### ISSUE TITLE
scrypt: maxmem ignored when N >= 65536**r

### ISSUE THREAD

**Issue by bnoordhuis** [openssl/openssl#10003]
Originally reported at https://github.com/nodejs/node/issues/29686 against openssl 1.1.1c.

`EVP_PBE_scrypt()` does not seem to respect the `maxmem` parameter under certain conditions. The bug report mentions `N=2**18, p=8, r=1`.

To my understanding, the canonical scrypt algorithm's memory usage is roughly `128*N*p*r`. Thus, the parameters should work when e.g `maxmem=300 * 2**20` because `128 * 2**18 * 8 * 1` equals `256 * 2**20`.

Instead however they are rejected with `EVP_R_MEMORY_LIMIT_EXCEEDED` because of this check:
https://github.com/openssl/openssl/blob/7c2a981ff7ca721a85687dcd972d54361434806f/providers/default/kdfs/scrypt.c#L382-L387

I'm unsure whether this is intentional or an oversight, hence why I'm filing this issue. If this is intentional, a note in the man page might be good.

My apologies if it's been discussed before. I searched the bug tracker and openssl-users@ but came up empty-handed.

**Comment by bnoordhuis** [comment]
Oh, and if I can interject a side question: am I right that openssl uses `128*p*r + 128*(2+N)*r` rather than the canonical equation?

I ask because that's the minimum number of bytes needed to compute e.g. `N=2**18, p=8, r=2`.

**Comment by paulidale** [comment]
This isn't a bug.

According to the RFC:

> The CPU/Memory cost parameter N ("costParameter") must be larger than 1, a power of 2, and less than 2^(128 * r / 8).

2^(128 * 1 / 8) = 65536.  Your N is larger than this, so the fail is mandated.
