### ISSUE TITLE
X509  -> cert_info -> key -> public_key not accessible 

### ISSUE THREAD

**Issue by phani-learner** [openssl/openssl#10010]
While porting an application to OpenSSL 1.1.1, I found that the cert_info struct member that was previously freely accessible for X509 data types seems now no longer accessible by any means.

My application directly access the data types so i'm replacing with get functions
For example 
To access sha1_hash I've used X509_digest 
but i'm not able to find how to access X509 -> cert_info -> key -> public_key

Can anyone let me know please

**Comment by phani-learner** [comment]
Also I want to know a get function to access 
 X509->cert_info->signature->algorithm

**Comment by mattcaswell** [comment]
There are a number of ways to get the public key data.

You can call:

X509_get_pubkey()

Which return the public key data as an EVP_PKEY.

Or you can call:

X509_get0_pubkey_bitstr()

Which returns the public key as an ASN1_BIT_STRING type.

Or you can call:

X509_get_X509_PUBKEY()

Which returns an X509_PUBKEY type. Once you have that you can call:

X509_PUBKEY_get0_param()

To get the public key bytes and length.

**Comment by mattcaswell** [comment]
> X509->cert_info->signature->algorithm

To get the X509->cert_info->signature data you can call:

X509_get0_tbs_sigalg()

This returns an X509_ALGOR type. From there you can call X509_ALGOR_get0() to get the ASN1_OBJECT for the algorithm.

**Comment by phani-learner** [comment]
Thank you so much :)
