### ISSUE TITLE
 ssl.SSLError: [SSL] malloc failure - with openssl=1.1.1d (ppc64le)

### ISSUE THREAD

**Issue by rjknight** [openssl/openssl#10015]
I originally commented in this conda issue: https://github.com/ContinuumIO/anaconda-issues/issues/11274, but after a little debug I decided to report the issue here as well.

Currently to reproduce the error I have been using a default conda environment with python 3.6 or 3.7 installed:

```
conda create -y -n my-test-env python=3.6
```
then running the following command
```
python -c 'import urllib.request; urllib.request.urlopen("https://pypi.org")'
```
which produces the following error:
```
(my-test-env) [builder@b98996cfec6a ~]$ python -c 'import urllib.request; urllib.request.urlopen("https://pypi.org")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/urllib/request.py", line 1286, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/http/client.py", line 1392, in __init__
    context = ssl._create_default_https_context()
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/ssl.py", line 502, in create_default_context
    context = SSLContext(PROTOCOL_TLS)
  File "/opt/anaconda3/envs/my-test-env/lib/python3.6/ssl.py", line 391, in __new__
    self = _SSLContext.__new__(cls, protocol)
ssl.SSLError: [SSL] malloc failure (_ssl.c:2805)
```
at this point, I don't have a test case without conda or python, but would be willing to write/test any suggested code to isolate the issue in ppc64le env.

I did poke around a little in the openssl code, using git bisect I narrowed it down to commit openssl/openssl@3ff98f5 as causing the problem, see openssl/openssl#9595 for details on the commit.
I disabled the change by setting -DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1 as suggested in the PR and was able to run the previously failing test successfully.

I made the following change in build.sh:
```
 diff --git a/recipe/build.sh b/recipe/build.sh
index a6cb10d..2155c45 100644
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -29,7 +29,7 @@ if [[ ${_BASE_CC} == *-* ]]; then
       ;;
     *powerpc64le-*linux*)
       _CONFIG_OPTS+=(linux-ppc64le)
-      CFLAGS="${CFLAGS} -Wa,--noexecstack"
+      CFLAGS="${CFLAGS} -Wa,--noexecstack -DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1"
       ;;
     *darwin*)
```
I don't think I have enough context regarding the change to figure out the root cause.

[openssl-config-data-dump.txt](https://github.com/openssl/openssl/files/3652871/openssl-config-data-dump.txt)

**Comment by kroeckx** [comment]
Which platform are you seeing that on?

**Comment by rjknight** [comment]
I am running on a power 9 system inside a container with the following: 
```
(base) [builder@b98996cfec6a pytorch]$ uname -a                                                                                                                                 
Linux b98996cfec6a 4.14.0-115.6.1.el7a.ppc64le #1 SMP Wed Feb 13 14:33:32 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

(base) [builder@b98996cfec6a pytorch]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
<snip>
```
as a note: if I run the same test on an x86_64 system (w/RHEL7.6 container) I don't see the failure

**Comment by stevehaertel** [comment]
I am also seeing it on:

```root@hostname:~# arch
ppc64le
root@hostname:~# uname -a
Linux hostname 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:01:41 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
root@hostname:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial```

**Comment by sh1ng** [comment]
```
# uname -a
Linux 7aa0728cab64 4.14.0-115.10.1.el7a.ppc64le #1 SMP Wed Jun 26 09:32:17 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7:server"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

**Comment by kroeckx** [comment]
I think the current code expects to be able to find getrandom() on a recent kernel, but that you have outdated libc and kernel headers that cause it to not be picked up.

If you try "strace openssl rand 1", do you see either a call to getrandom(), or trying to open /dev/urandom?

If I disable getrandom() support, "openssl rand 1" returns this for me:
```
140736378849120:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
140736378849120:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
140736378849120:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
140736378849120:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
140736378849120:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
140736378849120:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
140736378849120:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
140736378849120:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
```

I think the "Check the kernel's version and fail if it is too recent." might not be a good idea. If we get there on a new kernel, we'll always fail.

@bernd-edlinger: Care to comment on this?

**Comment by kroeckx** [comment]
At least one workaround is to add a define for __NR_getrandom for other platforms. For ppc* it seems to be 359.

I see:
ppc32:#define __NR_getrandom               359
ppc64:#define __NR_getrandom               359
x86:#define __NR_getrandom          355
mips32:#define __NR_getrandom                      (__NR_Linux + 353)
amd64:#define __NR_getrandom          318
s390x:#define __NR_getrandom               349
arm:#define __NR_getrandom                  384
arm64:#define __NR_getrandom 278
mips64 (N64?):#define __NR_getrandom              (__NR_Linux + 313)
mips64 (N32):#define __NR_getrandom               (__NR_Linux + 317)

There are still many others not listed here.

**Comment by rjknight** [comment]
> If you try "strace openssl rand 1", do you see either a call to getrandom(), or trying to open /dev/urandom?

using 1.1.1d I see the following error 
```
130140736342674976:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
130140736342674976:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
117140736342674976:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
130140736342674976:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
130140736342674976:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
117140736342674976:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
130140736342674976:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
117140736342674976:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
```
if I use 1.1.1c there is an access of `/dev/urandom`
```
open("/dev/random", O_RDONLY)           = 3
_newselect(4, [3], NULL, NULL, NULL)    = 1 (in [3])
close(3)                                = 0
open("/dev/urandom", O_RDONLY)          = 3
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
```

**Comment by bernd-edlinger** [comment]
Alright, seems the problem with the outdated kernel headers is not only a theoretical one.
We need to supply our own define here.  I did that for all kernel versions I am able to test with.
I would like that to be done by people who are able to test that specific kernel.

**Comment by kroeckx** [comment]
I have access to most if not all architecutes supported by Debian,
so I should be able to test them.

But I think that if we're going to treat 4.8 as special, we should
add the define for all architectures supported by 4.8. Archituctures
added afterwards will always have it in the kernel headers.

**Comment by bernd-edlinger** [comment]
Right, the point with v4.8 is that the entropy generator was re-designed in v4.8
due to critics by Daniel Bernstein, and by that re-design it unfortunately broke
the assumption that the /dev/urandom is initialized when /dev/random is readable
for the first time.

**Comment by richsalz** [comment]
I do not think we should add the define's, I think Debian should.  Or we have it in a NOTES file.  Suppose we get the number wrong?

**Comment by kroeckx** [comment]
Debian stable and unstable have the proper defines. But there
clearly are people who don't have them.

**Comment by bernd-edlinger** [comment]
That's why I did only add syscall numbers which I can personally verify.
I think we should only take the risk for systems which are used really often,
and where bad cross-toolchains are known to be circulating as in this case.

**Comment by kroeckx** [comment]
Even oldstable has them. I was planning to do a test building this
on oldstable, but even that is too recent. I need oldoldstable
which ships a 3.16 kernel, and so has 3.16 kernel headers.

(Or I change something so the kernel headers don't get included.)

I only talk about Debian because I have access to all Debian
development machines, and there should be one for each archicture.
At least the release architectures should have one I can just ssh
in, the others might require me ask to set up an account.

**Comment by bernd-edlinger** [comment]
The only reasonable way how this can happen is when you are targeting
your cross compiler for an old linux/glibc version, then you have no other
choice than to use linux/glibc headers, and libraries from before 2013.
Once you have this toolchain running it will produce binaries that run
on any system version newer than the sys-root files.
So people will just use it.
IF you do it with brand new glibc files your binaries will only run on
new glibc versions, due to the glibc being only upward compatible
not downward compatible.

**Comment by richsalz** [comment]
I think a NOTES.DEBIAN file created by Kurt who is a Debian maintainer is the best and safest way to go.  It's not hard to add -D__NR_getrandom=359 to your config line.  And there is a risk that someone will get their OS indirectly.  Are we confident, for example, that Ubuntu hasn't changed anything here?

**Comment by bernd-edlinger** [comment]
No they won't change that number.

**Comment by kroeckx** [comment]
Note that they all run in a chroot/container/whatever that only
has old files. It probably contains an old libc and kernel
headers. But the host system runs a recent kernel. This doesn't
even have to do with cross compilation, just targeting old
systems. And it breaks if you run it on a new kernel.

So people that upgrade the kernel will suddenly see their system
break, because the binary was build on an old system that didn't
know anything about that system call.

I really only see 2 options:
- We add the defines for the system call (for all systems we can test)
- We stop treating 4.8 as something that requires the system call.

**Comment by bernd-edlinger** [comment]
Option 1 sounds more safe.
The problem with Option 2 is that reading /dev/random does not
give you a guarantee that the CRNG is properly initialized with 4.8 and above.
Option 3 print something on the console and ask user for permission to continue.

**Comment by kroeckx** [comment]
I don't think option 3 is something a library should do.

**Comment by rjknight** [comment]
I was able to build an openssl conda-package using commit https://github.com/openssl/openssl/commit/eee565ec4b8509b53ee280e8f37243bc5cb5f535 and I no longer see the failure I was seeing.

Thank you!

**Comment by arkadiyt** [comment]
Also seeing this issue - compiling nginx with openssl 1.1.1c it works, but using 1.1.1f nginx fails to boot with the `RAND_DRBG_instantiate:error retrieving entropy` error. This is on a raspberry pi (`4.19.97-v7+` kernel), inside a docker "scratch" container (so no /dev/random or /dev/urandom available, but I get the same error even if I mount the host /dev/[u]random into the container)

**Comment by bernd-edlinger** [comment]
ask Google to fix this.

Thank You.
