### ISSUE TITLE
openssl-1.1.0-pre5   OCSP_SINGLERESP_add1_ext_i2d  add SCT data error

### ISSUE THREAD

**Issue by elitetony** [openssl/openssl#1001]
Hi:
  I tried to add the SCT data which Extract from x509v3 with extension scts into ocsp response extension ,but  failed. Could you tell me how to sign response with sct extension . thank you very much!

STACK_OF(SCT) * scts = (STACK_OF(SCT) *)X509_get_ext_d2i(x509, NID_ct_precert_scts, NULL, NULL);
		if (scts == NULL)
		{
			printf("get error\n");
		}
	   
		OCSP_SINGLERESP *single;
		single = OCSP_basic_add1_status(bs, cid, status, 0, NULL, thisupd, nextupd);

		int iret = OCSP_SINGLERESP_add1_ext_i2d(single, NID_ct_cert_scts, scts , 0, 0);
		printf("signed iret :%d \n", iret);

Program terminated with signal 11, Segmentation fault.
#0  0x00007f4a53490f64 in i2o_SCT_LIST () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6_5.4.x86_64
(gdb) bt
#0  0x00007f4a53490f64 in i2o_SCT_LIST () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#1  0x00007f4a53490ff7 in i2o_SCT_LIST () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#2  0x00007f4a534910c9 in i2d_SCT_LIST () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#3  0x00007f4a53583b9d in do_ext_i2d () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#4  0x00007f4a5358739f in X509V3_add1_i2d () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1

**Comment by mattcaswell** [comment]
Ping @benlaurie - can you provide some input here?

**Comment by richsalz** [comment]
@elitetony, Can you post the cert?

**Comment by RJPercival** [comment]
Having the certificate, so I can reproduce this, would be very helpful.

**Comment by RJPercival** [comment]
I've found the problem - putting together a fix now.

**Comment by mattcaswell** [comment]
Fixed at a9da48157. Closing.
