### ISSUE TITLE
Deprecate RAND method stuff

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10017]
Should we deprecate the RAND_method datatypes and API's? This will cause issues for some tests, which want to use a fixed byte-stream for random numbers, but we can work around that.

See also #6829

A related question, do we expect FIPS_MODE to work if the deprecated API's are enabled?

**Comment by levitte** [comment]
We've talked elsewhere that we want to make the RAND API providable, so deprecating method related stuff might not be the smartest move...

**Comment by richsalz** [comment]
API's to deprecate include:
```
ENGINE_get_RAND
ENGINE_get_default_RAND
ENGINE_register_RAND
ENGINE_register_all_RAND
ENGINE_set_RAND
ENGINE_set_default_RAND
ENGINE_unregister_RAND
RAND_OpenSSL
RAND_get_rand_method
RAND_set_rand_engine
RAND_set_rand_method
```

Engines should no longer do random, they should feed entropy into the DRBG.

**Comment by beldmit** [comment]
I'm against this idea. Cryptocom's commercial product includes custom RAND method and can't be certified without it.

**Comment by richsalz** [comment]
I think OpenSSL should standardizing on the DRBG model.  We can implement it in providers as the FIPS discussion is showing.

**Comment by levitte** [comment]
Not my strongest point, so I'll defer to @paulidale, @slontis, @mattcaswell and @mspncp

**Comment by beldmit** [comment]
> I think OpenSSL should standardizing on the DRBG model. We can implement it in providers as the FIPS discussion is showing.

I do not see a major difference between the engine and provider models here. We need to completely control the RNG algorithm (not data!) for our certification purpose. If it is possible, it's OK.

**Comment by richsalz** [comment]
I think Dmitry's comment, https://github.com/openssl/openssl/issues/10017#issuecomment-535087384, marks this as not feasible for this release.  Although since it would be *deprecated* and not *removed* maybe it's okay?

**Comment by beldmit** [comment]
Sorry, I hardly feel the difference. 

If we deprecate it with an intention other than removing, then what advantages we will get from the new API? If we deprecate it with an intention to remove, how non-US products will be able to base on OpenSSL?

**Comment by levitte** [comment]
Oh, it's *that* stuck with the RAND API?

**Comment by richsalz** [comment]
Deprecate means two things:
1. this is going to go away, probably in the next release
1. you have to take explicit configuration action to enable it

**Comment by levitte** [comment]
> you have to take explicit configuration action to enable it

I'm not sure what you're trying to say there...

**Comment by richsalz** [comment]
typo, should be "disable" it.  or make sure not to do "no-deprecated"

**Comment by levitte** [comment]
So basically, with a normal configuration, nothing changes, apart from some compilers warning you that the deprecated symbols are going away some day...

**Comment by paulidale** [comment]
The RAND and DRBG code needs to be moved into the providers.

There has been a suggestion that these old APIs could likewise moved into a provider engine loader.  Something Shane and I will start looking into in the coming weeks.

I'm not against deprecating them as well.

**Comment by levitte** [comment]
> There has been a suggestion that these old APIs could likewise moved into a provider engine loader.

I'm curious to see what that means in practical terms.  An application that uses those APIs will still want to link with something to access them, and provider modules aren't designed to be libraries, so my brain goes "huh?"...

**Comment by paulidale** [comment]
We were thinking more as a built in provider -- these calls become isolated from the rest of libcrypto but are usable by linking with it.  @slontis and I will try come up with some ideas.

**Comment by paulidale** [comment]
This isn't going to happen for 3.0.  We don't have a suitable replace for the `RAND_get_rand_method` and `RAND_set_rand_method` calls.

These are used to override the built in RAND infrastructure -- e.g. hardware RNG that is certified and faster than the DRBGs which should be used in preference to the inbuilt trio of DRBGs.  We currently don't have a way to do this.  At least, not without a lot of mucking around in obscure ways.

**Comment by richsalz** [comment]
Duplicate of #13126, so closing this.

**Comment by jiapei100** [comment]
All deprecated methods() are now replaced to what?
Isn't there a documentation for the replacement?

**Comment by paulidale** [comment]
Try the [migration guide](https://www.openssl.org/docs/manmaster/man7/migration_guide.html).
