### ISSUE TITLE
Building OpenSSL in Visual Studio?

### ISSUE THREAD

**Issue by alexander-novo** [openssl/openssl#1002]
All of the guides I can find (including [the official openssl wiki](https://wiki.openssl.org/index.php/Compilation_and_Installation#Windows)) mention using ms\do_win64a and ms\nt.mak, but as of 753585b94897f5628cf9c13d8a6c97861074febb, those files aren't available anymore. A "unified scheme" is mentioned, but I can't figure out what that refers to. How would one compile OpenSSL for linking in VC++ nowadays?

**Comment by levitte** [comment]
Might I suggest reading `INSTALL`?

**Comment by alexander-novo** [comment]
Following those instructions ends in the error 

    crypto\chacha\chacha-x86_64.asm(1755) : 
    error A2070:invalid instruction o?NMAKE : fatal error U1077: 
    '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\ml64.EXE"' :
    return code '0x1'"

**Comment by levitte** [comment]
Did you notice that it says this in the beginning?

```
 For additional platform specific requirements and other details,
 please read one of these:

  * NOTES.VMS (OpenVMS)
  * NOTES.WIN (any Windows except for Windows CE)
```

and if you did, did you also read `NOTES.WIN`?

**Comment by mattcaswell** [comment]
This looks like nasm not being present on the path...I thought we changed things to detect that and abort if that was the case?

**Comment by levitte** [comment]
Hmm, it should...

**Comment by levitte** [comment]
I just checked, and it does complain to me...  so @alexander-novo, would you mind telling us the origin of your source?  Is it a tarball you downloaded, and in that case which?  If not, I suppose it's master, but is it a fresh pull?  If not, I'd do a fresh pull and checkout

**Comment by levitte** [comment]
@alexander-novo , are your problems resolved?  Can this issue be closed?

**Comment by alexander-novo** [comment]
Yes - I was using OpenSSL 1.1.0-pre5, but doing a clone on the current repository gives me the warning about NASM. Now (with NASM installed), I get this error:

    crypto\bio\bio_lib.c(101) : error C2065: 'BIO_F_BIO_SET' : undeclared identifier

    NMAKE : fatal error U1077: 'cl' : return code '0x2'
    Stop.

**Comment by levitte** [comment]
Yup, fix coming up as soon as it's passed review.

**Comment by levitte** [comment]
Fix pushed.  Refresh your repo and try again

**Comment by alexander-novo** [comment]
So close!

    C:\openssl>nmake install
    
    Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    *** Installing development files
    created directory `C:/Program Files/OpenSSL'
    created directory `C:/Program Files/OpenSSL/include'
    created directory `C:/Program Files/OpenSSL/include/openssl'
    Destination must be a directory at .\util\copy.pl line 46.
    NMAKE : fatal error U1077: 'C:\Perl64\bin\perl.exe' : return code '0x2'
    Stop.

**Comment by levitte** [comment]
Would you mind trying the patch from #1023?

**Comment by alexander-novo** [comment]
The patch works. Thank you very much! I look forward to using OpenSSL in the future.
