### ISSUE TITLE
OpenSSL failed to nmake due to error LNK2019: unresolved external symbol _gcm_init_clmul referenced in function _CRYPTO_gcm128_init on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [openssl/openssl#10027]
Environment:
Windows Server 2016 + VS2017 + openssl master branch latest source code.

Issue description:
I tried to build openssl using VS2017 on Windows Server 2016. We found that openssl failed to nmake due to error LNK2019: unresolved external symbol _gcm_init_clmul referenced in function _CRYPTO_gcm128_init. It can be reproduced on latest master revision a6dd3a3. And it can build pass on revision 3b2f8c7. Could you please help take a look at this? Thanks in advance!

Repro steps:
1. git clone https://github.com/openssl/openssl D:\openssl\src
2. cd D:\openssl\src
3. perl Configure VC-WIN32
4. nmake clean
5. where cl.exe
6. nmake

[log_x86_build_2.log](https://github.com/openssl/openssl/files/3656920/log_x86_build_2.log)

Actual result:
libcrypto-shlib-gcm128.obj : error LNK2019: unresolved external symbol _gcm_init_clmul referenced in function _CRYPTO_gcm128_init
libcrypto-shlib-gcm128.obj : error LNK2019: unresolved external symbol _gcm_gmult_clmul referenced in function _CRYPTO_gcm128_init
libcrypto-shlib-gcm128.obj : error LNK2019: unresolved external symbol _gcm_ghash_clmul referenced in function _CRYPTO_gcm128_init
libcrypto-3.dll : fatal error LNK1120: 3 unresolved externals
NMAKE : fatal error U1077: 'link' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
[command took 448 seconds]

**Comment by spacelg** [comment]
Hi All,

Could someone look at this issue? It still can be reproduced on latest master revision.  Thanks in advance!

Thanks,
Lin

**Comment by FdaSilvaYY** [comment]
@spacelg : please send the ouput of `perl configdata.pm --dump`.

I remember seeing this recently too.

**Comment by matbech** [comment]
It's problem the same issue as here:
https://github.com/openssl/openssl/issues/10075
Also includes a workaround.

**Comment by spacelg** [comment]
@FdaSilvaYY  Thanks for your reply. Output of perl configdata.pm --dump as below:

Command line (with current working directory = .):

    C:\Perl\bin\perl.exe Configure VC-WIN32

Perl information:

    C:\Perl\bin\perl.exe
    5.24.1 for MSWin32-x86-multi-thread-64int

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    fips
    gost
    idea
    legacy
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    padlockeng
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    uplink
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    ktls                    [default]   OPENSSL_NO_KTLS
    afalgeng                [not-linux]
    asan                    [default]   OPENSSL_NO_ASAN
    buildtest-c++           [default]
    crypto-mdebug           [default]   OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]   OPENSSL_NO_EGD
    external-tests          [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]   OPENSSL_NO_FUZZ_AFL
    md2                     [default]   OPENSSL_NO_MD2 (skip crypto\md2)
    msan                    [default]   OPENSSL_NO_MSAN
    rc5                     [default]   OPENSSL_NO_RC5 (skip crypto\rc5)
    sctp                    [default]   OPENSSL_NO_SCTP
    ssl-trace               [default]   OPENSSL_NO_SSL_TRACE
    trace                   [default]   OPENSSL_NO_TRACE
    ubsan                   [default]   OPENSSL_NO_UBSAN
    unit-test               [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]
    zlib-dynamic            [default]
    ssl3                    [default]   OPENSSL_NO_SSL3
    ssl3-method             [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "lib",
    ARFLAGS => "/nologo",
    AS => "nasm",
    ASFLAGS => "",
    CC => "cl",
    CFLAGS => "/W3 /wd4090 /nologo /O2 /WX",
    CPP => "\$(CC) /EP /C",
    HASHBANGPERL => "/usr/bin/env perl",
    LD => "link",
    LDFLAGS => "/nologo /debug",
    MT => "mt",
    MTFLAGS => "-nologo",
    RANLIB => "CODE(0x25d6ac4)",
    RC => "rc",
    aroutflag => "/out:",
    asflags => "-f win32",
    asm_arch => "x86",
    asoutflag => "-o ",
    bin_cflags => "/Zi /Fdapp.pdb",
    bin_lflags => "/subsystem:console /opt:ref",
    bn_ops => "BN_LLONG",
    build_file => "makefile",
    build_scheme => [ "unified", "windows", "VC-common", "VC-WOW" ],
    cflags => "/Gs0 /GF /Gy /MD",
    coutflag => "/Fo",
    cppflags => "",
    defines => [ "OPENSSL_SYS_WIN32", "WIN32_LEAN_AND_MEAN", "UNICODE", "_UNICODE", "_CRT_SECURE_NO_DEPRECATE", "_WINSOCK_DEPRECATED_NO_WARNINGS" ],
    disable => [  ],
    dso_cflags => "/Zi /Fddso.pdb",
    dso_scheme => "win32",
    enable => [  ],
    ex_libs => "ws2_32.lib gdi32.lib advapi32.lib crypt32.lib user32.lib",
    includes => [  ],
    ldoutflag => "/out:",
    lflags => "",
    lib_cflags => "/Zi /Fdossl_static.pdb",
    lib_cppflags => "",
    lib_defines => [ "L_ENDIAN" ],
    module_cflags => "",
Use of uninitialized value $x in substitution (s///) at configdata.pm line 16561.
Use of uninitialized value $x in concatenation (.) or string at configdata.pm line 16561.
    module_cxxflags => "",
    module_ldflags => "/dll",
    mtinflag => "-manifest ",
    mtoutflag => "-outputresource:",
    perl_platform => "Windows::MSVC",
    perlasm_scheme => "win32n",
    rcoutflag => "/fo",
    shared_cflag => "",
    shared_defflag => "",
    shared_defines => [  ],
    shared_ldflag => "/dll",
    shared_rcflag => "",
    shared_target => "win-shared",
    sys_id => "WIN32",
    thread_defines => [  ],
    thread_scheme => "winthreads",
    unistd => "<unistd.h>",
    uplink_arch => "common",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = lib
    ARFLAGS         = /nologo
    AS              = nasm
    CC              = cl
    CFLAGS          = /W3 /wd4090 /nologo /O2 /WX
    CPP             = $(CC) /EP /C
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LD              = link
    LDFLAGS         = /nologo /debug
    LDLIBS          =
    MT              = mt
    MTFLAGS         = -nologo
    PERL            = C:\Perl\bin\perl.exe
    RANLIB          = ranlib
    RC              = rc
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    makefile

build file:

    makefile

build file templates:

    Configurations\common0.tmpl
    Configurations\windows-makefile.tmpl
    Configurations\common.tmpl

Thanks,
Lin

**Comment by FdaSilvaYY** [comment]
I can confirm https://github.com/openssl/openssl/issues/10075#issuecomment-542722966 .
Running _Configure_ with **-DOPENSSL_IA32_SSE2** : 
    `perl Configure ... -DOPENSSL_IA32_SSE2`
fix Visual Studio builds.

**Comment by FdaSilvaYY** [comment]
I confirm that #10222 fully fix this issue, with commit 
 de1581988f4a6b6e25f1e01474c63dc55f004c2a :  **"windows-makefile.tmpl: Convert all /I and /D to -I and -D"**

**Comment by levitte** [comment]
Cool.  Closing this
