### ISSUE TITLE
[docs] EVP_DigestInit clears all flags

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#10031]
The ``EVP_DigestInit`` function is documented as

> Behaves in the same way as EVP_DigestInit_ex() except it always uses the default digest implementation.

That's not entirely correct. The function also calls ``EVP_MD_CTX_reset`` prior to calling ``EVP_DigestInit_ex``. The reset function clears the struct with ``OPENSSL_cleanse``, which effectively also clears all flags. This behavior broke my CPython patch https://github.com/python/cpython/pull/16418 that added support for ``EVP_MD_CTX_FLAG_NON_FIPS_ALLOW`` flag. I worked around the problem by using ``EVP_DigestInit_ex`` instead.

I think this fact is worth mention in the docs.

> Behaves in the same way as EVP_DigestInit_ex() except it always uses the default digest implementation and resets all flags.

**Comment by t8m** [comment]
Please note that the EVP_MD_CTX_FLAG_NON_FIPS_ALLOW flag support is Fedora/Red Hat downstream patch. In upstream sources the flag has no effect. But anyway the discrepancy between docs and implementation in regards to the EVP_MD_CTX_reset() call is there.
