### ISSUE TITLE
please check man page about  SSL_CTX_set_stateless_cookie_generate_cb

### ISSUE THREAD

**Issue by simplelins** [openssl/openssl#10030]
plese check this page: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_stateless_cookie_generate_cb.html

It is unclear when I  want to get how to use TLS1.3 extension about cookie. 
 SSL_CTX_set_cookie_generate_cb and SSL_CTX_set_cookie_verify_cb need to be added, there are no any descriptions about SSL_CTX_set_stateless_cookie_generate_cb and SSL_CTX_set_stateless_cookie_verify_cb

**Comment by mattcaswell** [comment]
I'm not sure I understand your question. The man page seems quite clear to me (but then I wrote it so I am probably blind to its deficiencies). Did you also read the SSL_stateless() man page (which is linked from the callback man page you referenced above):

https://www.openssl.org/docs/man1.1.1/man3/SSL_stateless.html

These two man pages need to be read together to understand how this mechanism works.

**Comment by simplelins** [comment]
The synopsis are about SSL_CTX_set_stateless_cookie_generate_cb and SSL_CTX_set_stateless_cookie_verify_cb , but description are about SSL_CTX_set_cookie_generate_cb and SSL_CTX_set_cookie_verify_cb. both set different fileds.

**Comment by simplelins** [comment]
> I'm not sure I understand your question. The man page seems quite clear to me (but then I wrote it so I am probably blind to its deficiencies). Did you also read the SSL_stateless() man page (which is linked from the callback man page you referenced above):
> 
> https://www.openssl.org/docs/man1.1.1/man3/SSL_stateless.html
> 
> These two man pages need to be read together to understand how this mechanism works.

The synopsis are about SSL_CTX_set_stateless_cookie_generate_cb and SSL_CTX_set_stateless_cookie_verify_cb , but description are about SSL_CTX_set_cookie_generate_cb and SSL_CTX_set_cookie_verify_cb. both set different fileds.

**Comment by mattcaswell** [comment]
Ah! Right - thanks. Now I understand the problem. I will update it.

**Comment by mattcaswell** [comment]
Please keep this open, until I've actually committed a fix.

**Comment by simplelins** [comment]
> Please keep this open, until I've actually committed a fix.

ok
