### ISSUE TITLE
Windows test in AppVeyor builds are break.

### ISSUE THREAD

**Issue by FdaSilvaYY** [openssl/openssl#1003]
AFAIK, it seems that this commit a043d0b91d62fd8526a3fd791e3ad2ebcf888c
break all the SSL tests on AppVeyor .

Last good build: https://ci.appveyor.com/project/openssl/openssl/build/master.2741
Fist KO build: https://ci.appveyor.com/project/openssl/openssl/build/master.2745

Is there any fix in the team review pipe, or a revert is ongoing ?

**Comment by levitte** [comment]
Thanks, apparently we were busy with other stuff and lost our attention on Appveyor...  will check later today

**Comment by levitte** [comment]
I did some checking around and found what caused it.  #1005 should clear it up.

**Comment by levitte** [comment]
Issue cleared
