### ISSUE TITLE
Can't build in windows 10

### ISSUE THREAD

**Issue by FabioNevesRezende** [openssl/openssl#10038]
Steps to reproduce:

```
git clone https://github.com/openssl/openssl
cd openssl

perl Configure VC-WIN64A no-shared  --openssldir="%CD%"\rel64 --prefix="%CD%"\rel64
nmake
```

Fails with: 

> C:\Users\fabio.rezende\Desktop\openssl\openssl\e_os.h(13): fatal error C1083: Não é possível abrir arquivo incluir: 'limits.h': No such file or directory

Complete error output:

> Microsoft (R) Program Maintenance Utility Versão 14.16.27034.0
> Direitos autorais da Microsoft Corporation. Todos os direitos reservados.
>         "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe" /                   _all
> 
> Microsoft (R) Program Maintenance Utility Versão 14.16.27034.0
> Direitos autorais da Microsoft Corporation. Todos os direitos reservados.
> 
> Microsoft (R) Program Maintenance Utility Versão 14.16.27034.0
> Direitos autorais da Microsoft Corporation. Todos os direitos reservados.
>         cl  /Zi /Fdossl_static.pdb /MT /Zl /Gs0 /GF /Gy /W3 /wd4090 /nologo /O2 /I "." /I "include" /I "apps\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"C:\\Users\\fabio.rezende\\Desktop\\openssl\\openssl\\rel64\"" -D"ENGINESDIR=\"C:\\Users\\fabio.rezende\\Desktop\\openssl\\openssl\\rel64\\lib\\engines-3\"" -D"MODULESDIR=\"C:\\Users\\fabio.rezende\\Desktop\\openssl\\openssl\\rel64\\lib\\ossl-modules\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG"   -c /Foapps\lib\libapps-lib-app_params.obj "apps\lib\app_params.c"
> app_params.c
> C:\Users\fabio.rezende\Desktop\openssl\openssl\e_os.h(13): fatal error C1083: Não é possível abrir arquivo incluir: 'limits.h': No such file or directory
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.EXE"' : código de retorno '0x2'
> Stop.
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe"' : código de retorno '0x2'
> Stop.
> 
>

**Comment by FabioNevesRezende** [comment]
Perl version: v5.30.0
Nasm version: NASM version 2.14.02 compiled on Dec 26 2018

**Comment by slontis** [comment]
Not sure if you need to setup the environment (variables) before invoking the VS compiler?
e.g <VS folder>/VC/vcvarsall.bat (Note the directory is different for amd64).

**Comment by mspncp** [comment]
Search the Start Menu. Visual Studio installs shortcuts for suitable developer command prompts for x86 and amd64.

**Comment by FabioNevesRezende** [comment]
So the problem occurs because I was trying to build it using the standart command prompt of windows. To build it correctly I had to access the Visual Studio command prompt and build it from there.

**Comment by laki9** [comment]
Start a visual studio command prompt  can resolve the issue
