### ISSUE TITLE
OpenSSL Error

### ISSUE THREAD

**Issue by Milav-teq** [openssl/openssl#10035]
Hello Guys,

This is Milav Soni.

I download opessl-master from this [link](https://github.com/openssl/openssl).

and i am able to cross-compilation openssl.
after this i am attach openssl include path and library path to Mosquitto library.

But when i run mosuitto_pub command on my custom board than it gives following error.

"OpenSSL Error: error:14000086:SSL routines::certificate verify failed
Error : A TLS error occurred." 

please help me to sort out this error.

**Comment by jayaram-intel** [comment]
Hi @Milav-teq

Please try with below option

--proxy
Specify a SOCKS5 proxy to connect through. "None" and "username" authentication types are supported. The socks-url must be of the form socks5h://[username[:password]@]host[:port]. The protocol prefix socks5h means that hostnames are resolved by the proxy. The symbols %25, %3A and %40 are URL decoded into %, : and @ respectively, if present in the username or password.

Example : jram@edison:~# mosquitto_sub --cafile rootCA.pem --cert tomato.cert.pem --key tomato.private.key -h (Imnotgiving myend point).iot.us-east-1.amazonaws.com -p 8883 -q 1 -d -t topic/test -i clientid2

If it's works fine then Please close this issue.

Thanks
Jayaram Matta

**Comment by Milav-teq** [comment]
Hello  Jayaram Matta,

It is worked.

thank you for your response.
