### ISSUE TITLE
Sending openssl connect request to same web server from two different clients using the session ticket generated from a client

### ISSUE THREAD

**Issue by Keerthanalaxmi** [openssl/openssl#10056]
I am using the openssl below command to generate and store the session ticket:

openssl s_client -sess_out cdn77_out -connect cdn77.com:443  -tls1_3 -servername www.cdn77.com
openssl s_client -sess_in cdn77_out -sess_out cdn77_out1 -connect cdn77.com:443  -tls1_3 -servername www.cdn77.com 

i am transfering the session ticket i got from the above command to a different client and expecuting the below command:

openssl s_client -sess_in cdn77_out -sess_out cdn77_out1 -connect cdn77.com:443  -tls1_3 -servername www.cdn77.com 

Connection is going as Reused. My expectation is it should be a new connection because it is a different client with different ip.

Please let me know if i am missing something.

**Comment by t8m** [comment]
There is no such requirement. You could have for example changed your dynamic IP address due to network disconnection/reconnection. There is no point in disallowing it. By using the sess_in/sess_out you are making the second client to act fully as the first client just with the IP address changed.
