### ISSUE TITLE
Consistent formatting of I<a:b> in manpages

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10060]
Many of our commands take a key/value pair -- host:port, opt:value, etc.

The proper formatting of this is apparently ```I<first>:I<second>```

While fixing those, should we also standardize on the terminology?  I see ```opt:value``` ```hostname:port``` ```paramset:X``` etc.  (Most of these you will not see until #10022 is merged).

**Comment by levitte** [comment]
I have to revise that what I said earlier. From careful read of man(1), it turns out that all parts of a command that should be typed in exactly as is should be bold. Therefore, `I<first>B<:>I<second>`.

(the question of variable option names is separate, FYI)

**Comment by richsalz** [comment]
I think @levitte and I fixed this now, closing.  Richard, please re-open if there's still some nits.
