### ISSUE TITLE
unresolved external symbol _gcm_ghash_clmul

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#10075]
Windows build (x86-Win32) with the master branch:
libcrypto-shlib-gcm128.obj : error LNK2001: unresolved external symbol _gcm_ghash_clmul
libcrypto-shlib-gcm128.obj : error LNK2001: unresolved external symbol _gcm_init_clmul
libcrypto-shlib-gcm128.obj : error LNK2001: unresolved external symbol _gcm_gmult_clmul
libcrypto-3.dll : fatal error LNK1120: 3 unresolved externals

**Comment by levitte** [comment]
Ah, I see why that happens. The MSVC command-line gets passed `/DOPENSSL_IA32_SSE2` rather than `-DOPENSSL_IA32_SSE2` and therefore fails to recognise it. 

Fix coming up!

**Comment by mspncp** [comment]
What about the remaining slashes? Shouldn't they be converted, too?

**git grep -n '/[A-Z]' -- Configurations/windows-makefile.tmpl | grep -w -e CC -e CPP**

[Configurations/windows-makefile.tmpl:602:](https://github.com/openssl/openssl/blob/238e4a35ac/Configurations/windows-makefile.tmpl#L602)       \$(CPP) $incs $cppflags $defs \$@.S > \$@.i && move /Y \$@.i \$@
[Configurations/windows-makefile.tmpl:615:](https://github.com/openssl/openssl/blob/238e4a35ac/Configurations/windows-makefile.tmpl#L615)       \$(CPP) $incs $cppflags $defs "$args{generator}->[0]" > \$@.i && move /Y \$@.i \$@
[Configurations/windows-makefile.tmpl:663:](https://github.com/openssl/openssl/blob/238e4a35ac/Configurations/windows-makefile.tmpl#L663)       \$(CC) /EP -D__ASSEMBLER__ $cflags $defs $srcs > \$@.asm && \$(AS) $asflags \$(ASOUTFLAG)\$\@ \$@.asm
[Configurations/windows-makefile.tmpl:671:](https://github.com/openssl/openssl/blob/238e4a35ac/Configurations/windows-makefile.tmpl#L671)       \$(CC) $cflags $defs /Zs /showIncludes $srcs 2>&1 > $dep

**Comment by mspncp** [comment]
Ups, the `move /Y` is a false positive. But the `/EP`, `Zs`, and `/showIncludes` are not.

**Comment by levitte** [comment]
Does it matter?

**Comment by mspncp** [comment]
> Does it matter?

Oh, this post should have gone to #10222. Nevertheless: no, it doesn't. I'll approve it without.
