### ISSUE TITLE
Suspend handshake on private key operations

### ISSUE THREAD

**Issue by rmdmr** [openssl/openssl#10083]
Is there a plan to add callbacks that can optionally suspend the handshake when private key operations are required (In the same way the handshake is suspended for certificate lookup). The main reason for this request is to provide only the private key computation results to the library and not the private key itself.

This concerns the CertificateVerify and ServerKeyExchange messages.

Thank you

**Comment by mattcaswell** [comment]
Sort of. OpenSSL 3.0 will introduce the concept of providers. A provider will enable you to offload crypto algorithm operations to third party code. So, for example, you could write a provider that implements RSA and does all the private key operations for RSA "somewhere else" and returns the result back. You can actually do something similar to this with the ENGINE interface today, but hopefully providers will make this a little less painful.

There is a question of how keys get loaded into providers in the first place. With the state of the code currently in master, keys get loaded by libcrypto and then passed to the provider - so libcrypto still sees the actual private keying material. We have had discussions about offloading the actual loading and saving of key data to providers too - but its not clear how much of that will make it into OpenSSL 3.0. If that does get implemented then you could do the whole operation without libcrypto ever seeing any private keying material.

**Comment by beldmit** [comment]
I have experience in creating an engine offloading the private key computations to a remote party. It works with 1.0.* and I think it is implementable with 1.1.* though some necessary accessors may be missing.

**Comment by richsalz** [comment]
It *can* be done using the async facility. Akamai does it -- all private key goes to a separate process.  Sorry we can't share the code.

**Comment by beldmit** [comment]
It can be done even without async facility, though it causes more problems than solves :)

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
