### ISSUE TITLE
restore non-negative return value of EVP_CIPHER_CTX_*() in master

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#10106]
Issue is mainly for EVP_CIPHER_CTX_ctrl() but review of history shows that may some other functions are impacted - start is commit 13273237a65d46186b6bea0b51aec90670d4598a , dated  Tue, 9 Jul 2019 07:32:16 +0200.

Before switch to provider most of public function are "boolean like", i.e. never return negative value and zero as error indicator. In consequence many projects use "if ( !foo() )" calls to check for error.

Changes in this are of widely user API is like to open "Pandora's box".
Please restore original "preprovider" functionality.

I also think that in case of error public function should return -1 or negative value but this could be done with new api EVP_XCIPHER...

**Comment by petrovr** [comment]
Issue is related to #9524 (aes{128|256}-gcm failures in master 2019-08-03) , i.e.  correction of this will expose right failure.

**Comment by levitte** [comment]
You're right.  PR coming up!

**Comment by levitte** [comment]
#10108

**Comment by petrovr** [comment]
Report was for fore then one function.
Unfortunately I did not have enough time to check current each function impacted by commit mentioned in first post. For instance quick review of commit shows changes in block size, length and etc.

Issues in control function are  more then one . - so I will comment in #10108 .
