### ISSUE TITLE
Refactor common options?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10115]
I would like to move much of the common command flags to the openssl.pod page.  We already do this for "-help" and "pass phrase" options.  I would like to do that for some others, including:
- -rand/-writerand
- -engine
- -inform,-outform, etc (just description of DER, PEM ,etc) 
- the "verify" options (verify_depth, etc) -- those that are in OPS_V_ENUM
- cafile, capath, no-cafile, no-cpath

With the main documentation written in only one place, we avoid cut/paste errors (look at the "-engine" comments for #10065 for example), and perhaps people will be encouraged to write more text.

Before doing this, I want to make sure the project is okay with it.

**Comment by richsalz** [comment]
BTW, I used this script:
```
for I in `./apps/openssl list --commands -1` ; do
  ./apps/openssl list --options $I
done | sort | uniq -c | sort -n
```

**Comment by t8m** [comment]
+1 from me

**Comment by levitte** [comment]
-config would be logical to centralise

**Comment by levitte** [comment]
I knew you'd pull a popularity contest...  as a matter of fact, implementors have simply been lazy and relied on `OPENSSL_CONF`, and in master, it's for good reason, since initialization (and therefore configuration file loading, according to decisions we've made) happens long before that option is parsed.

The challenge that the late configuration through `-config` poses could be fixed in one of two ways:

1.  implement early parsing of *global* options, where `-config` would be one.  We don't really have the concept of *global* options in the `openssl` command, so that's quite a bit of work.
2.  Remove the `-config` option entirely and rely on `OPENSSL_CONF` only.

**Comment by richsalz** [comment]
> I knew you'd pull a popularity contest..

Heh.  I also wonder how it impacts with the auto-initialization. @mattcaswell  ?

**Comment by richsalz** [comment]
Related PR's https://github.com/openssl/openssl/pull/10142, https://github.com/openssl/openssl/pull/10135, https://github.com/openssl/openssl/pull/10134, #10132, #10128, and #10118

**Comment by beldmit** [comment]
> I knew you'd pull a popularity contest... as a matter of fact, implementors have simply been lazy and relied on `OPENSSL_CONF`, and in master, it's for good reason, since initialization (and therefore configuration file loading, according to decisions we've made) happens long before that option is parsed.
> 
> The challenge that the late configuration through `-config` poses could be fixed in one of two ways:
> 
> 1. implement early parsing of _global_ options, where `-config` would be one.  We don't really have the concept of _global_ options in the `openssl` command, so that's quite a bit of work.
> 2. Remove the `-config` option entirely and rely on `OPENSSL_CONF` only.

If I understand correctly, at least `req` and `ca` commands have a specific semantics of the `config` option. So it can't be just removed.

**Comment by mattcaswell** [comment]
> Heh. I also wonder how it impacts with the auto-initialization.

Good question. In 3.0 we now auto-load a config file, so I'm not too sure what happens if you then try and load a different one later.

**Comment by levitte** [comment]
> Good question. In 3.0 we now auto-load a config file, so I'm not too sure what happens if you then try and load a different one later.

If there's an engine specified, there will be an error (or was it warning) because that config module detects double loading of the same engine...  I assume it's there in case there's a conflict between two config files, with different settings for the same engine.

**Comment by richsalz** [comment]
Should the auto-load and engine thread be split off into a new issue?  I think this one will be closed when the various refactoring PR's (#10259, #10191, #10134, #10132, and #10128) are the ones remaining at this point.

**Comment by levitte** [comment]
> so I'm not too sure what happens if you then try and load a different one later.

That's a non-issue.  The commands that use `-config` load it separately in their own `CONF` instances, which keeps them separate from the library configuration.

**Comment by richsalz** [comment]
this was done.
