### ISSUE TITLE
how to use rsa_ossl_public_encrypt() function in openssl-1.1.0-pre5 build.

### ISSUE THREAD

**Issue by asthaaggarwal** [openssl/openssl#1011]
Hi,

I have requirement to use RSA public encrypt function with SHA256, Before I was using "RSA_eay_public_encrypt" function which later changed to "rsa_ossl_public_encrypt()" function. Now I was trying to port the same function with latest openssl build but i m getting errors at:
BN_MONT_CTX_set_locked(&rsa->_method_mod_n, &rsa->lock, n, ctx)
Here i m not able to provide values at first and second parameter as RSA structure is not available and I m not able to find the equivalent APIs.

And sameway how to replace,
rsa->meth->bn_mod_exp(ret, f, e, n, ctx, rsa->_method_mod_n) this call.

**Comment by levitte** [comment]
From what you say, it seems like you're trying to re-implement `rsa_ossl_public_encrypt()` rather than *using* it...  In any case, the `_method_mod_*` RSA fields are internal for OpenSSL.

Quite frankly, this sounds like a usage problem rather than an issue with OpenSSL itself, and therefore doesn't belong here.  May I suggest you turn to the users list, openssl-users@openssl.org?

Closing this.

**Comment by levitte** [comment]
Subscription information here: https://www.openssl.org/community/mailinglists.html

**Comment by asthaaggarwal** [comment]
I don't want to re-implement it, but because rsa_ossl APIs are not available so i was trying to directly use the source code. My requirement is to use RSA public encrypt with SHA256.

**Comment by mattcaswell** [comment]
It sounds like you need to raise this question on the openssl-users list as suggested by @levitte. It is not clear what you are trying to do or why you need to access internal fields of the RSA structure to do it. It is also not clear why you were using rsa_ossl_public_encrypt() which is an *internal* function. The equivalent external function is RSA_public_encrypt(). RSA_public_encrypt() does not care what the data is that it is encrypting (subject to certain limitations such as size), so it could easily be a SHA256 hash.
