### ISSUE TITLE
Deprecate X9.31?

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#10111]
It seems we have public functions generate primes and RSA keys according to X9.31. But that standard has been withdrawn for a very long time. Is there a reason to keep them around?

**Comment by slontis** [comment]
Does CMS still use them?

**Comment by mattcaswell** [comment]
Deprecation seems reasonable to me.

**Comment by paulidale** [comment]
RSA functions are deprecated.  BN functions need to be.

**Comment by paulidale** [comment]
Should continue supporting the X9.31 padding scheme.
Not the prime generation.

**Comment by kroeckx** [comment]
So looking at it again, ANSI X9.31-1998 is withdrawn at least 10 years ago, you can't find it on the x9 website anymore, nor on the ANSI store, but there are places that still sell it.

So I'm talking about the RSA_*X931* and BN_X931* functions. The RSA functions are deprecated, the BN functions not.

There is also RSA_X931_PADDING, I'm fine with that staying.

**Comment by sahanaprasad07** [comment]
I would like to work on this task.
