### ISSUE TITLE
Dead link (1.0.2 man s_client)

### ISSUE THREAD

**Issue by dilyanpalauzov** [openssl/openssl#10133]
https://www.openssl.org/docs/man1.0.2/man1/openssl-s_client.html links under -sigalgs sigalglist to https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set1_sigalgs.html and the latter site does not exist.

**Comment by levitte** [comment]
Ah, that link was added in #3065, but the page it links to was never backported to 1.0.2 (or to 1.1.0 for that matter...).

**Comment by mspncp** [comment]
Closing this ticket, because version 1.1.0 is not supported anymore and version1.0.2 will only receive security fixes until it reaches EOL by the end of this year (seeour [release policy](https://www.openssl.org/policies/releasestrat.html)).
