### ISSUE TITLE
PREEMPTIVE: Please do not remove '-md sha1' symmetric encryption key derivation

### ISSUE THREAD

**Issue by mirage335** [openssl/openssl#10145]
Regarding OpenSSL 'enc' feature.

Please do not remove '-md sha1' and similar functionality.

Although the 'pbkdf2' feature is indeed useful, and I understand users should be strongly encouraged to use it, there are some situations in which it is definitely not necessary.

Version compatibility would become a significant issue. Older versions of OpenSSL do not support '-pbkdf2'. Removing support for '-md sha1' now would not allow software to support both the current and recent previous versions.

Specifically, this warning message raised concern.
```
echo test | openssl enc -e -aes-256-cbc -nosalt -md sha1 -pass pass:test  -out - -in - | xxd -p

*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.

ba03ee302f3d81ffcc4ff9e416b1f0b2
```

Of somewhat lesser concern: the warning message could require minor revisions to some complicated software using OpenSSL.

**Comment by kroeckx** [comment]
I don't see the purpose of this bug. We don't have any plans to remove it soon. At some point we will remove it. If at that point you still need to deal with files with sha1, I suggest you keep the old version around.

If someone feels like it's time to remove sha1, I doubt that they find this bug.

**Comment by mirage335** [comment]
Unnecessary API instability is a bug.

At the very least, there needs to be a commitment to six-year support, similar to the Debian release cycle, for the command line interface to OpenSSL symmetric encryption features. Because OpenSSL is security software, and is often updated more frequently than other distro-provided software, this stability **must** come from upstream.

Interoperability is paramount. IoT or mesh wireless communications may include routers/devices, which may need to be replaced (due to hardware failure) without replacing _all_ endpoints more often than absolutely necessary, or routinely building a fully custom OS. Over-the-air updates do not negate this need for this interoperability with older software versions - overusing such functionality also carries vulnerability risks. Operating transmit-only, or receiving only messages passing symmetric authentication, the need for updates may be extremely rare, given the vanishingly small attack surface associated with such limited functionality.

Performance must not be compromised where security is not affected. Key strengthening is useless in automated systems where large-entropy open-hardware generated (>512bit) keys are already used. Embedded devices using microcontrollers have little storage or processing power.

Ongoing cost-optimization and miniaturization shows embedded developers will have incentives to meet requirements at the expense of security for many more years.

Communications security is a diverse field.

> If at that point you still need to deal with files with sha1, I suggest you keep the old version around.
Keeping old versions does not solve the problem of binary distro breakage. Spinning up a fresh install of Gentoo for every embedded IoT router, building dedicated hardware modems, or leaving systems unpatched, are not good options.

> If someone feels like it's time to remove sha1, I doubt that they find this bug.
Then where should this issue be reported? Given its use as a dependency in other software packages, maybe it is time for OpenSSL to have an official policy regarding algorithm support?

**Comment by richsalz** [comment]
Maybe you should read https://www.openssl.org/policies/releasestrat.html.  "Version 1.1.1 will be supported until 2023-09-11 (LTS)."  LTS releases are supported for at least five years.

**Comment by kroeckx** [comment]
Note that we have LTS releases that are supported for 5 years, and
1.1.1 is an LTS release.

Also note that I said we currently don't have any plans to remove
it. But it's really insecure, it can probably be recovered in 1
hour, so maybe we really should consider removing it as soon as
possible. But giving the current policies, as soon as possible can
still take a very long time.

**Comment by mirage335** [comment]
Thank you for pointing out the LTS release policy. Guess I should have found that.

Nonetheless, I dispute the 'really insecure' and 'can probably be recovered in 1 hour' statements regarding SHA1 digest functionality.

Please clarify if there is a reason sha1 message digest would be 'really insecure' even with high-entropy keys. For automated communications security applications, low-entropy keys should already be considered absolutely unacceptable practice.

Eliminating existing functionality 'as soon as possible' provides an incentive not to use any security at all (eg. plaintext password hashing).

A possible compromise would be to disable message digest functionality when given inputs less than 96bits in length, forcing PBKDF2 where needed for security.

**Comment by kroeckx** [comment]
Note that you're talking about the "enc" command. This is
something people normally use to just encrypt a file with a (low
entropy) key.

**Comment by mirage335** [comment]
It is also one of the few, if not the only, widely deployed implementations of the basic algorithms which can be used to create a pure ciphertext output authenticated and encrypted message. For that purpose, it would be nice if the API remained highly stable.

IoT is quickly making wireless device vulnerability an already badly underserved and widespread problem.

**Comment by kroeckx** [comment]
You know that we have a library right? And that enc is just a tool
that calls some of the function in the library?

**Comment by mirage335** [comment]
Yes.

**Comment by levitte** [comment]
Looking back at this, this issue is a non-issue.  `-md` isn't removed at all, nor is the value `sha1`.  What this warning does say is you *should* use `-iter` or `-pbkdf2`, otherwise the old `EVP_BytesToKey()` functions will be used to derive the cipher key.

**Comment by mirage335** [comment]
'deprecated'
Implies a feature _will_ be removed.

The point of this bug is there are valid applications for this specific algorithm which are _unnecessarily_ broken if this implied intent is followed through.

**Comment by levitte** [comment]
Yes. It's just a bit misleading to talk about `-md sha1` being deprecated when it's in fact the use of `EVP_BytesToKey` that is.

**Comment by mattcaswell** [comment]
> Yes. It's just a bit misleading to talk about -md sha1 being deprecated when it's in fact the use of EVP_BytesToKey that is.

Right. The intent is to (eventually) remove EVP_BytesToKey. "-md sha1" would remain for the foreseeable future. Although, I note that we haven't actually deprecated the API itself yet, so its not going to be happening anytime soon.

**Comment by levitte** [comment]
> Although, I note that we haven't actually deprecated the API itself yet, so its not going to be happening anytime soon.

Deprecate it now, then?

**Comment by mattcaswell** [comment]
> Deprecate it now, then?

Yes, we should.

**Comment by richsalz** [comment]
I took a brief look at the source; what's the new way to do what ```EVP_BytesToKey``` does?

**Comment by mattcaswell** [comment]
You're supposed to use PBKDF2 instead. You can either use the older PKCS5_PBKDF2_HMAC() function, or even in better in 3.0 you can use the new KDF API via EVP_KDF_fetch().

**Comment by mirage335** [comment]
Will this deprecation of 'EVP_BytesToKey' allow the "-md sha1" feature continue to provide _exactly_ the same inputs and outputs as before?

Specifically, would the command mentioned in the original post to this issue continue to produce the _exact_ string 'ba03ee302f3d81ffcc4ff9e416b1f0b2' ?

`
echo test | openssl enc -e -aes-256-cbc -nosalt -md sha1 -pass pass:test  -out - -in - | xxd -p
`

**Comment by mattcaswell** [comment]
> Will this deprecation of 'EVP_BytesToKey' allow the "-md sha1" feature continue to provide exactly the same inputs and outputs as before?

*Deprecation* will allow it to continue. Eventual removal will not. Note that our stability policy applies:

> No API or ABI breaking changes are allowed in a minor or patch release. The following stability rules apply to all changes made to code targeted for a major release from version 3.0.0 or later:
>
> No existing public interface can be modified except where changes are unlikely to break source compatibility or where structures are made opaque.
> No existing public interface can be removed until its replacement has been in place in an LTS stable release. The original interface must also have been documented as deprecated for at least 5 years. A public interface is any function, structure or macro declared in a public header file.
> When structures are made opaque, any newly required accessor macros or functions are added in a feature release of the extant LTS release and all supported intermediate successor releases.

One possibility we should consider is switching the default, so that you get the PBKDF2 behaviour if you don't do anything else. You then get the legacy behaviour by adding some additional flag, e.g. "-legacykdf" or something.

**Comment by mirage335** [comment]
Yes, I am aware of the policy now.

Changing default behavior works for me, I can't think of a reason it would be a problem anyone else can't work around.

Eventual removal, even in 5 years, would be undesirable. At least 8 would be better.

**Comment by levitte** [comment]
The deprecation of the use of EVP_BytesToKey has alreday been around for a few years, so if we start a 5 year count now, I believe those 8 years are already covered :wink:

**Comment by mattcaswell** [comment]
> The deprecation of the use of EVP_BytesToKey has alreday been around for a few years

Well, no, not really. The API has never been deprecated. It probably should have been - but it hasn't.

**Comment by levitte** [comment]
Note that I wrote "the deprecation *of the use*", not of the function itself.  I do try to choose my words carefully.  That warning has been around since 405988f2cca816fdfdf8ad62b1285dcf06822e85, i.e. for almost 5 years already.

**Comment by richsalz** [comment]
Can you call a KDF in such a way that gets the exact same output as BytesToKey?

**Comment by mattcaswell** [comment]
> Can you call a KDF in such a way that gets the exact same output as BytesToKey?

No, I don't think so. EVP_BytesToKey() is OpenSSL's own special invention and isn't standards based - hence the deprecation.

**Comment by richsalz** [comment]
So this means that files encrypted will now fail to be decrypted unless a pre-removal version is kept.  I think the project should think very carefully if they want to do that.

One possibility is to remove all internal use of BytesToKey from the runtime, and just inline the function in apps/enc.c, and only allow it for *decrypting* files.

**Comment by mattcaswell** [comment]
> One possibility is to remove all internal use of BytesToKey from the runtime, and just inline the function in apps/enc.c, and only allow it for decrypting files.

That sounds like quite a good idea (although we're not planning to actually remove yet anyway).

**Comment by mirage335** [comment]
Please, yes, continue to allow decryption. That works for the use cases I am thinking of.

**Comment by mirage335** [comment]
A force allow encryption flag would still be useful, though at least allowing decryption would allow one-way traffic.

To be clear, the problem I am trying to address here is the need for *very* long term deployment of IoT and similar devices which *only* process and *only* reply with something like a symmetrically encrypted string of bytes.

If the software to interoperate with such devices has to change within their lifetime, they must be physically replaced, or an increasingly complex support software must be arranged.

The OpenSSL 'enc' feature, if stable enough, can be ideal for such use, for a number of reasons.

**Comment by levitte** [comment]
If we're talking about interoperability, then it should be in your interest to use `-pbkdf2`, i.e. something like this:

``` console
$ echo test | openssl enc -e -aes-256-cbc -nosalt -pbkdf2 -md sha1 -pass pass:test  -out - -in - | xxd -p
```

`EVP_BytesToKey` is an *OpenSSL only mehod*, i.e. not interoperable with any other crypto software (that we know of).

**Comment by richsalz** [comment]
Folks, this conversation is going around in circles.  THERE ARE EXISTING ENCRYPTED FILES.

**Comment by levitte** [comment]
Yes? I'm talking about *encryption*, which is the initial example (see `-e`)

**Comment by mirage335** [comment]
Interoperability with existing, older, OpenSSL installations (which do not support -pbkdf2), as well as new installations (which currently support -md sha1) can be enough. The need for interoperability going both into past OpenSSL versions and future OpenSSL versions at the same time is my problem.

**Comment by levitte** [comment]
...  I wonder if `EVP_BytesToKey` can be turned into a legacy KDF that we stick in the legacy provider.  That way, those who absolutely want to use that can continue to do so, just with a different knob.

**Comment by mirage335** [comment]
**Interoperability between older and newer versions of OpenSSL is *NOT* optional for some use cases.**

For everyone's information, 'coreoracle' software (not public) 'commKey' uses openssl 'enc' with appropriately long, completely random, high-entropy keys, to send and receive *pure* ciphertext symmetrically authenticated and encrypted messages, and *never* send nor accept the same ciphertext more than once.

By decoding all possible offsets of a bytestream of analog symbols from a radio demodulator (ie. a frequency mixer), and transmitting pure ciphertext through an appropriately chosen radio modulator with appropriate bandwidth usage, it is possible to communicate by radio with no emissions different from random analog noise, which to a distant listener, may be statistically indistinguishable from any thermal/atmospheric/etc source of random analog noise. Such software can also add a layer of resistance to quantum computing to existing asymmetric encryption (eg. SSH, SSL, etc). 

Due to the obviously *very* limited 'attack surface', and the secret-splitting functionality of 'fragKey' there is usually little no security benefit from frequently updating software, and there can be significant security risk from the updates (eg. from installing large amounts of software without complete code review).

https://github.com/mirage335/coreoracle/blob/main/_prog/oracle/wrapper/_openssl.sh#L55
https://github.com/mirage335/coreoracle/blob/main/_prog/oracle/wrapper/_openssl.sh#L63

**Comment by mirage335** [comment]
While I could work with that, changing the command line syntax as such would be really irritating to me. This would result in the codebase that works with newer systems being different from the codebase for older systems, with **OpenSSL being the only cause of that breakage to keep track of**. Or I would have to go put in some automatic test case and wrapper function to detect which features were available from the OpenSSL installed and provide a consistent interfaces. Again, OpenSSL would be rather uniquely unhelpful here.

I suggest the whole 'let's go get rid of a little cryptographic primitive which is actually secure when used properly because some people might be stupid enough to miss the opportunity for a little extra security' mentality be forever abandoned. It is not helping the people who do need to be helped.
