### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Milav-teq** [openssl/openssl#10158]
Hello,

I make a qt application for Embedded Custom Board and when i run the Application it gives segmentation fault.

The application give segmentation fault due to following line.

`  mosq->subscribe(mosq->getMID(), topic.data(), 1);`

where mosq is define and declare as follow.
```

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    qtmosq* mosq = NULL;
    QStringList subed;
    QString currentTopic;
    Ui::MainWindow *ui;
--------
--------
--------
};
```

where qtmosq is define as follow..

```
#include "QObject"
#include "mosquittopp.h"

using namespace mosqpp;

class qtmosq : public QObject, public mosquittopp
{
    Q_OBJECT

public:
    qtmosq(const char *id = NULL, bool clean_session = true) : mosquittopp (id, clean_session) {MID = 0;}
    ~qtmosq() {}

    void on_connect(int result)
    {
        if (!result)
        {
            //subscribe(NULL, "$SYS/#", 2);
            emit connected();
        }
        else
            emit connectEnable();
    }
    void on_publish(int id)
    {
        MID++;
        emit messageSent(true);
    }
    void on_subscribe(int mid, int qos_count, const int *granted_qos)
    {
        if (MID != 0)
            emit subscribed();
        MID++;
    }
..........
..........
..........

signals:
    void connected();
    void messageSent(bool);
    void messageReceived(QString);
    void connectEnable();
    void subscribed();
};
```

so what is the reason behind for this fault.

The same application are successfully run on Host Linux PC.

I have use same mosquitto library in both the test.

please help me to sort out this problem.

I have send the reference link at where i used above program.

Link :- [Ref. Link](https://github.com/elmirador/qt-mosquitto)

Thank you
Milav Soni

**Comment by kroeckx** [comment]
I don't see how it related to OpenSSL.
