### ISSUE TITLE
The export of P12 files doesn't work as expected

### ISSUE THREAD

**Issue by h-rueda** [openssl/openssl#10175]
openssl version: OpenSSL 1.1.1  11 Sep 2018

command : openssl pkcs12 -export -in cert.pem -inkey cert.key -passout pass:1234 -out cert.p12

test : using the desktop environment (GNOME), double-click the cert.p12 file, then type "1234" as password.

result: GNOME indicates that the password is incorrect.

![Screenshot from 2019-10-14 14-35-03](https://user-images.githubusercontent.com/16239820/66751663-d737c080-ee8f-11e9-98ed-79264b1fba0d.png)

**Comment by mattcaswell** [comment]
I cannot reproduce this. I just tried this command with the exact same version of OpenSSL and GNOME is able to read it just fine. Possibly a GNOME bug?

**Comment by h-rueda** [comment]
I retested today again. I cannot reproduce the bug.
Maybe I made a mistake in my first test.
You can close this issue
