### ISSUE TITLE
Unclear documentation regarding memory ownership on failed set0 calls.

### ISSUE THREAD

**Issue by bdonlan** [openssl/openssl#10178]
The OpenSSL manpage for `RSA_set0_key` states:

> Calling this function transfers the memory management of the values to the RSA object, and therefore the values that have been passed in should not be freed by the caller after this function has been called.

However, in practice, memory management is transferred only _success_ of the function. In this particular case, this is relevant only if only one of `n` or `e` is passed, and the corresponding value is `NULL` in the RSA structure initially; in this case the function returns without modifying the `RSA` structure or freeing the provided value.

Please clarify in the documentation the intended ownership of memory for objects passed to a `set0` routine that returns failure (and, if appropriate, correct the implementation as well).

**Comment by kroeckx** [comment]
On failure, nothing has been modified. Either everything is done,
or nothing is done.

**Comment by mattcaswell** [comment]
I agree with Kurt. If a function fails then it doesn't perform any of its advertised operations. I don't think there is a need to point this out for the large number of functions in our man pages. Closing this.
