### ISSUE TITLE
After the submit dec95d75897125133380c7ce3c6ce58c93c06f10, the aes performance dropped a lot(about 93%). We can see it use one new path in provider, but some macro definitions missed, which cause all of the AES related algorithms didn't use ASM acceleration.

### ISSUE THREAD

**Issue by xkqian** [openssl/openssl#10172]
I know that you are updating the openssl from 1.1 to 3.0, which is related tons of code changes. My question is: is the performance regression issue one known issue or not. I locally debug and find: after the submit dec95d75897125133380c7ce3c6ce58c93c06f10, the aes init key will use the new path from provider/, but unfortunately, some macro definition such as "-DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DO      PENSSL_IA32_SSE2 -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM" be missed. if it's not one known issue,  I want to solve it and submit a patch, but wondering wherer to place the definition, should I place it in providers/implementations/ciphers/build.info?

**Comment by levitte** [comment]
I believe that the [diff I posted in #10146](https://github.com/openssl/openssl/pull/10146#issuecomment-541409582) fixes the issue.  Would you mind applying that patch and confirming?

**Comment by xkqian** [comment]
I apply this patch and test it locally, seems it can solve the issue for x86, but not for other platforms, such as aarch64, I believe they are also controlled by this macro: "OPENSSL_CPUID_OBJ".   By the way, should we place the definition of libimplementations.a under crypto/aes/?

**Comment by levitte** [comment]
> By the way, should we place the definition of libimplementations.a under crypto/aes/?

No need

**Comment by levitte** [comment]
But ok, noted, 2e need to do the same with other algos as welm

**Comment by slontis** [comment]
Is this issue addressed now?

**Comment by xkqian** [comment]
Issue has been fixed in #10180, with link:https://github.com/openssl/openssl/pull/10180

**Comment by xkqian** [comment]
> Is this issue addressed now?

Yes, it's been fixed
