### ISSUE TITLE
handshake test failed when using SM2 cert

### ISSUE THREAD

**Issue by cyangyang** [openssl/openssl#10193]
I am testing SM2 handshake using openssl 1.1.1d version.

I first generate self signed cert "ca.crt":
`openssl ecparam -genkey -name SM2 -out ca.key`
`openssl req -new -x509 -days 3650 -key ca.key -out ca.crt`

Then use "ca.crt" to generate server cert "server.crt" and key "server_sm2_private.pem"
`openssl ecparam -genkey -name SM2 -out server_sm2_private.pem`
`openssl req -new -key server_sm2_private.pem -out server.csr`
`openssl x509 -req -days 3650 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt`

Then I generate client cert and key using the same comands:
`openssl ecparam -genkey -name SM2 -out client_sm2_private.pem`
`openssl req -new -key client_sm2_private.pem -out client.csr`
`openssl x509 -req -days 3650 -in client.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out client.crt`

Now I start test server:
`openssl s_server -cert server.crt -key server_sm2_private.pem -CAfile ca.crt -msg -debug`

Then I start client:
`openssl s_client -CAfile ca.crt`

But the connection failed followed by these info:
**<<< TLS 1.3, Handshake [length 0132], ClientHello
    01 00 01 2e 03 03 f8 bf 47 a6 56 43 59 42 6b a2
    a0 a2 87 2e 39 8d a0 4a d5 66 61 8d a9 b4 5a fe
    a6 6c 66 a4 a8 ef 20 42 99 dd f5 4b d7 fb 61 26
    0a 2f f1 ef 8f ec a8 43 00 cc d3 df d8 37 92 9f
    82 e1 6e e3 79 a0 d3 00 3e 13 02 13 03 13 01 c0
    2c c0 30 00 9f cc a9 cc a8 cc aa c0 2b c0 2f 00
    9e c0 24 c0 28 00 6b c0 23 c0 27 00 67 c0 0a c0
    14 00 39 c0 09 c0 13 00 33 00 9d 00 9c 00 3d 00
    3c 00 35 00 2f 00 ff 01 00 00 a7 00 00 00 0e 00
    0c 00 00 09 6c 6f 63 61 6c 68 6f 73 74 00 0b 00
    04 03 00 01 02 00 0a 00 0c 00 0a 00 1d 00 17 00
    1e 00 19 00 18 00 23 00 00 00 16 00 00 00 17 00
    00 00 0d 00 30 00 2e 04 03 05 03 06 03 08 07 08
    08 08 09 08 0a 08 0b 08 04 08 05 08 06 04 01 05
    01 06 01 03 03 02 03 03 01 02 01 03 02 02 02 04
    02 05 02 06 02 00 2b 00 09 08 03 04 03 03 03 02
    03 01 00 2d 00 02 01 01 00 33 00 26 00 24 00 1d
    00 20 06 84 a4 d7 2a 11 8d cf 3f f9 ed 38 de 0d
    47 3b 03 57 ba d7 af 6a c0 47 05 e3 34 c3 17 2b
    43 7c
>>> ??? [length 0005]
    15 03 03 00 02
write to 0xa3d180 [0xa54510] (7 bytes => 7 (0x7))
0000 - 15 03 03 00 02 02 28                              ......(
>>> TLS 1.2, Alert [length 0002], fatal handshake_failure
    02 28
ERROR
140589259081536:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:2259:
shutting down SSL
CONNECTION CLOSED**

I am wondering what goes wrong?
Thanks!

**Comment by mattcaswell** [comment]
We don't support SM2/SM3 in libssl. It's actually not possible to use them in standard SSL/TLS because there are no officially defined codepoints for them - or at least there haven't been until very recently (within the last few weeks):

https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-01

That spec is still in draft so it will take a while for support for it to make it into a released version of OpenSSL.

**Comment by cyangyang** [comment]
> We don't support SM2/SM4 in libssl. It's actually not possible to use them in standard SSL/TLS because there are no officially defined codepoints for them - or at least there haven't been until very recently (within the last few weeks):
> 
> https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-01
> 
> That spec is still in draft so it will take a while for support for it to make it into a released version of OpenSSL.

Oh, I see. 
Thanks for your kind reply.
