### ISSUE TITLE
Issue with ctx->flags after upgrading to version 1.1.1d

### ISSUE THREAD

**Issue by amrithathorath** [openssl/openssl#10197]
The error I see is:

```
error: dereferencing pointer to incomplete type
ctx->flags |= (EVP_CIPH_FLAG_LENGTH_BITS);
```

My code is:

```
EVP_CIPHER_CTX  *ctx;
ctx = EVP_CIPHER_CTX_new();     // This was not part of my code while using 1.0.2p. Added it for 1.1.1d
EVP_CIPHER_CTX_init(ctx);       // Adding or removing this line makes no difference
ctx->flags |= (EVP_CIPH_FLAG_LENGTH_BITS);
....
....
EVP_CIPHER_CTX_free(ctx);

```

Is there something wrong with the way I'm updating flags variable?

**Comment by levitte** [comment]
Side note: that function needs documenting...

**Comment by mattcaswell** [comment]
`EVP_CIPHER_CTX_set_flags(flag_value)` adds the flags to the set of flags. Its equivalent to:

````
ctx->flags |= flag_value;
````

`EVP_MD_CTX_clear_flags(flag_value)` clears the flags from the set of flags. Its equivalent to:

````
ctx->flags &= ~flag_value;
````

`EVP_MD_CTX_test_flags(flag_value)` clears the flags from the set of flags. Its equivalent to:

````
(ctx->flags & flag_value)
````

Anything you need to do with the flags should be expressible using one of those forms.

**Comment by amrithathorath** [comment]
Thanks a lot...
