### ISSUE TITLE
curve selection

### ISSUE THREAD

**Issue by bjacquin** [openssl/openssl#10201]
Hi,

I am not too sure if this a bug or a compliance to RFC.

When a set of curves are specified on the server side, the selected curve is the first curve matching both client and server, using the client order. Is this something that is intended ?

For example with server side using the following code sample

```
SSL_CTX_set1_groups_list("X448:P-384:X25519:P-256")
```

# No curves specified on the client side

```
$ openssl s_client < /dev/null -connect 1.2.3.4:4433
..
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 6522 bytes and written 393 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

# Preempting `P-256` on the client side

```
$ openssl s_client < /dev/null -connect 1.2.3.4:4433 -curves P-256:X25519
..
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 6555 bytes and written 420 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

In my understand server side choice should be respected. Is this a misunderstanding ?

Both client and server are using OpenSSL 1.1.1d

**Comment by t8m** [comment]
You need to set the SSL_OP_CIPHER_SERVER_PREFERENCE on the server to override the client preference.

**Comment by bjacquin** [comment]
Well, yes SSL_OP_CIPHER_SERVER_PREFERENCE is indeed set up and works fine for ciphers, but here the question is regarding the curve (Server Temp Key) selection. Repening as I believe this was a misunderstanding

**Comment by kaduk** [comment]
No, it was not a misunderstanding; see https://github.com/openssl/openssl/blob/master/ssl/t1_lib.c#L373-L379 (noting that "curve" is generalized to arbitrary groups for key exchange, at this point)

**Comment by bjacquin** [comment]
I am afraid I am able to reproduce this with openssl s_server and s_client. s_server is reporting Shared Elliptic groups are `X25519:P-256`, while the `Server Temp Key` reported by s_client is `P-256`, here is a full output:

```
$ openssl s_server -port 4433 -serverpref -cert ./pub.pem -key ./priv.pem -curves X25519:P-256
Setting temp DH parameters
ACCEPT
-----BEGIN SSL SESSION PARAMETERS-----
# REDACTED #
-----END SSL SESSION PARAMETERS-----
Shared ciphers:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA
Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1
Supported Elliptic Groups: P-256:X25519
Shared Elliptic groups: X25519:P-256
CIPHER is TLS_AES_256_GCM_SHA384
Secure Renegotiation IS supported
DONE
shutting down SSL
CONNECTION CLOSED
```
```
$ openssl s_client < /dev/null -connect 127.0.0.1:4433 -curves P-256:X25519
CONNECTED(00000003)
---
Certificate chain
...

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, P-256, 256 bits
...
```

In my understanding since both end are supporting P-256 and X25519, the one defined the first on server side should be selected.

**Comment by mattcaswell** [comment]
> You need to set the SSL_OP_CIPHER_SERVER_PREFERENCE on the server to override the client preference.

This is true for TLSv1.2. In TLSv1.3 things work differently. In TLSv1.2 the curve is selected by the server and can be controlled by `SSL_OP_CIPHER_SERVER_PREFERENCE`. In TLSv1.3 the curve is selected by the *client* and is sent in the initial ClientHello. Since its selected by the client `SSL_OP_CIPHER_SERVER_PREFERENCE` has no impact. On the server side, as long as the curve is in its list of acceptable curves, then it will accept it. This is to avoid the cost of an additional round-trip which it would otherwise require.

If the curve selected by the client is not acceptable to the server then the server will respond with a HelloRetryRequest (HRR) (hence adding an additional round-trip) and it will request the first curve in the server's list that is also in the client's list (i.e. only at this point is the server's preference used).

This can be seen if we force an HRR with the client selecting a curve that the server does not support:

````
$ openssl s_server  port 4433 -cert ./pub.pem -key ./priv.pem -curves X25519:P-256
````

````
$ openssl s_client < /dev/null -connect 127.0.0.1:4433 -curves P-384:P-256:X25519
...
Server Temp Key: X25519, 253 bits
...
````
Note that the client initially selects P-384 which is not acceptable to the server - and finally we end up with X25519 which is the server's preference.

**Comment by bjacquin** [comment]
Cool, thanks a lot for the detailed information, this definitely make sense
