### ISSUE TITLE
Discussion: Reworking how we specify the OpenSSL version

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#10203]
*Related to discussions in #7863 and #9745*

Currently, the OpenSSL version is specified with a few macros in `include/openssl/opensslv.h` (`crypto/opensslv.h` in pre-1.1.0 OpenSSL), and those who want to extract the version number from them (including ourselves when we make the releases) in the best way they can.

With all releases so far (i.e. prior to upcoming 3.0), this is often done by finding `OPENSSL_VERSION_TEXT` and parsing it.  This works for them, but not for 3.0, where you have to piece together the values of several macros to figure out the version number string.  For example, CMake's [FindOpenSSL](https://cmake.org/cmake/help/latest/module/FindOpenSSL.html) is affected by this.

Furthermore, version numbers are a bit all over the place.  When doing a release, a number of files are being patched, commonly updating the version in specific files (README comes to mind, I forget if there are more).  Even `Configure` has to do work of this sort...

So in the interest of:

- having the version number in one readable place only
- satisfy the needs of those that haven't caught up with the new format

I would like to go with what @petrovr suggests in https://github.com/openssl/openssl/issues/7863#issuecomment-541403228.  An idea is to have a file `VERSION` with some well specified data:

```
MAJOR=3
MINOR=0
PATCH=0
PRE_RELEASE_TAG=-dev
BUILD_METADATA=
```

This can be read by anyone that wants to, and used to generate `include/openssl/opensslv.h`, and thereby get back a parsable `OPENSSL_VERSION_TEXT`.  This also simplifies our release process, where updating the version data simply means replacing `VERSION` instead of in-place edits of `include/openssl/opensslv.h`.

Comments?

**Comment by mattcaswell** [comment]
Sounds like a good idea to me.

**Comment by beldmit** [comment]
I also want to mention that there is a practice to add some information (e.g. distr-related, or, in case of software certification, some certification information) to version. Is the BUILD_METADATA the place to add such information? If I understand correctly - no, so we need to add a field to provide such information.

**Comment by levitte** [comment]
Yes, BUILD_METADATA is exactly that.

**Comment by beldmit** [comment]
And where do the build options (e.g. no-des) go?

**Comment by levitte** [comment]
Uhmmmm, huh?  They have *never* been part of the version information per se.  They are collected in `configdata.pm`, though.

**Comment by beldmit** [comment]
Got it, thanks!

**Comment by richsalz** [comment]
Is there any reason why the standard dofile "foo.in" stuff won't work?  Like, ya know, version.pm to have the version numbers?

**Comment by rwfranks** [comment]
Does this proposal mean that opensslv.h will contain a generated ready-to-eat
```
 #define OPENSSL_VERSION_TEXT    "OpenSSL 3.0.0-dev  xx XXX xxxx"
```
instead of assembling same from OPENSSL_MAJOR etc.?

**Comment by levitte** [comment]
> Is there any reason why the standard dofile "foo.in" stuff won't work? Like, ya know, version.pm to have the version numbers?

We already pass the version info via `configdata.pm`, and for once, I want a very simple syntax, even though Perl would be quite simple, but I want even simpler, something similar to the build.info syntax.

> Does this proposal mean that opensslv.h will contain a generated ready-to-eat...

Yes, that's one of the benefits

**Comment by richsalz** [comment]
> I want a very simple syntax, even though Perl would be quite simple, but I want even simpler, something similar to the build.info syntax.

build.info is no longer simple.  It has flow of control, variables, etc.  It is a custom mini language.

Perl is understood.  Only a couple of people would be editing a special version.pm file that configdata auto-imports.   I mean, really;
```
our $OpenSSL::version::MAJOR='3';
our $OpenSSL::Version::MINOR='0';
our $OpenSSL::version::PATCH='0';
our $OpenSSL::version::PRE_RELEASE_TAG='-dev';
our $OpenSSL::version::BUILD_METADATA='';
```

Please don't invent a new syntax and mechanism.

**Comment by rwfranks** [comment]
On Thu, 17 Oct 2019 at 13:43, Richard Levitte <notifications@github.com>
wrote:

> Does this proposal mean that opensslv.h will contain a generated
> ready-to-eat...
>
> Yes, that's one of the benefits
>
Excellent.

**Comment by richsalz** [comment]
So you have a new file syntax, a new mechanism, and build step because you are worried someone will make a mistake editing things.  That's the wrong trade-off in my view.  Oh well.

**Comment by levitte** [comment]
The file is new.  The syntax isn't terribly new.  The tools to parse the file was already in place (it was used to parse opensslv.h, and the regexp for this "new syntax" is hugely simpler), the *Configuration* step to check that the version data is in place was already there, and the *build step* to generate opensslv.h is needed either way.

You're exaggerating the newness of this all.  There's really very little that's new.

**Comment by richsalz** [comment]
People on the Internet exaggerate to make a point?  I never knew that!

Still, this is the wrong way to go.

**Comment by levitte** [comment]
[shrug] so we disagree.
