### ISSUE TITLE
CI does not cover configuration option 'enable-trace'

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#10237]
The recent commit f386632 broke `include/openssl/cmp_util.h` when the trace API is enabled.
I've just provided a respective fix: #10236.

This incident indicates that the build checks by the Continuous Integration tools do not cover the case that the trace API is enabled in the configuration, since otherwise the above issue would have been caught right away.

**Comment by mattcaswell** [comment]
We don't include all possible options in travis. There are simply too many of them and travis jobs would take far too long. Instead we have a cron job (the run-checker.sh script) that checks all of these options:

https://github.com/openssl/tools/blob/master/run-checker/run-checker.sh

Interestingly that script does have `enable-ssl-trace` as one of the options it checks - so its not clear why it didn't complain about it.

**Comment by levitte** [comment]
@mattcaswell, `enable-trace` and `enable-ssl-trace` is not the same thing

**Comment by mattcaswell** [comment]
Ah...right....I mixed them up. And now I see that run-checker *is* in fact failing on enable-trace.

**Comment by DDvO** [comment]
> We don't include all possible options in travis. There are simply too many of them and travis jobs would take far too long.

I understand.
Yet one could try combining certain config options that are (linkely) independent into one CI run,
leading to a better overage of options without extra computational overhead.

**Comment by DDvO** [comment]
Currently there is a further build failure that went unnoticed for a while 
just because `enable_trace` is not part of the CI builds: #10731.

**Comment by mspncp** [comment]
> We don't include all possible options in travis. There are simply too many of them and travis jobs would take far too long. Instead we have a cron job (the run-checker.sh script) that checks all of these options:
> 
> https://github.com/openssl/tools/blob/master/run-checker/run-checker.sh

@mattcaswell Is this an internal job only? Or are its results posted somewhere? If not, is it possible to post failures to, e.g., the [openssl-commits](https://mta.openssl.org/pipermail/openssl-commits) list?

**Comment by mspncp** [comment]
Oh, they _are_ posted, see for example

*  [FAILED build of OpenSSL branch master with options -d --strict-warnings enable-trace](https://mta.openssl.org/pipermail/openssl-commits/2019-December/026748.html).

@DDvO you just need to subscribe to the openssl-commits list and create a filter for 
'OpenSSL run-checker'.

**Comment by mspncp** [comment]
Interestingly, the offending commits for issue #10731 are already listed in run-checker's report:

```
Commit log since last time:

0ab6fc79a9 Fix regression on x509 keyform argument
625c781dc7 Use a function to generate do-not-edit comment
b575608507 Make Windows build more robust
3ce3866389 Fix travis timeout by excluding arm64 gcc -fsanitize=address build
31b59078c8 Optimize AES-GCM implementation on aarch64
51a7c4b5f2 TEST: Add test recipe and help program to test BIO_f_prefix()
f1299839b7 EVP: Adapt EVP_PKEY_print_ routines to use BIO_f_prefix()
0e79d20f1e ASN1: Adapt ASN.1 output routines to use BIO_f_prefix()
e79ae962fb APPS & TEST: Adapt to use the new BIO_f_prefix()
319cee9e2f BIO: Add BIO_f_prefix(), a text line prefixing filter
a0848daee5 crypto/bio/build.info: split the source files in categories
8913378a55 Fix unwind info for some trivial functions
f64f262204 Fix build when enabling mdebug options.
b2055d67f0 Cleanup legacy digest methods.
```

**Comment by mspncp** [comment]
@DDvO is this feature sufficient to satisfy your request?

**Comment by mspncp** [comment]
IMHO the @openssl/otc should find a precedure to deal with run-checker failures in a more automatic and timely fassion.

**Comment by DDvO** [comment]
From the above responses by @mattcaswell and @levitte I conclude that `enable_trace` so far is not covered by (standard) Travis CI builds - and if they were, everyone providing a PR that is based upon such a faulty branch would immediately notice.

**Comment by DDvO** [comment]
> @DDvO is this feature sufficient to satisfy your request?

As you found out, the failure has already been recorded internally on Dec 21st.
As long as such issues are then fixed soon this would be sufficient at least to me
(because we are not that dependent on the trace API, which unfortunately is not enabled by default).
Yet this time, maybe due to the Christmas break, so far nobody had taken care of it.

**Comment by DDvO** [comment]
The simplest solution in this case would of course be to generally enable the trace API ;-)

**Comment by richsalz** [comment]
The project does weekly builds of various 'no-xxx' options.  Perhaps enable-trace could be added there?

**Comment by mattcaswell** [comment]
> From the above responses by @mattcaswell and @levitte I conclude that enable_trace so far is not covered by (standard) Travis CI builds - and if they were, everyone providing a PR that is based upon such a faulty branch would immediately notice.

IMO adding such options to the Travis CI builds is not a viable option. At least not in the general case. There might be a small set of options that could be included (and maybe enable-trace is one of those). The problem is there are a *lot* of options. Systematically going through all of them  takes a *long* time and would slow down Travis too much.

One possible approach is to continue as we are with run-checker, but additionally have one travis build that enables everything that is disabled by default, and another build that disables everything that is enabled by default.

**Comment by nhorman** [comment]
given that we don't use travis any longer, is this still an issue in our current ci?

**Comment by DDvO** [comment]
> given that we don't use travis any longer, is this still an issue in our current ci?

The reference to Travis is clearly not the essential thing here,
but whether the current CI sufficiently covers the case that OpenSSL is configured with `enable-trace`.

Looks like this is the case because `.github/workflows/ci.yml` meanwhile contains the `full_featured` run
where youself were the one who added `enable-trace` to it in #22589 :smile:
```
      run: ./config --banner=Configured --strict-warnings enable-demos enable-h3demo enable-ktls enable-fips enable-egd enable-ec_nistp_64_gcc_128 enable-md2 enable-rc5 enable-sctp enable-ssl3 enable-ssl3-method enable-trace enable-zlib enable-zstd && perl configdata.pm --dump
```

To me this looks sufficient to give the trace feature a try, or is this too tightly coupled to libabigail checking?

If the idea of this CI run to enable basically everything, this looks good to me.
Would it be worth backporting (most of) making the `full_featured` run to 3.0 LTS?

**Comment by nhorman** [comment]
I'd be fine with opening a pr to include enable-trace in the last LTS release, but it seems like theres more going on here (hence my previous question)

@mspncp comment [here](https://github.com/openssl/openssl/issues/10237#issuecomment-569917958) for instance alludes to the fact that theres also a desire to address run-checker failures in a more timely fashion.  I may be reading into it, but it seems the ask there is perhaps for run-checker-daily.yml to be more obvious in its failures, is that the case?  From my experience run-checker-daily.yml attempts to run a more complete (if not fully complete) set of build option combinations, and if it fails, we get an email, but no immediate blockage or other prevention of developer progress, making daily checks effectively ignore-able.  Do I have that about right?

If so, I would suggest a new build status badge on the code page, tracking the last run of the run-checker-daily action.  In fact it might be good to do so, given that our current badge set includes what seems to be an appveyor action that may not have run in a few years.

**Comment by nhorman** [comment]
ok, so the ask is just to ensure that we have enable-trace in 3.2/3.1/3.0 builds somewhere in CI, ignoring the daily run-checker-daily issues (for now) then?

If theres agreement, @DDvO would you be willing to open a PR to do that backport from 3.3?

**Comment by t8m** [comment]
IMO the full_featured CI run is sufficiently covering this as it contains enable_trace and runs tests.
