### ISSUE TITLE
license text discrepancy

### ISSUE THREAD

**Issue by vladak** [openssl/openssl#10233]
There is a difference in https://www.openssl.org/source/license-openssl-ssleay.txt (linked from https://www.openssl.org/source/license.html) and the `LICENSE file` in the tar ball distribution:
```diff
$ diff --ignore-all-space -u license-openssl-ssleay.txt openssl-1.0.2t/LICENSE 
--- license-openssl-ssleay.txt	2019-10-21 16:33:52.346205363 +0200
+++ openssl-1.0.2t/LICENSE	2019-09-10 15:24:10.000000000 +0200
@@ -4,13 +4,15 @@
 
   The OpenSSL toolkit stays under a double license, i.e. both the conditions of
   the OpenSSL License and the original SSLeay license apply to the toolkit.
-  See below for the actual license texts.
+  See below for the actual license texts. Actually both licenses are BSD-style
+  Open Source licenses. In case of any license issues related to OpenSSL
+  please contact openssl-core@openssl.org.
 
   OpenSSL License
   ---------------
 
 /* ====================================================================
- * Copyright (c) 1998-2019 The OpenSSL Project.  All rights reserved.
+ * Copyright (c) 1998-2018 The OpenSSL Project.  All rights reserved.
  *
  * Redistribution and use in source and binary forms, with or without
  * modification, are permitted provided that the following conditions
```
Now, I am not a lawyer so I don't know how big problem this is but certainly this is causing me some grief when dealing with upgrade to the last version internally (meaning inside Oracle).

**Comment by mattcaswell** [comment]
This is not a change to the actual licence text itself, but to the non-normative preamble. The reference in 1.0.2 to "openssl-core@openssl.org" is certainly out of date. But since 1.0.2 is in security fix only mode I don't think a fix is necessary here.

**Comment by richsalz** [comment]
Mea culpa.

**Comment by paulidale** [comment]
Given that the text isn't going to be changed, there doesn't seem any reason to keep this open.
