### ISSUE TITLE
Nginx 1.17.5 problem with compiling!

### ISSUE THREAD

**Issue by hunterpl** [openssl/openssl#10244]
Hello Dear Staff,

Problem with compiling opensslmaster with nginx 1.17.5

Error common:

cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -D_GLIBCXX_USE_CXX11_ABI=0 -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/nginx/opensslmaster/.openssl/include -I objs \
        -o objs/src/event/ngx_event_openssl.o \
        src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_error’:
src/event/ngx_event_openssl.c:3066:13: error: ‘ERR_peek_error_line_data’ is deprecated [-Werror=deprecated-declarations]
             n = ERR_peek_error_line_data(NULL, NULL, &data, &flags);
             ^
In file included from /usr/local/nginx/opensslmaster/.openssl/include/openssl/opensslconf.h:123,
                 from /usr/local/nginx/opensslmaster/.openssl/include/openssl/macros.h:10,
                 from /usr/local/nginx/opensslmaster/.openssl/include/openssl/ssl.h:16,
                 from src/event/ngx_event_openssl.h:15,
                 from src/core/ngx_core.h:83,
                 from src/event/ngx_event_openssl.c:9:
/usr/local/nginx/opensslmaster/.openssl/include/openssl/err.h:296:30: note: declared here
 DEPRECATEDIN_3(unsigned long ERR_peek_error_line_data(const char **file,
                              ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/nginx/opensslmaster/.openssl/include/openssl/macros.h:36:38: note: in definition of macro ‘DECLARE_DEPRECATED’
 #    define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                      ^
/usr/local/nginx/opensslmaster/.openssl/include/openssl/err.h:296:1: note: in expansion of macro ‘DEPRECATEDIN_3’
 DEPRECATEDIN_3(unsigned long ERR_peek_error_line_data(const char **file,
 ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:934: objs/src/event/ngx_event_openssl.o] Error 1
make[1]: Leaving directory '/root/nginx-1.17.5'
make: *** [Makefile:8: build] Error 2
Error: Failure running 'make', exiting.

**Comment by kroeckx** [comment]
> Problem with compiling opensslmaster with nginx 1.17.5

Can I suggest that you don't use master, but the 1.1.1 release
instead?

We have deprecated things in master, and you build with -Werror
turning those warnings into errors.

**Comment by hunterpl** [comment]
Thank you, problem solved.
