### ISSUE TITLE
Make openssl code more ctags-friendly

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#10251]
A lot of openssl functions cannot be indexed using the `ctags` program and be found by name after `make tags` command.

Examples:

PKCS12_add_cert
CMS_get0_signers

In most cases, it's related to using the STACK_OF macros.
It makes sense to make a separate perl script for tags generation.

**Comment by InfoHunter** [comment]
> Or rather, call tags and then a script to merge in the STACK stuff?

I tried that before...

**Comment by StephenWall** [comment]
[exhuberent ctags](http://ctags.sourceforge.net/) and [universal ctags](https://github.com/universal-ctags/ctags) may help with this - the option `-I` can be used to redefine identifiers.  Look for `-I identifier-list` at https://github.com/universal-ctags/ctags/blob/master/man/ctags.1.rst.in for more details.

The functions I've found particularly frustrating are ones created by the **DECLARE_** and **IMPLEMENT_** macros.  It may even be possible to generate tags for those using the regex capabilities of exctags/uctags.

**Comment by levitte** [comment]
Something regex-based that rewords the `DECLARE_` and `IMPLEMENT_` macro calls to standard C declarations would be helpful. If uctags makes that possible, we can use uctags. It's also possible to make a crags preprocessor that makes such transformations if that would be more suitable. The base perl code for such things is already in place for the most part.

**Comment by StephenWall** [comment]
For a uctags example, this command:
```
uctags -R --regex-c='/IMPLEMENT_ASN1_FUNCTIONS\((.*)\)/d2i_\1/f/' --regex-c='/IMPLEMENT_ASN1_FUNCTIONS\((.*)\)/i2d_\1/f/' --regex-c='/IMPLEMENT_ASN1_FUNCTIONS\((.*)\)/\1_new/f/' --regex-c='/IMPLEMENT_ASN1_FUNCTIONS\((.*)\)/\1_free/f/' *
```
will add tags like this:
```
d2i_X509	crypto/asn1/x_x509.c	/^IMPLEMENT_ASN1_FUNCTIONS(X509)$/;"	f
i2d_X509	crypto/asn1/x_x509.c	/^IMPLEMENT_ASN1_FUNCTIONS(X509)$/;"	f
X509_new	crypto/asn1/x_x509.c	/^IMPLEMENT_ASN1_FUNCTIONS(X509)$/;"	f
X509_free	crypto/asn1/x_x509.c	/^IMPLEMENT_ASN1_FUNCTIONS(X509)$/;"	f
```
to the tags file.  Those `--regex-c` options can be placed in a file that uctags loads when it runs, but with the number of expressions needed to expand all of these type of macros, I can see that getting quite unwieldy, and being a maintenance issue.  It'd be worse if I were writing it, because I'd have `[ \t]*` between each piece of the expression to skip over white space, which makes them a lot harder for humans to read.

**Comment by masatake** [comment]
As an expert in ctags, I want to solve this issue.

Can we use Universal Ctags 6.0 (or higher) to solve this issue?
I have a script that can extract CMS_get0_signers and PKCS12_add_cert.

```
$ rm -f tags
$ time dash ./openssl-ctags.sh -R
real	0m3.664s
user	0m3.233s
sys	0m0.414s
$ grep ^CMS_get0_signers tags
CMS_get0_signers	crypto/cms/cms_sd.c	/^STACK_OF(X509) *CMS_get0_signers(CMS_ContentInfo *cms)$/;"	f	typeref:struct:stack_st_X509 *
$ grep ^PKCS12_add_cert tags
PKCS12_add_cert	crypto/pkcs12/p12_crt.c	/^PKCS12_SAFEBAG *PKCS12_add_cert(STACK_OF(PKCS12_SAFEBAG) **pbags, X509 *cert)$/;"	f	typeref:typename:PKCS12_SAFEBAG *
````

**Comment by paulidale** [comment]
Personally, I'd love such a script in the source tree.

Does your script deal with the macro generated functions like [these](https://github.com/openssl/openssl/issues/10251#issuecomment-548412706) (there are plenty more)?

**Comment by masatake** [comment]
After taking actions for CLA, I will make a pull request.

I put the script to https://github.com/universal-ctags/target-openssl/commit/23e8fb470f47ca00e27c0a7b03b2f8085bdaef5c

I hope this helps your daily hacking.

**Comment by paulidale** [comment]
The script works wonderfully, thanks!

As for the CLA, you should only need the ICLA I believe.  RedHat's CCLA allows all employees already.

**Comment by masatake** [comment]
> As for the CLA, you should only need the ICLA I believe. RedHat's CCLA allows all employees already.

This is one of the bigger benefits of working at Red Hat for people enjoying open source Surfin:-) I will look into ICLA.

**Comment by levitte** [comment]
I like what I see.  A proper PR is welcome!

**Comment by beldmit** [comment]
Fixed by @masatake - many thanks!
Closing.
