### ISSUE TITLE
PKCS7_sign can't set md.I need sha1 for BOC

### ISSUE THREAD

**Issue by boiciy** [openssl/openssl#10255]

**Comment by levitte** [comment]
In https://www.openssl.org/docs/man1.1.1/man3/PKCS7_sign.html, there's this note:

> The **certs**, **signcert** and **pkey** parameters can all be **NULL** if the **PKCS7_PARTIAL** flag is set. One or more signers can be added using the function PKCS7_sign_add_signer(). PKCS7_final() must also be called to finalize the structure if streaming is not enabled. Alternative signing digests can also be specified using this method.

Hppe that helps.
