### ISSUE TITLE
make fails in 1.0.2h for 'no-rc4'

### ISSUE THREAD

**Issue by wakwanza** [openssl/openssl#1026]
Custom compilation of 1.0.2h with no-rc4 option fails , perviously with 1.0.2g worked without any issues when building a static lib for nginx inclusion.

Current error:
`make[4]: *** No rule to make target `../../include/openssl/rc4.h', needed by `eng_openssl.o'.  Stop.
make[4]: Leaving directory `/root/rpmbuild/SOURCES/openssl-1.0.2h/crypto/engine'
make[3]: *** [subdirs] Error 1
make[3]: Leaving directory `/root/rpmbuild/SOURCES/openssl-1.0.2h/crypto'
make[2]: *** [build_crypto] Error 1
make[2]: Leaving directory `/root/rpmbuild/SOURCES/openssl-1.0.2h'
make[1]: *** [/root/rpmbuild/SOURCES/openssl-1.0.2h/.openssl/include/openssl/ssl.h] Error 2`

**Comment by mattcaswell** [comment]
You need to run "make depend" after config.

**Comment by yangdage** [comment]
try to execute `./config` comand before that.
