### ISSUE TITLE
s_client with DANE: valid 3 1 1 with invalid 3 0 2 records works, but valid 3 0 1 record with invalid 3 0 2 record fails?

### ISSUE THREAD

**Issue by dilyanpalauzov** [openssl/openssl#10269]
openssl’s s_client can verify DANE, if the DNS records are passed to the command line.

For _25._tcp.mail.aegee.org the valid TLSA records are:
```
3 0 1 BEAC45EB31CB044531757F3A8683F47F1BBEFB7262163D9F0D4B319B 5848998D
3 0 2 08A2D79628DDBBA20260CC1630E9E75FC303FE1BD308AFBAF799EBE7 28CFEE8F1577893813E908F45C9885138C185D84A5534502BFCA0177 E52D4F9D4D6640E2
3 1 1 2D1E4DDD0F7764423B1D6C62D41A324C71863BB8A4D71701B91FA126 CD5D457D
```
and there is a bunch of invalid TLSA records.

This works: (passing a single valid 3 1 1 record):
`echo QUIT|openssl s_client -connect mail.aegee.org:25 -starttls smtp -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 1 1 2D1E4DDD0F7764423B1D6C62D41A324C71863BB8A4D71701B91FA126 CD5D457D"; echo $?`

this also works (passing a single valid 3 0 2 record):
`echo QUIT|openssl s_client -connect mail.aegee.org:25 -starttls smtp -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 0 2 08A2D796
28DDBBA20260CC1630E9E75FC303FE1BD308AFBAF799EBE7 28CFEE8F1577893813E908F45C9885138C185D84A5534502BFCA0177 E52D4F9D4D6640E2"; echo $?`

Passing valid 3 0 2 and 3 1 1 records also works:

`echo QUIT|openssl s_client -connect mail.aegee.org:25 -starttls smtp -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 0 2 08A2D796
28DDBBA20260CC1630E9E75FC303FE1BD308AFBAF799EBE7 28CFEE8F1577893813E908F45C9885138C185D84A5534502BFCA0177 E52D4F9D4D6640E2" -dane_tlsa_rrdata "3 1
 1 2D1E4DDD0F7764423B1D6C62D41A324C71863BB8A4D71701B91FA126 CD5D457D"; echo $?`

Passing valid 3 0 2, 3 1 1 and 3 0 1 records also works:

`echo QUIT|openssl s_client -connect mail.aegee.org:25 -starttls smtp -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 0 2 08A2D796
28DDBBA20260CC1630E9E75FC303FE1BD308AFBAF799EBE7 28CFEE8F1577893813E908F45C9885138C185D84A5534502BFCA0177 E52D4F9D4D6640E2" -dane_tlsa_rrdata "3 1
 1 2D1E4DDD0F7764423B1D6C62D41A324C71863BB8A4D71701B91FA126 CD5D457D" -dane_tlsa_rrdata "3 0 1 BEAC45EB31CB044531757F3A8683F47F1BBEFB7262163D9F0D4
B319B 5848998D"; echo $?`

But passing valid 3 0 1 record, and invalid 3 0 2 record fails (I changed the last digit of the 3 0 2 record):
`echo QUIT|openssl s_client -connect mail.aegee.org:25 -starttls smtp -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 0 2 08A2D796
28DDBBA20260CC1630E9E75FC303FE1BD308AFBAF799EBE7 28CFEE8F1577893813E908F45C9885138C185D84A5534502BFCA0177 E52D4F9D4D6640E3" -dane_tlsa_rrdata "3 0
 1 BEAC45EB31CB044531757F3A8683F47F1BBEFB7262163D9F0D4B319B 5848998D"; echo $?`

Passing valid 3 1 1 record with invalid 3 0 2 record works:
```
echo QUIT|openssl s_client -connect mail.aegee.org:25 -starttls smtp -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 0 2 08A2D796
28DDBBA20260CC1630E9E75FC303FE1BD308AFBAF799EBE7 28CFEE8F1577893813E908F45C9885138C185D84A5534502BFCA0177 E52D4F9D4D6640E3" -dane_tlsa_rrdata "3 1
 1 2D1E4DDD0F7764423B1D6C62D41A324C71863BB8A4D71701B91FA126 CD5D457D"; echo $?
```

Why does the second last call (valid 3 0 1 with invalid 3 0 2) fail, but the last call (valid 3 1 1 with invalid 3 0 2) is OK?

**Comment by mattcaswell** [comment]
Ping @vdukhovni

**Comment by vdukhovni** [comment]
This is the expected result of digest algorithm agility <https://tools.ietf.org/html/rfc7671#section-9>.
When "X Y 2" records are present "X Y 1" records are ignored. This is hinted at in the `SSL_CTX_dane_enable(3)` manpage, but could perhaps be more explicit:
```
       The mtype argument specifies a DANE TLSA matching type and the md
       argument specifies the associated digest algorithm handle.  The ord
       argument specifies a strength ordinal.  Algorithms with a larger
       strength ordinal are considered more secure.  Strength ordinals are
       used to implement RFC7671 digest algorithm agility.  Specifying a NULL
       digest algorithm for a matching type disables support for that matching
       type.  Matching type Full(0) cannot be modified or disabled.

       By default, matching type "SHA2-256(1)" (see RFC7218 for definitions of
       the DANE TLSA parameter acronyms) is mapped to "EVP_sha256()" with a
       strength ordinal of 1 and matching type "SHA2-512(2)" is mapped to
       "EVP_sha512()" with a strength ordinal of 2.
```
