### ISSUE TITLE
想找一份sm2的签名验签使用案列，作测试使用  I am looking for a sm2 signature checklist for use in testing.

### ISSUE THREAD

**Issue by studentcaoqc** [openssl/openssl#10260]
公司要用sm2替换rsa算法，网关是用lua写的现在lua和node,java的不通，所以想测试下openssl的结果与java和node测试，想找一份sm2签名验签的使用案列

The company wants to replace the rsa algorithm with sm2. The gateway is written in lua. Now lua and node, java is nowhere, so I want to test the results of openssl and java and node tests, I want to find a sm2 signature check case.

**Comment by mspncp** [comment]
cc @InfoHunter

**Comment by InfoHunter** [comment]
If you just want to sign and verify the SM2 signature with OpenSSL, you can take a test case as a reference:

```
    # SM2
    ok_nofips(run(app(([ 'openssl', 'pkeyutl', '-sign',
                      '-in', srctop_file('test', 'certs', 'sm2.pem'),
                      '-inkey', srctop_file('test', 'certs', 'sm2.key'),
                      '-out', 'signature.dat', '-rawin',
                      '-digest', 'sm3', '-pkeyopt', 'sm2_id:someid']))),
                      "Sign a piece of data using SM2");
    ok_nofips(run(app(([ 'openssl', 'pkeyutl', '-verify', '-certin',
                      '-in', srctop_file('test', 'certs', 'sm2.pem'),
                      '-inkey', srctop_file('test', 'certs', 'sm2.pem'),
                      '-sigfile', 'signature.dat', '-rawin',
                      '-digest', 'sm3', '-pkeyopt', 'sm2_id:someid']))),
                      "Verify an SM2 signature against a piece of data");

```
from `test/recipes/20-test_pkeyutl.t`

If you want to use the APIs in your application, just check how `openssl pkeyutl` works by digging its source code. Good luck ;-)

**Comment by studentcaoqc** [comment]
Thank you
