### ISSUE TITLE
duplicated() in apps/req.c does not return 1 when -addext kv is duplicated

### ISSUE THREAD

**Issue by kinichiro** [openssl/openssl#10273]
About the function duplicated() in apps/req.c .
Comment says "1 if found or a syntax error", but it returns -1 if -addext kv is duplicated  after commit https://github.com/openssl/openssl/commit/750d5587d1d688df964cb37e86942da7e639d47b .

To detect duplicated, it should return 1 if p != NULL.
```diff
--- req.c.orig  Sun Oct 27 16:44:36 2019
+++ req.c       Sun Oct 27 16:47:22 2019
@@ -206,9 +206,12 @@ static int duplicated(LHASH_OF(OPENSSL_STRING) *addext
     *p = '\0';

     /* Finally have a clean "key"; see if it's there [by attempt to add it]. */
-    if ((p = (char *)lh_OPENSSL_STRING_insert(addexts, (OPENSSL_STRING*)kv))
-        != NULL || lh_OPENSSL_STRING_error(addexts)) {
-        OPENSSL_free(p != NULL ? p : kv);
+    p = (char *)lh_OPENSSL_STRING_insert(addexts, (OPENSSL_STRING*)kv);
+    if (p != NULL) {
+        OPENSSL_free(p);
+        return 1;
+    } else if (lh_OPENSSL_STRING_error(addexts)) {
+        OPENSSL_free(kv);
         return -1;
     }

```

Or comment should be changed like "-1 on runtime error or duplicated".

**Comment by mattcaswell** [comment]
Looks correct to me. It would be helpful if you could raise this as a pull request rather than as a diff in an issue.

**Comment by kinichiro** [comment]
close this issue since posted pull request.

**Comment by t8m** [comment]
It will be closed automatically when PR is merged.
