### ISSUE TITLE
OSCP HTTP client and other apps could benefit from improvements in cmp_http.c

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#10271]
When @mpeylo submitted his CMP implementation to OpenSSL a couple of years back he got the feedback that it should not use libCURL but OpenSSL's own HTTP client, which so far is used mainly for fetching OCSP responses (but also CRLs and certificates) .
So we changed CMPforOpenSSL to make use of the implementation in `crypto/ocsp/ocsp_ht.c`.

Unfortunately this HTTP client is tailored for use with OCSP and is very primitive - in particular, handling of delayed responses and errors is very poor and there is no support for more advanced features such redirection and use of proxies.

One of the next chunks of our current CMP contribution contains the HTTP client to be used for CMP, which will reside in `crypto/cmp/cmp_http.c`. The current state of its development can be found in https://github.com/mpeylo/cmpossl/blob/cmp-dev/crypto/cmp/cmp_http.c
This implementation is based on the mentioned HTTP code in `ocsp_ht.c`, while it contains improvements for those of its shortcomings critical for CMP: it
* can send and receive any types of ASN.1-formatted requests and responses
* does not include a potentially busy loop when waiting for responses 
but makes use of timeout mechanism integrated with socket-based BIO
* returns more useful diagnostics in various error situations
* supports the use of HTTP proxies and of TLS (including TLS over proxies)

I've already shaped the code in `cmp_http.c` such that several portions of it could more or less directly generalize and improve the existing HTTP client code in `ocsp_ht.c`, `apps/ocsp.c`, `apps/s_client.c`, and `apps/lib/apps.c`.

What is your view on these improvements - should I push them upstream (as a couple of independent PRs) for general use or should we keep them in `cmp_http.c`?

**Comment by richsalz** [comment]
It would be a shame to have two pieces of code that do the same thing.

**Comment by levitte** [comment]
I agree with @richsalz. Please make a generic http client that can be used by both CMP and OCSP. I'm not sure where it should be located in the end, but `crypto/http/` is at least a start.

**Comment by mattcaswell** [comment]
Agree with @levitte and @richsalz.

**Comment by DDvO** [comment]
Fine. I've meanwhile started implementing this.
Though I'm on vacation this week I estimate to be able to present a first version on Friday.

**Comment by DDvO** [comment]
Phew, implementing this generalized HTTP client was more work than expected.

I've moved most of the generally useful code into `crypto/http/http_client.c` (and a few functions into `crypto/http/http_lib.c` and as tentative a minor extension of `crypto/bio/b_sock.c`).
Doing so, the former `crypto/ocsp/ocsp_ht.c` (which is now called `crypto/ocsp/ocsp_http.c`), `crypto/ocsp/ocsp_lib.c`, and `crypto/cmp/cmp_http.c` have become pleasantly tiny.
Using the generalized code I also have been able to simplify `apps/ocsp.c`, `apps/s_client.c`, `apps/lib/apps.c`, and `apps/cmp.c` (which has not yet been submitted as part of our CMP contribution).
I've also updated the existing docs, while doc for the new functions is still to be done.

I invite you to take a look at https://github.com/mpeylo/cmpossl/tree/prepare_http/crypto/http (as well as on the other files I've just mentioned) and give me feedback on the changes I've made.
The branch `prepare_http` is a kind of preview of a proper pull request, which I'll provide ASAP (within a couple of days).

**Comment by levitte** [comment]
I had a quick look, and good start.
Something that became immediately obvious is the naming issue with public symbols. All new APIs must have names starting with `OSSL_` so we don't pollute the name space further. An example of a "new" API is the STORE, with all its public symbols starting with `OSSL_STORE`.

**Comment by DDvO** [comment]
Thanks for this quick first reaction.
I've prefixed all new and adapted exported (`BIO_*` and `HTTP_*`) functions with `OSSL_`.

**Comment by DDvO** [comment]
Is there anything else, in particular regarding the overall code structure, that I should change before doing the PR?

**Comment by levitte** [comment]
Heh, `BIO_` isn't necessary, 'cause that's an already existing API which you are just adding to.

**Comment by levitte** [comment]
Re the rest, I need a bit of time to have a deeper look.  Quite frankly, a PR works just as well, and you might want to mark it as WorkInProgress.  I assume you know how.

**Comment by DDvO** [comment]
> Heh, `BIO_` isn't necessary, 'cause that's an already existing API which you are just adding to.

I didn't get what you mean - 
replace `OSSL_BIO_wait` by `OSSL_wait` (which would be too unspecific in my view) 
and `OSSL_BIO_connect_retry` by `OSSL_connect_retry`?

**Comment by DDvO** [comment]
> Re the rest, I need a bit of time to have a deeper look. 

I understand - this code is non-trivial. While the bulk of it has just been moved around, 
there are a couple of improvements (taken from our to-be-contributed CMP implementation) which I mentioned above, some of which are a bit tricky, in particular the proxy & TLS support.

> Quite frankly, a PR works just as well, and you might want to mark it as WorkInProgress. I assume you know how.

I guess you mean prepending "**WIP:**" to the title of the PR?
Unfortunately the `prepare_http` branch (at least so far) touches also our current CMP master branch, but after I've sorted this out (likely tomorrow or Wed) I can do.

**Comment by levitte** [comment]
Sorry, didn't express myself well. What I meant is that the `BIO_` prefix is already established, so functions having names starting with that do not need further prefixing (`BIO` is not a new API). However, functions with names starting with `HTTP_` constitute an entirely new API, which means they need the additional `OSSL_` prefix.

**Comment by DDvO** [comment]
All right, reverted renaming the two new `BIO_*` functions to `OSSL_BIO_*`.

**Comment by DDvO** [comment]
Closing this issue since #10667 implementing it has been merged.
