### ISSUE TITLE
nmake gives error on apps\lib\apps.c(1818) : NMAKE : fatal error U1077 return code '0x2' Stop.

### ISSUE THREAD

**Issue by barmaley997** [openssl/openssl#10277]
Hello, i'm trying to compile the latest soruces of openssl that i've downloaded from here.
I have MS Visual Studio 2017, ActivePerl and NASM installed

so i did commands as you instructed:
```
perl Configure VC-WIN32
nmake
```
and after command nmake compiling begins but stops with error:
```
        cl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -I "." -I "include" -I "apps\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"C:\\Program Files (x86)\\Common Files\\SSL\"" -D"ENGINESDIR=\"D:\\Program Files (x86)\\OpenSSL\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\Program Files (x86)\\OpenSSL\\lib\\ossl-modules\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG"   -c /Foapps\lib\libapps-lib-apps.obj "apps\lib\apps.c"
apps.c
apps\lib\apps.c(1818): error C2220: warning treated as error - no 'object' file generated
apps\lib\apps.c(1818): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
apps\lib\apps.c(1989): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
apps\lib\apps.c(1994): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
NMAKE : fatal error U1077: 'd:\MSVisualStudio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.EXE' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'd:\MSVisualStudio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe' : return code '0x2'
Stop.
```

[config20191028132431.zip](https://github.com/openssl/openssl/files/3778205/config20191028132431.zip)

**Comment by kiyolee** [comment]
It is simply that /WX enables treating warnings as errors and stop compilation. Don't know why the option is there when for x64 build on Windows, for instance, there are still a lot of compiler warnings of C4244 and C4267. If you just want to compile, remove /WX from the generated makefile.

**Comment by mattcaswell** [comment]
> It is simply that /WX enables treating warnings as errors and stop compilation. Don't know why the option is there when for x64 build on Windows, for instance, there are still a lot of compiler warnings of C4244 and C4267. If you just want to compile, remove /WX from the generated makefile.

VC-WIN32 builds should be warning free so `/WX` should be ok there.

@barmaley997 - I see this is the master version of OpenSSL, so my guess is some newly introduced warning is causing the problem.

You are probably better off not using the master version and instead try OpenSSL 1.1.1

**Comment by levitte** [comment]
We shouldn't force /WX, just as we shouldn't (and don't) force -Werror

**Comment by mattcaswell** [comment]
> We shouldn't force /WX, just as we shouldn't (and don't) force -Werror

Good point..although perhaps we should for dev builds? At least for VC-WIN32 which (should be) warning free. It would be a shame to lose that.

**Comment by levitte** [comment]
So it should be possible to give `/WX` when configuring, is what you're saying. I totally agree.

**Comment by mattcaswell** [comment]
> So it should be possible to give /WX when configuring, is what you're saying.

Not, only should it be possible - but as developers we should do it. Certainly for AppVeyor builds. Remembering the particular incantation required for any particular platform isn't ideal. Perhaps amend `--strict-warnings` to do the right thing?

**Comment by levitte** [comment]
So, #10287

**Comment by barmaley997** [comment]
Ok - i removed /WX in CFLAGS in MAKEFILE and then all sources was copiled OK!
