### ISSUE TITLE
No checking return value of app_load_config() and app_load_config_bio() in apps/req.c

### ISSUE THREAD

**Issue by kinichiro** [openssl/openssl#10288]
Found this with 1.1.1d.
apps/req.c doesn't check return value of app_load_config() and app_load_config_bio().
It should `goto end;` if req_conf or addext_conf is NULL.
If we provide invalid value for -addext, it shows "req: Error on line 1 of config input", but continues processing like below.

```
$ openssl version
OpenSSL 1.1.1d  10 Sep 2019
$
$ openssl req -new  \
> -addext "subjectAltName := test.com" \
> -newkey rsa:2048 -nodes -keyout key.pem -out req.pem
req: Error on line 1 of config inputGenerating a RSA private key
..........+++++
......................+++++
writing new private key to 'key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
```

**Comment by mattcaswell** [comment]
This does appear suspicious. For `req_conf` the function `app_load_config` is called unconditionally (whether or not a config file was supplied or not), and we *do* handle the return being NULL - but we ignore it and continue. Probably we should only ignore it if an explicit config file was not specified.

**Comment by kinichiro** [comment]
I don't understand why we should ignore return NULL from `app_load_config()` when implicit (default) config file is used.
`template` is always set since `template` is initialized by `default_config_file` (implicit config file), and is overridden by `-config` option.
I thought we should handle returned NULL as error in both case that config file is explicit or implicit.
Is there any reason to ignore error while loading default config file ?
