### ISSUE TITLE
Looking for implementation of function sm3_update and sm3_final

### ISSUE THREAD

**Issue by GoudanWong** [openssl/openssl#10284]
Hi, I was trying to migrate the code under ` 1.1.1d/crypto/sm3 `, and I could only find declarations of function ` sm3_update ` and ` sm3_final ` in ` sm3.h ` ,but there seemed no implementation for those functions anywhere, I tried 
```
$ find -type f | xargs grep “sm3_update”
```
But still couldn’t find it’s body. Could anyone please help me?

**Comment by mattcaswell** [comment]
`sm3_locl.h` has these defines in it:

````
#define HASH_UPDATE             sm3_update
#define HASH_TRANSFORM          sm3_transform
#define HASH_FINAL              sm3_final
````

Then a few lines later it includes [md32_common.h](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1d/crypto/include/internal/md32_common.h) which defines the `HASH_UPDATE` and `HASH_FINAL` functions.

**Comment by GoudanWong** [comment]
👍Thank you so much! I thought that`#define A B` only meant make A an alias of B😂
