### ISSUE TITLE
Missing null check after OPENSSL_zalloc

### ISSUE THREAD

**Issue by KihongHeo** [openssl/openssl#10283]
Hi,

It seems that there is a potential null-dereference at line 29 if OPENSSL_zalloc returns NULL at line 26 the following code. https://github.com/openssl/openssl/blob/0a4d6c67480a4d2fce514e08d3efe571f2ee99c9/crypto/evp/keymgmt_lib.c#L26-L35

**Comment by InfoHunter** [comment]
Yes. Should check `OPENSSL_zalloc`'s return value.

**Comment by InfoHunter** [comment]
And also for line 80 I think.

**Comment by mattcaswell** [comment]
Agreed - confirmed bug.

**Comment by jayaram-intel** [comment]
Hi @mattcaswell 

Please Review the changes and suggest in case if I missed anything.


Thanks
Jayaram Matta
