### ISSUE TITLE
How to compiler openssl 1.0.2t with VS2017 vcvarsx86_arm.bat

### ISSUE THREAD

**Issue by lindazuo** [openssl/openssl#10282]
I was trying to build OpenSSL 1.0.2t with VS2017 arm. 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsx86_arm.bat"
During configure section, I ran command as following: "perl Configure VC-WIN32  --prefix=arm-win32-vc15\release  -D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1 -Z7 -MT"
But looks like VC-WIN32 is not right. I don't know which platform we can use for arm except VC-WIN32. I checked Configure file, didn't find any arm related platform.
I got the fatal error during building as following:
"tmp32\x86cpuid.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'ARM' "
Can somebody let me know how can I build OpenSSL 1.0.2t with VS2017 arm and arm64?
Thanks a lot!

**Comment by levitte** [comment]
You can't, 1.0.2 doesn't have the necessary data.
