### ISSUE TITLE
Some strange errors with using lybcrypto-3.dll externally 

### ISSUE THREAD

**Issue by barmaley997** [openssl/openssl#10291]
Hello! I am a Lua programmer and i need to use some of openssl cryptographic functions in Lua, such as HMAC SHA-512, so i decide to use it by the writing Dynamic Link Library in C with exported function that communicates with OpenSSL modules - they computing hash and returning it to the DLL and the DLL return this hash to the Lua code, So there is my code of DLL
in C on the MS Visual Studio 2017:

 ``` C
#define LUA_LIB
#define LUA_BUILD_AS_DLL

#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
#include "luaconf.h"
#include <openssl/hmac.h>
#include "hmac_lcl.h"
#include "stdafx.h"

static int forLua_Hmacsha512(lua_State *L) {

	size_t lSecret, lMsg;
	const char* secret = luaL_checklstring(L, 1, &lSecret);
	const unsigned char* msg = (const unsigned char*)luaL_checklstring(L, 2, &lMsg);

	HMAC_CTX ctx;
	HMAC_CTX_reset(&ctx);
	HMAC_Init_ex(&ctx, secret, lSecret, EVP_sha512(), NULL);

	HMAC_Update(&ctx, msg, lMsg);

	unsigned char result[129];
	unsigned int result_len = 129;
	HMAC_Final(&ctx, result, &result_len);

	lua_pushlstring(L, (const char*)result, result_len);

	return 1; 
}



LUALIB_API int __declspec(dllexport) luaopen_Hm512(lua_State* L) {
	lua_newtable(L);
	lua_pushstring(L, "Hm512");
	lua_pushcfunction(L, forLua_Hmacsha512);
	lua_rawset(L, -3);

	return 1;
}

```

this code need to include in Additional Dependency of Linker of properties of the project
the previously compiled into static library the Hmac sources from `\openssl-master\crypto\hmac`
and Lua51.lib ( or Lua53.lib or othe version of Lua)

After i compiled my project into DLL naming it for example Hm512 - Hm512.dll i  tried to use it in lua script to get Hmac Sha-512  hash, for this it needs to put libcrypto-3.dll  and compiled Hmac512.dll in the folder of Lua interpreter binaries
Lua script looks like this:
```
hm = require ("Hm512")

x=hm.Hm512("sfgds","drgsd")
```
after trying to execute this script it always gives me error and Windows suggest me an option - stops the program Lua.exe or debug it, if i choose to debug it with Visual Studio i see this:
https://cloud.mail.ru/public/EudE%2FSr82auPUz
https://cloud.mail.ru/public/G9MM%2FLxkm1Jbq3
So the C code stops on the error in string -  
```
if (!EVP_MD_CTX_test_flags(ctx, EVP_MD_CTX_FLAG_KEEP_PKEY_CTX))      
```
Unhandled exception thrown: read acces violation. ctx was 0xCCCCCCCC 
![Ashampoo_Snap_29 октября 2019 г _20h44m47s_026_](https://user-images.githubusercontent.com/21098903/67794144-14957400-fa74-11e9-916d-e9e4748b7c18.jpg)

![Ashampoo_Snap_29 октября 2019 г _20h06m00s_025_](https://user-images.githubusercontent.com/21098903/67793827-7b665d80-fa73-11e9-9019-c938bccd0a58.jpg)

by calling function   EVP_MD_CTX_test_flags
from the \openssl-master\crypto\evp\digest.c  line 910:
```
int EVP_MD_CTX_test_flags(const EVP_MD_CTX *ctx, int flags)
```

So i tried to build my Hm512.dll library with previous versions of OpenSSL and its libcrypto.dll, of openssl  - 1.1.1d,  1.1.0l and others, and to execute my Lua script with newly builded Hm512.dll library on its sources and with libcrypto.dll  of its version openssl, and libcrypto.dll of all version of OpenSSL gives me the same error:
```
if (!EVP_MD_CTX_test_flags(ctx, EVP_MD_CTX_FLAG_KEEP_PKEY_CTX))      
```
Unhandled exception thrown: read acces violation. ctx was 0xCCCCCCCC  

by calling function   EVP_MD_CTX_test_flags
from the \openssl-master\crypto\evp\digest.c  line :
```
int EVP_MD_CTX_test_flags(const EVP_MD_CTX *ctx, int flags)
```
How it may be that your library throwns error if try to use it externally?

**Comment by barmaley997** [comment]
> Do I understand correctly, that Hm512.dll is a compilation of the source from OpenSSL's
No, Hm512.dll is compilated from my own code that i posted above, Hm512.dll uses
hmac.h, hmac_lcl.h, and hmac.lib that i compiled myself  from the sources in openssl-master\crypto\hmac\  - hmac.c and hm_ameth.c, as a resut my Hm512.dll needs libcrypto-3.dll from openssl-master\apps\

**Comment by barmaley997** [comment]
No, Hm512.dll is compilated from my own code that i posted above, Hm512.dll uses
hmac.h, hmac_lcl.h, and hmac.lib that i compiled myself  from the sources in openssl-master\crypto\hmac\  - hmac.c and hm_ameth.c, as a resut my Hm512.dll needs to work  libcrypto-3.dll from openssl-master\apps\

**Comment by levitte** [comment]
Well, the main problem is this line:

``` C
   HMAC_CTX ctx;
```

That leaves `ctx` uninitialized, so you get whatever happens to already exist on the stack, and apparently, there's a pointer in there that is `0xCCCCCCCC` when you probably expected it to be NULL.

Either way, since 1.1.0, the `HMAC_CTX` should be allocated dynamically using `HMAC_CTX_new()`.  That will also mean that you won't have to compile the `crypto/hmac` source into a separate library.

**Comment by mspncp** [comment]
> there's a pointer in there that is 0xCCCCCCCC 

FWIW: the value is not by chance. It is typical for Visual Studio debug builds hat newly allocated memory is filled with nonzero patterns. (Among other reasons, to fool NULL checks and force crashes.) So if you see that pattern in the debugger, it means the memory is uninitialized. The [CRT Debug Heap](https://docs.microsoft.com/en-us/visualstudio/debugger/crt-debug-heap-details?view=vs-2019#BKMK_Types_of_blocks_on_the_debug_heap) uses 0xCD as fill pattern for new memory, 0xDD for freed memory, and 0xFD for "NoMansLand", the overrun buffer. And I recall that the Microsoft Foundation Classes (MFC) used 0xCC instead of 0xCD.

**Comment by levitte** [comment]
Uhmmm, @mspncp? In the code shown, the `HMAC_CTX` is stack allocated...

**Comment by mspncp** [comment]
> the `HMAC_CTX` is stack allocated..

Agreed. Sorry for talking too much about heaps. I was too much focused on explaining the patterns.

Nevertheless, something does not fit together in the description. If he had really passed `&ctx` for a stack based variable, then the pointer could never be 0xCCCCCCCC.

**Comment by levitte** [comment]
Yup, and that's probably because `ctx.md` happen to be an address to newly allocated memory (if your patterns are correct)

**Comment by mspncp** [comment]
> Yup, and that's probably because `ctx.md` happen to be an address to newly allocated memory (if your patterns are correct)

Or maybe it's just that the stack allocated `HMAC_CTX` structure is filled entirely with the 0xCC pattern by the compiler, because it not gets initialized explicitly, whence `md_ctx` and `i_ctx`, and `o_ctx` are filled with the 0xCC pattern, too.

```C
struct hmac_ctx_st {
    const EVP_MD *md;
    EVP_MD_CTX *md_ctx;
    EVP_MD_CTX *i_ctx;
    EVP_MD_CTX *o_ctx;
    unsigned int key_length;
    unsigned char key[HMAC_MAX_MD_CBLOCK_SIZE];
};
```

Oneof those pointers then get passed to `EVP_MD_CTX_test_flags()`, causing the crash. Does that make sense to you?

**Comment by levitte** [comment]
Yup, makes total sense.  I hope this all makes sense to @barmaley997

**Comment by mspncp** [comment]
The function `HMAC_CTX_reset()` does what its name says, it resets an already initialized context by calling `hmac_ctx_cleanup()`

https://github.com/openssl/openssl/blob/0a4d6c67480a4d2fce514e08d3efe571f2ee99c9/crypto/hmac/hmac.c#L184-L192

That's where the uninitialized pointers get dereferenced:

https://github.com/openssl/openssl/blob/0a4d6c67480a4d2fce514e08d3efe571f2ee99c9/crypto/hmac/hmac.c#L146-L154

**Comment by barmaley997** [comment]
> The function `HMAC_CTX_reset()` does what its name says, it resets an already initialized context by calling `hmac_ctx_cleanup()`. But the provided context is not initialized.

I tried to initialize it by HMAC_CTX ctx = { 0 }; instead of HMAC_CTX ctx;

so my code looks like this:
```
#define LUA_LIB
#define LUA_BUILD_AS_DLL

#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
#include "luaconf.h"
#include <openssl/hmac.h>
#include "hmac_lcl.h"

static int forLua_Hmacsha512(lua_State *L) {

	size_t lSecret, lMsg;
	const char* secret = luaL_checklstring(L, 1, &lSecret);
	const unsigned char* msg = (const unsigned char*)luaL_checklstring(L, 2, &lMsg);

	HMAC_CTX ctx = { 0 };
	HMAC_Init_ex(&ctx, secret, lSecret, EVP_sha512(), NULL);
	HMAC_Update(&ctx, msg, lMsg);

	unsigned char result[129];
	unsigned int result_len = 129;
	HMAC_Final(&ctx, result, &result_len);
	HMAC_CTX_reset(&ctx);

	lua_pushlstring(L, (const char*)result, result_len);

	return 1; 
}

LUALIB_API luaopen_Hm512(lua_State* L) {
	lua_newtable(L);
	lua_pushstring(L, "Hm512");
	lua_pushcfunction(L, forLua_Hmacsha512);
	lua_rawset(L, -3);

	return 1;
}
```
but it gives me other error \openssl-master\crypto\evp\evp_lib.c  line 905:

![photo_2019-10-31_09-23-14](https://user-images.githubusercontent.com/21098903/67924213-e913a600-fba7-11e9-9d2f-e9a5a8b91c24.jpg)

May be your could be so pleased to help me to correct my C code to get it work right,
cause i am only beginner in C and very weak C programmer ))))))

**Comment by mattcaswell** [comment]
> Hm512.dll uses
hmac.h, hmac_lcl.h, and hmac.lib that i compiled myself from the sources in openssl-master\crypto\hmac\ - hmac.c and hm_ameth.

Don't do this! The *_lcl.h files are internal only and are not intended for external application use. If you dive under the covers and start using these files directly then all bets are off...we really can't support you.

As @levitte said above:

> Either way, since 1.1.0, the `HMAC_CTX `should be allocated dynamically using `HMAC_CTX_new()`.

So your code needs to look something like this (error checking omitted for brevity):

```
   HMAC_CTX *ctx = HMAC_CTX_new();

   HMAC_Init_ex(ctx, ...);
   HMAC_Update(ctx, ...);
   HMAC_Final(ctx, ...);

   HMAC_CTX_free(ctx);
```

**Comment by mspncp** [comment]
FWIW: the OpenSSL Wiki  has a page explaining the most important [API changes between OpenSSL versions 1.0.2 and 1.1.0](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes).

**Comment by barmaley997** [comment]
> So your code needs to look something like this

I've corrected my code with your suggestion above and now it works! I am very grateful for your help! Thank you very much!

**Comment by levitte** [comment]
For a beginning C programmer, that was a quick turn-around!  Good for you.

Closing this now

**Comment by barmaley997** [comment]
A hint for all who will want to use the example above in Lua:
output result of compiled dll from code above is in byte code, to use it needs to be converted  into string from hex value of every byte like this:
```
hm = require ("Hm512")    --(Hm512 - Hm512.dll)
x=hm.Hm512(Some_key_to_be_hashed_by_SHA-512,  Some_key_for_HMAC)
-- Some_key_to_be_hashed_by_SHA-512 - string parameter
-- Some_key_for_HMAC                           - string parameter
x1=""
for i=1,#x do
x1 =x1..string.format("%02x", string.byte (x,i))
end

-- x1 - is the output hash  ready to be used
```
