### ISSUE TITLE
How to upgrade from sync openssl to asynchronous openssl

### ISSUE THREAD

**Issue by l-w-p** [openssl/openssl#10306]
Can you provide a simple demo for reference?
How to upgrade from sync openssl to asynchronous openssl

**Comment by mattcaswell** [comment]
Please clarify your question:

- What OpenSSL version are you using?
- Do you have an asynchronous capable engine?
- By "asynchronous openssl" do you mean you want to do asynchronous SSL/TLS, or asynchronous crypto?

**Comment by l-w-p** [comment]
I want to use openssl 1.1.1 and intel QAT Engine for asynchronous ssl/tls

**Comment by mattcaswell** [comment]
The main differences between normal SSL/TLS operations and async SSL/TLS is that you need to:

- Load your async engine e.g. typically via a call to ENGINE_by_id()
https://www.openssl.org/docs/man1.1.1/man3/ENGINE_by_id.html

- use `SSL_MODE_ASYNC` and be prepared to handle `SSL_ERROR_WANT_ASYNC` in any calls to SSL_get_error().
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_mode.html
https://www.openssl.org/docs/man1.1.1/man3/SSL_get_error.html

- Optionally you may want to check whether the async engine is ready to resume an operation. You can use SSL_get_all_async_fds() for that in conjunction with a call such as `select` or `poll`.
https://www.openssl.org/docs/man1.1.1/man3/SSL_get_all_async_fds.html
