### ISSUE TITLE
Crash seen in X509_VERIFY_PARAM_free()

### ISSUE THREAD

**Issue by Jayashankara-DM-135** [openssl/openssl#10315]
I have application which establish secure connection to server by using curl.
Curl intern will invoke custom x509 certificate verification library to verify server certificates. Once curl returns from my custom library it's crashing at X509_VERIFY_PARAM_free.

Back trace:
(gdb) bt
#0 __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1 0xb6054428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#2 0xb6055132 in __GI_abort () at abort.c:89
#3 0xb67de814 in fsmSig::sigCatcher (signal=2, infoPtr=0xb611b088 , uCntxtPtr=0x1)
at /home/ws/../source/linux-infra/infra/C/sig/src/sigApi.cpp:153
#4
#5 __GI___libc_free (mem=0x75726f00) at malloc.c:2940
#6 0xb6453be0 in X509_VERIFY_PARAM_free ()
from /home/ws/root/usr/lib/libcrypto.so.1.1
#7 0xb650680e in SSL_free ()
from /home/ws/root/usr/lib/libssl.so.1.1
#8 0xb6583936 in Curl_sasl_continue ()
from /home/ws/root/usr/lib/libcurl.so.4.4.0
#9 0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

code sniff:
//App entry point
void init() {

curl_easy_setopt(pEasy_handle, CURLOPT_SSL_CTX_FUNCTION, custom_x509_cert_verfiy_callback);
cout << "Before easy perform";
CURLcode ret = curl_easy_perform(pEasy_handle); ==> crash seen immediately after returning from custom x509 certificate verify lib.
cout << "after easy perform" ; ==> This print is not seen.
}

CURLcode custom_x509_cert_verfiy_callback() {
SSL_CTX_set_verify(pctx, (SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT | SSL_VERIFY_CLIENT_ONCE), NULL);
SSL_CTX_set_cert_verify_callback(pctx, TLSRestriction::verifyServerCertificate, NULL)

return CURL_OK;
}

// custom x509 cert verify library
int verifyServerCertificate() {
return 1;
}

Curl version : 7.63.0
Openssl version: 1.1.1c
Operating system : Ubuntu 16.04

Please let me know why curl is crashing at "curl_easy_perform" always .

Thanks

**Comment by Jayashankara-DM-135** [comment]
Library is property source code, Basically It calls Openssl 1.1.1c API to verify certificate validity , revocation status(CRL)
I started seeing this issue after adding certificate revocation code to x509 cert verify lib.

Please let me know if you required more information on this.

**Comment by mattcaswell** [comment]
I'd suggest this question is probably better asked on a curl forum. While it is possible there is an issue in OpenSSL, it seems more likely to me to be a problem somewhere between your application and curl. The curl developers will be in a better position to understand the curl context of this problem - and if that subsequently turns out to be an OpenSSL issue then a bug issue can be raised at that point.
