### ISSUE TITLE
The numbits argument is not documented in openssl genrsa -help

### ISSUE THREAD

**Issue by MaharishiCanada** [openssl/openssl#10313]
Using OpenSSL 1.1.1c  28 May 2019 in Ubuntu 19.10, I noticed that  the output of `openssl genrsa -help` does not document the numbits argument, which is documented  here https://www.openssl.org/docs/man1.0.2/man1/genrsa.html . This is perhaps normal.

**Comment by richsalz** [comment]
You are pointing to the 1.0.2 version.  But all three versions do document it; it's right after the -engine documentation. :)

**Comment by mattcaswell** [comment]
No, the reporter seems to be correct. I see no mention of it in the "-help" output:

````
$ openssl genrsa -help
Usage: genrsa [options]
Valid options are:
 -help               Display this summary
 -3                  Use 3 for the E value
 -F4                 Use F4 (0x10001) for the E value
 -f4                 Use F4 (0x10001) for the E value
 -out outfile        Output the key to specified file
 -rand val           Load the file(s) into the random number generator
 -writerand outfile  Write random data to the specified file
 -passout val        Output file pass phrase source
 -*                  Encrypt the output with any supported cipher
 -engine val         Use engine, possibly a hardware device
 -primes +int        Specify number of primes
 -verbose            Verbose output
````

**Comment by MaharishiCanada** [comment]
I was not clear apparently.  I was pointing to the output  of `openssl genrsa -help` in OpenSSL 1.1.1c 28 May 2019 in Ubuntu 19.10. What was confusing is that I also pointed to the online documentation, but it was only to say that IT IS documented elsewhere.  Again, maybe it is normal, something well known that nobody cares about and I am just making  a full of myself by showing that I just realized that now...

**Comment by richsalz** [comment]
Thanks for the clarification.  You are not making a fool of yourself!  I made one of myself by not reading carefully.

In general, the -help option only documents the options, but it's not consistent.  Using the #9953 stuff, we could add a "Parameters" section to those commands that take parameters and document them.

**Comment by mattcaswell** [comment]
> In general, the -help option only documents the options, but it's not consistent.

I really think it should list all arguments - not just the option flags.

**Comment by richsalz** [comment]
> I really think it should list all arguments - not just the option flags.

I'd be willing to do that. I had already committed to documenting all the missing flags.  But I need all of my other doc PR's to get reviewed first.

**Comment by richsalz** [comment]
I have the infrastructure to do this, here's sample output:
```
; ./apps/openssl genrsa --help
Usage: genrsa [flags] numbits

General options:
 -help               Display this summary
 -engine val         Use engine, possibly a hardware device

Input options:
 -3                  Use 3 for the E value
 -F4                 Use F4 (0x10001) for the E value
 -f4                 Use F4 (0x10001) for the E value

Output options:
 -out outfile        Output the key to specified file
 -passout val        Output file pass phrase source
 -primes +int        Specify number of primes
 -verbose            Verbose output
 -*                  Encrypt the output with any supported cipher

Random state options:
 -rand val           Load the file(s) into the random number generator
 -writerand outfile  Write random data to the specified file

Parameters:
 numbits             Size of key in bits
;
```

I need to have #9953 merged before I work on this PR.

**Comment by mattcaswell** [comment]
> I have the infrastructure to do this, here's sample output:

That looks really nice!

**Comment by richsalz** [comment]
#10371 is the fix for this.  Needs #9953 merged first.
