### ISSUE TITLE
A little advice about boringssl‘ url

### ISSUE THREAD

**Issue by GQBBBB** [openssl/openssl#10322]
Hi!
I recommend replacing the boringssl url in the `.gitmodules` file from `https://boringssl.googlesource.com/boringssl` to `https://github.com/google/boringssl.git`

Because sometimes the link `https://boringssl.googlesource.com/boringssl` will fail, this problem occurs when I build `riscv-tool-chain`. And I have seen people raise this question elsewhere.

**Comment by mattcaswell** [comment]
PRs would be welcome for this.
