### ISSUE TITLE
should openssl-cmds.pod be named openssl-commands.pod?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10325]
I don't think that "cmds" is a worthwhile abbreviation.

And also, should (heh) openssl-commands be in the NAME section?  After all, it's installed as openssl-commands.1  "find-doc-nits -l" complains about it not being there.  Should we add it or hack on find-doc-nits to not complain?

**Comment by mspncp** [comment]
FWIW: I prefer the long name and I would add it to the NAME section. But the latter would only make sense if openssl-commands(1) would be mentioned elsewhere (e.g. in appropriate SEE ALSO sections).

**Comment by mspncp** [comment]
BTW: why not call it openssl-app(1)?

**Comment by levitte** [comment]
The confusing thing about mentioning it in NAME is that someone might mistake that for meaning that there *is* a command `openssl commands` or `openssl app`...

(personally, I would prefer *not* to have that page at all, but since it serves as a connector to older names...)

**Comment by richsalz** [comment]
I think ```openssl-app``` is just as bad as ```cmds```  If you know what it means, you don't need it :)  Look at "man -k command" for example.

I thought this was a temporary measure until the old names went away, so i don't know where it would make sense to add "SEE ALSO" references.  Where you thinking of anything in particular?

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input
