### ISSUE TITLE
Move EC code to provider

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#10351]
The EC code needs to be available inside the providers in order to support the FIPS provider.

This should be done in a manner similar to how BN was done via `build.conf` rather than relocating source files.

**Comment by richsalz** [comment]
> This should be done in a manner similar to how BN was done via `build.conf` ...

Do you mean crypto/bn/build.info ?

**Comment by levitte** [comment]
Yes, that's what he meant

**Comment by InfoHunter** [comment]
What is the progress of this? Ping @romen

**Comment by romen** [comment]
@InfoHunter I am still in the preliminary steps as I have been quite busy since we last met.

I see it might be blocking the SM2 move to providers, and I am sorry for the delay this is causing!

**Comment by InfoHunter** [comment]
No worries, dude. I just want to check if there is something that I can help to move this faster, like implementing part of the `ec_kmgmt.c` for instance...

But I probably need more input from you - could you share some thoughts on this to me?

**Comment by paulidale** [comment]
I'd also suggest @levitte for input about the key manager part.

**Comment by InfoHunter** [comment]
> I'd also suggest @levitte for input about the key manager part.

Good idea.

**Comment by InfoHunter** [comment]
It seems it's not very complicated by following what *dh_kmgmt.c* does to implement the EC key management. Maybe some details are not known by me yet...

**Comment by levitte** [comment]
For the keymgmt bits, yeah, that should be easy by looking at others, *as well as* looking at the corresponding `_ameth.c` file (where the legacy->provider export function needs to be implemented anyway)

**Comment by romen** [comment]
Fixed via #10631 !
