### ISSUE TITLE
Move SM2 digest signature implementation to provider.

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#10357]
Move the SM2 digest signature code to `providers/implementation/signature`. The existing `dsa.c` file should give a general idea as to the bulk of the changes required.

This will probably need #10351 done first.

**Comment by InfoHunter** [comment]
I will take this and #10358 after the EC-in-privoder part has been done

**Comment by romen** [comment]
Fixed with #12536 (formerly #11248).
