### ISSUE TITLE
Move SM2 asymmetric cipher implementation to provider.

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#10358]
Move the SM2 asymmetric cipher code to `providers/implementation/asymciphers`. The existing `rsa.c` file should give a general idea as to the bulk of the changes required.

This will definitely need #10152 merged first.
This will probably also need #10351 done first.

**Comment by InfoHunter** [comment]
Interesting task...

**Comment by InfoHunter** [comment]
What is the estimated deadline of this task?

**Comment by paulidale** [comment]
Yesterday would be good :)

Moving algorithms hasn't proven to be too difficult in most cases.  The get and set params calls that replace the ctrl ones are the worst of the effort but even they are relatively mechanical.

**Comment by paulidale** [comment]
We estimated three days of effort (not calendar days) for this one.  It will requite the asym cipher framework in #10152 to be committed before it can be done.

**Comment by InfoHunter** [comment]
> We estimated three days of effort (not calendar days) for this one. It will requite the asym cipher framework in #10152 to be committed before it can be done.

I probably could take a look into this after #10152 has been merged. Perhaps during the IETF 106 week would be a good time to do this...

**Comment by paulidale** [comment]
If you could, it would be ideal.

**Comment by paulidale** [comment]
#10152 has been merged, this is unblocked I think.

**Comment by InfoHunter** [comment]
> #10152 has been merged, this is unblocked I think.

Great, will do soon

**Comment by InfoHunter** [comment]
Guys, I started looking into this yesterday and I found it seems that we should implement the *keymgmt* part first and then the signature/asymmetric-cipher of SM2 into provider.

But it SM2 relies on EC key, so should it be something like *ec_kmgmt* finished in advance? Correct me if I have a wrong understanding with provider...

**Comment by romen** [comment]
This was duplicated as #12908, fixed by #12913 .
