### ISSUE TITLE
Why did ERR_remove_thread_state() change signature in 1.1.0-pre*?

### ISSUE THREAD

**Issue by gstrauss** [openssl/openssl#1036]
Why did ERR_remove_thread_state() change signature in 1.1.0-pre*? (8509dcc9)
While the arg is not used, this change breaks compatibility with previous versions.
(OpenSSL_1_0_2h) crypto/err/err.h:void ERR_remove_thread_state(const CRYPTO_THREADID *tid);
(OpenSSL_1_1_0-pre5) include/openssl/err.h:void ERR_remove_thread_state(void);

**Comment by richsalz** [comment]
It was changed of the overhaul of all thread-state management.

**Comment by gstrauss** [comment]
@richsalz: Thank you for the quick response.  However, while you provided the summary of actions that resulted in the change (refactoring), I do not think that a satisfactory justification was provided for **breaking existing code**.  The performance "overhead" of passing (and ignoring) an additional argument is very small and unlikely to be noticed.  If that is your concern, then rename the function implementation (void)ERR_remove_thread_state_v(void), and add to the header:
`#ifdef ERR_remove_thread_state(x) ERR_remove_thread_state_v()`

Instead, code using ERR_remove_thread_state() must now #ifdef using OPENSSL_VERSION_NUMBER to pass the correct number of arguments to the function and be portable to older and newer versions of openssl.  This is unnecessary work as well as extra lines of code and preprocessor directives, making code more difficult to read.

Do you really think that breaking this interface for a little bit of code cleanup more important than breaking existing usage by clients of openssl?  There is no security requirement for this specific change, nor is there a performance issue.  Either might be plausible justifications, but neither are present here.

openssl 1.1.0-pre* is still in pre-release stage, so I am hoping that you will reconsider the unnecessary interface change prior to the release of openssl 1.1.0.  I am happy to code up a patch restoring the previous interface, or replacing it with the macros above.  I'll do so if there is a chance that the patch will be accepted.

**Comment by richsalz** [comment]
I suggest you bring this up on the openssl-dev mailing list.  Many other things "broke" too.

**Comment by richsalz** [comment]
Also, note that the old version let you delete state for any thread, which is no longer the case.  Changing the API at build-time prevents strange run-time errors.

**Comment by gstrauss** [comment]
Actually, changing the API at build-time does not necessarily prevent anything.  Unless the end-user is compiling with -Werror (which is what I do) or equivalent, the C compiler might simply produce a warning, which can be ignored.  Ignoring compiler errors is not recommended, but unfortunately occurs frequently in practice.

I appreciate your responses, and think it best if I take your advice and follow up on the openssl-dev mailing list.

**Comment by ekasper** [comment]
cc @davidben

**Comment by ghedo** [comment]
@gstrauss the function is defined as `void ERR_remove_thread_state(void)` not `void ERR_remove_thread_state()` so I think an error is generated (can't really speak for all compilers though).

In any case a warning is probably better than nothing at all.

**Comment by davidben** [comment]
Changing the signature without changing the name can't be as easily smoothed over with a "polyfill"-like approach as wpa_supplicant has done here:
https://w1.fi/cgit/hostap/tree/src/crypto/tls_openssl.c#n54

You could imagine going further and having a common "openssl-compat" header-only library of polyfills that consumers drop into their project. (I started toying with this, but haven't had the time to polish it up and send it to you all yet.) But because this change both changed the signature and didn't change the name, the polyfill approach doesn't work well.

If, after changing the name, you want to keep the old name around for compatibility but not define `CRYPTO_THREADID`, you can do something like:
```
struct OPENSSL_must_be_null_st;
void ERR_remove_thread_state(struct OPENSSL_must_be_null_st *unused);
```
No one ever uses it with non-`NULL` anyway. (I used this trick in a few places in BoringSSL. Though it seems our `ERR_remove_thread_state` is just a runtime check for `NULL`. I should probably go switch that.)

**Comment by richsalz** [comment]
I like that trick.

**Comment by levitte** [comment]
This became a topic of discussion in the team and lead to some work.  See commit 21e001747d4a246827ad432fc508d67ac404ecdb

I hope that's going to be satisfactory for everyone.

**Comment by davidben** [comment]
lgtm. (Ours calls `ERR_clear_error` in case any consumer was relying on it also clearing the error state, but I think a no-op is reasonable too.)

**Comment by gstrauss** [comment]
@richsalz @davidben @levitte
Thanks for both the code and doc updates.  The cleanup code in lighttpd now looks like this
https://redmine.lighttpd.net/projects/lighttpd/repository
https://redmine.lighttpd.net/projects/lighttpd/repository/revisions/1cd31ae2ccf9e839325ccafdb72108e6b2d39745
```
              #if   OPENSSL_VERSION_NUMBER >= 0x10100000L \
                && !defined(LIBRESSL_VERSION_NUMBER)
                /*(OpenSSL libraries handle thread init and deinit)
                 * https://github.com/openssl/openssl/pull/1048 */
              #elif OPENSSL_VERSION_NUMBER >= 0x10000000L
                ERR_remove_thread_state(NULL);
              #else
                ERR_remove_state(0);
              #endif
```
(FYI: libressl pretends to be openssl 2.0.0)

**Comment by davidben** [comment]
> (FYI: libressl pretends to be openssl 2.0.0)

You probably want to talk to them about that. I don't think anyone on this thread works on LibreSSL. It would be much better for them to pretend to be the version they are most API-compatible with.

**Comment by levitte** [comment]
> (FYI: libressl pretends to be openssl 2.0.0)

I was a bit provoked reading this...  but, I just downloaded their latest (2.3.4), and it seems they've changed that.  They still use the command name `openssl`, but their `openssl version` reports `LibreSSL 2.3.4`.  Doesn't look like it's worth making a stink.

**Comment by gstrauss** [comment]
I agree that they should pretend to be the openssl version with which they are most compatible.
It would make more sense if they provided something similar to OPENSSL_API_COMPAT

FYI: from libressl-2.3.4.tar.gz:
```
include/openssl/opensslv.h:#define OPENSSL_VERSION_NUMBER	0x20000000L
include/openssl/opensslv.h:#define LIBRESSL_VERSION_NUMBER	0x2030300fL
```
As you can see above, for preprocessor directives checking OPENSSL_VERSION_NUMBER, LibreSSL is pretending to be OpenSSL 2.0.0, which does not currently exist (at least to my knowledge).

**Comment by levitte** [comment]
Aha, yeah, ok
