### ISSUE TITLE
make: *** No rule to make target 'uninstall'.  Stop.

### ISSUE THREAD

**Issue by MESWEB** [openssl/openssl#10373]
Open SSL v 1.0.2t
Can't uninstall.

**Comment by mattcaswell** [comment]
There is no uninstall support in 1.0.2. That was added in this commit which first appeared in OpenSSL 1.1.0.

https://github.com/openssl/openssl/commit/9405a9a2e1594

For 1.0.2 you must uninstall files manually.

**Comment by MESWEB** [comment]
> There is no uninstall support in 1.0.2. That was added in this commit which first appeared in OpenSSL 1.1.0.
> 
> [9405a9a](https://github.com/openssl/openssl/commit/9405a9a2e1594)
> 
> For 1.0.2 you must uninstall files manually.

Any documentation to do that or I should scan all files by my eyes?

**Comment by mattcaswell** [comment]
> Any documentation to do that 

Unfortunately not.

**Comment by paulidale** [comment]
Closing this since nothing has happened for ages and I doubt any more will.
