### ISSUE TITLE
OpenSSL 1.0.2h gcc-arm 4.8 fails to build

### ISSUE THREAD

**Issue by madduci** [openssl/openssl#1037]
Hi

similar to 1.0.2g, the newer version fails to compile when using gcc-arm 4.8:

http://pastebin.com/zuuLg8S9

Versions prior to 1.0.2g can compile perfectly.
Build environment: Debian x64, ggc-arm 4.8.2

**Comment by levitte** [comment]
It's not entirely clear to me how you configured.  I just tried this, and it built flawlessly:

```
CROSS_COMPILE=arm-linux-gnueabi- ./Configure linux-armv4
make
```

The package I used is `gcc-arm-linux-gnueabi` with all its dependencies, on Ubuntu 14.04.

**Comment by levitte** [comment]
That was with master, btw...

**Comment by levitte** [comment]
Same flawless result with 1.0.2...

**Comment by levitte** [comment]
Making an educated guess at how you're doing things, I tried this as well in the 1.0.2 branch:

```
CC=arm-linux-gnueabi-cc AR=arm-linux-gnueabi-ar \
RANLIB=arm-linux-gnueabi-ranlib LD=arm-linux-gnueabi-ld \
./Configure linux-armv4
```

Still building flawlessly.

So, I have to ask you for an exact description of what you did.  That includes:

1.  The Debian package you used to get gcc-arm
2.  The exact configuration command, including the environment variables you defined
3.  A verbose build log (don't use `--silent` with `make`)

**Comment by madduci** [comment]
Thanks for the reply.

I have tested a clean environment (always with Debian) and I use a proprietary SDK and which ships gcc 4.8.2.  
I build OpenSSL using CMake as wrapper for it (https://github.com/madduci/CppDevLibs) and it builds successfully for x86 architecture, both windows and linux, but since version 1.0.2g, it fails on ARM (I was able to compile it for versions d-e-f without problems).  I give the path to the cross compiler to CMake and it effectively uses it (I've tested it against Boost libraries as well)
All it's caused by those not defined functions in **s_server.c** file, as in the pastebin, not defined in linking phase

**Comment by levitte** [comment]
Yes, I understand what the log show, but I need to know that stuff that's hidden to figure it all out.

So, `cmake` huh?  In that case, I'm going to ask you to do a verbose `make`.  I think it's done like this for a cmake based Makefile:

    make VERBOSE=1

**Comment by madduci** [comment]
At the same pastebin, I've written the verbose compiling steps

http://pastebin.com/zuuLg8S9

I've tested it with -03 and with -02 in release mode but the result is the same

**Comment by richsalz** [comment]
cmake, custom sdk, newer version of gcc... starting to feel like a custom port, not something we support.

**Comment by levitte** [comment]
@madduci, I can only assume that this is long past, and I hope you figured our the problem.
This issue is now so old that I'm closing it, and should there be problems to deal with, feel free to raise a new issue.
