### ISSUE TITLE
Using openssl in rc.local in the container will fail probabilistically

### ISSUE THREAD

**Issue by liaojm930** [openssl/openssl#10384]
I want to use openssl to generate the secret key, the command is as follows:

```bash
cd /root
openssl genrsa -out server.key 2048 2>&1 >/gen_server_cert.log
```

I want it to run automatically at boot, so put the above script in /etc/rc.local. But it will fail probabilistically, the result is as follows:

![image](https://user-images.githubusercontent.com/42411422/68445886-274b3e00-0216-11ea-9b25-d798592e37fc.png)

There is no problem when I use this in a virtual machine, but there are occasional problems in the container.

I looked at the code and it should be that the process exited during the production of prime numbers.

I don't know why it failed. Does anyone know what the problem is?

**Comment by levitte** [comment]
Looking at that log, I can only get to the same conclusion, that the process was killed before key generation could complete.  So the question is, why did the container die prematurely?

This doesn't look like an OpenSSL issue, though.

**Comment by mspncp** [comment]
Maybe it was killed because it was stuck with low entropy?
