### ISSUE TITLE
Provider callbacks constification

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#10397]
This is an aggregate issue for various questions regarding provider callback constification.

It seems reasonable that the argument of the `OSSL_FUNC_DIGEST_DUPCTX` (and I suppose, all the others _DUPCTX) should be `const`.

**Comment by nhorman** [comment]
We didn't do this 6 years ago, missing 3.0, 4.0 is looming and it doesn't seem to me like something we will get to.

Marking as inactive, to be closed at the end of 3.4 dev, barring further input
