### ISSUE TITLE
ordinals for non-released or new functionality

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#10395]
Using "markers" for not yet released functions is very good idea. Dunno how this will impact builds where is used def-file but this is out of scope to this request.
Question is why the file contain records with NOEXIST::FUNCTION?
Let review some of them:
```
$ grep NOEXIST util/libcrypto.num 
OPENSSL_memcmp                          466     3_0_0   NOEXIST::FUNCTION:
ERR_put_error                           1027    3_0_0   NOEXIST::FUNCTION:
EVP_MAC_CTX_new_id                      ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_ctrl                            ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_vctrl                           ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_ctrl_str                        ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_str2ctrl                        ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_hex2ctrl                        ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_nid                             ?       3_0_0   NOEXIST::FUNCTION:
EVP_get_macbyname                       ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_do_all                          ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_do_all_sorted                   ?       3_0_0   NOEXIST::FUNCTION:
CRYPTO_siv128_new                       ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_init                      ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_copy_ctx                  ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_aad                       ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_encrypt                   ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_decrypt                   ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_finish                    ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_set_tag                   ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_get_tag                   ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_cleanup                   ?       3_0_0   NOEXIST::FUNCTION:SIV
CRYPTO_siv128_speed                     ?       3_0_0   NOEXIST::FUNCTION:SIV
EVP_PKEY_derive_init_ex                 ?       3_0_0   NOEXIST::FUNCTION:
ERR_put_func_error                      ?       3_0_0   NOEXIST::FUNCTION:
EVP_MAC_name                            ?       3_0_0   NOEXIST::FUNCTION:
EVP_KDF_name                            ?       3_0_0   NOEXIST::FUNCTION:
EVP_PKEY_sign_init_ex                   ?       3_0_0   NOEXIST::FUNCTION:
EVP_PKEY_verify_init_ex                 ?       3_0_0   NOEXIST::FUNCTION:
EVP_PKEY_verify_recover_init_ex         ?       3_0_0   NOEXIST::FUNCTION:
```
CRYPTO_siv128* is clear - new public header was not added to list _(defect)_.

**Request** is for functions like ERR_put_func_error, i.e. do not list non-exisiting function without assigned ordinal.

Note that some "development" functions are not removed properly _(defect)_. For instance:
```
$ grep -rw EVP_PKEY_sign_init_ex
doc/man3/EVP_PKEY_CTX_ctrl.pod:for use in an operation (for example by L<EVP_PKEY_sign_init_ex(3)>,
doc/man3/EVP_PKEY_CTX_ctrl.pod:for use in an operation (for example by L<EVP_PKEY_sign_init_ex(3)>,
doc/man3/EVP_PKEY_sign.pod:EVP_PKEY_sign_init_ex() was added in OpenSSL 3.0.
doc/man7/provider-signature.pod:functions L<EVP_PKEY_sign_init_ex(3)>, L<EVP_PKEY_sign(3)>,
util/libcrypto.num:EVP_PKEY_sign_init_ex                   ?    3_0_0   NOEXIST::FUNCTION:

```

Roumen

**Comment by paulidale** [comment]
We need to run `sed -i '/[?].*NOEXIST/d' util/libcrypto.num` before beta.

**Comment by romen** [comment]
To address the last part of the description in this issue:

> Note that some "development" functions are not removed properly _(defect)_. For instance:
> ```
> $ grep -rw EVP_PKEY_sign_init_ex
> doc/man3/EVP_PKEY_CTX_ctrl.pod:for use in an operation (for example by L<EVP_PKEY_sign_init_ex(3)>,
> doc/man3/EVP_PKEY_CTX_ctrl.pod:for use in an operation (for example by L<EVP_PKEY_sign_init_ex(3)>,
> doc/man3/EVP_PKEY_sign.pod:EVP_PKEY_sign_init_ex() was added in OpenSSL 3.0.
> doc/man7/provider-signature.pod:functions L<EVP_PKEY_sign_init_ex(3)>, L<EVP_PKEY_sign(3)>,
> util/libcrypto.num:EVP_PKEY_sign_init_ex                   ?    3_0_0   NOEXIST::FUNCTION:
> 
> ```

I forked a separated dedicated issue: #13086 `Clean up documentation added for functions added during 3.0 but since removed`

**Comment by paulidale** [comment]
An alternative suggestion: a PR that removes all the unnumbered lines and recreates them from scratch.  Some merge pain in exchange for knowing it has been done correctly.

**Comment by levitte** [comment]
I don't see the value in removing all the unnumbered lines and recreating them over that very simple sed line you displayed earlier, @paulidale.  Curiously, you called the sed line "too aggressive", I have to disagree...

**Comment by paulidale** [comment]
The sed line removes calls it shouldn't.  It trims these functions:
```
CRYPTO_siv128_new
CRYPTO_siv128_init
CRYPTO_siv128_copy_ctx
CRYPTO_siv128_aad
CRYPTO_siv128_encrypt
CRYPTO_siv128_decrypt
CRYPTO_siv128_finish
CRYPTO_siv128_set_tag
CRYPTO_siv128_get_tag
CRYPTO_siv128_cleanup
CRYPTO_siv128_speed
OPENSSL_CTX_get0_primary_drbg
OPENSSL_CTX_get0_public_drbg
OPENSSL_CTX_get0_private_drbg
EC_GROUP_new_by_curve_name_ex
EC_KEY_new_ex
EC_KEY_new_by_curve_name_ex
EVP_DigestSignInit_ex
EVP_DigestVerifyInit_ex
X509v3_cache_extensions
X509_verify_ex
X509_REQ_verify_ex
EVP_RAND_set_callbacks
```

Note, for example, that `EC_KEY_new_ex` is removed even though it is in the public header files.  I think this meets a reasonable definition of _too aggressive_.  I've not investigate if it is a bug in `make update` or something weird in that header.

**Comment by levitte** [comment]
For the ordinals file, it's not too aggressive.  If it's marked NOEXIST, it's not going to appear in the linker scripts anyway, it's just as if that ordinals line wasn't there at all in practice.

So, something's wrong with parsing ec.h, because EC_KEY_new_ex() shouldn't be marked NOEXIST.  That's a *different issue* and should be raised separately from this one (something is most probably not quite right in OpenSSL::ParseC).

**Comment by levitte** [comment]
Hah!  This was an interesting goose chase, just to discover this:

``` console
$ grep -n EC_KEY_new_ex util/libcrypto.num 
4670:EC_KEY_new_ex                           ?	3_0_0	NOEXIST::FUNCTION:EC
5124:EC_KEY_new_ex                           ?	3_0_0	EXIST::FUNCTION:EC
```

I suspect a merge that wasn't as clean as was desired...

So no, the sed line wasn't too aggressive, it rather seems to have cleaned up our mistakes...  :wink:
(and yeah, OpenSSL::Ordinals could analyse these sorts of things a bit better...)

In the mean time, I've done a fix so that mknum will automatically drop all unnumbered NOEXIST entries.

**Comment by paulidale** [comment]
Nice catch.
