### ISSUE TITLE
nmake test hang on test_comp without error

### ISSUE THREAD

**Issue by skys215** [openssl/openssl#10393]
I have compiled OpenSSL 1.1.1d on a Windows7 64bit machine with Visual Studio 2019.
What I did is pretty simple,
1. Clone the repo, switch it to 1.1.1d version
2. Run `perl Configure VC-WIN32A --prefix=C:\opensslbuild32 no-asm`
3. Run `nmake`
4. Run `nmake test`
And it hangs on `test\recipes\70-test_comp.t......`

Then I tried running it separately with command `nmake TEST=test_comp V=1`
It hangs on 
```
read R BLOCK
engine "ossltest" set.
depth=0 C=UK, O=OpenSSL Group, OU=FOR TESTING PURPOSES ONLY, CN=Test Server Cert
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C=UK, O=OpenSSL Group, OU=FOR TESTING PURPOSES ONLY, CN=Test Server Cert
verify error:num=20:unable to verify the first certificate
verify return:1
DONE
```
and it hangs.

Should it end as test failed and notice user to set the certificate location? Or just may skip this test case?
P.S. I have post a comment on [this](https://github.com/openssl/openssl/issues/10020#issuecomment-551354818) issue as well.

**Comment by skys215** [comment]
@mattcaswell Ping?

**Comment by mattcaswell** [comment]
Hmm. I cannot reproduce this.

**Comment by thenullpoynter** [comment]
I'm experiencing the same issue.  Using ActiveState Perl 5.26 and Visual Studio 2017 on Windows 10.

**Comment by skys215** [comment]
Aha, I forgot to mention I was using ActiveState Perl. But I forgot which version I was using, 5.26 or 5.28

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by nonic-coco** [comment]
Same issue, when running 'nmake test', openssl1.1.1, windows10 6-bit machine, ActiveState Perl 5.36, VS2022.

**Comment by t8m** [comment]
> Same issue, when running 'nmake test', openssl1.1.1, windows10 64-bit machine, 32bit compiler, ActiveState Perl 5.36, VS2022.

Unfortunately 1.1.1 is out of public support. Also please note that ActiveState Perl is not supported for Windows builds. We recommend to use Strawberry Perl.

**Comment by nonic-coco** [comment]
> > Same issue, when running 'nmake test', openssl1.1.1, windows10 64-bit machine, 32bit compiler, ActiveState Perl 5.36, VS2022.
> 
> Unfortunately 1.1.1 is out of public support. Also please note that ActiveState Perl is not supported for Windows builds. We recommend to use Strawberry Perl.

Thanks. I turned to Strawberry Perl and built openssl1.1.1 successfully.

**Comment by McPherran** [comment]
ActiveState Perl works well. See information here:
[Information for use of ActiveState Perl](https://github.com/openssl/openssl/issues/28090#issue-3262043268)
