### ISSUE TITLE
"micalg" digest property

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#10399]
The `micalg` digest property is a property of digest, not the digest context, for all known to me digests. It was treated as a part of context because nobody wanted to add an extra field into the EVP_MD structure. My suggestion is moving it from the digest context parameters to digest parameters.

**Comment by nhorman** [comment]
@beldmit I can see no reference to micalg as part of struct evp_md_ctx_st anywhere, going back as far as 1.0.2, so I'm not sure what you mean by the above

Given that the only references I can find to micalg are in some param construction calls, some asn1 writers and a pkcs7 test, I'm assuming this has been resolved

Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by beldmit** [comment]
The purpose of this PR is eliminating a long `case` from
https://github.com/openssl/openssl/blob/master/crypto/asn1/asn_mime.c#L158-L234

See also 
https://github.com/openssl/openssl/blob/master/crypto/evp/digest.c#L904-907

**Comment by nhorman** [comment]
I'm not sure I see the relation of that code to the statement
```
The micalg digest property is a property of digest, not the digest context, for all known to me digests.
```

Are you asking to have the EVP_MD_CTRL_MICALG eliminated and in its place an EVP_MD api added to generate it?

**Comment by beldmit** [comment]
Well. In ideal world yes. But if there is a context-level control function already, we have to keep the API and there is no sense in this refactoring.
