### ISSUE TITLE
Issue with gSOAP 

### ISSUE THREAD

**Issue by rudrakunal** [openssl/openssl#10409]
Hello Team,

We are using **OpenSSL ver. 1.1.1d** along with **gSOAP ver. 2.8.14** and application is giving a crash while creating md5 handle in **md5evp.cpp**

Whereas **OpenSSL ver. 1.0.2t** is working fine with the same version of **gSOAP**.

Please can you look into it, also let me know if you need any further details.
Below is the code snippet for your reference.

```
//gSOAP file - httpda.cpp
static int http_da_parse(struct soap *soap)
{ 
	struct http_da_data *data = (struct http_da_data*)soap_lookup_plugin(soap, http_da_id);
  
	if (!data)
		return SOAP_PLUGIN_ERROR;
	
	data->qop = NULL;
	
	/* HTTP GET w/o body with qop=auth-int still requires a digest */
	md5_handler(soap, &data->context, MD5_INIT, NULL, 0);
/*
heap crash in below line with OpenSSL ver. 1.1.1d but working fine with 1.0.2t
*/
	md5_handler(soap, &data->context, MD5_FINAL, data->digest, 0);

	if ((soap->error = data->fparse(soap)))
		return soap->error;

	if (data->qop && !soap_tag_cmp(data->qop, "auth-int"))
	{
		if (soap->fpreparerecv != http_da_preparerecv)
		{
			data->fpreparerecv = soap->fpreparerecv;
			soap->fpreparerecv = http_da_preparerecv;
		}

		if (soap->fpreparefinalrecv != http_da_preparefinalrecv)
		{
			data->fpreparefinalrecv = soap->fpreparefinalrecv;
			soap->fpreparefinalrecv = http_da_preparefinalrecv;
		}

		md5_handler(soap, &data->context, MD5_INIT, NULL, 0);
	}
 
	return SOAP_OK;
}

//////////////////////////////////////////////////////////////

//gSOAP file md5evp.cpp
int md5_handler(struct soap *soap, void **context, enum md5_action action, char *buf, size_t len)
{ EVP_MD_CTX *ctx;
  unsigned char hash[EVP_MAX_MD_SIZE];
  unsigned int size;
  switch (action)
  { case MD5_INIT:
#ifdef WITH_OPENSSL
      OpenSSL_add_all_digests();
#endif
      if (!*context)
      { *context = (void*)SOAP_MALLOC(soap, sizeof(EVP_MD_CTX));
        EVP_MD_CTX_init((EVP_MD_CTX*)*context);
      }
      ctx = (EVP_MD_CTX*)*context;
      DBGLOG(TEST, SOAP_MESSAGE(fdebug, "-- MD5 Init %p\n", ctx));
      EVP_DigestInit(ctx, EVP_md5());
      break;
    case MD5_UPDATE:
      ctx = (EVP_MD_CTX*)*context;
      DBGLOG(TEST, SOAP_MESSAGE(fdebug, "-- MD5 Update %p --\n", ctx));
      DBGMSG(TEST, buf, len);
      DBGLOG(TEST, SOAP_MESSAGE(fdebug, "\n--"));
      EVP_DigestUpdate(ctx, (const void*)buf, (unsigned int)len);
      break;
    case MD5_FINAL:
      ctx = (EVP_MD_CTX*)*context;
      DBGLOG(TEST, SOAP_MESSAGE(fdebug, "-- MD5 Final %p --\n", ctx));
      EVP_DigestFinal(ctx, (unsigned char*)hash, &size);
      memcpy(buf, hash, 16);
      break;
    case MD5_DELETE:
      ctx = (EVP_MD_CTX*)*context;
      DBGLOG(TEST, SOAP_MESSAGE(fdebug, "-- MD5 Delete %p --\n", ctx));
      if (ctx)
      { EVP_MD_CTX_cleanup(ctx);
        SOAP_FREE(soap, ctx);
      }
      *context = NULL;
  }
  return SOAP_OK;
}

```

//Kunal Rudra.

**Comment by mattcaswell** [comment]
This code shouldn't even compile:

````
      if (!*context)
      { *context = (void*)SOAP_MALLOC(soap, sizeof(EVP_MD_CTX));
        EVP_MD_CTX_init((EVP_MD_CTX*)*context);
      }
````
`EVP_MD_CTX` was made opaque in OpenSSL 1.1.0. This means you are not allowed to access the structure directly and the definition of the structure is not in any of the public header files. Therefore the compile cannot know the value of `sizeof(EVP_MD_CTX)`. You are supposed to use `EVP_MD_CTX_new()` instead (and `EVP_MD_CTX_init()` is no longer necessary).

`EVP_MD_CTX_cleanup(ctx);`: This function doesn't even exist in OpenSSL 1.1.1 (you are supposed to use `EVP_MD_CTX_free()` to free up and `EVP_MD_CTX` when you are finished with it).

If the above code is successfully compiling for you in 1.1.1, then one of two things have occurred:

1) You have included OpenSSL *internal* header files in your application. This is a bad thing and will very likely lead to problems. Don't do that. Only use the public header files.

or

2) You are somehow using 1.0.2 header files but linking against the 1.1.1 library. This is doomed to failure. Make sure your header files match your library.

**Comment by rudrakunal** [comment]
Hello mattcaswell,

Thank you for your quick  response.

Yes we are using OpenSSL internal headers and we are referring **crypto** folder.
Will remove these references.

Below piece of code in used by another 3rd party library gSOAP, we will contact them and suggest them to use OpenSSL in right way.

```
if (!*context)
      { *context = (void*)SOAP_MALLOC(soap, sizeof(EVP_MD_CTX));
        EVP_MD_CTX_init((EVP_MD_CTX*)*context);
      }
```
Thanks again.

//Kunal Rudra

**Comment by richsalz** [comment]
```EVP_MD_CTX``` is a pointer to a struct, so the sizeof will be four or eight.

**Comment by richsalz** [comment]
Ignore my previous comment :(
