### ISSUE TITLE
internal_namemap.t fails

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#10401]
From https://travis-ci.org/openssl/openssl/jobs/609686570?utm_medium=notification&utm_source=github_status
```
03-test_internal_namemap.t ......... 1/1 
1..1
    # RAND SEED 1573316976
    # Subtest: /home/travis/build/openssl/openssl/test/namemap_internal_test
    1..4
    ok 1 - test_digestbyname
    ok 2 - test_cipherbyname
    ok 3 - test_namemap_independent
    # ERROR: (int) 'false1 == 0' failed @ test/namemap_internal_test.c:39
    # [1] compared to [0]
    not ok 4 - test_namemap_stored
/home/travis/build/openssl/openssl/util/shlib_wrap.sh /home/travis/build/openssl/openssl/test/namemap_internal_test => 1
not ok 1 - running namemap_internal_test
#   Failed test 'running namemap_internal_test'
#   at /home/travis/build/openssl/openssl/test/../util/perl/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.
03-test_internal_namemap.t ......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

**Comment by levitte** [comment]
Okie, will look. I wonder why that didn't happen in a PR...

**Comment by t8m** [comment]
This seems to fixed itself somehow with the 2555285fa5e4248ad4a5a0bc14ae4606443856c2 commit. This test was failing before that and is passing now. But given the commit is practically unrelated, it is weird.

**Comment by t8m** [comment]
For some reason the individual subtests can run in different order with ubsan?? The failure happens when the test_digestbyname runs before test_namemap_stored because the "foo" name will be there already.

**Comment by levitte** [comment]
Ah!  Fix coming up!

**Comment by levitte** [comment]
#10601
