### ISSUE TITLE
OPENSSL_clear_free instead of OPENSSL_free

### ISSUE THREAD

**Issue by ManSoSec** [openssl/openssl#10406]
It seems `OPENSSL_clear_free` needs to be called instead of `OPENSSL_free` here:
https://github.com/openssl/openssl/blob/1903a9b77af1aa289ce858de90790f3e2749fea9/crypto/sm2/sm2_sign.c#L475

As it has done here:
https://github.com/openssl/openssl/blob/1903a9b77af1aa289ce858de90790f3e2749fea9/crypto/ec/ecdsa_ossl.c#L347

**Comment by romen** [comment]
In the verify path nothing is secret, so actually we should use free instead of clear_free also in the ecdsa part!

**Comment by mattcaswell** [comment]
Yes - agreed. `OPENSSL_free` is sufficient. Still a bug - but in ecdsa_ossl.c no sm2_sign.c
