### ISSUE TITLE
PRNG requirement - file descriptors

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#1041]
Comment from @richsalz in RT ticket 1298:
"It's probably not an issue because the number of file descriptors has increased on the native O/S's. But "file descriptor exhaustion" is still an issue for RNG's (google it) and we should keep it in mind for the future. What's the best way to do that?"

This ticket is a placeholder for the above issue to be kept in mind during the design of the new PRNG (post 1.1.0).

**Comment by kaduk** [comment]
Just to note the obvious options: one can ensure that a fd to /dev/urandom is opened early and never closed, and one can have sources of entropy that do not rely on file descriptors (rdrand, getentropy).

**Comment by richsalz** [comment]
Read the whole ticket, : http://rt.openssl.org/Ticket/Display.html?id=1298 for more info.

**Comment by richsalz** [comment]
I am going to claim that this is addressed by using non-fd seeding mechanisms in the new RAND functionality.
