### ISSUE TITLE
AES-GCM performance regression against 1.1.1d release

### ISSUE THREAD

**Issue by ilya-albrekht** [openssl/openssl#10415]
Master branch introduced AES-GCM performance regression against 1.1.1d release.
```
$ ./openssl speed -evp aes-128-gcm
OpenSSL 1.1.1d  10 Sep 2019
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm     690985.95k  1638819.75k  3692466.18k  5292674.14k  6350113.45k  6408912.90k
$ ./openssl speed -evp aes-128-gcm
version: 3.0.0-dev
built on: built on: Mon Nov  4 18:40:20 2019 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x7ffaf3bfffebffff:0x40405f5ef2bf27ef
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm     287625.14k   997425.24k  2703344.98k  4564637.88k  5626322.94k  5711025.49k
```

`master` branch code falls back to non-stitched CTR+GHASH codepath instead of using stitched AES-GCM codepath.
Looking at commits history I found out that following two commits are responsible for introduced regression:
`dec95d75897125133380c7ce3c6ce58c93c06f10 - "Rework how our providers are built"`
Breaks gcm as providers were moved and goes to scalar code.
`600703f4f4d4bbe7016a8704a0f2195e370648c0 - Cleanup: move provider mains up`
Only partially fixes regression. Still doesn't use stitched GCM code.

**Comment by t8m** [comment]
It is fixed now:
LD_LIBRARY_PATH=. apps/openssl speed -evp aes-128-gcm
Doing aes-128-gcm for 3s on 16 size blocks: 79427251 aes-128-gcm's in 2.96s
Doing aes-128-gcm for 3s on 64 size blocks: 46304132 aes-128-gcm's in 2.97s
Doing aes-128-gcm for 3s on 256 size blocks: 24621958 aes-128-gcm's in 2.99s
Doing aes-128-gcm for 3s on 1024 size blocks: 9361415 aes-128-gcm's in 2.99s
Doing aes-128-gcm for 3s on 8192 size blocks: 1589281 aes-128-gcm's in 2.97s
Doing aes-128-gcm for 3s on 16384 size blocks: 716237 aes-128-gcm's in 2.97s
version: 3.0.0-alpha8
built on: built on: Thu Nov  5 00:00:00 2020 UTC
options:bn(64,64) md2(char) rc4(16x,int) des(int) aes(partial) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
CPUINFO: OPENSSL_ia32cap=0x7ffaf3ffffebffff:0x29c67af
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm     429336.49k   997799.48k  2108100.75k  3206049.82k  4383632.98k  3951120.20k

openssl speed -evp aes-128-gcm
Doing aes-128-gcm for 3s on 16 size blocks: 79027325 aes-128-gcm's in 2.96s
Doing aes-128-gcm for 3s on 64 size blocks: 46776681 aes-128-gcm's in 2.99s
Doing aes-128-gcm for 3s on 256 size blocks: 25446766 aes-128-gcm's in 2.99s
Doing aes-128-gcm for 3s on 1024 size blocks: 7852557 aes-128-gcm's in 2.98s
Doing aes-128-gcm for 3s on 8192 size blocks: 1291971 aes-128-gcm's in 2.98s
Doing aes-128-gcm for 3s on 16384 size blocks: 665593 aes-128-gcm's in 2.99s
OpenSSL 1.1.1g FIPS  21 Apr 2020
built on: Thu Apr 23 00:00:00 2020 UTC
options:bn(64,64) md2(char) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm     427174.73k  1001239.99k  2178719.76k  2698328.31k  3551619.61k  3647182.51k
