### ISSUE TITLE
Null pointer causing segfault in RAND_bytes

### ISSUE THREAD

**Issue by jhealyt** [openssl/openssl#10422]
I've found a small bug that causes a segfault in RAND_bytes if there is a failure in initiating the random number generator.

Firstly, here's the entire contents of "RAND_bytes":

    int RAND_bytes(unsigned char *buf, int num)
    {
        const RAND_METHOD *meth = RAND_get_rand_method();

        if (meth->bytes != NULL)
            return meth->bytes(buf, num);
        RANDerr(RAND_F_RAND_BYTES, RAND_R_FUNC_NOT_IMPLEMENTED);
        return -1;
    }

That first line where the function "RAND_get_rand_method" is called, might return a null pointer. The next line checks for a null pointer, but it really should be:

    if ( NULL != meth && NULL != meth->bytes )

On my own system, this has been causing a segfault when my custom engine's random number generator fails to load.

**Comment by paulidale** [comment]
This bug is in 1.1.1, not master.

**Comment by InfoHunter** [comment]
This is fixed by f9fdb9d2f5a0358a3fd34b060fe23cb0eceb2e2c, closing.
