### ISSUE TITLE
What default parameters uses -pbkdf2?

### ISSUE THREAD

**Issue by valecor95** [openssl/openssl#10427]
Hi guys, I encrypted a file with this command:

`openssl enc -aes-192-cbc -e -pbkdf2 -in <infile> -out <outfile> -pass pass: <password> `

Now I'm trying to do decrypt it in c and to take advantage of pbkdf2 I'm using the function:

```
int PKCS5_PBKDF2_HMAC (const char * pass, int passlen,
                        const unsigned char * salt, int saltlen, int iter,
                        const EVP_MD * digest,
                        int keylen, unsigned char * out);
```

But the problem is: I know the parameters pass, passlen, keyless and *out...

How do I know what are the parameters for the salt, iter and digest that correspond to the command written above?

**Comment by mattcaswell** [comment]
This was answered via you stackoverflow question (which I saw before this one!).

https://stackoverflow.com/questions/58823814/what-default-parameters-uses-openssl-pbkdf2

Closing.
