### ISSUE TITLE
How implement decryption commamd that uses pbkdf2 in c language?  

### ISSUE THREAD

**Issue by valecor95** [openssl/openssl#10437]
Hy guys, another problem about openssl:

I have this command: 

    `openssl enc -aes-192-cbc -pbkdf2 -e -in <infile> -out <outfile> -pass pass:password` 

Now i have only the ciphertext of this command and i know the password and then i know also the salt that is the first 8 bytes of the ciphertext after the string "Salted__". I know also that openssl as default parameter take 1000 iteration count and sha256 as a digest. My problem is: how i can go back to the derived key and derived iv from c language?

My code is this but it not return the right values:

```
void decrypt(unsigned char *ciphertext, int ciphertext_len, unsigned char *plaintext, const char *password, unsigned char* salt){
    EVP_CIPHER_CTX *ctx;

    int len;

    int plaintext_len;
    
    //unsigned char* key = "EF04020D6979FC09CC1859A2BFB832FFFCF57C64BA61F682"; right value
    //unsigned char* iv = "722EDDC813763C9AAB96A0A6885CE1DB"; right value
    unsigned char key[24], iv[16];
    
    int i;	
		
    PKCS5_PBKDF2_HMAC(password, strlen(password), (unsigned char*)salt, strlen(salt), 1000, EVP_sha256(), 16, key);

    EVP_BytesToKey(EVP_aes_192_cbc(), EVP_sha256(), (unsigned char*)salt, (unsigned char*)password, strlen(password), 1000, key+16, iv);
	
    printf("Key: "); for(i=0; i < 24; ++i){ printf("%02x", key[i]); } printf("\n");
    printf("IV: "); for(i=0; i < 16; ++i){ printf("%02x", iv[i]); } printf("\n\n");
	
    //Create and initialise the context 
    if(!(ctx = EVP_CIPHER_CTX_new()))
        handleErrors();

 
    //Initialise the decryption operation. IMPORTANT - ensure you use a key
    //and IV size appropriate for your cipher
    
	if(1 != EVP_DecryptInit_ex(ctx, EVP_aes_192_cbc(), NULL, key, iv))
		handleErrors();
    
    //Provide the message to be decrypted, and obtain the plaintext output.
    //EVP_DecryptUpdate can be called multiple times if necessary.
    
    if(1 != EVP_DecryptUpdate(ctx, plaintext, &len, ciphertext, ciphertext_len))
        handleErrors();
    plaintext_len = len;

    //Finalise the decryption. Further plaintext bytes may be written at
    //this stage.
    
    if(1 != EVP_DecryptFinal_ex(ctx, plaintext + len, &len))
        handleErrors();
    plaintext_len += len;

    //Clean up 
    EVP_CIPHER_CTX_free(ctx);
    
}
```

The right values are commented and i take it from the terminal.... but my c code don't return that values.
I think this depends by the fact that i don't translate well the -pbkdf2 derivation key...Help me please i use openssl 1.1.1

**Comment by mattcaswell** [comment]
Why are you calling both `PKCS5_PBKDF2_HMAC` *and* `EVP_BytesToKey`? They are alternatives for doing the same thing (with the latter being the old legacy way of doing it). If you supply the `-pbkdf2` argument then `enc` does not call `EVP_BytesToKey`.

**Comment by mattcaswell** [comment]
````
    PKCS5_PBKDF2_HMAC(password, strlen(password), (unsigned char*)salt, strlen(salt), 1000, EVP_sha256(), 16, key);
````
The 16 on this line makes no sense. You are trying to get a key suitable for `EVP_aes_192_cbc()` which uses a 24 byte key (192/8). If you are looking to replicate the "enc" command then that actually asks for 40 bytes of data in one go - with the first 24 before the key, and the next 16 being the IV.

**Comment by valecor95** [comment]
Thank you very much i understand and i also see the native code in apps/enc.c and what you said is the real behaviour of the command. Thanks
