### ISSUE TITLE
Anonymous Cipher not working with OpenSSL1.1.1-D

### ISSUE THREAD

**Issue by ravinjhajharia** [openssl/openssl#10445]
I am verifying the anonymous cipher support with OpenSSL-1.1.1-D with tls 1.3 disabled but its failing with SSL routines:ssl_cipher_list_to_bytes:no ciphers available:ssl\statem\statem_clnt.c:3798:**No ciphers enabled for max supported SSL/TLS version**.

Kindly find the S_Server and S_Client results as below

**OpenSSL S_Server**

s_server -no_tls1_3 -cipher ADH-AES128-SHA:ADH-AES128-SHA256:ADH-AES256-SHA256 -state -accept localhost:14000 -nocert -msg

> Using default temp DH parameters
> ACCEPT
> SSL_accept:before SSL initialization
> TLS 1.0, Alert [length 0002], fatal unexpected_message
> SSL3 alert write:fatal:unexpected_message
> SSL_accept:error in error
> ERROR
> 41244:error:140940F4:SSL routines:ssl3_read_bytes:unexpected message:ssl\record\rec_layer_s3.c:1477: shutting down SSL
> CONNECTION CLOSED
> 

**OpenSSL S_Client**

s_client -no_tls1_3 -cipher ADH-AES128-SHA256:ADH-AES256-SHA256 -state -connect localhost:14000 -msg

```
CONNECTED(00000168)
SSL_connect:before SSL initialization
TLS 1.2, Alert [length 0002], fatal internal_error
SSL3 alert write:fatal:internal error
SSL_connect:error in error 35516:error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available:ssl\statem\statem_clnt.c:3798:No ciphers enabled for max supported SSL/TLS version
no peer certificate available
No client certificate CA names sent
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol : TLSv1.2
Cipher : 0000
Session-ID:
Session-ID-ctx:
Master-Key:
PSK identity: None
PSK identity hint: None
SRP username: None
Start Time: 1573710105
Timeout : 7200 (sec)
Verify return code: 0 (ok)
Extended master secret: no

It seems to be some version mismatch with given sets of ciphers. I browse the OpenSSL-1.1.1-D code and found that the some sanity check was introduced during the construction of Client hello for cipher suite validation as mentioned below:
`        /* Sanity check that the maximum version we offer has ciphers enabled */
        if (!maxverok) {
            if (SSL_IS_DTLS(s)) {
                if (DTLS_VERSION_GE(c->max_dtls, s->s3->tmp.max_ver)
                        && DTLS_VERSION_LE(c->min_dtls, s->s3->tmp.max_ver))
                    maxverok = 1;
            } else {
                if (c->max_tls >= s->s3->tmp.max_ver
                        && c->min_tls <= s->s3->tmp.max_ver)
                    maxverok = 1;
            }
        }
`
I tried various other option like ADH, aNULL, aNULL:@SECLEVEL=0 etc but still the issue was same.
Kindly help me if i am missing out something

**Comment by mattcaswell** [comment]
Please try adding `:@SECLEVEL=0` onto the end of your cipher strings, e.g.

`-cipher "ADH-AES128-SHA:ADH-AES128-SHA256:ADH-AES256-SHA256:@SECLEVEL-0"`

The anon ciphersuites are disabled in the default security level in OpenSSL 1.1.0+

**Comment by ravinjhajharia** [comment]
Thanks. Its working fine

**Comment by mattcaswell** [comment]
Great! Closing.
