### ISSUE TITLE
DH_compute_key_padded is undocumented in 1.0.2, 1.1.1 and master

### ISSUE THREAD

**Issue by vdukhovni** [openssl/openssl#10440]
DH_compute_key_padded is not documented in any OpenSSL release, present since at least 1.0.2.

**Comment by jacobrogers256** [comment]
Close this issue, it is now documented. https://github.com/openssl/openssl/blob/3dbf82438004b31258627f324841476c4f586c19/doc/man3/DH_generate_key.pod
In addition, The function you mention is actually deprecated, so it does not make sense to complain that it is not documented.
