### ISSUE TITLE
PEM_read_bio_PrivateKey regression

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#10444]
I used to be able to call:
PEM_read_bio_PrivateKey(privateBio, NULL, NULL, const_cast<void*>(reinterpret_cast<const void*>(passwordUtf8))

with a NULL as the callback and the password in the last argument. However, this causes an access violation now because in ui_read the callback is called even when it is NULL:

static int ui_read(UI *ui, UI_STRING *uis)
...
            int len = **data->cb**(result,
                               maxsize > PEM_BUFSIZE ? PEM_BUFSIZE : maxsize,
                               data->rwflag, UI_get0_user_data(ui));

stack trace:
>	libcrypto-3.dll!ui_read(ui_st * ui, ui_string_st * uis) Line 111	C
 	libcrypto-3.dll!UI_process(ui_st * ui) Line 517	C
 	libcrypto-3.dll!file_get_pass(const ui_method_st * ui_method, char * pass, unsigned __int64 maxsize, const char * prompt_info, void * data) Line 71	C
 	libcrypto-3.dll!file_get_pem_pass(char * buf, int num, int w, void * data) Line 113	C
 	libcrypto-3.dll!PEM_do_header(evp_cipher_info_st * cipher, unsigned char * data, long * plen, int(*)(char *, int, int, void *) callback, void * u) Line 432	C
 	libcrypto-3.dll!file_read_pem(bio_st * bp, char * * pem_name, char * * pem_header, unsigned char * * data, long * len, const ui_method_st * ui_method, void * ui_data, int secure) Line 1126	C
 	libcrypto-3.dll!file_load(ossl_store_loader_ctx_st * ctx, const ui_method_st * ui_method, void * ui_data) Line 1317	C
 	libcrypto-3.dll!OSSL_STORE_load(ossl_store_ctx_st * ctx) Line 182	C
 	libcrypto-3.dll!PEM_read_bio_PrivateKey(bio_st * bp, evp_pkey_st * * x, int(*)(char *, int, int, void *) cb, void * u) Line 49	C

The following commit probably caused the change:
https://github.com/openssl/openssl/pull/2746

**Comment by matbech** [comment]
A workaround is to write a callback like this:

```
int password_callback(char* buf, int bufsize, int verify, void* userdata)
{
	const auto passwordLength{ std::strlen(static_cast<const char*>(userdata)) };
	if (passwordLength >= bufsize)
	{
		// buffer too small
		return 0;
	}
	std::memcpy(buf, userdata, passwordLength + 1);
	return static_cast<int>(passwordLength);
}
```

And then call
```
PEM_read_bio_PrivateKey(privateBio, NULL, password_callback, const_cast<void*>(reinterpret_cast<const void*>(passwordUtf8))
```

**Comment by mattcaswell** [comment]
@levitte

**Comment by levitte** [comment]
Please try #10447

**Comment by matbech** [comment]
I can confirm this fixes it. Thank you.
