### ISSUE TITLE
Why does the x509 command not copy extension in certificate request?

### ISSUE THREAD

**Issue by theoryfate** [openssl/openssl#10458]
Of course, I am not the first person to encounter this problem. After my search, I found that many people have raised this question.

https://github.com/openssl/openssl/issues/6481

https://github.com/Netflix/lemur/pull/1909

https://github.com/openssl/openssl/pull/9449

https://github.com/openssl/openssl/issues/3638

https://github.com/openssl/openssl/pull/9497

https://github.com/openssl/openssl/issues/6481

https://stackoverflow.com/questions/33989190/subject-alternative-name-is-not-copied-to-signed-certificate

https://stackoverflow.com/questions/6194236/openssl-version-v3-with-subject-alternative-name

https://stackoverflow.com/questions/30977264/subject-alternative-name-not-present-in-certificate

https://security.stackexchange.com/questions/150078/missing-x509-extensions-with-an-openssl-generated-certificate

https://security.stackexchange.com/questions/158166/how-to-add-altname-from-csr-file-to-crt-file-using-openssl-x509-req

https://security.stackexchange.com/questions/74345/provide-subjectaltname-to-openssl-directly-on-the-command-line

https://www.linuxquestions.org/questions/linux-software-2/get-subjectaltname-into-certificate-my-own-ca-4175479553/

https://forum.ivorde.com/openssl-certificate-authority-ca-how-to-copy-x509-extensions-from-csr-to-signed-pem-t19421.html

https://stackoverflow.com/questions/25900812/certificate-is-not-including-san-names-using-openssl

http://openssl.6102.n7.nabble.com/subjectAltName-removed-from-CSR-when-signing-td26928.html

https://mta.openssl.org/pipermail/openssl-users/2016-January/002759.html

The problem encountered by so many people is only because of a small bug here.

https://www.openssl.org/docs/man1.1.1/man1/x509.html

**BUGS
Extensions in certificates are not transferred to certificate requests and vice versa.**

Why is this problem not fixed yet? Please give me a reason.

Obviously only need to add a -copy_extensions option to solve this problem perfectly

**Comment by richsalz** [comment]
It is not really a bug, it is a security concern.  The job of a CA is to look at the request and verify all extensions before putting them into the cert.  Blindly copying extensions without some explicit direction to do so would be an issue -- for example, if the config didn't specify SAN values, but the cert request had them then the cert could be bogus.

Perhaps one way around this is to add a couple of flags to the ca command
- Copy all other extensions
- Fail-exit if there are unknown extensions
- Other?

**Comment by richsalz** [comment]
And BTW, that's *great* job of finding the complaints.

**Comment by levitte** [comment]
It's probably better to use the `openssl ca` command...

**Comment by theoryfate** [comment]
@richsalz 
You are right, of course, we should not copy extensions unconditionally.

Just as there is a copy_extensions option in openssl.cnf, we should also add the copy_extensions option to the x509 command.

This is very valuable, which avoids the need for a meaningless secondary extension addition in the x509 command and avoids the need to create a separate configuration file for -extfile.

**Comment by theoryfate** [comment]
@levitte 
Yes, you can configure the copy_extensions of openssl.cnf and then use "openssl ca" to achieve this effect.

In fact, you can also add extensions to "openssl x509" by using the -extfile option. But I think "openssl x509" should also be able to copy the extension of the certificate request, the reason can be seen above my reply.

"openssl x509" is a more lightweight certificate operation tool. I think it is different from "openssl ca". Sometimes we only need a lightweight tool and don't want to configure openssl.cnf.

**Comment by spaetow** [comment]
> @levitte
> Yes, you can configure the copy_extensions of openssl.cnf and then use "openssl ca" to achieve this effect.
> 
> In fact, you can also add extensions to "openssl x509" by using the -extfile option. But I think "openssl x509" should also be able to copy the extension of the certificate request, the reason can be seen above my reply.
> 
> "openssl x509" is a more lightweight certificate operation tool. I think it is different from "openssl ca". Sometimes we only need a lightweight tool and don't want to configure openssl.cnf.

This has just hit me as well. I have a number of SAN entries in my existing cert that need to go across, and even using `-extfile` with the `-x509toreq` command doesn't work after I pulled those out. It's very disappointing.

**Comment by DDvO** [comment]
PR #13711 meanwhile contains, among many other improvements of the `x509` app, a fix for this bug.

**Comment by kousu** [comment]
@DDv0 thank you! That's amazing.

I was just bemoaning

> BUGS
>       Extensions in certificates are not transferred to certificate requests and vice versa.

in x509(1), a mea culpa that I bet has been there for years and years, and then I find that you just fixed this, last month.

:bouquet:

**Comment by afrancoc2000** [comment]
Hi, I can see that this issue has been closed, but I can't find the -copy_extensions option for [v1.1.1](https://www.openssl.org/docs/man1.1.1/man1/x509.html) or [v3.0](https://www.openssl.org/docs/man3.0/man1/openssl-x509.html) and trying to run `openssl x509 -req -in ica.csr -days 365 -CA ca-root.crt -CAkey ca-root.key -CAcreateserial -out ica.crt -copy_extensions` doesn't work, am I missing something? how can I use the -copy_extensions option?

**Comment by afrancoc2000** [comment]
Sorry found it on v3.0 Thanks
