### ISSUE TITLE
EVP_CIPHER_CTX_FLAG_WRAP_ALLOW flag support

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#10455]
I'm implementing the new Russian GOST CMS specification. It uses the key wrap algorithm described here: https://tools.ietf.org/html/draft-smyshlyaev-tls12-gost-suites-06#section-8.2

I've implemented the algorithm as a cipher with the `EVP_CIPH_WRAP_MODE` flag.

The `EVP_CipherInit_ex` function does not reset the `EVP_CIPHER_CTX` object and the `EVP_CIPHER_CTX_FLAG_WRAP_ALLOW` stays untouched, so the behavior seems a bit controversial (and undocumented, at least for the 1.1.1 branch). The `EVP_CipherInit_ex` function also especially preserves the `EVP_CIPHER_CTX_FLAG_WRAP_ALLOW` flag. The 
`EVP_CipherInit` function cleans up the passed context. 

I see the following variants:

1. Document the difference in behavior.
2. Update the `EVP_CipherInit` function to preserve the `EVP_CIPHER_CTX_FLAG_WRAP_ALLOW` flag on context reset.

I'm ready to implement any of these variants.

**Comment by mattcaswell** [comment]
A significant difference between `EVP_CipherInit` and `EVP_CipherInit_ex` is that the former does a "memset" on the EVP_CIPHER_CTX first (thus resetting any flags). I'm fairly sure that it is by design that `EVP_CipherInit_ex` doesn't reset any flags.

I suspect documentation is probably the way forward.

**Comment by levitte** [comment]
The problem with the older `EVP_CipherInit()` is that it doesn't allow incremental initialization, i.e. something like:

``` C
    EVP_CipherInit_ex(ctx, cipher, NULL, NULL, NULL, 1);
    ....
    EVP_CipherInit_ex(ctx, NULL, NULL, key, NULL, 1);
    ....
    EVP_CipherInit_ex(ctx, NULL, NULL, NULL, iv, 1);
```

This way of initializing incrementally is something we use a little here and there.
