### ISSUE TITLE
Mistaken in EVP_sm4_ecb!

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [openssl/openssl#10462]
1.Correct data
plain_data:	0123456789ABCDEFFEDCBA9876543210
key:		0123456789ABCDEFFEDCBA9876543210
cipher_data:681EDF34D206965E86B3E94F536E4246

2.Get data(681edf34d206965e86b3e94f536e4246) when I call EVP_EncryptUpdate;
Get data(681edf34d206965e86b3e94f536e4246002a8a4efa863ccad024ac0300bb40d2) when I call EVP_EncryptFinal_ex.

3.demo:

``` C
int SM4_ecb_check() 
{

    static const unsigned char key[SM4_BLOCK_SIZE] = {
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
        0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10
    };

    static const unsigned char intext[SM4_BLOCK_SIZE] = {
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
        0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10
    };

    /*
     * This test vector comes from Example 1 of GB/T 32907-2016,
     * and described in Internet Draft draft-ribose-cfrg-sm4-02.
     */
    static const unsigned char expected[SM4_BLOCK_SIZE] = {
        0x68, 0x1e, 0xdf, 0x34, 0xd2, 0x06, 0x96, 0x5e,
        0x86, 0xb3, 0xe9, 0x4f, 0x53, 0x6e, 0x42, 0x46
    };

    /*
     * This test vector comes from Example 2 from GB/T 32907-2016,
     * and described in Internet Draft draft-ribose-cfrg-sm4-02.
     * After 1,000,000 iterations.
     */

	static const unsigned char iv[SM4_BLOCK_SIZE] = {
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
        0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10
    };

	int intextlen = sizeof(intext);

	unsigned char outbuf[4096] = {};
	memset(outbuf, 0, sizeof(outbuf));

	int outlen = 0, tmplen = 0;

	int i = 0;
	/*
	* Bogus key and IV: we'd normally set these from
	* another source.
	*/
	EVP_CIPHER_CTX *ctx;
	ctx = EVP_CIPHER_CTX_new();
	EVP_EncryptInit_ex(ctx, EVP_sm4_ecb(), NULL, key, iv);

	if (!EVP_EncryptUpdate(ctx, outbuf, &outlen, intext, intextlen)) {
	  /* Error */
	  EVP_CIPHER_CTX_free(ctx);
	  return 0;
	}

	print_data("out update", outbuf, outlen); 
	//outbuf:681edf34d206965e86b3e94f536e4246

	if (!EVP_EncryptFinal_ex(ctx, outbuf + outlen, &tmplen)) {
		EVP_CIPHER_CTX_free(ctx);
		return 0;
	}
	outlen += tmplen;
	print_data("out final", outbuf, outlen); 
	//outbuf:681edf34d206965e86b3e94f536e4246002a8a4efa863ccad024ac0300bb40d2

	printf("\n");
	return 0;
}
```

**Comment by levitte** [comment]
From the `EVP_EncryptFinal_ex` manual:

> If padding is enabled (the default) then **EVP_EncryptFinal_ex()** encrypts
       the "final" data, that is any data that remains in a partial block.  It
       uses standard block padding (aka PKCS padding) as described in the
       NOTES section, below. The encrypted final data is written to **out** which
       should have sufficient space for one cipher block. The number of bytes
       written is placed in **outl**. After this function is called the encryption
       operation is finished and no further calls to **EVP_EncryptUpdate()**
       should be made.
> ...
> **NOTES**
> ...
> *Padding is always added so if the data is already a multiple of the
       block size **n** will equal the block size.*

So, this is not a bug.
