### ISSUE TITLE
make install fails with openssl 1.1.1d on windows with VS 2019. error C2061: syntax error: identifier CAPI_str_functs for out of tree builds

### ISSUE THREAD

**Issue by matra774** [openssl/openssl#10460]
I am trying to build OpenSSL  version `OpenSSL_1_1_1d` on Windows 10. Using Microsoft Visual Studio 2019. I am using out of source build.

Steps to reproduce:
1. Open  x64 Native COmmand Prompt for VS2019
2. `mkdir openssl.build`
3. `git clone git://git.openssl.org/openssl.git`
4. `cd openssl`
5. `git checkout OpenSSL_1_1_1d`
6. `cd ../openssl.build `
7. `SET PATH=%PATH%;C:\Program Files\NASM`
8. `perl ..\openssl\configure VC-WIN64A --prefix=D:\src\openssl.build --openssldir=D:\src\openssl.build`
9. `nmake`
10. Build successfully completes with 

    ```
        cl  /Zi /Fdapp.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "include" /I "..\openssl\include" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  /Zs /showIncludes "..\openssl\test\x509aux.c" 2>&1 > test\x509aux.d
        IF EXIST test\x509aux.exe.manifest DEL /F /Q test\x509aux.exe.manifest
        link /nologo /debug /subsystem:console /opt:ref  /nologo /debug /out:test\x509aux.exe @C:\Users\matejt\AppData\Local\Temp\nmBED1.tmp
        IF EXIST test\x509aux.exe.manifest  mt -nologo -manifest test\x509aux.exe.manifest -outputresource:test\x509aux.exe
        "D:\Perl64\bin\perl.exe" "-I." -Mconfigdata "..\openssl\util\dofile.pl"  "-omakefile" "..\openssl\apps\CA.pl.in" > "apps\CA.pl"
        "D:\Perl64\bin\perl.exe" "-I." -Mconfigdata "..\openssl\util\dofile.pl"  "-omakefile" "..\openssl\apps\tsget.in" > "apps\tsget.pl"
        "D:\Perl64\bin\perl.exe" "-I." -Mconfigdata "..\openssl\util\dofile.pl"  "-omakefile" "..\openssl\tools\c_rehash.in" > "tools\c_rehash.pl"
   ```
11. `nmake install` runs for a while and then crashes with:

    ```
Copying: ./include/openssl/x509err.h to D:/src/openssl.build/include/openssl/x509err.h
Copying: ./include/openssl/x509v3.h to D:/src/openssl.build/include/openssl/x509v3.h
Copying: ./include/openssl/x509v3err.h to D:/src/openssl.build/include/openssl/x509v3err.h
created directory `D:/src/openssl.build/lib'
Copying: libcrypto.lib to D:/src/openssl.build/lib/libcrypto.lib
Copying: libssl.lib to D:/src/openssl.build/lib/libssl.lib
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe" /                   _build_engines

Microsoft (R) Program Maintenance Utility Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl  /Zi /Fddso.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "include" /I "..\openssl\include" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  -c /Foengines\e_capi.obj "..\openssl\engines\e_capi.c"
e_capi.c
D:\src\openssl\engines\e_capi_err.c(16): error C2061: syntax error: identifier 'CAPI_str_functs'
D:\src\openssl\engines\e_capi_err.c(16): error C2059: syntax error: ';'
D:\src\openssl\engines\e_capi_err.c(16): error C2059: syntax error: '['
D:\src\openssl\engines\e_capi_err.c(40): error C2061: syntax error: identifier 'CAPI_str_reasons'
D:\src\openssl\engines\e_capi_err.c(40): error C2059: syntax error: ';'
D:\src\openssl\engines\e_capi_err.c(40): error C2059: syntax error: '['
D:\src\openssl\engines\e_capi_err.c(91): warning C4013: 'ERR_get_next_error_library' undefined; assuming extern returning int
D:\src\openssl\engines\e_capi_err.c(95): warning C4013: 'ERR_load_strings' undefined; assuming extern returning int
D:\src\openssl\engines\e_capi_err.c(95): error C2065: 'CAPI_str_functs': undeclared identifier
D:\src\openssl\engines\e_capi_err.c(96): error C2065: 'CAPI_str_reasons': undeclared identifier
D:\src\openssl\engines\e_capi_err.c(107): warning C4013: 'ERR_unload_strings' undefined; assuming extern returning int
D:\src\openssl\engines\e_capi_err.c(107): error C2065: 'CAPI_str_functs': undeclared identifier
D:\src\openssl\engines\e_capi_err.c(108): error C2065: 'CAPI_str_reasons': undeclared identifier
D:\src\openssl\engines\e_capi_err.c(118): warning C4013: 'ERR_PUT_error' undefined; assuming extern returning int
..\openssl\engines\e_capi.c(113): error C2143: syntax error: missing ')' before '*'
..\openssl\engines\e_capi.c(113): error C2081: 'BIO': name in formal parameter list illegal
..\openssl\engines\e_capi.c(113): error C2143: syntax error: missing '{' before '*'
..\openssl\engines\e_capi.c(113): error C2059: syntax error: ')'
..\openssl\engines\e_capi.c(114): error C2143: syntax error: missing ')' before '*'
..\openssl\engines\e_capi.c(114): error C2081: 'BIO': name in formal parameter list illegal

    ```

11. Repeating `nmake install` procudes another error:

    ```
Microsoft (R) Program Maintenance Utility Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe" /                   _build_libs

Microsoft (R) Program Maintenance Utility Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "." /I "include" /I "..\openssl" /I "..\openssl\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_MONT5" -D"OPENSSL_BN_ASM_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"KECCAK1600_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"VPAES_ASM" -D"GHASH_ASM" -D"ECP_NISTZ256_ASM" -D"X25519_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"D:\\src\\openssl.build\"" -D"ENGINESDIR=\"D:\\src\\openssl.build\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  -c /Foapps\app_rand.obj "..\openssl\apps\app_rand.c"
app_rand.c
D:\src\openssl\e_os.h(241): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

    ```

Configuration:
D:\src\openssl.build>perl configdata.pm --dump

Command line (with current working directory = .):

    D:\Perl64\bin\perl.exe ..\openssl\Configure VC-WIN64A --prefix=D:\src\openssl.build --openssldir=D:\src\openssl.build

Perl information:

    D:\Perl64\bin\perl.exe
    5.24.3 for MSWin32-x64-multi-thread

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c\+\+
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [not-linux]
    asan                    [default]   OPENSSL_NO_ASAN
    crypto-mdebug           [default]   OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]   OPENSSL_NO_EGD
    external-tests          [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]   OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]   OPENSSL_NO_HEARTBEATS
    md2                     [default]   OPENSSL_NO_MD2 (skip crypto\md2)
    msan                    [default]   OPENSSL_NO_MSAN
    rc5                     [default]   OPENSSL_NO_RC5 (skip crypto\rc5)
    sctp                    [default]   OPENSSL_NO_SCTP
    ssl-trace               [default]   OPENSSL_NO_SSL_TRACE
    ubsan                   [default]   OPENSSL_NO_UBSAN
    unit-test               [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]
    zlib-dynamic            [default]
    ssl3                    [default]   OPENSSL_NO_SSL3
    ssl3-method             [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "lib",
    ARFLAGS => "/nologo",
    AS => "nasm",
    ASFLAGS => "-g",
    CC => "cl",
    CFLAGS => "/W3 /wd4090 /nologo /O2",
    CPP => "\$(CC) /EP /C",
    HASHBANGPERL => "/usr/bin/env perl",
    LD => "link",
    LDFLAGS => "/nologo /debug",
    MT => "mt",
    MTFLAGS => "-nologo",
    RANLIB => "CODE(0xd51958)",
    RC => "rc",
    aes_asm_src => "aes_core.c aes_cbc.c vpaes-x86_64.s aesni-x86_64.s aesni-sha1-x86_64.s aesni-sha256-x86_64.s aesni-mb-x86_64.s",
    aes_obj => "aes_core.o aes_cbc.o vpaes-x86_64.o aesni-x86_64.o aesni-sha1-x86_64.o aesni-sha256-x86_64.o aesni-mb-x86_64.o",
    apps_aux_src => "win32_init.c",
    apps_init_src => "../ms/applink.c",
    apps_obj => "win32_init.o",
    aroutflag => "/out:",
    asflags => "-Ox -f win64 -DNEAR",
    asoutflag => "-o ",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bin_cflags => "/Zi /Fdapp.pdb",
    bin_lflags => "/subsystem:console /opt:ref",
    bn_asm_src => "bn_asm.c x86_64-mont.s x86_64-mont5.s x86_64-gf2m.s rsaz_exp.c rsaz-x86_64.s rsaz-avx2.s",
    bn_obj => "bn_asm.o x86_64-mont.o x86_64-mont5.o x86_64-gf2m.o rsaz_exp.o rsaz-x86_64.o rsaz-avx2.o",
    bn_ops => "EXPORT_VAR_AS_FN SIXTY_FOUR_BIT",
    build_file => "makefile",
    build_scheme => [ "unified", "windows", "VC-common" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "/Gs0 /GF /Gy /MD",
    chacha_asm_src => "chacha-x86_64.s",
    chacha_obj => "chacha-x86_64.o",
    cmll_asm_src => "cmll-x86_64.s cmll_misc.c",
    cmll_obj => "cmll-x86_64.o cmll_misc.o",
    coutflag => "/Fo",
    cppflags => "",
    cpuid_asm_src => "x86_64cpuid.s",
    cpuid_obj => "x86_64cpuid.o",
    defines => [ "OPENSSL_SYS_WIN32", "WIN32_LEAN_AND_MEAN", "UNICODE", "_UNICODE", "_CRT_SECURE_NO_DEPRECATE", "_WINSOCK_DEPRECATED_NO_WARNINGS", "OPENSSL_USE_APPLINK" ],
    des_asm_src => "des_enc.c fcrypt_b.c",
    des_obj => "des_enc.o fcrypt_b.o",
    disable => [  ],
    dso_cflags => "/Zi /Fddso.pdb",
    dso_extension => ".dll",
    dso_scheme => "win32",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-x86_64.s x25519-x86_64.s",
    ec_obj => "ecp_nistz256.o ecp_nistz256-x86_64.o x25519-x86_64.o",
    enable => [  ],
    ex_libs => "ws2_32.lib gdi32.lib advapi32.lib crypt32.lib user32.lib",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600-x86_64.s",
    keccak1600_obj => "keccak1600-x86_64.o",
    ldoutflag => "/out:",
    lflags => "",
    lib_cflags => "/Zi /Fdossl_static.pdb",
    lib_cppflags => "",
    lib_defines => [ "L_ENDIAN" ],
    md5_asm_src => "md5-x86_64.s",
    md5_obj => "md5-x86_64.o",
    modes_asm_src => "ghash-x86_64.s aesni-gcm-x86_64.s",
    modes_obj => "ghash-x86_64.o aesni-gcm-x86_64.o",
    module_cflags => "",
    module_cxxflags => "",
    module_ldflags => "/dll",
    mtinflag => "-manifest ",
    mtoutflag => "-outputresource:",
    multilib => "-x64",
    padlock_asm_src => "e_padlock-x86_64.s",
    padlock_obj => "e_padlock-x86_64.o",
    perlasm_scheme => "auto",
    poly1305_asm_src => "poly1305-x86_64.s",
    poly1305_obj => "poly1305-x86_64.o",
    rc4_asm_src => "rc4-x86_64.s rc4-md5-x86_64.s",
    rc4_obj => "rc4-x86_64.o rc4-md5-x86_64.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rcoutflag => "/fo",
    rmd160_asm_src => "",
    rmd160_obj => "",
    sha1_asm_src => "sha1-x86_64.s sha256-x86_64.s sha512-x86_64.s sha1-mb-x86_64.s sha256-mb-x86_64.s",
    sha1_obj => "sha1-x86_64.o sha256-x86_64.o sha512-x86_64.o sha1-mb-x86_64.o sha256-mb-x86_64.o",
    shared_cflag => "",
    shared_defines => [  ],
    shared_extension => ".dll",
    shared_extension_simple => ".dll",
    shared_ldflag => "/dll",
    shared_rcflag => "",
    shared_target => "win-shared",
    sys_id => "WIN64A",
    thread_defines => [  ],
    thread_scheme => "winthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "../ms/uplink.c uplink-x86_64.s",
    uplink_obj => "../ms/uplink.o uplink-x86_64.o",
    wp_asm_src => "wp-x86_64.s",
    wp_obj => "wp-x86_64.o",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = lib
    ARFLAGS         = /nologo
    AS              = nasm
    ASFLAGS         = -g
    CC              = cl
    CFLAGS          = /W3 /wd4090 /nologo /O2
    CPP             = $(CC) /EP /C
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LD              = link
    LDFLAGS         = /nologo /debug
    LDLIBS          =
    MT              = mt
    MTFLAGS         = -nologo
    PERL            = D:\Perl64\bin\perl.exe
    RC              = rc
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    makefile

build file:

    makefile

build file templates:

    ..\openssl\Configurations\common0.tmpl
    ..\openssl\Configurations\windows-makefile.tmpl
    ..\openssl\Configurations\common.tmpl

**Comment by mattcaswell** [comment]
Hmm. That is strange. It looks like during the install phase it has attempted to start compiling things again - which it should not be doing.

I notice this is an out of tree build. I wonder what happens if you build in tree (i.e I you run Configure and nmake from the root of the source tree).

Ping @levitte.

**Comment by matra774** [comment]
>I wonder what happens if you build in tree (i.e I you run Configure and nmake from the root of the source tree).

Thanks @mattcaswell. If I build in tree, the `nmake install` works fine. I've updated the title of the issue.

**Comment by benh57** [comment]
I'm seeing the same thing and i'm running within the source tree and on VS 2017. I do have 2019 also installed on the same PC, but this is calling 2017.

 `Copying: libssl.lib to C:/usr/bin/openssl/openssl-1.1.1d/lib/libssl.lib   

`        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe" /                   _build_engines`

**Comment by benh57** [comment]
- Same results for me when using my 2019 install, inside the openssl tree.

**Comment by benh57** [comment]
Possible clue: whenever this failure happens, all the headers in include/openssl get set to Zero KB. Which naturally breaks all future configures/compiles.

**Comment by matra774** [comment]
I can confirm the following:
- I have also noticed that some times all header files have size of zero
- when building without engines the problem does not occur.

**Comment by levitte** [comment]
The headers becoming empty gave me a bit of a hint...

The --prefix that you set, `D:\src\openssl.build`, that wouldn't happen to be your build directory too, by any chance? So essentially, you're trying to install into your build directory....

The simple answer is, don't do that.

**Comment by matra774** [comment]
You are correct. There are actually 3 directories:  build, openssldir, prefix. All point to the same location:
>cd ../openssl.build
>perl ..\openssl\configure VC-WIN64A --prefix=D:\src\openssl.build --openssldir=D:\src\openssl.build

Looks like I was mislead with the comment from https://wiki.openssl.org/index.php/Compilation_and_Installation#PREFIX_and_OPENSSLDIR, which state, that **two** of them should point to the same location.

I'll retry with differnt dirs and then close this if everything is OK.

**Comment by levitte** [comment]
Prefix and openssldir should point to directories where you want to have openssl files installed, which is different from where it's built.

**Comment by benh57** [comment]
I was also following a guide (elsewhere) which suggested setting them to the same value.

Perhaps configure should error if they are the same, since it no longer works?

**Comment by levitte** [comment]
Prefix and openssldir can be the same, but making them *the same as the build dir* is error prone.
Yeah, maybe Configure should check that.

**Comment by matra774** [comment]
>I'll retry with differnt dirs and then close this if everything is OK.
Using different dirs worked OK.

Thanks for your prompt response. I'm closing the issue.

I agree with @levitte that it would be good if Configure could detect this.
