### ISSUE TITLE
question for how to use encryption algorithms 

### ISSUE THREAD

**Issue by haoxuegong** [openssl/openssl#10477]
dsa
rsa
rand
rehash
spkac
srp
blake2b512
blake2s256
gost
md4
md5
mdc2
rmd160
sha1
sha224
sha256
sha3-224
sha3-256
sha3-384
sha3-512
sha384
sha512
sha512-224
sha512-256
shake128
shake256
sm3
aes-128-cbc
aes-128-ecb
aes-192-cbc
aes-192-ecb
aes-256-cbc
aes-256-ecb
aria-128-cbc
aria-128-cfb
aria-128-cfb1
aria-128-cfb8
aria-128-ctr
aria-128-ecb
aria-128-ofb
aria-192-cbc
aria-192-cfb
aria-192-cfb1
aria-192-cfb8
aria-192-ctr
aria-192-ecb
aria-192-ofb
aria-256-cbc
aria-256-cfb
aria-256-cfb1
aria-256-cfb8
aria-256-ctr
aria-256-ecb
aria-256-ofb
base64
bf
bf-cbc
bf-cfb
bf-ecb
bf-ofb
camellia-128-cbc
camellia-128-ecb
camellia-192-cbc
camellia-192-ecb
camellia-256-cbc
camellia-256-ecb
cast
cast-cbc
cast5-cbc
cast5-cfb
cast5-ecb
cast5-ofb
des
des-cbc
des-cfb
des-ecb
des-ede
des-ede-cbc
des-ede-cfb
des-ede-ofb
des-ede3
des-ede3-cbc
des-ede3-cfb
des-ede3-ofb
des-ofb
des3
desx
idea
idea-cbc
idea-cfb
idea-ecb
idea-ofb
rc2
rc2-40-cbc
rc2-64-cbc
rc2-cbc
rc2-cfb
rc2-ecb
rc2-ofb
rc4
rc4-40
seed
seed-cbc
seed-cfb
seed-ecb
seed-ofb
sm4-cbc
sm4-cfb
sm4-ctr
sm4-ecb
sm4-ofb
What is the current status of these encryption algorithms, which ones are recommended, and which ones are forbidden, and what is the life cycle?

**Comment by haoxuegong** [comment]
Is there a relevant document?

**Comment by levitte** [comment]
All of them are *available*, at least in the source.  Which ones are actually available in the libraries depends on how OpenSSL has been configured.

Which ones are *recommended* doesn't depend on us, but on recommendations made elsewhere (for example, NIST makes recommendations primarily targeted at US government, and I assume there is a corresponding Chinese department making recommendations related to the SM algorithms, at least for use in China).
*Some* algorithms have been commonly deemed legacy, so it's safe to say that *no one* recommends them.

We do have a current document, [provider(7)](https://www.openssl.org/docs/manmaster/man7/provider.html), which lists currently available algorithms in different providers.  Does that help?

**Comment by haoxuegong** [comment]
Thank you for your answer, I will check the documentation.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
