### ISSUE TITLE
util/perlpath.pl calls deprecated File::Find module

### ISSUE THREAD

**Issue by chris-short** [openssl/openssl#1047]
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.CQ8rmV
- umask 022
- cd /home/vagrant/rpmbuild/BUILD
- cd openssl-1.0.2h
- perl util/perlpath.pl /usr/bin/perl
  Can't locate find.pl in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at util/perlpath.pl line 7.

**Comment by mattcaswell** [comment]
perlpath.pl is a prehistoric remnant from SSLeay days. It's been edited once (in 1999) since it was imported from SSLeay. Why do you need it? It's been deleted from 1.1.0.
