### ISSUE TITLE
Regression in ChaCha20 on 64 bit ARM

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#10470]
The commit 86a7ac5e76fd3df9a5c3422153ae5a3e4f99b3a8 broke the 64 bit ARM implementation of ChaCha20.

Running the evp_test on evpciph_chacha.txt segfaults (due to memory corruption) on the first test data that is larger than 512 bytes (it has 640 plaintext bytes to encrypt).

**Comment by t8m** [comment]
@dot-asm might be interested.

**Comment by t8m** [comment]
Or @ardbiesheuvel could be interested in looking at this?

**Comment by ardbiesheuvel** [comment]
This looks like a bug in the test to me. The test crashes trying to diff all of memory, but if you look at the dump carefully, the first 0x280 (640) bytes are actually correct.

**Comment by ardbiesheuvel** [comment]
... and interestingly, the debug build completes without crashing or reporting any errors.

**Comment by dot-asm** [comment]
I can't even reproduce it. And I can assure that I test was passing when I was putting it together. And the new code is not actually invoked for 640 bytes length. I mean it was 3+1 to 4+1 replacement, but[!] keep 6+2. And for length of 640 bytes it calls 6+2 and then processes 640-512=128 bytes with ... scalar subroutine, without calling 4+1...

**Comment by levitte** [comment]
@t8m, would you be able to produce a backtrace for that case?

**Comment by dot-asm** [comment]
> I can't even reproduce it.

What's compiler?

What is possibility of this being result of misinterpretation of ABI specification by compiler developer? The spec says that v7-v15 are to be preserved by callee, but with additional note that it suffices to preserve only  64 least significant bits. Which means that it's d7-d15 that need to be preserved, not v7-v15...

**Comment by dot-asm** [comment]
> The test crashes trying to diff all of memory,

What does it mean? Does it crash in memcmp, or equivalent of, on first non-readable page? I mean if you start accessing valid memory and just go forward, you are bound to run into a non-accessible page and suffer segmentation violation. Is this it? If so, then key question is where does length parameter to memcmp, of equivalent of, come from.

**Comment by ardbiesheuvel** [comment]
> > The test crashes trying to diff all of memory,
> 
> What does it mean? Does it crash in memcmp, or equivalent of, on first non-readable page? I mean if you start accessing valid memory and just go forward, you are bound to run into a non-accessible page and suffer segmentation violation. Is this it? If so, then key question is where does length parameter to memcmp, of equivalent of, come from.

Yes, it keeps looping over increasing memory addresses until it segfaults. But at this point, it has already decided that something is wrong (or it would not print the diff in the first place), so there are at least two separate bugs here.

But as far as I can tell, the ChaCha20 code is fine, Also, I cannot reproduce this on a Cortex-A53 box running Debian Stretch (using GCC 6), but I can on A57+Buster and TX2+Buster (using GCC 8)

**Comment by dot-asm** [comment]
> but I can on A57+Buster and TX2+Buster (using GCC 8)

I find if hard to imagine that it would be specific to processor, focus should be in on compiler instead. What about test with env OPENSSL_armcap=0? Does it crash? If no, then it should be relatively easy to spot if it's v7-v15 thing by examining disassembler output...

**Comment by dot-asm** [comment]
> it has already decided that something is wrong (or it would not print the diff in the first place)

Oh! You mean that memcmp doesn't crash, and program crashes **later** trying to print infinite diff. So there are diverging opinions on how large allegedly equal-sized buffers are... Well, given dependency on compiler flags (debug build didn't crash), it looks rather like compiler bug...

**Comment by t8m** [comment]
> > I can't even reproduce it.
> 
> What's [failing] compiler?

It is gcc-8.3.1 from RHEL-8.

**Comment by t8m** [comment]
Run with OPENSSL_armcap=0 does not crash.

**Comment by t8m** [comment]
Would it be possible to provide a (hackish even) patch that preserves the v7-v15 to test whether this is the case?

**Comment by dot-asm** [comment]
I'd say [again] look at disassembler output first. Also try to compile with -mgeneral-regs-only. Try do gradually drop optimization level, from -O2, -O1. In essence dependency on compiler flags is sufficient to classify it as compiler problem. And it should be sufficient to make a case. It should be noted that "v7-v15" is not specific to chacha20-armv8 module, so it's not unlikely that having it worked around for chacha would just move the problem elsewhere.

**Comment by dot-asm** [comment]
Correction for all references to "v7-v15" [and "d7-d15"]. It should have been "**v8**-v15"!!! Sorry about possible misunderstanding.

**Comment by t8m** [comment]
With -O1 it crashes differently the backtrace is broken due to stack corruption:
(gdb) bt
#0  0x0000ffffbe550158 in ChaCha20_512_neon () from ./libcrypto.so.3
#1  0x0706050403020100 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by ardbiesheuvel** [comment]
The following diff fixes things for me:
```
diff --git a/crypto/chacha/asm/chacha-armv8.pl b/crypto/chacha/asm/chacha-armv8.pl
index aed873d57ef8..f90687c2d204 100755
--- a/crypto/chacha/asm/chacha-armv8.pl
+++ b/crypto/chacha/asm/chacha-armv8.pl
@@ -1232,7 +1232,6 @@ $code.=<<___;
        adds    $len,$len,#512
        ushr    $ONE,$ONE,#1                    // 4 -> 2
 
-       ldp     d8,d9,[sp,#128+0]               // meet ABI requirements
        ldp     d10,d11,[sp,#128+16]
        ldp     d12,d13,[sp,#128+32]
        ldp     d14,d15,[sp,#128+48]
@@ -1250,6 +1249,7 @@ $code.=<<___;
        ld1     {$CTR,$ROT24},[$key]
        b.hs    .Loop_outer_neon
 
+       ldp     d8,d9,[sp,#0]                   // meet ABI requirements
        eor     @K[1],@K[1],@K[1]
        eor     @K[2],@K[2],@K[2]
        eor     @K[3],@K[3],@K[3]
@@ -1259,6 +1259,7 @@ $code.=<<___;
        b       .Loop_outer
 
 .Ldone_512_neon:
+       ldp     d8,d9,[sp,#128+0]               // meet ABI requirements
        ldp     x19,x20,[x29,#16]
        add     sp,sp,#128+64
        ldp     x21,x22,[x29,#32]
```
The problem is that d8 and d9 are not restored properly depending on the code path taken through these functions, and the compiler is spilling to FP registers.

**Comment by t8m** [comment]
Great, this patch fixes it for me as well.

**Comment by t8m** [comment]
Would you submit a PR, please? If you do not have OpenSSL CLA signed, I think this would be within CLA:trivial limits.

**Comment by ardbiesheuvel** [comment]
Sure, unless Andy prefers to fix it himself?

**Comment by dot-asm** [comment]
I'd like to suggest following:
```
diff --git a/arm/chacha-armv8.pl b/arm/chacha-armv8.pl
index fe33743..8891926 100755
--- a/arm/chacha-armv8.pl
+++ b/arm/chacha-armv8.pl
@@ -339,7 +339,7 @@ ___
 
 {{{
 my @K = map("v$_.4s",(0..3));
-my ($xt0,$xt1,$xt2,$xt3, $CTR,$ROT24) = map("v$_.4s",(4..9));
+my ($CTR,$ROT24, $xt0,$xt1,$xt2,$xt3) = map("v$_.4s",(4..9));
 my @X = map("v$_.4s",(16,20,24,28, 17,21,25,29, 18,22,26,30, 19,23,27,31));
 my ($xa0,$xa1,$xa2,$xa3, $xb0,$xb1,$xb2,$xb3,
     $xc0,$xc1,$xc2,$xc3, $xd0,$xd1,$xd2,$xd3) = @X;
@@ -1244,8 +1244,8 @@ $code.=<<___;
 	eor	@K[1],@K[1],@K[1]
 	eor	@K[2],@K[2],@K[2]
 	eor	@K[3],@K[3],@K[3]
-	eor	@K[4],@K[4],@K[4]
-	eor	@K[5],@K[5],@K[5]
+	//eor	@K[4],@K[4],@K[4]		// $CTR
+	//eor	@K[5],@K[5],@K[5]		// $ROT24
 	eor	@K[6],@K[6],@K[6]
 	b	.Loop_outer
 

```

**Comment by ardbiesheuvel** [comment]
Yes, I guess using caller save registers for CTR and ROT24 should do the trick as well. But why do those eor instructions need to be commented out? We are entering the scalar routine right after, which shouldn't care at all about the values of v4 and v5, no?

**Comment by davidben** [comment]
Over in BoringSSL, we have an ABI tester which checks that all our assembly functions properly save and restore caller-saved registers. Looks like you all have diagnosed the issue now, but if I import the current version of that file, I can confirm that `d8` and `d9` aren't being restored.

```
Note: Google Test filter = *ChaCha*ABI*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ChaChaTest
[ RUN      ] ChaChaTest.ABI
../crypto/chacha/chacha_test.cc:257: Failure
Failed
ABI failures in ChaCha20_ctr32(buf.get(), kInput, len + 15, key, kCounterNonce):
    d8 was not restored after return
    d9 was not restored after return

Google Test trace:
../crypto/chacha/chacha_test.cc:254: 512
[  FAILED  ] ChaChaTest.ABI (0 ms)
[----------] 1 test from ChaChaTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ChaChaTest.ABI
```

Assuming I've applied it correctly, it doesn't look like Andy's patch in https://github.com/openssl/openssl/issues/10470#issuecomment-557261619 fixes it:
```
[ RUN      ] ChaChaTest.ABI
../crypto/chacha/chacha_test.cc:255: Failure
Failed
ABI failures in ChaCha20_ctr32(buf.get(), kInput, len, key, kCounterNonce):
    d8 was not restored after return
    d9 was not restored after return

Google Test trace:
../crypto/chacha/chacha_test.cc:254: 256
../crypto/chacha/chacha_test.cc:257: Failure
Failed
ABI failures in ChaCha20_ctr32(buf.get(), kInput, len + 15, key, kCounterNonce):
    d8 was not restored after return
    d9 was not restored after return

Google Test trace:
../crypto/chacha/chacha_test.cc:254: 256
../crypto/chacha/chacha_test.cc:255: Failure
Failed
ABI failures in ChaCha20_ctr32(buf.get(), kInput, len, key, kCounterNonce):
    d8 was not restored after return
    d9 was not restored after return

Google Test trace:
../crypto/chacha/chacha_test.cc:254: 768
../crypto/chacha/chacha_test.cc:257: Failure
Failed
ABI failures in ChaCha20_ctr32(buf.get(), kInput, len + 15, key, kCounterNonce):
    d8 was not restored after return
    d9 was not restored after return

Google Test trace:
../crypto/chacha/chacha_test.cc:254: 768
[  FAILED  ] ChaChaTest.ABI (0 ms)
[----------] 1 test from ChaChaTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ChaChaTest.ABI
```

https://github.com/openssl/openssl/pull/10497 does resolve it.

**Comment by dot-asm** [comment]
> But why do those eor instructions need to be commented out?

Original rationale behind those eors is to wipe key and counter material. Note that `@K[0]` is not cleared. Why? Because it's known constant. And what are `@K[4,5]` at that point? Known constants as well.

Well, now, having said that, I realize that if one does this, right thing to do would be to wipe them even at .Ldone_512_neon... And .Ldone_neon... Yes, one can argue that more registers should be cleared... I'd argue that wiping key would be reasonable trade-off, even though deciphered clear text would be considered sensitive as well... So shall we clear key, more, or omit all eors at the end of ChaCha20_512_neon?

**Comment by dot-asm** [comment]
> it doesn't look like Andy's patch in #10470 (comment) fixes it:

Ah! Got it. .Ltail_neon...

**Comment by ardbiesheuvel** [comment]
> > But why do those eor instructions need to be commented out?
> 
> Original rationale behind those eors is to wipe key and ~counter~ nonce material. Note that `@K[0]` is not cleared. Why? Because it's known constant. And what are `@K[4,5]` at that point? Known constants as well.
> 
> Well, now, having said that, I realize that if one does this, right thing to do would be to wipe them even at .Ldone_512_neon... And .Ldone_neon... Yes, one can argue that more registers should be cleared... I'd argue that wiping key would be reasonable trade-off, even though deciphered clear text would be considered sensitive as well... So shall we clear key, more, or omit all eors at the end of ChaCha20_512_neon?

I think your current approach is fine, but it would be nice to capture this rationale in a code comment somewhere.

**Comment by t8m** [comment]
@dot-asm Would you please submit a PR with the changes?

**Comment by dot-asm** [comment]
Let's go with #10497, and I'll harmonize cleansing of key material and add commentary...

**Comment by dot-asm** [comment]
In the hindsight I kind of take an issue with how casual originating report was. Deprived on tangible details I was bound to resort to wild guesses and speculations. Which statistically expected outcome, failure to recognize problem.
