### ISSUE TITLE
ecdsatest.c is missing handling of negative ECDSA_size

### ISSUE THREAD

**Issue by john-chuah** [openssl/openssl#10485]
Improper use of negative value found by Coverity.
In test/ecdsatest.c:

static int test_builtin(int n)
{
...
    size_t sig_len; **// type should be an int**

 **negative_return_fn: Function ECDSA_size(eckey) returns a negative number. [show details]
   	19. var_assign: Assigning: unsigned variable sig_len = ECDSA_size.**
    sig_len = ECDSA_size(eckey);

**// Once the type is fixed above, add this test to handle negative or zero sig_len:
    if (!TEST_int_gt(sig_len, 0))
        goto err;**
...   	
**20. negative_returns: sig_len is passed to a parameter that cannot be negative. [show details]**
    if (!TEST_ptr(sig = OPENSSL_malloc(sig_len))

**Comment by coolshrid** [comment]
Can some one walk me through on how to check in the fix. I seem to have fixed the code, but when I create a pull request. I get an error that reads 'hold: cla required'. I have already submitted the CLA agreement the to 'legal@opensslfoundation.org'

Thanks

**Comment by mattcaswell** [comment]
>  I get an error that reads 'hold: cla required'. I have already submitted the CLA agreement the to 'legal@opensslfoundation.org'

Should be sorted now.

**Comment by t8m** [comment]
After commits on master (88b4c61) and 1.1.1 (f9f2e60) Coverity should not indicate this error anymore.

**Comment by t8m** [comment]
That does not mean a test for it as above from @coolshrid cannot be accepted.

**Comment by t8m** [comment]
@coolshrid feel free to submit a PR with the test.
