### ISSUE TITLE
Null-pointer-dereference bug at rand_lib.c

### ISSUE THREAD

**Issue by JZuming** [openssl/openssl#10480]
Hello, I have found an out-of-memory bug with my fuzzing tool **FIFUZZ**. The bug information is following.

**Describe the bug**
The **malloc()** in the call stack shown below may fail:

    #0 Call malloc() in CRYPTO_malloc(), at mem.c: 222
    #1 Call CRYPTO_malloc() in CRYPTO_zalloc(), at mem.c: 230
    #2 Call CRYPTO_zalloc() in CRYPTO_THREAD_lock_new(), at threads_pthread.c: 33
    #3 Call CRYPTO_THREAD_lock_new() in do_rand_init(), at rand_lib.c: 250
    #4 Call do_rand_init() in do_rand_init_ossl_(), at rand_lib.c: 242
    #5 Call do_rand_init_ossl_() in pthread_once()
    #6 Call pthread_once() in CRYPTO_THREAD_run_once(), at threads_pthread.c: 122
    #7 Call CRYPTO_THREAD_run_once() in RAND_get_rand_method(), at rand_lib.c: 777
    #8 Call RAND_get_rand_method() in rand_bytes_ex(), at rand_lib.c: 877
    #9 Call rand_bytes_ex() in RAND_bytes(), at rand_lib.c: 896
    #10 Call RAND_bytes() in enc_main(), at enc.c: 446
    #11 Call enc_main() in do_cmd(), at openssl.c:481
    #12 Call do_cmd() in main(), at openssl.c: 294

If the **malloc()** in this call stack fails, **RAND_get_rand_method()** in **rand_bytes_ex()** will return NULL at rand_lib.c: 877, so **meth** will become NULL. And then the program will check whether **meth** is equal to **RAND_OpenSSL()**. Since **FIPS_MODE** is not defined, so **RAND_OpenSSL()** returns **&rand_meth**, and it is not equal to **meth** (it is NULL). And then **meth->bytes** causes a **null-pointer-dereference** at rand_lib.c: 880.

The Stack Traceback when the bug occurs:

    (gdb) backtrace
    #0  0x00007ffff753023b in rand_bytes_ex (ctx=0x0, buf=0x7fd810 "\300\332\377\377\377\177", num=      8) at crypto/rand/rand_lib.c:880
    #1  0x00007ffff7530498 in RAND_bytes (buf=0x7fd810 "\300\332\377\377\377\177", num=8) at crypto/rand/rand_lib.c      :896
    #2  0x04579e0 in enc_main (argc=12, argv=         0x7fe2a0) at apps/enc.c:446
    #3  0x047cee2 in do_cmd (prog=0x7b7700, argc=12, argv=         0x7fe2a0) at apps/openssl.c:481
    #4  0x047bd1f in main (argc=12, argv=         0x7fe2a0) at apps/openssl.c:294

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Type openssl enc -e -des3 -a -salt -in /tmp/test.c -out test.cipher -k testtesttest -pbkdf2
1. Make the _malloc()_ shown at **Describe the bug** fail.
2. The program will crash.

**Expected behavior**
The program would not crash when _malloc()_ fails.

**Environment (please complete the following information):**
 - Version: 3.0.0-dev
 - OS: Ubuntu 18.04
 - Compiler: Clang-6.0
 - Application: openssl 3.0.0-dev

**Additional context**
This bug is found by my fuzzing tool and the bug is triggered at runtime.

**Comment by paulidale** [comment]
Thanks for the detailed bug report.

**Comment by JZuming** [comment]
> Thanks for the detailed bug report.

You are welcome.

**Comment by mspncp** [comment]
@JZuming please see #10483 for a fix.

**Comment by JZuming** [comment]
@mspncp It seems that this patch can fix the bug because my fuzzer doesn't report it after applying the patch.
