### ISSUE TITLE
ECDSA_size can return negative value on error

### ISSUE THREAD

**Issue by john-chuah** [openssl/openssl#10484]
https://www.openssl.org/docs/man1.1.1/man3/ECDSA_size.html states that "ECDSA_size() returns the maximum length signature or 0 on error", but in fact, it can also return a negative value because it calls: 
 ret = ASN1_object_size(1, i, V_ASN1_SEQUENCE);
which can return -1 under two error conditions.

**Comment by wbrawner** [comment]
I'd like to take this on, assuming no one else has already. Also if this is fixed, wouldn't it automatically resolve #10485 or should I add that additional test case as a sort of regression test?

**Comment by romen** [comment]
Thanks @wbrawner, please go ahead and take this! 

I believe the resolution of this and #10485 is that ECDSA_size should conform to the documentation, so the error cases currently returning a negative number should instead return 0 to conform also to EVP_PKEY_size which is a wrapper for this method and similar _size for other asymmetric keys.

I'll ping @levitte also, as this is relevant for #10778 and he might share his opinion on what needs fixing here: doc or behavior?

**Comment by wbrawner** [comment]
Hey @romen, apologies for dropping the ball on this one. I had a pretty busy winter/spring and kept putting this off.

I took a look at the code though, and it seems that this issue was already fixed by 88b4c61299c, back in December of last year. If I'm mistaken please let me know but otherwise I believe this issue can be closed.

**Comment by romen** [comment]
@wbrawner no worries!

I believe you are right, that commit had the side effect of fixing this in `master`, but  I am not sure that change can be back ported to 1.1.1.

We might summon @slontis to ask his opinion about it as he worked on that PR and its dependencies.

The alternative is to make sure that no negative value is returned on error, in which case a PR would be more than welcome @wbrawner!

**Comment by wbrawner** [comment]
Ah, apologies, I hadn't realized that this was for 1.1.1. I backported a small fix that should cover this issue

**Comment by t8m** [comment]
Fixed both on master (88b4c61) and 1.1.1 (f9f2e60).
