### ISSUE TITLE
Null-pointer-dereference bug in initthread.c

### ISSUE THREAD

**Issue by JZuming** [openssl/openssl#10491]
Hello, I have found a null-pointer-dereference bug with my fuzzing tool **FIFUZZ**. The bug information is following.

**Describe the bug**
The **pthread_rwlock_init()** in the call stack shown below may fail:

    #0 Call pthread_rwlock_init() at CRYPTO_THREAD_lock_new(), at threads_pthread.c: 38
    #1 Call CRYPTO_THREAD_lock_new() in create_global_tevent_register(), at initthread.c: 60
    #2 Call create_global_tevent_register() in create_global_tevent_register_ossl_(), at initthread.c:53
    #3 Call create_global_tevent_register_ossl_() in pthread_once()
    #4 Call pthread_once() in CRYPTO_THREAD_run_once(), at threads_pthread.c: 122
    #5 Call CRYPTO_THREAD_run_once() in get_global_tevent_register(), at initthread.c: 74
    #6 Call get_global_tevent_register() in init_thread_push_handlers(), at initthread.c: 154
    #7 Call init_thread_push_handlers() in init_get_thread_local(), at initthread.c: 105
    #8 Call init_get_thread_local() in ossl_init_thread_start(), at initthread.c: 347
    #9 Call ossl_init_thread_start() in err_get_state_int(), at err.c: 705
    #10 Call err_get_state_int() in ERR_clear_error(), at err.c: 374
    #11 Call ERR_clear_error() in engine_load_rdrand_int(), at eng_rdrand.c: 89
    #12 Call engine_load_rdrand_int() in ossl_init_engine_rdrand(), at init.c: 270
    #13 Call ossl_init_engine_rdrand() in ossl_init_engine_rdrand_ossl_(), at init.c: 267
    #14 Call ossl_init_engine_rdrand_ossl_() in pthread_once()
    #15 Call pthread_once() in CRYPTO_THREAD_run_once(), at threads_pthread.c: 122
    #16 Call CRYPTO_THREAD_run_once() in OPENSSL_init_crypto(), at init.c: 555
    #17 Call OPENSSL_init_crypto() in ENGINE_load_builtin_engines(), at eng_all.c: 15
    #18 Call ENGINE_load_builtin_engines() in openssl_config_int(), at conf_sap.c: 65
    #19 Call openssl_config_int() in ossl_init_config(), at init.c: 234
    #20 Call ossl_init_config() in ossl_init_config_ossl_(), at init.c: 232
    #21 Call ossl_init_config_ossl_() in pthread_once()
    #22 Call pthread_once() in CRYPTO_THREAD_run_once(), at threads_pthread.c: 122
    #23 Call CRYPTO_THREAD_run_once() in OPENSSL_init_crypto(), at init.c:538 
    #24 Call OPENSSL_init_crypto() in OPENSSL_init_ssl()
    #25 Call OPENSSL_init_ssl() in apps_startup(), at openssl.c: 57
    #26 Call apps_startup() in main(), at openssl.c: 270

The call stack may be so deep, but the most important part is **#0 - 6**. When the **pthread_rwlock_init()** in this call stack fails, the **create_global_tevent_register()** will return 0 at initthread.c: 66. As the result, in **init_thread_push_handlers()**, the **get_global_tevent_register()** will returns NULL at initthread.c: 154 since the create operation fails. After that, **init_thread_push_handlers()** returns 0 and triggers the error handling code of **init_get_thread_local()**.

However, when the program exits, it call **init_thread_deregister()**. In **init_thread_deregister()**, **gtr** is assigned by the return value of **get_global_tevent_register()** at initthread.c: 382. The **get_global_tevent_register()** will return NULL because the create operation previously mentioned fails. So **gtr** is NULL, and **gtr->lock** causes a **null-pointer-dereference** at initthread.c: 384.

The Stack Traceback when the bug occurs:

    (gdb) backtrace
    #0  0x00007ffff74795a1 in init_thread_deregister (index=0x7acd20, all=0) at crypto/initthread.c:384
    #1  0x00007ffff747a702 in ossl_init_thread_deregister (index=0x7acd20) at crypto/initthread.c:424
    #2  0x00007ffff7491030 in ossl_provider_free (prov=0x7acd20) at crypto/provider_core.c:301
    #3  0x00007ffff741bfb9 in EVP_CIPHER_free (cipher=0x880410) at crypto/evp/evp_enc.c:1528
    #4  0x00007ffff7424840 in evp_cipher_free (cipher=0x880410) at crypto/evp/evp_enc.c:1496
    #5  0x00007ffff75170ee in impl_free (impl=0x87e970) at crypto/property/property.c:99
    #6  0x00007ffff75c133f in OPENSSL_sk_pop_free (st=0x87fa50, func=0x7ffff7517080 <impl_free>) at crypto/stack/stack.c:367
    #7  0x00007ffff7518df8 in sk_IMPLEMENTATION_pop_free (sk=0x87fa50, freefunc=0x7ffff7517080 <impl_free>) at crypto/property/property.c:34
    #8  0x00007ffff7515e6c in alg_cleanup (idx=35586, a=0x8805a0) at crypto/property/property.c:112
    #9  0x00007ffff7495458 in trampoline (n=35586, l=0x8805a0, arg=0x7fd668) at crypto/sparse_array.c:134
    #10 0x00007ffff74950e9 in sa_doall (sa=0x7aa7c0, node=0x0, leaf=0x7ffff7495400 <trampoline>, arg=0x7fd668) at crypto/sparse_array.c:98
    #11 0x00007ffff74953ce in OPENSSL_SA_doall (sa=0x7aa7c0, leaf=0x7ffff7515df0 <alg_cleanup>) at crypto/sparse_array.c:144
    #12 0x00007ffff7515dc8 in ossl_sa_ALGORITHM_doall (sa=0x7aa7c0, leaf=0x7ffff7515df0 <alg_cleanup>) at crypto/property/property.c:65
    #13 0x00007ffff7515c40 in ossl_method_store_free (store=0x7a9cd0) at crypto/property/property.c:146
    #14 0x00007ffff7427bf0 in evp_method_store_free (vstore=0x7a9cd0) at crypto/evp/evp_fetch.c:27
    #15 0x00007ffff746fbbe in openssl_ctx_generic_free (parent_ign=0x0, ptr=0x7a9cd0, ad=0x7ffff7a6a398 <default_context_int+8>, index=4, argl_ign=0, argp=0x7ffff7a40980 <evp_method_store_method>) at crypto/context.c:183
    #16 0x00007ffff7475dc9 in CRYPTO_free_ex_data (class_index=16, obj=0x0, ad=0x7ffff7a6a398 <default_context_int+8>) at crypto/ex_data.c:378
    #17 0x00007ffff746e206 in context_deinit (ctx=0x7ffff7a6a390 <default_context_int>) at crypto/context.c:110
    #18 0x00007ffff746e085 in openssl_ctx_default_deinit () at crypto/context.c:124
    #19 0x00007ffff7476ed4 in OPENSSL_cleanup () at crypto/init.c:416
    #20 0x00007ffff68f1041 in __run_exit_handlers (status=1, listp=0x7ffff6c99718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
    #21 0x00007ffff68f113a in __GI_exit (status=<optimized out>) at exit.c:139
    #22 0x047c5ba in main (argc=12, argv=0x7fe2a0) at apps/openssl.c:379

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Type openssl enc -e -des3 -a -salt -in /tmp/test.c -out test.cipher -k testtesttest -pbkdf2
1. Make the _pthread_rwlock_init()_ shown at **Describe the bug** fail.
2. The program will crash.

**Expected behavior**
The program would not crash when _malloc()_ fails.

**Environment (please complete the following information):**
 - Version: 3.0.0-dev
 - OS: Ubuntu 18.04
 - Compiler: Clang-6.0
 - Application: openssl 3.0.0-dev

**Additional context**
This bug is found by my fuzzing tool and the bug is triggered at runtime.

**Comment by paulidale** [comment]
Master only.

Thanks for the report.
