### ISSUE TITLE
djgpp build broken

### ISSUE THREAD

**Issue by gvanem** [openssl/openssl#10513]
While generating `include/crypto/dso_conf.h`, I get this error (from Cygwin32 on Win-10):
```
perl -I. -I./util/perl -Mconfigdata util/dofile.pl include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
Can't locate object method "dsoext" via package "platform" (perhaps you forgot to load "platform"?) at include/crypto/dso_conf.h.in line 30.
```

I assume this is due to a missing `Configuration/platform/djgpp.pm` with this missing Perl object.
Probably easy for someone who understand this horrid Perl stuff.

**Comment by levitte** [comment]
This is curious...  For djgpp, no specific "perl_platform" is specified, and the default is `Unix`, which does define the method `dsoext`.  I'll have me a look at that...

**Comment by levitte** [comment]
However!  this could be due to the fact that we currently don't support DSOs on djgpp.

**Comment by gvanem** [comment]
DSO = *Dynamic Shared Object*? Right, no DLLs on djgpp.

Why so obfuscated. Why not just do:
```c
#ifndef DSO_EXTENSION
# define DSO_EXTENSION ""
#endif
```
somewhere?

**Comment by levitte** [comment]
The C preprocessor can't compare strings, so we have `DSO_NONE` to indicate no DSO support.

Either way, your issue is due to over-zealous control no when to load the `platform` module.  Would you mind trying out #10514?

**Comment by gvanem** [comment]
Man, that was quick! 

I did understand nothing of that change, but the `dso_conf.h` gets generated okay now.
Although it has a:
```c
# define DSO_EXTENSION ".so"
```
which seems strange. Covered by the `#define DSO_NONE`?

Anyway, my only problem with building now is a clash with these functions:
```c
static void _sock_timeout(int signum);  // in apps/ocsp.c
sock_timeout (sock_type *s, int seconds);  // in Watt-32's tcp.h
```
Can we patch `apps/ocsp.c` like this:
```diff
--- a/apps/ocsp.c 2019-11-25 12:15:37
+++ b/apps/ocsp.c 2019-11-24 17:49:25
@@ -115,7 +115,7 @@
 static int index_changed(CA_DB *);
 static void spawn_loop(void);
 static int print_syslog(const char *str, size_t len, void *levPtr);
-static void _sock_timeout(int signum);
+static void sock_timeout(int signum);
 # endif

 # ifndef OPENSSL_NO_SOCK
@@ -622,7 +622,7 @@
     if (multi && acbio != NULL)
         spawn_loop();
     if (acbio != NULL && req_timeout > 0)
-        signal(SIGALRM, _sock_timeout);
+        signal(SIGALRM, sock_timeout);
 #endif

     if (acbio != NULL)
@@ -1389,7 +1389,7 @@
 # endif

 # ifdef OCSP_DAEMON
-static void _sock_timeout(int signum)
+static void sock_timeout(int signum)
 {
     if (acfd != (int)INVALID_SOCKET)
         (void)shutdown(acfd, SHUT_RD);
```

**Comment by levitte** [comment]
> Man, that was quick!

Sometimes, I am...  :wink:

Regarding `sock_timeout`, we can sure modify the name...  but will do it differently, as a beginning `_` is reserved for standard libraries (yeah, I know, we're doing this in other places, *ahem*, to be refactored)

**Comment by levitte** [comment]
Please see #10515.  I hope that rename is good enough.

**Comment by gvanem** [comment]
I've not tried, but it looks okay. Thanks!
