### ISSUE TITLE
New ERR_load_xxx_strings() functions should not be public

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#10527]
The `util/mkerr.pl` script will automatically create new `ERR_load_xxx_stinrgs()` functions where needed and make them public. This results in PRs like #10394 adding these functions to "missingcrypto.txt" to avoid having to document them - which is the wrong thing to do. We shouldn't be adding new public functions unless we expect applications to actually call them.

Probably `util/mkerr.pl` needs to be updated so that it doesn't add these functions to public headers.

**Comment by levitte** [comment]
I'd be happy to do so.  I need ideas on how to best register the new ones, so `util/mkerr.pl` doesn't suddenly start to remove old ones.

**Comment by levitte** [comment]
Either way, they should all be deprecated

**Comment by mattcaswell** [comment]
> I'd be happy to do so. I need ideas on how to best register the new ones, so util/mkerr.pl doesn't suddenly start to remove old ones.

One possibility is to do it the same way that find-doc-nits knows when we introduce newly undocumented functions without complaining about old ones. We have a text file somewhere containing the list of ERR functions that should remain public.

> Either way, they should all be deprecated

Agreed.
