### ISSUE TITLE
What make e_os.h special?

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#10536]
All the other common include files sit in one of the "include" directories except e_os.h which sits in the top level directory. Why? Shouldn't it be moved?

**Comment by mspncp** [comment]
Note: I remember that [stumbled over e_os.h](https://github.com/openssl/openssl/pull/9333#discussion_r321617581) too when reorganizing the header files and wondering why it had to be in the top level directory. But I did not dare to move it at that time.

**Comment by levitte** [comment]
It should be split up per platform it offers support for, and we should have a separate source tree for platform-specific support routines.  So basically, what makes it "special" is that it's a hodge podge of, well, almost everything.

If you want to move it first, I propose `include/arch`, and we can split it up in there later?  While we're at it, we could move `os-def/haiku.h`...  `os-dep` was kind of an attempt to start this kind of thing, and went completely unnoticed when @mspncp did the grand header restructure.

**Comment by mattcaswell** [comment]
> If you want to move it first, I propose include/arch, and we can split it up in there later?

Works for me.

**Comment by nhorman** [comment]
seems to have been moved to include/internal, so this seems complete
