### ISSUE TITLE
CMS_RecipientInfo_ktri_get0_encryptedKey accessor needed

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#10535]
Working on GOST CMS implementation, I came across the lack of the `ktri.encryptedKey` field accessor. Is it a desired state or just a missing accessor? 

If the 2nd option, I'll provide a patch for both  1.1.1 and master branches to implement it...

**Comment by beldmit** [comment]
ping @slontis

**Comment by slontis** [comment]
Currently it is only used by cms_RecipientInfo_ktri_encrypt/decrypt - so there is no need for it to be exposed for these cases. (i.e - it just needs to save and load this value from asn1 - In order to wrap the real key). So it probably does not belong in 1.1.1.

**Comment by beldmit** [comment]
I had to use it in my callbacks to unwrap the sender's key. I'll check whether it can be moved somewhere else...

**Comment by beldmit** [comment]
@slontis, many thanks!
No need to create this function in 1.1.1 and hopefully in 3.0.
