### ISSUE TITLE
How does a client which support <= TLS1.2 can connect with server which supports tlsv1.3? OpenSSL-1.1.1-D

### ISSUE THREAD

**Issue by ravinjhajharia** [openssl/openssl#10534]

**Comment by ravinjhajharia** [comment]
Suppose the server is running with TLSv1.3 ciphers(TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256) set using SSL_CTX_set_ciphersuites. Now if a client which supports TLSv1.2, How will he able to connect to the server?

**Comment by mattcaswell** [comment]
`s_server -tls1_3 -state -ciphersuites TLS_AES_128_GCM_SHA256 -cipher ADH-AES128-SHA:ADH-AES56-SHA -accept 14000 -cert brokercrt.pem -key brokerkey.key -msg -bugs`

The "-tls1_3" flag here means: "Only ever talk TLSv1.3". So if your objective is to allow the server to negotiate either TLSv1.3 or TLSv1.2 then you should remove that flag. The TLSv1.2 ciphersuites you have specified (`ADH-AES128-SHA:ADH-AES56-SHA`) are both anonymous ciphersuites, i.e. no authentication will occur (the certificate/key you configured won't be used if TLSv1.2 is negotiated in that case). This is not allowed in the default security level setting. If you really meant for that to happen then you need to change your `-cipher` setting to this `-cipher ADH-AES128-SHA:ADH-AES56-SHA:@SECLEVEL=0`. 

`s_client -no_tls1_3 -state -cipher ADH-AES128-SHA -connect localhost:14000 -msg -bugs`

If you really mean to use anonymous ciphersuites here then you also need to add `:@SECLEVEL=0` here too. There should be no need for the "-bugs" flag. This enables workarounds for very old SSL/TLS bugs that should not be present in modern servers.

**Comment by ravinjhajharia** [comment]
> `s_server -tls1_3 -state -ciphersuites TLS_AES_128_GCM_SHA256 -cipher ADH-AES128-SHA:ADH-AES56-SHA -accept 14000 -cert brokercrt.pem -key brokerkey.key -msg -bugs`
> 
> The "-tls1_3" flag here means: "Only ever talk TLSv1.3". So if your objective is to allow the server to negotiate either TLSv1.3 or TLSv1.2 then you should remove that flag. The TLSv1.2 ciphersuites you have specified (`ADH-AES128-SHA:ADH-AES56-SHA`) are both anonymous ciphersuites, i.e. no authentication will occur (the certificate/key you configured won't be used if TLSv1.2 is negotiated in that case). This is not allowed in the default security level setting. If you really meant for that to happen then you need to change your `-cipher` setting to this `-cipher ADH-AES128-SHA:ADH-AES56-SHA:@SECLEVEL=0`.
> 
> `s_client -no_tls1_3 -state -cipher ADH-AES128-SHA -connect localhost:14000 -msg -bugs`
> 
> If you really mean to use anonymous ciphersuites here then you also need to add `:@SECLEVEL=0` here too. There should be no need for the "-bugs" flag. This enables workarounds for very old SSL/TLS bugs that should not be present in modern servers.

Have tried removing the -tls1_3 flags as mentioned in below comments but still i am receiving the error 

OpenSSL> s_server -state -cipher AES128-SHA256:AES256-SHA256@SECLEVEL=0 -nocert -accept 14000 -msg
Using default temp DH parameters
17444:error:02006740:system library:bind:reason(1856):crypto\bio\b_sock2.c:161:
17444:error:20093075:BIO routines:BIO_bind:unable to bind socket:crypto\bio\b_sock2.c:162:
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client renegotiates (SSL_connect())
   0 client connects that finished
   0 server accepts (SSL_accept())
   0 server renegotiates (SSL_accept())
   0 server accepts that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
   0 callback cache hits
   0 cache full overflows (128 allowed)

**Comment by ravinjhajharia** [comment]
This was the mistake from my side since the port was already being used hence the it was not able to bind. Its working fine after removing the version specific flag. You can close this issue.
