### ISSUE TITLE
How to design and structure complex error messages?

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#10537]
For simple technical reasons OpenSSL errors tend to appear bottom-up:
First rather low-level errors are shown (e.g., some check or algorithm failed, maybe with a low-level reason given) and then - as far as developers take care to provide them - also more high-level diagnostics are presented, which may explain more abstractly what went wrong and/or which consequences this has (e.g., a certificate is invalid and therefore some operation cannot proceed).

This can cause users to have a hard time trying to understand what went wrong and why, in particular when they are inexperienced, when crucial information is missing or there is a lot of detail (which may be essential) where the more general picture becomes clear only after reading the final entries in the error log.

A good example for a complex scenario where this problem is striking is the following:
The receiver of a CMP message typically needs to verify that the message is authentic by checking that the message is signed using an acceptable certificate.
The certificate usually is part of the list of "extra certs" at the end of the message but it could also be taken from a list or cache maintained by the receiver.
For each candidate cert various checks are performed: it should be generally valid (in particular, it must not be expired and cert path validation must succeed),
it must match the sender name and/or sender key ID fields of the message if provided, its subject must match the expected name if provided,
its extended key usage, if present, must allow for digital signatures, and of course its public key must be used successfully for verifying the message signature.
Moreover, the 3GPP TS 33.310 standard, which has been defined on top of CMP, defines some tricky specific rules and exceptions.

So there are in general many candidate certificates and for each of them there are many reasons why the verification of a CMP message may be unsuccessful.
When this happens, a simple error like "CMP message signature could not be verified" is not really helpful to users - much more  information is needed for explaining what went wrong and how to correct it, namely which certificates from which sources have been tried and why each of them was rejected.
The more such diagnostic information is needed the more difficult is it to keep the overview and to understand the real reason of what went wrong.

When extending @mpeylo's CMP implementation I spent quite some effort to include in error messages as much relevant information on a failed CMP message verification as needed and to present it in a top-down way, which IMHO makes the large amount of information much easier to digest.
To this end I tentatively set up a high-level error message to which status and diagnostic info is appended over the course of the certificate selection and message verification attempts. On successful outcome all this is discarded, else it is dumped to the error log along with any lower-level errors.

Recently we got feedback from a reviewer who considered this (partly) top-down approach confusing because it is unusual for OpenSSL error reporting.
Now the main question is: which is the most user-friendly way of presenting complex diagnostic data in error situations?
And in case a (non-standard) top-down presentation is more suitable, how to implement this most elegantly using the available mechanisms?
Does anyone have experience in providing complex error information and can share his views and potential solution hints?

**Comment by levitte** [comment]
I think that your attempt to circumvent the "normal" order is misdirected. In the end, it's not about the order in which the errors have been added to the error queue, but in what order the queue is displayed, i.e. how `ERR_print_errors` operates.

Do note that there is a `ERR_print_errors_cb` which can be used to do whatever with the error output lines, including collecting them in whatever order the application wants for display. See https://github.com/openssl/openssl/blob/master/doc/man3/ERR_print_errors.pod

**Comment by DDvO** [comment]
Thanks for your immediate response.

I was already considering reversing the order of printing the error queue entries, but this does not work in general, or at least not that easily. The upcoming CMP (message verification) component of the crypto lib is not the only module that uses the error queue. It internally uses other crpyto lib components, and for other modules and higher-level libs (like ssl) and applications it may be more appropriate to print their error queue entries in the order they were produced. Moreover, the CMP library component has little/no influence how applications built on top of the crypto lib present the error queue to users.

Still your comment points out an interesting approach: how about adding a feature to `crypto/err` that for a defined range of error queue entries their order is reversed? Or is there a way for lib modules to re-arrange itself the order of the error queue entries it just produced?

**Comment by levitte** [comment]
Very frankly, this sounds like your trying to over-engineer something very simple: deliver an error message at the moment of error.

That being said, could you point at the PR where you're doing this kind of thing? I'm curious

**Comment by DDvO** [comment]
Here is the current preview of the PR in question, where I directly point to the review comment mentioned above, which refers to a key element of the respective code: https://github.com/mpeylo/cmpossl/pull/199#discussion_r351340578

**Comment by levitte** [comment]
Yeah, I see. And I still think it's a bad idea, most of all because that makes for a mixed order error queue, which is *really* confusing.

Basically, there are two viable models, which can be said like this in prose:

1.  This happened, because
    This happened, because
    This happened
    ... 
2.  This happened, therefore
    This happened, therefore
    This happened, therefore
    ...

`ERR_print_errors` gives you model 2. You seem to wish for model one, but you end up with the mixture of the two, without the cues "because" and "therefore"

**Comment by DDvO** [comment]
I see your point and I agree that mixing the models _can_ be confusing.
Thanks also for your good comment at that code section in the PR preview.

I'm now re-phrasing part of what I tried to convey in my original post above as follows. 
Strictly following model 2 has at least two readability/usability drawbacks, as can be seen from the following example sequence of errors:
```
any unrelated error messages before
Low-level error X1
...
Low-level error Xn
Failed using cert X
Low-level error Y1
...
Low-level error Yn
Failed using cert Y
... etc ...
Failed verification of message M
any unrelated error messages after
```
1. The user will need to recognize within a potentially longer list or error entries the start and end of a series of errors that relate to the same complex issue, namely that/why the selection of a suitable certificate (and the subsequent message signature check using it) failed.
2. For any candidate certificate that potentially was acceptable to some extent only negative information is shown, and this is done again in the counter-intuitive bottom-up order.

I meanwhile got an idea how to solve these two issues using the existing mechanism:
1. At the beginning of the message verification function throw a tentative pseudo-error that contains info what is going to be attempted and marks the beginning of a potential series of actual errors.
2. For each candidate cert, throw a tentative pseudo-error that contains identification of this cert  and marks the beginning of the attempt to use the cert, followed by a potential series of actual errors for that cert.

After successful message verification all these error queue entries are discarded, and else (by default) the following order or error queue entries is shown:
```
any unrelated error messages before 
Start verification of message M
Start attempt using cert X
Low-level error X1
...
Low-level error Xn
Failed using cert X
Start attempt using cert Y
Low-level error Y1
...
Low-level error Yn
Failed using cert Y
... etc ...
Failed verification of message M
any unrelated error messages after
```

One could further visually enhance readability by additional indentation:
```
any unrelated error messages before 
Start verification of message M
    Start attempt using cert X
        Low-level error X1
        ...
        Low-level error Xn
    Failed using cert X
    Start attempt using cert Y
        Low-level error Y1
        ...
        Low-level error Yn
    Failed using cert Y
    ... etc ...
Failed verification of message M
any unrelated error messages after
```

One could also avoid extra (and partly redundant) pseudo-error entries while still significantly enhancing readability (in comparison to the typical plain list of errors) by using just indentation (and optionally additional context info for certain erorrs):
```
any unrelated error messages before 
        Low-level error X1
        ...
        Low-level error Xn
    Failed using cert X (for verifying M)
        Low-level error Y1
        ...
        Low-level error Yn
    Failed using cert Y (for verifying M)
    ... etc ...
Failed verification of message M
any unrelated error messages after
```

**Comment by levitte** [comment]
This can be viewed in different manners...  one is that the set of errors you suggest is too complicated, and that such situations may be better resolved by clearing the error queue and simply emitting something like "no suitable certificate found".

Another way to solve the need for more information might be via callbacks.  As an example, the X509_verify function set uses that method to provide more information on what's actually going on.  That is a more suitable way of not over complicating the error queue while still giving the application valuable information *at the application's option*.

**Comment by mattcaswell** [comment]
>  at the application's option.

Right. I think you are trying to solve an application level problem in the library itself - which is the wrong place.

**Comment by DDvO** [comment]
> This can be viewed in different manners... one is that the set of errors you suggest is too complicated, and that such situations may be better resolved by clearing the error queue and simply emitting something like "no suitable certificate found".

No, as I wrote: there are typically many non-trivial reasons why the CMP message verification including the selection of certificates can go wrong. So it is not helpful just to say  "no suitable certificate found".

It's like if your car computer displayed: "something is wrong with the engine or the gear".
The user does need a whole load of information for that potentially very complicated error situation.
Otherwise there are simply too many options he'd need to guess and/or try out.
 
> Another way to solve the need for more information might be via callbacks. As an example, the X509_verify function set uses that method to provide more information on what's actually going on. That is a more suitable way of not over complicating the error queue while still giving the application valuable information _at the application's option_.

Indeed using a callback is an option. I was already partly abusing the cert validation callback for that purpose, but due to a review comment by @mattcaswell I stopped that.
The CMP implementation does already define four callback functions, and I would be reluctant to add yet another one for the above purpose because this would put an extra burden to CMP application developers.

Yet actually one of the existing callbacks is for general CMP logging debug/error/warning/progress messages. Using it also for dumping debugging info on CMP message verification does sound very reasonable.

Thanks a lot for this hint, I'll give this a try :+1:

**Comment by DDvO** [comment]
I just had an internal discussion on this topic.

We are very glad about the option to use the already existing CMP logging mechanism for this purpose. This way we can keep the use of the error queue to a minimum here and still provide sufficient detail on demand (with configurable level of verbosity) to the application layer.

**Comment by DDvO** [comment]
I've just finished implementing the above suggestion.

Here is an example of the full log of a CMP client run including the search for a suitable server cert:
```
crypto/cmp/cmp_client.c:647:CMP info: contacting pki.certificate.fi:8700
crypto/cmp/cmp_client.c:173:CMP info: sending IR
crypto/cmp/cmp_client.c:197:CMP info: received IP
crypto/cmp/cmp_vfy.c:564:CMP info: trying to find an acceptable server cert that..
crypto/cmp/cmp_vfy.c:567:CMP info: matches msg sender name = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:379:CMP info:  considering cert from extraCerts or other untrusted source with..
crypto/cmp/cmp_vfy.c:381:CMP info:   subject = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:383:CMP info:   issuer  = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:412:CMP info:  cert is acceptable
crypto/cmp/cmp_vfy.c:379:CMP info:  considering cert from extraCerts or other untrusted source with..
crypto/cmp/cmp_vfy.c:381:CMP info:   subject = /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
crypto/cmp/cmp_vfy.c:383:CMP info:   issuer  = /C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
crypto/cmp/cmp_vfy.c:329:CMP info:  actual name in cert subject = /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
crypto/cmp/cmp_vfy.c:330:CMP info:  does not match sender field = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:379:CMP info:  considering cert from trusted store with..
crypto/cmp/cmp_vfy.c:381:CMP info:   subject = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:383:CMP info:   issuer  = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:389:CMP info:  cert has already been checked
crypto/cmp/cmp_vfy.c:480:CMP info: found 1 acceptable server certs
crypto/cmp/cmp_client.c:173:CMP info: sending CERTCONF
crypto/cmp/cmp_client.c:197:CMP info: received PKICONF
crypto/cmp/cmp_vfy.c:379:CMP info:  considering previously validated server cert with..
crypto/cmp/cmp_vfy.c:381:CMP info:   subject = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:383:CMP info:   issuer  = /C=FI/O=Insta Demo/CN=Insta Demo CA
crypto/cmp/cmp_vfy.c:412:CMP info:  cert is acceptable
apps/cmp.c:4242:CMP info: received from pki.certificate.fi PKIStatus: accepted 
apps/cmp.c:3494:CMP info: received 1 extra certificate(s), saving to file 'insta.extracerts.pem'
apps/cmp.c:3494:CMP info: received 1 enrolled certificate(s), saving to file 'creds/insta.cert.pem'
```
which IMHO reads pretty nice :)

The only drawback of the new solution is that since the CMP logging has been required to make use of the trace API it is by default statically disabled, so in order to be able to see the diagnostic output the OpenSSL configuration option `enable-trace` must have been used at compile time.

**Comment by levitte** [comment]
When I created the trace API, I wanted it to be enabled by default. No one else wanted that, so yeah, you need a specially built libcrypto.

But like I said, the other option is an application callback

**Comment by DDvO** [comment]
I had already attempted to enable the trace API in some PR but this was disallowed. The reason apparently being that it might leak sensitive data. Yet this issue could be solved by adding verbosity setting that can be changed on demand. 

In my view the trace API unfortunately is practically nearly useless due because of being disabled by default. So users would have to complie their own copy of OpenSSL, which is quite a hurdle.

**Comment by richsalz** [comment]
Every release doesn't have to address every problem that people bring up.  Changing the way errors work in openssl would need more than just discussion between, mostly, two people in a PR.

**Comment by DDvO** [comment]
As far as the CMP contribution is concerned, I've found and implemented an easy way of invoking its log callback even when the trace API is disabled. So there is no urgent need to statically enable the trace API for the specific use case I've brought up in this issue.

The question if and under which circumstances the trace API could be (re-)enabled can be discussed in some other thread, so I'm closing this one again.
