### ISSUE TITLE
Incorrect Key Size for Some EC Curves

### ISSUE THREAD

**Issue by git-blame** [openssl/openssl#10542]
This is on version 1.1.0l but may also affect newer versions. This public key for curve sect163r1 should be 163 bits.

```
openssl ec -in keys/alice2.pub -pubin -text
read EC key
Public-Key: (162 bit)
pub:
    04:02:e9:7f:a0:12:ab:f4:1e:4c:b0:f1:d6:18:5f:
    aa:d3:b8:f4:24:2f:96:03:18:f5:27:37:dc:21:74:
    7d:f2:7f:ab:f4:51:d6:53:92:c2:e6:90:cc
ASN1 OID: sect163r1
writing EC key
-----BEGIN PUBLIC KEY-----
MEAwEAYHKoZIzj0CAQYFK4EEAAIDLAAEAul/oBKr9B5MsPHWGF+q07j0JC+WAxj1
JzfcIXR98n+r9FHWU5LC5pDM
-----END PUBLIC KEY-----
```
A number of functions use `EC_GROUP_order_bits` (for example  `EVP_PKEY_bits`, `do_EC_KEY_print`) to calculate key/curve size.

The typical underlying function is `ec_group_simple_order_bits` which counts the number of bits in the BIGNUM group order.

However, as seen in curves like sect163r1, the order value can be 1-bit smaller than the actual curve size.

From SEC spec:
```
Finally the order n of G and the cofactor are:
n=03 FFFFFFFF FFFFFFFF FFFF48AA B689C29C A710279B
h=02
```
It may be better to use `EC_GROUP_get_degree`. From the openssl documentation:
> EC_GROUP_get_degree gets the degree of the field. For Fp fields this will be the number of bits in p. For F2^m fields this will be the value m.

Testing it with the same key:
```
(gdb) p EVP_PKEY_bits( key )
$22 = 162
(gdb) p EC_GROUP_order_bits( g )
$23 = 162
(gdb) p EC_GROUP_get_degree( g )
$24 = 163
```

**Comment by mattcaswell** [comment]
@romen?

**Comment by romen** [comment]
Thanks for reporting this @git-blame 

> This is on version 1.1.0l but may also affect newer versions. This public key for curve sect163r1 should be 163 bits.

This is not necessarily true: the 163 in the name refers to the underlying filed size not to the order of the curve.

As you notice there is a difference between the order of the field upon which the curve is built (the number of elements in the fields that can be used as curve coefficients or point coordinates, which in this case is over 163 bit), the cardinality of the curve (the number of points on the whole curve, this is bound to be close enough to the order of the underlying field, but could be slightly bigger or smaller) and the order of the prime order subgroup that we use for cryptography (this is the number of points in the subgroup of the curve that we can use for cryptographic applications, in this case the number of points is expressed over 162 bits).

The difference is that for some curves, the cardinality is not a prime number, which means that different prime subgroups are included in the group of all possible points on the curve, one subgroup for every prime factor of the cardinality of the whole curve.

To me it seems correct that the space of public keys is defined as 162-bit wide, as that is the number of points in the prime order subgroup.

@git-blame does this make sense?

**Comment by git-blame** [comment]
From a security perspective, it's the size of the private key that's important. It's the same size as the order of the group because you modulo the order when you compute the private key. So it's true that you can say that sect163r1 is 162-bit.

The literal size of the public key is the field size + 1 (for the x coordinate + y bit). So for sect163r1 it would actually be 164.

In any case, both answers would be hard to explain to marketing or corporate customers who tend to think that the curve name like sect163r1 (or secp256r1 etc.) tells you something about their key size.

So at least for me, I think I may just have to stick with the "easy-to-explain" answer/calculation which maps to the degree of the group.

**Comment by romen** [comment]
Well, that doesn't really work well with some of the curves that have bigger cofactors either.

Also the bit length of the public key really depends on the chosen encoding, compressed coordinates is not the default (as in the key above, the first `0x04` byte signals non compressed coordinates) so if you count the bits of the printed public key that is actually `(1+2*21)*8` that includes padding as a single uncompressed coordinate requires 21 bytes to represent 163 bit scalars, plus the initial byte to mark uncompressed (that would become `0x02` or `0x03` if it represented the sign of y in compressed encoding).

That 162 is not meant to be the bitlentgh of the public key per sé, but rather an indication of the ECDLP strength of the __keypair__, which a user could use (roughly by halving, or more precisely consulting the tables in the relevant reference standard of her choice) to assess the equivalent security level (to compare with symmetric crypto systems).

A user receiving a public key (e.g. reading the details of a TLS certificate) should be able to understand the equivalent security level achievable by using that public key: how difficult is for an attacker to break the security of this signature and authenticate as my intended peer? How difficult is it for an attacker to break ECIES encryption if I want to encrypt something for the owner of this public key? Etc.

That 162 is the proper measure of the security level of the EC key pair, akin to saying this RSA or DSA keypair is a 1024/2048/4096 key even though that is not necessarily the literal bitlen of the public key encoding.

At least this is my interpretation of the textual output included at the beginning of the issue: that is not a bit length but the size of the key in a security sense.

**Comment by git-blame** [comment]
Yes, that length is the size of the public key in the security sense. Openssl has made it equivalent to simply counting the bits in the order of the group. This is OK as it is essentially the same size as the private key. And the security of a EC keypair or public key is simply the strength of the private key.

We can also switch and use symmetric key security level equivalence. As you say, that is usually by halving the number of bits. I believe more generally it is dividing by the cofactor. Or consulting a specific crypto standard.

When I say literal public key size I meant minimal. That is, the smallest number of bits to represent the key. This is the x coordinate + the signed y bit. This is not quite the same as compressed format because as you pointed out, the typical representation includes a "format" byte and so on.

In any case, openssl is ok. I just have to find a way to explain to more casual users why there are "weird values" with some curves.
