### ISSUE TITLE
Decoding error loading valid PKCS#8 DER private key

### ISSUE THREAD

**Issue by oberien** [openssl/openssl#10543]
When loading a valid PKCS#8 private key stored in DER format, the asn.1 decoder errors both using the commandline and the C API.

```
openssl genrsa -out private.pem 2048
openssl pkcs8 -topk8 -in private.pem -inform pem -outform der -nocrypt -out test
openssl pkcs8 -in test -inform der

Error reading key
140015482615040:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1130:
140015482615040:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:290:Type=X509_ALGOR
140015482615040:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:627:Field=algor, Type=X509_SIG
```

The C library API errors with the same error stack when using `d2i_PKCS8PrivateKey_bio`.

Tested versions:
* OpenSSL 1.1.1d  10 Sep 2019 (5.3.8-arch1-1)
* OpenSSL 1.1.1a-freebsd  20 Nov 2018

**Comment by levitte** [comment]
The manpage says this:

> **-nocrypt**
>           PKCS#8 keys generated or input are normally PKCS#8
>           EncryptedPrivateKeyInfo structures using an appropriate password
>           based encryption algorithm. With this option an unencrypted
>           PrivateKeyInfo structure is expected or output.  This option does
>           not encrypt private keys at all and should only be used when
>           absolutely necessary. Certain software such as some versions of
>           Java code signing software used unencrypted private keys.

... and true enough:

```
: ; openssl pkcs8 -in test -inform der -nocrypt
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

**Comment by levitte** [comment]
One might argue that the command should be able to detect on its own what kind of data it's getting.  That will not happen for 1.1.x, but will hopefully happen in 3.0 (it depends on me getting a certain PR through)
