### ISSUE TITLE
Algorithm ED25519 not found

### ISSUE THREAD

**Issue by astha-nimblechapps** [openssl/openssl#10554]
Hi, 

I have openssl with version LibreSSL 2.6.5 which does not support algorithm ed25519 for generating private key. So need help how to generate the private key using ed25519 algorithm because when ever I write 

> openssl genpkey -algorithm ed25519 -outform PEM -out test.pem

always prompt  Algorithm ed25519 not found and error in genkey. 

Thank You.

**Comment by paulidale** [comment]
Perhaps ask the [LibreSSL people](https://www.libressl.org/mail.html), this isn't a problem with OpenSSL.
