### ISSUE TITLE
util/mkerr.pl does not add legacy include guards

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#10569]
During the header reorganization (#9333) the include guard names were changed from `HEADER_..._H` to `OPENSSL_..._H`. For the public header files, the old names were retained for compatibility reasons, but they are deprecated for 3.0.

- d86167ec75 Add legacy include guards to public header files
- ae4186b004 Fix header file include guard names  

_(Commits are listed bottom-up)_ This change applied also to the autogenerated error files, see for example [include/openssl/asn1err.h](https://github.com/openssl/openssl/commit/d86167ec7513265bbafaf5c13fa60bd7c23aa732#diff-cf5837e4d66ad5d1ee8e0d982bbf4384R13-R18):

```C
# pragma once

# include <openssl/macros.h>
# if !OPENSSL_API_3
#  define HEADER_ASN1ERR_H
# endif
```
However, the mkerr.pl script was never adjusted to add the legacy include guards. The only change to mkerr.pl was made in ae4186b00487: 

```patch
~/src/openssl$ git show ae4186b00487 -- util/mkerr.pl

diff --git a/util/mkerr.pl b/util/mkerr.pl
index c2888890cd..c8ec94d288 100755
--- a/util/mkerr.pl
+++ b/util/mkerr.pl
@@ -447,8 +447,8 @@ foreach my $lib ( keys %errorfile ) {
  * https://www.openssl.org/source/license.html
  */
 
-#ifndef HEADER_${lib}ERR_H
-# define HEADER_${lib}ERR_H
+#ifndef OPENSSL_${lib}ERR_H
+# define OPENSSL_${lib}ERR_H
 
 # include <openssl/opensslconf.h>
 # include <openssl/symhacks.h>
```
As a consequence, the legacy include guards get lost when the files are regenerated because new symbols are added. (This was noticed in https://github.com/openssl/openssl/pull/10549#issuecomment-560174422.)

### Todo: ###

The mkerr.pl script still needs to be adjusted to add the legacy guard, but not unconditionally; only if the file already has a legacy guard. Instead of scanning the existing header file, the mkerr.pl script could just check the following whitelist of legacy guard names, if that's significantly simpler to implement:

```
~/src/openssl$ git diff d86167ec75 -- include/openssl/*err.h | grep HEADER_

 #  define HEADER_ASN1ERR_H
 #  define HEADER_ASYNCERR_H
 #  define HEADER_BIOERR_H
 #  define HEADER_BNERR_H
 #  define HEADER_BUFERR_H
 #  define HEADER_CMSERR_H
 #  define HEADER_COMPERR_H
 #  define HEADER_CONFERR_H
 #  define HEADER_CRYPTOERR_H
 #  define HEADER_CTERR_H
 #  define HEADER_DHERR_H
 #  define HEADER_DSAERR_H
 #  define HEADER_ECERR_H
 #  define HEADER_ENGINEERR_H
 #  define HEADER_ERR_H
 #  define HEADER_EVPERR_H
+#  define HEADER_OSSL_KDFERR_H
 #  define HEADER_OBJERR_H
 #  define HEADER_OCSPERR_H
 #  define HEADER_PEMERR_H
 #  define HEADER_PKCS12ERR_H
 #  define HEADER_PKCS7ERR_H
-#  define HEADER_RANDERR_H
 #  define HEADER_RSAERR_H
 #  define HEADER_SSLERR_H
 #  define HEADER_OSSL_STOREERR_H
 #  define HEADER_TSERR_H
 #  define HEADER_UIERR_H
 #  define HEADER_X509ERR_H
 #  define HEADER_X509V3ERR_H
```

**Comment by mspncp** [comment]
It's still a problem. Just ran `make update` on #11111 and got this:

```diff
~/src/openssl$ git diff -- include/openssl/randerr.h
diff --git a/include/openssl/randerr.h b/include/openssl/randerr.h
index 68992d771d..fc934ff486 100644
--- a/include/openssl/randerr.h
+++ b/include/openssl/randerr.h
@@ -1,6 +1,6 @@
 /*
  * Generated by util/mkerr.pl DO NOT EDIT
- * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
+ * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
  *
  * Licensed under the Apache License 2.0 (the "License").  You may not use
  * this file except in compliance with the License.  You can obtain a copy
@@ -10,12 +10,6 @@
 
 #ifndef OPENSSL_RANDERR_H
 # define OPENSSL_RANDERR_H
-# pragma once
-
-# include <openssl/macros.h>
-# ifndef OPENSSL_NO_DEPRECATED_3_0
-#  define HEADER_RANDERR_H
-# endif
 
 # include <openssl/opensslconf.h>
 # include <openssl/symhacks.h>
@@ -41,6 +35,7 @@ int ERR_load_RAND_strings(void);
 #  define RAND_F_RAND_DRBG_GENERATE                        0
 #  define RAND_F_RAND_DRBG_GET_ENTROPY                     0
 #  define RAND_F_RAND_DRBG_GET_NONCE                       0
+#  define RAND_F_RAND_DRBG_INIT_METHOD                     0
 #  define RAND_F_RAND_DRBG_INSTANTIATE                     0
 #  define RAND_F_RAND_DRBG_NEW                             0
 #  define RAND_F_RAND_DRBG_RESEED                          0
```

**Comment by mspncp** [comment]
ping @levitte

**Comment by levitte** [comment]
Thing is that some new headers never had the legacy guards.  `HEADER_OSSL_KDFERR_H` is the perfect example.

I frankly find it questionable to keep them at all.  Did anyone actually use those for anything?

**Comment by mspncp** [comment]
I wouldn't mind if we remove the legacy guards from all error headers entirely and from the mkerr.pl script as well. This would makes things a lot easier. If you agree, I could create the pr for it.

**Comment by mspncp** [comment]
See #11541
