### ISSUE TITLE
ex_data lock free'd too early?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10573]
The comment at https://github.com/openssl/openssl/blob/master/crypto/ex_data.c#L40 seems wrong, especially given #10572.  It appears that when the module is unloaded crypto_cleanup_all_ex_data_int frees the context's global exdata lock.  And on program exit, the openssl cleanup cleans up the global context exdata lock.

If I comment out the NULL at https://github.com/openssl/openssl/blob/master/crypto/ex_data.c#L49 then fipsinstall crashes.  I have not debugged this.  Any pointers, @slontis?

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by richsalz** [comment]
five years, nobody duplicate this, so closing.
