### ISSUE TITLE
A performance issue about dtls1_get_record

### ISSUE THREAD

**Issue by simplelins** [openssl/openssl#10581]
Hi：
     One scene that we received a mssage from peer the length is up to 16k bytes(`SSL3_RT_MAX_PLAIN_LENGTH`), but actual effective length of the message only is 200 bytes. So when we call `ssl_read` next time, function `dtls1_get_record` will do more times goto forloop to drop the useless message that last time received and saved at `s->rlayer.rbuf` . `s->rlayer.rbuf->left` near to 16k。
     In this scene,there are any warning or error for us,so it is difficult to find this bug.This is a great loss of performance。
    Further，if someone take this bug to send a useless big package to peer,this may lead to reduced peer performance。
    Please check！

**Comment by mattcaswell** [comment]
I'm not sure I understand the problem you are reporting.

You said "the length is up to 16k bytes(SSL3_RT_MAX_PLAIN_LENGTH), but actual effective length of the message only is 200 bytes". So is the message malformed in some way? If so, in what way is it malformed?

> ext time, function dtls1_get_record will do more times goto forloop to drop the useless message

There are no "for" loops in this function so I'm not entirely sure what you are referring to. However there are a number of places where we drop messages and then "goto again" to restart reading of the record - so I assume this is what you are referring to. Which test is failing causing the message to be dropped?
