### ISSUE TITLE
How to handle SSL_ERROR_WANT_ASYNC in libevent

### ISSUE THREAD

**Issue by luwenpeng** [openssl/openssl#10598]
I want to integrate the ASYNC ssl features of openssl into libevent so that libevent supports qat. I encountered some problems in my work and would like to ask for your help.

The implementation process is as follows：

1. SSL_CTX_set_mode(SSL_MODE_ASYNC);
2. SSL_set_mode(SSL_MODE_ASYNC);
3. after tcp connect, get clientfd
4. event_add(clientfd, EV_READ|EV_WRITE, ssl_handshake);
5. When the client is readable / writable, run ssl_handshake.

``` c
    ssl_handshake()
    {
        SSL_do_handshake();
        err = SSL_get_error();
        if (err == SSL_ERROR_WANT_ASYNC)
        {
            event_del(clientfd, EV_READ);
            event_del(clientfd, EV_WRITE);

            call SSL_get_changed_async_fds() get async_fds

            // Register a readable event on asyncfd to detect when the engine is ready
            event_add(async_fds, READ, ssl_async_handshake);
        }
    }
```

6. When async_fds is readable, it means that the engine is ready. Run ssl_async_handshake, re-enable the clientfd read and write events, and continue the operation（next SSL_do_handshake)
``` c
    ssl_async_handshake()
    {
        event_add(clientfd, EV_READ, ssl_handshake);
        event_add(clientfd, EV_WRITE, ssl_handshake);
    }
```

Q1. Is there a problem with my process?

Q2. During the test, SSL_do_handshake will continue to return SSL_ERROR_WANT_ASYNC multiple times (exactly 9 times) before it succeeds. Is this normal?

Q3. The processing flow of SSL_read / SSL_write returning SSL_ERROR_WANT_ASYNC is similar to that of SSL_do_handshark, but SSL_read / SSL_write never returns SSL_ERROR_WANT_ASYNC during the test, is this a normal result? How can I test the processing flow of SSL_read / SSL_write returning SSL_ERROR_WANT_ASYNC？

**Comment by jim228** [comment]
I encountered exactly the same problem with libuv + epoll, SSL_read/SSL_write won't return SSL_ERROR_WANT_ASYNC. could anyone make a comment? 

Thank you,
Jim

**Comment by mattcaswell** [comment]
> Q1. Is there a problem with my process?

I'm not familiar with libevent, but from an OpenSSL perspective it sounds about right.

> Q2. During the test, SSL_do_handshake will continue to return SSL_ERROR_WANT_ASYNC multiple times (exactly 9 times) before it succeeds. Is this normal?

Exactly what happens will depend on the engine. Normally I would expect SSL_do_handshake() to return SSL_ERROR_WANT_ASYNC initially. If you then don't call SSL_do_handshake() again until the async_fds are readable then I would not expect to see another SSL_ERROR_WANT_ASYNC. If you do get one then the engine is saying that it is still not finished with its async process (or possibly started a second one), even though it signalled it was ready via the async_fd. If you are seeing strange behaviour here then it is probably better to pose the question to the engine author.

> Q3. The processing flow of SSL_read / SSL_write returning SSL_ERROR_WANT_ASYNC is similar to that of SSL_do_handshark, but SSL_read / SSL_write never returns SSL_ERROR_WANT_ASYNC during the test, is this a normal result? How can I test the processing flow of SSL_read / SSL_write returning SSL_ERROR_WANT_ASYNC？

This is entirely possible and engine dependent. During the handshake we are typically performing asymmetric crypto operations which are often long running and are a prime target for offload to an asynchronous engine. During SSL_read/SSL_write we are typically performing symmetric crypto operations which are usually a lot faster. It is an entirely reasonable strategy for an engine to only perform asymmmetric crypto asynchronously, but not do the same for the symmetric crypto. OpenSSL itself supports it, but the engine may not. Again this is a question for the engine author.

**Comment by nhorman** [comment]
looks like this was  a request to alter libevent, not openssl, and questions have been answered, closing
