### ISSUE TITLE
can't access https site by openssl 1.0.2k

### ISSUE THREAD

**Issue by akitaTian** [openssl/openssl#10591]
### I did this
**./openssl s_client -cipher ALL  -connect IP:443**
OutPut:
CONNECTED(00000003)
140608367363984:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:

no peer certificate available
No client certificate CA names sent
SSL handshake has read 0 bytes and written 364 bytes
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1575920735
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

--------
**but when i sort the ALL ciphers by SSLv2, SSLv3, TLS...  it's work**

OutPut:
CONNECTED(00000003)
depth=0 CN = mail.yn.stats.cn
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = mail.yn.stats.cn
verify error:num=21:unable to verify the first certificate
verify return:1
Certificate chain
 0 s:/CN=mail.yn.stats.cn
   i:/DC=cn/DC=stats/CN=ChinaNBS
Server certificate
-----BEGIN CERTIFICATE-----
MIIGBTCCBO2gAwIBAgIKYS2MlQAAAAAC5zANBgkqhkiG9w0BAQUFADA+MRIwEAYK
CZImiZPyLGQBGRYCY24xFTATBgoJkiaJk/IsZAEZFgVzdGF0czERMA8GA1UEAxMI
Q2hpbmFOQlMwHhcNMTYwMzAyMDQwNjA2WhcNMTgwMzAyMDQwNjA2WjAbMRkwFwYD
VQQDExBtYWlsLnluLnN0YXRzLmNuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAs20qnMIcVwnIUTgdCgOs8Wgxz/+0utOPpEommjLySKGtWQKPexuF421C
b4XMUPOvyoer/eBE1Nkyd7Eh5yjfWo6CE/hD8OvD4js99l0b+3GEwCd3Zs6obJiR
maZqBKO8JbTdbfqKGnn+lyuDoLDzPocArW/NBJ4SxE8SjGnKwdBTvQUK4Tia475m
GUuUOIw148Ker7flrZSs27bNlF547a2COKWdL8tHst+gvWWPzAym2dRkKcWmH6dY
IHeQwjPyFQBm2x+GilePryFbFXG+4TeSxGZ5wEgil3+RBzjoSrOHI74sn5QC8Z0N
GvsJXRGO/Y+gVsGnSGNO1t3DCeijeQIDAQABo4IDJjCCAyIwHQYDVR0OBBYEFMe9
5kaMsPlCuEqvr/5lE2bCfXlcMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAsGA1UdDwQE
AwIFoDCBjgYDVR0RAQH/BIGDMIGAghBtYWlsLnluLnN0YXRzLmNughhhdXRvZGlz
Y292ZXIueW4uc3RhdHMuY26CGXluLWV4aGNubGItMDEueW4uc3RhdHMuY26CFnlu
LWV4aGMtMDEueW4uc3RhdHMuY26CBG1haWyCCnluLWV4aGMtMDGCDXluLWV4aGNu
bGItMDEwHwYDVR0jBBgwFoAUjU8Gg4ytqHGkOgLh/67VIrsCPAQwgfoGA1UdHwSB
8jCB7zCB7KCB6aCB5oaBr2xkYXA6Ly8vQ049Q2hpbmFOQlMsQ049R0otUlREQy0w
MixDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMs
Q049Q29uZmlndXJhdGlvbixEQz1zdGF0cyxEQz1jbj9jZXJ0aWZpY2F0ZVJldm9j
YXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSG
Mmh0dHA6Ly9nai1ydGRjLTAyLnN0YXRzLmNuL0NlcnRFbnJvbGwvQ2hpbmFOQlMu
Y3JsMIIBCwYIKwYBBQUHAQEEgf4wgfswgaQGCCsGAQUFBzAChoGXbGRhcDovLy9D
Tj1DaGluYU5CUyxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049
U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1zdGF0cyxEQz1jbj9jQUNlcnRp
ZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTBS
BggrBgEFBQcwAoZGaHR0cDovL2dqLXJ0ZGMtMDIuc3RhdHMuY24vQ2VydEVucm9s
bC9HSi1SVERDLTAyLnN0YXRzLmNuX0NoaW5hTkJTLmNydDAhBgkrBgEEAYI3FAIE
FB4SAFcAZQBiAFMAZQByAHYAZQByMA0GCSqGSIb3DQEBBQUAA4IBAQAI6TWu+5e2
XaaaYYX8ltAU+Cvbt0jCYWw4Lm8l/oIgDPlLO3weQ0rGN2Wpbf8GAzrLhAMXI/5G
dqavn5m61rKPyGoS27DFiMHFzecXaAfx5EMg2Rf8ZOJznEpvLpmu+VQpg5C1jnED
6IWe7CGs1ehToCRspGGnHMAmAf+o2oELgYN2EIsqgo2q416zv2Jzt+Wszss56t+D
GZTcUAO0PEGlobxC7a6Ydrojr9BgQsplvTSos1eCXG17NqTC/XVkOnGLTub8fH+s
du8Xjr39Rl8JQ9oKKEHWNie71hEKPNUKYC1gwZd4nBgzqR73JLoKk9mUd2CNhiOv
SoT1u4qwljLN
-----END CERTIFICATE-----
subject=/CN=mail.yn.stats.cn
issuer=/DC=cn/DC=stats/CN=ChinaNBS

No client certificate CA names sent

SSL handshake has read 1681 bytes and written 690 bytes

New, TLSv1/SSLv3, Cipher is RC4-MD5
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : RC4-MD5
    Session-ID: CC00000014E92E655700712DC6F6EAD8F2F62BECD38627AAD44E08BD8A55082B
    Session-ID-ctx:
    Master-Key: 76FC3E0A911EC9A7A4B18514BD1839B9CB3D1E5E949971E7A8756A28BFF53E37CA8CEA2B4B7619E442551B96147F858B
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1575920768
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)

-------
And server side is IIS6.0

The SSLScan output 
     Supported Server Cipher(s):
Preferred TLSv1.0  128 bits  RC4-MD5
Accepted  TLSv1.0  128 bits  RC4-SHA
Accepted  TLSv1.0  112 bits  DES-CBC3-SHA
Accepted  TLSv1.0  56 bits   DES-CBC-SHA
Preferred SSLv3    128 bits  RC4-MD5
Accepted  SSLv3    128 bits  RC4-SHA
Accepted  SSLv3    112 bits  DES-CBC3-SHA
Accepted  SSLv3    56 bits   DES-CBC-SHA 

the ALL string contains 'Supported Server Cipher'
### I expected the following
the ciphers list string ALL can access the https site

### version

openssl  version 1.0.2k
----------
compile options 
./config --prefix=/root/openssl1_0_2k  shared zlib threads sctp enable-krb5 --with-krb5-flavor=MIT enable-weak-ssl-ciphers enable-ssl2 enable-ssl3

### operating system
CentOS Linux release 7.0

**Comment by akitaTian** [comment]
I know the server is so old, But can i access the https site in a generic way instead of specifying the suite type, like ALL string.

**Comment by mattcaswell** [comment]
> 140608367363984:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:

Do you have access to the server logs? This only tells us that something failed on the server side, but not what or why.

**Comment by akitaTian** [comment]
> Do you have access to the server logs? This only tells us that something failed on the server side, but not what or why.

NO,  I just know server is IIS6.0,   And I used tcpdump to view the ssl package. Only the cipher suite order is different(Client Hello),     In the case of failure, directly return FIN ack.

**Comment by akitaTian** [comment]
I  created a test site ,  windows server 2013 IIS6.0     same situation,     server logs == IIS log?

**Comment by akitaTian** [comment]
Windows Server 2013 IIS6.0  has a limit on the number of cipher suites？  so werid...

**Comment by mattcaswell** [comment]
> NO, I just know server is IIS6.0, And I used tcpdump to view the ssl package. Only the cipher suite order is different(Client Hello), In the case of failure, directly return FIN ack.

This suggests to me that there is one particular cipher (or perhaps a set of ciphers) that the server is selecting and then failing at some later point in the process to use that ciphersuite. If you change the order of the ciphersuites then it probably means that you end up selecting a different ciphersuite and hence the connection is successful. It might be helpful to narrow down which particular ciphersuite(s) the server has difficulty with.

**Comment by mattcaswell** [comment]
> I created a test site , windows server 2013 IIS6.0 same situation, server logs == IIS log?

I'm not familiar with IIS, but presumably somewhere there is a log which tells us any errors that it has encountered with a connection. We're looking for a clue somewhere that might tells us why it is failing the handshake.

**Comment by akitaTian** [comment]
> > NO, I just know server is IIS6.0, And I used tcpdump to view the ssl package. Only the cipher suite order is different(Client Hello), In the case of failure, directly return FIN ack.
> 
> This suggests to me that there is one particular cipher (or perhaps a set of ciphers) that the server is selecting and then failing at some later point in the process to use that ciphersuite. If you change the order of the ciphersuites then it probably means that you end up selecting a different ciphersuite and hence the connection is successful. It might be helpful to narrow down which particular ciphersuite(s) the server has difficulty with.

Windows Server 2013 IIS6.0 has a limit on the number of cipher suites？？？

**Comment by mattcaswell** [comment]
> Windows Server 2013 IIS6.0 has a limit on the number of cipher suites？？？

If that  is the case (I've never heard this before), then it sounds seriously broken!

**Comment by akitaTian** [comment]
sorry is Windows 2003 I just guessed based on the test

**Comment by richsalz** [comment]
It *could* have a limit on the size of the ClientHello, which would of course be affected by the ciphers that the client sends.  We've seen that in other implementations, too.

**Comment by kroeckx** [comment]
I think this is a known problem with IIS 6.0, but I forgot the details.
Was it SHA256 that had a broken implementation or something?

Have all the security updates been installed on it?

**Comment by mspncp** [comment]
> ### I did this
> **./openssl s_client -cipher ALL -connect IP:443**
> OutPut:
> CONNECTED(00000003)
> 140608367363984:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
> 
> no peer certificate available
> No client certificate CA names sent
> SSL handshake has read 0 bytes and written 364 bytes
> New, (NONE), Cipher is (NONE)
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
> Protocol : TLSv1.2


I noticed that the summary of your very first connect call mentions TLSv1.2, but according to http://www.g-sec.lu/sslharden/SSL_comp_report2011.pdf, IIS6 did not support TLSv1.2, only TLSv1.0. 

![image](https://user-images.githubusercontent.com/11467854/70470144-b2944980-1aca-11ea-894f-aff038fe0623.png)

Does the connect succeed if you add `-tls1`?

**Comment by akitaTian** [comment]
@richsalz  @kroeckx   
The server is unknown to me,   Can I solve the above problem by sorting？  or other methods?

**Comment by akitaTian** [comment]
@mspncp  
> Does the connect succeed if you add -tls1?
yes,   but succeed too when i sort the ciphers suite.

**Comment by richsalz** [comment]
So @akitaTian sounds like you have the answer: sort the ciphers.  Just pick something that works.

**Comment by akitaTian** [comment]
I find a discussion:  https://discussions.qualys.com/thread/16486-when-cant-openssl-connect-to-server-2003

**Comment by mspncp** [comment]
For completeness, I cite the [answer from that discussion](https://discussions.qualys.com/thread/16486-when-cant-openssl-connect-to-server-2003#comment-34404):

> 2) Failure occurs because of too many ciphers in the SSL Client Hello.
>
> I found a contributor on another forum who said that Server 2003 had an issue with more than 64 ciphers.  It asserted that Server 2003 will ignore cipher suites after the 64th entry in the Client Hello.  My testing indicates that it rejects the Client Hello completely when there are too many cipher suites offered.  Most of the client configurations tested by OpenSSL do not have a problem connecting to Server 2003 because they do not support enough cipher options to hit the 64 entry limit.   I adjusted the configuration of my Web Application Firewall appliance to limit the cipher suites offered in the Client Hello, and the problem was solved.

There seem to be two valid workarounds, sorting the ciphers or using `-tls1`. @akitaTian do you consider your question answered, can this ticket be closed now?

**Comment by akitaTian** [comment]
@mattcaswell @richsalz @kroeckx @mspncp 
Thanks for your help!!
