### ISSUE TITLE
Repeated return string in openssl source tar 1.1.1d.

### ISSUE THREAD

**Issue by santoshkumarlaxminarayanrai** [openssl/openssl#10596]
In source code tar of openssl v1.1.1d file **crypto/thread_none.c** line : **146**
have coding error as : **return return 0;**

**Comment by t8m** [comment]
This is already fixed in the 1.1.1 branch and the fix will be included in the next release from the branch.

**Comment by santoshkumarlaxminarayanrai** [comment]
Thanks....

**Comment by mspncp** [comment]
Duplicates #9858. Fixed in 1.1.1 by c3656cc594daac8167721dde7220f0e59ae146fc.
