### ISSUE TITLE
Link errors in 1.1 Windows static build: unresolved external symbol __imp_CertOpenStore

### ISSUE THREAD

**Issue by rustyx** [openssl/openssl#1061]
The documentation on [Windows static libs](https://github.com/openssl/openssl/blob/master/NOTES.WIN#L107-L109) seems to be outdated.
In fact, OpenSSL 1.1 seems to require one additional library, `CRYPT32.LIB` when linking on Windows XP or later.

Otherwise I get link errors:

```
1>libcrypto.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp_CertOpenStore
1>libcrypto.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp_CertCloseStore
1>libcrypto.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp_CertEnumCertificatesInStore
1>libcrypto.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp_CertFindCertificateInStore
1>libcrypto.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp_CertDuplicateCertificateContext
1>libcrypto.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp_CertFreeCertificateContext
1>libcrypto.lib(e_capi.obj) : error LNK2001: unresolved external symbol __imp_CertGetCertificateContextProperty
```

There is currently absolutely no mention of crypt32.lib in NOTES.WIN.

**Comment by levitte** [comment]
Yes, you are entirely correct.   This goes for earlier released versions as well, btw...

**Comment by levitte** [comment]
Oh, wait, haha, did we just do double work?

**Comment by rustyx** [comment]
I believe so :)

**Comment by levitte** [comment]
Ok.  I noticed you closed yours, so now we just have to wait for someone to review the changes I did.

**Comment by mattcaswell** [comment]
Can this be closed now?

**Comment by rustyx** [comment]
Looks good. Thanks!

**Comment by Croydon** [comment]
I guess this can be closed?
