### ISSUE TITLE
Missing null-check after CRYPTO_zalloc

### ISSUE THREAD

**Issue by KihongHeo** [openssl/openssl#10612]
> 
Hi, there are some calls to `CRYPTO_zalloc` that miss return value checking:

https://github.com/openssl/openssl/blob/77fedcdc8cf5446354a1e7ff9123d8ada5b79b06/providers/implementations/macs/poly1305_prov.c#L46-L48

https://github.com/openssl/openssl/blob/77fedcdc8cf5446354a1e7ff9123d8ada5b79b06/providers/implementations/macs/siphash_prov.c#L52-L54

**Comment by slontis** [comment]
@paulidale this should have closed automagically?

**Comment by paulidale** [comment]
Yeah, I'd have thought so.
