### ISSUE TITLE
Windows Cross Platform build of Android libraries is not possible - NMAKE : fatal error U1095, U1077

### ISSUE THREAD

**Issue by jzer0** [openssl/openssl#10627]
When attempting to perform a cross platform build of the openSSL 1.1.0 Android libraries from a Windows 10 host OS:

nmake

Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\nmake.exe" depend && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\nmake.exe" _all

Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1095:
...
fi;  fi' too long
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\nmake.exe"' : return code '0x2'
Stop

Full output is attached.  I have tried multiple NDK\SDK versions and every suggestion I have been able to find in order to resolve this issue except for attempting to manually adjust the configdata.pm file.  I have also attempting building using make and various setenv scripts.  I am assuming that NASM is being used to address this when building for Windows, but this does not seem to be utilized here.  Please confirm whether it should be possible to build the Android libs from a Windows OS or if this is only supported on a Linux environment.
[nmake_fail_output.txt](https://github.com/openssl/openssl/files/3964253/nmake_fail_output.txt)

**Comment by levitte** [comment]
> Please confirm whether it should be possible to build the Android libs from a Windows OS or if this is only supported on a Linux environment.

It's currently only supported on a Linux environment.  *If* we get Windows support as well, it will be in 3.0.

Side note: 1.1.0 has reached end of life, I'd like to suggest an upgrade to the latest 1.1.1.

**Comment by jzer0** [comment]
Much appreciated!
