### ISSUE TITLE
How to compile openssl on windows

### ISSUE THREAD

**Issue by xp19870106** [openssl/openssl#10641]
How to compile openssl on windows?
Where can I find the instructions?

**Comment by mattcaswell** [comment]
Check the INSTALL file for compilation instructions. This includes instructions for Windows:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/INSTALL

There are also some windows specific notes here:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/NOTES.WIN
