### ISSUE TITLE
Can you explain the differences ?

### ISSUE THREAD

**Issue by Legends** [openssl/openssl#10649]
What does a,b,c,d mean?
Which one to download?

![image](https://user-images.githubusercontent.com/966368/71102863-7000fa00-21b9-11ea-9205-df2cb48ede16.png)

**Comment by levitte** [comment]
The letters are release updates for each minor release. If you don't have an openssl version to update, I would simply go with the highest available, 1.1.1d. As time goes, you will probably see 1.1.1e, 1.1.1f and so on, and can simply update your installation with those as they appear.

Did that clarify things?

**Comment by levitte** [comment]
Do note that with upcoming 3.0, we're changing our versioning scheme, and the update releases (some call them patch releases) will be 3.0.1, 3.0.2 and so on.

**Comment by Legends** [comment]
Thanks for your answer, now it's clear.
