### ISSUE TITLE
The new DSA serializers aren't ever called

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#10645]
PR #10394 added support for various serializers including DSA. However while the other serializers were integrated into the default provider, the DSA ones were not for some reason. Similarly that PR added tests for the other serializers into evp_pkey_provided_test.c but not for DSA for some reason.

**Comment by levitte** [comment]
The code is there, but the lines in `deflt_serializer` are missing.  I *think* that's all it takes to integrate them.  Plus a test similar to the others, that should do it.
