### ISSUE TITLE
Remove SXNET cert extension

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10668]
Like #1177 et al, the "Strong Extranet" extension from Thawte is probably obsolete.

A search on censys, https://censys.io/certificates?q=extensions.id%3D1.3.101.1.4.1, shows one expired certificate and one wacky one.
https://censys.io/certificates/16dbb695f328659206147bded9308c56659ada63c583bea2f983ea426f863088 (that is good for about 11,000 days!)

**Comment by nhorman** [comment]
This has been discussed several time since my tenure here, and while it does seem obsolete, it seems theres no strong willingness to remove this on the off chance someone is still using it.

Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by richsalz** [comment]
See #1177  which also has pointed to sample code if you want it.  Closing this.
