### ISSUE TITLE
Issue with ECDSA signature generation

### ISSUE THREAD

**Issue by amrithathorath** [openssl/openssl#10670]
I've got a piece of code that successfully generates ECDSA signature for the following input when using OpenSSL 1.0.2*.

```
[P-256,SHA-224]

Msg = 07a73bd301c01afb7eb05e37f029bdf94f5d741573ccd42dc15bfe6d09a7eb79af98afa40939fe6309c7ef011c08009451dd5a2fbe1b5759209742bec1805e259ff229a2cac7e10d0eb148b2d286a54a40da0b2ba6d3ddbb1c39922a68cdb6611edc31350c13cce1d495f1b3db4bb205627b0e6ff39d6f3bff6a7619c535fb14
```
But the same code does not work when I'm using OpenSSL1.1.1.

My code is shown below:

```
        Qx = BN_new();
        Qy = BN_new();
        
        key = EC_KEY_new_by_curve_name(curve_nid);

        if ( !EC_KEY_generate_key(key) ) {
                LOG_ERROR("EC_KEY_generate_key() failed in %s at %d\n", __FILE__, __LINE__);
                LOG_ERROR("OpenSSL reports:   %s\n", ERR_error_string(ERR_get_error(), NULL));
                goto fail;
        }

        if ( !ec_get_pubkey(key, Qx, Qy) ) {
                LOG_ERROR("ec_get_pubkey() failed in %s at %d\n", __FILE__, __LINE__);
                LOG_ERROR("OpenSSL reports:   %s\n", ERR_error_string(ERR_get_error(), NULL));
                goto fail;
        }

        ctx = EVP_MD_CTX_create();
        rv = EVP_DigestInit_ex(ctx, md, NULL);

        rv = EVP_DigestUpdate(ctx, message, 128);

        rv = EVP_DigestFinal_ex(ctx, sig_buf, &temp);

        sig = ECDSA_do_sign(sig_buf, 128, key);

```

Basically if the curve value is greater than the SHA value, it segfaults.

**Comment by romen** [comment]
Can you give more details about this?
Where is the segmentation fault triggered? 
Also, the snippet above is lacking a few of checks on the return values that would help catch errors before a segmentation fault.

We should still investigate the problem you are experiencing, but at the same time it is worth mentioning that we are encouraging to move to the EVP API rather than the low level one used in the snippet above, as EVP is more flexible and will make it easier also to port to 3.0 (when it will be released) supporting all the new features.

**Comment by amrithathorath** [comment]
@romen : Thanks for the response.
I omitted the error checking on return values, but assure you it is present.

Here's what I see on my output with 1.0.2

```
  INFO:         looking up curve_nid from params->curve (13)
  INFO:         calling EC_KEY_new_by_curve_name()
  INFO:         creating storage for components
  INFO:         calling EC_KEY_set_public_key_affine_coordinates()
  INFO:         calling EVP_PKEY_new()
  INFO:         calling EVP_PKEY_assign_EC_KEY()
  INFO:         creating new sig
  INFO:         setting md function pointer
  INFO:         creating new mdctx

  INFO:         calling EVP_DigestInit_ex()
  INFO:         calling EVP_DigestUpdate()
  INFO:         calling EVP_DigestFinal_ex()
  INFO:         calling ECDSA_do_verify()
 DEBUG:                 ECDSA_shim_SignatureVerification() reports params->isValid == YES
```

Here's what I see on my output with 1.1.1.

```
  INFO:         looking up curve_nid from params->curve (13)
  INFO:         calling EC_KEY_new_by_curve_name()
  INFO:         creating storage for components
  INFO:         calling EC_KEY_set_public_key_affine_coordinates()
  INFO:         calling EVP_PKEY_new()
  INFO:         calling EVP_PKEY_assign_EC_KEY()
  INFO:         creating new sig
  INFO:         setting md function pointer
  INFO:         creating new mdctx

  INFO:         Non-FIPS mode
  INFO:         calling EVP_DigestInit_ex()
  INFO:         calling EVP_DigestUpdate()
  INFO:         calling EVP_DigestFinal_ex()
  INFO:         calling ECDSA_do_verify()
 DEBUG:                 ECDSA_shim_SignatureVerification() reports params->isValid == NO
```

If you see, the only difference is that with 1.1.1 the signature returned is always invalid. I've a retry condition to generate until I've a valid signature but I never hit that point with 1.1.1. But that's not the issue when I'm using 1.0.3 for same code and same input.

**Comment by romen** [comment]
In the first code snippet you call ECDSA_do_sign with a fixed size of 128, instead of using the value stored in temp by DigestFinal.

I can't really say why that is not causing segfault on 1.0.2, but might explain it? 

Forgive me, but from the second comment I fail to understand where the segfault is taking place. Which function call is segfaulting?

**Comment by amrithathorath** [comment]
Sorry that was my bad.
It was not a segfault.
It's a constant regeneration attempt (with 1.1.1).
I can try the 128 length as you suggested.

**Comment by romen** [comment]
Hi @amrithathorath , do you have any update on this issue?

**Comment by amrithathorath** [comment]
@romen : I'm out on vacation for a couple of days. I'll update the status after Christmas.

**Comment by amrithathorath** [comment]
That suggestion (digest_len) fixed my issue.
