### ISSUE TITLE
ssl3/tls13_enc.c typo improvement

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#10675]
In the function "tls13_hkdf_expand" the declaration :
    ```
    unsigned char hkdflabel[sizeof(uint16_t) + sizeof(uint8_t) +
                            + (sizeof(label_prefix) - 1) + TLS13_MAX_LABEL_LEN
                            + 1 + EVP_MAX_MD_SIZE];
    ```
contains a typo error (the + is doubled), might be confusing.
Is it possible de fix it ?
Thanks

**Comment by mattcaswell** [comment]
Yes, this should be fixed. I'm slightly surprised this even compiles.

**Comment by mspncp** [comment]
> I'm slightly surprised this even compiles.

A binary plus operator, followed by an unary plus (sign) operator?

**Comment by qualitesys** [comment]
yes exactly unary (+) operator

**Comment by mspncp** [comment]
Nevertheless, @qualitesys feel free to submit a pr to remove the second plus, because it _is_ confusing on first sight.
