### ISSUE TITLE
[Feature Request] Add -passin argument to openssl ocsp

### ISSUE THREAD

**Issue by kaysond** [openssl/openssl#10682]
I'd like to start the openssl ocsp responder programmatically. However, when it has to ask for the password for the OCSP signing private key, I can't supply that from the shell (I believe openssl directly reads/writes from tty?). It would be great if this command supported the `-passin` argument supported by most other openssl commands.

**Comment by mattcaswell** [comment]
This would be quite easy to do if someone fancies having a go at this. E.g. see the "-passin" handling in `dgst`:

https://github.com/openssl/openssl/blob/390b18a7a2b795b085c39b380e64d0f86b3801e5/apps/dgst.c#L241-L244

Which is subsequently passed to the `load_key` call here:

https://github.com/openssl/openssl/blob/390b18a7a2b795b085c39b380e64d0f86b3801e5/apps/dgst.c#L262-L268

We just need to add some similar handling to the responder `load_key` call:

https://github.com/openssl/openssl/blob/390b18a7a2b795b085c39b380e64d0f86b3801e5/apps/ocsp.c#L584-L601

**Comment by gmorganVA** [comment]
Mind if I merge this change with 1.1.1 so it can be used sooner?

**Comment by mattcaswell** [comment]
We do not allow new features in stable branches.

**Comment by imjustd** [comment]
Any idea when this will be available?

**Comment by gmorganVA** [comment]
It is my understanding that if you want this in a release it will have to be a part of 3.0.  I found an older patch someone wrote and made it work in 1.0.2 but that series doesn't allow new features and neither does the 1.1.1 series.  This is why this ticket is closed.

**Comment by mattcaswell** [comment]
This feature is already available. It was merged via #10718 in January 2020 and was therefore released when OpenSSL 3.0 was released. It will not be backported to 1.1.1

**Comment by imjustd** [comment]
OK, I will see how to get OpenSSL v3.0 installed on my Linux. I hope it's stable as v1.1.1.
