### ISSUE TITLE
openssl: /usr/local/openssl/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl) openssl: /usr/local/openssl/lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)

### ISSUE THREAD

**Issue by ealashwali** [openssl/openssl#10697]
I use 18.04.3 LTS. When I try to check the current version of openssl using:
    ```
openssl version -v
    ```
I get this error:
    ```
openssl: /usr/local/openssl/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
openssl: /usr/local/openssl/lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
    ```

Please note that for experiment purpose, I need to maintain the old version openssl 1.1.0g and I do not want to upgrade my system to have the openssl 1.1.1.

The issue also appears when I try to run MySQL or MySQL workbench. When I try to run MySQL:
    ```
sudo mysql 
    ```
I get this error:
    ```
mysql: /usr/local/openssl/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by mysql)
    ```
When I try the workbench:
    ```
sudo mysql-workbench
    ```
I get this error:
    ```
Found /usr/lib/x86_64-linux-gnu/libproj.so.12
/usr/bin/mysql-workbench-bin: /usr/local/openssl/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/lib/mysql-workbench/libmysqlcppconn.so.7)
/usr/bin/mysql-workbench-bin: /usr/local/openssl/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/lib/mysql-workbench/libmysqlclient.so.21)
    ```

1) Can you please explain why I'm getting this? How to solve the issues in MySQL to maintain openssl 1.1.0g? 

2) Also, if I decided to upgrade to OpenSSL1.1.1 how to do this?

**Comment by romen** [comment]
Could it be that you have installed a custom version of openssl to /usr/local/openssl and then altered LD_LIBRARY_PATH or other LD env variables to give precedence to the contents of /usr/local/openssl/lib when loading dynamic libraries?

(also, as a side note unrelated to the issue you are experiencing, if I am not mistaken 18.04.3 does update the provided openssl packages to the 1.1.1 branch, and the packages that depend on them as well)

**Comment by ealashwali** [comment]
Yes. I manually installed the openssl 1.1.0g and enabled some ciphers that were not enabled with the version installed by the system using the `./config` command. I followed these steps: https://blacksaildivision.com/how-to-install-openssl-on-centos . 

What do you suggest me to do to resolve the issue to be able to run openssl, mysql, and mysql-workbench in my current system?

**Comment by ealashwali** [comment]
I hope this is still a relevant question. How can I revert the mysql and mysql-workbench to the versions where they can work with openssl 1.1.0g?

**Comment by ealashwali** [comment]
Even if I rename the two files (with prefix OLD_)that I previously created to use the custom openssl which were:
```
/etc/ld.so.conf.d/openssl-1.1.1c.conf
vi /etc/profile.d/openssl.sh
```
and then I execute:
`sudo ldconfig -v`
But I get (not: I omitted the output as it is too long, but the errors are shown here):
```
/sbin/ldconfig.real: Can't stat /usr/local/lib/i386-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/usr/local/openssl/lib:
	libssl.so.1.1 -> libssl.so.1.1
	libcrypto.so.1.1 -> libcrypto.so.1.1
/usr/lib/x86_64-linux-gnu/libfakeroot:
	libfakeroot-0.so -> libfakeroot-tcp.so
/lib/i386-linux-gnu:
	libmemusage.so -> libmemusage.so
/sbin/ldconfig.real: /lib/i386-linux-gnu/ld-2.27.so is the dynamic linker, ignoring
....
```

If I restart the device, and try to execute: openssl, or mysql, or mysql-workbench
I still get the same openssl error: ``OPENSSL_1_1_1' not found`

**Comment by romen** [comment]
I suppose the first step to resolution is to revert all the environment changes you made, so remove `/etc/ld.so.conf.d/openssl-1.1.1c.conf` and `/etc/profile.d/openssl.sh` (well move them somewhere where they are not loaded systemwide).

Doing that should ensure that any package installed from the official repositories uses the openssl version coming from the official repositories.

If you somehow fear of having overwritten the system provided openssl, check with `dpkg -l | grep -E '(libssl|openssl)` what packages you currently have installed and try to force reinstall.

Once everything is restored to the original conditions make sure to reboot to make sure no traces of the faulty env variables is left around to cause failures.

Then, for your experiment, you can limit the changes that you attempted to the shell session in which you are running the experiment.
The details will vary depending on what the experiment is about: if you are compiling some software against you custom version of openssl you will need to point the build tool of the project to the location of your custom openssl installation (and verify that both headers and dynamic libraries fed to the linker are coming from your install location).
If the build tool supports setting rpath/runpath at build time, then the binaries built using that option will carry the information about the custom openssl lib location for the loader when the binaries are being loaded.
If rpath/runpath is not an option you will need to run the binaries that should use the custom openssl in a similar fashion: `LD_LIBRARY_PATH=/usr/local/openssl/lib /path/to/experiment/foo` where `/path/to/experiment/foo` is your executable.

In general you will need to familiarize with ld (and its env variables) and rpath/runpath to customize where dynamic libraries are searched on a process to process basis.

**Comment by romen** [comment]
More details are documented here: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/NOTES.UNIX

**Comment by ealashwali** [comment]
Thanks. It worked now. But I need python to use openssl 1.1.0g instead of my system's openssl 1.1.1. Any clear steps for this please?

**Comment by romen** [comment]
I am definitely not a python expert. I am not even sure if openssl is a direct dependency of the core python library or if it is exclusively a dependency of standalone modules.

In either case I believe your best chance is in contacting either python maintainers or the maintainers of the specific python module you need to tweak to determine how to best compile the project against a custom openssl installation (and how to guarantee that bad things won't happen if two separate modules try to load two different versions of the openssl library!)

**Comment by romen** [comment]
Given your original issue is now solved, @ealashwali if you don't have further questions that could be solved here, would you close the issue?
