### ISSUE TITLE
Export the certificate chain construction functionality of `build_chain()` 

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#10696]
As recently discussed: https://github.com/openssl/openssl/pull/10587#discussion_r357966995 would be nice if there was official/public access to the certificate chain construction implemented by  `build_chain()` in `x509_vfy.c`, along with suitable documentation of the algorithm used and the options that can be set for it.

There are situations where other parts of libcrypto, as well as applications, need to construct the chain of a given certificate from a given list of candidate intermediate certificates, potentially up to some trusted certificate, which may be from a set of certificates in an optionally given trust store.

So far, the chain buildling can be achieved for instance as in `ossl_cmp_build_cert_chain()` in `crypto/cmp/cmp_util.c`, yet this function unfortunately actually does too much: by using `X509_verify_cert()`it also attempts to verify the chain because it cannot call `build_chain()` directly, which results in a waste of computational resources and also requires chopping any new error queue entries.

**Comment by nhorman** [comment]
@DDvO are you looking for something along the lines of a getter variant of X509_STORE_CTX_set0_trusted_stack?

**Comment by DDvO** [comment]
> @DDvO are you looking for something along the lines of a getter variant of X509_STORE_CTX_set0_trusted_stack?

No, but anyway good that you asked: In #14128 I provided the wanted function myself,
and forgot that that solves this issue here - so closing as completed.
