### ISSUE TITLE
test case 'asynctest' would block when build with option 'enable-asan' 

### ISSUE THREAD

**Issue by zk3326312** [openssl/openssl#10695]
I wondering whether it is a bug, I find that when build with option 'enable-asan', test case 'asynctest' would block in test_ASYNC_init_thread(), actually it block in setcontext(), so,  this phenomenon is right or a bug?

My os and kernel:
Linux 3.10.0

Openssl version:
Synchronized with the branch master

**Comment by bernd-edlinger** [comment]
seems to be a sanitizer issue.
When I compile using gcc-10 build from latest sources,
I see this:
```
$ ./asynctest 
==30076==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7ffd3a563000; bottom 0x62d000007000; size: 0x1d2d3a55c000 (32080089432064)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
callback test pass
PASS
```

**Comment by zk3326312** [comment]
thanks，i will close this issue soon
