### ISSUE TITLE
SSL_do_handshake failed and get error No share cipher

### ISSUE THREAD

**Issue by 1flurry** [openssl/openssl#10717]
Hello, everyone!
I'm having trouble establishing an ssl connection.
My client side is using openssl1.0.2 and server side is using openssl1.1.1a.
When my client side received the client hello from the server side, it did not return server hello and  reported "no shared cipher".
This is the cipher suite supported by the server:
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384；
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
This is the cipher list set by the client:
       ` #define RA_TLS_CIPHERS_LIST "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM- SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384"`
This is part of the client initialization code
```` C
    SSL_CTX *pCtx = NULL;
    SSL_METHOD *pMeth = NULL;
    SSLeay_add_ssl_algorithms();
    SSL_load_error_strings();
    ERR_load_BIO_strings();
    OpenSSL_add_all_algorithms();
#ifdef OPENSSL_VERSION_1_0_X
    pMeth = (SSL_METHOD *) TLSv1_2_server_method();
#else
    pMeth = (SSL_METHOD *) TLS_server_method();
#endif
    pCtx = SSL_CTX_new(pMeth);
    if (pCtx == NULL) {
        return NULL;
    }
    SSL_CTX_set_options(sslCtx, SSL_OP_NO_SSLv2);
    SSL_CTX_set_options(sslCtx, SSL_OP_NO_SSLv3);
    SSL_CTX_set_options(sslCtx, SSL_OP_NO_TLSv1);
    SSL_CTX_set_options(sslCtx, SSL_OP_NO_TICKET);
    SSL_CTX_set_options(sslCtx, SSL_OP_NO_COMPRESSION);
    SSL_CTX_set_session_cache_mode(sslCtx, SSL_SESS_CACHE_OFF);
    if (!SSL_CTX_set_cipher_list(sslCtx, RA_TLS_CIPHERS_LIST)) {
        return NULL;
    }
````
How can I deal with it? Thanks!

**Comment by mattcaswell** [comment]
> This is part of the client initialization code

So you are showing the *client* code, and yet:

```` C
#ifdef OPENSSL_VERSION_1_0_X
    pMeth = (SSL_METHOD *) TLSv1_2_server_method();
#else
    pMeth = (SSL_METHOD *) TLS_server_method();
#endif
````

You are using *server* methods? That is not correct!

Also, what kind of certificate are you using on your server side, and what is the ciphersuite configuration?

**Comment by 1flurry** [comment]
The ciphersuite configuration is TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384。
And the certificate I'm using on my server side is RSA certificate

**Comment by mattcaswell** [comment]
Are you able to get a wireshark trace of a failing handshake? Also the full error message (including all codes/line numbers etc) seen on the server side would be helpful
