### ISSUE TITLE
util/mknum.pl should not add duplicate entries

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#10711]
When the same function happens to be declared in more than one public header
`make ordinals` should not add them multiple times to, e.g., `util/libcrypto.num` but give an error.

**Comment by DDvO** [comment]
When the function was already in the list and a further declaration for it shows up in a public header a duplicate is added to the list even silently.

**Comment by nhorman** [comment]
@DDvO do you have an example of this occurring currently?

**Comment by DDvO** [comment]
I've just tried it out: after adding a duplicate declaration, a suitable error is thrown.
So this bug has been fixed meanwhile.
