### ISSUE TITLE
"dsa_builtin_paramgen2" support in 1.1.1

### ISSUE THREAD

**Issue by ARao0123** [openssl/openssl#10727]
I've built 2 versions of OpenSSL: 1.0.2p (with fips-2.0.16) and openssl 1.1.1.
I'm trying to test DSA PQG Verification with both versions of OpenSSL.
I see the dsa_builtin_paramgen2() function in libcrypto.so.1.0.0 (version 1.0.2p) but not in libcrypto.so.1.1 (version 1.1.1). Is there no support for it in newer OpenSSL version?
I do see the implementation in dsa_gen.c but nothing in the library generated.
Below is the output from both versions of libcrypto:

```
amritha@thorath-vm:~/ultima_latest$ nm -D /home/amritha/ssl/lib/libcrypto.so.1.0.0 | grep dsa_builtin_paramgen2
000000000019ba34 T dsa_builtin_paramgen2
00000000000971f0 T fips_dsa_builtin_paramgen2

amritha@thorath-vm:~/ultima_latest$ nm -D /home/amritha/new_openssl/ssl/lib/libcrypto.so.1.1 | grep dsa_builtin_paramgen2
amritha@thorath-vm:~/ultima_latest$

```

I would expect to see atleast 1 entry with new openSSL.

**Comment by kroeckx** [comment]
dsa_builtin_paramgen2() was never intended to be a public symbol,
it's not in any of the public headers.

**Comment by amrithathorath** [comment]
How can I achieve the functionality that's perfomed by dsa_builtin_paramgen2() if I cannot access it? Is there an alternative?

**Comment by kroeckx** [comment]
You will need to explain what you're trying to do. You're using it
to generate g again, having passed in p and q, and then check that
it's the same g you already had?

I think it should be possible to do that with the EVP_PKEY_keygen. I
think you need to call EVP_PKEY_CTX_set_dh_paramgen_type() with 2.

**Comment by amrithathorath** [comment]
I'm trying to do the following (CAVP testing)

```
[A.1.1.2 Generation of the Probable Primes p and q Using an Approved Hash Function]

[A.2.1   Unverifiable Generation of the Generator g]

[A.2.3   Verifiable Canonical Generation of the Generator g]

[A.1.1.3 Validation of the Probable Primes p and q that were Generated Using an Approved Hash Function]

[A.2.2   Assurance of the Validity of the Generator g]

[A.2.4   Validation Routine when the Canonical Generation of the Generator g Routine Was Used]
```

Ref: look at DSA vectors (PQG Gen and Ver) provided [here](https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Digital-Signatures#dsa2vs).

**Comment by lisarabe** [comment]
I'm having the same problem, trying to do CAVP testing.  Have you had any luck figuring it out?

**Comment by paulidale** [comment]
This doesn't seem relevant with the provider model and the necessity of implementing CAVS tests there.
