### ISSUE TITLE
-addext character limit?

### ISSUE THREAD

**Issue by DaVinci0072** [openssl/openssl#10728]
It would seem like the -addext parameter with "subjectAltName=" has a limited number of allowed characters.

The following exports the two subjectAltName extensions as requested.
``` 
openssl req -new -key key1.key -out req.csr -subj "/C=CA/ST=QC/L=Montreal/O=MyCompany/CN=123456789a.ca" -addext "subjectAltName=DNS:123456789a.ca, DNS:123456789a.ca"
```
However, the following does not export the two subjectAltName extensions.  Note the additional "a" on the second domain name.
``` 
openssl req -new -key key1.key -out req.csr -subj "/C=CA/ST=QC/L=Montreal/O=MyCompany/CN=123456789a.ca" -addext "subjectAltName=DNS:123456789a.ca, DNS:123456789aa.ca"
```
I'm running OpenSSL 1.1.1d 10 Sep 2019 on Windows 10 x64

**Comment by bmurray** [comment]
I am experiencing this same bug. 1.1.1 on Ubuntu and 1.1.1d on Debian. 

This works as expected:
`openssl req -new -newkey rsa:2048 -keyout Requests/email.key -out Requests/email.csr -nodes -subj "/CN=name" -addext "subjectAltName=email:me@me12345678.com"`

This clears the extensions entirely. 
`openssl req -new -newkey rsa:2048 -keyout Requests/email.key -out Requests/email.csr -nodes -subj "/CN=name" -addext "subjectAltName=email:me@me123456789.com"`

Interestingly, if I remove `req_extensions=req_ext` from my `[req]` config, it works with substantially longer values. 

`[req_ext]
subjectKeyIdentifier = hash`

**Comment by clushie** [comment]
Somehow libressl is having the same bug, someone posted a workaround for back when `-addext` feature was still missing, which thankfully is also a sufficient workaround to the max 20 character limit bug.

https://github.com/libressl/portable/issues/544#issuecomment-570051316

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
