### ISSUE TITLE
Tls 1.3 PSK Chacha20 cipher fails during handshake

### ISSUE THREAD

**Issue by tunafish24** [openssl/openssl#10735]
I'm using Openssl 1.1.1d for TLS-PSK in my application.

[https://testssl.sh/openssl-iana.mapping.html](https://testssl.sh/openssl-iana.mapping.html)

The code works fine when I use TLS_AES_256_GCM_SHA384 but when I set cipher to  TLS_CHACHA20_POLY1305_SHA256, the handshake fails. 

SSL_get_error() returns 1
ERR_print_errors() returns 
"18656:error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl\\t1_lib.c:2720:\n"

**Comment by richsalz** [comment]
Are you using OpenSSL for both client and server?

**Comment by tunafish24** [comment]
Yes. I was able to resolve the issue by explicitly specifying ciphersuites on both ends and limiting it to the one I wanted.
