### ISSUE TITLE
'make update' gets timestamps wrong?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10744]
I'm at e7b834b6bb0a32be694ebc8e614247c9af735c0f

"make update" gives these differences:
```
; g diff
diff --git a/crypto/asn1/charmap.h b/crypto/asn1/charmap.h
index e855b15977..0374b643e3 100644
--- a/crypto/asn1/charmap.h
+++ b/crypto/asn1/charmap.h
@@ -2,7 +2,7 @@
  * WARNING: do not edit!
  * Generated by crypto/asn1/charmap.pl
  *
- * Copyright 2000-2020 The OpenSSL Project Authors. All Rights Reserved.
+ * Copyright 2000-2019 The OpenSSL Project Authors. All Rights Reserved.
  *
  * Licensed under the Apache License 2.0 (the "License").  You may not use
  * this file except in compliance with the License.  You can obtain a copy
diff --git a/crypto/bn/bn_prime.h b/crypto/bn/bn_prime.h
index ef16bb43d0..e99433cda6 100644
--- a/crypto/bn/bn_prime.h
+++ b/crypto/bn/bn_prime.h
@@ -2,7 +2,7 @@
  * WARNING: do not edit!
  * Generated by crypto/bn/bn_prime.pl
  *
- * Copyright 1998-2020 The OpenSSL Project Authors. All Rights Reserved.
+ * Copyright 1998-2019 The OpenSSL Project Authors. All Rights Reserved.
  *
  * Licensed under the Apache License 2.0 (the "License").  You may not use
  * this file except in compliance with the License.  You can obtain a copy
diff --git a/crypto/conf/conf_def.h b/crypto/conf/conf_def.h
index 3fdb6a9b4a..1a3557d954 100644
--- a/crypto/conf/conf_def.h
+++ b/crypto/conf/conf_def.h
@@ -2,7 +2,7 @@
  * WARNING: do not edit!
  * Generated by crypto/conf/keysets.pl
  *
- * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
+ * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
  * Licensed under the Apache License 2.0 (the "License").  You may not use
  * this file except in compliance with the License.  You can obtain a copy
  * in the file LICENSE in the source distribution or at
;
```

This is because the year that's output depends on the mod time of the script.  See for example

https://github.com/openssl/openssl/blob/e7b834b6bb0a32be694ebc8e614247c9af735c0f/crypto/conf/keysets.pl#L60-L61

Perhaps that needs to be changed?

**Comment by mspncp** [comment]
This seems to be not the only location:

[crypto/asn1/charmap.pl:86:](https://github.com/openssl/openssl/blob/master/crypto/asn1/charmap.pl#L86) my $YEAR = [localtime([stat($0)]->[9])]->[5] + 1900;
[crypto/bn/bn_prime.pl:10:](https://github.com/openssl/openssl/blob/master/crypto/bn/bn_prime.pl#L10) my $YEAR = [localtime([stat($0)]->[9])]->[5] + 1900;
[crypto/conf/keysets.pl:61:](https://github.com/openssl/openssl/blob/master/crypto/conf/keysets.pl#L61) my $YEAR = [localtime([stat($0)]->[9])]->[5] + 1900;
[crypto/objects/obj_dat.pl:40:](https://github.com/openssl/openssl/blob/master/crypto/objects/obj_dat.pl#L40) my $YEAR = [localtime([stat($0)]->[9])]->[5] + 1900;
[crypto/objects/obj_dat.pl:41:](https://github.com/openssl/openssl/blob/master/crypto/objects/obj_dat.pl#L41) my $iYEAR = [localtime([stat($ARGV[0])]->[9])]->[5] + 1900;
[crypto/objects/objects.pl:15:](https://github.com/openssl/openssl/blob/master/crypto/objects/objects.pl#L15) my $YEAR = [localtime([stat($0)]->[9])]->[5] + 1900;
[crypto/objects/objects.pl:16:](https://github.com/openssl/openssl/blob/master/crypto/objects/objects.pl#L16) my $iYEAR = [localtime([stat($ARGV[0])]->[9])]->[5] + 1900;
[crypto/objects/objxref.pl:18:](https://github.com/openssl/openssl/blob/master/crypto/objects/objxref.pl#L18) my $YEAR = [localtime([stat($0)]->[9])]->[5] + 1900;
[crypto/objects/objxref.pl:19:](https://github.com/openssl/openssl/blob/master/crypto/objects/objxref.pl#L19) my $iYEAR = [localtime([stat($mac_file)]->[9])]->[5] + 1900;
[fuzz/mkfuzzoids.pl:12:](https://github.com/openssl/openssl/blob/master/fuzz/mkfuzzoids.pl#L12) my $YEAR = [localtime([stat($0)]->[9])]->[5] + 1900;
[fuzz/mkfuzzoids.pl:13:](https://github.com/openssl/openssl/blob/master/fuzz/mkfuzzoids.pl#L13) my $iYEAR = [localtime([stat($obj_dat_h)]->[9])]->[5] + 1900;

Seems to be also related to #10738 and #10739,   cc @mattcaswell

**Comment by slontis** [comment]
This caused me a few issues yesterday :)
