### ISSUE TITLE
OpenSSL cross compilation succeeded, but running the command OpenSSL genrsa failed to display the result?

### ISSUE THREAD

**Issue by baimengwei** [openssl/openssl#10754]
The cross compile commands I use are as follows:
    ```
    ./config no-asm shared no-async --prefix=$(pwd)/install --cross-compile-prefix=arm-linux-
    ```   
Then - m64 in the Makefile is removed, and use the following commands:
    ```   
    make
    ```   
    ```   
    make install
    ```   

I got several items:
bin  include  lib  share  ssl

after that ,
when I finished migrating, I ran the following code, only the output and cursor blinked
    ```   
    openssl genrsa
    ```   
The only output is just like this:
Generating RSA private key, 2048 bit long modulus

There's nothing else

and the only thing I can do is pressing the ctrl + C to end this situation.

Is it appropriate to remove - m64 for cross compilation?

How can I verify that OpenSSL is installed correctly?

**Comment by mattcaswell** [comment]
Do you get output from just running `openssl version`?

Why did you need to remove `-m64`?

**Comment by mspncp** [comment]
> There's nothing else

The genrsa command needs randomness. So it might be blockin on the random device or getrandom() call due to low entropy. On what device/system are your running your cross compiled program?

**Comment by mspncp** [comment]
If you have some input devices available (keyboard, mouse) try to type arbitrary keys or move the mouse around and see whether it unblocks after a while.

**Comment by baimengwei** [comment]
> Do you get output from just running openssl version?
> Why did you need to remove -m64?



> If you have some input devices available (keyboard, mouse) try to type arbitrary keys or move the mouse around and see whether it unblocks after a while.

I have solved this problem by using the following command and delete the -m32 in the Makefile. Maybe there are some problems on architecture.

`sudo setarch i386 ./config no-asm shared --prefix=/home/ty/arm/openssl --cross-compile-prefix=arm-linux-`

I can get right answer when I input : openssl genrsa
