### ISSUE TITLE
I cann't find evp_locl.h

### ISSUE THREAD

**Issue by tys1996** [openssl/openssl#10769]

**Comment by romen** [comment]
It has been renamed to `crypto/ec/ec_local.h` as part of 706457b

That being said, external applications should never include this file, as it is only for internal consumption.

**Comment by mspncp** [comment]
Note: it seems like @romen misread the filename: `evp_locl.h` was renamed to `evp_local.h`. But as he said, it's an internal header file and not meant to be included by applications.

```
 crypto/evp/{evp_locl.h => evp_local.h}
```

**Comment by romen** [comment]
Yes, sorry, too much EC work on the weekend 😅

**Comment by tys1996** [comment]
> 是的，抱歉，周末有太多EC工作

thank you

**Comment by tys1996** [comment]
> 注意：@romen似乎误读了文件名：`evp_locl.h`重命名为`evp_local.h`。但是正如他所说，这是一个内部头文件，并不意味着应用程序会包含它。
> 
> ```
>  crypto/evp/{evp_locl.h => evp_local.h}
> ```

thank you

**Comment by tys1996** [comment]
> 它已重命名`crypto/evp/evp_local.h`为[＃9333的](https://github.com/openssl/openssl/pull/9333)一部分[](https://github.com/openssl/openssl/pull/9333)
> 
> 话虽这么说，外部应用程序不应该包含此文件，因为它仅供内部使用。
> 
> _编辑：固定名称以避免混淆_

thank you

**Comment by tys1996** [comment]
> Note: it seems like @romen misread the filename: `evp_locl.h` was renamed to `evp_local.h`. But as he said, it's an internal header file and not meant to be included by applications.
> 
> ```
>  crypto/evp/{evp_locl.h => evp_local.h}
> ```

thank you

**Comment by mspncp** [comment]
You’re welcome!
