### ISSUE TITLE
How does RSA get a pem string, and then how does RSA convert a pem string to RSA

### ISSUE THREAD

**Issue by jiagushuai** [openssl/openssl#10770]

**Comment by jiagushuai** [comment]
RSA_generate_key generates an RSA key pair.RSA gets the pem string and then the pem string is converted to RSA, can the RSA algorithm type be specified, for example, sha1 sha256 SM2withSM3

**Comment by jiagushuai** [comment]
+ I'm trying to get the string in the CER format
![image](https://user-images.githubusercontent.com/29997741/71885755-f59f1680-3175-11ea-8dc0-12e46158ad67.png)

**Comment by InfoHunter** [comment]
You probably need this:
~~~
PEM_write_bio_RSAPrivateKey();

and

PEM_read_bio_PrivateKey();
EVP_PKEY_get1_RSA();
~~~
Check the doc or the `apps/rsa.c` file for detailed usage.

**Comment by jiagushuai** [comment]
> You probably need this:
> 
> ```
> PEM_write_bio_RSAPrivateKey();
> 
> and
> 
> PEM_read_bio_PrivateKey();
> EVP_PKEY_get1_RSA();
> ```
> 
> Check the doc or the `apps/rsa.c` file for detailed usage.

PEM_write_bio_RSAPrivateKey() only writes the private key, not the key pair. Does openssl not support exporting key pair strings

**Comment by richsalz** [comment]
You write it in two parts, and you read it in two parts.  The PEM separators make clear which is which, and you can put both in one file.

**Comment by levitte** [comment]
Actually, `PEM_write_bio_RSAPrivateKey` *does* write the key pair, as the OpenSSL assumption is that the private key also contains the public bits.  This is also assumed by the standards that have anything to say about the serialized form of a key, such as PKCS#1 and PKCS#8.

**Comment by InfoHunter** [comment]
Yes, the private key contains the public exponent as well

**Comment by richsalz** [comment]
But you cannot call ```PEM_read_bio_PublicKey``` on a file written as a private key, the PEM markers don't match. You have to read the private key and "pull out" the fields and create your own public key from them.

**Comment by jiagushuai** [comment]
> Yes, the private key contains the public exponent as well

Thanks for your explanation, but PEM_write_bio_RSAPrivateKey requires a password.I need to export the key pair to a string, then export the private key to RSA and set the password. Is that possible?

**Comment by levitte** [comment]
Any PEM file with a "PRIVATE KEY" key type contains a complete key pair, which is what was asked for.  But true, if you only want the public key, then you should use functions like `PEM_write_bio_RSA_PUBKEY`

**Comment by richsalz** [comment]
> Any PEM file with a "PRIVATE KEY" key type contains a complete key pair

You can't call PEM read public key on such a file.

**Comment by levitte** [comment]
> You can't call PEM read public key on such a file.

Yes, and?  That's not what is asked here, as far as I can tell.

**Comment by InfoHunter** [comment]
> but PEM_write_bio_RSAPrivateKey requires a password

The password callback should be optional

**Comment by jiagushuai** [comment]
> > but PEM_write_bio_RSAPrivateKey requires a password
> 
> The password callback should be optional

Thanks for the answer. Let me test it out

**Comment by richsalz** [comment]
Well, let's see what the original poster needs.

**Comment by jiagushuai** [comment]
+ Thank you very much for your explanation
+ As for the key pair, I am still testing and sorting, 
+ **but I would like to ask, can you generate the key according to the algorithm like sha1, sha256 SM2withSM3?Is the specified algorithm implementable**

**Comment by levitte** [comment]
sha1 and sha256 are not asymmetric key algorithms, so you can't generate keys with them alone.
Regarding SM2-with-SM3, what you're looking for is SM2 (the -with-SM3 part relates to signatures done with the key)...  SM2 is really an EC key with some tweaks, and I can't quite recall how to make those.  @InfoHunter knows that part better than I.

**Comment by richsalz** [comment]
You cannot change the algorithm that generates the key without rewriting the code.

**Comment by jiagushuai** [comment]
> You cannot change the algorithm that generates the key without rewriting the code.



> sha1 and sha256 are not asymmetric key algorithms, so you can't generate keys with them alone.
> Regarding SM2-with-SM3, what you're looking for is SM2 (the -with-SM3 part relates to signatures done with the key)... SM2 is really an EC key with some tweaks, and I can't quite recall how to make those. @InfoHunter knows that part better than I.

+ Thanks for your answer. What is the default algorithm for the key pair generated by RSA_generate_key?

**Comment by levitte** [comment]
> What is the default algorithm for the key pair generated by RSA_generate_key?

That would be RSA.  It's not a "default" algorithm, it is *the* algorithm for the key pair.

From this question, I assume that:

- you might be wondering about names like "sha256WithRSAEncryption".  That's the name of a signature method that combines the hash algorithm SHA256 with the keypair algorithm RSA.

- you're kinda new to all of this cryptography stuff, and may need to learn the fundaments.  I I'm guessing correctly, may I suggest finding a book that describes such things as keypairs, what you can do with them, and hash algorithms what those are for, and how this all combines?  Learning by bits and pieces and the very short answers we give you here is not a good way...

**Comment by jiagushuai** [comment]
> That would be RSA. It's not a "default" algorithm, it is _the_ algorithm for the key pair.
> 
> From this question, I assume that:
> 
> * you might be wondering about names like "sha256WithRSAEncryption".  That's the name of a signature method that combines the hash algorithm SHA256 with the keypair algorithm RSA.
> * you're kinda new to all of this cryptography stuff, and may need to learn the fundaments.  If I'm guessing correctly, may I suggest finding a book that describes such things as keypairs, what you can do with them, and hash algorithms what those are for, and how this all combines?  Learning by bits and pieces and the very short answers we give you here is not a good way...

+ Yes, I really don't know much.I don't know how to start.Thank you very much for your advice. I always look for information on the blog.Let me look at the basics
