### ISSUE TITLE
Can't use blibpath (for AIX) in LDFLAGS

### ISSUE THREAD

**Issue by wiggin15** [openssl/openssl#10792]
On AIX, in order to use the "blibpath" linker flag (runtime library search path), I use the environment variable LDFLAGS like this:

    LDFLAGS="-Wl,blibpath:<foo>"

OpenSSL's Configure script interprets the colon character as a list separator (according to `$list_separator_re`) and eventually converts it to a space, causing the linker to fail ("ld: 0706-015 The -b libpath option needs a parameter.") 

The generated Makefile includes a different, "wrong" LDFLAGS:

```
# cd openssl-1.1.1d
# LDFLAGS="-Wl,blibpath:/usr/lib" ./Configure aix64-gcc
# grep -R blibpath .
./Makefile:LDFLAGS= -Wl,blibpath /usr/lib
./configdata.pm:  LDFLAGS => [ "-Wl,blibpath", "/usr/lib" ],
./configdata.pm:      "LDFLAGS" => "-Wl,blibpath:/usr/lib",
```

I could not find a way to change the list separator character or "escape" the colon character without editing the code of the configure script.

**Comment by mattcaswell** [comment]
Ping @levitte

**Comment by levitte** [comment]
Hmmm, why we treat LDFLAGS as a colon separated list is beyond me. Mistake, I assume. I will get to this later today, I hope.

**Comment by levitte** [comment]
Please have a look at #10793, try the patch, and comment there if it work for you or now.
