### ISSUE TITLE
Order of sub-sections in openssl.pod needs review

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10809]
From https://github.com/openssl/openssl/pull/10132#issuecomment-573238242

The order of the OPTION subsections in openssl.pod is debatable. For example it is suprising that the 'Extended Verification Options' precede the 'Verification Options'.

This should be handled after the #10132 and #10134 are merged.

```
doc/man1/openssl.pod:496:=head1 OPTIONS
doc/man1/openssl.pod:501:=head2 Common Options
doc/man1/openssl.pod:519:=head2 Format Options
doc/man1/openssl.pod:622:=head2 Pass Phrase Options
doc/man1/openssl.pod:668:=head2 Trusted Certificate Options
doc/man1/openssl.pod:722:=head2 Random State Options
doc/man1/openssl.pod:752:=head2 Extended Verification Options
doc/man1/openssl.pod:797:=head2 Verification Options
doc/man1/openssl.pod:1037:=head2 Name Format Options
doc/man1/openssl.pod:1187:=head2 Engine Options
```

**Comment by richsalz** [comment]
Ping @ddvo who said the plan is to split openssl.pod into separate sub-pages.  He can assign appropriately.

**Comment by paulidale** [comment]
Did this get resolved with those two PRs?

**Comment by richsalz** [comment]
Since there are now for "openssl-XXX-options" pages, I am closing this.
