### ISSUE TITLE
make test test_comp is blocked

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#10812]
I run the make test command on Linux, but ../test/recipes/70-test_comp.t is blocked with this :

engine "ossltest" set.
Using default temp DH parameters
ACCEPT [::1]:63907
Server responds on [::1]:63907
unable to connect: Resource temporarily unavailable

and never ends.
Is it possible to change the test ?
Thanks for your help

The complete log (make V=1 test) (I run ubuntu on windows sub-system for Linux)

../test/recipes/70-test_comp.t .....................
Proxy started on port [::1]:63906
Server command: /mnt/c/Logiciels/maven-qcr-plugin-testsunitaires/qcr4cpp/demoopen-ssl/openssl-1.1.1-stable-SNAP-20200101/util/shlib_wrap.sh /mnt/c/Logiciels/maven-qcr-plugin-testsunitaires/qcr4cpp/demoopen-ssl/openssl-1.1.1-stable-SNAP-20200101/apps/openssl s_server -max_protocol TLSv1.3 -no_comp -rev -engine ossltest -ext_cache -accept [::1]:0 -cert /mnt/c/Logiciels/maven-qcr-plugin-testsunitaires/qcr4cpp/demoopen-ssl/openssl-1.1.1-stable-SNAP-20200101/apps/server.pem -cert2 /mnt/c/Logiciels/maven-qcr-plugin-testsunitaires/qcr4cpp/demoopen-ssl/openssl-1.1.1-stable-SNAP-20200101/apps/server.pem -naccept 1 -cipher AES128-SHA -ciphersuites TLS_AES_128_GCM_SHA256
engine "ossltest" set.
Using default temp DH parameters
ACCEPT [::1]:63907
Server responds on [::1]:63907
unable to connect: Resource temporarily unavailable

**Comment by mattcaswell** [comment]
This is a TLSProxy test. There are quite a few of these. I wonder if the others have the same problem on your system? E.g. try

````
make TESTS=test_sslversions test
````

**Comment by qualitesys** [comment]
I have the same kind of error : 

engine "ossltest" set.
Using default temp DH parameters
ACCEPT [::1]:60062
Server responds on [::1]:60062
unable to connect: Resource temporarily unavailable

**Comment by mattcaswell** [comment]
The last couple of lines of output comes from this code:

https://github.com/openssl/openssl/blob/master/util/perl/TLSProxy/Proxy.pm#L213-L308

I note that it has decided to use IPv6 - so my guess is some problem with the IPv6 connection handling in the perl scripts. Perhaps @levitte or @vdukhovni might offer some insight.

**Comment by qualitesys** [comment]
Is it possible to skip the whole 70* test set ?

**Comment by kaduk** [comment]
I had some issues with IPv6 support in perl modules when I was getting things set up on FreeBSD.  It looks like I'm using IO::Socket::INET6 rather than IO::Socket::IP.  There's a comment in util/perl/TLSProxy/Proxy.pm that gives a bit more background on how we pick what module to use for IPv6 support.  Perhaps the reporter could give a list of the installed perl modules?

**Comment by qualitesys** [comment]
Command pminst '(?i)Socket'

Result 
Socket
IO::Socket
IO::Socket::INET
IO::Socket::UNIX
IO::Socket::IP
Socket
IO::Socket
IO::Socket::INET
IO::Socket::IP
IO::Socket::UNIX

Is it ok for you ?

**Comment by mattcaswell** [comment]
> Is it possible to skip the whole 70* test set ?

Yes this is possible:

````
make TESTS=-70 test
````

You can get more fine grained control too if you prefer. See:

https://github.com/openssl/openssl/blob/6a165fab239ec5b00b3cd68169a63b509207177d/INSTALL#L1204-L1258

**Comment by kaduk** [comment]
I would suggest installing IO::Socket::INET6 and seeing if that changes anything.

**Comment by qualitesys** [comment]
The root cause of these failures was an active AntiVirus (Avast) on my Windows machine. One deactivated everything seams fine.
May be it could be nice to add a timeout on the client connection process.
Thanks for your help !
