### ISSUE TITLE
ssl3_get_server_certificate has memory leak

### ISSUE THREAD

**Issue by ramahmoo** [openssl/openssl#1082]
I am using openssl 1.0.2-h versions in client server application, during my application exist i wrote any memory leak in a file using **CRYPTO_mem_leaks_fp**. All the time i see X509 stack in leak dump file, after backtracing the origin, found that stack memory was allocated in **ssl3_get_server_certificate** in **s3_clnt.c**. looked at source of the file and found **sk_X509_pop_free(sk, X509_free);** is being called at end of the ssl3_get_server_certificate function but problem is the **sk object was set to NULL** prior to sk_X509_pop_free call.

This seems to me a memory leak. Please confirm this.

**Comment by mattcaswell** [comment]
No, the code looks correct to me. `sk` is set to NULL only after the stack it points to is stored in the `SESS_CERT`. This will get freed later.

**Comment by cxxrocks** [comment]
@ramahmoo maybe [this](http://openssl.6102.n7.nabble.com/Memory-leak-in-ssl3-get-server-certificate-td49103.html) could help
