### ISSUE TITLE
Let's not have ex_data within the FIPS provider module

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#10835]
Recent changes in `crypto/dsa/` showed some key creating functions that take an `OPENSSL_CTX` as argument...  for the sole reason of supporting `ex_data` in the DSA structure.  Interestingly enough, the functions to get or set ex_data are not included in the compilation of the FIPS module, making that DSA field useless.

I would like to suggest that `ex_data` fields in diverse structures (such as low level key-pairs) are simply unsupported.  They exist purely for the sake of the application, which will never reach that deeply into the entrails of any provider, making `ex_data` support of that sort pretty moot.

**Note** There are still `CRYPTO_EX_DATA` items that need to remain supported, as the whole `OPENSSL_CTX` construct relies on that.  That's not what I'm talking about here.

**Comment by richsalz** [comment]
See also issue #8863 that I opened back in May.
