### ISSUE TITLE
Invalid relocations when linking a static libcrypto to a shared object on Android armv8

### ISSUE THREAD

**Issue by sztomi** [openssl/openssl#10842]
When building openssl for Android-armv8 in a static configuration, then linking this library to a .so (with lld), we get **two** kinds of relocation errors which are related to the asm modules. Below, I'll describe each error with outputs and the results of my investigation. A patch that fixes both issues will be attached. 

### First kind: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P

Linker output:

```
ld.lld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a(armcap.o)
>>> referenced by chacha-armv8.o:(.text+0x20) in archive ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a

ld.lld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a(armcap.o)
>>> referenced by poly1305-armv8.o:(.text+0x9A0) in archive ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a

ld.lld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a(armcap.o)
>>> referenced by sha1-armv8.o:(.text+0x1240) in archive ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a

ld.lld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a(armcap.o)
>>> referenced by sha256-armv8.o:(.text+0xF88) in archive ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a

ld.lld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a(armcap.o)
>>> referenced by sha512-armv8.o:(.text+0x1108) in archive ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a
```

This exact error was reported to the llvm bug tracker, but rejected as invalid: https://bugs.llvm.org/show_bug.cgi?id=32518

The recommendation of declaring the symbol as `.hidden` in each module works and so far doesn't seem to have ill effects. I don't know enough about relocations to confirm or deny the statements in the llvm bug tracker, but it does sound convincing.

As a side note, the same symbol has been already `.hidden` in `armv4cpuid.pl` for a long time.

### Second kind: relocation R_AARCH64_ADR_PREL_LO21 cannot be used against symbol poly1305_blocks

This error only appeared after fixing the first one. Linker output:

```
ld.lld: error: relocation R_AARCH64_ADR_PREL_LO21 cannot be used against symbol poly1305_blocks; recompile with -fPIC
>>> defined in ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a(poly1305-armv8.o)
>>> referenced by poly1305-armv8.o:(poly1305_init) in archive ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a

ld.lld: error: relocation R_AARCH64_ADR_PREL_LO21 cannot be used against symbol poly1305_emit; recompile with -fPIC
>>> defined in ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a(poly1305-armv8.o)
>>> referenced by poly1305-armv8.o:(poly1305_init) in archive ../conan/.conan/data/openssl/1.1.1d-1/tamas/openssl_upgrade2/package/ce6abafda4ebbdbdea95402815ce90c422f5c35a/lib/libcrypto.a
```

As you can see, this is a different relocation and it's also not possible to simply hide the symbols. Luckily, there was again an existing fix in the armv4 implementation:

https://mta.openssl.org/pipermail/openssl-commits/2018-April/019051.html

I basically ported the same solution to the armv8 version (`crypto/poly1305/asm/poly1305-armv8.pl`). In a nutshell: I created local labels at the same locations as the global symbols; and referenced those in the branch instructions instead of the global symbols. This removed the need for the dynamic relocations. Credits to the original author of that patch for armv4, Andy Polyakov. Applying this fix removed the relocation errors.

### Attachments

Config data, as requested in the template: [openssl_configdata.txt](https://github.com/openssl/openssl/files/4059730/openssl_configdata.txt)

Patch containing the above fixes: [android_aarch64_relocations_fix.patch.txt](https://github.com/openssl/openssl/files/4059880/android_aarch64_relocations_fix.patch.txt) - If there is interest, I'm happy to open a PR with this patch. 

Lastly, I don't think this is strictly related, but we have a patch against the configure script to consume the environment more directly instead of detecting stuff: [android_use_env.patch.txt](https://github.com/openssl/openssl/files/4059734/android_use_env.patch.txt) - we have a custom toolchain and the heuristics don't really work.

**Comment by SalusaSecondus** [comment]
Hi, has any progress been made on this issue? I bumped into the problem independently today myself.

**Comment by sztomi** [comment]
@SalusaSecondus I've not seen any communication from the authors regarding this, I'm not sure it was noticed. I'm not familiar with the openssl devs communication channels, but if this affects you and want if fixed in upstream, maybe try contacting them via their mailing list. It does seem like the issue tracker is in use by the devs, but obviously very high traffic. So it's understandable that some issues go unnoticed here.

**Comment by SalusaSecondus** [comment]
@sztomi, I'm starting to reach out through various back-channels to get attention on this.

IANAOD (I Am Not An Openssl Dev), but if you were to cut a PR for this change it might make things easier for me. That gets the change in through the standard process AND helps ensure the licensing (and CLA) is in order.

**Comment by scottarc** [comment]
> If there is interest, I'm happy to open a PR with this patch.

The patch is rather digestible. I'd say, "Open a pull request."

**Comment by kaduk** [comment]
> I'm not sure it was noticed

I think the key is that it needs to be noticed by someone who has andorid dev knowledge, which excludes a lot of us, including me.  Opening a PR, as suggested above, seems like the right next step.

**Comment by SalusaSecondus** [comment]
This issue applies to non-Android aarch64 platforms as well. Anyone with ARM knowledge may be sufficient.

**Comment by sztomi** [comment]
Alright, I'll open a pull request with the changes.

**Comment by SalusaSecondus** [comment]
@sztomi , any chance of getting the PR in? This is really important to some of my projects.

**Comment by sztomi** [comment]
Yep, sorry, I got pulled away for other stuff. I'm making it now. It might still take time to get into openssl, so if you are blocked on this I still suggest applying the patch locally. Are you concerned about licensing stuff regarding this patch?

**Comment by sztomi** [comment]
@SalusaSecondus PR above ^  I only applied the first half of my patch because the other half was already implemented on master (in a very similar manner).

**Comment by SalusaSecondus** [comment]
@sztomi, Yeah. By getting it in as PR I don't think I'll need to wrangle with lawyers over licensing. I expect to be cherry-picking it :-)  Though I might need to pull in the older version of your patch as 1.1.1f doesn't have the poly1305 fix yet. Can you clarify the licensing around the patch you link from this issue?

**Comment by sztomi** [comment]
@SalusaSecondus happy to release it with whatever license helps you get around such restrictions. By default, I usually release my stuff with the MIT license, so let's say it's that. Feel free to contact me via email if you need a different one, or a written permission or something (you can find my address in my fork in the commit I made). Corporations :man_facepalming:

**Comment by mattsplats** [comment]
This error no longer seems to appear on `master` when building on aarch64 with static linking.

**Comment by Romain-Geissler-1A** [comment]
> This error no longer seems to appear on master when building on aarch64 with static linking.

On my side I am still having issues. See the errors I have, and a proposed pull request which seems to work for me in #13056.

**Comment by Romain-Geissler-1A** [comment]
Hi,

This should be fixed on both branch 1.1.1 (and incoming release 1.1.1i) and master now.

**Comment by link2xt** [comment]
1.1.1i is released, shouldn't this bug be closed?

Similar problem is fixed by updating to 1.1.1i in this case: https://github.com/deltachat/deltachat-core-rust/issues/2120

**Comment by mattcaswell** [comment]
Closing this. Fixed by #13056 and #13218.

**Comment by kroeckx** [comment]
As far as I know, Ubuntu uses 1.1.1f. I assume the
/usr/lib/aarch64-linux-gnu/libcrypto.a file is the one shipped by
Ubuntu.

**Comment by rodmaz** [comment]
What is the risk/impact pointing `/usr/lib/aarch64-linux-gnu/libcrypto.a` instead to a newer `libcrypto.a` from OpenSSL 1.1.1i? Is 
That was the only way I could successfully link the forementioned module (`aws-crt-nodejs`).
