### ISSUE TITLE
BIO_f_buffer() wants to read more from a blocking socket than is available

### ISSUE THREAD

**Issue by Quuxplusone** [openssl/openssl#10859]
```
cat > trivial-server.c <<EOF
#include <assert.h>
#include <openssl/bio.h>
#include <stdio.h>

int main()
{
    BIO *accept_bio = BIO_new_accept("8080");
    assert(accept_bio != NULL);
    int err = BIO_do_accept(accept_bio);
    assert(err == 1);

    err = BIO_do_accept(accept_bio);
    assert(err == 1);
    BIO *bio = BIO_pop(accept_bio);
    assert(bio != NULL);

#if DEMONSTRATE_FAILURE
    BIO *bbio = BIO_new(BIO_f_buffer());
    BIO_push(bbio, bio);
    bio = bbio;
    assert(bio != NULL);
#endif
    char buffer[1024];
    int nbytes = BIO_read(bio, buffer, 1024);
    printf("%.*s\n", nbytes, buffer);
    BIO_write(bio, "world", 5);
    BIO_flush(bio);
}
EOF
cat >trivial-client.c <<EOF
#include <assert.h>
#include <openssl/bio.h>
#include <stdio.h>

int main()
{
    BIO *bio = BIO_new_connect("localhost:8080");
    assert(bio != NULL);
    int err = BIO_do_connect(bio);
    assert(err == 1);
    BIO_write(bio, "hello", 5);
    BIO_flush(bio);
    char buffer[1024];
    int nbytes = BIO_read(bio, buffer, 1024);
    printf("%.*s\n", nbytes, buffer);
}
EOF
gcc -lcrypto trivial-server.c -o trivial-server -DDEMONSTRATE_FAILURE
gcc -lcrypto trivial-client.c -o trivial-client
./trivial-server &
./trivial-client
```

When compiled with `-DDEMONSTRATE_FAILURE`, the server chains a `BIO_f_buffer` in front of the BIO that reads from the socket. This means that the server's `BIO_read(bio, buffer, 1024)` attempts to read 1024 bytes — succeeds at reading 5 bytes — _attempts to read 1024 more bytes_ — and hangs forever, because the client is done sending data and is waiting for the server to process the data it's already got.

This means that it is _still_ unsafe to use a `BIO_f_buffer` downstream of a `BIO_new_ssl`, even after the bugfix in #322. Bug #322 was about how the SSL BIO broke the contract of the buffer BIO while writing; this new bug is about how the buffer BIO breaks the contract of the SSL BIO while reading.

I think a buffer BIO should never attempt to read any additional data into its buffer unless either (A) its buffer was actually empty on entry into `buffer_read`, or (B) it has gotten a positive value from `BIO_pending(BIO_next(self))`.

**Comment by Quuxplusone** [comment]
> That would defeat the purpose of this filter...

Can you elaborate on this comment? My understanding of `BIO_f_buffer` (gleaned from the extremely sparse documentation) is that it's just supposed to maintain a buffer so that it can attempt larger reads than the user requested, or larger writes than the user demanded. For example, if the user says "Please read the next (up to) 1024 bytes," the buffer BIO might instead read the next (up to) _4096_ bytes, and if it happens to read more than 1024, it can buffer the rest for later. That is, the purpose of a buffer BIO should be to satisfy 2+ user-level read requests via a single lower-level read. This is an optimization.

However, what I observe happening in `trivial-server.c` is that the buffer BIO is instead reading the next (up to) 4096 bytes [it happens to receive 5 bytes from the socket] and then *again* reading (up to) 4096 bytes, which blocks forever. That is, the buffer is turning 1 user-level read request into 2 lower-level reads. That's a pessimization _and_ a blocking-forever-bug.

**Comment by levitte** [comment]
Something I just noticed, BTW, is that neither side is shutting down the communication. How does the receiving end know that 5 chars is all it's going to get?

**Comment by levitte** [comment]
I just ran your test program and can confirm what you say...  it does look to try and fill the 1024 bytes you asked for.  Maybe that's the conceptual idea that you don't agree with.

**Comment by Quuxplusone** [comment]
You can see the sequence of `BIO_read` calls by inserting "eavesdrop BIOs" in the chain, like this:
```
cat >trivial-server.c <<EOF
#include <assert.h>
#include <openssl/bio.h>
#include <stdio.h>

static int eavesdrop_read(BIO *bio, char *data, int len) {
    const char *name = (const char *)BIO_get_data(bio);
    printf("%s: asked to read (up to) %d bytes\n", name, len);
    int nbytes = BIO_read(BIO_next(bio), data, len);
    printf("%s: read %d (of %d) bytes\n", name, nbytes, len);
    return nbytes;
}
static int eavesdrop_write(BIO *bio, const char *data, int len) {
    const char *name = (const char *)BIO_get_data(bio);
    printf("%s: asked to write %d bytes\n", name, len);
    int nbytes = BIO_write(BIO_next(bio), data, len);
    printf("%s: wrote %d (of %d) bytes\n", name, nbytes, len);
    return nbytes;
}
BIO *eavesdrop(const char *name)
{
    BIO_METHOD *m = BIO_meth_new(BIO_TYPE_FILTER, "eavesdrop");
    BIO_meth_set_read(m, eavesdrop_read);
    BIO_meth_set_write(m, eavesdrop_write);
    BIO *bio = BIO_new(m);
    BIO_set_data(bio, (void *)name);
    BIO_set_init(bio, 1);
    return bio;
}

int main()
{
    BIO *accept_bio = BIO_new_accept("8080");
    assert(accept_bio != NULL);
    int err = BIO_do_accept(accept_bio);
    assert(err == 1);

    err = BIO_do_accept(accept_bio);
    assert(err == 1);
    BIO *bio = BIO_pop(accept_bio);
    assert(bio != NULL);

    bio = BIO_push(eavesdrop("LO"), bio);
#if DEMONSTRATE_FAILURE
    bio = BIO_push(BIO_new(BIO_f_buffer()), bio);
#endif
    bio = BIO_push(eavesdrop("HI"), bio);

    char buffer[1024];
    int nbytes = BIO_read(bio, buffer, 1024);
    printf("%.*s\n", nbytes, buffer);
    BIO_write(bio, "world", 5);
    BIO_flush(bio);
}
EOF
```
If you compile without `-DDEMONSTRATE_FAILURE`, `trivial-server` prints:
```
HI: asked to read (up to) 1024 bytes
LO: asked to read (up to) 1024 bytes
LO: read 5 (of 1024) bytes
HI: read 5 (of 1024) bytes
hello
HI: asked to write 5 bytes
LO: asked to write 5 bytes
LO: wrote 5 (of 5) bytes
HI: wrote 5 (of 5) bytes
```
If you compile with `-DDEMONSTRATE_FAILURE`, `trivial-server` hangs after printing:
```
HI: asked to read (up to) 1024 bytes
LO: asked to read (up to) 4096 bytes
LO: read 5 (of 4096) bytes
LO: asked to read (up to) 4096 bytes
```

The buffer BIO is _not_ "trying to fill the 1024 bytes you asked for." It reads 5 bytes and then asks for 4096 more — a total of 5001 bytes. That's much more than "the 1024 you asked for." Even if the high-level side knows _exactly_ how many bytes it expects, and issues a read for _exactly_ the right size, a chain of buffer BIOs will mess it up.

Change `trivial-server.c` to set up these BIOs and to issue a read of size 5 exactly:
```
    bio = BIO_push(eavesdrop("LO"), bio);
#if DEMONSTRATE_FAILURE
    bio = BIO_push(BIO_new(BIO_f_buffer()), bio);
    bio = BIO_push(eavesdrop("ME"), bio);
    bio = BIO_push(BIO_new(BIO_f_buffer()), bio);
#endif
    bio = BIO_push(eavesdrop("HI"), bio);

    char buffer[1024];
    int nbytes = BIO_read(bio, buffer, 5);
    printf("%.*s\n", nbytes, buffer);
    BIO_write(bio, "world", 5);
    BIO_flush(bio);
```
It hangs after printing:
```
HI: asked to read (up to) 5 bytes
ME: asked to read (up to) 4096 bytes
LO: asked to read (up to) 4096 bytes
LO: read 5 (of 4096) bytes
LO: asked to read (up to) 4096 bytes
```
This indicates that it is inherently impossible to use a buffer BIO in the middle of a BIO chain.

> How does the receiving end know that 5 chars is all it's going to get?

In general, the receiving end can't know how much it's going to get except via the application-level protocol. For example, in HTTP 1.1, when reading headers, the receiving end should issue reads until it sees `\r\n\r\n` in the data it's received so far.  In TLS, I don't know the exact protocol, but using an "eavesdrop BIO" we can observe the receiving end issuing many exact-sized small reads — 5 bytes, 70 bytes... — interspersed with small writes. If a buffer BIO further down the chain turns any single blocking read request into _multiple_ blocking read requests, then both HTTP and TLS will hang forever.

**Comment by levitte** [comment]
That the buffer filter tries to read 4096 bytes internally doesn't really matter, because ultimately, it gets what it gets (such as 5 bytes).  However, the way it's currently implemented, it does everything it can to try and fill the size that the caller asked for (1024 bytes in your case), so if one read didn't fill that up, it tries again until it is.

I think the "fix" to change this behaviour is:

``` C
diff --git a/crypto/bio/bf_buff.c b/crypto/bio/bf_buff.c
index 80db0b57ab..7e291ac895 100644
--- a/crypto/bio/bf_buff.c
+++ b/crypto/bio/bf_buff.c
@@ -109,35 +109,19 @@ static int buffer_read(BIO *b, char *out, int outl)
         memcpy(out, &(ctx->ibuf[ctx->ibuf_off]), i);
         ctx->ibuf_off += i;
         ctx->ibuf_len -= i;
-        num += i;
-        if (outl == i)
-            return num;
-        outl -= i;
-        out += i;
+        return i;
     }
 
     /*
-     * We may have done a partial read. try to do more. We have nothing in
-     * the buffer. If we get an error and have read some data, just return it
-     * and let them retry to get the error again. copy direct to parent
-     * address space
+     * The buffer was empty, so let's read downstream.  If the desired output
+     * size is larger than our internal buffer, we don't even try to buffer.
      */
     if (outl > ctx->ibuf_size) {
-        for (;;) {
-            i = BIO_read(b->next_bio, out, outl);
-            if (i <= 0) {
-                BIO_copy_next_retry(b);
-                if (i < 0)
-                    return ((num > 0) ? num : i);
-                if (i == 0)
-                    return num;
-            }
-            num += i;
-            if (outl == i)
-                return num;
-            out += i;
-            outl -= i;
+        i = BIO_read(b->next_bio, out, outl);
+        if (i <= 0) {
+            BIO_copy_next_retry(b);
         }
+        return i;
     }
     /* else */
 
@@ -145,10 +129,7 @@ static int buffer_read(BIO *b, char *out, int outl)
     i = BIO_read(b->next_bio, ctx->ibuf, ctx->ibuf_size);
     if (i <= 0) {
         BIO_copy_next_retry(b);
-        if (i < 0)
-            return ((num > 0) ? num : i);
-        if (i == 0)
-            return num;
+        return i;
     }
     ctx->ibuf_off = 0;
     ctx->ibuf_len = i;
```

Does this seem about right to you?

**Comment by Quuxplusone** [comment]
> Does this [patch] seem about right to you?

Modulo that I'm totally not qualified to review this code ;) yes, it looks like that patch is adding a more obvious `return` directly after each `BIO_read(b->next_bio, ...)`, so it looks like an improvement.

> the way it's currently implemented, it does everything it can to try and fill the size that the caller asked for (1024 bytes in your case)

But buffer BIOs in the middle of a chain can screw up even a "read of size 5 exactly" (Ctrl+F for this text in my comment above). Also notice that no buffer BIO in this entire thread has ever issued a read of size 1024. So the current behavior is _not_ trying to fill "the size the caller asked for (1024 bytes in your case)." It _never_ tries to read 1024 bytes. It tries to read 5001 bytes.

**Comment by levitte** [comment]
[sigh] 5001 is a red herring...  it tries to fill its internal buffer with the 4096 byte read, *but it doesn't necessarily get that many*.  It does this until it has gotten all `outl` bytes.  So for example, if the client was repeatedly sending 5 bytes in 2 second interval, you would see a 4096 read attempt result in 5 more bytes every 2 seconds on the server, exactly 205 times (because 5 × 205 = 1025), then it would stop, because it has fulfilled the 1024 bytes asked from the caller (i.e. the `BIO_read(bio, buffer, 1024)` call)

As for the attempt to have trivial-server read only 5 bytes instead of 1024, I didn't have your issue, that went smoothly:

```
HI: asked to read (up to) 5 bytes
LO: asked to read (up to) 4096 bytes
LO: read 5 (of 4096) bytes
HI: read 5 (of 5) bytes
hello
HI: asked to write 5 bytes
HI: wrote 5 (of 5) bytes
```

**Comment by levitte** [comment]
I have submitted the change in #10876. Note that I'm not proposing to backport it to the 1.1.1 branch, because it is a behaviour change, and it is unclear what the actual expectations are, i.e. should it or should it not try to desperately fill all `outl` bytes.

**Comment by Quuxplusone** [comment]
> As for the attempt to have trivial-server read only 5 bytes instead of 1024, I didn't have your issue

Looks like you forgot to cut-and-paste some of the changed lines. Namely, you must have forgotten to cut-and-paste at least this one line...

    bio = BIO_push(eavesdrop("ME"), bio);

...because your cut-and-pasted output doesn't contain any instances of "ME". (Or else you forgot to re-compile the code, or save the file, or something along those lines.)

Could you please test that example again, using your new patch, and verify that the patch fixes it?

Also, does OpenSSL have anything along the lines of a test suite? Would it make sense to add tests for any of this behavior? The commit that fixed #322 didn't add any tests either.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> That the buffer filter tries to read 4096 bytes internally doesn't really matter, because ultimately, it gets what it gets (such as 5 bytes).  However, the way it's currently implemented, it does everything it can to try and fill the size that the caller asked for (1024 bytes in your case), so if one read didn't fill that up, it tries again until it is.
>
> I think the "fix" to change this behaviour is:
> [SNIP ]

 From manual page BIO_f_buffer(3) is not clear what is expected behavior 
on read.
On write is documented : buffer is fill or on flush.

So what to expect - to read from next BIO only if buffer is empty (java 
style)?

Roumen

**Comment by levitte** [comment]
From hearing @t-j-h, the purpose with `BIO_f_buffer` actually *is* to insist on getting all `outl` bytes before returning.  In other words, for `BIO_f_buffer` to be useful with that in mind, a call with an arbitrary size such as 1024 is misuse.

With that purpose in mind, one might argue that `BIO_f_buffer` is poorly named, because `setbuf()` and how all that works.

Another solution is for this issue is simply to document it better.

**Comment by Quuxplusone** [comment]
@petrovr wrote:
> So what to expect - to read from next BIO only if buffer is empty (java style)?

Yes, even with the old code, we write to the next BIO only when the buffer is full, and we read from the next BIO only when the buffer is empty. This is "buffering" as I see and understand it.
The point of contention is "what should the BIO do when the user says `BIO_read(bio, buffer, 1024)` and there are only 5 bytes available _at all_" — should it give back those 5 bytes, or hang forever? Every other kind of BIO that I've used (SSL BIO, file BIO, raw socket BIO) will give back those 5 bytes. The buffer BIO is the only one that currently hangs forever.

**Comment by levitte** [comment]
"hang forever" is really "hang until the other end shuts down the communication", to be precise

**Comment by levitte** [comment]
BTW, I'm not sure i understand why you guys keep talking about "java style".  The stdio buffer works that way too if I understand correctly, i.e. it buffers what it gets internally, but doesn't necessarily block just because it has fewer bytes than what the caller asked for.
