### ISSUE TITLE
.Configure with env CFLAGS yields invalid CFLAGS from configuration

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#10868]
When I configure with already present CFLAGS in the env because I want to add more, then openssl's config does not add to them, but takes them as gospel and then discards what it wanted to add such as -O3

```
$ ./Configure no-shared --prefix=/usr linux-x86_64
Configuring OpenSSL version 1.1.1d (0x1010104fL) for linux-x86_64
$ grep "^CFLAGS=" Makefile 
CFLAGS=-Wall -O3

$ CFLAGS="-blah" ./Configure no-shared --prefix=/usr linux-x86_64
Configuring OpenSSL version 1.1.1d (0x1010104fL) for linux-x86_64
$ grep "^CFLAGS=" Makefile 
CFLAGS=-blah
```

I would have expected -blah -Wall -O3 instead

The same issue happens with every other variable in the builds

Seems like toplevel picker like in linux-generic32 should be made adds instead or something like to retain environment defines.

**Comment by levitte** [comment]
This was actually a deliberate choice that we made a few years ago, when implementing this.  Basically, we have certain defaults (such as `-Wall -O3`) in our config database, which can be overridden by the user.

Now, here's a trick; if you want to do what you talk about, have your choice of C flags *added*, rather than as an override, you can just give it as a configuration argument.  Like this:

``` console
$ ./Configure  no-shared --prefix=/usr -blah linux-x86_64
...
$ grep ^CFLAGS Makefile
CFLAGS=-Wall -O3 -blah
```

**Comment by dlegaultbbry** [comment]
Where can I change the default behaviour in Configure to override this? I'm fine with maintaining my own local changes for this. Reason is that this affects everything from CFLAGS, CPPFLAGS, LDFLAGS, etc. which I need to pass on various options from the env.

Thanks

**Comment by levitte** [comment]
Er...  that's not an easy task.

FYI, if you build anything that uses GNU auto-tools (autoconf, automake, all that) as well, you'll probably run into the exact same issue with them.

One way `could` be this:

``` console
$ env -i PATH=$PATH ./Configure no-shared --prefix=/usr linux-x86_64 $CFLAGS $CPPFLAGS $LDFLAGS ...
```

**NOTE** *I have not tested this.*  Do note that you will probably want to set a few more environment variables after `env -i`; PATH is only one of the basic basics.

**Comment by dlegaultbbry** [comment]
I got what I wanted by simply moving the grabbing of the env from %user to %useradd and then everything starts working fine and all options are accounted for in each area.

```
my %useradd = (
    CPPDEFINES  => [],
    CPPINCLUDES => [],
    CPPFLAGS    => [ env('CPPFLAGS') || () ],
    CFLAGS      => [ env('CFLAGS') || () ],
    CXXFLAGS    => [ env('CXXFLAGS') || () ],
    LDFLAGS     => [ env('LDFLAGS') || () ],
    LDLIBS      => [],
    RCFLAGS     => [],
   );
```

**Comment by levitte** [comment]
Hah!  Yeah, that works.

Are you satisfied enough to close this?

**Comment by dlegaultbbry** [comment]
Yes, thanks for the help!
