### ISSUE TITLE
SSL_get_peer_cert_chain difference between client and server

### ISSUE THREAD

**Issue by ironyman** [openssl/openssl#10871]
https://www.openssl.org/docs/man1.1.0/man3/SSL_get_peer_cert_chain.html

> SSL_get_peer_cert_chain() returns a pointer to STACK_OF(X509) certificates forming the certificate chain sent by the peer. If called on the client side, the stack also contains the peer's certificate; if called on the server side, the peer's certificate must be obtained separately using SSL_get_peer_certificate(3). If the peer did not present a certificate, NULL is returned.

Why is the behavior different for client and server?

**Comment by t8m** [comment]
I'd say for historical reasons. We cannot change API contract of existing functions.
