### ISSUE TITLE
SSL_read non-blocking socket SSL_ERROR_WANT_WRITE clarification

### ISSUE THREAD

**Issue by z-s-e** [openssl/openssl#10888]
The documentation of SSL_read states:
> In this case a call to SSL_get_error(3) with the return value of the read function will yield SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE. [...] When using a non-blocking socket, nothing is to be done, [...]

However, if there has been a call to SSL_write previously, which also did not fully complete (e.g. also returned SSL_ERROR_WANT_WRITE), I would think that a SSL_ERROR_WANT_WRITE error of SSL_read indicates that the previous SSL_write should be retried (instead of "nothing is to be done"). Is this not correct?

Thanks

**Comment by kroeckx** [comment]
Like SSL_get_error explains:
SSL_ERROR_WANT_WRITE is returned when the last operation was a write
to a non-blocking BIO and it was unable to sent all data to the BIO.
When the BIO is writeable again, the same function can be called
again.

That is if SSL_read() returns SSL_ERROR_WANT_WRITE, it's trying to
write something before it can make progress, and you need to wait
until the BIO is ready to accept more data. Then you can call
SSL_read() (or SSL_write()) again.

**Comment by z-s-e** [comment]
Yes, I have understood this so far. Maybe I haven't made myself clear, so let me reformulate. Consider the following pseudo-code:
```
SSL_write(my_buffer); // assume this fails with SSL_ERROR_WANT_WRITE
while(true) {
  if (SSL_read(other_buffer) <= 0 && SSL_get_error(..) == SSL_ERROR_WANT_WRITE) {
    poll(fd, POLLOUT);
    continue;
  }
  // ...
}
```

I am wondering if this could deadlock, because SSL_write might have written a partial record, and since SSL_write is not retried in the loop, SSL_read cannot continue even if the underlying socket is writable again. If this is true, then the documentation should probably say that pending writes need to be retried for SSL_read being able to continue.

**Comment by t8m** [comment]
If the SSL_write() fails with SSL_ERROR_WANT_WRITE you should wait for the BIO is able to accept more data to write and redo the SSL_write() call and not do SSL_read() in between.
