### ISSUE TITLE
ssh-keygen -m PEM & -t rsa features not working in OpenSSH 8.1/8.1p1 (2019-10-09)

### ISSUE THREAD

**Issue by vic-mer** [openssl/openssl#10886]
The previous version of ssh-keygen -t rsa still had the 
 -----BEGIN RSA PRIVATE KEY-----   
-----END RSA PRIVATE KEY-----   
but the OpenSSH 8.1/8.1p1 (2019-10-09) release removed the "RSA" out of these titles.  I've tried every conversion/creation method I could find including your documented:

-m key_format    Specify a key format for key generation, the -i(import), -e (export) conversion options, and the -p change passphrase operation. The latter may be used to convert between OpenSSH private key and PEM private key formats.The supported key formats are: “RFC4716” (RFC 4716/SSH2 public or private key), “PKCS8” (PKCS8 public or private key) or “PEM” (PEM public key). By default OpenSSH will write newly-generated private keys in its own format, but when converting public keys for export the default format is “RFC4716”. Setting a format of “PEM” when generating or updating a supported private key type will cause the key to be stored in the legacy PEM private key format.

However, none of them are working in OpenSSH 8.1/8.1p1 (2019-10-09).  I know the legacy PEM private key format is not as secure, but it is still needed and used.

**Comment by levitte** [comment]
We are OpenSS*L*, not OpenSSH.
