### ISSUE TITLE
getting basic constraints with new opaque api provided with v1.1.0

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1089]
I was using openssl version 1.0.2 and there it was possible to use 
```
x509->ex_pathlen 
```
as part of the basic constraints. 

Where can I find the access to this value in the new opaque api?

**Comment by richsalz** [comment]
we need to add an API for this in 1.1

**Comment by richsalz** [comment]
```long X509_get_pathlen(const X509 *x)```

**Comment by richsalz** [comment]
fixed in commit e417070c9f2162594e8289aed93bd5801e70e60d

**Comment by ekasper** [comment]
Reopening because I think we should try to avoid `long` in new public APIs. It's meaningless. Use int or an explicitly sized type.

**Comment by richsalz** [comment]
Closing this, see #1195
