### ISSUE TITLE
Intel CET support is incomplete

### ISSUE THREAD

**Issue by hjl-tools** [openssl/openssl#10896]
commit b2b43d1b698235ee674e588c224db38d9b78d1ea
Author: Richard Levitte <levitte@openssl.org>
Date:   Fri Jan 17 08:29:28 2020 +0100

    Add GNU properties note for Intel CET in x86_64-xlate.pl

has 2 issues.   Intel CET has 2 parts, shadow stack (SHSTK) and indirect branch tracking
(IBT).  Openssl is SHSTK compatible.  But ENDBR is needed at indirect branch targets for IBT.

1,  We need to mark SHSTK and IBT compatibility in GNU properties note for every object file,
not just those with ENDBR.   You can verify it on Fedora 31 with

$ CC="gcc -Wl,-z,cet-report=error" ./Configure shared linux-x86_64 -fcf-protection
$ make
$ make test

If you linker doesn't support

  -z cet-report=[none|warning|error] (default: none)

you need to install GNU binutils 2.33.  I got

/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aes-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aesni-mb-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aesni-sha1-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aesni-sha256-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aesni-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-bsaes-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-vpaes-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/bn/libcrypto-shlib-rsaz-avx2.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/bn/libcrypto-shlib-rsaz-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/bn/libcrypto-shlib-x86_64-gf2m.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/bn/libcrypto-shlib-x86_64-mont.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/bn/libcrypto-shlib-x86_64-mont5.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/camellia/libcrypto-shlib-cmll-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/chacha/libcrypto-shlib-chacha-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/ec/libcrypto-shlib-ecp_nistz256-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/ec/libcrypto-shlib-x25519-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/libcrypto-shlib-x86_64cpuid.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/md5/libcrypto-shlib-md5-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/modes/libcrypto-shlib-aesni-gcm-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/modes/libcrypto-shlib-ghash-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/poly1305/libcrypto-shlib-poly1305-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/rc4/libcrypto-shlib-rc4-md5-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/rc4/libcrypto-shlib-rc4-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/sha/libcrypto-shlib-keccak1600-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/sha/libcrypto-shlib-sha1-mb-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/sha/libcrypto-shlib-sha1-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/sha/libcrypto-shlib-sha256-mb-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/sha/libcrypto-shlib-sha256-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/sha/libcrypto-shlib-sha512-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/whrlpool/libcrypto-shlib-wp-x86_64.o: error: missing IBT and SHSTK properties

2. GNU properties note should be aligned to pointer size, not 8 bytes.  X32 pointer size is 4
bytes, not 8.

**Comment by mattcaswell** [comment]
@levitte

**Comment by levitte** [comment]
Something to be noted is that X32 comes with the flavor "elf32", which we can use.

**Comment by levitte** [comment]
OK, so it seems like we must do this unconditionally.  I wasn't aware.

**Comment by levitte** [comment]
Hold on...  if I generate that property note unconditionally, the linker will report similar errors for all other object files, unless `-fcf-protection` is added to the configuration, right?

But...  what does the linker actually do when it gets a mixture of object files with and without that property note?  What's the actual impact?

**Comment by hjl-tools** [comment]
> Hold on... if I generate that property note unconditionally, the linker will report similar errors for all other object files, unless `-fcf-protection` is added to the configuration, right?

Linker will output GNU property if all inputs have GNU property.  Linker option:

  -z cet-report=[none|warning|error] (default: none)

is used to check if any linker inputs aren't CET enabled when enabling CET.   It is very
useful when there are assembly codes in a project, like openssl.   This CET error report
is off by default.

> But... what does the linker actually do when it gets a mixture of object files with and without that property note? What's the actual impact?
> (the default is `cet-report=none`, so I can only assume that such a mix is allowed, perhaps even harmless...)

Mixed inputs are allowed by design.  You just don't get CET marking in the linker output.
