### ISSUE TITLE
Async use of SSL_CTX_set_cert_verify_callback?

### ISSUE THREAD

**Issue by TheDechev** [openssl/openssl#10894]
Certificate validation in general requires asynchronous operations such as: OCSP/CRL fetch.
On the other hand, the callback from `SSL_CTX_set_cert_verify_callback` expects a synchronous result: 1 (success) / 0 (failure). [(reference)](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_cert_verify_callback.html).

I find it kind of odd that **any** validation of this type is expected to be synchronous.
Is there an alternative API for certificate chain validation that supports asynchronous operations?
Or perhaps that's a feature worth implementing?

**Comment by mattcaswell** [comment]
Oh...I saw your stackoverflow question on this before I saw your question here. See my answer there:

https://stackoverflow.com/questions/59818437/openssl-1-1-1d-async-use-of-ssl-ctx-set-cert-verify-callback/59820324#59820324

**Comment by TheDechev** [comment]
> Oh...I saw your stackoverflow question on this before I saw your question here. See my answer there:
> 
> https://stackoverflow.com/questions/59818437/openssl-1-1-1d-async-use-of-ssl-ctx-set-cert-verify-callback/59820324#59820324

Thanks for the answer!
But I'm still uncertain if that's the correct way to approach this issue.

The async pause method must be called inside a job, I cannot call it explicitly from the certificate validation callback.

As far as I understand the callback itself should be first started as a job, and that of course doesn't happen by default.

**Comment by mattcaswell** [comment]
> The async pause method must be called inside a job, I cannot call it explicitly from the certificate validation callback.
>
> As far as I understand the callback itself should be first started as a job, and that of course doesn't happen by default.

It does if you set SSL_MODE_ASYNC!

**Comment by TheDechev** [comment]
@mattcaswell Thank you! My bad :)
