### ISSUE TITLE
how to modify the so file libcrypto to other name ???  Thank you!!!

### ISSUE THREAD

**Issue by WangJin-9909** [openssl/openssl#10899]

**Comment by t8m** [comment]
There is currently no easy way to do that.

**Comment by kaduk** [comment]
822b5e2645a99bea15329bd66c9723c7e7119cdb adds support for a "variant identifier" inserted between base library name and extension, so as to produce "libcrypto-mycustom.so".  It requires a custom configuration stanza that sets the configuration value, which could be made by copying an existing configure target and modifying it.
