### ISSUE TITLE
How to get the local cert chain with new opaque api?

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1091]
With v.1.0.2   I archived this with that code
```
STACK_OF(X509)* SSL_get_local_cert_chain(SSL* ssl, X509* x509) {
	int i;
	STACK_OF(X509)* result = NULL;

	for (i = 0; i < SSL_PKEY_NUM; i++) {
		if (ssl->cert->pkeys[i].x509 == x509) {
			result = ssl->cert->pkeys[i].chain;
		}
	}
	return result;
}
```

**Comment by richsalz** [comment]
Okay, will add ```SSL_get0_local_cert_chain()```

**Comment by richsalz** [comment]
thinking about this, why can't you get it when you load the cert?

**Comment by wolftobias** [comment]
Because I load the certificate and at some later point I want to get the local cert chain. The proposed function is great.

**Comment by richsalz** [comment]
The team decided not to add a new API, use the existing ones.

**Comment by wolftobias** [comment]
But I can't. It's hidden since the new opaque api.

**Comment by richsalz** [comment]
No, get it when you load the cert.  If this is a problem, please post to openssl-dev mailing list.

**Comment by wolftobias** [comment]
But loading the certificate and accessing the cert chain are complete different code paths at different places. If it is that easy I would not bother you. I want to use the new version 1.1 but there are a lot of open issues. Please help me out of this dilemma!

**Comment by richsalz** [comment]
Please post to openssl-dev

**Comment by mattcaswell** [comment]
@wolftobias Can you use SSL_select_current_cert() followed by SSL_get0_chain_certs()?

**Comment by mattcaswell** [comment]
So something like this (completely untested):
````
STACK_OF(X509)* SSL_get_local_cert_chain(SSL* ssl, X509* x509) {
    STACK_OF(X509) *certs;

    if (!SSL_select_currect_cert(ssl, x509))
        return NULL;

    certs = sk_X509_new_null();
    if (certs != NULL) {
        if (!SSL_get0_chain_certs(ssl, &certs)) {
            sk_X509_free(certs);
            certs = NULL;
        }
    }
    return certs;
}
````

**Comment by wolftobias** [comment]
That could be a good solution. I'll test it right next week when I'm back in the office.

**Comment by mattcaswell** [comment]
Credit to Steve Henson BTW for the idea ;-)

**Comment by mattcaswell** [comment]
Can this be closed now?

**Comment by wolftobias** [comment]
I implemented this in my code and tested it, but I don`t have a real cert chain right now. But I think I will work for me. Thanks for that great support!
