### ISSUE TITLE
Minor EVP_MD_CTX_ctrl regression in master

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#10915]
In pre-3.0.0 times it was possible to use custom ctrl command values at least for digests. Now EVP_MD_CTX_ctrl checks against known values (https://github.com/openssl/openssl/blob/7b131de2bb2be8582c6dfc50bdd3cbc49e1a08be/crypto/evp/digest.c#L671-L687) and then returns an error.

It's not critical regression but it's still a regression. If it's the desired behavior, I can leave with it.

**Comment by mattcaswell** [comment]
It only does this check for provided digests. Since they are provided digests and those digests will only ever understand those ctrls (because ctrls are considered legacy) - isn't it reasonable for it to return an "unsupported" response code for those it doesn't understand. Are you suggesting that previously digests would not return "unsupported" even for ctrls they didn't understand?

**Comment by beldmit** [comment]
For the engine-provided digests (that a legacy) the corresponding call of their ctrl function does not happen because of 'goto conclude'

**Comment by mattcaswell** [comment]
Hmmm....engine provided digests shouldn't be in that codepath at all. Looks like a possible bug here:

````
    if (ctx->digest->prov == NULL
        && (ctx->pctx == NULL
            || (ctx->pctx->operation != EVP_PKEY_OP_VERIFYCTX
                && ctx->pctx->operation != EVP_PKEY_OP_SIGNCTX)))
        goto legacy;
````
I think that first `&&` should probably be `||`. If `ctx->digest->prov` is NULL then there is no provider associated with the digest, so we should go down the legacy path.

**Comment by beldmit** [comment]
I'm freshly dived out from debugger, they get there :)

**Comment by mattcaswell** [comment]
So - if you make the change I suggest above, do they still get there?

**Comment by beldmit** [comment]
The suggested patch solves my problem.

**Comment by mattcaswell** [comment]
Ok...you want to raise a PR, or shall I?

**Comment by beldmit** [comment]
Will do tomorrow. Many thanks!

**Comment by beldmit** [comment]
Raised #10916

**Comment by beldmit** [comment]
Many thanks!
