### ISSUE TITLE
Remove NOTES.VALGRIND?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10921]
Withg PR #10572 and #9294 we basically moved to sanitizer; should we still keep the NOTES.VALGRIND file?

**Comment by beldmit** [comment]
Do we have a HOWTO describing an actual way to debug memory leaks?

**Comment by levitte** [comment]
No matter what we use, are there people interested in running our tests with valgrind, i.e. is this file of public interest?  Then it should remain.

Said differently: do we think we will be asked how to run our tests with valgrind?  Then this file is useful as a template answer, and might even ensure we don't get that question too often.

**Comment by levitte** [comment]
As for the sanitizer methods we use in Travis, it could definitely be valuable to have a similar NOTES file describing that.  Any volunteer?

**Comment by levitte** [comment]
I added a call for help issue, #10929.  I propose this one gets closed.
