### ISSUE TITLE
MIssing some accessors in new api

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1092]
With v1.0.2 I can access that directly:
```
SSL_CIPHER->algorithm_mkey
SSL_CIPHER->algorithm_auth

EVP_CIPHER_CTX->buf_len
```

**Comment by richsalz** [comment]
So the first two are handled by #1096.  Adding a function, trying to figure out the right name: ```int EVP_CIPHER_get_unused``` ?

**Comment by richsalz** [comment]
Can't you explain why you need to look at buf_len?  Otherwise we're going to close this.

**Comment by wolftobias** [comment]
I`m writing a java/jsse component which wraps the openssl api. I need that as part of my cipher implementation.

´´´
	private int getOutputSize(int inputLen) {
		logger.entry(inputLen);
		if (modeBlockSize == 1) {
			return logger.exit(inputLen);
		} else {
			final int buffered = OpenSSL.provider()
					.getEVPCipherCtxBufLen(cipherCtx.getContext());
			if (padding == Padding.NOPADDING) {
				return logger.exit(buffered + inputLen);
			} else {
				final int totalLen = inputLen + buffered + modeBlockSize;
				return logger.exit(totalLen - (totalLen % modeBlockSize));
			}
		}
	}
```

**Comment by levitte** [comment]
Do I get this correctly, that `getOutputSize` should give the total amount of bytes resulting from an `inputLen` that is the total length of the input?  There's no need to know the buffer length for that, as the output will always be a multiple of `modeBlockSize`.

```
final int calculated_size = inputLen;
if (padding != Padding.NOPADDING) {
    calculated_size += modeBlockSize;
} else if ((inputLen % modeBlockSize) != 0) {
    // this isn't right, should return an error.
}
// calculate the amount of bytes that's an exact multiple of modeBlockSize
logger.exit((calculated_size / modeBlockSize) * modeBlockSize);
```

**Comment by richsalz** [comment]
you're just logging some internal state? and as @levitte pointed out, we think you can get what you need with his code.  going to close this.

**Comment by wolftobias** [comment]
I`m not logging only an internal state!!!!
```
logger.exit(buffered + inputLen);
```
This line above is logging and RETURNS a value.

**Comment by levitte** [comment]
Yes?  The answer's still the same
