### ISSUE TITLE
Add MAC one shot function.

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#10939]
The `HMAC()` one shot function is being deprecated in #10836.
Replacing uses of it results in a code sequence that is considerably longer and less readable.

An `EVP_MAC()` one shot function makes sense as an easier replacement.

The main confounding factor is the slightly different things the various MACs require.  HMAC needs a digest, CMAC a cipher and GMAC and KMAC are stand alone.

The obvious answer of having an algorithm argument isn't very future proof -- the _cipher_ and _digest_ parameters to the KDFs and MACs were deliberately not specified as _algorithm_.

**Comment by paulidale** [comment]
KDFs would benefit from something similar, although the variation in parameters there is considerably larger.

**Comment by levitte** [comment]
If you have `EVP_MAC()` take an `OSSL_PARAM` array among others, I believe you have the solution for the varying needs.

**Comment by kaduk** [comment]
> If you have `EVP_MAC()` take an `OSSL_PARAM` array among others, I believe you have the solution for the varying needs.

Perhaps I misremember, but I thought `OSSL_PARAM` was just for the libcrypto/provider interface; exposing it in the user API would be a bit of scope creep.

**Comment by levitte** [comment]
`OSSL_PARAM` was never intended to be just internal. If you grep for `OSSL_PARAM` in the public headers, you will see that "scope creep" was there... actually from day one.

**Comment by richsalz** [comment]
I just did that grep and yes, PARAMS use has escaped into the public API.  I am not sure there is a way to avoid it sadly. My memory of the Edinburgh F2F is that this really wasn't intended to be a first-class public object.  Be that as it may, the team as made it part of the public API.

But boy, do I feel sorry for people who end up having to create a PARAMS object for any of the ```EVP_..._set_params``` functions.  That stuff sure will not "look like C."

**Comment by mattcaswell** [comment]
I do agree that this is rather unfortunate. OSSL_PARAM isn't a great user application facing mechanism.

**Comment by paulidale** [comment]
Wrapper functions would help hide the OSSL_PARAM stuff.
Pretty much the same as was done for the ctrl functions with their wrapper macros.

**Comment by levitte** [comment]
Errrr....  how else would applications communicate certain things directly with the providers?  Please remember that libcrypto cannot possibly know everything about the providers it loads, the application might very well have much better knowledge.

> That stuff sure will not "look like C."

That's neither here nor there.  C doesn't have the sort of limitations you seem to imply.  However, if that's a guiding argument, then there's a *lot* of C libraries that "do not look like C".

**Comment by richsalz** [comment]
Pauli's solution of wrapper functions is better than this.  Other crypto providers, who have new parameters that OpenSSL does not know anything about, can have their own headers and their own wrappers. I do not think we should support "generic" providers with "unknown" parameters in this first release.  The project should wait until some use-cases show up.

My statement that this doesn't "look like C" most definitely is appropriate.  OpenSSL hasn't strayed from C before this release and I think exposing this as almost a requirement for users to understand is a betrayal of that approach.

I am not turning this into an argument about PARAM's.  I just strongly feel it would be a mistake to require users to understand it.

**Comment by levitte** [comment]
> OpenSSL hasn't strayed from C before this release...

So you would say that everything surrounding ASN.1 and DER "looks like C"? Heh...

**Comment by richsalz** [comment]
Yes, everything that *surrounds* that data is a C API.  OpenSSL doesn't have programmers deal with "void*" all the time. And when we made datatypes opaque, we still kept typed pointers.

**Comment by levitte** [comment]
> Other crypto providers, who have new parameters that OpenSSL does not know anything about, can have their own headers and their own wrappers.

This is perfectly possible to do, of course...  *But*, those wrappers will have to call *something* that passes the `OSSL_PARAM` arrays they build up, hence public functions.

**Comment by paulidale** [comment]
Strictly, the wrappers don't need to call a _public_ function.
I think it is better if they do.

**Comment by levitte** [comment]
Er, I don't see how *external* providers that also provide a wrapper library would do without access to public functions...

**Comment by levitte** [comment]
> OpenSSL doesn't have programmers deal with "void*" all the time.

... 'xcept in all the `ctrl` functions...  (which, incidently, is the thing closest to OSSL_PARAM passing, except `ctrl` are closer to `ioctl`, which...  well...)

**Comment by richsalz** [comment]
>'xcept in all the ```ctrl``` functions.

No, the programmers don't know that they all filter down to a single ```void*``` parameter so they don't have to deal with it.  And there was discussion and a PR that turned many/most/some of the CTRL functions into one-line real functions with prototypes.  But my point is correct.  The fact that OpenSSL deals with it is OpenSSL's issue, not programmers.

**Comment by paulidale** [comment]
Didn't most of the ctrl functions end up with macro wrappers which loses all type safety -- a programming mistake and boom without the compiler catching it.

**Comment by levitte** [comment]
Like I said, nothing wrong with wrappers. However, we still need to be able to handle the unknown, and to give applications and other libraries the tools to pass values to and from providers that *they* know but we don't. Just like `ctrl` functions are available for exactly the same purpose. Basic tools.

**Comment by richsalz** [comment]
"we" is OpenSSL dev team.  "we" is not much larger community using OpenSSL.

The CTRL functions were always macros, there is a PR somewhere to turn them into functions.

**Comment by levitte** [comment]
> The CTRL functions were always macros

Incorrect.  The *wrappers* around the `ctrl` functions were macros.

**Comment by richsalz** [comment]
> Incorrect. The wrappers around the ctrl functions were macros.

Yes, I was too hasty.  I meant the wrappers were macro's and there's a PR somewhere to turn them into functions.  I recall Ben Laurie was also interested in bringing type-safety via functions, but nothing came of it.

The main point is that while the team has to handle void*, application developers do not.

**Comment by paulidale** [comment]
This has been done via EVP_Q_mac.
