### ISSUE TITLE
SSL routines:ssl3_get_record:wrong version number:../openssl-1.1.1b/ssl/record/ssl3_record.c:332

### ISSUE THREAD

**Issue by deekshith565** [openssl/openssl#10938]
I'm getting below error when I try to do SSL_accept() from server code

SSL routines:ssl3_get_record:wrong version number:../openssl-1.1.1b/ssl/record/ssl3_record.c:332

I'm not sure what does it mean, can anyone explain me

**Comment by mattcaswell** [comment]
"wrong version number" can occur in a few different scenarios. This particular instance happens when we're processing the first record of data that we've received from the client. SSL/TLS records have a defined structure. From RF5246:

>       struct {
>           ContentType type;
>           ProtocolVersion version;
>           uint16 length;
>           opaque fragment[TLSPlaintext.length];
>       } TLSPlaintext;

The first check we do when processing the first record of data from the client is sanity check the ProtocolVersion data. This is two bytes of data - the first of which is *always* 0x03. The error you're getting occurs when we've received something other than 0x03. This usually means that client that has connected is attempting to talk some protocol other than SSL/TLS - or sometimes that the data has been corrupted somehow (usually due to an application bug).

**Comment by deekshith565** [comment]
@mattcaswell Thanks for quick reply
Well what I'm doing is to establish a secure communication between an existing normal communication in our project, my project is plug n play device, which will be connected to other machine from where we get data and process it. let say data from where I get is client which is x86 based, and my local machine is server which is ARM based.
We have our own communication media let say X(it's a wrapper kinda to support multiple comm's beneath it like PCIe or USB or etc..,) which communicates via PCIe(lets say)   

Sow now I wrote own bio code:  

1. BIO *rbio = BIO_new(BIO_s_X());
2. BIO *wbio = BIO_new(BIO_s_X());
3. SSL_set_bio(ssl, rbio, wbio); 

where in BIO_s_X I have set bio ptr to my X media channel handle, write and read functions to my own X write and read (I took BIO_s_mem as example and wrote)

For now I wrote server and client code from http://simplestcodings.blogspot.com/2010/08/secure-server-client-using-openssl-in-c.html
Almost same code but I replaced socket part with above 3 lines of code, certificate also I created as mentioned in above link 

That's it I didn't do anything else, but when I run server and client code I get below error
SSL routines:ssl3_get_record:wrong version number:../openssl-1.1.1b/ssl/record/ssl3_record.c:332

I'm still not sure why, I'm really stuck actually, kindly help 

Also help if my approach of setting BIO is correct or not

**Comment by mattcaswell** [comment]
In principle this approach is fine. But it seems what is actually being passed is not quite what would be expected. Perhaps your custom BIO could dump what is being read at the time of the failure as hex to some log file? If  I can take a look at the data that it is trying to read when it fails I might be able to diagnose the problem.

Another thing you could do is dump what is written by the client for the same record and check that they are exactly the same.

**Comment by deekshith565** [comment]
Ok, will try to dump and see.
But instead of my own BIO, can I use any existing BIO and just change the pointer of that BIO to my X media channel handle, also read and write functions to X read and write? Suppose like I can just customize BIO_f_s_ssl? 
Or any other suggestion is highly helpful. (I am very new to this BIO concept and I'm not able to get it 
 at all especially from OPENSSL code)

**Comment by mattcaswell** [comment]
BIO_f_s_ssl() is a *filter* BIO not a source/sink BIO. A filter BIO sits in a chain of BIOs possibly making changes or otherwise examining the data being pass through the chain. Therefore it probably isn't a suitable template for your purposes.

> can I use any existing BIO and just change the pointer of that BIO to my X media channel handle, also read and write functions to X read and write

Well, you could certainly look at some of the existing BIO implementations and use them as a template for what you want to do. But without knowing more about your situation I couldn't suggest which one is the most suitable. It sounds like you already did pretty much that, but basing it on BIO_s_mem().

Lets see if we can get what you've already got working before we worry about rewriting it! A dump of what is going through your BIOs would be very helpful.

**Comment by deekshith565** [comment]
I couldn't see any data getting printed, kindly check my below BIO_s_X code, I feel something 

`#include <errno.h>
#include <bio_local.h>
#include "internal/cryptlib.h"
#include "internal/bio.h"
#include <openssl/ssl.h>
#include <openssl/err.h>

static struct X_handle devH;

static int mem_write(BIO *h, const char *buf, int num);
static int mem_read(BIO *h, char *buf, int size);
static int mem_puts(BIO *h, const char *str);
static long mem_ctrl(BIO *h, int cmd, long arg1, void *arg2);
static int mem_new(BIO *h);
int bwrite_conv(BIO *bio, const char *data, size_t datal, size_t *written);
int bread_conv(BIO *bio, char *data, size_t datal, size_t *readbytes);

static const BIO_METHOD mem_method = {
    	BIO_TYPE_MEM,
    	"Custom Secure BIO",
    /* TODO: Convert to new style write function */
    bwrite_conv,
    mem_write,
    bread_conv,
    mem_read,
    mem_puts,
    NULL,
    mem_ctrl,
    mem_new,
    NULL,
    NULL,                      /* mem_callback_ctrl */
};

const BIO_METHOD *BIO_s_X(void)
{
    return &mem_method;
}

static int mem_init(BIO *bi, unsigned long flags)
{
    bi->shutdown = 1;
    bi->init = 1;
    bi->num = -1;
    bi->ptr = &devH;
    return 1;
}

static int mem_new(BIO *bi)
{
    return mem_init(bi, 0L);    
}

static int mem_read(BIO *b, char *out, int outl)
{
int ret = -1, rc = -1;
	
 	  rc = X_read_data(b->num, X_CHANNEL_NO, (uint8_t **)&out, &outl);
  if(rc == 0)
   	 {
       printf("\nX Read SUCCESS\n");
  	   	      if(out != NULL)
	   	     printf("\nData read is = %s\n", out);
	   	   else printf("\nNOTHING READ\n");
       		   ret = outl;
                      }
   	 else
   	{
           		ret = -1;
           		printf("\nX Read FAIL\n");
   	}
 	return ret;
}

static int mem_write(BIO *b, const char *in, int inl)
{
    int ret = -1, rc = -1;

    	if (in == NULL) {
        	//BIOerr(BIO_F_MEM_WRITE, BIO_R_NULL_PARAMETER);
        	goto end;
    	}

   rc =  X_write_data(b->num, X_CHANNEL_NO, (uint8_t *)in, inl);
   if(rc == 0)
   	 {
	   	printf("\nX Write SUCCESS\n");
		  if(in != NULL)
	   	printf("\nData written is = %s\n", in);
	   	else printf("\nNOTHING WRITTEN\n");
	   	ret = inl;
   	}
   	else
   	{
	  	 ret = -1;
		   printf("\n write FAIL\n");
   	}
end: 
   	return ret;
}

int bwrite_conv(BIO *bio, const char *data, size_t datal, size_t *written)
{
    int ret;

    if (datal > INT_MAX)
       	  datal = INT_MAX;

    ret = bio->method->bwrite_old(bio, data, (int)datal);

    	if (ret <= 0) {
        *written = 0;
        	        return ret;
   	 }

    	*written = (size_t)ret;

    return 1;
}

int bread_conv(BIO *bio, char *data, size_t datal, size_t *readbytes)
{
    int ret;

    if (datal > INT_MAX)
        datal = INT_MAX;

    ret = bio->method->bread_old(bio, data, (int)datal);

    if (ret <= 0) {
        *readbytes = 0;
        return ret;
    }

    *readbytes = (size_t)ret;

    return 1;
}

static long mem_ctrl(BIO *b, int cmd, long num, void *ptr)
{
	long ret = 1;
 
	printf("\n\n\t\tCMD =%d\n\n");
	switch (cmd) {
	case BIO_CTRL_FLUSH:
        	ret = 1;
        	break;
	case BIO_CTRL_PUSH:
	default:
        	ret = 0;
        	break;
	}
	return ret;
}
static int mem_puts(BIO *bp, const char *str)
{
int n, ret;
    	n = strlen(str);
    	ret = mem_write(bp, str, n);
    	/* memory semantics is that it will always work */
    	return ret;
}
`

**Comment by mattcaswell** [comment]
If you're not seeing anything being printed after implementing the above then I'd guess that either:

1) Your code isn't being called at all (are you sure that it is?)
or
2) Perhaps stdout is being redirected somewhere or somehow being suppressed? You might try printing to a log file instead.

Aside from that I'll note a couple of things about this code (unfortunately none of which explain your problem):

1)  You are including *internal* header files: internal/cryptlib.h, internal/bio.h, bio_local.h. You are not supposed to do this. They are internal for a reason. The contents of these files are not stable and may change from one patch release to another which would break your code. Instead you are supposed to construct custom BIOs using the `BIO_meth_*` functions described here:

https://www.openssl.org/docs/man1.1.1/man3/BIO_meth_new.html

2) You are dumping your output using printf. That isn't going to work too well because the data is *binary* and may not be NUL terminated or contain printable characters. You might want to use `BIO_dump_fp` for this purpose instead. E.g instead of:

````
printf("\nData read is = %s\n", out);
````
You might use
````
printf("\nData read is =\n");
BIO_dump_fp(stdout, out, outl);
printf("\n");
````

**Comment by deekshith565** [comment]
Yeah I have also checked on that, I will construct BIO using BIO_meth_* APIs, Thanks :)

Now I got prints using BIO_dump_fp
Client hello seems ok right? but after that I'm not sure what is happening and why server read is NULL

Client:
`Data written is =
*************************************************************************
0000 - 16 03 01 00 bd 01 00 00-b9 03 03 58 f5 9e 9c 5d   ...........X...]
0010 - d1 b9 44 3f 70 a9 9d 41-58 3a 1d bc 3d b2 66 c0   ..D?p..AX:..=.f.
0020 - 11 aa d2 74 56 a4 b6 d6-d1 68 46 00 00 38 c0 2c   ...tV....hF..8.,
0030 - c0 30 00 9f cc a9 cc a8-cc aa c0 2b c0 2f 00 9e   .0.........+./..
0040 - c0 24 c0 28 00 6b c0 23-c0 27 00 67 c0 0a c0 14   .$.(.k.#.'.g....
0050 - 00 39 c0 09 c0 13 00 33-00 9d 00 9c 00 3d 00 3c   .9.....3.....=.<
0060 - 00 35 00 2f 00 ff 01 00-00 58 00 0b 00 04 03 00   .5./.....X......
0070 - 01 02 00 0a 00 0c 00 0a-00 1d 00 17 00 1e 00 19   ................
0080 - 00 18 00 23 00 00 00 16-00 00 00 17 00 00 00 0d   ...#............
0090 - 00 30 00 2e 04 03 05 03-06 03 08 07 08 08 08 09   .0..............
00a0 - 08 0a 08 0b 08 04 08 05-08 06 04 01 05 01 06 01   ................
00b0 - 03 03 02 03 03 01 02 01-03 02 02 02 04 02 05 02   ................
00c0 - 06 02                                             ..
*************************************************************************`

Data read is =
*************************************************************************
0000 - 00 00 00 00 00                                    .....
*************************************************************************

Server:

`Data read is =
*************************************************
0000 - 00 00 00 00 00                                    .....
*************************************************
`

**Comment by mattcaswell** [comment]
Well, this is clearly the reason for the "wrong version number" error. What is being read by the server from the underlying BIO is not the data that the client sent (its just a repeated sequence of 0 bytes). So it seems that either your `X_write_data` function is failing to write the data correctly, or your `X_read_data` is failing to read it properly, or some component in between those two is failing to transmit the data correctly.

Since none of that is in OpenSSL code there's not a lot I can do to help you with that!

**Comment by deekshith565** [comment]
Yeah but my x_write_data and X_read_data are working fine without setting BIO, i.e., just to send and read plain text(without OpenSSL TLS)

**Comment by mattcaswell** [comment]
You might want to try simplifying your test case down. This seems to have very little to do with libssl, so for example you might just want to try a simple program that just does some BIO_write()/BIO_read() calls. You might also want to run this through a debugger to step through what is happening. It seems fairly clear though that the problem doesn't lie in the OpenSSL libraries.

**Comment by mattcaswell** [comment]
Something else I noticed. I'm not sure if it is relevant because I don't know what X_read_data and X_write_data actually do. But I notice that the first argument to these calls is `b->num` which is never set to anything other than -1 in your code.

**Comment by deekshith565** [comment]
Yay there is a progress now :)
You are right in my read and write APIs call it should be b->ptr instead b->num actually, now server has read first packet successfully, and client now is waiting for server hello

And still I got error, in server from BIO, error I pasted down, I didn't get it.

Client:

Data written is =
*************************************************************************
0000 - 16 03 01 00 bd 01 00 00-b9 03 03 bd ae db ae 2e   ................
0010 - fc 5c 31 30 cb 29 0f 0c-ab 1e b8 f8 f9 b1 c0 97   .\10.)..........
0020 - a3 a3 3e 85 79 93 e7 51-9c f8 da 00 00 38 c0 2c   ..>.y..Q.....8.,
0030 - c0 30 00 9f cc a9 cc a8-cc aa c0 2b c0 2f 00 9e   .0.........+./..
0040 - c0 24 c0 28 00 6b c0 23-c0 27 00 67 c0 0a c0 14   .$.(.k.#.'.g....
0050 - 00 39 c0 09 c0 13 00 33-00 9d 00 9c 00 3d 00 3c   .9.....3.....=.<
0060 - 00 35 00 2f 00 ff 01 00-00 58 00 0b 00 04 03 00   .5./.....X......
0070 - 01 02 00 0a 00 0c 00 0a-00 1d 00 17 00 1e 00 19   ................
0080 - 00 18 00 23 00 00 00 16-00 00 00 17 00 00 00 0d   ...#............
0090 - 00 30 00 2e 04 03 05 03-06 03 08 07 08 08 08 09   .0..............
00a0 - 08 0a 08 0b 08 04 08 05-08 06 04 01 05 01 06 01   ................
00b0 - 03 03 02 03 03 01 02 01-03 02 02 02 04 02 05 02   ................
00c0 - 06 02                                             ..

*************************************************************************


Server:

Data read is =
*************************************************************************
0000 - 16 03 01 00 bd 01 00 00-b9 03 03 bd ae db ae 2e   ................
0010 - fc 5c 31 30 cb 29 0f 0c-ab 1e b8 f8 f9 b1 c0 97   .\10.)..........
0020 - a3 a3 3e 85 79 93 e7 51-9c f8 da 00 00 38 c0 2c   ..>.y..Q.....8.,
0030 - c0 30 00 9f cc a9 cc a8-cc aa c0 2b c0 2f 00 9e   .0.........+./..
0040 - c0 24 c0 28 00 6b c0 23-c0 27 00 67 c0 0a c0 14   .$.(.k.#.'.g....
0050 - 00 39 c0 09 c0 13 00 33-00 9d 00 9c 00 3d 00 3c   .9.....3.....=.<
0060 - 00 35 00 2f 00 ff 01 00-00 58 00 0b 00 04 03 00   .5./.....X......
0070 - 01 02 00 0a 00 0c 00 0a-00 1d 00 17 00 1e 00 19   ................
0080 - 00 18 00 23 00 00 00 16-00 00 00 17 00 00 00 0d   ...#............
0090 - 00 30 00 2e 04 03 05 03-06 03 08 07 08 08 08 09   .0..............
00a0 - 08 0a 08 0b 08 04 08 05-08 06 04 01 05 01 06 01   ................
00b0 - 03 03 02 03 03 01 02 01-03 02 02 02 04 02 05 02   ................
00c0 - 06 02                                             ..

*************************************************************************

**error:20078044:BIO routines:bio_read_intern:internal error:../openssl-1.1.1b/crypto/bio/bio_lib.c:281**

I'm just bugging with BIOs without any knowledge :)

**Comment by deekshith565** [comment]
Are there any examples to use BIO_meth_* APIs to create custom BIOs?

**Comment by mattcaswell** [comment]
See linked #10961

**Comment by mattcaswell** [comment]
> Are there any examples to use BIO_meth_* APIs to create custom BIOs?

s_server creates a custom BIO here:

https://github.com/openssl/openssl/blob/c8943eb04ae41506ec8a1869103e2e1dec6bfcd8/apps/s_server.c#L306

> Also I just need bio_local.h with this my current custom BIO implementation.

If you use the `BIO_meth_*` functions you shouldn't need bio_local.h at all.

**Comment by deekshith565** [comment]
Hi,

There is some progress but now I'm getting below errors
**CLIENT**: SSL routines:ssl3_get_record:bad record type:../ssl/record/ssl3_record.c:350
**SERVER**:  SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:../openssl-1.1.1b/ssl/record/rec_layer_s3.c:1536:SSL alert number 10

I think version mismatch is the problem but I'm not sure, below are my OpenSSL versions, could this be any problem?
**CLIENT:** OpenSSL 1.1.1  11 Sep 2018
**SERVER:** OpenSSL 1.1.1b  26 Feb 2019

I'm using below methods SSL context initialization, I want to implement in TLSv1.2 actually:
**CLIENT:** TLS_client_method()
**SERVER:** TLS_server_method()

Only server certificate I used generated using:
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout mycert.pem -out mycert.pem

**Below are client and server packets from BIO dump:**
**Client has sent below packet:**
*************************************************************************
0000 - 16 03 01 01 20 01 00 01-1c 03 03 65 01 dd 21 26   .... ......e..!&
0010 - f3 4a b1 af 77 91 59 16-7f 94 91 ac fc 51 90 27   .J..w.Y......Q.'
0020 - 44 9a 12 55 21 04 bd 0e-43 c5 2e 20 ea 62 6c 35   D..U!...C.. .bl5
0030 - d1 70 1b 40 af 7e d4 7b-ad 32 c5 8c 6a 7f 3e 35   .p.@.~.{.2..j.>5
0040 - cc 9a 31 06 6d fb 4f d8-ea 88 8d 9d 00 3e 13 02   ..1.m.O......>..
0050 - 13 03 13 01 c0 2c c0 30-00 9f cc a9 cc a8 cc aa   .....,.0........
0060 - c0 2b c0 2f 00 9e c0 24-c0 28 00 6b c0 23 c0 27   .+./...$.(.k.#.'
0070 - 00 67 c0 0a c0 14 00 39-c0 09 c0 13 00 33 00 9d   .g.....9.....3..
0080 - 00 9c 00 3d 00 3c 00 35-00 2f 00 ff 01 00 00 95   ...=.<.5./......
0090 - 00 0b 00 04 03 00 01 02-00 0a 00 0c 00 0a 00 1d   ................
00a0 - 00 17 00 1e 00 19 00 18-00 23 00 00 00 16 00 00   .........#......
00b0 - 00 17 00 00 00 0d 00 30-00 2e 04 03 05 03 06 03   .......0........
00c0 - 08 07 08 08 08 09 08 0a-08 0b 08 04 08 05 08 06   ................
00d0 - 04 01 05 01 06 01 03 03-02 03 03 01 02 01 03 02   ................
00e0 - 02 02 04 02 05 02 06 02-00 2b 00 09 08 03 04 03   .........+......
00f0 - 03 03 02 03 01 00 2d 00-02 01 01 00 33 00 26 00   ......-.....3.&.
0100 - 24 00 1d 00 20 d5 f8 54-91 e1 1d 08 59 b4 e2 1d   $... ..T....Y...
0110 - f1 a0 10 40 89 b1 01 ba-e7 50 1d 8d 16 cc fe 5b   ...@.....P.....[
0120 - 20 cb a9 ff 32                                     ...2
*************************************************************************

**Sever has read same and sent below:** (not copied full message)

0000 - 16 03 03 00 7a 02 00 00-76 03 03 68 d6 86 46 5c   ....z...v..h..F\
0010 - 64 9d 45 52 3f 63 ff a8-39 16 0b 64 a6 13 df 57   d.ER?c..9..d...W
0020 - 13 97 23 9f 9f f5 a3 ac-e6 9f 8c 20 ea 62 6c 35   ..#........ .bl5
0030 - d1 70 1b 40 af 7e d4 7b-ad 32 c5 8c 6a 7f 3e 35   .p.@.~.{.2..j.>5
.....
.....
03e0 - c3 2b c0 1f 87 89 30 24-b3 b9 3c 5e b6 5b b5 ee   .+....0$..<^.[..
03f0 - 6f cc 6b 76 e7 b9 60 60-82 29 40 c3 46 5a c3 56   o.kv..``.)@.FZ.V
0400 - 64 6f 72 f6 c7 47 e6 ee-ad 23 e5 98 6b f2 81 1d   dor..G...#..k...
0410 - 5f 21 35 e4 6c 64                                 _!5.ld

**Then Client has written:**

0000 - 15 03 03 00 02 02 0a 

And got below error:
139964884866880:error:1408F1BB:SSL routines:ssl3_get_record:bad record type:../ssl/record/ssl3_record.c:350

**Server read same (0000 - 15 03 03 00 02 02 0a) and got below error:**

548235530256:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:../openssl-1.1.1b/ssl/record/rec_layer_s3.c:1536:SSL alert number 10


Kindly help!

**Comment by mattcaswell** [comment]
> I think version mismatch is the problem but I'm not sure, below are my OpenSSL versions, could this be any problem?

In principle it should not matter that the client and server are at different versions. OpenSSL implements standards based TLS and is intended to be interoperable between different implementations of the TLS protocols, and certainly within different versions of itself. That said both your versions are quite old and a number of bugs have been fixed since then, so it certainly would not hurt to upgrade your OpenSSL versions on both ends to rule that out as a source of problems.

**Comment by deekshith565** [comment]
It's not actually in my hands to upgrade the versions now in our project, even if I ask it might take long process and time, so I'm mostly ruled out of this option. 

Also as you mentioned version should not a problem or I must upgrade?

But I want to ask from packet transmission could you find any problem? If anything missing?
Or this has anything to be done with my custom BIO implementation?

**Comment by deekshith565** [comment]
I got what is the issue but not solution

I dumped socket based client hello messages and compared with mine

Client has sent hello, server received and sent his hello and certificate together.

Client received server hello along with server certificate, client read server hello(5B+65B) and while reading server certificate (following is the header),

0000 - 16 03 03 02 74 (which means length = 0x274 which is 628 bytes)

Till here both socket based and my custom implementation are same, after this I see socket based is reading 628B of data, but in my case it got request to read only 65B from upper layer instead of 0x274(628), I'm not sure why 

(Also what I observed is 65B is server hello message length excluding header size(5B))

**Comment by deekshith565** [comment]
I found the issue and it is working now.

Issue is BIO_read/mem_read functions receive input to put data in specific address from upper layer, but our x_read is giving address of data, which is conflicting and it's reading different data.

So instead I should do mem copy and it worked.

Thank you :)

**Comment by huegelcesar** [comment]
Hello dears,
Is there any applied fix for this issue?

**Comment by t8m** [comment]
I do not think there is any real issue in OpenSSL here.
