### ISSUE TITLE
Code improvment in apps/x509.c

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#10940]
In the main function, a opthelp: label in defined line 215, inside a switch block.
``````
 opthelp:
            BIO_printf(bio_err, "%s: Use -help for summary.\n", prog);
            goto end;
``````
It is referenced in inside the switch block
It is also referenced from outside the switch block :

line 485
``````
    if (argc != 0) {
        BIO_printf(bio_err, "%s: Unknown parameter %s\n", prog, argv[0]);
        goto opthelp;
    }
``````
Is it possible to remove this reference like this (cleaner code) : 
``````
    if (argc != 0) {
        BIO_printf(bio_err, "%s: Unknown parameter %s\n", prog, argv[0]);
        BIO_printf(bio_err, "%s: Use -help for summary.\n", prog);
        goto end;
    }
``````
Thanks

**Comment by levitte** [comment]
That might look cleaner from one point of view, but means that the string is duplicated, so any time we want to update it, we must remember to do so in two places.  This ends up being a trade off between some idea of cleanliness and maintenance.

Unless you can point at a compiler that can't handle that goto properly, this is *not* a bug.

**Comment by richsalz** [comment]
More importantly, it is a parallel structure with every other command.  Changing one, to micro-optimize, is bad.  (And anyway, compilers usually optimize identical string constants into one instance)

**Comment by qualitesys** [comment]
I agree with you, this is _not_ a bug of course. Still, the while / switch structure is ignored (the o variable is undetermined) when the goto opthelp is called from outside the loop :

``````
    while ((o = opt_next()) != OPT_EOF) {
        switch (o) {
        case OPT_EOF:
        case OPT_ERR:
 opthelp:
            BIO_printf(bio_err, "%s: Use -help for summary.\n", prog);
            goto end;
.......
        }
    }
    if (argc != 0) {
        BIO_printf(bio_err, "%s: Unknown parameter %s\n", prog, argv[0]);
        goto opthelp;
    }
``````
goto statements can be tricky sometimes.

**Comment by richsalz** [comment]
>(the o variable is undetermined) 

and its not used. The benefit of parallel structure -- all command parsing looks and works the same -- is important.

i think this should be closed.

**Comment by levitte** [comment]
> Still, the while / switch structure is ignored (the o variable is undetermined) when the goto opthelp is called from outside the loop

That would only be a problem if we didn't `goto end`

**Comment by qualitesys** [comment]
Thanks, I close the point
