### ISSUE TITLE
Importing Arbitrary Key Data

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#10962]
We should have a mechanism for applications to import arbitrary key data into a provider. This is separate to key generation (where the keys are created inside the provider), or de-serialization (where the keys are loaded directly by the provider). This is the scenario where the application knows the low level key details and wants to create that key directly in the provider. We can do this with our built-in types (RSA, DSA, DH etc), via `evp_keymgmt_importkey`, but there is no application API directly to that  function.

**Comment by levitte** [comment]
Er, yes there is.

https://github.com/openssl/openssl/blob/master/doc/man3/EVP_PKEY_fromdata.pod

**Comment by mattcaswell** [comment]
Hmmmm...this seems to use `evp_keymgmt_fromdata` (which explains why I couldn't find it). What is the difference between that and `evp_keymgmt_importkey`? Why do we need both?

**Comment by levitte** [comment]
All you have to do is look

https://github.com/openssl/openssl/blob/0cb3f4f985aa52688ddc90075f480ba612d34fe3/crypto/evp/keymgmt_lib.c#L206-L218

**Comment by levitte** [comment]
It's true, though, that we I could have had `evp_keymgmt_importdomparams(keymgmt, params)` instead of `keymgmt->importdomparams(provctx, params)`, that would have avoided getting the provctx in this particular function.

**Comment by mattcaswell** [comment]
Thanks for clearing my confusion. My issue was unfounded. Closing.

**Comment by levitte** [comment]
> My issue was unfounded.

Not entirely, I can see how the way the function was written can be confounding.  I'll submit a small refactor for clarity.
