### ISSUE TITLE
macro SSL_IS_DTLS(s) not part of public api

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1097]
We`d like use the the macro, but it is not part of the public api.

```
/* Check if an SSL structure is using DTLS */ 
# define SSL_IS_DTLS(s)  (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_DTLS)
```

**Comment by richsalz** [comment]
this will be SSL_is_dtls() as a function.

**Comment by richsalz** [comment]
fixed in commit e417070c9f2162594e8289aed93bd5801e70e60d

**Comment by wolftobias** [comment]
Please provide us the nid values for the two constants of SSL_kEDH and SSL_kEECDH, because we`re unable to find them.

**Comment by wolftobias** [comment]
Please provide us an alternative for this in public api.
```
DTLS_VERSION_LT
```

**Comment by mattcaswell** [comment]
@wolftobias - please can you raise these as new issues, rather than adding them to an unrelated closed issue?
