### ISSUE TITLE
Support X.509 version change

### ISSUE THREAD

**Issue by stas730** [openssl/openssl#1099]
I want X509v4, so I need to change code. Version change not supported in OpenSSL command line tool. Sometimes, OpenSSL creates X509v1 certificates.
It is better to create option with name like "-x509version" or config line.

**Comment by stas730** [comment]
We need to add change code to CRL version, too.

**Comment by kaduk** [comment]
I was not aware that an X509v4 existed at all; if it did, I would expect OpenSSL to gain first-class support for it and not just a one-off flag to force-set the version field.
So, closing this until an X509v4 reference appears.

**Comment by JonathanWilbur** [comment]
@stas730 

Where is X.509 Version 4 defined? I have tried to find the specification for it. I believe it exists, because I see that [Firefox implemented support for it](https://bugzilla.mozilla.org/show_bug.cgi?id=1047177), but I can't find it in the latest X.509 ASN.1 module, nor in IETF RFCs. A Bing search has been somewhat unfruitful as well.

**Comment by mattcaswell** [comment]
@JonathanWilbur: there is no such thing as X.509v4. In the bug you link for Firefox you will see that what they implemented was a workaround for interoperating with buggy software that incorrectly encodes the certificate version as v4 (the encoding of v3 is 0x02, but buggy software may incorrectly encode it as 0x03 - which actually indicates v4). So they're just treating a v4 certificate in exactly the same way as a v3 certificate.

**Comment by JonathanWilbur** [comment]
Oh, I see. Thank you!

**Comment by erdbeerschnitzel** [comment]
For some more information you can have a look here https://github.com/openssl/openssl/issues/6599
