### ISSUE TITLE
Why are int and size_t are used so inconsistently

### ISSUE THREAD

**Issue by davxy** [openssl/openssl#10995]
For example, the function:

` int CRYPTO_secure_malloc_init(size_t size, int minsize);`

What is the rational behind the choice of `size_t` for `size` and `int` for `minsize`?
I mean, why not declare both as `size_t`?

Studying the codebase I found other cases here and there like this one.

Is there any particular reason for this type of choice? 

The only rational explanation I can think of is that in the past the `int` parameter was used with a negative value to trigger some particular behavior... but looks strange anyway.

Can we change the interface types where appropriate and not dangerous? Or are we  condemned to this badly designed interfaces forever because is too risky at this point?

Thanks

**Comment by levitte** [comment]
In this case, we can't even blame history, as this function appeared in 1.1.0.  Otherwise, it does turn out that history is to blame, and we're quite conservative in changing the argument types when we fear that applications rely on old signatures.

Our current main focus is on the internals for the moment, so don't expect much prompt change in this regard.  It is in the back of our minds, though, that we do need to clean up our history at some point.

**Comment by mattcaswell** [comment]
This has been a problem for a long time. At one point I went through and converted lots of libssl to use size_t internally as much as possible - but I was unable to change usage in the actual API because of backwards compat rules. We should be using size_t for all new APIs where we're talking about the size of something. I don't know how this particular function slipped through. That just looks like a mistake to me.

**Comment by richsalz** [comment]
Notwithstanding the general issue, which Matt and Richard explained, in this particular case there is no need for minsize to be size_t as it should generally be a small number (32 or 16 say), and having int provides a tiny sliver of safety.

**Comment by levitte** [comment]
Er, I fail to see the safety with `int` over `size_t`. The latter is a well known type in C90 and up.

**Comment by richsalz** [comment]
negative numbers.

**Comment by mattcaswell** [comment]
> negative numbers.

That makes no sense to me. How does that provide you with any safety? If anything its the other way around. `minsize` is a size and should not be negative. The fact that it can be due to its type means there is less safety that had it been a size_t.

**Comment by richsalz** [comment]
If a negative number is passed in, the implementation can check.  If a someone does ```(size_t)val``` where they get the val wrong, it will be a huge number.  Like I said, a tiny sliver of safety.

**Comment by mattcaswell** [comment]
The implementation can sanity check its input at run time regardless of whether you use an int or a size_t. If you use an int and the implementation considers negative numbers as not sane, then you can achieve exactly the same thing by using a size_t and considering anything over INT_MAX as being not sane. The choice of int for a type provides zero additional safety from that perspective.

What we're talking about here though is *type safety*. Type safety is enforced by the compiler at compile time. The size_t type doesn't have the concept of negative numbers - so (ignoring the problem of casts for the moment) - it is not possible to "accidentally"  pass a negative number around when you didn't mean to. Negative numbers simply don't exist with a size_t. The type enforces this for you.

Casts break type safety. If you use casts then you deliberately override the type safety checks that the compiler gives you. Its one of the main reasons casts are frowned upon, and should be avoided where possible. When I did the work on libssl to convert as many things that were sizes to use "size_t", it was one of my objectives to remove as many casts as possible. We had very many instances where things like a value would start off as an int, and then be passed to a function where it would be cast to a size_t, and then passed to something else where it would be cast again. I saw numerous instances of values being cast 3, or 4 or more times in a single call stack. Every time these casts occur we introduce the possibility of something going wrong. By using a single type for a size consistently throughout the code we avoid many possibilities for cock-up. By using size_t for sizes in our APIs we extend the benefits out to applications using those APIs (and potentially remove one more place in the call stack where a cast might occur).

The `CRTYPO_secure_malloc_init` function mentioned above simply should not have had this confused use of types in its parameters. But...now we're stuck with it, and for backwards compat reasons it is very difficult to change. Ah well. :-(

**Comment by richsalz** [comment]
Well, we disagree a bit, but it's not worth arguing about so fine.

**Comment by davxy** [comment]
There are always *religious* wars when comes to the style. But this is not just about the style, this is about **consistence**.

size_t is a standard C90 type meant to be used for sizes, that's all. And that is true regardless the **assumptions** about what the user will pass as the parameter's value.

If there are constraints about the max, I suggest to check it within the function and put it in the documentation.

This is especially ugly because of the **signed** type. Which makes even less sense to me.

I hope the size_t approach will be followed in the future.

I think this is particularly important because:

1.   a lot of people doesn't like badly designed interface and for them things like this are a sufficient reason to don't contribute to the project.
2.  type-safety matters.
3.  today's assumptions may not be valid in the future.

**Comment by levitte** [comment]
> I hope the size_t approach will be followed in the future.

That's the intention

**Comment by paulidale** [comment]
In this case, I don't think that changing the argument type will cause undue pain.

As @richsalz noted, small integer values are what are used.  The code underneath has this check for a non-negative, power of 2:
```
if (minsize <= 0 || (minsize & (minsize - 1)) != 0)
    goto err;
```

**Comment by levitte** [comment]
So, er, PR welcome? :wink:

**Comment by paulidale** [comment]
#11003 😁
