### ISSUE TITLE
Observations on the EVP_MAC API

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11007]
On converting some legacy code that was using the CMAC and HMAC APIs to use EVP_MAC instead I noticed some aspects about the API design that made the experience of conversion harder than it perhaps should have been. Or possibly these things were deliberate design decisions, in which case it would be interesting to know what the justification was:

- init/update/final naming inconsistencies. For CMAC and HMAC we have CMAC_Update and HMAC_Update. Other EVP update functions are called things like EVP_SignUpdate, EVP_VerifyUpdate, EVP_OpenUpdate, EVP_SealUpdate, EVP_DigestUpdate, EVP_CipherUpdate. But for EVP_MAC it is called EVP_MAC_update. Note the use of lower case. The use of the underscore is possibly justifiable since that's what the old MAC APIs used (but we don't do that for other EVP APIs). There are similar inconsistencies with the init/final names.

- Initialising an EVP_MAC_CTX is a three step process:
    - Create the EVP_MAC_CTX using EVP_MAC_CTX_new
    - Set parameters on it using EVP_MAC_CTX_set_params
    - Initialise it using EVP_MAC_CTX_init

Previously for old MAC APIs it was a two step process: Create it, initialise it. There seems no reason to have the EVP_MAC_CTX_set_params step...it could be combined with the init.

- There is no way to "reset" an EVP_MAC_CTX. They seem to be a one use thing, meaning if you are doing a repeated series of MAC operations you have to create a new EVP_MAC_CTX for each one. Previously, with the low level APIs, you could create a ctx, and the call "reset" when you had finished, so you could reuse it.

- The HMAC and CMAC low level APIs provide HMAC_CTX_copy() and CMAC_CTX_copy() functions, but there is no "dup" equivalent. By contrast there is an EVP_MAC_CTX_dup(), but not an EVP_MAC_CTX_copy(). This just adds some extra complexity to the conversion process.

**Comment by levitte** [comment]
Regarding CamelCase vs lowercase_with_underscore, we really have a mixed bag. The `EVP_PKEY` interface is the latter for the most part (it's arguable if `EVP_DigestSign` is primarily an `EVP_MD` interface or an `EVP_PKEY` one). The EVP_MAC follows the lowercase_with_underscore model, I don't see that it's more or less wrong than the other (except I personally find CamelCase distasteful, but that's just me).

Regarding setting params, there were definitely diverse controls you could set, as part of the EVP_PKEY implementations. 

As I remember it, not having a reset function was a deliberate choice. A reset would be a wipe anyway, so the use of reusing the ctx is questionable in my mind. 

I did have a copy function at some point, but it was argued that dup would be better for new APIs, so I went along with that. It *is* less risky, 'cause the function knows for sure that the memory area it copies to has the right size.

**Comment by levitte** [comment]
Something to be noted regarding reset functions: before 1.1.0, almost all structures were open, which made it possible to have them stack allocated. In that case, the use for a reset function is much more tangible since there is no other way to "start over". That benefit isn't as tangible with heap allocated structures.

A reset function could mean slightly better performance, still, so even though sceptical, I'm not opposed to adding it if that's what people want.

**Comment by t8m** [comment]
Why do we need explicit reset function. Shouldn't it be possible to reuse the CTX if just another Init was called on it?

**Comment by levitte** [comment]
Not necessarily. You have no idea what one init leaves around for the next to misunderstand.
The low level implementations are sometimes wildly different in their behaviour, and those different behaviours were probably desirable at some point. Then, you have to remember that they are still public APIs, even though deprecated, so sudden changes are not desirable.

**Comment by mattcaswell** [comment]
> A reset function could mean slightly better performance, still, so even though sceptical, I'm not opposed to adding it if that's what people want.

I am somewhat minded to have one if for no other reason that it makes conversion from old to new easier.

**Comment by mattcaswell** [comment]
> I don't see that it's more or less wrong than the other (except I personally find CamelCase distasteful, but that's just me).

Only that where converting existing code you expect to use an upper case "U" because that what you used in the original code. It's not wrong as it is now. But I found it surprising and slightly irritating.

**Comment by mattcaswell** [comment]
> Regarding setting params, there were definitely diverse controls you could set, as part of the EVP_PKEY implementations.

There seems no reason why we couldn't set the params as part of the init. I'm not really sure of the advantage of having a separate call for it.

**Comment by levitte** [comment]
> There seems no reason why we couldn't set the params as part of the init. I'm not really sure of the advantage of having a separate call for it.

I frankly don't understand why we should?  They are optional, and correspond to what you set with `EVP_PKEY_CTX_ctrl_str` with the old `EVP_PKEY_METHOD` interface.

Maybe you're thinking of the underlying algorithm, that you always have to give that with HMAC and CMAC, making that particular parameter not so optional after all?  But then, what about BLAKE, KMAC, POLY1305, SIPHASH, all MACs with no selectable underlying algorithm?

Just grepping for `OSSL_MAC_PARAM` in `providers/implementation/macs/*`, I can only see one truly common parameter: `OSSL_MAC_PARAM_KEY`.  However, that one already has a history of being an option, given with `-macopt`...  so yeah, that one could be an argument for init, but then comes the question, should we spacial case a `-macopt` called `key`?  Why?

**Comment by paulidale** [comment]
I think we'd want to keep the set params call for consistency.

I'd don't have a problem adding an OSSL_PARAM array as an argument to init.  It would simplify using these a little.  Likewise, passing the key would make sense but history makes this nasty.

Often more than just the algorithm is settable, so the three stage sequence applies more widely than CMAC and HMAC.

**Comment by mattcaswell** [comment]
> Just grepping for OSSL_MAC_PARAM in providers/implementation/macs/*, I can only see one truly common parameter: OSSL_MAC_PARAM_KEY. However, that one already has a history of being an option, given with -macopt... so yeah, that one could be an argument for init, but then comes the question, should we special case a -macopt called key? Why?

I wasn't thinking of special casing any particular option. But rather make the passing of parameters generally part of the init function's job, e.g.:

````
EVP_MAC_init(EVP_MAC_CTX *ctx, const OSSL_PARAM *params);
````

**Comment by levitte** [comment]
> But rather make the passing of parameters generally part of the init function's job

This deviates from the previous model, where parameters could be passed piece meal, as it pleases the application.  Doing what you ask forces the application to collect them as they get parsed from whatever, and if there are no parameters to pass, pass an explicit NULL.  That's additional work for the application, and I thought that we previously agreed that having to pass that NULL was ugly and undesirable.

Example applications that parse all kinds of parameters and pass them on piece meal:

- `test/evp_test.c` (doing what you propose will deeply affect that program)
- Some of the `openssl` sub-commands (interestingly enough, we use different models depending on the sub-command...  for example, the diverse `pkey` sub-commands pass the diverse options on the fly as they find them on the command line, while the `dgst` sub-command collects them and passes them in one go)

As a matter of fact, we get the same kind of issue within libcrypto, where any legacy ctrl function will suddenly have to collect the control values until init is called ('pkey_mac.c` will need quite a rewrite).

I suspect that model change will be more disruptive than it's worth.

**Comment by paulidale** [comment]
Having the option to pass parameters to the init function does not preclude having a set_params function as well.  I already mentioned that we should keep the set_params.

**Comment by levitte** [comment]
Are we going to do that across the board? For example EVP_KDF? Older EVP APIs? I see no reason to do this *only* for EVP_MAC.

**Comment by paulidale** [comment]
What about doing it for algorithm families where the PARAMs are essential?
I.e. MAC and KDF.

It does introduce an inconsistency in the APIs though.

**Comment by mattcaswell** [comment]
> What about doing it for algorithm families where the PARAMs are essential?
I.e. MAC and KDF.

I'd support that

> It does introduce an inconsistency in the APIs though.

This doesn't worry me too much.

**Comment by levitte** [comment]
> This doesn't worry me too much.

It does worry me.  We already have a somewhat disparate collection of APIs in this regard, do we really want to add on more of that, or do we want better uniformity (in so far that we can without bending over backwards)

**Comment by paulidale** [comment]
We **need** a set params call even if they are passed to init.

For an unknown algorithm, querying the size of e.g. the _key_ needs to be done **before** it can be set.

BTW: I know we can't do this currently, the only query is the _output size_.

**Comment by paulidale** [comment]
One thing that would make sense would be to move the key from a params to the derive call:

1. Reuse is not allowed, so there is no sense keeping it.
1. It's used for every MAC so making it easier to pass helps.
1. It's a blob of binary data, so none of the params typing is necessary.

**Comment by levitte** [comment]
I agree that the key could move away from params to the init call (uhmmmm not the derive call, unless you're talking EVP_KDF).  The `openssl mac` application should change accordingly, i.e. not take the key as a `-macopt`, but have its very own command line option (`-key`?).

The key as a `-macopt` was derived from how it's done using `openssl dgst`, but that caters to the EVP_PKEY_METHOD interface, and transferring the MAC key to the same type of parameter was thoughtless.

So yeah, making the key an argument for `EVP_MAC_init()` is something I can agree with.

**Comment by paulidale** [comment]
> I agree that the key could move away from params to the init call (uhmmmm not the derive call, unless you're talking EVP_KDF).

Yes, the init call.  MAC's don't have a derive of course.

KDF's have no parameter consistency, so this wouldn't be suitable for them.  In theory we could merge some of the KDF parameters so they all accepted something similar for the init or derive but it would cause more harm that good in my opinion.


Pauli

**Comment by ozppupbg** [comment]
I would also appreciate to be able to pass the key as an argument to the init/derive function.

Also, I'd like to point out something, which seems not to be consistent in all cases right now:
If I set a parameter via a set CTX call, I would expect it to be persistent across multiple init calls, because it is usually set before the call to init.
Is there any guideline, how parameters should be used or handled internally?

**Comment by paulidale** [comment]
Need to define the semantics of the EVP_MAC APIs (and all other algorithms using the init/update/final sequence).
Attempt to programmatically enforce the call flows (at the EVP layer)?

Allow init to be called after a final, it should reset to the state that was present in the previous init call.

**Comment by paulidale** [comment]
Refer to #8363

**Comment by kroeckx** [comment]
I would like an API where at least some of the settings can not be changed after creation. For instance, once you've selected HMAC with SHA256, you should not be able to change that to HMAC with SHA1. But you might want to reuse the same EVP_MAX_CTX object with a different key. I think there are changes to an object that we should not allow once it's setup up, since in general it complicates things, and make error handling very hard. For instance, I would like to avoid any malloc in EVP_MAC_CTX_set_params().

I think that if we want HMAC with SHA256, we should actually be saying that in the EVP_MAC_fetch() call. As I understand it, we want the combination of those 2 from the same provider, and we might end up with a provider that does HMAC but doesn't support the digest. The fetch call should known enough to make sure that it's possible to set it up. I suggest we change EVP_MAC_fetch() so that it can return an object that's setup up for HMAC with SHA256. This would also allow to get a complete list of all parameters you can set for the combination of algorithms that are used.

**Comment by levitte** [comment]
> I would like an API where at least some of the settings can not be changed after creation. For instance, once you've selected HMAC with SHA256, you should not be able to change that to HMAC with SHA1. But you might want to reuse the same EVP_MAX_CTX object with a different key. I think there are changes to an object that we should not allow once it's setup up, since in general it complicates things, and make error handling very hard. For instance, I would like to avoid any malloc in EVP_MAC_CTX_set_params().

There's a difference between *creating* the EVP_MAC_CTX and *initializing* the MAC operation.  I would agree that after init, there should be no changes.

> I think that if we want HMAC with SHA256, we should actually be saying that in the EVP_MAC_fetch() call.

That a big change.  Should we have that just for MACs (I assume that we should do the same with CMAC, then), or are you thinking bigger?  Things like "sha256WithRSAEncryption" for a signature algorithm come to mind.  I believe we did talk about something like that at some point, but chose not to go that route, among others because it would make EVP_DigestSignInit_ex() so much more complex.

> As I understand it, we want the combination of those 2 from the same provider

What actually happens is that the hash name is passed to the provided implementation, and it does whatever it wants with that information.  The idea is that the provider code knows best what it supports and how.  *Our* HMAC provider code simply fetches the hash with `EVP_MD_fetch()`, which works within the same provider, but *other* providers will choose whatever implementation they have access to, which might be something entirely different.

> and we might end up with a provider that does HMAC but doesn't support the digest.

Yes?  So when we try to set that parameter and they recognise the parameter key, they can return an error.  Or their init function might return an error.

> The fetch call should known enough to make sure that it's possible to set it up. I suggest we change EVP_MAC_fetch() so that it can return an object that's setup up for HMAC with SHA256. This would also allow to get a complete list of all parameters you can set for the combination of algorithms that are used.

Like I said, that's a paradigm shift.

**Comment by kroeckx** [comment]
> There's a difference between *creating* the EVP_MAC_CTX and *initializing* the MAC operation.  I would agree that after init, there should be no changes.

I'm not sure what you mean with initializing. If you mean
that after EVP_MAC_init() you're not allowed to call
EVP_MAC_CTX_set_params(), I think that point is already too late.
In case of HMAC, if you called EVP_MAC_CTX_set_params() to set the
digest, you should not be allowed to change the digest.

And we have documentation that says you can call
EVP_MAC_CTX_set_params() just before the EVP_MAC_final() call.

> > I think that if we want HMAC with SHA256, we should actually be saying that in the EVP_MAC_fetch() call.
> 
> That a big change.  Should we have that just for MACs (I assume that we should do the same with CMAC, then), or are you thinking bigger?  Things like "sha256WithRSAEncryption" for a signature algorithm come to mind.  I believe we did talk about something like that at some point, but chose not to go that route, among others because it would make EVP_DigestSignInit_ex() so much more complex.

It was really a general suggestion, over all APIs that got
introduced.

> > As I understand it, we want the combination of those 2 from the same provider
> 
> What actually happens is that the hash name is passed to the provided implementation, and it does whatever it wants with that information.  The idea is that the provider code knows best what it supports and how.  *Our* HMAC provider code simply fetches the hash with `EVP_MD_fetch()`, which works within the same provider, but *other* providers will choose whatever implementation they have access to, which might be something entirely different.

I guess there are cases where you want both in the same provider,
and other cases where it's not important.

**Comment by t8m** [comment]
We should not do such paradigm shifts at this point. As we can see the provider interface for 3.0 will definitely not be perfect but IMO we should accept that as a fact and defer any of those to the eventual 4.0 version.

**Comment by levitte** [comment]
> I guess there are cases where you want both in the same provider, and other cases where it's not important.

We did decide early on that a provider must be self-sufficient and self-contained.  We do not offer any fetching upcall over the libcrypto\<-\>provider interface.

**Comment by paulidale** [comment]
There are a number of questions about how we would like the APIs to look going forward.  The calls are described in reference to the EVP_MAC API but would be applicable more widely.  Any decisions will only change newly introduced calls (EVP_MAC and EVP_KDF).  However, they would represent the direction the project would like to take with respects to function nomenclature.

1. What should the nomenclature for `EVP_MAC_init`, `EVP_MAC_update`, `EVP_MAC_final` be? _(This also applies to KDFs)_
- Left as they currently are.
- Camel case without underscore (`EVP_MACUpdate`) to match the rest of EVP?
            `EVP_SignUpdate`, `EVP_VerifyUpdate`, `EVP_OpenUpdate`, `EVP_SealUpdate`,
            `EVP_DigestUpdate`, `EVP_CipherUpdate`
- Camel case with underscore (`EVP_MAC_Update`) to match existing low level calls?
            `CMAC_Update`, `HMAC_Update`

2. Should an optional OSSL_PARAM array be included in the init call? _(This also applies to KDFs and potentially more generally)_
- Initialising `EVP_MAC_CTX` requires an additional call beyond what used to be required.  The sequence is now: `EVP_MAC_CTX_new`, `EVP_MAC_CTX_set_params`, `EVP_MAC_CTX_init`, the low level calls are _new_ then _init_.
- Doing this does **not** remove the need for the `EVP_MAC_CTX_set_params` call.

2.5. Should the `EVP_MAC_CTX_init` accept a _key_ argument?
- Currently it is specified as a OSSL_PARAM
- All MACs always require a key, it is mandatory
- The key should never reused
- It's a blob of binary data that isn't getting much benefit from OSSL_PARAM typing

3. Should there be an `EVP_MAC_CTX_reset`?  _(This applies more generally)_
- What state should it reset to?
- Could the `EVP_MAC_CTX_init` call be used as the reset?  The different MACs behave differently with respect to what is reset.
- Not including a reset call was deliberate, there was a PR by Shane that was rejected.

4. Do we want an `EVP_MAC_CTX_copy` function?  _(This applies more generally)_
- The low level APIs are `HMAC_CTX_copy` and `CMAC_CTX_copy`
- The high level API is `EVP_MAC_CTX_dup`
- The EVP_MAC_CTX objects need not be from the same provider which means de-allocation and reallocation.
- Proposed vote text: _The `EVP_xxx_CTX types` should support an `EVP_xxx_CTX_dup` call but not an `EVP_xxx_CTX_copy` call._

**Comment by paulidale** [comment]
Resolutions:

1. leave the function names as they are.  Migrate existing names of the other forms over time -- post 3.0 is acceptable.
2. An OSSL_PARAM call should be included in all _init_ calls.
2.5. Add _key_ and _key length_ arguments to the MAC init function.
3. Do not support _reset_ operations.  Existing calls do not need to be removed in the 3.0 time frame.
4. Do not support _copy_ operations.  Existing calls do not need to be removed in the 3.0 time frame.

**Comment by t8m** [comment]
>     2\. An OSSL_PARAM call should be included in all _init_ calls.

OSSL_PARAM parameter should be included in all _init_ calls.

**Comment by paulidale** [comment]
The MAC portion of the _init call updates is in #14310

**Comment by paulidale** [comment]
For the remaining algorithms, it doesn't look like it makes sense to make similar changes:
1. digests and ciphers are pre-existing APIs so new calls would have to be introduced which take a params argument.  Given how few params these take, it doesn't seem worthwhile.
2. New PKEY pieces (signature, exchange, ...) don't expose set_params calls directly.  The PKEY calls that invoke them are pre-existing and deal with the various details.  Again, it doesn't seem worthwhile.
3. Encode/decode could accept params as an argument to the OSSL_ENCODER_CTX_new_for_pkey() call but it seems out of place.

When/if we update the names of the existing APIs, it might make sense to add params at that point.

**Comment by mattcaswell** [comment]
@paulidale #14310 was merged. So is there anything left do with this issue? Or can it be closed now?

**Comment by paulidale** [comment]
I think it can be closed.
