### ISSUE TITLE
Superfluid padding bytes in EVP_EncryptFinal_ex

### ISSUE THREAD

**Issue by FaberFlorian** [openssl/openssl#11008]
I noticed that with padding enabled (=default), EVL_EncryptFinal_ex (in openssl-1.1.1d) produces superfluid padding bytes whenever the amount of encrypted data ends exactly on the block boundary (example with aes-256-cbc, which has a blocksize of 16 bytes):

```
0x0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  The quick brown 
0x0010  10 10 10 10 10 10 10 10  10 10 10 10 10 10 10 10  ................
```

```
0x0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  The quick brown 
0x0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  fox jumps over t
0x0020  10 10 10 10 10 10 10 10  10 10 10 10 10 10 10 10  ................
```

The following patch might not be the most elegant, but it fixes that issue:

```
diff -uNr openssl-1.1.1d_orig/crypto/evp/evp_enc.c openssl-1.1.1d/crypto/evp/evp_enc.c
--- openssl-1.1.1d_orig/crypto/evp/evp_enc.c	2019-09-10 15:13:07.000000000 +0200
+++ openssl-1.1.1d/crypto/evp/evp_enc.c	2020-01-30 10:35:29.142383956 +0100
@@ -429,14 +429,18 @@
         return 1;
     }
 
-    n = b - bl;
-    for (i = bl; i < b; i++)
+    n = (b - bl) % b;
+    if (n > 0) {
+      for (i = bl; i < b; i++)
         ctx->buf[i] = n;
-    ret = ctx->cipher->do_cipher(ctx, out, ctx->buf, b);
-
-    if (ret)
+      ret = ctx->cipher->do_cipher(ctx, out, ctx->buf, b);
+      
+      if (ret)
         *outl = b;
-
+    } else {
+      *outl = 0;
+    }
+    
     return ret;
 }
 ```

**Comment by levitte** [comment]
That "superfluid" padding is PKCS#5 compatible, just extended for more-than-8-byte blocks. The original padding length is:

  8 - (length(*M*) mod 8)

For 16-byte blocks, that becomes:

  16 - (length(*M*) mod 16)

https://tools.ietf.org/html/rfc8018#section-6

**Comment by rwfranks** [comment]
s/superfluid/superfluous/

**Comment by levitte** [comment]
Ah !
Either way, my answer remains the same.

**Comment by rwfranks** [comment]
Conjured a vision of bytes flowing up the walls!

**Comment by mattcaswell** [comment]
The current behaviour is the correct PKCS5 behaviour. Padding bytes *always* exist if PKCS5 padding is in use. The smallest amount of padding you can have is one byte. Closing this.
