### ISSUE TITLE
Minor EVP_MD_CTX_ctrl regression in master

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#11002]
In pre-3.0.0 times it was possible to use custom ctrl command values at least for digests. Now EVP_MD_CTX_ctrl checks against known values (

openssl/crypto/evp/digest.c

Lines 671 to 687 in 7b131de
```
 switch (cmd) { 
 case EVP_MD_CTRL_XOF_LEN: 
     sz = (size_t)p1; 
     params[0] = OSSL_PARAM_construct_size_t(OSSL_DIGEST_PARAM_XOFLEN, &sz); 
     break; 
 case EVP_MD_CTRL_MICALG: 
     set_params = 0; 
     params[0] = OSSL_PARAM_construct_utf8_string(OSSL_DIGEST_PARAM_MICALG, 
                                                  p2, p1 ? p1 : 9999); 
     break; 
 case EVP_CTRL_SSL3_MASTER_SECRET: 
     params[0] = OSSL_PARAM_construct_octet_string(OSSL_DIGEST_PARAM_SSL3_MS, 
                                                   p2, p1); 
     break; 
 default: 
     goto conclude; 
 }
``` 
) and then returns an error.
It's not critical regression but it's still a regression. If it's the desired behavior, I can live with it.

Previous fix (#10916) was reverted in #10989 because of Travis failures in extended tests.
I can fix my engine to avoid this particular pitfall but I think it is as a matter of policy. If we think this is a neglectable regression, we should write about it in Changes. Otherwise, we should fix it.

**Comment by levitte** [comment]
I believe that the major thing that causes this regression is the check done before the switch:

https://github.com/openssl/openssl/blob/5a8848fa7fec532fee30fd6131a3ebd59a5c5902/crypto/evp/digest.c#L665-L669

I can't see why it couldn't be reduced to:

``` C
    if (ctx->digest->prov == NULL)
        goto legacy;
```

@beldmit, would you mind trying that change?

**Comment by levitte** [comment]
Oh wait...  incidently, that change is already implemented, in #10947, and is only a merge away.  Just wait 12 more hours :wink:

**Comment by beldmit** [comment]
Will try after merge.

**Comment by beldmit** [comment]
Works for me. Thanks!
