### ISSUE TITLE
BIO_new_file has an unitialized read

### ISSUE THREAD

**Issue by bsdinis** [openssl/openssl#11013]
On OpenSSL 1.1.0 (default on Fedora 30), the function `BIO_new_file` has an unitialized read of a variable.

This was found while running *client code* with clang's memory sanitizer.

(This also begs the question of whether the code is being tested with these sanitizers - it probably isn't and probably should - but that is another issue)

The high level API called was `OPENSSL_init_ssl`;
I did not evaluate whether there is any security impact. However, when dealing with UB, anything goes.

**Comment by mattcaswell** [comment]
> On OpenSSL 1.1.0 (default on Fedora 30), the function BIO_new_file has an unitialized read of a variable.

Which variable? Looking at the code I can't see any obvious place where that is the case.

1.1.0 is old and out of support. It's possible that this has already been fixed...although I looked at the old 1.1.0 code and couldn't see an obvious place there either where this could occur.

> (This also begs the question of whether the code is being tested with these sanitizers - it probably isn't and probably should - but that is another issue)

We regularly run our full test suite with various sanitizers enabled.

**Comment by BSDinis** [comment]
Hi,

I inspected the code, and in fact couldn't find the variable.
It seems to me a hard bug to track (or maybe not a bug at all).

The library call didn't have any input, so it certainly wasn't any misuse on my part.

I understand that 1.1.0 is old, but it is widespread...

**Comment by levitte** [comment]
1.1.0 is past end of life, so we won't target that.
However, it's quite possible that the bug remains in 1.1.1 or even in the master branch, so still worth looking into. 

That being said, it's quite difficult to figure out with so very little specifics, I'm sure you understand, so I wonder if you have some small piece of code that you know triggers this error when built with ub sanitizer?

**Comment by ivan2kh** [comment]
You need to build instrumented openssl version like shown here: https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo

**Comment by t8m** [comment]
> On OpenSSL 1.1.0 (default on Fedora 30), the function `BIO_new_file` has an unitialized read of a variable.

That is not true. There was OpenSSL-1.1.1b in Fedora 30 release and there is OpenSSL-1.1.1d in the Fedora 30 updates. There is no OpenSSL-1.1.0 in Fedora 30.

**Comment by BSDinis** [comment]
@t8m You're right, I must have read this wrong.
That would mean that this happens on th 1.1.1 version

**Comment by t8m** [comment]
I am closing this as you need fully instrumented builds to be able to use the memory sanitizer.
