### ISSUE TITLE
is the following planned for 1.0.2 branch ?

### ISSUE THREAD

**Issue by chipitsine** [openssl/openssl#11016]
hello,

I observe that openssl-1.0.2 still does not include https://github.com/openssl/openssl/commit/e9d26dc85238c071117d911704f5f769e79b46a1

(branches 1.1.0 and 1.1.1 do include).

are there any plans to backport that to 1.0.2 ?

we encountered that openssl-1.0.2 behaves in different way https://github.com/haproxy/haproxy/issues/429

**Comment by beldmit** [comment]
I'm afraid not. The 1.0.2 branch is out of support since December 2019
