### ISSUE TITLE
Invalid read in fmtstr() with precision and non-terminated string

### ISSUE THREAD

**Issue by bester** [openssl/openssl#1101]
In BIO_snprintf, fmtstr() calls strlen(value) unconditionally. 

If the value string is non-terminated, this will read further in the array than the caller expected. This could affect padding in the output, or even result in crashes. 

The attached example shows how padding can be affected by this bug. The two output lines are expected to be the same.

[bad-BIO_snprintf.c.txt](https://github.com/openssl/openssl/files/275271/bad-BIO_snprintf.c.txt)

.

**Comment by richsalz** [comment]
It's a C string and must be NUL-terminated.

**Comment by bester** [comment]
Even if it's terminated (like the example) you can get incorrect results.

**Comment by levitte** [comment]
I just ran the test program, and yeah, the result isn't correct.

**Comment by levitte** [comment]
PR #1104 contains a fix, please try it out.

**Comment by levitte** [comment]
#1104 has now made it to master.  This issue considered fixed, I'm closing it.
