### ISSUE TITLE
Extremely rare segfault

### ISSUE THREAD

**Issue by kreuzerkrieg** [openssl/openssl#11012]
Once in a while (really rarely) I get something like this

> 0x563aa8be2ccd large_dalloc /root/project/obj-x86_64-linux-gnu/../contrib/jemalloc/include/jemalloc/internal/atomic.h:55
> 0x563aa8bd52b2 free /root/project/obj-x86_64-linux-gnu/../contrib/jemalloc/src/jemalloc.c:2689
> 0x563aae801df5 recallocarray /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/compat/recallocarray.c:80
> 0x563aae79986f BUF_MEM_grow_clean /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/buffer/buffer.c:121
> 0x563aae7d9136 PEM_read_bio /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/pem/pem_lib.c:724
> 0x563aae84d4bd PEM_X509_INFO_read_bio /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/pem/pem_info.c:124
> 0x563aae7eb069 X509_load_cert_crl_file /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/x509/by_file.c:252
>  0x563aae7eb19a by_file_ctrl /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/x509/by_file.c:118
>  0x563aae7ec378 X509_STORE_load_locations /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/x509/x509_d2.c:96
>  0x563aadf85e85 ossl_connect_step1 /root/project/contrib/curl/lib/vtls/openssl.c:2343
>  0x563aadf88c7e ossl_connect_common /root/project/contrib/curl/lib/vtls/openssl.c:3287
>  0x563aadf5ac37 Curl_ssl_connect_nonblocking /root/project/contrib/curl/lib/vtls/vtls.c:273
>  0x563aadf5fbf2 https_connecting /root/project/contrib/curl/lib/http.c:1393
>  0x563aadf66a46 Curl_protocol_connect /root/project/contrib/curl/lib/url.c:1652
>  0x563aadf4c036 multi_runsingle /root/project/contrib/curl/lib/multi.c:1573
>  0x563aadf4cf84 curl_multi_perform /root/project/contrib/curl/lib/sigpipe.h:66
>  0x563aadf46dd4 curl_easy_perform /root/project/contrib/curl/lib/easy.c:699
>  0x563aadee71ab Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::shared_ptr<Aws::Http::Standard::StandardHttpRespo
>  0x563aadee91c1 Aws::Http::CurlHttpClient::MakeRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInte
>  0x563aadec2a35 Aws::Client::AWSClient::AttemptOneRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::AmazonWebServiceRequest const&,
>  0x563aadec3150 Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod,
>  0x563aadec408b Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char

Is there any know issue with openssl that looks similar? 

OS - Ubuntu 18.04
OpenSSL 1.1.1 11 Sep 2018

**Comment by t8m** [comment]
Unfortunately there is not much we can do with such bug report. It is also fairly specific build configuration as jemalloc is used as the malloc implementation here.
