### ISSUE TITLE
OpenSSL1.1.1d Minimum compatible glibc version

### ISSUE THREAD

**Issue by HemanthApte** [openssl/openssl#11026]
Hello All,
Which is the minimum compatible glibc version to be used with OpenSSL1.1.1d version?

Currently i am using GNU Kernel 2.6.31 and GCC version is 4.4.3.

Is it v2.17? 

I am getting errors while using glibc 2.10 as explained in https://github.com/openssl/openssl/issues/10969.

thanks in advance,
regards,
Hemanth.

**Comment by petrovr** [comment]
I would like to confirm that 1.1.1 stable branch builds and pass regression tests on:
$ uname -a
Linux centos_510 2.6.18-419.el5 ...
$ gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55)
$ ldd --version
ldd (GNU libc) 2.5

Optionally with [--with-rand-seed=devrandom] [zlib]

**Comment by kroeckx** [comment]
I don't know about any glibc version requirements. However, with
newer glibc versions we will use new features.

**Comment by HemanthApte** [comment]
Thank you petrovr for the details.  Thank you kroeckx for the reply..!!
