### ISSUE TITLE
Stop using SHA1 as default digest

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#11028]
Now that SHA1 has been banned from security level 1 in #10786 it is time to consider the places where SHA1 is still used as default digest. The following list was simply collected by skimming through the documentation. It might not be complete and it might not be accurate.

**~/src/openssl$ git grep -nE -C 1 'SHA-?1' doc/ | grep default**

https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-cms.pod.in#L289-L290
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-ocsp.pod.in#L268-L271
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-pkcs12.pod.in#L315-L320
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-pkeyutl.pod.in#L286-L288
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-pkeyutl.pod.in#L297-L299
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-smime.pod.in#L164-L165
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-x509.pod.in#L124-L126
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man3/CMS_sign.pod#L88-L89
https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man3/PKCS7_sign.pod#L76-L77

_(This SHA1 grep hit in openssl-pkcs12 is of a different nature, but I included it here for completeness.)_

**Comment by mspncp** [comment]
Some of the references might be only documenation issues, like this one here:

https://github.com/openssl/openssl/blob/f11f86f6ec7fb31bde1da2810ac975c032205321/doc/man1/openssl-cms.pod.in#L289-L290

**Comment by noloader** [comment]
Be careful of outright banning of SHA-1. I seem to recall GnuPG and GnuTLS moved on a ban, and then had to back-off because so much stuff in the field broke. At least that's what it looked like to me based on package updates that occurred about a week apart.

Anywhere you ban SSHA-1 you will need to provide a userland override or command option to re-enable it.

**Comment by mspncp** [comment]
We are not planning to remove SHA1 any time in the near future. Even MD5 is still available. We are only changing the default digest, because OpenSSL should be "secure by default". Same holds for pull request #10786: the SHA1 ciphers were not removed, only downgraded to SECLEVEL zero.

**Comment by paulidale** [comment]
Some things mandate SHA-1 as their default.  We can't change those so easily.

Although, not mentioned above pbkdf2 defaults to SHA-1 as does the TLS PRF.  Both of these cases should be safe for the foreseeable future.

**Comment by DDvO** [comment]
`doc/man3/SSL_CTX_set_security_level.pod` still says:

> **WARNING** at this time setting the security level higher than 1 for
> general internet use is likely to cause B<considerable> interoperability
> issues and is not recommended. This is because the B<SHA1> algorithm
> is very widely used in certificates and will be rejected at levels
> higher than 1 because it only offers 80 bits of security.

This should be updated since meanwhile SHA1 is attributed only 63 bits of security.

BTW, the above quotes remark is easily overlooked when checking the info on security levels regarding acceptance of SHA1.
Please state directly for level 1 that it prohibits SHA1 as a digest algorithm for signatures.

**Comment by DDvO** [comment]
Looks like this needs further attention.

**Comment by mattcaswell** [comment]
> doc/man3/SSL_CTX_set_security_level.pod still says:

Fixed by #12444

**Comment by DDvO** [comment]
Nice that the outdated and thus misleading remark about SHA1 and security level 1 has been removed from `SSL_CTX_set_security_level`.

Yet SHA1 is still mentioned there with level 4, while I suppose it would be helpful for users to mention that 
SHA1 is not any more acceptable as signature digest algorithm for any security level above 0.

**Comment by DDvO** [comment]
Since the docs meanwhile says for Level 4:
Cipher suites using SHA1 for the MAC are prohibited.

I believe this can be closed.
