### ISSUE TITLE
Capi engine doesn't list any certificate

### ISSUE THREAD

**Issue by martinscholz83** [openssl/openssl#11032]
I'm trying to use the openssl capi engine to load keys from windows store. When i call `ENGINE_load_private_key` from source code, key is always `NULL`. Also when trying from command line I'm getting no result.
```
.\openssl.exe engine dynamic -pre ID:capi -pre DIR_LOAD:2 -pre DIR_ADD:. -pre LIST_ADD:1 -pre LOAD  -post list_certs

(dynamic) Dynamic engine loading support
[Success]: ID:capi
[Success]: DIR_LOAD:2
[Success]: DIR_ADD:.
[Success]: LIST_ADD:1
[Success]: LOAD
Loaded: (capi) CryptoAPI ENGINE
 [RSA, DSA]
```
But when i add a `-t` to the command, then i get my certs listed
```
.\openssl.exe engine dynamic -t -pre ID:capi -pre DIR_LOAD:2 -pre DIR_ADD:. -pre LIST_ADD:1 -pre LOAD  -post list_certs

(dynamic) Dynamic engine loading support
[Success]: ID:capi
[Success]: DIR_LOAD:2
[Success]: DIR_ADD:.
[Success]: LIST_ADD:1
[Success]: LOAD
Loaded: (capi) CryptoAPI ENGINE
     [ available ]
Certificate 0
  <No Friendly Name>
  Subject: DC = com, DC = blah, CN = Users, CN = Administrator
  Issuer: DC = com, DC = blah, CN = blah-martin-VSRV-MER-MCSM2-CA-1
Certificate 1
  <No Friendly Name>
  Subject: DC = com, DC = adfs-test, CN = Users, CN = Administrator
  Issuer: DC = com, DC = adfs-test, CN = adfs-test-ADFSDC-CA
Certificate 2
  <No Friendly Name>
  Subject: DC = com, DC = adfs-test, CN = Users, CN = sam_test840
  Issuer: DC = com, DC = adfs-test, CN = adfs-test-ADFSDC-CA
Certificate 3
  <No Friendly Name>
  Subject: DC = com, DC = adfs-test, CN = Users, CN = Administrator
  Issuer: DC = com, DC = adfs-test, CN = adfs-test-ADFSDC-CA
Certificate 4
  <No Friendly Name>
  Subject: DC = com, DC = adfs-test, CN = Users, CN = Administrator
  Issuer: DC = com, DC = adfs-test, CN = adfs-test-ADFSDC-CA
Certificate 5
  Friendly Name "CMS2019"
  Subject: CN = CMS2019
  Issuer: CN = CMS2019
Certificate 6
  <No Friendly Name>
  Subject: DC = com, DC = adfs-test, CN = Users, CN = Administrator
  Issuer: DC = com, DC = adfs-test, CN = adfs-test-ADFSDC-CA
Certificate 7
  <No Friendly Name>
  Subject: DC = com, DC = vsecdev-martin, CN = Users, CN = Administrator
  Issuer: DC = com, DC = vsecdev-martin, CN = vsecdev-martin-VSRV-MER-MCSM2-CA-1
[Success]: list_certs
```

Am I missing something when trying to load private key? I'm using the subject name of the certificate. But when looking at [here](https://github.com/openssl/openssl/blob/master/engines/e_capi.c#L1552), it seems you don't support `subject` when loading a private key?

**Comment by levitte** [comment]
We do support substring of subject. That's actually the default, the lookup method `CAPI_LU_SUBSTR`. What happens with it is subject to how [`CertFindCertificateInStore()`](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certfindcertificateinstore) behaves.

Regarding the two runs of `openssl engine`, the `-post` control commands are only run when `-t` or `-tt` have been given. Since `list_cert` is a post control command...

**Comment by martinscholz83** [comment]
In detail i want to use the support for openssl engine in `gRPC`. See [here](https://github.com/grpc/grpc/blob/master/src/core/tsi/ssl_transport_security.cc#L625). But the is always null. Is something missed there?

**Comment by martinscholz83** [comment]
But what about the link i send you for the `capi_find_key` function. That `switch` case just ignore it.

**Comment by levitte** [comment]
Yeah? But it does call `capi_find_cert`, have a look at that one. After that call, it gets the key from the cert...

**Comment by martinscholz83** [comment]
I'm not a C expert, but the first case is empty, or does it means `case CAPI_LU_SUBSTR AND case CAPI_LU_FNAME`?
```C
case CAPI_LU_SUBSTR:
case CAPI_LU_FNAME:
        hstore = capi_open_store(ctx, NULL);
        if (!hstore)
            return NULL;
        cert = capi_find_cert(ctx, id, hstore);
        if (cert) {
            key = capi_get_cert_key(ctx, cert);
            CertFreeCertificateContext(cert);
        }
        CertCloseStore(hstore, 0);
        break;

case CAPI_LU_CONTNAME:
```
If so, i don't know why the key is always empty?

**Comment by levitte** [comment]
Yes, one switch case falls through to the next unless you have a break.

Regarding the key you want to get, I don't know what string you're using with the load_private_key function, so can't do too much to help...

**Comment by martinscholz83** [comment]
Subject is `CN=CMS2019` and i just paste `CMS2019`. But maybe something is wrong with the `gRPC` code.

**Comment by martinscholz83** [comment]
From logs i also can see that gRPC is passing the right value `CMS2019`. But key is though `NULL`. Also tried [this](https://stackoverflow.com/questions/51968387/openssl-and-capi-collisions-in-certificates). But same result. Does the key or the cert has to be special formatted? RSA? 2048, sha256 ??

**Comment by martinscholz83** [comment]
I'm really sorry for wasting your time. But now i got it working. I created another certificate, and now the private key is loading. So something was wrong with the cert or with the key.

**Comment by levitte** [comment]
I'm glad I could help you figure it out!
