### ISSUE TITLE
get_sess_cb never invoked in tls1.3

### ISSUE THREAD

**Issue by daum3ns** [openssl/openssl#11039]
OpenSSL version is 1.1.1d
When reading the docs here: 
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_sess_set_get_cb.html
and here:
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_session_cache_mode.html

I understand it this way: If a server sets SSL_SESS_CACHE_NO_INTERNAL cache mode, the callback set with SSL_CTX_sess_set_get_cb should always be invoked on resumed sessions, because the lookup in the internal cache is disabled, right?

This is the case in TLSv1.2, but not in TLSv1.3.

I have had a look at the code so this is where it is different:
https://github.com/openssl/openssl/blob/894da2fb7ed5d314ee5c2fc9fd2d9b8b74111596/ssl/ssl_sess.c#L509-L546

the callback gets called from the function _lookup_sess_in_cache_, which is, in the case of tls1.3, never executed.. 

Is this behavior intended? If so how can we lookup a tls1.3 session in our own session cache? If so the documentation is wrong. 

Thanks in advance!

**Comment by mattcaswell** [comment]
The `get_session_cb()` is described as follows in the man pages:

> The get_session_cb() is only called on SSL/TLS servers with the session id proposed by the client. The get_session_cb() is always called, also when session caching was disabled. The get_session_cb() is passed the ssl connection, the session id of length length at the memory location data.

In TLSv1.3 there are no session ids defined by the standard and therefore there is nothing to look up in the cache. Instead sessions work more like tickets do in TLSv1.2. The "session" data is wrapped up in an encrypted blob of data (a PSK) and passed back to the client. The client passes this data back to the server during a resumption in the psk extension. The server decrypts it and can therefore resume the session without looking anything up in the session cache. In this way the server can operate entirely statelessly without having to maintain a cache of sessions at all for TLSv1.3 connections.

OpenSSL does  have the capability to "simulate" sessions that work in the old way. By setting the option `SSL_OP_NO_TICKET` on the SSL or SSL_CTX object the server will store the TLSv1.3 session is in the session cache anyway and the "psk" that is passed back to the client is actually the session id. When the client resumes the server will interpret the psk as a session id and `lookup_sess_in_cache` should be invoked.

**Comment by daum3ns** [comment]
thanks a lot for clarification @mattcaswell !
i can confirm that, when setting this option the callback gets invoked. I still see some differences, namely that in TLSv1.3 immediately after the "get-session" callback the "new-session" callback gets invoked as well:

TLSv1.2:
initial request -> new session callback
resumed request -> get session callback

TLSv1.3:
initial request -> new session callback
resumed request -> get session callback immediately followed by new session callback

the SessionID in this two callbacks are different...

**Comment by mattcaswell** [comment]
Right - again the way TLSv1.3 handles sessions is different to the way it used to work in TLSv1.2. In TLSv1.2 a session was created (along with an associated session id) as part of the handshake. You could then reuse that session (potentially multiple times) in resumption connections.

In TLSv1.3 a session for use in a resumption is *not* created during the handshake. Instead *after* the handshake is completed the server sends NewSessionTicket message(s). Each NewSessionTicket message sent by the server represents a different session that could be used during resumption and will have a corresponding call to the "new session" callback. The standard encourages "single use" tickets as an anti-replay mechanism when 0-RTT is in use:

https://tools.ietf.org/html/rfc8446#section-8.1

For this reason implementations may actually issue *multiple* tickets in one go to allow clients to only use each ticket once. How many are issued is implementation dependent. In OpenSSL's case we default to issuing 2 tickets on a new connection (so you should actually see the "new session" callback being called twice in TLSv1.3), and 1 ticket on a resumed connection. So this explains why you see "get session" followed by "new session" in the resumption case.

**Comment by daum3ns** [comment]
ok, thanks.
so in the resumption case, which is the currently active session, the one from the get_sess_cb or the new one? 
do i get this right:  the client resumed a session, this is the currently active session and is the one from the get_sess_cb.  but a new session is created, which can be used by the client later if he wants (and is not active at the moment). 
so the new_sess callback kind of allows me to be able to be prepared for a possible next session..

**Comment by mattcaswell** [comment]
> do i get this right: the client resumed a session, this is the currently active session and is the one from the get_sess_cb. but a new session is created, which can be used by the client later if he wants (and is not active at the moment).
so the new_sess callback kind of allows me to be able to be prepared for a possible next session..

Yes - this is exactly right.
