### ISSUE TITLE
Page missing for x509 documentation

### ISSUE THREAD

**Issue by OmniTroid** [openssl/openssl#11066]
https://www.openssl.org/docs/manmaster/man1/x509.html this page doesn't seem to have any info related to x509 specifically

https://www.openssl.org/docs/manmaster/man1/openssl-x509.html yields a "Page not found".

The online documentation for x509 seems to be missing.

**Comment by mattcaswell** [comment]
For now please look at the 1.1.1 version of these docs:

https://www.openssl.org/docs/man1.1.1/man1/openssl-x509.html

There is a problem in master at the moment (ping @levitte).

**Comment by OmniTroid** [comment]
Thanks. This seems to be a duplicate of https://github.com/openssl/openssl/issues/11050 actually, so I'll just close it.
