### ISSUE TITLE
RISC-V arch support?

### ISSUE THREAD

**Issue by f0rm2l1n** [openssl/openssl#11073]
Hi there, my question is rather simple: Does currently openssl supports **risc-v** cross compile or something?

I did some searching, however, related topics is relatively limited.
- This [forum](https://groups.google.com/a/groups.riscv.org/forum/#!topic/sw-dev/8osjQ8mdeIE) mentioned about it, without an clear answer 💔
- Seems debian team did some [contributions](https://content.riscv.org/wp-content/uploads/2016/07/Wed1115_Working_Towards_a_Debian_RISC-V_Port.pdf) on package porting instead of compiling 😭

If there is not, which files should be concerned if I want to do manually porting? 👀
Thanks a lot.

**Comment by levitte** [comment]
We have no config target for RISC-V, but it's quite possible that adding the necessary data is easy.

If you're targetting Linux on RISC-V, the configuration targets `linux-generic32` and `linux-generic64` should be good enough starting points for RV32 and RV64 respectively, and then you can add on compiler flags and linker flags on the configurations line, like this:

```
./Configure linux-generic64 --cross-compile-prefix=riscv64-unknown-elf- CFLAGS='...' LDFLAGS='....'
```

Failing that form, the older form where you simply add flags directly on the configuration command line and leave it to Configure to figure out what's what (which it often does, but there are corner cases):

```
./Configure linux-generic64 --cross-compile-prefix=riscv64-unknown-elf- -DSOMEMACRO -Wl,-some-linker-flag
```

The `--cross-compile-prefix` is really important when you cross compile, at least using the "traditional" form with a gazillion target specific compilers et al (we have very poor support for clang's native way of specifying the target machine when compiling, for the moment)

**Comment by levitte** [comment]
Please experiment away and tell us what you're going through.  If you find a workable configuration, that could end up in our standard configuration targets.

**Comment by f0rm2l1n** [comment]
> Please experiment away and tell us what you're going through. If you find a workable configuration, that could end up in our standard configuration targets.

Okay, I will try that when free! Really appreciate your reply😄

**Comment by f0rm2l1n** [comment]
Ready for closed this issue 😅
If others want to compile executable openssl elf and run it on spike emulator, it will be fine running
`./Configure linux-generic64 --cross-compile-prefix=riscv64-unknown-linux-gnu- --prefix=...`

Of course you need handle the path problem and blabla, check this (https://github.com/phantom-v/riscv-rss-sdk) out

However, there will be another tiny bothers, I tried my best to run the s_server in the risc-v simulator while problems like below always happens when I wanted to connect to it

```
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
2303800:error:140780E5:SSL routines:SSL23_READ:ssl handshake failure:s23_lib.c:131:
```

I choose the old verions (openssl v1.0.1d) for testing heartbleed bug. Everything is okay when running on host x86-64. I believed a step-by-step debugging shall be required. I mentioned it here for any advice, which is really appreciated. 

Thanks for above answers, thanks a lot ~~

**Comment by levitte** [comment]
Regarding debugging emulated code, I frankly don't know. That being said, I'm glad you could build so easily.

**Comment by adamsir32** [comment]
Hey bro, don't we need to add some system calls to pk if we want to simulate with spike?
