### ISSUE TITLE
Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources

### ISSUE THREAD

**Issue by charsdavy** [openssl/openssl#1108]
I'm attempting to install jekyll and I've encountered an error. I'm running Mac OS X 10.11.4 (El Capitan).
```
$gem install jekyll
ERROR : While executing gem ... (Gem::Exception)
      Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources
$gem source -l
https://ruby.taobao.org
$which openssl
/usr/local/bin/openssl
```
I want to know that how to resolve this error.

**Comment by richsalz** [comment]
Suggest you ask the jekyll support area, this isn't an openssl issue.  To download and install openssl, go https://www.openssl.org
