### ISSUE TITLE
Replacement for deprecated raw DSA functions DSA_do_sign

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#11098]
The raw DSA functions as DSA_do_sign, DSA_do_verify have been deprecated in version 3. Unfortunately (for SSH with the insecure DSA signature algorithm), I do still need a way to access the raw values prior to the ASN encoding. Is this possible with the EVP interface: EVP_DigestSignInit, etc?

**Comment by levitte** [comment]
So if I understand correctly, you want the DSA_SIG, while the result you get from the EVP interface is its DER encoded form.

Is `d2i_DSA_SIG()` good enough for you? You pass it the DER encoded form and you get a DSA_SIG back. I understand it seems a bit backwards, but that's my quick top of my head answer.

**Comment by matbech** [comment]
Thank you. This worked.
