### ISSUE TITLE
Building on aarch64 with fips

### ISSUE THREAD

**Issue by andrewjwarren** [openssl/openssl#11105]
Hello, 

I am trying to build openssl 1.0.2u with fips module (openssl-fips-2.0.16) on a arm64 however, keep getting 
```
FIPS_text_start() returns NULL
make[2]: *** [../Makefile.shared:164: link_app.] Error 1
make[2]: Leaving directory '/home/ubuntu/openssl-1.0.2u/apps'
make[1]: *** [Makefile:157: openssl] Error 2
make[1]: Leaving directory '/home/ubuntu/openssl-1.0.2u/apps'
make: *** [Makefile:293: build_apps] Error 1
```
Same system when running a 32bit OS can build the 32 bit version fine under linux-armv4.

Building FIPS defaults to:
```
./config -t
Operating system: aarch64-whatever-linux2
Auto Configuring fipsonly
Auto Configuring fipsonly
Configuring for linux-generic32
/usr/bin/perl ./Configure linux-generic32 -Wa,--noexecstack no-bf no-camellia no-cast no-idea no-md2 no-md5 no-mdc2 no-rc2 no-rc4 no-rc5 no-ripemd no-seed
```
Have also switched out for generic 64 and linux-armv4

Building openssl with
```
./config -t fips
Operating system: aarch64-whatever-linux2
Configuring for linux-aarch64
/usr/bin/perl ./Configure linux-aarch64 fips -Wa,--noexecstack
```
Have also tried with linux-generic64.

Am I just not using the right combo? This is all native so would assume just the defaults would work.

Thanks,

**Comment by kroeckx** [comment]
1.0.2 is no longer supported.

**Comment by andrewjwarren** [comment]
Completely understand 1.0.2 isn't supported but it would still be nice to know if this is actually supposed to work or not. I am pretty new to compiling code so thought maybe I had forgotten a flag or something else I am supposed to set.

**Comment by kroeckx** [comment]
It looks like the fips canister does not support aarch64. The
canister is saying that it does not know how to find the start
(and end). And if you try to update it, it likely won't be
validated. But I know little about this.

**Comment by paulidale** [comment]
Without a premium support contract, we (i.e. OpenSSL) will not look at this.

With [premium support contract](https://www.openssl.org/support/contracts.html#premium), we'd make an effort but not if it requires changes inside the FIPS boundary.  Revalidation of this old FOM is essentially impossible at this point.

**Comment by deadsy** [comment]
Just leaving this here. Yes, I know that modifying fips_cannister.c is verboten.
Most of us will be working with a FIPS test house and can probably get a pass on this since it's so minor.

--- ./fips/fips_canister.c  2020-09-15 17:08:19.947787107 +0000
+++ ./fips/fips_canister.c  2020-09-15 17:10:58.879367051 +0000
@@ -19,7 +19,7 @@
 # if   (defined(__sun) && (defined(__sparc) || defined(__sparcv9)))    || \
        (defined(__sgi) && (defined(__mips) || defined(mips)))          || \
        (defined(__osf__) && defined(__alpha))                          || \
-       (defined(__linux) && (defined(__arm) || defined(__arm__)))      || \
+       (defined(__linux) && (defined(__arm) || defined(__arm__) || defined(__aarch64__)))      || \
        (defined(__i386) || defined(__i386__))                          || \
        (defined(__x86_64) || defined(__x86_64__))                      || \
        (defined(vax) || defined(__vax__))
@@ -36,7 +36,7 @@
                                  defined(__i386__)|| defined(__i386))) || \
         (defined(__NetBSD__)  && (defined(__powerpc__) || defined(__i386))) || \
        (defined(__linux)     && ((defined(__PPC__) && !defined(__PPC64__)) || \
-                                 defined(__arm__) || defined(__arm)) || \
+                                 defined(__arm__) || defined(__arm) || defined(__aarch64__)) || \
                                  defined(__mips__))    || \
        (defined(__APPLE__) /* verified on all MacOS X & iOS flavors */)|| \
        (defined(_TMS320C6X))

**Comment by alexw91** [comment]
I wanted to note that It's also possible to manually set these flags without source code modifications. Doing this generates a FIPS Module with the exact same hash on aarch64 platforms as the above 2 line change proposed by @deadsy , but does not require any source code modifications.

```
./config -DPOINTER_TO_FUNCTION_IS_POINTER_TO_1ST_INSTRUCTION -DFIPS_REF_POINT_IS_CROSS_COMPILER_AWARE
make
make install
```

**Comment by Santhosh-K-M** [comment]
Hi,
Using the above command, it compiled for me too. Thanks for the same.
I cross compiled openssl-fips-ecp-2.0.16, for Debian Buster aarch64.
But while running I am getting the error as below and it dumps core:

_Failed to set EC public coordinates in EC DSA KAT
Failed to set EC public coordinates in EC DSA PCT
free(): invalid next size (fast)
Aborted_

What could be the issue ?
It works fine on other platforms like RaspberryPI, CentOS.
Google has nothing on this topic.
I looked into the code, but couldn't make much.

Thanks in advance,
Santhosh

**Comment by paulidale** [comment]
Building using those commands isn't permitted by the security policy.  The output will not be FIPS valid.

There is an easy enough workaround which would be valid.

**Comment by Santhosh-K-M** [comment]
Hi Paulidale,
Thanks for the quick reply. Could you please mention that workaround also. That will be helpful.

Thanks & Regards,
Santhosh

**Comment by paulidale** [comment]
I really shouldn't be mentioning this because once NIST catches on, it's game over.

``` SH
export CFLAGS=.....
```

Then on to the mandated build process...

**Comment by Santhosh-K-M** [comment]
Hi Paulidale,
Thanks again,
Do you think, the error & the core dump are happening, because of those flags used in compilation.

Thanks & Regards,
Santhosh
