### ISSUE TITLE
Intermediate certificates with Extended Key Usage extension

### ISSUE THREAD

**Issue by defacto64** [openssl/openssl#11117]
With reference to issue #8328 , could you please explain the rationale more clearly?

@vdukhovni wrote "The mechanism is not specified in RFC5280, but is a long-standing de-facto practice."

Could you please share mode details on that? In which areas is this practice adopted de-facto?

I am aware of just one context wherein this is done: the validation of SSL Server certificates by (mainstream) browsers.

**Comment by kroeckx** [comment]
If mainstream browsers do it, is it not a de-facto standard? If you want this behavior to change, I suggest that you convince the IETF to publish an RFC about how it should behave. I think this also got discussed on mozilla's dev-security-policy and in the CAB Forum.

**Comment by defacto64** [comment]
I am very well aware of that, Kurt. Besides, I did not suggest that the current behavuour of OpenSSL is wrong or that it should be changed. I was just asking what examples the OpenSSL developers had in mind. Based on your answer, it seems to be exactly the only one case that I mentioned myself.

**Comment by nhorman** [comment]
Marking as inactive to be closed at the end of 3.4 dev, barring further input

**Comment by defacto64** [comment]
Fine to me.
