### ISSUE TITLE
Please make PKCS7_get_octet_string() and PKCS7_type_is_other() public

### ISSUE THREAD

**Issue by out0xb2** [openssl/openssl#11139]
[TianoCore's code for parsing attached P7's](https://github.com/tianocore/edk2/blob/3806e1fd139775610d8f2e7541a916c3a91ad989/CryptoPkg/Library/BaseCryptLib/Pk/CryptPkcs7VerifyBase.c#L101) is incomplete (does not handle other OIDs).  

I chatted with @mattcaswell , and a proposed fix was to leverage PKCS7_get_octet_string() and PKCS7_type_is_other() , but sadly they are not public.  The alternative to them being public appears to be copy/paste.

The TianoCore bug report and patchset:
https://bugzilla.tianocore.org/show_bug.cgi?id=2539

Thanks you!

**Comment by mattcaswell** [comment]
This seems like a reasonable request to me, and should be relatively straight forward. I've marked this as a "good first issue". PRs welcome!
