### ISSUE TITLE
547944019728:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:516:

### ISSUE THREAD

**Issue by AhsanSheraz** [openssl/openssl#11135]
**Encrypt command:**
`sudo /usr/bin/openssl enc -aes-256-cbc -salt -in file1 -out file2 -pass file:file3`

**Decrypt command**
`sudo /usr/bin/openssl enc -d -aes-256-cbc -in file -out file2 -pass file:file3`

This will generate bad decrypt error.

**Encryption at:**
OpenSSL 1.0.2k-fips  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic

**Decryption at:**

OpenSSL 1.0.1t  3 May 2016
built on: Fri Jan 27 00:08:40 2017
platform: debian-arm64
options:  bn(64,64) rc4(ptr,char) des(idx,cisc,16,int) blowfish(ptr) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wa,--noexecstack -Wall
OPENSSLDIR: "/usr/lib/ssl"

**Comment by mattcaswell** [comment]
> OpenSSL 1.0.2k-fips 26 Jan 2017

and

> OpenSSL 1.0.1t 3 May 2016

Both of these versions are out of support. Please try again with version 1.1.1 and see if you still have problems.

**Comment by AhsanSheraz** [comment]
Thanks for your response issue resolved.
Actually I was doing multi-level encryption and I created a key file for each level with named currentTime.key(this was done in nanoseconds) that's why it was replacing the key file in key directory each time and at the end, I only have a key file for the upper level and rest of the decryption commands return **bad decrypt** error.
