### ISSUE TITLE
libssl.so is missing OPENSSL_1_1_1d

### ISSUE THREAD

**Issue by 311303** [openssl/openssl#11141]
I compiled the source code of OpenSSL 1.1.1d a few months ago, and compiled curl with libssl.so. Today, I want to add -WL, -rpath parameter to libssl.so, and download the source code of OpenSSL 1.1.1d, but execute "nm -D libssl.so" after compiling, I found that OPENSSL_1_1_1d is missing, which is why

**Comment by 311303** [comment]
../config enable-tls1_3 -DOPENSSL_THREADS -pthread -D_REENTRANT -D_THREAD_SAFE -D_THREADSAFE --prefix=/data  -DOPENSSL_NO_STATIC_ENGINE

**Comment by mattcaswell** [comment]
> but execute "nm -D libssl.so" after compiling, I found that OPENSSL_1_1_1d is missing

I'm not too sure what you're expecting to see with that `nm` command, but (on my system at least) if you want to see the symbol versions (which is what I assume you are referring to), you have to additionally supply the `--with-symbol-versions` option to `nm`. E.g.

````
$ nm -D --with-symbol-versions libssl.so
...
0000000000046a25 T SSL_accept@@OPENSSL_1_1_0
00000000000451b7 T SSL_add1_host@@OPENSSL_1_1_0
000000000003ba50 T SSL_add1_to_CA_list@@OPENSSL_1_1_1
000000000003bab0 T SSL_add_client_CA@@OPENSSL_1_1_0
000000000003c019 T SSL_add_dir_cert_subjects_to_stack@@OPENSSL_1_1_0
000000000003be70 T SSL_add_file_cert_subjects_to_stack@@OPENSSL_1_1_0
000000000004ec87 T SSL_add_ssl_module@@OPENSSL_1_1_0
00000000000551d4 T SSL_alert_desc_string@@OPENSSL_1_1_0
0000000000055358 T SSL_alert_desc_string_long@@OPENSSL_1_1_0
000000000005519c T SSL_alert_type_string@@OPENSSL_1_1_0
0000000000055164 T SSL_alert_type_string_long@@OPENSSL_1_1_0
000000000004db71 T SSL_alloc_buffers@@OPENSSL_1_1_1
000000000004e230 T SSL_bytes_to_cipher_list@@OPENSSL_1_1_1
...
````

There aren't any symbol versions of OPENSSL_1_1_1d in libssl.so because there were no symbols introduced in that patch version. Therefore the symbol versions are from earlier releases. There are some which were introduced in libcrypto in 1.1.1d:

````
$ nm -D --with-symbol-versions libcrypto.so | grep 1_1_1d
0000000000000000 A OPENSSL_1_1_1d@@OPENSSL_1_1_1d
000000000027cb3a T X509_get0_authority_issuer@@OPENSSL_1_1_1d
000000000027cb88 T X509_get0_authority_serial@@OPENSSL_1_1_1d
````

**Comment by 311303** [comment]
I also found that OPENSSL_1_1_1d was only found in the newly compiled libcrypto.so, but this libssl.so was compiled by me last December or so, and it is specifically like this
![-5ee5d4283119d2fa](https://user-images.githubusercontent.com/41131571/75022648-72d9dd00-54d1-11ea-8f3c-ac7960b0ec4b.jpg)



my libcurl.so needs OPENSSL_1_1_1d in libssl.so, which is very strange

**Comment by 311303** [comment]
> > but execute "nm -D libssl.so" after compiling, I found that OPENSSL_1_1_1d is missing
> 
> I'm not too sure what you're expecting to see with that `nm` command, but (on my system at least) if you want to see the symbol versions (which is what I assume you are referring to), you have to additionally supply the `--with-symbol-versions` option to `nm`. E.g.
> 
> ```
> $ nm -D --with-symbol-versions libssl.so
> ...
> 0000000000046a25 T SSL_accept@@OPENSSL_1_1_0
> 00000000000451b7 T SSL_add1_host@@OPENSSL_1_1_0
> 000000000003ba50 T SSL_add1_to_CA_list@@OPENSSL_1_1_1
> 000000000003bab0 T SSL_add_client_CA@@OPENSSL_1_1_0
> 000000000003c019 T SSL_add_dir_cert_subjects_to_stack@@OPENSSL_1_1_0
> 000000000003be70 T SSL_add_file_cert_subjects_to_stack@@OPENSSL_1_1_0
> 000000000004ec87 T SSL_add_ssl_module@@OPENSSL_1_1_0
> 00000000000551d4 T SSL_alert_desc_string@@OPENSSL_1_1_0
> 0000000000055358 T SSL_alert_desc_string_long@@OPENSSL_1_1_0
> 000000000005519c T SSL_alert_type_string@@OPENSSL_1_1_0
> 0000000000055164 T SSL_alert_type_string_long@@OPENSSL_1_1_0
> 000000000004db71 T SSL_alloc_buffers@@OPENSSL_1_1_1
> 000000000004e230 T SSL_bytes_to_cipher_list@@OPENSSL_1_1_1
> ...
> ```
> 
> There aren't any symbol versions of OPENSSL_1_1_1d in libssl.so because there were no symbols introduced in that patch version. Therefore the symbol versions are from earlier releases. There are some which were introduced in libcrypto in 1.1.1d:
> 
> ```
> $ nm -D --with-symbol-versions libcrypto.so | grep 1_1_1d
> 0000000000000000 A OPENSSL_1_1_1d@@OPENSSL_1_1_1d
> 000000000027cb3a T X509_get0_authority_issuer@@OPENSSL_1_1_1d
> 000000000027cb88 T X509_get0_authority_serial@@OPENSSL_1_1_1d
> ```

I also found that OPENSSL_1_1_1d was only found in the newly compiled libcrypto.so, but this libssl.so was compiled by me last December or so, and it is specifically like this
![-5ee5d4283119d2fa](https://user-images.githubusercontent.com/41131571/75022854-c815ee80-54d1-11ea-9703-bf4f1a696188.jpg)

my libcurl.so needs OPENSSL_1_1_1d in libssl.so, which is very strange

Now my solution is to add OPENSSL_1_1_1d to libssl.map. Curl can be used temporarily

**Comment by levitte** [comment]
Why does libcurl.so need OPENSSL_1_1_1d in libssl.so?  That does indeed seem quite strange...

**Comment by kroeckx** [comment]
This is what readelf shows me on my libssl1.1:
```
Version definition section '.gnu.version_d' contains 5 entries:
  Addr: 0x000000000000bd60  Offset: 0x00bd60  Link: 4 (.dynstr)
  000000: Rev: 1  Flags: BASE  Index: 1  Cnt: 1  Name: libssl.so.1.1
  0x001c: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: OPENSSL_1_1_0
  0x0038: Rev: 1  Flags: none  Index: 3  Cnt: 2  Name: OPENSSL_1_1_0d
  0x0054: Parent 1: OPENSSL_1_1_0
  0x005c: Rev: 1  Flags: none  Index: 4  Cnt: 2  Name: OPENSSL_1_1_1
  0x0078: Parent 1: OPENSSL_1_1_0d
  0x0080: Rev: 1  Flags: none  Index: 5  Cnt: 2  Name: OPENSSL_1_1_1a
  0x009c: Parent 1: OPENSSL_1_1_1

Version needs section '.gnu.version_r' contains 3 entries:
 Addr: 0x000000000000be08  Offset: 0x00be08  Link: 4 (.dynstr)
  000000: Version: 1  File: libpthread.so.0  Cnt: 1
  0x0010:   Name: GLIBC_2.2.5  Flags: none  Version: 12
  0x0020: Version: 1  File: libc.so.6  Cnt: 4
  0x0030:   Name: GLIBC_2.14  Flags: none  Version: 15
  0x0040:   Name: GLIBC_2.4  Flags: none  Version: 13
  0x0050:   Name: GLIBC_2.3.4  Flags: none  Version: 9
  0x0060:   Name: GLIBC_2.2.5  Flags: none  Version: 7
  0x0070: Version: 1  File: libcrypto.so.1.1  Cnt: 5
  0x0080:   Name: OPENSSL_1_1_0d  Flags: none  Version: 14
  0x0090:   Name: OPENSSL_1_1_0i  Flags: none  Version: 11
  0x00a0:   Name: OPENSSL_1_1_0f  Flags: none  Version: 10
  0x00b0:   Name: OPENSSL_1_1_1  Flags: none  Version: 8
  0x00c0:   Name: OPENSSL_1_1_0  Flags: none  Version: 6
```

And this is what a libcurl linked to it says:
```
Version needs section '.gnu.version_r' contains 8 entries:
 Addr: 0x00000000000061c8  Offset: 0x0061c8  Link: 4 (.dynstr)
  000000: Version: 1  File: liblber-2.4.so.2  Cnt: 1
  0x0010:   Name: OPENLDAP_2.4_2  Flags: none  Version: 16
  0x0020: Version: 1  File: libgssapi_krb5.so.2  Cnt: 1
  0x0030:   Name: gssapi_krb5_2_MIT  Flags: none  Version: 11
  0x0040: Version: 1  File: libidn2.so.0  Cnt: 1
  0x0050:   Name: IDN2_0.0.0  Flags: none  Version: 10
  0x0060: Version: 1  File: libldap_r-2.4.so.2  Cnt: 1
  0x0070:   Name: OPENLDAP_2.4_2  Flags: none  Version: 8
  0x0080: Version: 1  File: libssl.so.1.1  Cnt: 2
  0x0090:   Name: OPENSSL_1_1_1  Flags: none  Version: 18
  0x00a0:   Name: OPENSSL_1_1_0  Flags: none  Version: 7
  0x00b0: Version: 1  File: libpthread.so.0  Cnt: 1
  0x00c0:   Name: GLIBC_2.2.5  Flags: none  Version: 6
  0x00d0: Version: 1  File: libcrypto.so.1.1  Cnt: 1
  0x00e0:   Name: OPENSSL_1_1_0  Flags: none  Version: 5
  0x00f0: Version: 1  File: libc.so.6  Cnt: 9
  0x0100:   Name: GLIBC_2.16  Flags: none  Version: 20
  0x0110:   Name: GLIBC_2.15  Flags: none  Version: 19
  0x0120:   Name: GLIBC_2.4  Flags: none  Version: 17
  0x0130:   Name: GLIBC_2.7  Flags: none  Version: 15
  0x0140:   Name: GLIBC_2.17  Flags: none  Version: 14
  0x0150:   Name: GLIBC_2.14  Flags: none  Version: 13
  0x0160:   Name: GLIBC_2.3.4  Flags: none  Version: 12
  0x0170:   Name: GLIBC_2.3  Flags: none  Version: 9
  0x0180:   Name: GLIBC_2.2.5  Flags: none  Version: 4
```

**Comment by 311303** [comment]
This libssl.so was compiled by me last December. It seems that I didn't find these things in the OpenSSL 1.1.1d source code

![-4defc7d38c531252](https://user-images.githubusercontent.com/41131571/75085140-2b029680-5561-11ea-97a0-c250768273ba.jpg)

**Comment by 311303** [comment]
I see. This is the OpenSSL I used to compile curl that supports http3😶

`git clone https://github.com/tatsuhiro-t/openssl.git -b OpenSSL_1_1_1d-quic-draft-25 --depth=1`

Thinks
