### ISSUE TITLE
static lib

### ISSUE THREAD

**Issue by CedricCouton** [openssl/openssl#11156]
Hi,

My context is a windows env. I would like to know what is the difference between the libcrypto_static.lib and libcrypto.lib files? Indeed when I try to link a program in static mode with the libcrypto.lib my program crash with code 0xC0000005 STATUS_ACCESS_VIOLATION.

Thanks in advance.

Cédric

**Comment by levitte** [comment]
`libcrypto.lib is the import library that goes together with the libcrypto DLL.

**Comment by CedricCouton** [comment]
So if I would like to link my program in static kind with libcrypto I must used libcrypto_static.lib? If it's true, when I use it I have many error during link process like  undefined reference to `__GSHandlerCheck'
undefined reference to `__chkstk'. What is my problem ?

Thanks in advance

**Comment by levitte** [comment]
Your problem is that you must also link with the libraries that the DLLs are linked with.  Which ones those are depends on what config target you used.

**Comment by CedricCouton** [comment]
ADVIAPI32.DLL, KERNELL32.DLL, W32_32.DLL etc...?
