### ISSUE TITLE
openssl1.1.2 bitbake unable to locate

### ISSUE THREAD

**Issue by meghana-linux** [openssl/openssl#11155]
Hello All,
I am trying to upgrade openssl to 1.1.2, can someone point me to openssl1.1.2 bb file.
( i am upgrading openssh also to 7.9 to support openssl1.1.2)

Thanks,
meghana

**Comment by levitte** [comment]
There is no 1.1.2. There is 1.1.1, though. Do you find it?

**Comment by meghana-linux** [comment]
Hello, Thanks i found openssl1.1.1b in github **thud branch** ( https://github.com/openembedded/openembedded-core/tree/thud/meta/recipes-connectivity/openssl) 
But in **warrior branch** i found **openssl_1.1.1d.bb** (https://github.com/openembedded/openembedded-core/tree/warrior/meta/recipes-connectivity/openssl)
I would like to understand whats the difference between 1.1.1b and 1.1.1d.

**_As  per openssh.org (https://www.openssh.com/releasenotes.html ) understood that we must upgrade to openssh7.9 to use openssl1.1.X_**
but as per the link : https://github.com/openembedded/openembedded-core/tree/thud/meta/recipes-connectivity/openssh
		The git commit message shows -> **openssh: upgrade 7.8p1 -> 7.8p1+git to support openssl 1.1.x**

Kindly point me to which version of openss to use , my requirement is to use openssl1.1.1d.

Please provide some pointers.


Thanks
meghana

**Comment by levitte** [comment]
>  I would like to understand whats the difference between 1.1.1b and 1.1.1d.

Bug fixes and security fixes.

> Kindly point me to which version of openss to use , my requirement is to use openssl1.1.1d.

Then by all means, do use that version!

**Comment by meghana-linux** [comment]
Hello 
Thanks for the help, i have picked up zeus branch and trying to upgrade openssl1.1.1d, i understood that i need to update rpm also, so picked up rpm4.14.2.1 from the same branch.
BUt when i do bitbake rpm, i get the following error:

WARNING: ~/recipes-devtools/rpm/rpm_4.14.2.1.bb: Exception during build_dependencies for do_install
WARNING: ~/recipes-devtools/rpm/rpm_4.14.2.1.bb: Error during finalise of virtual:nativesdk:/tmp/.../recipes-devtools/rpm/rpm_4.14.2.1.bb

ERROR: ExpansionError during parsing /tmp/~/recipes-devtools/rpm/rpm_4.14.2.1.bb

Kindly point me out what might be the issue.

Thanks
meghana

**Comment by meghana-linux** [comment]
Hello
Thanks for the help, i have picked up zeus branch and trying to upgrade openssl1.1.1d, i understood that i need to update rpm also, so picked up rpm4.14.2.1 from the same branch.
BUt when i do bitbake rpm, i get the following error:


WARNING: /tmp/~/rpm/rpm_4.14.2.1.bb: Exception during build_dependencies for do_install
WARNING: /tmp/~/rpm/rpm_4.14.2.1.bb: Error during finalise of virtual:nativesdk:/tmp/~/rpm/rpm_4.14.2.1.bb
ERROR: ExpansionError during parsing /tmp/~/rpm/rpm_4.14.2.1.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable do_install, expression was     autotools_do_install
        for tool in     /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpm    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpm2archive    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpm2cpio    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmbuild    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmdb    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmgraph    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmkeys    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmsign    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmspec    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/rpmdeps ; do
                create_wrapper /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image$tool \
                        RPM_CONFIGDIR='`dirname $''realpath`'/${@os.path.relpath(d.getVar('libdir',True), d.getVar('bindir',True))}/rpm \
                        RPM_ETCCONFIGDIR='$'{RPM_ETCCONFIGDIR-'`dirname $''realpath`'/${@os.path.relpath(d.getVar('sysconfdir'.True), d.getVar('bindir',True))}/..} \
                        MAGIC='`dirname $''realpath`'/${@os.path.relpath(d.getVar('datadir'.True), d.getVar('bindir',True))}/misc/magic.mgc \
                        RPM_NO_CHROOT_FOR_SCRIPTS=1
        done

        rm -rf /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image/var
        sed -i -e 's:${HOSTTOOLS_DIR}/::g' \
            /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image//opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/macros

        sed -i -e 's|/usr/bin/python|/usr/bin/env python3|' \
            /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image/opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/pythondistdeps.py \
            /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image/opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/python-macro-helper
 which triggered exception SyntaxError: invalid syntax (do_install, line 1)

Thanks
meghana

**Comment by romen** [comment]
We can't help you troubleshoot Yocto/bitbake issues as we do not maintain any bitbake recipe.

It would be more appropriate to look into the support channels of the Yocto/bitbake repositories you are using (unless you get compile time or runtime errors in OpenSSL itself, that are not depending on mistakes in the bitbake recipe).

**Comment by meghana-linux** [comment]
Hello
Thanks for the help, i have picked up zeus branch and trying to upgrade openssl1.1.1d, i understood that i need to update rpm also, so picked up rpm4.14.2.1 from the same branch.
BUt when i do bitbake rpm, i get the following error:


WARNING: /tmp/~/rpm/rpm_4.14.2.1.bb: Exception during build_dependencies for do_install
WARNING: /tmp/~/rpm/rpm_4.14.2.1.bb: Error during finalise of virtual:nativesdk:/tmp/~/rpm/rpm_4.14.2.1.bb
ERROR: ExpansionError during parsing /tmp/~/rpm/rpm_4.14.2.1.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable do_install, expression was     autotools_do_install
        for tool in     /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpm    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpm2archive    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpm2cpio    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmbuild    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmdb    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmgraph    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmkeys    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmsign    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/rpmspec    /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/rpmdeps ; do
                create_wrapper /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image$tool \
                        RPM_CONFIGDIR='`dirname $''realpath`'/${@os.path.relpath(d.getVar('libdir',True), d.getVar('bindir',True))}/rpm \
                        RPM_ETCCONFIGDIR='$'{RPM_ETCCONFIGDIR-'`dirname $''realpath`'/${@os.path.relpath(d.getVar('sysconfdir'.True), d.getVar('bindir',True))}/..} \
                        MAGIC='`dirname $''realpath`'/${@os.path.relpath(d.getVar('datadir'.True), d.getVar('bindir',True))}/misc/magic.mgc \
                        RPM_NO_CHROOT_FOR_SCRIPTS=1
        done

        rm -rf /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image/var
        sed -i -e 's:${HOSTTOOLS_DIR}/::g' \
            /tmp/sk1141_TD2_NGRPupgr_view/ngrp-p2-zcu15/poky/build_ngrp/tmp/work/x86_64-nativesdk-pokysdk-linux/nativesdk-rpm/1_4.14.2.1-r0/image//opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/macros

        sed -i -e 's|/usr/bin/python|/usr/bin/env python3|' \
            /tmp/~/nativesdk-rpm/1_4.14.2.1-r0/image/opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/pythondistdeps.py \
            /tmp/~/nativesdk-rpm/1_4.14.2.1-r0/image/opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/lib/rpm/python-macro-helper
 which triggered exception SyntaxError: invalid syntax (do_install, line 1)



Please point me what have to be fixed here
Thanks
meghana

**Comment by romen** [comment]
> Hello
> Thanks for the help, i have picked up zeus branch and trying to upgrade openssl1.1.1d, i understood that i need to update rpm also, so picked up rpm4.14.2.1 from the same branch.
> BUt when i do bitbake rpm, i get the following error:

We can't help you troubleshoot Yocto/bitbake issues as we do not maintain any bitbake recipe.

It would be more appropriate to look into the support channels of the Yocto/bitbake repositories you are using (unless you get compile time or runtime errors in OpenSSL itself, that are not depending on mistakes in the bitbake recipe).

**Comment by meghana-linux** [comment]
Thanks
ATleast is there a way to know what are the dependencies for a specific openssl version ?

Help appreciated.
Thanks
meghana

**Comment by romen** [comment]
The prerequisites are listed in the documentation that comes with the source code: https://github.com/openssl/openssl/blob/master/INSTALL.md#prerequisites

(the link above comes from the `master` branch where it has been recently nicely reformatted by @mspncp. 

You will find a similar section within the sources for the openssl version you are compiling (the latest stable release is currently 1.1.1d)

**Comment by levitte** [comment]
As far as I can see, that latest error output has nothing to do with openssl.
