### ISSUE TITLE
OSSL_PARAM_REAL type

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#11165]
The documentation says:
```
       OSSL_PARAM_REAL
           The parameter data is a floating point value in native form.
```

It seems that the code has switches all over checking sizeof(double). I think double is the only thing we support. It's probably more clear that we say double there instead of "floating point".

**Comment by levitte** [comment]
Why? Both `float` and `double` are floating point types, just of different sizes.

**Comment by kroeckx** [comment]
But we don't actually support either float or long double.

**Comment by levitte** [comment]
So?

**Comment by kroeckx** [comment]
If we have no intention to support anything other that double, I
think it should be clear that when we say OSSL_PARAM_REAL that
it's a double, and not any of the other floating point types. Or
everywhere that OSSL_PARAM_REAL is used, it should mention
only double is supported.

**Comment by levitte** [comment]
Key word here is *currently*. I see no reason to lock that data type to one specific C type.

And the point is that any size is perfectly possible for the OSSL_PARAM structure itself, even though the OSSL_PARAM *functions* currently only support double.

**Comment by paulidale** [comment]
I had `float` in the parameter code originally but it was decided to defer this until later.  Putting it back would be straightforward.

I'm less sure about `long double` though.  I have seen compilers where command line options change the size of this one which could cause problems with providers built differently to libcrypto.  A can of worms best left closed until we need it.

**Comment by levitte** [comment]
Right. And we can with no changes to the OSSL_PARAM data types.

**Comment by paulidale** [comment]
#11183 ??
