### ISSUE TITLE
Skein 1024 for certificates

### ISSUE THREAD

**Issue by stas730** [openssl/openssl#1116]
We need to support Skein 1024 because it stronger than SHA-512 (512 < 1024).
We need both -md skein1024 (sorry if -md is removed) and -skein1024 parameters.

**Comment by stas730** [comment]
P. S. If stronger algorithms are available, we need to include it, too.

**Comment by kaduk** [comment]
I'll defer to @levitte on the disposition/milestone for this issue (as part of pre-1.1.1 triage), since he assigned it to himself.

**Comment by levitte** [comment]
Skein is one of the candidates for SHA-3, which ended up being Keccak instead.

We have SHA3 implemented, so I'd say this point is moot at this point.

Ref: https://csrc.nist.gov/projects/hash-functions/sha-3-project

Anyone have a different opinion?

**Comment by richsalz** [comment]
No.  Close this.
