### ISSUE TITLE
foo.conf or foo.cnf ?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#11174]
The default configuration file is openssl.cnf  We can't seem to make up our minds:
```
; find . -name '*.conf' | wc
     79      79    3118
; find . -name '*.cnf' | wc  
     33      33    1064
; 
```

Should we rename conf to cnf ?  Because it will help people understand what's going on better?

(BTW, several files are never used: test/CAssdh.cnf, test/CAssdsa.cnf, test/CAssrsa.cnf, test/Sssdsa.cnf, test/Sssrsa.cnf)

**Comment by t8m** [comment]
+1 from me. I think we should use consistent suffix and as we cannot/should not change the suffix on openssl.cnf it has to be .cnf.

**Comment by t-j-h** [comment]
+1 also and agree with @t8m logic - has to be cnf.

**Comment by richsalz** [comment]
So @t-j-h and @t8m go approve #11176 :)
