### ISSUE TITLE
openssl psk_identity mismatch handling

### ISSUE THREAD

**Issue by ms-s** [openssl/openssl#11194]
Version: 1.1.1d

Mismatch of psk_identity not handled as specified in RFC 8446. 

The text in section 6.2 of RFC 8446 says "unknown_psk_identity:  Sent by servers when PSK key establishment is desired but no acceptable PSK identity is provided by the client. Sending this alert is OPTIONAL; servers MAY instead choose to send a "decrypt_error" alert to merely indicate an invalid PSK identity."

Currently, any identity is accepted as long as a matching PSK is found. For example:
openssl s_server -accept 4433 -psk 1a2b3c4d -nocert -tls1_3 -psk_identity 'test' -trace and
openssl s_client -connect 127.0.0.1:4433 -psk 1a2b3c4d -sess_out sesion -tls1_3 -psk_identity 'wewe' -trace

results in successful connection even though psk_identity at server 'test' does not match psk_identity at client 'wewe'. 

Server should either send a fatal "decrypt_error" alert or then "unknown_psk_identity" alert.

**Comment by kaduk** [comment]
`s_server` and `s_client` are debugging tools, not production-ready implementations.

Note the server output:

> PSK warning: client identity not what we expected (got 'wewe' expected 'test')

and code in s_server.c that explicitly continues past the identity mismatch:

```
    /* here we could lookup the given identity e.g. from a database */
    if (strcmp(identity, psk_identity) != 0) {
        BIO_printf(bio_s_out, "PSK warning: client identity not what we expected"
                   " (got '%s' expected '%s')\n", identity, psk_identity);
    } else {
      if (s_debug)
        BIO_printf(bio_s_out, "PSK client identity found\n");
    }
```

If the callback instead failed to match the requested identity (e.g., by reporting a zero-length key), then libssl would indeed send the "unknown_psk_identity" alert as you say:

```
    psklen = s->psk_server_callback(s, s->session->psk_identity,
                                    psk, sizeof(psk));

    if (psklen > PSK_MAX_PSK_LEN) {
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_PROCESS_CKE_PSK_PREAMBLE,
                 ERR_R_INTERNAL_ERROR);
        return 0;
    } else if (psklen == 0) {
        /*
         * PSK related to the given identity not found
         */
        SSLfatal(s, SSL_AD_UNKNOWN_PSK_IDENTITY,
                 SSL_F_TLS_PROCESS_CKE_PSK_PREAMBLE,
                 SSL_R_PSK_IDENTITY_NOT_FOUND);
        return 0;
    }
```

I don't think there's a bug here.
