### ISSUE TITLE
Function not found

### ISSUE THREAD

**Issue by AheadSnail** [openssl/openssl#11198]
hello,I have a question About the difference between the old and new version of the function

I used to compile the android static library with 1.0.2, now I replaced it with 1.1.1 to compile the static library, and directly replaced the original program.Found that many functions could not be found， such as 

../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_sha256sum: error: undefined reference to 'EVP_MD_CTX_create'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_sha256sum: error: undefined reference to 'EVP_MD_CTX_destroy'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_md5sum: error: undefined reference to 'EVP_MD_CTX_create'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_md5sum: error: undefined reference to 'EVP_MD_CTX_destroy'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_version: error: undefined reference to 'SSLeay'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_cleanup: error: undefined reference to 'EVP_cleanup'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_cleanup: error: undefined reference to 'ENGINE_cleanup'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_cleanup: error: undefined reference to 'ERR_free_strings'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_cleanup: error: undefined reference to 'CONF_modules_free'
  ../../../../src/main/cpp/third/lib/armeabi-v7a/libcurl.a(libcurl_la-openssl.o):openssl.c:function Curl_ossl_cleanup: error: undefined reference to 

Below is my compilation script

#!/bin/bash
cd openssl-1.1.1
export ANDROID_NDK=/opt/android-ndk-r14b
PATH=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH
./Configure android-arm -D__ANDROID_API__=21
make

Can you give some advice？ thandks

**Comment by beldmit** [comment]
All the functions you can't find are macros in 1.1.1 (and some of them are noop ones now). I'm not familiar with the Android development process but I think you'll have to change the library you try to link with some newer version.

**Comment by AheadSnail** [comment]
> All the functions you can't find are macros in 1.1.1 (and some of them are noop ones now). I'm not familiar with the Android development process but I think you'll have to change the library you try to link with some newer version.

thanks！ I replaced it with 1.1.1c to solve this problem

**Comment by AheadSnail** [comment]
> 您找不到的所有功能都是1.1.1中的宏（其中有些现在是noop功能）。我对Android开发过程不熟悉，但我认为您必须更改尝试与某些较新版本链接的库。

I changed it to 1.1.1c and it still compiles. Is there some compilation parameters that are not turned on?

**Comment by levitte** [comment]
libcurl.a seems to expect 1.0.2.  It needs to be recompiled (possibly upgraded) to be usable with OpenSSL 1.1.1
