### ISSUE TITLE
EOF handling in s_client faliure

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#11209]
s_server:
```
openssl s_server -cert cert.pem -key key.pem -www -cipher ECDHE-RSA-AES256-SHA
```
s_client:
```
openssl s_client -connect localhost:4433 -CAfile manul-gost/sslCA/cacert.pem -state -cipher ECDHE-RSA-AES256-SHA -ign_eof

GET / \n\n
```
result:
(some html)

```
</pre></BODY></HTML>

SSL3 alert write:fatal:decode error
00:71:81:B1:E1:7F:00:00:error:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:307:
```
This behavior was introduced in https://github.com/openssl/openssl/commit/db943f43a6
Found by @vt-alt

**Comment by beldmit** [comment]
If I understand correctly, now we have a violation of the comment here:
https://github.com/openssl/openssl/blob/e32c608e0733d5b295c9aa119153133413c5d744/apps/s_client.c#L2939-L2940

and need a more thorough study of the error setting it to zero when BIO_eof occurs.

**Comment by beldmit** [comment]
And also there is a problem with the result code of s_client, which I think should be 0 in this case.

**Comment by vt-alt** [comment]
@mattcaswell @t8m
Developers should note that this is stable branch, not development branch. So, this is sorta important.

**Comment by kroeckx** [comment]
I'm not sure what you're complaining about. s_client gave a very
confusing error "read:errno=0". With the current version, it
properly prints "unexpected eof while reading", which is normal.

s_server does not properly shut down a connection when it should,
it just closes the connection. So s_client should give an error
message.

If you modify s_server to properly shut down the connection, s_client
will not return an error. With a modified s_server, both the old
and new s_client will print "closed".

**Comment by beldmit** [comment]
Hmmm. The idea to fix it from the server side is interesting.

**Comment by mattcaswell** [comment]
> If you modify s_server to properly shut down the connection, s_client
will not return an error. With a modified s_server, both the old
and new s_client will print "closed".

Yes - this was my immediate thought too. If s_server is closing the connection without shutting it down properly then this seems more like an s_server bug than an s_client one.

**Comment by beldmit** [comment]
I tried to add SSL_shutdown (in a loop) at the end of www_body, and the result appears to be the same.

**Comment by beldmit** [comment]
I want to mention that the error appears when using s_client to connect to IIS-based server. So I think it should be retested and maybe rethought.

**Comment by kaduk** [comment]
It is "well known" that IIS does not send the `close_notify` alert.

**Comment by beldmit** [comment]
> It is "well known" that IIS does not send the close_notify alert.
Unfortunately not for me :(

Currently we have two sets of failures in the command-line utilities in master 
1. s_client/s_server pair
This case should be fixed on the s_server side, isn't it? If so, could you please give a minimal guideline so I could implement it?

2. s_client/"well-known" broken servers. 
I think it's better to have an option to ignore this error (off by default). If you agree and provide any clue, I'll try to implement it too.

**Comment by mattcaswell** [comment]
> s_client/s_server pair
This case should be fixed on the s_server side, isn't it? If so, could you please give a minimal guideline so I could implement it?

s_server shuts down like this (yuck):

https://github.com/openssl/openssl/blob/b756626a3732869875c50f150bddacfbcac5a7ab/apps/s_server.c#L2771-L2774

Compare that with s_client which shuts down like this:

https://github.com/openssl/openssl/blob/b756626a3732869875c50f150bddacfbcac5a7ab/apps/s_client.c#L101-L120

> s_client/"well-known" broken servers.
I think it's better to have an option to ignore this error (off by default). If you agree and provide any clue, I'll try to implement it too.

The check that we added is here:

https://github.com/openssl/openssl/blob/b756626a3732869875c50f150bddacfbcac5a7ab/ssl/record/rec_layer_s3.c#L303-L308

Without that check you'd get the "legacy" behaviour which ends up in SSL_get_error() reporting SSL_ERROR_SYSCALL even though `errno` is 0.
