### ISSUE TITLE
openssl-rand command doc and crypto-security

### ISSUE THREAD

**Issue by marcobellaccini** [openssl/openssl#11201]
openssl **RAND(1SSL)** manpage and the derived [HTML doc](https://www.openssl.org/docs/man1.1.1/man1/openssl-rand.html) do not explicitly state whether the generated pseudo-random bytes are crypto-secure or not.

From the <<SEE ALSO: **RAND_bytes(3)**>> link, it can inferred that the command is backed by **RAND_bytes()**, hence sharing its cryptographic properties.

However, I think it may be better to be a bit more explicit, since this seems to be [source of concern](https://crypto.stackexchange.com/questions/68919/is-openssl-rand-command-cryptographically-secure) for some users.

**Comment by richsalz** [comment]
What does it mean to be "crypto secure" ?
What does it mean to claim that, if someone configures OpenSSL with no seeding or a custom seed and feeds it a known repeatable stream of bytes?

I don't think openssl can make any more guarantees than it already states.  The FIPS module will be able to claim more, for validated platforms.

**Comment by marcobellaccini** [comment]
Hi,
as _crypto-secure_, I mean **openssl-rand** returning cryptographically strong pseudo-random bytes, thus being a [CSPRNG](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator).

In the [RAND_bytes() manpage](https://www.openssl.org/docs/man1.1.1/man3/RAND_bytes.html), I read: 

> RAND_bytes() puts num cryptographically strong pseudo-random bytes into buf

I'm asking you to clarify whether **openssl-rand** output shares the same cryptographic properties of **RAND_bytes()** output or not.

**Comment by richsalz** [comment]
sure, yes, a fix to say that the "rand" command uses "rand_bytes" would probaby be useful.  ping @paulidale

**Comment by paulidale** [comment]
The DRBGs are cryptographically strong PRNGs.  The weak point, as noted, is the seed source.
That's the essence of what I tried to capture in #11202.

**Comment by richsalz** [comment]
The original issue is that "openssl rand uses RAND_bytes" was not explicit enough.

**Comment by paulidale** [comment]
I'm editing a sentence in saying that too.

**Comment by marcobellaccini** [comment]
This has now been fixed by https://github.com/openssl/openssl/pull/11213 and https://github.com/openssl/openssl/pull/11251.

Thank you very much: great team, great job!
