### ISSUE TITLE
ANDROID_NDK_HOME should use ANDROID_NDK_ROOT

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#11205]
According to [`NOTES.ANDROID`](https://github.com/openssl/openssl/blob/master/NOTES.ANDROID):

>  Apart from PATH adjustment you need to set ANDROID_NDK_HOME
> environment to point at the NDK directory. If you're using a side-by-side
> NDK the path will look something like /some/where/android-sdk/ndk/<ver>

According to the NDK folks in [Recommended NDK Directory?](http://groups.google.com/group/android-ndk/browse_thread/thread/a998e139aca71d77), you should set two variables. The first is `ANDROID_SDK_ROOT`, and the second is `ANDROID_NDK_ROOT`. `ANDROID_SDK_ROOT` and `ANDROID_NDK_ROOT` are separate, independent environmental variables. Assuming there's some variable `ANDROID_NDK_HOME` that points to a SDK install and the NDK is some subfolder is just plain wrong.

In fact, setting `ANDROID_NDK_HOME` like that will break in another way because the Android Studio folks made their own shit up (instead of following the NDK folks) and used `ANDROID_NDK_HOME` for something else (iirc).

`ANDROID_NDK_HOME` is breaking Android builds for well configured environments.

**Comment by levitte** [comment]
This seem to be a moving target, see the discussion in #8101.  That being said, a quick search confirms what you say, so...

**Comment by levitte** [comment]
It's a bit unnerving that there doesn't seem to exist any official documentation on these variables...

**Comment by levitte** [comment]
See #11205
