### ISSUE TITLE
OpenSSL_Cleanup() + curl Memory Leak

### ISSUE THREAD

**Issue by Balenty** [openssl/openssl#11208]
Using: 
Windows 
OpenSSL1.1.1d
curl 7.68.0
Visual Studio 2019

I experienced memory leaks if init.c `OPENSSL_init_crypto` is executed on a different thread as init.c `OpenSSL_Cleanup()`.
During initalization threads_win.c `CRYPTO_THREAD_set_local` is called and heap elements are stored thread_local.
During cleanup this thread_local heap elements are accessed to free them.
But if the cleanup is not performed in the identical thread the cleanup process wont receive the correct pointer.

When i init and cleanup in the same thread and use openssl inbetween in different threads it is going to work without memory leaks.

Init is called usually automatically the first time openssl is used (through curl)
Cleanup is not called automatically through curl, instead it triggers at exit() (`ossl_init_register_atexit`) in the main thread.
So init may be called in different thread than the mainthread and cleanup is always called in the mainthread.
As `OpenSSL_Cleanup()` can only be executed once it needs to be executed correctly.

Is this an intended behaviour?

My workaround (if curl init and cleanup are executed in the same thread) is following:
Adding in the curl "vtls/openssl.c" file the line `OPENSSL_cleanup();` at the end of the `static void Curl_ossl_cleanup(void)` function

**Comment by mattcaswell** [comment]
Cleaning up threads can be a tricky business and may require you to call `OPENSSL_thread_stop`. Please take a look at this man page, and in particular read the paragraph on `OPENSSL_thread_stop` and the NOTES section:

https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_cleanup.html

**Comment by kaduk** [comment]
@Balenty did this resolve your question?

**Comment by Balenty** [comment]
Indeed this fixed my issue. Thank you very much.
That was a classic case of: Documentation ignored
