### ISSUE TITLE
Can I create DKIM key using Openssl

### ISSUE THREAD

**Issue by amjedomar** [openssl/openssl#11204]
I created DKIM ( `private` and `public`) key using **OpenSSL** via the following commands

```
openssl genrsa -out private.key 2048
openssl rsa -in private.key -pubout -out public.key
```

**The Question is:**

- Can I add the `public.key` to the domain’s DNS records (TXT).
- Can I used the `private.key` to setup **DKIM Signing** using [Nodemailer](https://nodemailer.com/dkim/).
- Is creating DKIM key (`private` and `public`) using **Openssl** is safe, Is **Openssl** the preferred tool to do that.

**Comment by LeonMelis** [comment]
I have written a guide on [how to create a DKIM record with OpenSSL](https://www.mailhardener.com/kb/how-to-create-a-dkim-record-with-openssl).

I am not familiar with Nodemailer per se, but judging from the Nodemailer documentation it should be able to use the private.key file for Nodemailer.

**Comment by t8m** [comment]
I'd say the answer to all these questions is "Why not?" but also "It depends on other circumstances such as having proper source of entropy on the system (should be fine on contemporary systems) and so on."
