### ISSUE TITLE
In TLS1.3, will SSL_write yield SSL_ERROR_WANT_READ ? And will SSL_read yield SSL_ERROR_WANT_WRITE?

### ISSUE THREAD

**Issue by hehechen** [openssl/openssl#11211]
There is no re-negotiation in TLS1.3, will SSL_write yield SSL_ERROR_WANT_READ? And will SSL_read yield SSL_ERROR_WANT_WRITE?

In SSL_write doc:
As at any time a re-negotiation is possible, a call to a write function can also cause read operations!
In SSL_read doc:
As at any time it's possible that non-application data needs to be sent, a read function can also cause write operations.

**Comment by kroeckx** [comment]
You should just assume that for protocol reasons, the TLS layer
might need to read or write. An example with TLS 1.3 is that it
might request a key update.

**Comment by kaduk** [comment]
It looks like this question was answered, so closing.
