### ISSUE TITLE
Resolution of 3 vars not possible in 1.1.1d on iOS archs

### ISSUE THREAD

**Issue by thejeff77** [openssl/openssl#11212]
Hey there,

I'm building OpenSSL 1.1.1d for iOS iPhone frameworks. I've tried numerous pods, custom commands and the like.

Everything builds fine, however certain references are broken after importing openssl via cocoapods or frameworks built off of 1.1.1d or c.

```
 Use of undeclared type 'X509'
 Use of unresolved identifier 'OpenSSL_add_all_digests'
 Use of unresolved identifier 'c2i_ASN1_INTEGER'
```

These issues go away using 1.0.2, however 1.0.2 doesn't support arm64.

build command reference:
https://github.com/thejeff77/OpenSSL-Pod/blob/master/OpenSSL.podspec

I verified this is using clang, and the build options recommended on the documentation here: https://wiki.openssl.org/index.php/Compilation_and_Installation#OpenSSL_1.1.0

Regarding the last build error for 'c2i_ASN1_INTEGER', as commented here: https://github.com/andrewcbancroft/SwiftyLocalReceiptValidator/issues/9#issuecomment-448305226

> I've been running around trying to figure out what happened to c2i_ASN1_INTEGER and it appears that in 2015 for OpenSSL 1.1.1 this method was moved into asn1_locl.h as a mechanism to hide it/make it private.
> openssl/openssl@c315a54
> 
> I did not really research why this was moved, so one could use OpenSSL 1.1.0 or... one could re-expose this method by copying the missing function definition lines into my OpenSSL/include/openssl/asn1.h file to allow swift to have access to it (which was still built when compiling OpenSSL 1.1.1).

Still requires a manual hack...

We've had no luck with resolution of X509 or OpenSSL_add_all_digests

Any help/bugfix would be much appreciated.

**Comment by beldmit** [comment]
`X509` is an opaque struct now. You shouldn't use it directly but the accessor functions instead.

You also should use `OPENSSL_init_crypto` instead of `OpenSSL_add_all_digests`

Regarding `c2i_ASN1_INTEGER`, I can't give you any advice not being familiar with your code.

**Comment by thejeff77** [comment]
Hey @beldmit thank you for the quick reply. 

OPENSSL_init_crypto resolves the issue.

For the X509, the use of this accessor method d2i_X509_bio has a return type of X509 (along with d2i_X509_CRL_bio and d2i_X509_REQ_bio in X509.h). I'd be interested in any suggestions for using the return value if the type is now internal-only.
`let appleRootCertificateX509 = d2i_X509_bio(appleRootCertificateBIO, nil)`

Method has a return type of `UnsafeMutablePointer<X509>`

The c2i_ASN1_INTEGER seems to be used to turn an intermediary pointer to an integer into an AS1_INTEGER before turning around to convert it into an Int type. Perhaps there is a better way to avoid this method in 1.1.1. 

```
    func DecodeASN1Integer(startOfInt intPointer: inout UnsafePointer<UInt8>?, length: Int) -> Int? {
        // These will be set by ASN1_get_object
        var type = Int32(0)
        var xclass = Int32(0)
        var intLength = 0
        
        ASN1_get_object(&intPointer, &intLength, &type, &xclass, length)
        
        guard type == V_ASN1_INTEGER else {
            return nil
        }
        
        let integer = c2i_ASN1_INTEGER(nil, &intPointer, intLength)
        let result = ASN1_INTEGER_get(integer)
        ASN1_INTEGER_free(integer)
        
        return result
    }
```

Thanks

**Comment by beldmit** [comment]
`UnsafeMutablePointer<X509>` is a pointer, X509* in terms of C. You should pass it as a whole object without diving inside.

Unfortunately, can't advise anything related to c2i_ASN1_INTEGER

**Comment by thejeff77** [comment]
Thanks for all the help. Solution is to just remove a bunch of the code in that function. 

```
    func DecodeASN1Integer(startOfInt intPointer: inout UnsafePointer<UInt8>?, length: Int) -> Int?  {       
        let integer = c2i_ASN1_INTEGER(nil, &intPointer, length)
        let result = ASN1_INTEGER_get(integer)
        ASN1_INTEGER_free(integer)
        
        return result
    }
```

**Comment by PurpleShrek** [comment]
> Спасибо за помощь. Решение состоит в том, чтобы просто удалить кучу кода в этой функции.
> 
> ```
>     func DecodeASN1Integer(startOfInt intPointer: inout UnsafePointer<UInt8>?, length: Int) -> Int?  {       
>         let integer = c2i_ASN1_INTEGER(nil, &intPointer, length)
>         let result = ASN1_INTEGER_get(integer)
>         ASN1_INTEGER_free(integer)
>         
>         return result
>     }
> ```

at the moment you need to replace the second line of your code with this...

let integer = d2i_ASN1_INTEGER(nil, &intPointer, length)
