### ISSUE TITLE
OCSP server crash with simple browser

### ISSUE THREAD

**Issue by stas730** [openssl/openssl#1121]
Critical bug in OCSP server!
I created EV certificate and setup OCSP server because browser require it for EV. And I like trust & security.
But if I connect to OCSP server using browser, it sends response and crashes.
It is a critical bug. Or my mistake. :)

**Comment by richsalz** [comment]
Sigh.  *USE EMAIL LISTS*
There is not enough information to reproduce the problem here

**Comment by stas730** [comment]
I fixed it by -ignore_err — it is my mistake.
I cannot use mailing list with Guerilla mail. My real email is on my server in Tor network.

**Comment by richsalz** [comment]
There are various mail/web gateways, including nabble and google groups.  or get a gmail account the same you got a github account.
