### ISSUE TITLE
when will the next stable release of OpenSSL1.1.1 

### ISSUE THREAD

**Issue by lantse-cap1** [openssl/openssl#11221]
When will the next stable version of OpenSSL1.1.1 be released? 

It has been over 5 months since last release. We are in need to use some enhancements for OpenSSL1.1.1, while we do not want to use nightly build. 

Thanks.

**Comment by mattcaswell** [comment]
There has been no decision as yet.

**Comment by lantse-cap1** [comment]
> There has been no decision as yet.

noted & thank you.

**Comment by lijk8090** [comment]
Do we have a planned date, such as this month or last month?
thank you
@mattcaswell

**Comment by mattcaswell** [comment]
I expect the release to be sooner rather than later, but I can't give you a date right now.

**Comment by lijk8090** [comment]
OK, I'll be waiting it.
Thank you again.

**Comment by rajeevsikka** [comment]
Any chance this is available by end of the month? Thanks.

**Comment by levitte** [comment]
1.1.1e was released this week, see https://mta.openssl.org/pipermail/openssl-announce/2020-March/000167.html
