### ISSUE TITLE
POD warnings

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#11233]
```
*** WARNING: line containing nothing but whitespace in paragraph at line 136 in file doc/man3/OSSL_SELF_TEST_new.pod
```

It would be great if find-doc-nits could capture stderr from the internal call to pod2man :(

**Comment by richsalz** [comment]
I think @levitte fixed this, closing.

**Comment by levitte** [comment]
Kinda sorta. My fix catches the *errors*. I think that should be enough, though...
