### ISSUE TITLE
A redundant RSA-SHA1 signature in a cert chain prevents connection

### ISSUE THREAD

**Issue by xnox** [openssl/openssl#11236]
Compiled OpenSSL 1.1.1-stable branch 93c50f46809bc0bd6c39e8445a4140c034a4320d

Executed:
```
LD_LIBRARY_PATH=`pwd` ./apps/openssl s_client -showcerts -connect toodledo.com:443 -cipher DEFAULT@SECLEVEL=1 &> seclevel1.log
LD_LIBRARY_PATH=`pwd` ./apps/openssl s_client -showcerts -connect toodledo.com:443 -cipher DEFAULT@SECLEVEL=2 &> seclevel2.log
```
I expected the connection to work in both cases, but it does not at SECLEVEL 2. It seems to trip up on the last certificate in the chain, which whilst redundant, is signed with RSA-SHA1.

**Comment by xnox** [comment]
[seclevel1.txt](https://github.com/openssl/openssl/files/4283171/seclevel1.txt)
[seclevel2.txt](https://github.com/openssl/openssl/files/4283172/seclevel2.txt)

**Comment by xnox** [comment]
Also reproducible with OpenSSL master 4a98ad086a6db9a8646244bd6e6517f9fff11762

**Comment by davidben** [comment]
We've been looking at RSA-SHA1 dependencies in TLS on the Chrome side and observed this as well. Thus is ultimately an issue on the server, not the client. The client isn't the one rejecting the redundant trust anchor, rather it's the server. It appears some servers, this one included, will match the client signature algorithm list against their configured certificate chains (redundant trust anchor and all!) and reject the connection if none match. If such servers additionally configure a redundant SHA-1 trust anchor, things break. The server needs to be fixed to not send the redundant trust anchor, which is a waste of bytes anyway.

(While one might think we could fix this by rejecting RSA-SHA1 but still advertising it, many *many* more servers will preferentially sign SHA-1 if offered but sign SHA-2 when not offered. That means a client which rejects RSA-SHA1 must omit it in the ClientHello and instead we get these servers to stop sending the redundant trust anchor.)

**Comment by xnox** [comment]
Thank you for explaining this! It was obvious to me that trust anchor is redundant, but I was not sure who is at fault. Will relay this info back to them.

**Comment by xnox** [comment]
I think I need to escalate this to the ssllabs as they currently flag this up, but make it very informational, but in practice it will cause connectivity issues when client tries to enforce stronger security.

**Comment by xnox** [comment]
```
gnutls-cli -d 999 --priority 'NORMAL:%PROFILE_MEDIUM' www.toodledo.com &>gnutls.log 
```
[gnutls.log.txt](https://github.com/openssl/openssl/files/4284056/gnutls.log.txt)

So gnutls, with PROFILE_MEDIUM (which should give one 112 bits of security) still sends RSA-SHA1 in the client hello, and rejects one certificate of the chain, accepting the rest, establishing the connection.

Even at PROFILE_HIGH (128 bits of security) it still sends RSA-SHA1 in the client hello, but then rejects the certs due to small key size.

I wonder if openssl should be sending RSA-SHA1 in client hello, even if it might reject it later.

**Comment by davidben** [comment]
A redundant SHA-1 trust anchor *should* be fine, merely a waste of bytes. Security-wise, the client ignores it anyway. It's only a problem when combined with server behavior to match the configured chain against the client's preference list. It would be useful to find out what implementations do this.

On the SSL Labs side, I think a useful test would be for them to check if the server fails to connect when RSA-SHA1 is omitted.

**Comment by davidben** [comment]
> I wonder if openssl should be sending RSA-SHA1 in client hello, even if it might reject it later.

That would cause even more interop problems. From what I wrote above:

> (While one might think we could fix this by rejecting RSA-SHA1 but still advertising it, many many more servers will preferentially sign SHA-1 if offered but sign SHA-2 when not offered. That means a client which rejects RSA-SHA1 must omit it in the ClientHello and instead we get these servers to stop sending the redundant trust anchor.)

**Comment by xnox** [comment]
The implementation on the other side is older series OpenSSL
```
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.2
```

**Comment by davidben** [comment]
There may be a funny load balancer in front of it. I don't think OpenSSL 1.0.1 retained enough information about the ClientHello signature algorithms to even perform this check, but it's been a long time since I was familiar with that code. I also don't know how OpenSSL's versioning scheme for the FIPS versions works.
