### ISSUE TITLE
Cannot compile current trunk version on linux for windows with mingw

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1124]
I`m compiling on linux for windows with mingw, but with the current trunk version it fails.
```
Can't locate IPC/Cmd.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./Configure line 17.
BEGIN failed--compilation aborted at ./Configure line 17.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
```

**Comment by levitte** [comment]
What perl version do you use?

**Comment by wolftobias** [comment]
I send you the output underneath. The compile is working fine with the latest beta version openssl-1.1.0-pre5.
```
perl --version

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
```

**Comment by levitte** [comment]
May I suggest you try with a fresher checkout?  The handling of IPC::Cmd was altered a few days ago, so we now have a fallback.

**Comment by wolftobias** [comment]
Yes for sure. I'll try it next week Monday or Tuesday. Yesterday was a public holiday in Germany and today I'm out of office.

**Comment by mattcaswell** [comment]
@wolftobias  any update on this?

**Comment by mattcaswell** [comment]
Assuming this is resolved. Closing.
