### ISSUE TITLE
tls_setup_handshake:no ciphers available

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#11244]
```
version:
OpenSSL> version
OpenSSL 1.1.1c  28 May 2019
code:
SSL_CTX_set_options(sslCtx, SSL_OP_NO_SSL_MASK | SSL_OP_NO_DTLS_MASK | SSL_OP_CIPHER_SERVER_PREFERENCE);
SSL_CTX_clear_options(sslCtx, SSL_OP_NO_TLSv1_2 | SSL_OP_NO_TLSv1_3);
SSL_CTX_set_cipher_list(Ctx, TLS1_TXT_ECDHE_RSA_WITH_AES_128_GCM_SHA256);
SSL_CTX_set_ciphersuites(ctx, "");
```
```
error: 
server error:141FC0B5:SSL routines:tls_setup_handshake:no ciphers available:ssl/statem/statem_lib.c:128:No ciphers enabled for max supported SSL/TLS version
client error:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1528:SSL alert number 40
```
https://github.com/openssl/openssl/blob/97ace46e11dba4c4c2b7cb67140b6ec152cfaaf4/ssl/statem/statem_lib.c#L108-L130

https://github.com/openssl/openssl/blob/97ace46e11dba4c4c2b7cb67140b6ec152cfaaf4/ssl/s3_lib.c#L1242-L1250
lines 120  the ver_max = "0x0304",and c->min_tls="0x0303" c->max_tls = "0x0303",then the ok =0 err.

I understand that setting 1.2 version and 1.3 version should be compatible with algorithms that only set 1.2

**Comment by mattcaswell** [comment]
> I understand that setting 1.2 version and 1.3 version should be compatible with algorithms that only set 1.2

This is not correct. TLSv1.2 ciphersuites cannot be used in TLSv1.3 and vice versa. The error you are seeing is because you have cleared all ciphersuites capable of being used in TLSv1.3 but still have TLSv1.3 enabled, hence there are "No ciphers enabled for max supported SSL/TLS version".
