### ISSUE TITLE
Mingw32 builds broken by merge of PR #11110

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#11255]
Unfortunately the merge of PR #11110 broke the Mingw32 builds in Travis CI.

Example: https://travis-ci.org/openssl/openssl/jobs/655692589

**Comment by mspncp** [comment]
cc @levitte

**Comment by romen** [comment]
I didn't notice this when I wrote https://github.com/openssl/openssl/pull/11110#pullrequestreview-369477488, and looking at the output I am not sure the two issues are related, but maybe it is worth considering when looking into this issue!
