### ISSUE TITLE
How can generate share key by raw private key and peer raw public key with the method NID_X9_62_prime256v1?

### ISSUE THREAD

**Issue by kimi20071025** [openssl/openssl#11256]
The code is:

#include <stdint.h>
#include <stdio.h>
#include <openssl/ec.h>

int main()
{
	uint8_t privatekey[32] = {0x99, 0x79, 0x88, 0x58, 0xA1, 0xDC, 0x6A, 0x2C, 0x68, 0x63, 0x71, 0x49, 0xA4, 0xB1, 0xDB, 0xFD, 0x1F, 0xDF, 0xF5, 0xAD, 0xDD, 0x62, 0xA2, 0x14, 0x2F, 0x06, 0x69, 0x9E, 0xD7, 0x60, 0x25, 0x29};
	const uint8_t* p = privatekey;
		
	EC_KEY* pkey = EC_KEY_new();	
	if (!d2i_ECPrivateKey(&pkey, &p, 32)) 
	{
		printf("Deserializing private_key failed\n");
	}
			
	return 0;
}

**Comment by mattcaswell** [comment]
It's expecting a DER encoded ECPrivateKey structure as defined in RFC5915. What you have doesn't look like that. Most likely what you have is the raw private key scalar value. In which case you will have to convert the key to a BIGNUM and then set it using EC_KEY_set_private_key(). Before you do that you will also need to set the group for the EC_KEY object using EC_KEY_set_group(). Finally you will also need to set the public key using EC_KEY_set_public_key().

Note, you can calculate the public key from the private key like this:

````
pubkey = EC_POINT_new(group);
EC_POINT_mul(group, pubkey, priv, NULL, NULL, NULL);
````

**Comment by kimi20071025** [comment]
> It's expecting a DER encoded ECPrivateKey structure as defined in RFC5915. What you have doesn't look like that. Most likely what you have is the raw private key scalar value. In which case you will have to convert the key to a BIGNUM and then set it using EC_KEY_set_private_key(). Before you do that you will also need to set the group for the EC_KEY object using EC_KEY_set_group(). Finally you will also need to set the public key using EC_KEY_set_public_key().
> 
> Note, you can calculate the public key from the private key like this:
> 
> ```
> pubkey = EC_POINT_new(group);
> EC_POINT_mul(group, pubkey, priv, NULL, NULL, NULL);
> ```

Thank you for your reply, In fact, my original demand is to get the share key by raw private key and peer raw public key with the NID_X9_62_prime256v1 method. Is there any API functions for me? If not, how can I get the share key?

**Comment by mattcaswell** [comment]
> get the share key

I assume you mean "get a shared secret using ECDH".

> by raw private key

First you will need to create an EVP_PKEY for your private key. Something like this (completely untested - and with error checking omitted for brevity):

````
EC_KEY *eckey = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
const EC_GROUP *group = EC_KEY_get0_group(eckey);
EC_POINT *pubpt = EC_POINT_new(group);
EVP_PKEY *privpkey = EVP_PKEY_new();

EC_KEY_oct2priv(eckey, privatekey, sizeof(privatekey));
EC_POINT_mul(group, pubpt, EC_KEY_get0_private_key(eckey), NULL, NULL, NULL);
EC_KEY_set_public_key(eckey, pubpt);
EVP_PKEY_assign_EC_KEY(privpkey, eckey);
````

> peer raw public key

What exactly this means is unclear. Probably something like this:

````
EC_KEY *pubeckey = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
EVP_PKEY *pubpkey = EVP_PKEY_new();

EC_KEY_oct2key(pubeckey, publickey, sizeof(publickey));
EVP_PKEY_assign_EC_KEY(pubpkey, eckey);
````

To the derive a shared secret you need to use `EVP_PKEY_derive`. E.g. see code here:

https://wiki.openssl.org/index.php/EVP_Key_Agreement

**Comment by kimi20071025** [comment]
> > get the share key
> 
> I assume you mean "get a shared secret using ECDH".
> 
> > by raw private key
> 
> First you will need to create an EVP_PKEY for your private key. Something like this (completely untested - and with error checking omitted for brevity):
> 
> ```
> EC_KEY *eckey = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
> const EC_GROUP *group = EC_KEY_get0_group(eckey);
> EC_POINT *pubpt = EC_POINT_new(group);
> EVP_PKEY *privpkey = EVP_PKEY_new();
> 
> EC_KEY_oct2priv(eckey, privatekey, sizeof(privatekey));
> EC_POINT_mul(group, pubpt, EC_KEY_get0_private_key(eckey), NULL, NULL, NULL);
> EC_KEY_set_public_key(eckey, pubpt);
> EVP_PKEY_assign_EC_KEY(privpkey, eckey);
> ```
> 
> > peer raw public key
> 
> What exactly this means is unclear. Probably something like this:
> 
> ```
> EC_KEY *pubeckey = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
> EVP_PKEY *pubpkey = EVP_PKEY_new();
> 
> EC_KEY_oct2key(pubeckey, publickey, sizeof(publickey));
> EVP_PKEY_assign_EC_KEY(pubpkey, eckey);
> ```
> 
> To the derive a shared secret you need to use `EVP_PKEY_derive`. E.g. see code here:
> 
> https://wiki.openssl.org/index.php/EVP_Key_Agreement

Thank you very much, I will try it later.

**Comment by MQader** [comment]
@mattcaswell could I ask for this specific NID_X9_62_prime256v1, how can we use EVP_PKEY_new_raw_public_key() if the I as 
a TLS server received the TLS client's public key in the keyExchange... Is it supported to get the EVP_PKEY from rawdata of such NID ? 
is there any other way? otherwise how we can derive the shared secret if we can't derive the public key (EVP_PKEY) ?  

Thanks!
