### ISSUE TITLE
trying to build in home directory

### ISSUE THREAD

**Issue by LarsOde** [openssl/openssl#11259]
Hello,

on a server where I have no root and an old openssl version, I'm trying to build the current version openssl-1.1.1d for use in my home directory. I followed this:
https://github.com/magnumripper/JohnTheRipper/wiki/Howto-build-non-root-when-system-does-not-have-OpenSSL
but I don't understand the part with 

> # to build john with this setup
>$ cd john_source_location       (wherever you placed the JtR tree, into the ./src directory)
>$ ./configure OPENSSL_CFLAGS="-I~/ssl" OPENSSL_LIBS="-L~/ssl/lib -lcrypto -lssl"
>$y make -sj4

what location is meant with john_source_location? I searched the source directory for a "configure" and couldn't find one, only the "Configure" for building
This is probably the reason I get an error from openssl:
>./openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by mspncp** [comment]
`john_source_location` nothing else but the name [John the Ripper](https://avatars2.githubusercontent.com/u/1268598?s=400&v=4) chose for his source directory ;-)

But now seriously: you can always _build_ OpenSSL without root privileges. In fact, it is recommended to build as normal user and only do an installation as root user. Your real problem is that you would like to _install_ your self built OpenSSL somewhere inside your home directory.

To do that, you can use the `--prefix` configure option to change the location of the installation directory. Try something like this:

```
./config --prefix=/home/yourname/openssl
```

**Comment by mspncp** [comment]
For more details, see [installation instruction](https://github.com/openssl/openssl/blob/master/INSTALL.md#directories).

**Comment by levitte** [comment]
This is the part that explains installing OpenSSL in your own directory:

> ```
> # now get the source (again, the proper file to download will likely be different)
> $ cd sslsrc
> $ wget www.openssl.org/source/openssl-1.0.2d.tar.gz
> $ tar xf openssl-1.0.2d.tar.gz
> $ cd openssl-1.0.2d
> $ ./Configure --prefix=~/ssl linux-x86_64       (Note, if your system is not linux-x86_64, you will have > to pick the right one)
> $ make -sj4 build_libs      (or gmake, or whatever 'make' tool is on your system)
> $ make -s test
> $ make install_sw           (I like installing without using -s to 'see' what is done)
> ```

**Comment by mspncp** [comment]
I beat you this time, @levitte :-P

**Comment by mspncp** [comment]
> To do that, you can use the `--prefix` configure option to change the location of the installation directory. Try something like this:
> 
> ```
> ./config --prefix=/home/yourname/openssl
> ```

After that, run `make && make install` (without sudo).

**Comment by LarsOde** [comment]
I did this:
>./Configure --prefix=/home/av01nqi/ssl linux-x86_64
>make -sj4 build_libs
>make -s test
>make install_sw
shouldn't that work?

**Comment by LarsOde** [comment]
solved it... of course on needs to set LD_LIBRARY_PATH and LDFLAGS accordingly ;)
