### ISSUE TITLE
openssl 1.1.1d  does not compile on Linux 

### ISSUE THREAD

**Issue by MoMuBud** [openssl/openssl#11268]
I am trying to compile openssl 1.1.1d on  

cat /etc/oracle-release
Oracle Linux Server release 6.4

./Configure linux-elf shared threads no-ssl3 --prefix=/var/tmp/dest --openssldir=/var/tmp/dest

failing make output:

gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -fomit-frame-pointer -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/var/tmp/dest\"" -DENGINESDIR="\"/var/tmp/dest/lib/engines-1.1\"" -DNDEBUG  -c -o crypto/aes/aesni-x86.o crypto/aes/aesni-x86.s
crypto/aes/aesni-x86.s: Assembler messages:
crypto/aes/aesni-x86.s:363: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:364: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:365: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:366: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:587: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:588: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:589: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:590: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:598: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:599: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:600: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:601: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:675: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:676: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:677: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:678: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:686: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:687: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:688: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:689: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:798: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:799: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:800: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:801: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:809: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:810: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:811: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:812: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1036: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1037: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1038: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1039: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1047: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1048: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1049: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1050: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1396: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1397: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1398: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1399: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1407: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1408: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1409: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1410: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1786: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1787: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1788: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1789: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1797: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1798: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1799: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1800: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2181: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2182: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2183: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2184: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2192: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2193: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2194: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2195: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2576: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2577: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2578: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2579: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2587: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2588: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2589: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2590: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2837: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2838: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2839: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2840: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2846: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2847: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2854: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3159: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3160: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3165: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3166: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3172: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3173: Error: suffix or operands invalid for `pop'
make[1]: *** [crypto/aes/aesni-x86.o] Error 1
make[1]: Leaving directory `/var/tmp/openssl-1.1.1d'
make: *** [all] Fehler 2
[root@llg00hvo openssl-1.1.1d]# echo $?
2

Output of:
perl configdata.pm --dump

Command line (with current working directory = .):

    /usr/bin/perl ./Configure linux-elf shared threads no-ssl3 --prefix=/var/tmp/dest --openssldir=/var/tmp/dest

Perl information:

    /usr/bin/perl
    5.10.1 for x86_64-linux-thread-multi

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c\+\+
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [too-old-kernel]
    asan                    [default]        OPENSSL_NO_ASAN
    crypto-mdebug           [default]        OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]        OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]        OPENSSL_NO_EGD
    external-tests          [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]        OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]        OPENSSL_NO_HEARTBEATS
    md2                     [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]        OPENSSL_NO_MSAN
    rc5                     [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]        OPENSSL_NO_SCTP
    ssl-trace               [default]        OPENSSL_NO_SSL_TRACE
    ubsan                   [default]        OPENSSL_NO_UBSAN
    unit-test               [default]        OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]
    zlib-dynamic            [default]
    ssl3                    [option]         OPENSSL_NO_SSL3
    ssl3-method             [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3 -fomit-frame-pointer",
    CXX => "g++",
    CXXFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c vpaes-x86.s aesni-x86.s",
    aes_obj => "aes_core.o aes_cbc.o vpaes-x86.o aesni-x86.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf-586.s",
    bf_obj => "bf-586.o",
    bn_asm_src => "bn-586.s co-586.s x86-mont.s x86-gf2m.s",
    bn_obj => "bn-586.o co-586.o x86-mont.o x86-gf2m.o",
    bn_ops => "BN_LLONG",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-pthread",
    chacha_asm_src => "chacha-x86.s",
    chacha_obj => "chacha-x86.o",
    cmll_asm_src => "cmll-x86.s",
    cmll_obj => "cmll-x86.o",
    cppflags => "",
    cpuid_asm_src => "x86cpuid.s",
    cpuid_obj => "x86cpuid.o",
    cxxflags => "-std=c++11 -pthread",
    defines => [  ],
    des_asm_src => "des-586.s crypt586.s",
    des_obj => "des-586.o crypt586.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-x86.s",
    ec_obj => "ecp_nistz256.o ecp_nistz256-x86.o",
    enable => [ "afalgeng" ],
    ex_libs => "-ldl -pthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DOPENSSL_USE_NODELETE -DL_ENDIAN",
    lib_defines => [  ],
    md5_asm_src => "md5-586.s",
    md5_obj => "md5-586.o",
    modes_asm_src => "ghash-x86.s",
    modes_obj => "ghash-x86.o",
    module_cflags => "-fPIC",
    module_cxxflags => "",
    module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    padlock_asm_src => "e_padlock-x86.s",
    padlock_obj => "e_padlock-x86.o",
    perlasm_scheme => "elf",
    poly1305_asm_src => "poly1305-x86.s",
    poly1305_obj => "poly1305-x86.o",
    rc4_asm_src => "rc4-586.s",
    rc4_obj => "rc4-586.o",
    rc5_asm_src => "rc5-586.s",
    rc5_obj => "rc5-586.o",
    rmd160_asm_src => "rmd-586.s",
    rmd160_obj => "rmd-586.o",
    sha1_asm_src => "sha1-586.s sha256-586.s sha512-586.s",
    sha1_obj => "sha1-586.o sha256-586.o sha512-586.o",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,--version-script=",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-soname=",
    shared_target => "linux-shared",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c wp-mmx.s",
    wp_obj => "wp_block.o wp-mmx.o",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = ar
    ARFLAGS         = r
    CC              = gcc
    CFLAGS          = -Wall -O3 -fomit-frame-pointer
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXX             = g++
    CXXFLAGS        = -Wall -O3
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          =
    PERL            = /usr/bin/perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl

running make test also fails:
gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -fomit-frame-pointer -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/var/tmp/dest\"" -DENGINESDIR="\"/var/tmp/dest/lib/engines-1.1\"" -DNDEBUG  -c -o crypto/aes/aesni-x86.o crypto/aes/aesni-x86.s
crypto/aes/aesni-x86.s: Assembler messages:
crypto/aes/aesni-x86.s:363: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:364: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:365: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:366: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:587: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:588: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:589: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:590: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:598: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:599: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:600: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:601: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:675: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:676: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:677: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:678: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:686: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:687: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:688: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:689: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:798: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:799: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:800: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:801: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:809: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:810: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:811: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:812: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1036: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1037: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1038: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1039: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1047: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1048: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1049: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1050: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1396: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1397: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1398: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1399: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1407: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1408: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1409: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1410: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1786: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1787: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1788: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1789: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:1797: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1798: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1799: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:1800: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2181: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2182: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2183: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2184: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2192: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2193: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2194: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2195: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2576: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2577: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2578: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2579: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2587: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2588: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2589: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2590: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2837: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2838: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2839: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2840: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:2846: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2847: Error: suffix or operands invalid for `push'
crypto/aes/aesni-x86.s:2854: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3159: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3160: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3165: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3166: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3172: Error: suffix or operands invalid for `pop'
crypto/aes/aesni-x86.s:3173: Error: suffix or operands invalid for `pop'
make[1]: *** [crypto/aes/aesni-x86.o] Error 1
make[1]: Leaving directory `/var/tmp/openssl-1.1.1d'
make: *** [tests] Fehler 2
[root@llg00hvo openssl-1.1.1d]# echo $?
2

**Comment by levitte** [comment]
What happens if you try this? 
```
./config shared threads no-ssl3 --prefix=/var/tmp/dest --openssldir=/var/tmp/dest
```

**Comment by MoMuBud** [comment]
> What happens if you try this?
> 
> ```
> ./config shared threads no-ssl3 --prefix=/var/tmp/dest --openssldir=/var/tmp/dest
> ```

./config shared threads no-ssl3 --prefix=/var/tmp/dest --openssldir=/var/tmp/dest
Operating system: x86_64-whatever-linux2

/usr/local/bin/perl5: error while loading shared libraries: libdb.so.3: cannot open shared object file: No such file or directory
/usr/local/bin/perl5: error while loading shared libraries: libdb.so.3: cannot open shared object file: No such file or directory
This system (linux-x86_64) is not supported. See file INSTALL for details.

**Comment by MoMuBud** [comment]
Any idea how to solve this issue?

**Comment by MoMuBud** [comment]
I was able to compile using an implicit OS by running:
./Configure linux-x86_64 shared threads no-ssl3 --prefix=/var/tmp/dest --openssldir=/var/tmp/dest
There is probably a way to give "./config" this argument as well but  I couldn't find it quick.
If this is not a bug of identifying the OS feel free to close this issue.

**Comment by t8m** [comment]
linux-elf is 32 bit x86 target. linux-x86_64 is 64 bit x86 target.
