### ISSUE TITLE
openSSL ts command in Javascript

### ISSUE THREAD

**Issue by MarcGodard** [openssl/openssl#11269]
Please forgive me if this exists, but calling something `timestamp` makes it hard to find.

I am looking for a javascript implementation of the 'ts' commands for TSA.

I did find `node-forge` https://github.com/digitalbazaar/forge, but it doesn't have the 'ts' commands.

I am not a `C` programmer and though looking at the code I could see if the `ts` stuff is just a combination of `node-forge` exiting commands so I could do it with it, but it is over my head :(

Sorry for the long preamble, but my questions are:

1) Am I right that the `ts` commands are a combination of other crypto with parsing, therefore can be made into `js` using the `node-forge` lib?

2) If so, is there spec documents that can help me accomplish this without reading the `C` code?

**Comment by t8m** [comment]
Apparently nobody knows the answers and it is only remotely related to the OpenSSL project. Closing.
