### ISSUE TITLE
Test case "./evptest recipes/30-test_evp_data/evppkey.txt" got about 9 errors

### ISSUE THREAD

**Issue by xkqian** [openssl/openssl#11265]
Get the OpenSSL source code, configure and compile, then install it. test the evp cases one by one, when execute this case "$cd test; $./evp_test recipes/30-test_evp_data/evppkey.txt", it report errors like this: "# Completed 1445 tests with 9 errors and 0 skipped". Seems some return value of the pkey cause this error.

**Comment by levitte** [comment]
`ldd test/evp_test`

Does it tell you the .so libraries you expected?

**Comment by mattcaswell** [comment]
> Get the OpenSSL source code,

Are you on the master branch?

> "$cd test; $./evp_test recipes/30-test_evp_data/evppkey.txt"

If you run the tests directly like this you have to be careful to setup environment variables such as `OPENSSL_CONF`. It might be better to look at the output from this:

````
make TESTS=test_evp V=1 test
````

**Comment by xkqian** [comment]
> > Get the OpenSSL source code,
> 
> Are you on the master branch?
------------->Yes, I am on the master branch.
> 
> > "$cd test; $./evp_test recipes/30-test_evp_data/evppkey.txt"
> 
> If you run the tests directly like this you have to be careful to setup environment variables such as `OPENSSL_CONF`. It might be better to look at the output from this:
> 
> ```
> make TESTS=test_evp V=1 test
> ```
-------------This is what I am confused，if I run the "make test", it passed without any complain, but once I run it directly, it report error.  Before this commit: "ae9e0698df7672977f0c7c88f3b3c2b695c14611", the result of the direct test "$cd test; $./evp_test recipes/30-test_evp_data/evppkey.txt" is pass. I am not sure what did you changed, if you have some parameters, can you tell me to have a try?

**Comment by xkqian** [comment]
> `ldd test/evp_test`
> 
> Does it tell you the .so libraries you expected?

Yes, it tell me the libraries,like this:

> "
xiaqia01@xiaqia01-01-arm-vm:~/work/ci-scripts/upstream_openssl$ ldd test/evp_test
        linux-vdso.so.1 (0x0000ffffbf6fd000)
        libcrypto.so.3 => /home/xiaqia01/work/ci-scripts/openssl-install-tmp/lib/libcrypto.so.3 (0x0000ffffbf36d000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffbf32c000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffbf1d3000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffbf6d2000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffbf1be000)

"

**Comment by mattcaswell** [comment]
> if I run the "make test", it passed without any complain, 

Hmm. The errors you see are:

````
    # recipes/30-test_evp_data/evppkey.txt:369: Expected VERIFY_ERROR got PKEY_CTRL_ERROR
````

The commit you refer to is this one:

```` diff
commit ae9e0698df7672977f0c7c88f3b3c2b695c14611
Author:     Richard Levitte <levitte@openssl.org>
AuthorDate: Tue Dec 3 11:02:58 2019 +0100
Commit:     Richard Levitte <levitte@openssl.org>
CommitDate: Sat Feb 22 01:07:16 2020 +0100

    test/recipes/30-test_evp_data/evppkey.txt
    
    Tests that go through provider cannot recognise PKEY_CTRL_INVALID from
    PKEY_CTRL_ERROR any more, because provided implementations' param
    setting functions return 0 or 1.
    
    Reviewed-by: Shane Lontis <shane.lontis@oracle.com>
    Reviewed-by: Tomas Mraz <tmraz@fedoraproject.org>
    (Merged from https://github.com/openssl/openssl/pull/10557)

diff --git a/test/recipes/30-test_evp_data/evppkey.txt b/test/recipes/30-test_evp_data/evppkey.txt
index 1ca16572c4..e649e92c3f 100644
--- a/test/recipes/30-test_evp_data/evppkey.txt
+++ b/test/recipes/30-test_evp_data/evppkey.txt
@@ -414,7 +414,7 @@ Reason = operation not supported for this keytype
 Sign = RSA-2048
 Availablein = default
 Ctrl = rsa_mgf1_md:sha1
-Result = PKEY_CTRL_INVALID
+Result = PKEY_CTRL_ERROR
 Reason = invalid mgf1 md
 
 # RSA PSS key tests
````

The difference between running it via "make test" and running it directly is that the former explicitly sets the OPENSSL_CONF environment variable to point to a config file which explicitly loads specific providers.

It looks to me like when you don't explicitly load a provider we end up getting different error messages to when we explicitly load one. This is slightly surprising I would expect not setting a config file would automatically load the default provider and it should work the same way as if we had loaded the test/default.cnf file.

@levitte - care to comment?

**Comment by levitte** [comment]
There should be no need for OPENSSL_CONF, as that particular test is specifically or the default provider, which is built in.

However, if the installed files, in particular /home/xiaqia01/work/ci-scripts/openssl-install-tmp/lib/libcrypto.so.3, is older than the latest source checkout, then that installed libcrypto.so.3 may have been built before ae9e0698df7672977f0c7c88f3b3c2b695c14611, and I can see how that could generate an error.

@xkqian, testing is normally done *in the build directory*.  We have a special script that adjusts the necessary environment to use the .so files that are in the build directory (this is what the test suite does).  If you can see a `util/wrap.pl`, then use it like this:

```
./util/wrap.pl test/evp_test test/recipes/30-test_evp_data/evppkey.txt
```

Otherwise, use the older `util/shlib_wrap.sh`:

```
./util/shlib-wrap.pl test/evp_test test/recipes/30-test_evp_data/evppkey.txt
```

**Comment by mattcaswell** [comment]
@levitte - I see the same problems using shlib_wrap.sh

**Comment by xkqian** [comment]
@levitte - I can't find the file ./util/wrap.pl, with the "./util/shlib-wrap.sh test/evp_test test/recipes/30-test_evp_data/evppkey.txt", I got the same result with mattcaswell, and even got one more error, now it's 10 errors.

**Comment by xkqian** [comment]
@levitte Hi, Is ther any progress about the issue?  Or should we fix it?

**Comment by xkqian** [comment]
has been fixed by the commit:
"
commit d3b2f8760a56da3e70c30e5614181f3798e4ad54
Author: Richard Levitte <levitte@openssl.org>
Date:   Tue Mar 17 14:41:59 2020 +0100

    evp_test: the tests using MDC2 need the legacy provider

    This was always a potential, we just haven't seen this need before now.

"

**Comment by levitte** [comment]
Thanks for confirming that.
