### ISSUE TITLE
OSSL_PARAM_allocate_from_text talks about non-existing varabiables

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#11276]
The OSSL_PARAM_allocate_from_text() manpage talks about `buf` and `buf_n`. I have no idea what is meant with them. OSSL_PARAM also doesn't contain such variables.

**Comment by kroeckx** [comment]
Maybe it's `value` and `value_n`?

**Comment by kroeckx** [comment]
But `value_n` can't be NULL ...

**Comment by levitte** [comment]
Oh my, that page was quite badly edited...

PR coming up!

**Comment by levitte** [comment]
#11279
