### ISSUE TITLE
OpenSSL versioning

### ISSUE THREAD

**Issue by bagajjal** [openssl/openssl#11274]
Why there are multiple versions released on the same date?
What is the difference between them?

![image](https://user-images.githubusercontent.com/23668037/76133926-b9e6c880-5fcf-11ea-88ea-0e5e595e9505.png)

**Comment by mspncp** [comment]
OpenSSL versions 1.0.2, 1.1.0, and 1.1.1 are different stable releases. Version 1.1.1 is the newest one and it is the only one which is currently still supported.  The letters at the end denote bugfix releases, and the page https://www.openssl.org/source will point you to the most current one. According to it, 1.1.1d is the  most current bugfix release of the only stable branch we currently support.

(Note that version 1.0.2 and versions >= 1.1.0 are not source compatible. So if you have application code which relies on that version, it requires adopting your code to the newer version.)

**Comment by extrimexxx** [comment]
when is 1.1.1e planned to be released ?

**Comment by mattcaswell** [comment]
> when is 1.1.1e planned to be released ?

No news on this yet.
