### ISSUE TITLE
Error: invalid field name for 'countryName_min' and similar size fields

### ISSUE THREAD

**Issue by lucafrancescato** [openssl/openssl#11287]
I cannot create a CSR from a configuration file.
```
problems making Certificate Request
4771307116:error:0DFFF07A:asn1 encoding routines:CRYPTO_internal:first num too large:<path to resource>/asn1/a_object.c:112:
4771307116:error:0BFFF077:x509 certificate routines:CRYPTO_internal:invalid field name:<path to resource>/x509/x509name.c:303:name=countryName_min
```

This is the command:
```
openssl req -new -config ca.cnf -key private/key.pem -out certreqs/csr.pem
```

This is the relevant part of the configuration file:
```
[ req ]

# other key=value pairs omitted
prompt             = no
string_mask        = utf8only
utf8               = yes
distinguished_name = req_distinguished_name

[ req_distinguished_name ]

countryName                = US
countryName_min            = 2
countryName_max            = 2

stateOrProvinceName        = State
stateOrProvinceName_max    = 25

localityName               = Locality
localityName_max           = 25

0.organizationName         = Example Name, Limited

organizationalUnitName     = IT
organizationalUnitName_max = 8

commonName                 = Example Name
commonName_max             = 64
```

While if in the configuration file I comment out:
```
# prompt = no
```
then I can create the CSR with no errors.

If I comment out 'contryName_min', the same error will appear for 'countryName_max', and so on for the other size fields.

**Comment by stawii** [comment]
Double check what `prompt=no` do - it takes all values literally, so you cannot define `*_min`, `*_max` and `*_default`.

**Comment by lucafrancescato** [comment]
If I understand correctly now, `*_min`, `*_max` and `*_default` should be used only when prompt=no is commented out, that is for validating user input.

If my understanding is correct, please close the issue.
Thanks for your help.

**Comment by t8m** [comment]
> If my understanding is correct, please let me know and I will close the issue.

Yes, it is correct. Closing.
