### ISSUE TITLE
OpenSSL ca command not able to parse input params correctly

### ISSUE THREAD

**Issue by salemba** [openssl/openssl#11283]
I'm trying to apply an Ambari process to recreate the Ambari SSLCertificate Authority using the process described [here Section 3.11](https://docs.cloudera.com/HDPDocuments/Ambari-2.6.2.0/bk_ambari-security/bk_ambari-security.pdf) 
The automated process fails while trying to run this command:

`openssl ca -create_serial -out /var/lib/ambari-server/keys/ca.crt -days 365 -keyfile /var/lib/ambari-server/keys/ca.key -key **** -selfsign -extensions jdk7_ca -config /var/lib/ambari-server/keys/ca.config -batch -infiles /var/lib/ambari-server/keys/ca.csr`

The reported error is not very explicit : `an error occurred parsing the command options`.

When I run the same command manually, I'm getting a weird parse error:
`unknown option Desktop`

OS properties :
Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: **Linux 3.10.0-957.el7.x86_64**
      Architecture: x86-64

Openssl version : **OpenSSL 1.0.2k-fips  26 Jan 2017**

I tried rewrting the command manually instead of paste/copy, but got the same result.

Any idea about this issue?

**Comment by levitte** [comment]
Does the argument to `-key` contain spaces?  In that case, you need to surround it with quotes.
