### ISSUE TITLE
util/check-format.pl

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#11284]
This code:

https://github.com/openssl/openssl/blob/99a16e0459e5089c2cfb92ee775f1221a51b8d05/providers/implementations/keymgmt/rsa_kmgmt.c#L400-L408

... generated this report:

```
providers/implementations/keymgmt/rsa_kmgmt.c:402:'for' { 1 stmt }:        ok = ok && rsa_validate_pairwise(rsa);
```

That doesn't seem quite right, since the `else` part contains multiple statements.

**Comment by DDvO** [comment]
This has been fixed by #11285.
