### ISSUE TITLE
[FreeBSD] Failure!  build file wasn't produced.

### ISSUE THREAD

**Issue by zoujiaqing** [openssl/openssl#11286]
```bash
./config --prefix=/usr --openssldir=/etc/pki/tls enable-ec_nistp_64_gcc_128 --system-ciphers-file=/etc/crypto-policies/back-ends/openssl.config zlib enable-camellia enable-seed enable-rfc3779 enable-sctp enable-cms enable-md2 enable-rc5 enable-ssl3 enable-ssl3-method enable-weak-ssl-ciphers no-mdc2 no-ec2m no-sm2 no-sm4 shared freebsd-x86_64 -O2 -g
Operating system: amd64-whatever-freebsd

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

target already defined - BSD-x86_64 (offending arg: freebsd-x86_64)
```

**Comment by levitte** [comment]
> target already defined - BSD-x86_64 (offending arg: freebsd-x86_64)

This says it all, simply remove that argument from your configuration command line and you'll be fine.

**Comment by zoujiaqing** [comment]
Thanks! openssl can overwrite this arg?

**Comment by levitte** [comment]
`./config` is a kinda hack that tries to guess what the appropriate config target should be, and doesn't look at all at the arguments it already has.  What it does is to simply call `./Configure` with the result, roughly like this:

```
exec perl ./Configure $GUESS "$@"
```

So what `./Configure` ends up with is a command line with *two* config targets, and that's simply confusing, especially if they aren't the same.

Note that there's an effort, #11230, that should take away exactly this kind of problem.  I hope to have it done for OpenSSL 3.0.

**Comment by FluffyPancakeLove** [comment]
thank you, i had the same problem on debian 8.9
