### ISSUE TITLE
Continue on UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by misery** [openssl/openssl#11297]
We like to request that it is possible (maybe by an explicit option) to continue certificate verification even if UNABLE_TO_VERIFY_LEAF_SIGNATURE is thrown.

We are implementing the official eID-Client of the German identity card. The whole system is defined by a technical guideline of the Federal Office for Information Security. [1]

The identity card uses NFC to establish a connection between server and the card itself. These connections are also secured by TLS. It is not possible to use root-CAs from system truststore as the German eID infrastructure uses it's own trust anchor. This trust anchor is a CVC (Card Verifiable Certificate) which is verified by the card itself. The CVC contains hash values of the allowed TLS certificates.

When we establish a secured connection via TLS we need to check certain things like certificate validity. But as we don't have a root CA we need to ignore "UNABLE_TO_VERIFY_LEAF_SIGNATURE" error. Even though the content of the certificate MIGHT be compromised we MUST do plausibility checks (like validity) because we can approve it LATER with our received CVC. However, openssl stops the whole validation. This breaks our workflow as it would allow that an expired certificate is not fatal.

We checked mbedtls and gnutls. Those implementations throw a similar error but don't stop the whole verification.

It is not possible to enforce all eID service providers to send the WHOLE certificate chain including the root-CA. See RFC5246 section-7.4.2.
```
   certificate_list
      This is a sequence (chain) of certificates.  The sender's
      certificate MUST come first in the list.  Each following
      certificate MUST directly certify the one preceding it.  Because
      certificate validation requires that root keys be distributed
      independently, the self-signed certificate that specifies the root
      certificate authority MAY be omitted from the chain, under the
      assumption that the remote end must already possess it in order to
      validate it in any case.
```

[1] https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03124/TR-03124-1.pdf?__blob=publicationFile&v=2

[2] https://tools.ietf.org/html/rfc5246#section-7.4.2

**Comment by richsalz** [comment]
You can do that by writing your own verify callback that masks the error.  Look at apps/verify.c for example.

**Comment by misery** [comment]
Are you sure that should work with UNABLE_TO_VERIFY_LEAF_SIGNATURE?

We uses Qt has framework which uses a custom verify callback. They allow to ignore certain ssl errors. We can ignore any error except UNABLE_TO_VERIFY_LEAF_SIGNATURE.
https://code.qt.io/cgit/qt/qtbase.git/tree/src/network/ssl/qsslsocket_openssl.cpp#n525

Also it looks like the whole verification will be stoped here as it immediately return and cannot go to "check_cert:" in line 1757.
https://github.com/openssl/openssl/blob/master/crypto/x509/x509_vfy.c#L1725

**Comment by richsalz** [comment]
> Are you sure that should work with UNABLE_TO_VERIFY_LEAF_SIGNATURE?

It should but I have not tried to do so.

> We uses Qt has framework which uses a custom verify callback.

I didn't know you were doing that.  I don't know what you would have to do to work with QT.

**Comment by misery** [comment]
> > Are you sure that should work with UNABLE_TO_VERIFY_LEAF_SIGNATURE?
> 
> It should but I have not tried to do so.

It immediately stops verification because openssl "returns" on THAT error. Any other error is not a problem.

I tried it with "openssl s_client", too. Expiration is not checked anymore after that error.

**Comment by richsalz** [comment]
I was suggesting you write a custom verify callback and mask that error.

**Comment by misery** [comment]
Sorry, I was not clear enough. :-)

I already did that - but that won't help.

**Comment by misery** [comment]
https://github.com/openssl/openssl/blob/master/crypto/x509/x509_vfy.c#L1725
```
            return verify_cb_cert(ctx, xi, 0,
                                  X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE);
```

That should be like this because all other callbacks are executed the same way.
```
  if(!verify_cb_cert(ctx, xi, 0,
                                  X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE))
     return 0;
```

That should be handled like a self-signed certificate like mentioned some lines later.
```
      /*
         * Skip signature check for self signed certificates unless explicitly
         * asked for.  It doesn't add any security and just wastes time.  If
         * the issuer's public key is unusable, report the issuer certificate
         * and its depth (rather than the depth of the subject).
         */
```

**Comment by bernd-edlinger** [comment]
Have you tried X509_V_FLAG_PARTIAL_CHAIN ?

**Comment by kaduk** [comment]
I'm not entirely sure that the spec at https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03124/TR-03124-1.pdf?__blob=publicationFile&v=2 is a particularly good one to use.  I only skimmed it, but it looks like it's advocating a "listen on localhost on a specific port" model that is not guaranteed to actually result in communication with the desired entity, and I'm also concerned about the usage of certificates for conveying additional information.  It sounds like the verification procedures for the certificate may be influenced by the contents of the certificate in a way that can lead to attacks unless the additional information in the certificate is additionally validated against some out-of-band channel.

**Comment by misery** [comment]
> Have you tried X509_V_FLAG_PARTIAL_CHAIN ?

No, Qt don't have an API for that. That would be another feature request there. They don't accept a lot of crypto library specific stuff because they supports multiple backends.

But why another parameter to skip the whole callback of X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE? In my opinion that error should be maskable like all other errors like @richsalz suggested.

**Comment by misery** [comment]
What are the disadvantages if it can be masked by the application? I don't see why it should not be merged.

**Comment by DDvO** [comment]
This is solved for the master but not yet for 1.1.1.

**Comment by misery** [comment]
Fixed for me. :-) Thank you very much!

**Comment by DDvO** [comment]
> Fixed for me. :-) Thank you very much!

You are welcome.
Glad that this backport was accepted during the OTC vote -  with a very narrow margin.

**Comment by jerenkrantz** [comment]
As a note - we're hitting this change as a regression in apache/serf - our test cases with a leaf (no CA chain present) are now seeing the verify_cb_cert get triggered multiple times.  The first time receives the failure, the second time receives success.  Since we're only expecting to receive invalid certs, we're treating the second call as an unexpected success...

Up to and including 1.1.1h, OpenSSL would stop processing the certificate after sending along the leaf error to the app callback.  In -stable and master, if the app's callback doesn't return a failure, it will then proceed to the date check portion (check_cert_time) - which then triggers a successful verification app callback.

So, I'm guessing the change is that downstream apps have to forcibly error out from our callback if we want to abort?  Are we the only client that this will trip up?  It might be good to denote this in the Changelogs - 1.1.1h was fine, but 1.1.1i wasn't.  (Maybe the accidental cert breakage in 1.1.1h masked this issue from surfacing earlier?)

dev@serf.apache.org thread:
https://lists.apache.org/thread.html/r7dcac67871b30cc565dc7655414b8ccbe2f08051aa0f17de9c0b53e8%40%3Cdev.serf.apache.org%3E

Debian bug tracker link:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978353

**Comment by kroeckx** [comment]
In the callback you decide what OpenSSL should do: ignore the error and continue or abort. It seems that you're telling it to ignore the error.

I'm not sure how the test works, but X509_verify_cert() should return the same if the certificate has not expired.
