### ISSUE TITLE
[FreeBSD] ld: error: ./libssl.so: undefined reference to secure_getenv

### ISSUE THREAD

**Issue by zoujiaqing** [openssl/openssl#11295]
Build is ok, but link error : (

```bash
./config --prefix=/usr --openssldir=/etc/pki/tls enable-ec_nistp_64_gcc_128 --system-ciphers-file=/etc/crypto-policies/back-ends/openssl.config zlib enable-camellia enable-seed enable-rfc3779 enable-sctp enable-cms enable-md2 enable-rc5 enable-ssl3 enable-ssl3-method enable-weak-ssl-ciphers no-mdc2 no-ec2m no-sm2 no-sm4 shared -Wa,--noexecstack -DPURIFY -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fstack-protector-strong
Operating system: amd64-whatever-freebsd

...

ld: error: ./libssl.so: undefined reference to secure_getenv
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[1]: stopped in /usr/home/zoujiaqing/rpmbuild/BUILD/openssl-1.1.1d
*** Error code 1
```

**Comment by levitte** [comment]
The code does pay attention to GLIBC versions, as you can see for yourself:

https://github.com/openssl/openssl/blob/99a16e0459e5089c2cfb92ee775f1221a51b8d05/crypto/getenv.c#L19-L24

It's possible, though, that we need to guard it a little more and check that  `__GNUC__` is defined ass well.  @bernd-edlinger, you are knowledgable in this area, can you say a word or two?

**Comment by zoujiaqing** [comment]
Thanks @levitte !
But freebsd not has glibc : (

**Comment by bernd-edlinger** [comment]
You are using gcc, right?
Can you try this "gcc -g3 -x c -E /dev/null |grep GLIBC"
what does it output?

**Comment by zoujiaqing** [comment]
I used clang9 ..

**Comment by bernd-edlinger** [comment]
Oh, and why are you using enable-ec_nistp_64_gcc_128 ?

**Comment by zoujiaqing** [comment]
I looks FreeBSD ports has this arg item:
https://svnweb.freebsd.org/ports/head/security/openssl/Makefile?revision=521932&view=markup#l107

I need remove this arg item?

**Comment by zoujiaqing** [comment]
I will try remove this arg item, tomorrow..

**Comment by bernd-edlinger** [comment]
No, I meant that as a joke.
If you would use gcc I would suggest you configure
with -g3 -save-temps, and look what defines __GLIBC_PREREQ in getenv.i

**Comment by bernd-edlinger** [comment]
But I don't know enough clang to tell if it supports the same debug options as gcc....

**Comment by zoujiaqing** [comment]
Thank you @bernd-edlinger :)
I will go to try at tomorrow. see you !

**Comment by zoujiaqing** [comment]
I can't resolve it ..
I looks FreeBSD's patch files, not found about GLIBC_PREREQ.

https://svnweb.freebsd.org/ports/head/security/openssl/files/

**Comment by bernd-edlinger** [comment]
Clearly it is wrong when __GLIBC_PREREQ is defined when this is not a glibc.
You need to look at the preprocessor output (add -dD -save-temps to your configure flags)

**Comment by zoujiaqing** [comment]
not generate *.i files:
```bash
ls -lh  openssl-1.1.1d/crypto/getenv.*
-rw-r--r--  1 zoujiaqing  wheel   728B Sep 10  2019 openssl-1.1.1d/crypto/getenv.c
-rw-r--r--  1 zoujiaqing  wheel   504B Mar 11 19:44 openssl-1.1.1d/crypto/getenv.d
-rw-r--r--  1 zoujiaqing  wheel   2.8K Mar 11 19:44 openssl-1.1.1d/crypto/getenv.o
```

**Comment by zoujiaqing** [comment]
https://github.com/openssl/openssl/blob/99a16e0459e5089c2cfb92ee775f1221a51b8d05/ssl/ssl_ciph.c#L1419-L1420

**Comment by bernd-edlinger** [comment]
maybe you try to use gcc then, at least it is able to output preprocessor files?

**Comment by kaduk** [comment]
I'm confused about the reference to patches in FreeBSD ports, when the stated build path includes `rpmbuild/BUILD/openssl-1.1.1d`, which is not a path used internally in the FreeBSD ports collection.
I'm also forced to surmise that there are some additional patches in play based on the ``--system-ciphers-file` argument given to `config`, which is not recognized by openssl internally and, when passed through to the FreeBSD cc as is expected for options to openssl config, causes a fatal error early in the build.  Please tell us more about where this source tree came from

**Comment by t8m** [comment]
Yep, this looks like Fedora/RHEL patched sources being used. This is certainly something I would not try compiling on FreeBSD. Closing the issue.
