### ISSUE TITLE
Can we use engine.so with libcryto.a?

### ISSUE THREAD

**Issue by Grim-lock** [openssl/openssl#11294]
I want to compile nginx with libcryto.a，and use engine.so.
can this work?

where can i find some document about this?

Thanks for any help

**Comment by levitte** [comment]
That's going to be really dodgy really fast.  Unfortunately, engines are no longer OpenSSL version agnostic, they kinda lost that quality with OpenSSL 1.1.0.

That being said, it's possible to build engine.so without linking it with libcrypto, leaving all libcrypto symbol references unresolved.  If you then do not strip symbol information from nginx itself, the unresolved symbol references in engine.so *should* get resolved automatically when it gets loaded, thanks to the symbols being present in nginx.

Note: I have done absolutely nothing to actually test this, so I can only say that it should work *in theory*.

**Comment by beldmit** [comment]
My experience (though rather old) says that it was problematic to build engines (at least via config file) in such a case.

**Comment by Grim-lock** [comment]
> That's going to be really dodgy really fast. Unfortunately, engines are no longer OpenSSL version agnostic, they kinda lost that quality with OpenSSL 1.1.0.
> 
> That being said, it's possible to build engine.so without linking it with libcrypto, leaving all libcrypto symbol references unresolved. If you then do not strip symbol information from nginx itself, the unresolved symbol references in engine.so _should_ get resolved automatically when it gets loaded, thanks to the symbols being present in nginx.
> 
> Note: I have done absolutely nothing to actually test this, so I can only say that it should work _in theory_.

Sorry my unclear description. I do not want to rebuild engine.so.
My case is build nginx with libcryto.a staticly，in this situation，can nginx use engine.so?

In some document, I only find nginx use libcryto.so dynamicly，and libcryto.so  can use engine.so. conf file like this 
'''
[engine_section]
qat = qat_section
[qat_section]
engine_id = qat
dynamic_path = /home/lbc/handshaker_qat/lib/engines-1.1/qat.so
'''

**Comment by beldmit** [comment]
I was not successful in the case you describe.

**Comment by levitte** [comment]
I can theorise about a number of possible cases:

1.  `qat.so` is dynamically linked with libcrypto.so.  You can verify which version with `ldd engine.so`, but this is generally RED ALERT territory, because since 1.1.0, the ENGINE API can be (isn't necessarily, but *can* be) sensitive to minor release differences.
2.  `qat.so` is statically linked with a version of libcrypto.a.  Depending on if symbols are stripped or not, that's very hard to verify, but if they aren't, `nm qat.so | grep ' T '` should show recognisable libcrypto symbols.  This is **RED ALERT** territory, don't even think about it.
3.  `qat.so` isn't linked with libcrypto in any form, i.e. the libcrypto symbols have been left unresolved, and symbol resolution is expected to happen at run time.  This can be verified with `nm --undefined-only qat.so`, which should show recognisable libcrypto symbols.  This could actually work.

Among "recognisable libcrypto symbols", symbols starting with `ENGINE_` or `EVP_` would be typical.

If this `qat.so` is the one I was involved in years ago, chances are that it's linked with libcrypto in some form, i.e. you're entering RED ALERT territory.  The prospect of getting what you're asking for to work look slim, to say the least.

**Comment by InfoHunter** [comment]
> I was not successful in the case you describe.

Me neither.

**Comment by InfoHunter** [comment]
I have also encountered this issue years ago with that QAT engine and finally we chose not to struggle with this. Eventually we made NGINX work with dynamic OpenSSL libraries in our environments and that brought agile management options as well as a bonus.

**Comment by Grim-lock** [comment]
> I was not successful in the case you describe.

Is openssl not support this case? 

In my opinion, static lib h

> 2\. **RED ALERT** territory

Thanks very much，My engine.so is like case 3 which you said, so I think that is work.
'''
[root@cdnnbct05-cache16 lib]# nm  engine.so | grep ENGINE_
                 U ENGINE_by_id
                 U ENGINE_free
                 U ENGINE_get_static_state
                 U ENGINE_set_ciphers
                 U ENGINE_set_cmd_defns
                 U ENGINE_set_ctrl_function
                 U ENGINE_set_destroy_function
                 U ENGINE_set_DH
                 U ENGINE_set_DSA
                 U ENGINE_set_EC
                 U ENGINE_set_finish_function
                 U ENGINE_set_id
                 U ENGINE_set_init_function
                 U ENGINE_set_name
                 U ENGINE_set_pkey_meths
                 U ENGINE_set_RSA
[root@cdnnbct05-cache16 lib]# nm  engine.so | grep EVP_
                 U EVP_aes_128_cbc
                 U EVP_aes_128_cbc_hmac_sha1
                 U EVP_aes_128_cbc_hmac_sha256
                 U EVP_aes_256_cbc
                 U EVP_aes_256_cbc_hmac_sha1
                 U EVP_aes_256_cbc_hmac_sha256
                 U EVP_CIPHER_CTX_encrypting
                 U EVP_CIPHER_CTX_get_cipher_data
                 U EVP_CIPHER_CTX_iv
                 U EVP_CIPHER_CTX_iv_length
                 U EVP_CIPHER_CTX_iv_noconst
                 U EVP_CIPHER_CTX_key_length
                 U EVP_CIPHER_CTX_new
                 U EVP_CIPHER_CTX_nid
                 U EVP_CIPHER_CTX_reset
                 U EVP_CIPHER_CTX_set_cipher_data
                 U EVP_CIPHER_CTX_set_flags
                 U EVP_CIPHER_impl_ctx_size
                 U EVP_CIPHER_meth_free
                 U EVP_CIPHER_meth_get_ctrl
                 U EVP_CIPHER_meth_get_do_cipher
                 U EVP_CIPHER_meth_get_init
                 U EVP_CIPHER_meth_new
                 U EVP_CIPHER_meth_set_cleanup
                 U EVP_CIPHER_meth_set_ctrl
                 U EVP_CIPHER_meth_set_do_cipher
                 U EVP_CIPHER_meth_set_flags
                 U EVP_CIPHER_meth_set_get_asn1_params
                 U EVP_CIPHER_meth_set_impl_ctx_size
                 U EVP_CIPHER_meth_set_init
                 U EVP_CIPHER_meth_set_iv_length
                 U EVP_CIPHER_meth_set_set_asn1_params
                 U EVP_DecryptFinal_ex
                 U EVP_DecryptInit_ex
                 U EVP_DecryptUpdate
                 U EVP_MD_type
                 U EVP_PKEY_CTX_get_data
                 U EVP_PKEY_CTX_set_data
                 U EVP_PKEY_meth_new
                 U EVP_PKEY_meth_set_cleanup
                 U EVP_PKEY_meth_set_ctrl
                 U EVP_PKEY_meth_set_derive
                 U EVP_PKEY_meth_set_init

'''

**Comment by Grim-lock** [comment]
> I can theorise about a number of possible cases:
> 
> 1. `qat.so` is dynamically linked with libcrypto.so.  You can verify which version with `ldd engine.so`, but this is generally RED ALERT territory, because since 1.1.0, the ENGINE API can be (isn't necessarily, but _can_ be) sensitive to minor release differences.
> 2. `qat.so` is statically linked with a version of libcrypto.a.  Depending on if symbols are stripped or not, that's very hard to verify, but if they aren't, `nm qat.so | grep ' T '` should show recognisable libcrypto symbols.  This is **RED ALERT** territory, don't even think about it.
> 3. `qat.so` isn't linked with libcrypto in any form, i.e. the libcrypto symbols have been left unresolved, and symbol resolution is expected to happen at run time.  This can be verified with `nm --undefined-only qat.so`, which should show recognisable libcrypto symbols.  This could actually work.
> 
> Among "recognisable libcrypto symbols", symbols starting with `ENGINE_` or `EVP_` would be typical.
> 
> If this `qat.so` is the one I was involved in years ago, chances are that it's linked with libcrypto in some form, i.e. you're entering RED ALERT territory. The prospect of getting what you're asking for to work look slim, to say the least.

**Comment by Grim-lock** [comment]
> I can theorise about a number of possible cases:
> 
> 1. `qat.so` is dynamically linked with libcrypto.so.  You can verify which version with `ldd engine.so`, but this is generally RED ALERT territory, because since 1.1.0, the ENGINE API can be (isn't necessarily, but _can_ be) sensitive to minor release differences.
> 2. `qat.so` is statically linked with a version of libcrypto.a.  Depending on if symbols are stripped or not, that's very hard to verify, but if they aren't, `nm qat.so | grep ' T '` should show recognisable libcrypto symbols.  This is **RED ALERT** territory, don't even think about it.
> 3. `qat.so` isn't linked with libcrypto in any form, i.e. the libcrypto symbols have been left unresolved, and symbol resolution is expected to happen at run time.  This can be verified with `nm --undefined-only qat.so`, which should show recognisable libcrypto symbols.  This could actually work.
> 
> Among "recognisable libcrypto symbols", symbols starting with `ENGINE_` or `EVP_` would be typical.
> 
> If this `qat.so` is the one I was involved in years ago, chances are that it's linked with libcrypto in some form, i.e. you're entering RED ALERT territory. The prospect of getting what you're asking for to work look slim, to say the least.

Thanks very much，My engine.so is like case 3 which you said, so I think that is work.
'''
[root@cdnnbct05-cache16 lib]# nm  engine.so | grep ENGINE_
                 U ENGINE_by_id
                 U ENGINE_free
                 U ENGINE_get_static_state
                 U ENGINE_set_ciphers
                 U ENGINE_set_cmd_defns
                 U ENGINE_set_ctrl_function
                 U ENGINE_set_destroy_function
                 U ENGINE_set_DH
                 U ENGINE_set_DSA
                 U ENGINE_set_EC
                 U ENGINE_set_finish_function
                 U ENGINE_set_id
                 U ENGINE_set_init_function
                 U ENGINE_set_name
                 U ENGINE_set_pkey_meths
                 U ENGINE_set_RSA
[root@cdnnbct05-cache16 lib]# nm  engine.so | grep EVP_
                 U EVP_aes_128_cbc
                 U EVP_aes_128_cbc_hmac_sha1
                 U EVP_aes_128_cbc_hmac_sha256
                 U EVP_aes_256_cbc
                 U EVP_aes_256_cbc_hmac_sha1
                 U EVP_aes_256_cbc_hmac_sha256
                 U EVP_CIPHER_CTX_encrypting
                 U EVP_CIPHER_CTX_get_cipher_data
                 U EVP_CIPHER_CTX_iv
                 U EVP_CIPHER_CTX_iv_length
                 U EVP_CIPHER_CTX_iv_noconst
                 U EVP_CIPHER_CTX_key_length
                 U EVP_CIPHER_CTX_new
                 U EVP_CIPHER_CTX_nid
                 U EVP_CIPHER_CTX_reset
                 U EVP_CIPHER_CTX_set_cipher_data
                 U EVP_CIPHER_CTX_set_flags
                 U EVP_CIPHER_impl_ctx_size
                 U EVP_CIPHER_meth_free
                 U EVP_CIPHER_meth_get_ctrl
                 U EVP_CIPHER_meth_get_do_cipher
                 U EVP_CIPHER_meth_get_init
                 U EVP_CIPHER_meth_new
                 U EVP_CIPHER_meth_set_cleanup
                 U EVP_CIPHER_meth_set_ctrl
                 U EVP_CIPHER_meth_set_do_cipher
                 U EVP_CIPHER_meth_set_flags
                 U EVP_CIPHER_meth_set_get_asn1_params
                 U EVP_CIPHER_meth_set_impl_ctx_size
                 U EVP_CIPHER_meth_set_init
                 U EVP_CIPHER_meth_set_iv_length
                 U EVP_CIPHER_meth_set_set_asn1_params
                 U EVP_DecryptFinal_ex
                 U EVP_DecryptInit_ex
                 U EVP_DecryptUpdate
                 U EVP_MD_type
                 U EVP_PKEY_CTX_get_data
                 U EVP_PKEY_CTX_set_data
                 U EVP_PKEY_meth_new
                 U EVP_PKEY_meth_set_cleanup
                 U EVP_PKEY_meth_set_ctrl
                 U EVP_PKEY_meth_set_derive
                 U EVP_PKEY_meth_set_init

'''

**Comment by levitte** [comment]
Just to exclude that possibility, did you check with `ldd`?  'cause if it's linked with libcrypto dynamically, *`nm` will also report undefined symbols!*

**Comment by Grim-lock** [comment]
> Just to exclude that possibility, did you check with `ldd`? 'cause if it's dynamically linked with libcrypto, _`nm` will also report undefined symbols!_

Yes I checked ldd,  no linked libcrypto.so.
and  I checked all undefined symbols  in engine.so，they are all be find in libcrypto.a through "nm libcrapto.a | grep ' T '"

'''
[root@cdnnbct05-cache16 lib]# ldd engine.so
	linux-vdso.so.1 =>  (0x00007ffdd0ce8000)
	libqat_s.so => /Application/qat/qat1.7.l.4.8.0-00005/build/libqat_s.so (0x00007fe6a962a000)
	libusdm_drv_s.so => /Application/qat/qat1.7.l.4.8.0-00005/build/libusdm_drv_s.so (0x00007fe6a9412000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe6a9045000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe6a8e29000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007fe6a8c13000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe6a9b3d000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe6a8a0b000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007fe6a8806000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe6a8504000)
	libdw.so.1 => /lib64/libdw.so.1 (0x00007fe6a82b3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe6a80af000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe6a7e99000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007fe6a7c94000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007fe6a7a7c000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe6a7866000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fe6a7640000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fe6a7430000)
'''
