### ISSUE TITLE
CMP Fuzzer

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#11301]
I think we should add new fuzz programs for the CMP related changes.

@DDvO: Is that something you can do?

**Comment by mattcaswell** [comment]
This is an excellent idea.

**Comment by DDvO** [comment]
I can give it a try when I have more time...
Where can I find documentation how to do that?

**Comment by kroeckx** [comment]
On Wed, Mar 18, 2020 at 05:35:33AM -0700, David von Oheimb wrote:
> I can give it a try when I have more time...
> Where can I find documentation how to do that?

We have existing fuzzers in the fuzz directory. You create a new
file per fuzzer, and need to implement a FuzzerTestOneInput()
function. You then let the fuzzer try to parse that input.

You probably also need the FuzzerInitialize() and FuzzerCleanup()
functions, but they can be empty.

If you have any questions, or need some help, let me know.

**Comment by richsalz** [comment]
One simple thing is add new ASN.1 types to fuzz/asn1.c

**Comment by DDvO** [comment]
Thanks @kroeckx and @richsalz for your hints.
I've started a PR that solves this issue: #11137

**Comment by DDvO** [comment]
Closing this issue since it has been solved meanwhile by #11386.
