### ISSUE TITLE
Example for Replace ECDSA_do_verify by EVP_DigestVerify*

### ISSUE THREAD

**Issue by misery** [openssl/openssl#11309]
OpenSSL 3.0.0 deprecates ECDSA_do_verify and suggest to use EVP_DigestVerify.

It would be helpful if the documentation shows an example.
It looks like the new API requires the content in place to generate a hash value itself. Is there a way to pass an already generated hash value as we don't have the content in that part.

**Comment by mattcaswell** [comment]
There's an EVP_DigestSign and EVP_DigestVerify example here:

https://wiki.openssl.org/index.php/EVP_Signing_and_Verifying

If you want to sign already hashed content then you are probably better using `EVP_PKEY_sign`. The man page (including an example) is here:

https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_sign.html

**Comment by misery** [comment]
Thanks, ```EVP_PKEY_verify``` did the trick.
