### ISSUE TITLE
EVP_MAC_size()

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11320]
We seem to have an EVP_MAC_size() function:

````
size_t EVP_MAC_size(EVP_MAC_CTX *ctx);
````

However rather than taking an `EVP_MAC` parameter it takes an `EVP_MAC_CTX`.

Shouldn't the function be called `EVP_MAC_CTX_size()`? Or is this deliberate?

**Comment by levitte** [comment]
I gotta wonder why this function got singled out...  but I'll play.

I can't really remember the exact reason, but my immediate intuition now says that "the size of the MAC" is more naturally spelled EVP_MAC_size() than EVP_MAC_CTX_size().

What I *don't* want to see is both `EVP_MAC_size()` and `EVP_MAC_CTX_size()`...  that's just confusing.

**Comment by mattcaswell** [comment]
> I gotta wonder why this function got singled out... but I'll play.
>
> I can't really remember the exact reason, but my immediate intuition now says that "the size of the MAC" is more naturally spelled EVP_MAC_size() than EVP_MAC_CTX_size().

Virtually all of our functions start with the name of the object it operates on. Notable exceptions are the init/update/final functions. Aside from those, AFAICT, all the other EVP_MAC_* functions do conform to that convention - making this one stick out as being the odd one out. I tripped over this when trying to find the size of the mac given an EVP_MAC_CTX. Grepping the source failed to find EVP_MAC_CTX_size() as I expected...

**Comment by levitte** [comment]
Okie, than change it.  You should do the same for EVP_KDF_size(), then

**Comment by paulidale** [comment]
Needs to be renamed for 3.0: `EVP_MAC_CTX_get_mac_size()`.  Likewise for the KDF.

**Comment by slontis** [comment]
EVP_KDF_reset() also renamed..

**Comment by paulidale** [comment]
Could we instead remove `EVP_MAC_size()`?  The size is returned as part of the final `EVP_MAC_final()`.
The same would be true of `EVP_MD_size()` and `EVP_DigestFinal_ex()`.

**Comment by t8m** [comment]
> Could we instead remove `EVP_MAC_size()`? The size is returned as part of the final `EVP_MAC_final()`.
> The same would be true of `EVP_MD_size()` and `EVP_DigestFinal_ex()`.

Do you mean completely remove it? I do not think it would be nice idea. In an application I might want to know a size of particular MAC (or MD) before I actually try to create one.
