### ISSUE TITLE
Use Carmichael totient in RSA key generation.

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#11326]
Refer to discussion in #3353.

~[FIPS 186-4](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf#page=62) mandates the use of the Carmichael totient function during RSA key generation.  The current code uses the Euler totient function instead.~

~The situation is compounded by multi-prime support being present.  It might be possible to meet the FIPS requirements by using the Carmichael totient function when there are only two primes.~

[edit: this isn't FIPS relevant because it is a different code path: `rsa_sp800_56b_generate_key()`]

**Comment by nhorman** [comment]
@paulidale  is this still relevant?

**Comment by paulidale** [comment]
It's an optimisation but unlikely to be relevant anymore.  Closing.
