### ISSUE TITLE
an error when using TLS1.2

### ISSUE THREAD

**Issue by l00519243** [openssl/openssl#11333]
Hello:
I have a question about TLS1.2 when using OpenSSL1.1.1c.
Server：
use SSL_CTX_set1_groups  - NID_X9_62_prime256v1
use SSL_CTX_set1_sigalgs set a signature:  EVP_PKEY_EC,NID_sha384
and load a device certificate (public key is ECC P384)
Client:
SSL_CTX_set_cipher_list  "ECDHE-ECDSA-AES256-GCM-SHA384"

here i find when a client connect with server,there is：
in tls12_check_peer_sigalg->tls1_check_group_id 
will comes an error,server will check group ,but no p384 there,only p256.

So my question is:
In TLS 1.2,my way is right? do SSL_CTX_set1_groups and SSL_CTX_set1_sigalgs have relation/dependency?
(sorry,i can not send email as it suggests...)

**Comment by lijk8090** [comment]
Use **SSL_CTX_set1_curves_list** set "**secp384r1**" elliptic curve.

Just like:
![image](https://user-images.githubusercontent.com/10040463/76735960-f5884c00-67a0-11ea-88c1-1cafdc6a8b23.png)

Good luck!

**Comment by l00519243** [comment]
你好：
解决方法明确。
还有疑问是：
证书的公钥类型是P384时，SSL_CTX_set1_curves_list设置的是支持的曲线类型，为啥不在设置P256提示错误？因为在本端校验对端的签名时，需要使用P384的校验呀

**Comment by l00519243** [comment]
你好：
这种场景在TLS1.3的时候没有问题。
对于TLS1.2，有问题
怎么理解这种差异性？

**Comment by lijk8090** [comment]
because tls 1.3 doesn't call the "tls12_check_peer_sigalg -> tls1_check_group_id" function.

![image](https://user-images.githubusercontent.com/10040463/76952419-08895080-6948-11ea-8a9b-142343a88623.png)

**Comment by l00519243** [comment]
why TLS1.3 do not check group and current pkey?

**Comment by lijk8090** [comment]
because tls.1.3 has different handshake workflow.

**Comment by l00519243** [comment]
ok,fine ,thank you

**Comment by l00519243** [comment]
another question:
DTLS over SCTP ,当出现解密失败时，openssl当前处理是丢弃报文，当前处理是否合理；是否可以发ALTER给对端；我自己认为可以回ALTER，SCTP是可靠的传输；
file:///C:/Users/l00519243/AppData/Roaming/eSpace_Desktop/UserData/l00519243/imagefiles/A2FB736B-8D2F-4E01-9CB5-0C09ED831FE6.png

下面是解决办法，帮确认下合理吗！
file:///C:/Users/l00519243/AppData/Roaming/eSpace_Desktop/UserData/l00519243/imagefiles/49363090-E3E3-46AC-B5A1-E36C5BC5FCB5.png

**Comment by kaduk** [comment]
Note that `SSL_CTX_set1_curves_list()` will override the setting from `SSL_CTX_set1_groups()`:

```
# define SSL_get1_curves               SSL_get1_groups
# define SSL_CTX_set1_curves           SSL_CTX_set1_groups
# define SSL_CTX_set1_curves_list      SSL_CTX_set1_groups_list
# define SSL_set1_curves               SSL_set1_groups
# define SSL_set1_curves_list          SSL_set1_groups_list
```

For TLS versions prior to 1.3, "the application" (you) is responsible for ensuring that the group list and cipherlist are compatible.
