### ISSUE TITLE
Support making with JOM instead of nmake on Windows

### ISSUE THREAD

**Issue by ganeshkamath89** [openssl/openssl#11348]
I was using nmake to build openssl, but switching to JOM helped me reduce the build time of my utility by 14 minutes.

I ran the following command to compile openssl using JOM (reference ticket: #9931 ):
`%JomPath% -k -j %NUMBER_OF_PROCESSORS% -f makefile build_libs`

Now I am getting Linker warning for 6 objects:

> 1>rand_egd.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
> 
> 1>ecp_nistputil.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
> 
> 1>ecp_nistp521.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
> 
> 1>ecp_nistp256.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
> 
> 1>ecp_nistp224.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
> 
> 1>ebcdic.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library

I can ignore this a a linker warning, but if there is some fix to this problem, I am interested in making my solution Linker warning free.

**Comment by richsalz** [comment]
#11263 and #11250 will help fix many of those warnings (but not ebcdic.obj)  But you can ignore those warnings.
