### ISSUE TITLE
Do all of our new types need to be public?

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11350]
The fetching of types like EVP_ASYM_CIPHER, EVP_SIGNATURE etc, is now done internally following a call to EVP_PKEY_CTX_new_from_name or EVP_PKEY_CTX_new_from_pkey. So - do we still need those types to be part of our public API? When would an end application need to do something with an EVP_SIGNATURE object for example?

**Comment by levitte** [comment]
This is a good question.  A related question is, do we have any reason to believe that a provider (linked with libcrypto, of course) would have any use for them?  In doing so, however, we also need to publish functions that can be used to call the method functions; for example, the interface functions in `crypto/evp/keymgmt_meth.c` would have to be made public (I added all those function for that kind of purpose among others).

**Comment by mattcaswell** [comment]
> This is a good question. A related question is, do we have any reason to believe that a provider (linked with libcrypto, of course) would have any use for them?

I'm struggling to see what a provider would do with them.

The main thing I hesitate on is the gettable/settable types functions and how they would be exposed or used by end applications.

**Comment by paulidale** [comment]
These should be public.
