### ISSUE TITLE
openssl 1.1.1e make install error on ./apps/CA.pl

### ISSUE THREAD

**Issue by brainstorm** [openssl/openssl#11362]
```shell
$ export OPENSSL_VERSION="1_1_1e" && wget https://github.com/openssl/openssl/archive/OpenSSL_$OPENSSL_VERSION.tar.gz && tar xvfz OpenSSL_$OPENSSL_VERSION.tar.gz && tar xvfz OpenSSL_$OPENSSL_VERSION.tar.gz && cd openssl-OpenSSL_$OPENSSL_VERSION && ./Configure --prefix=/usr/local/openssl --openssldir=/usr/local/openssl/etc linux-x86_64 no-shared no-dso no-gost no-engine no-ssl2 no-srp no-srtp no-tests zlib no-weak-ssl-ciphers && make install

install ./apps/CA.pl -> /usr/local/openssl/etc/misc/CA.pl
cp: cannot stat './apps/CA.pl': No such file or directory
Makefile:262: recipe for target 'install_ssldirs' failed
make: *** [install_ssldirs] Error 1
make: *** Waiting for unfinished jobs....
```

[openssl1.1.1e.confdump.txt](https://github.com/openssl/openssl/files/4352000/openssl1.1.1e.confdump.txt)

**Comment by brainstorm** [comment]
Funny bug, the issue is that "make install" cannot be issued right after `./Configure`, but separate `make` and `make install` should be run in order :)

It's still a bug though since `make` should work through the task dependencies anyway without failing on items not yet available (`CA.pl` in this case).

**Comment by kaduk** [comment]
To be clear, the documentation is pretty clear that you run `make` before `make install`, and the current implementation makes literally no attempt to provide at the makefile level dependencies from the install targets on the presence of the files to be installed.
While I personally would support having this "just work", I have a hard time calling the current behavior a "bug", particularly when one recalls that openssl uses a custom build system (as opposed to the autoconf/etc. stack that is near-ubiquitous for open-source Unix software).

**Comment by brainstorm** [comment]
Alright, call it "makefile UX" and not bug then. I reported it to save other people's time by adhering to [PoLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), that's it ;)

**Comment by rdp** [comment]
Just ran into this with 3.2, thanks.
