### ISSUE TITLE
EVP_PKEY_copy_parameters() broken

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11366]
EVP_PKEY_copy_parameters() appears to broken if the "to" key is a newly allocated EVP_PKEY, and the "from" key is a provider only key. It appears to bail out because it thinks the key types are not consistent with each other.

**Comment by levitte** [comment]
Did you notice the key type?  I just discovered that the EVP_PKEY_ASN1_METHOD functions export_to are broken for EC_KEY, DSA and DH.  They all assume that there *must* be a public key, which is obviously not true for key structures with only parameters...  so they fail.

**Comment by slontis** [comment]
Richard:

The EVP_PKEY_missing_parameters(to) check is not working correctly..
There wont be any parameters for an empty key.

**Comment by levitte** [comment]
Ah!  A newly *allocated*, got it!

**Comment by levitte** [comment]
But wait hold on!  Here's the 1.1.1 implementation equally broken?

https://github.com/openssl/openssl/blob/c3074077136c698af05ebe57347c186ae15c910a/crypto/evp/p_lib.c#L103-L108

**Comment by slontis** [comment]
Ok that was a false lead.. since it does    
```
if (!EVP_PKEY_missing_parameters(to)) {
        if (EVP_PKEY_cmp_parameters(to, from) == 1)
            return 1;
        EVPerr(EVP_F_EVP_PKEY_COPY_PARAMETERS, EVP_R_DIFFERENT_PARAMETERS);
        return 0;
    }
````
 The next bit however WILL fail since to is a new key.
```
    if (from->keymgmt != NULL) {
        EVP_KEYMGMT *tmp_keymgmt = from->keymgmt;

        /*
         * The returned pointer is known to be cached, so we don't have to
         * save it.  However, if it's NULL, something went wrong and we can't
         * copy.
         */
        if (evp_pkey_upgrade_to_provider(to, NULL,
```

**Comment by levitte** [comment]
Ah!  The broken thing isn't in `EVP_PKEY_missing_parameters()`, but in `EVP_PKEY_copy_parameters()`.  In 1.1.1, it starts like this:

https://github.com/openssl/openssl/blob/c3074077136c698af05ebe57347c186ae15c910a/crypto/evp/p_lib.c#L77-L79

We don't do that sort of thing in master...  I think.

**Comment by levitte** [comment]
Thanks for the test nugget, @slontis.  I'll add it

**Comment by levitte** [comment]
As an extension, I find that we haven't really established what an empty key looks like when the internal key is supposed to be provider side, i.e. we don't handle the `pk->keymgmt != NULL && pk->keydata == NULL` case too well.  By consequence, #11368 explodes a little bit...  nothing that I can't handle, but be prepared for a somewhat more elaborate PR.

**Comment by levitte** [comment]
Another question came back haunting...  should `EVP_PKEY_copy_parameters` only copy domain parameters or *all* parameters?  ec_kmgmt.c doesn't really like exporting non-domain parameters without the keypair also being selected for export, so a parameter copy with the selection OSSL_KEYMGMT_SELECT_ALL_PARAMETERS fails, while OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS works.  The description of `EVP_PKEY_copy_parameters()` isn't very clear on this subject, but on the other hand, it was created when life was simpler and the only parameters in existence were in fact the DSA and DH domain parameters.

**Comment by t8m** [comment]
What does the function really does in 1.1.1 - if it copies only domain parameters then it should do so in 3.0 as well and the documentation should be adjusted to reflect the reality.

**Comment by levitte** [comment]
The problem is that with 3.0, EVP_PKEY can have either an internal legacy key or an internal provider side key.  We run into trouble when we need to operate with two EVP_PKEYs where the internal keys are of different origins.

I just got hit by a case that doesn't work with the upgrade of *to* from legacy to provider side internal key:

https://github.com/openssl/openssl/blob/22e27978b29b2cdc1db79659ed653d6cf31834ab/crypto/dh/dh_pmeth.c#L419-L423

What happens in there is the when `ctx->pkey` holds an internal provider side key, `pkey` gets "upgraded" to a provider side key, which leads to `pkey->pkey.dh` being freed.  I *think* the solution needs to be a modification of `EVP_PKEY_gen()`...

**Comment by levitte** [comment]
#11375 reworks quite a lot how EVP_PKEYs work.  It's not a direct fixup commit for this issue, but just so happens to fix EVP_PKEY_copy_parameters() as part of it.
