### ISSUE TITLE
Create binaries for use in CI?

### ISSUE THREAD

**Issue by MSP-Greg** [openssl/openssl#11363]
The recently release of 1.1.1e broke Ruby's OpenSSL, due to the change in eof handling.

Might binaries of both the most recent release and master be saved as release assets so external repos could make use of them in CI?

In Ruby world, we've got assets where the current CI replaces the previous CI only if all testing passes, so the master release asset is always a passing build.

Actions could support Ubuntu, macOS, and both msvc & MSYS2/MinGW builds on Windows.

It would be more that a few lines of code, but it would certainly broaden the scope of applications testing against master.

Or, maybe just 'engage' the master releases when master hits an alpha or beta release...

**Comment by mattcaswell** [comment]
Creating binaries is not something we've ever attempted before, and we've always been a "source only" distribution. I'm not really sure I understand why us creating binaries helps? Or how testing against master helps prevent issues in the stable 1.1.1 release?

**Comment by nhorman** [comment]
It seems that you can just build the latest openssl in ruby's CI system
