### ISSUE TITLE
EVP access to CTS based ciphers

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#11364]
Currently CTS is done using a special mode that sits over ECB & CBC.  It does not use EVP level calls and bypasses the provider interface.

To confound things there are multiple definitions of how CTS is done.

**Comment by nhorman** [comment]
@paulidale still an issue?

**Comment by paulidale** [comment]
Not an issue anymore I suspect.  We've some CTS ciphers defined and that's likely good enough.  Closing.
