### ISSUE TITLE
Disable xcode sanitize-address build

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#11370]
Despite changes to add more time-outs, these builds still regularly fail.

We should just disable that build.  The non-stop failures everyone has to waste time tracking down the little red "x" to see if something is actually wrong.

Sorry @mspncp I didn't fix it.  Or you jinxed it. :)

**Comment by mspncp** [comment]
> Sorry @mspncp I didn't fix it. Or you jinxed it. :)

![jeanny](https://user-images.githubusercontent.com/11467854/77148398-ce2acb00-6a8f-11ea-862c-5431b90ea150.gif)

**Comment by t8m** [comment]
Perhaps we should make it just one of the extended tests?
Also why don't we also try using clang on linux?

**Comment by t8m** [comment]
This was Travis CI problem and so it is no more.
