### ISSUE TITLE
Openssl 1.1.1e / tor 0.4.2.7: Unhandled OpenSSL errors (possible #7712 regression?)

### ISSUE THREAD

**Issue by nikolasr** [openssl/openssl#11376]
When using OpenSSL 1.1.1e with Tor 0.4.2.7 (or version 0.4.2.6), Tor generates the following error:

  ```
Mar 21 16:10:39.000 [warn] Unhandled OpenSSL errors found at buffers_tls.c:159:
Mar 21 16:10:39.000 [warn] TLS error: error getting time (in asn1 encoding routines:ASN1_TIME_adj:---)
Mar 21 16:10:39.000 [warn] TLS error: error getting time (in asn1 encoding routines:ASN1_TIME_adj:---)
Mar 21 16:10:40.000 [notice] Bootstrapped 100% (done): Done
Mar 21 16:11:05.000 [warn] Unhandled OpenSSL errors found at buffers_tls.c:159:
Mar 21 16:11:05.000 [warn] TLS error: error getting time (in asn1 encoding routines:ASN1_TIME_adj:---)
Mar 21 16:11:05.000 [warn] TLS error: error getting time (in asn1 encoding routines:ASN1_TIME_adj:---)
```

The problem seems to have been addressed before in issue #7712 
See also [https://bugs.archlinux.org/task/61623](url)

OpenSSL version info (standard MSYS2 pacman package):
 ```
OpenSSL 1.1.1e  17 Mar 2020
built on: Wed Mar 18 07:57:00 2020 UTC
platform: mingw
options:  bn(64,32) rc4(8x,mmx) des(long) idea(int) blowfish(ptr)
compiler: gcc -m32 -Wall -O3 -fomit-frame-pointer -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAESNI_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DZLIB -DZLIB_SHARED -DOPENSSL_USE_APPLINK -DNDEBUG -D__MINGW_USE_VC2005_COMPAT -DOPENSSLBIN="\"/mingw32/bin\""
OPENSSLDIR: "D:/msys64/mingw32/ssl"
ENGINESDIR: "D:/msys64/mingw32/lib/engines-1_1"
Seeding source: os-specific
```

OS: Windows 10 pro. 64-bit, build 1909
Compiler details: OpenSSL: (standard MSYS2 distribution package); Tor: MSYS2 32-bit / MinGW32 gcc
Application details: Tor 0.4.2.7, 32-bit, MSYS2 32-bit / MinGW32 build
Steps to reproduce: start Tor
Reproduceable: always

**Comment by kroeckx** [comment]
We're seeing various regressions because of commit db943f43a60d,
"Detect EOF while reading in libssl".

See:
https://github.com/openssl/openssl/pull/10882
https://github.com/openssl/openssl/issues/10880

Are you sure you're not also getting that?

The problem you're seeing now seem to be unrelated to #7712

**Comment by nikolasr** [comment]
I also tried with a fresh git pull and compile from openssl-1-1-stable 2 hours ago... same outcome

However I switched back to standard MSYS2 dist package, since it didn't help

#10880 is about openssl 1.1.1d

1.1.1d did not show any errors on tor. So whatever it is, it's related to 1.1.1e

**Comment by kroeckx** [comment]
There was a bug repoted in #10880, the fix for that is in #10882,
and is part of 1.1.1e. OpenSSL did not return an error when it
should, it does now. Now that we properly return that error, various
software making use of OpenSSL start to get errors.

I don't know if tor is affected by this or not. If it is, it's
probably a bug in tor, not in OpenSSL.

**Comment by nikolasr** [comment]
Nope. Let's narrow that down. I happend to have a non-git zip-checkout of openssl-1-1-1-stable from 2020-02-22 (1.1.1e-dev) ... just tried that, worked fine :-)
Since the fix for #10882 was committed 2020-02-20 I doubt that this is the cause....

**Comment by kroeckx** [comment]
So do a git bisect then to find which commit breaks it. There are
very few commits after that commit that actually change code, and
nothing looks related to your error message.

**Comment by nikolasr** [comment]
Will do :-)
Doing a git bisect is new to me, but, hey, only until now ;-P . Might take this weekend to complete. Please be patient....

**Comment by nikolasr** [comment]
Sorry, error was on my side.
Did a bisect. Turned out my git checkout of openssl was corrupted somehow. Did a new clone, and now everything works fine *blush*.
Sorry for the inconvenience :-/

**Comment by mspncp** [comment]
> Did a new clone, and now everything works fine _blush_.
> Sorry for the inconvenience :-/

No need to blush. It was a well written error report and you did spend a significant amount of time to investigate the problem yourself before reporting it.
