### ISSUE TITLE
Windows: Ignore auto generated files

### ISSUE THREAD

**Issue by huangqinjin** [openssl/openssl#1138]
The commit [34f5d44](https://github.com/openssl/openssl/commit/34f5d44f6a4eb09f4d41041091a20c2bf4bf9bf7) modified the names of generated files tsget and c_rehash. Please update `.gitignore` to reflect that.

The compiler outputs such as *.lib and *.exp have moved into `/apps` and `/engines` directories in openssl-1.1 other than `/out32dll`. Please update the `Windows` section in `.gitignore`.

**Comment by richsalz** [comment]
+1 @levitte

**Comment by levitte** [comment]
Fixed in #1192

**Comment by levitte** [comment]
Now fixed, so closing.
