### ISSUE TITLE
Obtaining method of extracting OPenssl certificate information

### ISSUE THREAD

**Issue by MrNew** [openssl/openssl#11382]
Obtaining method of extracting OPenssl certificate information.
But I can't figure out the logic of the source code, the library 27M of openssl for iOS is too big for me.
Help Me,please.

**Comment by mattcaswell** [comment]
You'll have to give us a bit more information about what you are trying to do. Are we talking about extracting information from a cert on the command line or in code? If the latter, have you already loaded the cert and got an X509 object handle on it? What information are you looking to extract?
