### ISSUE TITLE
OpenSSL 1.1.1e: clients sends more alerts after TLS shutdown (close_notify) was send

### ISSUE THREAD

**Issue by noxxi** [openssl/openssl#11388]
The TLS RFC states that after the close_notify no more messages should be send. OpenSSL 1.1.1e seems to have introduced a bug where it still sends more messages even after the close_notify. 

This problem can be triggered if the client sends a close_notify but the server does not, i.e. the server closes the connection directly. In this case the client will send another alert. 

Take the following example code fragment (full code at https://pastebin.com/i28hWcCr):

```
 39     res = SSL_connect(ssl);
 40     assert(res == 1);
 41 
 42     strcpy(buf, "GET / HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n");
 43     res = SSL_write(ssl, buf, strlen(buf));
 44     fprintf(stderr,"SSL_write len=%ld res=%d\n", strlen(buf), res);
 45 
 46     SSL_shutdown(ssl);
 47     shutdown(sock,1);
 48 
 49     res = SSL_read(ssl, &buf, sizeof(buf));
 50     fprintf(stderr,"SSL_read res=%d err=%d\n", res, SSL_get_error(ssl, res));
```

After connecting (line 39) and writing some data (line 43) the SSL layer will be shutdown (line 46) and then the socket will be shutdown for writing (line 47) to make sure that it definitely will not write any more data. Then it will try to read the response from the server (line 49). 

With a server properly shutting down the SSL connection all will be well. With a server closing the TCP connection without shutting down the SSL part first (as in https://pastebin.com/MtXFQKCK) the client will get the socket close and likely as a result of the improper shutdown write another alert to the socket, which results in a SIGPIPE due to the explicit TCP shutdown in line 47 (without the shutdown the alert will also be send but the effect can be better seen with SIGPIPE).

The relevant strace output of the program:

```
   157  write(3, "\27\3\3\0003rI\23\227\362\355\315T\350\334\205\342\335>SC\311\351\202\6\2762\326\375\316\274\7"..., 56) = 56
   158  write(2, "SSL_write len=35 res=35\n", 24SSL_write len=35 res=35
   159  ) = 24
   160  write(3, "\25\3\3\0\22d{\365\303\303\211<Z\250\341H\261\372^\\\342)\25", 23) = 23
   161  shutdown(3, SHUT_WR)                    = 0
   162  read(3, "", 5)                          = 0
   163  write(3, "\25\3\3\0\22X\224\315\0358d\363\204r\0\4*K{V\4\205\1", 23) = -1 EPIPE (Broken pipe)
   164  --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=14910, si_uid=1001} ---
   165  write(2, "SSL_read res=0 err=1\n", 21SSL_read res=0 err=1
   166  )  = 21
```

In line 160 the sending of the close_notify from the SSL shutdown can be seen followed by the shutdown of the TCP socket in line 161. The SSL_read in the code will then result in the read in line 162 which returns 0, i.e. server closed socket. Line 162 then shows the attempt to write another alert to the socket which results in a SIGPIPE due to the previous TCP shutdown. The err=1 from SSL_read in the output (line 165) is the result from SSL_get_error and is SSL_ERROR_SSL.

The problem is the same with TLS 1.3 only that due to the new record layer with opaque_type always being application_data alerts are not that clearly visible in the strace output.

**Comment by roussosalex** [comment]
This is related to #11378 and #11381. The new EOF detection in `1.1.1e` detects the missing close notify as an error and attempts to send an error alert on the non-writable socket, which is what you see.

In general, `SSL_read` can also write on the socket as per the documentation:
> As at any time it's possible that non-application data needs to be sent, a read function can also cause write operations.

So you should not close the write side before complete shutdown anyways. If you want to completely avoid sending the second alert in case the server terminates without a close notify, you can only avoid calling `SSL_read` after the shutdown or downgrade to `1.1.1d` until this gets resolved.

**Comment by kroeckx** [comment]
This is clearly a bug in OpenSSL, it should not try to send
something after it has already sent the close notify.

> So you should not close the write side before complete shutdown anyways. If you want to completely avoid sending the second alert in case the server terminates without a close notify, you can only avoid calling `SSL_read` after the shutdown or downgrade to `1.1.1d` until this gets resolved.

Doing a shutdown should work as soon as you're done sending.

The client and/or server should be fixed so that there is no
unexpected EOF. That is:
- If the protocol requires that a close notify is used then the
  server should get fixed to send it.
- If the protocol does not require a close notify then the client
  should be fixed to not require it. But it's highly recommended
  that the server always sends the close notify, even when not
  required.

**Comment by noxxi** [comment]
Given the discussions here on how real client and server should behave: The goal of this bug report is only to describe the bug that OpenSSL, i.e. that it sends more data after it has send a close_notify. The code examples I gave are only there to make reproducing the bug easy and do not reflect my production code.

My intention was not to discuss how client and servers should behave properly but to focus only on the issue in OpenSSL. In fact, the bug was discovered by tracking down behavior changes in tests dealing with deliberately bad behaving peers.

**Comment by ct9915** [comment]
After my anaconda environment updating openssl to 1.1.1e , the conda update could not use openssl anymore and suffered the same issues. Because it is an openssl issue, the conda cannot downgrade openssl package to 1.1.1d. My current workaround is to fresh reinstall  anaconda and prevent openssl upgrading to 1,1,1e.

**Comment by kaduk** [comment]
Kurt, do you know if anyone has started looking for the openssl bug here?

**Comment by kroeckx** [comment]
Not that I know

**Comment by ct9915** [comment]
the 1.1,1f fix works like a charm

**Comment by tomato42** [comment]
I see this still in master, using 1f3b58d8413cf.

   <details><summary>Reproducer:</summary><p>

```
wget https://raw.githubusercontent.com/redhat-qe-security/certgen/master/certgen/lib.sh
source lib.sh
x509KeyGen ca
x509KeyGen server
x509KeyGen client

x509SelfSign ca
x509CertSign --CA ca server
x509CertSign --CA ca -t webclient client


openssl s_server -www -CAfile $(x509Cert ca) -key $(x509Key server) -cert $(x509Cert server) -verify 1 &> server.log &
server_pid=$?


git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tlsfuzzer/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/tlsfuzzer/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python scripts/test-extended-master-secret-extension-with-client-cert.py -k $(x509Key client) -c $(x509Cert client) -d
popd
kill $openssl_pid
```

   </p></details>

   <details><summary>tlsfuzzer output:</summary><p>

```
sanity ...
Error encountered while processing node <tlsfuzzer.expect.ExpectClose object at 0x7f694092f7c0> (child: None) with last message being: <tlslite.messages.Message object at 0x7f69408b9ee0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-extended-master-secret-extension-with-client-cert.py", line 342, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 232, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)

with certificate ...
Error encountered while processing node <tlsfuzzer.expect.ExpectClose object at 0x7f694092fc40> (child: None) with last message being: <tlslite.messages.Message object at 0x7f69408b9a60>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-extended-master-secret-extension-with-client-cert.py", line 342, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 232, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)

resume with certificate and EMS ...
Error encountered while processing node <tlsfuzzer.expect.ExpectClose object at 0x7f69408b92e0> (child: <tlsfuzzer.messages.Close object at 0x7f69408b9340>) with last message being: <tlslite.messages.Message object at 0x7f69408b9bb0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-extended-master-secret-extension-with-client-cert.py", line 342, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 232, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)

sanity ...
Error encountered while processing node <tlsfuzzer.expect.ExpectClose object at 0x7f694092f7c0> (child: None) with last message being: <tlslite.messages.Message object at 0x7f69408b9dc0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-extended-master-secret-extension-with-client-cert.py", line 342, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 232, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)

Test to verify if server supports extended master secret with 
client certificates.

Test end
====================
version: 2
====================
TOTAL: 4
SKIP: 0
PASS: 0
XFAIL: 0
FAIL: 4
XPASS: 0
====================
FAILED:
        'resume with certificate and EMS'
        'sanity'
        'sanity'
        'with certificate'
```
  </p></details>


When looking at packet capture, two alert packets are visible from the openssl server, first a close_notify, the other illegal_parameter (sent after client sent close_notify).
