### ISSUE TITLE
Does SSL_OP_NO_RENEGOTIATION Disable all renegotiation in TLSv1.2 and earlier?

### ISSUE THREAD

**Issue by hehechen** [openssl/openssl#11389]
Here is SSL_OP_NO_RENEGOTIATION in openssl doc, [https://www.openssl.org/docs/man1.1.1/man3/SSL_get_options.html](url)
SSL_OP_NO_RENEGOTIATION
**Disable all renegotiation** in TLSv1.2 and earlier. Do not send HelloRequest messages, and ignore renegotiation requests via ClientHello.
But here is SECURE RENEGOTIATION in openssl doc:
Patched client and server
Connections and **renegotiation are always permitted** by OpenSSL implementations.
If I set SSL_OP_NO_RENEGOTIATION, and communicate with patched client or server, will all renegotiation be disabled?
openssl version:1.1.1c

**Comment by mattcaswell** [comment]
If you set `SSL_OP_NO_RENEGOTIATION` then renegotiation is disabled. The text in the `SECURE RENEGOTIATION` section is describing how secure reneg works - but assumes that you have it enabled. If its disabled then nothing in that section applies.

**Comment by hehechen** [comment]
> If you set `SSL_OP_NO_RENEGOTIATION` then renegotiation is disabled. The text in the `SECURE RENEGOTIATION` section is describing how secure reneg works - but assumes that you have it enabled. If its disabled then nothing in that section applies.

I have set SSL_OP_NO_RENEGOTIATION in TLS server source code, and tried to use openssl s_client to test renegotiation, after entering `R` , renegotiation successed.
openssl version:1.1.1c, TLS1.2

**Comment by mattcaswell** [comment]
How are you setting this option - via config file or via code? If so are you setting on the SSL_CTX or on the SSL object? Do you have a code sample of what you are doing?

**Comment by hehechen** [comment]
> How are you setting this option - via config file or via code? If so are you setting on the SSL_CTX or on the SSL object? Do you have a code sample of what you are doing?

I set on the SSL object.
```
   SSL*ssl = SSL_new (ssl_ctx);
    SSL_set_fd(ssl, socket_fd);
    SSL_set_mode(ssl, SSL_MODE_ENABLE_PARTIAL_WRITE  | SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER | SSL_OP_NO_RENEGOTIATION);
    SSL_clear_options(ssl, SSL_OP_LEGACY_SERVER_CONNECT);
```

**Comment by mattcaswell** [comment]
Ah. `SSL_OP_NO_RENEGOTIATION`  is not a mode. It's an option. You need to use `SSL_set_options`:

````
    SSL_set_options(s, SSL_OP_NO_RENEGOTIATION);
````

**Comment by hehechen** [comment]
> Ah. `SSL_OP_NO_RENEGOTIATION` is not a mode. It's an option. You need to use `SSL_set_options`:
> 
> ```
>     SSL_set_options(s, SSL_OP_NO_RENEGOTIATION);
> ```

you're right, thank you
