### ISSUE TITLE
openssl invalid cmd name error

### ISSUE THREAD

**Issue by Parradox27** [openssl/openssl#11395]
Hello,
I have finally deployed an openssl utility onto an STM32MP1 board (ARM Cortex A7). I am developing an application for creating signatures and I want to take advantage of hardware acceleration that is available. This is why I have also installed devcrypto and built openssl with support for devcrypto. The problem is, that the supported algorithms for HW acceleration are only ciphers, there are no digests available whatsoever, even though HW acceleration for digests is possible on this board (checked with /proc/crypto). I have tried modifying openssl.cnf like this:
```
openssl_conf = openssl_section
[openssl_section]
engines = engine_section
[engine_section]
devcrypto = devcrypto_section
[devcrypto_section]
default_algorithms = ALL
CIPHERS = ALL
DIGESTS = ALL
```
However, the last two lines become problematic and cause following output, when issuing ```openssl engine``` :
```
(devcrypto) /dev/crypto engine
(dynamic) Dynamic engine loading support
3069665296:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:../../../../../../workspace/sources/openssl/crypto/engine/eng_ctrl.c:255:
3069665296:error:260BC066:engine routines:int_engine_configure:engine configuration error:../../../../../../workspace/sources/openssl/crypto/engine/eng_cnf.c:141:section=devcrypto_section, name=CIPHERS, value=ALL
3069665296:error:0E07606D:configuration file routines:module_run:module initialization error:../../../../../../workspace/sources/openssl/crypto/conf/conf_mod.c:177:module=engines, value=engine_section, retcode=-1
```

Removing CIPHERS line would cause invalid command error for DIGESTS as well.

I have tried to use the option -DUSE_CRYPTODEV_DIGESTS as well, but there is no effect of that.

I am using openssl 1.1.1b since it is the latest one that has a recipe for bitbake, which was used for building.  Here is also output of ```openssl version -f```:
```
compiler: arm-ostl-linux-gnueabi-gcc  -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=recipe-sysroot -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DNDEBUG -DUSE_CRYPTODEV_DIGESTS
```

The board has a custom linux distribution (OpenSTLinux), which is part of the Yocto project.

EDIT: Managed to install version 1.1.1e but still the same problem.

**Comment by Parradox27** [comment]
Does anyone have any idea, why the command is invalid?

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
