### ISSUE TITLE
SubjectPublicKeyInfo must not use id-RSASSA-PSS

### ISSUE THREAD

**Issue by DemiMarie-parity** [openssl/openssl#11397]
This is forbidden by <https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md#511-rsa>.

**Comment by levitte** [comment]
This contradicts [RFC 4055](https://tools.ietf.org/html/rfc4055#section-1.2), where you can find this:

>    When the RSA private key owner wishes to limit the use of the public
>    key exclusively to RSASSA-PSS, then the id-RSASSA-PSS object
>    identifier MUST be used in the algorithm field within the subject
>    public key information, and, if present, the parameters field MUST
>    contain RSASSA-PSS-params.  The id-RSASSA-PSS object identifier value
>    and the RSASSA-PSS-params syntax are fully described in Section 3.
> 
>    When the RSA private key owner wishes to limit the use of the public
>    key exclusively to RSAES-OAEP, then the id-RSAES-OAEP object
>    identifier MUST be used in the algorithm field within the subject
>    public key information, and, if present, the parameters field MUST
>    contain RSAES-OAEP-params.  The id-RSAES-OAEP object identifier value
>    and the RSAES-OAEP-params syntax are fully described in Section 4.

The update in [RFC 5756](https://tools.ietf.org/html/rfc5756) hasn't changed that as far as I can see.

**Comment by mattcaswell** [comment]
> This is forbidden by https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md#511-rsa.

This is Mozilla's policy for its root store. This applies additional restrictions and guidance on top of what the standards say. The *standards* allow use of id-RSASSA-PSS. OpenSSL conforms to the standards. It does not seek to enforce any additional restrictions that individual organisations might specify. This is up to the users of OpenSSL.

So - I don't believe this is an issue in OpenSSL.
