### ISSUE TITLE
openssl(1): support overriding RSA signature algorithm type

### ISSUE THREAD

**Issue by Demi-Marie** [openssl/openssl#11408]
When signing a CSR with an RSA-PSS public key, openssl(1) should have an option to force the AlgorithmIdentifier to be that of RSA, not that of RSA-PSS.  openssl(1) should also have an option to force the use of RSA-PSS or RSA PKCS1.5 irrespective of what kind of RSA key is used.

**Comment by levitte** [comment]
The way to do this is with an unlimited / plain RSA key, but sign with additional RSASSA-PSS parameters.  Incidently, we recently added `-sigopt` to `openssl ca` for exactly that sort of purpose.  I'm not sure we've tested exactly this scenario, though...  that should be subject for a few interesting test cases.

Note: master branch only, i.e. upcoming version 3.0

**Comment by DemiMarie-parity** [comment]
> The way to do this is with an unlimited / plain RSA key, but sign with additional RSASSA-PSS parameters. Incidently, we recently added `-sigopt` to `openssl ca` for exactly that sort of purpose. I'm not sure we've tested exactly this scenario, though... that should be subject for a few interesting test cases.
> 
> Note: master branch only, i.e. upcoming version 3.0

Would it be possible to support this with `openssl x509` as well?

**Comment by levitte** [comment]
> Would it be possible to support this with `openssl x509` as well?

Already done

**Comment by t8m** [comment]
This is done already for the req app as well in the current master. Closing.
