### ISSUE TITLE
How to link OpenSSL to a application is built with /MT flag in windows

### ISSUE THREAD

**Issue by pavan-linux** [openssl/openssl#11414]
My application uses /MT flag in windows but when I build openssl with default parameters it is building with /MD option and when I run  application crashes in openssl( included applink.c in my executable).

i can't change my application to /MD  so is there any way to link openssl to my application with shared library(DLL)

**Comment by bernd-edlinger** [comment]
Are you even using the same msvc runtime version than your application ?

**Comment by bernd-edlinger** [comment]
IF you can change the application to use File-BIO instead of using
openssl APIs which are passing FILE *, then you are of course less dependent
on applink.c

**Comment by demian51** [comment]
I'm suffering from this issue too. I tried to update to 1.1.1f from 1.1.0e and cannot link the application.
I dug `configdata.pm` and compiler log and found that openssl builds library with `/MD` whether using `-static` or not in 1.1.1f.
In 1.1.0e it attaches `/MT` as expected and the application is linked well. IMHO it seems that `/MT` had been omitted by mistake when the build script was revised...

**Comment by demian51** [comment]
I found the solution. In 1.1.1f `-static` don't automatically enable `no-shared` option. I set the option explicitly the problem solved. `/MT` is attached and works well.

**Comment by t8m** [comment]
Closing as answered above.
