### ISSUE TITLE
Porting to 1.1.1e

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#11418]
Hi,

I am currently using openssl 1.0.2n version.
Would like to port the same to 1.1.1e version.
I have below queries related to the same:
- What are the points that I have to take care of in doing this?
- Will there be any compatibility issues?
- Is there any porting related document available?

Any help is appreciated.

Target OS: Windows 7/10

Thanks in advance.

Regards,
Amal

**Comment by levitte** [comment]
The biggest change is that a lot of OpenSSL types have been made opaque, i.e. you can't stack allocate them any more, but must use allocator functions.

There is a [community driven page on our wiki](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes) that discusses these changes and give some guidance.  Please take the "No longer works" section with a grain of salt, as it's a bit outdated.

**Comment by amaljesudas** [comment]
Thanks Richard for the insight.
I will check the same.

Regards,
Amal
