### ISSUE TITLE
OpenSSL 1.1.1e version BN_CTX_free -> "segmentation fault"

### ISSUE THREAD

**Issue by lijk8090** [openssl/openssl#11429]
BN_CTX_new
BN_CTX_start

**BN_CTX_get(ctx)**
**... ...**
**many times**

BN_CTX_end
BN_CTX_free

and then, when I call BN_CTX_free(ctx), It will occure "segmentation fault".

but this same code will work on 1.0.2 version very well.

what's wrong with me?

**Comment by lijk8090** [comment]
Just like:

![image](https://user-images.githubusercontent.com/10040463/77812810-c6e26d80-70de-11ea-9389-c04280ba8a20.png)


and then, I call the BN_new instead of BN_CTX_get function

It work properly, do not "segmentation fault" again.

thank you

**Comment by romen** [comment]
This pattern should be working, and is used extensively both in the library code and in tests.

Can you provide a minimal working example to reproduce the segmentation fault?

**Comment by lijk8090** [comment]
I am not sure, because it is a part of big soafeware

it is hard to spun off

**Comment by lijk8090** [comment]
sorry, I made a mistake.

I call "BN_free" after "BN_CTX_get"

such as:

    b = BN_CTX_get();
    BN_free(b); // this should not be called

so I got the "segmentation fault".

**Comment by richsalz** [comment]
Do not call BN_free; BN's are released when the context is free'd.
