### ISSUE TITLE
Falling back to legacy when we shouldn't

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11424]
In some internal tests I just saw a TLS connection successfully perform an X25519 operation in a library context which only had the FIPS provider loaded - not the default provider. This is unexpected because X25519 does not exist in the FIPS provider (yet).

The reason seems to be because in our key exchange code we attempt to fetch the algorithm from the available providers. However if that does not work we fallback to legacy and see if the legacy path can help us. And of course in this case it can.

This is undesirable because if you only have the FIPS provider loaded you only want FIPS crypto being performed. Anything else should fail.

We should only really fallback to legacy if we know that an engine can service the request.

My guess is this same issue applies to other operations besides key exchange.

**Comment by levitte** [comment]
Yup.  However, we're still in an interim state when *everything* hasn't moved to providers (I'm still working on complete RSA-PSS support in a local branch, for example).  It's much to early at this time to turn off that fallback.

BTW, turning off the fallback is fairly simple...  it should enough to empty this array:

https://github.com/openssl/openssl/blob/9e2c03582de42e8ac5aa23412affcb9645395e94/crypto/evp/pmeth_lib.c#L39-L85

... and possibly this array:

https://github.com/openssl/openssl/blob/9e2c03582de42e8ac5aa23412affcb9645395e94/crypto/asn1/standard_methods.h#L15-L60

... although I suspect that emptying that array comes with consequences.

**Comment by mattcaswell** [comment]
Can we empty the arrays where we *have* completed the conversion (which is most of them)? Just leave the ones which are incomplete?

**Comment by sahanaprasad07** [comment]
@levitte Hello, what do you think about turning off the fallback now?

**Comment by levitte** [comment]
I could see dropping the array of "standard" `EVP_PKEY_METHOD`s.  Regarding `EVP_PKEY_ASN1_METHOD`, I'm a little more dubious, as they serve to export legacy EVP_PKEYs to provider EVP_PKEYs, among others...

**Comment by levitte** [comment]
Actually, it's even easier than I imagined.  PR coming up!

**Comment by levitte** [comment]
See #13973
