### ISSUE TITLE
The change of unexpected EOF reporting - revert and release 1.1.1f ?

### ISSUE THREAD

**Issue by MSP-Greg** [openssl/openssl#11436]
Re the change in EOF reporting in 1.1.1e:

From a [Fedora list post](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/O6L32KT4H2ZRK4E5JLZ2FFTVCJFYUGU6/), it is stated:

> It shows that this does not only break Python's own test suite, but various Python packages are failing as well (incl. python-pip).

They seem to be reverting the change in OpenSSL itself.

The change has also affected Ruby and Ruby Gems using OpenSSL.

I don't care about master (see Issue https://github.com/openssl/openssl/issues/11423), as any major release is likely to require changes.  But, 1.1.1e should not break code that worked in 1.1.1d.

As to the problem in Ruby (and I suspect the same with Python), in Ruby's OpenSSL code, some OpenSSL errors are translated into socket or IO errors that are already defined in Ruby.

With the change in the EOF error response, that translation doesn't happen, and the new SSL error is not caught, as the old EOF error was.

Hence, please consider releasing 1.1.1f with the EOF change reverted.

**Comment by mspncp** [comment]
The breaking change has already been reverted on 1.1.1 (see 30d190caf311d534867df97e26b552e628cb7d85 and 0cd2ee64bffcdece599c3e4b5fac3830a55dc0fa) and the [release of 1.1.1f is scheduled for next tuesday](https://mta.openssl.org/pipermail/openssl-announce/2020-March/000168.html).

**Comment by MSP-Greg** [comment]
Thank you.  I apologize for not looking at the recent commits.  Closing.

**Comment by mspncp** [comment]
No problem :-)
