### ISSUE TITLE
generate_ssl_tests.pl can't be run anymore following the docs

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#11430]
test/README.ssltest.md says to use:
```
$ cd test
$ TOP=.. perl -I ../util/perl/ generate_ssl_tests.pl ssl-tests/my.cnf.in \
  > ssl-tests/my.cnf
```

But that no longer works. I get:
`Cannot find current script 'generate_ssl_tests.pl' at /usr/share/perl/5.30/FindBin.pm line 166`

The problem is that it does chdir(../test-runs/no_test_here) just before trying to open the file.

**Comment by kroeckx** [comment]
@levitte: Is this something you can look at?

**Comment by levitte** [comment]
> @levitte: Is this something you can look at?

Yup

**Comment by levitte** [comment]
Would it be suitable enough if OpenSSL::Test only did said `chdir` if it detects that it's run under the test harness?

**Comment by mattcaswell** [comment]
I'd say so.

**Comment by slontis** [comment]
I imagine multiple people have got around this by copying the generated .none file..
I don't know what the history of this process is - but it seems counter-productive.

**Comment by richsalz** [comment]
Overin #15411 I tried this:
```
 TOP=.. perl -I../util/perl generate_ssl_tests.pl \
ssl-tests/17-renegotiate.cnf.in 
```

And @mattcaswell suggested using full pathnames as a work-around.
That doesn't work either, or I am making a silly mistake:
```
; x=`/bin/pwd`
; echo $x ; pwd
/home/rsalz/openssl/github/test
; TOP=.. perl -I$x/../util/perl $x/generate_ssl_tests.pl $x/ssl-tests/17-renegotiate.cnf.in >/tmp/x
Use of uninitialized value $provider in string eq at /home/rsalz/openssl/github/test/generate_ssl_tests.pl line 131.
Use of uninitialized value $provider in string eq at /home/rsalz/openssl/github/test/generate_ssl_tests.pl line 132.
Use of uninitialized value $provider in string eq at /home/rsalz/openssl/github/test/generate_ssl_tests.pl line 132.
```

I fixed that error by this (which will be in my PR)
```
diff --git a/test/generate_ssl_tests.pl b/test/generate_ssl_tests.pl
index cdb35cc150..22cff7125f 100644
--- a/test/generate_ssl_tests.pl
+++ b/test/generate_ssl_tests.pl
@@ -141,7 +141,7 @@ sub read_config {
 }
 
 my $input_file = shift;
-my $provider = shift;
+my $provider = shift // 'default';
 # Reads the tests into ssltests::tests.
 read_config($input_file, $provider);
 print_templates();
```
