### ISSUE TITLE
Configure/make leaves install directory empty on macOS

### ISSUE THREAD

**Issue by lincoln-b** [openssl/openssl#11437]
Cross-compiling openssl for android-arm64 on my Macbook Pro (macOS Catalina 10.15.3) leaves the install directory completely empty. I suspect this may have to do with subtle differences between the macOS shell and Linux's bash, but that's just a shot in the dark.

Here's my install script, run from a directory containing the openssl source repository (pwd is /Users/lincolnbergeson/Workspace/rostrum/deps):

```
#!/usr/bin/env bash

cd openssl
make clean

DIRNAME=build-android
rm -rf $DIRNAME
mkdir $DIRNAME
PREFIX="$(pwd)/$DIRNAME"

export ANDROID_NDK_ROOT=/Users/lincolnbergeson/Library/Android/sdk/ndk/21.0.6113669
export PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/bin:$PATH"

./Configure android-arm64 --prefix="$PREFIX"
make

cd ..
```

The script completes without errors, but `find openssl/build-android` reveals an empty directory. However, `find openssl -name "*.a"` shows these libraries in the openssl directory:

```
openssl/libcrypto.a
openssl/test/libtestutil.a
openssl/providers/libfips.a
openssl/providers/liblegacy.a
openssl/providers/libnonfips.a
openssl/providers/libimplementations.a
openssl/providers/libcommon.a
openssl/libssl.a
openssl/apps/libapps.a
```

Configure is setting INSTALLTOP in the Makefile properly:

```
$ grep INSTALLTOP openssl/Makefile
INSTALLTOP=/Users/lincolnbergeson/Workspace/rostrum/deps/openssl/build-android
```

But for some reason, make leaves INSTALLTOP empty.

See the attached file for the output of `perl openssl/configdata.pm --dump`.

[configdata.txt](https://github.com/openssl/openssl/files/4399541/configdata.txt)

**Comment by kaduk** [comment]
(The macOS shell being zsh as of Catalina, as opposed to the bash that it previously was.)  You should still be able to run `bash` manually and try a build in that shell.  I don't have my hopes up that it will change things, though.

**Comment by lincoln-b** [comment]
Just tried it, unfortunately that does not make a difference.

**Comment by lincoln-b** [comment]
Is it possible that there is something wrong with my invocation? Or is this a more general issue with Configure and macOS compatibility?

I just tried to run `./Configure darwin64-x86_64-cc --prefix="$PREFIX"` and had the same problem. Now I'm starting to doubt it is Android specific.

**Comment by levitte** [comment]
`make` only builds it.  `make install` installs it where you asked.

**Comment by lincoln-b** [comment]
Well, that's a mistake I won't make twice 🤦‍♂
