### ISSUE TITLE
make[1]: *** [objs/src/event/ngx_event_openssl.o] Error 1 (nginx 1.6 + openssl 1.1.0)

### ISSUE THREAD

**Issue by wanggaolin** [openssl/openssl#1143]
I make nginx hava  error:

cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DLDAP_DEPRECATED -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/openssl-1.1.0-pre5/.openssl/include -I objs \
                -o objs/src/event/ngx_event_openssl.o \
                src/event/ngx_event_openssl.c
cc1: warnings being treated as errors
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_init’:
src/event/ngx_event_openssl.c:101: error: ‘OPENSSL_config’ is deprecated (declared at /usr/local/src/openssl-1.1.0-pre5/.openssl/include/openssl/conf.h:140)
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_rsa512_key_callback’:
src/event/ngx_event_openssl.c:590: error: ‘RSA_generate_key’ is deprecated (declared at /usr/local/src/openssl-1.1.0-pre5/.openssl/include/openssl/rsa.h:245)
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_dhparam’:
src/event/ngx_event_openssl.c:637: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:638: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:640: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:640: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_handshake’:
src/event/ngx_event_openssl.c:856: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:857: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_connection_error’:
src/event/ngx_event_openssl.c:1618: error: ‘SSL_R_SSLV3_ALERT_UNEXPECTED_MESSAGE’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1618: error: (Each undeclared identifier is reported only once
src/event/ngx_event_openssl.c:1618: error: for each function it appears in.)
src/event/ngx_event_openssl.c:1619: error: ‘SSL_R_SSLV3_ALERT_BAD_RECORD_MAC’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1620: error: ‘SSL_R_TLSV1_ALERT_DECRYPTION_FAILED’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1621: error: ‘SSL_R_TLSV1_ALERT_RECORD_OVERFLOW’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1622: error: ‘SSL_R_SSLV3_ALERT_DECOMPRESSION_FAILURE’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1623: error: ‘SSL_R_SSLV3_ALERT_HANDSHAKE_FAILURE’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1624: error: ‘SSL_R_SSLV3_ALERT_NO_CERTIFICATE’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1625: error: ‘SSL_R_SSLV3_ALERT_BAD_CERTIFICATE’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1626: error: ‘SSL_R_SSLV3_ALERT_UNSUPPORTED_CERTIFICATE’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1627: error: ‘SSL_R_SSLV3_ALERT_CERTIFICATE_REVOKED’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1628: error: ‘SSL_R_SSLV3_ALERT_CERTIFICATE_EXPIRED’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1629: error: ‘SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1630: error: ‘SSL_R_SSLV3_ALERT_ILLEGAL_PARAMETER’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1631: error: ‘SSL_R_TLSV1_ALERT_UNKNOWN_CA’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1632: error: ‘SSL_R_TLSV1_ALERT_ACCESS_DENIED’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1633: error: ‘SSL_R_TLSV1_ALERT_DECODE_ERROR’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1634: error: ‘SSL_R_TLSV1_ALERT_DECRYPT_ERROR’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1635: error: ‘SSL_R_TLSV1_ALERT_EXPORT_RESTRICTION’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1636: error: ‘SSL_R_TLSV1_ALERT_PROTOCOL_VERSION’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1637: error: ‘SSL_R_TLSV1_ALERT_INSUFFICIENT_SECURITY’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1638: error: ‘SSL_R_TLSV1_ALERT_INTERNAL_ERROR’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1639: error: ‘SSL_R_TLSV1_ALERT_USER_CANCELLED’ undeclared (first use in this function)
src/event/ngx_event_openssl.c:1640: error: ‘SSL_R_TLSV1_ALERT_NO_RENEGOTIATION’ undeclared (first use in this function)
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_session_cache’:
src/event/ngx_event_openssl.c:1783: error: passing argument 2 of ‘SSL_CTX_sess_set_get_cb’ from incompatible pointer type
/usr/local/src/openssl-1.1.0-pre5/.openssl/include/openssl/ssl.h:715: note: expected ‘struct SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *)’ but argument is of type ‘struct SSL_SESSION * (*)(struct SSL *, u_char *, int,  int *)’
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_session_id_context’:
src/event/ngx_event_openssl.c:1805: error: storage size of ‘md’ isn’t known
src/event/ngx_event_openssl.c:1871: error: implicit declaration of function ‘EVP_MD_CTX_cleanup’
src/event/ngx_event_openssl.c:1805: error: unused variable ‘md’
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_new_session’:
src/event/ngx_event_openssl.c:2048: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:2048: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:2050: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:2050: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:2057: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_remove_session’:
src/event/ngx_event_openssl.c:2223: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:2224: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_session_ticket_key_callback’:
src/event/ngx_event_openssl.c:2520: error: ‘RAND_pseudo_bytes’ is deprecated (declared at /usr/local/src/openssl-1.1.0-pre5/.openssl/include/openssl/rand.h:99)
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_get_session_id’:
src/event/ngx_event_openssl.c:2612: error: dereferencing pointer to incomplete type
src/event/ngx_event_openssl.c:2613: error: dereferencing pointer to incomplete type
make[1]: *** [objs/src/event/ngx_event_openssl.o] Error 1
make[1]: Leaving directory `/usr/local/src/nginx-1.6.2'
make: *** [build] Error 2

make nginx  config argument(nginx 1.6 + openssl 1.1.0):
./configure --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-http_flv_module --add-module=/usr/local/src/nginx-auth-ldap --with-http_realip_module  --with-openssl=/usr/local/src/openssl-1.1.0-pre5  && make 

How should I do? thanks!

**Comment by levitte** [comment]
The OpenSSL API has changed quite a bit in 1.1.0...  this means that nginx needs some work to adapt.  I recommend you talk with the nginx folks.

**Comment by ghedo** [comment]
nginx 1.11.0 builds fine with OpenSSL master.
