### ISSUE TITLE
What's the default Elliptic Curve in ECDHE cipher suites?

### ISSUE THREAD

**Issue by hehechen** [openssl/openssl#11444]
In TLS1.2， openssl 1.1.1c, what Elliptic Curve is used in ECDHE cipher suites if I don't set `SSL_CTX_set1_groups_list` or `SSL_CTX_set_tmp_ecdh` ?
If I would use  `brainpoolP384r1` and `brainpoolP512r1`, rather than use NIST  Elliptic Curve such as `secp384r1`,  should I need to use `SSL_CTX_set1_groups_list(ssl_ctx, "brainpoolP384r1:brainpoolP512r1")`?

**Comment by bernd-edlinger** [comment]
The NIST curves outperform Brainpool by far.
So be careful what you wish....

**Comment by bernd-edlinger** [comment]
That has to do also with availability of assembler sopport for NIST,
and not for Brainpool.  If you like to implement an efficient Brainpool
implemenation, I can show you how to enable that for TLS 1.2
Unfortunatley nobody (except me) want to see Brainpool in TLS 1.3

**Comment by hehechen** [comment]
> That has to do also with availability of assembler support for NIST,
> and not for Brainpool. If you like to implement an efficient Brainpool
> implementation, I can show you how to enable that for TLS 1.2
> Unfortunately nobody (except me) want to see Brainpool in TLS 1.3

This PR [https://github.com/SWI-Prolog/packages-ssl/pull/71](url) 
said that after OpenSSL1.1.0,  the new default curve is X25519. I don't know if he is right.

**Comment by hehechen** [comment]
> That has to do also with availability of assembler support for NIST,
> and not for Brainpool. If you like to implement an efficient Brainpool
> implementation, I can show you how to enable that for TLS 1.2
> Unfortunately nobody (except me) want to see Brainpool in TLS 1.3

Actually, I don’t pay much attention to performance.  I just want to avoid the NIST elliptic curve algorithm for security.

**Comment by bernd-edlinger** [comment]
Please look at #7435 maybe that helps how to configure Brainpool,
I also have a PR for enabling Brainpool for TLS 1.3 but nobody likes me:  #7485

**Comment by bernd-edlinger** [comment]
@hehechen 
Finally I managed to put together a PR enabling brainpool for 1.1.1 : #11782 
you have to enable the brainpool curves explicitly in client and server but it should work
