### ISSUE TITLE
ld: -u and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

### ISSUE THREAD

**Issue by Sunanda193839** [openssl/openssl#11455]
set_target_properties(${TARGETNAME} PROPERTIES LINK_FLAGS
    "-Wl,-wrap,xyz -u __wrap_xyz -Wl")

So whenever xyz is invoked I want __wrap_xyz to get called

I want bitcode enabled and hence have -fembed-bitcode flag set for the whole project. How top resolve the error: 
ld: -u and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

**Comment by gavaliswapnil** [comment]
hi how did sloved above error? 
kindly provide the solution.
