### ISSUE TITLE
Build and runtime issues found for WinCE/VS2008 in 1.1.1e

### ISSUE THREAD

**Issue by bjorn-lg** [openssl/openssl#11466]
Hi, 
 
### Overview
I recently build openSSL 1.1.1e for Windows CE v6.0 successfully, but in advance I found 3 issues:
-	Issue #1: I got one compilation errors that had to be corrected in the openssl code to compile it successfully for my Windows CE configuration (se configure.bat script below).
-	Issue #2: I found one bug that had to be corrected to run the TLS correctly, disabling optimization for function BN_num_bits_word(BN_ULONG l) solved the issue.
-	Issue #3: I also had to manually edit the makefile each time after the configure, before build, as showed in the attached patch-file “makefile.patch”.
 
### My system and config
My desktop machine for building the library (dll’s and .pdb-files) is Windows 10 64-bit, with Strawberry Pearl version 5.30.1.1, and NASM version 2.14.02. I use MS Visual Studio 2008 for application code development.
 
The following tools was also installed in the Visual Studio 2008 command promt:
cpan -i Text::Template
cpan -i Test::More
 
I use Visual Studio 2008 command prompt for configuring and building openssl. The bat-script I use (configure.bat) for configuring openssl before build, is as follows:

> set OSVERSION=WCE600
> set PLATFORM=VC-CE
> set TARGETCPU=ARMV4I
> set WCECOMPAT=C:\wcecompat
> 
> set LIB=C:\Program Files (x86)\Windows CE Tools\wce600\PHY3250_SCANMATIC_AL2\Lib\ARMV4I;C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\lib\ARMV4I;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib;
> 
> set INCLUDE=C:\Program Files (x86)\Windows CE Tools\wce600\PHY3250_SCANMATIC_AL2\Include\Armv4i;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\include
> 
> set Path=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\bin\x86_arm;%Path%
> 
> REM set LIBPATH="C:\Program Files (x86)\Windows CE Tools\wce600\PHY3250_SCANMATIC_AL2\Lib\ARMV4I";C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib;
> 
> C:\Strawberry\perl\bin\perl Configure no-idea no-mdc2 no-rc5 no-ssl2 no-ssl3 no-weak-ssl-ciphers no-comp no-async no-engine VC-CE
> 
> REM Now, remember to "git apply makefile.patch" (or modify content of makefile according to makefile.patch manually), then run build.bat.

To build openssl, I use: 

> nmake build_generated libcrypto-1_1.dll libssl-1_1.dll

 
### Now, to the proposals of code changes for the above mentioned issues:
 
Issue #1:
In /crypto/dso/dso_win32.c -> method win32_pathbyaddr(….), I got compilation errors on the four instances of (uintptr_t) (not defined). I solved this by replacing (uintptr_t) with (unsigned long). Please also see the first diff-entry in the attached file 1-1-1e.patch.pdf.
[1-1-1e.patch.pdf](https://github.com/openssl/openssl/files/4427390/1-1-1e.patch.pdf)

Issue #2:
In /crypto/bn/bn_lib.c, due to a bug for arm when optimization is enabled, I had to turn off optimization in front of function BN_num_bits_word(BN_ULONG l), and then re-enable it after this function, as explained here: https://mta.openssl.org/pipermail/openssl-users/2018-August/008465.html. Or else, I got run time errors with printouts from the opensssl library. For a general implementation, I guess some set of #if defined statements must be used, not to disable optimization for systems that does not has this issue. Please see https://mta.openssl.org/pipermail/openssl-users/2018-August/008465.html for suggestions on that. The second/last diff-entry in the attached file 1-1-1e.patch.pdf shows my solution, which disables optimization for function BN_num_bits_word(BN_ULONG l) in all cases, for simplicity.
[1-1-1e.patch.pdf](https://github.com/openssl/openssl/files/4427390/1-1-1e.patch.pdf)
 
Issue #3:
For Windows CE, we need to modify the makefile each time a new configure has occurred, before build, to set correct path/syntax to required additional library WCECOMPAT among others. The changes required is documented in the following attached patch-listing makefile.patch.pdf:
[makefile.patch.pdf](https://github.com/openssl/openssl/files/4427419/makefile.patch.pdf)

Is it possible to let the configure program automatically set these parameters correctly, given that the first 4 config-lines of configure.bat (above) has been set?

I hope this can help others to successfully build openSSL for Windows CE, or even better, if the suggestions above can be implemented in future versions of openSSL, to elliminate the need of modifications/fixes for Windows CE users.
 
Best Regards
Bjørn Liene Gundersen

**Comment by bernd-edlinger** [comment]
I have heared about your issue Nr. 2 already, that must be a bug in the microsoft
compiler FWIW, I would disable optimization for this target in general,
since you cannot trust this compiler to generate correct code, mind bug-attacks.
I am surprised to hear that openssl can be built for windows CE at all.
Mind you give us a short description of the steps you take to build this,
just as a reference for others, at least building for Windows CE is a non-trivial
task IMHO.

**Comment by aSoujyuTanaka** [comment]
#### About issue 1:
Replacing _uintptr_t_ to _unsigned long_ would be OK for WinCE but have a problem considering 64-bit Windows adopting LLP64 data model whose _long_ is 32 bits that is not wide enough for their pointer value.

With WinCE7 + VS2008, this problem does not occur because <crtdefs.h> have definition of uintptr_t as:
```
#ifndef _UINTPTR_T_DEFINED
#ifdef  _WIN64
typedef unsigned __int64    uintptr_t;
#else
typedef _W64 unsigned int   uintptr_t;
#endif
#define _UINTPTR_T_DEFINED
```
dso_win32.c includes <crtdefs.h> through following route:
"e_os.h" -> <windows.h> -> <excpt.h> -> <crtdefs.h>

The header file is in:
* C:\Program Files (x86)\Windows CE Tools\SDKs\SDKNAME\Include\Armv4i\crtdefs.h
* C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\include\crtdefs.h

From your comment on [my post](https://qiita.com/souju/items/94117c024862f57459c3), I assume you are using WinCE6 + VS2005. If you find <crtdefs.h> or other header file defining _uintptr_t_ on that development platform, though I'm not sure whether there is, including it is a reasonable way to solve the problem. I suppose appropriate VS directory might be "C:\Program Files (x86)\Microsoft Visual Studio 8" for VS2005. "Microsoft Visual Studio 9.0" is for VS2008.

#### About issue 2:
A reader of my post told me he had been getting error from EVP_DigestSignFinal() and the error is "error:0306E06C:bignum routines:BN_mod_inverse:no inverse". He said the error don't occur after optimization tweak you mentioned so I agree that the fix is absolutely needed for WinCE6. 
We use ARM cross compiler bundled with Platform Builder. Its version is 15.01.50304.03 and is newer than one included in VS2008 (15.00.20720). I'm almost sure the newer compiler don't have the problem. Once the fixed version is revealed, the appropriate change should be something like:
```
#if defined(_WIN32_WCE) && defined(_ARM_) && _MSC_VER<XXXX
#pragma optimize("",off)
#endif
int BN_num_bits_word(BN_ULONG l)
..
#if defined(_WIN32_WCE) && defined(_ARM_) && _MSC_VER<XXXX
#pragma optimize("",on)
#endif
```

#### About issue 3:
Yes, the build process will be much simplified if makefile is automatically set with correct parameters.

**Comment by bjorn-lg** [comment]
> I have heared about your issue Nr. 2 already, that must be a bug in the microsoft
> compiler FWIW, I would disable optimization for this target in general,
> since you cannot trust this compiler to generate correct code, mind bug-attacks.
> I am surprised to hear that openssl can be built for windows CE at all.
> Mind you give us a short description of the steps you take to build this,
> just as a reference for others, at least building for Windows CE is a non-trivial
> task IMHO.

Thanks a lot for your answer. Regarding a short description of the steps required to build openssl for Windows CE, I followed this post: https://qiita.com/souju/items/94117c024862f57459c3, but additionally made the openssl code changes listed above. 

Just to inform: I tried to build the new OpenSSL version 1.1.1f for Windows CE using the same steps as described above, but this time the build failed, so it seems like version 1.1.1f is less Windows CE compatible than 1.1.1e. I have posted a description of that build issue in post: https://github.com/openssl/openssl/issues/11563.

**Comment by bjorn-lg** [comment]
> #### About issue 1:
> Replacing _uintptr_t_ to _unsigned long_ would be OK for WinCE but have a problem considering 64-bit Windows adopting LLP64 data model whose _long_ is 32 bits that is not wide enough for their pointer value.
> 
> With WinCE7 + VS2008, this problem does not occur because <crtdefs.h> have definition of uintptr_t as:
> 
> ```
> #ifndef _UINTPTR_T_DEFINED
> #ifdef  _WIN64
> typedef unsigned __int64    uintptr_t;
> #else
> typedef _W64 unsigned int   uintptr_t;
> #endif
> #define _UINTPTR_T_DEFINED
> ```
> 
> dso_win32.c includes <crtdefs.h> through following route:
> "e_os.h" -> <windows.h> -> <excpt.h> -> <crtdefs.h>
> 
> The header file is in:
> 
> * C:\Program Files (x86)\Windows CE Tools\SDKs\SDKNAME\Include\Armv4i\crtdefs.h
> * C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\include\crtdefs.h
> 
> From your comment on [my post](https://qiita.com/souju/items/94117c024862f57459c3), I assume you are using WinCE6 + VS2005. If you find <crtdefs.h> or other header file defining _uintptr_t_ on that development platform, though I'm not sure whether there is, including it is a reasonable way to solve the problem. I suppose appropriate VS directory might be "C:\Program Files (x86)\Microsoft Visual Studio 8" for VS2005. "Microsoft Visual Studio 9.0" is for VS2008.
> 
> #### About issue 2:
> A reader of my post told me he had been getting error from EVP_DigestSignFinal() and the error is "error:0306E06C:bignum routines:BN_mod_inverse:no inverse". He said the error don't occur after optimization tweak you mentioned so I agree that the fix is absolutely needed for WinCE6.
> We use ARM cross compiler bundled with Platform Builder. Its version is 15.01.50304.03 and is newer than one included in VS2008 (15.00.20720). I'm almost sure the newer compiler don't have the problem. Once the fixed version is revealed, the appropriate change should be something like:
> 
> ```
> #if defined(_WIN32_WCE) && defined(_ARM_) && _MSC_VER<XXXX
> #pragma optimize("",off)
> #endif
> int BN_num_bits_word(BN_ULONG l)
> ..
> #if defined(_WIN32_WCE) && defined(_ARM_) && _MSC_VER<XXXX
> #pragma optimize("",on)
> #endif
> ```
> 
> #### About issue 3:
> Yes, the build process will be much simplified if makefile is automatically set with correct parameters.

Thank you very much for your comments. Regarding your question under Issue #1, I use WinCE6 + VS2008 (not VS2005). Regarding your comments for Issue #2, if you have any tip on how I can upgrade ARM cross compiler in Platform Builder, please let me know.

**Comment by aSoujyuTanaka** [comment]
WinCE7 Platform Builder is bundled with WinCE7. VS2008 SP1 is required:
https://stackoverflow.com/questions/15198497/platform-builder-for-wince-7-0
I'm not sure if it works with WinCE6.

**Comment by billbarni** [comment]
@bjorn-lg Could you release this builds through some channels? I'm having trouble setting up the environment to build OpenSSL for WinCE.

**Comment by t8m** [comment]
We are not going to add support for new platforms requiring code changes to 1.1.1. If you have any fixes for master branch to allow compiling on Win CE, please submit them as pull requests.

**Comment by mdeihly** [comment]
> Hi,
> 
> ### Overview
> I recently build openSSL 1.1.1e for Windows CE v6.0 successfully, but in advance I found 3 issues:
> 
> * Issue [Serverinfo #1](https://github.com/openssl/openssl/pull/1): I got one compilation errors that had to be corrected in the openssl code to compile it successfully for my Windows CE configuration (se configure.bat script below).
> * Issue [Improve XMPP protocol support for starttls on s_client  #2](https://github.com/openssl/openssl/pull/2): I found one bug that had to be corrected to run the TLS correctly, disabling optimization for function BN_num_bits_word(BN_ULONG l) solved the issue.
> * Issue [misspellings fixes by https://github.com/vlajos/misspell_fixer #3](https://github.com/openssl/openssl/pull/3): I also had to manually edit the makefile each time after the configure, before build, as showed in the attached patch-file “makefile.patch”.
> 
> ### My system and config
> My desktop machine for building the library (dll’s and .pdb-files) is Windows 10 64-bit, with Strawberry Pearl version 5.30.1.1, and NASM version 2.14.02. I use MS Visual Studio 2008 for application code development.
> 
> The following tools was also installed in the Visual Studio 2008 command promt: cpan -i Text::Template cpan -i Test::More
> 
> I use Visual Studio 2008 command prompt for configuring and building openssl. The bat-script I use (configure.bat) for configuring openssl before build, is as follows:
> 
> > set OSVERSION=WCE600
> > set PLATFORM=VC-CE
> > set TARGETCPU=ARMV4I
> > set WCECOMPAT=C:\wcecompat
> > set LIB=C:\Program Files (x86)\Windows CE Tools\wce600\PHY3250_SCANMATIC_AL2\Lib\ARMV4I;C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\lib\ARMV4I;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib;
> > set INCLUDE=C:\Program Files (x86)\Windows CE Tools\wce600\PHY3250_SCANMATIC_AL2\Include\Armv4i;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\include
> > set Path=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\bin\x86_arm;%Path%
> > REM set LIBPATH="C:\Program Files (x86)\Windows CE Tools\wce600\PHY3250_SCANMATIC_AL2\Lib\ARMV4I";C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib;
> > C:\Strawberry\perl\bin\perl Configure no-idea no-mdc2 no-rc5 no-ssl2 no-ssl3 no-weak-ssl-ciphers no-comp no-async no-engine VC-CE
> > REM Now, remember to "git apply makefile.patch" (or modify content of makefile according to makefile.patch manually), then run build.bat.
> 
> To build openssl, I use:
> 
> > nmake build_generated libcrypto-1_1.dll libssl-1_1.dll
> 
> ### Now, to the proposals of code changes for the above mentioned issues:
> Issue #1: In /crypto/dso/dso_win32.c -> method win32_pathbyaddr(….), I got compilation errors on the four instances of (uintptr_t) (not defined). I solved this by replacing (uintptr_t) with (unsigned long). Please also see the first diff-entry in the attached file 1-1-1e.patch.pdf. [1-1-1e.patch.pdf](https://github.com/openssl/openssl/files/4427390/1-1-1e.patch.pdf)
> 
> Issue #2: In /crypto/bn/bn_lib.c, due to a bug for arm when optimization is enabled, I had to turn off optimization in front of function BN_num_bits_word(BN_ULONG l), and then re-enable it after this function, as explained here: https://mta.openssl.org/pipermail/openssl-users/2018-August/008465.html. Or else, I got run time errors with printouts from the opensssl library. For a general implementation, I guess some set of #if defined statements must be used, not to disable optimization for systems that does not has this issue. Please see https://mta.openssl.org/pipermail/openssl-users/2018-August/008465.html for suggestions on that. The second/last diff-entry in the attached file 1-1-1e.patch.pdf shows my solution, which disables optimization for function BN_num_bits_word(BN_ULONG l) in all cases, for simplicity. [1-1-1e.patch.pdf](https://github.com/openssl/openssl/files/4427390/1-1-1e.patch.pdf)
> 
> Issue #3: For Windows CE, we need to modify the makefile each time a new configure has occurred, before build, to set correct path/syntax to required additional library WCECOMPAT among others. The changes required is documented in the following attached patch-listing makefile.patch.pdf: [makefile.patch.pdf](https://github.com/openssl/openssl/files/4427419/makefile.patch.pdf)
> 
> Is it possible to let the configure program automatically set these parameters correctly, given that the first 4 config-lines of configure.bat (above) has been set?
> 
> I hope this can help others to successfully build openSSL for Windows CE, or even better, if the suggestions above can be implemented in future versions of openSSL, to elliminate the need of modifications/fixes for Windows CE users.
> 
> Best Regards Bjørn Liene Gundersen

I would like to ask you in wcecompact build what did u write in "Set Path=" in case of Win CE 6.0  Not 7.0. Thanks in advance

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Kha, 22 Jul 2021, 10:31 PM Tomáš Mráz ***@***.***>
menulis:
