### ISSUE TITLE
Why the values are different

### ISSUE THREAD

**Issue by kous4615** [openssl/openssl#11467]
Hello everyone

why are the values of Server 1 and Server 2 different?
Server 1 and Server 2 have the same certificate.

Because of this difference, server1 does not generate an error when starting from Apache.
However, server2 gives an error.

I'm looking forward to hearing from you.
Hope everything is good.

server 1
[root@test conf]# openssl.org version
OpenSSL 1.0.1e-fips 11 Feb 2013
[root@test conf]# openssl.org rsa -modulus -noout -in server2.key | openssl md5
Enter pass phrase for server2.key:
**(stdin)= bf970d630513b28944f4b9bdb51cf283**
[root@test conf]# openssl.org x509 -modulus -noout -in server2.crt | openssl md5
**(stdin)= bf970d630513b28944f4b9bdb51cf283**

server 2
[root@ucert test]# openssl version
OpenSSL 1.1.1d  10 Sep 2019
[root@ucert test]# openssl rsa -modulus -noout -in a.key | openssl md5
Enter pass phrase for a.key:
**(stdin)= bf970d630513b28944f4b9bdb51cf283**
[root@ucert test]# openssl x509 -modulus -noout -in a.crt
**Modulus=EEE55E39A8D3A76ED27ED4EB0676C566C37F2C30CCEF54AB3A51D3F8E074BA09DC0B26FB8EA9D5C5F5543A1CD59EAB924E46034D6C12454E52332A990754C581258651CF9160424E04FBF57AFEDD2531CECF160340C4A25B563CF7C2324917F41B3199C914EF01B72D9E5BD825862403C785FD0261CC58C6019A7F44C04664A355389598BE46548C7302A7EC17DEB128A4D342C3572DF31A5727EFC5B68B3723B0DBB95312FBAE055DC45D0F810B25C3D82E890EB7A116D4C2E7B752128F08DCF2EABC1F5AF9172A4BABB7A4E0B5DAD67D4873E4D636BA7AC164250A67055738E521D6C76B4A3748A630C67904A35A2259CCE6ACFDB4EDC97C1BCDCE011631DB**

**Comment by richsalz** [comment]
Did you leave off the ```|openssl md5``` on purpose? :)

**Comment by levitte** [comment]
``` console
$ echo 'Modulus=EEE55E39A8D3A76ED27ED4EB0676C566C37F2C30CCEF54AB3A51D3F8E074BA09DC0B26FB8EA9D5C5F5543A1CD59EAB924E46034D6C12454E52332A990754C581258651CF9160424E04FBF57AFEDD2531CECF160340C4A25B563CF7C2324917F41B3199C914EF01B72D9E5BD825862403C785FD0261CC58C6019A7F44C04664A355389598BE46548C7302A7EC17DEB128A4D342C3572DF31A5727EFC5B68B3723B0DBB95312FBAE055DC45D0F810B25C3D82E890EB7A116D4C2E7B752128F08DCF2EABC1F5AF9172A4BABB7A4E0B5DAD67D4873E4D636BA7AC164250A67055738E521D6C76B4A3748A630C67904A35A2259CCE6ACFDB4EDC97C1BCDCE011631DB' | openssl md5
(stdin)= bf970d630513b28944f4b9bdb51cf283
```

Nope, not different
