### ISSUE TITLE
RedHat 8 /lib64/libssh.so.4: symbol EVP_KDF_ctrl version OPENSSL_1_1_1b not defined in file libcrypto.so.1.1

### ISSUE THREAD

**Issue by mazer1310** [openssl/openssl#11471]
For our application, we build OpenSSL from source.  On Linux, we do the following:
./config --prefix=<InstallDir> shared
make
make test
make install

We set up our app to load our SSL version via LD_LIBRARY_PATH.  However, some of our application code has a dependency on /lib64/libssh.so and on RedHat 8, we began receiving the error:
/lib64/libssh.so.4: symbol EVP_KDF_ctrl version OPENSSL_1_1_1b not defined in file libcrypto.so.1.1

Now, this error is NOT seen on an equivalent CentOS system and we found that the system installed openssl is different between the two. 

If I dump the symbols from the RH8 installed OpenSSL crypto library and grep for EVP_KDF:

> $ nm -gD /lib64/libcrypto.so.1.1 | grep EVP_KDF
> 00000000001727e0 T EVP_KDF_ctrl
> 00000000001728d0 T EVP_KDF_ctrl_str
> 0000000000172620 T EVP_KDF_CTX_free
> 0000000000172660 T EVP_KDF_CTX_new_id
> 0000000000172990 T EVP_KDF_derive
> 0000000000172780 T EVP_KDF_reset
> 0000000000172960 T EVP_KDF_size
> 00000000001727b0 T EVP_KDF_vctrl

However, with our own build, EVP_KDF is not found:
> $ nm -gD libcrypto.so.1.1 | grep EVP_KDF

So, the question is:  what configuration settings are necessary to create a libcrypto.so version that exports those functions?  It's not clear from the Configuration script how to enable these features?

**Comment by t8m** [comment]
Red Hat adds EVP_KDF support downstream. You cannot get this function from the regular upstream openssl builds. It is strange that you would not see the same thing on the CentOS 8 as well though.

The only thing I can recommend is not trying to replace the Red Hat openssl build with your own if you link also to other system libraries such as libssh.

**Comment by schnoberts1** [comment]
@mazer1310 , I appreciate this is late but in case anyone else finds this issue and is still in search of a solution, here's one idea. If you're building your own openssl libs that you want to be in the runtime linker path for CentOS/RHEL built ssl enabled tooling then one option is to apply the relevant patches. See https://src.fedoraproject.org/rpms/openssl/tree/f33 (etc) for an example.

**Comment by mazer1310** [comment]
@schnoberts1:
Thanks for your follow up.  It was unfortunate that RedHat decided to customize the OpenSSL builds, but did not change the resulting library names or version numbers.  As a result, the RedHat and Stock OpenSSL libraries are both named "libcrypto.so.1.1" and "libssl.so.1.1", and yet are incompatible with one another.  Since RedHat took it upon themselves to customize OpenSSL, a better approach would have been to customize the library names or version numbers.  For instance, they could have named the libraries "libcrypto-rh.so" and "libssl-rh.so", or modified the version numbers to be libcrypto.so.1.2 and libssl.so.1.2

I did try the approach of applying the relevant patches from src.fedoraproject.org and was able to get it working with openssl-1.1.1-evp-kdf.patch, openssl-1.1.1-krb5-kdf.patch and openssl-1.1.1-ssh-kdf.patch.  However, we decided not to go this route because the other 32 patches would not be applied to our library which could still be loaded by RedHat specific binaries resulting in potentially unexpected behavior for modules outside of our software.  Additionally, we needed this to work on various Linux distributions, not just RedHat 8, and modifying the libraries in this way threatened to run into similar problems on other systems.  Finally, this would have made us dependent on the RedHat patch releases which can lag the official OpenSSL releases by a fair amount of time.

The rpath approach is excellent and would have been a good approach.  However, in the end, we took it upon ourselves to modify our own library names and this ended up sorting out the problems.  We created libcrypto_1_1.so and libssl_1_1.so and relinked the dependent libraries (including 3rdparties) to the new names.  The irony is that it is the RedHat libraries which are customized but use the official names and our libraries which are stock and use the customized names!

If anyone is interested in this approach, edit the OpenSSL Makefile in vi or vim and perform the following substitutions:
:%s/libcrypto$(SHLIB_EXT/libcrypto_1_1$(SHLIB_EXT/g
:%s/libssl$(SHLIB_EXT/libssl_1_1$(SHLIB_EXT/g
:%s/libcrypto\.a/libcrypto_1_1\.a/g
:%s/libssl\.a/libssl_1_1\.a/g
:%s/-lcrypto/-lcrypto_1_1/g
:%s/-lssl/-lssl_1_1/g

There is a test failure with test 90 shlibload which was I unable to sort out, but regardless of the failure the customized libraries work successfully 

Any libraries that need to use these libraries can do so by updating their respective Makefiles to -lcrypto_1_1 and -lssl_1_1

Cheers,
Steve

**Comment by philljj** [comment]
@mazer1310

Thank you, we took this approach and it also resolved our conflict.

We found it was simpler to just rename SHLIB_VERSION_NUMBER in opensslv.h by adding a suffix
    # define SHLIB_VERSION_NUMBER "1.1suffixhere" 
The stock openssl Configure script pulls from this, and automatically configures the openssl Makefile to build ssl/crypto libraries with this naming. Then the rest of our build uses that naming for linking.

**Comment by poempeng** [comment]
We have also encountered this problem and resolved it by statically linking OpenSSL.
