### ISSUE TITLE
'-static' option not working correctly

### ISSUE THREAD

**Issue by demian51** [openssl/openssl#11478]
Hello!

I'm using OpenSSL with static linking in Windows, using Visual Studio 2019. Lately, I updated the library from 1.1.0e to 1.1.1f and the library is not correctly built. When I try to build a library, the script adds `/MD` option although I appended `-static`. In 1.1.0e it set `/MT` option correctly.

I searched and found #11414, but it was not helpful. After some trial and error, I realized that the file `Configure` has the error. In commit aacae7a9(see line 1573) the script was not correctly modified. Originally the option `-static` made **`shared`** disabled, but it turns off **`static`** after the commit.

If I add `no-shared` explicitly, everything works fine. It seems that the script needs a fix.(Or should I make a pull request?)

**Comment by levitte** [comment]
> Originally the option `-static` made **`shared`** disabled, but it turns off **`static`** after the commit.

Not quite.  The first argument to `disable()` is the disable type, i.e. what is assigned to `$disable{something}`, so this line explicitly disabled **pic** and **threads**:

https://github.com/openssl/openssl/blob/e78f2a8f269a4dcf820ca994e2b89b77972d79e1/Configure#L1512

However, because of this line in *@disable_cascades*, **shared** should be automatically disabled as well:

https://github.com/openssl/openssl/blob/e78f2a8f269a4dcf820ca994e2b89b77972d79e1/Configure#L493

So you might want to have a closer look at why **shared** isn't disabled when it should...

**Comment by demian51** [comment]
Oh I missed that point. Then the code is innocent...
I found that `dynamic_engine` is also in disabled features list,

>  dynamic-engine          [cascade]

but in `configdata.pm` the variable `dynamic_engine` still has `"1"`.  I'll try to look into `disable_cascades`.

**Comment by demian51** [comment]
I did bisect and identified that the bug had begun after the commit 00721379.

https://github.com/openssl/openssl/blob/007213795a0e15901cbdc4558ae2a8c21d3ad9bb/Configure#L1562
`shared`, `pic`, and `threads` are disabled here. But some processing about the options is done already. So the tasks aren't applied correctly, I think.
For example, `dynamic-engine` is inserted to the array `disabled` at line 1562, but the variable `dynamic_engine` is already set as `"1"` here.
https://github.com/openssl/openssl/blob/007213795a0e15901cbdc4558ae2a8c21d3ad9bb/Configure#L1325
I'm not sure because I don't know Perl at all, but it seems that the disabling code should appear earlier. Or is there anything that I missed again...?

**Comment by levitte** [comment]
The disabling stuff was reworked to use this function:

https://github.com/openssl/openssl/blob/c61ced5ec50fc68707c7cea79f7df1d170f03f13/Configure#L1064-L1086

The intention is that everytime we disable some feature(s), it runs through `@disable_cascade`.
As for "... but the variable `dynamic_engine` is already set as `"1"` here", I'm not sure I understand the issue.  The value "1" is 'true', so it means that this feature is, indeed, disabled.
