### ISSUE TITLE
Switch from shlib_wrap.sh to wrap.pl broke the external krb5 test

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#11492]
The first build where the external krb5 test was broken is 30a4cda5e0c67b4e77da4f21b7c5f27991d3367a

That is when the PR #11110 was merged.

I assume some environment variables are not set up right when running the krb5 library build and the system and local openssl is mixed up in the tests.

**Comment by t8m** [comment]
Ping @levitte @mspncp

**Comment by kaduk** [comment]
Hmm, my local bisection shows that c3845ceba84aab9ddeb43f043549238fd10de63b is the first bad commit (and that 285e2991af23974761b9497f1e2a3396aa4bc440 is good)

**Comment by kaduk** [comment]
Which seems pretty clear because it's trying to consume `OPENSSL_MODULES` (to set it to an absolute path) as well as set it, but it's not set anymore to be consumed.  Using the buildtop path directly ought to work, testing now...

**Comment by levitte** [comment]
Since wrap.pl sets `OPENSSL_MODULE` (unless already set), I'm not sure I understand the failure. Does it set it incorrectly, or is there some other inter-play I'm missing?

**Comment by kaduk** [comment]
See #11499 -- the krb5 test environment needs `OPENSSL_MODULE` set, but we were only trying to canonicalize the path, not actually setting it, in the test spec.

**Comment by kaduk** [comment]
Belatedly closing since #11499 got merged
