### ISSUE TITLE
how to do config without configure file

### ISSUE THREAD

**Issue by egggHang** [openssl/openssl#11490]
is there a way to do what `openssl_config_int` does without using a configure file?  i want to share configurations between nodes, and configure files seem not easy to manage. 

i noticed the function `CONF_modules_load` , but have not find a proper way to construct a `CONF`, are there any docs about this? or just a better way.  thanks in advance.

**Comment by levitte** [comment]
I fail to understand how copying a configuration file between nodes is difficult, compared to copying programs around...

**Comment by egggHang** [comment]
@levitte  i am trying to pass the configuration (set as a string maybe) using the program's own configure file. it's convenient for nodes in the cluster to get this string by existing API. so maybe there is a way to init openssl with this string? what i can think is to construct a `CONF` and use `CONF_modules_load`.  any advice about this?

**Comment by mattcaswell** [comment]
You could configure from an "in memory" config file.

Create a mem BIO containing the config file "as a string" using `BIO_new_mem_buf()`. See:
https://www.openssl.org/docs/man1.1.1/man3/BIO_new_mem_buf.html

Then use `NCONF_load_bio` to load that string into a CONF structure. Something like this (completely untested):

````
    BIO *mem = BIO_new_mem_buf(myconfstr, strlen(myconfstr));
    CONF *conf = NCONF_new();

    if (mem == NULL || conf == NULL)
        /* error */;
    if (NCONF_load_bio(conf, mem, NULL) <= 0)
        /* error */
    OPENSSL_load_builtin_modules();
    if (CONF_modules_load(conf, NULL, DEFAULT_CONF_MFLAGS) <= 0)
        /* error */

**Comment by egggHang** [comment]
@mattcaswell  this works, thank you so much~

**Comment by levitte** [comment]
Glad we could help.  We seem to be done here, so I'm closing this issue.
