### ISSUE TITLE
add ICC support on Windows [post 1.1.0]

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#1150]
Hi, Everyone,

In short, Intel provide [C, C++ compiler on Windows](https://software.intel.com/en-us/intel-parallel-studio-xe), which has [some advantages](https://software.intel.com/en-us/c-compilers/ipsxe) compared to MSVC. Would be nice, if OpenSSL add support for it.

Since ICC on Windows pretends to be MSVC (compare [ICC](https://software.intel.com/en-us/node/512855) and [MSVC](https://msdn.microsoft.com/en-us/library/9s7c9wdw.aspx) options), required changes are minimal. In file `Configurations/10-main.conf`:
- add separate section `"VC-WIN64A-ICC"`, which is a duplicate of `"VC-WIN64A"` toolchain and behaves the same,
- in section `"VC-WIN64A-ICC"` override variables:

```
cc               => "cl",
```

inherit from `"VC-common"`, with

```
cc               => "icl",
```

and

```
cflags           => ... " /O2";
```

inherit from `"VC-noCE-common"`, with

```
cflags           => ... " /O3";
```

Because of OpenSSL build error using ICC:

```
#31000: corrupt PDB file ossl_static\vc140.pdb; delete and rebuild; if problem persists, delete and try /Z7 instead
```

also needed to replace in file `Configurations/10-main.conf` strings:

```
/Fdossl_static
/Fddso
/Fdapp
```

with

```
/Fdossl_static.pdb
/Fddso.pdb
/Fdapp.pdb
```

It fix this error while has no visible regressions for MSVC builds (tested for **<Debug,Release>+<shared,static>** configurations using MSVC 2015 only).

Regards,
Alexander

**Comment by dot-asm** [comment]
Even though Intel has free access program for Open-source contributors, it covers only Linux version of the compiler in question. For this reason it's unlike that ICC for Windows will make it to officially supported Configurations/10-main.cf. In other words suggestion should not be formulated what needs to be done in 10-main.cf, but how would a separate community-supported config-file would look like, and it should be left to community to figure out ;-)

On side note. Even though referred "some advantages" appear impressive, they are hardly representative in OpenSSL case. Using MSVC-compiled OpenSSL DLLs with ICC-compiled application code (in case "some advantages" apply to application code) are more than likely to get you as far as ICC-compiled DLLs.

**Comment by sav-ix** [comment]
> it covers only Linux version of the compiler in question

Yes and no. IPSXE [Student and Educator](https://software.intel.com/en-us/qualify-for-free-software) versions available for free on Windows.

> For this reason it's unlike that ICC for Windows will make it to officially supported

Could you share information, where it is said, that OpenSSL **should** support only compilers, which has free versions for opensource development?

> Even though referred "some advantages" appear impressive, they are hardly representative in OpenSSL case.

ICC provide about 25% better performance on scalar operations, compared to MSVC. Dunno, whether it representative in OpenSSL case or not; additional testing needed.
The main goal of this issue is allow ICC users to build OpenSSL and their apps with same compiler.

**Comment by dot-asm** [comment]
And could you share information where it says that we should pretend to be students and educators to get free stuff? As for should-be supported compilers or rather platforms. It's in common interest that team members have access to platforms we support.Nor is it inappropriate to split platforms to those that are actually supported by team and community-supported ones. And Configurations directory is already organized to facilitate this.

**Comment by sav-ix** [comment]
Your words
> Even though Intel has free access program for Open-source contributors, it covers only Linux version of the compiler in question. For this reason it's unlike that ICC for Windows will make it to officially supported 

mean that ICC won't be supported on Windows because there is no free version for Opensource development. I just trying to figure out, is it designated in official documents of OpenSSL project?

**Comment by richsalz** [comment]
No it’s not documented, not official, and not a policy.  :)  And he said "unlikely"

What *is* our policy is that we want to only official support platforms/toolkits that we can use regularly.  And right now, ICC in Windows isn't one of them.

**Comment by kaduk** [comment]
This is probably going to depend on the resolution of #5043 but I'll move it to the "post 1.1.1" milestone for now.

**Comment by levitte** [comment]
Well, a separate config could easily be accepted, classified as "community"...

**Comment by kaduk** [comment]
Sure.  But someone from the community would have to step up and provide a patch for that to happen, and we probably don't want to start blocking releases on random community contributions.

**Comment by levitte** [comment]
I'd prefer a separate file.  Top of my head, I could expect `50-windows-icc.conf`, to be placed in `Configurations/`.

BTW, should someone see this and provide a file, I would suggest using the power of inheritance and only provide new values for the attributes that need changing...  so from the description above, this should be the basic form:

```
(
    'VC-WIN64A-ICC' => {
        inherit_from            => [ 'VC-WIN64A' ],
        cc                      => 'icl',
        cflags                  => ...,
        # whatever else that needs changing from the VC-WIN64A attributes
    }
);
```

**Comment by sav-ix** [comment]
Hello, again,

Have to add few more details concerning ICC:
* As known, Intel [offers](https://software.intel.com/en-us/qualify-for-free-software/opensourcecontributor) free ICC license for OSS development for Linux platform only. But in case OpenSSL representatives would be interested to obtain such license for Windows, this can be discussed in appropriate [topic](https://software.intel.com/en-us/forums/intel-c-compiler/topic/639321).
* ICC on Windows imitates MSVC, and ICC on Linux imitates GCC. This simplifies adopting existing toolchains to ICC (e.g., as Qt ICC on Windows toolchain [win32-icc](http://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/win32-icc/qmake.conf?h=5.9) redefines some variables, obtained from MSVC toolchain [msvc-version.conf](http://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/common/msvc-version.conf?h=5.9), ICC on Linux toolchain [linux-icc](http://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/linux-icc/qmake.conf?h=5.9) redefines some variables, obtained from GCC toolchain [unix.conf](http://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/common/unix.conf?h=5.9), etc.).
* Recent ICC [compiler](https://software.intel.com/en-us/cpp-compiler-18.0-developer-guide-and-reference-compiler-option-details) and [linker](https://software.intel.com/en-us/cpp-compiler-18.0-developer-guide-and-reference-linking-or-linker-options) documentation available online.

A compiler-related patch to convert OpenSSL MSVC toolchain 'VC-WIN64A' to ICC on Windows is:
```
diff --git a/Configurations/10-main.conf b/Configurations/10-main.conf
index 046643d..8867fe1 100644
--- a/Configurations/10-main.conf
+++ b/Configurations/10-main.conf
@@ -1249,7 +1249,7 @@ my %targets = (
     "VC-common" => {
         inherit_from     => [ "BASE_Windows" ],
         template         => 1,
-        cc               => "cl",
+        cc               => "icl",
         cflags           => "-W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -D_WINSOCK_DEPRECATED_NO_WARNINGS",
         defines          => add(sub { my @defs = ();
                                       unless ($disabled{"zlib-dynamic"}) {
@@ -1262,9 +1262,9 @@ my %targets = (
                                       return [ @defs ];
                                     }),
         coutflag         => "/Fo",
-        lib_cflags       => add("/Zi /Fdossl_static"),
-        dso_cflags       => "/Zi /Fddso",
-        bin_cflags       => "/Zi /Fdapp",
+        lib_cflags       => add("/Zi /Fdossl_static.pdb"),
+        dso_cflags       => "/Zi /Fddso.pdb",
+        bin_cflags       => "/Zi /Fdapp.pdb",
         lflags           => add("/debug"),
         shared_ldflag    => "/dll",
         shared_target    => "win-shared", # meaningless except it gives Configure a hint
@@ -1284,7 +1284,7 @@ my %targets = (
                                        release =>
                                        sub {
                                            ($disabled{shared} ? "" : "/MD")
-                                               ." /O2";
+                                               ." /O3";
                                        })),
         lib_cflags       => add(sub { $disabled{shared} ? "/MT /Zl" : () }),
         # Following might/should appears controversial, i.e. defining

```
not to mention, that redefinition of `lib_cflags`, `dso_cflags` and `bin_cflags` is due to ICC issue [CMPLRS-42592](https://software.intel.com/en-us/forums/intel-c-compiler/topic/732926), and could be removed in future.

A linker-related patch not required at all, since ICC on Windows linker `xilink` and librarian `xilib` are a wrappers for MSVC `link` and `lib` respectively, so redefine:
```
ld              => "link",
<snip>
ar              => "lib",

```
variables in file `Configurations/00-base-templates.conf` not needed.

I assume the above should be enough for @openssl/committers to provide a separate toolchain for ICC on Windows. Feel free to notify me, when such PR would be available, and I test it and report results.

The only refinement, if it's negotiable,
`ICC-WIN64A`
toolchain name could be preferable, than
`VC-WIN64A-ICC`
in case
`ICC-LINUX`
or similar would be added in future. Although I agree, that
> it should be left to community to figure out

**Comment by levitte** [comment]
Have a look at #5058

**Comment by sav-ix** [comment]
In short, after applying PR #https://github.com/levitte/openssl/commit/5a7d0d8eabf909282d56ce185b3a2da4a01ede03 to OpenSSL-1.1.1-dev (a41a6120cdcb7e883481bc1bed55e7157c9255c4), all builds failed.

For <Debug|Release> Shared builds:
```
(perl Configure --prefix="%CD%\..\ICC64DH" --openssldir="%CD%\..\ICC64DH\ssl" threads no-deprecated shared debug-ICC-WIN64A >_Configure.log && jom /J1 >_nmake.log && nmake install >_install.log && nmake test >_test.log) 2>_stderr.log && copy *.log "%CD%\..\ICC64DH"

AND

(perl Configure --prefix="%CD%\..\ICC64RH" --openssldir="%CD%\..\ICC64RH\ssl" threads no-deprecated shared ICC-WIN64A >_Configure.log && jom /J2 >_nmake.log && nmake install >_install.log && nmake test >_test.log) 2>_stderr.log && copy *.log "%CD%\..\ICC64RH"
```

got error:
```
Microsoft (R) Program Maintenance Utility Version 14.12.25830.2
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\nmake.exe" depend && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\nmake.exe" _all

Microsoft (R) Program Maintenance Utility Version 14.12.25830.2
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.12.25830.2
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST libcrypto.dll.manifest DEL /F /Q libcrypto.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto.dll @C:\Users\test\AppData\Local\Temp\nm55C.tmp || (DEL /Q libcrypto.* libcrypto.* && EXIT 1)
        IF EXIST libcrypto.dll.manifest  mt -nologo -manifest libcrypto.dll.manifest -outputresource:libcrypto.dll
        IF EXIST apps\libcrypto.dll DEL /Q /F apps\libcrypto.dll
        IF EXIST test\libcrypto.dll DEL /Q /F test\libcrypto.dll
        IF EXIST fuzz\libcrypto.dll DEL /Q /F fuzz\libcrypto.dll
        COPY libcrypto.dll apps
        1 file(s) copied.
        COPY libcrypto.dll test
        1 file(s) copied.
        COPY libcrypto.dll fuzz
        1 file(s) copied.
        IF EXIST libssl.dll.manifest DEL /F /Q libssl.dll.manifest
        link /nologo /debug /dll  /implib:libssl.lib /out:libssl.dll @C:\Users\test\AppData\Local\Temp\nm6C5.tmp || (DEL /Q libssl.* libssl.* && EXIT 1)
LINK : fatal error LNK1104: cannot open file 'libcrypto.lib'
Could Not Find c:\libOPENSSL-1.1.1-dev\build\libssl.*
NMAKE : fatal error U1077: 'link' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```

Not reproduced, if used patch from my previous post.

**Comment by sav-ix** [comment]
while for <Debug|Release> **Static** builds:
```
(perl Configure --prefix="%CD%\..\ICC64DT" --openssldir="%CD%\..\ICC64DT\ssl" threads no-deprecated no-shared debug-ICC-WIN64A >_Configure.log && jom /J2 >_nmake.log && nmake install >_install.log && nmake test >_test.log) 2>_stderr.log && copy *.log "%CD%\..\ICC64DT"

AND

(perl Configure --prefix="%CD%\..\ICC64RT" --openssldir="%CD%\..\ICC64RT\ssl" threads no-deprecated no-shared ICC-WIN64A >_Configure.log && jom /J%NUMBER_OF_PROCESSORS% >_nmake.log && nmake install >_install.log && nmake test >_test.log) 2>_stderr.log && copy *.log "%CD%\..\ICC64RT"
```

got error:
```
Copying: ./include/openssl/x509err.h to C:/libOPENSSL-1.1.1-dev/ICC64DT/include/openssl/x509err.h
Copying: ./include/openssl/x509v3.h to C:/libOPENSSL-1.1.1-dev/ICC64DT/include/openssl/x509v3.h
Copying: ./include/openssl/x509v3err.h to C:/libOPENSSL-1.1.1-dev/ICC64DT/include/openssl/x509v3err.h
created directory `C:/libOPENSSL-1.1.1-dev/ICC64DT/lib'
Copying: libcrypto.lib to C:/libOPENSSL-1.1.1-dev/ICC64DT/lib/libcrypto.lib
Copying: libssl.lib to C:/libOPENSSL-1.1.1-dev/ICC64DT/lib/libssl.lib
Copying: ossl_static.pdb to C:/libOPENSSL-1.1.1-dev/ICC64DT/lib/ossl_static.pdb
*** Installing engines
created directory `C:/libOPENSSL-1.1.1-dev/ICC64DT/lib/engines-1_1'
*** Installing runtime files
created directory `C:/libOPENSSL-1.1.1-dev/ICC64DT/bin'
Copying: apps/openssl.exe to C:/libOPENSSL-1.1.1-dev/ICC64DT/bin/openssl.exe
Copying: apps/openssl.pdb to C:/libOPENSSL-1.1.1-dev/ICC64DT/bin/openssl.pdb
Can't Open ./tools/c_rehash.pl at .\util\copy.pl line 62.
NMAKE : fatal error U1077: 'C:\ProgramData\Perl64\bin\perl.exe' : return code '0x2'
Stop.
```
Not reproduced, if used my patch above.

**Comment by dot-asm** [comment]
Principal suggestion was discussed in #5058 in sufficient detail with resolution "won't fix". Well, `perl Configure VC-WIN64A CC=icl` should build(*) and pass tests, and it can be used as users' discretion. Installation issues don't seem to be related to compiler, and should be reported separately.

(*) it was reported to build with minor modification that was applied in #5574.
