### ISSUE TITLE
Dynamic engines seem to be broken

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#11510]
openssl is configured with ./config shared
GOST engine master
```
cmake -DOPENSSL_ROOT_DIR=/home/beldmit/crypto/openssl .
make
bin/test_curves
```
output:
```beldmit@manul$ bin/test_curves 
00:92:4D:4D:13:7F:00:00:error:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:334:id=dynamic
00:92:4D:4D:13:7F:00:00:error:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:334:id=gost
/home/beldmit/crypto/engine/test_curves.c:232: OpenSSL internal error: eng = ENGINE_by_id("gost")
Segmentation fault (core dumped)
```

**Comment by beldmit** [comment]
git bisect points to 22e27978b2

@slontis, could you please take a look?

**Comment by vt-alt** [comment]
I confirm this. Previously it was enough to set `OPENSSL_ENGINES` and then load engine with `ENGINE_by_id("gost")`. After this commit it's required to have`openssl.conf` with fully defined engine.

**Comment by slontis** [comment]
It is pretty bad how everything segfaults when something is missing :)

**Comment by slontis** [comment]
It appears that the tls test is also broken. (But not by this change I think)

**Comment by beldmit** [comment]
> It appears that the tls test is also broken. (But not by this change I think)

Yes. It's a subject of a separate git bisect...

**Comment by vt-alt** [comment]
> It is pretty bad how everything segfaults when something is missing :)

It segfaults due to `OpenSSLDie` calling `abort`.

**Comment by richsalz** [comment]
If you look, there are almost no cases of that in the code. ossl_assert only does it if -DNDEBUG (just like assert), and other then that it's just refcounting.

**Comment by vt-alt** [comment]
Well, segfault of the test is not a problem, since it's a test. We're not particularly need a crash, but it doesn't hurt either, and it was handy to call `OpenSSLDie()`.

**Comment by vt-alt** [comment]
>> It appears that the tls test is also broken. (But not by this change I think)
>Yes. It's a subject of a separate git bisect...

JFYI. I just bisected it to
~~~
openssl% git bisect bad
2972af109e10c5ce30e548190e3eee28327d6043 is the first bad commit
commit 2972af109e10c5ce30e548190e3eee28327d6043
Author: Richard Levitte <levitte@openssl.org>
Date:   Sun Oct 27 15:28:29 2019 +0100

    PROV: Add RSA functionality for key generation

    This includes added support in legacy controls

    Reviewed-by: Shane Lontis <shane.lontis@oracle.com>
    (Merged from https://github.com/openssl/openssl/pull/10289)
~~~
