### ISSUE TITLE
Get md from HMAC_CTX

### ISSUE THREAD

**Issue by huangqinjin** [openssl/openssl#1152]
Would you mind a new opaque api `const EVP_MD *HMAC_CTX_md(const HMAC_CTX *ctx)` for openssl-1.1?

BTW, the source ctx of `HMAC_CTX_copy` can be `const`.

**Comment by mattcaswell** [comment]
Possibly. Why do you need this?

**Comment by huangqinjin** [comment]
Yes, I want to copy a given HMAC_CTX, just the algorithm not the states.

**Comment by mattcaswell** [comment]
Added in commit a621181. Closing.
