### ISSUE TITLE
OpenSSLBitcode returning 404 error from CocoaPods

### ISSUE THREAD

**Issue by sdm-gh** [openssl/openssl#11521]
Hi,

I’m trying to use the “OpenSSLBitcode” framework from Cocoapods, 
I’ve been using OpenSSL-Universal for a while, but I now require Bitcode support for may app.
When I run “pod install” I get a "404 Not Found” error back as follows:

```
  $ pod install
  Analyzing dependencies
  Downloading dependencies
  Installing OpenSSLBitcode (1.0.217)

  [!] Error installing OpenSSLBitcode
  [!] /opt/local/bin/curl -f -L -o /var/folders/2z/lt84ktj14c107snw07w_6jz80000gn/T/d20200410-10182-rzp56r/file.tgz https://openssl.org/source/openssl-1.0.2q.tar.gz --create-dirs --netrc-optional --retry 2

    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   338  100   338    0     0    338      0  0:00:01 --:--:--  0:00:01  1522
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (22) The requested URL returned error: 404 Not Found
```
My Podfile contains the following fragment:

```
  target ‘MyTargetApp' do
    pod 'OpenSSLBitcode'
  end

```
Am I doing something wrong, or is this a problem at your end?

Thanks in advance.

**Comment by mspncp** [comment]
All you need to do is to change the download URL: The URL of OpenSSL release tarballs changes when they are superseded by newer versions(*): they are moved into the `old/x.y.z` folder. So instead of 

    https://openssl.org/source/openssl-1.0.2q.tar.gz

the correct URL is

    https://www.openssl.org/source/old/1.0.2/openssl-1.0.2q.tar.gz

Note however, that OpenSSL 1.0.2 has reached end of life by the end of 2019 and that the last official release is more current than the one you are using:

    https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz

_(*) Side note to @openssl/otc: the fact that the download URL changes over time is a frequent source of confusion and a little bit annoying IMHO_.

**Comment by mattcaswell** [comment]
> All you need to do is to change the download URL

Many scripts want a static unchanging URL

> the correct URL is

I think there is supposed to be a rewrite rule so that you don't have to specify the "old/1.0.2" bit. Looks like it is broken.

@levitte

**Comment by mattcaswell** [comment]
Looks like there is a bug here:

https://github.com/openssl/web/blob/37de7802c8761a93ce77322f3e840240d458a5bc/bin/mk-latest#L12

We need to fix the script.

In the meantime I've forced things through anyway so the above URL should be working again.

**Comment by mattcaswell** [comment]
Fix for the script in https://github.com/openssl/web/pull/170

**Comment by mspncp** [comment]
> the above URL should be working again.

confirmed.

**Comment by mariogruizdiaz** [comment]
Where is the URL defined?
