### ISSUE TITLE
Build Failed (OS X 10.15.4 using ruby-build 20200401)

### ISSUE THREAD

**Issue by j-ladd** [openssl/openssl#11522]
I am a newbie to everything (this could get lengthy)!  I am 'self-teaching' myself Ruby and the errors I've made are not legendary, but they border on legion.  

Sad history: started this project some years ago with version 1.8.7.  On restart upgraded to 2.7.0 (ruby --version got 2.7.0) then used Peter Cooper's 2nd ed Beginning Ruby for my training guide.  So mucking about I found two editors to play with: TextMate, Atom, iTerm2 and registered on GitHub (another thing about which I am trying to learn).  In the process of 'tweaking' the editors and terminal (suggestions from users posted to the internet, I think I have hosed my environment.  Because... after tweaking one of the above my Ruby version changed to 2.6.3p2 (?!).  That bit led to me, eventually, to choose rbenv --about which I know nothing--to upgrade to 2.7.0 as outlined at https://programmingzen.com/installing-rbenv-on-zsh-on-macos/.  Following those instructions I tried to install 2.7.0 which failed with the message shown in the title.  Attached are, approximately, the last two, three pages of the console log
[GitHubProblelm?.pdf](https://github.com/openssl/openssl/files/4465144/GitHubProblelm.pdf)
. 

I presume the problem is my lack of knowledge and could use some guidance.  I scanned the 4 similar issues and none of them is similar to my issue.  Thanks

**Comment by t8m** [comment]
I do not see anything OpenSSL related here. This question should be asked on Ruby.
