### ISSUE TITLE
TLS 1.3 stateles resumption ends with an "unsupported protocol" error.

### ISSUE THREAD

**Issue by mkaniewski** [openssl/openssl#11547]
Hi,

OpenSSL version: 1.1.1e.

I have a server which implements the TLS 1.3 session resumption using stateful tickets (as described in `SSL_CTX_set_options(3)`). Every time when a client sends a PSK ticket the OpenSSL library calls a function registered using `SSL_CTX_sess_set_get_cb(3)`. This function returns a valid `SSL_SESSION` object however right after that an error appears:
```
SSL error:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:ssl/statem/statem_srvr.c:1686
```
It is caused by things that happens earlier in `tls_early_post_process_client_hello`. The backtrace is as follow:
```
-> tls_early_post_process_client_hello
  -> ssl_choose_server_version
    -> ssl_version_supported
      -> is_tls13_capable
```
The `is_tls13_capable` function checks couple of conditions (eg. if the certificate is set). In my case none of the conditions is fulfilled and the function returns false. In a result the OpenSSL library doesn't recognize the TLS 1.3 protocol as a supported on the server and the resumption attempt fails.

If the explanation above makes sense then the solution would be to additionally check in `is_tls13_capable` if the `get_session_callback` is set:
```diff
@@ -1540,7 +1540,8 @@ static int is_tls13_capable(const SSL *s)
         return 1;
 #endif
 
-    if (s->psk_find_session_cb != NULL || s->cert->cert_cb != NULL)
+    if (s->psk_find_session_cb != NULL || s->cert->cert_cb != NULL ||
+        s->session_ctx->get_session_cb != NULL)
         return 1;
 
     for (i = 0; i < SSL_PKEY_NUM; i++) {
```

This fix works for me. I can make a PR if you could confirm that this is a correct solution.

**Comment by mattcaswell** [comment]
> Every time when a client sends a PSK ticket the OpenSSL library calls a function registered using SSL_CTX_sess_set_get_cb(3). This function returns a valid SSL_SESSION object however right after that an error appears:

Hmm. Are you sure about this ordering? TLS protocol negotiation occurs *before* session resumption is attempted. So you should see this error happening before any attempt is made to call the callback.

During protocol negotiation if we are attempting to negotiate TLSv1.3 the server does some checks to ensure that it is actually capable of performing TLSv1.3. In order for it to pass the checks in `is_tls13_capable` it must either:

1) Have been configured to use external PSKs,

2) Have a certificate callback in place, or

3) Have a certificate already configured that is suitable for use in TLSv1.3

Resumption is intended to occur sometime after a "full" handshake. In order for a full handshake to occur you must have a certificate available (either through (2) or (3)) above. Do you have such a certificate? If not, it seems correct that the server is failing.

It sounds a little bit like you are attempting to do external PSKs via the session callback mechanism - which is not its intended use at all. If that it what you are trying to do then you should use the PSK APIs intended for that purpose.

**Comment by mkaniewski** [comment]
> Hmm. Are you sure about this ordering? TLS protocol negotiation occurs before session resumption is attempted. So you should see this error happening before any attempt is made to call the callback.

You are right, the error message appears **before** the callback is called. Sorry for the confusion.

> Resumption is intended to occur sometime after a "full" handshake. In order for a full handshake to occur you must have a certificate available (either through (2) or (3)) above. Do you have such a certificate? If not, it seems correct that the server is failing.

In case of a "full" handshake I have a certificate set in the SSL object and therefore `is_tls13_capable` returns true. So the "full" handshake works properly. The problem I observe happens in case of a "resumed" handshake.

Let me describe the whole scenario step by step:

1. The client starts a "full" TLS 1.3 handshake (the client supports only TLS 1.3).
2. The server sees that this is a new session (not resumed) and therefore set a certificate for the `SSL` object (this kind of decisions are made in callback set by `SSL_CTX_set_client_hello_cb(3)`).
3. `is_tls13_capable` is called and returns true because the certificate is configured.
4. "full" handshake finishes successfully.
5. The server sends to the client a PSK ticket with a session ID inside (a "stateful ticket"). It also saves the `SSL_SESSION` object related to this ticket.
6. The client tries to establish a second session, but this time a "resumed" one. Therefore it sends a ClientHello with the session ID encapsulated in the `pre_shared_key` extension.
7. The server sees that this is a resumed session and therefore doesn't set a certificate for the `SSL` object. It expects that the `get_session_cb` will be called later and the `SSL_SESSION` object will be used to resume the session.
8. `is_tls13_capable` is called and returns false because no certificate is configured.
9. The handshake fails because the server thinks that it can't support TLS 1.3 protocol and the client doesn't support any other TLS version. In result I can see the "unsupported protocol" error.

> During protocol negotiation if we are attempting to negotiate TLSv1.3 the server does some checks to ensure that it is actually capable of performing TLSv1.3. In order for it to pass the checks in is_tls13_capable it must either:
>
> 1. Have been configured to use external PSKs,
> 2. Have a certificate callback in place, or
> 3. Have a certificate already configured that is suitable for use in TLSv1.3

If the session is resumed (using "stateful" tickets) then any of the above check doesn't return true. My idea is to add another check:
```
4. Session id resumption callback is configured.
```

**Comment by mattcaswell** [comment]
I'm not convinced that this is entirely correct - and your situation seems quite unusual. I'd suggest that as a workaround for your problem you simply set a PSK callback that doesn't do anything. This will cause the check to pass.

**Comment by kaduk** [comment]
I would suggest that the server not assume that because there's a PSK indication in the ClientHello the PSK resumption will succeed, and always configure a certificate...

**Comment by mkaniewski** [comment]
Thanks for the suggestions. I decided to always configure a server certificate.
