### ISSUE TITLE
"no-ui-console" configuration option is not documented in the INSTALL file

### ISSUE THREAD

**Issue by smuehlst** [openssl/openssl#11551]
I noticed this with OpenSSL 1.1.1f. In the CHANGES file it says:

     To disable, configure with 'no-ui-console'.  'no-ui' is still
     possible to use as an alias.  Check at compile time with the
     macro OPENSSL_NO_UI_CONSOLE.  The macro OPENSSL_NO_UI is still
     possible to check and is an alias for OPENSSL_NO_UI_CONSOLE.

This sounds to me that `no-ui-console` configuration option should be used going forward and that `no-ui` is only available for backward compatibility. But only `no-ui` is documented in the INSTALL file.

**Comment by levitte** [comment]
Fix in #11553
