### ISSUE TITLE
Openssl s_time error CAfile option not found

### ISSUE THREAD

**Issue by prchander** [openssl/openssl#11552]
Hello, I have a client and server setup on two vm's and I am trying to record the RTT speed with s_time but I get an error that states option unknown option -CAfile. My CA file is called pycacert.pem. 
pi@pi:~/openssl$ apps/openssl s_time -cipher RSA -connect 0.0.0.0:44330 -CAfile pycacert.pem
s_time: Option unknown option -CAfile
s_time: Use -help for summary.

**Comment by mattcaswell** [comment]
Confusingly, unlike every other app, the option in s_time is called "cafile" (i.e. with a lowercase "ca"). This was fixed recently in the master branch via 65718c51, so will be in OpenSSL 3.0 - but this wasn't backported to 1.1.1.

**Comment by t8m** [comment]
I think cherry-picking that fix from the master (not the whole commit) would be a good idea. I'll prepare a PR.
