### ISSUE TITLE
Issues when building openssl 1.1.1f for WinCE/VS2008

### ISSUE THREAD

**Issue by bjorn-lg** [openssl/openssl#11563]
I am successfully building openssl 1.1.1e for Windows CE 6.0 and Visual Studio 2008 (hereafter abbr. WinCE/VS2008). The code changes required in openssl 1.1.1e is explained in my github post: https://github.com/openssl/openssl/issues/11466. Moreover, I used windows ce compatibility library "wcecompat", as explained in this post: https://qiita.com/souju/items/94117c024862f57459c3

However, I now tried to do the same steps for building openssl 1.1.1f, but got build errors, so I suspect the new version has a new code bug with respect to compatibilty for windows CE targets ( #if defined(_WIN32_WCE) && defined(_ARM_)). My procedure for building version 1.1.1f is the same as described for 1.1.1e above. However, I got the following build error when trying to compile:

`        cl  /Zi /Fdossl_static.pdb /GF /Gy  /MD /W3 /wd4090 /nologo /O1i -D_MSC_VER=1300 /I "." /I "include" -D_WIN32_WCE=600 -DUNDER_CE=600 -DWCE_PLATFORM_VC-CE -DARM -D_ARM_ -DARMV4I -QRarch4T -QRinterwork-return -D"L_ENDIAN" -D"NO_CHMOD" -D"OPENSSL_SMALL_FOOTPRINT" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -D"ENGINESDIR=\"C:\\Program Files\\OpenSSL\\lib\\engines-1_1\"" -D_WIN32_WCE=600 -DUNDER_CE=600 -DWCE_PLATFORM_VC-CE -DARM -D_ARM_ -DARMV4I -QRarch4T -QRinterwork-return -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG" -IC:\wcecompat/include  /Zs /showIncludes "crypto\x509v3\v3err.c" 2>&1 > crypto\x509v3\v3err.d
        "C:\Strawberry\perl\bin\perl.exe" "util\mkdef.pl" crypto 32 > libcrypto.def
        IF EXIST .manifest DEL /F /Q .manifest
        IF EXIST libcrypto-1_1.dll DEL /F /Q libcrypto-1_1.dll
        link /nologo /debug /nologo /opt:ref /dll /subsystem:windowsce,6.00 /machine:THUMB /nologo /debug /nologo /opt:ref  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto.def @C:\Users\bjornl\AppData\Local\Temp\nmDEC1.tmp || (DEL /Q libcrypto-1_1.* libcrypto.lib && EXIT 1)
crypto\dllmain.obj : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'THUMB'
Could Not Find c:\openssl\libcrypto-1_1.*
NMAKE : fatal error U1077: 'link' : return code '0x1'
Stop.`

Any idea what can be modified in the code to compile 1.1.1f with success for Windows CE on ARM? I have attached the [perl configdata.pm dump.txt](https://github.com/openssl/openssl/files/4493161/perl.configdata.pm.dump.txt)

**Comment by kaduk** [comment]
`fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'THUMB'` suggests that the build environment has mixed objects in it.  Are you starting from a clean tree?

**Comment by bjorn-lg** [comment]
> `fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'THUMB'` suggests that the build environment has mixed objects in it. Are you starting from a clean tree?

Thanks for your suggestion. I tried to build again, with the modifications for compatibilitet with windows ce already mentioned in this post, however this time starting with a clean clone and checkout to branch 1.1.1g of OpenSSL. This time the built went ok, og is running ok.
