### ISSUE TITLE
1.1.1c TLS1.3 not work no cipher match

### ISSUE THREAD

**Issue by i553041** [openssl/openssl#11564]
I use Raspberry 3B+ as my web server,installed ubuntu server 19.10 eoan (32bit armhf),

my nginx use this ppa version (1.17.8),
https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline

my openssl is version 1.1.1c,use apt-get install

I want my site only run on TLSv1.3,so in my config file,I set it as :

```
ssl_protocols TLSv1.3;

ssl_ciphers TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384;
```
but when I use nginx -t command test config file,it prompt me an error:
```
nginx: [emerg] SSL_CTX_set_cipher_list("TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384") failed (SSL: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match)
```
if I use TLSv1.2 TLSv1.3:

```
ssl_protocols TLSv1.2 TLSv1.3;

ssl_ciphers TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE+AES128:RSA+AES128:ECDHE+AES256:RSA+AES256:ECDHE+3DES:RSA+3DES;
```
then use nginx -t command check again,it didn't prompt me any error:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
===========================================================

That's what I did to test,

A.)when I try these commands to check two TLS 1.3 ciphers,it show me those error:
```
openssl ciphers -v TLS-AES-256-GCM-SHA384

Error in cipher list
1992302608:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2549:
```
```
openssl ciphers -v TLS-CHACHA20-POLY1305-SHA256

Error in cipher list
1992876048:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2549:
```
B.)If I try another cipher,no error show:
```
openssl ciphers -v ECDHE-ECDSA-CHACHA20-POLY1305

TLS_AES_256_GCM_SHA384 TLSv1.3 Kx=any Au=any Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any Au=any Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256 TLSv1.3 Kx=any Au=any Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH Au=ECDSA Enc=CHACHA20/POLY1305(256) Mac=AEAD
```
C.)use this command, openssl show it support tls1.3

```
root@ubuntu:/etc/nginx/sites-available# openssl ciphers -v
TLS_AES_256_GCM_SHA384 TLSv1.3 Kx=any Au=any Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any Au=any Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256 TLSv1.3 Kx=any Au=any Enc=AESGCM(128) Mac=AEAD
```
D.)remove nginx & openSSL and reinstall it again again and again, many many times, it doesn't work,still show "no cipher match" error

what's wrong with my nginx & openssl？please help.

say thank you first.

**Comment by t8m** [comment]
This is a RFE request for nginx. The TLS-1.3 ciphersuites cannot be configured by SSL_CTX_set_cipher_list() function call. They have a separate SSL_CTX_set_ciphersuites() call.

Also there is no need to set the ciphersuites if you do not mind that the default contains also TLS_AES_128_GCM_SHA256 in addition to what you tried to specify above.

**Comment by t8m** [comment]
To clarify ssl_protocols TLSv1.3; should be sufficient to run only TLSv1.3 with the 3 default TLS1.3 ciphersuites.

**Comment by i553041** [comment]
> To clarify ssl_protocols TLSv1.3; should be sufficient to run only TLSv1.3 with the 3 default TLS1.3 ciphersuites.

Thanks for reply,if I only use ssl_protocols TLSv1.3; and don't set any ciphers,(use # ssI_ciphers ) I can restart nginx without any error.

but when I go to SSL Lab to test my TLSv1.3 is running or not,it show this error:
```
Assessment failed: Internal Error

Known Problems

There are some errors that we cannot fix properly in the current version. They will be addressed in the next generation version, which is currently being developed.

No secure protocols supported - if you get this message, but you know that the site supports SSL, wait until the cache expires on its own, then try again, making sure the hostname you enter uses the "www" prefix (e.g., "www.ssllabs.com", not just "ssllabs.com").
no more data allowed for version 1 certificate - the certificate is invalid; it is declared as version 1, but uses extensions, which were introduced in version 3. Browsers might ignore this problem, but our parser is strict and refuses to proceed. We'll try to find a different parser to avoid this problem.
Failed to obtain certificate and Internal Error - errors of this type will often be reported for servers that use connection rate limits or block connections in response to unusual traffic. Problems of this type are very difficult to diagnose. If you have access to the server being tested, before reporting a problem to us, please check that there is no rate limiting or IDS in place.
NetScaler issues - some NetScaler versions appear to reject SSL handshakes that do not include certain suites or handshakes that use a few suites. If the test is failing and there is a NetScaler load balancer in place, that's most likely the reason.
Unexpected failure - our tests are designed to fail when unusual results are observed. This usually happens when there are multiple TLS servers behind the same IP address. In such cases we can't provide accurate results, which is why we fail.
Common Error Messages

Connect timed out - server did not respond to our connection request, sometimes before we are dynamically blocked when our tests are detected
No route to host - unable to reach the server
Unable to connect to server - failed to connect to the server, it usually happens due to firewall restrictions
Connection reset - we got disconnected from the server
Unrecognized SSL message, plaintext connection? - the server responded with plain-text HTTP on HTTPS port
Received fatal alert: handshake_failure - this is either a faulty SSL server or some other server listening on port 443; if the SSL version of the web site works in your browser, please report this issue to us
Failed to communicate with the secure server - No secure protocol supported. Possibly this server only supports a draft version of TLS 1.3
```

It's my server's problem or SSL Labs problem？

if I use 
```
openssl s_client -connect 10.10.10.3:443
```

It show this information：

```
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

that's mean my site already running TLS1.3？

And the last question,if I really mind TLS_AES_128_GCM_SHA256,I only want to use this two ciphers

TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384

how can I do？

Thanks for ur help.

**Comment by t8m** [comment]
> It's my server's problem or SSL Labs problem？

Most probably this is some SSL Labs problem - perhaps they do not support TLSv1.3 only servers?

> ```
> New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
> Server public key is 256 bit
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> Early data was not sent
> Verify return code: 0 (ok)
> ```
> 
> that's mean my site already running TLS1.3？

Yes.
 
> And the last question,if I really mind TLS_AES_128_GCM_SHA256,I only want to use this two ciphers
> 
> TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384
> 
> how can I do？

Please ask on nginx support forums. This is not the right place to get answers for nginx configuration questions. But as I said above, this feature is most probably missing in the current nginx. At least I cannot find anything relevant on the nginx website.

**Comment by Pushergene** [comment]
Please fix it, I also would like to use ChaCha20 with TLSv1.3.

**Comment by richsalz** [comment]
There is nothing for OpenSSL to fix.  TLS 1.3 with the chacha/poly ciphers works.  There seems to be some configuration issue in other packages.

**Comment by Pushergene** [comment]
So its more problem with Certbot?
