### ISSUE TITLE
Aes 256 implementation

### ISSUE THREAD

**Issue by linuskoli** [openssl/openssl#11569]
I have a code that uses this library for AES128 and I wish to change it to AES256. If I just change the key size to 32bytes and change the number of bits passed in " int AES_set_encrypt_key(const unsigned char *userKey, const int bits, AES_KEY *key)) " function. Will it work?

**Comment by mattcaswell** [comment]
Yes - that should be fine - although note that we discourage the use of the low level AES_* functions (they will be deprecated in OpenSSL 3.0). Instead you should rewrite your code to use the EVP APIs.
