### ISSUE TITLE
openssl RTT test tools 

### ISSUE THREAD

**Issue by prchander** [openssl/openssl#11561]
Hello, I am working on a project and I have 2 VM's one that is a server and one that is a client. I need to calculate RTT/handshake time of a connection and I am looking for different tools that will allow me to take the timings. I have tried the s_time function but I was just wondering if there were more helpful tools and other similar measurements. 
Thank you for your help.

**Comment by t8m** [comment]
Unfortunately apparently nobody knows. This is only remotely related question to OpenSSL so closing this.
