### ISSUE TITLE
compile problem in current trunk

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1157]
Hi guys,

in the current trunk version I get a compile error in pkcs7.h file saying:
```
openssl/pkcs7.h:38:5: error: expected ')' before numeric constant
     X509_NAME *issuer;
     ^
```

This happens with gcc and also with VS.

**Comment by levitte** [comment]
Is that with a program of your own, or is it when building OpenSSL?  If the former, would you mind providing test source?

The reason I asked is that I just tried the following short program, and it compiles without failure on my system (Linux):

``` C
#include <openssl/pkcs7.h>

int main()
{
    return 0;
}
```

**Comment by mattcaswell** [comment]
@wolftobias is this still an issue for you?

**Comment by wolftobias** [comment]
Please give me some more time. I'm currently not in the office.

**Comment by mattcaswell** [comment]
Ping @wolftobias ... can this be closed?

**Comment by mattcaswell** [comment]
No movement on this. Closing assuming fixed. Please open a new issue if not.

**Comment by wolftobias** [comment]
I compile under windows with gnu compiler and still get this error. It seems that this symbol is not defined OPENSSL_SYS_WIN32. Do I have to define that by myself or is there some other mechanism which does this?

**Comment by richsalz** [comment]
Try adding ```–DOPENSSL_SYS_WIN32``` to the configure line and see if that works.  Normally the flag is set only when using VC.

**Comment by mattcaswell** [comment]
You mean you use mingw/msys? Please provide your Configure line.

**Comment by wolftobias** [comment]
Yes I`m using mingw and as IDE eclipse. 

```
g++ -DOPENSSL_SYS_WIN32 "-IC:\\Daten\\_projects\\sourcecode\\branches\\NewOpenSSL_1_1\\src\\main\\include" -O0 -g3 -Wall -c -fmessage-length=0 -o "src\\main\\cpp\\openssl_ssl_ctx.o" "..\\src\\main\\cpp\\openssl_ssl_ctx.cpp" 
```

**Comment by wolftobias** [comment]
But even when I define that symbol I get the error above. It seems to me it includes the windows one somewhere else before.

```
In file included from C:/TDM-GCC-64/x86_64-w64-mingw32/include/windows.h:95:0,
                 from C:\Daten\_projects\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl/crypto.h:393,
                 from C:\Daten\_projects\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl/bio.h:20,
                 from C:\Daten\_projects\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl/asn1.h:16,
                 from C:\Daten\_projects\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl/pkcs7.h:13,
                 from C:\Daten\_projects\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl_pkcs7.h:6,
                 from ..\src\main\cpp\openssl_pkcs7.cpp:1:
C:\Daten\_projects\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl/pkcs7.h:38:5: error: expected ')' before numeric constant
     X509_NAME *issuer;
     ^
```

**Comment by mattcaswell** [comment]
Please provide the arguments you give to "Configure"!

**Comment by wolftobias** [comment]
I compile the openssl library as you can see below:
```
./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=$root_bin_dir/bin/$lib_dir_name/win64 enable-ssl-trace enable-crypto-mdebug no-deprecated
```

**Comment by mattcaswell** [comment]
Ahhhh....so you are cross-compiling this - what host platform are you on?

**Comment by wolftobias** [comment]
Yes you`re right. I`m using a machine to compile for win64/32 and linux 64/32. The os is centos 2.6.32-642.el6.x86_64.

**Comment by wolftobias** [comment]
I just compiled with VS2015 / Win7 64bit and I got the same error.

**Comment by wolftobias** [comment]
I`ve a header where I include #include <openssl/opensslconf.h>, is this ok? Are there other "global" headers need to included?

**Comment by mattcaswell** [comment]
Should be fine...can you supply simple test code that replicates the problem?

**Comment by wolftobias** [comment]
My thought is that it always goes into wincrypt.h to resolve X509_NAME.

**Comment by mattcaswell** [comment]
Try this at the top of your source file before any other includes:
````
#include <openssl\e_os2.h>
#undef X509_NAME
````

**Comment by mattcaswell** [comment]
Obviously that should be `openssl/e_os2.h` !!

**Comment by wolftobias** [comment]
When I do this in  pkcs7.h then I can successfully compile.
```
#	undef X509_NAME
	typedef struct X509_name_st X509_NAME;
```

**Comment by wolftobias** [comment]
Sorry didn`t saw your comment before my last post. I´ll try this asap.

**Comment by wolftobias** [comment]
With your suggestion it work also fine.

```
# include <openssl/e_os2.h>
#undef X509_NAME
```

**Comment by mattcaswell** [comment]
Looks like this issue has been seen before, but the fix was only partial. See the top of x509v3.h.

**Comment by mattcaswell** [comment]
And in x509.h and ts.h!!

**Comment by mattcaswell** [comment]
What I don't understand is that pkcs7.h includes ossl_typ.h, which already has this in it:
````
# ifdef OPENSSL_SYS_WIN32
#  undef X509_NAME
#  undef X509_EXTENSIONS
#  undef PKCS7_ISSUER_AND_SERIAL
#  undef OCSP_REQUEST
#  undef OCSP_RESPONSE
# endif
````

**Comment by mattcaswell** [comment]
So rewinding the conversation a bit you said:

>It seems that this symbol is not defined OPENSSL_SYS_WIN32.

So if you were to have this symbol then presumably you would not get this problem because of the above code in ossl_typ.h. So why do you not have OPENSSL_SYS_WIN32. This should get defined in e_os2.h:

````
# if defined(OPENSSL_SYS_UEFI)
#  undef OPENSSL_SYS_UNIX
# elif defined(OPENSSL_SYS_UWIN)
#  undef OPENSSL_SYS_UNIX
#  define OPENSSL_SYS_WIN32_UWIN
# else
#  if defined(__CYGWIN__) || defined(OPENSSL_SYS_CYGWIN)
#   undef OPENSSL_SYS_UNIX
#   define OPENSSL_SYS_WIN32_CYGWIN
#  else
#   if defined(_WIN32) || defined(OPENSSL_SYS_WIN32)
#    undef OPENSSL_SYS_UNIX
#    if !defined(OPENSSL_SYS_WIN32)
#     define OPENSSL_SYS_WIN32
#    endif
````
So, assuming you haven't done something crazy like define OPENSSL_SYS_UEFI or OPENSSL_SYS_UWIN yourself, and also assuming you are not trying to do this under cygwin (I assume there is no chance you are picking up the cygwin compiler?), then as long as you have _WIN32 defined you should get OPENSSL_SYS_WIN32. _WIN32 should be automatically defined under windows.

Can you include e_os2.h at the top of your file and then include something like this after it:
````
#ifdef __CYGWIN__
# error Running under cygwin!
#endif
#ifndef _WIN32
# error expecting _WIN32 to be defined!
#endif
#ifndef OPENSSL_SYS_WIN32
# error Not detected win32!
#endif
````
Let me know what errors you get (if any).

**Comment by wolftobias** [comment]
The comment about defining the symbol OPENSSL_SYS_WIN32 was misleading. I tried around a lot and gave a wrong statement about this. Sorry! Finally I would say defining that symbol would`nt change anything. What made the difference and a working compile was ```#undef X509_NAME```. With this undef in pkcs7.h I`m able to compile successfully.

**Comment by wolftobias** [comment]
I tried what you said and I didn`t got any output, means the symbols you mentioned are defined. But I got still the compile message regarding X509_NAME. My idea is that somehow or somewhere the windows.h file get included again, but don`t know where or how. Will continue searching.

**Comment by mattcaswell** [comment]
Well normally if you include a header twice, the second include has no effect. At least that's what the openssl headers do, and I think that is common practice.

**Comment by wolftobias** [comment]
I was setting the option in VS to verbose the includes and I saw that after including pkcs7.h and e_os2.h etc. the windows.h file was included. That`s the reason I was asking.

**Comment by mattcaswell** [comment]
It would be interesting to know whether the following block in ossl_type.h actually gets entered or not:
````
# ifdef OPENSSL_SYS_WIN32
#  undef X509_NAME
#  undef X509_EXTENSIONS
#  undef PKCS7_ISSUER_AND_SERIAL
#  undef OCSP_REQUEST
#  undef OCSP_RESPONSE
# endif
````
i.e. Do we enter the block and undef X509_NAME, only to then redefine it again later? Or alternatively do we not enter the block at all. If you add a "#error" line inside the block in ossl_typ.h we would find out. If you see an error, then we know that X509_NAME does get undefined and redefined later. If you don't then we know that, for some reason, OPENSSL_SYS_WIN32 is not yet defined at that point, i.e.
````
# ifdef OPENSSL_SYS_WIN32
# error This should cause an error
#  undef X509_NAME
#  undef X509_EXTENSIONS
#  undef PKCS7_ISSUER_AND_SERIAL
#  undef OCSP_REQUEST
#  undef OCSP_RESPONSE
# endif
````

**Comment by wolftobias** [comment]
Yes I see the error, as mentioned before the symbol is being used.

**Comment by wolftobias** [comment]
I`m not sure if the including and reading of header files are that easy! Anyway use a protection for multiple including of the same headers.

```
#ifndef HEADER_PKCS7_H
# define HEADER_PKCS7_H
```

But as reference you can see that the windows.h file is included after the openssl stuff.
```
1>  openssl_pkcs7.cpp
1>  Hinweis: Einlesen der Datei: C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl_pkcs7.h
1>  Hinweis: Einlesen der Datei:  C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl_global.h
1>  Hinweis: Einlesen der Datei:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt.h
1>  Hinweis: Einlesen der Datei:     C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h
1>  Hinweis: Einlesen der Datei:      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sal.h
1>  Hinweis: Einlesen der Datei:       C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ConcurrencySal.h
1>  Hinweis: Einlesen der Datei:      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vadefs.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_wstdio.h
1>  Hinweis: Einlesen der Datei:     C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_stdio_config.h
1>  Hinweis: Einlesen der Datei:   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h
1>  Hinweis: Einlesen der Datei:   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdarg.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h
1>  Hinweis: Einlesen der Datei:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdlib.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_malloc.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_search.h
1>  Hinweis: Einlesen der Datei:     C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stddef.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_wstdlib.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits.h
1>  Hinweis: Einlesen der Datei:     C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h
1>  Hinweis: Einlesen der Datei:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\string.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_memory.h
1>  Hinweis: Einlesen der Datei:     C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_memcpy_s.h
1>  Hinweis: Einlesen der Datei:      C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\errno.h
1>  Hinweis: Einlesen der Datei:      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime_string.h
1>  Hinweis: Einlesen der Datei:       C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_wstring.h
1>  Hinweis: Einlesen der Datei:   C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/opensslconf.h
1>  Hinweis: Einlesen der Datei:  C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/pkcs7.h
1>  Hinweis: Einlesen der Datei:   C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/asn1.h
1>  Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h
1>  Hinweis: Einlesen der Datei:     C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_wtime.h
1>  Hinweis: Einlesen der Datei:    C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/e_os2.h
1>  Hinweis: Einlesen der Datei:     C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/opensslconf.h
1>  Hinweis: Einlesen der Datei:    C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/opensslconf.h
1>  Hinweis: Einlesen der Datei:    C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/bio.h
1>  Hinweis: Einlesen der Datei:     C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/crypto.h
1>  Hinweis: Einlesen der Datei:      C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/stack.h
1>  Hinweis: Einlesen der Datei:      C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/safestack.h
1>  Hinweis: Einlesen der Datei:      C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/opensslv.h
1>  Hinweis: Einlesen der Datei:      C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/ossl_typ.h
1>  Hinweis: Einlesen der Datei:      C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/opensslconf.h
1>  Hinweis: Einlesen der Datei:      C:\Daten\_projects\_Dev\sourcecode\branches\_NewOpenSSL_1_1\src\main\include\openssl/symhacks.h
1>  Hinweis: Einlesen der Datei:      C:\Program Files (x86)\Windows Kits\8.1\Include\um\**windows.h**
```

**Comment by mattcaswell** [comment]
I think I might have figured this out. I thought e_os2.h included windows.h, but apparently not.

What I think is happening is pkcs7.h includes asn1.h which include e_os2.h. At this point windows.h has not yet been included but OPENSSL_SYS_WIN32 gets defined.

Later asn1.h includes bio.h, which in turn includes crypto.h which in turn includes ossl_typ.h. At this point windows.h has *still not been included*. So ossl_typ.h runs the block above and does the "#undef X509_NAME". Later in crypto.h there *is* an include of windows.h which in turn includes wincrypt.h which redefines X509_NAME!

The answer in my mind is to include windows.h early on in ossl_typ.h. Can you add the following line to ossly_typ.h *after* the include of e_os2.h:

````
# include <windows.h>
````

**Comment by wolftobias** [comment]
In the header file ossl_typ.h I made the change

```
#ifndef HEADER_OPENSSL_TYPES_H
# define HEADER_OPENSSL_TYPES_H

#include <limits.h>

#ifdef  __cplusplus
extern "C" {
#endif

# include <openssl/e_os2.h>

# include <windows.h>
```

and this will fix the issue.

**Comment by mattcaswell** [comment]
Great. I'll write a patch for that shortly.

**Comment by wolftobias** [comment]
Sounds great! Please let me know when it is available.

**Comment by mattcaswell** [comment]
This should now be fixed, but was implemented in a different way. After some internal debate it was decided that including windows.h in our public header files was probably a bad idea. Apps developers may want more control over when windows.h is included (or even if it is included at all). Therefore we have removed windows.h from all our public headers altogether (in 1.1.0). This does have some knock on impacts - notably that if you want to use any of the CRYPTO_THREAD_* functions or you want to use any of the async.h functions that use the OSSL_ASYNC_FD type then you should include windows.h *before* any openssl headers.

Closing this ticket.

**Comment by Globik** [comment]
But if include windows.h before any openssl header leads to #undef x509_name behavor.

**Comment by mattcaswell** [comment]
Not sure if I understand your point?

**Comment by Globik** [comment]
Just wondering why x509_name is undefined.

**Comment by mattcaswell** [comment]
Because there is a name clash between windows and openssl. They both define that symbol. Therefore it is necessary for OpenSSL to undefine the windows version.

**Comment by Globik** [comment]
Ah yeah, there is a file that did not compile on windows 7 32bit vc++2015 and some openssl headers in it.
https://github.com/xhs/librtcdc/blob/master/src/dtls.c
And when I included windows.h on top , it get compiled. X509_name get compiled like a charm.
Thank you very much for your hint.
