### ISSUE TITLE
Missing accessors in ssl struct

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1158]
Please provide accessors for the following variables in SSL structure.

```
ssl->s3->tmp.ctype;
ssl->s3->tmp.ctype_num;
```

**Comment by richsalz** [comment]
Look for ```SSL_CTRL_GET_CLIENT_CERT_TYPES``` which isn't documented :(

**Comment by richsalz** [comment]
Look at the undocumented function ```SSL_get0_certificate_types```
