### ISSUE TITLE
EVP_set_default_properties() does not work

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11594]
The function `EVP_set_default_properties()` does not seem to be working. I created the following test program:

````
#include <stdio.h>
#include <openssl/evp.h>

int main(void)
{
    EVP_MD *md;

    if (!EVP_set_default_properties(NULL, "provider=wibble"))
        printf("Failed to set default properties\n");

    md = EVP_MD_fetch(NULL, "SHA2-256", NULL);
    if (md == NULL)
        printf("Failed to fetch the digest\n");
    else
        printf("Succeeded fetching the digest\n");

    EVP_MD_free(md);

    return 0;
}

````

The output I received was "Succeeded fetching the digest". But I expected it to fail, because no implementations match the specified criteria.

I also note that `EVP_set_default_properties()` does not exist in the test suite - so we should fix that.

**Comment by levitte** [comment]
The issue is multi-faceted...

1.  When a NULL (or possibly also an empty) propquery is passed, the global properties aren't considered, at all:

    https://github.com/openssl/openssl/blob/c72e59349f50ee00a1bf8605ada17dfccb8b3b1a/crypto/property/property.c#L326-L354

2.  The global properties are stored in the METHOD store rather than the library context.  This would be fine if we knew that we have only one METHOD store per library context, but that isn't the case; any time we fetch new methods from the provider, we do so to a temporary store that is created during the fetch and destroyed before the fetch is finished.  We do this to deal with no-cache implementations in a uniform manner.

    The solution *should* be to store the global properties in the library context.

**Comment by paulidale** [comment]
Re: the first problem: lines 326 through 332 should be deleted and the search forced.

**Comment by paulidale** [comment]
and, no doubt, deal with the carnage that follows....

**Comment by mattcaswell** [comment]
Ping. This is still a problem I think. Who is picking this one up?

**Comment by levitte** [comment]
I've planned on it, after I get PSS going...  so er, that'll be after today.

**Comment by levitte** [comment]
(I couldn't famously say "I have a branch"...  sorry to disappoint :wink:)

**Comment by mattcaswell** [comment]
Ping?

**Comment by paulidale** [comment]
This turns ugly.  Fixing the immediate problem leads to another: a temporary store is created in `ossl_method_construct` which is then used to fetch the algorithm and the global property query doesn't go along for the ride.  Algorithm found ignoring the global properties.

Refer #12123 for the fix to the first bit.

**Comment by mattcaswell** [comment]
Isn't this fixed now?

**Comment by slontis** [comment]
@paulidale ?

**Comment by mattcaswell** [comment]
@paulidale?

**Comment by levitte** [comment]
I just went through all the related PRs, and it looks like everything is fixed, indeed.

**Comment by mattcaswell** [comment]
Ok. Closing then.
