### ISSUE TITLE
openssl 1.1.1d 32bit not working on solaris 10

### ISSUE THREAD

**Issue by hordemark** [openssl/openssl#11590]
Hi, I'm trying to migrate our software from using openssl 0.98e to 1.1.1d. Note that our software need to support 32bit on solaris 10. I had configured and built 1.1.1d with 32bit successfully.
```
./Configure  solaris-x86-gcc -lrt --prefix="/tmp/openssl-OpenSSL_1_1_1d/install" --openssldir="/tmp/openssl-OpenSSL_1_1_1d/install" no-mdc2 no-rc5 no-idea no-asm
```
Then I built our software with openssl 1.1.1d successfully.  But the software was crashed when I run it on **SSL_write** function. Could somebody give me some suggestion.

Thanks.

```
Call stack signal 11:
/tmp/dren/client_lme/AldCS/aldcs: handleSignal
/lib/libc.so.1: __moddi3
/lib/libc.so.1: sema_post
/opt/aldon/aldonlmc/0.0/lib/ssl/libssl.so.1.1: SSL_rstate_string
Error 0(Error 0) interpreting stack frame.

Signal ABRT
Stack Trace:
WARNING: unable to get stack trace (printstack)
/lib/libc.so.1:_lwp_kill+0x15 [ Signal 6 (ABRT)]
/lib/libc.so.1:raise+0x1f
/lib/libc.so.1:abort+0x64
/tmp/dren/client_lme/AldCS/aldcs:handleSignal+0x294
/lib/libc.so.1:0xa75df
/lib/libc.so.1:0x9d2a0
/opt/aldon/aldonlmc/0.0/lib/ssl/libssl.so.1.1:0x1a5c9 [ Signal 11 (SEGV)]
0xfe38e868
Abort (core dumped)
```

**Comment by hordemark** [comment]
Update: 
If our software and openssl 1.1.1d was built by 64bit. no errors pop up.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
