### ISSUE TITLE
CMP is not mentioned in CHANGES

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11606]
CMP is not mentioned in the CHANGES file. This this is a significant new feature of 3.0 we should have something about it.

**Comment by mattcaswell** [comment]
It might also be nice to have some words about it on the 3.0 wiki page:

https://wiki.openssl.org/index.php/OpenSSL_3.0

**Comment by levitte** [comment]
Is it mentioned in NEWS?

**Comment by DDvO** [comment]
> It might also be nice to have some words about it on the 3.0 wiki page:
> 
> https://wiki.openssl.org/index.php/OpenSSL_3.0

I've just done this. Since there was no section where this fit well, I tentatively created a new one:

**1.6 Other major new features**

**Comment by mattcaswell** [comment]
> I've just done this.

Thanks!

**Comment by DDvO** [comment]
Since also #11608 is merged I'm closing this.
