### ISSUE TITLE
Property queries aren't as flexible as they should be

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11603]
Right now we have a set of algorithms in the FIPS provider. They all have the property "provider=fips". Some of those algorithms are non-approved (X25519, X448, ED25519, ED448), so only a subset of algorithms have the property "fips=yes". In the default provider we have some serializers which we allow to be used with FIPS algorithms. These also have the property "fips=yes".

It is not currently possible to have the FIPS and default providers loaded and specify via a property query that you want everything in the FIPS provider (including the non-approved algorithms), as well as the serializers from the default provider, i.e. you can't do something like "provider=fips || fips=yes".

**Comment by levitte** [comment]
Side note: considering that others may want to create FIPS providers of their own, I think "provider=fips" isn't a good name, especially if we actually want to rely on it (so far, I've regarded that property as a nice-to-have, not as something actually useful).  "provider=openssl-fips", maybe?

**Comment by levitte** [comment]
I've started to wonder if we should have a fetch variant that takes a callback, rather than inventing another mini-language...  We could have a few predefined simple ones, such as a standard "match-this-property-query" kind of thing.

**Comment by paulidale** [comment]
Adding an "or" operation will add the need for parenthesis for grouping.

If we do want to head down this path, we should replace the current ',' separator with something more readable _before_ the β release freezes it.  Changing after that will be more difficult and confusing.

**Comment by paulidale** [comment]
The original design had arrays of queries which gave us the disjunction across array elements and conjunction within each.  This was later replaced by the caller making multiple query calls to get disjunction, conjunction remains unchanged.

The problem @mattcaswell ran into was only having a single query string and not being able to make multiple queries with different strings.

**Comment by mattcaswell** [comment]
How difficult would it be to add the capability for grouping and boolean operations within the query string?

**Comment by paulidale** [comment]
Updating the parser would be easy.

The query matcher is where the complexity lies -- instead of a list of things to match it will have to match trees (in the general case).

We could restrict it to something like:
```ebnf
property query =
    property clause
    | ( "(", property clause, ")", ( "OR", "(", property clause, ")" )* );

property clause =
    single query, ( "AND", single query )*;
```
which is a disjunction of bracketed conjunctive clauses.  This would be easier to match.

**Comment by mattcaswell** [comment]
> which is a disjunction of bracketed conjunctive clauses

I could live with that.

**Comment by paulidale** [comment]
That's what we've aimed for all along.

**Comment by paulidale** [comment]
Should the 'OR' short circuit or process everything?

Reconsider the short circuit in the presence of '?' :smile:

**Comment by mattcaswell** [comment]
Hmmm. I'm not actually sure what `?` means in the presence of "OR". How should this query be interpreted:

`(provider=fips) OR (?fips=yes)`

**Comment by paulidale** [comment]
Exactly :)

Prefer something that has both?  Short circuit?  I don't know.

**Comment by mattcaswell** [comment]
I suppose (if we had short-circuit) it would mean "select something from the fips provider, but if we fail to match something there then choose anything but prefer something with fips=yes"

**Comment by mattcaswell** [comment]
And the more I think about it...short circuit makes sense.

**Comment by t8m** [comment]
Why do we have ed25519 in FIPS provider when it is not approved?

**Comment by t8m** [comment]
To me this seems to be heading into wrong direction. In general applications would like to easily (without contortions such as complex queries) specify a query that will limit them only to implementations and algorithms that are **allowed** by FIPS, regardless of whether they are approved, non-crypto, or non-approved but allowed. Could we just have such property and use it?

**Comment by levitte** [comment]
@t8m, that was the original intent with "fips=yes", as far as I know.

**Comment by mattcaswell** [comment]
We could set "fips=yes" on everything in the FIPS module and the serializers and perhaps have a different property for the non-approved but allowed, e.g. "fipsapproved=yes" on algorithms not including X25519, X448, ED25519, ED448 or the serializers

That way you could just specify "fips=yes" and get everything in the FIPS provider plus the serializers. Which is probably what most people want.

But I think that just moves the problem around a bit. In that scenario it is no longer possible to say "Only FIPS approved plus the serializers"

**Comment by levitte** [comment]
At some point - quite a while ago now - we did talk about having multiple default propqueries, thereby getting an "or" property (i.e. merge the fetch query string with each of them and match against the algorithm prop definition, at least one must match).

In config file terms, that's super easy to specify, it's already part of the config file definition:

```
1.default_properties = fips=yes
2.default_properties = fips-compatible=yes
```

**Comment by paulidale** [comment]
It seems that adding ecx to the FIPS provider has caused all manner of problems.  We could remove them?

Alternatively, a serialisation provider could be loaded with the FIPS provider in their own library context -- no need for properties at all.

**Comment by mattcaswell** [comment]
> Alternatively, a serialisation provider could be loaded with the FIPS provider in their own library context -- no need for properties at all.

The reason we didn't do this is because we didn't want to bring the ASN.1 code into the FIPS provider.

**Comment by mattcaswell** [comment]
@levitte's suggestion seems workable

**Comment by paulidale** [comment]
> The reason we didn't do this is because we didn't want to bring the ASN.1 code into the FIPS provider.

Note: _serialisation provider_.  I.e. separate from the default provider.  It would be outside the FIPS boundary and the library context would be the selection mechanism.

**Comment by paulidale** [comment]
Agreed, @levitte's suggestion seems good.

**Comment by paulidale** [comment]
> Why do we have ed25519 in FIPS provider when it is not approved?

The sponsors' wanted TLS 1.3 support including ecx even though it isn't FIPS approvable yet.

**Comment by richsalz** [comment]
As for https://github.com/openssl/openssl/issues/11603#issuecomment-617644752 I thought the intent was that non-openssl things (and properties) have a period in their name.  Am I over-remembering?

**Comment by paulidale** [comment]
The period is only for property names, not property values.

**Comment by richsalz** [comment]
Oh man, this is headed to a real dark and bad place.  We're defining all sorts of query semantics using a non-standard (and therefore non-intuitive) query language.  Perhaps take a step back AWAY from this PR, think and design, and come back with a document that people can look at.

I mean, if Paul says "I don't know what to do" that's an indication that this is heading off the rails.

Again, I still vote for something based on SQL query.

**Comment by levitte** [comment]
I you read on, @richsalz, you'll see that there was a change in the line of thinking.

**Comment by richsalz** [comment]
I read the thread before posting, Richard.

**Comment by paulidale** [comment]
Substitute `&&` for AND and `||` for OR and we're back to something people would understand readily :)  Still, it is a valid point.

**Comment by paulidale** [comment]
This will not be done for 3.0.

**Comment by nhorman** [comment]
@paulidale @mattcaswell @levitte @t8m 

4.0 is looming on the horizon, if this is still something we want to do, we should start planning it now.

Otherwise I would suggest closing this.  

thoughts?

**Comment by t8m** [comment]
I do not think this is something we should pursue for 4.0. IMO this is not that much useful feature.

OTOH perhaps we should collect all these features that would be feasible but we are unsure about them for 4.0 and get community feedback on which of these should be prioritized?

**Comment by paulidale** [comment]
I agree not for 4.0.

We're not really using properties very much (provider & fips basically).  Until we do, there isn't much point adding the stuff here.
