### ISSUE TITLE
Is possible to generate any length hash of shake128 and shake256

### ISSUE THREAD

**Issue by odingo** [openssl/openssl#11605]
In this link https://www.openssl.org/docs/man1.1.1/man3/EVP_shake256.html,

> The SHAKE-128 and SHAKE-256 Extendable Output Functions (XOF) that can generate a variable hash length.
> Specifically, EVP_shake128 provides an overall security of 128 bits, while EVP_shake256 provides that of 256 bits.

In FIPS-202

> An extendable-output function (XOF) is a function on bit strings (also called messages) in which
the output can be extended to any desired length. The two SHA-3 XOFs are named SHAKE128
and SHAKE256. The suffixes “128” and “256” indicate the security strengths that these two
functions can generally support, in contrast to the suffixes for the hash functions, which indicate
the digest lengths. SHAKE128 and SHAKE256 are the first XOFs that NIST has standardized.

But it seems the digest length of EVP_shake128 is fixed to 128, and EVP_shake256 is fixed to 256.
How could I get a digest which length is longer than 128 with EVP_shake128 (or longer than 256 with EVP_shake256)?

Thank you.

**Comment by kroeckx** [comment]
Use the EVP_DigestFinalXOF() function

**Comment by odingo** [comment]
Thank you, @kroeckx, it works!
