### ISSUE TITLE
Why I have openssl1.1.1 installed but reported 1.1.0 when dpkg -i ca-certificate.deb?

### ISSUE THREAD

**Issue by lk1983823** [openssl/openssl#11611]
I have openssl reinstalled on my Nvidia Jetson Nano with arm64.
I run openssl version in terminal, it shows OpenSSL 1.1.1f  31 Mar 2020.
But when I sudo dpkg -i ca-certificates_20190110_all.deb, it shows 

`dpkg: Dependency issues prevent ca-certificates configuration work from continuing:
  ca-certificates depends on openssl (> = 1.1.1); however:
The version of openssl in the system is 1.1.0g-2ubuntu4.3.
`
Thanks

**Comment by levitte** [comment]
You should ask Ubuntu.  However, I venture a guess that you're installed OpenSSL from source, i.e. have that installation in `/usr/local`.  This is different from the system installed OpenSSL, which is another Ubuntu package.

And before you go try it, *do not replace the system installed openssl with your own build*, that is likely to screw your system up.  Find the 1.1.1 Ubuntu openssl package instead.  If you have difficulties finding it, ask Ubuntu.

**Comment by lk1983823** [comment]
Thank you. Yes I build it from source.

发自我的 iPhone
