### ISSUE TITLE
NULL dereference in EVP_PKEY_get_raw_private_key with provider side keys

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#11627]
When EVP_PKEY_get_raw_private_key or EVP_PKEY_get_raw_public_key is called with a provider side key, there is a NULL dereference.

pkey->ameth for provider side keys is NULL:
https://github.com/openssl/openssl/blob/master/crypto/evp/p_lib.c#L384

A check for NULL could be added:
https://github.com/openssl/openssl/pull/11628

**Comment by mattcaswell** [comment]
This highlighted a whole heap of problems with ECX provider keys. My fix for this issue and other related ones in #11635.
