### ISSUE TITLE
ED25519_public_from_private() sometimes returns wrong result

### ISSUE THREAD

**Issue by kaduk** [openssl/openssl#11621]
As noted in #11600 there seem to be cases when ED25519_public_from_private() produces the wrong result for the SHA512 hash of the private key.
I've done some local testing involving using both the "old" and "new" codepaths to hash into separate output arrays to confirm that the "new" path is producing an incorrect result.

**Comment by mattcaswell** [comment]
As noted in #11600, I think this is actually a problem in TLSProxy and not a problem with Ed25519 itself at all.

**Comment by kaduk** [comment]
Closing, as this does not look like a library issue anymore.
