### ISSUE TITLE
Use of uninitialized value $provider in generate_ssl_tests.pl

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#11639]
I'm getting:
Use of uninitialized value $provider in string eq at ../../test/generate_ssl_tests.pl line 131.
Use of uninitialized value $provider in string eq at ../../test/generate_ssl_tests.pl line 132.
Use of uninitialized value $provider in string eq at ../../test/generate_ssl_tests.pl line 132.

**Comment by mattcaswell** [comment]
Documentation bug. Fix in #11659.
