### ISSUE TITLE
Doc issue about ed{25519,448} and cmdline tools

### ISSUE THREAD

**Issue by romen** [openssl/openssl#11633]
As reported by @vdukhovni on the [openssl-users ML](https://mta.openssl.org/pipermail/openssl-users/2020-April/012310.html):

> [The changes introduced by #6284 left ] us with a documentation bug, the dgst(1) manpage suggests using pkeyutl(1) for ed25519 and ed448, but the latter does not work.
> 
> The dgst(1) manpage probably needs a tweak to remove the misleading redirect.  Or else backport the pkeyutl(1) support from 3.0, but we're not supposed to add features in 1.1.1x patch releases, and there are no plans for a 1.1.2. 

https://github.com/openssl/openssl/blob/bb17971acb0d891b734991091244b90019968c65/doc/man1/dgst.pod#L94-L98

https://github.com/openssl/openssl/blob/bb17971acb0d891b734991091244b90019968c65/doc/man1/pkeyutl.pod#L203-L205

**Comment by rajatdiptabiswas** [comment]
Would you kindly let me know what exactly needs to be done so that I can try working on the issue?

**Comment by romen** [comment]
@rajatdiptabiswas thanks for taking an interest in this!

> Would you kindly let me know what exactly needs to be done so that I can try working on the issue?

Sure, I believe the easiest path would be to open a new GitHub Pull Request (PR), editing `doc/man1/dgst.pod` to just remove the last sentence `Use the B<pkeyutl> command instead for this.` from
https://github.com/openssl/openssl/blob/bb17971acb0d891b734991091244b90019968c65/doc/man1/dgst.pod#L94-L98

To start contributing to the project you should get familiar with [CONTRIBUTING.md](https://github.com/openssl/openssl/blob/master/CONTRIBUTING.md) and provide a [Contributor License Agreement][CLA] (CLA) as documented there.

[CLA]: https://www.openssl.org/policies/cla.html

**Comment by romen** [comment]
Notice this is a `1.1.1` issue, so you should work on a branch forked from `OpenSSL_1_1_1-stable`!

**Comment by rajatdiptabiswas** [comment]
Sure. Thanks a lot @romen.
I'll see what I can do.

**Comment by rajatdiptabiswas** [comment]
Created a PR to solve the issue. Kindly check if it's alright.

**Comment by romen** [comment]
This was fixed by  1632a6854cc594901018f9490426b26e893aae43 from #11636 but for some reason I am currently missing the usual GitHub automation was not triggred.

Closing manually.

Thanks again!
