### ISSUE TITLE
does the SHA3 in openssl support non-byte-aligned message?

### ISSUE THREAD

**Issue by odingo** [openssl/openssl#11646]
I'm trying to calculate the digest of an n-bit message where n is NOT a multiple of 8 by exercising one of the SHA3 algorithm in openssl.
The 3rd parameter of EVP_DigestUpdate is the bytes count of the message.
Which routine should I use if the input message is for example 5-bit (or 30-bit) long only?

 EVP_DigestInit_ex(mdctx, EVP_sha3_256(), NULL)
 EVP_DigestUpdate(mdctx, message, message_len)

Thank you!

**Comment by kroeckx** [comment]
OpenSSL only supports bytes.

**Comment by odingo** [comment]
Thank you, get it.
