### ISSUE TITLE
3.0-alpha1: "openssl speed" complains about md4/ripemd160 +EdDSA

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#11650]
Built alpha1 with ../config.

 "openssl speed" reports:

>  Doing md4 for 3s on 16 size blocks: md4 error!
>  40:07:14:74:7B:7F:00:00:error:digital envelope routines:evp_generic_fetch:fetch failed:../crypto/evp/evp_fetch.c:307:Default library context, Algorithm (MD4), Properties ()
>  40:07:14:74:7B:7F:00:00:error:digital envelope routines:EVP_DigestInit_ex:initialization error:../crypto/evp/digest.c:175:
>  Doing md5 for 3s on 16 size blocks: 27556753 md5's in 3.00s
> …
>  Doing whirlpool for 3s on 16384 size blocks: 36288 whirlpool's in 3.00s
>  Doing rmd160 for 3s on 16 size blocks: rmd160 error!
>  40:07:14:74:7B:7F:00:00:error:digital envelope routines:evp_generic_fetch:fetch failed:../crypto/evp/evp_fetch.c:307:Default library context, Algorithm (RIPEMD160), Properties ()
>  40:07:14:74:7B:7F:00:00:error:digital envelope routines:EVP_DigestInit_ex:initialization error:../crypto/evp/digest.c:175:
>  Doing rc4 for 3s on 16 size blocks: 96622041 rc4's in 3.00s
> …
>  Doing 253 bits  ecdh's for 10s: 288312 253-bits ECDH ops in 10.00s
>  Doing 448 bits  ecdh's for 10s: 25217 448-bits ECDH ops in 10.00s
>  Doing 253 bits sign Ed25519's for 10s: 240352 253 bits Ed25519 signs in 10.00s
>  EdDSA verify failure.  No EdDSA verify will be done.
>  40:07:14:74:7B:7F:00:00:error:digital envelope routines:EVP_DigestSignUpdate:called a function you should not call:../crypto/evp/m_sigver.c:312:
>  Doing 456 bits sign Ed448's for 10s: 37818 456 bits Ed448 signs in 10.00s
>  EdDSA verify failure.  No EdDSA verify will be done.
>  40:07:14:74:7B:7F:00:00:error:digital envelope routines:EVP_DigestSignUpdate:called a function you should not call:../crypto/evp/m_sigver.c:312:
>  Doing 256 bits sign CurveSM2's for 10s: 22645 256 bits CurveSM2 signs in 10.00s
> …

Is this something obvious wrong "speed" or are those algorithms (md4+ripe) fading out?

**Comment by mattcaswell** [comment]
For MD4 and whirlpool this is probably because these algorithms are no longer available by default (you need  to explicitly load the legacy provider to get them). Probably speed should not attempt to test them unless they are present.

For Ed448/Ed25519 it should not be attempting to call EVP_DigesetSignUpdate for those algorithms - they don't support it.

**Comment by paulidale** [comment]
Or `speed` should load the legacy provider if needed?

**Comment by levitte** [comment]
> Or `speed` should load the legacy provider _if needed_?

I don't think there's an in-between.  Do, or do not.

**Comment by romen** [comment]
What if we removed legacy algorithms from the list of things `speed` tested by default instead?

That way it would be up to the user to configure the system to load the legacy provider before calling `speed md4`.

If we changed `speed` to always load `legacy` I believe it would be confusing for users if all algorithms worked fine with it while other commands required explicit changes in configuration.

**Comment by levitte** [comment]
What if we rework `speed` to not make sso many assumptions?

**Comment by mattcaswell** [comment]
> What if we removed legacy algorithms from the list of things speed tested by default instead?

I agree

**Comment by sebastianas** [comment]
On 2020-04-27 03:22:32 [-0700], mattcaswell wrote:
> > What if we removed legacy algorithms from the list of things speed tested by default instead?
> 
> I agree

okay. So md4+ripemd160 are legacy algorithms and require special
initialisation. I only found this information in
SSL_PROVIDER-legacy.pod. Wouldn't it be good idea to add a note to
EVP_md4.pod (and the other ones) saying that they are legacy and
pointing them to SSL_PROVIDER-legacy.pod?
(I just noticed that this is mentioned in the wiki, once I knew what to
look for).

I will prepare a PR to remove md4+ripemd160 from the list that speed
tests so the error is gone. This means md4 won't be tested at all.

And as for Ed448/Ed25519, I will look and remove the call to
EVP_DigesetSignUpdate().

Is this okay?

Sebastian

**Comment by mattcaswell** [comment]
> Wouldn't it be good idea to add a note to
EVP_md4.pod (and the other ones) saying that they are legacy and
pointing them to SSL_PROVIDER-legacy.pod?

Yes. This would be a really good idea.

**Comment by mattcaswell** [comment]
> I will prepare a PR to remove md4+ripemd160 from the list that speed
tests so the error is gone. This means md4 won't be tested at all.

You should be able to test it if you explicitly ask for it (because you can always add the "-provider legacy" option and make it available). Just don't test by default.

> Is this okay?

A big yes!
