### ISSUE TITLE
FFT for BIGNUM multiplication

### ISSUE THREAD

**Issue by Jaskamalkainth** [openssl/openssl#11658]
Why we are using Karatsuba Algorithm for Bignum Multiplication whereas we have a far better algorithm with FFT which runs in O(n*logn) time.

As far as I know, in GMP we are using a combination of Naive school multiplication, Karatsuba, etc and FFT to support bignum multiplication which is the most optimized way.

[https://tspiteri.gitlab.io/gmp-mpfr-sys/gmp/Algorithms.html#Multiplication-Algorithms](https://tspiteri.gitlab.io/gmp-mpfr-sys/gmp/Algorithms.html#Multiplication-Algorithms)

For multiplication of large input in bn_mul() we can support FFT right?

**Comment by bbbrumley** [comment]
> Why we are using Karatsuba Algorithm for Bignum Multiplication whereas we have a far better algorithm with FFT which runs in O(n*logn) time.

Because the crossover point where FFT beats Karatsuba is high. The way OpenSSL uses BIGNUMs is way below this threshold.

OpenSSL's BIGNUM implementation is geared towards clear and standardized cryptographic implementations, not towards efficiency as a general multi-precision integer arithmetic library (like GMP).

Feel free to prove me wrong ;) PR's welcome if you can manage to improve what `openssl speed` spits out!

**Comment by DanFulger** [comment]
https://en.wikipedia.org/wiki/Sch%C3%B6nhage%E2%80%93Strassen_algorithm says the GMP cutoff is 110592 bits.

**Comment by bernd-edlinger** [comment]
Also GMP is not about constant time it can have short cuts like x*0 = 0,
OpenSSL BigNums must use constant time algorithms that is far more
important than speed.

**Comment by mattcaswell** [comment]
Looks like this was answered, so closing.

**Comment by hanno-arm** [comment]
FYI https://eprint.iacr.org/2022/439 (Doesn't mean this should be done in OpenSSL of course)

**Comment by paulidale** [comment]
I notice the comparison with Mbed TLS and BearSSL for 2k and 4k bit numbers.  Do you have similar numbers for OpenSSL?

Any performance improvement below 16k bit numbers would be interesting I think.

**Comment by hanno-arm** [comment]
@paulidale Not to date, we deliberately limited the scope to MCUs for now, but as mentioned in the "Other work" section, a study for high end CPUs would be equally interesting. OpenSSL would be an interesting point of comparison there.
