### ISSUE TITLE
SSH-keygen with RSA 4096 generate errors for openssl on macOS Catalina!

### ISSUE THREAD

**Issue by PontusTideman** [openssl/openssl#11653]
So, generated a new SSH key for new work with RSA 4096. All went well, and I was receiving a file that was encrypted with my public key.

First one liner was:
`base64 -d < secret.enc > secret.unc`

Second one liner was:
`openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in secret.unc`
Even when I spec the -out to a new file it throws errors.

The **enc** and **unc** is just random extensions for now!

The output I get is:

`unable to load Private Key
4430040684:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.100.4/libressl-2.8/crypto/pem/pem_lib.c:684:Expecting: ANY PRIVATE KEY`

The private key begins with and ends with:
cat id_rsa
-----BEGIN OPENSSH PRIVATE KEY-----
.......
-----END OPENSSH PRIVATE KEY-----

The version of openssl is:
`openssl version
LibreSSL 2.8.3`

**Comment by mattcaswell** [comment]
Since you are using Libressl and not OpenSSL you are probably better asking this question on their support forums.

OpenSSL at least does not support SSH keys. My guess is the same is true about Libressl.

**Comment by mattcaswell** [comment]
Looks like this was answered. Closing.

**Comment by numericillustration** [comment]
@PontusTideman one can convert the key from ssh2 ( https://www.ietf.org/rfc/rfc4716.txt ) format to a supported PEM format (https://tools.ietf.org/html/rfc7468 ) by changing the passphrase and specifying a different output format as follows
```
ssh-keygen -p -m PEM -f ~/.ssh/id_rsa
```
to be able to use it with rsautl
