### ISSUE TITLE
Can't locate Test/More.pm in @INC when compiling openssl-3.0.0-alpha1

### ISSUE THREAD

**Issue by satya-kotla** [openssl/openssl#11664]
I am compiling openssl-3.0.0-alpha1 on RHEL 7 and getting the following compilation error.
Attaching the output from "perl configdata.pm --dump" command. Please suggest how to fix this compilation error.
[configdata.pm.dump.txt](https://github.com/openssl/openssl/files/4541198/configdata.pm.dump.txt)

/usr/bin/perl "-I." "-Iproviders/common/der" -Mconfigdata -Moids_to_c "util/dofile.pl" "-oMakefile" providers/common/der/der_dsa.h.in > providers/common/include/prov/der_dsa.h
Can't locate Test/More.pm in @INC (@INC contains: /app/digital/softwares/openssl-3.0.0-alpha1/util/perl . providers/common/der /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 /app/digital/softwares/openssl-3.0.0-alpha1/external/perl/Text-Template-1.56/lib) at /app/digital/softwares/openssl-3.0.0-alpha1/util/perl/OpenSSL/OID.pm line 309.
BEGIN failed--compilation aborted at /app/digital/softwares/openssl-3.0.0-alpha1/util/perl/OpenSSL/OID.pm line 309.
Compilation failed in require at providers/common/der/oids_to_c.pm line 16.
BEGIN failed--compilation aborted at providers/common/der/oids_to_c.pm line 16.
Compilation failed in require.
BEGIN failed--compilation aborted.
make[1]: *** [providers/common/include/prov/der_dsa.h] Error 2
make[1]: Leaving directory `/app/digital/softwares/openssl-3.0.0-alpha1'
make: *** [build_sw] Error 2

**Comment by levitte** [comment]
That's probably because you didn't read these lines:

https://github.com/openssl/openssl/blob/80b94a5adb461f94629d36db351a051b0a890856/NOTES.PERL#L23-L24

**Comment by satya-kotla** [comment]
Thanks for the input. Installed 'perl-core' on RHEL7 and then compiled openssl-3.0.0-alpha1 successfully.
