### ISSUE TITLE
Does openssl support rfc5652

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#11667]
Hi @beldmit ,
   I found that in cms_lcl.h, openssl supprot CMS(Cryptographic Message Syntax)
taken from rfc3852.  And now the new version is rfc5652. I want to know whether
openssl support rfc5652?

Best Regards.
Miky Ma

**Comment by beldmit** [comment]
Unfortunately, I don't know it exactly but in my practice everything was fine.

**Comment by joymcg** [comment]
> Unfortunately, I don't know it exactly but in my practice everything was fine.

thanks

**Comment by kaduk** [comment]
https://tools.ietf.org/html/rfc5652#section-1.1.4 basically says that there are no significant changes, anyway.

**Comment by joymcg** [comment]
close it
