### ISSUE TITLE
SSL_CTX_set_cipher_list. The default cipher suite does not include RC4. Can the default cipher suite be changed?

### ISSUE THREAD

**Issue by gitguyingzhi** [openssl/openssl#11665]
SSL_CTX_set_cipher_list. The default cipher suite does not include RC4. Can the default cipher suite be changed?

**Comment by mattcaswell** [comment]
You cannot change the compiled in default cipher suite list unless you modify the OpenSSL source itself. But of course that's the whole point of SSL_CTX_set_cipher_list - to modify the list to whatever you want. So I'm not sure why you would want to change the compiled in default.
