### ISSUE TITLE
Hello! I am a freshman in Fuzzing. Can I ask you where I can find how to fuzz the openssl with the AFL ? What is the testing instruction? Thanks!

### ISSUE THREAD

**Issue by joanxqdeng** [openssl/openssl#11661]

**Comment by mattcaswell** [comment]
See this file for information on fuzzing the master branch:

https://github.com/openssl/openssl/blob/master/fuzz/README.md

See the equivalent file in the 1.1.1 tree for fuzzing that version.

**Comment by joanxqdeng** [comment]
Thank you very much!

**Comment by qa8302** [comment]
tapatalk://forums.pelicanparts.com?channel=share_link_topic&type=vb3x_4.10.2&location=topic&fid=844&tid=1058197
