### ISSUE TITLE
3.0.0-alpha1: "openssl pkcs12" is unable to parse or create PKCS#12 archives with default ciphers

### ISSUE THREAD

**Issue by sfackler** [openssl/openssl#11672]
Works in 1.1.1:
```
$ openssl version
OpenSSL 1.1.1d FIPS  10 Sep 2019
$ openssl pkcs12 -in cert.pem -inkey key.pem -out foo.p12 -export
Enter Export Password:
Verifying - Enter Export Password:
```

Fails in 3.0.0:
```
$ $HOME/openssl-3.0.0/bin/openssl version
OpenSSL 3.0.0-alpha1 23 Apr 2020 (Library: OpenSSL 3.0.0-alpha1 23 Apr 2020)
$ $HOME/openssl-3.0.0/bin/openssl pkcs12 -in cert.pem -inkey key.pem -out foo.p12 -export
Enter Export Password:
Verifying - Enter Export Password:
40:A7:D6:79:1B:7F:00:00:error:digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:307:Default library context, Algorithm (RC2-40-CBC), Properties ()
40:A7:D6:79:1B:7F:00:00:error:digital envelope routines:EVP_CipherInit_ex:initialization error:crypto/evp/evp_enc.c:336:
40:A7:D6:79:1B:7F:00:00:error:digital envelope routines:EVP_PBE_CipherInit:keygen failure:crypto/evp/evp_pbe.c:132:
40:A7:D6:79:1B:7F:00:00:error:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 algor cipherinit error:crypto/pkcs12/p12_decr.c:36:
40:A7:D6:79:1B:7F:00:00:error:PKCS12 routines:PKCS12_item_i2d_encrypt:encrypt error:crypto/pkcs12/p12_decr.c:133:
40:A7:D6:79:1B:7F:00:00:error:PKCS12 routines:PKCS12_pack_p7encdata:encrypt error:crypto/pkcs12/p12_add.c:119:
```

**Comment by paulidale** [comment]
Adding "-provider legacy" to the command line should work around this.

I'm not sure about using RC2.

**Comment by levitte** [comment]
> I'm not sure about using RC2.

Unfortunately, is glaringly present in the RFC: https://tools.ietf.org/html/rfc7292#appendix-C

**Comment by mattcaswell** [comment]
Is this only the case where a password is used? Perhaps we should fail with a helpful error message if the right cipher is not available and tell the user to explicitly load the legacy provider? Or alternatively should we automatically load it?

**Comment by paulidale** [comment]
There was a vote to not load the legacy provider by default, that's not ideal.

How would we warn the user when an algorithm isn't found?  The core fetch doesn't know that _RC2_ is a legacy algorithm.  It also doesn't know which provider _foobar_ comes from.

**Comment by mattcaswell** [comment]
> How would we warn the user when an algorithm isn't found? The core fetch doesn't know that RC2 is a legacy algorithm. It also doesn't know which provider foobar comes from.

But we know that PKCS12 has a hard-wired dependency on RC2-40-CBC - and we know that specific cipher is in the legacy provider. So we simply try to fetch that before doing anything with PKCS12 and if we get `NULL` back then we display a nice error message to the user suggesting they add `-provider legacy`

**Comment by levitte** [comment]
So what you're saying, @mattcaswell, is that the `openssl pkcs12` commant should load the legacy provider as a fallback?  Or should we make that globally in the `openssl` app?

**Comment by levitte** [comment]
Internally, we can load but not activate a provider, and flag it as fallback.  It would be perfectly possible to add a public function for this, and have that be used by our application.

**Comment by mattcaswell** [comment]
> So what you're saying, @mattcaswell, is that the openssl pkcs12 commant should load the legacy provider as a fallback? Or should we make that globally in the openssl app?

Well I suggested 2 possible paths:

1) Don't load legacy, but attempt to detect that we're failing because of an unavailable cipher and display a hint to the user that they might like to explicitly load the provider

or

2) Automatically load the legacy provider *for this one use case*

I do not think we should load it globally in the openssl app. The more I think about it the more I prefer (1) and the less I prefer (2). Although it might be tricky to get the detection right. Looking at the RFC there are a number of OIDs defined - some of which are in the legacy provider and some of which are not.

**Comment by paulidale** [comment]
> Internally, we can load but not activate a provider, and flag it as fallback.

It would be just as easy to load the legacy provider.  Easier since the API already exists.


> Don't load legacy, but attempt to detect that we're failing because of an unavailable cipher and display a hint to the user that they might like to explicitly load the provider

This would be my preference.  What about printing a message along the lines of: _algorithm not found, does a provider need to be loaded?_

**Comment by qa8302** [comment]
@sfackler

**Comment by mattcaswell** [comment]
(Note I blocked user qa8302....they have been commenting on various issues/PRs with random spam)

**Comment by levitte** [comment]
> It would be just as easy to load the legacy provider. Easier since the API already exists.

... except someone might use a config file, and thereby define a whole different set of providers, in which case the legacy provider *should not* get activated.  That's why fallbacks exist in the first place.

**Comment by mattcaswell** [comment]
> This would be my preference. What about printing a message along the lines of: algorithm not found, does a provider need to be loaded?

This is also my preference. How will we know that the error is caused by a missing algorithm?

**Comment by levitte** [comment]
I don't think we should over engineer things in the apps.  Talk of advanced detection gives me the heeby-geebies.  If you want to go down the route of advising the user, it should probably be done in a generic way, i.e. "This happened, you might want to add a different provider, for example '-provider legacy'"

**Comment by mattcaswell** [comment]
> I don't think we should over engineer things in the apps. Talk of advanced detection gives me the heeby-geebies. If you want to go down the route of advising the user, it should probably be done in a generic way, i.e. "This happened, you might want to add a different provider, for example '-provider legacy'"

I'd be ok with that...but do we just do that for any error then? Or do we narrow it down somewhat?

**Comment by levitte** [comment]
> ...but do we just do that for any error then? Or do we narrow it down somewhat?

That depends on where the error is detected, doesn't it?  I.e. for function calls that is likely to call a fetch function down the callstack, we can choose to do this.  In case of uncertainty, do it for all.

**Comment by mattcaswell** [comment]
> That depends on where the error is detected, doesn't it? I.e. for function calls that is likely to call a fetch function down the callstack, we can choose to do this. In case of uncertainty, do it for all.

Works for me - but we should probably make sure we have decent documentation about this for the pkcs12 app.

**Comment by levitte** [comment]
> Works for me - but we should probably make sure we have decent documentation about this for the pkcs12 app.

Agreed

**Comment by mattcaswell** [comment]
> Agreed (what about other apps?)

Other apps probably need to be handled on a case-by-case basis.

**Comment by t8m** [comment]
But why not default to PBES2 with PBKDF2 algos? And perhaps add a -legacy option to create a legacy-encrypted pkcs12 which would also load the legacy provider?

**Comment by t8m** [comment]
What is the point of creating insecurely encrypted pkcs12 files by default in openssl-3.0?

**Comment by paulidale** [comment]
> And perhaps add a -legacy option ...

This seems like a sensible suggestion.

The app framework could process the option and have it load the legacy provider _and_ set a global flag to enable other legacy behaviours.  It could be wrapped into the `OPT_PROV_OPTIONS` macro.

**Comment by richsalz** [comment]
Perhaps reconsider the decision to not load the legacy provider.

**Comment by t8m** [comment]
> Perhaps reconsider the decision to not load the legacy provider.

No, please, we should not use RC2 and similar abominations **by default**. And not having legacy provider loaded  by default prevents this nicely.

**Comment by richsalz** [comment]
Sure, not using weak crypto by default is a good thing.  So is not breaking existing applications. So is not breaking interop with external things.  It's all about trade-offs.

**Comment by levitte** [comment]
> And perhaps add a -legacy option ...

So there would be two ways to get the legacy providers loaded?

**Comment by levitte** [comment]
> But why not default to PBES2 with PBKDF2 algos?

Excellent thought!  PR welcome!  :wink:

**Comment by t8m** [comment]
> Sure, not using weak crypto by default is a good thing. So is not breaking existing applications. So is not breaking interop with external things. It's all about trade-offs.

I would never suggest something like this for 1.1.1 branch but I think it is very much appropriate and acceptable for 3.0 to change defaults. Because otherwise that would mean they are set-in-stone forever. We would not be taking away the possibility to create weakly encrypted things for interop with legacy systems completely. Just by default we would try to DTRT.

**Comment by t8m** [comment]
I'll work on the PR soon.

**Comment by paulidale** [comment]
> So there would be two ways to get the legacy providers loaded?

There are two already :)  I'd see the `-legacy` option as doing more than just loading the provider.  It could change the defaults as well e.g.

**Comment by t8m** [comment]
With the `-legacy` option we could switch the defaults to the current ones as of 1.1.1 which provide maximum interoperability in expense of security :D Although the RC2 is used only for encrypting the certificate, so that is actually not really protecting much. 3DES is used for protecting the key but with a weak password key derivation function.

**Comment by slontis** [comment]
> But why not default to PBES2 with PBKDF2 algos?

You might want to be careful with this kind of thing. The default may have been part of a standard also. Also ask 'if I change this -will it break existing apps'.

**Comment by t8m** [comment]
But I think OpenSSL-3.0 can break interoperability with legacy software. That is something expectable with a major version update. Otherwise we would never be able to update to more up-to-date defaults ever.

**Comment by zcybeijing** [comment]
how to solve the problem? I write code to call the function PKCS12_parse, if it can't work ,how can i change my code?

**Comment by sahanaprasad07** [comment]
> how to solve the problem? I write code to call the function PKCS12_parse, if it can't work ,how can i change my code?

@zcybeijing I am working on the fix, I'll have a MR in a few days hopefully
