### ISSUE TITLE
Building openssl on windows error

### ISSUE THREAD

**Issue by foroughmajidi** [openssl/openssl#11678]
I want to build openssl but I got this:

![Capture40](https://user-images.githubusercontent.com/51900859/80600925-efad9980-89e1-11ea-8407-eee2241cda96.PNG)

Please help me with the problem?

**Comment by mattcaswell** [comment]
That's strange. What perl version are you using?

**Comment by mattcaswell** [comment]
Can this be closed now?

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4  dev, barring further input
