### ISSUE TITLE
libcrypto fails to use KERN_ARND on NetBSD due to sys/sysctl.h not being included, and always falls back to reading from /dev/urandom

### ISSUE THREAD

**Issue by niacat** [openssl/openssl#11687]
This is fixed in NetBSD's vendored copy of OpenSSL. I'd like to help fix it here but I don't have access to a scanner to complete a CLA - can I sign it digitally?

`rand_unix.c` not only keeps usage of `sysctl(KERN_ARND)` behind `if defined(__FreeBSD__) || defined(__NetBSD__)`, it also checks if the `KERN_ARND` symbol is defined on these platforms. This is fragile. It makes what should be a hard error into a silent one. The syscall is available on all supported NetBSD and FreeBSD versions going back a decade.

[OpenSSL isn't including sys/sysctl.h on NetBSD](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_unix.c#L30) when the code obviously assumes it's included. So, KERN_ARND never gets defined, and the syscall never gets used due to the silent failure.  The fallback to /dev/urandom introduces potential problems because opening and reading from it can fail, while `sysctl(KERN_ARND)` never fails if used correctly. `sys/sysctl.h` should be included on NetBSD in `rand_unix.c`.

[This hack for old FreeBSD versions](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_unix.c#L224) is enabled unconditionally. It should probably be enabled conditionally just in case it means we can't get entropy on NetBSD.

`sysctl(KERN_ARND)` supports non-blocking reads of up to 256 bytes per call. Requests for higher numbers will fail. [If buflen exceeds 256 bytes, len should be set to 256 bytes here](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_unix.c#L251). I'm not sure if OpenSSL will request more than 256 bytes in practice, but it's something to be aware of.

**Comment by mattcaswell** [comment]
>  I'd like to help fix it here but I don't have access to a scanner to complete a CLA - can I sign it digitally?

Yes that's fine. PRs addressing this issue would be welcome.

**Comment by kroeckx** [comment]
I think this was fixed in #11689
