### ISSUE TITLE
about x509v3_cache_extensions issue on 1.1.1f 

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#11686]
about https://github.com/openssl/openssl/commit/ba4356ae4002a04e28642da60c551877eea804f7

Because the addition of the EXFLAG_INVALID assignment to the x509v3_cache_extensions interface caused some of the previously used certificates to be unusable, so I would like to consult when verifying the certificate extension fields are all parsed fields strictly according to RFC5280 description?

**Comment by bernd-edlinger** [comment]
Apoplgies for the inconvenience, there were a lot of code paths where
error handling was previously broken, which certificate causes you
this trouble, can you post a sample? (in pem format, please no URL)

**Comment by Mengliuxx** [comment]
I know that the problem is in the field [X509v3 Authority Key Identifier], but what I want to know is, in the version of 1.1.1f, does it strictly follow RFC5280 to parse the certificate extension field?


openssl x509 -in Certificates_SDV/Certificates/iPSICerts/DSA_V3/DSA_1024_SHA1_V3/cacert.pem  -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 517025777041 (0x7861234591)
        Signature Algorithm: dsaWithSHA1
        Issuer: C = IN, O = Huawei, OU = HTIPL, dnQualifier = dnQualifier, ST = Karnataka, CN = ipsiROOT, serialNumber = serial, L = AirportRoad, title = ms, SN = Inc, GN = Huawei, initials = ini, pseudonym = pseudo, generationQualifier = 1, emailAddress = ipsi@huawei.com, DC = SecurityTestTeam
        Validity
            Not Before: Sep 26 12:01:03 2005 GMT
            Not After : Sep 26 12:01:04 2016 GMT
        Subject: C = IN, O = Huawei, OU = HTIPL, dnQualifier = dnQualifier, ST = Karnataka, CN = ipsiCA, serialNumber = serial, L = AirportRoad, title = ms, SN = Inc, GN = Huawei, initials = ini, pseudonym = pseudo, generationQualifier = 1, emailAddress = ipsiCA@huawei.com, DC = SecurityTestTeam
        Subject Public Key Info:
            Public Key Algorithm: dsaEncryption
                pub: 
                    71:f4:15:4a:0f:5f:d0:5a:f5:88:ae:f2:b9:96:a7:
                    64:9e:c8:98:b2:13:06:bf:75:3b:e6:48:28:63:b3:
                    b2:bc:aa:3e:e0:d4:a6:bf:12:1c:2b:b7:82:99:5a:
                    55:79:86:e3:58:e3:11:9d:b5:32:29:0f:fc:f5:e8:
                    ef:73:94:6f:2d:e6:5a:ca:73:0d:e7:e6:73:74:0c:
                    3c:3c:5f:5f:9d:e9:dc:91:66:37:8f:f8:90:95:3d:
                    97:f1:1b:93:10:d9:f4:2f:31:35:8c:e9:d9:b7:cb:
                    10:33:fc:59:f4:06:64:54:09:74:62:98:f0:9f:2a:
                    14:e3:e6:27:03:f2:b5:fa
                P:   
                    00:9e:47:0c:bc:3a:98:7f:93:87:21:70:1d:5d:1c:
                    36:e4:e5:98:f6:7a:e0:55:d1:94:1b:59:66:ee:a1:
                    8b:e5:33:6f:08:ed:f5:90:c6:5f:d6:d3:f0:44:0d:
                    5c:e4:9e:aa:35:7d:1d:20:7f:6c:85:07:eb:bb:02:
                    ad:df:06:b2:87:fa:09:d4:dd:83:9f:d6:5a:6e:ef:
                    9d:c8:dc:0c:02:a0:0a:f9:a4:d2:f4:f5:7f:d2:cc:
                    13:cb:22:9f:95:fe:90:3f:9a:b6:f6:c5:b1:cd:46:
                    d7:4a:8e:6c:c8:3c:46:87:66:37:86:23:d3:65:fc:
                    e1:90:6a:75:b6:df:ee:75:79
                Q:   
                    00:95:f0:ca:00:c2:ad:ab:8f:12:dd:a0:63:51:a9:
                    40:04:ef:3a:ea:17
                G:   
                    00:8f:a4:b5:4d:31:cd:b7:d0:ac:25:7f:c3:24:f7:
                    7a:b8:c2:5e:f6:c5:95:7a:4c:3a:99:7f:c9:75:94:
                    79:05:63:46:3a:6e:d6:e8:45:6d:20:0d:3a:9c:94:
                    2d:71:c7:d4:ca:2a:cc:67:39:0f:4f:1e:b6:8b:55:
                    ad:2d:3b:b9:e9:6e:d5:4f:ea:7f:e1:ee:31:3e:bc:
                    ab:d3:87:d8:e7:33:c4:ba:e7:28:8a:1b:a6:a5:5e:
                    6d:e9:02:f1:24:ac:67:ae:01:04:e7:96:4a:a6:d6:
                    9d:a6:4d:f2:07:0c:b8:8c:3a:73:0d:af:6d:73:32:
                    d0:58:67:8f:70:e0:f8:2e:0c
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                5D:CF:36:67:BD:24:54:E1:53:76:41:C0:D1:16:4D:39:29:8F:7F:96
            X509v3 CRL Distribution Points: 
                0I0G....0...DistributionPoint@786.com.........0...DistributionPoint@786.com
            X509v3 Key Usage: critical
                Certificate Sign
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:2
            X509v3 Authority Key Identifier: 
..U.            0..X.......*.e.s#..&...o.....70..3.../0..+1.0...U....IN1.0
..U....serial1.0...U....AirportRoad1.0...U....ms1.0.U....Karnataka1.0
..U.*..Huawei1.0
..U.A..pseudo1
.....ipsiCA@huawei.com1 0..
..&...,d....SecurityTestTeam..xa#E.
    Signature Algorithm: dsaWithSHA1
         r:   
             41:c3:e9:aa:fb:74:43:8c:9d:f0:91:9d:f6:37:5d:
             8d:01:71:61:28
         s:   
             1a:7a:1f:62:cd:8f:41:09:17:e6:85:09:f6:0c:4d:
             f3:a9:21:06:9d
-----BEGIN CERTIFICATE-----
MIIGmDCCBligAwIBAgIFeGEjRZEwCQYHKoZIzjgEAzCCASsxCzAJBgNVBAYTAklO
MQ8wDQYDVQQKEwZIdWF3ZWkxDjAMBgNVBAsTBUhUSVBMMRQwEgYDVQQuEwtkblF1
YWxpZmllcjESMBAGA1UECBMJS2FybmF0YWthMREwDwYDVQQDEwhpcHNpUk9PVDEP
MA0GA1UEBRMGc2VyaWFsMRQwEgYDVQQHEwtBaXJwb3J0Um9hZDELMAkGA1UEDBMC
bXMxDDAKBgNVBAQTA0luYzEPMA0GA1UEKhMGSHVhd2VpMQwwCgYDVQQrEwNpbmkx
DzANBgNVBEETBnBzZXVkbzEKMAgGA1UELBMBMTEeMBwGCSqGSIb3DQEJARYPaXBz
aUBodWF3ZWkuY29tMSAwHgYKCZImiZPyLGQBGRYQU2VjdXJpdHlUZXN0VGVhbTAe
Fw0wNTA5MjYxMjAxMDNaFw0xNjA5MjYxMjAxMDRaMIIBKzELMAkGA1UEBhMCSU4x
DzANBgNVBAoTBkh1YXdlaTEOMAwGA1UECxMFSFRJUEwxFDASBgNVBC4TC2RuUXVh
bGlmaWVyMRIwEAYDVQQIEwlLYXJuYXRha2ExDzANBgNVBAMTBmlwc2lDQTEPMA0G
A1UEBRMGc2VyaWFsMRQwEgYDVQQHEwtBaXJwb3J0Um9hZDELMAkGA1UEDBMCbXMx
DDAKBgNVBAQTA0luYzEPMA0GA1UEKhMGSHVhd2VpMQwwCgYDVQQrEwNpbmkxDzAN
BgNVBEETBnBzZXVkbzEKMAgGA1UELBMBMTEgMB4GCSqGSIb3DQEJARYRaXBzaUNB
QGh1YXdlaS5jb20xIDAeBgoJkiaJk/IsZAEZFhBTZWN1cml0eVRlc3RUZWFtMIIB
tzCCASwGByqGSM44BAEwggEfAoGBAJ5HDLw6mH+ThyFwHV0cNuTlmPZ64FXRlBtZ
Zu6hi+Uzbwjt9ZDGX9bT8EQNXOSeqjV9HSB/bIUH67sCrd8Gsof6CdTdg5/WWm7v
ncjcDAKgCvmk0vT1f9LME8sin5X+kD+atvbFsc1G10qObMg8RodmN4Yj02X84ZBq
dbbf7nV5AhUAlfDKAMKtq48S3aBjUalABO866hcCgYEAj6S1TTHNt9CsJX/DJPd6
uMJe9sWVekw6mX/JdZR5BWNGOm7W6EVtIA06nJQtccfUyirMZzkPTx62i1WtLTu5
6W7VT+p/4e4xPryr04fY5zPEuucoihumpV5t6QLxJKxnrgEE55ZKptadpk3yBwy4
jDpzDa9tczLQWGePcOD4LgwDgYQAAoGAcfQVSg9f0Fr1iK7yuZanZJ7ImLITBr91
O+ZIKGOzsryqPuDUpr8SHCu3gplaVXmG41jjEZ21MikP/PXo73OUby3mWspzDefm
c3QMPDxfX53p3JFmN4/4kJU9l/EbkxDZ9C8xNYzp2bfLEDP8WfQGZFQJdGKY8J8q
FOPmJwPytfqjggIEMIICADAdBgNVHQ4EFgQUXc82Z70kVOFTdkHA0RZNOSmPf5Yw
UgYDVR0fBEswSTBHoB+gHTAbgRlEaXN0cmlidXRpb25Qb2ludEA3ODYuY29tgQUA
AgAAAKIdMBuBGURpc3RyaWJ1dGlvblBvaW50QDc4Ni5jb20wDgYDVR0PAQH/BAQD
AgIEMBIGA1UdEwEB/wQIMAYBAf8CAQIwggFlBgNVHSMEggFcMIIBWIAU2Oeq8JEq
qWWfcyPrtibRLs5v/xmhggE3MIIBM6SCAS8wggErMQswCQYDVQQGEwJJTjEPMA0G
A1UEChMGSHVhd2VpMQ4wDAYDVQQLEwVIVElQTDEUMBIGA1UELhMLZG5RdWFsaWZp
ZXIxEjAQBgNVBAgTCUthcm5hdGFrYTEPMA0GA1UEAxMGaXBzaUNBMQ8wDQYDVQQF
EwZzZXJpYWwxFDASBgNVBAcTC0FpcnBvcnRSb2FkMQswCQYDVQQMEwJtczEMMAoG
A1UEBBMDSW5jMQ8wDQYDVQQqEwZIdWF3ZWkxDDAKBgNVBCsTA2luaTEPMA0GA1UE
QRMGcHNldWRvMQowCAYDVQQsEwExMSAwHgYJKoZIhvcNAQkBFhFpcHNpQ0FAaHVh
d2VpLmNvbTEgMB4GCgmSJomT8ixkARkWEFNlY3VyaXR5VGVzdFRlYW2CBXhhI0WQ
MAkGByqGSM44BAMDLwAwLAIUQcPpqvt0Q4yd8JGd9jddjQFxYSgCFBp6H2LNj0EJ
F+aFCfYMTfOpIQad
-----END CERTIFICATE-----

**Comment by bernd-edlinger** [comment]
This cerificate is bogus.
for the CA the AKID should be equal to the SKID
but they are not equal.
And obviously this will stop working when we
fix the bug that makes OpenSSL accept that certificate.

**Comment by bernd-edlinger** [comment]
Of course RFC5280 does not require any AKID from the ROOT-CA,
because there is no trust relation to any authority except itsef.
The certificate is to be trusted unconditionally, but....

**Comment by bernd-edlinger** [comment]
And by the way, dsa and SHA1 are not considered safe choices for
ad ROOT CA.  That is probably the worst problem with this CA.
Please stop using that.

**Comment by Mengliuxx** [comment]
OK, I have stopped using it and used a new certificate
