### ISSUE TITLE
Why remove openssl1.0.2j and install 1.1.1g, ssh cant login to server? how to solve?

### ISSUE THREAD

**Issue by okayabc** [openssl/openssl#11692]

**Comment by richsalz** [comment]
Did you replace the system-provided OpenSSL?  If so, that was a bad mistake.

**Comment by okayabc** [comment]
I have executed rpm -e openssl1.0.2 and now can't ssh to server.
I try do an experiment because my service need libevent and mysqlclient.
libevent need libssl1.1 and mysqlclient need libssl1.0, so i try to remove openssl1.0 and compile mysqlclient as as to make mysqlclient use ssl1.1.
