### ISSUE TITLE
Building OpenSSL 3.0.0.aplha1 on Win32 fails ...

### ISSUE THREAD

**Issue by lllaffer** [openssl/openssl#11699]
I use to build OpenSSL on Win32 using Visual Studio Build Tools 2019 and ActivePerl 5.22.1.2201.

		perl Configure VC-WIN32 --prefix=z:\Build-OpenSSL-VC32-Release-DLL
		nmake

	This procedure works for OpenSSL 1.1.1g.

	The same procedure with OpenSSL 3.0.0.aplpha1 ends with:

	:
        "C:\Perl\bin\perl.exe" "-I." -Mconfigdata -Mconfigdata "util\dofile.pl" "-omakefile" "doc\man7\openssl_user_macros.pod.in" > doc\man7\openssl_user_macros.pod
        "C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe" /       
	depend && "C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe" /
                _build_sw

	Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
	Copyright (C) Microsoft Corporation.  All rights reserved.
	
	
	Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
	Copyright (C) Microsoft Corporation.  All rights reserved.
	
	        "C:\Perl\bin\perl.exe" "util\mkbuildinf.pl" ""cl" /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -D"L_ENDIA
	N" -D"OPENSSL_PIC"" "VC-WIN32" > crypto\buildinf.h
	        "cl"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -I "crypto" -I "." -I "include" -I "providers\common\i
	nclude" -I "providers\implementations\include" -I "crypto\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"C:\\Program Files\\C
	ommon Files\\SSL\"" -D"ENGINESDIR=\"Z:\\Build-OpenSSL-VC32-Release-DLL\\lib\\engines-3\"" -D"MODULESDIR=\"Z:\\Build-OpenSSL-VC32-Rel
	ease-DLL\\lib\\ossl-modules\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -
	D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG"   -DAES_ASM -DCMLL_ASM -DDES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DMD5_ASM -DOPENSSL_BN
	_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305
	_ASM -DRMD160_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto
	\cversion.c"
	cversion.c
	crypto\cversion.c(50): error C2143: syntax error: missing ';' before 'constant'
	crypto\cversion.c(50): error C2146: syntax error: missing ';' before identifier 'Apr'
	crypto\cversion.c(50): error C2065: 'Apr': undeclared identifier
	crypto\cversion.c(50): error C2143: syntax error: missing ';' before 'string'
	NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.E
	XE"' : return code '0x2'
	Stop.
	NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmak
	e.exe"' : return code '0x2'
	Stop.

	... ???

	On 1.1.1g this looks like this:

	:
	Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
	Copyright (C) Microsoft Corporation.  All rights reserved.
	
	        "C:\Perl\bin\perl.exe" "util\mkbuildinf.pl" "cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -D"L_ENDIAN"
	 -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_BN_ASM_PART_WORDS" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM
	_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"RMD160_ASM" -D"AESNI_ASM" -D"VPAES_ASM" -D"WHIRLPOOL_AS
	M" -D"GHASH_ASM" -D"ECP_NISTZ256_ASM" -D"POLY1305_ASM"" "VC-WIN32" > crypto\buildinf.h
	        cl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "." /I "include" /I "crypto" -D"L_ENDIAN" -D"OPENSSL_
	PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_BN_ASM_PART_WORDS" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_GF2m" -D"SH
	A1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"RMD160_ASM" -D"AESNI_ASM" -D"VPAES_ASM" -D"WHIRLPOOL_ASM" -D"GHASH_
	ASM" -D"ECP_NISTZ256_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -D"ENGINESDIR=\"Z:\\Build-OpenSSL
	-VC32-Release-DLL\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPR
	ECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  -c /Focrypto\cversion.obj "crypto\cversion.c"
	cversion.c
	        cl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "." /I "include" /I "crypto" -D"L_ENDIAN" -D"OPENSSL_
	PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_BN_ASM_PART_WORDS" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_GF2m" -D"SH
	A1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"RMD160_ASM" -D"AESNI_ASM" -D"VPAES_ASM" -D"WHIRLPOOL_ASM" -D"GHASH_
	ASM" -D"ECP_NISTZ256_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -D"ENGINESDIR=\"Z:\\Build-OpenSSL
	-VC32-Release-DLL\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPR
	ECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  /Zs /showIncludes "crypto\cversion.c" 2>&1 > crypto\c
	version.d
	        IF EXIST .manifest DEL /F /Q .manifest
	:

	... !!!

**Comment by mattcaswell** [comment]
This is a known issue in the alpha1 build (now fixed in the master branch). Please see the workaround procedure in the 3.0 notes here:

https://wiki.openssl.org/index.php/OpenSSL_3.0#Installation_and_Compilation_of_OpenSSL_3.0
