### ISSUE TITLE
SPM, swift package manager, support 

### ISSUE THREAD

**Issue by doozMen** [openssl/openssl#11701]
swift is usable in a variety of ways. Especially on embedded systems I foresee a future because of the high security features and inter operability with c. swift 5.1 does not support [spm](https://swift.org/package-manager) to use binary dependencies. Ware planning to support the https://github.com/swift-embedded initiative by adding bluetooth 5.0 support. We encountered an issue regarding NordicSemiconductors to drop support for SPM solely because [openssl does not support non binary additions to package managers.](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/commit/56ef0552a5fe42ee064fb465193ffd2d5aacc434). 

As an open initiative that openssl is I find it surprising that it does not offer support for package managers solely as a binary build. But maybe I can understand that. 

With swift 5.3 comming and [supporting binary dependencies](https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md) would it be possible to add SPM support [spm](https://swift.org/package-manager)?

**Comment by levitte** [comment]
With 1.1.0, we decided that we wouldn't do package managing beyond creating a source tarball. Simply put, we leave package managing to the diverse package managers out there. For example, it's up to Debian packagers to create the appropriate Debian packages, it's up to RPM managers to create RPM packagers.

Similarly, it's up to Swift managers to create Swift packages. I assume it's the same with creating those packages as it is elsewhere, with some additional files that can be managed separately from the openssl source...

**Comment by doozMen** [comment]
Thanks for the response. I can imagine it is up to them yes.
