### ISSUE TITLE
certConf_cb

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#11711]
OpenSSL doesn't use this style of capitalization.  It should be "certconf" or "cert_conf" not "certConf"

**Comment by levitte** [comment]
[ahem] Openssl is quite mixed re naming styles... Just sayin'

EVP_DigestSignInit...

**Comment by richsalz** [comment]
Can you find another one where the first letter of a multi-word thing is downcased?  Like I said, CertConf is better than initial lower-case.

Yes it has a mix of naming styles.  Don't add another.

**Comment by levitte** [comment]
I just grepped for it, to see what it is about (CMP). It's an ASN.1 field name, taken directly from RFC 4210, and I can understand why it was done this way, as it makes it easier to relate code directly to the standard. This isn't new, look at `struct rsa_pss_params_st` in `include/openssl/rsa.h` for an example that's been around for a while.

**Comment by levitte** [comment]
If we do make a policy on this, I think we do need to factor in the relationship with the standards that are put into code.

**Comment by mattcaswell** [comment]
Ping @DDvO. Do we need to do anything here? Adding this to the 3.0 beta1 mileston because it has an API impact if we make a change.

**Comment by DDvO** [comment]
I was not aware of this thread - good that @mattcaswell pinged me.

As mentioned during the contribution phase of the CMP chunks,
and as independently discovered by @levitte the camelCase of `certConf_cb` and various other such names
stems from the name conventions  in RFC 4210 etc. and have been retained for consistency with the standard.
So I suggest resolving this as  "not a bug" or "wont fix".

**Comment by mattcaswell** [comment]
Seems like a reasonable answer.

**Comment by slontis** [comment]
This sounds like a slippery slope to me.
I would prefer them to use the standard naming convention and then have a comment that ties it back to the standards.

**Comment by DDvO** [comment]
If the name `certConf_cb` is considered a bug then we have thousands of "bugs" in the code base 
where names do not follow the (incomplete and patrly not very clear) coding guideline rules.
See also #10725.

BTW, `util/check-format.pl` so far only does very little checking on variable names
(it just reports the graphically very confusing single-letter names `l`, `I`, and `O`).

**Comment by DDvO** [comment]
> This sounds like a slippery slope to me.
> I would prefer them to use the standard naming convention and then have a comment that ties it back to the standards.

IMO `certConf_cb` does not violate the present coding guideline - it says:

> **Except when otherwise required,** avoid mixed-case names.

**Comment by DDvO** [comment]
As mentioned there are many symbols in OpenSSL for which the same holds,
and just recently I came across several of them in `include/openssl/x590.h`:
```
int X509_CRL_set1_lastUpdate(X509_CRL *x, const ASN1_TIME *tm);
int X509_CRL_set1_nextUpdate(X509_CRL *x, const ASN1_TIME *tm);
const ASN1_TIME *X509_CRL_get0_lastUpdate(const X509_CRL *crl);
const ASN1_TIME *X509_CRL_get0_nextUpdate(const X509_CRL *crl);

int X509_set_serialNumber(X509 *x, ASN1_INTEGER *serial);
ASN1_INTEGER *X509_get_serialNumber(X509 *x);
const ASN1_INTEGER *X509_get0_serialNumber(const X509 *x);

const ASN1_TIME * X509_get0_notBefore(const X509 *x);
ASN1_TIME *X509_getm_notBefore(const X509 *x);
int X509_set1_notBefore(X509 *x, const ASN1_TIME *tm);
const ASN1_TIME *X509_get0_notAfter(const X509 *x);
```

**Comment by DDvO** [comment]
So @mattcaswell and/or @slontis, I suggest again closing this as a non-bug.

**Comment by richsalz** [comment]
I am going to close this.  If @slontis feels strongly then he should re-open it.)
