### ISSUE TITLE
Macros EVP_add_(cipher|digest)_alias are not documented

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#11715]
The function ``EVP_PKEY_asn1_add_alias`` is documented. But the macros ``EVP_add_cipher_alias`` and ``EVP_add_digest_alias`` are not documented. There have been around for a long time and I'd like to know if they are considered stable and support API.

### Background
Python uses slightly different default names for hashing algorithms. The names are mapping from e.g. ``sha3-256`` to valid Python identifier ``sha3_256``. I have to jump through some [annoying hoops](https://github.com/python/cpython/blob/21893fbb74e8fde2931fbed9b511e2a41362b1ab/Modules/_hashopenssl.c#L194-L245) to map from Python digest names to OpenSSL digest names. With ``EVP_add_digest_alias`` I would be able to register Python's aliases in the EVP digst LHASH lookup table. This would speed up and simplify our code, for example::

```
EVP_add_digest_alias(SN_sha3_224, "sha3_224");
EVP_add_digest_alias(SN_sha3_256, "sha3_256");
EVP_add_digest_alias(SN_sha3_384, "sha3_384");
EVP_add_digest_alias(SN_sha3_512, "sha3_512");
```

**Comment by tiran** [comment]
My PR https://github.com/python/cpython/pull/19880 replaces ``py_digest_by_name`` with ``EVP_add_digest_alias``

**Comment by mattcaswell** [comment]
> I'd like to know if they are considered stable and support API.

Yes, it is considered stable and supported API.

One word of caution is that it doesn't fit too well with the OpenSSL 3.0 way of doing things - so its unclear to me what its long term future might be. But, for now at least, there are no plans to deprecate it or remove this.

**Comment by nhorman** [comment]
asn1_add_alias is now documented, the other two functions are not.  Marking as a community issue for resolution

**Comment by paulidale** [comment]
These are internal macros and not really suitable for the Brave New Provider World.
Suggest we close this.

A PR that adds Python names to our providers would be considered.

**Comment by nhorman** [comment]
based on @paulidale comment, closing to keep our issue list sane
