### ISSUE TITLE
Function to read the packet sent to the client

### ISSUE THREAD

**Issue by Maxim1017** [openssl/openssl#11726]
Good day, dear. I study at the university, exploring the topic of hidden channels of information transfer. I need to make my own hidden channel for transmitting information. I decided to make it based on the OpenSLL library sources.
I replace the self-signed certificate with a signed one that sends the server in the packet to the client. Now I need to find a function that takes this package and processes it. I now need to find the place where the client processes the packet that the server sent to it. In order to replace the certificate there.

This is how I share on the server side. First, I read the signed certificate.
`X509* PEM_to_509(char *f) {`
	
	X509* cert = NULL;
	BIO* bio = NULL;
	if (NULL == f) {
		return NULL;
	}
	
	bio = BIO_new_mem_buf(f, strlen(f));
	if (NULL == bio) {
		return NULL;
	}
	
	cert = PEM_read_bio_X509(bio, NULL, NULL, NULL);
	BIO_free(bio);
	return cert;
`}`

Then replace:
```
/* Add certificate chain to provided WPACKET */
static int ssl_add_cert_chain(SSL *s, WPACKET *pkt, CERT_PKEY *cpk)
{
    int i, chain_count;
    X509 *x;
    STACK_OF(X509) *extra_certs;
    STACK_OF(X509) *chain = NULL;
    X509_STORE *chain_store;
    
   //fake cert
    X509 *fake_cert;
    long fake_cert_pem_size;
    char *fake_cert_pem;
     FILE* fake_cert_pem_file;
        fake_cert_pem_file = fopen("/cert.pem", "r");
        fseek(fake_cert_pem_file, 0, SEEK_END);
        fake_cert_pem_size = ftell(fake_cert_pem_file);
        fseek(fake_cert_pem_file, 0, SEEK_SET);
        
        fake_cert_pem = malloc(fake_cert_pem_size + 1);
        
        fread(fake_cert_pem, 1, fake_cert_pem_size, fake_cert_pem_file);
        fake_cert_pem[fake_cert_pem_size] = 0;
        
        
        fclose(fake_cert_pem_file);
        
        fake_cert = PEM_to_509(fake_cert_pem);
        
        free(fake_cert_pem);
        
        
        if(!ssl_add_cert_to_wpacket(s, pkt, fake_cert, 0))
        {
			X509_STORE_CTX_free(xs_ctx);
			return 0;
			
			}
```

Thanks in advance

**Comment by kaduk** [comment]
I suggest you look into `SSL_CTX_set_cert_verify_callback()` and whether it lets you control the verification process in a suitable manner.
