### ISSUE TITLE
OpenSSL parsed a certificate without error while ZCertificate reported serialization error.

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [openssl/openssl#11721]
OpenSSL v1.1.1 and Ubuntu 18.04.3 x64
OpenSSL v1.1.1f and Ubuntu 20.04 x64

The following OpenSSL command parsed the certificate in the attachment:
```
openssl x509 -in path/to/certificate_name -noout -text
```

OpenSSL parsed the certificate without any warning/error. But, ZCertificate reported "level=error msg="could not parse certificate: asn1: time did not serialize back to the original value and may be invalid: given \"20170123093000.1Z\", but serialized as \"20170123093000Z\""
[cert52.zip](https://github.com/openssl/openssl/files/4573525/cert52.zip)

**Comment by kaduk** [comment]
This seems to be intentional; see https://github.com/openssl/openssl/blob/b756626a3732869875c50f150bddacfbcac5a7ab/crypto/x509/x509_vfy.c#L1819-L1847

**Comment by richsalz** [comment]
yes, this is probably working as designed.

Zlint/Zcert is designed to very strict conformance, OpenSSL is designed to be more pragmatic.
