### ISSUE TITLE
ssl_cert_lookup_by_pkey() assumes the EVP_PKEY contains legacy internal key

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#11720]
There are two ways to deal with this:

- downgrade the input key (this should be a *temporary* measure)
- change it to deal with provider side internal keys as well (this should be the ultimate result, before the final 3.0 release)

Ref: https://github.com/openssl/openssl/issues/11549#issuecomment-623297414

**Comment by levitte** [comment]
@mattcaswell, I would like some input from you here

**Comment by mattcaswell** [comment]
> ssl_cert_lookup_by_pkey() assumes the EVP_PKEY contains legacy internal key

By this do you mean that it calls EVP_PKEY_id()? In practice all algorithms that we're ever going to use will exist as legacy algorithms. i.e. you can't just drop in an algorithm for use by a certificate that libssl has never heard of and expect it to work. To do that, its a level of refactoring beyond the scope of 3.0. So we should be able to make EVP_PKEY_id() work for all interesting algorithms - even if we've only got provider side keys.

**Comment by levitte** [comment]
There's the new related issue #11823 that points out the EVP_PKEY_id() response as well.

`ssl_cert_lookup_by_pkey()` should really be remade into using `EVP_PKEY_is_a()`

**Comment by mattcaswell** [comment]
Searching for `EVP_PKEY_id()` in libssl gives me 20 matches.

**Comment by levitte** [comment]
... and most of them probably succeed because we downgrade keys

**Comment by levitte** [comment]
Actually, I think I have a fix...

**Comment by levitte** [comment]
So, tentative fix in #11828.  @beldmit, @mouse07410, would you mind trying this out?

**Comment by beldmit** [comment]
Gost engine tests are passed.

**Comment by beldmit** [comment]
@levitte, could you please take a look at #11792 to enable GOST engine tests as a part of external tests?
