### ISSUE TITLE
Openssl - CAMELLIA ciphersuites in GCM mode

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#11729]
Hi,

Can someone clarify if openssl 1.1.1g version supports CAMELLIA ciphersuites in GCM mode.
Eg: TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384

Thanks in advance.

Regards,
Amal

**Comment by mattcaswell** [comment]
No, they are not supported.
