### ISSUE TITLE
How to specify @seed_sources at configure time? default seems to be OS, but I'd like to add RDCPU as well

### ISSUE THREAD

**Issue by cjolivier01** [openssl/openssl#11747]

**Comment by mspncp** [comment]
I assume you are asking for OpenSSL 1.1.1. The INSTALL file has some instructions:

https://github.com/openssl/openssl/blob/184b0f14173fd69120767d86227d1db3a4e60ec0/INSTALL#L233-L259

**Comment by mspncp** [comment]
Note that the entropy collection will be sequentual and stop as soon as it has gathered enough entropy. There is no such thing as mixing several entropy source. So just adding another entropy source to the list won't have the effect you might expect.

**Comment by cjolivier01** [comment]
thanks!
