### ISSUE TITLE
Error string format does not match documentation

### ISSUE THREAD

**Issue by jaimeebrown** [openssl/openssl#11743]
Error string format output by `ERR_print_errors` has changed from previous versions. Documentation still says:
```
 [pid]:error:[error code]:[library name]:[function name]:[reason string]:[filename]:[line]:[optional text message]
```
However, example output from master is:

```
00:47:4F:BB:77:7F:00:00:error:rsa routines:(unknown function):key size too small:../crypto/rsa/rsa_gen.c:94:
```
Either the format is incorrect, or documentation needs to be updated.

**Comment by levitte** [comment]
The format is indeed incorrect. I
