### ISSUE TITLE
openssl-1.0.2-stable failed building on windows

### ISSUE THREAD

**Issue by mayankessar** [openssl/openssl#1176]
Getting below issue on building OpenSSl-1.0.2 
1> perl crypto\sha\asm\sha1-586.pl win32 /MTd /Od -DDEBUG -D_DEBUG -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE >tmp32.dbg\sha1-586.asm
1> ml /nologo /Cp /coff /c /Cx /Zi /Fotmp32.dbg\sha1-586.obj tmp32.dbg\sha1-586.asm
1> Assembling: tmp32.dbg\sha1-586.asm
1>tmp32.dbg\sha1-586.asm(1427) : error A2070:invalid instruction operands
1>tmp32.dbg\sha1-586.asm(1571) : error A2070:invalid instruction operands
1>NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\ml.EXE"' : return code '0x1'
1>Stop.

Visual Studio 2008
Active Perl latest
NASM latest version

Can somebody tell me is there any specific changes required with NASM. Please help.

**Comment by mayankessar** [comment]
Integrated NASM into Visual Studio using following steps:-

1. First install nasm by running its installer
2. copy nasm.rules to c:\Program Files\Microsoft Visual Studio 2008\VC\VCProjectDefaults
3. Start Visual Studio 2008
4. go to Tools->Options->VC++ Directories
5. click on Show Directories for Executables
6. add C:\Program Files\NASM to the list of paths
7. Open a solution that you want to use NASM with
8. Right click on the project name and select Custom Build Rules
9. Check the box next to the NASM line
10. Add any .asm files to the project
11. click on build to test

Where exactly we will run ms\do_nasm when using Visual studio.?

Below is my configuration to run for 32 bit

md "$(OutDir)"
 cd "$(SolutionDir)\open\openssl-1.0.2h"
 perl Configure VC-WIN32
 perl util\mkfiles.pl >MINFO
 perl util\mk1mf.pl no-asm debug VC-WIN32 >ms\nt.mak
 perl util\mkdef.pl 32 libeay > ms\libeay32.def
 perl util\mkdef.pl 32 ssleay > ms\ssleay32.def
 del /s/q/f tmp32.dbg
 del /s/q/f out32.dbg
 del /s/q/f inc32
 rd /s /q inc32\openssl
 rd /s /q inc32
 ms\do_nasm.bat
 nmake -f ms\nt.mak tmp32.dbg
 nmake -f ms\nt.mak out32.dbg
 nmake -f ms\nt.mak inc32
 nmake -f ms\nt.mak inc32\openssl
 nmake -f ms\nt.mak banner
 nmake -f ms\nt.mak headers
 nmake -f ms\nt.mak lib

**Comment by levitte** [comment]
I'm noticing that it's `ml.EXE` complainint.  That's the Microsoft Assembler, not NASM.  Are you certain that `nasm.exe` is in a directory in your %PATH%?

**Comment by levitte** [comment]
Oh, no, I see what you're missing...  in you call of `mk1mf.pl`, you must have `nasm` as well among the command line arguments.  See `ms\do_nasm.bat` for examples.

**Comment by mattcaswell** [comment]
Yes, agreed, that is the problem. Your `mk1mf.pl` line above is wrong. Although I'm not sure why you don't just call ms\do_nasm.bat instead of the individual mkfiles/mk1mf/mkdef calls above.

**Comment by levitte** [comment]
Another thing to note is that you're giving `mk1mf.pl` the argument `no-asm`.  For that to work, you must give `Configure` the argument `no-asm` as well.

**Comment by mattcaswell** [comment]
Can this issue be closed now?

**Comment by mayankessar** [comment]
I still have issues, But after these changes some issues are reduced. So, please close itl. Thanks, for your help.

**Comment by mattcaswell** [comment]
Ok - closing.
