### ISSUE TITLE
Using engine ciphers regression

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#11763]
Fetching ciphers from engine is broken since 

9f2058611f7aec733d4a476f4f28c895d9e5667b is the first bad commit
commit 9f2058611f7aec733d4a476f4f28c895d9e5667b
Author: Shane Lontis <shane.lontis@oracle.com>
Date:   Tue May 5 16:51:32 2020 +1000

    Remove cipher table lookup from EVP_CipherInit_ex
    
    Reviewed-by: Richard Levitte <levitte@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/11731)

gost-engine grasshopper tests are failing with diagnostics

Encryption test for grasshopper ecb
00:52:A4:00:2D:7F:00:00:error:digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:307:Default library context, Algorithm (kuznyechik-ecb), Properties ()
00:52:A4:00:2D:7F:00:00:error:digital envelope routines:EVP_CipherInit_ex:initialization error:crypto/evp/evp_enc.c:176:
/home/beldmit/upstream/engine/test_context.c:69: OpenSSL internal error: EVP_CipherInit_ex(ctx, type, NULL, K, iv, enc)

**Comment by mattcaswell** [comment]
@slontis

**Comment by slontis** [comment]
@beldmit - Do you have any idea how this algorithm gets set up. The code I removed basically did a big switch statement on all the ciphers it knew about, if it wasnt one of these then it ran the legacy path. So somehow I need to detect this case now.

**Comment by beldmit** [comment]
This algorithm is registered via EVP_add_cipher.

**Comment by beldmit** [comment]
Oh, no, sorry. EVP_add_cipher is bypassed in this test. 

The EVP_CIPHER object used in this test is created in this way:
https://github.com/gost-engine/engine/blob/b9d014538053c2d0717a0029dee88694cc4e4ed7/gost_grasshopper_cipher.c#L987-L1005

**Comment by beldmit** [comment]
We've reimplemented the test. Now we don't just obtain the EVP_CIPHER object to run tests, but load the engine (that invokes EVP_add_cipher) and obtain it via the engine.

Here is the link to a previous (broken) state. 
https://github.com/gost-engine/engine/tree/b6181aefc8d1b76652c12b6da3c15321b069257d

If we think that direct creating the EVP_CIPHER without EVP_add_cipher is bad practice, the issue can be closed. Many thanks!
