### ISSUE TITLE
RSA keygen regression

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#11764]
beldmit@manul$ LD_LIBRARY_PATH=`pwd` apps/openssl genpkey  -algorithm rsa -pkeyopt rsa_keygen_bits:512 -out key.pem
Error generating key

beldmit@manul$ git bisect bad
5e77b79a8c47f0801f656cfccfcbaaa3ca1035b4 is the first bad commit
commit 5e77b79a8c47f0801f656cfccfcbaaa3ca1035b4
Author: Shane Lontis <shane.lontis@oracle.com>
Date:   Thu May 7 15:31:05 2020 +1000

    Remove gen_get_params & gen_gettable_params from keygen operation
    
    EVP_PKEY_CTX_gettable_params() was missing code for the keygen operation.
    After adding it it was noticed that it is probably not required for this type, so instead
    the gen_get_params and gen_gettable_params have been remnoved from the provider interface.
    gen_get_params was only implemented for ec to get the curve name. This seems redundant
    since normally you would set parameters into the keygen_init() and then generate a key.
    Normally you would expect to extract data from the key - not the object that we just set up
    to do the keygen.
    
    Added a simple settable and gettable test into a test that does keygen.
    
    Reviewed-by: Richard Levitte <levitte@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/11683)

**Comment by slontis** [comment]
It seems a bit strange to me that this commit would be causing the issue (ec keygen changed slightly - but not RSA)
If you are using the fips provider then it will be an issue because key lengths less than 2048 are not allowed.
I would suggest that a size of 512 should not be used anywhere.
See if PR #11765 does anything for you.

**Comment by beldmit** [comment]
Dear @slontis, the tests were written in ancient time :) 
And lack of diagnostics seems to be a separate problem.

**Comment by beldmit** [comment]
Works for the current master. Don't understand why :(

**Comment by beldmit** [comment]
@slontis many thanks anyway!
