### ISSUE TITLE
internal functions in .num files

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#1178]
Some functions are exported from crypto so they can be called from ssl.  Others are exported because we can't mark them not so.  the idea of adding a specific tag for internal functions. INTERNAL instead of EXISTS, perhaps? That should be fairly simple to do...

**Comment by richsalz** [comment]
Not a gating issue for 1.1.0 release IMO.

**Comment by kaduk** [comment]
In krb5 we have a similar case where symbols are exported from one shared object (e.g., libkrb5support) for use by another krb5 shared object, but are *not* intended for general public consumption.  In such cases, the symbols are identified by not being present in public header files or documentation.

In any case, I find it highly unlikely that we could agree on a way to do this that is compatible with the ABI/API stability policy, so I'll mark this for 1.2.0

**Comment by levitte** [comment]
It's the same with us, these internal symbols do not show in public headers.

**Comment by richsalz** [comment]
I'll go further:  as the OP I'm closing this.
