### ISSUE TITLE
Openssl 3.0 alpha QNX x86_64 - Issues running some tests

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#11784]
Running the tests on QNX x86_64 and after figuring out some of the changes compared to 1.1.1, I get this error for quite a few tests, others work without a problem. To run the tests, I just copy all the source folder after a build to a QNX target and run the tests from within that folder which contains all binaries and tests. 

I have to adjust the wrap.pl using EXE_SHELL because it kept insisting that it should be running ../../util/wrap.pl which is wrong if you run from the base of the srcdir or what is pointed to with SRCTOP.

> export SRCTOP=$(pwd); export BLDTOP=$(pwd); HARNESS_VERBOSE=1 EXE_SHELL="perl $(pwd)/util/wrap.pl" perl test/run_tests.pl test_fipsinstall
> 03-test_fipsinstall.t .. 
> The results of this test will end up in test-runs/test_fipsinstall
> Parameter to use fallback must be a directory, not a file at ../../configdata.pm line 28554.
> BEGIN failed--compilation aborted at ../../configdata.pm line 28554.
> Compilation failed in require at ../../Configurations/platform.pm line 8.
> BEGIN failed--compilation aborted at ../../Configurations/platform.pm line 8.
> Compilation failed in require at test/recipes/03-test_fipsinstall.t line 23.
> BEGIN failed--compilation aborted at test/recipes/03-test_fipsinstall.t line 23.
> Dubious, test returned 2 (wstat 512, 0x200)
> No subtests run 

That 28554 line is the fallback one in the middle of this grouping:

>         use lib '/Volumes/devel/qnx_repos/product/lib/openssl3/build/nto-x86_64-o/util/perl';
>         use OpenSSL::fallback '/Volumes/devel/qnx_repos/product/lib/openssl3/build/nto-x86_64-o/external/perl/MODULES.txt';
>         use OpenSSL::Template;

MODULES.txt contains only this line

> Text-Template-1.56/lib

Other test issues:

I also see these test failures, and TLS is enabled from the config data below so I'm not certain what is missing on the target

> 70-test_clienthello.t .............. skipped: No TLS/SSL protocols are supported by this OpenSSL build
> 70-test_recordlen.t ................ skipped: No TLS/SSL protocols are supported by this OpenSSL build
> 70-test_servername.t ............... skipped: No TLS/SSL protocols are supported by this OpenSSL build
> 70-test_sslcertstatus.t ............ skipped: test_sslcertstatus needs TLS enabled
> 70-test_sslextension.t ............. skipped: test_sslextension needs TLS enabled
> 70-test_sslmessages.t .............. skipped: test_sslmessages needs TLS enabled

Configuration

> $ perl configdata.pm --dump
> 
> Command line (with current working directory = .):
> 
>     perl ./Configure no-async no-capieng no-padlockeng --prefix=/usr nto-x86_64
> 
> Perl information:
> 
>     perl
>     5.18.4 for darwin-thread-multi-2level
> 
> Enabled features:
> 
>     aria
>     asm
>     autoalginit
>     autoerrinit
>     autoload-config
>     bf
>     blake2
>     camellia
>     cast
>     chacha
>     cmac
>     cmp
>     cms
>     comp
>     ct
>     deprecated
>     des
>     devcryptoeng
>     dgram
>     dh
>     dsa
>     dso
>     dtls
>     dynamic-engine
>     ec
>     ec2m
>     ecdh
>     ecdsa
>     engine
>     err
>     filenames
>     fips
>     gost
>     idea
>     legacy
>     makedepend
>     md4
>     mdc2
>     module
>     multiblock
>     nextprotoneg
>     pinshared
>     ocb
>     ocsp
>     pic
>     poly1305
>     posix-io
>     psk
>     rc2
>     rc4
>     rdrand
>     rfc3779
>     rmd160
>     scrypt
>     secure-memory
>     seed
>     shared
>     siphash
>     siv
>     sm2
>     sm3
>     sm4
>     sock
>     srp
>     srtp
>     sse2
>     ssl
>     static-engine
>     stdio
>     tests
>     threads
>     tls
>     ts
>     ui-console
>     whirlpool
>     tls1
>     tls1-method
>     tls1_1
>     tls1_1-method
>     tls1_2
>     tls1_2-method
>     tls1_3
>     dtls1
>     dtls1-method
>     dtls1_2
>     dtls1_2-method
> 
> Disabled features:
> 
>     afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
>     asan                [default]        OPENSSL_NO_ASAN
>     async               [option]         OPENSSL_NO_ASYNC
>     buildtest-c++       [default]        
>     capieng             [option]         OPENSSL_NO_CAPIENG
>     crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
>     ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
>     egd                 [default]        OPENSSL_NO_EGD
>     external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
>     fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
>     fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
>     ktls                [default]        OPENSSL_NO_KTLS
>     md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
>     msan                [default]        OPENSSL_NO_MSAN
>     padlockeng          [option]         OPENSSL_NO_PADLOCKENG
>     rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
>     sctp                [default]        OPENSSL_NO_SCTP
>     ssl-trace           [default]        OPENSSL_NO_SSL_TRACE
>     trace               [default]        OPENSSL_NO_TRACE
>     ubsan               [default]        OPENSSL_NO_UBSAN
>     unit-test           [default]        OPENSSL_NO_UNIT_TEST
>     uplink              [no uplink_arch] OPENSSL_NO_UPLINK
>     weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
>     zlib                [default]        
>     zlib-dynamic        [default]        
>     ssl3                [default]        OPENSSL_NO_SSL3
>     ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD
> 
> Config target attributes:
> 
>     AR => "ar",
>     ARFLAGS => "r",
>     CC => "gcc",
>     HASHBANGPERL => "/usr/bin/env perl",
>     RANLIB => "ranlib",
>     RC => "windres",
>     asm_arch => "x86_64",
>     bn_ops => "SIXTY_FOUR_BIT_LONG",
>     build_file => "Makefile",
>     build_scheme => [ "unified", "unix" ],
>     cflags => "-D__unix__ -DL_ENDIAN",
>     cppflags => "",
>     defines => [  ],
>     disable => [  ],
>     dso_scheme => "dlfcn",
>     enable => [ "devcryptoeng" ],
>     ex_libs => "-lsocket",
>     includes => [  ],
>     lflags => "",
>     lib_cflags => "",
>     lib_cppflags => "",
>     lib_defines => [ "OPENSSL_BUILDING_OPENSSL" ],
>     module_cflags => "-DOPENSSL_USE_NODELETE",
>     module_cxxflags => undef,
>     module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
>     perl_platform => "Unix",
>     perlasm_scheme => "elf",
>     shared_cflag => "-DOPENSSL_USE_NODELETE",
>     shared_defines => [  ],
>     shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
>     shared_rcflag => "",
>     shared_sonameflag => "-Wl,-soname=",
>     shared_target => "gnu-shared",
>     thread_defines => [  ],
>     thread_scheme => "pthreads",
>     unistd => "<unistd.h>",
> 
> Recorded environment:
> 
>     AR = x86_64-pc-nto-qnx7.2.0-ar
>     ARFLAGS = 
>     AS = 
>     ASFLAGS = 
>     BUILDFILE = 
>     CC = x86_64-pc-nto-qnx7.2.0-gcc
>     CFLAGS =  -O2 -Wall -frecord-gcc-switches -g
>     CPP = 
>     CPPDEFINES = 
>     CPPFLAGS =  -I/Volumes/devel/qnx_repos/stage/nto/usr/include -I/Volumes/devel/sdp/mainline/target/qnx7/usr/include  -D__USESRCVERSION
>     CPPINCLUDES = 
>     CROSS_COMPILE = 
>     CXX = x86_64-pc-nto-qnx7.2.0-g++
>     CXXFLAGS =  -frecord-gcc-switches -O2 -Wall -g
>     HASHBANGPERL = 
>     LD = 
>     LDFLAGS =  -L/Volumes/devel/qnx_repos/stage/nto/x86_64/lib -L/Volumes/devel/qnx_repos/stage/nto/x86_64/usr/lib -L/Volumes/devel/sdp/mainline/target/qnx7/x86_64/lib -L/Volumes/devel/sdp/mainline/target/qnx7/x86_64/usr/lib -Wl,-Map,install.map -Wl,--build-id=md5
>     LDLIBS = 
>     MT = 
>     MTFLAGS = 
>     OPENSSL_LOCAL_CONFIG_DIR = 
>     PERL = 
>     RANLIB = x86_64-pc-nto-qnx7.2.0-ranlib
>     RC = 
>     RCFLAGS = 
>     RM = 
>     WINDRES = 
>     __CNF_CFLAGS = 
>     __CNF_CPPDEFINES = 
>     __CNF_CPPFLAGS = 
>     __CNF_CPPINCLUDES = 
>     __CNF_CXXFLAGS = 
>     __CNF_LDFLAGS = 
>     __CNF_LDLIBS = 
> 
> Makevars:
> 
>     AR              = x86_64-pc-nto-qnx7.2.0-ar
>     ARFLAGS         = r
>     CC              = x86_64-pc-nto-qnx7.2.0-gcc
>     CFLAGS          =  -O2 -Wall -frecord-gcc-switches -g
>     CPPDEFINES      = 
>     CPPFLAGS        =  -I/Volumes/devel/qnx_repos/stage/nto/usr/include -I/Volumes/devel/sdp/mainline/target/qnx7/usr/include  -D__USESRCVERSION
>     CPPINCLUDES     = 
>     CXX             = x86_64-pc-nto-qnx7.2.0-g++
>     CXXFLAGS        =  -frecord-gcc-switches -O2 -Wall -g
>     HASHBANGPERL    = /usr/bin/env perl
>     LDFLAGS         =  -L/Volumes/devel/qnx_repos/stage/nto/x86_64/lib -L/Volumes/devel/qnx_repos/stage/nto/x86_64/usr/lib -L/Volumes/devel/sdp/mainline/target/qnx7/x86_64/lib -L/Volumes/devel/sdp/mainline/target/qnx7/x86_64/usr/lib -Wl,-Map,install.map -Wl,--build-id=md5
>     LDLIBS          = 
>     PERL            = perl
>     RANLIB          = x86_64-pc-nto-qnx7.2.0-ranlib
>     RC              = windres
>     RCFLAGS         = 
> 
> NOTE: These variables only represent the configuration view.  The build file
> template may have processed these variables further, please have a look at the
> build file for more exact data:
>     Makefile
> 
> build file:
> 
>     Makefile
> 
> build file templates:
> 
>     Configurations/common0.tmpl
>     Configurations/unix-Makefile.tmpl
>     Configurations/common.tmpl

**Comment by dlegaultbbry** [comment]
I just realized that I'm dumb =]

I just noticed that the paths are from my host system and won't work with the target one which doesn't contain the same paths as I have to transfer all the stuff to the target for testing. Is there a way to have it so that this fallback could search from SRCTOP too such that it would find that path on a target where all the source tree was copied over?

Could that also be the issue with not detecting tls being enabled since it's looking in the wrong spot for detecting if TLS is enabled?

Is there a better way to run the tests when doing a cross compile environment?

With 1.1.1, I basically just did what I'm trying now which is copy the whole built source tree on a QNX target and run the tests and it works fine.

**Comment by dlegaultbbry** [comment]
I found a workaround which I can get to run almost all tests successfully, but 2 are still failing because the 'perlapp' and 'perltest' commands do not honour the EXE_SHELL env variable which causes failures such as below.

'test_ca' and 'test_ssl_new' are the ones failing with the same error. Everything else is now 'ok'.

```
# export SRCTOP=$(pwd); export BLDTOP=$(pwd); EXE_SHELL="perl $(pwd)/util/wrap.pl" HARNESS_VERBOSE=1 perl test/run_tests.pl test_ca 
80-test_ca.t .. 
# The results of this test will end up in test-runs/test_ca
1..6
sh: ../../util/wrap.pl: No such file or directory
../../util/wrap.pl perl ../../apps/CA.pl -newca < /dev/null => 1
not ok 1 - creating CA structure

#   Failed test 'creating CA structure'
#   at test/recipes/80-test_ca.t line 29.
ok 2 # skip failed creating CA structure
ok 3 # skip failed creating CA structure
ok 4 # skip failed creating CA structure
ok 5 # skip failed creating CA structure
Using configuration from ../../test/CAss.cnf
ca: ./demoCA/newcerts is not a directory
./demoCA/newcerts: No such file or directory
ok 6 - Signing SM2 certificate request
# Looks like you failed 1 test of 6.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 
	(less 4 skipped subtests: 1 okay)

Test Summary Report
-------------------
80-test_ca.t (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=6,  3 wallclock secs ( 0.18 usr  0.00 sys +  2.48 cusr  0.02 csys =  2.68 CPU)
Result: FAIL
```

**Comment by dlegaultbbry** [comment]
Not being an expert in perl, I located the issue

perltest and perlapp do not add "exe_shell => $ENV{EXE_SHELL}" to the options causing them to eventually get the default in the cmd function through the __wrap_cmd.

After fixing that, I can get a pass on all tests.

**Comment by levitte** [comment]
PR welcome!

The tests aren't designed to be executed outside the build tree (which may or may not be the same as the source tree).  Interestingly enough, I was talking about the idea of an IVP (Installation Verification Procedure) with @mattcaswell a day or two ago.  Such a procedure should be designed to be much more independent of the source/build tree structure.
