### ISSUE TITLE
Build: duplicate -Mconfigdata when calling Perl on windows

### ISSUE THREAD

**Issue by FdaSilvaYY** [openssl/openssl#11786]
Extract of a Windows build output :
```
... 
    "C:\Perl\bin\perl.exe"  "-I." "-Idoc" -Mconfigdata -Mconfigdata -Mperlvars "util\dofile.pl" "-omakefile" "doc\man1\openssl-x509.pod.in" > doc\man1\opens
sl-x509.pod
    "C:\Perl\bin\perl.exe"  "-I." -Mconfigdata -Mconfigdata "util\dofile.pl" "-omakefile" "doc\man7\openssl_user_macros.pod.in" > doc\man7\openssl_user_macr
os.pod
    "C:\Perl\bin\perl.exe"  "-I." -Mconfigdata "util\dofile.pl" "-omakefile" "include\openssl\opensslv.h.in" > include\openssl\opensslv.h
    "C:\Perl\bin\perl.exe"  "-I." -Mconfigdata "util\dofile.pl" "-omakefile" "test\provider_internal_test.cnf.in" > test\provider_internal_test.cnf
    C:\VStudio12\VC\BIN\nmake.exe /                   depend && C:\VStudio12\VC\BIN\nmake.exe /                   _build_sw
```

There is a duplicated `-Mconfigdata -Mconfigdata` for most of perl calls.
Except the two last calls.

The duplicated comes from this line : 
https://github.com/openssl/openssl/blob/582311d7b469b4f57a29e9c3965c4d1eb4b477d4/Configurations/windows-makefile.tmpl#L644-L645

who adds to the second hard-coded one :
`"\$(PERL)" "-I\$(BLDDIR)" -MconfigData`

Only this second one remains alone in the last two Perl calls.

Ping @levitte : you can fix this faster than anyone ;)

**Comment by levitte** [comment]
This is purely cosmetic, as perl can handle using the same module twice.

However, sure, fix coming up!

**Comment by levitte** [comment]
See #11790
