### ISSUE TITLE
OpenSSL 1.1.1g build fails on Solaris 5.10 Sparc during MAKE at rm -f apps/openssl

### ISSUE THREAD

**Issue by rohitgaikwad09** [openssl/openssl#11799]
Can someone please have a look into this issue?

**Failure Log snapshot:**

    gcc -static-libgcc  -I. -Iinclude -Iapps -m64 -mcpu=ultrasparc -pthread -Wall -O3 -DNDEBUG  -MMD -MF apps/srp.d.tmp -MT apps/srp.o -c -o apps/srp.o apps/srp.c
    gcc: unrecognized option `-pthread'
    gcc -static-libgcc  -I. -Iinclude -Iapps -m64 -mcpu=ultrasparc -pthread -Wall -O3 -DNDEBUG  -MMD -MF apps/storeutl.d.tmp -MT apps/storeutl.o -c -o apps/storeutl.o apps/storeutl.c
    gcc: unrecognized option `-pthread'
    gcc -static-libgcc  -I. -Iinclude -Iapps -m64 -mcpu=ultrasparc -pthread -Wall -O3 -DNDEBUG  -MMD -MF apps/ts.d.tmp -MT apps/ts.o -c -o apps/ts.o apps/ts.c
    gcc: unrecognized option `-pthread'
    gcc -static-libgcc  -I. -Iinclude -Iapps -m64 -mcpu=ultrasparc -pthread -Wall -O3 -DNDEBUG  -MMD -MF apps/verify.d.tmp -MT apps/verify.o -c -o apps/verify.o apps/verify.c
    gcc: unrecognized option `-pthread'
    gcc -static-libgcc  -I. -Iinclude -Iapps -m64 -mcpu=ultrasparc -pthread -Wall -O3 -DNDEBUG  -MMD -MF apps/version.d.tmp -MT apps/version.o -c -o apps/version.o apps/version.c
    gcc: unrecognized option `-pthread'
    gcc -static-libgcc  -I. -Iinclude -Iapps -m64 -mcpu=ultrasparc -pthread -Wall -O3 -DNDEBUG  -MMD -MF apps/x509.d.tmp -MT apps/x509.o -c -o apps/x509.o apps/x509.c
    gcc: unrecognized option `-pthread'
       rm -f apps/openssl
    ${LDCMD:-gcc -static-libgcc} -m64 -mcpu=ultrasparc -pthread -Wall -O3 -L.   \
            -o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
             apps/libapps.a -lssl -lcrypto -lsocket -lnsl -ldl -pthread
    /bin/sh: bad substitution
    gmake[1]: *** [apps/openssl] Error 1
    gmake[1]: Leaving directory `/mnt/disk1/runtime/apacheBuild/SunOS/sun4/openssl-1.1.1g'
    gmake: *** [all] Error 2
bash-3.2$

**Snapshot of build script used:**

    #!/bin/sh
    
    set -e
    
    #build expat
    if [ "${NEED_EXPAT}" = 1 ] && [ "${SKIP_EXPAT}" != 1 ]; then
       rm -rf $EXPAT_ROOT
       EXPAT_FILENAME=`basename ../expat-* .gz`
       cp -f $SCRIPT_DIR/../$EXPAT_FILENAME.gz $BUILD_SRC_ROOT
       EXPAT_SRCDIR=$BUILD_SRC_ROOT/`basename $EXPAT_FILENAME .tar`
       rm -rf $EXPAT_SRCDIR
       (cd $BUILD_SRC_ROOT; gzip -dc $EXPAT_FILENAME.gz | $TAR -xf -)
       cd $EXPAT_SRCDIR
    
       $MAKE distclean || true
       AR=$AR NM=$NM STRIP=$STRIP CC="$CC" CFLAGS="$CFLAGS" CONFIG_SHELL="$CONFIG_SHELL" ./configure $EXPAT_CONFIG_PARAMS
       $MAKE
       $MAKE install
       cp README.md $EXPAT_ROOT
       (cd $APACHE_ROOT; zip -r $BUILD_BUNDLE_DIR/$EXPAT_OVERLAY_FILE expat)
       cd $SCRIPT_DIR
    fi
    
    if [ "${NEED_SSL}" = 1 ] && [ "${SKIP_SSL}" != 1 ]; then
       rm -rf $OPENSSL_ROOT
       OPENSSL_FILENAME=`basename ../openssl*.tar.gz .gz`
       cp -f $SCRIPT_DIR/../$OPENSSL_FILENAME.gz $BUILD_SRC_ROOT
       OPENSSL_SRCDIR=$BUILD_SRC_ROOT/`basename $OPENSSL_FILENAME .tar`
       rm -rf $OPENSSL_SRCDIR
       (cd $BUILD_SRC_ROOT; gzip -dc $OPENSSL_FILENAME.gz | $TAR -xf -)
       cd $OPENSSL_SRCDIR
       $MAKE clean || true
       CC=$CC ./Configure $OPENSSL_TARGET $OPENSSL_CONFIG_PARAMS #CC=gcc -static-libgcc ./Configure solaris64-sparcv9-gcc --prefix=/MYAPACHEBUILD/openssl threads shared
       $MAKE
       $MAKE test
       $MAKE install
       # copy documentation files to apache bundle
       cp LICENSE README NEWS $OPENSSL_ROOT
    fi

**bash-3.2$ perl configdata.pm --dump**

```
Command line (with current working directory = .):

    /mnt/disk1/runtime/perl-5.30.2.installed/bin/perl ./Configure solaris64-sparcv9-gcc --prefix=/MYAPACHEBUILD/openssl threads shared

Perl information:

    /mnt/disk1/runtime/perl-5.30.2.installed/bin/perl
    5.30.2 for sun4-solaris-thread-multi

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c\+\+
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [not-linux] OPENSSL_NO_AFALGENG
    asan                    [default]   OPENSSL_NO_ASAN
    crypto-mdebug           [default]   OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]   OPENSSL_NO_EGD
    external-tests          [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]   OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]   OPENSSL_NO_HEARTBEATS
    md2                     [default]   OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]   OPENSSL_NO_MSAN
    rc5                     [default]   OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]   OPENSSL_NO_SCTP
    ssl-trace               [default]   OPENSSL_NO_SSL_TRACE
    ubsan                   [default]   OPENSSL_NO_UBSAN
    unit-test               [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]
    zlib-dynamic            [default]
    ssl3                    [default]   OPENSSL_NO_SSL3
    ssl3-method             [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c aes-sparcv9.S aest4-sparcv9.S aesfx-sparcv9.S",
    aes_obj => "aes_core.o aes_cbc.o aes-sparcv9.o aest4-sparcv9.o aesfx-sparcv9.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "asm/sparcv8plus.S sparcv9-mont.S sparcv9a-mont.S vis3-mont.S sparct4-mont.S sparcv9-gf2m.S",
    bn_obj => "asm/sparcv8plus.o sparcv9-mont.o sparcv9a-mont.o vis3-mont.o sparct4-mont.o sparcv9-gf2m.o",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-m64 -mcpu=ultrasparc -pthread",
    chacha_asm_src => "chacha_enc.c",
    chacha_obj => "chacha_enc.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c cmllt4-sparcv9.S",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o cmllt4-sparcv9.o",
    cppflags => "",
    cpuid_asm_src => "sparcv9cap.c sparccpuid.S",
    cpuid_obj => "sparcv9cap.o sparccpuid.o",
    defines => [  ],
    des_asm_src => "des_enc-sparc.S fcrypt_b.c dest4-sparcv9.S",
    des_obj => "des_enc-sparc.o fcrypt_b.o dest4-sparcv9.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-sparcv9.S",
    ec_obj => "ecp_nistz256.o ecp_nistz256-sparcv9.o",
    enable => [  ],
    ex_libs => "-lsocket -lnsl -ldl -pthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DFILIO_H -DB_ENDIAN -DBN_DIV2W",
    lib_defines => [  ],
    md5_asm_src => "md5-sparcv9.S",
    md5_obj => "md5-sparcv9.o",
    modes_asm_src => "ghash-sparcv9.S",
    modes_obj => "ghash-sparcv9.o",
    module_cflags => "-fPIC",
    module_cxxflags => "",
    module_ldflags => "-shared -Wl,-Bsymbolic",
    multilib => "/64",
    padlock_asm_src => "",
    padlock_obj => "",
    perlasm_scheme => "void",
    poly1305_asm_src => "poly1305-sparcv9.S",
    poly1305_obj => "poly1305-sparcv9.o",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    sha1_asm_src => "sha1-sparcv9.S sha256-sparcv9.S sha512-sparcv9.S",
    sha1_obj => "sha1-sparcv9.o sha256-sparcv9.o sha512-sparcv9.o",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,-M,",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-h,",
    shared_target => "self",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC = gcc -static-libgcc
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = ar
    ARFLAGS         = r
    CC              = gcc -static-libgcc
    CFLAGS          = -Wall -O3
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          =
    PERL            = /mnt/disk1/runtime/perl-5.30.2.installed/bin/perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl
bash-3.2$
```

_Same error occurs with OpenSSL 1.1.1e & 1.1.1f._

**Comment by levitte** [comment]
Would you mind telling us the result of this?

```
gcc -v
```

```
echo $FOO
echo ${FOO:-bar}
```

**Comment by levitte** [comment]
The `-pthread` issue should be resolved by configuring OpenSSL to build without thread support.  That's done by adding `no-threads` to your Configure command line.

**Comment by rohitgaikwad09** [comment]
Hi levitte,

Please see the below response:
```
$ gcc -v
Reading specs from /usr/sfw/lib/gcc/sparc-sun-solaris2.10/3.4.3/specs
Configured with: /sfw10/builds/build/sfw10-patch/usr/src/cmd/gcc/gcc-3.4.3/configure --prefix=/usr/sfw --with-as=/usr/ccs/bin/as --without-gnu-as --with-ld=/usr/ccs/bin/ld --without-gnu-ld --enable-languages=c,c++ --enable-shared
Thread model: posix
gcc version 3.4.3 (csl-sol210-3_4-branch+sol_rpath)
$
```

Thanks,
           --Rohit

**Comment by levitte** [comment]
You use a very old /bin/sh which isn't POSIX compliant.  I suggest telling `make` to use bash as a shell.  `which bash` will tell you the exact path.

```
make SHELL=/PATH/TO/bash
```

**Comment by rohitgaikwad09** [comment]
Thanks a lot levitte. 

Now, I'm getting clock_gettime error as below with _make SHELL changes_:

    gcc: unrecognized option `-pthread'
    rm -f apps/openssl
    ${LDCMD:-gcc -static-libgcc} -m64 -mcpu=ultrasparc -pthread -Wall -O3 -L.   \
            -o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
             apps/libapps.a -lssl -lcrypto -lsocket -lnsl -ldl -pthread
    gcc: unrecognized option `-pthread'
    gcc: unrecognized option `-pthread'
    ld: warning: relocation warning: R_SPARC_COPY: file ./libcrypto.so: symbol PBEPARAM_it: relocation bound to a symbol with STV_PROTECTED visibility
    ld: warning: relocation warning: R_SPARC_COPY: file ./libcrypto.so: symbol PBE2PARAM_it: relocation bound to a symbol with STV_PROTECTED visibility
    ld: warning: relocation warning: R_SPARC_COPY: file ./libcrypto.so: symbol PBKDF2PARAM_it: relocation bound to a symbol with STV_PROTECTED visibility
    ld: warning: relocation warning: R_SPARC_COPY: file ./libcrypto.so: symbol SCRYPT_PARAMS_it: relocation bound to a symbol with STV_PROTECTED visibility
    Undefined                       first referenced
     symbol                             in file
    clock_gettime                       ./libcrypto.so
    ld: fatal: symbol referencing errors. No output written to apps/openssl
    collect2: ld returned 1 exit status
    gmake[1]: *** [apps/openssl] Error 1
    gmake[1]: Leaving directory `/mnt/disk1/runtime/apacheBuild/SunOS/sun4/openssl-1.1.1g'
    gmake: *** [all] Error 2
    $

Above error is similar to already reported issue: https://github.com/openssl/openssl/issues/6333 
In this the MAKE file needs to be manually edited. I also want to know that whether a fix will be made for #6333 so that manual editing is not required.

Thanks,
           --Rohit

**Comment by levitte** [comment]
Newer gcc versions don't understand `-pthreads` (with s), and since all that's mentioned in #6333 is gravely outdated, it's unlikely that there will be a sane fix for those issues.

But hey, if someone can solve the problem in a sane way, PR welcome!

**Comment by rohitgaikwad09** [comment]
Now, MAKE is working fine _MAKE SHELL & https://github.com/openssl/openssl/issues/6333_ changes.

There is another issue https://github.com/openssl/openssl/issues/11801 facing for Solaris i86pc, can you please 've a look into it.

I'm closing this issue.
