### ISSUE TITLE
Openssl  load ca from memory, but it does not  work

### ISSUE THREAD

**Issue by kongxa** [openssl/openssl#11791]
On linux, below code is ok
    if (SSL_CTX_load_verify_locations(m_ssl_ctx, m_ca_cert, NULL) == 0 ) {//here m_ca_cert is file path
        printf("SSL_CTX_load_verify_locations error\n");
        return false;
    }

But, on android, i can not get "ca path", so i will load ca from memory as follows:
    BIO * cbio = BIO_new_mem_buf(m_ca_cert, strlen(m_ca_cert));//here m_ca_cert is content of ca file
    X509* cert = NULL;
    PEM_read_bio_X509(cbio, &cert, 0, NULL);//d2i_X509_bio
    if (NULL == cert)
    {
        printf("PEM_read_bio_X509 error.\n");
        return false;
    }
    X509_STORE *certS = SSL_CTX_get_cert_store(m_ssl_ctx);
    if (NULL == certS) {
        printf("SSL_CTX_get_cert_store error.\n");
        return false;
    }
    if (!X509_STORE_add_cert(certS, cert)) {
        unsigned long error = ERR_peek_last_error();
         printf("SSL_CTX_get_cert_store error:%d.\n", error);
        return false;
    }
    X509_free(cert);
    BIO_free(cbio);
Everything is ok, but certificate authentication failed.

X509_STORE_add_cert and SSL_CTX_load_verify_locations has some differences in my code? How to use X509_STORE_add_cert???

**Comment by kongxa** [comment]
openssl version:1.1.1d

**Comment by kongxa** [comment]
I find the issue. In my ca file, there are two certificates, PEM_read_bio_X509 need called one more, just like this:
    X509_STORE *certS = SSL_CTX_get_cert_store(m_ssl_ctx);
    if (NULL == certS) {
        printf("SSL_CTX_get_cert_store error.\n");
        return false;
    }

    printf(" m_ca_cert:%s\n", m_ca_cert);
    BIO * cbio = BIO_new_mem_buf(m_ca_cert, strlen(m_ca_cert));
    X509* cert = NULL;
    for (int i = 0; ; i++) {
        PEM_read_bio_X509(cbio, &cert, 0, NULL);//d2i_X509_bio
        if (NULL == cert)
        {
            printf("PEM_read_bio_X509 error.\n");
            if (0 == i)  return false;

            break;
        }
        if (!X509_STORE_add_cert(certS, cert)) {
             unsigned long error = ERR_peek_last_error();
             printf("SSL_CTX_get_cert_store error:%d.\n", error);
             return false;
         }

         X509_free(cert);

**Comment by gorkemhacioglu** [comment]
You are a lifesaver. My CA .pem file also contains lots of certificates. I never tought of looping in my CA. Thank you very much @kongxa
