### ISSUE TITLE
DES_string_to_*() too wide variable scope

### ISSUE THREAD

**Issue by Dmitry-Me** [openssl/openssl#1180]
This was found with Cppcheck.

`DES_string_to_2keys()` and `DES_string_to_key()` inside `crypto/des/str2key.c` have this declaration:

    register unsigned char j;

at top level. The variable is only used depending on preprocessor symbols. It is only used inside in a single for-loop in each function and the values are retained between the loop iterations. It is therefore clearer to have the variable declared inside the for-loop body so that it's scope is minimized and also it's eliminated together with the loop depending on preprocessor symbols.

**Comment by richsalz** [comment]
fixed with 56989dcd0e208dcad204e85367a20fab2a45e2f8
