### ISSUE TITLE
Im not sure the best place to report this

### ISSUE THREAD

**Issue by JMC-PK** [openssl/openssl#11817]
The https://www.openssl.org/news/changelog.html page is missing the release notes for 1.1.1 (f) and (g). It is still showing (e) as the latest release for the 1.1.1 branch.

**Comment by levitte** [comment]
Here are snippets of that page, for clarification (emphasis mine):

> This is the changelog for the **master branch**, the one that is currently in active development. 
> ...
> For **other branches**, the changelogs are distributed with the source, but are also available here:
> 
> - [1.1.1](https://www.openssl.org/news/cl111.txt)

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4  dev, barring further input
