### ISSUE TITLE
Interface repeated declared

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#11818]
https://github.com/openssl/openssl/blob/63f1883dca7a42949e8b9db5b035c17fc160f998/crypto/crmf/crmf_local.h#L107-L111

https://github.com/openssl/openssl/blob/63f1883dca7a42949e8b9db5b035c17fc160f998/crypto/cmp/cmp_local.h#L281-L286

Hi，@DDvO  The  file  'crmf_local.h line' 111 and The file 'cmf_local.h line 286' is repeated declaration.

**Comment by levitte** [comment]
That looks like a copy-n-paste mistake...  line 286 in `cmp_local.h` should be changed to:

``` C
DECLARE_ASN1_DUP_FUNCTION(OSSL_CMP_PKISI) 
```

... or perhaps omitted.

**Comment by DDvO** [comment]
Right, this must have been a copy&paste error,
and ` DECLARE_ASN1_DUP_FUNCTION(OSSL_CRMF_CERTID)` can be dropped.
`DECLARE_ASN1_DUP_FUNCTION(OSSL_CMP_PKISI)` is already part of `cmp.h`.

**Comment by levitte** [comment]
PR welcome! :wink:

**Comment by DDvO** [comment]
I just tried removing `DECLARE_ASN1_DUP_FUNCTION(OSSL_CRMF_CERTID)` from `cmp_local.h` but found that is needed by `cmp_msg.c`. 
So although the decl looks odd, it is neither a needless duplication nor a copy&paste mistake.

An alternative would be to remove the decl from both internal headers and place it in `crmf.h`, but then `OSSL_CRMF_CERTID` would be public, which is not really needed.

My suggestion is to close this issue.

**Comment by levitte** [comment]
> An alternative would be to remove the decl from both internal headers and place it in `crmf.h`, but then `OSSL_CRMF_CERTID` would be public, which is not really needed.

That depends on what `crmf.h` you're talking about.  You could have one in `include/crypto`, those are generally only shared by libcrypto code.

**Comment by t8m** [comment]
But OSSL_CRMF_CERTID as opaque type is already public. For the dup function declaration it does not need to be non-opaque and I do not see anything wrong with having the dup function public as you already have other ASN1 functions for it public.

Or you could put the dup function declaration into some common non-public header in include/crypto.

**Comment by DDvO** [comment]
Good point that it is consequential to export `OSSL_CRMF_CERTID_dup`.
It does not really hurt and could be of help for other uses of CRMF.
Done in #11911.
