### ISSUE TITLE
Intermittent ssl errors and data corruption without OPENSSL_ia32cap

### ISSUE THREAD

**Issue by aalejandro** [openssl/openssl#11812]
I observed intermittent ssl problems including data corruption of files when downloading thru
https.

For example:
`
root at oasis:~#  curl -o o https://www.google.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (35) error:1408F119:SSL routines:ssl3_get_record:decryption
failed or bad record mac
root at oasis:~#
`

If I run: OPENSSL_ia32cap="~0x200000200000000" curl -o o https://www.google.com
The problem goes away and I can download files without corruption.

I tried on 3 different Linux distributions with same results: Unraid, Slax Live and Debian Buster 10.

System CPU: AMD Ryzen 5 3600X
Motherboard: AsRock X470D4U
RAM: 2 x DIMM CT16G4DFD8266

On Unraid this is the software version:
root@oasis:~# curl -V
curl 7.67.0 (x86_64-pc-linux-gnu) libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.1.1) libssh2/1.9.0 nghttp2/1.40.0

**Comment by kaduk** [comment]
Do you need to clear both bits in order to resolve the issue or is just one sufficient?
A packet capture with session keys logged might help to get a reproducing scenario, or we may end up trying to fuzz the relevant assembly module(s).

**Comment by aalejandro** [comment]
I am not sure I understand your bits question but if you send me the command with only one bit I can re-test for sure.

I can also take a packet packet, would a simple tcpdump -s0 work?

Also in case this helps, this is openssl connect -debug when the errors happens: https://termbin.com/5dh0

**Comment by kroeckx** [comment]
> If I run: OPENSSL_ia32cap="~0x200000200000000" curl -o o https://www.google.com

So you turned off those:
       bit #33 denoting availability of PCLMULQDQ instruction;
       bit #57 denoting AES-NI instruction set extension;

To only turn one of those bits of, use:
OPENSSL_ia32cap="~0x200000000000000"
OPENSSL_ia32cap="~0x000000200000000"

Can you post /proc/cpuinfo (for just the first processor)?

Have you installed the latest bios / microcode update?

**Comment by aalejandro** [comment]
I tried with each bit turned off and it still fails.

I have updated the motherboard to latest, yes. I also tried to downgrade, same results.

CPUINFO:

`root@oasis:~# cat /proc/cpuinfo |more
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 113
model name      : AMD Ryzen 5 3600X 6-Core Processor
stepping        : 0
microcode       : 0x8701012
cpu MHz         : 3994.222
cache size      : 512 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsa
ve avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_
ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 7585.81
TLB size        : 3072 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]`

**Comment by bernd-edlinger** [comment]
Can you please run the test suite, are there already there failures in the self-tests ?

**Comment by aalejandro** [comment]
I am not an expert but just to be clear I just need to download the sources, compile and then run  make tests?

**Comment by bernd-edlinger** [comment]
You need a C compiler first : -)
then you download the sources,
then cd source-dir call: ./config
then call: make
then call: make test
do not call: make install (but if you do on your own risk)
additionally you should try the compiled "openssl s_client"
thus: ./util/shlib-wrap.sh apps/openssl s_client
would be interesting if that has the same issues.

**Comment by aalejandro** [comment]
I was able to do the tests however I now believe this gotta be a hardware problem. The test runs good for most of the time and then fails 1 out of 50 or more tests. When it fails its in a random place, not always the same failure.

Just in case the error is here: https://pastebin.com/GRP0Z7zK

I will troubleshoot the hardware by replacing, sorry for the noise folks and thanks!

**Comment by bernd-edlinger** [comment]
Make a memory test  first

**Comment by bernd-edlinger** [comment]
I mean in the grub boot loader there is a memory test if may run for hours.

**Comment by aalejandro** [comment]
Memtest then find anything but Prime5 just crashed. I will close this now so it all points to hardware problems. Thanks all.
