### ISSUE TITLE
Malformed code because of missing brace

### ISSUE THREAD

**Issue by Dmitry-Me** [openssl/openssl#1181]
This was found with Cppcheck

`engines\e_chil.c` has `hwcrhk_ctrl()` which has this code

    case ENGINE_CTRL_SET_LOGSTREAM:
        {
            /* WHATEVER*/
            if (BIO_up_ref(bio)
                logstream = bio;

The second closing brace is missing in `BIO_up_ref()` call.

**Comment by richsalz** [comment]
fixed with 56989dcd0e208dcad204e85367a20fab2a45e2f8
