### ISSUE TITLE
Travis notoriously fails for s390x with: No space left on device

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#11810]
Recently I tend to get on each push a Travis CI failure on the s390x build, with output like this:
https://travis-ci.org/github/openssl/openssl/jobs/686482210
with various  lines containing `No space left on device`.

**Comment by levitte** [comment]
It looks like this isn't an issue any more...

**Comment by DDvO** [comment]
The issue is not really solved - just ran into it again: https://travis-ci.org/github/openssl/openssl/jobs/687354053

**Comment by levitte** [comment]
Ok.  However, that's nothing that *we* can "resolve", other than noting that there are intermittent failures there that aren't relevant to us.  If that happens for a longer period, we'll have to decide if it's worth keeping that job.  In my opinion, we should be a little more patient, though.

**Comment by t8m** [comment]
We could mark the build with allow_failures

**Comment by DDvO** [comment]
It's just confusing and annoying to keep track whether a PR looks bad just because of that technical issue.

I'd assume that someone should be able to clean up or extend space on whatever machine that is.

**Comment by t8m** [comment]
I've e-mailed travis-ci support, but I am not holding my breath for the fix. Unless this is resolved by Monday, I'll open a PR with marking the build wit allow_failures.

**Comment by DDvO** [comment]
Thanks @t8m.
This issue seems to be fixed already for a couple of weeks, thus closing it.
