### ISSUE TITLE
OpenSSL 1.1.1 TLS 1.3 performance is slower than TLS 1.2 performance

### ISSUE THREAD

**Issue by okudayukiko** [openssl/openssl#11811]
OpenSSL 1.1.1 TLS 1.3 performance is slower than TLS 1.2 performance, include applications that use OpenSSL library such as nginx and haproxy.

**Comment by okudayukiko** [comment]
Test platform: Ubuntu 20.04
Test command:
`openssl s_server -tls1_3 -port 443 -HTTP -cert /path/to/crt.pem -key /path/to/key.pem`
`openssl s_server -tls1_2 -port 443 -HTTP -cert /path/to/crt.pem -key /path/to/key.pem`
`gnutls-serv -p 443 --x509certfile=/path/to/cert.pem --x509keyfile=/path/to/key.pem --http`
`gnutls-serv -p 443 --x509certfile=/path/to/cert.pem --x509keyfile=/path/to/key.pem --priority=NORMAL:-VERS-TLS1.3 --http`
`openssl s_time -connect localhost:443`

**Comment by richsalz** [comment]
They are different protocols, and TLS 1.3 encrypts more, so it is not surprising.
