### ISSUE TITLE
SHA3-512 Digest output is shorten then the desired length

### ISSUE THREAD

**Issue by odingo** [openssl/openssl#11829]
My code like this:
`

    MD_size = EVP_MD_size(EVP_sha3_512());

    printf("size is %0d\n", MD_size);

	if((mdctx = EVP_MD_CTX_create()) == NULL)

		handleErrors(__LINE__);

	if(1 != EVP_DigestInit_ex(mdctx, f2sha(), NULL))

		handleErrors(__LINE__);

	if(1 != EVP_DigestUpdate(mdctx, message, message_len))

		handleErrors(__LINE__);

	if((*digest = (unsigned char *)OPENSSL_malloc(MD_size)) == NULL)

		handleErrors(__LINE__);

	if(1 != EVP_DigestFinal_ex(mdctx, *digest, digest_len))

	    	handleErrors(__LINE__);

    printf("digest len is %0d, digest_len is %0d\n", strlen(*digest), *digest_len);

	EVP_MD_CTX_destroy(mdctx);
`

the MD_size is 64, the digest_len is 64, they are all correct.
But the strlen of *digest is 49, I thought it should be 64 as well.
The same issue also happens with the SHAKE-128/256 algorithms.

**pls help! thx!**

**Comment by beldmit** [comment]
You get binary data. strlen is not relevant for them.

**Comment by mattcaswell** [comment]
`strlen` is a function that tells you the length of a printable string. It scans the string looking for the terminating `\0` character that you get at the end of printable strings in C. Digests are binary data. They are *not* printable strings. The digest itself may contain the '\0' character in the middle of it. You cannot use `strlen` on binary data.

**Comment by odingo** [comment]
I'm write these code and import the code to a systemverilog bench via 'import DPI-C'
And the systemverilog only gets the first 49 bytes which is annoying me.
Sorry, guys, I know it's maybe fay away from the openssl things.
Thank you, I'll close this issue.
