### ISSUE TITLE
Legacy EVP_PKEY_DHX keys don't work with providers

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11827]
If you have a legacy EVP_PKEY_DHX key it cannot be exported to a provider because there is no implementation of `export_to`, `dirty_cnt` or `import_from` in the EVP_PKEY_ASN1_METHOD.

This means that if we have such a key then we always just fallback to using legacy codepaths.

This was found during the development of #11826.

**Comment by levitte** [comment]
I noticed this while working with CMS.  I thought I left a TODO, er, *somewhere*.

We don't have a provider side implementation either, do we?  I've assumed that we have to treat these keys the same way as, for example, RSA-PSS keys, i.e. a separate implementation (that may very well use a lot of the same functions, but is a different `OSSL_DISPATCH` array and another `OSSL_ALGORITHM` entry).  Considering that it has there's a separate EVP_PKEY_ASN1_METHOD, that would make sense.  So, proposed keytype name?  "DH-X9.42"?

**Comment by mattcaswell** [comment]
> I noticed this while working with CMS. I thought I left a TODO, er, somewhere.

Yes it was a CMS test that failed for me too.

> We don't have a provider side implementation either, do we?

I think there is already support for `q` on the provider side - which is the key feature of DHX. But somehow this hasn't been fully exposed for DHX type keys (as opposed to DH keys that happen to have a 'q').

> So, proposed keytype name? "DH-X9.42"?

Yes, that would be ok.

**Comment by levitte** [comment]
So I'm a little confused re `q`...  are plain DH keys expected to never have it, but X9.42 keys are expected to always have it?

**Comment by mattcaswell** [comment]
PKCS3 DH (our DH) does not define `q` as a parameter - but we accept it anyway (I think).

X9.42 must have `q`.

**Comment by mattcaswell** [comment]
I believe this has now been resolved. Closing.
