### ISSUE TITLE
Is EVP_get_digestbyobj() going to be problematic to convert to a fetch?

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#11820]
I am in the initial stages of converting CMS to using a libctx..
I assume any calls to EVP_get_digestbyobj() really need to be replaced with EVP_MD_fetch().
It seems this may cause some issues with objects that are created outside the providers (e.g: the gost algorithms). i.e algorithms that are not part of the default provider.
What is the short term solution for this issue? (Long term is everything is fetched from a provider).

**Comment by levitte** [comment]
I'm unsure that we should convert this function.  The design is that `EVP_DigestInit_ex()` recognises if an `EVP_DIGEST` it receives is an old one or not, and if it is, an implicit fetch is done.

Since `EVP_get_digestbyobj()` is completely centerred around the old object database, I would say leave it as such and leave the implicit fetch to `EVP_DigestInit_ex()`

**Comment by slontis** [comment]
So the problem with this, is that it will not work if the default (NULL) library context uses the null provider. (Which is how we test if the fips module is working correctly).

**Comment by levitte** [comment]
Er...  I'm not sure why `EVP_get_digestbyobj()` is involved in that test.  Would you mind directing me to some code so I can try to understand the root problem a little better?

**Comment by slontis** [comment]
cms_SignedData_init_bio()?

**Comment by levitte** [comment]
I assume that you really meant `cms_DigestAlgorithm_init_bio()`, which does call 'EVP_get_digestbyobj()`, yes.  I'm unsure, however, how that "doesn't work".  As far as I undestand, that will currently return one of the (now crippled) ancient constant `EVP_MD` implementations, correct?  That will end up in an `EVP_DigestInit_ex()` call in `crypto/evp/bio_md.c`, which is then going to try an implicit fetch, unless an ENGINE is involved.

What am I missing?

**Comment by slontis** [comment]
Take OSSL_CRMF_pbm_new() as another example.
Imagine that I might want to change this to use a libctx
```
{
   ....
    if ((m = EVP_get_digestbyobj(pbmp->owf->algorithm)) == NULL) {
 ...
    }
    ...

    /* compute the basekey of the salted secret */
    if (!EVP_DigestInit_ex(ctx, m, NULL))
}

If there is no default context then this WILL fail.
I want it to only use a libctx that has been created.
EVP_DigestInit_ex() does not do this internally.

**Comment by levitte** [comment]
Nothing stops you doing an "implicit fetch" inside `OSSL_CRMF_pbm_new()`
Or we can do the same thing we've done with `EVP_PKEY_CTX`, add an `OPENSSL_CTX` field in it and add a function `EVP_MD_CTX_new_with_ctx()`, which can be used for such purposes.

**Comment by DDvO** [comment]
The following adaptation works:
```
    mdname = OBJ_nid2sn(OBJ_obj2nid(pbmp->owf->algorithm));
    owf = EVP_MD_fetch(libctx, mdname, propq);
```

**Comment by slontis** [comment]
That will have to do for now..
It doesnt solve the problem I am talking about though
(e.g fetching a gost algorithm will fail).

**Comment by mattcaswell** [comment]
@slontis - is this resolved now?

**Comment by slontis** [comment]
For gost we ended up having to do a fecth and then when it fails try the old way.. Not much else we can do with these until engines are gone.. Closing now.
