### ISSUE TITLE
EVP_PKEY_base_id always returns 0 for generated pkey on master

### ISSUE THREAD

**Issue by fffonion** [openssl/openssl#11823]
```
#include <stdio>
#include <openssl/evp.h>
#include <openssl/rsa.h>

void main() {
    EVP_PKEY_CTX *ctx;
    EVP_PKEY *pkey = NULL;

    ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, NULL);
    if (!ctx) {
        printf("1\n");
        exit(1);
    }
        
    if (EVP_PKEY_keygen_init(ctx) <= 0) {
        printf("2\n");
        exit(1);
    }

    if (EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, 2048) <= 0) {
        printf("3\n");
        exit(1);
    }

    /* Generate key */
    if (EVP_PKEY_keygen(ctx, &pkey) <= 0) {
        printf("4\n");
        exit(1);
    }

    printf("key_type %d\n", EVP_PKEY_base_id(pkey));
}
```

This prints `0` for master branch but correctly prints `6` for previous versions.

**Comment by levitte** [comment]
"correctly" is a matter of interpretation.  Opinions are diverse regarding this...  these ids were originally not meant to be public, and it would have been much better to return a constant string (even if the *internal* identity was a number).

That being said, I do understand that this is a surprising result, considering that you created the `EVP_PKEY_CTX` from one of those numeric identities.  I'll see if I can make a sane enough fix.

**Comment by fffonion** [comment]
@levitte Thanks!

There's a related behaviour when using `EVP_PKEY_new_raw_{public/private}_key`, posting here as well:

```
#include <openssl/evp.h>
#include <openssl/rsa.h>

void main() {
    EVP_PKEY_CTX *ctx;
    EVP_PKEY *pkey = NULL;
    unsigned char buf[32] = {0};

    if (!(pkey = EVP_PKEY_new_raw_public_key(EVP_PKEY_ED25519, NULL, buf, 32))) {
        exit(1);
    }
    printf ("%d", EVP_PKEY_base_id(pkey));
}
```
(outputs 0)
