### ISSUE TITLE
s_client silently overrides -unix when -connect is present.

### ISSUE THREAD

**Issue by Lukasa** [openssl/openssl#1183]
Right now there's a chunk of #ifdef'd code in s_client that essentially ensures that `-unix` and `-connect` silently override each other if both are provided on the s_client interface. This is probably unwise: providing them both should be considered an error.

See also: #1171 for more discussion.

**Comment by richsalz** [comment]
See PR #1196 that closes this.

**Comment by richsalz** [comment]
fixed with commit fe08bd76e2b2ffcba0d24b60feec839fcd985ff7; closing.
