### ISSUE TITLE
Upgrading from 0.9.8gz to 1.1.1g linker issues

### ISSUE THREAD

**Issue by amitdubey26** [openssl/openssl#11831]
I am upgrading openssl from 0.9.8 gz to 1.1.1g on Solaris 10.
Build is successful for openssl libs. But while linking to my app, i get below linker errors:

Undefined                       first referenced
 symbol                             in file
SSL_load_error_strings              ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)
SSLeay_version                      ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)
CRYPTO_cleanup_all_ex_data          ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)
SSLv3_client_method                 ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)
SSLv2_client_method                 ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)
EVP_cleanup                         ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)
ERR_free_strings                    ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)
SSL_library_init                    ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Wanted to know if there sysmbols are deprecated or removed what are their corresponding counter parts in 1.1.1g or is there a compile flag to inlcude these symbols in openssl build to get over these.

O/p perl dump below:

Command line (with current working directory = .):

    perl ./Configure solaris64-sparcv9-cc -KPIC -lrt shared

Perl information:

    perl
    5.10.1 for sun4-solaris-thread-multi

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c\+\+
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [not-linux]   OPENSSL_NO_AFALGENG
    asan                    [default]     OPENSSL_NO_ASAN
    crypto-mdebug           [default]     OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]     OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]     OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]     OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]     OPENSSL_NO_EGD
    external-tests          [default]     OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]     OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]     OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]     OPENSSL_NO_HEARTBEATS
    makedepend              [unavailable] 
    md2                     [default]     OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]     OPENSSL_NO_MSAN
    rc5                     [default]     OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]     OPENSSL_NO_SCTP
    ssl-trace               [default]     OPENSSL_NO_SSL_TRACE
    ubsan                   [default]     OPENSSL_NO_UBSAN
    unit-test               [default]     OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]     OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]     
    zlib-dynamic            [default]     
    ssl3                    [default]     OPENSSL_NO_SSL3
    ssl3-method             [default]     OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "cc",
    CFLAGS => "-xO5 -xdepend",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c aes-sparcv9.S aest4-sparcv9.S aesfx-sparcv9.S",
    aes_obj => "aes_core.o aes_cbc.o aes-sparcv9.o aest4-sparcv9.o aesfx-sparcv9.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "asm/sparcv8plus.S sparcv9-mont.S sparcv9a-mont.S vis3-mont.S sparct4-mont.S sparcv9-gf2m.S",
    bn_obj => "asm/sparcv8plus.o sparcv9-mont.o sparcv9a-mont.o vis3-mont.o sparct4-mont.o sparcv9-gf2m.o",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-xarch=v9 -xstrconst -Xa",
    chacha_asm_src => "chacha_enc.c",
    chacha_obj => "chacha_enc.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c cmllt4-sparcv9.S",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o cmllt4-sparcv9.o",
    cppflags => "-D_REENTRANT",
    cpuid_asm_src => "sparcv9cap.c sparccpuid.S",
    cpuid_obj => "sparcv9cap.o sparccpuid.o",
    defines => [  ],
    des_asm_src => "des_enc-sparc.S fcrypt_b.c dest4-sparcv9.S",
    des_obj => "des_enc-sparc.o fcrypt_b.o dest4-sparcv9.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-sparcv9.S",
    ec_obj => "ecp_nistz256.o ecp_nistz256-sparcv9.o",
    enable => [  ],
    ex_libs => "-lsocket -lnsl -ldl -lpthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "-mt",
    lib_cflags => "",
    lib_cppflags => "-DFILIO_H -DB_ENDIAN -DBN_DIV2W",
    lib_defines => [  ],
    md5_asm_src => "md5-sparcv9.S",
    md5_obj => "md5-sparcv9.o",
    modes_asm_src => "ghash-sparcv9.S",
    modes_obj => "ghash-sparcv9.o",
    module_cflags => "-KPIC",
    module_cxxflags => "",
    module_ldflags => "-G -dy -z text -Wl,-Bsymbolic",
    multilib => "/64",
    padlock_asm_src => "",
    padlock_obj => "",
    perlasm_scheme => "void",
    poly1305_asm_src => "poly1305-sparcv9.S",
    poly1305_obj => "poly1305-sparcv9.o",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    sha1_asm_src => "sha1-sparcv9.S sha256-sparcv9.S sha512-sparcv9.S",
    sha1_obj => "sha1-sparcv9.o sha256-sparcv9.o sha512-sparcv9.o",
    shared_cflag => "-KPIC",
    shared_defflag => "-Wl,-M,",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-G -dy -z text -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-h,",
    shared_target => "self",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPPFLAGS = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LDFLAGS = 
    LDLIBS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar
    ARFLAGS         = r
    CC              = cc
    CFLAGS          = -xO5 -xdepend -KPIC
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = -KPIC
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = -lrt
    PERL            = perl
    RC              = windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl

**Comment by mattcaswell** [comment]
With the exception of SSLv2_client_method, all of these things still exist in one form or another. Most of them have been converted to macros - many of which are actually no-ops. It's not clear why your compiler is not honouring the macros (they are not functions and so there shouldn't be an attempt to link against them).

Detailed notes below.

> SSL_load_error_strings
> ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Still exists as a macro. You no longer need to call it.

> SSLeay_version ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Still exists as a macro. You can use `OpenSSL_version` instead for the preferred name.


> CRYPTO_cleanup_all_ex_data
> ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Still exists as a no-op macro. You no longer need to call it.

> SSLv3_client_method
> ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Still exists as a deprecated function - support for this is not compiled by default. Compile with the "enable-ssl3" and "enable-ssl3-methods" if you really must have SSLv3 support. Or ideally remove it. SSLv3 is no longer considered secure.

The preferred approach for all of these "version specific" methods is to use the version flexible `TLS_client_method` or `TLS_server_method` instead. These will auto-negotiate the best available TLS protocol version - unlike the version specific variants.

> SSLv2_client_method
> ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Removed entirely. Don't use SSLv2. Ever. It's completely broken.

> EVP_cleanup ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Still exists as a no-op macro. You no longer need to call it.

> ERR_free_strings ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Still exists as a no-op macro. You no longer need to call it.

> SSL_library_init ../netapi4swp/src/Sol64exe/lib/libswecapi2.a(opensslutil.o)

Still exists as a macro. You no longer need to call it.

**Comment by amitdubey26** [comment]
HI 

Thanks for your response, i am trying to build openssl for 32 bit for Solaris 10.

But when i use ssl3 flags above suggested for configure it doesnt work.

/Configure  enable-ssl3 enable-ssl3-method -KPIC -lrt shared

Please help me resolving it.

Thanks
Amit

**Comment by mattcaswell** [comment]
>  it doesnt work.

What exactly doesn't work? You still get linker errors or something else goes wrong? If the latter please provide more details about happens.

**Comment by amitdubey26** [comment]
/Configure enable-ssl3 enable-ssl3-method -KPIC -lrt shared doesnt does configure 32 build with ssl3 symbols, rather it suggests to use ./config

**Comment by mattcaswell** [comment]
> Thanks for your response, i am trying to build openssl for 32 bit for Solaris 10.

Right....so in your original report you seemed to be trying to build for 64-bits. The configdata output said this:

````
perl ./Configure solaris64-sparcv9-cc -KPIC -lrt shared
````

Therefore, the equivalent command, adding the ssl3 options is:

````
perl ./Configure solaris64-sparcv9-cc -KPIC -lrt shared enable-ssl3 enable-ssl3-method
````

Does this work? If you can get this to work for 64-bits, then attempting a 32 bit compile would be the next step, and should probably be a different issue. I am not sufficiently familiar with Solaris to offer advice on building for 32-bit Solaris in a 64-bit Solaris environment.

**Comment by shaozhihua** [comment]
@mattcaswell 
hello,sir,you tell us the SSL_library_init is Still exists as a macro. You no longer need to call it. but we have a project which used this func in openssl 1.0.2,so how should I to change my code?

**Comment by paulidale** [comment]
Remove the call.

**Comment by amitdubey26** [comment]
Thanks closing it. Missed it in the past.
