### ISSUE TITLE
Update apps/progs.c when apps/build.info changes

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#11838]
For instance when new app is added to `apps/` then builds tend to fail because it is not yet referenced in `apps/progs.c`.

To fix this I would like to extend in the auto-generated `Makefile`:
```
apps/progs.c: apps/progs.pl
```
to
```
apps/progs.c: apps/progs.pl apps/build.info
```
but I have not found how to do that.

**Comment by mattcaswell** [comment]
Use the build.info `DEPEND` directive perhaps? Although really everything should be rebuilt if build.info files change I would have thought.

**Comment by levitte** [comment]
Fixed in #11824

**Comment by DDvO** [comment]
> Use the build.info `DEPEND` directive perhaps?

Indeed 
```
  DEPEND[progs.c]=build.info
```
does the trick! 
Should I make a separate PR for that tiny change or can I piggy-back this with some other?

>  Although really everything should be rebuilt if build.info files change I would have thought.

I would have thought, too, but I've verified:
If progs.h or progs.c is missing the new app then 
`touch app/build.info && make` does not adapt those two files.

**Comment by DDvO** [comment]
Ah, just found that @levitte already fixed it :)
