### ISSUE TITLE
ED25519 Signature Algorithm OID Not Complete in a Generated X.509 Certificate

### ISSUE THREAD

**Issue by okba-zoueghi** [openssl/openssl#11836]
I am using the OpenSSL version 1.1.1f which is installed by default in my system (Ubuntu 20.04).

I generated a self-signed X.509 certificate with the OpenSSL command line, the signature algorithm I used is ed25519.

I parsed the certificate using the following command:

`openssl asn1parse -inform PEM -in certs/ca.cert.pem`

This is a part of the output:

```
  369:d=1  hl=2 l=   5 cons:  SEQUENCE          
  371:d=2  hl=2 l=   3 prim:   OBJECT            :ED25519
  376:d=1  hl=2 l=  65 prim:  BIT STRING   
```

As you could remark, the output indicates that the OID of the ed25519 signature algorithm
is of size 3 bytes. I was able to find the offset of the 3 bytes and then print them and the result was `{0x2B, 0x65, 0x70}`.

According to the rfc8410 (https://tools.ietf.org/html/rfc8410) the OID of the ed25519 signature algorithm
is `id-Ed25519   OBJECT IDENTIFIER ::= { 1 3 101 112 }` which is when translated to hex 
equal to `{0x06, 0x03, 0x2B, 0x65, 0x70}`. 

The size of the OID is 5 bytes but OpenSSL outputs 3 and ignores the first 2 bytes.

Why is OpenSSL ignoring the first 2 bytes, is there a reason, is this done on purpose, 
am I missing something?

**Comment by levitte** [comment]
You're missing `hl=2`.

You see, DER encoding is essentially a tuple, \< tag, content length, content \>. So here you have the tag 0x06 (which is the tag for OBJECT IDENTIFIER), the length 0x03 and the contents (3 bytes).

`asn1parse` shows this by telling you the "header length" (hl) and the content length (l).
