### ISSUE TITLE
OpenSSL 3.0.0-alpha2 EVP_CipherInit_ex fails with some ciphers

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#11847]
In OpenSSL 1.1.1 (and lower) the following initialization code returns successfully, but in 3.0.0-alpha2 it fails with some `EVP_CIPHER *` objects. This pattern is commonly used when initializing the context and setting key length (for, e.g. RC4 or Blowfish) using `EVP_CIPHER_CTX_set_key_length`.

```c
#include <stdio.h>
#include <openssl/evp.h>
int main(void) {
    const EVP_CIPHER *cipher = EVP_get_cipherbyname("bf-ecb");
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    int res = EVP_CipherInit_ex(ctx, cipher, NULL, NULL, NULL, 1);
    if (res == 0) {
        printf("init failed");
        return 1;
    }
    return 0;
}
```

This appears to affect the following legacy ciphers:
* Blowfish
* CAST5
* IDEA
* RC4
* SEED

**Comment by mattcaswell** [comment]
This is by design. Some legacy ciphers have been moved to the legacy provider which you must load explicitly if you want to use them

See:
https://wiki.openssl.org/index.php/OpenSSL_3.0#Legacy_Algorithms
and
https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers

**Comment by reaperhulk** [comment]
@mattcaswell perfect, I'll take a look at that. Sorry about the noise then!

**Comment by alex** [comment]
It's surprising to me that `EVP_CipherInit_ex` would be where this fails. Surely `EVP_get_cipherbyname` should fail if you don't have the cipher available?

**Comment by kroeckx** [comment]
I assume it actually returns NULL. The example code at least
didn't check for NULL.

**Comment by reaperhulk** [comment]
It does not return NULL (which I knew from the non-reduced test case this came from but didn't include in the sample code). I've updated the original code to show that now.

**Comment by mattcaswell** [comment]
It is important to understand the difference between having a handle on the abstract EVP_CIPHER object which represents the the "bf-ecb" cipher (and is usually held in a "const" EVP_CIPHER)- and fetching a concrete implementation of that cipher. It is not until we attempt to locate a concrete implementation that we discover that there isn't one available.

You can fetch a concrete implementation either explicitly using the EVP_CIPHER_fetch() function, or implicitly. If done implicitly then the concrete implementation is fetched in a just-in-time manner in the EVP_CipherInit_ex()  function.

The EVP_get_cipherbyname() function just returns a "const" EVP_CIPHER. It does not fetch an implementation.

In fact the availability of a cipher also depends on the OPENSSL_CTX being used. It is perfectly possible to have the legacy provider loaded into one OPENSSL_CTX and not into another one, i.e one part  of the application has the cipher available - and another part does not.

**Comment by beldmit** [comment]
It sounds logical but counter-intuitive to me. I did not dive into the logic of providers, so many thanks for your explanation.

**Comment by mattcaswell** [comment]
If you can understand algorithm fetching then you are halfway there to understanding providers.
