### ISSUE TITLE
1.1.1g won't build on Linux; Configure CFLAGS bug and .private_extern pseudo-op errors

### ISSUE THREAD

**Issue by JoeUX** [openssl/openssl#11841]
**OpenSSL 1.1.1g on both Fedora 32 and Alpine Linux 3.11.6:**

## Error 1
The ./Configure command produces invalid CFLAGs in the resulting Makefile. The invalid bit is `-arch x86_64`.

`-arch` isn't a valid flag. The valid form is `-march`, and it has to be joined with a value. And x86_64 isn't valid syntax just sitting there on its own, separated from `-march` by a space. There needs to be an equals sign joining `-march` with a platform flag. The screenshot of the resulting error on running make is below. The error happens immediately – nothing is compiled.

The full command I'm running is:

$ `./Configure darwin64-x86_64-cc --prefix=/usr`
$ `make`

(I'm trying to build it for nginx, as instructed at nginx.com [here](https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/#dependencies).)

![Fedora OpenSSL error](https://user-images.githubusercontent.com/8071692/82058654-e1b27680-9679-11ea-9fd7-c205fe63f985.JPG)

## Error 2

I edited the Makefile and replaced `-arch x86_64` with `-march=ivybridge` and it fixed the error. It goes through a great deal of compilation before bumping into a different error. Now it says:

crypto/bn/x86_64-mont5.s:1213: Error: unknown pseudo-op: \`.private_extern\`
crypto/bn/x86_64-mont5.s:: Error: unknown pseudo-op: \`.private_extern\`

Anyone have a workaround for this error? I've tried it on both Fedora 32 Server (latest; with gcc 10.1) and Alpine Linux 3.11.6 (latest; with gcc 9.2). Fedora is a conventional Linux distribution that uses glibc, while Alpine is a much more compact distribution that uses the musl libc and busybox. I'm running both in Hyper-V on Windows 10 Pro, 64-bit throughout.

![Fedora OpenSSL error 2](https://user-images.githubusercontent.com/8071692/82058664-e5de9400-9679-11ea-9e37-c0d4c4307b61.JPG)

**Comment by levitte** [comment]
What happens if you replace `-march=ivybridge` with `-m64`?

**Comment by bernd-edlinger** [comment]
darwin64-x86_64-cc is mac o/s?
but why are you not  using linux-x86_64

**Comment by kaduk** [comment]
I agree with @bernd-edlinger the darwin configure argument tells us to use the macOS configuration, compiler flags, etc.  The `-arch x86_64` is standard stuff on macOS.

@JoeUX you probably want to use Bernd's suggestion or just use `./config --prefix=user` and let the script figure out what platform you're on automatically.

**Comment by JoeUX** [comment]
Thanks @bernd-edlinger and @kaduk. I was curious about the darwin bit, but I assumed it was some sort of artifact rooted in history I wasn't familiar with, like how we use the System V ABI. The nginx docs specified the syntax without comment. I'll run your syntax.

**Comment by levitte** [comment]
Side note: darwin is a historical name by now...  we should probably rename that config target to something more sensible (and provide the old name as an alias)

**Comment by bernd-edlinger** [comment]
FYI: when you build a GCC cross complier for that O/S  --target= is supposed to be one of:
x86_64-*-darwin*,i?86-*-darwin* | powerpc64*-*-darwin*,powerpc*-*-darwin*
but that does not mean much.

**Comment by t-j-h** [comment]
> Side note: darwin is a historical name by now... we should probably rename that config target to something more sensible (and provide the old name as an alias)

Wrong! Darwin is what Apple call their core operating system in all releases.
It is not historical - it is **current** usage.

uname -s reports "Darwin"

**Comment by levitte** [comment]
I stand corrected.
