### ISSUE TITLE
GCM IVs limited to 64 bytes in OpenSSL 3.0.0-alpha2

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#11843]
OpenSSL prior to 3.0.0 supports arbitrary length GCM IVs. As of 3.0.0 a default minimum is enforced in the provider (great!), but it also enforces a maximum of 64 bytes. OpenSSL's past choices to allow larger IVs makes this problematic from a compatibility standpoint . SP800-38D recommends that implementations just enforce 96-bits (although up to 2**64 -1 bits is hypothetically permissible), but NIST's own CAVP test vectors for GCM mode contain IV lengths up to 1024 bits in length. At least for the purposes of compatibility with the NIST test vector suite it might be good to raise `GCM_IV_MAX_SIZE` to 128 instead of 64.

**Comment by mattcaswell** [comment]
@slontis - thoughts on this?

**Comment by slontis** [comment]
there should not be a problem increasing the size (other than it uses a fixed sized array buffer)

**Comment by reaperhulk** [comment]
As 3.0 approaches it'd be nice to get a final answer here. I'm in favor of limiting the size (huge IVs are nonsense and the number of users who would run afoul of a change like this is likely very small), but I don't have a particularly strong opinion on what that size should be. If we wanted OpenSSL to be able to run the complete NIST GCM CAVP test suite `128` bytes would be appropriate though.

**Comment by slontis** [comment]
We may ask the lab about this...

**Comment by slontis** [comment]
The lab confirmed that a subset of the range can be tested..
I will increase the max size to 1024, but the minimum limit of 64 (not 1 byte) is still in place.

**Comment by mattcaswell** [comment]
@slontis - can this be closed now?

**Comment by slontis** [comment]
It has been resolved.. so closing.
