### ISSUE TITLE
OpenSSL 3.0.0-alpha2 can't serialize ed25519 or ed448 keys to PKCS8

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#11845]
The following code will successfully serialize an ed25519 key (or ed448 key if you swap the NID) as a PKCS8 structure in both PEM and DER encoding on OpenSSL 1.1.1, but errors on 3.0.0-alpha2.

```c
#include <stdio.h>
#include <openssl/bio.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/obj_mac.h>
int main(void) {
    int res = 0;

    EVP_PKEY_CTX *ctx = EVP_PKEY_CTX_new_id(NID_ED25519, NULL);
    res = EVP_PKEY_keygen_init(ctx);
    if (res != 1) {
        printf("could not init keygen\n");
        return 1;
    }
    EVP_PKEY *pkey;
    res = EVP_PKEY_keygen(ctx, &pkey);
    if (res != 1) {
        printf("could not generate key\n");
        return 2;
    }
    BIO *bio = BIO_new(BIO_s_mem());
    res = PEM_write_bio_PKCS8PrivateKey(bio, pkey, NULL, "", 0, NULL, NULL);
    if (res != 1) {
        printf("failed to serialize to PEM\n");
    }
    res = i2d_PKCS8PrivateKey_bio(bio, pkey, NULL, "", 0, NULL, NULL);
    if (res != 1) {
        printf("failed to serialize to DER\n");
    }

    return 0;
}
```

**Comment by levitte** [comment]
True.  The PKCS#8 PEM and i2d routines haven't been converted to deal with provider side keys yet.

**Comment by reaperhulk** [comment]
ed25519/ed448 keys also appear to be unable to perform signatures in `X509_CRL_sign` and `X509_sign`. I can open another issue for this if desired, but didn't want to clutter the issue tracker.

**Comment by levitte** [comment]
Would you mind trying #11855?

As for the X509_CRL_sign / X509_sign problem, please create another issue for them.

**Comment by reaperhulk** [comment]
@levitte I can test this tomorrow and will open a new issue for the X509 functions as well.

**Comment by reaperhulk** [comment]
The PR you linked (or at least it applied against the master branch) does allow serialization and all my tests pass against it.
