### ISSUE TITLE
OpenSSL does not check the revocation date of the revoked certificate(s)

### ISSUE THREAD

**Issue by yuemonangong** [openssl/openssl#11859]
I created a revoked certificate whose **revocation date** is **later than current time**. However, the revoked certificate is still applicable when a certificate chain is verified. OpenSSL **1.1.1d version** does not check the revocation date of the revoked certificate(s).

The command I used is:
```
openssl verify -show_chain -CAfile root.pem -CRLfile test.crl -crl_check_all leaf.pem
```

The verification returns
```
C = GB, ST = Berkshire, L = Newbury, O = My Company Ltd
error 23 at 0 depth lookup: certificate revoked
error leaf.pem: verification failed
```

root.pem:
```
-----BEGIN CERTIFICATE-----
MIIDNDCCAhygAwIBAgIJAPU0AU3ad04vMA0GCSqGSIb3DQEBCwUAMEcxCzAJBgNV
BAYTAkNOMQswCQYDVQQIDAJTSDENMAsGA1UECgwEU0pUVTENMAsGA1UECwwERERT
VDENMAsGA1UEAwwETkNSTDAeFw0yMDAzMjYwODI3NDlaFw0yMzAxMTQwODI3NDla
MEcxCzAJBgNVBAYTAkNOMQswCQYDVQQIDAJTSDENMAsGA1UECgwEU0pUVTENMAsG
A1UECwwERERTVDENMAsGA1UEAwwETkNSTDCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAPNLlu+KPCcjj1KiZ1/sUFvFRDt3Z7WZTWjOYeJUFvycHNcYN9cE
laGJ32hfjgaPw9u3cOgs0JJHwIhlQkNhSexUvgGatw336H/3FjPQCJKs48lDJG13
sDF7TK1MvG5wcF1pgRkfvoRSWOyr30aqoeQHaRnqMnT0lWBy26mmV6mgM7LPeNq8
E6jh6aLy7uep3+rO/Ef7LvFi/QWqy+vVVmr5MljXtFyWI+aLs4uFtZZ6rFw5Va4U
Y6OffwchjkVex1eML4D593fobkmkubxZEm2o2Upi/Eiech7CM8HuwgqrAwoIVxi6
FlObraD90sUSUKUwohvl03tkjCTXakXF2TUCAwEAAaMjMCEwEgYDVR0TAQH/BAgw
BgEB/wIBAzALBgNVHQ8EBAMCAeYwDQYJKoZIhvcNAQELBQADggEBACb6hOtUCqD5
sH4VucCO4FYFHM6nfBvB9vx+c2RPC/psam9clOvL5llrUhY070pXbZnd2hwxfnzj
cdr448sVyJkHosukzZj/MyEBV9BERTUMOaY4etQxM2L33uyzn5++/NeRC2Yd53AL
vY/s4znat7txqBK/izvLemLerp1Z5E58VFzLOvYNz+7vEoxMmNaU55TGh88VJIvo
THaZ3LflTc7hv9eUWin0LTV0mg7cvM+/qWrM2N2hyOukztF5gCcMEgoVkpEgUCJP
WsrvOumtDNuXnPr80r4N54n5TaQCTBG22Tj89klc6jUji63+UR9KKACCV44KT8hc
+0ecJPmXqEU=
-----END CERTIFICATE-----
```

leaf.pem:
```
-----BEGIN CERTIFICATE-----
MIIDITCCAgmgAwIBAgIBATANBgkqhkiG9w0BAQsFADBHMQswCQYDVQQGEwJDTjEL
MAkGA1UECAwCU0gxDTALBgNVBAoMBFNKVFUxDTALBgNVBAsMBEREU1QxDTALBgNV
BAMMBE5DUkwwHhcNOTYwODAxMDAwMDAwWhcNMjAxMjMxMjM1OTU5WjBMMQswCQYD
VQQGEwJHQjESMBAGA1UECBMJQmVya3NoaXJlMRAwDgYDVQQHEwdOZXdidXJ5MRcw
FQYDVQQKEw5NeSBDb21wYW55IEx0ZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAL+N0yePi18I/+MxN/31iBehb2rO5s8MzykUz3aGp3BG/5uEFueqoYZN
CNLA38wIUT/ry8wIw+jlTNj29L7Q9uOX8+10XgF4VTVtN14KT0s7tZ5dLjGRD7ft
fZF03ifbGYp39fW2Wjutjo4Jyop+Bm7g6SrSJB3uaioITpZh8Xf7MHo+kNjJKPsu
ZlVVNQ3T5WQWzoskcpRRIujv7U/NATuRzXODUzqnw+HGavu2qTX3falo5i0dzzrt
9yCtLKqtC+0oX+kZPIi3ib/o20fY3hEXwYstq5sKpvV25xgKTbtwRN1KlMIhfSQN
uFXIg/Rd6rbd9P60zPYxzOTwMsaEysECAwEAAaMTMBEwDwYDVR0TAQH/BAUwAwEB
/zANBgkqhkiG9w0BAQsFAAOCAQEAKhf5CQGxsJCzkFJv26ggzi2HxN/X/eXcwJyy
3gfPP0JZNLzRb6bmracLui58LyCX+0tmY5TA1G3V94Vdu2LIUMRoANwKszTxhW/n
8oNvXDji+E62EsivCtoPgYRAwFE0q4flvcWzDwGlqCfEdaG1uqYGLlLxW8gmHdFs
pKJf4yCzQOn04RmReXOhaAtyUT+xp9AUzawzr2PPGA75x7B07HT4ezLPWy+l1X0o
gMBOWm3AwrwTD8k1B488NiKivCYjBn6UPG0r9/gKxSvdEJEJ6SyM8+Jw+f7lij8i
55LYqy8oyPPknQOAWzB+KZkCbqkcBGJLEPR35agBN/SDSdioXA==
-----END CERTIFICATE-----
```

test.crl:
```
-----BEGIN X509 CRL-----
MIIBtjCBnwIBATANBgkqhkiG9w0BAQ4FADBHMQswCQYDVQQGEwJDTjELMAkGA1UE
CAwCU0gxDTALBgNVBAoMBFNKVFUxDTALBgNVBAsMBEREU1QxDTALBgNVBAMMBE5D
UkwXDTIwMDMwODIwMjYwN1oXDTIxMDIyMTIwMjYwN1owFDASAgEBFw0yMTAyMjEy
MDI2MDdaoA4wDDAKBgNVHRQEAwIBADANBgkqhkiG9w0BAQ4FAAOCAQEAkqQPjXyG
FTyPmHi47KoMaeg0M7wU5KO8SXOHxUEU65+QuXOK5pOSpjAH+JhLk5H19dY+22gW
+Bec3N3PO2Iw7iK58t5jl+UywRl3VNf6g2Pf+7zrZje3XoTHATLp+LHfVkUJLflZ
/FiEtJS6NVsNemrAY+BNCCIocHqBVjMAX1zSmUw9lSUFIH6+9HOtVQ0FlmO5RBA5
6QoCmAO3t/5FZF3LqxGj5z3weBVsU340iebf20remV2pEFwWW9KKDBkx+Rd9njgW
dmrKXY4pLfAUZ+D2eCevHBU7vLSSjmgBOKu+74/l28wGF+7oFtj5txbK4hdc1j11
/gX0RqNhGLarQw==
-----END X509 CRL-----
```

**Comment by kroeckx** [comment]
The date of revocation is not relevant to wether it's been revoked or not.

**Comment by dcooper16** [comment]
> I created a revoked certificate whose **revocation date** is **later than current time**. However, the revoked certificate is still applicable when a certificate chain is verified. OpenSSL **1.1.1d version** does not check the revocation date of the revoked certificate(s).

It is not valid for the revocation date to be later than the current time. Here is the text from [RFC 5280, Section 5.3.2](https://www.rfc-editor.org/rfc/rfc5280.html#section-5.3.2), with the most relevant portions of it in **bold**:

- The invalidity date is a non-critical CRL entry extension that provides the date on which it is known or suspected that the private key was compromised or that the certificate otherwise became invalid.  This date may be earlier than **the revocation date** in the CRL entry, which **is the date at which the CA processed the revocation**.  When a revocation is first posted by a CRL issuer in a CRL, the invalidity date may precede the date of issue of earlier CRLs, but **the revocation date SHOULD NOT precede the date of issue of earlier CRLs**.  Whenever this information is available, CRL issuers are strongly encouraged to share it with CRL users.

**Comment by yuemonangong** [comment]
> It is not valid for the revocation date to be later than the current time. 

I'm still confused here. Should an "invalid" revoked certificate be still used, like a valid one, for revoking certificates? OpenSSL takes it (a revoked certificate with an invalid revocation date) as a normal revoked certificate.

**Comment by kroeckx** [comment]
If it's in the CRL, it's revoked. The date in the CRL is just some
meta data that might be useful to known since when something is
wrong with the key.
