### ISSUE TITLE
Length appending in sha512

### ISSUE THREAD

**Issue by oktorok** [openssl/openssl#11854]
Hi i am studying this algorithm and i am very curious about the purpose of these lines:

https://github.com/openssl/openssl/blob/4fcd15c18ad6b5523a389863d3e5628d44db6eb4/crypto/sha/sha512.c#L288-L293

Following the algorithm pseudo code i am supposing those lines are in charge of keep the size of the buffer, for at the last step append the message length to the message, but what i don't understand is why the bit movements  ```(SHA_LONG64) len) << 3)``` and ```(SHA_LONG64) len) >> 61)``` are necessary.

**Comment by kaduk** [comment]
It seems that `Nl` and `Nh` together are the 'low' and 'high' portions of a 128-bit counter, that tracks the number of bits of input that have been consumed.  Note that per RFC 6234 the input length in bits is appended to the message before being digested.  The left-shift converts bytes to bits, and the right-shift accounts for cases where the `SHA512_Update()` input from a single call causes the 'high' half of the counter to increment more than once.

**Comment by oktorok** [comment]
Thanks for the answer, but i still don't understand the point of the shifts.
Why not 
```
 l = c->Nl + len; 
 if (l < c->Nl) 
     c->Nh++; 
 if (sizeof(len) >= 8) 
     c->Nh += len; 
 c->Nl = l; 
```

**Comment by oktorok** [comment]
I still doesn't understand the point of the shifts, from my understanding, doing that you are only shifting the entire number 3 bits to the left letting 3 0s at the right.
Why not this won't work:
```
  l = c->Nl +len; 
 if (l < c->Nl) 
     c->Nh++; 
 c->Nl = l; 
```

Edit:
Sorry for the close-open missclick

**Comment by kaduk** [comment]
The `len` input measures bytes, but the `Nl` and `Nh` structure members measure bits.  The factor of 8 difference is effecuated by a left-shift of 3, which, when combined with an (implicit) right-shift of 64 to get to the high word, becomes a right shift of 61.

**Comment by oktorok** [comment]
Bits and bytes, of course 🤦 

Now everything has sense, thank you so much, i forget totally about that shifting its the same than multiply by 2.

Have a super nice day ^^
