### ISSUE TITLE
CRYPTO_set_locking_callback openssl 1.0.2 and fips mode

### ISSUE THREAD

**Issue by abdollar** [openssl/openssl#11862]
### Question

We have a ruby on rails application that uses a number of different libraries such as libmysqlclient, and librdkafka and libcurl that then use openssl including ruby itself.

It seems that each of these libraries implementation uses its own CRYPTO_set_locking_callback implementation that then has its own mutex etc.

Some check for existing callbacks and others don't.

Here are the implementations online

1. libmysqlclient that uses the openssl_lock_function here - see - https://github.com/mysql/mysql-server/blob/7d10c82196c8e45554f27c00681474a9fb86d137/vio/viosslfactories.cc#L421

2. librdkafka can be found here - see - https://github.com/edenhill/librdkafka/blob/cedb2917396ddb02a853330adf5030506abdebf3/src/rdkafka_ssl.c#L1390

Ideally, I would like them to use one implementation of the CRYPTO_set_locking_callback API call but it depends on the order they are initialized. 

In the example above libmysqlclient doesn't look for existing callbacks which I would argue is a bug?

Ideally, I would like to just have it (that is CRYPTO_set_locking_callback) called once and for the other calls to delegate to the first caller somehow or maybe my own version.

If I use something like a trampoline to capture all calls to CRYPTO_get_locking_callback and CRYPTO_set_locking_callback is that in violation of FIPS ?

Is there an easy way to ensure there is only one CRYPTO_set_locking_callback implementation being used?

I understand this is not an issue with openssl 1.1 and above but we have to use 1.0.2 due to FIPS.

**Comment by paulidale** [comment]
1.0.2 is past its use by date and is unsupported.

For FIPS related questions, you should ask a FIPS lab.

**Comment by kaduk** [comment]
> Is there an easy way to ensure there is only one CRYPTO_set_locking_callback implementation being used?

No.  Having a library try to set the locking callbacks is a recipe for this kind of disaster.

If more than one library is trying to set the callbacks and to use the provided callback functions for mutual synchronization with their own internal processing, the situation is basically unresolvable.  In 1.1.1 the locking callbacks are not needed or used, and as was already noted 1.0.2 is EOL.

**Comment by paulidale** [comment]
It seems the question is answered, closing.
