### ISSUE TITLE
Openssl 3.0.0alpha3 fips provider: DSA key gen with some invalid p, q, g causes core dumps or hangs

### ISSUE THREAD

**Issue by jaimeebrown** [openssl/openssl#11864]
Observed with 3.0.0alpha3 configured with NULL lib context using fips provider only. Observed with older (non-fetch) APIs.
Some validity checking of p, q, g seems to be missing because for selected values, core dumps or hangs occur. 

Consider valid parameters (pval, qval, gval). The following behavior was observed with the following expected negative cases:
- set (p, q, g) = (qval, qval, qval) => key gen hangs
- set (p, q, g) = (qval, gval, qval) => Core dump [ free(): invalid next size ]
- set (p, q, q) = (pval,, qval, qval) => Core dump [ free(): invalid pointer ]
- set (p, q, g) = (qval, pval, qval) => Core dump [ free(): invalid next size ]
- set (p, q, g) = (pval, gval, gval) => Core dump [ free(): invalid next size ]

```
#include <openssl/provider.h>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/err.h>
#include <openssl/dsa.h>


int main(int argc, char *argv[]) 
{
   EVP_PKEY *pkey_parm = NULL;
   EVP_PKEY *pkey = NULL;
   DSA *dsa = NULL;
   EVP_PKEY_CTX *gen_ctx = NULL;
   int ret;
   BIGNUM *p = NULL;
   BIGNUM *q = NULL;
   BIGNUM *g = NULL;
   const char *pstr = "00F82CD0B121DF91E2F9D1A84A9A89402A40B9544184E1FDBD27B045D122D719BF1CB7188330EA0E866D3DD2E779C81146316D7280DA9E09FFEA58F4219484B8E7C606F8C6C15F5BD87C21730CC83484495EF991980DCE1D704C6FFB7330B691CCEE948F39935BDF4A1E6CEDAAA6EF37C83868EA0FFA529537384E3595D14F50FF044F9BA38CED5AB1B291D29C8DD2DA43C711E662666FE0C241835E2100C08210FBF0E180F7941CD12C8D98BE70CD68FCC7F57D40EB447D68BA269F6A36E6672D232B59077AD48933C95924E81C524775C7EB5E4D2996C21D7714DA89CF76C91C6E48E3678B80C75CE90437B3C8608886BB9595876C200CA77E554E6E0F724B39";
   const char *qstr = "00879D04B33B22C098583DE711AF3C6CEAB0BEBB0AAC1B5B5203154EEB";
   const char *gstr = "25895D1722207B2E06032D0269587DFDA581800D5510A5605888A7E9868BCFE625CFB6CFF9641AE18BDF0595CC3A7668F014D7E9A818006F7A6E63B1919A25E41389249F0880A968CB5E63714CA3B7CACFFB1C27BE121F7E4122FB711FCEA26F7FE2645799A9AF6007D00F846B04242A1A9664F084BD06762C66BF2BB1E42CFDF5CAE58BD4796272150A304115ACF499FACF41F57225CA6EEDFCB909F0331B9719E5B80F18399A677D0574BED3FDEA92BD05524B0FBCED902B73A203E26A864C99994B19B7C93959E58D5623480349B4468B47975C0F8676F05A429DFE31D7FB9A100F73C8B17C151391C63E814F93F7F249B7E861C7958DF56D021063DEA150";

   ret = OSSL_PROVIDER_available(NULL, "default");
   printf("default provider available: %d\n", ret);
   ret = OSSL_PROVIDER_available(NULL, "fips");
   printf("fips provider available: %d\n", ret);

    dsa = DSA_new();
    if (dsa == NULL) goto end;

    BN_hex2bn(&p, pstr);
    if (p == NULL) goto end;
    
    BN_hex2bn(&q, qstr);
    if (q == NULL) goto end;
    
    BN_hex2bn(&g, qstr);  /* changed from gstr to qstr => causes core dump */
    if (g == NULL) goto end;

    if (DSA_set0_pqg(dsa, p, q, g) <= 0)
        goto end;
    pkey_parm = EVP_PKEY_new();
    if (pkey_parm == NULL)
        goto end;
    if (EVP_PKEY_assign_DSA(pkey_parm, dsa) <= 0)
        goto end;
    
    printf("Generating DSA key \n");
    gen_ctx = EVP_PKEY_CTX_new(pkey_parm, NULL);   
    if (gen_ctx == NULL) goto end;
    if (EVP_PKEY_keygen_init(gen_ctx) <= 0) goto end;
    if (EVP_PKEY_keygen(gen_ctx, &pkey) <= 0) goto end;
    printf("... done generating DSA key\n");

end:
   printf ("err:\n");
   ERR_print_errors_fp(stderr);
   EVP_PKEY_free(pkey_parm);
   
   EVP_PKEY_free(pkey);
   EVP_PKEY_CTX_free(gen_ctx);
   return 1;
}
```
Output received:
```
default provider available: 0
fips provider available: 1
Generating DSA key 
free(): invalid pointer
Aborted (core dumped)
```

**Comment by slontis** [comment]
Hi Jaimee,

I think you have misunderstood what set0 means in the DSA_set0_pqg() call.
All of the failing case you show are sharing a value which is not good.

i.e: internally it does for each param x (where x = p, q,  and g)
       BN_free(dsa->x);
        d->x = x;
So if you just pass in DSA_set0_pqg(p, p, p) you will end up with all sorts of problems when it comes time to do the free, since it will free the p 3 times..

Can you try changing the code (you need to use BN_dup) and see how that works for you..

**Comment by jaimeebrown** [comment]
The sample code provided does NOT share the same value. Each parameter is created separately using BN_hex2bn.

The cases describing the failing behavior are for when the passed in values are different.

**Comment by slontis** [comment]
The following behavior was observed with the following expected negative cases:
So when you say 
    set (p, q, g) = (qval, qval, qval) => key gen hangs

Are you actually using 3 different variables for qval?

**Comment by slontis** [comment]
(If not then that would explain the free hanging)

**Comment by jaimeebrown** [comment]
Yes, 3 different variables used.

**Comment by slontis** [comment]
Ok I can see at least one issue from this..
What is actually happening is the pairwise test after the keygen happens fails (I didnt even know how to ever get it to run this as a failure).

I am wondering what is the actual intent of this code?
Keygen currently assumes that the parameters passed to it are valid..
There is a seperate call to validate the params before calling the keygen.. I dont think this call belongs inside the keygen does it?

**Comment by slontis** [comment]
with the q,q,q case the pairwise sign/verify test tries to calculate a mod_inverse and goes into a loop.. I cant really do a proper validate call since for FIPS_186_4 style keys this will cause some issues.

**Comment by slontis** [comment]
Hmm I could do some simple checks though??
