### ISSUE TITLE
OpenSSL 3.0.0-alpha2 EdDSA X509 signing

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#11875]
In OpenSSL 3.0.0-alpha2 ed25519 and ed448 keys fail when trying to use them to sign with `X509_sign`, `X509_CRL_sign`, and `X509_REQ_sign`. Based on some of the conversation in https://github.com/openssl/openssl/issues/11845 this could also possibly be an instance of a function not understanding provider side keys yet, but that is pure speculation on my part.

No errors are added to the stack, but the functions return 0.

Calling `EVP_PKEY_id` on ed25519/ed448 public keys returned from `X509_get_pubkey` also returns a 0 when we expect `NID_ED25519` (or the equivalent for ed448)

**Comment by reaperhulk** [comment]
Just a nudge to say this is still an issue on the latest master.

**Comment by mattcaswell** [comment]
Do you have any reproducer code?

**Comment by reaperhulk** [comment]
```c
#include <assert.h>
#include <stdio.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/x509.h>

int main() {
    int res;
    /* generate an ed25519 key */
    EVP_PKEY_CTX *ctx = EVP_PKEY_CTX_new_id(NID_ED25519, NULL);
    if (!EVP_PKEY_keygen_init(ctx)) {
        printf("failed to init PKEY ctx\n");
        return 0;
    }
    EVP_PKEY *pkey = NULL;
    if (!EVP_PKEY_keygen(ctx, &pkey)) {
        printf("failed to generate\n");
        return 1;
    }
    if (pkey == NULL) {
        printf("returned key is NULL\n");
        return 1;
    }
    /* get the pubkey from the private key we generated */
    unsigned char buf[32];
    size_t buflen = 32;
    if (!EVP_PKEY_get_raw_public_key(pkey, buf, &buflen)) {
        printf("failed to get raw data\n");
        return 1;
    }
    if (buflen != 32) {
        printf("didn't write the expected byte length\n");
        return 1;
    }

    EVP_PKEY *pubkey = EVP_PKEY_new_raw_public_key(NID_ED25519, NULL, buf, 32);
    if (pubkey == NULL) {
        printf("failed to load pubkey");
        return 1;
    }

    X509_REQ *req = X509_REQ_new();
    /* set some basic things */
    if (!X509_REQ_set_version(req, 0)) {
        printf("failed to set version\n");
        return 1;
    }

    if (!X509_REQ_set_pubkey(req, pubkey)) {
        printf("failed to set pubkey\n");
        return 1;
    }

    if (!X509_REQ_sign(req, pkey, NULL)) {
        printf("signing failed\n");
        return 1;
    }

    return 0;
}
```

This is a very degenerate signer (doesn't even set a subject), but this works without error on 1.1.1g and fails on current master. I believe the same is true for X509 and X509_CRL as well right now.

**Comment by mattcaswell** [comment]
Thanks @reaperhulk. I'll take a look.

**Comment by mattcaswell** [comment]
Thanks for the reproducer - that was very helpful. Fix in #12884.

**Comment by reaperhulk** [comment]
Thanks @mattcaswell. I pulled that PR, built the library, and then build `pyca/cryptography` against it to run our test suite. All X509 tests now pass.

**Comment by mattcaswell** [comment]
Thanks for the confirmation!
