### ISSUE TITLE
using EVP_DigestVerifyFinal to verify ecdsa signature, but always return true, no matter what msg/sig given

### ISSUE THREAD

**Issue by haixiaoyan7** [openssl/openssl#11882]
using EVP_DigestVerifyInit/EVP_DigestVerifyUpdate/EVP_DigestVerifyFinal to verify an ecdsa signature, but always return true, no matter what msg/sig given, does any body know the reason, (p.s. the verson is 1.0.2k)

**Comment by mattcaswell** [comment]
Do you have some sample code you can share which exhibits the problem?

**Comment by haixiaoyan7** [comment]
> Do you have some sample code you can share which exhibits the problem?

```
    if ((evp_ctx = EVP_MD_CTX_create()))
    {
        if (EVP_DigestVerifyInit(evp_ctx, NULL, EVP_sha256(), NULL, evp_pkey))
        {
            ret = EVP_DigestVerifyUpdate(evp_ctx, (const unsigned char*)msg.c_str(), msg.length())
                  && EVP_DigestVerifyFinal(evp_ctx, (const unsigned char*)sig.c_str(), sig.length());
            EVP_MD_CTX_destroy(evp_ctx);
        }
    }
    EVP_PKEY_free(evp_pkey);

```
just these code, it works for RSA, but not works for ECDSA, and the strange is, it always return true whatever the msg and sig is.

**Comment by t8m** [comment]
Have you tested that the EVP_DigestVerifyFinal actually does not return negative value? Because it can return it on failures and in your code you'll treat it as true value.

**Comment by t8m** [comment]
And better do the same for the other DigestVerify calls although the most probable culprit is the Final call.

**Comment by rwfranks** [comment]
If I insert your code fragment into my Net::DNS::SEC verify code, the installation tests work perfectly.

Can you please confirm that the return value was -1?
Was your example signature produced by DigestSignFinal?
It would be very useful to see the content of the signature.

**Comment by haixiaoyan7** [comment]
> If I insert your code fragment into my Net::DNS::SEC verify code, the installation tests work perfectly.
> 
> Can you please confirm that the return value was -1?
> Was your example signature produced by DigestSignFinal?
> It would be very useful to see the content of the signature.

the signature i used is copy from jwt.io
`eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.tyh-VfuzIxCyGYDlkBA7DfyjrqmSHu6pQ2hoZuFqUSLPNY2N0mpHb3nk5K17HWP_3cYHBw7AhHale5wky6-sVA`

>

**Comment by haixiaoyan7** [comment]
> Have you tested that the EVP_DigestVerifyFinal actually does not return negative value? Because it can return it on failures and in your code you'll treat it as true value.

it always return true

**Comment by rwfranks** [comment]
The return value is integer with these possible values:   1, 0, or -1.
Which is it?

**Comment by rwfranks** [comment]
Turing test result: Negative.

**Comment by kaduk** [comment]
Adding resolved:answered on the presumption of a negative (error) return value being wrongly interpreted as boolean true.  Not closing yet, but the bot should send a reminder to do so later.
