### ISSUE TITLE
Can I use one function to set cipherSuites for TLS1.2 and TLS1.3?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#11899]
Hi,
   From this document https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_cipher_list.html
   I should use  SSL_set_cipher_list to set TLS1.2 ciphers and use  SSL_CTX_set_ciphersuites to set for TLS1.3.
   I want to know whether there is a function to set ciphers for both TLS1.2 and TLS1.3.
   If not, why should we use two function for that?  Because now we must make a function  to use these two kind of ciphers.

Thanks.

**Comment by mattcaswell** [comment]
> I want to know whether there is a function to set ciphers for both TLS1.2 and TLS1.3.

No. In most cases you don't need to set the TLSv1.3 ciphersuites at all. You can just use the defaults. There are only 5 currently supported (of which 3 are in the default group).

> If not, why should we use two function for that? Because now we must make a function to use these two kind of ciphers.

Ciphersuites in TLSv1.3 are completely different to TLSv1.2 ciphersuites and are mutually exclusive (TLSv1.2 ciphersuites don't work in TLSv1.3 and vice versa). It was very possible to specify a ciphersuite string using the older ciphersuite functions that would have completely disabled TLSv1.3 ciphersuites by accident. In order to avoid breaking lots of existing deployments we opted to separate these two functions.

**Comment by joymcg** [comment]
Hi

> > I want to know whether there is a function to set ciphers for both TLS1.2 and TLS1.3.
> 
> No. In most cases you don't need to set the TLSv1.3 ciphersuites at all. You can just use the defaults. There are only 5 currently supported (of which 3 are in the default group).
> 
> > If not, why should we use two function for that? Because now we must make a function to use these two kind of ciphers.
> 
> Ciphersuites in TLSv1.3 are completely different to TLSv1.2 ciphersuites and are mutually exclusive (TLSv1.2 ciphersuites don't work in TLSv1.3 and vice versa). It was very possible to specify a ciphersuite string using the older ciphersuite functions that would have completely disabled TLSv1.3 ciphersuites by accident. In order to avoid breaking lots of existing deployments we opted to separate these two functions.

Hi,
   Got it.  Thanks a lot.

**Comment by joymcg** [comment]
> No. In most cases you don't need to set the TLSv1.3 ciphersuites at all. You can just use the defaults. There are only 5 currently supported (of which 3 are in the default group).
> 
If I set the TLS1.2 cipher suites, these TLSv1.3 cipher suite will be at the front of all cipher suites?
I mean openssl will use TLS1.3 cipher suites first even though I set some tls1.2 cipher suites?

**Comment by mattcaswell** [comment]
> If I set the TLS1.2 cipher suites, these TLSv1.3 cipher suite will be at the front of all cipher suites?
I mean openssl will use TLS1.3 cipher suites first even though I set some tls1.2 cipher suites?

Yes

**Comment by richsalz** [comment]
TLS version negotiation happens *before* cipher suite selection, so if the client speaks 1.3 then the server will use that.

**Comment by kaduk** [comment]
Resolving as answered.
