### ISSUE TITLE
Failed openssl 1.4.1 installation on AIX7.2 since XCOFF32 object files are not allowed in 64-bit mode

### ISSUE THREAD

**Issue by bergen288** [openssl/openssl#11901]
I am trying to install R packages (R base is 3.6.1) on AIX7.2 server (64 bit) with no internet access.  The openssl 1.4.1 package is failed with the following error message.  Can you please help me to resolve the issue?
R CMD INSTALL -l /software/R/site-library openssl_1.4.1.tar.gz

ld: 0711-738 ERROR: Input file /usr/lib/libssl.so:
	**XCOFF32 object files are not allowed in 64-bit mode.**
collect2: error: ld returned 8 exit status
make: 1254-004 The error code from the last command is 1.
[openssl.log](https://github.com/openssl/openssl/files/4663845/openssl.log)

**Comment by mspncp** [comment]
Hi @bergen288,

we distribute OpenSSL only as source code and not in compiled form. Also, 1.4.1 is not one of our version numbers. You might be better off to ask your Manufacturer or Distributor this question.

P.S: A quick google search for

- [openssl XCOFF32 object files are not allowed in 64-bit mode](https://www.google.com/search?q=openssl+XCOFF32+object+files+are+not+allowed+in+64-bit+mode)

brought me to this IBM support page, maybe it helps answering your question:

- [IBM support - 64-bit applications fail to link against libssl.a or libcrypto.a](https://www.ibm.com/support/pages/64-bit-applications-fail-link-against-libssla-or-libcryptoa)

**Comment by bergen288** [comment]
Thanks for your hints.  The openssl package has been installed successfully after those 2 obsolete "so" file were renamed.
