### ISSUE TITLE
Link issue in docs

### ISSUE THREAD

**Issue by FdaSilvaYY** [openssl/openssl#1191]
At the bottom of these page : 
    https://github.com/openssl/openssl/blob/master/doc/apps/x509v3_config.pod
or 
    https://www.openssl.org/docs/manmaster/apps/x509v3_config.html
the SEE ALSO link to ASN1_generate_nconf(3) don't work.

...
The right URL is 
https://www.openssl.org/docs/manmaster/crypto/ASN1_generate_nconf.html

**Comment by richsalz** [comment]
I think all HTML links are broken, missing the 'html' extension.  Is that right?

**Comment by levitte** [comment]
Not really just that.  The link says `.../apps/ASN1_generate_nconf.html` when it should say `.../crypto/ASN1_generate_nconf.html`.  `pod2man` can't really help us there, as it assumes a `man` directory structure, so we should *actually* generate pages in `manmaster/man1`, `manmaster/man3`, ...  We don't today.

**Comment by fractalb** [comment]
I also found this issue with the online documentation. On the SSL_get_error documentation page, in the SEE ALSO section, the hyperlink to _err_ documentation is broken. Currently it tries to link to the URL:
https://www.openssl.org/docs/man1.0.2/ssl/err.html
where it should be
...../crypto/err.html

**Comment by mattcaswell** [comment]
This currently has the 1.1.0 milestone. Should I remove that for this one?

**Comment by levitte** [comment]
> This currently has the 1.1.0 milestone. Should I remove that for this one?

Yes.  This isn't a OpenSSL source release issue, it's strictly about our web site.

**Comment by mattcaswell** [comment]
Well yes and no. The source is also broken because links generated from source don't have ".html" on the end. The structure issue is website specific.

**Comment by levitte** [comment]
Oh, the lack of `.html` is a build issue alright.  Sorry, missed that part, and am jumping right to it now.

**Comment by levitte** [comment]
#1277

**Comment by levitte** [comment]
`.html` issue fixed and merged.  Taking away the milestone.

**Comment by richsalz** [comment]
see #1435
