### ISSUE TITLE
The crash occurred on arm64 when I called the function DSA_sign

### ISSUE THREAD

**Issue by andy-gd** [openssl/openssl#11924]
HI, I got a crash when using openssl.
I use the DSA algorithm in openssl for data signing, which normally works, but when I do a stress test (QPS 1000), it crashes after a few hours or so.

openssl version: openssl-1.0.2k
linux release version ：CentOS Linux release 7.6.1810 (AltArch)
linux kernel version : Linux version 4.14.0-115.el7a.0.1.aarch64 (mockbuild@aarch64-01.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Sun Nov 25 20:54:21 UTC 2018
CPU architecture :ARM V8

The top stack information is as follows :
Program terminated with signal 11, Segmentation fault.
#0  sha1_block_armv8 () at sha1-armv8.S:1086
#1  0x0000ffff9f71b970 in SHA1_Update (c=0xfff764041db0, data_=0xffff9f8fc897 <state+1031>, len=18446744073709551564) at ../md32_common.h:350
#2  0x0000ffff9f7e41a4 in update (ctx=0xfff77cf96eb0, data=0xffff9f8fc897 <state+1031>, count=18446744073709551608) at m_sha1.c:78
#3  0x0000ffff9f7dafcc in EVP_DigestUpdate (ctx=0xfff77cf96eb0, data=0xffff9f8fc897 <state+1031>, count=18446744073709551608) at digest.c:296
#4  0x0000ffff9f7d54a0 in ssleay_rand_add (buf=0xfff77cf97080, num=32, add=32) at md_rand.c:273
#5  0x0000ffff9f7d56f4 in ssleay_rand_seed (buf=0xfff77cf97080, num=32) at md_rand.c:333
#6  0x0000ffff9f7d667c in RAND_seed (buf=0xfff77cf97080, num=32) at rand_lib.c:145
#7  0x0000ffff9f7b08d8 in DSA_sign (type=0, dgst=0xfff77cf97080 "s\321\tb\030\215\361w\256Xc\031u\226\256\223\"\256\226\333\004Ӄ\003\204{6W\204\372\361\a", dlen=32, sig=0xfff77cf981e0 "", 
    siglen=0xfff77cf981dc, dsa=0x5b009990) at dsa_asn1.c:158

Let's look at the fourth frame：
The current line of code is:    MD_Update(&m, &(state[st_idx]), j - k);
I tried to print some parameters with GDB:
![clipboard](https://user-images.githubusercontent.com/65799679/82727079-bb947280-9d1a-11ea-812d-0b5b9678b5d3.png)
Let's look at the third parameter: j-k，  here we get a negative number: -8
However, the third parameter type of MD_Update is site_t, resulting in count=18446744073709551608, which is not normal.
I think that's probably what caused the crash

**Comment by richsalz** [comment]
1.0.2 is out of support from the project, so they may close this.  One of the major changes between 1.0.2 and 1.1.0 is replacing the wonky/wacky RNG with a real RNG.

**Comment by paulidale** [comment]
1.0.2 is out of support.  This isn't going to be fixed.
