### ISSUE TITLE
GCM IV construction algorithm ?

### ISSUE THREAD

**Issue by nanayak** [openssl/openssl#11923]
I am using OpenSSL 1.1.1d as reference and want to understand the mechanism/algorithm used to construct GCM IVs.

Is there a default algorithm and alternatives that can be configured to be used (for example NIST 800-38D describes deterministic vs RBG based) ? Additionally, is the default IV length 96 bits and what is the maximum configurable size ? Any pointers to code/docs will be helpful. Thank you!

**Comment by paulidale** [comment]
The best way to do this IMO is:

```c
unsigned char IV[12];

if (RAND_bytes(IV, sizeof(IV)) <= 0)
    error();
```

It is the least prone to error way of producing a GCM IV.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
