### ISSUE TITLE
'openssl fipsinstall' doesn't work as advertised

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#11929]
The manual has an example:

https://github.com/openssl/openssl/blob/5e5bc836fbc5b1c0af428864f5286bbb225f7baf/doc/man1/openssl-fipsinstall.pod.in#L148-L150

But trying it (with minimum adjustment for running it in the build tree) fails:

``` console
$ ./util/wrap.pl apps/openssl fipsinstall -module ./providers/fips.so -out fips.cnf -provider_name fips -section_name fipsinstall -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:000102030405060708090A0B0C0D0E0F10111213
HMAC : (Module_Integrity) : Fail
INSTALL FAILED
C0:3D:A8:13:2F:7F:00:00:error:common libcrypto routines:provider_activate:init fail:../master/crypto/provider_core.c:503:
C0:3D:A8:13:2F:7F:00:00:error:configuration file routines:module_run:module initialization error:../master/crypto/conf/conf_mod.c:212:module=providers, value=provider_section, retcode=-1      
```

Looking at what the test recipes do, it seems that only a MAC key with zeroes work:

``` console
$ ./util/wrap.pl apps/openssl fipsinstall -module ./providers/fips.so -out fips.cnf -provider_name fips -section_name fipsinstall -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:00
HMAC : (Module_Integrity) : Pass
SHA1 : (KAT_Digest) : Pass
SHA2 : (KAT_Digest) : Pass
SHA3 : (KAT_Digest) : Pass
TDES : (KAT_Cipher) : Pass
AES_GCM : (KAT_Cipher) : Pass
RSA : (KAT_Signature) : Pass
ECDSA : (KAT_Signature) : Pass
DSA : (KAT_Signature) : Pass
HKDF : (KAT_KDF) : Pass
SSKDF : (KAT_KDF) : Pass
HASH : (DRBG) : Pass
CTR : (DRBG) : Pass
HMAC : (DRBG) : Pass
DH : (KAT_KA) : Pass
ECDH : (KAT_KA) : Pass
INSTALL PASSED
```

Eye-balling the code seems to confirm this, as the self test uses `fixed_key` is key data:

https://github.com/openssl/openssl/blob/5e5bc836fbc5b1c0af428864f5286bbb225f7baf/providers/fips/self_test.c#L153-L161

It's initialized when defined:

https://github.com/openssl/openssl/blob/5e5bc836fbc5b1c0af428864f5286bbb225f7baf/providers/fips/self_test.c#L38

... and not modified anywhere.

@slontis, you know these things better than most, is this an omission?

**Comment by richsalz** [comment]
FWIW, if I edit ```test/recipes/30-test_fipsinstall.t``` and replace all ":00" with ":33" I also get failures.

**Comment by slontis** [comment]
Yes the library is using a fixed internal key. So changing the app to use a key that doesnt match it will fail. Potentially the key could change between versions.. It may be better to change the documentation. (Not sure putting the key in a header is a good idea either).

**Comment by levitte** [comment]
Ah, right, I had forgotten the discussion around this.  In retrospect, I'm not quite sure about the approach, and more specifically, that anyone using `openssl fipsinstall` must "magically know" the correct MAC key.  This might be a good topic for the next vidcall.

**Comment by richsalz** [comment]
I dislike a single key shared across everything.  Really really dislike it. If the key is fixed value, then what is the point of having the flag in the fipsinstall command? I think this makes it easier to swap libraries and therefore weakens security.

**Comment by levitte** [comment]
"everything" is a bit over the top. And this is about integrity verification, i.e checking that the module used is the one that was installed.

**Comment by richsalz** [comment]
Everything is over the top?  How do I make my FIPS canister use a different key?  Especially if the instructions don't allow for that?

**Comment by slontis** [comment]
Please don't use the word 'security' in relation to this (unless you also use the words 'false sense of'). This is a sanity check not a security check.

**Comment by slontis** [comment]
i.e It only tells you if the source is corrupted - not that it is forged.

**Comment by richsalz** [comment]
No, it's a security issue.  I can build and deploy a provider onto my network, and as long as the HMAC key is secret, then nobody can replace the provider without my knowing because the HMAC key is public.

Make sense?

**Comment by levitte** [comment]
@richsalz, how secret do you imagine that this key can be, and how do you imagine keeping it secret to that level?

**Comment by richsalz** [comment]
I can keep it as secret as keeping "secret key" secret. But in the larger sense, this use-case is not uncommon.  It is susceptible on any platform where the attacker can write, but not read. For example, anyone running FIPS code on a cloud service provider should be concerned about this.

**Comment by t8m** [comment]
But the "secret" key must inevitably be built-into the FIPS module otherwise it cannot verify itself on POST. So how could you keep it secret?

**Comment by levitte** [comment]
> But the "secret" key must inevitably be built-into the FIPS module otherwise it cannot verify itself on POST.

I anticipate that it would be more practical to have it in `fipsinstall`'s output file.

**Comment by richsalz** [comment]
As Richard said, it will be in the output file.  And I am assuming an attacker cannot read things, but can replace them.  This is a common vulnerability, especially for hosted cloud services.

**Comment by paulidale** [comment]
Key material moving across the FIPS boundary causes all manner of problems.  Despite the key being a public known constant, it's a _key_ and the relevant rules most likely apply.

**Comment by paulidale** [comment]
My vote would be to fix the _key_ to a known value and hard code it inside the provider.

**Comment by richsalz** [comment]
Please answer the questions and address the issue I originally raised in https://github.com/openssl/openssl/issues/11929#issuecomment-633314978

**Comment by richsalz** [comment]
As things stand right now, it is *the exact same thing* as if the release-signing key were posted, is it not?  (That's a rhetorical question.  i believe it is, and apparently some disagree, to my amazement.)

**Comment by slontis** [comment]
The answer to your question is - The option to set the key will be removed from the app. It was never intended to be used as a security parameter.

**Comment by paulidale** [comment]
You don't use different key.  We should remove the command line option from the fipsinstall app.

The entire purpose of the integrity check is to detect random bit flips.  It is not intended to detect malicious changes -- as @t8m noted, it can't.  It is also not intended to be a replacement for release-signing.

**Comment by richsalz** [comment]
Then why HMAC and not SHA256 digest?

Will someone be able to download OpenSSL and specify a different key at configuration time?

**Comment by paulidale** [comment]
Something gets easier if HMAC is used.  I don't remember exactly what and a quick dash in to the abyss of 140-2 documents didn't remind me.

Deep in the maze, I did stumble over IG 7.4 which says that the integrity check key isn't a CSP and doesn't have to meet the zeroization requirements.  One could extend this to mean that it doesn't need to meet the other requirements for a CSP (in this case it can pass the module boundary freely) but it is safer not to.

**Comment by slontis** [comment]
> Will someone be able to download OpenSSL and specify a different key at configuration time?

NO

**Comment by richsalz** [comment]
I mean, for example, Ubuntu downloads and distributes OpenSSL and the FIPS module.  They have to use an all-bits-zero key?  The same key as Oracle?  The same key as Akamai?

If so, we need to discuss this.

**Comment by slontis** [comment]
@t-j-h care to comment?

**Comment by t-j-h** [comment]
The key serves no security purpose whatsoever. It is entirely for detecting inadvertent corruption of the executable image. It is not meant to be secret and for hardware modules a simple CRC32 is acceptable. Do not think this as a key - as it really isn't. It is simply the input to a checksum algorithm. 
If someone feels the need to have a different value they can change the source to do so. It isn't something that needs to be configurable - except in the sense of an easy way to test things during development which is what @slontis was doing.

**Comment by slontis** [comment]
Using HMAC sha for the integrity check also allows us to skip doing some of the self tests KATS..

**Comment by levitte** [comment]
> As Richard said, it will be in the output file. And I am assuming an attacker cannot read things, but can replace them. This is a common vulnerability, especially for hosted cloud services.

Not matter what the key is, the generated checksum will have to match what's in the `fipsinstall` output file, so if the attacker wants to replace your copy of fips.so with someone other, they will have to run `fipsinstall` on it and replace that output file too, or there will be a checksum mismatch.  Of course, it's always possible to imagine that someone might be able to get the same checksum for a different fips.so, but then the weakness isn't in the key.

Of course, the attacker could replace your fips.so with an exact copy, but I really don't see the worry with that :wink:

**Comment by slontis** [comment]
As stated quite a few times, this mechanism is not meant to stop an attacker.

**Comment by levitte** [comment]
Yup.  This was actually hashed quite a while ago, back when we worked on the [design document](https://www.openssl.org/docs/OpenSSL300Design.html) (which does talk about this).  If memory serves, what I wrote in my previous comment just regurgitates what was said way back then...  it seems like a reminder was needed.

**Comment by richsalz** [comment]
No reminder is needed.  I still dislike this and want to discuss it on the next call.

As a minimum, a config parameter to specify the key.  Or some dispensation in the instructions.

If the key serves no security function, and CRC is acceptable, why not SHA256?

**Comment by richsalz** [comment]
Responding to my last question: the answer is using HMAC allows us to skip some KAT tests.  I don't get the rationale, but if it's in the FIPS, I can accept that.

Will the team accept a config PR to set the key?

As for it being mentioned in the design doc, it says "with a known fixed key."  It does *not* say "with a known fixed global key."  Therefore, my being (very unpleasantly) surprised by this is not unreasonable.

As for "not designed to stop attacks" sure.  But this is an easy hole to fix.

As for https://github.com/openssl/openssl/issues/11929#issuecomment-633779947, yes, the adversary has to replace two files, the FIPS module and its config file.  (Well, duh, I thought that was obvious.)

As a FIPS sponsor, Akamai does not want to share the HMAC key with every other downstream FIPS installation.

**Comment by slontis** [comment]
Rich the question has been answered, please stop now.

The only reason I added the key originally, was that I thought that it might also be useful for third party fips providers. The (same applies to the input algorithm also which is also hardwired in code). Both will now be removed from the app.

**Comment by paulidale** [comment]
Can we close this, the question is answered?

**Comment by slontis** [comment]
@richsalz I think we addressed everything required here.

**Comment by richsalz** [comment]
Yes, we have a build-time key now that's great.

**Comment by mattcaswell** [comment]
Closing.
