### ISSUE TITLE
Provide a compilation constant for digest sizes

### ISSUE THREAD

**Issue by tawmoto** [openssl/openssl#11925]
I am trying to use some hashing functions (ex: sha256), but with the modern approach, there is no compiling-time constant for `SHA256_DIGEST_LENGTH`.

The recommended solution is to use `EVP_MD_size(EVP_sha256())`, which is not constant at compile time and therefore I cannot create the output buffer on stack, I have to create it on heap. The alternative is to use `EVP_MAX_MD_SIZE`, but why allocate so much?

old way: `unsigned char result[SHA256_DIGEST_LENGTH]`
new way:  `unsigned char *result = OPENSSL_malloc(EVP_MD_size(EVP_sha256()));  // then free()`

Is there another solution?
Thanks
P.S. Sorry, I posted it as a bug, it should be a feature request.thx

**Comment by slontis** [comment]
@paulidale - maybe these should be outside the deprecated section?

**Comment by tawmoto** [comment]
@paulidale Is there a good reason why those functions are deprecated, except for flexibility?
 I am asking because the new ones (`EV_`) are more intrusive and maybe slower, for example I had to link also with `-ldl -pthread`, which was not needed in the past. Otherwise it won't work.

**Comment by paulidale** [comment]
Does `#include <openssl/sha.h>` work?  The constant is defined there and isn't conditional.

**Comment by tawmoto** [comment]
> Does `#include <openssl/sha.h>` work? The constant is defined there and isn't conditional.

Yes, it should work, but I thought that those headers(`sha.h, md5.h` will be deprecated for external use. Or just the functions will be deprecated?

**Comment by paulidale** [comment]
Some of the functions and some of the #defines are being deprecated.  The sizes aren't.
