### ISSUE TITLE
How to add postfix for debug version?

### ISSUE THREAD

**Issue by playgithub** [openssl/openssl#11936]
For example, add "-d" for debug binaries, so that debug and release can be in one directory.

**Comment by mattcaswell** [comment]
I'm not entirely sure I understand your question. Configure has the `--debug` option as documented in the INSTALL file:

````
  --debug
                   Build OpenSSL with debugging symbols and zero optimization
                   level.
````

**Comment by playgithub** [comment]
I'd like to put debug & release binaries in one directry, like:
`bin/libssl-1_1-x64-d.dll`
`bin/libssl-1_1-x64.dll`
instead of
`debug/bin/libssl-1_1-x64.dll`
`release/bin/libssl-1_1-x64.dll`

**Comment by kaduk** [comment]
I'd recommend looking into the "variant SONAME" feature introduced by 822b5e2645a99bea15329bd66c9723c7e7119cdb

**Comment by playgithub** [comment]
Good way, thanks.
But I'll keep two different folds for debug & release now for simplicity.
I'm studying CMake now, I will try to support it by cmake.

**Comment by SpareSimian** [comment]
I think the correct term is "suffix", not "postfix". 

"perl Configure --debug VC-WIN64A" appears to properly create the debug build but I don't see how to request a suffix so that the result looks like "libssl_static-d.lib". What incantation is needed?

**Comment by kaduk** [comment]
> I think the correct term is "suffix", not "postfix".
> 
> "perl Configure --debug VC-WIN64A" appears to properly create the debug build but I don't see how to request a suffix so that the result looks like "libssl_static-d.lib". What incantation is needed?

The documentation is at https://github.com/openssl/openssl/blob/f309b3f6087db6c83126f8f227f1fc4984cf24b1/Configurations/README.md?plain=1#L129-L149 but in short you'll need to create a new configuration target other than VC-WIN64A.  But this is pretty straightforward, just dropping a new file in Configurations/ and using `inherit_from` to grab the VC-WIN64A defaults and just add the `shlib_variant` as the sole new piece of configuration.

**Comment by SpareSimian** [comment]
I created such a drop-in file and the resulting makefile doesn't have the variant suffix before the .lib extension. 
```
my %targets = (
    "VC-WIN64A-DEBUG" => {
        inherit_from     => [ "VC-WIN64A" ],
        # add -d suffix to lib names for debug builds
        shlib_variant    => "-d",
    },
);
```
My first attempt used the picker function to set the value to "-d" for debug and "" for release and I thought I was doing something wrong when the makefile lacked the debug sonames. 
```
        shlib_variant     => picker(debug   => "-d",
                                    release => ""),

```

**Comment by SpareSimian** [comment]
Ah, I see it. The "-d" is getting added for the shared libraries but not for the static ones, which are what I'm hoping to build with.

**Comment by blazewater-gmail** [comment]
> Ah, I see it. The "-d" is getting added for the shared libraries but not for the static ones, which are what I'm hoping to build with. And it only affects the names of the .pdb files, not the .lib or .dll files.

hi, did you know how to add same postfix to related .lib file?
