### ISSUE TITLE
Not able to find -trace option at openssl s_server and s_client.

### ISSUE THREAD

**Issue by ngbk1993** [openssl/openssl#11930]
[configdata.dump.txt](https://github.com/openssl/openssl/files/4672452/configdata.dump.txt)
Hi, i compiled open ssl with the parameter dumped in the configdata.dump.txt file, (--debug enable-ssl-trace) and wish to get a -trace option when running openssl s_server with. However there is error saying that option not found. Please help.

openssl version = 1.1.1d

**Comment by ngbk1993** [comment]
sorry my bad, I didn't compile properly.

**Comment by mattcaswell** [comment]
For future reference, if anyone else has this problem, you have to compile with the option "enable-ssl-trace" in order to get the "-trace" options with s_client and s_server.
