### ISSUE TITLE
Failure in to make install, what have I done wrong?

### ISSUE THREAD

**Issue by munocat** [openssl/openssl#11931]
I have built Openssl version 1.1.1 in Oracle Solaris 10 (Ultra Sparc II). there is not build issues as far as I can tell.

When I come in install, I enter the super user account and do a make install

I get the following errors:

make install
make depend && make _all
Possible unintended interpolation of @buildfile in string at configdata.pm 14965.
Possible unintended interpolation of @buildfile in string at configdata.pm 14965.
Possible unintended interpolation of @buildfile in string at configdata.pm 14965.
Possible unintended interpolation of @buildfile in string at configdata.pm 14965.
Possible unintended interpolation of @buildfile in string at configdata.pm 14965.
Possible unintended interpolation of @buildfile in string at configdata.pm 14965.
Possible unintended interpolation of @tmpl in string at configdata.pm line .
Possible unintended interpolation of @tmpl in string at configdata.pm line .
Possible unintended interpolation of @tmpl in string at configdata.pm line .
Bareword found where operator expected at configdata.pm line 15038, near "o, and you will get the information you ask for.  See L</OPTIONS"
  (Might be a runaway multi-line // string starting on line 14965)
Global symbol "@buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "@buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "$buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "@buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "$buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "@buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "@buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "@buildfile" requires explicit package name at configdata.pm 14965.
Global symbol "@tmpl" requires explicit package name at configdata.pm line .
Global symbol "@tmpl" requires explicit package name at configdata.pm line .
Global symbol "@tmpl" requires explicit package name at configdata.pm line .
configdata.pm has too many errors.
Compilation failed in require at ./util/add-depends.pl line 13.
BEGIN failed--compilation aborted at ./util/add-depends.pl line 13.
*** Error code 255
The following command caused the error:
perl ./util/add-depends.pl gcc
make: Fatal error: Command failed for target `depend'
Current working directory /home/pi/openssl-1.1.1
*** Error code 1
make: Fatal error: Command failed for target `all'

I googled to see if there were any solution to this, but I could not find an answer.

I am guess I must of not configured something correctly

Thank you for your interest in OpenSSL. If this is your first question,
please take the time to read the following lines before posting it.

For general questions about *using* OpenSSL:

    If you have questions about how to use OpenSSL for specific tasks
    or how to solve certain problems you have when using it, you might
    want to ask them on the openssl-users@openssl.org mailing list.
    There you can get help from a great community of OpenSSL users,
    not only (but including) the OpenSSL developers. For more information
    about our mailing lists, see
    https://www.openssl.org/community/mailinglists.html.

For questions related to build issues:

    Please use the 'Bug report' template.

For other questions:

    Please describe your problem as concisely as possible while giving
    us enough information to understand your problem. Example code
    or example commands are highly appreciated if they help us to
    better understand what you are trying to achieve.

    Also, please remember to tell us which OpenSSL version you are
    using and whether it is system provided or you built it yourself.
    In the latter case, please also send us your build configuration.
    With OpenSSL before 1.1.1, the configuration output comes from the
    configuration command.  With OpenSSL 1.1.1 and on, you can obtain
    the information by running the command `perl configdata.pm --dump`
    in the root directory of the source tree.

Please remember to put ``` lines before and after any commands plus
output and code, like this:

    ```
    $ echo output output output
    output output output
    ```

    ```
    #include <stdio.h>

    int main() {
        int foo = 1;
        printf("%d\n", foo);
    }
    ```
-->

**Comment by levitte** [comment]
Would you mind attaching that configdata.pm?

**Comment by munocat** [comment]
I had to add .txt to the end of the file for it to be accepted by github


[configdata.pm.txt](https://github.com/openssl/openssl/files/4672559/configdata.pm.txt)

**Comment by levitte** [comment]
Thank you.  I can't find anything wrong at the indicated lines.  Most of all, this error seems to be central:

```
(Might be a runaway multi-line // string starting on line 14965)
```

The line in question is this:

``` perl
            $prefix //= '';
```

According to https://perldoc.perl.org/perlop.html#Assignment-Operators, `//=` is a perfectly normal assignment operator...  so I would like to know what perl version you're using.  Do note that we require perl 5.10.0, which is mentioned in [NOTES.PERL](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/NOTES.PERL)

**Comment by munocat** [comment]
The perl version is 5.10.1

**Comment by levitte** [comment]
Okie. The weird thing is that we use that operator all over the place, such as `Configure` (which is called by `config`, FYI) and if I understand correctly, you didn't have any issues there.

Do you get similar errors when simply running that script, i.e this? 

``` console
$ ./configdata.pm
```

**Comment by munocat** [comment]
Same error, 

There was no problem running the config nor make. 

make test did not work, I believe that is down to the version of perl.

**Comment by levitte** [comment]
Okie.  What happens if you apply this patch to configdata.pm?  (frankly, I'm grasping at straws.  I don't have perl 5.10.1 on my machine...  it won't even compile)

``` diff
--- "configdata.pm.org"	2020-05-24 09:14:21.089185432 +0200
+++ "configdata.pm"	2020-05-24 09:48:49.823275855 +0200
@@ -14959,10 +14959,11 @@
     if ($dump || $makevars) {
         print "\nMakevars:\n\n";
         foreach my $var (@makevars) {
-            my $prefix = '';
+            my $prefix;
+            my $empty = '';
             $prefix = $config{CROSS_COMPILE}
                 if grep { $var eq $_ } @user_crossable;
-            $prefix //= '';
+            $prefix //= $empty;
             print '    ',$var,' ' x (16 - length $var),'= ',
                 (ref $config{$var} eq 'ARRAY'
                  ? join(' ', @{$config{$var}})
```

**Comment by munocat** [comment]
I figured out what I had done wrong, even though I had installed perl 5.10.1, when I logged as root,  in to 'make install', root was picking up on perl 5.8, which was installed by the OS. I moved the call top perl 5.10.1 to the front of the path, So it worked, kind off.

It would fail with a ln error, I fixed this by editing the Makefile and replacing all the ln -sf with just ln -s

Thank you

**Comment by levitte** [comment]
Ah!  Thanks for checking that out.

Regarding `ln`, I'm surprised it doesn't handle the `-f` flag.  I thought that had become standard eons ago...

**Comment by kbulgrien** [comment]
For posterity, and for the benefit of any others that may find this issue at the top of their web search results:

I ran into this problem while attempting a build of 1.1.1n, except that it occurred while attempting to run Configure.

```
Configuring OpenSSL version 1.1.1n (0x101010efL) for sco5-gcc
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile
Possible unintended interpolation of @buildfile in string at configdata.pm line 15251.
Possible unintended interpolation of @buildfile in string at configdata.pm line 15251.
Possible unintended interpolation of @buildfile in string at configdata.pm line 15251.
Possible unintended interpolation of @buildfile in string at configdata.pm line 15251.
Possible unintended interpolation of @buildfile in string at configdata.pm line 15251.
Possible unintended interpolation of @buildfile in string at configdata.pm line 15251.
Possible unintended interpolation of @tmpl in string at configdata.pm line 15251.
Possible unintended interpolation of @tmpl in string at configdata.pm line 15251.
Possible unintended interpolation of @tmpl in string at configdata.pm line 15251.
Bareword found where operator expected at configdata.pm line 15324, near "option, and you will get the information you ask for.  See L</OPTIONS"
  (Might be a runaway multi-line // string starting on line 15251)
Global symbol "@buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "@buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "$buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "@buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "$buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "@buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "@buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "@buildfile" requires explicit package name at configdata.pm line 15251.
Global symbol "@tmpl" requires explicit package name at configdata.pm line 15251.
Global symbol "@tmpl" requires explicit package name at configdata.pm line 15251.
Global symbol "@tmpl" requires explicit package name at configdata.pm line 15251.
configdata.pm has too many errors.
Compilation failed in require.

```

In this case, the system perl (/usr/bin/perl) was v5.8.8, but perl v5.10.1 was installed beneath /usr/local (/usr/local/bin/perl).

I noted a propensity of Configure to create configdata.pm with "#! /usr/bin/perl".  The Configure problem was solved by adding the following arguments to the Configure command-line:

              PERL=/usr/local/bin/perl \
              HASHBANGPERL=/usr/local/bin/perl \

I also happened to have to make this change:

$ diff -u Configure.orig Configure
--- Configure.orig      2022-03-15 09:37:47.000000000 -0500
+++ Configure   2022-04-26 21:44:21.000000000 -0500
@@ -1,4 +1,4 @@
-#! /usr/bin/env perl
+#! /bin/env perl
 # -*- mode: perl; -*-
 # Copyright 2016-2021 The OpenSSL Project Authors. All Rights Reserved.
 #

Which really is better accomplished with:

$ su -c "ln -s /bin/env /usr/bin/env"

This system has no trouble 'ln -sf'.
