### ISSUE TITLE
How to distinguish between a legacy and provided PKEY

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#11945]
Given a PKEY, what is the best way to figure out whether PKEY is a legacy or a provided key?
Before commit https://github.com/openssl/openssl/commit/5e5bc836fbc5b1c0af428864f5286bbb225f7baf it was possible by comparing the PKEY type using EVP_PKEY_base_id(key) to EVP_PKEY_NONE. As far as I understand, this is no longer the case as EVP_PKEY_base_id also returns a valid type for provided keys.

Maybe the design goal is not to expose the internal implementation type so obtaining this information should not be possible.

**Comment by levitte** [comment]
The intention is for this to be an implementation detail and to work transparently with the public interfaces as much as possible (we do walk a fine line of what's reasonable, some interfaces are strictly legacy, and quite frankly, the set of such interfaces hasn't been clearly defined yet).

**Comment by matbech** [comment]
Is there a workaround for this issue at the moment? Because openssl still creates legacy keys in some places and I need to know how to export the key params, given just a PKEY.

**Comment by matbech** [comment]
I'm using this workaround at the moment to detect a provided key:
EVP_PKEY_gettable_params(key) != NULL

**Comment by mattcaswell** [comment]
> EVP_PKEY_gettable_params(key) != NULL

A provided key isn't required to implement the `gettable_params` function, although I think currently all of OpenSSL's own implementations do. Its possible that at some point we will implement a key that doesn't, or some third party provider will.

It doesn't seem unreasonable for us to implement an `EVP_PKEY_provider()` or similar to return the associated provider as we have done with `EVP_CIPHER`, `EVP_MD` etc. Although EVP_PKEY's can have more than once associated provider which might complicate things. @levitte?

**Comment by levitte** [comment]
We do have internal methods to distinguish them (see the comment above `struct evp_pkey_st` as well), which would be useful for this:

https://github.com/openssl/openssl/blob/b0d5c1cb0773588dca69875e122fac75252ccdf6/include/crypto/evp.h#L535-L538

While I was hoping that we could keep things transparent to a fault, I'm not opposed in letting applications know.

**Comment by matbech** [comment]
@levitte Thank you. I noticed the macros but they cannot be used unless the evp_pkey_st struct is known, which isn't the case unless the internal header files are pulled in. The requirement came up because of the EVP_PKEY_get_bn_param issue that I have reported here: https://github.com/openssl/openssl/issues/11935
Solving this problem would remove my requirement to know the key type.

**Comment by levitte** [comment]
Well yeah, we'd have to write a public function, but that would be quite easy given those internal macros.

**Comment by matbech** [comment]
@paulidale The issue isn't really solved (has this public function be added yet) or if it is, maybe you can provide some insight?

**Comment by paulidale** [comment]
Overzealously on my part.  I've reopened it.

**Comment by nhorman** [comment]
does evp_pkey_is_legacy do what is needed here?

Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by paulidale** [comment]
> does evp_pkey_is_legacy do what is needed here?

That's an internal function, so no.

**Comment by t8m** [comment]
At least for some provided keys (those without legacy implementation) EVP_PKEY_KEYMGMT will be returned.

**Comment by t8m** [comment]
IMO there should be no need for this function anymore and given we will remove the legacy key support completely at some point it would be just adding a baggage to be removed.
