### ISSUE TITLE
OpenSSL 3.0.0 with 1.1.1 compatibility and FIPS property

### ISSUE THREAD

**Issue by gschaber** [openssl/openssl#11952]
Will it be possible for a client to use OpenSSL 3.0.0 without changing the source code (that was created for the OpenSSL 1.1 API), and nevertheless make use of the global FIPS setting? So basically keep the old client source code, and make it FIPS aware just by adding the global FIPS setting?

**Comment by levitte** [comment]
The intention is for it to work as much as possible with only a configuration file change. We're not making an absolute guarantee, though, but the expectation is in the very high range.

**Comment by mattcaswell** [comment]
There's quite a lot of discussion about what you need to do to make an application "FIPS" aware on the 3.0 wiki page:

https://wiki.openssl.org/index.php/OpenSSL_3.0
