### ISSUE TITLE
PEM_read_bio_ex might return 0 without setting the error message in some situation

### ISSUE THREAD

**Issue by spacewander** [openssl/openssl#11962]
When `EVP_DecodeFinal` doesn't update the `&taillen`, then `len` is 0:
https://github.com/openssl/openssl/blob/93f99b681ab5a1cf7062053323e09b0cad5ff854/crypto/pem/pem_lib.c#L964-L966

This execute path might be triggered by a malformed PEM file.

Another possible case:
https://github.com/openssl/openssl/blob/93f99b681ab5a1cf7062053323e09b0cad5ff854/crypto/pem/pem_lib.c#L968-L973

**Comment by nhorman** [comment]
Is there a reproducer for this, something to demonstrate a practically an issue?

Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by spacewander** [comment]
I can't recall how I discovered this 4 years ago. Anyway, OpenSSL has changed a lot since that. Feel free to close it.
