### ISSUE TITLE
What's the plan of OpenSSL 3.0 FIPS Module receives a FIPS certificate?

### ISSUE THREAD

**Issue by Tomasmule2015** [openssl/openssl#11960]
hi, I found the Release Strategy of openssl3.0, but can not find about fips certificate, can you tell me about this plan?
1. what's the plan of openssl3.0 fips module receives a fips certificate?
2. does openssl3.0 fips module receives a fips certificate before release?

**Comment by mattcaswell** [comment]
> does openssl3.0 fips module receives a fips certificate before release?

We are working closely with our lab during the development phase of OpenSSL 3.0, and the lab will be performing a lot of their preliminary testing during our alpha and beta phases. As soon as OpenSSL 3.0 is released the module will undergo its final testing with the lab and then all the relevant paper work should be submitted shortly afterwards. The actual certificate will be issued sometime later - the timescale for this is not under our control.

Back in late February I gave a talk with Ashit Vora from our lab about OpenSSL 3.0 and FIPS. You can listen to it here:

https://www.rsaconference.com/usa/agenda/openssl-and-fips-they-are-back-together

If you don't want to listen to the whole thing you might want to listen
to Ashit's comments on the likely validation timescale between 35:18 and
38:15 on the recording.
