### ISSUE TITLE
Compiling Openssl using gcc

### ISSUE THREAD

**Issue by fatimahkj** [openssl/openssl#11979]
Hi, 

I would like to ask if there is a way to compile the library using GCC?

Thanks in advance.

**Comment by mattcaswell** [comment]
> I would like to ask if there is a way to compile the library using GCC?

On which platform? I use gcc all the time on Linux.

**Comment by fatimahkj** [comment]
ME too I use Linux. 
However, I want to compile all the c files in the OpenSSL library using GCC.  Do I have to set a test file? or I can do it without?

can you share the command line with me? 

Thanks for your quick response.

**Comment by mattcaswell** [comment]
You will find the build instructions in the INSTALL file in the top level directory of the distribution. Assuming you are using 1.1.1 you can also read it here:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/INSTALL

To just get on with it, scroll down to the "Quick Start" section here:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/INSTALL#L75

**Comment by mattcaswell** [comment]
Look like this was answered so closing.
