### ISSUE TITLE
fipsld recursively invokes itself if FIPSLD_CC is unset and CC=fipsld

### ISSUE THREAD

**Issue by elagergren-spideroak** [openssl/openssl#11978]
Our build tooling only allows us to select the compiler with `CC` (i.e., we cannot invoke `fipsld` directly), so we set `FIPSLD_CC=/path/to/compiler` and `CC=/path/to/fipsld`.

If both environment variables are set, this works just fine. But if `FIPSLD_CC` is unset, `fipsld` recursively calls itself and compilation seemingly hangs. Ideally, `fipsld` would exit with an error message instead of seemingly hanging.

```
curl -L https://www.openssl.org/source/openssl-fips-2.0.16.tar.gz | tar xf -
cd openssl-fips-2.0.16/fips/
cat << EOF > test.c
int main(void) { return 1; }
EOF
# Uncommenting `#set -x` in `fipsld` makes the bug much more apparent.
( export CC="$(pwd)/fipsld" ; env -u FIPSLD_CC "${CC}" test.c ) # hangs indefinitely
```

**Comment by levitte** [comment]
Don't do that, then.

**Comment by elagergren-spideroak** [comment]
@levitte With all due respect, that's a little flippant.

More specifically, it's easier said than done. If I could somehow ensure that nobody building our project ever forgets to set `FIPSLD_CC`, I would. Alas.

**Comment by richsalz** [comment]
You tell folks not to use that script, but instead a wrapper that exists if both variables aren't defined.

Note that the FIPS 2 module is not supported, and 1.0.2 was end-of-life months ago.  Yes, this leaves you in a hard position.  But hey, you got it for free, right? :)

**Comment by elagergren-spideroak** [comment]
@richsalz we're ahead of you on that one :)

I understand what support is offered for FOM 2 and 1.0.2. Bug reports can still be useful, though. Perhaps `fipsld` is going to be repurposed for FOM 3? From the outside, it's impossible to know. Thus, the bug report.

**Comment by mattcaswell** [comment]
> Thus, the bug report.

Thanks.

FOM 3 is completely unrelated to FOM 2. It has been written from scratch. Unfortunately FOM2 is no longer receiving updates so this won't get fixed.

**Comment by levitte** [comment]
Sorry for coming off as flippant.
`fipsld` will not be repurposed for the new FIPS module. The integrity check mechanism is completely different.

**Comment by elagergren-spideroak** [comment]
@levitte no worries. 

@mattcaswell @levitte awesome, I'll close this then. Cheers.
