### ISSUE TITLE
1.1.0-pre5 generates problematic Perl scripts on OS X.

### ISSUE THREAD

**Issue by DomT4** [openssl/openssl#1199]
I'm not entirely comfortable working with Perl so please forgive any glaring ignorance here. The `Configure` script from [1.0.2](https://github.com/openssl/openssl/blob/4e16885c8c0e28e9586f3abe546cdf976bd21875/Configure#L1204-L1205) contains:

```
$perl=$ENV{'PERL'} or $perl=&which("perl5") or $perl=&which("perl")
````
Which by default (i.e. without `PERL` set in the env, with only the system `perl` installed) on OS X generates scripts (`c_rehash`, `tsget`, etc) with the hashbang `#!/usr/bin/perl` as expected.

Something similar enough was present in the 1.1.0 `Configure` script until https://github.com/openssl/openssl/commit/5902821d81ced5e7c5db972e4b569848500940f7, when it was modified a bit. Since that point running `./Configure` on OS X reflects an unprefixed `perl` command (`PERL          =perl`) which seems to be passed onto the Perl scripts:

```
~> cat c_rehash
#!perl

# WARNING: do not edit!
# Generated by Makefile from tools/c_rehash.in
...
[snip]
```

Which when executed causes this error:
```
Can't open perl script "
# WARNING: do not edit!
# Generated by Makefile from too": No such file or directory
```
It works fine if you execute `perl c_rehash`, but I don't know if that change was intentional? I couldn't find anything documented saying you'd have to call OpenSSL Perl scripts with `perl` every time from this release.

The generated `configdata.pm` file for that build can be found [here](https://gist.github.com/DomT4/75f901ba4a67b09b8b195500e09de981).

If I revert https://github.com/openssl/openssl/commit/5902821d81ced5e7c5db972e4b569848500940f7 things go back to working against the system Perl on OS X, with `./Configure` confirming `PERL          =/usr/bin/perl` and the `c_rehash` script containing the expected hashbang again.

This problem seems somehow related to the system Perl. If I `brew install perl` and then re-run the OpenSSL build process it correctly detects it with the full path:

```
PERL          =/usr/local/Cellar/perl/5.24.0_1/bin/perl
```
reflected in `c_rehash` which functions as-expected again with the hashbang `#!/usr/local/Cellar/perl/5.24.0_1/bin/perl`.

If it's helpful:

```
uname -prsv
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Wed Jun  1 11:10:40 PDT 2016; root:xnu-3248.60.4~4/RELEASE_X86_64 i386

/usr/bin/perl --version
This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

/usr/local/Cellar/perl/5.24.0_1/bin/perl --version
This is perl 5, version 24, subversion 0 (v5.24.0) built for darwin-thread-multi-2level
```

**Comment by levitte** [comment]
You know, you're quite correct.  I just had a look at the `perlvar` manual, and it does offer much more secure examples to do this.  I'll get back with a PR

**Comment by levitte** [comment]
#1201

**Comment by DomT4** [comment]
Can confirm #1201 fixes the problem for me locally against a vanilla system OpenSSL. `Configure` Perl declaration & script hashbang both as-expected.

**Comment by dot-asm** [comment]
I would argue that binding CA.pl to perl executable used at configure and compile time is not necessarily right thing to do. I mean why does execution-time environment have to be same as compile-time one? It's common place that it's not. Question should be if CA.pl actually has same strict requirement on perl as Configure, and if it doesn't (I can't see that it does except for `use warnings`), then it is better off with `#!/usr/bin/env perl` instead of #!{- $config{perl} -}.

This is not argument against #1201, but against introducing unnecessary dependencies between compile and execution time.

**Comment by levitte** [comment]
I have no issues with having `#!/usr/bin/env perl` in `CA.pl`, `c_rehash` or `tsget`...  arguments have gone back and forth about this, and I'll admit that I've totally lost track at this point.

That being said, it's possible to configure like this as well:

```
PERL='/usr/bin/env perl' ./config
```

**Comment by dot-asm** [comment]
> `PERL='/usr/bin/env perl' ./config`

Right, and the reason for why people wanted that is exactly my point. People who wanted it to work were those who produced packages and they are acutely aware of the fact that execution-time environment is not compile-time one, nor does it have to be. Question is if we recognize that by adhering to `#!/usr/bin/env perl` when appropriate or do we rely on "underground" to figure out the trick?

**Comment by levitte** [comment]
I've made this discussion into a separate issue, #1202, as it seems off topic here.

**Comment by levitte** [comment]
I believe that the solution in #1282 fixes this issue, so closing.  Should there be more problems, please open a new issue.
