### ISSUE TITLE
OpenSSL 1.0.1t suddenly evaluates expiry certificate wrongly 

### ISSUE THREAD

**Issue by hanscees** [openssl/openssl#12006]
Hi,

I have used a daily python bot for www.bomengids.nl for several years. It runs in a vm. 
Three days ago it suddenly failed. I investigated and opensll was the culprit. Now its probably an old version, because the code and vm is from 2016.  I did update to the latest version for 

However, the error is so basic I thought I would bring it your attention anyway.

OK: this is the version with the error:
OpenSSL 1.0.1t
runs on / uname -a
Linux core 3.16.0-10-amd64 #1 SMP Debian 3.16.81-1 (2020-01-17) x86_64 GNU/Linux

This is the error:
```
root@core twython/prod# openssl s_client -connect www.bomengids.nl:443
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=10:certificate has expired
notAfter=May 30 10:48:38 2020 GMT
verify return:0
```

On my desktop ubuntu you can see the certificate is fine:
OpenSSL 1.1.1  11 Sep 2018
runs on    uname -a
Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
mate2018:~$ openssl s_client -connect www.bomengids.nl:443
CONNECTED(00000005)
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = FR, ST = Paris, L = Paris, O = Gandi, CN = Gandi Standard SSL CA 2
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = www.bomengids.nl
verify return:1
```

I did not expect openssl would make such an error (if thats true), even an old version and since it occured suddenly three days ago, it might pop up elsewhere too. 

greetings and thanks for the f(ine software)

**Comment by levitte** [comment]
Did you check the time setting on each machine (did you run `date`)?

**Comment by kroeckx** [comment]
The AddTrust certificate has expired, but that website is still
sending that to you, and you still have it in your trust store. 

I believe that since version 1.1.0 the default algorithm has
changed and properly tries a different certificate if it's
expired.

As workaround, on Ubuntu, you can edit /etc/ca-certificates.conf
and put a "!" before the mozilla/AddTrust_External_Root.crt
line and then run update-ca-certificates

**Comment by beldmit** [comment]
Here is another HOWTO to fix it.

https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration

**Comment by hanscees** [comment]
> Did you check the time setting on each machine (did you run `date`)?

did not check that previously, but good point. 

date
Mon Jun  1 10:22:23 UTC 2020

So that checks out ok 

and error still there

Start Time: 1591007033
    Timeout   : 300 (sec)
    Verify return code: 10 (certificate has expired)

**Comment by hanscees** [comment]
> Here is another HOWTO to fix it.
> 
> https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration

thank you, indeed my website testend on 
https://whatsmychaincert.com/?www.bomengids.nl
shows:

www.bomengids.nl has a trusted chain containing an expired certificate. This chain will work with modern web browsers but may fail with older clients, notably OpenSSL 1.0.x. Download a chain without the expired certificate

I will try to fix it. Learned something new today :)

**Comment by hanscees** [comment]
> The AddTrust certificate has expired, but that website is still sending that to you, and you still have it in your trust store. I believe that since version 1.1.0 the default algorithm has changed and properly tries a different certificate if it's expired. As workaround, on Ubuntu, you can edit /etc/ca-certificates.conf and put a "!" before the mozilla/AddTrust_External_Root.crt line and then run update-ca-certificates

And that worked fine! Thank you!

**Comment by levitte** [comment]
I'm a bit horrified at the news of modern browsers accepting a certificate chain where a link is expired... even worse if it's a trust anchor.

**Comment by levitte** [comment]
I've removed the "bug" category, mostly because the "bug" is in an age old openssl version that we haven't supported for a long time. The question has been answered and accepted, time to close.

**Comment by beldmit** [comment]
> I'm a bit horrified at the news of modern browsers accepting a certificate chain where a link is expired... even worse if it's a trust anchor.

I hope they just build a valid chain to a newly added trusted root.

**Comment by mattcaswell** [comment]
> I'm a bit horrified at the news of modern browsers accepting a certificate chain where a link is expired... even worse if it's a trust anchor.

I believe there is an alternative trust anchor that is not expired, so the behaviour is correct. OpenSSL 1.0.x failed if the first trust anchor it comes to is expired, even if there is an alternative one that isn't.

**Comment by richsalz** [comment]
This twitter thread might be useful. https://twitter.com/sleevi_/status/1266647545675210753

**Comment by richsalz** [comment]
> I'm a bit horrified at the news of modern browsers accepting a certificate chain where a link is expired... even worse if it's a trust anchor.

They *might* accept it if they can find an alternate chain.  I.e., what OpenSSL added in 1.1.0

That website message is misleading/incomplete.

**Comment by ValZapod** [comment]
> I'm a bit horrified at the news of modern browsers accepting a certificate chain where a link is expired... even worse if it's a trust anchor.

LOL, no it is totally correct because there are many (3) trust chaines (to AddTrust External CA Root, USERTrust RSA Certification Authority and AAA Certificate Services), only 1 is expired. See https://tools.ietf.org/html/rfc4158 https://gist.github.com/minaguib/c8db186af450bceaaa7c452b76a9901b#gistcomment-3327448

**Comment by ValZapod** [comment]
> I believe that since version 1.1.0 the default algorithm has changed and properly tries a different certificate if it's expired.

This implemented it, no? 4 years ago. https://github.com/openssl/openssl/commit/0daccd4dc1f1ac62181738a91714f35472e50f3c
