### ISSUE TITLE
OpenSSL AArch64 doesn't support AES instruction set?

### ISSUE THREAD

**Issue by okudayukiko** [openssl/openssl#12002]
Execute `cat /proc/cpuinfo` on my Android smartphone, it returns:
`Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid`

**Comment by okudayukiko** [comment]
OpenSSL AArch64 doesn't call AES instruction set?

**Comment by kroeckx** [comment]
I'm not sure why you ask, but the aes instruction is supported and
used on processors that support it. (The sha1 and sha2 are also
being used.)
