### ISSUE TITLE
Allow 100 chars per source line and check for non-allowed tabs etc.?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#12010]
Linux just changed the 80char hard limit to a soft limit and made the hard limit 100chars.  See slashdot or go to the source: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bdc48fa11e46f867ea4d75fa59ee87a7f48be144

Between that, @ddvo's indent rewrite, etc., should there be a patch-check?  Even as simple as grepping for tabs in other than makefile templates. :)

**Comment by DDvO** [comment]
> Linux just changed the 80char hard limit to a soft limit 

I'd be glad if more than 80 chars would be allowed per line. 
Display space isn't that scarce any more these days :smile: 
100 chars sounds reasonable to me.

**Comment by DDvO** [comment]
> Between that, @DDvO's indent rewrite, etc., 

The `check-format.pl` tool just checks indentation etc. but does not rewrite anything.

**Comment by DDvO** [comment]
BTW, we still have the open issue #10725 on updating the coding guidelines.

**Comment by richsalz** [comment]
yes, it's a *check*

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by DDvO** [comment]
The questions remain: shall we allow 100 chars per line, and automatically check for tabs, etc.?

**Comment by nhorman** [comment]
yes, but given that the question was asked, and received no concrete response, the implicit answer is no.

If you disagree, would you be willing to open PRs to update the coding style guidelines and adjust the check-patch.pl script accordingly?

**Comment by DDvO** [comment]
There is no checkpatch.pl in OpenSSL.
Yet I am willing to adapt the coding guidelines and `check-format.pl` if @openssl/otc decides to allow 100 chars per line.

**Comment by DDvO** [comment]
Made the issue title to the point.

**Comment by nhorman** [comment]
@DDvO Thank you, marking this as a community issue then and assigning you, will bring up on the next OTC meeting

**Comment by t8m** [comment]
**OTC: 80 characters is a soft limit. At the moment there are too many places where we exceed even the 100 characters limit. It would be nice to have CI check for this but without fixing (or somehow waiving) these existing places we cannot enforce such check.

The other possible coding style CI checks that could be enforced should include non-allowed tabs and trailing spaces, EOLs and missing EOLs at EOF.**

**Comment by DDvO** [comment]
`check-format.pl` already checks for non-printable chars like TAB.
Extending the allowed line length to 100 is done by #24841 (which is to be merged tomorrow).
