### ISSUE TITLE
OPENSSL_1_1_1: SSL_CTX_set_ciphersuites not defined 

### ISSUE THREAD

**Issue by FinzelStefan** [openssl/openssl#12025]
An ubuntu update on 27. May, 2020 broke openssl. Anything that can be fixed or just wait?

openssl -v
openssl: relocation error: openssl: symbol SCRYPT_PARAMS_it version OPENSSL_1_1_1 not defined in file libcrypto.so.1.1 with link time reference

Linux ... 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:10:03 UTC 2020 i686 i686 i686 GNU/Linux

**Comment by mattcaswell** [comment]
Do you have multiple versions of OpenSSL on your system besides the system Ubuntu version?

If you only have the system Ubuntu version, then this is a problem for the Ubuntu maintainers to resolve - and this is the wrong place to report it (tell Ubuntu).

If you have installed multiple versions then it is possible that you have overwritten parts of the system version with a different one....which is a bad idea.

**Comment by mattcaswell** [comment]
No response to my questions above. Assuming that my comments solved it. Closing.
