### ISSUE TITLE
Travis failure in 1.1.1

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#12033]
Travis is failing on s390x with the following error:
```
In file included from test/handshake_helper.c:23:
test/handshake_helper.c: In function 'do_handshake_internal':
test/testutil.h:291:31: error: 'alpn_protos_len' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  291 | # define TEST_int_eq(a, b)    test_int_eq(__FILE__, __LINE__, #a, #b, a, b)
      |                               ^~~~~~~~~~~
test/handshake_helper.c:640:16: note: 'alpn_protos_len' was declared here
  640 |         size_t alpn_protos_len;
      |                ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:9106: test/handshake_helper.o] Error 1
make: *** [Makefile:174: all] Error 2
```

**Comment by kaduk** [comment]
Do we have reason to believe this is anything other than the usual `-Wmaybe-uninitialized` flakiness?

**Comment by kroeckx** [comment]
> Do we have reason to believe this is anything other than the usual `-Wmaybe-uninitialized` flakiness?

It's only in the last 3 builds, so it's at least new.

**Comment by kaduk** [comment]
> It's only in the last 3 builds, so it's at least new.

But the code doesn't seem to have changed -- did the compiler version change?

**Comment by bernd-edlinger** [comment]
Only those 3 builds used gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
while previous builds used gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
