### ISSUE TITLE
Inadvertendly pushed a bugfix backport to upstream/OpenSSL_1_1_1-stable

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#12034]
Oh, I was preparing a backport of commit 103ffd2 to 1.1.1
and by mistake I pushed directly to `OpenSSL_1_1_1-stable`, so without proper review and without addrev!
Very sorry for that :frowning_face: 

These are the following two commits:
* commit 7aa3fb0aa35ff064006355011cac84173611deea 
    Replace remnant BUF_strdup() call by OPENSSL_strdup() in bss_acpt.c
* commit fefc35da92132b429728fd05b51aa430ab581c55
   Fix err checking and mem leaks of BIO_set_conn_port and BIO_set_conn_address

Can this be removed/pruned?

**Comment by kroeckx** [comment]
I think it's just in your own copy of the OpenSSL_1_1_1-stable
branch, and not in the real repository? So just reset the branch
the one from the repo?

**Comment by DDvO** [comment]
Hmm, would be nice if so, but it looks to me that the push went directly upstream - see https://github.com/openssl/openssl/commit/fefc35da92132b429728fd05b51aa430ab581c55
which is on github.com/openssl/openssl :(

**Comment by kroeckx** [comment]
> Hmm, would be nice if so, but it looks to me that the push went directly upstream - see https://github.com/openssl/openssl/commit/fefc35da92132b429728fd05b51aa430ab581c55
> which is on github.com/openssl/openssl :(

Ah, but github is not the real repo, it's just a mirror. I think
I've fixed it.

**Comment by romen** [comment]
It's not on git.openssl.org :

https://git.openssl.org/?p=openssl.git;a=shortlog;h=refs/heads/OpenSSL_1_1_1-stable


The one in github is just a mirror of git.openssl.org and is now currently
out of sync: probably this will have to be fixed by Richard or Matt.

I don't know if a subsequent merge on 1.1.1 on git.openssl.org will result
in a force push that would fix the problem, or if it would make it worse!


Nicola

**Comment by DDvO** [comment]
Thanks a lot for taking care of that!
Hope the forced push was sufficient to prune the two commits.

**Comment by levitte** [comment]
> Hope the forced push was sufficient to prune the two commits.

That should be easy to check, just add a remote for the main repo, fetch both and compare their respective top of that same branch.

**Comment by mattcaswell** [comment]
> without proper review and without addrev!

You wouldn't have been able to push this to the main repo. The commit hooks reject commits without review headers.
