### ISSUE TITLE
Should most objects have EX_DATA?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#12059]
I started to do a PR, https://github.com/openssl/openssl/pull/10997, to add EXDATA as a general extensible data store to some objects.  Perhaps as an issue, not a WIP PR, it will get some discussion.

**Comment by nhorman** [comment]
Associated issue seems to indicate this isn't going to be planned

Marking as inactive, to be closed at the end of 3.4  dev, barring further input
