### ISSUE TITLE
evp_pkey_provided_test fails randomly sometimes

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12054]
The evp_pkey_provided_test randomly fails sometimes. It occurs because it dumps PEM files to stdout. If those PEM files happen to contain a line that starts with the text "ok" then it confuses the test harness and the test fails.

Example failing build:

https://travis-ci.org/github/openssl/openssl/jobs/694280520

**Comment by levitte** [comment]
This is really a generic problem.  The test programs should really treat *any* output that isn't TAP specific as commentary, i.e. ensure that it's prefixed with a `#`.  I have an idea on how to do that right, coming up.
