### ISSUE TITLE
openssl-1.1.0-pre5 coredumped

### ISSUE THREAD

**Issue by elitetony** [openssl/openssl#1205]
hi:
   when  add the STACK_OF(SCT) into ocsp  response, core dumped. please help me.thanks!

#0  0x00007f6e9f7beda4 in SCT_is_complete () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6_5.4.x86_64
(gdb) bt
#0  0x00007f6e9f7beda4 in SCT_is_complete () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#1  0x00007f6e9f7bdc7c in i2o_SCT () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#2  0x00007f6e9f7bdfc5 in i2o_SCT_LIST () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#3  0x00007f6e9f7bdff7 in i2o_SCT_LIST () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#4  0x00007f6e9f7be0c9 in i2d_SCT_LIST () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#5  0x00007f6e9f8b0b9d in do_ext_i2d () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1
#6  0x00007f6e9f8b439f in X509V3_add1_i2d () from /usr/local/openssl1.1.5/lib/libcrypto.so.1.1

**Comment by mattcaswell** [comment]
This is probably the issue fixed in a9da48157c90. Please try the latest master version.

**Comment by mattcaswell** [comment]
Closing assuming fixed by above commit.
