### ISSUE TITLE
Typo in doc string? bn_dh.c

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#12058]
`bn_dh.c` refers to RFC 2312:
https://github.com/openssl/openssl/blob/7b2d995ed79f0653defd682e5097ed937f4cabbc/crypto/bn/bn_dh.c#L32

but I can't find anything about DH primes in [RFC 2312](https://tools.ietf.org/html/rfc2312), so I'm guessing it's a typo. Any idea what is the correct RFC reference?

**Comment by kaduk** [comment]
Looks like RFC 2412 (OAKLEY groups)
