### ISSUE TITLE
Missing tests for both old and new key and param generation apps 

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#12066]
As partly discussed in https://github.com/openssl/openssl/issues/12047#issuecomment-639820496 the tests for the legacy apps `gendsa`, `dsaparam` and `dhparam` have disappeared, while the apps themselves are still present, which inevitably lead to regression bugs going unnoticed for a while.

So either re-introduce the tests are remove the legacy apps.
In this regard @richsalz wrote in https://github.com/openssl/openssl/issues/12047#issuecomment-639838285:
> Perhaps the project wishes to reconsider its deprecation actions and revert those commits.

Conversely, also for the new apps tests for some aspects seem to be missing:
* for `pkeyparam` there are tests regarding EC, but not yet for DH and DSA.
* ~for `genpkey` there are tests regarding DH and DSA, but not yet for EC and RSA.~

**Comment by beldmit** [comment]
There are plenty of tests for EC using `genpkey`: 
https://github.com/openssl/openssl/blob/8a9394c1eddbac210d4a2dceab521efa7518fa1f/test/recipes/15-test_genec.t#L200-L244

**Comment by beldmit** [comment]
RSA genpkey tests are present in `test/recipes/15-test_genrsa.t` and `test/recipes/15-test_mp_rsa.t`

**Comment by DDvO** [comment]
Thx for pointing this out, so i've updated the part of my post that refers to the `genpkey` app.

**Comment by beldmit** [comment]
DSA parameters tests are added in #13929

**Comment by beldmit** [comment]
DH parameters tests are added in #13930

**Comment by slontis** [comment]
Is this issue addressed now?

**Comment by beldmit** [comment]
I think yes. #14148 as superseded #13929 and is already merged.
