### ISSUE TITLE
Windows 10 - Build Problems - ActivePerl missing Win32/Console.pm

### ISSUE THREAD

**Issue by Tockra** [openssl/openssl#12068]
So Guys,

I'm very mad. Your build instructions are very bad.
You describe the dependencies here: https://github.com/openssl/openssl/blob/master/NOTES.WIN

I installed ActiveState, nasm and VS2019. 
I tried to run `perl Configure VC-Win64A` from a "Visual Studio 2019 Developer Command Prompt v16.6.1" what isn't explained somewhere. But I think it is necessary to use this command prompt...

Then I get the error: 
```bash
C:\Users\TiTan\openssl-master>perl Configure VC-WIN64A
Configuring OpenSSL version 1.1.1g (0x1010107fL) for VC-WIN64A
Using os-specific seed configuration
Can't locate Win32/Console.pm in @INC (you may need to install the Win32::Console module) (@INC contains: C:/Users/TiTan/openssl-master/util/perl C:/Perl64/site/lib C:/Perl64/lib) at C:/Perl64/site/lib/ActivePerl/Config.pm line 400.
Compilation failed in require at C:/Perl64/site/lib/ExtUtils/MakeMaker.pm line 9.
BEGIN failed--compilation aborted at C:/Perl64/site/lib/ExtUtils/MakeMaker.pm line 9.
Compilation failed in require at C:/Perl64/site/lib/IPC/Cmd.pm line 235.
```

So no problem. I tried `cpan -i Win32::Console`. But then: 
```bash
C:\Users\TiTan\openssl-master>cpan -i Win32::Console
Loading internal logger. Log::Log4perl recommended for better logging
Reading 'C:\Perl64\cpan\Metadata'
  Database was generated on Fri, 05 Jun 2020 03:17:03 GMT
Running install for module 'Win32::Console'
CPAN: Digest::SHA loaded ok (v6.01)
CPAN: Compress::Zlib loaded ok (v2.092)
Checksum for C:\Perl64\cpan\sources\authors\id\J\JD\JDB\Win32-Console-0.10.tar.gz ok
CPAN: Archive::Tar loaded ok (v2.30)
Win32-Console-0.10/
Win32-Console-0.10/Changes
Win32-Console-0.10/Console.pm
Win32-Console-0.10/Console.xs
Win32-Console-0.10/docs/
Win32-Console-0.10/docs/index.html
Win32-Console-0.10/docs/intro.html
Win32-Console-0.10/docs/license.html
Win32-Console-0.10/docs/reference.html
Win32-Console-0.10/docs/toc.html
Win32-Console-0.10/eg/
Win32-Console-0.10/eg/sample.pl
Win32-Console-0.10/Makefile.PL
Win32-Console-0.10/MANIFEST
Win32-Console-0.10/META.yml
Win32-Console-0.10/README
Win32-Console-0.10/typemap
CPAN: YAML::XS loaded ok (v0.69)
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: Parse::CPAN::Meta loaded ok (v2.150010)
CPAN: CPAN::Meta loaded ok (v2.150010)
Configuring J/JD/JDB/Win32-Console-0.10.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Win32::Console
Writing MYMETA.yml and MYMETA.json
  JDB/Win32-Console-0.10.tar.gz
  C:\Perl64\bin\perl.exe Makefile.PL INSTALLDIRS=site -- OK
Running make for J/JD/JDB/Win32-Console-0.10.tar.gz
CPAN: Module::CoreList loaded ok (v5.20181129_28)
Der Befehl "dmake" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
  JDB/Win32-Console-0.10.tar.gz
  dmake -- NOT OK
```

And this is the point where I need to get out. I can't find a solution for this problem...
Some pages says you just need to run `npan` to install dmake. But that isn't right. Other sites say you need to update stuff. But `npan -u` doesn't help.

I'm very frustrated by your bad documentation. Maybe I just didn't find the right lines. But at the moment I see no solution...

Maybe I need a Phd or some stuff in computer science to build your project. But shouldn't it be very easy for guys like me or other guys?

T

**Comment by levitte** [comment]
It should be easy.  Why it's failing for you, I do not know.  According to `corelist`, IPC::Cmd has been part of the core perl modules since perl 5.9.5, which means that it should come fully charged with ActiveState Perl.  We require perl 5.10 or newer for our stuff.

We run regular tests on Windows, and have never encountered this failure before, so it does come as a surprise.  I believe that our appveyor setup uses ActiveState perl, whereas I personally use StrawBerry perl for variety.

You must understand, though, that this failure isn't within our scope to resolve.  I suggest that you turn to ActiveState perl (in case there's something wrong with your installation), or to the developers of IPC::Cmd, https://metacpan.org/pod/IPC::Cmd

**Comment by Tockra** [comment]
I just went on https://www.activestate.com/ActivePerl. 
Pressed Download Now. Logged in with github account.Pressed the big blue 5.28 button.
Then I downloaded the .exe and did the default installation.

What should I did wrong?

**Comment by DDvO** [comment]
I've never heard of ActivePerl. Just tried it out and ran into the same issue.
There must be something wrong with module installation at least in their current version.
Like @levitte I usually use Strawberry Perl, which just works out of the box.

Maybe the recommendation in `NOTES.WIN` should be revised to give Strawberry Perl preference.

**Comment by levitte** [comment]
It sounds like a bug report should be filed with ActiveState...

**Comment by DDvO** [comment]
Another thing I spontaneously dislike about ActivePerl is that for being able to download their installer, one is forced to create a user account (or sign in via GitHub or the like).

Moreover, our company's Windows malware checker reported some spyware/greyware very soon after downloading and installing ActivePerl.

So I strengthen my above suggestion to: 
Let's remove ActivePerl from our list of recommended Perl implementations for Windows.

**Comment by levitte** [comment]
It seems, BTW, that others have hit the same bug through different means:

https://stackoverflow.com/questions/57897632/how-to-install-additional-perl-module-on-latest-perl-active-state

One interesting answer in there is this:

> Or `ppm install Win32-Console` since you said you're using ActiveState

**Comment by levitte** [comment]
@DDvO, this is kind of a side question to this issue, but have you ever tried `perl configdata.pm -r` with StrawBerry perl?  On my machine, that creates a detached subprocess.  I get immediately sent back to the prompt, and then reconfiguration output comes as from that subprocess, after a bit.  It's *weird*, but ok it works

**Comment by DDvO** [comment]
> One interesting answer in there is this:
> 
> > Or `ppm install Win32-Console` since you said you're using ActiveState

I had tried this as well, but no avail.
Apparently they replaced `ppm` by some gui-based package manager, which I can't find as part of the installation. 
And they failed to include the prerequisite tool `dmake.exe`.

**Comment by DDvO** [comment]
> @DDvO, this is kind of a side question to this issue, but have you ever tried `perl configdata.pm -r` with StrawBerry perl? On my machine, that creates a detached subprocess. I get immediately sent back to the prompt, and then reconfiguration output comes as from that subprocess, after a bit. It's _weird_, but ok it works

I've just tried this as well and got exactly the same behavior.

**Comment by levitte** [comment]
It seems like there's a whole collection of issues with the latest activeperl...

**Comment by Tockra** [comment]
I'll try strawberry perl. 

But there are many other issues with your "guide"...
The Notes.WIN says something about the default locations of openssl. But it doesn't say if you need to create there folders, you need to move there the openssl folder after build. 
If the default folders create themself while/after build. 

The information are at least ok, but not complete.

**Comment by Tockra** [comment]
Strawberry works ...


Perhabs you could write the NOTE.WIN file this way or adding some part of this kind:
```
...
1. Perl. We recommend ActiveState Perl, available from
   https://www.activestate.com/ActivePerl. Another viable alternative
   appears to be Strawberry Perl, http://strawberryperl.com.
   You also need the perl module Text::Template, available on CPAN.
   Please read NOTES.PERL for more information. (Maybe here without activestate)

 2. Microsoft Visual C compiler. Since we can't test them all, there is
   unavoidable uncertainty about which versions are supported. Latest
   version along with couple of previous are certainly supported. On
   the other hand oldest one is known not to work. Everything between
   falls into best-effort category. (here everybody would benefit from the exact package name of the VS19 installer. Maybe with screenshots because of the different languages)

3. Netwide Assembler, a.k.a. NASM, available from https://www.nasm.us,
   is required. Note that NASM is the only supported assembler. Even
   though Microsoft provided assembler is NOT supported, contemporary
   64-bit version is exercised through continuous integration of
   VC-WIN64A-masm target.

4. Command for build
5. Command for build
6. Command for build
7. Move directory to default location (see above)
....

```

Something like that would be nice. Maybe the single steps should contain less information and you could place the information somewhere else...
To use enumeration would be a advantage against using "-" ...

**Comment by levitte** [comment]
The central "hub" for installation is `INSTALL`.  NOTES files are only special notes on diverse topic, i.e. complementary (and necessary) extra information.

**Comment by Tockra** [comment]
yeah but the actual state isn't realy good

**Comment by mattcaswell** [comment]
I think NOTES.WIN could benefit from some re-organisation to put the really important information up front. It does need some up front explanation of the different Windows build types (because the instructions for a VC++ based build are different to a mingw build, and are different to a cygwin build). But the current wall of text at the beginning of NOTES.WIN just makes me glaze over.

A Windows specific "Quick Start" guide might be useful. Something along the lines of my SO answer here, which seems to have been quite popular:

https://stackoverflow.com/questions/45494630/how-to-build-openssl-on-windows-with-visual-studio-2017/45495686#45495686

**Comment by DDvO** [comment]
@Tockra, you could have found the solution to that ActivePerl module hick-up here:
https://stackoverflow.com/questions/58538495/ppm-doesnt-work-after-installing-activestate-perl

I wrote earlier:
> Apparently they replaced `ppm` by some gui-based package manager, which I can't find as part of the installation.

Meanwhile I understand better what's going on here:
ActiveState moved to an online package management, where one selects the wanted packages, lets them build remotely (not on the target Windows-based host) and then downloads an installer (.exe or .msi) which includes those packages. Kind of counter-intuitive and inflexible.

I've tried it out, manually selecting Win32-Console` for https://platform.activestate.com/DDvO/ActivePerl-5.26
AFAICS also other can now download the resulting augmented package from there.

**Comment by DDvO** [comment]
> yeah but the actual state isn't realy good

In my 35 year of IT experience, this statement has been true for Windoof (German pun intended) in general from its very beginning. It stated as a revamped MS-DOS, a legacy from which it has never really recovered. For any serious use it is still a PITA, so I use it only when I have no other choice.

As far as possible, I can only recommend using Linux instead (in case of need on a VM),
where all important development tools are simply just there and work smoothy.

**Comment by DDvO** [comment]
> A Windows specific "Quick Start" guide might be useful. Something along the lines of my SO answer here, which seems to have been quite popular:
> 
> https://stackoverflow.com/questions/45494630/how-to-build-openssl-on-windows-with-visual-studio-2017/45495686#45495686

I've taken this over, doing also a couple of more updates and minor extensions of `NOTES.WIN`, in #12098.

**Comment by yayiyao** [comment]
you can try ActivePerl 5.24 version. it works for me.

**Comment by shaunmlowry** [comment]
If you download a regular ActivePerl CE, it is missing Win32-Console required to run the configure script.  The CPAN tooling doesn't work well in ActivePerl, but if you go to [https://platform.activestate.com/ActiveState/ActivePerl-5.28](https://platform.activestate.com/ActiveState/ActivePerl-5.28) you can fork this project, add `Win32-Console` to the list of packages and the resulting build runs the Configure script just fine.

**Comment by mocolicious** [comment]
In activestate its case sensitive so `perl Configure VC-WIN64A` doesn't work but `per Configure VC-Win64A` does
