### ISSUE TITLE
Will Openssl reset client random and server random after key exchange?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12083]
Hi, 
   I want to know that whether openssl will reset client random and server random after it finished key exhange process.
   Thanks in advance.

**Comment by mattcaswell** [comment]
Well, it depends what you mean. New client and server random values are selected for each handshake - even for resumption and reneg handshakes. The values are used during the handshake but not used again after it, although they continue to exist within the SSL object for the lifetime of the connection/object.

**Comment by joymcg** [comment]
> Well, it depends what you mean. New client and server random values are selected for each handshake - even for resumption and reneg handshakes. The values are used during the handshake but not used again after it, although they continue to exist within the SSL object for the lifetime of the connection/object.

Thanks a lot. The answer cleared my doubts.
