### ISSUE TITLE
Does OpenSSL/1.1.1 support SM series TLS ciphersuits?

### ISSUE THREAD

**Issue by tokers** [openssl/openssl#12084]

**Comment by bowensd** [comment]
NO.ShangMi algo+mode is implemented located in crypto/sm2、sm3、sm4，but it's not supported in TLS(sm ciphersuits is not listed in RFC standards，which is OPENSSL's base). There are open project supporting SM in TLS as GMSSL、TASSL.

**Comment by tokers** [comment]
Thanks.

**Comment by InfoHunter** [comment]
> sm ciphersuits is not listed in RFC standards，which is OPENSSL's base

This is not true. Read: https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-03

**Comment by kaduk** [comment]
That one is still in ISE review and not published as an RFC yet, though.

**Comment by bowensd** [comment]
Precisely, it's indeed not an RFC.But I can understand what you mean.As the expansion of influence of SM algo ,it's definitely possible to witness the standarlization of SM algo in TLS1.3.  I visited your github last day@InfoHunter  and was familar with your name.The message you left reminded me of the TLS draf contributor.The fact is that I have read the draft a few month ago!I respect what you and antifince did，it will promote the application of SM algo.I have no doubt about that.BTW，I am a postgraduate in China，and I am trying to do the same thing as what you want to do in the draft.May need your help especially in OPENSSL oneday.Wish all the best.
