### ISSUE TITLE
[memory leak]unexpected eof while reading and data corrupt when KTLS enabled

### ISSUE THREAD

**Issue by MXWXZ** [openssl/openssl#12082]
When KTLS is enabled, multiple client's handshake will lead to unexpected eof while reading and data corrupt(possible memory leak).

Tested OpenSSL version: master, 3.0.0-alpha1
Kernel version:  5.4.43-1-MANJARO
Reproduce step(using docker):
```
sudo modprobe tls
git clone https://github.com/openssl/openssl.git
sudo docker run -it -v $(pwd)/openssl:/openssl archlinux

# [In docker]
pacman -Sy make gcc vim
cd openssl
./config enable-ktls
make build_sw -j4
pacman -Rdd openssl
make install_sw

cd /
vim server.cpp
# https://paste.ubuntu.com/p/fyhr6dDR7G/
vim client.cpp
# https://paste.ubuntu.com/p/P2DjwWhTkf/
vim server.pem
# https://paste.ubuntu.com/p/QttnVGsVSm/
vim serverkey.pem
# https://paste.ubuntu.com/p/g6QR84wSfw/

g++ -c -o client.o client.cpp
g++ -o client client.o -lssl -lcrypto
g++ -c -o server.o server.cpp
g++ -o server server.o -lssl -lcrypto
export LD_LIBRARY_PATH=/usr/local/lib
./server &
./client
```
You will see like this
![1](https://user-images.githubusercontent.com/16700613/83996689-51710400-a98f-11ea-9ed6-91cd7938b453.png)

When OpenSSL is compiled without ktls, the client will print `test` infinitely, but when enable ktls, some data are corrupted and sometimes result in `unexpected eof while reading`.

Even when you remove `SSL_write(ssl, reply, strlen(reply));` in server and `RecvPacket();` in client, it will also result in `unexpected eof while reading` so I think there is something wrong with handshake procedure when ktls is enabled, maybe memory leak or UAF.

Any suggestions?

**Comment by kroeckx** [comment]
@junjunk or @borisPis-zz: Is this something you can look at?

**Comment by paulidale** [comment]
This either needs to be fixed for 3.0 or disabled for 3.0.

**Comment by junjunk** [comment]
@kroeckx @paulidale I could propably take a look this week

**Comment by t8m** [comment]
I've tested that the issue still applies to the current master branch.

**Comment by paulidale** [comment]
@junjunk, that would be great.  There is no opposition to including this in 3.0, but it needs to be in for beta 1.  My comment was meant to indicate that we'd not delay 3.0 to include this.

It's going to be more than a week before beta 1.

**Comment by junjunk** [comment]
The problem disappears if:
1. Blacklist tls module - that's why Kernel TLS could not run
2. `SSL_set_mode(ssl, SSL_MODE_NO_KTLS_RX);` is added into client code.
So, the problem in the RX path of Kernel TLS. Right now I cannot determine is it problem in openssl or is it problem in kernel.
It's better to ping @borisPis-zz because he added RX path of Kernel TLS
I need more time to check it with different kernel versions

**Comment by t8m** [comment]
I've reproduced it on kernel 5.8.16

**Comment by junjunk** [comment]
Well, it seems to be kernel-related problem.
I have made simple test with bpftrace kprobes. And I found that user-space application receives exactly the same data that is filled by kernel in `tls_sw_recvmsg`.
The tested kernels are 5.9.2, 5.4.75, 5.4.40.
I will try earlier versions too, but anyway - I need to dig deeper in kernel to understand what's going on and why data is corrupted somehow

**Comment by MXWXZ** [comment]
> Well, it seems to be kernel-related problem.
> I have made simple test with bpftrace kprobes. And I found that user-space application receives exactly the same data that is filled by kernel in `tls_sw_recvmsg`.
> The tested kernels are 5.9.2, 5.4.75, 5.4.40.
> I will try earlier versions too, but anyway - I need to dig deeper in kernel to understand what's going on and why data is corrupted somehow

Agree, I've also convert this to GnuTLS and reproduced.
Deeper test shows that this could only appear when the server side send data to a new connected client IMMEDIATELY after the handshake. **If the client connect, and send some data to server first, that is, the server receive first instead of send. Or the server sleep sometime after the handshake and then send data(just add sleep in code above), the corrupt chance will be decreased apparently.**
So I think it may be some race in kernel side that when the handshake function completed, the actual connection is not established yet.

**Comment by junjunk** [comment]
Found a bug in kernel, here is [patch](https://patchwork.ozlabs.org/project/netdev/patch/1605326982-2487-1-git-send-email-vfedorenko@novek.ru/)
This is not OpenSSL error, the ticket could be closed

**Comment by levitte** [comment]
> the ticket could be closed

Okie, thanks

**Comment by junjunk** [comment]
just for history - fix in kernel is accepted https://patchwork.kernel.org/project/netdevbpf/patch/1605413760-21153-1-git-send-email-vfedorenko@novek.ru/

**Comment by junjunk** [comment]
just for history again - Linux kernels 5.4.80, 5.9.11 and 5.10+ have fix. All affected users are suggested to upgrade
