### ISSUE TITLE
what's the plan for skipping test cases that use legacy algorithms, with no-legacy?

### ISSUE THREAD

**Issue by kaduk** [openssl/openssl#12091]
As of 3.0.0 alpha3, if I configure with `no-legacy` several of the tests do not run successfully:

```
Test Summary Report
-------------------
20-test_enc.t                    (Wstat: 45568 Tests: 180 Failed: 178)
  Failed tests:  3-180
  Non-zero exit status: 178
20-test_enc_more.t               (Wstat: 35584 Tests: 141 Failed: 139)
  Failed tests:  3-141
  Non-zero exit status: 139
30-test_evp.t                    (Wstat: 2304 Tests: 28 Failed: 9)
  Failed tests:  17, 19-20, 22-25, 27-28
  Non-zero exit status: 9
80-test_cms.t                    (Wstat: 256 Tests: 10 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=197, Tests=1996, 206 wallclock secs ( 2.69 usr  0.56 sys + 200.66 cusr 15.32 csys = 219.23 CPU)
Result: FAIL
```

Is now the right time to be going through and skipping specific test cases as they are unuseful, or do we expect there to be further changes in flight that would affect such work?

**Comment by mattcaswell** [comment]
> Is now the right time to be going through and skipping specific test cases as they are unuseful, or do we expect there to be further changes in flight that would affect such work?

This should be an ongoing thing - so this is just a plain bug. We might want to consider adding "no-legacy" to one of the travis builds.

**Comment by levitte** [comment]
I had a look at test_enc.t, and this really boils down to knowing what algorithms are supported by what provider.  However, the list produced by `openssl list -cipher-commands` et al is deeply flawed, as it's the list generated from the old object database and doesn't at all reflect what's actually available when providers come into play.

**Comment by kaduk** [comment]
> This should be an ongoing thing - so this is just a plain bug. We might want to consider adding "no-legacy" to one of the travis builds.

Okay, thanks for clarifying.  I am a bit busy this week but will feel empowered to take a crack at it if I have time.
