### ISSUE TITLE
Error: DSA_SIG_set0 does not have a number assigned

### ISSUE THREAD

**Issue by vladsf** [openssl/openssl#1210]
Trying to build master on OL7 (oraclelinux-release-7.2-1.0.5.el7.x86_64).
make fails:

Error: DSA_SIG_set0 does not have a number assigned
LD_LIBRARY_PATH=: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="/home/vsa/local/ssl" -DENGINESDIR="/home/vsa/local/lib/engines" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -fPIC -m64 -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o ./libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map ./libcrypto.a -Wl,--no-whole-archive -ldl
/usr/bin/ld:crypto.map:983: syntax error in VERSION script
collect2: error: ld returned 1 exit status
make[1]: *** [link_shlib.linux-shared] Error 1
make[1]: Leaving directory `/home/vsa/git/openssl'
make: *** [libcrypto.so] Error 2

any ideas?

**Comment by richsalz** [comment]
Just fixed, try a recent commit.otp

**Comment by vladsf** [comment]
Thank you, opessl builds ok!
