### ISSUE TITLE
how to use fips3.0 correctly

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12113]
Hi,
   I want to use fips module3.0 in my application. And I have some questions to ask.
   1.  Is the fips-mode API diffrent from no-fips module's?  If they are different, is there any  api document to use it?
   2. From document below,  it shows that fips3.0 can used in SSL, can I use both both fips-mode and no-fips mode in SSL? I mean programmly change the mode while using SSL.
   3.  I have some apps writen use old fips libraries,  is it easy to make them use new fips3.0 module. 
       Any suggestions for this? 

Thanks in advance.

**Comment by mattcaswell** [comment]
You should start by reading this document:

https://wiki.openssl.org/index.php/OpenSSL_3.0

> Is the fips-mode API diffrent from no-fips module's? If they are different, is there any api document to use it?

The API is the same. You need to take some steps to ensure you are using FIPS algorithm implementations. The link above gives the overview of how to do that. The individual functions are documented in our man pages:

https://www.openssl.org/docs/manmaster/man3/

> From document below, it shows that fips3.0 can used in SSL, can I use both both fips-mode and no-fips mode in SSL? I mean programmly change the mode while using SSL.

I'm not sure what "document below" you are referring to. However it is possible to have some SSL connections using FIPS algorithms, while others do not. Probably the easiest way to do that is to have one OPENSSL_CTX with the FIPS provider loaded, and one OPENSSL_CTX with the default provider loaded. You then create a different SSL_CTX depending on which one you want to use using `SSL_CTX_new_with_libctx`.

See the wiki link above for a description of what all these terms mean and how to use them.

> I have some apps writen use old fips libraries, is it easy to make them use new fips3.0 module.
Any suggestions for this?

Mostly it is should be straight forward. The functions `FIPS_mode()` and `FIPS_mode_set()` no longer exist in 3.0, so you will have to remove calls to these functions and instead do things the 3.0 way to ensure you are using FIPS algorithms. In the simplest cases this can be done through configuration. Again see the wiki link above for further details.

**Comment by joymcg** [comment]
Thanks for the reply.
