### ISSUE TITLE
Why EVP_ digest functions depend on pthread?

### ISSUE THREAD

**Issue by tawmoto** [openssl/openssl#12114]
For hashing, I used until now the old deprecated functions declared in `md5.h`.
Now I am trying to switch to `EVP_` functions but my project does not compile if I don't link with `-pthread`.
I see that it needs it for some locking

```
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/output/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_new':
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/crypto/threads_pthread.c:34: undefined reference to `pthread_rwlock_init'
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/output/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_read_lock':
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/crypto/threads_pthread.c:65: undefined reference to `pthread_rwlock_rdlock'
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/output/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_write_lock':
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/crypto/threads_pthread.c:78: undefined reference to `pthread_rwlock_wrlock'
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/output/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_unlock':
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/crypto/threads_pthread.c:91: undefined reference to `pthread_rwlock_unlock'
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/output/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_free':
/home/tawfic/Desktop/openssl-OpenSSL_1_1_1g/crypto/threads_pthread.c:107: undefined reference to `pthread_rwlock_destroy'
```

Why a simple function like md5 hash needs locking? Is there a documetation on this that I can read?
Thanks

**Comment by mattcaswell** [comment]
I assume you are using static linking?

Probably there isn't anything directly in the MD5 implementation that requires locking...it is probably coming from some internal dependency. For example locks are used in the error queue management. They are also used in some of the memory management functions.

If your application is not multi-threaded, then one option is to compile OpenSSL with no-threads.

**Comment by tawmoto** [comment]
Hi @mattcaswell , thanks for the fast reply.
I am using static linking, yes.
I just did a very small test app that only hashes a string and it seems that I have to link pthread when using EVP.
When using the deprecated functions, there is no need for pthread.

**Comment by mattcaswell** [comment]
> I just did a very small test app that only hashes a string and it seems that I have to link pthread when using EVP.

Right - this is unsurprising. Like I said this is due to the various internal dependencies (such as the error management) that do use locking. If this is a problem for you then compile OpenSSL without thread support as noted above.

**Comment by tawmoto** [comment]
I see, it's not a problem for me, I just want to make sure that the EVP functions are not slower than the deprecated ones because of locking :)

**Comment by mattcaswell** [comment]
> I see, it's not a problem for me, I just want to make sure that the EVP functions are not slower than the deprecated ones because of locking :)

I can't think of any locks that you would run into as part of normal successful hashing.
