### ISSUE TITLE
WIN64 ARM64

### ISSUE THREAD

**Issue by has-syed** [openssl/openssl#12118]
I tried building OpenSSL for ARM64 WIN64 and I ran the command
~~~
perl Configure VC_WIN64-ARM
~~~
Soon, I concluded that that would build a library for ARM64 WIN32 i.e it would build a 32-bit library for Windows ARM64. 
I need a 64-bit ARM library for ARM64.
So, the commands that I should execute are
~~~
perl Configure VC-WIN64-ARM64
~~~
Hope you can support this new feature.

**Comment by has-syed** [comment]
Perhaps my conclusion is wrong. Below is the output of the command 
perl Configure VC-WIN64-ARM
~~~
Configuring OpenSSL version 3.0.0-alpha4-dev for target VC-WIN64-ARM
Using os-specific seed configuration
Can't locate Win32/Console.pm in @INC (you may need to install the Win32::Console module) (@INC contains: C:/Projects/openssl-master/util/perl C:/Perl64/site/lib C:/Perl64/lib C:/Projects/openssl-master/external/perl/Text-Template-1.56/lib) at C:/Perl64/site/lib/ActivePerl/Config.pm line 400.
Compilation failed in require at C:/Perl64/site/lib/ExtUtils/MakeMaker.pm line 9.
BEGIN failed--compilation aborted at C:/Perl64/site/lib/ExtUtils/MakeMaker.pm line 9.
Compilation failed in require at C:/Perl64/site/lib/IPC/Cmd.pm line 235.
~~~

**Comment by has-syed** [comment]
My conclusion doesn't seem correct. Closing issue for now since I should try other things first.
https://stackoverflow.com/questions/45494630/how-to-build-openssl-on-windows-with-visual-studio-2017
https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019

**Comment by mattcaswell** [comment]
> Can't locate Win32/Console.pm in @INC (you may need to install the Win32::Console module) (@INC contains: C:/Projects/openssl-master/util/perl C:/Perl64/site/lib C:/Perl64/lib C:/Projects/openssl-master/external/perl/Text-Template-1.56/lib) at C:/Perl64/site/lib/ActivePerl/Config.pm line 400.
Compilation failed in require at C:/Perl64/site/lib/ExtUtils/MakeMaker.pm line 9.
BEGIN failed--compilation aborted at C:/Perl64/site/lib/ExtUtils/MakeMaker.pm line 9.
Compilation failed in require at C:/Perl64/site/lib/IPC/Cmd.pm line 235.

If you're using ActiveState Perl they recently seem to have made some changes that mean not all the required perl modules are available by default - which can result in errors like these. You might get better results with Strawberry Perl.

**Comment by has-syed** [comment]
Thanks!
I uninstalled ActiveState Perl and switched to Strawberry Perl and everything worked smoothly and perfectly. I was able to build the libraries and link them in my application and tested them. So easy.
