### ISSUE TITLE
Algorithm and Working Mode

### ISSUE THREAD

**Issue by bowensd** [openssl/openssl#12115]
If I want to implement the combination of an algorithm A and a working mode B ,which both of them was implemented separatly(I am not so sure about that , but  A and B are implemented with other working modes or algotithms）？ If there is a possbility that I could implement A+B through evp or anything else by adding a few lines of code，without  adding a new algorithm  by engine machine mechanism ？That means a lot to me！Thanks!

**Comment by levitte** [comment]
No, we identify algo+mode as distinct algorithms, so for example, AES-CBC is separate from AES-CFB and so on.

**Comment by bowensd** [comment]
Thanks！

**Comment by bowensd** [comment]
@levitte I read the code again and have some questions: Now I want to implement SM4-OFB，and I find out modes/ofb128.c and crypto/sm4.c， If there is a possibility that I could call interfaces to implement it ? If not , the only way is to implement it myself from the beginning?

**Comment by levitte** [comment]
Yes, those are public (albeit undocumented) API functions, see:

https://github.com/openssl/openssl/blob/7f81aed4bccbeb0ad491b68dd601d576c4956c78/include/openssl/modes.h

**Comment by levitte** [comment]
In other words, you have access the mode functions by including `<openssl/modes,h>`

**Comment by bowensd** [comment]
It's very nice of you.Thanks for your help!

**Comment by levitte** [comment]
You're welcome
