### ISSUE TITLE
Engine Leak

### ISSUE THREAD

**Issue by anhu** [openssl/openssl#12126]
Root cause: 

`EVP_PKEY_asn1_find()` will always increment the engine's reference counter if the engine's ameth is returned. So if you set `engine` parameter to `NULL`, you will never get a reference back to call ENGINE_free().  Result: engine's reference count will stay too high and you will never de-allocate the engine.  Leak!! 

Issue found in 1.1.1 and master branch. 

Possible fix: 
```
diff --git a/crypto/x509/x509_set.c b/crypto/x509/x509_set.c
index 164b4e2b..2a65946d 100644
--- a/crypto/x509/x509_set.c
+++ b/crypto/x509/x509_set.c
@@ -15,6 +15,7 @@
 #include <openssl/evp.h>
 #include <openssl/x509.h>
 #include <openssl/x509v3.h>
+#include <openssl/engine.h>
 #include "crypto/asn1.h"
 #include "crypto/x509.h"
 #include "x509_local.h"
@@ -208,10 +209,14 @@ static void x509_sig_info_init(X509_SIG_INFO *siginf, const X509_ALGOR *alg,
     siginf->pknid = pknid;
     if (mdnid == NID_undef) {
         /* If we have one, use a custom handler for this algorithm */
-        const EVP_PKEY_ASN1_METHOD *ameth = EVP_PKEY_asn1_find(NULL, pknid);
+        ENGINE *e = NULL;
+        const EVP_PKEY_ASN1_METHOD *ameth = EVP_PKEY_asn1_find(&e, pknid);
         if (ameth == NULL || ameth->siginf_set == NULL
-                || ameth->siginf_set(siginf, alg, sig) == 0)
+                || ameth->siginf_set(siginf, alg, sig) == 0) {
+            ENGINE_free(e);
             return;
+        }
+        ENGINE_free(e);
         siginf->flags |= X509_SIG_INFO_VALID;
         return;
     }

```

Let me know if you want me to open a pull request.

**Comment by anhu** [comment]
Not sure, but I think similar changes will need to happen in many places.

**Comment by anhu** [comment]
Perhaps another solution would be to not increment the engine's reference counter.  Not sure what kind of side effects that could have or how to do that.

**Comment by anhu** [comment]
A quick search show where else this happens: 
```
openssl-1.1.1g/crypto/x509/x509_set.c:211:        const EVP_PKEY_ASN1_METHOD *ameth = EVP_PKEY_asn1_find(NULL, pknid);
openssl-1.1.1g/crypto/x509/t_x509.c:315:            ameth = EVP_PKEY_asn1_find(NULL, pkey_nid);
openssl-1.1.1g/crypto/pem/pem_lib.c:144:            ameth = EVP_PKEY_asn1_find_str(NULL, nm, slen);
openssl-1.1.1g/crypto/pem/pem_lib.c:167:            ameth = EVP_PKEY_asn1_find_str(NULL, nm, slen);
openssl-1.1.1g/crypto/pem/pem_pkey.c:94:        ameth = EVP_PKEY_asn1_find_str(NULL, nm, slen);
openssl-1.1.1g/crypto/store/loader_file.c:424:                && (ameth = EVP_PKEY_asn1_find_str(NULL, pem_name,
openssl-1.1.1g/test/ssl_test_ctx.c:525:    ameth = EVP_PKEY_asn1_find_str(NULL, value, -1);
openssl-1.1.1g/ssl/ssl_ciph.c:334:    ameth = EVP_PKEY_asn1_find_str(NULL, pkey_name, -1);
```

**Comment by anhu** [comment]
Huh.... `EVP_PKEY_asn1_find_str()` has logic to " Convert structural into functional reference" .  Is that needed in `EVP_PKEY_asn1_find()` as well?

**Comment by mattcaswell** [comment]
Ping @levitte

**Comment by anhu** [comment]
Uh....It has been about  a week now. Is there anything anyone wants me to do?

**Comment by paulidale** [comment]
Engine reference counting is broken in other ways too refer: #4821

**Comment by kaduk** [comment]
And given that ENGINE itself is slated for deprecation "soon", it's unclear how much energy there will be to tidy up the reference counting.

**Comment by beldmit** [comment]
It is not deprecated in 1.1.1 which is LTS. 

I've come across some deadlocks in the scheme where I loaded engine from another engine to replace some EVP_PKEY_ASN1_METHOD callbacks. This may (and may not) be related to this problem.

**Comment by anhu** [comment]
> And given that ENGINE itself is slated for deprecation "soon", it's unclear how much energy there will be to tidy up the reference counting.

You're willing to leave this bug in 1.1.1 until 2023/09/11 ?  Sure, perhaps there is not much energy, but I've already posted the fix above. And I'd be willing to fix the other places.  I just want to know if my fix is appropriate or if anyone else has any better suggestions.

**Comment by anhu** [comment]
Shall I close this and leave the bug in 1.1.1 or would you like a pull request?

**Comment by mattcaswell** [comment]
> EVP_PKEY_asn1_find() will always increment the engine's reference counter if the engine's ameth is returned. 

I don't see the place where `EVP_PKEY_asn1_find` will increment the engine's ref count if the first parameter is NULL (as it is in the original code). So, I'm not sure why you see a leak:

````
const EVP_PKEY_ASN1_METHOD *EVP_PKEY_asn1_find(ENGINE **pe, int type)
{
    const EVP_PKEY_ASN1_METHOD *t;

    for (;;) {
        t = pkey_asn1_find(type);
        if (!t || !(t->pkey_flags & ASN1_PKEY_ALIAS))
            break;
        type = t->pkey_base_id;
    }
    if (pe) {
#ifndef OPENSSL_NO_ENGINE
        ENGINE *e;
        /* type will contain the final unaliased type */
        e = ENGINE_get_pkey_asn1_meth_engine(type);
        if (e) {
            *pe = e;
            return ENGINE_get_pkey_asn1_meth(e, type);
        }
#endif
        *pe = NULL;
    }
    return t;
}
````

**Comment by anhu** [comment]
I think I may have been mistaken? So much time has passed that I don't know where I thought the engine ref count was incremented.  Sigh.  Seems I need to make my issues more detailed. 

I'll close this now.
