### ISSUE TITLE
Ideas for fuzzing

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#1213]
I noticed you have integrated a fuzzer in the master branch.

Here is an idea that has been very effective for me (pretty much
instantly found various segfaults in OpenSSL when I tried this a
couple of months ago).

Make your core allocation functions (like CRYPTO_malloc,
CRYPTO_realloc, ...) fail randomly. All code in OpenSSL that doesn't
verify the return value of the alloc correctly, will likely cause a
segmentation fault at some point. The rationale is that an allocation,
however small it is, can always fail, and might sometimes be coerced
by an attacker (through memory leaks and the likes).

In order to make the allocation fail in a deterministic way (so the
fuzzer doesn't get confused), you can compute some sort of hash on the
fuzzing input, seed a random number generator (POSIX srand() will do
fine) with this hash, and let the allocations fail at a certain rate.
For example something like:

``` c
uint32_t hash = compute_hash(input, inputsize);
srand(hash);

CRYPTO_malloc(size_t size)
{
   /* Fail about once in 10 times */
   return ( (rand() % 10) == 0 ) ? NULL : malloc(size);
}
```

This is what I used. It's pretty crappy but it did the job for me at the time. I'm sure you can come up with something better.

``` c
static void seed_random(const unsigned char* buffer, const size_t size)
{
    unsigned int seed = 0;
    size_t i;

    for (i = 0; i < size; i++)
    {
        if ( buffer[i] )
        {
            seed += (buffer[i]*(i+1));
        }
    }
    srand(seed);
}
```

Compile with sanitizers enabled and you're set.

You might want to extend this idea to all functions that rely on resource allocation, like file access and such, which can theoretically always fail as well.

Another thing is that -fsanitize=address usually won't detect slight overreads/writes of stack-based buffers, probably because all static data known at compile-time is stored in large blocks and the sanitizer cannot know where each buffer starts and ends. A way to solve this could be to dynamically allocate each static string at run-time, so the sanitizer is aware of its boundaries and will trigger as soon data outside its bounds is accessed. Unfortunately I do know know of a way to enable this behavior without manually adjusting all buffer declarations in the source code.

Guido

**Comment by richsalz** [comment]
From @ekasper : BoringSSL did something similar, except I believe they implemented a malloc that would fail deterministically on the n^th call - so you can iterate on every single malloc in, say, an SSL handshake and catch crashes. I think a malloc that fails randomly with some fixed probability will have coverage problems, i.e., there's an expected number of mallocs until fail, and so you need to be wise about adaptively adjusting your probability to have a good chance of hitting every malloc in the program.

**Comment by richsalz** [comment]
From @kroeckx : It's something I've at least been thinking about too, and I'm not sure what the best way is.  You want a way that every malloc() can fail, and you actually don't want it to depend on the current fuzzing input file.  So you would probably need to add 1 or more bytes at the start of the file that control the behaviour of malloc().

However, I've seen this commit in tis-interpreter:
commit da864e123c94ace6e5a762fee709936bbb1e7fcf
Author: Pascal Cuoq <cuoq@trust-in-soft.com>
Date:   Fri Jun 3 16:43:49 2016 +0200

    cleanup, prepare malloc-returns-null mode

So I'm hoping that at some point tis-interpreter will actually catch all those issues, and we wouldn't have to rely on the random behaviour to have it catch all issues.


An other related problem is that some things depend on the random number generator, and so the behaviour we get from the server fuzzing program is now random.  We need to have a way to make the program deterministic, only the input file should have an effect on what it does.

**Comment by richsalz** [comment]
See ```CRYPTO_mem_set_functions```  A variety of strategies can be set at runtime.

**Comment by guidovranken** [comment]
One way to exhaustively test all mallocs 'empirically' (as opposed to static analysis or something) is to
1. enumerate all calls to an allocation function in the code
2. assign a 1 bit variable to each allocation point in the code, 0 = fail, 1 = success
3. exhaust all bit combinations

and on top of that you would need to add a dimension to symbolize the Nth time the same allocation is hit.

A quick recursive grep on OpenSSL 1.0.2h reveals 670 instances of 'OPENSSL_malloc', it's obvious that (2**670)*N requires far too much computing resources to ever test the whole library exhaustively.

Of course, you can test certain parts of the code like this, say allocations performed crypto/evp/*.c, but that doesn't necessarily imply that each error brought about by an allocation failure is hit.

For example, it is determined by the approach above that code part X always checks all malloc returns. It is also determined that code part Y always checks all malloc returns. Both parts of the code will return an error value themselves to signal to the caller that it has failed. But if code part Y calls a function in code part X, and doesn't check its return value, an error occurs nonetheless.

```c
int X(char** out)
{
   *out = malloc(100);
   if ( *out == NULL )
   {
      return FAILURE;
   }
   *out[0] = 0x00;
   return SUCCESS;
}

int Y(char** out)
{
   *out = malloc(100);
   if ( *out == NULL )
   {
      return FAILURE;
   }
   *out[0] = 0x00;
   return SUCCESS;
}

void Y_2(void)
{
   char* out;
   X(&out);
   /* Segmentation fault if X() fails)
   memset(*out, 0, 100);
}
```

So code part X can individually be verified to be valid (by testing all combinations of success, failure for every allocation it performs itself), and the same can be done for code part Y, but it is their interplay that could cause problems.

At the end of the day, fuzzing will never find all vulnerabilities anyway, since some vulnerabilities depend on very large input data (2GB+), let alone timing attacks etc. It's just another tool in the shed and exhaustive results will never be yielded for a big library like OpenSSL with fuzzing alone.

Guido

**Comment by kroeckx** [comment]
So tis-interpreter now actually has support for malloc returns null mode, see https://github.com/TrustInSoft/tis-interpreter/issues/107

I started running it, and it directly found an issue.

**Comment by richsalz** [comment]
See #1252 which does the original request.
