### ISSUE TITLE
Where is the AEAD Algo implemented?

### ISSUE THREAD

**Issue by bowensd** [openssl/openssl#12130]
I have no idea where is the AEAD algo implemented such as AES-GCM/CCM ,If there is someone knows?

**Comment by romen** [comment]
Probably what you are looking for is in `crypto/modes` but in general support for AEAD parameters and logic is spread mostly between `crypto/modes` and `crypto/evp`.

A quick search shows this:

```bash
; git grep --name-only 'AEAD\|GCM\|CCM' -- crypto/ | grep -v -e "crypto/objects" -e "crypto/err"                                                                        
crypto/aes/asm/aesni-x86.pl
crypto/aes/asm/aesni-x86_64.pl
crypto/evp/e_aes.c
crypto/evp/e_aes_cbc_hmac_sha1.c
crypto/evp/e_aes_cbc_hmac_sha256.c
crypto/evp/e_aria.c
crypto/evp/e_chacha20_poly1305.c
crypto/evp/e_rc4_hmac_md5.c
crypto/evp/evp_enc.c
crypto/evp/evp_err.c
crypto/evp/evp_lib.c
crypto/modes/asm/aesni-gcm-x86_64.pl
crypto/modes/asm/ghash-alpha.pl
crypto/modes/asm/ghash-armv4.pl
crypto/modes/asm/ghash-c64xplus.pl
crypto/modes/asm/ghash-ia64.pl
crypto/modes/asm/ghash-parisc.pl
crypto/modes/asm/ghash-s390x.pl
crypto/modes/asm/ghash-sparcv9.pl
crypto/modes/asm/ghash-x86.pl
crypto/modes/asm/ghash-x86_64.pl
crypto/modes/ccm128.c
crypto/modes/gcm128.c
```

To be more precise we need to know a little bit more about what exactly you are looking for!

**Comment by romen** [comment]
If you are looking for the APIs for AEAD modes for different ciphers you can start from this [man page](https://www.openssl.org/docs/manmaster/man3/EVP_CipherInit.html#AEAD-INTERFACE).

There is also a [wiki page](https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption) but some of its content might be a tad out-of-date (last update was June 2019), so in case of ambiguities, refer to the man page.

**Comment by bowensd** [comment]
Your advice is really helpful.thanks
