### ISSUE TITLE
OpenSSL 1.0.2u allows the client to present certificates using 512 bit rsa keys.

### ISSUE THREAD

**Issue by Immortalem** [openssl/openssl#12133]
### Affected Versions
1.0.2u

### Setup
OpenSSL has been compiled from source in an alpine docker container. The following excerpt of the used docker file shows the build related commands:
```
RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make -s && make install_sw -s
```
After building it the respective OpenSSL version and required libraries have been copied into an minimal docker container (from scratch).

The server is later started using the following command:
`openssl s_server -accept 4433 -Verify 100 -cert /cert/inputCerts/rootv3.pem -key /cert/keys/rootv3.pem -CAfile /cert/inputCerts/root.pem -verify_return_error`

All files mentioned in this report (certificates, keys, etc.) have been included in the attached zip archive.

### Issue
OpenSSL 1.0.2u allows the client to present a certificate with a 512 bit RSA key. Keys of this length are considered insecure and shouldn't be allowed by default.

### Reproduction
Uses OpenSSL 1.1.1 on Ubuntu 18.04.
Connect to the started server using the following command:
` openssl s_client -connect localhost:4433 -cert ROOTv3_CAv3_LEAF_RSAv3_weakKey__leaf_certificate1.pem -key rsakey_weak512.pem -CAfile ROOTv3_CAv3_LEAF_RSAv3_weakKey__ca_certificate1.pem  -cipher "DEFAULT@SECLEVEL=0" -tls1_1`

### Expected Result
OpenSSL should reject the certificate due to its weak key.

### Actual Result
OpenSSL happily accepts the certificate and proceeds with the handhshake.

### Attachment
[opensslWeakKey.zip](https://github.com/openssl/openssl/files/4774593/opensslWeakKey.zip)

**Comment by FdaSilvaYY** [comment]
You state : 

> **Affected Versions** : 
> 1.0.2u
> ...
> **Reproduction**
> Uses OpenSSL **1.1.1** on Ubuntu 18.04.

A writing mistake ?

**Comment by Immortalem** [comment]
No. I meant to say I use OpenSSL 1.1.1 for the client while 1.0.2u is the server.

**Comment by kroeckx** [comment]
It's very unlikely that the 1.0.2 behaviour will be changed. The
security level support only got added in 1.1.0.

**Comment by mattcaswell** [comment]
Since this is 1.0.2 it  won't be fixed. Closing.
