### ISSUE TITLE
Can I use “d2i_CMS_bio”to cast cms der file to openssl’s CMS_ContentInfo

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12147]
Hi, 
      Now I am writing code to use openssl to decode a cms struct and  my question  is that the  "id-ct-sztpConveyedInfoJSON" type  in cms struct  is not defined in rfc 5672. 
     I wonder whether  I  can use “d2i_CMS_bio” to cast a cms der file  into openssl’s CMS_ContentInfo.   If it success,  how can I get the type? Since there is no nid for it, how can I get its oid like OID id-data(1.2.840.113549.1.7.1). 
     **In CMS_ContentInfo, there is a field named “otherdata”, I guess the content of the other type will be saved in it, is it right?_**

**Comment by slontis** [comment]
Not sure I can help you out completely here but.. 
It is described in https://www.rfc-editor.org/rfc/rfc8572.html Section 3.1 and the format depends on what you are trying to do.

I dont know what your data looks like but as a first step you could just try using the app
>openssl cms
to see if you can load it. Yes there is a d2i_CMS_bio() in there somewhere.
(NOTE it has many options - if you debug the code you should be able to figure out what is needed).

To see examples of options used by the tests run
>make TESTS="test_cms" V=1 tests

With CMS data, dumping the asn1 and looking at the format might give you some clues.. Use either 
>openssl asn1parse
or 
>dumpasn1

And then refer back to the CMS standard to figure out what the data actually is/means.

An OID can be added using OBJ_create() (This can also be done via configuration data)

**Comment by slontis** [comment]
Hello @joymcg. Did you come up with a solution?
