### ISSUE TITLE
EVP_DecodeBlock dereferences *f pointer even if n == 0

### ISSUE THREAD

**Issue by nazar554** [openssl/openssl#12143]
https://github.com/openssl/openssl/blob/e7fb44e7c3f7a37ff83a6b69ba51a738e549bf5c/crypto/evp/encode.c#L426

Does it expect to find a null terminator if `n == 0` ?
Maybe move the check `(n > 0)` to the left side of condition?

**Comment by levitte** [comment]
Thanks.  Fix in #12144
