### ISSUE TITLE
What is obj_mac.h used for

### ISSUE THREAD

**Issue by bowensd** [openssl/openssl#12152]
The notes said "Do not edit ".what is obj_mac.h used for? What would happened if I add a #define?

**Comment by bowensd** [comment]
If I need to add a new algorithm , is it necessary to add a new nid in obj_mac.h?

**Comment by paulidale** [comment]
No you shouldn't edit this directly.  Instead add your object to: `crypto/objects/objects.txt` then run `make update`.

**Comment by bowensd** [comment]
@paulidale Is obj_mac.h generated from the crypto/objects/objects.txt ?

**Comment by paulidale** [comment]
Yes.

**Comment by bowensd** [comment]
Thanks!And  I have another question~~When I add my object and make,build happens:

./libssl.so: undefined reference to `EVP_sm4_128_gcm'
collect2: error: ld returned 1 exit status
Makefile:6459: recipe for target 'apps/openssl' failed
make[1]: *** [apps/openssl] Error 1
make[1]: Leaving directory '/home/bowen/openssl-1.1.1d'
Makefile:174: recipe for target 'all' failed
make: *** [all] Error 2

Here is what I did:
                 1.added my object to crypto/objects/objects.txt  and make update
                 2. added EVP_add_cipher(EVP_CIPHER *cipher)
                 3.implemented corresponding evp interface.
Here is the question:
How to sovle the build error？ It's there any document or instruction for adding an algorithm ? Thank u again!!

**Comment by paulidale** [comment]
`EVP_sm4_128_gcm` isn't being exported from libcrypto.  `make update` should cover this too.

Note that new `EVP_xxx` algorithm functions are not being accepted.  Instead algorithms should be accessed by name, preferably using, in this case, `EVP_CIPHER_fetch()`.

**Comment by bowensd** [comment]
Thanks for advice! It didn't work.But I find out that obj_mac.h doesn't generate code after adding objects to `crypto\object\obects.txt` but other related files did such as `obj_dat.h` and `obj_mac.num`. It seems to be the core of the problem.How to solve it?

**Comment by beldmit** [comment]
Building of these files is available only on unix-like systems via `make update`

**Comment by bowensd** [comment]
Thanks for help.Yes my system is ubuntu 14.And I run `make clean`  `make depend` and `make update` . But As I said obj_dat.h and obj_mac.num they were updated , except for `obj_mac.h`.All the files related should be updated once I add object to `objects.txt`,right?

**Comment by bowensd** [comment]
I deleted some code from obj_mac.h and then run `make update`  and then  no code was recover as imagined......

**Comment by beldmit** [comment]
If you look at `make update` definition (e.g. via `make -n -B update` to see the real commands), you'll see that the regeneration also involves as intermediate `obj_mac.num` that you did not edit. 

BTW, I don't recommend making such experiments - it's possible to break the build completely.

**Comment by bowensd** [comment]
Thanks a lot! It's useful!
