### ISSUE TITLE
Will openssl Sever shutdown the connection when server certificate validity time expired?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12165]
Hi, 
    I want to know Will Sever shutdown the connection when server certificate validity time expired? I mean if the certificate validity expired during the server running, the server will refused the client connections? 
   If it not, is there any method I can detect the validity expired, like cerfiticate healthy check.

**Comment by BenBE** [comment]
The TLS server component in OpenSSL works independent of the validity or trust status of the certificate provided.

If you want to detect such situations you might want to implement a small watchdog that regularly connected to your server and checked if the server provided a valid and trusted (by your watchdog's system) certificate (this check is automatic for TLS client connections, unless disabled). If this check failed you could then act accordingly by e.g. switching the certificate and reloading the server to use that updated certificate.

HTH.

**Comment by joymcg** [comment]
>  (this check is automatic for TLS client connections, unless disabled). 
> HTH.

You mean openssl client side(not the client app, I mean the client use openssl) will check server's certificate validity automaticlly?

**Comment by kaduk** [comment]
The client will check the server certificate's validity at the time the connection is established.  There is no logic inside libssl to "remember" that the server certificate will expire in N days/hours and close the TLS connection at that time.
