### ISSUE TITLE
bad email: legaI@opensslfoundation.org

### ISSUE THREAD

**Issue by ideafarm** [openssl/openssl#12168]
The email address is not found:

The response from the remote server was:

550 5.1.1 <legaI@opensslfoundation.org>: Recipient address rejected: User unknown in local recipient table 

I'm a new contributor and am trying to email the required contributor's license.

**Comment by kaduk** [comment]
You sent to <ell> <ee> <gee> <a> <capital i>, but need to send to <ell> <ee> <gee> <a> <ell>

**Comment by kaduk** [comment]
Actually, please clarify: did you copy/paste from somewhere or type in manually?

**Comment by ideafarm** [comment]
I used OCR to read the italicized email address from the agreement.  Your eyes were sharper than mine!  Thanks.

**Comment by mspncp** [comment]
> You sent to [ell] [ee] [gee] [a] [capital i], but need to send to [ell] [ee] [gee] [a] [ell]

Good catch, I'm amazed you figured this out so quickly @kaduk. In a fixed size font, the error would have been obvious:

```
550 5.1.1 legaI@opensslfoundation.org: Recipient address rejected: User unknown in local recipient table
```

**Comment by kaduk** [comment]
I mean, I read email in mutt in a terminal with a fixed-width font specifically chosen to disambiguate such "confusables".  Given those preconditions, it was pretty easy to see :)

**Comment by ideafarm** [comment]
Can someone help me find my glasses? ...

**Comment by mspncp** [comment]
> Can someone help me find my glasses? ...

You can find them right there in your avatar.
