### ISSUE TITLE
Missing EC documentation

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#12189]
It's been recently discovered that `make doc-nits` didn't report new undocumented functions correctly lately, which had some functions slip through without being documented or otherwise noted:

- EC_GROUP_get_field_type(3)

**Comment by mattcaswell** [comment]
Ping @bbbrumley.

**Comment by bbbrumley** [comment]
Yep that's me. Whoops.

I'll get you a PR tonight or tomorrow.
