### ISSUE TITLE
err.h Conflict with the system header usr/include err.h in Xcode when compiling

### ISSUE THREAD

**Issue by zhoubingyu** [openssl/openssl#12183]
I import a bsdiff tool,http://www.daemonology.net/bsdiff/
in the bspatch.c file #include <err.h>. when using err or errx function,occur sevral compiling errors

is there any suggetions,thanks a lot!

<img width="683" alt="截屏2020-06-18下午3 32 30" src="https://user-images.githubusercontent.com/13882261/84992886-1931a880-b17b-11ea-832d-f40bdbb82f36.png">

**Comment by levitte** [comment]
`#include <err.h>` should never include the OpenSSL err.h.  Use `#include <openssl/err.h>`.  Please set your inclusion directories when compiling accordingly.

**Comment by zhoubingyu** [comment]
@levitte Thank you!  you mentioned about a right way,and I found another way out ,Thanks.
