### ISSUE TITLE
Add a 'make fipsinstall' target

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#12195]
The OpenSSL 3.0 Wiki Page has a section [Completing the installation of the FIPS Module](https://wiki.openssl.org/index.php/OpenSSL_3.0#Completing_the_installation_of_the_FIPS_Module) explaining the FIPS installation process. This process involves an `openssl fipsinstall` call with a long argument list.

```
$ openssl fipsinstall   \
        -out /usr/local/ssl/fipsmodule.cnf   \
        -module /usr/local/lib/ossl-modules/fips.so   \
        -provider_name fips  \
        -mac_name HMAC -macopt digest:SHA256 -macopt hexkey:00   \
        -section_name fips_sect
```
Wouldn't it make sense to have a `make fipsinstall` target which calls `openssl fipsinstall` with reasonable defaults?

Related to #11929

**Comment by slontis** [comment]
Related to PR #12311..
Can someone review please.

**Comment by slontis** [comment]
With the above changes it will now just need the -out and -module options..

**Comment by richsalz** [comment]
I think the target should be "install-fips-module" as part of the install target, or "make-fips-hmac" or "make-fips-config" as part of building the mangpages style of thing.  The name "make fipsinstall" is confusing, as it is also the name of an existing command.  I can write the make/mms/nmake templates if it will help, and we can agree on what the target should be.

**Comment by mspncp** [comment]
Why isn't `make fipsinstall` a suitable target name if it's just a convenience target which calls `openssl fipsinstall` with reasonable defaults?

P.S: FIPS _module_ is a name reminiscent of the FIPS 2.0 era.

**Comment by richsalz** [comment]
If folks think it's reasonable, okay, but I find re-using a make target name as the name of a program to be confusing. Perhaps it is just me.

OpenSSL uses the term providers, but NIST uses the term module. :)

**Comment by slontis** [comment]
All it does is generate a fips related config file - so the 'module' term would not be clearer.

**Comment by richsalz** [comment]
So how about "make fipsconf" ?

**Comment by t8m** [comment]
Is the target going to install the config file to the destdir? If so, it should be called install-something - perhaps install-fipsconf or install-fips-config

**Comment by richsalz** [comment]
Looking at a generated Makefile, it seems that the thing to do is add some lines to the "install_ssldirs", like right after this stanza: https://github.com/openssl/openssl/blob/master/Configurations/unix-Makefile.tmpl#L580

**Comment by richsalz** [comment]
I edited the wiki page to remove all the no-longer-required options.

Perhaps no surprise to anyone, doing this in the make process is kinda subtle because it depends on the modules and the command.  This diff does it:
```
; g diff
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index 441f83c345..c6aa1523c3 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -818,6 +818,10 @@ install_programs: install_runtime_libs build_programs
                mv -f $(DESTDIR)$(INSTALLTOP)/bin/$$fn.new \
                      $(DESTDIR)$(INSTALLTOP)/bin/$$fn; \
        done
+       @$(ECHO) "creating $(DESTDIR)$(MODULESDIR)/fips.cnf"
+       $(DESTDIR)$(INSTALLTOP)/bin/openssl fipsinstall \
+            -out $(DESTDIR)$(OPENSSLDIR)/fips.cnf \
+            -module $(DESTDIR)$(MODULESDIR)/fips.so
 
 uninstall_runtime: uninstall_programs uninstall_runtime_libs
 ```
I have it as the end of the ```install_programs``` target.  It's not a separate target and this location doesn't seem ideal, but putting it in the ```install_modules``` doesn't work because the command-line might not be installed.

Thoughts?

**Comment by levitte** [comment]
I thought that the intention would be to have a target that creates a *local* (build tree) fips module configuration, that can be used by tests as well as manually. It's not yet clear if we should provide an installation target as well.

**Comment by mspncp** [comment]
When I created the issue, I naively meant a public installation with reasonable default arguments to some location which is configurable but comes with a reasonable default. Just as it is the case for ‚make install‘.

**Comment by levitte** [comment]
Oh, ok...  I always thought it was about not having to have the `openssl fipsinstall` command duplicated all over the test recipes.

I do recall early discussions regarding having it automatically installed or not, and back then, the common opinion seemed to be leaning toward not doing this, and having a section on this in the User/Security documentation (which hasn't been written yet as far as I know), i.e. would be something that the Security Officer would have to run *explicitly* and *separately*.  @paulidale, @slontis, @mattcaswell, does this correspond to your impressions?

**Comment by slontis** [comment]
I think it was @mspncp that suggestion this to start with - so he may have a different idea of what it is for..
The one to install the fips config once before any test was run would be useful.

**Comment by levitte** [comment]
>  The one to install the fips config once before any test was run would be useful.

That's the local (in build tree) installation.

I think we're getting confused by the app being called `fipsinstall`, it seems to have lead to misunderstandings re intent...

**Comment by slontis** [comment]
fipsconfig was suggested..

**Comment by levitte** [comment]
> fipsconfig was suggested..

As the app name?  Yes!

**Comment by mspncp** [comment]
I don’t understand the discussion about the naming. If „fipsinstall“ is a suitable name for the app, then it should be a suitable name for the make target, no? Conversely, choosing different names only creates confusion. 

As for private vs. public installation: if the former is needed for the tests, there should be an internal target which is triggered automatically. The ‚fipsinstall‘ target should be the official one which needs to be run explicitly by the administrator resp. security engineer.

**Comment by mattcaswell** [comment]
> I thought that the intention would be to have a target that creates a local (build tree) fips module configuration

No - I was expecting an actual installation target that end  users could use

> I always thought it was about not having to have the openssl fipsinstall command duplicated all over the test recipes.

Having that is also desirable and is something we have discussed - but is separate to what I understood this issue to be about.

**Comment by levitte** [comment]
Ok then.

For the local/internal installation, it could be sufficient to use the actual file as a target, i.e. have 'tests' depend on 'providers/fipsmodule.cnf'

**Comment by mspncp** [comment]
> For the local/internal installation, it could be sufficient to use the actual file as a target, i.e. have 'tests' depend on 'providers/fipsmodule.cnf'

Sounds reasonable to me.

**Comment by richsalz** [comment]
I agree with https://github.com/openssl/openssl/issues/12195#issuecomment-686962388 (providers/fipsmodule.cnf is a dependency for tests).  I also and still think fipsinstall is a really bad name and fipsconfig is better.
