### ISSUE TITLE
STACK&LHASH "cleanups" deprecation issues

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#12193]
I'm concerned about them using our types. I'll try and give another example to illustrate my point. I'll use a stack because I believe the same issue already exists in master, that you are now introducing for hashes here - and there are more instances of stack usage that I can use as an example.

```
#include <openssl/x509_vfy.h>

int dostuff(X509_STORE_CTX *ctx)
{
    int i;
    STACK_OF(X509) *xstk = X509_STORE_CTX_get0_chain(ctx);

    for (i = 0; i < sk_X509_num(xstk); i++) {
        X509 *x = sk_X509_value(xstk, i);
        /* Do something with x */
    }
}
```

In this example an application wants to use our APIs to iterate through the contents of a stack. The above code compiles just fine on a normal build of current master. However it fails to compile in a no-deprecated build. I have to make it look like this instead:

```
#include <openssl/x509_vfy.h>

DEFINE_STACK_OF(X509)

int dostuff(X509_STORE_CTX *ctx)
{
    int i;
    STACK_OF(X509) *xstk = X509_STORE_CTX_get0_chain(ctx);

    for (i = 0; i < sk_X509_num(xstk); i++) {
        X509 *x = sk_X509_value(xstk, i);
        /* Do something with x */
    }
}
```

This code compiles fine in a no-deprecated build of master - but fails to compile on a normal build of master. As an application author it doesn't seem possible to get this code to work in both builds.

**Comment by beldmit** [comment]
Tried to do smth like 
```
# define STACK_DEF_GUARD(t) OPENSSL_STACK_##t##_DEFINED
# ifndef STACK_DEF_GUARD(t)
# define STACK_DEF_GUARD(t)
... 

# endif 
```
in `safestack.h`

but it's unrecognizable syntax and I'm not so familiar with C preprocessor

**Comment by levitte** [comment]
You `#ifndef` just the symbol, i.e.:

``` C
# ifndef STACK_DEF_GUARD
```

In C, macros with arguments and macros without are still the same macro, just with different semantics

**Comment by levitte** [comment]
@richsalz, the way safestack is currently set it, the definitions in safestack.h are deprecated, i.e. when `no-deprecated` is configured or when the application build asks for the same effect (by defining `OPENSSL_NO_DEPRECATED`), then and only then, the application must define the stack itself.  In other words, this should work in both configurations:

``` C
#ifdef OPENSSL_NO_DEPRECATED_3_0
DEFINE_STACK_OF(X509)
#endif
```

**Comment by mattcaswell** [comment]
> @richsalz, the way safestack is currently set it, the definitions in safestack.h are deprecated, i.e. when no-deprecated is configured or when the application build asks for the same effect (by defining OPENSSL_NO_DEPRECATED), then and only then, the application must define the stack itself. In other words, this should work in both configurations:

This might be technically how to achieve it - but I don't think we should be expecting our users to have to write code like that. They shouldn't need to write "ifdef hackery" just to get their code to work in a no-deprecated build vs a normal  build. If their code works in a  no-deprecated build then it should just work in a normal build - you should never get the situation where something works in no-deprecated but fails in a normal build.

**Comment by levitte** [comment]
Another way to give the application something more tangible would be this:

``` diff
diff --git a/include/openssl/safestack.h b/include/openssl/safestack.h
index c94ce78cf9..9150690ddd 100644
--- a/include/openssl/safestack.h
+++ b/include/openssl/safestack.h
@@ -186,6 +186,10 @@ typedef const char *OPENSSL_CSTRING;
  */
 DEFINE_OR_DECLARE_STACK_OF_STRING()
 DEFINE_OR_DECLARE_STACK_OF_CSTRING()
+#if !(defined(OPENSSL_BUILDING_OPENSSL) || defined(OPENSSL_NO_DEPRECATED_3_0))
+# define OSSL_DEFINED_STACK_OF_OPENSSL_STRING
+# define OSSL_DEFINED_STACK_OF_OPENSSL_CSTRING
+#endif
 
 #if !defined(OPENSSL_NO_DEPRECATED_3_0)
 /*
@@ -194,6 +198,7 @@ DEFINE_OR_DECLARE_STACK_OF_CSTRING()
  */
 typedef void *OPENSSL_BLOCK;
 DEFINE_SPECIAL_STACK_OF(OPENSSL_BLOCK, void)
+# define OSSL_DEFINED_STACK_OF_OPENSSL_BLOCK
 #endif
 
 /*
```

> This might be technically how to achieve it - but I don't think we should be expecting our users to have to write code like that. They shouldn't need to write "ifdef hackery" just to get their code to work in a no-deprecated build vs a normal build. If their code works in a no-deprecated build then it should just work in a normal build - you should never get the situation where something works in no-deprecated but fails in a normal build.

I generally agree.  However, the *stack definitions* in safestack.h are a hell-hole that we somehow need to get out of...  it's basically a bad situation (compile with `-fkeep-inline-functions` and you'll exactly how bad it can get)

**Comment by mattcaswell** [comment]
> I generally agree. However, the stack definitions in safestack.h are a hell-hole that we somehow need to get out of... it's basically a bad situation (compile with -fkeep-inline-functions and you'll exactly how bad it can get)

I think we should consider making them normal functions instead of inline. If we really *must* have inline, then perhaps we could have them defined as inline for our own code, but normal for others.

**Comment by levitte** [comment]
> I think we should consider making them normal functions instead of inline.

That could be done.  I think there was already an idea like this, but you have to consider that there will be immediate bloat in libcrypto.num, and believe you me, that's a fast growing list.

**Comment by t8m** [comment]
I'd prefer making the DEFINE_STACK_OF macro to be no-op in the regular build in the application code.

**Comment by levitte** [comment]
> I'd prefer making the DEFINE_STACK_OF macro to be no-op in the regular build in the application code.

Not sure what you meant with that...

**Comment by mattcaswell** [comment]
> Not sure what you meant with that...

The point is that applications have to put a `DEFINE_STACK_OF` line into their code if they are using a "no-deprecated" build - but if they are using a normal build of OpenSSL then that line causes compilation failures. By making it a no-op in a normal build the problem goes away.

**Comment by t8m** [comment]
> > Not sure what you meant with that...
> 
> The point is that applications have to put a `DEFINE_STACK_OF` line into their code if they are using a "no-deprecated" build - but if they are using a normal build of OpenSSL then that line causes compilation failures. By making it a no-op in a normal build the problem goes away.

But I see that that would not work as this macro can be used for arbitrary application types.

**Comment by t8m** [comment]
So a different idea - still ugly though: we require adding a 
#define OPENSSL_I_DONT_WANT_COLLIDING_STACK_DEFINES
to applications that are converted to call DEFINE_STACK_OF() by themselves.
Of course feel free to propose some less ugly name of the define.

**Comment by levitte** [comment]
> #define OPENSSL_I_DONT_WANT_COLLIDING_STACK_DEFINES

So *another* flag macro to deal with this situation?

On the other hand, that would actually be handy, and I would rather have that replace the current construct.  After all, it's as easy as this in safestack.h:

``` C
#ifndef OPENSSL_NO_DEFAULT_STACK_DEFS
DEFINE_STACK_OF(OPENSSL_STRING);
#endif
```

However, that still leaves the question of deprecation, 'cause part of the effort that @richsalz did was to deprecate the default stack definitions in safestack.h.  They really really really need to go at some point.

**Comment by t8m** [comment]
Instead of having OPENSSL_BUILDING_OPENSSL we would have this OPENSSL_NO_DEFAULT_STACK_DEFS and it would be defined automatically in build system in no-deprecated builds.
Please note that this is not just about safestack.h but also all the DEFINE_OR_DECLARE_STACK_OF() use in other public headers.
But yes, the 3rd party apps would have to use #define OPENSSL_NO_DEFAULT_STACK_DEFS whenever they use DEFINE_STACK_OF() macro themselves. Not sure if that is acceptable - to me it seems to be but there might be other opinions.
Unfortunately I do not see how we could get a deprecation notice in the regular builds. We can just document the change in CHANGES.md

**Comment by mattcaswell** [comment]
This is fixed now. Closing.
