### ISSUE TITLE
which stanard that openssl3.0 will follow , Fips 140-2 or Fips 140-3 ?

### ISSUE THREAD

**Issue by chensqecc** [openssl/openssl#12192]
hi  Gentlemen
Now openssl3.0 are developing.Obviously FIPs will be a significant feature of it. Now from Openssl org net, Openssl3.0 fips feature will follow 140-2 (https://www.openssl.org/blog/blog/2018/09/25/fips/).
while from NIST website:https://csrc.nist.gov/projects/fips-140-3-transition-effort
It declares :CMVP stops accepting FIPS 140-2 submissions for new validation certificates.
![image](https://user-images.githubusercontent.com/45892133/85017004-573fc400-b19d-11ea-930c-4fe291472327.png)
so i feel openssl3.0 fips process seems not matched with NIST.
Does we have any plan and guidepost for FIPS 140-3?

**Comment by mattcaswell** [comment]
We are still targeting FIPS 140-2.

**Comment by chensqecc** [comment]
hmm,does we have any anlaysis for FIPS 140-3? whether we will follow FIPS 140-3 in future?
if we will do, is there any plan here?
@mattcaswell

**Comment by mattcaswell** [comment]
We have discussed it with the lab. No doubt there we will go there eventually. IIRC there  were some issues around 140-3 and the associated IGs which are still in draft (last I heard) and may have some significant impacts on us. To avoid any chance of delays we are continuing with 140-2.

**Comment by chensqecc** [comment]
ok  thank you

**Comment by chensqecc** [comment]
And  here still have  some question,
from the lastest info from NIST :https://csrc.nist.gov/projects/fips-140-3-transition-effort
![image](https://user-images.githubusercontent.com/45892133/85120022-376bd700-b255-11ea-8cbd-4410d7734dc7.png)
140-3 had been officially released.
And from Openssl3.0 guidepost，3.0 will release at the end of 2020. And CMVP will  stop accepting FIPS 140-2 submissions for new validation certificates by September 21, 2021. 
it means Openssl3.0 fips module just can be accept before  September 21, 2021, Life cycle will be very short.
so what about your opinion about it?  
thanks! @mattcaswell

**Comment by mattcaswell** [comment]
> it means Openssl3.0 fips module just can be accept before September 21, 2021, Life cycle will be very short.

No. Once issued the certificate still has the same validity period as if FIPS 140-3 had not come along.

**Comment by richsalz** [comment]
Except that since OpenSSL isn't doing validation updates (i.e., adding platforms to its certificate), then folks who want to use this on other platforms *might* (depending on what the OpenSSL build instructions and policy say) have to seek their own validation.  If not, they can claim "vendor affirmed" as I understand.  But for those folks who do have to seek their own validation, yes, the timeline is short.

I am not a member of the project, this is my personal opinion: you got it for free, you shouldn't complain.

**Comment by chensqecc** [comment]
ok，thank you . i am not complaining about it，i want to know whether we have any plan about it.
@richsalz

**Comment by chensqecc** [comment]
ok  thank you @mattcaswell

**Comment by chensqecc** [comment]
And from now our analysis , FIPS 140-2 and FIPS 140-3 should almost same for Cryptographic algorithm module.   @mattcaswell   @richsalz

**Comment by mattcaswell** [comment]
Seems like the question was answered. Closing.
