### ISSUE TITLE
openssl-3.0.0-alpha3 does not compile on ia64

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#12197]
Could someone please try to compile it on Linux IA64? I'm getting here:

>../Configure linux-ia64
>Configuring OpenSSL version 3.0.0-alpha4-dev for target linux-ia64
>Using os-specific seed configuration
>ghash-ia64.s appears 2 times for the product providers/libfips.a
>ghash-ia64.s appears 2 times for the product libcrypto
>Died at ../Configure line 2348.

I have no porter box access but the Debian build failed with the very same error message.

**Comment by levitte** [comment]
Found it, fixed it, please try #12203

**Comment by sebastianas** [comment]
On 2020-06-19 01:11:29 [-0700], Richard Levitte wrote:
> Found it, fixed it, please try #12203

Yeah. So this passes the configure line. I have neither a cross compiler
nor porter box access for IA64.
If you feel good with it, just merge it into master and once the next
alpha gets released I let it build and report if it fails to compile
later on.

Sebastian

**Comment by levitte** [comment]
It's been merged now.  If the next tarball builds better, a little "hooray" here would be nice feedback :wink:
(do you know, btw, that we make nightly snapshot tarballs?  https://www.openssl.org/source/snapshot/
They aren't "official", but equivalent enough)

**Comment by sebastianas** [comment]
On 2020-06-20 12:40:01 [-0700], Richard Levitte wrote:
> It's been merged now.  If the next tarball builds better, a little "hooray" here would be nice feedback :wink:
> (do you know, btw, that we make nightly snapshot tarballs?  https://www.openssl.org/source/snapshot/
> They aren't "official", but equivalent enough)

I could take the patch and let it build - that is not the problem. The
thing is that I can not let it build only on ia64. It would be built on
all Debian build machines (~20). And I would like to avoid that to just
get the ia64 results. It took the mips/mips64el just two days (or so) to
get to the openssl package (also the experimantal packages are not top
priority).

Sebastian

**Comment by levitte** [comment]
Aha, ok
