### ISSUE TITLE
CLIENTHELLO_MSG.pre_proc_exts is not freed.

### ISSUE THREAD

**Issue by mkaniewski** [openssl/openssl#12194]
Hi,

I came accross a scenario in which `CLIENTHELLO_MSG.pre_proc_exts` is not freed:
1. I set client hello callback using `SSL_CTX_set_client_hello_cb()`.
2. I call `SSL_accept(ssl)` to accept a client connection.
3. I return SSL_CLIENT_HELLO_RETRY in the callback.
4. I call `SSL_close(ssl)`.

The free which is placed at the end of `tls_early_post_process_client_hello()` never happens and the `clienthello.pre_proc_exts` remains allocated.

I think that `SSL_close()` should handle this case. A proposed fix looks as follow:
```
--- a/ssl/ssl_lib.c
+++ b/ssl/ssl_lib.c
@@ -1217,6 +1217,8 @@ void SSL_free(SSL *s)
     OPENSSL_free(s->ext.ocsp.resp);
     OPENSSL_free(s->ext.alpn);
     OPENSSL_free(s->ext.tls13_cookie);
+    if (s->clienthello != NULL)
+        OPENSSL_free(s->clienthello->pre_proc_exts);
     OPENSSL_free(s->clienthello);
     OPENSSL_free(s->pha_context);
     EVP_MD_CTX_free(s->pha_dgst);
```

**Comment by kaduk** [comment]
I would say that "you shouldn't do that" (the combination (3) and (4)), but am willing to add the proposed change.
Do you want to create a pull request for it or should I do so?
