### ISSUE TITLE
Broken on 32 bit big endian

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#12199]
This code does not work on 32 bit big endian machines:

https://github.com/openssl/openssl/blob/9a7319b0b0b9ddaa440b102dc8e197d267700756/test/ossl_test_endian.h#L13-L20

I think it just needs to be changed to an int. But I wonder if we have other code like that that uses a long instead of an int. Maybe all that code should use that macro.

gcc also has built in macro's for that, I suggest we use that by default instead.

**Comment by sebastianas** [comment]
> I think it just needs to be changed to an int. But I wonder if we have other code like that that uses a long instead of an int. Maybe all that code should use that macro.

look at test_param_uint64() in params_api_test.c. 

> gcc also has built in macro's for that, I suggest we use that by default instead.

There is __builtin_bswap16() … 128() if __HAVE_BUILTIN_BSWAP16__ … 128 is defined.
If it is not, the preferred way is to do something like
>static line uint16_t __do_the_swap16(uint16_t val)
>{
>        return 
>         (val & 0x00ffU) << 8) |
>         (val & 0xff00U) >> 8);
>}

or as a define or so. But not loosing the type, using an array and copy it byte by byte.
To figure out what endian you are on, there is
>    __BYTE_ORDER__

which points is defined as

> __ORDER_LITTLE_ENDIAN__
> __ORDER_PDP_ENDIAN__
> __ORDER_BIG_ENDIAN__

So you can either pass the value or do the swap in your LE_to_cpu() macro/inline function.

**Comment by levitte** [comment]
I fail to understand why it matters if `one` is a long or an int...  as long as it's not a char, `little` should end up being zero on big endian machines, no?

**Comment by paulidale** [comment]
We do have other code that uses the same endian test union, lots of it.  This union was copied from one such.  All of these files contain the same thing:

- crypto/modes/ctr128.c
- crypto/modes/gcm128.c
- crypto/modes/siv128.c
- crypto/modes/xts128.c
- crypto/chacha/chacha_enc.c
- crypto/evp/e_chacha20_poly1305.c
- crypto/evp/bio_ok.c
- crypto/sha/sha_local.h
- crypto/sha/sha256.c

This would mean much is broken on 32 bit big endian machines.  I wonder how many 32 bit big endian users we have given this list?


I wouldn't use `params_api_test.c` as a reference for anything endian.  It is verifying that the OSSL_PARAM code is doing things as per the design, it is very very specific.

**Comment by t8m** [comment]
Most of the usage of the pattern that @paulidale mentions is there since ages and we have 32 bit ppc BE and s390 packages of openssl-1.0.2. The test suite is run during the builds and I would not expect it passing if the pattern was really broken on these architectures.

**Comment by kroeckx** [comment]
So looking closer at things, I think the issue is not the
detection, but the test itself is broken.

So what happens is:
- le_copy(buf, raw_values[n].value, len);

The raw_values[n].value is in LE format, and for a BE machine, it
changes it to BE.

- BN_lebin2bn(raw_values[n].value, (int)len, NULL))
  
Which converts the LE format to a BN, which is fine

- OSSL_PARAM_set_BN(&param, b)

Set the the OSSL_PARAM from a BN, which should work, writen to
bnbuf. OSSL_PARAM is a LE format.

- TEST_mem_eq(bnbuf, param.return_size, buf, param.return_size))

Compares an LE bnbuf to a BE buf

But I have no idea why this works on s390x

The fix for that test is simple, change le_copy to memcpy

**Comment by kroeckx** [comment]
The 32 bit big endian machines have other things in common:

    # Subtest: ../../test/keymgmt_internal_test
    1..1
        # Subtest: test_pass_key
        1..1
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [-1133215803] compared to [-981502788]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 0
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [65537] compared to [16777472]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 1
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [2064855961] compared to [-1724705925]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 2
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [59747] compared to [1676214272]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 3
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [52919] compared to [-1211236352]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 4
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [1] compared to [16777216]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 5
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [34201] compared to [-1719336960]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 6
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [48519] compared to [-2017656832]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 7
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [2] compared to [33554432]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 8
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [52283] compared to [1003225088]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 9
        # ERROR: (int) 'expected[i] == keydata[i]' failed @ test/keymgmt_internal_test.c:228
        # [3] compared to [50331648]
        # INFO:  @ test/keymgmt_internal_test.c:231
        # i = 10
        not ok 1 - iteration 1
    not ok 1 - test_pass_key


Error generating parameters
../../util/wrap.pl ../../apps/openssl genpkey -genparam -algorithm DH -pkeyopt 'gindex:1' -pkeyopt 'pbits:2048' -pkeyopt 'qbits:256' -pkeyopt 'type:fips186_4' -outform DER -out dhgen.der => 1
not ok 7 - genpkey DH params fips186_4 DER

#   Failed test 'genpkey DH params fips186_4 DER'
#   at test/recipes/15-test_gendh.t line 60.
Error reading parameter file dhgen.der
../../util/wrap.pl ../../apps/openssl genpkey -paramfile dhgen.der -pkeyopt 'gindex:1' -pkeyopt 'hexseed:0102030405060708090A0B0C0D0E0F1011121314' -pkeyopt 'pcounter:25' -text => 1
not ok 8 - genpkey DH fips186_4 with DER params

#   Failed test 'genpkey DH fips186_4 with DER params'
#   at test/recipes/15-test_gendh.t line 72.
Error generating key



not ok 10 - genpkey DH with a small private len should fail

#   Failed test 'genpkey DH with a small private len should fail'
#   at test/recipes/15-test_gendh.t line 84.
Error generating key
F7FB2D60:error::Diffie-Hellman routines:generate_key:BN lib:crypto/dh/dh_key.c:313:
../../util/wrap.pl ../../apps/openssl genpkey -algorithm DH -pkeyopt 'group:ffdhe3072' -pkeyopt 'priv_len:3072' -text => 1
ok 11 - genpkey DH with a large private len should fail
Error generating key
F7E02D60:error::Diffie-Hellman routines:generate_key:BN lib:crypto/dh/dh_key.c:313:
../../util/wrap.pl ../../apps/openssl genpkey -algorithm DH -pkeyopt 'group:ffdhe3072' -pkeyopt 'priv_len:256' -text => 1
not ok 12 - genpkey DH with a minimum strength private len

#   Failed test 'genpkey DH with a minimum strength private len'



Error generating parameters
../../util/wrap.pl ../../apps/openssl genpkey -genparam -algorithm DSA -pkeyopt 'gindex:1' -pkeyopt 'pbits:2048' -pkeyopt 'qbits:256' -pkeyopt 'type:fips186_4' -outform DER -out dsagen.der => 1
not ok 6 - genpkey DSA params fips186_4 DER

#   Failed test 'genpkey DSA params fips186_4 DER'
#   at test/recipes/15-test_gendsa.t line 55.
Error reading parameter file dsagen.der
../../util/wrap.pl ../../apps/openssl genpkey -paramfile dsagen.der -pkeyopt 'gindex:1' -pkeyopt 'hexseed:0102030405060708090A0B0C0D0E0F1011121314' -pkeyopt 'pcounter:25' -text => 1
not ok 7 - genpkey DSA fips186_4 with DER params


And then the test suite hangs doing:
apps/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_pubexp:3 -pkeyopt rsa_keygen_bits:512 -out genrsatest.pem


Full logs available at:
https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=hppa&ver=3.0.0%7E%7Ealpha3-1&stamp=1592493638&raw=0
https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=powerpc&ver=3.0.0%7E%7Ealpha3-1&stamp=1592479927&raw=0

I have access to both a hppa and powerpc machine, so I can run tests if you want.

**Comment by sebastianas** [comment]
With the #12371 pull it happens to pass the testuite on 32bit PPC.
Could we still please:
- get rid of B_ENDIAN and instead use 
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__

- use explicit __builtin_bswap32() / __builtin_bswap16() if a swap is required (based on the byte order given above)
  instead some "generic" byte swapping which may break aliasing.

I could provide patches once we agree (I also know that I am not the fastest).

**Comment by kroeckx** [comment]
So in looking at things, I think the test is actually correct as things are now. Above I wrote `OSSL_PARAM is a LE format`, but at least the documentation and the implementation don't agree, it's in native format. I think that native format for an OSSL_PARAM is wrong, which is why I filed #12388.

**Comment by sebastianas** [comment]
On 2020-07-07 12:23:04 [-0700], Kurt Roeckx wrote:
> So in looking at things, I think the test is actually correct as things are now. Above I wrote `OSSL_PARAM is a LE format`, but at least the documentation and the implementation don't agree, it's in native format. I think that native format for an OSSL_PARAM is wrong, which is why I filed #12388.

So regarding in BYTE_ORDER and bswap I should follow up there?

**Comment by kroeckx** [comment]
I was just looking into creating a PR to get rid of the B_ENDIAN
and L_ENDIAN defines. But since not all platforms actually have
the __BYTE_ORDER__ define, I need fall back code, like we do in
test/ossl_test_endian.h. Because we need that fallback code, it
can't be done in the preprocessor.

But then I came acros that we support big endian x86/x86_64. It
looks like VOS always keeps it's numbers in big endian, even when
the processor is little endian. So at least for that case we'll
need to keep the B_ENDIAN define.

**Comment by levitte** [comment]
FYI, there's a sourceforge project that holds information on all sorts of predefined macros.  Among others, it has [a whole page dedicated to endianness](https://sourceforge.net/p/predef/wiki/Endianness/)

**Comment by sebastianas** [comment]
On 2020-07-07 13:35:40 [-0700], Kurt Roeckx wrote:
> I was just looking into creating a PR to get rid of the B_ENDIAN
> and L_ENDIAN defines. But since not all platforms actually have
> the __BYTE_ORDER__ define, I need fall back code, like we do in
> test/ossl_test_endian.h. Because we need that fallback code, it
> can't be done in the preprocessor.
> 
> But then I came acros that we support big endian x86/x86_64. It
> looks like VOS always keeps it's numbers in big endian, even when
> the processor is little endian. So at least for that case we'll
> need to keep the B_ENDIAN define.

From https://gcc.godbolt.org/z/8ophTE there is always a __BYTE_ORDER__
around. But you lost me with VOS.

Sebastian

**Comment by kroeckx** [comment]
> From https://gcc.godbolt.org/z/8ophTE there is always a __BYTE_ORDER__
> around.

I think gcc only added support for that since gcc 4.6, and I'm
afraid people still use older gcc versions.

> But you lost me with VOS.

https://en.wikipedia.org/wiki/Stratus_VOS

**Comment by sebastianas** [comment]
On 2020-07-08 00:31:46 [-0700], Kurt Roeckx wrote:
> I think gcc only added support for that since gcc 4.6, and I'm
> afraid people still use older gcc versions.

Hmm. So gcc's ChangeLog-2010 states the introduction of __BYTE_ORDER__
in 2010-10-23. Bummer.
Older gcc are a thing? Okay. So maybe we could keep internal endian
state which is fed by the user if not available by the compiler.
It would be an improvement if we get rid of the autodetection of
endianess, use the compilers built-in and otherwise fall back to
converstation macros/static inlines functions based on the size of the
data type and not somthing that works in "auto" mode.


> > But you lost me with VOS.
> 
> https://en.wikipedia.org/wiki/Stratus_VOS
Ui. Interresting thing. According to the wiki page they have support for
x86 and PA-RISC (among others). The x86 port should be little endian and
PA-RISC should be big endian. I very much doubt that they have special
x86 CPUs which are big endian. Also how should add/mul work if the
numbers in the wrong endianess?  Setting B_ENDIAN unconditially on VOS
does not look right.

Sebastian

**Comment by sebastianas** [comment]
On 2020-07-08 22:21:04 [+0200], Sebastian Andrzej Siewior wrote:
> > https://en.wikipedia.org/wiki/Stratus_VOS
> Ui. Interresting thing. According to the wiki page they have support for
> x86 and PA-RISC (among others). The x86 port should be little endian and
> PA-RISC should be big endian. I very much doubt that they have special
> x86 CPUs which are big endian. Also how should add/mul work if the
> numbers in the wrong endianess?  Setting B_ENDIAN unconditially on VOS
> does not look right.

I just read this in that wiki page

|Numeric values in VOS are always big endian, regardless of the endianness of
|the underlying hardware platform. On little endian servers with x86 processors,
|the compilers do a byte swap before reading or writing values to memory to
|transform the data to or from the native little endian format.

So this I haven't seen this coming. And I would love to hear why this
extra exercise.

Sebastian
