### ISSUE TITLE
ASN1_STRING_to_UTF8 could not convert NumericString

### ISSUE THREAD

**Issue by agladkov** [openssl/openssl#1221]
`tag2nbyte` have `-1` at 18th position, but underlying `ASN1_mbstring_copy` supports NumericString.
`tag2nbyte` also used in `do_print_ex` which will not be broken by setting `1` at 18th position of `tag2nbyte`.

**Comment by mattcaswell** [comment]
Fixed by d6079a87db5. Closing.
