### ISSUE TITLE
What's the openssl default entropy of Linux system?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12211]
Hi, 
    I am reading the drbg code, but I am confused about the default entropy of Linux system?
It seems that a macro defined the devrandom device 
# define DEVRANDOM "/dev/urandom", "/dev/random", "/dev/hwrng", "/dev/srandom"
But also I find something use :
    return syscall(__NR_getrandom, buf, buflen, 0);

**I want to know openssl use which one by default**
Thanks in advance.

**Comment by paulidale** [comment]
Linux uses a variety of different sources.  The default source is from the operating system source. This will use the `getrandom(2)` call if available and the DEVRANDOM list (which really ends up as `/dev/urandom`).  It is possible to pick other sources via the configure line.
