### ISSUE TITLE
SM4_SET_KEY undefined reference

### ISSUE THREAD

**Issue by bowensd** [openssl/openssl#12213]
OpenSSL version :1.1.1-d
I add include as in` apps/speed.c`:
```
#ifndef OPENSSL_NO_SM4
# include "internal/sm4.h"
#endif
.....
#ifndef OPENSSL_NO_SM4
    SM4_set_key(key16,&sm4_key);
#endif
```
When I build this program ,it shows error: 
```
apps/speed.c:50:11: fatal error: internal/sm4.h: No such file or directory
 # include "internal/sm4.h"
           ^~~~~~~~~~~~~~~~
compilation terminated.
```
If I run`# include "./crypto/include/internal/sm4.h"`,it shows that `undefined reference SM4_set_key`
So how can I solve it?What's the rule of 'include' in OPENSSL?Why did that happen?

**Comment by InfoHunter** [comment]
`SM4_set_key` should not be used in the application side, it's an internal function rather than an export API. If you want to use it anyway in the application, you can try `#include "crypto/sm4.h"`

**Comment by paulidale** [comment]
Agreed with @InfoHunter, this shouldn't be used and isn't exported.

**Comment by bowensd** [comment]
Thanks a lot! closing this.
