### ISSUE TITLE
pkcs12 error

### ISSUE THREAD

**Issue by zcybeijing** [openssl/openssl#12227]
I want to combine the ca certification file and ca key file to pkcs12 file, the openssl-1.1.1g works ok but the openssl-3.0 reports error. the ca-cert.pem is my ca certification file and ca-key.key is my ca private key file , ca.p12 is my output file. I use the command as follow:
openssl pkcs12 -export -in ca/ca-cert.pem -inkey ca/ca-key.key -out ca/ca.p12
Enter Export Password:
Verifying - Enter Export Password:
ECF30000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto\evp\evp_fetch.c:307:Default library context, Algorithm (RC2-40-CBC), Properties ()
ECF30000:error::digital envelope routines:EVP_CipherInit_ex:initialization error:crypto\evp\evp_enc.c:176:
ECF30000:error::digital envelope routines:EVP_PBE_CipherInit:keygen failure:crypto\evp\evp_pbe.c:132:
ECF30000:error::PKCS12 routines:PKCS12_pbe_crypt:pkcs12 algor cipherinit error:crypto\pkcs12\p12_decr.c:37:
ECF30000:error::PKCS12 routines:PKCS12_item_i2d_encrypt:encrypt error:crypto\pkcs12\p12_decr.c:133:
ECF30000:error::PKCS12 routines:PKCS12_pack_p7encdata:encrypt error:crypto\pkcs12\p12_add.c:119:

**Comment by slontis** [comment]
You may notice the algorithm it cant load is RC2-40-CBC, This algorithm lives in the 'legacy' provider now.
Add the following to your command line..
```
openssl pkcs12 -provider default -provider legacy export -in ca/ca-cert.pem -inkey ca/ca-key.key -out ca/ca.p12

```

**Comment by zcybeijing** [comment]
> You may notice the algorithm it cant load is RC2-40-CBC, This algorithm lives in the 'legacy' provider now.
> Add the following to your command line..
> 
> ```
> openssl pkcs12 -provider default -provider legacy export -in ca/ca-cert.pem -inkey ca/ca-key.key -out ca/ca.p12
> ```

This command is ok! Thanks.

**Comment by zcybeijing** [comment]
> You may notice the algorithm it cant load is RC2-40-CBC, This algorithm lives in the 'legacy' provider now.
> Add the following to your command line..
> 
> ```
> openssl pkcs12 -provider default -provider legacy export -in ca/ca-cert.pem -inkey ca/ca-key.key -out ca/ca.p12
> ```

This command is ok! Thanks.



> You may notice the algorithm it cant load is RC2-40-CBC, This algorithm lives in the 'legacy' provider now.
> Add the following to your command line..
> 
> ```
> openssl pkcs12 -provider default -provider legacy export -in ca/ca-cert.pem -inkey ca/ca-key.key -out ca/ca.p12
> ```

I write code to call the function PKCS12_parse, it has the same problem ,but how can i change my code?  
the follow is the sample of pkread.c in openssl 3.0:

int main(int argc, char **argv)
{
	FILE *fp;
	EVP_PKEY *pkey = NULL;
	X509 *cert = NULL;
	STACK_OF(X509) *ca = NULL;
	PKCS12 *p12 = NULL;
	char *name = NULL;
	int i, ret = EXIT_FAILURE;

	if (argc != 4) {
		fprintf(stderr, "Usage: pkread p12file password opfile\n");
		exit(EXIT_FAILURE);
	}

	OpenSSL_add_all_algorithms();
	ERR_load_PKCS12_strings();

	if ((fp = fopen(argv[1], "rb")) == NULL) {
		fprintf(stderr, "Error opening file %s\n", argv[1]);
		exit(EXIT_FAILURE);
	}

	p12 = d2i_PKCS12_fp(fp, NULL);
	fclose(fp);
	if (p12 == NULL) {
		fprintf(stderr, "Error reading PKCS#12 file\n");
		ERR_print_errors_fp(stderr);
		goto err;
	}
	if (!PKCS12_parse(p12, argv[2], &pkey, &cert, &ca)) {
		fprintf(stderr, "Error parsing PKCS#12 file\n");
		ERR_print_errors_fp(stderr);
		goto err;
	}
	name = find_friendly_name(p12);
	PKCS12_free(p12);
	if ((fp = fopen(argv[3], "w")) == NULL) {
		fprintf(stderr, "Error opening file %s\n", argv[3]);
		goto err;
	}
	if (name != NULL)
		fprintf(fp, "***Friendly Name***\n%s\n", name);
	if (pkey != NULL) {
		fprintf(fp, "***Private Key***\n");
		PEM_write_PrivateKey(fp, pkey, NULL, NULL, 0, NULL, NULL);
	}
	if (cert != NULL) {
		fprintf(fp, "***User Certificate***\n");
		PEM_write_X509_AUX(fp, cert);
	}
	if (ca != NULL && sk_X509_num(ca) > 0) {
		fprintf(fp, "***Other Certificates***\n");
		for (i = 0; i < sk_X509_num(ca); i++)
			PEM_write_X509_AUX(fp, sk_X509_value(ca, i));
	}
	fclose(fp);

	ret = EXIT_SUCCESS;

err:
	OPENSSL_free(name);
	X509_free(cert);
	EVP_PKEY_free(pkey);
	sk_X509_pop_free(ca, X509_free);

	return ret;
}

the function PKCS12_parse is not running ok, how can I change the code?

**Comment by slontis** [comment]
Try doing the same thing as the -provider option does...
If you just use the default provider you dont need to do anything.. If you want legacy + default then you need to load then both at the top of your code..

```
OSSL_PROVIDER_load(NULL, "legacy");
OSSL_PROVIDER_load(NULL, "default");
```

**Comment by slontis** [comment]
You can also free them using OSSL_PROVIDER_unload

**Comment by slontis** [comment]
You may want to think about if there is some way to not use RC2 (or most things in the legacy provider).
The algorithms are in the 'legacy' provider for a reason.

**Comment by zcybeijing** [comment]
> Try doing the same thing as the -provider option does...
> If you just use the default provider you dont need to do anything.. If you want legacy + default then you need to load them both at the top of your code..
> 
> ```
> OSSL_PROVIDER_load(NULL, "legacy");
> OSSL_PROVIDER_load(NULL, "default");
> ```

Add these codes at the top of main() function ,and my problem is solved. Thanks.
