### ISSUE TITLE
EVP_PKEY KDF's do not work if the fips provider is in the default library context,

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#12225]
After running

```
make TESTS="test_evp" tests V=1
```
Run the evp_test using the fips module in the default library context.

```
export OPENSSL_CONF_INCLUDE=providers
export OPENSSL_MODULES=providers
OPENSSL_CONF=./test/fips.cnf ./test/evp_test/evppkey_kdf.txt
```

This fails when doing a internal fetch because the library context is NULL..

When setting the digest via pkey_kdf_ctrl_str() the call stack is
```
  EVP_KDF_set_ctx_params()
    kdf_tls1_prf_set_ctx_params()
      ossl_prov_macctx_load_from_params() 
         EVP_MAC_fetch(libctx = NULL, macname = “HMAC", properties = NULL);
```

-------------

If using the default provider it really only works due to the trickery related to the default library context..

i.e: the inner_fetch does calls like this...

```
static OSSL_METHOD_STORE *get_evp_method_store(OPENSSL_CTX *libctx)
{
    return openssl_ctx_get_data(libctx, OPENSSL_CTX_EVP_METHOD_STORE_INDEX,
                                &evp_method_store_method);
}
```
Which then calls openssl_ctx_get_concrete() which does special things if the libctx is NULL.

Should we be doing this trickery also if ONLY the fips module is loaded somehow?
Or do we really just not care about this scenario..

This type of pkey really goes pear shaped earlier on when it does the call to 
is_legacy_alg() when calling..
```
ctx = EVP_PKEY_CTX_new_id(kdf_nid, NULL);
```
Which basically tells it to ignore the fetch failure and continue on without a libctx being associated with the returned ctx. 
Should it fail early in the case of the default provider not being loaded??

**Comment by levitte** [comment]
Part of this trickery is that the FIPS module simply doesn't have a default library context, isn't it?

**Comment by slontis** [comment]
Yes.
I assume this is related to remaining  'inside' the fips module once you enter..

**Comment by levitte** [comment]
Well, wouldn't it be simpler to allow the FIPS module to actually have a default context?
(I'm well aware of the can of worms I started trampling into)

**Comment by slontis** [comment]
It sounds like it would be a good idea - @mattcaswell  probably had some good reasons for doing it this way?
Those worms might be over your head soon :).

**Comment by levitte** [comment]
The reason is that we're currently paranoid about the effects of RUN_ONCE in the FIPS module.  There are unanswered questions about when a data segment is created and when it's destroyed.  Does `dlopen()` create a new data segment for the some shared object, or will all "loaded instances" share the same, and how can we handle that.  Basically.

**Comment by mattcaswell** [comment]
This has nothing to do with the FIPS module not having a default libctx. Its a bug in `kdf_tls1_prf_reset` which resets a little too much. Fix coming up.

**Comment by levitte** [comment]
Ah!  Thanks for clearing that red herring

**Comment by mattcaswell** [comment]
Fix in #12229

**Comment by mattcaswell** [comment]
> If using the default provider it really only works due to the trickery related to the default library context..

We might want to consider running evp_test with the "null" provider in the default lib ctx. I've not done that as part of #12229 though.

**Comment by slontis** [comment]
For some apps running using the fips module in the default lib context may be the use case.

**Comment by mattcaswell** [comment]
> For some apps running using the fips module in the default lib context may be the use case.

If it works as a non-default libctx, its very unlikely not to work also in the default libctx I would imagine. It's normally when you have it in a non-default libctx that problems occur. It's probably not a bad idea to have at least some tests that do that though.

**Comment by slontis** [comment]
@mattcaswell 

pkey_kdf is the only one causing me problems now when swapping to using a lib context (with a null provider in the default)..

I am now stuck between 2 interfaces now for this kludgy pkey_kdf case..

Using EVP_PKEY_CTX_new_from_name(libctx, "TLS_PRF", NULL) it would just return an object that contains the libctx and name but does not set the meth OR run the meth_init.. So that is not good.

EVP_PKEY_CTX_new_id() will set the meth pointer, but will then not have a libctx set.. 
The meth->init will then fail because  pkey_kdf_init(EVP_PKEY_CTX *ctx) tries doing a kdf fetch (which will need to change to pass in the libctx).
So it looks like it needs a hybrid then sets the libctx for the new_id case. (sigh)

**Comment by mattcaswell** [comment]
> I am now stuck between 2 interfaces for this kludgy pkey_kdf case..

I do wonder whether we would be better off re-implementing the kdf/mac via pkey as full on provider implementations rather than going through the legacy bridges.
