### ISSUE TITLE
notBefore, notAfter timestamps sometimes off by one hour (DST/Daylight Saving Time issue?)

### ISSUE THREAD

**Issue by jab4** [openssl/openssl#12223]
Seen on current Debians/Ubuntus with `OpenSSL 1.0.1t  3 May 2016` and `OpenSSL 1.1.1c  28 May 2019`.

0) Assuming `dpkg-reconfigure tzdata` is configured properly.
1) Request a cert from Letsencrypt at exactly 0600 your local time, in my case _Europe/Berlin_. Alternatively, _know_ the exact timestamps of your test cert, ideally via third-parties (vendor, browser).
2) With the freshly issued certificate in place, run `true | openssl s_client -connect localhost:443 | openssl x509 -noout -dates -serial`

Actual Output (truncated): 
```
notBefore=Jun 14 03:00:59 2020 GMT
notAfter=Sep 12 03:00:59 2020 GMT
```

Expected Output:
```
notBefore=Jun 14 04:00:59 2020 GMT
notAfter=Sep 12 04:00:59 2020 GMT
```

Verified by (PHP's `strtotime` wraps C's):
```
$ php -r "print date('r', strtotime('Jun 14 04:00:59 2020 GMT')).PHP_EOL; "
Sun, 14 Jun 2020 06:00:59 +0200
```
Notice OpenSSL's difference by -1 hour. Related to DST?

Nonetheless, time zone names in general and specifically GMT are ambiguous. GMT can refer to both UTC (which intrinsically doesn't know or even care about DST) as well as Greenwich time, which could imply daylight savings for half of the year. And this is what actually happens in the above demonstration: GMT with DST, but apparently gotten wrong by OpenSSL.

Output could be non-ambiguous if it adhered to ISO 8601 and specified offsets. Thus:
Actually expected Output:
```
notBefore=2020-06-14T06:00:59+02:00
notAfter=2020-06-14T06:00:59+02:00
```

Implementing this may break some post-processing software relying on a home-grown datetime parser. However, C's `strtotime()` will happily welcome the new format with no extra work needed.

**Comment by dcooper16** [comment]
Hi @jab4,

I can not reproduce the problem you are having. If I use OpenSSL to generate a certificate, the notBefore time is set to the current time. A certificate I recently generated (at 8:01am EDT = 12:01+00:00) has:
```
Not Before: Jun 23 12:01:06 2020 GMT
Not After : Jun 24 12:01:06 2020 GMT
```
I also can not find anything to support the idea that GMT is ambiguous as you suggest. Both https://www.timeanddate.com/time/gmt-utc-time.html and https://www.worldtimeserver.com/learn/utc-vs-gmt/ say that neither GMT nor UTC are affected by daylight savings time. https://greenwichmeantime.com/time-zone/gmt-plus-0/ also seems to indicate that UTC and GMT are basically the same. https://greenwichmeantime.com/ notes that the UK switches from GMT to British Summer Time (BST) when daylight saving time is in effect, and that GMT is only used when daylight saving time is not in use.

So, I cannot see anything to justify a breaking change to the way that OpenSSL displays times.

I also tried the experiment you suggested. According to my browser the dates for the GitHub server's certificate are:
```
Not Before: 5/4/2020, 8:00:00 PM (Eastern Daylight Time)
Not After: 5/10/2022, 8:00:00 AM (Eastern Daylight Time)
```
OpenSSL shows the dates as:
```
notBefore=May  5 00:00:00 2020 GMT
notAfter=May 10 12:00:00 2022 GMT
```
Eastern Daylight Time is UTC - 04:00.

**Comment by jab4** [comment]
Hi @dcooper16,

Thanks for shedding light on this. Also, broadening my tests could have shown that:

> Let’s Encrypt certificates have a [“not before” time of 1 hour](https://community.letsencrypt.org/t/net-err-cert-date-invalid/81001/2) before the moment they were issued.  (And in fact expire 89 days and 23 hours after they were issued.)

Closing.
