### ISSUE TITLE
renegotiation callback function client_hello_cb

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#12239]
Scenes:
Any SSL renegotiation request sent by the SSL Client on the SSL connection will be rejected by the SSL Server and will send an Alert message to the SSL Client. The level of the message is Warning and the reason value is no_renegotiation(100). However, based on compatibility considerations, The server itself will not actively disconnect the current SSL connection because it refuses to renegotiate the request.
After receiving the Warning level renegotiation rejection message, the SSL Client can determine whether to continue to apply the current SSL connection or disconnect the current SSL connection according to its own configuration.

Set callback function:
````
SSL_CTX_set_client_hello_cb(ctx, reneg_manage_cb, NULL);
SSL_set_ex_data_ex(itor->first, SSL_EX_DATA_RESERVED1, &tmp_reneg_ctl)
int reneg_manage_cb(SSL *s, int *al, void *arg)
{
    char buf[1];
    int count =1;
	int *reneg_ctrl = NULL;
    int md_len = 0, peer_md_len = 0;
    md_len = SSL_get_finished(s, &buf[0], count);
    peer_md_len = SSL_get_peer_finished(s, &buf[0], count);
	reneg_ctrl = SSL_get_ex_data_ex(s, SSL_EX_DATA_RESERVED1); 
    /* Determine whether it is the first time, if it is the first time, return directly 1:sucess */
    if((0 == md_len) || (0 == peer_md_len)){//
        return 1;  
    } else{
        if(*reneg_ctrl == 1){//Allow Renegoration
           return 1;
        }
        else{
            *al = SSL_AD_NO_RENEGOTIATION;
            return 0;
        }

    }
}
````

problem:
When setting renegotiation occurs, `s->ctx->client_hello_cb` in the `tls_early_post_process_client_hello` interface will directly return failure, instead of rejecting and sending an alarm no_renegotiation(100)., how can I set it to achieve the desired effect?

**Comment by mattcaswell** [comment]
The callback has the following return values documented for it:

````
A callback that returns failure (0) will cause the
connection to terminate, and callbacks returning failure should indicate
what alert value is to be sent in the B<al> parameter.  A callback may
also return a negative value to suspend the handshake, and the handshake
function will return immediately.  L<SSL_get_error(3)> will return
SSL_ERROR_WANT_CLIENT_HELLO_CB to indicate that the handshake was suspended.
````

So, you are returning 0 in the "no renegotiation" case which aborts the connection as per the documentation.

Perhaps a better approach would be to simply set the option `SSL_OP_NO_RENEGOTIATION` via the function `SSL_set_options()`:

https://www.openssl.org/docs/man1.1.1/man3/SSL_set_options.html

Having set the option, return success (1), to continue the handshake normally. Because the option has been set this should then mean the reneg attempt is rejected automatically with the appropriate warning alert sent.

**Comment by Mengliuxx** [comment]
use the set the option SSL_OP_NO_RENEGOTIATION via the function SSL_set_options():
the ssl Will disconnect, but I only need the server to send an alarm to the client and the ssl connection will not be disconnected

**Comment by mattcaswell** [comment]
> use the set the option SSL_OP_NO_RENEGOTIATION via the function SSL_set_options():
the ssl Will disconnect, but I only need the server to send an alarm to the client and the ssl connection will not be disconnected

Err, no? That option should just send a warning alert back to the peer and continue.

**Comment by Mengliuxx** [comment]
However, when I set SSL_set_options(s, SSL_OP_NO_RENEGOTIATION) for SSL_read using the apps function of 1.1.1f, SSL is disconnected when the client initiates renegotiation. 

server:
gdb --args ./openssl s_server -tls1_2
GNU gdb (GDB; SUSE Linux Enterprise 12) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./openssl...done.
(gdb) b SSL_read
Breakpoint 1 at 0x482045: file ssl/ssl_lib.c, line 1770.
(gdb) r
Starting program: /home/lm/openssl/openssl-1..1.1f/openssl-OpenSSL_1_1_1f/apps/openssl s_server -tls1_2
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-49.16.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Using default temp DH parameters
ACCEPT
-----BEGIN SSL SESSION PARAMETERS-----
MFoCAQECAgMDBALAMAQABDC+OpDzHjBo2VCE3dj1w1R0+uaCO/UyotdNaJ2mMbw4
7vyvibNPTN3ZphXCcvJFWlGhBgIEXwPQd6IEAgIcIKQGBAQBAAAArQMCAQE=
-----END SSL SESSION PARAMETERS-----
Shared ciphers:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POL                         Y1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES                         128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES12                         8-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA
Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:R                         SA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+S                         HA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Supported Elliptic Curve Point Formats: uncompressed:ansiX962_compressed_prime:ansiX962_compressed_char2
Supported Elliptic Groups: X25519:P-256:X448:P-521:P-384
Shared Elliptic groups: X25519:P-256:X448:P-521:P-384
CIPHER is ECDHE-RSA-AES256-GCM-SHA384
Secure Renegotiation IS supported

Breakpoint 1, SSL_read (s=0xa04df0, buf=0xa00de0, num=16384) at ssl/ssl_lib.c:1770
1770        if (num < 0) {
(gdb) call SSL_set_options(s, 0x40000000U)
$1 = 1074921476
(gdb) c
Continuing.
Read BLOCK

Breakpoint 1, SSL_read (s=0xa04df0, buf=0xa00de0, num=16384) at ssl/ssl_lib.c:1770
1770        if (num < 0) {
(gdb) c
Continuing.
ERROR
140737353950976:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1544:SSL alert number 40
shutting down SSL
CONNECTION CLOSED

client:
./openssl s_client -tls1_2
CONNECTED(00000004)
depth=0 CN = server.example
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = server.example
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = server.example
   i:CN = Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDJTCCAg2gAwIBAgIBAjANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdSb290
IENBMCAXDTE2MDExNDIyMjk0NloYDzIxMTYwMTE1MjIyOTQ2WjAZMRcwFQYDVQQD
DA5zZXJ2ZXIuZXhhbXBsZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
ANVdYGrf/GHuSKqMEUhDpW22Ul2qmEmxYZI1sfw6BCUMbXn/tNXJ6VwcO+Crs7h9
o95tveDd11q/FEcRQl6mgtBhwX/dE0bmCYUHDvLU/Bpk0gqtIKsga5bwrczEGVNV
3AEdpLPvirRJU12KBRzx3OFEv8XX4ncZV1yXC3XuiENxD8pswbSyUKd3RmxYDxG/
8XYkWq45QrdRZynh0FUwbxfkkeqt+CjCQ2+iZKn7nZiSYkg+6w1PgkqK/z9y7pa1
rqHBmLrvfZB1bf9aUp6r9cB+0IdD24UHBw99OHr90dPuZR3T6jlqhzfuStPgDW71
cKzCvfFu85KVXqnwoWWVk40CAwEAAaN9MHswHQYDVR0OBBYEFMDnhL/oWSczELBS
T1FSLwbWwHrNMB8GA1UdIwQYMBaAFHB/Lq6DaFmYBCMqzes+F80k3QFJMAkGA1Ud
EwQCMAAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwGQYDVR0RBBIwEIIOc2VydmVyLmV4
YW1wbGUwDQYJKoZIhvcNAQELBQADggEBAHvTBEN1ig8RrsT716Ginv4gGNX0LzGI
RrZ1jO7lm5emuaPNYJpGw0iX5Zdo91qGNXPZaZ75X3S55pQTActq3OPEBOll2pyk
iyjz+Zp/v5cfRZLlBbFW5gv2R94eibYr4U3fSn4B0yPcl4xH/l/HzJhGDsSDW8qK
8VIJvmvsPwmL0JMCv+FR59F+NFYZdND/KCXet59WUpF9ICmFCoBEX3EyJXEPwhbi
X2sdPzJbCjx0HLli8e0HUKNttLQxCsBTRGo6iISLLamwN47mGDa9miBADwGSiz2q
YeeuLO02zToHhnQ6KbPXOrQAqcL1kngO4g+j/ru+4AZThFkdkGnltvk=
-----END CERTIFICATE-----
subject=CN = server.example

issuer=CN = Root CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1434 bytes and written 305 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 9DF8AAF3462DF5807BB13D92BB1E5BBC6D168FE7C3334437E83A0254D12A2F22
    Session-ID-ctx:
    Master-Key: BE3A90F31E3068D95084DDD8F5C35474FAE6823BF532A2D74D689DA631BC38EEFCAF89B34F4CDDD9A615C272F2455A51
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 5c c1 24 b7 2d 1e 15 5f-8a 64 3d 1b 27 9a 35 40   \.$.-.._.d=.'.5@
    0010 - 88 11 31 3b 5d e7 23 ad-3d 37 1b 90 76 71 3e 0b   ..1;].#.=7..vq>.
    0020 - 67 57 ec 44 1a 26 8d bd-97 5f 58 4c 06 b1 37 47   gW.D.&..._XL..7G
    0030 - 78 75 6f f9 0d 36 ee 1e-8a ed 9f bc f4 a4 2b 3c   xuo..6........+<
    0040 - 85 b9 90 25 17 5a 4c eb-98 81 f3 9d c9 6a 1c 65   ...%.ZL......j.e
    0050 - 44 1c 0d 85 99 5a 2e 38-9c 3f b7 9b 49 a2 e9 9e   D....Z.8.?..I...
    0060 - ad 1a a1 99 f1 5c e2 6b-d8 28 8c 0b cf 8b ee 4d   .....\.k.(.....M
    0070 - 77 12 43 9d 93 f8 83 72-88 32 87 1b 1b 97 34 4a   w.C....r.2....4J
    0080 - b8 bf cc 83 c8 b0 6d d1-30 a7 b9 be dd 00 38 05   ......m.0.....8.
    0090 - 33 40 f1 b2 15 ca 69 e0-5a 8b 36 02 36 80 81 35   3@....i.Z.6.6..5

    Start Time: 1594085495
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
R
RENEGOTIATING
139969167476480:error:14094153:SSL routines:ssl3_read_bytes:no renegotiation:ssl/record/rec_layer_s3.c:1561:

**Comment by kaduk** [comment]
> 139969167476480:error:14094153:SSL routines:ssl3_read_bytes:no renegotiation:ssl/record/rec_layer_s3.c:1561:

leads us to https://github.com/openssl/openssl/blob/OpenSSL_1_1_1g/ssl/record/rec_layer_s3.c#L1551-L1561 in which openssl treats the warning-level "no renegotiation" alert as a fatal error.  If you want the client to determine whether or not to continue, don't use openssl for the client (i.e., don't use `s_client` for your tests.

**Comment by Mengliuxx** [comment]
That means that clients that use OpenSSL are disconnected (not just s_client for testing).

**Comment by kaduk** [comment]
> That means that clients that use OpenSSL are disconnected (not just s_client for testing).

Yes.  Are you trying to make some additional point?
Note that this github issue starts with you espousing that this workflow (client tries to renegotiate, server rejects with warning alert, client decides whether or not to continue) is a good idea; I do not see anyone else having indicated agreement with that.  I had assumed that you were trying to match some existing workflow, which would correspondingly have existing clients that are expecting to do this.

**Comment by Mengliuxx** [comment]
No, I just wanted to make sure that I didn't get it wrong. Thank you.

**Comment by kaduk** [comment]
Thanks for clarifying.

I guess I should also note that warning (non-fatal) TLS alerts are pretty unreliable, with many implementations treating all alerts as fatal.  This led to the entire concept of "alert level" being removed from TLS 1.3, and all alerts other than "close_notify" are by definition error alerts for TLS 1.3.  So while it's reasonable to use warning alerts if you control all the implementations in use, in a broader Internet ecosystem they're so unreliable so as to be effectively useless.

**Comment by Mengliuxx** [comment]
You're welcome. Thank you for your help.

**Comment by Mengliuxx** [comment]
@kaduk if If the renegotiation fails, the server only sends an alarm. The client determines whether to disconnect from the server. 
How do I configure this scenario? Do you have any suggestions? Thank you, sir.

**Comment by kaduk** [comment]
> @kaduk if If the renegotiation fails, the server only sends an alarm. The client determines whether to disconnect from the server.
> How do I configure this scenario? Do you have any suggestions? Thank you, sir.

Sorry, I don't have any good suggestions here.  The server part is the default behavior of openssl, but I don't think there's a good way to make openssl do the client part, and I don't have a recommendation for what other TLS client implementation would be more amenable to it.

**Comment by Mengliuxx** [comment]
@kaduk @mattcaswell 

on openssl-1.1.1f:
man SSL_CTX_set_options
       SSL_OP_NO_RENEGOTIATION
           Disable all renegotiation in TLSv1.2 and earlier. Do not send HelloRequest messages, and ignore renegotiation requests via ClientHello.

After SSL_OP_NO_RENEGOTIATION is set on the server, only the renegotiation request from the client is ignored. However, during the test, it is found that the OpenSSL client and server are disconnected, 
So, is the man page not updated? Or is my method faulty? Can the test client be openssl? 
If my client uses OpenSSL, is there any other method to enable the server to ignore the renegotiation request from the client? SSL_CTX_set_client_hello_cb cannot be implemented.

**Comment by kaduk** [comment]
One could perhaps argue that the "ignore" is a documentation error, since we do send the warning-level "no_renegotiation" alert instead of completely ignoring the ClientHello.  However, RFC 5246 is arguably unclear on this matter, with the description for the "no_renegotiaton" alert saying that:

> Sent by the client in response to a hello request or by the server
      in response to a client hello after initial handshaking.  Either
      of these would normally lead to renegotiation; when that is not
      appropriate, the recipient should respond with this alert.

Renegotiation is not appropriate when it is disabled by configuration, ergo, the server should respond with the alert.

(There is more detailed discussion in RFC 5246 about the reverse case, where the client is ignoring a HelloRequest: "This message MAY be ignored by the client if it does not wish to renegotiate a a session, or the client may, if it wishes, respond with a no_renegotiation alert.")

On the whole, I'd be inclined to approve a documentation patch that clarifies our behavior here, but don't see much grounds for changing the actual behavior.

> If my client uses OpenSSL, is there any other method to enable the server to ignore the renegotiation request from the client?

I don't know of one, sorry.

I don't think the test client can be openssl, at least if the server is openssl.

**Comment by Mengliuxx** [comment]
@kaduk 
thanks much!
I just test use openssl. i shou use others.
,so the final behavior will be determined by the client.
