### ISSUE TITLE
openssl from 3.0.0-alpha3 breaks when reading from stdin

### ISSUE THREAD

**Issue by balducci** [openssl/openssl#12249]
hello

openssl from 3.0.0-alpha3 (but NOT from 3.0.0-alpha2) breaks when reading
from stdin with:

    ----8<----
    Could not open file or uri  for loading Certificate
    40D11D026C7F0000:error::system library:file_open:No such file or directory:crypto/store/loader_file.c:919:calling stat()
    Unable to load Certificate
    ---->8----

I have attached a simple test-case that you can use to reproduce the
problem

openssl built from source on linux:

    ----8<----
    install:260> uname -r
    5.7.5
    install:254> gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/opt/stow.d/versions/gcc-10.1.0/usr/lib64/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
    Target: x86_64-pc-linux-gnu
    Configured with: /home/balducci/tmp/install-us-d/gcc-9.3.0.d/gcc-10.1.0/configure --prefix=/opt/stow.d/versions/gcc-10.1.0/usr --libdir=/opt/stow.d/versions/gcc-10.1.0/usr/lib64 --libexecdir=/opt/stow.d/versions/gcc-10.1.0/usr/lib64 --enable-shared --disable-bootstrap --enable-languages=c,c++,objc,fortran --enable-multilib
    Thread model: posix
    Supported LTO compression algorithms: zlib zstd
    gcc version 10.1.0 (GCC) 
    ---->8----

thanks
ciao

[test-case.tar.gz](https://github.com/openssl/openssl/files/4820788/test-case.tar.gz)

**Comment by kaduk** [comment]
I believe this was fixed already by #11873 ; please confirm

**Comment by balducci** [comment]
> I believe this was fixed already by #11873 ; please confirm

confirmed
thanks

**Comment by mattcaswell** [comment]
Great - thanks. Closing.
