### ISSUE TITLE
Is aead avalible in command speed?

### ISSUE THREAD

**Issue by bowensd** [openssl/openssl#12269]
I read the manual about  command `speed -evp` ,it  displays that `If algo is an AEAD cipher, then you can pass <-aead> to benchmark a TLS-like sequence. `
I run `speed-aead aes-128-gcm `but failed,displays that it is an unkonwn aead algo.So how can I run an aead speed command?

**Comment by paulidale** [comment]
Try: `speed -aead -evp aes-128-gcm`

**Comment by bowensd** [comment]
Thanks !
