### ISSUE TITLE
Need help w.r.t dh-small-subgroup and dh-composite

### ISSUE THREAD

**Issue by pavangk** [openssl/openssl#12278]
We are using openssl-1.1.1d code base.
We need to block below websites(as clients).  -> dh-small-subgroup and dh-composite
 
https://dh-small-subgroup.badssl.com/
https://dh-composite.badssl.com/
 
note: SSL_OP_SINGLE_DH_USE is set on SSL_CTX exclusively. AFAIK, this is default behavior in 1.1.1d
 
Any pointers on code changes/api usage (in C)  to achieve the above behavior ?

**Comment by pavangk** [comment]
guys need some help on above query

**Comment by davidben** [comment]
Most browsers just disable the DHE ciphers altogether these days. They're rather problematic and not really worth saving, IMO. I think that is a more reasonable option than trying to do a couple primality tests on every DHE connection as a TLS client.
https://groups.google.com/a/chromium.org/g/blink-dev/c/AAdv838-koo/m/bJv17voIBAAJ

**Comment by pavangk** [comment]
Agree for deployment POV.
but we need to block these sites https://dh-small-subgroup.badssl.com/ and 
https://dh-composite.badssl.com/ as part of NSS labs testing.

any pointers on how to disable all together?

**Comment by davidben** [comment]
If you want to disable DHE ciphers, add `!DHE` to your cipher string.

**Comment by pavangk** [comment]
SSL_CTX_set_ciphersuites(xy, ALL:!DHE); << throws up error

**Comment by kaduk** [comment]
`SSL_CTX_set_ciphersuites()` is for the TLS 1.3 ciphersuites (which do not have any DHE at all, only ephemeral DH); you should be looking at `SSL_CTX_set_cipher_list()`

**Comment by pavangk** [comment]
thanks.
SSL_CTX_set_cipher_list worked for TLS1.2

**Comment by kroeckx** [comment]
You probably to use DEFAULT:!DHE
