### ISSUE TITLE
The aead algo performance 

### ISSUE THREAD

**Issue by bowensd** [openssl/openssl#12281]
Does the implemention of command line `speed -aead -evp algo`  equal  the implemention  of   processing  messages in record layer？In other words , is  the result of `speed -aead -evp algo `  equal to  the performance of aead algo used for processing data in record layer？

**Comment by bowensd** [comment]
If I want to shut down AES-NI in openssl，what should I do?

**Comment by paulidale** [comment]
Configure and build openssl with `no-asm` and AES-NI will be avoided.

The implementation of the speed command is testing the raw performance with no protocol overheads.  I'd expect there to be a correlation but not equality.

**Comment by bowensd** [comment]
Thanks for advice!
