### ISSUE TITLE
SSL_renegotiate:wrong ssl version:ssl/ssl_lib.c:2127

### ISSUE THREAD

**Issue by hdatma** [openssl/openssl#12294]
I am not sure how to read this. 

> openssl 1.1.1g
> dovecot  2.3.10.1

Both are compiled locally.

```
> openssl s_client -servername example.com -connect example.com:imaps
...
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
...
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ LOGINDISABLED AUTH=CRAM-MD5] server ready
R
RENEGOTIATING
2163851058936:error:1420410A:SSL routines:SSL_renegotiate:wrong ssl version:ssl/ssl_lib.c:2127:

```

Our IMAP is configured on port 993 only, so renegotiation is not required. The string "Secure Renegotiation IS NOT supported" says that openssl does not support secure renegotiation, but there is nothing in my ./Configure nor in configdata.pm to explicitly disable it. The end result is OK, but then again, how openssl ended up with that default is a mystery. The second question is why openssl terminates with an error, in tha above renego test. saying "wrong ssl version" when the ssl version is the only one there is on this system?

**Comment by kaduk** [comment]
You have negotiated TLS 1.3, which does not support renegotiation at all.
The "SSL version" here is the protocol version (i.e., TLS 1.3), not the software version.
Making a call to `SSL_renegotiate()` (which is what the 'R' does, here) is considered "user error" and generates this error.

One could perhaps argue that `s_client` should disable the call to `SSL_renegotiate()` when TLS 1.3 is used, but one could also that having 'R' always do the same thing is important, so it's not a clear-cut answer.

**Comment by davispuh** [comment]
How are we supposed to test services over TLS using openssl? I'm trying to test SMTP using submissions port 465 but I'm getting same error.
I also tried `-tls1_2` but it also failed.

```
$ openssl s_client -tls1_2 example.com:465
[...]
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Protocol: TLSv1.2
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
[...]
220 example.com ESMTP
EHLO test
250-example.com
250-PIPELINING
250-SIZE
250-ETRN
250-AUTH PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
MAIL FROM: <test@example.com>
250 2.1.0 Ok
RCPT TO: <test@example.com>
RENEGOTIATING
802B9D01F97D0000:error:0A000153:SSL routines:ssl3_read_bytes:no renegotiation:ssl/record/rec_layer_s3.c:925:
```

```
$ openssl s_client -tls1_3 example.com:465
[...]
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Protocol: TLSv1.3
Server public key is 2048 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
[...]
220 example.com ESMTP
EHLO test
250-example.com
250-PIPELINING
250-SIZE
250-ETRN
250-AUTH PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
MAIL FROM: <test@example.com>
250 2.1.0 Ok
RCPT TO: <test@example.com>
RENEGOTIATING
ERROR
807B9ADFC3770000:error:0A00010A:SSL routines:can_renegotiate:wrong ssl version:ssl/ssl_lib.c:2833:
```

There is also unanswered discussion https://github.com/openssl/openssl/discussions/25218 with same issue.

I'm using `OpenSSL 3.4.1 11 Feb 2025 (Library: OpenSSL 3.4.1 11 Feb 2025)`

**Comment by mattcaswell** [comment]
> How are we supposed to test services over TLS using openssl? I'm trying to test SMTP using submissions port 465 but I'm getting same error.

This would have been best raised as a new issue, rather than adding to the end of a long closed old one.

I've [responded](https://github.com/openssl/openssl/discussions/25218#discussioncomment-12712031) in the discussion you referenced above.
