### ISSUE TITLE
PKCS12_parse fails in openssl3

### ISSUE THREAD

**Issue by jeroen** [openssl/openssl#12297]
One of the unit tests in the R bindings parses a P12 file, which started failing in openssl3. Below is my example program. It requires this example p12 file: [wildcard-google.dk-chain.p12](https://github.com/jeroen/openssl/raw/master/tests/google.dk/wildcard-google.dk-chain.p12).

The code below works fine in openssl 1.0.2 and 1.1.1 however in 3 it gives:

```
C06DAD1701000000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:307:Default library context, Algorithm (RC2-40-CBC), Properties ()
```

The "fetch failed" error message is pretty cryptic (no pun) but I suppose this has to do with `RC2-40-CBC` getting deprecated maybe? However it seems like we can still parse the file with the command line.

```c
#include <stdio.h>
#include <openssl/crypto.h>
#include <openssl/pkcs12.h>
#include <openssl/err.h>


static void raise_error(){
  char buf[8192] = {0};
  BIO *bp = BIO_new(BIO_s_mem());
  ERR_print_errors(bp);
  int len = BIO_read(bp, buf, 8192);
  BIO_free(bp);
  printf("OpenSSL error: %.*s", len, buf);
}

static void bail(int success){
  if(!success){
    raise_error();
    exit(1);
  }
}

int main( int argc, const char* argv[] ){
  FILE *fp = fopen("wildcard-google.dk-chain.p12", "rb");
  if(!fp){
  	printf("Failed to open file");
  	exit(1);
  }
  PKCS12 *p12 = d2i_PKCS12_fp(fp, NULL);
  bail(!!fp);
  EVP_PKEY *pkey = NULL;
  X509 *cert = NULL;
  STACK_OF(X509) *ca = NULL;
  bail(PKCS12_parse(p12, "", &pkey, &cert, &ca));
  printf("Success!\n");
  exit(0);
}
```

**Comment by mattcaswell** [comment]
RC2 has been moved to the legacy provider in OpenSSL 3.0. If you want to use it you need to explicitly load the legacy provider:

````
OSSL_PROVIDER_load(NULL, "legacy");
````

**Comment by jeroen** [comment]
Thanks. Is this what the `openssl pkcs12 -info` command line does by default, then?

Still the error message here could be improved.

**Comment by paulidale** [comment]
I don't think the command line app does this by default.  It is likely being loaded via the OpenSSL configuration file.

To guarantee it: `openssl pkcs12 -info -provider legacy -provider default`.

The reason being that the _default_ provider will be loaded as a fall back if no other provider is loaded.  Once the _legacy_ provider is loaded, the _default_ won't be anymore -- things thus become load order dependent.  By specifying both on the command line, there is no problem.

**Comment by stone14z** [comment]
Found the solution.  Added 
OSSL_PROVIDER_load(NULL, "legacy");
before the call to pkcs12_parse.  Now it works.
