### ISSUE TITLE
do we have any plan to get NIST authentication for Openssl3.0.0?

### ISSUE THREAD

**Issue by chensqecc** [openssl/openssl#12301]
hi  Gentlemen
since Openssl 3.0.0.0 will release by the end of 2020. After Openssl3.0.0 release, do we have any plan to get NIST authentication？

**Comment by paulidale** [comment]
Yes.  See [this](https://www.openssl.org/blog/blog/2019/02/13/FIPS-update/) for example.

Applications that use FIPS are expected to need to make changes to support FIPS.
Processing time by NIST is long at the moment and getting longer.  We've no idea when the validation will be approved.
