### ISSUE TITLE
Are we implicitly recommending that it is fine to install OpenSSL from sources on a platform in which tests cannot be run?

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#12317]
This question has been raised by @romen: https://github.com/openssl/openssl/pull/12109#discussion_r444661133
regarding the following section of `NOTES.PERL` (which is about to be renamed to `NOTES-Perl.md`):

```
  * `Test::More`

    We require the minimum version to be 0.96, which
    appeared in Perl 5.13.4, because that version was
    the first to have all the features we're using.
    This module is required for testing only!
    If you don't plan on running the tests,
    you don't need to bother with this one.
```

**Comment by levitte** [comment]
There has never been anything that implies tests would be mandatory.  The user is perfectly free to install without testing.  We can, of course, *recommend* against it, but that's all.

It's perfectly possible and legitimate that the user has a test suite of their own.

**Comment by romen** [comment]
I think @levitte 's answer solves it.

Maybe as a resolution we could add a single sentence saying that we strongly recommend to validate any compilation of OpenSSL through a comprehensive test suite before production use.

**Comment by levitte** [comment]
> Maybe as a resolution we could add a single sentence saying that we strongly recommend to validate any compilation of OpenSSL through a comprehensive test suite before production use.

So far, we've seen that as self evident :wink:

**Comment by DDvO** [comment]
Thanks @levitte and @romen,
so I think this question has been sufficiently answered
and can be closed.
