### ISSUE TITLE
Out of bound access in ssl/statem/statem_clnt.c

### ISSUE THREAD

**Issue by qunying** [openssl/openssl#12319]
When psklen returned from L2901 is larger than PSK_MAX_PSK_LEN, it will trigger the goto in line 2908.

https://github.com/openssl/openssl/blob/31214258309251aff297da67a60a6b60bf4ef27e/ssl/statem/statem_clnt.c#L2901-L2909

Then in Line 2948, OPENSSL_cleanse is called with the over size, causing out of bound access.
https://github.com/openssl/openssl/blob/31214258309251aff297da67a60a6b60bf4ef27e/ssl/statem/statem_clnt.c#L2947-L2948

**Comment by kaduk** [comment]
This analysis seems valid (though it is an application bug to return a length larger than the `sizeof(psk)` value that is provided to it.  It would be simplest to clear the whole `psk` array, though "more correct" to clear the minimum of `psklen` and `sizeof(psk)`.

Are you interested in preparing a pull request to make such a change?

**Comment by nhorman** [comment]
Given that no pull request was submitted, I'm assuming there is no interest here

Marking as inactive to be closed at the end of 3.4 dev, barring further input

**Comment by kaduk** [comment]
I should be able to submit a PR; I didn't set a revisit timer for myself to check back in if the submitter didn't reply to my question.

**Comment by nhorman** [comment]
Thank you Kaduk!

**Comment by kaduk** [comment]
It looks like this was already fixed (slightly differently than my proposal) in 3de7f014a98.
