### ISSUE TITLE
libcrypto-1_1-x64.dll  does not meet GSCheck safe compilation options

### ISSUE THREAD

**Issue by HWliwenyong** [openssl/openssl#12315]
OpenSSL version:1.1.1g
Actual Behavior:

 libcrypto-1_1-x64.dll  does not meet GSCheck safe compilation options

**Comment by levitte** [comment]
Some of the code is in assembler, and don't contain the internal checks that the C compiler adds.

If you prefer having a pure C build, configure with `no-asm`.
