### ISSUE TITLE
Test 81-test_cmp_cli.t hangs on some platforms

### ISSUE THREAD

**Issue by jaimeebrown** [openssl/openssl#12324]
Test execution of `81-test_cmp_cli.t` on master branch does not complete on some platforms including: Solaris, AIX, z/Linux. 

Note that this also causes running of 'alltests' to get stuck and not complete on these platforms.

Execution stalled on Solaris11 x64 machine, does not complete. Stalls at:
```
$ SRCTOP=.. BLDTOP=. /usr/local/bin/perl ../test/run_tests.pl 81
81-test_cmp_cli.t .. 7/? 
```
Process still running `openssl cmp -config server.cnf`. Killing it manually causes test execution to complete.

In `81-test_cmp_cli.t`, cmd `lsof` is used to get pid in order to kill mock server. But lsof may not be available on all platforms.

**Comment by mattcaswell** [comment]
@DDvO

**Comment by DDvO** [comment]
Well, there is the known problem, originally discussed here: https://github.com/openssl/openssl/pull/11998/#issuecomment-641049350 that 

* using the shell ampersand `&` and `lsof` and `kill` is not really portable and
* the nice apparently platform-independent solution using the Perl module `Proc::Background` cannot be expected on all systems.

How if we simply disable these tests not only on Windows and VMS but on all non-Linux platforms?
In this case, how best to detect this situation with Perl?

**Comment by kaduk** [comment]
There are plenty of non-Linux Unix platforms out there (*BSD, macOS, etc.); it would be a shame to cripple the test suite for them without cause.

**Comment by DDvO** [comment]
@kaduk,

> There are plenty of non-Linux Unix platforms out there (*BSD, macOS, etc.);

I suppose the majority of users will be on Linux, but I agree it would be good to cover with all our tests as many other platforms as we can reasonably do. I already made sure that  `81-test_cmp_cli.t` works also with MacOS, for which we have CI configurations for trying it out. Yet I cannot experiment with *BSD, Solaris, and the like.

> it would be a shame to cripple the test suite for them...

The CMP lib/core tests run on any system. We are talking here only about the tests at CLI (`apps/openssl cmp`) level,
for which a CMP server is needed running in parallel to the client. 

> without cause.

As mentioned, there is at least some cause. I had tried hard finding a portable solution for spawning and later taking down a simple server process, and the best I could come up with is using the very nice `Proc::Background`. Yet this module does not seem present on many systems, and @mattcaswell did not support the idea of simply copying it in. Adapting and using the related solution in `util/perl/TLSProxy/Proxy.pm` appears pretty hard to do.

I had asked for help on this issue already in late May: https://github.com/openssl/openssl/pull/11998/#issuecomment-636374887, but so far nobody has come up with an adequate solution. 
Can you suggest one? 
Maybe there is at least a way of using here some shell tools that work across all flavors of Unix?

**Comment by DDvO** [comment]
I have not found a direct way of excluding the CLI-based high-level CMP tests on Solaris,
but I hope this issue is solved by #/12422 which skips them on systems that do not have a `kill` command.
@jaimeebrown, can you please try out and let us know if this works?

**Comment by jaimeebrown** [comment]
Yes, that change seems to skip the tests ok.

**Comment by DDvO** [comment]
Thanks @jaimeebrown for the confirmation.
