### ISSUE TITLE
Endianness is detected wrongly

### ISSUE THREAD

**Issue by Voker57** [openssl/openssl#12332]
Version: 5188d0d 

`perl configdata.pm --dump`: [config.txt](https://github.com/openssl/openssl/files/4854628/config.txt)

On a processor described in cpuinfo as `ARMv7 Processor rev 4 (v7l)`, Raspbian GNU/Linux 9, dpkg-architecture shows DEB_TARGET_ARCH_ENDIAN=little, yet configuration script defines B_ENDIAN.

Bug appeared somewhere around recent config rewrite, at some point after 4901b570ba13bad06a6418a636f6bdf98585a753

**Comment by levitte** [comment]
I need a little more info, could you run `uname -a` and tell me the result?

**Comment by levitte** [comment]
Never mind, I think I found it.  The following patch fixes it, right?

``` diff
diff --git a/util/perl/OpenSSL/config.pm b/util/perl/OpenSSL/config.pm
index 46dad98d08..51f8742475 100755
--- a/util/perl/OpenSSL/config.pm
+++ b/util/perl/OpenSSL/config.pm
@@ -621,7 +621,6 @@ EOF
       ],
       [ 'armv[1-3].*-.*-linux2',  { target => "linux-generic32" } ],
       [ 'armv[7-9].*-.*-linux2',  { target => "linux-armv4",
-                                    defines => [ 'B_ENDIAN' ],
                                     cflags => [ '-march=armv7-a' ],
                                     cxxflags => [ '-march=armv7-a' ] } ],
       [ 'arm.*-.*-linux2',        { target => "linux-armv4" } ],
```

**Comment by levitte** [comment]
The fix is in #12335

**Comment by bbbrumley** [comment]
Thanks @Voker57 for chasing it down and @levitte for the potential fix. I don't have access to our arm32 CI shell, but I reckon we'll be able to test it today

**Comment by Voker57** [comment]
Yes, the patch fixes it.
