### ISSUE TITLE
Can I  disable TLS ec_point_formats  extension?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12349]
Hi,
   I test openssl s_server and I find that openssl  sent ec_point_formats by default.  And there is a function to get  ec_point_formats values, but I didn't find any function to set it's value.
  Generally I want to disable it , 
  And I want to know 1) how to disable it,      2) is there any problem if I disable this extension?  

  Thanks in advance.

**Comment by mattcaswell** [comment]
> I test openssl s_server and I find that openssl sent ec_point_formats by default. And there is a function to get ec_point_formats values, but I didn't find any function to set it's value.
Generally I want to disable it ,
And I want to know 1) how to disable it, 2) is there any problem if I disable this extension?

That extension gets sent automatically if the client ends up offering any EC ciphersuites and the minimum supported TLS version is TLSv1.2 or below. The only way to disable it is to not offer EC ciphersuites,  or set a minimum TLS version of TLSv1.3 or above.

Obviously the impact of disabling it in the manner I describe is that you can't use EC in your connections which may have performance and interoperability impacts.

**Comment by joymcg** [comment]
Got it. thanks
