### ISSUE TITLE
ECDHE usage issues

### ISSUE THREAD

**Issue by lvzhao666** [openssl/openssl#12345]
Party B gives a data
0 x1d9bec7294e2a7426acff1c48e69d2dc995d471d3fe045b1bc3fa21298813fc8
0 x8d413fedaa2d0fd1036c27a3cc08e1776b951918513bbd5d8d22286ade63cfbc
How do I use ECDH_compute_key to compute a Shared password

**Comment by romen** [comment]
You should also know which curve they are using and you should have your own key pair on the same curve (maybe an ephemeral one just generated?).
When the other party sends their public key hopefully they do so using a standardized format, if they do there might already be functions in OpenSSL to decode their message into an EVP_PKEY object.

Once you have your EVP_PKEY object and their (public only) EVP_PKEY object, you can call EVP_PKEY_derive:

https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_derive.html

**Comment by romen** [comment]
Once you have derived a shared secret, depending on the protocol, you might want to mix it with other stuff to bound the "master secret" to the protocol run, and use some kdf construction to establish a key schedule to derive different good quality keys from this shared secret for different domains: e.g. if this is a two way scheme, you want to have a different key to do authenticated encryption of the messages from A to B, and a different one to be used for messages from B to A, and depending on the symmetric cipher selected, you also need to be able to rekey after a certain amount of data has been transferred, etc.

**Comment by lvzhao666** [comment]
I know the other side gave:
0 x36285438ee0f5e930a10ca20121c5c038f595d9dbb25fac78b555ef62654467c
0 x48663205ed0843ed9d7adb82223b51a5d459f258d6fb2d7480448e51d4be9f5c
Ec_group = EC_GROUP_new_by_curve_name (NID_secp256k1);
I want to get the Shared key by the function "ECDH_compute_key",

Char shareKey1 [256]
ECDH_compute_key(shareKey, 256, Pubkey, ec_Key, NULL);


Pubkey is the public key of the other party, how should I put:
0 x36285438ee0f5e930a10ca20121c5c038f595d9dbb25fac78b555ef62654467c
0 x48663205ed0843ed9d7adb82223b51a5d459f258d6fb2d7480448e51d4be9f5c
Convert to PubKey to calculate the Shared key.



Or:
Both sides specify the encryption curve: NID_secp256k1
Party A data:
0 x36285438ee0f5e930a10ca20121c5c038f595d9dbb25fac78b555ef62654467c
0 x48663205ed0843ed9d7adb82223b51a5d459f258d6fb2d7480448e51d4be9f5c
How do I get the Shared key.
Is there any Demo reference

**Comment by bbbrumley** [comment]
`ECDH_compute_key` is deprecated.

[Use the EVP interface](https://github.com/openssl/openssl/blob/0f6c3ebbf85b93ca78f6b5e5cead8f406fe70123/apps/speed.c#L3305).

**Comment by slontis** [comment]
I am not exactly sure why you are dealing directly with raw key data, but I will answer that question..

To create a public point you need to get a key in the form of
{
  0x04, //UNCOMRESSED
  X bytes, //NOTE: X or Y may be zero padded so that they are the same length
  Y bytes,
};

To do this in code you still need to use the EC_ API's to get the public key in this format...

```
EC_POINT_new()
EC_POINT_set_affine_coordinates(g, g2_gen, x, y, ctx);
EC_POINT_point2oct(g, pt, POINT_CONVERSION_UNCOMPRESSED, ...);
```
Refer to test/ectest.c which calls these functions..
....

For the openssl master branch:
You can then create a EVP_PKEY as shown in acvp_test.c ecdsa_create_pkey()
i.e (example without checking return values)

Note: you need to setup 2 EVP_PKEY's (one for the peer's public key and 1 for the host private key).
(You can do the same for the other side).

```
    bld = OSSL_PARAM_BLD_new();
    OSSL_PARAM_BLD_push_utf8_string(bld, OSSL_PKEY_PARAM_GROUP_NAME, curve_name, 0);
   /* The peer skey should only have the public key */
    OSSL_PARAM_BLD_push_octet_string(bld, OSSL_PKEY_PARAM_PUB_KEY, pub, pub_len);
    BN_bin2bn(priv, priv_len, priv_bn);
    /* The host needs the private key */
    OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_PRIV_KEY, priv_bn);
    params = OSSL_PARAM_BLD_to_param(bld);
    ctx = EVP_PKEY_CTX_new_from_name(libctx, "EC", NULL);
    EVP_PKEY_key_fromdata_init(ctx);
    EVP_PKEY_fromdata(ctx, pkey, params);

```

Then use https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_derive.html

**Comment by lvzhao666** [comment]
What Party A gives me is the original data:
0 x36285438ee0f5e930a10ca20121c5c038f595d9dbb25fac78b555ef62654467c
0 x48663205ed0843ed9d7adb82223b51a5d459f258d6fb2d7480448e51d4be9f5c
I need to generate it again, and then calculate the Shared secret key
How to use EVP_PKEY is not clear,
How do you assign the raw data x and y to EVP_PKEY, and then calculate it?

**Comment by bbbrumley** [comment]
> How do you assign the raw data x and y to EVP_PKEY, and then calculate it?

I think everyone is politely trying to tell you, if you have the "raw data x and y", you are already doing it wrong.

Where did x and y come from?

If you show some code, it would help.

**Comment by lvzhao666** [comment]
* About the ECDHE code block

```int testECDHE()
{
    EC_KEY *key1,*key2;
    const EC_POINT *pubkey1,*pubkey2;
    EC_GROUP *group1,*group2;
    unsigned int ret,nid,size,i,sig_len;
    unsigned char *signature,digest[20];
    BIO *berr;
    EC_builtin_curve *curves = NULL;
    char shareKey1[128],shareKey2[128];
    int len1,len2;
    /* 构造 EC_KEY 数据结构 */
    key1=EC_KEY_new();
    if(key1==NULL)
    {
        printf("EC_KEY_new err!\n");
        return -1;
    }
    key2=EC_KEY_new();
    if(key2==NULL)
    {
        printf("EC_KEY_new err!\n");
        return -1;
    }
    /* 选取一种椭圆曲线 */
    nid = NID_secp521r1;
    /* 根据选择的椭圆曲线生成密钥参数 group */
    group1 = EC_GROUP_new_by_curve_name(nid);
    if(group1==NULL)
    {
        printf("EC_GROUP_new_by_curve_name err!\n");
        return -1;
    }
    group2=EC_GROUP_new_by_curve_name(nid);
    if(group1==NULL)
    {
        printf("EC_GROUP_new_by_curve_name err!\n");
        return -1;
    }
    /* 设置密钥参数 */
    ret=EC_KEY_set_group(key1,group1);
    if(ret!=1)
    {
        printf("EC_KEY_set_group err.\n");
        return -1;
    }
    ret=EC_KEY_set_group(key2,group2);
    if(ret!=1)
    {
        printf("EC_KEY_set_group err.\n");
        return -1;
    }
    /* 生成密钥 */
    ret=EC_KEY_generate_key(key1);
    if(ret!=1)
    {
        printf("EC_KEY_generate_key err.\n");
        return -1;
    }
    ret=EC_KEY_generate_key(key2);
    if(ret!=1)
    {
        printf("EC_KEY_generate_key err.\n");
        return -1;
    }
    /* 检查密钥 */
    ret=EC_KEY_check_key(key1);
    if(ret!=1)
    {
        printf("check key err.\n");
        return -1;
    }
    /* 获取密钥大小 */
    size=ECDSA_size(key1);
    printf("size %d \n",size);
    for(i=0;i<20;i++)
        memset(&digest[i],i+1,1);
    signature= (unsigned char*)malloc(size);
    ERR_load_crypto_strings();
    berr=BIO_new(BIO_s_file());
    //BIO_set_fp(berr,stdout,BIO_NOCLOSE);
    /* 签名数据，本例未做摘要，可将 digest 中的数据看作是 sha1 摘要结果 */
    ret=ECDSA_sign(0,digest,20,signature,&sig_len,key1);
    if(ret!=1)
    {
        ERR_print_errors(berr);
        printf("sign err!\n");
        return -1;
    }
    /* 验证签名 */
    ret=ECDSA_verify(0,digest,20,signature,sig_len,key1);
    if(ret!=1)
    {
        ERR_print_errors(berr);
        printf("ECDSA_verify err!\n");
        return -1;
    }
    //#######################
    /* Get the other party's public key, not directly referenced
But the other party only gave me the following data: x and y. How do I calculate the Shared key
     x:AB5E1302CEB418AE64BB16D84415A2276219F3AE2F6CE80F6846C84B90738D76
     y:85C01F0FA6FBDE8BD5F7333DEE30D081EC56B2E2A351CD86C123D885A0E3E908
     */
    pubkey2 = EC_KEY_get0_public_key(key2);
    
    //#######################
    
    
    
    /* 生成一方的共享密钥 */
    len1= ECDH_compute_key(shareKey1, 128, pubkey2, key1, NULL);
    pubkey1 = EC_KEY_get0_public_key(key1);
    /* 生成另一方共享密钥 */
    len2= ECDH_compute_key(shareKey2, 128, pubkey1, key2, NULL);
    if(len1!=len2)
    {
        printf("err\n");
    }
    else
    {
        ret=memcmp(shareKey1,shareKey2,len1);
        if(ret==0)
            printf("生成共享密钥成功\n");
        else
            printf("生成共享密钥失败\n");
    }
    printf("test ok!\n");
    BIO_free(berr);
    EC_KEY_free(key1);
    EC_KEY_free(key2);
    free(signature);
    free(curves);
    return 0;
}
```

**Comment by bbbrumley** [comment]
If you want to do it that way, use `EC_POINT_hex2point`. Pass `POINT_CONVERSION_UNCOMPRESSED` and your hex string should look like `04(x coord hex)(y coord hex)`.

(You don't say what `x` and `y` are -- hex strings? BIGNUMs? bytes? So I am just guessing.)

**Comment by bbbrumley** [comment]
But those do not look like coordinates of a point on `NID_secp521r1` so I think you still have plenty of work to do on your code.

**Comment by lvzhao666** [comment]
Same curve NID_secp256k1
According to my understanding: I use my private key, with the public key of the other party, and then use this step :ECDH_compute_key to calculate the Shared secret key Len2 = ECDH_compute_key(shareKey2(result), 128, pubkey1(public key of the other party), EC_key, NULL);
But now the other side to give me the data is: 7 a896faebb3c39660f3f1d6f2e86fece7f2fec6e24aad421da5822e20ae5d112 a46bc1c8f10a20c2bb836c1589a93f55074f876020eb0ac2defd72e349ce4 19
I can't compute the Shared key directly. Or do you have a good method? thank you


Here's what I try to do:
```EC_KEY * key = NULL;
EC_POINT * pub_key;
Const EC_GROUP * group;

SSL_library_init ();
SSL_load_error_strings ();

Key = EC_KEY_new_by_curve_name (NID_secp256k1);
Group = EC_KEY_get0_group (key);
Pub_key = EC_POINT_new (group);


/ * *
Data from the other end
7a896faebb3c39660f3f1d6f2e86fece7f2fec6e24aad421da5822e20ae5d112
19a46bc1c8f10a20c2bb836c1589a93f55074f876020eb0ac2defd72e349ce4
* /

EC_POINT_hex2point (group,
"Seven a896faebb3c39660f3f1d6f2e86fece7f2fec6e24aad421da5822e20ae5d11219a46bc1c8f10a20c2bb836c1589a93f55074f876020eb0ac2defd72e349ce4 pub_key, NULL);

EC_KEY_set_public_key (key, pub_key);
BIGNUM * x = BN_new ();
BIGNUM * y = BN_new ();
If (EC_POINT_get_affine_coordinates_GFp(Group, pub_key, x, y, NULL)) {
Printf (" public key: \ n ");
BN_print_fp (stdout, x);
Putc (' \ n 'stdout);
BN_print_fp (stdout, y);
Putc (' \ n 'stdout);
}
```



It's not right, so can you help me figure out how to compute the ECDHE

**Comment by slontis** [comment]
I hope you have just mis-typed "Seven a89..."

If it is not right then either
- one of your inputs is wrong (e.g curve name, private key, public key, or secret_len)
OR the output has some KDF applied to it (which is the last parameter passed to ECDH_compute_key).

My suggestion to you is to randomly generate 2 key pairs that share the same curve (using the EVP interfaces) and get that case to work first, before trying some data that we dont know where it came from.

Just to reiterate one more time, using static (ECDH) keys is not a good idea..

**Comment by lvzhao666** [comment]
Initially, I use static public and private keys to complete the ECDHE algorithm and calculate the Shared secret key

Xiaoming's data:
public
BE78D884D2336EC54F385424174FCC535004E0EFA6CB2C1A96AAA90CB739CF42
15 eb5eaf998b3824913cfe2d1525e4a33c35594fb8aedb12a91300317ea65b88

My data:
public
3 d4353f3d993a930d96a9b0cad62d7a3df00c3ed69f0b3aaf2b0fd7fa6d18fda
F8C9F75165F98F169EF237719E7F6D8FC4877D41D28C5C83D55DEFD18B389CB2

Private
7 d6ea9ebc21606228243556f16d82ff5499213ea494d6391fe24bea24e86561b


How do you compute ECDHE?

**Comment by slontis** [comment]
The last E in ECDHE is the ephemeral bit..
Ephemeral keys are just temporary keys that are thrown away after use.

The normal process is:
2 parties agree on shared public parameters (for ECDH it is just the curve name).
Party1 generates a key pair using the public curve name and sends his public key to party2.
Party2 generates a key pair using the public curve name and sends his public key to party1.
Both parties use their own private key and the peers public key to derive the same shared secret.
Throw away the generated keys.. (If you keep them for next time they are static)

So you should be able to write some code that locally generates keys for both parties that does the above and see that you get the same shared secret for both sides.

That might also give you some ideas about what is wrong with your static data.

**Comment by lvzhao666** [comment]
I can now generate dynamic private and public keys
-- -- -- -- -- BEGIN PUBLIC KEY -- -- -- -- --
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAElzt7xG2QXU8gRwRvRW92fgfesQJB45TL
EULqb56Z5MnOYLMh3dixBXVUoyiqJejLdB0EdgVTHOmEkOiAo7gCtQ = =
-- -- -- -- -- END PUBLIC KEY -- -- -- -- --


-- -- -- -- -- BEGIN EC PRIVATE KEY -- -- -- -- --
MHQCAQEEICjiMAffK4wpzXiVCtMJEVxXOUr8Z5IOTAq/NZdodv5WoAcGBSuBBAAK
oUQDQgAElzt7xG2QXU8gRwRvRW92fgfesQJB45TLEULqb56Z5MnOYLMh3dixBXVU
OyiqJejLdB0EdgVTHOmEkOiAo7gCtQ = =
-- -- -- -- -- END EC PRIVATE KEY -- -- -- -- --

The other side gives me a different public key every time,
The format looks like this:
BE78D884D2336EC54F385424174FCC535004E0EFA6CB2C1A96AAA90CB739CF42
15 eb5eaf998b3824913cfe2d1525e4a33c35594fb8aedb12a91300317ea65b88
So how do I compute the Shared secret key.

**Comment by slontis** [comment]
Here is the EVP code..
NOTE: that the secret size is 32 bytes (which is dependent on the order of the curve).

```
static int test_shared_secret(void)
{
    int ret = 0;
    EVP_PKEY_CTX *gctx = NULL;
    EVP_PKEY_CTX *dctx1 = NULL, *dctx2 = NULL;
    EVP_PKEY *host_key = NULL, *peer_key = NULL;
    unsigned char secret1[128];
    size_t secret1_len = 0;
    unsigned char secret2[128];
    size_t secret2_len = 0;

    gctx = EVP_PKEY_CTX_new_from_name(NULL, "EC", NULL);
    if (gctx == NULL
        || EVP_PKEY_keygen_init(gctx) <= 0
        || EVP_PKEY_CTX_set_group_name(gctx, "prime256v1") <= 0
        || EVP_PKEY_keygen(gctx, &host_key) <= 0
        || EVP_PKEY_keygen(gctx, &peer_key) <= 0)
        goto err;

    dctx1 = EVP_PKEY_CTX_new_from_pkey(NULL, host_key, NULL);
    if (dctx1 == NULL
        || EVP_PKEY_derive_init(dctx1) <= 0
        || EVP_PKEY_derive_set_peer(dctx1, peer_key) <= 0
        || EVP_PKEY_derive(dctx1, secret1, &secret1_len) <= 0)
        goto err;
    dctx2 = EVP_PKEY_CTX_new_from_pkey(NULL, peer_key, NULL);
    if (dctx2 == NULL
        || EVP_PKEY_derive_init(dctx2) <= 0
        || EVP_PKEY_derive_set_peer(dctx2, host_key) <= 0
        || EVP_PKEY_derive(dctx2, secret2, &secret2_len) <= 0)
        goto err;

    ret = (secret1_len == secret2_len
              && memcmp(secret1, secret2, secret1_len) == 0);
err:
    OPENSSL_cleanse(secret1, secret1_len);
    OPENSSL_cleanse(secret2, secret2_len);
    EVP_PKEY_free(host_key);
    EVP_PKEY_free(peer_key);
    EVP_PKEY_CTX_free(dctx2);
    EVP_PKEY_CTX_free(dctx1);
    EVP_PKEY_CTX_free(gctx);
    return ret;
}

```

If you have more questions try debugging it to see what it does..

```
>./config -d
>make clean
>make
>gdb --tui --args mytest
```

**Comment by lvzhao666** [comment]
I still don't get it
How do I compute the Shared key if I have the data below it
-- BEGIN PUBLIC KEY --
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAElzt7xG2QXU8gRwRvRW92fgfesQJB45TL
EULqb56Z5MnOYLMh3dixBXVUoyiqJejLdB0EdgVTHOmEkOiAo7gCtQ = =
-- END PUBLIC KEY --

-- BEGIN EC PRIVATE KEY --
MHQCAQEEICjiMAffK4wpzXiVCtMJEVxXOUr8Z5IOTAq/NZdodv5WoAcGBSuBBAAK
oUQDQgAElzt7xG2QXU8gRwRvRW92fgfesQJB45TLEULqb56Z5MnOYLMh3dixBXVU
OyiqJejLdB0EdgVTHOmEkOiAo7gCtQ = =
-- END EC PRIVATE KEY --

The other public key,
BE78D884D2336EC54F385424174FCC535004E0EFA6CB2C1A96AAA90CB739CF42
15 eb5eaf998b3824913cfe2d1525e4a33c35594fb8aedb12a91300317ea65b88


How do you do that?

**Comment by slontis** [comment]
I am not going to continue to write detailed code for you :)

Look at the functions PEM_read_bio_PrivateKey() & PEM_read_bio_PUBKEY() to see how to load a static EVP_PKEY from a PEM file. If you are loading keys from files, you are back to using static keys again.

There is enough detail in all the answers above, for you to be able to figure out what you want to do.

**Comment by lvzhao666** [comment]
Thank you very much

**Comment by slontis** [comment]
Did you figure it out?

**Comment by lvzhao666** [comment]
YES, I know
```
    const char *public_key = publicKey.UTF8String;
    const char *private_key = privateKey.UTF8String; // 私钥
    EC_GROUP *group = EC_GROUP_new_by_curve_name(NID_secp256k1); // 椭圆曲线
    
    EC_POINT *pub_point = NULL;  // 公钥
    BIGNUM *pri_big_num = NULL; // 私钥
    EC_KEY *key = NULL;  // 密钥结构体
    NSString *ecdhStr = nil; // 协商出的密钥字符

    do {
        // 公钥转换为 EC_POINT
        pub_point = EC_POINT_new(group);
        EC_POINT_hex2point(group, public_key, pub_point, NULL);
        // 私钥转换为 BIGNUM 并存储在 EC_KEY 中
        if (!BN_hex2bn(&pri_big_num, private_key)) {
            break;
        }
        key = EC_KEY_new();
        if (!EC_KEY_set_group(key, group)) {
            break;
        }
        if (!EC_KEY_set_private_key(key, pri_big_num)) {
            break;
        }
        
        size_t outlen = 64;
        uint8_t *ecdh_text = (uint8_t *)OPENSSL_zalloc(outlen + 1);
        int ret = ECDH_compute_key(ecdh_text, outlen, pub_point, key, 0);
        if (ret <= 0) {
            break;
        }
        NSData *ecdhData = [NSData dataWithBytes:ecdh_text length:outlen];
        ecdhStr = [GMUtils dataToHex:ecdhData];
        
        OPENSSL_free(ecdh_text);
    } while (NO);
    
    if (group != NULL) EC_GROUP_free(group);
    EC_POINT_free(pub_point);
    BN_free(pri_big_num);
    EC_KEY_free(key);

```
