### ISSUE TITLE
why this function :OSSL_CMP_CTX_set1_server don't have impl? Is it missing or in  schedule?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12348]
@mattcaswell https://github.com/openssl/openssl/blob/168c595b14ff034ec40642ec1cb5d2c77ce82e0e/include/openssl/cmp.h#L277

**Comment by mattcaswell** [comment]
It does have an implementation. It is here:

https://github.com/openssl/openssl/blob/94941cada25433a7dca35b5b9f8cbb751ab65ab3/crypto/cmp/cmp_ctx.c#L785-L786
