### ISSUE TITLE
3.0.0-alpha4: Configurations name mismatch for solaris

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#12356]
File Configurations/10-main.conf refers to

shared_target    => "solaris-gcc"

but in file Configurations/shared-info.pl the entry is named "solaris-gcc-shared". When running the build, all settings from solaris-gcc-shared are not applied, eg. no symbolic linking is done and the SONAME of the created libs is mising the version suffix.

A naive fix of using "solaris-gcc-shared" instead of "solaris-gcc" in Configurations/10-main.conf leads to the next problem: in the generated Makefile the script mkdef.pl gets called with "--OS solaris-gcc", but mkdef.pl only knows about "solaris". So I added an alias line

"solaris-gcc" => "solaris"

to util/mkdef.pl.

It is possible, that other platforms will have similar problems. The following additional names occur in Configurations/10-main.conf as shared_target, without a definition in Configurations/shared-info.pl:

- aix
- self (irix-common, hpux-common)
- vms-shared
- win-shared

Regards,

Rainer

**Comment by levitte** [comment]
The `shared_target` serves two purposes:

-   Marker to show that we know how to produce shared libraries on this config target.
-   Optionally, the value *may* be a name found in `shared-info.pl`.  If it isn't there, the config target itself may have the necessary attributes (that's true for aix, self, vms-shared and  win-shared)

You're right, though, that solaris-gcc hasn't received the love it deserves.  Thank you for reporting this.

**Comment by levitte** [comment]
Fix in #12360

**Comment by rainerjung** [comment]
Great, looks good, thanks!
