### ISSUE TITLE
3.0.0-alpha4 81-test_cmp_cli.t on Solaris 10 and SLES 11 broken mock_server_pid() resulting in hang

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#12355]
test/recipes/81-test_cmp_cli.t uses "lsof" and "tail -n 1" in mock_server_pid(). On Solaris 10 Sparc and SLES 11 this leads to problems due to non-compliant or old versions of the tools:

Solaris 10 Sparc:

```
lsof: cannot open /dev/kmem
lsof: kvm_open(namelist=default, corefile=default): Permission denied

usage: tail [+/-[n][lbc][f]] [file]
       tail [+/-[n][l][r|f]] [file]
```

Solaris 10 does not support "tail -n NUMBER" but instead only "tail -NUMBER". Also lsof is very old and peculiar.

On SLES 11 it leads to lsof error messages, because it is too old:

```
lsof: unsupported TCP/TPI info selection: C
lsof: unsupported TCP/TPI info selection: P
lsof: unsupported TCP/TPI info selection: :
lsof: unsupported TCP/TPI info selection: L
lsof: unsupported TCP/TPI info selection: I
lsof: unsupported TCP/TPI info selection: S
lsof: unsupported TCP/TPI info selection: T
lsof: unsupported TCP/TPI info selection: E
lsof: unsupported TCP/TPI info selection: N
lsof 4.80
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhlnNoOPRstUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]]
 [-p s] [+|-r [t]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
```

Due to the tail/lsof errors, the pid can not get detected, which leads to a hanging test.

An alternative solution for mock_server_pid() on these platforms might use "pgrep -f" looking for the mock server process string. I don't have a final solution.

**Comment by sebastianas** [comment]
I see also a hang on Linux in a minimal build environment. I noticed that it the test needs `lsof' which I didn't have initially but even with it, it hangs at the end:

```
ok 7 - CMP app CLI Mock enrollment
# Can't exec "kill": No such file or directory at ../test/recipes/81-test_cmp_cli.t line 302.
```

**Comment by rainerjung** [comment]
I used the following patch as a workaround on both Solaris ("tail -n" problem plus old lsof) and also on SLES 11 (old lsof not supporting the args that the script uses). The patch has drawbacks, eg. when multiple test runs are done in parallel, but it can be used as a workaround for some people until a better solution is found:

--- test/recipes/81-test_cmp_cli.t.orig 2020-07-02 14:45:00.561724935 +0000
+++ test/recipes/81-test_cmp_cli.t      2020-07-03 00:33:11.519053884 +0000
@@ -207,10 +207,16 @@
         $server_name = chop_dblquot($server_name);
         load_config($server_name, $server_name);
         my $launch_mock = $server_name eq "Mock" && !$ENV{OPENSSL_CMP_CONFIG};
+        my $args = "";
+        my $proc = '';
         if ($launch_mock) {
             indir "Mock" => sub {
-                stop_mock_server(); # in case a previous run did not exit properly
-                start_mock_server("") || die "Cannot start CMP mock server";
+                $proc = bldtop_dir($app) . " -config server.cnf " . $args;
+                $proc =~ s/^\s+//;
+                $proc =~ s/\s+$//;
+                stop_mock_server($proc); # in case a previous run did not exit properly
+                start_mock_server($proc) || die "Cannot start CMP mock server";
+                sleep(2);
             }
         }
         foreach my $aspect (@all_aspects) {
@@ -222,7 +228,7 @@
                 test_cmp_cli_aspect($server_name, $aspect, $tests);
             };
         };
-        stop_mock_server() if $launch_mock;
+        stop_mock_server($proc) if $launch_mock && $proc ne '';
     };
 };
 
@@ -285,19 +291,22 @@
 }
 
 sub mock_server_pid {
-    return `lsof -iTCP:$localport -sTCP:LISTEN | tail -n 1 | awk '{ print \$2 }'`;
+    my $proc = shift;
+    my $pattern = '^' . $proc . '$';
+    return `pgrep -f '$pattern'`;
 }
 
 sub start_mock_server {
-    return 0 if mock_server_pid(); # already running
-    my $args = $_[0]; # optional further CLI arguments
+    my $proc = shift;
     my $dir = bldtop_dir("");
+    return 0 if mock_server_pid($proc); # already running
     return system("LD_LIBRARY_PATH=$dir DYLD_LIBRARY_PATH=$dir " .
-                  bldtop_dir($app) . " -config server.cnf " .
-                  "$args &") == 0; # start in background, check for success
+                  $proc .
+                  " &") == 0; # start in background, check for success
 }
 
 sub stop_mock_server {
-    my $pid = mock_server_pid();
+    my $proc = shift;
+    my $pid = mock_server_pid($proc);
     system("kill $pid") if $pid;
 }

**Comment by slontis** [comment]
@DDvO Could you disable this test until a viable solution is found?
This is causing many issues on quite a few platforms.

**Comment by slontis** [comment]
@paulidale

**Comment by DDvO** [comment]
Concerning Solaris, there is already a problem report: #12324 and a simple solution: #12422 that should be sufficient. I've handled the review comments a few hours ago, and I hope it will be approved soon.

**Comment by DDvO** [comment]
Concerning the problems with certain implementations of `lsof` and `tail`,
I've just extended #12422 with a commit avoiding `tail` and the `-s` option of `lsof`.

@rainerjung, does that PR solve the issues you reported?

**Comment by DDvO** [comment]
@rainerjung, as mentioned #12422 should solve the two problems you described here by removing the use of `tail` and the `sTCP:LISTEN` from the call of `lsof`.
I do not have those Solaris and SLES systems at hand to test this, so please confirm.

**Comment by rainerjung** [comment]
@DDvO I tried your patch, more precisely I added on top of master = 3.0.0-alpha5:

- 733a56959aefe483c4050bb70ac61ce77b4f27e2 (Skip test_cmp_cli if 'lsof' or 'kill' command is not available)
- 7e67db6c63ba22bc177acc280d2cd43b5758c179 (81-test_cmp_cli.t: Avoid using 'tail', 'awk', and the '-s' option of 'lsof')

These fix the problem of old version of lsof, like eg. on SuSE 11 and my self-build lsof on Solaris Sparc.

So it is definitly an improvment. For a full solution on Solaris Sparc one should note:

- lsof is not available by default. The latest version of test/recipes/81-test_cmp_cli.t should skip the test in that case. I did not test this.
 
- Oracle recommends using "netstat -u" instead of lsof. It was introduced only in Solaris 11.2 to show a list of processes associated with ports. I cannot test that.

- You test fixed the problem for me, because I have a self-build old lsof in place on Solaris. To make it work for a normal user I changed it to suid root.

Final minor nit: the following lines in test/recipes/81-test_cmp_cli.t have a mis-placed comment:

 37 plan skip_all => "Tests involving CMP server require 'kill' command"
 38     unless `which kill`; # this excludes Solaris
 39 plan skip_all => "Tests involving CMP server require 'lsof' command"
 40     unless `which lsof`;

The "Solaris" comment should be attached to the lsof check, not the kill check.

Thanks for your improvements.

**Comment by DDvO** [comment]
> These fix the problem of old version of lsof, like eg. on SuSE 11 and my self-build lsof on Solaris Sparc.
> 
> So it is definitly an improvment. 

Good to hear.

> For a full solution on Solaris Sparc one should note:
> 
>     * lsof is not available by default. The latest version of test/recipes/81-test_cmp_cli.t should skip the test in that case. I did not test this.

This point you do not need test; it's easy to convince oneself in other ways that this works.

>     * Oracle recommends using "netstat -u" instead of lsof. It was introduced only in Solaris 11.2 to show a list of processes associated with ports. I cannot test that.

Fine from my perspective since I do not want to add extra cases for certain versions of certain OSes.

>     * You test fixed the problem for me, because I have a self-build old lsof in place on Solaris. To make it work for a normal user I changed it to suid root.

I think this is fine. For users of vanilla Solaris `which lsof` will simply fail and thus the test will be skipped.

> Final minor nit: the following lines in test/recipes/81-test_cmp_cli.t have a mis-placed comment:
> 
> 37 plan skip_all => "Tests involving CMP server require 'kill' command"
> 38 unless `which kill`; # this excludes Solaris
> 39 plan skip_all => "Tests involving CMP server require 'lsof' command"
> 40 unless `which lsof`;
> 
> The "Solaris" comment should be attached to the lsof check, not the kill check.

Good point - I've adapted that commit.

> Thanks for your improvements.

Thanks also for your report and constructive comments and suggestions.

**Comment by DDvO** [comment]
Closing this since fix has been merged.
