### ISSUE TITLE
3.0.0-alpha4 test/recipes/81-test_cmp_cli.t compilation error

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#12353]
On RHEL6 and 7:

Not enough arguments for map at test/recipes/81-test_cmp_cli.t line 167, near "$params)"
Execution of test/recipes/81-test_cmp_cli.t aborted due to compilation errors.
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run

leading to

Test Summary Report
-------------------
81-test_cmp_cli.t                (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=203, Tests=2004, 496 wallclock secs ( 8.87 usr  0.95 sys + 420.50 cusr 59.24 csys = 489.56 CPU)
Result: FAIL

Possible fix (untested): change line 167:

<             my $invocation = ("$path_app ").join(' ', map quote_spc_empty @$params);
---
>             my $invocation = ("$path_app ").join(' ', map {quote_spc_empty} @$params);

Regards,
Rainer

**Comment by mattcaswell** [comment]
Does #12280 fix it for you?

**Comment by rainerjung** [comment]
Thanks for the pointer. Yes, looks good, I think one can close this issue then. Sorry that I didn't find the fix before opening the issue.
