### ISSUE TITLE
3.0.0-alpha4: man pages and html docs installed with perms 755

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#12350]
In file Configurations/unix-Makefile.tmpl there are the following lines, that result in installing man pages and html docs with permissions 755 instead of (suggested) 644:

                chmod 755 $(DESTDIR)$(MANDIR)/man1/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(MANDIR)/man3/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(MANDIR)/man5/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(MANDIR)/man7/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man1/$$fn; \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man3/$$fn; \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man5/$$fn; \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man7/$$fn; \

I suggest changing the 755 to 644.

Thanks and regards,

Rainer

**Comment by levitte** [comment]
Fixed in  #12373

**Comment by rainerjung** [comment]
Note that there are another 4 lines that need fixing for the HTML docs (look for "chmod" and "HTMLDIR"). Those are not yet part of #12373. Thanks.
