### ISSUE TITLE
3.0.0-alpha4 Platform specific error string test in errtest.c

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#12354]
File test/errtest.c tests against the string "Operation not permitted" for errno h, which is correct for Linux, but on Solaris 10 Sparc errno 1 gives "Not owner".

**Comment by levitte** [comment]
We have similar report in #12217 and #12276.  There's currently quite a bit being modified in the ERR sub-system, in #12343.  That includes fixing `test/errtest.c`.

**Comment by rainerjung** [comment]
Great. Using strerror(syserr) instead of the fixed string should work in my case too. Thanks for fixing this!
