### ISSUE TITLE
3.0.0-alpha4:  different compression level between distribution tarballs

### ISSUE THREAD

**Issue by HuKeping** [openssl/openssl#12364]
Happy to see we've already simplified the method for producing tarballs, but why we use different compression level to created it?

```
$ wget https://www.openssl.org/source/openssl-3.0.0-alpha4.tar.gz -O openssl-3.0.0-alpha4-release.tar.gz
$ wget https://github.com/openssl/openssl/archive/openssl-3.0.0-alpha4.tar.gz -O openssl-3.0.0-alpha4-github.tar.gz

$ file openssl-3.0.0-alpha4-github.tar.gz
openssl-3.0.0-alpha4-github.tar.gz: gzip compressed data, from Unix

$ file openssl-3.0.0-alpha4-release.tar.gz
openssl-3.0.0-alpha4-release.tar.gz: gzip compressed data, max compression, from Unix
```

It seems we use  `git archive -9 ` to create the distribution tarball on the official download page, and github automatically create the one from source tree with `git archive `.

To make  it consistent (official release page and github release page), would you mind if not using `level 9` to create the distribution tarball  on the official release page? It's almost the only difference between the two tgz.

**Comment by kroeckx** [comment]
I think that if you unpack the files from github, it will also
contain different files.

I wonder if we can either upload our file to github, or prevent
github from making such files.

**Comment by HuKeping** [comment]
> I think that if you unpack the files from github, it will also
contain different files.

Actually it's the same, the only difference between these two tarball is:
- compression level
- prefix, one is `openssl-openssl-3.0.0-alpha4`, the other is `openssl-3.0.0-alpha4`

```
$ mkdir openssl-3.0.0-alpha4-github openssl-3.0.0-alpha4-release
$ tar -zxf openssl-3.0.0-alpha4-github.tar.gz -C openssl-3.0.0-alpha4-github
$ tar -zxf openssl-3.0.0-alpha4-release.tar.gz -C openssl-3.0.0-alpha4-release
$ diff -r openssl-3.0.0-alpha4-github/openssl-openssl-3.0.0-alpha4 openssl-3.0.0-alpha4-release/openssl-3.0.0-alpha4
$
```

**Comment by kroeckx** [comment]
But the tarfiles aren't the same:
fc5584b92c70a5f7cd7cb8924f9cd30584f4c533e8af9765add0cfa76cd9f203 openssl-3.0.0-alpha4-github.tar
dbb5e8567f3747e335e6f2612e45d4ad0a30023306ec157a895ac28a86c87a6c openssl-3.0.0-alpha4-release.tar

**Comment by kroeckx** [comment]
So the release has openssl-3.0.0-alpha4 as directory, the github
one openssl-openssl-3.0.0-alpha4

**Comment by HuKeping** [comment]
> So the release has openssl-3.0.0-alpha4 as directory, the github
one openssl-openssl-3.0.0-alpha4

Correct, and you can make it the same if you try :
```
# tarball from release and md5sum
$ wget https://www.openssl.org/source/openssl-3.0.0-alpha4.tar.gz -O openssl-3.0.0-alpha4-release.tar.gz
$ md5sum openssl-3.0.0-alpha4-release.tar.gz
77b49cc5de23ef79a75a6d3aaa555b46  openssl-3.0.0-alpha4-release.tar.gz

# tarball from github and md5sum 
$ wget https://github.com/openssl/openssl/archive/openssl-3.0.0-alpha4.tar.gz -O openssl-3.0.0-alpha4-github.tar.gz
$ md5sum openssl-3.0.0-alpha4-github.tar.gz
cc82107365e76fec97a9d519b9c1f43d  openssl-3.0.0-alpha4-github.tar.gz


$ git clone https://github.com/openssl/openssl.git

# compare with tarball from github
$ git -C openssl archive -9 --prefix=openssl-3.0.0-alpha4/ -o ../openssl-3.0.0-alpha4-center.tar.gz openssl-3.0.0-alpha4
$ md5sum openssl-3.0.0-alpha4-center.tar.gz
77b49cc5de23ef79a75a6d3aaa555b46  openssl-3.0.0-alpha4-center.tar.gz

# comapre with tarball from release page
$ git -C openssl archive --prefix=openssl-openssl-3.0.0-alpha4/ -o ../openssl-openssl-3.0.0-alpha4-center.tar.gz openssl-3.0.0-alpha4
$ md5sum openssl-openssl-3.0.0-alpha4-center.tar.gz
cc82107365e76fec97a9d519b9c1f43d  openssl-openssl-3.0.0-alpha4-center.tar.gz
```

**Comment by levitte** [comment]
The github tarball *is not our distribution tarball*, do not take it as such.  Unfortunately, there seems to be no way to remove the releases section (many [have](https://stackoverflow.com/questions/28496319/github-a-tag-but-not-a-release) [asked](https://github.community/t/tag-without-release/857)), so there you go.

I'm not sure I understand why we should adapt our ways to whatever github does.  That would potentially have us spend unnecessary effort chasing down what they do (can anyone guarantee that they will never change their methods?), or suffer the occasional mismatch issue like this one.

If you want our distribution with our checksum, you download the tarball we produced and verify against our checksums.  It's that simple.

**Comment by HuKeping** [comment]
@levitte   Thanks for the link of those discussions , it helps a lot.

I'm definitely agreed with you that it is not reasonable to assume that GitHub will  (always) generated the distribution tarball as what we really wanted. The [mktar.sh scripts](https://github.com/openssl/openssl/blob/master/util/mktar.sh) we used is very explicit about how these distributions are created, and it works great.

But since we have everything versioned with git and use the tool(`git archive`) that comes with it, I think there is still one thing we could make a approve. See main part of the `mktar.sh` scripts :
```
 33  # This counts on .gitattributes to specify what files should be ignored
 34  git archive --worktree-attributes --format=tar --prefix="$NAME/" -v HEAD \
 35      | gzip -9 > "$TARFILE.gz"
 36 
```
Because the format will inferred from the output file and  attributes are by default taken from the `.gitattributes` files in the tree that is being archived. We can make it more simple :
```
  git archive --prefix="$NAME/"  -o $TARFILE.tar.gz HEAD
```

As this if we would like to to provide zip file in the further,  we can just change it as:
```
  git archive --prefix="$NAME/"  -o $TARFILE.zip HEAD
```

If the `$TARFILE` already contains the suffix, we can make it more general:
```
  git archive --prefix="$NAME/"  -o $TARFILE HEAD
```

If you think it's worth doing this, I can make a PR.

**Comment by levitte** [comment]
We'd like to keep `-9`, and I just saw that `git archive` supports it.  Otherwise, sure, I have nothing against things getting simpler.

Is there a reason why not `--worktree-attributes`

**Comment by HuKeping** [comment]
@levitte  As per the manual of git archive,  attributes are by default taken from the .gitattributes files in the tree that is being archived.

But with option `--worktree-attributes`  enabled, `git archive` will use the attribute file in the current workspace instead of using the one in the source tree, eg:
```
# make a temp attribute file
$ echo "NEWS.md  export-ignore" >> .gitattributes

# without --worktree-attributes
$ git archive -o old.tar.gz openssl-3.0.0-alpha4

# with --worktree-attributes
$ git archive -o new.tar.gz --worktree-attributes openssl-3.0.0-alpha4

# you will find the NEWS.md was removed in new.tar.gz
$ vimdiff    old.tar.gz    new.tar.gz
```

With this option, it will be more likely to make a wrong tarball especially when you are not on the right tree (git archive 3.0 but you're on 2.0, 1.0, master branch , etc).
