### ISSUE TITLE
does openssl support DHE in TLS1.3?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12376]
Hi,
   I found that in TLS1.3, there is a support_groups extension which used for key exchange, but I only find EC algorithms in it.
  Does openssl support DHE in TLS1.3? If it does, how to set it?  I found  SSL_CTX_set_tmp_dh(ctx,dh) doesn't work in TLS1.3

**Comment by mattcaswell** [comment]
This will be supported in the forthcoming OpenSSL 3.0 (currently in alpha testing), but is not in 1.1.1

**Comment by joymcg** [comment]
> This will be supported in the forthcoming OpenSSL 3.0 (currently in alpha testing), but is not in 1.1.1

thanks for the reply
