### ISSUE TITLE
poor backward compatibility of OCSP_parse_url()

### ISSUE THREAD

**Issue by petere** [openssl/openssl#12386]
(as of 3a19f1a9dd16f5855a7e2a42cd3e7f136f849bd3)

We have in `include/openssl/ocsp.h`

```c
#  define OCSP_parse_url OSSL_HTTP_parse_url /* for backward compatibility */
```

But `OSSL_HTTP_parse_url` requires including `<openssl/http.h>`, which is new in 3.0.0. So code can't really use `OCSP_parse_url` in a backward-compatible way without additional `#ifdef`s.

A simple fix might be to include `openssl/http.h` from `openssl/ocsp.h`.

**Comment by levitte** [comment]
@DDvO, I believe this is one for you :wink:

**Comment by DDvO** [comment]
> @DDvO, I believe this is one for you wink

Yep. I was away for the last two days, but just done this in #12399.

Thanks @petere for the report and suggestion how to fix this.
