### ISSUE TITLE
[3.0.0] EVP_PKEY_CTX_set_rsa_keygen_bits issue with EVP_PKEY_RSA_PSS

### ISSUE THREAD

**Issue by danbev** [openssl/openssl#12384]
While working on upgrading Node.js to use OpenSSL 3.0.0 alpha 4 I've run into an issue when calling `EVP_PKEY_CTX_set_rsa_keygen_bits` in combination with an id of `EVP_PKEY_RSA_PSS`. 

I've extracted the code used in Node.js into [rsa-pss](https://github.com/danbev/learning-libcrypto/blob/master/rsa_pss.c), and the section in question looks like this:
```c
  int modulus_bits = 512;                                                       
  const uint32_t exponent = 0x10001;                                            
  int salt_len = 16;                                                            
  const char* md_name = "sha256";                                               
  const EVP_MD* md = EVP_get_digestbyname(md_name);                             
  const char* mgf1_name = "sha256";                                             
  const EVP_MD* mgf1_md = EVP_get_digestbyname(mgf1_name);                      
                                                                                
  EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA_PSS, NULL);              
  if (ctx == NULL) {                                                            
    error_and_exit("Could not create a context for RSA_PSS");                   
  }                                                                             
                                                                                
  if (EVP_PKEY_keygen_init(ctx) <= 0) {                                         
    error_and_exit("Could not initialize the RSA context");                     
  }                                                                             
                                                                                
  if (EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, modulus_bits) <= 0) {               
    error_and_exit("EVP_PKEY_CTX_set_rsa_keygen_bits failed");                  
  }                        
```
The output of running the `rsa-pss` is:
```console
$ ./rsa_pss 
RSA_PSS example
EVP_PKEY_CTX_set_rsa_keygen_bits failed
errno: 0, error:00000000:lib(0)::reason(0)
```
In `EVP_PKEY_CTX_set_rsa_keygen_bits`  there is a check to see if  the `pkey_id` is `EVP_PKEY_RSA` which is not the case in our situation as it is `EVP_PKEY_RSA_PSS`, and this is causing `-1` to be returned:
https://github.com/openssl/openssl/blob/8c330e1939d6b7db93a963116354ef80ca0babb3/crypto/rsa/rsa_lib.c#L1331-L1332

It looks like in `1.1.1`  there was a that check for both ids:
 https://github.com/openssl/openssl/blob/e2e09d9fba1187f8d6aafaa34d4172f56f1ffb72/crypto/rsa/rsa_lib.c#L485-L493

I'm wondering if we should be doing something different for OpenSSL 3.0.0 since this check was removed, or if perhaps this is something that was just overlooked?

**Comment by mattcaswell** [comment]
> I'm wondering if we should be doing something different for OpenSSL 3.0.0 since this check was removed, or if perhaps this is something that was just overlooked?

The check wasn't removed. It still exists in `RSA_pkey_ctx_ctrl`in 3.0. The difference is that in 3.0 `EVP_PKEY_CTX_set_rsa_keygen_bits` is no longer a macro, but has been replaced with a function. That function is deciding whether to go down the legacy path (which eventually calls `RSA_pkey_ctx_ctrl`), or whether to go down the new provider based codepath. So, this does looks like a bug to me. `EVP_PKEY_CTX_set_rsa_keygen_bits` should be able to cope with both types of RSA key.

It *might* be as simple as modifying the check in `EVP_PKEY_CTX_set_rsa_keygen_bits` to additionally take account off `EVP_PKEY_RSA_PSS`. However, I'm slightly surprised though that our internal tests don't already call this for an RSA-PSS key - so if nothing else this indicates a missing test. Possibly there is also something missing on the provider side generation.

@levitte - do you have a view?

**Comment by levitte** [comment]
Your analysis seems correct, `EVP_PKEY_CTX_set_rsa_keygen_bits()` should recognise `EVP_PKEY_RSA_PSS` as well.

As for tests, I thought there were quite a bit of the with evp_test, but maybe I missed something...
.... and found that we have very little testing of RSA-PSS key generation, only here:

https://github.com/openssl/openssl/blob/eae4a008341149783b540198470f04f85b22730e/test/recipes/30-test_evp_data/evppkey.txt#L18591-L18596

I also just found that we have very little testing of plain RSA key generation as well:

https://github.com/openssl/openssl/blob/eae4a008341149783b540198470f04f85b22730e/test/recipes/30-test_evp_data/evppkey.txt#L18584-L18589
