### ISSUE TITLE
Can I interfere in the generation of CMP requests when using the OSSL_CMP_exec_IR_ses API?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12395]
@DDvO
https://github.com/openssl/openssl/blob/eae4a008341149783b540198470f04f85b22730e/include/openssl/cmp.h#L420
this api do the entire cmp req process ,how can i set my own encoded  crmf to the cmp message?that's mean :can i Interfering in the generation of CMP messages ?

**Comment by stardrift1** [comment]
I just fund i can use OSSL_CRMF_MSG_new->OSSL_CRMF_CERTTEMPLATE_fill->OSSL_CRMF_MSG_create_popo to creat a CRMF MSG but i can't inset it to the CMP MSG when i call OSSL_CMP_exec_IR_ses or any other API such as OSSL_CMP_exec_CR_ses ..

**Comment by stardrift1** [comment]
this issue maybe Related ：https://github.com/openssl/openssl/issues/12403#issue-654066296

**Comment by DDvO** [comment]
Indeed so far it was not possible to provide a custom CRMF structure to the CMP cert request API functions.
I've just fixed this, along with a related API generalization and simplification, in #12431.

**Comment by yangyangtiantianlonglong** [comment]
@DDvO   When will the modification be merged into OpenSSL-3.0.0?

**Comment by stardrift1** [comment]
@DDvO how a about the schedule of this request can be pull to openssl 3.0 master?
