### ISSUE TITLE
Re-initialising an EVP_CIPHER_CTX does not work as expected 

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12405]
With AES-128-CTR (and quite possibly other ciphers, but I didn't test it), re-initialising the EVP_CIPHER_CTX does not give the results we would expect. Consider this reproducer:

````
#include <openssl/evp.h>
#include <stdio.h>

int main(void)
{
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    unsigned char out[4];
    unsigned char in[4] = {
        0x0f, 0x0e, 0x0d, 0x0c
    };
    unsigned char key1[16] = {
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
        0x0c, 0x0d, 0x0e, 0x0f
    };
    unsigned char iv[16] = {
        0x0f, 0x0e, 0x0d, 0x0c, 0x0b, 0x0a, 0x09, 0x08, 0x07, 0x06, 0x05, 0x04,
        0x03, 0x02, 0x01, 0x00
    };
    int ret = 1, outl = 0;
    size_t i;

    if (!EVP_EncryptInit_ex(ctx, EVP_aes_128_ctr(), NULL, key1, iv))
        goto err;

    if (!EVP_EncryptUpdate(ctx, out, &outl, in, sizeof(in)))
        goto err;

    if (outl != 4)
        goto err;
    outl = 0;

    printf("First data block is:\n");
    for (i = 0; i < sizeof(out); i++)
        printf("%02X ", out[i]);
    printf("\n");

    if (!EVP_EncryptInit_ex(ctx, NULL, NULL, key1, iv))
        goto err;

    if (!EVP_EncryptUpdate(ctx, out, &outl, in, sizeof(in)))
        goto err;

    if (outl != 4)
        goto err;

    printf("Second data block is:\n");
    for (i = 0; i < sizeof(out); i++)
        printf("%02X ", out[i]);
    printf("\n");

    ret = 0;
 err:
    if (ret)
        printf("Error\n");
    else
        printf("Success\n");
    return ret;
}
````

When I run this code against 1.1.1 I get this output:

````
First data block is:
2F A7 F4 9E 
Second data block is:
2F A7 F4 9E 
Success
````
This is as expected. We have reset the key and IV and run the same encryption again. Therefore we would expect to see the same output. When I run this against master I get this:

````
First data block is:
2F A7 F4 9E 
Second data block is:
BB 42 56 E4 
Success
````
So the same encryption with the same key and IV gives different results in the re-initialised case.

**Comment by mattcaswell** [comment]
I think this is the underlying cause of #12377 (RNG fork-safety regression). We are re-seeding the RNG after a fork, but the new key/IV for the EVP_CIPHER_CTX we have put in place have not taken effect.

**Comment by mattcaswell** [comment]
Given that I'm away on holiday from tomorrow, I think its unlikely I'm going to be able to take the analysis much further before I go.

@slontis - any chance you can take a look?

**Comment by p-steuer** [comment]
@mattcaswell , see my comment https://github.com/openssl/openssl/issues/12377#issuecomment-656207334

**Comment by nmathewson** [comment]
Are there currently a set of tests that are run on every cipher provider?  If so, there should be a test to prevent other providers from making this mistake.  If not, it would be a good thing to add a set of tests that every provider needs to pass. (Commenting as reporter of #12377)

**Comment by mattcaswell** [comment]
> Are there currently a set of tests that are run on every cipher provider?

We have evp_test which runs a subset of its tests for all providers. @slontis is currently re-working it (#12236) to expand its coverage.

**Comment by slontis** [comment]
> Given that I'm away on holiday from tomorrow, I think its unlikely I'm going to be able to take the analysis much further before I go.
> 
> @slontis - any chance you can take a look?

Will do..

**Comment by slontis** [comment]
With your code it took about 5 minutes to find the culprit..
the ctx->num field is initially 0 and gets increased by 4 in the update..
If I reset this back to zero on the second update it gives the correct result.
I will have to see where this gets reset in 111.

**Comment by slontis** [comment]
I have put the fix for the cipher reinit issue into https://github.com/openssl/openssl/pull/12413.
@mspncp can you try this out?
(It doesnt have a integrated test yet - but it should be enough to see if this fixes the fork issue).

**Comment by mspncp** [comment]
> @mspncp can you try this out?

I tried it locally and it works. Created #12414 for a CI test.

**Comment by guidovranken** [comment]
@slontis 
I noticed this bug, and I am working on adding detection of it to my fuzzer.

Is the rule that an ```EVP_CIPHER_CTX``` can be fully re-initialized at any point by calling ```EVP_EncryptInit_ex``` again with the second parameter set to NULL (to retain the initial cipher), like in Matts example?

I found this and several other potential bugs after implementing this logic in my fuzzer:

```c
#include <openssl/evp.h>
#include <stdio.h>

int main(void)
{
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    unsigned char out[1024];
    unsigned char in[] = {0x00, 0xba, 0x6c, 0xd1, 0x93, 0x01, 0x50, 0x8d, 0xd2, 0x9a, 0x63, 0xe2, 0x56, 0x6a, 0x8c, 0x30,
 0x00, 0x00, 0x01, 0x16, 0x89, 0x29, 0xb7, 0xb0, 0x08, 0x5b, 0xf3, 0x30, 0x40, 0xaf, 0x41, 0x23,
 0x33, 0x00, 0x00, 0x33, 0x8d, 0xc5, 0x6b, 0x06, 0x67, 0x65, 0x1c, 0x40, 0xb0, 0x2f, 0xb6, 0xcc,
 0x47, 0xac, 0x48, 0x9e, 0xa3, 0xe2, 0x9c, 0xab, 0xbf, 0x97, 0x11, 0x29, 0xb7, 0x29, 0x89, 0x16,
 0xef, 0x00, 0x00, 0xaa, 0x05, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x17, 0x7e,
 0x53, 0x96, 0xd4, 0xd0, 0x27, 0x13, 0x4e, 0xa2, 0x56, 0x1b, 0xce, 0x00, 0xff, 0x03, 0xb1, 0x8f,
 0x08, 0x00, 0x00, 0x00, 0x0a, 0x7a, 0x36, 0x68, 0x21, 0xa0, 0xfd, 0x27, 0xce, 0xff, 0x0b, 0xb7,
 0x70, 0xfe, 0x91, 0xf0, 0x91, 0x9f, 0x1a, 0x35, 0xb2, 0x1d, 0xed, 0x24, 0x64, 0x00, 0x00, 0x00,
 0x00, 0x02, 0xc9, 0xe5, 0x83, 0x9a, 0x3e, 0x9c, 0xd4, 0x00, 0x00, 0x16, 0x00};
    unsigned char key1[16] = { 0 };
    unsigned char iv[8] = { 0 };
    int ret = 1, outl = 0;
    size_t i;

    if (!EVP_EncryptInit_ex(ctx, EVP_des_ede(), NULL, key1, iv))
        goto err;

    if (!EVP_EncryptUpdate(ctx, out, &outl, in, sizeof(in)))
        goto err;

    printf("First data block is:\n");
    for (i = 0; i < outl; i++)
        printf("%02X ", out[i]);
    printf("\n");

    outl = 0;
    if (!EVP_EncryptInit_ex(ctx, NULL, NULL, key1, iv))
        goto err;

    if (!EVP_EncryptUpdate(ctx, out, &outl, in, sizeof(in)))
        goto err;

    printf("Second data block is:\n");
    for (i = 0; i < outl; i++)
        printf("%02X ", out[i]);
    printf("\n");

    ret = 0;
 err:
    if (ret)
        printf("Error\n");
    else
        printf("Success\n");
    return ret;
}
```

This prints two different outputs. Am I doing something wrong or is this a legit bug?

To be clear this behavior is observed from the very latest checkout, so with https://github.com/openssl/openssl/commit/90409da6a520812b0266fcb1303175406dea81fe integrated.

**Comment by slontis** [comment]
For most ciphers this is true,
If it calls des_generatekey() then it will use a different random each time. which means the update will return a different value. You would have to figure out if it calls this function.

**Comment by guidovranken** [comment]
Ok, thanks.

How about this?

```c
#include <openssl/evp.h>
#include <stdio.h>

int main(void)
{
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    unsigned char out[1024];
    unsigned char in[8] = { 0 };
    unsigned char key1[24] = { 0 };
    unsigned char iv[16] = { 0 };
    int ret = 1, outl = 0;
    size_t i;

    if (!EVP_EncryptInit_ex(ctx, EVP_aes_192_cbc(), NULL, key1, iv))
        goto err;

    if (!EVP_EncryptUpdate(ctx, out, &outl, in, sizeof(in)))
        goto err;

    printf("First data block is:\n");
    for (i = 0; i < outl; i++)
        printf("%02X ", out[i]);
    printf("\n");

    outl = 0;
    if (!EVP_EncryptInit_ex(ctx, NULL, NULL, key1, iv))
        goto err;

    if (!EVP_EncryptUpdate(ctx, out, &outl, in, sizeof(in)))
        goto err;

    printf("Second data block is:\n");
    for (i = 0; i < outl; i++)
        printf("%02X ", out[i]);
    printf("\n");

    ret = 0;
 err:
    if (ret)
        printf("Error\n");
    else
        printf("Success\n");
    return ret;
}
```

Looks like it retains the input count across both calls, and outputs the block on the second call, once a total of 16 bytes have been consumed. Is this a bug or expected behavior?

**Comment by guidovranken** [comment]
FWIW, unlike OpenSSL, BoringSSL creates the same output (which is 0 bytes) on both calls, which is the expected result if we expect the internal cipher state to be reset upon the second call to `EVP_EncryptInit_ex`.

**Comment by slontis** [comment]
it is probably related to ctx->bufsz not being cleared also..

**Comment by slontis** [comment]
so it is a bug I think..

**Comment by guidovranken** [comment]
OK. We can create a new issue. And engage in a patch-test cycle until I encounter no more bugs around ctx re-initialization with my fuzzer.

**Comment by slontis** [comment]
In my commit I discuss the ones that dont work with correct input.
Note that the test I do sets up keys and iv that are large enough to handle all cipher types..

**Comment by slontis** [comment]
> OK. We can create a new issue. And engage in a patch-test cycle until I encounter no more bugs around ctx re-initialization with my fuzzer.

PR #12523 solves the buffered update issue.
