### ISSUE TITLE
EC_GROUP_new_by_curve_name

### ISSUE THREAD

**Issue by lvzhao666** [openssl/openssl#12412]
Which of these elliptic encryption curves corresponds to Openssl?
Based on ECC NIST curve of P - 256 (namely secp256r1) is calculated, the parameters of the curve, see: https://www.secg.org/SEC2-
Ver 1.0. PDF
"Secp256r1" : {
"P" : 0 xffffffff00000001000000000000000000000000ffffffffffffffffffffffff,
"A" : 0 xffffffff00000001000000000000000000000000fffffffffffffffffffffffc,
"B" : 0 x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b,
"G" : (0 x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296,
0 x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5),
"N" : 0 xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551,
"H" : 0 x1}

**Comment by romen** [comment]
`secp256r1` is understood by OpenSSL apps, but treated as an alias for `prime256v1` as the same curve is defined with different names by both SECG and ANSI:

https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/apps/ecparam.c#L225-L243

https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/crypto/ec/ec_curve.c#L2929-L2939

https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/crypto/ec/ec_curve.c#L2961

Here are the parameters:

https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/crypto/ec/ec_curve.c#L384-L420
