### ISSUE TITLE
Leading zeroes in BN_bn2hex

### ISSUE THREAD

**Issue by Yuri12358** [openssl/openssl#12415]
https://github.com/openssl/openssl/blob/454afd9866300b984306c5b565a9d55568a5bc50/crypto/bn/bn_conv.c#L38
This line can lead to a leading zero in a hexadecimal representation of a given integer in cases when the highest byte of the number is less that 16, thus, the byte has a leading zero in its representation (like 12 byte has the representation of `0C`).

Is this an error or a desired behavior? If it's desired, I think it should be mentioned in the docs, and if it's a bug, I could fix that.

**Comment by levitte** [comment]
I believe it's expected. Most people expect full bytes, i.e always an even number of nibbles.

**Comment by mattcaswell** [comment]
Seems like the question was answered. Closing.
