### ISSUE TITLE
EVP_MAC_final segfault on NULL outl

### ISSUE THREAD

**Issue by ozppupbg** [openssl/openssl#12425]
Hello,

while playing with the EVP_MAC API I noticed, that ``EVP_MAC_final`` sometimes crashed with a NULL reference if ``outl`` was NULL.

While looking into this I noticed, that everything is fine and as documented in ``mac_lib.c``:
https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/crypto/evp/mac_lib.c#L120-L132

But the provider implementations work very different:

**Blake2, CMAC and poly1305 don't set it at all:**
https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/providers/implementations/macs/blake2_mac_impl.c#L98-L105

https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/providers/implementations/macs/cmac_prov.c#L116-L122

https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/providers/implementations/macs/poly1305_prov.c#L91-L98

**GMAC and Siphash set it without a NULL check:**
https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/providers/implementations/macs/gmac_prov.c#L111-L128

https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/providers/implementations/macs/siphash_prov.c#L98-L109

**HMAC sets it with a NULL check:**
https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/providers/implementations/macs/hmac_prov.c#L125-L136

**KMAC only sets it if the operation was ok:**
https://github.com/openssl/openssl/blob/a01cae99ac384cb6a74b46ccdc90736fe0754958/providers/implementations/macs/kmac_prov.c#L286-L304

So my first question would be, what is the expected correct behaviour? Who is resposible for setting this value?

If it is ``EVP_MAC_final`` is would suggest removing the parameter from the provider implementations altogether.

**Comment by ozppupbg** [comment]
@paulidale: Thank you for the fix, but what speeks against defining/demanding some specific behaviour for the MAC implementations?

Woulkd this not be better in the long run and avoid other problems?

**Comment by paulidale** [comment]
I did consider updating the MACs to be consistent, but decided having the framework do more was a safer  approach.  The framework supplies a default size, an individual MAC can replace this if it want.  This seems less error prone than insisting each MAC does all of this.  I guess it comes down to personal preference.

I didn't remove the NULL checks from those MACs that did do them and arguably should have.

**Comment by ozppupbg** [comment]
Hmm, I'm still not convinced, that the entire procedure is necessary.
If the MAC returns something different than reported by ``EVP_MAC_size(ctx)`` I would consider this a violation of API.

And if we could agree on this, the ``outl`` parameter could be removed from the provider implementations entirely and thus removing the problem at its root.

**Comment by paulidale** [comment]
I had a brief discussion with some of the other team members and the consensus was keeping the `outl` parameter wasn't harmful and helps with future proofing.  If someone doesn't want to bother with it, pass NULL and it will be ignored.
