### ISSUE TITLE
Why are all discussions about racial terms blocked?

### ISSUE THREAD

**Issue by flecno** [openssl/openssl#12428]
do you have any idea? There was a discussion about this already in https://github.com/openssl/openssl/pull/12089 and https://github.com/openssl/openssl/issues/12148 but it was closed without any change. I can't see any reason to still discriminate people in this project. I also could not not find any argument to close it. Is it because white people have the power in openssl?

**Comment by flecno** [comment]
4 people vote for it to close this MR? I think the discussion is still very relevant. Who are you to end this with so little response?

**Comment by rwfranks** [comment]
Unless you can point to some specific example in OpenSSL that actually is offensive to some group or another, then this issue should be closed too.
Nobody has the right to not be offended.  If they did, satirists would be out of business.
As things are, they have a field day mocking people like you making idiots of themselves..

**Comment by Aspie96** [comment]
This made me interested in OpenSSL.

The code of conduct isn't full of bullshit nor is the community.

Good for OpenSSL!

**Comment by iamamoose** [comment]
Closing as @levitte answered the question.  I'd also note that although the initial PR of wording changes was not approved, others since have been, and some wording has already been changed i.e. via https://github.com/openssl/openssl/commit/ce3080e931d77fda3bb4f2d923fcc6cec967d1a3

**Comment by flecno** [comment]
ok thanks for the clarification. I was a little wired when I wrote this ticket. I see what happened, and I apologize for my accusations.
