### ISSUE TITLE
EVP_MAC.pod example uses wrong final signature

### ISSUE THREAD

**Issue by ozppupbg** [openssl/openssl#12424]
The [EVP_MAC.pod](https://github.com/openssl/openssl/blob/master/doc/man3/EVP_MAC.pod) documentation file uses the wrong ``EVP_MAC_final`` signature with only 3 parameters in the example:
``if (!EVP_MAC_final(ctx, buf, &final_l))``

The signature should be:
```
int EVP_MAC_final(EVP_MAC_CTX *ctx,
                   unsigned char *out, size_t *outl, size_t outsize);
```

**Comment by beldmit** [comment]
Would you like to submit a PR?
