### ISSUE TITLE
OpenSSL error[0x14228044] construct_ca_names: internal error

### ISSUE THREAD

**Issue by abhay8nitt** [openssl/openssl#12436]
I am using haproxy 2.1.4 am getting the below errors continuously.

**OpenSSL error[0x14228044] construct_ca_names: internal error**
The **ca-file** has close to 394 entries. It works just fine with 381 entries in it. 
Spoke to the haproxy community but they say its an openssl error.
Is there any artificial limit imposed? How can one get around this error?

Any help is appreciated. Thanks

**Comment by kaduk** [comment]
I'm not seeing any artificial limits in the sources, but the total list of names has to fit in 2^16 bytes.  You could look at a packet capture for the success (381-entry) case in wireshark to see if the "ca_names" TLS extension is nearing that size, which would pretty authoritatively confirm whether that's the issue.
Note that `SSL_OP_DISABLE_TLSEXT_CA_NAMES` is available to disable sending the extension (with all the consequences that entails).

**Comment by abhay8nitt** [comment]
@kaduk will try this out.. thanks

**Comment by paulidale** [comment]
Has this been adequately resolved?

**Comment by mattcaswell** [comment]
No, response to previous question. Assuming resolved. Closing.
