### ISSUE TITLE
MAC Salt/IV/Custom parameter confusion

### ISSUE THREAD

**Issue by ozppupbg** [openssl/openssl#12441]
Hello,

while looking into other stuff, I noticed, that there are some different parameters for MACs, which are similar or just use different names. Additionally in some cases the handling of these parameters is not consistent across the algorithms.

So, to start there are three MAC parameters I'd like to talk about (from [/include/openssl/core_names.h](https://github.com/openssl/openssl/blob/master/include/openssl/core_names.h)):
- ``#define OSSL_MAC_PARAM_IV           "iv"         /* octet string */``
- ``#define OSSL_MAC_PARAM_CUSTOM       "custom"     /* utf8 string */``
- ``#define OSSL_MAC_PARAM_SALT         "salt"       /* octet string */``

``IV`` is currently only used in GMAC, ``CUSTOM`` is used in Blake2 and KMAC and ``SALT`` is only used in Blake2.
While ``CUSTOM`` is very different conceptually from the other two, it is often called "personalization" for hashes/MACs or allso "tweak" for ciphers.
So is ``CUSTOM`` deliberately chosen to be different from the usual terms? Or should it be changed?

The other question regards the use of ``IV`` and ``SALT``:
Is it deliberate, that two different parameters are in use?
From looking at the algorithms, I would conclude, that ``SALT`` is an optional value, like ``CUSTOM``.
And ``IV`` suggests that key-reuse is not safe and can only be done with a different ``IV``.
If this is the case, it should be documented somewhere.

On the other hand, there is the Poly1305 algorithm, which originally had a Nonce as a specified parameter (which must also not be reused for a given key). But the implementation uses the version from RFC7539 and extracts the Nonce from the key:
https://github.com/openssl/openssl/blob/3d5a7578e09a984c6475b1c008f5c76f850328cb/crypto/poly1305/poly1305.c#L434-L439

Following the logic above (there is no ``IV``), the Poly1305 MAC would be safe to use multiple times with the same key, but this is not the case!

From the perspective, that a program could get any algorithm from a provider and should be able to select the correct parameters and how to work with this algorithm, there should be a way to handle the above case and communicate, that Poly1305 must only be used with one-time keys.

Are there any suggestions how to handle this?
An option would be to have a gettable parameter which is only present in such cases.

**Comment by paulidale** [comment]
I believe the differing names came from the standards documents where the various MACs are defined.

**Comment by paulidale** [comment]
It seems reasonable, to me at least, for Poly1305 to allow the nonce to be overridden as an extension beyond the RFC.

Allowing parameters with multiple names (in this case aliasing _iv_ and _salt_ for MACs) is something we  discussed.  We decided not to for reasons I no longer remember.  I do remember that inconsistencies crop up if it is done universally.  I.e. a pair of parameters that seemingly could and should be aliased can't be.

It would be possible for individual algorithms to allow two names for a single parameter.  Do we want to go there?

**Comment by richsalz** [comment]
>It would be possible for individual algorithms to allow two names for a single parameter. Do we want to go there?

Please, emphatically, *NO*

Let's get this release out with one name for each "thing" and then worry about aliases, if needed, later.

**Comment by kaduk** [comment]
> I believe the differing names came from the standards documents where the various MACs are defined.

Yes.  https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf refers to the "customization string", hence "custom".  ("salt" and "IV" have a long history, of course.)

**Comment by kaduk** [comment]
It seems like the main unanswered question relates to whether key+IV reuse is unsafe and how that should be documented; is that correct?
I think it seems reasonable to stick to the names used by the algorithm specs, and avoid aliases for parameter names (at least for now, given the release timelines).

**Comment by ozppupbg** [comment]
@kaduk: yes, that is correct.

I think the ``IV`` & ``Salt`` issue does not require additional discussion right now.
But would this be the right time to document the "definitions" I mentioned above?

**Comment by kaduk** [comment]
It seems reasonable to improve the documentation for the three parameter types, sure.
I assume that EVP_MAC.pod is the right place to do so, but am undecided on whether to just augment the existing parameter descriptions or to have a separate paragraph that compares/contrasts the three.
