### ISSUE TITLE
Is TLSv1.1 and lower, only available with legacy provider? (v3)

### ISSUE THREAD

**Issue by xnox** [openssl/openssl#12446]
Are protocol versions controllable with providers? Specifically are TLSv1.1 and lower only available via the legacy provider, and not via default or FIPS one?

**Comment by kroeckx** [comment]
As I understand it, TLS is not inside the provider. All the
crypto is done inside a provider, TLS just makes use of a
provider.

**Comment by paulidale** [comment]
TLS 1.1. and before will not work with the FIPS provider, they will work with the default provider.

Of course, all the algorithms used need to be present.  The legacy provider has RC4, SEED, IDEA, ... so cipher suites that use these will not work without it loaded.

**Comment by paulidale** [comment]
Providers control what algorithms are available for TLS, they don't current limit TLS versions.
