### ISSUE TITLE
Please move MD5, MD5-SHA1, SHA1 digests from default & fips providers to legacy provider (v3)

### ISSUE THREAD

**Issue by xnox** [openssl/openssl#12445]
I'm looking at https://wiki.openssl.org/index.php/OpenSSL_3.0#Provider_implemented_digests

I am not too sure if wikipage & source code for v3 currently match each other. It appears that they are. Please excuse me, if they don't.

Please remove MD5 and MD5-SHA1 from default provider, please remove SHA1 from default & fips providers. Please add them to the legacy provider instead.

MD5 is not trusted by anything anymore.

From NIST Special Publication 800-131A Revision 2, https://doi.org/10.6028/NIST.SP.800-131Ar2

> SHA-1 for digital signature generation:
SHA-1 may only be used for digital signature generation where specifically allowed by NIST protocol-specific guidance. For all other applications, SHA-1 is disallowed for digital signature generation.

> SHA-1 for digital signature verification:
When used for digital signature verification, SHA-1 is allowed for legacy use.

**Comment by paulidale** [comment]
This isn't going to happen for OpenSSL 3.0.  I expect at a future major release it might.

They are all far too widely used to be moved to legacy and not loaded by default.

**Comment by richsalz** [comment]
The 3.0 schedule has not slipped very much.  What non-FIPS ciphers do you think are in the FIPS provider library?

OpenSSL does not have any real metrics on how it is used -- it's too widely deployed, in too many environments, and it polls and such have never been effective.  Also, vendors who bake it into their products often don't know what all their customers are doing. It's also more than just the public Internet.  It's used in lots of hardware.  Stats about browser use and the WebPKI, are interesting but not necessarily dominant.  On the other hand, the project doesn't know, as I said above. Given that, the only thing the project can do is to pre-announce deprecations with a very long window.  As in a couple of years.

**Comment by xnox** [comment]
> The 3.0 schedule has not slipped very much. What non-FIPS ciphers do you think are in the FIPS provider library?
> 
> OpenSSL does not have any real metrics on how it is used -- it's too widely deployed, in too many environments, and it polls and such have never been effective. Also, vendors who bake it into their products often don't know what all their customers are doing. It's also more than just the public Internet. It's used in lots of hardware. Stats about browser use and the WebPKI, are interesting but not necessarily dominant. On the other hand, the project doesn't know, as I said above. Given that, the only thing the project can do is to pre-announce deprecations with a very long window. As in a couple of years.

SHA-1 is disallowed for digital signature generation, as per NIST Special Publication 800-131A Revision 2, https://doi.org/10.6028/NIST.SP.800-131Ar2

SHA-1 is shipped in the FIPS provider as per https://wiki.openssl.org/index.php/OpenSSL_3.0#Provider_implemented_digests

Meaning one will have to rip out or otherwise disable SHA-1 to get FIPS provider to be certified by NIST.

And if it's no longer good enough for FIPS, it should be removed from default provider and moved to legacy one.

I'm asking to move these things to legacy provider. If one needs to talk to things using legacy algorithms, one can install and activate legacy provider. There is no need for the default provider to ship those.

Default provider should target public internet, widely adopted and deployed algorithms.
MD5 & SHA1 are no longer widely adopted or deployed on the public internet.

**Comment by richsalz** [comment]
Look at https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/fips140-2/fips1402ig.pdf  MD5, in particular when used with SHA1 for TLS 1.0/1.1 is allowed (p85).  See, for example, p117 which talks about SHA1 for certs and when it is allowed.

You might be right about webpki, but I think you're not correct about FIPS.

**Comment by xnox** [comment]
> Look at https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/fips140-2/fips1402ig.pdf MD5, in particular when used with SHA1 for TLS 1.0/1.1 is allowed (p85). See, for example, p117 which talks about SHA1 for certs and when it is allowed.
> 
> You might be right about webpki, but I think you're not correct about FIPS.

The document you cite above, FIPS PUB 140-2 has overall last modification date June 29, 2020. Yet section 7.5 inside it has Last Modified Date: 05/10/2017.

NIST Special Publication 800-131A Revision 2 I cite was published In March 2019.

I am confused.

To me, the two publications appear to be in conflict with each other, and I do not know which one takes precedence. And if `echo | openssl sha1` should be allowed by the fips provider, or not.

**Comment by richsalz** [comment]
I understand the difference in dates, I guess you need to ask NIST or a validation lab.

Note that the OpenSSL FIPS approach for 3.0 is different from previous.  In the earlier module, you were prevented by doing some things because of the code. Now some of the things that you "shoudn't" do are moved to administrative guidance.  So your echo/sha example falls into that category.

**Comment by xnox** [comment]
> I understand the difference in dates, I guess you need to ask NIST or a validation lab.
> 
> Note that the OpenSSL FIPS approach for 3.0 is different from previous. In the earlier module, you were prevented by doing some things because of the code. Now some of the things that you "shoudn't" do are moved to administrative guidance. So your echo/sha example falls into that category.

Interesting.

Also, I wonder, is it *required* ? I.e. although allowed, can an opinion be made to not support MD5-SHA1 for example? Given that other better mechanisms are available.

**Comment by richsalz** [comment]
Sure you can provide a subset of what is allowed; OpenSSL is doing that, for example.  "Better mechanisms" aren't always available, e.g., if you have to interoperate with a deployed base.

**Comment by paulidale** [comment]
FIPS is confusing :)  SHA-1 is still allowed and can be validated.  I've a recollection that there are restrictions on what it can be used for (e.g. don't generate new certs but can validate old ones) -- but as @richsalz wrote, ask a FIPS lab: I'm not an expert.

Last we checked, several root CA certificates were SHA-1 signed.  These need to continue working.  SHA-1 is fine for TLS HMACs still.  SHA-1 is also used in a lot of other places (e.g. have _all_ subversion servers worldwide changed to something else yet?).

I'm fairly confident that making it legacy would break a lot of people.

**Comment by t8m** [comment]
SHA1 is definitely OK for HMAC. The collision attacks do not apply to HMAC.

**Comment by xnox** [comment]
> have all subversion servers worldwide changed to something else yet?

What is subversion? The first VCS I learned to use was git. 😀
