### ISSUE TITLE
A proposal for a small rename fest

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#12455]
This comment set off a whole line of thoughts: https://github.com/openssl/openssl/pull/12410#discussion_r455155645

That comment suggests using "export" and "import" instead of "serialize" and "deserialize".  Just on brevity alone, this is worth serious consideration.

However, we already use the terms "export" and "import" in KEYMGMT, which specifically does conversion of internal key structures to OSSL_PARAM arrays, and the other way around.  One might argue that this is also a form of serialization and deserialization, but still, it's likely to be confusing when loosely talking about "exporting" and "importing", like "which are we talking about again?"
Furthermore, at least the deserializer that's currently in #12410 has a function to export an object it holds, so naming wise, we'd end up with the dispatched function `OSSL_FUNC_import_export_object`, which isn't the most intuitive.

So the thoughts went to another terminology for the OSSL_PARAM array from / to provider side object...  and we can draw example from `EVP_PKEY_fromdata`, which uses the KEYMGMT import function already.  So maybe "from_data" and "to_data" might be better general names for that sort of dispatched provider function?

So, a proposal:

1.  Rename "export" and "import" in KEYMGMT to "to_data" and "from_data".  That will affect these names:

    | from | to |
    | ------ | --- |
    | `OSSL_FUNC_KEYMGMT_IMPORT` | `OSSL_FUNC_KEYMGMT_FROMDATA` |
    | `OSSL_FUNC_KEYMGMT_IMPORT_TYPES` | `OSSL_FUNC_KEYMGMT_FROMDATA_TYPES` |
    | `OSSL_FUNC_KEYMGMT_EXPORT` | `OSSL_FUNC_KEYMGMT_TODATA` |
    | `OSSL_FUNC_KEYMGMT_EXPORT_TYPES` | `OSSL_FUNC_KEYMGMT_TODATA_TYPES` |
    | `OSSL_FUNC_keymgmt_import` | `OSSL_FUNC_keymgmt_from_data` |
    | `OSSL_FUNC_keymgmt_import_types` | `OSSL_FUNC_keymgmt_from_data_types` |
    | `OSSL_FUNC_keymgmt_export` | `OSSL_FUNC_keymgmt_to_data` |
    | `OSSL_FUNC_keymgmt_export_types` | `OSSL_FUNC_keymgmt_to_data_types` |

    There are a number of internal functions that we may chose to rename in a similar way...

2.  Rename SERIALIZER and (upcoming) DESERIALIZER to EXPORT and IMPORT, and also make the minute changes to match the KEYMGMT "to_data" and "from_data" rename.  That will affect these names:

    | from | to |
    | ------ | --- |
    | `OSSL_OP_SERIALIZER` | `OSSL_OP_EXPORT` |
    | `OSSL_FUNC_SERIALIZER_NEWCTX` | `OSSL_FUNC_EXPORT_NEWCTX` |
    | `OSSL_FUNC_SERIALIZER_FREECTX` | `OSSL_FUNC_EXPORT_FREECTX` |
    | `OSSL_FUNC_SERIALIZER_SET_CTX_PARAMS` | `OSSL_FUNC_EXPORT_SET_CTX_PARAMS` |
    | `OSSL_FUNC_SERIALIZER_SETTABLE_CTX_PARAMS` | `OSSL_FUNC_EXPORT_SETTABLE_CTX_PARAMS` |
    | `OSSL_FUNC_SERIALIZER_SERIALIZE_DATA` | `OSSL_FUNC_EXPORT_FROM_DATA` |
    | `OSSL_FUNC_SERIALIZER_SERIALIZE_OBJECT` | `OSSL_FUNC_EXPORT_FROM_OBJECT` |
    | `OSSL_FUNC_serializer_newctx` | `OSSL_FUNC_export_newctx` |
    | `OSSL_FUNC_serializer_freectx` | `OSSL_FUNC_export_freectx` |
    | `OSSL_FUNC_serializer_set_ctx_params` | `OSSL_FUNC_export_set_ctx_params` |
    | `OSSL_FUNC_serializer_settable_ctx_params` | `OSSL_FUNC_export_settable_ctx_params` |
    | `OSSL_FUNC_serializer_serialize_data` | `OSSL_FUNC_export_from_data` |
    | `OSSL_FUNC_serializer_serialize_object` | `OSSL_FUNC_export_from_object` |

    ... and the following would happen in #12410: 

    | from | to |
    | ------ | --- |
    | `OSSL_OP_DESERIALIZER` | `OSSL_OP_IMPORT` |
    | `OSSL_FUNC_DESERIALIZER_NEWCTX` | `OSSL_FUNC_IMPORT_NEWCTX` |
    | `OSSL_FUNC_DESERIALIZER_FREECTX` | `OSSL_FUNC_IMPORT_FREECTX` |
    | `OSSL_FUNC_DESERIALIZER_GET_PARAMS` | `OSSL_FUNC_IMPORT_GET_PARAMS` |
    | `OSSL_FUNC_DESERIALIZER_GETTABLE_PARAMS` | `OSSL_FUNC_IMPORT_GETTABLE_PARAMS` |
    | `OSSL_FUNC_DESERIALIZER_SET_CTX_PARAMS` | `OSSL_FUNC_IMPORT_SET_CTX_PARAMS` |
    | `OSSL_FUNC_DESERIALIZER_SETTABLE_CTX_PARAMS` | `OSSL_FUNC_IMPORT_SETTABLE_CTX_PARAMS` |
    | `OSSL_FUNC_DESERIALIZER_DESERIALIZE` | `OSSL_FUNC_IMPORT_FROM_DATA` |
    | `OSSL_FUNC_DESERIALIZER_EXPORT_OBJECT` | `OSSL_FUNC_IMPORT_OBJECT_TO_DATA` |
    | `OSSL_FUNC_deserializer_newctx` | `OSSL_FUNC_import_newctx` |
    | `OSSL_FUNC_deserializer_freectx` | `OSSL_FUNC_import_freectx` |
    | `OSSL_FUNC_deserializer_get_params` | `OSSL_FUNC_import_get_params` |
    | `OSSL_FUNC_deserializer_gettable_params` | `OSSL_FUNC_import_gettable_params` |
    | `OSSL_FUNC_deserializer_set_ctx_params` | `OSSL_FUNC_import_set_ctx_params` |
    | `OSSL_FUNC_deserializer_settable_ctx_params` | `OSSL_FUNC_import_settable_ctx_params` |
    | `OSSL_FUNC_deserializer_deserialize` | `OSSL_FUNC_import_from_data` |
    | `OSSL_FUNC_deserializer_export_object` | `OSSL_FUNC_import_object_to_data` |

    (`object_to_data` is for "exporting" an provider side object held by the deserializer implementation to an OSSL_PARAM array)

Thoughts?

-----

My thoughts also went to `OSSL_PARAM` itself.  That name has been source for confusion in a number of manners already, having some think for a brief moment that all dispatched provider functions would simply take such an array in place of any sort of normal C arguments (that was never the intent).  Also, it's pretty confusing to loosely talk about parameters when both `OSSL_PARAM` and public key parameters (domain parameters as well as others), like "which are we talking about again?"
Thinking a bit more about it, and `OSSL_PARAM` array is really just a bag of (tagged, typed and language/library agnostic) data, to be pilfered by any code interested...

However, that's a much bigger and change, and may also be controversial, as we may or may not want to rename the likes of  "get_params", "get_ctx_params", etc to "get_data", "get_ctx_data", etc, and I'm frankly unsure that it's a step in the "right" direction.

This part may be left for another rainy day...

**Comment by levitte** [comment]
@t8m, since you're the "cause" of this, I'd like to know if my description matches your thoughts.

**Comment by levitte** [comment]
Oh, and of course, on the libcrypto side, the prefixes `OSSL_SERIALIZER` and `OSSL_DESERIALIZER` would change to `OSSL_EXPORT` and `OSSL_IMPORT`, respectively, and I'm thinking that `crypto/serializer/` should be renamed to `crypto/imexport/` (because it contains both).

**Comment by petrovr** [comment]
Richard Levitte wrote:
> This comment set off a whole line of thoughts: https://github.com/openssl/openssl/pull/12410#discussion_r455155645
>
> That comment suggests using "export" and "import" instead of "serialize" and "deserialize".  Just on brevity alone, this is worth serious consideration.

Interesting why serialization is not acceptable?
Now marshalling is not widely used.

[SNIP]
Roumen

**Comment by levitte** [comment]
> Interesting why serialization is not acceptable?

There were comments in #12410 indicating that the deserialize function names are quite a mouthful, not quite so easy to write (fingers tumbling over each other), quite a tongue twister when try to pronounce the words (especially if English isn't your native language)...  So while serialization isn't outright banned, making things easier for the programmers out there isn't a bad thing.

**Comment by t-j-h** [comment]
I disagree with @levitte on this as frankly serialise and deserialise are the correct words and they are widely used in programming contexts. The saving typing argument is specious in my view as following that principle would lead to fortran-style 6 character function names (which would save a lot of typing but certainly wouldn't be a good idea). 

I don't see anything wrong with the current set of names being used - they are descriptive - and they are out there in use already.  I see it as a little too late in the process to be changing terminology (as distinct from correcting API naming pattern issues which we have done elsewhere).

Note we have been using serialisation as terminology since at least the [new architecture](https://www.openssl.org/docs/OpenSSLStrategicArchitecture.html) was published.

**Comment by kaduk** [comment]
My small change: while "serializer" and "deserializer" may have flaws of their own, "import"/"export" can be quite confusing, since they require an implicit reference frame.  What is the "inside" vs. the "outside" that determines whether we are importing or exporting?  At least with serialize/deserialize it's clear what direction the data is moving in.

**Comment by t8m** [comment]
> @t8m, since you're the "cause" of this, I'd like to know if my description matches your thoughts.

Yes, this proposal matches my thoughts.

I would disagree a little bit with @t-j-h. Serialise and deserialise (or serialize/deserialize? :smile:) is usually used for marshalling internal state of some object to some opaque internal form that can be transferred or stored. It does not necessarily mean exporting and importing data to/from multiple various standardized forms of data. BTW in the way this is now designed you can have a chain of "deserializers" which is in this context rather confusing because you do not "deserialize" PEM into DER and only then "deserialize" DER into the internal object representation.

@kaduk I do not really see this confusion of reference frame. The provider that holds the key object is the inside, that should be quite obvious. On the other hand it maybe shows that the "PEM into DER"  is neither "deserializer" nor "importer".

**Comment by t-j-h** [comment]
If you don't like serialise/deserialise then the other used pattern for APIs for this sort of thing is encode/decode rather than import/export.

**Comment by levitte** [comment]
I could absolutely go with "serialize" -> "encode" and "deserialize" -> "decode" if that's satisfactory for everyone.

> ... because you do not "deserialize" PEM into DER and only then "deserialize" DER into the internal object representation.

Er, I fail to see why not...  The PEM library does *exactly* that.

**Comment by t-j-h** [comment]
I don't think the APIs should be changed - in that they aren't egregiously off target.
But if they were changed encode/decode seems a better fit then export/import.

**Comment by t8m** [comment]
Encode/decode is fine for me. At least I can pronounce it at first try. :smile: And it looks to me to be more accurate than serialize/deserialize.

I do not *insist* on the rename but I also do not think the API has to be set in stone from now on. IMO it still would not be particularly disruptive to do the rename now.

**Comment by levitte** [comment]
> IMO it still would not be particularly disruptive to do the rename now.

I agree with this.  These are new APIs, never released.

**Comment by mattcaswell** [comment]
We already use encode/decode to mean something else, i.e. the EVP_Encode* APIs.

**Comment by levitte** [comment]
So? Besides, EVP_Encode can be said to serialize into plain base64

**Comment by mspncp** [comment]
> Besides, EVP_Encode can be said to serialize into plain base64

Yes, just like encode/decode is used for conversion from unicode strings to byte streams and vice versa.

Another reason why I like this pair is because both words have the same length.
