### ISSUE TITLE
s_ server parameter

### ISSUE THREAD

**Issue by bowensd** [openssl/openssl#12453]
In the doc of s_server command ,it displays `-cipher val
This allows the list of TLSv1.2 and below ciphersuites used by the server to be modified. This list is combined with any TLSv1.3 ciphersuites that have been configured. When the client sends a list of supported ciphers the first client cipher also included in the server list is used. Because the client specifies the preference order, the order of the server cipherlist is irrelevant. See the ciphers command for more information.`
Is it fair to say that I can use TLS1.3ciphersuites in TLS1.2？

Another parameter is described that
`-ciphersuites val
This allows the list of TLSv1.3 ciphersuites used by the server to be modified. This list is combined with any TLSv1.2 and below ciphersuites that have been configured. When the client sends a list of supported ciphers the first client cipher also included in the server list is used. Because the client specifies the preference order, the order of the server cipherlist is irrelevant. See the ciphers command for more information. The format for this list is a simple colon (":") separated list of TLSv1.3 ciphersuite names.`
So I can use TLS1.2 ciphersuites in TLS1.3？ Only if I set the parameters?

**Comment by kaduk** [comment]
TLS 1.3 ciphersuites and TLS 1.2 ciphersuites are fundamentally different things (in a semantic sense, they "have a different type", conveying different pieces of information). The allocated numbers from IANA are taken from the same range (with no overlap), though, and they are sent together in the same field on the wire.
This text is just saying that you can separately set the TLS 1.2 ciphersuites and the 1.3 ciphersuites without overwriting the other one.  When using TLS 1.2, only the TLS 1.2 ciphersuites are used, and when using TLS 1.2, only the TLS 1.3 ciphersuites are used.
