### ISSUE TITLE
Inconsistent libctx awareness function parameters

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#12454]
There are many functions which had two parameters added for libctx awareness: `OPENSSL_CTX *libctx, const char *propq`. For most of them, they were added to the end of the parameter list,

```
~/src/openssl$ git grep -n  'OPENSSL_CTX.*propq)' |  wc -l
59
```

but eight functions are exceptional, they got them added at the beginning:

```
~/src/openssl$ git grep -n  'OPENSSL_CTX.*propq,' |  wc -l
8
```

Wouldn't it make sense to straighten that inconsistency out before the first beta?

```
~/src/openssl$ git grep -n -A 1 'OPENSSL_CTX.*propq,'
crypto/ec/ec_kmeth.c:79:EC_KEY *ec_key_new_method_int(OPENSSL_CTX *libctx, const char *propq,
crypto/ec/ec_kmeth.c-80-                              ENGINE *engine)
--
crypto/ec/ec_lib.c:26:EC_GROUP *ec_group_new_with_libctx(OPENSSL_CTX *libctx, const char *propq,
crypto/ec/ec_lib.c-27-                                   const EC_METHOD *meth)
--
crypto/ec/ec_local.h:602:EC_GROUP *ec_group_new_with_libctx(OPENSSL_CTX *libctx, const char *propq,
crypto/ec/ec_local.h-603-                                   const EC_METHOD *meth);
--
crypto/ec/ec_local.h:658:EC_KEY *ec_key_new_method_int(OPENSSL_CTX *libctx, const char *propq,
crypto/ec/ec_local.h-659-                              ENGINE *engine);
--
doc/man3/SSL_CTX_new.pod:21: SSL_CTX *SSL_CTX_new_with_libctx(OPENSSL_CTX *libctx, const char *propq,
doc/man3/SSL_CTX_new.pod-22-                                  const SSL_METHOD *method);
--
include/openssl/ec.h:894:EC_KEY *EC_KEY_new_by_curve_name_with_libctx(OPENSSL_CTX *ctx, const char *propq,
include/openssl/ec.h-895-                                             int nid);
--
include/openssl/ssl.h:1531:__owur SSL_CTX *SSL_CTX_new_with_libctx(OPENSSL_CTX *libctx, const char *propq,
include/openssl/ssl.h-1532-                                        const SSL_METHOD *meth);
--
ssl/ssl_lib.c:3086:SSL_CTX *SSL_CTX_new_with_libctx(OPENSSL_CTX *libctx, const char *propq,
ssl/ssl_lib.c-3087-                                 const SSL_METHOD *meth)
```

**Comment by mspncp** [comment]
Looking at the list, I ask myself: should `ec_key_new_method_int` be renamed to `ec_key_new_method_with_libctx`?

**Comment by paulidale** [comment]
A thought: should the OPENSSL CTX and the property query be combined into a structure?  We've had cases in the past where one but not the other was passed.

**Comment by t8m** [comment]
> A thought: should the OPENSSL CTX and the property query be combined into a structure? We've had cases in the past where one but not the other was passed.

I do not think so. This imho complicates callers and the called function unnecessarily.

**Comment by romen** [comment]
@mspncp should this also addressed before beta1?

**Comment by mspncp** [comment]
I can add it for now, then we can go through the milestone entries on Tuesday. But actually I'm not the right person to ask. For tickets which are listed in the Google spreadsheet, you should find the answer there.

**Comment by mspncp** [comment]
It's obsolete.
