### ISSUE TITLE
3.0.0-alpha5: typo in ssl.h

### ISSUE THREAD

**Issue by balducci** [openssl/openssl#12477]
hi

there seems to be a typo in ssl.h (3.0.0-alpha5):

      ----8<----
      diff -c include/openssl/ssl.h.FIX_CERTIFIATE include/openssl/ssl.h
      *** include/openssl/ssl.h.FIX_CERTIFIATE	Fri Jul 17 11:38:46 2020
      --- include/openssl/ssl.h	Fri Jul 17 11:38:46 2020
      ***************
      *** 1710,1716 ****
        __owur X509 *SSL_get1_peer_certificate(const SSL *s);
        /* Deprecated in 3.0.0 */
        #  ifndef OPENSSL_NO_DEPRECATED_3_0
      ! #   define SSL_get_peer_certificate SSL_get1_peer_certifiate
        #  endif
        # endif

      --- 1710,1716 ----
        __owur X509 *SSL_get1_peer_certificate(const SSL *s);
        /* Deprecated in 3.0.0 */
        #  ifndef OPENSSL_NO_DEPRECATED_3_0
      ! #   define SSL_get_peer_certificate SSL_get1_peer_certificate
        #  endif
        # endif
      ---->8----

AFAICS, it is still there in master

cheers
gabriele

**Comment by t8m** [comment]
Would you like to submit a PR? This would be well within `CLA: trivial`.

**Comment by t8m** [comment]
Ah independent PR is already there: #12468
