### ISSUE TITLE
s390x Eddsa HW support regression

### ISSUE THREAD

**Issue by p-steuer** [openssl/openssl#12476]
Either commit eea1e780a1 (build break) or 3965480c82 broke s390x HW support for Ed25519 and Ed448.

I would do the fix myself, however, i dont know what the recommended hooks for HW support are wrt the new architecture.

Right now, ED25519/448_sign/verify SW implementations are called directly by the ed25519/448_digest_sign/verify from providers/implementations/signature/eddsa.c. So all the pkey_method stuff seems not to be in place anymore. Also the ECX_KEY object doesnt have any hooks.

Compare e.g. to ECDSA_sign/verify: The EC_KEY object has a suitable "method" pointer.

**Comment by slontis** [comment]
The methods are gone for the other bits... i.e.
ecx_kmgmt.c has the keygen changes for s390,
and ecx_exch.c has the key agree parts..
(Not sure why the signature part was omitted..)
Why can't it be done in a similiar way inside eddsa.c?

e.g..
#ifdef S390X_EC_ASM
    if (OPENSSL_s390xcap_P.pcc[...)
        return s390x_digestsign(gctx);
#endif

**Comment by p-steuer** [comment]
Thanks @slontis for looking into this one.
