### ISSUE TITLE
rmd and rcid options are missing in ocsp man page for version 1.1.1

### ISSUE THREAD

**Issue by johnshajiang** [openssl/openssl#12481]
Although options `rmd` and `rcid` are supported by tool ocsp in version 1.1.1g, they are missing in the 1.1.1 man page [1]. However they are present in the master man page [2].

[1] https://www.openssl.org/docs/man1.1.1/man1/openssl-ocsp.html
[2] https://www.openssl.org/docs/manmaster/man1/openssl-ocsp.html

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
