### ISSUE TITLE
Is this function can do Hardware signature？

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12487]
@DDvO https://github.com/openssl/openssl/blob/168c595b14ff034ec40642ec1cb5d2c77ce82e0e/crypto/cmp/cmp_protect.c#L222
I Fund i can do Hardware signature for popo(in which the private key in Hardware and can't Load to ctx) using engine to repleace sign function, but i can't do Hardware signature for proctection because there are some checking of the private key before  proctection sign

**Comment by stardrift1** [comment]
in this place: } else if (ctx->cert != NULL && ctx->pkey != NULL) {

**Comment by DDvO** [comment]
@stardrift1, one can still do HW-based signatures for protecting CMP messages etc. using the (meanwhile deprecated) engine mechanism. Even in this case `ctx->pkey` contains a valid pointer to an `EVP_PKEY` structure with some data representing the private key held in a HW token.

**Comment by stardrift1** [comment]
@DDvO Is there any demo about how to do this?

**Comment by DDvO** [comment]
> @DDvO Is there any demo about how to do this?

Here is a simple example:
```
apps/openssl cmp -cmd cr -config openssl.cnf -cert <cert-for-keyid> -key engine:<keyid> -engine pkcs11
```
where of course you need to properly set up the engine, in this case one with the name pkcs11>,
and use the right <keyid> to refer to the private key managed by the engine.
You should find with Google various engine setup instructions.
