### ISSUE TITLE
why openssl use ecb mode for CTR-Drbg?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12488]
Hi,
   I am reading the DRBG code and I found drbg use ecb mode  for CTR-DRBG, why didn't use CTR mode or CBC mode for this? 
https://github.com/openssl/openssl/blob/a47dd08d6cacc64536c2f57e0f0aee03dcfaab3d/crypto/rand/drbg_ctr.c#L429

**Comment by slontis** [comment]
Google Sp800-90

**Comment by paulidale** [comment]
Closing since this has been answered.
