### ISSUE TITLE
Incorrect handling of multithreaded reference counters

### ISSUE THREAD

**Issue by wbl** [openssl/openssl#1248]
The idiom this codebase uses for shared reference counters is to use atomic operations with the relaxed ordering to change the reference count, and when it drops to zero, free it, including the space the reference counter was in. This is not a safe pattern: acquire_release semantics should be used instead. (There is a possibility of the free happening while the object is still used by another thread due to memory access reorderings)

**Comment by richsalz** [comment]
Can you show code for an upref/release?  I think your concern is more theoretical than practical.  (Might need a few volatile sprinklings around.)

**Comment by wbl** [comment]
Volatile does not introduce ordering in multithreaded programs. I think it's as simple as changing from relaxed to acquire_release in the atomic increment. The only synchronization actions are locks and atomic operations which are not relaxed, but I am by no means an expert on how to use atomics other then "Don't"!

I agree in practice this is unlikely to be visible, especially on CPUs with strong memory models. It's really a minor hiccup I happened to notice while looking at some code.

**Comment by richsalz** [comment]
Ping @dot-asm ?

**Comment by richsalz** [comment]
ping @dot-asm   Shoudl we just  close this?

**Comment by kaduk** [comment]
I think this was addressed via #1500, so closing.
