### ISSUE TITLE
Is ossl_prov_util_nid_to_name() needed?

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#12484]
The fips provider implements this, as does nid_to_name.c..

I can not see where this is called from, so the original intention is either lost or no longer needed.
If needed then the list needs to be checked/updated.

**Comment by levitte** [comment]
Hmmm, does that mean that we've ended up calling OBJ_nid2sn() somewhere in the code that ends up in the FIPS module?  Or did we end up abstracting that away somehow (the signature code in providers/implementations/signature does a lot of local nid to name conversion, maybe that was supposed to call ossl_prov_util_nid_to_name?)

**Comment by paulidale** [comment]
This isn't used and should be removed.  It is also documented in internal/man3.
