### ISSUE TITLE
Strange behaviour with openssl genrsa going to infinite loop 

### ISSUE THREAD

**Issue by smartproductlabs** [openssl/openssl#12502]
Using CentOS 7 Openssl 1.0.2k version

The below commands leads to infinite loop 
"openssl genrsa -out private_key.pem 16" 

The print like below starts and it never ends. The same command works for 32 and higher numbers. 
Generating RSA private key, 16 bit long modulus
.+++++++++++++++++++++++++++
.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.+++++++++++++++++++++++++++.++++++++++++++++++++++++

**Comment by kroeckx** [comment]
Why are you trying to create a 16 bit RSA key?

Newer versions will actually give you an error if you try to
create a key smaller than 512 bit, and even a 512 bit key provides
as a good as no security.

**Comment by paulidale** [comment]
1.0.2 is beyond support, this isn't going to be addressed.
