### ISSUE TITLE
3.0.0-alpha5: New dependency IPC::Cmd in util/perl/OpenSSL/config.pm

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#12501]
Commit a3310b182ca3952c2876792b35035b54a4c77713 introduced a new dependency on IPC::Cmd in config.pm. It is triggered by "use OpenSSL::config;" in Configure line 23.

On RHEL 7 the perl-IPC-Cmd rpm unfortunately has a few dependencies that are unwanted, like gdbm-devel and libdb-devel. Therefore it would be good to not rely on IPC::Cmd - or document its need in NOTES-Perl.md.

The full error is:

Can't locate IPC/Cmd.pm in @INC (@INC contains: /path/to/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /path/to/external/perl/Text-Template-1.56/lib) at /path/to/util/perl/OpenSSL/config.pm line 18.
BEGIN failed--compilation aborted at /path/to/util/perl/OpenSSL/config.pm line 18.
Compilation failed in require at /path/to/Configure line 23.
BEGIN failed--compilation aborted at /path/to/Configure line 23.

The calling file Configure also uses IPC::Cmd but has an eval-require construct to check for its existence and fallback code for the case it is missing. Maybe one can use the same approach in config.pm, or even move the code to some common place and use it in Configure and config.pm.

**Comment by romen** [comment]
Ping @levitte

**Comment by levitte** [comment]
According to [corelist](http://corelist.rpee.be/m/IPC::Cmd), IPC::Cmd has been around as a core perl module since v5.9.5.  That's within our requirements.  I was also careful to check that the function we use (`IPC::Cmd::can_run`) has been around long enough (I can at least trace it back to perl v5.10.1).

Why RHEL makes perl-IPC-Cmd on *devel packages*, I cannot answer.  I could understand that as *build* dependencies, but not for run-time package dependencies.

This sounds like a packaging problem more than a problem in our usage.  I can't see how our using it within our build parameters is a bug, sorry.
Maybe you could ask RH for an explanation on that (odd) package dependency?

**Comment by rainerjung** [comment]
Some history is in the following ticket:

https://bugzilla.redhat.com/show_bug.cgi?id=1129443

IPC::Cmd has a dependency on ExtUtils::MakeMaker which in turn needs perl-devel. That one includes header files which which include other headers from gdbm and db2.

In RHEL 8 they solved the issue by slightly adjusting IPC::Cmd: the onyl feature form MakeMaker that was used by IPC::Cmd was MM->maybe_command(). RHEL noticed this function was pretty simple and introduced a new module in RHEL 8, ExtUtils::MM::Utils. It contains the following comment:

These methods are copied from L<ExtUtils::MM_Unix>. Other operating systems
are not supported yet. The reason is this
L<a hack for Linux
distributions|https://bugzilla.redhat.com/show_bug.cgi?id=1129443>.

And the code is:

if (!exists $INC{'ExtUtils/MM.pm'}) {
    *MM::maybe_command = *ExtUtils::MM::maybe_command = \&maybe_command;
}

sub maybe_command {
    my($self,$file) = @_;
    return $file if -x $file && ! -d $file;
    return;
}

1;

It is fine for me to apply this fix locally to my RHEL 7 build environment for OpenSSL. At least the situation is well-documented now. So if you like, you might close this issue. Thanks for looking at it!

**Comment by levitte** [comment]
Nice investigation!  I'm glad you could fix it locally.
