### ISSUE TITLE
Whether to initiate renegotiation after the SSL connection is established 

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#12513]
Is SSL renegotiation initiated after the SSL connection is established? 
Renegotiation is initiated by the client or server after the SSL_renegotiate and SSL_do_handshake interfaces are invoked, but not after a long connection. Even if the client or server replaces the certificate after a connection is established, the renegotiation cannot be initiated. 

I don't know if I understand correctly, ask for guidance.

**Comment by mattcaswell** [comment]
Renegotiation is never automatically initiated by OpenSSL. It only occurs after an explicit request from the application (e.g. via `SSL_renegotiate`).
