### ISSUE TITLE
Various Coverity Issues

### ISSUE THREAD

**Issue by ashman-p** [openssl/openssl#12529]
Hi, We have found and addressed some of the static analysis issues found in our Coverity builds OpenSSL 1.1.1.
Checking if SA issues are being in 1.1.1 are being addressed and also if a PR for our fixes would be accepted?
Most of these are memory leaks and then a few other issues. diffs attached.
[coverity-diff.txt](https://github.com/openssl/openssl/files/4974073/coverity-diff.txt)

Thanks,
Norman

**Comment by kaduk** [comment]
It would be easier to review them as a PR, yes.  I expect at least most of them to be acceptable (but possibly in need of edits).
Please note that you will need to sign the CLA in order for the PR to be accepted.

**Comment by ashman-p** [comment]
> It would be easier to review them as a PR, yes. I expect at least most of them to be acceptable (but possibly in need of edits).
> Please note that you will need to sign the CLA in order for the PR to be accepted.

Thank you. PR @ 
https://github.com/openssl/openssl/pull/12531

**Comment by kroeckx** [comment]
I think this can be closed?

**Comment by t8m** [comment]
I agree, closing.
