### ISSUE TITLE
Release Timelines of OpenSSL3.0

### ISSUE THREAD

**Issue by raveendrapadala** [openssl/openssl#12539]
OpenSSL Team,

As said in the releases [link](https://www.openssl.org/policies/releasestrat.html), Beta1 is expected by 02-06-2020. 

```
The following alpha and beta releases for OpenSSL 3.0 are currently scheduled. Note that these dates are subject to change and alpha or beta releases may be inserted or removed as required:
- alpha1, 2020-03-31: Basic functionality plus basic FIPS module
- alpha2, 2020-04-21: Complete external provider support (serialization, support for new algs, support for providers which only include operations in a class)
- alpha3, 2020-05-21: Aiming to test the API completeness before beta1 freezes it)
- beta1, 2020-06-02: Code complete (API stable, feature freeze)
- betaN: Other beta releases TBD
- Final: 2020 early Q4
```

As per latest  update from [github](https://github.com/openssl/openssl/releases) alpha releases are ongoing(i.e.,alpha5). so would like to know what could be the probable revised dates for beta release. will there be any change in the Final release dates?  atleast ballpark figure.

**Comment by paulidale** [comment]
End of August is the current beta target.
Final early Q4 hopefully.

**Comment by raveendrapadala** [comment]
Thanks for the update.
