### ISSUE TITLE
Can the Default provider dynamically loaded?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12532]
Can the Default provider dynamically loaded?And the dynamically loadable provider's  supportting function can be load dynamically or just load all supportting function of them when load the  dynamically loadable module?

**Comment by paulidale** [comment]
> Can the Default provider dynamically loaded?

Not currently because it is built into libcrypto.  However, it doesn't have to be loaded into a library context and if it isn't it won't be used.  The default library context will load it unless something else has been loaded first.  I.e. by default it will load but it is straightforward to prevent this.


> And the dynamically loadable provider's supportting function can be load dynamically or just load all supportting function of them when load the dynamically loadable module?

I'm not sure what you are asking here.

**Comment by stardrift1** [comment]
> I'm not sure what you are asking here.

that's mean when i load the dynamically loadable provider(such as Legacy provider),if i load all the algorithms it supports?Or i can choose one specific algorithm to load when use the EVP_××_fetch（）function?

**Comment by paulidale** [comment]
The provider is opened using dlopen() with `RTLD_LAZY` flag.

When a provider is loaded all of its algorithms become available but none will be accessed until asked for using the EVP_xx_fetch() functions.  It would be possible to write a provider that used additional loadable modules for the algorithms it implements and they would be loaded on demand.  The OpenSSL supplied providers don't do this -- if you load the legacy provider, all of its algorithms will be memory mapped.

**Comment by stardrift1** [comment]
> if you load the legacy provider, all of its algorithms will be memory mapped.

you mean The provider is opened using dlopen() with RTLD_LAZY flag,but all the function of it have loaded to the memory before the main function exec using the dlsym() function?

**Comment by stardrift1** [comment]
I just want to know if i can reduce the size of the library when i just want use some specific algorithms.

**Comment by levitte** [comment]
You can disable algorithms when configuring openssl before building. We've also talked about a finer algorithm selector, but that hasn't been implemented yet.

We have had some vague talks of dividing up the default provider into multiple smaller modules. That won't happen for openssl 3.0, though, but may happen in the future.

**Comment by stardrift1** [comment]
> You can disable algorithms when configuring openssl before building. 

the default provider's algorithms can be disabled too?

**Comment by levitte** [comment]
Read INSTALL.md
