### ISSUE TITLE
can i add some function CONFORMING TO FIPS186-4 Section B.3.3 Generation of Random Primes that are Probably Prime for fip test?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12546]
I want to gen RSA KEY CONFORMING TO FIPS186-4 Section B.3.3 and test it ,how can i do?

**Comment by stardrift1** [comment]
> _No description provided._

**Comment by slontis** [comment]
You cant. We implement B.3.6 instead.
The standards do not require you to implement all approved implementations.

**Comment by mattcaswell** [comment]
Question was answered so closing.
