### ISSUE TITLE
OpenSSL 1.1.1 ZOS unable to produce *.so binaries.

### ISSUE THREAD

**Issue by RJGEYER1** [openssl/openssl#12542]
I used the information provided via  https://wiki.openssl.org/index.php/Configuration_%22packages%22 and was able to complete a build with no 'compile' errors. However, there were no *.so files generated. Our implementation requires shared libraries. When I run '''./Configure OS390-Unix shared no-asm no-tests''' -which we have been running in our code line since we started using OpenSSL with 0.9.7 and recently with or last upgrade to 1.0.2u. Due to the upcoming end of 1.0.2 extended EOL we are in the process of moving to 1.1.1e. I noticed this message was returned from Configure:

**The options 'shared', 'pic' and 'dynamic-engine' aren't supported on this
platform, so we will pretend you gave the option 'no-pic', which also disables
'shared' and 'dynamic-engine'.  If you know how to implement shared libraries
or position independent code, please let us know (but please first make sure
you have tried with a current version of OpenSSL).**

Is there any way around this restriction? I am wondering why/how previous release were able to generate *.so files, but, now in 1.1.1e is has become technically infeasible.

**Comment by mattcaswell** [comment]
@p-steuer contributed those notes on the Wiki so perhaps he can help answer this question.

**Comment by p-steuer** [comment]
This sounds that the newer config system tries you to keep you from doing something you want to do anyway. Have you tried to just remove the corresponding check from the configure scripts ?

**Comment by RJGEYER1** [comment]
The solution seems to be to simply add:
shared_target    => "OS390-shared"
to the zos-unix.conf

Perhaps someone can update the above wiki to reflect this as an option. It would also be useful to relay the appropriate compiler options for Debug vs Optimized binaries and 32bit vs 64 bit binaries.

**Comment by mattcaswell** [comment]
I made the suggested edit in the wiki. If you could check I did it right since I have no way of testing it, that would be appreciated.
