### ISSUE TITLE
Naming convention and the Wix installer

### ISSUE THREAD

**Issue by lakeweb** [openssl/openssl#12553]
This is not necessarily a bug so I didn't post there. The blame may well land in the laps of the Wix developers. But Wix will rename files with dashes, (libcrypto-3.dll) to files with underscores. (libcrypto_3.dll) So, of course when my app is installed the dll is not found.

I'm digging around in the make system to see about just fixing for myself and reproducing the library with underscored or just no dash names. I just thought you would like to know. As it came up for me I can imagine it will eventually show for others that move to version 3. Then maybe not as there may not be many folks using Wix to package native code apps.

And thanks for the great library! It was painless to build and seems to work beautifully with boost::beast.

If I did have a question, just where in the build system would I change the names of the libs. For now I'm just static linking as we are in beta of this release and I can live with the bloat.
Best, Dan.

**Comment by levitte** [comment]
The name is governed by platform dependent perl code.  The exact line to change in this case is this:

https://github.com/openssl/openssl/blob/5cd9962272388fc9a51711495a8c6a3f230ab5ce/Configurations/platform/Windows.pm#L49

But yeah, I would talk to Wix about this if I was you.  Such renaming is very annoying.

**Comment by lakeweb** [comment]
Thank you levitte.
I ended up with a different fix as I may run into this with other files. I just added a tool to my deployment chain that digs into any exe and corrects it there. I will post the the Wix group. The solution, in case someone else want to do it this way. It is a bit cheesy but an in house tool. The other thing that might be better is than while/if NSIS has write permission in the program folder, just let it rename the libs correctly. 
Best, Dan.

> int main()
> {
>     bfs::path file(arg[1]);
>     auto str = read_file(file);
>     auto where = str.find("libcrypto-3");
>     if (where == std::string::npos)
>          return -1;
>     str.replace(where, 11, "libcrypto_3");
>     where = str.find("libssl-3");
>     if (where == std::string::npos)
>          return -1;
>     str.replace(where, 8, "libssl_3");
>     std::ofstream out(file.string(), std::ios::binary);
>     out.write(str.data(), str.size());
>     return 0;
> }
>
