### ISSUE TITLE
SSL_get1_peer_certifiate not declared in headers for openssl-3.0.0-alpha5

### ISSUE THREAD

**Issue by EmericBr** [openssl/openssl#12556]
Compiling the haproxy software I got this issue:

./openssl-3.0.0-alpha5/include/openssl/ssl.h:1713:37: warning: implicit declaration of function ‘SSL_get1_peer_certifiate’ [-Wimplicit-function-declaration]
 \#   define SSL_get_peer_certificate SSL_get1_peer_certifiate

A macro is available in ssl.h, it maps  SSL_get_peer_certificate on SSL_get1_peer_certifixate, but this last function is not declared.

**Comment by mattcaswell** [comment]
This was fixed recently by 43b3ab6f8.
