### ISSUE TITLE
 typo in  'openssl enc -help' output

### ISSUE THREAD

**Issue by stopped** [openssl/openssl#1256]
$ openssl  version         
OpenSSL 1.1.0-pre5 (beta) 19 Apr 2016

$ openssl  enc -help 2>&1|grep kfile  
 -kfile infile  Fead passphrase from file

s/Fead/Read/

**Comment by richsalz** [comment]
already fixed:
; g show 5507b9610af8ba521ac10488b5cb6d6c6f1c69fa
commit 5507b9610af8ba521ac10488b5cb6d6c6f1c69fa
Author: Kurt Cancemi <kurt@x64architecture.com>
Date:   Tue May 17 01:47:28 2016 -0400

    Fix typos in apps/enc.c
    Reviewed-by: Richard Levitte <levitte@openssl.org>
    Reviewed-by: Matt Caswell <matt@openssl.org>

**Comment by stopped** [comment]
Great!
