### ISSUE TITLE
List of Message Authentication Code

### ISSUE THREAD

**Issue by felipin85** [openssl/openssl#12564]
Hi, 

I'm trying to calculate a message authentication code (MAC) and I got the same error all time. I've tried the commands of:

https://www.openssl.org/docs/manmaster/man1/openssl-mac.html

My first attempt was:

openssl list -mac-algorithms

And I got the next error: "list: Option unknown option -mac-algorithms". 

My second attempt was:

openssl mac -macopt cipher:AES-128-CBC \ -macopt hexkey:77A77FAF290C1FA30C683DF16BA7A77B \ -in encoded.data.txt CMAC

And I got the next error: "Invalid command '-mac'; type "help" for a list."

Does anyone have any idea why this is happening to me?

PD: I've trying in macos, windows and ubuntu, and always I get the same result.

Thanks

**Comment by paulidale** [comment]
What version of OpenSSL are you running?  `openssl version`
MAC support is only available on the master branch.

**Comment by felipin85** [comment]
Hi, 

In windows , for example, OpenSSL 1.1.1g  21 Apr 2020. In Ubuntu, OpenSSL 1.1.1f  31 Mar 2020.

Thanks a lot

**Comment by paulidale** [comment]
Version 1.1.1 doesn't that option.  Try [this version](https://www.openssl.org/docs/man1.1.1/man1/list.html) of the man page instead.

**Comment by felipin85** [comment]
Ahhh,, ok! And, do you have any page where explain how install from master branch?

Thanks and sorry for the inconveniences
