### ISSUE TITLE
EVP_default_properties_is_fips_enabled() not working as expected

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12565]
This issue is reproduced from the following openssl-users post:

https://mta.openssl.org/pipermail/openssl-users/2020-July/012811.html

I'm struggling to understand how `EVP_default_properties_is_fips_enabled()` works. I cannot get this function to return nonzero unless I first call either `EVP_default_properties_enable_fips()` or `EVP_set_default_properties()`, even when the config file sets default_properties to enable fips.

Also, the return value of this function doesn't seem to have any effect on which provider gets selected (which I think is what issue #11594 describes?).

My config file has the following:

````
[openssl_init]
providers = provider_sect
alg_section = alg_sect

[provider_sect]
fips = fips_sect
default = default_sect

[default_sect]
activate = 1

[alg_sect]
default_properties = fips=yes

.include /path/to/fips.cnf
````

I understand this to mean both the default provider and the fips provider will be loaded into the default context, and both of these providers will be activated. I also see that:

````
EVP_MD_fetch(NULL, "sha256", NULL);
````

returns a pointer which `EVP_MD_provider()` confirms as being from the fips provider (as expected). Changing this to "fips=no" in the config file results in `EVP_MD_fetch()` returning `EVP_MD` from the default provider, again as expected. However, in both cases, `EVP_default_properties_is_fips_enabled()` always returns zero. I don't see anything in #11594 that would explain this.

Calling `EVP_default_properties_enable_fips(NULL, 1)` results in `EVP_default_properties_is_fips_enabled() `returning 1, but this does not appear to override the `fips=no` from the config file during EVP_MD_fetch() (which is what I believe #11594 describes).

Is the result of `EVP_default_properties_is_fips_enabled()` supposed to take into account the default properties specified in the config file? I don't see it doing that. Also, regarding #11594, if default properties are currently still broken, why do those in the config appear to work properly?

And finally the burning question: Any ETA on a fix? :-) :-) :-)

**Comment by mattcaswell** [comment]
I can't actually reproduce this. I tried with this code:

````
#include <stdio.h>

#include <openssl/provider.h>
#include <openssl/evp.h>


int main(void)
{
    EVP_MD *md = EVP_MD_fetch(NULL, "SHA256", NULL);

    printf("Provider used is %s\n", OSSL_PROVIDER_name(EVP_MD_provider(md)));

    printf("Is fips enabled is %s\n", EVP_default_properties_is_fips_enabled(NULL) ? "yes" : "no");

    return 0;
}
````

And this config file:
````
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect
alg_section = alg_sect

[provider_sect]
fips = fips_sect
default = default_sect

[default_sect]
activate = 1

[alg_sect]
default_properties = fips=yes

.include fipsmodule.cnf
````
And I got this output:

````
Provider used is fips
Is fips enabled is yes
````
If I change the `default_properties` value to say `fips=no`, I instead get this output:

````
Provider used is default
Is fips enabled is no
````

I'm wondering whether your config file is working at all?

I did make a couple of tweaks to your config file to get it to work:

1) Added the line "openssl_conf = openssl_init" at the beginning

2) replaced "/path/to/fipsmodule.cnf" with just "fipsmodule.cnf" and ensured my OPENSSL_CONF_INCLUDE environment variable pointed at the relevant directory. I'm slightly surprised that an absolute include path did not seem to work (and our wiki shows examples with absolute paths)...but it didn't seem to for me. I've not investigated that further to see if there is some other issue there.

Part of the problem here is that OpenSSL is silent if it fails to parse the config file.

**Comment by tomiii00** [comment]
My config file has "openssl_conf = openssl_init" at the top. I inadvertently omitted that in my original email--sorry about that. I do have an absolute path to fips.cnf in the .include statement and that does appear to work for me.

I tried your test program and I got the same result at you did. However, further investigation reveals that the difference between your test program and mine is that you called EVP_MD_fetch() first. My test program calls EVP_default_properties_is_fips_enabled() first. The difference appears to matter.

```
#include <stdio.h>
#include <openssl/provider.h>
#include <openssl/evp.h>


int main(void)
{
    printf("Is fips enabled is %s\n", EVP_default_properties_is_fips_enabled(NULL) ? "yes" : "no");

    EVP_MD *md = EVP_MD_fetch(NULL, "SHA256", NULL);

    printf("Provider used is %s\n", OSSL_PROVIDER_name(EVP_MD_provider(md)));

    printf("Is fips enabled is %s\n", EVP_default_properties_is_fips_enabled(NULL) ? "yes" : "no");

    return 0;
}
```

Running this with "default_properties = fips=yes" gives me the following output:

```
Is fips enabled is no
Provider used is fips
Is fips enabled is yes

```
Interesting.

**Comment by mattcaswell** [comment]
Aha! That gives me a theory: We load the config file lazily. The first time anything in OpenSSL attempts to read something that might have been configured we check whether we've loaded the config file yet and load it first if not. My guess is that the EVP_default_properties_is_fips_enabled() function call is somehow not triggering that check. Therefore when it checks to see if fips is enabled the config file hasn't been loaded yet and the answer is "no". Later after the fetch, the config file has been loaded and the answer changes to "yes".

**Comment by tomiii00** [comment]
Indeed, strace confirms that the config file is not opened/read until after that first printf(). So that explains it. Thanks.

**Comment by mattcaswell** [comment]
Fix in #12567. Marked as WIP because I also need to write a test. But please try it out and let me know if it fixes your issue.

**Comment by tomiii00** [comment]
The changes in [#12567](https://github.com/openssl/openssl/pull/12567) seem to fix the issue for me. EVP_default_properties_is_fips_enabled() now returns the expected result whether or not EVP_MD_fetch() is called first.

**Comment by mattcaswell** [comment]
Great. Thanks for the feedback.
