### ISSUE TITLE
EVP_get_cipherbyname("sms4")

### ISSUE THREAD

**Issue by wangfugui-art** [openssl/openssl#12590]
I want to get zhe SM4 algorithm,which para should i choose to replace the "sms4". And what is the table about algorithm and character string.

**Comment by paulidale** [comment]
These are the options: `SM4-ECB`, `SM4-CBC`, `SM4-OFB`, `SM4-CFB`, `SM4-CFB1`, `SM4-CFB8`, `SM4-CTR`.  Which one you choose depends on the [cipher mode](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation) you want to use.
