### ISSUE TITLE
Removal of CRYPTO_LOCK breaks legacy locking callbacks

### ISSUE THREAD

**Issue by jeltz** [openssl/openssl#1260]
When the new threading API was added CRYPTO_LOCK and related constants were removed (commit 2e52e7df518d80188c865ea3f7bb3526d14b0c08). This breaks third-party software which has a  locking callback and looks at the `mode` parameter of the callback.

I think if we should keep the CRYPTO_set_locking_callback() function for compatibility reason we should also keep the commonly used defines for the callbacks.

For an example see [the following callback in PostgreSQL](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/interfaces/libpq/fe-secure-openssl.c;h=f6ce1c7a13d8ee47a093eb5f407208a77a769908#l753).

**Comment by jeltz** [comment]
This only affects the 1.1 pre-release version.

**Comment by richsalz** [comment]
Well, it will also affect 1.1 post-release version :)

I am not sure if there will be any solution other than ifdef's in the postgres code.  The old locking callback stuff was a hack, and was only semi-supported.  I know that doesn't really help.

Maybe @mattcaswell has some other thoughts?  Or @ghedo ?

**Comment by levitte** [comment]
`CRYPTO_set_locking_callback` is useless in 1.1.0, it's one of this interfaces we consiously removed so as not to fool users to keep using those.

Cheers,
Richard

**Comment by jeltz** [comment]
@levitte `CRYPTO_set_locking_callback` is still there as a noop macro, and I personally think the macro is not very useful from a compatibility standpoint without also having the defines commonly used by people implementing the callback.

**Comment by g10guang** [comment]
So if we use openssl 1.0.2, we set **2** callbacks:

```c
CRYPTO_set_id_callback((unsigned long (*)())thread_id);                                         
CRYPTO_set_locking_callback((void (*)(int, int, const char *, int))lock_callback);
```

And if we use openssl 1.1.1, we just need to set **1** set callback? like below:

```c
CRYPTO_THREADID_set_callback((unsigned long (*)())thread_id);
```

Merge: 

```c
#if OPENSSL_VERSION_NUMBER >= OPENSSL_VERSION_1_0_0                                                    
    CRYPTO_THREADID_set_callback((unsigned long (*)())thread_id);                                      
#else                                                                                                  
    CRYPTO_set_id_callback((unsigned long (*)())thread_id);                                            
    CRYPTO_set_locking_callback((void (*)(int, int, const char *, int))lock_callback);
#endif
```

Right?

**Comment by mattcaswell** [comment]
No. You don't need to set any thread callbacks in 1.1.0 or 1.1.1. `CRYPTO_THREADID_set_callback` is also a no-op in those versions.

**Comment by nugend** [comment]
Hi, I'm having an issue with this. This was made a no-op in the header, right? That should mean that anything compiled against the old header is broken when linked against a newer verison of the library, correct?

Is there a specific release where this was still defined in the library?

**Comment by richsalz** [comment]
Compiling against headers and linking to a library that wasn't built with the same headers is risky, and if there were no specific ABI promises made, pretty much guaranteed to not work. For 1.0.2 and 1.1.0 there is no compatibility promise.

The last time the code was present was in the 1.0.2 release stream.

**Comment by nugend** [comment]
Ah, I didn't realize that Semver was not being followed: https://github.com/openssl/openssl/issues/5042

Good to know

**Comment by levitte** [comment]
We will be much closer to semver from version 3.0.

**Comment by alexlehm** [comment]
I came to this issue while trying to build an old version of nagios-plugins with a current openssl and that failed because it was not finding the CRYPTO_lock method in libcrypto.o even though it is not used in the code. I replaced the check in the configure script with CRYPTO_THREAD_lock_new, then it worked fine.

**Comment by beef9999** [comment]
> `CRYPTO_set_locking_callback` is useless in 1.1.0, it's one of this interfaces we consiously removed so as not to fool users to keep using those.
> 
> Cheers, Richard

The removal of `CRYPTO_set_locking_callback` lacks documents. We can only find some docs of that on 1.0.2.
https://www.openssl.org/docs/man1.0.2/man3/CRYPTO_lock.html
