### ISSUE TITLE
EVP_PKEY_assign() bad input handling

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#12619]
I happen to have a test that verifies EVP_PKEY_assign_EC_KEY() & EVP_PKEY_assign_RSA() fail gracefully if passed a NULL pointer for the key.

It appears that sometime during 3.0.0 development the test broke (crashes) for the EC_KEY case only.

It looks to be a simple case of an unchecked de-reference.

This isn't an especially pressing issue given it's a negative testcase anyway, and I know there are many cases throughout the library where input pointers are not checked. This case jumped out both because it used to work & because different behavior is now observed depending on the key type.

**Comment by mattcaswell** [comment]
Yep, looks like a bug in `EVP_PKEY_assign` which now has some special case handling for EC keys.
