### ISSUE TITLE
GitHub and Travis Job Infos out-of-sync?

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#12616]
@openssl/otc,

recently, Travis Jobs started to take a very long time to complete. In some cases I checked the details and I noticed that the GitHub Job details page of the pull request seems to be out-of-sync with Travis': it shows jobs in created state (yellow), even though Travis shows them as completed (green).

Does anyone of you have an idea what's wrong with Travis? Is it possible that the Travis states are not reported back to GitHub properly?

Here an example:

### [GitHub Job details](https://github.com/openssl/openssl/pull/12407/checks?check_run_id=964502938)

![image](https://user-images.githubusercontent.com/11467854/89744232-40399600-daab-11ea-842a-8a01436470c7.png)

### Travis Job details

![image](https://user-images.githubusercontent.com/11467854/89744235-47f93a80-daab-11ea-9506-9dea3a806452.png)

**Comment by mspncp** [comment]
Meanhwile, all Travis Jobs have completed,

https://travis-ci.com/github/openssl/openssl/jobs/370145468
https://travis-ci.com/github/openssl/openssl/jobs/370145469
https://travis-ci.com/github/openssl/openssl/jobs/370145470
https://travis-ci.com/github/openssl/openssl/jobs/370145471
...
https://travis-ci.com/github/openssl/openssl/jobs/370145487
https://travis-ci.com/github/openssl/openssl/jobs/370145488
https://travis-ci.com/github/openssl/openssl/jobs/370145489
https://travis-ci.com/github/openssl/openssl/jobs/370145490

but GitHub still thinks they are running

https://github.com/openssl/openssl/pull/12407/checks?check_run_id=964502938

**Comment by mspncp** [comment]
Correction: a single job is stuck in the 'queued' state:

https://travis-ci.com/github/openssl/openssl/jobs/370145477

![image](https://user-images.githubusercontent.com/11467854/89753045-041c2a80-dad7-11ea-817a-16654aac17ab.png)

**Comment by mattcaswell** [comment]
Looks like s390...so is access to that  platform slowing things down?

**Comment by mspncp** [comment]
> Looks like s390...so is access to that platform slowing things down?

This might be a possible reason. @p-steuer any ideas what is causing the problem?

**Comment by paulidale** [comment]
The S390 build has been taking a very long time or (more commonly) timing out for a while now.

**Comment by p-steuer** [comment]
On s390 15-test_genec.t curently fails wiith errors like:
> not ok 1 - genpkey EC params Oakley-EC2N-3 with ec_param_enc:'explicit' (text) # TODO Currently not supported

So the comment reads as if this is expected atm.

However, since the job seems to timeout before even started, this looks unrelated. Let me see if i can find a contact for public s390 travis.

**Comment by slontis** [comment]
> So the comment reads as if this is expected atm.

This is an expected - it is a todo so it just prints without causing a real error.

**Comment by mspncp** [comment]
Travis is history now.
