### ISSUE TITLE
`openssl s_client` improvement

### ISSUE THREAD

**Issue by okudayukiko** [openssl/openssl#12617]
Automatically use TLS 1.0-1.2 protocol if use `-cipher` option.
`openssl version` (in Ubuntu 20.04)
`OpenSSL 1.1.1f 31 Mar 2020`
`openssl s_client -cipher ECDHE-RSA-CHACHA20-POLY1305 localhost:443`
`……`
`New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384`
`……`
`openssl s_client -cipher ECDHE-RSA-CHACHA20-POLY1305 -tls1_2 localhost:443`
`……`
`New, TLSv1.2, Cipher is ECDHE-RSA-CHACHA20-POLY1305`
`……`

**Comment by mattcaswell** [comment]
I don't think this is desirable at all. It is entirely reasonable to want to configure the TLSv1.2 cipher list and yet still want to accept TLSv1.3 connections. In fact I would say that's more common than not wanting TLSv1.3 connections. Until you connect to a server you don't necessarily know what the server supports.
