### ISSUE TITLE
[fips][cli][dsa] Sign/verify something with a non-FIPS key should fail in FIPS mode

### ISSUE THREAD

**Issue by romen** [openssl/openssl#12627]
This was triggered by the tests in #12291 .

~~~
# ------------------------------------------------------------------------------
../../util/wrap.pl ../../apps/openssl dgst -sha256 -sign DSA.nonfips.priv.pem -out DSA.nonfips.fail.sig ../../providers/fips.so => 0                                                                             
    not ok 11 - DSA: Sign something with a non-FIPS key (should fail) # TODO see issues #12xxx
# ------------------------------------------------------------------------------
    #   Failed (TODO) test 'DSA: Sign something with a non-FIPS key (should fail)'
    #   at ../../home/tuveri/repos/ossl_committer/test_cli_fips/test/recipes/20-test_cli_fips.t line 112.                                                                                                        
Verified OK
../../util/wrap.pl ../../apps/openssl dgst -sha256 -verify DSA.nonfips.priv.pem -signature DSA.nonfips.sig ../../providers/fips.so => 0                                                                          
    not ok 12 - DSA: Verify something with a non-FIPS key (should fail) # TODO see issues #12xxx
20-test_cli_fips.t .. ok   -----------------------------------------------------
~~~

**Comment by romen** [comment]
Ping @slontis

**Comment by slontis** [comment]
I dont think dgst has even been tested to be using the correct non legacy paths.
I had to update genpkey to get that to work correctly..
Thanks for the info - it might be a while before I get to look at this.

**Comment by romen** [comment]
I am not sure the issue is limited to `dgst` though, I would expect the APIs used by `dgst` to fail earlier when trying to compute operations that shouldn't work in FIPS.

Assuming the library is operating in FIPS mode:
- When the deserializer parses the non-FIPS key, shouldn't it fail to create a key object?
- When `sign` is passed a non-FIPS key object, shouldn't it fail?
- When `verify` is passed a non-FIPS pubkey object, shouldn't it fail? (this is borderline, some use cases may want to be able to verify legacy signatures with a warning, other might want to fail)

If we only "fix" `dgst` to do extra things in FIPS mode we are sidestepping the problem, and external applications that want to operate in FIPS mode might not rely on openssl failing to do non-FIPS things!

**Comment by slontis** [comment]
If it is actually using fips mode the answer is yes.. When I get time I will look at it.

**Comment by slontis** [comment]
Securitychecks have also been added to evp_test that target fips
