### ISSUE TITLE
TLS regression

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#12634]
Server:
```
openssl s_server -www -cert localhost_rsa_1024/cert.pem -key localhost_rsa_1024/seckey.pem -cipher ECDHE-RSA-AES256-SHA -tls1
```

Client:
```
openssl s_client -connect localhost:4433 -CAfile sslCA/cacert.pem -verify_return_error -verify 1 -state -cipher ECDHE-RSA-AES256-SHA
```

Server stderr:
```
0071BFB54D7F0000:error::SSL routines::no suitable signature algorithm:ssl/t1_lib.c:3329:
```

Client stderr:
```
verify depth is 1
CONNECTED(00000003)
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL3 alert read:fatal:internal error
SSL_connect:error in error
0071ECDD2E7F0000:error::SSL routines::tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1615:SSL alert number 80
```
Previous tests were against alpha2

**Comment by t8m** [comment]
Does TLS1 mandate SHA1 signatures? What if you use @SECLEVEL=0:ECDHE-RSA-AES256-SHA for cipher on both sides?

**Comment by beldmit** [comment]
Yes, it does the trick. Thanks!

If this is the desired behavior, I can just fx my tests and close this issue.

**Comment by t8m** [comment]
Yes, IMO it is desired because SHA1 was degraded (rightfully) to SECLEVEL 0 for signatures.
The question is whether there should be a server side error if you try to start up TLS1 server without SECLEVEL=0.
@kroeckx @mattcaswell - any opinion?

**Comment by mattcaswell** [comment]
We already do a check to confirm that we have ciphersuites available that are suitable for use with the max available TLS version:

https://github.com/openssl/openssl/blob/31d2daecb384475da13c4bf7c76a2dde0077b2f2/ssl/statem/statem_lib.c#L105-L138

It seems reasonable that we should have an equivalent check for available sig algs.

**Comment by kroeckx** [comment]
ECDHE-RSA-AES256-SHA is no longer allowed by default, because it
uses SHA1. It will only work when you lower the security level to
0.

**Comment by richsalz** [comment]
If SHA1 is completely disabled except when SECLEVEL is zero, that is too broad.  SHA1 as the signature in a certificate is one thing. SHA as a message-integrity check is fine. Requiring someone to set SECLEVEL=0 to use TLS 1.1 makes them more insecure.

**Comment by mattcaswell** [comment]
> If SHA1 is completely disabled except when SECLEVEL is zero, that is too broad

The OMC disagrees:

> topic: The TLS security bit values for MD5, MD5_SHA1 and SHA1 should be set to
       39, 67 and 65 respectively in OpenSSL 3.0. Consequently TLS < 1.2 will
       be disallowed in the default security level

+1: 4
 0: 1
-1: 2

**Comment by richsalz** [comment]
This will not be the first time I disagreed with the OMC.  :)

**Comment by t8m** [comment]
There seems to be some confusion here - IMO ECDHE-RSA-AES256-SHA is NOT currently disabled in SECLEVEL 1 and rightfully so. The security bits values of SHA1 should not apply to MAC.

The reason the connection fails in the original report is that the SHA1 signatures are not allowed in SECLEVEL 1 and that is also rightfully so.

@beldmit if you drop the -tls1 option from the server side, does the connection work even without @SECLEVEL=0 ?

**Comment by beldmit** [comment]
Yes, it does

**Comment by t8m** [comment]
So @richsalz - the problem is not with the mac but with the TLS handshake signatures in 1.0 and 1.1. And I do not think we can allow them in SECLEVEL=1.

**Comment by richsalz** [comment]
Yes, I mis-typed.  Still disagree.  Oh well.

**Comment by beldmit** [comment]
So anyway the current behaviour looks controversial to me.

**Comment by t8m** [comment]
What is controversial on the fact that SHA1 signatures do not have the necessary strength to satisfy SECLEVEL 1?
Do we have any better option? Should we except and allow SHA1 protocol signatures if the negotiated protocol version is < TLS-1.2? That could be an option, however a fairly ugly one.

**Comment by richsalz** [comment]
This is not a signature, like a cert.  It is a protocol transcript that two parties participate in.

I didn’t say controversial, I just said I disagree.

**Comment by beldmit** [comment]
I suspected a controversy in fact that we establish a connection after removing `-tls1` option, but now I see that we establish the TLS 1.3 session ignoring the `-cipher` option.

**Comment by beldmit** [comment]
So do I correctly understand that I should just fix the test specifying SECLEVEL=0?

**Comment by t8m** [comment]
And if you provide -tls1_2 option does it still fail?

**Comment by beldmit** [comment]
It works! Very strange :(

**Comment by t8m** [comment]
Not strange, it just confirms what I am saying, the SHA1 handshake digest is blocked not the use of HMAC-SHA1.

Anyway, for now I'd just specify SECLEVEL=0 in the test.

**Comment by beldmit** [comment]
For now, it will work, but the behavior should be at least tested...

**Comment by kroeckx** [comment]
We have tests that the connections fails at the default security
level but work when you set the security level to 0.

**Comment by beldmit** [comment]
Updated my tests. Thanks!
