### ISSUE TITLE
a2i_IPADDRESS() considers "1.2.3.4.test.example" as valid IPv4 address

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#12649]
The function ``a2i_IPADDRESS()`` converts an ASCII IP address to an ``ASN1_OCTET_STRING`` and returns NULL when the input string is not a valid IPv4 or IPv6 address. In CPython I use the function to check if a user-supplied hostname is a DNS name or an IP address and then call either ``X509_VERIFY_PARAM_set1_host`` or ``X509_VERIFY_PARAM_set1_ip``. To my surprise the function also considers a hostname as valid IPv4 address if the input string starts with a valid IPv4 address. It ignores additional content. The ``sscanf()`` call in ``ipv4_from_asc`` does not check that the string is terminated immediately after the last digit.

https://github.com/openssl/openssl/blob/master/crypto/x509/v3_utl.c#L1088-L1093

Afftected Python ssl code:

https://github.com/python/cpython/blob/fa5d7251987c70a9c5d58b59a0b36ac9287eaafa/Modules/_ssl.c#L862-L925

Python bug report: https://bugs.python.org/issue41556

**Comment by t8m** [comment]
Fixed by #16201 on master.
