### ISSUE TITLE
Question - Why does HMAC not support SHAKE128/256?

### ISSUE THREAD

**Issue by justablob** [openssl/openssl#12652]
Hey there! I was playing around with OpenSSL and noticed that HMAC doesn't support the SHAKE128 and SHAKE256 XOFs. Are there any reasons behind this? Anything in their specs that would disallow usage as a MAC?

**Comment by paulidale** [comment]
XOF is the issue.  There is no API to get a handle to the underlying digest to set the length.
Apart from that, I don't see a reason why XOF couldn't be supported.  The MAC code might need some modifications to late bind the output length (or it might not).

**Comment by kaduk** [comment]
Wouldn't it be better to use KMAC than HMAC(SHAKE)?
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf
