### ISSUE TITLE
const of "EVP_PKEY *pkey" in EVP_DigestSignInit

### ISSUE THREAD

**Issue by misery** [openssl/openssl#12686]
Looks like EVP_PKEY *pkey in EVP_DigestSignInit is used as read-only. Is it possible to add "const" for OpenSSL 3.0?

https://www.openssl.org/docs/man1.1.1/man3/EVP_DigestSignInit.html

**Comment by t8m** [comment]
In theory if you had stateful signatures the key used in the signature operation would have to be updated after the operation.
So perhaps better not although I do not see stateful signatures really useful.
