### ISSUE TITLE
How to export keying material using SSL_export_keying_material?

### ISSUE THREAD

**Issue by kamalthakur1** [openssl/openssl#12702]
I am trying to create one function to export keying material using SSL_export_keying_material. Below is the example code. 
SSL_export_keying_material is returns 0 and out variable is null. Not sure what am I doing wrong.

```
char* exportKeyMaterial(SSL *ssl_)
{
    /*
    int SSL_export_keying_material(SSL *s, unsigned char *out, size_t olen,
                                const char *label, size_t llen,
                                const unsigned char *context,
                                size_t contextlen, int use_context);
    */
 
    unsigned char *out;
    size_t olen, llen = 18, contextlen = 13;
    const char *label = "EXPORTER demo work";
    const unsigned char *context = "ignored value";
    int use_context = 0;
    int result;
    //char *result_str;
    result = SSL_export_keying_material(ssl_, out, olen, label, llen, context, contextlen, use_context);
    if(result == 1){
    }
    else{
        printf("%d\n", result);
        out = "failure";
    }

    return out;
}
```

**Comment by kamalthakur1** [comment]
When I call it before Handshake with ERR_print_errors_fp(stderr) in place I am getting below error:
140433579546368:error:0F073041:common libcrypto routines:CRYPTO_memdup:malloc failure:crypto/o_str.c:66:
140433579546368:error:1411C044:SSL routines:tls1_PRF:internal error:ssl/t1_enc.c:55:

When I call it after Handshake with ERR_print_errors_fp(stderr) in place I am not getting any error and the result is same.
I am not much aware of SSL lifecycle.

**Comment by mattcaswell** [comment]
You must only use this function *after* the handshake has occurred. As it says in the documentation:

"SSL_export_keying_material() derives keying material using the exporter_master_secret established in the handshake."

Therefore a handshake must have occurred first in order for this to work.

The documentation also says this:

"For a given SSL connection s, olen bytes of data will be written to out."

Where `out` and `olen` are the second and third parameters respectively. It is your responsibility to ensure that `out` points to a buffer that is at least `olen` bytes long. However in your code sample above you do not initialise those values to anything. That is likely to cause the function to fail, or possibly even crash.

**Comment by kamalthakur1** [comment]
Thank you so much. Buffer was not in place.
