### ISSUE TITLE
Unit-test framework?

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12709]
I had a short look into the unit-test code.
Seems like no specific unit-test framework (like GTEST or any other) has been used.

There is extra code written for use-cases like:
1)Selecting/Running sub-tests of a main test
2)Running tests parallelly
3)Filtering tests

Any particular reason for this? As having a framework like GTEST or any other would ease the above use-cases

**Comment by paulidale** [comment]
The library is C.  I've not found a good C unit test library.  Suggestions?

**Comment by saddy-muchu** [comment]
I think we can still use GTEST (even though it makes more sense logically to use GTEST for testing C++ code)

**Comment by kaduk** [comment]
Anything used by OpenSSL would also need to be portable to the full set of platforms that OpenSSL supports, which severly limits the field of candidates.  (Note that, e.g., cmake is not usable for a build system since it does not support VMS.)

**Comment by paulidale** [comment]
OpenSSL can't use C++.  It needs to build for platforms where this doesn't exist.  They'd still want to run the unit tests.

**Comment by saddy-muchu** [comment]
Alright.
I guess i'm convinced.
