### ISSUE TITLE
Double free ctx->pctx && ctx->md_data when calling "EVP_DigestFinal" 

### ISSUE THREAD

**Issue by timeforasong** [openssl/openssl#12704]
When I use EVP_MD_CTX_init(ctx) which frees "ctx->pctx".The next step when calling "EVP_DigestFinal" frees pointer "ctx->pctx" which has already been freed.

I don't know if it's reasonable or if it's a bug?
why?Pls help me! Thank you

**Comment by paulidale** [comment]
Fixed in master.
