### ISSUE TITLE
sk_GENERAL_NAME_num not defined if compiled with no-deprecated

### ISSUE THREAD

**Issue by Tomenz** [openssl/openssl#12707]
Hallo,

i compiled the openssl libs on windows with VS2019 and no-deprecated in the configure.
After that, i recompiled my own app, how is useing the openssl libs.
I get an error that sk_GENERAL_NAME_num and sk_GENERAL_NAME_value are not defined.
If i compile the openssl libs without no-deprecated everything works well an sk_GENERAL_NAME_num  and sk_GENERAL_NAME_value are defined.

Here is my code:
```
        GENERAL_NAMES* pSubAltNames = reinterpret_cast<GENERAL_NAMES*>(X509_get_ext_d2i(cert, NID_subject_alt_name, nullptr, nullptr));
        if (pSubAltNames != nullptr)
        {
            int iCountNames = sk_GENERAL_NAME_num(pSubAltNames);
            for (int i = 0; i < iCountNames; ++i)
            {
                GENERAL_NAME* entry = sk_GENERAL_NAME_value(pSubAltNames, i);
                if (!entry) continue;

                if (entry->type == GEN_DNS)
                {
```

Is there a replacement in V3 for sk_GENERAL_NAME_num and sk_GENERAL_NAME_value ?

regards
Thomas Hauck

**Comment by kaduk** [comment]
There was some cleanup to, among other things, reduce the number of 'static inline' functions in the headers.
You should be able to put `DECLARE_STACK_OF(GENERAL_NAME)` in your own files that need the functions and have things work, IIUC.  More details are in the discussion on #10669

**Comment by kroeckx** [comment]
How do we know that we need to define that?

**Comment by rsbeckerca** [comment]
I am hoping that DEFINE_STACK_OF is redone at some point and thought it was going internal only. It is creating compile issues in some compilers (c99-nonstop).

**Comment by Tomenz** [comment]
DEFINE_STACK_OF(GENERAL_NAME) after the openssl header file worked👍

```
...
#include "openssl/x509v3.h"
#if OPENSSL_VERSION_NUMBER >= 0x30000000L
DEFINE_STACK_OF(GENERAL_NAME);
#endif
...
```

**Comment by richsalz** [comment]
I did the PR #10669.  If you use no-deprecated, then any files that use the stack macros need the ```DEFINE_STACK_OF``` call. If you do not use no-deprecated, then you don't need it and things work like before. I don't understand the problems @rsbeckerca is having, unfortunately.

More details can be found in the "stack" manpage. (Similar cleanups were planned for LHASH, but the PR never got reviewed or merged before I left.)

**Comment by rsbeckerca** [comment]
@richsalz I wish I understood the underlying cause. I'm speculating that the C pre-processor is hitting some internal buffer limit because it does not happen in any simple tests I've run. It's not normally an issue with duplicate #defines or external declarations, but these generate duplicate real declarations.

**Comment by mattcaswell** [comment]
I think this is (perhaps) the same problem that I described for the lhash equivalent APIs here:

https://github.com/openssl/openssl/pull/10724#discussion_r441388355

**Comment by rsbeckerca** [comment]
@mattcaswell That does look very similar, yes.
