### ISSUE TITLE
the probleme of ssl_session use in nginx

### ISSUE THREAD

**Issue by cjhust** [openssl/openssl#1271]
for details, see https://trac.nginx.org/nginx/ticket/1006

we expect to parse server_name(It is independent in theory) before get session.
This way can resolve nginx ssl problems.

looking forward to your reply.

**Comment by richsalz** [comment]
It seems you want to change the behavior (or add a new API?) in 1.0.2.  We can't/won't do that to a fixed release.  Please see if this is an issue with the current branch.  If something needs to be changed to support nginx, we need to see a patch QUICKLY.  Time is running out.

**Comment by cjhust** [comment]
I just expect next Openssl version can resolve this issue, after all, nginx and openssl are becoming more and more popular.

**Comment by cjhust** [comment]
I will try to give a patch as soon as possible.
