### ISSUE TITLE
In BN_mask_bits, right shift is wrong?

### ISSUE THREAD

**Issue by mogisawa** [openssl/openssl#12720]
In the manual of master and v1.1.1. (also may in the more older versions)
At detail of the BN_mask_bits.
(https://www.openssl.org/docs/manmaster/man3/BN_mask_bits.html)
(https://www.openssl.org/docs/man1.1.1/man3/BN_mask_bits.html)

Hi, all.

Pseudo code of the detail "a&=~((~0)>>n)", it means following computation, I think,
`~0` : 11...(m-bits 1)...11 (left bit is higher, m is bit length of 'a'?)
`(~0)>>n` : 00...(n-bits 0)...0011...((m-n)-bits 1)...11
`~((~0)>>n)` : 11...(n-bits 1)...1100...((m-n)-bits of 0)...00
`a&=~((~0)>>n)` : masking 'a' with the bits and we get the higher n-bits of 'a'.

But the actual crypto library makes the 'lower' n-bits.

I think '<<' should be instead of '>>'. Then
`~0` : 11...(?-bits 1)...11 (left bit is higher)
`(~0)<<n` : 11...(?-bits 1)...1100...(n-bits 0)...00
`~((~0)<<n)` : 00...(?-bits 0, don't care!)...0011...(n-bits of 1)...11
`a&=~((~0)<<n)` : masking 'a' with the bits and we get the lower n-bits of 'a'.

Best regards. Thank you.

**Comment by mattcaswell** [comment]
Seems correct to me. Marking this as a good first issue, and help wanted. PRs to fix this welcome.

**Comment by mogisawa** [comment]
Thank you for your response.
Created PR #12727 .
