### ISSUE TITLE
Possibly invalid test skip condition for GOST

### ISSUE THREAD

**Issue by dvornikov-aa** [openssl/openssl#12722]
Hello!

There is a strange skip condition for gost tests: TLS v1.3 **or** TLS 1.2 are disabled:
https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/test/recipes/90-test_gost.t#L21

I think this condition should be used instead: TLS v1.3 **and** TLS 1.2 are disabled.

**Comment by mattcaswell** [comment]
@beldmit

**Comment by beldmit** [comment]
TLS 1.3 currently has nothing to do with GOST. I have custom patches but not sure they a worth including into OpenSSL 3.0, so I didn't even try.

gost-engine does not depend on DSA now.

The called C test, BTW, implements check that TLS 1.3 is not negotiated (and TLS 1.2 is) when GOST keys are used.

https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/test/gosttest.c#L42-L43

So the condition seems more or less relevant.

**Comment by beldmit** [comment]
Some more realistic tests of GOST support are done via https://github.com/openssl/openssl/blob/master/test/recipes/95-test_external_gost_engine.t
These tests are "external" (implying rare running) and are worth updating anyway.

**Comment by dvornikov-aa** [comment]
@beldmit, thank you for clarifications! This test is really confusing...
