### ISSUE TITLE
Error in openin new ssl connection(error:00000000:lib(0):func(0):reason(0)

### ISSUE THREAD

**Issue by deepak-kumar1985** [openssl/openssl#1272]
We are getting issue using open ssl . We are trying to test open source KMIP server PYKMIP. For the same we have used tox utility which runs unit and integration test cases.   First We got below error message while testing the same.

“SSLError: [Errno 1] _ssl.c:510: error:140890C7:SSL routines:SSL3_GET_CLIENT_CERT
                               IFICATE:peer did not return a certificate”

After searching through contents on internet ,We tried to use latest security certificates as recommended by  below link:
https://github.com/ask/python-github2/issues/58

But after doing recommended changes we are facing below issue:

“ERROR - [Errno 0] _ssl.c:344: error:00000000:lib(0):func(0):reason(0)”

Steps taken till now:
1)	Updated security certificate with latest certificate file.
2)	Installed  httplib2.
3)	Updated tox utility.
4)	Generated self-signed security certificate. 

But same problem persists. Please help on this issue.

**Comment by mattcaswell** [comment]
This error essentially means "no error", or at least no error that has been placed on the OpenSSL error stack. That doesn't necessarily mean that an error has not occurred - just that nothing is on the OpenSSL error stack. You should raise this with the application developers to see if they can understand the circumstances that led up to this.

**Comment by mattcaswell** [comment]
Actually I'll modify that answer to say it means that some function like ERR_error_string() has been passed a 0 error code. The error code can be obtained from ERR_get_error(), which returns 0 if there is no error on the error stack. Perhaps a subtle distinction!

**Comment by deepak-kumar1985** [comment]
@mattcaswell , if that be the case then why is my connection getting close just after this issue. please have a look on below code.
2016-06-30 01:08:28,703 - kmip.server - ERROR - [Errno 0] _ssl.c:344: error:0000
                               0000:lib(0):func(0):reason(0)
                               Traceback (most recent call last):
                                 File "/usr/local/lib/python2.7/dist-packages/kmip/services/server/server.py",
                               line 286, in serve
                                   connection, address = self._socket.accept()
                                 File "/usr/lib/python2.7/ssl.py", line 461, in accept
                                   raise e
                               SSLError: [Errno 0] _ssl.c:344: error:00000000:lib(0):func(0):reason(0)
                               2016-06-30 01:08:28,705 - kmip.server - INFO - Stopping connection service
There are many discussion on this issue on the same error but I could not resolve this issue those recommendations.

**Comment by mattcaswell** [comment]
Well, I am not familiar with either python, KMIP or the python OpenSSL bindings (which are not developed by the OpenSSL project). However the code line in question does not appear to be an OpenSSL call at all. Perhaps a network issue? Please take this to the KMIP developers.

**Comment by deepak-kumar1985** [comment]
thanks, i will post this question to kmip community also.But just to let you know that I tried with sample client and server applications using open ssl and again below message appears.
root@dbasevm:/root# python ../client/client.py
                               Traceback (most recent call last):
                                 File "../client/client.py", line 11, in <module>
                                   ssl_sock.connect(('localhost', 10023))
                                 File "/usr/lib/python2.7/ssl.py", line 433, in connect
                                   self._real_connect(addr, False)
                                 File "/usr/lib/python2.7/ssl.py", line 414, in _real_connect
                                   self.ca_certs, self.ciphers)
                               ssl.SSLError: [Errno 0] _ssl.c:344: error:00000000:lib(0):func(0):reason(0)

**Comment by sathishsms** [comment]
@deepak-kumar1985  Was this issue resolved ?
