### ISSUE TITLE
EVP_DecryptFinal_ex() no longer explicitly sets outl to 0 in some failure paths.

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#12734]
In 1.0.2 & 1.1.x, I believe the behavior of this function is to explicitly set outl to 0 in the event of a failure. In 3.0.0, it appears to leave outl unmodified in some errors paths (for example, decrypting with the wrong key).

I think it's debatable whether or not this is part of the API; I couldn't find anything in the man pages that explicitly stated one way or another what the expectations on outl should be in the failure case. Certainly it can be argued that as a matter of best practice a defensive application developer shouldn't trust outl in the event that EVP_DecryptFinal_ex() fails, but it can also be argued that assuming programmers will be as defensive as we'd like is a bad assumption.

To provide some sense of the potential fallout for applications here, I happened to notice this as a consequence of a negative testcase running under ASAN reporting a read off the end of a buffer boundary. Evidently we had some preexisting application code written by someone who wasn't defensive enough. Obviously I'm fixing it on the application side, but I wanted to submit this as an FYI.

**Comment by mattcaswell** [comment]
> I think it's debatable whether or not this is part of the API; I couldn't find anything in the man pages that explicitly stated one way or another what the expectations on outl should be in the failure case.

Normally we would not expect output parameters to be guaranteed to be updated in the event of an error. I'm not sure whether we should classify this as a bug. What do others think?

**Comment by jwalch** [comment]
For the record, I would completely agree with the statement that it is wrong for an application to depend on this behavior. That's why I'm fixing the application. :)

It is other factors here that give me pause. In particular, the facts that the behavior used to be reliable and that OpenSSL documentation has on longer timescales not historically been comprehensive (though I would happily note that it has made incredible strides in that direction) raise my hackles. While I noted that the behavior may not be part of the API in any formal sense, it is indisputably CLIENT-VISIBLE behavior. My experience with our own product is that customers have a habit of developing expectations that any externally visible behavior not change (and frequently characterize it as a "regression" when it does), regardless of whether we have formally documented it. Anecdotally, I have observed that this effect is amplified in areas where our documentation is lacking.

Now of course sometimes it is necessary to change an externally visible behavior for some reason. It happens. Maybe the behavior is no longer practical, who knows. But I ask myself if that's really the case here. Is there really some compelling reason to change it? Is it hard or impractical to change it back?

Perhaps this is a controversial claim, but I think well-designed libraries endeavor to minimize changing externally visible behavior unnecessarily. Ideally if the behavior has to change, the ABI / API also changes ("breaks") so as to clue in application owners to potential issues.

I hope I'm not ruffling too many feathers to say this, but I think it's a pretty open secret that a common criticism of OpenSSL is that it is difficult for application owners to use correctly. I would humbly submit that this type of issue (and furthermore a refusal to address it) ends up being a contributing factor to that perception. Did the application owner make a mistake? Sure. Could the library have made the application's life easier, possibly saving it from itself? I'd argue that's also true here.

**Comment by t-j-h** [comment]
I think that output parameters should get initialised to sane values as a general API pattern and not be left potentially unchanged depending on the code path that was taken. A level of deterministic behaviour is desirable.

The approach of setting output parameters on input so that all error paths result in a logical consistent condition is a reasonable approach to take. It does tend to stop a whole class of common application errors being reported. And yes - those would be application errors - but they are common to have happen. Reducing error reports for such circumstances is desirable - it lets the user figure out what the user did wrong without logging invalid issues against the project.

This is in a very similar category of API approach for checking things like NULL pointers on input parameters.
