### ISSUE TITLE
AIX: RAND_priv_bytes fails inside drbg initialization

### ISSUE THREAD

**Issue by pwaehnert** [openssl/openssl#12737]
Our framework uses OpenSSL 1.1.1c and occasionally one of our decryption multithreading tests fails on AIX. It was quiet a struggle to pin down at least one source of this failure since it doesn't happen very often. But every now and then the `RUN_ONCE()` call in `RAND_DRBG_get0_private()` fails and leads to chaos among the calling functions. The following minimal example shows this kind of error:

    /* example.c */
    #include <pthread.h>
    #include <openssl/rand.h>

    pthread_barrier_t barrier;

    void *worker(void *args) {
        unsigned char buffer[10];
        pthread_barrier_wait(&barrier);
        if (RAND_priv_bytes(buffer, 10) != 1) {
            *(int *)0 = 1; // (*) segfault in order to get a core dump
        }
        return NULL;
    }

    int main() {
        if (pthread_barrier_init(&barrier, NULL, 2) != 0) {
            return 1;
        }

        pthread_t t1;
        pthread_t t2;

        if (pthread_create(&t1, NULL, worker, NULL) != 0) {
            return 1;
        }
        if (pthread_create(&t2, NULL, worker, NULL) != 0) {
            return 1;
        }

        if (pthread_join(t1, NULL) != 0) {
            return 1;
        }
        if (pthread_join(t2, NULL) != 0) {
            return 1;
        }
        return 0;
    }

In order to compile this example you need to call

    $ xlc_r -o example example.c -I <OpenSSL-Include> -L <OpenSSL-Libs> -lcrypto

To run it sufficiently often I use

    $ i=0; while true; do ((i++)); echo $i; ./client.2 || break; done

It is important to put a certain pressure onto the system and usually the `while` loop trips if this pressure is released. Unfortunately, I don't know any other more reliable way to reproduce this error.

The core dump tells me, that one thread is of course at `(*)` and the other one is inside `do_rand_drbg_init()`, e.g.

    _global_lock_common(??, ??, ??) at 0x90000000124098c
    _mutex_lock(??, ??, ??) at 0x90000000124f0f0
    pthread_once(??, ??) at 0x90000000124ad10
    CRYPTO_THREAD_run_once() at 0x90000000825da6c
    OPENSSL_init_crypto() at 0x90000000825ecb4
    ERR_get_state() at 0x90000000825bcb8
    ERR_set_mark() at 0x90000000825ba4c
    IPRA.$syscall_random() at 0x900000008299a00
    rand_pool_acquire_entropy() at 0x900000008299e24
    rand_drbg_get_entropy() at 0x9000000082987bc
    RAND_DRBG_instantiate() at 0x90000000829e9f8
    IPRA.$drbg_setup() at 0x90000000829d1ec
    do_rand_drbg_init() at 0x90000000829cd60
    do_rand_drbg_init_ossl_() at 0x90000000829cccc
    pthread_once(??, ??) at 0x90000000124adb4
    CRYPTO_THREAD_run_once() at 0x90000000825da6c
    RAND_DRBG_get0_private() at 0x90000000829d980
    RAND_priv_bytes() at 0x90000000829918c
    worker(args = (nil)), line 9 in "example.c"

The error can be observed with OpenSSL 1.1.1g. I compile the OpenSSL on AIX in the following configuration:

    $ perl Configure aix64-cc --prefix=`pwd`/dist/ no-asm

The configuration dump can be found [here](https://github.com/openssl/openssl/files/5141239/dump.txt).

**Comment by paulidale** [comment]
We'll also need to confirm if this remains in master as well.  There is extra locking in master but the underlying initialisation code hasn't changed.

@mspncp, any chance you could poke around with this?  If not, I'll see if I get time.

**Comment by pwaehnert** [comment]
Interesting, I'll check the master right now!

**Comment by pwaehnert** [comment]
The minimal example from above doesn't fail anymore. Great!

Unfortunately, integrating OpenSSL 3 into our framework doesn't seem to me as something I could do in a couple of hours, beside the fact it shouldn't be used in production. Are there any plans to migrate this additional locking into the 1.1.1 series? Could you point me to the corresponding commits?

**Comment by mspncp** [comment]
> The minimal example from above doesn't fail anymore. Great!

I'm not sure whether this proves anything. Maybe just the timing has changed. After all, _a lot_ has changed between 1.1.1 and 3.0.

Anyway, the problem needs to be fixed for 1.1.1. I tried your example on an arbitrary linux machine and of course it did not fail. So I need your further assistance to check things on AIX. Have you tried to find out which error code is returned by `pthread_once()`? Also, adding an `abort()` might provide you with a more accurate core dump.

```diff
diff --git a/crypto/threads_pthread.c b/crypto/threads_pthread.c
index 5a59779ebb..04cecf0184 100644
--- a/crypto/threads_pthread.c
+++ b/crypto/threads_pthread.c
@@ -110,8 +110,12 @@ void CRYPTO_THREAD_lock_free(CRYPTO_RWLOCK *lock)
 
 int CRYPTO_THREAD_run_once(CRYPTO_ONCE *once, void (*init)(void))
 {
-    if (pthread_once(once, init) != 0)
+    int result = pthread_once(once, init);
+    if (result != 0) {
+        fprintf(stderr, "pthread_once failed, error = %d\n", result);
+        abort();
         return 0;
+    }
 
     return 1;
 }
```

**Comment by mspncp** [comment]
Hmmm... the [AIX documentation](https://www.ibm.com/support/knowledgecenter/ssw_aix_71/p_bostechref/pthread_once.html), `pthread_once` does not mention possible error codes. The [linux man page](https://linux.die.net/man/3/pthread_once) indicates that EINVAL could be returned if either once_control or init_routine is invalid, but I can't see how this should happen.

**Comment by makr** [comment]
It would also be nice to know the versions of AIX and XL C.

**Comment by mspncp** [comment]
@makr have you tried to reproduce the issue on your machine?

**Comment by makr** [comment]
Not yet.

**Comment by pwaehnert** [comment]
I got

    $ xlc_r -qversion
    IBM XL C/C++ for AIX, V16.1.0  (5725-C72, 5765-J12)
    Version: 16.01.0000.0004
    $ uname -a
    AIX vmaix72-dev02 2 7 00C15E804B00

I haven't tried to reproduce this bug on our AIX 7.1 machine yet.

@mspncp I'll try your patch and will be right back with the return values.

**Comment by makr** [comment]
Hm ... I have no access to an XL C/C++ V16, only V13 ... I am giving it a spin on a AIX 7.2 with xlc_r V13.1.3 and OpenSSL 1.1.1g. This is what I have immediately available.

**Comment by makr** [comment]
Hit a segfault with the above mentioned configuration, but compiled with `xlc_r -O3` ...
```
81747
81748
bash: line 1: 18350374 Segmentation fault      (core dumped) ./example
aixexx1t::makr 101 => dbx example core
Type 'help' for help.
[using memory image in core]
reading symbolic information ...warning: no source compiled with -g


Segmentation fault in worker at 0x100000538 ($t2)
0x100000538 (worker+0x38) 90000000            stw   r0,0x0(r0)
(dbx) where all
Thread $t1
_event_sleep(??, ??, ??, ??, ??, ??) at 0x9000000005ad874
_event_wait(??, ??) at 0x9000000005ae510
_cond_wait_local(??, ??, ??) at 0x9000000005bd87c
_cond_wait(??, ??, ??) at 0x9000000005bde14
pthread_join(??, ??) at 0x9000000005a2cf0
main() at 0x1000005f0
Thread $t2
worker() at 0x100000538
Thread $t3
pthread_once(??, ??) at 0x9000000005a1c74
CRYPTO_THREAD_run_once() at 0x9000000116366cc
err_shelve_state() at 0x900000011633fe8
ossl_init_load_crypto_nodelete() at 0x900000011636dd0
ossl_init_load_crypto_nodelete_ossl_() at 0x900000011636d8c
pthread_once(??, ??) at 0x9000000005a1dd4
CRYPTO_THREAD_run_once() at 0x9000000116366cc
OPENSSL_init_crypto() at 0x90000001163754c
do_rand_drbg_init() at 0x9000000116a3c14
do_rand_drbg_init_ossl_() at 0x9000000116a3bcc
pthread_once(??, ??) at 0x9000000005a1dd4
CRYPTO_THREAD_run_once() at 0x9000000116366cc
RAND_DRBG_get0_private() at 0x9000000116a4840
RAND_priv_bytes() at 0x9000000116a1fa0
worker() at 0x100000520
```
I'll retry with the same OpenSSL version with debugging symbols ...

**Comment by makr** [comment]
Hm ... yes it seems to trip, when releasing pressure from the system ...
```
127353
127354
bash: line 1: 19136918 Segmentation fault      (core dumped) ./example
aixexx1t::makr 115 => dbx example core
Type 'help' for help.
[using memory image in core]
reading symbolic information ...

Segmentation fault in worker at 0x100000538 ($t3)
0x100000538 (worker+0x38) 90000000            stw   r0,0x0(r0)
(dbx) where all
Thread $t1
_event_sleep(??, ??, ??, ??, ??, ??) at 0x9000000005ad874
_event_wait(??, ??) at 0x9000000005ae510
_cond_wait_local(??, ??, ??) at 0x9000000005bd87c
_cond_wait(??, ??, ??) at 0x9000000005bde14
pthread_join(??, ??) at 0x9000000005a2cf0
main() at 0x1000005f0
Thread $t2
pthread_once(??, ??) at 0x9000000005a1c74
CRYPTO_THREAD_run_once(once = 0x09001000a1fcfbe0, init = 0x09001000a1fd9140), line 118 in "threads_pthread.c"
err_shelve_state(state = 0x0000000110049178), line 777 in "err.c"
unnamed block in ossl_init_load_crypto_nodelete(), line 191 in "init.c"
ossl_init_load_crypto_nodelete(), line 191 in "init.c"
ossl_init_load_crypto_nodelete_ossl_(), line 159 in "init.c"
pthread_once(??, ??) at 0x9000000005a1dd4
CRYPTO_THREAD_run_once(once = 0x09001000a1fa6ce8, init = 0x09001000a1fd82a0), line 118 in "threads_pthread.c"
OPENSSL_init_crypto(opts = 0, settings = (nil)), line 658 in "init.c"
do_rand_drbg_init(), line 915 in "drbg_lib.c"
do_rand_drbg_init_ossl_(), line 909 in "drbg_lib.c"
pthread_once(??, ??) at 0x9000000005a1dd4
CRYPTO_THREAD_run_once(once = 0x09001000a1fa6fe0, init = 0x09001000a1fd3028), line 118 in "threads_pthread.c"
RAND_DRBG_get0_private(), line 1137 in "drbg_lib.c"
RAND_priv_bytes(buf = "", num = 10), line 927 in "rand_lib.c"
worker() at 0x100000520
Thread $t3
worker() at 0x100000538
```
The used OpenSSL 1.1.1g is not patched, build without optimization and including symbols: `./config --prefix=/opt/.../openssl --openssldir=/opt/.../openssl --debug shared no-idea no-mdc2 threads -R ../lib -R '$(LIBRPATH)'`

**Comment by pwaehnert** [comment]
The releasing pressure thing confirms my other observation: In our framework the error always happens if the two threads are completely synchronous. Every log line from the first thread is perfectly aligned with the corresponding line from the second thread. This is of course very demanding for a `pthread_once()` to get this synchronicity well sorted out.

Unfortunately too much `fprintf()` logging inside these once functions destroys this perfect harmony. Thus I wasn't able yet to pin down the actual failure location.

**Comment by makr** [comment]
I am giving it a spin again with the proposed changes above (catching the pthread_once()-result).

**Comment by makr** [comment]
Unfortunately it is not segfaulting/aborting anymore, when patched as proposed above. I'd like to retry with an optimized build. Just don't know, when ...

**Comment by makr** [comment]
I am unable to provoke a segfault with the CRYPTO_THREAD_run_once() changed as proposed above.

**Comment by pwaehnert** [comment]
Sorry, this week I don't have any time left to investigate this issue further, but next week I'll return and try to get some more meaningful backtraces.

A quick fix for our framework was to call `RAND_priv_bytes()` during the initialization of the framework surrounded by a mutex. This prevents any race condition inside those once functions.

**Comment by makr** [comment]
I changed your code slightly:
```diff
+#include <stdio.h>
 #include <pthread.h>
 #include <openssl/rand.h>

 pthread_barrier_t barrier;

 void *worker(void *args) {
+       int rc;
     unsigned char buffer[10];
     pthread_barrier_wait(&barrier);
-    if (RAND_priv_bytes(buffer, 10) != 1) {
-        *(int *)0 = 1; // (*) segfault in order to get a core dump
+
+       rc = RAND_priv_bytes(buffer, 10);
+       if (rc != 1) {
+               char err[1024];
+               ERR_error_string_n( ERR_peek_error(), err, 1024L );
+               fprintf( stderr, "\nrc = %d, err = %s\n", rc, err );
+               abort();
```
After hours of running with various different levels of system load, it finally aborted:
```
258752
258753

rc = 0, err = error:00000000:lib(0):func(0):reason(0)
bash: line 1: 18612640 IOT/Abort trap          (core dumped) ./example
aixexx1t::makr 80 => dbx example core
Type 'help' for help.
[using memory image in core]
reading symbolic information ...

IOT/Abort trap in pthread_kill at 0x9000000005b38a4 ($t3)
0x9000000005b38a4 (pthread_kill+0xc4) e8410028             ld   r2,0x28(r1)
(dbx) where all
Thread $t1
_event_sleep(??, ??, ??, ??, ??, ??) at 0x9000000005ad874
_event_wait(??, ??) at 0x9000000005ae510
_cond_wait_local(??, ??, ??) at 0x9000000005bd87c
_cond_wait(??, ??, ??) at 0x9000000005bde14
pthread_join(??, ??) at 0x9000000005a2cf0
main(), line 42 in "example.c"
Thread $t2
.() at 0xbadc0ffee0ddf00d
Thread $t3
pthread_kill(??, ??) at 0x9000000005b38a4
_p_raise(??) at 0x9000000005b30e4
raise.raise(??) at 0x90000000003f9c8
abort() at 0x90000000005e318
unnamed block in worker(args = (nil)), line 22 in "example.c"
worker(args = (nil)), line 22 in "example.c"
```
It seems `RAND_priv_bytes()` in thread 3 returns with 0 to indicate an error condition, but does not set an error.
It seems that thread 2 is sitting on an invalid/uninitialized pointer/register.
This actually matches both core dumps I posted earlier. The segfaults were caused by the segfault-lever in the `worker()` code.
Just to be sure, could it be that you just don't handle error conditions of `RAND_priv_bytes()`?

**Comment by pwaehnert** [comment]
Inside our framework the error occurs during a concurrent call to `PKCS12_parse()` which in turn calls `RAND_priv_bytes()` somewhere deep inside. Of course, `PKCS12_parse()` checks the result of `RAND_priv_bytes()` and returns itself an error. But the actual error is, that a highly concurrent first call to `RAND_priv_bytes()` sometimes fails by returning a value different than 1.

The `*(int *)0 = 1` resp. `abort()` call was a mere crutch to get a grip on this error since simply setting a breakpoint somewhere in the OpenSSL with dbx and running it won't yield any error.
