### ISSUE TITLE
Does openssl support nist ACVP test?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12746]
Hi,
  I found that openssl has some files related with ACVP.  Are these files used for NIST ACVP Test?  Since ACVP test need to connect to NIST acv server, does openssl now can do such things?
  And I also found this link https://mta.openssl.org/pipermail/openssl-project/2019-June/001380.html  which said that openssl fips 3.0 doesn't use acvp .  Has this test strategy changed?

**Comment by paulidale** [comment]
The FIPS lab is handling this portion for the validation.  I believe they are going the ACVP route but am not 100% sure.

**Comment by slontis** [comment]
The tests are just local tests, that do similiar tests to what ACVP would be using..
It also gives the labs examples of what they need to do when they do their own tests....

**Comment by joymcg** [comment]
> The tests are just local tests, that do similiar tests to what ACVP would be using....
> Regardless of the name (CAVS or ACVP) - these are not for use by labs directly - but they are a reference to how to call the API's.

thanks for the reply
