### ISSUE TITLE
Missing CT documentation

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#1274]
ct.h is a new public API header file, but as far as I can tell none of the functions declared in it come with associated pod file documentation! Can someone write some?

**Comment by mattcaswell** [comment]
Ping @RJPercival, @benlaurie - are one of you two able to help? We really need to stop adding new functions without documentation...I had thought we were getting a lot better at that.

**Comment by RJPercival** [comment]
I'll get right on that.

**Comment by RJPercival** [comment]
RFC6962 (Certificate Transparency) needs adding to https://www.openssl.org/docs/standards.html.

**Comment by richsalz** [comment]
commit 18f6a2c pushed to website, thanks!

**Comment by mattcaswell** [comment]
This issue is about far more than just adding an RFC reference to the website! Re-opening!

**Comment by richsalz** [comment]
oops, right, just saw the last update and got confused.

**Comment by RJPercival** [comment]
Yes that was a bit premature! I'm writing PODs as we speak, and noticed the missing RFC in the process.

**Comment by mattcaswell** [comment]
@RJPercival how is the documentation on this progressing?

**Comment by RJPercival** [comment]
It's partly written, but still needs more work. Judging by the milestone indicator, this is one of the last things left for 1.1 so I'll pause my other work and focus on this - should have something up for review later this week.

**Comment by mattcaswell** [comment]
Great - thanks for the update.

**Comment by mattcaswell** [comment]
...so its later this week ;-)

**Comment by mattcaswell** [comment]
Ping @RJPercival?

**Comment by richsalz** [comment]
@RJPercival just put what you have into a PR.  I'll finish it off.

**Comment by vdukhovni** [comment]
Or we could remove the hastily added CT support from OpenSSL 1.1.0... :-)

**Comment by richsalz** [comment]
If there is no documentation by the end of this week, I would plus-one an MR that did that.
SERIOUSLY.

**Comment by RJPercival** [comment]
I did promise documentation when all that code went through review, and it'll appear today. Sorry for the delay, I've had other time-sensitive tasks constantly competing for my time so this has progressed slower than I'd hoped.

**Comment by mattcaswell** [comment]
Closing this so we can track progress in one place, i.e. #1372
