### ISSUE TITLE
EVP_set_pw_prompt error

### ISSUE THREAD

**Issue by gaoguowei4444** [openssl/openssl#12748]
openssl1.1.1g and openssl3.0.0alpha

When i use the function "EVP_set_pw_prompt(pem_pass_phrase)" to set PEM pass phrase, I set the input parameter pem_pass_phrase = "1234567", then the terminal print 123456, but not continue to connect the mqtt server. Do i have some wrong step to use the EVP_set_pw_prompt()?

**Comment by mattcaswell** [comment]
> When i use the function "EVP_set_pw_prompt(pem_pass_phrase)" to set PEM pass phrase,

The function `EVP_set_pw_prompt` does *not* set the PEM pass phrase. It sets the *prompt* used to get the passphrase from the user (by default on stdin). If you don't want to get the pass phrase from the user, but instead from some other source, then you should provide a custom callback via the `pem_password_cb` argument to whatever function you are calling.

**Comment by mattcaswell** [comment]
Looks like this was answered. Closing.
