### ISSUE TITLE
Perl installing to wrong platform

### ISSUE THREAD

**Issue by LB913** [openssl/openssl#12742]
I am trying to build openSSL vs 3.0.0. I have installed Strawberry Perl and NASM. However, when I go to run the command to build openSSL "perl Configure VC-WIN64A" I get the following error:

Configuring OpenSSL version 3.0.0-alpha7-dev for target VC-WIN64A
Using os-specific seed configuration

Failure!  makefile wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

******************************************************************************
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.10.1 for i686-cygwin-thread-multi-64int
******************************************************************************

I am not sure why my Perl is build for i686-cygwin-thread-multi-64int and not what is needed to compile in Visual Studio.

I am using the x64 Native Tools Command Prompt from Visual Studio 17. How can I change which platform Perl is built for?

**Comment by mattcaswell** [comment]
Probably the cyygwin perl is on your %PATH% before the strawberry perl (or the strawberry perl is not on your %PATH% at all). Ad just your %PATH% environment variable appropriate to  ensure you get the right one.

**Comment by LB913** [comment]
My %PATH% = C:\Program Files\NASM;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin

Should those folders from Strawberry be rearrange some how?

**Comment by LB913** [comment]
@mattcaswell - you were correct, I had a CYGWIN folder listed before the Strawberry folders in my %PATH% definition. I didn't think to look at that, since it has been years since I installed anything related to CYGWIN.

**Comment by kaduk** [comment]
It sounds like this has been answered, so I'll close it -- please reopen if I am misunderstanding.
