### ISSUE TITLE
How can i do when i just want use drbg but not use provider?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12757]
https://github.com/openssl/openssl/blob/72c1e37421ffe9a4db4bba46f3d736dbc227c255/crypto/evp/evp_rand.c#L266

**Comment by levitte** [comment]
You can't, is the short answer.

**Comment by mattcaswell** [comment]
In OpenSSL 3.0 there is *always* a provider (or if not *nothing* works). But in most cases the default provider will just be used and loaded automatically so you don't need to worry about it.

If all you want is to get some random numbers then you don't need to use the `EVP_RAND_*` functions at all. Just use the `RAND_bytes()`/`RAND_priv_bytes()` functions and it should all "just work".

**Comment by stardrift1** [comment]
ok,thanks
