### ISSUE TITLE
ECDSA and TLS versions?

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12768]
Hello all,

I would like to know if ECDSA based certificates are supported in TLSv1.2
Or is it only supported in TLSv1.3?!

i'm currently facing the below issue:

Error connecting to server
139672568456832:error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter:../openssl-1.1.1d/ssl/record/rec_layer_s3.c:1544:SSL alert number 47

TLS alert (write): fatal: illegal parameter
SSL_accept: 1414D17A: error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve

**Comment by t8m** [comment]
The ECDSA should be fully supported in TLSv1.2.
What elliptic curve is your ECDSA certificate using?

**Comment by saddy-muchu** [comment]
**1)**192curve i.e. prime192v1 with sha1; 224 curve i.e. secp224r1 with sha224

Error connecting to server
140065863730816:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../openssl-1.1.1d/ssl/record/rec_layer_s3.c:1544:SSL alert number 40

**2)**256curve i.e. prime256v1 with sha256,sha1,sha224,sha384,sha512 => pass

**3)**384curve i.e. secp384r1 with sha384, 521curve with sha512 =>
Error connecting to server
139930653382272:error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter:../openssl-1.1.1d/ssl/record/rec_layer_s3.c:1544:SSL alert number 47

So, it seems that it works only for 256bit ECC curve

**Comment by mattcaswell** [comment]
`SSL_accept: 1414D17A: error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve`

If you get this on the client side in a TLSv1.2 connection then it usually means that the curve sent back by the server is not in the supported groups list that the client sent initially. Servers (including OpenSSL IIRC) will sometimes do this if its the only curve they have, i.e. they'll try it anyway.

The default supported groups list is here:

https://github.com/openssl/openssl/blob/56456c3404b0ec27f93816d951ff7a58827481f0/ssl/t1_lib.c#L180-L187

So it should be ok with P-384 and P-521, but not the 192 or 224 curves. Unless that is you have changed the default supported groups.

**Comment by saddy-muchu** [comment]
I haven't changed the default supported group list.
So, i guess i can't use 192 or 224 bit curves.

Thanks for this information.
I shall close this issue.
