### ISSUE TITLE
When i try to disable TLS 1.0 protocol it automatically disables TLS 1.1 as well

### ISSUE THREAD

**Issue by rahulrx135** [openssl/openssl#12763]
As per security policies we are trying to disable weaker cipher so i am disabling TLS 1.0 using the following strings 'ALL:!aNULL@STRENGTH:!TLSv1' and 'HIGH:!MEDIUM:!LOW:!aNULL@STRENGTH:!TLSv1' but it automatically disable TLS 1.1 protocol also. As per the openssl doc these both protocol TLS 1.0 and TLS 1.1 have similar ciphers.

Is there any possibility that i can disable only TLS 1.0 using openssl.

**Comment by kaduk** [comment]
The confusing part here is that the "TLSv1" in the cipher string does not rever to protocol versions, but rather to the ciphers that were first defined in that protocol version.  TLS 1.1 has no ciphers that are not also usable in TLS 1.0, so by disabling all TLS 1.0 ciphers you also remove all ciphers that TLS 1.1 could use.

See https://www.openssl.org/docs/manmaster/man3/SSL_set_min_proto_version for the recommended APIs to control protocol versions.

**Comment by rahulrx135** [comment]
These Supported version like TLS1_VERSION, TLS1_1_VERSION available in openssl 1.0.2 version..

**Comment by mattcaswell** [comment]
> These Supported version like TLS1_VERSION, TLS1_1_VERSION available in openssl 1.0.2 version..

Unfortunately the `SSL_set_min_proto_version` function (which as @kaduk states is the recommended APIs to use for this purpose) is not available in OpenSSL 1.0.2. Instead in that version you should use the function `SSL_set_options()` (or `SSL_CTX_set_options()`) in conjunction with `SSL_OP_NO_TLSv1`. See:

https://www.openssl.org/docs/man1.1.1/man3/SSL_set_options.html

**Comment by kaduk** [comment]
[Obligatory note that 1.0.2 is EoL and that 1.1.1 is currently the only supported release branch]

**Comment by rahulrx135** [comment]
Thanks mattcaswell and kaduk, i used SSL_set_options() method to disable
