### ISSUE TITLE
openssl3.0.0 cannot found some definition

### ISSUE THREAD

**Issue by paiguyun** [openssl/openssl#12764]
when I compile program with debug,it successed.
However,when I compile program with release,it says Undefined type "ssl_ctx_st" is used.
in openssl,I can't find the definition of ssl_ctx_st.it just shows that `typedef struct ssl_ctx_st SSL_CTX`.
I can't find other information about ssl_ctx_st.

**Comment by mattcaswell** [comment]
`ssl_ctx_st` was made opaque in OpenSSL 1.1.0. The definition of its structure is entirely held in OpenSSL internal header files. This should not cause a problem for any application using `SSL_CTX` objects as long as you don't attempt to access any of its members, or attempt to stack allocate it.

If you can post the section of code that results in the error, and the precise error message then we might be able to guide you more specifically in what you need to do to fix it.

**Comment by paiguyun** [comment]
@mattcaswell ,
`	meth = SSLv23_server_method();
	ctx = SSL_CTX_new(meth);
	if (!ctx) {
		ShowMessage(LOG_ERROR,"Failed to new ctx.");
		return;
	}
	do{
		if (SSL_CTX_use_certificate_file(ctx, pCertFile, SSL_FILETYPE_PEM) <= 0) {
			ShowMessage(LOG_ERROR,"Failed to use certificate file");
			break;
		}
		if (SSL_CTX_use_PrivateKey_file(ctx, pKeyFile, SSL_FILETYPE_PEM) <= 0) {
			ShowMessage(LOG_ERROR,"Failed to use PrivateKey file");
			break;
		}
		if (!SSL_CTX_check_private_key(ctx)) {
			ShowMessage(LOG_ERROR,"Private key does not match the certificate public key");
			break;
		}
		ctx->default_passwd_callback_userdata = this;
		ctx->default_passwd_callback = PemPwdCallback;`
it failed with Pointers to incomplete class types are not allowed.how can i use member  variables.

**Comment by mattcaswell** [comment]
Closing on the assumption that my answer above solved the issue.
