### ISSUE TITLE
why i should use libcrypto-3.dll and libssl-3.dll

### ISSUE THREAD

**Issue by paiguyun** [openssl/openssl#12774]
I built openssl static libraires (libcrypto.lib and libssl.lib) and linked in my application.
When i tried to start the application it's giving error libcrypto-3.dll and libssl-3.dll missing.
If i linked with static libraries why it's required to ship dll's.

**Comment by mattcaswell** [comment]
Did you actually build the OpenSSL static libraries explicitly (using the "no-shared" configure option)?

If not the .lib files aren't full static libraries. They're just stubs that load the dll.

**Comment by paiguyun** [comment]
@mattcaswell 
![image](https://user-images.githubusercontent.com/70562648/92100049-e14b1080-ee0d-11ea-9fca-26ef0de595e0.png)
how can i solve this problem?

**Comment by mattcaswell** [comment]
Closing on the assumption that my comment above resolved the issue.
