### ISSUE TITLE
Missing error reason strings for alerts in OpenSSL 1.1

### ISSUE THREAD

**Issue by jeltz** [openssl/openssl#1278]
When testing OpenSSL 1.1 with PostgreSQL I got the following error message:

    psql: SSL error: SSL error code 336151576

while I got the following with 1.0.2:

    psql: SSL error: tlsv1 alert unknown ca

This is due to PostgreSQL calling `ERR_reason_error_string()` and getting `NULL` back and therefore deciding to just output the raw packed error value, so this means that for some reason we get a failure when looking up this error (while other error messages appear as normal).

The error code in the example is `SSL_AD_REASON_OFFSET + TLS1_AD_UNKNOWN_CA`.

I tracked it down to aea145e3992aae298c63d4c7a1d5aec76883a50e which removes a lot of defines and error texts. These files look like they are generated but I am not familiar enough with the code to see what the bug is and what texts should not have been removed.

**Comment by richsalz** [comment]
You're right, that's a bug, the SSL_R_...alert... values need to be restore.  MR coming soon.

**Comment by richsalz** [comment]
See #1280 for a fix.
