### ISSUE TITLE
Docs talk about providers; makefiles say MODULES

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#12783]
Should the makefiles be fixed to use PROVIDER as the variable names and targets instead of MODULE?

**Comment by richsalz** [comment]
And why is the environment variable ```OPENSSL_MODULES``` and not ```OPENSSL_PROVIDERS```?

**Comment by levitte** [comment]
Because a "module" is the word we use for dynamically loadable objects (.so files on unix).
A provider can, but must not necessarily be module, so while there is an overlap between the two, that doesn't make them equal. 

Strictly speaking, engines can be modules as well, and I would include them in MODULES as well, if it wasn't for their need to be in an installation directory of their own. In other words, `ENGINES` is historic legacy.

**Comment by richsalz** [comment]
Where do we use module other than providers?  The DSO facility, which only loads compression libs AFAIK?
As for providers not necessarily being a module, can you tell me what else is supported?

Not going to be very upset if this is closed -- there are more important things -- but I find the answer not satisfactory.  What else is OPENSSL_MODULES used for beside crypto providers.

**Comment by mspncp** [comment]
> As for providers not necessarily being a module, can you tell me what else is supported?

The default provider is built in, so even in the case where libcrypto itself is a shared library I wouldn‘t call it a module. 

> What else is OPENSSL_MODULES used for beside crypto providers.

For (legacy) engines, as @levitte already mentioned.

**Comment by levitte** [comment]
> What else is OPENSSL_MODULES used for beside crypto providers.

For the moment, nothing.  In the future, who knows?

**Comment by mattcaswell** [comment]
> As for providers not necessarily being a module, can you tell me what else is supported?

There are plenty of examples or providers that aren't modules. The default provider (as mentioned by @mspncp). The null provider. When static linking, the legacy provider. The tls provider in the tests. The filter provider in the tests.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by levitte** [comment]
This should actually have been closed a loooong time ago.  Doing so now
