### ISSUE TITLE
NonStop fails to build libcrypto.so for overlong CC argument list

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12797]
This is essentially a similar root cause on NonStop as #12116 where the number of objects supplied in the construction of libcrypto.so exceeds the capacity of the platform.

I was able to MacGyver the Makefile (which is not sustainable) to create a libcrypto.so instance using:

```        <repeat the echo for all files going into libcrypto.so>
        echo providers/libcrypto-shlib-baseprov.o >> libcrypto.in
        echo providers/libcrypto-shlib-defltprov.o >> libcrypto.in
        echo providers/libcrypto-shlib-nullprov.o >> libcrypto.in
        $(CC) $(LIB_CFLAGS) $(LIB_LDFLAGS) \
                -Wshared \
                -o libcrypto.so \
                -Weld_obey=libcrypto.in \
                providers/libimplementations.a providers/libcommon.a providers/libnonfips.a  $(LIB_EX_LIBS)
```

If the linker is used directly, as configured, we could just supply the libcrypto.a, presumably, instead of constructing the list of objects.

**Comment by levitte** [comment]
Darn.  I suspect this will also hit the same mingw builds that already had issues of this sort when building static libraries.

The only viable solution I can see is to go back to linking from static libraries, and work out the different options to tell the linker to grab everything from the static library.  We did this previous to OpenSSL 1.1.0, but I abandoned that method because keeping track of those options felt dodgy.

**Comment by levitte** [comment]
FYI, I've plans to work quite a lot on the build system as soon as we've released the first beta.  Right now, I'm much too busy with stuff that need to happen before we have a feature freeze.

**Comment by rsbeckerca** [comment]
> 
> 
> FYI, I've plans to work quite a lot on the build system as soon as we've released the first beta. Right now, I'm much too busy with stuff that need to happen before we have a feature freeze.

That's cool. We just released 1.1.1g to our community. I think we have a little time before there's clamoring for 3.0.x. Besides, I need to work on a solution to enabling FIPS on the x86 platform variant. The Itanium variant won't have it for the foreseeable future.

**Comment by rsbeckerca** [comment]
Information only: Just tested this on commit 67ecd65cc4, which still has this problem.

**Comment by levitte** [comment]
I came to this today, and considering I haven't found the time to do the build system revamp that I want, I went with a kinda sorta hack.  Another config attribute, `shared_argfileflag`, will be good enough.  That will not only solve this problem for NonStop, but for Mingw as well.

**Comment by levitte** [comment]
Hmm, when looking into this, I discovered that you don't seem to encode version information into shared libraries.  How does it work on NonStop when you want to upgrade a library where the ABI differs (i.e. a "library bump")?

**Comment by rsbeckerca** [comment]
> 
> 
> Hmm, when looking into this, I discovered that you don't seem to encode version information into shared libraries. How does it work on NonStop when you want to upgrade a library where the ABI has gone through incompatible changes (i.e. a "library bump")?

Do you mean from something like 1.0.2 to 1.1.1 or 1.1.1 to 3.0.0?

**Comment by levitte** [comment]
> Do you mean from something like 1.0.2 to 1.1.1 or 1.1.1 to 3.0.0?

Yes.

The common way on most Unix systems is {libname}.so.{libversion}.  On Windows, there's no common standard, so we went for {libname}-{libversion}.dll (well, not just that, but close enough for the purpose of this discussion).

**Comment by rsbeckerca** [comment]
> 
> 
> > Do you mean from something like 1.0.2 to 1.1.1 or 1.1.1 to 3.0.0?
> 
> Yes.
> 
> The common way on most Unix systems is {libname}.so.{libversion}. On Windows, there's no common standard, so we went for {libname}-{libversion}.dll (well, not just that, but close enough for the purpose of this discussion). Something similar could be done for NonStop.

There is no standard mechanism for the NonStop loader. It looks for the DLL by exact name and does not accept a suffix version. We are currently using entirely different paths for OpenSSL because of the locations of engines and certificates. So something like `/usr/local` historically for 1.0.2, `/usr/local-1.1` for 1.1.1, and this one will be `/usr/local-3.0`.

**Comment by levitte** [comment]
> There is no standard mechanism for the NonStop loader. It looks for the DLL by exact name and does not accept a suffix version. We are currently using entirely different paths for OpenSSL because of the locations of engines and certificates. So something like `/usr/local` historically for 1.0.2, `/usr/local-1.1` for 1.1.1, and this one will be `/usr/local-3.0`.

Okie, that's workable (and of our hands, then :wink:)

**Comment by rsbeckerca** [comment]
> 
> 
> > There is no standard mechanism for the NonStop loader. It looks for the DLL by exact name and does not accept a suffix version. We are currently using entirely different paths for OpenSSL because of the locations of engines and certificates. So something like `/usr/local` historically for 1.0.2, `/usr/local-1.1` for 1.1.1, and this one will be `/usr/local-3.0`.
> 
> Okie, that's workable (and of our hands, then 😉)

I actually put together a whole webinar about this ;)

**Comment by rsbeckerca** [comment]
Not a good result here. The generated command was close, but there needs to be :
```
c99 -g -O0 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_neutral_library -Wverbose -Wtarget=tns/e -Wsystype=oss -Wilp32  -L. -Wshared -Weld="-export_all" -Weld="-set systype oss" -Weld="-set floattype neutral_float"  \
        -o libssl.so \
        -Weld_obey=libssl.so.args \
        -lcrypto  -lrld -lfloss
c99: error: No input file.
c99: Exiting with status 1; 1 error(s).
```
This is a c99 issue. When I run the linker directly:
```
/usr/bin/eld -o libssl.so -shared -L. -obey libssl.so.args -lcrypto -lrld \
   -lfloss -optional_lib -L \
   /G/system/sys04 -lcre -lcrtl -lossk -lossf -lsec -li18n -licnv -losse \
   -linet -lossh -lossc -no_optional_lib -export_all -set systype oss -set \
   floattype neutral_float
```
it is happy.

**Comment by levitte** [comment]
Can we discuss the PR in the actual PR?

**Comment by rsbeckerca** [comment]
> 
> 
> Can we discuss the PR in the actual PR?

I keep doing that. Sorry.

**Comment by rsbeckerca** [comment]
> 
> 
> > > There is no standard mechanism for the NonStop loader. It looks for the DLL by exact name and does not accept a suffix version. We are currently using entirely different paths for OpenSSL because of the locations of engines and certificates. So something like `/usr/local` historically for 1.0.2, `/usr/local-1.1` for 1.1.1, and this one will be `/usr/local-3.0`.
> > 
> > 
> > Okie, that's workable (and of our hands, then 😉)
> 
> I actually put together a whole webinar about this ;)

As a side-bar, we find that there are still versioning issues even with version affinity in Linux. The memory and threading models do not get resolved correctly. On NonStop this is a huge issue, many different builds being needed. That further confuses "DLL Hell". My webinar is [here](https://www.comforte.com/webinar-managing-openssl/). Understand that was done for the NonStop audience.

**Comment by rsbeckerca** [comment]
@levitte I'm not sure everything got merged yet on this one. If so, I think something got missed. I'm at commit 21e5be854d.

**Comment by levitte** [comment]
> I'm not sure everything got merged yet on this one

No, #12960 and #12962 are still in the merge waiting queue.

Dunno if you're aware, but we implement a 24h grace period starting from the approval, so that everyone has a chance to see what's going on, and comment if they have anything to say.  Since we're spread around the globe, we can't in good conscience make it shorter.  So those two are going in tomorrow (in the morning for me).

**Comment by rsbeckerca** [comment]
> 
> 
> > I'm not sure everything got merged yet on this one
> 
> No, #12960 and #12962 are still in the merge waiting queue.
> 
> Dunno if you're aware, but we implement a 24h grace period starting from the approval, so that everyone has a chance to see what's going on, and comment if they have anything to say. Since we're spread around the globe, we can't in good conscience make it shorter. So those two are going in tomorrow (in the morning for me).

Great to know. I'm still trying to get my hardware randomizer through (PR #12923) but getting loads of push back.
