### ISSUE TITLE
Potentially unused static functions in err.h starting in 3.0.0

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#12792]
I noticed this while experimenting with integration against a fairly old version of bind9.

```
+++ Compiling: src/contrib/bind9/lib/dns/gssapi_link.c ? bedrock/private/x86_64.debug/uliba/LIBDNS.A/gssapi_link.o
In file included from src/contrib/bind9/lib/dns/gssapi_link.c:33:
In file included from src/contrib/bind9/lib/dns/dst_internal.h:57:
bedrock/import/x86_64.debug/uliba/headers/openssl/err.h:224:24: error: unused function 'ERR_GET_LIB' [-Werror,-Wunused-function]
static ossl_inline int ERR_GET_LIB(unsigned long errcode)
                       ^
bedrock/import/x86_64.debug/uliba/headers/openssl/err.h:231:24: error: unused function 'ERR_GET_FUNC' [-Werror,-Wunused-function]
static ossl_inline int ERR_GET_FUNC(unsigned long errcode ossl_unused)
                       ^
bedrock/import/x86_64.debug/uliba/headers/openssl/err.h:243:24: error: unused function 'ERR_GET_REASON' [-Werror,-Wunused-function]
static ossl_inline int ERR_GET_REASON(unsigned long errcode)
                       ^
bedrock/import/x86_64.debug/uliba/headers/openssl/err.h:250:24: error: unused function 'ERR_FATAL_ERROR' [-Werror,-Wunused-function]
static ossl_inline int ERR_FATAL_ERROR(unsigned long errcode)
                       ^
4 errors generated.
```

Ok, so in 3.0.0 instead of being macros (as they previously were), now they're static inline functions.  All fine, I suppose, but it seems like the issue is that as a freestanding header there's no guarantee that some of these functions are actually used.

It seems like the "fix" here would be to slap ossl_unused into the method signature. This would as specifically applies to these 4 functions probably be something that could probably just be pushed under "trivial" CLA. However, when I tried to generalize this I had a little pause and I wanted to open an issue to allow for discussion or for someone to attack this as more of a systemic thing.

It seems to me that any static function in a public header should probably be annotated with ossl_unused. Perhaps it's unnecessary for cases where the function is used elsewhere in the same header (ERR_GET_RFLAGS(), for example), but it seems like as a matter of general policy it would reduce potential refactoring headaches. Others may disagree. 

Should only static ossl_inline functions be considered?

Should internal headers be considered? My original use case was compiling an OpenSSL consumer with -Wunused-function, but it may be desirable to compile OpenSSL itself with that flag. Presumably that basically works today, but I can imagine situations easily emerging with the right combination of #defines wherein some implementation file pulls in an internal header that defines some static function which ends up being unused within that particular translation unit. Perhaps it can be argued that these functions should be defined only under some appropriate #ifdef & that therefore such situations developing internally would reflect a mismanagement of #define / #ifdef.

Again, my personal take would be to be pretty aggressive in deploying ossl_unused with respect to headers (internal and public) just because it seems to me that there's very little downside to it. There could be reasonable disagreement to this, however.

**Comment by levitte** [comment]
I see no problem with slapping on ossl_unused where needed. Would you mind doing that? PR welcome!

**Comment by jwalch** [comment]
Yeah, it was wanting to more precisely define "where needed" that led me to file this as an issue rather than just going straight to a PR. I think for the 4 specifically mentioned in those compiler warnings it would be uncontroversial, but if it gets "bigger" than that maybe it's more questionable. I don't take it for granted that there would be consensus in the project in favor of my more extreme "just suppress unused for all static functions in all headers" position. Supposing some consensus position (not necessarily my proposed one) could be arrived at, beyond the immediate mechanical cleanup work there would remain the question of what an automated enforcement mechanism for keeping the project consistent would look like. If there's not a consensus view (that can be supported with automation), I'd be happy to just resolve this with a PR for the 4 functions. I just figured it was an opportunity to perhaps make things a bit less ad hoc in this particular regard.

**Comment by levitte** [comment]
I would start with the public headers, that's one PR.  Just doing the ERR functions you found is fine too.  It's too to decide how much of your personal cycles you want to pour into this.

Internals are probably less interesting in this regard, as there really isn't anything that's unused, as far as I know.

As for consensus, the best way to look is in Configure.  Look for the perl arrays that have "devteam" in their names.  Those are added to the C flags when `--strict-warnings` is used when configuring.
