### ISSUE TITLE
errstr fails on error 80000000: reports no error on NonStop.

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12798]
I think this might be a bit of a nit, but there might be small issue in errstr with one error value of 80000000. In the test suite:
```
02-test_errstr.t ................... 55/?
../../util/wrap.pl ../../apps/openssl errstr 80000000 => 0
not ok 56 - match 'No error' (2147483648) with one of ( '', 'reason(0)' )
```
This condition did not happen at 1.1.1g. The stack trace is showing that errnum is 0 by the time an attempt is made to report the error, which is would be expected:
```
#0  openssl_strerror_r (errnum=0, buf=0x6ffffd00 "No error", buflen=256) at o_str.c:332
#1  0x7fa6bf50:0 in ERR_error_string_n (e=2147483648, buf=0x6ffffe04 "", len=256) at crypto/err/err.c:516
#2  0x700599a0:0 in errstr_main (argc=<optimized out>, argv=<optimized out>) at apps/errstr.c:65
#3  0x7006d020:0 in do_cmd (prog=<optimized out>, argc=2, argv=<optimized out>) at apps/openssl.c:406
```
The platform response is: `error:80000000:system library::No error` rather than `reason(0)`. I have seen textual comparisons of results from `strerror` fail in test suites from other products. So this does not look like product issue, but a quirk in the test.

**Comment by levitte** [comment]
I assume that this is our current master development.

I'm going to guess that `openssl_strerror_r()` returns false here:

https://github.com/openssl/openssl/blob/076bf8c2c972d01a70ca4146e637dfbe6f35b2fb/crypto/err/err_prn.c#L44

Would you mind digging into that to see what actually happens?  `openssl_strerror_r()` is implemented in `crypto/o_str.c`

**Comment by rsbeckerca** [comment]
> 
> 
> I assume that this is our current master development.
> 
> I'm going to guess that `openssl_strerror_r()` returns false here:
> 
> https://github.com/openssl/openssl/blob/076bf8c2c972d01a70ca4146e637dfbe6f35b2fb/crypto/err/err_prn.c#L44
> 
> Would you mind digging into that to see what actually happens? `openssl_strerror_r()` is implemented in `crypto/o_str.c`

I'll have a look.

**Comment by rsbeckerca** [comment]
The code drops to the platform `strerror()`, which varies in what it returns. On NonStop, the string that gets copied into `buf` is `"No error"`, while other platforms may have a different result.

https://github.com/openssl/openssl/blob/076bf8c2c972d01a70ca4146e637dfbe6f35b2fb/crypto/o_str.c#L327

I think this is an issue in the test recipe, not `openssl_strerror_r()`.

**Comment by levitte** [comment]
Ah, thanks for pointing at the recipe, I forgot to look there.

This line indicates what's going on:

```
not ok 56 - match 'No error' (2147483648) with one of ( '', 'reason(0)' )
```

`'No error'` is the string that comes from `openssl errstr`
`'reason(0)' ` is the constructed fallback in case `openssl_errstrerror_r()` would return false.
`''`, the first in the "one of" list, is perl's interpretation of the system error (highest bit masked off, so a plain zero).

It seems like perl's interpretation of errno == 0 is the empty string, which makes sense from a perl perspective, as the empty string is "false" while the non-empty string is "true", making it possible to detect errors with a simple condition:

``` perl
    if ($!) {
        # error handling code
    }
```

Interestingly enough, `80000000` doesn't come up at all in my run of `test_errstr`, so it seems like your `<errno.h>` has a macro for zero (which is quite odd, since that's not an error, and definitely not POSIX).  Mine doesn't, so I never hit this issue.
(perl's Errno module derives its E constants from the local `<errno.h>`)

A simple solution would be to explicitly avoid zero in that recipe.  That's easy.  PR coming up!

**Comment by levitte** [comment]
Please try #12799

**Comment by rsbeckerca** [comment]
I don't think the fix is quite there yet.

```
02-test_errstr.t ................... 56/?
Can't "continue" outside a when block at test/recipes/02-test_errstr.t line 69.
02-test_errstr.t ................... Dubious, test returned 255 (wstat 65280, 0xff00)
```

**Comment by levitte** [comment]
Argh, language mix-up. Should be `next` rather than `continue`...

(the flip side of being multi-lingual...)

**Comment by rsbeckerca** [comment]
> 
> 
> Argh, language mix-up. Should be `next` rather than `continue`...
> 
> (the flip side of being multi-lingual...)

Which file/line? I'm in my dev environment right now.

**Comment by rsbeckerca** [comment]
> 
> 
> > Argh, language mix-up. Should be `next` rather than `continue`...
> > (the flip side of being multi-lingual...)
> 
> Which file/line? I'm in my dev environment right now.

`    next if $errcode == 0;`

Changing continue -> next in 02_test_errstr.t at line 69 still results in:

```
02-test_errstr.t ................... 109/?
02-test_errstr.t ................... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/111 subtests
```

**Comment by levitte** [comment]
In that case, this will give you the verbose output of that recipe only, please try:

```
make test TESTS=test_errstr V=1
```

(or whatever corresponding command you run)

**Comment by rsbeckerca** [comment]
> 
> 
> In that case, this will give you the verbose output of that recipe only, please try:
> 
> ```
> make test TESTS=test_errstr V=1
> ```
> 
> (or whatever corresponding command you run)

Only thing I could spot is:

`# Looks like you planned 111 tests but ran 110.`

**Comment by rsbeckerca** [comment]
> 
> 
> > In that case, this will give you the verbose output of that recipe only, please try:
> > ```
> > make test TESTS=test_errstr V=1
> > ```
> > 
> > 
> > (or whatever corresponding command you run)
> 
> Only thing I could spot is:
> 
> `# Looks like you planned 111 tests but ran 110.`

@levitte `/usr/include/errno.h` has the following line on the platform.

```
#define ENOERR               0
```
So that hypothesis is correct. Try the following code snipped instead of `next`. This works in my environment. So without changing `tests_planned`, calling `&ok` with a no-op seems to work.

```
    if ($errcode == 0) {
        &ok(1) # Ignore this condition
    } else {
        &ok(match_syserr_reason($errcode))
    }
```

**Comment by levitte** [comment]
Thanks for confirming!
