### ISSUE TITLE
OpenSSL's HMAC for BLAKE2b doesn't seem to agree with the reference implementation

### ISSUE THREAD

**Issue by Serpent27** [openssl/openssl#12809]
I don't want to submit this as a bug, since this may be intentional but OpenSSL's implementation of BLAKE2b-HMAC doesn't seem to follow either HMAC, or keyed mode (as defined in the [BLAKE2 reference [PDF]](https://blake2.net/blake2.pdf) and in the [reference implementation](https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c)). I'm guessing OpenSSL may have combined the 2 standards? Or has OpenSSL used their own standard and called it BLAKE2b-HMAC?

I'd appreciate an explanation as to why I'm seeing different behaviour. Thanks in advance!

**Comment by paulidale** [comment]
It's a bug.  OpenSSL should conform to the standard.

**Comment by Serpent27** [comment]
I closed this issue to re-submit it as a bug report [here](https://github.com/openssl/openssl/issues/12811).
