### ISSUE TITLE
OpenSSL's HMAC for BLAKE2b doesn't agree with the reference implementation

### ISSUE THREAD

**Issue by Serpent27** [openssl/openssl#12811]
In [this issue](https://github.com/openssl/openssl/issues/12809) I outlined that OpenSSL's implementation of BLAKE2b-HMAC doesn't seem to follow either HMAC, or keyed mode (as defined in the [BLAKE2 reference [PDF]](https://blake2.net/blake2.pdf) and in the [reference implementation](https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c)). Since it seems to be a bug, I'm closing that issue and re-creating it as a bug report.

**Comment by slontis** [comment]
Hi @Serpent27.

I haven't gone through the code line by line to compare, but will ask a few general questions first..

Are you looking at blake2b_mac.c and blake2b_prov.c?

The comment in this file says..
 * Derived from the BLAKE2 reference implementation written by Samuel Neves.
 * Copyright 2012, Samuel Neves <sneves@dei.uc.pt>
 * More information about the BLAKE2 hash function and its implementations
 * can be found at https://blake2.net.

There are test vectors in test/recipes/30-test_evp_data/evpmac_blake.txt.
Which has a title of
Title = Keyed BLAKE2 tests (Test vectors from reference implementation)

Are you saying these are test vectors are incorrect?

The tests can be run via
> ./test/evp_test test/recipes/30-test_evp_data/evpmac_blake.txt

**Comment by Serpent27** [comment]
I noticed the issue when comparing the result from the BLAKE2 library at https://github.com/BLAKE2/BLAKE2 initialized with `blake2b_init_key( S, outbytes, key, key_length );`. I'm not sure how the test vectors can possibly be wrong but I'm also at a loss as to how their own implementation can be wrong.

**Comment by Serpent27** [comment]
This is what im wondering: the Openssl implementation passes the test vectors. The test vectors are correct (I compared just now). Yet somehow the official implementation gets a different result?

Unless I'm just really clueless (which is a distinct possibility).

**Comment by slontis** [comment]
> Unless I'm just really clueless (which is a distinct possibility).
Welcome to my world  :)
Maybe try feeding one of the test vectors in to see it looks ok..
The other thing I notice about the vectors is that the keys are all the same size. Maybe a smaller key is getting zero padded differently or something silly like that. Let me know if you find anything.

**Comment by slontis** [comment]
> Yet somehow the official implementation gets a different result.

That does sound a bit strange.

**Comment by slontis** [comment]
You could try running genkat-c.c to see what it spits out.. if that is generating the right thing then you could debug it to see where you are going wrong maybe?

**Comment by Serpent27** [comment]
I just realized the issue (and it's more on the side of me being clueless)...

I just realized I've been zero-padding my keys! Oops.

**Comment by slontis** [comment]
Hmm I can see some changes done in 2016.. (So the ref has changed in some places)
e.g:
https://github.com/BLAKE2/BLAKE2/commit/932be4e9f5c973a2aa49656447683fbfae4cfb39#diff-18389a4a9ad5795744699cff0ba66c15

So this might be good that you have asked a question..

**Comment by slontis** [comment]
Please close this if everything seems ok

**Comment by slontis** [comment]
Glad we found what the problem was - and that it wasnt broken in OpenSSL.. Cheers.
