### ISSUE TITLE
[crypto][encode_decode] NULL Pointer dereference

### ISSUE THREAD

**Issue by raminfp** [openssl/openssl#12819]
Hi,

There is a "NULL Pointer dereference" in function [decoder_process()](https://github.com/openssl/openssl/blob/master/crypto/encode_decode/decoder_lib.c#L405),
When call function [OSSL_DECODER_INSTANCE_decoder()](https://github.com/openssl/openssl/blob/master/crypto/encode_decode/decoder_lib.c#L475) if return NULL, 

There isn't any check for it,in the line [LINE 514](https://github.com/openssl/openssl/blob/master/crypto/encode_decode/decoder_lib.c#L514),

Thanks,
Ramin - RavinAcademy

**Comment by raminfp** [comment]
@levitte

**Comment by mattcaswell** [comment]
Ping @levitte. This does look like a real issue

**Comment by levitte** [comment]
I assume that `new_decoder->decode == NULL` in this case...  such an OSSL_DECODER should simply never be, and I found the error that still allowed that to happen.

Fixup coming up!

**Comment by levitte** [comment]
Please try #12849.  That should give an error when trying to set up the decoder context.
