### ISSUE TITLE
how to use ed25519 cipher on DTLS client

### ISSUE THREAD

**Issue by xuyouming1986** [openssl/openssl#12827]
We know that openssl support ed25510 from version 1.1.1.  
now I just want to use this version to implement a DTLS client which use ed25519 cipher suite. But I am not sure how to infrom the server that the clinet prefer ed25519 cipher。I think we should try SSL_set_cipher_list or SSL_set_ciphersuites, but we have no idea of what param should use?

**Comment by paulidale** [comment]
@PKdisplayWs you should get notificates from here.

**Comment by mattcaswell** [comment]
> I think we should try SSL_set_cipher_list or SSL_set_ciphersuites, but we have no idea of what param should use?

You just use an ECDSA based ciphersuite, and the ed25519 certificate will be used if available.

**Comment by xuyouming1986** [comment]
ok, just use ECDSA is ok
