### ISSUE TITLE
We know that openssl support ed25510 from version 1.1.1.

### ISSUE THREAD

**Issue by PKdisplayWs** [openssl/openssl#12829]
We know that openssl support ed25510 from version 1.1.1.  
now I just want to use this version to implement a DTLS client which use ed25519 cipher suite. But I am not sure how to infrom the server that the clinet prefer ed25519 cipher。I think we should try SSL_set_cipher_list or SSL_set_ciphersuites, but we have no idea of what param should use?

__Originally posted by @xuyouming1986 in https://github.com/openssl/openssl/issues/12827__

**Comment by paulidale** [comment]
Asking multiple times doesn't speed up the response, in fact it slows things down.  Tag yourself on the original issue to get notified.

**Comment by PKdisplayWs** [comment]
> We know that openssl support ed25510 from version 1.1.1.
> now I just want to use this version to implement a DTLS client which use ed25519 cipher suite. But I am not sure how to infrom the server that the clinet prefer ed25519 cipher。I think we should try SSL_set_cipher_list or SSL_set_ciphersuites, but we have no idea of what param should use?
> 
> **Originally posted by @xuyouming1986 in #12827**

**Comment by PKdisplayWs** [comment]
> Asking multiple times doesn't speed up the response, in fact it slows things down.  Tag yourself on the original issue to get notified.
