### ISSUE TITLE
DTLS:Whether OpenSSL can invoke the our own  ed25519 signature or verification method

### ISSUE THREAD

**Issue by zhanghenghw** [openssl/openssl#12832]
Currently, we have our own ed25519 signature and verification method. How can I enable OpenSSL to invoke our own method to sign and verify messages? Are there any interfaces that can be used?

**Comment by paulidale** [comment]
This varies depending on the version of OpenSSL being used.  For 1.1.1, you'll need to use the various `EVP_PKEY_meth_*` functions to create an algorithm implementation or implement an engine.  For 3.0, you will need to implement a provider.

**Comment by mattcaswell** [comment]
Seems like this was answered. Closing.
