### ISSUE TITLE
ecp_nistz256-armv4.S bad arguments to instruction

### ISSUE THREAD

**Issue by HenryNe** [openssl/openssl#12848]
Error from ARMv4 Assembler:
```
arm-armv4tl-linux-gcc  -I. -Iinclude -Icrypto -fPIC -pthread -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/home/vagrant/igw-systems/INSTALL/OPENSSL-1.1.1g-issue/usr/lib/engines-1.1\"" -DNDEBUG -D__ARM_ARCH_4__ -march=armv4 -fpic -c -o crypto/ec/ecp_nistz256-armv4.o crypto/ec/ecp_nistz256-armv4.S
crypto/ec/ecp_nistz256-armv4.S: Assembler messages:
crypto/ec/ecp_nistz256-armv4.S:3853: Error: bad arguments to instruction -- `orr r11,r10'
crypto/ec/ecp_nistz256-armv4.S:3854: Error: bad arguments to instruction -- `orr r11,r12'
crypto/ec/ecp_nistz256-armv4.S:3855: Error: bad arguments to instruction -- `orrs r11,r14'
Makefile:3084: recipe for target 'crypto/ec/ecp_nistz256-armv4.o' failed
make[1]: *** [crypto/ec/ecp_nistz256-armv4.o] Error 1
make[1]: Leaving directory '/home/vagrant/igw-systems/build/openssl-1.1.1g'
Makefile:174: recipe for target 'all' failed
make: *** [all] Error 2
```
Call to build:
```
MACHINE="armv4tl" ./config shared --cross-compile-prefix="arm-armv4tl-linux-" --prefix=/usr/local "-D__ARM_ARCH_4__ -march=armv4 -fpic"

make MACHINE="armv4tl" SRCDIR=. BLDDIR=.
```
Version:
OpenSSL 1.1.1g  21 Apr 2020

Used GNU GCC:
arm-armv4tl-linux-gcc (GCC) 3.4.4

[perl-config-dump.txt](https://github.com/openssl/openssl/files/5200523/config-dump.txt)

Suggested patch:
[openssl-1.1.1.armv4.patch.txt](https://github.com/openssl/openssl/files/5200536/openssl-1.1.1.armv4.patch.txt)

**Comment by romen** [comment]
This seems to come from 75738b9433185f44103073fd29ec63ae72e24e63

@bernd-edlinger could you please have a look?

**Comment by romen** [comment]
Thanks for your report and for the proposed fix @HenryNe!

**Comment by romen** [comment]
I don't have access to an armv4 platform to test it out, but can this be the consequence of using a too old version of GCC?

**Comment by HenryNe** [comment]
Yes, the GCC is truely old. But need for this device.
The assember is:
```
$ arm-armv4tl-linux-ar --version
GNU ar 2.16
```
From [here](http://lists.lysator.liu.se/pipermail/nettle-bugs/2013/002325.html) found solution:

> 1. Always use 3-operand form instructions, i.e.,
> 
>      add r1, r1, r2
> 
>    rather then
> 
>      add r1, r2
>

**Comment by levitte** [comment]
Considering that the rest of `ecp_nistz256-armv4.pl` uses 3 arguments for `orr` and `orrs`, these lines do indeed look like a mistake.

@HenryNe, I suggest you make a PR from that patch.  I would go so far as to say that it's a `CLA: trivial` PR.

**Comment by HenryNe** [comment]
How can  run a single test for this ec on the platform? I have no perl there for the complete test suite.
