### ISSUE TITLE
Sometimes "fips selftest faild" is occurred.

### ISSUE THREAD

**Issue by pospione** [openssl/openssl#12842]
I am using the openssl version 1.0.2m with fips 2.0.16 to implement DICOM TLS.

After my application calls FIPS_mode_set(1) function at the first part. my application use other cipher functions for TLS.
FIPS_mode_set(1) function is always success and other functions works well usually.
but, sometimes "fips selftest failed" or "drbg stuck" error message is returned, and next functions are all failed.
I don't know what openssl function returns this error exactly, because I use openssl through DCMTK Library.

I wonder why this error is returned in spite of FIPS_mode_set(1) function success.
and I'd like to know how I can avoid this error or recover without reboot application.

**Comment by slontis** [comment]
Please read the security policy.
See https://www.openssl.org/docs/fips/SecurityPolicy-2.0.16.pdf
"Section 6 Self-test"

It is possible that a self test (Pairwise consistency tests OR continuous test for stuck) can fail at a later time..
The pairwise tests can only fail during a key generation, but the CRNG output test can fail if there are repeated patterns of bytes when it grabs entropy. Once this happens the fips module disables all services provided.

**Comment by pospione** [comment]
Thanks for you reply.

If the "fips selftest failed" or drbg stuck" error occurs, if I call the FIPS_mode_set(1) function again, can FIPS mode be activated again?

**Comment by slontis** [comment]
As far as i can see from reading the code - it looks possible..
This will run all the self tests again though, which make take some time.
You should be asking yourself why your entropy is bad (which is how this would happen).

**Comment by pospione** [comment]
Thanks for your comment.

It seems that I resolved this problem.
My S/W tries to connect to several servers at the same time with TLS.
Error was happening when my s/w tries to connect to 2 or 3 servers through threads at the same time.
I controlled connections with Critical section so openssl code is not called at the same time.

Thanks.
