### ISSUE TITLE
openssl-1.1.1 header file e_os.h  has  line  # include <limits.h> where is it this file located or supposed to be from ?

### ISSUE THREAD

**Issue by mxdog** [openssl/openssl#12864]
I get this bug?  with  windows  nmake 
openssl-1.1.1\e_os.h(13): fatal error C1083: Cannot open include file: 'limits.h': No such file or directory

Where is the file limits.h located/from what,  it does not seem to be in this repo ? 

Is it a dependency on some package I don't see a reference for i.e. a perl module, msys, VC   ?
I hate to bug report this if I just overlooked something but it is a build error.
this is the link I downloaded from .....

[https://www.openssl.org/source/openssl-1.1.1g.tar.gz)](https://www.openssl.org/source/openssl-1.1.1g.tar.gz)

win 10 x64 
nmake version  Version 14.00.24210.0

build environment::
mingwin32 after running vcvars.bat in terminal and tried 
from windows terminal after the same vcvars.bat in terminal
( so should have picked it up in the VC Environment if that is where it is supposed to be from )  

there are a few limits.h (247) files on my system and iirc I build this last year for another project and didn't have any problems just downloaded it and config/nmake.

**So if not a bug/missing file from the repo can someone point me to the right source file/library..etc. it is looking for so I can fix my paths.**

**Comment by levitte** [comment]
limits.h is one of the standard C header files, at the very least since C89, so it should come with any C compiler that can compile OpenSSL.

Ref: https://en.cppreference.com/w/c/header

**Comment by mxdog** [comment]
@ levitte
 Ok, thanks , sorry didn't even think of standard c headers at the time .....that gets me back on my way..
