### ISSUE TITLE
No suitable signature algorithm error

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12862]
What could be some of the reasons that one might end up in the below error?

2020.09.22 17:19:49 LOG7[0]: TLS alert (write): fatal: handshake failure
2020.09.22 17:19:49 LOG3[0]: SSL_accept: 14201076: error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm

140011398743872:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../openssl-1.1.1d/ssl/record/rec_layer_s3.c:1544:SSL alert number 40

i currently get this error when trying to use ECC based keys and certificates.
OpenSSL version: 1.1.1d
TLS version: 1.2

**Comment by kroeckx** [comment]
It means that the client did not offer any signature algorithm
that are accepted by the server.

**Comment by saddy-muchu** [comment]
But, the "Client Hello" message has all the possible signature algorithms.

**Comment by kroeckx** [comment]
And how is the server configured? Because it's the server that
gives an error.

Can you give the list that the client sends?

**Comment by saddy-muchu** [comment]
i guess there is some problem w.r.t the way server is configured because client is offering all it can.
Maybe, i need to configure the correct certificate and key from the server side.
Am i correct?

**Comment by kroeckx** [comment]
The signature depends on the configured certificate yes. The
public key type will allow a number of signature algorithms.
