### ISSUE TITLE
Code duplication between handshake_helper.h and ssltestlib.h

### ISSUE THREAD

**Issue by ekasper** [openssl/openssl#1287]
Both provide very similar code for setting up SSL objects and completing a handshake in-process.

**Comment by levitte** [comment]
I just did a diff between `test/handshake_helper.c` and `test/ssltestlib.c`...  it seems the similarities are gone, so I'll close this.

**Comment by ekasper** [comment]
Both offer helper functions to set up `SSL_CTX` and `SSL` objects and implement an in-memory handshake.

**Comment by levitte** [comment]
Ah, ok.

**Comment by kaduk** [comment]
While I can abstractly appreciate the desire to avoid duplication of functionality, there doesn't seem to be much driving force to get this done for the 1.1.1 release, so I'm inclined to kick the can down the road some more and mark it for "post 1.1.1".  At this time, there's about 10 uses of handshake_helper's ```do_handshake()```, and about 20 uses of ssltestlib's ```create_ssl_ctx_pair()```, if we wanted to let the more popular one win.

**Comment by levitte** [comment]
Looking at old issue...  Like @kaduk says, the driving force regarding this is low.  Looking at the the files, it looks to me like merging the handshake_helper and ssltestlib code requires some serious refactoring.  Correct me if I'm wrong.

This should be closed...

**Comment by mattcaswell** [comment]
Agreed. Closing.
