### ISSUE TITLE
The internal ECX_KEY structure seems to be exposed publicly

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12880]
The ECX_KEY structure is a purely internal type. We have never exposed a low level API for ECX keys. However we seem to have exposed this type in the public API (and documented them) recently via the function calls `EVP_PKEY_get0_X25519()`, `EVP_PKEY_get0_X448()`, `EVP_PKEY_get0_ED25519()`, `EVP_PKEY_get0_ED448()` as well as the equivalent `set0` variants.

This doesn't seem correct - they should be removed.

**Comment by mattcaswell** [comment]
@levitte - can you comment? (seems to have come in via #12544)

**Comment by levitte** [comment]
My mistake...  I thought this was a case of "not feature complete".
