### ISSUE TITLE
Deprecate ASN1_STRING_length_set

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#12885]
`ASN1_STRING_length_set` sets the length of an `ASN1_STRING` without also setting the data, unlike `ASN1_STRING_set` and `ASN1_STRING_set0`. This is not particularly safe as it messes up the bounds of the string if it doesn't match the previously-passed-in pointer. I found no evidence of anyone using this, so perhaps it's worth deprecating and later removing.

**Comment by levitte** [comment]
Agreed.  Feel free to submit the PR, it should be quite trivial (don't forget `make update`)
