### ISSUE TITLE
a crash happened on openssl-1.1.1g

### ISSUE THREAD

**Issue by tonyzdf** [openssl/openssl#12898]
Hi folks
we met a crash happened on openssl-1.1.1g. 
the libssl.a and libcrypto.a was built by ourself.
our application is a single thread http server.
and we can not reproduce in develop environments.
but it crash often on our production line.

Could you help to check the root cause ?

the crash stack:
![image 2020091715250641652C7](https://user-images.githubusercontent.com/13919213/93433928-0bb2c880-f8fa-11ea-8d70-196cfcb41dd8.png)

Best Regards

**Comment by mattcaswell** [comment]
Any chance you can get an OpenSSL build with debug symbols switched on in your production environment?

**Comment by tonyzdf** [comment]
I will try.

**Comment by tonyzdf** [comment]
![image](https://user-images.githubusercontent.com/13919213/94127437-84320000-fe8b-11ea-8689-93780c6fc5fc.png)

**Comment by tonyzdf** [comment]
@mattcaswell  could you help to analysis this stack ?

**Comment by mattcaswell** [comment]
So this shows a "refcout error" when freeing an expired session.

Sessions are represented in OpenSSL by an SSL_SESSION object and they are ref counted. Newly created SSL_SESSION objects start with a ref count of 1. You can up the ref count by calling SSL_SESSION_up_ref(), and it is decremented by calling SSL_SESSION_free(). When calling the latter the session is only "really" freed if the ref count drops to 0.

OpenSSL keeps a cache of sessions inside the SSL_CTX object. This is so that if a client attempts to resume a session we can find the session data inside the cache. We up the ref count when putting the session in the cache, and decrement it when removing it again. Sessions have a default timeout of 2 hours - so if they're not used within that time period then they are automatically flushed from the cache (we check for timed out sessions every time we attempt to add a new session to the cache).

In this case a session has gone passed its 2 hour time period and therefore we have attempted to remove it from the cache. However when we called SSL_SESSION_free() we found that the ref count was already 0! In other words we are attempting to free an already freed session. This happens if there is a mis-match betweeen the number of up_ref vs the number of free calls.

Do you ever call SSL_SESSION_free() in your own code? If you do, I'd start by looking in those locations to see if there is ever the possibility of calling it when you shouldn't.

> and we can not reproduce in develop environments.

This is most likely because the default timeout after which sessions are removed from the cache is 2 hours. I guess its unlikely that you run your dev environments for that long. You can change the default session timeout by calling the function `SSL_CTX_set_timeout`.

**Comment by tonyzdf** [comment]
![image](https://user-images.githubusercontent.com/13919213/94216958-5bede400-ff13-11ea-934f-9898f4b55290.png)
My questions is if the session had been freed,  why does it still exist in the cache list ?
The session object  have all fields be 0. where does this zero-valued session come from ?

**Comment by mattcaswell** [comment]
> My questions is if the session had been freed, why does it still exist in the cache list ?

Like I said sessions are ref counted. So calling "free" on a session just decrements the ref count. The session cache itself increments the ref count when the session goes into the cache, and decrements it when it is taken out of the cache. In this case however the ref count has already reached zero when the cache looks at the session. This means that *somewhere* some code has decremented the ref count when it should not have done (e.g. calling "free" when it does not own a reference).

> The session object have all fields be 0. where does this zero-valued session come from ?

Once a session has been freed you can't rely on any of the values in it. The memory has been returned to the OS for reuse so could have any garbage data in itl. However, as it happens, when OpenSSL frees a session it zeroizes all the data in it.

**Comment by tonyzdf** [comment]
after confirmation, our application did not call SSL_SESSION_free(),  we reply on openssl to manage session and cache.

**Comment by tonyzdf** [comment]
![image](https://user-images.githubusercontent.com/13919213/94444065-7efcea00-01d8-11eb-9d77-aaa804e0a608.png)

**Comment by mattcaswell** [comment]
> above SSL_CTX can prove we did not get session.

Ok - although note that the highlighted callbacks aren't the only way to get hold of SSL_SESSION objects (e.g. you can get one by calling SSL_get_session(), SSL_get0_session() or SSL_get1_session()).

> @mattcaswell do you think there is possibility that it is openssl-1.1.1g's internel bug ?

I certainly wouldn't rule that possibility out. But, on the basis that we've not seen this before, I tend to suspect something in your application is the cause. However I keep an open mind.

> can you give some suggestions how to look up the root cause ?

It would be really very helpful if we could manage to make this a bit more easily reproducible, and in your dev environment. An obvious way to try and do that would be to reduce the session timeout to something very short (e.g. like 10 seconds) to see if we can induce the crash. You can try calling `SSL_CTX_set_timeout()` and see if that make it occur.

Another possibility that springs to mind is some kind of memory corruption. If the ref count got corrupted then this could certainly cause this error. Perhaps you could try running some tests with valgrind to see if that shows up anything unexpected.

**Comment by mdsiebler** [comment]
Hi I am cross-posting this in the hopes it brings more light to the issue. It seems like this has been reported twice:

https://github.com/openssl/openssl/issues/12898
https://github.com/openssl/openssl/issues/12814

Our team is trying to see if we can make a standalone C program that can illustrate this issue; but even without that is there a way to make progress on these crashes?
Please do let me know if this is not the best way to approach this as I am not very familiar with the community.
Thanks in advance.

**Comment by mattcaswell** [comment]
> Our team is trying to see if we can make a standalone C program that can illustrate this issue; but even without that is there a way to make progress on these crashes?

Without a reliable way of reproducing the problem its difficult to make progress....so if you are able to come up with a standalone reproducer that would be an enormous help.

**Comment by kaduk** [comment]
To expound on Matt's answer a bit: the locking strategy for SSL_SESSION lists is pretty simple: each SSL (and thus, SSL_SESSION) hash is associated to a single dedicated `SSL_CTX` structure (the "session_ctx") for the lifetime of its existence, even if SNI or some other mechanism is used to cause the SSL to get some configuration from a different `SSL_CTX`.  The "session_ctx" has a lock, and that lock is held whenever the session list or associated hash table of sessions is being modified.  This has been invariant for a very long time and has been audited by many people over that time, and asking someone to go through and audit it again "just in case" is unlikely to find anything that has been missed in the previous attempts.

In the absence of a specific dedicated reproducer, you might attempt to profile or add diagnostic assertions to the lock implementation to confirm that the expected lock is always held when the session list and related datastructures are modified, but in some sense the "most likely" explanation is that there is unsafe memory access in some other part of the application (or library, I suppose) that is modifying the underlying memory outside of the locking regime, and a tool like valgrind or ASAN would be expected to assist in locating such memory-unsafe behavior.

**Comment by mdsiebler** [comment]
ok thank you for the feedback.

**Comment by HushAsy** [comment]
same problem with you, core dump stack, as follow:
```
#0  0x00007f160cd25387 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f160cd26a78 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f160cd67ed7 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f160cd70299 in _int_free () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007f160d45acef in doall_util_fn (use_arg=1, func=0x0, arg=<optimized out>, func_arg=<optimized out>, lh=0x1b57790) at crypto/lhash/lhash.c:196
        i = 181
        a = <optimized out>
        n = 0x0
#5  OPENSSL_LH_doall_arg (lh=0x1b57790, func=func@entry=0x7f160d8033b0 <timeout_cb>, arg=arg@entry=0x7ffeec6b9be0) at crypto/lhash/lhash.c:211
No locals.
#6  0x00007f160d804337 in lh_SSL_SESSION_doall_TIMEOUT_PARAM (arg=0x7ffeec6b9be0, fn=0x7f160d8033b0 <timeout_cb>, lh=<optimized out>) at ssl/ssl_sess.c:1067
No locals.
#7  SSL_CTX_flush_sessions (s=0x19e93b0, t=<optimized out>) at ssl/ssl_sess.c:1082
        tp = {ctx = 0x19e93b0, time = 1677117607, cache = 0x1b57790}
#8  0x00007f160d7fb486 in ssl_update_cache (s=s@entry=0x21b5330, mode=mode@entry=2) at ssl/ssl_lib.c:3564
        stat = <optimized out>
        i = <optimized out>
#9  0x00007f160d81e081 in tls_construct_new_session_ticket (s=0x21b5330, pkt=0x7ffeec6b9e10) at ssl/statem/statem_srvr.c:4181
        tctx = <optimized out>
        tick_nonce = "\000\000\000\000\000\000\000"
        age_add_u = {age_add_c = "\022\272\345>", age_add = 1055242770}
#10 0x00007f160d810187 in write_state_machine (s=0x21b5330) at ssl/statem/statem.c:843
        post_work = 0x7f160d81f620 <ossl_statem_server_post_work>
        mt = 4
        pkt = {buf = 0x2b6f480, staticbuf = 0x0, curr = 57, written = 57, maxsize = 18446744073709551615, subs = 0x2b978b0}
        pre_work = 0x7f160d81f420 <ossl_statem_server_pre_work>
        get_construct_message_f = 0x7f160d81f990 <ossl_statem_server_construct_message>
        confunc = 0x7f160d81dea0 <tls_construct_new_session_ticket>
        st = 0x21b5378
        transition = 0x7f160d81f030 <ossl_statem_server_write_transition>
        cb = <optimized out>
---Type <return> to continue, or q <return> to quit---
#11 state_machine (s=0x21b5330, server=1) at ssl/statem/statem.c:443
        buf = 0x0
        cb = <optimized out>
        st = 0x21b5378
        ret = -1
        ssret = <optimized out>
#12 0x00007f160d7fb5c8 in SSL_do_handshake (s=0x21b5330) at ssl/ssl_lib.c:3716
        ret = 1
#13 0x0000000000453ffe in ngx_ssl_handshake (c=0x7f160b8bc8e0) at src/event/ngx_event_openssl.c:1720
        n = <optimized out>
        sslerr = <optimized out>
        err = <optimized out>
        rc = <optimized out>
        c = 0x7f160b8bc8e0
#14 0x00000000004543b2 in ngx_ssl_handshake_handler (ev=<optimized out>) at src/event/ngx_event_openssl.c:2091
        c = 0x7f160b8bc8e0
#15 0x000000000044f637 in ngx_epoll_process_events (cycle=<optimized out>, timer=<optimized out>, flags=<optimized out>) at src/event/modules/ngx_epoll_module.c:901
        events = 6
        revents = 1
        instance = <optimized out>
        i = 3
        level = <optimized out>
        err = <optimized out>
        rev = <optimized out>
        wev = <optimized out>
        queue = <optimized out>
        c = 0x7f160b8bc8e0
#16 0x0000000000446213 in ngx_process_events_and_timers (cycle=cycle@entry=0x194e0b0) at src/event/ngx_event.c:257
        flags = 1
        timer = <optimized out>
        delta = 0
        q = <optimized out>
        ev = <optimized out>
#17 0x000000000044d762 in ngx_worker_process_cycle (cycle=cycle@entry=0x194e0b0, data=data@entry=0x7) at src/os/unix/ngx_process_cycle.c:782
        worker = 7
---Type <return> to continue, or q <return> to quit---
#18 0x000000000044c100 in ngx_spawn_process (cycle=cycle@entry=0x194e0b0, proc=proc@entry=0x44d6f0 <ngx_worker_process_cycle>, data=data@entry=0x7, 
    name=name@entry=0x578cbd "worker process", respawn=respawn@entry=-4) at src/os/unix/ngx_process.c:199
        on = 1
        pid = 0
        s = 17
#19 0x000000000044dbbc in ngx_start_worker_processes (cycle=cycle@entry=0x194e0b0, n=8, type=type@entry=-4) at src/os/unix/ngx_process_cycle.c:382
        i = 7
#20 0x000000000044e45b in ngx_master_process_cycle (cycle=0x194e0b0, cycle@entry=0x177dfb0) at src/os/unix/ngx_process_cycle.c:241
        title = <optimized out>
        p = <optimized out>
        size = <optimized out>
        i = <optimized out>
        sigio = 0
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 0}, it_value = {tv_sec = 0, tv_usec = 0}}
        live = <optimized out>
        delay = 0
        ccf = 0x194fc50
#21 0x00000000004260c6 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:386
        b = <optimized out>
        log = 0x81edc0 <ngx_log>
        i = <optimized out>
        cycle = 0x177dfb0
        init_cycle = {conf_ctx = 0x0, pool = 0x177ce70, log = 0x81edc0 <ngx_log>, new_log = {log_level = 0, file = 0x0, connection = 0, disk_full_time = 0, handler = 0x0, 
            data = 0x0, writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0}, log_use_stderr = 0, files = 0x0, free_connections = 0x0, free_connection_n = 0, modules = 0x0, 
          modules_n = 0, modules_used = 0, reusable_connections_queue = {prev = 0x0, next = 0x0}, reusable_connections_n = 0, connections_reuse_time = 0, listening = {
            elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, 
            size = 0, nalloc = 0, pool = 0x0}, config_dump_rbtree = {root = 0x0, sentinel = 0x0, insert = 0x0}, config_dump_sentinel = {key = 0, left = 0x0, right = 0x0, 
            parent = 0x0, color = 0 '\000', data = 0 '\000'}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, 
          shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0, 
          read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {len = 42, data = 0x7ffeec6bc379 "rker process"}, conf_param = {len = 0, data = 0x0}, 
          conf_prefix = {len = 32, data = 0x7ffeec6bc379 "rker process"}, prefix = {len = 27, data = 0x573c65 "/usr/local/openresty/nginx/"}, error_log = {len = 18, 
            data = 0x573c91 "/app/log/error.log"}, lock_file = {len = 0, data = 0x0}, hostname = {len = 0, data = 0x0}, intercept_error_log_handler = 0x0, 
          intercept_error_log_data = 0x0, entered_logger = 0}
        cd = <optimized out>
---Type <return> to continue, or q <return> to quit---
        ccf = <optimized out> 
```

**Comment by HushAsy** [comment]
I have been tortured by this problem for a long time😖😖😖, who can help me, thank you very much

**Comment by tonyzdf** [comment]
@HushAsy SSL_CTX_set_session_cache_mode(ctx, SSL_SESS_CACHE_OFF) could avoid the crash.

**Comment by HushAsy** [comment]
> 

Thanks very mush,you gave me a great hope, try it now 🌹🌹🌹

**Comment by HushAsy** [comment]
> 

The nginx used in our production environment is used as a reverse proxy, all external interfaces are configured with ssl, and the ssl session cache uses the cache mechanism provided by openssl itself. We will no longer use the cache provided by openssl itself in the future. now.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
