### ISSUE TITLE
Will OpenSSL add renegotiation_info to initial clienthello msg?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12902]
Hi, 
   As mentioned in this issue  #6484  , openssl use TLS_EMPTY_RENEGOTIATION_INFO_SCSV for secure renegotiation. I want to know whether openssl will add a choice to choose "renegotiation_info" extension to initial clienthello msg for renegotiation?

**Comment by kaduk** [comment]
Sorry, "initial clienthello msg for renegotiation" does not parse properly for me.  "Initial" in the context of TLS renegotiation refers to the "initial handshake", that is, the ClientHello sent in a TLSPlaintext record.  But renegotiation inherently requires a preexisting TLS connection, and involves a ClientHello sent in an (encrypted) TLSCiphertext record.

OpenSSL adds the "renegotiation_info" extension to the encrypted ClientHello, unconditionally.

**Comment by joymcg** [comment]
Hi kaduk,
   Thanks for the reply. 
   So openssl doesn't  add  the an empty "renegotiation_info" extension in ClientHello when it's initial handshake. But it will add this extension  when client send clientHello for renegoation after initial handshake success?

**Comment by kaduk** [comment]
> Hi kaduk,
> Thanks for the reply.
> So openssl doesn't add an empty "renegotiation_info" extension in ClientHello when it's initial handshake. But it will add this extension when client send clientHello for renegoation after initial handshake success?

Yes.

**Comment by joymcg** [comment]
Hi Kaduk,
From RFC5746:
3.4.  Client Behavior: Initial Handshake
   Note that this section and Section 3.5 apply to both full handshakes
   and session resumption handshakes.
   o  **The client MUST include either an empty "renegotiation_info"
      extension, or** the TLS_EMPTY_RENEGOTIATION_INFO_SCSV signaling
      cipher suite value in the ClientHello.  Including both is NOT
      RECOMMENDED.


**_Will openssl add a option for use to choose use empty  "renegotiation_info"
      extension？_**

**Comment by kaduk** [comment]
I don't expect us to spontaneously add such an option (each new option comes with a maintenance burden).  If someone wrote the code to do it and made a pull request, we would look at it, but I think we'd want to hear some justification for why the empty extension is needed instead of the SCSV before we would accept it.
