### ISSUE TITLE
openssl-3.0.0 uses des encryption to report an exception

### ISSUE THREAD

**Issue by yan-yy** [openssl/openssl#12906]
Version:       3.0.0-alpha6
Download From: https://www.openssl.org/source/openssl-3.0.0-alpha6.tar.gz
Compiler Environment:  
        OS:     Debian 10 Buster 
        Kernel: 4.19.0-10-amd64
        GCC:    8.3.0,system build-in
        perl:   perl-5.28.1 ,system build-in
        Compilation parameters: ./Configure --prefix=/opt/scientific/libs/openssl

Use command:
        openssl des -a -pass pass:1111
        Output: 
                Error setting cipher DES-CBC
                00A14855797F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:
                        Global default library context, Algorithm (DES-CBC), Properties ()
                00A14855797F0000:error::digital envelope routines:EVP_CipherInit_ex:initialization error:crypto/evp/evp_enc.c:179
        des-cfb, des-ecb and cast all have the same problem

**Comment by paulidale** [comment]
This isn't a bug, it is the intended behaviour.  DES is a very old algorithm and is considered legacy.  This means it is not enabled by default.

You'll need to add `-provider legacy` or modify your configuration file.
