### ISSUE TITLE
04-test_params_conversion fails on NonStop x86

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12919]
This is a new breakage for 3.0.0 when building on x86.

```
04-test_params_conversion.t ........
        # INFO:  @ /home/ituglib/randall/openssl-3.0/test/testutil/stanza.c:21
        # Reading ../../test/recipes/04-test_params_conversion_data/native_types.txt
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 14
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 21
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 36
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 44
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 52
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 60
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 67
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 75
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 83
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 91
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 99
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 107
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 115
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 123
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 131
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 139
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 155
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 171
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 179
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 187
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 195
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 203
        # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
        # false
        # unexpected conversion to double on line 211
        # ERROR: (bool) 'i32 == pc->i32 == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:198
        # false
        # unexpected conversion to int32 on line 249
        # ERROR: (bool) 'i32 == pc->i32 == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:198
        # false
        # unexpected conversion to int32 on line 256
        # ERROR: (bool) 'i32 == pc->i32 == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:198
        # false
        # unexpected conversion to int32 on line 264
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 272
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 280
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 288
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 296
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 304
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 312
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 320
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 328
        # INFO:  @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:121
        # Line 336: extra characters at end 'inf' for double
        # ERROR: (bool) 'OSSL_PARAM_get_int32(pc->param, &i32) == false' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:192
        # true
        # unexpected valid conversion to int32 on line 343
        # INFO:  @ /home/ituglib/randall/openssl-3.0/test/testutil/stanza.c:33
        # Completed 0 tests with 0 errors and 0 skipped
        not ok 1 - ../../test/recipes/04-test_params_conversion_data/native_types.txt
# ------------------------------------------------------------------------------
    not ok 1 - run_param_file_tests
# ------------------------------------------------------------------------------
../../util/wrap.pl ../../test/params_conversion_test ../../test/recipes/04-test_params_conversion_data/native_types.txt => 255
not ok 1 - running params_conversion_test native_types.txt
04-test_params_conversion.t ........ 1/? ---------------------------------------
#   Failed test 'running params_conversion_test native_types.txt'
#   at test/recipes/04-test_params_conversion.t line 21.
04-test_params_conversion.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by levitte** [comment]
```
        # Line 336: extra characters at end 'inf' for double
```

Line 336 in `test/recipes/04-test_params_conversion_data/native_types.txt` is at the end of this (that line number wasn't very obvious, @paulidale):

```
# infinite
type=double
int32=invalid
int64=invalid
uint32=invalid
uint64=invalid
double=inf
```

That `inf` is given to `strtod()`, so that particular error tells me that the NonStop version of that function doesn't work quite like we expected.  According to https://en.cppreference.com, [`strtod()`](https://en.cppreference.com/w/c/string/byte/strtof) is a C function since C89, and it should accept `inf`:

> * **INF** or **INFINITY** ignoring case 

POSIX specifies the same: https://pubs.opengroup.org/onlinepubs/009604599/functions/strtod.html

Judging from the rest of the output, I'm guessing that other `strto` functions also behave in ways that we don't quite expect.  It would be good to know how NonStop varies in this particular area.

**Comment by paulidale** [comment]
Good detective work @levitte

**Comment by rsbeckerca** [comment]
> 
> 
> Good detective work @levitte

I'm happy to test this. What am I expecting not to see? ;)

**Comment by rsbeckerca** [comment]
`strtod`, according to the first test that fails, is converting "6" to a double 6. The return pointer, `p` is pointing to the `'\0'` at the end of the "6" as is expected. If I interpret the test correctly, the test (second call to `param_conversion_load_stanza`) seems to think that this conversion is invalid, where it is not invalid according to both this platform and other Linux definitions.

The test reports:
```
    # ERROR: (bool) 'd == pc->d == true' failed @ /home/ituglib/randall/openssl-3.0/test/params_conversion_test.c:278
    # false
```
Which seems like a false positive.

**Comment by rsbeckerca** [comment]
When converting `9007199254740991` to double in `strtod()`, the value returned is 0, even though the pointer `p` points to null. According to the man page:

>       Because  a return value of 0.0 (zero) can represent either a valid con-
>       version or an error, you should use errno to check for possible errors.
>       Set  errno to a value of 0 before the call to the strtod() function and
>       then check it for a nonzero value after the call.  If errno is nonzero,
>       an error has occurred.

The same applies to `strtoimax()`.

**Comment by paulidale** [comment]
Are you sure you have POSIX compliant implementations?

The only error listed is `ERANGE` and with a zero return this indicates an underflow has occurred.  Why does a large value like that underflow?

**Comment by rsbeckerca** [comment]
> 
> 
> Are you sure you have POSIX compliant implementations?
> 
> The only error listed is `ERANGE` and with a zero return this indicates an underflow has occurred. Why does a large value like that underflow?
> 
> `strtoimax()` can also only `ERANGE` on overflow and returns a huge value in this case.

Actually, I am one of the first to complain that this might not be purely POSIX complaint. I'll instrument the code to see what is really being returned tomorrow or Wednesday. If it turns out that this is the case, I will report the error to HPE, but assuming that is the case, I don't see this getting fixed in the 3.0.0 timeframe. Under those conditions, I can put together a temporary-ish fix until a fix is available. That work?

**Comment by rsbeckerca** [comment]
> 
> 
> > Are you sure you have POSIX compliant implementations?
> > The only error listed is `ERANGE` and with a zero return this indicates an underflow has occurred. Why does a large value like that underflow?
> > `strtoimax()` can also only `ERANGE` on overflow and returns a huge value in this case.
> 
> Actually, I am one of the first to complain that this might not be purely POSIX complaint. I'll instrument the code to see what is really being returned tomorrow or Wednesday. If it turns out that this is the case, I will report the error to HPE, but assuming that is the case, I don't see this getting fixed in the 3.0.0 timeframe. Under those conditions, I can put together a temporary-ish fix until a fix is available. That work?
> 
> Edit: according to POSIX, `ERANGE` can occur on an overflow also. This is arguable, so I am working on a workaround and submitting this to HPE. I am also getting `EINVAL` from `strtod()` when `-1e100` is supplied. That will be reported also.

What is weird is that I am not getting an error from `strtoimax()`, and `p` points to `'\0'` for `int32` types. I'm investigating that.

**Comment by rsbeckerca** [comment]
I'm going to retract the above. While `ERANGE` may occur, and `EINVAL` may be unreasonable, by the time the code gets to `OSSL_PARAM_get_int32`, the value of `p` does not look reasonable:
```
$1 = {
  key = 0x80002d0 "double",
  data_type = 3,
  data = 0x8003600,
  data_size = 8,
  return_size = 4294967295
}
```
and
```
p *(p->data)
$3 = (void) 0x0
```
given
```
d = *(const double *)p->data;
```
sets `d` to 0, which is in range, and the comparison at 
```
if (d >= INT32_MIN && d <= INT32_MAX && d == (int32_t)d) {
```
specifically `d==(int32_t)d` is coming back as true because `d==0` and on this platform the cast still works. This is using a simple test file of:
```
# 2^53-1
type=double
int32=invalid
int64=9007199254740991
uint32=invalid
uint64=9007199254740991
double=9007199254740991
```

**Comment by paulidale** [comment]
> I'm going to retract the above. While `ERANGE` may occur, and `EINVAL` may be unreasonable, by the time the code gets to `OSSL_PARAM_get_int32`, the value of `p` does not look reasonable:

> ```
> *p = {
>   key = 0x80002d0 "double",
>   data_type = 3,
>   data = 0x8003600,
>   data_size = 8,
>   return_size = 4294967295
> }
> ```

What's not reasonable here?  This is a double that hasn't been subject to a set call yet.


> ```
> p->data = (void) 0x0
> ```

This I don't understand.  A void pointer or a pointer to zero bytes?


> specifically `d==(int32_t)d` is coming back as true because `d==0` and on this platform the cast still works. This is using a simple test file of:

> ```
> # 2^53-1
> type=double
> int32=invalid
> int64=9007199254740991
> uint32=invalid
> uint64=9007199254740991
> double=9007199254740991
> ```

It looks like the double value is being lost and replaced by zero.  I'll note that a double has 53 bits of mantissa and 2^53-1 uses all of them.  It's an edge case but it should work.

**Comment by levitte** [comment]
> I'll note that a double has 53 bits of mantissa and 2^53-1 uses all of them. It's an edge case but it should work.

Uhmmm, that reminds me; @rsbecker, which config target did you get this result with?  Does tandem vs neutral floats have any relevance here?
(I know absolutely nothing about the different tandem floats...  @paulidale assumes standard IEEE format, as far as I know)

**Comment by rsbeckerca** [comment]
The ranges are very different for tandem vs. neutral. We could try IEEE. The option is `-WIEEE_float`. This would make no difference to strtoimax(), which is behaving properly as far as I can debug. The issue seems to be that the int32 indicator is not being checked when the parameter is examined after the call in the test code.

**Comment by paulidale** [comment]
> The issue seems to be that the int32 indicator is not being checked when the parameter is examined after the call in the test code.

Can you elucidate on this?  What int32 indicator?

**Comment by rsbeckerca** [comment]
> 
> 
> > The issue seems to be that the int32 indicator is not being checked when the parameter is examined after the call in the test code.
> 
> Can you elucidate on this? What int32 indicator?

In 
```
typedef struct {
    OSSL_PARAM *param;
    int32_t i32;
    int64_t i64;
    uint32_t u32;
    uint64_t u64;
    double d;
    int valid_i32, valid_i64, valid_u32, valid_u64, valid_d;
    void *ref, *datum;
    size_t size;
} PARAM_CONVERSION;
```
The `valid_i32` value is `0` but I'm getting an indication of a supplied int32 in the test results. Once the other PRs are in place I can go retest and give you a snapshot and trace.

**Comment by paulidale** [comment]
The double conversion is erroneously returning 0, this is a valid int32 and will be returned as such.  The conversion code being tested doesn't know if the value is meant to be valid or not: it checks the range and returns it if an exact representation is possible.

**Comment by rsbeckerca** [comment]
@paulidale Would it be possible to have a quick Zoom/GotoMeeting call to debug this?

**Comment by paulidale** [comment]
Try running this on the target (build without optimising if possible):

``` C
#include <stdlib.h>
#include <stdio.h>

int main() {
    double e, d = 9007199254740991.;
    char *end;

    e = strtod("9007199254740991", &end);

    printf("d = %.2f\ne = %.2f\nend = %c (%d)\n", d, e, *end, *end);
    return 0;
}
```

I get this output:
```
d = 9007199254740991.00
e = 9007199254740991.00
end =  (0)
```

I'm guessing you'll get something different...

A call is possible.

**Comment by rsbeckerca** [comment]
> ```
> d = 9007199254740991.00
> e = 9007199254740991.00
> end =  (0)
> ```
> 
> I'm guessing you'll get something different...

```
d = 9007199254740991.00
e = 9007199254740991.00
end =  (0)
```
I'm as surprised as you are. ;)

**Comment by rsbeckerca** [comment]
@paulidale Please feel free to reach out to me via the email temporarily on my profile to set up a Zoom/GTM debug session.

**Comment by paulidale** [comment]
Busy week here.

In the meantime, would it be possible to track down where exactly the double becomes zero?

**Comment by rsbeckerca** [comment]
It appears that the double is initialized as zero and never changes.

**Comment by rsbeckerca** [comment]
@paulidale Do you have any available this week?

**Comment by paulidale** [comment]
Not this week, unlikely next.

The value is loaded here:

https://github.com/openssl/openssl/blob/bdde5b46c74852e38e660a16f64d7d8ba1c7c2e2/test/params_conversion_test.c#L106-L114

Why isn't it being set to a non-zero value?

It's being made the test primary here:

https://github.com/openssl/openssl/blob/bdde5b46c74852e38e660a16f64d7d8ba1c7c2e2/test/params_conversion_test.c#L167-L175


The value is converted to an integer here:

https://github.com/openssl/openssl/blob/bdde5b46c74852e38e660a16f64d7d8ba1c7c2e2/crypto/params.c#L205-L215


One of the three must be going wrong.

**Comment by rsbeckerca** [comment]
> The value is converted to an integer here:
> 
> https://github.com/openssl/openssl/blob/bdde5b46c74852e38e660a16f64d7d8ba1c7c2e2/crypto/params.c#L205-L215

The if at 209 is succeeding. In this compiler:
```
        double d = 0.0;
        if (d >= INT32_MIN && d <= INT32_MAX && d == (int32_t)d) {
                int32_t val = (int32_t) d;
                printf("Values are %f %d\n", d, val);
        }
```
and the output is: `Values are 0.000000 0`. Is the assumption that the test should fail due to the cast assuming that the `d != (int32_t)d`, because that clause of the if is `true` on this platform.

**Comment by paulidale** [comment]
The `d == (int32_t)d` is checking that the double can be represented exactly by a 32 bit integer.  It should succeed when d is zero.

The problem is that d is zero, it shouldn't be.  It is meant to be 9007199254740991 for the case originally mentioned.
The earlier test showed that the strtod works okay for this value.  Is the `d = *(const double *)p->data` working?  Either look at the raw data or replace it with a memcpy() call.

**Comment by rsbeckerca** [comment]
> 
> 
> The `d == (int32_t)d` is checking that the double can be represented exactly by a 32 bit integer. It should succeed when d is zero.
> 
> The problem is that d is zero, it shouldn't be. It is meant to be 9007199254740991 for the case originally mentioned.
> The earlier test showed that the strtod works okay for this value. Is the `d = *(const double *)p->data` working? Either look at the raw data or replace it with a memcpy() call.

When I supply `9007199254740991`, `strtod()` works and d is correctly set. The `d == (int32_t)d` is false, and `memcpy()` is inappropriate because the size of `double` `8` bytes while `int32_t` is `4` bytes. I don't see how the cast or pointer assignment is valid. I'm a bit lost as to what you're really intending here, because the value of p->data, if set to a double is safe in this case, but mixing type sizes is risky. If `p->data` was set to an `int32_t` that just happened to be at top of heap, and an attempt was made to compare with a double, a `SIGSEGV` would result.

**Comment by rsbeckerca** [comment]
@paulidale I found something suspicious in the generated code:

```
Value: 9007199254740991.000000, double = 8 bytes, int32_t = 4 bytes
9007199254740991.000000 >= -2147483648 (true)
9007199254740991.000000 <= 2147483647 (false)
9007199254740991.000000 == (int32_t)-1 (true)
9007199254740991.000000 == -1 (false)
```
There is no justification I can find for the third check being true. It looks like this may be a code generation defect in the compiler. Under `-O0`, the above happens. Under `-O2` the code evaluates correctly - third line is **false** - although the reported values are the same. I think the idea of introducing an intermediate variable to perform the cast check may be more appropriate now, like the `memcpy()` suggestion, but taking type length into account - alternatively just doing an assignment with a cast may still work.

Under gcc in Windows x86-64, the result is stable across optimizers (and different from on NonStop, Itanium and x86 big-endian):
```
Value: 9007199254740991.000000, double = 8 bytes, int32_t = 4 bytes
9007199254740991.000000 >= -2147483648 (true)
9007199254740991.000000 <= 2147483647 (false)
9007199254740991.000000 == (int32_t)-2147483648 (false)
9007199254740991.000000 == -2147483648 (false)
```
Before I go about attempting to instrument this, do you have any opinions/thoughts/baleful glaring looks at my compiler?

**Comment by rsbeckerca** [comment]
The previous analysis did not lead to a solution. In this case:
```
 pc->d = strtod(pp->value, &p);
```
on the second time (line 14) it is called, returns `2147483647`. When the optimizer is off, it returns 0. It should be 6 from what I could tell based on the test case. I'm at a loss as to why this is happening, but thing it is a compiler issue. I'm investigating further with regards to whether there is an address violation somewhere because I do get a `SIGSEGV` when trying to use `pp->value` after `strtod()` is called.

**Comment by rsbeckerca** [comment]
Serious question now for both @paulidale and @levitte: Is there a requirement to support IEEE float or can I go back to Tandem float? `strtod()` does not appear to produce valid results in IEEE mode. It changes the boundaries, however. I can live with limit failures but not complete conversion issues.

**Comment by rsbeckerca** [comment]
@levitte Taking neutral float off the build configuration seems to make 90% of the difference. The compiler bug/fix I found seems to solve this issue. I'm going through a build test cycle now, but expect a change to `50-nonstop.conf` as part of this.

**Comment by paulidale** [comment]
Glad you found it.  There is no need for this to be IEEE -- the test cases assume a little about IEEE format (mantissa length) but not a lot.

The cast and dereferences are all safe -- the OSSL_PARAM structure contains type and length information, so when the casting is done, it is always to the correct type.  The OSSL_PARAM design also guarantees correct alignment.

**Comment by rsbeckerca** [comment]
> 
> 
> Glad you found it. There is no need for this to be IEEE -- the test cases assume a little about IEEE format (mantissa length) but not a lot.
> 
> The cast and dereferences are all safe -- the OSSL_PARAM structure contains type and length information, so when the casting is done, it is always to the correct type. The OSSL_PARAM design also guarantees correct alignment.

Glad to hear it. We're going to deploy with IEEE float configured by default. I'm giving a Webinar/presentation in November for the NonStop community on how to build/deploy 3.0.0 with other settings for those who might not like our defaults. When released, anyone on NonStop with git will be able to build OpenSSL 3.0.0 with whatever configuration settings, memory models, threading models, float models, etc., they want without worrying about dependencies - just a c99 compiler which is pretty standard on the boxes. That's a pretty big win, from my point of view.
