### ISSUE TITLE
Build failing for libcrypto.so due to missing OSSL_ENCODER_CTX_get_encoder

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12937]
In OpenSSL 3.0.0 at commit 6600baa9bb, the `OSSL_ENCODER_CTX_get_encoder` is not exported in `libcrypto.a`, so the link of libcrypto.so fails on NonStop.

```
**** ERROR **** [1210]:
   crypto/pem/libcrypto-shlib-pem_all.o: In function `PEM_write_bio_PUBKEY':
   crypto/pem/libcrypto-shlib-pem_all.o(.text+0x1696): unresolved reference to
   OSSL_ENCODER_CTX_get_encoder.
```

**Comment by levitte** [comment]
Your conclusion isn't quite right.  The missing symbol is OSSL_ENCODER_CTX_get_encoder

**Comment by levitte** [comment]
Uhmmmm, how about trying a `make clean` first?

**Comment by rsbeckerca** [comment]
> 
> 
> Your conclusion isn't quite right. The missing symbol is OSSL_ENCODER_CTX_get_encoder

Yeah, I was asleep at the keyboard. Thanks.

**Comment by rsbeckerca** [comment]
I'm still getting
```
**** ERROR **** [1210]:
   crypto/pem/libcrypto-shlib-pem_all.o: In function `PEM_write_bio_PUBKEY':
   crypto/pem/libcrypto-shlib-pem_all.o(.text+0x1696): unresolved reference to
   OSSL_ENCODER_CTX_get_encoder.
```
on commit 434343f896.

**Comment by levitte** [comment]
Er, something's not quite right with your checkout.  When I do `git grep git grep OSSL_ENCODER_CTX_get_encoder` in the source, I get nothing, which is correct, it's been recently removed.

**Comment by rsbeckerca** [comment]
> 
> 
> Er, something's not quite right with your checkout. When I do `git grep git grep OSSL_ENCODER_CTX_get_encoder` in the source, I get nothing, which is correct, it's been recently removed.

Well (doh) that's because `make clean` is getting `arglist too long` errors and not cleaning up (around line 1423). I'm doing that manually and trying again on both platforms.

**Comment by rsbeckerca** [comment]
`make clean` should change line:
```
rm -f `find . -name '*.o' \! -name '.*' \! -type d -print`
```
to
```
find . -name '*.o' \! -name '.*' \! -type d -exec rm {} \;
```

**Comment by rsbeckerca** [comment]
@levitte the clean did the trick. We can close this case but open another with the Make line length issue.
