### ISSUE TITLE
make clean is failing with arglist too long errors on NonStop platforms.

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12938]
This was issue #12937. The rm lines in `make clean` can result in very long results coming back from find that exceed the maximum argument list size. Couple with the error being ignored left the build area in an unclean state.

Recommendation is to replace the `rm` with `find -exec`.

**Comment by paulidale** [comment]
Again, I recommend `xargs` because this is exactly what it was designed for.

**Comment by rsbeckerca** [comment]
> 
> 
> Again, I recommend `xargs` because this is exactly what it was designed for.

In this case, we're already running `find`. Adding `-exec rm {} \;` seems like a fairly innocuous change.

**Comment by levitte** [comment]
How does `xargs` work?  Would it just hit the same limits?

**Comment by richsalz** [comment]
xargs rewraps the input so that instead of one rm per file, it will be dozens per file (depends on the argc or arglen limit on the system).

**Comment by rsbeckerca** [comment]
> 
> 
> How does `xargs` work? Would it just hit the same limits?

From my tests, yes

**Comment by paulidale** [comment]
`xargs` reads a list of file names from stdin and appends them to the command it is given.  It breaks overlong lines and runs the commands multiple time.  Thus, `find . -print | xargs rm` is far more efficient than `find . -exec rm {} \;`

**Comment by rsbeckerca** [comment]
> 
> 
> `xargs` reads a list of file names from stdin and appends them to the command it is given. It breaks overlong lines and runs the commands multiple time. Thus, `find . -print | xargs rm` is far more efficient than `find . -exec rm {} \;`

Affirmative, in the case of `rm` this works on the platform. Where it has issues is when there are many other arguments on the command line, as with `ar`. For some reason, the line length calculation did not work properly there because of the archive name, I think missing by a few bytes, but would work in this situation (I tried it in the `rm -f` scenario).
