### ISSUE TITLE
Request test progress reporting for ffc_internal_test

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12942]
I know this may seem like a trivial thing, but the `ffc_internal_test` is entirely CPU bound. On the NonStop platform, which is not primarily intended as a computational engine, this causes the test to drop to the lowest possible priority because the operating system thinks the process is in a loop. It is not, of course. The problem is that this causes the test to run extremely slowly. A simple report of test i/n would cause this not to happen because of the I/O and kick up the speed that the test runs.

**Comment by slontis** [comment]
It takes about 3 seconds to run on my local machine..
It will be the key generation that is slow.
You could try some TEST_note("blah") in the code - but you only see these with V=1..

If you are having issues with this one then some of the ec ones must be really slow..

I cant really test this, so you would have to submit a PR.

**Comment by rsbeckerca** [comment]
I think I could live without this.
