### ISSUE TITLE
Supported "keys" in openssl.cnf key-value pairs?

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12946]
Could anybody guide me to a documentation (or similar) regarding what are the supported keys (i.e. from the key-value pair) that could be used for configuring sections in openssl.cnf.

i had a look at: https://www.openssl.org/docs/man1.1.1/man5/config.html
But, couldn't figure out much though.

Also had a look into the configuration options that STUNNEL provides: https://www.stunnel.org/static/stunnel.html#CONFIGURATION-FILE
Can these options be used?

**Comment by saddy-muchu** [comment]
I basically have all the command line args needed by s_server in the above conf file.
I want to provide this conf file as input to s_server. But, I don't see an option to give an input file as input to s_server.

Any other alternative?

**Comment by saddy-muchu** [comment]
i guess i overlooked it a bit.
s_server has the "-ssl_config" option.

Not sure if i could use that

**Comment by saddy-muchu** [comment]
Command used: openssl s_server -ssl_config conf.file -rev

Above command results in the below error though:

Can't open server.pem for reading, No such file or directory
281473412392560:error:02001002:system library:fopen:No such file or directory:../openssl-1.1.1d/crypto/bio/bss_file.c:69:fopen('server.pem','r')
281473412392560:error:2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1d/crypto/bio/bss_file.c:76:
unable to load server certificate private key file

**Comment by levitte** [comment]
What's supported depends on the application. For those supported by the `openssl ca` command, see the manual for that command, for example.

**Comment by saddy-muchu** [comment]
OK.
Thank you.
