### ISSUE TITLE
-addext ends up adding both CA:TRUE and CA:FALSE

### ISSUE THREAD

**Issue by apparebit** [openssl/openssl#12940]
I tried replacing the configuration file for creating a self-signed TLS certificate with `-addext` command line arguments. Unfortunately, OpenSSL 1.1.1g *implicitly* emits a `CA:TRUE` constraint while also adding my *explicit* `CA:FALSE` constraint, resulting in an invalid certificate.

When I generate the self-signed certificate with this extension configuration

```
basicConstraints=critical,CA:FALSE
keyUsage=digitalSignature,keyCertSign
extendedKeyUsage=serverAuth
```

the certificate correctly reflects the configuration

```
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Alternative Name: 
                DNS:localhost, IP Address:127.0.0.1, IP Address:0:0:0:0:0:FFFF:7F00:1
            X509v3 Key Usage: 
                Digital Signature, Certificate Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
```

However, when I generate the self-signed certificate with `-addext` command line arguments only

```
openssl req -x509 -newkey rsa:2048 -nodes -keyout the.key -subj '/CN=localhost' -days 30 \
    -addext 'basicConstraints = critical,CA:FALSE' \
    -addext 'keyUsage = digitalSignature,keyCertSign' \
    -addext 'extendedKeyUsage = serverAuth' \
    -addext 'subjectAltName = DNS:localhost,IP:127.0.0.1,IP:::ffff:7f00:1' \
    -out the.cert 
```

the resulting certificate contains contradictory basic constraints:

```
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Certificate Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:localhost, IP Address:127.0.0.1, IP Address:0:0:0:0:0:FFFF:7F00:1
```

I suspect that the `keyCertSign` results in an implicit addition of the `CA:TRUE` constraint. However, the explicit `CA:FALSE` should replace that constraint instead of being added to the list of extensions, which effectively invalidates the certificate.

**Comment by lukeyeager** [comment]
It is interesting to note that generating a certificate request (`req -new`) does not have the same issue as generating a self-signed certificate (`req -x509`):
```console
$ flags=( -key the.key -subj '/CN=localhost' -addext 'basicConstraints=critical,CA:FALSE' -addext 'keyUsage=digitalSignature,keyCertSign' -noout -text )
$ openssl req -x509 "${flags[@]}" 2>/dev/null | grep -A1 'Basic Constraints'
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Basic Constraints: critical
                CA:FALSE
$ openssl req -new "${flags[@]}"  2>/dev/null | grep -A1 'Basic Constraints'
            X509v3 Basic Constraints: critical
                CA:FALSE
```

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by apparebit** [comment]
@nhorman, I just tried with latest version of OpenSSL on Homebrew, 3.3.1, and it appears that somebody fixed the bug. The generated certificate only contains CA:FALSE, as requested. 🎉

**Comment by nhorman** [comment]
thank you for reporting back!
