### ISSUE TITLE
openssl s_client -connect: "Bad file descriptor" instead of "Connection refused".

### ISSUE THREAD

**Issue by StyXman** [openssl/openssl#12953]
> If relevant, please remember to tell us in what OpenSSL version you
found the issue.

```$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

On this version, when I have a connection refused error at  `connect()` time, I get the wrong error:

```
$ openssl s_client -connect 10.254.254.11:8443
socket: Bad file descriptor
connect:errno=9
```

Checking at the `strace` output, we can see why:

```
$ strace openssl s_client -connect 10.254.254.11:8443
[...]
socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
setsockopt(3, SOL_SOCKET, SO_KEEPALIVE, [0], 4) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(8443), sin_addr=inet_addr("10.254.254.11")}, 16) = -1 ECONNREFUSED (Connection refused)
close(3)                                = 0
close(3)                                = -1 EBADF (Bad file descriptor)
write(3, "socket: Bad file descriptor\n", 28) = 28
close(3)                                = 0
write(2, "connect:errno=9\n", 16)       = 16
[...]
```

So, basically, the code is reporting the error from a spurious, second call to `close()`, and not the error that caused `close()` to be called in the first place.

**Comment by kroeckx** [comment]
This is what I get with 1.1.1:
139973892289856:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:
139973892289856:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=111

And with master:
4027D59C9A7F0000:error::system library:BIO_connect:Connection refused:crypto/bio/b_sock2.c:125:calling connect()
4027D59C9A7F0000:error::BIO routines:BIO_connect:connect error:crypto/bio/b_sock2.c:127:
connect:errno=111

1.0.2 is no longer supported, and in newer versions it's fixed.
