### ISSUE TITLE
engine dynamic cmd line versus C call

### ISSUE THREAD

**Issue by clem844** [openssl/openssl#12954]
OpenSSL version: 1.1.1g
In openssl engines documentation, there is this example ([source](https://github.com/openssl/openssl/blob/master/README-Engine.md)):
```
 ENGINE *e = ENGINE_by_id("dynamic");
 ENGINE_ctrl_cmd_string(e, "SO_PATH", "/lib/libfoo.so", 0);
 ENGINE_ctrl_cmd_string(e, "ID", "foo", 0);
 ENGINE_ctrl_cmd_string(e, "LOAD", NULL, 0);
 ENGINE_ctrl_cmd_string(e, "CMD_FOO", "some input data", 0);
```
For testing, the "openssl engine" utility can be useful for this sort of thing. For example the above code excerpt would achieve much the same result as;
```
 openssl engine dynamic \
           -pre SO_PATH:/lib/libfoo.so \
           -pre ID:foo \
           -pre LOAD \
           -pre "CMD_FOO:some input data"
```

If I use the 2nd example in the terminal it works
```
root@raspberrypi3:~# openssl engine dynamic \
                                    -pre SO_PATH:/usr/lib/engines-1.1/pkcs11.so \
                                    -pre ID:pkcs11 \
                                    -pre LIST_ADD:1 \
                                    -pre LOAD \
                                    -pre MODULE_PATH:/usr/lib/libtpm2_pkcs11.so.0
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/usr/lib/engines-1.1/pkcs11.so
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
[Success]: MODULE_PATH:/usr/lib/libtpm2_pkcs11.so.0
Loaded: (pkcs11) pkcs11 engine
```
However the code looks like the 1st example and tests the result for each call. The problem is that "LOAD" command is not working if called individually. The `ENGINE_ctrl_cmd_string(e, "LOAD", NULL, 0);` returns an error. 
It seems the LOAD command should always be used with engine path. However the two examples are supposed to achieve the same result.

**Comment by kaduk** [comment]
Hi @clem844 

I'm sorry no one responded to you sooner (as it happens, the ENGINE interface is slated for deprecation, and so it's not terribly exciting to work on, even though it's still a supported interface for now).
If you closed the issue because you found the answer to your question, it would be very helpful for you to post the answer here, so that it is available if someone else is experiencing the same (or a similar) issue.

**Comment by clem844** [comment]
Hey, no solution found but the problem might also come from the module used. I opened an issue there too  (tpm2-software/tpm2-pkcs11#604)
If this will be deprecated, what's the new interface to use for hardware crypto delegation?

**Comment by levitte** [comment]
I believe that `pkcs11.so` needs to load another module for the actual implementation, and that's what `MODULE_PATH` is for.

As I understand it, `pkcs11.so` is merely an ENGINE\<-\>PKCS#11 "proxy" of sorts.

**Comment by kaduk** [comment]
The new "provider" interface in (the forthcoming) 3.0 release is supposed to be the successor to ENGINE (and more).
There are some links with more background at a previous answer to a similar question, at https://github.com/openssl/openssl/issues/11999#issuecomment-636387461

**Comment by clem844** [comment]
Ok, thanks a lot
