### ISSUE TITLE
It's too hard for a novice, I don't know how to do it with configuration parameters, I don't even know why the compile went wrong,Why isn't there a complete document

### ISSUE THREAD

**Issue by Damonxy** [openssl/openssl#12961]

**Comment by Damonxy** [comment]
I just wana a small cross complete for my 32bit device.

**Comment by levitte** [comment]
What are you trying to do?  If you tell us, we might be able to help you out

**Comment by slontis** [comment]
> I just wana a small cross complete for my 32bit device.

Did you mean 'I am trying to cross compile for a 32 bit android (version ??) device'?
Information that might be helpful
- type of device and the version and sdk version,
 - If you are cross compiling what type of machine are you building on,
 - What have you tried doing, and what error message did you get.
