### ISSUE TITLE
CMS_SignerInfo_verify() will most like not work with engine-supplied hash functions.

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#12969]
While looking over `EVP_DigestVerifyInit()`, I noticed the following code snippet:

https://github.com/openssl/openssl/blob/cdb5129e5c5fd8ad678c5efb1e87c91595d907b4/crypto/cms/cms_sd.c#L826-L850

As can be seen, the code tries fall back on legacy implementations if the MD implementation couldn't be fetched (lines 831-834), which might include finding an engine-supplied implementation...  however, the call to `EVP_DigestVerifyInit_with_libctx()` only uses the name, and thereby throws away everything legacy.  If the MD implementation was engine-supplied, that information is lost, and an attempt will be made to fetch it (again!) internally.

In case the MD was only available as an engine-supplied implementation, which is the case for anything GOST, `CMS_SignerInfo_verify()` will very simply fail.

I haven't looked at the rest of CMS (yet), but suspect that I might find similar cases elsewhere.

**Comment by beldmit** [comment]
Could you please tell me how to trigger it via cms command-line application? I'll check whether a test is currently present in the gost-engine test suite...

**Comment by levitte** [comment]
I think I found the answer to the mystery...  it seems that `EVP_DigestSignInit_with_libctx()` works as an "extended fetch", which is capable of getting legacy / engine implementations by name.  I hadn't quite understood that part...

**Comment by levitte** [comment]
So, er, this bug isn't a bug.  Closing.
