### ISSUE TITLE
ASN.1 DER: bug in encoding of DEFAULT value

### ISSUE THREAD

**Issue by indutny** [openssl/openssl#1297]
Section 11.5 of X.690 ( https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf ) says:

```
11.5 Set and sequence components with default value
The encoding of a set value or sequence value shall not include an encoding for any component value which is equal to its default value. 
```

However, OpenSSL's ASN.1 implementation doesn't seem to have a check for this. In fact, it produces invalid DER encoding for OCSP ResponseData of LetsEncrypt:

```
    0:d=0  hl=3 l= 219 cons: SEQUENCE
    3:d=1  hl=2 l=   3 cons: cont [ 0 ]
    5:d=2  hl=2 l=   1 prim: INTEGER           :00
    8:d=1  hl=2 l=  76 cons: cont [ 1 ]
   10:d=2  hl=2 l=  74 cons: SEQUENCE
   12:d=3  hl=2 l=  11 cons: SET
   14:d=4  hl=2 l=   9 cons: SEQUENCE
   16:d=5  hl=2 l=   3 prim: OBJECT            :countryName
   21:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :US
   25:d=3  hl=2 l=  22 cons: SET
   27:d=4  hl=2 l=  20 cons: SEQUENCE
   29:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
   34:d=5  hl=2 l=  13 prim: PRINTABLESTRING   :Let's Encrypt
   49:d=3  hl=2 l=  35 cons: SET
   51:d=4  hl=2 l=  33 cons: SEQUENCE
   53:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   58:d=5  hl=2 l=  26 prim: PRINTABLESTRING   :Let's Encrypt Authority X3
   86:d=1  hl=2 l=  15 prim: GENERALIZEDTIME   :20160708003300Z
  103:d=1  hl=2 l= 117 cons: SEQUENCE
  105:d=2  hl=2 l= 115 cons: SEQUENCE
  107:d=3  hl=2 l=  75 cons: SEQUENCE
  109:d=4  hl=2 l=   9 cons: SEQUENCE
  111:d=5  hl=2 l=   5 prim: OBJECT            :sha1
  118:d=5  hl=2 l=   0 prim: NULL
  120:d=4  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:7EE66AE7729AB3FCF8A220646C16A12D6071085D
  142:d=4  hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:A84A6A63047DDDBAE6D139B7A64565EFF3A8ECA1
  164:d=4  hl=2 l=  18 prim: INTEGER           :03D4C479F0C3C2B66CAF11DA87C1743CB343
  184:d=3  hl=2 l=   0 prim: cont [ 0 ]
  186:d=3  hl=2 l=  15 prim: GENERALIZEDTIME   :20160708000000Z
  203:d=3  hl=2 l=  17 cons: cont [ 0 ]
  205:d=4  hl=2 l=  15 prim: GENERALIZEDTIME   :20160715000000Z
```

The `cont[0]` and integer that follows it should not be present, because `0` is a DEFAULT value. I suspect that this happens because LetsEncrypt supplies this value in a first place, nevertheless this encoding is invalid and should not be produced, in my opinion.

cc @jsha @alubbe @richsalz 

See: https://github.com/indutny/ocsp/issues/12#issuecomment-231612777

**Comment by jsha** [comment]
I haven't had the opportunity to look at this hug yet, but Let's Encrypt
uses golang.org/x/crypto/ocsp to generate OCSP responses, not OpenSSL.

**Comment by indutny** [comment]
@jsha I am not a go expert, but is there a bug here:

https://github.com/golang/crypto/blob/master/ocsp/ocsp.go#L117

Shouldn't it be `default:0`?

**Comment by indutny** [comment]
@jsha FWIW PR for go/crypto https://go-review.googlesource.com/#/c/24841/

**Comment by richsalz** [comment]
Not a bug, says Henson:  The ASN.1 code attempts to keep the original encoding so if a DEFAULT value is present it retains it. That's a workaround so incorrectly encoded structures still work without breaking signatures over them.

**Comment by indutny** [comment]
@richsalz thank you for resolving it so fast! I'll try to get go's attention then!

**Comment by davidben** [comment]
I believe the X.509 code doesn't rely on this. Instead, `X509_CINF` uses `ASN1_SEQUENCE_enc` which avoids any re-encoding in signature verification. (Or rather, it still re-encodes, but `i2d` secretly pulls the cached value out.) Any reason why you all don't tag `OCSP_RESPDATA` the same? That seems a more controlled way of being able to verify signatures on whatever quirks you all decide to parse, without making your encoder output invalid things.

(But, yes, it seems the root problem is Go is encoding things wrong and should be fixed. Alas, my understand is enough implementations do this that receivers still need to accept both.)

**Comment by odeke-em** [comment]
@indutny would you mind opening an issue here https://github.com/golang/go/issues/new and then in your CL, please refer to it say it is `issue #XXY`
```
Fixes golang/#XXY
```
This way it can be brought to Go's attention and triaged. We are currently in a Go1.7 freeze but the tree should open up in a few weeks and then it can be fixed.

**Comment by shurcooL** [comment]
@odeke-em, you meant to say this, right?

```
Fixes golang/go#XXY.
```

It should [include the username and repository name](https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-a-different-repository) to reference the issue.

**Comment by odeke-em** [comment]
@shurcooL yes in deed that's what I meant to say. I'll def use that the next time, thanks for the correction.
