### ISSUE TITLE
Configure cannot guess the NonStop system automatically

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#12972]
With the help of [OpenSSL::config](https://github.com/openssl/openssl/blob/master/util/perl/OpenSSL/config.pm), `./Configure` now guesses all system flavors (even Windows) automatically from standard settings.  I know that for NonStop, there's the complication of different threading models, but maybe there's a possibility to do a good enough selection based on `uname` data, it would be a start.

@rsbecker, perhaps you have some ideas of "standard" host triplets that could be used to select at least some of the OpenSSL configs?  If you have `config.guess`, its answer in diverse environments could be a starting point.

**Comment by rsbeckerca** [comment]
> 
> 
> With the help of [OpenSSL::config](https://github.com/openssl/openssl/blob/master/util/perl/OpenSSL/config.pm), `./Configure` now guesses all system flavors (even Windows) automatically from standard settings. I know that for NonStop, there's the complication of different threading models, but maybe there's a possibility to do a good enough selection based on `uname` data, it would be a start.
> 
> @rsbecker, perhaps you have some ideas of "standard" host triplets that could be used to select at least some of the OpenSSL configs? If you have `config.guess`, its answer in diverse environments could be a starting point.

Who's config.guess would you like? I have loads.

uname -a:
```
NONSTOP_KERNEL hostname L20 05 NSX-D NSX NSX-D NonStop Kernel
```
So the significant bits are:
`uname -s: NONSTOP_KERNEL`
`uname -p: NSE` (Itanium)
`uname -p: NSX` (x86)
`uname -p: NSV` (x86 virtualized) - This is not certain at this stage and if you see it, you can use NSX.

You could use `uname -i` and will get something like `NSE-L` with a qualifier of the model that probably can be ignored.

The operating system versions probably won't help much. The NSR processor was the now unsupported MIPS box.

**Comment by levitte** [comment]
> Who's config.guess would you like? I have loads.

I leave it in your hands to decide, really.  You know much better than I what to choose, what corresponds best to the traditions surrounding NonStop and so on.

**Comment by rsbeckerca** [comment]
Just point me at the code to adjust ;)

**Comment by levitte** [comment]
I did, the `OpenSSL::config` link in https://github.com/openssl/openssl/issues/12972#issue-708330696...  either way, it's just to check the "standard" way to translate the `uname` values to host triplets, and it turns out that I have that on my system too :wink:

**Comment by rsbeckerca** [comment]
Missed the link. I can give some of this a shot soon; however, I am still trying to debug strtoimax/strtod in #12919.

**Comment by levitte** [comment]
Well, I [ahem] got you a starting point, see #12973
