### ISSUE TITLE
Error from ossl_statem_client_read_transition

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12979]
i get the below error:

281473688212912:error:141A10F4:SSL routines:ossl_statem_client_read_transition:unexpected message:../openssl-1.1.1d/ssl/statem/statem_clnt.c:395:

Basically, i'm running a s_server with -rev option and trying to connect a client to it via BIO_do_connect()
But BIO_do_connect() fails with the above error.

Code snippet is as follows:

................
sbio = BIO_new_ssl_connect(ctx);

BIO_set_conn_hostname(sbio, connect_str);
out = BIO_new_fp(stdout, BIO_NOCLOSE);
BIO_do_connect(sbio)
....................

Could anyone help me out with this?

**Comment by mattcaswell** [comment]
Hmm. Strange. Can you provide a wireshark trace (pcap file) of the connection?

**Comment by saddy-muchu** [comment]
I'm somehow unable to attach any file.
But the log from wireshark is:

"Alert (Level:Fatal, Description: Unexpected Message)"

The above log is "after" a "client hello" and it ends there. No further logs seen after the above error log.

**Comment by mattcaswell** [comment]
> But the log from wireshark is:

I'm interested in what happens before that. You might have to put the file inside a zip to get github to accept it. Alternatively you can email it to me direct. My email address is on this page:

https://www.openssl.org/community/omc.html

**Comment by saddy-muchu** [comment]
Thank you.

I've sent you a mail

**Comment by mattcaswell** [comment]
This is a very strange log indeed.

A typical handshake would look like this (from RFC5246):

````
      Client                                               Server

      ClientHello                  -------->
                                                      ServerHello
                                                     Certificate*
                                               ServerKeyExchange*
                                              CertificateRequest*
                                   <--------      ServerHelloDone
      Certificate*
      ClientKeyExchange
      CertificateVerify*
      [ChangeCipherSpec]
      Finished                     -------->
                                               [ChangeCipherSpec]
                                   <--------             Finished
      Application Data             <------->     Application Data
````

What we see in this trace is:

````
      Client                                           Server

      ClientHello                  -------->
                                   <--------      ClientHello
      Alert(UnexpectedMessage)     -------->
````

A server should always respond to an initial ClientHello from the client with a ServerHello response - but in this trace we get a ClientHello!! A server *never* sends a ClientHello. So this doesn't add up. You said you were using s_server with the "-rev" option. There is no way that this trace came from s_server. This is a client message - s_server will never send that. So unless there is some hitherto unnoticed fundamental bug in s_server (which seems unlikely) whatever it is you think you are connecting to - it isn't s_server.

Perhaps you can expand a little more on what you are trying to achieve and the steps you took to get this far.

**Comment by saddy-muchu** [comment]
Thanks for your analysis.

I basically have an echo application which sends some data to s_server , then this s_server sends it back to the client. The client finally receives it. All this is done using BIO_ api's (as you can see below)

i'm just trying to mimic an echo sort of a use-case.

.................................
    ctx = SSL_CTX_new(TLSv1_2_client_method());
    SSL_CONF_CTX_set_ssl_ctx(cctx, ctx);
    sbio = BIO_new_ssl_connect(ctx);

    BIO_get_ssl(sbio, &ssl);

    if (!ssl) {
        fprintf(stderr, "Can't locate SSL pointer\n");
        rc = 1;
        goto end;
    }

    /* Don't want any retries */
    SSL_set_mode(ssl, SSL_MODE_AUTO_RETRY);

    BIO_set_conn_hostname(sbio, connect_str);

    out = BIO_new_fp(stdout, BIO_NOCLOSE);
    if (BIO_do_connect(sbio) <= 0) {
        fprintf(stderr, "Error connecting to server\n");
        ERR_print_errors_fp(stderr);
        rc = 1;
        goto end;
    }

    if (BIO_do_handshake(sbio) <= 0) {
        fprintf(stderr, "Error establishing SSL connection\n");
        ERR_print_errors_fp(stderr);
        rc = 1;
        goto end;
    }

    BIO_puts(sbio, args->test_message);
    //for (;;) {
        len = BIO_read(sbio, tmpbuf, 1024);
        if (len <= 0)
            goto end;
        BIO_write(out, tmpbuf, len);
    //}
........................

I could see that BIO_do_connect() fails and hence i get "Error connecting to server" and "281473688212912:error:141A10F4:SSL routines:ossl_statem_client_read_transition:unexpected message:../openssl-1.1.1d/ssl/statem/statem_clnt.c:395:" error messages.

**Comment by kaduk** [comment]
Can you say how you are invoking `s_server`?  I agree with Matt, it seems most likely that `s_server` is not what you are connecting to.  Also, what does your `connect_str` look like?

**Comment by saddy-muchu** [comment]
s_server command used: openssl s_server -accept 127.0.0.1:1111 -tls1_2 -rev -CAfile <CA_file> -cert <Cert_file> -key <Key_file>

connect_str = 127.0.0.1:2222

Could this be because of a mismatched port number?

**Comment by kaduk** [comment]
> Could this be because of a mismatched port number?

Yes.  The connect_str has to match what the server is listening on (the `-accept` argument).

**Comment by saddy-muchu** [comment]
But, s_server complains as below:

281473131513456:error:02006062:system library:bind:Address already in use:../openssl-1.1.1d/crypto/bio/b_sock2.c:161:
281473131513456:error:20093075:BIO routines:BIO_bind:unable to bind socket:../openssl-1.1.1d/crypto/bio/b_sock2.c:162:

**Comment by mattcaswell** [comment]
> Address already in use:

This indicates that something else is already listening on the 2222 port. Which makes sense because we know from your wireshark trace that you got a reply on that port (the unexpected ClientHello). So what is it that is listening on that port?

**Comment by kaduk** [comment]
The `lsof` command can usually help find out what is listening on a given port.

**Comment by saddy-muchu** [comment]
Turns out that i need to explicitly send a "\n" in addition to the test message being sent from the client to s_server when -rev option is used. This is because for reversal to happen, s_server needs to know when the string ends
