### ISSUE TITLE
The FIPS DRBG has no fork protection

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12984]
The FIPS DRBG code does not currently implement fork protection. This should probably be fixed before beta 1.

Reference is:

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/crypto/threads_pthread.c#L198

**Comment by mattcaswell** [comment]
So, it looks to me like the TODO comment is actually inaccurate. Although it says "No fork protection in FIPS module yet" this does not seem to be the case. What is not in the FIPS module and is excluded in this code is the code that calls OPENSSL_fork_prepare(), OPENSSL_fork_parent() and OPENSSL_fork_child() when we detect a fork. But those functions are no-ops anyway. All this code looks redundant.

The DRBG has its own fork detection code entirely independent of this code and, AFAICT, this should work in the FIPS module.

I'll leave this issue open until the comments are fixed, but I don't think this needs to be resolved for beta 1. Taking this issue out of that milestone.

**Comment by paulidale** [comment]
The DRBGs do have fork() protection.  I think this TODO should be removed
I didn't realise it was present and this file wasn't touched by the RAND changes so easily missed.

**Comment by paulidale** [comment]
I suspect the comment is more about other uses for fork detection/protection.  I'm not sure they are relevant to FIPS.
