### ISSUE TITLE
Add CPU randomizer capability on NonStop Itanium architecture

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12988]
In order to support FIPS, a hardware randomizer is desirable for the NonStop Itanium (NSE) platform. This continues the discussion from #12923.

NonStop is a MPP architecture for real time clocks in each of 16 CPUs and a software clock that runs at variable adaptive speed that aggregates time across all CPUs. Calls into the operating system have no guaranteed timing and are subject to interrupts, system activity, and message system uncertainty. A RNG is proposed based on a combination of those, as follows:

```
unsigned long get_sys_random(void) {
        unsigned long long nanos = TS_NANOSECS_() % UINT_MAX ;
        unsigned long long micros = JULIANTIMESTAMP() % UINT_MAX;
        unsigned long long inverted_micros = (micros % 65536LL << 16LL)
                + (micros / 65536LL);
        unsigned long long random = (nanos * inverted_micros) % UINT_MAX;
        return (unsigned long) random;
}
```

The current testing, based on the FIPS-140-2 test results in:
```
============== Summary results of FIPS-140-2 ==============

 Generator:        nse_gsr
 Number of bits:   20000

       Test          s-value        p-value    FIPS Decision
 --------------------------------------------------------
 Monobit               9854           0.98       Pass
 Poker                14.00           0.53       Pass

 0 Runs, length 1:     2519                      Pass
 0 Runs, length 2:     1242                      Pass
 0 Runs, length 3:      648                      Pass
 0 Runs, length 4:      336                      Pass
 0 Runs, length 5:      165                      Pass
 0 Runs, length 6+:     150                      Pass

 1 Runs, length 1:     2609                      Pass
 1 Runs, length 2:     1248                      Pass
 1 Runs, length 3:      614                      Pass
 1 Runs, length 4:      313                      Pass
 1 Runs, length 5:      137                      Pass
 1 Runs, length 6+:     140                      Pass

 Longest run of 0:       14           0.46       Pass
 Longest run of 1:       13           0.50       Pass
 ----------------------------------------------------------
 All values are within the required intervals of FIPS-140-2
```

**Comment by rsbeckerca** [comment]
Background: the `JULIANTIMESTAMP()` OS call is an aggregate variable pace clock that summarizes time to microsecond resolution with drift compensation that introduces chaos. The `TS_NANOSECS_()` method is a real time clock that exists in each CPU independently and starts when an individual CPU is cold-loaded. The likelihood of any two CPUs having the same TS_NANOSECS_() result is highly unlikely since cold-loads are not instantaneous or resumable. Times to call `TS_NANOSECS_()` are quasi-deterministic when the system is idle but non-deterministic when there is activity in the CPU and the process performing the call runs at an application priority.

Both values are monotomically increasing and non-repeating while a CPU remains operational. There is a possibility that two processes in different CPUs may obtain the same value of `TS_NANOSECS()` but not `JULIANTIMESTAMP()` simultaneously based on architectural and message system constraints. It is also possible to obtain the same `JULIANTIMESTAMP()` value in two processes but not with the same `TS_NANOSECS()` value except in a highly unlikely situation of the two CPUs being cold-loaded within the `JULIANTIMESTAMP()` inter-call time interval. The minimum inter-call time between invocations of `TS_NANOSECS_() ` in one process is approximately `131ns` on an idle system. The minimum inter-call time for `JULIANTIMESTAMP()` is 1 microsecond. The values on the x86 platform variant are significantly smaller with strong probability of `JULIANTIMESTAMP()` inter-call times being 0 microseconds, making this technique impractical for the x86 platform variant.

Note that no new hardware speed improvements are being made to the NonStop Itanium platform, which is planned to go out of support within the next few years, to invalidate this analysis.

**Comment by rsbeckerca** [comment]
Well, FIPS mode is not supported by `Configure`, so perhaps this is a moot point after all.

**Comment by rsbeckerca** [comment]
> 
> 
> Well, FIPS mode is not supported by `Configure`, so perhaps this is a moot point after all.

I'm not sure why FIPS is not supported on this platform, however. It seems that HP-UX Itanium 2 can do it, and this is the virtually the same processor. `Configure` was run with:
```
./Configure nonstop-nse --prefix=/usr/local-ssl3.0 --openssldir=/usr/local-ssl3.0/ssl --with-rand-seed=rdcpu fips --debug
```

**Comment by paulidale** [comment]
The NIST test suite needs to run on the unwhitened entropy.  Your function is whitening the values.
Are you using the SP 800-90B tests?  The output doesn't look like it.
What does TestU01 give?

**Comment by rsbeckerca** [comment]
> 
> 
> The NIST test suite needs to run on the unwhitened entropy. Your function is whitening the values.
> Are you using the SP 800-90B tests? The output doesn't look like it.
> What does TestU01 give?

Which test from TestU01? I'm using `bbattery_FIPS_140_2 (gen);`

Running the BigCrush and bbattery_FIPS_140_2 tests now (it will take a while) and will post results.

**Comment by paulidale** [comment]
BigCrush is the gold standard.

**Comment by rsbeckerca** [comment]
With `-O2`, the gaps between calls to `TS_NANOSECS_()` is pretty constant at `118ns`, even when the system is running pretty hot. Not getting the chaos I wanted from this. Even if I hit the OS between every call, the gaps just move to `295ns`. The gaps for `JULIANTIMESTAMP()` are stable at `1us` so no chaos there. I doubt that the technique in `rand_unix.c` will work either, because there are no kernel threads to introduce any chaos on this platform, so maybe that's part of it. I'm not happy about this at all.

**Comment by rsbeckerca** [comment]
Moving on, I'm going to see whether I can adapt the choronex jitter technique to something on the platform. Should I bother is the question.

**Comment by rsbeckerca** [comment]
> 
> 
> Moving on, I'm going to see whether I can adapt the choronex jitter technique to something on the platform. Should I bother is the question.

I have the jitter library ported and will run some tests on whether it make sense to use on NonStop.

**Comment by rsbeckerca** [comment]
> 
> 
> > Moving on, I'm going to see whether I can adapt the choronex jitter technique to something on the platform. Should I bother is the question.
> 
> I have the jitter library ported and will run some tests on whether it make sense to use on NonStop.

I tried out the jitter library from choronex but there is just not enough jitter in the querying of the RTC on NonStop Itanium to even pass the FIPS test suite (unlike my original technique that did). I'm going to put this aside for a bit and try to consult some of the hardware people.
