### ISSUE TITLE
Possibly missed deprecations

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12980]
There are some TODOs in the code that suggest that certain things should be deprecated but haven't yet been.

These should be resolved one way or the other before beta 1.

The TODOs in question are:

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/rsa.h#L67-L68
 
https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/rsa.h#L284-L285

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/rsa.h#L356-L358

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/dh.h#L176-L179

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/dh.h#L201-L202

**Comment by mattcaswell** [comment]
Also this one:

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/err.h.in#L375-L381

**Comment by kaduk** [comment]
It looks like 9d2d857f135abd281591ee0c2b58e01a710c3cea has already removed the `DH_new_by_nid()` call from `s3_lib.c` so that TODO can go with no changes.

I think I would agree with deprecating the `ERR_get_error_*()` functions, for the stated reason.

**Comment by mattcaswell** [comment]
All the RSA TODO's were resolved by #13096.
All the DH TODO's will be resolved once #13138 is merged.

That just leaves the ERR ones.

**Comment by mattcaswell** [comment]
````
   * TODO(3.0) consider if the following three functions should be deprecated. 
  * They all drop the error record from the error queue, so regardless of which 
  * one is used, the rest of the information is lost, making them not so useful. 
  * The recommendation should be to use the peek functions to extract all the 
  * additional data. 
````
I'd like more opinions on this one. Up until now deprecations have typically been done because the "old" way doesn't really fit very well with the "new" way of doing things. This doesn't seem to be the case here. It's more that we don't think these functions are all that useful. But is that sufficient reason to deprecate them? I'm unsure.

**Comment by levitte** [comment]
> I'd like more opinions on this one. Up until now deprecations have typically been done because the "old" way doesn't really fit very well with the "new" way of doing things. This doesn't seem to be the case here. It's more that we don't think these functions are all that useful. But is that sufficient reason to deprecate them? I'm unsure.

I would argue that the `peek` variants of the same functions are better, as they don't drop the error record.  I wonder, for example, how useful it is to `ERR_get_error_func()` and then not be able to `ERR_get_error_line()`, or perhaps mistakenly do that and get the line from the *next* error record in the queue, and then have that one dropped as well to boot!

**Comment by richsalz** [comment]
I vote for deprecating the dangerous ones in favor of ERR_get_error_all or individual peek.

**Comment by levitte** [comment]
I would even drop `ERR_get_error_all()`, as it doesn't retrieve the error code, just the extra data that's attached to the record (file name, line number, function name, extra text).

**Comment by levitte** [comment]
(note that `ERR_get_error_func()` and `ERR_get_error_data()` are new in master, so they can actually be dropped, not just deprecated)

**Comment by levitte** [comment]
#13466 is my answer regard the ERR TODOs.

**Comment by t8m** [comment]
In current master I see only these TODOs related to deprecations:
https://github.com/openssl/openssl/blob/master/include/openssl/dsa.h#L97
https://github.com/openssl/openssl/blob/master/include/openssl/ocsp.h.in#L201

**Comment by richsalz** [comment]
OCSP fix is in #13064

**Comment by richsalz** [comment]
I'm not sure how the original list was generated, but
```
; g grep --fixed 'TODO(3.0)' | wc -l
181
```

**Comment by slontis** [comment]
This issue looks like it is all addressed now. Can this be closed?

**Comment by t8m** [comment]
Yes, IMO we have separate issues for other TODOs and further deprecations. Closing.
