### ISSUE TITLE
API name for EVP_PKEY_param_fromdata_settable

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12989]
There is a TODO  in the code that suggests we might want to consider EVP_PKEY_param_settable() as a better name for this API function (it also talks about a gettable variant which doesn't seem to exist at all). Should we rename it?

Reference:

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/crypto/evp/pmeth_gn.c#L392-L398

**Comment by levitte** [comment]
I think we should.  Basically, these return the OSSL_PARAM descriptors for import and export, but the public API doesn't specifically mention importing or exporting.  *For the moment*, this is only useful with the fromdata functionality, but we may find that we want to get (and possibly set) individual numbers, and these same descriptors would be useful with such functionality too, so having it seemingly tied to the fromdata functionality is illusionary

**Comment by levitte** [comment]
We currently don't have `EVP_PKEY_param_gettable()`, but we do have everything we need to implement it.

**Comment by slontis** [comment]
I completely disagree with the rename
EVP_PKEY_param is too confusing. (This sound like domainparams).

**Comment by t-j-h** [comment]
EVP_PKEY_fromdata_settable with an extra arg that is the evp_keymgmt_import_types second argument 
(i.e. OSSL_KEYMGMT_SELECT_ALL_PARAMETERS for "param" and OSSL_KEYMGMT_SELECT_ALL for "key")

Hence we remove the two separate functions.

**Comment by levitte** [comment]
Note that for EVP_PKEY use, we do have the macros EVP_PKEY_KEY_PARAMETERS and EVP_PKEY_KEYPAIR.  Less to type, and since this is EVP_PKEY stuff, they are suitable name wise
