### ISSUE TITLE
Decode related TODOs

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12982]
There are a couple of TODOs which suggest code needs to be rewritten for Decoder support - but that rewrite hasn't occurred. Does something still need to be done? I'm unsure if there is missing functionality so adding to beta 1 for now.

References are:

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/crypto/store/store_result.c#L341-L346

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/crypto/store/store_result.c#L364-L368

**Comment by levitte** [comment]
This is an easy one, but not a stopper for beta1.  However, considering how easy this is to fix, PR coming up!

**Comment by levitte** [comment]
BTW, this is STORE related more than DECODER related...

**Comment by levitte** [comment]
Fix in #12986

**Comment by levitte** [comment]
> Can you also provide an opinion on this one:
> 
> https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/dsa.h#L77-L80

Yeah...  I think the TODO should be removed.  We *could* consider deprecation, but since this is functionality that exists in pre-3.0 OpenSSL, straight out removal is not the right move now.

**Comment by mattcaswell** [comment]
Since there's no missing code (just code that needs cleaning up and removing), I'm taking this out of the beta 1 milestone.
