### ISSUE TITLE
Downgrade of key in EVP_PKEY2PKCS8()

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12990]
We are deliberately downgrading a key in the function EVP_PKEY2PKCS8() which suggests missing functionality.

Do we need to implement something?

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/crypto/evp/evp_pkey.c#L80-L81

**Comment by levitte** [comment]
Ah, that could actually be implemented using OSSL_ENCODER.

I don't see this as a beta1 blocker.

**Comment by mattcaswell** [comment]
> Ah, that could actually be implemented using OSSL_ENCODER.

That answer suggests to me that we've missed implementing something, i.e. its not just a minor bug fix - its new code that needs to be written. This, in my mind, means it should be in for beta 1.

**Comment by levitte** [comment]
> That answer suggests to me that we've missed implementing something, i.e. its not just a minor bug fix - its new code that needs to be written. This, in my mind, means it should be in for beta 1.

The thing that isn't done yet is to reimplement the inside of `EVP_PKEY2PKCS8` so that it uses OSSL_ENCODER.  The encoders are already in place, so I don't quite see how this adds new features, especially publicly.  So, I disagree re how quickly this must be done.

**Comment by levitte** [comment]
#12995
