### ISSUE TITLE
"openssl pkcs12 -info -legacy" does not honor "-nodes" or "-noenc"

### ISSUE THREAD

**Issue by wangweij** [openssl/openssl#12994]
The following command runs smoothly without any user interaction:

    openssl pkcs12 -passin pass:changeit -noenc -info -in p12

but adding a `-legacy` prompts for passout. I can also confirm if `-passout` is added on the command line, the keys are encrypted.

Tried the new (?) `-noenc` option. Same observation.

Please note the p12 file here is actually not using legacy algorithms. If one is used, the first command would fail (as expected) and the second one still prompts for a password.

I'm using openssl I compiled just now synced with the master branch here.

**Comment by kaduk** [comment]
Hi Max, long time no see!

This is a clear bug; at the end of the "use legacy" block at https://github.com/openssl/openssl/blob/d93bded6aa2852e681de2ed76fb43c415687af68/apps/pkcs12.c#L364-L384 we clobber `enc` even if it was previously cleared by the `-noenc` option.

Do you want to put together a pull request?

**Comment by t8m** [comment]
This was fixed with #13534
