### ISSUE TITLE
I can't get the full string when I decrypt it.

### ISSUE THREAD

**Issue by lanxiaolin-sz** [openssl/openssl#13006]
Dear,
I can't get the full string when I'm decrypting.
 encrypt secret:6yy2dqTco8rMdFV3eDgc/jNfs3NlxJaJrPjy/zl7BJ5GP+zXpyPHOBXMBC6nXSPk
 decrypt secret:6yy2dqTco8rMdF
The end of the string is missing.

How should the last parameter of the function EVP_CipherUpdate be determined when I decrypt it?

encrypt

    unsigned char* keystring=“some code“;//128bytes

    EVP_CIPHER_CTX *ctx;
    ctx = EVP_CIPHER_CTX_new();
    unsigned char* ivec=(unsigned char*) malloc(1024);
    unsigned char* en_secret=(unsigned char*) malloc(1024);
    memset((unsigned char*)&ivec, 0, strlen(ivec));
    
    int en_secretLen=0;

    EVP_CipherInit_ex(ctx, EVP_aes_128_ecb(), NULL, keystring, ivec, 1);

    EVP_CipherUpdate(ctx, en_secret, &en_secretLen, secret, strlen(secret));
    int encLen = en_secretLen;
    EVP_CipherFinal_ex(ctx, en_secret+en_secretLen, &en_secretLen);
    encLen += en_secretLen;
    
    EVP_CIPHER_CTX_cleanup(ctx);
    en_secret[encLen]='\0';

decrypt     

    unsigned char* keystring=“some code“;//128bytes
    int decLen = 0;
    int outlen = 0;
    unsigned char* result=(unsigned char*) malloc(1024);
    memset((unsigned char*)&result, 0, strlen(result));
    memset((unsigned char*)&ivec, 0, strlen(ivec));
    EVP_CIPHER_CTX *ctx2;
    ctx2 = EVP_CIPHER_CTX_new();
    EVP_CipherInit_ex(ctx2, EVP_aes_128_ecb(), NULL, keystring[0], ivec, 0);
    
    EVP_CIPHER_CTX_set_padding(ctx2, EVP_PADDING_PKCS7);

    EVP_CipherUpdate(ctx2, result, &outlen, en_secret,strlen(en_secret));

    decLen = outlen;
    EVP_CipherFinal_ex(ctx2, result+outlen, &outlen);
  
    decLen += outlen;

    result[decLen] = '\0';
 
    EVP_CIPHER_CTX_cleanup(ctx2);

**Comment by slontis** [comment]
You are doing multiple things wrong...

1) using strlen on an (unsigned char[]) array of bytes is a very bad idea - since the output can contain 0.
If you have an unsigned char array it is not a string and should be printed out using a loop.

2) EVP_CIPHER_CTX_set_padding() enables or disables padding.. 
This looks incorrect - you normally only use this to disable padding - So setting to 0 would disable padding.
If you were going to use this it would normally go into both the encrypt and decrypt.
3) Look here to see if you think ecb mode is a good idea.. https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation


Here is some code that works.


```
unsigned char key[] = "012345678901234567890123456789";  
EVP_CIPHER_CTX *ctx = NULL, *ctx2 = NULL;
int en_secretLen=0, decLen = 0, outlen = 0, encLen = 0, ret = 0;                                                                                            
unsigned char secret[18] = {  
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 
    0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10,  
    0x11, 0x12  };  
unsigned char *result = (unsigned char *)OPENSSL_zalloc(1024); 
unsigned char *ivec = (unsigned char *)OPENSSL_zalloc(16);
unsigned char *en_secret = (unsigned char *)OPENSSL_zalloc(1024); 
                                                      
ctx = EVP_CIPHER_CTX_new(); 
/* Note iv is not used by ecb mode */
ret = EVP_CipherInit_ex(ctx, EVP_aes_128_ecb(), NULL, key, ivec, 1); 
ret = EVP_CipherUpdate(ctx, en_secret, &en_secretLen, secret, sizeof(secret));
encLen = en_secretLen; 
ret = EVP_CipherFinal_ex(ctx, en_secret+en_secretLen, &en_secretLen); 
encLen += en_secretLen;
EVP_CIPHER_CTX_cleanup(ctx); 

ctx2 = EVP_CIPHER_CTX_new(); 
ret = EVP_CipherInit_ex(ctx2, EVP_aes_128_ecb(), NULL, key, ivec, 0);                                                                                                           ret = EVP_CipherUpdate(ctx2, result, &outlen, en_secret, encLen); 
decLen = outlen; 
ret = EVP_CipherFinal_ex(ctx2, result+outlen, &outlen);
decLen += outlen; 
EVP_CIPHER_CTX_cleanup(ctx2);
```

**Comment by paulidale** [comment]
ECB is generally not a good idea.
Use something else.
