### ISSUE TITLE
Getting random data failed on some embedded Linux platforms

### ISSUE THREAD

**Issue by millikk** [openssl/openssl#13002]
Hello everybody! I build a static `openssl-1.1.1g` library for the `armv7` platform with `Linux kernel 4.9.37`. The problem is that the toolchains (arm-himix-200-linux) provide the `getentropy()` function, which actually is not implemented: it always returns -1 and sets errno to the `ENOSYS`. This confuses the logic of the openssl's `syscall_random()` function (see crypto/rand/rand_unix.c:345): it takes that dummy `getentropy()` function, because it's pointer is not NULL, calls it and returns. So there's no chance to check if the `__NR_getrandom` syscall is available (btw: on the target platform it's just available). So I'd like to suggest the more robust logic:

```
--- a/crypto/rand/rand_unix.c
+++ b/crypto/rand/rand_unix.c
@@ -367,8 +367,12 @@ static ssize_t syscall_random(void *buf, size_t buflen)
 #  if defined(__GNUC__) && __GNUC__>=2 && defined(__ELF__) && !defined(__hpux)
     extern int getentropy(void *buffer, size_t length) __attribute__((weak));

-    if (getentropy != NULL)
-        return getentropy(buf, buflen) == 0 ? (ssize_t)buflen : -1;
+    if (getentropy != NULL) {
+        if (getentropy(buf, buflen) == 0)
+            return (ssize_t)buflen;
+        else if (errno != ENOSYS)
+            return -1;
+    }
```

P.S.: Of course I did a workaround in my application that uses openssl: I implemented my own `getentropy()` function that calls `__NR_getrandom` syscall like it's implemented in the `glibc` library. But I think it would be better to solve this issue inside the openssl because there may be a lot of wrong toolchains like mine

Thanks in advance!

**Comment by paulidale** [comment]
Is there a possibility of you making your change available to the project as a pull request?

**Comment by millikk** [comment]
@paulidale , sure. But I need some time for it. Thanks for reply

**Comment by millikk** [comment]
@paulidale , I prepared the fix but I can't push my branch to the repository because I have no permissions. Could you help me with this problem?

**Comment by paulidale** [comment]
Thanks for taking the time and effort to get these though the review process.
