### ISSUE TITLE
OBJ_nid2obj doesn't reliably push error

### ISSUE THREAD

**Issue by stbuehler** [openssl/openssl#13008]
Hi,

`OBJ_nid2obj` doesn't push the `OBJ_F_OBJ_NID2OBJ::OBJ_R_UNKNOWN_NID` error if the requested `nid` is beyond the static range and no "dynamic" NIDs were defined (`added == NULL`).

Afaict this could happen if:
- the user simply provides an invalid NID
- the program was built against a more recent version than it is run with

Source code links:
- [current master](https://github.com/openssl/openssl/blob/8c27ee6e056257ab872598bb2a410b23f6c411a0/crypto/objects/obj_dat.c#L236-L237)
- [current openssl1.1.1-stable](https://github.com/openssl/openssl/blob/5c2c624e2e8c50368a081fdd5ff8cb33e1124187/crypto/objects/obj_dat.c#L231-L232)

**Comment by hlandau** [comment]
I believe this is now fixed. https://github.com/openssl/openssl/blob/master/crypto/objects/obj_dat.c#L299-L324

But it looks like it's still unfixed in 1.1.1. https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/objects/obj_dat.c

Will get a fix for this.

**Comment by paulidale** [comment]
Should be fixed after #17808 was merged.
