### ISSUE TITLE
Error in the make process for android.

### ISSUE THREAD

**Issue by vmprog** [openssl/openssl#13007]
Hello!
I have a trouble with building process.
Host system: SMP Debian 5.7.6-1(2020-07-01) i686 GNU/Linux
Target system: Samsung Galaxy s3 32bit ARMv7
My steps:
export ANDROID_NDK_ROOT=/home/kl/android/android-ndk-r21d
PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$ANDROID_NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH
./Configure android-arm -D__ANDROID_API__=21
:~/android/openssl$ ./Configure android-arm -D__ANDROID_API__=21
Configuring OpenSSL version 3.0.0-alpha7-dev for target android-arm
Using os-specific seed configuration
Creating configdata.pm
Running configdata.pm
Creating Makefile

perl configdata.pm --dump
  __CNF_LDFLAGS =
  __CNF_LDLIBS =

Makevars:

    AR              = llvm-ar
    ARFLAGS         = rs
    CC              = clang
    CFLAGS          =  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64
    CPPDEFINES      = __ANDROID_API__=21
    CPPFLAGS        =  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64
    CPPINCLUDES     =
    CXX             = /arm-linux-androideabi-g++
    CXXFLAGS        =  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -frtti -fexceptions
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =  -march=armv7-a -Wl,--fix-cortex-a8
    LDLIBS          =
    PERL            = /usr/bin/perl
    RANLIB          = :
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl

$make

/home/kl/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar: 1: 6: not found
/home/kl/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar: 1: ELF: not found
/home/kl/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar: 16: Syntax error: Unterminated quoted string
$make[1]: *** [Makefile:2339: apps/libapps.a] Error 2

$ls /home/kl/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
$llvm-ar

Please help me.

**Comment by mattcaswell** [comment]
Is this still an issue with the latest alpha release?

**Comment by mattcaswell** [comment]
Ping? is this still an issue?

**Comment by mattcaswell** [comment]
No response from OP, so closing this issue.
