### ISSUE TITLE
why `pkeyutl: Unknown option: -sig` ? openssl-3.0.0-alpha6

### ISSUE THREAD

**Issue by niXman** [openssl/openssl#13009]
Hi,

I am trying to use `openssl-3.0.0-alpha6` for signing using Ed25519.

I downloaded the [archive](https://github.com/openssl/openssl/archive/openssl-3.0.0-alpha6.tar.gz) and built it from sources for `linux-x86_64`
after building I installed it in the `/home/user/openssl` directory.
after that I exported `LD_LIBRARY_PATH`: `export LD_LIBRARY_PATH=/home/user/openssl/lib`.

1. to gen secret key: `/home/user/openssl/bin/openssl genpkey -algorithm Ed25519 -out priv.pem` - OK
2. to gen public key: `/home/user/openssl/bin/openssl pkey -in priv.pem -pubout -out pub.pem` - OK
3. to sign: `/home/user/openssl/bin/openssl pkeyutl -sign -inkey priv.pem -out sig.dat -rawin -in /bin/ls` - OK
4. to verify: `/home/user/openssl/bin/openssl pkeyutl -verify -pubin -inkey pub.pem -rawin -in /bin/ls -sig sig.dat` - ERROR
> pkeyutl: Unknown option: -sig

what am I doing wrong?

thanks!

**Comment by beldmit** [comment]
Try `-sigfile` instead

**Comment by niXman** [comment]
yes, it works, thank you @beldmit !
