### ISSUE TITLE
How to determine List of Ciphers supported by Server from Client ?

### ISSUE THREAD

**Issue by sratnesh** [openssl/openssl#13024]
Hi , 

I want to determine List of Ciphers supported by Server from Client ?

Please guide with exact API to use 

Thanks

**Comment by kaduk** [comment]
There's not a protocol message to do this; you have to manually iterate through each cipher, attempt a connection with only that cipher, and assume that the server does not support that cipher if the connection fails.  Note that (especially prior to TLS 1.3), some ciphers have preconditions for use, so you can get false negatives pretty easily.

This, of course, does raise the question of why you think you need to know this information...

**Comment by sratnesh** [comment]
I am developing a application where I want to log errors due to cipher mismatch .
So my area of interest is to get errors .

So in this case If I manually iterate through list of ciphers and initiate connection and if ciphers are not supported then what error code ( what will be exact error message ) ? How I will know from error that  ok the corresponding cipher is not supported  and due to that ssl connection has failed .

Does Openssl throws any error that the cipher used is not supported by server ? If so then which API I can use to know ?
and what will be error code ?

Thanks
Ratnesh

**Comment by t8m** [comment]
The only way to distinguish is to try to infer the difference from different alerts the server sent, but it of course depends on the server implementation whether it will be really distinguishable.
