### ISSUE TITLE
DSA related TODO

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13020]
This TODO was originally listed as part of #12982, but in #12986 @levitte asked me to open it as a separate issue.

Since this appears in a public header, do we need to take any action before beta 1?

https://github.com/openssl/openssl/blob/53c4992e0b1c79bdf5904b84e77ca7d362cc4af0/include/openssl/dsa.h#L77-L80

**Comment by kaduk** [comment]
These do seem like candidates for deprecation, given the other infrastructure we have in place.
That said, `apps/dhparam.c` uses `d2i_DSAparams_bio()`, and `providers/implementations/encode_decode/encode_key2any.c` uses `i2d_DSAparams_bio()`, so we'd have to do the work to update those call sites before effectuating the deprecation.

**Comment by t-j-h** [comment]
Until we are completely sure that the EVP_PKEY layer can handle everything so that EVP_PKEY_get0_DSA and the other _get0_XXX's never need to be used, these all need to remain.

Topic was discussed at the OTC virtual face to face meeting (day 1) with more discussion to follow on day 2.

**Comment by kaduk** [comment]
What is the threshold for "completely sure"?  "Just" a thorough code audit? This sounds like a recipe for never getting rid of anything -- marking something as deprecated is not a guarantee that it will be removed at any particular time, and it would help crowdsource detection of cases where the EVP_PKEY layer is insufficient.

**Comment by t-j-h** [comment]
Moving the low-level apps across to the EVP interface is how to the "sure" at a reasonable level. Right now there are **major** gaps at the EVP_PKEY layer that are being worked through.

**Comment by kaduk** [comment]
Thanks for the extra detail; that sounds like a good plan to me.

**Comment by mattcaswell** [comment]
There are no instances of the macros that this comment is referring to being used anywhere within current master. All of the macros were deprecated by commit f41ac0e. Therefore I think this comment should just be removed.
