### ISSUE TITLE
OpenSSL configuration at installation: NASM is missing

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [openssl/openssl#1303]
Hello!

My obstacle occurs when I tried to install OpenSSL on Windows. I installed Perl as it should be, and met all requirements given. I also installed NASM into the c:\Users\user\AppData\Local\NASM directory.

So when I tried to run `perl Configure VC-WIN32`, I got the error as though I didn't installed NASM. 

I tried to add it to PATH, though it didn't seem to help at all.

Thanks for your answers!

Balint

**Comment by levitte** [comment]
Can you show us you PATH?  Just type the command `PATH` and show us the result.

**Comment by RokaFogtaCsukaFarka** [comment]
I've found the solution:


73

down vote

accepted
 

The process registering a value in the PATH only modifies the registry. A process won't use these values until it is started after this change and doesn't inherit the environment from its parent.
 
I have must logged out and logged in, in order to use it from the cmd tool.

Regards,
B.

**Comment by richsalz** [comment]
glad you got it working!
