### ISSUE TITLE
Cross-compiling openssl with custom prefix

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#13042]
Trying to Configure openssl 1.1.1g
```
./Configure mingw64 shared enable-ssl-trace -ggdb --libdir=lib --openssldir=c:/cryptopack4/ssl -Wl,-rpath,c:/cryptopack4/lib --cross-compile-prefix=x86_64-w64-mingw32- -D__SEH_NOOP --prefix=c:/cryptopack4
```

Got an output
```
Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

Directory given with --prefix MUST be absolute
```

Do I need to specify the --prefix at all? If yes, how do I explain the path is absolute (it is, in fact)?

**Comment by t8m** [comment]
I suppose the prefix would work if the build was being done on windows. So the bug is in the code checking the prefix being absolute path does not account for cross unix/windows builds.

**Comment by beldmit** [comment]
I agree. As it is reproducible on the master branch, I added the corresponding labels.

**Comment by nhorman** [comment]
@beldmit is this still an issue?

**Comment by beldmit** [comment]
It was a report from my previous job so no idea

**Comment by nhorman** [comment]
copy that, marking as inactive, since the target release is out of support.

**Comment by beldmit** [comment]
The same command works for OpenSSL 3.4-dev so this can be closed
