### ISSUE TITLE
VC-WIN32 executables generate R6034 Runtime Error

### ISSUE THREAD

**Issue by jamercee** [openssl/openssl#1304]
Running into problem with windows manifest files. The built executables do not embed their manifest, nor are the _*.manifest_ files copied to the _INSTALL\bin\_ directory. This results in **R6034** Runtime Error's when trying to applications installed in the _INSTALL\bin\_ folder.  If we manually copy the _*.manifest_ files to the _INSTALL\bin\_ folder, the binaries work as expected.

Platform:
```
OpenSSL-1.1.0-pre6-dev  (fresh git clone this morning)
Microsoft Visual C++ 2008 Express Edition
Netwide Assember 2.12.02
ActiveState perl 5.20.1
Windows 8.1 Professional

```

Build Procedure

```
perl Configure VC-WIN32
nmake
nmake test   (all tests pass)
nmake install
```

I believe the correct procedure is documented here https://msdn.microsoft.com/en-us/library/ms235591.aspx?f=255&MSPPError=-2147217396.  I'm just not familiar enough with the OpenSSL build procedure to know how to hack in the change.  If someone could provide a little guidance on the _Configurations/windows-makefile.tmpl_, I'd be happy to make the change and submit a merge request. Any docs I can read that explain how this might be done would be greatly appreciated.

**Comment by levitte** [comment]
I've seen the same issue, but thought it was something local on my machine since my team-mates couldn't reproduce it.  Thanks for identifying the actual issue, I'll have a fix ready tomorrow.

**Comment by levitte** [comment]
Meh...  ok, a few attempts and I'm stuck.  I'm just now re-reading your proposal, @jamercee, and hadn't noticed your offer to do some coding...  sorry about that.

So, `Configurations/windows-makefile.tmpl` is basically a `makefile` with perl fragments enclosed with `{-` and `-}` mixed in.  Whatever those fragments leave behind *or* is added to the variable `$OUT` is added to the makefile.

I would really suggest reading `Configurations/README` and `Configurations/README.design`.

Alternatively, if you can tell me how to handle the manifests properly, I can help out with the coding.  Me, I've tried adding `/manifest:no`, to no avail.

**Comment by levitte** [comment]
So it seems I finally figured it out.  PR coming up

**Comment by levitte** [comment]
@jamercee, would you mind trying PR #1311 for me?  It should resolve this issue.

**Comment by jamercee** [comment]
Perfect -- works like a champ.

Sorry I couldn't help you get this done. I'm stuck in another a project & didn't have a chance to cycle back to this. Greatly appreciated.

**Comment by levitte** [comment]
No problem, I was hitting the same thing, and you provided the hint I needed.
