### ISSUE TITLE
EVP_CIPHER_meth_set for get / set params missing

### ISSUE THREAD

**Issue by wbeck10** [openssl/openssl#13057]
Hi guys,

I’m trouble shooting a problem in the Gost engine.
When calling EVP_CIPHER_CTX_set_padding in OPenssl111d is implemented like:

``` C
int EVP_CIPHER_CTX_set_padding(EVP_CIPHER_CTX *ctx, int pad)
{
    if (pad)
        ctx->flags &= ~EVP_CIPH_NO_PADDING;
    else
        ctx->flags |= EVP_CIPH_NO_PADDING;
    return 1;
}
```

In OpenSSL3 it is implemented like:

``` C
int EVP_CIPHER_CTX_set_padding(EVP_CIPHER_CTX *ctx, int pad)
{
    int ok;
    OSSL_PARAM params[2] = { OSSL_PARAM_END, OSSL_PARAM_END };
    unsigned int pd = pad;

    if (pad)
        ctx->flags &= ~EVP_CIPH_NO_PADDING;
    else
        ctx->flags |= EVP_CIPH_NO_PADDING;

    params[0] = OSSL_PARAM_construct_uint(OSSL_CIPHER_PARAM_PADDING, &pd);
    ok = evp_do_ciph_ctx_setparams(ctx->cipher, ctx->provctx, params);

    return ok != 0;
}
```

In my case Openssl3 will return -1 because the Gost engine
Doesn’t implement the get_ctx_params:

```
PARAM_FUNCTIONS(EVP_CIPHER,
                evp_do_ciph_getparams, get_params,
                evp_do_ciph_ctx_getparams, get_ctx_params,
                evp_do_ciph_ctx_setparams, set_ctx_params)
```

Instead it has the get/set asn1_params implemented.
However looking into the Gost engine code they use OpenSSL3 methods to set the openssl EVP_CIPHER function like:

```
EVP_CIPHER_meth_set_iv_length(cipher, TPL(c, iv_len))
!EVP_CIPHER_meth_set_flags(cipher, flags)
!EVP_CIPHER_meth_set_init(cipher, TPL(c, init))
!EVP_CIPHER_meth_set_do_cipher(cipher, TPL(c, do_cipher))
…
```

I can’t find the one who is setting the set/get_ctx_params.
Is that missing?

B.R.
 Wolfgang Beck

**Comment by mattcaswell** [comment]
> I can’t find the one who is setting the set/get_ctx_params. Is that missing?

That only exists if you have a cipher implementation from a provider. This looks like a bug in `EVP_CIPHER_CTX_set_padding`. It should only attempt to set the params if the cipher is provided.

e.g. something like inserting this after the existing `if`

````
if (ctx->cipher != NULL && ctx->cipher->prov == NULL)
    return 1;
````

**Comment by slontis** [comment]
@wbeck10 - did you try this change?
