### ISSUE TITLE
Use openssl static library without fips in android

### ISSUE THREAD

**Issue by jishuo1213** [openssl/openssl#1306]
I build openssl static library follow the openssl [wiki](https://wiki.openssl.org/index.php/Android),my build environment is as follows:
openssl-1.0.2h
ndk:android-ndk-r12b
android-api:android-14
android_arch=arch-arm
At first,I use md5 to test wether build success, it's ok.But when I use some other functions,there is a link error as follows:

> libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'bsd_signal'

I search this error and found that in android version less than or equal 19,in [signal.h](https://chromium.googlesource.com/android_tools/+/20ee6d20/ndk/platforms/android-19/arch-arm/usr/include/signal.h),there is bsd_signal symbol,but in android version 21 or higher [signal.h](https://chromium.googlesource.com/android_tools/+/20ee6d/ndk/platforms/android-21/arch-arm/usr/include/signal.h),the bsd_signal was removed,so I changed android-api to 21 and rebuild the library,everything is ok on android version higher or equal 21, but on earlier version,it's failed.
I find the code in [ui_openssl.c](https://github.com/openssl/openssl/blob/master/crypto/ui/ui_openssl.c),Will this problem be solved if modify some source code?
I am very confuse about two point:
1.in every version in android ,there is a function called signal(),in previous version less than 21,it's a wrapper function of bsd_signal,in later version,It's not a wrapper function,so there must be no error when we called signal().
2.when I use android-api=14 to build library,the library have same error on android version less than 19 and higher than 19, in android version less than or equal 19 there is bsd_signed() in signal.h,I think the library must can be use in version less than 19 and can't use in other version.
Look forward to you reply.

**Comment by mattcaswell** [comment]
If this is still an issue please raise on the openssl-users email list. Details here: https://mta.openssl.org

Closing
