### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by JeffreyChee** [openssl/openssl#13068]
installation error when I'm at step
nmake
see below error
C:\dev\openSSL>nmake

Microsoft (R) Program Maintenance Utility Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x86\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x86\nmake.exe" /                   _all

Microsoft (R) Program Maintenance Utility Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Program Maintenance Utility Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST .manifest DEL /F /Q .manifest
        IF EXIST libcrypto-1_1-x64.dll DEL /F /Q libcrypto-1_1-x64.dll
        link /nologo /debug /dll  /nologo /debug  /implib:libcrypto.lib /out:libcrypto-1_1-x64.dll /def:libcrypto.def @C:\Users\Jeffrey\AppData\Local\Temp\nmE52F.tmp || (DEL /Q libcrypto-1_1-x64.* libcrypto.lib && EXIT 1)
crypto\aes\aesni-mb-x86_64.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
Could Not Find C:\dev\openSSL\libcrypto-1_1-x64.*
NMAKE : fatal error U1077: 'link' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

-->
[dump.txt](https://github.com/openssl/openssl/files/5321806/dump.txt)

**Comment by mattcaswell** [comment]
> module machine type 'x64' conflicts with target machine type 'x86'

This indicates a conflict between the architecture for the Configure target and the toolchain. Typically this happens if you "Configure" for 64 bit ("VC-WIN64A") but you are using the Microsoft 32-bit toolchain (or vice versa).

If you want to build 64-bit OpenSSL make sure your environment is setup for the 64-bit compiler/linker. Similarly for 32-bit. You should be able to check what flavour of compiler you are currently using by running `cl` from the command line with no arguments:

````
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
````

As you can see, in this case, I get the x64 toolchain.

**Comment by JeffreyChee** [comment]
ok thanks. wasnt a windows programmer, mainly mac. 1st tie building windows code on a windows pc.

**Comment by JeffreyChee** [comment]
C:\dev\openSSL>nmake

Microsoft (R) Program Maintenance Utility Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe" /                   _build_sw

Microsoft (R) Program Maintenance Utility Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "lib" /nologo /out:providers\libimplementations_static.lib @C:\Users\Jeffrey\AppData\Local\Temp\nm396E.tmp
crypto\md5\libimplementations-lib-md5_dgst.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\lib.EXE"' : return code '0x458'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

C:\dev\openSSL>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29112 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

**Comment by JeffreyChee** [comment]
my cl is x64 but this error still occur

**Comment by JeffreyChee** [comment]
nvm i fixed it by re cloning (maybe old .o files not removed)
