### ISSUE TITLE
new without delete in bsslshim.cc

### ISSUE THREAD

**Issue by smc897** [openssl/openssl#13069]
I found a possible allocation error in bsslshim.cc, using CodeQL. It is on line 1637, 1913,1955,1279, and 215.  There is a new declaration of a local variable, but there is no delete in the file. I would think this is a possible security issue, because my understanding is the shim sits on top of the SSL layer during socket creation, and if someone were to send enough traffic to the client, it would create a scenario where the attacker, doing a DOS attack, could get the device low on memory enough to where things overflow, and he could flip something or shut something off, and get into the device. I would be interested in getting a CVE for it, and I can help fix it as well. 

Thank you. Here is an example of the source code:

if (!SetTestConfig(ssl.get(), config) ||
1637| !SetTestState(ssl.get(), std::unique_ptr<TestState>(new TestState))) {
1638 | return false;
1639 | }

**Comment by mattcaswell** [comment]
> I found a possible allocation error in bsslshim.cc, using CodeQ

What version of OpenSSL are you looking at? I find no such file in current master. Perhaps you mean ossl_shim.cc, but that file only has 1312 lines so the line numbers do not match your report. There is a file bssl_shim.cc in the boringssl project (which our file ossl_shim.cc has a historical relationship to) - but I also can't match up line numbers there either.

> I would be interested in getting a CVE for it, and I can help fix it as well.

Fixes are always welcome in the form of PRs. Assuming you mean the file ossl_shim.cc then there can be no possibility of a security issue. That file is *only* ever used internally for test purposes. The compiled code is not installed as part of OpenSSL.

**Comment by paulidale** [comment]
The code is probably:

https://github.com/openssl/openssl/blob/5357c10624bedaeed984ef4ff370096911ee2ddf/test/ossl_shim/ossl_shim.cc#L910-L921

It looks like there are a fair number of early returns that don't free everything.

**Comment by paulidale** [comment]
Thanks @richsalz, this isn't a bug.
