### ISSUE TITLE
Problem with mails 

### ISSUE THREAD

**Issue by CoyoteStarrk94** [openssl/openssl#13063]
Hello there im from Ecuador im not so good at english, but lets try, im trying to send a mail via php mailer and im getting this error 
Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
i've tried with smtp options but it doesnt send, i dunno if my version is giving trouble or something i got 1.0.1p

**Comment by kroeckx** [comment]
The error message you get probably means that the other side of the connection isn't doing TLS. I assume that your settings are wrong, and that there isn't any problem related to OpenSSL. I suggest you instead contact the author of your PHP mailer.

**Comment by CoyoteStarrk94** [comment]
Hi there sorry being late, in fact im debugging the mails, and the server answer go ahead when it asks for starttls after that i get the error i'll leave a screenshot of the error 
![Screenshot_1](https://user-images.githubusercontent.com/39922025/95084962-37002a80-06e4-11eb-87da-f5c588979ca1.png)
