### ISSUE TITLE
Revisiting / refactoring deprecation

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#13065]
As currently defined, deprecation and simulated removal (as of `no-deprecated` configuration) are kind of mixed together in the macros `DEPRECATEDIN_x_y_z`, which makes function declaration and function implementation look quite different:

``` C
/* in whatever.h */
DEPRECATEDIN_3_0(WHATEVER *WHATEVER_new(void))
```

``` C
/* in whatever.c */
#ifndef OPENSSL_NO_DEPRECATED_3_0
WHATEVER *WHATEVER_new(void)
{
    ...
}
#endif
```

Furthermore, if we want to deprecate things that are already declared through other macros, a lot of duplication of macro conditions is required, so for example, `DECLARE_ASN1_FUNCTIONS` would explode macros like `DECLARE_ASN1_FUNCTIONS_DEPRECATEDIN_3_0`, which would have to duplicate the complex version checking preprocessor code with have in `include/openssl/macros.h`.

## Proposal

I propose that we switch to use attribute macros that are separate from the removal simulation, for example `OPENSSL_DEPRECATEDIN_3_0`.  That would force us to switch our declarations to look like this:

``` C
/* in whatever.h */
#ifndef OPENSSL_NO_DEPRECATED_3_0
OPENSSL_DEPRECATEDIN_3_0 WHATEVER *WHATEVER_new(void);
#endif
```

This corresponds more clearly to the implementation guard, and also has the benefit of looking more like C.

A stronger benefit is that we can use that same attribute macro for declaration macros.  Imagine a `DECLARE_ASN1_FUNCTIONS_ATTR` that can be used like this:

``` C
#ifndef OPENSSL_NO_DEPRECATED_3_0
DECLARE_ASN1_FUNCTIONS_ATTR(WHATEVER, OPENSSL_DEPRECATEDIN_3_0)
#endif
```

A bonus is that this is likely to simplify the preprocessor in `include/openssl/macros.h`

**Comment by paulidale** [comment]
+1

**Comment by levitte** [comment]
#13074 is my proposed implementation
