### ISSUE TITLE
Another alpha release?

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#13081]
It's two months since [alpha6](https://github.com/openssl/openssl/releases), whereas before, the cadence of alpha release was quite exactly every three weeks. Considering the amount of [things](https://github.com/openssl/openssl/milestone/17) still under discussion for beta1, especially considering what "beta readiness" may [require](https://mta.openssl.org/pipermail/openssl-project/2020-October/002279.html), I think it's worth biting the bullet of having one more alpha, rather than holding out for beta1 while hugely increasing the volume of changes.

In fact, it might even be worth having a separate (short-lived!) alpha once "beta readiness" is achieved, to ensure broader testing before actually committing to everything that is being promised by the beta label.

**Comment by mattcaswell** [comment]
Whether or not to have more alpha releases was discussed at today's OTC meeting which has led to this proposal:

https://mta.openssl.org/pipermail/openssl-project/2020-October/002285.html

**Comment by paulidale** [comment]
Which has passed, the next alpha is Thursday.
