### ISSUE TITLE
Clean up documentation added for functions added during 3.0 but since removed

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13086]
Forking this issue from #10395 to address the last part of it:

@petrovr said:
> Note that some "development" functions are not removed properly _(defect)_. For instance:
> ```
> $ grep -rw EVP_PKEY_sign_init_ex
> doc/man3/EVP_PKEY_CTX_ctrl.pod:for use in an operation (for example by L<EVP_PKEY_sign_init_ex(3)>,
> doc/man3/EVP_PKEY_CTX_ctrl.pod:for use in an operation (for example by L<EVP_PKEY_sign_init_ex(3)>,
> doc/man3/EVP_PKEY_sign.pod:EVP_PKEY_sign_init_ex() was added in OpenSSL 3.0.
> doc/man7/provider-signature.pod:functions L<EVP_PKEY_sign_init_ex(3)>, L<EVP_PKEY_sign(3)>,
> util/libcrypto.num:EVP_PKEY_sign_init_ex                   ?    3_0_0   NOEXIST::FUNCTION:
> 
> ```

Before the release of 3.0 we should do a pass to ensure the spurious entries are cleaned up.

**Comment by slontis** [comment]
Closing this as it has been addressed..
@romen maybe this needs to be added as an item to the release process (beta process?)..

**Comment by romen** [comment]
@slontis what if we reopened this with the intent of adding a test to make sure this does not happen again?

**Comment by slontis** [comment]
If you can think of a way of nicely doing that then sure - otherwise it should be a checklist item.
