### ISSUE TITLE
Add Siemens to the list of companies that contribute staff time

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#13098]
https://www.openssl.org/community/thanks.html currently says:

> The following organizations who contribute staff time to work on the project (alphabetically): Akamai, Cryptsoft, Google, Oracle, Red Hat, and Softing. 

I suggest adding Siemens to this list, as they've already financed several man-months of my project participation.

**Comment by paulidale** [comment]
A pull request against the web repository would be the quickest: https://github.com/openssl/web

**Comment by DDvO** [comment]
Thanks for the hint how to do that - done.

**Comment by mattcaswell** [comment]
Done.
