### ISSUE TITLE
`fips` option no longer works for NonStop x86

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#13107]
After the refactor of `50-nonstop.conf` the fips option no longer works.

```
./Configure nonstop-nsx --prefix=/usr/local-ssl3.0 --openssldir=/usr/local-ssl3.0/ssl --with-rand-seed=rdcpu --dynamic-engine fips

Failure!  build file wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

FIPS mode not supported
```

Noting else seems to have changed.

**Comment by rsbeckerca** [comment]
I think this happened on or about commit e1f5a92df4.

**Comment by rsbeckerca** [comment]
This may be an operator error. We used to use 'fips' as the option to select fips. It seems that this isn't necessary.

```
Enabled features:
...
    fips
    fips-securitychecks
```
If this is confirmed to mean FIPS is included, then this is a non-issue.

**Comment by levitte** [comment]
This is a non-issue. That configuration is for the old FIPS module, what was compatible with 1.0.2.
We have started over regarding FIPS, and there's a new module, which is indeed part of OpenSSL from 3.0 on.

**Comment by rsbeckerca** [comment]
Thanks for confirming and the attention given.
