### ISSUE TITLE
apps/lib/engine.c does not compile on NonStop x86

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#13102]
As of commit 3094351625, engine.c does not include `string.h` so `strcmp()` is missing.

Fix in progress.

**Comment by levitte** [comment]
I don't quite understand how that commit affected the inclusions...

**Comment by rsbeckerca** [comment]
> 
> 
> I don't quite understand how that commit affected the inclusions...

I don't think it's that commit specifically and I've not done a bisect on it, but I'll apply the fix to `HEAD`. I should have said after commit e1f5a92df4 and before or at commit 3094351.
