### ISSUE TITLE
OSSL_PROVIDER_load(0, "legacy")  fail

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#13115]
dggphicprd00055: /usr1/lm/openssl/openssl3-alpha6/openssl-openssl-3.0.0-alpha6 # ./config
dggphicprd00055: /usr1/lm/openssl/openssl3-alpha6/openssl-openssl-3.0.0-alpha6/apps # ldd openssl
        linux-vdso.so.1 (0x00007fffab3c7000)
        libachk.so => /lib64/libachk.so (0x00007ffbd47c0000)
        libssl.so.3 => /usr1/lm/openssl/openssl3-alpha6/openssl-openssl-3.0.0-alpha6/libssl.so.3 (0x00007ffbd450c000)
        libcrypto.so.3 => /usr1/lm/openssl/openssl3-alpha6/openssl-openssl-3.0.0-alpha6/libcrypto.so.3 (0x00007ffbd3e9c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffbd3c98000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffbd3a7a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffbd36d7000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ffbd34cf000)
        /lib64/ld-linux-x86-64.so.2 (0x0000563a1c2bd000)

dggphicprd00055: /usr1/lm/openssl/openssl3-alpha6/openssl-openssl-3.0.0-alpha6/apps # gdb ./openssl
GNU gdb (GDB; SUSE Linux Enterprise 12) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./openssl...done.
(gdb) b main
Breakpoint 1 at 0x44af2c: file apps/openssl.c, line 229.
(gdb) r
Starting program: /home/lm/openssl/openssl3-alpha6/openssl-openssl-3.0.0-alpha6/apps/openssl
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-49.16.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, main (argc=1, argv=0x7fffffffe218) at apps/openssl.c:229
229         LHASH_OF(FUNCTION) *prog = NULL;
(gdb) call OSSL_PROVIDER_load(0, "legacy")
$1 = (OSSL_PROVIDER *) 0x0
(gdb)

the OSSL_PROVIDER_load(0, "legacy") is failed.
OpenSSL need other settings???

**Comment by levitte** [comment]
What happens if you do this?

```
$ ../util/wrap.sh ./openssl
```

or this?

```
$ OPENSSL_MODULES=../providers ./openssl
```

**Comment by Mengliuxx** [comment]
> OPENSSL_MODULES=../providers ./openssl

dggphicprd00055: /usr1/lm/openssl/openssl3-alpha6/openssl-openssl-3.0.0-alpha6/apps # OPENSSL_MODULES=../providers ./openssl
Standard commands
asn1parse         ca                ciphers           cmp
cms               crl               crl2pkcs7         dgst
dhparam           dsa               dsaparam          ec
ecparam           enc               engine            errstr
fipsinstall       gendsa            genpkey           genrsa
help              info              kdf               list
mac               nseq              ocsp              passwd
pkcs12            pkcs7             pkcs8             pkey
pkeyparam         pkeyutl           prime             provider
rand              rehash            req               rsa
rsautl            s_client          s_server          s_time
sess_id           smime             speed             spkac
srp               storeutl          ts                verify
version           x509

Message Digest commands (see the `dgst' command for more details)
blake2b512        blake2s256        gost              md4
md5               mdc2              rmd160            sha1
sha224            sha256            sha3-224          sha3-256
sha3-384          sha3-512          sha384            sha512
sha512-224        sha512-256        shake128          shake256
sm3

Cipher commands (see the `enc' command for more details)
aes-128-cbc       aes-128-ecb       aes-192-cbc       aes-192-ecb
aes-256-cbc       aes-256-ecb       aria-128-cbc      aria-128-cfb
aria-128-cfb1     aria-128-cfb8     aria-128-ctr      aria-128-ecb
aria-128-ofb      aria-192-cbc      aria-192-cfb      aria-192-cfb1
aria-192-cfb8     aria-192-ctr      aria-192-ecb      aria-192-ofb
aria-256-cbc      aria-256-cfb      aria-256-cfb1     aria-256-cfb8
aria-256-ctr      aria-256-ecb      aria-256-ofb      base64
bf                bf-cbc            bf-cfb            bf-ecb
bf-ofb            camellia-128-cbc  camellia-128-ecb  camellia-192-cbc
camellia-192-ecb  camellia-256-cbc  camellia-256-ecb  cast
cast-cbc          cast5-cbc         cast5-cfb         cast5-ecb
cast5-ofb         des               des-cbc           des-cfb
des-ecb           des-ede           des-ede-cbc       des-ede-cfb
des-ede-ofb       des-ede3          des-ede3-cbc      des-ede3-cfb
des-ede3-ofb      des-ofb           des3              desx
idea              idea-cbc          idea-cfb          idea-ecb
idea-ofb          rc2               rc2-40-cbc        rc2-64-cbc
rc2-cbc           rc2-cfb           rc2-ecb           rc2-ofb
rc4               rc4-40            seed              seed-cbc
seed-cfb          seed-ecb          seed-ofb          sm4-cbc
sm4-cfb           sm4-ctr           sm4-ecb           sm4-ofb

**Comment by levitte** [comment]
And now, with gdb, and try the same load again.  So:

```
OPENSSL_MODULES=../providers gdb ./openssl
```

Does `call OSSL_PROVIDER_load(0, "legacy")` still fail with this?

**Comment by Mengliuxx** [comment]
successful, 
so , it must be required  legacy.so? but now  just only provides libssl.a and libcrypto.a

**Comment by levitte** [comment]
legacy.so is required to use legacy algorithms, but otherwise not.

**Comment by Mengliuxx** [comment]
> legacy.so is required to use legacy algorithms, but otherwise not.

OK, ths much!!

**Comment by Mengliuxx** [comment]
How can I compile the algorithm suites included in Legay into libcrypto and libssl and modify some configuration files for compilation?

**Comment by mattcaswell** [comment]
> How can I compile the algorithm suites included in Legay into libcrypto and libssl and modify some configuration files for compilation?

legacy.so is built by default. You don't need to do anything special to build it. You just need to make sure it is loaded at run time if you need to use it.

There is information on the Wiki for how to load providers:

https://wiki.openssl.org/index.php/OpenSSL_3.0

**Comment by Mengliuxx** [comment]
> > How can I compile the algorithm suites included in Legay into libcrypto and libssl and modify some configuration files for compilation?
> 
> legacy.so is built by default. You don't need to do anything special to build it. You just need to make sure it is loaded at run time if you need to use it.
> 
> There is information on the Wiki for how to load providers:
> 
> https://wiki.openssl.org/index.php/OpenSSL_3.0

just only used the legacy.so? the liblegacy is not available?

**Comment by mattcaswell** [comment]
> just only used the legacy.so? the liblegacy is not available?

Building OpenSSL for static linking will result in the legacy provider being part of libcrypto. You still have to explicitly "load" it using "OSSL_PROVIDER_load" or via the config file, but you don't need a legacy.so file in that case.

**Comment by Mengliuxx** [comment]
ok, i try it,ths

**Comment by Mengliuxx** [comment]
> > How can I compile the algorithm suites included in Legay into libcrypto and libssl and modify some configuration files for compilation?
> 
> legacy.so is built by default. You don't need to do anything special to build it. You just need to make sure it is loaded at run time if you need to use it.
> 
> There is information on the Wiki for how to load providers:
> 
> https://wiki.openssl.org/index.php/OpenSSL_3.0
OpenSSL 3.0 compiles legacy algorithms such as (RC4, DES...) into the crypto library instead of using the legacy library. Is it consistent with 1.1.1f?
