### ISSUE TITLE
[no OPENSSL_SUPPRESS_DEPRECATED] Remove deprecated calls from apps/rsautl.c

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13119]
From point 2 of the [Technical Items still to be done list][todo_list]:

The apps are the minimum bar to measure feature completeness for the EVP interface: rewrite them so they do not use internal nor deprecated functions (except speed, engine, list, passwd -crypt and the code to handle the -engine CLI option).

That is, remove the suppression of deprecated defines.

- [ ] `apps/rsautl.c`

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by levitte** [comment]
Partially fixed in #13096

**Comment by levitte** [comment]
Actually, this ended up being *completely* fixed by #13096.  Closing
