### ISSUE TITLE
[no OPENSSL_SUPPRESS_DEPRECATED in apps] Remove deprecated calls from apps/dhparam.c

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13117]
From point 2 of the [Technical Items still to be done list][todo_list]:

The apps are the minimum bar to measure feature completeness for the EVP interface: rewrite them so they do not use internal nor deprecated functions (except speed, engine, list, passwd -crypt and the code to handle the -engine CLI option).

That is, remove the suppression of deprecated define.

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by kroeckx** [comment]
@mattcaswell: Was this fixed?

**Comment by mattcaswell** [comment]
Yes.
