### ISSUE TITLE
Draft documentation (contents but not pretty)

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13129]
From the [Technical Items still to be done list][todo_list]:

3) Draft documentation (contents but not pretty)
   - Need a list of things we know are not present -- including things we have removed.
   - We need to have mapping tables for various d2i/i2d functions.
   - We need to have a mapping table from “old names” for things into the `OSSL_PARAMS` names.
     - Documentation addition to old APIs to refer to new ones (man7).
     - Documentation needs to reference name mapping.
     - All the legacy interfaces need to have their documentation pointing to the replacement interfaces.

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by mattcaswell** [comment]
This is now being tracked by #14710
