### ISSUE TITLE
Deprecate all RAND_METHOD_* functions

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13126]
From point 2 of the [Technical Items still to be done list][todo_list]:

Deprecation List Proposal: `DH_`, `DSA_`, `ECDH_`, `ECDSA_`, `EC_KEY_`, `RSA_`, `RAND_METHOD_`.
   - Does not include macros defining useful constants (e.g. SHA512_DIGEST_LENGTH).
   - Excluded from Deprecation: `EC_`, `DSA_SIG_`, `ECDSA_SIG_`.
   - There might be some others.
   - Review for exceptions.

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by richsalz** [comment]
Just want to ask a question (might be obvious):  Any function that takes a ```RAND_METHOD``` parameter gets deprecated, right?  And internal fields (such as in the ENGINE structure) become deprecated too, right?

**Comment by paulidale** [comment]
I thought that `RAND_METHOD` was going to be kept.  It's currently the only way to completely replace the RAND DRBGs without writing a provider.  People with hardware RNGs use this.

**Comment by richsalz** [comment]
Well, y'all voted to deprecate it....

**Comment by t8m** [comment]
With all the agreed upon deprecations it is clear that writing providers is the right way. So yes, I voted for deprecation of the RAND_METHOD as well because it really is a legacy API.

**Comment by richsalz** [comment]
Note that this removes a whole bunch of functions, including
- RAND_poll
- RAND_add
- RAND_seed
- RAND_load_file
- RAND_write_file
- RAND_file_name
- RAND_get_method
- RAND_set_method

Is this okay?

Because of the last two, existing tests that change the CSPRNG to a fixed byte-stream invalidates some of the KAT's.  Thoughts?

**Comment by mspncp** [comment]
@richsalz none of the RAND methods you mentioned, except for `RAND_[gs]et_rand_method()`, takes or returns a `RAND_METHOD` pointer (see below), and none of them is marked for deprecation. (Those functions use the RAND_METHOD interface only internally.) I consider the RAND API a high (application) level API which abstracts the underlying implementation and is remarkable simple to use. The latter holds in particular for RAND_bytes() and RAND_priv_bytes(). So the RAND API is certainly not a legacy interface IMHO. (You might recall that used to think differently and preferred the RAND_DRBG API. But that has vanished already.)

Deprecation of the RAND_METHOD api essentially means that you can't modify the RAND interface anymore by replacing its underlying RAND_METHOD. If you want to provide a different entropy source in the future, you need to implement a provider (pun intended).

> [include/openssl/engine.h:482:](https://github.com/openssl/openssl/blob/b40498c6e7c6726cc4fc8fef5346f743fdd48aaf/include/openssl/engine.h#L482) DEPRECATEDIN_3_0(int ENGINE_set_RAND(ENGINE *e, const RAND_METHOD *rand_meth))
> [include/openssl/engine.h:531:](https://github.com/openssl/openssl/blob/b40498c6e7c6726cc4fc8fef5346f743fdd48aaf/include/openssl/engine.h#L531) DEPRECATEDIN_3_0(const RAND_METHOD *ENGINE_get_RAND(const ENGINE *e))
> [include/openssl/rand.h:48:](https://github.com/openssl/openssl/blob/b40498c6e7c6726cc4fc8fef5346f743fdd48aaf/include/openssl/rand.h#L48) int RAND_set_rand_method(const RAND_METHOD *meth);
> [include/openssl/rand.h:49:](https://github.com/openssl/openssl/blob/b40498c6e7c6726cc4fc8fef5346f743fdd48aaf/include/openssl/rand.h#L49) const RAND_METHOD *RAND_get_rand_method(void);
> [include/openssl/rand.h:54:](https://github.com/openssl/openssl/blob/b40498c6e7c6726cc4fc8fef5346f743fdd48aaf/include/openssl/rand.h#L54) RAND_METHOD *RAND_OpenSSL(void);
[include/openssl/types.h:145:](https://github.com/openssl/openssl/blob/b40498c6e7c6726cc4fc8fef5346f743fdd48aaf/include/openssl/types.h#L145) typedef struct rand_meth_st RAND_METHOD;

**Comment by mspncp** [comment]
> Because of the last two, existing tests that change the CSPRNG to a fixed byte-stream invalidates some of the KAT's

I don't recall the details, but @slontis was able to adopt the known answer tests.

**Comment by paulidale** [comment]
Internally we shouldn't be using `RAND_METHOD`.  The KATs use the test RNG as the entropy source.
We did discuss `RAND_add`, @t-j-h really wanted it and the decision was that it wasn't to be removed from memory.

With the recent revelations about the entropy source, I expect that we will get a replacement for `READ_set_method`.

**Comment by mspncp** [comment]
> the decision was that it wasn't to be removed from memory.

Oh, don't worry: `RAND_add()` will always be in our memories. ;-)

**Comment by mspncp** [comment]
> We did discuss `RAND_add`, @t-j-h really wanted it

I think that @t-j-h is on the wrong side of history here. Random sources should be provided by experts and not stuffed in by amateur application developers. So there should be a backend API for doing it, not a front end API.

**Comment by richsalz** [comment]
See #13171

**Comment by paulidale** [comment]
A thought for this one: we could introduce a `RAND_set0_lib_ctx_rand(OSSL_LIB_CTX *ctx, EVP_RAND_CTX *rand)` which overrides the primary, private and public DRBGs on a per library context basis.

This should be enough to replace RAND_METHOD.

The only issue I see is inside the FIPS provider where it isn't possible to gain access to the internal library context.  FIPS internal RAND calls would still go there.

A RAND_set0_global_rand(EVP_RAND_CTX *rand) fails for FIPS since it's not necessarily inside the boundary.

**Comment by richsalz** [comment]
At this point, the approaches and requirements that you want go beyond my modest skills in this area, so I'll leave this PR here, mark it WIP, and hope it's of us. I'm abandoning it.

**Comment by richsalz** [comment]
Congrats on pushing this over the finish line!
