### ISSUE TITLE
[external test] Compile and link 1.1.1 command line app against the master headers and library

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13127]
From point 2 of the [Technical Items still to be done list][todo_list]:

Compile and link 1.1.1 command line app against the master headers and library.
Run 1.1.1 app test cases against the chimera.
Treat this as an external test using a special 1.1.1 branch.

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by nelsonopenssl** [comment]
These items are blocking building 1.1.1 apps with 3.0:
OCSP_REQ_CTX_new API has changed between 1.1.1 and 3.0 - Issue 13873
	1.1.1 - prototype is OCSP_REQ_CTX *OCSP_REQ_CTX_new(BIO *io, int maxline);
	3.0 - define has 8 args instead of two: #   define OCSP_REQ_CTX_new(wb, rb, m, ml, mrl, t, ect, ea) \
       							 OSSL_HTTP_REQ_CTX_new(wb, rb, m, ml, mrl, t, ect, ea)

OCSP_REQ_CTX_http API has changed between 1.1.1 and 3.0 - Issue 13873
	1.1.1 - prototype is int OCSP_REQ_CTX_http(OCSP_REQ_CTX *rctx, const char *op, const char *path)
	3.0 - define has four parameters: #   define OCSP_REQ_CTX_http(r, s, po, pa) \
       						 OSSL_HTTP_REQ_CTX_header(r, s, po, pa)

X509_http_nbio - docs in 3.0 are incorrect
	1.1.1 - prototype is int X509_http_nbio(OCSP_REQ_CTX *rctx, X509 **pcert)
	3.0 - define is # define X509_http_nbio(url) X509_load_http(url, NULL, NULL, 0)

X509_CRL_http_nbio not defined but is mentioned in doc/man3/X509_load_http.pod as a define having only one param instead of two
	1.1.1 - prototype is int X509_CRL_http_nbio(OCSP_REQ_CTX *rctx, X509_CRL **pcrl)
	3.0 - define is # define X509_CRL_http_nbio(url) X509_CRL_load_http(url, NULL,  NULL, 0)

TLS_CT_GOST12_SIGN is missing from 3.0
TLSEXT_TYPE_heartbeat is missing from 3.0

**Comment by nelsonopenssl** [comment]
TLS_CT_GOST12_SIGN is TLS_CT_GOST12_LEGACY_SIGN in 3.0.0

**Comment by DDvO** [comment]
> X509_http_nbio - docs in 3.0 are incorrect
1.1.1 - prototype is int X509_http_nbio(OCSP_REQ_CTX *rctx, X509 **pcert)
3.0 - define is # define X509_http_nbio(url) X509_load_http(url, NULL, NULL, 0)

> X509_CRL_http_nbio not defined but is mentioned in doc/man3/X509_load_http.pod as a define having only one param instead of two
1.1.1 - prototype is int X509_CRL_http_nbio(OCSP_REQ_CTX *rctx, X509_CRL **pcrl)
3.0 - define is # define X509_CRL_http_nbio(url) X509_CRL_load_http(url, NULL, NULL, 0)

Sorry for these - fix for them is in #13960.

**Comment by nelsonopenssl** [comment]
Clone openssl 3.0 and build (I cloned to openssl)
Clone openssl 1.1.1 and build (I cloned to openssl_1_1_1)
cd to the openssl 1.1.1 top level directory
Create a folder named test_apps_3 or choose any name.
Copy the script below to the folder.
Run the script.
Copy test_apps_3/bin/openssl to apps/openssl

cd to top of the openssl 1.1.1 build directory.
You need to set OPENSSL_REGRESSION= path to the openssl 3 clone. You must not use a relative path.
You should be able to run `OPENSSL_REGRESSION=path_to_openssl util/shlib_wrap.sh apps/openssl version`
You can now run
`OPENSSL_REGRESSION=../openssl make TESTS=25 test` and other tests

You may run the script with --clean to clean the test folder you created
You may run the script with --preprocess to only preprocess the source files.  .pp files will be in the bin folder.

Use this script to build apps/openssl in an openssl 1.1.1 clone:
``` #!/bin/sh

USEABORT=1
abort() {
	echo $1
	[ $USEABORT = "1" ] &&  exit 1
}

BUILD_MODE="-c"
BUILD_OUTPUT_TYPE="o"
DO_CLEAN=0
DO_INSTALL=0

OSSL=/usr/local/openssl3
SRCAPPDIR=../../openssl_1_1_1/apps
TESTDIR=`pwd`
BINDIR="$TESTDIR"/bin
APPDIR="$TESTDIR"/apps
SKIPFILES=""

OPT_INCLUDE="-I./include -I$APPDIR -I$OSSL/include -I$OSSL/include/openssl -I$APPDIR/include"
OPT_DEFINES="-DOPENSSL_NO_HEARTBEATS -DOPENSSL_NO_OCSP -DOPENSSL_UNISTD=<stdlib.h> -DOPENSSL_BUILDING_OPENSSL -D_REENTRANT -DLIST_SEPARATOR_CHAR=';'"

OBJ=""
LIBSRC="app_rand.c apps.c bf_prefix.c opt.c s_cb.c s_socket.c"
#
# left out ocsp.c 
APPSRC="asn1pars.c ca.c ciphers.c cms.c crl.c crl2p7.c dgst.c dhparam.c dsa.c dsaparam.c ec.c ecparam.c enc.c engine.c errstr.c gendsa.c genpkey.c genrsa.c nseq.c openssl.c passwd.c pkcs12.c pkcs7.c pkcs8.c pkey.c pkeyparam.c pkeyutl.c prime.c rand.c rehash.c req.c rsa.c rsautl.c s_client.c s_server.c s_time.c sess_id.c smime.c speed.c spkac.c srp.c storeutl.c ts.c verify.c version.c x509.c"

dobuild() {
	if [ ! -f "$BINDIR"/$1.$BUILD_OUTPUT_TYPE ]; then
		DOBUILD=1
	elif [ "$BINDIR"/$1.$BUILD_OUTPUT_TYPE -ot "$APPDIR"/$1.c ]; then 
		DOBUILD=1
	else 
		DOBUILD=0
	fi
}

# start here

for i
do
 case "$i" in
 	--clean) DO_CLEAN=1;;
 	--install) DO_INSTALL=1;;
	--preprocess) BUILD_MODE="-E"; BUILD_OUTPUT_TYPE="pp";;
	--noabort) USEABORT=0;;
	--skip) 
		SKIPFILES="$SKIPFILES $2"
 esac
 shift
done

if [ $DO_CLEAN = '1' ]; then
	rm -rf "$BINDIR"
	rm -rf "$APPDIR"
fi
if [ ! -d "$BINDIR" ]; then 
	mkdir -p "$BINDIR"
fi
if [ ! -d "$APPDIR" ]; then
	mkdir -p "$APPDIR"
	(cd "$SRCAPPDIR"; tar cf - .) | (cd "$APPDIR"; tar xf -)
fi

#[ -f "$APPDIR"/progs.pl ] && (cd ..; perl "$APPDIR"/progs.pl $APPSRC >"$APPDIR"/progs.h ) || abort "Can't make progs.h"

for src in $APPSRC
do
	echo $SKIPFILES | grep --quiet "$src" || {
		echo $src
		FN=$(basename $src .c)
		dobuild $FN
		echo $DOBUILD, $FN
		if [ $DOBUILD = 1 ] ; then
			set -x
			cc  $OPT_INCLUDE -arch x86_64 $BUILD_MODE -Wall -g -O0 $OPT_DEFINES -o "$BINDIR"/$FN.$BUILD_OUTPUT_TYPE "$APPDIR"/$FN.c || abort "compile failed for $FN.c" }
			unset x
		fi
		OBJ="$OBJ $BINDIR/$FN.$BUILD_OUTPUT_TYPE"
	}
done

LIBOBJ=""
for src in $LIBSRC
do
	echo $SKIPFILES | grep --quiet "$src" || {
		echo $src
		FN=$(basename $src .c)
		if [ "$BINDIR"/$FN.$BUILD_OUTPUT_TYPE -ot "$APPDIR"/$FN.c ]; then
			set -x
			cc  $OPT_INCLUDE -arch x86_64 $BUILD_MODE -Wall -g -O0 $OPT_DEFINES -o "$BINDIR"/$FN.$BUILD_OUTPUT_TYPE "$APPDIR"/$FN.c || abort "compile failed for $FN.c"
			unset x
		fi
		LIBOBJ="$LIBOBJ $BINDIR/$FN.$BUILD_OUTPUT_TYPE"
	}
done
if [ "x$LIBOBJ" != x ]; then
	ar r bin/libapps.a $LIBOBJ 
fi

# build stubs
if [ -d "$TESTDIR"/stubs ]; then 
	for src in "$TESTDIR"/stubs/*.c
	do
		echo $src
		FN=$(basename $src .c)
		set -x
		cc  $OPT_INCLUDE -arch x86_64 $BUILD_MODE -Wall -g -O0 $OPT_DEFINES -o "$BINDIR"/$FN.$BUILD_OUTPUT_TYPE "$APPDIR"/$FN.c || abort "compile failed for $FN.c"
		unset x
		OBJ="$OBJ $BINDIR/$FN.$BUILD_OUTPUT_TYPE"
	done
fi

if [ $BUILD_OUTPUT_TYPE = "o" ]; then
	cc -o "$BINDIR"/openssl $OBJ "$BINDIR"/libapps.a "$OSSL"/lib/libssl.3.dylib "$OSSL"/lib/libcrypto.3.dylib
	if [ x$DO_INSTALL = x1 ]; then
		rm "$SRCAPPDIR"/openssl
		cp "$BINDIR"/openssl "$SRCAPPDIR"/openssl
	fi
fi
```

**Comment by levitte** [comment]
@nelsonopenssl, I detect traces of MacOS/X :wink:

**Comment by nelsonopenssl** [comment]
Just a trace? I did do the work on Ubuntu. My shell coding is probably old fashioned though

**Comment by levitte** [comment]
Well, only MacOS/X has shared libraries called *whatever*.dylib :wink:

**Comment by DDvO** [comment]
> > X509_http_nbio - docs in 3.0 are incorrect
> > 1.1.1 - prototype is int X509_http_nbio(OCSP_REQ_CTX *rctx, X509 **pcert)
> > 3.0 - define is # define X509_http_nbio(url) X509_load_http(url, NULL, NULL, 0)
> 
> > X509_CRL_http_nbio not defined but is mentioned in doc/man3/X509_load_http.pod as a define having only one param instead of two
> > 1.1.1 - prototype is int X509_CRL_http_nbio(OCSP_REQ_CTX *rctx, X509_CRL **pcrl)
> > 3.0 - define is # define X509_CRL_http_nbio(url) X509_CRL_load_http(url, NULL, NULL, 0)
> 
> Sorry for these - fix for them is in #13960.

That fix is merged now.

**Comment by levitte** [comment]
I have a cmake based 1.1.1-derived branch that does this, and which includes github action tests.

https://github.com/levitte/openssl/tree/EXPERIMENTAL-build-against-3.0

**Comment by mattcaswell** [comment]
Closed based on the availability of @levitte's branch

Issue #14275 can be used to track fixes to the tests
