### ISSUE TITLE
Reduce scope of deprecated suppression in libssl

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13128]
From point 2 of the [Technical Items still to be done list][todo_list]:

Deprecated functions used by `libssl` should be moved to independent file(s), to limit the suppression of deprecated defines to the absolute minimum scope.

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by levitte** [comment]
Partially fixed in #13096

**Comment by mattcaswell** [comment]
This was fixed by #13135. Closing.
