### ISSUE TITLE
Deprecate all EC_KEY_* functions

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13124]
From point 2 of the [Technical Items still to be done list][todo_list]:

Deprecation List Proposal: `DH_`, `DSA_`, `ECDH_`, `ECDSA_`, `EC_KEY_`, `RSA_`, `RAND_METHOD_`.
   - Does not include macros defining useful constants (e.g. SHA512_DIGEST_LENGTH).
   - Excluded from Deprecation: `EC_`, `DSA_SIG_`, `ECDSA_SIG_`.
   - There might be some others.
   - Review for exceptions.

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by levitte** [comment]
This is finished
