### ISSUE TITLE
Source checksum script

### ISSUE THREAD

**Issue by romen** [openssl/openssl#13130]
From the [Technical Items still to be done list][todo_list]:

6) Source checksum script.

[todo_list]: <https://www.mail-archive.com/openssl-project@openssl.org/msg02141.html>

**Comment by richsalz** [comment]
If nobody is working on this, I will.  Please let me know.

**Comment by mattcaswell** [comment]
> If nobody is working on this, I will. Please let me know.

@levitte is currently working on it.

**Comment by t8m** [comment]
The PR implementing this was merged. There are still some deficiencies (missing include file checksums #15133) but they will be tracked separately.
