### ISSUE TITLE
PAM unable to dlopen(/usr/lib64/security/pam_unix.so): /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b

### ISSUE THREAD

**Issue by spacexnasa** [openssl/openssl#13141]
i want to install the newest opens and openssl version on CentOS 8

##############

[root@centos8 openssl-1.1.1h]# uname -a
Linux centos8 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@centos8 openssl-1.1.1h]# uname -r
4.18.0-193.19.1.el8_2.x86_64
[root@centos8 openssl-1.1.1h]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 8.2.2004 (Core) 
Release:        8.2.2004
Codename:       Core

####################################################

openssl version :openssl-1.1.1h

[root@centos8 openssl-1.1.1h]# perl ./configdata.pm -o

Enabled features:

    afalgeng
    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c\+\+
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    ec_nistp_64_gcc_128
    engine
    err
    filenames
    gost
    heartbeats
    hw(-.+)?
    idea
    makedepend
    md2
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rc5
    rdrand
    rfc3779
    rmd160
    scrypt
    sctp
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ubsan
    ui-console
    whirlpool
    weak-ssl-ciphers
    zlib
    zlib-dynamic
    ssl3
    ssl3-method
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    asan                    [default] OPENSSL_NO_ASAN
    crypto-mdebug           [default] OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default] OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default] OPENSSL_NO_DEVCRYPTOENG
    egd                     [default] OPENSSL_NO_EGD
    external-tests          [default] OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default] OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default] OPENSSL_NO_FUZZ_AFL
    msan                    [default] OPENSSL_NO_MSAN
    unit-test               [default] OPENSSL_NO_UNIT_TEST

################   A   ####################
cd openssl-1.1.1h
./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl/shared \
-fPIC shared \
'-Wl,--enable-new-dtags,-rpath,$(LIBRPATH)' \
enable-md2 \
enable-rc5 \
sctp \
zlib \
zlib-dynamic \
enable-ubsan \
enable-heartbeats \
enable-weak-ssl-ciphers \
enable-ssl-trace \
enable-ssl3 \
enable-ssl3-method \
enable-ec_nistp_64_gcc_128

make -j $(npoc)  && make install && ldconfig && cd .. && echo "Success"

##############  B    #################################
cd openssh-8.4p1

LDFLAGS="-L/usr/local/openssl/lib -Wl,-rpath,/usr/local/openssl/lib" CPPFLAGS="-I/usr/local/openssl/include/openssl" ./configure  --prefix=/usr \
 --sysconfdir=/etc/ssh \
 --with-privsep-path=/var/empty/sshd/ \
 --with-selinux \
 --with-zlib=/usr \
 --with-ssl-dir=/usr/local/openssl \
 --with-ssl-engine  \
 --with-pam \
 --with-ldflags="-L/usr/local/openssl/lib"

make -j $(npoc)  && make install && ldconfig && cd .. && echo "Success" 

#################################################

A   and B are all ok

openssl version 
OpenSSL 1.1.1h  22 Sep 2020

ssh -V
OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020

############################################

/etc/ssh/sshd_config
..................
UsePAM no  
##    then systemctl status sshd  
# PAM unable to dlopen(/usr/lib64/security/pam_unix.so): /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version # OPENSSL_1_1_1b
# PAM adding faulty module: /usr/lib64/security/pam_unix.so
# fatal: Access denied for user root by PAM account configuration [preauth]

###########  display this error   and can not remote login #########

how can i resolve this problem

**Comment by t8m** [comment]
That is not possible. The CentOS system openssl is patched to add additional API for KDFs. You would have to rebase the patches in the CentOS openssl source rpm package.
If you for some reason need the 1.1.1h release for some particular application, that you compile, you should be able to place the upstream 1.1.1h build somewhere else like into /usr/local/ and link that application against that. Replacing the system libcrypto.so is not possible this way.
