### ISSUE TITLE
dhparam says we don't support X9.42

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#13151]
The documentation says:
`OpenSSL currently only supports the older PKCS#3 DH, not the newer X9.42 DH.`

We now generate a X9.42 file by default. The wiki says that 1.0.2 and 1.1.0 support it.

**Comment by mattcaswell** [comment]
> We now generate a X9.42 file by default. 

This bit is a bug in master (fixed by #13138).

**Comment by paulidale** [comment]
dhparam(1) is the errant man page.
