### ISSUE TITLE
prioritize chacha not working when downgrading from 1.3

### ISSUE THREAD

**Issue by robguima** [openssl/openssl#13153]
feature enabled via `SSL_OP_PRIORITIZE_CHACHA` (in code) or `-prioritize_chacha` in s_server.

It seems that when clients (including s_client) attempt to negotiate TLS1.3, they will add 1.3 ciphers to the list. In the client hello pkt, it just seems like the 1.3 ciphers will always appear at the top of the list, which presumably break the feature which tests that chacha tops of the client cipher list.

It takes an 1.3-capable openssl binary to repro this. I'm using openssl-1.1.1g.

```
openssl s_server -port 4433 -serverpref -prioritize_chacha -cert server.crt -key server.key -no_tls1_3 -cipher "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305"
```
Then 
```
openssl s_client -connect 127.0.0.11:4433 -cipher "ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384"
```
should pick chacha, but aes is selected.
Stick a `-tls1_2` to s_client and it works as intended since the 1.3 cipher will not be added to the list.

It looks like openssl should be sanitizing the cipher list when downgrading from 1.3 and removing any 1.3 cipher form the list, so that the chacha preference can work as intended.

**Comment by kaduk** [comment]
The code to implement prioritize_chacha should be looking for any cipher that uses chacha/poly and putting it at the front of the list, without care for TLS 1.3 or not.  I think the issue your test exposes is that the TLS 1.3 ciphers are prepended to the TLS 1.2 ciphers given with `-ciphers`, and the default set of TLS 1.3 ciphers does not list chacha first.  Try running a test that uses both `-ciphers` and `-ciphersuites` with chacha first.

**Comment by robguima** [comment]
@kaduk ah you are right, thank you.
That makes sense and I assume mobile client implementations will always have a CHACHA cipher at the top.
 
I'm closing this. Thanks again and sorry for the distraction.
