### ISSUE TITLE
Python@3.8's Openssl Problem

### ISSUE THREAD

**Issue by haotianmichael** [openssl/openssl#13168]
## Description
I installed [glances](https://github.com/nicolargo/glances) using `brew install glances`. 
But once tapped `glances` on shell, it emitted:
> ImportError: dlopen(/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_ssl.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib

It seems to be **openssl's version problem still**, I tried to change $PATH but it didn't work.  I don't know how to fix it. My machine has several versions of python and theirs dependencies like openssl, which exists in `/usr/local/Cellar/`, `use/bin/` and `/usr/local/opt/`.  But I really don't  know the calling  connection.  Can anyone teach me how to manage them, Please?

#### Versions
* Darwin Kernel Version 19.6.0

#### Logs
```
----------:  Search glances.conf file in /usr/local/etc/glances/glances.conf
WARNING:  PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
```
[glances.log](https://github.com/nicolargo/glances/files/5385650/glances.log)

**Comment by romen** [comment]
Hi @haotianmichael, thanks for opening this issue. 

This seems to be a very specific issue on how homebrew decides to do the plumbing to overlay your system library and frameworks with the ones installed via homebrew.

It seems like the issue might be complicated by a potential failure in dependency tracking.

Anyway you would be best served by asking this question in the homebrew support channels, as there is very little that we can offer on these matters!

**Comment by romen** [comment]
Please consider closing this issue, and including a link to the issue or mailing list to which you will forward your question, so other users encountering a similar problem could follow your issue and find relevant answers.

**Comment by haotianmichael** [comment]
> Please consider closing this issue, and including a link to the issue or mailing list to which you will forward your question, so other users encountering a similar problem could follow your issue and find relevant answers.

Thanks for your answer!  But I found  `libssl.1.0.0.dylib` is also in `/usr/local/Cellar/open@1.1/1.1.1f`  which was exactly the same in `/usr/local/Cellar/openssl/1.0.2s/libssl.1.0.0.dylib`.  Is this normal?  I don't remember  if it was me who changed that content... Sorry for that. I forgot why. But if `libssl.1.1.dylib` should have been there, is it Recommended to reinstall  `openssl@1.1` through brew despite its warnning:
> Error: Refusing to uninstall /usr/local/Cellar/openssl@1.1/1.1.1f
because it is required by  pygobject3, python, python@2, python@3.8... ( almost 30 softwares listed ) which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies openssl@1.1

**Comment by paulidale** [comment]
These are questions for the homebrew developers.  OpenSSL does not install this way by default.

**Comment by haotianmichael** [comment]
Sorry, But I mean that maybe it's neither `brew` nor `openssl`'s fault, maybe it's me who exchanged the lib for some reason.....Can you send me a link where I can  download the built version to check.

**Comment by romen** [comment]
We don't release binaries, only source.

On www.openssl.org you can find the official release tarballs, which contain the instructions on how to compile. 

But in this case, if you want to avoid to complicate the situation further, I would advise not to install from source, and instead contact the homebrew support channels to figure out how to restore your homebrew install to a proper state.
Seems like something went wrong there, and installing from source without following homebrew recipes and dependencies will probably make things worse.

**Comment by haotianmichael** [comment]
OK, I' will send a link here once I forward a issue to `brew`, then I'll  close this one. Again Thanks for your time!
