### ISSUE TITLE
openssl rsa gen privatekey remove dots

### ISSUE THREAD

**Issue by prchander** [openssl/openssl#13177]
Hello, I am using this command to generate a private key "openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out private-key.pem -noout -text". Is there a way to remove the dots and pluses that are generated when generating a private key.

**Comment by t8m** [comment]
I suppose the `-noout` is just an copy&paste error.

If you are on unix-like system you can redirect the error output to `/dev/null`:
`openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out private-key.pem -text 2>/dev/null`

Unfortunately that will also hide any error messages. They are unlikely for this command though, but you should at least check the exit status of the command if you are calling the command from a script.

**Comment by prchander** [comment]
I was trying the noout to see if that meant "no output" but is there no other way to remove those dots and pluses to measure key generation data more accurately?

**Comment by t8m** [comment]
What exactly do you want to measure? But no, there is no other option for suppressing the dot and plus output than redirecting it to /dev/null.

**Comment by prchander** [comment]
Average key generation time, average CSR generation time, and average cert gen time. I am going to be doing this for 100, 1000, and 10000 trials for accuracy.

**Comment by kroeckx** [comment]
If you really want to remove it from the output, I suggest you change the callback to not print it.

The output is there just to show you what is going on, which tests have passed when generating the random numbers.
