### ISSUE TITLE
SSL_CTX_sess_accept gives negative value

### ISSUE THREAD

**Issue by anupamam13** [openssl/openssl#13183]
Hi,
I am seeing this issue in openssl-1.1.1d.
These are the steps to see the negative value.
* Start with a default SSL_CTX, initiate a TLS 1.3 connection with SNI, "Accept" count of default context gets incremented
* After servername lookup, "Accept" count of default context gets decremented and that of SNI context is incremented
* Server sends a "Hello Retry Request"
* Client sends the second "Client Hello", now again "Accept" count of default context is decremented. Hence giving a negative value.

Please let me know if you need any more information on this.

**Comment by kaduk** [comment]
Thanks for the report; it doesn't look like we'll need more information.

https://github.com/openssl/openssl/blob/master/ssl/statem/extensions.c#L962-L971 is only checking `SSL_IS_FIRST_HANDSHAKE()` but should apparently also be looking at `s->hello_retry_request` to only move the counter on the first ClientHello.  The initial `sess_accept` increment happens in `tls_setup_handshake()` which is called from the state machine only when receiving the initial ClientHello.

**Comment by romen** [comment]
This was fixed, via #13297, in `master` with

- 42141197a1 *Fix for negative return value from `SSL_CTX_sess_accept()`*

and in `1.1.1` with:

- 212d7118a7 *Fix for negative return value from `SSL_CTX_sess_accept()`*
