### ISSUE TITLE
OSSL_DECODER cannot read from stdin

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13185]
Using the code in #13138, I run this command:

````
$ cat dh.pem | openssl dhparam -noout -text
````
This fails with:

````
Error, unable to load parameters
80B23C65177F0000:error::DECODER routines:decoder_process:BIO lib:crypto/encode_decode/decoder_lib.c:511:
````

The problem seems to be here:

https://github.com/openssl/openssl/blob/1dc5128577ed983fab8d5b3e65c06dd7e12cf4dc/crypto/encode_decode/decoder_lib.c#L510-L513

Calling `BIO_tell()` on stdin just fails immediately and we bail out at this point.

**Comment by levitte** [comment]
Ok, that does it.  We really need a BIO filter/source-sink that can handle this kind of stuff.  I've hinted at this here:

https://github.com/openssl/openssl/blob/1dc5128577ed983fab8d5b3e65c06dd7e12cf4dc/providers/implementations/storemgmt/file_store.c#L327-L331

**Comment by levitte** [comment]
Another suggestion is to use OSSL_STORE for this sort of thing.  It deals better with stdin.

**Comment by t8m** [comment]
Moved to 3.0.0 beta1 as this potentially requires API changes.

**Comment by levitte** [comment]
> Moved to 3.0.0 beta1 as this potentially requires API changes.

I don't think it will require public API changes, not the way I imagine it.  But it's definitely "work not done", so beta1 is appropriate either way.

**Comment by rainerjung** [comment]
See #13352 for another use case which fails reading am pem file from stdin via a pipe.

**Comment by slontis** [comment]
@levitte Do you mind if I attempt this one?

I am thinking of doing a mem_cache bio that can chain to a file bio.
It would just buffer into memory all the reads from the file bio. it can seek backwards.
ftell would be the location in the read buffer. seek would just go backwards in the buffer.

**Comment by levitte** [comment]
@slontis, I do not mind at all, please go ahead (you have my thanks!).  What you describe seems to be what I had in mind.

**Comment by slontis** [comment]
I am describing a filter here not a source/sink...

**Comment by levitte** [comment]
> I am describing a filter here not a source/sink...

Details...  the functionality you describe is still what I had in mind.
