### ISSUE TITLE
Openssl 1.1.1 build package for debian

### ISSUE THREAD

**Issue by mickae1** [openssl/openssl#13181]
Hi,

How do you build package openssl ?

I use checkinstall, but it doesn't create libssl package.

How do you create libssl package ?

**Comment by paulidale** [comment]
Might this question be better asked of the Debian developers?
OpenSSL doesn't distribute binary packages.

**Comment by kaduk** [comment]
The great thing about Debian is that the source package is just an `apt-get source openssl` away.
With that as a starting point, the `debuild` utility is a straightforward way to do one-off builds of debian packages (you probably want `debuild -uc -us`).  But yes, such questions belong in a Debian forum, not here.
