### ISSUE TITLE
How to deprecate declarations in header files?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#13186]
Deprecations in header files look like this:
```
DEPRECATEDIN_1_1_0(struct hostent *BIO_gethostbyname(const char *name))
```

This is not what ```doc/internal/man7/deprecated.pod``` says to do:
```
     # ifndef OPENSSL_NO_DEPRECATED_1_1_0
     /* ... */
     OSSL_DEPRECATEDIN_1_1_0 __owur int
     HMAC_Init(HMAC_CTX *ctx, const void *key, int len, const EVP_MD *md);
     /* ... */
     # endif
```

Are the old things going to be changed, will OpenSSL continue to have two ways to signal deprecation, or should the "new way" quoted above just be removed?

**Comment by richsalz** [comment]
Ping @levitte and @paulidale who wrote/reviewed #13074.

I also question the utility of adding seven macros (the ```_FOR``` ones) that aren't used except internally.

**Comment by richsalz** [comment]
And *none* of the new ```OSSL_DEPRECATEDIN_``` macros are used anywhere except in the header file.

**Comment by levitte** [comment]
> Ping @levitte and @paulidale who wrote/reviewed #13074.

I wrote the stuff, but didn't go on a big change spree...  I want to see that stuff mature, and I expect the deprecation efforts to be the arena where this is tested out.  For example, I'm converting all the RSA deprecations to the new form in #13167. 

(@mattcaswell, I'd like to encourage you to do the same in #13138)

> I also question the utility of adding seven macros (the ```_FOR``` ones) that aren't used except internally.

I think we should use them more, and I admit I haven't really started yet, but the RSA deprecations in #13137 could absolutely be of this form (just picking an example out of many possible):

``` C
DECLARE_ASN1_ENCODE_FUNCTIONS_only_attr(OSSL_DEPRECATEDIN_3_0_FOR("please use OSSL_ENCODER instead"), RSA, RSA_PUBKEY)
```

**Comment by richsalz** [comment]
>  For example, I'm converting all the RSA deprecations to the new form in #13167

Can you show me where?  I didn't find any in a quick review but maybe it's not there yet.

(Not surprisingly, having two ways to do the same thing is sub-optimal IMO.)

**Comment by levitte** [comment]
> > For example, I'm converting all the RSA deprecations to the new form in #13167
> 
> Can you show me where? I didn't find any in a quick review but maybe it's not there yet.

Argh, wrong PR number, should have said #13096!  In there, scroll down to `include/openssl/rsa.h`

> (Not surprisingly, having two ways to do the same thing is sub-optimal IMO.)

Depends...  there are other factors, like nudging others in participating in the change, which also helps re-calibrating their muscle memory.  Or so I hope...

**Comment by mattcaswell** [comment]
> (@mattcaswell, I'd like to encourage you to do the same in #13138)

It's not clear to me....why do we need a new way of deprecating things?

**Comment by levitte** [comment]
> It's not clear to me....why do we need a new way of deprecating things?

I've argued for it in #13074.  Keywords: "more like C", and "consistency"

**Comment by paulidale** [comment]
It's also less annoying to add to functions :)

**Comment by richsalz** [comment]
When adding a new way of doing things, the old way should have been converted. Unless someone takes this up, you'll be burdened with two ways of doing things for years :(

**Comment by levitte** [comment]
> When adding a new way of doing things, the old way should have been converted. Unless someone takes this up, you'll be burdened with two ways of doing things for years :(

There's absolutely nothing stopping us from doing a conversion of what `DEPRECATEDIN_x_y_z` just before releasing beta 1.

**Comment by richsalz** [comment]
Yup, there's nothing stopping anyone from doing the conversion. Let's see if it happens.

**Comment by mattcaswell** [comment]
Closing this. I had a look but couldn't find any of these old style deprecations any more.
