### ISSUE TITLE
when i use the 1.1.1 version openssl,i fund the Decryption failed during finish message processing when create the ssl session in armv8 platform with the asm acceleration on using the GCM alg.Can it be fixed in 1.1.1 version?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#13188]
when i use the 1.1.1c and 1.1.1f version openssl,i fund the Decryption failed during finish message processing when create the ssl session in armv8 platform with the asm acceleration on using the GCM alg.Can it be fixed in 1.1.1 version?

**Comment by stardrift1** [comment]
#10751
This sloution can be apply to 1.1.1 version and merge to 1.1.1 branch: OpenSSL_1_1_1-stable?

**Comment by t8m** [comment]
The fix is now merged to 1.1.1 branch.

**Comment by stardrift1** [comment]
thanks
