### ISSUE TITLE
Undocumented symbols added since 1.1.1

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13192]
We have added ~23~ ~13~ ~5~  public functions and ~12~ ~3~ 4 macros since the release of 1.1.1 that have not been documented.

These should all be documented before beta1, or removed from the public API.

(NOTE the ~strike~ items have been addressed). 
````
$ perl util/find-doc-nits -o -e
````
crypto: function ASN1_item_sign_ex(3) undocumented
crypto: function ASN1_item_verify_ctx(3) undocumented
crypto: function ASN1_item_verify_ex(3) undocumented
~crypto: function ERR_load_CMP_strings(3) undocumented~
~crypto: function ERR_load_CRMF_strings(3) undocumented~
~crypto: function ERR_load_ESS_strings(3) undocumented~
~crypto: function ERR_load_HTTP_strings(3) undocumented~
~crypto: function ERR_load_KDF_strings(3) undocumented~
~crypto: function ERR_load_OSSL_DECODER_strings(3) undocumented~
~crypto: function ERR_load_OSSL_ENCODER_strings(3) undocumented~
crypto: function OPENSSL_LH_flush(3) undocumented
crypto: function asn1_d2i_read_bio(3) undocumented
~crypto: function evp_pkey_get_EC_KEY_curve_nid(3) undocumented~
~crypto: function EVP_PKCS82PKEY_ex(3) undocumented~
~crypto: function EVP_hex2ctrl(3) undocumented~
~crypto: function EVP_str2ctrl(3) undocumented~
~crypto: function EVP_aes_128_siv(3) undocumented~
~crypto: function EVP_aes_192_siv(3) undocumented~
~crypto: function EVP_aes_256_siv(3) undocumented~
~crypto: function ossl_b2i(3) undocumented~
~crypto: function ossl_b2i_bio(3) undocumented~
~crypto: function ossl_do_PVK_header(3) undocumented~
~crypto: function ossl_do_blob_header(3) undocumented~

# ~23~ ~16~ 5 libcrypto names are not documented
include/openssl/core_dispatch.h: macro OSSL_CORE_MAKE_FUNC(3) undocumented
include/openssl/opensslv.h: macro OPENSSL_VERSION_PREREQ(3) undocumented
include/openssl/params.h: macro OSSL_PARAM_DEFN(3) undocumented
include/openssl/x509v3.h: macro EXT_UTF8STRING(3) undocumented
~include/openssl/macros.h: macro OSSL_DEPRECATED(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATED_FOR(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATEDIN_3_0_FOR(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_1_1_FOR(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_1_0_FOR(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_0_2_FOR(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_0_1_FOR(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_0_0_FOR(3) undocumented~
~include/openssl/macros.h: macro OSSL_DEPRECATEDIN_0_9_8_FOR(3) undocumented~
# ~12~ ~3~ 4 macros undocumented (count is approximate)

**Comment by levitte** [comment]
```
include/openssl/macros.h: macro OSSL_DEPRECATED(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATED_FOR(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATEDIN_3_0_FOR(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_1_1_FOR(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_1_0_FOR(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_0_2_FOR(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_0_1_FOR(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATEDIN_1_0_0_FOR(3) undocumented
include/openssl/macros.h: macro OSSL_DEPRECATEDIN_0_9_8_FOR(3) undocumented
```

Actually, they are.  https://github.com/openssl/openssl/blob/master/doc/internal/man7/deprecation.pod

The question here is, what public documentation should there be?  These aren't macros that our users are supposed to use, they are macros for our own uses, albeit quite public.

**Comment by mattcaswell** [comment]
Should we have some way of clearly identifying things in the public headers that are considered "internal"? Perhaps we should have a "reserved symbols" man page, which lists things that exist in the public headers which users should not rely on? That way everything has documentation - but the documentation in this case says "don't use this".

**Comment by levitte** [comment]
> Should we have some way of clearly identifying things in the public headers that are considered "internal"? Perhaps we should have a "reserved symbols" man page, which lists things that exist in the public headers which users should not rely on? That way everything has documentation - but the documentation in this case says "don't use this".

That could be a way, yeah.

**Comment by paulidale** [comment]
The three AES SIV ciphers `EVP_aes_(128|192|256)_siv` should be removed.  These should be provider only.

I'm leaning the same way for `OPENSSL_LH_flush` but it might be more problematic.

The four ossl_ functions (`ossl_b2i`, `ossl_b2i_bio`, `ossl_do_PVK_header` and `ossl_do_blob_header`) are internal already and should be removed from the list.

**Comment by mattcaswell** [comment]
> The four ossl_ functions (ossl_b2i, ossl_b2i_bio, ossl_do_PVK_header and ossl_do_blob_header) are internal already and should be removed from the list.

These ones are there because they are exported by libcrypto (even though they may not be in public header files). I'm not sure why we need to export them at all. They are functions that are used by an engine/provider - can't we just link in the object files directly?

**Comment by paulidale** [comment]
`ossl_do_PVK_header` and `ossl_do_blob_header` are used by `engines/e_loader_attic.c`.  The other two don't seem to be.

**Comment by paulidale** [comment]
I'd prefer for them to not be exported.

**Comment by richsalz** [comment]
See #13199 which tries to address all missing ERR documentation.

**Comment by slontis** [comment]
Why is the internal function asn1_d2i_read_bio() showing up here? (NOTE: it is listed in missingcrypto-internal.txt)

**Comment by mattcaswell** [comment]
> Why is the internal function asn1_d2i_read_bio() showing up here? (NOTE: it is listed in missingcrypto-internal.txt)

Probably because it is being exported in util/libcrypto.num. I'm not too sure *why* it is exported.

**Comment by mattcaswell** [comment]
`ERR_load_KDF_strings` appears to be a false positive above since it was present in 1.1.1. I'm not sure why it is appearing in the list of things added since 1.1.1

**Comment by mattcaswell** [comment]
> I'm not sure why it is appearing in the list of things added since 1.1.1

Ah! Because #9662 incorrectly *removed* it from missingcrypto111.txt. So now the scripts think that it was documented or not present in 1.1.1, and is now undocumented.

**Comment by levitte** [comment]
> Ah! Because #9662 incorrectly *removed* it from missingcrypto111.txt. So now the scripts think that it was documented or not present in 1.1.1, and is now undocumented.

Duly noted, reversal of that commit has now been added to #13390

**Comment by mattcaswell** [comment]
We're now down to just 5 public functions that are undocumented (down from 16 last time we checked). Unfortunately we seem to have gained an extra undocumented macro. We're now at 4 undocumented macros.

**Comment by mattcaswell** [comment]
#14232 provides the remaining documentation.
