### ISSUE TITLE
Minor grammar problem

### ISSUE THREAD

**Issue by vdrey** [openssl/openssl#132]
doc\HOWTO\keys.txt has a section on DSA keys that is poorly worded.

Here is my proposed change:

A DSA key can be used for signing only.  It is important to 
know what a certificate request with a DSA key can really be used for.

Instead of:

A DSA key can be used for signing only.  This is important to keep
in mind to know what kind of purposes a certificate request with a
DSA key can really be used for.

I think my version is clearer and more helpful.

**Comment by ghedo** [comment]
This seems to be fixed in 7b2373d904a812ab290396624274d2ae7e5ac543, so the issue can be closed.

**Comment by richsalz** [comment]
4.0.4?  Not found :)  We're up to 4.0.19 now.  But the bug is fixed.
