### ISSUE TITLE
Low number pull request reference `refs/pull/2067/merge` gets overridden

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#13209]
@levitte once again, I was surprised to see a low number pull request (`gh-2067`) in my fetch list:

**gh-2067**

    msp@msppc:~/src/openssl$ git fetch github
    remote: Enumerating objects: 199, done.
    remote: Counting objects: 100% (199/199), done.
    remote: Compressing objects: 100% (38/38), done.
    remote: Total 203 (delta 161), reused 189 (delta 160), pack-reused 4
    Receiving objects: 100% (203/203), 175.46 KiB | 223.00 KiB/s, done.
    Resolving deltas: 100% (161/161), completed with 101 local objects.
    From https://github.com/openssl/openssl
       4b7595e3ec..b11aa831cf  OpenSSL_1_1_1-stable -> github/OpenSSL_1_1_1-stable
       0a737e16b2..8300a8742b  master               -> github/master
     + 16dd5f9e44...da96b3e904 refs/pull/12998/head -> github/gh-12998  (forced update)
     + a0b2a60158...bbbec78831 refs/pull/13116/head -> github/gh-13116  (forced update)
       f56aafac14..5ea7cd15cf  refs/pull/13140/head -> github/gh-13140
       2c59531420..b743c099df  refs/pull/13189/head -> github/gh-13189
     + 54f766cbc5...a1e5350720 refs/pull/13195/head -> github/gh-13195  (forced update)
     + b8c30f6bbc...c25747b32f refs/pull/13198/head -> github/gh-13198  (forced update)
     * [new ref]               refs/pull/13199/head -> github/gh-13199
     * [new ref]               refs/pull/13200/head -> github/gh-13200
     * [new ref]               refs/pull/13201/head -> github/gh-13201
     * [new ref]               refs/pull/13202/head -> github/gh-13202
     * [new ref]               refs/pull/13204/head -> github/gh-13204
     * [new ref]               refs/pull/13207/head -> github/gh-13207
       0a737e16b2..8300a8742b  refs/pull/2067/head  -> github/gh-2067

As the merge comment correctly indicates, this commit was just merged by you and belongs to this pull request.

    commit 8300a8742b2abc487594a09b5e6ee726dbd30771 (origin/master, origin/HEAD, github/master, github/gh-2067)
    Author: Richard Levitte <levitte@openssl.org>
    Date:   Tue Oct 20 06:48:10 2020 +0200
    
        Work around Windows ftell() bug as per Microsoft engineering's suggestion
        
        See
        https://developercommunity.visualstudio.com/content/problem/425878/fseek-ftell-fail-in-text-mode-for-unix-style-text.html
        
        Reviewed-by: Paul Dale <paul.dale@oracle.com>
        (Merged from https://github.com/openssl/openssl/pull/13190)

I get those `github/gh-*` references, because I added a fetch rule
```
remote.github.fetch=+refs/pull/*/head:refs/remotes/github/gh-*
```
But it is not a local problem, because `git ls-remote` shows that the `refs/pull/13190/merge` reference is missing in openssl/openssl:

    msp@msppc:~/src/openssl$ git ls-remote github | grep -e /2067/ -e /13190/
    82d1ca56fc4bb730ef55252a3a74ddd6125bc4b5    refs/pull/13190/head
    8300a8742b2abc487594a09b5e6ee726dbd30771    refs/pull/2067/head
    8f4b62db049555c01f35a1c13a08a81dea4fea60    refs/pull/2067/merge

One possible explanation for this could be that somehow the commit id 8300a8742b2abc487594a09b5e6ee726dbd30771 was erroneously written to `refs/pull/2067/head` instead of `refs/pull/13190/head`.

This might simple be a GitHub bug. Or is it possible that this strange bug is caused by one of our scripts? (E.g., some hook script on GitHub, or the mirror hook script from git.openssl.org to GitHub?)

_Originally posted by @mspncp in https://github.com/openssl/openssl/pull/13190#issuecomment-713654420_

**Comment by mspncp** [comment]
As you can see from the last line of the fetch log above,
```
   0a737e16b2..8300a8742b  refs/pull/2067/head  -> github/gh-2067
```

it's not the first time that this reference has been overwritten, because the commit 0a737e16b2bc333cc3a8727458acc5460be10e0e is the parent of 8300a8742b on master.

**Comment by romen** [comment]
I noticed this behavior from time to time... The explanation I gave to myself was that there is some sort of garbage collection running on github side that is killing stale PR and associated refs: but I admit I did not take the effort of looking into github documentation to see what kind of guarantees are there about PR lifetime.

**Comment by mspncp** [comment]
> The explanation I gave to myself was that there is some sort of garbage collection running on github side that is killing stale PR and associated refs

This would only explain if pull request references would disappear. I believe that the `refs/pull/*/merge` references get deleted if you merge the pull request officially using the 'merge' button. (We don't do that here in openssl. In my company, we do create pr merge commits, and the GitHub merge references are missing for the merged prs.) I believe that the `refs/pull/*/head` references are never removed, but I have no reference to documentation.

However, an old reference being updated with the commit id of a curren pull request is a completely different matter. 

**It's the zombie pull request**

I already suspected it, so I checked my email: it's the zombie pull request again, which haunts me since February 2018. Here are two mails I sent to the internal committer's list, resp. to @levitte:

```

Subject: Strange github remote reference: refs/pull/2067/head
From: Dr. Matthias St. Pierre Matthias.St.Pierre at ncp-e.com
Date: Tue Feb 13 13:21:20 UTC 2018


Hi,

I am a little worried because my git log tells me that apparently the
head of PR #2067 (github/pr-2017) coincides with master:

    commit 87411f05953ee22e552d132ad5583dde5286e448 (HEAD -> master,
origin/master, origin/HEAD, github/pr-2067, github/master)
    Author: Dr. Matthias St. Pierre <Matthias.St.Pierre at ncp-e.com>
    Date:   Tue Feb 13 02:04:50 2018 +0100

        Fix whitespace issues in CHANGES and NEWS
   
        Removed mixed tabs (converted tabs to eight spaces)
   
        Reviewed-by: Matt Caswell <matt at openssl.org>
        (Merged from https://github.com/openssl/openssl/pull/5344)

As an explanation: My repository is configured to pull the heads of the
pull requests automatically via the following rule (see .git/config below):

    +refs/pull/*/head:refs/remotes/github/pr-*

To be sure, I rechecked it manually and again it showed me my commit
87411f05953ee22e552d132ad5583dde5286e448:

    git fetch github refs/pull/2067/head
    git show FETCH_HEAD

Could someone of you please check whether you are encountering the same
symptom? If yes, does anyone have an explanation for it?


Thanks!
Matthias
```


```
Subject: Zombie pull request


Hi Richard,

it looks like PR #2067 is a zombie which will hunt me for the rest of my
life: the reference is moving automatically and always points to the
head of master.

    $ git fetch --all
    Fetching origin
    Fetching github
    From https://github.com/openssl/openssl
       51cf8e0b50..856f231bd2  master              -> github/master
       51cf8e0b50..856f231bd2  refs/pull/2067/head -> github/pr-2067

Pretty much looks like a GitHub bug. Well, if it ever happens that I
don't know what to do next, I will post a bug report... ;-)

Matthias
```

**Comment by mspncp** [comment]
I'll raise an issue at the GitHub support.

**Comment by mspncp** [comment]
> I'll raise an issue at the GitHub support.

Done. I'll keep you updated about the outcome.

**Comment by levitte** [comment]
I don't use those refs, so I haven't had to deal with that problem...  but then, can't really answer your concerns either.

**Comment by mspncp** [comment]
> I don't use those refs, so I haven't had to deal with that problem... but then, can't really answer your concerns either.

It's the most simple and convenient way to checkout the pull requests of other people locally:  `git checkout gh-1234` will checkout PR 1234 .  How do you do it? Do you lookup the repo and branch name of the contributor on the website and do a fetch with a full URL? Or do you use some perl script which does some GitHub REST API magic?

**Comment by kroeckx** [comment]
Do you reuse branch names, and so had 2 PR with the same branch name?

**Comment by mspncp** [comment]
Sorry @kroeckx I don't understand your question, or at least the intention of your question. The issue I describe is an entirely remote issue and has nothing to do with the fact that I have specific fetch rules. (It's only the reason why Nicola and I notice it.)

Anyone can observe that the HEAD of PR 2067 (note that this number does not exist, neither [as a pull request](https://github.com/openssl/openssl/pull/2067), nor [as an issue](https://github.com/openssl/openssl/issues/2067)) is a moving target:

```
$ git fetch https://github.com/openssl/openssl.git  refs/pull/2067/head
From https://github.com/openssl/openssl
 * branch                  refs/pull/2067/head -> FETCH_HEAD
msp@msppc:~/src/openssl-1.1.1$ git show FETCH_HEAD --oneline --no-patch
3d914185b7 (origin/master, origin/HEAD) Constify OSSL_FUNC_keymgmt_has()
```
So since I raised this issue, it has already moved again.

**Comment by kroeckx** [comment]
I have a simular fetch rule, so I do see the same thing.

I was just not aware that 2067 never existed at all. I can't even
find that number in my mailbox to ever have existed.

**Comment by mspncp** [comment]
> I can't even find that number in my mailbox to ever have existed.

Thanks for the information. Your mailbox certainly dates back much further than mine. :-)

My last hope is that the GitHub support might be able to provide more insight. If that fails, I would say we should delete the rogue reference `refs/pull/2067/head` from the repository and see what happens.

**Comment by levitte** [comment]
> > I don't use those refs, so I haven't had to deal with that problem... but then, can't really answer your concerns either.
> 
> It's the most simple and convenient way to checkout the pull requests of other people locally:  `git checkout gh-1234` will checkout PR 1234 .

Considering troubles you have told me, I've been apprehensive and avoided using that.

>  How do you do it? Do you lookup the repo and branch name of the contributor on the website and do a fetch with a full URL? Or do you use some perl script which does some GitHub REST API magic?

There are several hub commands that are pretty useful.  I'm most aquainted with [`hub`](https://github.com/github/hub)...  but I also have a shell (hah!) script that knows what to do with an argument like "mspncp:branchname".

**Comment by kaduk** [comment]
My experience with other repos has been that always fetching all pull-request-analogues makes the local repo bloated and slow, so I end up just manually fetching a single pull-request when I need it.  E.g., `git fetch github refs/pull/NNNN/head && git rebase origin/master FETCH_HEAD`.

**Comment by mspncp** [comment]
> Considering troubles you have told me, I've been apprehensive and avoided using that.

Oh, I've never had problems with *existing* pull requests. The fetch rule works like a charm.  I'd also like to emphasize that this issue has nothing to do with the fetch rule, it's a server only problem. IMO it's a GitHub programming error. You might see it just as oddity, but the fact that we don't understand what' going on worries me a little. And it tickles my Sherlock instinct.

**Comment by levitte** [comment]
> but the fact that we don't understand what' going on worries me a little

... and exactly why I'm avoiding it.  One worry less...

> And it tickles my Sherlock instinct.

Have fun with it :wink:
My detective instincts are triggered elsewhere (and boy, are they!)

**Comment by mspncp** [comment]
The pull request https://github.com/openssl/openssl/pull/2067 which had caused these strange issues was deleted on our request by the GitHub support team in Dec 2020.
