### ISSUE TITLE
How to include PKCS12_SAFBAG def in openssl1.1.?

### ISSUE THREAD

**Issue by annieysu** [openssl/openssl#13205]
Before openssl 1.1, the definition of PKCS12_SAFEBAG is in include/openssl/pkcs12.h. 
But in openssl1.1, pkcs12.h only includes forward declaration of this structure. 
Thus when we try to access its member value.other, we meet note: forward declaration of ‘struct pkcs12_bag_st’ error. 
Seems the struct definition is moved to p12_local.h which in not under 'include' folder. 
Is there a way to include head file and use this structure?

**Comment by t8m** [comment]
No, the structures were made opaque on purpose with OpenSSL-1.1.0. If you need to access a member of a structure and there is no accessor function for that member yet we can add it, but we need a clear reasoning why the member accessor is needed.

**Comment by t8m** [comment]
I suppose #10063 that was already merged to master is what you need, but I am not sure this would be elligible for 1.1.1 branch.

**Comment by annieysu** [comment]
Thanks for the clarification. I have a follow up question on accessor.
We find there are accessor for the first 4 members in the union.
But there is no one for value.other. Our use case happens to use this field.
So is it possible to have the accessor for value.other?
Is there any consideration for not providing accessor for it?
typedef struct pkcs12_bag_st {
    ASN1_OBJECT *type;
    union {
        ASN1_OCTET_STRING *x509cert;
        ASN1_OCTET_STRING *x509crl;
        ASN1_OCTET_STRING *octet;
        ASN1_IA5STRING *sdsicert;
        ASN1_TYPE *other;       /* Secret or other bag */
    } value;
} PKCS12_BAGS;

**Comment by mattcaswell** [comment]
How about `PKCS12_SAFEBAG_get0_bag_obj`?

**Comment by t8m** [comment]
@mattcaswell yeah, that is what was added in #10063. However that is in master only and I am unsure whether this would be eligible for backport to 1.1.1.

**Comment by paulidale** [comment]
Missing accessors qualify as bug fixes but this is more than that.
Maybe we need a new API call to get the _other_ pointer?

**Comment by mattcaswell** [comment]
> Missing accessors qualify as bug fixes but this is more than that.

Well `PKCS12_SAFEBAG_get0_bag_obj` is just a simple accessor, although #10063 is more than that. So perhaps a subset of #10063 might be elgible?

**Comment by paulidale** [comment]
My bad, I thought the safe bag was new.  I'd be fine with just pulling or couple of functions back to 1.1.1.

**Comment by annieysu** [comment]
Thanks all for your help 👍 
Will PKCS12_SAFEBAG_get0_bag_obj and #10063 be available in openssl 3.0?

**Comment by paulidale** [comment]
Yes, they'll be available in 3.0.

**Comment by annieysu** [comment]
Thanks! 
It helps me a lot. I will close the issue.
