### ISSUE TITLE
SSL_ctxSetCipherList(Context,TLS12_CK_ADH_RC4_128_MD5, 1) is failed!

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#13212]
In openssl3.0.0, I has configured Legacy Providers,:
`	legacy = OSSL_PROVIDER_load(NULL,"legacy");
	if (legacy == NULL) {
	printf("Failed to load Legacy provider\n");
    }
	deflt = OSSL_PROVIDER_load(NULL, "default");
	if (deflt == NULL) {
		printf("Failed to load Default provider\n");
		OSSL_PROVIDER_unload(legacy);
	}`
but ret = SSL_ctxSetCipherList(Context,TLS12_CK_ADH_RC4_128_MD5, 1) is failed!  the ret is 0.
I found that Algorithm stack without TLS12_CK_ADH_RC4_128_MD5  in ssl_create_cipher_list(), so cipher_list_tls12_num(sk) = 0.

**Comment by paulidale** [comment]
Won't `OSSL_PROVIDER_unload(legacy);` remove the legacy provider?

**Comment by 1185129439** [comment]
> Won't `OSSL_PROVIDER_unload(legacy);` remove the legacy provider?
It is not good. There are other reasons?
if it is not supported by default? How to modify the default?

**Comment by paulidale** [comment]
To make the default different, use a configuration file.  Something like:
```
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```

Set the `OPENSSL_CONF` environment variable to point to the configuration file to test.

**Comment by mattcaswell** [comment]
> but ret = SSL_ctxSetCipherList(Context,TLS12_CK_ADH_RC4_128_MD5, 1) is failed! the ret is 0.

I assume you actually mean `SSL_CTX_set_cipher_list`? I also assume that the cipher string you are passing is "ADH-RC4-MD5" right? `TLS12_CK_ADH_RC4_128_MD5` is not defined by OpenSSL. Perhaps you meant `SSL3_CK_ADH_RC4_128_MD5` - but that isn't a string either.

If you do mean "ADH-RC4-MD5", then have you built OpenSSL with the "enable-weak-ssl-ciphers" Configure option? That ciphersuite is not available in a default build of OpenSSL. You have to explicitly request that support for it is built in when you configure OpenSSL for compilation.

Also, if you have built OpenSSL with support for it, it still won't be used unless you also set your security level to 0. So typically this might be done by passing a cipher list of "ADH-RC4-MD5:@SECLEVEL=0".

**Comment by 1185129439** [comment]
Yes, I actually mean SSL_CTX_set_cipher_list and "ADH-RC4-MD5".
In Makefile, I have built OpenSSL with the "enable-weak-ssl-ciphers" Configure option: OPTIONS= enable-weak-ssl-ciphers. And I have set your security level to 0 by SSL_CTX_set_security_level(ctx, 0) , but it is not ok.
My code is shown below:
`ctx = SSL_CTX_new(TLSv12_clientMethod());
	SSL_CTX_set_security_level(ctx, 0);
	legacy = OSSL_PROVIDER_load(NULL,"legacy");
	if (legacy == NULL) {
	printf("Failed to load Legacy provider\n");
    }
	deflt = OSSL_PROVIDER_load(NULL, "default");
	if (deflt == NULL) {
		printf("Failed to load Default provider\n");
		OSSL_PROVIDER_unload(legacy);
}
ret = SSL_CTX_set_cipher_list_ex(ctx,"ADH-RC4-MD5", 1);
`
legacy and deflt is ok, but ret = 0.

**Comment by mattcaswell** [comment]
What is `SSL_CTX_set_cipher_list_ex` above, and the third parameter `1`? There is no such function in OpenSSL?

**Comment by 1185129439** [comment]
> What is `SSL_CTX_set_cipher_list_ex` above, and the third parameter `1`? There is no such function in OpenSSL?
sorry, SSL_CTX_set_cipher_list_ex(ctx,"ADH-RC4-MD5", 1) mean SSL_CTX_set_cipher_list(ctx, "ADH-RC4-MD5").

**Comment by 1185129439** [comment]
> If you do mean "ADH-RC4-MD5", then have you built OpenSSL with the "enable-weak-ssl-ciphers" Configure option? That ciphersuite is not available in a default build of OpenSSL. You have to explicitly request that support for it is built in when you configure OpenSSL for compilation.
> In Makefile, I have built OpenSSL with the "enable-weak-ssl-ciphers" Configure option: OPTIONS= enable-weak-ssl-ciphers. but after I enter the command “openssl ciphers -tls1_2”，there is not "ADH-RC4-MD5"
![image](https://user-images.githubusercontent.com/69578444/96855876-e7fe1780-148f-11eb-9e8a-ad92c86cb95b.png)

**Comment by kaduk** [comment]
From ciphers(1):

```
       -tls1_3, -tls1_2, -tls1_1, -tls1, -ssl3
           In combination with the -s option, list the ciphers which could be
           used if the specified protocol were negotiated.  Note that not all
           protocols and flags may be available, depending on how OpenSSL was
           built.
```

Passing just `-tls1_2` does not do anything.

**Comment by kaduk** [comment]
Adding the 'answered' label since there doesn't see to be an open question left and discussion has stalled.
If there is no further traffic here the issue will eventually be closed.
