### ISSUE TITLE
Compared with OpenSSL 1.1.1f, OpenSSL 3.0-alpha5 increases the bin size. How to compile OpenSSL 3.0 to be the same as 1.1.1f?

### ISSUE THREAD

**Issue by yxungh** [openssl/openssl#13219]
The bin size cannot be increased after the OpenSSL 1.1.1f is switched to OpenSSL 3.0, the compilation options acvp_tests, fips, idea, ktls, legacy, module, padlockeng, secure-memory, siv, trace, tto, and uplink are added.

**Comment by t8m** [comment]
Unfortunately your question is quite confusing perhaps due to a language barrier. If you are talking about the size of the compiled OpenSSL library then of course yes, this is very much expectable that 3.0 will be much larger than the 1.1.1 because of the added provider support. Unfortunately there is some binary code duplication involved due to some legacy code in the libcrypto and duplication between default and fips providers.

**Comment by paulidale** [comment]
Try some of these configure options to reduce the size: `no-shared no-dso no-pic no-aria no-async no-autoload-config no-blake2 no-bf no-camellia no-cast no-chacha no-cmac no-cms no-cmp no-comp no-ct no-des no-dgram no-dh no-dsa no-dtls no-ec2m no-engine no-filenames no-gost no-idea no-ktls no-mdc2 no-md4 no-multiblock no-nextprotoneg no-ocsp no-ocb no-poly1305 no-psk no-rc2 no-rc4 no-rmd160 no-seed no-siphash no-siv no-sm2 no-sm3 no-sm4 no-srp no-srtp no-ssl3 no-ssl3-method no-ts no-ui-console no-whirlpool no-asm -DOPENSSL_NO_SECURE_MEMORY -DOPENSSL_SMALL_FOOTPRINT`

Being a separate provider, FIPS doesn't increase the size.

**Comment by yxungh** [comment]
> Unfortunately your question is quite confusing perhaps due to a language barrier. If you are talking about the size of the compiled OpenSSL library then of course yes, this is very much expectable that 3.0 will be much larger than the 1.1.1 because of the added provider support. Unfortunately there is some binary code duplication involved due to some legacy code in the libcrypto and duplication between default and fips providers.

I'm sorry, but I might not be very accurate. Currently, the OpenSSL3.0 libcrypto library is too large, and adding compilation options that can be added cannot meet my requirements. In the next version or beta version, is there any plan to eliminate duplicate binary code or reduce the binary library size?

**Comment by yxungh** [comment]
> Try some of these configure options to reduce the size: `no-shared no-dso no-pic no-aria no-async no-autoload-config no-blake2 no-bf no-camellia no-cast no-chacha no-cmac no-cms no-cmp no-comp no-ct no-des no-dgram no-dh no-dsa no-dtls no-ec2m no-engine no-filenames no-gost no-idea no-ktls no-mdc2 no-md4 no-multiblock no-nextprotoneg no-ocsp no-ocb no-poly1305 no-psk no-rc2 no-rc4 no-rmd160 no-seed no-siphash no-siv no-sm2 no-sm3 no-sm4 no-srp no-srtp no-ssl3 no-ssl3-method no-ts no-ui-console no-whirlpool no-asm -DOPENSSL_NO_SECURE_MEMORY -DOPENSSL_SMALL_FOOTPRINT`
> 
> Being a separate provider, FIPS doesn't increase the size.

Thank you for your reply. After adding these options, the binary library is still increasing. I want to be the same size as the openssl 1.1.1f I am using now. Can I do that?

**Comment by paulidale** [comment]
You can't.  3.0 is larger.  This is as small as I know how to make it.

**Comment by levitte** [comment]
> I want to be the same size as the openssl 1.1.1f I am using now.

I'm curious...  why is the same size important?

**Comment by paulidale** [comment]
I'd guess it's an embedded device and rom is full.  I've been in this situation more times than I can remember.

**Comment by levitte** [comment]
Yeah, we're not very good at small footprint...

**Comment by yxungh** [comment]
> Yeah, we're not very good at small footprint...

Thanks, for the same reason as paulidale said. 
Some legacy codes in libcrypto generate duplicate codes, and the no-dsa, no-dh, and no-des compilation options are added.
Can it be eliminated?

**Comment by t8m** [comment]
The problem is that some of the duplicate code can be eliminated only in no-deprecated build that probably won't work for you unless you change your application to not call any deprecated interfaces.

Also even with the legacy code removed the support for providers takes some space as it is much more general interface than the old engines and the provider support code cannot be eliminated as this is the main feature of 3.0 and all the (non-legacy) cryptographic operations are done via the providers in this version.

**Comment by mattcaswell** [comment]
> eliminated only in no-deprecated

I suspect there is quite a lot of code that could be removed from a no-deprecated build that currently isn't.

**Comment by t8m** [comment]
> > eliminated only in no-deprecated
> 
> I suspect there is quite a lot of code that could be removed from a no-deprecated build that currently isn't.

Yes, that is very much probable. However we do not know if that helps the reporter of the issue at all.

@yxungh Is build with no-deprecated option usable for you?

**Comment by yxungh** [comment]
Thank you for replying.
