### ISSUE TITLE
3.0 Root Certificate Expired

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#13214]
If the self-signed root CA certificate loaded to the client expires, the certificate will not be verified during SSL connection setup verification, and the SSL connection will be established.

**Comment by t8m** [comment]
Could you please describe the issue in more details? What does the self-signed root CA sign? The server certificate or the client certificate?

**Comment by Mengliuxx** [comment]
> Could you please describe the issue in more details? What does the self-signed root CA sign? The server certificate or the client certificate?

The client loads an expired root CA certificate, and the server loads a normal secondary CA certificate and a device certificate. The root CA certificate, secondary CA certificate, and device certificate are certificate chains that can be authenticated. According to my understanding, the SSL connection fails to be established because the root CA is expired. However, the validity period of the root CA certificate is not verified during the current test in version 3.0.

**Comment by t8m** [comment]
The validation should in this case fail on the server side. Is the server side also openssl? And if so, does it actually require client certificate to be present or not?

**Comment by kaduk** [comment]
If I am understanding correctly, the scenario here is that the root CA on the client (the trust anchor) has expired.  But this is not necessarily a problem, because in this setup the trust is anchored in the *key* of the root CA, and the certificate is largely just a convenient container to hold that key.  It can contain some additional metadata, yes, but that is to a large extent just advisory.  If the client does not want to trust the root CA past the expiration date of the containing X.509 certificate, the client is free to remove that entry from the root store.

**Comment by Mengliuxx** [comment]
> The validation should in this case fail on the server side. Is the server side also openssl? And if so, does it actually require client certificate to be present or not?

the server is openssl, and he server does not verify the client.  just  client verify server

**Comment by Mengliuxx** [comment]
> If I am understanding correctly, the scenario here is that the root CA on the client (the trust anchor) has expired. But this is not necessarily a problem, because in this setup the trust is anchored in the _key_ of the root CA, and the certificate is largely just a convenient container to hold that key. It can contain some additional metadata, yes, but that is to a large extent just advisory. If the client does not want to trust the root CA past the expiration date of the containing X.509 certificate, the client is free to remove that entry from the root store.

but  in actual use, the client expects that the connection will fail once the certificate expires, instead of periodically checking whether the certificate expires. This is not a normal scenario.

**Comment by kaduk** [comment]
> but in actual use, the client expects that the connection will fail once the certificate expires

I don't believe that this is universally true of all clients.

**Comment by Mengliuxx** [comment]
> > but in actual use, the client expects that the connection will fail once the certificate expires
> 
> I don't believe that this is universally true of all clients.

ok, i see,The client must ensure that the root CA is within a limited period？

**Comment by t8m** [comment]
There is nothing stopping the client application to add a client cert verification call with `X509_verify_cert` that will report error if the client root CA has expired. As we said - it is not universally desirable so we will not change the TLS client implementation to do it automatically.

**Comment by DDvO** [comment]
Closing since this question has been answered and no follow-up discussion has taken place.
Note that this issue is related to #13427, which has been fixed by #13590.
