### ISSUE TITLE
1.1.1 vs 3.0.0-alpha7: load_cert_pass() used with wrong param leading to "No filename or uri specified for loading certificate"

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#13235]
This was noticed by

  openssl x509 -MD5 -fingerprint -noout -inform PEM

returning 

  No filename or uri specified for loading certificate

in OpenSSL 3.0.0-alpha7.

IMHO this is due to a refactoring resulting in calling load_cert_pass() with wrong params.

The declaration and implementation of load_cert_pass() in apps/include/apps.h and apps/lib/apps.c

X509 *load_cert_pass(const char *uri, int maybe_stdin,
                     const char *pass, const char *desc);

There is no format params and the second param maybe_stdin is an int signaling, whether data might be read from STDIN.

I found the following calling places, that use wrong params:

apps/ca.c:        x509 = load_cert_pass(certfile, certformat, passin, "CA certificate");
apps/ca.c:            revcert = load_cert_pass(infile, certformat, passin,
apps/ca.c:    if ((template_cert = load_cert_pass(infile, certformat, passin, "template certificate")) == NULL)
apps/s_client.c:        cert = load_cert_pass(cert_file, cert_format, pass, "client certificate");
apps/s_server.c:        s_cert = load_cert_pass(s_cert_file, s_cert_format, pass,
apps/s_server.c:            s_cert2 = load_cert_pass(s_cert_file2, s_cert_format, pass,
apps/s_server.c:        s_dcert = load_cert_pass(s_dcert_file, s_dcert_format, dpass,
apps/x509.c:        x = load_cert_pass(infile, FORMAT_UNDEF, passin, "certificate");
apps/x509.c:        xca = load_cert_pass(CAfile, CAformat, passin, "CA certificate");

I think most or all of them were introduced by 2a33470b4f23bcf1cd66bbf645c855142efa0ed9 (Merged from #12647). That commit switches from using load_cert() to load_cert_pass(). Note that in the same commit changes the original load_cert() from originally calling load_cert_pass() with maybe_stdin set to 1 to now calling it with a 0. So switching the callers back to using load_cert() will likely not fix the "No filename or uri specified for loading certificate" problem.

Also load_cert() drops the format param.

**Comment by levitte** [comment]
The format argument has become largely unnecessary, you can see more about that in the manual pages.  However, passing the format as argument for `maybe_stdin` is a clear omission, of course.  PR coming up!
