### ISSUE TITLE
EVP_MAC does not document how to use it in XOF mode

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#13232]
We have at least one MAC in the EVP_MAC interface that support XOF, but it's unclear to me how you can actually use it in XOF mode. For an EVP_MD we have EVP_DigestFinalXOF().

(It also doesn't make sense to me that you need to set an xof parameter to enable the xof mode.)

**Comment by levitte** [comment]
From the parenthesis, it seems you found the info somehow.  Since it's backend implementation specific, it's described with the implementation documentation, https://github.com/openssl/openssl/blob/master/doc/man7/EVP_MAC-KMAC.pod

**Comment by levitte** [comment]
> (It also doesn't make sense to me that you need to set an xof parameter to enable the xof mode.)

Considering that's the form of communication form we have to implementation specific data in providers...  how else?

**Comment by kroeckx** [comment]
That page doesn't explain it any more than the other. I don't see
how to use it in XOF mode. In XOF mode, the output size is
unkonwn. I can just keep getting more output until I'm done. Does
that mean I can call the EVP_MAC_final() function until I have all
the data I need?

EVP_MAC-KMAC documents that if you put it in XOF mode, it will
write the length as zero. I think that's an implementation detail
that doesn't need to be documented. But I think it's important
that you put it in XOF mode before calling EVP_MAC_init(). (Which
might be obvious to you.)

The paramaters that you can set for KMAC also seem to be very
underdocumeted, you just get a name and type.

**Comment by slontis** [comment]
> (It also doesn't make sense to me that you need to set an xof parameter to enable the xof mode.)

It is related to the way that the algorithm works..
````
  See SP800-185 "Appendix A - KMAC, .... in Terms of Keccak[c]"
 
  KMAC128(key, input, out_len, custom)
  {
      start = bytepad(encode_string("KMAC") || encode_string(custom), 168) || bytepad(encode_string(key), 168)
      end = right_encode(xof_mode ? 0 : out_len) || 00.
      return KECCAK[256](start || input || end, out_len).
 }
````
So the provider kmac functions do the following:
init() does setup + digestupdate(start)
update() does digestupdate(input) for as many inputs as it needs
final() does digestupdate(end) + digestfinalXOF(,,outlen);

So you can see that the optional xof flag and the out_len can be set any time before the final.. 
Hopefully you can also see why it needs the flag.

**Comment by slontis** [comment]
I will update the docs to reflect this..

**Comment by kroeckx** [comment]
That documentation change does not actually fix my question on how to use it in XOF mode. Can I call the final function multi times, so that I can get data at one call, and more data at a later call? Or do I need to set the total size I'd want at the start, and just call final once?

**Comment by slontis** [comment]
I think it does answer your question.. There is an example showing how to use it.
You can set the output size at any time before the final.
Calling the final function multi times just seems like a weird thing to try to do...
I have also explained what the algorithm does above which should have also answered your question.

**Comment by kroeckx** [comment]
The point of the XOF is that you can actually call it multiple times, and we've had users asking that it's possible because it's not clear from the documentation.

The current behaviour that final can only be called once seems to be a limitation that can cause issues.

**Comment by slontis** [comment]
Are there existing cases where EVP_DigestFinalXOF is being called multiple times?

**Comment by slontis** [comment]
It would be helpful if you could answer some of your own questions...

So given the above algorithm of

 KMAC128(key, input, out_len, custom)
  {
      start = bytepad(encode_string("KMAC") || encode_string(custom), 168) || bytepad(encode_string(key), 168)
      end = right_encode(xof_mode ? 0 : out_len) || 00.
      return KECCAK[256](start || input || end, out_len).
 }

What is it that you are trying to change this into?

**Comment by kroeckx** [comment]
> Are there existing cases where EVP_DigestFinalXOF is being called multiple times?

Yes, I've seen multiple people ask that's possible.

**Comment by kroeckx** [comment]
As far as I understand, the point of the XOF is that you can do:
Init()
Update()
s1 = Final(len1);
s2 = Final(len2);

Or you can do:
Init()
Update()
s = Final(len1+len2);

And that:
s = concat(s1, s2)

**Comment by beldmit** [comment]
Hmmm... I always understood it as if we can have a variable-length output of the digest calculation. The details are specific to a digest (e.g. truncating for GOST ones), and some default length is specified.

**Comment by kroeckx** [comment]
It is about variable length. But you don't have to get everything
in 1 call. You can generate it as needed.

**Comment by slontis** [comment]
@kroeckx - maybe have a look at the spec to see how this would actually work in practice.
````
KMAC128(key, input, out_len, custom)
{
start = bytepad(encode_string("KMAC") || encode_string(custom), 168) || bytepad(encode_string(key), 168)
end = right_encode(xof_mode ? 0 : out_len) || 00.
return KECCAK[256](start || input || end, out_len).
}
````
Some things to consider:
1) DigestFinalXOF can only be called once currently - it has a reset call at the end, so it is not designed to be called multiple times currently.
2) KECCAK has an init, update and final.. The final does an absorb and squeeze.. This final() is not going to work as is - if you call it multiple times.  Would calling just squeeze on subsequent calls work? If so a final_run flag would be needed.
3) The KMAC provider final would need to have a final_run flag also.
4) If you want multiple output values what would out_len be in the line KECCAK[256](start || input || end, out_len).
5) There are no existing test vectors for this use case - so how do we know it is correct?

**Comment by kroeckx** [comment]
> 1) DigestFinalXOF can only be called once currently - it has a reset call at the end, so it is not designed to be called multiple times currently.

That seems to be #13402? As far as I know, it's possible to do
this in 1.1.1.

> 2) KECCAK has an init, update and final.. The final does an absorb and squeeze.. This final() is not going to work as is - if you call it multiple times.  Would calling just squeeze on subsequent calls work? If so a final_run flag would be needed.

As far as I understand, yes, we just want to call squeeze on the
next calls.

I think for the reason EVP_DigestFinalXOF() got introduced is that
it needed to do the same thing. I'm not sure it actualy needs a
different function.

> 3) The KMAC provider final would need to have a final_run flag also.
> 4) If you want multiple output values what would out_len be in the line KECCAK[256](start || input || end, out_len).

I'm not sure what the question is. It's not because the
specification just talks about 1 function you need to call that
can not split it into multiple function. The specification does
not really concern itself with implementation details, just what
the final result should be.

> 5) There are no existing test vectors for this use case - so how do we know it is correct?

You split an existing test vector in two or more parts.

**Comment by kroeckx** [comment]
So looking at the implementation, it seems there are various
reasons why this can't work in 1.1.1 and master.

**Comment by kroeckx** [comment]
So I started with #13470 to make it possible to do it, but that
clearly still needs a lot of work and probably won't make it for
3.0.0.

The EVP_MAC API itself has an output size parameter, so I think
the API itself doesn't need to change, just the implementation,
and so I think this doesn't block the 3.0.0 beta 1.

**Comment by slontis** [comment]
You may have noticed that nothing currently uses the output size  (and there was talk of removing it at one stage).
This is the only case where it would be useful assuming you potentially wanted different sized blocks on each final call..
But then it does get a bit confusing since everywhere else the output size is already set internally.

**Comment by slontis** [comment]
I might just update the task list to say OTC decision for this one?

**Comment by kroeckx** [comment]
So the question is if the current API what we want. There is an OSSL_MAC_PARAM_SIZE option you can set, and the current documentation says that you need to set that for the KMAC XOF mode. Other MACs also support the OSSL_MAC_PARAM_SIZE option. The Blake2 MAC supports setting a shorter output length. I think for all the others it's currently only something you can get, not set.

EVP_MAC_final() has an outsize parameter. It's currently just documented as the size of the buffer, and that it will give an error when it's too small. But for a variable output length MAC, like KMAC when set in XOF mode, or Blake2, it at least would feel more natural that the outsize is the amount that will be returned without having to first set the size you want.

Reading the documentation, EVP_MAC_final() has an option to return the required size of the buffer using NULL for the buffer. But we also have EVP_MAC_CTX_get_mac_size() that seems to return the same value.

**Comment by t8m** [comment]
I agree that for XOF and Blake2 MAC the outsize parameter should be the way to change the output size.
I'd leave the OSSL_MAC_PARAM_SIZE as read-only parameter. The question then is what OSSL_MAC_PARAM_SIZE should return for the XOF algorithms and what EVP_MAC_final() with NULL buffer and EVP_MAC_CTX_get_mac_size() should return for those

**Comment by levitte** [comment]
Considering that the description of KMAC talks about an output size set to zero to indicate XOF mode, that could be a possible answer that at least people who read the specs can recognise.

**Comment by kroeckx** [comment]
That just means you can put it in XOF mode, but does not allow to
call the function multiple time to get more data out of it. I
think I've made some PR that will allow the multiple calls.

**Comment by levitte** [comment]
Yes of course, there needs to be support for calling multiple finals...

The PR you're talking about is #13470.

Personally, though, I don't see why we would need a separate function for XOF mode.

**Comment by t8m** [comment]
> Personally, though, I don't see why we would need a separate function for XOF mode.

It would be IMO necessary for provider API clarity if we decide to postpone this feature after 3.0. If we decide to implement it before 3.0 beta I do not think it is necessary to do it as separate function. It still might be a good idea though if we want to clearly separate the Final and Squeeze steps of the XOF hashes in the API.

**Comment by t8m** [comment]
The speciality is that the XOF hashes/macs have the additional squeeze step.

Currently we have the DigestFinalXOF() call which by the name implicates that there is some finalization done but it is just some special form of it that allows you to set the length of the generated hash/mac. However the XOF hashes/macs need to allow you to generate any amount of the hash/mac material in further steps but those steps do not need to/should not do any finalization anymore as that is done only for the first time the DigestFinalXOF() is called. So it is slightly misleading to call those additional calls as DigestFinalXOF where it would be more appropriate to call them DigestSqueezeXOF()/MACSqueeze() or something like that.

**Comment by levitte** [comment]
Using "Squeeze" in a *generic* function name would be inappropriate, since it's a functional name used in a *specific* algorithm.

**Comment by t8m** [comment]
Yeah, IMO Squeeze would be fine as general term as well. But something like GenerateOutput would work as well.

**Comment by levitte** [comment]
But then, what's the difference between final and squeeze?  Essentially, they fulfil the same thing, i.e. get the MAC output, but it's true that "squeeze" doesn't imply the same finality.  I don't think we need both, really, 'cause "squeeze" would simply stop filling the buffer with new data when there's nothing more to get, right?

**Comment by t8m** [comment]
I mean the semantic difference is on the provider side not really on the caller side. Because for all the various algorithm implementations that could implement the XOF, it is most probable there will be 2 steps 1. finalization of the context 2. squeezing. So for the first call of the FinalXOF they will have to do the 1. and 2., and for the further calls they must do only 2. So they will have to keep some state whether the context was finalized or not.

**Comment by levitte** [comment]
> So they [providers] will have to keep some state whether the context was finalized or not.

Yes?  So on first "final" or "squeeze" call, they finalize the context, and set a flag in that same context to say it's finalized.

What I want to avoid is for the caller, be it the application calling our public interface, or libcrypto calling the provider code, to have to keep track of that state, I would very much like to see one function that simply squeeze output out of the context, until there's no more to squeeze out, and the *only* thing the caller should have to know is that as soon as they start squeezing, they cannot update any more (at least with current algos).

**Comment by beldmit** [comment]
It looks like GOST algorithms provide a 3rd set of case: a relatively short output having length in some range. Current XOF API fits normally for this case, and it shouldn't be forgotten

**Comment by levitte** [comment]
> It looks like GOST algorithms provide a 3rd set of case: a relatively short output having length in some range. Current XOF API fits normally for this case, and it shouldn't be forgotten

So are you saying that the output from the GOST algorithm may be shorter than what `EVP_MAC_CTX_get_mac_size()` returns?
I don't see that as a huge problem, and if we go for the "squeeze" line of thought, where we basically get whatever output the MAC implementation is willing to give, that should fit right in.

**Comment by beldmit** [comment]
As usual, GOST authors have a great imagination. 

There is a range (say, from 1 to 8 bytes) for the allowed lengths of MAC. 
There is some default value (say, 4 bytes) for most protocols (e.g. TLS). So in my implementation `EVP_MAC_CTX_get_mac_size()` returns the default value (mostly because of TLS), but if we need any other explicit value, it is provided via the ctrl function (for 1.1.1).

**Comment by mattcaswell** [comment]
Issue created to write a proposal on this in #14140

**Comment by kaduk** [comment]
> However the XOF hashes/macs need to allow you to generate any amount of the hash/mac material in further steps

My apologies if I'm not remembering the result of some previous discussion, but I don't understand why you think this is the case.  AFAICT, FIPS-202 talks about SHAKE producing a single output of arbitrary length and does not talk about asking for it in bits and pieces.  My understanding is that the XOF concept is intended as a generalization of (fixed-output-length) hash functions to be usable when a custom output length is needed, but that it's still intended to produce a single conceptual output and not as a source of an infinite bitstream to be divided up and used for multiple unrelated purposes.  So why should I expect to be able to produce additional output in further steps after having gotten the initial output of my single (arbitrary) desired length?

**Comment by t8m** [comment]
Please read the appendix A.2. The FIPS-202 does not disallow using SHAKE in such way. It is actually very useful to many applications of XOF functions to be able to generate arbitrary long bit stream in chunks. It is IMO wrong when the underlying crypto primitive allows for that and was explicitly designed so it allows that to arbitrarily limit such usage by the API design.

**Comment by t8m** [comment]
And yes the Appendix A.2 also talks about situation where it would be wrong to naively use a XOF primitive but that is another story.

**Comment by levitte** [comment]
In the section on KMAC, [SP 800-185](https://doi.org/10.6028/NIST.SP.800-185) talks about exactly the scenario discussed here, where output may start to be pulled before knowing the desired output length, and how XOF is an applicable method to do so.
