### ISSUE TITLE
Multiple definition of AES when cross compiling for powerpc

### ISSUE THREAD

**Issue by serzagit** [openssl/openssl#13255]
Hello,

I'm trying to cross compile OpenSSL 1.1.0l for a powerpc architecture.

The commands i used was the following:

./Configure linux-ppc zlib-dynamic shared threads --prefix=/home/serza/eNodeB/OPENSSL_1.1.0/powerpc --openssldir=/home/serza/eNodeB/OPENSSL_1.1.0/powerpc

make CFLAGS="-Os -I/home/serza/eNodeB/enb_lte_trunk.old1/bsp/pkgs/zlib-new/usr/include -DOPENSSLDIR=\"\\\"/home/serza/eNodeB/OPENSSL_1.1.0/powerpc\\\"\" -DENGINESDIR=\"\\\"/home/serza/eNodeB/OPENSSL_1.1.0/powerpc/lib/engines-1.1\\\"\"" LDFLAGS="-L/home/serza/eNodeB/enb_lte_trunk.old1/bsp/pkgs/zlib-new/usr/lib"

The first problema I faced was with the OPENSSLDIR and ENGINESDIR which always was reported as undeclared, so the solution I found was to force definition in CFLAGS.

The second problem I am facing is multiple definition of AES functions:

```
make[2]: Entering directory '/home/serza/eNodeB/OPENSSL_1.1.0/openssl-1.1.0k'
LD_LIBRARY_PATH=: /opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/bin/powerpc-linux-gnu-gcc -Os -I/home/serza/eNodeB/enb_lte_trunk.old1/bsp/pkgs/zlib-new/usr/include -DOPENSSLDIR="/home/serza/eNodeB/OPENSSL_1.1.0/powerpc" -DENGINESDIR="/home/serza/eNodeB/OPENSSL_1.1.0/powerpc/lib/engines-1.1" -fPIC -DOPENSSL_USE_NODELETE -Wl,-znodelete -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map libcrypto.a -Wl,--no-whole-archive -ldl -pthread
libcrypto.a(aes_core.o): In function `AES_encrypt':
aes_core.c:(.text+0x718): multiple definition of `AES_encrypt'
libcrypto.a(aes-ppc.o):(.text+0x1280): first defined here
libcrypto.a(aes_core.o): In function `AES_decrypt':
aes_core.c:(.text+0xc2c): multiple definition of `AES_decrypt'
libcrypto.a(aes-ppc.o):(.text+0x1900): first defined here
collect2: ld returned 1 exit status
Makefile.shared:182: recipe for target 'link_shlib.linux-shared' failed
make[2]: *** [link_shlib.linux-shared] Error 1
make[2]: Leaving directory '/home/serza/eNodeB/OPENSSL_1.1.0/openssl-1.1.0k'
Makefile:630: recipe for target 'libcrypto.so' failed
make[1]: *** [libcrypto.so] Error 2
make[1]: Leaving directory '/home/serza/eNodeB/OPENSSL_1.1.0/openssl-1.1.0k'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2
```

For this error I didn't found an easy solution, can you help me to find a way on how to compile OpenSSL1.1.0 for a powerpc architecture ????

Thanks in advance,

Sergio

**Comment by mattcaswell** [comment]
OpenSSL 1.1.0 is no longer being supported so the first step is to try 1.1.1.

**Comment by serzagit** [comment]
@mattcaswell thank you for the answer, I understood,  but unfortunately this is a very disappointing answer.

I had success compiling openssl 1.1.1 for this powerpc architecture, but when I compiled openssh 8.4p1 with the openssl 1.1.1 the ssh and sshd execution stucks in the powerpc system, this could be a bug ??? What is recommended to do in this case ????

---------------------------------------------------------------------------
Nevertheless, I also had success compiling openssl 1.1.0l for powerpc and openssh 8.4p1 works fine with this openssl version.

I let here the solution on how to compile openssl 1.1.0 for powerpc architecture in my case:

- Define in CFLAGS: -DOPENSSLDIR=\"\\\"/usr/local\\\"\" -DENGINESDIR=\"\\\"/usr/lib/engines-1.1\\\"\"
- Include in CFLAGS: -Wl, --allow-multiple-definition
- Disable padlock: no-hw-padlock

```
./Configure linux-ppc no-hw-padlock enable-zlib shared threads --with-zlib-include=/home/serza/eNodeB/enb_lte_trunk.old1/bsp/pkgs/zlib-new/usr/include --with-zlib-lib=/home/serza/eNodeB/enb_lte_trunk.old1/bsp/pkgs/zlib-new/usr/lib

make CFLAGS="-Os -I/tmp/build_enb_distro/rootfs/usr/include -DOPENSSLDIR=\"\\\"/usr/local\\\"\" -DENGINESDIR=\"\\\"/usr/lib/engines-1.1\\\"\"  -Wl,--allow-multiple-definition" LDFLAGS="-L/tmp/build_enb_distro/rootfs/usr/lib"

make DESTDIR=/home/serza/eNodeB/OPENSSL_1.1.0/powerpc/openssl-1.1.0l-zlib install
```

This leads to a successful compilation.

I would like to use most recently openssl version of 1.1.1, but openssh 8.4p1 ssh and sshd are not working properly with this version.
