### ISSUE TITLE
The SSL job maybe helpful for consecutive processing

### ISSUE THREAD

**Issue by s-c-c** [openssl/openssl#13257]
As OpenSSL does not support asynchronous read/write duplex, sometimes, the asynchronous read/write logic needs to be changed to consecutive processing. An interface for viewing the job status in internal objects maybe helpful for this.
```
ASYNC_JOB *SSL_get_job(const SSL *s)
{
    return s->job;
}
```

**Comment by mattcaswell** [comment]
I don't see a problem with adding this. PR welcome.

**Comment by t-j-h** [comment]
Code has been added already.
