### ISSUE TITLE
How openssl process Certificate Authorities extension?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#13265]
Hi,
   I want to know how openssl process Certificate Authorities extension?
   I read the code, I found openssl can handle this extension(both parse and construct) , but I didn't saw openssl use it to select certificate.  
   So what's usage of this extension in openssl? When we build cert chain, it will use this extension?

  Thanks in advance.

**Comment by kroeckx** [comment]
There is no such thing as a "Certificate Authority" extention.
You're probably talking about the "Basic Constraints" extention,
which has an "cA" field, to indicate if a certificate is a
certificate authority or not.

If the certificate is a version 3 certificate, the Basic
Constraints extention is required, and cA should be set to true,
to be able to sign an other certificate.

The place this is checked during the verify is first in
x509v3_cache_extensions() that will look at the extention and set
EXFLAG_CA. This flag is then later used in the verification code

**Comment by joymcg** [comment]
Hi kroeckx,
    There have such extension. You can found it from https://tools.ietf.org/html/rfc8446#section-4.2.4,  and openssl has a ext type TLSEXT_TYPE_certificate_authorities to handle it.

**Comment by kroeckx** [comment]
So it's about a TLS extension, not an X509 extension.

I believe it's up to the application to set the correct
certificate in a callback, like it has to do for SNI.

**Comment by kaduk** [comment]
We do seem to use the provided CA information within libssl, when picking a client certificate and strict-mode is in effect.

**Comment by joymcg** [comment]
Do openssl use it to build cert chain or only use it to check cert chain?

**Comment by joymcg** [comment]
answered by this issue #13453
