### ISSUE TITLE
Why I has fobiddened tls 1.3 with SSL_OP_NO_TLSv1_3, openssl(1.1.1c) still take tls1.3 cipher suit when client hello?

### ISSUE THREAD

**Issue by huangkaicheng2017** [openssl/openssl#13264]
SSL_CTX_set_options  wtith SSL_OP_NO_TLSv1_3, I has fobiddened tls 1.3 with SSL_OP_NO_TLSv1_3, openssl(1.1.1c) still take tls1.3 cipher suit when client hello in android 10?
 
0x13,0x02 - TLS_AES_256_GCM_SHA384

0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256

0x13,0x01 - TLS_AES_128_GCM_SHA256

**Comment by kaduk** [comment]
Version negotiation is orthogonal to cipher selection as currently implemented, and it's not clear there's a good reason to make the code more complicated.
You can use SSL_{CTX_,}set_ciphersuites to cause them to not be sent.
