### ISSUE TITLE
Possible NULL pointer dereference on  the function afalg_aes_cbc

### ISSUE THREAD

**Issue by ycaibb** [openssl/openssl#13260]
Dear developers:

  Our static analysis tool reports a NULL pointer dereference on the function [afalg_aes_cbc](https://github.com/openssl/openssl/blob/master/engines/e_afalg.c#L681). The dereference site is [here](https://github.com/openssl/openssl/blob/master/engines/e_afalg.c#L684). It may be a false positive. Thank you for your help.

```
static const EVP_CIPHER *afalg_aes_cbc(int nid)
{
    cbc_handles *cipher_handle = get_cipher_handle(nid); // may return null
    if (cipher_handle->_hidden == NULL  //dereference here
        && ((cipher_handle->_hidden =
         EVP_CIPHER_meth_new(nid,
                             AES_BLOCK_SIZE,
                             cipher_handle->key_size)) == NULL
        || !EVP_CIPHER_meth_set_iv_length(cipher_handle->_hidden,
                                          AES_IV_LEN)
        || !EVP_CIPHER_meth_set_flags(cipher_handle->_hidden,
                                      EVP_CIPH_CBC_MODE |
                                      EVP_CIPH_FLAG_DEFAULT_ASN1)
        || !EVP_CIPHER_meth_set_init(cipher_handle->_hidden,
                                     afalg_cipher_init)
        || !EVP_CIPHER_meth_set_do_cipher(cipher_handle->_hidden,
                                          afalg_do_cipher)
        || !EVP_CIPHER_meth_set_cleanup(cipher_handle->_hidden,
                                        afalg_cipher_cleanup)
        || !EVP_CIPHER_meth_set_impl_ctx_size(cipher_handle->_hidden,
                                              sizeof(afalg_ctx)))) {
        EVP_CIPHER_meth_free(cipher_handle->_hidden);
        cipher_handle->_hidden= NULL;
    }
    return cipher_handle->_hidden;
}
```

```
static cbc_handles *get_cipher_handle(int nid)
{
    switch (nid) {
    case NID_aes_128_cbc:
        return &cbc_handle[AES_CBC_128];
    case NID_aes_192_cbc:
        return &cbc_handle[AES_CBC_192];
    case NID_aes_256_cbc:
        return &cbc_handle[AES_CBC_256];
    default:
        return NULL; //may return null.
    }
}
```

**Comment by paulidale** [comment]
This would require AES CBC ciphers to not be present.  Under the new provider model, this is possible.  It wasn't previously.  So yes, this would be a bug and the return should be NULL checked.

**Comment by ycaibb** [comment]
OK. Thank you for your confirmation!

**Comment by kaduk** [comment]
I don't think that the routine in question is actually using an AES CBC cipher from a provider in this spot in the code.
To me it looks to just be accessing another static array, and all the calls to `afalg_aes_cbc()` ensure that the `nid` argument is one for which NULL is not returned.

**Comment by paulidale** [comment]
Quite possible, I didn't track through to see if it was possible or not.  It was easier to take the cautious approach and add the check...

**Comment by ycaibb** [comment]
Hi, it is possible to apply for a CVD ID for this vulnerability?

**Comment by t8m** [comment]
There is no real vulnerability here.
