### ISSUE TITLE
arm/poly1305-armv8.pl: reorder PAC authentication with SP update.

### ISSUE THREAD

**Issue by dot-asm** [openssl/openssl#13275]
https://github.com/dot-asm/cryptogams/commit/237895b9408d304d40230ed7f5cca10d32870bc4

**Comment by mattcaswell** [comment]
Thanks @dot-asm. This looks like the same fix as in #13256?

**Comment by t8m** [comment]
Yes, it looks like so. The #13256 is now merged to both master and 1.1.1, so closing this issue.
