### ISSUE TITLE
Remove FLOSS requirement from OSS and PUT builds on NonStop

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#13277]
During the conversion to the new configuration structure for NonStop, some libraries slipped through that are not needed. Having these libraries reduces the ability to easily build some configurations.

The fix needs to correct the TNS/X and TNS/E builds for OSS (PUT threaded 32/64 bit, and unthreaded 32/64 bit).

**Comment by levitte** [comment]
I assume you have a PR in mind?  Remember to have `Fixes #13277` on a line of its own in the commit message body (*not* the subject line)

**Comment by rsbeckerca** [comment]
I think I did something weird during an auto-wrap. Yes, it will be a PR on its own. I'm just doing the build/test now.

**Comment by rsbeckerca** [comment]
@levitte Does the PR look better this time? I tried to avoid the wrapping issue.
