### ISSUE TITLE
Missing fork methods in PUT builds on NonStop

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#13273]
In 3.0, the following methods are missing from the POSIX user thread build, referenced by `liblegacy-lib-threads_pthread.o`:

* `OPENSSL_fork_prepare`
* `OPENSSL_fork_child`
* `OPENSSL_fork_parent`

This occurs during the link phase of `providers\legacy.so`.

**Comment by rsbeckerca** [comment]
This appears to occur because of:
https://github.com/openssl/openssl/blob/648cf9249e6ec60e0af50d5d903e05244b837cb0/crypto/init.c#L669

not being defined for NonStop platforms. The following might solve this:

```
#if defined OPENSSL_SYS_UNIX || defined OPENSSL_SYS_TANDEM
```
If appropriate, I will create a PR for this.

**Comment by mattcaswell** [comment]
Hmm. They are defined in init.c - and that file is not included when building liblegacy:

````
$UTIL_COMMON=\
        cryptlib.c params.c params_from_text.c bsearch.c ex_data.c o_str.c \
        ctype.c threads_pthread.c threads_win.c threads_none.c initthread.c \
        context.c sparse_array.c asn1_dsa.c packet.c param_build.c $CPUIDASM \
        param_build_set.c der_writer.c passphrase.c
$UTIL_DEFINE=$CPUIDDEF

SOURCE[../libcrypto]=$UTIL_COMMON \
        mem.c mem_sec.c \
        cversion.c info.c cpt_err.c ebcdic.c uid.c o_time.c o_dir.c \
        o_fopen.c getenv.c o_init.c init.c trace.c provider.c \
        punycode.c \
        $UPLINKSRC
SOURCE[../providers/libfips.a]=$UTIL_COMMON
SOURCE[../providers/liblegacy.a]=$UTIL_COMMON
````
I have no idea why they are included in init.c. The only place they are ever referenced from internally is threads_pthread.c - and they are only relevant in a pthreads build. I'd suggest we move their definitions (which are empty anyway) in threads_pthread.c.

The alternative is to remove them completely. They are totally unused, and do nothing - but they do form part of the public API.

**Comment by mattcaswell** [comment]
> not being defined for NonStop platforms. 

The reference for them has the same guard - so this doesn't look like the issue to me:

````
#  ifdef OPENSSL_SYS_UNIX
static pthread_once_t fork_once_control = PTHREAD_ONCE_INIT;

static void fork_once_func(void)
{
    pthread_atfork(OPENSSL_fork_prepare,
                   OPENSSL_fork_parent, OPENSSL_fork_child);
}
#  endif
````

**Comment by rsbeckerca** [comment]
My impression from the documentation is that external developers can fill these in with whatever they need on a platform basis. Doesn't help though. It has me scratching my head as to why these are being referenced  through that guard, but they are.

**Comment by mattcaswell** [comment]
> My impression from the documentation is that external developers can fill these in with whatever they need on a platform basis.

No. The idea is that applications can call these manually to inform OpenSSL about forks - if OpenSSL is running on a platform where it can't detect the fork itself. I think the original idea was that OpenSSL would do something in response to this information (e.g. reseed the DRBG). However in practice calls to these functions are ignored and have been ever since they were first introduced in 1.1.1. So they are no-ops and always have been no-ops. I doubt very much anyone is actually calling them, so we probably could just delete them entirely and no-one would notice. However strictly speaking that is an API break that would require an OMC vote.

**Comment by richsalz** [comment]
@mattcaswell 's summary is correct and they should at least be deprecated.

**Comment by rsbeckerca** [comment]
I'm just testing the change to move the content from init.c to threads_pthread.c, which should ensure that the build works without changing functionality and will push when it's done.

**Comment by rsbeckerca** [comment]
Aside: I'm finding other configuration nits around PUT and SPT builds. Will open those as a separate issue. Very small cleanup changes in 50-nonstop.conf. :(

**Comment by kaduk** [comment]
> However in practice calls to these functions are ignored and have been ever since they were first introduced in 1.1.1

Technically they were used for a while for actual robust DRBG fork-safety, which got ripped out in favor of the simple pid-based mechanism by https://github.com/openssl/openssl/pull/9832 (so the use never made it into a release).

**Comment by rsbeckerca** [comment]
@kaduk well the PR should be ready in any event.

**Comment by rsbeckerca** [comment]
Looks happy now
