### ISSUE TITLE
dhparam app only allows generation of 2048 bit keys

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#13271]
The default algorithm is now fips186_4 which only allows 2048 bit keys.

1024 bit keys are no longer secure.

What should this app do with 1024, 3072, and 4096 bit sizes? As it will currently produce an error.
We could generate legacy for the 1024 case with a warning?
It could spit out a named group for larger sizes.
Ideally this app should die at some point since 'named group' safe primes are a better option.
If it produces values for these other sizes then a warning would also be needed..

NOTE: genpkey handles all of the dh options for fips186_2, fips_1864, group, generator specified in EVP_PKEY-DH.pod

**Comment by mattcaswell** [comment]
> The default algorithm is now fips186_4 which only allows 2048 bit keys.

In #13228, I propose that we change this to be PKCS3 instead for backwards compatibility reasons.

**Comment by kroeckx** [comment]
I think that this can be closed now?

**Comment by mattcaswell** [comment]
Yes.
