### ISSUE TITLE
The -x509_strict flag no longer accepts missing Authority Key Identifier and Subject Key Identifier

### ISSUE THREAD

**Issue by petersohn** [openssl/openssl#13283]
We have some old certificates that have missing Authority Key Identifier and Subject Key Identifier fields. OpenSSL version 1.1.1 did not check these fields, even with `-x509_strict`, but since 3.0.0alpha7, certificates are no longer accepted if these flags are missing. Unfortunately, we have to accept these old certificates. Turning off `-x509_strict` is not an option, because it has other checks that are important for us.

There should be some way to reproduce the old behavior, so that certificates accepted by 1.1.1 are also accepted by the new version.

Here is an example. The following command accepts the files below in 1.1.1, but not in 3.0.0alpha7.

```
openssl verify -x509_strict -CAfile a.pem b.pem
```

[a.pem.txt](https://github.com/openssl/openssl/files/5466177/a.pem.txt)
[b.pem.txt](https://github.com/openssl/openssl/files/5466176/b.pem.txt)

With 3.0.0alpha7, the command produces the following output:

```
C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = dmsk
error 85 at 0 depth lookup: Missing Authority Key Identifier
error b.pem: verification failed
```

**Comment by t8m** [comment]
The AKID is required by RFC5280 so IMO this really belongs to the `-x509_strict` checks.

What are the other `-x509_strict` checks that are important for you?

**Comment by kroeckx** [comment]
For reference, after scanning almost 4G certificates (https://www.roeckx.be/x509lint_stats.txt), I see about 57M (or 1.5%) of the certificates that don't have an AKID, and 45M (1.2%) that are missing an SKID.

I think the check do belong in the strict check. But maybe we can move some of the strict checks to be done when not in strict mode.

**Comment by DDvO** [comment]
@petersohn you can use the cert verifcation callback mechanism to waive that specific rejection.

**Comment by DDvO** [comment]
What we should do is mention all added/stricter checks in `CHANGES.md`.

**Comment by petersohn** [comment]
> What we should do is mention all added/stricter checks in `CHANGES.md`.

That would be a good idea.

> @petersohn you can use the cert verification callback mechanism to waive that specific rejection.

This does not work. The verification callback is only called once with the last error it can find, not with each error if there are more.

This is how it works right now: first do a lot of checks, and if an error is found, overwrite the error. Then at the end, call the callback with the last error if we found one.

https://github.com/openssl/openssl/blob/e7a8fecd0b1138b156bee71d92372abda956f1a8/crypto/x509/x509_vfy.c#L530-L598

Is it possible for it to be fixed? Then we could ignore a specific error if needed.

**Comment by DDvO** [comment]
> > What we should do is mention all added/stricter checks in `CHANGES.md`.
> 
> That would be a good idea.

I'll do that today.

> > @petersohn you can use the cert verification callback mechanism to waive that specific rejection.
> 
> This does not work. The verification callback is only called once with the last error it can find, not with each error if there are more.

Ah, you are right; my memory was wrong on this.

> Is it possible for it to be fixed? Then we could ignore a specific error if needed.

I'll fix that in the same PR.

**Comment by DDvO** [comment]
@petersohn, the fix is merged; you can try it out with the current master.
