### ISSUE TITLE
openssl dhparam -check segfaults

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#13287]

**Comment by slontis** [comment]
There are a few issues here:
1)
For a start the check needs to do this..
check_ctx = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, NULL);
EVP_PKEY_param_check(check_ctx);

Using the gen_ctx is not going to work.

2) Calling key_validate is likely to fail if we are generating different standards (PKCS#3, SP800-56Ar3) and the validate only checks for SP800-56Ar3 validation. If we make the validate more general then we will be accepting keys that are not good for S0800-56Ar3.

**Comment by slontis** [comment]
@kroeckx Maybe supplying your commandline args might be helpful?

**Comment by slontis** [comment]
@mattcaswell This needs to be considered also when deciding on the dh param gen.

**Comment by kroeckx** [comment]
> @kroeckx Maybe supplying your commandline args might be helpful?

openssl dhparam -check -in <file>

Where file is an PKCS3 file.

**Comment by kroeckx** [comment]
If I try "openssl dhparam -check 2048" with master, I get:
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
[...]
Error, invalid parameters generated
4027AC5C6D7F0000:error::digital envelope routines:EVP_PKEY_param_check:no key set:crypto/evp/pmeth_check.c:65:

**Comment by mattcaswell** [comment]
None of these issues seem to occur with #13231 applied, so I think this issue can be closed once that PR is merged.

**Comment by mattcaswell** [comment]
#13231 was merged so closing.
