### ISSUE TITLE
Help finding replacement for ASN1_seq_unpack_X509

### ISSUE THREAD

**Issue by jamercee** [openssl/openssl#1328]
OpenSSL 1.1.0 has upgraded the safestack.h macro system, but I'm having difficulty understanding the changes.  I'm porting a piece of code from OpenSSL 0.9.8 that uses `ASN1_seq_unpack_X509`.  In 0.9.8, safestack.h had this definition.

```
#define ASN1_seq_unpack_X509(buf, len, d2i_func, free_func) \
        SKM_ASN1_seq_unpack(X509, (buf), (len), (d2i_func), (free_func))
```

Could anyone point me in the right direction and how this needs to be adapted?

**Comment by richsalz** [comment]
post to openssl-users mailing list https://mta.openssl.org to join.
