### ISSUE TITLE
OpenSSL speed command missing algorithms- linux-armv4 - Raspberry Pi 2b

### ISSUE THREAD

**Issue by Atzeloss** [openssl/openssl#13292]
### Problem:
Multiple algorithm combinations are not available when using the `openssl speed` command.
After several trials, only symmetric encryption algorithms that don´t require an external MAC function in the argument seem to be accepted by the speed command.

### Tested commands(working):
 ```openssl speed -evp camellia-128-ecb ```        -same for all other modes of operation(cbc,ccm,gcm etc)
 ```openssl speed -evp aria-128-ecb ```              -same for all other modes of operation(cbc,ccm,gcm etc)
 ```openssl speed -evp aes-128-ecb ```               -same for all other modes of operation(cbc,ccm,gcm etc)
 ```openssl speed hmac ```                                  - uses md5 as desired
`openssl speed -evp ChaCha20-Poly1305`        - works even if is AEAD scheme
`echo -n "value-to-digest" | openssl dgst -sha256 -hmac "secret-key-here" ` 

![OpenSSL_hmac_command_line](https://user-images.githubusercontent.com/37959001/97815749-a55aed00-1c90-11eb-883d-865f08a0126e.PNG)

### Tested commands(not working):
 ```  openssl speed -evp aes-128-cbc-hmac-sha1 ```      -works however on a x86_64 Debian linux systems, seems like a Raspberry Problem

![openssl_mac_then_encrypt_error](https://user-images.githubusercontent.com/37959001/97815570-3af57d00-1c8f-11eb-8a45-24e76f639a60.PNG)

![openssl_working_command](https://user-images.githubusercontent.com/37959001/97815577-4c3e8980-1c8f-11eb-9b90-3b1c265829af.png)

 ```  openssl speed -evp aes-256-cbc-hmac-sha256 ```  - same as before
 ```  openssl speed -evp ```   <algo&gt;-<MAC&gt;       - seems to not work with any cipher or MAC except ChaCha20-Poly1305

### Compilation:
The compillation was done on the target plattform as intended by INSTALL.md
- cloned this github repository
- ` ./config`
- `make `
- `make test `      (passed without errors)
- `make install`    

### Target config:
![Raspberry_Pi_OpenSSL_version](https://user-images.githubusercontent.com/37959001/97815631-ab040300-1c8f-11eb-97ee-b55d839cebcc.PNG)

**Comment by paulidale** [comment]
Ciphers like `aes-256-cbc-hmac-sha256` are for libssl's use for TLS.  They are not meant to be used stand alone.  Hence they aren't supported by speed.

**Comment by mattcaswell** [comment]
Right, as @paulidale says these are not general use ciphers. They are specifically for use by libssl and are not available on all platforms (for anything not just speed). libssl detects there availability and uses them if possible.

**Comment by Atzeloss** [comment]
All right, I'm sorry then that I incorrectly raised an issue.
Thanks for the explanation.
