### ISSUE TITLE
What is the role of the Provider CTX in evp_md_ctx_st?

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#13293]
By comparing the openssl 1.1.1f and oIpenssl 3.0.0，I find that 3.0.0 added Provider CTX in evp_md_ctx_st. So I want to konw the role of the Provider CTX, Can you tell me？ Thank you.T

**Comment by 1185129439** [comment]
![image](https://user-images.githubusercontent.com/69578444/97826228-fb18af00-1cfb-11eb-9477-f0d6e738dd37.png)
What are the differences these two iv？

**Comment by slontis** [comment]
Please read https://wiki.openssl.org/index.php/OpenSSL_3.0 for information about providers.

The getparams call is getting the working iv from the provider.
ctx->iv is only there for legacy reasons..

The provider only variant of this function is a few lines down: see EVP_CIPHER_CTX_get_iv()

**Comment by 1185129439** [comment]
> The getparams call is getting the working iv from the provider.
> ctx->iv is only there for legacy reasons..
> Before evp_do_ciph_ctx_getparams，ctx->iv is NULL, but after evp_do_ciph_ctx_getparams, ctx->iv is not NULL. Now，the ctx->iv is  working iv from the provider? 
> The provider only variant of this function is a few lines down: see EVP_CIPHER_CTX_get_iv()

**Comment by 1185129439** [comment]
Before evp_do_ciph_ctx_getparams，ctx->iv is NULL, but after evp_do_ciph_ctx_getparams, ctx->iv is not NULL. Now，the ctx->iv is working iv from the provider?

**Comment by 1185129439** [comment]
Before evp_do_ciph_ctx_getparams，ctx->iv is NULL, but after evp_do_ciph_ctx_getparams, ctx->iv is not NULL. Now，the ctx->iv is working iv from the provider? 
 but why  provctx.iv and the ctx->iv getted after evp_do_ciph_ctx_getparams are different？

And, I want to get  provctx.iv, how to do?

**Comment by mattcaswell** [comment]
It looks like you are using an older version of 3.0. I'd suggest upgrading to alpha7 which made some changes in this area as per PR #12233.

Older versions of 3.0 gave you the *original* IV rather than the *running* IV which is probably why you see discrepancies between the two values.

**Comment by 1185129439** [comment]
EVP_CIPHER_CTX_get_iv_state(EVP_CIPHER_CTX *ctx, void *buf, size_t len) can accesses the current "IV state" of the cipher, but What's the buf?

**Comment by 1185129439** [comment]
EVP_CIPHER_CTX_get_iv_state(EVP_CIPHER_CTX *ctx, void *buf, size_t len) can accesses the current "IV state" of the cipher, but What's the buf?

**Comment by slontis** [comment]
It is documented in doc/man3/EVP_CIPHER_CTX_get_iv.pod

**Comment by slontis** [comment]
@mattcaswell - should this be a void *?

**Comment by 1185129439** [comment]
> It is documented in doc/man3/EVP_CIPHER_CTX_get_iv.pod
I have read the doc, but There is no description about the buf.

**Comment by slontis** [comment]
It is the caller-supplied buffer in the following sentence..

```
EVP_CIPHER_CTX_get_iv() and EVP_CIPHER_CTX_get_iv_state() copy initialization
vector (IV) information from the B<EVP_CIPHER_CTX> into the caller-supplied
buffer.  L<EVP_CIPHER_CTX_iv_length(3)> can be used to determine an
appropriate buffer size, and if the supplied buffer is too small, an error
will be returned (and no data copied).  EVP_CIPHER_CTX_get_iv() accesses the
("original") IV that was supplied when the B<EVP_CIPHER_CTX> was created, and
EVP_CIPHER_CTX_get_iv_state() accesses the current "IV state" of the cipher,
which is updated during cipher operation for certain cipher modes (e.g., CBC
and OFB).
```

i.e- you supply a fixed buffer and it fills it with an iv.

**Comment by slontis** [comment]
I think this has been answered sufficiently.. Please reopen if this is not the case.
