### ISSUE TITLE
OpenSSL 3.0 will continue to support TLS 1.0 and 1.1?

### ISSUE THREAD

**Issue by polarathene** [openssl/openssl#13299]
[IETF draft to deprecate TLS 1.0 and 1.1](https://tools.ietf.org/html/draft-ietf-tls-oldversions-deprecate-08) (initial version was back in 2018, unclear when the draft will be completed):

> At least one widely-used library has plans to drop TLSv1.1 and TLSv1.0 support in upcoming releases; products using such libraries would need to use older versions of the libraries to support TLSv1.0 and TLSv1.1, which is clearly undesirable.

Not sure what the "one widely-used library" is referenced there, but will the upcoming OpenSSL 3.0 be making such a change as well, or will TLS 1.0/1.1 support continue to be available by default? I had a look at OpenSSL 3.0 wiki and blog pages and saw no mention of any plans to remove/deprecate such support so I assume they'll remain available?

**Comment by paulidale** [comment]
It isn't dropping TLS 1.0 or 1.1.

If FIPS is being used, however, TLS 1.2 is the minimum supported version due to the availability of algorithm implementations.

**Comment by kaduk** [comment]
> IETF draft to deprecate TLS 1.0 and 1.1 (initial version was back in 2018, unclear when the draft will be completed):

The WG has completed its part of things, and sent it to me to review as responsible Area Director.  I expect it to progress on to IETF last call fairly soon, as the fundamentals of what it is doing are not controversial -- I only wanted to have some changes in terms of how we talk about what we are doing in relation to the affected documents.

**Comment by kroeckx** [comment]
Note that we do have this change for 3.0:
 * The security strength of SHA1 and MD5 based signatures in TLS has been
   reduced. This results in SSL 3, TLS 1.0, TLS 1.1 and DTLS 1.0 no longer
   working at the default security level of 1 and instead requires security
   level 0. The security level can be changed either using the cipher string
   with @SECLEVEL, or calling SSL_CTX_set_security_level().

So they are not usable by default.

**Comment by polarathene** [comment]
@kroeckx oh, I must have missed that if it was mentioned on the wiki or blog posts. Thank you!

When a system is updated OpenSSL package is updated to 3.0 in future, any software package that links to the system OpenSSL will lose TLS 1.0/1.1 support if that software has been configured to allow those protocol versions to be used (eg Postfix)? (as they currently are with neither of the suggested methods to lower security level from default)

I contribute to a project on Github that uses official Docker base images and makes a legacy config available to support TLS 1.0/1.1 for those that still need it (eg, macOS <10.12 iOS <10 (both released in Sep 2016, but there is still some users in 2020 afaik) native mail app doesn't support TLS 1.2 for non-HTTPS protocols).

> The security level can be changed either using the cipher string with @SECLEVEL, or calling SSL_CTX_set_security_level().

Unless Postfix(and Dovecot) internally manages so with an update (to lower security level when configured for <TLS 1.2), I guess our project would need to add `@SECLEVEL` to cipher strings used; although that may expose more risk beyond allowing TLS 1.0/1.1 cipher suites from the sounds of it? Would it be advisable to deprecate the legacy support config option for users instead?

---

@kaduk Do you know if OpenSSL is the library referred to in the linked IETF document I quoted?

**Comment by beldmit** [comment]
@polarathene, an off-topic question

Do you have any relevant contacts among the Dovecot developers?

**Comment by kaduk** [comment]
@polarathene sorry, I don't remember offhand which library that referred to, and couldn't find it in a quick search.

**Comment by kroeckx** [comment]
I think that if you need to talk to legacy clients that do not
support TLS 1.2, most likely they don't support any (aes based)
ciphers from security level 1 either, and you already need to lower your
security level to 0, even with the 1.1.1 release.

**Comment by polarathene** [comment]
> Do you have any relevant contacts among the Dovecot developers?

@beldmit No sorry, I am just a contributor to https://github.com/tomav/docker-mailserver

---

> and couldn't find it in a quick search.

@kaduk No worries, just seemed a bit odd to be mentioned in the document without any reference.

---

> most likely they don't support any (aes based) ciphers from security level 1 either, and you already need to lower your security level to 0, even with the 1.1.1 release.

@kroeckx 

**Security level 1**  sets the minimum strength to [80-bits](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_get_security_level.html), so I'm not sure why that would rule out TLS 1.0+1.1 cipher suites by default in OpenSSL 1.1.1?

```
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020

$ openssl ciphers -s -v 'ECDHE-RSA-AES128-SHA:@SECLEVEL=1' | column -t
TLS_AES_256_GCM_SHA384        TLSv1.3  Kx=any   Au=any  Enc=AESGCM(256)             Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256  TLSv1.3  Kx=any   Au=any  Enc=CHACHA20/POLY1305(256)  Mac=AEAD
TLS_AES_128_GCM_SHA256        TLSv1.3  Kx=any   Au=any  Enc=AESGCM(128)             Mac=AEAD
ECDHE-RSA-AES128-SHA          TLSv1    Kx=ECDH  Au=RSA  Enc=AES(128)                Mac=SHA1
```

We expose a few AES-CBC-SHA1 cipher suites for TLS 1.0+1.1, those offer both 128-bit and 256-bit AES. These are needed for some users running macOS/iOS releases prior to Sep 2016 when using Apple's official mail app which lacked TLS 1.2 support until then. When we dropped the earlier protocol versions several users were running into this problem in 2018 IIRC, I assume their system was unable to update to a newer macOS/iOS release. 

AES-GCM was also unavailable on macOS until 10.11 (Sep 2015). Most other clients gained TLS 1.2 by 2012-2014, on a related note some lagged behind a bit with ECC support until 2014-2017.

Except for SMTP on port 25, all other ports are explicitly listing cipher suites to allow, and Postfix has some exclusion rules to apply to port 25 (uses Postfix's own `medium` list). 

I checked with `@SECLEVEL=4` and the explicit AES128 cipher was excluded as expected. Likewise, if I changed the explicit cipher to 256-bit AES, it was excluded due to being a TLSv1 cipher due to the min TLS 1.2 condition. So I assume that OpenSSL 3.0 with Postfix and Dovecot are going to behave in the same manner once the update for 3.0 is ready, despite listing explicit cipher suites to allow, we'd need to append `@SECLEVEL=0` for TLS 1.0+1.1 support if a user enables our legacy cipher suite support.

**Comment by kroeckx** [comment]
On Thu, Nov 05, 2020 at 04:49:50PM -0800, Brennan Kinney wrote:
> > most likely they don't support any (aes based) ciphers from security level 1 either, and you already need to lower your security level to 0, even with the 1.1.1 release.
> 
> **Security level 1**  sets the minimum strength to [80-bits](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_get_security_level.html), so I'm not sure why that would rule out TLS 1.0+1.1 cipher suites by default in OpenSSL 1.1.1?

I was thinking about Windows XP users, who only have ciphers like
DES and RC4, while Windows 7 has TLS 1.2.

I was not aware that MacOS took so long to implement TLS 1.2.
