### ISSUE TITLE
Absolute paths in a .include directive no longer working with master

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13302]
I have numerous times seen or been bitten myself by an attempt to ".include" a file which is specified with an absolute path. Unfortunately this only works with relative paths.

I can't think of a good reason to disallow absolute paths. Should we add this? I think it would be a significant usability improvement.

See for example:

https://mta.openssl.org/pipermail/openssl-users/2020-November/013105.html

**Comment by t8m** [comment]
I am confused - why shouldn't the `.include` directive already support absolute paths? If this does not work, it must be a regression. It works fine with 1.1.1.

**Comment by mattcaswell** [comment]
> I am confused - why shouldn't the .include directive already support absolute paths? If this does not work, it must be a regression. It works fine with 1.1.1.

I haven't looked into why it doesn't work. I've only observed that if you provide one then it fails.

**Comment by t8m** [comment]
Yep, it is regression in 3.0.

**Comment by t8m** [comment]
I'll fix it.

**Comment by levitte** [comment]
At some point, we should have an internal platform agnostic path editing library.  A bit like perl's File::Spec.
