### ISSUE TITLE
There should be an easy way to validate a config file

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13303]
Debugging errors in config files is hard. Where a config file is loaded automatically, it either works or it doesn't, and you don't get  any kind of feedback as to what went wrong.

See for example:

https://mta.openssl.org/pipermail/openssl-users/2020-November/013105.html

I envisage some option to the OpenSSL command line which attempts to load the config file and prints any errors found to stdout.

**Comment by levitte** [comment]
> I envisage some option to the OpenSSL command line which attempts to load the config file and prints any errors found to stdout.

Er, what parts of the config file?  Some parts are application specific...

**Comment by mattcaswell** [comment]
> Er, what parts of the config file? Some parts are application specific...

All parts for which we have built-in config modules.

**Comment by mattcaswell** [comment]
The primary issue I think is that if a config file is auto-loaded then we clear all errors and ignore them. If we had the ability from a command line app to dump the error stack to stdout instead that would probably be sufficient.

**Comment by mattcaswell** [comment]
The other question is what app would we add such an option to? Possibilities that spring to mind are `list` and `version`

**Comment by richsalz** [comment]
Make it a new "config" command.  All sorts of interesting options then become possible
- config -as xxx # treat it as if the command were x509
- config -value section.name # print the (possibly exanded or default) value
- config -sections # list all the sections found
- config -dump # print the internal CONF structures
- config -keys # print the keys for the specified section.

**Comment by levitte** [comment]
> The primary issue I think is that if a config file is auto-loaded then we clear all errors and ignore them

... and we should probably stop doing that!

**Comment by mattcaswell** [comment]
> ... and we should probably stop doing that!

That is another option but is liable to break lots of stuff where there is a dodgy config file that isn't actually being used for anything.

**Comment by beldmit** [comment]
> > The primary issue I think is that if a config file is auto-loaded then we clear all errors and ignore them
> 
> ... and we should probably stop doing

Warnings and/or strict mode could be a possible solution...

**Comment by paulidale** [comment]
What about #12663?

Include `config_diagnostics = 1` in the very top level section and the silence should be broken.

**Comment by mattcaswell** [comment]
I had completely forgotten about #12663 when raising this issue! So I'm closing this.

**Comment by beldmit** [comment]
I think it should be placed in the default config file. Let switching the config verification off be deliberate.

**Comment by mattcaswell** [comment]
> I think it should be placed in the default config file. Let switching the config verification off be deliberate.

That's a very good idea.

**Comment by mattcaswell** [comment]
Although I note this about the option in the man page:

"This is useful for diagnosing misconfigurations and should not be used in
production."

I'm not clear why this shouldn't be used in production.

**Comment by beldmit** [comment]
#13310

**Comment by paulidale** [comment]
The rationale for not using it in production is that it returns errors for malformed configuration files.
This leads to DoS if the configuration is broken either by an attacker or by accident.

It's the same argument for ignoring errors when loading the configuration.

**Comment by mattcaswell** [comment]
> This leads to DoS if the configuration is broken either by an attacker or by accident.

Hmm. Is there really a DoS here? If an attacker can break the configuration then presumably they can write to sensitive files on your filesystem and you have bigger problems. If its by accident then that's not really a DoS, and is the mechanism working, i.e. you've got an error in your config file, you've asked for config file diagnostics and therefore you want to know about errors.

> It's the same argument for ignoring errors when loading the configuration.

Ignoring errors by default is a different argument. I don't know why this was done initially, but I'm not sure it was a good one. However, we are now stuck with it. There may be many broken config files out there - but they're not actually causing any harm because they don't actually have any interesting configuration in them anyway. So we don't want to suddenly break those applications when they upgrade.

**Comment by paulidale** [comment]
@vdukhovni, you mentioned the ignore errors when this was discussed....

**Comment by t8m** [comment]
I mostly agree with Matt, IMO ignoring errors in random configuration files out there which do not have `config_diagnostics = 1` is the right thing to do. However that does not really imply that we should not ship the default configuration file with `config_diagnostics = 1`. The users can decide themselves if they want to ignore the potential errors and drop the assignment.
