### ISSUE TITLE
What is the meaning of The return value "ok"?

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#13314]
![image](https://user-images.githubusercontent.com/69578444/98111847-34a81080-1edc-11eb-8311-6cce8fa06f41.png)

Does ok return 1 on success and 0 on failure?

**Comment by paulidale** [comment]
The function returns 1 on success and 0 on failure.

**Comment by DDvO** [comment]
As can be seen from the code, the variable `ok` just remembers the outcome of `evp_do_ciph_ctx_setparams()`
and `return ok != 0` returns the values explained by @paulidale.

The latter expression is very common - it makes sure that any non-zero outcome is mapped to success and zero to failure.

**Comment by 1185129439** [comment]
> The function returns 1 on success and 0 on failure.
 For EVP_CIPHER_CTX_set_padding，Does it return non-zero on success and 0 on failure also?

**Comment by 1185129439** [comment]
For EVP_CIPHER_CTX_set_padding(ctx, 1), this ctx was already set up for padding, The function returns 1 on success and 0 on failure?

**Comment by 1185129439** [comment]
For EVP_CIPHER_CTX_set_padding(ctx, 1), this ctx was already set up for padding, does the function returns 1 on success and 0 on failure?

**Comment by levitte** [comment]
@paulidale answered your question in https://github.com/openssl/openssl/issues/13314#issuecomment-721712600

**Comment by 1185129439** [comment]
For ok = evp_do_ciph_ctx_setparams, the function  return 1 on success. So when ok != 0(1 != 0), EVP_CIPHER_CTX_set_padding return 0.  Now , EVP_CIPHER_CTX_set_padding is failure. 

Why  evp_do_ciph_ctx_setparams is successful, but EVP_CIPHER_CTX_set_padding is failure?

**Comment by paulidale** [comment]
You need to learn how conditional expressions work in C: 1 != 0 has a value of 1.

**Comment by levitte** [comment]
The point is that `evp_do_ciph_ctx_setparams` may return -1 as well, and we ignore that in the interest of backward compatibility (1.1.1 code just sets the flag and doesn't check if the underlying cipher implementation actually uses it).  If it hadn't been  for that detail, we would just have done `return evp_do_ciph_ctx_setparams(ctx->cipher, ctx->provctx, params)` and not had an `ok` variable at all.

Does that answer your question better?
