### ISSUE TITLE
OpenSSH8.4p1 and OpenSSL1.1.1h not working on Linux 2.6.33.x device

### ISSUE THREAD

**Issue by serzagit** [openssl/openssl#13325]
Hello,

I cross compiled openssl 1.1.1h for a PowerPC processor (e500v2) and when I tested it in the host it works fine.

However, when I cross compiled openssh8.4p1 with openssl1.1.1 any openssh binary(ssh, sshd, sshkeygen..) I try to run hangs in command prompt.

When I cross compile openssh8.4p1 with openssl1.1.0l it works fine.

I would like to use the most recently version of openssl1.1.1, how can I debug this to know what is happening ??

I found a similar problem in this issue [#10181](https://github.com/openssl/openssl/issues/10181) but without a solution.

Can you help me to solve this issue ??

Architecture: PowerPC e500v2
System/OS: Linux kernel 2.6.33.9-rt1

configure and compile commands for openssl1.1.1h:
```
./Configure linux-ppc enable-zlib shared threads --with-zlib-include=/home/serza/eNodeB/OPENSSL_1.1.1/powerpc/zlib-1.2.11/usr/include --with-zlib-lib=/home/serza/eNodeB/OPENSSL_1.1.1/powerpc/zlib-1.2.11/usr/lib

make CC=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/bin/powerpc-linux-gnu-gcc
```

configure and compile commands for openssh8.4p1:
```
`./configure --host=powerpc-linux-gnu --prefix=/usr CC=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/bin/powerpc-linux-gnu-gcc CXX=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/bin/powerpc-linux-gnu-g++ LDFLAGS="-L/tmp/build_enb_distro/rootfs/usr/lib -L/home/serza/eNodeB/OPENSSL_1.1.1/powerpc/openssl-1.1.1h/lib" CFLAGS="-O1 -te500v2 -Wl,-rpath=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/powerpc-linux-gnu/libc/te500v2/lib:/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/powerpc-linux-gnu/libc/te500v2/usr/lib -Wl,--dynamic-linker=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/powerpc-linux-gnu/libc/te500v2/lib/ld.so.1 -I/tmp/build_enb_distro/rootfs/usr/include" CPPFLAGS="-O1 -te500v2 -Wl,-rpath=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/powerpc-linux-gnu/libc/te500v2/lib:/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/powerpc-linux-gnu/libc/te500v2/usr/lib -Wl,--dynamic-linker=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/powerpc-linux-gnu/libc/te500v2/lib/ld.so.1 -I/tmp/build_enb_distro/rootfs/usr/include" -with-ssl-dir=/home/serza/eNodeB/OPENSSL_1.1.1/powerpc/openssl-1.1.1h/usr --with-zlib=/home/serza/eNodeB/OPENSSL_1.1.1/powerpc/zlib-1.2.11/usr --with-pam --with-cflags --with-cppflags  --with-ldflags --disable-strip`


make 
```

Thanks in advance,

Sergio.

**Comment by t8m** [comment]
Most probably it is waiting on /dev/random read. You can try to find out with strace command.

**Comment by t8m** [comment]
If it is the case you can try to supply more entropy with rngd.

**Comment by serzagit** [comment]
Hi Tomás

Thank you for the quick answer.

I am a little bit lay at openssl, so some terms I wil need a more detailed explanation.

Can you explain how to use strace command and what do you mean on supply more entropy with rngd ??? what is rngd ??

Thank you and sorry for so many questions.

**Comment by t8m** [comment]
I am afraid I'll have to point you at Google for details but:
https://en.wikipedia.org/wiki/Strace
https://github.com/nhorman/rng-tools

**Comment by t8m** [comment]
There are also other alternative entropy supplying daemons - haveged for example.
http://www.issihosts.com/haveged/

**Comment by serzagit** [comment]
Don't worry about that. It helped to give me a direction.

I will research more about this and try some ways.

I will return as soon as I have more information

Thanks

**Comment by serzagit** [comment]
I used strace to run ssh and apparently it stucks at that point after oppening /dev/random and select:

```
[...]
open("/dev/null", O_RDWR|O_LARGEFILE)   = 3
close(3)                                = 0
brk(0)                                  = 0x2024d000
brk(0x2026e000)                         = 0x2026e000
futex(0x2012dc5c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x2012dc60, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x2012dc64, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x2012dd0c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x2012dc6c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x2012dc70, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x2012e020, FUTEX_WAKE_PRIVATE, 2147483647) = 0
SYS_359(0x2024fea8, 0x20, 0, 0x7fffffff, 0) = -1 ENOSYS (Function not implemented)
shmget(0x72, 1, 0)                      = -1 ENOENT (No such file or directory)
uname({sys="Linux", node="bsc913x", ...}) = 0
open("/dev/random", O_RDONLY)           = 3
select(4, [3], NULL, NULL, NULL
```

**Comment by t8m** [comment]
Then what I wrote above about supplying entropy applies.

**Comment by serzagit** [comment]
Hi Tomás,

Thank you so much for your help. You were right.

I activeted rngd in Linux and Openssh8.4p1 + Openssl1.1.1h worked as expected.

I tried havaged daemon and cross-compiled it for PowerPC, he also did the job to supply more entropy.

Regards.

**Comment by paulidale** [comment]
I cannot recommend havaged, it's entropy expansion process lies about how much entropy it really has.  By a factor of about 30.

I do recommend [cpujitter](https://www.chronox.de/jent.html) which is using the same basic concept but doesn't lie and makes more effort to output "good" randomness.

**Comment by serzagit** [comment]
Hi Pauli,

Thanks for the suggestion.

I cross compiled cpujitter, it was a little bit more painful than haveged to build, but it also did the job of supply entropy.
