### ISSUE TITLE
Unexpected side effect of downgrading a key

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13322]
I would expect that if a key gets downgraded internally, this is largely invisible to the user of that key. However this turns out not to be the case for the EVP_PKEY_public_check function:

Reproducer of the issue below:
````
#include <stdio.h>
#include <openssl/evp.h>
#include <openssl/rsa.h>

void check_key(EVP_PKEY *pkey)
{
    EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new(pkey, NULL);

    if (EVP_PKEY_public_check(pctx) > 0)
        printf("EVP_PKEY_public_check succeeded\n");
    else
        printf("EVP_PKEY_public_check failed\n");

    if (EVP_PKEY_check(pctx) > 0)
        printf("EVP_PKEY_check succeeded\n");
    else
        printf("EVP_PKEY_check failed\n");

    EVP_PKEY_CTX_free(pctx);
}

int main(void)
{
    RSA *r = RSA_new();

    EVP_PKEY *rsapkey = EVP_PKEY_new();
    EVP_PKEY_CTX *pctx;

    EVP_PKEY_assign_RSA(rsapkey, r);
    pctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL);

    if (!EVP_PKEY_keygen_init(pctx)) {
        printf("Error initing keygen\n");
        return 1;
    }

    if (EVP_PKEY_CTX_set_rsa_keygen_bits(pctx, 2048) <= 0) {
        printf("Error setting RSA length\n");
        return 1;
    }
    if (!EVP_PKEY_keygen(pctx, &rsapkey)) {
        printf("Error generating key\n");
        return 1;
    }

    check_key(rsapkey);
    EVP_PKEY_get0(rsapkey);
    printf("After downgrading the key\n");
    check_key(rsapkey);

    EVP_PKEY_free(rsapkey);
    EVP_PKEY_CTX_free(pctx);
    return 0;
}
````
Running this code gives the following output:
````
EVP_PKEY_public_check succeeded
EVP_PKEY_check succeeded
After downgrading the key
EVP_PKEY_public_check failed
EVP_PKEY_check succeeded
````

So, prior to the downgrade calling `EVP_PKEY_public_check()` on the key succeeds. But after the downgrade it fails. The problem appears to be that downgrade completely removes any associated key manager, EVP_PKEY_public_check() does not attempt to find one if one does not already exist, and the RSA key type is not supported by EVP_PKEY_public_check() in the ameth/pmeth legacy codepath.

**Comment by t8m** [comment]
On the other hand, this is not a regression, if I understand it right. So probably not a serious issue.

**Comment by mattcaswell** [comment]
> On the other hand, this is not a regression, if I understand it right. So probably not a serious issue.

No - it's not a regression. However, I don't agree that it is not necessarily serious. I've just been having a conversation with someone about the changes required to adapt their code for 3.0. They were doing some manual checks on the RSA key by extracting the RSA object from the EVP_PKEY and checking the various fields contained within it. I advised that the correct way to do this in 3.0 is to call EVP_PKEY_public_check(). However it seems that this function is not entirely reliable and may sometimes work, and sometimes not depending on how the EVP_PKEY was constructed and what it might have been used for in the meantime (sometimes the library does automatic downgrading of keys).

**Comment by levitte** [comment]
> The problem appears to be that downgrade completely removes any associated key manager

Uhm, no.  It's moved to the operation cache.

> EVP_PKEY_public_check() does not attempt to find one if one does not already exist

I'm not sure that it should, unless...

> and the RSA key type is not supported by EVP_PKEY_public_check() in the ameth/pmeth legacy codepath.

This does indeed sound like a problem, and it seems to me like such a check should simply be added in `crypto/rsa/rsa_ameth.c`.  I would characterize the lack of support a bug in 1.1.x already...  there's really no reason why `EVP_PKEY_public_check()` shouldn't be able to give a sensible return there, and is certainly surprising now that people are actually trying it!

**Comment by mattcaswell** [comment]
Won't this be an ongoing problem as we add `EVP_PKEY_foo()` capabilities in the future? Presumably such functions will only work where there is an associated key manager...but if we never add the key manager in such a situation then `EVP_PKEY_foo()` will work or not depending on whether or not the key has been downgraded in between.

I also very much don't like the idea of going down the legacy path at all for *any* key unless there is *only* an ENGINE implementation. Otherwise we should *always* use a provider. ENGINEs are the only reason the legacy METHODs are still sticking around, so we shouldn't be using them for any other purpose.

**Comment by t8m** [comment]
> I also very much don't like the idea of going down the legacy path at all for _any_ key unless there is _only_ an ENGINE implementation. Otherwise we should _always_ use a provider. ENGINEs are the only reason the legacy METHODs are still sticking around, so we shouldn't be using them for any other purpose.

Not just engines but also apps can set legacy METHODs.

**Comment by mattcaswell** [comment]
> Not just engines but also apps can set legacy METHODs.

Right. If a custom METHOD is in use then we should use it. Otherwise we should use the provider. We shouldn't be using built-in METHODs.

**Comment by levitte** [comment]
> Not just engines but also apps can set legacy METHODs.

Yup...  some of us keep forgetting that :wink:

...  and even then, if an ENGINE supplies an alternative EVP_PKEY_ASN1_METHOD and doesn't implement certain functionality, we risk the same problem.  Well, not entirely, the new thing we do is to convert a key from one backend to another.

But either way, what we *should* do is to ensure that our different backends are compatible enough with each other.  Either we *take away* the public key check in rsa_keymgmt.c, or we *add* a public key checker in `rsa_ameth.c`.  Both would solve the incompatibility and neither would be a regression (*taking away* would even be backward compatible with 1.1.1 :laughing:).

**Comment by levitte** [comment]
Summary: let's make sure that *our* stuff are compatible across the board.

**Comment by mattcaswell** [comment]
> Summary: let's make sure that our stuff are compatible across the board.

I think this is the wrong approach. We should not need to make fixes to the legacy code paths. We shouldn't be using it at all.

**Comment by levitte** [comment]
> I think this is the wrong approach. We should not need to make fixes to the legacy code paths.

So the *take away* approach, then :wink:

> We shouldn't be using it at all.

Sooooo...  that would make it hard for anyone to create an RSA and feed it numbers and then EVP_PKEY_assign_RSA().

However, what I hear is that we should try to avoid downgrades as much as possible.  It's possible that the answer is to look through the places where we still do that and see if they can be rewritten to avoid that entirely.  That would be consistent with other efforts we currently have, that are meant to encourage to move off of legacy keys.

**Comment by mattcaswell** [comment]
> Sooooo... that would make it hard for anyone to create an RSA and feed it numbers and then EVP_PKEY_assign_RSA().

Why? Ok...we need to export functions...but what else?

**Comment by levitte** [comment]
> > Sooooo... that would make it hard for anyone to create an RSA and feed it numbers and then EVP_PKEY_assign_RSA().
> 
> Why? Ok...we need to export functions...but what else?

Never mind, I hadn't thought that through.

**Comment by levitte** [comment]
#13334 attemps to solve this situation
