### ISSUE TITLE
Possible Documentation Error - EVP_VerifyInit

### ISSUE THREAD

**Issue by mfeldmanBT** [openssl/openssl#13342]
Please check page https://www.openssl.org/docs/manmaster/man3/EVP_VerifyInit.html
Notes, 2nd paragraph:
The call to EVP_Verify**Final**() internally finalizes a copy of the digest context. This means that calls to EVP_VerifyUpdate() and EVP_VerifyFinal() can be called later to digest and verify additional data.

Should it say:
The call to EVP_Verify**Init**() ....

**Comment by kroeckx** [comment]
No, the text is correct. Once you called the Final function, you
can add more data using the Update function, and call Final again
to check a new signature that covers all data added since the Init
call.

**Comment by levitte** [comment]
It is a bit curiously expressed, one has to admit...

**Comment by mattcaswell** [comment]
>  Once you called the Final function, you
can add more data using the Update function

Hmm. This makes me think of #13210. In that case we are saying that using the APIs in that way is dangerous and we shouldn't allow it. Here though we seem to be encouraging it in the documentation.

**Comment by mattcaswell** [comment]
> Hmm. This makes me think of #13210. In that case we are saying that using the APIs in that way is dangerous and we shouldn't allow it. Here though we seem to be encouraging it in the documentation.

(Oh...I see @kroeckx thought about the same thing and made a comment about it in #13210 - probably that is a better place for this aspect of the conversation)
