### ISSUE TITLE
When does default library context release the cache algorithms after use fetch function and cache algorithms?

### ISSUE THREAD

**Issue by wongmz** [openssl/openssl#13360]
hi, i have some questions.
Default library context will cache algorithms when use fetch function, but when does it release the cache? Does it release automatically?
In future releases, we can use OSSL_FUNC_PROVIDER_QUERY_OPERATION to let the core not cache algorithms?

**Comment by wongmz** [comment]
Default library context is on thethread or process?

**Comment by levitte** [comment]
> Default library context will cache algorithms when use fetch function, but when does it release the cache? Does it release automatically?

It's released automatically on process exit (`atexit()` is used for this)

> In future releases, we can use OSSL_FUNC_PROVIDER_QUERY_OPERATION to let the core not cache algorithms?

We could make that an option already, but changing this line:

https://github.com/openssl/openssl/blob/00eae3f9cf4c45f3d0c6561512a51aef74ac8b3d/providers/defltprov.c#L478

All that's needed is to change the `0` to a `1`.

**Comment by mattcaswell** [comment]
> Default library context is on the thread or process?

There is a single library context that is shared between, and used by default in all threads in the process. However you can override what that default is on a per thread basis using `OSSL_LIB_CTX_set0_default()`:

https://www.openssl.org/docs/manmaster/man3/OSSL_LIB_CTX_set0_default.html

**Comment by wongmz** [comment]
> > Default library context will cache algorithms when use fetch function, but when does it release the cache? Does it release automatically?
> 
> It's released automatically on process exit (`atexit()` is used for this)
> 
> > In future releases, we can use OSSL_FUNC_PROVIDER_QUERY_OPERATION to let the core not cache algorithms?
> 
> We could (or _you_ could, in your source copy) make that an option already, but changing this line:
> 
> https://github.com/openssl/openssl/blob/00eae3f9cf4c45f3d0c6561512a51aef74ac8b3d/providers/defltprov.c#L478
> 
> All that's needed is to change the `0` to a `1`.

@levitte hi, levitte.
I have try chage *no_cache to 1,but after i do that, i can't establishing an SSL Connection.Do I need to call other functions?

**Comment by wongmz** [comment]
> > Default library context is on the thread or process?
> 
> There is a single library context that is shared between, and used by default in all threads in the process. However you can override what that default is on a per thread basis using `OSSL_LIB_CTX_set0_default()`:
> 
> https://www.openssl.org/docs/manmaster/man3/OSSL_LIB_CTX_set0_default.html

Thank you very much for your reply.

**Comment by mattcaswell** [comment]
> I have try chage *no_cache to 1,but after i do that, i can't establishing an SSL Connection.Do I need to call other functions?

Looks like this is buggy. I opened a separate issue for it #13364.
