### ISSUE TITLE
The rsa 4096 bits key generation has about 50% performance degradation in alpha5 compare to 1.1.1f version.

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#13370]
When i use  "openssl genrsa -out rsakey.pem 4096" to generate the rsa key, need about 6s  to generate five keys in 1.1.1f,but need about 11s in openssl 3.0.0 alpha5.
    so ,i wonder if there any big difference in rsa key generation to lead to the above result?

**Comment by t8m** [comment]
OpenSSL now uses different RSA key generation method according to FIPS 186-4 B.3.6 for (non-multiprime) keys >= 2048 bits which is slower.

**Comment by stardrift1** [comment]
> OpenSSL now uses different RSA key generation method according to FIPS 186-4 B.3.6 for (non-multiprime) keys >= 2048 bits which is slower.
 thanks for reply ，and another question is that if i don't want to use the new method as the performance don't fits my requirements，is there any other way i can use the old method?

**Comment by mattcaswell** [comment]
Currently the code says this:

````
    /*
     * Only multi-prime keys or insecure keys with a small key length will use
     * the older rsa_multiprime_keygen().
     */
    if (primes == 2 && bits >= 2048)
        ok = ossl_rsa_sp800_56b_generate_key(rsa, bits, e_value, cb);
#ifndef FIPS_MODULE
    else
        ok = rsa_multiprime_keygen(rsa, bits, primes, e_value, cb);
````

So selecting an insecure key length <2048, or generating a multi prime key will get you the old key gen. Otherwise you get the new one.

**Comment by stardrift1** [comment]
ok ,get it ,thanks,maybe multi prime is a choice

**Comment by paulidale** [comment]
Why is key generation performance so critical?
This generally isn't something that should be done often.

**Comment by stardrift1** [comment]
> Why is key generation performance so critical?
It's a important point to the applicant's design,so should use with extra careful

**Comment by kroeckx** [comment]
> ok ,get it ,thanks,maybe multi prime is a choice

Before using more than 2 primes, I suggest that you look into what
that all means.

**Comment by kroeckx** [comment]
> > Why is key generation performance so critical?
> It's a important point to the applicant's design,so should use with extra careful

RSA key generation has never been a fixed time. You try to find
primes. Sometimes that goes faster than other times. Even if I
test it using 1.1.1 just a few times I see a factor of more than 30
between the fastest and slowest. I was able to find 2 primes in
100 ms, and also in 3.6 seconds.

If the performance is so important, you might need to consider
doing it differently. You could for instance do it at a different
time when the user doesn't wait for it, or use an EC key.

**Comment by paulidale** [comment]
For 3.0, a decision needs to be made to either always use the old path outside of FIPS or leave this as it stands.

**Comment by paulidale** [comment]
There is a paper that claims to be able to fingerprint OpenSSL generated keys due to biases in the old generation method.

**Comment by stardrift1** [comment]
I Just fund that the prime test desig change related to this issue may be the Biggest reason for this performance degradation:https://github.com/openssl/openssl/pull/9272.When i not use the api provided by openssl to gen the rsa key pair,but just use the bn function to gen,there is performance degradation too,when i modify to code to the old version,the  performance is the same.which i change are BN_is_prime_fasttest_ex->bn_check_prime_int->bn_mr_min_checks(modify)->bn_is_prime_int->calc_trial_divisions(modify to return 2048 as the old version code).

**Comment by kroeckx** [comment]
What you might see is that we now always use 64 rounds of the
Miller-Rabin test, while it used to be fewer. See #9272.

**Comment by stardrift1** [comment]
> 64 rounds

yes ,i modify this to BN_prime_checks_for_size from bn_mr_min_checks

**Comment by paulidale** [comment]
The extra checks are deliberate then.

**Comment by kroeckx** [comment]
So if I understand things correctly, the difference is time is because of the different amount of Miller-Rabin test, and not because we switched to the FIPS algorithm. So does that mean we can close this issue?

**Comment by paulidale** [comment]
I think this can be closed.  There are good reasons to want the extra iterations.

**Comment by mattcaswell** [comment]
I wonder whether we should expand the CHANGES entry a little more to explain the consequences of this. Currently it doesn't mention RSA at all:

````
 * Change generating and checking of primes so that the error rate of not
   being prime depends on the intended use based on the size of the input.
   For larger primes this will result in more rounds of Miller-Rabin.
   The maximal error rate for primes with more than 1080 bits is lowered
   to 2^-128.

   *Kurt Roeckx, Annie Yousar*
````

**Comment by paulidale** [comment]
A CHANGES update is worthwhile IMO.

**Comment by paulidale** [comment]
See #13439 for a possible CHANGES entry.
