### ISSUE TITLE
1.1.1h: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [openssl/openssl#13383]
Unpatched vanilla source tree.
```
+ OPENSSL_ENABLE_MD5_VERIFY= \
+ OPENSSL_SYSTEM_CIPHERS_OVERRIDE=xyz_nonexistent_file
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test

[..]

../../util/shlib_wrap.sh ../v3nametest => 0
ok 1 - running v3nametest
ok
../test/recipes/95-test_external_boringssl.t ....... skipped: No external tests in this configuration
../test/recipes/95-test_external_krb5.t ............ skipped: No external tests in this configuration
../test/recipes/95-test_external_pyca.t ............ skipped: No external tests in this configuration
../test/recipes/99-test_ecstress.t .................
1..1
ok 1 # skip Skipping EC stress test
ok
../test/recipes/99-test_fuzz.t .....................
1..11
# Subtest: Fuzzing asn1
    1..1
../../util/shlib_wrap.sh ../../fuzz/asn1-test ../../fuzz/corpora/asn1 => 0
    ok 1
ok 1 - Fuzzing asn1
# Subtest: Fuzzing asn1parse
    1..1
../../util/shlib_wrap.sh ../../fuzz/asn1parse-test ../../fuzz/corpora/asn1parse => 0
    ok 1
ok 2 - Fuzzing asn1parse
# Subtest: Fuzzing bignum
    1..1
../../util/shlib_wrap.sh ../../fuzz/bignum-test ../../fuzz/corpora/bignum => 0
    ok 1
ok 3 - Fuzzing bignum
# Subtest: Fuzzing bndiv
    1..1
../../util/shlib_wrap.sh ../../fuzz/bndiv-test ../../fuzz/corpora/bndiv => 0
    ok 1
ok 4 - Fuzzing bndiv
# Subtest: Fuzzing client
    1..1
../../util/shlib_wrap.sh ../../fuzz/client-test ../../fuzz/corpora/client => 0
    ok 1
ok 5 - Fuzzing client
# Subtest: Fuzzing conf
    1..1
../../util/shlib_wrap.sh ../../fuzz/conf-test ../../fuzz/corpora/conf => 0
    ok 1
ok 6 - Fuzzing conf
# Subtest: Fuzzing crl
    1..1
../../util/shlib_wrap.sh ../../fuzz/crl-test ../../fuzz/corpora/crl => 0
    ok 1
ok 7 - Fuzzing crl
# Subtest: Fuzzing server
    1..1
../../util/shlib_wrap.sh ../../fuzz/server-test ../../fuzz/corpora/server => 0
    ok 1
ok 8 - Fuzzing server
# Subtest: Fuzzing x509
    1..1
../../util/shlib_wrap.sh ../../fuzz/x509-test ../../fuzz/corpora/x509 => 0
    ok 1
ok 9 - Fuzzing x509
# Subtest: Fuzzing cms
    1..1
../../util/shlib_wrap.sh ../../fuzz/cms-test ../../fuzz/corpora/cms => 0
    ok 1
ok 10 - Fuzzing cms
# Subtest: Fuzzing ct
    1..1
../../util/shlib_wrap.sh ../../fuzz/ct-test ../../fuzz/corpora/ct => 0
    ok 1
ok 11 - Fuzzing ct
ok

Test Summary Report
-------------------
../test/recipes/80-test_ca.t                     (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=158, Tests=1884, 146 wallclock secs ( 5.80 usr  0.71 sys + 112.37 cusr 47.12 csys = 166.00 CPU)
Result: FAIL
make[1]: *** [Makefile:208: _tests] Error 1
```

**Comment by paulidale** [comment]
Platform?  Configure options?  Run `perl configdata.pm --dump` and provide it's output.

Could you run `make test TESTS=test_ca V=1` and include the output?

**Comment by t8m** [comment]
Given the command line I expect this is from a Fedora package. This should be reported against openssl in Fedora bugzilla. The shortened log is also not helpful because the important stuff - the test_ca output was cut out.

**Comment by kloczek** [comment]
Fiirst of all: I'm not building openssl for Fedora.
Will back to you shortly with full output of the fest suite.

**Comment by t8m** [comment]
Then `OPENSSL_ENABLE_MD5_VERIFY=` and `OPENSSL_SYSTEM_CIPHERS_OVERRIDE=xyz_nonexistent_file` does not make any sense as those environment variables are patched in with Fedora specific patches.
Also please output the configdata dump output as requested above.

**Comment by kloczek** [comment]
Yes, I'm using some Fedora pataches but I'm not buldig my package for Fedora.

Do you have some details what needs to be changed/fixed in those patches to pass corretly test suite?

Kind od side question: is it anywhere some discussion about include some fedora patches to openssl?
And/or if that was already siscussed .. wny they've been refused?

**Comment by t8m** [comment]
I would recommend starting with clean upstream openssl build. Then, if that passes, apply the patches you need from Fedora. Then, if the build&test fails, this is clearly issue to discuss with Fedora openssl maintainer.

Many (most) of the Fedora patches do not make sense in the broader openssl upstream context - for example both patches introducing those environment variables mentioned above do not as they are mostly legacy stuff for previous features of Fedora that were obsoleted now by the provider work in 3.0.

Also the Fedora patches are not tested separately but as a whole and they do not support building with arbitrary set of enable-<stuff> so if you select just a few patches from Fedora and decide to enable different stuff than in the Fedora build, you're on your own as for making the resulting openssl to build and actually pass tests.

Anyway this is really off-topic here.

**Comment by kloczek** [comment]
OK. You are right.
I promisse will do that.
For now I'll close that ticket.

Thank you for your time.

Nevertheless I see some value of some fedora patches and I'm sill curiouse why none of them are included in main openssl tree?
Did someone from Fedora already have been trying to push them as PRs to openssl tree?

**Comment by t8m** [comment]
The only two patches that might make some sense upstream (at least partially) are https://github.com/t8m/openssl/commit/a161ed3afbe0c23b3e5b8cb0f844810ca298d512 and https://github.com/t8m/openssl/commit/c2f58d840d926c1867fbbaf4c0376ffa4500ab7b . There might be some others in the sense of yeah, that thing would be interesting upstream, but those would require basically rewrite from scratch, because they were not designed to be applicable upstream. Also please note that 1.1.1 upstream branch takes bug fixes and the patches from the src.rpm that are not in the fedora-package branch in my openssl github repo are not relevant to 3.0 at all.

**Comment by kloczek** [comment]
As I'm controlling openssl in distribution on which I'm working I've started thinking on move to openssl 3.0 alpha like already openmandriva did (IIRC). If I'm right looks like 3.0.x alpha is already ready to some wider use.
I would be also interested details which one more fedora patches you may be interested and what needs to be rewrited because using those hints I may try to spend some time on prepare commits basing on those patches.
