### ISSUE TITLE
Cipher Suite Protocol Version Wrong?

### ISSUE THREAD

**Issue by MarkVLK** [openssl/openssl#13386]
_Tested on OpenSSL 1.0.1l-fips_

Using **openssl** to list ciphers seems to associate a few cipher suites with an incorrect protocol version. In particular the two cipher suites below appear to be identified as belonging to SSLv3 protocol version whereas [RFC 4132](https://tools.ietf.org/html/rfc4132) suggests that these cipher suites were not introduced until TLSv1.0 and sure enough the [openssl docs](https://www.openssl.org/docs/man1.0.2/man1/ciphers.html) list these cipher suites as extending TLSv1.0, unless I'm misunderstanding something.

```
openssl ciphers -v "HIGH:MEDIUM:-SSLv2:@STRENGTH"
```

DHE-RSA-CAMELLIA256-SHA SSLv3 Kx=DH Au=RSA Enc=Camellia(256) Mac=SHA1
DHE-DSS-CAMELLIA256-SHA SSLv3 Kx=DH Au=DSS Enc=Camellia(256) Mac=SHA1

I would expect that these cipher suites be associated with TLSv1 rather than SSLv3. If there's some reason they're intended to be listed as associated with protocol version SSLv3 instead, an explanation would be helpful!

**Comment by mattcaswell** [comment]
The protocol version number indicates the minimum version number in which the ciphersuite is supported. This is *not* necessarily the same as the protocol version number in which ciphersuite was first introduced. These ciphersuites are fully backwards compatible with SSLv3, e.g. assuming you have a version of OpenSSL with support for SSLv3 compiled in:

````
$ openssl s_server -cipher "DHE-RSA-CAMELLIA256-SHA" -cert server.pem -ssl3
````
Followed by:
````
$ openssl s_client -cipher "DHE-RSA-CAMELLIA256-SHA" -ssl3
````
Will create a successful connection.

**Comment by MarkVLK** [comment]
Thank you for clarifying, that makes sense!
