### ISSUE TITLE
RAND algorithm selection in 3.0.0

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#13399]
The OSSL_OP_RAND interface in 3.0.0 (master) feels tedious for TPM-based hardware implementations. I am not sure if this is desired.

The obsolete RAND_METHOD based approach allows engines to define a RAND function that gets called from RAND_bytes, including when invoked via the command line `openssl rand -engine tpm 16`. Quite simple.

The replacement(?) OSSL_OP_RAND based approach:
 1) Searches for the `CTR-DRBG` algorithm, unless `random` is defined in the configuration. This requires the TPM provider to either publish its RAND algorithm as `CTR-DRBG` eventhough it's something else, or the user has to define a configuration file, which was not required before. The simple `openssl rand -provider tpm 16` doesn't work anymore (without `CTR-DRBG` or configuration).
 2) Defines the *primary*, *public* and *private* DRBG instances all based on the same algorithm from the Provider. Since there is one generator in the TPM, which cannot be (fully) seeded, the three instances will(?) be identical. It feels unnecessary to create the RNG hierarchy in case of a non-seedable hardware generator. Moreover, the *primary* instance initialization requires context locking to be implemented by the Provider, which is otherwise optional and makes no sense (to me) in the context of hardware TPM.

In that matter:
 1) I wish there was a possibility for the Provider to define a "default" RAND algorithm name to be used if nothing is configured, instead of the fixed `CTR-DRBG`, or to have a rule that always the first OSSL_ALGORITHM in the table is considered to be the default. So that user is not forced to define a configuration in the simple case of a random number generation.
 2) I wonder if the hierarchy has to be always based on the same algorithm, because in case of a TPM it could make sense, for example, to have the *primary* based on the built-in `CTR-DRBG` and ignore its result and then define *public* and *private* based on the (non-seedable) TPM RNG though the Provider, or to have a *primary* and *public* based on the built-in `CTR-DRBG`, and only the *private* based on the TPM Provider.

What is your view on this, please? I can try to propose a pull request if there is a consensus on the approach to address this.

**Comment by beldmit** [comment]
For the Russian GOST purposes, we used the logic "engine provides RAND method". We still want this logic for providers (and I think, China government-certified products will require something similar).

**Comment by gotthardp** [comment]
Of course, the good old "engine provides RAND method" would be also suitable for me, but the documentation says *The ability for an ENGINE to replace the RAND API was deprecated in OpenSSL 3.0.*

**Comment by paulidale** [comment]
As noted, it is possible to get the result you want:

1. Create a provider that has a TPMRNG.
1. Use the configuration to request TPM as the RNG to be loaded.
1. No DRBGs.

It is true that libcrypto will still create three instances of EVP_RAND over the TPM.  That they all use the same TPM underneath isn't a concern is it?  Allowing the RNG plumbing architecture to be mutable is something we'd like but I doubt it will be done for 3.0.  A way to specify the RAND to be fetched that doesn't use configuration is something I expect will be done eventually too.

Leaving the primary as CTR-DRBG while using TPM for the public and private is kind of odd.  The primary will be unused.  It would be easier to just use the TPM for all three.

Being able to specify a default RAND does sound useful.  It's not clear to me how it would be hooked up.  If you've got any ideas, I'd be interested.  I'll raise this at the technical committee meeting week.  @mspncp any thoughts?

Finally, the RAND_METHOD calls are only deprecated.  They still work and will remain so at least until 4.0.  Likewise, engines should continue to work.

**Comment by gotthardp** [comment]
Thanks. The three instances are not a big concern. The CTR-DRBG hardcoded as default is most troublesome. I can probably see only the most obvious implementation options:
 * Pass the default RAND algorithm name through a new OSSL_DISPATCH function, or a new OSSL_PARAM;
 * Use the algorithm properties to tag the default algorithm (e.g. `"default=yes,provider=tpm2,fips=yes"`) and enhance the EVP_RAND_fetch to choose the tagged algorithm if the algorithm name has not been specified by the caller or in the config.

But there may be a more elegant solution.

**Comment by beldmit** [comment]
@paulidale, would you mind to document your proposed solution?

**Comment by paulidale** [comment]
I don't have a proposed solution yet.  I've a few ideas about how it might be approached but nothing substantial.

**Comment by paulidale** [comment]
This isn't going to be addressed for 3.0.  However, if something were proposed and submitted, it would be considered.

**Comment by beldmit** [comment]
Could it be planned immediately after the 3.0? It seems mission-critical for national crypto

**Comment by nhorman** [comment]
so, planning immediately after 3.0 didn't happen.  Is this still something that can be planned still?  or is there no interest?

**Comment by paulidale** [comment]
Likely covered by #24498.  Closing.
