### ISSUE TITLE
The user support resource page is not valid now

### ISSUE THREAD

**Issue by xkqian** [openssl/openssl#13396]
Once you want to report new issues, system will remind you to refer the the support page: 

>     If you're asking about how to use OpenSSL, this isn't the right 
>     forum.  Please see our User Support resources:
>     https://github.com/openssl/openssl/blob/master/.github/SUPPORT.md

But, the link https://github.com/openssl/openssl/blob/master/.github/SUPPORT.md doesn't work now.

**Comment by levitte** [comment]
Fixed in #13397.  Thank you!
