### ISSUE TITLE
Why there are much alg have the  performance degradation problem?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#13407]

**Comment by stardrift1** [comment]
Encrypt/Decrypt   Algorithm |   |   | 16 bytes(k/s) | 64 bytes(k/s)
-- | -- | -- | -- | --
  | 1.1.1f | 3.0.0 | Percentage Diff   (%)(3.0.0-1.1.1f/1.1.1f) | 1.1.1f | 3.0.0 | Percentage Diff   (%)(3.0.0-1.1.1f/1.1.1f)
aes-128-gcm | 382765.1 | 358116.79 | -6.43953955 | 1029171.99 | 998325.99 | -2.997166683
aes-256-gcm | 342468.88 | 303120.78 | -11.48954031 | 949272.3 | 818651.73 | -13.7600739
aes-128-ccm | 159026.82 | 166945.85 | 4.979682044 | 450991.91 | 480293.38 | 6.497116545
aes-256-ccm | 132729.62 | 119189.72 | -10.20111411 | 367570.15 | 351785.41 | -4.294347623
aes-128-ctr | 436971.8 | 598410.35 | 36.94484404 | 1283991.19 | 1537795.82 | 19.76685136
aes-256-ctr | 365281.65 | 533223.53 | 45.97599688 | 1227385.07 | 1429240.98 | 16.44601315
des-cbc | 58305.47 | 54618.54 | -6.32347188 | 56901.12 | 61425.26 | 7.950880404
des-ede3 | 22680.77 | 22664.63 | -0.071161605 | 22874.84 | 22906.09 | 0.136612977
sha1 | 102295.56 | 80872.1 | -20.94270758 | 253656.96 | 165868.44 | -34.60915088
sha256 | 50611.06 | 54900.94 | 8.476171019 | 131573.08 | 116798.51 | -11.22917393
sha512 | 42588.05 | 43124.12 | 1.258733377 | 163007.15 | 172232.33 | 5.659371383
aes-128-cbc | 145951.32 | 101394.87 | -30.52829532 | 182638.81 | 118340.67 | -35.20508045
aes-192-cbc | 153043.16 | 87340.23 | -42.93098104 | 158095.91 | 97385.47 | -38.40101872
aes-256-cbc | 132168.08 | 78799.9 | -40.37902344 | 138665.73 | 79965.55 | -42.33214652

**Comment by stardrift1** [comment]
i use  "openssl speed -evp ××" to get this datas

**Comment by stardrift1** [comment]
much more data are like below:

64 bytes(k/s)
-2.997166683
-13.7600739
6.497116545
-4.294347623
19.76685136
16.44601315
7.950880404
0.136612977
-34.60915088
-11.22917393
5.659371383
-35.20508045
-38.40101872
-42.33214652

256 bytes(k/s)

5.60847441
-5.521645852
1.245271926
3.077855319
30.38664778
8.651204312
3.066836347
-1.696055092
-47.43223314
13.68533521
16.71495324
-36.52389641
-35.71318738
-39.94763183

1024 bytes(k/s)
-18.64358
0.9412298
-0.042814
2.8369394
5.0579355
3.778088
-0.368829
-0.419221
-1.602735
25.176471
22.241589
-34.04642
-36.13742
-37.85786

8192 bytes(k/s)
-11.935329
-1.6383827
-0.3172754
0.47879301
-0.2882417
0.57896773
0.29574909
-1.384952
-0.0995673
0.03665348
7.6397739
-33.921858
-36.132703
-37.68891

16384 bytes(k/s)
-1.153113348
-1.889231291
-0.326986259
1.214131271
0.087831719
1.499715234
0.510327107
0.047505628
0.674206816
2.417077272
-18.9185446
-37.01822681
-35.73831619
-37.72232322

**Comment by levitte** [comment]
I translated all the extra numbers into a table, for easier viewing:

All numbers are Percentage Diff   (%)(3.0.0-1.1.1f/1.1.1f)

Encrypt/Decrypt   Algorithm | 64 bytes(k/s) | 256 bytes(k/s) | 1024 bytes(k/s) | 8192 bytes(k/s) | 16384 bytes(k/s) 
--------------------------- | ------------- | -------------- | --------------- | --------------- | ----------------
aes-128-gcm                 | -2.997166683  | 5.60847441     | -18.64358       | -11.935329      | -1.153113348
aes-256-gcm                 | -13.7600739   | -5.521645852   | 0.9412298       | -1.6383827      | -1.889231291
aes-128-ccm                 | 6.497116545   | 1.245271926    | -0.042814       | -0.3172754      | -0.326986259
aes-256-ccm                 | -4.294347623  | 3.077855319    | 2.8369394       | 0.47879301      | 1.214131271
aes-128-ctr                 | 19.76685136   | 30.38664778    | 5.0579355       | -0.2882417      | 0.087831719
aes-256-ctr                 | 16.44601315   | 8.651204312    | 3.778088        | 0.57896773      | 1.499715234
des-cbc                     | 7.950880404   | 3.066836347    | -0.368829       | 0.29574909      | 0.510327107
des-ede3                    | 0.136612977   | -1.696055092   | -0.419221       | -1.384952       | 0.047505628
sha1                        | -34.60915088  | -47.43223314   | -1.602735       | -0.0995673      | 0.674206816
sha256                      | -11.22917393  | 13.68533521    | 25.176471       | 0.03665348      | 2.417077272
sha512                      | 5.659371383   | 16.71495324    | 22.241589       | 7.6397739       | -18.9185446
aes-128-cbc                 | -35.20508045  | -36.52389641   | -34.04642       | -33.921858      | -37.01822681
aes-192-cbc                 | -38.40101872  | -35.71318738   | -36.13742       | -36.132703      | -35.73831619
aes-256-cbc                 | -42.33214652  | -39.94763183   | -37.85786       | -37.68891       | -37.72232322

**Comment by levitte** [comment]
The SHA performance changes are jumping quite sporadically...

**Comment by kroeckx** [comment]
So I've tested "openssl speed -evp sha1" on a current master and OpenSSL_1_1_1-stable branch.
What I get is:

Version | 16 bytes(k/s) | 64 bytes(k/s) | 256 bytes(k/s) | 1024 bytes(k/s) | 8192 bytes(k/s) | 16384 bytes(k/s) 
--| -- | -- | -- | -- | -- | --
1.1.1 | 57861 | 171142 | 398294 | 594279 | 690582 | 696843
master | 24344 |  85196 |  252298 | 495502 | 686567   | 707309
difference | -58% | -50% | -37% | -17% | -0.6% | +1.5

**Comment by kaduk** [comment]
Is that just for a single trial, or are you doing multiple runs and properly computing statistics on them?
(hint: I am not going to place much faith in any single run)

**Comment by kroeckx** [comment]
For my results, it was an average of 5 runs, the standard
deviation was 2% or lower.

**Comment by stardrift1** [comment]
> you doing multiple runs
I do it twice,the aes-cbc alg's performance degradation are the same.

**Comment by kaduk** [comment]
> For my results, it was an average of 5 runs, the standard
deviation was 2% or lower.

Thanks for confirming.

**Comment by mattcaswell** [comment]
@stardrift1 Is it possible to get updated performance numbers based  on the latest master commits? Numerous fixes have gone in, and it would be good to see if they make a difference for your setup.

**Comment by stardrift1** [comment]
@mattcaswell yes ,i will do the performance test using the master's code later,and will write the result in this issue

**Comment by stardrift1** [comment]
@mattcaswell  this two times the result when test master
1 | 16 bytes | 64 bytes | 256 bytes | 1024 bytes | 8192 bytes | 16384 bytes
-- | -- | -- | -- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
aes-128-gcm | 363889.38 | 332076.91 | 9.579850041 | 1006228.76 | 532859.24 | 88.83575332 | 2065092.61 | 1534312.36 | 34.59401513 | 3206114.3 | 3197674.5 | 0.263935557 | 4055490.56 | 4031100.25 | 0.605053422 | 4112400.38 | 4144010.58 | -0.762792454
aes-256-gcm | 341862.27 | 342494.28 | -0.184531549 | 924513.75 | 952558.53 | -2.944152944 | 1733298.77 | 1682467.84 | 3.021212578 | 2523824.81 | 2511519.74 | 0.489945184 | 2958016.51 | 2968089.94 | -0.339390996 | 2995879.94 | 2988976.81 | 0.230952946
aes-128-ccm | 171683.83 | 146230.74 | 17.40611447 | 486685.46 | 439818.5 | 10.65597741 | 801834.07 | 765690.11 | 4.720442321 | 951561.22 | 937672.7 | 1.481169282 | 961904.64 | 1005882.03 | -4.372022632 | 1013060.95 | 1010521.43 | 0.251307882
aes-256-ccm | 144445.82 | 134567.5 | 7.340791796 | 385882.3 | 368128.87 | 4.822612799 | 600727.81 | 588973.74 | 1.995686599 | 697065.13 | 692574.55 | 0.648389404 | 730524.33 | 729631.4 | 0.122380972 | 733184 | 732026.2 | 0.158163738
aes-128-ctr | 640848.34 | 453966.81 | 41.16634209 | 1566316.1 | 1351763.67 | 15.87203701 | 2748917.33 | 2843013.46 | -3.309732132 | 3951352.83 | 3804428.97 | 3.861916234 | 4209489.24 | 4190699.52 | 0.44836715 | 4244084.05 | 4235739.14 | 0.197011896
aes-256-ctr | 538096.53 | 379074.49 | 41.95007688 | 1526235.84 | 1198640.04 | 27.3306238 | 2515316.39 | 1680978.35 | 49.63407411 | 2892390.4 | 2307138.22 | 25.36701854 | 3012676.27 | 3001480.53 | 0.373007251 | 3039827.29 | 3031520.6 | 0.274010673
des cbc | 59390.06 | 58839.11 | 0.936366984 | 61080.6 | 61159.81 | -0.129513156 | 61601.02 | 61679.27 | -0.126865963 | 61080.23 | 61848.92 | -1.242851128 | 60730.03 | 54558.72 | 11.31131742 | 61756.76 | 51074.39 | 20.91531588
des ede3 | 22181 | 21782.69 | 1.828562037 | 23010.9 | 22586.13 | 1.880667472 | 23131.78 | 23169.11 | -0.161119698 | 23161.24 | 23276.89 | -0.496844725 | 23030.44 | 23262.55 | -0.997783992 | 22457 | 23303.51 | -3.632542909
sha1 | 56304.28 | 57975.62 | -2.882832473 | 165671.34 | 170339.26 | -2.74036649 | 396658.6 | 397552.04 | -0.224735358 | 618777.26 | 606569.47 | 2.012595523 | 718102.53 | 740401.15 | -3.011694404 | 732233.73 | 750212.44 | -2.396482522
sha256 | 38674.25 | 38270.54 | 1.054884514 | 104341.03 | 106712.55 | -2.222344045 | 220056.06 | 223539.29 | -1.558218244 | 299625.81 | 303533.06 | -1.287256815 | 336115.03 | 342526.63 | -1.87185446 | 339815.08 | 344369.83 | -1.322633286
sha512 | 29440.59 | 25105.49 | 17.2675379 | 117463.57 | 107306.52 | 9.465454662 | 244324.95 | 232238.59 | 5.204285817 | 404447.91 | 395995.82 | 2.134388691 | 502775.81 | 501888.34 | 0.176826184 | 510536.36 | 510847.66 | -0.060937932
aes-128 cbc | 783277.38 | 633345.5 | 23.67299997 | 971060.14 | 963973.21 | 0.735179145 | 998844.42 | 999254.36 | -0.04102459 | 1004079.79 | 1008163.5 | -0.405064258 | 1014658.39 | 1010128.21 | 0.448475743 | 1016747.35 | 1010909.18 | 0.577516766
aes-192 cbc | 731761.31 | 599226.7 | 22.11760758 | 826095.04 | 826600.96 | -0.061204865 | 631675.14 | 837121.19 | -24.54197223 | 820368.73 | 839930.54 | -2.328979489 | 854777.86 | 845490.86 | 1.098415186 | 849035.26 | 846359.21 | 0.316183716
aes-256 cbc | 564278.42 | 577243.82 | -2.246087277 | 717714.43 | 719440.34 | -0.239896195 | 728818.6 | 728247.3 | 0.078448626 | 731069.1 | 731780.44 | -0.097206752 | 733779.29 | 733391.53 | 0.052872168 | 723244.37 | 735461.38 | -1.66113549


2 | 16 bytes | 64 bytes | 256 bytes | 1024 bytes | 8192 bytes | 16384 bytes
-- | -- | -- | -- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
aes-128-gcm | 398302.29 | 394701.69 | 0.912233236 | 1011864.13 | 1016442.09 | -0.450390637 | 2047820.12 | 1883499.01 | 8.724247219 | 3284974.25 | 3240333.99 | 1.37764379 | 4079007.06 | 4073196.2 | 0.14266094 | 4152524.8 | 4157276.16 | -0.114290218
aes-256-gcm | 323353.55 | 342411.81 | -5.56588863 | 915166.25 | 952506.69 | -3.920228634 | 1716779.35 | 1682307.5 | 2.049081396 | 2526541.82 | 2424150.36 | 4.22380813 | 2945886.89 | 2937135.1 | 0.297970291 | 2980975.96 | 2965061.63 | 0.536728473
aes-128-ccm | 169426.01 | 153775.72 | 10.17734789 | 492086.4 | 446821.35 | 10.13045818 | 801970.35 | 777528.15 | 3.143577503 | 951957.85 | 945675.95 | 0.664276172 | 1006575.62 | 1005024.6 | 0.154326571 | 1010215.59 | 1005010.94 | 0.517869985
aes-256-ccm | 144300.57 | 133895.65 | 7.770917128 | 387853.57 | 367737.9 | 5.470110641 | 599544.66 | 588483.58 | 1.879590251 | 694366.21 | 691753.98 | 0.377624137 | 728536.41 | 729956.35 | -0.19452396 | 733675.52 | 732457.64 | 0.166273097
aes-128-ctr | 497576.18 | 453885.58 | 9.625906159 | 1080583.91 | 1390711.42 | -22.29991827 | 2759654.57 | 2803344.04 | -1.558476925 | 3847653.72 | 3775863.47 | 1.901293587 | 4213738.15 | 4197384.19 | 0.389622662 | 4247879.68 | 4234199.04 | 0.323098651
aes-256-ctr | 552150.99 | 397259.64 | 38.98995377 | 1523103 | 1254669.67 | 21.39474129 | 2502045.18 | 2223966.12 | 12.50374534 | 2896369.32 | 2802458.62 | 3.35101112 | 3030441.98 | 3016906.07 | 0.448668592 | 3042426.88 | 2985476.1 | 1.907594571
des cbc | 59384.01 | 59409.15 | -0.042316714 | 61014.89 | 61175.85 | -0.263110361 | 61491.29 | 58548.99 | 5.025364229 | 61720.23 | 57328.64 | 7.660377082 | 61794.99 | 60050.09 | 2.905740857 | 61827.75 | 60943.02 | 1.451733111
des ede3 | 22901.78 | 22687.1 | 0.946264617 | 23113.9 | 22959.36 | 0.673102386 | 22002.69 | 22568.02 | -2.50500487 | 23344.47 | 22693.21 | 2.869845209 | 23328.09 | 22962.18 | 1.593533367 | 23352.66 | 23003.14 | 1.519444737
sha1 | 25841.17 | 55199.8 | -53.18611662 | 136470.34 | 164087.51 | -16.83075695 | 403205.38 | 404838.31 | -0.403353625 | 624771.75 | 621857.45 | 0.468644381 | 729609.56 | 742798.68 | -1.775598201 | 653230.08 | 756307.29 | -13.62901183
sha256 | 34824.93 | 40653.22 | -14.33660114 | 94351.53 | 105234.05 | -10.34125362 | 201231.19 | 222723.41 | -9.649735517 | 299239.42 | 306622.46 | -2.407860142 | 339045.03 | 342212.61 | -0.925617557 | 341600.94 | 343900.16 | -0.668571948
sha512 | 29254.53 | 26707.87 | 9.535241859 | 115081.43 | 106331.39 | 8.229028136 | 239562.07 | 231236.01 | 3.60067621 | 352513.71 | 360028.84 | -2.08736889 | 497451.01 | 485332.31 | 2.496990155 | 512802.82 | 504064.68 | 1.733535466
aes-128 cbc | 787955.5 | 638900.04 | 23.33001263 | 977546.71 | 973314.99 | 0.434773947 | 1002305.79 | 1001278.55 | 0.10259283 | 1006477.99 | 1006779.73 | -0.029970806 | 1016037.38 | 1006149.63 | 0.982731564 | 1013721.77 | 1008102.06 | 0.55745447
aes-192 cbc | 727751.77 | 570738.18 | 27.51061616 | 827568.6 | 819239.83 | 1.016646127 | 838430.63 | 838717.35 | -0.034185533 | 842909.01 | 838650.88 | 0.50773571 | 856129.54 | 836689.92 | 2.323395984 | 856380.76 | 845212.33 | 1.32137566
aes-256 cbc | 645320.96 | 576921.13 | 11.85601054 | 701572.18 | 718890.28 | -2.409004612 | 726582.1 | 728347.48 | -0.242381562 | 731171.16 | 731488.94 | -0.043442899 | 730540.71 | 732673.37 | -0.291079229 | 725215.91 | 735046.31 | -1.337385123

**Comment by t8m** [comment]
What these numbers are supposed to mean? Are they just two separate runs against the same codebase? If so, the numbers are apparently useless as they differ wildly between the runs meaning the load on the machine, caches vs regular memory accesses, or CPU clock changes are actually causing the differences.

**Comment by mattcaswell** [comment]
Thanks @stardrift1

> What these numbers are supposed to mean? Are they just two separate runs against the same codebase?

That is my interpretation of them.

> If so, the numbers are apparently useless as they differ wildly between the runs

Yes, there do seem to be significant differences. E.g in run 2 sha1 performance on 16 bytes shows -53% performance degradation over 1.1.1 But in run 1 the difference was only -2.8%.

**Comment by stardrift1** [comment]
> Are they just two separate runs against the same codebase

yes

**Comment by t8m** [comment]
Then unfortunately those numbers are useless. You need to produce stable numbers from multiple runs. Ideally the benchmarking should be done on an idle machine that does not do CPU speed throttling.

**Comment by stardrift1** [comment]
maybe i should Calculate the average value  of my test testing data.

**Comment by stardrift1** [comment]
average   of five times testing data | 16 bytes |   |   | 64 bytes |   |   | 256 bytes |   |   | 1024 bytes |   |   | 8192 bytes |   |   | 16384 bytes |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
aes-128-gcm | 375490.042 | 362687.028 | 0.035300446 | 950388.664 | 875746.132 | 0.085233071 | 1969214.346 | 1699375.992 | 0.158786728 | 3203003.87 | 2792198.28 | 0.147126224 | 4022078.122 | 3911042.118 | 0.028390388 | 4102165.846 | 4148039.952 | -0.011059225
aes-256-gcm | 302985.458 | 298703.286 | 0.014335872 | 907915.438 | 936860.956 | -0.03089628 | 1702912.682 | 1657346.73 | 0.027493313 | 2493916.364 | 2446461.882 | 0.019397188 | 2934834.79 | 2901581.822 | 0.01146029 | 2990739.73 | 2914615.296 | 0.026118176
aes-128-ccm | 162787.156 | 148040.902 | 0.099609323 | 482646.486 | 454018.4 | 0.063054903 | 797550.028 | 776549.272 | 0.027043688 | 950563.228 | 943096.696 | 0.007917038 | 997210.522 | 1006569.61 | -0.009298004 | 1008362.018 | 1009678.198 | -0.001303564
aes-256-ccm | 244686.484 | 197538.662 | 0.238676427 | 382683.848 | 363461.734 | 0.052886211 | 598880.358 | 588223.642 | 0.018116776 | 684752.352 | 691907.514 | -0.010341212 | 717833.832 | 723234.542 | -0.007467439 | 732683.742 | 731270.35 | 0.00193279
aes-128-ctr | 587251.434 | 438907.484 | 0.337984553 | 1507214.062 | 1384006.544 | 0.089022352 | 3028225.588 | 2700944.64 | 0.121172772 | 3897299.626 | 3796696.338 | 0.026497586 | 4200670.822 | 4183471.446 | 0.004111269 | 4247622.998 | 4224098.852 | 0.005569033
aes-256-ctr | 435736.68 | 304195.63 | 0.43242255 | 1459074.54 | 1225988.01 | 0.190121378 | 2443906.046 | 2128674.254 | 0.148088319 | 2835544.884 | 2705643.996 | 0.048011079 | 3010054.28 | 3004680.874 | 0.001788345 | 3039604.464 | 3025374.416 | 0.004703566
des cbc | 51999.36 | 51355.542 | 0.012536485 | 60780.276 | 59414.22 | 0.022992072 | 61684.106 | 61003.28 | 0.011160482 | 61695.678 | 60830.174 | 0.014228202 | 61582.542 | 59209.592 | 0.040077121 | 61799.84 | 59161.532 | 0.044594991
des ede3 | 27556.382 | 28222.962 | -0.023618357 | 23059.508 | 22132.048 | 0.041905747 | 22471.298 | 22453.162 | 0.000807726 | 23104.664 | 23026.69 | 0.003386244 | 23140.76 | 23080.142 | 0.002626414 | 23046.824 | 23020.614 | 0.001138545
sha1 | 46508.344 | 52692.702 | -0.1173665 | 160303.416 | 162154.534 | -0.011415765 | 399907.414 | 387172.162 | 0.032892995 | 615482.776 | 605365.59 | 0.016712522 | 736010.788 | 735722.426 | 0.000391944 | 727490.014 | 750914.766 | -0.031194955
sha256 | 36068.97 | 37002.112 | -0.025218615 | 102676.858 | 91973.56 | 0.11637364 | 216047.122 | 214418.398 | 0.007596009 | 300932.436 | 300843.144 | 0.000296806 | 336986.658 | 332256.05 | 0.014237839 | 338184.326 | 342218.07 | -0.011787057
sha512 | 180196.77 | 85460.606 | 1.108536066 | 103732.066 | 104767.526 | -0.009883406 | 231815.288 | 231460.214 | 0.001534061 | 393902.352 | 388376.03 | 0.014229308 | 501303.98 | 498487.568 | 0.005649914 | 510288.418 | 508431.564 | 0.003652122
aes-128   cbc | 725681.906 | 629738.364 | 0.152354609 | 967097.516 | 972899.598 | -0.005963701 | 999209.524 | 1002045.528 | -0.002830215 | 990215.784 | 1006263.228 | -0.015947561 | 995898.71 | 1007940.95 | -0.011947367 | 1011171.328 | 1009713.15 | 0.001444151
aes-192   cbc | 630952.56 | 580691.712 | 0.08655341 | 821475.474 | 807878.702 | 0.016830215 | 784985.106 | 787279.53 | -0.00291437 | 836111.84 | 840015.802 | -0.004647486 | 855786.018 | 843403.538 | 0.01468156 | 853895.85 | 845876.428 | 0.009480607
aes-256   cbc | 499852.014 | 444326.366 | 0.124965909 | 694317.992 | 717103.232 | -0.031774003 | 724141.96 | 727587.16 | -0.004735103 | 728813.842 | 729878.938 | -0.001459278 | 734185.062 | 731565.806 | 0.003580342 | 727086.964 | 733698.458 | -0.009011187

**Comment by beldmit** [comment]
I think your results mean we have successfully eliminated the performance degradation. At least, the performance measurement degradation :)

**Comment by mattcaswell** [comment]
The % diff doesn't look quite right. I think (for example) 0.035300446 should be read as +3.53% in this latest table.

Most things look better. Although SHA1 still looks a little degraded at small sizes.

**Comment by stardrift1** [comment]
@mattcaswell yes,i forgot to muti 100

**Comment by beldmit** [comment]
I think it may be closed now?

**Comment by mattcaswell** [comment]
I think this has been addressed.
