### ISSUE TITLE
Is there any way to get the keys and IVs from the established tls session?

### ISSUE THREAD

**Issue by xkqian** [openssl/openssl#13419]
Before, we can get the keys and ivs in read/write client by the following procedures(take write for example):

> EVP_CIPHER_CTX * writeCtx = ssl->enc_write_ctx;
> EVP_AES_GCM_CTX* gcmWrite = (EVP_AES_GCM_CTX*)(writeCtx->cipher_data);
> unsigned char* writeKey = (unsigned char*)(gcmWrite->gcm.key);
> unsigned char* writeIV = gcmWrite->iv;

But with latesd code, it will report compiling error. 
Seems the definition of "struct ssl_ctx_st { }" is moved into the ssl_local.h. 
Is there any other APIs to replace this?

**Comment by mattcaswell** [comment]
No, we don't expose this. In fact even in 1.0.2 `EVP_AES_GCM_CTX` was not a publicly exposed type - so it looks like you are "cheating" even in your old code.

**Comment by xkqian** [comment]
Thanks for the reply.   Seems he old code is "cheating", and it's only for the application of KTLS, which need two sockets seperately for handshake and record layer. After the first socket handshake, we need expose the keys and ivs and set them to the second socket for record.   I am not sure, how can we meet this requirement, or is the latest version didn't need two sockets at all?

**Comment by mattcaswell** [comment]
Running things in this way is not currently supported in 1.1.1. OpenSSL 3.0 has full support for KTLS directly.

You might be able to do something with a custom engine to solve this problem, but that is liable to be a lot of work.

**Comment by xkqian** [comment]
Maybe we can have a try of the ways in OpenSSL 3.0. Is there any guideline how to program the ktls with 3.0 or just some simple example code? Thanks.

**Comment by mattcaswell** [comment]
You just need to build with OpenSSL with the "enable-ktls" option (see the INSTALL.md file). You must use a socket BIO. If the negotiated ciphersuite is one that is supported by the KTLS implementation then it will be automatically used transparently.

@borisPis, I was going to point @xkqian at the CHANGES entry for this feature - but it seems we don't have one. That seems like a big omission - would you like to contribute one?

**Comment by BorisPis** [comment]
We do have an entry in CHANGES for kernel TLS:
> Added support for Linux Kernel TLS data-path. The Linux Kernel data-path
   improves application performance by removing data copies and providing
   applications with zero-copy system calls such as sendfile and splice. 

OpenSSL's kernel TLS support enables applications using the *existing* API to work with the kernel TLS data-path instead of the user-space data-path. Additionally, it allows you to call the SSL_sendfile API, which will leverage the underlying kernel TLS sendfile system call.

**Comment by mattcaswell** [comment]
> We do have an entry in CHANGES for kernel TLS:

Ah! Thanks! I was searching for KTLS and coming up with nothing!!

**Comment by xkqian** [comment]
Thanks a lot @mattcaswell @BorisPis . I can find the description of kernel TLS in CHANGES.md.  I have built out the bins with "enable-ktls" option, will have a try of BIO socket. 
Is there any special about the socket type ?  say AF_INET is fine?

**Comment by BorisPis** [comment]
Yes, you may want to look at the [unit tests for ktls](https://github.com/openssl/openssl/blob/master/test/sslapitest.c#L8483)

**Comment by xkqian** [comment]
> Yes, you may want to look at the [unit tests for ktls](https://github.com/openssl/openssl/blob/master/test/sslapitest.c#L8483)

Yeah, it's quite helpfull, thank you.

**Comment by kroeckx** [comment]
Can this issue be closed?

**Comment by xkqian** [comment]
> Can this issue be closed?

Sure! Thanks to @BorisPis @mattcaswell @kroeckx  for your quick help.
