### ISSUE TITLE
Provider is not invoked by the ecparam App

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#13410]
The `openssl ecparam` tool/app (3.0.0, latest master) does not work (for me) with a Provider, it feels like the `-provider` argument is being ignored. I believe the code was not entirely migrated, e.g. it uses EC_KEY_new although (I believe) it should use EC_KEY_new_ex or EC_KEY_new_by_curve_name_ex instead with a context pointer, shouldn't it?

Even worse, at least one API feature feels missing: the `-list_curves` argument uses EC_get_builtin_curves, whereas (I believe) the curves supported by the Provider should be returned instead. I didn't find a function that could be used to provide this list.

**Comment by levitte** [comment]
This has been subject for intense debate more than once.  There's a more modern `openssl pkeyparam`, which is written with EVP_PKEY in mind, and that does handle EC among other key types.

However, we've had recent discussions on this subject, and there's currently an ongoing effort to refactor the older key type specific commands to use EVP_PKEY functionality, at least for the time being.

For EC, the effort is currently a draft PR, #13139.  Watch that space, and when the time is right, I assume @slontis would appreciate any help trying it out.

**Comment by t8m** [comment]
This is now fixed by merging #13139.
