### ISSUE TITLE
OpenSSL 3.0 does not verify the validity of the root CA certificate.

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#13427]
In 3.0  :  
internal_verify: get the root CA(X509 *xi ), When the check_issued(ctx, xi, xi) interface is invoked, the value 0 is returned, Therefore, the validity period of the root CA is not verified.

static int internal_verify(X509_STORE_CTX *ctx)
{
    int n = sk_X509_num(ctx->chain) - 1;
    X509 *xi = sk_X509_value(ctx->chain, n);
    X509 *xs;

    /*
     * With DANE-verified bare public key TA signatures, it remains only to
     * check the timestamps of the top certificate.  We report the issuer as
     * NULL, since all we have is a bare key.
     */
    if (ctx->bare_ta_signed) {
        xs = xi;
        xi = NULL;
        goto check_cert;
    }

    if (ctx->check_issued(ctx, xi, xi)) /* the last cert appears self-signed */
        xs = xi;
    else {
        if (ctx->param->flags & X509_V_FLAG_PARTIAL_CHAIN) {
            xs = xi;
            goto check_cert;
        }
        if (n <= 0)
            return verify_cb_cert(ctx, xi, 0,
                                  X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE);
        n--;
        ctx->error_depth = n;
        xs = sk_X509_value(ctx->chain, n);
    }

static int check_issued(X509_STORE_CTX *ctx, X509 *x, X509 *issuer)
{
    if (x509_likely_issued(issuer, x, ctx->libctx, ctx->propq) != X509_V_OK)
        return 0;
    if ((x->ex_flags & EXFLAG_SI) == 0 || sk_X509_num(ctx->chain) != 1) {
        int i;
        X509 *ch;

        for (i = 0; i < sk_X509_num(ctx->chain); i++) {
            ch = sk_X509_value(ctx->chain, i);
            if (ch == issuer || X509_cmp(ch, issuer) == 0)
                return 0;
        }
    }
    return 1;
}

In  1.1.1f :  get the root ca(X509 *xi ), When the check_issued(ctx, xi, xi) interface is invoked, the value 0 is returned., Therefore, the validity period of the root CA is verified.

static int check_issued(X509_STORE_CTX *ctx, X509 *x, X509 *issuer)
{
    int ret;
    if (x == issuer)
        return cert_self_signed(x);
    ret = X509_check_issued(issuer, x);
    if (ret == X509_V_OK) {
        int i;
        X509 *ch;
        /* Special case: single self signed certificate */
        if (cert_self_signed(x) && sk_X509_num(ctx->chain) == 1)
            return 1;
        for (i = 0; i < sk_X509_num(ctx->chain); i++) {
            ch = sk_X509_value(ctx->chain, i);
            if (ch == issuer || !X509_cmp(ch, issuer)) {
                ret = X509_V_ERR_PATH_LOOP;
                break;
            }
        }
    }

    return (ret == X509_V_OK);
}

If an expired root CA certificate is used, openssl1.1.1f returns a failure message, while 3.0 does not.
Is that a bug? What is the reason for this modification?

**Comment by DDvO** [comment]
@Mengliuxx, I agree that this is a bug in the sense that it was due to an unintentional loss (in commit 0e7b1383e138ce3fa66c5bd0ea4a9cb35487436c) of some (undocumented) feature.

The certificate path validation procedure specified in RFC 5280 does not include checking the validity period of the trusted (root) certificate. Still it is common good practice to perform this check. 
See also the proposed fix for OpenSSL 1.1.1 in #13585.
