### ISSUE TITLE
Compared legacy.so and libcrypto.so 

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#13423]
![image](https://user-images.githubusercontent.com/69578444/99329604-8d52b280-28b9-11eb-88f7-e061bf6f24f2.png)
 Does the algorithms of correlation function and executable file (.o) only in legacy.so？

For example, I find some executable files in legacy.a
![image](https://user-images.githubusercontent.com/69578444/99334124-a0ff1880-28bb-11eb-96be-fdccb369586f.png)
But I also find some executable files in libcrypto.a
![image](https://user-images.githubusercontent.com/69578444/99337301-f8ea4f00-28bc-11eb-8c81-f662c8b1dd4c.png)
I want to know why the two libraries have RC4 associated executable files，Why don't load in a library （legacy.a）?

**Comment by mattcaswell** [comment]
RC4 does not exist in the default provider and is instead in the legacy provider. Ciphers such as RC4-HMAC-MD5 (which is a specialist cipher used in TLS) are only accessible via this way.

It is also possible to access RC4 via deprecated APIs. The deprecated APIs use the underlying algorithm implementation directly and do not go via the provider infrastructure. For this reason libcrypto *also* contains the RC4 implementation. This is required for backwards compatibility reasons.

**Comment by levitte** [comment]
> This is required for backwards compatibility reasons.

When they are removed, in a few years time, files like `libcrypto-lib-rc4_enc.o` will simply not appear any more.

**Comment by 1185129439** [comment]
> It is also possible to access RC4 via deprecated APIs. The deprecated APIs use the underlying algorithm implementation directly and do not go via the provider infrastructure. For this reason libcrypto _also_ contains the RC4 implementation. This is required for backwards compatibility reasons.

Thanks，I think  RC4  still can use by legacy provider,  is right?
