### ISSUE TITLE
What is the purpose of designing this interface：void X509_VERIFY_PARAM_set_time(X509_VERIFY_PARAM *param, time_t t);

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#13428]
when set this time,how to  ensure the accuracy of certificate verification?I think there may be some delay here between set the time and use this time to check cert or crl's time.

**Comment by kaduk** [comment]
> when this is set

If you call this function, you accept responsibility for ensuring that the time you pass is the time you want to use during verification.  If you don't call this API, the current time is used.

Most places doing X.509 validation should not call this function.

**Comment by stardrift1** [comment]
ok,thanks
