### ISSUE TITLE
EVP_PKEY_CTX_set_signature_md() behavior discrepency for ECDSA relative to DSA & RSA

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#13422]
For 3.0.0, sometime between alpha6 & alpha7 EVP_PKEY_CTX_set_signature_md() began to fail within the FIPS provider for DSA & RSA if SHA1 was passed in along with an EVP_PKEY_CTX set up for signing (ie, EVP_PKEY_sign_init() had been called). That's fine, this is actually what I expect.

The code paths in master responsible are very similar. We track (d|r)sa_set_ctx_params() to (d|r)sa_setup_md(), and we see a call to digest_get_approved_nid_with_sha1() which passes along the sha1_allowed parameter as "true" iff the operation isn't signing. Straight-forward enough, I suppose.

However, ECDSA doesn't seem to follow this model. ecdsa_set_ctx_params() doesn't appear to do any checks on the digest for OSSL_SIGNATURE_PARAM_DIGEST, which differs from RSA & DSA. I see some calls to digest_get_approved_nid_with_sha1() elsewhere within providers/implementations/signature/ecdsa.c, so it seems like there is some kind of intent to impose the same general rules for ECDSA. For this reason I am inclined to believe that it's simply a missing check.

That being said, I am certainly not an expert on the FIPS rules or the provider implementation code. If this discrepancy in behavior is in fact intentional I could certainly be mollified by an explanation of why this is the case.

**Comment by levitte** [comment]
Oh my...  this doesn't have much to do with FIPS or not FIPS, I suspect that you get the same results with the default provider.

Basically, the md passed with `EVP_PKEY_CTX_set_signature_md()` ends up being ignored, indeed.  It seems like or provided ECDSA implementation will only care about the name of the EVP_MD passed with EVP_DigestSignInit() and related calls.

**Comment by slontis** [comment]
Yep there was some weird comment in there saying that it doesn't use the set param. I am updating it to resemble code used in dsa.
