### ISSUE TITLE
unable to establish secure connection with Kernel TLS enabled

### ISSUE THREAD

**Issue by junjunk** [openssl/openssl#13430]
This is another bug found after #12082 
The returned error is unexpected end of file while handshake. The error is because `readsock()` returns 0 in `sock_read()` after `setsockopt()` is called.
Again looks like kernel bug, [patch](https://patchwork.kernel.org/project/netdevbpf/patch/1605440628-1283-1-git-send-email-vfedorenko@novek.ru/) is on review.
The bug is for history terms, could be closed

**Comment by kaduk** [comment]
I'll go ahead and close this, per what I understand the intent of:

> The bug is for history terms, could be closed

to be.  Please reopen if I am misunderstanding, and thank you for giving us this placeholder issue report even though the fix is in the kernel!
