### ISSUE TITLE
ivec is updated two times, detecting ctr overflow in GmSSL/crypto/modes/ctr128.c @ line 186

### ISSUE THREAD

**Issue by gongfna** [openssl/openssl#13433]

**Comment by gongfna** [comment]
I think the correct code is :
if (ctr32 == 0) {
    ctr96_inc(ivec);
} else {
    /* (*ctr) does not update ivec, caller does: */
    PUTU32(ivec + 12, ctr32);
}

**Comment by levitte** [comment]
If this is indeed a bug in GmSSL, then you might want to talk with [GmSSL](https://github.com/guanzhi/GmSSL)...

**Comment by paulidale** [comment]
I'm pretty sure the code is correct as written.  ctr32 is the low 32 bits of the 128 bit counter.  ctr96_inc() is incrementing the upper 96 bits on overflow.

**Comment by gongfna** [comment]
If the whole 128bit is counter，the code is correct. I think CRYPTO_ctr128_encrypt_ctr32 means the counter is 32bit.

**Comment by levitte** [comment]
It isn't, it's still a 128bit counter.  However, `CRYPTO_ctr128_encrypt` is more suitable with callbacks that only handle one block at a time, while `CRYPTO_ctr128_encrypt_ctr32` is more suitable for callbacks that can handle multiple blocks.  There are other nuances as well (like `CRYPTO_ctr128_encrypt_ctr32` is more suitable for stream ciphers callbacks), but I forget.

**Comment by gongfna** [comment]
OK I got it. Many thanks
