### ISSUE TITLE
OSSL_PARAM_utf8_ptr() API is confusing

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#13446]
This is a split of #11162

The OSSL_PARAM_utf8_ptr() is a macro, not a function.

The code you need to write with the macro is:
char *foo;
OSSL_PARAM_utf8_ptr(foo);

And the macro will modify the value of foo. That is, the pointer will change.

Normally when a value can be modified, you need pass a pointer to that variable, so:
char *foo;
OSSL_PARAM_utf8_ptr(&foo);

But because OSSL_PARAM_utf8_ptr() is a macro, it can modify the variable without having to take a pointer.

**Comment by levitte** [comment]
You're right that it does look odd, at least now in retrospect.  I cannot for the life of me remember why it was done that way...  I do recall some argument around some of those macros, but details escape me.

This is pretty easy to fix, though.

**Comment by t-j-h** [comment]
The same comments apply to OSSL_PARAM_octet_ptr

**Comment by levitte** [comment]
> The same comments apply to OSSL_PARAM_octet_ptr

Agreed.
