### ISSUE TITLE
libssl-shlib-ssl_lib.obj : error LNK2001: unresolved external symbol _SSLerr

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#13449]
With one of the latest commits, building libssl fails on Windows with this error:
libssl-shlib-ssl_lib.obj : error LNK2001: unresolved external symbol _SSLerr

I think it's caused by the no-deprecated configure option, because then the SSLerr macro is not defined. The SSLerr calls here must be replaced with ERR_raise_data(ERR_LIB_SSL, (r), NULL):
https://github.com/openssl/openssl/blob/master/ssl/ssl_lib.c#L5963
etc

**Comment by levitte** [comment]
Fix in #13450.  Thanks
