### ISSUE TITLE
Duplicate code exists for the default provider and legacy APIs

### ISSUE THREAD

**Issue by yxungh** [openssl/openssl#13451]
Hi, I have a question.
The provider mechanism is added to OpenSSL 3.0. Is the algorithm implementation in the default provider new code or reuses the previous algorithm implementation? Why is the code duplicate with the legacy API?

**Comment by levitte** [comment]
> Why is the code duplicate with the legacy API?

Backward compatibility.  See https://www.openssl.org/blog/blog/2019/02/13/FIPS-update/, where we say, among others:

> Of course support will be maintained for existing APIs so applications don’t need to use the new APIs if they don’t want to.

We do and continue to deprecate the old APIs, which means they will be removed at some point in the future.  However, this does allow existing applications to transition to the new OpenSSL without having to be rewritten too much in one go.

**Comment by paulidale** [comment]
We're reusing old code.  There is no duplication, the default provider is linked with libcrypto.

**Comment by yxungh** [comment]
@levitte 
> We do and continue to deprecate the old APIs, which means they will be removed at some point in the future. However, this does allow existing applications to transition to the new OpenSSL without having to be rewritten too much in one go.

Can I understand that the old APIs are retained at the current stage, and the old and new sets of code exist at the same time during the development of new provider code?
Will the old APIs be completely removed in a later version?

**Comment by mattcaswell** [comment]
> Can I understand that the old APIs are retained at the current stage, and the old and new sets of code exist at the same time during the development of new provider code?

Yes, the old APIs are retained and exist at the same time as the newer EVP alternatives. In fact this has been the case for a long time (way before OpenSSL 3.0). The provider code is mainly a restructuring of how the EVP APIs work. There are some new EVP functions, but a lot of the API functions existed even in older versions of OpenSSL.

> Will the old APIs be completely removed in a later version?

Yes. They are all deprecated with an intention that they will be eventually removed.

**Comment by richsalz** [comment]
I took the question to be why is the same code in default and FIPS providers.  If I'm correct, it wasn't answered.

**Comment by yxungh** [comment]
> We're reusing old code. There is no duplication, the default provider is linked with libcrypto.

During reconstruction, whether some functions are duplicated?
At least the alpha phase

**Comment by yxungh** [comment]
@richsalz 
> I took the question to be why is the same code in default and FIPS providers. If I'm correct, it wasn't answered.

I want to understand the relationship between the default provider and legacy APIs because they are build_in.

**Comment by yxungh** [comment]
@mattcaswell 
> Yes. They are all deprecated with an intention that they will be eventually removed.

I can take this as a change point of OpenSSL 3.0, which means that users need to replace all old APIs.

**Comment by mattcaswell** [comment]
> I can take this as a change point of OpenSSL 3.0, which means that users need to replace all old APIs.

Ideally, yes - you should replace all use of the old APIs if possible.

**Comment by yxungh** [comment]
> > I can take this as a change point of OpenSSL 3.0, which means that users need to replace all old APIs.
> 
> Ideally, yes - you should replace all use of the old APIs if possible.

Does it not exist or not allow external use? I understand that they are used to encapsulate new Envision Video Platform interfaces. Is there any way I can keep using them?

**Comment by mattcaswell** [comment]
> Does it not exist or not allow external use?

The old APIs still exist and you *may* continue to use them. It is recommended to replace them because they will eventually be removed - but you don't *have* to. It will be some while before a release that actually removes them comes along. If you do use the deprecated APIs then you may see compilation warnings saying that the functions have been deprecated.

**Comment by t8m** [comment]
I believe all the questions were answered. Closing the issue.
