### ISSUE TITLE
Does openssl client choose ca certificates base on certificate_authorities field in Certificate Request 

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#13453]
Hi,
   From RFC5246   https://tools.ietf.org/html/rfc5246#section-7.4.4:
   It describes certificate_authorities  in Certificate Request message as below:  

>    certificate_authorities: 
>       A list of the distinguished names [X501] of acceptable
>       certificate_authorities, represented in DER-encoded format.  These
>       distinguished names may specify a desired distinguished name for a
>       root CA or for a subordinate CA; thus, this message can be used to
>       describe known roots as well as a desired authorization space.

  I want to know if openssl client use this field to choose CA certificate?

**Comment by mattcaswell** [comment]
> I want to know if openssl client use this field to choose CA certificate?

No, it doesn't. There is very limited support for this extension:

- It is *only* supported in TLSv1.3
- An application may query what was sent from the peer in the extension using the API function `SSL_get0_peer_CA_list()`
- An application could write a certificate callback that selects an appropriate certificate to be used based on the return value from the  above function, e.g. see `SSL_CTX_set_cert_cb()`
- It is also possible to configure OpenSSL to reject the currently set certificate before it is sent if it doesn't meet the CA names criteria. But in this case it doesn't select an alternative instead so is probably not what you want.

**Comment by joymcg** [comment]
> > I want to know if openssl client use this field to choose CA certificate?
> 
> No, it doesn't. There is very limited support for this extension:
> 
> * It is _only_ supported in TLSv1.3
> * An application may query what was sent from the peer in the extension using the API function `SSL_get0_peer_CA_list()`
> * An application could write a certificate callback that selects an appropriate certificate to be used based on the return value from the  above function, e.g. see `SSL_CTX_set_cert_cb()`
> * It is also possible to configure OpenSSL to reject the currently set certificate before it is sent if it doesn't meet the CA names criteria. But in this case it doesn't select an alternative instead so is probably not what you want.

Thanks for the reply,  so if I want to choose CA cert base on peer_ca_names, I must implement the select function myself?

**Comment by mattcaswell** [comment]
> Thanks for the reply, so if I want to choose CA cert base on peer_ca_names, I must implement the select function myself?

Yes

**Comment by joymcg** [comment]
> > Thanks for the reply, so if I want to choose CA cert base on peer_ca_names, I must implement the select function myself?
> 
> Yes

Thanks
