### ISSUE TITLE
openssl_3.0.0 : if sys undefined AF_INET6, apps will  failed  

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#13482]
https://github.com/openssl/openssl/blob/948fd7af627f42cf9ab6b7c3df34aa5ebad422ae/apps/lib/s_socket.c#L169
https://github.com/openssl/openssl/blob/948fd7af627f42cf9ab6b7c3df34aa5ebad422ae/apps/lib/s_socket.c#L251-L258

should these code be used  ```#ifdef AF_INET6"?

**Comment by levitte** [comment]
Fix in #13484.  Thank you
