### ISSUE TITLE
Openssl not building with JOM on Windows for build 1.1.1g and build 1.1.1h, it was working till build 1.1.1f

### ISSUE THREAD

**Issue by ganeshkamath89** [openssl/openssl#13481]
I was using JOM command on Windows to build Openssl till version 1.1.1f. Recently I migrated my project to 1.1.1g and found that it was failing with error.

I was recommended to use JOM build in OpenSSL github forum itself. 
link: https://github.com/openssl/openssl/issues/9931

nmake builds are still working.

**Comment by kroeckx** [comment]
What error do you get when building?
