### ISSUE TITLE
The propq in X509_new_ex (and x509_set0_libctx) is not duplicated

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#13486]
The propq argument in X509_new_ex (and x509_set0_libctx) is not duplicated but it should be to ensure consistency with how other _new_ex functions handle the property query.

Fixing this requires also fixing it in #12687.

**Comment by slontis** [comment]
There was already a PR for this which was waiting on #12687 (which is now merged).
Fixing it up now so that it links to here..
