### ISSUE TITLE
how to use AES Key Wrap inverse ciphers in the EVP layer

### ISSUE THREAD

**Issue by odingo** [openssl/openssl#13483]
I know the AES Key Wrap inverse ciphers function is supported in EVP layer by reading CHANGES.md

> * Add support for AES Key Wrap inverse ciphers to the EVP layer.
   The algorithms are:
   "AES-128-WRAP-INV", "AES-192-WRAP-INV", "AES-256-WRAP-INV",
   "AES-128-WRAP-PAD-INV", "AES-192-WRAP-PAD-INV" and "AES-256-WRAP-PAD-INV".
   The inverse ciphers use AES decryption for wrapping, and
   AES encryption for unwrapping.
>
>   *Shane Lontis*

I'm using `EVP_aes_128_wrap` in my code, but do not know how to set the inverse cipher function in the below code.
Can you help me on this?

````
int wrap(unsigned char *pad_mode, //w/wo pad 
            unsigned char *plaintext, int plaintext_len, unsigned char *key,
            unsigned char *iv, unsigned char *ciphertext)
{
    EVP_CIPHER_CTX *ctx;
    const EVP_CIPHER *(*f2aes)(void);
    int len;
    int ciphertext_len;

    printf("[%s:WRAP]\n", pad_mode);
    if(strcmp(pad_mode, KW128) == 0) f2aes = EVP_aes_128_wrap;
    else if(strcmp(pad_mode, KW256) == 0) f2aes = EVP_aes_256_wrap;
    else if(strcmp(pad_mode, KWP128) == 0) f2aes = EVP_aes_128_wrap_pad;
    else if(strcmp(pad_mode, KWP256) == 0) f2aes = EVP_aes_256_wrap_pad;
    else handleErrors(__LINE__);

    if(!(ctx = EVP_CIPHER_CTX_new()))
        handleErrors(__LINE__);

    EVP_CIPHER_CTX_set_flags(ctx, EVP_CIPHER_CTX_FLAG_WRAP_ALLOW);

    if(1 != EVP_EncryptInit_ex(ctx, f2aes(), NULL, key, iv))
        handleErrors(__LINE__);

    if(1 != EVP_EncryptUpdate(ctx, ciphertext, &len, plaintext, plaintext_len))
        handleErrors(__LINE__);
    ciphertext_len = len;

    if(1 != EVP_EncryptFinal_ex(ctx, ciphertext + len, &len))
        handleErrors(__LINE__);
    ciphertext_len += len;

    EVP_CIPHER_CTX_free(ctx);

    return ciphertext_len;
}
````

**Comment by odingo** [comment]
I noticed there's a member of structure EVP_CIPHER_CTX {aka evp_cipher_ctx_st} named encrypt, is this member used to select the inverse cipher function?
And the inverse cipher function is only supported by openssl 3.0?

**Comment by mattcaswell** [comment]
The AES Key Wrap inverse ciphers are only supported in OpenSSL 3.0, and only in the latest alpha release (alpha 8).

To use them you need to "fetch" an implementation using the `EVP_CIPHER_fetch` function. See the [OpenSSL 3.0 wiki page](https://wiki.openssl.org/index.php/OpenSSL_3.0) for information about algorithm fetching. For example:

````
EVP_CIPHER *ciph = EVP_CIPHER_fetch(NULL, "AES-128-WRAP-INV", NULL);

/* Do stuff with ciph */

EVP_CIPHER_free(ciph);
````

**Comment by odingo** [comment]
Get it, thank you.
As I'm using openssl 1.x, I cannot use this new fetch method. But still thank you.
