### ISSUE TITLE
Issues in cmp_cli_test

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13494]
The cmp_cli_test seems to fail in the minimal Github CI build:

https://github.com/openssl/openssl/pull/13489/checks?check_run_id=1443890824

There seems to be at least 2 problems. This code in the cmp app looks very suspect:

https://github.com/openssl/openssl/blob/9524a3089c0d4c3ae553e86f877eef9d6b192b20/apps/cmp.c#L2699-L2707

To start with `ui_fallback_method` does not seem to be used for anything beyond this block. Secondly the `UI_method_set_reader()` function call seems to be modifying the built-in OpenSSL method directly. This works for `UI_OpenSSL()` which is not declared `const` (perhaps it should be?), but not for `UI_null()` which *is* declared const. This latter problem results in a seg-fault.

A second issue is that in the minimal build we have `no-des` specified. Unfortunately there is a key used in the test that seems to be encrypted with DES, and hence this fails.

**Comment by mattcaswell** [comment]
@DDvO - thoughts?

**Comment by DDvO** [comment]
> @DDvO - thoughts?

It turns out that in case `OPENSSL_NO_UI_CONSOLE` using `UI_null()` was not really needed.
Moreover, `81-test_cmp_cli_data/Mock/signer.p12` was still encrypted using DES; changed this to AES-256-CBC.
This apparently was all to fix cmp_cli_test.

Fixed by #13497.
