### ISSUE TITLE
Extra arguments given. rand: Use -help for summary. 

### ISSUE THREAD

**Issue by MUHAMMAD0KASHIF** [openssl/openssl#13492]
I am trying  to run following command it is working fine with the  OpenSSL 1.0.2k-fips  26 Jan 2017 but unable to run with 
  OpenSSL 1.1.1c FIPS  28 May 2019.
**Command**
/usr/bin/openssl rand -base64 32 -rand private.pem > temp.bin
**Message**
Extra arguments given.
rand: Use -help for summary.

**Comment by mattcaswell** [comment]
The argument parser became stricter in 1.1.1. If you run the "-help" as suggested by the text above you will see that the syntax for the command is:

````
Usage: rand [flags] num
Valid options are:
 -help               Display this summary
 -out outfile        Output file
 -rand val           Load the file(s) into the random number generator
 -writerand outfile  Write random data to the specified file
 -base64             Base64 encode output
 -hex                Hex encode output
 -engine val         Use engine, possibly a hardware device
````
Note that the number of bytes appears *after* any options.

In 1.0.2, the help text says something very similar, but it actually tolerates the number of bytes appearing earlier in the argument list. 1.1.1 no longer tolerates it.

So to fix the issue you should ensure that "32" is the last argument, i.e.

````
/usr/bin/openssl rand -base64 -rand private.pem 32 > temp.bin
````
