### ISSUE TITLE
How to get OpenSSL function trace via cmd line?

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#13509]
Any command line option available to get the function call hierarchy when a particular operation is performed via command line?

If not, any other alternative?

**Comment by levitte** [comment]
The most consistent is to run it in the debugger, set a breakpoint at the function that performs the operation, and look at the call stack then.

**Comment by saddy-muchu** [comment]
For this, i would need to re-compile OpenSSL with debug symbols.

**Comment by mattcaswell** [comment]
> For this, i would need to re-compile OpenSSL with debug symbols.

Correct.

**Comment by saddy-muchu** [comment]
Ok, i will give it a try.
Thanks
