### ISSUE TITLE
Cannot create DH private key without public value when using OSSL_PARAMs

### ISSUE THREAD

**Issue by jon-oracle** [openssl/openssl#13506]
This is an issue I've run into using the latest 3.0. Previously I've used the now deprecated low-level DH APIs where it was possible to set the private value only using:

`
DH_set0_key(dh, NULL, priv);
`

With the OSSL_PARAMs you'd need to call EVP_PKEY_fromdata with the OSSL_PKEY_PARAM_PRIV_KEY, which ends up calling dh_key_fromdata(). This fails as it also requires the public value as stated in the comment:

```
    /*
     * DH documentation says that a public key must be present if a
     * private key is present.
     * We want to have at least a public key either way, so we end up
     * requiring it unconditionally.
     */
```

For my current application I'm not always able to access the public value so this is a breaking change. Could you consider modifying the behaviour or adding another way to set the private value only?

**Comment by levitte** [comment]
Oh whoopsie, this is exactly the same sort of issue as in #12612, another spot where we have allowed a break of the "EVP_PKEY promise".  @romen, I think you need to see this.

**Comment by jon-oracle** [comment]
Yeah it seems as though this should be allowed, if only for compatibility with other toolkits/applications. The Java JCE crypto API has a DHPrivateKeySpec object used to create a DH private key, which only includes the P, G and X (private) values. (https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/crypto/spec/DHPrivateKeySpec.html).

**Comment by romen** [comment]
@levitte, I agree this seems like another instance of the same problem.

**Comment by jon-oracle** [comment]
FYI also affecting DSA via dsa_key_fromdata() in from crypto/dsa/dsa_backend.c.

**Comment by levitte** [comment]
`DSA_set0_key()` tried to ensure there was a public key, though...

**Comment by paulidale** [comment]
OTC vote required to expand the scope of the earlier vote about EC keys.

**Comment by paulidale** [comment]
Suggestion is to allow public key generation (where possible) but to not enable it by default.
Possible ways to enable: configuration or API.

**Comment by paulidale** [comment]
Ed keys require public key to be present for signing, others don't.

**Comment by levitte** [comment]
Since this issue was raised, the stance on what's required for a "valid" EVP_PKEY has changed.  That means that the import of DH keys into our providers need to change to accept a private key without the public bits.

**Comment by levitte** [comment]
For reference: 68e91251826949430270edfbf6dd5f334eb4df57

**Comment by jon-oracle** [comment]
> For reference: [68e9125](https://github.com/openssl/openssl/commit/68e91251826949430270edfbf6dd5f334eb4df57)

Thanks. Added a pull request, tested locally.

**Comment by slontis** [comment]
Jon - Can this be closed now?

**Comment by jon-oracle** [comment]
@slontis sure, thanks!
