### ISSUE TITLE
 why  SSL3_BUFFER_get_left(wb) != 0  when DTLSv1_2 SSL_write fail ?

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#13518]
```
#0  0xf7fd9ed9 in __kernel_vsyscall ()
#1  0xf6e64937 in raise () from /lib/libc.so.6
#2  0xf6e660b5 in abort () from /lib/libc.so.6
#3  0x59caed83 in OPENSSL_die (message=0x5aa74ae8 "Assertion failed: SSL3_BUFFER_get_left(wb) == 0", file=0x5aa74a54 "../ssl/record/rec_layer_d1.c", line=814) at ../crypto/cryptlib.c:421
#4  0x59c0fca1 in ossl_assert_int (expr=0, exprstr=0x5aa74ae8 "Assertion failed: SSL3_BUFFER_get_left(wb) == 0", file=0x5aa74a54 "../ssl/record/rec_layer_d1.c", line=814)
    at ../include/internal/cryptlib.h:35
#5  0x59c11626 in do_dtls1_write (s=0xdbca28a4, type=23, buf=0xdc7ab5b4 "", len=93, create_empty_fragment=0, written=0xd57a0d14) at ../ssl/record/rec_layer_d1.c:814
#6  0x59c1155d in dtls1_write_bytes (s=0xdbca28a4, type=23, buf=0xdc7ab5b4, len=93, written=0xd57a0d14) at ../ssl/record/rec_layer_d1.c:793
#7  0x59c7bacb in dtls1_write_app_data_bytes (s=0xdbca28a4, type=23, buf_=0xdc7ab5b4, len=93, written=0xd57a0d14) at ../ssl/d1_msg.c:33
#8  0x59c2056d in ssl3_write (s=0xdbca28a4, buf=0xdc7ab5b4, len=93, written=0xd57a0d14) at ../ssl/s3_lib.c:4471
#9  0x59c30625 in ssl_write_internal (s=0xdbca28a4, buf=0xdc7ab5b4, num=93, written=0xd57a0d14) at ../ssl/ssl_lib.c:1966
#10 0x59c306be in SSL_write (s=0xdbca28a4, buf=0xdc7ab5b4, num=93) at ../ssl/ssl_lib.c:1980
```
https://github.com/openssl/openssl/blob/2d840893e78253bcce428603fdbcda159bdebe08/ssl/record/rec_layer_d1.c#L804-L809

https://github.com/openssl/openssl/blob/2d840893e78253bcce428603fdbcda159bdebe08/ssl/record/rec_layer_s3.c#L1199-L1226
First, I look at ssl/record/rec_layer_s3.c:1210 and 1223,```SSL3_BUFFER_set_left(&wb[currbuf], 0)```.
No matter whether success or failure is returned at SSL_write, ```SSL3_BUFFER_get_left(wb)  == 0```.
Then, What kind of scene? openssl/ssl/record/rec_layer_d1.c:807 lines of code are executed?

**Comment by mattcaswell** [comment]
Which version of OpenSSL did you see this behaviour in?

**Comment by mattcaswell** [comment]
Looking at the code in master, I just can't see a route through the code that would end up triggering this assertion. So, its a bit of a mystery at the moment. If you let me know the specific version you are using then I can check that version.

Can you easily reproduce this issue?

**Comment by yangyangtiantianlonglong** [comment]
I got the call stack in openssl-1.1.1f， and found that the code openssl-1.1.1f is the same as openssl-3.0.0. I do not understand it that stack had  fail.

**Comment by yangyangtiantianlonglong** [comment]
I realize that this stack may be caused by SSL_write in multi threads, SSL_write do not have mutex. If it is a single thread, will the code （```openssl/ssl/record/rec_layer_d1.c:807```） not  go?

**Comment by mattcaswell** [comment]
Ah! An SSL object must *not* be shared across multiple threads. So, it is fine to call SSL_write in different threads - but each thread must be using a different SSL object (or you must implement appropriate locking to prevent concurrent access to the same SSL object).

> If it is a single thread, will the code （openssl/ssl/record/rec_layer_d1.c:807） not go? What is the purpose of adding this code?

Right - in a single threaded application that assertion should never fail. So the code is a sanity check.

**Comment by yangyangtiantianlonglong** [comment]
Thank you！
