### ISSUE TITLE
Compared with openssl1.1.1f and openssl3.0, the performance in aes-cbc mode deteriorates significantly.

### ISSUE THREAD

**Issue by yxungh** [openssl/openssl#13516]
I tested it five times, and it's probably the same.
One of the results

`Algorithm: aes-128-cbc`
`Doing aes-128 cbc for 3s on 16 size blocks: 25156911 aes-128 cbc's in 2.98s`
`Doing aes-128 cbc for 3s on 64 size blocks: 4754871 aes-128 cbc's in 2.98s`
`Doing aes-128 cbc for 3s on 256 size blocks: 1219704 aes-128 cbc's in 3.00s`
`Doing aes-128 cbc for 3s on 1024 size blocks: 393419 aes-128 cbc's in 2.99s`
`Doing aes-128 cbc for 3s on 8192 size blocks: 66722 aes-128 cbc's in 2.99s`
`Doing aes-128 cbc for 3s on 16384 size blocks: 33282 aes-128 cbc's in 3.00s`
`OpenSSL 1.1.1f  31 Mar 2020`
`built on: Mon Aug 17 03:20:00 2020 UTC`
`options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) `
`compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -``DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -``DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -``DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG`
													  
`The 'numbers' are in 1000s of bytes per second processed.`
`type                 16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes`
`aes-128 cbc     135070.66k   102118.03k   104081.41k   134736.14k   182804.89k   181764.10k`

`Algorithm: aes-128-cbc`
`Doing aes-128 cbc for 3s on 16 size blocks: 12263915 aes-128 cbc's in 2.99s`
`Doing aes-128 cbc for 3s on 64 size blocks: 3402683 aes-128 cbc's in 3.00s`
`Doing aes-128 cbc for 3s on 256 size blocks: 866258 aes-128 cbc's in 3.00s`
`Doing aes-128 cbc for 3s on 1024 size blocks: 356685 aes-128 cbc's in 3.00s`
`Doing aes-128 cbc for 3s on 8192 size blocks: 41133 aes-128 cbc's in 2.99s`
`Doing aes-128 cbc for 3s on 16384 size blocks: 22014 aes-128 cbc's in 3.00s`
`version: 3.0.0-alpha5`
`built on: built on: Tue Nov 10 09:53:13 2020 UTC`
`options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) `
`compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -``DOPENSSL_BUILDING_OPENSSL -DNDEBUG`
`CPUINFO: OPENSSL_ia32cap=0xfffa32035f8bffff:0xd19e4fbb`

`The 'numbers' are in 1000s of bytes per second processed.`
`type                  16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes`
`aes-128 cbc      65626.30k    72590.57k    73920.68k   121748.48k   112696.17k   120225.79k`

aes-128-cbc aes-192-cbc aes-256-cbc results are consistent, with a 40% decrease.

Is there any change in the implementation of 3.0? What causes performance deterioration?

**Comment by yxungh** [comment]
I'm using  
 `openssl speed -evp ***`

**Comment by kroeckx** [comment]
This looks like #13407

**Comment by yxungh** [comment]
It's my fault.
I'm using
`openssl speed ***`  -evp is not added to the AES-CBC test.
After -evp is added:


                      3.0-alpha8      1.1.1f         Diff(3.0-1.1.1f)/1.1.1f*100
aes-128 cbc | 628286.76 | 619126.41 | 1.479560531
aes-192 cbc | 575800.76 | 564676.61 | 1.970003681
aes-256 cbc | 531641.31 | 524854.07 | 1.29316707

**Comment by richsalz** [comment]
I suggest closing this as a dup of #13407.  Also, @beldmit and @mattcaswell  is this "fixed" by the recent speed changes?

**Comment by beldmit** [comment]
I didn't see the performance degradation for the aes-cbc but expect it should be fixed

**Comment by yxungh** [comment]
Thanks!
