### ISSUE TITLE
The cmp app modifies the global UI_OpenSSL() UI_METHOD

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13511]
https://github.com/openssl/openssl/blob/931d5b4b27fcc907e3ff4d4328c59a5f285a44fb/apps/cmp.c#L2700-L2705

In the above code we modify the global UI_OpenSSL() method. This doesn't sound like a great idea. Probably we should take a copy of it first and then use the modified version.

**Comment by levitte** [comment]
No, that's not a good idea.  Fix in #13512
