### ISSUE TITLE
`no-dsa`  build error

### ISSUE THREAD

**Issue by aggat** [openssl/openssl#13529]
`./Configure no-dsa mingw64 ` 
link error:
```
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: apps/openssl-bin-dhparam.obj:dhparam.c:(.text+0x7a9): undefined reference to 'EVP_PKEY_CTX_set_dsa_paramgen_bits'
collect2.exe: error: ld returned 1 exit status
```

**Comment by levitte** [comment]
Note:

Of course, when `no-dsa` is configured, internal implementations are disabled.  However, the EVP_PKEY_CTX functions aren't among them, and even though our own implementation may be absent, `EVP_PKEY_CTX_set_dsa_paramgen_bits()` is still useful when there's *another* provider (or by all means, engine, so this isn't a new problem) implementing DSA.

This might turn out to be a larger issue, where we need to review when we make certain EVP_PKEY_CTX functions accessible or not.

**Comment by mattcaswell** [comment]
It is strange that functions like `EVP_PKEY_CTX_set_dsa_paramgen_bits` are declared in dsa.h. You might have expected them to be in evp.h

**Comment by levitte** [comment]
That's a different question.  We have had other headers that declare EVP stuff related to that particular type of object.  See for example kdf.h.  It's not entirely unreasonable to organise things that way, rather that piling *everything* into one header file (that makes for an overwhelming read)

But I agree, we have to competing organizations of this kind of stuff, which I believe has grown organically over time.  At some point, we might want to decide on one organization and stick to it.  I don't think that decision and reorganization should be done now, or even for 3.0, but is a cleanup item for later.

**Comment by levitte** [comment]
... and let's not side track this issue too much, eh?

**Comment by mattcaswell** [comment]
> But I agree, we have to competing organizations of this kind of stuff, which I believe has grown organically over time. At some point, we might want to decide on one organization and stick to it. I don't think that decision and reorganization should be done now, or even for 3.0, but is a cleanup item for later.

Agreed. Although it is kind of relevant because at the moment the whole of the dsa.h header is disabled in the event of no-dsa via a OPENSSL_NO_DSA guard - which is why we get this error.

**Comment by levitte** [comment]
> Although it is kind of relevant because at the moment the whole of the dsa.h header is disabled in the event of no-dsa via a OPENSSL_NO_DSA guard - which is why we get this error.

That's not very hard to deal with, it's just a handful of lines to shuffle around and a misplaced __cplusplus to adjust

**Comment by levitte** [comment]
Fixed in #13530

**Comment by richsalz** [comment]
You have to treat ```no-dsa``` ```no-rsa``` etc as meaning "Not supported by this build of OpenSSL"  Anything else will be confusing and partial. For example, the implemented algorithms would not work in TLS.

**Comment by mattcaswell** [comment]
> You have to treat no-dsa no-rsa etc as meaning "Not supported by this build of OpenSSL" Anything else will be confusing and partial. For example, the implemented algorithms would not work in TLS.

I totally disagree. "no-dsa" means the DSA algorithm implementation is not present. If a DSA algorithm implementation becomes available via a third party provider there is no reason not to use it.

**Comment by richsalz** [comment]
And how do you plan to do that?  There are lots of ifdef's in the table in s3_lib, ssl_ciph, etc. You can fix that in a future release.  Right now, it effectively means "not supported by this config"  Just like no-ktls means not supported, or any other extension (ocsp, psk etc)  I can see how "no-dsa" etc means no implementation of the crypto code in the default provider, but then how do people say "no ARIA even if provided somewhere else?"

**Comment by t8m** [comment]
With the provider concept there is no such thing as disabling a particular algorithm during build time _including the provider support_. You can support algorithms completely unknown to OpenSSL via providers.

**Comment by levitte** [comment]
> And how do you plan to do that? There are lots of ifdef's in the table in s3_lib, ssl_ciph, etc.

We change the code to use EVP functionality, and *remove those guards*.  @mattcaswell has already done this quite a bit recently, if I'm not mistaken.

> You can fix that in a future release. Right now, it effectively means "not supported by this config" Just like no-ktls means not supported, or any other extension (ocsp, psk etc)

Right, so when those features are disabled, then we don't have an implementation for them.  That doesn't mean TLS stops working altogether.

> I can see how "no-dsa" etc means no implementation of the crypto code in the default provider, but then how do people say "no ARIA even if provided somewhere else?"

There's no way for them to say such a thing, just as there is no way for them to say "no DSA even if provided somewhere else".  If an engine or a provider supplies DSA (or ARIA), then it's going to be used.  If that's undesirable, *do not use that engine or provider*, it's as simple as that.

**Comment by richsalz** [comment]
Okay, I've made my point. Removing the compile-time guards means the ClientHello and ServerHello messages will be computed at run-time?

**Comment by mattcaswell** [comment]
> Okay, I've made my point. Removing the compile-time guards means the ClientHello and ServerHello messages will be computed at run-time?

For most things they already are. There's a few things left where we have hard coded defaults which we need to fix, e.g. see #13184
