### ISSUE TITLE
Calling EVP_PKEY_get_bn_param() on a legacy key does not work

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13528]
For example if you have a DH legacy key stored in an EVP_PKEY, Calling EVP_PKEY_get_bn_parms() to get the p,g etc params does not work.

Also see #13522.

**Comment by mattcaswell** [comment]
Same issue applies to other "params" calls, e.g. `EVP_PKEY_get_utf8_string_param()`

**Comment by slontis** [comment]
@levitte : This is the reason for some failing SSL tests for the "ec deprecation" PR also.

Do you have any suggestions on how to handle this..
We just have a legacy key here with no pkey_ctx or keymanager (i.e it has a ameth) so I am not sure how this will be able to do an export here.
I assume a big special case 'switch' table here is not what we really want to do?

**Comment by levitte** [comment]
My suggestion is to continue to make specialized functions for all cases where we expect EVP_PKEYs to have either a legacy or a provided key.  See #13436.

In the future, when legacy stuff is removed, we will have to deprecate them and turn to pure OSSL_PARAM support, but as long as we have legacy stuff, this is the path we're already on.

**Comment by slontis** [comment]
We may need to discuss this within OTC..
Since this pretty much makes the EVP_PKEY_get_XXXX_param() calls pretty much pointless.
(The getters assumed non-legacy use cases when they were written).

**Comment by levitte** [comment]
> Since this pretty much makes the EVP_PKEY_get_XXXX_param() calls pretty much pointless.

Er, no?

https://github.com/openssl/openssl/blob/81aef6ba720971c09ad68f89d418c8d3d3f904f7/crypto/evp/p_lib.c#L1260-L1263

**Comment by levitte** [comment]
I hear you, though.  And yeah, it's perfectly possible to to the reverse of what we've done with ctrls, i.e. a params-to-legacy function to support the transition.

Are you willing to code that?

**Comment by mattcaswell** [comment]
>  Er, no?

Having to check whether a key is legacy or not if quite horrific from an end user perspective (this should be an internal implementation detail that they are not aware of).

**Comment by levitte** [comment]
> Having to check whether a key is legacy or not if quite horrific from an end user perspective (this should be an internal implementation detail that they are not aware of).

I wasn't implying that they should have to do that.

**Comment by levitte** [comment]
So...  are we done discussing approaches?  I can accept that we will make the diverse EVP_PKEY_get_*_param functions work with legacy keys, and my proposal is params-to-legacy translation of all the things we're interested in.  That involves extracting the underlying type (RSA, DSA, ...) and extracting numbers from it in some cases, or calling a ctrl function in other cases.

Another approach, which I think has been mentioned, is to do the automated export to provider and make the appropriate get_params() call.  I see an issue with that one, though, that it cannot support ENGINE backed keys (not even those with open data, since they are unlikely to have implemented the required export function).

If we're done discussing, it might be time to code...

**Comment by jon-oracle** [comment]
@levitte I may have some time to look at this. The params-to-legacy approach, extracting fields from the new API to return via legacy APIs, would be my first choice but I'd need to prototype something to see how feasible it is. Let me know if you have any more helpful insights!

**Comment by levitte** [comment]
I had an idea now that this calls for a bit of refactoring, to give translation data more of a two way flair.

I mean, the "easy" way is to create a separate set of functions that do the inverse of `legacy_ctrl_to_param` and friends, but that comes with a cost of one more spot to keep track of and potential loss of sync.

So er, you or me?

**Comment by jon-oracle** [comment]
@levitte Ah ok. I'm continuing to dig up and investigate other issues which may or may not be related, so I'm a long way from coding this. I'm happy to leave this one to you.

**Comment by slontis** [comment]
@levitte is the bottleneck currently - so probably not a good idea to assign to him.

**Comment by levitte** [comment]
Well...  I'm already well ahead, so I might as well finish it up.
(what I'm doing will also clean away huge amounts of code copying)

**Comment by levitte** [comment]
One thing we need to be aware of is that there's no way we can support EVP_PKEY_get_bn_param() on ENGINE-implemented key types that we know nothing about.  That translation capability is simply not there, and never was.  On the other hand, there has never been any support to extract payload from such keys, so it's probably not something to worry about.

**Comment by levitte** [comment]
See #13913.
