### ISSUE TITLE
APPS: Check that all apps really consume all command line arguments

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#13527]
As part of this, the apps need to check if there are any remaining command line arguments, and exit with an error in that case

**Comment by richsalz** [comment]
Almost all commands do this.  Some (cms, errstr) are special cases.  Which ones have you found?

**Comment by levitte** [comment]
> Which ones have you found?

We haven't.  We made this issue as a reminder to double check.  Are you willing to help us out with this?

**Comment by richsalz** [comment]
Yes, I will do this, to help 3.0 get done.
