### ISSUE TITLE
OBJ_create is not thread-safe

### ISSUE THREAD

**Issue by kingiw** [openssl/openssl#13524]
In version >= 1.1.0, `OBJ_create` will check if an ASN1 object already existed by `nid`, `long name` and `short name`. See [here](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/objects/obj_dat.c#L690).

If `OBJ_create` (with the same input params) is called by multiple threads, random number of ASN1 object will be created due to the concurrency. 

You can run this example scripts for test:
```c++
#include <string.h>
#include <thread>
#include <vector>
#include "openssl/pem.h"
#include "openssl/evp.h"

using namespace std;

void test() {
    int nid = OBJ_create("1.2.3.4", "short name", "long name");
    printf("nid %d\n", nid);
}

int main() {
    vector<unique_ptr<thread>> v;
    for (size_t i = 0; i < 10; ++i) {
        v.emplace_back(new thread(test));
    }
    for (size_t i = 0; i < 10; ++i) {
        v[i]->join();
    }
}
```
Random number of threads will create the ASN object successfully, while the rest threads will get `nid==0`. 

Is this an expected behavior? 
How can a thread get the correct AS1 object when `OBJ_create` returns 0?

**Comment by mattcaswell** [comment]
IMO, this is expected behaviour. Any `OBJ_create()` calls should be done before multiple threads are called. That's probably not the way we would design the API these days, but its been that way for a long time, and I think the lack of thread safety is known. AFAICT though it doesn't seem to be documented anywhere, so there is at least a documentation issue here.

**Comment by kingiw** [comment]
Thanks for your response.

How can a thread create an ASN object or get the existed ASN object properly if the program is running in a multi-threading environment? 

Does this code works?
```cpp
// Acquire a mutex
int nid = create_OBJ("1.2.3.4", "short_name", "long_name");
if (nid != 0) {
  nid = OBJ_ln2nid("long_name");
  // or nid = OBJ_sn2nid("short_name");
}
// release a mutex
```

**Comment by mattcaswell** [comment]
> Does this code works?

Unfortunately not. You just can't create them in a multi-threaded environment. Or at least you would have to guarantee that no other thread was calling any OpenSSL function. The OBJ_ database is used extensively internally so any OpenSSL function could end up making OBJ_* function calls and hence run into these problems.
