### ISSUE TITLE
Cannot retrieve parameters from DH key created using d2i_AutoPrivateKey_ex()

### ISSUE THREAD

**Issue by jon-oracle** [openssl/openssl#13522]
I've found that if I use the d2i_AutoPrivateKey_ex API then I can create a valid EVP_PKEY but the EVP_PKEY_get_bn_param() calls to retrieve the P & G values fail.

Here's a modified test to show the failure:

https://github.com/openssl/openssl/commit/2b76d9b1d031597f5e8c64c157bb31e4618b106e

The EVP_PKEY_get0_DH() and DH_get0_pqg() APIs return the parameters fine but the test fails on the first call to EVP_PKEY_get_bn_param().

**Comment by mattcaswell** [comment]
There are two issues here:

1) Why does d2i_AutoPrivateKey_ex result in an EVP_PKEY with a legacy key?
and
2) When you have a legacy key why doesn't EVP_PKEY_get_bn_param() work?

For the second issue I have raised #13528
