### ISSUE TITLE
Does EVP_ENCODER_CTX_new_by_EVP_PKEY() need an explicit library context?

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#13544]
This is the current signature for that function:

``` C
OSSL_ENCODER_CTX *OSSL_ENCODER_CTX_new_by_EVP_PKEY(const EVP_PKEY *pkey,
                                                   int selection,
                                                   const char *output_type,
                                                   const char *output_struct,
                                                   OSSL_LIB_CTX *libctx,
                                                   const char *propquery);
```

However, the passed `pkey` already holds a library context, so it can just as well be extracted from there.  Furthermore, it's questionable whether the key should be passed to another library context for encoding.

**Comment by levitte** [comment]
This was first discussed as a side note in #13542

**Comment by levitte** [comment]
Proposed change in #13545

**Comment by t8m** [comment]
+1 to using the implicit context from PKEY and removing the parameter.

**Comment by mattcaswell** [comment]
Seems reasonable to get the context from the PKEY.

**Comment by slontis** [comment]
I am ok with removing the libctx also..

This should allow code like the following to set the libctx in the non '_ex' method calls..

````
PEM_write_fnsig(Parameters, EVP_PKEY, BIO, write_bio)
{
    char pem_str[80];
    IMPLEMENT_PEM_provided_write_body_vars(EVP_PKEY, Parameters, NULL, NULL);
````

**Comment by levitte** [comment]
> This should allow code like the following to set the libctx in the non '_ex' method calls..

Didn't think of it, but yeah, that's going to happen automagically, you're quite right about that

**Comment by levitte** [comment]
This question, and especially #13545 will need an OTC vote, won't it?  It *is* an API change, albeit only in master.

**Comment by slontis** [comment]
It is only a change in 3.0, raising it during a meeting wouldnt hurt..

**Comment by paulidale** [comment]
Not having the library context is goodness.
