### ISSUE TITLE
RSA signatures with RIPEMD160 MAC incompatible between openssl-3.0.0-alpha9 and openssl-1.x.x

### ISSUE THREAD

**Issue by eichelberg** [openssl/openssl#13559]
I am one of the developers of an open source toolkit named DCMTK (www.dcmtk.org) that implements the DICOM standard ("Digital Imaging and Communications in Medicine"), which defines a very common file format and network communication protocol for medical images. DCMTK uses OpenSSL to implement encrypted network connections (TLS) and digital signatures.

I tested the current version of DCMTK, which is know to work correctly with OpenSSL 1.0.1, 1.0.2, 1.1.0 and 1.1.1, with the latest Alpha 9 release of OpenSSL 3.0.0 and noticed that most digital signatures created with previous OpenSSL versions cannot be verified anymore with the same tool (same source code) compiled and linked against OpenSSL 3.0.0-alpha9.

Specifically, this affects RSA signatures using a RIPEMD160 message digest, which is the default for signatures in the DICOM standard. The reason is apparently the PKCS1 padding, implemented in encode_pkcs1() in crypto/rsa/rsa_sign.c, which produces a different byte stream in openssl-3.0.0-alpha9 than in previous releases.

In previous releases (specifically 1.1.0), encode_pkcs1() internally calls i2d_X509_SIG() and produces the following padded byte sequence for a RIPEMD hash:
```
30 20 30 08 06 04 2b 24 03 03 01 02 05 00 04 14                # PKCS#1 padding
eb 64 e6 fe e9 59 7e 6c ab 45 8d 5f ea cc 39 51 05 49 0d 8d    # RIPEMD160 hash
```
In openssl-3.0.0-alpha9, the padding is defined in digestinfo_ripemd160_der[] and produces the folowing byte sequence:
```
30 21 30 09 06 05 2b 24 03 02 01 05 00 04 14                   # PKCS#1 padding
eb 64 e6 fe e9 59 7e 6c ab 45 8d 5f ea cc 39 51 05 49 0d 8d    # RIPEMD160 hash
```

This causes signatures created with OpenSSL 1.x.x to fail verification when using OpenSSL 3.0.0, and vice versa.

The bug can be reproduced by compiling DCMTK with OpenSSL 3.0.0 and verifying a signature created with an earlier version (e.g. using the binaries available from www.dcmtk.org).

**Comment by levitte** [comment]
Ah-yup, those numbers aren't quite right.  However, *none* of those you show are right:

1.  The OID (which is 1.3.36.3.3.1.2) has been coded as

     **06** _04_ 2b 24 03 03 01 02

    The length (in italics) is very obviously incorrect

2.  The OID (still 1.3.36.3.2.1) has been coded as

    **06** _05_ 2b 24 03 02 01

    While this is a correct encoding for the OID, this is the RIPEMD160 hash algorithm OID, not the rsaSignatureWithripemd160 signature OID.

BTW, I think you have things mixed up.  The first output is more likely from OpenSSL 3.0 and the latter from 1.1.1.

I have a fix for OpenSSL 3.0 coming up

**Comment by levitte** [comment]
#13562 should give more sensible output

**Comment by eichelberg** [comment]
Yes, I have mixed things up. OpenSSL 1.1 produces a 35-byte output for the padded mac, OpenSSL 3.0 produces a 36-byte output. The second one is from 1.1, the first one from 3.0.

And I don't think that pull request 13562 will fix that issue - I fail to see how this should affect the length of the padded output.

One more thing: If all OpenSSL releases before 3.0 have been using 1.3.36.3.3.1.2 as OID, then you cannot just change that in 3.0 (not without offering a compatibility option, at least), because otherwise nobody using OpenSSL 3.0 will be able to verify a signature anymore that was created with any older release.

**Comment by levitte** [comment]
Thanks for having me look again.  Yes, you are absolutely right, the digestinfos must contain the hash OID (i.e. encoded 1.3.36.3.2.1), not the corresponding signature OID.

I just pushed a correction to #13562
