### ISSUE TITLE
Unused variable assignments

### ISSUE THREAD

**Issue by FloridSleeves** [openssl/openssl#13555]
Hi! I've recently used some tool to check OpenSSL code (master branch, newest version) and find that there are a lot of unused value assignments in the code base. When a developer assigns some value to a variable, the expectation is to use the value sometimes. So an unused assignment could potentially indicate bugs. 

To categorize, the unused assignments we find in OpenSSL code base include:

1. Unhandled return value:

File Name	| Variable Name  |  Line Number	
----------------|--------------------|---------------
crypto/initthread.c | hands | 179 
crypto/asn1/bio_ndef.c | derlen | 124 

These two values assigned from callee return value do not get handled. Since the return value of functions may indicate error code or some useful information, they are potentially bugs.

2. Unused assignment

File Name	| Variable Name |  Line Number	
-------------------- |---------------------|--------------------
crypto/store/store_result.c | der | 369
crypto/store/store_result.c | der_len | 370
crypto/x509/x509_vfy.c | x | 3304
providers/implementations/ciphers/cipher_aes_cbc_hmac_sha1_hw.c | maxpad | 617
providers/implementations/ciphers/cipher_aes_cbc_hmac_sha256_hw.c | maxpad | 669
crypto/asn1/asn1_par.c | bp | 78
crypto/initthread.c | hands | 179
crypto/bn/bn_exp.c | j | 412
crypto/bn/bn_exp.c | t | 1255
crypto/bn/bn_exp.c | j | 255
crypto/bn/bn_exp.c | j | 1357
crypto/evp/e_aes_cbc_hmac_sha1.c | maxpad | 716
crypto/evp/e_aes_cbc_hmac_sha256.c | maxpad | 720
crypto/asn1/tasn_dec.c | q | 347
crypto/asn1/tasn_dec.c | q | 522
crypto/bio/b_print.c | ch | 331

These values get assigned but not used, they could indicate either bugs or redundant assignments.

3. Unused initialization

File Name	| Variable Name |  Line Number	
-------------------- |---------------------|--------------------
crypto/encode_decode/decoder_lib.c | bio | 509
providers/implementations/keymgmt/rsa_kmgmt.c | mdname | 331
crypto/aes/aes_ige.c | len | 53
crypto/x509/by_dir.c | postfix | 231

Though the unused initialization value possibly does not affect the normal functionality, they may waste instruction cycles and harm the readability of the code.

4. Unused parameter

File Name	| Variable Name |  Line Number	
-------------------- |---------------------|--------------------
ssl/record/ssl3_record_tls13.c | mac | 24
ssl/record/ssl3_record_tls13.c | macsize | 24
include/internal/refcount.h | lock | 49
include/internal/refcount.h | lock | 33
ssl/statem/extensions.c | context | 1132
ssl/statem/extensions_srvr.c | context | 270
ssl/statem/extensions_srvr.c | x | 271
ssl/statem/extensions_srvr.c | chainidx | 271
ssl/statem/extensions.c | context | 1677
ssl/statem/extensions_clnt.c | context | 1161
ssl/statem/extensions_clnt.c | x | 1162
ssl/statem/extensions_clnt.c | chainidx | 1162
ssl/statem/extensions_srvr.c | context | 1217
ssl/statem/extensions_srvr.c | x | 1218
ssl/statem/extensions_srvr.c | chainidx | 1218
ssl/statem/statem_lib.c | wst | 1046

These unused parameter may invoke compiler warnings, as well as being neglect because of some underlying bugs.

I will appreciate it so much if you could take time to confirm, especially for the 1st and 2nd category! 

Also, for the unused assignments and parameters that are just redundant, I wonder whether I can help to remove them. After all, their existence can either invoke compiler warnings or make the code readability worse.

Thank you for your patient reading!

**Comment by paulidale** [comment]
The ones of these that I've looked at thus far are all false positives.

This doesn't mean that they shouldn't be addressed (where reasonable), but it does mean your static analyser needs more fine tuning.

The enemy of static analysis is false positives.

**Comment by FloridSleeves** [comment]
Thanks for your confirmation and suggestion! I really agree with your opinion that we should do more on filtering out real bugs from the unused assignments. We will try more on that direction.

If there is anything I can help with the milestone on this issue, I'm always willing to. :-) 

Thanks again!
