### ISSUE TITLE
Compile shared libssl with static libcrypto

### ISSUE THREAD

**Issue by Adrianilloo** [openssl/openssl#13561]
When building OpenSSL 1.1.1, is it possible to produce a shared ssl library (`libssl.so.1.1`) that links statically against `libcrypto.a` instead of its shared library?

My current config: `./config no-comp no-ssl2 no-ssl3 no-threads shared && make`

If this isn't possible, how to prevent that `libcrypto.so.1.1` dependency entry resolves to a system path, but uses the one in the current working directory instead? So for embedding both shared libraries locally in application.

```
ldd lib/libssl.so.1.1
        linux-vdso.so.1 (0x00007ffd65f63000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f364109b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3640ea9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3640ea3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3640e80000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3641612000)
```
Thank you.

**Comment by levitte** [comment]
Our building stuff doesn't allow that mix between shared and static, no.

Your problem is a generic problem, though.  On Linux, the environment variable `LD_LIBRARY_PATH` can be used to tell ld.so where it should go look for libraries before going looking in the system default.  For more information, see [man ld.so](https://man7.org/linux/man-pages/man8/ld.so.8.html).

**Comment by Adrianilloo** [comment]
> Our building stuff doesn't allow that mix between shared and static, no.

I understand. Fine.

> Your problem is a generic problem, though. On Linux, the environment variable `LD_LIBRARY_PATH` can be used to tell ld.so where it should go look for libraries before going looking in the system default. For more information, see [man ld.so](https://man7.org/linux/man-pages/man8/ld.so.8.html).

I'm aware of `LD_LIBRARY_PATH` but I had used it mistakenly so I got confused, like this: `LD_LIBRARY_PATH=. ldd lib/libssl.so.1.1`

Fix:

```
$ LD_LIBRARY_PATH=lib ldd lib/libssl.so.1.1
libcrypto.so.1.1 => lib/libcrypto.so.1.1 (0x00007f4185001000)
```

Thanks for the answer. Closing then.
