### ISSUE TITLE
OCSP callbacks in case of Hello Retry Request

### ISSUE THREAD

**Issue by anupamam13** [openssl/openssl#13574]
I have ocsp callback registered on my proxy server to staple ocsp response if the client sends a status_request. I am updating stats in this callback to keep track of number of ocsp requests. In the case where there is a Hello Retry Request, this callback will be called twice and hence the stats is getting updated twice. What can i check to make sure i update this stat only once?

**Comment by mattcaswell** [comment]
I don't think we expose the HRR state anywhere through the API, so I can't immediately think of something you could check. But you could use `SSL_set_ex_data` to associate some app specific data to the SSL object. That data could include a flag to indicate whether you've already "counted" that object.

https://www.openssl.org/docs/man1.1.1/man3/SSL_set_ex_data.html

**Comment by anupamam13** [comment]
If i were to access the HRR state by using a patch, what would be the value i have to check, out of SSL_HRR_NONE, SSL_HRR_PENDING and SSL_HRR_COMPLETE. Please do let me know.

**Comment by t8m** [comment]
Matt's answer is the proper way how to do that.
