### ISSUE TITLE
DTLS cookie exchange in openssl is different as RFC6347

### ISSUE THREAD

**Issue by wongmz** [openssl/openssl#13579]
According to rfc6347, in DTLS, default execute cookie exchange.
However, in OpenSSL, must use SSL_set_options() to set SSL_OP_COOKIE_EXCHANGE.
![image](https://user-images.githubusercontent.com/54125561/100709620-6633cf00-33e9-11eb-8ddc-fccf012a3147.png)

**Comment by mattcaswell** [comment]
> However, in OpenSSL, must use SSL_set_options() to set SSL_OP_COOKIE_EXCHANGE.

In fact this option is automatically set if you use `DTLSv1_listen()`. If you are not using `DTLSv1_listen()` then the server is stateful anyway and there is less benefit to using cookies.

**Comment by wongmz** [comment]
> In fact this option is automatically set if you use `DTLSv1_listen()`. If you are not using `DTLSv1_listen()` then the server is stateful anyway and there is less benefit to using cookies.

Does OpenSSL plan to DTLS default execute cookie exchange in future versions, no additional settings are required?
Why do I use SSL_set_options() to set up SSL_OP_COOKIE_EXCHANGE instead of DTLSv1_listen(), which leads to less benefits?

**Comment by mattcaswell** [comment]
> Does OpenSSL plan to DTLS default execute cookie exchange in future versions, no additional settings are required?

No.

> Why do I use SSL_set_options() to set up SSL_OP_COOKIE_EXCHANGE instead of DTLSv1_listen(), which leads to less benefits?

I would recommend that you use the `DTLSv1_listen()` approach rather than setting the option explicitly via `SSL_set_options()`. The main reason to use the latter is that it makes the code slightly simpler - but the code is not stateless. You will still gain *some* benefit rather than no cookies at all, but `DTLSv1_listen()` is the best route.
