### ISSUE TITLE
How to establish a session with all supported elliptic curves?

### ISSUE THREAD

**Issue by dylc5190** [openssl/openssl#13582]
I want to test all the supported elliptic curves with the command like this

```
for c in `cat curves`
do
openssl s_client -connect 172.17.0.3:443 -cipher kEECDH:kECDHE:ECDH:ECDHE:EECDH -curves $c -no_tls1_3
done
```

Initially I use `openssl ecparam -list_curves` as my input but I found many of them cannot perform the handshake successfully. Later I found the list https://github.com/openssl/openssl/blob/0c60676338f1e25faaa44117238d8e35e507feee/ssl/t1_lib.c#L141 but again not all of them work. The failed ones are as below
```
sect163k1
sect163r1
sect163r2
sect193r1
sect193r2
sect233k1
sect233r1
sect239k1
secp160k1
secp160r1
secp160r2
secp192k1
secp192r1
secp224k1
secp224r1
secp256r1
brainpool512r1
X25519
X448
```
Among them there 3 curves have different errors
```
secp192r1
secp256r1
brainpool512r1
```

The errors are
```
Error with command: "-curves secp192r1"
Error with command: "-curves secp256r1"
Error with command: "-curves brainpool512r1"

```
I'm wondering if my approach has any mistake? How to explain the errors I got? Are they not supported or there are additional configurations I missed?

**Comment by mattcaswell** [comment]
> but again not all of them work. The failed ones are as below

Most likely the server doesn't support them - hence they fail.

For the ones with a different error:

> secp192r1

Use the name "P-192" or "prime192v1" for this curve.

> secp256r1

Use the name "P-256" or "prime192v1" for this curve

> brainpool512r1

That's a typo in the comment in the t1_lib.c file. It should be "brainpoolP512r1" (i.e. with a "P" in it).

**Comment by dylc5190** [comment]
Thank you but I still have a question. Why not all of the curves listed in the result of `openssl ecparam -list_curves` are supported? For example, 
`openssl s_server -accept 1443  -cert rsacrt.pem  -key rsakey.pem -curves c2tnb431r1`
gave me this error
`Error with command: "-curves c2tnb431r1"`

**Comment by mattcaswell** [comment]
> Why not all of the curves listed in the result of openssl ecparam -list_curves are supported? 

OpenSSL is a general purpose crypto library and supports many different curves. However, not all curves that OpenSSL supports are defined for use in TLS. IANA maintains a list of curves that are defined for use in TLS:

https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8

So only the curves in the output from `openssl ecparam -list_curves` that are also in the above IANA list can be used.

**Comment by dylc5190** [comment]
It sounds that nid_list is a subset of `openssl ecparam -list_curves`
However this is what I found in openssl-1.1.1g
https://github.com/openssl/openssl/blob/e2e09d9fba1187f8d6aafaa34d4172f56f1ffb72/ssl/t1_lib.c#L141
```
static const TLS_GROUP_INFO nid_list[] = {
    {NID_sect163k1, 80, TLS_CURVE_CHAR2}, /* sect163k1 (1) */
    {NID_sect163r1, 80, TLS_CURVE_CHAR2}, /* sect163r1 (2) */
    {NID_sect163r2, 80, TLS_CURVE_CHAR2}, /* sect163r2 (3) */
    {NID_sect193r1, 80, TLS_CURVE_CHAR2}, /* sect193r1 (4) */
    {NID_sect193r2, 80, TLS_CURVE_CHAR2}, /* sect193r2 (5) */
    {NID_sect233k1, 112, TLS_CURVE_CHAR2}, /* sect233k1 (6) */
    {NID_sect233r1, 112, TLS_CURVE_CHAR2}, /* sect233r1 (7) */
    {NID_sect239k1, 112, TLS_CURVE_CHAR2}, /* sect239k1 (8) */
    {NID_sect283k1, 128, TLS_CURVE_CHAR2}, /* sect283k1 (9) */
    {NID_sect283r1, 128, TLS_CURVE_CHAR2}, /* sect283r1 (10) */
    {NID_sect409k1, 192, TLS_CURVE_CHAR2}, /* sect409k1 (11) */
    {NID_sect409r1, 192, TLS_CURVE_CHAR2}, /* sect409r1 (12) */
    {NID_sect571k1, 256, TLS_CURVE_CHAR2}, /* sect571k1 (13) */
    {NID_sect571r1, 256, TLS_CURVE_CHAR2}, /* sect571r1 (14) */
    {NID_secp160k1, 80, TLS_CURVE_PRIME}, /* secp160k1 (15) */
    {NID_secp160r1, 80, TLS_CURVE_PRIME}, /* secp160r1 (16) */
    {NID_secp160r2, 80, TLS_CURVE_PRIME}, /* secp160r2 (17) */
    {NID_secp192k1, 80, TLS_CURVE_PRIME}, /* secp192k1 (18) */
    {NID_X9_62_prime192v1, 80, TLS_CURVE_PRIME}, /* secp192r1 (19) */
    {NID_secp224k1, 112, TLS_CURVE_PRIME}, /* secp224k1 (20) */
    {NID_secp224r1, 112, TLS_CURVE_PRIME}, /* secp224r1 (21) */
    {NID_secp256k1, 128, TLS_CURVE_PRIME}, /* secp256k1 (22) */
    {NID_X9_62_prime256v1, 128, TLS_CURVE_PRIME}, /* secp256r1 (23) */
    {NID_secp384r1, 192, TLS_CURVE_PRIME}, /* secp384r1 (24) */
    {NID_secp521r1, 256, TLS_CURVE_PRIME}, /* secp521r1 (25) */
    {NID_brainpoolP256r1, 128, TLS_CURVE_PRIME}, /* brainpoolP256r1 (26) */
    {NID_brainpoolP384r1, 192, TLS_CURVE_PRIME}, /* brainpoolP384r1 (27) */
    {NID_brainpoolP512r1, 256, TLS_CURVE_PRIME}, /* brainpool512r1 (28) */
    {EVP_PKEY_X25519, 128, TLS_CURVE_CUSTOM}, /* X25519 (29) */
    {EVP_PKEY_X448, 224, TLS_CURVE_CUSTOM}, /* X448 (30) */
};
```
Compared to `openssl ecparam -list_curves`, all sect* curves are not included. This makes confused again.
```
# openssl version
OpenSSL 1.1.1g  21 Apr 2020
# openssl ecparam -list_curves
  secp112r1 : SECG/WTLS curve over a 112 bit prime field
  secp112r2 : SECG curve over a 112 bit prime field
  secp128r1 : SECG curve over a 128 bit prime field
  secp128r2 : SECG curve over a 128 bit prime field
  secp160k1 : SECG curve over a 160 bit prime field
  secp160r1 : SECG curve over a 160 bit prime field
  secp160r2 : SECG/WTLS curve over a 160 bit prime field
  secp192k1 : SECG curve over a 192 bit prime field
  secp224k1 : SECG curve over a 224 bit prime field
  secp224r1 : NIST/SECG curve over a 224 bit prime field
  secp256k1 : SECG curve over a 256 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime192v1: NIST/X9.62/SECG curve over a 192 bit prime field
  prime192v2: X9.62 curve over a 192 bit prime field
  prime192v3: X9.62 curve over a 192 bit prime field
  prime239v1: X9.62 curve over a 239 bit prime field
  prime239v2: X9.62 curve over a 239 bit prime field
  prime239v3: X9.62 curve over a 239 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
  wap-wsg-idm-ecid-wtls6: SECG/WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls7: SECG/WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls8: WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls9: WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls12: WTLS curve over a 224 bit prime field
  brainpoolP160r1: RFC 5639 curve over a 160 bit prime field
  brainpoolP160t1: RFC 5639 curve over a 160 bit prime field
  brainpoolP192r1: RFC 5639 curve over a 192 bit prime field
  brainpoolP192t1: RFC 5639 curve over a 192 bit prime field
  brainpoolP224r1: RFC 5639 curve over a 224 bit prime field
  brainpoolP224t1: RFC 5639 curve over a 224 bit prime field
  brainpoolP256r1: RFC 5639 curve over a 256 bit prime field
  brainpoolP256t1: RFC 5639 curve over a 256 bit prime field
  brainpoolP320r1: RFC 5639 curve over a 320 bit prime field
  brainpoolP320t1: RFC 5639 curve over a 320 bit prime field
  brainpoolP384r1: RFC 5639 curve over a 384 bit prime field
  brainpoolP384t1: RFC 5639 curve over a 384 bit prime field
  brainpoolP512r1: RFC 5639 curve over a 512 bit prime field
  brainpoolP512t1: RFC 5639 curve over a 512 bit prime field


```

**Comment by mattcaswell** [comment]
> Compared to openssl ecparam -list_curves, all sect* curves are not included.

Did you builds openssl yourself, or are you using the OS supplied version? OpenSSL provides a compile time option to disable support for "binary curves". This includes all the "sect" curves. Some distros do this for patent reasons. It seems likely to me that you are running a version of OpenSSL without support for those curves compiled - hence you can seem them mentioned in the source code, but not in the output from `-list_curves`.

>Is there any method to get supported curves, i.e., nid_list I think?

Unfortunately not, no. That would be a useful feature.

**Comment by dylc5190** [comment]
Yes, I tried both. Now I understand why they are different even the version is the same. As for supported curves, my workaround is to call SSL_CTX_set1_groups_list and check the return code. Thanks for the help.
