### ISSUE TITLE
list -cipher-commands lists ciphers that aren't available

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13594]
The list option `-cipher-commands` option is supposed to list the available ciphers. However it takes no note of what providers are available so, for example, if the  legacy provider is not loaded it will still list legacy ciphers.

**Comment by levitte** [comment]
> if the legacy provider is not loaded it will still list legacy ciphers.

Well, er, yes.  Those are not from the legacy provider, they are EVP_PKEY_METHOD implementations.
(we do confuse legacy and legacy...)

I assume this will be resolved as soon as we start clearing `standard_methods[]` (in `crypto/evp/pmeth_lib.c`)

**Comment by mattcaswell** [comment]
> I assume this will be resolved as soon as we start clearing standard_methods[] (in crypto/evp/pmeth_lib.c)

As I read the code its just a hard coded list:

https://github.com/openssl/openssl/blob/b03da688a223c18b5a10b5a66abe229bbb590133/apps/progs.pl#L176-L218

**Comment by levitte** [comment]
Oh *cipher* commands.... Never mind, I read this wrong.

**Comment by richsalz** [comment]
I think you should deprecate the idea of "cipher-name is a command" and not add any more because of the complexity of handling providers.

**Comment by levitte** [comment]
I agree with @richsalz regarding this

**Comment by paulidale** [comment]
This should list available ciphers, rather than a fixed list.  `-cipher-algorithms` does this.

Keep the fixed list.  Attempt to fetch each item in the list and only print it if it is found.
Deprecate?
