### ISSUE TITLE
Android javax.net.ssl and FIPS compliance openSSL. (In app vs android stack)

### ISSUE THREAD

**Issue by NitzDKoder** [openssl/openssl#1359]
Hi folks,

AFAIK Android javax.net.ssl classes uses openSSL/BoringSSL library at C/Low level for any SSL/TLS.

https://developer.android.com/reference/javax/net/ssl/package-summary.html.

/**
* Provides the Java side of our JNI glue for OpenSSL.
*/
https://android.googlesource.com/platform/external/conscrypt/+/f087968/src/main/java/org/conscrypt/OpenSSLSocketImpl.java
 
https://android.googlesource.com/platform/external/conscrypt/+/master/src/main/java/org/conscrypt/NativeCrypto.java
 
https://android.googlesource.com/platform/external/conscrypt/+/master/src/main/java/org/conscrypt
 
 
C++
https://android.googlesource.com/platform/external/conscrypt/+/master/src/main/native/org_conscrypt_NativeCrypto.cpp
 
org_conscrypt_NativeCrypto.cpp
 
https://android.googlesource.com/platform/external/conscrypt/+/master/Android.mk
 
(Build OpenSSL or BoringSSL).
 
**Intention:** Load FIPS compliance openSSL libaray in my application and make javax.net.ssl(okhttp) classes use the that library hence my application become fips complaince.

https://wiki.openssl.org/index.php/FIPS_Library_and_Android
http://square.github.io/okhttp/

Simlilar to WolfSSL provider but its at firrware level or aosp,  also its not JSSE compatible.

http://www.linuxjournal.com/article/10896

is this feasible to load FIPS openSSL .OS and link it , what are configuration at android java level ?

Thanks
Nithin

**Comment by NitzDKoder** [comment]
@mattcaswell pls share your thoughts on this..

**Comment by mattcaswell** [comment]
Sorry, I'm not really the best person to ask about either FIPS or andriod. In any case this issue is probably better raised on the openssl-users email list rather than here as it isn't a bug. Sign up info here:
mta.openssl.org

**Comment by mattcaswell** [comment]
If this is still an open question please raise on openssl-users as noted above. Closing this.
