### ISSUE TITLE
Support  RFC 8879 on TLS Certificate Compression

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#13597]
Details in https://www.rfc-editor.org/info/rfc8879

In TLS handshakes, certificate chains often take up the majority of
the bytes transmitted.

This document describes how certificate chains can be compressed to
reduce the amount of data transmitted and avoid some round trips.

This document is a product of the Transport Layer Security Working Group of the IETF.

**Comment by davidben** [comment]
The extension will be especially valuable for QUIC:
https://www.fastly.com/blog/quic-handshake-tls-compression-certificates-extension-study

**Comment by t184256** [comment]
Is it now closed with https://github.com/openssl/openssl/pull/18186#issuecomment-1282606957?

**Comment by tomato42** [comment]
fixed by #18186 ?

**Comment by hlandau** [comment]
Yes, I believe this is resolved by #18186.
