### ISSUE TITLE
During the performance test, the performance fluctuates greatly.

### ISSUE THREAD

**Issue by yxungh** [openssl/openssl#13601]
Hi,
When I use `openssl speed -evp xxx`,Comparing OpenSSL 1.1.1f and OpenSSL 3.0 in performance tests,The changes greatly in each test. Does this indicate that the performance of OpenSSL 3.0 is unstable in the current phase?

For example:
Percentage Diff (%) =(3.0-1.1.1f)/1.1.1f

First | sign/s |   |   | verify/s |   |  
-- | -- | -- | -- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
256 bits ecdsa(nistp256) | 14772.3 | 32115.2 | -54.00215474 | 8159.6 | 10581.6 | -22.88878808
384 bits ecdsa(nistp384) | 677.4 | 722 | -6.177285319 | 849.4 | 976.7 | -13.03368486
253 bits EdDSA(Ed25519) | 17114.7 | 21251.5 | -19.46592005 | 5288.9 | 6561.7 | -19.39741226

Second | sign/s |   |   | verify/s |   |  
-- | -- | -- | -- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%) | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
256 bits ecdsa(nistp256) | 31357.1 | 20346 | 54.1192372 | 10818.3 | 10370.9 | 4.313993964
384 bits ecdsa(nistp384) | 804.4 | 456.2 | 76.32617273 | 951.9 | 917.3 | 3.771939387
253 bits EdDSA(Ed25519) | 19982.7 | 20526.4 | -2.648784005 | 6119.8 | 5533.5 | 10.59546399

First | op/s |   |  
-- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
256 bits ecdh(nistp256) | 5813.3 | 13722.5 | -57.636728
384 bits ecdh(nistp384) | 510.7 | 660.3 | -22.65636832
253 bits ecdh(X25519) | 14872.5 | 20350.3 | -26.9175393

Second | op/s |   |  
-- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
256 bits ecdh(nistp256) | 14139.5 | 13342.5 | 5.973393292
384 bits ecdh(nistp384) | 861.2 | 752.2 | 14.49082691
253 bits ecdh(X25519) | 20318.2 | 18867.9 | 7.686599993

First | 16 bytes |   |  
-- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
aes-128-gcm | 91862.83 | 243883.56 | -62.33332415

Second | 16 bytes |   |  
-- | -- | -- | --
  | openssl3.0 | openssl1.1.1f | Percentage Diff (%)
aes-128-gcm | 314223.45 | 248368.29 | 26.51512397

These are only partial data.
I think the openssl3.0 alpha stage is unstable.
Or in this case, can I consider the performance of OpenSSL 3.0 deteriorated?

**Comment by t8m** [comment]
What machine do you use to test? If that is a laptop there might be thermal and power saving controls in play.

**Comment by yxungh** [comment]
> What machine do you use to test? If that is a laptop there might be thermal and power saving controls in play.

It is a Linux x86 machine instead of a laptop. The performance of the machine is different each time.
Is it normal?

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz
Stepping:              4
CPU MHz:               2200.000
BogoMIPS:              4400.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              30976K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch arat fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1

**Comment by kroeckx** [comment]
I can not reproduce this. Results of `openssl speed ecdsap256` using master:
```
                              sign    verify    sign/s verify/s
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  27393.7   8885.6
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  27579.3   8871.4
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  27494.4   8890.7
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  27587.8   8883.6
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  27555.0   8894.6
```
Which gives:
sign/s = 27522 +/- 72
verify/s = 8885.1 +/- 7.9

With 1.1.1 I get:
```
                              sign    verify    sign/s verify/s
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  28886.9   8761.9
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  28837.6   8736.2
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  28975.2   8761.2
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  28921.1   8800.7
 256 bits ecdsa (nistp256)   0.0000s   0.0001s  28833.9   8774.4
```

Which gives:
sign/s = 28891 +/- 53
verify/s = 8767 +/- 21

Difference:
sign/s = -4.7%
verify/s = +1.3%

**Comment by levitte** [comment]
What does "first" and "second" mean?

A wild guess is that the diff fluctuation is the difference between cold and hot, i.e the first does all the algo method fetching, while the second has all the methods in the method store/cache. 

This differs a *lot* from pre-3.0, where all methods are constant arrays or arrays that are allocated much much earlier.

**Comment by levitte** [comment]
If "first" and "second" are two separate runs of `openssl speed`, my guess is obviously not relevant

**Comment by yxungh** [comment]
Thanks!

**Comment by yxungh** [comment]
Thanks!
