### ISSUE TITLE
There should be no algorithm specific ifndef OPENSSL_NO_ALGORITHM in libssl

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#13616]
As crypto implementations are provided and the libssl should now call high level APIs from libcrypto only the algorithm specific ifndefs should not be present in libssl code at all.

This of course requires properly handling cases where an algorithm supported by libssl is not supported by a provider but that should be already part of the cleanup necessary for libssl support for external providers.

**Comment by paulidale** [comment]
In general this should happen. There might be exceptions in the deprecated files.  These exceptions are permitted.

**Comment by mattcaswell** [comment]
Fix for this in #13916
