### ISSUE TITLE
which version of openssl does libssl.so.10 correspond to?  

### ISSUE THREAD

**Issue by KiAlexander** [openssl/openssl#13619]
I need libssl.so.10, but when I tried to  install openssl1.0.0/1.0.2/1.1 to link its libssl.so to libssl.so.10, I met different problems like "undefined symbol: EVP_idea_cbc". so which version of openssl does libssl.so.10 correspond to?

**Comment by levitte** [comment]
That, I'm afraid, depends on which operating system (distribution if we're talking Linux) this is on. I assume libssl.so.10 came from a package of some sort. That package probably has the information you seek.

Be very careful trying to replace a packaged libssl with your own build.

**Comment by t8m** [comment]
We are using .10 suffix in libssl/libcrypto SONAME in Fedora/RHEL/CentOS for the openssl-1.0.2 libraries. If you are trying to use some 3rd party software built for these distributions that needs libssl.so.10 then I'd recommend extracting libssl.so.10 and libcrypto.so.10 from a CentOS 7 openssl rpm package.
