### ISSUE TITLE
Deprecate EVP_PKEY_new_CMAC_key_ex() and EVP_PKEY_new_CMAC_key() ?

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#13628]
Considering that we discourage doing MAC via EVP_PKEY, it only seems fitting to discourage the use of these functions.

**Comment by richsalz** [comment]
I'm willing to make a PR for this if it should happen for 3.0 (which seems like yes, but confirmation would be appreciated).

**Comment by levitte** [comment]
You got it, thanks for offering

**Comment by richsalz** [comment]
Note that ```EVP_PKEY_new_CMAC_key_ex``` was added in 3.0 so it can just be removed.

**Comment by richsalz** [comment]
I had forgotten about this and am just now getting back to it.

What function replaces ```EVP_PKEY_NEW_CMAC_key```? Since that function takes a ```EVP_CIPHER*``` parameter, I'm not sure what you were thinking should be done here, @levitte?

**Comment by t8m** [comment]
> I had forgotten about this and am just now getting back to it.
> 
> What function replaces `EVP_PKEY_NEW_CMAC_key`? Since that function takes a `EVP_CIPHER*` parameter, I'm not sure what you were thinking should be done here, @levitte?

You just would not use the EVP_PKEY interface for handling CMAC and HMAC at all and use EVP_MAC API instead. You would just set the OSSL_MAC_PARAM_CIPHER param on the EVP_MAC_CTX.

**Comment by t8m** [comment]
Deprecation (and removal) done now on master with #13829
