### ISSUE TITLE
OSSL_DECODER_CTX_new_by_EVP_PKEY API 

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#13621]
The OSSL_DECODER_CTX_new_by_EVP_PKEY documentation shows the first parameter as EVP_PKEY * and the code has it as EVP_PKEY **.

The decoder API is inconsistent with respect to the encoder API which has EVP_PKEY *.
The API should not logically be returning a different pointer to the caller.

**Comment by t-j-h** [comment]
OSSL_DECODER_CTX_new_by_EVP_PKEY has a libctx parameter, OSSL_ENCODER_CTX_new_by_EVP_PKEY does not. 
That inconsistency should also be fixed.

**Comment by t-j-h** [comment]
The DECODER_from_<whatever> APIs really should have the EVP_PKEY return pointer on those functions rather than setting that up in the DECODE_CTX_new call ... and the naming of new_by really makes no sense if this is an output only parameter.

This whole API needs review.

**Comment by levitte** [comment]
> OSSL_DECODER_CTX_new_by_EVP_PKEY has a libctx parameter, OSSL_ENCODER_CTX_new_by_EVP_PKEY does not.
That inconsistency should also be fixed.

This was discussed a bit in #13544, FYI.  The basic question is, where to pick the library context from...  if there's an input parameter that already holds it, why do we need an explicit one?  The follow up question is, if the explicit and the implicit library context differ, what do we do?  If that's an error, why do we need to have the users pass an explicit one?  I'd say that these are relevant questions to ask to determine what the API should look like, to have something that's flexible enough, while not being too confusing functionally.

> The DECODER_from_ APIs really should have the EVP_PKEY return pointer on those functions rather than setting that up in the DECODE_CTX_new call ... and the naming of new_by really makes no sense if this is an output only parameter.

Yeah ok...  so then we get to the question, what should it look like when more types move to being provider supported?  Say that we move the base X509 functionality to providers, what then?  This is something I had clearly on my mind from the start, and I think that it *is* realistic to imagine a future with X509 being provided.  How far or how near, I haven't the faintest idea...

**Comment by levitte** [comment]
Please don't misunderstand my comments as a pushback on the idea of reviewing the API.  It's food for thought.

**Comment by levitte** [comment]
Early morning thoughts: I could imagine a function `EVP_PKEY_from_bio()`...  the line of thought I have is that most of the rest of OSSL_DECODER would remain, as they are generic building blocks that helps making decoders for specific types.

This is, of course, more food for thought.

**Comment by mattcaswell** [comment]
This has been done.
