### ISSUE TITLE
overload engine for openssl dgst -sign 

### ISSUE THREAD

**Issue by SyedElec** [openssl/openssl#1362]
Hi,

I'm currently working on an engine and I have a question about 'overload' the openssl dgst -sign ... command line using this engine.

I can overload the openssl dgst only (for digests) using ENGINE_set_digests but how overload the whole command openssl dgst -sign 

for example : 
`openssl dgst -md5 -binary -engine myengine -keyform engine -sign key.pem -out dgst.sig file`

Thank you.

**Comment by mattcaswell** [comment]
Please raise this issue on the openssl-users email list rather than here. Sign up details:

mta.openssl.org.

**Comment by mattcaswell** [comment]
Closing this ticket.
