### ISSUE TITLE
i2c_ASN1_INTEGER is removed from public headers in 1.1.0

### ISSUE THREAD

**Issue by ngg** [openssl/openssl#1363]
Was this an intended modification?

I've found lots of programs that use it.
Calling i2d_ASN1_INTEGER and removing the tag and length is a valid workaround of course but it's not really comfortable.

**Comment by richsalz** [comment]
I believe it was intended (still looking for the commit id), but it was apparently a mistake.  We will fix for 1.1

**Comment by richsalz** [comment]
From the team:  if they only care about positive integers then can just retrieve the contents of the ASN1_INTEGER with ASN1_STRING_length() and ASN1_STRING_data(). If this is precursor to converting it to a BIGNUM then ASN1_INTEGER_to_BN() should be called instead.

So, what are you trying to do?

**Comment by ngg** [comment]
We are using it mostly for two reasons.

One is that our OCSP URLs contain the hexencode(i2c_ASN1_INTEGER(certificate's serial)) as a suffix.

The other is that we do not want to pass OpenSSL objects like ASN1_INTEGERs or BIGNUMs around in our codebase (the openssl library is only included and used in a small wrapper layer), but we need to deal with certificate serials in a few places, so we pass them around in byte vectors in this format (this is an only in-memory usage, it can be switched to anything else easily).

**Comment by richsalz** [comment]
Does compatibility with the old form matter? If serial numbers are always positive (standards require it when generating certificates but they also say we must tolerate zero or negative serial numbers) then representing it in big endian form would work: that's directly available from ASN1_STRING_data() on the ASN1_INTEGER.

If you want 100% compatibility with the old form then on encode they can check if the MSB is set in the first byte and prepend a zero.

If you really need to handle negative and positive serial numbers then d2i_ASN1_INTEGER and i2d_ASN1_INTEGER and skipping the header are the only real way to do things. That's not hard to do though either manually or using some of the lower level ASN.1 routines: ask on the openssl-users mailing list.
