### ISSUE TITLE
Ubuntu 20.04 different version

### ISSUE THREAD

**Issue by ashrafalzyoud** [openssl/openssl#13633]
```
root@redmine:~# openssl version 
OpenSSL 1.1.1c  28 May 2019
root@redmine:~# apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.1.1f-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@redmine:~# 
```

**Comment by romen** [comment]
Likely you might have a custom installation in your `PATH`.
Try checking with `which openssl` likely it is pointing to `/usr/local/bin/openssl` (but it is also possible you installed from source on top of the packaged version).

Be very careful when installing from source, as most distributions treat openssl as a system package.

**Comment by ashrafalzyoud** [comment]
```
root@redmine:~# which openssl
/usr/local/bin/openssl
root@redmine:~# openssl version 
OpenSSL 1.1.1c  28 May 2019
root@redmine:~# apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.1.1f-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@redmine:~# 
```
how i can fix it?

**Comment by romen** [comment]
> how i can fix it?

So, you have a custom installation in `/usr/local/` that is taking precedence over the packaged version.
If you still have the original build tree, you should be able to run `make uninstall` inside of it to undo the installation.

If you have removed the original build folder, you could try to rebuild it from source using exactly the same sequence of operations and arguments you followed during installation and running `make uninstall` instead of `make install`.

**Comment by ashrafalzyoud** [comment]
im not install it from any folder
its installl automatic as package from ubuntu 20.04, im not mack any install just from apt-get update or upgrade

**Comment by ashrafalzyoud** [comment]
im search to my problem, i found one tell me update your version openssl
 this my problem
```
Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system
doesn't have the CA certificates needed for verification. For information about OpenSSL
certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources
and change 'https' 
```

**Comment by romen** [comment]
> im not install it from any folder
> its installl automatic as package from ubuntu 20.04, im not mack any install just from apt-get update or upgrade

This is incorrect, the official ubuntu packages of openssl do not install in `/usr/local/`, either you manually or some script or build system (e.g. `homebrew` or similar ones) installed a version of `openssl` in `/usr/local`.

Unfortunately we have no way of determining how you got this custom installation in `/usr/local` so there is no simple answer we can give you on how to uninstall it: you should refer to the documentation of the method you used to install it to discover how to properly uninstall.

**Comment by ashrafalzyoud** [comment]
if im unistall it its effect to my nginx or mysql or passenger ??
or openssl its independent

**Comment by romen** [comment]
> im search to my problem, i found one tell me update your version openssl
> this my problem
> 
> ```
> Could not verify the SSL certificate for https://rubygems.org/.
> There is a chance you are experiencing a man-in-the-middle attack, but most likely your system
> doesn't have the CA certificates needed for verification. For information about OpenSSL
> certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources
> and change 'https' 
> ```

This seems to be unrelated to the installed version of OpenSSL, it seems like something is wrong in your installation with respect to local trusted certificates, which are not distributed as part of OpenSSL.

To fix this separate issue your best bet is to contact support channels of ruby/rubygems/etc. : the mentioned http://bit.ly/ruby-ssl resource offers some pointers.

> if im unistall it its effect to my nginx or mysql or passenger ??
> or openssl its independent

It really depends on how nginx/mysql/passenger or any other software was built and installed.
If they were built/configured to depend on the custom version installed in `/usr/local` then yes, if they are strictly versions installed from Ubuntu packages, then they were built to depend on the packaged version of `openssl`, and the custom installation in `/usr/local` might actually interfere with those.

**Comment by romen** [comment]
Anyway, I am closing this as the follow-up questions are not really relevant for the officially supported installation method.

The recommended way of installing OpenSSL from source is documented in `INSTALL` and contains disclaimers about installing from source in a system path.

In general linux usage recommendations, if you are building (directly or indirectly) packages from sources outside the mechanisms tracked by the distribution-specific package management (especially when they replace functionality of distribution-provided packages) you might want to install them in a separate non-default prefix.
It is then user responsibility to manage the cross-dependencies of installations inside the custom prefix.

**Comment by ashrafalzyoud** [comment]
How to switch OpenSSL version  ubuntu 20.04
