### ISSUE TITLE
Creating an OCSP extension via X509V3_EXT_conf_nid() seems to have regressed in alpha9

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#13636]
I have a test that does basically this:

```
X509V3_EXT_conf_nid(NULL, NULL, NID_info_access, "OCSP;URI:http://ocsp.ex1.com:2560,OCSP;URI:http://ocsp.ex2.com:2567");
```

(Obviously those are just URI meant to exercise the parsing paths, not actual OCSP servers.)

This seems broken starting in alpha9.

I was looking through the commit history for v3_info.c and I suspect https://github.com/openssl/openssl/commit/a150f8e1fcc38752fef4d7c75d765d8efc7d46d6. It seems like there was semantically meaningful refactoring done there outside of just the error reporting. We used to do OBJ_txt2obj() on cnf->name (indirected through a string copy), now it's on cnf->value.

**Comment by t-j-h** [comment]
It does indeed seem to be that commit - and https://github.com/openssl/openssl/commit/a150f8e1fcc38752fef4d7c75d765d8efc7d46d6#diff-0e144f730d183d7a7c685df62d4be7049c3842df24a491c5a103365a2770cc96 is the section in isolation for others to look at.

**Comment by jwalch** [comment]
It took me a bit to realize what the old objtmp was accomplishing. I'd tried merely switching cnf->value to cnf->name and that didn't work. I believe what this code is actually trying to do as relates to my example input string is call OBJ_txt2obj() on the string "OCSP" with a NULL terminator, and cnf->name has more than that in it; hence the strchr & pointer arithmetic business.
