### ISSUE TITLE
make install fails sometimes with -j8

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#1364]
Make install fails sometimes:

> /usr/bin/make -f Makefile install DESTDIR=`pwd`/debian/tmp
> make[1]: Entering directory '/home/bigeasy/openssl/openssl-1.1.0-pre5'
> /usr/bin/make depend && /usr/bin/make _all
> *** Installing development files
> *** Installing manpages
> *** Installing HTML manpages
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp'
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr'
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib'
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/ssl'
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/ssl/certs'
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/x86_64-linux-gnu'
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/x86_64-linux-gnu/openssl-1.1'
> created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/x86_64-linux-gnu/openssl-1.1/engines-1.1'
 >created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/bin'
 >created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/include'
 >created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/include/openssl'
 >created directory `/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/ssl/private'
 >*** Installing engines
 >install engines/capi.so -> /home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/x86_64-linux-gnu/openssl-1.1/engines-1.1/capi.so
> install ./apps/CA.pl -> /home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/ssl/misc/CA.pl
> install ./include/openssl/aes.h -> /home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/include/openssl/aes.h
> cp: cannot create regular file '/home/bigeasy/openssl/openssl-1.1.0-pre5/debian/tmp/usr/lib/ssl/misc/CA.pl.new': No such file or directory
> Makefile:222: recipe for target 'install_ssldirs' failed
> make[1]: *** [install_ssldirs] Error 1
|>make[1]: *** Waiting for unfinished jobs....

Sometimes it passes, sometimes it fails and when it fails it is always complaining the same way about CA.pl.new. My current workaround is to use -j1 during install. I have no idea what is causing this.
This popped up somewhere between fe964f0c88f6780fd30b26e306484b981b0a8480 and 976ef6adcc157233fb641ca99e2424630ef1814f

Sebastian

**Comment by levitte** [comment]
The install target hasn't been carefully crafted to handle parallell execution, so `-j1` (or no `-j` at all) is the right approach.

That being said, it shouldn't be too difficult to craft this a bit more carefully.  I'll look into it.

**Comment by levitte** [comment]
Fix in #1375, please try it out.

**Comment by levitte** [comment]
#1375 merged, I believe it does fix the issue presented here, so closing this.  Please create a new issue if you find more.

**Comment by sebastianas** [comment]
On 2016-08-01 15:57:14 [-0700], Richard Levitte wrote:
> #1375 merged, I believe it does fix the issue presented here, so closing this.  Please create a new issue if you find more.

Thank you. I can't map your changes to the root problem but it seems to
be gone :)

Sebastian
