### ISSUE TITLE
Openssl fails to compile on windows 10.

### ISSUE THREAD

**Issue by LaurentDuroisin7601** [openssl/openssl#13646]
Hi! I'm trying to compile openssl but I've this error : rm -f apps/libapps.a
process_begin: CreateProcess(NULL, rm -f apps/libapps.a, ...) failed.
make (e=2): Le fichier spécifié est introuvable.
Makefile:2365: recipe for target 'apps/libapps.a' failed
mingw32-make[1]: *** [apps/libapps.a] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/Laurent/Downloads/openssl-master/openssl-master'
Makefile:1406: recipe for target 'build_sw' failed
mingw32-make: *** [build_sw] Error 2
It seems there are missing files.

**Comment by levitte** [comment]
Is this in a mingw shell or in cmd.exe?

**Comment by t8m** [comment]
No response from reporter.
