### ISSUE TITLE
The EVP_PKEY-DH(7) docs are confusing

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13644]
The introductory paragraph to EVP_PKEY-DH(7) says this:

> For B<DH> FFC key agreement, two classes of domain parameters can be used:
"safe" domain parameters that are associated with approved named safe-prime
groups, and a class of "FIPS 186-type" domain parameters. FIPS 186-type domain
parameters should only be used for backward compatibility with existing
applications that cannot be upgraded to use the approved safe-prime groups.

This seems really confusing to me:

- The term FFC is not defined (it might be helpful to contrast this with ECDH)
- This seems mainly talking about the DHX key type - but this is on the DH page and DHX doesn't get mentioned anywhere on this page

**Comment by levitte** [comment]
> * The term FFC is not defined (it might be helpful to contrast this with ECDH)

Actually, it is...  just not by us: https://csrc.nist.gov/glossary/term/Finite_Field_Cryptography

And again, it seems like we would need a openssl-glossary(7) (inspired by gitglossary(7))

**Comment by mattcaswell** [comment]
> Actually, it is... just not by us:

Well that's kind of what I meant. Obviously it *is* defined *somewhere* out there! But that doesn't help the reader of this man page.

**Comment by levitte** [comment]
> But that doesn't help the reader of this man page.

So when do we start on openssl-glossary(7)?

**Comment by richsalz** [comment]
It is a good point to spell out acronyms when first used, as in "Finite Field Cryptography (FFC)"

A glossary seems to be a timesink.  Are you going to define TLS X509 ECDH ?  Yuk.

**Comment by levitte** [comment]
> A glossary seems to be a timesink.

We have plenty of glossary already, dispersed all over the manuals, and sometimes duplicated.  For example, do you know which `man something` that'll tell you about PEM?  I believe we have that one in more than one spot, all different.  Also, if anyone wants to explain some term that we use, where do we put that explanation?  That's something everyone has to think about every time we have that, and everyone will come up with their own answer.  *That* is *also* a time sink, and even more so for the user who simply has to be lucky to hit the correct page.

**Comment by levitte** [comment]
I'm not suggesting that someone has to make a *complete* glossary off the bat, but rather that this should be the spot to hit every time we find ourselves wondering "what was FFC again?" or "what was PEM again?"

**Comment by levitte** [comment]
At this point, there *is* a `doc/man7/openssl-glossary.pod`

**Comment by richsalz** [comment]
Close this because of PR #14883 ?
