### ISSUE TITLE
Context gettable/settable nomenclature

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#13654]
Which style should be adopt:

```C
const OSSL_PARAM *EVP_MD_gettable_params(const EVP_MD *md);
const OSSL_PARAM *EVP_MD_gettable_ctx_params(const EVP_MD *md);
const OSSL_PARAM *EVP_MD_CTX_gettable_params(EVP_MD_CTX *ctx);
```

Do we want `EVP_X_CTX_gettable_params` for other types?

This applies to all of the gettable/settable context call types.

**Comment by levitte** [comment]
It could be more fair to mention the calls within the same type of operation:

``` C
const OSSL_PARAM *EVP_MD_settable_ctx_params(const EVP_MD *md);
const OSSL_PARAM *EVP_MD_gettable_ctx_params(const EVP_MD *md);
const OSSL_PARAM *EVP_MD_CTX_settable_params(EVP_MD_CTX *ctx);
const OSSL_PARAM *EVP_MD_CTX_gettable_params(EVP_MD_CTX *ctx);
```

Does this mean that the two would be merged, or will you have to *always* set up a `EVP_MD_CTX` just to get the settable and gettable parameters?  Is that what `apps/list.c` will have to do?

**Comment by t8m** [comment]
Yes, we went through this before and the `EVP_MD_gettable_ctx_params` and `EVP_MD_gettable_params` model is the best we came up with given the constraints.

**Comment by paulidale** [comment]
There is a reason we included `EVP_MD_CTX_gettable_params()` and friends.  They are required.

**Comment by levitte** [comment]
> There is a reason we included `EVP_MD_CTX_gettable_params()` and friends.  They are required.

And?  I haven't said that they shouldn't exist, but we need to be aware that the two forms have *different semantics*, it's not just a simple "choose the style you like"

**Comment by t8m** [comment]
Yes, EVP_MD_CTX is needed because the EVP_MD_CTX is overloaded with being not just a digest context but also signature/verification context.

It would have to be similar for the MAC or KDF  if we wanted to have the strict set params call done via matching the gettables.

**Comment by t-j-h** [comment]
The full list of like functions:

```
const OSSL_PARAM *ossl_provider_gettable_params(const OSSL_PROVIDER *prov);
const OSSL_PARAM *OSSL_DECODER_gettable_params(OSSL_DECODER *decoder);
const OSSL_PARAM *OSSL_ENCODER_gettable_params(OSSL_ENCODER *encoder);
const OSSL_PARAM *EVP_MD_gettable_params(const EVP_MD *digest);
const OSSL_PARAM *EVP_MD_gettable_ctx_params(const EVP_MD *md);
const OSSL_PARAM *EVP_MD_CTX_gettable_params(EVP_MD_CTX *ctx);
const OSSL_PARAM *EVP_CIPHER_gettable_params(const EVP_CIPHER *cipher);
const OSSL_PARAM *EVP_CIPHER_gettable_ctx_params(const EVP_CIPHER *cipher);
const OSSL_PARAM *EVP_MAC_gettable_params(const EVP_MAC *mac);
const OSSL_PARAM *EVP_MAC_gettable_ctx_params(const EVP_MAC *mac);
const OSSL_PARAM *EVP_RAND_gettable_params(const EVP_RAND *rand);
const OSSL_PARAM *EVP_RAND_gettable_ctx_params(const EVP_RAND *rand);
const OSSL_PARAM *EVP_KEYMGMT_gettable_params(const EVP_KEYMGMT *keymgmt);
const OSSL_PARAM *EVP_PKEY_CTX_gettable_params(EVP_PKEY_CTX *ctx);
const OSSL_PARAM *EVP_SIGNATURE_gettable_ctx_params(const EVP_SIGNATURE *sig);
const OSSL_PARAM *EVP_ASYM_CIPHER_gettable_ctx_params(const EVP_ASYM_CIPHER *ciph);
const OSSL_PARAM *EVP_KEM_gettable_ctx_params(const EVP_KEM *kem);
const OSSL_PARAM *EVP_PKEY_gettable_params(EVP_PKEY *pkey);
const OSSL_PARAM *EVP_KEYEXCH_gettable_ctx_params(const EVP_KEYEXCH *keyexch);
const OSSL_PARAM *EVP_KDF_gettable_params(const EVP_KDF *kdf);
const OSSL_PARAM *EVP_KDF_gettable_ctx_params(const EVP_KDF *kdf);
const OSSL_PARAM *OSSL_PROVIDER_gettable_params(const OSSL_PROVIDER *prov);
```

**Comment by t-j-h** [comment]
Comment that gettable_params should belong together in the name and we should not say gettable_ctx_params but perhaps gettable_params_from_ctx or something like that.
