### ISSUE TITLE
Mechanism to define custom propq in openssl apps

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#13656]
The `app_get0_propq` (from apps/lib/apps.c) is used throughout many openssl apps to define propq used to fetch the algorithms. Currently, it just returns NULL and its comment says "TODO(3.0): Make this an environment variable if required".
If a provider is used that does not implement all algorithms (e.g. reuses STORE from the default one) the propq needs to be defined to fetch the right implementation. (One such example has been discussed in #13539.) Therefore, the current app_get0_propq implementation is insufficient.

What should be the right way for a user to specify the propq when executing an openssl command? I'd prefer either a command line argument or (if no more args can be added) the config file, so that all configuration parameters are on a single place. Having providers defined as command line args (`-provider`) and then propq as an environment variable feels inconsistent.

**Comment by levitte** [comment]
`doc/man5/config.pod` says this:

```
   EVP Configuration
       The name alg_section in the initialization section names the section
       containing algorithmic properties when using the EVP API.

       Within the algorithm properties section, the following names have
       meaning:

       default_properties
           The value may be anything that is acceptable as a property query
           string for EVP_set_default_properties().
```

Does that answer your question?

**Comment by gotthardp** [comment]
Oh, yes. Thank you! In that case the `app_get0_propq` needs to be updated to read this from the config. I will (try to) propose a PR.

**Comment by t8m** [comment]
IMO those two should be something different. There should be a default property query in the config file that is being read when the libcrypto is loaded and initialized. And then there should be a additional way how to specify a non-default propq in the similar way the -provider can be specified for the applications. So yes, there should be a -propquery option that would allow you to override the default propquery from the config file.

**Comment by mattcaswell** [comment]
> In that case the app_get0_propq needs to be updated to read this from the config

The default propq from the config file should already be being used, so no changes should be needed to support it. Note that the implicit default propq is different to any explicit propq that is provided during individual fetches (which is what app_get0_propq is for). The default propq and any explicit propq are merged during the fetch.

> IMO those two should be something different.

This is my view too. I think a "-propquery" option would be ideal.

**Comment by paulidale** [comment]
Agreed, a `-propquery` command line option seems like the way forward.  What about `-prop-query` ?

**Comment by mattcaswell** [comment]
Either is fine by me.

**Comment by paulidale** [comment]
This won't block beta1 but if a PR is created, it would likely get in.
