### ISSUE TITLE
SM4-GCM Mode Support

### ISSUE THREAD

**Issue by ssagittis** [openssl/openssl#13667]
Please support sm4-gcm mode pls

**Comment by paulidale** [comment]
This is slightly being a good first issue I suspect.

The place I'd start would be the ARIA GCM code in `providers/implementations/ciphers`.
Copy the three files, and change ARIA to SM4 throughout.
Then add the appropriate lines to `providers/defltprov.c`.

Assuming that the cipher suite numbers have been officially allocated, adding SM4-GCM cipher suites to TLS would again be following the ARIA example.

**Comment by mattcaswell** [comment]
> Assuming that the cipher suite numbers have been officially allocated, adding SM4-GCM cipher suites to TLS would again be following the ARIA example.

SM4 with GCM ciphersuite numbers have been allocated for TLSv1.3 (https://datatracker.ietf.org/doc/draft-yang-tls-tls13-sm-suites/) but not for TLSv1.2. With ARIA its the other way around: there are no ARIA TLSv1.3 ciphersuites to copy from unfortunately (although there are some TLSv1.2 ones).

**Comment by paulidale** [comment]
Thanks @mattcaswell, I knew about the TLS 1.3 draft but wasn't sure about 1.2.  I'll edit my response's part about TLS.

**Comment by jim-rowan** [comment]
Is there line of sight on implementing this feature?  I am looking for Python Cryptography support for SM4 GCM and that relies on OpenSSL.

**Comment by t8m** [comment]
> Is there line of sight on implementing this feature?

There are no current plans to do this by the team members but if external contributor submitted a PR it would be welcome.

**Comment by zzl-360** [comment]
there is already SM4-GCM  code in providers/implementations/ciphers/cipher_sm4_gcm.c,but missing evp_sm4_gcm.

**Comment by paulidale** [comment]
There never will be an evp_sm4_gcm() function.  Instead you should call EVP_CIPHER_fetch(NULL, "sm4-gcm", NULL) to access the cipher.  Or something similar if you've got a library context or want a property query included.

**Comment by paulidale** [comment]
Closing this because SM4-GCM is present.

**Comment by braveryHuang** [comment]
Hi, i using EVP_CIPHER_fetch(NULL, "sm4-gcm", NULL), but didn't work, i was using version 3.0.3.
Did sm4-gcm really existed ?

**Comment by t8m** [comment]
sm4-gcm is implemented only in the master branch and will be in 3.1 release.

**Comment by braveryHuang** [comment]
> sm4-gcm is implemented only in the master branch and will be in 3.1 release.

Thank you for your prompt reply.

**Comment by jackxiaoer** [comment]
@paulidale  thank you, EVP_CIPHER_fetch(NULL, "sm4-gcm", NULL), it work.
