### ISSUE TITLE
How to build openssl static libs libssl.a & libcrypto.a compliant to glibc 2.17

### ISSUE THREAD

**Issue by sudhirnir** [openssl/openssl#13665]
Hi openssl experts,

I want to build static libraries of openssl which is compatible with glibc 2.17. I want to do this on centos7 with gcc 4.8.5 20150623.

My question is, 
1) Which openssl source should i use to achieve this? (compatible with glibc 2.17) 
2) What options should i provide to ./config to create  libssl.a & libcrypto.a
2) What  options should i use to make?

Right now when i use ./config -shared & make, it is only creating libcrypto.a & not libssl.a

Hope I will get the help sooner 👍 
Thanks

**Comment by mattcaswell** [comment]
I see you asked the same question on SO. I'll refer you to the excellent answer by dave_thompson_085 there:

https://stackoverflow.com/a/65247812/1946679

**Comment by sudhirnir** [comment]
> I see you asked the same question on SO. I'll refer you to the excellent answer by dave_thompson_085 there:
> 
> https://stackoverflow.com/a/65247812/1946679

Thanks @mattcaswell. My main focus is to build openssl static libs libssl.a & libcrypto.a which is compatible with glibc 2.17.& with gcc 4.8.5. I have ommitted requirement of FIPS compliance. I have edited question on SO as well accordingly.
