### ISSUE TITLE
Magma Implementation

### ISSUE THREAD

**Issue by pedroalbanese** [openssl/openssl#13674]
Hi,

How to compile against GOST Engine branch vt_alt_openssl_1_0_2_alt? I need Kuznyechik & Magma Implementations and -pbkdf2 function.

Thanks in advance.

0wner@AMD-W7 /cygdrive/h/PRGM/Linux/openssl-1.0.2t/engines/ccgost
$ make
[  3%] Building C object CMakeFiles/gost.dir/gost_ec_keyx.c.o
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c: In function ‘VKO_compute_key’:
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:32:43: error: ‘NID_id_GostR3411_2012_512’ undeclared (first use in this function); did you mean ‘NID_id_GostR3410_2001’?
   32 |     int effective_dgst_nid = (dgst_nid == NID_id_GostR3411_2012_512) ?
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           NID_id_GostR3410_2001
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:32:43: note: each undeclared identifier is reported only once for each function it appears in
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:33:9: error: ‘NID_id_GostR3411_2012_256’ undeclared (first use in this function); did you mean ‘NID_id_GostR3410_2001_cc’?
   33 |         NID_id_GostR3411_2012_256 : dgst_nid;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |         NID_id_GostR3410_2001_cc
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:44:15: error: implicit declaration of function ‘OPENSSL_zalloc’; did you mean ‘OPENSSL_malloc’? [-Werror=implicit-function-declaration]
   44 |     databuf = OPENSSL_zalloc(buf_len);
      |               ^~~~~~~~~~~~~~
      |               OPENSSL_malloc
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:44:13: error: assignment to ‘unsigned char *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   44 |     databuf = OPENSSL_zalloc(buf_len);
      |             ^
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:78:13: error: implicit declaration of function ‘EVP_MD_CTX_new’; did you mean ‘EVP_MD_CTX_init’? [-Werror=implicit-function-declaration]
   78 |     mdctx = EVP_MD_CTX_new();
      |             ^~~~~~~~~~~~~~
      |             EVP_MD_CTX_init
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:78:11: error: assignment to ‘EVP_MD_CTX *’ {aka ‘struct env_md_ctx_st *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   78 |     mdctx = EVP_MD_CTX_new();
      |           ^
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:96:5: error: implicit declaration of function ‘EVP_MD_CTX_free’; did you mean ‘EVP_MD_CTX_create’? [-Werror=implicit-function-declaration]
   96 |     EVP_MD_CTX_free(mdctx);
      |     ^~~~~~~~~~~~~~~
      |     EVP_MD_CTX_create
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c: In function ‘pkey_GOST_ECcp_encrypt’:
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:159:21: error: ‘NID_id_tc26_gost_28147_param_Z’ undeclared (first use in this function)
  159 |         OBJ_nid2obj(NID_id_tc26_gost_28147_param_Z);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/gost.dir/build.make:83: CMakeFiles/gost.dir/gost_ec_keyx.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:183: CMakeFiles/gost.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

0wner@AMD-W7 /cygdrive/h/PRGM/Linux/openssl-1.0.2t/engines/ccgost
$

0wner@AMD-W7 /cygdrive/h/PRGM/Linux/openssl-1.0.2t/engines/ccgost
$ make
[  3%] Building C object CMakeFiles/gost.dir/gost_ec_keyx.c.o
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c: In function ‘VKO_compute_key’:
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:32:43: error: ‘NID_id_GostR3411_2012_512’ undeclared (first use in this function); did you mean ‘NID_id_GostR3410_2001’?
   32 |     int effective_dgst_nid = (dgst_nid == NID_id_GostR3411_2012_512) ?
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           NID_id_GostR3410_2001
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:32:43: note: each undeclared identifier is reported only once for each function it appears in
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:33:9: error: ‘NID_id_GostR3411_2012_256’ undeclared (first use in this function); did you mean ‘NID_id_GostR3410_2001_cc’?
   33 |         NID_id_GostR3411_2012_256 : dgst_nid;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |         NID_id_GostR3410_2001_cc
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:44:15: error: implicit declaration of function ‘OPENSSL_zalloc’; did you mean ‘OPENSSL_malloc’? [-Werror=implicit-function-declaration]
   44 |     databuf = OPENSSL_zalloc(buf_len);
      |               ^~~~~~~~~~~~~~
      |               OPENSSL_malloc
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:44:13: error: assignment to ‘unsigned char *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   44 |     databuf = OPENSSL_zalloc(buf_len);
      |             ^
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:78:13: error: implicit declaration of function ‘EVP_MD_CTX_new’; did you mean ‘EVP_MD_CTX_init’? [-Werror=implicit-function-declaration]
   78 |     mdctx = EVP_MD_CTX_new();
      |             ^~~~~~~~~~~~~~
      |             EVP_MD_CTX_init
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:78:11: error: assignment to ‘EVP_MD_CTX *’ {aka ‘struct env_md_ctx_st *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   78 |     mdctx = EVP_MD_CTX_new();
      |           ^
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:96:5: error: implicit declaration of function ‘EVP_MD_CTX_free’; did you mean ‘EVP_MD_CTX_create’? [-Werror=implicit-function-declaration]
   96 |     EVP_MD_CTX_free(mdctx);
      |     ^~~~~~~~~~~~~~~
      |     EVP_MD_CTX_create
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c: In function ‘pkey_GOST_ECcp_encrypt’:
/cygdrive/h/PRGM/Linux/engine-openssl_1_1_0_release1/gost_ec_keyx.c:159:21: error: ‘NID_id_tc26_gost_28147_param_Z’ undeclared (first use in this function)
  159 |         OBJ_nid2obj(NID_id_tc26_gost_28147_param_Z);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/gost.dir/build.make:83: CMakeFiles/gost.dir/gost_ec_keyx.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:183: CMakeFiles/gost.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

0wner@AMD-W7 /cygdrive/h/PRGM/Linux/openssl-1.0.2t/engines/ccgost
$

How to apply patches? It's manually?

**Comment by beldmit** [comment]
OpenSSL project has nothing to do with this request. Please let's discuss it within the gost-engine project.
