### ISSUE TITLE
Makefile: two issues related to `install_fips` resp. `uninstall_fips` target

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#13680]
### make install_fips

It seems like the rule for the `install_fips` target calls `openssl` without providing a path.

https://github.com/openssl/openssl/blob/52c6c12c1cad6f1046b34f4139d1aa3e967a5530/Configurations/unix-Makefile.tmpl#L562-L567

In my case, the openssl (1.1.1g) application from my Linux distribution is called, which does not recognize the `fipsinstall` command:

```
Invalid command 'fipsinstall'; type "help" for a list.
make: *** [Makefile:3362: install_fips] Error 1
```

### make uninstall_fips

It does not seem right to me to have the `uninstall_fips` target depend on `uninstall_sw`, because it should be allowed to remove the FIPS module configuration without uninstalling the entire software.

https://github.com/openssl/openssl/blob/52c6c12c1cad6f1046b34f4139d1aa3e967a5530/Configurations/unix-Makefile.tmpl#L569-L572

Instead, the dependency should probably be the other way around: uninstall the FIPS module configuration as part of uninstalling the software.

### Attempted Fix

I tried to use `$(DESTDIR)$(INSTALLTOP)/bin/openssl`, but I got shared library issues

```
opt/openssl-dev/bin/openssl: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
and I wasn't sure how to address them correctly, i.e. whether I should set the `LD_LIBRARY_PATH` or use the wrap.pl script and the not-yet-installed openssl app from the source tree instead.

Also, I had problems with my Perl installation (issue #13679), so I gave up.

```diff
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index 342e46d24d..d7acecccc4 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -552,7 +552,7 @@ depend:
 
 install_sw: install_dev install_engines install_modules install_runtime
 
-uninstall_sw: uninstall_runtime uninstall_modules uninstall_engines uninstall_dev
+uninstall_sw: uninstall_runtime uninstall_fips uninstall_modules uninstall_engines uninstall_dev
 
 install_docs: install_man_docs install_html_docs
 
@@ -562,11 +562,12 @@ uninstall_docs: uninstall_man_docs uninstall_html_docs
 install_fips: install_sw
        @$(ECHO) "*** Installing FIPS module configuration"
        @$(ECHO) "fipsinstall $(DESTDIR)$(MODULESDIR)/$(FIPSMODULENAME).cnf"
-       @openssl fipsinstall -module $(DESTDIR)$(MODULESDIR)/$(FIPSMODULENAME) \
+       @$(DESTDIR)$(INSTALLTOP)/bin/openssl fipsinstall \
+               -module $(DESTDIR)$(MODULESDIR)/$(FIPSMODULENAME) \
                -out $(DESTDIR)$(MODULESDIR)/$(FIPSMODULENAME).cnf \
                -macopt 'key:$(FIPSKEY)'
 
-uninstall_fips: uninstall_sw
+uninstall_fips:
        @$(ECHO) "*** Uninstalling FIPS module configuration"
        @$(ECHO) "$(RM) $(DESTDIR)$(MODULESDIR)/$(FIPSMODULENAME).cnf"
        @$(RM) $(DESTDIR)$(MODULESDIR)/$(FIPSMODULENAME).cnf
```

**Comment by levitte** [comment]
`./util/wrap apps/openssl fipsinstall ...`

That's the safest bet.

**Comment by mspncp** [comment]
Ok, I can make  a PR for it, if you help me get my perl problem fixed first.

**Comment by t-j-h** [comment]
As noted the other issue is key: should be hexkey:

**Comment by mspncp** [comment]
See #13684.
