### ISSUE TITLE
`rsa -outform PVK` fails with `check_bitlen_rsa:unsupported key components` when using 1.1.0 tip

### ISSUE THREAD

**Issue by vszakats** [openssl/openssl#1368]
Using latest `master` branch, configured with `./Configure darwin64-x86_64-cc no-shared no-unit-test`

Command:
```
openssl genrsa 2048 | openssl rsa -outform PVK -passout pass:test > test.pvk
```
fails with:
```
writing RSA key
unable to write key
140735153328128:error:0908307E:PEM routines:check_bitlen_rsa:unsupported key components:crypto/pem/pvkfmt.c:531:
```

whereas with 1.0.2h (using default Homebrew build), a valid-looking `test.pvk` is output.

Not sure what to make out of this, possibly:
- a required, but disabled-by-default component has to be manually enabled, even though PVK output itself is allowed.
- the error should have been there in 1.0.2h, but wrong output was silently created.
- the error is bogus.

**Comment by mattcaswell** [comment]
This is a 1.1.0 bug. Fix on the way.

**Comment by mattcaswell** [comment]
Fixed in latest HEAD. Closing this.
