### ISSUE TITLE
Before using EVP_PKEY_free, I want to clear sensitive memory information

### ISSUE THREAD

**Issue by yxungh** [openssl/openssl#13695]
I use PEM_read_bio_PrivateKey to return EVP_PKEY.

Before using EVP_PKEY_free, I want to clear sensitive memory information.
However, other operations are performed before OPENSSL_free in EVP_PKEY_free.

Can OpenSSL do what I want to do now?

```
void EVP_PKEY_free(EVP_PKEY *x)
{
    int i;

    if (x == NULL)
        return;

    CRYPTO_DOWN_REF(&x->references, &i, x->lock);
    REF_PRINT_COUNT("EVP_PKEY", x);
    if (i > 0)
        return;
    REF_ASSERT_ISNT(i < 0);
    EVP_PKEY_free_it(x);
    CRYPTO_THREAD_lock_free(x->lock);
    sk_X509_ATTRIBUTE_pop_free(x->attributes, X509_ATTRIBUTE_free);
    OPENSSL_free(x);
}
```

**Comment by levitte** [comment]
Hmmm, the routines that are called should do a memory cleanse of the key material, I assume that's what you mean.

**Comment by yxungh** [comment]
> Hmmm, the routines that are called should do a memory cleanse of the key material, I assume that's what you mean.

@levitte 
like the private key is key information，I want to clear the key information in the memory before calling EVP_PKEY_free.
Does OpenSSL not encapsulate this interface?

**Comment by yxungh** [comment]
@levitte 
When I call EVP_PKEY_free, do you clear key information in the memory, such as the private key.
I call EVP_PKEY_get1_RSA and then RSA_free.

**Comment by t8m** [comment]
The EVP_PKEY_free is going to clear the key information in the memory before it deallocates the memory occupied by the key.

**Comment by richsalz** [comment]
If you are able to use the secure memory arena, then all private key information is stored there.  This is done at the BIGNUM layer.

**Comment by yxungh** [comment]
ok thanks!
