### ISSUE TITLE
The x509 and req apps should copy X.509 extensions when converting formats

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#13708]
When using the `X509` app to input and output certs (maybe just converting from PEM to DER) or 
when using the `req` app to input and output a CSR, 
any X.590 extensions in the input are copied.

In contract, when using the `x509` app with `-x509toreq` to convert a cert to a CSR or with `-req` for the opposite direction, or
when using the `req` app with `-x509` to convert a CSR to a cert (whereas the opposite direction is not supported),
any X.509 extensions in the input are not taken over. I find this at least counter-intuitive.
I'm currently cleaning up both apps in particular concerning their user guidance and will make clear that no extension are copied.
Yet I believe it would be better if X.509 extensions were copied also when converting between cert and CSR, at least optionally.

BTW, there is a huge overlap between these two apps, while on the other hand there are needless inconsistencies in their use. 
It would have been good, also in terms of code redundancy and maintenance, to have just one app that covers all their (pretty related) use cases.

**Comment by levitte** [comment]
Re the last thing you wrote, I find it clearer that there is a separate command to handle CSRs and a separate command to handle certs.

Regarding the matter of this issue, though, I couldn't agree more.  I vaguely recall that there was a time when automatic copying of extensions was frowned upon, especially for the `ca` command when making a cert (the argument there was that the authority should govern the extensions, not the certificate requestor), and it's possible that this impacted on how the `x509` and `req` commands.

**Comment by richsalz** [comment]
>  vaguely recall that there was a time when automatic copying of extensions was frowned upon,

Normal CA's don't do this, of course. I think there was concern that someone would build a real CA around the OpenSSL app. Perhaps that isn't a concern any more. 👍 

But if you do change the behavior to copy over all extensions in the request, please do it by adding a new flag.  Don't quietly change the existing behavior.

**Comment by FdaSilvaYY** [comment]
It a recurring question : see also #6890, #10458 ( plenty more links here) or an old one #341.

**Comment by DDvO** [comment]
>> BTW, there is a huge overlap between these two apps, while on the other hand there are needless inconsistencies in their use.
It would have been good, also in terms of code redundancy and maintenance, to have just one app that covers all their (pretty related) use cases.

> Re the last thing you wrote, I find it clearer that there is a separate command to handle CSRs and a separate command to handle certs.

Yeah, having just one command to handle both X.509 certs and X.509 cert requests may also be confusing.

For the remaining points in my above more general side remark I've just filed a separate issue: #13720.

**Comment by DDvO** [comment]
> It a recurring question : see also #6890, #10458 ( plenty more links here) or an old one #341.

Oh my goodness, so many requests in that direction for that long time, and nobody has taken the time yet to fix the issue!
Now I see that the issue I've filed here is a generalization of #10458.

I'll fix it right away by adding a `-copy_extensions` option to both `x509` and `req`.

**Comment by kaduk** [comment]
>  I vaguely recall that there was a time when automatic copying of extensions was frowned upon,

I mean, in some sense it still is, and @richsalz hit it on the head with "there was concern that someone would build a real CA around the OpenSSL app".  The first rule of being a CA is "know what you sign", and if you are blindly copying extensions that means you're not looking at them, and thus, don't know that you know what you're signing.

**Comment by DDvO** [comment]
> The first rule of being a CA is "know what you sign"

Of course. Yet this issue is not about the CA (demo) app but about two rather low-level cert/CSR conversion tools.

**Comment by Tbohunek** [comment]
There's a good thing about this bug: it made me study the `openssl` tool in detail. Couldn't believe this was a bug!

**Comment by DDvO** [comment]
Finally, I've found the time to fix this also for the  `x509` app, as part of #13711.
