### ISSUE TITLE
Provider-related digest performance degradation

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#13725]
As denoted in #13578, there was a significant performance degradation in openssl 3.0 measured via `openssl speed`.

The situation is significantly improved by prefetching the digest/cipher object before the benchmark (see #13721). But we still have some benchmark degradation for the provider-based digest.

The `EVP_DigestInit_ex` function invokes the `ENGINE_get_digest_engine` function for each loop. These calls cause significant waste of the time (7% for 16-bytes sha256 blocks). These calls should be eliminated for the provider-based digests.

The  `EVP_DigestFinal_ex` function invokes the `EVP_MD_size` function that fetches data from the provider and also consumes approximately 7% of the benchmark time for 16-bytes sha256 blocks.

**Comment by beldmit** [comment]
The strawman patch to remove the redundant calls of `ENGINE_get_digest_engine` is here. It breaks some SSL tests using TLSProxy 

```
--- a/crypto/evp/digest.c
+++ b/crypto/evp/digest.c
@@ -198,7 +198,7 @@ int EVP_DigestInit_ex(EVP_MD_CTX *ctx, const EVP_MD *type, ENGINE *impl)
         ctx->engine = NULL;
     }
 
-    if (type != NULL && impl == NULL)
+    if (type != NULL && type->prov == NULL && impl == NULL)
         tmpimpl = ENGINE_get_digest_engine(type->type);
 #endif
 
```

**Comment by mattcaswell** [comment]
> These calls cause significant waste of the time (7% for 16-bytes sha256 blocks). 

How are you profiling this?

**Comment by beldmit** [comment]
I use the following command in the build dir:
`LD_LIBRARY_PATH=. valgrind --tool=callgrind ./apps/openssl speed -evp sha256 -bytes 16`
and use `kcachegrind` afterwards.

**Comment by mattcaswell** [comment]
Strangely, I cannot replicate your results. Running with your #13721 branch, I tried the above profile command and I don't see `ENGINE_get_digest_engine` appearing in the list at all!? I think its output is skipped because the time spent is so small. Perhaps something to do with config files?

OTOH, I *do* see significant time spent in `EVP_MD_size()` (for me it was nearly 10%). One significant difference I see between the EVP_CIPHER implementation and the EVP_MD implementation is that the former caches frequently accessed constants in the EVP_CIPHER_fetch call:

https://github.com/openssl/openssl/blob/c4b2c53fadb158bee34aef90d5a7d500aead1f70/crypto/evp/evp_enc.c#L1486-L1499

However there is no such equivalent in the EVP_MD code:

https://github.com/openssl/openssl/blob/c4b2c53fadb158bee34aef90d5a7d500aead1f70/crypto/evp/digest.c#L954-L962

So, when calling `EVP_MD_size()` we go all the way back to the provider every time.

**Comment by beldmit** [comment]
```
LD_LIBRARY_PATH=. valgrind --tool=callgrind ./apps/openssl speed -evp sha256 -bytes 16
==210139== Callgrind, a call-graph generating cache profiler
==210139== Copyright (C) 2002-2017, and GNU GPL'd, by Josef Weidendorfer et al.
==210139== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==210139== Command: ./apps/openssl speed -evp sha256 -bytes 16
==210139== 
==210139== For interactive control, run 'callgrind_control -h'.
Doing sha256 for 3s on 16 size blocks: 170829 sha256's in 2.99s
version: 3.0.0-alpha10-dev
built on: built on: Tue Dec 22 08:52:12 2020 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x7ffaf3ffffebffff:0x27aa
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes
sha256             914.14k
==210139== 
==210139== Events    : Ir
==210139== Collected : 631403581
==210139== 
==210139== I   refs:      631,403,581
```
![Screenshot from 2020-12-22 11-01-07](https://user-images.githubusercontent.com/13785747/102876129-158e1f80-4445-11eb-8181-33d258c75ebc.png)

**Comment by beldmit** [comment]
BTW, didn't you compile the library with -no-deprecated, no-engine, or defining fips-module?
The code is

https://github.com/openssl/openssl/blob/c4b2c53fadb158bee34aef90d5a7d500aead1f70/crypto/evp/digest.c#L180-L203

**Comment by mattcaswell** [comment]
> Strangely, I cannot replicate your results.

Never mind! User error. I'm seeing it now.

**Comment by mattcaswell** [comment]
> The EVP_DigestFinal_ex function invokes the EVP_MD_size function that fetches data from the provider and also consumes approximately 7% of the benchmark time for 16-bytes sha256 blocks.

See fix for this in #13730.

**Comment by mattcaswell** [comment]
> The strawman patch to remove the redundant calls of ENGINE_get_digest_engine is here. It breaks some SSL tests using TLSProxy

Unfortunately I don't think this can work. I think we need to do this call even in the event that we have a provider based digest.

However with #13733 applied, the overhead of `ENGINE_get_digest_engine` drops to about 2%.

**Comment by kaduk** [comment]
> > The strawman patch to remove the redundant calls of ENGINE_get_digest_engine is here. It breaks some SSL tests using TLSProxy
> 
> Unfortunately I don't think this can work. I think we need to do this call even in the event that we have a provider based digest.

It does perhaps make one wonder when 'ossltest' will need to move from being an engine to being a provider...I assume not for 3.0.0, but could perhapas be convinced otherwise.

**Comment by beldmit** [comment]
@kaduk, would you mind converting your last comment to an issue?

**Comment by kaduk** [comment]
> @kaduk, would you mind converting your last comment to an issue?

Sure, see #13760 .
