### ISSUE TITLE
When to release beta？

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#13726]
Hello，Could you please tell me when to release beta？
Thanks！

**Comment by dlegaultbbry** [comment]
When this list is at 0 Open (or 100% complete): https://github.com/openssl/openssl/milestone/17

**Comment by 1185129439** [comment]
> When this list is at 0 Open (or 100% complete): https://github.com/openssl/openssl/milestone/17

How long can these problems be completed?
Thanks！

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by mattcaswell** [comment]
This was a question specifically about the 3.0 beta, so no longer seems relevant at all. Closing.
