### ISSUE TITLE
How to get encrypt_then_mac and cookie_ext extension?

### ISSUE THREAD

**Issue by wongmz** [openssl/openssl#13727]
If i want to get encrypt_then_mac and cookie entensions, what functions should I use?
Can i read ssl_st.ext.use_etm to get encrypt_then_mac and read ssl_st.ext.tls13_cookie, ssl_st.ext.cookieok to get cookie?
Why is there no interface to get thse information? 
Is these information sensitive?

**Comment by mattcaswell** [comment]
> Why is there no interface to get thse information? 

These fields are considered internal and therefore not exposed. Why do you want to be able to access them?

**Comment by wongmz** [comment]
> These fields are considered internal and therefore not exposed. Why do you want to be able to access them?

I'd like to know if these fields have been sent from the peer.
Can i read ssl_st.ext.use_etm to get encrypt_then_mac and read ssl_st.ext.tls13_cookie, ssl_st.ext.cookieok to get cookie?

**Comment by mattcaswell** [comment]
> I'd like to know if these extensions have been sent from the peer.

Why do you want to know this?

> Can i read ssl_st.ext.use_etm to get encrypt_then_mac and read ssl_st.ext.tls13_cookie, ssl_st.ext.cookieok to get cookie?

Like I said, these are internal fields so you cannot read them

**Comment by wongmz** [comment]
> Why do you want to know this?

**Comment by wongmz** [comment]
> Why do you want to know this?

I want to know if the peer set relevant options, like SSL_OP_NO_ENCRYPT_THEN_MAC.

> Like I said, these are internal fields so you cannot read them

I know that now these are internal fields, and there is no function to get them.But I can add new ones to get them.But I'm worried that this information is sensitive data. Are they sensitive data?

**Comment by mattcaswell** [comment]
> I know that now these are internal fields, and there is no function to get them.But I can add new functions to get them.But I'm worried that these informations are sensitive data. Are they sensitive data?

It's not sensitive in the sense that we could choose to expose these fields without compromising security. However if you add new functions to get them yourself then your code could break at anytime if we choose to refactor the structure of ssl_st.

**Comment by wongmz** [comment]
> It's not sensitive in the sense that we could choose to expose these fields without compromising security. However if you add new functions to get them yourself then your code could break at anytime if we choose to refactor the structure of ssl_st.

Thank you for your reply. I plan to add new functions to get them.
Can I use ssl_st.ext.tls13_cookie and ssl_st.ext.cookieok to know if there is cookie extension in the message?
Use ssl_st.ext.use_etm to know if the peer set SSL_OP_NO_ENCRYPT_THEN_MAC?

**Comment by mattcaswell** [comment]
`tls13_cookie` is useful on the client side to know if a server sent a cookie. `cookieok` is useful on the server to know whether the client echoed back the cookie we sent. This is only relevant to TLSv1.3 cookies. They tell you nothing about DTLS cookies.
`use_etm` can be used on the client or server side to determine whether encypt-then-mac has been negotiated (which corresponds to the `SSL_OP_NO_ENCRYPT_THEN_MAC` option in OpenSSL terms).

I repeat the warning though that these are considered internal fields so applications are not supposed to use them. They do not form part of our stable API, so their implementation and meanings could change at any time.

**Comment by wongmz** [comment]
> `tls13_cookie` is useful on the client side to know if a server sent a cookie. `cookieok` is useful on the server to know whether the client echoed back the cookie we sent. This is only relevant to TLSv1.3 cookies. They tell you nothing about DTLS cookies.
> `use_etm` can be used on the client or server side to determine whether encypt-then-mac has been negotiated (which corresponds to the `SSL_OP_NO_ENCRYPT_THEN_MAC` option in OpenSSL terms).
> 
> I repeat the warning though that these are considered internal fields so applications are not supposed to use them. They do not form part of our stable API, so their implementation and meanings could change at any time.

Thank you very much for your reply.

**Comment by kaduk** [comment]
If you just want to know what extensions the client, sent, it seems simplest to set a client_hello callback, and call `SSL_client_hello_get1_extensions_present()` rather than adding a new function for each extension's data field.
