### ISSUE TITLE
If all the certificate without AKID/SKID，does certificate chain can be verified？

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#13737]
If all the certificate without AKID/SKID，does certificate chain can be verified about openssl3.0.0？
We have a number of test cases without AKID/SKID certificates，the output is as follows in openssl1.1.1f:
“SSL_getVerifyResult Description : unable to get issuer certificate”. It's what we want.

But，It is no error in openssl3.0.0. So I am wondering if there are any changes to AKID/SKID about openssl3.0.0.

**Comment by kroeckx** [comment]
The AKID is not needed, but used if present. This is not different
than previous versions.
