### ISSUE TITLE
Incomplete libctx/propq support in X509 sigining

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#13732]
The X509 signing still relies on some legacy (non `xx_ex`) functions, so the digest/signature algorithm selection does not follow the given propq. This can be tracked down to the following:

* The `openssl req` doesn't pass libctx/propq when signing the X509 CSR. It even cannot (see next item).

* There is no `X509_sign_ex` with libctx/propq support. 

* The `ASN1_item_sign_ex` is "half-migrated" only. It takes libctx/propq (which is good), but it also takes `EVP_MD` as input and calls `EVP_DigestSignInit` (without passing the libctx/propq). In my view, the `ASN1_item_sign_ex` should take a `const char*` digest name instead and call `EVP_DigestSignInit_ex`, which already exists and takes also libctx/propq. This ensures the correct cipher selection, which then manages the digest.

**Comment by slontis** [comment]
X509_sign_ex() is not necessary as the X509 object can be setup with a libctx, propq. 
ie ASN1_item_sign() should use ASN1_item_sign_ex() everywhere with x->libctx, x->propq.
In the apps all EVP_DigestSignInit() should be replaced with EVP_DigestSignInit_ex() so pkey is setup correctly.

**Comment by mattcaswell** [comment]
Will be fixed by #14752
