### ISSUE TITLE
With EVP_Digest* API, How can I save intermidiate Update hash value for later load and continue digest?

### ISSUE THREAD

**Issue by navigator117** [openssl/openssl#13746]
As the Openssl API said, "After calling EVP_DigestFinal_ex() no additional calls to EVP_DigestUpdate() can be made", how can I save intermidiate  hash value?
dig into code, EVP_MD_CTX_md_data() return HASH_CTX, which is not obviously to get save / load intermidiate hash value functions.

**Comment by dlegaultbbry** [comment]
Before you call final, use https://www.openssl.org/docs/man1.1.1/man3/EVP_MD_CTX_copy.html

**Comment by navigator117** [comment]
> Before you call final, use https://www.openssl.org/docs/man1.1.1/man3/EVP_MD_CTX_copy.html

This function just copy to a new MD_CTX, which is not what I want. How to save intermidiate hash value to a file, at a later time load from file and construct a new MD_CTX to continue digest? Or send/recv hash value to/from network to continue digest?

**Comment by navigator117** [comment]
AFAIK, EVP_MD_CTX_md_data(HASH_CTX) is opaque with internal data pointer to some mem address, can't direct copy and save.

**Comment by dlegaultbbry** [comment]
You can't do that as far as I know of digests, but what you can do though is a rolling digest which is effectively:

curr digest value = digest(previous digest value | new data)

This is easy to continue since you don't need the digest's internal state to do the next iteration.

**Comment by kaduk** [comment]
I believe that the internal hash state is deliberately not exposed via any public API, and thus that serializing it to a file is impossible using the offiical sources.
Why do you need to do so?  I note that, e.g., TLS 1.3 had originally considered serializing the transcript hash state across a HelloRetryRequest cycle but instead opted for a different construction akin to what @dlegaultbbry describes, for the final version in RFC 8446.  In addition to the implementation difficulty, the serialized hash state is much larger than a single hash output value.

**Comment by t8m** [comment]
There is #14222 as the digest state serialization RFE.
