### ISSUE TITLE
Remove SM2/3/4 from OpenSSL.

### ISSUE THREAD

**Issue by pthfdr-42** [openssl/openssl#13744]
SM2/3/4 is provided by the Chinese government, and by the 2019 "Encryption Method Law", it has mandatory backdoors.
So it should never ever be implemented.

**Comment by kroeckx** [comment]
Can you provide more info about the backdoors?

**Comment by pthfdr-42** [comment]
The "encrypt method law" that passes in 2019:

>第二十七条　法律、行政法规和国家有关规定要求使用商用密码进行保护的关键信息基础设施，其运营者应当使用商用密码进行保护，自行或者委托商用密码检测机构开展商用密码应用安全性评估。商用密码应用安全性评估应当与关键信息基础设施安全检测评估、网络安全等级测评制度相衔接，避免重复评估、测评。
>关键信息基础设施的运营者采购涉及商用密码的网络产品和服务，可能影响国家安全的，应当按照《中华人民共和国网络安全法》的规定，通过国家网信部门会同国家密码管理部门等有关部门组织的国家安全审查。

**Comment by kroeckx** [comment]
@InfoHunter: Can you comment on that?

**Comment by mspncp** [comment]
FWIW: here is Google's translation of the above text:

> Article 27: Operators of critical information infrastructures that are required by laws, administrative regulations, and relevant national regulations to be protected by commercial passwords shall be protected by commercial passwords, and commercial password testing institutions shall be themselves or entrusted to conduct commercial password application security assessments. The security assessment of commercial cryptography applications should be linked with the critical information infrastructure security testing and assessment and network security level assessment systems to avoid repeated assessments and assessments.
Critical information infrastructure operators who purchase network products and services involving commercial cryptography that may affect national security shall, in accordance with the provisions of the "Network Security Law of the People's Republic of China", be organized through the national network information department in conjunction with the national password management department and other relevant departments. National security review.

**Comment by kroeckx** [comment]
This is translated by bing:
> Article 27 Where laws, administrative regulations and relevant state regulations require the use of commercial passwords for the protection of critical information infrastructure, its operators shall use commercial passwords for protection, and shall conduct security assessments of commercial password applications on their own or by entrusting commercial password detection institutions. The security assessment of commercial password application should be connected with the security detection assessment and network security rating system of key information infrastructure, so as to avoid repeated evaluation and evaluation.
> If the operators of key information infrastructure purchase network products and services involving commercial passwords that may affect national security, they shall, in accordance with the provisions of the Cyber Security Law of the People's Republic of China, conduct a national security review through the State Network Information Department in cooperation with the State Password Administration and other relevant departments.```

**Comment by kroeckx** [comment]
To me, this reads as that infrastructure equipment (like routers and switches) should properly be protected with a password. I assume they should use some password manager or something like that. It does not read as that they need to share the passwords with the government. In any case, I don't see how this affects the use of SM2/3/4.

**Comment by pthfdr-42** [comment]
The last part is the key. You know what is a "security review" in an Orwellian country.
I am not 100% sure SMx has backdoors, but considering that the government (of an Orwellian country) wrote it, it is very likely to have backdoors.

**Comment by kroeckx** [comment]
It might be the case that the website you're talking to will tell
everything to the government, or will give the key used for the
communication to the government, but that is not a backdoor at the
encryption level. This can be done with things like RSA and AES
too.

**Comment by pthfdr-42** [comment]
Most of the people who view web pages do not give a damn about which encryption is used. The most thing they care is that whether it is HTTP or HTTPS. I think that we should remove any exotic encryption or hash methods (basically everything that is not AES and SHA).

Also, the US is not China. I won't delve into political stuff, but I want to say that RSA and AES have been reviewed countless times by experts, because everyone is using them. The same cannot be said about SMx.

**Comment by richsalz** [comment]
SM2/3/4 have had some review in the cryptography community.  Not as much as other systems, of course. No holes or weaknesses have been found so far.  That is not to say there are none, just that nothing has been found in limited review so far.

**Comment by pthfdr-42** [comment]
It all depends on how much you trust the maker, and the reviewer.
Just like the US government, those reviewers can be bribed and/or threatened (which is a common tactic by the Chinese government).
Remember that it is made by the Chinese government, which made and spread the coronavirus and lied about it.

**Comment by jinfeihan57** [comment]
> SM2/3/4 have had some review in the cryptography community. Not as much as other systems, of course. No holes or weaknesses have been found so far. That is not to say there are none, just that nothing has been found in limited review so far.
@richsalz 
Can you provide more info about "SM2/3/4 have had some review in the cryptography community."?

**Comment by richsalz** [comment]
I had a brief chat with Kenny Paterson and I paraphrased what he told me.  Web searching "analysis of sm2" for example, finds a few papers.

**Comment by open520** [comment]
Nonsense. I think you are a conspiracy theorist.

Since the algorithm is open source, if you think there are any backdoors, you should point them out! Not just say that you think there should be.

I think this issue should be closed! @kroeckx

**Comment by t8m** [comment]
Yep, unless it is clearly shown that the SM2/3/4 are broken algorithms, I do not think they should be removed. They are fully disableable in build time so anybody that is intimidated by those algorithms should just build OpenSSL without them.

**Comment by mengwangict** [comment]
"Remember that it is made by the Chinese government, which made and spread the coronavirus and lied about it."------there are too much politics and racism in github.
