### ISSUE TITLE
DRBG implementation comparison

### ISSUE THREAD

**Issue by tusharmishu** [openssl/openssl#13751]
Hi Team@OpenSSL,

When working with the DRBG and comparing it with a personal implementation, I notice that there is the following difference in bytes, the first generate works identically, however, the second generate gives different results on the ECB

printing cu-k
*******
 0xcd 0x3b 0xe0 0x58 0x63 0xee 0xba 0xfa 0x12 0xad 0x8b 0xbd 0x77 0x59 0x6c 0xf2
 0x04 0x4f 0xa2 0x42 0x39 0xd4 0x74 0x95 0xcb 0xcc 0xce 0xc6 0x54 0x92 0x05 0x85
*******
data counter.
*******
 0x9f 0x19 0x34 0x81 0x8d 0xb6 0x99 0xd1 0x22 0xd5 0xa3 0x43 0x22 0xaf 0x81 0x39
 0x9f 0x19 0x34 0x81 0x8d 0xb6 0x99 0xd1 0x22 0xd5 0xa3 0x43 0x22 0xaf 0x81 0x3a
 0x9f 0x19 0x34 0x81 0x8d 0xb6 0x99 0xd1 0x22 0xd5 0xa3 0x43 0x22 0xaf 0x81 0x3b
*******
My result
printing kv-update
*******
 0x02 0x7d 0x88 0xce 0x8b 0xe3 0x9e 0xa9 0xec 0x88 0xf4 0xa5 0x8d 0x3d 0xb6 0x43
 0x34 0x8a 0x05 0x55 0x70 0x04 0x54 0x36 0xee 0x13 0xe6 0x43 0x2e 0xd4 0x93 0xf9
 0x99 0x1f 0x51 0xe4 0xdc 0xc3 0x83 0x61 0xc5 0xf5 0xf4 0x4a 0xdf 0x5d 0xbf 0xab
*******

OpenSSL DRBG Result
printing out
*******
 0x7d 0x5f 0x70 0x97 0x8b 0xc9 0xa8 0x96 0xc9 0xc8 0x35 0xb6 0x21 0xd7 0x1b 0xb3
 0x8c 0x38 0x18 0x35 0xff 0xa4 0x2d 0x8d 0x31 0x6e 0xe5 0x3e 0x26 0xca 0x0b 0x5a
 0x18 0x4e 0x83 0x8f 0x55 0x1d 0x06 0x20 0x5d 0x3e 0xd7 0x42 0x45 0x0d 0x62 0x94
*******
Both implementations are consitently repeatable and also the end entropy of both implementation is 7.919xxx, however, the data differs. This is ECB so I wouldn't expect any differences, also my underlying library is OpenSSL.

Also, the EVP_Encrypt and DRBG_CTR code gave my head a spin.

Thanks
Tushar (tjpatel.tl@gmail.com)

**Comment by paulidale** [comment]
Might I suggest running your implement through NIST's [DRBG test vectors](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/drbg/drbgtestvectors.zip)?  They are comprehensive and the OpenSSL implementation passes them.  The data are in [test/recipes/30-test_evp_data/evprand.txt](https://github.com/openssl/openssl/blob/master/test/recipes/30-test_evp_data/evprand.txt).


The test source code is:

https://github.com/openssl/openssl/blob/30af356df487b2dad571be15574b454daf70743c/test/evp_test.c#L2055-L2338


I wouldn't trust entropy estimates from DRBG output.  DRBG are designed to look random, they are also deterministic & hence not random at all.

**Comment by tusharmishu** [comment]
Hi Pauli,

Thank you for the prompt answer and I will be running the test vectors, I
used the SP800 90a entropy assessment on about 10 million bits. And in line
with the question, DRBG should be deterministic and I was getting different
answers, however, a different answer for ECB on the same data was the
concern with the same key.

Anyway, will sync-up after the vector tests.

Thx.,
Tushar

On Wed, Dec 30, 2020 at 5:39 AM Pauli <notifications@github.com> wrote

**Comment by tusharmishu** [comment]
Hi Pauli,

First, Happy New Year to the OpenSSL team and though you may not know me
directly, I have been working with OpenSSL for about 20 odd years and thank
you for the great product.
I have also been fortunate to have two extensive certification efforts
covering OpenSSL and its use in Cisco's CiscoSSL and Palo Alto Network's
PAN-OS.
I believe you to be one of the original members, hence, this message to
thank all of you.

Back to work,

I ran the DRBG Tests on the alpha9 branch with
https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Standards-and-Guidelines/documents/examples/CTR_DRBG_withDF.pdf

entropy_input is
00010203 04050607 08090A0B 0C0D0E0F 10111213 14151617 18191A1B 1C1D1E1F
20212223 24252627 28292A2B 2C2D2E2F

nonce is
20212223 24252627 28292A2B 2C2D2E2F

no personalization_string

My results passed, however, the openssl results seems to be different, also
maybe I did something wrong, however, the OpenSSL version failed the ea_iid
tests also.

The test is on page 478, 479... in the attached document.

Please note that I was requesting 32 bytes (i.e. 256 bits) for a total of
2000000 bytes.

Something doesn't quite seem correct as OpenSSL has passed certs for about
16 yrs. for me and some guidance in the latest release would be helpful.

Thx.,
Tushar

**Comment by kroeckx** [comment]
Maybe Paul's message wasn't clear. You should not run an entropy
estimate on the output of the DRBG, as long as it's working fine,
it should always produce something that's random.

You want to run the entropy estimate on your raw entropy input,
before any processing. And I'm 99% sure that you want to run the
non-iid version on that.

**Comment by paulidale** [comment]
Might it be possible you are triggering the DRBG reseed code.  Does a request for more bytes per call stay in sync longer?  There are two parameters controlling this in 3.0: `reseed_requests` and `reseed_time_interval`.  Setting both to zero ought to disable them.  I'm a little confused though, we run a lot of DRBG tests to verify conformance with NIST's definitions.

As @kroeckx mentioned, the SP 800-90 entropy tests are not relevant to the output of a DRBG.  They are meant to be used on the raw input.  They are meaningless on the output.

**Comment by tusharmishu** [comment]
Hi Pauli,

It is quite possible, I might have made an error, however, the tests use
the raw AES-CTR DRBG file so that the errors are minimal and current there
is not other DRBG that I can trust to validate my implementation. hence,
preferred OpenSSL.

I am not performing any reseeds at this moment and only performed
i. Instantiate
ii. Generate about 2000000 bytes (each through a generate call with 32
bytes).

I know you guys have a tough schedule given that there is no FIPS approval
since 2016, however, sent this in as the test did not pass the entropy
tests, I thought this might help your certification, from my recollection,
given that the eseed and df are similar, the following occurred and the
results from OpenSSL should be matching the NIST results (alpha9 release)

1. My results and NIST matched and the data file generated from my version
was 7.90 min entropy.
2. The OpenSSL result did not pass, since this is conditioned (due to
SP800-90A), it should have passed (though I may have goofed up something,
however with other seeds it passes)

Anyway, here is the OpenSSL test file (attached ) and test program below
that I created and hopefully it can help look into this.

Thx.,
Tushar

===========================================================================
Here are the results from OpenSSL
$ ~/3p_srcs/SP800-90B_EntropyAssessment-master/cpp/ea_iid test1.dat
Calculating baseline statistics...
H_original: 1.738728
H_bitstring: 0.646364
min(H_original, 8 X H_bitstring): 1.738728

igamc: UNDERFLOW
** Failed chi square tests

** Failed length of longest repeated substring test
===========================================================================
Results from my implementation and NIST
$ ~/3p_srcs/SP800-90B_EntropyAssessment-master/cpp/ea_iid test2.dat
Calculating baseline statistics...
H_original: 7.908815
H_bitstring: 0.998991
min(H_original, 8 X H_bitstring): 7.908815

** Passed chi square tests

** Passed length of longest repeated substring test

Beginning initial tests...
Beginning permutation tests... these may take some time
** Passed IID permutation tests
===========================================================================

static uint8_t eseed[48]=
  {
   0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,
   0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,
   0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,
   0x18,0x19,0x1a,0x1b,0x1c,0x1d,0x1e,0x1f,
   0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,
   0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F
  };
static uint8_t nonce[16]=
  {
   0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,
   0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F
  };



int main(int argc, char *argv[])
{
  int                             rv                  = 0;
  size_t                          nbytes              = 0;
  size_t                          maxbytes            = 2000000;
  tst_PROV_DRBG_CTR              *mdc                 = NULL;
  FILE                           *fptr;
  uint8_t                         obuf[64];

  if(NULL == (fptr = fopen(argv[1], "w"))){
    ;
  }
  else if( NULL == (mdc = tst_drbg_ctr_new())){
    ;
  }
  else if(1 != tst_drbg_ctr_init(mdc)){
    ;
  }
  else if(1 != tst_drbg_ctr_instantiate(mdc,eseed,48,
nonce,16,NULL,0)){
    ;
  }
  else{
    /** Generate bytes */
    while(nbytes < maxbytes){
      rv = tst_drbg_ctr_generate(mdc,obuf,32,NULL,0);
      if(1 == rv){
nbytes += fwrite(obuf,1,64,fptr);
      }
    }
    fclose(fptr);
    rv = 1;
  }
  if(mdc)tst_drbg_ctr_free(mdc);
  return rv;
}

**Comment by paulidale** [comment]
Could you please include the rest of the code.  What exactly are you calling in OpenSSL?  `tst_drbg_ctr_generate` isn't an OpenSSL call e.g.

You still shouldn't be attempting entropy assessment on the DRBG output.  It's meaningless.

**Comment by tusharmishu** [comment]
Hi Pauli,

The tst_ is just a namespace wrapper around the drbg_ctr.c code in OpenSSL,
when I was getting differing numbers, I just stripped this off the
provider/implementations rand code, that is all the code.

The rest is linking is the c stub and the code in the file.

It’s a raw test and , the only additional code is

1. A call to Openssl_add_all_algorithms

2. The ea_Iid SP 800 90 assessment is available from Nist directly


3. The a.out can be run with an option test1.dat which will write the data
to the file


If it might be worth the time, I can setup a zoom to discuss and run the
tests on a zoom session


Thx.,
Tushar

**Comment by paulidale** [comment]
Some source code that indicates the problem will still be useful.  I don't think debugging this via zoom would be effective.  The intermediate DRBG values are critical and there are published examples to compare against.  Still, the problem seems to be with multiple calls to generate().

BTW: Openssl_add_all_algorithms() is not longer required.  What version of OpenSSL are you linking against?

After too many times, the **NIST's entropy assessment is simply not relevant to the output of a DRBG**.

**Comment by tusharmishu** [comment]
Hi Pauli,

Here is a zip file with the ossl code, it also includes my test results in
a file called atna/atna-tests/src/atn_drbg.dat and the step through prints
are in log_atna_drbg in the same directory.

There is an analogous naming for ossl (short for openssl)

You can build the ossl version by running make in the atna directory,
please note that you may need to edit the file atna-ossl-test.mk to point
to your alpha9 libcrypto as below

Building libossldrbg
gcc -shared -o ../lib64/libossldrbg.so.1.0.0 -L /home/tpatel/lib64 -lcrypto
 -Wl,-soname,libossldrbg.so.1 ../cobjs/drbg_ctr.o

The command for making the test is
cd atna/atna-tests/srcs
make -f atna-ossl-test.mk

To run the program after fixing the library links and setting
LD_LIBRARY_PATH correctly in bash is
../bin/atna-ossl-test <outfile >& logfile.

Sorry for sending the zip by email, however, my system is usually offline
with no networking.

I had to resend with the file truncated due to email limitations.

I hope this helps.

Thx.,
Tushar

**Comment by paulidale** [comment]
I'm not seeing the file...


Pauli

**Comment by tusharmishu** [comment]
Hi Pauli,

There should be a zip file in the attachment, let me check it,

Thx.,
Tushar

**Comment by tusharmishu** [comment]
Hi Pauli,

atna.tar.bz2 is attached, please tar -xvf it on a linux box.

Thx.,
Tushar

**Comment by tusharmishu** [comment]
Hi Pauli,

Sorry, not sure, however, my zip was corrupted last time, here is a resend.

Thx.,
Tushar

**Comment by kroeckx** [comment]
Note that you can't attach document per email. You need to attach them using the web interface.

**Comment by tusharmishu** [comment]
Hi Kurt,

Can you send instructions?

Thx.,
Tushar

**Comment by kroeckx** [comment]
You go to https://github.com/openssl/openssl/issues/13751  You can add a new comment at the bottom. You can click the border under the comment box that says "Attach files by dragging & dropping, selecting or pasting them". If you click it, it will open the file-open dialog box.

**Comment by tusharmishu** [comment]
Hi Pauli, Kurt,

I have uploaded the file as requested.

[atna.tar.gz](https://github.com/openssl/openssl/files/5788956/atna.tar.gz)

Thx.,
Tushar

**Comment by paulidale** [comment]
Thanks.  I'll try to get a look at this next week.

**Comment by paulidale** [comment]
I've not forgotten this, I'm just too busy on holiday...

**Comment by tusharmishu** [comment]
Hi Pauli,

Thanks for your update.

Thx.,
Tushar

**Comment by paulidale** [comment]
I'm getting the right output for the example starting page 478.

NIST claims the output of the two generate calls should be
> rnd_val is `E686DD55 F758FD91 BA7CB726 FE0B573A 180AB674 39FFBDFE 5EC28FB3 7A16A53B`
> rnd_val is `8DA6CC59 E703CED0 7D58D96E 5B6D7836 C3259973 5B734F88 C1A73B53 C7A6D82E`

I'm getting:
> `E686DD55F758FD91BA7CB726FE0B573A180AB67439FFBDFE5EC28FB37A16A53B`
> `8DA6CC59E703CED07D58D96E5B6D7836C32599735B734F88C1A73B53C7A6D82E`

Which is a match.


My quick and dirty test program is:

``` C
#include <stdio.h>
#include <openssl/evp.h>

static unsigned char e0[] = {
0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F, 
};
static unsigned char nonce[] = {
0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F, 
};

int main(int argc, char *argv[]) {
    EVP_RAND *rng, *tst;
    EVP_RAND_CTX *r, *t;
    OSSL_PARAM params[20], *p;
    int use_df = 1, strength = 500;
    size_t j, len = 32;
    unsigned char buf[1000];

    tst = EVP_RAND_fetch(NULL, "TEST-RAND", NULL);
    t = EVP_RAND_CTX_new(tst, NULL);

    p = params;
    *p++ = OSSL_PARAM_construct_int("strength", &strength);
    *p++ = OSSL_PARAM_construct_octet_string("test_entropy", e0, sizeof(e0));
    *p++ = OSSL_PARAM_construct_octet_string("test_nonce", nonce, sizeof(nonce));
    *p = OSSL_PARAM_construct_end();
    EVP_RAND_set_ctx_params(t, params);

    EVP_RAND_instantiate(t, 256, 0, "", 0);

    rng = EVP_RAND_fetch(NULL, "CTR-DRBG", NULL);
    r = EVP_RAND_CTX_new(rng, t);

    p = params;
    *p++ = OSSL_PARAM_construct_utf8_string("cipher", "AES-256-CTR", 0);
    *p++ = OSSL_PARAM_construct_int("use_derivation_function", &use_df);
    *p = OSSL_PARAM_construct_end();
    EVP_RAND_set_ctx_params(r, params);

    EVP_RAND_instantiate(r, 256, 0, "", 0);

    EVP_RAND_generate(r, buf, len, 256, 0, NULL, 0);
    for (j=0; j<len; j++)
        printf("%02X", buf[j]);
    printf("\n");

    EVP_RAND_generate(r, buf, len, 256, 0, NULL, 0);
    for (j=0; j<len; j++)
        printf("%02X", buf[j]);
    printf("\n");

    return 0;
}
```

Now, if I generate `len * 2` bytes in the first generate call and omit the second generate call, the second half of the output **is** different:

> `E686DD55F758FD91BA7CB726FE0B573A180AB67439FFBDFE5EC28FB37A16A53B`
> `68F2F51A364601AF9533C864F25DA9977D095ACEB5DE8DA2333C40858D88DE5B`

Perhaps this is what you are encountering?

**Comment by tusharmishu** [comment]
Hi Pauli,

Thank you for the detailed information, maybe it could be the case. For
now, I think it should be fine, however, though, I think NIST should
standardize an implementation. I actually was fine with a different answer,
however, the entropy was way to low. My seeds are based on RDSEED and hence
cautious.

Anyway, will look into it when I get back to DRBG testing

Thx.,
Tushar

**Comment by paulidale** [comment]
Again, please do not attempt to entropy test the output of a DRBG.  It really is pointless.
