### ISSUE TITLE
Failure creating (x25519) private key encrypted with chacha20

### ISSUE THREAD

**Issue by ean365** [openssl/openssl#13753]
Noob to openssl community here....
I did a quick search and didn't see this in any of the bug reports...

`$ openssl genpkey -algorithm x25519 -chacha20`
`139710361634112:error:0D0A706C:asn1 encoding routines:PKCS5_pbe2_set_iv:cipher has no object identifier:../crypto/asn1/p5_pbev2.c:52:
139710361634112:error:2307D00D:PKCS12 routines:PKCS8_encrypt:ASN1 lib:../crypto/pkcs12/p12_p8e.c:32:`

It seems to be an issue with using chacha20 for key encryption...

`$ openssl genpkey -algorithm rsa -chacha20`
`140095238944064:error:0D0A706C:asn1 encoding routines:PKCS5_pbe2_set_iv:cipher has no object identifier:../crypto/asn1/p5_pbev2.c:52:
140095238944064:error:2307D00D:PKCS12 routines:PKCS8_encrypt:ASN1 lib:../crypto/pkcs12/p12_p8e.c:32:`

My environment:

`$ openssl version`
`OpenSSL 1.1.1f  31 Mar 2020`

`$ cat /proc/version`
`Linux version 5.4.0-52-generic (buildd@lgw01-amd64-060) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020`

**Comment by kaduk** [comment]
Yes, it's related to attempting to use chacha20 for key encryption.
There is not (to my knowledge) an OID assigned for using chacha20 as a PKCS#5 PBES2 encryption algorithm (see the list at https://tools.ietf.org/html/rfc8018#appendix-B.2).  And if there has been one allocated by someone, openssl doesn't implement it.

In general, I don't expect there to be much demand for chacha20 in this use case; is there a particular reason why you wanted to do so?

**Comment by ean365** [comment]
I see.  Thanks for the quick answer.  So, it's not really a bug, and from your answer and reading other postings, I see that openssl really only implements the current standards.
Without going into much detail, I'm basically implementing encryption of sensitive log entries.  I was looking for a "good" "strong" alternative to AES for storing an encrypted private key file in a more-or-less public directory (considered "public" because I do not physically control the server -- which makes what I'm doing an imperfect solution.).  Anyway, I can simply encrypt the entire private key file using chacha20, but I thought there might be a way to do it as in PKCS#5.  AES key encryption is probably good enough for my purposes, for now.  Though, I'm guessing PKCS#5 is likely to move on to include/allow other key encryption algorithms, such as chacha20, in future.

**Comment by kaduk** [comment]
Thanks for the extra information.
I agree that AES is probably fine for you.

I'll go ahead and close this issue for now, but of course feel free to reopen or open a new one if something else comes up (such as finding a spec for PKCS#5 with chacha20).
