### ISSUE TITLE
d2i_X509 and d2i_X509_AUX behavior has become inconsistent and non-intuitive and is not documented

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#13754]
@slontis wrote in https://github.com/openssl/openssl/pull/12153#issuecomment-650094516:

> NOTE that `d2i_X509()` calls `X509v3_cache_extensions()` if the cert object is passed in.

Why has this non-intuitive behavior been added? At least, this must be documented.
If calling `X509v3_cache_extensions()` is really helpful then better do this also in case no cert object is passed in.

(**Update:** The issue described in this paragraph is fixed by #13755:
The call of  `X509v3_cache_extensions()` causes trouble: if the caller passed in a pointer to a NULL cert pointer the caller must be very careful in case NULL is returned after the cert was parsed successfully but is invalid such that `X509v3_cache_extensions()` failed.
In this case the caller needs to free the cert object which has been allocated regardless.)

I have already fixed part of this in #13755 (because I needed it there) such that `d2i_X509()` behaves consistently at least with `d2i_X509_AUX`, which deallocates the just created cert object in case an error occurred in its further processing. This way a mem leak is avoided.

@slontis, ~do you agree with the small improvement I did, and~ 
can you please properly document `d2i_X509()` and `d2i_X509_AUX()`?
The description in `i2d doc/man3/d2i_X509.pod` so far does not cover that new special feature of conditionally calling `X509v3_cache_extensions()`in `d2i_X509()` and thus also in `d2i_X509_AUX()`.
Moreover, the deallocation behavior for any passed-in object pointer is not documented for any `d2i_TYPE()` , neither for  `d2i_X509_{CERT_,}AUX()`.

**Comment by slontis** [comment]
I am on holidays currently, so may not respond again till next week.

Caching seems like internal behavior to me, so documenting this particular bit seems debatable.
The changes were added so that the libctx/propq could be set into the cert before the d2i call.. This means that by the end of the d2i call the cert should be in a 'fixed' final state - So caching at this time seems to be a good point to do this.
For the NULL case being passed in -  I wasnt sure it this was the right thing to do or not.
If we have any cases where X509 certs are loaded as an embedded part of another ANS1 object then a resolve stage would be needed, so that optionally the libctx/propq could be set before the cert (caching) is used.

**Comment by slontis** [comment]
Fixing the bug seems like a good idea :)

**Comment by DDvO** [comment]
Reopening this because #13755 fixed only part of this.

BTW, thanks @slontis for your above initital comments.

**Comment by t8m** [comment]
@DDvO could you please summarize what are the issues remaining to be fixed (if they are regressions) or documented for 3.0 in case they aren't regressions.

**Comment by DDvO** [comment]
I had already updated the original post according to my partial fix in #13755,
and just edited it further in order more clearly stating the remaining state of affairs.

**Comment by DDvO** [comment]
> I am sorry but it is still not clear to me if this is now just a documentation issue or if there is also any code change remaining to be done.

I find it strange and even unfortunte that `d2i_X509()` meanwhile calls `X509v3_cache_extensions()`.
and moreover that it does so in some cases only, namely if the `a` parameter is not NULL.
From the above response by @slontis it do not understand why this is not done also if `a` is  NULL.

If there is no good reason, I propose removing this call again because `X509v3_cache_extensions()` may fail,
which prevents the use of `d2i_X509()` and  `d2i_X509_AUX()` for low-level loading certs that may be somewhat malformed.

Otherwise, this unexpected behavior should be documented for both  `d2i_X509()` and  `d2i_X509_AUX()`,
even though `X509v3_cache_extensions()` is a somewhat internal thing, because it limits the use of these functions.

**Comment by richsalz** [comment]
I would hope that by now, the project has learned that if something is done in the X509 code, and they don't understand why, then they should not touch it until they understand it.

**Comment by DDvO** [comment]
> I would hope that by now, the project has learned that if something is done in the X509 code, and they don't understand why, then they should not touch it until they understand it.

@richsalz, I feel your comment misplaced.
In particular since loading certs is not a security-critical operation.

**Comment by DDvO** [comment]
> We disagree. "I don't know why we do this, I'll remove/refactor it" scares me now.

@richsalz, I see only one reason to disagree and to be scared here: not understanding the issue.
By carefully reading the above exchange, you should be able to realize what the situation is:

#12153 added a conditional call of `X509v3_cache_extensions()` to `d2i_X509()` because the author thought this should be beneficial,
not properly taking into account that `X509v3_cache_extensions()` may fail in strange situations and with strange cert objects.
One should note here that despite its - pretty misleading - name, that function does much more than caching extensions.
Among others, it calculates and internal hash of the cert, which may fail because the alg may not be available,.
and it does some low-level well-formedness checks, which may fail when the cert construction did not follow certain rules.

Inevitably, it turned out that the new call to `X509v3_cache_extensions()` did not help but caused trouble, 
including situations that lead to obscure memory leaks, which I fixed in #13755.
Yet still `X509v3_cache_extensions()` and thus  `d2i_X509()` may fail for unexpected reasons and under undocumented conditions.
Since the newly added call to `X509v3_cache_extensions()` is not needed for `d2i_X509()` (which should keep focused on parsing a cert object, not on doing some more high-level stuff like checking well-formedness), and  `X509v3_cache_extensions()` is anyway called later when needed, I propose here to remove that call again.

Having the call already along with parsing the cert object clearly is a bug, not a feature.
As explained, it can lead to weird trouble and limits the applicability of  `d2i_X509()` and  `d2i_X509_AUX()`.

> And if you don't think loading certs is a security-critical operation, what about the trust store?

Come on. `d2i_X509()` is just used for parsing certs while loading them, e.g., from files.
This low-level operation is entirely independent of any decision on putting a cert into a trust store.
Again, this function is not security critical. The worst thing that can happen with it is that it fails to load a cert.

**Comment by t8m** [comment]
@DDvO would you like to submit a PR?

**Comment by DDvO** [comment]
> @DDvO would you like to submit a PR?

Here it is: #15705.
