### ISSUE TITLE
If three be a Bit transition in the DTLS Message,should i drop this message and go on or shutdown the DTLS Lilk?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#13763]
If three be a Bit transition in the DTLS Message,should i drop this message and go on or shutdown the DTLS Lilk?

**Comment by stardrift1** [comment]
In the function:  dtls1_process_record(SSL *s, DTLS1_BITMAP *bitmap),if the received message have a bad mac,it chooses to generate a bad_record_mac alert:
SSLfatal(s, SSL_AD_BAD_RECORD_MAC, SSL_F_DTLS1_PROCESS_RECORD,
                   SSL_R_DECRYPTION_FAILED_OR_BAD_RECORD_MAC);
but in RFC 6347 it says that will lead denial-of-service (DoS) attacks when DTLS RUN Over UDP
![image](https://user-images.githubusercontent.com/42114820/103476389-0a95a080-4df0-11eb-8110-d6fea7bfcfae.png)

**Comment by kaduk** [comment]
The code needs to exist for the case of DTLS over SCTP.
I am pretty sure we don't actually send the alert when running over UDP, but have forgotten where the code to make that happen is.  I suggest looking at a packet capture rather than just code analysis, if you are investigating this scenario.

**Comment by stardrift1** [comment]
@kaduk thanks，i get a  packet capture,and find when dtls over udp ，it simply discard the bad packet .
