### ISSUE TITLE
OpenSSL 3.0 Issues

### ISSUE THREAD

**Issue by yxungh** [openssl/openssl#13766]
I see PRE_RELEASE_TAG=alpha10_dev, the next version is alpha 10.When will alpha10 be released?
Is there any alpha 11 after that?
Any plans to release the beta version when?

**Comment by mattcaswell** [comment]
alpha10 is expected on Thursday (7th January 2021).

We don't yet have a date for the beta release.

**Comment by yxungh** [comment]
ok
