### ISSUE TITLE
Arm-Linux Openssl 3.0 req Error

### ISSUE THREAD

**Issue by ejparz** [openssl/openssl#13773]
Hi Openssl Team,

I'm working on a dev team that's testing openssl 3.0 on our arm-linux embedded device.

We successfully cross compiled Openssl 3.0 Alpha 9 using the following commands:

```
Download and unpack latest release from github
cd openssl
export ANDROID_NDK_ROOT=$(abspath ../standalone-toolchain) 
export TOP = $(shell pwd)
./Configure android-arm -march=armv7-a --prefix=$(TOP)/install
make
make install
```

We then adb pushed the generated install directory to our embedded device.

At this point, we ran a simple test to ensure that the openssl binary works as expected.

```
cd install/bin
./openssl req -x509 -newkey rsa:2048 -keyout key.pem -out req.pem -config ../ssl/openssl.cnf
```

We get the following message:

> Generating a RSA private key
> .........+....................+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...+......+.....+....+..............+...+...+.......+.................+...+...+.+.....+...+......+.+...+......+..+.........+.+...+..............+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*Error Generating Key

Is it possible to get a more verbose error message that highlights the actual cause of the error? Have any of you seen a similar issue?

On that last version of openssl we used on our embedded device (OpenSSL 1.0.2l), the above command completed successfully and prompted for usual certificate fields

> Generating a 2048 bit RSA private key
> ....+......+...++++++++++++++++++++++++++++*...+..........++++++++++++++++++++++++++++*....+............+........................................+............................................+................+..............+......+....+..................+........+....+............................................+..........+..+....+......+..............................+................................+..............................+............+++++++++++++++++++++++++++++++++++++++++++++++++++
> ...............+...+..+............+.+........++++++++++++++++++++++++++++*.....+...+.........++++++++++++++++++++++++++++*............................................+....+......+........................+....................+....+................................+..............................................+........+............+....................................................+..+........................+................+..............+..................................+........+............+..................+............................+....................................................................................+....................+......+..............................+........................................................................+..................+........................+................+..+....+..................+......+......+..............+....+..................+........+....+......+........................+......+............+........+......+................................................+..................+..................+................+++++++++++++++++++++++++++++++++++++++++++++++++++
> writing new private key to 'key.pem'
> -----
> You are about to be asked to enter information that will be incorporated
> into your certificate request.
> What you are about to enter is what is called a Distinguished Name or a DN.
> There are quite a few fields but you can leave some blank
> For some fields there will be a default value,
> If you enter '.', the field will be left blank.

Thanks,

Eric

**Comment by mattcaswell** [comment]
> Is it possible to get a more verbose error message that highlights the actual cause of the error? Have any of you seen a similar issue?

Hmm. It is supposed to dump the contents of the OpenSSL error stack in the event of a failure like this. The fact that it doesn't suggests that there are no errors on the stack - in spite of the error message. Probably you've hit some codepath which has failed but not populated the error stack with the reason which is annoying and unhelpful.

The fact that you are getting *some* output before the failure seems to suggest that it gets quite a way through the process of generating the key before eventually failing.

How feasible is it to run a debugger on this device?

**Comment by mattcaswell** [comment]
Another thought - what is in you openssl.cnf file? I wonder what happens if you try exactly the same command with the same config file on a non-embedded platform. Do you get the same error?

**Comment by ejparz** [comment]
@mattcaswell Thanks very much for those ideas!

I just compiled openssl for my local machine (Configuring OpenSSL version 3.0.0-alpha9 for target linux-x86_64)
```
./Configure --prefix=/home/eparziale/openssl/install
make
make install
```

Then I ran 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/eparziale/openssl/install/lib
cd /home/eparziale/openssl/install/bin
./openssl req -x509 -newkey rsa:2048 -keyout key.pem -out req.pem -config ../ssl/openssl.cnf
``` 
(The exact same command with same config for non-embedded platform.

In this case it worked as expected:

> Generating a RSA private key
> ..+.+..+......+....+...+.....+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+.......+...+..+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+....+.....+....+..+.........+...+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> ......+........+.+......+.....+...+..................+...+.+......+........+....+......+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.............+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...........+............+...+.......+..+...+.+......+..............+....+...+..+.......+.........+.....+............+....+......+.....+.......+..+...+................+..+........................+.+........+.+.....+.........+.+........+.......+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> writing new private key to 'key.pem'
> Enter PEM pass phrase:
> Verifying - Enter PEM pass phrase:
> -----
> You are about to be asked to enter information that will be incorporated
> into your certificate request.
> What you are about to enter is what is called a Distinguished Name or a DN.
> There are quite a few fields but you can leave some blank
> For some fields there will be a default value,
> If you enter '.', the field will be left blank.
> -----
> Country Name (2 letter code) [AU]:US


I will now use the strace tool to see what code path is failing on the embedded device. Will report back this afternoon.

**Comment by ejparz** [comment]
After running openssl through strace on both an x86_64 linux host and on our ARM device, we noticed the following which might be giving a good hint. Could it be that the "/dev/urandom" codepath has a bug in it or is missing logging?
### ARMv7l running 3.14 kernel
Note the getrandom() syscall failing and using gettimeofday() instead. The date is also set correctly (Mon Jan  4 20:54:58 UTC 2021).
```none
write(2, "Generating a RSA private key\n", 29) = 29
mmap2(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6840000
madvise(0xb6840000, 262144, MADV_MERGEABLE) = 0
prctl(0x53564d41 /* PR_??? */, 0, 0xb6840000, 0x40000, 0xb6aa928f) = 0
futex(0xb6dbaa60, FUTEX_WAKE_PRIVATE, 2147483647) = 0
mmap2(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6800000
madvise(0xb6800000, 262144, MADV_MERGEABLE) = 0
prctl(0x53564d41 /* PR_??? */, 0, 0xb6800000, 0x40000, 0xb6aa928f) = 0
clock_gettime(CLOCK_REALTIME, {1609790116, 522751082}) = 0
getrandom(0xb6888180, 32, 0)            = -1 ENOSYS (Function not implemented)
openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_LARGEFILE) = 3
fstat64(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
read(3, "\324\225\274\302u\303c\224?s\23e\233\t\234\246\224\25\231T\342J\220\312\t\355\265.\254).\t", 32) = 32
gettimeofday({1609790116, 523920}, NULL) = 0
gettimeofday({1609790116, 524168}, NULL) = 0
gettimeofday({1609790116, 524464}, NULL) = 0
gettimeofday({1609790116, 524621}, NULL) = 0
gettimeofday({1609790116, 524779}, NULL) = 0
gettimeofday({1609790116, 525074}, NULL) = 0
gettimeofday({1609790116, 525318}, NULL) = 0
write(2, ".", 1)                        = 1
write(2, "+", 1)                        = 1
gettimeofday({1609790116, 527524}, NULL) = 0
write(2, ".", 1)                        = 1
write(2, ".", 1)                        = 1
write(2, "+", 1)                        = 1
gettimeofday({1609790116, 530105}, NULL) = 0
write(2, ".", 1)                        = 1
write(2, "+", 1)                        = 1
gettimeofday({1609790116, 531778}, NULL) = 0
write(2, ".", 1)                        = 1
write(2, ".", 1)                        = 1
write(2, ".", 1)                        = 1
.
.
.
gettimeofday({1609790116, 670150}, NULL) = 0
write(2, "+", 1)                        = 1
gettimeofday({1609790116, 671411}, NULL) = 0
write(2, "+", 1)                        = 1
gettimeofday({1609790116, 672334}, NULL) = 0
write(2, "+", 1)                        = 1
gettimeofday({1609790116, 673320}, NULL) = 0
write(2, "+", 1)                        = 1
write(2, "*", 1)                        = 1
write(2, "Error Generating Key\n", 21)  = 21
madvise(0xb68ff000, 4096, MADV_DONTNEED) = 0
futex(0xb6abe5ac, FUTEX_WAKE_PRIVATE, 2147483647) = 0
mprotect(0xb6e3b000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0xb6e3b000, 4096, PROT_READ)   = 0
fstat64(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
close(3)  
```
### X86_64 running 4.14 kernel
Note the getrandom() syscall passing and the lack of gettimeofday().
```none
write(2, "Generating a RSA private key\n", 29) = 29
futex(0x7f331495d468, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(0x26f6000)                          = 0x26f6000
brk(0x2717000)                          = 0x2717000
brk(0x273a000)                          = 0x273a000
brk(0x275c000)                          = 0x275c000
brk(0x277d000)                          = 0x277d000
getrandom("\v\322\17\324\333\370G\20)\373\206\5\217y\376\362\34\330\345\253\32054Xj^f\32\366!\225\202", 32, 0) = 32
write(2, ".", 1)                        = 1
write(2, ".", 1)                        = 1
write(2, ".", 1)                        = 1
write(2, ".", 1)                        = 1
write(2, ".", 1)                        = 1
.
.
.
write(2, "writing new private key to 'key."..., 37) = 37
open("key.pem", O_WRONLY|O_CREAT|O_TRUNC, 0600) = 3
fcntl(3, F_GETFL)                       = 0x8001 (flags O_WRONLY|O_LARGEFILE)
futex(0x7f331495e984, FUTEX_WAKE_PRIVATE, 2147483647) = 0
open("/dev/tty", O_RDONLY)              = 4
open("/dev/tty", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
fstat(5, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
ioctl(5, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(5, "Enter PEM pass phrase:", 22)  = 22
```

**Comment by FdaSilvaYY** [comment]
Common issue with embedded device: lack of entropy !
OS is waiting for more random inputs.
It can be fixed by adding some other tools/packages to your Linux installation.

**Comment by ejparz** [comment]
Ah thanks very much for that tip.

We will investigate how to increase our entropy.

In the meantime - Is there an openssl tool that can help us test whether our  entropy source is sufficient?
Also, can the openssl binary be updated to return an err message if it encounters lack of entropy?

Thank you,

**Comment by FdaSilvaYY** [comment]
See also : #13325

**Comment by mattcaswell** [comment]
You can just use the openssl "rand" tool to see if you are getting random data generated, e.g.

`````
openssl rand -out test.rnd 256
````

**Comment by ejparz** [comment]
Thanks for that info, we were able to increase the entropy on our embedded device, and succesfully run
```
./openssl req -x509 -newkey rsa:2048 -keyout key.pem -out req.pem -config ../ssl/openssl.cnf
```

Now that we've confirmed the above basic openssl command works, we want to confirm the same command works with fips enabled.

Before enabling fips on the embedded device and running a test, we first decided to test on our local machines.

We enabled fips locally on our X86_64 linux box via these commands:

**First, run fipsinstall on local**
```
/home/eparziale/openssl/install/bin/openssl  fipsinstall -out /home/eparziale/openssl/fipsmodule.cnf -module /home/eparziale/openssl/install/lib/ossl-modules/fips.so

HMAC : (Module_Integrity) : Pass
SHA1 : (KAT_Digest) : Pass
SHA2 : (KAT_Digest) : Pass
SHA3 : (KAT_Digest) : Pass
TDES : (KAT_Cipher) : Pass
AES_GCM : (KAT_Cipher) : Pass
RSA : (KAT_Signature) : RNG : (Continuous_RNG_Test) : Pass
Pass
ECDSA : (KAT_Signature) : Pass
DSA : (KAT_Signature) : Pass
HKDF : (KAT_KDF) : Pass
SSKDF : (KAT_KDF) : Pass
HASH : (DRBG) : Pass
CTR : (DRBG) : Pass
HMAC : (DRBG) : Pass
DH : (KAT_KA) : Pass
ECDH : (KAT_KA) : Pass
RSA_Encrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
INSTALL PASSED
```
Second, modify two lines in /home/eparziale/openssl/install/ssl/openssl.cnf 
```

###We added this line under openssl_conf = openssl_init
.include /home/eparziale/openssl/fipsmodule.cnf

### we uncommented the following line under [provider_sect]
fips = fips_sect
```

Then we ran 

```
/home/eparziale/openssl/install/bin/openssl req -x509 -newkey rsa:2048 -keyout key.pem -out req.pem -config /home/eparziale/openssl/install//ssl/openssl.cnf
```

But got the following output

```
Generating a RSA private key
..+.....+...............+............+.+.....+...+....+..+......+.......+..................+..+...+.......+.....+.+..+............+.+..+..........+...+.....+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+...+..................+.+...+..+...+.+...............+.....+....+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+......+......+.....+.+...+..+.......+........+...+.......+...+..+...+....+..+...+..........+..+...+.+.....+.......+...+..+.............+......+.....+.........+.+...........+.......+..+.............+.....+...+.........+....+.....+.+......+...+.........+...+..+......+......+.+...............+..............+....+...........+.+...+..+.........+.........+..........+..+.........+..........+........+............+......+...+.+...+...+...+..+.........+.+.....+.............+......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
....+.+......+...+..+...............+.......+.....+.+.........+.....+...+....+..............+.+.....+......+....+...+........+.......+..+....+.....+....+..+......+.......+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.......+......+..+.......+........+.......+...+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.........+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
writing new private key to 'key.pem'
0017A5C8DE7F0000:error::PEM routines:do_pk8pkey:error converting private key:crypto/pem/pem_pk8.c:127
```

Is this error expected?

How do we get this req command to work with fips enabled?

Thanks,

Eric

**Comment by mattcaswell** [comment]
> How do we get this req command to work with fips enabled?

You don't have any serializers loaded. The serializers are required to convert a key to/from a file format. They are not cryptographic algorithms in themselves and are therefore considered out of the scope of the FIPS module, and are not included in that provider. If you load the "default" provider you always get the serializers, but if you don't load "default" then you *should* also load the "base" provider. That provider doesn't include any crypto algorithms but does include all the serializers and is designed to work in conjunction with the "fips" provider.

See the 3.0 wiki page for a further discussion on this:
https://wiki.openssl.org/index.php/OpenSSL_3.0

Side note: I wonder if we can improve the error reporting here? I imagine this is going to be a common problem and the error message is quite cryptic and doesn't really lead you in the right direction.

**Comment by mattcaswell** [comment]
> Side note: I wonder if we can improve the error reporting here? I imagine this is going to be a common problem and the error message is quite cryptic and doesn't really lead you in the right direction.

I raised #13798 for this.

**Comment by ejparz** [comment]
Thanks very much @mattcaswell.

Based on your feedback we uncommented  (#activate = 1 under [default_sect])

```
[default_sect]
activate = 1
```
and now the command works!

However, I want to make sure we fully understand your comment. You say:

> If you load the "default" provider you always get the serializers, but if you don't load "default" then you should also load the "base" provider. That provider doesn't include any crypto algorithms but does include all the serializers and is designed to work in conjunction with the "fips" provider.

Does this mean that we should activate a base_sect instead of default_sect? I'm a little confused here. How do we enable "base" provider via config?

In the documentation listed here, when it describes how to make all apps use FIPS module by default, 
https://wiki.openssl.org/index.php/OpenSSL_3.0#Making_all_applications_use_the_FIPS_module_by_default,
 it says to edit the config file to add the following lines:

```
openssl_conf = openssl_init

.include /usr/local/ssl/fipsmodule.cnf

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
```

Should it also say to uncomment #activate =1 under default section? Or to enable base_sect (however that is done)?

Thanks very much.

E

**Comment by mattcaswell** [comment]
> Does this mean that we should activate a base_sect instead of default_sect?

Yes

> How do we enable "base" provider via config?

Something like this should do it:

````
openssl_conf = openssl_init

.include /usr/local/ssl/fipsmodule.cnf

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1
````

> In the documentation listed here, when it describes how to make all apps use FIPS module by default,
https://wiki.openssl.org/index.php/OpenSSL_3.0#Making_all_applications_use_the_FIPS_module_by_default,
it says to edit the config file to add the following lines:

Thanks for pointing that out. I modified the documentation to talk about "base", and include it in the config file example.

**Comment by ejparz** [comment]
Awesome. Thanks for updating the documentation.

Confirmed openssl works with the updated base_sect config as you suggested

**Comment by mattcaswell** [comment]
Great. Glad it works.
