### ISSUE TITLE
OpenSSL 1.1.1i v. VMS

### ISSUE THREAD

**Issue by Antinode-org** [openssl/openssl#13789]
Greetings:

   I'm reconciled myself to the changes involved with automating
creation of the builders on VMS.  But I have a few complaints.

------------------------------------------------------------------------

      NOTES.VMS

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
 MMS has certain limitations when it comes to line length, [...]
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   It sure does:

$ mms install
[...]
######################################################################

Installation complete

Run @UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.1_1_1I.SYS$STARTUP]openssl_startup0101 
to set up logical names
then run @UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.1_1_1I.SYS$STARTUP]openssl_utils01
01 to define commands

%MMS-F-EXETOOBIG, Command too large.  Maximum length is 1019 characters.
ITS $ 

   Those tall piles of "WRITE SYS$OUTPUT <whatever>" inside PIPE
commands could/should be broken apart.

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
[...] a very simple solution is to set yourself up a few logical
names for the directory trees you're going to use.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   Or, defining a symbol in the MMS description file for "WRITE
SYS$OUTPUT".  Or breaking apart the PIPE piles, especially where
user-specified variables are used.

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
 The easiest way to check if everything got through as it should is to
 check for one of the following files:

   [.crypto]opensslconf^.h.in
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   "one of the following files"?  Out of that list of one?

   And I see no such file in [.crypto].  I do see one in
[.include.openssl].

------------------------------------------------------------------------

      INSTALL

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
 This will build and install OpenSSL in the default location, which is:
[...]
  OpenVMS: SYS$COMMON:[OPENSSL-'version'...], where 'version' is the
           OpenSSL version number with underscores instead of periods.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   Not a good choice.  I don't want this stuff in my SYS$COMMON tree. 
Who does?

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
 If you want to install it anywhere else, run config like this:
[...]
  On OpenVMS:

    $ @config --prefix=PROGRAM:[INSTALLS] --openssldir=SYS$MANAGER:[OPENSSL]
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   I missed the explanation of what "PROGRAM:[INSTALLS]" was supposed to
tell me, or why SYS$MANAGER would be a good place for any of this stuff.

   I'll admit that --prefix and --openssldir are explained further
along, but someone reading from beginning to end hasn't seen that yet. 
A casual reader might guess that "PROGRAM" might be some product-defined
logical name, and not just useless nonsense.  Something as simple as
"See --prefix and --openssldir, below" would be more helpful.  Or more
obviously generic examples, like, say "dev:[dir]".

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
       OpenVMS ('arch' is replaced with the architecture name, "Alpha"
       or "ia64", 'sover' is replaced with the shared library version
       (0101 for 1.1), and 'pz' is replaced with the pointer size
       OpenSSL was built with):
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   "ia64"?  As in?:

ITS $ write sys$output f$getsyi( "arch_name")
IA64

   I don't see it being downcased in real life.  Revealing how the name
is actually obtained might help the user when the next architecture type
appears.

   "0101" as in "1.1." of "1.1.X", not ".1.1" of "1.1.1"?  Using "1.1.1"
as the example was less than optimal.

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
         [.SYS$STARTUP] Contains startup, login and shutdown scripts.
                        These define appropriate logical names and
                        command symbols.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   I'd vote for those changes as being the worst new idea.  Dollar signs
in names like that are (or should be) reserved for the custodians of the
OS, currently VMS Software, Inc. (https://vmssoftware.com/).

   These are not what I'd call "startup" or "shutdown" scripts.  As the
description says, they define/undefine logical names or DCL symbols. 
And, again, too many dollar signs.  "[.vms]" and the other older names
weren't long/complicated/misleading enough?

   Of course, now that I've generated yet another set of LINK option
files for this stuff, more changes now might be worse.

------------------------------------------------------------------------

   The VMS section of this could use some work:

      https://wiki.openssl.org/index.php/Compilation_and_Installation

------------------------------------------------------------------------

   Yes, it's not all "Documentation", but it started out as e-mail to
openssl-dev.

**Comment by levitte** [comment]
It seems NOTES.VMS is short of a few edits, as you noticed.  Will fix.

> . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
> This will build and install OpenSSL in the default location, which is:
> [...]
> OpenVMS: SYS$COMMON:[OPENSSL-'version'...], where 'version' is the
> OpenSSL version number with underscores instead of periods.
> . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
> 
> Not a good choice. I don't want this stuff in my SYS$COMMON tree.
> Who does?

Do you have a better idea for a *default* location (i.e. one that's guaranteed to work given enough admin permissions)?  Of course, anyone can choose another location with the `--prefix` option.

> ... Something as simple as "See --prefix and --openssldir, below" would be more helpful. Or more obviously generic examples, like, say "dev:[dir]".

I'll expand the text a bit.

> . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
> [.SYS$STARTUP] Contains startup, login and shutdown scripts.
> These define appropriate logical names and
> command symbols.
> . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
> 
> I'd vote for those changes as being the worst new idea. Dollar signs
> in names like that are (or should be) reserved for the custodians of the
> OS, currently VMS Software, Inc. (https://vmssoftware.com/).

Interestingly enough, the VSI folks haven't said peep about that (and yes, I do talk with them)

> These are not what I'd call "startup" or "shutdown" scripts. As the
> description says, they define/undefine logical names or DCL symbols.

There are other products out in the wild having "startup" scripts that merely set up system logical names.  Mind you, the DCL symbols are set in a different script.

> The VMS section of this could use some work:
> 
>     https://wiki.openssl.org/index.php/Compilation_and_Installation

Note that our wiki is user driven.  You're welcome to contribute.

**Comment by levitte** [comment]
I've a PR coming up that hopefully fixes the issues mentioned here.  @Antinode-org, I welcome you to help reviewing it.  Stay tuned.

**Comment by levitte** [comment]
While looking at this, I found some more documentation faults.  I've apparently forgotten to update certain details as the way of doing things was developped.

**Comment by levitte** [comment]
Fixup commit in #13834, please discuss it there
