### ISSUE TITLE
ASFLAGS is documented, but unused anywhere

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#13784]
I need to pass in some stuff when building .S files in openssl and ASFLAGS is documented but nowhere does it end up being used/defined in compiling .S files.

I can probably work to patch it up myself perhaps this should be addressed in 3.0 and possibly backported to 1.1.1.

**Comment by levitte** [comment]
"anywhere" is untrue.  It's unused in the Unix Makefile template, that's true, but not in the others.  There's a comment to that effect:

https://github.com/openssl/openssl/blob/e211d949cd5737e53cd3399e6a88453930768b98/Configurations/unix-Makefile.tmpl#L283-L288

**Comment by dlegaultbbry** [comment]
What I meant is that there's no bindings in the build system to pass in shared_asflags in project configurations. If you look at the build in the unix-Makefille.tmpl you can't see any CNF_ASFLAGS, LIB_ASFLAGS, DSO_ASFLAGS, etc. This is what I meant by ASFLAGS are not wired in anywhere.

It's not the end of the world as I managed to add all these items so I could get what I wanted.
