### ISSUE TITLE
Endianness-Issue in FIPS provider

### ISSUE THREAD

**Issue by juergenchrist** [openssl/openssl#13782]
OpenSSL master HEAD fails to load FIPS provider on s390 due to endianness problems.
Handling of parameter OSSL_KDF_PARAM_SSHKDF_TYPE caused endianness problems on
s390.  It is not possible to pass FIPS tests since the parameter was stored
with an integer value but read via a cast to char pointer.  While this works
on little endian machines, big endian s390 read the most significant bits
instead of the least significant (as done by, e.g., x86).

See https://github.com/openssl/openssl/pull/13781 for a possible fix.

**Comment by t8m** [comment]
This is now fixed.
