### ISSUE TITLE
Attribute Certificates and AVLs

### ISSUE THREAD

**Issue by JonathanWilbur** [openssl/openssl#13793]
Though the Internet overwhelmingly uses X.509 Certificates for authentication, other similar constructs have been defined in the ITU's Recommendation X.509. Attribute certificates comprise nearly as much of the standard's subject matter as do public key certificates. Authorization and Validation Lists (AVLs) are also a similar construct.

I am interested in implementing AC and AVL decoding from the command-line tool. Ideally, I would like to have new subcommands such as `ac` and `avl` which would display the information from those constructs just like the `x509` subcommand does.

Here is an example of what I am talking about:

```
$ openssl avl -in ./test.avl -inform PEM -noout -text
        Version: 3 (0x2)
        Serial Number:
            b8:65:a6:40:9f:a6:83:1f
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = Test CA
        Constrained: TRUE
        Entries:
        ...
        Extensions:
        ...
```

Would the OpenSSL project be open to me (or somebody) pushing commits that minimally implement Attribute Certificates and AVL decoding from the command line? From a security perspective, this should not increase the attack surface too much, because ACs and AVLs are not used in TLS at all, and the file formats are similar to certificates.

**Comment by t8m** [comment]
I suppose nobody would object to having this in OpenSSL at some point. However right now it is not the best time to try to get this into. It is unlikely to be considered before the 3.0 version is released. So I'd suggest waiting with a PR submission for time when 3.0 is released.

**Comment by JonathanWilbur** [comment]
That sounds great. Thanks!

**Comment by mwiseman32** [comment]
Attribute Certificates are also used in the Trusted Computing Group's [Platform Certificate Specification](https://trustedcomputinggroup.org/resource/tcg-platform-certificate-profile). They are now being supported by most major OEMs to provide assurance in the supply chain. Agree, the OpenSSL team is busy, but an effort to develop this with a future PR at the appropriate time would benefit early adopters and expedite merging at when things settle down.
