### ISSUE TITLE
const XXX_{up,down}_ref ?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#13796]
As dicussed in #13788, OpenSSL sometimes uses `const` in its API, but then casts it away internally.  The `const` indicates that the it's logically constant.

The project should consider making the object pointers in all the up_ref/down_ref function be `const` and then internally cast it away.  See `X509_cmp()` for an example.

**Comment by nhorman** [comment]
The proposal as I read it here is to alter, for example:
```
int EVP_MD_up_ref(EVP_MD *md)
```
Such that it is defined as:
```
int EVP_MD_up_ref(const EVP_MD *md)
```
Is that correct?  I can't  argue that EVP_MD being const here is valid, I'm just not sure I see the value in light of the ABI breakage this introduces.

I agree that it creates a visual cue that indicates to the developer that the EVP_MD pointer in the example above isn't altered, and so might be considered thread safe, but its inclusion certainly isn't definitive

Can you elaborate more on what the value of this change is, to better evaluate it against the abi change impact?

FWIW, We have recently made a proposed coding style change, to being documenting functions using doxygen: https://github.com/openssl/technical-policies/pull/94
it might be reasonable alternate solution to this problem, as we add doxygen comments to add notes about thread safety to them.  That would obviate the need to change the ABI, and just assert that they are in fact thread safe

**Comment by richsalz** [comment]
do whatever you want.
