### ISSUE TITLE
KTLS should not be on by default

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13794]
At the moment KTLS support is not built by default. But if built it is on at runtime by default.

This might cause problems. For example If you are using the FIPS module you might reasonable expect all your crypto to be performed inside the module boundary. However, if you are using a KTLS enabled  build then that might not be the case if libssl decided it can offload things to the kernel.

A suggestion is to switch the KTLS defaults around - so that it is always built by default if possible, but it is disabled at runtime unless you explicitly ask for it.

**Comment by richsalz** [comment]
I don't have a strong view as to whether or not it is compiled by default, but a slight preference for *not* doing so, just like we do for various crypto algorithms, it should be explicitly enabled.

I am opposed to making the run-time be "enabled by default."

Perhaps putting it into the config-file and SSL_conf_cmd support is a good thing to do? That way folks who want it can globally enable it.

**Comment by kroeckx** [comment]
Does that mean the enable should be for an OSSL_LIB_CTX?

**Comment by mattcaswell** [comment]
> Does that mean the enable should be for an OSSL_LIB_CTX?

At the moment it is handled at the SSL_CTX level via the `SSL_MODE_NO_KTLS_TX` and `SSL_MODE_NO_KTLS_RX` modes. These modes default to "on" (if KTLS support has been explicitly enabled at compile time). So, I would envisage keeping it the same but swapping it to be "off" by default at the SSL_CTX level.

**Comment by paulidale** [comment]
The security policy will need to include build instructions -- not building KTLS here seems reasonable.
Not that this would stop somebody who didn't read the instructions...

**Comment by t8m** [comment]
We could keep SSL_MODE_NO_KTLS_* and add SSL_OP_ENABLE_KTLS (there are 3 values left unused which is not much but anyway). This would allow both coarse-grained enablement via the options and the configuration file and fine-grained disablement by the SSL*_set_mode().

**Comment by t8m** [comment]
@mattcaswell what do you think about this proposal? I can implement it if you agree.

**Comment by t8m** [comment]
We could save one OP value by having only one OP to enable but still keep separate MODE values for RX and TX.

**Comment by mattcaswell** [comment]
Do we actually need to separately control the RX and TX?

**Comment by bsdjhb** [comment]
I suspect most users who care about KTLS will be content with a single knob to turn it on or off.  The current tests in sslapi assume that RX and TX can be toggled independently, and I'm aware of some use cases where users may wish to only offload TX but not RX.  For FreeBSD I'm likely to permit that policy to be configured in the kernel however, so separate knobs in OpenSSL aren't strictly required.  OTOH, I didn't add the separate MODE values myself, so am not sure if there are other use cases for treating them separately.

**Comment by mattcaswell** [comment]
In that case, unless someone can come up with a compelling reason for it, I propose removing the separate RX and TX controls and just have a single one covering both.
