### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by vishnuutd** [openssl/openssl#1380]
i am trying to install openssl. i have downloaded the zip file. when i try to type "nmake" in developer command prompt it says "fatal error: makefile not found". i typed "nmake /f makefile.shared". it worked.
 the "nmake test" and "nmake install" options returns errors.
 can someone help please ?

**Comment by mattcaswell** [comment]
You don't say what version of OpenSSL you downloaded. Assuming that it was version 1.0.2 then you should read the INSTALL.W32 file. If it was the 1.1.0 beta then you should read INSTALL.

**Comment by vishnuutd** [comment]
i downloaded the github version of openssl. the installation instructions are vague.

**Comment by mattcaswell** [comment]
You checked it out from github? I assume you mean the master branch? Did you read the INSTALL file? And if so did you run "perl Configure VC-WIN32" (or a similar Windows Configure target listed in INSTALL). Please post the *exact* steps that you ran.

**Comment by vishnuutd** [comment]
i downloaded the mater file from github.
 1. ran developer command prompt for vs2015.
2. in command prompt typed "cd C:\Users\Administrator\Desktop\openssl-master (1)\openssl-master".
3. perl Configure {WIN64I}
   This returned an error 
Configuring OpenSSL version 1.1.0-pre6-dev (0x0x10100006L)
    no-asan         [default]  OPENSSL_NO_ASAN (skip dir)
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG (skip dir)
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE (skip dir)
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-egd          [default]  OPENSSL_NO_EGD (skip dir)
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL (skip dir)
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER (skip dir)
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-ssl3         [default]  OPENSSL_NO_SSL3 (skip dir)
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD (skip dir)
    no-ubsan        [default]  OPENSSL_NO_UBSAN (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS (skip dir)
    no-zlib         [default]
    no-zlib-dynamic [default]
Configuring for {WIN64I}
Warning! target {WIN64I} doesn't exist!
Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-dso] [no-egd] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--config=FILE] os/compiler[:flags]

3. as provided in the installation instructions, next i ran "nmake". this returns an error.
 fatal error U1064: MAKEFILE not found and no target specified
Stop.

4. nmake test
 fatal error U1052: file 'test' not found
Stop.

5.nmake install.
 fatal error U1033: syntax error : 'OPENSSL' unexpected
Stop.

**Comment by mattcaswell** [comment]
Successfully running Configure is a required step for compilation and installation. Your Configure step has errored with the following error message:
````
Warning! target {WIN64I} doesn't exist! 
```

You have the syntax wrong. It should be:

```
perl Configure WIN64I
````

However, unless you are building this on an Itanium machine, you probably more likely want:

````
perl Configure WIN64A
````

**Comment by vishnuutd** [comment]
@mattcaswell 
Configuring for WIN64A
Warning! target WIN64A doesn't exist!

**Comment by mattcaswell** [comment]
Sorry. My bad. I meant:
````
perl Configure VC-WIN64A
````

**Comment by vishnuutd** [comment]
NASM not found - please read INSTALL and NOTES.WIN for further details

**Comment by mattcaswell** [comment]
So, please read those...in particular NOTES.WIN.

**Comment by vishnuutd** [comment]
@mattcaswell  i have read everything twice :P. read it even now. i also downloaded the latest nasm and installed it. still returns nasm not found.

**Comment by mattcaswell** [comment]
If NASM is not on your %PATH% then it won't find it. If you don't know how to check that yourself, most likely logging out and logging back in again will update it for you.

**Comment by vishnuutd** [comment]
i am getting an error when i run nmake.

  IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\ADMINI~1\AppData\Local\Temp\nmD28F.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
bn_mul.obj : error LNK2005: _bn_sub_part_words already defined in bn-586.obj
   Creating library libcrypto.lib and object libcrypto.exp
bn_exp.obj : error LNK2019: unresolved external symbol _bn_mul_mont_gather5 referenced in function _BN_mod_exp_mont_consttime
bn_exp.obj : error LNK2019: unresolved external symbol _bn_scatter5 referenced in function _BN_mod_exp_mont_consttime
bn_exp.obj : error LNK2019: unresolved external symbol _bn_gather5 referenced in function _BN_mod_exp_mont_consttime
bn_exp.obj : error LNK2019: unresolved external symbol _bn_power5 referenced in function _BN_mod_exp_mont_consttime
bn_exp.obj : error LNK2019: unresolved external symbol _bn_get_bits5 referenced in function _BN_mod_exp_mont_consttime
bn_exp.obj : error LNK2019: unresolved external symbol _bn_from_montgomery referenced in function _BN_mod_exp_mont_consttime
e_aes.obj : error LNK2019: unresolved external symbol _bsaes_cbc_encrypt referenced in function _aes_init_key
e_aes.obj : error LNK2019: unresolved external symbol _bsaes_ctr32_encrypt_blocks referenced in function _aes_init_key
e_aes.obj : error LNK2019: unresolved external symbol _bsaes_xts_encrypt referenced in function _aes_xts_init_key
e_aes.obj : error LNK2019: unresolved external symbol _bsaes_xts_decrypt referenced in function _aes_xts_init_key
libcrypto-1_1.dll : fatal error LNK1120: 10 unresolved externals
NMAKE : fatal error U1077: 'link' : return code '0x1'
Stop.

**Comment by levitte** [comment]
You must have had some errors before that.  A related question, did you install perl (ActiveState is supported)?

**Comment by vishnuutd** [comment]
@levitte i installed activeperl 64bit. My computer is a 64bit intel chip machine. and i also ran the following command. perl Configure VC-WIN64A. Can you help me with the exacts steps on how to use this library. also should i have the openssl-master in a c drive ?

**Comment by vishnuutd** [comment]
the latest error am getting is 

fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
NMAKE : fatal error U1077: 'link' : return code '0x1'. i have a 64bit intel machine. if its x86 what are the exact steps i need to run ? @mattcaswell @levitte

**Comment by levitte** [comment]
Ok, it sounds like things got a bit confused along the way, so what I'd suggest is a clean start.  Get a new copy if master into an empty directory, then do the following:

```
perl Configure VC-WIN64A
nmake
```

**Comment by vishnuutd** [comment]
the same error again lol :P but i was able to install 32 bit one. and i cannot resolve a lot functions like
SSL_CTX , SSL_METHOD, OpenSSL_add_all_algorithms(),ERR_load_BIO_strings(),ERR_load_crypto_strings();
SSL_load_error_strings(); is there a sample secure sockets(https server) implementation example using openssl. like a sample c++ or c# code? im very new to openssl.

**Comment by mattcaswell** [comment]
This error:
````
fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
````
Is due to using the wrong MS Developer command prompt for the build. The MS Developer prompt comes in a 32 bit flavour and a 64 bit flavour. If you use the 32 bit one to build 64-bit OpenSSL, or vice-versa, you will get this problem. See:

https://msdn.microsoft.com/en-GB/library/ms229859(v=vs.110).aspx

**Comment by vishnuutd** [comment]
thanks guys :) @mattcaswell the above was the issue. Thanks for helping. i was able to sucessfully install openssl in my computer.
