### ISSUE TITLE
Breaking change: fixed DH key certs

### ISSUE THREAD

**Issue by bbbrumley** [openssl/openssl#13810]
Howdy Folks

In #13772 I mentioned I had some trouble in my reproducer, due to what I thought was a breaking change.

Run this in 111:

```bash
#!/bin/bash

export OPENSSL_CONF=/etc/ssl/openssl.cnf
OPENSSL=openssl

## generate X9.42 DH params
if [ ! -s params.pem ]; then
    $OPENSSL genpkey -genparam -algorithm DH -out params.pem -pkeyopt dh_rfc5114:1 -pkeyopt dh_paramgen_type:1
fi

## CA does this
mkdir -p ca
$OPENSSL req -x509 -sha256 -nodes -newkey rsa:2048 -keyout ca/ca.prv -out ca/ca.pem -subj '/C=FI/ST=Pirkanmaa/L=Tampere/O=CAFoo/CN=localhost'

## client does this
mkdir -p client
$OPENSSL genpkey -paramfile params.pem -out client/alice.prv
$OPENSSL pkey -in client/alice.prv -out client/alice.pub -pubout
$OPENSSL genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out client/fake.prv
$OPENSSL req -new -key client/fake.prv -out client/alice.req -subj '/C=FI/ST=Pirkanmaa/L=Tampere/O=AliceBar/CN=localhost'

## CA does this
$OPENSSL x509 -req -in client/alice.req -CA ca/ca.pem -CAkey ca/ca.prv -force_pubkey client/alice.pub -extensions dh_cert -CAcreateserial -out client/alice.pem
```

Now do a CMS encryption:

```
bbrumley@feldspar:/tmp$ openssl cms -aes128 -encrypt -in /etc/lsb-release -binary -out lsb-release.pem -outform PEM -recip client/alice.pem
bbrumley@feldspar:/tmp$ echo $?
0
bbrumley@feldspar:/tmp$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
bbrumley@feldspar:/tmp$ 
```

So that went swell.

Now try the encryption on master:

```
bbrumley@feldspar:/tmp$ ~/svnrepos/openssl/apps/openssl cms -aes128 -encrypt -in /etc/lsb-release -binary -out lsb-release.pem -outform PEM -recip client/alice.pem
40C77B46F47F0000:error:03000096:digital envelope routines:evp_pkey_asym_cipher_init:operation not supported for this keytype:crypto/evp/asymcipher.c:142:
bbrumley@feldspar:/tmp$ echo $?
3
bbrumley@feldspar:/tmp$ ~/svnrepos/openssl/apps/openssl version
OpenSSL 3.0.0-alpha10-dev  (Library: OpenSSL 3.0.0-alpha10-dev )
bbrumley@feldspar:/tmp$ 
```

So, there appears to be some kind of breaking change. I did not bisect it.

**Comment by t8m** [comment]
This is caused by missing handling of non-legacy keys in cms_pkey_get_ri_type.

**Comment by t8m** [comment]
> This is caused by missing handling of non-legacy keys in cms_pkey_get_ri_type.

Actually no, I was looking at wrong checkout. Investigating further...

**Comment by t8m** [comment]
Please try #13869, it should fix it (with the current master branch).

**Comment by slontis** [comment]
There is a breaking change in 3.0 because DH and DHX are separate key types in the provider.
The -algorithm that you select is the format that it will spit the data out in (for X9.42 you want DHX).

If you want to generate X9.42 param data the correct way in 3.0 is to do: (note you can use group instead of dh_rfc5114)
openssl genpkey -genparam -algorithm DHX -out params.pem -pkeyopt dh_rfc5114:1

OR cutout the middleman altogether and just generate a key using a named group in one pass.
openssl genpkey -algorithm DHX -pkeyopt group:dh_2048_224 -text
