### ISSUE TITLE
AUTHORS is out of date

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#13815]
Many project members are missing.

**Comment by mspncp** [comment]
Has this list been maintained manually, or is there already some script to update the list from, say, the git log?

**Comment by levitte** [comment]
@mspncp, it's maintained manually

**Comment by mspncp** [comment]
So what exactly are the criteria for being mentioned in the AUTHORS file? There does not seem to be an official policy for it. I think we should discuss that in our next OTC meeting.

For the moment, I believe that at least all (former and current) Committers should be in the list. I added the missing ones in #14029.

**Comment by richsalz** [comment]
> For the moment, I believe that at least all (former and current) Committers should be in the list.

Historically that had been the policy.
