### ISSUE TITLE
use one and the same password file for pkcs12 utility

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#13827]
Request is pkcs12 utility to support one and the same "file" for -passin and -passout arguments.

Work-around is simple - for instance: ... -passin file:./filename -passout file:././filename ..., i.e. file is one and the same but filepath is different.

**Comment by levitte** [comment]
There is `-password`, does that satisfy what you want?

**Comment by petrovr** [comment]
Argument -password is "alias" to -passin or -passout and format of argument is specified in ... #13883 .

**Comment by petrovr** [comment]
Closed as is document how it works if "pathname" is same. Same file requires more work and usually is not portable.
