### ISSUE TITLE
Cannot find "aesenc" instruction in disassembly code 

### ISSUE THREAD

**Issue by winter2020** [openssl/openssl#13838]
I compiled AES encryption with static linking, then disassemble it. I cannot find "aesenc" instruction in the disassembly code. Does it mean that my example will not run with AES-NI? My CPU is definitely supported by AES-NI. 

Example code:
```
    AES_KEY key;
    AES_set_encrypt_key(key_buf, 8*KEY_SIZE, &key);
    AES_ecb_encrypt(pt, cp, &key, 1);
```

**Comment by paulidale** [comment]
You need to use the EVP layer calls to access the assembly implementations.  The direct calls here only ever use the C implementation.
