### ISSUE TITLE
How to port/ build openssl on Windows (Visual studio) from source file?

### ISSUE THREAD

**Issue by lijintv07** [openssl/openssl#13839]
I'm am trying to port OpenSSL for windows (Visual Studio) from Source code , without using DLL and Lib. 
Is there any porting guide available or could you give any inputs regarding this.

**Comment by mattcaswell** [comment]
The installation/build guide is here:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/INSTALL

That guide covers all platforms. There are some additional Windows specific notes here:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/NOTES.WIN

**Comment by ganeshkamath89** [comment]
It would be very helpful if the OpenSSL community had a batch file to generate the project file like the solution used in Curl forum.
Reference: https://github.com/curl/curl/tree/master/projects

Expecially since I believe these two projects work very well together.
