### ISSUE TITLE
ERR_PACK cast problem / inconsistent definition (master branch)

### ISSUE THREAD

**Issue by msalle** [openssl/openssl#1383]
Originally ERR_PACK cast all arguments to unsigned long, this was patched in commit c3ddb263315c7196b488f384b3bc82cd474c8698 to no cast and then in commit d82c27589b5f9e9128f1ae9fce89fadd03c1c229 it was partially reverted by explicitly casting the first l (library) argument to unsigned int (instead of long). However, also the f (function) and preferably also the r (reason) arguments should be cast to unsigned since the arguments are normally of int, as advertised in the man page of ERR_PACK: https://github.com/openssl/openssl/blob/master/doc/crypto/ERR_load_strings.pod
Not casting leads to compiler warnings (with -Wsign-conversion):

`include/openssl/err.h:137:59: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]`
`   ( ((unsigned int)((l) & 0x0FF) << 24L) | (((f) & 0xFFF) << 12L) | ((r) & 0xFFF) )`
where the error indicator is under the **second** shift-left.

**Comment by richsalz** [comment]
The masking means the error can't happen, the compiler is wrong.  But we should fix this.

**Comment by richsalz** [comment]
https://github.com/openssl/openssl/pull/1385

**Comment by msalle** [comment]
Thanks for the fix. I agree the compiler is wrong in that the mask prevents the sign flip.
By the way, note  that the code is no longer safe on a platform with 16bits int/32bits long (I don't know if OpenSSL is supported on any of those). Can I suggest to cast to uint32_t instead? I should have suggested that in the first place, I'm sorry...

**Comment by mattcaswell** [comment]
We don't support a 16 bit int. Lots of stuff will break in such an environment.

**Comment by richsalz** [comment]
We don’t support 16bit platforms.  For now long is fine, since the table is a long.  Will fix in the future,  I think.

**Comment by msalle** [comment]
Just a final note: the << will actually work on the level of the unsigned int, the cast to unsigned long is only done afterwards. But as long as you're using at least 32bit integer, there indeed isn't any problem.

**Comment by richsalz** [comment]
Changing from long to uint32_t is a bigger change than we can do this late in the cycle, I think.  But ping @emilia :)

**Comment by msalle** [comment]
How do you mean `long`? In  pull request #1385  you cast to `unsigned int`? That was where I suggested making that explicitly `uint32_t` which is internally the same on x86_64 but safe on any platform...

**Comment by richsalz** [comment]
It's used to build error table definitions and the error table field is a long.

**Comment by mattcaswell** [comment]
It's unclear to me looking at the description here as to whether we are looking at this for 1.1.0 or not. I'm putting it against that milestone for now...@richsalz is that appropriate?

**Comment by richsalz** [comment]
I think a longer-term issue about the ERR API and structures is already recorded.  This simple fix of fixing the casts, in #1385 is for 1.1.0

**Comment by mattcaswell** [comment]
So can I close this in favour of that (lets only track it one place)?

**Comment by richsalz** [comment]
One’s an issue, one’s a PR.  I view it as RT and PR, but YMMV.

**Comment by mattcaswell** [comment]
Still confused. #1385 seems to have been closed, but I can't find it in the repo?

**Comment by richsalz** [comment]
I never pushed :(  Rebased and just pushed it.

**Comment by mattcaswell** [comment]
Ok. So can I change the milestone on this to post 1.1.0?

**Comment by richsalz** [comment]
No, I just pushed it.  It’s done. ☺

**Comment by mattcaswell** [comment]
Ok...so this issue can be closed right?
