### ISSUE TITLE
OSSL_PROVIDER_do_all creating side effects

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#13844]
This pertains to a locally build (linux-x86_64) master (OpenSSL3): The return value of [`OSSL_PROVIDER_available`](https://www.openssl.org/docs/manmaster/man3/OSSL_PROVIDER_available.html) depends on whether (apparently side-effect free `OSSL_PROVIDER_do_all`) has been run before (or not). This is at least unexpected; if there is an explanation, I'd be glad to get it.

Code to reproduce:
```
#include <string.h>

#include <openssl/crypto.h>
#include <openssl/provider.h>

int display_provider(OSSL_PROVIDER *provider, void *cbdata) {
   printf("Provider loaded: %s\n", OSSL_PROVIDER_name(provider));
   return 1;
}

int main(int argc, char *argv[]) {
    OSSL_LIB_CTX *libctx = OSSL_LIB_CTX_new();

    if (!libctx)
        return -1;

    // run this iterator only if two parameters are passed:
    if (argc>2) OSSL_PROVIDER_do_all(libctx, display_provider, NULL);

    if (!OSSL_LIB_CTX_load_config(libctx, "base.cnf"))
        return -1;

    // run this iterator if any parameter is passed:
    if (argc>1) OSSL_PROVIDER_do_all(libctx, display_provider, NULL);

    printf("default provider available: %d\n", 
            OSSL_PROVIDER_available(libctx, "default"));

}

```

Compiled with `gcc -Iinclude bug.c -L. -lcrypto`, this command sequence shows the problem:
```
> LD_LIBRARY_PATH=. ./a.out 
default provider available: 0
> LD_LIBRARY_PATH=. ./a.out 1
Provider loaded: base
default provider available: 0
> LD_LIBRARY_PATH=. ./a.out 1 2
Provider loaded: default
Provider loaded: base
Provider loaded: default
default provider available: 1

```
The first invocation returns as expected: "default" provider is not loaded (as per cnf below).
The second invocation now iterates providers after loading the configuration and only the loaded "base" is shown; "default" is correctly shown as absent.
The final iteration already at the start shows "default" loaded when iterating providers (and subsequently returns a different result in `OSSL_PROVIDER_available`). This does not seem plausible and is not explicable from [the documentation](https://www.openssl.org/docs/manmaster/man3/OSSL_PROVIDER_do_all.html): Or in other words: Why does calling `OSSL_PROVIDER_do_all` cause the "default" provider to be loaded?

`base.cnf` contents:
```
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
base = base_sect

[base_sect]
activate = 1
```

**Comment by mattcaswell** [comment]
This is expected behaviour.

The default provider is a *fallback* provider. This means that, by the time you first try to do something with a provider, if none have been loaded yet (or attempted to be loaded), then the fallback provider is automatically loaded. This is primarily for backwards compatibility reasons. Pre 3.0 applications know nothing about providers and therefore will never load one explicitly. If that happens we just want the default provider to be automatically available.

In your sample code you are attempting to do something with all loaded providers. Since you haven't loaded any explicitly at the point you attempt this the default provider is automatically loaded for you. You subsequently then additionally load another provider (base) when you load the config file and end up with both of them.

**Comment by baentsch** [comment]
As always a perfectly understandable explanation: Thanks. So, did I overlook documentation already explaining this? The statement that misled me was this: "OSSL_PROVIDER_do_all() iterates over all loaded providers, calling cb for each one, with the current provider in provider and the cbdata that comes from the caller." No statement indicating that this function causes the default provider to load if no other provider is present. The text above made me assume that it is a no-op if no provider is present. 

If no other documentation regarding this auto-default-load mechanism exists, allow me to suggest adding such wording (to all functions exhibiting this behaviour if it's not just `OSSL_PROVIDER_do_all`).

**Comment by mattcaswell** [comment]
It could probably do with being more clearly documented.

It is mentioned on the wiki:
https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers

It's mentioned rather obliquely on the `OSSL_PROVIDER-default.pod` page without really explaining what is meant by fallback:

````
The OpenSSL default provider supplies the majority of OpenSSL's diverse
algorithm implementations.  It also acts as a fallback when no other
provider has been loaded.
````

It's also mentioned in the documentation for the "null" provider (!) on the provider.pod page:
````
The null provider is built in as part of the F<libcrypto> library. It contains
no algorithms in it at all. When fetching algorithms the default provider will
be automatically loaded if no other provider has been explicitly loaded. To
prevent that from happening you can explicitly load the null provider.
````

I'd suggest we should add a clearer explanation on the `OSSL_PROVIDER-default.pod` page. Probably functions that trigger this fallback mechanism should briefly mention that this occurs and refer to the `OSSL_PROVIDER-default.pod` for further details. provider.pod should probably also have a more explicit discussion on this.

**Comment by baentsch** [comment]
That would make sense. Will you do that or shall I make a proposal?

**Comment by mattcaswell** [comment]
> That would make sense. Will you do that or shall I make a proposal?

If you want to do it the please do!! I probably won't get to it for a while.

**Comment by baentsch** [comment]
So now done: Basically I lifted the text from the Wiki: That was crystal clear... but I won't be the only one just relying on manpages, so I did this PR regardless... I also updated a missing return value documentation for `OSSL_PROVIDER_do_all()` while going through the pages more carefully... Hope that "feature creep" is acceptable and not a separate issue/PR should've been done (?).

**Comment by mattcaswell** [comment]
> Hope that "feature creep" is acceptable and not a separate issue/PR should've been done (?).

Yeah, that's fine. Thank you!
