### ISSUE TITLE
"Fully compliant implementation of RFC8446 (TLSv1.3)" statement is a bit too strong

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#13864]
`NEWS.md` currently says: 
> Fully compliant implementation of RFC8446 (TLSv1.3)

According to https://github.com/openssl/openssl/issues/4449#issuecomment-748355999:
> Technically we're not actually fully compliant -- we decided to continue to allow/offer (e.g.) DSA even for non-TLS-1.3 connections in order to preserve our API stability, despite there being a "MUST NOT" in the list at the end of https://tools.ietf.org/html/rfc8446#section-4.2.3 . There might be one or two other points of divergence, but that's the one I remember the most.

There can be good reason for not being _fully_ compliant, but then one must not claim full compliance.
Otherwise potential users trusting this statement may later find out the hard way that certain aspects are not fulfilled.

Let's be fair to users and state upfront which (known) deviations exist (or at least tune down the word "fully"),
to prevent needless work by others to figure out that there are exceptions, and where they are.

BTW, a related topic is which _optional_ features are supported.
Would be really nice to provide a list making clear which of them are supported (to which extent) or not.
For instance, support for the "status_request" extension (for OCSP responses)  is not mandatory,
and so far OpenSSL only supports the classical "OCSP stapling" of the server cert (but not of intermediate certs nor any client certs).

**Comment by tomato42** [comment]
Duplicate of #13863 ?

**Comment by DDvO** [comment]
Oops, yes. I had problem with the browser connection when filing the issue. So closing this.
