### ISSUE TITLE
Android build of 1.1.1 broken with new r22 NDK

### ISSUE THREAD

**Issue by saurik** [openssl/openssl#13877]
When using the new r22 Android NDK, OpenSSL Configure prints `$ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle is invalid at (eval 7)[openssl/Configure:3018] line 37.` as neither $ndk/platforms nor $ndk/AndroidVersion.txt exist.

This bug has probably already been addressed by 948fd7af627f42cf9ab6b7c3df34aa5ebad422ae ("Support for Android NDK r22-beta1"); but, as far as I can tell, that patch is only in master for 3.0.0 and hasn't been backported to 1.1.1.

**Comment by truboxl** [comment]
Checking for $ndk/platforms is broken in r22 because:
```The deprecated <NDK>/platforms and <NDK>/sysroot directories have been removed. These directories were merged and relocated into the toolchain during r19. The location of these contents should not be relevant to anyone, including build systems, since the toolchain handles them implicitly. If you are using a build system that hasn't adapted to the changes introduced in NDK r19, file a bug with your build system maintainer. See the Build System Maintainers Guide for information on using the NDK in your own build system.``` https://github.com/android/ndk/wiki/Changelog-r22

I think we need to wait for https://github.com/openssl/openssl/pull/13694

**Comment by zhuxiaoguang** [comment]
openssl3.0 支持 ndk r22了, 1.1.1版本的我这边使用r21e是可以编译通过的。

**Comment by saurik** [comment]
I wish there were a way for me to more easily just bypass the OpenSSL build system here and pass my own flags, as the Configure script was awkward before anyway--it doesn't parse my ABI-annotated -target and insists on my passing -D__ANDROID_ABI__, which it then also sets (and which isn't how you are supposed to do that AFAIK)--but now it is forcing my entire project to be stuck being compatible with some extremely old version of LLVM so I can compile this one extremely-key dependency correctly for this one platform :(. I am probably just going to have to give up and figure out what files are being compiled and try to bypass the build scripts entirely soon.

**Comment by saurik** [comment]
This (my) issue was a duplicate of #13685 and has now been fixed by #13694 \o/.
