### ISSUE TITLE
OCSP_REQ_CTX API is quite broken going from 1.0.2 to 3.0.0

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#13873]
This relates somewhat to https://github.com/openssl/openssl/issues/12234, I suggest familiarizing oneself with the broad strokes of the discussion there before reading any further.

I have some application code that contains approximately the following snippet. Note that I've stripped error handling and surrounding context, so this cannot be considered a reproduction artifact, but hopefully it is more useful for discussion purposes.

```
OCSP_REQ_CTX* ctx = OCSP_sendreq_new(some_bio, some_path_string, NULL, -1);
OCSP_REQ_CTX_add1_header(ctx, "Host", some_hostname_string);
OCSP_REQ_CTX_set1_req(ctx, some_ocsp_request);
OCSP_sendreq_nbio(some_ocsp_response, ctx);
```

The reason it is written this way is that in some cases other headers (besides just "Host") are added and the man page states

> OCSP_REQ_CTX_add1_header() adds header name with value value to the context rctx. It can be called more than once to add multiple headers. It MUST be called before any calls to OCSP_sendreq_nbio(). The req parameter in the initial to OCSP_sendreq_new() call MUST be set to NULL if additional headers are set.

Now, out of the gate, OCSP_REQ_CTX_set1_req() is deprecated starting in a recent 3.0.0 alpha (9 or 10, don't remember off-hand). Now the man page tells me exactly how to handle that:

> OCSP_REQ_CTX_set1_req(rctx, req) is equivalent to the following: [...]

This actually leads to the first unacceptable API breakage: OCSP_REQ_CTX_i2d() takes *three* arguments in 1.0.2 (though the function is not explicitly documented in 1.0.2, it is publicly accessible), now it takes *four*, without ever having been walked through any kind of deprecation process to my knowledge. This is actually tangential to the most central aspect of the issue at hand, but this class of API breakage shows up again later in this discussion as well.

Anyway, if I make the OCSP_REQ_CTX_set1_req->OCSP_REQ_CTX_i2d change (conditionally including the "application/ocsp-request" parameter on a version-check ifdef), the above snippet still works fine against 1.0.2 and compiles without any warnings against 3.0.0.

However, against 3.0.0 the response I get back from the server is telling me that I have a malformed request. This is happening because OCSP_sendreq_new() behaves in a significantly different way in 3.0.0 compared to 1.0.2, which interacts badly with the other APIs I am subsequently using. The way I can prove that / the way I work around it starts by examining the 1.0.2 implementation:

```
OCSP_REQ_CTX *rctx = NULL;
rctx = OCSP_REQ_CTX_new(io, maxline);
if (!rctx)
    return NULL;

if (!OCSP_REQ_CTX_http(rctx, "POST", path))
    goto err;

if (req && !OCSP_REQ_CTX_set1_req(rctx, req))
    goto err;

return rctx;
```

Ok... so I'm passing a NULL request here anyway, so discounting the error handling I should basically be able to simply replace my OCSP_sendreq_new() call with a call to OCSP_REQ_CTX_new() & OCSP_REQ_CTX_http(). Those are both public symbols in 1.0.2 (though again undocumented), so should be fine.

But of course not. Because both of those APIs take a completely different set of arguments in 3.0.0 compared to 1.0.2. Two more unacceptable API breakages. Frustrating.

Anyway, if I replace the OCSP_sendreq_new() from above with the following when compiling against 3.0.0, then I actually get back a valid response from the OCSP server (ie, my request is no longer malformed):

```
OCSP_REQ_CTX *ctx = OCSP_REQ_CTX_new(some_bio, some_bio, 0, -1, 0, 0, NULL, 1);
OCSP_REQ_CTX_http(ctx, NULL, NULL, some_path_string);                                             
```

My guess is that there was some duplication of the headers in the 3.0.0 case (based on a cursory examination of the 3.0.0 implementation of OCSP_sendreq_new()).

I think that pretty much of all of this mess was caused by https://github.com/openssl/openssl/commit/29f178bddfdbd11218fbcba0b8060297696968e3. I hate pointing fingers and making a suggestion like this because it's very easy for things to get personal and distractions to arise, but IMO that commit should really be given a serious reexamination with particular emphasis on potential API / ABI breakages.

**Comment by mattcaswell** [comment]
This does appear to be a problem.

Somehow I missed the breaking API changes introduced in #10667.

@DDvO care to comment on this? It looks like we need to reintroduce the original API function declarations (possibly creating new "_ex" versions, in order to add the additional arguments).

**Comment by levitte** [comment]
So as not to create another mess, I'd suggest that we allow #13742 to be merged first, and fix back the API after.  There's a risk that #13742 becomes overly entangled otherwise.

**Comment by mattcaswell** [comment]
> So as not to create another mess, I'd suggest that we allow #13742 to be merged first, and fix back the API after. There's a risk that #13742 becomes overly entangled otherwise.

Agreed

**Comment by DDvO** [comment]
Thanks @jwalch for your detailed error report.
I was already about to write that this issue is related also to #13742, 
which properly deprecates and documents also the formerly undocumented legacy OCSP HTTP functions.

Yes, although undocumented, the number of parameters of  `OCSP_REQ_CTX_i2d()` should not have changed.
This is an oversight for which I apologize. 
I'll fix this as soon as #13742 is finished and merged, which should happen within the next couple of days.

For `OCSP_sendreq_new()` I changed the implementation in order to take advantage of the meanwhile strengthened implementation while of course aiming at semantic compatibility. Sorry to hear that this did not work out fully.
I'm going to fix this as well when #13742 is merged.

**Comment by levitte** [comment]
While fixing, would you mind renaming `OSSL_HTTP_REQ_CTX_header` -> `OSSL_HTTP_REQ_CTX_http`, seeing that this function sets the *HTTP command*, which isn't a header?
(the old name was `OCSP_REQ_CTX_http`, btw...).
As currently named, I find this function much to easy to confuse with `OSSL_HTTP_REQ_CTX_add1_header`...

**Comment by DDvO** [comment]
I found the old name `OCSP_REQ_CTX_http` pretty unclear if not confusing (for instance, it could have been misunderstood as if it was doing an HTTP transfer) and therefore renamed it to `OSSL_HTTP_REQ_CTX_header` when updating the name prefix.
Therefore I would not like to rename it (essentially) back to `OSSL_HTTP_REQ_CTX_http`.

The new documentation added by #13742 nicely says:
```
OSSL_HTTP_REQ_CTX_header() adds an HTTP request line to the request context.
```

> seeing that this function sets the HTTP command, which isn't a header?

I meanwhile understand that the HTTP request line (which includes the method) is not considered part of the header.
So I suggest renaming it to `OSSL_HTTP_REQ_CTX_set_request_line`, which is much more to the point.

I will also correct the brief internal documentation of the function in `http_client.c` which currently says:
```
 * Create HTTP header using given op and path (or "/" in case path is NULL).
```
to
```
 * Create HTTP request line using the given |ctx| and |path| (or "/" in case |path| is NULL).
```

**Comment by levitte** [comment]
> So I suggest renaming it to `OSSL_HTTP_REQ_CTX_set_request_line`, which is much more to the point.

Yes, even better!

**Comment by DDvO** [comment]
@jwalch, in anticipation of #13742 being merged soon,
I've already tentatively fixed all the issues you reported here 
in https://github.com/siemens/openssl/tree/fix_13873_HTTP_method_API:
```
    OCSP HTTP: Restore API of undocumented and recently deprecated functions
    
    Restore parameters of OCSP_REQ_CTX_new(), OCSP_REQ_CTX_http(), OCSP_REQ_CTX_i2d().
    Un-deprecate OCSP_REQ_CTX_set1_req() because it is helpful also for internal use.
    Fix a bug (wrong HTTP method selected on req == NULL in OCSP_sendreq_new().
```
I'll submit this as a PR as soon as possible (likely tomorrow) but you might already have a look at it.
