### ISSUE TITLE
ASN1 Generation for OtherName parameter using UnstructuredName is incorrect

### ISSUE THREAD

**Issue by cmdli** [openssl/openssl#13881]
I generated a new certificate signing request with this config and command:

```
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = req_ext

[ dn ]
CN=Blah

[ req_ext ]
subjectAltName = @altNames

[ altNames ]
otherName = 1.2.840.113549.1.9.2;UTF8:blah
```
```
openssl req -new -out test.csr -config config.txt -nodes
```

`1.2.840.113549.1.9.2` here is the UnstructuredName attribute defined in https://tools.ietf.org/html/rfc2985#section-5. This generated a CSR with this structure in the subjectAltNames field:
```
    0:d=0  hl=2 l=  21 cons: SEQUENCE          
    2:d=1  hl=2 l=  19 cons:  cont [ 0 ]        
    4:d=2  hl=2 l=   9 prim:   OBJECT            :unstructuredName
   15:d=2  hl=2 l=   6 cons:   cont [ 0 ]        
   17:d=3  hl=2 l=   4 prim:    UTF8STRING        :blah
```

However, according to https://tools.ietf.org/html/rfc5280#section-4.2.1.6, the OtherName attribute should be a Sequence, like this structure generated by [PKIjs](https://github.com/PeculiarVentures/PKI.js):
```
    0:d=0  hl=2 l=  75 cons: SEQUENCE          
    2:d=1  hl=2 l=  73 cons:  cont [ 0 ]        
    4:d=2  hl=2 l=  71 cons:   SEQUENCE          
    6:d=3  hl=2 l=   9 prim:    OBJECT            :unstructuredName
   17:d=3  hl=2 l=  58 cons:    cont [ 0 ]        
   19:d=4  hl=2 l=  56 prim:     UTF8STRING        :blah
```

Unless there's some justification which I don't know about (which is entirely possible), this seems to go against spec. Am I missing something, or is this a bug?

The full asn1parse of the CSR is below:
```
    0:d=0  hl=4 l= 645 cons: SEQUENCE          
    4:d=1  hl=4 l= 365 cons:  SEQUENCE          
    8:d=2  hl=2 l=   1 prim:   INTEGER           :00
   11:d=2  hl=2 l=  15 cons:   SEQUENCE          
   13:d=3  hl=2 l=  13 cons:    SET               
   15:d=4  hl=2 l=  11 cons:     SEQUENCE          
   17:d=5  hl=2 l=   3 prim:      OBJECT            :commonName
   22:d=5  hl=2 l=   4 prim:      UTF8STRING        :Blah
   28:d=2  hl=4 l= 290 cons:   SEQUENCE          
   32:d=3  hl=2 l=  13 cons:    SEQUENCE          
   34:d=4  hl=2 l=   9 prim:     OBJECT            :rsaEncryption
   45:d=4  hl=2 l=   0 prim:     NULL              
   47:d=3  hl=4 l= 271 prim:    BIT STRING        
  322:d=2  hl=2 l=  49 cons:   cont [ 0 ]        
  324:d=3  hl=2 l=  47 cons:    SEQUENCE          
  326:d=4  hl=2 l=   9 prim:     OBJECT            :Extension Request
  337:d=4  hl=2 l=  34 cons:     SET               
  339:d=5  hl=2 l=  32 cons:      SEQUENCE          
  341:d=6  hl=2 l=  30 cons:       SEQUENCE          
  343:d=7  hl=2 l=   3 prim:        OBJECT            :X509v3 Subject Alternative Name
  348:d=7  hl=2 l=  23 prim:        OCTET STRING      [HEX DUMP]:3015A01306092A864886F70D010902A0060C04626C6168
  373:d=1  hl=2 l=  13 cons:  SEQUENCE          
  375:d=2  hl=2 l=   9 prim:   OBJECT            :sha256WithRSAEncryption
  386:d=2  hl=2 l=   0 prim:   NULL              
  388:d=1  hl=4 l= 257 prim:  BIT STRING  
```

And I parsed the subjectAltName with:
```
openssl asn1parse -i -in test.csr -strparse 348
```

**Comment by kroeckx** [comment]
OpenSSL just puts in ASN1 what you've told it to do, you give it an OID and the data it needs to put there, and you told it to use an UTF8STRING.

What I see is:
```
OtherName ::= SEQUENCE {
        type-id    OBJECT IDENTIFIER,
        value      [0] EXPLICIT ANY DEFINED BY type-id }
```

And you say that the OID you used is for an unstructuredName. So the "ANY DEFINED BY" is seems to be:
```
unstructuredName ATTRIBUTE ::= {
           WITH SYNTAX PKCS9String {pkcs-9-ub-unstructuredName}
           EQUALITY MATCHING RULE pkcs9CaseIgnoreMatch
           ID pkcs-9-at-unstructuredName
   }

   PKCS9String { INTEGER : maxSize} ::= CHOICE {
           ia5String       IA5String (SIZE(1..maxSize)),
           directoryString DirectoryString {maxSize}
   }
```

I don't see anything about a sequence there.

**Comment by kroeckx** [comment]
Of course I'm missing this part:
```
Attribute               ::= SEQUENCE {
      type             AttributeType,
      values    SET OF AttributeValue }
            -- at least one value is required
```

**Comment by cmdli** [comment]
If I'm understanding this correctly, I believe there should be two sequences in SubjectAltName: one for GeneralNames and one for OtherName.

```
   SubjectAltName ::= GeneralNames

   GeneralNames ::= SEQUENCE SIZE (1..MAX) OF GeneralName

   GeneralName ::= CHOICE {
        otherName                       [0]     OtherName,
        rfc822Name                      [1]     IA5String,
        dNSName                         [2]     IA5String,
        x400Address                     [3]     ORAddress,
        directoryName                   [4]     Name,
        ediPartyName                    [5]     EDIPartyName,
        uniformResourceIdentifier       [6]     IA5String,
        iPAddress                       [7]     OCTET STRING,
        registeredID                    [8]     OBJECT IDENTIFIER }

   OtherName ::= SEQUENCE {
        type-id    OBJECT IDENTIFIER,
        value      [0] EXPLICIT ANY DEFINED BY type-id }
```

So, theoretically, the ASN1 should look like this:

```
    0:d=0  hl=2 l=  75 cons: SEQUENCE                               // SubjectAltName
    2:d=1  hl=2 l=  73 cons:  cont [ 0 ]        
    4:d=2  hl=2 l=  71 cons:   SEQUENCE                             // OtherName
    6:d=3  hl=2 l=   9 prim:    OBJECT            :unstructuredName // type-id
   17:d=3  hl=2 l=  58 cons:    cont [ 0 ]                          // value
   19:d=4  hl=2 l=  56 prim:     UTF8STRING        :blah

```

Instead, it looks like this:
```
    0:d=0  hl=2 l=  21 cons: SEQUENCE          
    2:d=1  hl=2 l=  19 cons:  cont [ 0 ]        
    4:d=2  hl=2 l=   9 prim:   OBJECT            :unstructuredName
   15:d=2  hl=2 l=   6 cons:   cont [ 0 ]        
   17:d=3  hl=2 l=   4 prim:    UTF8STRING        :blah
```
At least, that's my current understanding.

**Comment by kroeckx** [comment]
You need to tell OpenSSL what it needs to generate, see the ASN1_generate_nconf() manpage. I'm not sure what needs to be generated.

**Comment by kroeckx** [comment]
One thing that maybe wasn't clear is that this line:
```
 2:d=1  hl=2 l=  73 cons:  cont [ 0 ]
```
Is the sequence for OtherName that contains the OID and value, and you seem to want to add a new sequence in that sequence.

**Comment by cmdli** [comment]
Thanks for the help! I'll start taking a look at telling OpenSSL how to generate the correct ASN1 in the config file. Out of curiosity, is it also possible to tell OpenSSL how to correctly parse OtherName with `openssl req`? Currently, when it tries to parse the OtherName parameter, its gives out a bunch of random junk for SubjectAltName:

```
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: CN=Chris
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    <modulus>
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
            X509v3 Subject Key Identifier: 
                67:FB:F5:5A:60:88:CA:B6:4E:15:7F:ED:55:0D:30:CF:AC:A8:58:00
            X509v3 Subject Alternative Name: 
....:.8GGRS2PZN2PRTXLYHDBMWDR7GIPFSBNPEHFBLOYUVALHGZ4NMMRVA====
    Signature Algorithm: rsassaPss
         Hash Algorithm: sha256
         Mask Algorithm: mgf1 with sha256
         Salt Length: 0x20
         Trailer Field: 0xBC (default)

         <signature>
```

**Comment by davidben** [comment]
OpenSSL's encoding is correct. The SEQUENCE tag from OtherName is supposed to be omitted when wrapped in a GeneralName because the module defining GeneralName uses implicit tagging ("DEFINITIONS IMPLICIT TAGS ::="), and the GeneralName structure doesn't specify anything else.

This is, sadly, a rather confusing corner of ASN.1. Let's Encrypt has a nice overview of ASN.1 which discusses implicit vs explicit tagging and how you determine which is used where. (They're missing an even more confusing rule about CHOICE types, but OtherName is not a CHOICE type, so you don't have to worry about it here.)
https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/

**Comment by davidben** [comment]
(I don't think what ASN.1 specified in the config file would affect this. That controls the value field of the OtherName, whereas the question here is about the OtherName structure itself. That part is something OpenSSL knows about and encodes on its own.)

**Comment by davidben** [comment]
By the way, if PKIjs is including the implicit SEQUENCE tag, you may want to file a bug on their end. It's possible they've gotten the tagging wrong.

**Comment by kroeckx** [comment]
With that junk, I assume that it's not actually properly encoded,
and might be with the extra sequence in it. It should output:
"othername:<unsupported>". And least that's what it does with x509,
I assume req does the same.

I have a certificate that has:
            X509v3 Subject Alternative Name:
                email:EMAIL, othername:<unsupported>

Which asn1parse shows as:
    0:d=0  hl=2 l=  42 cons: SEQUENCE
    2:d=1  hl=2 l=  29 prim:  cont [ 1 ]
   33:d=1  hl=2 l=   9 cons:  cont [ 0 ]
   35:d=2  hl=2 l=   3 prim:   OBJECT            :description
   40:d=2  hl=2 l=   2 cons:   cont [ 0 ]
   42:d=3  hl=2 l=   0 prim:    PRINTABLESTRING   :

**Comment by davidben** [comment]
@kroeckx do you mean the output in https://github.com/openssl/openssl/issues/13881#issuecomment-763158654? I think that may be OpenSSL trying to parse an incorrectly-encoded GeneralName.otherName, from whatever other software (PKIjs?) that @cmdli is using. @cmdli, is that right?

When I run the command from the original report, `openssl req` manages to parse it back out just fine.

I think this bug has correctly identified that OpenSSL and the other software disagree on how to encode GeneralName.otherName. But I believe the error is in the other software, not OpenSSL.

**Comment by cmdli** [comment]
@davidben Yes, that garbled output is from a CSR generated by PKIjs. I'll be taking a closer look and maybe filing a bug with them.

**Comment by kroeckx** [comment]
Yes, I think we agree that the other software is doing it wrong.

But it's also still unclear to me what is expected for the UnstructuredName. I think it's a PKCS9String, which is a CHOICE between ia5String and directoryString, where directoryString can be an UTF8String. So I think the "UTF8:blah" is wrong.

**Comment by davidben** [comment]
Oh, I see. I don't think that would affect the output in `openssl req` since OpenSSL doesn't parse OtherName values anyway. (It doesn't look like PKCS9String adds any tags to the ia5String and directoryString CHOICE arms. Rather it relies on the two arms having disjoint tag sets. So just emitting a UTF8String tag plain is right.)

**Comment by kroeckx** [comment]
So in conclusion, there was no problem on the OpenSSL side, and
the config file he used was also correct.

**Comment by cmdli** [comment]
I am closing this issue since my personal questions/issue have been resolved. Thank you!
