### ISSUE TITLE
  How openssl 3.0 do fips integrity check for static library?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#13891]
Hi,
    I found that openssl3.0 do integrity check for shared library by open the library and check whether the mac of shared library matches the value in the *.hmac file.
   But how openssl3.0 do this check for static library  libfips.a?
   And I found openssl doesn't do integrity check on shared library load, but  do it in provider init, does this way compliance with FIPS140-2?

**Comment by richsalz** [comment]
OpenSSL 3.0 only supports shared library FIPS provider; if you use a static library, then you have to get your own validation.

The way it verifies the HMAC is valid and has been verified with the lab that will be doing the certification.
