### ISSUE TITLE
How SNI is derived

### ISSUE THREAD

**Issue by nmathew** [openssl/openssl#13890]
**I want to know how the SNI is derived...**

**IN all these cases I am using 
"openssl s_client -connect k8s-registry.test.local:443" command**

1)
—
GET https://k8s-registry.test.local:443/v2/_catalog HTTP/1.1
Host: k8s-registry.test.local
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

HTTP/1.1 401 Unauthorized
Server: nginx/1.17.10
Date: Fri, 15 Jan 2021 09:36:36 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 145
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Basic realm="docker-registry-realm"
Strict-Transport-Security: max-age=15724800; includeSubDomains

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[
{"Type":"registry","Class":"","Name":"catalog","Action":"*"}

]}]}
closed

2)
—
GET https://k8s-registry.test.local:443/v2/_catalog HTTP/1.1
Host: evil.com
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

HTTP/1.1 401 Unauthorized
Server: nginx/1.17.10
Date: Fri, 15 Jan 2021 09:37:17 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 145
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Basic realm="docker-registry-realm"
Strict-Transport-Security: max-age=15724800; includeSubDomains

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[
{"Type":"registry","Class":"","Name":"catalog","Action":"*"}

]}]}
closed

3)
—
GET /v2/_catalog HTTP/1.1
Host: k8s-registry.test.local
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

HTTP/1.1 401 Unauthorized
Server: nginx/1.17.10
Date: Fri, 15 Jan 2021 09:37:48 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 145
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Basic realm="docker-registry-realm"
Strict-Transport-Security: max-age=15724800; includeSubDomains

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[
{"Type":"registry","Class":"","Name":"catalog","Action":"*"}

]}]}
closed

4)
—
GET /v2/_catalog HTTP/1.1
Host: evil.com
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

HTTP/1.1 404 Not Found
Server: nginx/1.17.10
Date: Fri, 15 Jan 2021 09:38:27 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: close
Strict-Transport-Security: max-age=15724800; includeSubDomains

default backend - 404closed

5)
—
GET https://evil.com:443/v2/_catalog HTTP/1.1
Host: evil.com
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

HTTP/1.1 404 Not Found
Server: nginx/1.17.10
Date: Fri, 15 Jan 2021 09:39:04 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: close
Strict-Transport-Security: max-age=15724800; includeSubDomains

default backend - 404closed

6)

GET https://evil.com:443/v2/_catalog HTTP/1.1
Host: k8s-registry.test.local
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

HTTP/1.1 404 Not Found
Server: nginx/1.17.10
Date: Fri, 15 Jan 2021 09:39:36 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: close
Strict-Transport-Security: max-age=15724800; includeSubDomains

default backend - 404closed

**Then from HTTP 1.1 spec**

**https://tools.ietf.org/html/rfc2616#section-5.2**

The Resource Identified by a Request

The exact resource identified by an Internet request is determined by
examining both the Request-URI and the Host header field.

An origin server that does not allow resources to differ by the
requested host MAY ignore the Host header field value when
determining the resource identified by an HTTP/1.1 request. (But see
section 19.6.1.1 for other requirements on Host support in HTTP/1.1.)

An origin server that does differentiate resources based on the host
requested (sometimes referred to as virtual hosts or vanity host
names) MUST use the following rules for determining the requested
resource on an HTTP/1.1 request:

    If Request-URI is an absoluteURI, the host is part of the
    Request-URI. Any Host header field value in the request MUST be
    ignored.

    If the Request-URI is not an absoluteURI, and the request includes
    a Host header field, the host is determined by the Host header
    field value.

**How SNI is derived in this case? SNI is used as host, hence it is used in ingress routing...**

**Comment by kroeckx** [comment]
I'm not sure why you talk about HTTP or quote an HTTP RFC, it's not relevant. SNI happens at the TLS layer, not the HTTP layer.

You can set the SNI hostname in s_client using -servername, and it defaults to the hostname you provided with -connect since 1.1.1. I think in older versions s_client did not send an SNI by default.

But I assume you want to set it with something other that s_client, in which case you need to call SSL_set_tlsext_host_name().

**Comment by nmathew** [comment]
Thanks you Closing the issue
