### ISSUE TITLE
Public keys decoded from an X509 certificate are legacy keys

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13893]
When we decode an X509 certificate, the public key contained within it is decoded by the internal function `x509_pubkey_decode`:

https://github.com/openssl/openssl/blob/47b784a41b729d5df9ad47c99355db2f2026a709/crypto/x509/x_pubkey.c#L181-L214

This firstly takes the algorithm and uses `OBJ_obj2nid` to find a nid for it. This is the first problem. What if the algorithm comes from a provider and we don't have a nid for that algorithm? Once we have the nid we call `EVP_PKEY_set_type` which has the effect of setting the ameth on the EVP_PKEY. Subsequently we then call `ameth->pub_decode` to decode it - which obviously gives us a legacy key.

Instead we somehow need to find a decoder from a provider that is associated with the algorithm OID and use that (perhaps using "capabilities"?). Once we have the decoder we can use that to create a provider side key.

**Comment by mattcaswell** [comment]
Ping @levitte....your thoughts??

**Comment by mattcaswell** [comment]
@baentsch - I think this is directly relevant to the what you are trying to do.

**Comment by baentsch** [comment]
> I think this is directly relevant to the what you are trying to do.

It is. Another spot (didn't hit on that one yet, so thanks for the heads-up) adding to several places where I found fixed tables I'm unsure how to "open up" for provider-populated sig data structures :-/

**Comment by levitte** [comment]
I have avoided diving too deep into X509 with regards to keys. I made an attempt once early, and found a number of unsavory corner cases... they had me back away.

The idea was anyway that legacy keys should be possible to use, and I'm not familiar with @baentsch' problem, so can't really say.

It looks, however, like we're having a trend shift toward trying our utmost to have provider side keys everywhere. That's additional time before getting to beta1...

**Comment by levitte** [comment]
Speaking of OIDs, an idea is to make them part of the name string.

"BLARGH:1.2.3.4"

Why complicate things further?

**Comment by mattcaswell** [comment]
> The idea was anyway that legacy keys should be possible to use, and I'm not familiar with @baentsch' problem, so can't really say.

@baentsch is writing a provider for algorithms that we don't currently have in OpenSSL. Those include signature algorithms that need to be present in X509 certs.

**Comment by mattcaswell** [comment]
> Speaking of OIDs, an idea is to make them part of the name string.

You mean as an alias for the usual name? Hmm...that might work.

**Comment by levitte** [comment]
> You mean as an alias for the usual name? Hmm...that might work.

Exactly. After all, and OID is conceptually just another identifier, or name, albeit numeric.

**Comment by kroeckx** [comment]
A provider could register the OID with OBJ_create() and get an
NID, I don't see that part as being a problem.

**Comment by mattcaswell** [comment]
> A provider could register the OID with OBJ_create() and get an
NID, I don't see that part as being a problem.

That would require the provider to be linked against libcrypto which might not be the case...unless we were to make OBJ_create() an upcall, which could work. But that doesn't help us to associate the nid with the provider.

**Comment by kroeckx** [comment]
> I'm unsure how to "open up" for provider-populated sig data structures :-/

I'm not sure what the problem is that you're trying to fix. You
can create your own ASN.1 structures. If you need help, it's
probably best to open an other issue for that.

**Comment by levitte** [comment]
I really don't see why a provider should go through OBJ_create, or why the application (or libcrypto) should have to use yet another way to fetch an algorithm via an OID. How about this?

EVP_CIPHER_fetch(NULL, "1.2.3.4", NULL) 

OBJ_obj2txt() can help convert an ASN1_OBJECT to a numeric string where needed.

**Comment by levitte** [comment]
I finally got around to handle this.  See #13994.
