### ISSUE TITLE
Should secure BIGNUM be used to store private keys and if so, why doesn't EC_generate_key?

### ISSUE THREAD

**Issue by lumip** [openssl/openssl#13892]
I seem to be a bit uncertain about the semantics of the secure BIGNUM (i.e. BIGNUMs created via `BN_secure_new`, using `OPENSSL_secure_malloc` internally) but the name suggests that this should be used to store sensitive information such as private keys. This is somewhat confirmed looking at [`rsa_builtin_keygen`](https://github.com/openssl/openssl/blob/76ed0c0ad119569f6e6f6c96b27b76d3b110413b/crypto/rsa/rsa_gen.c#L64) which uses `BN_secure_new` to intialize all sensitive members of the RSA structure (in OpenSSL 1.1.1i).

However, in constrast to that, the [`ec_key_simple_generate_key`](https://github.com/openssl/openssl/blob/76ed0c0ad119569f6e6f6c96b27b76d3b110413b/crypto/ec/ec_key.c#L199) creates an "insecure" BIGNUM using `BN_new` for the private key. Why is that? What is the difference that requires `BN_secure_new` to be used for RSA keys but allows regular BN_new for EC keys?

**Comment by t8m** [comment]
BN_secure_new should be used with all private keys.

This is already fixed in master. The question is whether this is something that can be called a bug and thus it is eligible for fix in 1.1.1 branch.

**Comment by lumip** [comment]
Alright, thanks for clarifying this. If creation with `BN_secure_new` is seen as bringing relevant security improvements, I would see this as a bug. The private keys of ECC would be less secure than RSA used from high-level APIs, which is unexpected.

For me personally, however, it seems for now I can work around this by setting an empty secure BIGNUM as private key (using `EC_KEY_set_private_key`) before invoking the key generation.

**Comment by romen** [comment]
OTC discussed this, and does not consider this a security issue for `1.1.1`.
