### ISSUE TITLE
OCSP responder app is trying to read OCSP_RESPONSE instead of OCSP_REQUEST

### ISSUE THREAD

**Issue by gthulasi** [openssl/openssl#13904]
https://github.com/openssl/openssl/blob/c972577684f8627267556f0bffa3c4035e9456e4/apps/ocsp.c#L1164

openssl-1.1.1g OCSP server works correctly,  with instructions from https://knowledge.broadcom.com/external/article/42966/creating-and-using-an-ocsp-responder-for.html

When moved to openssl-3.0.0-alpha10, server fails with the following error.

ocsp: waiting for OCSP client connections...
ocsp: Error parsing request
C07DE80D01000000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1143:
C07DE80D01000000:error:0688010A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:crypto/asn1/tasn_dec.c:708:
C07DE80D01000000:error:0688010A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:641:Field=responseStatus, Type=OCSP_RESPONSE 

Verified the same by changing OCSP_RESPONSE to OCSP_REQUEST.

**Comment by t8m** [comment]
Can you please retest with alpha12?

**Comment by tchalamarla** [comment]
I still see the do_responder() code trying to read ASN1 item of "OCSP_RESPONSE" instead of OCSP_REQUEST both in alpha12 and in master.

**Comment by gthulasi** [comment]
I still see do_responder() code trying to read ASN1 item of OCSP_RESPONSE instead of OCSP_REQUEST both in alpha12 and in master.

**Comment by richsalz** [comment]
looks like a bug; https://github.com/openssl/openssl/blob/master/apps/ocsp.c#L1168
