### ISSUE TITLE
SRP is not EVP enabled or provider aware or deprecated

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#13917]
SRP is a cryptographic algorithm - but it is not available via EVP. It isn't clear what EVP API it would be available via, or whether it needs a whole new EVP API. Since it is not available via EVP it is also not provider aware and only available via a low-level API which is not currently deprecated.

What should we do about this?

My answer: nothing for 3.0

**Comment by t8m** [comment]
+1 to keeping the status quo in regards to SRP for 3.0

**Comment by levitte** [comment]
Isn't SRP a bit more than just a crypto algorithm?  Like, a protocol?

> My answer: nothing for 3.0

Agreed

**Comment by romen** [comment]
Does this require an OTC or OMC vote?

**Comment by paulidale** [comment]
I don't see why not doing it would require a vote.  Likewise, I don't see why doing it would either.

**Comment by mattcaswell** [comment]
According to a previous OTC vote:

````
 1) EVP is the recommended API, it must be feature-complete compared with
    the functionality available using lower-level APIs.
   - Anything that isn’t available must be put to an OTC vote to exclude.
````

**Comment by romen** [comment]
And I could see how this could be seen also as an OMC vote:
provider-awareness is a precondition of support for FIPS, which is among the strategic objectives for 3.0
Having non-deprecated SRP functionality ignoring the FIPS setup might be seen as an OMC concern.

**Comment by levitte** [comment]
I hadn't read https://tools.ietf.org/html/rfc5054 earlier. In there, it's classified as a KEX.

**Comment by mattcaswell** [comment]
SRP will be deprecated in 3.0

**Comment by mattcaswell** [comment]
Deprecation PR is in #14132
