### ISSUE TITLE
After importing certificate into keystore getting error while running tomcat server 

### ISSUE THREAD

**Issue by veera2019** [openssl/openssl#13919]
Hi Team, 

We have imported ssl certificate into my tomcat keystore and after imported tomcat server not getting and getting below error 

**Caused by: java.lang.IllegalArgumentException: Alias name [test] does not identify a key entry**

Please guide us where we are missing while certificate import 

Thanks

**Comment by mattcaswell** [comment]
From you question its a little unclear how OpenSSL comes into this. Unless you used OpenSSL to generate your keystore in the first place? If so you'd need to tell us how you did that. But in general this question looks more appropriate to ask on a tomcat forum.

**Comment by veera2019** [comment]
Hi, issue resolved now, i have imported private key and certificate using openssl and now it's working fine


Thanks
