### ISSUE TITLE
Issue with Configure option for Tls1.1 multiblock mode

### ISSUE THREAD

**Issue by FdaSilvaYY** [openssl/openssl#1391]
Hi,

While looking into speed app code , I noticed that the flag `EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK `
and his related code is guarded by :
`# if !defined(OPENSSL_NO_MULTIBLOCK) && EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK`

But I don't see any associated "no-multiblock" option in configurations,  ...

Did I miss something  ?
"no-multiblock"  should be fixed ?
 or  OPENSSL_NO_MULTIBLOCK should be discard ?

**Comment by mattcaswell** [comment]
Looks like you missed something. It is in Configure, and is documented in INSTALL?

**Comment by FdaSilvaYY** [comment]
Oups, I miss it  ;)
