### ISSUE TITLE
Typo in man1.0.2/man1/crl2pkcs7

### ISSUE THREAD

**Issue by tim-hitchins-ekkosense** [openssl/openssl#13910]
Page URL: https://www.openssl.org/docs/man1.0.2/man1/crl2pkcs7.html

Section: `-certfile filename`

Error: Paragraph says "form" where it should say "from":

original:  
> specifies a filename containing one or more certificates in PEM format. All certificates in the file will be added to the PKCS#7 structure. This option can be used more than once to read certificates **form** multiple files.

fixed:  
> specifies a filename containing one or more certificates in PEM format. All certificates in the file will be added to the PKCS#7 structure. This option can be used more than once to read certificates **from** multiple files.

**Comment by mattcaswell** [comment]
1.0.2 is no longer supported, so this won't be fixed there. However the same issue seems to apply to master/1.1.1.

**Comment by tim-hitchins-ekkosense** [comment]
@mattcaswell agreed, https://github.com/openssl/openssl/blob/master/doc/man1/openssl-crl2pkcs7.pod.in#L58

I'm happy to open a pull request for this, but don't want to get it wrong. Is it a matter of changing that one file, or are docs auto generated from the code?

**Comment by mattcaswell** [comment]
> I'm happy to open a pull request for this, but don't want to get it wrong. Is it a matter of changing that one file, or are docs auto generated from the code, so it needs to be changed there?

Yes - just change that one file. Please make your PR against the master branch. This looks trivial to me from a copyright perspective so please include the line "CLA: trivial" on a line by itself (not the subject line) in the commit description, to avoid the need to submit a CLA.
