### ISSUE TITLE
rsa 

### ISSUE THREAD

**Issue by xiezhaokun** [openssl/openssl#13928]
In JDK ，the `PrivateKeyImpl.java` only has `n` and `d` ，and the function `RSA_set0_key` can only be used on public key。So how to use n and d to create rsa private key in openssl。

**Comment by mattcaswell** [comment]
> the function RSA_set0_key can only be used on public key

This is not correct. `RSA_set0_key` can be used to create private or public keys. In the case of a private key you need to supply `n`, `e` and `d`. I'm not familiar with the JDK implementation, but you will need to get the `e` value from somewhere.

**Comment by xiezhaokun** [comment]
> > the function RSA_set0_key can only be used on public key
> 
> This is not correct. `RSA_set0_key` can be used to create private or public keys. In the case of a private key you need to supply `n`, `e` and `d`. I'm not familiar with the JDK implementation, but you will need to get the `e` value from somewhere.

But in JDK, RSA supports two kinds of PrivateKey：`RSAPrivateKey` and `RSAPrivateCrtKey`. RSAPrivateKey only contains `n` and `d` , RSAPrivateCrtKey contains `n`,`e`,`d`,`p`,`q`,`dmp1`,`dmq1` and `iqmp`. Does openssl not support no crt private key（only has `n` and `d`) ?

**Comment by mattcaswell** [comment]
We also support private keys with CRT params. If you have them then `p` and `q` can be set via `RSA_set0_factors` and `dmp1`, `dmq1` and `iqmp` can be set via `RSA_set0_crt_params

**Comment by mattcaswell** [comment]
>Does openssl not support no crt private key（only has n and d) ?

You must supply at least `n`, `e` and `d`. Optionally you can also supply `p`, `q`, `dmp1`, `dmq1` and `iqmp`.

**Comment by xiezhaokun** [comment]
> You must supply at least `n`, `e` and `d`. Optionally you can also supply `p`, `q`, `dmp1`, `dmq1` and `iqmp`.
Why Openssl do not support no crt private key ?

**Comment by mattcaswell** [comment]
> Why Openssl do not support no crt private key ?

It does. To do RSA without the CRT params, you must supply `n`, `e` and `d`. No CRT params are involved in this case. `e` is a required parameter and must be present. Normally `n` and `e` are considered part of the public key, and `d` is the private key. OpenSSL requires all components to be present.

**Comment by xiezhaokun** [comment]
> > Why Openssl do not support no crt private key ?
> 
> It does. To do RSA without the CRT params, you must supply `n`, `e` and `d`. No CRT params are involved in this case. `e` is a required parameter and must be present. Normally `n` and `e` are considered part of the public key, and `d` is the private key. OpenSSL requires all components to be present.

But boringssl support private key without `e`.

**Comment by jjeffroberts** [comment]
I have a related question - we're upgrading libraries and with libp11 0.4.11 and openssl 3.0.5, I'm seeing an issue where libp11 tries to copy a private key by passing ONLY the n and e from an EVP_PKEY to a fresh (RSA *) via RSA_set0_key(). 

This used to work with older libraries but now EVP_PKEY_decrypt() fails with that key and the error is 'missing private key'.

From the discussion above it sounds as if this should have failed all along? I can make it work if I also pass the d.

**Comment by petrovr** [comment]
> I have a related question - we're upgrading libraries and with libp11 0.4.11 and openssl 3.0.5, I'm seeing an issue where libp11 tries to copy a private key by passing ONLY the n and e from an EVP_PKEY to a fresh (RSA *) via RSA_set0_key().
> 
> This used to work with older libraries but now EVP_PKEY_decrypt() fails with that key and the error is 'missing private key'.

It seems to me above is fail into #17092 or #17286.

**Comment by petrovr** [comment]
RSA_set0_key could be called only with d. Perphaps method could be called with "fake" exponent (n , fake-e, d) if key use is limited to "sign" operation only.

Question is why to create private key in OpenSSL? Why do not delegate sign opeation to Java "security"?

**Comment by t8m** [comment]
I think the original question was answered. Closing.
