### ISSUE TITLE
About PKCS7_STREAM for PKCS7_encrypt, is it possible to read output stream by chunk when encrypt is on going?

### ISSUE THREAD

**Issue by navigator117** [openssl/openssl#13927]
The PKCS7_encrypt docs says:
SMIME_write_PKCS7(), i2d_PKCS7_bio_stream(), PEM_write_bio_PKCS7_stream() will finalize the PKCS7 structure.
In these functions, they all call SMIME_crlf_copy()  which call BIO_read/BIO_write/BIO_flush to do the stream encrypt operation.
If I want to  read output stream by chunk when encrypt is on going, how can I do it? (for example use BIO_new_PKCS7 directly?)

**Comment by navigator117** [comment]
BTW, is PKCS7_decrypt support PKCS7_STREAM flag ?

**Comment by navigator117** [comment]
a readme at [](https://github.com/ChatSecure/OpenSSL/blob/master/README.ASN1) says:
3. The code is memory based: that is it expects to be able to read the whole
structure from memory. This is fine for small structures but if you have a
(say) 1Gb PKCS#7 signedData structure it isn't such a good idea...

**Comment by yhy37092** [comment]
if you want to read output stream by chunk ,i think you can use the following code 
`p7 = PKCS7_encrypt(certs, in, EVP_aes_128_cbc(), PKCS7_STREAM);
    BIO *p7bio = BIO_new_PKCS7(out, p7);

    uint8_t buff[10240];
    size_t bufflen = 0;
    while ((bufflen = BIO_read(in, buff, 10240)) > 0)
    {
        BIO_write(p7bio, buff, bufflen);
    }` 
instead of `i2d_PKCS7_bio_stream(out, p7, in, PKCS7_STREAM);`

**Comment by navigator117** [comment]
> if you want to read output stream by chunk ,i think you can use the following code
> 
> `p7 = PKCS7_encrypt(certs, in, EVP_aes_128_cbc(), PKCS7_STREAM); BIO *p7bio = BIO_new_PKCS7(out, p7); uint8_t buff[10240]; size_t bufflen = 0; while ((bufflen = BIO_read(in, buff, 10240)) > 0) { BIO_write(p7bio, buff, bufflen); }`
> 
> instead of
> `i2d_PKCS7_bio_stream(out, p7, in, PKCS7_STREAM);`

I think BIO_new_PKCS7, it's encode not decode
