### ISSUE TITLE
(Cent Os 7)Build failed using the command "make install"

### ISSUE THREAD

**Issue by DaemonZhao** [openssl/openssl#13936]
After "./Configure --prefix=/usr/local/ssl --openssldir=/usr/local/ssl '-Wl,--enable-new-dtags,-rpath,$(LIBRPATH)' & make" 
Run "make install",
Print info like this:
  ... ...
  basename: missing operand
  Try 'basename --help' for more information.
  make: *** [Makefile:3401: install_dev] Error 1
  ... ...

**Comment by DaemonZhao** [comment]
This disappeared. after choosing another branch named " OpenSSL_1_1_1-stable".

**Comment by levitte** [comment]
Yup. This was reported by another as well, fix in #13935

Duplicate of #13933

**Comment by levitte** [comment]
Duplicate of #13933
