### ISSUE TITLE
Can we make err_state_st private in 3.0 ?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#13945]
Does the project feel it is okay to make the err_state_st structure private in 3.0?  Tried to do it in https://github.com/openssl/openssl/pull/9082 was was turned away.  Wondering if thoughts changed now?

**Comment by levitte** [comment]
@kroeckx, you were the more knowledgeable last time this was discussed.

**Comment by kroeckx** [comment]
You need to deprecate it, and at some later point we can then make it private or remove it.

**Comment by richsalz** [comment]
It looks like @levitte already deprecated the one function that uses it.  So internally the code could be rewritten.  Tempting.

**Comment by levitte** [comment]
Well, deprecation is OK, but that won't make the structure more private...

**Comment by paulidale** [comment]
I'm all for deprecating this.  It can be made private in 4.0.

**Comment by richsalz** [comment]
I think this can be closed.  At least the "won't block 3.0" label should be removed because it the project decided that the answer for 3.0 is "no"

**Comment by t8m** [comment]
Hmm, actually during the OTC meeting on Tuesday we did not say the answer for 3.0 is "no". Otherwise we would assign this to `Post 3.0.0` milestone. So actually if someone contributes the PR and it is not overwhelmingly complex, I think it will be considered and potentially merged. Of course it would have to happen before beta1 is out.

**Comment by richsalz** [comment]
The `ERR_get_state` function is deprecated for 3.0  I believe the OTC decided, although perhaps informally, that it could not be removed without being deprecated first.   Since the function is still visible, the datatype must be visible.  I recall @kroeckx was among those saying it must be deprecated first.

**Comment by richsalz** [comment]
I think you should put a "post 3.0" tag on this.

**Comment by richsalz** [comment]
Closing this. The one function that uses the datatype is deprecated and will presumably go away when the rest of the 3.0 deprecated functions go away.  There's nothing special about `err_state_st` other than it is horribly bad sad (parallel arrays rather than a single array of struct's) and therefore sticks in my craw :)
