### ISSUE TITLE
Parameter 'propq' in CMS_ReceiptRequest_create0_ex() is documented but unused

### ISSUE THREAD

**Issue by FloridSleeves** [openssl/openssl#13943]
In `CMS_ReceiptRequest_create0_ex()`, parameter `propq` is not used at all. However, in the corresponding [document](https://github.com/openssl/openssl/blob/master/doc/man3/CMS_get1_ReceiptRequest.pod), it says

> CMS_ReceiptRequest_create0_ex() creates a signed receipt request structure... **the property query propq are used when retrieving algorithms from providers.**

So I guess either it's necessary to add "`propq` is ignored " to document or the implementation of `CMS_ReceiptRequest_create0_ex()` may have potential bugs.

**Comment by slontis** [comment]
It was deliberately added as an unused parameter as most often the libctx and propq are needed as a pair. I can mark it as unused.

**Comment by FloridSleeves** [comment]
Thanks for your confirmation!
