### ISSUE TITLE
PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY

### ISSUE THREAD

**Issue by gavinju** [openssl/openssl#13947]
My os is ubuntu 20.04.1，when generate private key:
1、ssh-keygen -t rsa -b 4096 -f /home/apps/AIspace/bin/certs/amber-api.key
2、openssl rsa -in /home/apps/AIspace/bin/certs/amber-api.key  -pubout -outform PEM -out amber-api.key.pub
There is an error message：
140551763596608:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
Checked the relevant environment：
openssl version： OpenSSL 1.1.1f  31 Mar 2020

But in my previous environment, everything worked fine：
ubuntu 18.04.5
OpenSSL 1.1.1  11 Sep 2018

So， I'm not sure if there is a bug in the higher version.

**Comment by levitte** [comment]
I believe amber-api.key (which you can display as a text file) starts with this:

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

`OPENSSH` isn't a key type that openssl understands, not in any version to date.

**Comment by gavinju** [comment]
@levitte   Yes, you are right. How can i solve this problem？

**Comment by levitte** [comment]
In the [man page ssh-keygen(1)](https://man7.org/linux/man-pages/man1/ssh-keygen.1.html), you can read about the export option `-e`. That should help.
I would recommend the PKCS#8 format.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> In the [man page ssh-keygen(1)](https://man7.org/linux/man-pages/man1/ssh-keygen.1.html), you can read about the export option `-e`. That should help.
> I would recommend the PKCS#8 format.
>
Still open?

Information provided - reference to manual page. Also manual details how to write in different formats.

Regard,
Roumen Petrov

**Comment by Potherca** [comment]
I had the same issue. The `-e` export option does not work for me, as this will not convert the private key. Instead I converted my original key to PEM (SSH2) format:
```sh
ssh-keygen -p -f ~/.ssh/id_rsa -m pem
```

**Comment by naniruddha-git** [comment]
> I had the same issue. The `-e` export option does not work for me, as this will not convert the private key. Instead I converted my original key to PEM (SSH2) format:
> 
> ```shell
> ssh-keygen -p -f ~/.ssh/id_rsa -m pem
> ```

Thank you so much! After many hours of unsuccessful attempts this worked for me.

**Comment by sezanzeb** [comment]
> OPENSSH isn't a key type that openssl understands, not in any version to date.

I wish openssl would at least tell me that this is the problem. "Expecting: ANY PRIVATE KEY" isn't a very helpful error message

**Comment by JVKeller** [comment]
Similar issuer here.
```
unable to load private key
139944805250368:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY

```
For me, the permissions were off on the files so openssl couldn't read the file, therefore -> 'no start line'

My solution was:
```
    sudo -s
    chown -hR root yourdomain.com/
    cd yourdomain.com/
    openssl pkcs12 -export -out cert.pfx -inkey privkey.pem -in cert.pem
```

The conversion worked after taking ownership of the directory. After this I copied it to my home folder. Permissions were still funny getting it copied to windows, but after zipping the file up, I could copy it over.

**Comment by sjackson0109** [comment]
This is a LINUX to WINDOWS file formatting problem:

Godaddy Generated Private.KEY file:
![image](https://user-images.githubusercontent.com/38080190/157653327-c5c9ec0a-59f1-4906-bd3a-895b786a9aba.png)

When running this command (using the above KEY file), we get an error:
```
openssl pkcs12 -export -inkey private.key -in downloadedCert.crt -out websitefqdn.pfx
unable to load private key
11892:error:0909006C:PEM routines:get_name:no start line:crypto\pem\pem_lib.c:745:Expecting: ANY PRIVATE KEY
```


After Converting it (create a new txt file and edit old and new files with notepad.exe, copy > paste into the new file > save)..
We now have new a compatible file-format...
![image](https://user-images.githubusercontent.com/38080190/157653696-e02256af-9e22-4638-827b-cd8c213d5c0e.png)

and the repeated command:
```
openssl pkcs12 -export -inkey converted-private.key -in downloadedCert.crt -out websitefqdn.pfx
Enter Export Password:
Verifying - Enter Export Password:
```


You're welcome :)

**Comment by rsgilbert** [comment]
@sjackson0109 wowww!! It worked. Thanks. I was executing the commands from git bash. I didnt think notepad would be so useful. Btw, even if you just copy and paste to a new file using visual studio code it works. But using the cp command wont work.

**Comment by chunji08** [comment]
> This is a LINUX to WINDOWS file formatting problem:
> 
> Godaddy Generated Private.KEY file: ![image](https://user-images.githubusercontent.com/38080190/157653327-c5c9ec0a-59f1-4906-bd3a-895b786a9aba.png)
> 
> When running this command (using the above KEY file), we get an error:
> 
> ```
> openssl pkcs12 -export -inkey private.key -in downloadedCert.crt -out websitefqdn.pfx
> unable to load private key
> 11892:error:0909006C:PEM routines:get_name:no start line:crypto\pem\pem_lib.c:745:Expecting: ANY PRIVATE KEY
> ```
> 
> After Converting it (create a new txt file and edit old and new files with notepad.exe, copy > paste into the new file > save).. We now have new a compatible file-format... ![image](https://user-images.githubusercontent.com/38080190/157653696-e02256af-9e22-4638-827b-cd8c213d5c0e.png)
> 
> and the repeated command:
> 
> ```
> openssl pkcs12 -export -inkey converted-private.key -in downloadedCert.crt -out websitefqdn.pfx
> Enter Export Password:
> Verifying - Enter Export Password:
> ```
> 
> You're welcome :)


Are you trying to convert the key file into the DOS mode ? And the follow-up command would start  working  ? 
On my UBUNTU  20.0.4, I have tried the freshly created key file and the converted copy,  and it fails in either way.  

Comments ? 

Jack
