### ISSUE TITLE
Decoder/Encoder documentation

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#13949]
This pertains to OpenSSL3 encoder/decoder documentation (feel free to tick checkboxes when reviewing issue(s)).

- [x] Wrong API description in [OSSL_ENCODER](https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_ENCODER.pod) and [OSSL_DECODER](https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_DECODER.pod): "OSSL_DECODER_do_all_provided() [...] data as arguments.": *data* is no argument to the function, *arg* is.
- [x] Wrong wording in [OSSL_DECODER](https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_DECODER.pod): "OSSL_DECODER_do_all_provided() traverses all encoder implementations by all activated providers" should refer to *decoders*.
- [ ] Missing: provider-decoder (analogous to [provider-encoder](https://github.com/openssl/openssl/blob/master/doc/man7/provider-encoder.pod))
- [x] Nit: Wrong HTML markup, e.g., https://www.openssl.org/docs/manmaster/man7/ "$description$lt;-$description$gt;"

**Comment by levitte** [comment]
Thanks.  Fixups coming up, for now the quick ones.

See #13954 for the OSSL_ENCODER / OSSL_DECODER manual issues.
See openssl/web#214 for the `$description$` problem.

`provider-decoder(7)` will be a separate PR that will take a bit longer to finish, stay tuned.

**Comment by t8m** [comment]
There is still missing the provider-decoder, which should imo be there before beta1.
