### ISSUE TITLE
No "release" with more than just the "Source Code" ?

### ISSUE THREAD

**Issue by life777eternal** [openssl/openssl#13959]
Are there any actual releases of this "OpenSSL" with more than just the "Source Code" which will work on Windows Web Server 2008 R2 ? 

Need to convert a Crt file from an SSL Cert to PFX for an OpenSim region connected to Osgrid. https://osgrid.org/download.php Have tried to do that conversion, though not sure if it worked right. 

Thank you.

**Comment by levitte** [comment]
There are others who release binary packages from our source code, but yes, *our* releases are source code only, so far.

https://wiki.openssl.org/index.php/Binaries has a list of known binary dists

**Comment by mspncp** [comment]
> https://wiki.openssl.org/index.php/Binaries has a list of known binary dists

FWIW: Alternatively, you can download the Apache 2.4 Win64 zip file from the [Apache Lounge](https://www.apachelounge.com/download), which contains an up-to-date openssl 1.1.1 executable in the folder Apache24\bin.

**Comment by life777eternal** [comment]
Alright, thank you both.
