### ISSUE TITLE
openssl-genpkey documentation for the DSA/DH params is controversial

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#13952]
Documentation for openssl-genpkey parameters generation is controversial and confusing.

How can we generate DH and DHX parameters? DH is PKCS#3 style DH, while DHX is X9.42 style DH. But then its not clear what dh_paramgen_type does, since that is documented as meaning 0 == PKCS3 and 1 == X9.42. What happens if you do "-algorithm -DHX" but with "dh_paramgen_type:0", vs "-algorithm DH" with "dh_paramgen_type:1" what kind of params do you get (note the PEM headers are different for DH vs DHX)

Its also unclear from this test what "pbits" and "qbits" options do. Qbits is only documented for DSA not DH on the genpkey page, and pbits isn't documented at all except it appears in one of the genpkey examples (for DSA).

From here: https://github.com/openssl/openssl/pull/13930#discussion_r563637923

**Comment by t8m** [comment]
dh_paramgen_type is currently ignored and that is a bug.

**Comment by mattcaswell** [comment]
qbits doesn't seem to make a lot of sense for PKCS#3 DH (which has no q parameter)

**Comment by t8m** [comment]
Reported #13956 for the dh_paramgen_type being ignored.

**Comment by beldmit** [comment]
> qbits doesn't seem to make a lot of sense for PKCS#3 DH (which has no q parameter)

Removed it from the generating script

**Comment by slontis** [comment]
The doc is not quite right. What this does in 1.1.1 is actually..
0 = use generator                                           (Assigns to DH type key)
1 = fips 186-2 gen (this is less than ideal)     (Assigns to DHX type key)
2 = fips 186-4 gen                                           (Assigns to DHX type key)

And yes the -algorithm parameter is problematic..

**Comment by levitte** [comment]
This is currently problematic in another way with providers in that the application must decide the keytype first, then feed it all the parameters.  We have no mechanism for changing keytype under the hood.

**Comment by levitte** [comment]
This is related to #13871 and #13956

**Comment by slontis** [comment]
Documentation is updated..
The dh_paramgen_type is just ignored if the group is set which is also documented.
