### ISSUE TITLE
With master the genpkey -genparam command ignores the -pkeyopt dh_paramgen_type option

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#13956]
The `dh_paramgen_type` should indicate whether DH (value 0) or DHX (value 1) type of DH parameters are generated. This is ignored with current master and if DHX parameters are to be generated the `-algorithm DHX` must be used instead.

**Comment by slontis** [comment]
This is not quite correct.. The values in 1.1.1 are.
0 = DH param gen using generator
1 = DSA param gen using fips 186-2 converted to DHX
2 = DSA param gen using fips 186-3 converted to DHX

This command is telling it to create a DH algorithm and then it changes it to DHX..

**Comment by levitte** [comment]
This is related to #13871

**Comment by slontis** [comment]
@mattcaswell do you want me to look at this and all the other dh/dhx related issues?

**Comment by mattcaswell** [comment]
> do you want me to look at this and all the other dh/dhx related issues?

If you want to take them on, I'm more than happy for you to do that. I had this one and #14444 in my queue for the current sprint. If you want to take them I'll pick some other issues instead. Let me know if you want to do that.

**Comment by slontis** [comment]
> > do you want me to look at this and all the other dh/dhx related issues?
> 
> If you want to take them on, I'm more than happy for you to do that. I had this one and #14444 in my queue for the current sprint. If you want to take them I'll pick some other issues instead. Let me know if you want to do that.

Yep I can do that one too.. (14145,13956,13952,13871,14054,14444) are all kind of related.

**Comment by mattcaswell** [comment]
Ok I reassigned this one and #14444 to you.
