### ISSUE TITLE
Memory leak in ssl_derive(), pubkey may be not free.

### ISSUE THREAD

**Issue by wongmz** [openssl/openssl#13981]
![image](https://user-images.githubusercontent.com/54125561/105971237-45c08200-60c5-11eb-8c62-329b9b08ecde.png)
If EVP_PKEY_derive_set_peer() return false, pctx->peerkey != pubkey, in EVP_PKEY_CTX_free(pctx), pubkey will not be free or down reference.
![image](https://user-images.githubusercontent.com/54125561/105971860-f464c280-60c5-11eb-88da-19f9edb961d7.png)
![image](https://user-images.githubusercontent.com/54125561/105971895-fcbcfd80-60c5-11eb-8e49-6cfe84f87dac.png)

**Comment by t8m** [comment]
The EVP_PKEY_derive_set_peer() bumps the refcount if the key is actually successfully set. So this should not be an issue. The pubkey here is owned by the calling routine and will be properly down ref-ed and deallocated.

In other words the EVP_PKEY_derive_set_peer() behaves like EVP_PKEY_derive_set1_peer() so the caller always keeps the ownership of the pubkey reference regardless of the success or failure.

**Comment by mattcaswell** [comment]
Behaviour looks correct to me. `pubkey` should not be freed in this case.

**Comment by wongmz** [comment]
@t8m @mattcaswell 
If EVP_PKEY_derive_set_peer() is success, pubkey refcount will reduce by EVP_PKEY_CTX_free(pctx).
But if EVP_PKEY_derive_set_peer() is fail, pubkey refcount will not be changed.
Is this correct?

**Comment by t8m** [comment]
No, if  EVP_PKEY_derive_set_peer() succeeds, the refcount will be increased inside the function call. Not otherwise.
