### ISSUE TITLE
Where is the "ca-bundle.crt" in openssl1.1.1b

### ISSUE THREAD

**Issue by 727751410** [openssl/openssl#13985]
I downloaded source code from, and install 1.1.1b like this:
`tar -zxv openssl-OpenSSL_1_1_1b.tar.gz`
`cd openssl-OpenSSL_1_1_1b/`
`./config --prefix=/usr/local/openssl-1.1.1b`
`make && make install`
`./config shared `
`make clean`
`make  && make install`

`cd /usr/local/openssl-1.1.1b/`
`echo "/usr/local/openssl-1.1.1b/lib/" >> /etc/ld.so.conf`
`ldconfig -v`

then I used `./usr/local/openssl-1.1.1b/bin/openssl version -a` and get 
`OpenSSL 1.1.1b  26 Feb 2019`
`built on: Wed Jan 27 14:05:38 2021 UTC`
`platform: linux-x86_64`
`options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) `
`compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG`
`OPENSSLDIR: "/usr/local/openssl-1.1.1b/ssl"`
`ENGINESDIR: "/usr/local/openssl-1.1.1b/lib/engines-1.1"`

I think I have installed openssl1.1.1b successfully, but under `/usr/local/openssl-1.1.1b/ssl/certs`, there is no this file `ca-bundle.crt`, if with openssl1.0.1, `ca-bundle.crt` is under `/etc/pki/tls/certs/`, whether this file `ca-bundle.crt` is canceled in 1.1.1b? Or I did not install successfully?

**Comment by mattcaswell** [comment]
That file has never been distributed as part of OpenSSL. It is typically provided by distributions from another source such as Mozilla's truststore.

**Comment by sergeevabc** [comment]
The question is still relevant. Being an ordinary Windows user, not a developer, I download a fresh copy of OpenSSL, unpack it and run some command such `openssl s_client -showcerts -connect dns.google:443 -verify` as `` only to get `unable to get local issuer certificate` error. Aaand? Yes, there are -CAfile and -CApath switches, but there is no certificates file around. Gosh, some instructions, please!

**Comment by mattcaswell** [comment]
There is some discussion of this here:

https://docs.openssl.org/3.5/man7/ossl-guide-tls-introduction/

**Comment by sergeevabc** [comment]
> https://docs.openssl.org/3.5/man7/ossl-guide-tls-introduction/

Great, it's all working now. Thank you, Matt.  Here's what I did to make it work:

``` console
$ cd /d c:\soft\openssl

$ curl -LOs https://curl.se/ca/cacert.pem

$ setx SSL_CERT_FILE c:\soft\openssl\cacert.pem

$ openssl s_client -showcerts -connect dns.google:443 -verify 5
verify depth is 5
Connecting to 8.8.4.4
CONNECTED(0000011C)
depth=2 C=US, O=Google Trust Services LLC, CN=GTS Root R4
verify return:1
depth=1 C=US, O=Google Trust Services, CN=WE2
verify return:1
depth=0 CN=dns.google
verify return:1
...
```
