### ISSUE TITLE
Intermittent failures of the test_evp_pkey_provided

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#13995]
Occasionally the test_evp_pkey_provided fails with:

```
30-test_evp_extra.t ................ ok
30-test_acvp.t ..................... ok
30-test_evp_kdf.t .................. ok
30-test_evp_libctx.t ............... ok
30-test_evp_pkey_dparam.t .......... ok

    # ERROR: (bool) 'EVP_PKEY_public_check(key_ctx) == true' failed @ ../test/evp_pkey_provided_test.c:353
    # false
    not ok 2 - test_fromdata_rsa
# ------------------------------------------------------------------------------
../../util/wrap.pl ../../test/evp_pkey_provided_test ../../../test/recipes/30-test_evp_pkey_provided => 1
not ok 1 - running evp_pkey_provided_test
# ------------------------------------------------------------------------------
#   Failed test 'running evp_pkey_provided_test'
#   at ../test/recipes/30-test_evp_pkey_provided.t line 17.
# Looks like you failed 1 test of 1.30-test_evp_pkey_provided.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
30-test_pbelu.t .................... ok
30-test_pkey_meth.t ................ ok
30-test_evp_fetch_prov.t ........... ok
30-test_pkey_meth_kdf.t ............ ok
30-test_provider_status.t .......... ok
```
Example of the failed test run: https://github.com/openssl/openssl/runs/1779579314

Perhaps adding some debugging output to the test_evp_pkey_provided could help investigating the issue as it is intermittent.

**Comment by slontis** [comment]
This make no sense to me...
This is loading 'fixed' data into a key.
The public key check does an export and checks the range of e and that n is prime.

**Comment by t8m** [comment]
@levitte If I forcibly break the key and make the check fail then for some reason the verbose failure output does not include the error message. It is visible only when running with full verbosity because it is printed after the not ok 2 message. Could it be somehow fixed?

**Comment by t8m** [comment]
And yeah, I was trying hard to reproduce this today and failed so the only option I can see is to add some more diagnostic output and wait if it happens again.

**Comment by t8m** [comment]
> @levitte If I forcibly break the key and make the check fail then for some reason the verbose failure output does not include the error message. It is visible only when running with full verbosity because it is printed after the not ok 2 message. Could it be somehow fixed?

This is actually trivial to fix. PR coming.

**Comment by t8m** [comment]
Ha now we have a failure with an error message at least:
https://github.com/openssl/openssl/pull/14352/checks?check_run_id=2003263950

**Comment by t8m** [comment]
Now I get it - the ossl_bn_miller_rabin_is_prime() check first tries gcd of the modulus with a random value of the same size. And because we are talking here about modulus that is a product of two 16 bit primes there is surely non-negligible probability that the random value is product of one of those two primes as well. In that case the ossl_bn_miller_rabin_is_prime returns status value BN_PRIMETEST_COMPOSITE_WITH_FACTOR instead of BN_PRIMETEST_COMPOSITE_NOT_POWER_OF_PRIME which is the expected status in ossl_rsa_sp800_56b_check_public(). This is of course something that has negligible probability to happen with real RSA keys of reasonable bit size so there is no point in changing the check. I'm inclined in just removing the call in the test with some comment added. @slontis @openssl/committers opinions?

**Comment by slontis** [comment]
In fips mode this would fail as this is not actually a secure key.
The indeterminate state is related to the MR check using BN_priv_rand_range_ex().
So yes the check is not ok here.
The question here is if it should even do the MR check for small keys in the default provider..

**Comment by t8m** [comment]
> The question here is if it should even do the MR check for small keys in the default provider..

Do you mean just skipping the MR check if the key size is < 512 bits for example? That would be possibly one option. I'll do a PR.

**Comment by t8m** [comment]
Another option of course would be to make the 512 bits minimum in the pubkey check and fail it always otherwise and of course not  to call it from the evp_pkey_provided_test.
