### ISSUE TITLE
Not able add edipartyname extension in subjectAltnames

### ISSUE THREAD

**Issue by saranyav-pulsesecure** [openssl/openssl#13993]
v2i_GENERAL_NAME_ex function is not having case to set edipartyname.

So is there any different way to add edipartyname  extension

**Comment by mattcaswell** [comment]
You can construct an EDIPARTYNAME and a GENERAL_NAME using `EDIPARTYNAME_new` and `GENERAL_NAME_new` respectively. You can then set the EDIPARTYNAME into the GENERAL_NAME using:

````
GENERAL_NAME_set0_value(genname, GEN_EDIPARTY, edipartyname);
````

**Comment by saranyav-pulsesecure** [comment]
To add extension say dns we can add like this..
cert.add_extensions([X509Extension(b'subjectAltName', False, b'otherName:222')])

but in the samy way is it possible to add edipartyname extension also?

**Comment by mattcaswell** [comment]
This looks like you are using the python bindings for OpenSSL? I can't answer your question because we don't maintain those bindings here. You'd need to ask the python guys:

https://github.com/pyca/cryptography

**Comment by saddam1995** [comment]
Running error code 404,500

**Comment by saddam1995** [comment]
> v2i_GENERAL_NAME_ex function is not having case to set edipartyname.
> 
> So is there any different way to add edipartyname  extension
> 
> 
> 

Run error Code 404,500
