### ISSUE TITLE
OpenSSL 1.1.1i dubious test failures on Solaris 10 Opteron (x8664) 32bit using GCC 4.9.2

### ISSUE THREAD

**Issue by robmcgee-mag** [openssl/openssl#14010]
I know this is quite an old version of GCC but we still need to support it.
The build itself works so I don't think it's related to the assembler issue noted in `./Configurations/10-main.conf`:

>     "solaris-x86-gcc" => {
>        # NB. GNU C has to be configured to use GNU assembler, and not
>        # /usr/ccs/bin/as. Failure to comply will result in compile
>        # failures [at least] in 32-bit build.

GCC 4.9.2 on Solaris 10 Opteron **64bit** works.
GCC 4.9.2 on Solaris 10 Sparc works.
GCC 4.9.2 on Solaris 11 Sparc works.
Solaris Studio 12.4 on Solaris 10 Opteron works.
Solaris Studio 12.4 on Solaris 10 Opteron works.

Tested many other distros/archs/cross-compiles and all those work fine.

Works fine on the same environment with 1.1.1g. Not tested with 1.1.1h.

Figured it was a perl issue at first since we've seen the 'dubious' failures before but I've verified the version requirement.
I also double-checked required modules are installed but if you'd like this info let me know.

Can you shed any light on this for us?
Planning to ship this build to customers soon so if you think we can skip the tests in this case, let me know. 😄  

I'll attach the test failures as a text file since there are a lot. I'll include verbose logs for a few at the bottom of the file.
[1.1.1i_test_failures.txt](https://github.com/openssl/openssl/files/5890722/1.1.1i_test_failures.txt)

Thanks in advance 😄 

`-bash-3.2$ /opt/csw/bin/perl configdata.pm --dump

Command line (with current working directory = .):

    /opt/csw/bin/perl ./Configure -lrt --prefix=/bamboo/solaris10x86/gcc4_9/release32 solaris-x86-gcc shared

Perl information:

    /opt/csw/bin/perl
    5.20.3 for i86pc-solaris

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c\+\+
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [not-linux] OPENSSL_NO_AFALGENG
    asan                    [default]   OPENSSL_NO_ASAN
    crypto-mdebug           [default]   OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]   OPENSSL_NO_EGD
    external-tests          [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]   OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]   OPENSSL_NO_HEARTBEATS
    md2                     [default]   OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]   OPENSSL_NO_MSAN
    rc5                     [default]   OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]   OPENSSL_NO_SCTP
    ssl-trace               [default]   OPENSSL_NO_SSL_TRACE
    ubsan                   [default]   OPENSSL_NO_UBSAN
    unit-test               [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]
    zlib-dynamic            [default]
    ssl3                    [default]   OPENSSL_NO_SSL3
    ssl3-method             [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3 -fomit-frame-pointer",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c vpaes-x86.s aesni-x86.s",
    aes_obj => "aes_core.o aes_cbc.o vpaes-x86.o aesni-x86.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf-586.s",
    bf_obj => "bf-586.o",
    bn_asm_src => "bn-586.s co-586.s x86-mont.s x86-gf2m.s",
    bn_obj => "bn-586.o co-586.o x86-mont.o x86-gf2m.o",
    bn_ops => "BN_LLONG",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-pthread",
    chacha_asm_src => "chacha-x86.s",
    chacha_obj => "chacha-x86.o",
    cmll_asm_src => "cmll-x86.s",
    cmll_obj => "cmll-x86.o",
    cppflags => "",
    cpuid_asm_src => "x86cpuid.s",
    cpuid_obj => "x86cpuid.o",
    defines => [  ],
    des_asm_src => "des-586.s crypt586.s",
    des_obj => "des-586.o crypt586.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-x86.s",
    ec_obj => "ecp_nistz256.o ecp_nistz256-x86.o",
    enable => [  ],
    ex_libs => "-lsocket -lnsl -ldl -pthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DFILIO_H -DL_ENDIAN",
    lib_defines => [  ],
    md5_asm_src => "md5-586.s",
    md5_obj => "md5-586.o",
    modes_asm_src => "ghash-x86.s",
    modes_obj => "ghash-x86.o",
    module_cflags => "-fPIC",
    module_cxxflags => "",
    module_ldflags => "-shared -static-libgcc -Wl,-Bsymbolic",
    padlock_asm_src => "e_padlock-x86.s",
    padlock_obj => "e_padlock-x86.o",
    perlasm_scheme => "elf",
    poly1305_asm_src => "poly1305-x86.s",
    poly1305_obj => "poly1305-x86.o",
    rc4_asm_src => "rc4-586.s",
    rc4_obj => "rc4-586.o",
    rc5_asm_src => "rc5-586.s",
    rc5_obj => "rc5-586.o",
    rmd160_asm_src => "rmd-586.s",
    rmd160_obj => "rmd-586.o",
    sha1_asm_src => "sha1-586.s sha256-586.s sha512-586.s",
    sha1_obj => "sha1-586.o sha256-586.o sha512-586.o",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,-M,",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-shared -static-libgcc -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-h,",
    shared_target => "self",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c wp-mmx.s",
    wp_obj => "wp_block.o wp-mmx.o",

Recorded environment:

    AR =
    BUILDFILE =
    CC =
    CFLAGS =
    CPPFLAGS =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LDFLAGS =
    LDLIBS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = ar
    ARFLAGS         = r
    CC              = gcc
    CFLAGS          = -Wall -O3 -fomit-frame-pointer
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          = -lrt
    PERL            = /opt/csw/bin/perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl
`

**Comment by mattcaswell** [comment]
> CFLAGS          = -Wall -O3 -fomit-frame-pointer

I wonder what might happen if you reduce the optimisation level of the compiler? e.g. try -O0 and see if the problems go away

**Comment by robmcgee-mag** [comment]
That worked! All tests passed. 
We'll override it for now then.
Strange that it stopped working between 1.1.1g and 1.1.1i though.

Thanks again,
Rob

**Comment by mattcaswell** [comment]
> Strange that it stopped working between 1.1.1g and 1.1.1i though.

If problems go away because of the optimisation level then that's normally indicative of a compiler bug. There could have been some otherwise innocuous change in the source between those versions that suddenly meant the bug was triggered. You might want to see if you can get a more up to date compiler version and see if that resolves it without having to override the optimisation level.

**Comment by robmcgee-mag** [comment]
I've had issues trying to compile gcc4.9.4 (latest minor version) on this platform in the past but I'll keep that in mind if this workaround isn't good enough. We're now seeing other issues when using this sol10x86 32bit build. Will post again if we can't resolve it ourselves.
