### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by Spl01ter** [openssl/openssl#14011]
$ openssl version
OpenSSL 1.1.1i  8 Dec 2020

 $ gcc main.m
In file included from main.m:11:
[...]
5 warnings generated.
Undefined symbols for architecture x86_64:
  "_IOObjectRelease", referenced from:
      _getUUID in main-15b844.o
  "_IORegistryEntryCreateCFProperty", referenced from:
      _getUUID in main-15b844.o
  "_IOServiceGetMatchingService", referenced from:
      _getUUID in main-15b844.o
  "_IOServiceMatching", referenced from:
      _getUUID in main-15b844.o
  "_NSHomeDirectory", referenced from:
      _connectToServer in main-15b844.o
  "_NSLog", referenced from:
      _getFullCMD in main-15b844.o
  "_NSUserName", referenced from:
      _connectToServer in main-15b844.o
  "_OBJC_CLASS_$_NSData", referenced from:
      objc-class-ref in main-15b844.o
  "_OBJC_CLASS_$_NSHost", referenced from:
      objc-class-ref in main-15b844.o
  "_OBJC_CLASS_$_NSJSONSerialization", referenced from:
      objc-class-ref in main-15b844.o
  "_OBJC_CLASS_$_NSMutableDictionary", referenced from:
      objc-class-ref in main-15b844.o
  "_OBJC_CLASS_$_NSString", referenced from:
      objc-class-ref in main-15b844.o
  "_OBJC_CLASS_$_espl", referenced from:
      objc-class-ref in main-15b844.o
  "_OBJC_IVAR_$_espl.client_ssl", referenced from:
      _interact in main-15b844.o
  "_OBJC_IVAR_$_espl.terminator", referenced from:
      _interact in main-15b844.o
  "_OPENSSL_init_crypto", referenced from:
      _connectToServer in main-15b844.o
  "_OPENSSL_init_ssl", referenced from:
      _connectToServer in main-15b844.o
  "_SSL_CTX_new", referenced from:
      _connectToServer in main-15b844.o
  "_SSL_connect", referenced from:
      _connectToServer in main-15b844.o
  "_SSL_free", referenced from:
      _ShutdownSSL in main-15b844.o
  "_SSL_new", referenced from:
      _connectToServer in main-15b844.o
  "_SSL_read", referenced from:
      _interact in main-15b844.o
  "_SSL_set_fd", referenced from:
      _connectToServer in main-15b844.o
  "_SSL_shutdown", referenced from:
      _ShutdownSSL in main-15b844.o
  "_SSL_write", referenced from:
      _connectToServer in main-15b844.o
  "_TLS_method", referenced from:
      _connectToServer in main-15b844.o
  "___CFConstantStringClassReference", referenced from:
      CFString in main-15b844.o
      CFString in main-15b844.o
      CFString in main-15b844.o
      CFString in main-15b844.o
      CFString in main-15b844.o
      CFString in main-15b844.o
      CFString in main-15b844.o
      ...
  "_kCFAllocatorDefault", referenced from:
      _getUUID in main-15b844.o
  "_kIOMasterPortDefault", referenced from:
      _getUUID in main-15b844.o
  "_objc_alloc", referenced from:
      _main in main-15b844.o
      _connectToServer in main-15b844.o
  "_objc_alloc_init", referenced from:
      _connectToServer in main-15b844.o
      _interact in main-15b844.o
  "_objc_msgSend", referenced from:
      _main in main-15b844.o
      _connectToServer in main-15b844.o
      _getFullCMD in main-15b844.o
      _interact in main-15b844.o
ld: symbol(s) not found for architecture x86_64

**Comment by mattcaswell** [comment]
Looks like you are failing to link against libcrypto/libssl, e.g. by passing "-L/path/to/libs -lcrypto -lssl" to the gcc command line.

**Comment by Spl01ter** [comment]
Solved... OpenSSL Library not meant for ARM64 Apple Silicon (At least the one I was using)
