### ISSUE TITLE
Should the X509_V_ERR_ defines keep the same value in OSSL3?

### ISSUE THREAD

**Issue by bartonjs** [openssl/openssl#14025]
Many (most?) of the X509_V_ERR_ values seem to be unchanged across versions of OpenSSL, but `X509_V_ERR_INVALID_CA` has changed for 3.0 (now 79, was 24).

Changing the value of the define is fine under recompilation, but if the library is used from languages that don't support ingesting C headers (such as C# p/invokes), or if the application uses a loose coupling via dylib then the changed value complicates the caller's understanding.

In case there's a project goal to not change the define values, but this one got missed, it seemed prudent to ask the question before doing the work to work around the complication.

1.1.1:
https://github.com/openssl/openssl/blob/c2fc1115eac53d2043e09bfa43ac5407f87fe417/include/openssl/x509_vfy.h#L118-L127

3.0 (current):
https://github.com/openssl/openssl/blob/a2a5506b9329b978a2a5b11a518b9789446ad310/include/openssl/x509_vfy.h.in#L154-L163

**Comment by paulidale** [comment]
3.0 is a major release.  Recompilation is expected.

A binary compatible release would not change these error numbers.  3.0 was never intended to be binary compatible.
