### ISSUE TITLE
OpenSSL certificate verification behavior has changed in 1.1.1i (nginx web server)

### ISSUE THREAD

**Issue by tfloch** [openssl/openssl#14036]
PR #11359 changed the "client certificate verification behavior" in nginx web server, when using nginx setting "[ssl_verify_client optional_no_ca](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_client_certificate)" 

- **Before** (nginx 1.19.6 compiled with OpenSSL 1.1.1h)

```
# HTTPS WebRequest, client authenticated with an expired certificate
$ curl https://<IP> --cert expired.crt --key expired.key -v
...
<HTTP Reply, depending of nginx upstream>.

# nginx error log
<empty>
```

- **After** (nginx 1.19.6 compiled with OpenSSL 1.1.1i)

```
# HTTPS WebRequest, client authenticated with an expired certificate
$ curl https://<IP> --cert expired.crt --key expired.key -v
...
< HTTP/1.1 400 Bad Request

# nginx log
2021/01/29 15:42:39 [info] 1256#0: *1 client SSL certificate verify error: (10:certificate has expired) while reading client request headers, client: 10.10.10.50, server: localhost, request: "POST /Tools/IInformationManager/GetInformationValueList1 HTTP/1.1", host: "10.10.10.52:10443"
```

Best regards.

**Comment by t8m** [comment]
I would argue, that the new behavior is the correct one.

**Comment by tfloch** [comment]
From what I known, the behavior in nginx with [ssl_verify_client optional_no_ca](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client) option has always been the "before" one (even with openssl 1.0.1). **An expired client certificate was accepted by nginx**, and if was up to the upstream application to analyze the certificate and to decide to process the request (or not).

But you may be right, maybe it could be considered as a bug in nginx ... fixed unintentionally in openssl 1.1.1i!

**Comment by t8m** [comment]
The nginx can still decide to ignore the expiration error when the verify callback is called with that error. Of course it means a code change in nginx would be needed.

**Comment by tfloch** [comment]
I do agree, nginx can be adapted to match the new openssl 1.1.1i behavior.

But I don't think #11359 was supposed to break anything for existing applications.
See commit description:

> This change in behaviour **is backward compatible** as user callbacks
who don't want to ignore UNABLE_TO_VERIFY_LEAF_SIGNATURE will
still abort the connection by default.

**Comment by t8m** [comment]
Yeah, it is unintended consequence of the commit.

**Comment by mdounin** [comment]
With `ssl_verify_client optional_no_ca;` nginx is not expected to accept expired certificates, yet may do so if the error returned by `SSL_get_verify_result()` is not about expired certificate, but about unknown CA. Previously, verification of expired certificates used to fail with `ssl_verify_client optional_no_ca;` in some cases as well (see [here](https://trac.nginx.org/nginx/ticket/338)). If you want to nginx to ignore other certificate errors, such as expired certificate, you have to configure nginx to ignore other certificate errors as well, using `error_page 495 ...` ([docs](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#errors)). Note well that in either case it is up to backend application to fully validate the certificate.

Overall, this looks like something to fix in the particular nginx configuration, and this issue can be closed.

**Comment by t8m** [comment]
Yes, I agree. Closing.

**Comment by tfloch** [comment]
Hi!

Thank you for your reply.
 
> With `ssl_verify_client optional_no_ca;` nginx is not expected to accept expired certificates

Indeed, in practice, that was the case.

> yet may do so if the error returned by `SSL_get_verify_result()` is not about expired certificate, but about unknown CA. 

OK, I understand better why the client certificate behavior has changed then!
before 1.1.1i, `SSL_get_verify_result()` was probably only returning "Unknown CA" (error ignored by nginx), and the expired certificate was accepted (= transmitted to the backed application for final validation).
I will check `SSL_get_verify_result()` return value in nginx, using OpenSSL 1.1.1h in 1.1.1i.

> Previously, verification of expired certificates used to fail with `ssl_verify_client optional_no_ca;` in some cases as well (see [here](https://trac.nginx.org/nginx/ticket/338)).

Thank you for this information, I didn't know that. During the last 6 years (starting with nginx 1.9.5 + openssl 1.0.1), I have always seen nginx to "accept" expired certificate.


> If you want to nginx to ignore other certificate errors, such as expired certificate, you have to configure nginx to ignore other certificate errors as well, using `error_page 495 ...` ([docs](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#errors)). Note well that in either case it is up to backend application to fully validate the certificate.
> Overall, this looks like something to fix in the particular nginx configuration, and this issue can be closed.

Thanks, I will patch nginx client certificate code, to ignore expired certificates errors (to restore previous behavior).

Cheers.

**Comment by rmacklem** [comment]
With this change, the expiry date of certificates in
the verify chain (such as the site local CA root
certificate) are now checked and if they have
expired, results in X509_V_ERR_CERT_HAS_EXPIRED
even if the peer's certificate has not expired.

Was this an intended change in behaviour?

**Comment by t8m** [comment]
The expiry date of certificates in the verify chain were always checked in case the chain ends with a trusted certificate. The change in 231c228 affected just the case where the chain presented by the peer does not end with trusted CA certificate. In that case the callback to an application that can make the verification errors ignored can be called multiple times - the first time with the X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE and if the application decides to ignore the error the chain verification continues as if the root certificate was trusted meaning all the certificates along the chain are checked for valid signatures and expiration.

Yes, looking back in time we probably should not have added the change to the 1.1.1 branch but now that it is there and that it will stay with 3.0 as it is IMO the correct behavior, there is no point in reverting that on the 1.1.1 branch either.
