### ISSUE TITLE
Centos8 Make Error 

### ISSUE THREAD

**Issue by jdb130496** [openssl/openssl#14033]
While using make after ./config with -q and --enable-optimization to build latest OpenSSL Alpha Version on CENTOS8 Stream - Elrepo Kernel-ml-5.10.12 following error was encountered:
gcc: error: unrecognized command line option '-q'
make[1]: *** [Makefile:4274: apps/lib/libapps-lib-app_params.o] Error 1

Without using -q with ./config (but with --enable-optimization) following error was detected in make command:

cc1: error: unknown pass optimization specified in -fenable
make[1]: *** [Makefile:4262: apps/lib/libapps-lib-app_params.o] Error 1

**Comment by levitte** [comment]
I believe you're mixing us up with another software project.  OpenSSL's `config` has never known those arguments, as far as I can remember, and therefore tries to pass them on to the compiler.

**Comment by jdb130496** [comment]
I could compile successfully from source on the same server configuration for OpenSSL version 1.1.1i (./config -q --enable-optimization followed by make and finally make install). So tried it on 3.0 alpha but resulted in above error. I believe there are 3 projects - Which one I should try and can you please post a link here? Thank you in advance and also for clarifying vide above response.
