### ISSUE TITLE
Unable to build OpenSSL 1.1.1i for Apple Silicon Mac

### ISSUE THREAD

**Issue by samasubbaiahios** [openssl/openssl#14032]
We have a Mac application and we are trying to build OpenSSL 1.1.1i to support the New Apple Mac lineup, tried to build on New Apple M1 mac mini. Tried normal config command 
"./config" command, this is picking apple arm64, which is ios 64.

After checking 10-main.conf file, for arm64 mac, we need to use "darwin64-ppc-cc". By trying this and applying make, getting many errors. Please have a look at the attached files for the exact errors of the commands.
[M1 Mac Issues.txt](https://github.com/openssl/openssl/files/5902368/M1.Mac.Issues.txt)

**Comment by bbolli** [comment]
You may have to cherry-pick this commit from the OpenSSL_1_1_1-stable branch that's not released yet: 61168b5b8dde03f3b77ddf5e4b1b81c338c01746

**Comment by samasubbaiahios** [comment]
Is it for M1 chip Macs or iOS devices! as both use ARM processors, getting confused with the flags.
Also, the 'perlasm_scheme' key set with "ios64", which confusing for iOS devices. But my actual requirement is to build it for Mac device for Mac application development.
Please clarify on this.
Thanks

**Comment by paulidale** [comment]
It's for M1.

**Comment by samasubbaiahios** [comment]
thanks for the clarification @paulidale
