### ISSUE TITLE
Add testing of updated IV to evp_test and at least some cipher test data

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14047]
In #9524 it was suggested by @petrovr that there is insufficient testing of the updated IV values (currently only covered by evp_extra_test). Implementing the subject of this issue should fix that.

**Comment by jon-oracle** [comment]
Looking at this now. Adding support for a NextIV tag into evp_test is straightforward but augmenting/generating the test data will take some time.

**Comment by t8m** [comment]
This was fixed by merging #15041
