### ISSUE TITLE
Key generation in OpenSSL 3.0-dev is inflexible compared to OpenSSL 1.1.1

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#14054]
Related issues:

#13871 
#13952
#13956 

In OpenSSL 1.1.1, key generation could start from one keytype (in the reports referenced above, the starting point is DH), and depending on parameters, could end up with another keytype (DHX in the reports referenced above).

Current development with providers does not allow this type of key type change.

Question: do we actually want that sort of flexibility, or should the user / application know the exact keytype in advance?
*(note: considering scripts that are made for earlier OpenSSL versions, let alone applications that use the corresponding EVP_PKEY_CTX setters, answering "no" could be a breaking change)*

If we want to have that sort of flexibility, how do we fix it?

**Comment by levitte** [comment]
(I do have some ideas on how to fix it...  some of them aren't exactly small...)

**Comment by t8m** [comment]
My answer to the first question would be "no, unless we can invent a clear and non-hackish method how to do that".

And the answer to the how question could be to introduce some kind of key type hierarchy - i.e. to allow starting with a more generic key type and to end up with more special one. I would not allow starting with special type and ending with generic one.

DH key could be upgraded to DHX, RSA key to RSA-PSS, and possibly EC to SM2 - we currently use EC key to test SM2 performance in openssl speed (which fails - see #14052).

This should cover most relevant use-cases IMO. Even if 1.1.1 allowed anything else, I'd declare that as not supported anymore.

**Comment by levitte** [comment]
For a key type hierarchy, there's a relevant question: *who decides?*

Who decides what the hierarchy looks like?  Who decides what keytypes can be "upgraded", and to what?

**Comment by levitte** [comment]
To clarify my question, I view this with the libcrypto\<-\>provider edge in mind.  On which side of the edge is the decision made?  That'll have to direct the solution.

**Comment by t8m** [comment]
IMO the provider implementation should be the entity that decides. Meaning the upgrades would be only within a single provider and the provider would have to support both types.

Of course when legacy keys come into play things start to get ugly. But we might say we do not support type upgrades with legacy keys.

And yeah, :grin:  once we find that we could have too many limitations, we might actually decide to scratch the idea of type changes completely.

**Comment by levitte** [comment]
Okie, we're on the same page regarding who's responsible for the keytypes and the conversion between them.

Type upgrades with legacy keys *is already supported*. That can happen because the backends (the ameth and pmeth functions) have complete access to the EVP_PKEY itself and can do whatever the hell they want with, including changing the pkey_id. The problem we have is entirely on the provider side. 

So, to support this, libcrypto and the provider need to communicate, and there needs to be some mechanics to perform whatever the change is.

**Comment by HaveYouTall** [comment]
Could anyone help me with how to generate SM2 key directly, while `EVP_PKEY_set_alias_type()` has been removed in OpenSSL-3.0.0

**Comment by mattcaswell** [comment]
> Could anyone help me with how to generate SM2 key directly, while EVP_PKEY_set_alias_type() has been removed in OpenSSL-3.0.0

Please raise that as a separate issue. Its a slightly different problem to the issue covered here.

**Comment by slontis** [comment]
Documentation has been added related to this breaking change. Restrictions to what parameters can be set by DH and DHX have been documented.

**Comment by richsalz** [comment]
So can this issue be closed now?  Or leave it open and remove the '3.0.0 beta' label?
