### ISSUE TITLE
With fips and base provider the openssl pkcs12 -export fails due to PKCS12KDF needed for MAC

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14057]
Should we imply -nomac/-nomacver in that case possibly with some warning?

The PKCS12KDF is not FIPS approved so it cannot be included in the fips provider and there is unfortunately no other way how to do integrity checking for pkcs12 files.

**Comment by paulidale** [comment]
Agree that a reasonable error message is advisable.  We don't have a great way of detecting this generally -- although we could try the fetch early and see if it fails.

**Comment by slontis** [comment]
PKCS12_key_gen_uni() could raise an specific error also, since this is the single point where the fetch happens.

**Comment by t-j-h** [comment]
OTC: better error message
