### ISSUE TITLE
CI loops are not as comprehensive as they were under Travis

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14065]
There are tests that used to be run that aren't anymore.  The obvious ones are:

- [x] non x86/64 Linux platforms (Windows, OS/X, ARM, s390, PPC)
- [x] external tests
- [x] code coverage (noted in #14013)

Latest released .travis.yml can be found:

https://github.com/openssl/openssl/blob/cae118f9382c3790359b3ff050d6e01c11579a7f/.travis.yml#L1-L267

**Comment by paulidale** [comment]
I'd like to see a non-caching build present.  I.e. one where the providers' returns are never cached by libcrypto.  This has turned up a number of sticky problems so far and it continues to give (refer #13364 and its child PRs).

**Comment by t8m** [comment]
The only substantial missing stuff that was in Travis and we do not have it anymore are the builds on other architectures than x86_64. We have only cross-compilation builds but these do not run tests. Is it possible to do anything with this? We would have to have our own runners I suppose.

**Comment by levitte** [comment]
It is possible to run tests for mingw cross compilations.  wine needs to present, and EXE_SHELL needs to be set to it.
Others are possible as well with binfmt, although I've never experimented with those.

**Comment by paulidale** [comment]
Another possibility would be using qemu or another emulator to run tests on non-x86 platforms.  A quick check and it looks like qemu covers aarch32, aarch64, MIPS, PPC, S390x & SPARC.  We don't have licences for proprietary OSes (AIX etc), but we'd be able to test on Linux or a BSD derivative.  Adding test runs to the cross compile builds should be possible.

Is mingw cross compiled running under Wine going to increase our coverage much?  More testing is good but we've limited engineering resources to set things up and keep them running.

**Comment by levitte** [comment]
> Another possibility would be using qemu or another emulator to run tests on non-x86 platforms.

That's what binfmt does, I think...

**Comment by paulidale** [comment]
GitHub Actions are more comprehensive than what we had on Travis.
Closing this since there's nothing more to do.
