### ISSUE TITLE
Client authentication with Android KeyStore

### ISSUE THREAD

**Issue by misery** [openssl/openssl#14071]
Hi there,

we are required to use the Android KeyStore for our private key. But we also need to use that key for a TLS connection as client authentication. As it is not possible to extract the whole private key from the Android KeyStore to provide it to openssl - is it possible to delegate the required crypto functions that openssl needs to the Android KeyStore?

https://developer.android.com/training/articles/keystore

Best regards

**Comment by t8m** [comment]
Engines (in 1.1.1) and providers (in 3.0) are the way to do that.
