### ISSUE TITLE
Windows compilation option /Gs0 on 1.0.2x

### ISSUE THREAD

**Issue by VeeFu** [openssl/openssl#14072]
Hello experts,

One of the default compiler options for building OpenSSL on Windows is `/Gs0` documented [here](https://docs.microsoft.com/en-us/cpp/build/reference/gs-control-stack-checking-calls?view=msvc-160#:~:text=A%20stack%20probe%20is%20a,store%20the%20function's%20local%20variables).

Summarizing as best I can, `/Gs` tells the compiler how many bytes of stack space a function must consume before "stack probe" code is emitted to the beginning of the functions during code-generation.

`/Gs0` means all functions consuming any stack space first check a short distance into the stack to see if a page fault may occur and triggers expansion of the stack before entering the function.

Without `/Gs`, the "stack probe" code is emitted into functions consuming at least 4096 bytes of stack space.

This seems to be significant overhead when calling hash algorithms that iterate many thousands of times. This is especially true when running with FIPS enabled, as FIPS interjects lock-related calls between each iteration.

My questions are:
* Does anyone know why this option is set?
  It appears that the `/Gs0` option has been in place since the [beginning of OpenSSL history ](https://github.com/openssl/openssl/blob/d02b48c63a58ea4367a0e905979f140b7d090f86/util/pl/VC-32.pl).

* Are there serious risks to removing this compiler option?
  Near as I can tell, removing the option means that a page fault could now happen in the middle of a function call. I'm not sure what the further implications of this are for OpenSSL functions.

Thank you!

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input
