### ISSUE TITLE
Intermittent ssl errors and data corruption - 1.1.1f & 1.1.1j-dev

### ISSUE THREAD

**Issue by Peekayy** [openssl/openssl#14079]
I am facing heavy issues with my workstation that after investigation all seemed to be related to openssl.
For instance: chrome tabs crashing, curl showing SSL routines:ssl3_get_record:decryption failed or bad record mac errors, ...

I'm using Ubuntu 20.04 and current shipped version is 1.1.1f.

This happens only on this particular pc in my house, regardless of using ethernet or connection sharing from my cell phone. I've also tried different live linux distros (ubuntu, fedora, arch) just to see the same problem. However Windows has no issue at all, which makes sense.

After reading this: https://github.com/openssl/openssl/issues/11812 I decided to run the tests myself.
I ran tests 1.1.1j-dev branch.
And when they'd fail, they'd always fail on 80-test_dtls.
So here's a verbose failing run of 80-test_dtls :
[openssl-test-report.txt](https://github.com/openssl/openssl/files/5931951/openssl-test-report.txt)

I don't suspect this could be en openssl bug but more like a hardware issue or incompatibility. That's why I submitted a 'Question'.
However any help would be greatly welcome in finding the root cause or a workaround.
I can obviously provide more information.

Thanks.

**Comment by mattcaswell** [comment]
> chrome tabs crashing

Chrome uses boringssl not OpenSSL, so this is unlikely to be the same as your curl issue.

**Comment by kroeckx** [comment]
I suggest you run memtest86

**Comment by Peekayy** [comment]
> > chrome tabs crashing
> 
> Chrome uses boringssl not OpenSSL, so this is unlikely to be the same as your curl issue.

Thanks for pointing this out, I didn't know. But since it is a fork, I still believe the root cause can be the same.

> I suggest you run memtest86

Sorry I forgot to mention it, I ran 1 full pass of memtest86. I know this is generally considered insufficient but seeing how often I get ssl errors, I think a mem failure would have been detected in seconds. Also my Windows working perfectly makes me think it's not memory related.

I also ran prime95 stress tests for about an hour without any failure.

If you believe memtest is the way to go anyway, I'll do it this weekend.

**Comment by t8m** [comment]
This can be some hw issue that is triggered only by linux kernel or something in the openssl and boringssl code.

**Comment by t8m** [comment]
You could try building and testing openssl on windows for example, whether it shows the same problem.

**Comment by npribadi** [comment]
> I am facing heavy issues with my workstation that after investigation all seemed to be related to openssl.
> For instance: chrome tabs crashing, curl showing SSL routines:ssl3_get_record:decryption failed or bad record mac errors, ...
> 
> I'm using Ubuntu 20.04 and current shipped version is 1.1.1f.
> 
> This happens only on this particular pc in my house, regardless of using ethernet or connection sharing from my cell phone. I've also tried different live linux distros (ubuntu, fedora, arch) just to see the same problem. However Windows has no issue at all, which makes sense.
> 
> After reading this: #11812 I decided to run the tests myself.
> I ran tests 1.1.1j-dev branch.
> And when they'd fail, they'd always fail on 80-test_dtls.
> So here's a verbose failing run of 80-test_dtls :
> [openssl-test-report.txt](https://github.com/openssl/openssl/files/5931951/openssl-test-report.txt)
> 
> I don't suspect this could be en openssl bug but more like a hardware issue or incompatibility. That's why I submitted a 'Question'.
> However any help would be greatly welcome in finding the root cause or a workaround.
> I can obviously provide more information.
> 
> Thanks.

**Comment by davidben** [comment]
(Re Chrome, we do network stuff outside of the renderer processes, so a tab crash is unlikely to be BoringSSL. There are some [instructions](https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug) you can follow for reporting the Chrome crash.)

**Comment by Peekayy** [comment]
Thanks everyone, I'm going to follow your suggestions. However, I've been sick since last friday and too tired to spend some time on computer. So no news for now but I'll keep you updated for sure.

**Comment by Peekayy** [comment]
So, running the tests on windows didn't fail at all. I even added a for loop around the dtls tests just to run them hundred of times.

Also, posted crash report : https://bugs.chromium.org/p/chromium/issues/detail?id=1177829  (which was not easy as the report tab kept crashing before I could post)

**Comment by Peekayy** [comment]
So after spending too many hours on this issue, I resigned myself not to use linux with this computer anymore...
Pretty sad if you ask me but not enough free time for now to push investigations further.
Thanks for your help anyway!
