### ISSUE TITLE
Openssl 1.1.1i - Can't do SSL handshake

### ISSUE THREAD

**Issue by Real96** [openssl/openssl#14085]
Hey guys, i'm trying to run a server using Nginx with sslv3 and ciphers RC4-SHA:RC4-MD5 support.
I was able to do this on Ubuntu 16.04 using Openssl 1.0.2u source + last nginx version source (nginx-1.19.6). I builded Nginx using this command:

```./configure --with-http_ssl_module --with-openssl=/path/to/openssl-1.0.2u --with-openssl-opt=enable-ssl3 --with-openssl-opt=enable-ssl3-method --with-openssl-opt=enable-weak-ssl-ciphers```

and after setting up nginx config file everything worked perfectly. I was able to obtain the ssl certificate using this command from an Ubuntu 14.04 machine:

```openssl s_client -connect MyIP:443 -ssl3 -cipher RC4-SHA:RC4-MD5```.

I tryed to do the same thing building Nginx with Openssl 1.1.1i source with the same configuration options, but after setting up nginx conf file, when i try to run ```openssl s_client -connect...``` command, i get this error:
```
CONNECTED(00000003)
140420793624224:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:339:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : SSLv3
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1612540521
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

In Nginx error.log file i got this:

```
SSL_do_handshake() failed (SSL: error:141FC044:SSL routines:tls_setup_handshake:internal error) while SSL handshaking, client: 192.168.1.10, server: 0.0.0.0:443
```
Did something change with openssl 1.1.1? Am i missing any configuration options to enable SSLv3 + RC4-SHA:RC4-MD5?
Thanks for any tips!

**Comment by mattcaswell** [comment]
> SSL: error:141FC044:SSL routines:tls_setup_handshake:internal error

That comes from this code:

````
        /*
         * Sanity check that the maximum version we accept has ciphers
         * enabled. For clients we do this check during construction of the
         * ClientHello.
         */
        if (ssl_get_min_max_version(s, &ver_min, &ver_max, NULL) != 0) {
            SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_SETUP_HANDSHAKE,
                     ERR_R_INTERNAL_ERROR);
            return 0;
        }
````

So it looks like nginx hasn't got any ciphers enabled for the maximum supported TLS version.

**Comment by mattcaswell** [comment]
> So it looks like nginx hasn't got any ciphers enabled for the maximum supported TLS version.

No...wait...scratch that....this is just the start of that test. Something else is going on.

**Comment by Real96** [comment]
> > SSL: error:141FC044:SSL routines:tls_setup_handshake:internal error
> 
> That comes from this code:
> 
> ```
>         /*
>          * Sanity check that the maximum version we accept has ciphers
>          * enabled. For clients we do this check during construction of the
>          * ClientHello.
>          */
>         if (ssl_get_min_max_version(s, &ver_min, &ver_max, NULL) != 0) {
>             SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_SETUP_HANDSHAKE,
>                      ERR_R_INTERNAL_ERROR);
>             return 0;
>         }
> ```
> 
> So it looks like nginx hasn't got any ciphers enabled for the maximum supported TLS version.
I didn't change nginx version, that's why i think that the problem is on openssl configuration

**Comment by mattcaswell** [comment]
Right, so looking further into this we can see that  `ssl_get_min_max_version` is returning a non-zero return value. That can only happen in one of two scenarios. The first scenario requires the last parameter to be non-NULL - which it isn't, so we know its not that. Therefore must be the second scenario:

There are no SSL/TLS protocol versions enabled

Unfortunately I know nothing about nginx configuration...or how to enable/disable different TLS protocol versions.

**Comment by Real96** [comment]
> Right, so looking further into this we can see that `ssl_get_min_max_version` is returning a non-zero return value. That can only happen in one of two scenarios. The first scenario requires the last parameter to be non-NULL - which it isn't, so we know its not that. Therefore must be the second scenario:
> 
> There are no SSL/TLS protocol versions enabled
> 
> Unfortunately I know nothing about nginx configuration...or how to enable/disable different TLS protocol versions.

Enabling a specific ssl version in nginx isn't difficult.
You have to add

```
ssl_protocols SSLv3;
ssl_ciphers RC4-SHA:RC4-MD5:@SECLEVEL=0;
```
in the configuration file. The syntax is also ok (i did ngix -t), the same config settings work with openssl 1.0.2u t.t

**Comment by mattcaswell** [comment]
Hmmm....is it possible that you're picking up the wrong libssl at runtime? E.g. a system version rather than the version you compiled?

**Comment by Real96** [comment]
> Hmmm....is it possible that you're picking up the wrong libssl at runtime? E.g. a system version rather than the version you compiled?

Wouldn't the problem exist with openssl 1.0.2u also?

**Comment by mattcaswell** [comment]
> Wouldn't the problem exist with openssl 1.0.2u also?

Not necessarily. 1.1.x and 1.0.2 are not binary compatible. So, if the system provides 1.1.x, and nginx is linked against 1.0.2 then it will never pick up the system version at runtime. Another related thought is that 1.0.2 defaults to creating static libraries, but 1.1.x defaults to creating dynamic libraries (although its possible that the nginx build stuff overrides this anyway).

**Comment by Real96** [comment]
> > Wouldn't the problem exist with openssl 1.0.2u also?
> 
> Not necessarily. 1.1.x and 1.0.2 are not binary compatible. So, if the system provides 1.1.x, and nginx is linked against 1.0.2 then it will never pick up the system version at runtime. Another related thought is that 1.0.2 defaults to creating static libraries, but 1.1.x defaults to creating dynamic libraries (although its possible that the nginx build stuff overrides this anyway).

The thing is that i link nginx to the 1.1.1 source version at buold time. Not to the system. If i need 1.0.2 i link itnto 1.0.2 always at build time

**Comment by mattcaswell** [comment]
> The thing is that i link nginx to the 1.1.1 source version at buold time.

If you're using dynamic linking then that doesn't matter. The dynamic library still gets loaded at runtime and can end up getting the wrong one.

**Comment by Real96** [comment]
> > The thing is that i link nginx to the 1.1.1 source version at buold time.
> 
> If you're using dynamic linking then that doesn't matter. The dynamic library still gets loaded at runtime and can end up getting the wrong one.

To make nginx build complete without errors i run this command first:
```
apt-get install libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev
```

(got from: https://askubuntu.com/questions/980145/cant-add-nginx-module-requires-zlib)

Can libssl-dev be the issue?

**Comment by mattcaswell** [comment]
> libssl-dev

That  package is for the include files for the system provided version of OpenSSL. If you need that to build without errors then something is not right in your build setup....its not finding the headers for your custom OpenSSL build. That's slightly different to what library gets loaded at runtime - but its very likely to cause problems if you want non-default OpenSSL options (which you do).

**Comment by Real96** [comment]
> > libssl-dev
> 
> That package is for the include files for the system provided version of OpenSSL. If you need that to build without errors then something is not right in your build setup....its not finding the headers for your custom OpenSSL build. That's slightly different to what library gets loaded at runtime - but its very likely to cause problems if you want non-default OpenSSL options (which you do).

I just tryed building both in ubuntu 20.04. Didn't get error about libssl, but i always have the same problem t.t It still complained about libpcre3 and zlib1g so i had to install them

**Comment by Real96** [comment]
In the end i was able to fix this!

I downloaded the last openssl source (1.1.1i) and the last nginx source (1.19.6).
I compiled and installed openssl with the following commands:
```
./config enable-ssl3 enable-ssl3-method enable-weak-ssl-ciphers
make
sudo make install
```

I edited openssl.cnf file (/usr/local/ssl/openssl.cnf) adding
```
openssl_conf = default_conf
```
at the beginning of the file and adding
```
[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = ALL:@SECLEVEL=0
```
at the bottom of the file. This to enable old ciphers (RC4-SHA and RC4-MD5).
Then i compiled and installed nginx with the following commands:
```
./configure --with-http_ssl_module --with-ld-opt="-L/usr/local
make
sudo make install
```

After configuring nginx for ssl certificates i was able to get them!

**Comment by mattcaswell** [comment]
Great! Glad you got it sorted.

**Comment by Real96** [comment]
Yeah i installed them separately and used the ALL flag to enable all the old ciphers. Do you know if there is a way to add the ALL flag at compile time instead of adding it in the conf file?

**Comment by Real96** [comment]
> Great! Glad you got it sorted.

Yeah i installed them separately and used the ALL flag to enable all the old ciphers. Do you know if there is a way to add the ALL flag at compile time instead of adding it in the conf file?

**Comment by mattcaswell** [comment]
> Do you know if there is a way to add the ALL flag at compile time instead of adding it in the conf file?

No, you can't change the default cipher list at compile time.

**Comment by Real96** [comment]
> > Do you know if there is a way to add the ALL flag at compile time instead of adding it in the conf file?
> 
> No, you can't change the default cipher list at compile time.

Perfect, good to know. Thanks!
