### ISSUE TITLE
BIO_set_mem_buf would cause mem corruption when calling BIO_free

### ISSUE THREAD

**Issue by william-zk** [openssl/openssl#14098]
Openssl version: 1.1.1
Code like this:
```
BUF_MEM     bufmem;
char              str[2048];

bio = BIO_new(BIO_s_mem());
bufmem.length = 0;
bufmem.data = str;
bufmem.max = buf_len;
BIO_set_mem_buf(bio, &bufmem, BIO_CLOSE);
BIO_free(bio);
```
would cause "double free or corruption", which address is `&str[0]`
It seems that `BIO_set_mem_buf` only support read_only mode, or will meet this memory problem

**Comment by paulidale** [comment]
I don't consider this a bug.  A BIO_s_mem() requires allocated memory because it is freed when the BIO is destroyed.  The documentation should describe this better however.

**Comment by william-zk** [comment]
I got it, thanks
