### ISSUE TITLE
how to get certificate purpose with openssl 1.1.1 in c/c++

### ISSUE THREAD

**Issue by libxengine** [openssl/openssl#14090]
can't used this code

	X509_check_ca(pSt_X509);
	LONG lKeyUsage = pSt_X509->ex_kusage;
	if ((lKeyUsage & KU_DATA_ENCIPHERMENT) == KU_DATA_ENCIPHERMENT)
	{
		//encry
	}
	else if ((lKeyUsage & KU_DIGITAL_SIGNATURE) == KU_DIGITAL_SIGNATURE)
	{
		//sign
	}

**Comment by t8m** [comment]
There is a function X509_get_extended_key_usage() that will return the extended key usage value.
