### ISSUE TITLE
Add an EVP demo for key encoding using RSA

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14116]
Do both encode and decode.

It should be the current best practice (fetch), have proper error handling and resource allocation/deallocation and be in the style of a known answer test.

**Comment by CuckooEXE** [comment]
I'd like to take a crack at this one, if you'd like to assign it to me!

**Comment by paulidale** [comment]
It's all yours :)

**Comment by paulidale** [comment]
There is likely going to be a new easier API for key generation soon: #14695  The exact form isn't known, however this will only have a minor or no impact on this example.

**Comment by t8m** [comment]
Yeah, the demo should demonstrate the "normal, full-featured way" not the quick call (that call should not need a demo).

**Comment by CuckooEXE** [comment]
Before I countinue development, I want to make sure I'm on the right track (I'm fairly new to OpenSSL). Could you point out the "core" function(s) that need to be demonstrated? Just want to make sure I get exactly what you want :)

**Comment by t8m** [comment]
Please look at the examples in https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_DECODER_from_bio.pod and https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_ENCODER_to_bio.pod.

**Comment by CuckooEXE** [comment]
Thanks! I'll change what I had coded 😅

**Comment by richsalz** [comment]
perhaps a simple test is to build against a version of openssl that is configured with `no-deprecated`  right, @t8m ?

**Comment by t8m** [comment]
Yeah, sure, the demo should build fine against no-deprecated build of openssl.
