### ISSUE TITLE
Add an EVP demo for RSA key generation

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14111]
Generate a 4096 bit key.  Include a validation step (separate function).

It should be the current best practice (fetch), have proper error handling and resource allocation/deallocation and be in the style of a known answer test.

**Comment by peterdjalaliev** [comment]
Is this to add an example of an RSA key generation code snippet to the respective man page(s)?

**Comment by paulidale** [comment]
It is adding a new program to the demo directory that generates an RSA key.
It's fine to do more, e.g. save to PEM file.

**Comment by peterdjalaliev** [comment]
FWIW, I closed the pull request because I don't have my employer's permission to contribute it.
