### ISSUE TITLE
Add an EVP signature demo for RSA

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14113]
Use RSA OAEP.  Do both validation and signature generation.

It should be the current best practice (fetch), have proper error handling and resource allocation/deallocation and be in the style of a known answer test.

**Comment by hlandau** [comment]
I have a rough draft for this but some questions:

* AIUI OAEP is only applicable to encryption, not signing. What do you want to use?
* PSS is non-deterministic so known answer tests don't seem applicable.

**Comment by t8m** [comment]
IMO it should be RSA-PSS and KAT is not really needed. Just create a signature with one function and verify it with another.

**Comment by hlandau** [comment]
Sounds good.
