### ISSUE TITLE
Add an EVP demo for signatures using EC

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14115]
Use a named curve.  Do both validation and signature generation.

It should be the current best practice (fetch), have proper error handling and resource allocation/deallocation and be in the style of a known answer test.

**Comment by yuechen-chen** [comment]
Looking into this issue now..

**Comment by slontis** [comment]
The comment here related to KAT here is misleading.. KATS can only be done on verify.. For this example a sign and verify is sufficient.
