### ISSUE TITLE
Support cross compillin OpenSSL for target ios-simulator-arm64 on host darwin-arm64(m1)

### ISSUE THREAD

**Issue by 6epreu** [openssl/openssl#14131]
Hello support team
I just found solution for building OpenSSL for target darwin64-arm64-cc which is supportns MacOS
But is the support to build OpenSSL for target ios-simulator-arm64-cc?

**Comment by 6epreu** [comment]
I have added this to 10-main.conf
```
"ios64sim-arm64-cc" => {
        inherit_from     => [ "darwin-common", asm("aarch64_asm") ],
        cflags           => add("-arch arm64 -DOPENSSL_NO_ASM -mios-version-min=7.0.0 -isysroot \$(CROSS_TOP)/SDKs/\$(CROSS_SDK) -fno-common"),
        sys_id           => "iOS",
        bn_ops           => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
        perlasm_scheme   => "ios64",
    },
```

But got this

```
ld: building for iOS, but linking in .tbd file (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libSystem.tbd) built for iOS Simulator, file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libSystem.tbd' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by 6epreu** [comment]
The full story
I had a project where I have compiled OpenSSL from source for IOS for 2 targets
- for ios-device-arm64 
```
"ios64-cross" => {
        inherit_from     => [ "ios64-xcrun" ],
        CC               => "cc",
        cflags           => add("-isysroot \$(CROSS_TOP)/SDKs/\$(CROSS_SDK)"),
    },
```
- for ios-x86_64-simulator
```
"ios64sim-cross" => {
        inherit_from     => [ "darwin-common", asm("no_asm") ],
        cflags           => add("-arch x86_64 -DOPENSSL_NO_ASM -mios-version-min=7.0.0 -isysroot \$(CROSS_TOP)/SDKs/\$(CROSS_SDK) -fno-common"),
        sys_id           => "iOS",
        bn_ops           => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
        perlasm_scheme   => "ios64",
    },
```

Then pack using lipo
```
lipo ${TMP_DIR}/x86_64/lib/lib${LIBNAME}.a \
	${TMP_DIR}/arm64/lib/lib${LIBNAME}.a \
	-output ${TMP_DIR}/lib/lib${LIBNAME}.a -create
```

This *.a file I have used in my ios SDK project and it have succesfully compiled for simulator and arm device
Profit!

Now when I got apple m1 computer which is arm64 based I was not surprized that ios SDK project was not able to compile for simulator because now it's arm64 base and I got error like 
```
in .../ossl/lib/libcrypto.a(bio_lib.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
```

**Conclusion**
I need to compile openSsl for simulator arm64 but next thing... Im doubting if I will be able to pack 2 libraries 
1) for arm64 device 
2) for arm64 simulator 
In one fat *.a file using lipo...


Any help really appreciated. Pretty sure that Im not alone in this fight :-)

**Comment by paulidale** [comment]
The problem the OpenSSL team has here is that we do not have access to M1 based Macs.  If somebody were to submit a pull request fixing this, it would be considered.

**Comment by 6epreu** [comment]
Conclusion
`
export CROSS_TOP="`xcode-select --print-path`/Platforms/iPhoneSimulator.platform/Developer"
export CROSS_SDK="iPhoneSimulator.sdk"
./Configure iossimulator-xcrun "-arch arm64 -fembed-bitcode" no-asm no-shared no-hw no-async
`

This do the tric.
As a result libssl.a and libcrypto.a will be compiled for arm64 simulator

Could be close

**Comment by Jeevhi** [comment]
Thanks @6epreu  It worked, yet to test though!

**Comment by TheHmmka** [comment]
> Conclusion ` export CROSS_TOP="`xcode-select --print-path`/Platforms/iPhoneSimulator.platform/Developer" export CROSS_SDK="iPhoneSimulator.sdk" ./Configure iossimulator-xcrun "-arch arm64 -fembed-bitcode" no-asm no-shared no-hw no-async `
> 
> This do the tric. As a result libssl.a and libcrypto.a will be compiled for arm64 simulator
> 
> Could be close

Can you format the code, please, cause it's hard to understand?!

**Comment by theo-dep** [comment]
> Conclusion
> 
> ```
> export CROSS_TOP="`xcode-select --print-path`/Platforms/iPhoneSimulator.platform/Developer"
> export CROSS_SDK="iPhoneSimulator.sdk"
> ./Configure iossimulator-xcrun "-arch arm64 -fembed-bitcode" no-asm no-shared no-hw no-async
> ```
> 
> This do the tric. As a result libssl.a and libcrypto.a will be compiled for arm64 simulator
> 
> Could be close

@6epreu this code is to compile binaries for arm64 iphone simulator would be? Did you try to create a framework with iphoneos arm64, iphone simulator arm64 and x86_64 in a single file?
