### ISSUE TITLE
Demonstration code

### ISSUE THREAD

**Issue by paulnelsontx** [openssl/openssl#14134]
Epic to complete sample code demonstrating using new APIs.

**Comment by paulidale** [comment]
The relevant component issues are:

#14102 CCM
#14103 GCM
#14104 non-AEAD cipher
#14105 digest
#14106 XOF digest
#14107 PBKDF2
#14108 SCRYPT
#14109 HMAC
#14110 CMAC
#14111 RSA key gen
#14112 EC key gen
#14113 RSA sign/verify
#14114 DSA sign/verify
#14115 EC sign/verify
#14116 RSA key encode/decode
#14117 EC key encode/decode
#14118 Key agreement
#14119 AES key wrap
#14120 HKDF
#14121 SIPHASH
#14122 POLY1305
#14123 GMAC
#14124 assymetric cipher

#14125 Build & test infrastructure

**Comment by mspncp** [comment]
Uhm... do we _really_ need yet another label, one which does not have a clear purpose and breaks all naming conventions? Or is this just a fun label? How about using [triaged: documentation](https://github.com/openssl/openssl/labels/triaged%3A%20documentation) instead?

**Comment by mspncp** [comment]
> Uhm... do we _really_ need yet another label, one which does not have a clear purpose and breaks all naming conventions? Or is this just a fun label? How about using [triaged: documentation](https://github.com/openssl/openssl/labels/triaged%3A%20documentation) instead?

Oh, I see, it's a term from Jira. Well, if you insist... sigh. But please use all lowercase.

**Comment by richsalz** [comment]
> Oh, I see, it's a term from Jira. 

Agile, actually.

**Comment by paulidale** [comment]
I've lower-cased the label.

**Comment by t8m** [comment]
What about using `agile: blah` for the labels related to the agile methodology?

**Comment by nelsonopenssl** [comment]
I have made this issue an “Epic” in ZenHub.  It will appear quite differently when opened from the Kanban board. ZenHub created the "epic" label and apparently needs it to properly display the Kanban board. 

I want to have a consistent error handling style.  I like using indenting with ifs instead of using go to. 
I would also like to see the demonstrated code be in a function so it is outside of main(). This raises the importance of the clean up code to the reader.

**Comment by t8m** [comment]
> I have made this issue an “Epic” in ZenHub. It will appear quite differently when opened from the Kanban board. ZenHub created the "epic" label and apparently needs it to properly display the Kanban board.

OK, that unfortunately means we have to keep the label name as is :disappointed:

> I want to have a consistent error handling style. I like using indenting with ifs instead of using go to.

This is IMO OTC decision to make as we can have different opinions on that. The nested ifs or duplicating the cleanup for each call makes the demo code less clear IMO.

> I would also like to see the demonstrated code be in a function so it is outside of main(). This raises the importance of the clean up code to the reader.

**Comment by paulidale** [comment]
Agreed, this style used in the demos should be an OTC discussion.  There are merits both ways.

**Comment by richsalz** [comment]
Why not use the openssl coding style?

**Comment by mattcaswell** [comment]
> Why not use the openssl coding style?

IMO we should be using OpenSSL coding style for the demos (and in fact that is the default position absent a decision otherwise from OTC). See chapter 7 for error handling.

**Comment by nhorman** [comment]
It seems like all the issue tasks above are marked as complete, including our ability to build them in CI, as such this seems complete

marking as inactive, to be closed at the end of the 3.4 dev cycle barring further input

**Comment by t8m** [comment]
Yes, this is complete. Closing
