### ISSUE TITLE
Create a nightly CI loop

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14142]
The on commit CI loops are great but there is a point where the time they take to run is annoying.  Refer #14126 where addition of a one hour run was considered bad.

Should we create a nightly CI loop that runs more extensive / longer tests?

If so, what tests should be in it?
* The full non-caching ASAN run.
* Some of the build bot tests if they can be hooked in nicely.

How should we define night?  I.e. what time should such tests be kicked off?

**Comment by mattcaswell** [comment]
Would this replace run-checker? And if not, why would we not use run-checker for these types of tests?

**Comment by paulidale** [comment]
Either.  I've not been properly introduced to run-checker.

**Comment by mattcaswell** [comment]
@paulidale meet run-checker:

https://github.com/openssl/tools/tree/master/run-checker

run-checker meet @paulidale.

We run it nightly and failure reports go to the openssl-commits mailing list. I'm wondering whether there is a better way to get the reports out. Currently you get a separate email for each failed run, and you have to be on openssl-commits to get it.

**Comment by t8m** [comment]
Yeah, the reports in the e-mails are also not as comprehensive as I'd like them to see. Could full logs be stored somewhere for download for a short period of time?

**Comment by mattcaswell** [comment]
> Could full logs be stored somewhere for download for a short period of time?

That would be nice. Also nice would be some kind of dashboard showing the current run-checker status across all builds (perhaps with clickable links to get the logs).

**Comment by paulidale** [comment]
Something like [Jenkins](https://www.jenkins.io/)?

**Comment by mattcaswell** [comment]
> Something like Jenkins?

Yeah, something like that. Or I guess perhaps buildbot can do this too?

**Comment by paulidale** [comment]
Closing this.  Run-checker is good enough.
