### ISSUE TITLE
Add durations to the test output

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14141]
Knowing the relative duration of each of the CI tests will allow us to more easily maintain a cap on the build times.

**Comment by richsalz** [comment]
do you mean each test, or each stanza (e.g., that runs all the tests)?

**Comment by paulidale** [comment]
I'm after each stanza I think but both would be better.

The problem I've hit in #14126 is that the tests take an hour to run.  The problem being addressed doesn't really need all the tests run, so excluding some brings the time down.

**Comment by levitte** [comment]
The manual for `Test::Harness` (which is a foundation for `Test::More`) says this in its section on environment variables:

> "HARNESS_TIMER"
> Setting this to true will make the harness display the number of milliseconds each test took.  You can also use prove's "--timer" switch.

So a simple `HARNESS_TIME=1` in the right spot would be an option.
I have no idea what the granularity of those timers is.

**Comment by paulidale** [comment]
Hmmm, I'm not seeming to get times out when I set that.  It too late to dig in now.

**Comment by levitte** [comment]
Ah, right, I sometimes forget TAP::Harness, which is the more modern variant.  This makes HARNESS_TIMER work for that as well:

``` diff
diff --git a/test/run_tests.pl b/test/run_tests.pl
index 2be4e607a0..fd585a60ec 100644
--- a/test/run_tests.pl
+++ b/test/run_tests.pl
@@ -44,6 +44,7 @@ my %tapargs =
       lib               => [ $libdir ],
       switches          => '-w',
       merge             => 1,
+      timer             => $ENV{HARNESS_TIMER} ? 1 : 0,
     );
 
 $tapargs{jobs} = $jobs if $jobs > 1;
```

**Comment by levitte** [comment]
... and to answer the other question: the timer measures per test recipe (i.e. per `.t` file processed)

**Comment by paulidale** [comment]
That works.  I've created a PR with this change.
