### ISSUE TITLE
utf8 use is unsafe

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#14174]
I am concerned that using UTF8 in PARAM's is not safe and could lead to errors. 

Look at &#x1F385 which is UTF8 encoded as 0xF0 0x9F 0x8E 0x85. What happens is the UTF8 is truncated and the trailing 0x85 byte, for example, is omitted. That shouldn't be a valid PARAM string -- how is the error returned?

What happens is someone mistakenly puts an eight-bit "ascii" value there? That's the most likely thing that will happen, I believe. Suppose someone enters a Cyrillic §, which is 0xA7 and that is likely to mess up anything that really wants to use *real* UTF8.

One possibility is to change the current UTF8 to a "CHAR8BIT" type. If not doing that, the position so far, "it's up to the receiver to check," isn't good, especially when consider that the project has recently been adding run-time checks for NULL pointers. Why not a run-time check for bad UTF8? It's possible to do that checking without depending on a heavyweight conversion library, see https://www.fileformat.info/info/unicode/utf8.htm.

Also, the byte-order mark should be supported. This is described in many places, including https://www.rfc-editor.org/rfc/rfc3629.

**Comment by levitte** [comment]
I'm not sure what would be gained with `CHAR8BIT`.  What does that tell anyone?  That they should shove in any 8-bit character they want?  What happens with encoding?  Is ASCII ok?  Is ISO-8859-15 ok?  Is EBCDIC ok?  How should the receiving end handle that?  How do you detect errors in that case?  Can you even detect an error in that case, and based on what assumptions?
I guess that the bottom line is, how is that any safer?

Regarding error checking, I would say that it's much easier if you can assume that UTF-8 should be passed.  But, who should do the checking?  The application?  libcrypto?  the provider?
Do note that *our* providers compare must UTF8 strings with other strings, one way or another, and those other strings are all ASCII.  The error check in that case is quite easy; if the strings aren't the same, according to strcmp() or strcasecmp(), then there's an error recorded.

**Comment by richsalz** [comment]
I don't know how Windows handles codesets, but on Unix platforms the codeset is a per-process attribute.  So while it's possible the maincode will use a different codeset from a loaded library, that seems less likely than someone will naively pass an 8bit string as a utf8 param.

But we have almost no experience, so this is everyone just guessing.

I am raising the issue, I'd  be fine if the OTC (not just individuals) thought about this and then dismissed it.

**Comment by t8m** [comment]
I do not really see what is wrong with assuming that strings passed are UTF8 encoded but not actively checking that. IMO openssl should not be in business of doing such checking when by itself it does not really care. It should be the business of applications to ensure that they do not pass in for example ISO-8859-15 encoded stuff.

**Comment by richsalz** [comment]
The project has decided, closing this issue.
