### ISSUE TITLE
Logical OR between repeated conditions 

### ISSUE THREAD

**Issue by geovandro** [openssl/openssl#14176]
Is there a reason at line below for performing the same condition with an OR?

https://github.com/openssl/openssl/blob/bae39163409ac3b8a1c579c2bcfbdae35370a133/ssl/statem/extensions_clnt.c#L236

**Comment by mattcaswell** [comment]
This is closing the two sub-packets started a bit above this point:

https://github.com/openssl/openssl/blob/bae39163409ac3b8a1c579c2bcfbdae35370a133/ssl/statem/extensions_clnt.c#L214-L215

The first sub-packet if for the whole supported groups extension. The second is for the actual list of groups contained within that extension.
