### ISSUE TITLE
No check on return value of ASN1_item_ndef_i2d()

### ISSUE THREAD

**Issue by FloridSleeves** [openssl/openssl#14177]
In crypto/asn1/bio_ndef.c, line 116 in `ndef_prefix()`, the return value `derlen` of `ASN1_item_ndef_i2d` does not get checked. However, it could be smaller than 0.
I wonder whether the right handling should check `derlen<=0` before proceed.

**Comment by kaduk** [comment]
@FloridSleeves this got closed automatically when the fixes were merged, but I wanted to say thank you for reporting the issue -- it's a good thing to have fixed.

**Comment by FloridSleeves** [comment]
You are welcome!
