### ISSUE TITLE
recursive EVP_PKEY lock in evp_keymgmt_util_clear_operation_cache()

### ISSUE THREAD

**Issue by kaduk** [openssl/openssl#14171]
There's a path in evp_pkey_downgrade() that leads to calling evp_pkey_free_it() and in turn evp_keymgmt_util_clear_operation_cache() that tries to lock the EVP_PKEY's lock when it is already held.
Since #13924 , or when using rwlocks, this is either a deadlock or similar fatal condition (i.e., undefined behavior).

See the tracethrough at https://github.com/openssl/openssl/pull/13987#issuecomment-778486077 for a little more context on the codepath

**Comment by t8m** [comment]
I verified after the merge of #14319 that there is no such codepath that would lead to a recursive lock anymore.
Closing.

**Comment by kaduk** [comment]
I also confirmed that the test suite no longer deadlocks on FreeBSD, which is where I first observed the issue.
