### ISSUE TITLE
There is no documentation for CMS_compress.

### ISSUE THREAD

**Issue by nelsonopenssl** [openssl/openssl#14170]
Even though the man page for CMS_uncompress refers to it.

**Comment by mattcaswell** [comment]
It's here:

https://www.openssl.org/docs/man1.1.1/man3/CMS_compress.html

**Comment by nelsonopenssl** [comment]
I should have been more precise.  After "make install" there is no man page for CMS_compress in the installed man pages folder, but there is for CMS_uncompress.

**Comment by nelsonopenssl** [comment]
make install does indeed install a man page for CMS_compress
