### ISSUE TITLE
[master] 'openssl enc' can't access ciphers that libcrypto doesn't know about

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#14178]
I played a bit with external providers that offer ciphers that libcrypto doesn't know about, and that fails.
This is due to `opt_cipher()` (in `apps/lib/opt.c`) only tries to get the cipher with `EVP_get_cipherbyname()`, never with `EVP_CIPHER_fetch()`.

**Comment by richsalz** [comment]
Also, after #14135, it looks like the only place that was missed is for `OPT_WRAP` case in cms.c

Should `opt_cipher` just /always do the fetch call?

**Comment by beldmit** [comment]
I have a function used in the `speed` application that tries to first fetch cipher or digest and than to get it by name. It seems a reasonable approach now

**Comment by richsalz** [comment]
`OPT_WRAP` fixed in #14182

**Comment by levitte** [comment]
> Should `opt_cipher` just /always do the fetch call?

No, because engines.

**Comment by richsalz** [comment]
Please look at commit https://github.com/openssl/openssl/pull/14182/commits/59bd58929f5d93abe7b699f58deed652b7e733e2 part of #14182 and let me know if I got things right.

**Comment by levitte** [comment]
Since #14179 was closed, shouldn't this be as well?

**Comment by richsalz** [comment]
And also #14135  This shoudl be closed.
