### ISSUE TITLE
Using OpenSSL for Non-blocking server socket

### ISSUE THREAD

**Issue by cxxboy** [openssl/openssl#14186]
Hi, I'm writing a non-blocking/event-driven HTTP server and I wanted to use OpenSSL for TLS support. I have implemented it with `epoll()` and I'm specifically targeting Linux. My question is, How can I use OpenSSL for TLS support for a non-blocking server written with `epoll()`? I had successfully implemented TLS support with OpenSSL for a blocking socket in the past, but I cannot find any online docs/code example on using OpenSSL for a `epoll()` based non-blocking server.

It would be great if someone could help me with this.
Thank you!

**Comment by kaduk** [comment]
The `s_server` test utility has an option to use non-blocking IO.  It uses select() instead of epoll(), but the principles of operation should be close enough.

**Comment by SuperbTUM** [comment]
From my experiments, `ssl_accept` does not work well with non-blocking epoll... It will always give me `resource temporarily unavailable` error. But it works with blocking epoll.
