### ISSUE TITLE
EVP_DigestSignInit_ex ignores props when libctx == NULL

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#14183]
The propquery specified is ignored by `EVP_DigestSignInit_ex` and `EVP_DigestVerifyInit_ex`.

This is due to the following code in `do_sigver_init` (https://github.com/openssl/openssl/blob/master/crypto/evp/m_sigver.c#L63)
```
        if (libctx != NULL)
            ctx->pctx = EVP_PKEY_CTX_new_from_pkey(libctx, pkey, props);
        else
            ctx->pctx = EVP_PKEY_CTX_new(pkey, e);
```

The `libctx` is often (always?) NULL, so the first branch never happens. The else branch then is executed, which ignores `props`. I didn't find a similar code anywhere else in the repo. It feels wrong to detect legacy engines using `libctx`. Would you agree?

Shouldn't we instead of that use:
```
        if (e == NULL)
```
or
```
        if (libctx != NULL || props != NULL)
```

**Comment by levitte** [comment]
I would agree change the test to `(e == NULL)`.  PR welcome!
