### ISSUE TITLE
Timestamp verification error if the response contains 2 fingerprints in `id-smime-aa-signingCertificate`

### ISSUE THREAD

**Issue by zhanzhenzhen** [openssl/openssl#14190]
I use the TSA `http://timestamp.comodoca.com/rfc3161`, whose certificate chain includes an intermediate cert besides the root cert and the TSA signing cert.

All certs needed to reproduce this issue can be downloaded here:

[certs.zip](https://github.com/openssl/openssl/files/5991015/certs.zip)

- `comodo-root.pem` - The root cert
- `comodo-intermediate.pem` - The intermediate cert
- `comodo-leaf.pem` - The TSA signing cert
- `comodo-untrusted.pem` - Combination of the intermediate cert and the TSA signing cert

Here're the steps to reproduce:

First, create a file `sample-data.txt` with random content.

Then, get the timestamp response:

```bash
openssl ts -query -data sample-data.txt -sha256 | curl -s -S \
-H "Content-Type: application/timestamp-query" --data-binary @- -o sample-data.txt.tsr \
http://timestamp.comodoca.com/rfc3161
```

Finally, verify it:

```bash
openssl ts -verify -in sample-data.txt.tsr -data sample-data.txt \
-CAfile comodo-root.pem -untrusted comodo-untrusted.pem
```

It shows this error:

```
time stamp routines:ts_check_signing_certs:ess signing certificate error:crypto/ts/ts_rsp_verify.c:249
```

I researched `ts_rsp_verify.c` and found that although there're 2 untrusted certificates, the `chain` variable has 3 certificates, including the root certificate. But `cert_ids` only has 2 certificates. When the program searches `cert_ids` for the first 2 certificates in the chain, it succeeds. But when searching `cert_ids` for the 3rd certificate (the root certificate), it cannot find it and therefore produces an error.

At first I thought maybe it's the misconfiguration at the TSA side. Then I tested the TSA `http://timestamp.entrust.net/TSS/RFC3161sha2TS` and it shows the same error. This TSA's chain also contains an intermediate certificate.

When I timestamp a PDF document in Adobe Acrobat Reader DC using these 2 TSAs, they all produce good results. Adobe Acrobat Reader shows the timestamps are valid.

Version: v1.1.1 and v3.0.0

---

Added on Feb 17:

DigiCert's chain also contains an intermediate cert but doesn't cause verification error. The reason for the Comodo/Sectigo error is *not* that there's an intermediate cert, but that there're two SHA-1 fingerprints in `id-smime-aa-signingCertificate` in the response. Here's the comparison:

DigiCert:

```
 3030:d=8  hl=2 l=  11 prim: OBJECT            :id-smime-aa-signingCertificate
 3043:d=8  hl=2 l=  28 cons: SET               
 3045:d=9  hl=2 l=  26 cons: SEQUENCE          
 3047:d=10 hl=2 l=  24 cons: SEQUENCE          
 3049:d=11 hl=2 l=  22 cons: SEQUENCE          
 3051:d=12 hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3
```

Comodo/Sectigo:

```
  643:d=8  hl=2 l=  11 prim: OBJECT            :id-smime-aa-signingCertificate
  656:d=8  hl=3 l= 221 cons: SET               
  659:d=9  hl=3 l= 218 cons: SEQUENCE          
  662:d=10 hl=3 l= 215 cons: SEQUENCE          
  665:d=11 hl=2 l=  22 cons: SEQUENCE          
  667:d=12 hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:951137101D882F31BD513F949ADA4C68AD8C08F5
  689:d=11 hl=3 l= 188 cons: SEQUENCE          
  692:d=12 hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:02D65B95E28370C1570095FA88F923DD937FAD8F
```

**Comment by midnight-wonderer** [comment]
Great timing; I experienced the same error today too.
For me, it is from `http://timestamp.sectigo.com`, an alias of `http://timestamp.comodoca.com/rfc3161`, I supposed.

Java validates the response just fine.
I also wanted to add that there are 2 possible certificate paths.
* One already provided by the OP
* Another one chained to [AAACertificateServices](https://sectigo.com/resource-library/sectigo-root-intermediate-certificate-files)

Since the timestamp server can be updated arbitrarily, I will capture the request/response here.

<details>
  <summary>Base64 encoded request</summary>
  
> MDkCAQEwMTANBglghkgBZQMEAgEFAAQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAf8=
  
</details>


<details>
  <summary>Base64 encoded response</summary>
  
> MIITcTADAgEAMIITaAYJKoZIhvcNAQcCoIITWTCCE1UCAQMxDzANBglghkgBZQMEAgIFADCCAQ0GCyqGSIb3DQEJEAEEoIH9BIH6MIH3AgEBBgorBgEEAbIxAgEBMDEwDQYJYIZIAWUDBAIBBQAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhUAsilQtRSFO3T2KfQ7rX3ZQhLA/vIYDzIwMjEwMjE2MTU0MjQ3WqCBiqSBhzCBhDELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMSwwKgYDVQQDDCNTZWN0aWdvIFJTQSBUaW1lIFN0YW1waW5nIFNpZ25lciAjMqCCDfswggcHMIIE76ADAgECAhEAjHegAI/00bDGPZ86SIONazANBgkqhkiG9w0BAQwFADB9MQswCQYDVQQGEwJHQjEbMBkGA1UECBMSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHEwdTYWxmb3JkMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxJTAjBgNVBAMTHFNlY3RpZ28gUlNBIFRpbWUgU3RhbXBpbmcgQ0EwHhcNMjAxMDIzMDAwMDAwWhcNMzIwMTIyMjM1OTU5WjCBhDELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMSwwKgYDVQQDDCNTZWN0aWdvIFJTQSBUaW1lIFN0YW1waW5nIFNpZ25lciAjMjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAJGHSyyLwfEeoJ7TB8YBylKwvnl5XQlmBi0vNX27wPsn2kJqWRslTOrvQNaafjLIaoF9tFw+VhCBNToiNoz7+CAph6x00BtivD9khwJf78WA7wYc3F5Ok4e4mt5MB06FzHDFDXvsw9njl+nLGdtWRWzuSyBsyT5s/fCb8Sj4kZmq/FrBmoIgOrfv59a4JUnCORuHgTnLw7c6zZ9QBB8amaSAAk0dBahV021SgIPmbkilX8GJWGCK7/GszYdjGI50y4SHQWljgbz2H6p818FBzq2rdosggNQtlQeNx/ULFx6a5daZaVHHTqadKW/neZMNMmNTrszGKYogwWDG8gIsxPnIIt/5J4Khg1HCvMmCGiGEspe81K9EHJaCIpUqhVSu8f0+SXR0/I6uP6Vy9MNaAapQpYt2lRtm6+/a35Qu2RrrTCd9TAX3+CNdxFfIJgV6/IEjX1QJOCpi1arK3+3PU6sf9kSc1ZlZxVZkW/eOUg9m/Jg/RAYTZG7p4RVgUKWx7M+46MkLvsWE990Kndq8KWw9Vu2/eGe2W8heFBy5r4Qtd6L3OZU3b05/HMY8BNYxxX7vPehRfnGtJHQbLNz5fKrvwnZJaGLVi/UD3759jg82dUZbk3bEg+6CviyuNxLxvFbD5K1Dw7dmll6UMvqg9quJUPrOoPMIgRrRRKfM97gxAgMBAAGjggF4MIIBdDAfBgNVHSMEGDAWgBQaofhhGSAPw0F3RSiO0TVfBhIEVTAdBgNVHQ4EFgQUaXU3e7udNUJOv1fTmtufAdGu3tAwDgYDVR0PAQH/BAQDAgbAMAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwQAYDVR0gBDkwNzA1BgwrBgEEAbIxAQIBAwgwJTAjBggrBgEFBQcCARYXaHR0cHM6Ly9zZWN0aWdvLmNvbS9DUFMwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5zZWN0aWdvLmNvbS9TZWN0aWdvUlNBVGltZVN0YW1waW5nQ0EuY3JsMHQGCCsGAQUFBwEBBGgwZjA/BggrBgEFBQcwAoYzaHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0aWdvUlNBVGltZVN0YW1waW5nQ0EuY3J0MCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTANBgkqhkiG9w0BAQwFAAOCAgEASgN4kEIz7Hsagwk2M5hVu51ABjBrRWrxlA4ZUP9bJV474TnEW7rplZA3N73f+2Ts5YK3lcxXVXBLTvSoh90ihaZXu7ghJ9SgKjGUigchnoq9pxr1AhXLRFCZjOw+ugN3poICkMIuk6m+ITR1Y7ngLQ/PATfLjaL6uFqarqF6nhOTGVWPCZAu3+qIFxbradbhJb1FCJeA11QgKE/Ke7OzpdIAsGA0ZcTjxcOl5LqFqnpp23WkPnlomjaLQ6421GFyPA6FYg2gXnDbZC8Bx8GhxySUo7I8brJeotD6qNG4JRwW5sDVf2gaxGUpNSotiLzqrnTWgufAiLjhT3jwXMrAQFzCn9UyHCzaPKw29wZSmqNAMBewKRaZyaq3iEn36AslM7U/ba+fXwpW3xKxw+7OkXfoIBPpXCTH6kQLSuYThBxN6w21uIagMKeLoZ+0LMzAFiPJkeVCA0uAzuRN5ioBPsBehaAkoRdA1dvb55gQpPHqGRuAVPpHieiYgal1wA7f0GiUeaGgno62t0Jmy9nZay9N2N4+Mh4g5OycTUKNncczmYI3RNQmKSZAjngvue76L/Hxj/5QuHjdFJbeHA5wsCqFarFsaOkq5BArbiH903ydN+QqBtbD8ddo408HeYEIE/6yZF7psTzm0Hgjsgks4iZivzupl1HMx0QygbKvz98wggbsMIIE1KADAgECAhAwD2+s3WaYdHypRjaneC25MA0GCSqGSIb3DQEBDAUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKTmV3IEplcnNleTEUMBIGA1UEBxMLSmVyc2V5IENpdHkxHjAcBgNVBAoTFVRoZSBVU0VSVFJVU1QgTmV0d29yazEuMCwGA1UEAxMlVVNFUlRydXN0IFJTQSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0xOTA1MDIwMDAwMDBaFw0zODAxMTgyMzU5NTlaMH0xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAOBgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDElMCMGA1UEAxMcU2VjdGlnbyBSU0EgVGltZSBTdGFtcGluZyBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMgbAa/ZLH6ImX0BmD8gkL2cgCFUk7nPoD5T77NawHbWGgSlzkeDtevEzEk0y/NFZbn5p2QWJgn71TJSeS7JY8ITm7aGPwEFkmZvIavVcRB5h/RGKs3EWsnb111JTXJWD9zJ41OYOioe/M5YSdO/8zm7uaQjQqzQFcN/nqJc1zjxFrJw06PE37PFcqwuCnf8DZRSt/wflXMkPQEovA8NT7ORAY5unSd1VdEXOzQhe5cBlK9/gM/REQpXhMl/VuC9RpyCvpSdv7QgsGB+uE31DT/b0OqFjIpWcdEtlEzIjDzTFKKcvSb/01Mgx2Bpm1gKVPQF5/0xrPnIhRfHuCkZpCkvRuPd25Ffnz82Pg4wZytGtzWvlr7aTGDMqLufDRTUGMQwmHSCIc9iVrUhcxIe/arKCFiHd6QV6xlV/9A5VC0m7kUaOm/N14Tw1/AoxU9kgwLU++Le8bwCKPRt2ieKBtKWh97oaw7wW33pdmmTIBxKlyx3GSuTlZicl57rjsF4VsZEJd8GEpoGLZ8DXv2DolNnyrH6jaFkyYiSWcuoRsDJ8qb/fVfbEnb6ikEk1Bv8cqUUotStQxykSYtBORQDHin6G6UirqXDTYLQjdprt9v3GEBXc/Bxo/tKfUU2wfeNgvq5yQ1TgH36tjlYMu9vGFCJ10+dM70atZ2h3pVBeqeDAgMBAAGjggFaMIIBVjAfBgNVHSMEGDAWgBRTeb9aqitKz1SA4dibwJ3ysgNmyzAdBgNVHQ4EFgQUGqH4YRkgD8NBd0UojtE1XwYSBFUwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAwEwYDVR0lBAwwCgYIKwYBBQUHAwgwEQYDVR0gBAowCDAGBgRVHSAAMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2BggrBgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDovL29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAbVSBpTNdFuG1U4GRdd8DejILLSWEEbKw2yp9KgX1vDsn9FqguUlZkClsYcu1UNviffmfAO9Aw63T4uRW+VhBz/FC5RB9/7B0H4/GXAn5M17qoBwmWFzztBEP1dXD4rzVWHi/SHbhRGdtj7BDEA+N5Pk4Yr8TAcWFo0zFzLJTMJWk1vSWVgi4zVx/AZa+clJqO0I3fBZ4OZOTlJux3LJtQW1nzclvkD1/RXLBGyPWwlWEZuSzxWYG9vPWS16toytCiiGS/qhvWiVwYoFzY16gu9jc10rTPa+DBjgSHSSHLeT8AtY+dwS8BDa153fLnC6NIxi5o8JHHfBd1qFzVwVomqfJN2Udvuq82EKDQwWli6YJ/9GhlKZOqj0J9QVst9JkWtgqIsJLnfE5XkzeSD2bNJaaCV+O/fexUpHOP4n2HKG1qXUfcb9bQ11lPVCBbqvw0NP8srMftpmWJvQ8eYtcZMzN7iea5aDADHKHwW5NWtMe6vBE5jJvHOsXTpTDeGUgOw9Bqh/poUGd/rG4oGUqNODeqPk85sEwu8CgYyz8XBYAqNDEf+oRnR4GxqZtMl20OAkrSQeq/eww2vGnL8+3/frQo4TZJ577AWZ3uVYQ4SBuxq6x+ba6yDVdM3aO8XwgDCp3rrWiAoa6Ke60WgCxjKvj+QrJVF3UuWp0nr1IrpgxggQtMIIEKQIBATCBkjB9MQswCQYDVQQGEwJHQjEbMBkGA1UECBMSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHEwdTYWxmb3JkMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxJTAjBgNVBAMTHFNlY3RpZ28gUlNBIFRpbWUgU3RhbXBpbmcgQ0ECEQCMd6AAj/TRsMY9nzpIg41rMA0GCWCGSAFlAwQCAgUAoIIBazAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8XDTIxMDIxNjE1NDI0N1owPwYJKoZIhvcNAQkEMTIEMHrght84MlecL0HINHANz3XJMfWp6iSxKgaLXH/6u3J3N/1s3lQrnT4BNFkVfU4zUDCB7QYLKoZIhvcNAQkQAgwxgd0wgdowgdcwFgQUlRE3EB2ILzG9UT+UmtpMaK2MCPUwgbwEFALWW5Xig3DBVwCV+oj5I92Tf62PMIGjMIGOpIGLMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKTmV3IEplcnNleTEUMBIGA1UEBxMLSmVyc2V5IENpdHkxHjAcBgNVBAoTFVRoZSBVU0VSVFJVU1QgTmV0d29yazEuMCwGA1UEAxMlVVNFUlRydXN0IFJTQSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eQIQMA9vrN1mmHR8qUY2p3gtuTANBgkqhkiG9w0BAQEFAASCAgB/SFyUB4vO4NqWha7l6bWhIMJA8nEZkSmJk9Pq3UU1vIBkNoNKmzb2UYDruJbP4k5OJAZ9e/7bPtYSdcWcnIa2TJFrV0Qr/pP3q4xnzatL8iaj00IPKdhp1gBgdM3jbv8ClAdb/U4gRSrLFMLp1O3undV4IJyWsARvDAe58Z923w1rjLMinYqTV/7M3RUgckDwNpsozP7W6KNjCa/G6tQnTZuslTpR8FgzX11nMcOCUuSb9Ot1ypTDnFlvsac+DFMbe/sP5p9dn0l4KP2AtsnU5r3KV5Ed1PEtBDp67YMSfP+ahTjrWdizIU7bhH7Fc6munEePl0CrDdRWOXPfCiodUJ0RJoQO8W4DHRHOyrgBdHBIERwUWZaM2JCyRKMV0k1sODhi71xuP2ONRaPyYX/gvev8lJcwlXssxSZ409su5z65BEnDh6UTXVpcIJ4fonsHmx7TTFu1UG+J3KOYl2bExcQ5/bJPhM70fFk+q85mSnsA3+vOFKTKWc3+ZFfZw1naKjoB+F7GWHRj013Lx1q1/lxcdBOJ3KzN8ENMSQ0btLW0KVfK1MQImjj1ICdGZ6YtQT/w/levrAoigLOvX5eA4YijCAQ37QQ5DqqyMfKxvnQGhLhn0WBSKDTLlZXQZ5BormbNvokYbMDzjQnP3zkK5h6jonTgjqCzDiLidIuOFw==
  
</details>

**Comment by midnight-wonderer** [comment]
@zhanzhenzhen
I did not dig into it as deeply as you.

However, from the outsider perspective, I wonder why we need to supply intermediate certificates to OpenSSL at all?
I don't even know what these `cert_ids` are, but from my understanding:
* There are 2 certificates sent along with the timestamp response.
* One of them, with the serial number `30:0f:6f:ac:dd:66:98:74:7c:a9:46:36:a7:78:2d:b9`, specify `X509v3 Authority Key Identifier` as `keyid:53:79:BF:5A:AA:2B:4A:CF:54:80:E1:D8:9B:C0:9D:F2:B2:03:66:CB`, which happened to be `X509v3 Subject Key Identifier` of the root certificate, with serial number `01:fd:6d:30:fc:a3:ca:51:a8:1b:bc:64:0e:35:03:2d`.
* Therefore, all certificates presented in the response are perfectly chained to root already. We should be able to only supply the root certificate `01:fd:6d:30:fc:a3:ca:51:a8:1b:bc:64:0e:35:03:2d` and nothing else.

Could you enlighten me a little? (I am somewhat new to PKI related topics.)

**Comment by zhanzhenzhen** [comment]
@midnight-wonderer I think with `-cert` option the response contains one (but only one) intermediate certificates. Without `-cert` option the response contains no intermediate certificates. So you still have to provide 1 or 2 intermediate certificates when verifying the timestamp. You can find that if you miss some intermediate certificate, the error is different, not the error I mentioned above.

**Comment by zhanzhenzhen** [comment]
Sorry for misconception. The TSA signing cert isn't an intermediate cert. I changed the title and the comment.

**Comment by zhanzhenzhen** [comment]
@midnight-wonderer From your pull request, you mean there're 2 "signing certificates" when using Sectigo?

I just see one signing certificate `Sectigo RSA Time Stamping Signer #2`, with the intermediate certificate `Sectigo RSA Time Stamping CA` and root certificate `USERTrust RSA Certification Authority`. What's the other signing certificate?

Yesterday I also found that DigiCert's timestamp works well. They also have an intermediate certificate. So, is the issue *not* about whether there's an intermediate certificate?

Here's the DigiCert certs:
[digicert.zip](https://github.com/openssl/openssl/files/5996384/digicert.zip)

**Comment by zhanzhenzhen** [comment]
> I also wanted to add that there are 2 possible certificate paths.
>
> One already provided by the OP
> Another one chained to AAACertificateServices

@midnight-wonderer By the other signing certificate, do you mean that?

**Comment by zhanzhenzhen** [comment]
It seems that DigiCert's response has only one `id-smime-aa-signingCertificate`, which is the SHA-1 of the leaf cert:

```
 3030:d=8  hl=2 l=  11 prim: OBJECT            :id-smime-aa-signingCertificate
 3043:d=8  hl=2 l=  28 cons: SET               
 3045:d=9  hl=2 l=  26 cons: SEQUENCE          
 3047:d=10 hl=2 l=  24 cons: SEQUENCE          
 3049:d=11 hl=2 l=  22 cons: SEQUENCE          
 3051:d=12 hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3
```

While Sectigo's reponse has two, which are the SHA-1 of both the leaf and the intermediate:

```
  643:d=8  hl=2 l=  11 prim: OBJECT            :id-smime-aa-signingCertificate
  656:d=8  hl=3 l= 221 cons: SET               
  659:d=9  hl=3 l= 218 cons: SEQUENCE          
  662:d=10 hl=3 l= 215 cons: SEQUENCE          
  665:d=11 hl=2 l=  22 cons: SEQUENCE          
  667:d=12 hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:951137101D882F31BD513F949ADA4C68AD8C08F5
  689:d=11 hl=3 l= 188 cons: SEQUENCE          
  692:d=12 hl=2 l=  20 prim: OCTET STRING      [HEX DUMP]:02D65B95E28370C1570095FA88F923DD937FAD8F
```

Is this the reason?

**Comment by midnight-wonderer** [comment]
@zhanzhenzhen I just mentioned that the certificate with serial number `30:0f:6f:ac:dd:66:98:74:7c:a9:46:36:a7:78:2d:b9` can be chained to either the one with serial `39:72:44:3a:f9:22:b7:51:d7:d3:6c:10:dd:31:35:95` or `01:fd:6d:30:fc:a3:ca:51:a8:1b:bc:64:0e:35:03:2d` because both certificates contain the same public key.
It is somewhat unrelevant to the main topic, it just might affect the implementation details.

To keep you in the loop, it is because of the number of fingerprints inside `id-smime-aa-signingCertificate` as you mentioned.
[RFC 5035](https://tools.ietf.org/html/rfc5035) mentioned that:
>  If more than one certificate is present, subsequent certificates limit the set of certificates that are used during validation. Certificates can be either attribute certificates (limiting authorizations) or public key certificates (limiting path validation).  The issuerSerial field (in the ESSCertIDv2 structure) SHOULD be present for these certificates, unless the client who is validating the signature is expected to have easy access to all the certificates required for validation. If only the signing certificate is present in the sequence, there are no restrictions on the set of certificates used in validating the signature.

TSAs and OpenSSL seem to interpret `the set of certificates used in validating the signature` differently.
The details are inside the pull request #14214.

OpenSSL interpretation has more strict security and also more reasonable IMO.
A TSA can just send one fingerprint from the beginning; the only reason they send more fingerprints should be because they want to mention something beyond the certificates included with the response.

**Comment by zhanzhenzhen** [comment]
> There are 2 certificates sent along with the timestamp response.

@midnight-wonderer You're right. I've deleted the old reply. I also don't know why we need to use `-untrusted` option to specify a cert that's already in the response. Anyone know why? Or, is there an option that can eliminate the use of `-untrusted` option? It's not about this issue but I'm curious.

I just tested DigiCert. I dumped 1333 bytes starting from position 1470 in the timestamp response, according to what `asn1parse` shows, and then converted it to PEM. The generated file is exactly the same as my testing DigiCert intermediate cert.

**Comment by DDvO** [comment]
>  I also don't know why we need to use `-untrusted` option to specify a cert that's already in the response. Anyone know why? Or, is there an option that can eliminate the use of `-untrusted` option? It's not about this issue but I'm curious.

I also came across this issue when adding tests to `test/recipes/80-test_tsa.t`.
I'd say it's an omission, even a bug.
I' providing a fix for that in #14504.

**Comment by DDvO** [comment]
> Java validates the response just fine.

Which crypto library are you using there?
If it's BouncyCastle, here is the reason why: they simply ignore any further ESSCertIDs :frowning_face: 
https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/tsp/TimeStampToken.java#L186

**Comment by DDvO** [comment]
A further issue with the OpenSSL implementation is that it silently prefers any given `ESSCertID` 
over any given `ESSCertIDv2`, while both may be present and [RFC 5035 says](https://tools.ietf.org/html/rfc5035#section-5.4.1):
> Applications SHOULD recognize both attributes as long as
   they consider SHA-1 able to distinguish between two different
   certificates, (i.e., the possibility of a collision is sufficiently
   low).  If both attributes exist in a single message, they are
   independently evaluated.

**Comment by midnight-wonderer** [comment]
@DDvO 
Confirmed to be BouncyCastle.

Nice catch on
> If both attributes exist in a single message, they are independently evaluated.

but in RFC 2634, they also said that: 
> A SignerInfo MUST NOT include multiple instances of the SigningCertificate attribute.

; not sure if that also extends to v2.

However, it is not like physically impossible for ASN1 to contain both despite what the spec says.
So, probably those branches need rework a little bit.

**Comment by DDvO** [comment]
> A SignerInfo MUST NOT include multiple instances of the SigningCertificate attribute.

This only means that there must not be multiple SigningCertificate v1 attribute
(and the same holds for SigningCertificate v2 attributes).

> it is not like physically impossible for ASN1 to contain both despite what the spec says.

it is definitely possible, and RFC 5035 explicitly mentions this as references above.
It also says in section 7:
>    To ensure that legacy implementations are provided protection against
   certificate substitution, clients are permitted to include both
   ESScertID and ESScertIDv2 in the same message.  Since these
   attributes are generated and evaluated independently, the contents
   could conceivably be in conflict.  Specifically, where a signer has
   multiple certificates containing the same public key, the two
   attributes could specify different signing certificates.  The result
   of signature processing may vary depending on which certificate is
   used to validate the signature.
   Recipients that attempt to evaluate both attributes may choose to
   reject such a message.
