### ISSUE TITLE
openssl enc with passcode doesn't decode on linux/windows if created on mac m1

### ISSUE THREAD

**Issue by verbunk** [openssl/openssl#14203]
Creating encrypted files on Mac with M1 chip and attempting to decode on Linux/Windows yields error 'bad decrypt'.

**Comment by beldmit** [comment]
Could you please provide more details? The command line you use in both cases, for example

**Comment by kaduk** [comment]
Also whether the password includes any Unicode codepoints/characters that are encoded differently under different normalization forms.

**Comment by verbunk** [comment]
- No unicode, just hex key (generated with openssl actually).
- command to encypt/decrypt is,
openssl enc -aes-256-cbc -in input.enc -out output.txt
openssl enc -aes-256-cbc -d -in input.enc -out output.txt

**Comment by t8m** [comment]
What are the versions of the openssl on the Mac, Linux, Windows?

**Comment by t8m** [comment]
No response from the reporter. Closing.
