### ISSUE TITLE
The use of PTHREAD_MUTEX_ERRORCHECK doesn't work

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14229]
In threads_pthread.c we have this code:

https://github.com/openssl/openssl/blob/ba37b82045b1b2fbcbf7580b317de5e3b52c8035/crypto/threads_pthread.c#L58-L62

Unfortunately, at least on Linux, the `PTHREAD_MUTEX_ERRORCHECK` value is defined as an enum not a macro. Therefore the test for its presence never succeeds.

Additionally the check for `NDEBUG` at this same location is incorrect. `NDEBUG` is *not* defined in debug builds so this should be `!defined(NDEBUG)`

Finally it is never possible to get to this point in the code in modern Linux because it supports rwlocks. There doesn't seem to be a way to tell the build that we don't want to use rwlocks. This would be useful so that we can force a build which uses `PTHREAD_MUTEX_ERRORCHECK` to help debug threading issues.

**Comment by richsalz** [comment]
I can fix the NDEBUG (man, I always get those double-negatives wrong).  I wonder if adding `-DPTHREAD_MUTEX_ERRORCHECK=PTHREAD_MUTEX_ERROR_CHECK` as a hack would work?  That's kinda gross.  Adding "-DERROR_CHECK_MUTEX" and that adding it to the ifdef would be less of a hack.  Thoughts?

**Comment by mattcaswell** [comment]
Do we actually need to test for the presence of `PTHREAD_MUTEX_ERRORCHECK` at all? It seems to go way back in the pthreads spec...at least I see mention of it here in the unix spec from 1997:

https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_mutexattr_settype.html

Adding a "-DOSSL_ERROR_CHECK_MUTEX" to *force* the usage of that would be a nice addition.

**Comment by kaduk** [comment]
(I expect that once this is fixed many systems are going to start stumbling over #14171 )

**Comment by paulidale** [comment]
What does `PTHREAD_MUTEX_ERRORCHECK` buy us that the thread sanitizer doesn't?

**Comment by mattcaswell** [comment]
> What does PTHREAD_MUTEX_ERRORCHECK buy us that the thread sanitizer doesn't?

It's much lighter weight compared to thread sanitizer so we can afford to have it on by default in debug builds. We're much more likely to discover problems this way. In particular it was put in place to detect recursive locks. I found it helpful when investigating #14225.
