### ISSUE TITLE
EVP: How to set modulus for DH paramgen

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#14227]
Is it possible to set the modulus (for legacy reasons) for DH during paramgen. The generator can be set using:
EVP_PKEY_CTX_set_dh_paramgen_generator
But I couldn't figure out a way to set a "custom" modulus/group.

**Comment by mattcaswell** [comment]
Are you using OpenSSL 1.1.1 or 3.0? The answer differs depending on the version.

In 3.0 you should use `EVP_PKEY_fromdata`:

https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_fromdata.html

Also see:
https://www.openssl.org/docs/manmaster/man7/EVP_PKEY-FFC.html
https://www.openssl.org/docs/manmaster/man7/EVP_PKEY-DH.html

In 1.1.1 `EVP_PKEY_fromdata` does not exist. In that version you probably have to create a low level DH object and "assign" it to an EVP_PKEY via `EVP_PKEY_set1_DH`:

https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_set1_DH.html

**Comment by matbech** [comment]
Thank you. I'm trying to port some legacy code from OpenSSL 1.x to 3.0.

What I did try is something like this:
```
	std::unique_ptr<::EVP_PKEY_CTX, ::OpenSSL::Deleter> ctx_params{ ::EVP_PKEY_CTX_new_from_name(nullptr, "DH", nullptr) };
	OPENSSL_ENSURE_TRUE(ctx_params != nullptr);
	OPENSSL_ENSURE_TRUE(::EVP_PKEY_paramgen_init(ctx_params.get()) > 0);

	size_t keyLength{ _KeyLength };
	OSSL_PARAM params[]{
		OSSL_PARAM_size_t(OSSL_PKEY_PARAM_FFC_PBITS, &keyLength)
		, OSSL_PARAM_BN(OSSL_PKEY_PARAM_FFC_P, _Modulus.data(), _Modulus.size())
		, OSSL_PARAM_BN(OSSL_PKEY_PARAM_FFC_G, _Generator.data(), _Generator.size())
		, OSSL_PARAM_END };
	OPENSSL_ENSURE_TRUE(::EVP_PKEY_CTX_set_params(ctx_params.get(), params));
	
	::EVP_PKEY* pkey_params{ nullptr };
	OPENSSL_ENSURE_TRUE(::EVP_PKEY_gen(ctx_params.get(), &pkey_params) > 0);
``
Where the generator is either 0x5, or 0x2 and the keyLength is 3192 and the modulus is 399 bytes (3192 bits).

It takes 10 minutes? (also in the release build) to generate a key, so I must be doing something wrong.

**Comment by t8m** [comment]
The DH parameter generation needs to generate safe prime for P, that takes a very long time. However if I try to generate parameters with `openssl  genpkey -genparam -algorithm DH -pkeyopt dh_paramgen_prime_len:2064` by looking at the dots output the search for the safe prime is apparently much slower than in case of `openssl  genpkey -genparam -algorithm DH -pkeyopt dh_paramgen_prime_len:2048` than it would be warranted by the difference in the prime size. @kroeckx might have some idea why?

**Comment by t8m** [comment]
I tried even generating 2046, 2048, 2050, 2052 bit long primes and there is sudden jump in the speed of printing the dots between 2048 and 2050. The speed is roughly halved.

**Comment by kroeckx** [comment]
The prime check changes from 64 rounds of Miller-Rabin to 128 when
the size of the prime is larger than 2048. It probably tries 128
rounds on p, to then directly fail on q. Maybe we should have
something for safe primes that switches between checking p and q?

**Comment by t8m** [comment]
No, the MR rounds do not even come into play at this point - try it yourself and/or look at the code. The slowness happens either when generating the probable prime candidate or a single MR round.

**Comment by t8m** [comment]
Is here anything remaining to be resolved?

**Comment by matbech** [comment]
I have this with the latest commit and the performance regression is still present. Running
```
openssl genpkey -genparam -algorithm DH -pkeyopt dh_paramgen_prime_len:2048
```
takes minutes (instead of seconds).

**Comment by kroeckx** [comment]
There are 2 differences in 3.0 compared to 1.1.1. The first is the
number of trial divisions. This should be lower in 3.0 compared to
1.1.1. This will result in the "."'s on the screen being faster,
but it's probably hard to notice the difference.

The other difference is the number of MR-rounds at the end of the test,
which is the number of "++*" at the end of the tests. There are 64 or
128 rounds in 3.0, and most likely 4 or 5 rounds in 1.1.1. The number
of rounds depends on the size of the prime. More MR-rounds will
make it slower, but this is normally a very small part of the
total time.

Finding a safe prime is slow and unpredictable. It doesn't always
take the same amount of time. Sometimes it takes less than a second,
sometimes it takes minutes. The speed in 1.1.1 and 3.0 should be
about the same.

You probably should not be generating your own DH parameters, but
use a named group, for example one from rfc7919.

**Comment by t8m** [comment]
So apparently you do not want to generate _domain parameters_ but a private key with known _domain parameters_. Then you need to create a parameters pkey with EVP_PKEY_fromdata() and then use it with a keygen to generate a key. How to do that can be seen in the example in the EVP_PKEY_gen manpage.

**Comment by matbech** [comment]
Thank you. It is working as expected. I apologize for the noise.
