### ISSUE TITLE
void return values are often not good

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#14239]
It's probably a mistake to have many "void" functions. I found out by  doing #14238 that sometimes an internal function does things like "ask for a lock" in a "void xxxx_free" function, and there's no way to indicate that something went wrong.

**Comment by paulidale** [comment]
Agreed completely.

Although exactly how an `xxx_free` function can be recovered after failure is another story.  I can't remember any code checking the return from `close(2)` :smiley:

**Comment by t-j-h** [comment]
"void" is really never appropriate as over time even what might once have been a trivial no-error-path-possible function evolves into something more complicated - I certainly don't ever recollect anyone saying "I wish I'd made that function have a void return" but the other is pretty common to hear.

**Comment by t8m** [comment]
I'd really prefer to keep at least the _free functions void. Checking error returns on _free() calls would make the code truly insane.

**Comment by richsalz** [comment]
>  I can't remember any code checking the return from close(2) 

You never used the Andrew File System :)  Yeah, all you could do is log as a warning that not all data might be there.

FWIW, I agree that free functions should remain void, but that's just my opinion and the project will have to decide.

**Comment by t8m** [comment]
> FWIW, I agree that free functions should remain void, but that's just my opinion and the project will have to decide.

Well I do not think we need explicit decision for that. Anybody from OTC who would like to try to make the rest of the team insane can raise a vote to change the status quo and see if it passes. :rofl:

**Comment by mattcaswell** [comment]
If there was ever a demonstration of the problems with void functions its #14250. I changed a single void function to return int and it had a massive ripple effect affecting very many public API function signatures.

**Comment by nhorman** [comment]
so, it seems like the ask here is that we  change some enumeration of internal functions to not return void, but there is hesitation as to the potential fallout effort from doing so.  Given this has been here for 3 years without action, I get the impression that we don't intend to make this change.

Feel like this should be closed as not planned.  @mattcaswell @t8m ?

**Comment by paulidale** [comment]
I agree, closing.
