### ISSUE TITLE
CRYPTO_THREAD_read_lock() and CRYPTO_THREAD_write_lock() can fail

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14230]
It is possible for `CRYPTO_THREAD_read_lock()` and  `CRYPTO_THREAD_write_lock()` to fail. For example if `PTHREAD_MUTEX_ERRORCHECK` is in use and we hit a deadlock then they will fail. Unfortunately while we do check for failure in some locations there are many locations where we do not. This means we carry on regardless assuming we have successfully obtained the lock even though we haven't. (See also issue #14229)

**Comment by paulidale** [comment]
The return value from these looks to be ignored more often than not 😞

**Comment by mattcaswell** [comment]
In theory the unlock function could fail as well.

**Comment by richsalz** [comment]
> In theory the unlock function could fail as well.

I would rather see this as a separate issue.  If you can't lock, you can at least fail the operation and report back. If you can't unlock, what should you do?  (And a future lock will fail anyway)
