### ISSUE TITLE
Using TLS 1.3 methods

### ISSUE THREAD

**Issue by Patrick5088** [openssl/openssl#14245]
I'm using OpenSSL and Winsock and I want to use the TLS 1.3 protocol because I heard that TLS 1.3 will not renegotiate during communication between server and client. So my question is how to invoke SSL_CTX_new for TLS 1.3?

**Comment by mattcaswell** [comment]
Just use:

````
SSL_CTX *ctx = SSL_CTX_new(TLS_server_method());
````
or
````
SSL_CTX *ctx = SSL_CTX_new(TLS_client_method());
````
as appropriate. This will enable the highest protocol version supported by both client and server to be negotiated.

Optionally you can enforce a lower bound on the protocol version that will be negotiated. For example to fail the handshake if a TLSv1.2 only peer connects then you can use:
````
SSL_CTX_set_min_proto_version(ctx, TLS1_3_VERSION);
````

**Comment by Patrick5088** [comment]
Do you have any idea why OpenSSL ,in the context of Windows Sockets, triggers FD_READ events with 0 bytes ready to be read?

**Comment by Patrick5088** [comment]
Thanks
