### ISSUE TITLE
How do I free the memory of the OBJ_create application.

### ISSUE THREAD

**Issue by wngg-no-gg** [openssl/openssl#14242]
OBJ_create() adds a new object to the internal table.
When I tested, I call OBJ_create() repeatedly, and the heap was increasing.

This is the official OpenSSL documentation :
"In OpenSSL versions prior to 1.1.0 OBJ_cleanup() cleaned up OpenSSLs internal object table and was called before an application exits if any new objects were added using OBJ_create(). This function is deprecated in version 1.1.0 and now does nothing if called. No explicit de-initialisation is now required."

**Comment by paulidale** [comment]
Exit?  The object's lifetime is the until OpenSSL is closed.  The clean up is automatic now.
