### ISSUE TITLE
ossl_provider_forall_loaded should not hold a lock while calling the user callback

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14251]
A user callback could do almost anything, so a deadlock is a very likely outcome.

This is very similar to the issue encountered in #14225 and fixed by #14250

**Comment by paulidale** [comment]
There have been other cases of this exact problem.  Perhaps we should review all of the _for all_ and _do all_ type calls.

**Comment by t8m** [comment]
> There have been other cases of this exact problem. Perhaps we should review all of the _for all_ and _do all_ type calls.

Please open a new issue.

**Comment by paulidale** [comment]
Issue #14285 deals with checking the rest of the _forall_ loops.
