### ISSUE TITLE
Trouble with OpenSSL

### ISSUE THREAD

**Issue by Lifeda92** [openssl/openssl#14272]
I have trouble with building sha256 example code. Help me. Thanks.

Error C4996 'SHA256_Final': Since OpenSSL 3.0
Error C4996 'SHA256_Init': Since OpenSSL 3.0
Error C4996 'SHA256_Update': Since OpenSSL 3.0

![2](https://user-images.githubusercontent.com/27778666/108677482-6d531080-74f2-11eb-9898-1c2c1d2a45f2.png)
![1](https://user-images.githubusercontent.com/27778666/108677484-6deba700-74f2-11eb-83ce-789008faeb6e.png)

```
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>

using namespace std;

#include <openssl/sha.h>

string sha256(const string str)
{
    unsigned char hash[SHA256_DIGEST_LENGTH];
    SHA256_CTX sha256;
    SHA256_Init(&sha256);
    SHA256_Update(&sha256, str.c_str(), str.size());
    SHA256_Final(hash, &sha256);
    stringstream ss;
    for (int i = 0; i < SHA256_DIGEST_LENGTH; i++)
    {
        ss << hex << setw(2) << setfill('0') << (int)hash[i];
    }
    return ss.str();
}

int main() {
    cout << sha256("1234567890_1") << endl;
    cout << sha256("1234567890_2") << endl;
    cout << sha256("1234567890_3") << endl;
    cout << sha256("1234567890_4") << endl;
    return 0;
}
```

**Comment by paulidale** [comment]
Did you build OpenSSL with the `no-deprecated` option?
Are you erroring when the warning about deprecated functions is produced?

**Comment by Lifeda92** [comment]
> Did you build OpenSSL with the `no-deprecated` option?

I think no.
I built from this video: https://www.youtube.com/watch?v=PMHEoBkxYaQ

```
nmake clean
perl Configure VC-WIN32 --debug --prefix=C:\openssl\DLL\x32\Debug --openssldir=C:\openssl\SSL
nmake test
nmake install_sw

nmake clean
perl Configure VC-WIN32 --prefix=C:\openssl\DLL\x32\Release --openssldir=C:\openssl\SSL
nmake test
nmake install_sw

nmake clean
perl Configure VC-WIN32 --debug --prefix=C:\openssl\Lib\x32\Debug --openssldir=C:\openssl\SSL no-shared
nmake test
nmake install_sw

nmake clean
perl Configure VC-WIN32 --prefix=C:\openssl\Lib\x32\Release --openssldir=C:\openssl\SSL no-shared
nmake test
nmake install_sw
```

> Are you erroring when the warning about deprecated functions is produced?

I should define something? Pls, tell me what.

**Comment by Lifeda92** [comment]
I will try build with "no-deprecated" option. I will write here result

**Comment by paulidale** [comment]
The compile will fail with the `no-deprecated` option.  The functions disappear with this option.

The functions you are using are very low level and are not the preferred way of accessing the SHA256 algorithm.  The `EVP_MD_` interfaces are the modern calls. Have a look at the example in the [documentation](https://www.openssl.org/docs/manmaster/man3/EVP_DigestInit.html).

**Comment by Lifeda92** [comment]
More errors. Dont work. Unpossible to use. Will find another way just make sha256. Thanks
![3](https://user-images.githubusercontent.com/27778666/108684686-e145e680-74fb-11eb-87ee-4be1ef84c1a6.png)

**Comment by levitte** [comment]
[C4996 is a deprecation warning](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-160)

Have you enabled "Treat warnings as errors" in Visual Studio?  That is the probable reason why you have problems.

**Comment by Lifeda92** [comment]
> Treat warnings as errors

NICE. Working. THANK YOU!!!!

**Comment by levitte** [comment]
It looks like you're happy with the answer, so I'm closing this issue

**Comment by mattcaswell** [comment]
Note that the reason that you are suddenly getting these warnings is that the old SHA256* APIs are deprecated. While not treating warnings as errors will get things working for you in the short term, the long term solution is to rewrite your code to use the "EVP" APIs as per @paulidale's [comment](https://github.com/openssl/openssl/issues/14272#issuecomment-783189096) above.

The old SHA256 APIs will eventually be removed from some future version of OpenSSL.

**Comment by spider1-dev** [comment]
> Did you build OpenSSL with the `no-deprecated` option? Are you erroring when the warning about deprecated functions is produced?

How do we do that?


> Note that the reason that you are suddenly getting these warnings is that the old SHA256* APIs are deprecated. While not treating warnings as errors will get things working for you in the short term, the long term solution is to rewrite your code to use the "EVP" APIs as per @paulidale's [comment](https://github.com/openssl/openssl/issues/14272#issuecomment-783189096) above.
> 
> The old SHA256 APIs will eventually be removed from some future version of OpenSSL.

Where will we access the code for the new OpenSSL versions?
