### ISSUE TITLE
Resolve PKCS#7/CMS related backend hack

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#14276]
In OpenSSL pre-3.0, the ctrl commands EVP_PKEY_CTRL_PKCS7_ENCRYPT, EVP_PKEY_CTRL_PKCS7_DECRYPT, EVP_PKEY_CTRL_CMS_DECRYPT and EVP_PKEY_CTRL_CMS_ENCRYPT were used for PKCS#7 and CMS related things to take extra necessary steps to set X509_ALGORs, verify that the key type is correct, that sort of thing.  This necessity disappeared in 0574cadf857b19485465b9d71b7dec9549857a4d, apart from verifying that the RSA key to encrypt with wasn't an RSA-PSS key.

In 3.0 and provider backed methods, we have copied that into the legacy-to-params translators, with a comment that something more might be needed.  Alternatively, maybe we don't need the ctrl commands at all with provider backed methods, since what can be done is determined by the methods themselves anyway.

https://github.com/openssl/openssl/blob/7f90026b3fca9cfd3d9098d358d949d37509a2e5/crypto/evp/pmeth_lib.c#L1417-L1429

**Comment by t8m** [comment]
There are also 2 related TODO 3.0 in crypto/pkcs7/pk7_doit.c which should be resolved together with the above hack:
```
    /*
     * TODO(3.0): This causes problems when providers are in use, so disabled
     * for now. Can we get rid of this completely? AFAICT this ctrl has never
     * been used since it was first put in. All internal implementations just
     * return 1 and ignore this ctrl and have always done so by the looks of
     * things. To fix this we could convert this ctrl into a param, which would
     * require us to send all the signer info data as a set of params...but that
     * is non-trivial and since this isn't used by anything it may be better
     * just to remove it. The original commit that added it had this
     * justification in CHANGES:
     *  
     * "During PKCS7 signing pass the PKCS7 SignerInfo structure to the
     *  EVP_PKEY_METHOD before and after signing via the
     *  EVP_PKEY_CTRL_PKCS7_SIGN ctrl. It can then customise the structure
     *  before and/or after signing if necessary."
     */
#if 0
    if (EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_SIGN,
                          EVP_PKEY_CTRL_PKCS7_SIGN, 0, si) <= 0) {
        ERR_raise(ERR_LIB_PKCS7, PKCS7_R_CTRL_ERROR);
        goto err;
    }            
#endif
```

**Comment by levitte** [comment]
Do note that the TODO in pk7_doit.c is *not* the same thing as the thing this issue is about.
EVP_PKEY_CTRL_PKCS7_ENCRYPT ≠ EVP_PKEY_CTRL_PKCS7_SIGN.

They are similar in so far that they are PKCS7 / CMS hacks, but their uses are quite different.

When it comes to `EVP_PKEY_CTRL_PKCS7_ENCRYPT`, `EVP_PKEY_CTRL_PKCS7_DECRYPT`, `EVP_PKEY_CTRL_CMS_DECRYPT` and `EVP_PKEY_CTRL_CMS_ENCRYPT`, they seem to be used for exactly one purpose, to confirm that encryption / decryption can indeed be done with the keytype in question.  In provider terms, that would be trying to call `EVP_SealInit()` or EVP_OpenInit()` and see if that raised an error or not (to be crass, that's probably how things should have been done from the very start).

**Comment by levitte** [comment]
Oh pardon me, `EVP_PKEY_CTRL_PKCS7_SIGN` seems to have a similar purpose, but for signing/verifying.

**Comment by t8m** [comment]
And the TODO 3.0 is in cms_sd.c as well of course:
```
    /*
     * TODO(3.0): This causes problems when providers are in use, so disabled
     * for now. Can we get rid of this completely? AFAICT this ctrl has been
     * present since CMS was first put in - but has never been used to do
     * anything. All internal implementations just return 1 and ignore this ctrl
     * and have always done so by the looks of things. To fix this we could
     * convert this ctrl into a param, which would require us to send all the
     * signer info data as a set of params...but that is non-trivial and since
     * this isn't used by anything it may be better just to remove it.
     */
#if 0
    if (EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_SIGN,
                          EVP_PKEY_CTRL_CMS_SIGN, 0, si) <= 0) {
        ERR_raise(ERR_LIB_CMS, CMS_R_CTRL_ERROR);
        goto err;
    }
#endif
```
