### ISSUE TITLE
Change provctx fields in EVP_xxx_CTX structures to data.

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14284]
Most `EVP_xxx_CTX` structures keep the provider side context pointer in a field called `data`.  The rest (EVP_MD_CTX, EVP_CIPHER_CTX, ...) use the name `provctx` which is confusing.

This was first raised [here](https://github.com/openssl/openssl/pull/14240#discussion_r578879244).  Again in more details [here](https://github.com/openssl/openssl/pull/14240#discussion_r580695418).

**Comment by t8m** [comment]
Is this really a bug or a refactoring i.e., something that has to be in before beta?

**Comment by paulidale** [comment]
It's not a bug.  I don't think this needs to be in for beta.
Changing the field names in opaque structures is a fairly trivial refactoring which can take place anytime IMO.

**Comment by t8m** [comment]
The question is whether refactoring albeit trivial one can be allowed after beta release. I do not have problem with that but opinions of some of the OTC members may differ. :grin:

**Comment by levitte** [comment]
It doesn't really restructure anything, it's just an internal rename.  I think it's a stretch to call it "refactoring"
