### ISSUE TITLE
Getting NULL when using -apr1 to hash a password, but only in one particular environment...

### ISSUE THREAD

**Issue by a-roberts** [openssl/openssl#14289]
Hey folks, I'm using this build of openssl:

```
bash-4.4$ openssl version -a
OpenSSL 1.1.1g FIPS  21 Apr 2020
built on: Fri Dec  4 14:43:52 2020 UTC
platform: linux-x86_64
options:  bn(64,64) md2(char) rc4(8x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific
engines:  rdrand dynamic 
```

and I've got the following happening, every time, on a user's node I'm debugging. For context this is running in OCP 4.6.16 and our environments do match entirely at face value (so in terms of OS version, memory amounts available, that kinda thing; the exact same Kubernetes node template essentially).

```
bash-4.4$ openssl passwd -apr1 0MX1xvEX8xdYbn8FZ1eiyIH6
<NULL>
```

when I do that on my own personal OCP 4.6.16 node, or my Mac, I get the hash back, every time, so it works great. Again my OpenSSL version matches.

I've tried (mainly out of desperation) adding a salt, reading from a file, but it is always, always, always! null on this particular set up.

Here's the OpenSSL config in use, for us both:

```
@SECLEVEL=2:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
```

is there anything else I should be checking please?

I have the exact environment available to me and so willing to check anything and everything. 

I've also explored with different password inputs as well (always null) and I know that if I were to use -5, I do always get a working hash. 

Maybe that's justification enough to stop using md5 (as well as any other problems using that comes with!) but I'm really, very curious how this could happen, especially from a support perspective - always helpful to know the root cause before suggesting actions.

Thanks in advance!

**Comment by levitte** [comment]
If `-apr1` doesn't work, it's likely that MD5 has been disabled.  If you do `perl configdata.pm --dump` in your build directory, there's a list of enabled / disabled features...

**Comment by a-roberts** [comment]
> perl configdata.pm --dump

Thanks - good suggestion, so we're using OpenSSL in a Docker container and its source is obtained/built as follows

```
# openssl requires perl
RUN curl -L -O http://www.openssl.org/source/openssl-1.1.1g.tar.gz \ 
    && tar -zxf openssl-1.1.1g.tar.gz \
    && cd openssl-1.1.1g \
    && ./config \
    && make \
    && make install
```

From the command you suggested when I do that on my Mac:

```
(base) Adams-MBP:openssl-1.1.1g aroberts$ perl configdata.pm --dump

Command line (with current working directory = .):

    /usr/bin/perl ./Configure darwin64-x86_64-cc

Perl information:

    /usr/bin/perl
    5.18.4 for darwin-thread-multi-2level

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl
```

Should I be expecting more or less? Note, that isn't the same machine used for our builds, just me seeing what the output would look like so far. I'll take a look at what each of those enabled features does in the meantime.

I do have another question as well though - if I said the build configuration is exactly the same (so the image that's used is the same for OpenSSL, would something on the actual VM side be causing MD5 to be disabled and is there something there I could take a look at? Thanks again

**Comment by levitte** [comment]
I'm sorry, it seems I've led you off on a goose chase...  there is no sane way to disable MD5 in OpenSSL 1.1.1.

The error is somewhere else.  Unfortunately, it seems like the passwd app doesn't print OpenSSL errors (for reasons I cannot fathom).  Applying this patch will have the passwd app say a little more about what's going wrong.

``` diff
diff --git a/apps/passwd.c b/apps/passwd.c
index d741d05335..2700311815 100644
--- a/apps/passwd.c
+++ b/apps/passwd.c
@@ -290,9 +290,7 @@ int passwd_main(int argc, char **argv)
     ret = 0;
 
  end:
-#if 0
     ERR_print_errors(bio_err);
-#endif
     OPENSSL_free(salt_malloc);
     OPENSSL_free(passwd_malloc);
     BIO_free(in);
```

**Comment by levitte** [comment]
> ... it seems like the passwd app doesn't print OpenSSL errors (for reasons I cannot fathom)

It turns out that it was me disabling the printout of errors (0f3ffbd1581fad58095fedcc32b0da42a486b8b7).  I cannot for the life of me remember why...

**Comment by a-roberts** [comment]
> I'm sorry, it seems I've led you off on a goose chase... there is no sane way to disable MD5 in OpenSSL 1.1.1.
> 
> The error is somewhere else. Unfortunately, it seems like the passwd app doesn't print OpenSSL errors (for reasons I cannot fathom). Applying this patch will have the passwd app say a little more about what's going wrong.
> 
> ```diff
> diff --git a/apps/passwd.c b/apps/passwd.c
> index d741d05335..2700311815 100644
> --- a/apps/passwd.c
> +++ b/apps/passwd.c
> @@ -290,9 +290,7 @@ int passwd_main(int argc, char **argv)
>      ret = 0;
>  
>   end:
> -#if 0
>      ERR_print_errors(bio_err);
> -#endif
>      OPENSSL_free(salt_malloc);
>      OPENSSL_free(passwd_malloc);
>      BIO_free(in);
> ```

No problem, at least I learned a few things along the way!

So what else would give me NULL? If I've understood your above comments correctly, I'm already getting all the possible errors? Or should I go ahead and apply the above, get a custom build, have it used by my Docker image and try to get it failing again? I think that would be difficult but I still have access to the system where it happens!

**Comment by levitte** [comment]
> So what else would give me NULL?

Frankly, I do not know.  I haven't been able to reproduce your problem.

> If I've understood your above comments correctly, I'm already getting all the possible errors?

Not necessarily.  The diff I posted, when applied, may give you more details.

> Or should I go ahead and apply the above, get a custom build, have it used by my Docker image and try to get it failing again? I think that would be difficult but I still have access to the system where it happens!

That's the possibility I see.

**Comment by a-roberts** [comment]
> > So what else would give me NULL?
> 
> Frankly, I do not know. I haven't been able to reproduce your problem.
> 
> > If I've understood your above comments correctly, I'm already getting all the possible errors?
> 
> Not necessarily. The diff I posted, when applied, may give you more details.
> 
> > Or should I go ahead and apply the above, get a custom build, have it used by my Docker image and try to get it failing again? I think that would be difficult but I still have access to the system where it happens!
> 
> That's the possibility I see.

It shall be done, building now with your suggested patch, thanks

**Comment by a-roberts** [comment]
Unfortunately I get nothing else - so I did this inside of our build process which removes those lines in question (accommodating for the fact the sed to remove the line removes the line-break too, thus what you mention is line 295 becomes 294, so I am removing `#if 0` and `#endif` surrounding ` ERR_print_errors(bio_err);`).

```
RUN curl -L -O http://www.openssl.org/source/openssl-1.1.1g.tar.gz \ 
    && tar -zxf openssl-1.1.1g.tar.gz \
    && cd openssl-1.1.1g \
    && sed -i '293d' apps/passwd.c \
    && sed -i '294d' apps/passwd.c \
    && ./config \
    && make \
    && make install
```

And I created a custom Kubernetes pod spec to run it.

```
[eventprocessing@adam-test /]$ openssl passwd -apr1 foo
<NULL>
```

I do think my Dockerfile looks good so it should have your suggestion in. Note that in the meantime I have advocated to switching to use sha256 anyway, so this is really just a case of trying to figure out what might be causing it for sure. Thanks

**Comment by paisleyrob** [comment]
This exact behavior got me today in a continuous integration environment. I was testing with `alpine:3.18.4` and it worked properly:

```console
/w # apk add openssl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/3) Upgrading libcrypto3 (3.1.3-r0 -> 3.1.4-r1)
(2/3) Upgrading libssl3 (3.1.3-r0 -> 3.1.4-r1)
(3/3) Installing openssl (3.1.4-r1)
Executing busybox-1.36.1-r2.trigger
OK: 8 MiB in 16 packages
/w # openssl version -a
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)
built on: Sat Nov 11 00:00:50 2023 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Os -Wformat -Werror=format-security -g -Os -Wformat -Werror=format-security -Os -Wformat -Werror=format-security -g -Wa,--noexecstack -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Os -Wformat -Werror=format-security
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib/engines-3"
MODULESDIR: "/usr/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ffaf3bfffebffff:0x18c05fdef3bfa7eb
/w # openssl passwd -apr1 foo
$apr1$8HziGBmx$ZnYeM88dhAVOOrBBjqXxx1
```

I then ran the same command from my RHEL 8 host and I get `NULL` as follows. The behavior is the same from the `redhat/ubi8:latest` image.

```console
$ openssl version -a
OpenSSL 1.1.1k  FIPS 25 Mar 2021
built on: Wed Feb  8 16:12:48 2023 UTC
platform: linux-x86_64
options:  bn(64,64) md2(char) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific
engines:  rdrand dynamic
$ openssl passwd -apr1 foo
<NULL>
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.9 (Ootpa)
```

Perhaps FIPS is to blame?

**Comment by t8m** [comment]
1.1.1k is RedHat patched version and yeah, most probably FIPS is to blame. You'll have to ask Red Hat about this.
