### ISSUE TITLE
Deprecate EVP_PKEY_CTX_ctrl and related functions

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14287]
Those functions purpose is to serve the legacy implementations and with #13913 they are completely replaceable with get/set params functions.

We need to deprecate them to be able to remove them when the legacy support code is removed.

It would be interesting to deprecate also the EVP_MD_CTX_ctrl and EVP_CIPHER_CTX_ctrl functions but we need to ensure that there are replacements that handle the legacy support correctly.

**Comment by t8m** [comment]
This also means the following TODOs about deprecating API functions that are tied to the EVP_PKEY_CTX_ctrl will be resolved as those functions should be also deprecated along with EVP_PKEY_CTX_ctrl().

```
/*
 * This one is currently implemented as an EVP_PKEY_CTX_ctrl() wrapper,
 * simply because that's easier.
 * TODO(3.0) Should this be deprecated?
 */
int EVP_PKEY_CTX_set_rsa_padding(EVP_PKEY_CTX *ctx, int pad_mode)
```
and
```
int EVP_PKEY_CTX_get_rsa_padding(EVP_PKEY_CTX *ctx, int *pad_mode)
```
and
```
int EVP_PKEY_CTX_set_rsa_pss_keygen_md(EVP_PKEY_CTX *ctx, const EVP_MD *md)
```
and
```
int EVP_PKEY_CTX_set_rsa_oaep_md(EVP_PKEY_CTX *ctx, const EVP_MD *md)
```
and
```
int EVP_PKEY_CTX_get_rsa_oaep_md(EVP_PKEY_CTX *ctx, const EVP_MD **md)
```
and
```
int EVP_PKEY_CTX_set_rsa_mgf1_md(EVP_PKEY_CTX *ctx, const EVP_MD *md)
```
and
```
int EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md(EVP_PKEY_CTX *ctx, const EVP_MD *md)
```
and
```
int EVP_PKEY_CTX_get_rsa_mgf1_md(EVP_PKEY_CTX *ctx, const EVP_MD **md)
```
and
```
int EVP_PKEY_CTX_set_dh_nid(EVP_PKEY_CTX *ctx, int nid)
```
and
```
int EVP_PKEY_CTX_set_dh_kdf_type(EVP_PKEY_CTX *ctx, int kdf)
```
and
```
int EVP_PKEY_CTX_get_dh_kdf_type(EVP_PKEY_CTX *ctx)
```
and
```
int EVP_PKEY_CTX_set_dh_kdf_md(EVP_PKEY_CTX *ctx, const EVP_MD *md)
```
and
```
int EVP_PKEY_CTX_get_dh_kdf_md(EVP_PKEY_CTX *ctx, const EVP_MD **pmd)
```
and
```
int EVP_PKEY_CTX_set_dsa_paramgen_md(EVP_PKEY_CTX *ctx, const EVP_MD *md)
```
and
```
int EVP_PKEY_CTX_set_ecdh_kdf_md(EVP_PKEY_CTX *ctx, const EVP_MD *md)
```
and
```
int EVP_PKEY_CTX_get_ecdh_kdf_md(EVP_PKEY_CTX *ctx, const EVP_MD **pmd)
```
and
```
int EVP_PKEY_CTX_set_ec_paramgen_curve_nid(EVP_PKEY_CTX *ctx, int nid)
```

**Comment by mattcaswell** [comment]
OTC: Not for 3.0

**Comment by nhorman** [comment]
It seems like this is a must do in a near term minor release if we are to remove them (ostensibly in 4.0)

**Comment by t8m** [comment]
I am afraid it is too late to deprecate and remove them in 4.0.

**Comment by paulidale** [comment]
> I am afraid it is too late to deprecate and remove them in 4.0.

With an OTC vote it is.

**Comment by nhorman** [comment]
Ok, then someone can open an issue for 5.0 if this is of interest
