### ISSUE TITLE
EVP_RAND should be renamed to OSSL_RAND

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#14297]
A decision was made a few years ago that all new APIs (*) should be prefixed with `OSSL_` or `OPENSSL_`.  This is how the STORE sub-system came to be named `OSSL_STORE`.

With that in mind, `EVP_RAND` is misnamed and should be called `OSSL_RAND`, especially in light that there was nothing preexisting within the EVP APIs (*) that offered randomness functionality (the preexisting sub-system was simply called `RAND`).

-----

(*) In this issue, "API" is understood as "family / related group of functions", not "individual functions"

**Comment by mattcaswell** [comment]
>  decision was made a few years ago that all new APIs (*) should be prefixed with OSSL_ or OPENSSL_

I think this only applies to new namespaces that we want to use. Since EVP_* is already a namespace we use I don't think this is a reason in itself (e.g. we've also recently introduced EVP_MAC_*, EVP_KDF_* etc)

There might be other reasons to consider a rename.

**Comment by t-j-h** [comment]
Basically all the crypto related stuff is under EVP_ which I think is fine - we have a lot of stuff there. 
Renaming at this point I don't think adds value.
Right now anyone asking about what APIs to use for crypto gets the simple answer of "EVP" which helps. 
Pulling just rand out separately doesn't make a lot of sense to me.

**Comment by richsalz** [comment]
FWIW, I think @t-j-h gets it exactly right:

> Right now anyone asking about what APIs to use for crypto gets the simple answer of "EVP" which helps.

**Comment by mattcaswell** [comment]
OTC: We won't be doing this.
