### ISSUE TITLE
Figure out algorithm lifecycles

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14298]
Figure out state machines for the various cryptographic algorithms.
The intention is to enforce the transitions in due course.

e.g. for digests:

```
new --> init --> update +-> final +-> free
        ^        ^      |         |
        |        +------+         |
        +-------------------------+
```

**Comment by t8m** [comment]
You should be able to go from update to init as well.

And then there is the XOF which might allow repeating final (but only for XOF digests).

**Comment by paulidale** [comment]
Agreed with both.  I was keeping it simple since it was only an illustration :)

**Comment by paulidale** [comment]
The MAC portion of this is discussed in #13210

**Comment by paulidale** [comment]
Continuing the digest theme:

![digest](https://user-images.githubusercontent.com/17916609/109445093-888dc500-7a8a-11eb-85f7-2a6face78fd8.png)

1. The primary path through is along the black edges going through the red labelled nodes.
1. The dark blue edges are less common, but still legal, paths.  I've used a dotted line to indicate a shortcut to free and a dashed for the rest.
1. The XOF only path is black and dashed.  I could use another colour here perhaps.
1. The light blue nodes represent the beginning and end of the lifecycle.

What are people's thoughts about this approach?  Suggestions etc welcome.

**Comment by paulidale** [comment]
In the same vein, MAC and RAND.
![mac](https://user-images.githubusercontent.com/17916609/109451808-01484d80-7a9a-11eb-8541-b9b0216e5a54.png)

![rand](https://user-images.githubusercontent.com/17916609/109451811-03aaa780-7a9a-11eb-99a5-03e670b93759.png)

**Comment by t8m** [comment]
IMO I would not add the dotted _free lines as they should be just implicit and obvious (or just add it as remark to the freed state).

Otherwise this is looking good in general sense. I am not sure though the EVP_MD_CTX diagram is correct though in regards what the current implementation is doing. In particular the EVP_MD_CTX_reset() puts the ctx into the new state and not initialised. Also you should be able to do Init from any state (except for freed of course).

**Comment by t8m** [comment]
The init from any state should IMO apply to EVP_MAC_CTX as well.

**Comment by paulidale** [comment]
I'll fix the EVP_MD_CTX_reset() lines, rushing too quickly through the code without thinking through the implications.
Happy to drop the _free lines, that will simplify the diagrams a little -- maybe I could add a "any other state" box with the _free calls....

**Comment by paulidale** [comment]
Getting rid of the _free lines simplifies things.

![digest](https://user-images.githubusercontent.com/17916609/109572719-74ed6780-7b39-11eb-9276-f2cd3b980152.png)

![mac](https://user-images.githubusercontent.com/17916609/109572724-76b72b00-7b39-11eb-898e-80d8ea4cc811.png)

![rand](https://user-images.githubusercontent.com/17916609/109572735-79198500-7b39-11eb-8f17-31274b38223e.png)

**Comment by paulidale** [comment]
And ciphers.

I didn't include the evcrypt init and decrypt init flows separately, although they could be.  I also didn't include the setting of the tag for AEAD decryption -- this can be one in multiple states and makes a mess.

![cipher](https://user-images.githubusercontent.com/17916609/109579094-04981380-7b44-11eb-8e2c-691822afed18.png)

**Comment by paulidale** [comment]
The tripath cipher.

![cipher](https://user-images.githubusercontent.com/17916609/109591886-1ab0ce80-7b5a-11eb-8456-67930275c183.png)

**Comment by richsalz** [comment]
I appreciate the pretty pictures but how does this help 3.0 get done?

**Comment by richsalz** [comment]
I need to clarify my comment because it came across badly.  I think the pictures are cool.  They are clear and legible. I am just wondering how this affects 3.0?  That is an honest question.

**Comment by beldmit** [comment]
Formal description of the state machine can be used to forbid the bad order of the operations

**Comment by paulidale** [comment]
What @beldmit wrote.  This sprang from the bug in #13210 and the OTC wanted it looked into.

**Comment by paulidale** [comment]
KDF

![kdf](https://user-images.githubusercontent.com/17916609/109778989-364ad080-7c51-11eb-9ef2-abad9075a359.png)

**Comment by paulidale** [comment]
Updated digest that splits XOF and non-XOF better.

![digest](https://user-images.githubusercontent.com/17916609/109900191-ae150b80-7ce2-11eb-917d-713d87062228.png)


 A PKEY overview.  The intention is to dig into one operation in more details.

![pkey](https://user-images.githubusercontent.com/17916609/109900240-c38a3580-7ce2-11eb-906a-5707b275e50a.png)

**Comment by beldmit** [comment]
I'm not sure we should allow the transition between Update and Init.

**Comment by t8m** [comment]
> I'm not sure we should allow the transition between Update and Init.

Why not? It seems harmless. Basically you should be able to reinit your context at any point. And 1.1.1 certainly allows this.

Also you can run init from the init state as well. That is currently missing.

**Comment by beldmit** [comment]
> > I'm not sure we should allow the transition between Update and Init.
> 
> Why not? It seems harmless. Basically you should be able to reinit your context at any point. And 1.1.1 certainly allows this.
> 
> Also you can run init from the init state as well. That is currently missing.

I don't see any scenario to allow it.

**Comment by t8m** [comment]
Why not? You can set up a context for an operation, init it and then at any point later by some external cause you can decide that the operation is not to be finished and it needs to be restarted again fresh. I do not see why you would have to start with a new context in such case when if you finalize it, you'd be allowed to reuse the context. It simply does not make sense to me to arbitrarily limit the possibilities to reinitialize the context.

Of course another option would be not allowing reinitialization at all or only via reset->init, but that would be a breaking change.

**Comment by beldmit** [comment]
Personally I'm afraid that some implementations will not be accurate enough to cleanup in this case. Reset and init seems to be safer.

**Comment by paulidale** [comment]
The only algorithm I showed init going back to itself was ciphers where this is used.  Digests support it too but it's kind of pointless.  I left this out because it (needlessly) complicates thing IMO.  I'm kind of ambivalent about permitting it or not: I doubt anyone would reinit while in the init state.  Going back to init from any other state is reasonable.

The free calls can be done from anywhere, this is also not pictured.  It greatly simplified things.

For PKEY operations, any of the inits can be called pretty much anytime.  I planned on including this in the single operation diagram, it was pointless in the combined one (as was the free call).

**Comment by t8m** [comment]
I do not really see why init from init complicates things when you still allow init from any other state.

As for the @beldmit worry about the cleanup - that means we should worry about cleanup when calling init from any other state except reset and that means allowing only reset from any state and that means breaking change.

**Comment by paulidale** [comment]
It messed the pretty pictures up :)

**Comment by t8m** [comment]
You could do something like "any state except freed" and line with init from there.

**Comment by t8m** [comment]
And similarly for reset

**Comment by slontis** [comment]
Look ok to me Pauli.

ccm and gcm follow the same kind of pattern - the complexity is in the places WHERE params need to be setup for ivlen and tag depending on encryption or decryption

**Comment by paulidale** [comment]
I had those bits in at one point.  For encryption it was okay, the tag is grabbed from the final state.  For decryption, the tag can be set in too many places for nice output.

**Comment by paulidale** [comment]
I've created a spreadsheet with fuller state transitions.  The spreadsheet should be considered canonical with the diagrams begin illustrative only.

[lifecycles.xlsx](https://github.com/openssl/openssl/files/6098293/lifecycles.xlsx)

**Comment by paulidale** [comment]
OTC: document these life cycles, note that these will be enforced at some point in the future and doing that will not be considered a breaking change.
