### ISSUE TITLE
SSL_build_cert_chain crashed

### ISSUE THREAD

**Issue by moso1** [openssl/openssl#14294]
Recently I am testing the new OpenSSL 3.0 alpha release and I find a regression that track to commit 6725682d77510bf6d499957897d7be124d603f40.
 
The file in question is ssl/ssl_cert.c 
My application crashes at line 887 because ctx is null.
    xs_ctx = X509_STORE_CTX_new_with_libctx(real_ctx->libctx, ctx->propq);
 
The crash callstack is:
ssl_build_cert_chain
ssl3_ctrl (case SSL_CTRL_BUILD_CERT_CHAIN: it pass in ctx as null)
SSL_ctrl
SSL_build_cert_chain

**Comment by slontis** [comment]
It looks like the line should be
````
xs_ctx = X509_STORE_CTX_new_with_libctx(real_ctx->libctx, real_ctx->propq);
````
Can you see if that fixes your issue?

**Comment by moso1** [comment]
Yes, that fix resolves the immediate crash.

**Comment by mattcaswell** [comment]
There's another reference to just `ctx` a little bit further down that function. Probably that should also be `real_ctx`
