### ISSUE TITLE
Generate providers/fipsmodule.cnf as part of the build and not in individual tests

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14315]
The tests that run also with the fips provider generate the providers/fipsmodule.cnf file with fipsinstall. Unfortunately that causes intermittent CI failures when multiple tests are run in parallel and the tests step on each other toes.

It would be useful also to developers to have the providers/fipsmodule.cnf be generated in the build target with proper dependency on the fips.so if they do not want to do installation and they do not want to run one of the existing tests that will generate the file for them.

**Comment by t8m** [comment]
This is an example of the typical failure:
https://github.com/openssl/openssl/runs/1948887011

**Comment by levitte** [comment]
Yup.

Oh, I have a branch...

**Comment by levitte** [comment]
The other answer could also be that each test should place that file in their respective result directory instead of $BLDDIR/test

**Comment by richsalz** [comment]
> Oh, I have a branch ...

I took at look at https://github.com/levitte/openssl/branches/all and just closed the window and backed away ... :)

**Comment by t8m** [comment]
> The other answer could also be that each test should place that file in their respective result directory instead of $BLDDIR/test

Yeah, but on the other hand there are also other reasons why having correct fipsmodule.cnf file that can be shared by the tests would make sense. Also the file is currently placed in $BLDDIR/providers and IMO it should stay there.

**Comment by levitte** [comment]
> Yeah, but on the other hand there are also other reasons why having correct fipsmodule.cnf file that can be shared by the tests would make sense.

Oh, I totally agree with you. I have lamented the difficulty to reproduce a single test due to having to run the whole test recipe to get a correct fipsmodule.cnf, more than once. I'm just saying that there is a real quick solution, other than this more correct solution.

**Comment by levitte** [comment]
> I took at look at https://github.com/levitte/openssl/branches/all and just closed the window and backed away ... :)

Yeah, there's a lot of old junk there that I should clean away. But even then, the branch I mentioned here only exists on my laptop for the moment. 
(so if you think my openssl fork on github is full of branches? ... Yeah, that)

**Comment by levitte** [comment]
There, that dormant branch cleaned up and submitted, see #14320
