### ISSUE TITLE
Should man7 pages be in an OpenSSL namespace?

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14318]
Numerous man7 pages are just called things like "provider" or "property". Should these pages have some sort of openssl prefix to them?

**Comment by rsbeckerca** [comment]
Considering that SSL documentation, by default, is in its own namespace already (`/usr/local/ssl/man`), it might not be worth the effort. How many common is it for installations to fold `/usr/local/ssl/man` into `/usr/local/man`?

**Comment by mattcaswell** [comment]
I'm thinking more about people doing "man property" and getting an OpenSSL page back - not so much where they are physically stored.

**Comment by rsbeckerca** [comment]
So, in the case of MANPATH having both `./man7` directories, I would then prefer to have the SSL namespace involved at the very least for anything ambiguous. `openssl-` is commonly used. Using `./man1` as an example, though, there is both `genrsa.1` and `openssl-genrsa.1`, which is confusing unto itself to the casual user.

**Comment by levitte** [comment]
The common way to claim a namespace in man-pages isn't to modify the manual basename, but to append to the suffix.

As a matter of fact, we do support that kind of namespace claim when installing, via the make variable MANSUFFIX, but leave it to the user / packager to set it as they wish.  For example, this:

```
$ make install MANSUFFIX=ossl
```

will result in the installation having man-page files like `man7/provider-base.7ossl`

**Comment by mattcaswell** [comment]
Interesting. Should that be on by default I wonder?

**Comment by levitte** [comment]
That's a good question.  I would.

**Comment by rsbeckerca** [comment]
> 
> 
> Interesting. Should that be on by default I wonder?

Personally, I think it should be. We currently install to a separate directory structure within man, so it might not matter much but I would prefer to have this as a default.

**Comment by kroeckx** [comment]
I've been using "ssl" in Debian for 15 years as suffix.

I've also patched it to call pod2man with --section that adds
"SSL" to the section.

At some point I also made a patch that updated all manpages
to use "evp(7ssl)" instead of "evp(7)", and would then turn it
whatever suffix was used when making the manpage.

There are at least some manpages that conflict with manpages from
other software.

**Comment by paulidale** [comment]
I'd support on by default.  @kroeckx got it right IMO.

**Comment by levitte** [comment]
1. If we pick a namespace, which should use it for all sections, which is what MANSUFFIX does
2. Should the namespace reflect the functionality or the product?  "ssl" does kinda sorta both...

**Comment by mattcaswell** [comment]
> I've also patched it to call pod2man with --section that adds
"SSL" to the section.
>
> At some point I also made a patch that updated all manpages
to use "evp(7ssl)" instead of "evp(7)", and would then turn it
whatever suffix was used when making the manpage.

This sounds like stuff we should have in main line OpenSSL.

**Comment by mattcaswell** [comment]
> Should the namespace reflect the functionality or the product? "ssl" does kinda sorta both...

Since "ssl" is what Debian is using it kinda makes sense just to use that.

**Comment by levitte** [comment]
Hmmm, it seems like we dropped `$(MANSUFFIX)` in master.  It is present in the commands to produce man-pages in 1.1.1...
So basically, this diff would make the difference, I think?

``` diff
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index a079311b13..cbf94e643b 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -1332,7 +1332,7 @@ EOF
           my $pod = $args{generator}->[0];
           return <<"EOF";
 $args{src}: $pod
-       pod2man --name=$name --section=$section --center=OpenSSL \\
+       pod2man --name=$name --section=$section\$(MANSUFFIX) --center=OpenSSL \\
                --release=\$(VERSION) $pod >\$\@
 EOF
       } elsif (platform->isdef($args{src})) {
```

The other bit is that MANSUFFIX is currently empty by default, but that's easily changed, here:

https://github.com/openssl/openssl/blob/b0aae913246af1d07e728d24f53f55028f61c696/Configurations/unix-Makefile.tmpl#L287-L290

**Comment by mattcaswell** [comment]
How do we handle internal references to the section using the right suffix with MANSUFFIX within the pod files, i.e. references to evp(7) should be evp(7ssl) (or whatever the MANSUFFIX is).

**Comment by kroeckx** [comment]
As far as I know, the only way to do that is to process the pod files before giving it to pod2man.

**Comment by kroeckx** [comment]
But if we just say that from now on is ssl or ossl, there is no
need to pre-process it.

**Comment by mattcaswell** [comment]
> But if we just say that from now on is ssl or ossl, there is no need to pre-process it.

Not sure I understand your point here? Surely if we specify a MANSUFFIX then all the pod files need to use it where references to other pages are made?
