### ISSUE TITLE
Rename ASN1_BOOLEAN variable name in struct asn1_type_st in asn1.h

### ISSUE THREAD

**Issue by Patrick5088** [openssl/openssl#14312]
```
typedef struct asn1_type_st {
    int type;
    union {
        char *ptr;
        ASN1_BOOLEAN boolean;
        ASN1_STRING *asn1_string;
        ASN1_OBJECT *object;
        ASN1_INTEGER *integer;
        ASN1_ENUMERATED *enumerated;
        ASN1_BIT_STRING *bit_string;
        ASN1_OCTET_STRING *octet_string;
        ASN1_PRINTABLESTRING *printablestring;
        ASN1_T61STRING *t61string;
        ASN1_IA5STRING *ia5string;
        ASN1_GENERALSTRING *generalstring;
        ASN1_BMPSTRING *bmpstring;
        ASN1_UNIVERSALSTRING *universalstring;
        ASN1_UTCTIME *utctime;
        ASN1_GENERALIZEDTIME *generalizedtime;
        ASN1_VISIBLESTRING *visiblestring;
        ASN1_UTF8STRING *utf8string;
        /*
         * set and sequence are left complete and still contain the set or
         * sequence bytes
         */
        ASN1_STRING *set;
        ASN1_STRING *sequence;
        ASN1_VALUE *asn1_value;
    } value;
} ASN1_TYPE;
```

**ASN1_BOOLEAN boolean** will create conflicts in windows environment, because there are other places in the Windows SDK that define the **boolean** type. Because of that, the compiler will interpret the boolean variable as a type and two types can't be next to each other. It's a beginner mistake from Windows to create unconditional define, especially a boolean. Compilation errors will be a problem for projects that use OpenSSL on Windows.

Can you please rename it, if it's possible?

**Comment by t8m** [comment]
Why do not we see this failure on any Windows builds anywhere? Unfortunately the struct asn1_type_st definition is part of the public API and we cannot change this.

**Comment by levitte** [comment]
> Why do not we see this failure on any Windows builds anywhere?

It might be that we're being careful in which order we include `<windows.h>` and `<openssl/asn1.h>`...  there is a spot *somewhere* with a comment on that topic (can't remember where)

**Comment by Patrick5088** [comment]
I want to mention that the conflict will be with the typedef of **boolean** in **rpcndr.h (Windows SDK)**

**Comment by petermost** [comment]
> 
> 
> Why do not we see this failure on any Windows builds anywhere? Unfortunately the struct asn1_type_st definition is part of the public API and so we cannot change this.

But the 'boolean' name is part of a union, so it should be possible to conditionally provide a different name, like 'asn1_boolean'  and the size or memory layout of that union should stay the same.

**Comment by levitte** [comment]
> But the 'boolean' name is part of a union, so it should be possible to conditionally provide a different name, like 'asn1_boolean' and the size or memory layout of that union should stay the same.

I believe that @t8m's concern is that, since this is a publicly defined union, there may be apps out there that do look explicitly at this field, by that name, and that if we change the name, their build will break.

So what we need to weigh is one break (the clash with Windows SDK) vs another possible break (apps that access that field directly).

[personal opinion: direct access of the ASN1_TYPE fields should be discouraged, so I'm leaning toward a name change...  but in that case, we should change all those names uniformly, like prefixing them all with `ossl_`]

**Comment by mattcaswell** [comment]
> Why do not we see this failure on any Windows builds anywhere? 

Presumably this doesn't affect our *own* builds, but rather applications that include certain windows headers *and* our headers.

**Comment by petermost** [comment]
I was talking about something like this:

#if defined(DONT_USE_BOOLEAN_FIELDNAME)
    ASN1_BOOLEAN asn1_boolean;
#else
    ASN1_BOOLEAN boolean;
#endif`

**Comment by t8m** [comment]
We could maybe use some define from the rpcndr.h in the ifdef.

However we would still have to add some more hacking around like `#define asn1_boolean boolean` in the `#else` case so we could reference the field uniformly in our code.

**Comment by t8m** [comment]
And yeah another option would be to make the ASN1_TYPE private. Would it be possible? I do not think going just the half way of changing the other member names which would inevitably break the same apps would make much sense.

**Comment by richsalz** [comment]
apps that include the windows headers *after* openssl should be fine.
this is not a regression.

**Comment by tom-cosgrove-arm** [comment]
@mattcaswell Is this really a bug in OpenSSL? It seems it's more a problem with the Windows headers. It also seems unlikely that we are going to make a change to OpenSSL here, so @t8m do you think we should close this issue?

**Comment by t8m** [comment]
Hmm... maybe we could do something that I mentioned in https://github.com/openssl/openssl/issues/14312#issuecomment-785830705

```C
/* rpcndr.h which typedefs boolean includes this define */
#ifdef small
#define asn1_boolean asn1_boolean
#else
#define asn1_boolean boolean
#endif
```

IMO we could do this.

**Comment by t8m** [comment]
Potential fix in #24124

**Comment by davidben** [comment]
Whether or not OpenSSL works around this, this should definitely be communicated to Microsoft as something they need to fix. Squatting as generic of a name as `boolean` as a macro in system headers like this is quite rude.

Adding @samuel-lee-msft who got something similar resolved in wincrypt.h previously in https://github.com/openssl/openssl/pull/18131#discussion_r854415820

That said, we build an OpenSSL derivative with Windows all the time and have never run into this. I'm a little confused by this report. I don't see a `boolean` macro in `rpcndr.h`. I do see `typedef unsigned char boolean`, but that doesn't seem to be a problem. Playing around with godbolt, every compiler I've tried is perfectly happy with the same symbol being used as a struct field and a typedef name, in both C and C++.

Before doing a workaround and breaking the public API, I think OpenSSL should gather a bit more data here. @Patrick5088 can you please share the compiler error that you got, as well as what compiler + version you're running, and which version of the Windows SDK you're using?

**Comment by agustinbcu01** [comment]
Good morning:

Any Idea when this is fixed using boolean.

**Comment by tom-cosgrove-arm** [comment]
@agustinbcu01 If you are seeing this issue, would you mind showing exactly how you are building OpenSSL? The Microsoft SDK actually appears to `typedef` `boolean`, which means it's in a different namespace, and this definition in OpenSSL shouldn't be a problem.

If something is `#define`ing `boolean` then that would be a problem, but that's not what we are seeing.

In other words: we build OpenSSL on Windows, and don't see this problem. So do many other people. So we need more information to understand what the specific problem is.

**Comment by nhorman** [comment]
Given that the PR is still a draft, and that  @samuel-lee-msft hasnt yet provided input as to how to raise this as an issue to msft, and the fact that @tom-cosgrove-arm  accurately poiints out that our windows builds build fine (implying that there is something amiss with the reporters environment), i'm inclined to close this as not planned, unless there is some disagreement?

**Comment by nhorman** [comment]
no response, marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by petermost** [comment]
**3 years** ago @Patrick5088 and I worked for the same company when he/we encountered the problem. But we no longer work there and therefore can no longer reproduce the problem or provide any further information.

**Comment by t8m** [comment]
I am closing the issue then as it should be a non-issue.

**Comment by Patrick5088** [comment]
Yeah. It can be closed. Not relevant anymore
