### ISSUE TITLE
How to free the result of EVP_PKEY_get1_DSA() ?

### ISSUE THREAD

**Issue by tomiii00** [openssl/openssl#14323]
With DSA_free() deprecated in #10977, what is the proper way to free the pointer returned by EVP_PKEY_get1_DSA()? Or was that supposed to be deprecated similarly to EVP_PKEY_get1_RSA() and others? Ideally I would just use EVP_PKEY* everywhere as recommended but I'm porting legacy code that passes around lots of DSA* and I'm trying to rewrite as little of it as possible. Thanks!

**Comment by paulidale** [comment]
The plan is to deprecate this call.  So it's either rewrite the relevant code or suppress the deprecation warning.

An aside: the deprecated calls are not going to disappear for a number of years.

**Comment by mattcaswell** [comment]
> Or was that supposed to be deprecated similarly to EVP_PKEY_get1_RSA() and others?

Yes - `EVP_PKEY_get1_DSA()` is supposed to be deprecated (see #14303). PR #14319 makes that change.

**Comment by levitte** [comment]
Either way, to answer the question asked, `DSA_free()` remains the appropriate way to free something that was returned by `EVP_PKEY_get1_DSA()`.  We just gotta get our deprecations in sync.
