### ISSUE TITLE
Viewing the salt length field in the PKCS7 structure for RSA-PSS

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#14327]
Below is a piece of my PKCS7 structure with RSA PSS being set:
```
........        
digest_enc_alg: 
          algorithm: rsassaPss (1.2.840.113549.1.1.10)
          parameter: SEQUENCE:
    0:d=0  hl=2 l=  48 cons: SEQUENCE          
    2:d=1  hl=2 l=  13 cons:  cont [ 0 ]        
    4:d=2  hl=2 l=  11 cons:   SEQUENCE          
    6:d=3  hl=2 l=   9 prim:    OBJECT            :sha256
   17:d=1  hl=2 l=  26 cons:  cont [ 1 ]        
   19:d=2  hl=2 l=  24 cons:   SEQUENCE          
   21:d=3  hl=2 l=   9 prim:    OBJECT            :mgf1
   32:d=3  hl=2 l=  11 cons:    SEQUENCE          
   34:d=4  hl=2 l=   9 prim:     OBJECT            :sha256
   45:d=1  hl=2 l=   3 cons:  cont [ 2 ]        
   47:d=2  hl=2 l=   1 prim:   INTEGER           :20
..........
```

So, the integer "20" above is the salt length?
Please correct me if i'm wrong.

**Comment by t8m** [comment]
Yes, this is the salt length.

**Comment by saddy-muchu** [comment]
OK.
Thank you

**Comment by levitte** [comment]
FYI, what you're looking at is described in [RFC 3447, A.2.3 - (Scheme identification for) RSASSA-PSS](https://tools.ietf.org/html/rfc3447#appendix-A.2.3).  The `cont [2]` corresponds to this:

```
          saltLength         [2] INTEGER          DEFAULT 20,
```

**Comment by saddy-muchu** [comment]
But for SHA256, the salt length needs to be 32 right?
i am a little confused as to why it is 20

**Comment by t8m** [comment]
No, the salt length is only recommended to be the same as the hash size but there is no such requirement.

**Comment by saddy-muchu** [comment]
OK.
It even doesn't take the max salt length too via the formula (key_size - digest_len - 2). I'm signing using a 2048 bit RSA key.

**Comment by levitte** [comment]
I really suggest reading the RFC I linked to.  Lots of gory details that answer most of your questions

**Comment by saddy-muchu** [comment]
ok i understood now.
20 is the hexadecimal value which equates to 32 in decimal
