### ISSUE TITLE
Pushed by mistake to git@github.com:openssl/openssl.git

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#14332]
When preparing a PR I made two mistakes in a row, which had the effect that I pushed it to upstream/master rather than origin/master :frowning: 
Very sorry for that - how to fix this? 
I guess I cannot force-push, so shall I revert the commits?

**Comment by t8m** [comment]
There is no problem with that. It will get overwritten once there is a regular PR merge.

**Comment by t8m** [comment]
This should be now resolved.

**Comment by DDvO** [comment]
Yes, thanks!
