### ISSUE TITLE
Resolve or remove TODO in test/acvp_test.c - AES_GCM iv setting

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14330]
There is a TODO 3.0:

```
    /*
     * TODO(3.0): The IV should not be set outside the boundary as it is now.
     * It needs to be fed in via a dummy entropy source for this test.
     */
    if (!TEST_true(EVP_CipherInit_ex(ctx, NULL, NULL, key, iv, enc))
        || !TEST_true(EVP_CIPHER_CTX_set_padding(ctx, 0))
        || !TEST_true(EVP_CipherUpdate(ctx, NULL, &len, aad, aad_len))
        || !TEST_true(EVP_CipherUpdate(ctx, out, &len, pt, pt_len)))
        goto err;

```

**Comment by paulidale** [comment]
@slontis, do we need to address this or not?

I can't imagine this being a problem.  The ACVP test utility was mostly to demonstrate what's required for the FIPS lab.

**Comment by slontis** [comment]
Ideally when they do the test in the lab the IV would be done the way that is mentioned here.. ta the time of writing it was not possible.. Maybe just remove the TODO tag and leave the comment.

**Comment by slontis** [comment]
@paulidale - did you actually address this problem which was that we couldnt feed test fixed bytes into the FIPS provider.

**Comment by paulidale** [comment]
Yes, the test-rng can do this, it's a bit of mucking around to set up.  See `drbg_test()` in the same test.

**Comment by t8m** [comment]
What's unclear to me is whether it is really required by the ACVP testing. IMO it isn't. If the ACVP test requires to feed the whole IV explicitly to the GCM algorithm, it must allow it to be done via some kind of diagnostic interface even if such interface is not allowed to be used for normal use in compliant applications. In my opinion it should not matter whether that diagnostic interface is just hacking the rng used or extra EVP set IV call.

BTW we have been always ACVP testing the OpenSSL in Red Hat Enterprise Linux via te explicit set IV call and it was never a problem. The limitation that the compliant applications must never do that applies only to applications, not to the algorithm testing.

⁣Tomáš​

27. 2. 2021 2:27, 2:27, Pauli <notifications@github.com> napsal/a:
