### ISSUE TITLE
EVP_PKEY_supports_digest_nid does not work with provider-side keys

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#14343]
I am facing a regression of #7348. During TLS negotiation is the TPM provider asked to sign using an unsupported hash, provided by the default provider. The TPM cannot sign using external hash algorithms, so despite a hash algorithm is implemented by some other provider it cannot be used for digest-signing using TPM-based keys.

To solve this in a generic way, the `EVP_PKEY_supports_digest_nid` has been created some years ago and used in [`ssl/t1_lib.c:check_cert_usable`](https://github.com/openssl/openssl/blob/master/ssl/t1_lib.c#L3045) to check whether a particular hash is compatible with a particular sigalg. It is however based on `evp_pkey_asn1_ctrl`, which works for legacy keys only, so the old problem re-appears after migration to providers.

I found few possibilities how this could be solved "in the provider world", but none of them is perfect. The trouble is there seems to be no mechanism to "check" something.
 * The `EVP_PKEY_CTX_set_signature_md` could be (mis)used to check compatibility of a hash, but this requires creation of a temporary PKEY_CTX and initialization of a sign/verify operation (e.g. `EVP_PKEY_sign_init`). These steps can be seen as a waste of computing resources, decreasing the performance as it needs to be called for each candidate sigalg.
 * There could be a new KEYMGMT settable parameter such as `OSSL_PKEY_PARAM_MD_SUPPORTED` that will only test validity of the argument, instead of setting it. But this is also a slight misuse of the API.
 * Or there could be a completely new KEYMGMT function to check various assertions (`OSSL_FUNC_KEYMGMT_ASSERT_PARAMS`) that would consume e.g. the `OSSL_PKEY_PARAM_MD_SUPPORTED`, verify the assertion ("this MD is supported") and return 0/1 accordingly. It seems to me that e.g. `ASN1_PKEY_CTRL_CMS_IS_RI_TYPE_SUPPORTED` might be also unsupported by providers, so this might be usable also for others.

The `OSSL_FUNC_KEYMGMT_ASSERT_PARAMS` function feels to be the cleanest solution, but is it acceptable to introduce yet another KEYMGMT function? (It's not very invasive and it's quite generic hence reusable.) Or do you see other options how the `EVP_PKEY_supports_digest_nid` can be implemented for non-legacy?

**Comment by levitte** [comment]
> * There could be a new KEYMGMT settable parameter such as `OSSL_PKEY_PARAM_MD_SUPPORTED` that will only test validity of the argument, instead of setting it. But this is also a slight misuse of the API.

Wouldn't that be better implemented as a *gettable* parameter?

**Comment by levitte** [comment]
I have another fairly radical idea; make sigalgs directly fetchable.  I cannot see why libcrypto needs to go through the business of splitting a sigalg into hash and pkey algos, just to join them backtogether to perform the signing operation.  The benefit with that is that libcrypto would have no need at all to keep that internal cross reference table saying what goes together.

**Comment by beldmit** [comment]
It will possibly work for GOST, but I'm not sure that it work for RSA that allows many hash algorithms to be used.

**Comment by gotthardp** [comment]
Having a gettable parameter is also a possibility. But since a TPM usually supports multiple digest algorithms, there would be multiple parameters of the same type (if that is allowed) or some array structure (which is cumbersome to use). A muti-value gettable parameter sounds nice though.

Having fetchable sigalgs sounds nice too. It might also simplify the EVP_DigestSign API and bring some automation to the "algorithm-id" business.

**Comment by levitte** [comment]
Er, @beldmit, can you tell me why fetching "sha1WithRSAEncryption" and getting an EVP_SIGNATURE wouldn't be workable?

> Having fetchable sigalgs sounds nice too. It might also simplify the EVP_DigestSign API and bring some automation to the "algorithm-id" business.

Yes, exactly.
(although, I would prefer not to overload the EVP_DigestSign API, it's already confusing enough as it is)

**Comment by beldmit** [comment]
Yes, it will be workable. My fault.

**Comment by levitte** [comment]
Come to think of it, this isn't even a novel idea...  this thought exists in pre-3.0, but is implemented in terms of EVP_MD:

https://github.com/openssl/openssl/blob/a88ea7dfdfba2c34bd575076f12f06d80dd2c0c2/crypto/evp/m_sha1.c#L280-L292

Now that we have an `EVP_SIGNATURE`, that would seem like the perfect method for that sort of thing

**Comment by beldmit** [comment]
If I remember correctly, there were some tricks when there was more than one compatible algorithm...

**Comment by paulidale** [comment]
I think this boils down to us needing a way for a provider to say that this signature algorithm can only be used with digests from itself (or more generally, that if any one operations comes from a provider, all must do so).  For most providers and quite a number of HSMs, it isn't necessary to fetch the digest from the same device as the signature -- we definitely don't want to lose this capability.

**Comment by levitte** [comment]
Having yet another look at this, I'm not sure I understand what's happening.  If the key is a provider key, then `evp_pkey_asn1_ctrl()` should return -2, no?  In that case, the fallback code should kick in, no?  As far as I know, that code *does* support provider side keys.

https://github.com/openssl/openssl/blob/8287a4c3b2230f8df109f5eb34171fa0058add2c/crypto/evp/p_lib.c#L1254-L1265

**Comment by gotthardp** [comment]
My point was that legacy engines have `ASN1_PKEY_CTRL_DEFAULT_MD_NID` **and** `ASN1_PKEY_CTRL_SUPPORTS_MD_NID`, each behaving differently. However, for providers there is only `EVP_PKEY_get_default_digest_nid` because the `EVP_PKEY_supports_digest_nid` falls back to (behaves exactly as) `EVP_PKEY_get_default_digest_nid`.

**Comment by levitte** [comment]
`ASN1_PKEY_CTRL_SUPPORTS_MD_NID` is new in master / 3.0, so no production engine should support it.  We *could* very simply revert ecbb2fca9301ef22b15beb30c4c0303b29846935

**Comment by levitte** [comment]
My reasoning is that it's a bit misplace to ask the key type implementation what digests are supported, since that's really about the signature implementation.  However, that's how the legacy implementations work, and as long as libssl hasn't been refactored to handle signature algorithms that libcrypto doesn't have internal knowledge of, the legacy code should keep on working with very little change.

**Comment by gotthardp** [comment]
Yeah, it doesn't fit the provider mechanisms. The ecbb2fc was introduced as an option for a TPM (and similar engines) to indicate what sigalgs can be used. It would be sad to revert that commit without having an alternate solution. Offering only one (default) digest during TLS negotiation will cause unnecessary handshake failures.

**Comment by levitte** [comment]
> The ecbb2fc was introduced as an option for a TPM (and similar engines) to indicate what sigalgs can be used...

... gotcha, and I've recently argued that this should really be done by fetching them directly instead of doing the split-and-join dance with the sigalg identity, see #14467.

Note that with fetchable sigalgs, it would mean that they're fetched very early, and of `check_cert_usable()` would have to check support of the sigalg id (be it a NID or a name in string form) against that, or be fetched on demand, which would essentially make `check_cert_usable()` irrelevant, as the usability comes down to the fetch result.

In a similar vein, we could simply keep doing the split dance, but then simply call `EVP_DigestSIgnInit_ex()` or `EVP_DigestVerifyInit_ex()` (whichever applies) and use the result to verify that the sigalg is acceptable.  I'd find that kind of solution much more feasible, and most of all future proof, than making `EVP_PKEY_supports_digest_nid()` work with providers.

**Comment by gotthardp** [comment]
With #14467 the ecbb2fc can be reverted. (I was not aware of that, sorry.) Only I wish it could be in 3.0.0 as it impacts usability of TLS with TPM-based keys.

**Comment by levitte** [comment]
Unfortunately, it might take a longer while than I expected to get #14467 in.  In the mean time, a cheap solution would be what I proposed, to do a check using `EVP_DigestSignInit_ex()`
