### ISSUE TITLE
Resolve or remove TODO 3.0 in providers/.../rand_unix.c

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14358]
There is the following TODO in function wait_random_seeded():

```
#    ifndef FIPS_MODULE
            /* TODO 3.0: The FIPS provider doesn't have OPENSSL_atexit */
            if (shm_addr != (void *)-1)
                OPENSSL_atexit(&cleanup_shm);
#    endif
```
Is this still really relevant given the seed source is not in the FIPS provider anymore?
@paulidale

**Comment by paulidale** [comment]
This isn't needed anymore.  In fact the `#ifndef FIPS_MODULE` can be removed.  I'll raise the PR.
