### ISSUE TITLE
See also link on OPENSSL_init_crypto docs on website does not work.

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#1435]
The website's [`OPENSSL_init_crypto` docs](https://www.openssl.org/docs/manmaster/crypto/OPENSSL_init_crypto.html) have a link to `OPENSSL_init_ssl`, but that link doesn't work. It goes to:
https://www.openssl.org/docs/manmaster/crypto/OPENSSL_init_ssl.html
rather than:
https://www.openssl.org/docs/manmaster/ssl/OPENSSL_init_ssl.html

**Comment by richsalz** [comment]
same root cause as #119.
