### ISSUE TITLE
SSL_CTX_set_ecdh_auto is undefined for newer openssl's

### ISSUE THREAD

**Issue by vishnuutd** [openssl/openssl#1437]
im trying to implement the sample TLS server program from

[(https://wiki.openssl.org/index.php/Simple_TLS_Server )]. im trying to implement this visual studio 2015 and i installed the master fork of openssl. Are there any solutions for this?

thanks
vishnu

**Comment by mattcaswell** [comment]
It has been removed from OpenSSL 1.1.0. Here is the relevant CHANGES entry:
````
  *) SSL_{CTX_}set_ecdh_auto() has been removed and ECDH is support is
     always enabled now.  If you want to disable the support you should
     exclude it using the list of supported ciphers. This also means that the
     "-no_ecdhe" option has been removed from s_server.
     [Kurt Roeckx]
````

Perhaps we should have a no-op compatibility macro for this.

**Comment by mattcaswell** [comment]
Although one issue with a compat macro would be that `SSL_CTX_set_ecdh_auto()` can be used to both enable and disable support. The macro wouldn't work as expected for anyone trying to disable support. I expect 99% of uses would be for enabling though.

**Comment by mattcaswell** [comment]
I added some compat macros in 2ecb9f2.

Closing ticket.
