### ISSUE TITLE
Equality tests on EVP_sha1() etc should not be called

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#14387]
In a number of places in the code we have

`if (md == EVP_sha1())`

and that is something we should not be doing. If we want to know if something is SHA1 then testing this way is simply not the right way to do it. It will break in unexpected ways.

```
./ts/ts_rsp_sign.c:        || ctx->ess_cert_id_digest == EVP_sha1()) {
./x509/x_all.c:    if (type == EVP_sha1() && (data->flags & EXFLAG_SET) != 0
./cms/cms_sd.c:            if (md == EVP_sha1() || md == NULL) {
```

**Comment by t8m** [comment]
Should be replaced with EVP_MD_is_a

**Comment by richsalz** [comment]
also
```
; g grep '== EVP_md'  
crypto/ec/ecx_meth.c:        if (p2 == NULL || (const EVP_MD *)p2 == EVP_md_null())
; g grep --extended '[!=]= EVP_[a-zA-Z0-9]+\('
# duplicates removed 
crypto/ess/ess_lib.c:    if (hash_alg != EVP_sha256()) {
```

**Comment by paulidale** [comment]
Shane already did a PR #14474 that addressed most of these.  All of the == tests and a number of others.

What's left are in his comment: https://github.com/openssl/openssl/pull/14474#issuecomment-817429336

> There are still some calls to EVP_Digest() and EVP_DigestInit_ex()
> If you do a search for EVP_sha1()
> EVP_PKEY_CTX_set_dh_kdf_md() also
>
> Note that X509_digest() is fine since it uses the libctx from the cert.

Including a few EVP_sha256() references, the relevant file list is:
```
crypto/asn1/x_algor.c
crypto/rsa/rsa_oaep.c
crypto/rsa/rsa_pmeth.c
crypto/pem/pvkfmt.c
crypto/ocsp/ocsp_lib.c
crypto/ocsp/ocsp_vfy.c
crypto/evp/p5_crpt2.c
crypto/cms/cms_dh.c
crypto/cms/cms_smime.c
crypto/cms/cms_ec.c
crypto/x509/v3_skid.c
crypto/x509/v3_purp.c
crypto/x509/t_x509.c
crypto/x509/x_crl.c
crypto/ess/ess_lib.c
crypto/srp/srp_vfy.c
crypto/pkcs12/p12_crt.c
crypto/pkcs12/p12_mutl.c
```

plus _crypto/evp/dh_ctrl.c_ that defines `EVP_PKEY_CTX_set_dh_kdf_md()`.
