### ISSUE TITLE
Should bio_new_from_core_bio be made public API?

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14409]
Certain provider side functions get passed an `OSSL_CORE_BIO` object. Providers are supposed to use that in the various BIO related upcalls that the core makes available `c_bio_read_ex`, `c_bio_write_ex`, `c_bio_vprintf`, etc. However an `OSSL_CORE_BIO` must never be used as a straight `BIO` although it will be tempting to provider authors to simply cast it to one. This will work if the provider and the core are linked against the same version of libcrypto - but if the definition of the BIO structure is different then this will break.

For our own providers we have a mechanism for wrapping up an `OSSL_CORE_BIO` inside a real BIO that the provider can actually use directly. We make use of this extensively in our own providers but it is not public API.

Should we make it public? It will probably need some refactoring to make it suitable.

**Comment by paulidale** [comment]
So long as `OSSL_CORE_BIO` stays opaque, I can't immediately think of any adverse implications. It would allow an application that contains a provider to access it from both sides.  However, we don't expose the `OSSL_CORE_BIO` to applications and they shouldn't be talking directly to providers so what's the use case?


Another possibility would be to ensure that `OSSL_CORE_BIO` is distinct from a normal BIO to prevent the cast from working.  It would be straightforward to make it a structure that either has a pointer to the BIO or a dummy field to offset it in memory.

**Comment by mattcaswell** [comment]
> However, we don't expose the OSSL_CORE_BIO to applications and they shouldn't be talking directly to providers so what's the use case?

We expose OSSL_CORE_BIO to provider authors (its defined in the public API in include/openssl/core.h and is use in include/openssl/core_dispatch.h). So the use case is for provider authors to have access to this functionality. At the moment a provider author that needs to use an OSSL_CORE_BIO has to jump through hoops to make sure they use the upcalls appropriately.

It might not be a bad idea to ensure the cast does not work too.

**Comment by paulidale** [comment]
Thinking further about this, I'm starting to have nebulous doubts.

**Comment by mattcaswell** [comment]
> I'm starting to have nebulous doubts.

Care to expand on why?

**Comment by paulidale** [comment]
Nothing specific yet, just confusion from muddling through the morass on both sides of the provider boundary.
