### ISSUE TITLE
Should OSSL_DECODER_from_data update the data pointer?

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14410]
The new 3.0 function OSSL_DECODER_from_data is defined as follows:

````
 int OSSL_DECODER_from_data(OSSL_DECODER_CTX *ctx, const unsigned char **pdata,
                            size_t *pdata_len);
````
It has this documentation

````
OSSL_DECODER_from_data() runs the decoding process for the context I<ctx>,
with input coming from I<*pdata>, I<*pdata_len> bytes long.  Both I<*pdata>
and I<*pdata_len> must be non-NULL.  When OSSL_DECODER_from_data() returns,
I<*pdata> is updated to point at the location after what has been decoded,
and I<*pdata_len> to have the number of remaining bytes.
````

The "updated to point at the location after what has been decoded" is what I am concerned about. This, presumably, is copied from the approach that the d2i functions take. I assume it is to allow for the possibility of easily running multiple decoders one after the other on a stream of input. In practice however I have rarely seen applications take advantage of this "feature" (with the d2i functions) and have many times seen misunderstandings about this and incorrect usage. This kind of error is common place:

````
   unsigned char *data = /* malloc some data and fill it */
   long len = /* len of the data */

   SOMETHING *thing = d2i_SOMETHING(NULL, &data, len);

    OPENSSL_free(data);
````

This code looks natural but is wrong (because the `data` pointer is modified by the d2i call and hence you end up freeing the wrong thing). The solution is that you have to maintain 2 pointers and free the right one.

In practice, mallocing a buffer and then calling a d2i function on it is quite common - but calling multiple d2i functions one after the other is rare. Therefore, IMO, we should design the decoder API to make it easy for the common usage by not updating the data pointer. Instead applications wishing to call multiple decoders one after other should have the responsibility of amending the pointer themselves based on the returned length.

**Comment by t8m** [comment]
Or something like
```
int OSSL_DECODER_from_data(OSSL_DECODER_CTX *ctx, const unsigned char *data,
                           size_t *pdata_len, const unsigned char **pnext);
```
should work as well and be quite clear. The pnext could be NULL of course for applications that are not interested in knowing the pointer to the remaining data. Although there is still the update of *pdata_len that might be confusing. In that case this might be even better:
```
int OSSL_DECODER_from_data(OSSL_DECODER_CTX *ctx, const unsigned char *data,
                           size_t data_len, const unsigned char **pnext, size_t *premaining);
```

**Comment by levitte** [comment]
I don't see why we need to update both the pointer and the count of remaining bytes.  So I'd either go for the strtol() model:

``` C
int OSSL_DECODER_from_data(OSSL_DECODER_CTX *ctx, const unsigned char *data,
                           size_t data_len, const unsigned char **pnext);
```

or have a size_t pointer where the number of consumed bytes is given:

``` C
int OSSL_DECODER_from_data(OSSL_DECODER_CTX *ctx, const unsigned char *data,
                           size_t data_len, size_t *used);
```

The application can easily calculate whatever they need from the updated output args.

**Comment by levitte** [comment]
Do note that we have a precedent for this type of thing, in BIO:

``` C
int BIO_read_ex(BIO *b, void *data, size_t dlen, size_t *readbytes);
int BIO_write_ex(BIO *b, const void *data, size_t dlen, size_t *written);
```

**Comment by t8m** [comment]
In that case I'd vote for the size_t *used option. As it is much less awkward to use the value for both moving the pointer and decreasing remaining data length than in the strtol case.

**Comment by mattcaswell** [comment]
> Do note that we have a precedent for this type of thing, in BIO:

This is my preferred model too.

**Comment by levitte** [comment]
> As it is much less awkward to use the value for both moving the pointer and decreasing remaining data length than in the strtol case.

I've also seen compilers for an LP64 platform that converts any pointer calculation (comparisons, subtractions, additions) to int, and this constantly warns about possible data loss.  For that reason, this is my preference too.

**Comment by richsalz** [comment]
The i2d/d2i stuff is useful when (un)packing nested structures.  And, like this API, is sometimes used on data from an external source.  Parsing is historically trickier than we think. I suggest you keep the length and buffer and somehow return the new values.

**Comment by t-j-h** [comment]
Given that people will be using a combination of d2i and from_data in code I think having two different models here would be an unfortunate choice to make. This model has its uses - and we haven't deprecated all the d2i functions and having a split model approach I think leads to more irritation.

I guess this comes down to new users compared to existing users - existing users know and use this model and you're introducing a variation on the pattern. Keeping the same model isn't unreasonable - and this is a matter of "taste" more than any actual real need.

The arguments for doing this would also suggest a need to add a d2i variant that works the same way for the existing d2i calls and then deprecate the originals - i.e. if we think this is important enough to make a change we should offer a consistent API set for usage. Having to use two different models of API in the one code base doesn't really "solve" the underlying "problem" here.
