### ISSUE TITLE
Some public GOST macros are no longer present in 3.0

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14440]
In 1.1.1 the following GOST macros are defined in tls1.h

````
# define TLS_CT_GOST12_SIGN              238
# define TLS_CT_GOST12_512_SIGN          239
````

In 3.0 they are renamed as follows:

````
# define TLS_CT_GOST12_IANA_SIGN         67
# define TLS_CT_GOST12_IANA_512_SIGN     68
# define TLS_CT_GOST12_LEGACY_SIGN       238
# define TLS_CT_GOST12_LEGACY_512_SIGN   239
````

This is actually a breaking change. There probably should be a compatibility macro for the old defines.

**Comment by mattcaswell** [comment]
@beldmit

**Comment by beldmit** [comment]
Well... 67 and 68 are officially registered values, 238 and 239 are from a special range.

Will submit a PR.
