### ISSUE TITLE
Missing CHANGES entry describing the legacy provider

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14441]
I can't seem to find a CHANGES entry which describes the introduction of the legacy provider, and the fact that certain algorithms that were previously available by default are no longer available.

**Comment by mattcaswell** [comment]
Fix in #14465

**Comment by t8m** [comment]
IMO this should be even in NEWS.md

**Comment by mattcaswell** [comment]
> IMO this should be even in NEWS.md

Done in #14465
