### ISSUE TITLE
1.1.0 API needs const getters

### ISSUE THREAD

**Issue by ekasper** [openssl/openssl#1444]
The new 1.1.0 APIs have added getters of the form

```
FOO *BAR_get0_foo(BAR *bar);
```

These should be *const* getters

```
const FOO *BAR_get0_foo(const BAR *bar);
```

 (along with setters or mutable getters, if needed) to be able to still write code with `const` arguments.

**Comment by FdaSilvaYY** [comment]
Hi, i'm agree with what you stated.

How do you thinking a mutable getter should be named: ?
`FOO *BAR_get_foo(BAR *bar);` ? 
another form ?

**Comment by mattcaswell** [comment]
FWIW I compiled a list of all symbols that contain the string `_get0_` that appear in the header files, that do not appear in the 1.0.2 headers. Attached. There are 83 of them.
[get0new.txt](https://github.com/openssl/openssl/files/414350/get0new.txt)

**Comment by mattcaswell** [comment]
See #1456

**Comment by ekasper** [comment]
@FdaSilvaYY I think we prefer

```
FOO *BAR_get1_foo(BAR *bar);
```

for refcounted objects. (Where the `1` in `get1` indicates that we up the refcount.) Probably

```
FOO *BAR_get0_mutable_foo(BAR *bar);
```

if we really need to return a shared mutable pointer.

**Comment by mattcaswell** [comment]
@ekasper can we close this issue now? Steve has applied all the non-controversial changes from #1456, so I think we've got as far as we are able to get with this.

**Comment by mattcaswell** [comment]
Ping @ekasper - happy to close?

**Comment by mattcaswell** [comment]
Closing this on the basis of Steve's recent commits.
