### ISSUE TITLE
Change in behaviour for EVP_PKEY_CTRL_RSA_KEYGEN_BITS

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14443]
Previously this ctrl (typically invoked via `EVP_PKEY_CTX_set_rsa_keygen_bits`) would fail (with a -2 return value) if the number of bits was too small. In 3.0 any value is allowed and the failure occurs during the keygen call instead.

Is this change intentional or correct?

**Comment by t8m** [comment]
We could and should IMO fix that (probably except for the concrete -2 return value). I do not see why to defer the check to the keygen call.

**Comment by levitte** [comment]
I assume that the difference in behavior is specifically with an EVP_PKEY with a provider side internal key.


-2 was mainly used for "unsupported ctrl command", but *sometimes* also used for "unsupported value" or something along that line, while in other cases, 0 was used for an invalid value (or was it -1?)...  The ctrl\<-\>params translator can probably include a workaround to fix this, specifically for that control...

**Comment by paulidale** [comment]
Add note to the effect of: _providers can validate settings/parameters on set or on init.  Neither is enforced.  Users should not rely on either behaviour_ to the documentation.  No need to change the behaviour here.
