### ISSUE TITLE
Some ctrls seem to have a different return value in some cases than they did in 1.1.1

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14442]
Previously the ctrl `EVP_PKEY_CTRL_RSA_MGF1_MD` would return -2 in the event of an attempt to use this
ctrl with the rsa padding set to some mode not compatible with its use. It now returns -1.

Is this change intentional or correct?

I suspect a number of other ctrls that previously returned -2 for some invalid data, now no longer do.

Since these ctrls are now handled by params (which I think universally return 0 or 1?),  I'm not sure it's viable to retain support for the old -2 return codes.

**Comment by t8m** [comment]
We could return -2 if the relevant param is not present in settable params. However it would not solve this case unless we make the rsa_settable_params fully dynamic.

**Comment by levitte** [comment]
This is related to #14443

**Comment by mattcaswell** [comment]
OTC: This change of behaviour, but there should be a CHANGES entry for it.
