### ISSUE TITLE
Why engine's .rsa_sign is never called?

### ISSUE THREAD

**Issue by ademyankov** [openssl/openssl#14459]
It happens while implementing an engine with RSA. Even though `RSA_METHOD`'s set `.rsa_sign`, the latter never gets invoked. Instead, `.rsa_priv_enc` is called which doesn't make any sense at all! Because sign operation internally is decryption with a private key.

This is how `openssl `is invoked:
```sh
openssl rsautl -sign -raw -engine myssl \
-keyform ENGINE -inkey rsa_1024_priv_myssl.bin \
-in plaintxt.bin \
-out sig.bin
```
Is there a reasonable explanation for this? Because it's very confusing.

**Comment by levitte** [comment]
`openssl rsautl` has long been a utility that enables the basic primitives, and therefore directly calls RSA_private_encrypt() to sign, and that ends up in the `.rsa_priv_enc` function of the RSA method.

For your curiousity, here's the code that does the actual work:

https://github.com/openssl/openssl/blob/01b9e18fb20ae158a056223fc62772887040d85f/apps/rsautl.c#L232-L251

To get "higher level" operations, `openssl pkeyutl` would probably end up calling `.rsa_sign`...

Note that in OpenSL 3.0 (not yet released), `openssl rsautl` has changed to use higher level functions, so you'll probably notice a different behavior.

**Comment by ademyankov** [comment]
I have `OpenSSL 1.1.1f  31 Mar 2020`, and I've just checked `openssl pkeyutl`, `EVP_PKEY_sign` still calls the `.rsa_priv_enc` function.

BTW, `s_server` and `s_client` also call `.rsa_priv_enc` for RSA signature. Will it be changed in the new version as well?

**Comment by t8m** [comment]
> Because sign operation internally is decryption with a private key.

No, sign operation is internally an _encryption_ with a private key.

**Comment by t8m** [comment]
> I have `OpenSSL 1.1.1f 31 Mar 2020`, and I've just checked `openssl pkeyutl`, `EVP_PKEY_sign` still calls the `.rsa_priv_enc` function.

It does for some padding modes. The reason is simple. The engine's rsa_method->sign() operation supports only the RSA_PKCS1_PADDING mode.

> BTW, `s_server` and `s_client` also call `.rsa_priv_enc` for RSA signature. Will it be changed in the new version as well?

TLS uses now PSS padding when possible so no, it cannot call the sign() operation of the RSA method.

With 3.0 version the engines are deprecated and the providers are the replacements. With providers the whole signing operation is under the provider's control. So yes, with 3.0 there is a way how to do this properly, but not via the engines interface.

**Comment by ademyankov** [comment]
@t8m, thanks for the explanation. I got the idea. Unfortunately, I don't think version 3.0 and providers will solve anything, at least not for me. I need an implementation right now. The problem is that there are hundreds or maybe even thousands of HSMs and crypto-providers implementations using the engine interface. And those are not going anywhere, so all those services cannot simply move to 3.0 unless a provider is implemented from scratch. But I understand that demanding anything from an open-source project would be simply unfair.

> No, sign operation is internally an _encryption_ with a private key.

RSA signing and decryption use the private key, and RSA encryption and verification use the public key. This is the cornerstone of asymmetric cryptography. Some crypto-providers do not allow or do not support RSA encryption with a private key. That's the case I am having. When you remove hashing and padding from the picture the 'textbook' RSA sign operation mathematically is the same as 'textbook' RSA _decryption_ with a private key. The way the RSA primitives are applied. You can read up if you do not believe me.

And `openssl` does exactly that. It uses a naked RSA operation when does RSA PSS sign. The data is prepared outside and then `.rsa_priv_enc` w/ NO_PADDING is called. Where actually `openssl` meant to do signing operation. I had to do RSA decryption internally to do that. Imagine how ugly it looks from the code perspective when you see `XCrypto_RSA_decrypt(...)` inside of `.rsa_priv_enc` engine function. That's why I said that the way `openssl` name functions and calls them doesn't make sense in this case.

But anyway, thanks for the discussion; I appreciate it.

**Comment by t8m** [comment]
> When you remove hashing and padding from the picture the 'textbook' RSA sign operation mathematically is the same as 'textbook' RSA _decryption_ with a private key. The way the RSA primitives are applied. You can read up if you do not believe me.

We are both right actually because this is just a matter of naming the operation. Because the raw encryption and decryption operations for RSA are actually the same modular exponentiations. The openssl code calls the rsa_priv_enc this way because the signing is really RSA private key encryption operation and verification is really RSA public key decryption operation. No matter that in the mathematical sense there is no distinction between encryption and decryption under the hoods.
