### ISSUE TITLE
After merging the change constifying EVP_PKEY_get0 return value external gost test fails

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14466]
The gost engine uses EVP_PKEY_get0*() functions and does not expect the return value being const. This makes the external tests build to fail.

A temporary workaround could be to make the gost engine build without -Werror. Otherwise this needs fixing in the gost-engine code.

**Comment by t8m** [comment]
@beldmit Would you please look at this on the gost-engine side?

**Comment by beldmit** [comment]
@t8m, will do.

**Comment by t8m** [comment]
Example of the failure:
https://github.com/openssl/openssl/runs/2057812906

**Comment by beldmit** [comment]
No, switching of the -Werror makes non-working build :(

**Comment by beldmit** [comment]
Oh. It looks like we've got to the situation I tried to avoid as much as possible.

I'd suggest temporary switch off the gost tests until I deal with this stuff. I'm afraid there is no relevant API to replace it for the GOST engine.

**Comment by levitte** [comment]
It sounds real mysterious with a build that breaks when you remove `-Werror`...

**Comment by beldmit** [comment]
The build doesn't, but the tests do

**Comment by t8m** [comment]
I am curious why this breaks. Shouldn't the Gost engine work with legacy keys only?

8. 3. 2021 19:05, 19:05, Dmitry Belyavskiy <notifications@github.com> napsal/a:

**Comment by beldmit** [comment]
It should. I didn't investigate yet, but it may fall because of trying to modify the constant EVP_PKEY object

**Comment by t8m** [comment]
If the EVP_PKEY object has legacy origin it shouldn't be truly const. I.e., the key should be update-able although the get0 call returns it as const. If we broke that somehow, we need to fix that. @mattcaswell ?

8. 3. 2021 20:02, 20:02, Dmitry Belyavskiy <notifications@github.com> napsal/a:

**Comment by mattcaswell** [comment]
> If the EVP_PKEY object has legacy origin it shouldn't be truly const.

Right...if legacy origin then it shouldn't be a problem.

**Comment by t8m** [comment]
I'm thinking we could even provide a new function EVP_PKEY_get0_legacy() that would return a non-const pointer but would return NULL if the key doesn't have legacy origin.

8. 3. 2021 20:09, 20:09, mattcaswell <notifications@github.com> napsal/a:

**Comment by mattcaswell** [comment]
Or just use the get1 functions which are already non-const.

**Comment by mattcaswell** [comment]
Or....actually maybe there isn't an EVP_PKEY_get1....'cos its void *...:-(

**Comment by beldmit** [comment]
> Or just use the get1 functions which are already non-const.

It was the first idea but I didn't find it immediately

**Comment by levitte** [comment]
> Or just use the get1 functions which are already non-const.

Hmmm, except that functionality that's part of an EVP_PKEY_ASN1_METHOD *must* be able to manipulate the internal legacy key, by design.  And that's exactly what an engine does.

**Comment by levitte** [comment]
Functions that are designed for EVP_PKEY_ASN1_METHOD will have to unconst the return value of `EVP_PKEY_get0()`

**Comment by levitte** [comment]
An idea is to make `EVP_PKEY_get0()` return a non-const value, which the type specific counterparts (EVP_PKEY_get0_RSA() et al) return const values, with the argument that EVP_PKEY_get0() is more likely to be used from EVP_PKEY_METHOD and EVP_PKEY_ASN1_METHOD functionality.

**Comment by beldmit** [comment]
Yes, it's a great idea

**Comment by t8m** [comment]
Then we should also make it to return NULL if the key origin is not legacy.

8. 3. 2021 20:38, 20:38, Richard Levitte <notifications@github.com> napsal/a:

**Comment by levitte** [comment]
> Then we should also make it to return NULL if the key origin is not legacy.

Sure
