### ISSUE TITLE
OpenSSL 1.1.0 missing accessors

### ISSUE THREAD

**Issue by ramahmoo** [openssl/openssl#1446]
With v1.0.2 I can access that directly:

`SSL_SESSION->cipher`

In new version how can i access this?

**Comment by mattcaswell** [comment]
Looks like a reasonable thing to want to do, and there is no accessor for it. We should add one.

**Comment by richsalz** [comment]
@mattcaswell see #1451

**Comment by richsalz** [comment]
fixed at commit e928132.  thanks for the report.
