### ISSUE TITLE
"error 20 at 0 depth lookup: unable to get local issuer certificate" On Lets Encrypt fullchain.pem

### ISSUE THREAD

**Issue by nagstaku** [openssl/openssl#14470]
This caused me some headache, and I'm not entirely sure the openssl tool is "wrong" here, but the fullchain.pem provided by Lets Encrypt appears to fail verification when checking with the latest openssl tool (performed via docker alpine/openssl image):

```
root@testHost:~/certs/acme.services# docker run --rm -it -v ${PWD}:/tmp alpine/openssl verify /tmp/fullchain.pem
CN = acme.services
error 20 at 0 depth lookup: unable to get local issuer certificate
error /tmp/fullchain.pem: verification failed
```

version:
```
docker run --rm -it alpine/openssl version
OpenSSL 1.1.1g  21 Apr 2020
```

These certs do however work when I load them into the [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx).

This problem all became apparent when I got GoDaddy certs, followed directions like such:
```
cat intermediate.crt server.crt > chain.crt
openssl verify chain.crt
chain.crt: OK
```

BUT! Loading these into [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) actually fails with the following errors:
`backend_ssl.go:46] Error obtaining X.509 certificate: unexpected error creating SSL Cert: certificate and private key does not have a matching public key: tls: private key does not match public key`

And then I found strangely enough doing it backwards works:
```
cat server.crt intermediate.crt > chain.crt
openssl verify chain.crt
CN = acme.services
error 20 at 0 depth lookup: unable to get local issuer certificate
error chain.crt: verification failed
```

Yet loading that, once again, into kubernetes/[ingress-nginx](https://github.com/kubernetes/ingress-nginx) works without error.

I was about to file the issue with the ingress-nginx project, but realized if it works there, and Lets Encrypt provides the fullchain.pem in this format, that I feel it is more likely that openssl is the errant tool. But please do correct me if I'm wrong, I just want to save other developers from the headaches 😄

**Comment by mattcaswell** [comment]
Are you able to share fullchain.pem?

**Comment by nagstaku** [comment]
@mattcaswell 

-----BEGIN CERTIFICATE-----
MIIGLzCCBRegAwIBAgISBESIBVMjGRpuFFc3oMPJktCpMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTAyMTQwNzE1NDZaFw0yMTA1MTUwNzE1NDZaMBcxFTATBgNVBAMT
DHR0ci5zZXJ2aWNlczCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANXz
2rrRYZ4vcPcRCun32Jr6pdUAlM9QWhgZBYaQoptGEe8O671X/QLU+2JhDmi1vjBk
kTFXLSTyScnl/3OzMXpSzuCmMbJp9CDmkZ3CeDf8r3aDcQJDzZeZ/rCM86ZN6K2f
Xq9ld5HP3jYpK3+P8r7JlaV8RdB3n+hmWfopcnUlDF7IjYfioQSjvxZICSp50pYc
ujz47dd6kXxpeYYJ3GiQ5F/svBf8489c6hRb+j2k3E1lVsTtRXw3J2eGjwlpdxB/
jK2IaMYlwy5G7CIxlaBHGdj1j4qz4+dbmUi5gFpZVc54VQDt4OXllk+VcbaiZQlk
t4XQv2rvk9vzr/7QLVZma56RBEz7xaghGcpFlWnG+PvsQ0QaPRBYOAgOB7tkorQR
2TxK1krFmKRErrgTyWfnqKT98W1iix+4jAy32xZneT/EqmgqjL4H6vAHl9B2+7OB
nyKOvGMf+VeLyUxJZU3DKv4o0Q86UVXL9dFLgkHF8Mt21INzfgpQI7ac1/38qmz2
ZeM0Df2fdcXLYURkYfedVIV4BDBlL9t9bk1QnYyGaiolEJ343IcAnowE0GKBfjCh
/KZnhmo5ASyMF4z9MGZFobmEb0826f+qYnAvdMXn9e0UavlDpCqMq/vhC14pq57F
ybq8VruKFNmF57reJhti8iViF2MK/ER+19A7cNBpAgMBAAGjggJYMIICVDAOBgNV
HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
EwEB/wQCMAAwHQYDVR0OBBYEFL0bFkszU6PpGklfNDGu58jrdqLGMB8GA1UdIwQY
MBaAFBQusxe3WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEF
BQcwAYYVaHR0cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8v
cjMuaS5sZW5jci5vcmcvMCcGA1UdEQQgMB6CDioudHRyLnNlcnZpY2Vzggx0dHIu
c2VydmljZXMwTAYDVR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAm
BggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEFBgorBgEE
AdZ5AgQCBIH2BIHzAPEAdgBc3EOS/uarRUSxXprUVuYQN/vV+kfcoXOUsl7m9scO
ygAAAXefnCPNAAAEAwBHMEUCIQCMa+UpkeRcWs8/nIunLng1bkGAqPvRL+AGLo0E
59+52gIgWeuRThRpxPz52ISziN/ZNrItRO9E4dg+vldsid0vDeoAdwD2XJQv0Xcw
IhRUGAgwlFaO400TGTO/3wwvIAvMTvFk4wAAAXefnCPJAAAEAwBIMEYCIQCAQLwm
qFX3s4vXnoPcROJjxci7pztnK8aItvYhG1K8nQIhAJzPxTSYQ1aolBLPL0hkhnGI
uOj4cQiDcjpEzCGNRAlBMA0GCSqGSIb3DQEBCwUAA4IBAQBK1t1fPmUgaUZudTAc
ISBF/P3MUciQFK+6g7u4kpEo4f32aDTVGTk5z58dC173EDL7bIm4RwNqUgJMe9JA
nZ+YI6GHjokiGmS71xIV4us8Y1LmP68kkR9NfOENjhJL9FxZipPxod4v3pVSqDAS
X71Gi0X5V+Whx+YBxtM9PyN6bxis003CC55V270g8jLZj0TAxOTLJKuBq3FgRe2D
QJ7Rkc8ZZnhSZmTG5b0ZLmPkI7DbB/L+ICCqnuI4PUwYjEUFygAwW+100EFWuiU7
91a278CwPG9aRvSfLJbY6JIbLwNgXlFzlHiZxhwcbeYOIN1qhUd8XkXNukzbqTDG
IGjt
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIEZTCCA02gAwIBAgIQQAF1BIMUpMghjISpDBbN3zANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIwMTAwNzE5MjE0MFoXDTIxMDkyOTE5MjE0MFow
MjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxCzAJBgNVBAMT
AlIzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwIVKMz2oJTTDxLs
jVWSw/iC8ZmmekKIp10mqrUrucVMsa+Oa/l1yKPXD0eUFFU1V4yeqKI5GfWCPEKp
Tm71O8Mu243AsFzzWTjn7c9p8FoLG77AlCQlh/o3cbMT5xys4Zvv2+Q7RVJFlqnB
U840yFLuta7tj95gcOKlVKu2bQ6XpUA0ayvTvGbrZjR8+muLj1cpmfgwF126cm/7
gcWt0oZYPRfH5wm78Sv3htzB2nFd1EbjzK0lwYi8YGd1ZrPxGPeiXOZT/zqItkel
/xMY6pgJdz+dU/nPAeX1pnAXFK9jpP+Zs5Od3FOnBv5IhR2haa4ldbsTzFID9e1R
oYvbFQIDAQABo4IBaDCCAWQwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8E
BAMCAYYwSwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5p
ZGVudHJ1c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTE
p7Gkeyxx+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEE
AYLfEwEBATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2Vu
Y3J5cHQub3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0
LmNvbS9EU1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYf
r52LFMLGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0B
AQsFAAOCAQEA2UzgyfWEiDcx27sT4rP8i2tiEmxYt0l+PAK3qB8oYevO4C5z70kH
ejWEHx2taPDY/laBL21/WKZuNTYQHHPD5b1tXgHXbnL7KqC401dk5VvCadTQsvd8
S8MXjohyc9z9/G2948kLjmE6Flh9dDYrVYA9x2O+hEPGOaEOa1eePynBgPayvUfL
qjBstzLhWVQLGAkXXmNs+5ZnPBxzDJOLxhF2JIbeQAcH5H0tZrUlo5ZYyOqA7s9p
O5b85o3AM/OJ+CktFBQtfvBhcJVd9wvlwPsk+uyOy2HI7mNxKKgsBTt375teA2Tw
UdHkhVNcsAKX1H7GNNLOEADksd86wuoXvg==
-----END CERTIFICATE-----

**Comment by t8m** [comment]
The openssl verify command does something else than you expect. It just gets one certificate from the file, ignoring the other one and does the verification which of course fails for the second case because the intermediate is not used. You should be able to successfully do:

`openssl verify -untrusted intermediate.crt server.crt`

On the other hand the nginx (and many other applications) just expect the server.crt to be the first certificate in the fullchain file.
