### ISSUE TITLE
Error handling in x509_algor_new_from_md() & x509_algor_md_to_mgf1() functions

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#14472]
i see the following snippets in each of those functions:
  if (md == NULL || EVP_MD_is_a(md, "SHA1"))
        return 1
    
  if (mgf1md == NULL || EVP_MD_is_a(mgf1md, "SHA1"))
        return 1;

Why do we return success even if "md" and "mgf1md" is a NULL pointer?

**Comment by t8m** [comment]
Because the default is SHA1 - that is the == NULL part of the condition and that is just fine. And if the default is passed in then we do not have to do anything further. That is the other part of the condition.

**Comment by t8m** [comment]
Does it answer the question?

**Comment by saddy-muchu** [comment]
Sorry - i'm still confused

**Comment by t8m** [comment]
Basically NULL is fine to pass as it indicates you want the default, which is SHA-1. And the SHA1 does not need any extra work to be done, because it is the default. So `return 1` is correct. Not sure how to explain it differently if it still is not clear.

**Comment by saddy-muchu** [comment]
ok thanks a lot
