### ISSUE TITLE
Do we need the KDF set_ctx_params calls

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14475]
The KDF derive call takes an OSSL_PARAM array which can set everything required.  If this argument is made mandatory, we no longer require the context set params call.

The KDF life cycle is new -> derive -> free.  There is no init or update.

We'd lose the ability to set the params piecemeal but this is a new API so there is no need to support such setting via ctrls.

The settable call would remain.

Should we remove these functions?

**Comment by levitte** [comment]
Will no one ever need them?  We've been discussing future proofing elsewhere, wouldn't leaving the possibility to set params separately before the derive open be just that?

**Comment by paulidale** [comment]
Derive accepts params and they have to be used before the derivation -- otherwise they are doing nothing since there isn't anything after the derive call.

**Comment by mattcaswell** [comment]
OTC: We will leave the set_ctx_params as is.
