### ISSUE TITLE
Freshly generated DSA parameters fail EVP_PKEY_param_check()

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14480]
I used the following code to create a new set of DSA parameters and then call `EVP_PKEY_param_check()` on it:

````
void do_param_check(const char *name, int paramgen)
{
    EVP_PKEY_CTX *ctx = EVP_PKEY_CTX_new_from_name(NULL, name, NULL);
    EVP_PKEY *pkey = NULL;

    if (paramgen) {
        if (EVP_PKEY_paramgen_init(ctx) <= 0) {
            printf("failed to init PKEY ctx\n");
            return;
        }
    } else {
        if (EVP_PKEY_keygen_init(ctx) <= 0) {
            printf("failed to init PKEY ctx\n");
            return;
        }
    }

    if (EVP_PKEY_gen(ctx, &pkey) <= 0) {
        printf("failed to generate\n");
        return;
    }

    EVP_PKEY_CTX_free(ctx);
    ctx = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, NULL);

    if (EVP_PKEY_param_check(ctx) > 0)
        printf("Param check for %s succeeded\n", name);
    else
        printf("Param check for %s failed\n", name);

    EVP_PKEY_CTX_free(ctx);
    EVP_PKEY_free(pkey);
}

int main(void)
{
    ...
    do_param_check("DSA", 1);
    ...
}
````

This always fails the param check complaining that `q` is not prime.

**Comment by t8m** [comment]
The reason is that we generate the parameters with ossl_ffc_params_FIPS186_2_gen_verify but verify them with ossl_ffc_params_FIPS186_4_gen_verify. The FFC_CHECK_Q_NOT_PRIME is misleading as the q is prime it is just not the prime expected to be generated with the seed.

**Comment by t8m** [comment]
IMO we should not use ossl_ffc_params_FIPS186_2_gen_verify when generating DSA of size >= 2048 bits.

**Comment by slontis** [comment]
Before I go trying to fix this - this raises a few issues that I am not sure what the correct way to do is..

We have 2 types of keygen
(1) fips-186-3 (which is what 1.1.1 had)
(2) fips-186-4

When we do the keygen,
params for gen_type, seed etc can be set into the keygen params...
A validity check can be made to work for these since the keygen knows all the parameters,,

If we save these dsa params to a file and load it again there is missing info (for the type and seed etc)..

What is the correct way to feed this info back into the key after the load??
(There is no set_params in dsa_keymgmt.c)

**Comment by slontis** [comment]
The original spec for (1) was between 512-1024 bits in multiples of 64 (The code does allow large sizes though)

**Comment by slontis** [comment]
> ossl_ffc_params_FIPS186_2_gen_verify when generating DSA of size >= 2048 bits.

Currently the gen_type determines this..
Are you talking about if the type is not set??
There is a "default" currently but that chooses fips-186-2 (We could change it so it selects depending on the size for the default case), but if you specifically set the type then it should not chose something else.

**Comment by t8m** [comment]
> Are you talking about if the type is not set?

Yes, I am talking about the default case. It should be different based on the size IMO.

**Comment by t8m** [comment]
Let's put aside the save/load case for now. But at least for the freshly generated case we could record the paramgen type in the key parameters and thus the parameter validation could select the proper validation algorithm based on the paramgen type.

**Comment by slontis** [comment]
It already sets a flag in the ffc params when it does the gen, so it is easy to get that to work..
Will add a PR tomorrow.
