### ISSUE TITLE
OpenSSL 1.1.1j - Unit tests fail randomly with no-asm option

### ISSUE THREAD

**Issue by am185352** [openssl/openssl#14488]
1. All unit tests were passing in OpenSSL 1.1.1d with _no-asm_ option.
2. Upon using 1.1.1j (or 1.1.1i - same results), unit tests fail randomly E.g., 20-test_enc.t, 15-test_genec.t, and 70-test_packet.t tests pass randomly in one attempt while they fail in another attempt.
3. However, all unit tests pass consistently upon removing no-asm option and using NASM assembler version 2.15.05
4. From the OpenSSL email distribution group, it seems someone might have updated these unit tests or a different section of code after 1.1.1d to pass them in one scenario but might not have validated with no-asm scenario.
5. Am attaching two files - One without VERBOSE and one with. The file is a large one but you may search with "failed" keyword in order to go to the location of the failed tests. Alternatively, you can search with below test names which are the failed ones:
a. 15-test_genec.t
b. 20-test_enc_more.t
c. 90-test_store.t
You can find the overall failure report at the end of the log file.
6. One other observation is using VERBOSE is not raising an error when the test fails so we're seeing success towards the end of the log file with VERBOSE enabled but it seems errors are still logged.
7. I added details to my best but if am missing something, please let me know so that I will add or try them too.

I am expecting:
a. All Unit tests to pass on using no-asm configuration and that too consistently.
b. Can someone take a moment to add your 2-cents what changes can I expect when using OpenSSL APIs built without assembler vs the ones built with assembler (I know C functions are called instead of assembly routines when no-asm is set but I would like to know what difference it would make)

[NT-VS15_WITH_VERBOSE.log](https://github.com/openssl/openssl/files/6111663/NT-VS15_WITH_VERBOSE.log)
[NT-VS15_WITHOUT_VERBOSE.log](https://github.com/openssl/openssl/files/6111664/NT-VS15_WITHOUT_VERBOSE.log)

Windows Batch File - Command Details (Only extracted major portion - rest might not be relevant for your investigation):
    ```
call RSSet OPENSSL_COMMON_CFG_FLAGS=no-asm no-rc5 no-idea no-cast no-whirlpool no-camellia no-seed no-md2 no-md4 no-ripemd no-mdc2 no-hw no-srp no-ssl2 no-ssl3 no-sctp
perl configure --prefix=%~dp0Intermediate\prefix\NT-VS15 --openssldir=%CURRENT_SDKS_PATH%\OpenSSL\%BuildVersion% VC-WIN32 %OPENSSL_COMMON_CFG_FLAGS%

nmake
nmake test
nmake install
    ```

Build Platform Details:

- NASM assembler version - 2.15.05 (Passing when used this)
- Operating System - Windows 10
- Build Platform - VC-WIN32
- nmake.exe - C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
- Perl Version - Tried Strawberry versions of 5.32.1.1-64 and 5.30.0.1-64 and an ActiveState Perl and it did not make a difference.
- Windows SDK Version - 10.0.10586.0

**Comment by mattcaswell** [comment]
> One other observation is using VERBOSE is not raising an error when the test fails so we're seeing success towards the end of the log file with VERBOSE enabled but it seems errors are still logged.

The VERBOSE version really is passing. You may see error messages in the log but that is normal (a lot of the tests are testing error conditions).

It's really very strange that it would pass with VERBOSE but fail without. Possibly some subtle timing issue in the tests?

> Can someone take a moment to add your 2-cents what changes can I expect when using OpenSSL APIs built without assembler vs the ones built with assembler (I know C functions are called instead of assembly routines when no-asm is set but I would like to know what difference it would make)

You will see *significant* performance degradation in the no-asm build vs the asm build. In some cases the asm versions are using constant time, while the C versions are not (or in other words an asm build would be considered more secure than a no-asm build).

Why are you using no-asm rather than asm?

**Comment by am185352** [comment]
Thank you for a quick turn around Max.

- no-asm flag has been set for over a decade in our scripts and we've been leaving it as-is on every OpenSSL upgrade.
- Also, I am not sure what changes it can bring around the APIs functionality on Windows (VC-Win32) when using assembler.

Can you please confirm below:

1. Are we sure that using assembler will not change any functionality on the VC-Win32 platform vs _no-asm_? (so that I can proceed with making the change)
2. If so, what is the intention behind introducing this no-asm option in the first place? 
3. Are we going to fix this (either in this version or upcoming OpenSSL versions)?
4. Please share me with any other information that I should consider before making the change to use assembler vs no-asm.

**Comment by mattcaswell** [comment]
> Are we sure that using assembler will not change any functionality on the VC-Win32 platform vs no-asm? (so that I can proceed with making the change)

There should be no functional difference between asm and no-asm

> If so, what is the intention behind introducing this no-asm option in the first place?

It's primarily there as a debugging option, and as a workaround for people who can't get asm working

> Are we going to fix this (either in this version or upcoming OpenSSL versions)?

We've not had other reports of this problem. If we're able to isolate the issue then it is likely that we would include the fix. However it is very unlikely to be a high priority for investigation.

**Comment by am185352** [comment]
Sorry, it seems a false observation that using assembler is passing the unit tests. I just ran 
[NT-VS15_WithVerbose_WITH_ASM.log](https://github.com/openssl/openssl/files/6119419/NT-VS15_WithVerbose_WITH_ASM.log)
[NT-VS15_WithoutVerbose.log](https://github.com/openssl/openssl/files/6119421/NT-VS15_WithoutVerbose.log)

without "no-asm" flag and tests still fail. Attached are the files with and without Verbose.

**Comment by t8m** [comment]
Actually apparently the runs with verbose output pass correctly. You can see some errors in the verbose output but those are just expected errors in negative test cases. Is the only difference between the verbose and non-verbose build the verbose flag? Could you add the perl configdata.pm --dump to the build script to see the difference between the configure options?

Also I see you're applying some nontrivial patch at the beginning of the build, could you please try building unpatched sources to see whether it behaves in the same way?

**Comment by am185352** [comment]
I capture the config data both with Verbose and without Verbose and I did not see any difference except some address of RanLIb code, which seems to be changing on each build attempt configuration. Am attaching both the configurations and also an additional configuration, which corresponds to the build without applying any of the patches, and that still fails. (You may try using a beyond compare for easily comparison)
[PerlConfigDump_Fail_WithoutPatch.log](https://github.com/openssl/openssl/files/6127491/PerlConfigDump_Fail_WithoutPatch.log)
[PerlConfigDump_Fail_WithPatch.log](https://github.com/openssl/openssl/files/6127492/PerlConfigDump_Fail_WithPatch.log)
[PerlConfigDump_Pass_WithPatchandVerbose.log](https://github.com/openssl/openssl/files/6127493/PerlConfigDump_Pass_WithPatchandVerbose.log)

Also, am attaching the logs again for the build
[NT-VS15_FailWithoutPatch.log](https://github.com/openssl/openssl/files/6127497/NT-VS15_FailWithoutPatch.log)
[NT-VS15_FailWithPatch.log](https://github.com/openssl/openssl/files/6127498/NT-VS15_FailWithPatch.log)
[NT-VS15_PassVerbose.log](https://github.com/openssl/openssl/files/6127499/NT-VS15_PassVerbose.log)

**Comment by t8m** [comment]
@levitte could it be some perl issue? I really cannot see why there should be any difference between the tests running in verbose and non-verbose mode.

**Comment by am185352** [comment]
Hello
I am now facing this sporadic issue again - Last year, the build passed and when I am trying to build now, the tests are failing now. Nothing changed.  Can you please look at the attached files (pass and fail one) and provide your inputs?
[build_fail.txt](https://github.com/openssl/openssl/files/10675560/build_fail.txt)
[build_pass.txt](https://github.com/openssl/openssl/files/10675562/build_pass.txt)

@t8m @mattcaswell

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
