### ISSUE TITLE
Deprecate _ex calls that take an ENGINE * argument

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14492]
There are a number of _ex calls which accept an ENGINE * argument.  These should be deprecated along with the rest of the engine infrastructure.

**Comment by levitte** [comment]
ENGINE is actually not the reason why I suggested the deprecations in #14383.

We had a discussion a while ago, where we, perhaps not formally but still, came to the conclusion that if there is a "modified" function (i.e. one where we append `_ex` or `ex{n}`, `{n}` being a number), the older should be deprecated.
If we do *actually* want to offer several variants of a call, we should distinguish them differently, so for example the `EVP_PKEY_CTX_new_from_xxx()`.

That's what my proposal to deprecate was about.  The fact that the older functions in #14383 take an ENGINE argument is accidental.

**Comment by levitte** [comment]
> If I remember correctly we already discussed that within OTC with the conclusion that we do not want such names, i.e., these should really be _ex functions.

I don't recall that.  We do offer variants with the intention to allow for different types of input in other places, for example the object type specific OSSL_DECODER_CTX_new_for_xxx(), and I think it would be *misleading* to call them `_ex` instead.

**Comment by t8m** [comment]
I think we are mixing things here -  OSSL_DECODER_CTX_new_for_xxx() is fine because that would be a separate call for every xxx type that we would able to decode.
But I thought here we are just adding PARAMS argument and so I do not even know what do you envision the xxx would be in case of the `EVP_PKEY_CTX_new_from_xxx()` that you propose above.

**Comment by levitte** [comment]
> I think we are mixing things here - OSSL_DECODER_CTX_new_for_xxx() is fine because that would be a separate call for every xxx type that we would able to decode.

... and that was what I was trying to express with "If we do _actually_ want to offer several variants of a call,..."

**Comment by mattcaswell** [comment]
OTC: We won't be doing this at this stage.
