### ISSUE TITLE
Segmentation fault in genpkey

### ISSUE THREAD

**Issue by joernheissler** [openssl/openssl#14494]
```
$ openssl version
OpenSSL 1.1.1j  16 Feb 2021
$ openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve P-256
Segmentation fault
```

Reproducible on Debian Stable, Unstable and Ubuntu 20.04.
It should read `ec_paramgen_curve:P-256` (with a colon) but I'd expect a proper error message instead of a segfault.

**Comment by mattcaswell** [comment]
Fix in #14496.
