### ISSUE TITLE
X509_verify_cert regression in 3.0.0-alpha12

### ISSUE THREAD

**Issue by ngg** [openssl/openssl#14509]
I have an example code that generates and verifies a self-signed certificate and it can run successfully with `1.1.1j` and also with `3.0.0-alpha11`, but it fails with `3.0.0-alpha12` with error code `X509_V_ERR_UNSPECIFIED` whose documentation says `Unspecified error; should not happen`.

<details>
 <summary>Click here to expand the code!</summary>

```c
#include <stdio.h>
#include <string.h>
#include <openssl/evp.h>
#include <openssl/x509.h>

int main(void)
{
    // Generate an RSA private key
    EVP_PKEY_CTX* key_ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, NULL);
    EVP_PKEY_keygen_init(key_ctx);
    EVP_PKEY_CTX_set_rsa_keygen_bits(key_ctx, 2048);

    BIGNUM* pubexp = BN_new();
    BN_set_word(pubexp, 65537);
    // This is a deprecated function in 3.0, we only use it to make the example code compatible with 1.1.1 as well
    EVP_PKEY_CTX_set_rsa_keygen_pubexp(key_ctx, pubexp);

    EVP_PKEY* priv_key = NULL;
    EVP_PKEY_keygen(key_ctx, &priv_key);
    EVP_PKEY_CTX_free(key_ctx);

    // Create cert subject
    X509_NAME* subject = X509_NAME_new();
    X509_NAME_add_entry_by_NID(subject, NID_pkcs9_emailAddress, V_ASN1_UTF8STRING,
      (const unsigned char*)"boss@example.com", strlen("boss@example.com"), -1, 0);

    // Compose a root CA
    X509* cert = X509_new();
    X509_set_issuer_name(cert, subject);
    X509_set_subject_name(cert, subject);
    X509_NAME_free(subject);

    ASN1_TIME* time = ASN1_TIME_new();
    ASN1_TIME_set(time, 1000000000);
    X509_set1_notBefore(cert, time);
    ASN1_TIME_set(time, 2000000000);
    X509_set1_notAfter(cert, time);
    ASN1_TIME_free(time);

    X509_set_pubkey(cert, priv_key);
    ASN1_INTEGER* serial = ASN1_INTEGER_new();
    ASN1_INTEGER_set(serial, 10);
    X509_set_serialNumber(cert, serial);
    ASN1_INTEGER_free(serial);

    // Sign it
    X509_sign(cert, priv_key, EVP_sha512());
    EVP_PKEY_free(priv_key);

    // Add it as a trusted cert
    X509_STORE* cert_store = X509_STORE_new();
    X509_STORE_add_cert(cert_store, cert);

    STACK_OF(X509)* chain = sk_X509_new_null();
    sk_X509_push(chain, cert);

    // Verify
    X509_STORE_CTX* store_ctx = X509_STORE_CTX_new();
    X509_STORE_CTX_init(store_ctx, cert_store, cert, chain);

    int res = X509_verify_cert(store_ctx);
    printf("res=%d error=%d %s\n", res, X509_STORE_CTX_get_error(store_ctx),
      X509_verify_cert_error_string(X509_STORE_CTX_get_error(store_ctx)));

    X509_STORE_CTX_free(store_ctx);
    sk_X509_pop_free(chain, X509_free);
    X509_STORE_free(cert_store);
    X509_free(cert);

    return res == 1 ? 0 : 1;
}
```
</details>

The example code outputs `res=1 error=0 ok` with `1.1.1j` and `3.0.0-alpha11`, but outputs `res=-1 error=1 unspecified certificate verification error` with `3.0.0-alpha12`.

I've bisected to find https://github.com/openssl/openssl/commit/364246a986cd08e6b2b0e9ab8043ed2e2c505026 as the first failing commit and I think there are two separate issues here. The first problem is that somewhy `X509_get_pubkey_parameters` fails, and the second problem is that failures of the `X509_get_pubkey_parameters`  function in `verify_chain` is not handled correctly because `ctx->error` is not set. The first one causes an error, and it is unspecified because of the second one.

**Comment by t8m** [comment]
This is caused by RSA keymgmt returning 0 on rsa_has(OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS); IMO it should return 1 although OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS is not really meaningful on RSA.

**Comment by t8m** [comment]
Interestingly this seems to mean that we still use legacy keys when parsing X509 certs.

**Comment by t8m** [comment]
As for whether this should be anything else than X509_V_ERR_UNSPECIFIED - I am not sure about that, IMO it is OK as this should not be really a problem with real use-cases and this was simply a regression to be fixed. Also if you printed out the error stack contents it would give some additional hints.
