### ISSUE TITLE
Cannot duplicate EVP_PKEY with RSA with 3.0

### ISSUE THREAD

**Issue by ngg** [openssl/openssl#14501]
In OpenSSL 1.1.1, there was a way to duplicate EVP_PKEY objects (which were known to be RSA keys) by:
1. EVP_PKEY_get0/1_RSA()
2. duplicate the RSA* with RSAPublicKey_dup or RSAPrivateKey_dup
3. creating a new EVP_PKEY with the duplicated RSA key

In OpenSSL 3.0, the EVP_PKEY_get0/1_RSA functions and basically every function dealing with RSA* structs are deprecated.
What is the recommended way to achieve this without using these functions?

According to a really old email from https://www.mail-archive.com/openssl-users@openssl.org/msg17614.html there should be an EVP_PKEY_dup function which might be missing by accident.

**Comment by levitte** [comment]
From that email:
> > "Hmm no EVP_PKEY_dup() function? Thats an omission which will be fixed.
> > Steve."
> > 
> > Was it ever fixed, or is there a reason why this was dropped?
> ...
> Ooops, I forgot about that.

I never saw an EVP_PKEY_dup(), so I wouldn't be surprised if it was more or less permanently forgotten...

It may be time that we remember :wink:

**Comment by mattcaswell** [comment]
> It may be time that we remember

Definitely. Since this is lost functionality I've added this to the beta1 milestone.

**Comment by mattcaswell** [comment]
Incidentally do you actually *need* a new copy, or would an up-ref be sufficient via `EVP_PKEY_up_ref`?

**Comment by t8m** [comment]
If we made EVP_PKEYs fully immutable full copy would not be needed and up_ref would be sufficient, but until we still allow setting at least some parameters, I think we need full copy. For example to allow them to be modified in separate threads.

**Comment by mattcaswell** [comment]
> If we made EVP_PKEYs fully immutable full copy would not be needed and up_ref would be sufficient

Yes. Although in the case of RSA keys specifically (at least the RSA implementations from our own providers), they are immutable already once created (they do not support any settable parameters). So for that particular case up_ref should already be enough.

In fact there don't seem to be that many settable parameters for any of the key types with the notable exception of EC keys.

**Comment by ngg** [comment]
When we use an EVP_PKEY for a crypto operation, we have to make sure it is not freed before the operation completes, because EVP_PKEY_CTX does not hold a reference. We do it currently by duplicating the key and storing the new instance together with the other variables necessary for the operation.

Currently EVP_PKEY does not seem to be immutable, for example I can call EVP_PKEY_set1_RSA to change the rsa key. Because of this, we prefer a full copy over a reference, simply to avoid accidental bug in our software.

Having an up_ref function would still be great, if we can ensure in our own software that we use these EVP_PKEYs immutably, it would be a performance win over a copy.
