### ISSUE TITLE
Provider fetch not working as expected

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#14516]
I have a problem with fetching algorithms from a provider.
Either this is a bug, or my expectation is wrong :-)

I have implemented my own provider, lets call it "myprov". That provider implements some algorithms, but not all of them. I.e. it implements the KEYMGMT for RSA, RSA-PSS and EC, as well as the ASYM-CIPHER für RSA, and SIGNATURE for RSA, RSA-PSS, and EC. It uses `"provider=myprov"` as property for all the algorithms it implements. 

In an application I create new library context via `OSSL_LIB_CTX_new()`, load my provider `"myprov"` with that context, and also load the default provider into the same context. I then set that library context as default via `OSSL_LIB_CTX_set0_default()`. Furthermore, I set the default properties for that library context via `EVP_set_default_properties()` to `"?provider=myprov"` (myprov is optional but preferred).

The intention is that it fetches the algorithms from my provider, if it implements it, but falls back to the default provider for all the other algorithms. This is for implicit fetches, where no specific property query is specified (i.e. property query is NULL), or an older function from before provider support is used.

The application the generates a PKEY context to generate an RSA key via `EVP_PKEY_CTX_new_id(EVP_PKEY_RSA)` or `EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL)` followed by `EVP_PKEY_keygen_init()` and `EVP_PKEY_gen()`. I would expect that it fetches my provider for that, since it implements RSA (and the KEYMGMT key gen functions).  However, it is fetching the default provider. 

If I use `EVP_PKEY_CTX_new_from_name(NULL, "RSA", "provider=myprov")`, then it fetches mine, but I would have expected that it also fetches mine because of the default properties being "?provider=myprov". 

Is what I am trying to do supposed to work that way? 
Or how else can a provider implement only some algorithms, with a fallback to the default provider?

**Comment by paulidale** [comment]
What you are doing sounds correct.  Could you post your provider setup code (no need for the provider itself, just how you are putting all these pieces around it together)?

**Comment by ifranzki** [comment]
OK, see below some extracts from my code. Let me know if you want to see anything additional.
Its a secure key provider supporting HSM based asymmetric keys (RSA, EC), thus ist called "securekey".

I am running with latest from master, i.e. commit e66682a838a60351cf112830dee263862a1f9d10 "Prepare for 3.0 alpha 14", so its one commit ahead of openssl-3.0.0.-alpha13.

```
OSSL_LIB_CTX *securekey_libctx = NULL;
OSSL_LIB_CTX *previous_libctx = NULL;
OSSL_PROVIDER *securekey_provider = NULL;
OSSL_PROVIDER *default_provider = NULL;

#define SK_PROV_NAME			"securekey"

static const OSSL_ALGORITHM sk_prov_keymgmt[] = {
	{ "RSA:rsaEncryption", "provider="SK_PROV_NAME,
					sk_prov_rsa_keymgmt_functions },
	{ "RSA-PSS:RSASSA-PSS", "provider="SK_PROV_NAME,
					sk_prov_rsapss_keymgmt_functions },
	{ "EC:id-ecPublicKey", "provider="SK_PROV_NAME,
					sk_prov_ec_keymgmt_functions },
	{ NULL, NULL, NULL }
};

static const OSSL_ALGORITHM sk_prov_signature[] = {
	{ "RSA:rsaEncryption", "provider="SK_PROV_NAME,
					sk_prov_rsa_signature_functions },
	{ "ECDSA", "provider="SK_PROV_NAME,
					sk_prov_ecdsa_signature_functions },
	{ NULL, NULL, NULL }
};

static const OSSL_ALGORITHM sk_prov_asym_cipher[] = {
	{ "RSA:rsaEncryption", "provider="SK_PROV_NAME,
					sk_prov_rsa_asym_cipher_functions },
	{ NULL, NULL, NULL }
};

static const OSSL_ALGORITHM *sk_prov_query(struct sk_prov_ctx *provctx,
					   int operation_id, int *no_cache)
{
	if (provctx == NULL)
		return NULL;

	*no_cache = 0;

	pr_debug_ctx(provctx, "%s: provctx: %p operation_id: %d", __func__,
		     provctx, operation_id);

	switch (operation_id) {
	case OSSL_OP_KEYMGMT:
		return sk_prov_keymgmt;
	case OSSL_OP_SIGNATURE:
		return sk_prov_signature;
	case OSSL_OP_ASYM_CIPHER:
		return sk_prov_asym_cipher;
	}

	return NULL;
}

static const OSSL_DISPATCH sk_prov_dispatch_table[] = {
	{ OSSL_FUNC_PROVIDER_TEARDOWN, (void (*)(void))sk_prov_teardown },
	{ OSSL_FUNC_PROVIDER_GETTABLE_PARAMS,
				(void (*)(void))sk_prov_gettable_params },
	{ OSSL_FUNC_PROVIDER_GET_PARAMS, (void (*)(void))sk_prov_get_params },
	{ OSSL_FUNC_PROVIDER_QUERY_OPERATION, (void (*)(void))sk_prov_query },
	{ 0, NULL }
};
int sk_provider_init(const OSSL_CORE_HANDLE *handle, const OSSL_DISPATCH *in,
		     const OSSL_DISPATCH **out, void **provctx)
{
	OSSL_FUNC_core_get_libctx_fn *c_get_libctx = NULL;
	struct sk_prov_ctx *ctx;

	if (handle == NULL || in == NULL || out == NULL || provctx == NULL)
		return 0;

	for (; in->function_id != 0; in++) {
		switch (in->function_id) {
		case OSSL_FUNC_CORE_GET_LIBCTX:
			c_get_libctx = OSSL_FUNC_core_get_libctx(in);
			break;
		default:
			/* Just ignore anything we don't understand */
			break;
		}
	}

	if (c_get_libctx == NULL)
		return 0;

	ctx = OPENSSL_zalloc(sizeof(struct sk_prov_ctx));
	if (ctx == NULL)
		return 0;

	ctx->handle = handle;
	ctx->c_get_libctx = c_get_libctx;
	*provctx = ctx;

	*out = sk_prov_dispatch_table;
	return 1;
}


int SK_OPENSSL_init(bool debug)
{
	struct sk_prov_ctx *provctx;

	if (securekey_libctx == NULL)
		securekey_libctx = OSSL_LIB_CTX_new();
	if (securekey_libctx == NULL) {
		pr_debug(debug, "%s: OSSL_LIB_CTX_new failed", __func__);
		return -ENOMEM;
	}

	if (OSSL_PROVIDER_add_builtin(securekey_libctx, SK_PROV_NAME,
				      sk_provider_init) != 1) {
		pr_debug(debug, "%s: OSSL_PROVIDER_add_builtin failed",
			 __func__);
		return -EIO;
	}

	if (securekey_provider == NULL) {
		securekey_provider = OSSL_PROVIDER_load(securekey_libctx,
							SK_PROV_NAME);
		if (securekey_provider == NULL) {
			pr_debug(debug, "%s: OSSL_PROVIDER_load("SK_PROV_NAME
				 ") failed", __func__);
			return -EIO;
		}
	}
	provctx = OSSL_PROVIDER_get0_provider_ctx(securekey_provider);
	provctx->debug = debug;

	if (default_provider == NULL) {
		default_provider = OSSL_PROVIDER_load(securekey_libctx,
						      "default");
		if (default_provider == NULL) {
			pr_debug(debug, "%s: OSSL_PROVIDER_load(default) failed",
				 __func__);
			SK_OPENSSL_term();
			return -EIO;
		}
	}

	previous_libctx = OSSL_LIB_CTX_set0_default(securekey_libctx);
	if (previous_libctx == NULL) {
		pr_debug(debug, "%s: OSSL_LIB_CTX_set0_default failed",
			 __func__);
		SK_OPENSSL_term();
		return -EIO;
	}

	/* Prefer the secure key provider, but allow to fall back to default */
	if (!EVP_set_default_properties(securekey_libctx,
					"?provider="SK_PROV_NAME)) {
		pr_debug(debug, "%s: EVP_set_default_properties failed",
					 __func__);
		SK_OPENSSL_term();
		return -EIO;
	}

	pr_debug(debug, "%s: sk_provider support initialized, provctx: %p",
		 __func__, provctx);
	return 0;
}
```

Here is the debug output of my provider, for the following key gen code:
```
	EVP_PKEY_CTX *genctx;
	EVP_PKEY *pkey = NULL;

	genctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL); 
	printf("genctx: %p\n", genctx);
	if (genctx == NULL)
		return NULL;

	EVP_PKEY_keygen_init(genctx);
	EVP_PKEY_CTX_set_rsa_keygen_bits(genctx, 2048);

	EVP_PKEY_keygen(genctx, &pkey);

	EVP_PKEY_CTX_free(genctx);
	printf("pkey: %p\n", pkey);
```
Output:
```
openssl_seckey: DBG: SK_OPENSSL_init: sk_provider support initialized, provctx: 0x1a939f0
openssl_seckey: DBG: sk_prov_query: provctx: 0x1a939f0 operation_id: 10
genctx: 0x1ae0ee0
openssl_seckey: DBG: sk_prov_query: provctx: 0x1a939f0 operation_id: 5
openssl_seckey: DBG: sk_prov_query: provctx: 0x1a939f0 operation_id: 2
pkey: 0x1a98230
```
As you can see it is querying my provider for OSSL_OP_KEYMGMT (10) when generating the genctx, and furthermore queries my provider for OSSL_OP_RAND (5) and OSSL_OP_CIPHER (2) during key generation. 
My provider does support OSSL_OP_KEYMGMT for RSA, but not OSSL_OP_RAND, and not OSSL_OP_CIPHER.

Other than the query function, it does not call my provider, this would output additional debug messages. 
If I change the application code to use `genctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", "provider=securekey"); ` then it does call my provider and generate a key with my provider.

**Comment by levitte** [comment]
@paulidale, could there be a bug in the checks of optionals?

**Comment by paulidale** [comment]
@levitte it's possible.

@ifranzki, just a note: you don't need to create your own library context, just load your provider and the default provider into the default library context by passing NULL for the library context.

**Comment by ifranzki** [comment]
I debugged this and I guess the problem is within EVP_set_default_properties().

It is parsing the query, but does not create the names, if they do not already exist:

```
#0  ossl_property_string (t=0x14e4af0, pidx=0x0, s=0x3ffffffe7dc "securekey") at crypto/property/property_string.c:147
#1  0x0000000001170726 in ossl_property_value (ctx=0x14e44f0, s=0x3ffffffe7dc "securekey", create=0)
    at crypto/property/property_string.c:173
#2  0x000000000116e7d2 in parse_unquoted (ctx=0x14e44f0, t=0x3ffffffed48, res=0x14f9b30, create=0)
    at crypto/property/property_parse.c:247
#3  0x000000000116eb02 in parse_value (ctx=0x14e44f0, t=0x3ffffffed48, res=0x14f9b30, create=0)
    at crypto/property/property_parse.c:279
#4  0x000000000116f332 in ossl_parse_query (ctx=0x14e44f0, s=0x136d964 "securekey") at crypto/property/property_parse.c:428
#5  0x0000000001118102 in evp_set_default_properties_int (libctx=0x14e44f0, propq=0x136d95a "?provider=securekey", loadconfig=1)
    at crypto/evp/evp_fetch.c:406
#6  0x00000000011181b2 in EVP_set_default_properties (libctx=0x14e44f0, propq=0x136d95a "?provider=securekey")
    at crypto/evp/evp_fetch.c:415
#7  0x0000000001008c0c in SK_OPENSSL_init (debug=true) at sk_provider.c:2223
#8  0x0000000001003dac in main () at openssl_seckey.c:741
```
At frame 1-3, create is 0, so it won't create any names that do not already exist. I.e. the name "securekey" has not been created before, because it did not yet do anything with my provider that would have created that name.
As a result the parsed query string contains an invalid name index:

```
ossl_parse_query (ctx=0x14e44f0, s=0x136d96d "") at crypto/property/property_parse.c:431
*prop = {name_idx = 1, type = PROPERTY_TYPE_STRING, oper = PROPERTY_OPER_EQ, optional = 1, v = {int_val = 0, str_val = 0}}
```
--> v.str_val is zero !!!

Later on when matching the query strings, it fails to match that query in ossl_property_match_count(), because it won't match with any property definitions due to the invalid str_val in the parsed query.  So it does not match my provider, and thus goes on with the default provider.

**Comment by ifranzki** [comment]
> @ifranzki, just a note: you don't need to create your own library context, just load your provider and the default provider into the default library context by passing NULL for the library context.

Yes I know, but I will possibly use this in a environment where the default context or other library context's are already set up somehow, and I don't want to mess up with that. I have code that removes my library context when done, and restores the previous context.

**Comment by levitte** [comment]
Ah!  This is a chicken-and-egg sort of problem.

When parsing property definitions, we do create the value strings:

https://github.com/openssl/openssl/blob/8f08957674c2015fad72ea240bbff4564b83d518/crypto/property/property_parse.c#L359

However, when parsing property *queries*, we don't:

https://github.com/openssl/openssl/blob/8f08957674c2015fad72ea240bbff4564b83d518/crypto/property/property_parse.c#L428

Trouble is that queries are normally parsed before definitions, because fetches need the parsed query string first...

**Comment by ifranzki** [comment]
The following confirms my analysis:
By explicitly fetching a PKEY context with my provider first (to force that the name "securekey" is created), and then setting the default properties again, 'solves' the problem. It does now already find the name "securekey" and thus produce a valid parsed query. Any subsequent implicit fetches do then use my provider, as expected..
```
genctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", "provider=securekey");
EVP_PKEY_CTX_free(genctx);

EVP_set_default_properties(NULL, "?provider=securekey");

genctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL);
```

**Comment by levitte** [comment]
My educated guess is that if you change 0 to 1 on openssl/crypto/property/property_parse.c:428, things will start to work as expected.

**Comment by ifranzki** [comment]
Yes, that would probably fix it also. As mentioned above, If I force that the name is created by using an explicit query first, it also works to parse the default property correctly.

**Comment by levitte** [comment]
> As mentioned above, If I force that the name is created by using an explicit query first, it also works to parse the default property correctly.

Yes, absolutely...  the point is, *you shouldn't have to*

**Comment by levitte** [comment]
If you want to make a PR with the fix, we welcome it.

**Comment by paulidale** [comment]
Hmmmm, unforeseen side effect.

Not creating values on query is intentional to avoid contaminating the string database with values that can never be matched.  @levitte's suggestion would work but we'd also lose this feature.

I'll have to have a think of an alternative solution...

**Comment by levitte** [comment]
A possible solution would be to parse the query string after the array of OSSL_ALGORITHM has been processed.

**Comment by levitte** [comment]
In other words, we simply cannot pre-parse the default properties, that will have to be done when it's time to use them, i.e. late.  That will have to be done *every* time, 'cause the next query for an OSSL_ALGORITHM array may come with new property values, unseen until that point.

In view of that, I wonder of "contamination" isn't preferable after all...

**Comment by paulidale** [comment]
That's along the lines I was thinking of, the alternative would be to parse when the provider is loaded but even then there could be some oddities.

**Comment by t8m** [comment]
What is the real advantage of not contaminating the string database with items that cannot be matched? Frankly, I do not see much of it. To me it looks like a kind of premature optimization. I do not see hundreds of random property strings to be set as the default properties as a real and valid use-case.

**Comment by levitte** [comment]
I'm thinking like @t8m, that this optimization look like a bit of a micro-optimization, and while I do enjoy those as much as anyone, the trade-off doesn't look optimal...

**Comment by paulidale** [comment]
If a third party can ever specify the property query it becomes a DoS avenue.

The suggested change will impact every query, not just the default properties.  An extra argument to `ossl_parse_query` to distinguish the two cases might work.  I agree that the defaults aren't likely to be an issue.

**Comment by ifranzki** [comment]
I leave it totally up to you how to fix this, but I agree that an extra argument to ossl_parse_query() would be the best way to let only the default property query create the strings, but not a normal query.

**Comment by t8m** [comment]
Giving untrusted third party a way to specify arbitrary property query seems to me like an avenue for security issues regardless. But yeah, this proposal is OK.

**Comment by paulidale** [comment]
> Giving untrusted third party a way to specify arbitrary property query seems to me like an avenue for security issues regardless.

I'm not sure how -- they could pick an alternative implementation or cause a fetch to fail.  I agree that it is something that applications shouldn't do, but history shows that they will.

Anyway, I think adding the argument to create values for the global query is okay.  Algorithms are loaded into a store (which means their properties are parsed) before the query string is parsed.  The code assumes that parsing the query is a readonly operation, so making all queries create values would be bad.

**Comment by ifranzki** [comment]
I have cherrypicked the commit(s) from the PR and I can confirm that it fixes the problem.
Thanks a lot for the very quick turn around!
