### ISSUE TITLE
Failing the early FIPS install test cascades

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14523]
If the early FIPS installation test fails for any reason, a large number of later tests also fail.
It would be nice if just the first failed and the test run ceased.

**Comment by rsbeckerca** [comment]
I'm with you on that. What is the best way to abort the test run? I'm happy to contribute.

**Comment by levitte** [comment]
It may be that we want to stop if any of the sanity / internal / essential checks fail.  That's all the tests numbered 00-04.

**Comment by mattcaswell** [comment]
Fixed by #14320.
