### ISSUE TITLE
Building EVP_PKEY_CTX for Verification from raw parameters in OpenSSL 3.0

### ISSUE THREAD

**Issue by jtrillma** [openssl/openssl#14528]
Hi,

We are currently trying to migrate our code base to the OpenSSL 3.0 API alpha 13 and we have difficulty understanding how to build an `EVP_PKEY_CTX` to verify a signature.

Until now we took all the parameters of an EC curve (a, b, p, generator, order and cofactor), built an `EC_GROUP`, an `EC_KEY`, an `EVP_PKEY` and used that for the `EVP_PKEY_CTX`:

```c
EC_GROUP* group = EC_GROUP_new_curve_GFp(bn_p, bn_a, bn_b, 0);
EC_POINT* base_point = EC_POINT_new(group);
EC_POINT_oct2point(group, base_point, generator, sizeof(generator), 0);
EC_GROUP_set_generator(group, base_point, bn_order, bn_cofactor);
EC_KEY* ecKey = EC_KEY_new();
EC_KEY_set_group(ecKey, group);
EC_POINT* public_point = EC_POINT_new(group);
EC_POINT_oct2point(group, public_point, pub, sizeof(pub), 0);
EC_KEY_set_public_key(ecKey, public_point);

EVP_PKEY* evpPkey = EVP_PKEY_new();
EVP_PKEY_set1_EC_KEY(evpPkey, ecKey);
EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new(evpPkey, 0);
EVP_PKEY_verify_init(ctx);
EVP_PKEY_verify(ctx, signature, sizeof(signature), data, sizeof(data));
```

Working with EC_KEY directly is deprecated in OpenSSL 3.0 (EC_KEY_new, EC_KEY_set_group, EC_KEY_set_public_key, EVP_PKEY_set1_EC_KEY). We therefor tried to use the parameter interface:

```c
EVP_PKEY_CTX* gctx = EVP_PKEY_CTX_new_from_name(0, "EC", 0);

EVP_PKEY_verify_init(gctx);

OSSL_PARAM_BLD* bld = OSSL_PARAM_BLD_new();
OSSL_PARAM* params = 0;

if (bld == NULL
        || !OSSL_PARAM_BLD_push_BN(bld, "p", bn_p)
        || !OSSL_PARAM_BLD_push_BN(bld, "a", bn_a)
        || !OSSL_PARAM_BLD_push_BN(bld, "b", bn_b)
        || !OSSL_PARAM_BLD_push_BN(bld, "order", bn_order)
        || !OSSL_PARAM_BLD_push_BN(bld, "cofactor", bn_cofactor)
        || !OSSL_PARAM_BLD_push_octet_string(bld, "pub", pub, sizeof(pub))
        || !OSSL_PARAM_BLD_push_octet_string(bld, "generator", generator, sizeof(generator))
        || !OSSL_PARAM_BLD_push_utf8_string(bld, "field-type", fieldtype, sizeof(fieldtype))
        || (params = OSSL_PARAM_BLD_to_param(bld)) == 0)
{
    printf("Param builder failed\n");
    exit(1);
}

EVP_PKEY_CTX_set_params(gctx, params);

EVP_PKEY_verify(gctx, signature, sizeof(signature), data, sizeof(data));
```

The first way works, but is deprecated, the second is not, using the same parameters. What are we missing here? Are we missing a parameter, do we use the wrong name for the `EVP_PKEY_CTX` or are we simply not using the API as intended?

Another question: In https://www.openssl.org/docs/manmaster/man7/EVP_KEYMGMT-EC.html some parameters use `unsigned int` (a, b, p, order), but shouldn't it be `BIGNUM`? 

A simple example is attached. [ossl_example.zip](https://github.com/openssl/openssl/files/6129109/ossl_example.zip)

**Comment by paulidale** [comment]
> Another question: In https://www.openssl.org/docs/manmaster/man7/EVP_KEYMGMT-EC.html some parameters use `unsigned int` (a, b, p, order), but shouldn't it be `BIGNUM`?

Unsigned integer in this context doesn't specify a length.  A BIGNUM is allowed as would a byte.

**Comment by t8m** [comment]
You cannot set the key parameters on the EVP_PKEY_CTX. You need to use EVP_PKEY_fromdata() to create an EVP_PKEY from the data and then use that EVP_PKEY. Basically you'll keep the last three lines of your legacy code but you'll replace the rest with appropriately adjusted code from the example from the EVP_PKEY_fromdata(3) manpage.

**Comment by misery** [comment]
Thanks, this worked for us!

We are still unsure on how to use the static OSSL_PARAMs without a BIGNUM.

This works for us.
```
BIGNUM* p;
BN_bin2bn(mPrimeModulus->data, mPrimeModulus->length, p);
OSSL_PARAM_BLD_push_BN(bld, "p", p)
```

How to avoid a BIGNUM and use mPrimeModulus directly? Is that possible? What format is expected here? Our call to `EVP_PKEY_fromdata` fails.
```
params[0] = OSSL_PARAM_construct_BN("p", mPrimeModulus->data, mPrimeModulus->length);
...
params[n] = OSSL_PARAM_construct_end();
```

**Comment by t8m** [comment]
Unfortunately there is basically no nice and clean way how to use the static OSSL_PARAMs without a BIGNUM because the params must be in arch native byte order. So if you have regular big endian static data as what the bin2bn expects, you'd need to first convert it to little endian on little endian architectures before using the construct_BN call.

**Comment by mattcaswell** [comment]
From the documentation:

````
=item B<OSSL_PARAM_UNSIGNED_INTEGER>

The parameter data is an integer (signed or unsigned) of arbitrary
length, organized in native form, i.e. most significant byte first on
Big-Endian systems, and least significant byte first on Little-Endian
systems.
````

**Comment by misery** [comment]
Thanks!

Is it possible to fetch the parameters later? Just need for unit tests here.

It works for the "group".
```
EVP_PKEY_get_utf8_string_param(key.data(), "group", name, sizeof(name), &len);
```

But I cannot get a BN here.

```
EVP_PKEY_get_bn_param(key.data(), "a", &a)
EVP_PKEY_get_bn_param(key.data(), "b", &b)
EVP_PKEY_get_bn_param(key.data(), "p", &p)
```

**Comment by mattcaswell** [comment]
> But I cannot get a BN here.

Hmmm...assuming you are using a key type that recognises those parameter names (i.e. ec), that should be ok. We do this in our own tests here:

https://github.com/openssl/openssl/blob/6511f686c2c56d3ed68477981c1a3821bdc2e565/test/ectest.c#L2443-L2450

What happens when you try to do this?

**Comment by t8m** [comment]
It does not work for named groups - if the curve matches a named group it is automatically converted to a named group and the curve parameters are not retrievable for the named groups. I'd say it is a bug. I do not see a reason why you shouldn't be able to retrieve the parameters even for the named groups.

**Comment by mattcaswell** [comment]
> I'd say it is a bug. 

Sounds like a bug to me. You really should be able to do this.

**Comment by t8m** [comment]
@misery Would you please open a new issue for the ec parameters problem?

**Comment by misery** [comment]
Thanks for answer! I created a new issue: https://github.com/openssl/openssl/issues/14662
