### ISSUE TITLE
Library path "X64" folder doesn't exist

### ISSUE THREAD

**Issue by Bernardrouhi** [openssl/openssl#1453]
Hi, 

I'm trying to config the OpenSSL 1.0.1g to build Qt4.8.6  for Maya 2016, however in Maya documentation mention:

> OpenSSL
> -------
> 
> On Windows,  Qt needs a bit of help to have OpenSSL support for QtNetwork
> We dynamically link in the OpenSSL 1.0.1g build of OpenSSL.  the include and
> pre-built modules are provided in a parallel directory to the Qt source code
> 
> i.e.
>     d:\qt\4.8.6
>     d:\qt\openssl\1.0.1g
> 
> 	d:\qt\openssl\1.0.1g\include
> 	d:\qt\openssl\1.0.1g\x64
> 
> When configuring Qt will add in the command line options required to include
> these libraries
> 
> configure.exe [your normal options] -openssl -I <path to the OpenSSL includes> -L <path to the OpenSSL libraries>
> 
configure -debug-and-release -stl -no-qt3support -directwrite -openssl -plugin-sql-sqlite -I \qt\openssl\1.0.1g\include -L \qt\openssl\1.0.1g\x64 

 I downloaded `openssl-OpenSSL_1_0_1q.zip` from release tab and when i extract it, i can't find the library path, there is no folder name "x64", am i missing something?

**Comment by levitte** [comment]
It will appear when you install OpenSSL.  I believe the above was done by configuring OpenSSL as follows:

```
perl Configure --prefix=d:\qt\openssl\1.0.1g
```

and after it all has been built (`nmake ...` according to the usual instructions), you do this:

```
nmake -f ms\ntdll.mak install
```
