### ISSUE TITLE
openssl 3.0.0-alpha13 04-test_pem.t on Windows crash

### ISSUE THREAD

**Issue by gv74** [openssl/openssl#14530]
04-test_pem.t test crashes on Windows (two consecutive times). Command line from from process explorer is:
..\..\apps\openssl.exe x509 -text -noout -inform PEM -in ..\..\test\recipes\04-test_pem_data\cert-comment.pem

The crash dialog is the same as for the issue reported here: https://github.com/openssl/openssl/issues/13338

**Comment by t8m** [comment]
Could you please try with alpha13?

**Comment by gv74** [comment]
Sorry, wrong copy/paste from #13338 title. 

Tested with alpha13.
