### ISSUE TITLE
regression openssl ocsp "responder"? (master 2021-03-13) + crash (3.0.0 2021-10-20)

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#14547]
Currently PKIX-SSH ocsp regression test fail with:
> Responder Error: malformedrequest (1)

Not investigated in details yet.

**Comment by richsalz** [comment]
I believe this is a duplicate of #13904 which was closed in ef7ae359109c7c4edb252523d5ab1467ae1d2110 and should be closed.

**Comment by t8m** [comment]
@petrovr Could you please confirm that the ocsp test passes with the current master?

**Comment by petrovr** [comment]
Off topic:
It seems to me some works related to OCSP was done.
This based on fact that now "responder" outputs information like ACCEPT 0.0.0.0:20080. 
First error is that this "new" debug go to standard output instead error and before.
Second error is that adress is just plain wrong.


On topic.
Error sill exists with 2021-05-24 code.

Now I check standard error log from openssl ocsp command. It is full (~70) with simialar errors
```
0037E9BBE77F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:crypto/store/store_result.c:151:
```
before line:
```
ocsp: waiting for OCSP client connections...
```

**Comment by t8m** [comment]
Unfortunately to fix this we would need more information on where the issue is - preferably some constrained test case.

**Comment by petrovr** [comment]
It seem to me responder error now is crash. Dunno if original is fixed.

+++
Core was generated by `[TESTROOT]/testing-master_inplace/ssh ...
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f786c128bb8 in main_arena () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f786c128bb8 in main_arena () from /lib64/libc.so.6
#1  0x00007f786ca8bfed in BIO_free (a=0xce2ef0) at crypto/bio/bio_lib.c:147
#2  0x00007f786cbb0061 in OSSL_HTTP_REQ_CTX_free (rctx=0xce30f0) at crypto/http/http_client.c:127
#3  0x00007f786cbdbe63 in OCSP_sendreq_bio (b=b@entry=0xce41d0, path=<optimized out>, req=req@entry=0xcd84a0)
    at crypto/ocsp/ocsp_http.c:66
#4  0x000000000042875d in ssh_ocsp_get_response (req=0xcd84a0, conn=0xca0e60)
    at [TESTROOT]/origin-testing/ssh-ocsp.c:537
#5  ssh_ocsp_validate2 (cert=cert@entry=0xcd8660, x509store=x509store@entry=0xc9f1b0, ocsp=ocsp@entry=0xca0e60)
    at [TESTROOT]/origin-testing/ssh-ocsp.c:788
#6  0x0000000000429ad8 in ssh_ocsp_validate (cert=cert@entry=0xcd8660, x509store=0xc9f1b0)
    at [TESTROOT]/origin-testing/ssh-ocsp.c:1003
#7  0x00000000004270ac in ssh_x509store_verify_cert (cert=0xcd8660, untrusted=<optimized out>)
    at [TESTROOT]/origin-testing/x509store.c:1049
#8  0x000000000047d222 in xkey_validate_cert (k=k@entry=0xcd2eb0)
    at [TESTROOT]/origin-testing/ssh-x509.c:2019
#9  0x000000000042d6e3 in verify_host_key (host=0xca0630 "master.example.net", hostaddr=0x70aa20 <hostaddr>, 
    hostkey_alg=0xcd54f0 "x509v3-rsa2048-sha256", host_key=0xcd2eb0, cinfo=0xcd1db0)
    at [TESTROOT]/origin-testing/sshconnect.c:1483
#10 0x000000000042f699 in verify_host_key_callback (hostkey=<optimized out>, ssh=<optimized out>)
    at [TESTROOT]/origin-testing/sshconnect2.c:97
#11 0x000000000048d1f9 in kex_verify_host_key (ssh=ssh@entry=0xc9c170, server_host_key=0xcd2eb0)
    at [TESTROOT]/origin-testing/kex.c:1220
#12 0x000000000048f012 in input_kex_gen_reply (type=<optimized out>, seq=<optimized out>, ssh=0xc9c170)
    at [TESTROOT]/origin-testing/kexgen.c:171
#13 0x000000000046f86c in ssh_dispatch_run (ssh=ssh@entry=0xc9c170, mode=mode@entry=0, done=done@entry=0xc9ca70)
    at [TESTROOT]/origin-testing/dispatch.c:114
#14 0x000000000046f8c9 in ssh_dispatch_run_fatal (ssh=ssh@entry=0xc9c170, mode=mode@entry=0, done=done@entry=0xc9ca70)
    at [TESTROOT]/origin-testing/dispatch.c:134
#15 0x00000000004311d5 in ssh_kex2 (ssh=ssh@entry=0xc9c170, host=host@entry=0xca0630 "master.example.net", 
    hostaddr=hostaddr@entry=0x70aa20 <hostaddr>, port=port@entry=10022, cinfo=cinfo@entry=0xcd1db0)
    at [TESTROOT]/origin-testing/sshconnect2.c:243
#16 0x000000000042dc80 in ssh_login (ssh=0xc9c170, sensitive=0x709800 <sensitive_data>, orighost=<optimized out>, 
    hostaddr=0x70aa20 <hostaddr>, port=<optimized out>, pw=<optimized out>, timeout_ms=30000, cinfo=0xcd1db0)
    at [TESTROOT]/origin-testing/sshconnect.c:1631
#17 0x0000000000411234 in main (ac=<optimized out>, av=<optimized out>)
    at [TESTROOT]/origin-testing/ssh.c:1747
(gdb) 
+++

As result neither ssh daemon nor ssh client could reach responder.

For the record OSSL_HTTP_REQ_CTX_{new|free} does not look consitent . Dunno how this code pass approval.

**Comment by petrovr** [comment]
It seems to there is wish to update code in OpenSSL style not to correct bogus messages.

Todaw crash is not reprodusible and original issue (malformedrequest) mistically disaprear.
