### ISSUE TITLE
EC_KEY_* is not deprecated in manual pages

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#14545]
Command "grep EC_KEY_ util/libcrypto.num" output only ...DEPRECATEDIN_3_0.... but manual page list only EC_KEY_precompute_mult.

See for instance "https://www.openssl.org/docs/manmaster/man3/EC_KEY_get0_private_key.html"

**Comment by slontis** [comment]
I will go through the entire list - there is other ones also..
