### ISSUE TITLE
Alpha dependency on Perl IPC::Cmd

### ISSUE THREAD

**Issue by bwelling** [openssl/openssl#14541]
Testing 3.0.0alpha13, although the same issue happened with alpha12.

The build fails with `Can't locate IPC/Cmd.pm in @INC`.  NOTES.PERL says that Perl 5.10.0 is required (I have 5.10.1), and the only additional required module is Text::Template, which is also included in external/perl.

Is IPC.Cmd a requirement for building now?  If so, should it be documented and included in external/perl?

**Comment by levitte** [comment]
According to [corelist](https://perldoc.perl.org/corelist), it should be available in a regular perl distribution:

``` console
$ corelist IPC::Cmd

Data for 2021-01-23
IPC::Cmd was first released with perl v5.9.5
```

Note that there's a snag, which is mentioned in NOTES-PERL.md as well:

>  - on Linux distributions based on Debian, the package `perl` will
>    install the core Perl modules as well, so you will be fine.
>  - on Linux distributions based on RPMs, you will need to install
>    `perl-core` rather than just `perl`.
