### ISSUE TITLE
OpenVPN build issue: OpenSSL version too old

### ISSUE THREAD

**Issue by jackykwandesign** [openssl/openssl#14552]
So i just download the openVPN community, This is my step:
```
1. sudo apt update
2. sudo apt upgrade
3. sudo apt install build-essential
4. In the downloaded folder, sudo ./configure && make && make install
```

And then it run into this error
```
checking for OPENSSL... no
checking additionally if OpenSSL is available and version >= 1.0.2... configure: error: OpenSSL version too old
```

My System Info
OS:Ubuntu 20.04.2 LTS (desktop with GUI)
OpenVPN: 2.5.1
OpenSSL(apt-cache policy openssl): 
  Installed: 1.1.1f-1ubuntu2.2
  Candidate: 1.1.1f-1ubuntu2.2
  Version table:
 *** 1.1.1f-1ubuntu2.2 500
        500 http://hk.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1f-1ubuntu2 500
        500 http://hk.archive.ubuntu.com/ubuntu focal/main amd64 Packages
N: Ignoring file 'google-cloud-sdk.lis' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

As the OpenSSL version is latest, definitely not old, and this is a fresh installed OS, so no any duplicate version

**Comment by paulidale** [comment]
Perhaps ask the OpenVPN or OS folks about this?

**Comment by t8m** [comment]
Do you have the devel files for the openssl installed?

**Comment by jackykwandesign** [comment]
> Perhaps ask the OpenVPN or OS folks about this?

ops i post to the wrong repo ... thx for your reminder

**Comment by jackykwandesign** [comment]
> Perhaps ask the OpenVPN or OS folks about this?

but maybe, just may be anyone have the same case like me ?

**Comment by JJassonn69** [comment]
I have the same issue. Although I have openssl version 
` openssl version`
> OpenSSL 1.1.1f  31 Mar 2020 

any help ?

**Comment by paulidale** [comment]
This isn't an OpenSSL problem.....

**Comment by levitte** [comment]
You need to install the dev package, `libssl-dev`

**Comment by pengzhang018** [comment]
为什么

**Comment by pengzhang018** [comment]
openssl -devel 安装
