### ISSUE TITLE
Question on RSA engine and Key strength

### ISSUE THREAD

**Issue by bhatja1** [openssl/openssl#14568]
Hi All,

I am a RSA engine for OpenSSL to handle certificates up to 4096 bytes strength. However we do support certificates up to 8k.  
I read in the openssl documents as below

     **/* If this callback is NULL, the builtin software RSA key-gen will be
     * used. This is for behavioural compatibility whilst the code gets
     * rewired, but one day it would be nice to assume there are no such
     * things as "builtin software" implementations.
     */
    int (*rsa_keygen) (RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb);**

How do I make engine to handle key generation/encryption/decryption for certificates only up to 4K. And rest handled by OpenSSL itself.

Any help, inputs are appreciated. 

Thanks and Regards,
Jayalakshmi

**Comment by t8m** [comment]
Unfortunately there is no simple way to support this.
