### ISSUE TITLE
The -inform option is ignored because store does not support enforcement of encoding format

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14569]
The apps -inform option to choose whether input format is PEM or DER is currently ignored because store does not support enforcement of encoding format and tries to parse the input as PEM and if that fails it tries DER. This is useful behavior in case -inform option is not specified however there might be use cases (checking the correctness of the format) where the enforcement is needed.

There is also no CHANGES.md entry for the automatic behavior of the apps.

**Comment by mattcaswell** [comment]
I'd suggest `-inform` should be enforced where it is specified, and either form should be allowed if it is not specified.

**Comment by richsalz** [comment]
I am concerned about the security implications of trying multiple formats unless explicitly directed to do so.  I know the "read private key" functions (pre-3.0) try multiple key formats and are documented to do so.  Trying PEM, an ASCII format, and then trying DER, a binary format, worries me about security issues especially since DER encoding has historically been problematic.

**Comment by t8m** [comment]
PEM is just base64 encoded DER. The DER decoder MUST be safe anyway. IMO this concern does not make any sense.

**Comment by richsalz** [comment]
I was just using the PEM and DER as examples.  I don't know details of what chaining the STORE stuff does. Perhaps it does other types of chaining like the pre-3.0 "read private key" stuff does.

>The DER decoder MUST be safe anyway.

Yes. But asserting something doesn't make it so.  Fuzzing helps, but still ...  Glad you're not concerned.  I am.

**Comment by t8m** [comment]
Aargh! The code doing the DER decoding is used when parsing the PEM files anyway. That's what I meant by using it separately having no additional security impact.

**Comment by richsalz** [comment]
Yes, I know PEM calls DER :)  Are there other fallback chains within store that might be concerning?  I don't know.  That's the point I was trying to make.

**Comment by t8m** [comment]
IMO this cannot be fixed without API changes so I think we need to reconsider this. And IMO it is worth fixing before beta1.

@levitte What do you think about this approach?

Add an OSSL_PARAMS argument to OSSL_STORE_open_ex and OSSL_STORE_attach. Add a OSSL_STORE_CTX parameter "input-type" which would be then applied to the decoder context when it is created. In apps apply this parameter when appropriate.

**Comment by levitte** [comment]
This is only tied to the file: scheme. If someone wrote an ldap: store loader, then the input type is completely irrelevant. So I'm frankly unsure about making that an OSSL_PARAM thing, and wonder if it could be retrofitted into the uri, like an appended `?input-type=DER`.

This is not a finished thought.

**Comment by t8m** [comment]
On the other hand we might say that -inform is not ignored only with files. I would not think that would be too restrictive.

**Comment by levitte** [comment]
I'm not sure what you're saying there...  most other schemes would most probably have a well known format(s), and completely different indication what format to expect, so they have no need for an `-inform` hint.  The whole guessing game is very much a file: scheme thing, especially originally.

**Comment by t8m** [comment]
Then why an OSSL_PARAM set and forwarded to stores that internally would ignore it or forward to the OSSL_DECODER would be wrong and adding ?input-type to file uris would be better? I see the OSSL_PARAM(s) as potential hints given they are ignored if unknown.
