### ISSUE TITLE
Engine algorithms unregistration after calling ENGINE_by_id

### ISSUE THREAD

**Issue by longagofaraway** [openssl/openssl#14572]
After commit a5c864c a call to ENGINE_by_id will register all the algorithms of an engine. But who is expected to call ENGINE_unregister_(ciphers|digests|...)? We have an engine, and it is not doing the unregistration itself. Should we start doing it now?

**Comment by levitte** [comment]
As far as I recall, there is no need.  The tables where they are registered are destroyed when the ENGINE is destroyed, so they simply "disappear".  All the engine needs to do is to destroy the methods themselves, in the function registered with `ENGINE_set_destroy_function()`

**Comment by longagofaraway** [comment]
There are still references to the engine remaining, so the destroy function is not called. For example, if we call EVP_PKEY_new_mac_key, then free the key and then deinitialize the engine (ENGINE_finish, ENGINE_free), in ENGINE_free we just decrement reference count. But if we additionally call ENGINE_unregister_pkey_asn1_meths, then the destroy function will be called. Similarly, if we use EVP_EncryptInit_ex, then we'll need to call ENGINE_unregister_ciphers afterwards.

**Comment by longagofaraway** [comment]
So I looked further into the code to find the reason for the additional reference. Inside the call to `EVP_PKEY_new_mac_key` in our engine's handler pmeth->keygen we call `EVP_PKEY_assign`. Inside it there's a call to `EVP_PKEY_type`, after which the engine's reference count is increased. The increase happens in `ossl_engine_table_select`, and is only decreased after the call to `ENGINE_unregister_pkey_asn1_meths`.
So is there something wrong with the call to EVP_PKEY_assign? Or should the engine just call unregistration method itself during deinitialization now?

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
