### ISSUE TITLE
SSL_CTX_new is unexpectedly changing the current library context

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#14593]
`SSL_CTX_new()` and `SSL_CTX_new_ex()` does change the current library context to the initial default library context under some circumstances:

`SSL_CTX_new_ex()` calls `ssl_ctx_system_config()` which in turn calls `ssl_do_config()`. In `ssl_do_config()`, somewhere in the middle of the function, it uses `OSSL_LIB_CTX_set0_default()` to set the current library context to the one from the SSL context, and remembers the previous library context in `prev_libctx`. Further down (at the `err` label) it restores the previous library context to what it was before (i.e. `prev_libctx`).

So far so good, but if the function fails early, i.e. before initially setting the library context via `OSSL_LIB_CTX_set0_default()`, it did not change the current library context, and thus did not remember the previous context,  but at the `err` label it unconditionally restores the previous library context to `prev_libctx`, which is then NULL.  

However, calling `OSSL_LIB_CTX_set0_default()` with NULL changes the current library context to the initial default library context. So if a different library context was set up before and set as current one, it is now no longer the current one. It should not be assumed that calling `OSSL_LIB_CTX_set0_default` with NULL would be a no-op.

In my case it is failing at `conf_ssl_name_find()` to find the `"system_default"`, for whatever reason. It then goes to the `err` label and thus changes the current library context to NULL. Since I loaded my own provider only into my own library context, it won't find my provider from now on.

This problem was introduced with commit 6725682d77510bf6d499957897d7be124d603f40 as far as I can tell.

There are some other similar places with similar invalid restoring of the default library context:
- `SSL_load_client_CA_file_ex()` (ssl/ssl_cert.c) unconditionally restores the library context at the done label.  If the function fails early, it also calls `OSSL_LIB_CTX_set0_default`  with NULL (also since commit 6725682d77510bf6d499957897d7be124d603f40).
- `ASYNC_start_job()` (crypto/async/asyc.c) sets and restores the library context, but if `async_fibre_swapcontext()` fails, it did change the library context, but does not restore the previous one at the err label (since commit 6c689e58f70726cfa5533bc10f9669abce199fb8).

**Comment by ifranzki** [comment]
I am actually not sure if the code in `ssl_do_config()` works as intended in the non-error case. 

It takes the desired library context from the SSL context and the calls `OSSL_LIB_CTX_set0_default()` with that.
However, the library context in the SSL context could be NULL. Calling `OSSL_LIB_CTX_set0_default()` with NULL will set the initial default context, but I guess that the intention is to behave the same as the `EVP_xxx_fetch()` routines: If the specified library context is NULL, then it uses the thread's current default library context (i.e. the one you get from `ossl_lib_ctx_get_concrete()`). 

So I guess the fix is to add a NULL check in front of **both** `OSSL_LIB_CTX_set0_default()` calls. If the desired library context from the SSL context is NULL, then don't call `OSSL_LIB_CTX_set0_default()`, the current default context is already set. At the `err` label, when restoring the previous library context, and the previous library context is NULL, then also don't call `OSSL_LIB_CTX_set0_default()`, since we did not change it at the first place, and thus no restoration is needed.

```
    SSL_CONF_CTX_set_flags(cctx, flags);
    if (libctx != NULL)                                   <---- add this line
        prev_libctx = OSSL_LIB_CTX_set0_default(libctx);
    for (i = 0; i < cmd_count; i++) {
        char *cmdstr, *arg;

        conf_ssl_get_cmd(cmds, i, &cmdstr, &arg);
        rv = SSL_CONF_cmd(cctx, cmdstr, arg);
        if (rv <= 0) {
            int errcode = rv == -2 ? SSL_R_UNKNOWN_COMMAND : SSL_R_BAD_VALUE;

            ERR_raise_data(ERR_LIB_SSL, errcode,
                           "section=%s, cmd=%s, arg=%s", name, cmdstr, arg);
            goto err;
        }
    }
    rv = SSL_CONF_CTX_finish(cctx);
 err:
    if (prev_libctx != NULL)                              <---- add this line
        OSSL_LIB_CTX_set0_default(prev_libctx);
    SSL_CONF_CTX_free(cctx);
    return rv <= 0 ? 0 : 1;

```

A similar fix is needed in `SSL_load_client_CA_file_ex()`, I guess it should also behave like the `EVP_xxx_fetch()`  routines in regards of the library context passed to the function.

**Comment by t8m** [comment]
I think your analysis is correct. Would you like to submit a PR?

**Comment by ifranzki** [comment]
Submitted a PR, see above. 

I did not touch ASYNC_start_job() (crypto/async/asyc.c) as I don't know that code good enough to decide if and how this needs to be fixed.

**Comment by t8m** [comment]
> Submitted a PR, see above.
> 
> I did not touch ASYNC_start_job() (crypto/async/asyc.c) as I don't know that code good enough to decide if and how this needs to be fixed.

I'd just add `ctx->currjob->libctx = OPENSSL_CTX_set0_default(libctx);` before the `goto err;` to restore the previous libctx.

**Comment by t8m** [comment]
maybe with additional `if (libctx != NULL)` before both these calls as that NULL indicates failure of the original set call.

**Comment by t8m** [comment]
I'll submit PR for that one.

**Comment by ifranzki** [comment]
`libctx = OSSL_LIB_CTX_set0_default(ctx->currjob->libctx);`

Can `ctx->currjob->libctx` be NULL? If so, then you don't want to callOSSL_LIB_CTX_set0_default at all, because that would set the initial lib context, but that's possibly not what is desired?

**Comment by mattcaswell** [comment]
> Can ctx->currjob->libctx be NULL?

No. That isn't possible (except in an error condition).
