### ISSUE TITLE
KTLS enable

### ISSUE THREAD

**Issue by mincymathew** [openssl/openssl#14595]
With openssl 3.0, is ktls implicit to SSL_Write? Or should SSL_sendfile be called instead? 
In the application, BIO_get_ktls_send(SSL_get_wbio(ssl)) returns 0. Is there any change needed to be made in the application with respect to the client/server socket after the handshake is done?
I have built openssl 3.0 against kernel 5.11 with ktls enabled. (Some of the tests in openssl are failing. But I do see an increment in tls_stat counters.  )

**Comment by mattcaswell** [comment]
KTLS will be used if:

- OpenSSL has been compiled with the "enable-ktls" option
- KTLS has not been explicitly disabled at run time via `SSL_MODE_NO_KTLS_TX` and `SSL_MODE_NO_KTLS_RX`
- You are using a suitable KTLS aware BIO (`BIO_s_connect()`, or `BIO_s_socket()`)
- KTLS is compatible with the ciphersuites, TLS protocol versions and extensions that have been negotiated (this may vary from one platform to another based on kernel support)

If any of these are not true then it will fallback to normal OpenSSL managed TLS.

You don't need to do anything special in your code. `SSL_write` will just do the right thing if the above conditions are met. You don't need to call `SSL_sendfile`

**Comment by kaduk** [comment]
> You are using a suitable KTLS aware BIO (BIO_s_connect(), or BIO_s_socket())

Note that there are some BIOs out in the wild that are buggy and claim success for the `BIO_CTRL_SET_KTLS` and related control options, which results in openssl thinking the kernel will apply TLS record protection but the kernel not actually doing so (and thus, the messages going over the wire in plaintext).  This will usually be immediately obvious due to a failure to interoperate with a proper TLS implementation, but given the potential loss of confidentiality seems worth calling out.

The only buggy BIO types I know about are in Apache serf and Apache ssl_engine_io.c, but I also haven't been on the front lines for this.  Tagging @bsdjhb to check if there were others that are known.

**Comment by t8m** [comment]
> This will usually be immediately obvious due to a failure to interoperate with a proper TLS implementation, but given the potential loss of confidentiality seems worth calling out.

Another good reason for #13794

**Comment by bsdjhb** [comment]
The two in Apache (really two copies of the same code) are the only ones I have encountered.  I've tried to be proactive about cc'ing @kaduk on anything I come across.  For reference, the two upstream bug reports are https://issues.apache.org/jira/browse/SERF-198 and https://bz.apache.org/bugzilla/show_bug.cgi?id=65160.  I do agree that #13794 is a good idea.

**Comment by mincymathew** [comment]
So I have a TCP socket that is getting upgraded to a TLS socket when a ClientHello is found. Then a BIO gets added using BIO_new. BIO_new_socket is not called here (which would have implicitly enabled ktls). So, I tried explicitly enabling ktls by calling setsockopt(fd, SOL_TCP, TCP_ULP, "tls", sizeof("tls"))). This succeeds but BIO_get_ktls_send still says its disabled. What am I missing here?

**Comment by bsdjhb** [comment]
The setsockopt (which isn't portable btw), just asks the Linux kernel to permit the later socket options performed in t1_enc.c during negotiation to provide the cipher suite and session keys to the kernel.  Only once that other socket option succeeds does BIO_get_ktls_send() return true.  What kind of BIO are you adding?  It would have to support the relevant KTLS-related requests in the BIO class's ctrl method to support KTLS.  For example, the KTLS requests in bss_sock.c.

**Comment by bsdjhb** [comment]
Oh, one other note is that #13794 won't actually address the issue with broken custom BIO_ctrl methods unless BIO_get_ktls_send() were to inline the check of the enable/disable setting before invoking BIO_ctrl().  Also, the bugs I've found in apache and serf affect other new BIO_ctrl operations (such as the EOF one added in 3.0 and merged back in 1.1.1<mumble>), though a false positive on the EOF check may have less drastic consequences, so I'm not sure it makes sense to try to inline the enable/disable check in BIO_get_ktls_send() but instead use the enable/disable check as the current ones are used today to gate whether the setsockopt() to enable KTLS is attempted at all.
