### ISSUE TITLE
libeay32.dll and ssleay32.dll are not generated for OpenSSL compilation on Windows-10

### ISSUE THREAD

**Issue by am185352** [openssl/openssl#14619]
We are the premium customers for OpenSSL 1.0.2 version and we are trying to build OpenSSL 1.0.2y and facing an issue where the DLLs are not generated for the ARM platform when compiled on Windows-10. (Same issue when tried to build OpenSSL 1.0.2r, which succeeded when built on Windows-7 previously)

The DLLs are generated when compiled for other platforms like NT, NT-VS10, NT-VS15, CE-X86, CE-SHX

I have a Windows XP Virtual machine and an official Windows-10 build machine. The ARM version OPENSSL DLLs are generated on the former but not on the latter, which is our official build machine. The build does not fail nor it generates errors but succeeds and misses the binaries for ARM platform.

I am attaching two build log files:
  1. One is from official build machine. This is a large file where the OpenSSL code is built on multiple platforms listed above and only the DLLs from ARM platform are not getting generated (OPENSSL.exe is still generated fine on ARM platform). The DLLs for other versions are generated fine without issues.
  2. On XP virtual machine, I just built only for ARM platform without any additional differences but we can see that the binaries are indeed generated.

If you could quickly compare two log files using a comparison tool like Beyond Compare, we can see that it seems to be failing to create a directory however I think this is because there are no DLLs generated beforehand. The comparison screenshot which is also attached shows the difference **(perl util/mkdir-p.pl "C:\OpenSSL_Arm") is the first line that is not executed or missing on Windows-10)**
On Windows 10, am seeing 'install' is up-to-date message around the above line execution time. Looks like the below is the script line which is behaving differently:
nmake -f ms\cedll_ARM.mak INSTALLTOP=C:\OpenSSL_ARM install

(Before the above line: this is executed move /Y ms\cedll.mak ms\cedll_ARM.mak)
[Arm.log](https://github.com/openssl/openssl/files/6168647/Arm.log)

[build.log](https://github.com/openssl/openssl/files/6168649/build.log)
![Comparison](https://user-images.githubusercontent.com/69016645/111731881-c93b5b80-884a-11eb-9e2d-38e67c67a4d1.JPG)

**Comment by mattcaswell** [comment]
Hello. Premium support customers need to use a different route for raising support requests. Please email me directly for information on how to do that. My contact details are on this page:

https://www.openssl.org/community/omc.html

**Comment by mattcaswell** [comment]
Closing this as it is being handled via premium support.
