### ISSUE TITLE
Deprecated low level key API's that have no replacements

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#14616]
Whilst updating the documentation related to deprecation's I noticed the following had no replacements..
Should these be supported?

DH:

void DH_clear_flags(DH *dh, int flags);
 int DH_test_flags(const DH *dh, int flags);
 void DH_set_flags(DH *dh, int flags);

The flag DH_FLAG_CACHE_MONT_P is not accessible.
DH_FLAG_TYPE_DHX, DH_FLAG_TYPE_DH - EVP_is_a() for the test_flags, not sure set or get should be used.

DH *DH_get_1024_160(void);
DH *DH_get_2048_224(void);
DH *DH_get_2048_256(void);
Maybe these are not that useful - the DH gen handles these as RFC5114 types as a group name - I have updated the docs to reflect this.

DSA:
void DSA_clear_flags(DSA *d, int flags);
int DSA_test_flags(const DSA *d, int flags);
void DSA_set_flags(DSA *d, int flags);
DSA_FLAG_CACHE_MONT_P

DH *DSA_dup_DH(const DSA *r) - maybe not useful externally?
DSAparams_dup()

RSA:

void RSA_clear_flags(RSA *r, int flags);
int RSA_test_flags(const RSA *r, int flags);
void RSA_set_flags(RSA *r, int flags);
Flags
RSA_METHOD_FLAG_NO_CHECK
RSA_FLAG_CACHE_PUBLIC
RSA_FLAG_CACHE_PRIVATE
RSA_FLAG_BLINDING
RSA_FLAG_THREAD_SAFE - cant see this used..
RSA_FLAG_EXT_PKEY
RSA_FLAG_NO_BLINDING - related to the blinding functions below

RSA_get_version()

int RSA_blinding_on(RSA *rsa, BN_CTX *ctx);
void RSA_blinding_off(RSA *rsa);
BN_BLINDING *RSA_setup_blinding(RSA *rsa, BN_CTX *ctx) - I assume there will be no replacement for this.

RSAPrivateKey_dup()
RSAPublicKey_dup()

**Comment by paulidale** [comment]
The OTC needs to make a decision on these as soon as possible so they can be scheduled in or not.

**Comment by t8m** [comment]
IMO none of these are worth it except the DH_get_length which would be easy to add as gettable.

The dup functions will be replaced by EVP_PKEY_dup which I am working on.

**Comment by levitte** [comment]
What does DH_get_length actually do? Do we have something corresponding somewhere else?

**Comment by t8m** [comment]
Actually we have a OSSL_PKEY_PARAM_DH_PRIV_LEN which gives you exactly this value from an EVP_PKEY. So we already have a replacement.

**Comment by levitte** [comment]
> Actually we have a OSSL_PKEY_PARAM_DH_PRIV_LEN which gives you exactly this value from an EVP_PKEY. So we already have a replacement.

Ah, right, no I remember what that was for...

(btw, what was that again about immutable keys?)

**Comment by slontis** [comment]
> Actually we have a OSSL_PKEY_PARAM_DH_PRIV_LEN which gives you exactly this value from an EVP_PKEY. So we already have a replacement.

Removed from list - it was inside a define...

**Comment by paulidale** [comment]
OTC: document that these functions have no replacement.
add a "blinding=yes" to the appropriate algorithms.
