### ISSUE TITLE
engine sign/verify fail (master 2021-03-21)

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#14632]
Now openssl utilites could create keys, certificates and PKCS#12(#13826) files used in E_NSS regression tests.
Unfortunately simple cross sign and verify tests fail when operation uses engine. The error in both cases is one and the same:
```
Error setting context
00172A651C7F0000:error:03000086:digital envelope routines:do_sigver_init:initialization error:crypto/evp/m_sigver.c:94:
```

**Comment by t8m** [comment]
Could you please paste here the relevant part of the application code? I wonder why the evp_pkey_ctx_is_legacy() test does not work correctly.

**Comment by petrovr** [comment]
[sign-ec1-sha256.out-openssl_1_1_1_stable.log](https://github.com/openssl/openssl/files/6185095/sign-ec1-sha256.out-openssl_1_1_1_stable.log)
[sign-ec1-sha256.out-openssl_master.log](https://github.com/openssl/openssl/files/6185097/sign-ec1-sha256.out-openssl_master.log)

Attached logs , trace build and debug level 3. The difference is after line TRACE[e_nss] nss_load_key(): ^ pkey=...
In 1.1.1 stable next is "TRACE[e_nss] nss_ecdsa_do_sign():  ..." while master calls are 
```
TRACE_E_NSS:nss_ec_init()  ...
TRACE_E_NSS:nss_ec_init()  idx: 1, ptr: 0xefb470
TRACE_E_NSS:nss_ec_init()  ^ ok
TRACE_E_NSS:NSS_KEYCTX_free_ec()  idx: 1, ptr: 0xefb470
Error setting context
00D752636C7F0000:error:03000086:digital envelope routines:do_sigver_init:initialization error:crypto/evp/m_sigver.c:94:
```

**Comment by petrovr** [comment]
For protocol test case is https://gitlab.com/e_nss/e_nss/-/blob/master/tests/sign-ec1-sha256.test , uncommented DEBUG in  openssl.cnf.in , and build with  preprocessor flags  -DENABLE_CALL_TRACE and  -DENABLE_NSS_TRACE  .

**Comment by t8m** [comment]
The load of the pkey through the OSSL_STORE does not set the engine pointer for some reason. I need to investigate further.

**Comment by petrovr** [comment]
Tomáš Mráz wrote:
> The load of the pkey through the OSSL_STORE does not set the engine pointer for some reason. I need to investigate further.

NSS and CAPI engines are not "default" engines. With other words "engine" method is not set when key is created.
In "engine load" code assign engine method.

But if engine method is lost by "STORE" code ....

Note that NSS engine support OpenSSL STORE API and engine has a command that list certificates. It is indicated by E_NSS_STORE_LOADER definition in configuration header.
Dunno what is error but "list" test pass. May be is not related to real issue.


Regards,
Roumen Petrov

**Comment by t8m** [comment]
So the problem is not in OSSL_STORE but in that we do not recognize the low-level engine based keys properly and do not handle them as legacy.

**Comment by petrovr** [comment]
Tomáš Mráz wrote:
> So the problem is not in OSSL_STORE but in that we do not recognize the low-level engine based keys properly and do not handle them as legacy.
> 

Hmm, actually then issue is not new one.
When I report this one https://github.com/openssl/openssl/issues/9915 I note one thing - the author have no idea how OpenSSL uses keys.

Before master there was no need to mark keys external or internal or etc.
It is expected do set any private attribute - operation (functional) on key method should do the work.

About public attributes - usually it is not required to set them for operations.
It is good to set public attribute as program code my decide to use them outside operation. For instance before 1.1 (1.1.1) openssl utilites lack pubout argument. i.e. output of "external keys" is not correct.

Another same in use of identity in ssh authentication process.

Third because key method will be used only in signing operation - must be external.


Tomáš,
You wrote low-level engine but the world is not only engine keys.

This report is for engine but I have another set of key methods - https://gitlab.com/secsh/pkixssh/-/blob/master/ssh-pkcs11-client.c .

So I hope that team could find a proper way how to push a key to "key manager".


Regards,
Roumen Petrov


P.S. About one year I drop plan to support OpenSSL 3.0 in PKIX-SSH due to amount of errors. Direct pkcs11 support will be tested with 3.1 API, i.e. provider based implementation.
I home that engine functionality will be restored before 3.0 release and so PKIX-SSH could use pkcs#11 engine as work-around if direct is broken.
