### ISSUE TITLE
"PEM_read_bio_PrivateKey" returns null when passing a base64 bio parameter

### ISSUE THREAD

**Issue by wawbin** [openssl/openssl#14631]
platform:android
openssl version:3.0.0-alpha11

The bug occurs when
```
const char *PrivateKey_file = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t....";  //pem file content with base64 encode
BIO *privateKey_mem = BIO_new_mem_buf(PrivateKey_file, strlen(PrivateKey_file));
BIO *b64 = BIO_new(BIO_f_base64());
BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
BIO *buffer = BIO_new(BIO_f_buffer());
BIO_push(b64, privateKey_mem);
BIO_push(buffer, b64);
EVP_PKEY *privateKey = PEM_read_bio_PrivateKey(buffer, nullptr, nullptr, nullptr); //privateKey is always null
```
I do not know if it is a bug,I use the same way to call PEM_read_bio_X509, it works perfect.

then,I try to put the data into a file and read it,it works perfect,too.
```
const char *PrivateKey_file = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t....";  //pem file content with base64 encode
BIO *privateKey_mem = BIO_new_mem_buf(PrivateKey_file, strlen(PrivateKey_file));
BIO *b64 = BIO_new(BIO_f_base64());
BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
BIO *buffer = BIO_new(BIO_f_buffer());
BIO_push(b64, privateKey_mem);
BIO_push(buffer, b64);
BIO *f1=BIO_new_file("/data/data/appname/cache/pri","w+");
char bb[9999];
while (BIO_gets(buffer,bb,9999)!=0){
        BIO_puts(f1,bb);
}
BIO_flush(f1);
BIO_reset(f1);
EVP_PKEY *privateKey = PEM_read_bio_PrivateKey(f1, nullptr, nullptr, nullptr); //It works ok
```

**Comment by levitte** [comment]
I tried both variants, both against my 1.1.1 installation and my 3.0 installation, and both worked without flaw.  Not sure what happens in your case.

Would you mind adding this to your program, to see if it prints anything?

``` C
ERR_print_errors_fp(stderr);
```

**Comment by wawbin** [comment]
> I tried both variants, both against my 1.1.1 installation and my 3.0 installation, and both worked without flaw. Not sure what happens in your case.
> 
> Would you mind adding this to your program, to see if it prints anything?
> 
> ```c
> ERR_print_errors_fp(stderr);
> ```

This function print nothing when calling PEM_read_bio_PrivateKey,but print "null parameter" when calling SSL_CTX_use_PrivateKey.

But luckily,I try to update to the newest version alpha13 just now,the program works normally,I think it is a bug in alpha11 version.

I have another question about BIO for a long time.

BIO_new(BIO_f_cipher()) return a cipher bio,after I having used it,I call BIO_pop()、BIO_reset()、BIO_set_cipher() and BIO_push() to try to reuse it,but it can not output anydata anymore.What happen in this case?

**Comment by mattcaswell** [comment]
> But luckily,I try to update to the newest version alpha13 just now,the program works normally,I think it is a bug in alpha11 version.

Ok great. Closing this then.

> BIO_new(BIO_f_cipher()) return a cipher bio,after I having used it,I call BIO_pop()、BIO_reset()、BIO_set_cipher() and BIO_push() to try to reuse it,but it can not output anydata anymore.What happen in this case?

Please create a new issue for a different question.
