### ISSUE TITLE
 can't resolve symbol '__ctype_b_loc'

### ISSUE THREAD

**Issue by 0neday** [openssl/openssl#14643]
I have cross compile stunnel using openssl-1.1.1j support
but when I load config file for stunnel, get this errors

```
EchoLife_WAP ~ # stunnel  ss-client.conf
/mnt/jffs2/app/bin/stunnel: can't resolve symbol '__ctype_b_loc'
EchoLife_WAP ~ # stunnel
[ ] Initializing inetd mode configuration
[.] stunnel 5.58 on arm-unknown-linux-gnu platform
[.] Compiled/running with OpenSSL 1.1.1j  16 Feb 2021
[.] Threading:FORK Sockets:POLL,IPv4 TLS:ENGINE,OCSP,SNI
[ ] errno: (*__errno_location ())
[!] Invalid configuration file name "/mnt/dists/stunnel/etc/stunnel/stunnel.conf"
[!] realpath: No such file or directory (2)

```
my uclibc version is 
`/lib/libuClibc-0.9.34-git.so`

**Comment by mattcaswell** [comment]
It looks like this is an issue you would be better addressing to the stunnel developers rather than us.

**Comment by 0neday** [comment]
> It looks like this is an issue you would be better addressing to the stunnel developers rather than us.

yes, I found commit #include <ctype.h> could fix `can't resolve symbol '__ctype_b_loc'`
is there any method to commit all #include <ctype.h>

**Comment by paulidale** [comment]
This is still a question better asked for the stunnel developers.
