### ISSUE TITLE
Support for Attribute Certificate RFC-5755

### ISSUE THREAD

**Issue by mwiseman32** [openssl/openssl#14648]
Please add support for Attribute Certificates per RFC-5755.

**Comment by henkbirkholz** [comment]
I know these are busy times, but that would be quite awesome!

+1

**Comment by mattcaswell** [comment]
Previous request for this in #13793.

**Comment by dhobsong** [comment]
Hi, I am also interested in this feature (including the command line support mentioned in #13793), and I'm just wondering generally what would be involved in implementing this.  It seems like the main tasks would be implementing a new type for Attribute Certificates (X509_ACERT or maybe just ACERT?) with APIs for:
* serialization (d2i_ / i2d_)
* verification
* setting / getting attributes.  

Then implementation of a subcommand of `openssl` to be able to also use these APIs from the command line.

Does that sound like it would be the general gist of it?

**Comment by FdaSilvaYY** [comment]
@dhobsong : see #2759 or more recently #11216 for inspiration.

Your new attributes should be parseable from configuration file too.

A better path should be:
  -  serialization (d2i_ / i2d_) : depends on DECLARE* and IMPLEMENT macros
  -  setting / getting attributes. : add the corresponding accessors
   - config parsing : to declare default attributes for new certificates
this will be a large PR, i bet.

And in a second PR submission,  you could add :
   - apps : command line support if needed ...
   - verification : 
so the review process will be light-weighted

**Comment by dhobsong** [comment]
@FdaSilvaYY Sorry, for my late reply. 
Thanks very much for the pointers.  I'll look into it some more.

**Comment by dhobsong** [comment]
I've put together a draft PR covering the first set of features described above.  It is still early to think about merging, (no documentation, needs more error code handling), but if there are any comments on the current state, they would be appreciated. 

One thing that hasn't been touched on yet, but I mention in the PR comment, is that the Attributes described in RFC 5755 use ASN.1 SEQUENCEs in the Attribute values.  There is a nice mechanism for handling X509 EXTENSIONs based on their OID for generating / parsing ASN.1 SEQUENCEs, but I haven't been able to find anything similar of X509 ATTRIBUTEs.

**Comment by arapov** [comment]
openssl/openssl#15857

**Comment by t8m** [comment]
The feature PR was merged! :rocket:
