### ISSUE TITLE
ECDHE_RSA_WITH_AES_256_GCM_SHA384 supprt in openssl 1.1.1i

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#14644]
Hi,

I recently upgraded the libraries of my application.
In brief it is an application that is capable of acting both as a client and server.
A third party library provides the required functionalities.
For secure communication the library relies on openssl.
This time I built the third party library using openssl1.1.1i version.
Everything works smoothly except for one scenario.

I set my application to work in server mode and I select ECDHE_RSA_WITH_AES_256_GCM_SHA384 cipher suite.
From another test application that acts as a client, I try to establish an association with my server application.
I set up the client to use another cipher suite (anything but ECDHE_RSA_WITH_AES_256_GCM_SHA384).
My expectation is that the association will get rejected due to cipher mismatch.
But it always connects and establishes association with my server.
This issue is noticed only when ECDHE_RSA_WITH_AES_256_GCM_SHA384 is selected at my server side.
Is there any known issue for this cipher suite or could it be an issue with the third party library?
I did some dig up on the third party tool code and saw SSL_accept() being called.
But it returned success even with mismatched ciphers.

Could any one provide some hint or information?
Any info is highly valued as it will help me analyze the scenarios further.
Thanks in advance.

Regards,
Amal

**Comment by mattcaswell** [comment]
> This time I built the third party library using openssl1.1.1i version.

What was the previous version of OpenSSL?

If it was something less that OpenSSL 1.1.1 (e.g. 1.0.2 or 1.1.0) then it is likely that this issue is due to the use of TLSv1.3 ciphersuites. 1.1.1 supports TLSv1.3 and the ciphersuites for this protocol version are quite different to the ciphersuites from previous versions and are configured independently. Unless you have explicitly disabled TLSv1.3 and its ciphersuites then an OpenSSL server will automatically be able to negotiate TLSv1.3, and will use one of the TLSv1.3 ciphersuites - regardless of your configuration of the TLSv1.2 ciphersuites.

**Comment by amaljesudas** [comment]
Hi Matt,

Thanks for checking on my question.
The last time the third party library was built, we used openssl 1.0.2n version.
As you mentioned, this issue could be because TLSv1.3 is being negotiated.
I have so far not thought on these lines as ECDHE_RSA_WITH_AES_128_GCM_SHA256 did not show similar issue.
Let me try if I can disable TLSv1.3 support.

Please comment if you think there is some other possibility also.

Regards,
Amal

**Comment by amaljesudas** [comment]
Hi Matt,

I checked after disabling TLSv1.3 support, but the issue still exists.
The scenario was analyzed using Wireshark.
It could be seen that even when ECDHE_RSA_WITH_AES_256_GCM_SHA384 is set at server side, the Server Hello message was always using the cipher suite that we set at client side.
i.e. if we set DHE_RSA_WITH_AES_256_GCM_SHA384 at client side, this cipher suite is seen in the Client Hello message.
There is no association rejection and the response Server Hello message also contains the cipher suite DHE_RSA_WITH_AES_256_GCM_SHA384.

I am still unable to confirm if this behavior is due to change in openssl or due to some issue in third party library.

Regards,
Amal

**Comment by mattcaswell** [comment]
> I select ECDHE_RSA_WITH_AES_256_GCM_SHA384 cipher suite.

How are you selecting this ciphersuite? I wonder if there is some problem with the way that you are doing this which means that the configuration doesn't "take", and therefore you are just using the default ciphersuite list.

**Comment by amaljesudas** [comment]
Hi @mattcaswell 

Finally found the culprit.
It was a comparison logic mistake that was causing no cipher suite to be set at server side.
Thanks for your time and sorry for the trouble.

I am closing this issue.

Regards,
Amal

**Comment by amaljesudas** [comment]
Not an issue.
It was an internal code logic mistake of the application.

**Comment by mattcaswell** [comment]
Great. Glad you got it sorted.
