### ISSUE TITLE
stdin is missing(no output), when using the engine to do digest.

### ISSUE THREAD

**Issue by jiaqizho** [openssl/openssl#14653]
here is my test code 

when i create the EVP_MD by nid : 
```
int res = 1;
if ((md = EVP_MD_meth_new(nid, 0)) == NULL) {
        WARN("Failed to allocate cipher methods for nid %d\n", nid);
        return NULL;
}
res &= EVP_MD_meth_set_init(md, my_sha1_init);
res &= EVP_MD_meth_set_update(md, my_sha1_update);
res &= EVP_MD_meth_set_final(md, my_sha1_final);
res &= EVP_MD_meth_set_cleanup(md, my_sha1_cleanup);
res &= EVP_MD_meth_set_flags(md, MY_FLAG);
res &= EVP_MD_meth_set_app_datasize(md, sizeof(MY_CTX));
```

and then in method `my_sha1_final`
```
static int my_sha1_final(EVP_MD_CTX* ctx, unsigned char* md)
{
    // here is the SHA1 code
    memcpy(md,sha1_result,size);
    LOG(sha1_result);
    return 1
}
```

then i do the test :
```
echo "Hello" | apps/openssl dgst -sha1
echo "Hello" | apps/openssl dgst -sha1 -engine myengine
```

**Then the result will output in my log , but it won't show in the (stdin) ,** like this: 
```
engine "myengine" set.
(stdin)=
```

and my openssl version is 1.1.1f , not sure is thisproblem with my code or a problem with openssl.

Thanks

**Comment by jiaqizho** [comment]
is anybody have seen this bug ?

**Comment by paulidale** [comment]
I very much suspect the problem is in your _LOG_ function.  Without seeing it there is nothing anyone can to do assist.

**Comment by levitte** [comment]
@paulidale says:
> Where does the `engine "myengine" set.` message come from?

https://github.com/openssl/openssl/blob/f775b5c4857d1fef67f487c2ec6017b1f1c6eb19/apps/apps.c#L1317
