### ISSUE TITLE
Unexpected behavior in i2d_PrivateKey and i2d_PublicKey

### ISSUE THREAD

**Issue by bhess** [openssl/openssl#14655]
The behavior of `int i2d_PrivateKey(EVP_PKEY *a, unsigned char **pp)` and `int i2d_PublicKey(EVP_PKEY *a, unsigned char **pp)` seems to be unexpected with some inputs, and different compared to the legacy variants (e.g. `i2d_ECPrivateKey`).

1. Case: if `pp != NULL` and `*pp == NULL`

The data is successfully stored in *pp, but the return value is close to `INT_MAX`.

The likely casue is in

https://github.com/openssl/openssl/blob/6511f686c2c56d3ed68477981c1a3821bdc2e565/crypto/asn1/i2d_evp.c#L59-L62

I believe that `ret = (int) len;` should be set if `pp == NULL || *pp == NULL` holds at the beginning of `i2d_provided`.

2. Case: if `pp != NULL` and `*pp != NULL`

The return value is correct, but `*pp` points to a location after the stored data.

The likely cause is

https://github.com/openssl/openssl/blob/6511f686c2c56d3ed68477981c1a3821bdc2e565/crypto/encode_decode/encoder_lib.c#L116

If there is no reason for incrementing the pointer, the line could be removed.

The described behavior occurs in master (6511f686c2c56d3ed68477981c1a3821bdc2e565).

**Comment by t8m** [comment]
May be fixed by #14647

**Comment by t8m** [comment]
Please disregard the above comment. That is a similar issue in d2i.

**Comment by kaduk** [comment]
This sounds pretty similar to 1d73e2adae9c80d359d6d85c9f65d97a86add542 on the face of things.

**Comment by slontis** [comment]
> If there is no reason for incrementing the pointer, the line could be removed.

The behavior of d2i and i2d is described in doc/man3/d2i_X509.pod.
See the WARNINGS section.. (Forgetting this is fairly perilous :))

**Comment by levitte** [comment]
Good catch!  Fix in #15277.  @bhess, would you please try it out?

**Comment by bhess** [comment]
Thanks @levitte for the fix! I tried it and it works fine.

> The behavior of d2i and i2d is described in doc/man3/d2i_X509.pod.
> See the WARNINGS section.. (Forgetting this is fairly perilous :))

Thanks @slontis for pointing to this. Indeed, this documents that the pointer is incremented when `*p != NULL`. The second case I described isn't an issue in this case.

Ok for me to close the issue with the fix in #15277.
