### ISSUE TITLE
Update 3.0 wiki with current status

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#14663]
The status section of https://wiki.openssl.org/index.php/OpenSSL_3.0 hasn't been updated comprehensively in quite a while - e.g. it still shows the decoders as missing.

Aside from the updated status, updating the page might also unearth topics that haven't been explicitly milestoned for beta1 yet - e.g. there's a comment that "EVP_KEYMGMT [misses] functionality for loading HSM keys", and it's unclear to me from searching issues & PRs if this was done already.

Similarly for "9.4 Library Context/Provider implementation support in other OpenSSL APIs", where e.g. #11422 sounds relevant but hasn't been milestoned yet.

**Comment by h-vetinari** [comment]
This should IMO still be milestoned for - at the very least - 3.0.0. The link to the wiki is in all the version announcements (most recently [alpha15](https://mta.openssl.org/pipermail/openssl-project/2021-April/002608.html)), and having it that out of date is surely not beneficial for the goal of people testing the betas / rcs.

**Comment by t8m** [comment]
IMO the current intention is to drop this page and have all this information in a migration guide document.

**Comment by h-vetinari** [comment]
Makes sense; then it's just the link in the announcement email that needs to change. ;-)

**Comment by richsalz** [comment]
I added text to the front of the page that says:
```
READ ME FIRST:

The project is planning on having a FIPS 140-2 (not 140-3) validated module which means that the schedule is driven by the NIST deadline for 140-2 which is near the end of September, 2021.

The team is focused on development, and this page is somewhat out of date, in terms of content and schedule. It is expected that much of the content here will be in the FIPS, or other, documentation in the 3.0 release.

The current list of items being worked on, can be found at their Kanban board, [1]. The list of items that must be done for 3.0 ("blockers") can be found at [2]. The list of items that are "nice to have" but not committed can be found at [3] 
```

I think that is good enough that this issue can be closed.

**Comment by h-vetinari** [comment]
Sure. Wasn't aware of the Zenhub link, good to know!

**Comment by h-vetinari** [comment]
> [...] then it's just the link in the announcement email that needs to change. ;-)

@mattcaswell, the alpha16 announcement still points to the wiki; would you like me to open an issue to change the announcement text for beta1?

**Comment by mattcaswell** [comment]
> @mattcaswell, the alpha16 announcement still points to the wiki; would you like me to open an issue to change the announcement text for beta1?

Please do. Until #14710 is merged though I think the wiki link is better than nothing.
