### ISSUE TITLE
Automatically set library path on NonStop for testing

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#14666]
The NonStop platform has a proprietary mechanism for loading DLLs. This involves the environment variable `_RLD_LIB_PATH`, which should contain the location of the `libcrypto.so` and `libssl.so` files. Modification is requested of `util/shlib_wrap.sh.in` to account for this.

The case statement should include a separate condition for `NONSTOP_KERNEL` to construct and export the variable in question.

**Comment by rsbeckerca** [comment]
I am working on this.

**Comment by levitte** [comment]
Why should the condition be needed?  Just modify the variable along with the others that are already there...

**Comment by levitte** [comment]
...  and now that I've seen the comment in your change, I see why
