### ISSUE TITLE
Build information in OPENSSL_ia32cap.pod

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#14674]
Information about advanced assembler stuff is in `doc/man3/OPENSSL_ia32cap.pod`  It doesn't belong there.  It should be in `INSTALL.md` somewhere.

**Comment by levitte** [comment]
You're talking about the NOTES?  Agreed, and that should probably end up in a NOTES file.  INSTALL.md is made fairly detail agnostic for a reason

**Comment by amatyuko-intc** [comment]
About the NOTES and the paragraph above it. But it seems like we don't have OS independent NOTES file to put such stuff into. May be additional entry in Notes section in the INSTALL.md is not that bad option.

**Comment by levitte** [comment]
> May be additional entry in Notes section in the INSTALL.md is not that bad option.

I saw your addition, and yeahok, it's fine.

Side notes:

> But it seems like we don't have OS independent NOTES file to put such stuff into.

Hmmm, NOTES-PERL.md? :wink:
There's also the option of making a new one.  It's permitted to make new files.

**Comment by amatyuko-intc** [comment]
Yeah, there's a PERL file, but looking at its content it seems it has a bit different purpose. As to a new file, I couldn't come to an agreement with myself regarding its naming and its purpose, so I just made yet another section in INSTALL.md. ;)
