### ISSUE TITLE
Doubt: Virtual Machines and cipher suites

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#14681]
Hi,

This is just a general query related to cipher suites and virtual machines.
I have an application that uses openssl 1.1.1i version for handling secure connections.
It is capable of functioning both as a client and server.
I have tested both the server and client functioning of my application using independent test applications.
It works as expected.
Now I try to test using two instances of my application where one will be the client and the other the server.
I run my application as server from my machine and the second instance(client) I run from a virtual machine.
This testing is failing as the connection gets established even when server and client sides are configured with different cipher suites.
On analysis I am seeing that the client hello message contains cipher suites that I have not configured anywhere in my application.
For example, if I set TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 at the client side, the client hello is seen to contain the below cipher suites:
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

I am using the virtual machine environment for the first time for testing this scenario.
Can anyone shed light on why this is happening?

Thanks in advance.

Regards,
Amal

**Comment by t8m** [comment]
These are the TLS-1.3 ciphersuites. They cannot be disabled through the SSL_CTX_set_cipher_list() call. There is a new SSL_CTX_set_ciphersuites() call that can configure those. Or, if you do not want TLS-1.3 support at all, you should disable the TLS-1.3 support via the SSL_CTX_set_max_proto_version() call.

**Comment by amaljesudas** [comment]
Hi Tomáš,

Thanks for the reply.

I tried SSL_CTX_set_max_proto_version() call through my 3rd party library.
Still I am seeing 5 cipher suites in the client hello message.
Below is the Wireshark capture details for the same:

Transport Layer Security
    TLSv1.3 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 263
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 259
            Version: TLS 1.2 (0x0303)
            Random: 4e20c2afe985fdc06c5c752711cd231a41c3444d5bac5f2f606109113d0bff2b
            Session ID Length: 32
            Session ID: 435aea540976b065164373a6d8930e7686153b7b2408a904a7d63ca50ae6f5ba
            Cipher Suites Length: 10
            Cipher Suites (5 suites)
                Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
                Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
                Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
                Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 176
            Extension: ec_point_formats (len=4)
            Extension: supported_groups (len=28)
            Extension: session_ticket (len=0)
            Extension: encrypt_then_mac (len=0)
            Extension: extended_master_secret (len=0)
            Extension: signature_algorithms (len=26)
            Extension: supported_versions (len=9)
            Extension: psk_key_exchange_modes (len=2)
            Extension: key_share (len=71)

Will disabling TLS1.3 with no-tls1_3 flag during openssl build help?
Also, any idea why Wireshark lists the Version: TLS 1.2 (0x0303) even though it is TLS1.3 protocol?

Please excuse my limited knowledge on the same.

Regards,
Amal

**Comment by t8m** [comment]
This does not look like a client hello with disabled TLS-1.3. Apparently for some reason your SSL_CTX_set_max_proto_version() call did not work. I'd recommend trying to investigate that further. You need to call it on the SSL_CTX before you start using it. The Version: TLS 1.2 (0x0303) is correct even for TLS-1.3 this is according to the TLS-1.3 spec and it is done like this to avoid breaking TLS-1.3 by broken middleboxes.

**Comment by amaljesudas** [comment]
Hi @t8m

Yes, I too suspect that the SSL_CTX_set_max_proto_version() did not function as expected.
Have limitations investigating what went wrong since the call was made through a third party library API.
Still will try to figure out what went wrong with SSL_CTX_set_max_proto_version() call.
Thanks again for your observations.

As a side note, disabling TLS1.3 during openssl build did help.

Regards,
Amal

**Comment by amaljesudas** [comment]
Hi @t8m

We updated source code of third party library to include separate API for setting max proto version.
After calling this API, we were able to disable the TLS-1.3 as suggested by you.
Thanks for the support.

Regards,
Amal
