### ISSUE TITLE
RSA_X931_generate_key_ex is much slower than before (on average double the time)

### ISSUE THREAD

**Issue by qunying** [openssl/openssl#14688]
Hi,
With the attach patch (1.1.1-stable branch)  `openssl genrsa -x 4096` could be used to generate X931 compliance key.

I found that after the checked in of  [Constant-time GCD function](https://github.com/openssl/openssl/commit/ef599605040bc5c1a426ccd83d58cd0dd294509f), the generation of X931 key is much slower, my simple test on an linux i7-8700 X86_64 shows that on average it double the time it needs to generate the key, while
normal RSA key generation seems not affected that much.
This is the test result I collected comparing 1.1.1 and 1.1.1k for X931 4096 key, numbers are in seconds:
`openssl1.1.1k 0.250 1.681 1.778 0.664 2.915 1.673 1.313 2.442 2.746 3.926
0.799 0.865 2.728 ~ average 1.829 second

openssl1.1.1  0.496 0.476 1.412 0.827 0.560 0.306 1.216 0.385 0.702 0.734
0.257 1.693 1.094 ~ average 0.781 second`

[x931.patch.gz](https://github.com/openssl/openssl/files/6206986/x931.patch.gz)

On slower machine, the difference is much longer, for previously keys could be generated within around 2 minutes, now it took more than 10 minutes.

Not sure if this is intentional or the side effect of the GCD patch.

**Comment by paulidale** [comment]
Secure or fast?  Which is more important to our users?

**Comment by richsalz** [comment]
I don't see why keygen is doing constant-time things, but to answer the question: secure is more important.

**Comment by t8m** [comment]
There were definitely attacks against some key generation algorithms that due to using some non-const-time operations were able to infer the private key generated.

**Comment by richsalz** [comment]
> There were definitely attacks against some key generation algorithms that due to using some non-const-time operations were able to infer the private key generated.

Got a link or search terms I could try?  I mean, keygen is inherently not constant time.

**Comment by qunying** [comment]
According to [https://github.com/openssl/openssl/issues/10111] (Deprecate X9.31? #10111), X931 is depreciated, so RSA_generate_key_ex() should be used, which does not have the problem.
