### ISSUE TITLE
Sign pre-calculated hash using "openssl cms"

### ISSUE THREAD

**Issue by zuiderkwast** [openssl/openssl#14686]
Allow hash-then-sign as two separate operations.

With large files, hashing them (repeatedly) takes notable time. If signatures can be generated on a hash instead of the original file, it simplifies the following scenarios:

* Generating test signatures repeatedly of large files
* Re-signing large files with multiple different keys
* Splitting the processing of the signature away from the processing of the format of the final signature (CPU and I/O load of hashes vs. key calculations that are done in a different part of a larger pipeline, leading to lowered network transfer cost when the large file can be left behind)

Raw RSA signatures can already be hash-then-sign split with `openssl pkeyutl`, but there is no equivalent option available for CMS signatures yet.

**Idea:** Add a command line argument `-digest HASH` which, if provided, is used instead of hashing a file provided as `-in FILE`. The hash is given in hexadecimal format on the command line (suggestion), but it can be a filename if you prefer.

**Example:**

```sh
openssl dgst -sha256 -out helloworld.sha256 helloworld.txt | \
    awk '{printf $2}' > helloworld.sha256.hex

openssl cms -sign -binary -digest $(cat helloworld.sha256.hex) \
    -inkey private-key -keyform PEM -out output-file.sig \
    -outform DER -signer public-key-certificate -keyid \
    -certfile ca-certs-to-be-included
```

Would this be an acceptable feature?

**Comment by zuiderkwast** [comment]
I can add that signing gigabyte files while at the same time running the signing software in a smaller secure area (Trusted Platform Module, secure enclave, etc.) can be enabled by this feature.

Signed software packages in CMS format is already part of at least one telecom standard: https://www.etsi.org/deliver/etsi_gs/NFV-SOL/001_099/007/03.03.01_60/gs_NFV-SOL007v030301p.pdf, e.g. section 5.4 "Signature of individual artifacts".

**Comment by agaryen** [comment]
👍 
I have pretty much the same use case, but using the C functions. 
We had to hack them to pass down a char *hash instead of a BIO * of a file, and remove the hashing step.

We'd be happy to help if this improvement is considered to be implemented.

**Comment by zuiderkwast** [comment]
Thanks @agaryen! Yes we want to implement it. Are you using `CMS_sign()` or CMS_sign_ex()`? Since those are part of the C API, I guess we can't change them directly, but we'd have to add another `CMS_sign_digest()` which does this. What do you think?

**Comment by agaryen** [comment]
It's exactly what we're doing in our fork.
```c
CMS_ContentInfo *CMS_sign_digest(X509 *signcert, EVP_PKEY *pkey,
                          STACK_OF(X509) *certs, char *md_data, int md_length,
                          unsigned int flags)
```

Maybe there's a smarter way to do it rather than duplicating all the functions code until the one that actually does the signing, but we went for the fastest route for now.

**Comment by bjosv** [comment]
Ah, interesting. Is your fork public?

**Comment by agaryen** [comment]
Nowp, but it's really straightforward. We just commented the blocks of code that generate the hash and add it to the signature.

**Comment by Sunita1987-coder** [comment]
Hi Team
We have requirement to sign binaries using openssl cms feature. As I can see the discussion in this forum there is no parameters available to pass digest into cms. Can you please share how currently openssl cms sign is working ? Something like the equivalent  bash script like below , where we can pass digest to the below script which is getting signed using rsautl. Can you please help me same stuff for cms signings.



#!/bin/bash
# @(#) Bash script demos difference between openssl rsautl and dgst signing
# Usage: $0 <name of file to sign> <private key file, without passphrase>

# 1. Make an ASN1 config file

cat >asn1.conf <<EOF
asn1 = SEQUENCE:digest_info_and_digest

[digest_info_and_digest]
dinfo = SEQUENCE:digest_info
digest = FORMAT:HEX,OCT:`openssl dgst -sha256 $1 |cut -f 2 -d ' '`

[digest_info]
algid = OID:2.16.840.1.101.3.4.2.1
params = NULL

EOF

# If you are wondering what the "algid = OID:2.16.840.1.101.3.4.2.1" is, it's
# the SHA256 OID, see http://oid-info.com/get/2.16.840.1.101.3.4.2.1

# 2. Make a DER encoded ASN1 structure that contains the hash and
# the hash type
openssl asn1parse -i -genconf asn1.conf -out $1.dgst.asn1

# 3. Make a signature file that contains both the ASN1 structure and
# its signature
openssl rsautl -sign -in $1.dgst.asn1 -inkey $2 -out $1.sig.rsa

# 4. Verify the signature that we just made and ouput the ASN structure
openssl rsautl -verify -in $1.sig.rsa -inkey $2 -out $1.dgst.asn1_v

# 5. Verify that the output from the signature matches the original
# ASN1 structure
diff $1.dgst.asn1 $1.dgst.asn1_v

# 6. Do the equivalent of steps 1-5 above in one "dgst" command
openssl dgst -sha256 -sign $2 -out $1.sig.rsa_dgst $1

# 7. Verify that the signature file produced from the rsautl and the dgst
# are identical
diff $1.sig.rsa $1.sig.rsa_dgst

**Comment by t8m** [comment]
It is currently not possible to sign a hash using `openssl cms`. This issue is about adding such feature.

**Comment by Sunita1987-coder** [comment]
Can we have the details command line /  bash script how currently cms calculates the hash of the input and generating the signature.

**Comment by Sunita1987-coder** [comment]
> Nowp, but it's really straightforward. We just commented out the blocks of code that generate the hash and add it to the signature.
 What's your plan to release this feature ?
Also can you please share how current cms signings process. Mostly interested in the bash script where we can pass hash directly to generate the signature, to avoid huge size files to upload

**Comment by Sunita1987-coder** [comment]
> It is currently not possible to sign a hash using `openssl cms`. This issue is about adding such feature.

--> any ETA when this feature will available in public ?
Also can you help with the bash script how cms signing working internally.

**Comment by berlin4apk** [comment]
im facing the same problem,
together with singed iPXE network boot images (large ISO and wim image files),
its relay time and cpu intensive.
