### ISSUE TITLE
EVP_CipherInit_ex(ctx, NULL, NULL, NULL, NULL, -1) no longer resets IV in CBC mode

### ISSUE THREAD

**Issue by bartonjs** [openssl/openssl#14704]
I haven't verified with a minimal repro, but while testing with OpenSSL 3 alpha 13, it looks like `EVP_CipherInit_ex` with a `NULL` IV no longer restores `oiv` as the IV:

OpenSSL 1.1.1:

If IV is provided, copy over oiv.  After that, either way, copy oiv over IV.

https://github.com/openssl/openssl/blob/122e5f7c010859f0b2984d553fa45cd1f18a6fc4/crypto/evp/evp_enc.c#L179-L188

OpenSSL 3(a13):

Generic init only calls initiv when an IV was given.

https://github.com/openssl/openssl/blob/88df2c0b3d6162971304c06a240deb9320c9ae67/providers/implementations/ciphers/ciphercommon.c#L187-L190

Since nothing ever copied oiv over iv, the iv continues as it was when reset was called, a change from previous versions (except when an engine is used, which hits the compatibility fallback).

A quick test using the deprecated `EVP_CIPHER_CTX_original_iv` function fixed the issue for AES, 3DES, DES, and RC2 for both CBC and CFB (all applicable sizes).

**Comment by sahanaprasad07** [comment]
@t8m Hello, would it be possible to add tmp:HIGH label for this one?
.NET builds are blocked by this issue.
Thank you.

**Comment by bartonjs** [comment]
@sahanaprasad07 I wouldn't say we're blocked.  If this is the most important failure in your ingestion testing for OpenSSL 3, ping me our issue for the workaround patch.

**Comment by t8m** [comment]
This is already selected for this sprint.

**Comment by bartonjs** [comment]
Hey, @t8m.  I pulled down the current master this morning (aed03a12096cbcce30a133c179336072fdad64d1) and this seems to have maybe regressed again?

The only time that I'm seeing cipher_generic_init_internal get called is in mode 5/CTR (from the RNG?).  For a context built on EVP_des_ede3_cbc I'm seeing the theoretical IV reset code at `tdes_init`

```
(lldb) bt 4
* thread #13: tid = 11806, 0x00007fff46a4b4cc libcrypto.so.3`tdes_init(vctx=0x00007fff30005810, key=0x0000000000000000, keylen=0, iv=0x0000000000000000, ivlen=0, params=0x0000000000000000, enc=1) + 112 at cipher_tdes_common.c:77, name = '.NET Long Runni', stop reason = step over
  * frame #0: 0x00007fff46a4b4cc libcrypto.so.3`tdes_init(vctx=0x00007fff30005810, key=0x0000000000000000, keylen=0, iv=0x0000000000000000, ivlen=0, params=0x0000000000000000, enc=1) + 112 at cipher_tdes_common.c:77
    frame #1: 0x00007fff46a4b5d9 libcrypto.so.3`ossl_tdes_einit(vctx=0x00007fff30005810, key=0x0000000000000000, keylen=0, iv=0x0000000000000000, ivlen=0, params=0x0000000000000000) + 76 at cipher_tdes_common.c:97
    frame #2: 0x00007fff4691ad1a libcrypto.so.3`evp_cipher_init_internal(ctx=0x00007fff30002530, cipher=0x00007fff3c11d3f0, impl=0x0000000000000000, key=0x0000000000000000, iv=0x0000000000000000, enc=1, params=0x0000000000000000) + 1187 at evp_enc.c:213
    frame #3: 0x00007fff4691b3f9 libcrypto.so.3`EVP_CipherInit_ex(ctx=0x00007fff30002530, cipher=0x0000000000000000, impl=0x0000000000000000, key=0x0000000000000000, iv=0x0000000000000000, enc=-1) + 76 at evp_enc.c:389
```

https://github.com/openssl/openssl/blob/b9cd82f95bf99eab4e1b0420918e7139db091c4b/providers/implementations/ciphers/cipher_tdes_common.c#L77-L80

**Comment by t8m** [comment]
@bartonjs it did not regress again, it's just that the original fix fixed it only for everything except DES and 3DES.
