### ISSUE TITLE
test/pkits-test.pl not suitable for current OpenSSL

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#14709]
[`test/pkits-test.pl`](https://github.com/openssl/openssl/blob/master/test/pkits-test.pl) is clearly made for pre-1.1.0 OpenSSL, and has been forgotten since.  It needs to be changed to fit our test suite, or dropped.

If we decide to change it, we need to add instructions on how to get the test suite it runs OpenSSL against (the PKITS RFC3280 compliance test suite).

**Comment by nhorman** [comment]
I believe this is currently being tracked by https://github.com/openssl/openssl/issues/19663

Closing this as a duplicate
