### ISSUE TITLE
Missing EVP_PKEY_type_name() - no way how to get a key type name for new algorithms

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14701]
There is an EVP_KEYMGMT_get0_first_name() call but there is no public EVP_PKEY_get0_keymgmt() call either.

**Comment by t8m** [comment]
There is a EVP_PKEY_typenames_do_all() - however that is definitely not a simple replacement for OBJ_nid2sn(EVP_PKEY_type()).

**Comment by levitte** [comment]
There are a couple of cases where this can be handled differently:

1.  Does the application already have the name?  Let it use that, since it already has the knowledge.
2.  Is this used for type comparison?  In that case, `EVP_PKEY_is_a()` is a better choice.

**Comment by t8m** [comment]
1. might not be ideal if the application wants to display some kind of "canonical" name which the EVP_KEYMGMT_get0_first_name() should provide.

**Comment by levitte** [comment]
> 1. might not be ideal if the application wants to display some kind of "canonical" name which the EVP_KEYMGMT_get0_first_name() should provide.

Except no.  What ends up being the first name is undefined

**Comment by t8m** [comment]
IMO this is wrong. There should be a canonical name.

**Comment by levitte** [comment]
Aha ok...  Heh, it took almost 3 years to rehash that question again.

The key question here is "by who's authority?"

Let's take an example:  someone puts together a new algorithm, BLARGH.  The IETF likes it and give the OID the name id-BLARGH.  Someone puts together a provider (A), thinking that standards are gold, so calls it "id-BLARGH".  Someone else, who has a more all-encompassing mindset, puts together another provider (B), and gives it both names, "id-BLARGH:BLARGH".
Which name is canonical?  And specifically, how does libcrypto know?

There was some talk, a bit of time ago, that we could have some special syntax to mark one name canonical...  but then, what happens if one provider says "[canonical]id-BLARGH" and another says "id-BLARGH:[canonical]BLARGH"?  Suddenly we have two canonical names, and one canonicallity conflict...

"SCRYPT" and "id-SCRYPT" is a living example of this type of problem.

**Comment by paulidale** [comment]
You answered it yourself: the OID is canonical.  Who isn't a fan of 1.3.111.2.1619.1.1.2?

**Comment by levitte** [comment]
> You answered it yourself: the OID is canonical.

our EVP_PKEY_METHOD alias chain for RSA has a surprise for you.  There are two OIDs that we support for everything RSA: an earlier ITU-T OID (2.5.8.1.1) and the PKCS#1 OID (1.2.840.113549.1.1.1).
Not sure I want to reproduce that specifically (the old ITU-T OID should not be used as far as I know), but I'm wondering what we should do with implementations that transition from one OID to another.  It comes back to the same question, *how can libcrypto discern* what's "canonical" at any given time?

Plus, that doesn't answer the case where there simply isn't an OID for the algorithm yet.  Sure, that makes it unusable for anything that involves an AlgorithmIdentifier, but still...

**Comment by t8m** [comment]
The provider should mark one name as canonical. And among multiple providers? I do not really care.

**Comment by t8m** [comment]
The canonical name should be something that is output to the user in case I for example load a key with decoder and I'd like to print out what type of key I've actually loaded. And yeah - then there is a problem that we do not really distinguish regular RSA and RSA-PSS keys by type, but let's not dive into that here.

If you say that all the names are equal and there is no canonical one - what should I print out? By chance I could randomly print `2.5.8.1.1` or RSA or `1.2.840.113549.1.1.1`. That is not really user friendly.

**Comment by levitte** [comment]
> And yeah - then there is a problem that we do not really distinguish regular RSA and RSA-PSS keys by type

Er...  we do

**Comment by levitte** [comment]
> If you say that all the names are equal and there is no canonical one - what should I print out? By chance I could randomly print `2.5.8.1.1` or RSA or `1.2.840.113549.1.1.1`. That is not really user friendly.

There's the option of all.  Another option is that the app usually knows what it wants, and therefore already has the name.

**Comment by levitte** [comment]
> The provider should mark one name as canonical.

So, add more syntax to the name string...

> And among multiple providers? I do not really care.

Not sure what you don't care about.  If there are multiple providers having different opinions about the canonical name, you basically have two choices: 1) refuse to take on more than one (and what ends up being canonical will depend on what the user tries to load first), or 2) you have *two* or more canonical names, and you're back on square one.

**Comment by t8m** [comment]
> > And yeah - then there is a problem that we do not really distinguish regular RSA and RSA-PSS keys by type
> 
> Er... we do

I stand corrected. I confused this by that we do not use separate operation name for RSA-PSS.

**Comment by t8m** [comment]
>  1) refuse to take on more than one (and what ends up being canonical will depend on what the user tries to load first)

I do not see this as that big problem.

Printing all names is not really an option, this could be really ugly if numerical oids are among the names. And the app does not necessarily know always "what it wants". What should the pkey app print as the algorithm name if it loads a key with an algorithm supported by a third party provider. Of course it would be a hypothetical pkey app as currently there is no way to print just the key type name. Currently you can only print out the whole key (or just public part) and the type name is hardcoded in our encoder to text implementation. So in theory if you had a third party encoder to text the output could be something completely different.

**Comment by t8m** [comment]
> > The provider should mark one name as canonical.
> 
> So, add more syntax to the name string...

Why? The first name would be the canonical one (from the viewpoint of the provider).

**Comment by levitte** [comment]
> > So, add more syntax to the name string...
>
> Why? The first name would be the canonical one (from the viewpoint of the provider).

Provider A: "id-BLARGH:BLARGH"
Provider B: "BLARGH"

What's the canonical name?  Under what conditions?  Do note that with current mechanisms, they get aliased together since they share one name.

**Comment by t8m** [comment]
Maybe the term "canonical name" is not the best. Can I call it the "preferred name" and by preferred I mean preferred by the provider. And the EVP_PKEY_name() would simply call EVP_KEYMGMT_get0_first_name() from its keymgmt. For legacy keys it would return the ameth->pem_str.

**Comment by levitte** [comment]
> For legacy keys it would return the ameth->pem_str.

Er....  with legacy keys, it's *currently* usually something like this: `OBJ_nid2sn(EVP_PKEY_id(pkey))`

**Comment by levitte** [comment]
> Can I call it the "preferred name"

... you can, but you still end up with the same question, what should we do if there are two?  Whatever you wanna call it, it comes back to this.

Mind you, I've been playing with the idea that this could be solved the same way I finally did descriptions (#14656), i.e. make that dependent on the implementation.  The user would then have to accept that depending on what provider they end up using, they may get different names.
So, per-implementation "canonical"?  That could be acceptable enough in my mind.

**Comment by t8m** [comment]
> So, per-implementation "canonical"? That's what you're talking about, right?

Yes. I'll do a PR implementing that.

**Comment by levitte** [comment]
The interesting thing will, of course, be to decide whether pre-population of the namemap should use the OBJ short name or the long name as preferred name...  You may hit some interesting corner cases (no, I haven't checked, I just don't trust that we've been entirely consistent)

**Comment by t8m** [comment]
LOL I feel embarassed - we already have the function, not sure why I was not able to find it when reporting the issue. It is the EVP_PKEY_get0_first_alg_name(). IMO the name is quite awkward so I'll submit a renaming PR for consideration.

**Comment by levitte** [comment]
I forgot as well, so if there's embarassment to be had, it's shared :wink:

**Comment by t8m** [comment]
The rename is not sufficient. I also need to change the implementation to return the first name from the OSSL_ALGORITHM data.
