### ISSUE TITLE
debug heap: size of leaks of more than 2 GiB are reported incorrectly

### ISSUE THREAD

**Issue by smcpeak** [openssl/openssl#14714]
On a 64-bit platform, if a memory block of 2 GiB or larger is leaked, its size will be reported incorrectly in the memory leak report afterwards.  For example, after:

```
size_t gib = 0x40000000;
OPENSSL_malloc(2*gib);
```

`CRYPTO_mem_leaks_fp` will print:

```
[21:49:59]     4 file=src/demo.c, line=303, thread=14712, number=-2147483648, address=0x7fff1040
-2147483648 bytes leaked in 1 chunks
```

The size should be 2147483648, not -2147483648.

Observed with OpenSSL 1.1.1k on Windows and Linux, built from source (with MinGW on Windows), configured with `enable-crypto-mdebug`.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
