### ISSUE TITLE
Feature Request: Hybrid Public Key Encryption

### ISSUE THREAD

**Issue by chris-wood** [openssl/openssl#14748]
Hybrid public key encryption is a well-known cryptographic construction that allows a sender to encrypt arbitrarily-sized messages under a receiver’s public key. ECIES, for example, is one variant of this particular construction built on elliptic curve Diffie Hellman for non-interactive key exchange. However, there exists a number of standardized versions of ECIES, each of which differs in [features, flexibility, security properties and, importantly, interoperability](https://ieeexplore.ieee.org/abstract/document/5604194/). 

HPKE is an emerging IRTF standard aimed at providing a single standard for all applications and use cases wherein public key encryption is required. This includes several other IETF standards, such as the [Message Layer Security protocol](https://datatracker.ietf.org/doc/draft-ietf-mls-protocol/), [TLS Encrypted Client Hello](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html), and [Oblivious DNS over HTTPS](https://tools.ietf.org/html/draft-pauly-dprive-oblivious-doh-06). HPKE is flexible in almost every dimension, being built primarily on Key Encapsulation Mechanisms (KEMs), Key Derivation Functions, and AEAD algorithms. (Parameterization by KEMs is particularly useful in making the protocol ready for post-quantum algorithms.)

HPKE has a growing number of interoperable implementations in widely used [cryptographic libraries](https://github.com/cfrg/draft-irtf-cfrg-hpke#existing-hpke-implementations). The draft has [test vectors](https://github.com/cfrg/draft-irtf-cfrg-hpke/blob/master/test-vectors.json) available for all supported features.

HPKE is through the CFRG review process, is currently under review by the ISRG, and will likely be an RFC within the next couple of months. Given the maturity of the specification, growing number of dependent protocols and use cases, and wide community support, it seems like an obvious primitive to include in OpenSSL, especially given the dependency for ECH.

**Comment by paulidale** [comment]
It seems like it meets the standardisation requirement for inclusion.  However, I don't think that any of the core developers would be able to work on this for the 3.0 release.

A pull request would likely be reviewed and accepted if somebody else was will to invest the effort required.

**Comment by chris-wood** [comment]
@sftcd, could happykey work here? :-)

**Comment by sftcd** [comment]
On 02/04/2021 00:33, Christopher Wood wrote:
> @sftcd, could happykey work here? :-)

Well, I'm sure it's [1] not ready but I'd be willing to do
some work to try make it so.

Cheers,
S.

[1] https://github.com/sftcd/happykey

**Comment by mattcaswell** [comment]
Sounds somewhat related to the existing EVP_Seal* APIs:

https://www.openssl.org/docs/manmaster/man3/EVP_SealInit.html

**Comment by yan12125** [comment]
HPKE is published as [RFC 9180](https://www.rfc-editor.org/rfc/rfc9180.txt) 🎉

**Comment by mattcaswell** [comment]
Support for HPKE has been merged into master (via PR#17172).
