### ISSUE TITLE
RSA-PSS negotiation between client and server

### ISSUE THREAD

**Issue by Hussain1811** [openssl/openssl#14740]
I'm currently using TLS v1.2

I've seen that RSA-PSS signature algorithm is successfully negotiated only for SHA256, SHA384, SHA512.
However, the connection between the client and server fails if RSA-PSS is used with MD5/SHA1/SHA224.

On the other hand, RSA with SHA1, SHA224, SHA256, SHA384, SHA512 is negotiated successfully (MD5 fails though)

is this because there is a security weakness w.r.t RSA-PSS for MD5/SHA1/SHA224 and RSA with MD5?

**Comment by davidben** [comment]
Mechanically, what's going on here is the IETF only defined RSA-PSS code points for SHA-256, SHA-384, and SHA-512.
https://tools.ietf.org/html/rfc8446#section-4.2.3

In terms of why, MD5 is *extremely* broken at this point. and SHA-1 has also fallen. Beyond that, SHA-224 is a bit small and it's generally bad for the ecosystem to define too many options, so it did not make the cut.
https://en.wikipedia.org/wiki/MD5#Security
https://en.wikipedia.org/wiki/SHA-1#Cryptanalysis_and_validation
https://tools.ietf.org/html/draft-ietf-tls-md5-sha1-deprecate-06

**Comment by Hussain1811** [comment]
Alright.
Thank you @davidben
