### ISSUE TITLE
Is BIO_snprintf supposed to NUL-terminate its output even if it fails?

### ISSUE THREAD

**Issue by smcpeak** [openssl/openssl#14772]
When `BIO_snprintf` fails (returns negative), and the output buffer size is at least 1, is it guaranteed to put a NUL terminator into that buffer?

I ask because the [documentation](https://www.openssl.org/docs/man1.1.1/man3/BIO_snprintf.html) does not say, and I see two conflicting bits of evidence in the code:

* The OpenSSL code contains more than 100 calls to `BIO_snprintf`, but in most cases the return value is not checked and the buffer is subsequently passed to a function that requires NUL termination.  This suggests the answer is **yes**.
* The implementation of `BIO_snprintf` contains many error handling paths that, if followed, would omit NUL termination.  The most frequent example is the many calls to `doapr_outch`, including the one that actually performs NUL termination in the usual case.  This suggests the answer is **no**.

Digging into `doapr_outch`, it has a few paths that return 0 (meaning failure), but they are difficult or impossible to exercise from `BIO_snprintf`.  The same is true of `fmtfp`.

So: is it considered safe for a caller to "know" that `BIO_snprintf` cannot fail in a particular circumstance due to avoiding all of the potential error paths, or should every call site instead be prepared for `BIO_snprintf` to fail and not NUL terminate the output?  If the former, is there a concise statement of the conditions under which a caller is allowed to assume that `BIO_snprintf` cannot fail?

**Comment by levitte** [comment]
All failures in `doapr_outch` are about lack of space (either because the buffer is full or because memory couldn't be allocated, and the latter is only applicable when `BIO_printf()` is called, not with `BIO_snprintf()`), and this trickles up the call stack back to `BIO_snprintf()`.  `fmtfp` has similar failure conditions, plus a few extra for "impossible" floating point numbers, some of them due to assumed memory space limits as well.

As far as I recall, all our calls to `BIO_snprintf()` are done with buffers that are more than large enough, so it's correct that we "know" that they will never fail.  You're welcome to scrutinize and prove us wrong.

**Comment by smcpeak** [comment]
Ok, thanks for the clarification.  If it is considered correct usage to ignore the return value when `BIO_snprintf` is known to not be capable of failing, then I think the conditions that imply failure is an impossibility ought to be documented in the API reference.  Would you agree?

**Comment by richsalz** [comment]
> I think the conditions that imply failure is an impossibility ought to be documented in the API reference. Would you agree?

That would move from something which is true for the current uses, to an API guarantee.  Those are different thing and probably not appropriate, or correct.

**Comment by smcpeak** [comment]
Indeed, which is sort of my point: the non-checking call sites seem to be making risky assumptions by relying on current implementation details rather than a documented interface.  A future change could break them.  Furthermore, they are potentially setting a poor example for users of OpenSSL, who will often look to the code and examples in OpenSSL to see how to use the API properly.

**Comment by smcpeak** [comment]
Let me reiterate, though, that my original question was not about the "cannot fail" conditions, but rather the "will NUL terminate" conditions.  As a user of OpenSSL, I would prefer that `BIO_snprintf` have a documented guarantee that it will always leave a NUL terminator in the output buffer so long as its size is at least 1.  That would address the security concern of potentially reading beyond the array bounds.

**Comment by levitte** [comment]
> I would prefer that `BIO_snprintf` have a documented guarantee that it will always leave a NUL terminator in the output buffer so long as its size is at least 1.

Considering that this is a "clone" of `snprintf()`, that's an incompatible change of semantics.  Whether such a change would be acceptable or not is the question.

**Comment by smcpeak** [comment]
Unless I'm missing something, my suggested semantics would be compatible with the C11 specification for `snprintf()`.  Quoting C11 7.21.6.5/2:

>  If `n` is zero, nothing is written, and `s` may  be  a  null  pointer.   Otherwise,  output  characters  beyond  the `n-1`st  are discarded rather than being written to the array, and a null character is written at the end of  the  characters  actually  written  into  the  array

C99 7.19.6.5/2 says the same thing.

Now, a possible source of confusion is this statement in paragraph 3 of both specifications:

>  Thus,   the   null-terminated   output   has   been completely written if and only if the returned value is nonnegative and less than `n`.

However, the key word there is "completely".  It does not contradict the earlier statement.

Furthermore, the current (OpenSSL 1.1.1k) behavior of `BIO_snprintf` does in fact leave a NUL character in the buffer in all cases except for the rare or impossible failure cases.  In particular, even when it returns -1 to signal insufficient space, it puts a NUL terminator in the output.

**Comment by paulidale** [comment]
I've looked at the code diff between 1.1.1 and master and the functions are virtually identical.  The differences being:

- one unused assignment removed,
- the licence change and
- an error message change.

Can you provide an example where 1.1.1 null terminates where 3.0 doesn't?

**Comment by smcpeak** [comment]
If you're asking me, I don't know of any behavior differences between the versions.  I was only looking at 1.1.1 when asking my original question.

**Comment by paulidale** [comment]
You made the claim:

>Furthermore, the current (OpenSSL 1.1.1k) behavior of BIO_snprintf does in fact leave a NUL character in the buffer in all cases except for the rare or impossible failure cases. In particular, even when it returns -1 to signal insufficient space, it puts a NUL terminator in the output.

If this is true, it seems like this is a non-event.

**Comment by smcpeak** [comment]
Ah, sorry for the confusion.  I was just trying to clarify what I meant by "current".

My point remains that for most practical purposes `BIO_snprintf` behaves in a way that conforms to the C99/C11 specification of `snprintf` with regard to null termination, which is good, and I think it would be beneficial to adjust the documentation to state that it does conform.  That is, I propose this be documented: "`BIO_snprintf` always null-terminates the given buffer if the given size is at least 1."

The effect of such a statement would be to (1) clarify that the numerous uses of `BIO_snprintf` in the OpenSSL code that do not check for errors are in fact correct, and (2) imply that the numerous syntactic code paths through `BIO_snprintf` that omit null termination are officially considered impossible to execute.

**Comment by smcpeak** [comment]
As I explained in comments on 586d943, my original question remains unanswered.  Even with that addition, I still do not know if `BIO_snprintf` is guaranteed to null terminate the output when the size is non-zero.  Should I open a new question?

**Comment by t8m** [comment]
Would you like to submit a PR with your proposed text?
