### ISSUE TITLE
[DH- BIGNUM]:Upgrade from 1.0.2 series to 1.1.1 series

### ISSUE THREAD

**Issue by raveendrapadala** [openssl/openssl#14798]
In Version 1.0.2:
For reading/get DH parameters, we have a legacy code to convert "Convert the Big number to little endian byte array". so want to understand whether endianness issues are taken care in the New API's that return Big Number like ```DH_get0_p, DH_get0_q, DH_get0_g```
The reason for asking this question is we have not seen any references in documentation.

**Comment by mattcaswell** [comment]
BIGNUMs handle all endian issues internally (even in 1.0.2). Where you might need to be aware of endianess is when converting a BIGNUM to or from some external format.

So, the question really is why do you need to "Convert the Big number to little endian byte array" in your 1.0.2 code? What are you then doing with the little endian byte array?

Note that there are OpenSSL functions that do conversions from BIGNUMs to little endian byte arrays already. See for example the functions described here:

https://www.openssl.org/docs/man1.1.1/man3/BN_bn2lebinpad.html

**Comment by raveendrapadala** [comment]
Thanks Mattcaswell. That was quite informative response. we will try to reuse the existing API's instead of custom implementations.

One last question regarding the access of EVP_PKEY_CTX from EVP_MD_CTX in the new opaque model. Need suggestion on adapting to OpenSSL-1.1.1k

if ( EVP_PKEY_CTX_set_rsa_padding(**ctx->pctx**, RSA_PKCS1_PSS_PADDING ) <= 0 ) {
```
 ctx = EVP_MD_CTX_create();

      if(ctx == NULL) {
          printf("[%s] EVP_MD_CTX_create is failed\n",__func__);
          status = VERIFY_SLOT_SIGN_EVP_CTX_CREATE_FAILED;
          goto end;
      }
      // Using RSA-PSS padding
      if (EVP_DigestVerifyInit(ctx, &pkey_ctx, md, NULL, CertPubKey)<=0) {
          err = ERR_get_error();
          errMsg = ERR_error_string(err, NULL);
          printf("[%s] EVP_DigestVerifyInit failed,err[%lu]errmsg[%s]\n", __func__,err, GETSTRING(errMsg));
          status = VERIFY_SLOT_SIGN_DIGEST_INIT_FAILED;
          goto end;
      }
      // Setting RSA padding mode and salt length
      if ( EVP_PKEY_CTX_set_rsa_padding(ctx->pctx, RSA_PKCS1_PSS_PADDING ) <= 0 ) {
          printf("[%s] Setting RSA padding mode failed\n", __func__);
          status = VERIFY_SLOT_SIGN_DIGEST_INIT_FAILED;
          goto end;
      }
      /* Setting RSA PSS salt length to -1, sets salt length to digest length*/
      if ( EVP_PKEY_CTX_set_rsa_pss_saltlen(ctx->pctx, -1) <= 0 ) {
          printf("[%s] Setting RSA PSS salt length failed\n", __func__);
          status = VERIFY_SLOT_SIGN_DIGEST_INIT_FAILED;
          goto end;
      }

```

**Comment by mattcaswell** [comment]
You can use the function `EVP_MD_CTX_pkey_ctx()` for this purpose. See:

https://www.openssl.org/docs/man1.1.1/man3/EVP_MD_CTX_pkey_ctx.html

**Comment by raveendrapadala** [comment]
Awesome Thanks. :-).

**Comment by davidben** [comment]
You actually don't even need that function here. `EVP_DigestVerifyInit` returns the `EVP_PKEY_CTX` via `&pkey_ctx`. You all already had the value, just weren't using it.
