### ISSUE TITLE
Openssl in an Conda environment on the Apple M1 Chip

### ISSUE THREAD

**Issue by 2Gameboyz** [openssl/openssl#14792]
### How can I install an stable version of openssl on my Macbook with Apple Silicon Chip? ###

My openssl Installation:

``
OpenSSL> version -a
OpenSSL 1.1.1k  25 Mar 2021
built on: Thu Mar 25 14:53:07 2021 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: x86_64-apple-darwin13.4.0-clang -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/USER/miniforge3/envs/tensorflowvenv/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/USER/miniforge3/envs/tensorflowvenv/include -fdebug-prefix-map=/opt/concourse/worker/volumes/live/d6cc10a3-c4ff-4472-4e1b-a339b333e76e/volume/openssl_1616683945709/work=/usr/local/src/conda/openssl-1.1.1k -fdebug-prefix-map=/Users/USER/miniforge3/envs/tensorflowvenv=/usr/local/src/conda-prefix -fPIC -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/paulciupke/USER/envs/tensorflowvenv/include -fdebug-prefix-map=/opt/concourse/worker/volumes/live/d6cc10a3-c4ff-4472-4e1b-a339b333e76e/volume/openssl_1616683945709/work=/usr/local/src/conda/openssl-1.1.1k -fdebug-prefix-map=/Users/USER/miniforge3/envs/tensorflowvenv=/usr/local/src/conda-prefix -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/USER/miniforge3/envs/tensorflowvenv/include
OPENSSLDIR: "/Users/USER/miniforge3/envs/tensorflowvenv/ssl"
ENGINESDIR: "/Users/USER/miniforge3/envs/tensorflowvenv/lib/engines-1.1"
Seeding source: os-specific
``

I get some errors when I use pip or Jupyter Notebook:

``
(tensorflowvenv) USER@Air-von-USER ~ % pip install matplotlib
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/matplotlib/
...
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/matplotlib/
Could not fetch URL https://pypi.org/simple/matplotlib/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/matplotlib/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement matplotlib (from versions: none)
ERROR: No matching distribution found for matplotlib
``

``
Last login: Wed Apr  7 12:24:40 on ttys001
/Users/USER/miniforge3/envs/tensorflowvenv/bin/jupyter_mac.command ; exit;
USER@Air-von-USER ~ % /Users/USER/miniforge3/envs/tensorflowvenv/bin/jupyter_mac.command ; exit;
Traceback (most recent call last):
  File "/Users/USER/miniforge3/envs/tensorflowvenv/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/USER/miniforge3/envs/tensorflowvenv/lib/python3.8/site-packages/notebook/notebookapp.py", line 60, in <module>
    from tornado import httpserver
  File "/Users/USER/miniforge3/envs/tensorflowvenv/lib/python3.8/site-packages/tornado/httpserver.py", line 29, in <module>
    import ssl
  File "/Users/USER/miniforge3/envs/tensorflowvenv/lib/python3.8/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/Users/USER/miniforge3/envs/tensorflowvenv/lib/python3.8/lib-dynload/_ssl.cpython-38-darwin.so, 2): Library not loaded: @rpath/libssl.1.1.dylib
  Referenced from: /Users/USER/miniforge3/envs/tensorflowvenv/lib/python3.8/lib-dynload/_ssl.cpython-38-darwin.so
  Reason: no suitable image found.  Did find:
	/Users/USER/miniforge3/envs/tensorflowvenv/lib/libssl.1.1.dylib: mach-o, but wrong architecture
	/Users/USER/miniforge3/envs/tensorflowvenv/lib/libssl.1.1.dylib: mach-o, but wrong architecture
	/Users/USER/miniforge3/envs/tensorflowvenv/lib/python3.8/lib-dynload/../../libssl.1.1.dylib: mach-o, but wrong architecture
	/Users/USER/miniforge3/envs/tensorflowvenv/lib/libssl.1.1.dylib: mach-o, but wrong architecture
	/Users/USER/miniforge3/envs/tensorflowvenv/bin/../lib/libssl.1.1.dylib: mach-o, but wrong architecture
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Prozess beendet]

``

**Comment by paulidale** [comment]
This is a question for the Python folks who maintain `pip`.

**Comment by 2Gameboyz** [comment]
It's not a pip problem. The libssl version I installed is not suitable for the Apple Silicon Chip. How can I install it suitable.

**Comment by paulidale** [comment]
Where did the libssl version you installed come from?
The OpenSSL project doesn't distribute binaries, so it wasn't us.

**Comment by 2Gameboyz** [comment]
It was installed with mini forge. Ok I accept it's not your problem.

**Comment by h-vetinari** [comment]
Normally, you should open an issue for conda builds in the respective feedstock, in this case here: https://github.com/conda-forge/openssl-feedstock. However, I see from the error stack that you're working with tensorflow, which hasn't been updated in conda-forge due to CI limitations for a long time - perhaps you installed this via pip? Mixing pip & conda is never guaranteed to work. Conda-forge keeps its own packages consistent, but pip might stomp all over things in an environment. The good news is that there will very soon be current tensorflow builds in conda-forge again (see here: https://github.com/conda-forge/tensorflow-feedstock).

This issue can be closed.

**Comment by paulidale** [comment]
Thanks @h-vetinari, closing this.
