### ISSUE TITLE
Use config auto-detect 128bit datatype

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#14805]
As @mattcaswell pointed out in https://github.com/openssl/openssl/pull/14784#discussion_r608398648:

We could use the auto-detect to auto-enable `ec_nistp_64_gcc_128`

**Comment by richsalz** [comment]
So should `ec_nistp_64_gcc_128`
- Be renamed to drop gcc or is clang not supporting 128bit?
- Changed to get default value from the `$config{use_int128}` value?

**Comment by t8m** [comment]
There is no autodetect in config anymore. That was reverted due to inherent problems with misdetections.

**Comment by richsalz** [comment]
Close this since it is no longer relevant.
