### ISSUE TITLE
AES KAT for FIPS provider has a gap

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14807]
IG 9.4 states (bolding mine):

> In addition, and applying only to the AES algorithm, if the module implements the forward
> cipher function, then this forward cipher function shall be self-tested at least once by either
> performing a KAT on any encryption mode that supports the forward cipher function (typically
> all encryption modes support the forward cipher), or by selecting a decryption mode that supports
> the forward cipher function (e.g. CFB, OFB, CTR, CMAC, CCM, GCM, FF1). **Similarly, if the
> inverse cipher function is implemented, then it shall be self-tested at least once by performing a
> KAT on any mode that supports the inverse function.** Typically, the following modes support the
> inverse function within the decryption mode: ECB, CBC, XTS, KW, KWP.
> The Encrypt KAT and Decrypt KAT do not need to be performed for each mode(s) that is
> selected to meet this cipher function requirement, as long the forward and inverse cipher
> functions (if implemented) are self-tested at least one time within any implemented mode(s). For
> example, if the module only implements AES GCM (Encrypt/Decrypt) and AES ECB
> (Encrypt/Decrypt), then the following KATs would suffice: AES GCM Encrypt (to cover the
> forward cipher function), AES ECB Decrypt (to cover the inverse cipher function). KATs on
> AES GCM Decrypt and AES ECB Encrypt would not be necessary. Or, in this example, the
> following KATs would also suffice: AES ECB Encrypt (to cover the forward cipher function),
> AES ECB Decrypt (to cover the inverse cipher function). KATs on AES GCM would not be
> necessary to meet this cipher function requirement.
> The reason the above two paragraphs only apply to AES and not Triple-DES is because every
> approved Triple-DES mode involves running both a forward and an inverse application of the
> underlying DES algorithm.
> All module submissions (2SUB, 3SUB or 5SUB) after November 30, 2019 shall comply with
> this requirement.

It isn't immediately obvious that we're testing the decryption direction.  We have:
- AES-GCM (forward only),
- AES-CTR-DRBG (forward only), and
- X9.42 KDF (only uses the OIDs)

An additional KAT should be added to cover this gap.

**Comment by slontis** [comment]
self_test_cipher() does encrypt and decrypt operations?

**Comment by paulidale** [comment]
Both GCM and CTR only ever use the encrypt half of the cipher.  We'll need one of ECB, CBC, OFB or CFB modes.  I'd suggest ECB.
