### ISSUE TITLE
DH key derivation checks are incomplete (alpha14)

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#14808]
Commit https://github.com/openssl/openssl/commit/e454a3934c287aede194cac49c8934f04bf6a04f#diff-78ed4660fbeb3ac4a81589478f963d94a1452d534c6d7189d562512852a1efcfR79-R94 shifts DH key checks into `EVP_PKEY_derive_set_peer`. This changes the behavior of `DH_compute_key` (which is fine, OpenSSL 3.0 is a breaking change), but the new code path does not do the same set of checks that were previously performed when calling `DH_compute_key`. Specifically, it appears the verification that the public key is less than `p` is missing:

https://github.com/openssl/openssl/blob/dfccfde06562ac87fe5e5f9401ba86cad050d9a2/crypto/ffc/ffc_key_validate.c#L41-L48

This causes a new failure in the pyca/cryptography test suite where we verify that DH kex fails when passing this vector. This vector fails as expected on OpenSSL 1.0.2+ including alpha13, but passes in alpha14.

https://github.com/pyca/cryptography/blob/58f0ad5b6b928677931c7ad44deee839a29ee9d3/vectors/cryptography_vectors/asymmetric/DH/bad_exchange.txt#L3-L11

**Comment by slontis** [comment]
Will look into it today..

**Comment by slontis** [comment]
I cant see any tests in OpenSSL for DH KEX at all :(

**Comment by t8m** [comment]
> I cant see any tests in OpenSSL for DH KEX at all :(

IMO it's at least implicitly tested by the TLS tests. But yeah, that means only positive testing.

**Comment by t8m** [comment]
If we had the pyca/cryptography external test working we would have found it. :grin:

**Comment by slontis** [comment]
> If we had the pyca/cryptography external test working we would have found it. 😁

Chicken and egg problem...

**Comment by reaperhulk** [comment]
@slontis If the project is willing to do an alpha release specifically to get to zero failures in cryptography I'm willing to validate master works prior to the alpha release, merge into our own main branch with testing against alpha15 in our CI, and then help get the cryptography test suite running again on your master branch.

**Comment by slontis** [comment]
@mattcaswell? Any thoughts on this?

There is a planned date for alpha15 (can someone confirm this date?). I assume that won't be too far away..
If I work to fix anything that is currently broken and you test against master just before this date then maybe we can coordinate from there..

**Comment by slontis** [comment]
It does do the check for the public key being in range - but it does this for its own 'p' not the p of the private key.. So it also needs to do a 'matching' test also.

**Comment by slontis** [comment]
I have put the matching check into the provider side set_peer methods for ecdh and dh. This duplicates a small bit of code that is present in the match() methods inside the keymanager for dh and ecdh.

An alternative approach would be to call EVP_PKEY_cmp_parameters from the EVP_PKEY_derive_set_peer() function.. BUT this would then require the getparams accessor to pull the private key out of the PKEY for the dh and ecdh exchange.

**Comment by t8m** [comment]
> @mattcaswell? Any thoughts on this?
> 
> There is a planned date for alpha15 (can someone confirm this date?). I assume that won't be too far away..
> If I work to fix anything that is currently broken and you test against master just before this date then maybe we can coordinate from there..

The current plan is for Alpha 15 on Apr 22 - but of course plans might change.

**Comment by slontis** [comment]
@reaperhulk - this would probably mean building against master to check it is ok probably multiple times before this date to make sure we have everything working. (Ideally starting at the end of this week to give us time to fix any new issues).

**Comment by reaperhulk** [comment]
Once these two issues are closed I can test against master again. Assuming no new failures testing it a few times is no problem.
