### ISSUE TITLE
segfault when using ed25519 in OCSP_basic_sign (alpha14)

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#14809]
In OpenSSL 3.0 alpha13 it was possible to use an ed25519 cert/keypair to sign using `OCSP_basic_sign`. As in the other X.509 APIs in OpenSSL this passes an `EVP_MD *` nullptr since ed25519 defines its hashing algorithm as part of the algorithm itself and it is not configurable. As of alpha14 this now causes a segfault. A quick look at the implementation suggests this is because the `EVP_MD *` is assumed to be non-null as of this change: https://github.com/openssl/openssl/commit/e6c2f96489fc0c006845c8597f8ceed2f01f76ee#diff-67db6b3831d76edabcc44e235055c6520c41916b4451ffedb57b08962ae3ace8L226

The current EdDSA implementations supported by OpenSSL (ed25519, ed448) both take NULL for `EVP_MD *` on X509 signing APIs, so every signing API should probably have an EdDSA example added to prevent regression on this in the future.

**Comment by slontis** [comment]
yep - my fault.. will fix..
