### ISSUE TITLE
using secp256k1 curve sign cert get handshake failure

### ISSUE THREAD

**Issue by 0neday** [openssl/openssl#14820]
`/build/dists/openssl-v1.1.1k/bin/openssl ecparam -genkey -name secp256k1 -out "${DIR}/my-service.key"`

```
2021.04.10 19:41:02 LOG7[11]: TLS state (connect): SSLv3/TLS write client hello
2021.04.10 19:41:02 LOG7[11]: TLS alert (read): fatal: handshake failure
2021.04.10 19:41:02 LOG3[11]: SSL_connect: ssl/record/rec_layer_s3.c:1544: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
2021.04.10 19:41:02 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
```
but use prime256v1 is fine

**Comment by mattcaswell** [comment]
This means the peer has rejected the handshake. Unfortunately the protocol doesn't tell you anything more that the peer has rejected it - not why. To be sure you would have to look at the peer's logs. However its almost certainly because the peer does not want to accept this curve. It's rarely used in practice.

**Comment by 0neday** [comment]
> This means the peer has rejected the handshake. Unfortunately the protocol doesn't tell you anything more that the peer has rejected it - not why. To be sure you would have to look at the peer's logs. However its almost certainly because the peer does not want to accept this curve. It's rarely used in practice.

The peer log is same. I use stunnel lastest version with openssl 1.1.1k. I try prime256v1 curve to sign a cert, that is ok. and I try ed25519 to sign a cert, that is also fine. It is so wierd.

**Comment by t8m** [comment]
secp256k1 is not allowed with TLS-1.3 - could that be the issue?

**Comment by mattcaswell** [comment]
>  It is so wierd.

That curve is not in OpenSSL's default set of accepted curves so its not so weird:

https://github.com/openssl/openssl/blob/f82f5392f39797c1cf3a5d114c0125f121b0f769/ssl/t1_lib.c#L180-L187

**Comment by 0neday** [comment]
> secp256k1 is not allowed with TLS-1.3

nice. https://github.com/openssl/openssl/issues/8369#issuecomment-518565778
