### ISSUE TITLE
Cannot Install openssl into MinGW

### ISSUE THREAD

**Issue by Terminou** [openssl/openssl#14836]
I am trying to install openssl into MinGW but I am getting errors. Here is what I did:

- Download tar and unzipped it.
- Open MYSY terminal and _**cd**_' to relative path. (The location of unzipped folders)
- Run **./config** command.

The error messages I obtanied:

- _The system cannot find the path specified._
- _Configuring OpenSSL version 3.0.0-alpha14 for target VC-WIN64A_
- _Using os-specific configuration._

- _Failure! build file wasn't produced._

- _NASM not found - make sure it's installed and available on %PATH%_

Can you please help me with the issue I'm facing. What I'm trying to do basically using openssl in an IDE called CodeBlocks that uses MinGW.

Thanks in advanced,
Terminou

**Comment by tmshort** [comment]
Please review: https://github.com/openssl/openssl/blob/master/NOTES-WINDOWS.md

You should specify **mingw** or **mingw64** as the platform:
```
./Configure mingw64
```

The instructions for building with NASM are under **Native builds using Visual C++**
You can also try the **no-asm** option when configuring.

**Comment by tmshort** [comment]
> Configuring OpenSSL version 3.0.0-alpha14 for target VC-WIN64A

It's defaulting the configuration to be built using Visual-C++ 64-bit. Use the one of the **mingw** configuration options.

**Comment by mattcaswell** [comment]
> Open MYSY

There was clearly a typo here. I assume you mean MSYS2 right? The old "MSYS" does *not* work.

> Configuring OpenSSL version 3.0.0-alpha14 for target VC-WIN64A

My guess is the Configure script is picking up a non-msys2 version of perl. If you are going to do an msys2 based build using MinGW then you need msys2 perl. If you are doing a Visual Studio based build then you need a native perl (typically ActiveState or Strawberry).

As @tmshort says make sure you've read the NOTES-WINDOWS.md file, and in particular the section "Native builds using MinGW".

**Comment by Terminou** [comment]
Thanks for your assistance. It is solved.
