### ISSUE TITLE
Symlinks are no longer generated when installing the man pages

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14846]
It used to be the case (in 1.1.1) than when you install the man pages symlinks were generated for all functions described on the page that pointed to the main page. This no longer seems to be the case any more. This means that many pages are not found. For example the function "X509_REQ_verify_ex" is defined in the X509_verify.pod page. In 1.1.1 issuing the command `man X509_REQ_verify_ex` would bring up the correct page. It no longer does this.

**Comment by paulidale** [comment]
There are also some image files in doc/man7/ which should be included in the HTML generation.

**Comment by t8m** [comment]
> There are also some image files in doc/man7/ which should be included in the HTML generation.

I think that should be a separate issue and PR.

**Comment by paulidale** [comment]
#15305 raised for the other problem
