### ISSUE TITLE
Conversion of SSH key with passphrase into OpenSSL PEM format | 'unable to load Private Key'

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#14854]
**OS:** Fedora 34; **Component:** openssl-1.1.1k-1.fc33.x86_64

**Prerequisite:** Creation of an SSH Ed25519 key pair –  using function `ssh-keygen` – associated to passphrase.
```
$ cd ~/.ssh; openssl req -x509 -days 256 -new -key id_ed25519 -out id_ed25519.pem
unable to load Private Key
139867874473792:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
```
**Expected:**  to be asked the passphrase via an interactive prompt .

**Comment by beldmit** [comment]
It's not an openssl issue but an OpenSSH one.
The patch from https://github.com/openssh/openssh-portable/pull/230 adds such a possibility.

**Comment by t8m** [comment]
In other words - the private keys as generated by the ssh-keygen use by default a special format that is not readable by openssl. Please see the man ssh-keygen manual page and especially the -m option.

**Comment by Ricky-Tigg** [comment]
Thanks for those comments. Indeed `man ssh-keygen`; since there was no mention regards non-compatibility of OpenSSH-specific format – _RFC4716_ – with OpenSSL, i could reasonably assume that OpenSSL might support it.

**Comment by t8m** [comment]
There is definitely no problem with asking the question here.
