### ISSUE TITLE
Cross-compiling openssl-fips-2.0.16 for armv7

### ISSUE THREAD

**Issue by vikas-yadav77** [openssl/openssl#14853]
I am trying to cross compiling openssl-fips-2.0.16 for ARMv7. Below is my configuration

Host environment -  Ubuntu 14.04.5 LTS

Target configuration -
Operating system: armv7-whatever-linux2
Auto Configuring fipsonly
Auto Configuring fipsonly
Configuring for linux-armv4
Auto Configuring fipsonly
Configuring for linux-armv4

MACHINE=armv7
CC            =arm-fslc-linux-gnueabi-gcc  -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.4.3/sysroots/armv7at2hf-neon-fslc-linux-gnueabi
CFLAG         =-DOPENSSL_FIPSCANISTER -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -Wa,--noexecstack -DTERMIO -O3 -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DGHASH_ASM

I have used below commands to compile it
cd ~/openssl-fips-2.0.16 
./config
make

during make I am getting below error

./fips_standalone_sha1 fipscanister.o > fipscanister.o.sha1
./fips_standalone_sha1: 1: ./fips_standalone_sha1: Syntax error: word unexpected (expecting ")")
make[2]: *** [fipscanister.o] Error 2

I am following User Guide - OpenSSL FIPS Object Module v2.0 

I have attached complete build logs here
[Uploading openSSl_FIPS_build_errors.txt…]()

Can you please look into the issue and provide some pointer to resolve this.

**Comment by 0neday** [comment]
use ./Configure , check [here](https://gist.github.com/0neday/2c820af5acbf90e48a8f1f2b9abf01a6)

**Comment by paulidale** [comment]
You can't use Configure and remain compliant with the security policy -- what you end up with will not be blessed by FIPS.

**Comment by vikas-yadav77** [comment]
@paulidale @0neday  Thanks for your comments. I am not using Configure option. 
I have followed User Guide - OpenSSL FIPS Object Module v2.0 to cross compile openssl-fips-2.0.16 for ARM
Below are the commands

cd ~/openssl-fips-2.0.16
./config
make

And getting below error

during make I am getting below error

./fips_standalone_sha1 fipscanister.o > fipscanister.o.sha1
./fips_standalone_sha1: 1: ./fips_standalone_sha1: Syntax error: word unexpected (expecting ")")
make[2]: *** [fipscanister.o] Error 2

Here are the complete logs
[openSSl_FIPS_build_errors.txt](https://github.com/openssl/openssl/files/6308792/openSSl_FIPS_build_errors.txt)

I know the error is from fips_standalone_sha1 binary, which is actually built for ARM and make try to run it on x86 host machine, that why we have this error.

Do we have the other mechanism to build OpenSSL FIPS Object Module v2.0.  And how we can solve this issue.

@richsalz Do you have any comments on this? or any idea of what I am doing wrong?

Thanks

**Comment by vikas-yadav77** [comment]
After I export HOSTCC to gcc thic error get resolved.
