### ISSUE TITLE
Why are there two ways of providing OSSL_PARAMs to EVP_MAC?

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#14855]
Pondering on the typical use of the new EVP_MAC API, 
I wondered why there is a non-linearity concerning the `OSSL_PARAM *` arguments, e.g.:
```
    ctx = EVP_MAC_CTX_new(mac);
    EVP_MAC_CTX_set_params(ctx, params);
    EVP_MAC_init(ctx, key, keylen, params);
    EVP_MAC_update(ctx, data, datalen);
    EVP_MAC_final(ctx, out, &len, outsize);
```
So `params` can go both into `EVP_MAC_CTX_set_params()` and `EVP_MAC_init()`.
This may be confusing or at least appears not sufficiently documented. 
Is this really needed, or can go all params in one of the two functions?

**Comment by mattcaswell** [comment]
Initially you could only do it via `EVP_MAC_CTX_set_params()`. I think this is needed - it may well be different parts of an application that sets parameters versus where the mac is initialised. However, in many cases you can just do it all at init, therefore we recently additionally added a params argument to the init to reduce the number of calls that you needed to make.

**Comment by DDvO** [comment]
I see - so `EVP_MAC_CTX_set_params()` is the core way of setting params,
and setting params via `EVP_MAC_init()` is just a shorthand for doing an extra  `EVP_MAC_CTX_set_params()` call, right? 
If so, does it make a difference if any further call of  `EVP_MAC_CTX_set_params()` is done before or after calling  `EVP_MAC_init()`?
All this should become clear from reading `EVP_MAC.pod`.

**Comment by t8m** [comment]
Yep, the semantics of set_params after init is quite confusing. Should we allow it at all? Or, with #14787 in mind we probably need to still allow it but it should be documented that it does not take an effect unless you call init again.

**Comment by richsalz** [comment]
> Yep, the semantics of set_params after init is quite confusing. Should we allow it at all? 

Shouldn't it show up in @paulidale's state diagrams?  Whatever you decide.

**Comment by t8m** [comment]
Yeah, the set_params() (and get_params()) calls are missing in https://github.com/openssl/openssl/blob/master/doc/man7/life_cycle-mac.pod

**Comment by paulidale** [comment]
They are present in the table below the diagram.  Including them in the diagram unnecessarily complicated things.  As documented the diagram is the _usual_ flow and the table is the _canonical_ list of possible transitions.

**Comment by DDvO** [comment]
`EVP_MAC_CTX_set_params()` is not mentioned at all in `life_cycle-mac(7)`.
And even if it was, readers of `EVP_MAC.pod` typically won't notice that is may be helpful looking at it.

Why not simply mention in the description of `EVP_MAC_init()` that providing `params` there is equivalent to calling `EVP_MAC_CTX_set_params()` beforehand.

**Comment by levitte** [comment]
The "confusion" is the same as it's been for using ctrl functions.  Very simply put, you *can* call those both before and after the corresponding init function, and the diverse values passed take effect in different spots of the flow.

A prime example of this happening is `EVP_DigestFinalXOF()`, which calls the MD ctrl with command `EVP_MD_CTRL_XOF_LEN` and the given length in 1.1.1, corresponding OSSL_PARAM in master.

**Comment by paulidale** [comment]
Argh, I put "settable" and "gettable" instead of "set" and get" in the life-cycle document.

**Comment by paulidale** [comment]
Fixed in  #14867

**Comment by DDvO** [comment]
#14937 adds to the doc of `EVP_MAC_init()`:
```
Providing non-NULL I<params> to this function is equivalent to calling
EVP_MAC_CTX_set_params() with those I<params> for the same I<ctx> beforehand.
```
Is this correct, and is there maybe more to say about it?

**Comment by paulidale** [comment]
Yes, it is correct.  The params are processed before the initialisation.  What more needs to be said here?
