### ISSUE TITLE
The condition is always true.

### ISSUE THREAD

**Issue by ihsinme** [openssl/openssl#14876]
good day.
maybe I'm wrong, but it seems to me.
check `if (maskedDBLen - i)` requires your attention.
my analysis shows that it will always be true, and as a result will lead to `goto err;`.
perhaps a more specific comparison is required here.
https://github.com/openssl/openssl/blob/aed03a12096cbcce30a133c179336072fdad64d1/crypto/rsa/rsa_pss.c#L125

Thank you.

**Comment by t8m** [comment]
It can be 0 if salt len is 0.

14. 4. 2021 19:33, 19:33, ihsinme ***@***.***> napsal/a:

**Comment by ihsinme** [comment]
exactly, sorry.

maybe then it's better to write `if(sLen == 0)`
