### ISSUE TITLE
I run into the the problem "Undefine refrence to EVP_sm4_cbc" when i use the "EVP_EncryptInit_ex" API 

### ISSUE THREAD

**Issue by hql420621** [openssl/openssl#14870]
hi there,thanks for your time in advance,I run into the the problem "Undefine refrence to EVP_sm4_cbc" when i use the "g++ -g sm4.cpp -o sm4 -lcrypto -lssl" command. there is my runing envirnment as follow:

openssl version:
OpenSSL 1.1.1k  25 Mar 2021

gcc version
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

ldd /usr/local/bin/openssl
   linux-vdso.so.1 =>  (0x00007fff7a6c3000)
   libssl.so.1.1 => /usr/local/lib64/libssl.so.1.1 (0x00007fa9cf116000)
   libcrypto.so.1.1 => /usr/local/lib64/libcrypto.so.1.1 (0x00007fa9cec2b000)
   libdl.so.2 => /lib64/libdl.so.2 (0x00007fa9cea27000)
   libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa9ce80b000)
   libc.so.6 => /lib64/libc.so.6 (0x00007fa9ce43d000)
   /lib64/ld-linux-x86-64.so.2 (0x00007fa9cf3a8000)

when i use "nm -D /usr/lib64/libcrypto.so|grep -w EVP_sm4_cbc", it output nothing.

i am wandering  if there are some parameter control(/enable/disable) the sm4 component feature when compile the openssl 

thanks again

**Comment by paulidale** [comment]
How are you accessing the SM4 algorithm?

**Comment by slontis** [comment]
Is sm4 in the enabled features list when you do?
> perl configdata.pm --dump

**Comment by slontis** [comment]
> nm -D libcrypto.so | grep -w EVP_sm4_cbc
Is finding an entry on my local build of 111.
unless it was configured with no-sm4 somehow that symbol should be there..

**Comment by paulidale** [comment]
The EVP_sm4_cbc() call is not one we export.  To access this cipher/mode you must use the higher level EVP calls.

**Comment by hql420621** [comment]
> How are you accessing the SM4 algorithm?

thanks your attention. i had sovle this problem by using the ` g++ -g sm4test.cpp -I/root/tools/ssl/include   -lcrypto -lssl` it seems that i have to add `-I/root/tools/ssl/include  ` opthions,but i encountered another problem when i run it,

the another problem is that it pops up double free and curporation when the program run in the postion of `EVP_CIPHER_CTX_free(ctx)` it is very confusing

there is my code snippet following


bool do_crypto(const EVP_CIPHER *cipher, const char* key, const char* iv, const unsigned char* in, int in_len, unsigned char* out, int* out_len, bool encrypt) {
    bool ret = false;
    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();
    int tmp = 0;
    int rst = EVP_CipherInit(ctx, cipher, reinterpret_cast<const unsigned char*>(key), reinterpret_cast<const unsigned char*>(iv), encrypt ? 1 : 0);
    if (rst != 1) goto RET;
    rst = EVP_CipherUpdate(ctx, out, &tmp, in, in_len);
    if (rst != 1) goto RET;
    *out_len = tmp;
 
    rst = EVP_CipherFinal(ctx, out + tmp, &tmp);
    if (rst != 1) goto RET;
    if (tmp > 0) {
        *out_len += tmp;
    }
 
    ret = true;
 
RET:
    EVP_CIPHER_CTX_free(ctx);
    ctx = NULL;
    return ret;
}
int main(){
........
const EVP_CIPHER *cipher = EVP_sm4_cbc();
 bool encryped = do_crypto(cipher, key, iv, reinterpret_cast<const unsigned char*>(plain_text), strlen(plain_text), cipher_text, &enc_len, true);
    assert(encryped);
    printf("the encryped string is %s:\n",cipher_text);
    bool decrypted = do_crypto(cipher, key, iv, cipher_text, enc_len, re_plain_text, &dec_len, false);
.........
}

thanks,brother!

**Comment by hql420621** [comment]
> nm -D libcrypto.so | grep -w EVP_sm4_cbc
> 
> Is finding an entry on my local build of 111.
> unless it was configured with no-sm4 somehow that symbol should be there..

thanks for your attention,my bro, yeah,it is there

nm -D /usr/local/lib64/libcrypto.so | grep -w EVP_sm4_cbc
0000000000174900 T EVP_sm4_cbc

i had sovle this problem by using the g++ -g sm4test.cpp -I/root/tools/ssl/include -lcrypto -lssl it seems that i have to add -I/root/tools/ssl/include opthions,but i encountered another problem when i run it,

the another problem is that it pops up double free and curporation when the program run in the postion of EVP_CIPHER_CTX_free(ctx) it is very confusing

there is my code snippet following

```
bool do_crypto(const EVP_CIPHER cipher, const char key, const char* iv, const unsigned char* in, int in_len, unsigned char* out, int* out_len, bool encrypt) {
bool ret = false;
EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();
int tmp = 0;
int rst = EVP_CipherInit(ctx, cipher, reinterpret_cast<const unsigned char*>(key), reinterpret_cast<const unsigned char*>(iv), encrypt ? 1 : 0);
if (rst != 1) goto RET;
rst = EVP_CipherUpdate(ctx, out, &tmp, in, in_len);
if (rst != 1) goto RET;
*out_len = tmp;

rst = EVP_CipherFinal(ctx, out + tmp, &tmp);
if (rst != 1) goto RET;
if (tmp > 0) {
    *out_len += tmp;
}

ret = true;
RET:
EVP_CIPHER_CTX_free(ctx);
ctx = NULL;
return ret;
}
int main(){
........
const EVP_CIPHER cipher = EVP_sm4_cbc();
bool encryped = do_crypto(cipher, key, iv, reinterpret_cast<const unsigned char>(plain_text), strlen(plain_text), cipher_text, &enc_len, true);
assert(encryped);
printf("the encryped string is %s:\n",cipher_text);
bool decrypted = do_crypto(cipher, key, iv, cipher_text, enc_len, re_plain_text, &dec_len, false);
.........
}

**Comment by slontis** [comment]
Use valgrind if you can..
Maybe the buffers you are using are too small to store the cipher_text or re_plain_text.

**Comment by hql420621** [comment]
> Use valgrind if you can..
> Maybe the buffers you are using are too small to store the cipher_text or re_plain_text.

thanks @slontis there is full error information,

the full code
```
#include <iostream>
#include <cassert>
#include <cmath>
#include <string.h>
#include <openssl/aes.h>
#include <openssl/evp.h>
#include <openssl/kdf.h>
 
const char *key = "www.cybersky.com";
char iv[16];

const char *plain_text = "www.cybersky.com";
 


bool do_crypto(const EVP_CIPHER *cipher, const char* key, const char* iv, const unsigned char* in, int in_len, unsigned char* out, int* out_len, bool encrypt) {
    bool ret = false;
    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();
    int tmp = 0;
    int rst = EVP_CipherInit(ctx, cipher, reinterpret_cast<const unsigned char*>(key), reinterpret_cast<const unsigned char*>(iv), encrypt ? 1 : 0);
    if (rst != 1) goto RET;
    rst = EVP_CipherUpdate(ctx, out, &tmp, in, in_len);
    if (rst != 1) goto RET;
    *out_len = tmp;
 
    rst = EVP_CipherFinal(ctx, out + tmp, &tmp);
    if (rst != 1) goto RET;
    if (tmp > 0) {
        *out_len += tmp;
    }
 
    ret = true;
 
RET:
    EVP_CIPHER_CTX_free(ctx);
    ctx = NULL;
    return ret;
}
 


int main(void) {
    //TODO init OPENSSL 
    memset(iv,'i',16);
    // EVP_CIPHER 是 OPENSSL 内置的一系列对称加密算法。可以使用 EVP_xxx_() 来获取，使用后无需释放。
    // OPENSSL 具体提供哪些内置算法可以在 evp.h 里查看
    const EVP_CIPHER *cipher = EVP_sm4_cbc();
    
 
    // 计算加解密结果 buffer 的大小。AES 对称加密后数据的大小与加密前相同。
    // 考虑到可能有 padding 存在，大小为大于输入的，最小的 AES_BLOCK_SIZE 倍整数。

    int out_len = ceil((float)strlen(plain_text) / AES_BLOCK_SIZE) * AES_BLOCK_SIZE;
    unsigned char *cipher_text = (unsigned char *)malloc(out_len);
    unsigned char *re_plain_text = (unsigned char *)malloc(out_len);
 
    //实际加解密输出的 buffer 大小
    int enc_len = 0, dec_len = 0; 
 
    /** Method 2
    * 使用 EVP_Cipher 系列函数
    */
    

    memset(cipher_text, 0, out_len);
    memset(re_plain_text, 0, out_len);
    bool encryped = do_crypto(cipher, key, iv, reinterpret_cast<const unsigned char*>(plain_text), strlen(plain_text), cipher_text, &enc_len, true);
    assert(encryped);
    printf("the encryped string is %s:\n",cipher_text);
    bool decrypted = do_crypto(cipher, key, iv, cipher_text, enc_len, re_plain_text, &dec_len, false);
    assert(decrypted);
    int cmp = strcmp(plain_text, reinterpret_cast<char*>(re_plain_text));
    printf("the decryped string is %s:\n",plain_text);
    assert(cmp == 0);

    free(cipher_text);
    free(re_plain_text);
 
    //TODO  free OPENSSL
 
    return 0;
}

the error information:
```
*** Error in `./sm4': double free or corruption (out): 0x00000000022b6050 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x7f407da07299]
./sm4[0x400df2]
./sm4[0x401174]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f407d9a8555]
./sm4[0x400c39]
======= Memory map: ========
00400000-00402000 r-xp 00000000 fd:00 17238237                           /root/730/src/pm_encrypt/sm4
00601000-00602000 r--p 00001000 fd:00 17238237                           /root/730/src/pm_encrypt/sm4
00602000-00603000 rw-p 00002000 fd:00 17238237                           /root/730/src/pm_encrypt/sm4
022b6000-022d7000 rw-p 00000000 00:00 0                                  [heap]
7f4078000000-7f4078021000 rw-p 00000000 00:00 0
7f4078021000-7f407c000000 ---p 00000000 00:00 0
7f407d566000-7f407d57d000 r-xp 00000000 fd:00 38221                      /usr/lib64/libpthread-2.17.so
7f407d57d000-7f407d77c000 ---p 00017000 fd:00 38221                      /usr/lib64/libpthread-2.17.so
7f407d77c000-7f407d77d000 r--p 00016000 fd:00 38221                      /usr/lib64/libpthread-2.17.so
7f407d77d000-7f407d77e000 rw-p 00017000 fd:00 38221                      /usr/lib64/libpthread-2.17.so
7f407d77e000-7f407d782000 rw-p 00000000 00:00 0
7f407d782000-7f407d784000 r-xp 00000000 fd:00 16942                      /usr/lib64/libdl-2.17.so
7f407d784000-7f407d984000 ---p 00002000 fd:00 16942                      /usr/lib64/libdl-2.17.so
7f407d984000-7f407d985000 r--p 00002000 fd:00 16942                      /usr/lib64/libdl-2.17.so
7f407d985000-7f407d986000 rw-p 00003000 fd:00 16942                      /usr/lib64/libdl-2.17.so
7f407d986000-7f407db4a000 r-xp 00000000 fd:00 16936                      /usr/lib64/libc-2.17.so
7f407db4a000-7f407dd49000 ---p 001c4000 fd:00 16936                      /usr/lib64/libc-2.17.so
7f407dd49000-7f407dd4d000 r--p 001c3000 fd:00 16936                      /usr/lib64/libc-2.17.so
7f407dd4d000-7f407dd4f000 rw-p 001c7000 fd:00 16936                      /usr/lib64/libc-2.17.so
7f407dd4f000-7f407dd54000 rw-p 00000000 00:00 0
7f407dd54000-7f407dd69000 r-xp 00000000 fd:00 16912                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f407dd69000-7f407df68000 ---p 00015000 fd:00 16912                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f407df68000-7f407df69000 r--p 00014000 fd:00 16912                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f407df69000-7f407df6a000 rw-p 00015000 fd:00 16912                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f407df6a000-7f407e06b000 r-xp 00000000 fd:00 16944                      /usr/lib64/libm-2.17.so
7f407e06b000-7f407e26a000 ---p 00101000 fd:00 16944                      /usr/lib64/libm-2.17.so
7f407e26a000-7f407e26b000 r--p 00100000 fd:00 16944                      /usr/lib64/libm-2.17.so
7f407e26b000-7f407e26c000 rw-p 00101000 fd:00 16944                      /usr/lib64/libm-2.17.so
7f407e26c000-7f407e355000 r-xp 00000000 fd:00 42108                      /usr/lib64/libstdc++.so.6.0.19
7f407e355000-7f407e555000 ---p 000e9000 fd:00 42108                      /usr/lib64/libstdc++.so.6.0.19
7f407e555000-7f407e55d000 r--p 000e9000 fd:00 42108                      /usr/lib64/libstdc++.so.6.0.19
7f407e55d000-7f407e55f000 rw-p 000f1000 fd:00 42108                      /usr/lib64/libstdc++.so.6.0.19
7f407e55f000-7f407e574000 rw-p 00000000 00:00 0
7f407e574000-7f407e5fa000 r-xp 00000000 fd:00 17603879                   /usr/local/lib64/libssl.so.1.1
7f407e5fa000-7f407e7f9000 ---p 00086000 fd:00 17603879                   /usr/local/lib64/libssl.so.1.1
7f407e7f9000-7f407e801000 r--p 00085000 fd:00 17603879                   /usr/local/lib64/libssl.so.1.1
7f407e801000-7f407e806000 rw-p 0008d000 fd:00 17603879                   /usr/local/lib64/libssl.so.1.1
7f407e806000-7f407eabf000 r-xp 00000000 fd:00 17603875                   /usr/local/lib64/libcrypto.so.1.1
7f407eabf000-7f407ecbf000 ---p 002b9000 fd:00 17603875                   /usr/local/lib64/libcrypto.so.1.1
7f407ecbf000-7f407ecea000 r--p 002b9000 fd:00 17603875                   /usr/local/lib64/libcrypto.so.1.1
7f407ecea000-7f407eced000 rw-p 002e4000 fd:00 17603875                   /usr/local/lib64/libcrypto.so.1.1
7f407eced000-7f407ecf1000 rw-p 00000000 00:00 0
7f407ecf1000-7f407ed13000 r-xp 00000000 fd:00 16929                      /usr/lib64/ld-2.17.so
7f407ef03000-7f407ef0a000 rw-p 00000000 00:00 0
7f407ef0f000-7f407ef12000 rw-p 00000000 00:00 0
7f407ef12000-7f407ef13000 r--p 00021000 fd:00 16929                      /usr/lib64/ld-2.17.so
7f407ef13000-7f407ef14000 rw-p 00022000 fd:00 16929                      /usr/lib64/ld-2.17.so
7f407ef14000-7f407ef15000 rw-p 00000000 00:00 0
7ffd61fbd000-7ffd61fde000 rw-p 00000000 00:00 0                          [stack]
7ffd61ff7000-7ffd61ff9000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

**Comment by hql420621** [comment]
> Use valgrind if you can..
> Maybe the buffers you are using are too small to store the cipher_text or r

**Comment by hql420621** [comment]
> Use valgrind if you can..
> Maybe the buffers you are using are too small to store the cipher_text or re_plain_text.

Thanks brother,your reply works! it runs succesfully when i try two following methods 

1. i allocate more 16 byte size buffers to re_plain_text
or
2. i use `EVP_CIPHER_CTX_set_padding(ctx, 0);` to disable the padding feature

there are another issue to to be create, does the openssl add padding by default even if the  size of original plain_text is the multiple of the 16, in my code ,the original input data is "www.cybersky.com" ,which length is already 16

**Comment by slontis** [comment]
padding is set to 1 by default.
This will add an extra 16-byte block even if the data is aligned.
You can see this by looking at the value returned from tmp for the update and final (The final adds the padding bytes).
If you turn off padding you will see the final returns a tmp of 0.

**Comment by hql420621** [comment]
> padding is set to 1 by default.
> This will add an extra 16-byte block even if the data is aligned.
> You can see this by looking at the value returned from tmp for the update and final (The final adds the padding bytes).
> If you turn off padding you will see the final returns a tmp of 0.

thanks very much ,i got it ,you help me a lot.

**Comment by slontis** [comment]
No problems - I will close this issue now..
