### ISSUE TITLE
CI: external-tests (95-test_external_krb5.t) fail for each PR

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#14902]
Any chance to get this fixed soon?

**Comment by XuanThuLe** [comment]
Ok

**Comment by XuanThuLe** [comment]
Ok

**Comment by mspncp** [comment]
There is some work in progress in https://github.com/openssl/openssl/pull/14872

**Comment by t8m** [comment]
@DDvO the #14872 now finally resolves this.
