### ISSUE TITLE
openssl 1.1.1d raspbian config failure build file wasn't produced [Raspbian / Raspbery Pi 3 Model B+]

### ISSUE THREAD

**Issue by antokxvi** [openssl/openssl#14909]
On my project, I implemented an algorithm called GIFT into OpenSSL om Raspberry Pi 3 Model B+, that have armv7l core. So, OpenSSL will later have the main cipher suite of the GIFT algorithm. in carrying out the implementation stages I carry out the stages according to what is given in the following link:

https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher#Create_the_Cipher

however, when I try to compile with

./sudo config --prefix = / opt / openssl-gift enable-gift

raises the error command:

Failure! build file wasn't produced. Please read INSTALL and associated NOTS files. You may also have to look over your available compiler tool chain or change your configuration.
***** Unsupported options: enable-gift

does anyone know about the problem? I really need a solution.

Thank you very much

**Comment by paulidale** [comment]
Did you add "gift" to config and Configure?  That's likely where that message is coming from.
Since this is for your use, I'd not bother making it conditionally compiled -- always include it.

You shouldn't need `sudo` for the configuration step either.

**Comment by levitte** [comment]
If you want to be able to enable gift, you must have "gift" among the items in `@disablables`. Did you do that?

**Comment by antokxvi** [comment]
> Did you add "gift" to config and Configure? That's likely where that message is coming from.
> Since this is for your use, I'd not bother making it conditionally compiled -- always include it.
> 
> You shouldn't need `sudo` for the configuration step either.

I have added "gift" to config and Configure, because I really follow the steps in
https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher#Create_the_Cipher

**Comment by antokxvi** [comment]
> If you want to be able to enable gift, you must have "gift" among the items in `@disablables`. Did you do that?

hhmm okay thank's, i wanna try it, because on the step that https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher#Create_the_Cipher given, add the algorithm to @disablables is optional, when we wanna disable the algorithm from OpenSSL. am I alright? Maybe i'm wrong, correct me please, thanks

**Comment by antokxvi** [comment]
> If you want to be able to enable gift, you must have "gift" among the items in . Did you do that?`@disablables`

okay, thank's, maybe it's failed because the syntax that i used is wrong, that not including --

**Comment by paulidale** [comment]
Is this resolved?

**Comment by paulidale** [comment]
Gone quiet, closing.
