### ISSUE TITLE
Dereferencing pointer to incomplete type RSA {aka struct rsa_st}

### ISSUE THREAD

**Issue by leagmain** [openssl/openssl#1491]
I meet this issue after I install openssl from latest code.
Can anyone help me with this?

Details : 
```
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/rand.h>
#include <openssl/bn.h>
#include <openssl/rsa.h>
...
BIGNUM* n = BN_new();
... // initialize n.
RSA* rsa = RSA_new();
rsa->n = n; // error happened here
```

OpenSSL version: OpenSSL 1.1.0-pre7-dev  xx XXX xxxx

Host ENV : Ubuntu Server 16.04  64Bit

**Comment by leagmain** [comment]
Temporarily, I use below code to fix this issue.
`#include "openssl/crypto/rsa/rsa_locl.h"`

openssl is the source directory of openssl

**Comment by vdukhovni** [comment]
> [@leagmain] Temporarily, I use below code to fix this issue.
> #include "openssl/crypto/rsa/rsa_locl.h"

This is very bad advice.  The reason the structures were made opaque is to enable
internal improvements without breaking the (new) ABI.  If applications bypass
the public interface and directly access internal structures, they are liable
to break with future patch updates.

DO NOT do this.  Instead port your code to use the new public accessors.

**Comment by richsalz** [comment]
What @vdukhovni said.  Closing issue..

**Comment by leagmain** [comment]
@vdukhovni Could you please tell me where can I find the new public accessors?

**Comment by leagmain** [comment]
https://wiki.openssl.org/index.php/1.1_API_Changes
Just found this.

**Comment by aiace9** [comment]
Same error here on Fedora 26 while compiling openwrt.

/tmp/openwrt/build_dir/host/u-boot-2014.10/lib/rsa/rsa-sign.c:279:21: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
  if (BN_num_bits(key->e) > 64)

**Comment by richsalz** [comment]
OpenSSL 1.1.0 is not necessarily source-compatible with previous releases.  We made many structures opaque and you can no longer do things like look directly at the fields in a struct.
The source you are using must be ported.

**Comment by mattcaswell** [comment]
You can use OpenSSL 1.0.2 with code that has not yet been ported to support OpenSSL 1.1.0
