### ISSUE TITLE
[BUG] A double free bug in openssl/apps/cmp.c

### ISSUE THREAD

**Issue by Yunlongs** [openssl/openssl#14910]
**File:** openssl/apps/cmp.c
**Bug Function:** setup_request_ctx
**Version:** Git-master(2021-4-18)

**Description:** In function `setup_request_ctx`,  `csr` is obtained via `load_csr_autofmt()` at line 1,583.
At line 1,587, `csr` is freed by `X509_REQ_free(csr)` at line 1,587 in the first time and `goto oom`.
But in the `oom` branch, `csr` is freed by `X509_REQ_free(csr)`  again at line 1,694, which is a double free bug.

**Code Description:**
```
static int setup_request_ctx(OSSL_CMP_CTX *ctx, ENGINE *engine)
{
    ...
    if (opt_csr != NULL) {
        if (opt_cmd == CMP_GENM) {
            CMP_warn("-csr option is ignored for command 'genm'");
        } else {
1583:       csr = load_csr_autofmt(opt_csr, "PKCS#10 CSR");
            if (csr == NULL)
                return 0;
            if (!OSSL_CMP_CTX_set1_p10CSR(ctx, csr)) {
1587:           X509_REQ_free(csr);   // csr is Freed Here !
                goto oom;
            }
        }
    }
    ....
 oom:
         CMP_err("out of memory");
 exts_err:
         sk_X509_EXTENSION_pop_free(exts, X509_EXTENSION_free);
1694:    X509_REQ_free(csr);   // csr is Freed again !
         return 0;
}


```

**Comment by paulidale** [comment]
It isn't clear if this is a double free or not.  The line above the free calls `OSSL_CMP_CTX_set1_p10CSR` which takes a reference to the object.  Thus the free call isn't actually freeing it.  What's not clear is what's happening later.

**Comment by t8m** [comment]
IMO this is a double free. If the OSSL_CMP_CTX_set1_p10CSR() fails it should not upref the csr. @DDvO ?

**Comment by DDvO** [comment]
Yes, it's a double free (on OSSL_CMP_CTX_set1_p10CSR() failure).
Thanks for the report and analysis.
Fix is in #14929.

**Comment by mspncp** [comment]
Seems like the otc hold isn’t necessary anymore @paulidale ?

**Comment by DDvO** [comment]
> Seems like the otc hold isn’t necessary anymore @paulidale ?

I see little sense in that label - likely a mistake?

**Comment by paulidale** [comment]
I put the hold on so we'd have a proper look.  Now that that has happened, I've removed the hold.
