### ISSUE TITLE
openssl speed -evp uses hw crypto, openssl speed does not

### ISSUE THREAD

**Issue by kestrel1974** [openssl/openssl#14912]
Hi,

I have set up openssl to use hw crypto with devcrypto. But when using openssl speed without -evp it does not use the hw algorithm. For example:
`
openssl speed -evp aes-128-cbc
`
uses hw crypto, all other commands do not:
```
openssl speed aes
openssl speed aes-128-cbc
openssl speed -engine devcrypto aes
openssl speed -engine devcrypto aes-128-cbc
```
Is there anything I can do about it? I tried the openssl.cnf but any change on the engines section, ciphers etc. does not have any effect.
In addition, now I wonder if for other functions, like using openvpn with openssl, do I always have to check and explicitly set any parameters if I want to use hw crypto?
Optional question, is there any way to specify to use hw crypto only above a certain blocksize, because e.g. for block size smaller than 256 bytes, hw crypto is slower than the default/software implementation, depending on algorithm?

Thanks in advance.

This is the version:
```
OpenSSL 1.1.1k  25 Mar 2021
built on: Tue Apr 13 12:00:49 2021 UTC
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr) 
compiler: mips-openwrt-linux-musl-gcc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT
```

This is the devcrypto environment:
```
openssl engine -pre DUMP_INFO devcrypto
(devcrypto) /dev/crypto engine
Information about ciphers supported by the /dev/crypto engine:
Cipher DES-CBC, NID=31, /dev/crypto info: id=1, driver=ifxdeu-cbc(des) (hw accelerated)
Cipher DES-EDE3-CBC, NID=44, /dev/crypto info: id=2, driver=ifxdeu-cbc(des3_ede) (hw accelerated)
Cipher BF-CBC, NID=91, /dev/crypto info: id=3, CIOCGSESSION (session open call) failed
Cipher CAST5-CBC, NID=108, /dev/crypto info: id=4, CIOCGSESSION (session open call) failed
Cipher AES-128-CBC, NID=419, /dev/crypto info: id=11, driver=ifxdeu-cbc(aes) (hw accelerated)
Cipher AES-192-CBC, NID=423, /dev/crypto info: id=11, driver=ifxdeu-cbc(aes) (hw accelerated)
Cipher AES-256-CBC, NID=427, /dev/crypto info: id=11, driver=ifxdeu-cbc(aes) (hw accelerated)
Cipher RC4, NID=5, /dev/crypto info: id=12, CIOCGSESSION (session open call) failed
Cipher AES-128-CTR, NID=904, /dev/crypto info: id=21, driver=ifxdeu-ctr(aes) (hw accelerated)
Cipher AES-192-CTR, NID=905, /dev/crypto info: id=21, driver=ifxdeu-ctr(aes) (hw accelerated)
Cipher AES-256-CTR, NID=906, /dev/crypto info: id=21, driver=ifxdeu-ctr(aes) (hw accelerated)
Cipher AES-128-ECB, NID=418, /dev/crypto info: id=23, driver=ifxdeu-ecb(aes) (hw accelerated)
Cipher AES-192-ECB, NID=422, /dev/crypto info: id=23, driver=ifxdeu-ecb(aes) (hw accelerated)
Cipher AES-256-ECB, NID=426, /dev/crypto info: id=23, driver=ifxdeu-ecb(aes) (hw accelerated)

Information about digests supported by the /dev/crypto engine:
Digest MD5, NID=4, /dev/crypto info: id=13, driver=ifxdeu-md5 (hw accelerated), CIOCCPHASH capable
Digest SHA1, NID=64, /dev/crypto info: id=14, driver=ifxdeu-sha1 (hw accelerated), CIOCCPHASH capable
Digest RIPEMD160, NID=117, /dev/crypto info: id=102, driver=unknown. CIOCGSESSION (session open) failed
Digest SHA224, NID=675, /dev/crypto info: id=103, driver=sha224-generic (software), CIOCCPHASH capable
Digest SHA256, NID=672, /dev/crypto info: id=104, driver=sha256-generic (software), CIOCCPHASH capable
Digest SHA384, NID=673, /dev/crypto info: id=105, driver=unknown. CIOCGSESSION (session open) failed
Digest SHA512, NID=674, /dev/crypto info: id=106, driver=unknown. CIOCGSESSION (session open) failed

[Success]: DUMP_INFO
```

**Comment by t8m** [comment]
This is not a bug, rather a missing feature. Simply in 1.1.1 the openssl speed command uses the low-level interfaces to access the symmetric ciphers and hashes unless you use the `-evp` option. As 1.1.1 is closed for features there is nothing to fix there. In master branch the speed was already modified to use the EVP APIs for everything at the cost of the speed results not being always fully comparable with 1.1.1 branch.

**Comment by mattcaswell** [comment]
> In addition, now I wonder if for other functions, like using openvpn with openssl, do I always have to check and explicitly set any parameters if I want to use hw crypto?

The decision as to whether to use EVP or not isn't configurable for most applications (it just happens to be with speed). Most applications tend to either use the low level interfaces (in which case they won't benefit from all acceleration possibilities) or they use EVP. This is just the way things are in 1.1.1. In 3.0, all low level interfaces are deprecated.

**Comment by kestrel1974** [comment]
Thanks guys for your replies and sheding a light on it.
