### ISSUE TITLE
Should EVP_CipherInit_ex(ctx, NULL, NULL, NULL, NULL, -1) always reset IV for all modes?

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14924]
Currently the IV is reset only for CBC, OFB and CFB modes in master and 1.1.1.

Ref #14882 #14704

**Comment by kaduk** [comment]
https://github.com/openssl/openssl/blob/045a893091994a5837a2bec9cc5646ae9ff07a2c/crypto/evp/evp_enc.c#L352-L356 is somewhat persuasive that we should *not* do so for CTR.  My recollection is that most (all?) of the other modes don't actually produce a situation where the values of iv and oiv differ.  If that's correct, reseting the IV would be a noop for those modes.

**Comment by mattcaswell** [comment]
OTC: No, this call should not reset IV for all modes.
