### ISSUE TITLE
OpenSSL 1.1.1j a fatal error in handshaking with memory  bios

### ISSUE THREAD

**Issue by jackwolf1024** [openssl/openssl#14923]
Hi ,
 I am using OpenSSL 1.1.1j, Now i have met a problem when using openssl with memory bios.
 The TLS handshake hops 4 times between client and server as shown in the snippet below:
1. <client -> server>: ClientHello
2. <server -> client>: ServerHello,Certificate*,ServerKeyExchange*, ...
3. <client -> server>: Certificate*,ClientKeyExchange,CertificateVerify*,...      | client handshake finished
4. <server -> client>: [ChangeCipherSpec]                                                     | server handshake finished
5. ------ Application Data        <------->        Application Data ----------

In my client project, I use one work thread for sending and another for receiving.
After step 3, handshaking of client is finished (SSL_is_init_finished() return 1), then sending thread begin send application data(SSL_write,BIO_read), and receiving thread got the last handshake data (BIO_write,and SSL_read) together.
At this point, BIO_read will return -1 in sending thread, SSL_get_error() return the SSL_ERROR_SYSCALL.

I guess when openssl is processing the last handshake data (step 4) and sending application data in another thread together is not permitted.

Is there any api can get the corrected handshake status for client when it complete the step 4.
Does anyone know about the problem? I really need a solution.

Thanks in advance!

**Comment by yangyangtiantianlonglong** [comment]
@jackwolf1024   If SSL_is_init_finished() return 1 both in sending's thread and  receing's thread, The SSL_write will  not  be able  to do BIO_read, because  s->statem.in_init eq 0, SSL_write will not do s->handshake_func, The SSL_read is similar.

**Comment by jackwolf1024** [comment]
@yangyangtiantianlonglong Thanks for your reply! 
I have tested my project for thousands of times, it is always crashed or return error in ssl.  I got the answer from https://www.openssl.org/docs/faq.html#PROG
"an SSL connection cannot be used concurrently by multiple threads." 
Then I used one std::mutex lock the ssl object in the sending thread and receving thread, It is ok now. 
Thank you!
