### ISSUE TITLE
Swift--use_frameworks!--[!] 

### ISSUE THREAD

**Issue by Jyaowen** [openssl/openssl#1492]
[!] The 'Pods-XXX' target has transitive dependencies that include static binaries: (Pods/OpenSSL/lib/libcrypto.a and /Pods/OpenSSL/lib/libssl.a)

delete "use_frameworks!" ,  pod openssl is ok
but other pod is lose ------  [!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: XXX

**Comment by richsalz** [comment]
This does not seem to be an openssl issue.

**Comment by togtalk** [comment]
![jjjjjjjjjjjjjjjjjjjj - copy](https://cloud.githubusercontent.com/assets/10146368/17957772/ffc455ce-6a9c-11e6-85b8-b4cc49703d02.jpg)

**Comment by togtalk** [comment]
yes Iwant to help me to get key hash Android for my apps
