### ISSUE TITLE
 s_client doesn't recognise XMPP STARTTLS messages with double quotes 

### ISSUE THREAD

**Issue by vladak** [openssl/openssl#1494]
The XMPP handling in s_client does not work when the server sends back attributes enclosed in double quotes. Using single or double quotes is valid per XML standard.

The problem is that no code should directly be testing/comparing the plain XMPP/XML output strings. Code should parse XML statements and build XML components. For example, `<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>` defines a `startttls` XML element with an `xmlns` attribute of value `urn:ietf:params:xml:ns:xmpp-tls`.

This has been reported elsewhere:
- https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1420608
- https://bugzilla.redhat.com/show_bug.cgi?id=608239

redhat suggests to address this by adding double quotes to the if clause. While this is certainly not optimal (proper XML parsing should be used), it is better than nothing.

**Comment by richsalz** [comment]
We’ve had an open ticket for five years (https://rt.openssl.org/Ticket/Display.html?id=2712) about this.

We are *not* going to put an xml parser into s_client :) Maybe we'll change the quotes, and maybe we'll change the case-ignore part, but things like XMLNS prefix... no.  Perhaps its most realistic to leave what we have, and encourage other folks to write an xml-aware program.

**Comment by vladak** [comment]
Either rip the XMPP code out of s_client or at least make it agnostic to the quotes, please.

**Comment by richsalz** [comment]
We’re not going to rip it out; you can always just not use it :)  Quotes or case, which is more important? :)

**Comment by vladak** [comment]
For my use case, definitely quotes.

**Comment by richsalz** [comment]
And per the original RT, it was case. :)  That's my point.

**Comment by levitte** [comment]
Why choose between quotes and case?  RT2712 has a fix for both

**Comment by richsalz** [comment]
My point was that it’s parsing XML as text, which will never completely work.

**Comment by levitte** [comment]
Okie

**Comment by levitte** [comment]
Either way, it's too late for 1.1.0, sorry.

**Comment by vladak** [comment]
In the master the quoting part of the problem was fixed in 4e48c77572a9a96a301e362a3646cd3cc7eca0f9
