### ISSUE TITLE
Please remove statement of adding Dual_EC_DRBG from release notes for future versions...

### ISSUE THREAD

**Issue by josephlhall** [openssl/openssl#1495]
The support for Dual_EC_DRBG seems to have been added in 2011:

https://github.com/openssl/openssl/commit/7fdcb45745c01b90b256fe97e87eae31453e11e6

But the 1.1.0 release notes still include the note from that time:

https://github.com/openssl/openssl/blob/abd30777cc72029e8a44e4b67201cae8ed3d19c1/CHANGES#L877

This cause a bit of confusion during today's release; would be great to zap that for future releases.

**Comment by richsalz** [comment]
Thanks joe ☺

**Comment by mattcaswell** [comment]
Fixed in a35d8fb168. Closing.
