### ISSUE TITLE
Runchecker failures

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14957]
Run checker failures since the beginning of March have all been fixed.

- `no-asm` #14980 logs indicate a time out during the tests, fixed by openssl/tools#86
- `no-autoalginit` #14960 make test fails to create `fipsmodule.cnf`, fixed by #14979
- `no-autoerrinit` #14961 make test fails in `test_err`, fixed by  #14976
- `no-des` #14958, fixed by #14975
- `no-dtls1_2` #14956, fixed by #15047
- `no-dtls1_2-method` #14956, fixed by #15047
- `no-ec2m` #14959, fixed by #14977
- `enable-fuzz-afl no-shared no-module` #14966, fixed by #15158
- `no-sm2`  #14962 logs indicate failure in `test_evp` which doesn't reproduce in master, possibly fixed by #14834
- `no-sm3`  #14963 logs indicate failure in `test_evp` which doesn't reproduce in master, possibly fixed by #14834
- `no-sock` #15054, fixed by #15055
- `no-stdio` #14953 fixes this
- `no-stdio` #15056 make test failing due to no apps,  fixed by #15057
- `no-tls1_2` #14964 `test_sslextension` fails, fixed by #14955
- `no-tls1_2-method` #14964 `test_sslextension` fails, fixed by #14955
- `no-tls1_3` #14965 `test_ssl_new` fails, fixed by #14978

These worked but have been re-confirmed:

- `no-dso` logs indicate that it runs currently which has been confirmed in master
- `no-pic` logs indicate that it runs currently which has been confirmed in master
- `enable-asan no-shared -DOPENSSL_SMALL_FOOTPRINT` logs indicate that it runs currently which has been confirmed in master

**Comment by t8m** [comment]
```
-d --strict-warnings no-tls1_2
-d --strict-warnings no-tls1_2-method
```
Should be fixed by #14955

**Comment by t8m** [comment]
```
-d --strict-warnings no-stdio
```
should be fixed by #14953

**Comment by paulidale** [comment]
Adding additional run-checker jobs in openssl/tools#84

**Comment by paulidale** [comment]
All the failing run-checker builds are good now.
The newly introduced builds can be handled elsewhere.
