### ISSUE TITLE
GOST engine external tests failed

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#14973]
e.g. https://github.com/openssl/openssl/pull/14972/checks?check_run_id=2400316825

OpenSSL cmdline: /home/runner/work/openssl/openssl/apps/openssl ocsp -issuer ocspCA-gost2001_A/cacert.pem -CAfile ocspCA-gost2001_A/cacert.pem -cert U_ocsp_gost2001_A/cert.pem -signer U_ocsp_gost2001_A/cert.pem -signkey U_ocsp_gost2001_A/seckey.pem -reqout request2.der
	STDERR CONTENTS:
	40C7F5815B7F0000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:82:No supported for the data to decode. Input type: DER, Input structure: pkcs8

Missed when did it appear first time

**Comment by t8m** [comment]
It is most probably a regression from #14834
Due to the external krb5 test failure at that time it was not noticed before merging.
@levitte do you have any idea why this regressed?

**Comment by beldmit** [comment]
I think so too

**Comment by beldmit** [comment]
@t8m, I'd also like to disable "expected failures" because of such troubles, but I'm afraid I'll not get any support...

**Comment by t8m** [comment]
@beldmit I do not understand what do you mean by disable "expected failures". If you mean that we should have disabled the failing krb5 test immediately, I do not think that would be a good idea.

The failure in krb5 test was caused by Github CI environmental changes and it took some time to find out the cause and the workaround. I do not think we should have disabled the test immediately otherwise we would risk not reviving it again as once it would be disabled it would not be pressing to resolve it.

Should we disable the gost engine test right away until we find the real cause for the regression and fix it? I do not think so.

**Comment by beldmit** [comment]
@t8m, I got a (possibly wrong) impression that krb5 tests were failing for a long time, being enabled. It's definitely better to have them.

**Comment by levitte** [comment]
That must be caused by i2d_PrivateKey changes or something like that.
I'll have a look tomorrow.

**Comment by levitte** [comment]
Uhmmmmmmm...  I can't reproduce this with current master

**Comment by beldmit** [comment]
I confirm it's still reproducable :(

**Comment by levitte** [comment]
Yup, found the issue, it's all in here:

https://github.com/openssl/openssl/blob/ed82976b43934789b5afa0641236d881b1aedd0e/crypto/store/store_result.c#L172-L442

What's happening is that `try_key_ref()`, `try_key_value()` and `try_key_value_legacy()` filter errors without knowing if the next of them being called will succeed or not...  that filtering needs to move up to `try_key()`...

**Comment by beldmit** [comment]
I don't understand why does it happen only in such a strange subset of tests.

**Comment by t8m** [comment]
I was looking at this out of curiosity and came up with this but it might be incomplete fix https://github.com/t8m/openssl/commit/c748c64f2fa3c56bf76065df5272f61fdb8a6699

**Comment by levitte** [comment]
You might hit another thing in there...  have you ever looked at what happens when you do `ERR_set_mark()` twice in a row?  How many `ERR_clear_last_mark()` / `ERR_pop_to_mark()` does it take to clear them?

**Comment by levitte** [comment]
With this, I discovered that the expectations on `evp_keymgmt_util_try_import()` differ in different places.  I'll fix that

**Comment by t8m** [comment]
@levitte will you incorporate my fix or should I submit a PR? But it causes a regression in evp_test which I'd have to investigate.

**Comment by levitte** [comment]
Well, I've done that same as you and am continuing...  I found a few glitches in other places too.  But yeah, the evp_test failure, which I'm also experiencing, is keeping me busy.

**Comment by levitte** [comment]
Did you ever figure out *why* you got in trouble with evp_test?

**Comment by t8m** [comment]
> Did you ever figure out _why_ you got in trouble with evp_test?

Nope, after looking at the failure for a while I've just started working on something else and never tried to investigate further.

**Comment by levitte** [comment]
Okie, I think I've figured it all out.  PR coming up as soon as I'm done testing.

**Comment by levitte** [comment]
See #15008
