### ISSUE TITLE
OpenSSL 1.1.0 does not compile for ARM with clang in Android NDK

### ISSUE THREAD

**Issue by yan12125** [openssl/openssl#1498]
I'm currently trying to upgrade OpenSSL 1.0.2h to 1.1.0. I got some assembler errors:
```
crypto/modes/ghash-armv4.s: Assembler messages:
crypto/modes/ghash-armv4.s:96: Error: bad instruction `ldrbpl r12,[r2,r3]'
crypto/modes/ghash-armv4.s:109: Error: bad instruction `ldrbpl r8,[r0,r3]'
crypto/modes/ghash-armv4.s:139: Error: bad instruction `ldrbne r12,[r2,#15]'
crypto/modes/ghash-armv4.s:204: Error: bad instruction `ldrbpl r12,[r0,r3]'
```
Steps to reproduce:
```
$ git clone -b cpython-hg https://github.com/yan12125/python3-android
$ cd python3-android
$ make openssl
```
This is my build scripts for CPython on Android. In this tree I use clang with ```-fno-integrated-as```, as suggested in https://github.com/android-ndk/ndk/issues/144. AArch64 builds fine, while arm gives strange errors as above.

**Comment by mattcaswell** [comment]
ping @dot-asm

**Comment by dot-asm** [comment]
> I use clang with -fno-integrated-as, as suggested [elsewhere]

But referred suggestion applies to aarch64, not 32-bit build. Consider even fbab8baddef8d3346ae40ff068871e2ddaf10270, where Google failed to compile it with clang and filed the bug report... If clang would reflect -fno-integrated-as in pre-defined macros, then it would be possible to have it both ways, but it doesn't... So we have to choose. And no special options normally take precedence. In other words adhere to integrated assembler in 32-bit case.

**Comment by yan12125** [comment]
Got lots of errors like this without ```-fno-integrated-as```:
```
crypto/ec/ecp_nistz256-armv4.s:3603:2: error: instruction requires: thumb2
 sbcs r9,r9,#-1
 ^
```
Seems it's more like an NDK issue instead of and OpenSSL one?

**Comment by dot-asm** [comment]
The torture never stops, huh? Error message makes no sense. It suggests that a) either thumb "mode" is engaged, but not thumb2; or b) thumb "mode" is not engaged and this instruction is available only in thumb2. If a) was the case, then it should fail much earlier, because in thumb-but-non-thumb2 you can only address 8 registers and there are references to higher registers earlier in the code. And b) is just plain wrong, the instruction in question is generic ARM one, i.e. available in non-thumb2 "mode". In other words it speaks in favour of suggestion that integrated assembler is out of shape. It's probably possible to work around the issue by replacing sbcs x,y,#-1 with adcs x,y,#1, but question is if we should sacrifice code readability for ability to compile with clearly broken assembler. So that you probably have no other choice but to stick to -fno-integrated-as even in 32-bit build. Could you see if it would be sufficient to mess up `#ifdef __clang__` in crypto/modes/asm/ghash-armv4.pl to compile the whole thing? I mean question is if ghash-armv4.pl is the *only* module that is problematic...

**Comment by yan12125** [comment]
> if ghash-armv4.pl is the only module that is problematic

Tried with ```make -i```. ```libssl.a``` links fine, and ```libcrypto.a``` fails with only one missing file: ```ghash-armv4.o```

**Comment by dot-asm** [comment]
> libcrypto.a fails with only one missing file: ghash-armv4.o

Hmmm... There is chacha-armv4 module that also has similar re-define, ldrhsb to ldrbhs. I wonder how it worked there, and if similar would work even here. Try to replace `#ifdef __clang__` in ghash-amv4 with `#if defined(__thumb2__) || defined(__clang__)`... I fail to see how it would do the trick, but do try...

**Comment by yan12125** [comment]
This patch:
```Diff
--- openssl-1.1.0/crypto/modes/asm/ghash-armv4.pl.orig	2016-08-27 21:54:58.003637668 +0800
+++ openssl-1.1.0/crypto/modes/asm/ghash-armv4.pl	2016-08-27 21:56:38.553634768 +0800
@@ -150,7 +150,7 @@
 .code	32
 #endif
 
-#ifdef  __clang__
+#if defined(__clang__) || defined(__thumb2__)
 #define ldrplb  ldrbpl
 #define ldrneb  ldrbne
 #endif
```
Fails with the same error messages. On the other hand
```Diff
--- openssl-1.1.0/crypto/modes/asm/ghash-armv4.pl.orig	2016-08-27 18:44:50.315238948 +0800
+++ openssl-1.1.0/crypto/modes/asm/ghash-armv4.pl	2016-08-27 18:45:13.035238124 +0800
@@ -150,11 +150,6 @@
 .code	32
 #endif
 
-#ifdef  __clang__
-#define ldrplb  ldrbpl
-#define ldrneb  ldrbne
-#endif
-
 .type	rem_4bit,%object
 .align	5
 rem_4bit:
```
Compiles and runs fine (CPython's test suite test_ssl passes).

By the way, my NDK version is r12b, and clang version is:
```
Android clang version 3.8.256229  (based on LLVM 3.8.256229)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
```
and GNU as version:
```
GNU assembler (binutils-2.25-0666073) 2.25.51.20141117
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `arm-linux-androideabi'.
```

**Comment by yan12125** [comment]
Verbose compilation commands:
```
$ /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7-none-linux-androideabi -gcc-toolchain /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot /opt/android-ndk/platforms/android-21/arch-arm/usr -I. -Icrypto/include -Iinclude -Icrypto -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/yen/Projects/python3-android/build/21-arm-linux-androideabi-4.9/share\"" -DENGINESDIR="\"/home/yen/Projects/python3-android/build/21-arm-linux-androideabi-4.9/lib/engines-1.1\"" -Wall -O3 -pthread -v -fPIE  -fno-integrated-as -fPIC -Wa,--noexecstack  -fPIC -MMD -MF crypto/modes/ghash-armv4.d.tmp -MT crypto/modes/ghash-armv4.o -c -o crypto/modes/ghash-armv4.o crypto/modes/ghash-armv4.s 
Android clang version 3.8.256229  (based on LLVM 3.8.256229)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
Found candidate GCC installation: /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x
Selected GCC installation: /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x
Candidate multilib: .;@m32
Selected multilib: .;@m32
clang: warning: argument unused during compilation: '-D DSO_DLFCN'
clang: warning: argument unused during compilation: '-D HAVE_DLFCN_H'
clang: warning: argument unused during compilation: '-D NDEBUG'
clang: warning: argument unused during compilation: '-D OPENSSL_THREADS'
clang: warning: argument unused during compilation: '-D OPENSSL_NO_DYNAMIC_ENGINE'
clang: warning: argument unused during compilation: '-D OPENSSL_PIC'
clang: warning: argument unused during compilation: '-D OPENSSL_BN_ASM_MONT'
clang: warning: argument unused during compilation: '-D OPENSSL_BN_ASM_GF2m'
clang: warning: argument unused during compilation: '-D SHA1_ASM'
clang: warning: argument unused during compilation: '-D SHA256_ASM'
clang: warning: argument unused during compilation: '-D SHA512_ASM'
clang: warning: argument unused during compilation: '-D AES_ASM'
clang: warning: argument unused during compilation: '-D BSAES_ASM'
clang: warning: argument unused during compilation: '-D GHASH_ASM'
clang: warning: argument unused during compilation: '-D ECP_NISTZ256_ASM'
clang: warning: argument unused during compilation: '-D POLY1305_ASM'
clang: warning: argument unused during compilation: '-D OPENSSLDIR="/home/yen/Projects/python3-android/build/21-arm-linux-androideabi-4.9/share"'
clang: warning: argument unused during compilation: '-D ENGINESDIR="/home/yen/Projects/python3-android/build/21-arm-linux-androideabi-4.9/lib/engines-1.1"'
clang: warning: argument unused during compilation: '-Wall'
clang: warning: argument unused during compilation: '-O3'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-MMD'
clang: warning: argument unused during compilation: '-MF crypto/modes/ghash-armv4.d.tmp'
clang: warning: argument unused during compilation: '-MT crypto/modes/ghash-armv4.o'
 "/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/as" -mfpu=neon -mfloat-abi=softfp -I . -I crypto/include -I include -I crypto --noexecstack -o crypto/modes/ghash-armv4.o crypto/modes/ghash-armv4.s
```

**Comment by dot-asm** [comment]
> On the other hand ... compiles and runs fine

But it will fail elsewhere, so that just removing that re-definition is not really an option. Fixing such problems is always a compromise...

**Comment by dot-asm** [comment]
ghash-armv4 will be modified to have following:
```
.text
#if defined(__thumb2__) || defined(__clang__)
.syntax unified
#endif
#if defined(__thumb2__)
.thumb
#else
.code   32
#endif

#ifdef  __clang__
#define ldrplb  ldrbpl
#define ldrneb  ldrbne
#endif
```
This makes it possible to compile with either -fno-integrated-as or without. As for omitting -fno-integrated-as and failure to compile ecp_nistz256-armv4. Well, add -mthumb to your command line. In other words there will be two working options to choose from: add -fno-integrated-as or -mthumb. Adding both works too...

**Comment by yan12125** [comment]
The latest git-master builds fine with ```-fno-integrated-as```, thanks! As a side note: ```-mthumb``` breaks CPython's ```_ssl``` module. I may report it to CPython.
