### ISSUE TITLE
Random Crash in X509_NAME_cmp OpenSSL version 1.1.1

### ISSUE THREAD

**Issue by georgi-m** [openssl/openssl#14984]
Hello All,

We are facing a random crash in X509_NAME_cmp function in "openssl/crypto/x509/x509_cmp.c" file. 
The OpenSSL version is 1.1.1g now (This crash came after migrating from 1.0.2 to 1.1.1). 
It is our custom build for ARM architecture.

Here is the gdb output for this crash(captured from OpenSSL version 1.1.1g). We have checked also 1.1.1k and the crash still there.

(gdb) bt
#0  0x000e09a8 in X509_NAME_cmp ()
#1  0x000e16bc in x509_object_cmp ()
#2  0x000ad50c in OBJ_bsearch_ex_ ()
#3  0x000dc9c4 in internal_find ()
#4  0x000e1f54 in x509_object_idx_cnt ()
#5  0x000e201c in X509_OBJECT_retrieve_by_subject ()
#6  0x000e1b18 in X509_STORE_CTX_get_by_subject ()
#7  0x0000a098 in X509_STORE_get_crl ()
#8  0x0000a274 in verify_callback ()
#9  0x000e5fd4 in internal_verify ()
#10 0x000e3bf4 in verify_chain ()
#11 0x000e3dbc in X509_verify_cert ()
#12 0x000221b8 in ssl_verify_cert_chain ()
#13 0x00040530 in tls_process_server_certificate ()
#14 0x0003d320 in read_state_machine ()
#15 0x0003cf70 in state_machine ()
#16 0x0002b0ac in SSL_do_handshake ()
#17 0x0000adf0 in fd_ready_for_connect ()
#18 0x00014b44 in event_process_active ()
#19 0x00014c04 in eloop_event_loop ()
#20 0x00008548 in main ()

Could you please help us to understand what is the problem or give some hint on how to proceed with this?

We found an old discussion about a similar issue here: https://mta.openssl.org/pipermail/openssl-dev/2016-February/005213.html

**Comment by yangyangtiantianlonglong** [comment]
Your func ```verify_callback``` is implemented by yourself, it is hook by``` void SSL_CTX_set_verify(SSL_CTX *ctx, int mode,
                        int (*cb) (int, X509_STORE_CTX *)) ```. It may has  a problem. How does it work?

**Comment by t8m** [comment]
Is this still valid with current release of openssl-1.1.1? Would you be able to build it with debug information to produce better stack trace?
