### ISSUE TITLE
Runchecker failure with no-asm: tests hang

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14980]
Output is:

```05-test_bf.t ....................... ok
05-test_cast.t ..................... ok
05-test_cmac.t ..................... ok
05-test_des.t ...................... ok
05-test_hmac.t ..................... ok
05-test_idea.t ..................... ok
05-test_rand.t ..................... ok
05-test_rc2.t ...................... ok
05-test_rc4.t ...................... ok
05-test_rc5.t ...................... skipped: rc5 is not supported by this OpenSSL build
06-test_algorithmid.t .............. ok
06-test_rdrand_sanity.t ............ ok
make[1]: *** [Makefile:3274: _tests] Terminated
make[1]: *** wait: No child processes.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: *** wait: No child processes.  Stop.
make: *** [Makefile:3271: tests] Terminated
```

The test following rdrand is the big number test which is slow.

**Comment by paulidale** [comment]
The ending point isn't deterministic.  For example, these have been seen too:

> 25-test_x509.t ..................... ok
> 15-test_ecdsa.t .................... ok

**Comment by t8m** [comment]
So apparently it is just reallyreally slow. Still can be problem with seeding the rng if the runchecker OS is old and does not support getrandom.

**Comment by paulidale** [comment]
I still can't login to the run-checker machine to figure this out.  @levitte.

**Comment by paulidale** [comment]
Hmmm....

This test runs on the run-checker host in just over 25 minutes.

The two longest running tests are:
> 04-test_encoder_decoder_legacy.t ... ok  1191522 ms
> 20-test_dhparam_check.t ............ ok   700571 ms
which amount to 32 minutes (4 processor test, so it's possible)

This could depend heavily on system load at the time.

**Comment by paulidale** [comment]
This is probably addressed by openssl/tools#86

**Comment by paulidale** [comment]
Optimised, the build time doesn't change a lot.  The test time is circa 6 minutes which is *much* better.

**Comment by paulidale** [comment]
Should be fixed, closing.
