### ISSUE TITLE
nmake install stuck in first step in windows

### ISSUE THREAD

**Issue by tavrez** [openssl/openssl#14994]
Greetings.
I tried to compile openssl 3.0.0-alpha.15 in Windows, `nmake` compiled everything fine, but `nmake install` stucked at the first step, which is `nmake depend`, which is running a perl command: `"perl.exe" ".\util\add-depends.pl" "VC"`.
I should also note alpha.14 was fine.
config data:
```
$ perl configdata.pm --dump
Command line (with current working directory = .):

    D:\linux\perl\bin\perl.exe Configure VC-WIN64A no-asm --prefix=d:\linux\openssl3 --openssldir=d:\linux\openssl3\conf

Perl information:

    D:\linux\perl\bin\perl.exe
    5.24.3 for MSWin32-x64-multi-thread

Enabled features:

    acvp_tests
    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    fips
    fips-securitychecks
    gost
    idea
    legacy
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    padlockeng
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    uplink
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng            [not-linux] OPENSSL_NO_AFALGENG
    asan                [default]   OPENSSL_NO_ASAN
    asm                 [option]    OPENSSL_NO_ASM
    buildtest-c++       [default]   
    crypto-mdebug       [default]   OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]   OPENSSL_NO_EGD
    external-tests      [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer      [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl            [default]   OPENSSL_NO_FUZZ_AFL
    ktls                [default]   OPENSSL_NO_KTLS
    md2                 [default]   OPENSSL_NO_MD2 (skip crypto\md2)
    msan                [default]   OPENSSL_NO_MSAN
    rc5                 [default]   OPENSSL_NO_RC5 (skip crypto\rc5)
    sctp                [default]   OPENSSL_NO_SCTP
    ssl-trace           [default]   OPENSSL_NO_SSL_TRACE
    trace               [default]   OPENSSL_NO_TRACE
    ubsan               [default]   OPENSSL_NO_UBSAN
    unit-test           [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers    [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]   
    zlib-dynamic        [default]   
    ssl3                [default]   OPENSSL_NO_SSL3
    ssl3-method         [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "lib",
    ARFLAGS => "/nologo",
    AS => "ml64",
    ASFLAGS => "/nologo /Zi",
    CC => "cl",
    CFLAGS => "/W3 /wd4090 /nologo /O2",
    CPP => "\"\$(CC)\" /EP /C",
    HASHBANGPERL => "/usr/bin/env perl",
    LD => "link",
    LDFLAGS => "/nologo /debug",
    MT => "mt",
    MTFLAGS => "-nologo",
    RANLIB => "CODE(0x25cf490)",
    RC => "rc",
    ar_resp_delim => "
",
    aroutflag => "/out:",
    asflags => "/c /Cp /Cx",
    asm_arch => "x86_64",
    asoutflag => "/Fo",
    bin_cflags => "/Zi /Fdapp.pdb",
    bin_lflags => "setargv.obj /subsystem:console /opt:ref",
    bn_ops => "SIXTY_FOUR_BIT",
    build_file => "makefile",
    build_scheme => [ "unified", "windows", "VC-common" ],
    cflags => "/Gs0 /GF /Gy /MD",
    coutflag => "/Fo",
    cpp_depend_flags => "/Zs /showIncludes",
    cppflags => "",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "OPENSSL_SYS_WIN32", "WIN32_LEAN_AND_MEAN", "UNICODE", "_UNICODE", "_CRT_SECURE_NO_DEPRECATE", "_WINSOCK_DEPRECATED_NO_WARNINGS" ],
    disable => [  ],
    dso_cflags => "/Zi /Fddso.pdb",
    dso_scheme => "win32",
    enable => [  ],
    ex_libs => "ws2_32.lib gdi32.lib advapi32.lib crypt32.lib user32.lib",
    includes => [  ],
    ld_implib_flag => "/implib:",
    ld_resp_delim => "
",
    lddefflag => "/def:",
    ldoutflag => "/out:",
    ldpostoutflag => "",
    ldresflag => " ",
    lflags => "",
    lib_cflags => "/Zi /Fdossl_static.pdb",
    lib_cppflags => "",
    lib_defines => [ "L_ENDIAN" ],
    module_cflags => "",
    module_cxxflags => undef,
    module_ldflags => "/dll",
    mtinflag => "-manifest ",
    mtoutflag => "-outputresource:",
    multilib => "-x64",
    perl_platform => "Windows::MSVC",
    perlasm_scheme => "auto",
    rcoutflag => "/fo",
    shared_cflag => "",
    shared_defflag => "",
    shared_defines => [  ],
    shared_ldflag => "/dll",
    shared_rcflag => "",
    shared_target => "win-shared",
    sys_id => "WIN64A",
    thread_defines => [  ],
    thread_scheme => "winthreads",
    unistd => "<unistd.h>",
    uplink_arch => "x86_64",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = lib
    ARFLAGS         = /nologo
    AS              = ml64
    ASFLAGS         = /nologo /Zi
    CC              = cl
    CFLAGS          = /W3 /wd4090 /nologo /O2
    CPP             = "$(CC)" /EP /C
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LD              = link
    LDFLAGS         = /nologo /debug
    LDLIBS          = 
    MT              = mt
    MTFLAGS         = -nologo
    PERL            = D:\linux\perl\bin\perl.exe
    RC              = rc
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    makefile

build file:

    makefile

build file templates:

    Configurations\common0.tmpl
    Configurations\windows-makefile.tmpl
    Configurations\common.tmpl
```

**Comment by mspncp** [comment]
I can confirm this issue (on Windows 10). However, it's not a 'hang': the Process Monitor indicates that the Perl script

```
C:\Strawberry\perl\bin\perl.exe ".\util\add-depends.pl" "VC"
```

is spending **a lot** of time scanning all these `libcrypto-*.d` files, without generating any output showing progress:

```
...
"23:49:55,7136560","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 8.192, Length: 8.192","SUCCESS"
"23:49:55,7165435","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 16.384, Length: 8.192","SUCCESS"
"23:49:55,7182249","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 24.576, Length: 8.192","SUCCESS"
"23:49:55,7227086","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 32.768, Length: 8.192","SUCCESS"
"23:49:55,7280174","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 40.960, Length: 8.192","SUCCESS"
"23:49:55,7309768","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 49.152, Length: 8.191","SUCCESS"
"23:49:55,7734020","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 57.343, Length: 8.192","SUCCESS"
"23:49:55,7846256","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 65.535, Length: 8.192","SUCCESS"
"23:49:55,7860635","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 73.727, Length: 8.192","SUCCESS"
"23:49:55,7885968","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 81.919, Length: 8.192","SUCCESS"
"23:49:55,7895546","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 90.111, Length: 8.192","SUCCESS"
"23:49:55,7902984","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 98.303, Length: 8.192","SUCCESS"
"23:49:55,7911464","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 106.495, Length: 8.192","SUCCESS"
"23:49:55,7921372","perl.exe","17440","ReadFile","C:\src\openssl\crypto\bio\libcrypto-shlib-bf_buff.d","Offset: 114.687, Length: 8.192","SUCCESS"
...
```


I'm suspecting that commit 16f2a444 might be the cause. However, I wasn't able to test my conjecture thoroughly, since building and testing on Windows is painfully slow, see #14055

**Comment by mspncp** [comment]
> I'm suspecting that commit [16f2a44](https://github.com/openssl/openssl/commit/16f2a44435fccbd7466b0659220c765a17e5d0c0) might be the cause. However, I wasn't able to test my conjecture thoroughly, since building and testing on Windows is painfully slow, see #14055

cc @tanzislam @levitte @beldmit

**Comment by levitte** [comment]
Oh!  The command to create the dependency files has changed from `$(CC)` to `$(CPP)`...  the latter has the flag `/EP`, which is ["Preprocess to stdout Without #line Directives"](https://docs.microsoft.com/en-us/cpp/build/reference/ep-preprocess-to-stdout-without-hash-line-directives)...  that's a sudden [censor]load of text to process!

It might be wise to have a separate config target command attribute specifically for generating dependency data...

**Comment by tanzislam** [comment]
Changing [`cpp_depend_flags` in `Configurations/10-main.conf`](https://github.com/openssl/openssl/blob/master/Configurations/10-main.conf#L1281) to:
```diff
-        cpp_depend_flags => "/Zs /showIncludes",
+        cpp_depend_flags => "/Zs /showIncludes /P /FiNUL",
```
avoids writing the preprocessed output to the `.d` file, but then the preprocessing runs much slower -- prob. because the `NUL` device is much slower than writing to a file.

**Comment by t8m** [comment]
> NUL device is much slower than writing to a file

Windows always surprises me.

**Comment by mspncp** [comment]
> The command to create the dependency files has changed from `$(CC)` to `$(CPP)`...

@levitte yes, I forgot to mention it explicitely, but the switch from  `$(CC)` to `$(CPP)` was exactly what triggered my suspicion. My analysis didn't go as deep as yours, I simply thought that parsing the output of `/showIncludes` would be more effective than parsing the full preprocessor output.

However, I still have a related question : when I reverted 16f2a44435fccbd7466b0659220c765a17e5d0c0 for testing, it became very obvious in the generated `makefile`that the compiler is invoked twice for every C module:

```
crypto\ec\libcrypto-lib-ecdsa_sign.obj: crypto\ec\ecdsa_sign.c
	$(CC)  $(LIB_CFLAGS) -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c $(COUTFLAG)$@ "crypto\ec\ecdsa_sign.c"

	$(CC)  $(LIB_CFLAGS) -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" $(LIB_CPPFLAGS)  -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM /Zs /showIncludes "crypto\ec\ecdsa_sign.c" 2>&1 > crypto\ec\libcrypto-lib-ecdsa_sign.d
```

I it really necessary to have two passes, couldn't that be done in one pass? That would save a lot of time I guess.

What also confuses me that the dependencies of the module are generated *after* building it. How does this make sense?

**Comment by tavrez** [comment]
> What also confuses me that the dependencies of the module are generated after building it. How does this make sense?

I also have this question, why those dependencies are generated in `nmake install` and not in `nmake`? And why they are not optional(adding some flags like `--gen-dependency` should trigger creating them, in build time)

**Comment by levitte** [comment]
> I it really necessary to have two passes, couldn't that be done in one pass? That would save a lot of time I guess.

`/showIncludes` prints on stderr, alongside all the error messages, warnings, ...  there's no way to get it to a separate file that I know of.  Yeah, that's a royal pain 😕 .

> What also confuses me that the dependencies of the module are generated _after_ building it. How does this make sense?

They are generated *during* build (it doesn't really matter which of the two commands come first in the same rule).  The idea is that with a pristine checkout, *everything* will be built anyway, so knowing all the dependencies isn't really necessary.  On the *next* build, you should have a full set of `.d` files, which are integrated into the Makefile.  Most of the times, this just works...  occasionally, when you move stuff around and add another include, or remove one, you need to run nmake twice...
The basic idea is that `make depend` shouldn't be a manual step, it should be as automated as possible.

**Comment by levitte** [comment]
> And why they are not optional(adding some flags like `--gen-dependency` should trigger creating them, in build time)

There is a configuration option to turn them off: `no-makedepend`

**Comment by mspncp** [comment]
@levitte are you saying that the 'makedepend' configure option is not necessary for a full build, that it's just an optimization for further builds?

If that is the case, then the 'makedepend' option should be disabled by default. Because regular users will build&install the binaries in one go using configure, make, make install. So there is no benefit from creating the dependency files, it only slows everything down. Only openssl developers working on the source code would benefit from this optimization. (And the benefit is limited by the fact that switching between topic branches very often requires reconfiguration and a full rebuild.)

My main motivation is that we ought to get the terrible build times on Windows back to reasonable values before the beta release (issue #14055). Using `no-makedepend` and `no-fips` I was able to reduce the build times significantly:

```
BUILD OPENSSL
20:39:39,53 start configure
20:40:21,36 start nmake
20:53:34,86 start nmake install
20:57:17,08 start nmake clean
20:57:50,51 done
```

A more detailed report will follow soon on #14055.

**Comment by mspncp** [comment]
Fun fact for @tanzislam and @levitte: I just happened to look into `libcrypto-lib-bio_enc.d` and this is what I found:

```
...
Hinweis: Einlesen der Datei:   C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h
Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_wtime.h
Hinweis: Einlesen der Datei:   C:\src\openssl\include\openssl/e_os2.h
Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include\stdint.h
...
```

It seems like the `add-depends.pl` doesn't work anyway if the compiler emits localized messages (which is the default in Visual Studio):

https://github.com/openssl/openssl/blob/d830526c711074fdcd82c70c24c31444366a1ed8/util/add-depends.pl#L191

**Comment by mspncp** [comment]
(Note: I *hate* localized warnings and error messages and normally I try to change it, but apparently I didn't bother to do it this time.)

**Comment by tanzislam** [comment]
@mspncp Could you try with this change in [`Configurations\windows-makefile.tmpl`](https://github.com/openssl/openssl/blob/master/Configurations/windows-makefile.tmpl#L839):

```diff
-	cmd /C "\$(CPP) $cflags $defs $target{cpp_depend_flags} $srcs > $dep 2>&1"
+	cmd /C "set VSLANG=1033 & chcp 437 >NUL & \$(CPP) $cflags $defs $target{cpp_depend_flags} $srcs > $dep 2>&1"
```
re-run `Configure` then `nmake`, and see if the `.d` files now get English messages? (I took the commands from [here](https://stackoverflow.com/questions/2286216/how-to-change-msbuild-error-message-language#comment114981372_48529386).)

**Comment by levitte** [comment]
Oh of course they meant for the `/showIncludes` to be for human consumption...  [facepalm]
On the other hand, if they keep that same format, then `/^[^:]*: [^:]*: /` could suffice...

**Comment by mspncp** [comment]
@tanzislam the stackoverflow solution you cited is eleven years old and doesn't seem to work for VS 2019 anymore. To speed up the testing, I did my experiments directly in the VS command prompt using the following command line:

```
C:\src\openssl>cl.exe /diagnostics:column /showIncludes "crypto\evp\bio_enc.c"
```

No combination of setting the `VSLANG` environment variable and/or modifying the codepage had any effect on the compiler output. (Also the [list of compiler options](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-by-category?view=msvc-160) does not indicate any way to change the localization of the diagnostic output.)

```
C:\src\openssl>set VSLANG=1033

C:\src\openssl>chcp 437
Aktive Codepage: 437.

C:\src\openssl>cl.exe /diagnostics:column /showIncludes "crypto\evp\bio_enc.c"
Microsoft (R) C/C++-Optimierungscompiler Version 19.28.29910 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

bio_enc.c
Hinweis: Einlesen der Datei: C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdio.h
Hinweis: Einlesen der Datei:  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt.h
Hinweis: Einlesen der Datei:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include\vcruntime.h
...
```

Apart from that, messing with the code page is not a good idea because it affects the current console, even if you wrap it int a `cmd /c` call: 

```
C:\src\openssl>chcp
Aktive Codepage: 850.

C:\src\openssl>cmd /c "chcp 437"
Aktive Codepage: 437.

C:\src\openssl>chcp
Aktive Codepage: 437.
```
So @levitte's suggestion to use a more general regular expression is probably the best solution.

**Comment by mspncp** [comment]
> Oh of course they meant for the /showIncludes to be for human consumption... [facepalm]

@levitte in defense of Microsoft I have to say: indeed, `/showIncludes` is not intended to produce machine parseable output, it's not a makedepend replacement. The information about the included files is printed in between the compiler messages as an aid for the developer to understand the include hierarchy.(*) So it is in fact natural to print those notifications in the same language as the other diagnostic output of the compiler.

(*) The `/showIncludes` option used to be very useful for the case when a syntax error in a module triggered an error in a header file. gcc shows the entire 'included by ...' hierarchy in such cases, but cl.exe wasn't that smart. But maybe this has changed by now.

**Comment by tanzislam** [comment]
@mspncp I just installed the German language pack from the VS2019 installer (I have a English installation), then did in a **x86 Native Tools Command Prompt for VS2019**:
```
set VSLANG=1031
cl /?
```
and the usage text did appear in German. Setting `VSLANG=1033` makes `cl /?` output appear in English. Seems to me that `VSLANG` is indeed supported, but it requires the specified Language Pack to be installed -- otherwise it falls back to one of the installed languages.

**Comment by mspncp** [comment]
Ok, it turns that on my computer only the german language pack was enabled. 

![image](https://user-images.githubusercontent.com/11467854/116014780-42db1c00-a637-11eb-9bb6-a433109ebcb8.png)

I don't recall deselecting the english language pack explicitly, I guess that VS simply installs only one language pack, the one for the language which you get to choose during the initial setup.

The consequence is that you can't rely on being able to switch to english output.

**Comment by levitte** [comment]
I'm reworking #15006 to accomodate for language variance for VC, among others.
