### ISSUE TITLE
AppVeyor unusably slow for pull requests

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#15003]
As the AppVeyor is unusably slow for pull requests I propose changing its configuration to run it only on pushes to the master (and possibly also 1.1.1) branch.

We could then probably also change the configuration so an existing running job is not cancelled on new push so we have a proper history of failures to track regressions.

**Comment by tanzislam** [comment]
I'm guessing this is same as #14994 (as AppVeyor, being Windows/MSVC, does `nmake test`), and perhaps will be fixed by #15001.

**Comment by t8m** [comment]
IMO it was too slow even before the change.

**Comment by levitte** [comment]
> IMO it was too slow even before the change.

Appveyor gives us very few parallel slots, meaning that jobs queue up pretty damn quickly.  I would rather drop it completely in favor of the Github actions windows build.

**Comment by t8m** [comment]
If we can limit it to be run only on pushes to master I do not see a reason why not keep it there running.

**Comment by t8m** [comment]
So, I think we can close this now. For new pull requests the AppVeyor will not be run anymore. We keep running AppVeyor on pushes.
