### ISSUE TITLE
RSA_verify() always failed.

### ISSUE THREAD

**Issue by YouliangHUANG** [openssl/openssl#15013]
When I used RSA_verify() to verify the signature, it always returns failed.
The error output is:
error:04091068:rsa routines:int_rsa_verify:bad signature:crypto/rsa/rsa_sign.c:220
Then I look up the file, and find out the line 220 is a marco.
The test environment is 5.10.30-1-MANJARO, openssl version is 1.1.1k.

**Comment by slontis** [comment]
There is not enough info in this issue for anyone to help you.

Note that m is the digest of the message  (not the message plaintext)..
 int RSA_verify(int type, const unsigned char *m, unsigned int m_len,
                unsigned char *sigbuf, unsigned int siglen, RSA *rsa);

**Comment by mattcaswell** [comment]
Not enough information. Closing.
