### ISSUE TITLE
OpenSSL 1.1.1d stuck on sudo make with enable custom cipher

### ISSUE THREAD

**Issue by antokxvi** [openssl/openssl#15012]
now, i'm on implementing a custom cipher, that called GIFT lightweight block cipher to the OpenSSL as a cipher suite algorithm on my Raspberry Pi 3 B+ with raspbianOS. on the step **sudo make** i'm stuck an got error like this

apps/libapps.a -lssl -lcrypto -ldl -pthread 
/usr/bin/ld: apps/speed.o: in function `GIFT128_encrypt_loop':
speed.c:(.text+0x6e8): undefined reference to `gift128_encrypt'
/usr/bin/ld: apps/speed.o: in function `speed_main':
speed.c:(.text+0x4128): undefined reference to `gift128_init'
/usr/bin/ld: speed.c:(.text+0xbd5c): undefined reference to `gift128_encrypt'
/usr/bin/ld: ./libcrypto.so: undefined reference to `gift128_decrypt'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6452: apps/openssl] Error 1
make[1]: Leaving directory '/home/pi/bismillah_ossl_gift'
make: *** [Makefile:174: all] Error 2

anybody have solution about that?

**Comment by beldmit** [comment]
If you are implementing a custom cipher in 1.1.1d, I'd recommend you to use it via EVP interface, not via low-level functions. If you are patching OpenSSL, you could register it simultaneously with other built-in ciphers. You may also need to patch the objects list.

**Comment by antokxvi** [comment]
> If you are implementing a custom cipher in 1.1.1d, I'd recommend you to use it via EVP interface, not via low-level functions. If you are patching OpenSSL, you could register it simultaneously with other built-in ciphers. You may also need to patch the objects list.

okay thanks guys, may i ask you reference or tutorial how to build the EVP interface that is not via low-level function?

**Comment by beldmit** [comment]
The EVP interface uses low-level functions. 

If you patch openssl 1.1.1x series itself, you could take a look into, e.g., crypto/evp/e_rc4.c

**Comment by paulidale** [comment]
This question looks like it has been answered.
