### ISSUE TITLE
rt.openssl.org's expired certificate

### ISSUE THREAD

**Issue by kousu** [openssl/openssl#15026]
rt.openssl.org's cert expired this month. It is [referenced in the curl source code](https://github.com/curl/curl/blob/67d3afa73f4cdb8a6c473f911c8af800121e0a49/lib/vtls/openssl.c#L3054) and maybe elsewhere.

![2021-04-25-165406_1485x927_scrot](https://user-images.githubusercontent.com/987487/116009312-db957b80-a5e6-11eb-9250-95124c795c05.png)

Is this server supposed to still be maintained?

**Comment by kaduk** [comment]
> Is this server supposed to still be maintained?

Not really -- see https://www.openssl.org/blog/blog/2016/10/12/f2f-rt-github/

It is (IIUC) kept up on a best-effort basis for the historical record, but is not expected to be in any normal workflows at this point.

**Comment by romen** [comment]
There is a request about renewing it also here: https://github.com/openssl/web/issues/226

It is a let's encrypt certificate, so maybe we just need to check up what happened with the renewal bot.
Maybe @levitte could help?

**Comment by kousu** [comment]
Thanks for taking a look.  I know how maintenance can be a headache.

**Comment by t8m** [comment]
The server does not exist anymore.
