### ISSUE TITLE
Too optimistic heuristics when auto detecting the private key format

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15022]
`d2i_AutoPrivateKey` function that is used for the auto-detection of the key type looks for the number of elements in the SEQUENCE of the DER key, using the number of elements as a detector of key type.

https://github.com/openssl/openssl/blob/513ead860853e0d07f7fc43bf35d1b90fdad5a11/crypto/asn1/d2i_pr.c#L83-L127

At least one of the Russian GOST commercial implementations adds an extra proprietary element to the SEQUENCE, so 3 elements turn into 4, and the GOST key is started being parsed as EC key, unsuccessfully.

When the PEM format is used, the PRIVATE KEY header indicates the format, and no heuristics is used, so the PKCS#8 PEM parser is used.

Don't know when this behavior was introduced. It seems that it was done last 6 months, though I can be mistaken.

**Comment by t8m** [comment]
This code is there since ages. So this is definitely not a recent regression.

**Comment by beldmit** [comment]
Yes, I've got this after checking the blame. The tests were introduced in the 1.0 age, and the failures after re-implementing the code on the top of 1.1.1 were not studied thoroughly enough.

**Comment by levitte** [comment]
Even though this code has been in for ages, it's still a bug.  We probably haven't heard about it earlier for the lack of PKCS#8-wrapped private keys with the attributes field populated...

From [RFC 5208](https://tools.ietf.org/html/rfc5208#section-5):


      PrivateKeyInfo ::= SEQUENCE {
        version                   Version,
        privateKeyAlgorithm       PrivateKeyAlgorithmIdentifier,
        privateKey                PrivateKey,
        attributes           [0]  IMPLICIT Attributes OPTIONAL }

**Comment by levitte** [comment]
A quick solution would be to try to unpack it as PKCS#8 first, and only do the heuristic as a fallback.  It's more churn, but...

**Comment by beldmit** [comment]
@levitte, do you think that the master legacy decoder will suffer from the same problem? If yes, I could submit a test to the gost-engine test suite.

**Comment by levitte** [comment]
> @levitte, do you think that the master legacy decoder will suffer from the same problem? If yes, I could submit a test to the gost-engine test suite.

Yes and no.  We go for the provider based decoders first, and since those use a trial method rather than shallow heuristics, they are less likely to mistake a PKCS#8 structure for a type specific structure.  There's a fallback to d2i_PrivateKey_legacy(), which does have the same problem as what you mention in this issue, but since d2i_PrivateKey_decoder() is likely to already have unpacked a PKCS#8 structure, it's less likely that  d2i_PrivateKey_legacy() is even reached.  That being said, it's not *wrong* to apply the same fix there as well.

**Comment by beldmit** [comment]
The bug is not reproducible with master.

**Comment by levitte** [comment]
> The bug is not reproducible with master.

Agreed, it's much harder to reach...  I might come up with a use case :wink:

**Comment by beldmit** [comment]
Let me come up with the upstream patch first...

**Comment by beldmit** [comment]
Fixed by #15075
