### ISSUE TITLE
confusing logic in apps/ocsp.c

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15036]
I don't think this is a 3.0 issue.

The flow of control start at https://github.com/openssl/openssl/blob/master/apps/ocsp.c#L606 seems confusing, if not confused.  The comment at `spawn_loop` says that function does not return.  And in the area of code from 606 to 647 there seem to be redundant tests against `acbio`

**Comment by nhorman** [comment]
ocsp.c has undergone significant change.  The referenced comment is missing, and the line numbers are no longer aligned.  Please update your comment to more clearly enumerate what you think this issues are here.

**Comment by nhorman** [comment]
The current comment for spawn_loop says this:

```
/*
 * Loop spawning up to `multi` child processes, only child processes return
 * from this function.  The parent process loops until receiving a termination
 * signal, kills extant children and exits without returning.
 */
```
which does seem somewhat...wrong.  It definately waits for a child process to exit, and when sees an exit, it kills the rest of them without returning.  What it doesn't do is actually spawn anything that I can see.  Whats more It doesn't appear that anything creates those child processes, so I'm lost as to how that happens.

@DDvO can you by any chance shed some light on that?

**Comment by t8m** [comment]
The forking happens just further down in the loop code. IMO this works as described in the comment. I am inclined to just close this issue.
