### ISSUE TITLE
3.0.0alpha15: "openssl crl" can not read from STDIN

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#15031]
Example from 1.1.1k:

openssl crl -noout -hash < /path/to/crl/ca-bundle.crl
fdd35eee

The same for 3.0.0alpha15:

openssl crl -noout -hash < /path/to/ca-bundle.crl
No filename or uri specified for loading CRL
Unable to load CRL

The same error happens when using a pipe to feed STDIN, which works for 1.1.1k as well.

Cross check: using the same file with "-in":

openssl crl -noout -hash -in /path/to/ca-bundle.crl
issuer name hash=fdd35eee

So the file in general works.

Further nit: The output format changed. I think that was supposed to get fixed by https://github.com/openssl/openssl/pull/14553, but that seems not to be enough. Should I open a second issue for the format change topic?

Thanks and regards,
Rainer

**Comment by mattcaswell** [comment]
> Should I open a second issue for the format change topic?

Yes please.

**Comment by rainerjung** [comment]
2nd issue (format change) opened: #15034

**Comment by slontis** [comment]
Fix is simple.. PR coming soon..
