### ISSUE TITLE
OSX - clang: error: unknown argument: '-mandroid'

### ISSUE THREAD

**Issue by ware16** [openssl/openssl#15043]
Hi, 

I am trying to build the 'FIPS object module (2.0.16)' for Android and based on it I want to build FIPS capable library (1.0.2n).
To build, I am using 
MAC OS: 10.14.6 
Apple clang version 11.0.0

setting following Environment variables:
```
export ANDROID_ABI=x86
export ANDROID_API=21
export OPENSSL_COMPILE=android-x86
export CROSS_COMPILE="i686-linux-android-"
export HOSTCC=clang
export LD=ld
export ANDROID_DEV=/Users/x/Library/Android/ndk-r18b/sysroot/usr
export ANDROID_ARCH_INC=/Users/x/Library/Android/ndk-r18b/sysroot/usr/include/i686-linux-android
export ANDROID_CLANG_INC=/Users/x/Library/Android/ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/7.0.2/include
export ANDROID_TOOLCHAIN=/Users/x/Library/Android/ndk-r18b/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin
export ANDROID_NDK_ROOT=/Users/x/Library/Android/ndk-r18b
export PATH=$ANDROID_TOOLCHAIN:$PATH
```

I want to build this for x86 architecture.

When I set the environment variables and run ./config, I don't see any issue.
When trying to run: make 

getting the following error:
```
clang: error: unknown argument: '-mandroid'
make[1]: *** [cryptlib.o] Error 1
make: *** [build_crypto] Error 1
```

Am I missing anything?

I have gone through many discussions in this forum but only find the problem definitions. Is there any way where I can use clang on MAC OS and build openSSL?

**Comment by t8m** [comment]
Unfortunately the 'FIPS object module (2.0.16)' is out of support. We are sorry, we cannot help you with the issue.

**Comment by ware16** [comment]
Thanks!
I tried it on CentOS and able to compile it.
