### ISSUE TITLE
sudo make 1.1.1d stuck error

### ISSUE THREAD

**Issue by antokxvi** [openssl/openssl#15059]
I enabling a custom cipher to openssl ver.1.1.1d that called gift128, but on my step 'sudo make', I'm stuck and got this error :

apps/libapps.a -lssl -lcrypto -lz -ldl -pthread 
/usr/bin/ld: apps/speed.o: in function 'gift128_encrypt_loop':
speed.c:(.text+0xba8): undefined reference to `gift128_encrypt'
/usr/bin/ld: apps/speed.o: in function `speed_main':
speed.c:(.text+0x41b8): undefined reference to `gift128_init'
/usr/bin/ld: ./libcrypto.so: undefined reference to `gift128_decrypt'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6452: apps/openssl] Error 1
make[1]: Leaving directory '/home/pi/openssl-gift'
make: *** [Makefile:174: all] Error 2

anybody knows the problem and how to fix it? thanks a alot

**Comment by richsalz** [comment]
Almost definitely the `sudo` command is dropping some environment variables.

You should really try to make things compile, test, run without `sudo`

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
