### ISSUE TITLE
Runchecker: failing with no-stdio due to dependence on apps

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#15056]
> $ make test
> make: *** No rule to make target 'apps/openssl', needed by 'providers/fipsmodule.cnf'.  Stop.

**Comment by richsalz** [comment]
I would say that if no-stdio is configured, don't build the test target either.  It was really intended for embedded environments like UEFI.  You could also add no-fips to the cascade as well.

**Comment by paulidale** [comment]
It looks like run-checker doesn't exercise these disablable options directly:
- `acvp_tests`
- `autoload-config`
- `buildtest-c++`
- `bulk`
- `cached-fetch`
- `cmp`
- `fips`
- `fips-securitychecks`
- `ktls`
- `legacy`
- `module`
- `pinshared`
- `padlockeng`
- `secure-memory`
- `siv`
- `tests`
- `tls`
- `uplink`
