### ISSUE TITLE
async_release_job may  crash  get NULL 

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#15063]
https://github.com/openssl/openssl/blob/c0a79e9836a9aa30912978f69fab3b3bb3a8ddc5/crypto/async/async.c#L137-L145
The var  pool  get NULL on line140, then it may  crash in line 143.  I find that my code occasionally gets a NULL value,and I don't  find the  probelm yet.

**Comment by slontis** [comment]
@paulidale - any ideas? There are quite few places in that file that dont check for NULL..
e.g async_start_func() ctx = async_get_ctx()

**Comment by paulidale** [comment]
Not sure.

I think the only way there'd be a NULL there is if an asynch context was moved between threads.  I don't think that's something we should try supporting.

**Comment by yangyangtiantianlonglong** [comment]
yes, @paulidale  is  right,  The thread is not destructed in this thread in the VXworks 5.5.
