### ISSUE TITLE
How to configure cryptodev in openssl-1.1.1j

### ISSUE THREAD

**Issue by trymine** [openssl/openssl#15062]
./Configure  --openssldir=$PWD/output --prefix=$PWD/output --cross-compil-prefix=xxxx -no-ssl3 no-autoerrinit shared linux-generic32 enable-engine enable-dso enable-devcryptoeng
I have add "enable-devcryptoeng"  and the following content was added at the end of the apps/openssl.cnf when config.
    ```
[default]
openssl_conf=openssl_def

[openssl_def]
# this is the main library configuration section
engines=engine_section

[engine_section]
# this is the engine configuration section, where the engines are listed
devcrypto=devcrypto_section

[devcrypto_section]
# this is the section where the devcrypto engine commands are used
CIPHERS=ALL
DIGESTS=NONE
    ```
but I insmod cryptodev.ko, run "openssl engine -c" on my board, I didn't see engine "cryptodev".

note:
openssl version 1.1.1j

**Comment by beldmit** [comment]
Try to put the line

openssl_conf=openssl_def

first in your config file

**Comment by trymine** [comment]
> Try to put the line
> 
> openssl_conf=openssl_def
> 
> first in your config file

I have put the line
openssl_conf=openssl_def
first in my config file (apps/openssl.cnf)
just like this 
```
#.include filename
openssl_conf=openssl_def
#This definition stops the following lines chiking if HOME isn't
defined.
HOME          = .
oid_section  = new_oids
......
......
[openssl_def]
engines=engine_section
[engine_section]
devcrypto=devcrypto_section
[devcrypto_section]
CIPHERS=ALL
DIGESTS=NONE
```
but it is still not works.

**Comment by trymine** [comment]
> Try to put the line
> 
> openssl_conf=openssl_def
> 
> first in your config file

For this configuration to take effect, should I actively call any function in the code in advance?
Or The configuration file will be automatically loaded when compiling?

**Comment by beldmit** [comment]
If you use the default config file, it should be processed automatically. Otherwise you can specify it via the OPENSSL_CONF environment variable.

**Comment by trymine** [comment]
> If you use the default config file, it should be processed automatically. Otherwise you can specify it via the OPENSSL_CONF environment variable.

I am very confused. In the 1.1.1j version or 1.1.1g version, to enable the devcrypto engine, that is, to call the "openssl engine" command to display the devcrypto engine, what conditions are required?
What I know so far is：
1、 Add enable-devcryptoeng option when Compile .(Don 't use OPENSSL_CONF)
2、Manual insmod cryptodev.ko/hardware_aaccelerate.ko when the system boot is complete.
I do not specify any configuration file, such as openssl.cnf.
As far as I know, other people can succeed through the above two operations.(It means "openssl engine" command can successfully displayed devcrypto).
Any help will be appreciated....

**Comment by beldmit** [comment]
I usually check if the openssl tried to load the engine via `strace`. I don't think the cryptodev engine is loaded by default. 

If it did not try to load, you can try either to load it via the config or via the command line for those commands that support it.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
