### ISSUE TITLE
Some old algorithms in PKCS#12 files don't work any more

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#15070]
Using alpha16-dev (1f3b58d8413cfa) compiled with `./config enable-md2 enable-rc5 no-shared enable-ec_nistp_64_gcc_128 -ggdb` on Fedora 32.

Some files that are readable with 1.1.1 aren't readable with 3.0.0-alpha16-dev, even with legacy provider loaded.

Algorithms affected:
 - PBES2 with RC2-CBC-128
 - PBES2 with RC2-CBC-40
 - PBES2 with RC2-CBC-64
 - PBES1 with pbeWithSHAAnd128BitRC4
 - PBES1 with pbeWithSHAAnd40BitRC4

Reproducer for RC2-CBC-128:
```
# compile openssl with old algorithms enabled
# checkout the keyfile corpus in parallel directory:
git clone https://github.com/redhat-qe-security/keyfile-corpus.git
cd openssl
apps/openssl pkcs12 -provider-path providers/ -provider legacy -provider default -in ../'keyfile-corpus/rsa(2048,sha256),cert&key(PBES2(PBKDF2(salt(8),iter(2048),keyLen(16),prf(default)),rc2-cbc(keyBits(56=128bit),IV(8)))),mac(sha1,salt(8),iter(2048)),pass(ascii).p12' -out /dev/null -info -nodes -passin file:../keyfile-corpus/password-ascii.txt
```

OpenSSL output:
```
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, RC2-CBC, Iteration 2048, PRF hmacWithSHA1
Error outputting keys and certificates
4057DE1C127F0000:error:0680006D:asn1 encoding routines:ASN1_TYPE_get_octetstring:data is wrong:crypto/asn1/evp_asn1.c:37:
4057DE1C127F0000:error:0300007A:digital envelope routines:evp_cipher_asn1_to_param_ex:cipher parameter error:crypto/evp/evp_lib.c:230:
4057DE1C127F0000:error:0300007A:digital envelope routines:PKCS5_v2_PBE_keyivgen:cipher parameter error:crypto/evp/p5_crpt2.c:149:
```

Reproducer for RC4:
```
apps/openssl pkcs12 -provider-path providers/ -provider legacy -provider default -in '../keyfile-corpus/rsa(2048,sha256),cert&key(pbeWithSHAAnd128BitRC4,salt(8),iter(2048)),mac(sha1,salt(8),iter(2048)),pass(ascii).p12' -out /dev/null -info -nodes -passin 'file:../keyfile-corpus/password-ascii.txt'
```
OpenSSL output:
```
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And128BitRC4, Iteration 2048
Error outputting keys and certificates
40374D13F17F0000:error:1180006A:PKCS12 routines:PKCS12_PBE_keyivgen:iv gen error:crypto/pkcs12/p12_crpt.c:61:
```

Other reproducers:
```
apps/openssl pkcs12 -provider-path providers/ -provider legacy -provider default -in '../keyfile-corpus/rsa(2048,sha256),cert&key(PBES2(PBKDF2(salt(8),iter(2048),keyLen(5),prf(default)),rc2-cbc(keyBits(160=40bit),IV(8)))),mac(sha1,salt(8),iter(2048)),pass(ascii).p12' -out /dev/null -info -nodes -passin 'file:../keyfile-corpus/password-ascii.txt'
apps/openssl pkcs12 -provider-path providers/ -provider legacy -provider default -in '../keyfile-corpus/rsa(2048,sha256),cert&key(PBES2(PBKDF2(salt(8),iter(2048),keyLen(8),prf(default)),rc2-cbc(keyBits(120=64bit),IV(8)))),mac(sha1,salt(8),iter(2048)),pass(ascii).p12' -out /dev/null -info -nodes -passin 'file:../keyfile-corpus/password-ascii.txt'
apps/openssl pkcs12 -provider-path providers/ -provider legacy -provider default -in '../keyfile-corpus/rsa(2048,sha256),cert&key(pbeWithSHAAnd40BitRC4,salt(8),iter(2048)),mac(sha1,salt(8),iter(2048)),pass(ascii).p12'  -out /dev/null -info -nodes -passin 'file:../keyfile-corpus/password-ascii.txt'
```

**Comment by t8m** [comment]
Hmm, did this regress recently? Could you try some previous alphas?

**Comment by sahanaprasad07** [comment]
I can try to fix this issue.

**Comment by tomato42** [comment]
I did try alpha1: did not compile; alpha2: doesn't support the -provider-path option so can't make it load the legacy provider; alpha10 fails in the same way

**Comment by paulidale** [comment]
@sahanaprasad07 you are welcome to try.

**Comment by paulidale** [comment]
#14434 does some major updates in this area, I don't know if it fixes this but it does make the code provider aware.

**Comment by sahanaprasad07** [comment]
@paulidale Oh yes, I'll wait and see what impact it has on this issue. Thanks!

**Comment by sahanaprasad07** [comment]
I confirm that the PR fixes the cases with RC4, but not RC2

**Comment by paulidale** [comment]
@jon-oracle any idea?

**Comment by jon-oracle** [comment]
I can manage to read a file with RC2/MD5 PBE encryption as long as both legacy and default providers are loaded. Using the PR in #14434 I ran:

./apps/openssl pkcs12 -provider-path=./providers -provider legacy -provider default -in 1key_ciph-PBE-MD5-RC2-64_iter-1000.p12

The file came from the PKCS#12 test app which was run using:

./test/pkcs12_format_test -test 2 -write

Note that I had to set OPENSSL_MODULES=./providers to pick up the legacy provider.

**Comment by tomato42** [comment]
Yes, I can see that PBES1 ciphers that use RC2 work, it's the combination of RC2 with PBES2 that's problematic

**Comment by jon-oracle** [comment]
> Yes, I can see that PBES1 ciphers that use RC2 work, it's the combination of RC2 with PBES2 that's problematic

Ah, ok. 

I've added NID_rc2_cbc to the list of algorithms in ./test/pkcs12_format_test.c in #14434 and generated a P12 file using PBES2. The file can be read using the v3.0 pkcs12 app but does fail with the v1.1.1 app installed on the system, which points to some incompatibility between the versions. This will need more investigation.

**Comment by jon-oracle** [comment]
@tomato42 could you post the steps you're using to create the file (or the file itself) with 1.1.1?

**Comment by sahanaprasad07** [comment]
> @tomato42 could you post the steps you're using to create the file (or the file itself) with 1.1.1?

@jon-oracle the files are here: 
git clone https://github.com/redhat-qe-security/keyfile-corpus.git

**Comment by tomato42** [comment]
I don't remember exactly how I created the files in the keyfile-corpus git repo, I think they were using `-keypbe RC2-CBC -certpbe RC2-CBC`, but that's just one key size, I might have generated the other key sizes by modifying the sources of the pkcs12 util.

What's a bit atypical in RC2-CBC in PKCS#8 encoding/PBCS#5 is that the key size is not specified directly, see https://tools.ietf.org/html/rfc8018#appendix-B.2.3

**Comment by jon-oracle** [comment]
@tomato42 this appears to be an issue with the provided cipher implementation. I've added a commit to fix this.

BTW - the keyfiles in your repo could be useful to add to OpenSSL regression tests, maybe as another external test. Do you foresee any problems with this?

**Comment by tomato42** [comment]
I published it so that people would use them :)
One possible gotcha is that there are few NSS-created files that are malformed, they have `malformed` in the name, you'll likely want to skip those
