### ISSUE TITLE
X509_get0_notBefore not found

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1507]
When I compile under linux with mingw some functions e.g. X509_get0_notBefore is there.

```
./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=$root_bin_dir/bin/$lib_dir_name/win64 enable-ssl-trace enable-crypto-mdebug no-deprecated
```

When I compile with Visual Studio 2015 x86 x64 command line, these functions are not there.

```
./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=$root_bin_dir/bin/$lib_dir_name/win64 enable-ssl-trace enable-crypto-mdebug no-deprecated
```

After removing `no-deprecate` option the function appears, but as far as I understood the _get0_ function are the new ones and should not be deprecated!

Written here in the docs:
https://www.openssl.org/docs/manmaster/crypto/X509_get_notBefore.html

**Comment by levitte** [comment]
Hmmm, this is a bit aged, and as far as I can see *now*, `X509_get0_notBefore` isn't deprecated, while `X509_get_notBefore` is.

I'm closing this.  If this issue reappears, feel free to create a new issue.
