### ISSUE TITLE
Handling of session tickets under TLS1.3

### ISSUE THREAD

**Issue by dmitri-d** [openssl/openssl#15079]
Is `new_session_cb` callback (set by `SSL_CTX_sess_set_new_cb`) supposed to be called on the client side when the server-side sends a `NewSessionTicket` message? In particular at the end of an ssl handshake?

If that's not the case, what is the correct way for a client to handle `NewSessionTicket`, considering that it may array at any time?

**Comment by mattcaswell** [comment]
> Is new_session_cb callback (set by SSL_CTX_sess_set_new_cb) supposed to be called on the client side when the server-side sends a NewSessionTicket message? In particular at the end of an ssl handshake?

In TLSv1.3 it gets called when the client processes a NewSessionTicket message (i.e. post handshake) *if* `SSL_SESS_CACHE_CLIENT` has been enabled via a call to `SSL_CTX_set_session_cache_mode`. See:

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_session_cache_mode.html

**Comment by dmitri-d** [comment]
> In TLSv1.3 it gets called when the client processes a NewSessionTicket message (i.e. post handshake) if SSL_SESS_CACHE_CLIENT has been enabled via a call to SSL_CTX_set_session_cache_mode

That's what I thought, but in my case (OpenSSL 1.1.1d) the callback is not being invoked; I have an info_callback setup and it shows that the server-side is trying to send session keys, but the client side has successfully completed the handshake. Provided the cache mode is set to `SSL_SESS_CACHE_CLIENT` could anything else prevent the callback from being invoked?

**Comment by davidben** [comment]
Tickets are post-handshake in TLS 1.3, so the client completing the handshake is not sufficient to get the ticket. The client also needs to pick up the post-handshake. This usually happens at some point in the application protocol itself, because it depends on the client calling `SSL_read`.

**Comment by dmitri-d** [comment]
> The client also needs to pick up the post-handshake NewSessionTicket message.

Is this supposed to be done via new_session_cb? If not, how should the application differentiate between data containing a ticket (as it can show up at any time) and application data itself?

**Comment by davidben** [comment]
new_session_cb will be called. and the application should not try to differentiate. If the server sent a ticket, SSL_read will consume it, call new_session_cb, and, assuming SSL_MODE_AUTO_RETRY is enabled (the default), continue on to the next record to look for application data.

**Comment by dmitri-d** [comment]
> SSL_read will consume it, call new_session_cb

Yep, it works now, this was the bit I was missing. tyvm for the explanation.
