### ISSUE TITLE
Minor typo change in ssl/s3_enc.c

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#151]
For c/cpp syntax analysis ambiguities, is it possible to change
in int ssl3_digest_cached_records(SSL *s)
memset(s->s3->handshake_dgst,0,SSL_MAX_DIGEST *sizeof(EVP_MD_CTX *));
to
memset(s->s3->handshake_dgst,0,SSL_MAX_DIGEST * sizeof(EVP_MD_CTX *));
(space added)
Thanks
Didier CRUETTE

**Comment by mattcaswell** [comment]
This was changed as part of the reformat work. Closing this issue.
