### ISSUE TITLE
OpenSSL 1.1.0: disable building test executables

### ISSUE THREAD

**Issue by vszakats** [openssl/openssl#1511]
Somewhere along the 1.1.0 alphas/betas the build system was patched to disable building the many test executables when configured with `no-unit-test`. This made build-time significantly shorter. In final 1.1.0 this method doesn't seem to be working anymore.

What is the current method to disable building tests?

/cc @levitte

**Comment by levitte** [comment]
Wellllll, not exactly.  `no-unit-test` is something different.  What we had was separate targets, `build_apps` and `build_tests`, but that proved cumbersome when fuzz testing was introduced.

We *do* have the provisions to disable tests (both building and running), except we never made it a direct configurable option, it currently only exists as a consequence of disabling stdio ( `no-stdio`).  Easily added.

**Comment by levitte** [comment]
#1514 should do what you ask for.  Just configure with `no-tests`

**Comment by vszakats** [comment]
Indeed, it was the different target.

Thank you very much for the PR. Not sure if this was a consequence of applying this patch alone onto 1.1.0 stable, but by itself, it wasn't enough to disable tests:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.883#L1356

Doing some further tests with `no-stdio`.

**Comment by levitte** [comment]
The `buildtest_FOO.c` builds are not functional tests, they are a verification that any header file we have is consistent enough to carry its on weight.  This is to have some minimal assurance that any external software will build against OpenSSL's headers (I've been thinking about extending it to refer to a small range of functions)

I did move those outside of the `$disabled{tests}` condition for a very specific reason, seen in commit 5cdad22f3e6ed5077b6c06dc2ac4edcea7bc0bb4

**Comment by vszakats** [comment]
Ah okay, I understand. It's only 15-20 seconds per platform on AppVeyor (a lot of log output though), so it's not a huge overhead. It'd still be nice to have such self-tests disabled for stable versions (my 2 cents), though I understand that even stable versions may have such combination of options that weren't build-tested and may fail.

All in all, `no-stdio` [turns out](https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.884#L2745) to break using OpenSSL with curl, but `no-tests` resolve this issue sufficiently. Thanks you very much for the patch!

**Comment by vszakats** [comment]
This is still valid and it'd be interesting IMO, but I sense it's a lost cause.

**Comment by gm42** [comment]
I have found that `no-tests` has become `no-unit-test` (correct me if I am wrong) on latest OpenSSL versions.

**Comment by Philosoph228** [comment]
Thank you all for advance. In my case I'd would build libraries only. How can I disable building of executable tool `openssl.exe` too?

**Comment by levitte** [comment]
There's a specific target that only builds libraries. Read INSTALL, I believe it's mentioned there.
