### ISSUE TITLE
libcrypto.def : error LNK2001: unresolved external symbol OSSL_ESS_check_signing_certs

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#15137]
I get the following linker errors for a Windows build with the latest commit:
```
libcrypto.def : error LNK2001: unresolved external symbol OSSL_ESS_check_signing_certs
libcrypto.def : error LNK2001: unresolved external symbol OSSL_ESS_signing_cert_new_init
libcrypto.def : error LNK2001: unresolved external symbol OSSL_ESS_signing_cert_v2_new_init
libcrypto.lib : fatal error LNK1120: 3 unresolved externals
```

The configure options:
set options=no-cmac no-ocsp no-ui-console no-sock no-dgram no-camellia no-idea no-rc2 no-md2 no-md4 no-sm3 no-sm4 no-mdc2 no-srp no-whirlpool no-seed no-rc4 no-rc5 no-cms no-scrypt no-cast no-err no-deprecated no-engine no-crypto-mdebug no-filenames no-async no-rmd160 no-blake2 no-comp no-ts no-gost no-ct no-chacha no-trace no-aria no-cmp no-legacy VC-WIN32 -DUNICODE -D_UNICODE -DWINVER=0x0601 -D_WIN32_WINNT=0x0601

**Comment by t8m** [comment]
Was it a clean build? Or rebuild of an existing build of an older checkout.

**Comment by matbech** [comment]
A clean build using these commands:
nmake -f makefile clean
nmake -f makefile build_libs

**Comment by t8m** [comment]
Fix in #15138

**Comment by matbech** [comment]
Thank you.

**Comment by t8m** [comment]
Not merged yet.
