### ISSUE TITLE
utility target to verify source checksums are okay

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15139]
It would be useful to have a "make verify-checksums" so that downstream vendors can make changes, config openssl, etc., and verify that they haven't (inadvertantly) messed up the FIPS module source checksum.  Of course, I don't care what word you use for `verify-checksums` :)

Performing that step should probably be part of the security policy's build instructions and I update #14865

**Comment by t8m** [comment]
This is now implemented as `make diff-fips-checksums` which is used by the FIPS Checkums CI job.

**Comment by richsalz** [comment]
great job, thanks!
