### ISSUE TITLE
Header files included from FIPS module sources are not checksummed

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#15133]
This is obviously missing as changes there might be FIPS relevant.

**Comment by levitte** [comment]
Hmmm, we should be able to do something smart with makedepend, no?

**Comment by paulidale** [comment]
I thought the original intent was to expand our header files and checksum the result.  Hence no need to checksum the headers themselves.

**Comment by t8m** [comment]
Yep, but the current checksumming does not work that way. Also is it possible to expand only our headers and not the system headers? I'd say it would be very unfortunate if changes to system headers changed the checksums.

**Comment by paulidale** [comment]
The idea was to not expand system headers.  How wasn't determined.

**Comment by levitte** [comment]
Filtering our headers contra system headers is fairly simple, already solved in util/add-depends.pl

**Comment by t8m** [comment]
@levitte Yes, filtering in list of headers is easy. I meant this in case we wanted to do the header expansion by the preprocessor. That would be IMO harder.

**Comment by richsalz** [comment]
Please see #15165

**Comment by rsbeckerca** [comment]
If you're in git, using `git grep` with a reasonable pattern is probably easier.

**Comment by t8m** [comment]
> If you're in git, using `git grep` with a reasonable pattern is probably easier.

We cannot depend on git in the checksumming targets.

**Comment by levitte** [comment]
> We cannot depend on git in the checksumming targets.

Perhaps not.  We can use it to collect file names into `providers/fips.module.sources`, though...
On the other hand, `grep -r` is another possibility that gives us the same functionality.

**Comment by levitte** [comment]
Another thought I had was that...  all our headers?  Really?  Even those that could be system installed, like all of those in include/openssl?  This would basically mean that *every time we add some EVP functionality, the FIPS module gets a new source checksum*, regardless if we actually use it in the FIPS module or not.

So, it seems to me that we need to think a bit more about exactly what header files we actually include into the checksum, and why.
For a moment, I was thinking that we might want to include `_local.h` headers, since they defined structures that might be used...  however, even then I'm pretty sure that we also make source code changes that would affect the checksum anyway.

**Comment by t8m** [comment]
Yep, this really needs some bigger discussion within OTC.

**Comment by richsalz** [comment]
> This would basically mean that every time we add some EVP functionality, the FIPS module gets a new source checksum, regardless if we actually use it in the FIPS module or not.

Please see #15165 which provides an answer to this question.

**Comment by levitte** [comment]
> > This would basically mean that every time we add some EVP functionality, the FIPS module gets a new source checksum, regardless if we actually use it in the FIPS module or not.
> 
> Please see #15165 which provides an answer to this question.

That script outputs the header files from include/openssl/ among others, which is exactly the problem

**Comment by paulidale** [comment]
> Even those that could be system installed, like all of those in include/openssl?

We have executable code in headers in include/openssl....

**Comment by richsalz** [comment]
> That script outputs the header files from include/openssl/ among others, which is exactly the problem

Maybe I don't understand the issue, but this:
```
./configdata.pm --query 'get_sources("providers/fips")' | ./util/find-deps -Iinclude -I...whatever...
```
And then feed that into xargs/dgst or whatever.

**Comment by levitte** [comment]
> Maybe I don't understand the issue

Let me be a bit bold then:

"This would basically mean that every time we add some EVP functionality, the FIPS module gets a new source checksum, **regardless if we actually use it in the FIPS module or *not***."

So any change, *even if not relevant for the FIPS module*, would trigger a new checksum, leading to revalidation or whatever, completely unnecessarily.

**Comment by richsalz** [comment]
Why aren't header files getting the same ifdef treatment that source files are?
And similarly pre-processed/filtered?

**Comment by levitte** [comment]
I would argue that it gives a lot of extra complication for no benefit at all.
Basically this reasoning: if we make any FIPS relevant changes in a header file, it's extremely likely that we do a change to a source file as well.  In other words, we get a relevant FIPS checksum change anyway.

**Comment by richsalz** [comment]
Suppose someone changes a name in the `prov_names` file?  And rebuidls a module and as far as anyone can tell it's valid.  They could even distribute source, as it's unlikely to be caught by everyone.

As Pauli pointed out, *there is code* in the header files.

Perhaps you should ask the lab.

**Comment by levitte** [comment]
> We have executable code in headers in include/openssl....

In this respect, using that in the FIPS module may turn out to be a mistake...

**Comment by mattcaswell** [comment]
OTC: All header files that are included by the FIPS module need to be checksummed. We do not need to add "ifdef FIPS_MODULE" at this stage.

**Comment by richsalz** [comment]
If you use the same scheme to pre-process the header files that you do for the source files, then the ifdef/ifndef "FIPS_MODULE" comes for free, right?

**Comment by richsalz** [comment]
So for now, everything in the header files is inside the FIPS boundary.  Got it. That seems like a reasonable trade-off at this point in the schedule. :)
