### ISSUE TITLE
OpenSSL-3.0.0 alpha-15 fails to support 3DES

### ISSUE THREAD

**Issue by dengert** [openssl/openssl#15141]
https://www.openssl.org/docs/OpenSSL300Design.html 
Says: "Legacy Provider Module" "DES (but not 3DES)" This implies 3DES is still available. But when with OpenSSL alpha-15 is built I don't see any 3DES ciphers or crypto routines.

Am I missing something?

 Since 3DES is built with 3 DES keys, I would expect des.h would still define DES_cblock and DES_LONG, but lines 14 -17 of des.h:
```
# include <openssl/macros.h>
# ifndef OPENSSL_NO_DEPRECATED_3_0
#  define HEADER_DES_H
# endif
```
ignore the rest of the header file. Additional ifdefs later in des.h test for `OPENSSL_NO_DEPRECATED_3_0`

I would suggest lines 14-17 be removed, and if needed add additional ifdefs later in des.h

**Comment by t8m** [comment]
Just do not configure no-deprecated build if you need low-level functions. With the no-deprecated build the DES and 3DES is still supported via the high level interfaces (EVP_CIPHER and so on).

**Comment by dengert** [comment]
OK, since EVP_CIPHER is now passing  `const unsigned char *key, const unsigned char *iv`  it is up to the application to store the key as  `unsigned char`, so defines like DES_LONG, and DES_cblock are no longer needed or defined. EVP_CIPHER_key_length() and EVP_MAX_KEY_LENGTH  can help the application.
