### ISSUE TITLE
SSL_OP_ almost no more bits

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15145]
Every 32-bit value from `0x00000001` to `0x80000000` is taken by an `SSL_OP` value.

I don't have any good suggestions on how to handle this, short of naming any new options with OPX and return two new API's to set/clear the OPX values.  Ugh.

**Comment by mattcaswell** [comment]
Not quite. 0x00000020U and 0x00000100U are still free.

**Comment by paulidale** [comment]
3.0 would be the time to change the APIs to long longs if we're possibly going to use both remaining ones.
I'm not sure it's a good idea.

**Comment by mattcaswell** [comment]
> change the APIs to long longs

`uint64_t` would be better

**Comment by t8m** [comment]
It would be a minor API break though.

**Comment by mattcaswell** [comment]
> It would be a minor API break though.

Yes. But if we're going to do it then 3.0 would be the time.

**Comment by t8m** [comment]
Setting beta1 milestone for OTC to evaluate if we want this change.

**Comment by paulidale** [comment]
Adding an OTC hold so it doesn't get missed.

**Comment by richsalz** [comment]
If the OTC wants to do this, I'll make the change.  I would prefer to write things as `1<<X` to make it more clear what the bits are. Suggestions for how to write that expression would be useful. But please wait until the OTC decides to move forward or not.

**Comment by richsalz** [comment]
See #15184.  "and then there was one."

**Comment by mattcaswell** [comment]
OTC: We should move this to uint64_t for the 3.0 beta

**Comment by richsalz** [comment]
I am working on a PR now.  What about the dane flags?

**Comment by mattcaswell** [comment]
This was fixed by #15230. Closing.
