### ISSUE TITLE
Openssl sends protocol_version alert when client hello has a valid version

### ISSUE THREAD

**Issue by I-mpossible** [openssl/openssl#15155]
## Description:

OpenSSL sends protocol_version alert for a client message with valid version. As shown in the capture file, the client message has valid version (record version 0x0301 TLS1.0 and handshake version 0x0303 TLS1.2). I think handshake_failure alert is more appropriate here.

## Environment:

Ubuntu 18.04

Openssl 1.1.1j

## How reproducible:

Steps to Reproduce:

```openssl s_server -key /path/to/key.pem -cert /path/to/cert.pem -accept 44330 -tls1_2 -www -no_ticket```

```echo -n -e "\x16\x03\x01\x00\xd2\x01\x00\x00\xce\x03\x03\xd9\xfd\xd9\x6f\x24\x3e\xb6\x21\x69\xa7\xc3\x90\x12\x07\xc3\x20\x90\x7c\x9f\x98\x1c\x84\xf5\x36\xe5\x3f\x0e\x6c\xa8\x0c\x7d\x46\x20\x38\xcd\x7c\x7f\x3e\xa9\xb3\x4f\x41\xa1\x47\xb6\x4f\x29\x68\x8c\x85\x14\x0f\xb1\x90\xe5\x78\xb3\x71\xf7\x3e\x85\xbb\x33\x42\xbf\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x7d\x00\x0b\x00\x04\x03\x00\x01\x02\x00\x0a\x00\x0c\x00\x0a\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00\x23\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\x0d\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\x09\x08\x0a\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x00\x2b\x00\x03\x02\x03\x04\x00\x2d\x00\x02\x01\x01\x00\x33\x00\x26\x00\x24\x00\x1d\x00\x20\x6d\x3f\x07\xca\x6e\x4a\xee\x67\x2d\xcf\x24\x9a\x50\x7b\x1e\x9f\xa7\x3a\xda\xb9\xc0\xfc\xd7\xdf\x9a\x6f\x98\x01\x5d\x26\xbf\x43" | nc 127.0.0.1 44330```

## Actual results:

Openssl sends protocol_version alert. The capture file is attached.

## Expected results:

Send handshake_failure alert to client.

## Attachments:
[openssl capture.zip](https://github.com/openssl/openssl/files/6425529/openssl.capture.zip)

**Comment by mattcaswell** [comment]
The definition of `protocol_version` is:

````
   protocol_version:  The protocol version the peer has attempted to
      negotiate is recognized but not supported (see Appendix D).
````

This is exactly the case here so this alert seems appropriate.

**Comment by I-mpossible** [comment]
> The definition of `protocol_version` is:
> 
> ```
>    protocol_version:  The protocol version the peer has attempted to
>       negotiate is recognized but not supported (see Appendix D).
> ```
> 
> This is exactly the case here so this alert seems appropriate.

Sorry, I don't get it. The client is sending valid version: record layer version 0x0301 TLS1.0 and handshake layer version 0x0303 TLS1.2. Here is a regular handshake where such version is accepted.
[regular handshake.zip](https://github.com/openssl/openssl/files/6427163/regular.handshake.zip)

**Comment by mattcaswell** [comment]
> The client is sending valid version

Exactly. The version is valid and recognised. It's just that the server does not support it. Hence, protocol_version is the correct alert.

**Comment by I-mpossible** [comment]
I think the server supports it. In the regular handshake capture, you can see client hello with such versions can successfully complete the handshake.

**Comment by mattcaswell** [comment]
> I think the server supports it.

It doesn't. The server is configured to support TLSv1.2 only (via the command line flag "-tls1_2"). But this is a TLSv1.3 ClientHello as can be seen from the "supported_versions" extension:

````
Header:
  Version = TLS 1.0 (0x301)
  Content Type = Handshake (22)
  Length = 210
    ClientHello, Length=206
      client_version=0x303 (TLS 1.2)
      Random:
        gmt_unix_time=0xD9FDD96F
        random_bytes (len=28): 243EB62169A7C3901207C320907C9F981C84F536E53F0E6CA80C7D46
      session_id (len=32): 38CD7C7F3EA9B34F41A147B64F29688C85140FB190E578B371F73E85BB3342BF
      cipher_suites (len=8)
        {0x13, 0x02} TLS_AES_256_GCM_SHA384
        {0x13, 0x03} TLS_CHACHA20_POLY1305_SHA256
        {0x13, 0x01} TLS_AES_128_GCM_SHA256
        {0x00, 0xFF} TLS_EMPTY_RENEGOTIATION_INFO_SCSV
      compression_methods (len=1)
        No Compression (0x00)
      extensions, length = 125
        extension_type=ec_point_formats(11), length=4
          uncompressed (0)
          ansiX962_compressed_prime (1)
          ansiX962_compressed_char2 (2)
        extension_type=supported_groups(10), length=12
          ecdh_x25519 (29)
          secp256r1 (P-256) (23)
          ecdh_x448 (30)
          secp521r1 (P-521) (25)
          secp384r1 (P-384) (24)
        extension_type=session_ticket(35), length=0
        extension_type=encrypt_then_mac(22), length=0
        extension_type=extended_master_secret(23), length=0
        extension_type=signature_algorithms(13), length=30
          ecdsa_secp256r1_sha256 (0x0403)
          ecdsa_secp384r1_sha384 (0x0503)
          ecdsa_secp521r1_sha512 (0x0603)
          ed25519 (0x0807)
          ed448 (0x0808)
          rsa_pss_pss_sha256 (0x0809)
          rsa_pss_pss_sha384 (0x080a)
          rsa_pss_pss_sha512 (0x080b)
          rsa_pss_rsae_sha256 (0x0804)
          rsa_pss_rsae_sha384 (0x0805)
          rsa_pss_rsae_sha512 (0x0806)
          rsa_pkcs1_sha256 (0x0401)
          rsa_pkcs1_sha384 (0x0501)
          rsa_pkcs1_sha512 (0x0601)
        extension_type=supported_versions(43), length=3
          TLS 1.3 (772)
        extension_type=psk_key_exchange_modes(45), length=2
          psk_dhe_ke (1)
        extension_type=key_share(51), length=38
            NamedGroup: ecdh_x25519 (29)
            key_exchange:  (len=32): 6D3F07CA6E4AEE672DCF249A507B1E9FA73ADAB9C0FCD7DF9A6F98015D26BF43

````

**Comment by paulidale** [comment]
Answered, closing.
