### ISSUE TITLE
X509_NAME_hash fail to hash android emulator system CA certs

### ISSUE THREAD

**Issue by ncy94** [openssl/openssl#15154]
The function `X509_NAME_hash` doesn't work with Android emulator's system CA certs. 

When I use libcurl (7.76.1) built with openssl (1.1.1k), setting `curl_easy_setopt(curl, CURLOPT_CAPATH, "/system/etc/security/cacerts");`, curl returns error `CURLE_SSL_CACERT`. 

However, when I change the code in `openssl-1.1.1k/crypto/x509/by_dir.c` line to 
```
#if defined(__ANDROID__)
  h = X509_NAME_hash_old(name);
#else
  h = X509_NAME_hash(name);
#endif
```
The above problem gets solved.

**Comment by kaduk** [comment]
If I'm reading the history correctly, the "old" hash algorithm was only used in versions of openssl prior to 1.0.0.  I wonder if this incompatibility has been around since 1.0.0 as well?

**Comment by t8m** [comment]
> If I'm reading the history correctly, the "old" hash algorithm was only used in versions of openssl prior to 1.0.0. I wonder if this incompatibility has been around since 1.0.0 as well?

Yes, IMO this is definitely the case.

**Comment by ncy94** [comment]
It seems so because I found a post saying the same problem, with openssl version 1.0.1h: https://stackoverflow.com/questions/25253823/how-to-make-ssl-peer-verify-work-on-android

I wonder if it safe to use the old `X509_NAME_hash_old`? We would like to get our android build running by this change

**Comment by t8m** [comment]
> I wonder if it safe to use the old `X509_NAME_hash_old`? We would like to get our android build running by this change

It uses MD5 instead of SHA1. Which, for this particular case, does not bring any serious security implications as the hashes are truncated anyway with inevitable collisions appearing which should be handled fine with the cert store loading. 

We do not want to change this in our sources though as that would make them incompatible with builds using the X509_NAME_hash and using a private cert store with the new hashes.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
