### ISSUE TITLE
Some strangeness in fips checksummed sources

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#15157]
We include all the sources in libimplementations.a in the fips checksummed sources. That seems incorrect as there are clearly some sources that compile to object files that are not supposed to be included in the fips provider at all.

Namely:
```
providers/common/der/der_sm2_gen.c.in
providers/common/der/der_sm2_key.c
providers/common/der/der_sm2_sig.c
providers/implementations/asymciphers/sm2_enc.c
providers/implementations/ciphers/cipher_aria.c
providers/implementations/ciphers/cipher_aria_ccm.c
providers/implementations/ciphers/cipher_aria_ccm_hw.c
providers/implementations/ciphers/cipher_aria_gcm.c
providers/implementations/ciphers/cipher_aria_gcm_hw.c
providers/implementations/ciphers/cipher_aria_hw.c
providers/implementations/ciphers/cipher_camellia.c
providers/implementations/ciphers/cipher_camellia_hw.c
providers/implementations/ciphers/cipher_chacha20.c
providers/implementations/ciphers/cipher_chacha20_hw.c
providers/implementations/ciphers/cipher_chacha20_poly1305.c
providers/implementations/ciphers/cipher_chacha20_poly1305_hw.c
providers/implementations/ciphers/cipher_null.c
providers/implementations/ciphers/cipher_sm4.c
providers/implementations/ciphers/cipher_sm4_hw.c
providers/implementations/digests/blake2_prov.c
providers/implementations/digests/blake2b_prov.c
providers/implementations/digests/blake2s_prov.c
providers/implementations/digests/md5_prov.c
providers/implementations/digests/md5_sha1_prov.c
providers/implementations/digests/sm3_prov.c
providers/implementations/encode_decode/decode_der2key.c
providers/implementations/encode_decode/decode_msblob2key.c
providers/implementations/encode_decode/decode_pem2der.c
providers/implementations/encode_decode/decode_pvk2key.c
providers/implementations/encode_decode/encode_key2any.c
providers/implementations/encode_decode/encode_key2blob.c
providers/implementations/encode_decode/encode_key2ms.c
providers/implementations/encode_decode/encode_key2text.c
providers/implementations/encode_decode/endecoder_common.c
providers/implementations/kdfs/scrypt.c
providers/implementations/macs/blake2b_mac.c
providers/implementations/macs/blake2s_mac.c
providers/implementations/macs/poly1305_prov.c
providers/implementations/macs/siphash_prov.c
providers/implementations/rands/seed_src.c
providers/implementations/rands/seeding/rand_cpu_x86.c
providers/implementations/rands/seeding/rand_tsc.c
providers/implementations/rands/seeding/rand_unix.c
providers/implementations/rands/seeding/rand_win.c
providers/implementations/signature/sm2sig.c
providers/implementations/storemgmt/file_store.c
providers/implementations/storemgmt/file_store_der2obj.c
```

I've tried to put some of these into libnonfips.a instead of libimplementations.a but that did not seem to work for some reason.

**Comment by t8m** [comment]
> I've tried to put some of these into libnonfips.a instead of libimplementations.a but that did not seem to work for some reason.

Ah, the weak dependency of libimplementations.a on libnonfips.a causes that. If I comment it out it will work as expected.

Obviously it is not a good idea. Probably the get_sources query should somehow avoid weak deps.

**Comment by levitte** [comment]
This is a clash of ideas.

libimplementations.a came with the idea that all implementations would be placed in one library, and that each provider could simply refer to whatever they see fit, and linking would do the rest.  It's a nice idea, but doesn't allow the segregation of FIPS vs non-FIPS stuff, so we get everything.

I can see two ways this could be solved:

1.  Throw away libimplementations.a and rather use the source directly with the applicable provider.
    In all build.info files, it would mean changing any of these lines:
    
    ```
    SOURCE[libimplementations.a]=something.c
    ```
    
    to: 
    
    ```
    SOURCE[providers/fips]=something.c
    SOURCE[libcrypto]=something.c
    ```
    
    Pros:
    -   I think it would diminish confusion, 'cause it seems like all those static libraries aren't well understood.

    Cons:
    -   More object files from the same source, basically *everything* that we use for the FIPS provider will have duplicated object files for the detault provider.

2.  Doing deeper analysis of symbol references in providers/fips.so and providers/libimplementations.a and see what object files define them...  I can already feel my head explode at the thought.

**Comment by t8m** [comment]
Why can't we use libfips and libnonfips instead of providers/fips vs libcrypto?

It would still have the "more object files from the same source" problem I suppose though.

**Comment by levitte** [comment]
> Why can't we use libfips and libnonfips instead of providers/fips vs libcrypto?

They lose their value as intermediary libraries.  The original intention was that everything that can be compiled the same (i.e. doesn't have any conditions on FIPS_MODULE) would end up in libimplementations.a, and libfips.a / libnonfips.a would contain support functions that would be compiled differently depending on FIPS_MODULE.
However, with libimplementations gone, this is how the providers would linked:

FIPS provider (providers/fips.so): fips provider object files + libfips.a + libcommon.a
Default provider (built into libcrypto): default provider object files + libnonfips.a + libcommon.a
Legacy provider (providers/legacy.so): legacy provider object files + libnonfips.a + libcommon.a

So looking at it now, we might want to keep linnonfips.a around, but libfips.a isn't very useful any more...

**Comment by t8m** [comment]
I'd still keep it to keep the linkage of the providers more uniform.

**Comment by richsalz** [comment]
I would ignore the disk space issue.  What is *way* more important is being able to clearly understand what is in the FIPS provider, and therefore what is in the module boundary.

Repeat object files and make it explicit.  It should be easy for someone (I'll open an issue if necessary) to list what source files are in a provider, or at least the FIPS provider).

Sharing implementation is a premature optimization and therefore the root of this evil :)
