### ISSUE TITLE
Openssl not sending protocol_version alert

### ISSUE THREAD

**Issue by I-mpossible** [openssl/openssl#15153]
## Description:

OpenSSL does not respond with protocol version alert for a client message with invalid version. But I observed that it prints ssl3_get_record:wrong version number in the terminal. It would be nice to respond with a protocol_version alert as well.

## Environment:

Ubuntu 18.04

Openssl 1.1.1j

## How reproducible:

Steps to Reproduce:

```openssl s_server -key /path/to/key.pem -cert /path/to/cert.pem -accept 44330 -tls1_2 -www -no_ticket```

```echo -n -e "\x15\x83\x01\x00\x02\x02\x50" | nc 127.0.0.1 44330```

## Actual results:

Openssl doesn't respond to client. The capture file is attached.

## Expected results:

Send protocol version alert to client.

## Attachments:
[openssl capture.zip](https://github.com/openssl/openssl/files/6425477/openssl.capture.zip)

**Comment by mattcaswell** [comment]
This behaviour is deliberate. Basically if what we've received doesn't even look like TLS then we don't send an alert back:

https://github.com/openssl/openssl/blob/97b59744f2ad91adf606e6f77e355e97413e7b2c/ssl/record/ssl3_record.c#L353-L355

**Comment by I-mpossible** [comment]
Thanks for your reply. It's very helpful.

**Comment by I-mpossible** [comment]
@mattcaswell The message sent by the client is an alert message (type \x15) with invalid version \x83\x01 so it is a TLS message. 

As per RFC8446, the version field is deprecated and should be ignored. Therefore, since the client sends an alert message while the server is expecting client hello, the server should send an `unexpected_message` alert.
>legacy_record_version:  MUST be set to 0x0303 for all records
      generated by a TLS 1.3 implementation other than an initial
      ClientHello (i.e., one not generated after a HelloRetryRequest),
      where it MAY also be 0x0301 for compatibility purposes.  This
      field is deprecated and MUST be ignored for all purposes.

**Comment by t8m** [comment]
Given the major version does not match, the received data can be a pure garbage. I do not think we are going to change the behavior of the SSL server here.

Also please note that you run the server with the `-tls1_2` option so RFC 8446 does not apply.

**Comment by I-mpossible** [comment]
Ok. This was the original discussion about protocol version alert and it's a bit confusing to discuss another issue here. I'll submit a separate issue for TLS1.3.

**Comment by paulidale** [comment]
This has been answered and #15246 duplicates the relevant information for TLS 1.3.  Closing this.
