### ISSUE TITLE
check_update ci fails

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15160]
e.g. https://github.com/openssl/openssl/pull/15159/checks?check_run_id=2509219126

Marked as urgent because it causes tests failure

BTW, if we have some procedure changes, it's worth documenting them...

**Comment by paulidale** [comment]
`make update` should fix these after a rebase.  There are some teething problems.

I think we should either disable this, make it non-fatal or update the checksums automatically.

**Comment by t8m** [comment]
The check_update should be OK as of the current master.
