### ISSUE TITLE
Should cipher_null be added to the fips provider?

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#15172]

**Comment by t-j-h** [comment]
If it is added then additional requirements have to be addressed as that would be considered a bypass mode in FIPS140-2 terms.

**Comment by slontis** [comment]
ok - happy to close this. Just asking in case it was required..

**Comment by paulidale** [comment]
Closing since this is answered.

**Comment by t-j-h** [comment]
My comment wasn't an answer - it was an observation that having a null cipher means we have other things we would have to do. It wasn't a comment on whether or not we should add null cipher support to the fips module. I'm assuming @slontis has a reason for the issue being raised.

**Comment by slontis** [comment]
It was not a requirement, i was just an observation based on looking at the checksums.. And trying to figure out what should and shouldnt be in the module - since it is a lot easier to see what is in there now.
