### ISSUE TITLE
PEM_read_bio_PrivateKey_ex does not return an error code.

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#15170]
Configuring with  no-ec2m results in failures in evp_test

e.g:
>./test/evp_test -config ./test/default-and-legacy.cnf ./test/recipes/30-test_evp_data/evppkey_ecc.txt

Internally it calls PEM_read_bio_PrivateKey_ex()..

If this call fails, it then calls key_supported() (and if this returns 1 then the key is skipped)..

key_supported() tries to test against err, lib and reason.
These values are all zero - which means the test fails.

The trying code may need a bit of a rethink? I can see this type of thing breaking some applications.

**Comment by slontis** [comment]
der2key_decode() calls into
ec_d2i_PKCS8() calls down into
der2key_decode_p8() calls down into
ossl_ec_key_from_pkcs8() which does raise an error when it calls ossl_ec_key_param_from_x509_algor() 
inside EC_GROUP_new_by_curve_name_ex()

but not of this sets the fatal_error flag which will means the error gets thrown away..

Setting this flag seems very brittle..
e.g: ossl_ec_key_from_pkcs8() would probably need to set it in multiple places?
key_from_pkcs8() doesnt handle this flag so this is a bit tricky to handle.

**Comment by t8m** [comment]
Things changed since the PEM_read... functions now do not use store anymore. The error is reported but there is actually another quite useless error hiding the real one.

**Comment by slontis** [comment]
It is good that you have fixed this..
Isnt the underlying problem still lurking there in the store code though?
