### ISSUE TITLE
Test certificates will expire soon

### ISSUE THREAD

**Issue by pmgdeb** [openssl/openssl#15179]
While working on reproducible builds for openSUSE, some tests fail with expired certificates when setting the build date after 2022-06-01. Originally reported by Bernhard Wiedemann in [openSUSE bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1185637). See also:

```
for cert in `find test -name \*pem` ; do openssl x509 -text < $cert | grep After |grep 2022 && echo $cert ; done 2>&1 |grep -A1 2022
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/ISIC_D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/WSNIC_D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/WKIC_D1_Issuer_ICA.pem
            Not After : Jun  1 00:00:00 2022 GMT
test/certs/embeddedSCTs1_issuer.pem
            Not After : Jun  1 00:00:00 2022 GMT
test/certs/embeddedSCTs1.pem
```

The verbose ouput of test `80-test_ssl_new.t` shows:
```
# ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:33
# [2] compared to [0]
# INFO:  @ test/ssl_test.c:34
# ExpectedResult mismatch: expected Success, got ClientFail.
# 139919277639040:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl/record/rec_layer_s3.c:1543:SSL alert number 45
not ok 2 - iteration 2
```

Since the expiring date is a year from now, could you update these certificates?

**Comment by bmwiedemann** [comment]
I made a patch to extend the expiring certs that works on openssl-1.1.1i but fails on openssl-1.1.1l because of certificate-transparency tests  `test/recipes/80-test_ct.t` and `test/recipes/80-test_ssl_new.t`

I noticed that 4d9e8c95544d7a86765e6a46951dbe17b801875a by @vdukhovni touched the same files in master, so maybe that can be ported to the 1.1 series?
2022-06-01 is only 9 months away.

**Comment by vdukhovni** [comment]
The setup.sh script (via mkcert) defaults to generating 100-year certs.  If some certs in the test-suite are not expiring the early 2100's, they were generated outside those scripts, which perhaps presently don't have support for creating certs with SCTs, but that could perhaps be added.

Iny case if new test certs are created, they should rediculously long expiration times, so if that if QCs some day obsolete RSA, ECDSA, ... it'll be well before these certs expire...

**Comment by bmwiedemann** [comment]
Still a problem with openssl-1.1.1m - but not until June, so these crt files need to be renewed:

        Not After : Jun  1 00:00:00 2022 GMT test/certs/embeddedSCTs1_issuer.pem
        Not After : Jun  1 00:00:00 2022 GMT test/certs/embeddedSCTs1.pem

**Comment by t8m** [comment]
Ouch, now it is urgent.

**Comment by Xpktro** [comment]
Just experienced a problem with this while installing 1.1 and 3 and wasted an entire day trying to figure out why the tests were failing. Had move my system time back a few days to get this to work.

**Comment by levitte** [comment]
I can pick this up

**Comment by levitte** [comment]
Meh, there's a slew of files in test/certs that are *not* created with setup.sh 😕

**Comment by t8m** [comment]
> I can pick this up

I'm already working on this.

**Comment by levitte** [comment]
> > I can pick this up
> 
> I'm already working on this.

Ok, I'll let that go then.  Thanks

**Comment by t8m** [comment]
It will be in the next release. You can also get the patch to fix the immediate expiration problem from git - They are the commits 73db5d82489b3ec09ccc772dfcee14fef0e8e908 and b7ce611887cfac633aacc052b2e71a7f195418b8

**Comment by beldmit** [comment]
Reopening because #18467 doesn't apply clean to 1.1.1 branch

**Comment by t8m** [comment]
Fix for 1.1.1 in #18481

**Comment by phodina** [comment]
Is there a patch for version `3.0.3`?

**Comment by bmwiedemann** [comment]
Can this issue be closed now?

**Comment by mattcaswell** [comment]
> Can this issue be closed now?

Yes. Closing.
