### ISSUE TITLE
RSA key generation is two times slower in 3.0

### ISSUE THREAD

**Issue by DirtYiCE** [openssl/openssl#15183]
We have this tiny program to generate an RSA private key:

```c
#include <openssl/evp.h>
#include <openssl/rsa.h>

int main(void)
{
    /* Generate an RSA private key */
    BIGNUM* pub_exp = BN_new();
    BN_set_word(pub_exp, 65537);
    EVP_PKEY_CTX* key_ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, NULL);
    EVP_PKEY_keygen_init(key_ctx);

    EVP_PKEY_CTX_set_rsa_keygen_bits(key_ctx, 4096);
    EVP_PKEY_CTX_set_rsa_keygen_pubexp(key_ctx, pub_exp);

    EVP_PKEY* priv_key = NULL;
    EVP_PKEY_keygen(key_ctx, &priv_key);
    EVP_PKEY_CTX_free(key_ctx);

    EVP_PKEY_free(priv_key);
}
```

With OpenSSL 1.1.1k, it takes about 0.5 seconds to execute it, while with the current master (6ef2f71ac70aff99da277be4a554e3b1fe739050) it takes about 1.2 s on my machine (x64 linux, Core i7-8700K).

**Comment by mattcaswell** [comment]
This is a known consequence of changing the default key generation method for RSA. From the CHANGES file:

````
The default key generation method for the regular 2-prime RSA keys was changed to the FIPS 186-4 B.3.6 method (Generation of Probable Primes with Conditions Based on Auxiliary Probable Primes). This method is slower than the original method.
````

**Comment by slontis** [comment]
There is also this entry in the CHANGES.

 * Deprecated the BN_is_prime_ex() and BN_is_prime_fasttest_ex() functions.
   They are replaced with the BN_check_prime() function that avoids possible
   misuse and always uses at least 64 rounds of the Miller-Rabin
   primality test. At least 64 rounds of the Miller-Rabin test are now also
   used for all prime generation, including RSA key generation.
   This increases key generation time, especially for larger keys.
