### ISSUE TITLE
Update link to migration documentation in release emails

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#15186]
From #14663:

> > > > @t8m: IMO the current intention is to drop this [wiki] page and have all this information in a migration guide document.
> > >
> > > @h-vetinari: Makes sense; then it's just the link in the announcement email that needs to change. ;-)
> >
> > @h-vetinari: @mattcaswell, the alpha16 [announcement](https://mta.openssl.org/pipermail/openssl-project/2021-May/002621.html) still points to the wiki; would you like me to open an issue to change the announcement text for beta1?
>
> @mattcaswell: Please do. Until #14710 is merged though I think the wiki link is better than nothing.

**Comment by slontis** [comment]
Comment from @mattcaswell 

'Can we also change the two release email text templates (dev/release-aux/openssl-announce(-pre)-release.tmp) to remove the wiki link and instead have a link to the migration guide (would fix #15186)?'
