### ISSUE TITLE
The test_gmtime test produces a lot of output.

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#15185]
test-runs/test_gmdiff Is producing a lot of output.
The output of testsuite "HARNESS_VERBOSE=yes" is 49MiB in my configuration. The output of 
```
 90-test_gmdiff.t ...................
 # The results of this test will end up in test-runs/test_gmdiff
 1..1
     # Subtest: ../../test/gmdifftest
     1..1000000
     ok 1 - test_gmtime - iteration 1
     ok 2 - test_gmtime - iteration 2
…
     ok 1000000 - test_gmtime - iteration 1000000
 ../../util/wrap.pl ../../test/gmdifftest => 0
 ok 1 - running gmdifftest
 ok

```
is 45MiB. Is it possible to shink this somehow, please? I have HARNESS_VERBOSE enabled so I see on a build box once something goes wrong without the need to re-run the whole thing. It helps a lot especially if the test does not fail on each run.

Sebastian

**Comment by richsalz** [comment]
You could run them normally, scrape the output for failures and re-run those tests verbosely.

**Comment by sebastianas** [comment]
It runs automatically on a build box without any interaction. And if this a "one time" thing I lose everything.
I could this logic to the part where make test is handled but this would increase the build time in error case. The build on armhf takes ~1h, mip64el ~3h.

Now that I found VERBOSE_FAILURE would it do what I want? Be quiet and print verbose output of the test that failed?

Sebastian

**Comment by richsalz** [comment]
> Now that I found VERBOSE_FAILURE would it do what I want? Be quiet and print verbose output of the test that failed?

Probably.  See test/README.md

**Comment by sebastianas** [comment]
Yes. thank you.
For some reason I was using HARNESS_VERBOSE and a grep for it did not lead to test/README.md.
Thanks again.

Sebastian

**Comment by sebastianas** [comment]
So as it turns out VERBOSE_FAILURE is not optimal - for other reasons.
The build on mipsel failed twice with:
```
04-test_encoder_decoder.t .......... ok
E: Build killed with signal TERM after 150 minutes of inactivity
--------------------------------------------------------------------------------

```
This wasn't a problem with VERBOSE=1 because the output in between subtests is enough to reset the timer. And this test can take some time:
```
(sid_mipsel-dchroot)bigeasy@eller:~/openssl-3.0.0~~alpha16/build_shared$ make test TESTS=test_encoder_decoder_legacy
make depend && make _tests
make[1]: Entering directory '/home/bigeasy/openssl-3.0.0~~alpha16/build_shared'
make[1]: Leaving directory '/home/bigeasy/openssl-3.0.0~~alpha16/build_shared'
make[1]: Entering directory '/home/bigeasy/openssl-3.0.0~~alpha16/build_shared'
( SRCTOP=.. \
  BLDTOP=. \
  PERL="/usr/bin/perl" \
  FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
  EXE_EXT= \
  /usr/bin/perl ../test/run_tests.pl test_encoder_decoder_legacy )
04-test_encoder_decoder_legacy.t .. ok
All tests successful.
Files=1, Tests=1, 5219 wallclock secs ( 0.08 usr  0.00 sys + 5216.96 cusr  0.42 csys = 5217.46 CPU)
Result: PASS
make[1]: Leaving directory '/home/bigeasy/openssl-3.0.0~~alpha16/build_shared'

```
So here the test took ~87 Minutes without generating any output. On the build box the 150min were exceeded.


Would it be okay if I reduce the visible output of those loops to say 10 or so?

Sebastian

**Comment by paulidale** [comment]
Having `TESTS=-test_gmdiff` on the `make test` line will suppress this test.

Still 10⁶ iterations seems large.  I like exhaustive testing but this doesn't seem useful every build.
