### ISSUE TITLE
Android NDK r22b not working with 1.1.1k

### ISSUE THREAD

**Issue by LucasAschenbach** [openssl/openssl#15200]
As explained in issue #13685, the android NDK r22b no longer contains an `AndroidVersion.txt` file and a `platform` directory. There has been a pull request #13694 fixing this compatibility issue, however, the changes cannot be found in any of the stable releases (1.1.1*) which means there is still the error message:

```
++ Build openssl armeabi-v7a ++
Configuring OpenSSL version 1.1.1k (0x101010bfL) for android-arm
Using os-specific seed configuration
$ANDROID_NDK_HOME=/android-ndk-r22b is invalid at (eval 10) line 37.
```

**Comment by mattcaswell** [comment]
The PR #13694 that you refer to has been merged to the 1.1.1 branch and therefore will be included the next time we do a 1.1.1 release.

**Comment by LucasAschenbach** [comment]
I see, thank you!

**Comment by brodybits** [comment]
Hi is there anything we can do to help get a new 1.1.1 release with this update?

**Comment by t8m** [comment]
There is a release imminent. https://mta.openssl.org/pipermail/openssl-announce/2021-August/000205.html
