### ISSUE TITLE
Update fips checksums only before release and have a CI job to flag PRs that touch fips sources

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#15223]
The current way of having the checksums checked by the check_update CI job is bad as this creates constant merge conflicts.

OTC decided that the checksums should be updated just before the releases but PRs that actually touch the FIPS module sources need to be flagged somehow.

The check_update job should not fail if checksums are not up-to-date.

There should be a new job that would not make the CI fail but it would add a label or it would somehow else flag that a PR is changing the checksums. This job would have to update checksums on the fresh master, then merge the PR, then update the checksums and see if the final checksum changed.

**Comment by h-vetinari** [comment]
This was reverted without much description in https://github.com/openssl/openssl/commit/e2daf6f14045587614681bf6579480be63de6da0 - is there a way to work around the vulnerability and still have the same functionality? Or is it a fundamental problem with github actions on PRs somehow?

**Comment by mattcaswell** [comment]
We're hoping to have an updated script soon. @t8m is looking at it.

**Comment by t8m** [comment]
PR coming soon

**Comment by t8m** [comment]
See #15309
