### ISSUE TITLE
Demo code or api to call for RSA key generation FIPS186-4 openssl3.0.0-alpha 16

### ISSUE THREAD

**Issue by sikkamukul** [openssl/openssl#15233]
Hi Openssl Team,
I am using openssl3.0.0-alpha 16 version
I was not able to find the correct set of api or any demo code for RSA key generation 
example for test vector - 
    ```
      "algorithm": "RSA",
      "mode": "keyGen",
      "revision": "FIPS186-4",
      "isSample": true,
      "testGroups": [
         {
            "tgId": 1,
            "infoGeneratedByServer": false,
            "modulo": 2048,
            "testType": "KAT",
            "keyFormat": "standard",
            "primeTest": "tblC2",
            "randPQ": "B.3.3",
            "pubExp": "random",
            "tests": [
               {
                  "tcId": 1,
                  "e": "...",
                  "p": "...",
                  "q": ""
               }
            ]
      }
]
    ```

**Comment by mattcaswell** [comment]
See the examples section here:

https://www.openssl.org/docs/manmaster/man7/EVP_PKEY-RSA.html

Note the one line example `pkey = EVP_RSA_gen(4096);` can't be done in alpha16 but will be available in alpha17.

**Comment by slontis** [comment]
See also test/acvp_test.c

**Comment by slontis** [comment]
Note that OpenSSL uses FIPS186-4 B.3.6 "Generation of Probable Primes with Conditions Based on Auxiliary Probable Primes".

**Comment by sikkamukul** [comment]
Will OpenSSL is later on going to implement FIPS186-4 B.3.3?

**Comment by slontis** [comment]
Not currently. It is not required that we have every type of key generation.

**Comment by paulidale** [comment]
I don't expect that we (the OpenSSL developers) will ever implement B.3.3.  If somebody were to submit an implementation, it would be considered of course.

**Comment by slontis** [comment]
That could affect fips validation also.. You would also need a property or param type to select the different rsa keygen types.
That would also then probably affect the validation.
