### ISSUE TITLE
Openssl 1.1.1 build failed at bn_conf.h.in (potentially a documentation issue)

### ISSUE THREAD

**Issue by kleshchevand** [openssl/openssl#15234]
Issue: nmake fails with "NMAKE : fatal error U1077: '' : return code '0x1'"

**Logs:**

```
+ nmake

Microsoft (R) Program Maintenance Utility Version 14.16.27045.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        /usr/bin/perl "-I." -Mconfigdata "util/dofile.pl"  "-oMakefile" include/crypto/bn_conf.h.in > includ
e/crypto/bn_conf.h
Системе не удается найти указанный путь.
NMAKE : fatal error U1077: '' : return code '0x1'
Stop.
```
"Системе не удается найти указанный путь." translates as "System can not find specified path".

Attached "perl configdata.pm --dump output" as an "configdata.txt".
[configdata.txt](https://github.com/openssl/openssl/files/6461598/configdata.txt)
[Makefile.txt](https://github.com/openssl/openssl/files/6461666/Makefile.txt)

**Commands:**
```
targetname=Cygwin-x86
perl Configure "$targetname" no-asm no-idea zlib threads -DNO_WINDOWS_BRAINDEATH \
                --with-zlib-include="$(cygpath -w "$stage/packages/include/zlib")" \
                --with-zlib-lib="$(cygpath -w "$stage/packages/lib/release/zlib.lib")"

nmake
```
Configuration completed without issues. But nmake fails.

**Environment:**

Windows 10 Pro 64bit
MS Visual Studio 2017 Community
Cygwin 64bit
Perl v5.32.1 (from cygwin)
Text::Template 1.59-2
nasm-2.15.05

**Other:**
Tried using make instead of nmake, it did get somewhat further, but it complains about gcc, and neither make nor gcc were marked as requirements in NOTES.WIN's section for cygwin
This might be not an issue with openssl, but with documentation and missing requirements for cygwin builds in NOTES.WIN.

Configured and built "darwin64-x86_64-cc" without issues under mac, from same repo.
util/dofile.pl,  include/crypto/bn_conf.h.in and even include/crypto/bn_conf.h are present. But bn_conf.h is empty and only appeared after running nmake)
Same error without Text::Template from cygwin
Tried configuring with no arguments but $targetname, same result. 
Also tried via ./configure and with other Cygwin configuration variants - no changes.
VC- variants fail to configure, they are complaining about '/'. Since I'm building under cygwin, with cygwin's perl I'm using cygwin-x86 and cygwin-x86_64
No related paths contain unicode.
Tried manually executing
perl "-I." -Mconfigdata "util/dofile.pl"  "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
But it complains about uninitialized Text::Template::ERROR

P.S. I was trying to upgrade our openssl from 1.0.2 to 1.1.1, but got stumped by this issue. It is not clear from log, what nmake fails to access. Nor where did the error happen.
I probably can get around the issue by installing curl for windows and running VC-* configuration+nmake from a bat file, but I think either build documentation or nmake build should be fixed.

**Comment by t8m** [comment]
Is there an  `/usr/bin/perl` ? Would PERL=/path/to/perl help?

**Comment by kleshchevand** [comment]
It is present
/usr/bin/perl --version
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-cygwin-threads-multi

I now suspect that this is a documentation issue and not an SSL's issue. Likely NOTES.WIN needs to specify that cygwin builds require 'make' and 'gcc' packages, not nmake.

I managed to do an OpenSSL build with VC-* configuration without issues out of cygwin, so will try to integrate that into our sh build script. Not sure what to do with this 'issue'. Technically I no longer need it, so it can be closed, but seems like openssl needs some improvements at least documentation wise.

**Comment by t8m** [comment]
> Technically I no longer need it, so it can be closed, but seems like openssl needs some improvements at least documentation wise for cygwin builds.

That's always true but best way how to get such documentation issues fixed are by submitting PRs fixing them.

Closing then.
