### ISSUE TITLE
openssl with curl make random unix time

### ISSUE THREAD

**Issue by ahrzeroday** [openssl/openssl#15235]
hello 

i have a problem with openssl when i make request with curl(compiled with openssl) in client Hello in random i give random unix time like this :
![Screenshot 2021-05-12 011012](https://user-images.githubusercontent.com/80595646/117881709-d1e66600-b2be-11eb-9f4b-6dcda977238c.jpg)

and when i use this line code :

`SSL_CTX_set_options(ctx, SSL_MODE_SEND_CLIENTHELLO_TIME);`

It makes no difference

please help me , how can i set my current client time ?

**Comment by ahrzeroday** [comment]
no one can't help me?

**Comment by FdaSilvaYY** [comment]
Probably a curl question.
A good bug or question will provide a more detailed context  : OS, distro, version of related libs, reproduction steps ...
So you can not expected a good answer without a good background.

**Comment by mattcaswell** [comment]
> and when i use this line code :
>
> `SSL_CTX_set_options(ctx, SSL_MODE_SEND_CLIENTHELLO_TIME);`
> 
> It makes no difference

`SSL_MODE_SEND_CLIENTHELLO_TIME` is a *mode* not an *option*. Therefore you need to use `SSL_CTX_set_mode` instead of `SSL_CTX_set_options`.

> how can i set my current client time ?

But why would you want to? This mode was introduced a long time ago to deal with (according to the comment in the header file) "...compatibility with hypothetical implementations that require it...". I'm not actually aware that any such implementations really exist.

**Comment by ahrzeroday** [comment]
when i use curl with winssl or curl with mbedtls it's show me real time but when use curl with openssl it's show me random time!!

no way to show real time with openssl?(if need some change in source code can you tell me to change it for my special work?)
thanks

**Comment by mattcaswell** [comment]
> when i use curl with winssl or curl with mbedtls it's show me real time but when use curl with openssl it's show me random time!!

And why does this matter? This is just an implementation difference between different libraries. There are many differences between implementations but they should not impact interoperability.

> no way to show real time with openssl?

Yes you can. As I tried to explain in my previous post you can do this using `SSL_MODE_SEND_CLIENTHELLO_TIME` and `SSL_CTX_set_mode` (but NOT `SSL_CTX_set_options` as you were attempting). I'm just questioning why you would want to do this and why it matters.

**Comment by ahrzeroday** [comment]
thanks it's work

my server need real client time for this i need this mode thanks
