### ISSUE TITLE
Poorly named getter functions

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#15236]
There are a number of new functions that do not include a _get_: `XXX_provider()`, `XXX_number()`, `XXX_name()`, `XXX_properties()`, `XXX_description()` and likely more.  These are in EVP and ENCODER/DECODER namespaces.  The project is moving towards having _get_ in the name of getter functions.

Note: there is no corresponding setting for any of these, only the getters.

**Comment by t8m** [comment]
I am not sure about this - there are preexisting EVP_MD_name(), EVP_CIPHER_name(), EVP_PKEY_size(), and so on. What shall we do with these? Make them just aliases to the _get_xxxx() functions? Also for the getters returning pointers should they be named XXX_get0_yyy() to indicate that the ownership of the returned pointer to data stays with the EVP object?

**Comment by slontis** [comment]
I think we should be leaving the ones added before 3.0 alone for now.

**Comment by t8m** [comment]
That would be ugly IMO.

**Comment by steveloughran** [comment]
aah, you appear to have broken bits of hadoop. please, please, please can someone with time look at the proposed fix and let us know if there is anything *wrong* with it -or any other forthcoming change we should anticipate and address now. thanks.
https://github.com/apache/hadoop/pull/5256
