### ISSUE TITLE
Openssl not sending unexpected_message alert

### ISSUE THREAD

**Issue by I-mpossible** [openssl/openssl#15246]
## Description:

The client sends an alert message as the first message to OpenSSL server. The server doesn't respond with alert. But I observed that it prints ssl3_get_record:wrong version number in the terminal. 

The client message is an alert (type \x15) and the version is \x83\x01. The server is configured to use TLS1.3. As per RFC8446, the version should be ignored. Thus, the message should be parsed as a well-formed alert message. Since the server is expecting a client hello, `unexpected_message` should be sent to client.

>legacy_record_version: MUST be set to 0x0303 for all records
generated by a TLS 1.3 implementation other than an initial
ClientHello (i.e., one not generated after a HelloRetryRequest),
where it MAY also be 0x0301 for compatibility purposes. This
field is deprecated and MUST be ignored for all purposes.

## Environment:

Ubuntu 18.04

Openssl 1.1.1j

## How reproducible:

Steps to Reproduce:

```openssl s_server -key /path/to/key.pem -cert /path/to/cert.pem -accept 44330 -tls1_3 -www -no_ticket```

```echo -n -e "\x15\x83\x01\x00\x02\x02\x50" | nc 127.0.0.1 44330```

## Actual results:

Openssl doesn't respond to client.

## Expected results:

Send unexpected_message alert to client.

**Comment by kaduk** [comment]
This seems to be fundamentally the same behavior that Matt clarified in https://github.com/openssl/openssl/issues/15153#issuecomment-832491387 -- "if what we've received doesn't even look like TLS then we don't send an alert back"

**Comment by I-mpossible** [comment]
The client message has two errors (1) type being \x15 so it's an alert instead of client hello (2) the version is invalid.

I agree that in TLS1.2 the major version doesn't match so it doesn't look like TLS. So the version check code mentioned by Matt makes sense. 

https://github.com/openssl/openssl/blob/97b59744f2ad91adf606e6f77e355e97413e7b2c/ssl/record/ssl3_record.c#L353-L355

However, in TLS1.3, the legacy_record_version is required as "MUST be ignored for all purposes". Therefore, any record version should be accepted. And the server should parse the client message as a well-formed alert. Since the server is expecting a client hello, an `unexpected_message` should be sent
>legacy_record_version: MUST be set to 0x0303 for all records
generated by a TLS 1.3 implementation other than an initial
ClientHello (i.e., one not generated after a HelloRetryRequest),
where it MAY also be 0x0301 for compatibility purposes. This
field is deprecated and MUST be ignored for all purposes.

**Comment by kaduk** [comment]
We don't know that we need to apply RFC 8446 if we don't know that we should be attempting TLS 1.3.  (While s_server is started with `-tls1_3`, that says nothing about what the client is trying to do.  At this stage in processing we have not even determined that the client is trying to speak TLS, let alone what version.

We could also cite:

>   Upon receiving an error alert, the TLS implementation
   SHOULD indicate an error to the application and MUST NOT allow any
   further data to be sent or received on the connection.

that we don't respond to a (non-closure) alert with anything at all, even another alert.
(This is also a fairly natural defense against getting into an "alert loop" between two implementations rejecting eath others' messages.)

But really, though, this is just responsible software design for a network-facing service.  If the input you get is complete nonsense, ignore it, to avoid being tricked into doing something harmful.

**Comment by I-mpossible** [comment]
I don't understand why it may get into an "alert loop". When implementation receives fatal alert, it MUST close the connection.
>Upon transmission or
   receipt of a fatal alert message, both parties MUST immediately close
   the connection.

If I change the record_version of client message from `\x83\x01` to `\x03\x01`, the OpenSSL server responds with `unexpected_message` alert. This indicates that, once the record version check is passed, the current OpenSSL implementation does think this alert sent by client is an unexpected message and sends back `unexpected_message` alert. So the current implementation is not ignoring this message.
`echo -n -e "\x15\x83\x01\x00\x02\x02\x50" | nc 127.0.0.1 44330`

So it seems that OpenSSL first checks the version field then check the type. Type checking makes sense but version checking does not conform to RFC 8446 since the legacy_record_version field is required as "MUST be ignored for all purposes".

**Comment by t8m** [comment]
Would it make sense to change the code to not react to anything with an alert unless it is a client hello message type?

That would make it to conform to _legacy record version MUST be ignored for all purposes_.

**Comment by I-mpossible** [comment]
I think it should be changed to (1) not check the version field as required by RFC8446 (2) check the type field and respond with `unexpected_message` alert if the type sent by the client is not client hello message type.

I don't understand why you want to change it to "_not react to anything with an alert unless it is a client hello message type_". First of all, the `unexpected_message` alert makes total sense in this case i.e. The server is expecting client hello but got a message that is not client hello (as indicated by the type field). Secondly, if it's because of the reasons given by kaduk, I've presented my understanding about "alert loop" in the comments above. I also don't agree with "_If the input you get is complete nonsense, ignore it, to avoid being tricked into doing something harmful._". The alert protocol in TLS is exactly designed to indicate errors.

And as I mentioned, the client message has two errors (1) unexpected type (this corresponds to unexpected_message alert) (2) wrong version (this is required to be ignored by RFC). The current implementation checks version field first. So if I modify the version to \x03\x01 to bypass the version check, the current OpenSSL implementation indeed responds with `unexpected_message` alert.

**Comment by richsalz** [comment]
Yes, the TLS protocol is "exactly designed to indicate errors."  The messages being sent from the client are not valid TLS messages, so the RFC does not apply.

**Comment by I-mpossible** [comment]
In the current implementation, the server parses the record version field and decide that it's not valid TLS message. So nothing is sent back. I totally agree with this logic. And this is exactly what the server should do in terms of RFC5246 (when it was the latest TLS RFC).

https://github.com/openssl/openssl/blob/97b59744f2ad91adf606e6f77e355e97413e7b2c/ssl/record/ssl3_record.c#L353-L355

However, as required by RFC8446, the server should ignore the version field. Then how does it know whether the message sent by client is valid TLS message or not? I think it should parse the type field. Then it finds that this is an invalid type and it's expecting a client hello. So it sends `unexpected_message` alert.

The reason to conform to RFC8446 here is, as pointed out by kaduk, at this point the server haven't decided what version to use i.e. which RFC to apply. Thus I think it should conform to the latest RFC and accept any version field for maximum compatibility.

**Comment by richsalz** [comment]
> However, in TLS1.3, the legacy_record_version is required as "MUST be ignored for all purposes". Therefore, any record version should be accepted

This is incomplete. You are ignoring the first sentence which says it "MUST be set to 0x303..."

So the client is not conforming, and the server can do what it wants.

**Comment by kaduk** [comment]
>  Ignoring any invalid message doesn't seem to be a good practice

The internet ecosystem as a whole has quite a bit of painfully earned experience that there are many cases where ignoring invalid messages is a good practice.  Ignoring invalid messages is not always the right thing to do, and for certain classes of invalid messages, responding with an error **is** the right thing to do.  But not always.

**Comment by I-mpossible** [comment]
>You are ignoring the first sentence which says it "MUST be set to 0x303..."

That's for TLS 1.3 client implementation. "for all records generated by a **TLS 1.3** implementation other than an initial ClientHello". At this point of processing, the server hasn't determined which version to use.

>The internet ecosystem as a whole has quite a bit of painfully earned experience that there are many cases where ignoring invalid messages is a good practice.

Exactly, I totally agree that ignoring is important in lots of cases. Otherwise the server can be easily tricked by attackers. Sending correct alert is also important as TLS design provides many types of alert and detailed descriptions for error indications.

---

You can see that the current implementation conforms to RFC5246. RFC5246 states that "MUST accept any value {03,XX} as the record layer version number for ClientHello." So the code checks whether the major version is 03.
>   Earlier versions of the TLS specification were not fully clear on
   what the record layer version number (TLSPlaintext.version) should
   contain when sending ClientHello (i.e., before it is known which
   version of the protocol will be employed).  Thus, TLS servers
   compliant with this specification MUST accept any value {03,XX} as
   the record layer version number for ClientHello.

https://github.com/openssl/openssl/blob/97b59744f2ad91adf606e6f77e355e97413e7b2c/ssl/record/ssl3_record.c#L336

As RFC8446 specifies new requirements, i.e. the version field should be ignored, the server should accept any `legacy_record_version`.

In terms of what alert should be sent (or just completely ignore the unexpected type) in this case, I've experimented with message that has valid version (\x03\x01) but invalid type (\x15). And the server does respond with `unexpected_message` alert. So I think in the current design it's not ignoring this class of invalid message. And I think this behavior is correct because the server is expecting a client hello but got an unexpected type.

RFC8446 on `unexpected_message` alert
>unexpected_message:  An inappropriate message (e.g., the wrong
      handshake message, premature Application Data, etc.) was received.
      This alert should never be observed in communication between
      proper implementations.

**Comment by richsalz** [comment]
> As RFC8446 specifies new requirements,
> That's for TLS 1.3 client implementation.

You can't require 8446 in one paragraph and then reject it in another :)

The client is not compliant with either TLS 1.2 or TLS 1.3.  The server can do what it wants.  I don't think there's any more to say.

**Comment by I-mpossible** [comment]
>The client is not compliant with either TLS 1.2 or TLS 1.3.
Yes, as human we know that. But server needs to check this at code level.

>The server can do what it wants.
The server needs to first check whether client is conforming (sending valid TLS message). If yes, it needs to start handshake. If not, it can send alerts, or just ignore client message (if it's too malformed). My point is, server can't do this check by looking at the `legacy_record_version` because the field is required as "MUST be ignored for all purposes".

**Comment by kaduk** [comment]
The thread starting at https://mailarchive.ietf.org/arch/msg/tls/8LgYNPHuJPAooVEssJeqfqig1SQ/ has some additional discussion on this topic.  My high-level summary is that some people want the server to enforce the MUST+MAY, and others don't care, but that inferring semantic meaning to the actual value is what is prohibited.  "This is not TLS" does not qualify as "semantic meaning" to me.
(Do note that Rich is a designated expert for the TLS IANA registries, and I'm currently the Area Director responsible for the TLS working group, which among other things confers upon me the ability/responsibility to process errata reports against the TLS specification.)

**Comment by paulidale** [comment]
@kaduk, will this be reported?  @mattcaswell noted in the previous issue that this was intentional behaviour on the part of OpenSSL.  My opinion is that we're in undefined territory.

**Comment by kaduk** [comment]
@paulidale I'm not sure I understand the question.  I am happy with what OpenSSL is currently (intentionally) doing, and I don't feel strongly that a clarification to the specification is needed in order to allow us to do so.
That said, there is an internet-draft open to do a revision of RFC 8446, and if someone felt strongly they could open a PR (or issue, I suppose, but PR is better) against https://github.com/tlswg/tls13-spec and send mail to tls@ietf.org about it.  But, as I said before, I don't plan to do either myself.

**Comment by paulidale** [comment]
@kaduk, that answers my question.  You're not formally actioning this.  I'm closing this discussion since we're not going to change the current behaviour unless the RFC is modified.

**Comment by I-mpossible** [comment]
@kaduk Thanks for the mail thread.
>legacy_record_version: **MUST be set to 0x0303** for all records generated by a TLS 1.3 implementation other than an initial
ClientHello (i.e., one not generated after a HelloRetryRequest),

>where it **MAY also be 0x0301** for compatibility purposes. 

> This field is deprecated and **MUST be ignored for all purposes**.

Can I just check that I've understood you correctly? The requirement on `legacy_record_version` can be split to these three parts above. Do you mean by combining the first two requirements: "MUST be set to 0x0303" and "MAY also be 0x0301", it's ok for server to assume the first byte shall always be "03" and thus perform check on it?

I feel like such interpretation somewhat contradicts the third requirement: "MUST be ignored".

Here is a different interpretation from GnuTLS https://gitlab.com/gnutls/gnutls/-/issues/1230

**Comment by kaduk** [comment]
> Can I just check that I've understood you correctly? The requirement on legacy_record_version can be split to these three parts above. Do you mean by combining the first two requirements: "MUST be set to 0x0303" and "MAY also be 0x0301", it's ok for server to assume the first byte shall always be "03" and thus perform check on it?

Generally if no one is allowed to check compliance, we don't write MUST and MAY in the specification.  Some people want to check and there was not WG consensus to forbid such checking.

> I feel like such interpretation somewhat contradicts the third requirement: "MUST be ignored".

You can go back to the mail thread to confirm, but the sense here is: the contents of this field have no semantic value in the TLS protocol.  Specifically, in previous versions of TLS it was used to indicate a minimum supported version, but this specification explicitly disclaims such usage.

However, if you are trying to decide whether or not you are receiving a TLS packet, you need not be bound by RFC 8446.

**Comment by I-mpossible** [comment]
I see. Thanks.
