### ISSUE TITLE
Reduce/remove the "OpenSSL has been successfully configured" banner

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15247]
If you enable FIPS, openssl gets configured three times.  That banner, which was planned for removal anyway, is big and disconcerting.  It should really just be one or two lines of text, ideally with some context as to why it's being configured.

**Comment by levitte** [comment]
I'd suggest adding the configuration option `--quieter` and use that when configuring for the checksum stuff

**Comment by richsalz** [comment]
Where is the checksum stuff configured?  In #15248, I added no-banner/enable-banner support.

**Comment by levitte** [comment]
Here:

https://github.com/openssl/openssl/blob/8f965908a53b4f0c5a735739e8a273a3a33a976e/Configurations/unix-Makefile.tmpl#L1157-L1160
