### ISSUE TITLE
OpenSSL_1_0_2h build fails with no-ecdh option

### ISSUE THREAD

**Issue by frezbo** [openssl/openssl#1525]
The build fails when no-ecdh option is specified.
_t1_lib.c: In function 'tls1_get_curvelist':
t1_lib.c:500:42: error: 'struct cert_st' has no member named 'ecdh_tmp_auto'_

Here's my config:

```
./config --prefix=/usr no-ssl3 no-rc4 no-camellia no-seed no-comp no-srp no-psk no-idea no-des  no-dh
```

Providing _no-descbcm_ also fails but issue solved by applying patch: https://github.com/openssl/openssl/pull/872/files

**Comment by levitte** [comment]
This is resolved.
