### ISSUE TITLE
const values e.g. const SSL* ssl

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1526]
We experienced a change between beta6 and release version 1.1.0 concerning const values.
At some stage you return a const SSL\* which is fine, but at other places a non const parameter is required. That generates the need of unwanted casts.

parameter 1: **const SSL\* s**
parameter 2: **SSL_is_server((SSL*)s)**

```
int security_callback(**const SSL* s,** const SSL_CTX* ctx, int op,
                                         int bits, int nid, void *other,
                                         void *ex) {
    int rc = 1;

    security_cb_ex *sdb = (security_cb_ex *)ex;

    switch (op) {
    case SSL_SECOP_TMP_DH: {
        DH* dh = NULL;
        if (**SSL_is_server((SSL*)s)** == 1) {
....
```

**Comment by richsalz** [comment]
That’s a bug, SSL_is_server() should take a const.  Please list other places where you had to add casts and we’ll look at fixing them.

**Comment by wolftobias** [comment]
ASN1_TIME* t_not_before = (ASN1_TIME*)X509_get0_notBefore(x509);
	ASN1_GENERALIZEDTIME* gt_not_before = ASN1_TIME_to_generalizedtime(t_not_before, NULL);

**Comment by wolftobias** [comment]
ASN1_TIME* t_not_after = (ASN1_TIME*)X509_get0_notAfter(x509);
	ASN1_GENERALIZEDTIME* gt_not_after = ASN1_TIME_to_generalizedtime(t_not_after, NULL);

**Comment by richsalz** [comment]
In those examples, t_not_before and t_not_after should be const.

**Comment by levitte** [comment]
These were never fixed.  We should have a second look.

**Comment by richsalz** [comment]
Sadly, this is clearly an API change so 1.2 (which means 2018).

**Comment by levitte** [comment]
As before, I disagree.

The [FAQ on version numbering](https://www.openssl.org/docs/faq.html#MISC8) as well as our [release strategy](https://www.openssl.org/policies/releasestrat.html) talk about backward compatibility (both API and ABI).  As far as I know, constifying function input parameters where appropriate does *not* constitute a backward incompatibility, it only explicitely asserts that we're not going to change the contents of the passed parameter.

This could at the very least be done in 1.1.1.  (I'd argue that it's safe in 1.1.0 as well, but that's a fight I'm not as willing to take)

**Comment by richsalz** [comment]
I agree with you about parameters becoming const (although @dot-asm disagrees; we'll have to discuss and vote).  But this case is *return values*

**Comment by levitte** [comment]
I think you've misunderstood.  The way I read the complaint, it's that `SSL_is_server` takes a non-const `SSL *`, and that `ASN1_TIME_to_generalizedtime` takes a non-const `ASN1_TIME`.  `SSL_is_server` clearly doesn't change the input, and I just checked, constifying the input `ASN1_TIME` parameter for `ASN1_TIME_to_generalizedtime` is without issues as well.

**Comment by richsalz** [comment]
you're right.  oops.

**Comment by richsalz** [comment]
ping @levitte @mattcaswell

**Comment by mattcaswell** [comment]
This is #3360 which I opened earlier today.
