### ISSUE TITLE
Build error: conflicting types for 'OSSL_HTTP_get'

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#15268]
`max_resp_len` parameter is defined as `size_t`, but implemented as `unsigned long`. This causes a build error on platforms where these types have different length.

https://github.com/openssl/openssl/blob/3ba3e350fd15c133a172095f67e6e0c99ab9b410/crypto/http/http_client.c#L1018-L1023

https://github.com/openssl/openssl/blob/3ba3e350fd15c133a172095f67e6e0c99ab9b410/include/openssl/http.h#L78-L83

**Comment by gotthardp** [comment]
Note also that `maxline` is declared as `buf_size`, which may be confusing. But that one is harmless.

**Comment by gotthardp** [comment]
Appears to be fixed in #15251. Sorry, I missed that one when writing this.

**Comment by paulidale** [comment]
Closing this since the fix is in the pipeline already.
