### ISSUE TITLE
OPENSSL_CONF isn't sticking for threadstest.c

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#15261]
The fix in #15256 changes from relying on `OPENSSL_CONF` to calling `OSSL_LIB_CTX_load_config()` on the new library context directly.

What is unknown is why `OPENSSL_CONF` wasn't happening properly.  The environment variable is passed with the correct value but `OSSL_LIB_CTX_new()` followed by `OSSL_PROVIDER_load()` didn't read the config specified.

**Comment by mattcaswell** [comment]
> What is unknown is why OPENSSL_CONF wasn't happening properly. The environment variable is passed with the correct value but OSSL_LIB_CTX_new() followed by OSSL_PROVIDER_load() didn't read the config specified.

Ah! Actually this is correct behaviour. Only the default libctx is ever auto-inited. If you're using a non-default libctx then you won't get the config auto load.

**Comment by paulidale** [comment]
Good news.

**Comment by paulidale** [comment]
Would not auto-initing the context impact #14527 I wonder?

**Comment by mattcaswell** [comment]
> Would not auto-initing the context impact #14527 I wonder?

I don't see why it would. Since auto-init only ever occurs in the default lib ctx, it only ever occurs application side. It has never at any point occurred provider side.

**Comment by t8m** [comment]
The problem in #14527 happens only when the default context auto-init happens in a child thread and the FIPS provider is loaded during that auto-init. If I remember correctly it had nothing to do with the config file except for the thing that you actually need a valid default config file including the fipsmodule.cnf to be able to load the FIPS provider at all.
