### ISSUE TITLE
definition of BIO_CB_return is wrong

### ISSUE THREAD

**Issue by chrisemsen** [openssl/openssl#15280]
The #define for `BIO_CB_return` is wrong -- it has 1 too many closing brackets.

`#define BIO_CB_return(a) ((a)|BIO_CB_RETURN))`

**Comment by mattcaswell** [comment]
I'm intrigued what version of OpenSSL you are running. This appears to refer to the bug that was fixed here 6 years ago in 1.0.2d:

https://github.com/openssl/openssl/commit/3bf9adaa2ba3456b90c01ac719edc566f8bb3037

No current version of OpenSSL seems to have this problem:

https://github.com/openssl/openssl/blob/f04bb0bce490de847ed0482b8ec9eabedd173852/include/openssl/bio.h.in#L270

**Comment by chrisemsen** [comment]
I used Visual Studios NuGet package manager to pull an OpenSSL package, looks like the one (for there are MANY) I chose was complied against an ancient version of OpenSSL and has not been updated.
