### ISSUE TITLE
Broken links in crypto/ec/ec_mult.c comments

### ISSUE THREAD

**Issue by cygnusv** [openssl/openssl#1528]
The comments state this code implements the wNAF-based interleaving multi-exponentiation method described in http://www.informatik.tu-darmstadt.de/TI/Mitarbeiter/moeller.html#multiexp, but this link is broken. Possibly it refers to:

Möller, B. (2001, August). Algorithms for multi-exponentiation. In International Workshop on Selected Areas in Cryptography (pp. 165-180). Springer Berlin Heidelberg.

http://link.springer.com/chapter/10.1007%2F3-540-45537-X_13
http://www.bmoeller.de/pdf/TI-01-08.multiexp.pdf

**Comment by richsalz** [comment]
ping @levitte :)

**Comment by richsalz** [comment]
comment updated on all release branches.
