### ISSUE TITLE
Support setting up ENGINE operations on specific SSL/SSL_CTX objects

### ISSUE THREAD

**Issue by TheDechev** [openssl/openssl#15296]
Using OpenSSL 1.1.1i in my organization and we're trying to migrate some hardware acceleration package that has its own ENGINE implementation.

Unfortunately, with the existing documentation, it seems like there's no way to set the ENGINE on specific SSL/SSL_CTX object.
Instead, we're forced to use the following ENGINE API which sets the operations for the **entire process**:

```
ENGINE_set_default_RSA
ENGINE_set_default_DSA
ENGINE_set_default_ciphers
ENGINE_set_default_EC
```

This is quite the limitation as it requires adjusting the entire OpenSSL usage due to the ENGINE dependency in one particular area.

Having the option to set the ENGINE for specific SSL/SSL_CTX objects would allow us to migrate external packages way more easily.

Is that something that has been brought up before or that's currently in development?

Thanks in advance!

**Comment by paulidale** [comment]
I don't think this will ever happen.  We're moving away from the engine API to providers in 3.0 and 1.1.1 is bug fix only.

**Comment by TheDechev** [comment]
Thanks @paulidale.
Will those "providers" have some similar mechanism of setting it per SSL/SSL_CTX?

**Comment by gotthardp** [comment]
For providers there is `SSL_CTX_new_ex`, which allows you to specify (via `libctx` and `propq`) quite precisely what implementations shall be used. https://www.openssl.org/docs/manmaster/man3/SSL_CTX_new_ex.html
For more details on `libctx` and `propq` see e.g. "Algorithm Fetching" in https://www.openssl.org/docs/manmaster/man7/crypto.html.

**Comment by paulidale** [comment]
Answered, closing.
