### ISSUE TITLE
AppVeyor builds failing with missing sleep symbol

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#15304]
The failure can be seen here for example:
https://ci.appveyor.com/project/openssl/openssl/builds/39187157/job/8e9luf4me92f80h6

openssl-bin-cmp.obj : error LNK2019: unresolved external symbol sleep referenced in function cmp_main

**Comment by t8m** [comment]
@DDvO might be interested?

**Comment by DDvO** [comment]
I was about to copy the awkward definition of `ossl_sleep()` from `include/internal/cryptlib.h` over to `apps/include/apps.h,`
but then I though: how about instead exporting it as, e.g., `OSSL_sleep()`?
This way also the apps, tests, and external users can profit from it.

**Comment by paulidale** [comment]
I don't think we should make it public.

It saves writing the documentation and test cases.

`sleep()` is a very abused call, the number of times I've seen it properly used is dwarfed by the number of times it was used as a cop out.

**Comment by richsalz** [comment]
the CMP case seems like one of those mis-uses. Why not use select/poll/waitformutipleevents?
