### ISSUE TITLE
Openssl-3.0 : Segmentation fault while calling "EVP_RAND_instantiate" for CTR-DRBG

### ISSUE THREAD

**Issue by banvikas** [openssl/openssl#15318]
This segmentation fault happens only with **drbg_name[]="CTR-DRBG"** 
NOT with **drbg_name[]="HMAC-DRBG"** and **drbg_name[]="HASH-DRBG"**

Following is the snippet of source code which is reproducing the issue (Almost same source is working with HMAC-DRBG & HASH-DRBG):

{
OSSL_PARAM params[4];
char cipher[]="AES-128-CTR";
char drbg_name[]="CTR-DRBG";
EVP_RAND *rand = NULL;
EVP_RAND_CTX *ctx = NULL, *parent = NULL;
rand = EVP_RAND_fetch(NULL,"TEST-RAND" , "-fips");
parent = EVP_RAND_CTX_new(rand, NULL);
EVP_RAND_free(rand);
rand = NULL;
strength=256;
params[0] = OSSL_PARAM_construct_uint(OSSL_RAND_PARAM_STRENGTH, &strength);
params[1] = OSSL_PARAM_construct_end();
CKINT(EVP_RAND_CTX_set_params(parent, params));
rand = EVP_RAND_fetch(NULL, drbg_name, NULL);
ctx = EVP_RAND_CTX_new(rand, parent);
strength = EVP_RAND_strength(ctx);
params[0] = OSSL_PARAM_construct_int(OSSL_DRBG_PARAM_USE_DF,
                                     (int *)(&df));
params[1] = OSSL_PARAM_construct_utf8_string(OSSL_DRBG_PARAM_CIPHER,
                                             (char *)cipher, strlen(cipher)+1);
params[2] = OSSL_PARAM_construct_utf8_string(OSSL_DRBG_PARAM_MAC, "HMAC", 0);

EVP_RAND_CTX_set_params(ctx, params)
params[0] = OSSL_PARAM_construct_octet_string(OSSL_RAND_PARAM_TEST_ENTROPY,
                                                  (void *)data->entropy.buf,
                                                  data->entropy.len);
params[1] = OSSL_PARAM_construct_octet_string(OSSL_RAND_PARAM_TEST_NONCE,
                                                  (void *) data->nonce.buf,
                                                  data->nonce.len);
params[2] = OSSL_PARAM_construct_end();
EVP_RAND_instantiate(parent, strength,0, NULL, 0, params);
z = data->pers.buf != NULL ? data->pers.buf : (unsigned char *)"";
EVP_RAND_instantiate(ctx, strength, data->pr, z, data->pers.len,NULL)
}

Backtrace:
#0  0x00007e5a5d840cb0 in evp_cipher_init_internal ()
   from /usr/local/lib/libcrypto.so.3
#1  0x00007e5a5d84119b in EVP_CipherInit_ex ()
   from /usr/local/lib/libcrypto.so.3
#2  0x00007e5a5d9677bb in drbg_ctr_instantiate ()
   from /usr/local/lib/libcrypto.so.3
#3  0x00007e5a5d97621c in ossl_prov_drbg_instantiate ()
   from /usr/local/lib/libcrypto.so.3
#4  0x00007e5a5d846120 in EVP_RAND_instantiate ()
   from /usr/local/lib/libcrypto.so.3
#5  0x0000570001f3f75a in ?? ()
#6  0x00007ffec9aa2450 in ?? ()
#7  0x00007ffec9aa21d0 in ?? ()
#8  0x0000000000000000 in ?? ()

**Comment by paulidale** [comment]
You got the length of a string wrong.  Change:
```C
params[1] = OSSL_PARAM_construct_utf8_string(OSSL_DRBG_PARAM_CIPHER,
(char *)cipher, strlen(cipher)+1);
```
to
```C
params[1] = OSSL_PARAM_construct_utf8_string(OSSL_DRBG_PARAM_CIPHER,
(char *)cipher, 0);
```

A reproducer that compiled would have made this easier.

**Comment by banvikas** [comment]
Thanks Pauli
It is working fine now.
