### ISSUE TITLE
ChaCha20's AVX-512(VL) assembly do not respect Microsoft x64 calling convention

### ISSUE THREAD

**Issue by jpboivin** [openssl/openssl#15314]
Hello,

Some AVX-512 and AVX-512VL assembly code for ChaCha20 is zeroing registers that should be preserved by the callee on Win64 platforms (as per [Microsoft doc](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#callercallee-saved-registers)). More precisely, `ChaCha20_avx512` and `ChaCha20_avx512vl` save the nonvolatile `xmm6` and `xmm7` registers properly, but they do not for `xmm8`-`xmm15`. In their teardown (the `done` part), they clear all YMM registers with `vzeroall`, zeroing the remaining nonvolatile XMM registers.

This issue has been seen with OpenSSL 1.1.1k, with a corrupted caller state after an OpenSSL call.

**Comment by t8m** [comment]
Fix is merged to both 1.1.1 and master.
