### ISSUE TITLE
unnecessarily complicated ifdef handling and namespace polution

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#15322]
https://github.com/openssl/openssl/blob/a227ff336fc934b4a52c4659ae423dfa10efd5f3/providers/fips/self_test.c#L71-L157

That is wrong to have declared a public _init_ and _cleanup_ function - they should not be visible as such. They should be static. That pollutes the namespace with a function name that is highly likely to clash with user function names and it also allows direct user invocation of the functions and if we planned to allow for that they should be ossl_ prefixed.

And the ifdef soup here is not the right approach IMHO - these functions are required.

#if defined(DEP_INIT_ATTRIBUTE) && defined(DEP_FINI_ATTRIBUTE)

The whole mess here is more complicated than it needs to be.

We should have a default define of those two items that does nothing (which is what the majority of platforms use) and then just the __GNUC__ attribute tagging. Or define a default if one is not set.
Repeating the same "junk" all over the place just clutters up the code with noise.

And on top of that the whole DEP_DECLARE() stuff is just wrong-thinking. It isn't at all required on any of the platforms if the code is simply slightly reorganised to have the GNUC attribute tagging done first then it can be directly used.

**Comment by paulidale** [comment]
Noting that there isn't any namespace pollution.  These symbols are linked into a shared object which doesn't export them.  The shared object's exports are not merged into the callers namespace.

That doesn't mean we shouldn't make them static.

**Comment by t8m** [comment]
AFAIK at least in some cases the DEP entry points cannot be static.
