### ISSUE TITLE
Build error in macOS

### ISSUE THREAD

**Issue by zorrorffm** [openssl/openssl#15321]
Build error is reported in macOS

`crypto/aes/bsaes-armv8.S:852:1: error: unknown directive
.size _bsaes_encrypt8,.-_bsaes_encrypt8
^
crypto/aes/bsaes-armv8.S:854:1: error: unknown directive`

This issue is introduced by PR #14592,  it implements bsaes-armv8.S following GAS syntax, but macOS assembler does not support directive like ".type"  , ".size".

It is supposed that we should implement a perl version for bsaes-armv8.S,  perl will generate correct ".S" code for different platforms.

**Comment by paulidale** [comment]
Agreed, a Perlasm version would be best.

**Comment by slontis** [comment]
Would it be better to revert this PR until it is resolved?

**Comment by paulidale** [comment]
Yes, good suggestion.
