### ISSUE TITLE
AppVeyor fails in cms test for the -binary option handling

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#15347]
Merge of #12959 introduced a regression in the cms test on Windows.

@DDvO ?

**Comment by t8m** [comment]
Log visible here: https://ci.appveyor.com/project/openssl/openssl/builds/39225692

**Comment by DDvO** [comment]
Hmm, this is hard to debug in particular without having a Windows system at hand.
And for PRs currently the Windows builds are disabled - how can I switch them on for a PR?
As a workaround I can simply disable the recently added tests for Windows.

**Comment by t8m** [comment]
As the failing test cases are now skipped on Windows, I am removing the urgent severity. It should still be investigated and fixed properly.

**Comment by DDvO** [comment]
Sure. 
Again my question: how to locally enable Windows CI runs?

**Comment by t8m** [comment]
@DDvO locally? You mean in a personal fork? Just enable actions in settings/actions on the forked repo.

**Comment by DDvO** [comment]
> @DDvO locally? You mean in a personal fork?

I meant for a specific PR, but for my (the Siemens) fork would do as well.

> Just enable actions in settings/actions on the forked repo.

I can't see how to do that. These are the options offered there to me:

![Screenshot_2021-05-19 siemens openssl actions](https://user-images.githubusercontent.com/4600384/118829077-1b861080-b8be-11eb-8148-8571d601f7a3.png)

**Comment by t8m** [comment]
With this you should be just able to cherry-pick the changes from #15349 and the tests should run for you.

**Comment by t8m** [comment]
As you can see here on my fork:
https://github.com/t8m/openssl/runs/2620681946

**Comment by DDvO** [comment]
I'm still struggling with the handling of file contents on Windows in CMS files that contain both text and binary portions, which on all other systems is no problem. 
Meanwhile it's clear that for such mixed contents binary mode is strictly needed because in case the binary section contains a Ctrl-Z (`0x1a)` character reading the file is terminated at this point because this is taken as EOF marker.

**Comment by DDvO** [comment]
MS-DOS (and actually CP/M) legacy in Windows has hit hard here.

Finally I've been able to solve this.
@t8m, I invite you to have a look at #15358.
