### ISSUE TITLE
Question: Where is SHA256_FINAL?

### ISSUE THREAD

**Issue by vvclin** [openssl/openssl#1534]
Hi,

Sorry for noobs question but I can't seem to find where the SHA256_FINAL function is implemented. Can somebody please shed some light?

Thanks

**Comment by mattcaswell** [comment]
In crypto/sha/sha256.c you will see this block of code:
````
#define HASH_UPDATE             SHA256_Update
#define HASH_TRANSFORM          SHA256_Transform
#define HASH_FINAL              SHA256_Final
#define HASH_BLOCK_DATA_ORDER   sha256_block_data_order
#ifndef SHA256_ASM
static
#endif
void sha256_block_data_order(SHA256_CTX *ctx, const void *in, size_t num);

#include "internal/md32_common.h"
````
Then in  md32_common.h you will find a definition of the HASH_FINAL function:
````
int HASH_FINAL(unsigned char *md, HASH_CTX *c)
{
...
}
````
Obviously `HASH_FINAL` here is a macro for SHA256_Final.

**Comment by vvclin** [comment]
Thanks for the quick reply!

So along that line, `md32_common.h` also has the definition of `SHA256_Update` function, which is `HASH_UPDATE`. Then in `openssl/crypto/evp/e_aes_cbc_hmac_sha256.c`, does

`# define SHA256_Update sha256_update`

override the `HASH_UPDATE` definition in `md32_common.h`?

**Comment by vvclin** [comment]
Ran a few simple tests and seems like it does override it for all lines below the define, but not above?

**Comment by wwhheerree** [comment]
Thanks for the info. It's really hard to figure out this kind of function implement
#define HASH_UPDATE             SHA256_Update
