### ISSUE TITLE
catched a hang in bignum with fuzzer AFL++

### ISSUE THREAD

**Issue by toralf** [openssl/openssl#15356]
It seems that this hang is reproducible here at my server
```
$ ./bignum-test default/hangs/id\:000000\,src\:000417\,time\:11050140\,op\:havoc\,rep\:8 
Warning: AFL++ tools will need to set AFL_MAP_SIZE to 79232 to be able to run this instrumented program!
# default/hangs/id:000000,src:000417,time:11050140,op:havoc,rep:8
^C

$ export AFL_MAP_SIZE=79232

$ ./bignum-test default/hangs/id\:000000\,src\:000417\,time\:11050140\,op\:havoc\,rep\:8 
# default/hangs/id:000000,src:000417,time:11050140,op:havoc,rep:8
```
still hangs.
The hang was catched by the scripts under https://github.com/toralf/fuzz-utils, the archived file is in: https://zwiebeltoralf.de/pub/fuzz/

**Comment by toralf** [comment]
FWIW this is rather a bug than a "question"

**Comment by toralf** [comment]
and there are more of this kind : https://zwiebeltoralf.de/pub/fuzz/openssl_bignum_20210521-141609_819b94c0c0d3.tar.xz

**Comment by davidben** [comment]
The bignum fuzzer does modular exponentiations, which take roughly cubic time. So the first thing to check is what are the actual inputs being fuzzed. If they're large, this could just be expected. (In which case the answer would be for fuzzer infrastructure to bound the input size on that fuzzer, or for the fuzzer to internally skip inputs beyond some hard-coded size.)

**Comment by nhorman** [comment]
several of our fuzzers have been updated to limit input sizes where this has been observed to be a problem.  Please recheck with the latest build.

As such, Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by toralf** [comment]
[bignum-hangs.tar.gz](https://github.com/user-attachments/files/16381358/bignum-hangs.tar.gz)

got more today for 
```
~/sources/openssl $ git describe
openssl-3.2.0-alpha2-1464-g3c6e114959

```

**Comment by nhorman** [comment]
I'm a bit confused here.  you recently opened https://github.com/openssl/openssl/issues/21645
which describes afl-fuzz taking a long time, and you also have this issue, indicating a hang.  Are these duplicates of one another?  If so, lets close one and work on the other.

I'm having trouble compiling with afl-clang-fast at the moment (fedora 40 seems to have a problem in the package where one of the plugins is unable to resolve a C++ symbol.

In the interim, while I sort that out, if this is in fact a hang, can you attach gdb to the hung process and grab a backtrace to give us some insight as to where the process is stuck?

**Comment by toralf** [comment]
One ticket is enough - indeed. I answered here due to "Please recheck with the latest build."
Attaching a gdb is not to easy here. A hang means usually "takes much longer than expected" - and finally the fuzzer continues after a certain time frame - usually just seconds. The fuzzer is done at my server which runs 24/7 but usually I'm either not connected or realize the hangs hours later.

**Comment by nhorman** [comment]
ack, lets close this bug, and continue work in your other one, as thats got almost all the info, and is already in an active state.
