### ISSUE TITLE
seg fault on executing 'openssl spkac'

### ISSUE THREAD

**Issue by sahanaprasad07** [openssl/openssl#15367]
currently on master, running 'openssl spkac' results in a seg fault.

(gdb) run spkac
Program received signal SIGSEGV, Segmentation fault.
0x0000000000478a75 in app_load_config_internal ()
(gdb) bt
#0 0x0000000000478a75 in app_load_config_internal ()
#1 0x000000000046cc59 in spkac_main ()
#2 0x0000000000444c09 in do_cmd ()
#3 0x0000000000422457 in main ()

OpenSSL version used:
OpenSSL 3.0.0-alpha17-dev

**Comment by paulidale** [comment]
This happens when no input file is specified.
Definitely a bug since it is documented as working (using stdin).
