### ISSUE TITLE
Too aggressive error suppressing

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15372]
Before #15371 is merged, when the digest was not found, there was no relevant output in the STDERR.
I suppose we have too aggressive error suppression somewhere in the EVP_SignInit* stuf

The command 
```
openssl dgst -d -hmac key data.txt
```
doesn't print any relevant error message though the `ERR_print_errors` is called.

**Comment by beldmit** [comment]
How should we label this issue to be triaged?

**Comment by mattcaswell** [comment]
> How should we label this issue to be triaged?

Just add the "triaged: bug" label to say its been triaged by a committer but don't add the "OTC evaluated" label until OTC have looked at it. If you think its important to look at soon then add it to the beta 1 milestone (which I see you have done).

**Comment by levitte** [comment]
The fact is that we have *lots* of places in the provider code where we just return 0 or NULL with no error reporting whatsoever.  It's not error suppression, it's *lack of error reports*

**Comment by beldmit** [comment]
I think we have both cases really. Don't know what exactly happens here.

**Comment by richsalz** [comment]
Is there something we can do in the apps to ensure that all specified providers are loaded, via an API? This is something that https://github.com/openssl/openssl/blob/master/apps/dgst.c#L232 was intended to handle. But maybe that's not the problem?

**Comment by levitte** [comment]
> Is there something we can do in the apps to ensure that all specified providers are loaded, via an API?

Yes

https://github.com/openssl/openssl/blob/340cf8759f904859e609cecf4315b7cb50cde561/include/openssl/provider.h#L24

**Comment by levitte** [comment]
When it comes to the apps, there's the config file, but it's harder to get errors that way
*Some* apps have a `-provider` flag, which I believe end up calling `OSSL_PROVIDER_load()`

**Comment by richsalz** [comment]
Okay, let me be a bit more verbose.

The -provider_path, -provider, and -prop_query flags are handled by common code, in https://github.com/openssl/openssl/blob/340cf8759f904859e609cecf4315b7cb50cde561/apps/lib/app_provider.c  Those functions *seem* to load and check the provider right away. Are they doing that?  If they are, then my question is why doesn't the check in https://github.com/openssl/openssl/blob/master/apps/dgst.c#L232 do the right thing?

**Comment by levitte** [comment]
Hmmm, you're right that `opt_md()` doesn't use any propq:

https://github.com/openssl/openssl/blob/2ed0a45a65b0df10648a4c11d365e2e1ebb1e697/apps/lib/opt.c#L397-L419

**Comment by richsalz** [comment]
So should `opt_md` use the app_propq?  And similar for `opt_cipher`?

**Comment by levitte** [comment]
... and the next question is also, if either the app propq or library context is non-NULL, or a default propq is set, should `EVP_get_digestbyname()` be called at all?

This discussion sounds like someone should raise an issue, btw

**Comment by richsalz** [comment]
I don't know if a discussion is needed.  If you specify query and or providers and or libraries, then call the evp-get-by-name routine seems wrong.  See #15414 which does that.  But it breaks the CMS tests.

**Comment by DDvO** [comment]
> The command
> 
> ```
> openssl dgst -d -hmac key data.txt
> ```
> 
> doesn't print any relevant error message though the `ERR_print_errors` is called.

I just had a related issue with **external-tests** using the gost engine, see https://github.com/openssl/openssl/pull/12095#issuecomment-846111317

**Comment by beldmit** [comment]
I'm afraid it's a different problem. GOST engine is rather picky to console output, but here it looks like we have no errors on stack.

**Comment by paulidale** [comment]
This is slated for 3.0 but it is not clear to me what needs to be done.  Can somebody provide some clarification?

The lack of libctx/propq was covered in #15687
The EVP_fetchbyname() PR #15414 seems to have stalled, does this need to be kicked along?

**Comment by beldmit** [comment]
@paulidale could you please rollback the changes from #15371 and test if the relevant information is present in stderr (meaning that the error was put into the stack)? The original bug report was about that.

**Comment by paulidale** [comment]
Without the changes in #15371 I just get the message _Error setting context_.  With the changes the MAC is computed.

Ths doesn't appear to be error suppression, rather it looks like a failure case isn't being handled.  I'll put a _no defualt digest_ in place.

**Comment by beldmit** [comment]
`Error setting context` is an app-level error, isn't it? We should also get a library error. Yes, it could be just omitted by an accident. I also don't think that #15414 fix it.

**Comment by paulidale** [comment]
#16015 just might :grinning:

**Comment by richsalz** [comment]
I first did #15414 but then @levitte did some work on it and I turned it over to him.  Maybe he forgot that I did that. :)

**Comment by levitte** [comment]
My last comment in #15414 is "I don't agree with the solution any longer"
