### ISSUE TITLE
OpenSSL closes the connection when client drops psk_key_exchange_modes ext in renegotiation

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#15375]
When running current master (d5e08231dbef8) and 1.1.1-stable (7e12c2b3d9ccf97186e4) openssl just closes the connection when it receives a renegotiation ClientHello that drops the psk_key_exchange_modes extension compared to the initial ClientHello.

This is a regression compared to openssl-3.0.0-alpha16 and 1.1.1k.

Reproducer:
```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www -client-renegotiation
```
And in separate terminal:
```
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tlsfuzzer/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/tlsfuzzer/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python3 scripts/test-renegotiation-changed-clienthello.py -d
```
Result:
```
drop psk_key_exchange_modes in renegotiation ...
Error encountered while processing node ExpectServerHello(description='second handshake') (child: <tlsfuzzer.expect.ExpectCertificate object at 0x7eff4774f7f0>) with last message being: None
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 196, in run
    header, parser = self.state.msg_sock.\
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 102, in recvMessageBlocking
    for res in self.recvMessage():
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 84, in recvMessage
    for ret in self.recvRecord():
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 893, in recvRecord
    for result in self._recordSocket.recv():
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 210, in recv
    for record in self._recvHeader():
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 144, in _recvHeader
    for result in self._sockRecvAll(1):
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 131, in _sockRecvAll
    raise TLSAbruptCloseError()
tlslite.errors.TLSAbruptCloseError: TLSAbruptCloseError()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/test-renegotiation-changed-clienthello.py", line 408, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 222, in run
    raise AssertionError(
AssertionError: Unexpected closure from peer
```

`ec_point_formats` also fails, but that's tracked in #14875

**Comment by tomato42** [comment]
Given that on 1.1.1 bisect points out to either 1ab7b9991ba00a or 5d88a9c62c81e, it looks like it was introduced by the #14749.
@kaduk any ideas why it would impact TLS 1.2 connections?

**Comment by kaduk** [comment]
The relevant part here seems to not be that the "psk_key_exchange_modes" is dropped on renegotiation, but rather that "pre_shared_key" is present without "psk_key_exchange_modes", ever.
"pre_shared_key" is defined in RFC 8446, and that RFC is quite clear that if you send "pre_shared_key" you have to send "psk_key_exchange_modes" as well.  You should modify your test to drop both psk and psk_kex_modes, not just psk.

I know that boringssl did not enforce this requirement until recently, either (https://github.com/google/boringssl/commit/3af62269df3525ea526a2b6de0d7c70e8f8d5919 ).  I don't know if the file being "tls13_server.cc" means that the check is not performed for other TLS versions.

**Comment by davidben** [comment]
> I don't know if the file being "tls13_server.cc" means that the check is not performed for other TLS versions.

I believe in our current implementation, that check is only enforced at TLS 1.3. But I think it's a bit ambiguous what one does with a ClientHello which you know is invalid for some other version, but isn't invalid at the version you chose. The spec doesn't really say, and you can naturally end up with one or the other interpretation depending on how your implementatino works.

I'd agree that the test is doing something odd here and should probably drop both extensions.

**Comment by t8m** [comment]
Closing.

**Comment by tomato42** [comment]
Even if we decide that looking at TLS 1.3 extensions in a TLS 1.2 connection is somehow valid, I don't see how aborting the connection without sending an alert is consistent with the overall OpenSSL behaviour.

**Comment by tomato42** [comment]
@davidben 
> I'd agree that the test is doing something odd here and should probably drop both extensions.

The whole point of the test is to cause the server to misbehave, for that it does need to do stuff that's inconsistent or "odd".
How else are we supposed to verify that handling of such misbehaving clients is implemented correctly?

**Comment by t8m** [comment]
Reopening as the 'not sending alert' is certainly valid problem.

**Comment by kaduk** [comment]
I guess it's https://github.com/openssl/openssl/blob/master/ssl/t1_enc.c#L851-L852 in `tls1_alert_code()` that treats all unrecognized alert codes as "don't send an alert" as opposed to squashing to a generic one.  (There is not currently a `SSL_AD_NO_ALERT` special case, so I guess to some extent we are relying on it.)

**Comment by kaduk** [comment]
https://github.com/openssl/openssl/pull/15412 just adds the one alert to the "allowed list".
I don't have the historical background for why we do filtering at that stage and whether it's still a good idea to do so.

**Comment by davidben** [comment]
Dates to 0.9.0b apparently. I guess SSL 3.0 to TLS 1.0 defined a ton more alerts, but they wanted to keep the SSL 3.0 path sending the old ones. I suppose, if you wanted to, you could map missing_extension to a more generic one in earlier versions. We don't bother and just send the alert codes as-is.
https://boringssl-review.googlesource.com/c/boringssl/+/6843/

**Comment by tomato42** [comment]
First, I think that interpretation of RFC 8446 is wrong. It doesn't say that TLS 1.3 limitations also apply to TLS 1.2 ClientHello. It states exact opposite: in [section 4.1.2](https://datatracker.ietf.org/doc/html/rfc8446#section-4.1.2) states that during renegotiation, even when a fully compliant TLS 1.3 ClientHello is received the implementations MUST NOT negotiate TLS 1.3:
```
   If a server established a TLS connection with a previous version of
   TLS and receives a TLS 1.3 ClientHello in a renegotiation, it MUST
   retain the previous protocol version.  In particular, it MUST NOT
   negotiate TLS 1.3.
```
And it clearly states that TLS 1.2 requirements do override TLS 1.3 requirements when TLS 1.2 gets negotiated, in [section 4.2.3](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.3):
```
   TLS 1.3
   implementations willing to negotiate TLS 1.2 MUST behave in
   accordance with the requirements of [RFC5246] when negotiating that
   version. 
```
While there are multiple places where TLS 1.3 does override TLS 1.2 behaviour (e.g. certificates in Certificate or RSA-PSS signatures), each and every one of them does that _explicitly._ PSK and PSK_modes ext handling doesn't say that it applies to TLS 1.2 ClientHello messages (or for that matter, TLS 1.3-draft ClientHello messages).

Second, while TLS 1.2 is not explicit about handling of unrecognised alert description, it is explicit in handling of [fatal alerts](https://datatracker.ietf.org/doc/html/rfc5246#section-7.2):
```
   Alert messages
   with a level of fatal result in the immediate termination of the
   connection. 
```
so as long as OpenSSL never sends a warning level `missing_extension` Alert, I don't think it's dangerous to send it.
If it could be a `warning`, then yes, I can imagine sending an alert from future extension or protocol version as being problematic.

**Comment by davidben** [comment]
Warning alerts (mostly) no longer exist.

**Comment by kaduk** [comment]
> First, I think that interpretation of RFC 8446 is wrong. It doesn't say that TLS 1.3 limitations

This is not a matter of TLS 1.2 vs TLS 1.2.  This is a question of the semantics of the "pre_shared_key" extension.  RFC 8446 happens to be the reference for that, but the semantics of the extension are not tied to using TLS 1.3.

The TLS 1.2 renegotiation semantics don't give you free reign to send whatever jumbled mismatch of extensions you want; you still have to conform to the requirements and semantics of the extensions you send.  If you send "pre_shared_key", you have to send "psk_key_exchange_modes".  This holds for all TLS versions not because RFC 8446 is changing the semantics of other TLS versions, but rather because RFC 8446 is defining an extension to have particular semantics.   This still holds even if RFC 8446 says that you are obligated to not use the contents of the extension to negotiate a TLS 1.3 resumption and must retain the previous TLS version, because it is a property of the extension that the client chooses to send.

In your interpretation, you seem to be claiming that because the "pre_shared_key" extension is only useful to send for TLS 1.3, it somehow has no semantics when sent for other TLS versions; I don't see anything to support such a claim.

> so as long as OpenSSL never sends a warning level missing_extension Alert, I don't think it's dangerous to send it.

Well, it's sent here by the `SSLfatal()` macro, which inherently sets the "fatal" level.
