### ISSUE TITLE
apps use `EVP_xxx` to fetch ciphers and digest

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15385]
They should instead use a default *name* of the algorithm and do the opt_md/opt_cipher lookup after the providers are loaded.

Failing that, it needs to be pointed out in the FIPS policy that the apps *are not necessarily* FIPS compliant.

```
; g grep 'EVP_[a-z0-9_]*()' apps
apps/cms.c:            cipher = (EVP_CIPHER *)EVP_des_ede3_cbc();
apps/crl.c:    EVP_MD *digest = (EVP_MD *)EVP_sha1();
apps/dgst.c:            md = (EVP_MD *)EVP_sha256();
apps/enc.c:        dgst = (EVP_MD *)EVP_sha256();
apps/ocsp.c:                cert_id_md = (EVP_MD *)EVP_sha1();
apps/ocsp.c:                cert_id_md = (EVP_MD *)EVP_sha1();
apps/passwd.c:        || !EVP_DigestInit_ex(md, EVP_md5(), NULL)
apps/passwd.c:        || !EVP_DigestInit_ex(md2, EVP_md5(), NULL)
apps/passwd.c:        if (!EVP_DigestInit_ex(md2, EVP_md5(), NULL))
apps/passwd.c:        sha = EVP_sha256();
apps/passwd.c:        sha = EVP_sha512();
apps/pkcs12.c:    EVP_CIPHER *default_enc = (EVP_CIPHER *)EVP_aes_256_cbc();
apps/pkcs12.c:            enc = (EVP_CIPHER *)EVP_des_ede3_cbc();
apps/pkcs8.c:                cipher = (EVP_CIPHER *)EVP_aes_256_cbc();
apps/pkcs8.c:                cipher = (EVP_CIPHER *)EVP_aes_256_cbc();
apps/pkcs8.c:        cipher = (EVP_CIPHER *)EVP_aes_256_cbc();
apps/rehash.c:    evpmd = EVP_sha1();
apps/req.c:    cipher = (EVP_CIPHER *)EVP_des_ede3_cbc();
apps/smime.c:            cipher = (EVP_CIPHER *)EVP_des_ede3_cbc();
apps/speed.c:        if (!EVP_DigestSignInit(sm2ctx[testnum], NULL, EVP_sm3(),
apps/speed.c:        if (!EVP_DigestVerifyInit(sm2ctx[testnum], NULL, EVP_sm3(),
apps/speed.c:                                    EVP_sm3(), NULL, sm2_pkey))
apps/speed.c:                                      EVP_sm3(), NULL, sm2_pkey))
apps/spkac.c:        i = NETSCAPE_SPKI_sign(spki, pkey, EVP_md5());
; 
```

**Comment by mattcaswell** [comment]
> They should instead use a default name

Why does it make a difference to FIPS compliance? If you use `EVP_sha256` and  only have the FIPS provider loaded then it will use the FIPS implementation.

**Comment by richsalz** [comment]
Some of those settings are done in variable initialization time before the config file is parsed and loaded.

If you're sure that doesn't matter, and that the code is correct, then I guess the ony thing that needs to be done to address this is to document the config file, it's autoload, and how to specify the FIPS provider, right?

Right now, the uninformed user will just assume they can specify `-provider fips` and the right thing will happen and I think they're wrong.

**Comment by richsalz** [comment]
More importantly, the `EVP_sha256` just returns a pointer to an internal global variable. It doesn't do any *fetching*

**Comment by mattcaswell** [comment]
3. They haven't loaded an ENGINE that implements the same algorithm

**Comment by richsalz** [comment]
Thank you for the explanation. I had forget about the magic lookup under the covers. I will close this.
