### ISSUE TITLE
req command doesn't work with providers 

### ISSUE THREAD

**Issue by anhu** [openssl/openssl#15388]
....therefore if your implementation is in a provider, it won't be found.  I believe I was told in a past PR that `EVP_PKEY_asn1_find_str()` was to be deprecated.

**Comment by anhu** [comment]
There is a fairly simple work.around which is to generate a private key file first with `genpkey`. And then use that file as the parameter to `-key` instead of using `-newkey`

**Comment by anhu** [comment]
.......req calls EVP_PKEY_asn1_find_str() with the algorithm string. It does not consider providers.

**Comment by levitte** [comment]
Good catch.  It's not very hard to adapt it, PR coming up!

**Comment by levitte** [comment]
Refactoring is in #15400, currently in draft

**Comment by anhu** [comment]
@levitte , should I mark this as closed or will you?

**Comment by levitte** [comment]
@anhu, it will happen automatically when #15400 is merged, since the commit there has "Fixes #15388" in it
