### ISSUE TITLE
make test fails when there's an example.com entry in /etc/hosts 

### ISSUE THREAD

**Issue by sftcd** [openssl/openssl#15395]
``make test TESTS=test_cmp_http V=1`` fails if there's an example.com entry in /etc/hosts

Test ran on ubuntu 20.10 with latest openssl (found it while re-merging with upstream).

I often use example.com for testing and typically have an entry in /etc/hosts like:
```
127.0.1.3 example.com
```

Commenting that out means tests pass. Uncomment it and that test fails. I didn't check the details as to why.

I'd recommend maybe using ``<random>.example.com`` in test scripts or similar

**Comment by levitte** [comment]
Okie, that's easily done.  PR coming up!

**Comment by levitte** [comment]
See #15398, please try it out

**Comment by sftcd** [comment]
On 21/05/2021 05:14, Richard Levitte wrote:
> See #15398, please try it out

Looks good. Once I figured a way to pull in that change
``make test`` worked fine with and without the offending
stanzas in /etc/host.

Thanks,
S.
