### ISSUE TITLE
doc-nits failure

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15407]
Doing `make doc-nits` gives the following errors:
```
/usr/bin/perl ./util/find-doc-nits -c -n -l -e
Complex regular subexpression recursion limit (32766) exceeded at ./util/find-doc-nits line 1004.
.. repeated for 110 lines ...
```

**Comment by romen** [comment]
This is being addressed as part of #15449 and should get fixed by #15450 .

Marking this as a duplicate and closing, even if it predates #15449 , just because most of the discussion happened over there.
