### ISSUE TITLE
undefined reference to `ossl_ecdsa_sign_sig' in OpenSSL_1_1_1-stable

### ISSUE THREAD

**Issue by jack-tan2** [openssl/openssl#15403]
recently i am reading the openssl's source code on ecdsa algorithm to optimize the performance, the version is Openssl 1.1.1 stable. i want cut out the low level fuction such as `ossl_ecdsa_sign_sig` and `ossl_ecdsa_verify_sig` run it, it means i want call the two fuctions directly, because i think it can make me easier to analyze code and optimize code. but when i write a program to call the two function, the error hanppened : `undefined reference to ossl_ecdsa_sign_sig` , i am sure i link the `libcrypto.a`, and the library contains the `ecdsa_ossl.o` which defined the function ossl_ecdsa_sign_sig and ossl_ecdsa_verify_sig. 

this is my Makefile, in this file i have link the libcrypto.a, and i have compile the openssl source code to generate the library:
```c
CFLAGS=-Wall -O0 -g
#CFLAGS=-Wall -O0 -g3 -pg -gdwarf-2
CC=gcc

app: test1.o 
	$(CC) $(CFLAGS)	\
		-o $@ test1.o	\
		-L /home/tam/Documents/openssl-OpenSSL_1_1_1-stable/ -lcrypto


test1.o: test1.c
	$(CC)	-I/home/tam/Documents/openssl-OpenSSL_1_1_1-stable/include	\
	-I/home/tam/Documents/openssl-OpenSSL_1_1_1-stable/crypto/ec	\
		$(CFLAGS)\
		-c -o $@ test1.c

clean:
	rm -f *.o app

```

this is my source code which attempt to call two fuctions `ossl_ecdsa_sign_sig` and `ossl_ecdsa_verify_sig`(the last two lines, i call the two low level fuctions which have been defined in  `ecdsa_ossl.o`, and it is included in library `libcrypto.a`:
```c
#include "testutil.h"

#include <openssl/evp.h>
#include <openssl/bn.h>
#include <openssl/ec.h>
#include <openssl/ossl_typ.h>
#include <openssl/rand.h>
#include "ecdsatest.h"
#include <openssl/crypto.h>
//#include <ec_local.h>
#include <stdint.h>

// use extern to declare the two fuctions
extern int ossl_ecdsa_verify_sig(const unsigned char *dgst, int dgst_len,
                         const ECDSA_SIG *sig, EC_KEY *eckey);
extern ECDSA_SIG *ossl_ecdsa_sign_sig(const unsigned char *dgst, int dgst_len,
                               const BIGNUM *in_kinv, const BIGNUM *in_r,
                               EC_KEY *eckey);

size_t crv_len = 0;
EC_builtin_curve *curves = NULL;

int main(){
  int res1 = 0;
  EC_KEY *eckey = NULL;
  unsigned char dirt, offset, tbs[20]="i love you,love you";
  unsigned char *sig = NULL;
  EVP_PKEY *pkey = NULL;
  EVP_MD_CTX *mctx = NULL;
  size_t sig_len;
  int nid = 0;

  ECDSA_SIG *ret = ECDSA_SIG_new();

  uint64_t t1, t2;

  crv_len = EC_get_builtin_curves(NULL,0);
  curves = OPENSSL_malloc(sizeof(*curves) * crv_len);
  EC_get_builtin_curves(curves,crv_len);


  for(int i=0; i<crv_len; i++){
    nid = curves[i].nid;
    printf("testing ECDSA is %dth, name is %s\n", i+1, OBJ_nid2sn(nid));
  }

  nid = curves[64].nid;

  //mctx = EVP_MD_CTX_new();
  eckey = EC_KEY_new_by_curve_name(nid);
  EC_KEY_generate_key(eckey);
  pkey = EVP_PKEY_new();
  EVP_PKEY_assign_EC_KEY(pkey,eckey);

  sig_len = ECDSA_size(eckey);
  //printf("sig_len的长度为：%d\n",sig_len);
  sig=OPENSSL_malloc(sig_len);

  int dgst_len = 32;
  const unsigned char *dgst[35] = {0x39	,0x74	,0xbf	,0x95	,0xaa	,0x7d	,0xdb	,0xe6,0x63,	0x89,	0xd9,	0xea,	0x50,	0x44,	0xdb,	0xd1,0xbf,	0xce,	0xb6,	0xc8,	0xb8,	0x8c,	0x2e,	0xd5,0xa2,	0x4f,	0xe3,	0x83,	0x6c,	0xd3,	0x36,	0x4f
  };

  BIGNUM *in_kinv = BN_new();
  BIGNUM *in_r = BN_new();

  ret = ossl_ecdsa_sign_sig(dgst, dgst_len, in_kinv, in_r, eckey);

  res1 = ossl_ecdsa_verify_sig(dgst, dgst_len, ret, eckey);

}
```
when i use `make` command, the console output the error message below:
gcc -Wall -O0 -g	\
	-o app test1.o	\
	-L /home/tam/Documents/openssl-OpenSSL_1_1_1-stable/ -lcrypto
/usr/bin/ld: test1.o: in function `main':
/home/tam/shares/win10-share/编程linux二进制imp/Openssl学习/day04_简化版ECDSA/test1.c:69: `undefined reference to `ossl_ecdsa_sign_sig'`
/usr/bin/ld: /home/tam/shares/win10-share/编程linux二进制imp/Openssl学习/day04_简化版ECDSA/test1.c:71: `undefined reference to `ossl_ecdsa_verify_sig'`
collect2: error: ld returned 1 exit status
make: *** [Makefile:6：app] 错误 1

so is there any solution to help me out to call the two low level ECDSA sig fuctions?

**Comment by t8m** [comment]
You're most probably linking to the system-wide libcrypto.so and not the libcrypto.a from your build. Just use a  /full/path/to/libcrypto.a instead of -lcrypto when linking?

**Comment by jack-tan2** [comment]
> You're most probably linking to the system-wide libcrypto.so and not the libcrypto.a from your build. Just use a /full/path/to/libcrypto.a instead of -lcrypto when linking?

thank you for your help, i have solved this problem with linking /full/path/to/libcrypto.a and -lpthread, -ldl

**Comment by paulidale** [comment]
Closing since this is answered.
