### ISSUE TITLE
Move no-client-renegotiation test

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15410]
@mattcaswell pointed out in https://github.com/openssl/openssl/pull/15184#issuecomment-840617351 that a better place to do the test is not in `test_renegotiation` but in `test/ssl-tests/17-renegotiate.cnf.in`

Doing this could remove the `-client_renegotiation` flag from `s_server` but that could be seen as an API change.

**Comment by kaduk** [comment]
It's a new API for 3.0, so not quite locked in as something we have to support, though.

**Comment by richsalz** [comment]
#15415 moved the test to the right spot, so closing.
