### ISSUE TITLE
RSA key strength calculations in FIPS mode

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#15421]
Currently in FIPS mode RSA keys of 15360 bits are rejected.
NIST's 2020 recommendations have the security strength of those sized keys noted as 256.

ossl_rsa_sp800_56b_validate_strength returns a different value

crypto/rsa/rsa_sp800_56b_gen.c has a check with an upper bound.

That upper bound check really should **not** be in place as we should not be stopping people from using strengths greater than what a NIST SP document shows (i.e. exceeding should not be a fatal error for usage). 

```
#ifdef FIPS_MODULE
    if (s < RSA_FIPS1864_MIN_KEYGEN_STRENGTH
            || s > RSA_FIPS1864_MAX_KEYGEN_STRENGTH) {
        ERR_raise(ERR_LIB_RSA, RSA_R_INVALID_MODULUS);
        return 0;
    }
#endif

```

**Comment by slontis** [comment]
Pauli - what does that horrible formula return for 15360? (If it returns >256 then that is not a good change..)
The max strength of the entropy in OpenSSL is 256 bits. If we try to generate something with a larger strength than this,then it should fail.

**Comment by slontis** [comment]
> what a NIST SP document shows (i.e. exceeding should not be a fatal error for usage).

For FIPS mode - I completely disagree.

**Comment by t-j-h** [comment]
NIST has always allowed exceeding their sizes. And they have not required technical enforcement of sizes. 
So I think you are incorrect on multiple grounds. 
But I do have a question in with the lab to see what their view on the approach is.

**Comment by slontis** [comment]
See the comment above related to entropy..

**Comment by slontis** [comment]
You cant use a strength higher than your entropy bit strength (If it is 256 then it is ok).

**Comment by t-j-h** [comment]
This code path has absolutely **nothing** to do with entropy. It is entirely about the input request size. There is no check on entropy properties at all - and nor should there be. You are mixing two different things up here I think.

**Comment by paulidale** [comment]
NISTs formula returns 264.  The table now includes 15360 listed at 256 bits of strength.  There is also a note saying that the table should be used first then the formula, so the current code is wrong.  The fix for this is in #15428.

**Comment by slontis** [comment]
We are probably talking at cross purposes here.. You normally chose a bigger key so that you have a higher bit strength.
ossl_rsa_sp800_56b_generate_key() calls this function. keygeneration does depend on the maximum entropy strength.

**Comment by t-j-h** [comment]
We are talking about different things for sure - you are talking about what we wouldn't be allowed to change if this code did something entirely different from what it actually does. It is something where it is perfectly fine to accept larger values and not have an upper bound.

If somewhere else we had some code that was limited the strength claim to the underling entropy properties then it would be reasonable for it to cap things (i.e. cap this claim down to a lower value). But that is **not** what this code is doing and not anything to do with what this actual check is about.

Conceptually, we should not be enforcing upper bounds here - the lower bound limits make sense - the upper ones simply do not.

**Comment by slontis** [comment]
No idea what you are talking about. It is being used in keygeneration.

**Comment by t8m** [comment]
If NIST table says 15360 bits has security strength of 256 bits then we should be OK generating it. Whether we should be allowed to generate bigger keys is debatable as those then should imply a higher security strength and we are not able to to create keys with higher security strength with our DRBG.

**Comment by mattcaswell** [comment]
OTC: There should be no upper bound at this point in the code

**Comment by paulidale** [comment]
One little confounding issue here.  The BN_rand calls do not have a concept of security strength.  So generating an RSA key with > 15360 bits will claim a strength > 256 bits which is impossible with the DRBGs we use.  We should error out in this case.

**Comment by slontis** [comment]
yep..

**Comment by t-j-h** [comment]
As was discussed in the OTC call - the RNG solution is replaceable - so the properties are variable.  We do not provide the right hooks to enable linkage of the two contexts (security strength based entirely and solely on the size of the key which is what is happening at this point, compared to the strength of the RNG used during the key generation process) here so there is no place to apply a limit which we don't know if it is valid.

And in this specific context raised - this is about an upper bound check in the FIPS context - and FIPS does not require an upper bound check at all. It should simply be removed.

You are talking at cross purposes here if you are saying we should have a check of the strength of the RNG used at this point in time. This is not that check. This is a different check. And if there was such a RNG strength check it would be elsewhere and the code elsewhere would need to be plumbed differently. That is not something the code is designed to do and not something we are changing in 3.0. We also discussed explicitly that point on the OTC call.

**Comment by slontis** [comment]
There should be a disclaimer somewhere in OpenSSL documentation then, since OpenSSL is generating 'weak' keys.

**Comment by slontis** [comment]
i.e It is pointless currently to generate a larger key (other than for compatability purposes).

**Comment by paulidale** [comment]
A disclaimer is to be added.

I'm going to check to see if we can add a check in the RSA key gen code.
