### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_SSLeay_add_all_algorithms"

### ISSUE THREAD

**Issue by charsdavy** [openssl/openssl#1543]
```
Undefined symbols for architecture x86_64:
  "_SSLeay_add_all_algorithms", referenced from:
      _config_encryption in encrypt.o
```

How can I to do?

**Comment by levitte** [comment]
I assume this is with OpenSSL 1.1.0, right?  Simply remove the call to `SSLeay_add_all_algorithms`, the addition is now done automatically and internally in libssl.
