### ISSUE TITLE
util/perl/OpenSSL/config.pm does not detect solaris os

### ISSUE THREAD

**Issue by orcl-jlana** [openssl/openssl#15435]
running on Solaris 11.4 on Sparc platform the [./Configure](https://github.com/openssl/openssl/blob/master/Configure) script reports it as unixware-7:

 ```
$ uname -X
System = SunOS
Node = host-8-62.osc.uk.oracle.com
Release = 5.11
KernelID = 11.4.36.96.0
Machine = sun4v
BusType = <unknown>
Serial = <unknown>
Users = <unknown>
OEM# = 0
Origin# = 1
NumCPU = 512

$ perl ./Configure
Configuring OpenSSL version 3.0.0-beta1-dev for target unixware-7
...
```

This breaks the buildbot FIPS builds on the platform

**Comment by levitte** [comment]
The guessing should end up in this code snippet...  it's to wonder what goes wrong.

https://github.com/openssl/openssl/blob/7217decc7c454eec4a6d4ce163ac44b4558fe03b/util/perl/OpenSSL/config.pm#L684-L718

**Comment by orcl-jlana** [comment]
it is broken a bit earlier - this return true for solaris and mislead the config.pm script:
 https://github.com/openssl/openssl/blob/7217decc7c454eec4a6d4ce163ac44b4558fe03b/util/perl/OpenSSL/config.pm#L195-L210

I am preparing a patch for solaris.

**Comment by levitte** [comment]
#15439 is merged, so closing this
