### ISSUE TITLE
crypto/aes/aes-x86_64.s:2659:31: error: expected string in directive         .section .note.gnu.property, #alloc

### ISSUE THREAD

**Issue by Cassielcc** [openssl/openssl#15431]
I build the openssl with clang compiler on Ubuntu, There is an error,
crypto/aes/aes-x86_64.s:2659:31: error: expected string in directive         
                                    .section .note.gnu.property, #alloc

I found that this issue has been fixed in https://github.com/openssl/openssl/pull/11219, but clone the latest source code and built with clang, there was still the same error. I am not sure if it is a regression issue.  Is there a workaround for this issue?

**Comment by t8m** [comment]
We have CI jobs using clang on Ubuntu which build and test correctly.  So it must be some other issue with the build environment you're using. What Ubuntu and clang do you have? How do you invoke the OpenSSL Configure and build?

**Comment by Cassielcc** [comment]
Thanks @t8m , it is related the clang compiler I used. I use another version, there is no this error. So please close this ticket.

**Comment by engineer1109** [comment]
meet this problem on Android NDK 21.63(Clang-9)
