### ISSUE TITLE
Re-introduce support for C++ Builder

### ISSUE THREAD

**Issue by martinprikryl** [openssl/openssl#1544]
Since OpenSSL 1.1.0, there's no support for building the OpenSSL library using Borland/Embarcadero C++ Builder.

The supports was removed by the commit 2fe730362812e3c7d364197449a9439e3cb5915b:

> The Borland C++ config is commented away for the monent, perhaps
permanently.

I can image you may not have a dev env for this and that the support may need to come from a 3rd party. I'm just filing this issue to show that there's still a demand for C++ Builder support.

Note that I'm aware of a possibility of using MS-built DLL from C++ Builder application. I'm looking for a static library.

Thanks.

**Comment by levitte** [comment]
The Borland config was completely removed later on, in 8e56a4227bcd2e3eeb1cb18f3d0d5876ed76a8ce

However, there's nothing stopping you from creating your own config files and putting them in the Configurations directory, or in a separate directory that you can refer to when configuring, like this:

```
set OPENSSL_LOCAL_CONFIG_DIR=drv:\path\to\local\openssl\configs
perl Configure BC-32
```

For this to work correctly, you must have a file named `{something}.conf` (`{something}` can be whatever you want, the important part is the extension `.conf`) containing this:

``` perl
%targets = (
    "BC-32 => {
        # Borland settings go here
    }
);
```

Read the README files in `Configurations` and look through a few of the `.conf` files as examples for inspiration.  I suggest discussing on the mailing list openssl-users.

**Comment by levitte** [comment]
If you want to share the results, our [wiki](https://wiki.openssl.org) would be a good place.

**Comment by tanzislam** [comment]
The [`&&` operator in commands has a special meaning](http://docwiki.embarcadero.com/RADStudio/Sydney/en/MAKE_Rules_(Explicit_and_Implicit)_and_Commands#MAKE_Command_Operators) to the `make.exe` included in C++Builder and not passed down to the shell (even when the `-N` option is specified to emulate Microsoft NMake syntax), so [its](https://github.com/openssl/openssl/blob/master/Configurations/windows-makefile.tmpl#L32) use [cases](https://github.com/openssl/openssl/blob/master/Configurations/windows-makefile.tmpl#L706) in the [makefile](https://github.com/openssl/openssl/blob/master/Configurations/windows-makefile.tmpl#L719) [snippets](https://github.com/openssl/openssl/blob/master/Configurations/windows-makefile.tmpl#L767) in `windows-makefile.tmpl` [need](https://github.com/openssl/openssl/blob/master/Configurations/windows-makefile.tmpl#L809) to be [changed](https://github.com/openssl/openssl/blob/master/Configurations/windows-makefile.tmpl#L842) to `\n\t` or `;`.
