### ISSUE TITLE
Symlinks for manpages brake when staging

### ISSUE THREAD

**Issue by Sp1l** [openssl/openssl#15443]
@9e7a6411708702dd4ad4657636ab346382234437 adds a new way of symlinking, this breaks building when the install is not in the final destination. FreeBSD ports build/install into $WRKDIR. This change symlinks to the absolute path in $WRKDIR rather than relative symlinks in the man3 dir.

**Comment by mattcaswell** [comment]
Dupe of #15424. Will be fixed by #15437.
