### ISSUE TITLE
64-bit build of 1.0.2h fails under Windows

### ISSUE THREAD

**Issue by dbrnz** [openssl/openssl#1545]
Windows 10
Activestate Perl
VC 2014 and ml64 assembler

```
perl Configure VC-WIN64A
ms\do_win64a
nmake -f ms\ntdll.mak
```

fails when assembling `x86_64cpuid.asm` with a host of `A2071:initializer magnitude too large for specified size` errors. This apparently is not a new issue as it looks like a manifestation of https://rt.openssl.org/Ticket/Display.html?id=2963 -- applying the suggested patch to `crypto/x86_64cpuid.pl` (changing `OUT` to `FD`) certainly fixes things. 

Should this "fix" not be applied to the 1.0.2 branch? Or are these errors indicative of something else and all this is doing is patching the cracks??

**Comment by mattcaswell** [comment]
Please try using the nasm assembler instead of ml64. Nasm is now our only supported assembler.

**Comment by dbrnz** [comment]
Hmm, from `INSTALL.W64`:

> You will need Microsoft Platform SDK, available for download at
 http://www.microsoft.com/msdownload/platformsdk/sdkupdate/. As per
 April 2005 Platform SDK is equipped with Win64 compilers, as well
 as assemblers, but it might change in the future.

which is why I was using ml64.

With nasm, `ms\do_win64a` produces:
```
>perl util\mkfiles.pl  1>MINFO
>cmd /c "nasm -f win64 -v"  1>NUL 2>&1
>if 0 NEQ 0 goto ml64
>perl ms\uplink-x86_64.pl nasm  1>ms\uptable.asm
>nasm -f win64 -o ms\uptable.obj ms\uptable.asm
ms\uptable.asm:17: warning: absolute address can not be RIP-relative
ms\uptable.asm:24: warning: absolute address can not be RIP-relative
ms\uptable.asm:37: warning: absolute address can not be RIP-relative
ms\uptable.asm:44: warning: absolute address can not be RIP-relative
ms\uptable.asm:57: warning: absolute address can not be RIP-relative
ms\uptable.asm:64: warning: absolute address can not be RIP-relative
ms\uptable.asm:77: warning: absolute address can not be RIP-relative
...
```
with or without patching `crypto/x86_64cpuid.pl`.

**Comment by mattcaswell** [comment]
Looks like a problem for @dot-asm

**Comment by dot-asm** [comment]
If your nasm version is 2.12.02, then it seems to be a nasm bug. I can confirm that in this case the warning can be safely ignored, as binary generated by 2.12.02 is identical to binary generated by 2.12.01. In other words, ignore it now for 2.12.02 and we'll see how nasm evolves...

**Comment by levitte** [comment]
Not a peep after @dot-asm's comment.  I assume this is resolved.  If not, please feel free to reopen.
