### ISSUE TITLE
Add 'md-nits' to 'doc-nits'

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15459]

**Comment by richsalz** [comment]
Look at a built makefile, for example. There's an md-nits target. It depends on a ruby package, and has comments. Should be easy to integrate this into the `doc-nits` CI build.

**Comment by t8m** [comment]
I do not think we want to make the doc-nits target to depend on having installed ruby.

**Comment by t8m** [comment]
I've probably misunderstood what do you mean. If you just mean running make md-nits from the check_docs CI build, then OK.

**Comment by richsalz** [comment]
>  If you just mean running make md-nits from the check_docs CI build, then OK.

Yes, that's what I meant.  Sorry for not being clear.

**Comment by richsalz** [comment]
#15590 merged, I forgot to put the Fixes line in the commit so now I pay penance by closing this by hand. :)
