### ISSUE TITLE
Are TLS1.0 and TLS1.1 supposed to work in OpenSSL-3.0.0alpha17?

### ISSUE THREAD

**Issue by lzsiga** [openssl/openssl#15457]
Hi,
I don't wish start it as a bug-report, because it might a know issue, 3.0.0 still being in the alpha state.
Well I've compiled it on Linux, 64-bit; tests connections (s_client/s_server, httpd, wget etc) are successful. Of course those tests all use protocols TLS1.2 and TLS1.3

Then, for the sake of completeness, I tried to protocols TLS1.0 and TLS1.1 -- they didn't work, nor 3.0.0 beging the client, neither it being the server (or both). The reference was OpenSSL-1.1.1k, where these protocols work.

Error messages:
client side:
`40175207187F0000:error:0A0C0103:SSL routines:tls_process_key_exchange:internal error:ssl/statem/statem_clnt.c:2250:`

server side:
`40A7AA0E277F0000:error:0A000076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:3324:`

On server-side, I tried `SSL_CTX_set_min_proto_version(TLS1_VERSION)`, it changed nothing.

Of course it can be a configuration problem, too. I used the following options when running `Configure`:
`shared zlib no-zlib-dynamic enable-ssl3 enable-ssl3-method enable-weak-ssl-ciphers`

**Comment by mattcaswell** [comment]
This is a deliberate change.

From the migration guide:
https://www.openssl.org/docs/manmaster/man7/migration_guide.html

````
The security strength of SHA1 and MD5 based signatures in TLS has been reduced.

This results in SSL 3, TLS 1.0, TLS 1.1 and DTLS 1.0 no longer
working at the default security level of 1 and instead requires security
level 0. The security level can be changed either using the cipher string
with `@SECLEVEL`, or calling L<SSL_CTX_set_security_level(3)>. This also means
that where the signature algorithms extension is missing from a ClientHello
then the handshake will fail in TLS 1.2 at security level 1. This is because,
although this extension is optional, failing to provide one means that
OpenSSL will fallback to a default set of signature algorithms. This default
set requires the availability of SHA1.
````

**Comment by lzsiga** [comment]
Thank you very much, @mattcaswell

**Comment by t8m** [comment]
@rainerjung That's actually an interesting problem and worth a separate issue. Because this does look like a severe interoperability problem. Would you open the issue? Of course ideally it would be nice to get a dump of the DH parameters and key used for the failed connection.

**Comment by t8m** [comment]
But that will require adding a debugging output somewhere where the error is reported.
