### ISSUE TITLE
In OpenSSL3.0.0- alpha 17 API for FFC key generation 

### ISSUE THREAD

**Issue by sikkamukul** [openssl/openssl#15456]
Hi Openssl Team,
I am using openssl3.0.0-alpha 17 version
I was not able to generate key which also return Private key and Pubic key for EVP_PKEY_CTX_new_from_name(NULL, "DH", NULL);
Params I set were - OSSL_PKEY_PARAM_FFC_P, OSSL_PKEY_PARAM_FFC_Q and OSSL_PKEY_PARAM_FFC_G
EVP_PKEY_fromdata(ctx, &key, EVP_PKEY_KEYPAIR, params) 
runs successfully but when I try to get  OSSL_PKEY_PARAM_PRIV_KEY and OSSL_PKEY_PARAM_PUB_KEY params using EVP_PKEY_get_bn_param it returns null
which API should I for this test vector - 
    ```
     "algorithm": "KAS-FFC-SSC",
      "revision": "Sp800-56Ar3",
      "isSample": true,
      "testGroups": [
         {
            "p": "...",
            "q": "...",
            "g": "...",
            "tgId": 1,
            "testType": "AFT",
            "tests": [
               {
                  "ephemeralPublicServer": "...",
                  "tcId": 1
               }
            ],
            "domainParameterGenerationMode": "FC",
            "scheme": "dhEphem",
            "kasRole": "responder"
         }
    ```
or any param changes are required

**Comment by mattcaswell** [comment]
> Params I set were - OSSL_PKEY_PARAM_FFC_P, OSSL_PKEY_PARAM_FFC_Q and OSSL_PKEY_PARAM_FFC_G
EVP_PKEY_fromdata(ctx, &key, EVP_PKEY_KEYPAIR, params)
runs successfully but when I try to get OSSL_PKEY_PARAM_PRIV_KEY and OSSL_PKEY_PARAM_PUB_KEY params using EVP_PKEY_get_bn_param it returns null

Can you share the code that is failing?

Did you call `EVP_PKEY_keygen_init`/`EVP_PKEY_keygen`? You don't mention it in your question.

**Comment by sikkamukul** [comment]
```
bld = OSSL_PARAM_BLD_new();
OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_P, p);
OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_Q, q);
OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_G, g);
ctx = EVP_PKEY_CTX_new_from_name(NULL, "DH", NULL);
EVP_PKEY_fromdata_init(ctx);
params = OSSL_PARAM_BLD_to_param(bld);
EVP_PKEY_fromdata(pctx, &pkey, EVP_PKEY_KEYPAIR, params);
pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_PRIV_KEY, &Xloc->buf, &Xloc->len);
pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_PUB_KEY, &Yloc->buf , &Yloc->len);
```
```pkey_get_bn_bytes``` contains ```EVP_PKEY_get_bn_param``` to get the public and private key

**Comment by mattcaswell** [comment]
````
bld = OSSL_PARAM_BLD_new();
OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_P, p);
OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_Q, q);
OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_G, g);
ctx = EVP_PKEY_CTX_new_from_name(NULL, "DH", NULL);
EVP_PKEY_fromdata_init(ctx);
params = OSSL_PARAM_BLD_to_param(bld);
EVP_PKEY_fromdata(pctx, &pkey, EVP_PKEY_KEYPAIR, params);
````
The code above creates a "parameters only" EVP_PKEY, i.e. it holds the parameters p, q and g only. In order to get the private and public keys you actually need to generate them based on those parameters using `EVP_PKEY_keygen_init`/`EVP_PKEY_generate`.  E.g. something like this (error checking omitted for brevity):

````
    EVP_PKEY *genkey;
    EVP_PKEY_CTX *gctx = NULL;

    gctx = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, NULL);
    EVP_PKEY_keygen_init(gctx);
    EVP_PKEY_generate(gctx, &genkey);
````

**Comment by mattcaswell** [comment]
> EVP_PKEY_fromdata(pctx, &peerkey, EVP_PKEY_KEYPAIR, params_peer);

Did this line actually succeed? You should check the return value. `EVP_PKEY_KEYPAIR` looks wrong since that instructs `EVP_PKEY_fromdata` to expect parameters, a public key and a private key. You are only supplying parameters and a public key. Instead you should probably use `EVP_PKEY_PUBLIC_KEY`

**Comment by sikkamukul** [comment]
And I also noticed ```EVP_PKEY_generate(gctx, &genkey);``` is also failing for many cases

**Comment by mattcaswell** [comment]
Is there an error on the stack after the `EVP_PKEY_derive_set_peer` failure? E.g. try `ERR_print_errors_fp(stderr);`

**Comment by sikkamukul** [comment]
```
C0C2B64A847F0000:error:0280007E:Diffie-Hellman routines:generate_key:modulus too small:crypto/dh/dh_key.c:272:
C0C2B64A847F0000:error:030000A3:digital envelope routines:EVP_PKEY_get_params:invalid key:crypto/evp/p_lib.c:2328:
C0C2B64A847F0000:error:030000A3:digital envelope routines:EVP_PKEY_get_params:invalid key:crypto/evp/p_lib.c:2328:
```

**Comment by mattcaswell** [comment]
> C0C2B64A847F0000:error:0280007E:Diffie-Hellman routines:generate_key:modulus too small:crypto/dh/dh_key.c:272

Your "p" value is too small. OpenSSL will refuse to generate a DH key if the p value is less than 512 bits.

> C0C2B64A847F0000:error:1C800080:Provider routines:dh_plain_derive:missing key:providers/implementations/exchange/dh_exch.c:152:

In this case you have attempted a "derive" operation but either the key or the peer key is absent. Probably because of some earlier failure.
