### ISSUE TITLE
Undefined symbols on DragonFly BSD

### ISSUE THREAD

**Issue by zrj-rimwis** [openssl/openssl#1546]
We have some troubles compiling our dports security/openssl-devel port (v1.1.0).
Is build fix in https://github.com/DragonFlyBSD/DeltaPorts/pull/631/commits/66a12bd0463efa885944907af1dcae5246231be7#diff-6ae164c9829b908765ba46072361968fR21 correct?

Looks like rename change in cryptodev_engine_ciphers() was missed in https://github.com/openssl/openssl/commit/b61d2da71b246fbc24af0dec2b15dc49141d5990

make test passes with those changes on DragonFly.

**Comment by mattcaswell** [comment]
Yes, that build fix looks ok to me. That section seems to only be compiled if CRYPTO_AES_CTR is defined in cryptodev.h - which presumably it isn't for @benlaurie who wrote that commit.

**Comment by richsalz** [comment]
+1 if you want to merge that fix, @mattcaswell.

**Comment by mattcaswell** [comment]
To be clear that would be for master and 1.1.0

**Comment by richsalz** [comment]
Yes +1 for both

**Comment by richsalz** [comment]
@mattcaswell want me to merge the fix?

**Comment by mattcaswell** [comment]
Yes please!

**Comment by richsalz** [comment]
Please see https://github.com/openssl/openssl/pull/1584

**Comment by richsalz** [comment]
dragonfly was NOT done, that's a separate issue -- please make a PR.
The compile-time function names were fixed in master and 1.1.0

**Comment by jrmarino** [comment]
hello @richsalz and @mattcaswell , I have opened a separate PR #1765 for the DragonFly macros as Github apparently noticed.
