### ISSUE TITLE
Compilation with strict warnings fails on GCC 11

### ISSUE THREAD

**Issue by juergenchrist** [openssl/openssl#15462]
When compiling master OpenSSL with GCC 11 and strict warnings, compilation fails due to a warning.

Configuration:
```
./config --strict-warnings enable-asan enable-ubsan enable-zlib-dynamic enable-unit-test enable-md2 enable-rc5 enable-buildtest-c++ enable-weak-ssl-ciphers enable-ssl3 enable-ssl3-method -w
```
Warning:
```
ssl/s3_cbc.c: In function 'ssl3_cbc_digest_record':
ssl/s3_cbc.c:404:13: error: 'memcpy' offset [64, 128] is out of the bounds [0, 13] [-Werror=array-bounds]
  404 |             memcpy(first_block, header + md_block_size, overhang);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
GCC version:
```
# gcc --version
gcc (GCC) 11.0.1 20210324 (Red Hat 11.0.1-0)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Since `header` is defined as an array of 13 bytes, adding `md_block_size` which is larger than 13 bytes seems wrong.  Not sure how to fix that.

**Comment by t8m** [comment]
I suppose the argument in the function prototype should be just changed to a pointer.

**Comment by juergenchrist** [comment]
From what I found digging further into this I can say that the pointer is 13 bytes if the last parameter (`sslv3`) is 0 and more otherwise.  So I agree.  PR coming up...
