### ISSUE TITLE
Some CI builds are too slow

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#15475]
The following five builds exceed the desired 15 minute run time for CIs:
1. Windows GitHub CI / shared (win32) Successful in 37m 
1. Windows GitHub CI / shared (win64) Successful in 24m 
1. CIFuzz / Fuzzing Successful in 20m 
1. Windows GitHub CI / plain Successful in 17m 
1. GitHub CI / non-caching Successful in 17m 

The first two or three are well over.

**Comment by t8m** [comment]
On the other hand without Windows CI on PRs we are getting constant regressions. I would say we could perhaps drop some tests from the shared builds if we can identify some that are slow and unlikely to get broken only on Windows.

**Comment by levitte** [comment]
I would say that if you want to drop tests for speed reasons, then you need to review your priorities

**Comment by t8m** [comment]
> But then, we might also want to review what tests should be run for every PR, and what tests only need to be done on a daily basis (or some other regular unit of time)

I would not recommend dropping any of these except of CIFuzz from the set of tests run for every PR. All these find regressions regularly and fixing them post-merge is always harder and with more overhead than when catching the issue before the PR is merged.

**Comment by paulidale** [comment]
I don't have a problem relegating CIFuzz to one of the less often run suites.  It's not the bottleneck here, so I'd be tempted to keep it.  At least until the even slower tests are addressed.

I do agree the others find errors too often to be dropped.

Are alternate Windows tests possible?  They aren't all this slow.  We could also look into reducing the test suite coverage.

**Comment by paulidale** [comment]
Closing this as it doesn't seem very relevant.  So CIs are slow but they aren't impacting negatively.
