### ISSUE TITLE
ACVP-AES-CCM when plaintext input length is zero OpenSSl 3.0.0 Alpha 17  

### ISSUE THREAD

**Issue by sikkamukul** [openssl/openssl#15482]
Hi Openssl team,
I was trying to obtain ciphertext for ```"algorithm": "ACVP-AES-CCM"``` for case where plaintext length  is 0

```
            "testType": "AFT",
            "direction": "encrypt",
            "keyLen": 128,
            "ivLen": 104,
            "payloadLen": 0,
            "aadLen": 256,
            "tagLen": 128,
            "tests": [
               {
                  "tcId": 994,
                  "pt": "",
                  "key": "...",
                  "aad": "...",
                  "iv": "..."
               }
```
I attempted with code -
``` 
ctx = EVP_CIPHER_CTX_new();
EVP_CipherInit_ex(ctx, cipher, NULL, NULL, NULL,1);
EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_IVLEN, iv_len, NULL);
EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, tag_len, NULL);
EVP_CipherInit_ex(ctx, NULL, NULL, key_buf, iv_buf,1);
EVP_CipherUpdate(ctx, NULL, &len, NULL, data_len);
EVP_CipherUpdate(ctx, NULL, &len , aad.buf, aad.len);
EVP_CipherUpdate(ctx, out, &len, data_buf, data_len);
EVP_EncryptFinal_ex(ctx, out + len, &len);
EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_GET_TAG, tag_len, tag_buf);
```
the code never fails at any point except last and shows error-
```
error:1C800077:Provider routines:ossl_ccm_get_ctx_params:tag not set:providers/implementations/ciphers/ciphercommon_ccm.c:206:
```
for other cases where plaintext is not null it's working fine except for case where plaintext is null

**Comment by slontis** [comment]
Tried it locally and I got a tag back using tests/acvp_test.c if I set the pt_len to zero..
i.e. Do not pass it a NULL pt buffer as that will not work.. That is equivalent to calling the final which skips lots of code and
does not set the tag.. Pass a dummy buffer with a pt_len of 0 instead.
Also remember that this whole interface is horrible with lots of hidden meanings when you pass certain values as NULL..
i.e- setting the pt_len and the aad.
