### ISSUE TITLE
SSL_CTX_use_PrivateKey() fails to report mismatch with certificate

### ISSUE THREAD

**Issue by dwmw2** [openssl/openssl#1549]
Quoth the man page:

```
       SSL_CTX_use_PrivateKey() adds pkey as private key to ctx.
       SSL_CTX_use_RSAPrivateKey() adds the private key rsa of type RSA to
       ctx. SSL_use_PrivateKey() adds pkey as private key to ssl;
       SSL_use_RSAPrivateKey() adds rsa as private key of type RSA to ssl.  If
       a certificate has already been set and the private does not belong to
       the certificate an error is returned. To change a certificate, private
       key pair the new certificate needs to be set with SSL_use_certificate()
       or SSL_CTX_use_certificate() before setting the private key with
       SSL_CTX_use_PrivateKey() or SSL_use_PrivateKey().
```

So if I add a certificate, and a private key that doesn't belong to the certificate, I'm supposed to get an error. Simple... 

Except it doesn't seem to work like that. My torture test suite contains RSA, DSA and EC keys (and certs). If I load one cert and a _different_ key, it seems to silently accept that, then just neglect to do any client cert auth on the wire without ever telling me.

**Comment by dwmw2** [comment]
It looks like applications need to explicitly call `SSL_CTX_check_private_key()` to check for the classes of mismatch which `SSL_CTX_use_PrivateKey()` *doesn't* report, if they want to behave well and report errors coherently to their users? Fixed in my application [thus](http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/4a991d3a299) but the documentation still wants fixing.

**Comment by richsalz** [comment]
This is not a new bug in 1.1.1, so removing that milestone.

**Comment by erbsland-dev** [comment]
@t8m In the current `master` branch, this seems to work as expected—the public key part is correctly compared with the one from the certificate. Additionally, the documentation accurately reflects the actual behavior of the function calls. Either I’m missing something, or this issue is now obsolete.

**Comment by t8m** [comment]
Yeah, I am closing this now.
