### ISSUE TITLE
Encoders and decoders implementations should be possible to filter using their properties

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#15500]
The current way to select among the multitude of encoder and decoder implementations is done by getting a set of implementation level params (OSSL_PARAM entries).

However, these are duplicates of properties assigned to these implementations, for technical reasons (we currently don't have a way to query property definition values).  It would be much better (and most of all, kinder to those implementing decoders) if this duplication wasn't necessary...  it's also likely that querying property values is faster than getting params.

Related to #14217

**Comment by t8m** [comment]
Moving to beta1 milestone as that most probably requires API change to query property values.

**Comment by levitte** [comment]
Internal API addition only, as far as I can tell

**Comment by t8m** [comment]
Hmm, wouldn't querying properties of an implementation be a useful API call for public consumption?

**Comment by levitte** [comment]
Our property API is entirely internal. Not sure that I see a public use for it

**Comment by t8m** [comment]
Should this be closed now as #15570 is merged?

**Comment by levitte** [comment]
Er, yes.  I thought that would happen automatically...  I probably forgot to add "Fixes #15500" in that PR.
