### ISSUE TITLE
FIPS derxxx.h.in in wrong directory

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15506]
Files like `der_digests.h.in` are in `providers/common/der`.  For every other `.in` file in OpenSSL (all 130 of them), they exist in the same directory where the target file exists.  There is no reason this should be otherwise.

**Comment by levitte** [comment]
The files in `providers/common/der` is a set that belongs together.  Contrary to you, I don't think it matters very much if the generated files end up in the same directory or elsewhere.

**Comment by paulidale** [comment]
These caused pain in the check-summing script....

**Comment by levitte** [comment]
Aha, that...  I'll have a look, `configdata.pm`'s `--query` should certainly be able to make that much easier

**Comment by levitte** [comment]
Yup, wasn't so hard.  All that was needed was to *stop guessing* and use the available database instead.  See #15514

**Comment by levitte** [comment]
I believe that with #15514, this can be closed?

**Comment by richsalz** [comment]
just move the darn files.  sigh.  openssl source is viewed by many more people, and maintained, than just the under a dozen active developers here on this project.

**Comment by levitte** [comment]
Something I did discover, though, is that those generated files don't contain the usual autowarn text.

**Comment by richsalz** [comment]
The point of this issue is that "foo.h.in" should be in the same directory as "foo.h"  Just like everything else "*.in" is in the same directory as the generated "*"

The missing autowarn text is a bug, of course :)

**Comment by paulidale** [comment]
I'm with @richsalz here, we should move the generated headers.  Leave the generated C files since they are in the right place.  I don't care where the .asn1 files but a comment should be included giving their location for files not in the same directory.

**Comment by levitte** [comment]
> There is more than checksumming scripts involved here.

Do tell.

Me, I'm looking at it pragmatically (and in that respect, I find "I don't care where the .asn1 files" a bit flippant).
Right now, all build.info instructions to generate those files are in one place.  Do you suggest spreading that around? Just to show what I'm talking about:

https://github.com/openssl/openssl/blob/43dbe3b72de0ba4ebd20e9e6a2c526ef747326ab/providers/common/der/build.info#L1-L10

These all go together in my view.  What you suggest is splitting them up and spreading that to different locations.

**Comment by levitte** [comment]
Side note:  Thinking the other way around, I would have no issues whatsoever moving, for example, `include/openssl/x509.h.in` to `crypto/x509`, and only have the generated `x509.h` in `include/openssl`.

**Comment by richsalz** [comment]
There is no need to move the quoted `build.info` instructions, you could just use a variable for the header file is you want.  Or move them up a level like doc/build.info for the man1 pages.

The number of people who will look at `build.info` is much lower than the number of people who will look at `.in.h` and `.h` files.

I do not understand why you're so insistent.  We're just asking that `foo.h.in` be *right next to* `foo.h` because that will be most obvious to an external openssl developer/user, and it is consistent.  I am sorry that those arguments fall on deaf ears, or that you think the clarity of the `build.info` files is more important.

**Comment by levitte** [comment]
> I do not understand why you're so insistent.

Because I view these files are a related set: der_digests_gen.c.in, der_digests.h.in, NIST.asn1, DIGESTS.asn1
So while you're claiming that der_digests.h.in should be *right next to* der_digests.h, I claim that it should be *right next to* the set it's related with.
I only brought up the build.info file because that's where the set mentality is most visible.

Different viewpoints.

Speaking of insistence, I'm just as stumped by yours.

**Comment by richsalz** [comment]
> So while you're claiming that der_digests.h.in should be right next to der_digests.h, I claim that it should be right next to the set it's related with.

Why?  There is nothing in that `.in` file but an invocation to an external function.  If `der_digests.h.in` should be with the related set, why not `der_digests.h`? 

I'm insistent because I am trying to make my point.  If you feel you understood what I am saying, and disagree, oh well. I'll stop.

**Comment by paulidale** [comment]
What @richsalz wrote:

> The number of people who will look at `build.info` is much lower than the number of people who will look at `.in.h` and `.h` files.

I'm one of these people.  Perhaps I'm being naïve to believe that I've some experience with OpenSSL.

**Comment by t-j-h** [comment]
@levitte the .in files should be in the same place as the output files in general - and what they depend on if not used elsewhere should be with them. If that means we have some copied logic in build.info that doesn't alter that we should be placing things where people would naturally expect to find them. I agree with both @paulidale and @richsalz that these seem to be the odd ones out at not logical - and your arguments don't really make sense to me - unless you placed the output files in that same location (which wouldn't be a logical outcome either). 

The related-to-sets-proximity is a much weaker argument than simplicity and clarity and also a much less clear "rule" to follow.

And yes - they should have the auto-generated warning comments too.

My view would be entirely different if all the .in files were grouped together somewhere else - but they aren't.

**Comment by levitte** [comment]
I will continue to disagree with what's said here, but am not going to oppose a PR
