### ISSUE TITLE
inconsistent enforcement of keygen size

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#15502]
PR #15472 put a maximum size of generated keys.  This is wrong, it should only be enforced in FIPS mode which has requirements.  OpenSSL is a toolkit and someone might want/need to generate long keys, perhaps *not for production use.*

I point out that there is no similar enforcement of mimimum size:
```
; ./apps/openssl genpkey -algorithm rsa -pkeyopt rsa_keygen_bits:512
```
(Yes, under 512 is not supported.  But 512 is stupid weak these days.)

**Comment by paulidale** [comment]
This isn't a FIPS requirement.
Having a circumvention mechanism might be prudent.

**Comment by paulidale** [comment]
It would be straightforward to modify the `RAND_bytes_ex()` and `RAND_priv_bytes()` to take a strength argument which is passed through to the underlying RNG to get universal enforcement.

Adding a strength argument to these calls might be prudent even if the underlying changes don't happen.

**Comment by paulidale** [comment]
OTC resolution: make the check FIPS only for the moment.
