### ISSUE TITLE
Do provider ciphers need a gettable for the EVP_CIPH_RAND_KEY flag?

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#15531]
When documenting the cipher flags I noticed EVP_CIPH_RAND_KEY is used here:

````
int EVP_CIPHER_CTX_rand_key(EVP_CIPHER_CTX *ctx, unsigned char *key)
{
    if (ctx->cipher->flags & EVP_CIPH_RAND_KEY)
        return EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_RAND_KEY, 0, key);)
   ...
}
````

For des and des3 this flag is set by the legacy code...
Since the providers dont return this flag this path never runs.

i.e the random key may not be odd parity. Is this a problem??

evp_cipher_cache_constants() would need to handle an additional param if this is needed.

**Comment by slontis** [comment]
EVP_EncryptInit.pod will need to updating also

**Comment by t8m** [comment]
IMO this should be fixed somehow. In theory there might be 3rd party provided ciphers that require a special key generation.

**Comment by slontis** [comment]
Ok will do.

**Comment by t8m** [comment]
I wonder if just calling the CTRL unconditionally and do the RAND_bytes() as fallback if the CTRL fails would be OK.

**Comment by slontis** [comment]
That would break the legacy case..

**Comment by slontis** [comment]
The 111 code is this..
````
int EVP_CIPHER_CTX_rand_key(EVP_CIPHER_CTX *ctx, unsigned char *key)
{
    if (ctx->cipher->flags & EVP_CIPH_RAND_KEY)
        return EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_RAND_KEY, 0, key);
    if (RAND_priv_bytes(key, ctx->key_len) <= 0)
        return 0;
    return 1;
}
````

**Comment by paulidale** [comment]
@slontis, are you going to be working on this?

**Comment by slontis** [comment]
yep - see the assignment..
