### ISSUE TITLE
In openssl-alpha17 release, symlinks of man/man* are introduced which are giving packaging issues

### ISSUE THREAD

**Issue by satya-rajesh** [openssl/openssl#15541]
Issue not observed with openssl-3.0.0-alpha16.

While building openssl-3.0.0-alpha17, packaging issues are observed for docs, man/man1, man/man3, man/man7 etc as there are symbolic links introduced.

errors:
.
.
.

    Symlink points to BuildRoot: /usr/share/man/man1/asn1parse.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/c_rehash.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-rehash.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/ca.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/ciphers.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/cms.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/crl.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/crl2pkcs7.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/dgst.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/dhparam.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
    Symlink points to BuildRoot: /usr/share/man/man1/dsa.1ssl.gz -> /usr/src/photon/BUILDROOT/openssl-3.0.0-alpha17.1.ph4.x86_64/usr/share/man/man1/openssl-cmds.1ssl.gz
.
..
..

Request to fix this by removing the symlinks.

**Comment by paulidale** [comment]
Does #15437 fix the problem?

Removing the symbolic links isn't going to happen.  They do need to be relative.

**Comment by levitte** [comment]
Something to be noted is that OpenSSL 1.1.1 symlinks manpages...  but they are relative symlinks, so unless 1.1.1 has been problematic because of this (I would be surprised, since that was never reported), #15437 should indeed make the problem go away.

**Comment by satya-rajesh** [comment]
pulled the patch from #15437 and it seems to have worked. Thanks @paulidale & @levitte
