### ISSUE TITLE
OSSL_PKEY_PARAM_EC_PUB_X and OSSL_PKEY_PARAM_EC_PUB_Y are not documented

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15548]
I presume they can be used when creating an EC EVP_PKEY from params.

**Comment by romen** [comment]
I am still not entirely sure this was a great choice... I understand the convenience for the FIPS tests, but I would stick to the SECG standards and use points encoding.
Supporting both the standard points encoding and the convenience X and Y complicates things uselessly for provider authors, and is prone to breaking given that X and Y representations are custom and might break things in the future if standards evolve to include more information in the point encoding (e.g. @beldmit and I discussed some presentation at a recent IETF meting that would speedup ECC applications by embedding some extra knowledge in the point encoding)

**Comment by beldmit** [comment]
Well. I got some experience today to create EVP_PKEY from x, y, and curve, and don't like API :)

**Comment by t8m** [comment]
OTC: too late before beta for making these settable. These should be just documented.

**Comment by slontis** [comment]
> I presume they can be used when creating an EC EVP_PKEY from params.

No they are only gettable currently.
acvp_test.c has an example of inserting a public key using the 04||X||Y format.

Making them settable would be a bit tricky currently as the code is shared between many different things..
The code would have to be reworked if there are multiple ways of setting the public key (i.e the code for export would need to be different).
