### ISSUE TITLE
The implementation of AES

### ISSUE THREAD

**Issue by Natruel** [openssl/openssl#15547]
### openssl 1.1.1
I want to know the whole functions call trace about the algorithm, such AES、SM4. But when i planned to know that about the AES,i found that, unlike SM4, the implementation of AES seems that it did't need the file, such as aes_core.c、aes_cbc.c and so on(under the directory ./crypto/aes/......). Because after i rewrote the functions defined by the aes_core.c and recompiled the openssl, it seems that openssl still implement the AES just like nothing happening. But when i do the same thing for the sm4.c(under the directory ./crypto/sm4) , the implementation of SM4 indeed changed. 
So i want to know whether the implenmantation of AES need the .c files under the directory ./crypto/aes/...... or not?

**Comment by paulidale** [comment]
Look in `crypto/aes/asm` for the assembly code implementations.  The C versions are only used if OpenSSL is configured `no-asm` or the low level functions are called directly.

**Comment by Natruel** [comment]
Thank you for solving my problem!
