### ISSUE TITLE
Any configuration to enable deprecated APIs (when migrating from openssl 1.1.1 to openssl 3.0.0) for compatibility of dependent packages

### ISSUE THREAD

**Issue by satya-rajesh** [openssl/openssl#15542]
Hi Openssl team,

I would like to migrate from openssl 1.1.1 to openssl 3.0.0. To make the process smooth, is there any way to enable openssl 1.1.1 deprecated API's for openssl 3.0.0.

The reason for the question is, due to deprecated APIs, lot of other packages are failing for which there is no official support yet. 
Once there is official support, i shall start upgrading the packages with openssl 3.0.0 support, but it seems a long way to go.

For example:
nginx - Failed due to ENGINE_*, HMAC_* APIs are deprecated
rabbitmq - undefined symbol: FIPS_mode - deprecated
tpm2-tools - RSA_*, HMAC_*, EC_*, ECDH_* deprecated APIs

and so on....

Please suggest.

**Comment by paulidale** [comment]
All OpenSSL 1.1.1 APIs are present in OpenSSL 3.0 unless the `no-deprecated` option is used to configure OpenSSL 3.0.

You might get compiler warnings for using deprecated functions but these can generally be turned off.

**Comment by levitte** [comment]
I suppose you want to get rid of that specific warning. The way to do this is to add an appropriate compiler option to your configuration.  With gcc and clang, that's `-Wno-deprecated`.

**Comment by paulidale** [comment]
Answered, closing.
