### ISSUE TITLE
Pod file links causing build error on windows x64_icl14..

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#15543]
Errors are of the form:

"C:\strawberry-perl-5.14.4.1-64bit-portable\perl\bin\perl.exe" "../util/mkpod2html.pl" -i "..\doc\man1\CA.pl.pod" -o doc\html\man1\CA.pl.html -t "CA.pl" -r "../doc"
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl(1)> in paragraph 11.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl(1)> in paragraph 12.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl(1)> in paragraph 12.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-req(1)> in paragraph 22.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-req(1)> in paragraph 24.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-req(1)> in paragraph 26.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-req(1)> in paragraph 28.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-ca(1)> in paragraph 28.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-ca(1)> in paragraph 33.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-ca(1)> in paragraph 35.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-x509(1)> in paragraph 37.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-ca(1)> in paragraph 37.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-ca(1)> in paragraph 39.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-ca(1)> in paragraph 41.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl(1)> in paragraph 45.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-req(1)> in paragraph 45.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl(1)> in paragraph 56.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-x509(1)> in paragraph 56.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-ca(1)> in paragraph 56.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<openssl-req(1)> in paragraph 56.
../util/mkpod2html.pl: ..\doc\man1\CA.pl.pod: cannot resolve L<config(5)> in paragraph 56.
	"C:\strawberry-perl-5.14.4.1-64bit-portable\perl\bin\perl.exe" "-I." "-I..\doc" -Mconfigdata -Mperlvars "..\util\dofile.pl" "-omakefile" "..\doc\man1\openssl-asn1parse.pod.in" > doc\man1\openssl-asn1parse.pod

I suspect Commit id 0e7e3b9b9d2d0a49097b4e224098036d3e6b8087
It worked 5 days ago, so it is a recent change.

Build Config:
perl C:\jenkins\workspace\openssl-windows_x64_icl14\Configure --prefix=C:\jenkins\workspace\openssl-windows_x64_icl14/install-win enable-trace no-asm --openssldir=ssl VC-WIN64A

Command line (with current working directory = .):

    C:\strawberry-perl-5.14.4.1-64bit-portable\perl\bin\perl.exe ..\Configure --prefix=C:\jenkins\workspace\openssl-windows_x64_icl14/install-win enable-trace no-asm --openssldir=ssl VC-WIN64A

Perl information:

    C:\strawberry-perl-5.14.4.1-64bit-portable\perl\bin\perl.exe
    5.14.4 for MSWin32-x64-multi-thread

Enabled features:

    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    idea
    legacy
    loadereng
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    trace
    ts
    ui-console
    uplink
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    acvp-tests          [default]   OPENSSL_NO_ACVP_TESTS
    afalgeng            [not-linux] OPENSSL_NO_AFALGENG
    asan                [default]   OPENSSL_NO_ASAN
    asm                 [option]    OPENSSL_NO_ASM
    buildtest-c++       [default]   
    crypto-mdebug       [default]   OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]   OPENSSL_NO_EGD
    external-tests      [default]   OPENSSL_NO_EXTERNAL_TESTS
    fips                [default]   
    fips-securitychecks [cascade]   OPENSSL_NO_FIPS_SECURITYCHECKS
    fuzz-afl            [default]   OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [default]   OPENSSL_NO_KTLS
    md2                 [default]   OPENSSL_NO_MD2 (skip crypto\md2)
    msan                [default]   OPENSSL_NO_MSAN
    rc5                 [default]   OPENSSL_NO_RC5 (skip crypto\rc5)
    sctp                [default]   OPENSSL_NO_SCTP
    ssl-trace           [default]   OPENSSL_NO_SSL_TRACE
    ubsan               [default]   OPENSSL_NO_UBSAN
    unit-test           [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers    [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]   
    zlib-dynamic        [default]   
    ssl3                [default]   OPENSSL_NO_SSL3
    ssl3-method         [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "lib",
    ARFLAGS => "/nologo",
    AS => "ml64",
    ASFLAGS => "/nologo /Zi",
    CC => "cl",
    CFLAGS => "/W3 /wd4090 /nologo /O2",
    CPP => "\"\$(CC)\" /EP /C",
    HASHBANGPERL => "/usr/bin/env perl",
    LD => "link",
    LDFLAGS => "/nologo /debug",
    MT => "mt",
    MTFLAGS => "-nologo",
    RANLIB => "CODE(0x2bd1b18)",
    RC => "rc",
    ar_resp_delim => "
",
    aroutflag => "/out:",
    asflags => "/c /Cp /Cx",
    asm_arch => "x86_64",
    asoutflag => "/Fo",
    bin_cflags => "/Zi /Fdapp.pdb",
    bin_lflags => "setargv.obj /subsystem:console /opt:ref",
    bn_ops => "SIXTY_FOUR_BIT",
    build_file => "makefile",
    build_scheme => [ "unified", "windows", "VC-common" ],
    cflags => "/Gs0 /GF /Gy /MD",
    coutflag => "/Fo",
    cppflags => "",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "OPENSSL_SYS_WIN32", "WIN32_LEAN_AND_MEAN", "UNICODE", "_UNICODE", "_CRT_SECURE_NO_DEPRECATE", "_WINSOCK_DEPRECATED_NO_WARNINGS" ],
    disable => [  ],
    dso_cflags => "/Zi /Fddso.pdb",
    dso_scheme => "win32",
    enable => [  ],
    ex_libs => "ws2_32.lib gdi32.lib advapi32.lib crypt32.lib user32.lib",
    includes => [  ],
    ld_implib_flag => "/implib:",
    ld_resp_delim => "
",
    lddefflag => "/def:",
    ldoutflag => "/out:",
    ldpostoutflag => "",
    ldresflag => " ",
    lflags => "",
    lib_cflags => "/Zi /Fdossl_static.pdb",
    lib_cppflags => "",
    lib_defines => [ "L_ENDIAN" ],
    makedep_scheme => "VC",
    makedepcmd => "\"\$(CC)\" /Zs /showIncludes",
    module_cflags => "",
    module_cxxflags => undef,
    module_ldflags => "/dll",
    mtinflag => "-manifest ",
    mtoutflag => "-outputresource:",
    multilib => "-x64",
    perl_platform => "Windows::MSVC",
    perlasm_scheme => "auto",
    rcoutflag => "/fo",
    shared_cflag => "",
    shared_defflag => "",
    shared_defines => [  ],
    shared_ldflag => "/dll",
    shared_rcflag => "",
    shared_target => "win-shared",
    sys_id => "WIN64A",
    thread_defines => [  ],
    thread_scheme => "winthreads",
    unistd => "<unistd.h>",
    uplink_arch => "x86_64",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = icl
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = lib
    ARFLAGS         = /nologo
    AS              = ml64
    ASFLAGS         = /nologo /Zi
    CC              = icl
    CFLAGS          = /W3 /wd4090 /nologo /O2
    CPP             = "$(CC)" /EP /C
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LD              = link
    LDFLAGS         = /nologo /debug
    LDLIBS          = 
    MT              = mt
    MTFLAGS         = -nologo
    PERL            = C:\strawberry-perl-5.14.4.1-64bit-portable\perl\bin\perl.exe
    RANLIB          = ranlib
    RC              = rc
    RCFLAGS         =

**Comment by levitte** [comment]
Why would anything in `util/find-doc-nits` make `util/mkpod2html.pl` fail?????

I suspect that, because dependency specs are lacking, the POD files to be generated haven't yet...  and as a matter of fact, the line at the end of your log demonstrates exactly this:

> ```
> "C:\strawberry-perl-5.14.4.1-64bit-portable\perl\bin\perl.exe" "-I." "-I..\doc" -Mconfigdata -Mperlvars "..\util\dofile.pl" "-omakefile" "..\doc\man1\openssl-asn1parse.pod.in" > doc\man1\openssl-asn1parse.pod
> ```

If CA.pl.pod would have had a `L<openssl-asn1parse(1)>` somewhere, you would have seen a complaint about that too.

The quick fix is to add a dependency on `build_generated_pods` somewhere.
The not quite as quick fix is to add dependencies manually in doc/build.info (and oh boy maintenance issue!)
The more difficult fix is to do something similar to the automatic dependency generation, by parsing all POD files for any of those that are generated and place those dependency specs in appropriate .d files.

**Comment by slontis** [comment]
There were alot of complaints - that was just the first one..
The question is why is this problem newly introduced? (i.e it has broken in the last 5 days).

**Comment by paulidale** [comment]
I'm guessing this isn't related to the AppVeyor failure: https://ci.appveyor.com/project/openssl/openssl/builds/39388894/job/4e51ipp4jgqrhgbh

**Comment by levitte** [comment]
@slontis,can you confirm that `make build_generated_pods` first fixes the problem?

**Comment by slontis** [comment]
Should this already be doing this? Makefile.in contains

doc-nits: build_generated_pods
	$(PERL) $(SRCDIR)/util/find-doc-nits -c -n -l -e

**Comment by slontis** [comment]
Hmm - The problem seemed to disappear when I rebuilt.. Will close this for now.

**Comment by levitte** [comment]
Of course the problem went away after the first build...  at that point, all pods to be generated are actually generated.
