### ISSUE TITLE
openssl version redirect to a file

### ISSUE THREAD

**Issue by jack-tan2** [openssl/openssl#15549]
I want to know my openssl's version info, so i use the command `openssl version` , but the output of the command can't redirect to a file, it means when i use the `openssl version > ./test.txt`，the screen still output the info, and the `test.txt` is empty, so how can i deal with this question

**Comment by t8m** [comment]
Which version of openssl are you talking about here? The `openssl version` command as of the current OpenSSL versions should print out the version information to the standard output so it should be redirectable with `>` just fine.

**Comment by jack-tan2** [comment]
the openssl's version is openssl 1.1.1-stable，now i solve the problem, if the file you want to redirect doesn't exist, the command `openssl version` will still print out to the standard output, and if file was created before, the  `openssl version` will redirect successfully, thank you

**Comment by levitte** [comment]
That explanation made no sense at all.  With redirection, the file gets created if it doesn't already exist.

**Comment by paulidale** [comment]
Output redirection isn't a property of OpenSSL, it's a property of the command line shell you're using.
For me on Linux with bash, the redirected file is created fine.

**Comment by jack-tan2** [comment]
> That explanation made no sense at all. With redirection, the file gets created if it doesn't already exist.

you can try, for command `openssl version`, the redirection can't happen if the file doesn't already exits

**Comment by t8m** [comment]
> you can try, for command `openssl version`, the redirection can't happen if the file doesn't already exits

That would be a bug of the shell you're using, not of OpenSSL.

**Comment by paulidale** [comment]
Answered, closing.
