### ISSUE TITLE
Seems something changed in openssl-3.0.0-alpha17 related to SHA1, SHA256, SHA384, SHA512 which makes some packages fail 

### ISSUE THREAD

**Issue by satya-rajesh** [openssl/openssl#15553]
It works when compiled against openssl-3.0.0-alpha16.

However it fails with openssl-3.0.0-alpha17.

lib/tpm2_openssl.c: In function 'tpm2_openssl_halg_to_digester':
lib/tpm2_openssl.c:358:16: error: 'SHA1' undeclared (first use in this function)
  358 |         return SHA1;
      |                ^~~~
lib/tpm2_openssl.c:358:16: note: each undeclared identifier is reported only once for each function it appears in
lib/tpm2_openssl.c:360:16: error: 'SHA256' undeclared (first use in this function); did you mean 'SHA256_CTX'?
  360 |         return SHA256;
      |                ^~~~~~
      |                SHA256_CTX
lib/tpm2_openssl.c:362:16: error: 'SHA384' undeclared (first use in this function)
  362 |         return SHA384;
      |                ^~~~~~
lib/tpm2_openssl.c:364:16: error: 'SHA512' undeclared (first use in this function); did you mean 'SHA512_CTX'?
  364 |         return SHA512;
      |                ^~~~~~
      |                SHA512_CTX
  CC       tools/tpm2_setprimarypolicy.o
  CC       tools/tpm2_createprimary.o
make: *** [Makefile:4845: lib/lib_libcommon_a-tpm2_openssl.o] Error 1
make: *** Waiting for unfinished jobs....
  CC       tools/tpm2_dictionarylockout.o
error: Bad exit status from /var/tmp/rpm-tmp.dMTf5n (%build)

Kindly suggest as to what changed from alpha16 to alpha17 and seems not an expected behavior.

**Comment by paulidale** [comment]
These were changes to macros I believe.  #include <openssl/sha.h> ?

**Comment by slontis** [comment]
e.g
````
# define SHA256(d, n, md) \
    (EVP_Q_digest(NULL, "SHA256", NULL, d, n, md, NULL) ? md : NULL)
````
The nicest way to fix this would be to return a string instead.

e.g return "SHA256";

And then in the place where you use it, call EVP_Q_digest

**Comment by satya-rajesh** [comment]
> string

Any sample code i can refer to fix this ?

**Comment by paulidale** [comment]
```c
int sha256(const void *d, size_t n, unsigned char *md) {
    return SHA256(d, n, md);
}
```

**Comment by slontis** [comment]
Not really.. return the algorithm name..
At the place where the returned function was getting called it already passed 3 parameters.. At that point
Replace the function call with EVP_Q_digest(d, n, md)

**Comment by slontis** [comment]
Or do what pauli just suggested..

**Comment by levitte** [comment]
@satya-rajesh, I suggest you have  a talk with the folks at https://github.com/tpm2-software/tpm2-openssl.
(or maybe @gotthardp is paying attention already? :wink:)

**Comment by gotthardp** [comment]
@satya-rajesh, there is nothing wrong with openssl. You are trying to build tpm2-tools, which (heavily) use the deprecated API functions, so one cannot build it against openssl 3 yet. You did report this on March 4 https://github.com/tpm2-software/tpm2-tools/issues/2354, so the team is aware of this.
