### ISSUE TITLE
EVP_DigestSignInit potential regression

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15556]
Legacy code automatically sets the default digest when the passed digest is null.
https://github.com/openssl/openssl/blob/f7c1b472bf0a790b9c87e1c87e48897d6413ec45/crypto/evp/m_sigver.c#L240-L252

For provided code we look at mdname which is NULL when called from EVP_DigestSignInit.

It may cause a regression if there are no similar processing in the providers.

**Comment by levitte** [comment]
Not sure I understand the issue.  Are you saying that we have providers that do not answer to the OSSL_PKEY_PARAM_DEFAULT_DIGEST or OSSL_PKEY_PARAM_MANDATORY_DIGEST parameters, but that should?

**Comment by beldmit** [comment]
@levitte I want to be sure that they answer respond the same way which they answered in 1.1.1

**Comment by levitte** [comment]
``` console
$ git grep -l -E '(OSSL_PKEY_PARAM_DEFAULT_DIGEST|OSSL_PKEY_PARAM_MANDATORY_DIGEST)'
crypto/evp/keymgmt_lib.c
doc/man7/EVP_PKEY-X25519.pod
include/openssl/core_names.h
providers/implementations/keymgmt/dsa_kmgmt.c
providers/implementations/keymgmt/ec_kmgmt.c
providers/implementations/keymgmt/ecx_kmgmt.c
providers/implementations/keymgmt/rsa_kmgmt.c
```

Is that enough of an answer for you?

**Comment by levitte** [comment]
As far as I recall, they should answer in a similar enough manner.

**Comment by beldmit** [comment]
Thanks!
