### ISSUE TITLE
What is the purpose of this dtls code? I don't find where it's used.

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#15559]
https://github.com/openssl/openssl/blob/28cab20916731c188180628330de27f6ce5f684e/ssl/ssl_local.h#L1862-L1866
https://github.com/openssl/openssl/blob/28cab20916731c188180628330de27f6ce5f684e/ssl/d1_lib.c#L406-L409

**Comment by kaduk** [comment]
Looks like it's been dead code even as of the original DTLS import (36d16f8ee0845d932e250286e8e236580470e35b) -- there used to be a local `send_alert` that was set when `DTLS1_TMO_READ_COUNT` was hit, but the only use of `send_alert` was commented out.
