### ISSUE TITLE
Openssl-3.0 - hashZ generation for ECDH is failing(Result not matching) for all curves

### ISSUE THREAD

**Issue by banvikas** [openssl/openssl#15555]
Hi Openssl team,

Below is the Test-Vector used:
{
"ephemeralPublicServerX": "077BF40C364599E82F546E9415269EACC5D5BC66572BB684F1F933F9C0D73DAEB01BB52F",
"ephemeralPublicServerY": "05F26053EB4877563D273C1DCC8416DE6A65B3E46A4D7B8B36AC20B78E6ECFAAFBEC4D4B",
"ephemeralPrivateIut": "017DCF9BB9E7A36C35D60456BF476F710B4FD075B7887DCE61D9035FB4D299538E461478",
"ephemeralPublicIutX": "06DBBF5FA4F13C634AF8047E35E46A67D02F8BF1DB77EAA53A33AB1D3DC439287BBC1ABB",
"ephemeralPublicIutY": "02F2E19833597B99DA0685863FE48BA10BBAF18383FAB13B642657EBA885BFE9B77CFFB1",
"tcId": 35,
"hashZ": "03AF44039694D87C6219CA50F9046D808731D0A4FADA79686C0ED31074F0400744F91C4417CBF46BA503FC4DB5236189B2C2CE2F90C5B9E4E499BEE01EC93903"
}
],
"domainParameterGenerationMode": "K-283",
"scheme": "ephemeralUnified",
"kasRole": "responder",
 "hashFunctionZ": "SHA2-512"
}

Code used:

bld = OSSL_PARAM_BLD_new();
/*Get curve name in digest*/
_openssl_ecdsa_curves(cipher, &nid , digest);
OSSL_PARAM_BLD_push_utf8_string(bld, OSSL_PKEY_PARAM_GROUP_NAME, digest, 0);
publoc.buf[0]= POINT_CONVERSION_UNCOMPRESSED;
OSSL_PARAM_BLD_push_octet_string(bld, OSSL_PKEY_PARAM_PUB_KEY, publoc.buf,publoc.len);
privloc_bn = BN_bin2bn((const unsigned char *)privloc->buf, (int)privloc->len, NULL);
OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_PRIV_KEY, privloc_bn);
params = OSSL_PARAM_BLD_to_param(bld);
kactx = EVP_PKEY_CTX_new_from_name(NULL, "EC", NULL);
ret = EVP_PKEY_fromdata_init(kactx);
ret = EVP_PKEY_fromdata(kactx, &pkey, EVP_PKEY_KEYPAIR, params);
pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_EC_PUB_X, &Qxloc->buf , &Qxloc->len);
pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_EC_PUB_Y, &Qyloc->buf , &Qyloc->len);
pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_PRIV_KEY, &privloc->buf , &privloc->len);
OSSL_PARAM_BLD_push_utf8_string(bld, OSSL_PKEY_PARAM_GROUP_NAME, digest, strlen(digest)+1);
pubrem.buf[0]= POINT_CONVERSION_UNCOMPRESSED;
OSSL_PARAM_BLD_push_octet_string(bld, OSSL_PKEY_PARAM_PUB_KEY, pubrem.buf,pubrem.len);
params_remote = OSSL_PARAM_BLD_to_param(bld);
kactx = EVP_PKEY_CTX_new_from_name(NULL, "EC", NULL);
ret = EVP_PKEY_fromdata_init(kactx);
ret = EVP_PKEY_fromdata(kactx, &remotekey, EVP_PKEY_PUBLIC_KEY, params_remote);
dctx = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, NULL);
ret = EVP_PKEY_derive_init(dctx);
ret = EVP_PKEY_derive_set_peer(dctx, remotekey);
ret = EVP_PKEY_derive(dctx, NULL, &ss.len);
ret = EVP_PKEY_derive(dctx, ss.buf, &ss.len);

/*Get MD value*/
openssl_md_convert(cipher & ACVP_HASHMASK, &md);
ctx = EVP_MD_CTX_create();

EVP_DigestInit(ctx, md);
EVP_DigestUpdate(ctx, ss.buf, ss.len);
EVP_DigestFinal(ctx, hashzz_tmp, &hashlen);

My result generated is not matching this expected hashZ value.

Regards
Vikash

**Comment by slontis** [comment]
If I remember rightly these use EC Cofactor DH.

See OSSL_PKEY_PARAM_USE_COFACTOR_ECDH in EVP_PKEY-EC.pod

i.e

````
Enable Cofactor DH (ECC CDH) if this value is 1, otherwise it uses normal EC DH
if the value is zero. The cofactor variant multiplies the shared secret by the
EC curve's cofactor (note for some curves the cofactor is 1).
````

**Comment by slontis** [comment]
K-283 has a cofactor of 4 (see ec_curve.c line 1265) which would be why it doesnt work for some curves..
P256 has a cofactor of 1.
