### ISSUE TITLE
EVP_PKEY_size() returning too small value for a signature

### ISSUE THREAD

**Issue by sahanaprasad07** [openssl/openssl#15552]
While testing libssh, it was found that the following call [1] to EVP_DigestSign() overwrites raw_sig_len.
Using gdb, I checked the value of raw_sig_len before passing it to EVP_DigestSign().
It's value was 32 (as assigned in [2])
After passing it to EVP_DigestSign(),
the value is 64.
[1]https://gitlab.com/libssh/libssh-mirror/-/blob/master/src/pki_crypto.c#L2236
[2] https://gitlab.com/libssh/libssh-mirror/-/blob/master/src/pki_crypto.c#L2212

Because of this memory corruption, there is a crash at [3].

[3] https://gitlab.com/libssh/libssh-mirror/-/blob/master/src/pki_crypto.c#L2296

(as tested with latest master 3.0.0-beta1-dev)

If I change the value of raw_sig_data [4] to
raw_sig_data = (unsigned char *)malloc(4*raw_sig_len);
then the crash is no longer seen.

[4] https://gitlab.com/libssh/libssh-mirror/-/blob/master/src/pki_crypto.c#L2213

The same test has been passing with OpenSSL version 1.1.1.

Kindly investigate this further. Thank you.

**Comment by paulidale** [comment]
I don't think this qualifies as a bug in OpenSSL.  The documentation of `EVP_PKEY_size()` could be improved despite it noting:
> It must be stressed that, unless the documentation for the operation
that's being performed says otherwise, the size returned by
EVP_PKEY_size() is only preliminary and not exact, so the final
contents of the target buffer may be smaller.  It is therefore crucial
to take note of the size given back by the function that performs the
operation, such as L<EVP_PKEY_sign(3)> (the I<siglen> argument will
receive that length), to avoid bugs.

The way to get the output size is to pass a NULL signature parameter to EVP_DigestSign():
```c
EVP_PKEY_size(ctx, NULL, &siglen, input, input_length);
sig = malloc(siglen);
EVP_PKEY_size(ctx, sig, &siglen, input, input_length);
```

**Comment by slontis** [comment]
pauli - please fix the EVP_PKEY_size() above :)

**Comment by levitte** [comment]
The EVP_DigestSign documentation says this (italics line, for emphasis):

> EVP_DigestSign() signs tbslen bytes of data at tbs and places the
> signature in sig _and its length in siglen_ in a similar way to
> EVP_DigestSignFinal().

In other words, this is documented behavior.  YOU must make sure that the result buffer is large enough for the signature.

**Comment by beldmit** [comment]
_the size returned by EVP_PKEY_size() is only preliminary and not exact, so the final contents of the target buffer may be smaller._

This implies that the buffer allocated according to `EVP_PKEY_size` is enough, doesn't it?

**Comment by levitte** [comment]
If you want to know the exact size that the signature buffer should have, you should simply call EVP_DigestSign twice, the first time with the `sig` being NULL.  In other words, something like this:

``` C
    rc = EVP_DigestSign(ctx, NULL, &raw_sig_len, input, input_len);
    raw_sig_data = OPENSSL_malloc(raw_sig_len);
    rc = EVP_DigestSign(ctx, raw_sig_data, &raw_sig_len, NULL, 0);
```

This behavior is documented for `EVP_DigestSignFinal()`

**Comment by beldmit** [comment]
Yes, I totally agree, it's a proper way. But it still means that EVP_PKEY_size is wrong here, doesn't it?

**Comment by paulidale** [comment]
I'd suggest amending the EVP_PKEY_size documentation from:

> so the final contents of the target buffer may be smaller.

to:

> so the final contents of the target buffer may be larger or smaller.

**Comment by t8m** [comment]
I have to disagree here. We have apparently changed the semantics of the EVP_PKEY_size() - is that 3.0 regression? IMO the EVP_PKEY_size should stay to mean upper bound of signature size produced by the EVP_PKEY.

**Comment by t8m** [comment]
@sahanaprasad07 What is the algorithm of the EVP_PKEY involved?

**Comment by t-j-h** [comment]
It must remain the **upper bound** of the required size  - that has been the semantics and they should not change.
The signature can be less, but it cannot be more.

**Comment by mattcaswell** [comment]
> I have to disagree here. We have apparently changed the semantics of the EVP_PKEY_size() - is that 3.0 regression? IMO the EVP_PKEY_size should stay to mean upper bound of signature size produced by the EVP_PKEY.

Agreed. It should be an upper bound.

**Comment by t8m** [comment]
I am looking at the code of EVP_PKEY_size and the underlying implementation of the OSSL_PKEY_PARAM_MAX_SIZE in master and do not see anything suspicious at the first sight. Could you please provide more details about the EVP_PKEY? I.e., the algorithm, the bit lengths of the key values, etc.

**Comment by levitte** [comment]
Side note: `EVP_PKEY_size()` is quite a confusing name, when we have separated out the *operations* from the key type. So to throw in a curve-ball, `EVP_SIGNATURE_size()` anyone?

**Comment by t8m** [comment]
The current description in the manual talks about all the various kinds of operations. So IMO no, it should stay as is. It is of course already renamed to EVP_PKEY_get_size(). Maybe EVP_PKEY_get_max_size() or EVP_PKEY_get_max_output_size() would be a better new name.

**Comment by levitte** [comment]
@sahanaprasad07, what key algorithm was it that got you to this crash?

**Comment by sahanaprasad07** [comment]
ED25519, while executing this test [1]
pki_do_sign() invokes pki_sign_data() [2] that calls EVP_PKEY_size().

[1] https://gitlab.com/libssh/libssh-mirror/-/blob/master/tests/unittests/torture_pki_ed25519.c#L441
[2] https://gitlab.com/libssh/libssh-mirror/-/blob/master/src/pki_crypto.c#L2161

**Comment by t8m** [comment]
Ah, that makes it clear.

**Comment by levitte** [comment]
Ah, yeah, we have a bug, here:

https://github.com/openssl/openssl/blob/31b7f23d2f958491d46c8a8e61c2b77b1b546f3e/providers/implementations/keymgmt/ecx_kmgmt.c#L311-L312

and here:

https://github.com/openssl/openssl/blob/31b7f23d2f958491d46c8a8e61c2b77b1b546f3e/providers/implementations/keymgmt/ecx_kmgmt.c#L318-L319

We keep confusing even ourselves as to the meaning of the EVP_PKEY_size() :wink:

**Comment by levitte** [comment]
@sahanaprasad07, please try #15565

**Comment by sahanaprasad07** [comment]
just tested the fix, I confirm that it works. Thank you!
