### ISSUE TITLE
lh_free crashes

### ISSUE THREAD

**Issue by ataomic** [openssl/openssl#1555]
This bug exists in all SSL versions

(gdb) 0x7ffb24410120 is in lh_free (lhash.c:170).
165             for (i=0; i<lh->num_nodes; i++)
166                     {
167                     n=lh->b[i];
168                     while (n != NULL)
169                             {
170                             nn=n->next;
171                             OPENSSL_free(n);
172                             n=nn;
173                             }
174                     }

The fix:
In lhash.c, the expand function should allocate the memory first, then increase all the counters. Otherwise, it crashes the application because the hash node inserted into wrong slot.

This is the diff for 1.0.2h
[lhash_fix.txt](https://github.com/openssl/openssl/files/462940/lhash_fix.txt)

**Comment by ataomic** [comment]
lh->num_nodes was wrongly increased in expand function

**Comment by richsalz** [comment]
I don't see how it was wrongly increased.  Are you confused about how realloc works?

**Comment by ataomic** [comment]
realloc fails cause num_nodes > bucket size

**Comment by richsalz** [comment]
perhaps the simpler fix is put ```lh->num_nodes--;`` in the "if realloc fails" block.

**Comment by ataomic** [comment]
Yes, revert all the counters fix this issue too.

**Comment by richsalz** [comment]
The only counter to be revered is num_nodes.

**Comment by ataomic** [comment]
I'm not sure. I write a test program, so you can try with your fix. 

[pkgs]$ gcc -Werror -Wall -g lhash.c
[pkgs]$ gdb a.out
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from a.out...done.
(gdb) r
Starting program: a.out

Program received signal SIGSEGV, Segmentation fault.
0x00000000004008a9 in lh_free (lh=0x603010) at lhash.c:192
192                 nn = n->next;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.8.x86_64
(gdb) bt
#0  0x00000000004008a9 in lh_free (lh=0x603010) at lhash.c:192
#1  0x0000000000401384 in main () at lhash.c:503



[lhash.zip](https://github.com/openssl/openssl/files/463092/lhash.zip)

**Comment by ataomic** [comment]
I read the code again. It seems that more test required for 'counter fix'. The memory fix will be the simpler one if you consider the test cost.

**Comment by richsalz** [comment]
I prefer to keep realloc and will work from there.

**Comment by richsalz** [comment]
You have to check the return value of lh_insert.  You can't keep using the hashtable after an insert fails.

**Comment by ataomic** [comment]
I prefer to disable expand if reallloc fails. It helps if the hash table becomes very huge but the system still have memory for small items. For example, can't allocate 2M for hash table, but can allocate 100K for hash nodes.

**Comment by richsalz** [comment]
In general, once malloc fails, openssl stops.  (It’s better, we used to not always catch them, and then crash:)  If you disagree, please brings this up on the mailing list.

**Comment by ataomic** [comment]
If OPENSSL_malloc uses external malloc function, malloc fails doesn't mean system fails, so crash is not a good idea. I will bring this up on the mailing list. Thanks!

**Comment by t-j-h** [comment]
Once malloc fails the function that depends on the malloc should fail. And that failure should make it back to the application to decide what to do. The function should not alter behaviour and silently continue - it must return an error.

**Comment by ataomic** [comment]
Ok, it sounds very reasonable. I agree with you.

Thanks,
Yang

**Comment by richsalz** [comment]
fixed in master, 1.1.0 and 1.0.2  thanks for raising the issue!

**Comment by ataomic** [comment]
Thanks for the fix!

**Comment by ya1gaurav** [comment]
Is this needed in 0.9.8 branch ?

**Comment by mattcaswell** [comment]
@ya1gaurav 0.9.8 has not been supported for some while and no longer receives any bug or security fixes.
