### ISSUE TITLE
FIPS filter is not ignoring whitespace correctly.

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#15562]
#15539 was comment only changes and the fips checker showed differences

It should be ignoring whitespace.

The FIPS check-summing doesn't handle spaces perfectly.

Specificaly, these two lines are considered different:
```c
    statement;  /* comment */
    statement;
```
So adding or removing an end of line comment is detected as significant.

Refer to #15539 in pmeth_lib.c

**Comment by paulidale** [comment]
The actual difference after compressing is:
```diff
@@ -231,7 +231,7 @@
 ret->keytype = keytype;
 ret->keymgmt = keymgmt;
 ret->legacy_keytype = id;
- ret->engine = e;
+ret->engine = e;
 ret->pmeth = pmeth;
 ret->operation = EVP_PKEY_OP_UNDEFINED;
 ret->pkey = pkey;
```
which is here:
https://github.com/openssl/openssl/blob/147ed5f9def86840c9f6ba512e63a890d58ac1d6/crypto/evp/pmeth_lib.c#L323-L330

Minimal example:
```
b; 
 c;
```
There is a space after the `b;` and before the `c;`.  Leaving either out unindents the `c;` after compression.
