### ISSUE TITLE
"Custom" RSA certificate generation & DH params

### ISSUE THREAD

**Issue by jamesoxford08** [openssl/openssl#1556]
I'm not sure this is the right place for this, but its more of a question than an issue.  I've been over all the documentation like probably closing on 100 times and I can't really find anything about it anywhere else.  Is there anyway to generate an RSA private/public key and/or DH parameters from given inputs; Like feed a utility p,q & e (I think those are the unique primes needed for RSA) or feed a utility the prime needed for DH parameters and have it properly encode the values in a certificate/key?

The reason this arises is OpenSSH seems to be a lot more efficient in the way it sieves for safe primes of a given length compared to how OpenSSL generates safe primes.  I have a database of some 40,000+ 4095+ bit length primes (don't ask).  It would be nice if I could use them somewhere other than the OpenSSH moduli file.  Is there a utility available through the command line interface or would one need to implement a custom solution using the openssl library?

**Comment by mattcaswell** [comment]
Do you mean can you do it from the command line? I don't think so. Obviously it can be done via code.

**Comment by jamesoxford08** [comment]
yeah. I was pretty sure there wasn't an option on the command line.  I don't know C/C++ but I have a text now and I'm working on it.  ...And I know there are OpenSSL wrappers for other languages.  Part of this was my effort to really understand PKI/x509/X.690.  I still don't totally understand BER/ASN1.
I know other lesser languages like VB/.NET and PHP; in the .NET framework I know there are ways to read an RSA key and represent the parameters in memory and I know you can create RSA parameters in memory, but I don't think there is a way to actually encode parameters and store them as a certificate.  I also haven't put all that effort into this either at this point.  I just wanted to make sure I hadn't missed any "low laying fruit".

**Comment by richsalz** [comment]
No, all of the ISO/ITU standards for ASN.1 DER BER are freely available.  Perhaps start here: https://www.itu.int/rec/T-REC-X.680/en

Closing this issue.  For more discussion, please use the openssl-users mailing lits, https://mta.openssl.org for details.
