### ISSUE TITLE
Duplicate Code  in file  d1_lib.c

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#15561]
https://github.com/openssl/openssl/blob/8ee66a092c07e618191ef49c8912f8235b08bb95/ssl/d1_lib.c#L389-L414

```dtls1_handle_timeout -->dtls1_double_timeout<lines 399>  --> dtls1_start_timer ``` and   ```dtls1_handle_timeout --> dtls1_start_timer<lines 411> ``` is  duplicate.

**Comment by mattcaswell** [comment]
Fix in #15595
