### ISSUE TITLE
Old header files persist past an upgrade and cause build failure

### ISSUE THREAD

**Issue by jhealyt** [openssl/openssl#15605]
Step 1) OpenSSL versions up to v1.0.2 store their header files in /usr/local/ssl
Step 2) When OpenSSL got to version 1.1.0, the header file location changed to /usr/linclude/
Step 3) Depending on how you uninstalled v1.0.2 and installed v1.1.0, you might be left with the older header files in /usr/local/ssl/
Step 4) The GNU compiler suite search path goes in this order:
```
    * /usr/local/include
    * libdir/gcc/target/version/include
    * /usr/target/include
    * /usr/include
```
Step 5) You go to build a program that needs a new feature in OpenSSL v1.1.0, but it fails to build because it's including the older header files.

I think the solution here would be as follows:
When you install OpenSSL version v1.1.0+, the installation process renames or deletes the directory: /usr/loca/ssl

**Comment by levitte** [comment]
> I think the solution here would be as follows:
> When you install OpenSSL version v1.1.0+, the installation process renames or deletes the directory: /usr/local/ssl

This isn't the right move, as that would absolutely sabotage things for people who do want both installations to be present.

Furthermore, I can see nothing in your description that would automatically look at that directory, so I can only assume that in the builds you have that fail, there's an explicit `-I /usr/local/ssl/include`.  Simply remove that.

**Comment by paulidale** [comment]
Answered, closing.
