### ISSUE TITLE
Adding "openssl" binary into yocto SDK

### ISSUE THREAD

**Issue by sivaprasath9** [openssl/openssl#15603]
We are trying to integrate openssl-bin package into sdk inorder to get openssl binary in SDK. Currently we are using openssl "1.0.2n" version. While building yocto sdk we are facing the below error:

ERROR: core-image-sato-sdk-1.0-r0 do_populate_sdk: Could not invoke dnf. Command '/opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=info -y -c /opt/workspace/yoctol/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/sdk/image/opt/poky/3.1.2/sysroots/corei7-32-poky-linux/etc/dnf/dnf.conf --setopt=reposdir=/opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/sdk/image/opt/poky/3.1.2/sysroots/corei7-32-poky-linux/etc/yum.repos.d --installroot=/opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/sdk/image/opt/poky/3.1.2/sysroots/corei7-32-poky-linux --setopt=logdir=/opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/temp --repofrompath=oe-repo,/opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/oe-sdk-repo --nogpgcheck install coreutils packagegroup-core-eclipse-debug run-postinsts packagegroup-core-ssh-openssh intel-vaapi-driver packagegroup-base-extended target-sdk-provides-dummy gstreamer1.0-vaapi perl packagegroup-core-standalone-sdk-target psplash kernel-devsrc packagegroup-core-sdk packagegroup-core-boot packagegroup-core-tools-testapps packagegroup-core-x11-sato dnf packagegroup-core-tools-profile packagegroup-core-x11-base packagegroup-core-tools-debug rpm' returned 1:
DNF version: 4.2.2
cachedir: /opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/sdk/image/opt/poky/3.1.2/sysroots/corei7-32-poky-linux/var/cache/dnf
Added oe-repo repo from /opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/oe-sdk-repo
repo: using cache for: oe-repo
not found other for:
not found modules for:
not found deltainfo for:
not found updateinfo for:
oe-repo: using metadata from Thu 03 Jun 2021 06:48:52 AM UTC.
Last metadata expiration check: 0:00:01 ago on Thu 03 Jun 2021 06:48:55 AM UTC.
No module defaults found
--> Starting dependency resolution
--> Finished dependency resolution
Error:
Problem: package packagegroup-base-extended-1.0-r83.intel_x86_32 requires libcrypto-bin, but none of the providers can be installed
- conflicting requests
- nothing provides /opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/hosttools/perl needed by libcrypto-bin-1.0.2n-r16.5.corei7_32
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

ERROR: Logfile of failure stored in: /opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/temp/log.do_populate_sdk.5622
ERROR: Task (/opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/meta/recipes-sato/images/core-image-sato-sdk.bb:do_populate_sdk) failed with exit code '1'

Anyone can help on this?

Thanks in Advance

**Comment by levitte** [comment]
It looks like you should look at the failure logfile: /opt/workspace/yocto/Git_Repo/BUILD/i686/poky-dunfell-23.0.2/build/tmp/work/intel_x86_32-poky-linux/core-image-sato-sdk/1.0-r0/temp/log.do_populate_sdk.5622

Other than that, this is a packaging problem, which is external to OpenSSL.  I think you'd have better chances talking with the Yocto project folks.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input
