### ISSUE TITLE
How to debugging ciphersuite between client and server?

### ISSUE THREAD

**Issue by antokxvi** [openssl/openssl#15612]
I'm using openssl 1.1.1d on my raspberry pi, and i want to debugging test ciphersuite between client and server, anybody know about the syntax that i have to used? thanks

**Comment by yangyangtiantianlonglong** [comment]
./config -d -DCIPHER_DEBUG

**Comment by mattcaswell** [comment]
See my answer to your other question in #15613.

**Comment by richsalz** [comment]
> ./config -d -DCIPHER_DEBUG

There are no `CIPHER_DEBUG` ifdefs in standard OpenSSL source.  This will do nothing unless there is local code that is checking it.

**Comment by paulidale** [comment]
Answered, closing.
