### ISSUE TITLE
checking ciphers in openssl 1.1.1d

### ISSUE THREAD

**Issue by antokxvi** [openssl/openssl#15613]
I'm so confuse when i check the ciphers list in openssl with syntax ciphers -v {name cipher}, like this
![image](https://user-images.githubusercontent.com/51256988/120724636-6890f600-c4fe-11eb-8b8e-f87aa180f326.png)
the output is show the tls 1.3 ciphers too. Is it a problem? i'm confuse about that
i have tried to the other cipher, the output is same, that tls 1.3 shown too like this
![image](https://user-images.githubusercontent.com/51256988/120724747-a2fa9300-c4fe-11eb-86f2-61fd04379b1a.png)

![image](https://user-images.githubusercontent.com/51256988/120724764-ad1c9180-c4fe-11eb-8eaf-fe5f0a211c2a.png)

anybody knows about the problem? or its the default setting?

**Comment by paulidale** [comment]
TLS 1.3 is enabled by default in OpenSSL 1.1.1.  The output you are seeing is expected.

**Comment by antokxvi** [comment]
> TLS 1.3 is enabled by default in OpenSSL 1.1.1. The output you are seeing is expected.

okay, thankyou very much sirr

**Comment by mattcaswell** [comment]
> may i ask question, i want to test debugging connection between openssl client and openssl server within cipher that used detailed, but i don't know the syntax/command. do you know about that?

I *think* you are asking how to test a client <-> server connection with a specific cipher. Assuming that you mean a TLSv1.2 (or below) cipher, then to test (for example) the AES128-SHA cipher:

````
$ openssl s_server -cert server.pem -key server-key.pem -cipher AES128-SHA -max_protocol TLSv1.2
````
Then from a separate terminal:

````
$ openssl s_client
````

**Comment by antokxvi** [comment]
> > may i ask question, i want to test debugging connection between openssl client and openssl server within cipher that used detailed, but i don't know the syntax/command. do you know about that?
> 
> I _think_ you are asking how to test a client <-> server connection with a specific cipher. Assuming that you mean a TLSv1.2 (or below) cipher, then to test (for example) the AES128-SHA cipher:
> 
> ```
> $ openssl s_server -cert server.pem -key server-key.pem -cipher AES128-SHA -max_protocol TLSv1.2
> ```
> 
> Then from a separate terminal:
> 
> ```
> $ openssl s_client
> ```

okay thankyou very much sir
