### ISSUE TITLE
OSSL_PROVIDER_load() will accept an absolute filename for the provider name

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15620]
To my surprise calling `OSSL_PROVIDER_load("/path/to/my/provider.so")` actually works and loads that file and gives the provider the name "/path/to/my/provider.so".

This means passing "-provider /full/path/to/provider.so" to the apps actually works without providing a "-provider-path". I'm not sure that is correct behaviour?

**Comment by mattcaswell** [comment]
Either we should fix things so that you can't supply a filename, or alternatively we could fix it so that you can provide a filename, but  we strip off the path and the suffix to get a sensible name for the provider.

**Comment by anhu** [comment]
I think this syntax should be supported .  It was supported for engines so this is a natural progression.  However, if you strip off the path and you have two providers with the same name but different paths, you'll have a name clash.  

Perhaps you can just strip of the `.so` ? Is there a problem with having `/`'s in the name?  is there a problem with having `.so`'s in the name?

**Comment by t8m** [comment]
> Either we should fix things so that you can't supply a filename, or alternatively we could fix it so that you can provide a filename, but we strip off the path and the suffix to get a sensible name for the provider.

Should the provider name be actually one of the parameters of the provider itself rather than libcrypto trying to infer it from the string passed to the OSSL_PROVIDER_load()? I see we have OSSL_PROV_PARAM_NAME but that is actually something more like the DESCRIPTION in case of the algorithms. So perhaps this should be actually OSSL_PROV_PARAM_DESCRIPTION and the OSSL_PROV_PARAM_NAME should be "default" for the default provider, etc.

**Comment by t8m** [comment]
We need to discuss this within OTC before beta therefore I've set the beta1 milestone.

**Comment by mattcaswell** [comment]
Are there potential security implications where an application could be tricked into loading a provider from an unsafe location?

**Comment by anhu** [comment]
> Are there potential security implications where an application could be tricked into loading a provider from an unsafe location?

Were there any for engines?

**Comment by t8m** [comment]
> Are there potential security implications where an application could be tricked into loading a provider from an unsafe location?

I think this is of no business for OpenSSL library to decide. It would be clearly a security issue of the application and not the library. And yes, we allowed that with engines, why shouldn't we with providers.

**Comment by mattcaswell** [comment]
OTC: The functionality as is, is fine. The documentation should be updated and the name for the provider should not be the path.

**Comment by t8m** [comment]
The #15680 changed only the documentation. We need to re-evaluate within OTC whether the name is path is acceptable or not.

**Comment by mattcaswell** [comment]
OTC: We're happy with the documentation updates in #15680.
