### ISSUE TITLE
Obtaining EC public key in different fomatting

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15626]
Does the current master API allow to get EC public key serialized in various format? I mean, at least, explicit/named_curve and compression.

If yes, what is a proper way to set the parameters to get the public key?

**Comment by mattcaswell** [comment]
> I mean, at least, explicit/named_curve and compression.

Yes.

See the following for the full list of gettable/settable params:

https://www.openssl.org/docs/manmaster/man7/EVP_PKEY-EC.html

Specifically `OSSL_PKEY_PARAM_EC_POINT_CONVERSION_FORMAT` can be used to specify the compression and `OSSL_PKEY_PARAM_EC_ENCODING` can be used to specify explicit or named curve.

**Comment by mattcaswell** [comment]
Use `EVP_PKEY_set_params` to actually set these values.
