### ISSUE TITLE
Decoding SubjectPublicKeyInfo structures is very inefficient

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15646]
I have the following file (a DH public key):

````
-----BEGIN PUBLIC KEY-----
MIIBIDCBlQYJKoZIhvcNAQMBMIGHAoGBAKO3UUHeLGtYuOeAefepPlI9wgw+mzQx
/UA2TSyGDj1iu6U7MsOwYzcRa0+dsI/UMeS1Q/gf+g6scoyk6MelTcfPxEb9xZ4S
6+cqsy+8ExZMxTgnM5LfjGEDcNB4qLGKgM4Ryag+azEhg6rvR+xBHOa5cVGpTay2
2VYsqnUl7EjjAgECA4GFAAKBgQCeFtXoVpN1mQ8cSvBoZzFDtcuzzSp6wdo5vU8I
OU6xgr1UgvdEJxtgeBeL5OKu/Z6wavtSOX565GmFvGob78F1kpyJMiCk5mvDm2XJ
5p29enY2n0HAPBHzQNgYDdEoqlH3MWK3pnAkGbFxepp3Vaqg6/KL3IrQ6FULr/71
0IVtIQ==
-----END PUBLIC KEY-----
````

Using the program below I can read it:

````
#include <stdio.h>
#include <openssl/pem.h>
#include <openssl/evp.h>

int main(void)
{
    BIO *bio = BIO_new_file("dhpubkey.pem", "r");
    EVP_PKEY *pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);

    if(pkey == NULL)
        printf("Failed\n");
    else
        printf("Success\n");

    EVP_PKEY_free(pkey);

    return 0;
}
````

The above code will eventually (via the decoders in a provider) call this function - which actually reads a SubjectPublicKeyInfo encoded DH key:

https://github.com/openssl/openssl/blob/6d2e0076e6a8146f3bdaa60151b2fa6e4df0d1bf/crypto/dh/dh_ameth.c#L60-L109

By setting a breakpoint in this function, I see that this decoding routine is actually called 11 times for my simple program above! The key is successfully decoded 10 times and then thrown away. On the 11th time it is successfully decoded and kept.

What happens is this:

1) The PEM file is first decoded to SubjectPublicKeyInfo  (SPKI) DER data
2) There are 11 built-in decoders that know handle SPKI data (one for each key type).
3) The first one gets called (which is for RSA). This uses d2i_RSA_PUBKEY to attempt to read the RSA key. Internally this calls d2i_X509_PUBKEY. That function detects that the key is DH and calls the correct DH decoding function to successfully read the key. The read key is then passed back up the stack to d2i_RSA_PUBKEY which checks its type, discovers that it isn't an RSA key and so throws it away and fails
4) Since the first SPKI decoder failed we move on to the second one which is for RSA-PSS. This is implemented in the same way, and so the DH key is decoded successfully again and then thrown away.
5) We continue to iterate through all the different key types which are all implemented in the same way. So we repeatedly successfully decode the DH key and then throw it away.
6) The final key type in the list to check is a DH key. This time it actually works and the key is returned.

**Comment by t8m** [comment]
IMO we should have wildcard decoders that can produce different key types based on the decoded data. The wildcard keytype decoder would be used in case the keytype is NULL instead of this _try every possible decoder_.

**Comment by mattcaswell** [comment]
How would the wildcard keytype decoder work with keytypes it doesn't know?

**Comment by levitte** [comment]
> How would the wildcard keytype decoder work with keytypes it doesn't know?

Set the data type to be the OID in text form if it can't find the name.  In other words, a call to OBJ_obj2txt().  This is, incidently, what I do in https://github.com/openssl/openssl/pull/15498/files#diff-9c8cda6982e26bbb9ca5a45076c49b4f0d61fa06051412c56f3e8813402a0ec5

**Comment by t8m** [comment]
There could be multiple wildcard decoders present. A third party wildcard decoder could be able to decode these. Of course that would still mean some inefficiency because presumably our wildcard decoder would be tried first and it would fail because it would not know the key type and then the third party one would be tried after that.

**Comment by mattcaswell** [comment]
Using @levitte's OID idea, then we can have just one that knows what to do even in the case of an OID it doesn't recognise.
