### ISSUE TITLE
which is better OpenSSL version for debian buster (raspbian/raspberry armv7l)

### ISSUE THREAD

**Issue by antokxvi** [openssl/openssl#15654]
I'm on project that implementation of OpenSSL modification on my Raspberry Pi 3 Model B+ that used armv7l with OS Raspbian within Debian Buster. On the official debian website [https://packages.debian.org/buster/openssl](url) , it says that the OpenSSL 1.1.1d is the stable version for Debian Buster, but from the OpenSSL project, the newest version is OpenSSL 1.1.1k. Which version is the best for my project, and what's the impact if I used the 1.1.1k version, while the 1.1.1d is the stable version for debian buster?

**Comment by mattcaswell** [comment]
The only difference between 1.1.1d and 1.1.1k are bug and security fixes. The Debian version will be 1.1.1d plus backports of important security fixes. Usually it is sufficient to use the version of OpenSSL provided by your distro.

**Comment by paulidale** [comment]
Answered, closing.
