### ISSUE TITLE
Packet header generation

### ISSUE THREAD

**Issue by alimtolman** [openssl/openssl#15657]
Hey. I'm just exploring the tls messages structure and want to know what those headers mean, and where they're generating. 

16 0301 0200 xxxxxxxx - ClientHello
16 0303 0025 xxxxxxxx
16 0303 0028 xxxxxxxx

Application data

17 0303 0030 5D38950BFE0C9801 xxxxxxxx
17 0303 0027 5D38950BFE0C9802 xxxxxxxx
17 0303 00CB 5D38950BFE0C9803 xxxxxxxx
17 0303 033A 5D38950BFE0C9804 xxxxxxxx
17 0303 0021 5D38950BFE0C9805 xxxxxxxx
17 0303 0043 5D38950BFE0C9806 xxxxxxxx
17 0303 0368 5D38950BFE0C9807 xxxxxxxx

I'm asking about 5D38950BFE0C9801, 5D38950BFE0C9802, 5D38950BFE0C9803 etc
Can someone tell me where it's generated please? (The source code I mean, in 1.1.1)

**Comment by mattcaswell** [comment]
> Can someone tell me where it's generated please? (The source code I mean, in 1.1.1)

These are IVs. The exact length etc is dependent on the cipher and protocol version in use. They are created in cipher specific code. For example here is the location for TLSv1.2 AES GCM based ciphersuites:

https://github.com/openssl/openssl/blob/bfcdfdee50b0adb9a6e448f07fd8f1c87c919cda/crypto/evp/e_aes.c#L3081-L3088

**Comment by alimtolman** [comment]
> > Can someone tell me where it's generated please? (The source code I mean, in 1.1.1)
> 
> These are IVs. The exact length etc is dependent on the cipher and protocol version in use. They are created in cipher specific code. For example here is the location for TLSv1.2 AES GCM based ciphersuites:
> 
> https://github.com/openssl/openssl/blob/bfcdfdee50b0adb9a6e448f07fd8f1c87c919cda/crypto/evp/e_aes.c#L3081-L3088

And why there's 01, 02, 03 etc in the last byte?
Can you please tell me where this is setting in ssl library?

**Comment by mattcaswell** [comment]
> And why there's 01, 02, 03 etc in the last byte?

The initial IV value in the first encrypted record is random:

https://github.com/openssl/openssl/blob/bfcdfdee50b0adb9a6e448f07fd8f1c87c919cda/crypto/evp/e_aes.c#L2898-L2916

Subsequent IV values are simply incremented:

https://github.com/openssl/openssl/blob/bfcdfdee50b0adb9a6e448f07fd8f1c87c919cda/crypto/evp/e_aes.c#L2918-L2931

**Comment by alimtolman** [comment]
Ok, thanks
