### ISSUE TITLE
SHAxxx turned into macros in alpha17 causes client libs build errors

### ISSUE THREAD

**Issue by stac47** [openssl/openssl#15655]
Hello,
I am compiling [POCO](https://github.com/pocoproject/poco) (gcc11 linux/ubuntu amd64). This used to work until alpha16. In alpha17 all the functions SHA256, SHA38... were turned into macros. But this might cause build error.
For instance:
```
  /home/jenkins/workspace/OSP_osp-poco_release_21.0.0/BUILD/poco-1.10.1-all/JWT/src/Signer.cpp:76:45: error: macro "SHA256" requires 3 arguments, but only 1 given
     76 | const std::string Algorithm::SHA256("SHA256");
        |                                             ^
  In file included from /home/jenkins/workspace/OSP_osp-poco_release_21.0.0/DEPS/root/include/openssl/x509.h:41,
                   from /home/jenkins/workspace/OSP_osp-poco_release_21.0.0/DEPS/root/include/openssl/pem.h:23,
                   from /home/jenkins/workspace/OSP_osp-poco_release_21.0.0/BUILD/poco-1.10.1-all/Crypto/include/Poco/Crypto/EVPPKey.h:28,
                   from /home/jenkins/workspace/OSP_osp-poco_release_21.0.0/BUILD/poco-1.10.1-all/Crypto/include/Poco/Crypto/RSAKeyImpl.h:22,
                   from /home/jenkins/workspace/OSP_osp-poco_release_21.0.0/BUILD/poco-1.10.1-all/Crypto/include/Poco/Crypto/RSAKey.h:23,
                   from /home/jenkins/workspace/OSP_osp-poco_release_21.0.0/BUILD/poco-1.10.1-all/JWT/include/Poco/JWT
```
I let you advise on if the macros should be turned back into plain functions.
Regards,
Laurent

**Comment by t8m** [comment]
@DDvO @openssl/otc Apparently having new macros without proper name prefixes is not that good idea. Should we turn those macros back into functions? Perhaps even inline ones?

**Comment by DDvO** [comment]
Converting to inline functions sounds good to me.

**Comment by paulidale** [comment]
Careful with inline functions.  They've caused problems before.

I'm fine having these as normal functions even though they are thin wrappers.

**Comment by levitte** [comment]
So, what becomes of the question of deprecation? After all, that's what got us to this point...

**Comment by paulidale** [comment]
We decided to not deprecate these one shot functions.

**Comment by levitte** [comment]
Thanks for the reminder

**Comment by DDvO** [comment]
So I'll convert those to proper functions.

**Comment by DDvO** [comment]
> So I'll convert those to proper functions.

Oops, just found that this is already done :)
