### ISSUE TITLE
Hang on 2G network

### ISSUE THREAD

**Issue by seemamathew** [openssl/openssl#15669]
Hi, 

We have c++ application which using Azure SDK and open ssl 1.0.2. This application is running in 2 G network. 
In a low network situation, one of the Azure SDK API getting hang. 
On checking detailed logs, it pointing to some open ssl API.
Logs:
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:839 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1426 Failed opening the underlying I/O.

As per information from Azure, the next step after tlsio_openssl_open is calling SSL_free()/SSL_CTX_free().

Could you please help us to find the root cause.
Is there any known issue with this version of SDK.

Thanks in Advance
Seema

**Comment by paulidale** [comment]
That really isn't much to go on.  For a start why do you believe OpenSSL is at fault?  Can we see the failing code?  Knowing that the calls **after** the failure are OpenSSL ones isn't much use.

Version 1.0.2 is also unsupported.

**Comment by seemamathew** [comment]
Hi Pauli,

Thank you for quick response
We are using azure SDK from
https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_01_2021_Ref01

Error logs are collected using this SDK.

We tried to upgrade open ssl version, but due to dependency to underlying libraries we are facing some difficulties in upgrading it. 

Thanks and Regards
Seema

**Comment by t8m** [comment]
Closing as 1.0.2 is unsupported.
