### ISSUE TITLE
RSAPSK ciphers not classed as PSK

### ISSUE THREAD

**Issue by Iansus** [openssl/openssl#1566]
Hi!
I noticed some strange behavior in the latest 1.0.2i-dev release, when trying to ban PSK ciphersuites from my Apache config.

According to OpenSSL documentation, this is what should be the PSK container:
```
PSK

    All cipher suites using pre-shared keys (PSK).
```

There is no distinction as to whether the pre-shared key is used for authentication or key exchange.
However, when I add manually all the PSK containers individually and I remove them with "!PSK", there are leftovers, which are all "RSAPSK":
```
root ~ $ ./openssl version
OpenSSL 1.0.2-chacha (1.0.2i-dev)
root ~ $ ./openssl ciphers 'PSK:ECDHEPSK:RSAPSK:DHEPSK:aPSK:kPSK:kRSAPSK:kDHEPSK:kECDHEPSK:!PSK'
RSA-PSK-AES256-CBC-SHA:RSA-PSK-AES128-CBC-SHA:RSA-PSK-RC4-SHA:RSA-PSK-3DES-EDE-CBC-SHA
```

So it would seem that RSAPSK are neither PSK nor kRSAPSK in this version.
Can you confirm that point? If yes, is this the normal behavior ?

Regards,
iansus

**Comment by mattcaswell** [comment]
What I get:

````
$ ./openssl version
OpenSSL 1.0.2i-dev  xx XXX xxxx

$ ./openssl ciphers 'PSK:ECDHEPSK:RSAPSK:DHEPSK:aPSK:kPSK:kRSAPSK:kDHEPSK:kECDHEPSK:!PSK'
Error in cipher list
140125948876440:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1383:
````

This is the correct behaviour. The only obvious difference between these two is your version which is listed as:

````
OpenSSL 1.0.2-chacha (1.0.2i-dev)
````

This is not a version string produced from official sources (we do not produce any 1.0.2-chacha version). Therefore I assume this is some patched version (possibly from a distro) which is adding chacha ciphers.

Further version 1.0.2 does not support RSAPSK, ECDHEPSK or DHEPSK ciphersuites. 1.0.2 only has support for plain PSK:

````
$ ./openssl ciphers 'PSK'
PSK-AES256-CBC-SHA:PSK-AES128-CBC-SHA:PSK-RC4-SHA:PSK-3DES-EDE-CBC-SHA
````

Version 1.1.0 does support those ciphersuites, but that behaves as expected:

````
$ ./openssl version
OpenSSL 1.1.0-dev xx XXX xxxx

$ ./openssl ciphers 'PSK'
DHE-PSK-AES256-CCM8:DHE-PSK-AES256-CCM:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:ECDHE-PSK-CAMELLIA256-SHA384:RSA-PSK-CAMELLIA256-SHA384:DHE-PSK-CAMELLIA256-SHA384:PSK-AES256-CCM8:PSK-AES256-CCM:PSK-AES256-CBC-SHA384:PSK-AES256-GCM-SHA384:PSK-AES256-CBC-SHA:PSK-CAMELLIA256-SHA384:DHE-PSK-AES128-CCM8:DHE-PSK-AES128-CCM:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:ECDHE-PSK-CAMELLIA128-SHA256:RSA-PSK-CAMELLIA128-SHA256:DHE-PSK-CAMELLIA128-SHA256:PSK-AES128-CCM8:PSK-AES128-CCM:PSK-AES128-CBC-SHA256:PSK-AES128-GCM-SHA256:PSK-AES128-CBC-SHA:PSK-CAMELLIA128-SHA256:ECDHE-PSK-RC4-SHA:RSA-PSK-RC4-SHA:DHE-PSK-RC4-SHA:PSK-RC4-SHA:ECDHE-PSK-3DES-EDE-CBC-SHA:RSA-PSK-3DES-EDE-CBC-SHA:DHE-PSK-3DES-EDE-CBC-SHA:PSK-3DES-EDE-CBC-SHA:ECDHE-PSK-NULL-SHA384:ECDHE-PSK-NULL-SHA256:ECDHE-PSK-NULL-SHA:RSA-PSK-NULL-SHA384:RSA-PSK-NULL-SHA256:DHE-PSK-NULL-SHA384:DHE-PSK-NULL-SHA256:RSA-PSK-NULL-SHA:DHE-PSK-NULL-SHA:PSK-NULL-SHA384:PSK-NULL-SHA256:PSK-NULL-SHA

$ ./openssl ciphers 'PSK:ECDHEPSK:RSAPSK:DHEPSK:aPSK:kPSK:kRSAPSK:kDHEPSK:kECDHEPSK:!PSK'
Error in cipher list
140472895325848:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1343:
````

Therefore I assume that wherever you got your version of OpenSSL from has backported the new PSK ciphersuites from 1.1.0 into 1.0.2 - but has introduced a bug in the process. I suggest you file a bug report with whoever that is.

**Comment by PeterMosmans** [comment]
Hi @Iansus @mattcaswell - I'm to blame for that fork :wink: - see https://github.com/PeterMosmans/openssl
Thanks for reporting, I'm on it.

Cheers,

Peter
