### ISSUE TITLE
OBJ_create() returns 0 when used for 2nd time

### ISSUE THREAD

**Issue by udiakasnuke** [openssl/openssl#15660]
We recently migrated to openssl 1.1.1i from 1.0.2. While testing a SCEP related usecase we are observing that OBJ_create() API is returning 0 when used for 2nd time.

The flow of the application is such that when somehow our client gets recreated due to some configuration change so we do the enrollment again to SCEP server and the below mentioned code path is executed again but this time OBJ_create returns 0.

Here's the piece of code that we are using, which looks like the root cause for the actual crash. 
We also have  the compatibility related checks, so the same piece of code works fine for 1.0.2 openssl while OBJ_create returns 0 for 1.1.1. 

```
int CSimpleCertificateEnrollmentFacade::InitializeOpenSSL()
{
	unsigned char   randpool[1024];
#if OPENSSL_VERSION_NUMBER < 0x10100000L
	/* Add algorithms/digests/ciphers and init random pool */
	OpenSSL_add_all_ciphers();
	OpenSSL_add_all_algorithms();
	OpenSSL_add_all_digests();
#endif
	RAND_seed(randpool, sizeof(randpool));

	/* Create OpenSSL NIDs */

	g_nid_messageType = OBJ_create("2.16.840.1.113733.1.9.2", "messageType", "messageType");
	g_nid_pkiStatus = OBJ_create("2.16.840.1.113733.1.9.3", "pkiStatus", "pkiStatus");
	g_nid_failInfo = OBJ_create("2.16.840.1.113733.1.9.4", "failInfo", "failInfo");
	g_nid_senderNonce = OBJ_create("2.16.840.1.113733.1.9.5", "senderNonce", "senderNonce");
	g_nid_recipientNonce = OBJ_create("2.16.840.1.113733.1.9.6", "recipientNonce", "recipientNonce");
	g_nid_transId = OBJ_create("2.16.840.1.113733.1.9.7", "transId", "transId");
	g_nid_extensionReq = OBJ_create("2.16.840.1.113733.1.9.8", "extensionReq", "extensionReq");

	if (!g_nid_messageType || !g_nid_pkiStatus || !g_nid_failInfo ||
		!g_nid_senderNonce || !g_nid_recipientNonce || !g_nid_recipientNonce ||
		!g_nid_transId || !g_nid_extensionReq)
	{
#if OPENSSL_VERSION_NUMBER < 0x10100000L
		OBJ_cleanup();
		EVP_cleanup();
#endif
		LOGW() << "unable to create object identifiers (OID)";
		return DC_FAILURE;
	}

	return DC_SUCCESS;

}
```

Now the problem is because of the above mentioned issue the SCEP enrollment is failing when using this API
```
PKCS7_set_signed_attributes
```
where we set the attribs via the following
```
add_attribute(attribs, g_nid_transId, trans->trans_id,
				  (int)strlen(trans->trans_id), V_ASN1_PRINTABLESTRING);
add_attribute(attribs, g_nid_messageType, req_type_str,
				  (int)strlen(req_type_str), V_ASN1_PRINTABLESTRING);
add_attribute(attribs, g_nid_senderNonce, trans->sender_nonce,
				  trans->sender_nonce_len, V_ASN1_OCTET_STRING);
```
and this is the small piece of code causing the problem, basically PKCS7_set_signed_attributes fails and then openssl crashes in PKCS7_free(p7)
```
if (!PKCS7_set_signed_attributes(si, attribs))
	{
		LOGD() <<  "Unable to set signed attributes";
		sk_X509_ATTRIBUTE_pop_free(attribs, X509_ATTRIBUTE_free);
		PKCS7_free(p7);
		OPENSSL_free(buf);
		return DC_FAILURE;
	}
```
As i understand initialization and deinitiliazation of openssl is handled by library itself since 1.1.0, so we don't do anything explicit on that part.

Please look into this and revert. Thanks!!

**Comment by t8m** [comment]
I do not think we want to revert this. It has been like that since 1.1.0 release. You need for each object test whether the OBJ_sn2nid() returns something else than NID_undef and use that value instead of re-creating the object. Or to be on the safe side you should check also the consistency with OBJ_txt2nid() value.

**Comment by udiakasnuke** [comment]
Hi @t8m - Thanks for replying.. As i see the documentation for OBJ_create() we have
```
int OBJ_create(const char *oid, const char *sn, const char *ln);
```
whereas for the following 
```
int OBJ_sn2nid(const char *sn);
int OBJ_txt2nid(const char *s);
```

How do you propose i use this new API that you are suggesting since it takes only a single argument will it have the same affect ?

Here is 1 of the creation from my code 
```
g_nid_messageType = OBJ_create("2.16.840.1.113733.1.9.2", "messageType", "messageType");
```
can you please suggest the alternate what you are saying. It would be very helpful. Thanks a ton!!

**Comment by t8m** [comment]
```
const char *txt, *sn, *ln;

txt = "2.16.840.1.113733.1.9.2";
sn = "messageType";
ln = "messageType"'

if ((g_nid_messageType = OBJ_sn2nid(sn)) == NID_undef) {
    g_nid_messageType = OBJ_create(txt, sn, ln);
} else if (g_nid_messageType != OBJ_txt2nid(txt)) {
    Error();
}
```

**Comment by udiakasnuke** [comment]
@t8m - looks like this is working - i wrote this small function to test out - 
```
void getnids(const char* txt, const char* sn, const char* ln, int& nid)
{
	LOGD() << OBJ_sn2nid(sn);
	if ((nid = OBJ_sn2nid(sn)) == NID_undef)
	{
		LOGD() << OBJ_sn2nid(sn);
		nid = OBJ_create(txt, sn, ln);
	}
}
```
and calling the above via the below and similarly for others
```
getnids("2.16.840.1.113733.1.9.2", "messageType", "messageType", g_nid_messageType);
```

for the first time object creation happens via call to OBJ_create() inside if statement and then for subsequent call i.e for 2nd time OBJ_sn2nid() was returning me the proper nid i.e same as last time.

@t8m  - Thanks a lot!!

**Comment by kaduk** [comment]
It sounds like this question has been answered, so I'll close the github issue.  Please reopen it or file a new issue if there remains an issue.
