### ISSUE TITLE
AppVeyor regression from change from rel2abs() to abs_path() in Test.pm 

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#15679]
The change from rel2abs() to abs_path() in Test.pm (#15644) caused regression in AppVeyor builds:
https://ci.appveyor.com/project/openssl/openssl/builds/39529249

```
# The results of this test will end up in test-runs\prep_fipsmodule
..\test\recipes\00-prep_fipsmodule_cnf_data: No such file or directory at C:\projects\openssl\util\perl/OpenSSL/Test.pm line 1154.
BEGIN failed--compilation aborted at ..\test\recipes\00-prep_fipsmodule_cnf.t line 17.00-prep_fipsmodule_cnf.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
Test Summary Report
-------------------
00-prep_fipsmodule_cnf.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
Result: FAIL
Died at ..\test\run_tests.pl line 312.
NMAKE : fatal error U1077: 'cmd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by levitte** [comment]
Argh.  How come that didn't err in #15644?  Or did it and no one noticed?

**Comment by t8m** [comment]
It does not fail the same way in GitHub CI. Not sure what is the difference. The 00-prep_fipsmodule_cnf.t is run at least in the 64bit shared build.

**Comment by levitte** [comment]
I'm conducting an experiment in https://github.com/levitte/openssl/tree/experimental-appveyor-202106 to figure this out

**Comment by levitte** [comment]
Aha!  The flip side of using `abs_path` is that it checks if the directory exists, i.e. it's more than mere string munging.  So, it finds that some directories do not exist, and barfs...

Fix coming up

**Comment by levitte** [comment]
See #15700
