### ISSUE TITLE
Install R with error and have to install openssl

### ISSUE THREAD

**Issue by yueli8** [openssl/openssl#15671]
Hello,

Thank you for developing so nice software!

I have error when install R, and have to install OpenSSL.

1. Which version of OpenSSL, and where I can download it?
2. How I can install the correct version of OpenSSL?

Thank you in advance for your great help!

Best!

Yue

`checking if libcurl is version 7 and >= 7.28.0... yes`
`checking if libcurl supports https... no`
`configure: error: libcurl >= 7.28.0 library and headers are required with support for https`

**Comment by mattcaswell** [comment]
> Which version of OpenSSL, and where I can download it?

Assuming this is Linux you can usually get pre-compiled OpenSSL from your distro. The OpenSSL project only distributes source code which can be downloaded from here:

https://www.openssl.org/source/

The version required will depend on the software that is using it. Most likely OpenSSL 1.1.1.

**Comment by paulidale** [comment]
Answered, closing.
