### ISSUE TITLE
OpenSSL 1.1.0 cannot compile with lua-nginx-module v0.10.6

### ISSUE THREAD

**Issue by ja1cul** [openssl/openssl#1567]
Hi.
I tried to compie openssl1.1.0 + nginx1.11.3 +  lua-nginx-module v0.10.6.
But could not compile.

lua-nginx-module uses session_id,session_id_length members of struct ssl_session_st .
But they were privated , lua-nginx-module can't use them.

So I want to make functions to use these in lua-nginx-module.
I am going to post a message like this to lua-nginx-module community soon.

diff --git a/src/ngx_http_lua_ssl_session_storeby.c b/src/ngx_http_lua_ssl_session_storeby.c
index b5596bc..114de52 100644
--- a/src/ngx_http_lua_ssl_session_storeby.c
+++ b/src/ngx_http_lua_ssl_session_storeby.c
@@ -249,6 +254,6 @@ ngx_http_lua_ssl_sess_store_handler(ngx_ssl_conn_t *ssl_conn,<br>
     cctx->connection = c;
     cctx->request = r;
     cctx->session = sess;
\-    cctx->session_id.data = sess->session_id;
\-    cctx->session_id.len = sess->session_id_length;
\+    cctx->session_id.data = SSL_get_sessionid( sess);
\+    cctx->session_id.len = SSL_get_sessionid_length( sess );
     cctx->done = 0;

--- a/include/openssl/ssl.h
+++ b/include/openssl/ssl.h
@@ -1692,6 +1692,8 @@ __owur SSL_SESSION *SSL_get_session(const SSL *ssl);
 __owur SSL_SESSION *SSL_get1_session(SSL *ssl); /* obtain a reference count */
 __owur SSL_CTX *SSL_get_SSL_CTX(const SSL *ssl);
 SSL_CTX *SSL_set_SSL_CTX(SSL *ssl, SSL_CTX *ctx);
\+unsigned char * SSL_get_sessionid( SSL_SESSION *sess);
\+unsigned int SSL_get_sessionid_length( SSL_SESSION *sess );
 void SSL_set_info_callback(SSL *ssl,
                            void (*cb) (const SSL *ssl, int type, int val));
 void (*SSL_get_info_callback(const SSL *ssl)) (const SSL *ssl, int type,<br>
diff --git a/ssl/ssl_ciph.c b/ssl/ssl_ciph.c
index 0d46509..366dcc9 100644
diff --git a/ssl/ssl_lib.c b/ssl/ssl_lib.c
index bd0fbf8..488f412 100644
--- a/ssl/ssl_lib.c
+++ b/ssl/ssl_lib.c
@@ -3414,6 +3414,15 @@ SSL_CTX *SSL_set_SSL_CTX(SSL *ssl, SSL_CTX *ctx)
     return ssl->ctx;
 }
 
\+unsigned char * SSL_get_sessionid( SSL_SESSION *sess)
\+{
\+	return sess->session_id ;
\+}
\+unsigned int SSL_get_sessionid_length( SSL_SESSION *sess )
\+{
\+	return sess->session_id_length ;
\+}
\+
 int SSL_CTX_set_default_verify_paths(SSL_CTX *ctx)
 {
     return (X509_STORE_set_default_paths(ctx->cert_store));
'

**Comment by mattcaswell** [comment]
Please use this existing `SSL_SESSION_get_id()` function for this purpose.

**Comment by ja1cul** [comment]
Hi mattcaswell

Thank you for your quick response.
I understand and will use this.

bye
