### ISSUE TITLE
secp256k1 only works if both client and server use TLS 1.2 but fails with 1.3

### ISSUE THREAD

**Issue by TheBestOrNothing** [openssl/openssl#15675]
### Problem description
I'm trying to use secp256k1 with the ECDSA algorithm, assmuming that the key of **BTC** or **ETH** will be used grpc authentication directly. Unfortunately secp256k1 only works if both client and server use TLS 1.2 but fails with 1.3.

### Reproduction steps
All the following contents and steps can been found from the [repository](https://github.com/vulnsystem/OpenssLabs/tree/main/secp256k1)
1. To generate server and client's EC secp256k1 private key and TLS certificates with [gen.sh](https://github.com/vulnsystem/OpenssLabs/tree/main/secp256k1/gen.sh). 
```shell
# 1. Generate EC private key and self-signed certificate
openssl ecparam -genkey -out ca.key -name secp256k1 
openssl req -x509 -new -key ca.key -out ca.cert -subj "/C=FR/ST=Occitanie/L=Toulouse/O=Tech School/OU=Education/CN=*.techschool.guru/emailAddress=root.guru@gmail.com"

echo "CA's self-signed certificate"
openssl x509 -in ca.cert -noout -text

# 2. Generate web server's private key and certificate signing request (EC)
openssl ecparam -genkey -out server.key -name secp256k1 
openssl req  -key server.key -new -out server.req -subj "/C=FR/ST=Ile de France/L=Paris/O=PC Book/OU=Computer/CN=*.pcbook.com/emailAddress=server@gmail.com"

# 3. Use CA's private key to sign web server's CSR and get back the signed certificate
openssl x509 -req -in server.req -days 60 -CA ca.cert -CAkey ca.key -CAcreateserial -out server.cert -extfile server.ext

echo "Server's signed certificate"
openssl x509 -in server.cert -noout -text

# 4. Generate client's private key and certificate signing request (EC)
openssl ecparam -genkey -out client.key -name secp256k1 
openssl req -key client.key -new  -out client.req -subj "/C=FR/ST=Alsace/L=Strasbourg/O=PC Client/OU=Computer/CN=*.client.com/emailAddress=client@gmail.com"

# 5. Use CA's private key to sign client's CSR and get back the signed certificate
openssl x509 -req -in client.req -days 60 -CA ca.cert -CAkey ca.key -CAcreateserial -out client.cert -extfile client.ext

echo "Client's signed certificate"
openssl x509 -in client.cert -noout -text

# 6. To verify the server certificate aginst by root CA
echo "server's certificate verification"
openssl verify -show_chain -CAfile ca.cert server.cert

# 7. To verify the client certificate aginst by root CA.
echo "client's certificate verification"
openssl verify -show_chain -CAfile ca.cert client.cert
```
2. Create server with openssl with TLS 1.2
```
openssl s_server -accept 20000 -cert server.cert -key server.key  -debug -tlsextdebug -curves secp256k1 -tls1_2
```
3. Access server with client
```
openssl s_client -showcerts -connect localhost:20000  -CAfile ca.cert  -cert client.cert -key client.key -curves secp256k1 -tls1_2
```
4. Output of handshake successfully with TLS 1.2
```shell
Server certificate
subject=CN = localhost, emailAddress = server@gmail.com
issuer=CN = localhost, emailAddress = ca@gmail.com

No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: ECDH, secp256k1, 256 bits
SSL handshake has read 1085 bytes and written 330 bytes
Verification: OK
New, TLSv1.2, Cipher is **ECDHE-ECDSA-AES256-GCM-SHA384**
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
```
5. Try the same way as TLS 1.3 
```
openssl s_server -accept 20000 -cert server.cert -key server.key  -debug -tlsextdebug -curves secp256k1 -tls1_3
```
```
openssl s_client -showcerts -connect localhost:20000  -CAfile ca.cert  -cert client.cert -key client.key -curves secp256k1 -tls1_3
```
6.  Error information in the server side
```
ERROR
140591523578304:error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:../ssl/t1_lib.c:2589:
shutting down SSL
CONNECTION CLOSED
```
7. Error information in the client side 
```
CONNECTED(00000005)
140496557109696:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1528:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 258 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```
### Environment
 - OS [Ubuntu 18.04 amd64]
 - Openssl version [1.1.1]
 - Authentication mode: SSL/TLS
 - Signature algorithm: ecdsa-withsha256
 - Key generate type: **secp256k1**

### Comments and Question
**TLS 1.3 with secp256k1 is very helpful and useful to build up peer to peer safe communication with BTC or ETH key.**
May this is the same reason why [grpc node mutual auth failed when uses secp256k1](https://github.com/grpc/grpc-node/issues/1802)
Could you please help to fix this issue? Thanks.

> This is a  a separate and different issue from [openssl supports obsoleted curves in TLS 1.3](https://github.com/openssl/openssl/issues/8369)

**Comment by t8m** [comment]
But TLS-1.3 standard does not allow using secp256k1. We would be non-conforming in this regard if we allowed that.

**Comment by mattcaswell** [comment]
It is not entirely correct to say secp256k1 cannot be used in TLSv1.3. It *can* but *only* for key exchange.

E.g.

````
$ openssl s_server -groups secp256k1
$ openssl s_client -groups secp256k1
...
Server Temp Key: ECDH, secp256k1, 256 bits
...
````
It is not currently possible to use it in a certificate because there are no suitable signature schemes in the IANA TLS Signature Scheme registry. See:

https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme

The only ECDSA schemes that have codepoints assigned are the following:
ecdsa_secp256r1_sha256
ecdsa_secp384r1_sha384
ecdsa_secp521r1_sha512
ecdsa_brainpoolP256r1tls13_sha256
ecdsa_brainpoolP384r1tls13_sha384
ecdsa_brainpoolP512r1tls13_sha512

As you can see none of these use the secp256k1 curve.

In order to add support for this to OpenSSL you would first have to get a codepoint for it. That is a matter for the IETF TLS WG not OpenSSL. See:

https://datatracker.ietf.org/wg/tls/about/

**Comment by kaduk** [comment]
> It is not entirely correct to say secp256k1 cannot be used in TLSv1.3. It _can_ but _only_ for key exchange.

A careful reading of RFC 8446 reveals that even this usage is intended to be forbidden -- from https://datatracker.ietf.org/doc/html/rfc8446#appendix-B.3.1.4 :
```
      enum {
          unallocated_RESERVED(0x0000),

          /* Elliptic Curve Groups (ECDHE) */
          obsolete_RESERVED(0x0001..0x0016),
          secp256r1(0x0017), secp384r1(0x0018), secp521r1(0x0019),
[...]
          (0xFFFF)
      } NamedGroup;

      struct {
          NamedGroup named_group_list<2..2^16-1>;
      } NamedGroupList;

   Values within "obsolete_RESERVED" ranges are used in previous
   versions of TLS and MUST NOT be offered or negotiated by TLS 1.3
   implementations.
```

**Comment by richsalz** [comment]
Also, look at https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8  You can see that `secp256k1` is not recommended, not referenced in RFC 8446, and defined in RFC 8422.

You can write it up and get a codepoint assigned, but it's highly doubtful that it will ever be an official part of TLS 1.3

**Comment by TheBestOrNothing** [comment]
Dear all, I'm new to the OpenSSL community. what is codepoint mean in this context and how can we get a codepoint assigned?

**Comment by mattcaswell** [comment]
> Dear all, I'm new to the OpenSSL community. what is codepoint mean in this context and how can we get a codepoint assigned?

A codepoint is a number. In order to be able to use secp256k1 for signatures we need a signature scheme for it. For example at the link I gave previously (https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme) you can see that the signature scheme "ecdsa_secp256r1_sha256" has the number "0x0403". We would need a similar number for an ECDSA signature scheme using secp256k1. Without this any implementation that OpenSSL might provide would not interoperate with any other library (which is something we will not do).

Assigning a codepoint is bigger than just OpenSSL. If affects all TLS implementations and is the remit of the IETF TLS Working Group. If I understand the process correctly you would need to write up an RFC describing the new signature scheme and request a codepoint. However @richsalz and @kaduk are much better able to advise on the process than I am (you will note that @richsalz is one of the assigned experts for the TLS SignatureScheme registry at the link I gave, and @kaduk is the IETF area director with responsibility for the IETF TLS Working Group).

**Comment by richsalz** [comment]
The requirement to get into the codepoint registry is that the use has to be documented. It can be an internet-draft, or other docs. It doesn't have to go through the full IETF RFC process.  I suggest you look at the link Matt and I gave, and then look at the iana.org website.

Of course, it is unlikely that this will be accepted as part of the official TLS protocol definition.  If you want to try that, see https://dt.ietf.org/wg/tls and join the mailing list and make a posting.  If it is not an official standard, the OpenSSL project is less likely to support it.    See the comments on "crypto policy" at https://www.openssl.org/blog/blog/2018/01/18/f2f-london/ as well.

**Comment by kaduk** [comment]
Going back to the original post, I'll also note that:

> TLS 1.3 with secp256k1 is very helpful and useful to build up peer to peer safe communication with BTC or ETH key.

seems to suggest a desire to use the same key for BTC or ETH and for TLS.  This is actually contrary to cryptographic best practices, and can invalidate the proof of security for either protocol for which the key is being "reused".  Reusing a single key for different operations in different contexts introduces the risk that an input could be swapped from one context to another (in this case, from BTC to TLS, or vice versa) to produce an unexpected (and insecure!) outcome.  Only using any given cryptographic key for a single type of operation is the most reliable way to avoid this type of attack.

**Comment by richsalz** [comment]
What Ben said:  do not re-use the same key for different things.

**Comment by TheBestOrNothing** [comment]
@kaduk @richsalz Thanks very much for your guide. So is there any detailed information to tell re-use the same key is insecure? and why there is risk when re-use the same key in different context?

**Comment by richsalz** [comment]
> So is there any detailed information to tell re-use the same key is insecure? and why there is risk when re-use the same key in different context?

A web search for "dangers of key-reuse" will find many papers. Perhaps start with https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-felsch.pdf  Also search for "cross-protocol attacks"  Perhaps this thesis from nearly 10 years ago: https://www.esat.kuleuven.be/cosic/publications/thesis-208.pdf

**Comment by t8m** [comment]
Closing as an answered question. We certainly are not going to implement non-standard codepoint for secp256k1 for TLS-1.3
