### ISSUE TITLE
Please consider changing the license for OpenSSL 3.0+ to dual Apache 2.0/LGPLv2

### ISSUE THREAD

**Issue by berolinux** [openssl/openssl#15685]
Thanks for trying to resolve the license problems in OpenSSL 3.0 with the switch to Apache 2.0 -- however, there's a small problem with that license as well: It is incompatible with the GPLv2.
https://www.apache.org/licenses/GPL-compatibility.html

While the GPL incompatibility has been resolved in the GPLv3, a lot of code remains under the GPL v2 only because some contributors don't like the Tivoization clause in the GPLv3. A lot of GPLv2 projects that use OpenSSL already exist, each of them with their own licensing exception along the lines of "This is released under the GPLv2 with the extra permission to link to OpenSSL" - but this causes new problems (can't link the code with the extra permission to (L)GPLv2 libraries that don't have any extra permissions), and in some cases will create new problems with the changed license in OpenSSL 3.0 ((L)GPLv2 projects that grant permission to link to "code unter the the OpenSSL 1.0 license" or something along those lines rather than "OpenSSL" can't update to 3.0 without getting everyone to agree on a license change).

It would be great if the licensing situation could be resolved for those projects as well by dual-licensing under the Apache 2.0 and (L)GPLv2 licenses. Since the license is changing for 3.0 anyway, this is probably the best time to make such a change.

**Comment by mattcaswell** [comment]
This was discussed many times at the time of the licensing work. The change of license was the result of several years of hard work contacting previous contributors to the project (from before the time that CLAs were mandatory) and confirming their acceptance of the licence change or (in some cases) removing code where acceptance was not provided. I cannot understate the amount of work and time that went into this. Licenses are an emotive issue (not least when the GPL is involved) and there were many strong and opposing opinions expressed by many different people. The GPLv2 issue was well understood at that time.

I don't believe there is any appetite to reopen this debate or to recontact the many hundreds of contributors to ask if they are ok with GPLv2 (which I suspect a small but significant minority will not be).

**Comment by richsalz** [comment]
> . I cannot understate the amount of work and time that went into this

This is true.  Way true.  (I did most, not all, of the work.)  It took nearly two years.  See https://www.openssl.org/blog/blog/categories/license/ for some blog posts about it.

**Comment by mattcaswell** [comment]
OMC: The OMC will not be doing this.
