### ISSUE TITLE
Support for selecting curves / groups in s_client

### ISSUE THREAD

**Issue by MichalStaruch** [openssl/openssl#1568]
Servers can support multiple cipher suites, and multiple curves (or groups if we consider ffdhe2048 etc. - see [RFC 7919](https://tools.ietf.org/html/rfc7919) and [current TLS v1.3 draft](https://tools.ietf.org/html/draft-ietf-tls-tls13-15#appendix-A.3.1.3)).

When establishing connection via s_client -connect we can select cipher suite we want using -cipher parameter, for example "cipher -kEECDH+aRSA:kEDH+aRSA". But cipher string doesn't currently allow selecting particular curve / group, and I didn't notice any separate option for selecting it, either.

So my proposal is to add support for selecting particular curves / groups in s_client - either by extending cipher string syntax ("-cipher kEECDH+gX25519+aRSA:kEDH+gFFDHE4096+aRSA") or by adding another parameter for that ("-group X25519:FFDHE4096").

Similar approach is already supported in Microsoft Schannel, where you can use cipher strings like "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384_P521".

**Comment by richsalz** [comment]
A flag to specify the groups seems useful.  Extending the cipher-suite syntax would take longer, as there are changes for TLS 1.3, changes to support versions perhaps, and so on.

**Comment by dcooper16** [comment]
Try using the "-curves" option.
```
 -curves arg       - Elliptic curves to advertise (colon-separated list)
```
For example:
```
openssl s_client -cipher kEECDH -curves prime256v1:secp384r1 -connect 192.30.253.112:443 -servername github.com
```
It was added in OpenSSL 1.0.2:

>   *) Enhance and tidy EC curve and point format TLS extension code. Use
>      static structures instead of allocation if default values are used.
>      New ctrls to set curves we wish to support and to retrieve shared curves.
>      Print out shared curves in s_server. New options to s_server and s_client
>      to set list of supported curves.
>      [Steve Henson]

**Comment by MichalStaruch** [comment]
@dcooper16 Indeed "-curves" option seems to be working (at least on OpenSSL 1.1.0), but currently it's an undocumented feature - it should be listed under "man s_client" and "man s_server", where most people (myself included) will look for it.

And maybe it's the time to future-proof this parameter - I'd add either rename "-curves" to "-group", or add "-group" alias, so it would fit the FFDHE groups, when they come.

@richsalz Extension of cipher string syntax would be a bigger change, but it would allow to:
1. Bind specific sets of parameters together, for example X448 with AES-256 (when you need over 200 bits of security), or X25519 with AES-128 (when ~128 bits are enough).
2. Configure groups in applications that support passing cipher string, but doesn't support groups / curves configuration.

Worth implementing, IMO.

**Comment by richsalz** [comment]
It *is* documented, just in a different manpage.  I tried to make that link more explicit, see https://github.com/openssl/openssl/pull/1574

**Comment by richsalz** [comment]
commit 6f0ac0e in master and 03a8bf0 in 1.1.0 makes the doc link more explicit.

**Comment by MichalStaruch** [comment]
LGTM :+1:
