### ISSUE TITLE
Configuring OpenSSL - PKCS#7 to X509,

### ISSUE THREAD

**Issue by lijintv07** [openssl/openssl#15699]
I'm working on a project where i need to convert PKCS#7 to X509,
I only need these PKCS#7 and X509 related functions  alone from OpenSSL, How do i configure OpenSSL before building the project?
Could you please guide to obtain this.

**Comment by slontis** [comment]
After you configure it says you can run the following.
> perl configdata.pm --dump
This lists the 'Enabled features'. Any of these features can be disabled.
The options are described in INSTALL.md. e.g. no-cmp.

**Comment by lijintv07** [comment]
@slontis  is there any OpenSSL porting guide available for RTOS?

**Comment by slontis** [comment]
Not that I am aware of.
