### ISSUE TITLE
OpebSSL 3.0 how to access fields in EVP_CIPHER_CTX

### ISSUE THREAD

**Issue by LinghaoYu** [openssl/openssl#15703]
The EVP_CIPHER_CTX is defined at https://github.com/openssl/openssl/blob/master/crypto/evp/evp_local.h#L36. How can I access its encrypt and final_used fields of a given EVP_CIPHER_CTX? I checked the manpage but wasn't able to find it. Can someone please help?

**Comment by mattcaswell** [comment]
You can use `EVP_CIPHER_CTX_is_encrypting()` to check the `encrypt` value. `final_used` is really an internal implementation detail. You're not supposed to access it (and in fact is unused if using a provided cipher).
