### ISSUE TITLE
Wrong MAC calculation for certain plaintext lengths with AES128_CBC_SHA256 ciphersuites in TLS

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#15706]
When connecting to openssl server with a vanilla connection (i.e. no Encrypt then MAC, no Extended Master Secret) and TLS_*_AES_128_CBC_SHA256 ciphersuites, OpenSSL generates records with incorrect MAC, but only for certain sizes.
The ones I've tested were between 1000-1024 bytes and 2000-2048 bytes (inclusive). Of those 2032-2047 and 1008-1023 (inclusive) generate incorrect MAC values.

Reproducer:
```
cat > make-files.py << EOF
for i in range(1000, 1025):
    with open("data-{0}.txt".format(i), "wb+") as f:
        f.write(b"A" * (i-1) + b"\n")
EOF
python3 make-files.py
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -HTTP -cipher @SECLEVEL=0:AES128-SHA256
```
in another console:
```
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tlsfuzzer/tlsfuzzer/pull/762 gets merged
git checkout length-testing
git clone https://github.com/tlsfuzzer/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/tlsfuzzer/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python3 scripts/test-lengths.py
```
(alternatively the server can be set up with either ECDHE-RSA-AES128-SHA256 or DHE-RSA-AES128-SHA256 ciphersuite and tlsfuzzer script executed with the `-d` option)

tlsfuzzer output:
```
...
length: 1008 ...
Error encountered while processing node <tlsfuzzer.expect.ExpectApplicationData object at 0x7f061e6d0cd0> (child: <tlsfuzzer.messages.AlertGenerator object at 0x7f061e6d0d00>) with last message being: None
Error while processing
Traceback (most recent call last):
  File "scripts/test-lengths.py", line 229, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 196, in run
    header, parser = self.state.msg_sock.\
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 102, in recvMessageBlocking
    for res in self.recvMessage():
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 84, in recvMessage
    for ret in self.recvRecord():
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 927, in recvRecord
    data = self._decryptThenMAC(header.type, data)
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 702, in _decryptThenMAC
    raise TLSBadRecordMAC()
tlslite.errors.TLSBadRecordMAC

length: 1010 ...
Error encountered while processing node <tlsfuzzer.expect.ExpectApplicationData object at 0x7f061e6d5730> (child: <tlsfuzzer.messages.AlertGenerator object at 0x7f061e6d5760>) with last message being: None
Error while processing
Traceback (most recent call last):
  File "scripts/test-lengths.py", line 229, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 196, in run
    header, parser = self.state.msg_sock.\
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 102, in recvMessageBlocking
    for res in self.recvMessage():
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 84, in recvMessage
    for ret in self.recvRecord():
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 927, in recvRecord
    data = self._decryptThenMAC(header.type, data)
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 702, in _decryptThenMAC
    raise TLSBadRecordMAC()
tlslite.errors.TLSBadRecordMAC
...

====================
version: 1
====================
TOTAL: 27
SKIP: 0
PASS: 11
XFAIL: 0
FAIL: 16
XPASS: 0
====================
FAILED:
        'length: 1008'
        'length: 1009'
        'length: 1010'
        'length: 1011'
        'length: 1012'
        'length: 1013'
        'length: 1014'
        'length: 1015'
        'length: 1016'
        'length: 1017'
        'length: 1018'
        'length: 1019'
        'length: 1020'
        'length: 1021'
        'length: 1022'
        'length: 1023'
```

While debugging it, @beldmit and me suspect the assembly `aesni_cbc_sha256_enc()` method.

Update: I've tested all lengths between 1 and 8192, and the ones that fail are: 240-255, 496-511, 752-767, etc. every 256

**Comment by t8m** [comment]
Is this in master only?

**Comment by tomato42** [comment]
yes, it's 3.0.0 only, 1.1.1k isn't affected

also setting `OPENSSL_ia32cap` to either `0x0:0x0` or masking the AES-NI bit makes the issue go away on master

**Comment by t8m** [comment]
My investigation so far:
1. it is not in aesni_cbc_sha256_enc() as masking SHAEXT and AVX bits does not make the issue go away but the aesni_cbc_sha256_enc() is not called in such case
2. it appears even in OPENSSL_NO_MULTIBLOCK build

**Comment by mattcaswell** [comment]
git bisect tells me that the offending commit is 0d2bfe52bb

**Comment by beldmit** [comment]
I'm afraid it just means that it's because of switching from legacy to provider in `crypto/evp/evp_enc.c`

**Comment by beldmit** [comment]
Yes, the offending part of this commit is switching to provider code from legacy.

**Comment by beldmit** [comment]
Current state: when https://github.com/openssl/openssl/commit/0d2bfe52bb7e839f7bddcdb1160c335f2994df2f is checked out, `providers/implementations/ciphers/cipher_aes_cbc_hmac_sha256_hw.c` implementation is broken but `crypto/evp/e_aes_cbc_hmac_sha256.c` is not

**Comment by beldmit** [comment]
@slontis , do you have a chance to look?

**Comment by slontis** [comment]
I might try to have a look tomorrow.
It would help if you have a simpler way to repo the issue..

**Comment by beldmit** [comment]
@slontis Non-isolated reproducer:
Use patch from #15735
s_server: `openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -HTTP`
s_client: `openssl s_client -connect localhost:4433 -no_etm -tls1_2 -cipher ECDHE-RSA-AES128-SHA256`
After connection succeeds, request `GET /data-1019.txt HTTP/1.0`, where data-1019.txt is plain text file 1019 bytes length.

I get the following error on the s_client side:
```
GET /data-1019.txt HTTP/1.0
C001CF04D07F0000:error:1C800066:Provider routines:ossl_cipher_generic_stream_update:cipher operation failed:providers/implementations/ciphers/ciphercommon.c:470:
C001CF04D07F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:609:
```
for the current master

**Comment by tomato42** [comment]
> I might try to have a look tomorrow.
> It would help if you have a simpler way to repo the issue..

Could you say what makes the instructions complex?

**Comment by tomato42** [comment]
@beldmit the other thing that would make it easier to reproduce is having an echo mode in s_server, like I've described in #15736

**Comment by beldmit** [comment]
Found it!!!

https://github.com/openssl/openssl/blob/f77208693ec3bda99618e6f76c0f8d279c0077bb/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha256_hw.c#L736

**Comment by mattcaswell** [comment]
> Found it!!!

Nice work!

**Comment by t8m** [comment]
> Found it!!!

Good work!

**Comment by samm-git** [comment]
congrats!
