### ISSUE TITLE
Hashcat segmentation fault after upgrade

### ISSUE THREAD

**Issue by MrUndead13** [openssl/openssl#15715]
Good afternoon,
I updated my GPU driver this morning and did a apt update and upgrade this afternoon.
When I try to use hashcat , I get the following error :
Segmentation fault

Would anyone have a fix for this issue ?

Thanks in advance !

**Comment by mattcaswell** [comment]
Errr...and what has this got to do with OpenSSL?

**Comment by MrUndead13** [comment]
Sorry I couldn't find a way to create another issue.. I clicked on New Issue within the OPenssl channel without seeing it.. so sorry
