### ISSUE TITLE
OpenSSL Porting on RTOS

### ISSUE THREAD

**Issue by gskrish7** [openssl/openssl#15726]
Hi,

I am trying to incorporate OpenSSL with an RTOS. The target platform is am ARM A5 family, we have the compilers set-up. However, I am facing few challenges while try porting OpenSSL.

1. OpenSSL using linux libraries <sys/types.h>  => I tried replacing it with <stdint.h>
2. OpenSSL configurations has only VxWorks RTOS configuration.
3. Calling non-standard memory.h in bio_pk7.c => Simply commented #include <memory.h>
3. bio_pk7.c BIO_new_NDEF called -> Could not definition in OpenSSL library

I would like to port it to RTOS with following configurations; while trying to look into the header, could not find any documentation for each macro in opensslconf.h

So, I have built opensslconf.h for linux_x85_x64 and added few macro
1. Disable random seeding - Not sure how to add TRNG on the platform as Entropy source for random seeding.
    //#ifndef OPENSSL_RAND_SEED_OS
    //# define OPENSSL_RAND_SEED_OS
    //#endif
2. Disabled Threads
    //#ifndef OPENSSL_THREADS
    //# define OPENSSL_THREADS
    //#endif
3. Disable File IO
    #ifndef OPENSSL_NO_STDIO
    #define OPENSSL_NO_STDIO
    #endif
4. Modify network Send/Recv - not yet understood
While including a sample driver function to that converts certificate format, I am seeing numerous errors e_os.h(I think it is not required) and even after macro OPENSSL_NO_STDIO defined, some file related functions are being enabled for compilation on X509_def.c. 

Still I am facing issues may other compilation issues. The OpenSSL looks like have Linux libraries dependencies. I would like to have/locate developer documentation to understand the OpenSSL project organization and understand to configure the library in granular level. And successfully port OpenSSL on top of RTOS.

Thank You,
GK

**Comment by paulidale** [comment]
You most definitely should **not** be configuring for `linux_x85_x64` (disregarding the typo).  You should be configuring for one of the ARM targets.  `linux_armv4` might be a beginning.  `linux-generic32` might also be.

I suggest reading the INSTALL.md file and then looking at the configurations available.
