### ISSUE TITLE
Which config should I use to compile OpenSSL 1.1.1k?

### ISSUE THREAD

**Issue by TenTakano** [openssl/openssl#15721]
Hi,

I'm trying to compile OpenSSL 1.1.1k for Android devices. I got the following options by `./Configure LIST | grep android`, but I'm not sure which one is correct.

```
android-arm
android-arm64
android-armeabi
android-mips
android-mips64
android-x86
android-x86_64
android64
android64-aarch64
android64-mips64
android64-x86_64
```

Currently, from the target ABI is armeabi-v7a, I guess `android-arm` is the correct selection.
However, I want to know also the others for future updates. Especially, android64 and options whose name start with android64 confuse me because there are 64 bit architectures like android-arm64. (Does it my cheep understanding of Android architectures?)

The following is my cross-compile environments.

- OS: Ubuntu 20.04 LTS
- NDK: r19c (Cannot change to latest version because of a requirement of my using framework)

**Comment by JeromeDeBretagne** [comment]
Hi @TenTakano,

As described in the [NOTES.ANDROID](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1l/NOTES.ANDROID#L20-L21) documentation, I've been compiling OpenSSL 1.1.1x for Android successfully using the following configs:
- for 32-bit ARM processors (armeabi-v7a): `android-arm`
- for 64-bit ARM processors (arm64-v8a): `android-arm64`
- for 64-bit x86 processors (x86_64): `android-x86_64`

and in a similar way, the last main config would be:
- for 32-bit x86 processors (x86): `android-x86`

The other configs are kept for backwards compatibility it seems, as described [here](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1l/Configurations/15-android.conf#L263-L280).

I hope this answers your question,
Jérôme
