### ISSUE TITLE
Porting OpenSSL for RTOS

### ISSUE THREAD

**Issue by lijintv07** [openssl/openssl#15729]
I am trying to port OpenSSL for RTOS. Could you help me with a OpenSSL porting guide for RTOS.

**Comment by paulidale** [comment]
There is no porting guide that I'm aware of.  If your RTOS supports a POSIX like version of C, it shouldn't be too difficult.  Without this it could be hard.

Have you searched for TLS/crypto tool kits targeted at such platforms?
