### ISSUE TITLE
Support echo mode in s_server

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#15736]
Issues like #15706 are a bit harder to reproduce and test for because they require creation of files of specific lengths.

It would be much easier if `openssl s_server` supported an `-echo` option, where the server would just echo back the data received from the client.

**Comment by mattcaswell** [comment]
Is "-rev" good enough?

````
       -rev
           Simple test server which just reverses the text received from the
           client and sends it back to the server. Also sets -brief. Cannot be
           used in conjunction with -early_data.
````

**Comment by tomato42** [comment]
@mattcaswell yes, that is good enough for testing  #15706, but I think the documentation of it could make it a bit easier to find, see #15739

**Comment by beldmit** [comment]
I think this could be closed?

**Comment by tomato42** [comment]
right
