### ISSUE TITLE
Incomplete definition of type 'struct x509_st' error when using sk_X509_value(certificates, 0)->signature

### ISSUE THREAD

**Issue by atiksplanet** [openssl/openssl#15738]
Hello,
We are using OpenSSL 1.0 in our project and Its working fine.
Recently we are trying to update  OpenSSL library to 1.1.1 version for the project.
We replaced all the **header files**, **libcrypto.a** and **libssl.a** with from https://github.com/krzyzanowskim/OpenSSL.
But we are getting build error in one of our existing C implementation.
The function with  C implementation is below.
```
const char *getFileSignature(const char *filePathBytes, size_t filePathSize) {
     const char *signature = NULL;
     STACK_OF(X509) *certificates = NULL;
     //..... Implementations
     X509 *certValue = sk_X509_value(certificates, 0);
     const unsigned char *signatureData;
     int signatureLength;
     signatureLength = certValue->signature->length; //Incomplete definition of type 'struct x509_st'
     signatureData = certValue->signature->data; //Incomplete definition of type 'struct x509_st'
     //..... Implementations
     return signature;
}
```
Getting build error **`Incomplete definition of type 'struct x509_st'`** in `signatureLength = certValue->signature->length;` and `signatureData = certValue->signature->data;` lines.

Any idea how can resolve this issue from our implementation or any alternative solution for this case?

Thanks in advance

**Comment by mattcaswell** [comment]
The X509 type (along with many others) was made opaque in 1.1.0 and above. Use the `X509_get0_signature`to get the signature value instead:

https://www.openssl.org/docs/man1.1.1/man3/X509_get0_signature.html

**Comment by atiksplanet** [comment]
Thanks @mattcaswell 
Your answer helped me to resolve the issue.
Below is the resolved code snippet with `X509_get0_signature` usage.
```
const char *getFileSignature(const char *filePathBytes, size_t filePathSize) {
     const char *signature = NULL;
     STACK_OF(X509) *certificates = NULL;
     
     //..... Implementations

     X509 *certValue = sk_X509_value(certificates, 0);
     const unsigned char *signatureData;
     int signatureLength;

     const ASN1_BIT_STRING *asnSignature;
     X509_get0_signature(&asnSignature, NULL, certValue);

     signatureLength = asnSignature->length;
     signatureData = asnSignature->data;

     //..... Implementations

     return signature;
}
```
