### ISSUE TITLE
: undefined reference to `OPENSSL_init_crypto'

### ISSUE THREAD

**Issue by knoxcard** [openssl/openssl#1573]
Never have a problem compiling the Bitcoin core on my Debian Jessie server.  I recently upgraded to the latest vesion of OpenSSL 1.1.0 and things went awry.

Getting this error..
: undefined reference to `OPENSSL_init_crypto'

How  do I clear out the SSL headers from previous installs?

**Comment by richsalz** [comment]
you have to set the bitcoin compile flags to point to where you installed openssl.

**Comment by knoxcard** [comment]
this got it for me! all installed...

[Special thanks to user2084795]
http://stackoverflow.com/questions/29477569/use-self-compiled-openssl-to-compile-bitcoin-on-fedora-21

Bitcoin appears to run on an old version of OpenSSL, OpenSSL version:  OpenSSL 1.0.2a 19 Mar 2015
, which I found surprising.  Wasn't OpenSSL support removed though?

**SOLUTION**
install dependecies
export OPENSSL_PREFIX=/usr/local/ssl/
Download and unzip openssl-1.0.2a source code
CC='cc -fPIC' ./config --prefix=$OPENSSL_PREFIX
make all install_sw
Download and unzip bitcoin source code
./autogen.sh
./configure --without-gui CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib"
make
sudo make install

**Comment by Bitcoinera** [comment]
This didn't help me. I still get the same problem and followed all instructions step by step. I also installed Openssl 1.1.0 and now I need to downgrade to 1.0.2 again.
