### ISSUE TITLE
Missing tests for stitched ciphers

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15749]
We need to test stitched ciphers (AES+SHA, maybe also RC4+MD5) to avoid cases like #15706.

Follow-up to #15740

**Comment by t8m** [comment]
I would not call this a feature. Not having any tests for a particular cipher implementation seems more like a bug to me. Sure it is not something we must backport to 1.1.1.

**Comment by paulidale** [comment]
I'd call this a bug fix too.  I don't see a need to back-port to 1.1.1 but wouldn't oppose such.  Adding a test case is a safe change IMO.
