### ISSUE TITLE
aix64-gcc: openssl-3.0.0-alpha17 does not build using gcc without no-asm

### ISSUE THREAD

**Issue by gv74** [openssl/openssl#15748]
```
gcc -maix64 -pthread -O -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/var/pd/ssl\"" -DENGINESDIR="\"/usr/pd/lib/engines-3\"" -DMODULESDIR="\"/usr/pd/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -c -o crypto/bn/libcrypto-shlib-ppc-mont.o crypto/bn/ppc-mont.s
gcc -maix64 -pthread -O -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/var/pd/ssl\"" -DENGINESDIR="\"/usr/pd/lib/engines-3\"" -DMODULESDIR="\"/usr/pd/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -c -o crypto/bn/libcrypto-shlib-ppc64-mont-fixed.o crypto/bn/ppc64-mont-fixed.s
Assembler:
crypto/bn/ppc64-mont-fixed.s: line 4: Error In Syntax 
make[1]: *** [Makefile:6969: crypto/bn/libcrypto-shlib-ppc64-mont-fixed.o] Error 1
make[1]: Leaving directory '/home/xxx/openssl-3.0.0-alpha17'

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix7.1.0.0/9.3.1/lto-wrapper
Target: powerpc-ibm-aix7.1.0.0
Configured with: ../gcc-9.3.1-20200408/configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++ --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --enable-bootstrap --build=powerpc-ibm-aix7.1.0.0
Thread model: aix
gcc version 9.3.1 20200408 (GCC) 
```

openssl-3.0.0-alpha13 was the latest version I tried and was compiling fine.

**Comment by paulidale** [comment]
#15175 introduced this code.

@martin-schwenke, any idea?

**Comment by martin-schwenke** [comment]
Will try to get on an AIX machine to test this.  Our testing was with gcc on Linux.

Until then, @gv74 can you please paste the output of `head crypto/bn/ppc64-mont-fixed.s`?  The first thing I'm wondering is whether Perl is running correctly and properly generating correct assembly.  Thanks...

**Comment by gv74** [comment]
```
.machine        "any"
.csect  .text[PR],7
.align  5
.p2align        5,,31

.globl  .bn_mul_mont_fixed_n6
.bn_mul_mont_fixed_n6:
        mr      9,3

        mtvsrd  32,14

```

**Comment by martin-schwenke** [comment]
@paulidale Not sure what the convention is here, but I'm happy to have this assigned to me.  I broke it, I'll fix it!  Sorry about that...

**Comment by paulidale** [comment]
I don't know either :)

**Comment by martin-schwenke** [comment]
@gv74 What processor is this building for?

I'm trying to work out whether the error message is for line 4 of the file or the 4th instruction.  Can you please try adding:
```
        or        3,3,3
```

before the line with `mtvsrd`.  Then we can see if the error moves down.  If it does then it must be because `mtvsrd` is only for ISA >= 2.07 (e.g. >= IBM Power8) and we shouldn't have unconditionally used that instruction.  I'll get a patch ready for that issue tomorrow, even if it is a different one...

**Comment by gv74** [comment]
```
$ head -n15 crypto/bn/ppc64-mont-fixed.s
.machine        "any"
.csect  .text[PR],7
.align  5
.p2align        5,,31

.globl  .bn_mul_mont_fixed_n6
.bn_mul_mont_fixed_n6:
        mr      9,3

        or      3,3,3
        mtvsrd  32,14
        mtvsrd  33,15
        mtvsrd  34,20
        mtvsrd  35,21
        mtvsrd  36,22
```

```
$ make
make depend && make _build_sw
make[1]: Entering directory '/home/xxx/openssl-3.0.0-alpha17'
make[1]: Leaving directory '/home/xxx/openssl-3.0.0-alpha17'
make[1]: Entering directory '/home/xxx/openssl-3.0.0-alpha17'
gcc -maix64 -pthread -O -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/var/pd/ssl\"" -DENGINESDIR="\"/usr/pd/lib/engines-3\"" -DMODULESDIR="\"/usr/pd/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -c -o crypto/bn/libcrypto-lib-ppc64-mont-fixed.o crypto/bn/ppc64-mont-fixed.s
Assembler:
crypto/bn/ppc64-mont-fixed.s: line 4: Error In Syntax 
make[1]: *** [Makefile:13800: crypto/bn/libcrypto-lib-ppc64-mont-fixed.o] Error 1
make[1]: Leaving directory '/home/xxx/openssl-3.0.0-alpha17'
make: *** [Makefile:3130: build_sw] Error 2
```

The error seems pretty clear to me:
Assembler:
crypto/bn/ppc64-mont-fixed.s: **line 4**: Error In Syntax 

```
$ lsconf | grep Processor
Processor Type: PowerPC_POWER8
Processor Implementation Mode: POWER 8
Processor Version: PV_8_Compat
Number Of Processors: 2
Processor Clock Speed: 3425 MHz
  Model Implementation: Multiple Processor, PCI bus
+ proc0                                                           Processor
+ proc8                                                           Processor
```

**Comment by martin-schwenke** [comment]
Yep, seems pretty clear, especially since the extra instruction doesn't move the error.  I was wondering if those directives count as lines.  I have seen things like pre-processor directives mess with line numbering...

Can you please take out that no-op `or` that I asked you to add and try deleting that 4th line saying:
```
.p2align        5,,31
```
and try building again?

I don't see `.p2align` in any other Power assembly in the OpenSSL code, so I'm guessing we shouldn't be doing that if the code is meant to be portable...

Thanks!

**Comment by gv74** [comment]
Without line 4, the compilation succeed for `ppc64-mont-fixed.s`. openssl still cannot be compiled because of another error later in build process (I will open a new issue) but removing the line fix at least this problem.

Thank you!

**Comment by martin-schwenke** [comment]
Thanks to you for doing the testing!

I'll get a patch for that ready tomorrow, along with one for the other issue that I noticed.

**Comment by martin-schwenke** [comment]
@gv74 Can you please tell me what `./config` or `./Configure` command you used on AIX?  I can't get past some very basic errors (shell syntax, Perl error).  Thanks...

**Comment by gv74** [comment]
[build-openssl-alpha.sh.txt](https://github.com/openssl/openssl/files/6661868/build-openssl-alpha.sh.txt)

github won't let me attach a .sh script.  Just rename attached .txt file.

**Comment by martin-schwenke** [comment]
I have patches but want to discuss some aspects with people around "here" before posting them.  Tomorrow...

**Comment by gv74** [comment]
Take your time. Thank you.

**Comment by t8m** [comment]
> I have patches but want to discuss some aspects with people around "here" before posting them. Tomorrow...

That probably means they won't make it into beta1. Which is not fatal of course.

**Comment by martin-schwenke** [comment]
> [build-openssl-alpha.sh.txt](https://github.com/openssl/openssl/files/6661868/build-openssl-alpha.sh.txt)

The key was passing `aix64-gcc`.  Thanks!
