### ISSUE TITLE
Error in NEWS.md

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15743]
NEWS.md says this:

````
  * The X25519, X448, Ed25519, Ed448 and SHAKE256 algorithms are included in
    the FIPS provider.  None have the "fips=yes" property set and, as such,
    will not be accidentially used.
````

In spite of what it says above, all of these algorithms have "fips=yes" set.

Also, it seems odd that SHAKE256 is explicitly called out, but SHAKE128 is not.

**Comment by mattcaswell** [comment]
Another line in NEWS.md says this:

````
  * The algorithm specific public key command line applications have
    been deprecated.  These include dhparam, gendsa and others.  The pkey
    alternatives should be used instead: pkey, pkeyparam and genpkey.

````
Did we actually deprecate these in the end? I thought we decided not to??

**Comment by paulidale** [comment]
They are not deprecated.

The ECX and SHAKE algorithms are usable in a FIPS context (i.e. the documentation is wrong).
