### ISSUE TITLE
RSA_GENERATE_KEY_EX takes 10-20 seconds on ARM32-bit platforms

### ISSUE THREAD

**Issue by remainfox** [openssl/openssl#15751]
**openssl version**: `openssl-1.1.1k`

**openssl run platform**: `arm-32bit, 4 cores, 1.2GHZ`

**encryption info**: `rsa key length is 2048 bytes, The encryption algorithm is RSA_F4`

**openssl compile environment**: `ubuntu 18.04 64bit`

```c
root@brian:webrtc# cat /proc/version
Linux version 5.4.0-74-generic (buildd@lcy01-amd64-023) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021
```

**openssl compile command**:

```c
./Configure no-asm shared -fPIC linux-generic32  no-tests --prefix=$INSTALL_DIR --openssldir=$INSTALL_DIR
```

**problem description**:
```
RSA_GENERATE_KEY_EX takes 10-20 seconds on ARM32-bit platforms
```

**Comment by paulidale** [comment]
Does a second generation take this long too?

**Comment by remainfox** [comment]
@paulidale yes

**Comment by paulidale** [comment]
This is likely due to the increase in the number of Miller Rabin rounds used for probably prime checking.  I'm guessing that this is for a fairly slow ARM processor?

The [migration guide](https://github.com/openssl/openssl/blob/master/doc/man7/migration_guide.pod#key-generation-is-slower) has this to say:
>#### Key generation is slower
>
>The Miller-Rabin test now uses 64 rounds, which is used for all prime generation, including RSA key generation. This affects the time for larger keys sizes.
>
>The default key generation method for the regular 2-prime RSA keys was changed to the FIPS 186-4 B.3.6 method (Generation of Probable Primes with Conditions Based on Auxiliary Probable Primes). This method is slower than the original method.

@slontis, was a way to use the faster method made available?

**Comment by slontis** [comment]
No.

**Comment by paulidale** [comment]
Getting rid of the `no-asm` configuration option should improve performance significantly.

It's too late for us to switch to a different prime generation algorithm especially since we don't if there are performance benefits or not.

**Comment by t-j-h** [comment]
@paulidale @slontis note this is for **openssl-1.1.1k** and is not for **master**

@remainfox you don't state the size of the key you are generating nor the CPU speed of the arm platform (both of which are significant with respect to the expecting time for key generation)

**Comment by slontis** [comment]
thanks Tim I just realized this before.

**Comment by slontis** [comment]
Maybe try using armv4 instead of linux-generic32 also?

**Comment by remainfox** [comment]
@t-j-h rsa key length is **2048** bytes,  The encryption algorithm is **RSA_F4**,  arm cpu 4 cores 1.2GHZ

**Comment by remainfox** [comment]
@paulidale thanks, Remove the `no-asm` option, and it's still slow

```
./Configure shared -fPIC linux-generic32  no-tests --prefix=$INSTALL_DIR --openssldir=$INSTALL_DIR
```

```c
XLOG_INFO("111111111111111");
/* This takes some time. */
if (!RSA_generate_key_ex(rsa_key, num_bits, bne, NULL)) {
		XLOG_TRACE("RSA_generate_key_ex() failed\n");
		goto error;
}
XLOG_INFO("222222222222222");
```

```
2021-06-15 21:46:40.708 INFO: [WebrtcDtlsSrtp.cpp:webrtc_dtls_generate_keys:431] 111111111111111
2021-06-15 21:47:05.080 INFO: [WebrtcDtlsSrtp.cpp:webrtc_dtls_generate_keys:437] 222222222222222
```

takes 25 seconds

**Comment by remainfox** [comment]
@slontis thanks for your reply,  When the `linux-armv4` compilation option is added, time consumption is significantly reduced

```
./Configure shared -fPIC linux-armv4 no-tests --prefix=$INSTALL_DIR --openssldir=$INSTALL_DIR 
```

```
2021-06-15 22:15:01.709 INFO: [WebrtcDtlsSrtp.cpp:webrtc_dtls_generate_keys:431] 111111111111111
2021-06-15 22:15:03.272 INFO: [WebrtcDtlsSrtp.cpp:webrtc_dtls_generate_keys:437] 222222222222222
```

**Less than 2 seconds**

**Comment by remainfox** [comment]
@slontis Hello, is there any way to continue to improve, thank you, Sometimes it takes up to three seconds

**Comment by slontis** [comment]
Not sure there is..
