### ISSUE TITLE
Incosistent cipher name AES_128 and AES128 prevents exclusion

### ISSUE THREAD

**Issue by xplora1a** [openssl/openssl#15761]
I am trying to ensure that the cipher selection for my site only uses ciphers with greater than 128 bit keys and hashes.
I have set the cipher selection to: 
HIGH:!aNULL:!SHA:!AES128:!CAMELLIA128:!ARIA128
but this still selects the cipher TLS_AES_128_GCM_SHA256

I think this is because the two ciphers TLS_AES_256_GCM_SHA384 and TLS_AES_128_GCM_SHA256 are named with AES_128 and AES_256 rather than AES128 and AES256 as seems the norm for the other ciphers.

```
`$` openssl ciphers -s 'HIGH:!aNULL:!SHA:!AES128:!CAMELLIA128:!ARIA128'
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:
ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:
DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:
DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-CCM8:ECDHE-ECDSA-AES256-CCM:
DHE-RSA-AES256-CCM8:DHE-RSA-AES256-CCM:ECDHE-ECDSA-ARIA256-GCM-SHA384:
ECDHE-ARIA256-GCM-SHA384:DHE-DSS-ARIA256-GCM-SHA384:DHE-RSA-ARIA256-GCM-SHA384:
ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:
DHE-DSS-AES256-SHA256:ECDHE-ECDSA-CAMELLIA256-SHA384:ECDHE-RSA-CAMELLIA256-SHA384:
DHE-RSA-CAMELLIA256-SHA256:DHE-DSS-CAMELLIA256-SHA256:AES256-GCM-SHA384:
AES256-CCM8:AES256-CCM:ARIA256-GCM-SHA384:AES256-SHA256:CAMELLIA256-SHA256
```

**Comment by mattcaswell** [comment]
> I think this is because the two ciphers TLS_AES_256_GCM_SHA384 and TLS_AES_128_GCM_SHA256 are named with AES_128 and AES_256 rather than AES128 and AES256 as seems the norm for the other ciphers.

This is not the reason.

`TLS_AES_128_GCM_SHA256` is a TLSv1.3 ciphersuite. It is always sent by default if you have TLSv1.3 enabled and is not impacted by the cipher selection string.  If you add the "-tls1_2" option to your "ciphers" command you will see that it goes away:

````
$ openssl ciphers -s -tls1_2 'HIGH:!aNULL:!SHA:!AES128:!CAMELLIA128:!ARIA128'
````

Alternatively you can configure the TLSv1.3 ciphersuites to be empty using the "-ciphersuites" option:

````
openssl ciphers -s -ciphersuites "" 'HIGH:!aNULL:!SHA:!AES128:!CAMELLIA128:!ARIA128'
````

**Comment by xplora1a** [comment]
@mattcaswell Thanks I see. and yes these are only selected for TLS1.3 from testssl I get:
Testing server preferences 

 Has server cipher order?     yes (OK) -- TLS 1.3 and below
 Negotiated protocol          TLSv1.3
 Negotiated cipher            TLS_AES_256_GCM_SHA384, 253 bit ECDH (X25519)
 Cipher order
    TLSv1.2:   ECDHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-CHACHA20-POLY1305
               DHE-RSA-CHACHA20-POLY1305 DHE-RSA-AES256-CCM8 DHE-RSA-AES256-CCM
               ECDHE-ARIA256-GCM-SHA384 DHE-RSA-ARIA256-GCM-SHA384 ECDHE-RSA-AES256-SHA384
               DHE-RSA-AES256-SHA256 ECDHE-RSA-CAMELLIA256-SHA384 DHE-RSA-CAMELLIA256-SHA256
               AES256-GCM-SHA384 AES256-CCM8 AES256-CCM ARIA256-GCM-SHA384 AES256-SHA256
               CAMELLIA256-SHA256 
    TLSv1.3:   TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256
