### ISSUE TITLE
openssl 1.1.1k There may be a bug, and it cannot run normally in the armv7l system.

### ISSUE THREAD

**Issue by 0xdddddddd** [openssl/openssl#15770]
openssl 1.1.1k cannot run normally in armv7l 32bit lite version of linux system.
No matter whether you test openssl alone or test https tls through curl, it doesn't work properly.

The current version of openssl 1.1.1a can adapt to arm335x armv7l linux system.

I reported the problem in CURL. After 3 days of investigation, I finally found that it was an openssl error!

Refer to the bug report link: https://github.com/curl/curl/issues/7247

T**he following is my build command.**

```
setarch linux32 ./config -Wl,-rpath=/dynamic/ -Wl,--dynamic-linker=/dynamic/ld-linux-armhf.so.3 no-asm -march=armv7-a -D__ARM_MAX_ARCH__=7 zlib \
--with-zlib-include=/home/dev/Projects/Shattrath/arm/include --with-zlib-lib=/home/dev/Projects/Shattrath/arm/lib \
--prefix=/home/dev/Projects/Shattrath/arm \
--openssldir=/home/dev/Projects/Shattrath/arm/openssl --cross-compile-prefix=arm-none-linux-gnueabihf-
```

**Comment by paulidale** [comment]
We're going to need a lot more information.  Can you supply a minimal program that reproduces the problem?
Do the OpenSSL unit tests pass on the target platform?

It doesn't seem like you are specifying a target for the config command.  `linux-armv4` might be appropriate but you'll likely have to figure this out?

**Comment by X-Crack** [comment]
> We're going to need a lot more information. Can you supply a minimal program that reproduces the problem?
> Do the OpenSSL unit tests pass on the target platform?
> 
> It doesn't seem like you are specifying a target for the config command. `linux-armv4` might be appropriate but you'll likely have to figure this out?

linux-armv4 I have added this parameter, without the smallest test unit, directly compile it, curl the source code, and then make an htps request to reproduce the problem.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
