### ISSUE TITLE
syswrite() isn't allowed on :utf8 handles

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15805]
Bug reported submitted to openssl-users:
https://mta.openssl.org/pipermail/openssl-users/2021-June/013863.html

Fyi, i have `$PERL5OPT=-C` permanently in my environment, in
conjunction with `LC_ALL=en_US.utf8` this results in the build error
as below.  Prefixing `LC_ALL=C` fixes this.

````
  #?0|kent:src$ MYPREFIX=$HOME/$USR/opt/.ossl3 make -j4 openssl
  cd tls-openssl.git &&\
  if [ -f NULL ]; then git checkout `cat NULL`; fi &&\
  ./config --prefix=/home/steffen/usr-kent-linux-x86_64/opt/.ossl3 zlib-dynamic shared \
          no-deprecated no-async threads no-tests \
          -Wl,-rpath,'' &&\
  make &&\
   make install_sw &&  make install_ssldirs; \
  { git clean -fxd; git reset --hard HEAD;\
  git checkout arena-manager-null; } >/dev/null
  Switched to branch 'master'
  Your branch is up to date with 'origin/master'.
  Configuring OpenSSL version 3.0.0-beta2-dev for target linux-x86_64
  Using os-specific seed configuration
  Creating configdata.pm
  Running configdata.pm
  Creating Makefile.in
  syswrite() isn't allowed on :utf8 handles at /usr/lib/perl5/5.32/File/Copy.pm line 181.
  Switched to branch 'arena-manager-null'
````

**Comment by t8m** [comment]
>  Prefixing `LC_ALL=C` fixes this.

This basically undoes the -C option effect. I am not sure we need to fix this. Just do not use -C (unset PERL5OPT) or set LC_ALL=C when running.

**Comment by richsalz** [comment]
Maybe adding this to Configure is simplest?
```
$ENV{LC_ALL}='C';
```

**Comment by levitte** [comment]
> Maybe adding this to Configure is simplest?
> 
> ```
> $ENV{LC_ALL}='C';
> ```

Hmmm, isn't locale stuff done very early in perl, so setting that env variable inside a perl script has no effect?
I would assume that an explicit setlocale would do better:

``` perl
use POSIX qw(setlocale);
setlocale( LC_ALL, "C" );
```

**Comment by richsalz** [comment]
But if `configdata.pm` is run as a sub-process, it needs/wants the env var.  So do both I guess.

**Comment by levitte** [comment]
> But if `configdata.pm` is run as a sub-process, it needs/wants the env var.  So do both I guess.

Then the setlocale() call should be in `configdata.pm.in`.  Otherwise, there will be no effect when you run it directly from the command line.

**Comment by paulidale** [comment]
Why not just print an error if the locale isn't C?
I don't see a need for us to run in other locales.

**Comment by levitte** [comment]
> Why not just print an error if the locale isn't C?

Where would you do that?  In `Configure`?  In `configdata.pm`?  I don't think that's a good idea, considering that anyone might have a different locale by default, so that would force everyone to do something like this:

``` console
$ LANG=C ./configdata.pm
```

I don't see that flying...

**Comment by levitte** [comment]
I've experimented a bit, and setting locale to 'C' in `configdata.pm` doesn't help either.

I think this will indeed end with "Just don't do that", as @t8m suggested: https://github.com/openssl/openssl/issues/15805#issuecomment-863310097

**Comment by mattcaswell** [comment]
From the OP on openssl-users refering to the converstaion above:

> I think the thread comes to the right conclusion.  That $PERL5OPT
habit of mine seems to come from the years 2002/3, perl 5.8.0 /
5.8.1, and i instead changed all of mine and reomved $PERL5OPT
from my program environment.

**Comment by mattcaswell** [comment]
Issue was resolved in discussion above.
