### ISSUE TITLE
[OpenSSL] EC_KEY_generate_key FAIL Issue - pyelliptic==1.5.7

### ISSUE THREAD

**Issue by naveensinghal** [openssl/openssl#1580]
Hi @richsalz, @dot-asm, @levitte 

I have few issues related to PyOpenSSL & Pyelliptic packages in Python. Can you please help in resolving these, if possible ? (Tried a lot but couldn't figure out the exact reason still)

Python Code which initiates the Error:
```
print("Salt: %s" % salt)
server_key = pyelliptic.ECC(curve="prime256v1")
print("Server_key: %s" % server_key)
server_key_id = base64.urlsafe_b64encode(server_key.get_pubkey()[1:])

http_ece.keys[server_key_id] = server_key
http_ece.labels[server_key_id] = "P-256"
encrypted = http_ece.encrypt(data, salt=salt, keyid=server_key_id,
            dh=self.receiver_key, authSecret=self.auth_key)
```

Value of "Salt" is getting displayed in 100% of the cases. But
If value of "Server Key:" gets displayed, I see the the following EntryPoint Error because of http_ece.encrypt() call:
`AttributeError("'EntryPoint' object has no attribute 'resolve'",)`
(Ref. File Link: https://github.com/martinthomson/encrypted-content-encoding/blob/master/python/http_ece/__init__.py#L128 )

Otherwise I get the following Error because of pyelliptic.ECC() call:
`Exception('[OpenSSL] EC_KEY_generate_key FAIL ... error:00000000:lib(0):func(0):reason(0)',)`
(Ref. File Link: https://github.com/yann2192/pyelliptic/blob/master/pyelliptic/ecc.py#L214)

Other Details:
Partial Requirements.txt:
```
cryptography==1.5
pyelliptic==1.5.7
pyOpenSSL==16.1.0
```

**Command**: openssl version -a
**Output**: 
```
OpenSSL 1.0.1t  3 May 2016
built on: Sun May 15 19:23:55 2016
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"
```

The Django App is running on Debian8 Google Compute Engine VM Instance using Apache and mod_wsgi.

Can you please help in resolving this issue ?
Please let me know if any more information is required.

Thanks,

**Comment by richsalz** [comment]
Sorry, absolutely no idea, I’ve never looked at that python code.  Suggest you ask for help where those packages are maintained.  Or maybe openssl-users mailing list, see https://mta.openssl.org

**Comment by naveensinghal** [comment]
@richsalz Can you please add any member, if possible, who might be familiar with this code or who can help ?

I have sent a mail to openssl-users group too.

**Comment by richsalz** [comment]
Nobody is, as far as I know.
