### ISSUE TITLE
Ordinals not created

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15806]
Now that we are in beta the ordinals should have been populated in `util\libcrypto.num` and `util\libssl.num` as part of the `make update` in the release script. For some reason that didn't happen.

**Comment by levitte** [comment]
It didn't happen because it's done in the wrong spot in release.sh

**Comment by h-vetinari** [comment]
Shouldn't this now error the CI, philosophically speaking? I get that `beta1-dev` is pre-beta, but `beta2-dev` isn't anymore.

**Comment by h-vetinari** [comment]
Would it make sense to order the new functions alphabetically before assigning them a number? This would make `libcrypto.num` much more readable, IMO.

**Comment by levitte** [comment]
> Would it make sense to order the new functions alphabetically before assigning them a number? This would make libcrypto.num much more readable, IMO.

Not sure if that's worth the extra code, and I'm even less sure that I think it's a good idea to create that sort of expectation.

**Comment by h-vetinari** [comment]
> Not sure if that's worth the extra code, and I'm even less sure that I think it's a good idea to create that sort of expectation.

That expectation wouldn't have to be created anywhere IMO, and it doesn't even need to be done by the release script. Would a PR ordering the new functions in `libcrypto.num` be acceptable?

**Comment by levitte** [comment]
I wouldn't at all be surprised if people notice the alphabetical order, and when new symbols start getting added at the end, start asking why they aren't sorted alphabetically with those that come before. That's what I meant with "creating an expectation"....

**Comment by h-vetinari** [comment]
> 
> 
> I wouldn't at all be surprised if people notice the alphabetical order, and when new symbols start getting added at the end, start asking why they aren't sorted alphabetically with those that come before. That's what I meant with "creating an expectation"....

I get what you're saying, yet that file is clearly not sorted in its entirety, and the committers could easily enforce through review that new functions get sorted at the end as usual. What I'm suggesting is a one-off re-order of the new functions since the previous release, which I think wouldn't cause undue problems.
