### ISSUE TITLE
OSSL_PARAM_set_double() may fail on systems that do not define intmax_t

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#15815]
On systems that do not define `intmax_t`, we define our own variant like this:

https://github.com/openssl/openssl/blob/52e6c77ebc25590ac894ce67d83a02da07c6f01f/include/openssl/types.h#L236-L245

On 32-bit systems, `long` will typically be 32 bits, but `double` is often twice as large (64 bits).

This has an impact on `test/params_conversion_test.c` among others with the following stanza:

https://github.com/openssl/openssl/blob/52e6c77ebc25590ac894ce67d83a02da07c6f01f/test/recipes/04-test_params_conversion_data/native_types.txt#L76-L82

With these data, the following test fails:

https://github.com/openssl/openssl/blob/52e6c77ebc25590ac894ce67d83a02da07c6f01f/test/params_conversion_test.c#L288

This is due to this check in `OSSL_PARAM_set_double()`

https://github.com/openssl/openssl/blob/52e6c77ebc25590ac894ce67d83a02da07c6f01f/crypto/params.c#L1038

What's happening here, because `intmax_t` is 32 bits, is that the result of `(ossl_intmax_t)val` becaomes -2147483648, not 2147483648 (because that's how small ints work), and since `val` is the *double* 2147483648.0, they turn out not to be equal and `OSSL_PARAM_set_double()` fails.

**Comment by levitte** [comment]
This causes these failures on the VMS box I use:

```
        # INFO: 
        # Reading USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test.recipes.04-test_params_conversion_data]native_types.txt
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 83
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 107
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 115
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 123
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 131
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 139
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 155
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 203
        # ERROR: (bool) 'OSSL_PARAM_set_double(pc->param, d) == true' failed @ USER:[LEVITTE.TEST.openssl-3_0_0-beta1-dev.test]params_conversion_test.c;4:288
        # false
        # unexpected valid conversion from double on line 211
        # INFO: 
        # Completed 0 tests with 0 errors and 0 skipped
```

**Comment by rsbeckerca** [comment]
I had this issue on NonStop when using native float. Moving to IEEE float fixed it. That is a platform difference from 1.0.2/1.1.1 to 3.0.0.

**Comment by levitte** [comment]
BTW, this looks like a dumb bug:

https://github.com/openssl/openssl/blob/52e6c77ebc25590ac894ce67d83a02da07c6f01f/crypto/params.c#L1027-L1032

**Comment by levitte** [comment]
I may have got together a fix.  Testing it, will submit PR soon

**Comment by levitte** [comment]
Fix in #15816

**Comment by levitte** [comment]
With that fix, the failure on VMS is also gone

**Comment by paulidale** [comment]
> BTW, this looks like a dumb bug:
> 
> https://github.com/openssl/openssl/blob/52e6c77ebc25590ac894ce67d83a02da07c6f01f/crypto/params.c#L1027-L1032

???? What's the bug here ????

**Comment by levitte** [comment]
> > BTW, this looks like a dumb bug:
> > https://github.com/openssl/openssl/blob/52e6c77ebc25590ac894ce67d83a02da07c6f01f/crypto/params.c#L1027-L1032
> 
> ???? What's the bug here ????

That part of the condition will always be true. Now, if you insert `val <` into it, it could make sense...

**Comment by paulidale** [comment]
Ahh, yep it's a bug.
