### ISSUE TITLE
Packaging Question - OpenSSL 3.0.0 on NonStop

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#15813]
As the packager for NonStop builds, I have a question regarding FIPS and the best way to deliver it.

We currently have non-FIPS builds on ia64 for no threads, PUT threads, and SPT threads. These are three distinct builds delivered in `/usr/local-ssl3.0`, `/usr/local-ssl3.0_put`, and `/usr/local-ssl3.0_spt` respectively. Note that there is no way to change the name of a DLL in a client object once linked on this platform, although changing the directory is possible providing all of the rules for providers are followed for OpenSSL.

We also have have FIPS-enabled builds on x86 for no threads, PUT threads, and SPT threads. These are three distinct builds delivered in `/usr/local-ssl3.0`, `/usr/local-ssl3.0_put`, and `/usr/local-ssl3.0_spt` respectively.

The question is for x86 whether to have non-FIPS builds separately as whole packages as above, or deliver the FIPS providers as a separate package for each build. It would take up less space to do this, but might be more complex for the end-consumer. The net-workload for my team is roughly the same.

Note that we are encouraging people to build their own DLLs from tarballs, but that is not always (or often not) possible. Our end-customers typically would have access to our package site but not the tarball download site - something completely outside of my control.

I am looking for opinions on the most appropriate ways to accomplish this packaging. Our current package structure has the 3 packages for each platform.

Thanks,
Randall

**Comment by richsalz** [comment]
Why not just build `enable-fips` but not configure it by default (comment out the lines from the default config, or name it differently, etc.) Then people who *want* it just install the module and tweak the config.  Or create a small 'openssl-fips-enablement' that makes the changes to config and ships the module.

**Comment by rsbeckerca** [comment]
> 
> 
> Why not just build `enable-fips` but not configure it by default (comment out the lines from the default config, or name it differently, etc.) Then people who _want_ it just install the module and tweak the config. Or create a small 'openssl-fips-enablement' that makes the changes to config and ships the module.

I would love to have you come and talk to some of the people who want this. It is an interesting thought and I will see what I can figure out.

**Comment by richsalz** [comment]
Happy to talk if it will help, rsalz at akamai

**Comment by mattcaswell** [comment]
Note that non-stop is not one of the platforms that the project are going to be validating. Therefore although you could package the fips module and make it available, anyone using it still won't have a FIPS compliant installation. That is unless you were planning on validating it yourself based on our validation (which I expect a lot of organisations will be doing).

**Comment by richsalz** [comment]
They could do user- or vendor-affirmed tho.

**Comment by levitte** [comment]
The whole provider module architecture is designed so that provider modules can be separate, and are made such that both upward and downward compatibility is almost (*) certain.  If I was a packager, I would actually make the FIPS module into a separate package, installable separately.

-----
(*) if we decide to drop parts of the libcrypto\<-\>provider API, that won't hold true for older providers...  we don't predict something like that to happen in the foreseeable future, though

**Comment by richsalz** [comment]
Hence the "or create ... " comment I made.  Yeah, I would make the base package configured with `enable-fips` but not include it and the `.cnf` file(s) don't use it the FIPS provider.  And then a small add-on package that has the provider and modified `.cnf` file(s).

**Comment by mattcaswell** [comment]
> They could do user- or vendor-affirmed tho.

You are right. I stand corrected.

**Comment by rsbeckerca** [comment]
> 
> 
> > They could do user- or vendor-affirmed tho.
> 
> You are right. I stand corrected.

The affirmed stuff is going to be entirely the user issue. We are not going to be affirming it. If they really want to affirm anything, they should be building their own copy, in my view.

**Comment by rsbeckerca** [comment]
> 
> 
> Note that non-stop is not one of the platforms that the project are going to be validating. Therefore although you could package the fips module and make it available, anyone using it still won't have a FIPS compliant installation. That is unless you were planning on validating it yourself based on our validation (which I expect a lot of organisations will be doing).

I think a lot of organisations who use our packages will be validating it themselves based on your validation. My group does not have the financial resources to do that unless our community wants to fund it. I'm just making it work - and making sure it keeps working.

**Comment by paulidale** [comment]
How you build and package the FIPS provider will be determined by the instructions in the security policy (which isn't done yet).  No variations from these instructions will be permitted if the result is to be claimed FIPS compliant -- so if _no-threads_ isn't specified (and it won't be), you can't build FIPS with _no-threads_.

For an organisation doing their own validation, anything goes.

**Comment by rsbeckerca** [comment]
> 
> 
> How you build and package the FIPS provider will be determined by the instructions in the security policy (which isn't done yet). No variations from these instructions will be permitted if the result is to be claimed FIPS compliant -- so if _no-threads_ isn't specified (and it won't be), you can't build FIPS with _no-threads_.

I'm happy to wait for the security policy to be written.

However, it seems that there will be no FIPS compliance allowed on MPP architectures, where threading is not really relevant, but it's fine for SMP? I'm a bit surprised at that decision. Would you mind my asking what the rational is for that?

**Comment by richsalz** [comment]
Each validated configuration needs to undergo development, testing, and a great deal of lab involvement.  None of the FIPS sponsors were interested in a `no-threads` configuration.

**Comment by mattcaswell** [comment]
But does that still apply if an entry in the "Configurations" files for a particular platform has an entry saying "disable => ['threads']" - that's picked up automatically for your platform (as is the case for some of the nonstop platforms)? If that's the case then effectively you get "no-threads" automatically  without having to deviate from the build instructions.

**Comment by richsalz** [comment]
> But does that still apply if an entry in the "Configurations" files for a particular platform has an entry saying "disable => ['threads']"

I would say it depends on what the security policy says.  Which hasn't been made available yet.

**Comment by rsbeckerca** [comment]
> 
> 
> > But does that still apply if an entry in the "Configurations" files for a particular platform has an entry saying "disable => ['threads']"
> 
> I would say it depends on what the security policy says. Which hasn't been made available yet.

We have one user, a large technology firm whom I cannot directly identify, who uses both threading models for their product and would get their own certification. Other users do not use threading to our knowledge. We have surveyed but not received any other responses - not surprising as these are high-security environments. I know some of their situations, primarily in banking and financial situations, where threading is not used - instead, large numbers of independent processes (line drivers) are.

**Comment by paulidale** [comment]
> But does that still apply if an entry in the "Configurations" files for a particular platform has an entry saying "disable => ['threads']" - that's picked up automatically for your platform (as is the case for some of the nonstop platforms)? If that's the case then effectively you get "no-threads" automatically without having to deviate from the build instructions.

My understanding is that this would meet the requirements.  I'm not a FIPS lab or NIST so my opinion is worthless :)

**Comment by rsbeckerca** [comment]
> 
> 
> > But does that still apply if an entry in the "Configurations" files for a particular platform has an entry saying "disable => ['threads']" - that's picked up automatically for your platform (as is the case for some of the nonstop platforms)? If that's the case then effectively you get "no-threads" automatically without having to deviate from the build instructions.
> 
> My understanding is that this would meet the requirements. I'm not a FIPS lab or NIST so my opinion is worthless :)

I suppose I would arrange that. The standard build for `nonstop-nsx` could explicitly disable threads, while the `nonstop-nsx_spt_floss` and `nonstop-nsx_put` could explicitly enable threads without giving anyone the option. Perhaps that's the way to go. I do know there is a desire for FIPS on all of those three builds, and possibly the `nonstop-nsx_g` also. The last of those does not use threads - and cannot.

**Comment by rsbeckerca** [comment]
Our standard build is currently `nonstop-nsx_64`, which is typically configured using:
```
./Configure nonstop-nsx_64 --with-rand-seed=rdcpu enable-fips'
```
If I am understanding correctly, I would need to add `disable -> ['threads']` to that configuration. The threaded versions, say `nonstop-nsx_64_put`, is built as follows:
```
./Configure nonstop-nsx_64_put --with-rand-seed=rdcpu threads enable-fips "-D_REENTRANT"
```
It seems that I should changed the configuration to always specify `threads` and `-D_REENTRANT` so that the configuration would end up with:
```
./Configure nonstop-nsx_64_put --with-rand-seed=rdcpu enable-fips
```
If makes me wonder whether the `--with-rand-seed=rdcpu` should also be done by default because there's no way to add `enable-fips` without it, so if I am understanding, setting up something like:
```
./Configure nonstop-nsx_64_put_fips
```
should contain everything needed for a fips enabled build. Or am I getting ahead of myself?

**Comment by paulidale** [comment]
You're jumping ahead :)

This part of the security policy hasn't been written.
Neither has anything been written about entropy sources.

**Comment by rsbeckerca** [comment]
> You're jumping ahead :)
> 
> This part of the security policy hasn't been written.
> Neither has anything been written about entropy sources.
> 

True, but I did write the hardware entropy source and fips won't even configure with the old prngd.
