### ISSUE TITLE
ecdhp521 broken on AIX with enable-ec_nistp_64_gcc_128 

### ISSUE THREAD

**Issue by martin-schwenke** [openssl/openssl#15821]
If I build with:
```
../../Configure aix64-gcc enable-ec_nistp_64_gcc_128 && make
```
then OpenSSL builds successfully.

However, I see the following errors:
```
$ LD_LIBRARY_PATH=. apps/openssl speed ecdhp521 ecdsap521
Doing 521 bits sign ecdsa's for 10s: 11891 521 bits ECDSA signs in 6.58s 
ECDSA verify failure.  No ECDSA verify will be done.
ECDH computations don't match.
version: 3.0.0-alpha4
built on: built on: Fri Jun 18 04:33:52 2021 UTC
options:bn(64,64) rc4(char) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -maix64 -pthread -O -DB_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: N/A
```
This predates recent changes that add custom assembly code for p521 with this configuration option.  Those changes do not improve the situation.

This occurs on AIX 7.2 with gcc 8.1.0.

**Comment by martin-schwenke** [comment]
This happens on all the `3.0.0-alpha` versions I tried building.  I tried to check the most recent 1.1.1 version but it failed to build on AIX.

Unless someone with more clue says otherwise, this doesn't seem like a high priority because it has been broken for at least a year.  I suggest tagging it as a `master` branch issue - I can't see how to do that myself.

I'll point some AIX developers at this issue.

**Comment by kroeckx** [comment]
That option is known not to work on various systems, like big
endian. And it seems it is a big endian system.

**Comment by martin-schwenke** [comment]
@kroeckx Aha!  I should have read `INSTALL.md` first - I've just realised that this is mentioned there.

Should I apologise for the noise and close this?  Or should we use it as an opportunity to add something that causes the build to fail if `B_ENDIAN` is defined?

**Comment by martin-schwenke** [comment]
GitHub is too smart for my locked down browser and I can't attach a file here...

How about something like this?
```
From b053df0c103c5655ff65402ff2bc8a5ee8a47d4c Mon Sep 17 00:00:00 2001
From: Martin Schwenke <martin@meltin.net>
Date: Fri, 18 Jun 2021 16:35:16 +1000
Subject: [PATCH] ec: Fail build on big endian with enable-ec_nistp_64_gcc_128

I can't see way of making Configure fail but this at least makes the
build fail.

Signed-off-by: Martin Schwenke <martin@meltin.net>
---
 crypto/ec/ec_local.h | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/crypto/ec/ec_local.h b/crypto/ec/ec_local.h
index 693f21fa29..b658525341 100644
--- a/crypto/ec/ec_local.h
+++ b/crypto/ec/ec_local.h
@@ -508,6 +508,10 @@ int ossl_ec_GF2m_simple_field_div(const EC_GROUP *, BIGNUM *r, const BIGNUM *a,
                                  const BIGNUM *b, BN_CTX *);
 
 #ifndef OPENSSL_NO_EC_NISTP_64_GCC_128
+# if B_ENDIAN
+# error "Can not enable ec_nistp_64_gcc_128 on big endian systems"
+# endif
+
 /* method functions in ecp_nistp224.c */
 int ossl_ec_GFp_nistp224_group_init(EC_GROUP *group);
 int ossl_ec_GFp_nistp224_group_set_curve(EC_GROUP *group, const BIGNUM *p,
-- 
2.30.2

```

**Comment by mattcaswell** [comment]
> How about something like this?

Seems reasonable to me
