### ISSUE TITLE
`unsigned int` instead of `size_t` in `EVP_Q_mac()`

### ISSUE THREAD

**Issue by romen** [openssl/openssl#15839]
PR #14664 added `EVP_Q_mac()` as a wrapper around the `EVP_MAC` functionality to improve usability.

Unfortunately we did not notice that the parameter type of the last argument of the new function is inconsistent with the underlying function, as it swapped `size_t*` for `unsigned int*`.

This is evident when comparing `(unsigned int*) outlen` in

https://github.com/openssl/openssl/blob/openssl-3.0.0-beta1/include/openssl/evp.h#L1215-L1219

against `(size_t*) outl` in

https://github.com/openssl/openssl/blob/openssl-3.0.0-beta1/include/openssl/evp.h#L1223-L1224

**Comment by romen** [comment]
This comes with the OTC hold because it affects a public API.

@paulidale you reviewed #14664, do you believe we can get an exemption from the API freeze to correct this issue?

**Comment by paulidale** [comment]
The only confounding thought is that _unsigned int_ is probably wide enough for the MAC's output.

**Comment by romen** [comment]
Yeah, probably it is big enough, but I keep finding myself to have to declare a temporary uint variable just to collect that output and then assign it to the actual `size_t`output (in code based on our libssl code and apps).

I believe this would have been evident if we had tests for the wrappers comparing the output of the wrapper with the output of the underlying functions.

**Comment by t-j-h** [comment]
I think you are missing the context of the purpose of the function - it is to make it easy to write the **previous** function usage for the older style - and in that context not being size_t is actually consistent with the older API which wasn't size_t. 

That is the reason this was set that way.

Remember we actually don't have any reasonable context in which the output length of any of the crypto functions should actually need to be size_t for a single chunk of data on any platform (realistically).  For a 32-bit platform, processing more than 4Gb data in a single chuck isn't really a typical context.

There are higher level protocols for chunking data - and these are effectively low level raw crypto primitives.

**Comment by t8m** [comment]
> For a 32-bit platform, processing more than 4Gb data in a single chuck isn't really a typical context.

I agree with Tim with one small correction. With the outlen being unsigned int this limit applies to practically all 64 bit platforms as well as int/unsigned int is usually 32 bit on 64 bit platforms as well. But anyway, the limitation of the output size for MAC to be 32 bits is surely fine.

We could add an explicit check in the EVP_Q_mac() for the underlying implementation to not return more than UINT_MAX value but it would be more like a code correctness fix rather than a real bug fixed.

**Comment by paulidale** [comment]
I don't think any extra checking would be required -- no MAC will output anything like that much without being told to (and even then I think it's only KMAC that can currently).

Realistically, 100 bytes is more than enough and this fits in a signed char so there is a bit of head room.

**Comment by romen** [comment]
> I think you are missing the context of the purpose of the function - it is to make it easy to write the **previous** function usage for the older style - and in that context not being size_t is actually consistent with the older API which wasn't size_t.
> 
> That is the reason this was set that way.
> 
> Remember we actually don't have any reasonable context in which the output length of any of the crypto functions should actually need to be size_t for a single chunk of data on any platform (realistically). For a 32-bit platform, processing more than 4Gb data in a single chuck isn't really a typical context.
> 
> There are higher level protocols for chunking data - and these are effectively low level raw crypto primitives.

This seems to condemn new code to be written using antipatterns (not using size_t for sizes), for the sake of old code that is being refactored anyway to use this function, basically transferring the technical debt of older applications to new ones (i.e., old applications have to deal with the legacy of having defined internal interfaces using unsigned int for sizes instead of size_t, with this design choice we spread the cost of having to deal with unsigned int lengths and convert it to size_t for compliance with modern recommendations to new code).

EVP_Q_mac() is generally useful for new applications, 1 line instead of a dozen is always better! 😉

**Comment by t-j-h** [comment]
OTC: vote held that passed to change EVP_Q_mac and EVP_Q_digest

**Comment by paulidale** [comment]
But to not modify the wrappers HMAC, SHA1, SHA256, SHA512, SHA224 & SHA384.

**Comment by DDvO** [comment]
> But to not modify the wrappers HMAC, SHA1, SHA256, SHA512, SHA224 & SHA384.

Understood, as this would defeat their strict API backward compatibility, which was the reason to keep them.

**Comment by levitte** [comment]
See #15861
