### ISSUE TITLE
OpenSSL 3.0.0.0-b1 : entry point "EVP_PKEY_id" is missing in DLL "libcrypto-3.dll"

### ISSUE THREAD

**Issue by lllaffer** [openssl/openssl#15835]
I have been able to build openSSL

	3.0.0-a16
	3.0.0-a17

and to link/run cURL.

e.g.

```
curl 7.77.0 (i386-pc-win32) libcurl/7.77.0 OpenSSL/3.0.0 zlib/1.2.11 WinIDN libssh2/1.9.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets alt-svc libz
```

With
	3.0.0-b1
	
cURL claims 

	entry point "EVP_PKEY_id" is missing in DLL "libcrypto-3.dll"

What am I missing ?!

thx for your work
thx for your time

**Comment by paulidale** [comment]
The name was changed to `EVP_PKEY_get_id()` late in the piece.

There is a `#define EVP_PKEY_id EVP_PKEY_get_id` in evp.h which seems to have been missed.
Did you do a clean build after updating?

**Comment by lllaffer** [comment]
I forgot to mention: OpenSSL was built with 

	--api=1.1.1 ... for the moment w!thout >no-deprecated<


I use to build new versions in a dedicated, fresh & untouched environment:

	e.g .../3.0.0-b1/MSVC-32

Further I use to build with sequence

	configure
	nmake clean
	nmake
	
In
	...\OpenSSL\3.0.0-b1\MSVC-32\include\openssl\evp.h
	
there is actually a line

	# define EVP_PKEY_id EVP_PKEY_get_id

For

	..\OpenSSL\3.0.0-b1\MSVC-32\libcrypto-3.dll

Dependency Walker only reveals 

	EVP_PKEY_get_id

while

	...\OpenSSL\3.0.0-a17\MSVC-32\libcrypto-3.dll

only shows

	EVP_PKEY_id



thx for your attention

**Comment by t8m** [comment]
Do not use `--api=1.1.1` there is no point in doing that. Did you rebuild the curl against the beta1. It has to be rebuilt against the beta if you built it against an alpha release before. Otherwise it will not work.
