### ISSUE TITLE
Add tests for EVP_Q_* functions

### ISSUE THREAD

**Issue by romen** [openssl/openssl#15837]
Recently, new public functions have been added to improve usability:

- PR #14664 added `EVP_Q_mac()`
- PR #14741 added `EVP_Q_digest()`

Both were merged, but we missed they did not include tests for the new functions.
This is partially mitigated by the fact that they act as wrappers around the underlying functionality which has tests.

We should add the missing tests for the high level functionality, also as a way to exercise in more combinations the coverage of the underlying functions.

**Comment by romen** [comment]
@DDvO can you work on this?

**Comment by DDvO** [comment]
> @DDvO can you work on this?

I was about to start working on that, 
but found that I would only be able to come up with a rather basic test for each of the two functions.
So I suggest someone else does this who can provide some more in-depth tests with sufficient coverage.

**Comment by levitte** [comment]
The underlying functions for `EVP_Q_*` are already tested, and seeing that these functions aren't terribly complex, there's only so much that needs coverage.  I would suggest adding a few more tests in `test/evp_extra_test.c`.

**Comment by DDvO** [comment]
Would for instance
```
static int test_EVP_Q_mac(void)
{
    static unsigned char static_md[SHA_DIGEST_LENGTH];
    size_t outlen;
    char *p;

    /* Test EVP_Q_mac with NULL key. */
    p = pt(EVP_Q_mac(NULL /* libctx */, "HMAC", NULL /* propq */, "sha1",
                     NULL /* params */, NULL /* key */, 0 /* keylen */,
                     test[4].data, test[4].data_len,
                     static_md, sizeof(static_md), &outlen),
                     SHA_DIGEST_LENGTH);
    return TEST_ptr(p) && TEST_int_eq(outlen, SHA_DIGEST_LENGTH)
        && TEST_str_eq(p, test[4].digest);
}
```
in `test/hmactest.c` make sense?
Unfortunately, the existing test data there does not include a key.

**Comment by romen** [comment]
I would also include some tests that compare the output of EVP_Q_mac with the output of the underlying functions and the convenience macros for compatibility with legacy.

This kind of testing I am proposing does admittedly little regarding the correctness of the output (at least for now), but is a way to formalize that legacy code, EVP_Q_* and the more elaborated way that uses EVP_MAC functions all are supposed to be backward/forward compatible in their behavior.
This will prevent us from changing something in any of these 3 points of duplication without noticing that we are breaking some promises.

**Comment by paulidale** [comment]
@DDvO, that's exactly what I had in mind (with TEST_mem_eq not TEST_str_eq).  I don't think much depth is needed here, just a single basic known answer test for each of the two calls is enough.  The algorithm is tested elsewhere, just the function interface needs testing.

Perhaps use something other than HMAC since that path is well covered already.  CMAC is the obvious choice since it is different but KMAC or GMAC would be reasonable picks.

**Comment by paulidale** [comment]
I've hooked these two calls into the evp tests in #15888.  We should be getting fairly comprehensive testing from this.

**Comment by levitte** [comment]
I find it a little over the top to hook it into `test/evp_test.c`.  After all, `EVP_Q_mac` *is just wrappers*, so what you end up doing is essentially to run the exact same EVP_MAC functions twice.  The same goes for `EVP_Q_digest`, but it's a wrapper of a wrapper, which is probably the reason why `EVP_Digest` is tested in `test/evp_extra_test.c`.

**Comment by paulidale** [comment]
It also checks that **all** the different MACs can be run via the EVP_Q_mac call.  That's not going to happen if the is relegated to evp_extra_test or equivalent.

Including SipHash found a problem with the calling code I began with.  I wouldn't have found the issue otherwise because no other MAC exposed it and SipHash wouldn't have been something I'd have chosen.

**Comment by DDvO** [comment]
The further this discussion has come, the more I see that this topic is not my turf - 
I can treat crypto algs only as a black box, and luckily this is sufficient for the use cases I am actually involved with.
So I'm glad that @paulidale has taken over providing some (in my limited understanding) pretty general test cases.
@romen, since you seem to have specific ideas which tests to add, I wonder why you did not do that yourself.

**Comment by romen** [comment]
@DDvO Just time constraints at the moment, otherwise, yes, I would have opened just a pull request. For now I am happy to review a PR with some tests and give suggestions, and when I will be able to I will integrate with my own PR if I think there is more that I would like to be tested!

In general, I hear @levitte argument that "this functionality is already tested through the underlying functions elsewhere", what I would like to be tested here is actually API testing rather than functionality testing.

We have the complex EVP_MAC way, the quick EVP_Q_mac way, and the "legacy macros" way of achieving the same result to compute hmac, cmac, etc. through different entry points.
As we promise these entry points are equivalent, we should test that this expectation is met (for hmac, cmac, etc.) and prevent that future changes break things in subtle ways.

Otherwise we risk ending up with other cases of documenting one thing when functions are created, altering functionality in subtle ways, discovering years later inconsistencies between docs and code and setting for the latter because "this was never enforced/tested".
Whenever this happens, we send a very bad message about our documentation and the guarantees of its consistency.

One way to prevent this to happen again (and the reason why I am suggesting it) is, when we document "this is just a wrapper for X", "Y called with such and such arguments is equivalent to Z", etc., that we also write tests that bind our intention to what the code actually does.

**Comment by t8m** [comment]
I suppose the MAC and digest tests are quick enough that it really does not matter whether we test them twice or not.

**Comment by paulidale** [comment]
Yes, they are very quick.

Public key and KDF tests might need to be more discerning.
