### ISSUE TITLE
ossl-modules folder is not versioned, should it be?

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#15849]
Hello,

While porting openssl 3.0 beta1 to QNX, I noticed that the engines directory is versioned, but not the ossl-modules one. My first question is: should it be? I anticipate that if we would like to support multiple versions of openssl in parallel that it would be convenient if that folder was `ossl-modules-3` (3_1, 3_2, etc. for future versions).

If those modules are providers, why not name the folder openssl-providers (openssl-engines for the other one since you are starting anew) to make things clearer what these folders are and contain?

Minor additional question, what is the purpose of loader-attic.so?

```
|   `-- x86_64/
|       `-- usr/
|           |-- bin/
|           |   |-- c_rehash*
|           |   `-- openssl*
|           `-- lib/
|               |-- engines-3/
|               |   |-- devcrypto.so*
|               |   `-- loader_attic.so*
|               |-- libcrypto.a
|               |-- libcrypto.so -> libcrypto.so.3*
|               |-- libcrypto.so.3*
|               |-- libssl.a
|               |-- libssl.so -> libssl.so.3*
|               |-- libssl.so.3*
|               |-- ossl-modules/
|               |   `-- legacy.so*
|               `-- pkgconfig/
|                   |-- libcrypto.pc
|                   |-- libssl.pc
|                   `-- openssl.pc
```

**Comment by paulidale** [comment]
Part of the provider design was for them to function across versions of OpenSSL (and vice versa).  Hence the somewhat convoluted provider <-> libcrypto interface.

Time will tell how well this was achieved.

**Comment by dlegaultbbry** [comment]
Given that eventually you'll move openssl 4.0 (I presume) then these 3.X modules wouldn't necessarily work with libcrypto.so.4? So on a system where you have both 3.X and 4.X the folders would overwrite themselves since the provider binaries are not versioned.

**Comment by levitte** [comment]
This is fine, as far as we can see.  The intention is that what's supported is determined by what is offered in OSSL_DISPATCH tables, not by a version number.  The provider entry point is, as far as we can tell, frozen for the foreseeable future, regardless of versions

**Comment by dlegaultbbry** [comment]
Ok, sounds good!
