### ISSUE TITLE
Building for macOS/Darwin with `@loader_path`?

### ISSUE THREAD

**Issue by atomicbird** [openssl/openssl#15856]
I'm helping out with a Mac framework that's currently using a very old version of OpenSSL, where the framework depends on a configuration that doesn't seem to be currently supported.

Right now, the framework builds `libssl.dylib` and `libcrypto.dylib` and embeds them in its bundle, then dynamically loads them at run time. This works because it uses `--prefix="@loader_path/../Frameworks"` in its config options. The `@loader_path` is resolved by Darwin based on the framework's bundle, so the libraries work regardless of the bundle's absolute path. The libraries are found in the bundle at `Contents/Frameworks/`, but the bundle can be anywhere in the filesystem.

I see that [some time ago](https://github.com/openssl/openssl/commit/5482dac9f4de7eb73d1b9c776be9495735f7e299#diff-6defafa2caa65304173956e3fbc26b6947c50bc769c08c3da32c1032fa6519d4R581), `--prefix` was changed so that only absolute paths are allowed. This obviously breaks the approach described above. [`INSTALL.md`](https://github.com/openssl/openssl/blob/master/INSTALL.md) mentions a `-framework` option but it doesn't sound like it does what I need.

What can I do to build a version of 1.1.1 that I can use in a Mac framework bundle?

**Comment by levitte** [comment]
I assume that what you did was with OpenSSL prior to 1.1.0, right?  How did that work when installing, like `make install_sw`?  That make target has statements that would end up looking like this in 1.0.2:

```
cp whateverfile @loader_path/../Frameworks/include/openssl/whateverfile
```

**Comment by atomicbird** [comment]
Correct, the current project uses OpenSSL 1.0.2. As far as I can tell (the people who originally set this up have long since moved on to other things), it does `make build_libs` to build the dylibs. It follows that with `install_name_tool` to update instal names, then simply copies the libraries to the necessary locations. The Makefile install targets are never used.

**Comment by levitte** [comment]
> The Makefile install targets are never used.

Like I suspected...

I don't recall what it was that made us decide to enforce absolute paths for `--prefix`...  the problem that I see now is that a relative path makes for pretty surprising results when using the install targets, *especially* if you also consider the use of DESTDIR (this depends on the prefix being an absolute path, there's really no way around that).

**Comment by atomicbird** [comment]
Does that mean that since I'm not using the install targets, I could delete that check from `./Configure`? I didn't know why it was added and I didn't want to delete it without knowing.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
