### ISSUE TITLE
how to get the function pointer of algorithm in default provider from third party provider?

### ISSUE THREAD

**Issue by lgynju** [openssl/openssl#15876]
I am trying to build a third-party provider based on OpenSSL3.0, what I focus on is RSA-related in SIGNATRUE operation, but some algorithms in the KEYMANAGMENT operation are also needed, I just want to do RSA in SIGNATURE, and others by default. 

The following is my solution:
I fetch the algorithm by evp_**_fetch, but I just get a void* pointer, then I copy the definition of that (for example, evp_keymgmt_st) into my source file, finally, then I get the function pointer.

May it is a little tricky, but I don't know what is the best way,
Could anyone tell me what is the proper way to do it?

**Comment by t8m** [comment]
You always need to implement key management in a provider that needs to work with public key algorithms. Otherwise there is no way how to transfer the key data inside/outside your provider. What you describe you're doing is unfortunately just a hack that uses private data structures that can be changed at any time.

**Comment by mattcaswell** [comment]
It's a little unclear to me what you are trying to achieve. If I read what you wrote correctly then I *think* you are trying to implement a provider that just does RSA, while still being able to use all the other algorithms from the default provider at the same time.

If that is what you meant then simply just implement RSA in your provider. The application should then load both your provider and the default provider. Using a global property they can prefer your provider over the default one. E.g. if your provider is called "myprovider" then you can set a global property string of "?provider=myprovider". This will prefer algorithms from "myprovider", but if that doesn't have anything suitable then it will use the default provider.

**Comment by lgynju** [comment]
> It's a little unclear to me what you are trying to achieve. If I read what you wrote correctly then I _think_ you are trying to implement a provider that just does RSA, while still being able to use all the other algorithms from the default provider at the same time.
> 
> If that is what you meant then simply just implement RSA in your provider. The application should then load both your provider and the default provider. Using a global property they can prefer your provider over the default one. E.g. if your provider is called "myprovider" then you can set a global property string of "?provider=myprovider". This will prefer algorithms from "myprovider", but if that doesn't have anything suitable then it will use the default provider.

Thanks for your reply, that is what I mean and I am doing now, I did use the `?provider=myprovider`, but the question is the OpenSSL core will check whether the provider of key management and signature is the same provider, so I need to implement the key management operation, which I don't expect. so I am trying to find some way to get the key management algorithm from my provider.

**Comment by mattcaswell** [comment]
>  so I need to implement the key management operation, which I don't expect. so I am trying to find some way to get the key management algorithm from my provider.

You *must* implement both. You cannot reuse the key management from another provider.

**Comment by Yogaraj-Alamenda** [comment]
Earlier engine interface provides default OpenSSL implementation to be used within 3rd party engines. This is useful in cases like fallback where engine implementation fails (eg: hardware error). Do you mean to say with providers we cannot achieve this ?

**Comment by paulidale** [comment]
Yes it can be achieved.  Fetch the algorithm from the default provider, parse the OSSL_ALGORITHM table and call the appropriate function if you need to.

**Comment by mattcaswell** [comment]
> Yes it can be achieved. Fetch the algorithm from the default provider, parse the OSSL_ALGORITHM table and call the appropriate function if you need to.

I wouldn't recommend that route unless you really know what you are doing. As an alternative you can just fetch the algorithm in a different libctx and call the appropriate EVP routines directly.

**Comment by Yogaraj-Alamenda** [comment]
Thanks for the information @mattcaswell  @paulidale .

**Comment by wenkema** [comment]
Hi @mattcaswell,
I have some questions:
1 as @lgynju 's said, we want to build a third-party provider,but we only focus on signature operation, must we implement the keymgmt operation in our provider? 
2 can we only implement the signature operation and don't implement the keymgmt operation?(for example, use the default provider keymgmt)
3 what does this mean?  "As an alternative you can just fetch the algorithm in a different libctx and call the appropriate EVP routines directly."  Can we use this method to fetch default provider keymgmt operation in our provider and by this way we don't need to implement our keymgmt?  

thanks

**Comment by mattcaswell** [comment]
> 1 as @lgynju 's said, we want to build a third-party provider,but we only focus on signature operation, must we implement the keymgmt operation in our provider?

The purpose of implementing a key manager is to translate a key into a format that the provider understands. Each provider that wants to use such keys *must* implement its own key manager.

> 2 can we only implement the signature operation and don't implement the keymgmt operation?(for example, use the default provider keymgmt)

No. You must implement keymgmt.

> 3 what does this mean? "As an alternative you can just fetch the algorithm in a different libctx and call the appropriate EVP routines directly." Can we use this method to fetch default provider keymgmt operation in our provider and by this way we don't need to implement our keymgmt?

No. This answer was in reference to the question about falling back to another provider if the current provider cannot fulfil the operation.
