### ISSUE TITLE
alpha17->beta1 regression: unexpected X509_get_pubkey() failure under "FIPS mode"

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#15884]
I have a testcase that generates a CA certificate on the fly and outputs it in PEM format, calls EVP_default_properties_enable_fips(NULL, true), reads the PEM data back into a new X509 via PEM_read_bio_X509(), and then calls X509_get_pubkey().

The certificate is different each time (though structurally the same), but here is one example:
```
-----BEGIN CERTIFICATE-----
MIIETjCCAzagAwIBAgIEYNN7uTANBgkqhkiG9w0BAQsFADB0MQswCQYDVQQDEwJD
QTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5DMQwwCgYDVQQHEwNSVFAxDzANBgNV
BAoTBk5ldEFwcDENMAsGA1UECxMEU0RGSTEdMBsGCSqGSIb3DQEJARYOcnRwQG5l
dGFwcC5jb20wHhcNMjEwNjIzMTgyMTQ1WhcNMjEwNzIzMTgyMTQ1WjB0MQswCQYD
VQQDEwJDQTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5DMQwwCgYDVQQHEwNSVFAx
DzANBgNVBAoTBk5ldEFwcDENMAsGA1UECxMEU0RGSTEdMBsGCSqGSIb3DQEJARYO
cnRwQG5ldGFwcC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDP
4pYr6pBr0ATLBap6sf4qeiphSG1ffgEGMKG5uZVaizUcd2HcEi8L9CHfFA9zmRC9
3otERHmQCSgvLEoefPAohTmt7KDuLYdn7ZcKGza0XocrrLVPntc5t7gvufAQvboj
oTlvNSFVqT8ti7Owx6ub6wIQGL4Hnl18s2tk3dK39LZ+GIF7l1yyX6T4wj5NecIE
Ez26NglpD12ZYjExsG1HxzKcYq8bykaKxGy3K545FGNHN6VTx2XdDWPoFwnhFaX4
awtdIny09ru4nbd6Vmtim3Z53/MkCmijg3ShremPFKfBcbFe2n/0tIPMnvCxNGbT
f5gWoAj7pBIlvORpCum/AgMBAAGjgecwgeQwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFCDD3ih6cLQFqfQxn2BM4nigdE9gMIGhBgNV
HSMEgZkwgZaAFCDD3ih6cLQFqfQxn2BM4nigdE9goXikdjB0MQswCQYDVQQDEwJD
QTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5DMQwwCgYDVQQHEwNSVFAxDzANBgNV
BAoTBk5ldEFwcDENMAsGA1UECxMEU0RGSTEdMBsGCSqGSIb3DQEJARYOcnRwQG5l
dGFwcC5jb22CBGDTe7kwDQYJKoZIhvcNAQELBQADggEBAIOTkKYVtbLCdBo9QPJt
fLZPkgItqEVPI/Aae3i6eo68D818Y6+Qq/o9rAGWqnqaFeaMUEMs0/fpQKGiaboq
jNwuiPXazSVQOp7n2y4l+lM3LSuOnyse21TJ9vhmhHkLa0UcPWpnDClBDhDDW/74
RqWQuZ0jpviKArgxorVI/nxKBIcHCssLYzaEAlRwYxZK4Y3GfYcbH1R5Bl1xVUer
sXbSCU+492xxH8bXGK5otI1EtrLflof4D6YjCqN1wLwA0WJi+RnMPF+NIcO2Vin0
LwnZBb8FtrUIiNE38oQdXh20mNqUTD9Bn2/f4Y5nam5EHAQw6OvIKY1XpGsqVF5f
IUQ=
-----END CERTIFICATE-----
```

Here's what I was able to fish out of the error queue after X509_get_pubkey() returned NULL (the return value of the preceding call to PEM_read_bio_X509() *is* checked and was non-NULL.):

```
205BCE8A837F0000:error:1D880106:ENCODER routines:OSSL_ENCODER_CTX_new_for_pkey:reason(524550):crypto/encode_decode/encoder_pkey.c:304:The passed EVP_PKEY must be assigned a key
205BCE8A837F0000:error:1D880106:ENCODER routines:OSSL_ENCODER_CTX_new_for_pkey:reason(524550):crypto/encode_decode/encoder_pkey.c:304:The passed EVP_PKEY must be assigned a key
205BCE8A837F0000:error:03000072:digital envelope routines:X509_PUBKEY_get0:decode error:crypto/x509/x_pubkey.c:441:
```

**Comment by mattcaswell** [comment]
> I have a testcase that generates a CA certificate on the fly and outputs it in PEM format, calls EVP_default_properties_enable_fips(NULL, true), reads the PEM data back into a new X509 via PEM_read_bio_X509(), and then calls X509_get_pubkey().

You don't mention anywhere here that actually *load* the FIPS provider...do you do that?

**Comment by jwalch** [comment]
Apparently I had not. I forgot to mention or check for it because we drive it through the config file. Evidently for this particular test binary the fipsinstall step wasn't happening correctly - thus preventing the provider from getting loaded correctly during startup - and this is the only testcase within said binary that doesn't behave correctly under those circumstances. If I'd had multiple FIPS-dependent testcases falling over I surely would have suspected that type of failure mode sooner. So I'm assuming what actually happened was that between alpha17 and beta1 something changed such that the X509_get_pubkey() call can no longer be serviced by the base provider. Otherwise I'm at a loss as to how this worked before. At any rate, as I have a solution I'm content to close this.

**Comment by mattcaswell** [comment]
> between alpha17 and beta1 something changed such that the X509_get_pubkey() call can no longer be serviced by the base provider. 

X509 parsing was actually falling back to legacy keys in earlier alphas. We fixed that to use provider side keys. In other words in the earlier alpha the base provider wasn't being used at all in your test. It is now.
