### ISSUE TITLE
OpenSSL-3.0.0-beta1 compile breaks under Standard Posix Threads (NonStop)

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#15885]
The definitions associated with the change at lines 60-64 in `crypto/threads_pthread.c` are not defined for all Standard Posix Thread (SPT) implementations.

https://github.com/openssl/openssl/blob/86ff7cf2a6cdf26f2ba7e64db6fe5c92c64bf9ac/crypto/threads_pthread.c#L60-L64

In particular, `PTHREAD_MUTEX_NORMAL` is undefined. I will look into fixing this ASAP.

**Comment by rsbeckerca** [comment]
I did not catch this earlier because our threaded builds were not working :( and I had an error in our CI pipeline.

**Comment by richsalz** [comment]
So presumably:
```
#ifndef PTHREAD_MUTEX_NORMAL
# define PTHREAD_MUTEX_NORMAL PTHREAD_MUTEX_DEFAULT
#endif
```

**Comment by rsbeckerca** [comment]
> 
> 
> So presumably:
> 
> ```
> #ifndef PTHREAD_MUTEX_NORMAL
> # define PTHREAD_MUTEX_NORMAL PTHREAD_MUTEX_DEFAULT
> #endif
> ```

I don't even have that on the box. Need to define out the whole thing. Problem is that the build is worse than I thought. `netdb.h` is being referenced in multiple places different, that I have to fix as well.

**Comment by rsbeckerca** [comment]
Looks like it was relatively simple. I tried to document the situation in the code. Still under build/test cycle.

**Comment by rsbeckerca** [comment]
@richsalz I need some help. 
```
          ret = ctx->loader->close(ctx->loader_ctx);
                             ^
"/home/ituglib/randall/openssl-3.0/crypto/store/store_lib.c", line 516: error(1565):
          struct "ossl_store_loader_st" has no field "spt_close"
```
It looks like `close` is redirected to `spt_close`. I'm wondering whether I need to adjust the redirection where `close` is defined.

**Comment by rsbeckerca** [comment]
What I had to do is:
```
    if (ctx->fetched_loader == NULL)
# if defined (OPENSSL_TANDEM_FLOSS) && defined (_SPT_MODEL_)
   /* NonStop SPT redirects close to spt_close causing a compile failure. */
#  undef close
# endif
        ret = ctx->loader->close(ctx->loader_ctx);
# if defined (OPENSSL_TANDEM_FLOSS) && defined (_SPT_MODEL_)
#  define close(filedes) spt_close(filedes)
# endif
```

**Comment by richsalz** [comment]
That undef/redef is bad. It is really depending on the internals of the system header file.  Yuk.
