### ISSUE TITLE
dsa_do_sign free - uniniitialize variable on FIPS mode

### ISSUE THREAD

**Issue by aradyaron** [openssl/openssl#15893]
https://github.com/openssl/openssl/blob/d11e6a4410d5aae70ad545d085d344644c33d9cc/crypto/dsa/dsa_ossl.c#L160

when fips_check_dsa_prng  fails - and goto error is called,

the bignums {m,xr} are freed without being initialized

**Comment by mattcaswell** [comment]
The code you are pointing at is EOL and no longer supported by the project. This problem does not exist in currently supported code.
