### ISSUE TITLE
Build error in visual studio 2017

### ISSUE THREAD

**Issue by gvarun25** [openssl/openssl#15896]
hi

i am facing build error in windows  visual studio 2017.

**ERROR **

`4>libeay32MT.lib(txt_db.obj) : error LNK2001: unresolved external symbol __iob_func`
`4>libeay32MT.lib(ui_openssl.obj) : error LNK2001: unresolved external symbol __iob_func`
`4>ssleay32MT.lib(t1_enc.obj) : error LNK2001: unresolved external symbol __iob_func`
`4>ssleay32MT.lib(d1_both.obj) : error LNK2001: unresolved external symbol __iob_func`
`4>ssleay32MT.lib(s3_srvr.obj) : error LNK2001: unresolved external symbol __iob_func`
`4>libeay32MT.lib(cryptlib.obj) : error LNK2001: unresolved external symbol __iob_func`

how to solve is error?

Thanks!

**Comment by mattcaswell** [comment]
You need to give us a bit more to go on. What version of OpenSSL are you using? What build steps did you take to get to this point?
