### ISSUE TITLE
__owur question

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15902]
Some functions from the OpenSSL public API have an `__owur` attribute that raises a warning when its result is not checked.

This warning is guarded by `-DUNUSEDRESULT_DEBUG` define.

I wonder why, e.g. `EVP_EncryptInit` has such an attribute while `EVP_EncryptInit_ex` doesn't. It looks suspicious to me. 
Also I'd like to rename the `-DUNUSEDRESULT_DEBUG` to `-DOPENSSL_UNUSEDRESULT_DEBUG`.

**Comment by beldmit** [comment]
The commented `__owur`s were introduced by @snhenson...
 
https://github.com/openssl/openssl/commit/ae551760917614647ad6fbacec6e4c1b495a94cf

**Comment by t8m** [comment]
These seem to me like possible Post 3.0 changes.

**Comment by beldmit** [comment]
I understand your reasons but I have my own at least to uncomment the commented ones and see what happens...

**Comment by beldmit** [comment]
The necessary changes looks pretty small. All the unchecked values are found only in apps.

**Comment by paulidale** [comment]
I suspect that quite a number of user applications don't check the return.  Making this change will break them.

**Comment by tomato42** [comment]
And because they don't check the returns they are affected by the introduction of the legacy provider.
They're using the OpenSSL API incorrectly, why we should accommodate them?

**Comment by beldmit** [comment]
> I suspect that quite a number of user applications don't check the return. Making this change will break them.
Let me disagree.

1. They have to check it to avoid being crashed
2. It is a compile-time check and to enable this check they need to add special compile-time settings

**Comment by mattcaswell** [comment]
> I suspect that quite a number of user applications don't check the return. Making this change will break them.

Unlikely. The check only occurs if the application explicitly defines `UNUSEDRESULT_DEBUG`. We do this for our own code (if you pass `--strict-warnings`) - but my guess is most applications don't do this. And if they do they are probably interested in this kind of failure.

**Comment by paulidale** [comment]
I suspect the --strict-warnings option is used commonly.  Perhaps errantly...

**Comment by beldmit** [comment]
Anyway it doesn't raise any errors for the external application without the #define.

@paulidale, the results are available in #15902. Would you mind to review?

**Comment by paulidale** [comment]
This is #15902....
I'm off to sleep now.

**Comment by mattcaswell** [comment]
> I suspect the --strict-warnings option is used commonly

That doesn't matter. `--strict-warnings` is only relevant for compiling our own code. It adds the `UNUSEDRESULT_DEBUG` define when building OpenSSL. But we regularly test that so it is fine. External applications would have to explicitly define `UNUSEDRESULT_DEBUG` in some other way (which I guess most do not).

**Comment by beldmit** [comment]
Sorry, I mean #15905

**Comment by mattcaswell** [comment]
As per my comment in #15905, this is now a post 3.0 thing. Removing OTC hold.
