### ISSUE TITLE
Windows: nmake fails due to incorrectly generated makefile

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#1591]
nmake -f makefile build_libs

Fails with:
NMAKE : fatal error U1073: don't know how to make '"Configurations\windows-makefile.tmpl Configurations\common.tmpl"'

The problem seems to be with the double quotes in the following part of the generated makefile:
configdata.pm: "$(SRCDIR)\Configure" "Configurations\windows-makefile.tmpl Configurations\common.tmpl" "build.info" ...

**Comment by levitte** [comment]
Yup, we found out.  It's been fixed with #1590, which has now been merged into the affected branches.
