### ISSUE TITLE
OpenSSL-3.0.0-beta1 - configure failed for Windows cross compile of target nonstop-nsx

### ISSUE THREAD

**Issue by simon-p-r** [openssl/openssl#15919]
Hi

I am getting this error when attempting to cross compile from Windows to HPE Nonstop,

```
E:\Dev\c\nonstop\openssl>perl Configure nonstop-nsx --prefix=<some path> --openssldir=/usr/local/ssl --with-rand-seed=rdcpu no-threads

Configuring OpenSSL version 3.0.0-beta1 for target nonstop-nsx

Failure!  Makefile wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.


******************************************************************************
This perl implementation doesn't produce Unix like paths (with forward slash
directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.32.1 for MSWin32-x64-multi-thread
******************************************************************************
```

**Comment by t8m** [comment]
Was this working on 1.1.1?

**Comment by mattcaswell** [comment]
You might like to try this under msys2, with the msys2 version of perl. That's a windows perl implementation that generates the UNIX style paths that the error is complaining about.

But, be warned, I think you are in uncharted territory attempting to cross compile for nonstop from windows.

**Comment by rsbeckerca** [comment]
> 
> 
> You might like to try this under msys2, with the msys2 version of perl. That's a windows perl implementation that generates the UNIX style paths that the error is complaining about.
> 
> But, be warned, I think you are in uncharted territory attempting to cross compile for nonstop from windows.

I do not think this is possible - not for a lack of trying on my part. You could try `nonstop-nsx_64` at the very least, since that is the one ITUGLIB uses as its base version.

**Comment by rsbeckerca** [comment]
Also, `no-threads` is redundant for `nonstop-nsx` at 3.0.0:
```
    'nonstop-nsx' => {
        inherit_from     => [ 'nonstop-common',
                              'nonstop-archenv-x86_64-oss',
                              'nonstop-ilp32',
                              'nonstop-efloat-x86_64' ],
        disable          => ['threads'],
    },
```

**Comment by rsbeckerca** [comment]
Well, I'm gobsmacked. On Cygwin:
```
$ ./Configure nonstop-nsx_64 --with-rand-seed=rdcpu
Configuring OpenSSL version 3.0.0-beta2-dev for target nonstop-nsx_64
Creating configdata.pm
Running configdata.pm
Creating Makefile.in
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************
```

**Comment by rsbeckerca** [comment]
Make does not work out of this box on this, because the default CygWin path is pointing to the c99 implementation from CygWin. You will need to specify PATH to point to the HP NonStop compiler location first, as in:
```
export PATH=/cygdrive/c/Program\ Files\ \(x86\)/HPE\ NonStop/L16.05/usr/bin:$PATH
```
However, `make` still reports problems with the `-MT` option. This is likely because `makedepend` under CygWin is not always compatible with with the NonStop c99 compiler.
```
c99  -I. -Iinclude -Iapps/include  -g -O2 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_neutral_library -Wverbose -Wtarget=tns/x -Wsystype=oss -Wlp64 -WIEEE_float  -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_VPROC= -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED=1 -D_TANDEM_SOURCE -DB_ENDIAN -D_TANDEM_ARCH=3 -DNDEBUG  -MMD -MF apps/lib/libapps-lib-app_libctx.d.tmp -MT apps/lib/libapps-lib-app_libctx.o -c -o apps/lib/libapps-lib-app_libctx.o apps/lib/app_libctx.c
c99.exe: error: Invalid option: -M.
```
Maybe there is a mechanism to change this option that I do not know at this point. The build works fine in OSS.

**Comment by rsbeckerca** [comment]
Investigation continues: `-MT` is a `gcc` extension and is not supported by `c99`. It is interesting that when the Makefile is generated on NonStop, a sample recipe is:
```
apps/lib/libapps-lib-app_libctx.o: apps/lib/app_libctx.c
        $(CC)  -I. -Iinclude -Iapps/include  $(LIB_CFLAGS) $(LIB_CPPFLAGS)  -c -
```
while the same file when generated for a cross compile on Windows is:
```
apps/lib/libapps-lib-app_libctx.o: apps/lib/app_libctx.c
        $(CC)  -I. -Iinclude -Iapps/include  $(LIB_CFLAGS) $(LIB_CPPFLAGS) -MMD
-MF apps/lib/libapps-lib-app_libctx.d.tmp -MT $@ -c -o $@ apps/lib/app_libctx.c
        @touch apps/lib/libapps-lib-app_libctx.d.tmp
        @if cmp apps/lib/libapps-lib-app_libctx.d.tmp apps/lib/libapps-lib-app_l
ibctx.d > /dev/null 2> /dev/null; then \
                rm -f apps/lib/libapps-lib-app_libctx.d.tmp; \
        else \
                mv apps/lib/libapps-lib-app_libctx.d.tmp apps/lib/libapps-lib-ap
p_libctx.d; \
        fi
```
It appears that the Windows template is still assuming dependencies will be rebuilt, while UNIX does not; but that looks like two separate problems here.

**Comment by levitte** [comment]
> It appears that the Windows template is still assuming dependencies will be rebuilt, while UNIX does not; but that looks like two separate problems here.

Not quite, re Unix.  However, we have so far only known about the gcc / clang flags to do this, and are falling back on makedepend if it's available.

**Comment by rsbeckerca** [comment]
@mattcaswell is there a way to force the use of a template in `Configure` instead of using the one on the source platform during a cross compile? I'm not sure that is the correct solution, but with `Configure` running, we do not get a good `Makefile` in a `Windows -> NonStop` cross compile and I wonder how many other situations are similar.

@simon-p-r You might want to run Configure on your TNS/X or TNS/E machine and copy the generated Makefile to your workstation. That might work better temporarily, but you'll need CygWin. You can always use the ITUGLIB build, which is current at `3.0.0-beta1` and `1.1.1k` on both platforms.

> 
> 
> > It appears that the Windows template is still assuming dependencies will be rebuilt, while UNIX does not; but that looks like two separate problems here.
> 
> Not quite, re Unix. However, we have so far only known about the gcc / clang flags to do this, and are falling back on makedepend if it's available.

My `Cygwin` environment has `makedepend`, but the platform `c99` cross-compiler does not support `-MT`. Is there a detection point I can play with to see whether I can suppress the wrong behaviour? We can reasonably depend on `Cygwin` as it is recommended by the platform manufacturer for most activities relating to cross-compiles.

**Comment by t8m** [comment]
What about using no-makedepend when configuring the build?

**Comment by rsbeckerca** [comment]
> 
> 
> What about using no-makedepend when configuring the build?

With no-makedepend, I'm getting closer:
```
export PATH=/cygdrive/c/Program\ Files\ \(x86\)/HPE\ NonStop/L16.05/usr/bin:$PATH
./Configure nonstop-nsx_64 no-makedepend --with-rand-seed=rdcpu
make
...
c99  -I. -Iinclude -Iapps/include  -g -O2 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_neutral_library -Wverbose -Wtarget=tns/x -Wsystype=oss -Wlp64 -WIEEE_float  -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_VPROC= -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED=1 -D_TANDEM_SOURCE -DB_ENDIAN -D_TANDEM_ARCH=3 -DNDEBUG   -c -o apps/lib/libapps-lib-app_libctx.o apps/lib/app_libctx.c
c99 args: C:\Program Files (x86)\HPE NonStop\L16.05\usr\bin\c99.exe -I. -Iinclud
e -Iapps/include -g -O2 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_n
eutral_library -Wverbose -Wtarget=tns/x -Wsystype=oss -Wlp64 -WIEEE_float -DOPEN
SSL_PIC -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-3" -D
MODULESDIR="/usr/local/lib/ossl-modules" -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_VP
ROC= -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED=1 -D_TANDEM_SOURCE -DB_ENDIAN -D_T
ANDEM_ARCH=3 -DNDEBUG -c -o apps/lib/libapps-lib-app_libctx.o apps/lib/app_libct
x.c
c99.exe: error: Can't access executable "\usr\cmplr\ccomfe.exe": No such file or directory.
```
I'm not sure I'm going to be able to get past this one. @simon-p-r this might require a call to GNSC because the preprocessor should not be getting initiated that way.

**Comment by rsbeckerca** [comment]
Another required piece found:
```
export COMP_ROOT="C:\Program Files (x86)\HPE NonStop\L16.05"
```
And the build is now proceeding. Whether it links or not is a different subject. There are `--cross-compile-prefix` settings that are required when this is actually used, I think.

**Comment by rsbeckerca** [comment]
I have successfully cross-compiled the two main configurations (unthreaded and put) and added documentation about how to do this in `NOTES-NONSTOP.md`. PR created for this documentation.
