### ISSUE TITLE
OCSP Response: no response sent on version 1.1.1.k

### ISSUE THREAD

**Issue by Jab2870** [openssl/openssl#15914]
For some reason, when using openssl 1.1.1k, I don't get an OCSP response.

```
$ openssl version
OpenSSL 1.1.1k  25 Mar 2021
$ openssl s_client -connect <domain>:443 -tls1_2  -tlsextdebug  -status
CONNECTED(00000003)
TLS server extension "session ticket" (id=35), len=0
TLS server extension "extended master secret" (id=23), len=0
TLS server extension "renegotiation info" (id=65281), len=1
0000 - 00                                                .
TLS server extension "server name" (id=0), len=0
OCSP response: no response sent
....
```

However, using libressl, I do.

```
$ libressl_openssl s_client -connect <domain>:443 -tls1_2  -tlsextdebug  -status
CONNECTED(00000003)
TLS client extension "status request" (id=5), len=0
TLS client extension "renegotiation info" (id=65281), len=1
0001 - <SPACES/NULS>
OCSP response:
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
....
```

Is this expected behaviour? 

I should clarify that this is not for all domains, but a particular one so I
assume server configuration is related and openssl isn't supporting some element
of the server's configuration.

**Comment by Jab2870** [comment]
I have version `1.1.0l  10 Sep 2019` of openssl installed on a different
machine, and I do get an OCSP response using that. So I assume something has
changed since then?

**Comment by mattcaswell** [comment]
Most likely this is related to SNI (Server Name Indication). `s_client` will send the SNI extension by default in 1.1.1, but did not do so in 1.1.0. My guess is libressl also does not send it.

Without SNI you will get the default certificate for the server, but with SNI you will get the certificate for the specified host (assuming the server supports SNI). It is entirely possible that OCSP is configured differently on the server for the default certificate vs the specified host's certificate.

To test this theory you could try passing the "-noservername" option to s_client to suppress sending of SNI.

**Comment by Jab2870** [comment]
Thank you @mattcaswell , with the `-noservername` flag, I do get the ocsp response. So, to clarify, the issue here is with a host-specific certificate on the server?

Thanks for your help

**Comment by mattcaswell** [comment]
Yes. OCSP only seems to be configured on the server for the default certificate and not the host specific certificate.
