### ISSUE TITLE
Error report lacks granularity/precision - patch provided

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#15921]
In `crypto/x509/x509_cmp.c` file, function `X509_check_private_key()` does not report errors precisely enough to pinpoint the problem.

This patch both demonstrates what is missing, and repairs it:
```diff
diff --git a/crypto/x509/x509_cmp.c b/crypto/x509/x509_cmp.c
index 1c1a5e6a27..012f2a83f8 100644
--- a/crypto/x509/x509_cmp.c
+++ b/crypto/x509/x509_cmp.c
@@ -395,7 +395,7 @@ int X509_check_private_key(const X509 *x, const EVP_PKEY *k)
     if (xk)
         ret = EVP_PKEY_eq(xk, k);
     else
-        ret = -2;
+        ret = -3;
 
     switch (ret) {
     case 1:
@@ -408,6 +408,10 @@ int X509_check_private_key(const X509 *x, const EVP_PKEY *k)
         break;
     case -2:
         ERR_raise(ERR_LIB_X509, X509_R_UNKNOWN_KEY_TYPE);
+        break;
+    case -3:
+        ERR_raise(ERR_LIB_X509, X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY);
+        break;
     }
     if (ret > 0)
         return 1;
```

P.S. This problem surfaced in https://github.com/OpenSC/libp11/issues/413, but it shouldn't matter.

**Comment by mouse07410** [comment]
Thanks!

It would be nice if `evp_pkey_cmp_any()` received the same treatment, as its error reporting also leaves a lot to be desired.

**Comment by nhorman** [comment]
@mouse07410 can you open a PR to improve the error reporting in the instance you identified please?

**Comment by mouse07410** [comment]
In only three years... ;-)

Let me see what I can do.

**Comment by nhorman** [comment]
Yes, trying to clean up our issue board :)
I'll assign this to you a community issue, thank you!

**Comment by mouse07410** [comment]
I checked the code, and this patch has been incorporated - albeit in a different way. Closing.
