### ISSUE TITLE
OPENSSL_API_COMPAT is no longer defined by default

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#15928]
In 1.1.1 we had:
```
#ifndef OPENSSL_MIN_API
# define OPENSSL_MIN_API 0
#endif

#if !defined(OPENSSL_API_COMPAT) || OPENSSL_API_COMPAT < OPENSSL_MIN_API
# undef OPENSSL_API_COMPAT
# define OPENSSL_API_COMPAT OPENSSL_MIN_API
#endif
```
In 3.0 beta 1 it says:
```
 * Applications should use -DOPENSSL_API_COMPAT=<version> to suppress the
 * declarations of functions deprecated in or before <version>.  If this is
 * undefined, the value of the macro OPENSSL_CONFIGURED_API (defined in
 * <openssl/opensslconf.h>) is the default.
```

and:
```
If not set, this macro will default to C<30000>.
```
Where that value is actually based on OPENSSL_CONFIGURED_API

But it's not defined.

**Comment by levitte** [comment]
The documentation is a bit incorrect on this topic.  I'll try to fix that tomorrow.

**Comment by levitte** [comment]
Do note that this macro has fallen out of direct use with 3.0.  While we use it *directly* all over the place in 1.1.1, we now only use it to figure out what other macros should be defined.  That's all in `include/openssl/macros.h`

**Comment by richsalz** [comment]
Sorry to hijack a closed thread, but should that comment about "fallen out of direct use with 3.0" be documented in the user-defines manpage?

**Comment by levitte** [comment]
Not the way I see it, @richsalz.  This is now truly a user defined macro, period.  Just like feature macros like `_POSIX_SRC`, those aren't defined unless explicitly defined in the build commands or source files.
