### ISSUE TITLE
Broken: ECC public key retrieval from a cert - X509_get0_pubkey(cert)->ameth is NULL

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#15927]
OpenSSL - current master. MacOS 11.4, Xcode-12.5.1, libp11 - current master. Not that any of this version data matters.

ECC public key retrieval from a certificate via `X509_get0_pubkey()` is broken (incomplete): `X509_get0_pubkey(cert)->ameth` remains `NULL` no matter what.

This problem manifests itself in https://github.com/OpenSC/libp11 (the issue there is https://github.com/OpenSC/libp11/issues/413).

For details see https://github.com/OpenSC/libp11/issues/413#issuecomment-868689692 and https://github.com/OpenSC/libp11/issues/413#issuecomment-869144689 .

Also, https://github.com/openssl/openssl/issues/15921 patch helps pinpointing this bug.

**Comment by levitte** [comment]
->ameth being NULL is an indication that the loaded key is tied to a provider.
It *is* a bit strange that this happens no matter what for you guys, as the intention as far as I understood it was that engines would indeed get some sort of first dibs. There's been quite a bit of work happening in that area, though, so this may have changed since last I looked...

**Comment by mouse07410** [comment]
> `->ameth` being `NULL` is an indication that the loaded key is tied to a provider

@mtrojnar does it mean that the `check-privkey` should do something different with OpenSSL-3.0?

@levitte I'm a little outdated here, but still - shouldn't  `X509_check_private_key()` work properly with engine- or provider-housed keys? What we observe is that `X509_check_private_key(cert, privkey)` fails because of that `->ameth` ptr.

**Comment by levitte** [comment]
> @levitte I'm a little outdated here, but still - shouldn't `X509_check_private_key()` work properly with engine- or provider-housed keys? What we observe is that `X509_check_private_key(cert, privkey)` fails because of that `->ameth` ptr.

Well, that should work as before, I think.  However, that's not what this issue is about, is it?  The *public key* that's part of the certificate isn't tied to any specific engine or provider, so conceptually speaking, as long as anyone can hold it, be it an engine or a provider, shouldn't really matter.  libcrypto code should be astute enough to compare keys that are held by different back ends.
I haven't looked very deeply in `X509_check_private_key()`, though, so am currently unsure what's happening there...

**Comment by mouse07410** [comment]
> I haven't looked very deeply in `X509_check_private_key()`, though, so am currently unsure what's happening there...

First, I think https://github.com/openssl/openssl/issues/15921 should be applied/merged, so `X509_check_private_key()` at least reports errors correctly.

Then, if you take a look at `X509_check_private_key()` here https://github.com/openssl/openssl/blob/5fc0992fc748ec182ef5a8191807a18ecccbb4ce/crypto/x509/x509_cmp.c#L396 you'll see that it calls `EVP_PKEY_eq()` which fails here https://github.com/openssl/openssl/blob/5fc0992fc748ec182ef5a8191807a18ecccbb4ce/crypto/evp/p_lib.c#L349 because `->ameth` is `NULL`.

**Comment by levitte** [comment]
That key needs a closer look.  See, when `->ameth == NULL`, it means that the EVP_PKEY is *unassigned*, or is held by a provider.  The latter is determined by looking at the `->keymgmt`, which is done only a few lines above the one you mentioned:

https://github.com/openssl/openssl/blob/5fc0992fc748ec182ef5a8191807a18ecccbb4ce/crypto/evp/p_lib.c#L341-L343

**Comment by mouse07410** [comment]
>  it means that the `EVP_PKEY` is *unassigned*, **or is held by a provider**. The latter is determined by looking at the `->keymgmt`

I see. That means: the problem hits *before* the line I thought problematic - somewhere inside of `evp_pkey_cmp_any()`.
Of course, the error reporting of `evp_pkey_cmp_any()` is akin to the original Unix error message ("Very funny" - whatever caused the problem ;), as for most errors `evp_pkey_cmp_any()` returns `-2` ("very funny" indeed).

So, now I need to increase the granularity of the `evp_pkey_cmp_any()` error returns, and observe where it's failing???

**Comment by levitte** [comment]
> To summarize the problem: `X509_check_private_key()` consistently fails when the private key is on a PKCS#11 token.

I'm currently playing with tpm2-openssl, and am finding the same problem.  I haven't dived into that issue yet, but am going to soon.

What I suspect is that the issue happens whenever one of the providers is an HSM, i.e. refuses to export the key data.  Worst case scenario would be trying to compare keys held by two providers, both of them HSMs.  That's simply an impossible situation...

**Comment by mouse07410** [comment]
> What I suspect is that the issue happens whenever one of the providers is an HSM, i.e. refuses to export the key data. 

HSM might refuses to export the key data - though somehow the engine/provider still manages to perform (through the HSM) operations on that key, so *some* knowledge about that key must become available. 

Also, it looks like @mtrojnar observed some similarity in this problem between a "normal" cert and a cert taken from the HSM: https://github.com/OpenSC/libp11/issues/413#issuecomment-869144689

> Worst case scenario would be trying to compare keys held by two providers, both of them HSMs. That's simply an impossible situation...

I hear you - but cannot judge because of my lack of understanding of what exactly OpenSSL and the engine/provider "knows" about a key whose private key is in the HSM (but pubkey and cert can be extracted).

**Comment by mouse07410** [comment]
Also,  `X509_check_private_key()` works perfectly (with HSM and such) in OpenSSL_1.1.1.

**Comment by mattcaswell** [comment]
Is there a way to get a standalone reproducer of this issue?

**Comment by mouse07410** [comment]
> Is there a way to get a standalone reproducer of this issue?

Matt, I hear you - but how would you do "standalone" to get to a key on a PKCS#11 token? IMHO, you *have* to employ a PKCS#11 engine, in this case - `libp11`. https://github.com/OpenSC/libp11/blob/master/tests/check-privkey.c is the reproducer, and I can probably simplify it a bit - but not by much, and it would still rely on, e.g., SoftHSM2 token emulator and the libp11 itself.

And if the private key is local/accessible-directly, then `->ameth` is not `NULL`, and things seem to work (AFAICT).

**Comment by levitte** [comment]
I just ran a debug of libp11's tests/check-privkey using the EC case (i.e. reproducing this: https://github.com/OpenSC/libp11/blob/master/tests/ec-check-privkey.softhsm

It goes through all the expected steps, i.e. I end up in evp_pkey_cmp_any(), which detects that the keys are held in different backends, where one isn't a provider...  it does come as far as trying to export the engine key to import it into a provider, and stops here:

```
ec_pkey_export_to (from=0x5555555e89b0, to_keydata=0x5555555e7340, 
    importer=0x7ffff7e63677 <ec_import>, libctx=0x0, propq=0x0)
    at crypto/ec/ec_ameth.c:484
484	    const EC_KEY *eckey = NULL;
(gdb) n
485	    const EC_GROUP *ecg = NULL;
(gdb) 
486	    unsigned char *pub_key_buf = NULL, *gen_buf = NULL;
(gdb) 
489	    OSSL_PARAM *params = NULL;
(gdb) 
490	    const BIGNUM *priv_key = NULL;
(gdb) 
491	    const EC_POINT *pub_point = NULL;
(gdb) 
492	    int selection = 0;
(gdb) 
493	    int rv = 0;
(gdb) 
494	    BN_CTX *bnctx = NULL;
(gdb) 
496	    if (from == NULL
(gdb) 
497	            || (eckey = from->pkey.ec) == NULL
(gdb) 
498	            || (ecg = EC_KEY_get0_group(eckey)) == NULL)
(gdb) 
505	    if (EC_KEY_get_method(eckey) != EC_KEY_OpenSSL())
(gdb) 
506	        return 0;
```

So it seems like a main problem, at least as far as can be judged for the moment, is this unconditional refusal to export anything that's held by an ENGINE...  and it turns out that this is a bit too unconditional; we know, because this is *required* of ENGINEs, that the public key is available through perfectly normal (albeit old) OpenSSL functions.  One solution is to export public bits only when `EC_KEY_get_method(eckey) != EC_KEY_OpenSSL()`, rather than refusing to export anything at all...

I'll try that and see where it gets me.

**Comment by levitte** [comment]
One thing that surprises me, though, is this (in the same debug session):

```
(gdb) p *eckey
$8 = {meth = 0x555555571830, engine = 0x0, version = 1, 
  group = 0x5555555e8260, pub_key = 0x5555555e94b0, priv_key = 0x5555555e7e70, 
  enc_flag = 0, conv_form = POINT_CONVERSION_UNCOMPRESSED, references = 1, 
  flags = 0, ex_data = {ctx = 0x0, sk = 0x5555555e9af0}, 
  lock = 0x5555555e78c0, libctx = 0x0, propq = 0x0, dirty_cnt = 3}
(gdb) p *eckey->meth
$9 = {name = 0x7ffff7eb4740 "OpenSSL EC_KEY method", flags = 1, init = 0x0, 
  finish = 0x0, copy = 0x0, set_group = 0x0, set_private = 0x0, 
  set_public = 0x0, keygen = 0x7ffff7c84098 <ossl_ec_key_gen>, 
  compute_key = 0x7ffff7adfa38 <pkcs11_ec_ckey>, 
  sign = 0x7ffff7c8f689 <ossl_ecdsa_sign>, sign_setup = 0x0, 
  sign_sig = 0x7ffff7adf25d <pkcs11_ecdsa_sign_sig>, 
  verify = 0x7ffff7c9038a <ossl_ecdsa_verify>, 
  verify_sig = 0x7ffff7c8f5f5 <ossl_ecdsa_verify_sig>}
```

it's quite obvious that this *is* an ENGINE-backed key, since its method holds `pkcs11_` functions.  but, `eckey->engine` is NULL?  This might be an age old bug, mind you, so maybe not terribly important for the issue here.  Still...

**Comment by levitte** [comment]
For that EC check specifically, I tried this OpenSSL patch:

```
diff --git a/crypto/ec/ec_ameth.c b/crypto/ec/ec_ameth.c
index c7fbaeab5e..c1d914cc59 100644
--- a/crypto/ec/ec_ameth.c
+++ b/crypto/ec/ec_ameth.c
@@ -498,13 +498,6 @@ int ec_pkey_export_to(const EVP_PKEY *from, void *to_keydata,
             || (ecg = EC_KEY_get0_group(eckey)) == NULL)
         return 0;
 
-    /*
-     * If the EC_KEY method is foreign, then we can't be sure of anything,
-     * and can therefore not export or pretend to export.
-     */
-    if (EC_KEY_get_method(eckey) != EC_KEY_OpenSSL())
-        return 0;
-
     tmpl = OSSL_PARAM_BLD_new();
     if (tmpl == NULL)
         return 0;
@@ -523,7 +516,6 @@ int ec_pkey_export_to(const EVP_PKEY *from, void *to_keydata,
         goto err;
     selection |= OSSL_KEYMGMT_SELECT_DOMAIN_PARAMETERS;
 
-    priv_key = EC_KEY_get0_private_key(eckey);
     pub_point = EC_KEY_get0_public_key(eckey);
 
     if (pub_point != NULL) {
@@ -539,6 +531,16 @@ int ec_pkey_export_to(const EVP_PKEY *from, void *to_keydata,
         selection |= OSSL_KEYMGMT_SELECT_PUBLIC_KEY;
     }
 
+    /*
+     * If the EC_KEY method is foreign, then we can't be sure how to get
+     * the private bits, and can therefore not export or pretend to export
+     * them.
+     */
+    if (EC_KEY_get_method(eckey) != EC_KEY_OpenSSL())
+        goto skip_priv;
+
+    priv_key = EC_KEY_get0_private_key(eckey);
+
     if (priv_key != NULL) {
         size_t sz;
         int ecbits;
@@ -548,7 +550,8 @@ int ec_pkey_export_to(const EVP_PKEY *from, void *to_keydata,
          * Key import/export should never leak the bit length of the secret
          * scalar in the key.
          *
-         * For this reason, on export we use padded BIGNUMs with fixed length.
+         * For this reason, on export we use padded BIGNUMs with fixed
+         * length.
          *
          * When importing we also should make sure that, even if short lived,
          * the newly created BIGNUM is marked with the BN_FLG_CONSTTIME flag as
@@ -604,6 +607,7 @@ int ec_pkey_export_to(const EVP_PKEY *from, void *to_keydata,
         selection |= OSSL_KEYMGMT_SELECT_OTHER_PARAMETERS;
     }
 
+ skip_priv:
     params = OSSL_PARAM_BLD_to_param(tmpl);
 
     /* We export, the provider imports */
```

With that, libp11's test `ec-check-privkey.softhsm` is passing with flying colors.

**Comment by levitte** [comment]
Fix in #15996

**Comment by mouse07410** [comment]
> Fix in #15996

I confirm the fix. 

_Now need to test similar for RSA..._

**Comment by levitte** [comment]
@mouse07410, I completely rewrote that PR, so it would be great if you checked once more

**Comment by mouse07410** [comment]
> it would be great if you checked once more

Thankfully, still passes the test. ;-)
