### ISSUE TITLE
Windows: no-async fails to build

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#1593]
Configure with no-async fails to build openssl.

Linker errors:
libcrypto-1_1.def : error LNK2001: unresolved external symbol ASYNC_WAIT_CTX_clear_fd
libcrypto-1_1.def : error LNK2001: unresolved external symbol ASYNC_WAIT_CTX_free
libcrypto-1_1.def : error LNK2001: unresolved external symbol ASYNC_WAIT_CTX_get_all_fds
etc

**Comment by levitte** [comment]
Fixed in #1596

**Comment by levitte** [comment]
#1596 just made it into the affected branches.  Closing.
