### ISSUE TITLE
How best to handle Coverity false positives?

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#15936]
Yesterday's Coverity Scan report contains three items regarding `ossl_cmp_error_new()`,
and it turns out that all three are false positives.

So I logged in to the Coverity web interface and marked them as such, with the "Action" field set to "ignore".
Is there anything more/else/better to do,
in particular to avoid that anyone else how has received that email of yesterday (needlessly) has a look at those findings?

**Comment by paulidale** [comment]
I generally make an attempt to stop the warning in the code because this prevents them from ever reappearing -- e.g. when code is moved.  A significant number of the reports over the past few months have been earlier issues that were marked ignore.

If "fixing" them isn't possible, I mark them as False Positive, Minimal impact and Ignore.

**Comment by DDvO** [comment]
> I generally make an attempt to stop the warning in the code because this prevents them from ever reappearing -- e.g. when code is moved. A significant number of the reports over the past few months have been earlier issues that were marked ignore.

Good point.  At first I had no idea why Coverity came up with issues 1486533, 1486534, and 1486536
and I knew from tests that the behavior apparently inferred by Coverity does not happen,
though in this case after having a closer look I think an overflow can happen maybe dependent on the architecture,
so to be no the safe side I meanwhile consider it a bug and provided a fix in

> If "fixing" them isn't possible, I mark them as False Positive, Minimal impact and Ignore.

I don't think that the "Severity" field (this is how it's called, not "Impact") is relevant for false positives.
After I left its value as "Unspecified", Coverity automatically changed it to "Insignificant" (which I guess is what you meant by "Minimal").
