### ISSUE TITLE
ERR_GET_FUNC should be removed or marked deprecated

### ISSUE THREAD

**Issue by notroj** [openssl/openssl#15946]
Handling of encrypted private keys in `mod_ssl` was broken by the change to remove function codes, since it checked for a specific function returning errors in:

https://github.com/apache/httpd/blob/trunk/modules/ssl/ssl_engine_init.c#L1484

IMO if function codes are removed it would be preferable to remove ERR_GET_FUNC completely - the ABI is changed here, better to have it break at compile time than at runtime in an obscure way.  Or at least ERR_GET_FUNC should be marked deprecated so we get a gcc warning, which it isn't currently?

**Comment by t8m** [comment]
Unfortunately it is too late to add deprecation markers after 3.0-beta1 has been released.

**Comment by t8m** [comment]
Thinking about this more, this might cause quite serious breakage in apps so perhaps adding the deprecation marker could be treated as a bug fix.

**Comment by t8m** [comment]
OTC will have to decide.

**Comment by t8m** [comment]
@notroj would the bug be avoided if ERR_GET_FUNC() returned -1 for example instead of 0?

**Comment by notroj** [comment]
In this case it would yes, the problem was both that ERR_GET_FUNC() always returned 0 and all the `_F_` constants were also defined to 0.

**Comment by t8m** [comment]
Unfortunately adding the deprecation marker would require to change the way the deprecation marker is defined as it cannot be otherwise applied to static inline functions.

**Comment by levitte** [comment]
> .... as it cannot be otherwise applied to static inline functions.

Oh‽

**Comment by t8m** [comment]
> Oh‽

We define it to extern when OPENSSL_SUPPRESS_DEPRECATED is defined or for compilers that do not support deprecation markers. And `extern static` is invalid.

**Comment by richsalz** [comment]
So make the function a regular function, not static inline.  The extra cost for a deprecated function is not a big deal.  Breaking `mod_ssl` however, *is* a big deal.

**Comment by mattcaswell** [comment]
OTC have voted for removal.
