### ISSUE TITLE
Windows: no-err fails to build

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#1595]
Configure with no-err fails to build the Windows binary:
libcrypto-1_1.def : error LNK2001: unresolved external symbol ERR_add_error_data
libcrypto-1_1.def : error LNK2001: unresolved external symbol ERR_add_error_vdata
libcrypto-1_1.def : error LNK2001: unresolved external symbol ERR_clear_error
libcrypto-1_1.def : error LNK2001: unresolved external symbol ERR_error_string
etc

**Comment by richsalz** [comment]
I think that this isn’t supported and it’s really an error if Configure accepts it .

**Comment by levitte** [comment]
Nope, `no-err`, as well as `no-async` (see #1593) *are* supposed to work.  However, an earlier change to `Configure` lost track of these two, specifically.  I've a fix coming up.

**Comment by levitte** [comment]
Fixed in #1596

**Comment by levitte** [comment]
#1596 just made it into the affected branches. Closing.
