### ISSUE TITLE
When I called the d2i_PrivateKey in openssl1.1.1k, there was a bug.

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#15958]
Hi, When I fuzzed the d2i_PrivateKey interface in openssl1.1.1k, it ran for 23 hours and found cransh.  there was a bug.

As shown in the figure,  the memcpy() is performed when len = 2 and data is unusable in ASN1_STRING_set:304.
![image](https://user-images.githubusercontent.com/69578444/123940524-d92b1580-d9cb-11eb-9ac3-0c81a45d59eb.png)

![gdb](https://user-images.githubusercontent.com/69578444/123940673-fa8c0180-d9cb-11eb-8ed1-744326169c56.png)
For fuzzing, my initial input and cransh are as follows:
![wdw](https://user-images.githubusercontent.com/69578444/123940758-11325880-d9cc-11eb-8253-f33d55e4fedf.png)

My code is as follows
``` C
int FuzzerInitialize(int *argc, char ***argv)
{
    OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL);
    ERR_clear_error();
    CRYPTO_free_ex_index(0, -1);
    return 1;
}
int type[4] = {EVP_PKEY_NONE, EVP_PKEY_RSA, EVP_PKEY_DSA, EVP_PKEY_EC};
int FuzzerTestOneInput(const uint8_t *buf, size_t len)
{
    int n;
    if (len == 0)
        return 0;
    for(n=0; n<4;++n) {
		EVP_PKEY *pkey;
		unsigned char *out = NULL;
		pkey = d2i_PrivateKey(type[n], NULL, &buf, len);
		if (pkey != NULL) {
			i2d_PrivateKey(pkey,&out);
			OPENSSL_free(out);
			EVP_PKEY_free(pkey);
		}
	}

    ERR_clear_error();

    return 0;
}

void FuzzerCleanup(void)
{
}
```

My test data is as follows:
[Data.zip](https://github.com/openssl/openssl/files/6739908/Data.zip)

**Comment by t8m** [comment]
The buf needs to be initialized to num inside the loop.

d2i_TYPE() attempts to decode len bytes at *ppin. If successful a pointer to the TYPE structure is returned and *ppin is incremented to  the byte following the parsed data.

Yes, this is a documentation issue as the sentence above is in the d2i_X509 man page but not mentioned in the d2i_PrivateKey man page.

**Comment by 1185129439** [comment]
> The buf needs to be initialized to num inside the loop.
> 
> d2i_TYPE() attempts to decode len bytes at *ppin. If successful a pointer to the TYPE structure is returned and *ppin is incremented to the byte following the parsed data.
> 
> Yes, this is a documentation issue as the sentence above is in the d2i_X509 man page but not mentioned in the d2i_PrivateKey man page.

I agree that the buf needs to be initialized to num inside the loop.



> The buf needs to be initialized to num inside the loop.
> 
> d2i_TYPE() attempts to decode len bytes at *ppin. If successful a pointer to the TYPE structure is returned and *ppin is incremented to the byte following the parsed data.
> 
> Yes, this is a documentation issue as the sentence above is in the d2i_X509 man page but not mentioned in the d2i_PrivateKey man page.
Hi, I updated my description, and please re-read, thank you!

**Comment by 1185129439** [comment]
Hi, I updated my description, and please re-read, thank you!

**Comment by 1185129439** [comment]
1

**Comment by 1185129439** [comment]
> The buf needs to be initialized to num inside the loop.
> 
Hi, I updated my description, and please re-read, thank you!

**Comment by 1185129439** [comment]
> Yes, this is a documentation issue as the sentence above is in the d2i_X509 man page but not mentioned in the d2i_PrivateKey man page.
Hi, I updated my description, and please re-read, thank you!

**Comment by t8m** [comment]
It is still unclear whether there is any bug or whether your code just crashes because on success the pointer is moved and then you invoke the d2i_PrivateKey again on the moved pointer.

Please fix your fuzz testcase and re-run. Then please provide the crashing data.

**Comment by 1185129439** [comment]
> It is still unclear whether there is any bug or whether your code just crashes because on success the pointer is moved and then you invoke the d2i_PrivateKey again on the moved pointer.
> 
> Please fix your fuzz testcase and re-run. Then please provide the crashing data.
I do not think the problem is caused by the testcase. The same method is used to test d2i_publickey. No error is reported.

**Comment by 1185129439** [comment]
I do not think the problem is caused by the testcase. The same method is used to test d2i_publickey. No error is reported.
![image](https://user-images.githubusercontent.com/69578444/124053414-c4459500-da52-11eb-9ca1-fcecfb873e66.png)

**Comment by slontis** [comment]
> I do not think the problem is caused by the testcase. The same method is used to test d2i_publickey. No error is reported.

I am just going to reiterate what @t8m has said. You code above is not correct and is potentially walking past the end of the passed in buffer. Please change your code to do the following. If you still get a problem after doing this then we can then look at it.
````
const unsigned char *p = buf;
pkey = d2i_PrivateKey(type[n], NULL, &p, len);
````

**Comment by levitte** [comment]
@1185129439, you should observe `buf`.  On each _successful_ d2i, it will have moved forward the length of the DER encoded key, meaning that on the next iteration, the d2i call is made on whatever follows those contents.

Do note _successful_.  Could it be that none of your data contains anything that can be successfully decoded as a public key?  That's a way for the d2i_PublicKey case to never crash, because then, `buf` is never moved forward.

Regarding this forward moving of the pointer, you could simply read the docs (try `man d2i_X509`):

> d2i_TYPE() attempts to decode _len_ bytes at _\*ppin_. If successful a pointer to the **TYPE** structure is returned and _\*ppin_ is incremented to the byte following the parsed data. If _a_ is not NULL then a pointer to the returned structure is also written to _\*a_. If an error occurred then NULL is returned.

Key part: "If successful ... and _\*ppin_ is incremented"

I'm the third person to point out this flaw in your test.  @slontis gave you the proper fix.

**Comment by 1185129439** [comment]
Thank you very much，I've got it.

**Comment by DonyFang** [comment]
![截屏2021-08-03 上午9 43 05](https://user-images.githubusercontent.com/15819652/127944497-fa941530-078c-4ae3-838e-31393a228683.png)

**Comment by DonyFang** [comment]
Hi,somebody can give any guidance。I don't know what's the problem. openssl

**Comment by t8m** [comment]
This does not seem to be related to the original problem. If you need help, please open a new issue where you describe your problem in detail, how do you build openssl, what is the platform you are using, etc.

**Comment by DonyFang** [comment]
ok thanks bro @t8m。 i will open a new issue  and  describe the problem in detail. please help me to check out .
