### ISSUE TITLE
When using "openssl speed" to test the benchmakr, when it shows "compiler: /home/sat_bot/base/conda-bld/openssl_split_1615307469352/_build_env/bin/x86_64-conda-linux-gnu-cc"?

### ISSUE THREAD

**Issue by Cassielcc** [openssl/openssl#15960]
I use the icc compiler and gcc compiler to build the openssl. And I want to test the benchmark using "openssl speed", in the output, it shows the below information,

> OpenSSL 1.1.1j  16 Feb 2021
built on: Tue Mar  9 16:31:59 2021 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: /home/sat_bot/base/conda-bld/openssl_split_1615307469352/_build_env/bin/x86_64-conda-linux-gnu-cc 
The 'numbers' are in 1000s of bytes per second processed.
....

I didn't use conda, why the compiler info is "/home/sat_bot/base/conda-bld/openssl_split_1615307469352/_build_env/bin/x86_64-conda-linux-gnu-cc"?

**Comment by Cassielcc** [comment]
I checked the  ' compiler_flags ' variable in buildinf.h, it did show that i used icc compiler.

> static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','i','c','c',' ','-','f',
    'P','I','C',' ','-','p','t','h','r','e','a','d',' ','-','m','6',
    '4',' ','-','W','a',',','-','-','n','o','e','x','e','c','s','t',
    'a','c','k',' ','-','W','a','l','l',' ','-','O','3',' ','-','D',
    'O','P','E','N','S','S','L','_','U','S','E','_','N','O','D','E',
    'L','E','T','E',' ','-','D','L','_','E','N','D','I','A','N',' ',
    '-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D',
    'O','P','E','N','S','S','L','_','B','U','I','L','D','I','N','G',
    '_','O','P','E','N','S','S','L',' ','-','D','N','D','E','B','U',
    'G','\0'
};

**Comment by h-vetinari** [comment]
> I didn't use conda, why the compiler info is "/home/sat_bot/base/conda-bld/openssl_split_1615307469352/_build_env/bin/x86_64-conda-linux-gnu-cc"?

You must have either had the conda-build environment still active (or somehow broken) so that it still picks up the gcc from there. Also, those compiler_flags look completely busted (like calling `list(...)` on a string in python, which turns the string into a list of characters)

**Comment by paulidale** [comment]
Check you PATH, you're picking up the wrong openssl.

**Comment by Cassielcc** [comment]
Thanks @paulidale  and @h-vetinari . There is indeed an activated conda environment on my machine. I have resolved my problem. So close this ticket.
