### ISSUE TITLE
buildbot.openssl.org certificate expired

### ISSUE THREAD

**Issue by jenda1** [openssl/openssl#15969]
Our OpenSSL FIPS buildbot worker started having trouble logging on to the buildbot.openssl.org master. It started ~2w ago. The main reason is probably the validity of the buildbot.openssl.org certificate, which needs to be renewed:

```
$ openssl s_client -showcerts -servername buildbot.openssl.org -connect buildbot.openssl.org:9989
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = buildbot.openssl.org
verify error:num=10:certificate has expired
notAfter=Jun 16 10:14:56 2021 GMT
verify return:1
...
```

**Comment by paulidale** [comment]
We know about this, I'm not sure why it's not been fixed.  @levitte?

**Comment by jenda1** [comment]
it looks the certificate has been updated and it is valid now.

I close this bug
