### ISSUE TITLE
The s_client -reconnect option does not work with TLSv1.3

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15979]
The "-reconnect" option to s_client is supposed to attempt to reconnect to a server 5 times - each time reusing the session. This works fine in TLSv1.2 and below. However in TLSv1.3 the client fails to send the PSK from the session ticket when attempting to reconnect.

**Comment by kaduk** [comment]
I wonder if it's related to #15951 .
I may be able to look at it next week, if I have time.

**Comment by mattcaswell** [comment]
> I may be able to look at it next week, if I have time.

That would be great

**Comment by amithm7** [comment]
Duplicate of #10714
