### ISSUE TITLE
the remainder sign seems error when a positive number divided by a negative number, when use BN_div

### ISSUE THREAD

**Issue by xinkailinkk** [openssl/openssl#15982]

**Comment by paulidale** [comment]
Could you give more details?  What inputs are you using?  What output are you expecting?  A simple test case would be ideal.

Also remember there is more than one way to define remainder:

- x remainder y can take the sign of x → -7 mod 3 = -1
- x remainder y can take the sign of y → -7 mod 3 = 2

These two definitions are equivalent for x and y positive.

**Comment by xinkailinkk** [comment]
int main() {
        char *str1 = NULL;
        char *str2 = NULL;
        char cnum[] = "3";
        char cdivisor[] = "-2";
        BIGNUM *bnssl1 = BN_new();
        BIGNUM *bnssl2 = BN_new();
        BIGNUM *bnssl3 = BN_new();
        BN_CTX *ctx = BN_CTX_new();
        BN_hex2bn(&bnssl1, cnum);
        BN_hex2bn(&bnssl2, cdivisor);
        BN_div(bnssl1, bnssl3, bnssl1, bnssl2, ctx);
        str1 = BN_bn2hex(bnssl1);
        str2 = BN_bn2hex(bnssl3);
        printf("str1 is %s, str2 is %s\n", str1, str2);
        BN_free(bnssl1);
        BN_free(bnssl2);
        BN_free(bnssl3);
        OPENSSL_free(str1);
        OPENSSL_free(str2);
        BN_CTX_free(ctx);
    }
   expect result : str1 is -01, str2 is 01
   and we get: str1 is -01, str2 is -01
   The problem is the assignment at crypto/bn/bn_div.c:448 "snum->neg = num->neg;"

**Comment by xinkailinkk** [comment]
When the dividend and quotient use the same variable and the dividend is positive and the divisor is negative, the sign of the remainder is error.
