### ISSUE TITLE
openssl cms verify always return success with RSASSA-PSS signed message and no PSS parameters

### ISSUE THREAD

**Issue by wangweij** [openssl/openssl#15984]
`CMS_SignerInfo_verify` in `crypto/cms/cms_sd.c` has
```
883    if (!cms_sd_asn1_ctrl(si, 1))
884        goto err;
```
Here, `cms_sd_asn1_ctrl` calls ...
      `ossl_cms_rsa_sign` calls ...
      `ossl_cms_rsa_sign` (in `cms_rsa.c`) calls ...
      `rsa_cms_verify` calls ...
      `ossl_rsa_pss_to_ctx` (in `cms_ameth.c`) which could return -1 (error) or 1 (success)

and this 1 or -1 is returned back to `CMS_SignerInfo_verify` and the check in 883 will never fail. Is this intended?

I'm running `openssl cms` to verify a RSASSA-PSS signed message where the AlgorithmIdentifier for RSASSA-PSS has no parameters. `ossl_rsa_pss_to_ctx` should have failed because `ossl_rsa_pss_get_param` returns 0. But at the end, the command still shows "CMS Verification successful".

On the other hand, openssl 1.1.1k (from Brew on macOS) shows
```
4561284608:error:0409B095:rsa routines:rsa_pss_to_ctx:invalid pss parameters:crypto/rsa/rsa_ameth.c:683:
4561284608:error:2E0AA06F:CMS routines:cms_sd_asn1_ctrl:ctrl failure:crypto/cms/cms_sd.c:235:
```

**Comment by t8m** [comment]
Thanks for the report and thorough analysis. Fix in #15985.
