### ISSUE TITLE
OpenSSL 3.0.0-beta-1 ACVP GCM Internal IV generation Queries

### ISSUE THREAD

**Issue by sikkamukul** [openssl/openssl#15988]
"algorithm": "ACVP-AES-GCM",
"revision": "1.0",
 "isSample": true,
"testGroups": [
     {
        "tgId": 1,
        "testType": "AFT",
         "direction": "encrypt/decrypt",
         "keyLen": ...,
         "ivLen": ...,
         "ivGen": "internal",
         "ivGenMode": "8.2.1",
         "payloadLen": ...,
         "aadLen": ...,
         "tagLen": ...,
         "tests": [
           {
              "tcId": 1,
               "pt/ct": "",
               "key": "...",
               "aad": "...",
               "iv": ""(for decryption only)
           }
         ]
    }
]
As the Generation for IV is internal and IV is also an input for decryption so do we need to generate a new IV?
what API should I use for Generation of IV for ACVP in GCM?

**Comment by paulidale** [comment]
Is the answer you seek in the acvp test?

https://github.com/openssl/openssl/blob/master/test/acvp_test.c

This file is a demonstration for the FIPS lab of the way to do what's required.  It includes GCM testing.

**Comment by sikkamukul** [comment]
acvp_test.c contains GCM test in which IV is external.
I wanted to know how to generate a new IV.
and In case ivGen is internal do we need to generate a new IV for decryption as input test vectors also contains IV as input

**Comment by paulidale** [comment]
A different IV will change the encryption, so you must decrypt with the same IV as was used for encryption.
If you don't set an IV, one will be generated as part of the encryption.  Read and save this to decrypt.

**Comment by sikkamukul** [comment]
And which API can I use for new IV generation for encryption

**Comment by paulidale** [comment]
You don't call any API.  The IV is generated automatically.
