### ISSUE TITLE
Openssl 1.1.1k make test fails

### ISSUE THREAD

**Issue by sdrhmn** [openssl/openssl#15990]
I am trying to install openssl-1.1.1k on google cloud CentOS 8, the build is successfull but the make test fails. Here is the summary of the commad
    make VERBOSE=1 test

Test Summary Report
-------------------
../test/recipes/10-test_bn.t                     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
../test/recipes/15-test_dsa.t                    (Wstat: 768 Tests: 6 Failed: 3)
  Failed tests:  4-6
  Non-zero exit status: 3
../test/recipes/15-test_ec.t                     (Wstat: 2304 Tests: 11 Failed: 9)
  Failed tests:  3-11
  Non-zero exit status: 9
../test/recipes/15-test_genec.t                  (Wstat: 65024 Tests: 1143 Failed: 761)
  Failed tests:  4-5, 7-8, 10-11, 13-14, 16-17, 19-20, 22-23
                25-26, 28-29, 31-32, 34-35, 37-38, 40-41
                43-44, 46-47, 49-50, 52-53, 55-56, 58-59
                61-62, 64-65, 67-68, 70-71, 73-74, 76-77
                79-80, 82-83, 85-86, 88-89, 91-92, 94-95
                97-98, 100-101, 103-104, 106-107, 109-110
                112-113, 115-116, 118-119, 121-122, 124-125
                127-128, 130-131, 133-134, 136-137, 139-140
                142-143, 145-146, 148-149, 151-152, 154-155
                157-158, 160-161, 163-164, 166-167, 169-170
                172-173, 175-176, 178-179, 181-182, 184-185
                187-188, 190-191, 193-194, 196-197, 199-200
                202-203, 205-206, 208-209, 211-212, 214-215
                217-218, 220-221, 223-224, 226-227, 229-230
                232-233, 235-236, 238-239, 241-242, 244-245
                247-248, 250-251, 253-254, 256-257, 259-260
 262-263, 265-266, 268-269, 271-272, 274-275
                277-278, 280-281, 283-284, 286-287, 289-290
                292-293, 295-296, 298-299, 301-302, 304-305
                307-308, 310-311, 313-314, 316-317, 319-320
                322-323, 325-326, 328-329, 331-332, 334-335
                337-338, 340-341, 343-344, 346-347, 349-350
                352-353, 355-356, 358-359, 361-362, 364-365
                367-368, 370-371, 373-374, 376-377, 379-380
                382-383, 385-386, 388-389, 391-392, 394-395
                397-398, 400-401, 403-404, 406-407, 409-410
                412-413, 415-416, 418-419, 421-422, 424-425
                427-428, 430-431, 433-434, 436-437, 439-440
                442-443, 445-446, 448-449, 451-452, 454-455
                457-458, 460-461, 463-464, 466-467, 469-470
                472-473, 475-476, 478-479, 481-482, 484-485
                487-488, 490-491, 493-494, 496-497, 499-500
                502-503, 505-506, 508-509, 511-512, 514-515
                517-518, 520-521, 523-524, 526-527, 529-530
                532-533, 535-536, 538-539, 541-542, 544-545
                547-548, 550-551, 553-554, 556-557, 559-560
                562-563, 565-566, 568-569, 571-572, 574-575
                577-578, 580-581, 583-584, 586-587, 589-590
                592-593, 595-596, 598-599, 601-602, 604-605
                607-608, 610-611, 613-614, 616-617, 619-620
                622-623, 625-626, 628-629, 631-632, 634-635
                637-638, 640-641, 643-644, 646-647, 649-650
                652-653, 655-656, 658-659, 661-662, 664-665
                667-668, 670-671, 673-674, 676-677, 679-680
                682-683, 685-686, 688-689, 691-692, 694-695
                697-698, 700-701, 703-704, 706-707, 709-710
                712-713, 715-716, 718-719, 721-722, 724-725
                727-728, 730-731, 733-734, 736-737, 739-740
                742-743, 745-746, 748-749, 751-752, 754-755
                757-758, 760-761, 763-764, 766-767, 769-770
                772-773, 775-776, 778-779, 781-782, 784-785
                787-788, 790-791, 793-794, 796-797, 799-800
                802-803, 805-806, 808-809, 811-812, 814-815
                817-818, 820-821, 823-824, 826-827, 829-830
                832-833, 835-836, 838-839, 841-842, 844-845
                847-848, 850-851, 853-854, 856-857, 859-860
                862-863, 865-866, 868-869, 871-872, 874-875
                877-878, 880-881, 883-884, 886-887, 889-890
                892-893, 895-896, 898-899, 901-902, 904-905
                907-908, 910-911, 913-914, 916-917, 919-920
                922-923, 925-926, 928-929, 931-932, 934-935
                937-938, 940-941, 943-944, 946-947, 949-950
                952-953, 955-956, 958-959, 961-962, 964-965
                967-968, 970-971, 973-974, 976-977, 979-980
                982-983, 985-986, 988-989, 991-992, 994-995
                997-998, 1000-1001, 1003-1004, 1006-1007
                1009-1010, 1012-1013, 1015-1016, 1018-1019
                1021-1022, 1024-1025, 1027-1028, 1030-1031
                1033-1034, 1036-1037, 1039-1040, 1042-1043
                1045-1046, 1048-1049, 1051-1052, 1054-1055
                1057-1058, 1060-1061, 1063-1064, 1066-1067
                1069-1070, 1072-1073, 1075-1076, 1078-1079
                1081-1082, 1084-1085, 1087-1088, 1090-1091
                1093-1094, 1096-1097, 1099-1100, 1102-1103
                1105-1106, 1108-1109, 1111-1112, 1114-1115
                1117-1118, 1120-1121, 1123-1124, 1126-1127
                1129-1130, 1132-1133, 1135-1136, 1138-1139
                1141-1143
  Non-zero exit status: 254
../test/recipes/15-test_genrsa.t                 (Wstat: 1024 Tests: 5 Failed: 4)
  Failed tests:  2-5
  Non-zero exit status: 4
../test/recipes/15-test_mp_rsa.t                 (Wstat: 7680 Tests: 31 Failed: 30)
  Failed tests:  2-31
  Non-zero exit status: 30
../test/recipes/15-test_out_option.t             (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
../test/recipes/15-test_rsa.t                    (Wstat: 768 Tests: 6 Failed: 3)
  Failed tests:  4-6
  Non-zero exit status: 3
../test/recipes/15-test_rsapss.t                 (Wstat: 512 Tests: 5 Failed: 2)
  Failed tests:  1, 5
  Non-zero exit status: 2
../test/recipes/20-test_dgst.t                   (Wstat: 768 Tests: 5 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 3
../test/recipes/20-test_enc.t                    (Wstat: 256 Tests: 86 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 170 tests but ran 86.
../test/recipes/20-test_enc_more.t               (Wstat: 256 Tests: 137 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
../test/recipes/25-test_crl.t                    (Wstat: 768 Tests: 7 Failed: 3)
  Failed tests:  2, 6-7
  Non-zero exit status: 3
../test/recipes/25-test_pkcs7.t                  (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
../test/recipes/25-test_req.t                    (Wstat: 2304 Tests: 14 Failed: 9)
  Failed tests:  2, 7-14
  Non-zero exit status: 9
../test/recipes/25-test_sid.t                    (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
../test/recipes/25-test_x509.t                   (Wstat: 1792 Tests: 9 Failed: 7)
  Failed tests:  2-8
  Non-zero exit status: 7
../test/recipes/40-test_rehash.t                 (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 4 tests but ran 0.
../test/recipes/60-test_x509_store.t             (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
../test/recipes/80-test_ca.t                     (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/80-test_cms.t                    (Wstat: 1280 Tests: 6 Failed: 5)
  Failed tests:  1-5
  Non-zero exit status: 5
../test/recipes/80-test_ocsp.t                   (Wstat: 512 Tests: 11 Failed: 2)
  Failed tests:  1, 10
  Non-zero exit status: 2
../test/recipes/80-test_ssl_new.t                (Wstat: 7424 Tests: 29 Failed: 29)
  Failed tests:  1-29
  Non-zero exit status: 29
../test/recipes/80-test_ssl_old.t                (Wstat: 1536 Tests: 6 Failed: 6)
  Failed tests:  1-6
  Non-zero exit status: 6
../test/recipes/80-test_tsa.t                    (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 20 tests but ran 0.
../test/recipes/90-test_store.t                  (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 209 tests but ran 0.
Files=158, Tests=2104, 50 wallclock secs ( 2.16 usr  0.38 sys + 41.83 cusr 11.11 csys = 55.48 CPU)
Result: FAIL
make[1]: *** [Makefile:208: _tests] Error 1
make[1]: Leaving directory '/home/bottomup_real/Downloads/openssl-1.1.1k'
make: *** [Makefile:205: tests] Error 2

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input
