### ISSUE TITLE
ASN1_generate_nconf not accepting complex input

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1600]
I`m calling ASN1_generate_nconf from openSSL 1.1.0 with the following sample:

```
IA5STRING:Hello World
```

and it works, but if I`m using a more complex string like

```
asn1 = SEQUENCE:seq_section

 [seq_section]

 field1 = BOOLEAN:TRUE
 field2 = OID:commonName
 field3 = UTF8:Third field
```

then I`m getting the following error:

```
error:0D0B10C2:asn1 encoding routines:asn1_cb:unknown tag
```

**Comment by levitte** [comment]
Hi, sorry that we didn't respond earlier.  This is a question that's best asked on openssl-users, see [our mailing list information](https://www.openssl.org/community/mailinglists.html)
