### ISSUE TITLE
apps/x509.c: Why the strange call: `OBJ_create("2.99999.3", ...);`

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#16018]
Working through a list of former TODOs removed by #15539 I came across again a question I had added to `apps/x509.c`:

```
    if (!noout || text || next_serial)
        OBJ_create("2.99999.3", "SET.ex3", "SET x509v3 extension 3");
    /* Why is this strange object created (and no error checked)? */
```

**Comment by levitte** [comment]
It looks inherited...  it's there in OpenSSL's originating commit: d02b48c63a58ea4367a0e905979f140b7d090f86

Googling doesn't help much.  This being pre-1998, I'm ready to assume it's lost in history and could be thrown away.  PR welcome

**Comment by DDvO** [comment]
Thanks @levitte for swiftly responding.
I made the removal part of #16006 which I created for following up various loose (and in this case even: lost) ends.

**Comment by richsalz** [comment]
https://en.wikipedia.org/wiki/Secure_Electronic_Transaction  It can be removed.

**Comment by richsalz** [comment]
(Only one CA certificate, maybe two, ever had that extension and the HSM's that held the pieces of the key are gone.)

**Comment by DDvO** [comment]
> https://en.wikipedia.org/wiki/Secure_Electronic_Transaction It can be removed.

Thanks @richsalz - interesting background!
