### ISSUE TITLE
Does  a TLS handshake happen if the GCM iv overflow?

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#16013]
FIPS IG A.5
States thart after 2^64 records for a TLS connection when using a GCM cipher suite renegotiation shall happen automatically.

The implementation of the nonce_explicit management logic inside the module shall ensure that when the nonce_explicit part of the IV exhausts the maximum number of possible values for a given session key (e.g., a 64-bit counter starting from 0 and increasing, when it reaches the maximum value of 2^64 -1), either party (the client or the server) that encounters this **condition triggers a handshake to establish a new encryption key** – see Sections 7.4.1.1 and 7.4.1.2 in RFC 5246. A statement to that effect shall be included in the Security Policy and Validation Test Report.

The tls_gcm_cipher code just returns an error.

**Comment by paulidale** [comment]
This justifies a note in #14865 (& a reference back here)

The error would need to be dealt with by the TLS stack, which isn't inside the boundary.
The AES GCM code can't force a renegotiation directly.

**Comment by slontis** [comment]
There are multiple error paths here - so there is no distinction between an fatal error.. Unless the TLS caller is looking at the record_count overflowing??

**Comment by paulidale** [comment]
I doubt it is.

**Comment by slontis** [comment]
@paulidale - I think the work 'keys' in the comment in openssl is also not quite right..
i.e.
   /*
     * Check for too many keys as per FIPS 140-2 IG A.5 “Key/IV Pair Uniqueness
     * Requirements from SP 800-38D”.  The requirements is for one party to the
     * communication to fail after 2^64 - 1 keys.  We do this on the encrypting
     * side only.
     */

**Comment by mattcaswell** [comment]
There is nothing in the TLS code to trigger an automatic renegotiation. Of course that concept doesn't even exist in TLSv1.3, unless you interpret "triggers a handshake" to mean "send a keyupdate message" for TLSv1.3 connections.

**Comment by paulidale** [comment]
@slontis that does look suspect.  _blocks_ seems more accurate.

**Comment by paulidale** [comment]
I've noted this in the list of security policy things.

Given that the encryption will fail from the wrap onward, it could be argued that TLS will need a new handshake to continue and this check is the trigger.

**Comment by richsalz** [comment]
You might find https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-aead-limits to be useful.

**Comment by kaduk** [comment]
Per the doc Rich linked (as applied at https://datatracker.ietf.org/doc/html/rfc8446#section-5.5), TLS 1.3 requires KeyUpdate well before the GCM 64-bit counter rolls over.  AFAIR we don't track that internally, though, and require the application to notice if they're protecting millions of records on a single connection.

**Comment by mattcaswell** [comment]
OTC: This will be dealt with via security policy.

**Comment by richsalz** [comment]
Is closing this premature, or have you already told those writing the security policy to address this?

**Comment by t8m** [comment]
It is tracked by an item in #14865
