### ISSUE TITLE
Suggestion: signed bit field

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#16010]
I'm just wondering whether the following bit field should be explicitly unsigned. c99 reports this as a warning.
https://github.com/openssl/openssl/blob/ef1e0242a9aec5210845df86162c0b9219ff0f11/include/crypto/evp.h#L689
should really be:
```
unsigned int foreign:1;
```
If a pull request is wanted for this, I can handle it.

**Comment by richsalz** [comment]
just make it a char or a short. The compiler will be using that space anyhow, and the instructions to test/set a bit are probably better than with a bitfield.

**Comment by rsbeckerca** [comment]
> 
> 
> just make it a char or a short. The compiler will be using that space anyhow, and the instructions to test/set a bit are probably better than with a bitfield.

`Unsigned char` it is.

**Comment by kaduk** [comment]
If we're going to move from bitfields to `unsigned char`, then the `unsigned int flag_call_digest_custom:1` in `evp_pkey_ctx_st` should be changed as well.

**Comment by kaduk** [comment]
and `git grep ':1;'` finds a number of other instances.

**Comment by rsbeckerca** [comment]
> 
> 
> and `git grep ':1;'` finds a number of other instances.

Oh I see where we're going with this ;)

**Comment by richsalz** [comment]
Don't do more in this one, open a new issue.  Doing more unlikely to make it for 3.0 IMO.

**Comment by rsbeckerca** [comment]
> 
> 
> Don't do more in this one, open a new issue. Doing more unlikely to make it for 3.0 IMO.

Thanks. I was concerned about the scope. Most of the `:1` entries are private in `.c` files.

In header files:
```
crypto/provider_local.h:    unsigned int is_fallback:1;
include/crypto/ecx.h:    unsigned int haspubkey:1;
include/internal/passphrase.h:    unsigned int flag_cache_passphrase:1;
providers/implementations/include/prov/ciphercommon_gcm.h:    unsigned int enc:1;         /* Set to 1 if we are encrypting or 0 otherwise */
providers/implementations/include/prov/ciphercommon_gcm.h:    unsigned int pad:1;         /* Whether padding should be used or not */
providers/implementations/include/prov/ciphercommon_gcm.h:    unsigned int key_set:1;     /* Set if key initialised */
providers/implementations/include/prov/ciphercommon_gcm.h:    unsigned int iv_gen_rand:1; /* No IV was specified, so generate a rand IV */
providers/implementations/include/prov/ciphercommon_gcm.h:    unsigned int iv_gen:1;      /* It is OK to generate IVs */
```

**Comment by kaduk** [comment]
Right, so my suggestion is to just fix the one outlier to `unsigned int foreign:1;` and leave any broader changes for a follow-up PR

**Comment by rsbeckerca** [comment]
> 
> 
> Right, so my suggestion is to just fix the one outlier to `unsigned int foreign:1;` and leave any broader changes for a follow-up PR

The current commit fixes both in the evp.h file. Should I undo the second?

**Comment by kaduk** [comment]
> The current commit fixes both in the evp.h file. Should I undo the second?

The current commit is converting to `unsigned char` not-bitfields.  The argument for consistency would be to normalize on unsigned bitfields, which would only change the one instance in `evp.h`.

**Comment by paulidale** [comment]
I agree with @kaduk, just make the one change to `unsigned int foreign:1`.

Changing from bit fields to bytes is a question for post 3.0.

**Comment by rsbeckerca** [comment]
Will do

**Comment by rsbeckerca** [comment]
Reverted to the original change.
