### ISSUE TITLE
X509 extension type admission

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1601]
Could you please include the support for x509 extension admission?

Pseudo code of the asn1 syntax:

```
AdmissionSyntax ::= SEQUENCE { 

  admissionAuthority GeneralName OPTIONAL, 

  contentsOfAdmissions SEQUENCE OF Admissions } 



Admissions ::= SEQUENCE { 

  admissionAuthority [0] EXPLICIT GeneralName OPTIONAL, 

  namingAuthority [1] EXPLICIT NamingAuthority OPTIONAL, 

  professionInfos SEQUENCE OF ProfessionInfo } 



NamingAuthority ::= SEQUENCE { 

  namingAuthorityId OBJECT IDENTIFIER OPTIONAL, 

  namingAuthorityUrl IA5String OPTIONAL, 

  namingAuthorityText DirectoryString(SIZE(1..128)) OPTIONAL} 



ProfessionInfo ::= SEQUENCE { 

  namingAuthority [0] EXPLICIT NamingAuthority OPTIONAL, 

  professionItems SEQUENCE OF DirectoryString (SIZE(1..128)), 

  professionOIDs SEQUENCE OF OBJECT IDENTIFIER OPTIONAL, 

  registrationNumber PrintableString(SIZE(1..128)) OPTIONAL, 

  addProfessionInfo OCTET STRING OPTIONAL } 
```

**Comment by wolftobias** [comment]
I found a good and working example here [(https://github.com/dirkx/openssl-AdmissionSyntax)]

**Comment by richsalz** [comment]
the code needs some tweaking (we use NULL for pointers, not !; the .i2r syntax isn't supported), but looks reasonable.  Who needs this and how important is it?

**Comment by richsalz** [comment]
And of course we'd need a CLA from the original author if s/he wanted it.

**Comment by dirkx** [comment]
As the original author - consider this contributed under the CLA. There should be an old FIPS related CLA on file from a very long time ago (that predates last years apache style CLAs. I'll make sure that the foundation also gets a new version.

**Comment by richsalz** [comment]
Thanks very much, Dirk!

**Comment by wolftobias** [comment]
I`m working for German Health Insurance card which will be rolled out Germany wide with thousands of customers, I saw already a solution where admission was use by lawers. For my opinion this would be a good improvement for openssl project. Are you accepting this issue as an improvment?

**Comment by richsalz** [comment]
Yes, it will likely go in a future release.

**Comment by ramahmoo** [comment]
This seems to be a reasonable addition in openssl project, why not. I made some tests using the above mentioned code with openssl-1.1.0. On windows, tests work fine but on Linux machine, they are failing with a crash at

`C  [libcrypto.so.1.1+0x8d4bd]  asn1_item_embed_d2i+0x4d`

**Comment by levitte** [comment]
Would one of you be interested in making an actual PR from this?  @dirkx, since you refer to an old CLA, would you do the honors?

**Comment by wolftobias** [comment]
I would be very grateful if you could solve this issue. You have more experience developing with openssl. I would like to provide me as a tester. The current solution has a problem with freeing resources. The upper structure ADMISSION is not freeing the internal ones. I`m not sure if freeing of a X509 structure is also freeing the ADMISSION structure.

**Comment by FdaSilvaYY** [comment]
I will try to push a PR on this.
Freeing resources issue may be solved using a `ASN1_OP_FREE_PRE `/ `ASN1_OP_FREE_POST` .

**Comment by snhenson** [comment]
A few comments. 

The casting on the STACK_OF shouldn't be necessary if you declare the stack appropriately and use the appropriate sk_FOO_func form.

You shouldn't need to have ASN.1 functions for all the sub structures unless there is a need to have i2d/d2i for them.

Not sure about the resource issue. It should be handled automatically if the structure and module is defined appropriately. I'd need to look into exactly what is going on to be sure though.

The function i2r_NAMING_AUTHORITY looks a bit odd. You return 0 if any of several fields is NULL (which they could be because they're OPTIONAL) then also check later on to see if the fields are NULL.

**Comment by dirkx** [comment]
On 27 Feb 2017, at 05:50, Stephen Henson <notifications@github.com> wrote:
> A few comments.
> The casting on the STACK_OF shouldn't be necessary if you declare the stack appropriately and use the appropriate sk_FOO_func form.
> 
> You shouldn't need to have ASN.1 functions for all the sub structures unless there is a need to have i2d/d2i for them.
> 
> Not sure about the resource issue. It should be handled automatically if the structure and module is defined appropriately. I'd need to look into exactly what is going on to be sure though.
> 
> The function i2r_NAMING_AUTHORITY looks a bit odd. You return 0 if any of several fields is NULL (which they could be because they're OPTIONAL) then also check later on to see if the fields are NULL.
> 

Yes - it is not correct. I found the issue I think - and am waiting for a sample from production to test with a few more cases.

Dw.

**Comment by FdaSilvaYY** [comment]
@dirkx and @wolftobias : have you seen PR #2759 ? It contains some questions to resolve ...

**Comment by mattcaswell** [comment]
Closing this in favour of #2759

**Comment by wolftobias** [comment]
I just downloaded the openssl-master to try the admission feature, but the windows build fails, Linux 32/64 was fine. I tried afterwards the version openssl-1.1.0f which was fine. This leads me to the question: Is something wrong in the master build?

make[2]: Entering directory `/usr/local/gematik/openssl-master'
( :; LIBDEPS="${LIBDEPS:-test/libtestutil.a libcrypto.a -lws2_32 -lgdi32 -lcrypt32 }"; LDCMD="${LDCMD:-x86_64-w64-mingw32-gcc}"; LDFLAGS="${LDFLAGS:--DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_API_COMPAT=0x10100000L -DOPENSSLDIR="\"/usr/local/gematik/bin/openssl-master/win64/ssl\"" -DENGINESDIR="\"/usr/local/gematik/bin/openssl-master/win64/lib/engines-1_1\"" -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m64 -Wall -O3 -D_MT   }"; LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`; LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`; echo LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=test/asn1_internal_test.exe} test/asn1_internal_test.o ${LIBDEPS}; LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=test/asn1_internal_test.exe} test/asn1_internal_test.o ${LIBDEPS} )
LD_LIBRARY_PATH=: x86_64-w64-mingw32-gcc -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_API_COMPAT=0x10100000L -DOPENSSLDIR="/usr/local/gematik/bin/openssl-master/win64/ssl" -DENGINESDIR="/usr/local/gematik/bin/openssl-master/win64/lib/engines-1_1" -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m64 -Wall -O3 -D_MT -o test/asn1_internal_test.exe test/asn1_internal_test.o test/libtestutil.a libcrypto.a -lws2_32 -lgdi32 -lcrypt32
libcrypto.a(mem.o):mem.c:(.text+0xb): undefined reference to `random'
collect2: error: ld returned 1 exit status
make[2]: *** [link_app.cygwin] Error 1
make[2]: Leaving directory `/usr/local/gematik/openssl-master'
make[1]: *** [test/asn1_internal_test.exe] Error 2
make[1]: Leaving directory `/usr/local/gematik/openssl-master'
make: *** [all] Error 2
remove temp source dir
[root@gematikserver gematik]#

**Comment by levitte** [comment]
@wolftobias, you should raise a separate issue for that one.
