### ISSUE TITLE
Performance of FIPS Mode Digest on Small Buffers

### ISSUE THREAD

**Issue by mseaborn62** [openssl/openssl#1602]
We are using OpenSSL in FIPS mode for a variety of functions on our data storage appliance. I am seeing a significant performance drop in throughput for SHA digests when in FIPS mode vs non-FIPS mode for small buffer sizes (< 900K range). The tests I performed compared execution of the library (build for FIPS) in and out of FIPS mode. It seems to affect all versions of OpenSSL that I have tested. The latest version I tested was OpenSSL 1.0.1t with OpenSSL-FIPS module 2.0.13. I have created a small C program that demonstrates the issue. The program enables the threading callbacks and runs a number of threads to demonstrate the issue. 

The issue is not seen in single-threaded applications. The issue is not seen unless the locking callbacks are set. The application calculates a SHA256 digest on the sample sets and just measures the performance of the digest calculation. We noticed in our testing that initialization is a big part of the cost to calculate the signature. We believe the FIPS module enables additional mutexes and locking, which creates additional contention in threaded applications under high load. We have also been advised that continuous self-testing of the module and the locking associated to that could attribute to the issue. The measurements in my tests do not include calls to FIPS_set_mode(1).

Has anyone seen or better yet address this issue in their environment. We would be very interested in finding a solution to the performance degradation.

The following text contains instructions on how to build and execute the program that demonstrates the issue.

The simple command line application makes use of the same environment variable openssl uses to enable FIPS mode. When run without any command line parameters to set the digest buffer size, the application will calculate signatures on a 64 byte buffer 1000 times per thread. The application runs 100 threads.

Command to Compile in an environment that OpenSSL has been deployed using the default directories.
cc main.c -L /usr/local/ssl/lib -I /usr/local/ssl/include -lssl -lcrypto -lpthread -o fipsapp

Environment to enable FIPS mode
    export OPENSSL_FIPS=1

Use unset on the environment variable and the application will no longer use FIPS mode, if it had been set in the environment.
    unset OPENSSL_FIPS

Description of the output:
I.  The program outputs the size of the digest buffer.
II. The program outputs whether the application will run in FIPS mode. if the environment variable is not set or set to anything other than 1, the application will not enable FIPS mode. Three potential outputs are below.
FIPS ENV set to : getenv() returned NULL <--- non-FIPS mode
FIPS ENV set to : 1                                   <--- FIPS mode
FIPS ENV set to : 2                                   <--- non-FIPS mode
III.    If the application runs in FIPS mode, one will see the following output.

---

Entered FIPS Mode

---

IV. The program will output the total number of Megabytes processed.
V.The program will output the total Megabytes per second processed.

Usage 
    fipsperformanceapp -s <data buffer size to hash in bytes>

Output from the application with no command line parameters and the OPENSSL_FIPS environment variable not set. The application runs out of FIPS mode in this environment.

home:> fipsperformanceapp
Digest sample size = 64 bytes.
FIPS ENV set to : getenv() returned NULL
totalMBs is 6.103516
duration() = 27752 microseconds

---

Processed 219.930649 Mbps

---

Output from the application with no command line parameters and the OPENSSL_FIPS environment variable set to 1. The application runs in FIPS mode in this environment.

home:> fipsperformanceapp
Digest sample size = 64 bytes.
FIPS ENV set to : 1

---

Entered FIPS Mode

---

totalMBs is 6.103516
duration() = 101942 microseconds

---

Processed 59.872433 Mbps

---

When comparing the application running with larger signature buffers, the delta is not so dramatic. The two sample outputs below were captured from running the same application  passing a larger buffer size specification as a command line parameter. 

home:> fipsperformanceapp -s 1000000
Digest sample size = 1000000 bytes.
FIPS ENV set to : getenv() returned NULL
totalMBs is 95367.429688
duration() = 115499059 microseconds

---

Processed 825.698792 Mbps

---

home:> fipsperformanceapp -s 1000000  
Digest sample size = 1000000 bytes.
FIPS ENV set to : 1

---

Entered FIPS Mode

---

totalMBs is 95367.429688
duration() = 118400798 microseconds

---

Processed 805.462708 Mbps

---

Though each run of the applications is subject to a deviation in through put, multiple runs of the application with larger sets can be averaged. The averages are very similar when running the application in and out of FIPS mode on large buffers. The examples above just show typical behavior
 of signature throughput for the library.

Is there someone on this forum that can help us address this issue

I had to upload the program as a .txt file. Just change to .c if you are looking at the issue. Thanks
[main.txt](https://github.com/openssl/openssl/files/480948/main.txt)

**Comment by richsalz** [comment]
Consider posting on openssl-users mailing list; see https://mta.openssl.org for details.
