### ISSUE TITLE
Why control the header files under openssl/include/crypto not to be external in the dynamic library？

### ISSUE THREAD

**Issue by Andras-z** [openssl/openssl#16038]
I found that openssl/include/crypto/*.h is visible to the outside in libcrypto.a, but not visible to the outside in libcrypto.so.

Which process is used to control this, and why should we do this?

**Comment by levitte** [comment]
Headers in `include/crypto/` are libcrypto internal.  That's why.

**Comment by t8m** [comment]
Also to answer how this is achieved - when creating the shared library, you can basically provide a list of symbols that should be visible. Anything else is hidden (those are the internal symbols which must not be used by applications). There is no such mechanism for static libraries and so all the symbols that are not static are visible in there. Of course that does not mean an application linked statically to openssl should use the internal symbols as their definition can change at any time and they can be renamed/removed freely even in minor releases.
