### ISSUE TITLE
Randomisation changes

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#16031]
As noted in #14464, the randomisation used does not need to be cryptographically secure.  Any form of randomisation is sufficient.

The project could implement a low quality but fast RNG for the purposes generating this kind of blinding material.  There is an existing low quality RNG in `impl_cache_flush_cache()` in `crypto/property/property.c` which could be used more widely.  There is another in `test/testutil/random.c`.

At the least, both of these low quality RNGs should be combined.

**Comment by pedroelbanquero** [comment]
i was making 40 bit primes with openssl and -safe , at some thousands of primes generated they starts to repeat primes in the list

i think is not working fine because 2^40 is too big to have just some thousands safe primes from 0 to 1099511627776 to start to repeat primes, something is wrong i think

**Comment by paulidale** [comment]
This is expected.

A 40 bit safe prime _p_ means that _q = ½(p - 1)_ is also prime.  _q_ will be 20 bits.  How many such q are there?
There are **at most** _π(2²⁰) - π(2¹⁹)= 82025 - 43390 = 38635_such _q_.  In reality there will be a lot fewer.
This is a direct limit on the number of _p_.

**Comment by pedroelbanquero** [comment]
I generate 77 k primes of 40 bit size, 6 are repeated , around each 12 k primes 1 is repeated in 40 bit primes

..
      1 987269702039
      1 987271352303
      1 987272299043
      2 987280147823
      1 987287748779
      1 987291713543
      1 987294481403
      1 987301047143
..

**Comment by ruscot** [comment]
Hi I try to understand the problem and how to solve it, but I'm not sure to understand how impl_cache_flush_cache() function works. We just want to generate a new random seed from the previous one ? And if i understand the main problem is the current implementation with the 32 bit xorshift, which is not good enough so you want to use it with the GNU C library's random(3) function. Just to have a new random seed ?

So if what I said before is true we want something like this for the function impl_cache_flush_cache() : 
static void impl_cache_flush_cache(QUERY *c, IMPL_CACHE_FLUSH *state)
{
    uint32_t n;

    /*
     * Implement the 32 bit xorshift as suggested by George Marsaglia in:
     *      https://doi.org/10.18637/jss.v008.i14
     *
     * This is a very fast PRNG so there is no need to extract bits one at a
     * time and use the entire value each time.
     */
    n = state->seed;
    n ^= n << 13;
    n ^= n >> 17;
    n ^= n << 5;

   //start added part
    /*
    * This is an implementation of the algorithm used by the GNU C library's
    * random(3) pseudorandom number generator as described:
    *      https://www.mscs.dal.ca/~selinger/random/
    */
    uint32_t random_state[31];
    random_state[0] = n;
    int i;
    const unsigned int mod = (1u << 31) - 1;
    int32_t s;
    for (i = 1; i < 31; i++) {
        s = (int32_t)random_state[i - 1];
        random_state[i] = (uint32_t)((16807 * (int64_t)s) % mod);
    }
    unsigned int pos = 3;
    random_state[pos] += random_state[(pos + 28) % 31];
    n = random_state[pos]/2;
    //end added part 

    state->seed = n;

    if ((n & 1) != 0)
        impl_cache_free(lh_QUERY_delete(state->cache, c));
    else
        state->nelem++;
}

**Comment by paulidale** [comment]
In what way do you believe that the xor-shift RNG used here is inadequate?
Why do you thinks that GNU's random(3) addresses these?
How do you propose avoiding the licence incompatibility that include GNU code in OpenSSL creates?

This is not being used as a secure random number generator.  It's also completely unrelated to the problem that was  raised (repeating random numbers for small bit lengths).  Rather, it is being used to flush some elements of an internal cache when the cache gets too full.  All that is needed here is a series of roughly uniformly distributed bits that are not too patterned.  Unless I'm missing something fundamental, the xor-shift generator does this admirably.

**Comment by ruscot** [comment]
Okay I totally misunderstanding the problem ! I'll try to find a solution and come back to you when I found one
Thanks for your message !

**Comment by faramir-dev** [comment]
Are there any news? I would take a look into this.

**Comment by paulidale** [comment]
There is nothing to fix here.  The RNG in question is not used in a security critical role.
