### ISSUE TITLE
I can't reach the legal@opensslfoundation.org  when I submit a CLA

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#16034]
The CLA email always send fail， may I send other email address?   I uploaded it here, I am not sure what to do next. https://github.com/openssl/openssl/pull/16021
```rcpt handle timeout,last handle info: Can not connect to opensslfoundation.org:185.231.103.75:25```
openssl_icla.pdf

**Comment by paulidale** [comment]
I've processed it, you're good to go now.

**Comment by yangyangtiantianlonglong** [comment]
Thank you very much for your enthusiastic help, sorry for the unchanging logo that brought you.The mailbox server is unstable, I still submit it here first. And I also sent the mail, it may not be reachable. I have rewritten the name type, is this okay? 
[openssl_icla.pdf](https://github.com/openssl/openssl/files/6794903/openssl_icla.pdf)
