### ISSUE TITLE
Should EVP_PKEY_check() validate domain params?

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#16046]
The pod file says... 'EVP_PKEY_check() validates all components of a key given by ctx.'

The code for EVP_PKEY_check() is currently similar to EVP_PKEY_pairwise_check().

i.e. it calls
````
try_provided_check(ctx, OSSL_KEYMGMT_SELECT_KEYPAIR, OSSL_KEYMGMT_VALIDATE_FULL_CHECK);
````

**Comment by levitte** [comment]
Actually, it appears that the meaning of `EVP_PKEY_check()` has shifted, at least in documentation.  In 1.1.1, the manual text says this:

> **EVP_PKEY_check()** validates the key-pair given by _ctx_.

Looking at it from a 1.1.1 perspective, having it similar to the pairwise check is correct (and the new documentation is incorrect).

That being said, I frankly wouldn't mind a shift to include the domain parameters in this function.  That may be controversial, though, and probably needs an OTC discussion.

**Comment by slontis** [comment]
Yes the documentation is what confused me.. It may need to be changed back..

**Comment by t8m** [comment]
I'd prefer changing the documentation so the semantics is not changed in comparison to 1.1.1.
