### ISSUE TITLE
rsa_st definition is absent

### ISSUE THREAD

**Issue by MChelik** [openssl/openssl#1604]
Dear OpenSSL developers,

When I use **RSA** struct, I get _not defined_ error. Its definition in _ossl_typ.h_ is like this:
`typedef struct rsa_st RSA;`
**RSA** is **struct rsa_st** but there is no body of it. I searched whole _include/openssl_ for **rsa_st** but found nothing. Am I doing something wrong or there is lack of definition?
By the way ; I have same problem with EVP_PKEY too:
`typedef struct evp_pkey_st EVP_PKEY;`

P.S. I use OpenSSL 1.1.0 in VS2010.

Thank you

**Comment by mattcaswell** [comment]
One of the principle differences between OpenSSL 1.1.0 and previous versions is that many of the structures have now been made opaque. The biggest consequence of that is you cannot stack allocate the structures any more. So to create a new `RSA` object you must call `RSA_new()`. There are also various `RSA_get*()` and `RSA_set*()` functions that have been added to enable you to access the various members. Similarly with `EVP_PKEY`.

**Comment by MChelik** [comment]
Hmm... thank you for clarification. I changed my code like this to get **N** and **E**:
```
const BIGNUM *rsa_e, *rsa_n;
RSA_get0_key( rsa_key, &rsa_n, &rsa_e, NULL );
```
But I couldn't find any equivalent for getting public key algorithm:
`int pubkey_algonid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);`
Do you know its equivalent in OpenSSL 1.1?

Thank you

**Comment by richsalz** [comment]
Retrieving the X509_PUBKEY structure using X509_get_X509_PUBKEY(), then
X509_PUBKEY_get0_param() should do the trick.

Please put questions on the openssl-users mailing list (https://mta.openssl.org for details)

**Comment by MChelik** [comment]
I did not test but I think it's correct ¯\_(ツ)_/¯
```
X509_PUBKEY *public_key = X509_get_X509_PUBKEY( cert );
X509_ALGOR *algor;
X509_PUBKEY_get0_param( NULL, NULL, NULL, &algor, public_key );
const ASN1_OBJECT *algor_obj;
X509_ALGOR_get0( &algor_obj, NULL, NULL, algor );
int pubkey_algonid = OBJ_obj2nid( algor_obj );
```

**Comment by mattcaswell** [comment]
Looks ok - except you need to add error checking. Even easier though is (without error checking):
````
X509_PUBKEY *public_key = X509_get_X509_PUBKEY( cert );
const ASN1_OBJECT *algor_obj;
X509_PUBKEY_get0_param( &algor_obj, NULL, NULL, NULL public_key );
int pubkey_algonid = OBJ_obj2nid( algor_obj );
````

**Comment by MChelik** [comment]
Thank you very much Matt.
Have a nice day
