### ISSUE TITLE
CrossCompile about "STAGING_DIR"

### ISSUE THREAD

**Issue by mandi-china** [openssl/openssl#16049]
when i cross compile, it would have warnings "mipsel-openwrt-linux-musl-gcc.bin: warning: environment variable 'STAGING_DIR' not defined"

So, I can`t understand the STAGING_DIR， What does it have to do with my cross compilation？  what the STAGING_DIR meaning? and how i set it, Thanks!

![image](https://user-images.githubusercontent.com/17793782/125266400-6198a700-e338-11eb-92dd-a35fa0b159ca.png)

**Comment by mattcaswell** [comment]
`STAGING_DIR` isn't an OpenSSL thing. It seems to be something to do with OpenWRT. E.g. see:

https://oldwiki.archive.openwrt.org/doc/devel/crosscompile

I suggest you ask about this on OpenWRT forums.
