### ISSUE TITLE
AttributeError: '_EllipticCurve' object has no attribute 'get_pubkey'

### ISSUE THREAD

**Issue by naveensinghal** [openssl/openssl#1605]
Hi @mattcaswell 

I have an issue related to Encryption in Python. Can you please help in resolving this, if possible ? (Tried a lot but couldn't figure out the exact reason still)

Python Code which initiates the Error:
```
print("Salt: %s" % salt)    
from OpenSSL.crypto import get_elliptic_curve      #Line1
server_key = get_elliptic_curve("prime256v1")        #Line2
print("Server_key: %s" % server_key)     #Line3
server_key_id = base64.urlsafe_b64encode(server_key.get_pubkey()[1:])    #Line4

http_ece.keys[server_key_id] = server_key
http_ece.labels[server_key_id] = "P-256"
encrypted = http_ece.encrypt(data, salt=salt, keyid=server_key_id,
            dh=self.receiver_key, authSecret=self.auth_key)
```

Value of "Salt" is getting displayed in 100% of the cases. But I get the following Error because of Line4:
AttributeError: '_EllipticCurve' object has no attribute 'get_pubkey'
(Ref. File Link: https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/crypto.py)

Other Details:
Partial Requirements.txt:
```
setuptools==27.1.2
cryptography==1.5
pyelliptic==1.5.7
pyOpenSSL==16.1.0
```

The Django App is running on Debian8 Google Compute Engine VM Instance using Apache and mod_wsgi.

Can you please help in resolving this issue ?
(Alternate Code for Lines 1-4 would also be helpful if this complete Code snippet can work correctly)

Please let me know if any more information is required.

Thanks,

**Comment by richsalz** [comment]
this is a python library issue, not openssl.
