### ISSUE TITLE
OpenSSL 3.0 beta 1 no longer permits 1 byte AES-GCM IVs

### ISSUE THREAD

**Issue by dskern-github** [openssl/openssl#16057]
I have been working with an application that has supported many different versions of many different cryptographic libraries across many different platforms, so has collected a large set of automated cryptographic test vectors over the years to ensure that these upgrades don't cause any regressions. 

With OpenSSL 1.1.1, all 25 of the AES-GCM tests -- 12 pulled from IEEE P1619.1 and 13 pulled from http://csrc.nist.gov/groups/STM/cavp/ -- succeed. 

With OpenSSL 3.0 beta 1 (rebuild / relink with new headers and binaries; no changes to calling code) the vectors with 12, 16, 17, and 128 byte IVs all succeeded. However, the NIST vectors that exercise 1 byte IVs fail when calling `EVP_EncryptInit_ex` or `EVP_DecryptInit_ex` the second time to set the key and IV with "0x1C80006D:Provider routines::invalid iv length".  This application doesn't actually use 1 byte IVs, so I could disable those test vectors if this was a deliberate change, but there is no mention that I can find in OpenSSL's documentation for any restrictions on AES-GCM IV length beyond those imposed by NIST 800-38D. 

Our AES-GCM code is modeled on the examples shown in the OpenSSL wiki: https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption.

**Comment by paulidale** [comment]
Short IVs are bad.  Really bad.  GCM mode requires the combination of IV and counter to be globally unique.  Having a short IV makes this far less likely.  3.0 is enforcing a minimum 64 bit IV length (and a default of 96 bits).

Refer to FIPS 140-2 IG A.5 Key/IV Pair Uniqueness Requirements from SP 800-38D for discussion.

Is this a regression we should address?  I'll flag this for an OTC decision.

**Comment by dskern-github** [comment]
> Short IVs are bad. Really bad. GCM mode requires the combination of IV and counter to be globally unique. Having a short IV makes this far less likely. 3.0 is enforcing a minimum 64 bit IV length (and a default of 96 bits).
> 
> Refer to FIPS 140-2 IG A.5 Key/IV Pair Uniqueness Requirements from SP 800-38D for discussion.

I agree that short IVs are extremely bad. No argument here. I've never seen anyone actually use anything other than 96 and 128 bit IVs with AES-GCM. 

> 
> Is this a regression we should address? I'll flag this for an OTC decision.

I suspect that the NIST test vectors with 8 bit and 1024 bit IVs were only on the list to test that implementations could handle abnormally long and short IVs. Knowing that a minimum IV length was deliberately added to OpenSSL 3.0 for the obvious reasons, I would personally have no objections to disabling those test vectors when running against OpenSSL 3.0.  

However, I would suggest documenting this change in functionality from OpenSSL 1.1.1, since OpenSSL 3.0 is being positioned as a drop-in replacement for OpenSSL 1.1.1.

**Comment by paulidale** [comment]
That sounds like a good suggestion.  I'll put up a PR adding the documentation changes, since I doubt the OTC will remove this restriction.

I also note that ARIA, which has the exact same problem with short IVs, specifies a minimum of 4 bytes (32 bit).

**Comment by paulidale** [comment]
OTC: the lower limit to be removed.
