### ISSUE TITLE
TLSv1.3 ciphersuite TLS_AES_128_CCM_SHA256 does not work with KTLS

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#16089]
It seems that the TLSv1.3 TLS_AES_128_CCM_SHA256 ciphersuite is causing a test failure in sslapitest when ktls is enabled. This at least occurs with my kernel version (5.4.0, x86_64), and @t8m mentioned this issue in #16003 with his kernel version (5.11.22 x86_64):

````
        # ERROR: (int) 'SSL_get_error(clientssl, 0) == SSL_ERROR_WANT_READ' failed @ test/helpers/ssltestlib.c:1042
        # [1] compared to [2]
        # ERROR: (bool) 'create_ssl_connection(serverssl, clientssl, SSL_ERROR_NONE) == true' failed @ test/sslapitest.c:1192
        # false
        # 80124EA9997F0000:error:1C800066:Provider routines:ossl_ccm_stream_update:cipher operation failed:providers/implementations/ciphers/ciphercommon_ccm.c:278:
        # 80124EA9997F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:609:
        # 80124EA9997F0000:error:0A000197:SSL routines:SSL_shutdown:shutdown while in init:ssl/ssl_lib.c:2242:
        # OPENSSL_TEST_RAND_ORDER=1626364417
        not ok 19 - iteration 19
# ------------------------------------------------------------------------------
        # ERROR: (int) 'SSL_get_error(clientssl, 0) == SSL_ERROR_WANT_READ' failed @ test/helpers/ssltestlib.c:1042
        # [1] compared to [2]
        # ERROR: (bool) 'create_ssl_connection(serverssl, clientssl, SSL_ERROR_NONE) == true' failed @ test/sslapitest.c:1192
        # false
        # 80124EA9997F0000:error:1C800066:Provider routines:ossl_ccm_stream_update:cipher operation failed:providers/implementations/ciphers/ciphercommon_ccm.c:278:
        # 80124EA9997F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:609:
        # 80124EA9997F0000:error:0A000197:SSL routines:SSL_shutdown:shutdown while in init:ssl/ssl_lib.c:2242:
        # OPENSSL_TEST_RAND_ORDER=1626364417
        not ok 20 - iteration 20
# ------------------------------------------------------------------------------
    # OPENSSL_TEST_RAND_ORDER=1626364417
    not ok 1 - test_ktls
# ------------------------------------------------------------------------------
        # ERROR: (int) 'SSL_get_error(clientssl, 0) == SSL_ERROR_WANT_READ' failed @ test/helpers/ssltestlib.c:1042
        # [1] compared to [2]
        # ERROR: (bool) 'create_ssl_connection(serverssl, clientssl, SSL_ERROR_NONE) == true' failed @ test/sslapitest.c:1319
        # false
        # 80124EA9997F0000:error:1C800066:Provider routines:ossl_ccm_stream_update:cipher operation failed:providers/implementations/ciphers/ciphercommon_ccm.c:278:
        # 80124EA9997F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:609:
        # 80124EA9997F0000:error:0A000197:SSL routines:SSL_shutdown:shutdown while in init:ssl/ssl_lib.c:2242:
        # OPENSSL_TEST_RAND_ORDER=1626364417
        not ok 29 - iteration 5
# ------------------------------------------------------------------------------
    # OPENSSL_TEST_RAND_ORDER=1626364417
    not ok 2 - test_ktls_sendfile
# ------------------------------------------------------------------------------
````

I have seen this issue with current master. I also ran some tests on commit a6d36303e9 which added the TLSv1.3 KTLS CCM support. sslapitest looked different at that point but I was able to recreate a failure using that ciphersuite in an s_server/s_client communication:

````
$ openssl s_server -cert $CERT -ciphersuites TLS_AES_128_CCM_SHA256
````
and
````
openssl s_client -ciphersuites TLS_AES_128_CCM_SHA256
...
807261EB7A7F0000:error::Provider routines:ccm_stream_update:cipher operation failed:providers/implementations/ciphers/ciphercommon_ccm.c:253:
807261EB7A7F0000:error::SSL routines::decryption failed or bad record mac:ssl/record/ssl3_record.c:706:
````

The same s_server/s_client technique doesn't quite work to demonstrate the issue in current master because current master additionally requires `SSL_OP_ENABLE_KTLS` to be set (which wasn't the case for commit a6d36303e9).

What is slightly surprising is that this apparently fails in the provider CCM code...which presumably it should not be using if KTLS is being used?

**Comment by mattcaswell** [comment]
@junjunk

**Comment by mattcaswell** [comment]
> What is slightly surprising is that this apparently fails in the provider CCM code...which presumably it should not be using if KTLS is being used?

This much I think is a red herring. Once side of the communication is using ktls and one side is not. The provider code error is coming from receiving side which is not using KTLS.

Further testing reveals that the *first* app data packet sent from the peer with KTLS enabled decrypts successfully. But the *second* app data packet always fails. So it looks like something in the KTLS send path is failing.

**Comment by vvfedorenko** [comment]
@mattcaswell I will try to reproduce problem on my installation and will be back with results

**Comment by mattcaswell** [comment]
I've some further testing with a 3.0 server using KTLS, and a 1.1.1 client (obviously without KTLS). When sending app data, the plaintext seems to be making it through correctly to the `writesocket` call (actually `write`) in bss_sock.c for sending by the kernel. Wireshark shows that the kernel is apparently encrypting it and sending it to the peer. The peer is always able to decrypt the first packet, but not the second one. I'm wondering if this is a potential bug in the kernel tls module? I've not been able to identify anything unexpected happening on the OpenSSL side.

**Comment by vvfedorenko** [comment]
It definitely could be a bug in kernel because we don't have test for AES_128_CCM ciphers. Only GCM and Chacha-Poly are covered right now. And AFAIR only TLSv1.2 is covered. So I will add v1.3 and CCM cipher explicitly to kernel tests and also will try to figure out the bug.

**Comment by mattcaswell** [comment]
OTC: This ciphersuite will be disabled in 3.0 KTLS

**Comment by vvfedorenko** [comment]
Looks like it's fixed in Kernel and will be backported soon
https://patchwork.kernel.org/project/netdevbpf/patch/20211129093212.4053-1-tianjia.zhang@linux.alibaba.com/

**Comment by vvfedorenko** [comment]
There is no easy way to detect version of kernel in runtime, so I would say let's go with reverting.
I also don't like all these plays around `LINUX_VERSION_CODE < KERNEL_VERSION(x, x, x)` because it doesn't really work with custom kernel builds with backported features and will post PR to change the way we check features in Linux.
So, let's wait for actual backport, then revert commit and add a comment in documentation about fixed versions of kernel

**Comment by mattcaswell** [comment]
> So, let's wait for actual backport, then revert commit and add a comment in documentation about fixed versions of kernel

Sounds reasonable. Will you raise the PR when appropriate? I think in any case this can only go to master.

**Comment by vvfedorenko** [comment]
> Sounds reasonable. Will you raise the PR when appropriate? I think in any case this can only go to master.
Sure, will make the PR. And another one to clean this `KERNEL_VERSION` stuff, both to master
