### ISSUE TITLE
Add cipher aliases for commonly used groups

### ISSUE THREAD

**Issue by BenBE** [openssl/openssl#1608]
Please add aliases to use in cipher strings for the following groups of ciphers:
- AESCBC, AES128CBC, AES256CBC, ...
  Analoguous to AESGCM and friends, maybe analoguous for CAMELLIA too.
- mCBC, mCCM, mGCM, mNULL, mSTREAM, ...
  Mode of operation with groups for CBC, CCM/CCM8, GCM respectively.
  mSTREAM contains all Stream Ciphers, while mNULL basically maps to eNULL (if I didn't miss anything).
- iMD2, iMD4, iMD5, iSHA, iSHA1, iSHA2, iSHA3, iSHA256, iSHA384, ...
  iMD2 = MD2, iMD4 = MD4, iMD5 = MD5
  iSHA = SHA, iSHA1 = SHA1; basically an alias.
  iSHA2 = iSHA256:iSHA384:iSHA512
  iSHA3 = Variants of Keccak
- AEAD
  All AEAD mode ciphers.
- PFS
  All ciphers providing PFS; AFAIR something along the lines of kECDHE:kDHE:kSRP

Background: Try to sort all AEAD ciphers in "HIGH" before any CBC mode cipher to avoid breakage of websites providing HTTP/2 - Challange: without writing SHA\* or naming ciphers explicitly.

**Comment by richsalz** [comment]
I am not sure that aliases are the way to move forward.  It makes it very hard to understand what is really going on.

**Comment by BenBE** [comment]
Personally I prefer reading "AEAD:+HIGH" over "AESGCM:CHACHA20POLY1305:...:+HIGH".

The idea (in aboves naming) is basically to follow up on existing attribute groups we already have: kDHE, kECDHE, kSRP, ... with k for key agreement; aRSA, aECDSA, aNULL, ... with a for server authentication; eNULL (encryption). Providing m (cipher mode) and i (integrity check) as further groups.

The unprefixed groups/aliases for AESCBC just supplement what we already have for AESGCM/AESCCM, which could be a shorthand for (the not much more verbose) "AES+mCBC", "AES+mCCM" and "AES+mGCM".

For the groups/aliases PFS and AEAD this equivalent cipher string isn't that short, but an explanation "contains ciphers satisfying the requirements for XY, which translates to approx. like $cipherstring." helps as it keeps documentation relatively short.

Where do you see the complexities for the user's understanding? Which alternative would you prefer?

**Comment by richsalz** [comment]
I understand exactly what you are suggesting.  I do not like it.  Others will disagree.  That's fine :)

I prefer cipher profiles which explicitly list things in detail.  See https://github.com/openssl/openssl/pull/192 for example.

**Comment by BenBE** [comment]
Yet cipher profiles lack easy forward compatibility when a new cipher is introduced. Plus the discussion on applications and properly using the OpenSSL config file API we had some while back.

I kind of like the approach in #192 but think that some pre-defined groups should be provided by OpenSSL rather than user configuration (if you chose to follow through with the cipher profiles). Implementing both also is no contradiction: Provide sensible names for groups of things AND let the user supplement names he'd rather like to use instead.

Let's see what others think of it.

**Comment by levitte** [comment]
Not a peep for half a year.  Shall we consider the issue moot or should we have another round of discussion?

**Comment by mattcaswell** [comment]
Discussion has run out of steam. I think we should close this and create specific PRs that can be considered if people want this.
