### ISSUE TITLE
1.1.1k: openssl x509 req -text shows subject as issuer

### ISSUE THREAD

**Issue by YushengYangRTI** [openssl/openssl#16080]
On OpenSSL 1.1.1k, if I generate a certificate request ecdsa01Peer01Req.pem, and I run
```
openssl x509 -req -text -CAcreateserial -CA ca/ecdsa01RootCaCert.pem -CAkey ca/private/ecdsa01RootCaKey.pem -extfile ca/ecdsa01RootCa.cnf -in identities/ecdsa01Peer01Req.pem -out identities/ecdsa01Peer01CertX509.pem
```
and then
```
grep -i issuer ecdsa01Peer01CertX509.pem
```
it shows the subject name of `ecdsa01Peer01Req` as the issuer, but the subject name of `ecdsa01RootCaCert` should be the issuer. This problem seems to be caused by https://github.com/openssl/openssl/blob/OpenSSL_1_1_1k/apps/x509.c#L570 taking place before the `X509_set_issuer_name` on line 990, and the printing of the wrong issuer happening in between those lines.

If I run `openssl ca` instead of `openssl x509 -req`, the problem doesn't happen:

```
openssl ca -config ca/ecdsa01RootCa.cnf -in identities/ecdsa01Peer01Req.pem -out identities/ecdsa01Peer01CertCa.pem
```

x509.c line 570 doesn't appear in OpenSSL 3.0.0 alpha11: https://github.com/openssl/openssl/blame/openssl-3.0.0-alpha11/apps/x509.c , so I guess the problem is fixed in OpenSSL 3.0.0. But would it be possible to fix the problem in the next version of OpenSSL 1.1.1?

**Comment by kaduk** [comment]
It looks like switching the order(!) of the `-text` and `-CA path/to/pem` arguments would be a workaround, but we should still fix the bug.
