### ISSUE TITLE
SSL_OP_BIT macro makes constant incompatible with preprocessor

### ISSUE THREAD

**Issue by fweimer-rh** [openssl/openssl#16082]
Commit f04bb0bce490de847ed0482b8ec9eabedd173852 introduced the `SSL_OP_BIT` bit macro and uses that to rewrite various `#define` constants, e.g. `SSL_OP_TLS_ROLLBACK_BUG`.

For example, squid fails to build with an error like this:

```
In file included from ../../compat/openssl.h:42,
                 from ../../src/security/Context.h:15,
                 from ../../src/security/forward.h:14,
                 from ../../src/security/PeerOptions.h:14,
                 from PeerOptions.cc:16:
PeerOptions.cc:330:5: error: missing binary operator before token "1"
  330 | #if SSL_OP_TLS_ROLLBACK_BUG
      |     ^~~~~~~~~~~~~~~~~~~~~~~
```

If I recall correctly, haproxy is similarly afflicted.

The application fix is easy enough: Replace `#if` with `#ifdef`. It should probably be mentioned in the porting guide.

If OpenSSL can use `ULL` constants in public header files, you could define the macro like this:

```
#define SSL_OP_BIT(n)  (((uint64_t)+1ULL) << ((uint64_t)+(n)))
```

`uint64_t` expands to 0 in preprocessor expressions, so the resulting expression will be syntactically valid.

**Comment by t8m** [comment]
I do not think we can use ULL constants. In that case we might want to just drop the SSL_OP_BIT and use the constants directly.

**Comment by t8m** [comment]
But would the definition with a cast `# define SSL_OP_NO_EXTENDED_MASTER_SECRET                (uint64_t)0x00000001` work?

**Comment by fweimer-rh** [comment]
Not really, so this issue was actually introduced in an earlier commit (56bd17830f2d5855b533d923d4e0649d3ed61d11).

**Comment by fweimer-rh** [comment]
The C standard has an `UINT64_C` macro which *appears* related, but it does not provide the right type (it's `uint_least64_t` instead) and does not require that the result is a valid preprocessor expression. So I don't think it helps here.

The `+` kludge could result in false negative results for `#if` in cases where the preprocessor arithmetic overflows and the C implementation does not provide a diagnostic for that (it's not required to do so).

**Comment by t8m** [comment]
So perhaps just documenting the breakage in migration guide is the only reasonable way.

**Comment by fweimer-rh** [comment]
Looks like it. Using `#if` instead `#ifdef` does not really provide any benefit, and there is no OpenSSL 1.1 compatibility impact to worry about, either.

**Comment by t8m** [comment]
Doc addition in #16084

**Comment by richsalz** [comment]
I know you already came to a (correct IMO) decision, but the reason for introducing the macro is to make it easier to find "free" bits, re-used bits, etc.  It's much easier to compare 24 and 21 versus their hex equivalents.
