### ISSUE TITLE
How to checkout 1_0_2 branch?

### ISSUE THREAD

**Issue by airbagi** [openssl/openssl#16083]
I have tried to checkout several old branches but they are all not full. Some sources are absent, how, for instance, I can checkout OpenSSL_1_0_2_stable?
"include" folder is absent, can't compile it.
Is it possible to get old sources from github?

And another question. from 1_0_2 version I can't compile using MinGW because there are no library functions, such as 
`getaddressinfo`,` _malloca`... etc.
How can I resolve that?

Thanks

**Comment by mattcaswell** [comment]
The `OpenSSL_1_0_2_stable` branch should contain all the sources you need to compile 1.0.2. There is no "include" directory in a freshly checked out version of the branch. Instead that directory is generated at "Configure" time, i.e. run the "Configure" script as per the installation instructions and you should find the include directory is populated.

There should be no problem with building using MingGW. Please provide further information on the build steps that you took and the errors that you saw.

**Comment by airbagi** [comment]
Sure, I ran configure. Not helped. Ok.
I have found branch that is full of sources.

That's what I'm doing:

```bash
git fetch
git checkout OpenSSL_1_1_1

 ./Configure no-shared --prefix=$PWD/dist mingw
Configuring OpenSSL version 1.1.1 (0x1010100fL) for mingw
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   If you want to report a building issue, please include the   ***
***   output from this command:                                    ***
***                                                                ***
***     perl configdata.pm --dump                                  ***
***                                                                ***
**********************************************************************
mingw32-make
```

The result - almost everything compiled, but (I'm using TDM-GCC-32 toolchain):
```
C:/TDM-GCC-32/bin/../lib/gcc/mingw32/10.3.0/../../../../mingw32/bin/ld.exe: ./libcrypto.a(b_addr.o):b_addr.c:(.text+0xbd): undefined reference to `getnameinfo'
C:/TDM-GCC-32/bin/../lib/gcc/mingw32/10.3.0/../../../../mingw32/bin/ld.exe: ./libcrypto.a(b_addr.o):b_addr.c:(.text+0xb86): undefined reference to `getaddrinfo'
C:/TDM-GCC-32/bin/../lib/gcc/mingw32/10.3.0/../../../../mingw32/bin/ld.exe: ./libcrypto.a(b_addr.o):b_addr.c:(.text+0xd5e): undefined reference to `getaddrinfo'
C:/TDM-GCC-32/bin/../lib/gcc/mingw32/10.3.0/../../../../mingw32/bin/ld.exe: ./libcrypto.a(b_addr.o):b_addr.c:(.text+0x859): undefined reference to `freeaddrinfo'
C:/TDM-GCC-32/bin/../lib/gcc/mingw32/10.3.0/../../../../mingw32/bin/ld.exe: ./libcrypto.a(init.o):init.c:(.text+0x1d3): undefined reference to `GetModuleHandleEx'
C:/TDM-GCC-32/bin/../lib/gcc/mingw32/10.3.0/../../../../mingw32/bin/ld.exe: ./libcrypto.a(init.o):init.c:(.text+0xb84): undefined reference to `GetModuleHandleEx'
```
That's where I've stucked.
To your information, I've downloaded sources of **1_0_2a** in tar.gz from the Internet (not from GitHub). It compiles ok, no any problem. 

Many thanks for your quick reply!

**Comment by mattcaswell** [comment]
````
git checkout OpenSSL_1_1_1
````
This says you checked out the 1.1.1 branch. Are you attempting to build 1.0.2 or 1.1.1?

**Comment by airbagi** [comment]
I've said, that if I checkout 1.0.2 it don't find a lot's of files. I'm trying to build last version, that can be comiled.
If I compile the **master** branch it gives even more errors. If here we see about 7 functions not found, there about 20 functions...
I've also found this comment [on stacko](https://stackoverflow.com/questions/44198460/mingw-undefined-reference-to-libws2-32-getnameinfo-getaddrinfo) and added flags `-DWINVER=0x0501 -D_WIN32_WINNT=0x0501` but it didn't help.

**Comment by mattcaswell** [comment]
There are differences in the build process depending on whether you are building for 1.0.2 or 1.1.1. If you just want the latest stable version then I recommend you build 1.1.1.

From the 1.1.1 branch please ensure that you have read the INSTALL file and the NOTES.WIN file. Most specifically the section in the latter file on building using mingw.

In order to get a successful build you *must* be using an MSYS2 shell. Are you? You must also be using the MSYS2 version of perl. Please report your perl version by running `perl --version`.

I'm not familiar with the TDM-GGC-32 toolchain. We've tested the build process using the vanilla mingw/msys2 combination. No idea how well it will work with an alternative toolchain.

**Comment by airbagi** [comment]
Ok. Yes I'm using MSYS2 shell.
Well, I wrote you wrongly, the problem gone, when using those flags in Makefile
But I had to modify it by hand:

```
CFLAGS=-Wall -O3 -fomit-frame-pointer -DWINVER=0x0501 -D_WIN32_WINNT=0x0501
```

The other problem is at the end of comilation process (again some files are absent):
```
include/openssl/crmf.h:27:12: fatal error: openssl/crmferr.h: No such file or directory
   27 | #  include <openssl/crmferr.h>
      |            ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:7225: recipe for target 'test/buildtest_cmp.o' failed
```

**Comment by mattcaswell** [comment]
> buildtest_cmp.o

This should not be being built in a 1.1.1 checkout. This should only be happening in the master branch. This is most likely the result of an unclean directory - probably as a result of swapping between different branches. I'd suggest you completely clean your repository, (e.g. with something like `git clean -x -d -f`), and then start the build process again.

You should not need to modify the generated Makefile. You can pass custom CFLAGS by setting an environment variable "CFLAGS" to the appropriate value before you run the Configure script.
