### ISSUE TITLE
aes_cfb1_bits_test fails to do EVP_CIPHER_fetch when pasing "fips=yes" as a properties string

### ISSUE THREAD

**Issue by arubadean** [openssl/openssl#16094]
The tests/acvp_test is failing aes_cfb1_bits_test:

>    ERROR: (ptr) 'cipher = EVP_CIPHER_fetch(libctx, "AES-128-CFB1", "fips=yes") != NULL' failed @ test/acvp_test.c:1415
>    0x0
>   400777E6A17F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:346:Non-default library context, Algorithm (AES-128-CFB1 : 0), Properties (fips=yes)
>   OPENSSL_TEST_RAND_ORDER=1626378403
> not ok 1 - aes_cfb1_bits_test

applying NULL properties makes it work, which is concerning since the reason I'm looking at all these example ACVP tests is specifically because of FIPS.

**Comment by paulidale** [comment]
It seems fine here.  Is the FIPS provider failing to load for some reason?  Could the setup configuration be bad?  A clean rebuild can help sometimes.

**Comment by slontis** [comment]
Are you just running
````
>make TESTS
````
Or are you trying to run it via some other mechanism? (e.g test/acvp_tests)

**Comment by slontis** [comment]
This is answered in https://github.com/openssl/openssl/issues/16092

**Comment by arubadean** [comment]
closing this to discuss further in #16092
