### ISSUE TITLE
What is the purpose of setting self_tests_args.called and self_test_args.enabled in ecdsa_keygen_test?

### ISSUE THREAD

**Issue by arubadean** [openssl/openssl#16093]
In the test/acvp_test.c, self_test_args.called is set to 0 and .enabled is set to 1 in the ecdsa_keygen_test. The test then is written in such a way as to fail if self_test_args.called is not greater >= 3.

Is EVP_PKEY_Q_keygen meant to increment the value of self_test_args.called, or is it incorrect to subsequently do a `TEST_int_ge(self_test_args.called, 3)` ?

It is unclear if there is a bug or if the test is just messed up. Commenting out the check allows the test to pass.

**Comment by paulidale** [comment]
There is a callback installed which changes this value.

**Comment by slontis** [comment]
See the line in the setup that does... 
   OSSL_SELF_TEST_set_callback(libctx, self_test_events, &self_test_args);
  self tests get run during the keygen in fips mode.

**Comment by arubadean** [comment]
got it. thank you.
