### ISSUE TITLE
Apparent failure to set test parameters for RSA key gen

### ISSUE THREAD

**Issue by arubadean** [openssl/openssl#16091]
the ACVP demo test for RSA KeyGen fails when attempting to check that P1 is fetched:

>     # Subtest: rsa_keygen_test
>     1..1
>     # ERROR: (bool) 'pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_RSA_TEST_P1, &p1, &p1_len) == true' failed @ test/acvp_test.c:1095
>     # false
>     # OPENSSL_TEST_RAND_ORDER=1626365470
>     not ok 7 - iteration 1
>  OPENSSL_TEST_RAND_ORDER=1626365470
> not ok 5 - rsa_keygen_test

Tracking back, what is failing is call in `pkeyu_get_bn_bytes()` to `EVP_PKEY_get_bn_param()`.

If you edit the test to ignore p1, p2, q1 and q2 values, and just look at p, n, d, and q you will see that the test fails to match these against the control values:

>     # Subtest: rsa_keygen_test
>     1..1
>     # ERROR: (memory) 'tst->p == p' failed @ test/acvp_test.c:1115
>     # --- tst->p
>     # +++ p
>     # 0000:-cf721b9afd0d221a 7450972276d8c0c2 fd088105dd182199 96d65c79e30281d7
>     # 0000:+d57c1eaefe773f94 b8a7b9d29d12fb9b e09d8054fac2b4e7 e714f8afd8f9225e
>     #       ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
>     # 0020:-0e3f3b34da61c92d 8486621e3d5dbf92 2ecd353d6eb95916 c9825041304567aa
>     # 0020:+25a6e46152b8c210 7b0d9a49a122c1f3 27b59ac92727322f 1da182caf41ca253
>     #       ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
>     # 0040:-b7beecea4b9ea0c3 05bc4c01a54bbda4 20b520d5596f825c 8f4fe03a4e7efe44
>     # 0040:+59932a22284e9477 8daf11b41776c637 e2e52deb53cc22c1 1f5b72af21342bef
>     #       ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
>     # 0060:-f33cc00e142b32e6 288b638700c3534a 5b717a5b2840c418 b6770bab59a4967d
>     # 0060:+8919f52619c67c5f 4a44a72b0cdc81c1 f0aefac446e7e6de e5b8210b06e248a1
>     #       ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
>     #
>     # OPENSSL_TEST_RAND_ORDER=1626365857
>     not ok 1 - iteration 1
>  OPENSSL_TEST_RAND_ORDER=1626365857
> not ok 1 - rsa_keygen_test

A valid key seems to be generated, but without test valus and with random public and private parts, etc. This leads me to believe that the parameters for xP1 etc aren't being set correctly, or are at least not being actually respected.

**Comment by paulidale** [comment]
This is working for me here.  I suggest a clean rebuild and a retry.  The make dependencies can get confused at times and this is sometimes required.  If that doesn't work, we'll need more information...

**Comment by slontis** [comment]
This is directly related to the other issues that you raised.. i.e. This parameter is only gettable inside the fips module.
Because you are running from command line without the proper setup (as is done in the tests i.e environment variables + command line options passed to the test) it is using the default provider which does not support this.

**Comment by arubadean** [comment]
@slontis yup. that was in deed what was messing me up.
