### ISSUE TITLE
"make test" reports/returns success, including for acvp tests, when tests fail

### ISSUE THREAD

**Issue by arubadean** [openssl/openssl#16092]
Right now, multiple tests fail in the test/acvp_tests binary. Running that binary directly shows the failures and results in non-0 exit code on the shell. However, if you run `make tests`, you see such that:

> ...
> 25-test_x509.t ..................... ok
>30-test_acvp.t ..................... ok
>30-test_aesgcm.t ................... ok
> ...

And at the end: 
> Files=240, Tests=3400, 2528 wallclock secs ( 9.74 usr  3.65 sys + 398.42 cusr 653.22 csys = 1065.03 CPU)
> Result: PASS

Issuing `echo $?` returns 0. However, `acvp_tests:rsa_keygen_test`, `acvp_tests:ecdsa_keygen_test` and `acvp_tests:aes_cfb1_bits_test` all fail in master as of now. Running that binary returns 1 as the exist status.

My concern is that other tests may be failing as well, but that something in the mechanism of running `make test` is hiding this fact.

**Comment by slontis** [comment]
The part you are missing is that running
````
make tests
````
does extra setup that you are not doing when you run it directly..
Which means the fips provider is not loaded, and it fails.

test/recipes/30-test_acvp.t is the file used for this.. You will see that it adds extra params.

It also uses run_tests.pl which sets up environment variables such as
````
OPENSSL_CONF_INCLUDE=test
OPENSSL_MODULES=providers
````

**Comment by arubadean** [comment]
Ok, thanks. I see what I did wrong now!
