### ISSUE TITLE
[Question] Hi, How to use OpenSSL to make diffenrent public key from one private key?

### ISSUE THREAD

**Issue by nottellyou** [openssl/openssl#16101]
Hi,  

   I have a private key, and I want use this private key to make diffent  public key.
   Does have any way? 
   

Thanks.

**Comment by richsalz** [comment]
You cannot directly have more than one public key match to a single private key.  They are pairs.  Having said that, there are perhaps ways to generate multiple private keys once you have one, but it depends on what algorithm and/or curve type you are using, and is at any rate beyond the scope of what could be discussed here.

**Comment by levitte** [comment]
@nottellyou, are you trying to ask how to extract the public key from a private key, i.e. get it in a separate file?

**Comment by nottellyou** [comment]
> @nottellyou, are you trying to ask how to extract the public key from a private key, i.e. get it in a separate file?

I want use one private key file to make many different public key file.   The public key file to use different APP project.

But I found one private key file can not make many different public key file.

**Comment by mattcaswell** [comment]
As @richsalz said, this is not possible. The private and public keys are pairs. If you want a new public key, then you must have a new private key to go with it.

**Comment by nottellyou** [comment]
Oh, I know,  thanks .
