### ISSUE TITLE
Disabling sslv2, sslv3, TLSv1.0, TLSv1.1 for all the client application using OpenSSL 1.0.2k-fips.

### ISSUE THREAD

**Issue by vipul17shukla** [openssl/openssl#16114]
We are trying to disable sslv2, sslv3, TLSv1.0, TLSv1.1 for all the client application( x11vnc, apache httpd) using OpenSSL 1.0.2k-fips. We already tried disabling these protocols from the client application side. For example, In httpd configuration files /etc/httpd/conf.d/ssl.conf and /etc/httpd/conf/httpd.conf we have disabled these deprecated protocols. However, we are unable to find any such configuration for x11vnc.

Hence we tried updating to openssl 1.1.1. By default for x11vnc and other client services, sslv2 and sslv3 got disabled. But, TLSv1.0 and TLSv1.1 protocols are still being used.

1. We don't want to manually update openssl 1.1.1 as it is part of centos 8 and we are using centos 7.8. Is there any way that we can disable deprecated ssl protocols while using openssl 1.0.2k-fips?
2. If we have to update to openssl 1.1.1, then how we can disable TLSv1.0 and TLSv1.1 protocols?

**Comment by yangyangtiantianlonglong** [comment]
1.reference manual https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_new.html 
2. reference manual https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_max_proto_version.html

**Comment by t8m** [comment]
The versions 1.0.2 and 1.1.1 are not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
