### ISSUE TITLE
Makefile: Avoid changing LIBDIR based on whether it already exists

### ISSUE THREAD

**Issue by jenda1** [openssl/openssl#16121]
If `$config{libdir}` is not set, unix-Makefile.tmpl generates it:

https://github.com/openssl/openssl/blob/fd76ee47b951657cf1366fd6297bb3a85aecb169/Configurations/unix-Makefile.tmpl#L298-L309

But the assumption that the `$prefix/lib$target{multilib}` must exist is wrong. If openssl is installed to non-standard lib directory, it is common the directory does not exist on the build machine (because the compiled version of openssl is not yet installed).

**Comment by t8m** [comment]
Hmm, this is very old code from 1.1.0 times. So no new regression.

**Comment by jenda1** [comment]
this code makes the config unstable. Configure generates different pkg-config's `.pc` files depending on whether the system directory exists.

**Comment by t8m** [comment]
> this code makes the config unstable. Configure generates different pkg-config's `.pc` files depending on whether the system directory exists.

Yes, however there is a problem that someone could depend on the behavior. So IMO this should not be changed in 1.1.1 and the window to get this to 3.0.0 is closing right now.

**Comment by jenda1** [comment]
fixed
