### ISSUE TITLE
Log Remote IP Address in `s_client` Output

### ISSUE THREAD

**Issue by DabeDotCom** [openssl/openssl#16124]
I know this is going to sound trivial... but hopefully it's \*SO\* trivial that it's easy to implement!  «grin»

I was using `openssl s_client` to debug an issue that turned out to be the result of having multiple DNS (round-robin) 'A' records defined...

It would have helped tremendously if `s_client` had logged the IP address to which it *actually* connected at the top.  (And running {`dig`/`nslookup`/`host`} first — or [pro-tip] `getent hosts server.example.org` — didn't always help, since different queries could return different results at different times.)

Cheers!  :-D

**Comment by SauravMaheshkar** [comment]
**Request for Clarity:** Should this PR be closed after #16392

**Comment by t8m** [comment]
Yes, closing.
