### ISSUE TITLE
Question about SSL routines:SSL_renegotiate:wrong ssl version:ssl/ssl_lib.c:2127

### ISSUE THREAD

**Issue by okayabc** [openssl/openssl#16126]
In order to test renegotiation function, i use  openssl s_client -connect 172.16.70.82:8200, and the middle output i don't list detail, only pick some part:
1) 
···
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
···
Does this mean service using 8200 port do not support Renegotiation?

2)
···
HEAD / HTTP/1.0
R
RENEGOTIATING
140371330676480:error:1420410A:SSL routines:SSL_renegotiate:wrong ssl version:ssl/ssl_lib.c:2127:
···
What is the possible reason?

My system openssl version is OpenSSL 1.1.1g, and service using 8200 port use openssl 1.1.1k.

**Comment by yangyangtiantianlonglong** [comment]
```openssl s_client -connect 172.16.70.82:8200 ```, The tls1.3 version will be negotiated.However, The tls1.3 does not support renegotiation.
This command is required if renegotiation is required. ```openssl s_client -connect 172.16.70.82:8200 -tls1_2```

**Comment by kaduk** [comment]
> In order to test renegotiation function, i use openssl s_client -connect 172.16.70.82:8200, and the middle output i don't list detail, only pick some part:
> 1)
> ···
> Server public key is 2048 bit
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> ···
> Does this mean service using 8200 port do not support Renegotiation?

"Secure renegotiation" indicates the functionality of RFC 5746 (e.g., the "renegotiation_info" extension), which is distinct from actual renegotiation functionality.

> 
> 
> ···
> HEAD / HTTP/1.0
> R
> RENEGOTIATING
> 140371330676480:error:1420410A:SSL routines:SSL_renegotiate:wrong ssl version:ssl/ssl_lib.c:2127:
> ···
> What is the possible reason?
> 
> My system openssl version is OpenSSL 1.1.1g, and service using 8200 port use openssl 1.1.1k.

The previous comment answered this part correctly.
