### ISSUE TITLE
lastError:604418162.     errorMessage:   error:2406B072:random number generator:RAND_DRBG_generate:in error state

### ISSUE THREAD

**Issue by chenfei1117** [openssl/openssl#16139]
I am using OpenSSL 1.1.1g for development, compiling programs in MIPs, Linux system, gcc5.3 version, calling RSA_ pub_ encrypt function When using the encrypt method, when running on a higher version MIPS Linux (gcc8.3) system, the following error occurs: random number generator: Rand_ DRBG_ generate:in error state。

RSA *rsaKey = RSA_new();

	BIGNUM *bigNumE = BN_new();
	BIGNUM *bigNumN = BN_new();
	BN_bin2bn(pubKey.Exponent, RSA_KEY_LEN_1024, bigNumE);
	BN_bin2bn(pubKey.Modulus, RSA_KEY_LEN_1024, bigNumN);

	RSA_set0_key(rsaKey, bigNumN, bigNumE, NULL);

	char cCipher[RSA_KEY_LEN_1024];
	memset(cCipher, 0, sizeof(cCipher));
	int nResult = RSA_public_encrypt(sSource.size(), (const unsigned char*)sSource.c_str(), (unsigned char*)cCipher, rsaKey, RSA_PKCS1_PADDING);
	unsigned long error = ERR_peek_last_error();
	char errorMessage[120] = { 0 };
	ERR_error_string(error, errorMessage);
	printf("pkcsRsaPubKeyEncrypt%d.%s:\n", error, errorMessage);
	sEncData.assign(cCipher, RSA_KEY_LEN_1024);

	RSA_free(rsaKey);
	
	return  (RSA_KEY_LEN_1024 == nResult);

**Comment by mattcaswell** [comment]
Are there any other errors on the stack? There might be an earlier error that gives a clue. Rather that just printing the last error you could try dumping all errors, e.g. using `ERR_print_errors_fp`

**Comment by chenfei1117** [comment]
Okay, I will print out all the errors next

**Comment by t8m** [comment]
No input from reporter. Closing.
