### ISSUE TITLE
SSL Session cache timeout from context is ignored

### ISSUE THREAD

**Issue by wbeck10** [openssl/openssl#16142]
The method SSL_SESSION_new sets a default timeout to 5 minutes then it calls the 
ssl_session_calculate_timeout to update the calculated timeout value:

SSL_SESSION *SSL_SESSION_new(void)
{
    ...
    ss->timeout = 60 * 5 + 4;   /* 5 minute timeout by default */
    ss->time = time(NULL);
    ssl_session_calculate_timeout(ss);

In the method ssl_get_new_session the timeout value of the SSL_SESSION structure is set but the calculated timeout value is not updated.

**Comment by t8m** [comment]
@tmshort Could you please look at this? The ssl_session_calculate_timeout() was added by your patch.

**Comment by yangyangtiantianlonglong** [comment]
It looks like the calc_timeout needs to be updated.
```javascript
diff --git a/ssl/ssl_sess.c b/ssl/ssl_sess.c
index b526984289..49947211c6 100644
--- a/ssl/ssl_sess.c
+++ b/ssl/ssl_sess.c
@@ -438,6 +438,8 @@ int ssl_get_new_session(SSL *s, int session)
     else
         ss->timeout = s->session_ctx->session_timeout;

+    ssl_session_calculate_timeout(ss);
+
     SSL_SESSION_free(s->session);
     s->session = NULL;
```

**Comment by tmshort** [comment]
I will take a look, although @yangyangtiantianlonglong patch might be correct.

**Comment by t8m** [comment]
> It looks like the calc_timeout needs to be updated.

Would you submit a PR, please?

**Comment by tmshort** [comment]
I scanned through the code, and this appears to have been the only place where the `ssl_session_calculate_timeout()` was missed. Will create a PR.

**Comment by wbeck10** [comment]
I don't think calling ssl_session_calculate_timeout would be the right fix unless you change it that it can use the old ss->time value.
The ss->calctimeout should use the old ss->time (set by SSL_SESSION_new) + ctx->timeout.

**Comment by tmshort** [comment]
It's the new `ss` session that is being updated; whenever the time or timeout value of a session is updated, the `ssl_session_caclulate_timeout()` API needs to b called on this session. That is the case here. It was not being called even though `ss->timeout` was being updated. It should not be using the "old" `ss->time`; it should be using the current values in the session.

**Comment by tmshort** [comment]
> I don't think calling ssl_session_calculate_timeout would be the right fix unless you change it that it can use the old ss->time value.
> The ss->calctimeout should use the old ss->time (set by SSL_SESSION_new) + ctx->timeout.

That's basically what it's doing. The `ssl_session_calculate_timeout()` API uses the current values in the session. Which, if you look at PR #16145, are the new `ss->timeout` (which is either the default, or the one from the `ctx`), and whatever `ss->time` was set in `SSL_SESSION_new()`.

**Comment by tmshort** [comment]
Basically, whenever `ss->timeout` or `ss->time` are modified, `ss_session_calculate_timeout()` needs to be called.

**Comment by paulidale** [comment]
> Basically, whenever `ss->timeout` or `ss->time` are modified, `ss_session_calculate_timeout()` needs to be called.

Something to consider for the future might be an update helper function or functions that do this.

**Comment by tmshort** [comment]
> Something to consider for the future might be an update helper function or functions that do this.

`ssl_session_calculate_timeout()` *is* the helper function!

**Comment by paulidale** [comment]
An easy to forget helper.  I was thinking more along the lines of an `ssl_session_set_timeout()` function(s) that sets one or both timeouts and then does the required calculation.

**Comment by tmshort** [comment]
> An easy to forget helper. I was thinking more along the lines of an `ssl_session_set_timeout()` function(s) that sets one or both timeouts and then does the required calculation.

Gotcha. Thinking about this gets complicated; do you have a single function with both `time` and `timeout` arguments, and have to deal with cases where the values aren't supposed to change (i.e. feed in the original value, or use NULLs to represent "don't change"), or have 3 APIs, one for `time`, another for `timeout` and a third for both? It can get pretty ugly. But it's internal, so how much does it matter?

**Comment by paulidale** [comment]
A solution more complex than the problem is rarely good :)

One API with two parameters and pass a known value (-1, 0, MAX_UINT, whatever) for "don't touch" might be cleanest.  This avoids double calling the running the fix up code if both need changing but doesn't mandate both always changing.  Anyway an idea for the future to help prevent this kind of thing.
