### ISSUE TITLE
RSA encrypt

### ISSUE THREAD

**Issue by Lifeda92** [openssl/openssl#16149]
Hello.

`
"exponent": "65537",
"public_key": "d911ad3f...553e6c4ff"
`

Which function from openssl i need use to encrypt some string with public key and exponent, which i have?
Thanks.

**Comment by paulidale** [comment]
Are you sure you want to encrypt a string with RSA?

The typical approach is to encrypt the data with a symmetric cipher (AES) and to only encrypt the key that was used with RSA.

**Comment by Lifeda92** [comment]
> Are you sure you want to encrypt a string with RSA?
> 
> The typical approach is to encrypt the data with a symmetric cipher (AES) and to only encrypt the key that was used with RSA.

I got public rsa key and exponent from server. I need use these data for encrypt my password.

**Comment by kroeckx** [comment]
Are you trying to authenticate yourself to the server, and have
the public key of the server? You really need to provide more
details about what you're actually trying to do.

In theory it's possible to directly encrypt the password if it's
shorter then the public key, but it's unlikely. In general, you
want to switch to a symmetric cipher like AES, since it's unlikely
that it would be the only communication. In any case, you'd
still need to know which padding mode to use.

If it's not to authenticate now, but for instance storage of the
password to be able to later authentication, encrypting the
password with RSA is a bad idea, you want something that's
designed to store passwords.

**Comment by Lifeda92** [comment]
> Are you trying to authenticate yourself to the server, and have the public key of the server? You really need to provide more details about what you're actually trying to do. In theory it's possible to directly encrypt the password if it's shorter then the public key, but it's unlikely. In general, you want to switch to a symmetric cipher like AES, since it's unlikely that it would be the only communication. In any case, you'd still need to know which padding mode to use. If it's not to authenticate now, but for instance storage of the password to be able to later authentication, encrypting the password with RSA is a bad idea, you want something that's designed to store passwords.

In process signing in steam my password encrypting with this JS ( https://store.cloudflare.steamstatic.com/public/shared/javascript/crypto/rsa.js ).

I need make same encrypt on c++ for signing in to steam account from my program.

Process of signin in to steam:

1. Send POST request to https://store.steampowered.com/login/getrsakey/
POST DATA:
`
donotcache=1627122272446&username=LOGIN
`
Response from server will be:

`{
   "publickey_exp" : "010001",
   "publickey_mod" : "d911ad3f5a817e0610e2c86adc69a217df6ed8cf18f2943b4f326a5753d72a5e97732fb2748257db9c673f8e4c83f8c19daee4b34d5689b1c116801af0d7988c25163a37ead2320a36dbd26510698f76e2d0cf0bf70a013a9d40ed09b2936af21f3354e2975c92b7b32931de73a5d08e6242578c63a24a0252df083e0bc060d9a0013db6daf58c44d57966311c77c4669303cb862111038fecb89d739b3fe21c0b45a9e4f93d9aa8458c8d33986d3fb368b18ae04a83f41d5f0d53a0b5f4695140dd7bb4462d1bc348c1e748262e76ccec39d59e5bbe8f26375575a7ee01a176f24e5fa4a4077e0388d4900767b4b1ef3a55bd6fcbdb265d8a3a402553e6c4ff",
   "success" : true,
   "timestamp" : "295419750000",
   "token_gid" : "a355653dfff9e80"
}`

2. Encrypt password with this JS ( https://store.cloudflare.steamstatic.com/public/shared/javascript/crypto/rsa.js )
Use for encrypt publickey_exp and publickey_mod.

3. Send POST request with encrypted password to https://store.steampowered.com/login/dologin/ .
POST DATA:
`
donotcache=1627122272723&
password=VZZJte82S8YswfjpdC3eMPYFpwiTc6eWRFYFbkkvjTZ7xSY%2BBRwqgnfrMAXkpeNFK3tpXfieWe%2BNJOLAEMydqV44TRK%2BLcQu4mx90ptmjmOYwzLHzq9MxFyZtjUh2CfQVd0OOME6D8XHPqGbDm0sOIsq8o7hmL3Te7OkLlqzbB31DKMsfcDYGE7dCNzThQBJOqsAECG40njY2WpUM5cMcDf96j0UF23gweZ29bkTcWgv5CWWO1qSV3xgYdYKqWr%2B1EwQcRjy8AurqtQpVzSYokamca1C10CLILGYRVFs5LdZSBHUV5%2BsRjvwU34YWKH6JcQHB5BhfVgCEJEZ9d5T0w%3D%3D (encrypted, i need do this)&
username=LOGIN&
twofactorcode=&
emailauth=&
loginfriendlyname=&
captchagid=-1&
captcha_text=&
emailsteamid=&
rsatimestamp=295419750000&r
emember_login=false
`

Thats all, after i sent to server encrypted password i will get tokens. Successfully signed in. But i need function to encrypting my password. I see RSA, then i asking you about RSA.
