### ISSUE TITLE
Migration guide is 404 Not Found

### ISSUE THREAD

**Issue by slel** [openssl/openssl#16152]
Please restore the migration guide.

The page https://www.openssl.org/source/ has this sentence

> Information and notes about migrating existing applications
> to OpenSSL 3.0 are available in the [OpenSSL 3.0 Migration Guide](https://www.openssl.org/docs/manmaster/man7/migration_guide.html)

but the link gives

> Page Not Found
>
> Sorry, but the link you gave does not exist.

That page is not archived at the Web Archive's Internet Wayback Machine.

- https://web.archive.org/web/*/https://www.openssl.org/docs/manmaster/man7/migration_guide.html

All the manpages may have been deleted, as this seems empty:

- https://www.openssl.org/docs/manmaster/man7/

as well as all the other manN subdirectories of docs/manmaster:

- https://www.openssl.org/docs/manmaster/

**Comment by slel** [comment]
The page https://www.openssl.org/news/changelog.html
uses a different link, pointing to

- https://github.com/openssl/openssl/blob/master/doc/man7/migration_guide.pod

**Comment by paulidale** [comment]
The last Internet Archive copy is from the [end of October](https://web.archive.org/web/20201029072633/https://www.openssl.org/docs/manmaster/man7/) last year.

**Comment by slel** [comment]
Oops, wrong issue tracker, this issue should have been opened in

- https://github.com/openssl/web/issues

Maybe someone can migrate it. Otherwise please close.

Pull request openssl/web#247 fixes the issue.

**Comment by paulidale** [comment]
The PR doesn't fix this properly.  The files are meant to be where the link points.  They're not being put there which is probably a failure of the installation process here.

**Comment by paulidale** [comment]
The content looks like it's back.  The directories still seem empty.  E.g. https://www.openssl.org/docs/manmaster/man7/ just shows:

><h1>Index of /docs/manmaster/man7</h1>
><b>Name	Last modified	Size	Description</b>
><br>Parent Directory	 	- 	 
><hr>_Apache/2.4.29 (Ubuntu) Server at www.openssl.org Port 443_

**Comment by mattcaswell** [comment]
The content is now fully back. Closing.
