### ISSUE TITLE
EVP_MD_meth_dup() on global EVP_MDs leaks memory in OpenSSL 3.0

### ISSUE THREAD

**Issue by martelletto** [openssl/openssl#16157]
When EVP_MD_meth_dup() is called on a global EVP_MD in OpenSSL 3.0, the origin of the newly allocated EVP_MD is initially set to EVP_ORIG_METH in EVP_MD_meth_new(), but is later overwritten with the origin of the source EVP_MD in memcpy(), which turns EVP_MD_meth_free() into a no-op.

The following excerpt works with OpenSSL 1.1.1, but leaks memory with OpenSSL 3.0:

```c
#include <openssl/evp.h>
#include <stdlib.h>

int main(void) {
        EVP_MD *md = EVP_MD_meth_dup(EVP_sha256());
        if (md) EVP_MD_meth_free(md);
}
```

A potential fix might be to set origin back to EVP_ORIG_METH in EVP_MD_meth_dup() after the call to memcpy():

```diff
diff --git a/crypto/evp/evp_lib.c b/crypto/evp/evp_lib.c
index f78df52a..42331b0b 100644
--- a/crypto/evp/evp_lib.c
+++ b/crypto/evp/evp_lib.c
@@ -822,6 +822,7 @@ EVP_MD *EVP_MD_meth_dup(const EVP_MD *md)
         CRYPTO_RWLOCK *lock = to->lock;
 
         memcpy(to, md, sizeof(*to));
+        to->origin = EVP_ORIG_METH;
         to->lock = lock;
     }
     return to;
```

**Comment by mattcaswell** [comment]
Fix in #16159.
