### ISSUE TITLE
Reconsider strength of CCM_8 TLS ciphers

### ISSUE THREAD

**Issue by kaduk** [openssl/openssl#16154]
As far as I can tell, we don't give any particular consideration to the truncated authentication tag of the CCM_8 ciphers when we're considering cipher strength and security level.  E.g., at `openssl ciphers -s -v 'ALL@SECLEVEL=2' we still see ECDHE-ECDSA-AES256-CCM8, AES128-CCM8, etc., and I think that TLS_AES_128_CCM_8_SHA256 is also treated as being strong.
It's not entirely clear that we should be treating ciphers that only have a 64-bit authentication tag as providing that level of security.

(Inspired by https://github.com/openssl/openssl/issues/13689#issuecomment-752220290)

**Comment by paulidale** [comment]
I'll raise this at the OTC call tomorrow.

**Comment by mattcaswell** [comment]
OTC: We will consider this post 3.0

**Comment by mattcaswell** [comment]
OTC: See comment in #16160
