### ISSUE TITLE
stunnel regression

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16158]
We've found an stunnel regression when using a password-protected private key:

The error stack with beta1 is
```
[ ] Loading certificate from file: /root/localhost.crt
[ ] Certificate loaded from file: /root/localhost.crt
[ ] Loading private key from file: /root/localhost.key
[!] error queue: ssl/ssl_rsa.c:384: error:0A080009:SSL routines::PEM lib
[!] error queue: crypto/pkcs12/p12_decr.c:86: error:11800074:PKCS12 routines::pkcs12 cipherfinal error
[!] error queue: providers/implementations/ciphers/ciphercommon_block.c:124: error:1C800064:Provider routines::bad decrypt
[!] SSL_CTX_use_PrivateKey_file: crypto/encode_decode/decoder_lib.c:97: error:1E08010C:DECODER routines::unsupported
```

The error stack with alpha16 was different:
```
[ ] Loading certificate from file: /root/localhost.crt
[ ] Certificate loaded from file: /root/localhost.crt
[ ] Loading private key from file: /root/localhost.key
[!] error queue: ssl/ssl_rsa.c:384: error:0A080009:SSL routines::PEM lib
[!] error queue: crypto/encode_decode/decoder_lib.c:83: error:1E08010C:DECODER routines::unsupported
[!] error queue: providers/implementations/encode_decode/decode_der2key.c:132: error:1C80009F:Provider routines::unable to get passphrase
[!] error queue: crypto/passphrase.c:178: error:07880028:common libcrypto routines::UI lib
[!] SSL_CTX_use_PrivateKey_file: crypto/ui/ui_lib.c:544: error:1400006B:UI routines::processing error
```
The keypair was generated using
```
openssl genrsa -aes128 -out localhost.key -passout pass:1234 2048
openssl req -x509 -key localhost.key -out localhost.crt -subj /CN=localhost -batch
```

sample stunnel.conf:
```
[gmail-pop3]
client = yes
accept = 127.0.0.1:1100
connect = pop.gmail.com:995
verifyChain = yes
CApath = /etc/ssl/certs
checkHost = pop.gmail.com
OCSPaia = yes
cert=/root/localhost.crt  
key=/root/localhost.key
```

**Comment by beldmit** [comment]
I don't know if it is a stunnel error or openssl regression so don't mark it as a bug now.

**Comment by beldmit** [comment]
For clarity: it's a regression comparing to openssl 1.1.1. The PKCS#12 report in the error stack can be a consequence of the stunnel fallback chain or reveal a bug in openssl.

**Comment by t-j-h** [comment]
A separate program using SSL_CTX_use_PrivateKey_file is not generating an error with a key and cert created as specified.
Can we get more information on the context here and the configuration in terms of providers loaded etc.

**Comment by beldmit** [comment]
Only the default provider is loaded and activated.

**Comment by beldmit** [comment]
stunnel relevant code:
```
    /* try the cached value first */
    set_prompt(section->key);
    SSL_CTX_set_default_passwd_cb(section->ctx, cache_passwd_get_cb);
    success=SSL_CTX_use_PrivateKey_file(section->ctx, section->key,
        SSL_FILETYPE_PEM);
    /* invoke the UI on subsequent calls */
    SSL_CTX_set_default_passwd_cb(section->ctx, cache_passwd_set_cb);

    /* invoke the UI */
    for(i=0; !success && i<3; i++) {
        if(!ui_retry())
            break;
        if(i==0) { /* silence the cached attempt */
            ERR_clear_error();
        } else {
            sslerror_queue(); /* dump the error queue */
            s_log(LOG_ERR, "Wrong passphrase: retrying");
        }
        success=SSL_CTX_use_PrivateKey_file(section->ctx, section->key,
            SSL_FILETYPE_PEM);
    }
    if(!success) {
        sslerror("SSL_CTX_use_PrivateKey_file");
        return 1; /* FAILED */
    }
```
First, we try to use the cached password. After that, we change the callback to the one that really asks user for a password, and try to get it, if current state permits (see `ui_retry`)

The `ui_retry` finction:
```
int ui_retry() {
    unsigned long err=ERR_peek_error();

    switch(ERR_GET_LIB(err)) {
    case ERR_LIB_ASN1:
        return 1;
    case ERR_LIB_PKCS12:
        switch(ERR_GET_REASON(err)) {
        case PKCS12_R_MAC_VERIFY_FAILURE:
            return 1;
        default:
            return 0;
        }
    case ERR_LIB_EVP:
        switch(ERR_GET_REASON(err)) {
        case EVP_R_BAD_DECRYPT:
            return 1;
        default:
            return 0;
        }
    case ERR_LIB_PEM:
        switch(ERR_GET_REASON(err)) {
        case PEM_R_BAD_PASSWORD_READ:
            return 1;
        default:
            return 0;
        }
    case ERR_LIB_UI:
        switch(ERR_GET_REASON(err)) {
        case UI_R_RESULT_TOO_LARGE:
        case UI_R_RESULT_TOO_SMALL:
            return 1;
        default:
            return 0;
        }
    case ERR_LIB_USER: /* PKCS#11 hacks */
        switch(ERR_GET_REASON(err)) {
        case 7UL: /* CKR_ARGUMENTS_BAD */
        case 0xa0UL: /* CKR_PIN_INCORRECT */
            return 1;
        default:
            return 0;
        }
    default:
        return 0;
    }
}
```

I'll see what happens in ui_retry a bit later.

**Comment by beldmit** [comment]
OpenSSL currently returns `ERR_LIB_OSSL_DECODER` as lib (this changed since 1.1.1) and 524556 as a reason (didn't get quickly enough how to decode). Stunnel 5.58 doesn't know about `ERR_LIB_OSSL_DECODER` so it just return "stop processing".

**Comment by mattcaswell** [comment]
It is expected that some error codes may have changed between 1.1.1 and 3.0. We should probably have something in the migration guide about this (I couldn't find anything).

**Comment by beldmit** [comment]
It looks like we tried to decode private key with empty password, got the PKCS#12 error in the end of the internal libcrypto chain of fallbacks, and returned this error. @levitte, does it make sense?

@mattcaswell, I'm not sure I agree with you, it looks like a decoder fallback problem to me.

**Comment by mattcaswell** [comment]
> It looks like we tried to decode private key with empty password

Why is the password empty?

>  got the PKCS#12 error in the end of the internal libcrypto chain of fallbacks, and returned this error

So, its tried lots of different things, failed with all of them, and this is the set of errors it got from the last thing it tried?

**Comment by beldmit** [comment]
> > It looks like we tried to decode private key with empty password
> 
> Why is the password empty?

It's a first try to load the key, so it has no idea what is inside the file.

> > got the PKCS#12 error in the end of the internal libcrypto chain of fallbacks, and returned this error
> 
> So, its tried lots of different things, failed with all of them, and this is the set of errors it got from the last thing it tried?

Yes. In 1.1.1 it would try just PKCS#8 stuff without fallback to PKCS#12

**Comment by mattcaswell** [comment]
So, I tried creating a simple reproducer:

```` C
#include <openssl/ssl.h>
#include <openssl/err.h>

int main(void)
{
    int ret;
    SSL_CTX *ctx = SSL_CTX_new(TLS_method());

    ret = SSL_CTX_use_PrivateKey_file(ctx, "key.pem", SSL_FILETYPE_PEM);

    if (!ret) {
        printf ("Failed to load key\n");
        ERR_print_errors_fp(stdout);
    }

    return 0;
}
````

Running this code against beta1 and supplying a bad password I get this:

````
80925640857F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers/implementations/ciphers/ciphercommon_block.c:124:
80925640857F0000:error:11800074:PKCS12 routines:PKCS12_pbe_crypt_ex:pkcs12 cipherfinal error:crypto/pkcs12/p12_decr.c:86:maybe wrong password
80925640857F0000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:97:No supported data to decode. Input type: PEM
80925640857F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers/implementations/ciphers/ciphercommon_block.c:124:
80925640857F0000:error:11800074:PKCS12 routines:PKCS12_pbe_crypt_ex:pkcs12 cipherfinal error:crypto/pkcs12/p12_decr.c:86:maybe wrong password
80925640857F0000:error:0A080009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib:ssl/ssl_rsa.c:384:
````
Which looks similar to the errors you were seeing in stunnel for beta1. In master I get slightly different output:

````
8062504AF57F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers/implementations/ciphers/ciphercommon_block.c:124:
8062504AF57F0000:error:11800074:PKCS12 routines:PKCS12_pbe_crypt_ex:pkcs12 cipherfinal error:crypto/pkcs12/p12_decr.c:86:maybe wrong password
8062504AF57F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers/implementations/ciphers/ciphercommon_block.c:124:
8062504AF57F0000:error:11800074:PKCS12 routines:PKCS12_pbe_crypt_ex:pkcs12 cipherfinal error:crypto/pkcs12/p12_decr.c:86:maybe wrong password
8062504AF57F0000:error:0A080009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib:ssl/ssl_rsa.c:384:
````

And in 1.1.1 I get:

````
140696840958592:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:610:
140696840958592:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:crypto/pkcs12/p12_decr.c:62:
140696840958592:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:crypto/pkcs12/p12_decr.c:93:
140696840958592:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:crypto/pem/pem_pkey.c:88:
140696840958592:error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib:ssl/ssl_rsa.c:537:
````

Note that both in 1.1.1 and master the failure occurs in the PKCS12 PBE code - so this is consistent across the versions. In master you additionally get the extra text "maybe wrong password" which you didn't get before (although stunnel seems to suppress this).

The error codes have changed but essentially the same processing seems to have taken place.

There is a slight oddity in the master output above. You can see that the error codes are repeated twice. This appears to be due to this code:

https://github.com/openssl/openssl/blob/c6fcd88fa030da8322cf27aff95376512f41faff/crypto/pem/pem_pkey.c#L232-L243

i.e., we initially try with the decoders. If that fails then we try again with legacy. I'm not entirely clear why this is necessary - but may be correct (if surprising).

So, this still looks to me like a documentation problem, i.e. the error codes have changed between 1.1.1 and master.

**Comment by beldmit** [comment]
Many thanks! I'm now convinced it's not an openssl regression. I can either close this issue or leave it as a documentation issue.

**Comment by paulidale** [comment]
Better closed I think.  It can still be searched for.
