### ISSUE TITLE
OpenSSL 1.1.0a version info wrong

### ISSUE THREAD

**Issue by thorn1976** [openssl/openssl#1615]
OpenSSL 1.1.0a returns a wrong version info when being executed from the command line :

x@y:~/Downloads> /usr/local/ssl/bin/openssl version
OpenSSL 1.0.2h  3 May 2016

Interestingly, the info is correct when being queried interactively from within openssl:

x@x:~/Downloads> /usr/local/bin/openssl 
OpenSSL> version
OpenSSL 1.1.0a  22 Sep 2016
OpenSSL> quit

**Comment by levitte** [comment]
Look at the paths you're using. They're different.

**Comment by thorn1976** [comment]
Yeah - right, seems I would have needed more coffee before opening the issue, sorry

**Comment by levitte** [comment]
No biggie. Good morning (it is morning where I live)
