### ISSUE TITLE
Performance worsening from 1.0.2d to 1.0.2g

### ISSUE THREAD

**Issue by mparis** [openssl/openssl#1616]
Hello,
I have came across a relevant performance worsening when updating from version 1.0.2d to 1.0.2g.
Specifically, I have noticed it using libsrtp [1](which has not been changed) to encrypt (srtp_protect) and decrypt (srtp_unprotect) RTP packets.

Analysing with callgrind a case where audio RTP packets are encrypted and decrypted, I have measured a worsening of ~17%, which is too big.

The results show the next differences between both versions (even there could be more):

**aes_icm_openssl_set_iv**
- 1.0.2d: 1100 CPU cycles per call
- 1.0.2g: 1700 CPU cycles per call

**hmac_compute**
- 1.0.2d: 4300 CPU cycles per call
- 1.0.2g: 5200 CPU cycles per call

From this observation I have few questions:
- Is this normal?
- Could a bug have been added?
- What could we do to improve the performance?

Thanks!!

Refs
[1] https://github.com/cisco/libsrtp/

**Comment by dot-asm** [comment]
I don't any changes between 1.0.2d and 1.0.2g that could affect performance that much. If we consider aes_icm_openssl_set_iv there were no changes. I would guess it's about specific configurations than versions. In other words where do these two come from and how they were compiled, i.e. config flags...

**Comment by mparis** [comment]
OK, I will check it.
Thanks for the help!!

**Comment by richsalz** [comment]
if you find anything, please post and re-open the issue.
