### ISSUE TITLE
Unable to trigger config file based fips algorithms being forced

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#16166]
With a configuration file only loading the default provider things still work.

```
[algorithm_sect]
default_properties = "fips=yes"

```

When adding the following into the code the expected behaviour (of no algorithms that meet the requirement) happens.

`EVP_default_properties_enable_fips(NULL,1) 
`

I hit this when testing with a deliberately invalid fips module checksum and expected that any fallback to default would be blocked by the configuration file setting. It appears to not be the case and I believe this is a change from prior testing although I have not gone and tried to reproduce this on earlier releases.

**Comment by mattcaswell** [comment]
The problem is that if a provider is configured for use in the config file, but it fails to load then we abandon all further loading of the config file and give up. My proposed solution is not treat a failure to load a provider as a fatal error.

**Comment by mattcaswell** [comment]
Fix in #16168
