### ISSUE TITLE
Is there sample code that show how to implement RSA_meth_new() series of functions used in an engine to a provider?

### ISSUE THREAD

**Issue by qunying** [openssl/openssl#16181]
Since the ENGINE interface is depreciated in 3.0, is there a sample code that show how to make a conversion from an engine code to an provider like the used of RAS_meth_new()?

**Comment by mattcaswell** [comment]
I'd start by reading these two pages:

https://www.openssl.org/docs/manmaster/man7/provider.html
https://www.openssl.org/docs/manmaster/man7/provider-base.html

There is an example provider on the second of those pages.

**Comment by qunying** [comment]
I have read that and have implemented a simple RNG provider, that works. For this RSA method, let's say I just need to replace the `bn_mod_exp` method function, I am having a hard time to find a suitable entry point in provider. Is there anyway the existing code in `bn_mod_exp` could be reused, or it is totally not usable under current provider?

**Comment by t8m** [comment]
Unfortunately there is no simple way how to modify only some part of the RSA implementation via a new provider. You would have to do a whole new RSA implementation in the provider.
