### ISSUE TITLE
The result length value (strlen) of the OPENSSL_buf2hexstr_ex function is 1 greater than the actual length.

### ISSUE THREAD

**Issue by neoniemand** [openssl/openssl#16184]
openssl version : OpenSSL 3.0.0-beta3-dev  (Library: OpenSSL 3.0.0-beta3-dev )
os version : Linux ubuntu 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
gcc version : gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

The length value of hex string comes out by 1 more. Is there any reason it should be?

[Source]
```
int main(int argc, char *argv[])
{
	int i = 0;
    
    long len;
    long hexlen;
    
    unsigned char *buf = NULL;
    char *out = NULL;
    
    char cText[256];
    char out2[64];

    printf("cHEX=[61626364]\n");
    buf = OPENSSL_hexstr2buf("61626364", &len);
    memset(cText, 0x00, sizeof(cText));
    memcpy(cText, buf, len);
    printf("cBIN=[%s] length=[%ld]\n", cText, len);
   
    OPENSSL_buf2hexstr_ex(out2, sizeof(out2), &hexlen, buf, len, ':');
    memset(cText, 0x00, sizeof(cText));
    memcpy(cText, out2, hexlen);
    printf("cHEX=[%s] length=[%ld]\n", cText, hexlen);

    OPENSSL_buf2hexstr_ex(out2, sizeof(out2), &hexlen, buf, len, '\0');
    memset(cText, 0x00, sizeof(cText));
    memcpy(cText, out2, hexlen);
    printf("cHEX=[%s] length=[%ld]\n", cText, hexlen);

    return 0;
}
```
When I run the above source, it comes out as below.

[Result]
```
julian@ubuntu:/data/crypto/evp$ ./openssl_hex_test
cHEX=[61626364]
cBIN=[abcd] length=[4]
cHEX=[61:62:63:64] length=[12]     <-- Shouldn't it be 11?
cHEX=[61626364] length=[9]        <-- Shouldn't it be 8?
julian@ubuntu:/data/crypto/evp$ 

```

The buf2hexstr_sep function of o_str.c is coded like this.
size_t len = has_sep ? buflen * 3 : 1 + buflen * 2;

But maybe the below is correct?
size_t len = has_sep ? buflen * 3 -1 : buflen * 2;

**Comment by paulidale** [comment]
These functions are adding a '\0' terminator to the string.  That's where the extra character comes from.
This is required if you are going to allocate a buffer to put the string into.
