### ISSUE TITLE
fips.dll doesn't get installed in prefix folder

### ISSUE THREAD

**Issue by wbeck10** [openssl/openssl#16194]
1. Configure openssl with a prefix folder, debug mode and enabled-fips for windows x64 msvc (VC-WIN64A).
2. Build OpenSSL calling nmake
3. Call nmake install
4. Check prefix folder /lib/ossl-modules
=> The fips.pdb is in this folder but not the fips.dll.

**Comment by paulidale** [comment]
Having the actually commands used would be useful.

**Comment by wbeck10** [comment]
Here are my perl args from configdata.pm
    "perlargv" => [
        "--debug",
        "--prefix=C:\\Users\\beckw\\trunk\\osslinst",
        "enable-fips",
        "no-shared",
        "no-asm",
        "--openssldir=ssl",
        "VC-WIN64A"

**Comment by paulidale** [comment]
FIPS and no shared are exclusive.  The FIPS provider **must** be loadable.

The configure ought to report an error in this situation.

**Comment by wbeck10** [comment]
Why should no-shared cause an error? I need an option to create a static openssl libs but I need to have the dynamic fips library available as well. In fact using my command the build is fine. I have static linkable openssl libs and I have legacy.dll and fips.dll in the provider folder. The issue is more about the deployment (calling nmake install). The fips.dll doesn't get deployed in the <prefix>/lib/ossl-modules folder, but the legacy.dll does.

**Comment by t8m** [comment]
Ah, you're right, the no-shared is not the actual cause of the error.

**Comment by t8m** [comment]
`nmake install_fips` should work as a workaround. The fix is in #16208
