### ISSUE TITLE
Issues with valid certificate validation when upgrading from 1.0.1h to 1.1.1d

### ISSUE THREAD

**Issue by RadulescuValentin** [openssl/openssl#16218]
Hi,

We were using OpenSSL version 1.0.1h and we decided to update to OpenSSL  1.1.1d.
We are using a certificate with  Signature algorithm name: SHA1withRSA.
The certificate validation works fine in 1.0.2:
> openssl verify  -CAfile ./ca.pem ./test.pem
./test.pem: OK
> openssl version
OpenSSL 1.0.1h 5 Jun 2014

But when trying to use the certificate in the uplifted OpenSSL we get errors:
openssl verify -show_chain -CAfile ca.pem test.pem
***
error 7 at 0 depth lookup: certificate signature failure
error test.pem: verification failed
140159498815232:error:04091068:rsa routines:int_rsa_verify:bad signature:crypto/rsa/rsa_sign.c:220:
140159498815232:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto/asn1/a_verify.c:170:
openssl version
OpenSSL 1.1.1d 10 Sep 2019

The certificate should be valid to Tue Nov 26 08:56:53 CET 2030.
The issue appears in int_rsa_verify.
decrypt_len = RSA_public_decrypt((int)siglen, sigbuf, decrypt_buf, rsa,
                                     RSA_PKCS1_PADDING);
.....
        if (!encode_pkcs1(&encoded, &encoded_len, type, m, m_len))
            goto err;
The encoded_len and decrypt_len differ and also the decrypt_buf and encoded differ for the certificate.

**Comment by t8m** [comment]
How was the test.pem certificate issued?Which software issued it?

**Comment by mattcaswell** [comment]
This issue is stale with no response to the last questions. Closing.
