### ISSUE TITLE
Windows 10 x64  cannot link - missing OPENSSL_UplinkTable 

### ISSUE THREAD

**Issue by PeterBocan** [openssl/openssl#1621]
Hello guys, I've tried to compile the latest OpenSSL 1.1,0 x64 on Windows 10 (Visual Studio 2015) as VC-WIN64A and this is what happened. The compilation went smoothly on x86 build, not quite sure what happened here.

```
IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\PETERB~1\AppData\Local\Temp\nmB07C.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
   Creating library libcrypto.lib and object libcrypto.exp
b_dump.obj : error LNK2001: unresolved external symbol OPENSSL_UplinkTable
bss_fd.obj : error LNK2001: unresolved external symbol OPENSSL_UplinkTable
bss_file.obj : error LNK2001: unresolved external symbol OPENSSL_UplinkTable
libcrypto-1_1.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: 'link' : return code '0x1'
Stop.
```

**Comment by dot-asm** [comment]
How does crypto\uplink-x86_64.asm read? If it's about 10KB, then what happens if you delete crypto\uplink-x86_64.obj and re-run nmake? If it's less than 10KB what happens if you delete it and re-run nmake?

**Comment by PeterBocan** [comment]
I removed that object file, ran nmake, and it worked! Thanks!

**Comment by dot-asm** [comment]
I assume that answer to the first question, i.e. "how does uplink-x86_64.asm read", is "looks sensible, it's about 10KB large". Similar issue was reported earlier and failure was attributed to antivirus software. It apparently can introduce race condition when assembler is asked to assemble not yet written file. As result an .obj file without symbols was generated, yet upon inspection of .asm file it appeared perfectly sane. This is why removing .obj file can help, and apparently did even in this case.

**Comment by eternalego** [comment]
Was trying to build OpenSSL 1.1.1s x64 on Windows 8.1 (Visual Studio 2015) as VC-WIN64A and experienced the same issue. Unfortunately, .obj removal didn't help. Moreover, I am trying to build with no-asm option, seems it has been ignored.
