### ISSUE TITLE
when I build the macos project   I got an error    Undefined symbol: _d2i_X509_AUX. But i had import openssl . I click the api  d2i_X509_AUX, I can jump  into  the openssl  lib I don't  know what's the problem.  the openssl version is 1.1.1   the macOS version is 10.15.7  Xcode version is 12.4

### ISSUE THREAD

**Issue by DonyFang** [openssl/openssl#16222]
//
//  DDNetworkManager.m
//  duplusworkhelper
//
//  Created by nobody
//

#import "DDNetworkManager.h"
#import <netinet/in.h>
#include <ifaddrs.h>
#include <AFNetworking/AFNetworking.h>
#import "DDInfoManager.h"
#import <Sparkle/Sparkle.h>
#import <openssl/x509.h>
#import <openssl/asn1.h>
//#import <openssl/x509v3.h>
//#import <openssl/x509_vfy.h>
//#import <openssl/x509err.h>
//#import <openssl/x509v3err.h>
//#import <openssl/pem.h>
//#import <openssl/pkcs12.h>
#define HTTP_REQUEST_TIMEOUT 30.f

@implementation DDNetworkManager

+ (void)connect{
//    PATCH https://10.179.130.105:1443/api/v1/node/{mac_address}
    AFHTTPSessionManager *smanager = [[AFHTTPSessionManager manager] initWithBaseURL:[NSURL URLWithString:DD_URL_DOMAIN]];
    smanager.requestSerializer = [AFJSONRequestSerializer serializer];
    smanager.responseSerializer = [AFHTTPResponseSerializer serializer];
    smanager.requestSerializer.timeoutInterval = HTTP_REQUEST_TIMEOUT;
    [smanager.securityPolicy setAllowInvalidCertificates:YES];
    smanager.securityPolicy.validatesDomainName = NO;

    NSString *token = [NSString stringWithFormat:@"%@",[[NSUserDefaults standardUserDefaults] valueForKey:@"cer_token"]];

    [smanager.requestSerializer setValue:token forHTTPHeaderField:@"Authorization"];
    [smanager.requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    NSLog(@"header=%@",    smanager.requestSerializer.HTTPRequestHeaders);
    
    [smanager POST:@"https://10.179.130.105:1443/api/v1/nodes" parameters:@{@"mac": @"14:7d:da:dc:38:6f",
                                                                            @"status": @"reg",
                                                                            @"pid": @"shao",
                                                                            @"category_id": @"10",
                                                                            @"unreg_date": @"",
                                                                            @"notes": @"shao",
                                                                            @"unregdate": @"2021-08-0 00:00:00"} progress:^(NSProgress * _Nonnull uploadProgress) {
        
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSDictionary *dic = [NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingMutableLeaves error:nil];
        NSLog(@"dic===%@",dic);
        
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        
    }];
    
   
}

+ (void)downCerFilesuccess:(void(^)(id data))success
failure:(void(^)(id data))failure
{
    //1.创建会话管理者
       AFHTTPSessionManager *manager =[AFHTTPSessionManager manager];
        manager.requestSerializer = [AFJSONRequestSerializer serializer];
        manager.responseSerializer = [AFHTTPResponseSerializer serializer];
        manager.requestSerializer.timeoutInterval = HTTP_REQUEST_TIMEOUT;
        [manager.securityPolicy setAllowInvalidCertificates:YES];
        manager.securityPolicy.validatesDomainName = NO;
       NSString *token = [NSString stringWithFormat:@"%@",[[NSUserDefaults standardUserDefaults] valueForKey:@"cer_token"]];
       [manager.requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
       NSURL *url = [NSURL URLWithString:@"https://10.179.130.105:1443/api/v1/pki/cert/shao/download/123456"];
       NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
       request.HTTPMethod = @"GET";
       request.allHTTPHeaderFields = @{@"Authorization":token};
       //2.下载文件
       /*
        第一个参数:请求对象
        第二个参数:progress 进度回调 downloadProgress
        第三个参数:destination 回调(目标位置)
                   有返回值
                   targetPath:临时文件路径
                   response:响应头信息
        第四个参数:completionHandler 下载完成之后的回调
                   filePath:最终的文件路径
        */
//    NSLog(@"header=%@",    manager.requestSerializer.HTTPRequestHeaders);
       NSURLSessionDownloadTask *download = [manager downloadTaskWithRequest:request progress:^(NSProgress * _Nonnull downloadProgress) {
           //监听下载进度
           //completedUnitCount 已经下载的数据大小
           //totalUnitCount     文件数据的中大小
           NSLog(@"%f",1.0 *downloadProgress.completedUnitCount / downloadProgress.totalUnitCount);
    
       } destination:^NSURL * _Nonnull(NSURL * _Nonnull targetPath, NSURLResponse * _Nonnull response) {
    
           NSString *fullPath = [[NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject] stringByAppendingPathComponent:response.suggestedFilename];
    
           NSLog(@"targetPath:%@",targetPath);
           NSLog(@"fullPath:%@",fullPath);
           [self getClientCertificate:fullPath];
           
//           [self connect];
           return [NSURL fileURLWithPath:fullPath];
       } completionHandler:^(NSURLResponse * _Nonnull response, NSURL * _Nullable filePath, NSError * _Nullable error) {
    
           NSLog(@"%@",filePath);
       }];
    
       //3.执行Task
       [download resume];
}

static NSString * CertificateGetIssuerName(X509 *certificateX509)
{
    NSString *issuer = nil;
    if (certificateX509 != NULL) {
     X509_NAME *issuerX509Name = X509_get_issuer_name(certificateX509);

     if (issuerX509Name != NULL) {
      int nid = OBJ_txt2nid("O"); // organization
      int index = X509_NAME_get_index_by_NID(issuerX509Name, nid, -1);

      X509_NAME_ENTRY *issuerNameEntry = X509_NAME_get_entry(issuerX509Name, index);

      if (issuerNameEntry) {
       ASN1_STRING *issuerNameASN1 = X509_NAME_ENTRY_get_data(issuerNameEntry);

       if (issuerNameASN1 != NULL) {
       const unsigned char *issuerName = ASN1_STRING_data(issuerNameASN1);
        issuer = [NSString stringWithUTF8String:(char *)issuerName];
       }
      }
     }
    }

    return issuer;
}

static NSDate *CertificateGetExpiryDate(X509 *certificateX509)
{
    NSDate *expiryDate = nil;

    if (certificateX509 != NULL) {
     ASN1_TIME *certificateExpiryASN1 = X509_get_notAfter(certificateX509);
     if (certificateExpiryASN1 != NULL) {
      ASN1_GENERALIZEDTIME *certificateExpiryASN1Generalized = ASN1_TIME_to_generalizedtime(certificateExpiryASN1, NULL);
      if (certificateExpiryASN1Generalized != NULL) {
          const  unsigned char *certificateExpiryData = ASN1_STRING_data(certificateExpiryASN1Generalized);

       // ASN1 generalized times look like this: "20131114230046Z"
       //        format: YYYYMMDDHHMMSS
       //        indices:
       //             1111
       // There are other formats (e.g. specifying partial seconds or
       // time zones) but this is good enough for our purposes since
       // we only use the date and not the time.
       //
       // (Source: http://www.obj-sys.com/asn1tutorial/node14.html)

       NSString *expiryTimeStr = [NSString stringWithUTF8String:(char *)certificateExpiryData];
       NSDateComponents *expiryDateComponents = [[NSDateComponents alloc] init];

       expiryDateComponents.year = [[expiryTimeStr substringWithRange:NSMakeRange(0, 4)] intValue];
       expiryDateComponents.month = [[expiryTimeStr substringWithRange:NSMakeRange(4, 2)] intValue];
       expiryDateComponents.day = [[expiryTimeStr substringWithRange:NSMakeRange(6, 2)] intValue];
       expiryDateComponents.hour = [[expiryTimeStr substringWithRange:NSMakeRange(8, 2)] intValue];
       expiryDateComponents.minute = [[expiryTimeStr substringWithRange:NSMakeRange(10, 2)] intValue];
       expiryDateComponents.second = [[expiryTimeStr substringWithRange:NSMakeRange(12, 2)] intValue];

       NSCalendar *calendar = [NSCalendar currentCalendar];
       expiryDate = [calendar dateFromComponents:expiryDateComponents];

//       [expiryDateComponents release];
      }
     }
    }

    return expiryDate;
}
//- (void)search{
//    NSString *thePath = [[NSBundle mainBundle]
//                         pathForResource:@"Romeo Montague" ofType:@"cer"];
//    NSData *certData = [[NSData alloc]
//                        initWithContentsOfFile:thePath];
//    CFDataRef myCertData = (__bridge CFDataRef)certData;                 // 1
//
//    SecCertificateRef myCert;
//    myCert = SecCertificateCreateWithData(NULL, myCertData);    // 2
//
//    SecPolicyRef myPolicy = SecPolicyCreateBasicX509();         // 3
//
//    SecCertificateRef certArray[1] = { myCert };
//    CFArrayRef myCerts = CFArrayCreate(
//                                       NULL, (void *)certArray,
//                                       1, NULL);
//    SecTrustRef myTrust;
//    OSStatus status = SecTrustCreateWithCertificates(
//                                                     myCerts,
//                                                     myPolicy,
//                                                     &myTrust);  // 4
//
//    SecTrustResultType trustResult;
//    if (status == noErr) {
//        status = SecTrustEvaluate(myTrust, &trustResult);       // 5
//    }
//    //...                                                             // 6
//    if (trustResult == kSecTrustResultRecoverableTrustFailure) {
//        // ...;
//    }
//    // ...
//    if (myPolicy)
//        CFRelease(myPolicy);
//
//}
//+(NSString *)copySummaryString:(SecIdentityRef)identity
//{
//// Get the certificate from the identity.
//SecCertificateRef myReturnedCertificate = NULL;
//OSStatus status = SecIdentityCopyCertificate (identity,
//                                              &myReturnedCertificate);  // 1 从证书中提取身份
//
//if (status) {
//    NSLog(@"SecIdentityCopyCertificate failed.\n");
//    return NULL;
//}
//
//CFStringRef certSummary = SecCertificateCopySubjectSummary
//(myReturnedCertificate);  // 2 从证书中获取概要信息。
//
//NSString* summaryString = [[NSString alloc]
//                           initWithString:(__bridge NSString *)certSummary];  // 3转换string为NSString对象
//
//CFRelease(certSummary);    //4 释放NSString对象
//
//return summaryString;
//}
//我已经从文件系统成功加载了.p12证书：
+ (SecIdentityRef)getClientCertificate:(NSString *) certificatePath {
    
    SecIdentityRef identity = nil;
    NSData *PKCS12Data = [NSData dataWithContentsOfFile:certificatePath];
    CFDataRef inPKCS12Data = (__bridge CFDataRef)PKCS12Data;
    CFStringRef password = CFSTR("123456");
    const void *keys[] = { kSecImportExportPassphrase };
    const void *values[] = { password };
    CFDictionaryRef options = CFDictionaryCreate(NULL, keys, values, 1, NULL, NULL);
    
    SecTrustRef trust = NULL;
//    [self recoverFromTrustFailure:trust];
    CFArrayRef items = CFArrayCreate(NULL, 0, 0, NULL);
    OSStatus securityError = SecPKCS12Import(inPKCS12Data, options, &items);
    CFRelease(options);
    CFRelease(password);
    if (securityError == errSecSuccess) {
        NSLog(@"Success opening p12 certificate. Items: %ld", CFArrayGetCount(items));
        CFDictionaryRef identityDict = CFArrayGetValueAtIndex(items, 0);
        identity = (SecIdentityRef) CFDictionaryGetValue(identityDict, kSecImportItemIdentity);
    } else {
        NSLog(@"Error opening Certificate.");
    }

    return identity;
}

+ (CFArrayRef)getCertificate:(SecIdentityRef) identity {
    SecCertificateRef certificate = nil;

    SecIdentityCopyCertificate(identity, &certificate);
    SecCertificateRef certs[1] = { certificate };
    
    
    NSData *certificateData = (NSData *) CFBridgingRelease(SecCertificateCopyData(certificate));

    const unsigned char *certificateDataBytes = (const unsigned char *)[certificateData bytes];

    X509 *certificateX509 = d2i_X509_AUX(NULL, &certificateDataBytes, [certificateData length]);

    
    CFArrayRef array = CFArrayCreate(NULL, (const void **) certs, 1, NULL);
    SecPolicyRef myPolicy = SecPolicyCreateBasicX509();
    SecTrustRef myTrust;

    OSStatus status = SecTrustCreateWithCertificates(array, myPolicy, &myTrust);
    if (status == noErr) {
        NSLog(@"No Err creating certificate");
    } else {
        NSLog(@"Possible Err Creating certificate");
    }
    return array;
}

//+(void)recoverFromTrustFailure:(SecTrustRef)myTrust
//{
//SecTrustResultType trustResult;
//OSStatus status = SecTrustEvaluate(myTrust, &trustResult);  // 1
//
////Get time used to verify trust
//CFAbsoluteTime trustTime,currentTime,timeIncrement,newTime;
//CFDateRef newDate;
//if (trustResult == kSecTrustResultRecoverableTrustFailure) {// 2
//    trustTime = SecTrustGetVerifyTime(myTrust);             // 3
//    timeIncrement = 31536000;                               // 4
//    currentTime = CFAbsoluteTimeGetCurrent();               // 5
//    newTime = currentTime - timeIncrement;                  // 6
//    if (trustTime - newTime){                               // 7
//        newDate = CFDateCreate(NULL, newTime);              // 8
//        SecTrustSetVerifyDate(myTrust, newDate);            // 9
//        status = SecTrustEvaluate(myTrust, &trustResult);   // 10
//    }
//}
//if (trustResult != kSecTrustResultProceed) {                // 11
//    //...
//
//   }
//}

+ (void)getRequestWithUrl:(NSString*)url
               parameters:(NSDictionary*)params
                 showInfo:(BOOL)showInfo
                   inView:(NSView*)view
                  success:(void(^)(id data))success
                  failure:(void(^)(id data))failure
{
    if (![DDNetworkManager checkOnlineInView:view]) {
        NSMutableDictionary *info = nil;
        if (showInfo) {
            info = [[NSMutableDictionary alloc] init];
            info[@"msg"] = DDLocalMsg(@"抱歉,网络不可用,请检查网络");
            [FNHUD showMessage:DDLocalMsg(@"抱歉,网络不可用,请检查网络") inView:[NSApplication sharedApplication].keyWindow.contentView];
        }
        if (failure) {
            failure(info);
        }
        return;
    }
    
    AFHTTPSessionManager *smanager = [[AFHTTPSessionManager manager] initWithBaseURL:[NSURL URLWithString:DD_URL_DOMAIN]];
    [smanager setSessionDidReceiveAuthenticationChallengeBlock:^NSURLSessionAuthChallengeDisposition(NSURLSession * _Nonnull session, NSURLAuthenticationChallenge * _Nonnull challenge, NSURLCredential * _Nullable __autoreleasing * _Nullable credential) {
        NSURLProtectionSpace *protectionSpcae = challenge.protectionSpace;
        SecTrustRef trust = protectionSpcae.serverTrust;
        long n = SecTrustGetCertificateCount(trust);
        SecCertificateRef cert = SecTrustGetCertificateAtIndex(trust, n-1);
        SecTrustRef myTrust;
        OSStatus status = SecTrustCreateWithCertificates(cert, SecPolicyCreateBasicX509(), &myTrust);
        SecTrustResultType trustResult;
        if (status == noErr) {
            status = SecTrustEvaluate(myTrust, &trustResult);
            if (trustResult == kSecTrustResultUnspecified) {
                return NSURLSessionAuthChallengePerformDefaultHandling;
            }
        }
        
        return NSURLSessionAuthChallengeCancelAuthenticationChallenge;
    }];
    smanager.requestSerializer = [AFJSONRequestSerializer serializer];
    smanager.responseSerializer = [AFHTTPResponseSerializer serializer];
    smanager.requestSerializer.timeoutInterval = HTTP_REQUEST_TIMEOUT;
    [smanager.securityPolicy setAllowInvalidCertificates:YES];
    smanager.securityPolicy.validatesDomainName = NO;
    [self handlerHeader:smanager params:params];
    
    [smanager GET:url parameters:[DDNetworkManager handleParams:params url:url] progress:^(NSProgress * _Nonnull uploadProgress) {
        ;
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {

        NSDictionary *dic = [NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingMutableLeaves error:nil];
        
        if (dic) {
            if (showInfo && [dic[@"msg"] length]) {
                [FNHUD showMessage:dic[@"msg"] inView:[NSApplication sharedApplication].keyWindow.contentView];
            }
            
            if (success && [dic[@"code"] intValue] == 0) {
                success(dic);
            }else{
                if ([dic[@"code"] intValue] >= 100 && [dic[@"code"] intValue] < 200) {
                    DDLocal *local = [DDUserManager sharedInstance].local;
                    local.token = nil;
                    [[DDUserManager sharedInstance] setLocal:local];
                }else if ([dic[@"code"] intValue] == 888){
                    [[SUUpdater sharedUpdater] installUpdatesIfAvailable];
                }
                if (failure) {
                    failure(dic);
                }
            }
        }else{
            if (showInfo) {
                [FNHUD showMessage:DDLocalMsg(@"抱歉,网络开小差了,请稍后重试") inView:[NSApplication sharedApplication].keyWindow.contentView];
            }
            if (failure) {
                failure(dic);
            }
        }
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSMutableDictionary *info = nil;
        if (showInfo) {
            info = [[NSMutableDictionary alloc] init];
            if (error.code == -999) {
                info[@"msg"] = DDLocalMsg(@"警告,系统检测到中间人劫持");
                [FNHUD showMessage:DDLocalMsg(@"警告,系统检测到中间人劫持") inView:[NSApplication sharedApplication].keyWindow.contentView];
            }else{
                info[@"msg"] = DDLocalMsg(@"抱歉,网络不可用,请检查网络");
                [FNHUD showMessage:DDLocalMsg(@"抱歉,网络不可用,请检查网络") inView:[NSApplication sharedApplication].keyWindow.contentView];
            }
        }
        if (failure) {
            failure(info);
        }
    }];
}
    
+ (void)postRequestWithUrl:(NSString*)url
                parameters:(NSDictionary*)params
                  showInfo:(BOOL)showInfo
                    inView:(NSView*)view
                   success:(void(^)(id data))success
                   failure:(void(^)(id data))failure{
    if (![DDNetworkManager checkOnlineInView:view]) {
        NSMutableDictionary *info = nil;
        if (showInfo) {
            info = [[NSMutableDictionary alloc] init];
            info[@"msg"] = DDLocalMsg(@"抱歉,网络不可用,请检查网络");
            [FNHUD showMessage:DDLocalMsg(@"抱歉,网络不可用,请检查网络") inView:[NSApplication sharedApplication].keyWindow.contentView];
        }
        if (failure) {
            failure(info);
        }
        return;
    }
    
    AFHTTPSessionManager *smanager = [[AFHTTPSessionManager manager] initWithBaseURL:[NSURL URLWithString:DD_URL_DOMAIN]];
    [smanager.requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    smanager.requestSerializer = [AFJSONRequestSerializer serializer];
    smanager.responseSerializer = [AFHTTPResponseSerializer serializer];
    smanager.requestSerializer.timeoutInterval = HTTP_REQUEST_TIMEOUT;
    [smanager.securityPolicy setAllowInvalidCertificates:YES];
    // 是否校验域名, 默认为YES
    smanager.securityPolicy.validatesDomainName = NO;
//    [self handlerHeader:smanager params:params];
    
    [smanager POST:url parameters:params progress:^(NSProgress * _Nonnull uploadProgress) {
        ;
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        
        NSDictionary *dic = [NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingMutableLeaves error:nil];
        if (dic) {
            NSString *token = [NSString stringWithFormat:@"%@",dic[@"token"]];
            [[NSUserDefaults standardUserDefaults] setValue:token forKey:@"cer_token"];
            if (showInfo && [dic[@"msg"] length]) {
                [FNHUD showMessage:dic[@"msg"] inView:[NSApplication sharedApplication].keyWindow.contentView];
            }
            
            if (success && [dic[@"code"] intValue] == 0) {
                success(dic);
            }else {
                if ([dic[@"code"] intValue] >= 100 && [dic[@"code"] intValue] < 200) {
                    DDLocal *local = [DDUserManager sharedInstance].local;
                    local.token = nil;
                    [[DDUserManager sharedInstance] setLocal:local];
                }else if ([dic[@"code"] intValue] == 888){
                    [[SUUpdater sharedUpdater] installUpdatesIfAvailable];
                }
                
                if (failure) {
                    failure(dic);
                }
            }
        }else{
            if (showInfo) {
                [FNHUD showMessage:DDLocalMsg(@"抱歉,网络开小差了,请稍后重试") inView:[NSApplication sharedApplication].keyWindow.contentView];
            }
            if (failure) {
                failure(dic);
            }
        }
        
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSMutableDictionary *info = nil;
        if (showInfo) {
            info = [[NSMutableDictionary alloc] init];
            if (error.code == -999) {
                info[@"msg"] = DDLocalMsg(@"警告,系统检测到中间人劫持");
                [FNHUD showMessage:DDLocalMsg(@"警告,系统检测到中间人劫持") inView:[NSApplication sharedApplication].keyWindow.contentView];
            }else{
                info[@"msg"] = DDLocalMsg(@"抱歉,网络不可用,请检查网络");
                [FNHUD showMessage:DDLocalMsg(@"抱歉,网络不可用,请检查网络") inView:[NSApplication sharedApplication].keyWindow.contentView];
            }
        }
        if (failure) {
            failure(info);
        }
    }];
}
    
+ (void)handlerHeader:(AFHTTPSessionManager*)smanager params:(NSDictionary*)params{

    NSUInteger n = [DDOtherManager checkSafeApp];
    
    NSDictionary *headers = @{@"timestamp":[DDInfoManager getTimestamp],
                              @"os":@"mac",
                              @"osVersion":[DDInfoManager getOSVersion],
                             @"ip":[DDInfoManager getIPAddress:[DDInfoManager getWifiDevice]],
                              @"wiredIp":[DDInfoManager getIPAddress:[DDInfoManager getEthernetDevice]],
                             @"mac":[DDInfoManager getMacAddress:[DDInfoManager getWifiDevice]],
                              @"wiredMac":[DDInfoManager getMacAddress:[DDInfoManager getEthernetDevice]],
                             @"version":[DDInfoManager getVersion],
                              @"deviceNo":[DDInfoManager getHardwareSerialNumber],
                              @"deviceType":@"mac",
                              @"user":[DDInfoManager getLoginUser],
                              @"hostname":[DDInfoManager getHostname],
                              @"safeApp":[NSString stringWithFormat:@"%d",(int)n],
                              @"token":[DDUserManager sharedInstance].local.token?[DDUserManager sharedInstance].local.token:@"",
                              @"clientID":@"", //序列号
                              @"pid":@"" //用户ID
                             };
    
    for (int i = 0 ; i < headers.allKeys.count; i++) {
        [smanager.requestSerializer setValue:headers[headers.allKeys[i]] forHTTPHeaderField:headers.allKeys[i]];
    }
    
    [smanager.requestSerializer setValue:@"" forHTTPHeaderField:@"sign"];
}

+ (NSDictionary*)handleParams:(NSDictionary*)params url:(NSString*)url{
    return params;
}
    
+ (BOOL)checkOnlineInView:(NSView*)view{
    BOOL ret = [DDNetworkManager checkOnline];
    if (!ret) {
        [FNHUD showMessage:DDLocalMsg(@"抱歉,网络不可用,请检查网络") inView:view];
    }
    return ret;
}
//检测网络状况
+ (BOOL)checkOnline{
    struct sockaddr_in zeroAddress;
    bzero(&zeroAddress, sizeof(zeroAddress));
    zeroAddress.sin_len = sizeof(zeroAddress);
    zeroAddress.sin_family = AF_INET;
    
    SCNetworkReachabilityRef target = SCNetworkReachabilityCreateWithAddress(kCFAllocatorDefault, (const struct sockaddr*)(&zeroAddress));
    if(target != NULL){
        SCNetworkReachabilityFlags netflags;
        SCNetworkReachabilityGetFlags(target, &netflags);
        CFRelease(target);
        if (
            (netflags & kSCNetworkReachabilityFlagsReachable) != 0
            &&
            (netflags & kSCNetworkReachabilityFlagsConnectionRequired) == 0
            )
        {
            return YES;
        }else{
            return NO;
        }
    }
    return NO;
}
    

- (void)downLoadCer
{
    NSURL *url = [NSURL URLWithString:@""];
    NSURLRequest *request = [NSURLRequest requestWithURL:url];
    NSURLSession *session = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration] delegate:self delegateQueue:[NSOperationQueue mainQueue]];
    NSURLSessionDataTask *dataTask = [session dataTaskWithRequest:request];
    
    [dataTask resume];

}

@end

**Comment by DonyFang** [comment]
![截屏2021-08-05 上午11 09 20](https://user-images.githubusercontent.com/15819652/128284835-bec25387-0d2c-4d56-ba92-7bfb9994365e.png)

**Comment by DonyFang** [comment]
![截屏2021-08-05 上午11 09 53](https://user-images.githubusercontent.com/15819652/128284874-028e0a5d-cfd5-4c51-a036-cf805cdf8e6e.png)

**Comment by yangyangtiantianlonglong** [comment]
ld can't find the ```d2i_X509_AUX``` definition, I guess,  you may not have the correct link to libcrypto.so

**Comment by paulidale** [comment]
That would be my guess too.

How was OpenSSL installed?  What were the configuration used to build it?

The OpenSSL project does not distribute binary files.  We only distribute source code.

**Comment by DonyFang** [comment]
> That would be my guess too.
> 
> How was OpenSSL installed? What were the configuration used to build it?
> 
> The OpenSSL project does not distribute binary files. We only distribute source code.

I install OpenSSL use homebrew.please tell me the right way to configuration it . so  I need to make the binary files by myself?

**Comment by DonyFang** [comment]
> > That would be my guess too.
> > How was OpenSSL installed? What were the configuration used to build it?
> > The OpenSSL project does not distribute binary files. We only distribute source code.
> 
> I install OpenSSL use homebrew.please tell me the right way to configuration it . so I need to make the binary files by myself?

> ld can't find the `d2i_X509_AUX` definition, I guess, you may not have the correct link to libcrypto.so

but when I click the api  d2i_X509_AUX  I can jump to the  X509 file and i can find the definition

**Comment by paulidale** [comment]
Try asking the homebrew developers for suggestions.  They packaged OpenSSL.

OpenSSL can be configured and build on MacOS.  Read the INSTALL.md file.  I am not convinced that you want to do this, homebrew is used to **avoid** having to deal with such details.

**Comment by DonyFang** [comment]
> Try asking the homebrew developers for suggestions. They packaged OpenSSL.
> 
> OpenSSL can be configured and build on MacOS. Read the INSTALL.md file. I am not convinced that you want to do this, homebrew is used to **avoid** having to deal with such details.

please tell me how to resolve the problem @
