### ISSUE TITLE
X509V3_EXT_add_conf() frees config in OpenSSL 3

### ISSUE THREAD

**Issue by nikic** [openssl/openssl#16226]
Prior to OpenSSL 3, X509V3_EXT_add_conf() did not free the passed config LHASH. This was used by PHP as follows: https://github.com/php/php-src/blob/13313d9b1b9fa014fe6f92c496477e28f4f11772/ext/openssl/openssl.c#L705-L709

Now the LHASH gets freed. This was easy to resolve on our side by switching from CONF_* to NCONF_* APIs, but I suspect the change in behavior was not intentional, thus this report.

**Comment by t8m** [comment]
Good catch! Fix in #16227
