### ISSUE TITLE
Something about "libcrypto.so" cause error when "make"

### ISSUE THREAD

**Issue by xianglingzhang** [openssl/openssl#16229]
**Environment**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

I have a proble when install openssl:
**openssl-3.0.0**  After "./config" and "make", I got this error 
```
crypto/aes/libcrypto-shlib-aes-x86_64.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:919: libcrypto.so.3] Error 1
make[1]: Leaving directory '/home/zhang/Code/openssl-master'
make: *** [Makefile:165：all] 错误 2
```

I tried **openssl-1.1.1f**, still
```
/usr/bin/ld:libcrypto.map:0: syntax error in VERSION script
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:756: libcrypto.so] Error 1
make[1]: Leaving directory '/home/zhang/Code/new_feature_test/openssl-1.1.1f'
make: *** [Makefile:174：all] 错误 2

```
How can I solve this problem?

**Comment by beldmit** [comment]
Could you please build from scratch? It looks like some sort of previous build remnants.

**Comment by Sarahtorekryo** [comment]
> **Environment**
> 
> ```
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.1 LTS
> Release:	20.04
> Codename:	focal
> ```
> 
> I have a proble when install openssl:
> **openssl-3.0.0** After "./config" and "make", I got this error
> 
> ```
> crypto/aes/libcrypto-shlib-aes-x86_64.o: file not recognized: file format not recognized
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:919: libcrypto.so.3] Error 1
> make[1]: Leaving directory '/home/zhang/Code/openssl-master'
> make: *** [Makefile:165：all] 错误 2
> ```
> 
> I tried **openssl-1.1.1f**, still
> 
> ```
> /usr/bin/ld:libcrypto.map:0: syntax error in VERSION script
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:756: libcrypto.so] Error 1
> make[1]: Leaving directory '/home/zhang/Code/new_feature_test/openssl-1.1.1f'
> make: *** [Makefile:174：all] 错误 2
> ```
> 
> How can I solve this problem?

您好，遇到了和您相同的问题，查了很久都未解决，请问您最后是怎么解决的呀？感谢~

**Comment by zhangxiang1ing** [comment]
我重装了虚拟机的系统，Ubuntu 20.04.1自带OpenSSL 1.1.1f，之前编译遇到的错误并没有解决

**Comment by Sarahtorekryo** [comment]
> 我重装了虚拟机的系统，Ubuntu 20.04.1自带OpenSSL 1.1.1f，之前编译遇到的错误并没有解决

好的，谢谢您的回复🌸
