### ISSUE TITLE
Documentation issue: "fips=yes" works for X25519, X448, Ed25519, and Ed448 in OpenSSL 3.0 beta 2

### ISSUE THREAD

**Issue by dskern-github** [openssl/openssl#16234]
https://www.openssl.org/docs/manmaster/man7/OSSL_PROVIDER-FIPS.html 
claims that X25519 and X448 have the property "provider=fips,fips=no".  However, X25519 and X448 can function with "fips=yes", in OpenSSL 3.0 beta 2, just like the NIST prime curves. 

Pseudocode: 
```
pCtx = EVP_PKEY_CTX_new_from_pkey (NULL, pAsymKey, "fips=yes");
osslErr = EVP_PKEY_derive_init (pCtx);
prov = EVP_PKEY_CTX_get0_provider (pCtx);
pName = OSSL_PROVIDER_get0_name(prov);
osslErr = EVP_PKEY_derive_set_peer (pCtx, pPeerKey);
osslErr = EVP_PKEY_derive (pCtx, pOut, &OutLen);
```

I was expecting a failure when passing in a `EVP_PKEY_X25519` or `EVP_PKEY_X448` EVP_PKEY after I switched my code from calling `EVP_PKEY_CTX_new` to calling `EVP_PKEY_CTX_new_from_pkey`, but all computations and vector-based tests succeeded, and pName returns "fips". 

I don't know if this is an issue with the documentation or an incorrect setting in the fips provider.

**Comment by dskern-github** [comment]
On a closely related note, in OpenSSL 3.0 beta 2 "fips=yes" also works in `EVP_DigestSignInit_ex` and `EVP_DigestVerifyInit_ex` with Ed25519 and Ed448.

**Comment by paulidale** [comment]
The documentation is incorrect.

**Comment by dskern-github** [comment]
I've just read all of the possibly relevant documentation that I could find to look for similar statements, since Google doesn't seem to be keeping up with the OpenSSL 3.0 doc changes.  The same statement also appears at 
https://www.openssl.org/docs/manmaster/man7/EVP_KEYMGMT-X25519.html
and a host of related links that appear to map to the same page on the back end. 
Thanks!

**Comment by paulidale** [comment]
Thanks, I'll check harder...

The story behind this is long and twisty.  X25519 et al cannot be FIPS validated currently, thus they were tagged as non-FIPS algorithms.   They are kind of handy for TLS 1.3 so they ended up in the provider.  Later, our lab confirmed that they could be vendor affirmed and tagged as FIPS.  There is a lot more to it than this but they've been in and out more than once now.
