### ISSUE TITLE
OpenSSL 3 deprecates CTS

### ISSUE THREAD

**Issue by frozencemetery** [openssl/openssl#16235]
Previously, it was possible to get CTS from OpenSSL by passing the appropriate `_cbc_encrypt()` to `CRYPTO_cts128_encrypt()`/`CRYPTO_cts128_decrypt()`.  These functions support multiple calls.  krb5 uses this approach for our [AES](https://github.com/krb5/krb5/blob/master/src/lib/crypto/openssl/enc_provider/aes.c#L129-L232) and [Camellia](https://github.com/krb5/krb5/blob/master/src/lib/crypto/openssl/enc_provider/camellia.c#L153-L256) enctypes.

However, OpenSSL 3 deprecates the non-EVP `_cbc_encrypt()` calls we've been using.  While we'd be fine to port to the EVP interface, "CTS mode does not support multiple calls to EVP_CipherUpdate()" (per EVP_EncryptInit_ext(3ossl)) - so we can't it.  Moreover, the only CTS-semi-enabled ciphers are AES based: for krb5's purposes, that means no Camellia.

CTS is not overly complicated, and it would be possible to implement it ourselves on top of what OpenSSL provides (that isn't deprecated).  However, given that it's both relatively common and was present before, I'd like openssl to at least consider adding it back (or not removing it, depending on how we're thinking about the issue).

Specifically, I'm asking for two things:

1. Support multiple calls to `EVP_CipherUpdate()` for CTS mode.
2. Provide CTS mode for Camellia (only matters if (1) is done).

It would also satisfy our needs to unmark `Camellia_set_key()`, `Camellia_cbc_encrypt()`, `Camellia_ecb_encrypt()`, `AES_set_encrypt_key()`, and `AES_cbc_encrypt()` as deprecated, but I don't imagine this is the preferred course of action for openssl :)

(I've previously discussed this with @beldmit, who suggested raising it here as post-3.0 work.)

**Comment by frozencemetery** [comment]
In our conversation, one possibility Dmitry suggested was passing a custom function built around EVP_EncryptXXX() to CRYPTO_cts128_encrypt() et al..  Unfortunately this would not help much, since I don't think it would update the IV.

(Right now IV updating is handled by e.g. AES_cbc_encrypt() rather than CRYPTO_cts128_encrypt() itself (and AES_cbc_encrypt() becomes CRYPTO_cbc128_encrypt()).  So our wrapper function would need to handle updating the IV, but e.g. EVP_EncryptUpdate doesn't export this information - and a `cbc128_f` (which is what CRYPTO_cts128_encrypt() takes) is otherwise stateless.)

**Comment by paulidale** [comment]
I've flagged this for an OTC call as to fix for 3.0 or not.

**Comment by slontis** [comment]
Not sure I quite understand..  Each call to CRYPTO_cts128_encrypt() is doing 2 calls to the passed in cbc function.  So this doesn't sound like it fits nicely into using it in an update? (The normal pattern in an update would be to buffer the input but this sounds like different behavior).

**Comment by frozencemetery** [comment]
> Not sure I quite understand.. Each call to CRYPTO_cts128_encrypt() is doing 2 calls to the passed in cbc function. So this doesn't sound like it fits nicely into using it in an update? 

Assuming this was in reference to designing a wrapper function, I think the suggestion was an inverse of that: make a wrapper that provides CBC to pass *to* CRYPTO_cts128_encrypt().  (And as you say, doing it the other way around won't work either.)

**Comment by slontis** [comment]
> > Not sure I quite understand.. Each call to CRYPTO_cts128_encrypt() is doing 2 calls to the passed in cbc function. So this doesn't sound like it fits nicely into using it in an update?
> 
> Assuming this was in reference to designing a wrapper function, I think the suggestion was an inverse of that: make a wrapper that provides CBC to pass _to_ CRYPTO_cts128_encrypt(). (And as you say, doing it the other way around won't work either.)

I am not talking about the ARIA support here..
Each call to CRYPTO_cts128_encrypt() is doing the swapping of the last byte every time.. The EVP_CipherUpdate() does only one of these.. All other ciphers that allow  updates - buffer the input so multiple calls to the update would result in the swapping of the last byte only happening once in the final(). This is different to what you have described.
Equivalent behavior to calling the CRYPTO_cts128_encrypt() multiple times would be be calling
Init()/Update()/Final() multiple times.

**Comment by mattcaswell** [comment]
OTC: This won't be fixed for 3.0 release. The missing Camellia implementation could be added for post 3.0.

**Comment by t8m** [comment]
#16276 is RFE for the missing Camellia CTS

**Comment by frozencemetery** [comment]
> I am not talking about the ARIA support here..
Each call to CRYPTO_cts128_encrypt() is doing the swapping of the last byte every time.. The EVP_CipherUpdate() does only one of these.. All other ciphers that allow updates - buffer the input so multiple calls to the update would result in the swapping of the last byte only happening once in the final(). This is different to what you have described.

I see, thank you for clarifying.  I was confused because the docs only talk about Final() as handling padding, but I get how that could apply.

> Equivalent behavior to calling the CRYPTO_cts128_encrypt() multiple times would be be calling Init()/Update()/Final() multiple times.

Okay.  But then how is the IV passed between multiple sets of Init()/Update()/Final()?  Because if there's no way to, that's not equivalent behavior.

**Comment by t8m** [comment]
You can use EVP_CIPHER_CTX_get_updated_iv() to get the updated iv to be set for the next Init().

**Comment by frozencemetery** [comment]
Perfect, thanks!
