### ISSUE TITLE
An error occurs when the openssl rand-hex 10 command is executed

### ISSUE THREAD

**Issue by Ccaomei** [openssl/openssl#16243]
perform
./apps/openssl rand -hex 10

0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:

The machine information: 
Linux master001 4.19.90-1.nk7_5.18.mips64el #1 SMP PREEMPT Wed Jun 3 21:24:29 CST 2020 mips64el mips64el mips64el GNU/Linux
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Azalea)"
ID="kylin"
ID_LIKE="fedora"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Azalea)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:kylin:enterprise_linux:V10:GA:server"
HOME_URL="https://www.cs2c.com.cn/"
BUG_REPORT_URL="https://bugzilla.cs2c.com.cn/"

**Comment by t8m** [comment]
Which openssl version is this? Could you please strace the command to see which syscalls are failing?

**Comment by t8m** [comment]
No response from the reporter.
