### ISSUE TITLE
Cannot fetch OSSL_PKEY_PARAM_PUB_KEY from legacy DH key

### ISSUE THREAD

**Issue by nikic** [openssl/openssl#16247]
Fetching OSSL_PKEY_PARAM_PUB_KEY from a legacy DH does not work. The assertion in the following code fails:

```
#include <assert.h>
#include <openssl/core_names.h>
#include <openssl/dh.h>
#include <openssl/evp.h>

int main() {
	EVP_PKEY *key = EVP_PKEY_new();
	DH *dh = DH_new();
	DH_generate_parameters_ex(dh, 512, DH_GENERATOR_2, NULL);
	DH_generate_key(dh);
	EVP_PKEY_assign_DH(key, dh);

	BIGNUM *bn = NULL;
	EVP_PKEY_get_bn_param(key, OSSL_PKEY_PARAM_PUB_KEY, &bn);
	assert(bn != NULL);
	EVP_PKEY_free(key);
	return 0;
}
```

From some cursory debugging, I believe this is due to a bad interaction between https://github.com/openssl/openssl/blob/46d51520319b8e4220b203c517b1232cf33a579f/crypto/evp/ctrl_params_translate.c#L2252 and 
https://github.com/openssl/openssl/blob/46d51520319b8e4220b203c517b1232cf33a579f/crypto/evp/ctrl_params_translate.c#L659.

**Comment by t8m** [comment]
Fix in #16253
