### ISSUE TITLE
AEAD documentation fix

### ISSUE THREAD

**Issue by cmouse** [openssl/openssl#1624]
Your documentation claims that `EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, taglen, tag);` is not valid after data is read, but at the moment we are using this in application that stores the tag as last 16 bytes of data, as it is not feasible to store it to header after data has been encrypted.

Perhaps your could clarify whether it really is invalid to set TAG after data decryption has started?

This is related to https://github.com/ruby/openssl/issues/74

**Comment by mattcaswell** [comment]
Hmmmm....what mode are you using GCM or OCB?

**Comment by cmouse** [comment]
GCM.

**Comment by cmouse** [comment]
And as further clarification, setting tag just before decrypt final works just fine and produces expected results.

**Comment by mattcaswell** [comment]
The linked ruby issue says we fixed this - so closing this issue.

**Comment by cmouse** [comment]
thank you =)
