### ISSUE TITLE
OpenSSL3 regression: RSA_generate_key_ex fails with e = 17

### ISSUE THREAD

**Issue by tsdgeos** [openssl/openssl#16255]
https://www.openssl.org/docs/manmaster/man3/RSA_generate_key_ex.html says

> The exponent is an odd number, typically 3, 17 or 65537.

But if you give it 17 it will fail because it will end up with `rsa_multiprime_keygen` calling `ossl_rsa_check_public_exponent` and BN_num_bits(17) is only 5 and will fail the 

`return (BN_is_odd(e) && bitlen > 16 && bitlen < 257);`

check

**Comment by kroeckx** [comment]
I think this change is intended, and that the documentation should reflect that.

**Comment by paulidale** [comment]
This was intentional.  There are concerns with small exponents.
The documentation should be updated...

**Comment by mattcaswell** [comment]
OTC: There is an ongoing OTC vote on this issue:

topic: RSA public exponent validation in 3.0 for the default provider should be
consistent with 1.1.1

**Comment by vdukhovni** [comment]
My take is this layer of the library is not the right place to enforce floors on the public exponent. There are legitimate use-cases for small public exponents.

For example, offline DNS zone signing is performed non-interactively, and verification is fast when the public exponent is 3.  While F_4 is much more widely used and performs adequately, F_0 (3), and F_2 (17) are reasonable choices.

If a floor is to be enforced it should be in particular applications, not in the low level RSA keygen routines.

**Comment by mattcaswell** [comment]
> topic: RSA public exponent validation in 3.0 for the default provider should be
consistent with 1.1.1

This vote passed:

accepted:  yes  (for: 4, against: 2, abstained: 3, not voted: 1)
