### ISSUE TITLE
ERR_GET_FUNC(x) should result in compiler error

### ISSUE THREAD

**Issue by fweimer-rh** [openssl/openssl#16254]
Issue #15946 removed `ERR_GET_FUNC`. However, not everyone uses a C compiler that requires explicit function declarations (or a C++ compiler). As a result, builds can succeed. With ELF lazy binding, the resulting binaries may even load, and crash only if there is an error condition and there is an attempt to call this undefined function.

If `ERR_GET_FUNC(x)` resulted in a compiler error, these issues could be avoided, and programmers would notice more quickly that something is wrong. It is not clear to me whether `#ifdef ERR_GET_FUNC` needs to be supported. Maybe

```
void ERR_GET_FUNC (void);
```

plus a deprecation warning and an explanatory comment is the best approach here.

**Comment by richsalz** [comment]
I don't know that this is a feature request, so much as a bugfix.  That PR removed something, which probably should have been deprecated, as it needlessly breaks existing applications. This is the kind of thing that the project was hoping BETA releases would find -- platforms beyond what the project itself uses.

**Comment by fweimer-rh** [comment]
Here's a real-world example:

```c
        // If the most recent error pushed onto the error queue is NOT from OID parsing
        // then signal for an exception to be thrown.
        if (err != 0 && ERR_GET_FUNC(err) != ASN1_F_A2D_ASN1_OBJECT)
        {
            return -1;
        }
```

https://github.com/dotnet/runtime/blob/164a0c079a44ec82a2af71767b1eefb255242aa9/src/libraries/Native/Unix/System.Security.Cryptography.Native/openssl.c#L1081

And in our build environment, [it does not result in a build failure](https://bugzilla.redhat.com/show_bug.cgi?id=1991050).

I'm going to treat this as a reminder that we really should change the GCC defaults to match C99 (which removed implicit function declarations). But that is something that might become available in 2023 only, so I definitely would appreciate an OpenSSL mitigation here.

**Comment by davidben** [comment]
Setting aside removal vs. deprecation, this same issue with implicit declarations could be said about every symbol removed by every C API. Or common typos for functions. I don't think replacing them with the wrong type signature is a particularly reasonable expectation. Indeed adding the symbol in with the wrong type signature risks calling code incorrectly thinking the symbol _does_ exist.

Rather, the root cause here is that enabling C's implicit function declarations is a terrible idea, especially so when your environment does not check missing symbols at link time. As you note, it was removed 22 years ago in C99.

If GCC still uses the wrong defaults, that's unfortunate. But there's nothing stopping you from passing the correct flags to your build environment to disable them. (I think `-Wimplicit-function-declaration` and then make that warning an error? Unless there's another one.)

**Comment by paulidale** [comment]
The OTC had an involved discussion about removing this.  No matter what it was defined as, it would cause application problems: tt would either always or never match the defines.  Both cause problems.  By removing it, the intention was that applications would fail to compile indicating that there was a problem that needed to be fix.

We didn't anticipate a compiler with implicit declarations and lazy runtime binding.  Given this is an unlikely setup, I'm not convinced that the path chosen was in any way incorrect.  I strongly agree with @davidben that we should not be introducing an incorrect prototype to catch this edge case.

**Comment by fweimer-rh** [comment]
> We didn't anticipate a compiler with implicit declarations and lazy runtime binding. Given this is an unlikely setup, […]

It's the default build configuration for OpenSSL on GNU/Linux. Some distributions may have patched their binutils build to disable lazy binding for its linker output automatically, but this is a downstream-only change that is by no means universal.

**Comment by kroeckx** [comment]
I think the behaviour for undefined symbols is also relevant. The
manpage says:

           The default behaviour is to report errors for any
undefined symbols referenced in shared libraries if the linker is
being used to create an executable, but to allow them if the
linker is being used to create a shared library.

           The reasons for allowing undefined symbol references in
shared libraries specified at link time are that:

           •   A shared library specified at link time may not be
the same as the one that is available at load time, so the symbol
might actually be resolvable at load time.

           •   There are some operating systems, eg BeOS and HPPA,
where undefined symbols in shared libraries are normal.

               The BeOS kernel for example patches shared
libraries at load time to select whichever function is most
appropriate for the current architecture.  This is used, for
example, to dynamically select an appropriate memset function.

**Comment by t8m** [comment]
OTC: It would be a terrible hack to add an incorrect prototype for a non-existing function. It is responsibility of users of the openssl library to compile their code with warnings about removed functions - especially when updating to a new major release.
