### ISSUE TITLE
KATS results not printed by "openssl fipsinstall" when fips provider is used

### ISSUE THREAD

**Issue by SylwBar** [openssl/openssl#16260]
Hi.
Command "openssl fipsinstall" is not reporting any KATS results when OpenSSL 3.0 is configured to use FIPS module by default:
as described in: 
https://wiki.openssl.org/index.php/OpenSSL_3.0#Making_all_applications_use_the_FIPS_module_by_default

```
$ ./apps/openssl fipsinstall -module providers/fips.so
[fips_sect]
activate = 1
install-version = 1
conditional-errors = 1
security-checks = 1
module-mac = 68:CB:D3:E6:9E:E1:8C:8C:F6:3F:66:6C:EE:B7:02:A6:68:AB:36:F2:B0:F0:11:42:2C:D0:72:E2:E1:C5:52:9B
install-mac = 41:9C:38:C2:8F:59:09:43:2C:AA:2F:58:36:2D:D9:04:F9:6C:56:8B:09:E0:18:3A:2E:D6:CC:69:05:04:E1:11
install-status = INSTALL_SELF_TEST_KATS_RUN
INSTALL PASSED
```

when default provider is selected the same command prints:
```
$ ./apps/openssl fipsinstall -module providers/fips.so
HMAC : (Module_Integrity) : Pass
SHA1 : (KAT_Digest) : Pass
SHA2 : (KAT_Digest) : Pass
SHA3 : (KAT_Digest) : Pass
TDES : (KAT_Cipher) : Pass
AES_GCM : (KAT_Cipher) : Pass
AES_ECB_Decrypt : (KAT_Cipher) : Pass
RSA : (KAT_Signature) : RNG : (Continuous_RNG_Test) : Pass
Pass
ECDSA : (KAT_Signature) : Pass
ECDSA : (KAT_Signature) : Pass
DSA : (KAT_Signature) : Pass
TLS12_PRF : (KAT_KDF) : Pass
PBKDF2 : (KAT_KDF) : Pass
SSHKDF : (KAT_KDF) : Pass
KBKDF : (KAT_KDF) : Pass
HKDF : (KAT_KDF) : Pass
SSKDF : (KAT_KDF) : Pass
X963KDF : (KAT_KDF) : Pass
X942KDF : (KAT_KDF) : Pass
HASH : (DRBG) : Pass
CTR : (DRBG) : Pass
HMAC : (DRBG) : Pass
DH : (KAT_KA) : Pass
ECDH : (KAT_KA) : Pass
RSA_Encrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
[fips_sect]
activate = 1
install-version = 1
conditional-errors = 1
security-checks = 1
module-mac = 68:CB:D3:E6:9E:E1:8C:8C:F6:3F:66:6C:EE:B7:02:A6:68:AB:36:F2:B0:F0:11:42:2C:D0:72:E2:E1:C5:52:9B
install-mac = 41:9C:38:C2:8F:59:09:43:2C:AA:2F:58:36:2D:D9:04:F9:6C:56:8B:09:E0:18:3A:2E:D6:CC:69:05:04:E1:11
install-status = INSTALL_SELF_TEST_KATS_RUN
INSTALL PASSED
```

There is also problem when I simulate failure of one test - output is still successful with fips provider:
```
./apps/openssl fipsinstall -module providers/fips.so -corrupt_desc SHA2
[fips_sect]
activate = 1
install-version = 1
conditional-errors = 1
security-checks = 1
module-mac = 68:CB:D3:E6:9E:E1:8C:8C:F6:3F:66:6C:EE:B7:02:A6:68:AB:36:F2:B0:F0:11:42:2C:D0:72:E2:E1:C5:52:9B
install-mac = 41:9C:38:C2:8F:59:09:43:2C:AA:2F:58:36:2D:D9:04:F9:6C:56:8B:09:E0:18:3A:2E:D6:CC:69:05:04:E1:11
install-status = INSTALL_SELF_TEST_KATS_RUN
INSTALL PASSED
```

With default provider the output is correct (KAT failure):
```
HMAC : (Module_Integrity) : Pass
SHA1 : (KAT_Digest) : Pass
SHA2 : (KAT_Digest) : Corrupt Fail
SHA3 : (KAT_Digest) : Pass
TDES : (KAT_Cipher) : Pass
AES_GCM : (KAT_Cipher) : Pass
AES_ECB_Decrypt : (KAT_Cipher) : Pass
RSA : (KAT_Signature) : RNG : (Continuous_RNG_Test) : Pass
Pass
ECDSA : (KAT_Signature) : Pass
ECDSA : (KAT_Signature) : Pass
DSA : (KAT_Signature) : Pass
TLS12_PRF : (KAT_KDF) : Pass
PBKDF2 : (KAT_KDF) : Pass
SSHKDF : (KAT_KDF) : Pass
KBKDF : (KAT_KDF) : Pass
HKDF : (KAT_KDF) : Pass
SSKDF : (KAT_KDF) : Pass
X963KDF : (KAT_KDF) : Pass
X942KDF : (KAT_KDF) : Pass
HASH : (DRBG) : Pass
CTR : (DRBG) : Pass
HMAC : (DRBG) : Pass
DH : (KAT_KA) : Pass
ECDH : (KAT_KA) : Pass
RSA_Encrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Pass
Failed to load FIPS module
INSTALL FAILED
80C2FA791D7F0000:error:1C8000D4:Provider routines:SELF_TEST_post:invalid state:providers/fips/self_test.c:261:
80C2FA791D7F0000:error:1C8000D8:Provider routines:OSSL_provider_init_int:self test post failure:providers/fips/fipsprov.c:704:
80C2FA791D7F0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto/provider_core.c:820:name=fips

```

**Reproduced on:**
OpenSSL 3.0 beta1, beta2
AMD64 Linux, embedded system with ARM 32-bit.

**Steps to reproduce:**
Configure OpenSSL to use FIPS provider as default, as described in:
https://wiki.openssl.org/index.php/OpenSSL_3.0#Making_all_applications_use_the_FIPS_module_by_default

Edit the config file to add the following lines near the beginning: 
```
openssl_conf = openssl_init

.include /usr/local/ssl/fipsmodule.cnf

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1

```
Enter commands included earlier.

**Comment by SylwBar** [comment]
Reproduced also on beta3-dev.
```
sylbar@MATE:~/openssl_303f$ ./apps/openssl version -a
OpenSSL 3.0.0-beta3-dev  (Library: OpenSSL 3.0.0-beta3-dev )
built on: Sat Aug  7 19:04:19 2021 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/home/sylbar/openssl_303f_inst/dir"
ENGINESDIR: "/home/sylbar/openssl_303f_inst/pre/lib64/engines-3"
MODULESDIR: "/home/sylbar/openssl_303f_inst/pre/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xdefa2203478bffff:0x842421
```

**Comment by t8m** [comment]
I suppose (I did not investigate deeper) it works like this: If you have a fips provider loaded by the default configuration file the fips provider will load before the fipsinstall command starts its work. Once it is installed, there is not much the fipsinstall command can do. The workaround is to disable loading the default configuration file via `OPENSSL_CONF=/nonexistent_file openssl fipsinstall`.

Unfortunately given the fipsinstall command is part of the openssl tool it would be quite invasive change to do this override inside the command. Basically we would have to pre-parse the openssl tool command line to find out whether the fipsinstall command is being invoked and then do the configuration file override before any further initialization of OpenSSL library is performed.

**Comment by t8m** [comment]
My proposal would be to just document the situation and the workaround.

**Comment by SylwBar** [comment]
Hi.
Thank you for explanation.
However, please note that there is OSSL_PROVIDER_self_test() function that could be used to manually retrigger KATS during fipsinstall - even if fips.so engine was already loaded.

I prepared draft implementation to confirm that "openssl fipsinstall" could work as required even with fips.so engine was loaded before.

**Comment by mattcaswell** [comment]
OTC: No decision required at this stage. This is not associated with the 3.0 milestone so is not a blocker for 3.0 release.

**Comment by slontis** [comment]
The main point of fipsinstall is to generate a fips config file.
What you are doing is trying to generate a fips config file by loading a fips provider which already has a generated fips config file. It makes more sense to use the default provider.

What happens is that the OSSL_SELF_TEST_set_callback() is set up AFTER the config is autoloaded. The autoload runs the self tests then with no callback. Which means that nothing is printed, as well as any test you try to set in the callback will also not work since the callback is not used.

When you use the default provider, the fipsinstall will set the callback and then do the fips module load.

I dont think adding an option to run self tests on demand from here is what we really want to do.

**Comment by t8m** [comment]
@slontis perhaps we should document this somehow in the fipsinstall manual page? Would you be able to submit a PR?

**Comment by SylwBar** [comment]
Thank you for update.
Finally, I ended up with systemd service redirecting OPENSSL_CONF as proposed:

...
[Service]
Type=oneshot
Environment=OPENSSL_CONF=/nonexistent_file
ExecStart=openssl fipsinstall -module /usr/lib/ossl-modules/fips.so -out /usr/lib/ssl-3/fipsmodule.cnf
...

I guess issue could be closed.

**Comment by t8m** [comment]
Closing.
