### ISSUE TITLE
OpenSSL3 regression: DSA_generate_parameters_ex fails to set FFC_PARAM_FLAG_VALIDATE_LEGACY when needed 

### ISSUE THREAD

**Issue by tsdgeos** [openssl/openssl#16261]
I was going to submit a patch but then I realized i needed to sign a CLA so i will describe the problem textually and hopefully you can come up with the one liner needed without me having to go through the hassle of signing a CLA.

If we don't set FFC_PARAM_FLAG_VALIDATE_LEGACY when creating a DSA_PARAMGEN_TYPE_FIPS_186_2 type on DSA_generate_parameters_ex, then using that DSA will fail later on on dsa_keygen because ossl_ffc_params_simple_validate will go though ossl_ffc_params_FIPS186_4_validate instead of ossl_ffc_params_FIPS186_2_validate.

**Comment by t8m** [comment]
Fix in #16268

**Comment by slontis** [comment]
There is a testcase that needs to be fixed taht should cover this..
See dsatest.c dsa_test().

DSA_generate_key() and DSA_Sign() both fail but dont check the return value.
DSA_verify is also wrong since in returns -1 and then passes on the TEST_true()
