### ISSUE TITLE
Add Camellia CTS implementation to default provider

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#16276]
We are missing Camellia CTS in the high level API which was possible to do with the old APIs.
See also #16235

**Comment by slontis** [comment]
I am having a look. It doesn't look too hard to refactor this to handle both cases..

**Comment by slontis** [comment]
@frozencemetery I am looking at test vectors in
https://mirror.unpad.ac.id/ietf/internet-drafts/draft-ietf-krb-wg-camellia-cts-00.txt

And dont seem to be getting the right results for  Sample encryptions (all using the default cipher state):
````
   Plaintext: 1
   Random confounder:
       6F 2F C3 C2 A1 66 FD 88 98 96 7A 83 DE 95 96 D9
   128-bit Camellia key:
       50 27 BC 23 1D 0F 3A 9D 23 33 3F 1C A6 FD BE 7C
   Ciphertext:
       84 2D 21 FD 95 03 11 C0 DD 46 4A 3F 4B E8 D6 DA
       88 A5 6D 55 9C 9B 47 D3 F9 A8 50 67 AF 66 15 59
       B8
`````
I was assuming this translates to:

````
IV =  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
PT =  6F2FC3C2A166FD8898967A83DE9596D931 (cofounder || pt)
KEY = 5027BC231D0F3A9D23333F1CA6FDBE7C (Is this right??)
CT =  842D21FD950311C0DD464A3F4BE8D6DA88 (first bytes of above CIphertext)
````

Any ideas where I am going wrong here?

**Comment by slontis** [comment]
It appears that the key is the base key - the missing data is the usage,,,

**Comment by frozencemetery** [comment]
>  https://mirror.unpad.ac.id/ietf/internet-drafts/draft-ietf-krb-wg-camellia-cts-00.txt

For what it's worth, that's an early draft of [RFC 6803](https://datatracker.ietf.org/doc/html/rfc6803).

As I read section 6, that vector becomes:

    IV = <all zeroes>
    PT = 6F 2F C3 C2 A1 66 FD 88 98 96 7A 83 DE 95 96 D9 01
    KEY (Ke): 50 27 BC 23 1D 0F 3A 9D 23 33 3F 1C A6 FD BE 7C
    CT = 84 2D 21 FD 95 03 11 C0 DD 46 4A 3F 4B E8 D6 DA 88

assuming by CT you mean what the draft calls C.

The only difference I spot is that the last octet of PT needs to be a full octet: you have 1, I have 01.

If that doesn't help, I'll have to defer to the document author.

**Comment by frozencemetery** [comment]
Right after hitting submit, another thought: the "key" may not be "Ke" but rather base-key.  So you'd need to derive Ke (and Ki, if you were doing the MAC part) from it using the KDF.

**Comment by slontis** [comment]
Yeah it was the base key.. Test vectors are now in the PR.
The missing usage was what threw me initially.
