### ISSUE TITLE
How to generate RSA EVP_PKEY using new APIs

### ISSUE THREAD

**Issue by maheshkumar01** [openssl/openssl#16288]
I'm new to OpenSSL and we have a C++ project which uses OpenSSL 1.1.1. Below is the code to generate EVP_PKEY in OpenSSL 1.1.1. Most of these APIs are deprecated in OpenSSL 3.0.0. I would need help here on "How can I achieve similar functionality using new (non-deprecated) APIs?" A sample code would go long way here.

```
//Error handling (null check etc.) are missing

void CreatePKey(uint32_t bits) {
  EVP_PKEY *pkey = NULL;
  RSA *rsa = NULL;
  BIGNUM *f4 = NULL;
  
  // Allocate private key structure
  pkey = EVP_PKEY_new();
  
  // Allocate and intialize big number
  f4 = BN_new();
  
  BN_set_word(f4, RSA_F4);
   
   // alocate RSA struct
   rsa = RSA_new();
	
  RSA_generate_key_ex(rsa, static_cast<int>(bits), f4, NULL);
	
  EVP_PKEY_assign_RSA(pkey, rsa);
}
```

**Comment by mattcaswell** [comment]
The simplest way is to use `EVP_RSA_gen`:

````
EVP_PKEY *pkey = EVP_RSA_gen(bits);
````
You can't specify the exponent through this route (you would need to use the `EVP_PKEY_keygen` API for that). But `RSA_F4` is the default anyway.

https://www.openssl.org/docs/manmaster/man3/EVP_RSA_gen.html

**Comment by maheshkumar01** [comment]
Thanks. Closing the issue
