### ISSUE TITLE
Integrating Android and iOS Secure Enclave keystore with Openssl apps

### ISSUE THREAD

**Issue by pprindeville** [openssl/openssl#16284]
We have a lot of code using Openssl libraries, as well as scripts using the canned Openssl CLI commands.

We'd like to be able to make all of this work with the iOS and Android Secure Enclave keystores, without requiring major rewrites.  I was thinking that the iOS keystore is a bit like an HSM that only supports 256-bit ECC private key functions (decryption and signing, mostly), or derivative operations layers on top of those (CMS, CSR generation, etc).  Almost forgot: random number generation, since the Secure Enclave typically has shielded state, it's harder to predict its PRNG if it's algorithmic and it gathers system entropy.

Or alternatively, maybe it looks like a crypto-token at PKCS11 is the way to model it.

How have other people solved this problem?  What's the best way to think about it?

We're prepared to write a PKCS11 wrapper to access the Secure Enclaves (and put it up on GitHub) if that's the best way to do this, to solve this problem for ourselves and anyone else who is also running into it.  Just looking for some guidance before we start sprinting down the garden path...

**Comment by t8m** [comment]
There is basically just one (non-deprecated) option how to make it work with OpenSSL (3.0 version that is) - write an OpenSSL provider for the keystores.

In future when a generic PKCS11 provider will exist for OpenSSL, it would also work to have the PKCS11 provider on top of a PKCS11 module for the keystores. However the PKCS11 OpenSSL provider is something that still needs to be written and it will be a major effort to write one.

**Comment by dengert** [comment]
As noted in https://github.com/openssl/openssl/pull/1551#issuecomment-896716734  PCs can have a TPM (Trusted Platform Module) and Windows 11 is going to require one for secure boot. Search for: Windows 11 TPM.

With all of these devices, what is not clear is how  a user, gains access to the device, and for how long, and can multiple uses have keys in these devices.  

in https://github.com/openssl/openssl/pull/1551#issuecomment-896439783  it was said:
> making it surprising and user-unfriendly to require the hardware token to sign (twice?) just to set the key on an SSL context. 

This goes back to the access i.e. (authenticate or login to a a token), and the sign (twice?) may be sign (authenticate in SSL context), and DH key exchange to derive a shared session key, And the user had to authenticate twice.  

And as @t8m points out PKCS11 may be the answer. Windows 10 has a way to treat  a TPM as a smartcard, at least via CAPI.

**Comment by dwmw2** [comment]
I definitely think PKCS#11 is the right way to expose the OS keystore; it allows keys therein to be referenced with standard RFC7512 URIs, which users should expect to Just Work™ with any application.

**Comment by pprindeville** [comment]
> There is basically just one (non-deprecated) option how to make it work with OpenSSL (3.0 version that is) - write an OpenSSL provider for the keystores.
> 
> In future when a generic PKCS11 provider will exist for OpenSSL, it would also work to have the PKCS11 provider on top of a PKCS11 module for the keystores. However the PKCS11 OpenSSL provider is something that still needs to be written and it will be a major effort to write one.

Are there any existing providers that I can use as an example to follow?

Or some pre-3.0.0 code that just needs to be updated?

**Comment by dwmw2** [comment]
You could start by looking at #8200 or https://github.com/OpenSC/engine_pkcs11

**Comment by pprindeville** [comment]
> You could start by looking at #8200 or https://github.com/OpenSC/engine_pkcs11

Thanks

**Comment by dwmw2** [comment]
> I do not think the engine_pkcs11 is a good example as this is using the engine and not the provider interface. 

Sure, but it does provide a lot of the code for wrapping PKCS#11 APIs and making an `EVP_PKEY` out of them, which is kind of helpful too. Note that #8200 was submitted with a compatible licence, while the engine_pkcs11 licence isn't strictly compatible but I *did* round up approval from Olaf Kirch and the other major copyright-holders to relicense it. You might keep life simpler by *not* using it though.

**Comment by dwmw2** [comment]
@pprindeville You want to be looking at the OSSL_STORE interface, providing a loader for the 'pkcs11:' scheme.

I think I'd actually recommend adopting libp11_kit wholesale as a dependency and letting it load/manage PKCS#11 modules for you. Others may dissent.

**Comment by t8m** [comment]
Making an EVP_PKEY is IMO not really relevant for the provider interface.

**Comment by pprindeville** [comment]
> I do not think the engine_pkcs11 is a good example as this is using the engine and not the provider interface. This is a new TPM2 provider https://github.com/tpm2-software/tpm2-openssl which can be an example of a provider providing access to asymmetric keys in some external storage.

Is there a recap of engine vs. provider interfaces?

And to make sure I'm understanding, it's not just _accessing on external storage_ though is it?  We're actually squirting ciphertext into an external device where the private key resides, so it can decrypt it for us...

**Comment by dwmw2** [comment]
Think of it as *calling a function* which performs the crypto operations for us using the corresponding private key.

**Comment by pprindeville** [comment]
> Think of it as _calling a function_ which performs the crypto operations for us using the corresponding private key.

For providers?  Or both?

**Comment by dwmw2** [comment]
Both, but I meant more the other side; the low level implementations that your code calls into to actually perform the operations.

**Comment by paulidale** [comment]
Engines provider a low level interface to the operations.  Providers provider the equivalent of the EVP interfaces.
You will definitely want a provider for this -- engines are deprecated, not as version safe and in my opinion more difficult to write.

PKCS #11 seems like a good approach.  It is on the project's roadmap but don't expect it anytime soon, there are a lot of good things on the roadmap and there aren't a lot of fellows to implement them.  A thirty party/community produced provider would be view favourably.

There is one hurdle between the current provider interface and what you want to do.  Currently, a provider needs to implement all of EC or none of it -- it's not obvious how to implement just one curve.  It's possible but requires a bit too much cleverness.  Again, fixing this is part of the roadmap.

**Comment by dengert** [comment]
> Currently, a provider needs to implement all of EC or none of it -- it's not obvious how to implement just one curve. 

Many smartcards are issued by a government agency, so the key type and its parameters are already set.
This may also apply to  Android and IOS Secure Enclave keystore.

Could a PKCS11 provider internally call a software provider when needed? In effect that is what engine_pkcs11 does now using OpenSSL for operations such as hashing, padding and operations that use only the public key.

**Comment by paulidale** [comment]
That's the workaround.  For EC key types that aren't know to a provider, it needs to call through to the default (or other) provider for the capability.

Like I noted, this is something that will be addressed after 3.0 is released.

**Comment by pprindeville** [comment]
> > Currently, a provider needs to implement all of EC or none of it -- it's not obvious how to implement just one curve.
> 
> Many smartcards are issued by a government agency, so the key type and its parameters are already set.
> This may also apply to Android and IOS Secure Enclave keystore.

It does indeed.  Android keystore only permits RSA-2048, and iOS only allows NIST P-256.
> 
> Could a PKCS11 provider internally call a software provider when needed? In effect that is what engine_pkcs11 does now using OpenSSL for operations such as hashing, padding and operations that use only the public key.
