### ISSUE TITLE
AIX-6.1 error : openssl-1.1.1/engines/e_afalg.c , line 24.10: 1506-296 (S) #include file <linux/version.h> not found.

### ISSUE THREAD

**Issue by nitinyadav91** [openssl/openssl#16297]
I am trying to build openssl-1.1.1 on AIX 6.1 platform but getting below error 
openssl-1.1.1/engines/e_afalg.c", line 24.10: 1506-296 (S) #include file <linux/version.h> not found.

Compiler details:
bash-4.2$ /opt/local/Vendor/vac/11/usr/vacpp/bin/xlc_r -qversion
IBM XL C/C++ for AIX, V11.1 (5724-X13)

OS details:
bash-4.2$ uname -a
AIX 1 6 00C95D924C00

Does any package missing on my system or need to set some configuration setting?

**Comment by mattcaswell** [comment]
Please can you provide your build steps, and in particular how you called the "Configure" script (or "config").

**Comment by nitinyadav91** [comment]
I am using cmake instead of configuration . I have compiler option and linking option by cmake . Do I need to set any extra flag for AIX platform.

**Comment by mattcaswell** [comment]
> I am using cmake instead of configuration .

This is not a supported configuration and almost certainly won't work. You are on your own here. The e_afalg.c file that it is failing on is a Linux only file. It should not be attempted to be compiled on AIX.
