### ISSUE TITLE
support for musl

### ISSUE THREAD

**Issue by piranna** [openssl/openssl#163]
Add support to be able to compile OpenSSL with [musl](http://www.musl-libc.org/). Currently it has too much dependence with glibc, so it's needed to apply some patches to make it to work, being the first one the use of TERMIOS macro instead of the non-standard TERMIO. Also, it's not possible to compile it statically with the ```-static``` flag due to linking errors:

```
/home/piranna/Dropbox/Proyectos/NodeOS/NodeOS-QEmu/Layer2-nodejs/deps/node/out/Release/libopenssl.a(eng_all.o): En la función `ENGINE_load_builtin_engines':
eng_all.c:(.text.ENGINE_load_builtin_engines+0x46): referencia a `ENGINE_load_padlock' sin definir
eng_all.c:(.text.ENGINE_load_builtin_engines+0x4b): referencia a `ENGINE_load_gost' sin definir
collect2: error: ld returned 1 exit status
```

**Comment by piranna** [comment]
musl is now a lot more complete and compatible with glibc and can be able to compile openssl without problems, only remaining point is the usage of TERMIO by openssl instead of the standard TERMIOS macro. [This patch](https://github.com/maximeh/buildroot/blob/master/package/openssl/openssl-004-musl-termios.patch) fix openssl so it can be compiled with musl:

```diff
--- a/crypto/ui/ui_openssl.c 2013-09-08 11:00:10.130572803 +0200
+++ b/crypto/ui/ui_openssl.c 2013-09-08 11:29:35.806580447 +0200
@@ -190,9 +190,9 @@
# undef SGTTY
#endif
-#if defined(linux) && !defined(TERMIO)
-# undef TERMIOS
-# define TERMIO
+#if defined(linux)
+# define TERMIOS
+# undef TERMIO
# undef SGTTY
#endif
```

**Comment by levitte** [comment]
I suppose you mailed openssl-dev with the same issue yesterday.  I actually saw this issue here just a few days ago and decided that I'd have a look whenever I have the time.  The time is now.

It turns out that the man page for termio(7) on Linux points out that termio is obsolete and that termios is standardised in POSIX.1-1990, so there's definitely reason for your patch, not just for musl.  I'll see how your patch does in some non-Unix environments I deal with.

**Comment by levitte** [comment]
Easier than I first thought (I haven't looked at that file in ages).

Fix committed, it just has to go through our review process.
Thanks!

**Comment by piranna** [comment]
> I suppose you mailed openssl-dev with the same issue yesterday.

Lol! No, I didn't :-P


> Fix committed, it just has to go through our review process.

Awesome! :-D Seems it was a greatly requested issue for years! :-P Now Node.js will not need to be patched to compile with musl!!! :-D

**Comment by levitte** [comment]
It actually became a much larger change...  we've made TERMIOS the default on most platforms (because it's well defined POSIX).  It's in the main repo since a couple of days back.

**Comment by piranna** [comment]
> a much larger change

There was any problem? Just curious...

P.D.: Thank you so much! :-D

**Comment by piranna** [comment]
Ok, I've found the rationale, makes sense :-)

https://github.com/openssl/openssl/commit/64e6bf64b36136d487e2fbf907f09612e69ae911
https://github.com/openssl/openssl/commit/ba4bdee7184a5cea5bef8739eb360e5c2bc3b52c
