### ISSUE TITLE
Backport ALPN Support to 1.0.1

### ISSUE THREAD

**Issue by futureweb** [openssl/openssl#1630]
As RedHat won't upgrade to openssl 1.0.2 before RHEL 7.4 (https://bugzilla.redhat.com/show_bug.cgi?id=1276310) it should be considered if ALPN Support could be backported to 1.0.1 thus enabling RHEL Users to support HTTP/2 on Chrome again (As Chrome dropped NPN Support: http://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html)

Thank you
Andreas Schnederle-Wagner

**Comment by richsalz** [comment]
Sorry, 1.0.1 only gets security fixes and even that ends at the end of the year.
See https://www.openssl.org/policies/releasestrat.html
