### ISSUE TITLE
prime generation failed on multi-core machines

### ISSUE THREAD

**Issue by jinleiw** [openssl/openssl#16310]
Host: kvm machine, 48C64G
OS：CentOS-7.2
openssl version：openssl-1.0.1e

I'm using `ssh-keygen` to generate rsa key, but that failed, then I debug step by step with gdb

it call openssl libs finally, the function call chain:

```
...
-> RSA_generate_key_ex [crypto/rsa/rsa_gen.c:154]
    -> rsa_builtin_keygen [crypto/rsa/rsa_gen.c:399]
        -> BN_generate_prime_ex [crypto/rsa/rsa_gen.c:450]
            -> BN_generate_prime_ex [crypto/bn/bn_prime.c:159]
                -> BN_is_prime_fasttest_ex [crypto/bn/bn_prime.c:199]
                    -> BN_pseudo_rand_range [crypto/bn/bn_prime.c:322]
                        -> bn_rand_range [crypto/bn/bn_rand.c:233]
```

finally, error and stop here:

![98B@ 4~ZOSX W_PN5RGNNJ4](https://user-images.githubusercontent.com/12782092/129443542-cee02d32-00b2-4be0-918b-4afb5c6b5a16.png)

**But, it's OK when I adjust kvm machine to 4C8G.**

May be it's a bug that can reproduce on powerful kvm machine.

My machine info:

![image](https://user-images.githubusercontent.com/12782092/129443987-9c323dde-c300-4da2-a810-37f2bcff5727.png)

**Comment by paulidale** [comment]
My guess would be your RNG source is dud.
There are some known problems with RDRAND and RDSEED on some CPUs.  There are additional issues in VM environments.
I think it's worth checking out what's coming out of the instruction.

**Comment by paulidale** [comment]
OpenSSL 1.0.1 is long out of support.

**Comment by jinleiw** [comment]
It's OK when update openssl to 1.0.2k. close the issue.

Thanks.
