### ISSUE TITLE
doc-nits warning

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#16328]
Does nobody in the project run doc-nits any more?
```
 mk doc-nits
perl ./util/find-doc-nits -c -n -l -e
*** WARNING: Verbatim paragraph in NAME section at line 8 in file doc/man3/TS_RESP_CTX_new.pod

```

Perhaps capturing stderr and exit 1 if not emptiy during a CI build?

At any rate, it seems that deleting line 8 from that file fixes the noise.

**Comment by paulidale** [comment]
?? I'm not seeing this on master ??
```sh$ make doc-nits
/usr/bin/perl ../openssl/util/find-doc-nits -c -n -l -e
$ 
```

We still run a CI that does doc-nits.

**Comment by levitte** [comment]
This probably depends on Pod::Checker version.  I recall that there was a version that was unusually verbose with some warnings.

**Comment by richsalz** [comment]
The main point, which got lost in my intro snark, is that the warnings are not captured and do not affect the status.  Shrug. Close this if you want.

**Comment by paulidale** [comment]
I've done a fix for the specific problem.

I didn't realise we could exit with a success after producing output on stderr.

**Comment by levitte** [comment]
Warnings are not errors, that's true.  That's how Pod::Checker sees it, according to the manual:

https://metacpan.org/pod/Pod::Checker#RETURN-VALUE

> I didn't realise we could exit with a success after producing output on stderr.

Uhm...

**Comment by levitte** [comment]
If you really want to check if there were any warnings, and have our script behave differently, you need to use the full interface, described here:

https://metacpan.org/pod/Pod::Checker#INTERFACE

The podchecker *function* (which is what we currently use) simply returns `$checker->num_errors()`, but with the full interface, you have access to `$checker->num_warnings()` as well.

**Comment by paulidale** [comment]
Thanks, I'll give this a whirl tomorrow and see what explodes.

**Comment by richsalz** [comment]
I tried to do this before and gave up, but @paulidale you're better at perl than I am.  Thanks.  I think the project wants to do this for the same reason it uses `-Werror` in the code.

**Comment by levitte** [comment]
If you're up for an adventure, try warning level 2. :wink:
(and no, we shouldn't use that as a standard, it will make certain documentation impossible)

**Comment by richsalz** [comment]
> If you're up for an adventure, try warning level 2. 😉
> (and no, we shouldn't use that as a standard, it will make certain documentation impossible)

I did.  And then undid the mod and walked slowly away :)

**Comment by levitte** [comment]
> And then undid the mod and walked slowly away :)

Wisely done

**Comment by paulidale** [comment]
> ... but @paulidale you're better at perl than I am.

No b****y way, my Perl is minimialistic.
