### ISSUE TITLE
Please explain why binaries for download are not offered.

### ISSUE THREAD

**Issue by webdev3301** [openssl/openssl#16326]
Help me understand why I have to go to a website that was made in 1992 to download something you develop continuously on GitHub. Please tell me how exact instructions to compile OpenSSL in any platform are not listed here.

**Comment by levitte** [comment]
> Please tell me how exact instructions to compile OpenSSL in any platform are not listed here.

Uhmm, did you look at INSTALL.md (or INSTALL for OpenSSL 1.1.1)?

**Comment by webdev3301** [comment]
And as for the first question?

**Comment by levitte** [comment]
> Yes I did look. Are you familiar with Double-Clicking on Windows? Jesus Christ have you seen the size of the INSTALL.md? Is that a joke?

No joke.  There are many configuration options, they should be documented.
But tell you what, there's a [Quick Installation Guide](https://github.com/openssl/openssl/blob/master/INSTALL.md#quick-installation-guide) in there, that's the minimum you need to look at unless you want to go fancy.

**Comment by webdev3301** [comment]
Right on. So...
Step 1 - Recharge wireless mouse to full in order to reach the bottom of [Quick Installation Guide](https://github.com/openssl/openssl/blob/master/INSTALL.md#quick-installation-guide).
Step 2 - Go quickly learn C++ for a week in order to compile a tool exactly once to generate a SSL certificate.

**Comment by mattcaswell** [comment]
We maintain a list of third party supplied precompiled binaries here:

https://wiki.openssl.org/index.php/Binaries

**Comment by webdev3301** [comment]
What you don't maintain is a windows batch file that once double-clicked, compiles the entire code. Because people who use openssl do not need to know how to build it. They just need to use it.

Proposed OpenSSL install:

1. Download and install prerequisites.
2. Double-click batch file to compile OpenSSL.
3. Done.

**Comment by mspncp** [comment]
> Yes I did look. Are you familiar with Double-Clicking on Windows? Jesus Christ have you seen the size of the INSTALL.md? Is that a joke?

The OpenSSL toolkit is provided as source code which can be compiled for various different platforms. This explains the size of the installation instructions. If you are looking for a worry-free-double-click-install-and-run-solution, please search for a binary precompiled distribution at one of the locations mentioned [previously](https://github.com/openssl/openssl/issues/16326#issuecomment-900360481). And before asking your next question on an open source project, you might want to consult an etiquette and politeness guide.

**Comment by rsbeckerca** [comment]
> 
> 
> We maintain a list of third party supplied precompiled binaries here:
> 
> https://wiki.openssl.org/index.php/Binaries

@mattcaswell Would you like me to provide a link on the wiki for the NonStop precompiled binaries?

**Comment by mspncp** [comment]
If you don't mind the effort, your contribution is welcome. Citing from https://wiki.openssl.org/index.php/Binaries:

> The condition to get a link here is that the link is stable and can provide continued support for OpenSSL for a while.
