### ISSUE TITLE
Documentation for SSL_CTX_check_private_key return value

### ISSUE THREAD

**Issue by procedural** [openssl/openssl#16324]
`SSL_CTX_check_private_key` returns an int.
What an int == 0 means? 
What an int > 0 means?
What an int < 0 means?
Documentation doesn't tell. Thanks, Obama.

**Comment by procedural** [comment]
https://www.ibm.com/docs/en/ztpf/2021?topic=apis-ssl-ctx-check-private-key
> Return code 1 indicates that the function was successful.

Where did they get that from?

**Comment by paulidale** [comment]
The section titled [Return Values](https://www.openssl.org/docs/manmaster/man3/SSL_check_private_key.html#RETURN-VALUES) perhaps?

**Comment by procedural** [comment]
> On success, the functions return 1. Otherwise check out the error stack to find out the reason.

What is error stack?

**Comment by t8m** [comment]
> What is error stack?

Thread local stack of error reason codes that are added by the OpenSSL functions if some error is encountered.

See man ERR_get_error.

**Comment by procedural** [comment]
@t8m Thanks!
I have no more questions now, closing.
