### ISSUE TITLE
Why is renegotiation disabled in KTLS simply due to a code error?

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#16357]
> I tried a renegotiation from s_client to see what would happen. I got an assertion failed error and abort! This error needs to call SSLfatal first. We later do a sanity check to make sure we've sent an alert via SSLfatal if we're in an error state. That assertion was failing in this case (also see #7594). I wonder if we should automatically set SSL_OP_NO_RENEGOTIATION if ktls is in use.

Originally posted by @mattcaswell in #5253 (comment)

**Comment by nhorman** [comment]
@mattcaswell not being familiar with the ktls methods, is this still an issue?

**Comment by mattcaswell** [comment]
The comment was responded to at the time of that PR and was (apparently) fixed (although I've not retested it now). I think this can be closed.
