### ISSUE TITLE
'make test' picks up the wrong library files

### ISSUE THREAD

**Issue by jeffjanes** [openssl/openssl#1635]
If I install OpenSSL_1_1_0 to the default location, and then build OpenSSL_1_1_0b the "make test" fails because it picks up the .so files from the first install, rather than the incipient library files.

I do a purely default build, i.e. `(./config && make && make test) > /dev/null`

This problem occurs on both CentOS7 and Ubuntu 16.04.

The problem begins with commit 342a1a23793cb9992.  That commit causes the stanza starting with `if [ -f "$LIBCRYPTOSO" -a -z "$preload_var" ]; then` to disappear from the util/shlib_wrap.sh file, which means LD_PRELOAD does not get set.

**Comment by levitte** [comment]
That's...  interesting.  `$LD_LIBRARY_PATH` should have the local build directory as its first element (to prove it: `./util/shlib_wrap.sh sh -c 'echo $LD_LIBRARY_PATH'`), and the locally built library should be found on it.

**Comment by levitte** [comment]
Sorry, I forgot that `Makefile.shared` implements `-rpath` everywhere it can...  that's the culprit in this.

**Comment by jeffjanes** [comment]
Correct, LD_LIBRARY_PATH is "./util/..", but it is over-ridden by the rpath.  

I guess the problem is that "util/shlib_wrap.sh.in" is not correctly detecting that rpath is in use?  Unfortunately, I don't think I know enough to help fix that.

**Comment by levitte** [comment]
> I guess the problem is that "util/shlib_wrap.sh.in" is not correctly detecting that rpath is in use?

Yes, that's one way of looking at it.  The other is that the use of rpath is problematic to begin with (I see many talking about DT_RPATH as a deprecated feature, DT_RUNPATH should be used instead on ELF systems).  For the moment, the debate is become a question if we should restore `shlib_wrap.sh` to always have the preloading code (which comes with its own problems) or if we should stop using -rpath altogether.

**Comment by kaduk** [comment]
My vote (not that it counts for much) is to stop using -rpath altogether.  It is just asking for headaches, and DT_RUNPATH is much better.

**Comment by mattcaswell** [comment]
@levitte can this be closed?

**Comment by levitte** [comment]
I think so
