### ISSUE TITLE
I tried a renegotiation from s_client to see what would happen. I got an assertion failed error and abort! This error needs to call `SSLfatal` first. We later do a sanity check to make sure we've sent an alert via SSLfatal if we're in an error state. That assertion was failing in this case (also see #7594). I wonder if we should automatically set `SSL_OP_NO_RENEGOTIATION` if ktls is in use.

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#16356]
I tried a renegotiation from s_client to see what would happen. I got an assertion failed error and abort! This error needs to call `SSLfatal` first. We later do a sanity check to make sure we've sent an alert via SSLfatal if we're in an error state. That assertion was failing in this case (also see #7594). I wonder if we should automatically set `SSL_OP_NO_RENEGOTIATION` if ktls is in use.

_Originally posted by @mattcaswell in https://github.com/openssl/openssl/pull/5253#r231904626_

**Comment by yangyangtiantianlonglong** [comment]
Sorry, wrong opening

**Comment by mspncp** [comment]
(FWIW: there is an ‚Edit‘ button next to the subject line which enables you to change it at any time.)
