### ISSUE TITLE
[Bug] Forcing lib64 in 64-bit builds

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#16373]
The NonStop x86 builds are typically 64-bit but are not going into the `lib64` directory. I think I am missing something in `Configurations/50-nonstop.conf`. May I ask for assistance on this, please?

**Comment by rsbeckerca** [comment]
This may turn out to be a red herring. Not that I don't mind herring ;) Apologies if it is.

**Comment by levitte** [comment]
I think it is in fact a red herring

There are platform that support having multiple versions of the same library for different runtime flavors.  For example, many Linux installation support having 32-bit and 64-bit versions of the same library, just installed in different directories.  The `multilib` target attribute helps getting things into the "correct" directory, where we have been able to determine what that is.

So if your NonStop x86 supports both 32-bit and 64-bit runtime flavors, you will probably need to set `multilib` appropriately.  Otherwise, don't bother.

**Comment by rsbeckerca** [comment]
We have 6 builds currently, so I am interested in `multilib`, definitely. And herring.

**Comment by levitte** [comment]
> We have 6 builds currently

Yes.  The question is, will some of them be present in the same environment, ever?

**Comment by rsbeckerca** [comment]
> > We have 6 builds currently
> 
> Yes.  The question is, will some of them be present in the same environment, ever?
> 

Very likely. We currently differentiate by prefix:
`/usr/local-ssl1.1`, `/usr/local-ssl3.0`, `/usr/local-ssl3.0-put`, `/usr/local-ssl3.0-spt`, `/usr/local-ssl3.0-32`. This is because we cannot change name binding at runtime, so `libssl.so` has to be used, because most tools expect to build with `-lssl`.

**Comment by levitte** [comment]
So it sounds like this would be suitable:

``` diff
diff --git a/Configurations/50-nonstop.conf b/Configurations/50-nonstop.conf
index 7524c50016..bc3ece8878 100644
--- a/Configurations/50-nonstop.conf
+++ b/Configurations/50-nonstop.conf
@@ -170,12 +170,14 @@
         defines          => ['_PUT_MODEL_',
                              '_REENTRANT', '_THREAD_SUPPORT_FUNCTIONS'],
         ex_libs          => '-lput',
+        multilib         => '-put',
     },
     'nonstop-model-spt' => {
         template         => 1,
         defines          => ['_SPT_MODEL_',
                              '_REENTRANT', '_ENABLE_FLOSS_THREADS'],
         ex_libs          => '-lspt',
+        multilib         => '-spt',
     },
 
     # Additional floss model that can be combined with any of the other models.
```

**Comment by rsbeckerca** [comment]
It would simplify my builds. Can this make the 3.0.0 timeframe?

Would that make multilib=64 for just 64bit builds?

**Comment by rsbeckerca** [comment]
Also, does `multilib` take into account engine build differences? Should our structure now use `/usr/local-ssl3.0` and then the `multilib` attribute will handle all of the differentiation below? That would be much easier, I think.

**Comment by rsbeckerca** [comment]
I think I need to transition this to a bug. If two `multilib` attributes are specified in the configuration from different models, there is a space inserted between the values. That probably should be suppressed. In my experiment, using the above configuration and setting `multilib => '64'` for 64 bit builds, I end up with the following in the `Makefile`.
```
LIBDIR=lib64 -put
```

**Comment by paulidale** [comment]
> Can this make the 3.0.0 timeframe?

The only change that might be problematic is the white space crunching since that might hit other platforms.

**Comment by rsbeckerca** [comment]
> > Can this make the 3.0.0 timeframe?
> 
> The only change that might be problematic is the white space crunching since that might hit other platforms.
> 

Consider that second through n multilib attributes in a configuration will end up as unintended distinct arguments to the compiler.

**Comment by levitte** [comment]
Sorry, merged attribute values are space delimited. Changing that would have quite complex ramifications. In this case, it's better to combine them manually and place those attributes in the final config targets.

**Comment by rsbeckerca** [comment]
If the space delimited is important, let me fix this and push again. The values are in the wrong places.
