### ISSUE TITLE
Bug in SSL_connect results in a crash

### ISSUE THREAD

**Issue by httpstorm** [openssl/openssl#16400]
I recently struggled with a crash when an OpenSSL client using synchronous sockets is used with two threads: one for sending and one for receiving. The interesting thing is that the crash may only occur during the first few messages. Once we get past that point, the communication can go on over night without any issues. I know many of you will say that I should not use two threads with sync sockets, however the cause of the crash seems to be a bug in SSL_connect.

Steps to reproduce:
The server is configured not to send any data over the secure channel. The client configures OpenSSL and calls `SSL_connect`. During this, 3 messages are exchanged: client hello, server hello, client fin. `SSL_connect` returns immediately after that, without waiting for the server fin message. Herein lies the issue: it expects the next call from the client to be `SSL_read`, however if another thread calls `SSL_write` first, the client has not processed the 4th message yet, and gets confused. If we call `SSL_read` now, the client will crash.

Workaround:
I switched to using memory BIO. Initially I implemented the handshake the way `SSL_connect` is doing it, however the crash persisted. Then I added a final `SSL_read` in my handshake function and the crash was fixed. My recommendation to the OpenSSL team: please process the 4th message before returning from `SSL_connect`. This will make apps using OpenSSL much more reliable.
Another workaround is to delay the first write and make sure `SSL_read` is called first. After that, both can be called without any issues.

The complete source code of my SSL implementation is provided below:
https://pastebin.com/4UrStN13

OpenSSL 1.1.1k
Ubuntu 20.04, Windows 10, macOS 11.5.2, FreeBSD 13.0

**Comment by t8m** [comment]
This is not supported and probably never will be. You have to synchronize the access to a SSL object if you want to use it from multiple threads.

**Comment by httpstorm** [comment]
@t8m 
The main purpose of this ticket is to discuss the behaviour of `SSL_connect,`, which leaves a risk. I do not see a good reason for closing it before that topic is settled.
Is using a memory BIO considered synchronous, asynchronous or irrelevant?

**Comment by t8m** [comment]
This does not have anything with memory BIO but with using SSL object from multiple threads without explicit mutexes protecting from simultaneous access.

**Comment by httpstorm** [comment]
@t8m  Thank you!
After switching to OpenSSL 1.1.1l the issue was more obvious and easy to reproduce. As per your advice I was able to fix it by protecting access to the SSL and WBIO objects. WBIO had to be protected because a read request may generate output traffic. I'm not sure if I also need to protect the RBIO? So far everything works fine without that. To my knowledge it is only used in the receive function, so single thread, since SSL_write from another thread does not access it, does it?

**Comment by davidben** [comment]
While not very common, it is possible for SSL_write to touch the rbio and for SSL_read to touch the wbio. But since you need to read the SSL object itself as single-threaded, it's probably simpler to lock SSL and the two BIOs all together. And then extract data from the memory BIOs under that same lock. Then you don't have to worry about this.

**Comment by httpstorm** [comment]
Thanks @davidben !
I protected the SLL object along with both RBIO and WBIO as a good measure and only unlock during socket IO.
I've been wondering if it is possible to use `BIO_set_mem_buf(RBIO)` instead of `BIO_write(RBIO)`? My attempts so far cause the session to fail. On the other hand using `BIO_get_mem_ptr(WBIO)` instead of `BIO_read(WBIO)` works just fine:

```
BUF_MEM * bm = NULL;
BIO_get_mem_ptr(WBIO, &bm);
send(bm->data, bm->length);
bm->length = 0;
BIO_set_shutdown(WBIO, BIO_NOCLOSE);
BIO_set_mem_buf(WBIO, bm, BIO_CLOSE);
```
