### ISSUE TITLE
Microsoft Defender & fuzz files

### ISSUE THREAD

**Issue by gvanem** [openssl/openssl#16406]
I got this warning from Microsoft's Antivirus (Defender) just now:
![OpenSSL-fuzz-virus](https://user-images.githubusercontent.com/945271/130654256-248996e3-714c-4b83-8bb0-65a1c4022bf6.png)

*Translation*:  
  Microsoft Defender Antivirus wants to check if the following files are safe.
   `Send chosen` | `Do not send`

This occurred while doing a GNU-diff of all the OpenSSL files (comparing with another version). 
So reading these new fuzz-files triggered this warning perhaps? I've never seen such warning
on **any** fuzz-files before. What's this?

I'm on Win-10.

**Comment by paulidale** [comment]
A false positive I suspect.

**Comment by TCode110** [comment]
you can try to update your Microsoft Defender and then check

**Comment by gvanem** [comment]
> you can try to update your Microsoft Defender and then check

No issue today when I did a `git pull` followed by another `diff` command. 
So probably just a fluke event? Closing.
