### ISSUE TITLE
1.1.1l cannot be built on older (than yosemite) OSX anymore

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#16407]
In https://github.com/conda-forge/openssl-feedstock/pull/67, there's the following error:
```
[...]
x86_64-apple-darwin13.4.0-clang -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-1.1.1l -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -I. -Iinclude -fPIC -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-1.1.1l -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"$PREFIX/ssl\"" -DENGINESDIR="\"$PREFIX/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -MMD -MF crypto/rand/rand_unix.d.tmp -MT crypto/rand/rand_unix.o -c -o crypto/rand/rand_unix.o crypto/rand/rand_unix.c
crypto/rand/rand_unix.c:38:11: fatal error: 'CommonCrypto/CommonRandom.h' file not found
# include <CommonCrypto/CommonRandom.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

The build [recipe](https://github.com/conda-forge/openssl-feedstock/blob/master/recipe/build.sh) used to run through for `1.1.1k`.

Looking at https://github.com/openssl/openssl/blame/OpenSSL_1_1_1l/crypto/rand/rand_unix.c#L37-L39, this was added by #15935. @paulidale @t8m @devnexen

**Comment by ericonr** [comment]
Basically duplicate of #16408

**Comment by noloader** [comment]
@ericonr,

If I am parsing things correctly, there are two bugs. The first is 16407, where including `<CommonCrypto/CommonRandom.h>` results in a compile error. I assume the compile error is due to something like `-Werror`. The second is 16408, where the missing include generates a warning, but the build errors on use of `kCCSuccess` errors and `CCRandomGenerateBytes` generates another warning. `CCRandomGenerateBytes` will eventually fail to link.

**Comment by debohman** [comment]
We fixed this several weeks ago on the trunk.

#16248

**Comment by debohman** [comment]
I just checked a Mavericks (10.9) root, and headers for CommonCrypto exist, but CommonCrypto/CommonRandom.h does not exist. That must be a later extension to the API.

**Comment by devnexen** [comment]
yes introduced in yosemite.

**Comment by noloader** [comment]
@debohman,

> I just checked a Mavericks (10.9) root, and headers for CommonCrypto exist, but CommonCrypto/CommonRandom.h does not exist. That must be a later extension to the API.

Yes, confirmed. OpenSSL no longer builds on OS X 10.9 either.

**Comment by h-vetinari** [comment]
After the merge of https://github.com/openssl/openssl/commit/96ac8f13f4d0ee96baf5724d9f96c44c34b8606c, I believe this issue can now be closed. Thanks everyone.

**Comment by francisuk1989** [comment]
https://github.com/Homebrew/homebrew-core/issues/84337

**Comment by francisuk1989** [comment]
I followed a guide on a temporary fix here https://stackoverflow.com/questions/68957915/macos-10-12-brew-install-openssl-issue/69057786#69057786 but after **make test** I'm faced with this error?

```
==> make test
Last 15 lines from /Users/francis/Library/Logs/Homebrew/openssl@1.1/04.make:
../test/recipes/95-test_external_boringssl.t ....... skipped: No external tests in this configuration
../test/recipes/95-test_external_krb5.t ............ skipped: No external tests in this configuration
../test/recipes/95-test_external_pyca.t ............ skipped: No external tests in this configuration
../test/recipes/99-test_ecstress.t ................. ok
../test/recipes/99-test_fuzz.t ..................... ok

Test Summary Report
-------------------
../test/recipes/05-test_rand.t                   (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=158, Tests=2630, 216 wallclock secs ( 3.40 usr  0.47 sys + 146.68 cusr 65.16 csys = 215.71 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make: *** [tests] Error 2
```
