### ISSUE TITLE
PKCS7_verify() unnecessarily creates temp indata BIO which ignores caller's indata BIO callbacks

### ISSUE THREAD

**Issue by bobm21** [openssl/openssl#16429]
This PKCS7_verify() [performance optimization](https://github.com/openssl/openssl/commit/fcd5cca418c1efcd420cfbdcd56182e0524698c1#) from 2005 creates a new RO mem BIO from the caller's indata mem BIO, even if it's already a RO mem BIO in this code block:

https://github.com/openssl/openssl/blob/69b920bb134417213adce260e15da3f751922cf4/crypto/pkcs7/pk7_smime.c#L301-L318

I have a use case for a callback on a RO mem indata BIO passed to PKCS7_verify() and simply added a test for the indata BIO already being RO to the if statement to avoid the creation of the new tmpin BIO in OpenSSL 1.1.1j so that my callback remained in effect:
```
if (indata && (BIO_method_type(indata) == BIO_TYPE_MEM) &&
    !BIO_test_flags(indata, BIO_FLAGS_MEM_RDONLY)) {
```

However, after taking a closer look, the performance issue with reading RW mem BIOs that existed at the time of this optimization no longer exists, so all the logic related to the tmpin RO mem BIO should be deleted and the caller's indata BIO used as-is.

**Comment by faramir-dev** [comment]
It looks this issue was already fixed: https://github.com/openssl/openssl/pull/16590.

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Kha, 26 Ogo 2021, 8:55 AM Bob Morgan ***@***.***>
menulis:
