### ISSUE TITLE
Beta3 release?

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#16431]
I understand people cannot wait to get the release out the door. At the same time, it's been 4 weeks since beta2, and quite a few changes (incl. some larger ones like #16203, #16286, etc.) have landed since then.

Wouldn't it be worth considering to release beta3 as one more release candidate, and if (fingers' crossed) nothing else turns up, make the actual release a week (or so) later?

**Comment by paulidale** [comment]
OTC: beta3 is not planned.
