### ISSUE TITLE
openssl s_client gives: Verification error: certificate signature failure on 1 machine; works on other 3 machines

### ISSUE THREAD

**Issue by MirtoBusico** [openssl/openssl#16432]
I have a machine with an apache web server (see the framework in attachment [sslconfig.txt](https://github.com/openssl/openssl/files/7057947/sslconfig.txt) )

Accessing this server from machine 2  with the command

```
openssl s_client -connect p01serv.p01.net:443 -servername p01serv.p01.net < /dev/null >sslmachine2error.txt 2>&1
```

gives the error

```
SSL handshake has read 1503 bytes and written 387 bytes
Verification error: certificate signature failure
```
The complete output 
[sslmachine2error.txt](https://github.com/openssl/openssl/files/7058072/sslmachine2error.txt)
 

Data for machine 2 (laptop)
name/address: santech 192.168.68.16
operating system: Linux santech 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
openssl version: OpenSSL 1.1.1f  31 Mar 2020
Result file: sslmachine2error.txt

Doing the same command on othe three machines works perfectly
The complete output of the other three machines
[sslmachine4.txt](https://github.com/openssl/openssl/files/7058148/sslmachine4.txt)
[sslmachine3.txt](https://github.com/openssl/openssl/files/7058150/sslmachine3.txt)
[sslmachine1.txt](https://github.com/openssl/openssl/files/7058151/sslmachine1.txt)

What can I do / investigate?

**Comment by kaduk** [comment]
The error is coming from https://github.com/openssl/openssl/blob/OpenSSL_1_1_1f/crypto/x509/x509_vfy.c#L1747-L1748 and typically indicates that there is something awry with the signature on the certificate being verified.  Are you sure your webserver is sending the correct certificate chain up to (but not including) a trusted root?

**Comment by kaduk** [comment]
Also, 1.1.1f is quite old; if that's a stock 1.1.f (as opposed to an OS-vendor-patched copy) you should probably upgrade.

**Comment by MirtoBusico** [comment]
Thanks

Well, the webserver is an apache 2 configured with
```
<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerAdmin webmaster@localhost
                ServerName k6k.p01.net

                DocumentRoot /var/www/k6k

                ErrorLog ${APACHE_LOG_DIR}/errork6k.log
                CustomLog ${APACHE_LOG_DIR}/accessk6k.log combined

                SSLCertificateFile      /home/sysop/p01certs/k6k.crt
                SSLCertificateKeyFile   /home/sysop/p01certs/k6k.key

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                # –----------------------------------------------- 
                #        Keycloak
                # –----------------------------------------------- 

                ProxyPreserveHost On
                SSLProxyEngine On
                SSLProxyCheckPeerCN On
                SSLProxyCheckPeerExpire On
                RequestHeader set X-Forwarded-Proto "https"
                RequestHeader set X-Forwarded-Port "443"
                ProxyRequests Off
                ProxyPass / http://127.0.0.1:8080/
                ProxyPassReverse / http://127.0.0.1:8080/

        </VirtualHost>
</IfModule>
```
which uses k6k.crt and k6k.key
This is used for all the four machines

About the version I installed the Ubuntu packages with
```
sudo apt install openssh-server
```

This gives me the OpenSSL 1.1.1j on Ubuntu 21.04 and OpenSSL 1.1.1f on Ubuntu 20.04

The mistery for me is that three machines with two version of openssl work correctly and only one gives the error.

Any suggestion?

**Comment by kaduk** [comment]
The same cert is used on all four machines?  The file contents for both k6k.crt and k6k.key are the same on all four machines?

If I was trying to debug this I would probably save the certificate and chain to files, then switch from `openssl s_client` to `openssl verify` (still on the machine experiencing issues) in order to get something that's easier to run in a debugger and step through where verification fails.  (That would also let the same verify command be tried out on the other systems.)
Note that `openssl verify` will need `-purpose sslserver` and possibly `-x509_strict` in order to do the same checks that `s_client` does.

**Comment by MirtoBusico** [comment]
I'll try asap
