### ISSUE TITLE
Failed to load 'legacy' provider when linking OpenSSL libraries statically on AIX

### ISSUE THREAD

**Issue by EasonYu-Centrify** [openssl/openssl#16455]
I build OpenSSL 3.0 beta1 on AIX 6.1 successfully, then I tried to write a simple program (Ref: no_fips_mode.c) to test it. 

```
bash-4.3# uname -a
AIX vAIX61-2 1 6 00C12AB64C00
```
**no_fips_mode.c**
```
#include <stdio.h>
#include <stdlib.h>

#include <openssl/provider.h>
#include <openssl/evp.h>

int main()
{
    OSSL_PROVIDER *deflt;
    OSSL_PROVIDER *legacy;

    legacy = OSSL_PROVIDER_load(NULL, "legacy");
    if (legacy == NULL) {
        printf("Failed to load legacy provider\n");
        return 1;
    }

    deflt = OSSL_PROVIDER_load(NULL, "default");
    if (deflt == NULL) {
        OSSL_PROVIDER_unload(legacy);
        printf("Failed to load default provider\n");
        return 1;
    }

    EVP_MD_CTX *ctx;
    EVP_MD* md4;

    ctx = EVP_MD_CTX_new();
    //md4 = EVP_md4();
    md4 = EVP_MD_fetch(NULL, "MD4", "fips=no");

    int ok = EVP_DigestInit_ex(ctx, md4, NULL);
    if (!ok)
    {
        printf("Failed to init digest context\n");
    }
    else
    {
        printf("Succeed in init digest context\n");
    }

    EVP_MD_CTX_free(ctx);
}
```
When I build it with linking OpenSSL libraries dynamically, then it can work as expected, but when I tried to build it with linking OpenSSL libraries statically, then it failed to load 'legacy' provider, ref:
```
bash-4.3# gcc no_fips_mode.c -maix64 -Wl,-brtl -I/usr/share/centrifydc/include -I/usr/share/centrifydc/kerberos/include -L /usr/share/centrifydc/lib64 -lcrypto -lssl -o no_fips_mode
bash-4.3# ./no_fips_mode
Succeed in init digest context
```
```
bash-4.3# gcc no_fips_mode.c -maix64 -I/usr/share/centrifydc/include -I/usr/share/centrifydc/kerberos/include -o no_fips_mode_static_link /usr/share/centrifydc/lib64/libcrypto.a /usr/share/centrifydc/lib64/libssl.a
bash-4.3# ./no_fips_mode_static_link
Failed to load legacy provider
```

**Comment by Tarnum-tst** [comment]
To make static link work liblegacy.a should be linked also.

**Comment by EasonYu-Centrify** [comment]
@Tarnum-tst No. OSSL_PROVIDER_load(NULL, "legacy") is supposed to load legacy.so dynamically. This issue only exist for 'legacy' provider on AIX. OSSL_PROVIDER_load(NULL, "fips") can work well on AIX (both static and dynamic link). Also, this issue does not exist on the other platforms.

BTW, @Tarnum-tst are you a member of OpenSSL contributor? P.S. And, obviously, In order to use 'legacy' provider, you do not need to configure 'enable-legacy' explicitly.

**Comment by mattcaswell** [comment]
Looks like a possible AIX bug. The legacy provider should be built-in when linking statically.

**Comment by EasonYu-Centrify** [comment]
@mattcaswell I tried to run 'truss' against my another test program (FIPS mode), but fip.so can be loaded successfully. Note: both fips.so and legacy.so exist under .../lib64/oss-modules dir. FYI:
```
...
kload("/usr/share/centrifydc/lib64/ossl-modules/fips.so", 17367680, "") = 648518346072918280
kopen("/usr/share/centrifydc/lib64/ossl-modules/fips.so", O_RDONLY) = 3
...
kload("/usr/share/centrifydc/lib64/ossl-modules/legacy.so", 17367680, "") = 0
...
```

fips_mode.c
```
#include <stdio.h>
#include <stdlib.h>

#include <openssl/provider.h>
#include <openssl/evp.h>

int main()
{
    OSSL_PROVIDER *fips;
    OSSL_PROVIDER *base;
    OSSL_PROVIDER *legacy;


    fips = OSSL_PROVIDER_load(NULL, "fips");
    if (fips == NULL) {
        printf("Failed to load FIPS provider\n");
        return 1;
    }

    base = OSSL_PROVIDER_load(NULL, "base");
    if (base == NULL) {
        OSSL_PROVIDER_unload(fips);
        printf("Failed to load base provider\n");
        return 1;
    }

    legacy = OSSL_PROVIDER_load(NULL, "legacy");
    if (legacy == NULL) {
        OSSL_PROVIDER_unload(fips);
        OSSL_PROVIDER_unload(base);
        printf("Failed to load legacy provider\n");
        return 1;
    }

    int rc = EVP_default_properties_enable_fips(NULL, 1);
    if (!rc)
        printf("Failed to enable FIPS\n");

    EVP_MD_CTX *ctx;
    EVP_MD* md4;

    ctx = EVP_MD_CTX_new();
    //md4 = EVP_md4();
    md4 = EVP_MD_fetch(NULL, "MD4", "fips=no");
    EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);

    int ok = EVP_DigestInit_ex(ctx, md4, NULL);
    if (!ok)
    {
        printf("Failed to init digest context\n");
    }
    else
    {
        printf("Succeed in init digest context\n");
    }

    EVP_MD_CTX_free(ctx);
}
```

**Comment by t8m** [comment]
This looks like another instance of missing symbols in legacy.so. Could you please dump the symbol table in legacy.so to see which symbols are undefined in there?

**Comment by t8m** [comment]
Also could you please try beta2?

**Comment by EasonYu-Centrify** [comment]
> This looks like another instance of missing symbols in legacy.so. Could you please dump the symbol table in legacy.so to see which symbols are undefined in there?
```
-bash-4.3$ nm -X64 -u /usr/share/centrifydc/lib64/ossl-modules/legacy.so
.___memmove64        U       62464
.___memset64         U       59400
ASN1_TYPE_free       U           -
ASN1_TYPE_get_int_octetstring U           -
ASN1_TYPE_new        U           -
ASN1_TYPE_set_int_octetstring U           -
BF_cbc_encrypt       U           -
BF_cfb64_encrypt     U           -
BF_ecb_encrypt       U           -
BF_ofb64_encrypt     U           -
BF_set_key           U           -
CAST_cbc_encrypt     U           -
CAST_cfb64_encrypt   U           -
CAST_ecb_encrypt     U           -
CAST_ofb64_encrypt   U           -
CAST_set_key         U           -
CRYPTO_clear_free    U           -
CRYPTO_free          U           -
CRYPTO_malloc        U           -
CRYPTO_zalloc        U           -
DES_cfb64_encrypt    U           -
DES_cfb_encrypt      U           -
DES_ecb_encrypt      U           -
DES_ofb64_encrypt    U           -
DES_set_key_unchecked U           -
DES_set_odd_parity   U           -
DES_xcbc_encrypt     U           -
ENGINE_by_id         U           -
ENGINE_finish        U           -
ERR_clear_last_mark  U           -
ERR_new              U           -
ERR_pop_to_mark      U           -
ERR_set_debug        U           -
ERR_set_error        U           -
ERR_set_mark         U           -
EVP_CIPHER_fetch     U           -
EVP_CIPHER_free      U           -
EVP_CIPHER_up_ref    U           -
EVP_DigestFinal_ex   U           -
EVP_DigestInit_ex    U           -
EVP_DigestUpdate     U           -
EVP_MAC_CTX_free     U           -
EVP_MAC_CTX_new      U           -
EVP_MAC_CTX_set_params U           -
EVP_MAC_fetch        U           -
EVP_MAC_free         U           -
EVP_MD_CTX_free      U           -
EVP_MD_CTX_new       U           -
EVP_MD_fetch         U           -
EVP_MD_free          U           -
EVP_MD_get_size      U           -
EVP_MD_up_ref        U           -
EVP_get_cipherbyname U           -
EVP_get_digestbyname U           -
IDEA_cbc_encrypt     U           -
IDEA_cfb64_encrypt   U           -
IDEA_ecb_encrypt     U           -
IDEA_ofb64_encrypt   U           -
IDEA_set_decrypt_key U           -
IDEA_set_encrypt_key U           -
MD4_Final            U           -
MD4_Init             U           -
MD4_Update           U           -
MDC2_Final           U           -
MDC2_Init            U           -
MDC2_Update          U           -
OSSL_LIB_CTX_free    U           -
OSSL_LIB_CTX_new_child U           -
OSSL_PARAM_construct_end U           -
OSSL_PARAM_construct_octet_string U           -
OSSL_PARAM_construct_utf8_string U           -
OSSL_PARAM_get_octet_string U           -
OSSL_PARAM_get_size_t U           -
OSSL_PARAM_get_uint  U           -
OSSL_PARAM_get_uint64 U           -
OSSL_PARAM_locate    U           -
OSSL_PARAM_locate_const U           -
OSSL_PARAM_set_int   U           -
OSSL_PARAM_set_octet_ptr U           -
OSSL_PARAM_set_octet_string U           -
OSSL_PARAM_set_size_t U           -
OSSL_PARAM_set_uint  U           -
OSSL_PARAM_set_utf8_ptr U           -
RAND_bytes_ex        U           -
RAND_priv_bytes_ex   U           -
RC2_cbc_encrypt      U           -
RC2_cfb64_encrypt    U           -
RC2_ecb_encrypt      U           -
RC2_ofb64_encrypt    U           -
RC2_set_key          U           -
RC4                  U           -
RC4_set_key          U           -
RIPEMD160_Final      U           -
RIPEMD160_Init       U           -
RIPEMD160_Update     U           -
SEED_cbc_encrypt     U           -
SEED_cfb128_encrypt  U           -
SEED_ecb_encrypt     U           -
SEED_ofb128_encrypt  U           -
SEED_set_key         U           -
WHIRLPOOL_Final      U           -
WHIRLPOOL_Init       U           -
WHIRLPOOL_Update     U           -
___memmove64         U       62464
___memset64          U       59400
__fd_getdtablesize   U           -
__fd_select          U           -
d2i_ASN1_TYPE        U           -
i2d_ASN1_TYPE        U           -
strtod               U           -
```

**Comment by EasonYu-Centrify** [comment]
@t8m 
> Also could you please try beta2?

Just tried, this issue also exists with beta2.

**Comment by t8m** [comment]
The undefined symbols mean that the legacy.so expects a libcrypto.so to be loaded. Which you do not have when the app is statically linked against libcrypto.

**Comment by paulidale** [comment]
OTC: this is a bug but it isn't a blocker for the 3.0 release.

**Comment by EasonYu-Centrify** [comment]
@paulidale Not sure if it's a easy or complicated fix, but I still hope it can be fixed in 3.0 release. If not, is there any workaround for it? Thanks!

**Comment by levitte** [comment]
If you use the default configuration, then you'll currently get a dynamically loadable legacy provider.  Period.

There is, however, a workaround to get the legacy provider built into libcrypto: configure with `no-module`
The drawback with that configuration is that you get no dynamically loadable modules at all, neither dynamically loadable providers nor engines.

To support having the legacy provider built into libcrypto while still being able to have all other dynamically loadable modules as such, we'd need a special configuratoin option, something like `builtin-legacy-provider`...  This won't be part of 3.0.0, though, we're just much too close to release.

**Comment by t8m** [comment]
@EasonYu-Centrify Have you actually tried to configure with:
```
./Configure no-shared enable-fips
```

**Comment by t8m** [comment]
Because the default configuration is a shared build and a legacy provider from shared build rightfully expects libcrypto.so to be available.

**Comment by levitte** [comment]
Something to note is that it wouldn't be too difficult to *also* offer the legacy provider as a static library.  The application would have to make a call like this to integrate it, though:

``` C
OSSL_provider_init_fn ossl_legacy_provider_init;

OSSL_PROVIDER_add_builtin(NULL, "legacy", ossl_legacy_provider_init);
```

**Comment by EasonYu-Centrify** [comment]
@t8m No, I didn't try "no-shared" because I don't think it's the proper option for me. 

Actually, I'd like to have a shared build, then I can use them (shared library + static archive) for different cases.

**Comment by EasonYu-Centrify** [comment]
@levitte I will check if it can work well for my case tomorrow. Thanks!

**Comment by t8m** [comment]
> @t8m No, I didn't try "no-shared" because I don't think it's the proper option for me.
> 
> Actually, I'd like to have a shared build, then I can use them (shared library + static archive) for different cases.

Then you need to do two builds. A default one and no-shared one. And if you're concerned about the legacy and fips provider duplication - the fips provider from any of the two builds should be usable with both dynamically and statically linked apps. And the legacy provider from the no-shared build should be usable with both default and no-shared build.

**Comment by levitte** [comment]
I'm not sure why `no-shared` would be needed, that should only mean that shared libcrypto and libssl won't be produced.  We do produce the static libcrypto and libssl variants *either way*.

**Comment by levitte** [comment]
... although [ahem] AIX is a bit special, I may forget how things are done there...

**Comment by t8m** [comment]
The difference is in how the legacy.so looks like in the no-shared build vs the shared build. In the no-shared build it is linked with libcrypto.a but in the shared build with libcrypto.so. And you do not have libcrypto.so loaded if you want to have an application statically linked with libcrypto.

**Comment by levitte** [comment]
> The difference is in how the legacy.so looks like in the no-shared build vs the shared build. In the no-shared build it is linked with libcrypto.a but in the shared build with libcrypto.so. And you do not have libcrypto.so loaded if you want to have an application statically linked with libcrypto.

I suggest you scroll up and read https://github.com/openssl/openssl/issues/16455#issuecomment-909458193

**Comment by EasonYu-Centrify** [comment]
@levitte As you mentioned, 'no-module' option can get legacy provider built into libcrypto. Do you have idea if it's also possible to get the fips provider built into libcrypto? Thanks!

**Comment by levitte** [comment]
No, the fips module is available as a dynamically loadable module only. We do it this way because of boundary requirements.

**Comment by t8m** [comment]
Closing as there is a way how to built-in the legacy provider and I do not think we want to explicitly support other scenarios.
