### ISSUE TITLE
X509_NAME_ENTRY_set_data() modified flag not changed

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1645]
I' m using the function X509_NAME_ENTRY_set_data() for changing the value of a RDN. I experienced a strange behavior. After getting the certificate in der or pem format the value isn't changed! When I'm using X509_NAME_delete_entry and X509_NAME_add_entry_by_NID it works fine. I think that the modified flag of X509_NAME within the function X509_NAME_ENTRY_set_data is not set which should take over the changed string.

**Comment by levitte** [comment]
The X509_NAME_ENTRY functions have no knowledge of the X509_NAME structure that might or might not include them.  So yeah, to get it right, use the X509_NAME functions.
