### ISSUE TITLE
Query regarding  ECDSA POST test

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [openssl/openssl#16457]
Hello,

The POST log says "ECDSA : (KAT_Signature) : Pass"
But when i debugged the code , it is actually doing a pairwise consistency test, i.e generate signature using random k and verify the signature at the end.
But as far as i know , for KAT we need to fix the random value K for generating the signature and compare with the know signature value.   Please let me know if i missing anything here  and about my understanding regarding  KAT and PWCT(pairwise consistency test).

Thanks,
Nagarjun

**Comment by paulidale** [comment]
@slontis ??

**Comment by slontis** [comment]
Yes it is a pairwise test..

https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/fips140-2/fips1402ig.pdf
9.4 Known Answer Tests for Cryptographic Algorithms

````
for algorithms whose output vary for a given set of inputs
such as DSA and ECDSA, they shall
be tested either,
1. as a KAT similar to RSA for signature generation or verification if the randomization parameter is fixed, or
2. as a pair-wise consistency test. This test does not require the comparison of the intermediate result (the generated signature) to a known value.

Note9: a KAT or pair-wise consistency test for DSA shall be performed at a minimum on any one approved modulus size that is supported by the module.
Note10: a KAT or pair-wise consistency for ECDSA shallbeperformed at a minimum, on any one of the implemented curves in each of the implemented two types of fields (i.e., prime field GF(p), and binary field GF(2m))
````

**Comment by slontis** [comment]
I will change the string associated with these tests... Note that this will be a different name from the conditional pairwise tests that get run during keygen..
