### ISSUE TITLE
brew install openssl@1.1 - Last 15 lines from /Users/$User/Library/Logs/Homebrew/openssl@1.1/02.make:

### ISSUE THREAD

**Issue by HELMAB** [openssl/openssl#16458]
macOS High Sierra
Version: 10.13.6

Last 15 lines from /Users/helmab/Library/Logs/Homebrew/openssl@1.1/02.make:
crypto/rand/rand_vms.o crypto/rand/rand_vms.c
In file included from crypto/rand/rand_unix.c:38:
/usr/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
typedef CCCryptorStatus CCRNGStatus;
        ^
crypto/rand/rand_unix.c:385:47: error: use of undeclared identifier 'kCCSuccess'
    if (CCRandomGenerateBytes(buf, buflen) == kCCSuccess)
                                              ^
2 errors generated.
make[1]: *** [crypto/rand/rand_unix.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

I can't install openssl@1.1.1l on my mac machine. Can anyone help?

**Comment by xtkoba** [comment]
First you should try out the fix for #16407 (and #16408).

**Comment by HELMAB** [comment]
> First you should try out the fix for #16407 (and #16408).

Thank you for your reply, but [#16407](https://github.com/openssl/openssl/issues/16407) is still open and [#16408](https://github.com/openssl/openssl/issues/16408) is closed because it duplicated with [#16407](https://github.com/openssl/openssl/issues/16407)

**Comment by xtkoba** [comment]
I mean https://github.com/openssl/openssl/commit/96ac8f13f4d0ee96baf5724d9f96c44c34b8606c

**Comment by HELMAB** [comment]
> I mean [96ac8f1](https://github.com/openssl/openssl/commit/96ac8f13f4d0ee96baf5724d9f96c44c34b8606c)

it absolutely works. thank you

**Comment by werksone** [comment]
> > I mean [96ac8f1](https://github.com/openssl/openssl/commit/96ac8f13f4d0ee96baf5724d9f96c44c34b8606c)
> 
> it absolutely works. thank you

Would love to know a little more info on exactly how you got this running with brew, I have run into the same problem today

**Comment by HELMAB** [comment]
Yes, what I did

1. Download [openssl](https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1l.zip)
2. Extract it 
3. Open the folder with a texteditor to update 2 files on this [commit](https://github.com/openssl/openssl/commit/96ac8f13f4d0ee96baf5724d9f96c44c34b8606c)
4. cd `openssl-OpenSSL_1_1_1l`
5. run command `perl ./Configure --prefix=/usr/local/Cellar/openssl@1.1/1.1.1l --openssldir=/usr/local/etc/openssl@1.1 no-ssl3 no-ssl3-method no-zlib darwin64-x86_64-cc enable-ec_nistp_64_gcc_128`
6. run command `make`
7. run command `make test`
8. run command `sudo make install` # need sudo if you have no permission to create folder or file
9. run command `ln -sf /usr/local/Cellar/openssl@1.1/1.1.1l /usr/local/opt/openssl@1.1`

**Comment by werksone** [comment]
Fantastic, This worked perfectly. Thanks very much for your help!

**Comment by werksone** [comment]
> Hello [@weksone](https://github.com/werksone) Yes, what I did
> 
> 1. Download [openssl](https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1l.zip)
> 2. Extract it
> 3. Open the folder with a texteditor to update 2 files on this [commit](https://github.com/openssl/openssl/commit/96ac8f13f4d0ee96baf5724d9f96c44c34b8606c)
> 4. cd `openssl-OpenSSL_1_1_1l`
> 5. run command `perl ./Configure --prefix=/usr/local/Cellar/openssl@1.1/1.1.1l --openssldir=/usr/local/etc/openssl@1.1 no-ssl3 no-ssl3-method no-zlib darwin64-x86_64-cc enable-ec_nistp_64_gcc_128`
> 6. run command `make`
> 7. run command `make test`
> 8. run command `sudo make install` # need sudo if you have no permission to create folder or file
> 9. run command `ln -sf /usr/local/Cellar/openssl@1.1/1.1.1l /usr/local/opt/openssl@1.1`

Fantastic, This worked perfectly. Thanks very much for your help!

**Comment by crazyi** [comment]
The simplest method is adding the `-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include ` to args array in `configure_args` with the command _brew edit openssl_  from [stackoverflow](https://stackoverflow.com/questions/68957915/macos-10-12-brew-install-openssl-issue)
