### ISSUE TITLE
Due date (or tentative date) for openssl 3.0.0 GA

### ISSUE THREAD

**Issue by satya-rajesh** [openssl/openssl#16467]
Hi Openssl team,

Would like to know if there is any due date to share for openssl 3.0.0 GA release.

**Comment by mattcaswell** [comment]
By 2021-09-21 at the latest. Maybe before.

**Comment by mattcaswell** [comment]
FYI, OTC passed the following vote at yesterday's OTC meeting:

"topic: Release 3.0.0 final on Tuesday the 7th of September 2021 if run-checker and CI builds have been clean for two days."

**Comment by satya-rajesh** [comment]
> FYI, OTC passed the following vote at yesterday's OTC meeting:
> 
> "topic: Release 3.0.0 final on Tuesday the 7th of September 2021 if run-checker and CI builds have been clean for two days."

If there is any change in plan, please keep us updated :)
