### ISSUE TITLE
RSA private key DER decode fails without CRT components

### ISSUE THREAD

**Issue by bkommanaboyina** [openssl/openssl#16479]
I'm trying to decode the RSA private key which was DER encoded earlier without p, q, and CRT components (dmp1, dmq1 and iqmp is NULL). I'm using same openssl version for both encoding and decoding, encoding works fine but decode fails. In decode we call EVP_PKCS82PKEY() function, this is failing with below error:

**_469393408:error:0D078079:asn1 encoding routines:asn1_item_embed_d2i:field missing:crypto/asn1/tasn_dec.c:425:Field=p, Type=RSAPrivateKey_**

The above error is because field p is NULL, but with same p is NULL encoding is success. Any idea why encode is Success but decode fails?

The openssl version I tested is 1.1.1d.

The sample code:

To Encode RSA private key I used below code:

```
int encode_priv_key(EVP_PKEY * pkey, unsigned char *data, size_t * len)
{
    BIO *bio = NULL;
    BUF_MEM *bptr = NULL;
    PKCS8_PRIV_KEY_INFO *p8inf = NULL;

    if (NULL == len) {
        printf("%s:%d\n", __FILE__, __LINE__);
        return -1;
    }

    p8inf = EVP_PKEY2PKCS8(pkey);
    if (!p8inf) {
        printf("%s:%d\n", __FILE__, __LINE__);
        goto end;
    }

    bio = BIO_new(BIO_s_mem());
    if (!bio) {
        printf("%s:%d\n", __FILE__, __LINE__);
        goto end;
    }

    if (i2d_PKCS8_PRIV_KEY_INFO_bio(bio, p8inf) < 0) {
		printf("%s:%d\n", __FILE__, __LINE__);
        goto end;
	}

    BIO_get_mem_ptr(bio, &bptr);
    if ((*len < bptr->length) && data) {
        *len = bptr->length;
        printf("%s:%d\n", __FILE__, __LINE__);
        goto end;
	}
    *len = bptr->length;

    if (NULL != data)
        memcpy(data, bptr->data, *len);

    PKCS8_PRIV_KEY_INFO_free(p8inf);
    BIO_free(bio);
    return 0;
end:
    if (p8inf)
        PKCS8_PRIV_KEY_INFO_free(p8inf);
    if (bio)
        BIO_free(bio);
    return -1;
}

```
For decode we use below code:
```
EVP_PKEY *decode_priv_key(unsigned char *data, size_t len)
{
    BIO *bio = NULL;
    PKCS8_PRIV_KEY_INFO *p8inf = NULL;
    EVP_PKEY *pkey = NULL;

    bio = BIO_new_mem_buf(data, len);
    if (!bio) {
        printf("%s:%d\n", __FILE__, __LINE__);
        goto end;
    }

    p8inf = d2i_PKCS8_PRIV_KEY_INFO_bio(bio, NULL);
    if (!p8inf) {
        printf("%s:%d\n", __FILE__, __LINE__);
        goto end;
    }

    if (!(pkey = EVP_PKCS82PKEY(p8inf))) {
        printf("%s:%d\n", __FILE__, __LINE__);
        goto end;
    }

    PKCS8_PRIV_KEY_INFO_free(p8inf);
    BIO_free(bio);
    return pkey;

end:
    if (p8inf)
        PKCS8_PRIV_KEY_INFO_free(p8inf);
    if (bio)
        BIO_free(bio);
    if (pkey)
        EVP_PKEY_free(pkey);
    return NULL;
}

```
EVP_PKCS82PKEY() is failing with error reported above.

**Comment by bbbrumley** [comment]
Slight correction: parameters `p` and `q` are not CRT components.

**Comment by bkommanaboyina** [comment]
yeah agree, I mean p and q and missing CRT components.

**Comment by davidben** [comment]
The "successful" encoding is due to a bug. See https://github.com/openssl/openssl/issues/16026. OpenSSL 3.0 will have that bug fixed. Sadly, the bugfix had to be reverted in 1.1.1 because it was discovered that some TPM applications misused the `i2d_X509` API to encode a different, non-X.509, structure.

The serialization for RSA private keys is defined here. It only works for RSA keys with CRT parameters. RSA keys without CRT parameters are not serializable in any standard format that I'm aware of.
https://datatracker.ietf.org/doc/html/rfc8017#appendix-A.1.2

**Comment by bbbrumley** [comment]
> RSA keys without CRT parameters are not serializable in any standard format that I'm aware of

Yet you might be surprised what variations libraries are prepared to accept, due to the long history. See Tbl 1 and Appx A [here](https://arxiv.org/abs/1909.01785).

**Comment by bbbrumley** [comment]
> I'm not sure where you got this implication.

I don't think it's meant to be taken that way, although I see how you get that.

I read it as "our experiments tell us a lot of code is doing this", rather than "if you're not doing this, your code is wrong".

If you go back through the history of RFC 8017, you'll notice it pre-dates (by far) "SHOULD" "SHALL" etc considerations from RFC 8174.

Anyway, what a bunch of quacks. I'll send a scathing email to the authors now. Let me go find out who they are.

**Comment by levitte** [comment]
I think we can all agree that if an RSA key is claimed to be DER serialized according to PKCS#1 / RFC8017, it must serialize the structure of `RSAPrivateKey` or `RSAPublicKey`.  Otherwise, that serialization is something else, it simply isn't PKCS#1 / RFC8017 compliant.

**Comment by bbbrumley** [comment]
> I think we can all agree that if an RSA key is claimed to be DER serialized according to PKCS#1 / RFC8017, it must serialize the structure of `RSAPrivateKey` or `RSAPublicKey`

Totally

I'm derailing the original issue. My apologies, @bkommanaboyina 

Please continue like normal

**Comment by romen** [comment]
@levitte one of the points is exactly that, and the recent discussion at OTC that resulted in reverting #16027 in 1.1.1 (see #16308) is a perfect example. OpenSSL, and many other libraries, often err on the side of legacy compatibility or historical interoperability when faced with bugfixes: this means that buggy or not conformant behavior is tolerated (or even defaulted to) in input and output, and non-standard things become de-facto standards.

The long and twisted story of RSA gave us multiple instances of this as discussed above!

**Comment by davidben** [comment]
@romen I think you are mixing up parsing and serialization, as well as backwards compatibility with historical errors vs. introducing new errors.

I don't know of any version of that OpenSSL tolerated missing fields when *parsing* an RSAPrivateKey, so there's not actually a backwards-compatibility problem. While #16027 had to be reverted, that was for *serialization*. Serialization *was* broken in old OpenSSL. Fixing that ran into a backwards-compatibility problem in one particular consumer. That one particular consumer was misusing the API in a context that happened to work for their particular use case. It is not a generally applicable strategy. Omitting fields in ASN.1 does not work generally work. It ends up syntactically ambiguous if there is a run of fields with the same tag.

Indeed RSAPrivateKey is one such case. If you delete a field in the middle vs. at the end, there's no way to tell which field was deleted.

**Comment by romen** [comment]
@davidben I was mixing it deliberately to stay on the general side and reiterate that across libraries and products "uncommon" serialization output and tolerance for "uncommon" encodings on parsing is not that unusual after all, and usually justified by interoperability, legacy baggage, historical reasons, despite what the standards encourage, recommend, mandate or forbid!

**Comment by levitte** [comment]
Either way, this issue is about *decoding*, and the example code is *correctly* demonstrating that OpenSSL serialization could be made to produce utter shite.

The take away lesson here is really, don't misuse OpenSSL bugs :wink:

**Comment by levitte** [comment]
I would say that this issue can be closed at this point.  I hope I sprinkled enough response labels...

**Comment by t-j-h** [comment]
Up to PKCS#1 v1.5 there was additional text included that made it clear what you were meant to do for portability if you did not have the CRT components. Unfortunately this text was omitted in later versions. It makes it exceedingly clear that you aren't expected to omit values or place in substitute values in the ASN1 representation - if you don't have the CRT values you need to calculate them. **The syntax explicitly and deliberately requires the CRT values.**

> An RSA private key logically consists of only the
> modulus n and the private exponent d. The presence
> of the values p, q, d mod (p-1), d mod (p-1), and
> q-1 mod p is intended for efficiency, as
> Quisquater and Couvreur have shown [QC82]. A
> private-key syntax that does not include all the
> extra values can be converted readily to the
> syntax defined here, provided the public key is
> known, according to a result by Miller [Mil76].
>
