### ISSUE TITLE
1.0.2j: make test dumps core on solaris64-sparcv9-cc

### ISSUE THREAD

**Issue by makr** [openssl/openssl#1647]
Hi *,

there is an alignment issue in bad-dtls-test.c. The variable server_random is an unsigned char array of 32 bytes (line 257). Its address will later be handed to the time(2) function (line 776) which expects a pointer to a time_t value.

The build is using a Sun Studio 12.3 compiler and is not failing. But issuing 'make test' dumps core at test-bad-dtls with a SIGBUS on the time()-function call.

Solution proposal:
- my first attempt had been to insert a pragma statement:
  #pragma align 8 (client_random, server_random)
  at line 255 - this solves the issue for Solaris 64bit, but the code is still wrong
- a second way is to append -xmemalign=4i to the ./config script options - this too solves the issue, but seems to come with a notable performance penalty
- the third way is to get the access right in the code, without having tested on other systems yet:

``` C
static union {
  time_t as_time[SSL3_RANDOM_SIZE / sizeof(time_t)];
  unsigned char as_char[SSL3_RANDOM_SIZE];
} server_random;
...
time(&server_random.as_time[0]);
// anything else like: server_random.as_char
```

kind regards Matthias

**Comment by richsalz** [comment]
A less invasive solution is to use a temporary variable for the time_t call and then memcpy it into the srever random.

**Comment by makr** [comment]
I have been trying to find a way that doesn't change implementation, too much. So you are suggesting something along the way of:
```C
time_t now = 0L;
...
now = time(NULL);
memcpy( server_random, &now, sizeof(time_t) );
```

**Comment by kaduk** [comment]
Yes, that's a fine way to do it.  (But use sizeof(now) instead of sizeof(time_t).)

**Comment by richsalz** [comment]
Yes, exactly that.

**Comment by richsalz** [comment]
#1650 merged, closing.
