### ISSUE TITLE
OpenSSL FIPS Object Module for Apple Silicon (arm64)

### ISSUE THREAD

**Issue by pszyrko** [openssl/openssl#16492]
Hi.
I'm looking for an OpenSSL FIPS Object Module that supports Apple Silicon/M1 (arm64 arch). I only found this comment: https://github.com/openssl/openssl/issues/12254#issuecomment-733122210
Is there any plan to have a FIPS Object Module that supports Apple Silicon/M1?
Thanks

**Comment by mattcaswell** [comment]
The old OpenSSL FIPS  Object Module (2.0.x) is no longer being maintained by the project and hasn't been for sometime. Therefore this won't work on Apple Silicon. You might be able to find alternative FOMs based on OpenSSL from third parties that do, but I don't know whether such a module exists.

The OpenSSL 3.0 FIPS Object Module should build and run just fine on Apple Silicon/M1. OpenSSL 3.0 is currently in beta, but the final version is expected to be released next week:

https://mta.openssl.org/pipermail/openssl-project/2021-August/002729.html

However, this platform is not be on the initial list of platforms submitted for validation. So, assuming that list doesn't change, then that platform won't appear on the certificate when it eventually gets issued (next year sometime). IIUC it should be possible to "user affirm" the platform instead - but you would need to consult with a FIPS expert to figure out how to do this.

**Comment by pszyrko** [comment]
Thanks @mattcaswell
