### ISSUE TITLE
How do I extract an OCTET STRING with asn1parse -strparse $offset ?

### ISSUE THREAD

**Issue by grondilu** [openssl/openssl#16490]
Hello,

I'm trying to extract the exponent from an EC key generated with
ecparam -genkey.  I'm using asn1parse with the -strparse option and I
get a "header too long" error : 

```
$ openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021
$ openssl ecparam -name prime256v1 -noout -genkey |openssl asn1parse
    0:d=0  hl=2 l= 119 cons: SEQUENCE          
    2:d=1  hl=2 l=   1 prim: INTEGER           :01
    5:d=1  hl=2 l=  32 prim: OCTET STRING      [HEX DUMP]:8F95AA282BB968A4A09D6EA3238A0A4CDED4B45B635F3B8CF9906511C039C26C
   39:d=1  hl=2 l=  10 cons: cont [ 0 ]        
   41:d=2  hl=2 l=   8 prim: OBJECT            :prime256v1
   51:d=1  hl=2 l=  68 cons: cont [ 1 ]        
   53:d=2  hl=2 l=  66 prim: BIT STRING        
$ !! -strparse 5
openssl ecparam -name prime256v1 -noout -genkey |openssl asn1parse -strparse 5
Error in encoding
140113360803648:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:
```

'-strparse' takes an offset as argument and as shown in output the
octet string is at offset 5, isn't it?  What am I missing?

**Comment by t8m** [comment]
The private key is just a data, there is nothing to parse further with asn1parse in it.

**Comment by grondilu** [comment]
> The private key is just a data, there is nothing to parse further with asn1parse in it.

Ah, that makes sense.

**Comment by levitte** [comment]
The hex string that you see is literally a big number, MSB first.
