### ISSUE TITLE
EVP_PKEY object usage

### ISSUE THREAD

**Issue by yfaker** [openssl/openssl#16496]
Hi. 
I have a question about the EVP_PKEY object usage.
Step 1. Create a global EVP_PKEY object
Step 2. use the global EVP_PKEY object in multiple threads  concurrently to do signature verify
here is some code sample
```
//create the global EVP_PKEY object
EVP_PKEY *evp_key = EVP_PKEY_new();
//assign rsa key
EVP_PKEY_set1_RSA(*evp_key, rsa_key);

Thread 1
void verify1()
{
    EVP_MD_CTX *mdctx = EVP_MD_CTX_new();
    EVP_DigestVerifyInit(mdctx, NULL, EVP_sha256(), NULL, evp_key);
}

Thread 2
void verify2()
{
    EVP_MD_CTX *mdctx = EVP_MD_CTX_new();
    EVP_DigestVerifyInit(mdctx, NULL, EVP_sha256(), NULL, evp_key);
}
```

I wonder if this kind of usage is ok or may have safty issue?

Thanks a lot~

**Comment by paulidale** [comment]
You can't use one object across multiple threads.

**Comment by mattcaswell** [comment]
Errr....@paulidale...it should be safe to share an EVP_PKEY as long as you don't *change* the EVP_PKEY. We do this in libssl.

**Comment by paulidale** [comment]
Oops...

**Comment by yfaker** [comment]
thanks for your answers~
