### ISSUE TITLE
ciphers doc page is broken

### ISSUE THREAD

**Issue by 89z** [openssl/openssl#16509]
This page is correct:

https://www.openssl.org/docs/man1.1.1/man1/ciphers.html

in that you can actually see the ciphers documentation, such as:

~~~
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
~~~

while the newer page is broken:

https://www.openssl.org/docs/man3.0/man1/ciphers.html

it doesnt actually give any information about Ciphers, only about the OpenSSL command line tool.

**Comment by mspncp** [comment]
The content of

https://www.openssl.org/docs/man3.0/man1/ciphers.html

is indeed surprising for somebody looking for the man page for the `openssl ciphers` command. @levitte any ideas what happened here?

@89z note that all openssl commands are now prefixed with `openssl-`, i.e. the page you are looking for is now at

https://www.openssl.org/docs/man3.0/man1/openssl-ciphers.html

**Comment by 89z** [comment]
Looks like PHP (and maybe others) still linking to old page:

https://php.net/context.ssl#context.ssl.ciphers

**Comment by paulidale** [comment]
There was a naming rationalisation.  I'm not sure if it better, but it is at least consistent.
As noted `openssl-ciphers` is the man page you are looking for.

**Comment by levitte** [comment]
> @levitte any ideas what happened here?

Yes. If you read what's written there, it should actually be quite clear what happened; the older style pages are deprecated.

However, it would probably be nicer if the web variants were converted to a redirection to the new form.

**Comment by mspncp** [comment]
I was aware that the old style pages were replaced by the ones with the `openssl-` prefix. But I wasn't aware that the old pages were left in place with a new, rather confusing context. Shouldn't we just delete them or forward them to the new locations? As [@89z noted](https://github.com/openssl/openssl/issues/16509#issuecomment-913223228), downstream pages are linking to them.

**Comment by mspncp** [comment]
OTOH: I understand the intention to place it there. Maybe the page would be less confusing if the explanation would be moved from the **HISTORY** section at the bottom to the **DESCRIPTION** section where it is not so easily overlooked.

![grafik](https://user-images.githubusercontent.com/11467854/132164420-f547e044-44e9-4916-a07d-69335301027c.png)

**Comment by mspncp** [comment]
I'll propose a PR...

**Comment by levitte** [comment]
@mspncp, may I nudge your memory a bit?  b6b66573bdeb369636be66104687f211dfad03aa

**Comment by mspncp** [comment]
Ooops. 😊 I forgot it was me who changed it. As an excuse I may say that it was a pre-covid change, which feels like half a century ago.

Now I feel even more motivated to improve the quality of that confusing man page. 😉
