### ISSUE TITLE
What to do if the thread calls SSL_shutdown during the SSL asynchronous encryption process

### ISSUE THREAD

**Issue by hijj** [openssl/openssl#16514]
During the SSL negotiation process, when asynchronous hardware encryption is required, call ASYNC_pause_job to switch back from the coroutine and continue processing other events. At this time, when the TCP connection is disconnected, SSL_shutdown will be called, and ASYNC_start_job will be called to switch back to ASYNC_pause_job. Is it unreasonable in this case?

**Comment by mattcaswell** [comment]
> At this time, when the TCP connection is disconnected, SSL_shutdown will be called, and ASYNC_start_job will be called to switch back to ASYNC_pause_job. Is it unreasonable in this case?

You must not call other IO functions (including SSL_shutdown) on the SSL object while an asynchronous job is running. You must wait until the asynchronous job is complete.
