### ISSUE TITLE
openssl-passwd(1) doesn't give all algorithms in Description

### ISSUE THREAD

**Issue by RalphCorderoy** [openssl/openssl#16529]
https://www.openssl.org/docs/manmaster/man1/openssl-passwd.html says in Description:

> The MD5-based BSD password algorithm -1, its Apache variant -apr1, and its AIX variant are available.

I almost stopped reading there because I wanted SHA512. The Options section lists `-5` and `-6`; these should also be in Description's summary.

Or better still, get rid of that line as it's duplicating Options by not only listing the algorithms but giving their options too.

**Comment by levitte** [comment]
Fix in #16531
