### ISSUE TITLE
Segmentation fault in pthread_rwlock_timedrdlock ()

### ISSUE THREAD

**Issue by hapablanha** [openssl/openssl#16555]
We are building with OpenSSL_1.1.1l, and randomly encounter segfault, is this a known issue? 
![S(4U~NC0BE{ A4%)60OW)OX](https://user-images.githubusercontent.com/39362475/132463047-2e6f50d4-0b90-431c-8a2c-a6a8c57ec151.png)

**Comment by t8m** [comment]
No, we are not currently aware of any such issue.
