### ISSUE TITLE
Make it possible to get the currently used curve of a connection (on server-side)

### ISSUE THREAD

**Issue by Darkspirit** [openssl/openssl#1656]
> @richsalz  https://github.com/openssl/openssl/issues/1652#issuecomment-251085175
> Please open a separate issue for the “which curve” item

---

> @Darkudorus https://github.com/openssl/openssl/issues/1652#issuecomment-251083742
> Also it would be nice, if OpenSSL (on the server side) could tell nginx which curve is in use in the current connection for logging purposes. Original ticket: https://trac.nginx.org/nginx/ticket/1088

**Comment by Darkudorus** [comment]
Additional, when DHE is used over
- TLS 1.3, OpenSSL could output the FFDHE group name (ffdhe2048,ffdhe3072,ffdhe4096,ffdhe6144,ffdhe8192 https://tools.ietf.org/html/rfc7919#page-3) at this place.
- TLS 1.2 (and lower), OpenSSL could output anything like "dh4096" oder "dh2048".

I have no idea if it would better to return this information through a dedicated function to don't confuse (ECDHE<>DHE) server implementations.

**Comment by t8m** [comment]
Implemented by #14750
