### ISSUE TITLE
Why does my CPU support avx512ifMA, ossl_rsaz_avx512ifma_eligible is return 0?

### ISSUE THREAD

**Issue by zhangjie928** [openssl/openssl#16566]
I have set export OPENSSL_ia32cap, but it still does not work. Are there any other conditions that I should pay attention to?

**Comment by bernd-edlinger** [comment]
Your toolchain is likely too old.
In addition to the CPU features avx512vl + avx512ifma + avx512dq + avx512f
you need an assembler that is able to compile this code.
That is
- GNU assembler version >= 2.26
- NASM version >= 2.11.8
- LLVM clang version >=7.0

**Comment by paulidale** [comment]
Setting OPENSSL_ia32cap will also not override what the CPU actually offers.

**Comment by zhangjie928** [comment]
Thank you, I checked my compilation environment, GNU Assembler version has a problem, I will update the compilation environment later and try again.

**Comment by zhangjie928** [comment]
This is a compilation environment problem and has been resolved
