### ISSUE TITLE
Android build '__ANDROID_API__' macro redefined warnings

### ISSUE THREAD

**Issue by juha-h** [openssl/openssl#16560]
When I build OpenSSL_1_1_1-stable for Android using NDK 23.0.7599858 and following the instructions in NOTES-ANDROID, I get lots of __ANDROID_API__' macro redefined warnings that I didn't get when I was using NDK 21.4.7075529.

Configuration dump and start of the build log, where the warnings are shown are included.
[dump.log](https://github.com/openssl/openssl/files/7129724/dump.log)
[build.log](https://github.com/openssl/openssl/files/7129737/build.log)

**Comment by xtkoba** [comment]
`Configurations/15-android.conf` could be improved.

A workaround is to specify `-U__ANDROID_API__` such as

```
$ ./Configure android-arm64 no-shared -U__ANDROID_API__ -D__ANDROID_API__=21
```

Yes it is ugly, but it works.

**Comment by juha-h** [comment]
Thanks for the tip. I tested, and it worked. Please add this to `NOTES.ANDROID` if `Configurations/15-android.conf` is hard to fix.

**Comment by misery** [comment]
Maybe there is a proper fix for this that could be merged into openssl-3 branch? Seems hacky...
