### ISSUE TITLE
Why not OpenSSL-3_0-stable branch?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#16574]
All other releases have one, why not 3.0?
```
; git branch -r | grep stable
  origin/OpenSSL-engine-0_9_6-stable
  origin/OpenSSL-fips-0_9_7-stable
  origin/OpenSSL-fips-0_9_8-stable
  origin/OpenSSL-fips-1_2-stable
  origin/OpenSSL-fips-2_0-stable
  origin/OpenSSL-fips2-0_9_7-stable
  origin/OpenSSL_0_9_6-stable
  origin/OpenSSL_0_9_7-stable
  origin/OpenSSL_0_9_8-stable
  origin/OpenSSL_0_9_8fg-stable
  origin/OpenSSL_1_0_0-stable
  origin/OpenSSL_1_0_1-stable
  origin/OpenSSL_1_0_2-stable
  origin/OpenSSL_1_1_0-stable
  origin/OpenSSL_1_1_1-stable
```

**Comment by mspncp** [comment]
The naming conventions have changed, the stable branch is called [openssl-3.0](https://github.com/openssl/openssl/tree/openssl-3.0) and the tags are named openssl-3.0.x.

**Comment by rsbeckerca** [comment]
I can see the point of having a stable branch. With a CI/CD system that monitors changes on a git branch, it is easy to automatically kick off builds without having a human modify the build pipeline to point to a tag. The `openssl-3.0` branch, however, is already pointing to the commit beyond the `openssl-3.0.0` tag, so the branch cannot be used. I know, we're officially supposed to use the tarballs, but that doesn't help keep the ongoing testing up-to-date with each change.

**Comment by richsalz** [comment]
So for 3.0 I have to checkout a TAGGED version, whereas in earlier release I could check out a "*_stable" vesion.  Okay. Was this documented somewhere that I missed?

**Comment by levitte** [comment]
The idea of a new naming scheme was introduced by yours truly about 1½ years ago:

https://mta.openssl.org/pipermail/openssl-project/2020-April/001931.html

As for tags and branches:

-  TAGS have *always* been used to mark the actual release.  The latest tag on the 1.1.1 series is [`OpenSSL_1_1_1l`](https://github.com/openssl/openssl/tree/OpenSSL_1_1_1l)
- BRANCHES have *always* been used for the release series, and the head of each branch is *always* the development of the next update release.  So for example, the head of `OpenSSL_1_1_1-stable` is version 1.1.1m-dev (see [`include/openssl/opensslv.h` in that branch](https://github.com/openssl/openssl/blob/2753b6ff7f0b91c7ddeb72a6a08948ca28d12a91/include/openssl/opensslv.h)), which will eventually become 1.1.1m (and the tag `OpenSSL_1_1_1m`) when that update release is done.

So:

- if you want the continued stable branch for 3.0.x (i.e. all the subsequent updates of 3.0), you checkout the BRANCH `openssl-3.0`, just like you checked out the BRANCH `OpenSSL_1_1_1-stable` to get the branch for the 1.1.1 series.
- if you want the exact release, 3.0.0, you checkout the TAG `openssl-3.0.0`, just like you would have checked out the TAG `OpenSSL_1_1_1l` to get that exact release.

Does this clarify things?

**Comment by levitte** [comment]
While we're on the subject, I'm actually *quite* surprised that no one noticed the pre-release tags:

``` console
$ git tag -l
...
openssl-3.0.0-alpha1
openssl-3.0.0-alpha10
openssl-3.0.0-alpha11
openssl-3.0.0-alpha12
openssl-3.0.0-alpha13
openssl-3.0.0-alpha14
openssl-3.0.0-alpha15
openssl-3.0.0-alpha16
openssl-3.0.0-alpha17
openssl-3.0.0-alpha2
openssl-3.0.0-alpha3
openssl-3.0.0-alpha4
openssl-3.0.0-alpha5
openssl-3.0.0-alpha6
openssl-3.0.0-alpha7
openssl-3.0.0-alpha8
openssl-3.0.0-alpha9
openssl-3.0.0-beta1
openssl-3.0.0-beta2
...
```

Compare that to the 1.1.1 pre-releases:

``` console
OpenSSL_1_1_1-pre1
OpenSSL_1_1_1-pre2
OpenSSL_1_1_1-pre3
OpenSSL_1_1_1-pre4
OpenSSL_1_1_1-pre5
OpenSSL_1_1_1-pre6
OpenSSL_1_1_1-pre7
OpenSSL_1_1_1-pre8
OpenSSL_1_1_1-pre9
```

**Comment by richsalz** [comment]
I think putting something in CHANGES would have been very useful.  Anyhow, closing this.
