### ISSUE TITLE
Dead code in apps/cmp.c

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#16585]
In apps/cmp.c line 2009, the condition can never be true
Line 2004 :
    if (len > SECTION_NAME_MAX)
        len = SECTION_NAME_MAX;
Line 2009 : 
    if (len > SECTION_NAME_MAX)
        CMP_warn2("using only first %d characters of section name starting with \"%s\"",
                  SECTION_NAME_MAX, opt_item);

**Comment by FdaSilvaYY** [comment]
Ping @DDvO

**Comment by DDvO** [comment]
Good spotting - the warning should have been given before limiting the value of the `len` variable.
This bug must have been due to a glitch while refactoring the code of the `prev_item()` function.
Fix is in #16586.
