### ISSUE TITLE
SSL routines:tls_process_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by ufo56** [openssl/openssl#16604]
Hi

I'm losing my mind, i have tried to downgrade/upgrade openssl version but on this VM i can't get work file_get_contents function. That exact code works on many other machines with same or newer openssl version. 

https://github.com/google/recaptcha/blob/master/src/ReCaptcha/RequestMethod/Post.php#L80

```
OpenSSL Library Version	OpenSSL 1.1.1d 10 Sep 2019
OpenSSL Header Version	OpenSSL 1.1.1d 10 Sep 2019
Openssl default config	/usr/local/ssl/openssl.cnf
 ```

Other VM with exact openssl version and file_get_contents function works like it should.

**Comment by mattcaswell** [comment]
> certificate verify failed

If this same code works elsewhere this suggests something environmental. Perhaps the certificate trust store is incorrect configured or not being picked up?

**Comment by ufo56** [comment]
> not being picked up?

Unbelievable, i discovered this 10 minutes after this post. OpenSSL was looking certs from wrong place /usr/lib/ssl/certs. I symlinked /etc/ssl/certs to /usr/lib/ssl/certs and it works.
