### ISSUE TITLE
Freeing pointer in CRYPTO_realloc if num == 0 degrades security (makes double-frees possible)

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#1660]
This is a common pattern, both within OpenSSL and in other software:

```c
#include <openssl/crypto.h>
int main(void)
{
    void* q, *p = OPENSSL_malloc(10);
    if ( p == NULL ) {
        goto end;
    }
    q = OPENSSL_realloc(p, 20);
    if ( q == NULL ) {
        goto end;
    }
    p = q;
end:
    OPENSSL_free(p);
    return 0;
}
```

This works as long as the amount of bytes requested to be realloc'ed (here: 20) is positive. However, since this patch: https://github.com/openssl/openssl/commit/bbd86bf5424a611cb6b77a3a17fc522931c4dcb8#diff-0ad35796f3b4040e66893ac4cb4b6b28R172 CRYPTO_realloc will free the pointer if num == 0.

If you replace '20' with '0' in the example, a double-free will occur for current versions of OpenSSL (1.1.0/master) but not for older versions.

I don't believe that OpenSSL currently contains any code where it is possible to realloc zero bytes in any of its internal functions. However, other software sometimes also uses OpenSSL's allocation functions in parts of their code where heap memory is required. This new feature actually introduces a new attack vector since an attacker needs to coerce the application into reallocating zero bytes. This may happen through an array allocation in the form

```c
OPENSSL_realloc(p, n * sizeof(element)); 
```

or through overflows.

With the new feature, this may lead to double-frees where the application will free ```p``` if ```OPENSSL_realloc``` fails (like in my example code) whereas it would operate fine with the old ```OPENSSL_realloc```.

So the new feature is bound to degrade security some place, some time (especially as more and more projects will be linked against OpenSSL 1.1.0), and I think that it's better to leave it out.

**Comment by richsalz** [comment]
I disagree.  I think it is better, and easier to understand, if OPENSSL_realloc semantics were exactly like realloc.

**Comment by guidovranken** [comment]
Ok
