### ISSUE TITLE
How to properly using OSSLEncoder code example?

### ISSUE THREAD

**Issue by trippleflux** [openssl/openssl#16612]
On 1.1.1 we have the following low level function : 
PEM_write_PKCS8PrivateKey
PEM_write_X509
PEM_write_bio_DHparams

But as far I am reading the OpenSSL 3.0.0 docs, now we need to go through OSSLEncoder, the question is how to use it properly?
Need code example in C, current code : 
```
		
	        //OpenSSL 3.0
	        EVP_PKEY_CTX* ctx;
	        EVP_PKEY* PKey = NULL;
		
	        //OSSL Encoder
	        OSSL_ENCODER_CTX* ectx;
	        const char* format = "PEM";
	        const char* structure = "PrivateKeyInfo"; /* PKCS#8 structure */
	        const unsigned char* pass = "my password";
		
		ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, NULL);
		if (!ctx)
		{
			goto error_rsa;
		}
		EVP_PKEY_CTX_set_dh_paramgen_prime_len(ctx, 2048);
		EVP_PKEY_CTX_set_dh_paramgen_subprime_len(ctx, 2048);
		EVP_PKEY_CTX_set_dh_paramgen_generator(ctx, 5);
		EVP_PKEY_CTX_set_cb(ctx, CallBack);
		EVP_PKEY_CTX_set_app_data(ctx, CallBack);

		if (EVP_PKEY_keygen_init(ctx) <= 0)
		{
			goto error_rsa;
		}
		
		if (EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, rsa_bits_strength) <= 0)
		{
			goto error_rsa;
		}

		if (EVP_PKEY_keygen(ctx, &PKey) <= 0)
		{
			goto error_rsa;
		}
		
		FILE* fp;

		fp = fopen("test.pem", "w+");


		ectx = OSSL_ENCODER_CTX_new_for_pkey(ctx,OSSL_KEYMGMT_SELECT_ALL_PARAMETERS,
			format, structure,
			NULL);
		if (ectx == NULL) {
			/* error: no suitable potential encoders found */
		}
		if (pass != NULL)
			OSSL_ENCODER_CTX_set_passphrase(ectx, pass, strlen(pass));
		if (OSSL_ENCODER_to_fp(ectx, fp)) {
			/* crashes in here regarding keymgmt*/
		}
		else {
			/* encoding failure */
		}

		fclose(File);
		File = NULL;

		Putlog(LOG_DEBUG, _T("Finished saving !\r\n"));
		bReturn = TRUE;
```

In code above I am trying to create RSA Private key & DH Params, Certificate files, and dump the private key and certificate files into a file or separated file (*.dhp,*,pem, *.key).

**Comment by kaduk** [comment]
> But as far I am reading the OpenSSL 3.0.0 docs, now we need to go through OSSLEncoder,

Well, not really.  The `PEM_write_*()` APIs still exist in 3.0.0 and work fine; they're just marked as deprecated.  That means they might be removed in some future release, but you have 5+ years in which to transition over to the alternatives.

```
OSSL_ENCODER_CTX_new_for_pkey(ctx,OSSL_KEYMGMT_SELECT_ALL_PARAMETERS,
```
The first argument needs to be the `EVP_PKEY *` you created (i.e., `PKey`), not the `EVP_PKEY_CTX *` that was used to generate the key.

**Comment by slontis** [comment]
If you get stuck you can always look at the apps to see what they do..
e.g: apps/genpkey.

**Comment by mattcaswell** [comment]
> Well, not really. The PEM_write_*() APIs still exist in 3.0.0 and work fine; they're just marked as deprecated.

Actually this isn't quite correct. Not *all* of the PEM functions are deprecated - only certain ones. Of those listed by @trippleflux, the only one that is deprecated is `PEM_write_bio_DHparams`. The other two are not deprecated and there is no problem with using them.

**Comment by levitte** [comment]
> On 1.1.1 we have the following low level function

I might point out that none of those mentioned are what I would call "low level"...  they are PEM application utility functions.
There *are* PEM functions that I would call low level, although I think of them as generic rather than "low level", such as `PEM_read_bio()`
