### ISSUE TITLE
C++ Got 'Forward declaration of X509_req_st' error when access request infor of X509_REQ - openssl

### ISSUE THREAD

**Issue by nguyentan193** [openssl/openssl#16616]
Here my problem:
I create a sample code in Command Line Tool Project (c++) on MacOS 10.15.7, with openssl installed.

I need to create a certificate signing request (CSR or X509_REQ) and sign by the HSM token (epass 2003 usb token, not sign by X509_Sign function)
I found a solution at [here](https://stackoverflow.com/questions/64987043/sign-certificate-request-with-smartcard-private-key-in-pkcs11), and applied to my project, but i got some errors when access to: request->req_info,  request->signature->flags
=== short desc ====
```
#include <openssl/x509.h>
#include <vector>


template<typename T>
using AutoDeletedPtr = std::unique_ptr<T, std::function<void(T*)>>;
void makeCSR2()
{
    auto request = AutoDeletedPtr<X509_REQ>(X509_REQ_new(), X509_REQ_free);
    //-- add detail information to CSR
    
    //-----------------
    //-- get csr info and sign it by HSM token
    unsigned char* buffer { nullptr };
    auto size = i2d_X509_REQ_INFO(&request->req_info, &buffer);
    std::vector<unsigned char> der_encoded_request(buffer, buffer + size);
    //-----------------
    //-- update flags of signature of the csr
    request->signature->flags &= ~(ASN1_STRING_FLAG_BITS_LEFT | 0x07);
    request->signature->flags |= ASN1_STRING_FLAG_BITS_LEFT;
}
```
===================

Error image
![Screen Shot 2021-09-17 at 09 28 45](https://user-images.githubusercontent.com/3622614/133721299-6075debd-47ee-449f-afd4-76b428cbc939.png)

=============

So, please help me to fix the errors and give me some other solutions for the problem: Gen CSR and sign it by HSM - Usb Token (in C++)

Thanks in advance!

**Comment by mattcaswell** [comment]
Use `i2d_re_X509_REQ_tbs()` instead of `i2d_X509_REQ_INFO()`.

**Comment by nguyentan193** [comment]
> Use `i2d_re_X509_REQ_tbs()` instead of `i2d_X509_REQ_INFO()`.

Wow, thank you very much!
I also found the solution just some minutes ago :))

And, can you suggest for me a alternate way to set signature flags, as bellow:
```
request->signature->flags &= ~(ASN1_STRING_FLAG_BITS_LEFT | 0x07);
request->signature->flags |= ASN1_STRING_FLAG_BITS_LEFT;
```

**Comment by mattcaswell** [comment]
Create the `ASN1_BIT_STRING` for the signature, and set the flags as appropriate. Then set the signature via `X509_REQ_set0_signature`.

**Comment by nguyentan193** [comment]
> Create the `ASN1_BIT_STRING` for the signature, and set the flags as appropriate. Then set the signature via `X509_REQ_set0_signature`.

Thanks so much! ;)
