### ISSUE TITLE
just a clarification.

### ISSUE THREAD

**Issue by ihsinme** [openssl/openssl#16613]
good afternoon to me, it is very important to me that nulling sensitive information is very important in openssl.
I may be wrong, but it is more logical to organize this call https://github.com/openssl/openssl/blob/1ed3249f253e4490a813279e2eb253c8e5cfaabb/ssl/t1_enc.c#L553 within the framework of the wrapper functions https://github.com/openssl/openssl/blob/e59bfbaa2dbd680f77e1121e382502bd522a466c/ssl/s3_lib.c#L3343
, or create this zeroing procedure.

thanks for your time.

**Comment by mattcaswell** [comment]
I'm not sure I understand your question. `ssl3_cleanup_key_block()` is called from various places including inside `ssl3_free`:

https://github.com/openssl/openssl/blob/e59bfbaa2dbd680f77e1121e382502bd522a466c/ssl/s3_lib.c#L3343-L3348

**Comment by ihsinme** [comment]
thanks for the answer.
I may well be wrong.
but ```ssl3_free()``` looks like a wrapper, with validation and cleanup.
it seemed to me that this indicates the need for similar behavior in other calls to ```ssl3_cleanup_key_block()```

**Comment by mattcaswell** [comment]
`ssl3_free` is called if the application invokes `SSL_free` and is used to free up "everything". `ssl3_cleanup_key_block()` is only about freeing up the key block data. There are a number of calls to `ssl3_cleanup_key_block()` and, AFAICT, calling `ssl3_free` in those locations (and in particular the location you point out in t1_enc.c) would be doing too much. The call in t1_enc.c is very specifically about the key block. We are about to update the key block with new data, so we need to clean and free any old existing key block data before we do so.

**Comment by ihsinme** [comment]
it is reasonable.
of course your code is tricky for me, so I might not be precise in my statements.
it was important for me to understand whether the presence of a wrapper can be considered a sign of the need for additional checks in all other places.

thanks for your time
