### ISSUE TITLE
status_request extension should not be sent on resumption

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#1662]
It appears OpenSSL servers send the status_request extension on resumption handshakes. While not forbidden in the spec anywhere I see, it doesn't make any sense. There's no way to send a CertificateStatus message on a resumption.

This is particularly odd because the OCSP logic acts on the private key:
https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=ssl/t1_lib.c;h=71c480f4029e1a4587e5f44939398ba959310b4c;hb=HEAD#l2645

But cert_cb has been skipped:
https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=ssl/statem/statem_srvr.c;h=009d06c811a67dfb998d995f4ff4f64adabe7209;hb=HEAD#l1387

So it may even be a little confusing to the API consumer if they act on both callbacks.

**Comment by briansmith** [comment]
> It appears OpenSSL servers send the status_request extension on resumption handshakes. While not forbidden in the spec anywhere I see, it doesn't make any sense.

I think it is OK, if not ideal. The extension just means "I understand the OCSP stapling extension." It doesn't mean that a `CertificateStatus` message will be sent in the handshake (even for a full, non-resumed, handshake).

> There's no way to send a CertificateStatus message on a resumption.

...such clients could never work because of this.

OpenSSL isn't sending a `CertificateStatus` message during resumption, right?

**Comment by davidben** [comment]
It's not sending one during resumption, though it is calling the callback, so I doubt this was a conscious decision. But, yeah, this isn't terrible (otherwise someone would have noticed interop problems by now), but I don't think implementations should do this.

(OpenSSL actually originally wouldn't tolerate CertificateStatus being optional in a full handshake until bb1aaab42880489729aeafea27d3569cce60c20b. I think this was a mistake in the spec since it adds state machine complexity while the decisions get made on the server in the same RTT anyway. But, sadly, some stacks do this so clients have to handle it.)

**Comment by mattcaswell** [comment]
It seems this only applies to 1.1.0 and 1.0.2. We accidentally fixed the behaviour in master a while ago. However see #5896, #5897, #5898.
