### ISSUE TITLE
`./Configure no-alpn`?

### ISSUE THREAD

**Issue by dilyanpalauzov** [openssl/openssl#16625]
I want to create the minimal OCI image, providing LDAP with OpenLDAP.  In the LDAP world NPN and ALPN are not used.  I call `./Configure no-nextprotoneg` to disable NPN.  I want in addition to disable ALPN.

* Add an option to disable ALPN, so that the (static) libraries (libssl and libcrypto) and the binaries (using static libraries) get smaller.

**Comment by dilyanpalauzov** [comment]
I refer to v1.1.1.

**Comment by paulidale** [comment]
I think this unlikely for 1.1.1.  We don't add features to stable branches, so would need to justify the omission of this option as a bug which seems like a stretch.

For master, there would be no problem add such an option.

**Comment by kaduk** [comment]
I note that the IETF is currently revising its guidance to TLS implementations (BCP 195), to make support for ALPN mandatory for TLS implementations: https://www.ietf.org/archive/id/draft-ietf-uta-rfc7525bis-02.html#section-3.8
Accordingly, I'm not sure that "no problem to add such an option" is quite accurate.

**Comment by paulidale** [comment]
That @kaduk, I wasn't aware of that.  That change would certainly make such an option a harder sell.

Possibly not impossible: it will be forever before the standard is updated and never before it is universally adopted :grinning:

**Comment by t8m** [comment]
OTC: We do not see any real need for having no-alpn as a build time configuration option. There is not much to spare by switching it off.
Closing.
