### ISSUE TITLE
openssl-3.0: Cannot construct RSA key using non-deprecated APIs

### ISSUE THREAD

**Issue by stefanberger** [openssl/openssl#16635]
I have been trying to construct an RSA key using OpenSSL 3.0 non-deprecated APIs and I cannot do it.

The function `EVP_PKEY_set_bn_param()` seems particularly useful in this case yet I cannot make it succeed. To 'get past it' I would need to pass the `evp_pkey_is_assigned(pkey)` check, which I don't know how to do without using non-deprecated APIs. And even if I get past it using deprecated APIs (`EVP_PKEY_assign_RSA(RSA_new())`) I would then need to get past the check `evp_pkey_is_provided(pkey)` in `EVP_PKEY_set_params()`, which has `keymgmt` set to `NULL` no matter what.

I also could not find any code in the openssl 3 checkout using the `EVP_PKEY_set_bn_param()` function.

So here's an example code that should be able to make this work, but it exits with code '5', failing when trying to set the exponent.

```
include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/core_names.h>

int main(void)
{
    BIGNUM *exp = BN_new();
    EVP_PKEY *pkey;
    EVP_KEYMGMT *keymgmt;

    if (BN_hex2bn(&exp, "10001") == 0)
        exit(1);
    pkey = EVP_PKEY_new();
    if (!pkey)
        exit(2);
    keymgmt = EVP_KEYMGMT_fetch(NULL, "rsa", NULL);
    if (!keymgmt)
        exit(3);
    if (EVP_PKEY_set_type_by_keymgmt(pkey, keymgmt) != 1)
        exit(4);
    if (EVP_PKEY_set_bn_param(pkey, OSSL_PKEY_PARAM_RSA_E, exp) != 1)
        exit(5);

    printf("success!\n");
    return 0;
}
```

**Comment by mattcaswell** [comment]
> I have been trying to construct an RSA key using OpenSSL 3.0 non-deprecated APIs

You are using the wrong API. Use `EVP_PKEY_fromdata`:

https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_fromdata.html

**Comment by stefanberger** [comment]
Thanks for the quick response. This now gets it to work.

```
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/core_names.h>

int main(void)
{
    BIGNUM *exp = BN_new();
    EVP_PKEY *pkey;
    EVP_KEYMGMT *keymgmt;
    EVP_PKEY_CTX *ctx;

    if (BN_hex2bn(&exp, "10001") == 0)
        exit(1);
    pkey = EVP_PKEY_new();
    if (!pkey)
        exit(2);
    ctx = EVP_PKEY_CTX_new_from_name(NULL, "rsa", NULL);
    if (!ctx)
        exit(3);
    keymgmt = EVP_KEYMGMT_fetch(NULL, "rsa", NULL);
    if (!keymgmt)
        exit(4);
    if (EVP_PKEY_set_type_by_keymgmt(pkey, keymgmt) != 1)
        exit(5);
 
    {
        OSSL_PARAM params[2] = {
            OSSL_PARAM_BN(OSSL_PKEY_PARAM_RSA_E, exp, BN_num_bytes(exp)),
            OSSL_PARAM_END
       };

       if (EVP_PKEY_fromdata_init(ctx) != 1 ||
           EVP_PKEY_fromdata(ctx, &pkey, EVP_PKEY_KEY_PARAMETERS, params) != 1)
           exit(7);
    }

    printf("success!\n");
    return 0;
}
```

**Comment by mattcaswell** [comment]
This part of the code should not be necessary and can be dropped:

````
    keymgmt = EVP_KEYMGMT_fetch(NULL, "rsa", NULL);
    if (!keymgmt)
        exit(4);
    if (EVP_PKEY_set_type_by_keymgmt(pkey, keymgmt) != 1)
        exit(5);
````

**Comment by stefanberger** [comment]
@mattcaswell I am trying this in a bigger context rather than this little program. Problem is now that encryption doesn't work (after setting mod as well). I see that pkey->pkey.rsa is NULL once it has come to 'success' but keydata is set. `EVP_PKEY_encrypt_init()` then ends up failing. Also ctx->pkey is NULL...

**Comment by stefanberger** [comment]
Also ctx->pkey is NULL... which is the reason it ends up failing in `evp_pkey_export_to_provider`. Before one could connect the two via `EVP_PKEY_CTX *EVP_PKEY_CTX_new(EVP_PKEY *pkey, ENGINE *e);` but that doesn't work anymore. Using `ctx = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, NULL))` doesn't work, either. 

I thought `EVP_PKEY_fromdata(ctx, &pkey, EVP_PKEY_KEY_PARAMETERS, params)` would connect the two now but that doesn't seem to be the case.

So, I am looking for some sort of a suitable setter for the ctx but cannot find one.

**Comment by mattcaswell** [comment]
> one could connect the two via EVP_PKEY_CTX *EVP_PKEY_CTX_new(EVP_PKEY *pkey, ENGINE *e); but that doesn't work anymore

In what way does it not work? This is a valid way to associate a pkey with a pkeyctx.

> Using ctx = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, NULL)) doesn't work, either.

Same question. This is the correct way to do this.

**Comment by stefanberger** [comment]
> In what way does it not work? This is a valid way to associate a pkey with a pkeyctx.

I thought I would only need one context, but this is not correct, instead I need one for key creation and one for key usage. So I had tried to use these context creation functions instead of `ctx = EVP_PKEY_CTX_new_from_name(NULL, "rsa", NULL);`, which of course didn't work with an uninitialized key.
