### ISSUE TITLE
https://wiki.openssl.org/index.php/OpenSSL_3.0 needs update

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#16633]
It still says: 

OpenSSL 3.0 is the next release of OpenSSL that is currently in development. This page is intended as a collection of notes for people downloading the alpha/beta releases or who are planning to upgrade from a previous version of OpenSSL to 3.0.

**Comment by mattcaswell** [comment]
Fixed. I edited the page to remove the out-of-date text at the beginning, and replaced it with some text to say that page is no longer being maintained ad added a link to the migration guide instead.
