### ISSUE TITLE
s_client CONNECT/proxy issue with case sensitivity

### ISSUE THREAD

**Issue by godly** [openssl/openssl#1663]
According to https://www.ietf.org/rfc/rfc2817.txt any "successful (2xx) response to a CONNECT request indicates that the proxy has established a connection to the requested host and port, and has switched to tunneling the current connection to that server connection."
The current code checks for "200" and "established" in lower case. Connections to proxy servers which send "HTTP/1.1 200 Connection Established" (upper case E) fail with 's_client: HTTP CONNECT failed'.

Keeping the current code a simple fix would replace strstr(..) with strcasestr(mbuf, "established") != NULL) in https://github.com/openssl/openssl/blob/master/apps/s_client.c#L2014 . It would still not conform to the RFC but allow the usage of more proxy servers. For me this works fine and as I do not code C I'll live with this fix.
Anyhow as there is a RFC one could also rewrite the code to do an RFC compliant check.

**Comment by levitte** [comment]
Have a look at #1664, I think it fixes everything you're talking about in one go.

**Comment by mattcaswell** [comment]
Linked PR was merged so closing this.
