### ISSUE TITLE
File encrypted on x86 linux cannot be decrypted on M1 Mac

### ISSUE THREAD

**Issue by TheKinrar** [openssl/openssl#16649]
Hi!

Encrypting a file on ArchLinux x86:
`openssl enc -aes-256-cfb -in file.txt -out file.txt.enc -k "enc_key"`

Then decrypting on a Mac M1:
`openssl enc -d -aes-256-cfb -in file.txt.enc -out file.txt -k "enc_key"`

Results in garbled output in file.txt on the M1 side. Tried using base64. Encrypting then decrypting on the same machine works as intended.

**Comment by t8m** [comment]
Which openssl version(s) are they?

**Comment by t8m** [comment]
Closing for no response.
