### ISSUE TITLE
Selftest 90-test_sslapi.t fails for KTLS CHACHA tests in fips configuration

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16657]
Selftest 90-test_sslapi.t fails for KTLS CHACHA tests in fips configuration

The command line 
```
../../util/wrap.pl ../../test/sslapitest ../../test/certs ../../test/recipes/90-test_sslapi_data/passwd.txt /tmp/apiI5KldIs fips ../../test/fips-and-base.cnf => 1
```
provides a lot of debug output when OPENSSL_KTLS_CHACHA20_POLY1305 is enabled
E.g

```
        # ERROR: (bool) 'SSL_CTX_set_cipher_list(cctx, cipher) == true' failed @ test/sslapitest.c:1307
        # false
        # 007C4FCB527F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl/ssl_lib.c:2729:
        # OPENSSL_TEST_RAND_ORDER=1632295916
        not ok 36 - iteration 4
```
It's predictable because FIPS provider doesn't implement CHACHA/POLY.

Commenting out the subtests under `#ifdef OPENSSL_KTLS_CHACHA20_POLY1305` does the trick. I suspect we don't have such machines (with Linux kernel 5.11+) in our CI...

**Comment by mattcaswell** [comment]
We probably don't do "enable-ktls" in conjunction with "enable-fips". There's lots of option combinations that we don't test because there are too many of them.

**Comment by beldmit** [comment]
In fact we do it in CI target `enable_non-default_options`.

Not sure if we really test a fresh enough kernel, BTW.
