### ISSUE TITLE
There's no hint on which key is used to PGP sign the tarballs

### ISSUE THREAD

**Issue by sledgehammer999** [openssl/openssl#1665]
I can't seem to find any reference to which PGP key is used to sign the tarballs on the site, even though you offer signature files for the tarballs.

**Comment by mattcaswell** [comment]
Details of the keys for all the dev team members are here:
https://www.openssl.org/community/team.html

**Comment by sledgehammer999** [comment]
The download page should have a direct reference to the key. It is difficult to imagine to search in the page you linked.
Moreover, is the signing done by a specific member or should I import the keys of all members?

**Comment by mattcaswell** [comment]
> The download page should have a direct reference to the key. It is difficult to imagine to search in the page you linked.

Good point. I added a link. It will take a little while to show up.

> Moreover, is the signing done by a specific member or should I import the keys of all members?

Current team members that sign releases include myself (Matt Caswell), Richard Levitte and Stephen Henson.
