### ISSUE TITLE
Does aix6.1 support openssl1.1.1g?

### ISSUE THREAD

**Issue by tengliu0929** [openssl/openssl#16653]
I had tried to compile openssl1.1.1g on an aix6.1, but it reported unkown type 'rid_t' in unistd.h file,  Could any one tell me that can I compile openssl1.1.1g on aix6.1? I am confused for this problem for a long time

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
