### ISSUE TITLE
SSL_CTX_use_certificate failing with OpenSSL 3.0.0

### ISSUE THREAD

**Issue by maheshkumar01** [openssl/openssl#16650]
We have below code that used to work with OpenSSL 1.1.1. But fails with OpenSSL 3.0.0. I'm making sure that I'm loading legacy.dll (on Windows)

```
int nid_key = NID_pbe_WithSHA1And3_Key_TripleDES_CBC;
int nid_cert = NID_pbe_WithSHA1And40BitRC2_CBC;
char *cipher = "AESGCM+kEECDH:!aNULL:!eNULL:!ECDSA:AES256-SHA:AES128-SHA";
...
...

X509 *cert_;
//Initialized here to store cert 
void InitCert(X509 *cert) {
    if (cert_ != NULL) {
        X509_free(cert_);
    }
  
    cert_ = cert;
}

...
...
...

void SSLProc() {
    SSL_CTX *ctx = SSL_CTX_new(TLS_method());

    if (SSL_CTX_set_max_proto_version(ctx, TLS1_2_VERSION) != 1) {
        return -1;
    }

    if (SSL_CTX_set_min_proto_version(ctx, TLS1_1_VERSION) != 1) {
        return -1;
    }

    if(SSL_CTX_use_certificate(ctx, cert_) != 1) {
        //------> Fails here
        return -1;
    }
}
```

The code fails when it calls "SSL_CTX_use_certificate" (returns 0). Any idea what I may be missing here?

**Comment by mattcaswell** [comment]
It might be useful to dump the OpenSSL error stack to see if that gives any clues (e.g. via `ERR_print_errors_fp`).

**Comment by t8m** [comment]
Also given legacy algorithms are obviously used here you need to load the legacy provider either by configuring it in the configuration file or by explicitly loading both default and legacy providers by `OSSL_PROVIDER_load()`.

**Comment by maheshkumar01** [comment]
> It might be useful to dump the OpenSSL error stack to see if that gives any clues (e.g. via `ERR_print_errors_fp`).

Output from "ERR_print_errors_fp"
```60150000:error:0A00018E:SSL routines:SSL_CTX_use_certificate:ca md too weak:ssl\ssl_rsa.c:221: ```

**Comment by slontis** [comment]
(CHANGES.md has this entry) X509 certificates signed using SHA1 are no longer allowed at security level 1 and above.

**Comment by mattcaswell** [comment]
As noted by @slontis, you almost certainly have a certificate in the chain signed using SHA1 which is no longer considered sufficiently secure. You should update your chain/certificate as required to avoid this.

You *can* reduce the security level in OpenSSL to avoid this error - but you should consider this a temporary workaround to the real fix (which is to fix the cert/chain). To reduce the security level (to 0), call `SSL_CTX_set_security_level`:

````
SSL_CTX_set_security_level(ctx, 0);
````

**Comment by maheshkumar01** [comment]
Thanks @mattcaswell @slontis. Closing this issue.
