### ISSUE TITLE
EVP_PKEY_free crash

### ISSUE THREAD

**Issue by wanhl123** [openssl/openssl#16663]
I use openssl-1.0.1r.

There is a crash when i call curl_multi_perform(s_curl_m, &stillRunning) 

09-16 18:13:52.180 4094 4094 F DEBUG : Build fingerprint: 'TCL/G03_8K_GB/BeyondTV4:11/RP1A.200622.001/AR05:userdebug/release-keys'
09-16 18:13:52.180 4094 4094 F DEBUG : Revision: '0'
09-16 18:13:52.181 4094 4094 F DEBUG : ABI: 'arm'
09-16 18:13:52.182 4094 4094 F DEBUG : Timestamp: 2021-09-16 18:13:52+0000
09-16 18:13:52.182 4094 4094 F DEBUG : pid: 366, tid: 2233, name: mds_xml_endpoin >>> /vendor/tvos/bin/sitatvservice <<<
09-16 18:13:52.182 4094 4094 F DEBUG : uid: 0
09-16 18:13:52.182 4094 4094 F DEBUG : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xada5a898
09-16 18:13:52.182 4094 4094 F DEBUG : r0 9e5f7f10 r1 00000000 r2 9e5f7f18 r3 ada5a898
09-16 18:13:52.183 4094 4094 F DEBUG : r4 9e5f7f10 r5 9e340abc r6 00000000 r7 10787e9c
09-16 18:13:52.183 4094 4094 F DEBUG : r8 1023508c r9 00000002 r10 10787e9c r11 ad000630
09-16 18:13:52.183 4094 4094 F DEBUG : ip 10790b70 sp aa52c8c0 lr 101b2bc8 pc ada5a898
09-16 18:13:52.760 4094 4094 F DEBUG : backtrace:
09-16 18:13:52.760 4094 4094 F DEBUG : #00 pc 0049a898 [anon:scudo:primary]
09-16 18:13:52.760 4094 4094 F DEBUG : #01 pc 00d27bc4 /vendor/tvos/bin/sitatvservice (EVP_PKEY_free+80)

**Comment by paulidale** [comment]
The trace as given isn't helpful.  Could you use a debug build of OpenSSL and get a full stack trace.

Better would be building an address sanitizer version of OpenSSL or using valgrind to locate where the problem is coming from -- it's usually, but by no means always, an application problem that causes this kind of crash in OpenSSL.
