### ISSUE TITLE
OBJ_sn2nid() doesn't like newer names like "SHA2-256" ?

### ISSUE THREAD

**Issue by selvanair** [openssl/openssl#16662]
```
const char *mdname = "SHA2-256";
nid = OBJ_sn2nid(mdname);

if(nid == NID_undef) {
    printf("Error: invalid digest name '%s'\n", mdname);
}
```
fails to find the NID (gets `NID_undef`). Using  "SHA256" as the name is okay.

At the same time, `EVP_MD_get0_name(md)` returns "SHA2-256" for a matching EVP_MD. It would be nice if `OBJ_sn2nid` is updated to take with newer (preferred?) names as well.

**Comment by paulidale** [comment]
If we register all the new names, how would we deal with new algorithms that do not have a NID allocated?

The project is moving away from NIDs towards names.  You can no longer assume that anything has a NID.  Existing NIDs and helper functions like this will remain for compatibility reasons.

**Comment by selvanair** [comment]
Names are fine, but then we would need OBJ_sn2obj which doesn't seem to exist, or does it? What I'm trying to do is to get an OBJ from an mdname received from OpenSSL, and thought I have to go through OBJ_sn2nid for that.

**Comment by slontis** [comment]
The question would then be what do you need the object for..
This name is only for use by providers i.e via the EVP_MD_fetch()..

You could do the following (not sure its a good idea).
````
nid = OBJ_sn2nid(mdname);
if(nid == NID_undef) {
    EVP_MD *md = EVP_MD_fetch(NULL,  mdname, NULL);
    nid = EVP_MD_get_type(md);
    EVP_MD_free(md);
} 
````

**Comment by selvanair** [comment]
I only expect a few kinds of digests, so I made an array and will leave it at that. But good that you ask what this is for. This is for interfacing with external non-exportable keys using a provider.

With both EVP_PKEY and provider interfaces, we get the digest to sign (or data to digest and sign), which in case of PKCS1 is not encoded with DigestInfo header. But PKCS11 specs want CKM_RSA_PKCS requests to be made with encoded digest. Now, OpenSSL does not expose the so called encode_pkcs1() function, and I'm left to build it myself. That's where I use it. Probably there is a better way but my ASN1 packing foo is limited. Its all working now, but some of these quirks caught me off-guard.
