### ISSUE TITLE
undefined reference to `MD5_Init'

### ISSUE THREAD

**Issue by marller2013** [openssl/openssl#16677]
I compiled openssl-1.1.1l according with NOTES.ANDROID,and it compiled successfully.But when I invoked api method it happened building error,I had tried on openssl-1.1.1k,it works no error :

OS version: macOS 11.5.2
NDK version: 21.4.7075529
Android Api = 30

***************************************************************************************************************************

My shell script:

#!/bin/bash
export ANDROID_NDK_HOME=mdt/android-sdk/ndk/21.4.7075529
       PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH
./Configure no-test android-arm64 -D__ANDROID_API__=30
make

***************************************************************************************************************************

My building log:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCMakeDebug'.
> Build command failed.
  Error while executing process mdt/android-sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /teddy/TeddyService/app/.cxx/Debug/371l5t16/arm64-v8a Teddy}
  ninja: Entering directory /teddy/TeddyService/app/.cxx/Debug/371l5t16/arm64-v8a'
  [1/12] Building CXX object CMakeFiles/Teddy.dir/teddy_signal.cc.o
  [2/12] Building CXX object CMakeFiles/Teddy.dir/jniglobal.cpp.o
  [3/12] Building CXX object CMakeFiles/Teddy.dir/alarm.cc.o
  [4/12] Building CXX object CMakeFiles/Teddy.dir/dispatch_queue.cc.o
  [5/12] Building CXX object jsoncpp/CMakeFiles/jsoncpp.dir/json_writer.cpp.o
  [6/12] Building CXX object CMakeFiles/Teddy.dir/teddy.cpp.o
  [7/12] Building CXX object jsoncpp/CMakeFiles/jsoncpp.dir/json_value.cpp.o
  [8/12] Building CXX object jsoncpp/CMakeFiles/jsoncpp.dir/json_reader.cpp.o
  [9/12] Linking CXX static library/teddy/TeddyService/app/src/main/cpp/jsoncpp/libs/libjsoncpp.a
  [10/12] Building CXX object CMakeFiles/Teddy.dir/TeddyService.cpp.o
  [11/12] Building CXX object CMakeFiles/Teddy.dir/httplib.cc.o
  [12/12] Linking CXX shared library /teddy/TeddyService/app/build/intermediates/cxx/Debug/371l5t16/obj/arm64-v8a/libTeddy.so
  FAILED: /teddy/TeddyService/app/build/intermediates/cxx/Debug/371l5t16/obj/arm64-v8a/libTeddy.so 
  : && /mdt/android-sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/mdt/android-sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/mdt/android-sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libTeddy.so -o /teddy/TeddyService/app/build/intermediates/cxx/Debug/371l5t16/obj/arm64-v8a/libTeddy.so CMakeFiles/Teddy.dir/alarm.cc.o CMakeFiles/Teddy.dir/dispatch_queue.cc.o CMakeFiles/Teddy.dir/httplib.cc.o CMakeFiles/Teddy.dir/teddy_signal.cc.o CMakeFiles/Teddy.dir/TeddyService.cpp.o CMakeFiles/Teddy.dir/jniglobal.cpp.o CMakeFiles/Teddy.dir/teddy.cpp.o -L/teddy/TeddyService/app/src/main/cpp/openssl/libs/android/arm64-v8a -Wl,-Bstatic -lcrypto -lssl /teddy/TeddyService/app/src/main/cpp/jsoncpp/libs/libjsoncpp.a -Wl,-Bdynamic -llog -latomic -lm && :
  CMakeFiles/Teddy.dir/TeddyService.cpp.o: In function `TeddyService::convert2MD5Str(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) const':
  /teddy/TeddyService/app/src/main/cpp/TeddyService.cpp:118: undefined reference to `MD5_Init'
 /teddy/TeddyService/app/src/main/cpp/TeddyService.cpp:119: undefined reference to `MD5_Update'
 /teddy/TeddyService/app/src/main/cpp/TeddyService.cpp:120: undefined reference to `MD5_Final'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by paulidale** [comment]
Are you sure you are building against the 1.1.1 source code?  The function in question was public then and freely callable.

OpenSSL 3.0 has deprecated this call but it ought to still work.

**Comment by marller2013** [comment]
Yes,I built against the 1.1.1l, and the building script depending on the NOTES.ANDROID

**Comment by marller2013** [comment]
I had fixed this error with exporting "CC=clang"

**Comment by levitte** [comment]
Small point: `-lcrypto - lssl` should be `-lssl - lcrypto`
