### ISSUE TITLE
Trouble installing Ruby on Mac OS Big Sur by using Chruby and ruby-install

### ISSUE THREAD

**Issue by vnguyen1982** [openssl/openssl#16679]
I am trying to install another version of ruby on my Mac. (Already installed 2.6.3 before). By using Chruby and ruby-install

I got this error: 

```
<scratch space>:108:1: note: expanded from here
RSA_set0_crt_params
^
/usr/local/opt/openssl@3/include/openssl/rsa.h:209:1: note: 'RSA_set0_crt_params' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int RSA_set0_crt_params(RSA *r,
^
/usr/local/opt/openssl@3/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/local/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
ossl_pkey_rsa.c:942:5: error: use of undeclared identifier 'RSA_SSLV23_PADDING'
    DefRSAConst(SSLV23_PADDING);
    ^
ossl_pkey_rsa.c:877:58: note: expanded from macro 'DefRSAConst'
#define DefRSAConst(x) rb_define_const(cRSA, #x, INT2NUM(RSA_##x))
                                                         ^
<scratch space>:144:1: note: expanded from here
RSA_SSLV23_PADDING
^
115 warnings and 1 error generated.
make[2]: *** [ossl_pkey_rsa.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make: *** [build-ext] Error 2
!!! Compiling ruby 2.7.4 failed!
```

Anyone can help me about this? I tried with version 2.7.4 or 3.0.2 still the same error.

Thanks all for your helps!!!

**Comment by xtkoba** [comment]
OpenSSL for Ruby does not support OpenSSL 3.0 yet. See https://github.com/ruby/openssl/pull/399.

**Comment by vnguyen1982** [comment]
> OpenSSL for Ruby does not support OpenSSL 3.0 yet. See [ruby/openssl#399](https://github.com/ruby/openssl/pull/399).

So how can I fix it? I'm trying remove OpenSSL 3 and install OpenSSL 1, but when I do `ruby-install ruby 3.0.2` , it install automatically OpenSSl 3 and this bug occur.

**Comment by xtkoba** [comment]
I am sorry that I am not familiar with the `ruby-install` command. Maybe the installation recipe needs to specify explicit dependency on `openssl@1.1`?

**Comment by vnguyen1982** [comment]
I am already install OpenSSL 1.1 by this: `brew install openssl@1.1` (Sure that remove all versions of OpenSSL before install)

But when install ruby version, it automatically install OpenSSL 3. It's not happen before because I already install ruby 2.6.3 in my local

**Comment by xtkoba** [comment]
I hear that now `@3` is the default for brew `openssl`. Thus it is natural that `openssl@3` is installed as a dependency when the version is not specified in the installation recipe.

Anyway, I believe this to be an issue of the package manager and not of OpenSSL itself.

**Comment by levitte** [comment]
Hey @vnguyen1982, this project doesn't do Ruby.  You might want to talk with https://github.com/ruby/openssl

**Comment by xtkoba** [comment]
I suppose you may rather want to contact https://github.com/Homebrew/homebrew-core.

**Comment by slontis** [comment]
Closing this..
