### ISSUE TITLE
Convert a hex string to BIGNUM with BN_hex2bn() then convert it back with BN_bn2hex() will get extra leading zero

### ISSUE THREAD

**Issue by aqer** [openssl/openssl#16672]
My OpenSSL is 1.1.1 and 3.0.0 have the same problem

I found that when I convert a password hex string to BIGNUM format with BN_hex2bn(),
then covert it back with BN_bn2hex(), the password hex string will get extra leading zero.

This problem only occurs when the length of input hex string is odd number.

**Because the input string is used as password,
the extra leading zero will cause decryption failed later.**

I saw another post https://github.com/openssl/openssl/issues/12415 say its not a bug,
But the comment in code https://github.com/openssl/openssl/blob/5402f96aba9dd3d0b3006b8b2651bd27d3cbf326/crypto/bn/bn_print.c#L38 describe to "strip leading zeros", so I think it was a bug.

Below is my test code and test results:
```
#include <stdio.h>
#include <string.h>
#include "/usr/include/openssl/bn.h"

int main(int argc, char* argv[])
{
    BIGNUM *q;
    const char *inputPW;
    char *outPW;

    inputPW = argv[1];
    q = BN_new();

    printf("BN_hex2bn inputPW=%s, len=%ld\r\n",inputPW, strlen(inputPW));
    BN_hex2bn(&q, inputPW);
    outPW = BN_bn2hex(q);
    printf("BN_bn2hex outPW  =%s, len=%ld\r\n",outPW, strlen(outPW));

    OPENSSL_free(outPW);
    BN_free(q);

    return 0;
}
```

```
server:~$ ./test AB88D967E866DDC1B3EF
BN_hex2bn inputPW=AB88D967E866DDC1B3EF, len=20
BN_bn2hex outPW  =AB88D967E866DDC1B3EF, len=20
server:~$ ./test AB88D967E866DDC1B3E
BN_hex2bn inputPW=AB88D967E866DDC1B3E, len=19
BN_bn2hex outPW  =0AB88D967E866DDC1B3E, len=20
server:~$ ./test AB88D967E866DDC1B3
BN_hex2bn inputPW=AB88D967E866DDC1B3, len=18
BN_bn2hex outPW  =AB88D967E866DDC1B3, len=18
server:~$ ./test AB88D967E866DDC1B
BN_hex2bn inputPW=AB88D967E866DDC1B, len=17
BN_bn2hex outPW  =0AB88D967E866DDC1B, len=18
```

**Comment by levitte** [comment]
The bignum is treated as an array of 8-bit bytes in `BN_bn2hex()`.  The comment that you saw is to be understood in terms of bytes, i.e. it will skip over leading bytes with the value zero.  However, a byte is two hex digits, so (taken from your example) `0A` isn't zero, and is therefore written that way.

That being said, why do you convert a password to BIGNUM?  It should probably be used as is, even if it's hexadecimal characters...  *or*, if the hex digits are supposed to be hex encodings, you'd better get out the actual bytes back, i.e. convert the bignum to a binary string, using `BN_bn2bin`.
