### ISSUE TITLE
OpenSSL master (and 3.0 branch) won't build on MacOS 10.11 (El Capitan)

### ISSUE THREAD

**Issue by lprimak** [openssl/openssl#16670]
Trying to compile 3.0.0 via Homebrew on MacOS 10.11 fails.

```
==> perl ./Configure --prefix=/usr/local/Cellar/openssl@3/3.0.0 --openssldir=/us
==> make
lang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/etc/openssl@3\"" -DENGINESDIR="\"/usr/local/Cellar/openssl@3/3.0.0/lib/engines-3\"" -DMODULESDIR="\"/usr/local/Cellar/openssl@3/3.0.0/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -c -o crypto/bn/liblegacy-lib-rsaz-x86_64.o crypto/bn/rsaz-x86_64.s
crypto/bn/rsaz-avx512.s:36:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpxord %ymm0,%ymm0,%ymm0
 ^
crypto/bn/rsaz-avx512.s:37:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqa64 %ymm0,%ymm1
 ^
crypto/bn/rsaz-avx512.s:38:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqa64 %ymm0,%ymm16
 ^
crypto/bn/rsaz-avx512.s:39:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqa64 %ymm0,%ymm17
 ^
crypto/bn/rsaz-avx512.s:40:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqa64 %ymm0,%ymm18
 ^
crypto/bn/rsaz-avx512.s:41:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqa64 %ymm0,%ymm19
 ^
crypto/bn/rsaz-avx512.s:55:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpbroadcastq %r13,%ymm3
 ^
crypto/bn/rsaz-avx512.s:66:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpbroadcastq %r13,%ymm4
 ^
crypto/bn/rsaz-avx512.s:76:2: error: invalid instruction mnemonic 'vpmadd52luq'
 vpmadd52luq 0(%rsi),%ymm3,%ymm1
 ^~~~~~~~~~~
crypto/bn/rsaz-avx512.s:77:2: error: invalid instruction mnemonic 'vpmadd52luq'
 vpmadd52luq 32(%rsi),%ymm3,%ymm16
 ^~~~~~~~~~~
crypto/bn/rsaz-avx512.s:78:2: error: invalid instruction mnemonic 'vpmadd52luq'
 vpmadd52luq 64(%rsi),%ymm3,%ymm17
 ^~~~~~~~~~~
crypto/bn/rsaz-avx512.s:79:2: error: invalid instruction mnemonic 'vpmadd52luq'
 vpmadd52luq 96(%rsi),%ymm3,%ymm18
 ^~~~~~~~~~~
crypto/bn/rsaz-avx512.s:80:2: error: invalid instruction mnemonic 'vpmadd52luq'
....
clang  -I. -Icrypto -Iinclude -Iproviders/implementations/include -Iproviders/common/include  -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -D
OPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/etc/open
ssl@3\"" -DENGINESDIR="\"/usr/local/Cellar/openssl@3/3.0.0/lib/engines-3\"" -DMODULESDIR="\"/usr/local/Cellar/openssl@3/3.0.0/lib/ossl-modules\"" -D_R
EENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF crypto/bn/liblegacy-lib-rsaz_exp.d.tmp -MT crypto/bn/liblegacy-lib-rsaz_exp.o -c -o crypto/bn/l
iblegacy-lib-rsaz_exp.o crypto/bn/rsaz_exp.c
crypto/bn/rsaz-avx512.s:676:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpandq %ymm4,%ymm1,%ymm1
 ^
crypto/bn/rsaz-avx512.s:677:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpandq %ymm4,%ymm16,%ymm16
 ^
crypto/bn/rsaz-avx512.s:678:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpandq %ymm4,%ymm17,%ymm17
 ^
crypto/bn/rsaz-avx512.s:679:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpandq %ymm4,%ymm18,%ymm18
 ^
crypto/bn/rsaz-avx512.s:680:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpandq %ymm4,%ymm19,%ymm19
 ^
crypto/bn/rsaz-avx512.s:682:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpbroadcastq %r15,%ymm3
 ^
crypto/bn/rsaz-avx512.s:687:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpsrlq $52,%ymm2,%ymm24
 ^
crypto/bn/rsaz-avx512.s:688:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpsrlq $52,%ymm20,%ymm25
 ^
crypto/bn/rsaz-avx512.s:689:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vpsrlq $52,%ymm21,%ymm26
 ^
```

**Comment by dskern-github** [comment]
Have you tried switching to a newer version of Xcode?  I needed to switch from using Xcode 9 to Xcode 10 for `AVX-512` errors at some point between alpha 9 and beta 1.  Xcode 9 worked with alpha 9; beta 1 failed to compile with Xcode 9 but worked with Xcode 10.

Similarly, on W64 I needed to upgrade nasm from 2.15.02 to 2.15.05 due to compile-time errors in `rsaz-avx512.asm` in order to build beta 1. 

Sadly, my notes don't specify exactly where between alpha 9 and beta 1 that change was introduced.

**Comment by lprimak** [comment]
@dskern-github unfortunately newer Xcode isn’t available on El Capitan.

**Comment by dmacks** [comment]
Looks like the same failure on my 10.13 (High Sierra) with Xcode 10, the highest available for this OS X.

**Comment by dskern-github** [comment]
On 10.14 (Mojave) it builds fine with Xcode 10, but not with Xcode 9.  So it's not **just** the OS, or **just** the compiler version...

**Comment by paulidale** [comment]
What conditional can be used to distinguish the two?

We much prefer assembly code that run-time detects processor features and that works across OS/compiler/CPU versions but there are always exceptions.

**Comment by lprimak** [comment]
@paulidale Is there a `#define` flag already that can turn this on / off and compile? Homebrew can be patched to turn it on, so there would be no need to detect it. However, if there isn't one, it would need to be added

Otherwise `_IPHONE_OS_VERSION_MAX_ALLOWED >= XXX` or `__MAC_OS_X_VERSION_MAX_ALLOWED >= XXX` can be used. I would just disable the advanced features on older versions of MacOS

**Comment by Bo98** [comment]
> On 10.14 (Mojave) it builds fine with Xcode 10, but not with Xcode 9. So it's not **just** the OS, or **just** the compiler version...

Can you clarify which Xcode 10 version? Because there's a big difference between Xcode 10.1 (the latest High Sierra can run) and Xcode 10.3.

**Comment by Bo98** [comment]
> What conditional can be used to distinguish the two?
> 
> We much prefer assembly code that run-time detects processor features and that works across OS/compiler/CPU versions but there are always exceptions

If the answer to my previous question is how I suspect, the fix I believe would be to adjust this conditional:

https://github.com/openssl/openssl/blob/52f7e44ec88a4d803dc9783cd7c71f87014ae3ee/crypto/bn/asm/rsaz-avx512.pl#L51-L53

Apple's Clang uses a different versioning scheme. Clang 7 is equivalent to Apple Clang 10.0.1 (not 10.0.0 which is Clang 6.0.1). Apple Clang 10.0.1 is first used in Xcode 10.2.

If it's CLA trivial then I can potentially open a PR, otherwise I hopefully what I've suggested makes sense.

**Comment by dskern-github** [comment]
@Bo98 I have Xcode 9.3, 9.4.1, 10.3, and 11.3.1 on my macOS 10.14.6 (Mojave) system. I've tested building OpenSSL 3.0.0 with Xcode 9.3 (fail) and Xcode 10.3 (success). I have not tested with 9.4.1 or 11.3.1, but could do so if it would provide useful information.

**Comment by lprimak** [comment]
@Bo98 I have confirmed that it builds on MacOS El Capitan with the above changes (I just set it to false)
All tests pass

**Comment by lprimak** [comment]
I guess now to figure out how to change the conditional so it works in all cases.
Any ideas?
I am not that familiar with Xcode or perl :(

**Comment by crazyi** [comment]
> @Bo98 I have confirmed that it builds on MacOS El Capitan with the above changes (I just set `$avx512ifma` to false) All tests pass

@lprimak Can you show me how to set `$avx512ifma` to false? I met the same issue as you.

**Comment by lprimak** [comment]
No longer have the hardware

**Comment by mikewcaldwell** [comment]
Did this change ever make it into release?

I ran into this issue yesterday when I was trying to install ruby on my computer running 10.13. I'm unable to upgrade macos as my computer is too old, so here's what I had to do to get openssl 3.0 compiling:

$ brew fetch openssl
This gives you a file path, use that in the next command to unzip the files:
$ cd ~/Library/Caches/Homebrew/downloads/
$ tar xvf 2bd005bb37d33fcc49b50e48959a45801d2e989cb693e93a9528df0e5e8ed950--openssl-3.0.5.tar.gz

Open the file in your editor of choice and update line 52 in the if statement from:
$ vim openssl3.0/crypto/bn/asm/rsaz-avx512.pl 

https://github.com/openssl/openssl/blob/52f7e44ec88a4d803dc9783cd7c71f87014ae3ee/crypto/bn/asm/rsaz-avx512.pl#L51-L53

To:
 ```
if (!$avx512 && `$ENV{CC} -v 2>&1` =~ /((?:clang|LLVM) version|.*based on LLVM) ([0-9]+\.[0-9]+)/) { 
     $avx512ifma = 0; 
 }
```

Zip everything up, replacing the old tar file:
$tar cvf 2bd005bb37d33fcc49b50e48959a45801d2e989cb693e93a9528df0e5e8ed950--openssl-3.0.5.tar.gz openssl3.0/

Try to do:
$brew install openssl

This will give you a sha256 hash mismatch error. Copy the new hash value, and update by doing:
$brew edit openssl

Update line 6 with the new hash:
sha256 "new hash here"

Then install, making sure we don't auto update (which will rewrite the previous hash change):
$ HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl

That should work! If, like me, you were installing ruby, run this command:
$ export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"

Now you should be able to run the following no problem!
$rbdev install 3.1.2

**Comment by levitte** [comment]
Hmmm.  @mikewcaldwell, what's the output of `cc -v` on your machine?

**Comment by mikewcaldwell** [comment]
> Hmmm. @mikewcaldwell, what's the output of `cc -v` on your machine?

Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by levitte** [comment]
So it looks like the condition `$2>=7.0` isn't quite right (`$2` contains the major.minor version, i.e. `10.0` in your case).

**Comment by levitte** [comment]
Ah, I see in discussions higher up that someone came to the same conclusion...  however, no one made a PR to change it, and this was closed later, so forgotten.  Should this be re-opened?

**Comment by levitte** [comment]
I'm re-opening this one, 'cause there does seem to be a way to fix this.

**Comment by levitte** [comment]
I did a bit of research, and came up with a possible fix, see #19352.

Please help me test that change, as I don't have older hardware to test on myself.

**Comment by levitte** [comment]
With #19361 also merged, this issue is done with.  Closing.

**Comment by mattcaswell** [comment]
#19361 isn't merged yet after all...
