### ISSUE TITLE
I found that SHA256 can be written 30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00 04 20 and 30 2F 30 0b 06 09 60 86 48 01 65 03 04 02 01

### ISSUE THREAD

**Issue by kongleiqiang** [openssl/openssl#16683]
I found that SHA256 can be written 30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00 04 20 or 30 2F 30 0b 06 09 60 86 48 01 65 03 04 02 01

If the signature data is 30 2F 30 0B 06 09 60 86 48 01 65 03 04 02 01, ossl_rsa_verify   returns false
![图片](https://user-images.githubusercontent.com/17700935/134798456-502a8d4a-6f46-4d23-ad8b-e7d256f6adf8.png)

Does OpenSSL not support this?

The signature summary data is shown below：
308006092A864886F70D010702A0803080020101310F300D06096086480165030402010500308006092A864886F70D0107010000A080308207E6308205CEA003020102021300A5B201706C83F2C52960D9A270B5E315D216300D06092A864886F70D01010B0500306F3119301706035504610C10564154504C2D39353132333532333739310B300906035504061302504C311C301A060355040A0C134575726F436572742053702E207A206F2E6F2E3127302506035504030C1E43656E7472756D204B77616C6966696B6F77616E65204575726F43657274301E170D3231303231373039333731325A170D3234303231373039333731325A30819B312A3028060355040A0C214B616E63656C61726961205072657A6573612052616479204D696E697374726F773145304306035504030C3C4D696E697374657220646F20737072617720696E666F726D6174797A61636A69202D20706965637A656320706F6470697375207A617566616E65676F3119301706035504610C10564154504C2D35323631363435303030310B300906035504060C02504C30820122300D06092A864886F70D01010105000382010F003082010A0282010100BDC2C6D376D0806CCECC71FCF42B7B64083A164C21D89BF28E21AB1905621BCA9AD7C27123DD169A89CA76B18D509ECC28AE9FEE90C7CAEAA7764D86E7FF6983287BF851C003A080AF0D9740D7347A2DD9C194F4BBCB2D9613E4EE7D0FCDEAECB476C2594D2B911EF034592074BE2CE575734E9851F21BC81E3D81B1A3BF7A99D17259684207399BA7A53B486F27DB20BFC580CCB0F6919BF984A004EBF462B1E12F42EFADC237C1A0F32948285817DF3E74F70D90A3B604DC955742E9AF58C7348FEF6916A32C909C907730D2C09E589FBB15BAAE8323304F0689DB9597BA0523EF7185CCA2DF40ED330A17853FDEA0F768C7D22C04069BF4DF9732BF56C1770203010001A382034C30820348301F0603551D2304183016801474627099FF1B603BC464B5841FA3150C5CCB5FBD301D0603551D0E041604142895B254B2749E8338E29C11728B7EF6F28F71E3300F0603551D130101FF04053003010100300E0603551D0F0101FF0404030206C03082022E0603551D20048202253082022130820212060A2A84680186F87F01020330820202303006082B060105050702011624687474703A2F2F7777772E6575726F636572742E706C2F7265706F7A79746F7269756D2F308201CC06082B06010505070202308201BE0C8201BA436572747966696B617420777973746177696F6E79207A676F646E6965207A20616B7475616C6E796D20646F6B756D656E74656D3A20506F6C6974796B6120436572747966696B61636A692069204B6F64656B7320506F737465706F77616E696120436572747966696B6163796A6E65676F204B77616C6966696B6F77616E7963682055736C7567205A617566616E6961204575726F436572742C207A6E616A64756A6163796D207369652077207265706F7A79746F7269756D3A20687474703A2F2F7777772E6575726F636572742E706C2F7265706F7A79746F7269756D2F2E20546869732063657274696669636174652077617320697373756564206163636F7264696E6720746F207468652063757272656E7420646F63756D656E743A20436572746966696361746520506F6C69637920616E642043657274696669636174696F6E2050726163746963652053746174656D656E74206F66204575726F43657274205175616C69666965642054727573742053657276696365732C2077686963682063616E20626520666F756E6420617420687474703A2F2F7777772E6575726F636572742E706C2F7265706F7A79746F7269756D2F2E3009060704008BEC40010130310603551D1F042A30283026A024A0228620687474703A2F2F63726C2E6575726F636572742E706C2F71636130332E63726C305106082B0601050507010104453043304106082B06010505073002863568747470733A2F2F6575726F636572742E706C2F7075622F507261776F2F51434130335F4575726F636572745F323031372E646572302D06082B060105050701030421301F3008060604008E4601013013060604008E4601063009060704008E46010602300D06092A864886F70D01010B050003820201007A958A03E1F83A946154A8C1A6DA68243764377BB479EF56B39FE6E1005CF9D51E5E527FF0E64135A78853D5985FDB5E5444B249CBA9DA5382D4DC6FE9566FEF752620EDE07E749BDB06F3B525497FF4E3D3D0F41CC6F866D78C2AF6A0DED56652A9A1026DE0BED6A36A85629DE73AB3FBE8EB99C51507B88E03D9521A4DC01AD700A1BA3CA5BD13CEBB0A15F7043410BC2769FD3103A8B3F61A9DB4D2B7D66921833E64B6B6FF2156ECC1062769D984EFBFD13A3435173C64C11B06EED69043450825336B9ABD0FD484A37EE6764AEA412E9296F95EF03B5E3D6EFDA5B70930321B01117070DE27914A42BF9FA1A6494FF8A0BB3CBE223AB025DFAD979FB47F0FEEDD1C54422573D04EE6E43E17669ACD088E2B1AE3FE568BFC482F0CF9CEBE8B69AB4226EAD6022689E6E00684C06E2E855432206E564A23EDA6618989B918354E1C9115F26D082F4FEF3E5B8AB349D82142DCD31A26AA739D086677AA8D70AB978E6C5E848897F611C4540CCFC9B564CEFADB198FD848BFA3646BEEC0E5081EE5D5E1816EFC8032CCA578E69B7B9210AF49070A941DA4E68D3FC11F34128E31EE0F880CE3509F8B6BE650B11A6D5FD06B8BED9AAC9C8EE2BC60F819D05BEFD65D42BA261B27D6A781287BDB7142C643343A789BE56D6F1F4C0EA4EFCD52BF7343B74ADBA3D4021A560DEB2D8330DDC4EBF07B9760845E22DE0F4042C0D8020000318202CC308202C8020101308186306F3119301706035504610C10564154504C2D39353132333532333739310B300906035504061302504C311C301A060355040A0C134575726F436572742053702E207A206F2E6F2E3127302506035504030C1E43656E7472756D204B77616C6966696B6F77616E65204575726F43657274021300A5B201706C83F2C52960D9A270B5E315D216300D06096086480165030402010500A0820116301806092A864886F70D010903310B06092A864886F70D010701302F06092A864886F70D0109043122042003EBCF80DD1C6A491C02A7ADE38486CC78803BD5B73388E902A0F43B636CEFB03081C8060B2A864886F70D010910022F3181B83081B53081B23081AF0420F13CF1DE71F57181B13724467A071F322E9E83032418C00EAB1FC84CD9D36D0F30818A3073A471306F3119301706035504610C10564154504C2D39353132333532333739310B300906035504061302504C311C301A060355040A0C134575726F436572742053702E207A206F2E6F2E3127302506035504030C1E43656E7472756D204B77616C6966696B6F77616E65204575726F43657274021300A5B201706C83F2C52960D9A270B5E315D216300D06092A864886F70D01010B0500048201007606F574A7711638E5BCFCCE52F07E5493D72A0351B921D5E1E95EE7B9186CBB6F1B8D97111014817DCD0DDF21D97198EDF811045C4BEDD27BF0E105EE650CAF176C8BA61699BBA4A465E8D928B35E089BA1C994A1B6B33D41379F6FA08C3634714BDB49CD24370D8D776F55681021E3F791A73E19BD8C68CFD3E371D8619B536A91F7C3B010414D0B9A28B59066404C446A7E89273A46084887431CC4FE0DF039E2CAB78F630D9F82F93AC4225E41DD10DB6DDCE8819F56A904276AA902C31535EAF8644FF840BE31A5F486D9C9D3294392CEF019BAE4C32FD7336D7A6463570EF885653BF54C295A48EC654FCA1A2CD035E123C6585E385CED0CE5D6922116000000000000000000000

**Comment by levitte** [comment]
SHA256 itself is actually just this:

06 09 60 86 48 01 65 03 04 02 01

That's the DER encoding of the ASN.1 OBJECT IDENTIFIER 2.16.840.1.101.3.4.2.1

The rest around that is the signature structure around it.

Eirther way, `30 2F 30 0B 06 09 60 86 48 01 65 03 04 02 01` isn't the complete thing to look at.  `2F` is the length, that indicates that you need to look at all 47 bytes following it to get the full picture, not just  13...

If you want to play around, I suggest combining `xxd` and `openssl asn1parse`.  For the two strings you give us, I did this (subsequent tries in each case is with enough beginning bytes shaved off, and when needed, at the end as well):

-   30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00 04 20
    ``` console
    $ echo 30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00 04 20 | xxd -ps -r | openssl asn1parse -i -inform d
    Error in encoding
    140106177279360:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:../crypto/asn1/asn1_lib.c:91:
    $ echo 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00 | xxd -ps -r | openssl asn1parse -i -inform d
        0:d=0  hl=2 l=  13 cons: SEQUENCE          
        2:d=1  hl=2 l=   9 prim:  OBJECT            :sha256
       13:d=1  hl=2 l=   0 prim:  NULL              
    $ echo 06 09 60 86 48 01 65 03 04 02 01 | xxd -ps -r | openssl asn1parse -i -inform d
        0:d=0  hl=2 l=   9 prim: OBJECT            :sha256
    ```

-   30 2F 30 0b 06 09 60 86 48 01 65 03 04 02 01
    ``` console
    $ echo 30 2F 30 0b 06 09 60 86 48 01 65 03 04 02 01 | xxd -ps -r | openssl asn1parse -i -inform d
    Error in encoding
    140013986219392:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:../crypto/asn1/asn1_lib.c:91:
    $ echo 30 0b 06 09 60 86 48 01 65 03 04 02 01 | xxd -ps -r | openssl asn1parse -i -inform d
        0:d=0  hl=2 l=  11 cons: SEQUENCE          
        2:d=1  hl=2 l=   9 prim:  OBJECT            :sha256
    ```

**Comment by kongleiqiang** [comment]
The complete string is:30 2f 30 0b 06 09 60 86 48 01 65 03 04 02 01 04 20 1b 67 ca 30 56 42 54 29 68 58 5d 7f 2e 18 e1 58 94 0e 97 c1 28 12 87 31 25 5d 40 fc 1b 29 86 03
30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00 04 20 1b 67 ca 30 56 42 54 29 68 58 5d 7f 2e 18 e1 58 94 0e 97 c1 28 12 87 31 25 5d 40 fc 1b 29 86 03

I will use CMS_verify to verify the signature, and the data above will cause the verification to fail
![图片](https://user-images.githubusercontent.com/17700935/134802722-3fb65ea1-31ff-4117-9f96-122401a2ab75.png)

Is it possible to use the following code in the function (int_rsa_verify) during validation to make it compatible?

	if (decrypt_len == encoded_len - 2)
		{
			int len = (int)m_len;
			int sigOffset = decrypt_len - len - 2;
            int expectedOffset = encoded_len - len - 2;

             encoded[1] -= 2;      // adjust lengths
             encoded[3] -= 2;

             int nonEqual = 0;

              for (auto i = 0; i < (int)m_len; i++)
              {
                    nonEqual |= (decrypt_buf[sigOffset + i] ^ encoded[expectedOffset + i]);
              }

              for (int i = 0; i < sigOffset; i++)
              {
                    nonEqual |= (decrypt_buf[i] ^ encoded[i]);  // check header less NULL
              }

              return nonEqual == 0;
		}

![图片](https://user-images.githubusercontent.com/17700935/134802887-0d9dd5ca-7c38-42a9-9c5c-1afba20bb182.png)

**Comment by slontis** [comment]
@levitte
In ossl_DER_w_algorithmIdentifier_MDWithRSAEncryption() we set ossl_DER_w_null(pkt, -1)..
I think he is trying to load data that does not have the NULL param..

**Comment by slontis** [comment]
I think in 1.0.2 FOM it tried both encodings (whether that is right or not I dont know).

**Comment by kongleiqiang** [comment]
I have checked the latest code and found that there is no relevant compatibility processing. I don't know why

**Comment by t8m** [comment]
I do not think the encoding with NULL param is allowed by standards. And I do not think we should allow it in verification.

**Comment by levitte** [comment]
Why are you guys talking about MDWithRSAEncryption stuff here?

``` console
$ echo 30 2f 30 0b 06 09 60 86 48 01 65 03 04 02 01 04 20 1b 67 ca 30 56 42 54 29 68 58 5d 7f 2e 18 e1 58 94 0e 97 c1 28 12 87 31 25 5d 40 fc 1b 29 86 03 \
    | xxd -ps -r | openssl asn1parse -i -inform d
    0:d=0  hl=2 l=  47 cons: SEQUENCE          
    2:d=1  hl=2 l=  11 cons:  SEQUENCE          
    4:d=2  hl=2 l=   9 prim:   OBJECT            :sha256
   15:d=1  hl=2 l=  32 prim:  OCTET STRING      [HEX DUMP]:1B67CA305642542968585D7F2E18E158940E97C128128731255D40FC1B298603
```

``` console
$ echo 30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00 04 20 1b 67 ca 30 56 42 54 29 68 58 5d 7f 2e 18 e1 58 94 0e 97 c1 28 12 87 31 25 5d 40 fc 1b 29 86 03 \
    | xxd -ps -r | openssl asn1parse -i -inform d
    0:d=0  hl=2 l=  49 cons: SEQUENCE          
    2:d=1  hl=2 l=  13 cons:  SEQUENCE          
    4:d=2  hl=2 l=   9 prim:   OBJECT            :sha256
   15:d=2  hl=2 l=   0 prim:   NULL              
   17:d=1  hl=2 l=  32 prim:  OCTET STRING      [HEX DUMP]:1B67CA305642542968585D7F2E18E158940E97C128128731255D40FC1B298603
```

No trace of RSA in this stuff!  This is entirely about hash AlgorithmIdentifiers, which is something CMS uses extensively.
See https://datatracker.ietf.org/doc/html/rfc5754

@t8m is correct, but it's quite possible that we aren't as thorough as we should:

>   The AlgorithmIdentifier parameters field is OPTIONAL.
>   Implementations MUST accept SHA2 AlgorithmIdentifiers with absent
>   parameters.  Implementations MUST accept SHA2 AlgorithmIdentifiers
>   with NULL parameters.  Implementations MUST generate SHA2
>   AlgorithmIdentifiers with absent parameters.

Right now, I can't remember where exactly we generate or parse these...  I suspect this hasn't been translated to provider code yet.

**Comment by t8m** [comment]
I think we are talking here about the PKCS#1 v1.5 signatures and the padding is defined unambiguously to not include any algorithm parameters in RFC 8017.

**Comment by levitte** [comment]
Ah, then we're looking at DigestInfo: https://datatracker.ietf.org/doc/html/rfc8017#appendix-A.2.4

> For each OID, the parameters field associated with this OID in a value of type AlgorithmIdentifier SHALL have a value of type NULL.

**Comment by selvanair** [comment]
I think "30 2f 30 0b 06 09 60 86 48 01 65 03 04 02 01 04 20 || H" where the NULL parameter is missing is wrong encoding for EMSA-PKCS1-v1_5 (see RFC 8017 sec 9.2 Note 1). The option to omit the parameter does not apply in this  case -- see exceptions in Appendic B.1 of same RFC.

I have been looking into this to add encoding to the digest before sending it for signature to a pkcs#11 library using CKM_RSA_PKCS. Would love to know if both forms are standard compliant.

**Comment by levitte** [comment]
I strongly doubt that what we're looking at is PKCS#1 stuff.  If that was the case, we would see the OID name sha256WithRSAEncryption, not sha256.

https://datatracker.ietf.org/doc/html/rfc5754#section-2 is about CMS, which does things *differently* (to the confusion of everyone, including yours truly a bit too regularly), and the section I point at says that the NULL parameter *must* be produced (even though application must also accept absent parameters).

**Comment by davidben** [comment]
> I strongly doubt that what we're looking at is PKCS#1 stuff. If that was the case, we would see the OID name sha256WithRSAEncryption, not sha256.

By "PKCS#1 stuff", do you mean the DigestInfo structure inside an RSASSA-PKCS1-v1_5 signature? That one uses the digest OIDs, so sha256, not sha256WithRSAEncryption.

> I think we are talking here about the PKCS#1 v1.5 signatures and the padding is defined unambiguously to not include any algorithm parameters in RFC 8017.

It's the exact opposite. The internal structure of PKCS#1 v1.5 signatures *does* include the parameters. The RFC is, as you say, unambiguous in this:

>    Exception: When formatting the DigestInfoValue in EMSA-PKCS1-v1_5
>   (see Section 9.2), the parameters field associated with id-sha1,
>   id-sha224, id-sha256, id-sha384, id-sha512, id-sha512/224, and
>   id-sha512/256 shall have a value of type NULL.  This is to maintain
>   compatibility with existing implementations and with the numeric
>   information values already published for EMSA-PKCS1-v1_5, which are
>   also reflected in IEEE 1363a [IEEE1363A].

Note 1 in Section 9.2 also spells out the encodings precisely:
https://datatracker.ietf.org/doc/html/rfc8017#page-47

Additionally, accepting the other value would be a bug as verification in that RFC is defined in terms of constructing the expected value and comparing.

And, yeah, in other contexts it's a bit of a mess. :-( But in the context of message encoding for signatures, it's clear.

**Comment by levitte** [comment]
> By "PKCS#1 stuff", do you mean the DigestInfo structure inside an RSASSA-PKCS1-v1_5 signature? That one uses the digest OIDs, so sha256, not sha256WithRSAEncryption.

... this is embarrassing.  Had I read *all* of https://datatracker.ietf.org/doc/html/rfc8017#appendix-A.2.4 (something I did a few years ago, but apparently promptly forgot), I would had seen that for myself.  Inscidently, the end of that section also confirms the presence of the NULL parameter.

```
       PKCS1-v1-5DigestAlgorithms    ALGORITHM-IDENTIFIER ::= {
           { OID id-md2        PARAMETERS NULL }|
           { OID id-md5        PARAMETERS NULL }|
           { OID id-sha1       PARAMETERS NULL }|
           { OID id-sha224     PARAMETERS NULL }|
           { OID id-sha256     PARAMETERS NULL }|
           { OID id-sha384     PARAMETERS NULL }|
           { OID id-sha512     PARAMETERS NULL }|
           { OID id-sha512-224 PARAMETERS NULL }|
           { OID id-sha512-256 PARAMETERS NULL }
       }
```

**Comment by t8m** [comment]
Yeah embarrassing for me as well.

**Comment by opensignature** [comment]
However with the current code openssl cannot verify many signed files.
Verification that other products give correctly.
I would propose something like [this](https://github.com/openssl/openssl/compare/master...opensignature:master#diff-e957b6c457005d9ce7eb4f406ea86ef0dedf14900d42c997ba70f36f78c36e62
) (code is ugly and quickly written, but work).

**Comment by t8m** [comment]
These signatures are incorrect and should NOT be verified. So I do not think we are ever going to add this.

**Comment by resoli** [comment]
> And there is no choice here. If any current software formats the DigestInfoValue in EMSA-PKCS1-v1_5 differently, it is simply buggy.

Here I am. I am the maintainer of [j4sign](https://sourceforge.net/projects/j4sign/), a FLOSS sw for performing digital signatures according to EU EIdAS rules (formerly Italian ones, the project dates from 2004). I tried recently to verify some files signed with j4sign with latest OpenSSL (current master), and discovered that j4sign is affected. I think that I would never have found it if OpenSSL would not be strict in verification, so Thanks, really.

I tried another widespread (closed sw) tool based on the same Bouncycastle crypto libs that j4sign uses, and it seems not affected. So I guess the buggy implementations are may be very few nowadays.

Anyway, looking backwards at the rfcs for Pkcs#1, i found these: 

[rfc2313](https://datatracker.ietf.org/doc/html/rfc2313) (1998) -> [rfc2437](https://datatracker.ietf.org/doc/html/rfc2437) (1998) -> [rfc3447](https://datatracker.ietf.org/doc/html/rfc3447) (2003) -> [rfc8017](https://datatracker.ietf.org/doc/html/rfc8017) (2016) 

So, a very long history. If I am correct the mentioned `Exception: When formatting the DigestInfoValue in EMSA-PKCS1-v1_5 ...`
is present in recent [rfc8017 Appendix B.1 Hash Functions](https://datatracker.ietf.org/doc/html/rfc8017#appendix-B.1) only, and it is not unreasonable to suppose that many files signed some time ago could exhibit the wrong (correct at that time?) DigestInfo. 

Given that the wrong DigestInfo does not weakens crypto robustness (in my view), i'm thinking if a flag  like `-norfc8017` could relax `cms -verify` behavior, enabling OpenSSL usage for that class of obsolete signed files. 

What do you think?

Thanks,
rob

**Comment by t8m** [comment]
> So, a very long history. If I am correct the mentioned `Exception: When formatting the DigestInfoValue in EMSA-PKCS1-v1_5 ...` is present in recent [rfc8017 Appendix B.1 Hash Functions](https://datatracker.ietf.org/doc/html/rfc8017#appendix-B.1) only, and it is not unreasonable to suppose that many files signed some time ago could exhibit the wrong (correct at that time?) DigestInfo.

No, even in the RFC2313 this is specified - if you look in section 11.2.3 there is:
```
In the digestInfo type mentioned in [Section 9.2.1](https://datatracker.ietf.org/doc/html/rfc2437#section-9.2.1) the OIDS for the
   digest algorithm are the following:

   id-SHA1 OBJECT IDENTIFIER ::=
           {iso(1) identified-organization(3) oiw(14) secsig(3)
            algorithms(2) 26 }

   md2 OBJECT IDENTIFIER ::=
           {iso(1) member-body(2) US(840) rsadsi(113549)
            digestAlgorithm(2) 2}

   md5 OBJECT IDENTIFIER ::=
           {iso(1) member-body(2) US(840) rsadsi(113549)
            digestAlgorithm(2) 5}

   The parameters field of the digest algorithm has ASN.1 type NULL for
   these OIDs.
```

**Comment by resoli** [comment]
Hello @t8m. Sorry but I do not understand where to look. RFC2313 has no 11.2.3 section; do you mean rfc2437, section-9.2.1?

**Comment by t8m** [comment]
Yes, I'm sorry I meant RFC2437 section 11.2.3.

**Comment by resoli** [comment]
I see, thanks. I checked the rfcs in the sections you pointed out, and it seems to me that the real exception is the paragraph in rfc8017 mentioned by @opensignature:
> https://datatracker.ietf.org/doc/html/rfc8017#page-65 "This is to align with the definitions originally promulgated by NIST. For the SHA algorithms, implementations MUST accept AlgorithmIdentifier values both without parameters and with NULL parameters."

So I guess the impact should be very limited and related to implementations marginally used like mine (I fixed it, by the way). 

The presence of a 'sha256noparam' test cms in the junit test suite of Bouncycastle made me think the converse.

**Comment by t8m** [comment]
> https://datatracker.ietf.org/doc/html/rfc8017#page-65 "This is to align with the definitions originally promulgated by NIST. For the SHA algorithms, implementations MUST accept AlgorithmIdentifier values both without parameters and with NULL parameters."

We are running in circles. That part cited above is NOT relevant for the DigestInfoValue inside the EMSA-PKCS1-v1_5 encoding.
