### ISSUE TITLE
Issues understanding util/libeay.num

### ISSUE THREAD

**Issue by moatze87** [openssl/openssl#16692]
Hi,

I'm new to openssl and working on an very old branch of openssl, version 1.0.2d.
This branch has been patched to support certificate request message format.
I want to see the implementation of a couple of different functions, but I'm unable to find a function declaration or definition.

e.g. The code uses `i2d_CRMF_CERTREQMSG()`, but I'm unable to find the implementation.
A grep (ofc after applying the patch chain) `grep -r i2d_CRMF_CERTREQMSG` mentions the function a single time within util/libeay.num.:

`util/libeay.num:i2d_CRMF_CERTREQMSG                     5164	EXIST::FUNCTION:CRMF`

I search for help to understand what libeay.num does (some sort of mapping?) and where/how to find further info on that function.

Best regards!

**Comment by mattcaswell** [comment]
It's not libeay.num that is doing the magic. Almost certainly these functions are implemented via macros. See the code here:

https://github.com/openssl/openssl/blob/12ad22dd16ffe47f8cde3cddb84a160e8cdb3e30/crypto/asn1/asn1t.h#L821-L912

Most likely there is a line in your patch somewhere that looks something like this:

````
IMPLEMENT_ASN1_FUNCTIONS(CRMF_CERTREQMSG)
````

However as you can see from the above link there are a few variants of these macros with slightly different names besides `IMPLEMENT_ASN1_FUNCTIONS` so you might need to do some searching to find exactly how it is implemented.

**Comment by moatze87** [comment]
Thanks @mattcaswell, this sheds some light onto the issue and helps me to proceed!
