### ISSUE TITLE
Compiling for Android on a windows computer

### ISSUE THREAD

**Issue by helgovic** [openssl/openssl#16691]
I'm trying to compile for Android. I'm using a Windows computer, with msys and perl and python installed. I'm using NDK r21. I keep getting "no NDK arm-linux-androideabi-gcc on $PATH at (eval 6) line 124". What should the  PATH variable (toolchain) be set to? How shold the ./Configure parameters be set? Other variables? Is there somewhere that i can get the .so files? I need version 3

**Comment by xtkoba** [comment]
Assuming that `ANDROID_NDK_ROOT` is already set to the correct value, `PATH` needs to include the following place:

```
$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/windows-x86_64/bin
```

For further details please read https://github.com/openssl/openssl/blob/master/NOTES-ANDROID.md

P.S. Although this might be irrelevant, I recommend that you upgrade your NDK to version r23, as version r21 is no longer officially supported. You can download it from https://developer.android.com/ndk/downloads

**Comment by helgovic** [comment]
I tried r23. Now i get
$ANDROID_NDK_HOME=c:/Users/Public/Documents/Embarcadero/Studio/21.0/CatalogRepository/android-ndk-r23 is invalid at (eval 6) line 37

cd /c/openssl-master/openssl-master
rm -rf "libs"
mkdir -p  "libs"
export ANDROID_NDK_ROOT=/c/Users/Public/Documents/Embarcadero/Studio/21.0/CatalogRepository/android-ndk-r23
export ANDROID_NDK_HOME=/c/Users/Public/Documents/Embarcadero/Studio/21.0/CatalogRepository/android-ndk-r23
PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/windows-x86_64/bin:$PATH
./Configure android-arm -D__ANDROID_API__=29 --openssldir=libs

**Comment by xtkoba** [comment]
First make sure that `c:/Users/Public/Documents/Embarcadero/Studio/21.0/CatalogRepository/android-ndk-r23/source.properties` exists and that ~~`c:/Users/Public/Documents/Embarcadero/Studio/21.0/CatalogRepository/android-ndk-r23/AndroidVersion.txt`~~ does NOT exist.

Also make sure that the Perl used comes from MSYS2.

Of course it is possible that the configuration file ([`Configurations/15-android.conf`](https://github.com/openssl/openssl/blob/master/Configurations/15-android.conf)) has some portability issues. Windows paths are totally different from *nix after all...

**Comment by helgovic** [comment]
I reverted back to m r21 ndk, and i was able to configure, but the make failed with

make[1]: llvm-ar: Argument list too long
make[1]: *** [Makefile:11501: libcrypto.a] Error 127
make[1]: Leaving directory '/c/openssl-master/openssl-master'
make: *** [Makefile:2762: build_sw] Error 2

I then downloaded the version 3.0 branch, and that compiled

**Comment by xtkoba** [comment]
> make[1]: llvm-ar: Argument list too long

Similar to #10459.
