### ISSUE TITLE
Legacy provider question

### ISSUE THREAD

**Issue by maheshkumar01** [openssl/openssl#16708]
We are porting our code working with OpenSSL 1.1.1 to OpenSSL 3.0.0. After porting, our code works with OpenSSL 3.0.0 but has to load legacy library, may be because support for some of the ciphers/ APIs moved to legacy library. We want to get rid of legacy library support.  

For example the code uses ```NID_pbe_WithSHA1And40BitRC2_CBC``` for which it needs legacy library support.

Is there any link which talks about the ciphers moved to legacy library with OpenSSl 3.0.0? And how get around this?

**Comment by t8m** [comment]
Please see https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-legacy.html for the list of algorithms in the legacy provider.

Your code would not be able to use RC2 based password based encryption without legacy provider loaded.
