### ISSUE TITLE
OpenSSL 1.1.1l v. VMS -- build failure, "openssl0101.EXE"

### ISSUE THREAD

**Issue by Antinode-org** [openssl/openssl#16702]
On a VMS V8.4 IA64 system, I had some problems with OpenSSL 1.1.1l.

   Perl on this system says:

```
ITS $ perl --version

This is perl 5, version 26, subversion 1 (v5.26.1) built for VMS_IA64
```

   If the whole "perl configdata.pm --dump" result (or other info) would
actually help, then please let me know.

   First, the OpenSSL build failed.

```
ITS $ show default
  ITS$DKA0:[UTILITY.SOURCE.OPENSSL.openssl-1_1_1l]

ITS $ @ config --prefix=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.1_1_1l -
_ITS $ --openssldir=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.1_1_1l]
Configuring OpenSSL version 1.1.1l (0x101010cfL) for vms-ia64
Using os-specific seed configuration
Creating configdata.pm
Creating descrip.mms

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
[...]
```

   That's one opinion.  Not widely shared, however.  ("UTILITY_DEV"
translates to "ITS$DKA0", by the way.)

```
ITS $ mms

%DCL-W-PARMDEL, invalid parameter delimiter - check use of special characters
 \]\
%MMS-F-ABORT, For target .FIRST, CLI returned abort status: %X00038110.
-CLI-W-PARMDEL, invalid parameter delimiter - check use of special characters
```

      descrip.mms:

```
# Do not edit this manually. Use Configure --prefix=DIR to change this!
INSTALLTOP=[.UTILITY_DEV:^[UTILITY^.SOURCE^.OPENSSL^.1_1_1L]
SYSTARTUP=[.UTILITY_DEV.^[UTILITY^.SOURCE^.OPENSSL^.1_1_1L.SYS$STARTUP]
# This is the standard central area to store certificates, private keys...
OPENSSLDIR=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.1_1_1L]
```

   Someone apparently decided to "fix" my path specifications.  With
unfortunate results.

   After I did "edit this manually", restoring my original path
specifications, it seemed to work, including "mms test", with this
exception:

```
[.recipes]80-test_ocsp.t ..................... ok
%DCL-W-IVKEYW, unrecognized keyword - check validity and spelling
 \-A\
```

   It would be nice if "config.com" didn't try to "fix" the perfectly
fine user-supplied path specifications, producing only junk to replace
them.  A "--please-do-not-help-me" option would be helpful.  If some
"absolute" path is required, then the script might look for an unescaped
":", followed by an unescaped "[" which is not followed by a dot.

   Or, if Perl can't be trusted, then the script could test a known-good
"device:[directory]" path to see if it remained valid after the "fix"
was applied, and then if the "fix" is determined to be broken, don't
inflict it on the user.  As usual, many things are possible, and most of
them would be better.

   Second, when trying to use the resulting 1.1.1l kit, I had trouble
adapting a previously satisfactory, adequately flexible program builder
to the new, more complex naming/numbering scheme.

   The intended target was Kermit, whose VMS builders use the version
number of the user-selected OpenSSL package to adjust some of the C
macros which determine some things which have changed in OpenSSL over
time -- things such as where the "const" attribute is used.

    The existing builders attempt to use commands like the following to
determine the OpenSSL version:

```
      $ openssl_cmd := $ <user-specified_logical_name>:openssl.exe
      $ openssl_cmd version
```

where "<user-specified_logical_name>" might be, say, "SSL$EXE"
("SSL$ROOT:[IA64_EXE]") or "SSL1$EXE" ("SSL1$ROOT:[IA64_EXE]") for the
HPE-supplied SSL kits, or "SSLEXE" (sslroot:[IA64_exe]) for OpenSSL
versions before the Great Enlightenment (1.1.1).

   This all worked fine, until, for some reason which I have not yet
discovered, all the relevant logical names have been changed (made more
complicated), and the name of the OpenSSL executable was changed from
"OPENSSL.EXE" to "openssl0101.EXE".  Needing to add another set of
(misguided?) logical names to the scheme is annoying, but adding "the
shared library version (0101 for 1.1.x)" (as it says in INSTALL) to the
"openssl" program name pretty much defeats the whole scheme.  If I need
to guess the program version number to find the program which I want to
tell me the program version number, then I fail to see the wisdom in the
new naming/numbering scheme.

   Is there some actual reason for polluting the executable name with
this version-related information?  What's the actual benefit?  Why does
VMS deserve this bonus complication, which I didn't notice on my Mac,
where "/usr/local/bin/openssl" seems to have escaped this "enhancement"?

   Any useful advice would be gratefully received.

**Comment by Antinode-org** [comment]
After some rest and extended staring, I spotted my (_my_) original
path-specification error:

```
      Missing "]" ------------------------------------------------v
ITS $ @ config --prefix=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.1_1_1l -
_ITS $ --openssldir=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.1_1_1l]
```

(The difference between "l" and "]" might have been too small for my old
sensory/cognitive apparatus.  Lucky font, too.)

   Some kind of useful error message (instead of a confused path
transformation hidden inside descrip.mms) would still be nice in such a
case.

   Complaints regarding "openssl0101.EXE" (and the rest of the
name/number changes) remain.

**Comment by levitte** [comment]
It was desirable to be able to have several major OpenSSL releases installed at the same time.  This is the reason why the libraries got the same sort of shared object version in the file name as we often see on, for example, Linux (like `libcrypto.so.1.1`).
At the time (this is years ago, at the time we were working toward 1.1.0), I do recall an expressed interest in also having the executable should be available in a similar fashion...  in retrospect, that doesn't seem very useful, so I see your point re openssl0101.EXE.

All that being said, the use that we ultimately support is an installation (the result of `mms install` and varieties thereof), and the use of our startup / shutdown / login scripts to get the logicals and symbols (`OPENSSL`!) to work with.  If people decide to use what's in the build directory directly, they're kinda sorta on their own, even though we're willing to help figure out ways to do things.

**Comment by levitte** [comment]
Regarding the `--prefix` argument (oh, and that holds for the `--openssldir` argument as well), we have so far never made a sanity check on them, on any platform.  I can personally not remember hearing this sort of bug report for all the time since 1.1.0 came out.

I agree that it's reasonable to have some sort of sanity check of the command line arguments.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
