### ISSUE TITLE
skip compilation of executables

### ISSUE THREAD

**Issue by manang** [openssl/openssl#16719]
Is there a way to skip the compilation of the executables? I want to compile only the libs
Thanks

**Comment by paulidale** [comment]
`make build_libs`?

**Comment by manang** [comment]
thanks, but is there a way to pass this command to ./Configure script?
something like no-apps

**Comment by t8m** [comment]
No, there isn't.

**Comment by paulidale** [comment]
Not that I'm aware of.

**Comment by manang** [comment]
ok, thanks for your help
