### ISSUE TITLE
Issue while compiling the openssl in windows 10 OS

### ISSUE THREAD

**Issue by velrajancse** [openssl/openssl#16723]
When compiling the OpenSSL source code, I am getting following error

Error libcrypto.rc 1 11: Cannot open file: winver.h
** error 20018 ** deleting libcrypto-shlib-libcrypto.res
** error 1 ** deleting **build_sw**

![image](https://user-images.githubusercontent.com/36440376/135498942-ab9a9441-3234-4832-b157-1b5de0359c3b.png)

Kindly help me how to fix this error

**Comment by t8m** [comment]
I am not sure Borland compiler (and looks like a quite old one) is supported for building OpenSSL.

**Comment by mattcaswell** [comment]
Borland support was removed a long time ago (8e56a4227).
