### ISSUE TITLE
Implement AES-GCM-SIV

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16721]
AES GCM SIV is specified in [RFC 8452](https://datatracker.ietf.org/doc/html/rfc8452)

**Comment by dylan7581** [comment]
Hello,

We are a team of new contributors whose goal is to answer security issues on open source projects.

In response to your ticket, we tried to implement AES-GCM-SIV in OpenSSL inspired by what was done for AES-GCM. Here you will find our implementation of this algorithm:
<https://github.com/Project-Opensource/AES-GCM-SIV>

Unfortunately, due to a lack of knowledge of the OpenSSL architecture (with the providers directory), we were unable to integrate it correctly so that it was available for use.

In the hope that our contribution will advance the problem,

Contribution by [Project Opensource](https://github.com/Project-Opensource).

**Comment by tmshort** [comment]
I can't speak for the OMC, but there might be some licensing issues here. Specifically, OpenSSL uses the Apache 2.0 license and I'm not seeing any formal licensing in that repository. Then there's the matter of CLAs.

If those issues are resolved, I'd be willing to look at this; I was the one that ported the AES-SIV code.

Ref: [RFC-8452](https://datatracker.ietf.org/doc/html/rfc8452)

**Comment by mattcaswell** [comment]
> I'm not seeing any formal licensing in that repository. Then there's the matter of CLAs.

All contributors who were involved in writing the code would have to submit CLAs to us (https://www.openssl.org/policies/cla.html). We would also need some statement formally contributing the code to us. Usually when code is contributed it occurs through a PR which is deemed as sufficient indication that the authors are contributing the code - but there is no PR here. The licensing of the original code is not really a problem: if the authors sign a CLA, and formally contribute the code under that CLA, then the CLA allows us to relicence it to Apache 2.

**Comment by tmshort** [comment]
> The licensing of the original code is not really a problem

I was mostly checking to see if there was already Apache, BSD, MIT or GPL licensing attached. I suspect that any GPL flavor would be an issue.

**Comment by tmshort** [comment]
Actually, it looks as though they applied an Apache 2.0 license on it: https://github.com/Project-Opensource/AES-GCM-SIV/commit/5ac1d5704caa1fa017bd6b39b3cb18ae340b3138

**Comment by t8m** [comment]
We would still need CLAs signed.

**Comment by dylan7581** [comment]
Hello,

We sent the signed CLAs by email.

**Comment by tmshort** [comment]
@t8m @mattcaswell unless someone else _really_ wants to do this, feel free to assign this to me.

**Comment by dylan7581** [comment]
Hello,

we sent our CLA to the email address: legal@opensslfoundation.org, but we received an email telling us this:
"We were unable to deliver your mail. The recipient's mail system refused to accept a connection from your mail system despite multiple attempts to deliver your mail."

How should we proceed ?

**Comment by paulidale** [comment]
That's the correct address, I didn't see anything come in.  No idea why :(

@levitte, any idea?

**Comment by dylan7581** [comment]
We also tried with another mail service, but the result is the same. : -(
Do you have a temporary solution that could work around this problem?

**Comment by paulidale** [comment]
@levitte??

**Comment by beldmit** [comment]
Are there any updates regarding the CLA status?

**Comment by paulidale** [comment]
Could you please resend the CLAs to legal@opensslfoundation.org, we had some server problems recently.

**Comment by dylan7581** [comment]
Email is working fine again!

**Comment by tmshort** [comment]
What's the status of this?
