### ISSUE TITLE
Y2038 overflow problem in API functions taking long values when compiling for Windows

### ISSUE THREAD

**Issue by bplu4t2f** [openssl/openssl#16726]
When cross compiling for Windows as per the instructions in the readme files:

```
./Configure mingw --cross-compile-prefix=i686-w64-mingw32-
./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32-
```

, then `sizeof(long) == 4`. This is effecitvely required by mingw to ensure compatibility of generated code with other compilers on Windows, given the same header files.

This impacts functions which take timestamps generated by `time` in particular, such as `SSL_SESSION_flush_sessions`, and makes them susceptible to the year 2038 (Y2038) overflow problem.

As far as I can tell the root problem is that `long` is used in places where `time_t` (which is 64 bit using reasonably modern Windows compilers) would have been appropriate. The only function I personally ran across noticing this was `SSL_SESSION_flush_sessions`.

Fixing this would be non-trivial since it would break ABI compatibility. It might not be classified as a bug per-se, but rather as a quietly accepted shortcoming, but it'll need to be fixed eventually at some point in the future, and I haven't been able to find an existing issue mentioning this.

**Comment by t8m** [comment]
I'll set it as feature as IMO this cannot be fixed in released versions. However we could add _ex() API calls in future releases that would have appropriately typed parameter for that.

**Comment by h-vetinari** [comment]
Xref #15231 / #10995
CC @richsalz

**Comment by FdaSilvaYY** [comment]
Issue was mentioned here, during a review : 
 https://github.com/openssl/openssl/pull/8687#discussion_r610855707
I give a try, some times ago.
This changes is raising a lots of warning/errors for some platforms, because of implicit types conversions.

**Comment by richsalz** [comment]
you CC'd me but I'm not involved with openssl any more.

**Comment by slontis** [comment]
It would also effect these..
````
long SSL_CTX_set_timeout(SSL_CTX *ctx, long t);
long SSL_CTX_get_timeout(const SSL_CTX *ctx);
long SSL_SESSION_get_time(const SSL_SESSION *s);
long SSL_SESSION_set_time(SSL_SESSION *s, long t);
long SSL_SESSION_get_timeout(const SSL_SESSION *s);
long SSL_SESSION_set_timeout(SSL_SESSION *s, long t);
unsigned long SSL_SESSION_get_ticket_lifetime_hint(const SSL_SESSION *s);
````

**Comment by TabLand** [comment]
Hi Team!

Hope you're having a fine day.

I've been digging through the following cpython issue, which I believe is related to `SSL_SESSION_get_time()` being of `long` return type; which according to the output of `./configure` is only 4 bytes on i686, and 8 bytes on x64. 

https://github.com/python/cpython/issues/101732

This effects 32 bit Python builds against i686 Linux built with these flags to enable 64 bit time:
```
export CPPFLAGS="-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64"
```
It looks like the return value of `SSL_SESSION_get_time()` overflows and returns a negative number when the system date is post Y2038. I don't believe `SSL_SESSION_get_time()` is a relative time compared against the SSL Session, according to the documentation:

https://www.openssl.org/docs/manmaster/man3/SSL_SESSION_get_time.html
```
SSL_SESSION_get_time() returns the time at which the session s was established. 
The time is given in seconds since the Epoch and therefore compatible to the time delivered by the time() call.
```
I'll try and have a go at drafting a PR if I get some time and test it against the above cpython issue.

**Comment by nhorman** [comment]
@TabLand did you ever raise a PR for this?  If so, please attach it here.  Otherwise, given that we have other issues to address time_t concerns, I'll close this.

Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by FdaSilvaYY** [comment]
Not all mentioned functions above are currently fixed.

**Comment by nhorman** [comment]
@FdaSilvaYY Can you enumerate which functions still need to be addressed please?

**Comment by t8m** [comment]
IMO there are no other functions having long representing a time in seconds since epoch.

**Comment by t8m** [comment]
So AFAIK this can be closed.
