### ISSUE TITLE
How to access passphrase within external provider?

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#16746]
The documentation regarding the proper use of `cbarg` within a provider when implementing [OSSL_FUNC_encoder_encode_fn](https://www.openssl.org/docs/manmaster/man7/provider-encoder.html ) is _very_ brief; the code itself seems to suggest it is a (stack-based) `struct ossl_passphrase_data_st`, which seems to be inaccessible to (external) providers.  Internal/libcrypto-based providers can (and do) make use of [internal APIs](https://github.com/openssl/openssl/blob/master/include/internal/passphrase.h) to get access to passphrase information. However, this API set is not available to (external) providers, right? 

So what mechanism is suggested to be used by external providers to obtain access to the passphrase, e.g., as set for encrypting private keys? Thanks in advance.

**Comment by levitte** [comment]
The `cbarg` is passed to the password callback (`OSSL_PASSPHRASE_CALLBACK`).  It's *entirely* up to that passphrase callback to define what `cbarg` actually is.  To anyone else, it's simply a pointer that's passed on.

What are you trying to achieve?  I might have an idea or two how to do that.

**Comment by levitte** [comment]
If you have an issue for this in your project, please point at it...  it might be easier to discuss ideas there.

**Comment by baentsch** [comment]
> If you have an issue for this in your project, please point at it

OK, it's all part of https://github.com/open-quantum-safe/oqs-provider/issues/2 . Will create suitable code pointers there and reference you.

**Comment by levitte** [comment]
Yes
