### ISSUE TITLE
FIPS APIs

### ISSUE THREAD

**Issue by maheshkumar01** [openssl/openssl#16742]
We have code where we integrated with OpenSSL 1.1.1. Since OpenSSL 3.0.0 is released we planning to upgrade to latest released OpenSSL. Our product do support FIPS. With OpenSSL 1.1.1 we used APIs ```FIPS_mode()``` and ```FIPS_mode_set(1)```. 

Is it safe to assume that we should be able to replace above mentioned APIs with ```EVP_default_properties_is_fips_enabled(NULL)``` and ```EVP_default_properties_enable_fips(NULL, 1)``` ?

**Comment by paulidale** [comment]
Not completely, these calls do not do exactly what you're wanting, they are just setting/checking the default property query.  I suggest looking at the [migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html#Using-the-FIPS-Module-in-applications) and specifically the FIPS relevant parts.
