### ISSUE TITLE
Add EVP_MAX_TAG_LENGTH

### ISSUE THREAD

**Issue by ladar** [openssl/openssl#1674]
OpenSSL supports a maximum tag length of 16 octets for the AEAD block modes, but there is no easy way of checking for that maximum. I would like to suggest adding the define EVP_MAX_TAG_LENGTH so it follows the convention currently used by EVP_MAX_IV_LENGTH. 

I also noticed that GCM and OCB allow a tag length of 0 in their EVP_CTRL_AEAD_SET_TAG operations. Is that correct? 

CCM enforces a minimum length of 4, which should probably be the minimum for GCM and OCB as well. Presuming that's the case, then perhaps EVP_MIN_TAG_LENGTH should also be added. 
See crypto/evp/e_aes.c lines 1320 and 2389 for the min of 0 and line 1974 for the min of 4. 
Note the first two lines would be updated to use  EVP_MAX_TAG_LENGTH once it has been added.

**Comment by mattcaswell** [comment]
Moving to post 1.1.1

**Comment by t8m** [comment]
These could be gettable parameters of EVP_CIPHER.

**Comment by paulidale** [comment]
`s/could/should/`

**Comment by mattcaswell** [comment]
`EVP_MAX_AEAD_TAG_LENGTH` was added in OpenSSL 3.2...

...and now we're considering removing it again:

openssl/project#435

Anyway, for now at least, this feature has been implemented.
