### ISSUE TITLE
SSL_CTX_set_ssl_version openssl 3.0

### ISSUE THREAD

**Issue by manang** [openssl/openssl#16740]
Hi,
I'm trying to convert my application linked against openssl 1.1.1 to openssl 3.0
my unique error is:
SSL_CTX_set_ssl_version is deprecated: do you know what is the relative function on openssl 3.0?
Thanks
Angelo

**Comment by davidben** [comment]
What are you trying to do with that function? `SSL_CTX_set_ssl_version`, contrary to the name, actually swaps out the underlying `SSL_METHOD`, which is more than a little strange.

Are you just trying to configure TLS versions? In that case, the answer is `SSL_CTX_set_max_proto_version` and `SSL_CTX_set_min_proto_version`.

**Comment by moooscht** [comment]
Hi,
I tried using **SSL_CTX_set_min_proto_version** to force **TLS 1.3** with **openssl 3.0.0** for a **client application**.
Also check it with **SSL_CTX_get_min_proto_version** successfully.
But in the **Client Hello** only **TLS 1.2** is showing up, can't solve it ... 
![client_hello](https://user-images.githubusercontent.com/91946481/135996939-46b71bd1-1c85-4405-be84-a05a7c24646a.png)

**Here's the simplified code:**
OPENSSL_init_ssl(OPENSSL_INIT_LOAD_SSL_STRINGS, NULL);
meth = (SSL_METHOD*)TLS_client_method();
ctx = SSL_CTX_new(meth); if (!ctx) {... ERROR ...}
if (SSL_CTX_set_min_proto_version(ctx, TLS1_3_VERSION) != 1) {... ERROR ...}
if (SSL_CTX_get_min_proto_version(ctx) != TLS1_3_VERSION)	 {... ERROR ...}
SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);
if (SSL_CTX_set_default_verify_paths(ctx) != 1) {... ERROR ...}
myssl = SSL_new(ctx); if (!myssl) {... ERROR ...}
...here I create the TCP socket (successfully) ...
SSL_set_fd(myssl, (int)(S_socket) );
err = SSL_connect(myssl); if (err < 1) {... ERROR ...}
...

Is there a fault in the code ?
Thank you for your help !!

**Comment by manang** [comment]
> What are you trying to do with that function? `SSL_CTX_set_ssl_version`, contrary to the name, actually swaps out the underlying `SSL_METHOD`, which is more than a little strange.
> 
> Are you just trying to configure TLS versions? In that case, the answer is `SSL_CTX_set_max_proto_version` and `SSL_CTX_set_min_proto_version`.

thanks for your help

**Comment by mattcaswell** [comment]
> But in the Client Hello only TLS 1.2 is showing up, can't solve it ...

This seems to be a different question (please don't hijack other people's issues)...but ok....what you are seeing is normal behaviour. The field you have highlighted is the legacy version field and isn't used in TLSv1.3. Its always set to to TLSv1.2. Version information is instead negotiated via the "supported_versions" extension.

**Comment by moooscht** [comment]
Sry for hijacking, thought it's a similar theme ... won't do it again :)
And thank you for the help, now it's clear :)
