### ISSUE TITLE
When cert verification is disabled, SSL handshake should continue despite DH key is too short

### ISSUE THREAD

**Issue by jinq102030** [openssl/openssl#1675]
I created an issue #1176 but I believe it's closed by mistake.   The point is that when user doesn't care about security by turning off cert verification,  the SSL handshake should move on despite the DH key is too short.

Here is the text from #1176. 

Currently with openssl 1.0.2j, when client starts SSL handshake, it will bail out when Diffie Hellman Key is too short (64bytes). This is true even when certificate verification is turned off on client.

Wonder if openssl should not complain about DH key being too short. After all this is for testing purpose and user is even ok with no cert verification!

Thanks.

**Comment by kroeckx** [comment]
If you don't do the validation of the certificate, you don't seem
to care about the authentication. But you might still want the
secrecy. You might as well not use SSL with such a short DH key.

**Comment by mattcaswell** [comment]
This is a non-issue. No authentication does not mean you should accept poor key exchange. Closing this.
