### ISSUE TITLE
pkey_set_type() mishandles ENGINE references

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#16757]
The internal function `pkey_set_type` seems to mishandle `ENGINE` references passed to it. Most of the time it consumes the reference on success - but not always:

https://github.com/openssl/openssl/blob/a596d38a8cddca4af3416b2664e120028d96e6a9/crypto/evp/p_lib.c#L1501-L1504

Although by luck I think the above codepath probably can't be hit at the moment with existing usage of `pkey_set_type` where the `ENGINE` is non-null since the pkey is always freshly allocated when it is called.

The fact that `pkey_set_type()` consumes the `ENGINE` reference seems quite surprising and means that the public API functions `EVP_PKEY_new_raw_private_key_ex()`, `EVP_PKEY_new_raw_private_key()`, `EVP_PKEY_new_raw_public_key_ex()` and `EVP_PKEY_new_raw_public_key()` also consume it - even in some failure cases (but there is at least one case where it is *not* consumed).

Due to the behaviour of `pkey_set_type()` this also means the function `EVP_PKEY_new_CMAC_key()` consumes the `ENGINE` reference in (most) cases in 1.1.1, but no longer does so in 3.0 (because the implementation of `EVP_PKEY_new_CMAC_key()` has changed considerably and no longer calls `pkey_set_type()`).

The documentation for these functions makes no reference to the fact that the `ENGINE` reference is consumed, and this seems quite surprising behaviour because most other similar functions that take an `ENGINE` reference do not do so.

I do not believe it was the original intent for the reference to be consumed, and I think the behaviour of `pkey_set_type` is an error.

See also:
https://mta.openssl.org/pipermail/openssl-users/2021-October/014423.html

**Comment by t8m** [comment]
The issue is present on 1.1.1 as well, isn't it?

**Comment by mattcaswell** [comment]
Yes it affects master, 3.0 and 1.1.1

**Comment by bernd-edlinger** [comment]
Ah, okay, that's funny. so if invoked with e=NULL it is still using an engine.
I just wonder how #16750 manages not to trigger this issue.

**Comment by mattcaswell** [comment]
It only impacts if you call `EVP_PKEY_new_raw_private_key_ex()`, `EVP_PKEY_new_raw_private_key()`, `EVP_PKEY_new_raw_public_key_ex()`,  `EVP_PKEY_new_raw_public_key()` or (in 1.1.1 only)  `EVP_PKEY_new_CMAC_key()` with an explicit ENGINE parameter which I guess does not happen with #16750.
