### ISSUE TITLE
"cipher operation failed" / "failed or bad record mac" when ETM is not set in extensions.

### ISSUE THREAD

**Issue by jwh-hutchison** [openssl/openssl#16758]
On both OpenSSL 1.1.1 and OpenSSL3, I'm having issues where unless I specify `encrypt-then-mac` in the TLS handshake extensions, I have to suffer an unavoidable 'failed or bad record mac' error that originates from evaluating the ciphersuite. This is happening for all available ciphers in both CBC and GCM mode when I'm trying to run a TLS-PSK server, I have tested that I can connect to the server with `OpenSSL c_client` but that force enables`ecrypt-then-mac` in the packet extensions whereas with the application I'm writing, I'm unable to specify the header.

The exact error is:
```
40BD7C0201000000:error:1C800066:Provider routines:ossl_gcm_stream_update:cipher operation failed:providers/implementations/ciphers/ciphercommon_gcm.c:312:
40BD7C0201000000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:610:
```

But I see no reason for it as wireshark shows that a server hello response was provided with an agreed-upon ciphersuite and all the extensions that are active. So the client handshake should be valid, but it looks like it fails because of the lack of ETM.

**Comment by t8m** [comment]
The encrypt-then-mac extension should have no effect on GCM ciphersuites. There must be something wrong with your application that causes the decryption to fail. What is the server? Is it also OpenSSL based?

**Comment by jwh-hutchison** [comment]
OK, perhaps it's the extensions that are being included with the application then. and those were my thoughts too, that ETM/MTE should only apply when using CBC.

`openssl3 s_server -tls1_2 -accept 8888 -nocert -psk abc123 -psk_identity test` is being used to create the server, I can connect successfully using `openssl3 s_client -tls1_2 -connect localhost:8888 -psk abc123 -cipher PSK-AES256-GCM-SHA384` but when I run with iOS which uses BoringSSL it fails.

In wireshark the noticable differences are that:
on the working server end: 
1. 'TLS_EMPTY_RENEGOTIATION_INFO_SCSV` is inside ciphersuites (but I notice that the server hello response sets the renegotiation extension value anyway) - I'm specifying PSK-AES256-GCM-SHA384 in both instances
2. there are 20 algorithms listed in the signature hash algorithms extension whereas there are only 11 listed on iOS

There's a number of different extensions, `ec_points_format`(len=12), `supported_groups`(len=2), `status_request`(len=5), `reserved(grease)`(len=1) are present on the iOS client hello packet but not on openssl s_client - is it more likely that one of those are the culprits? because when I receive a server hello, it doesn't include those extensions.

**Comment by jwh-hutchison** [comment]
Issue resolves around iOS network framework and is not an issue with OpenSSL.
