### ISSUE TITLE
OBJ_add_sigid disallows NID_undef for the digest id

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#16761]
The function `OBJ_add_sigid` explicitly disallows `NID_undef` for the digest id:

https://github.com/openssl/openssl/blob/64da15c40d15aac58e211fd25d00e9ae84d0379b/crypto/objects/obj_xref.c#L139-L145

However this makes no sense since we have multiple signature algorithms in the built-in list where it is valid for the digest id to be NID_undef (e.g. Ed25519 and Ed448):

https://github.com/openssl/openssl/blob/64da15c40d15aac58e211fd25d00e9ae84d0379b/crypto/objects/obj_xref.h#L22-L83

There are external provider that need to do this:
https://github.com/open-quantum-safe/oqs-provider/issues/2#issuecomment-936308396

**Comment by mattcaswell** [comment]
Should this be considered a bug?

**Comment by levitte** [comment]
Another thing to consider is that if there is no info present for the signid in question, we could simply try with it (or the associated OID / name) as it is, without digest...  In other words, without info, assume that it's to be initialized the same way as ED25519.

That would also pave the way to have directly fetchable sigs, like sha1WithRSAEncryption.

**Comment by mattcaswell** [comment]
That's something to consider for the master branch. It seems less plausible as a bug fix eligible for backport to 3.0.

**Comment by t8m** [comment]
I agree this is a bug.
