### ISSUE TITLE
Please apply automated building and quality assurance to the github repo

### ISSUE THREAD

**Issue by javabeanz** [openssl/openssl#1677]
Github offers a plethora of automation tools, for building on multiple platforms and compilers, security auditing and code quality checks and so on. Please use them and get Github project badges to the world the status of the build, the overall quality of the code and the number of vulnerabilities in the dependencies (if any). This great corner stone project of the internet can benefit a lot from this.

**Comment by kroeckx** [comment]
If you create a pull request, it should be obvious that we have
CI. We just don't have any badges that go with it. I guess this
might be useful for external people to see some of the things that
we do.

**Comment by javabeanz** [comment]
good to hear that. I dont see any of that in your project description, so it;s not that obvious you have CI. Do you also have integration with some of the quality and security services ? (https://github.com/integrations/feature/security)

**Comment by kroeckx** [comment]
I did look at this before. Some of them are about issues in third party packages (which we don't have), some of them don't work with C. The others are also mentioned at https://github.com/integrations/feature/code-quality, which is probably what we want to look at.

The only thing I find there that might be useful is SonarQube, which looks like you need to integrate this in travis.

**Comment by javabeanz** [comment]
And what about Coverity , for instance ?  (https://scan.coverity.com/)

**Comment by kroeckx** [comment]
I understand it gets run from a cron job.

**Comment by javabeanz** [comment]
Please try this : https://scan.coverity.com/travis_ci Most other tools integrate with Travis too.

**Comment by kroeckx** [comment]
That would require you to create a special branch for it, which you can push to a few times a day. You can just as well run it from cron.

**Comment by richsalz** [comment]
We do coverity separately, via the free coverity facility.

At this point, what specific recommendations do you have?  Otherwise we can just close this.
