### ISSUE TITLE
Is it possible to configure reproducible random numbers using OpenSSL 3.0?

### ISSUE THREAD

**Issue by ElenaTyuleneva** [openssl/openssl#16784]
Hello!

I'm moving to OpenSSL 3.0 and for testing purposes I need to have the ability to reproduce the values generated by `BN_rand_range`, `EVP_PKEY_keygen` and other functions using the specified seed value.

For the version 1.x.x it could be done manually by implementing a rand engine with stdlib's rand() at its core: https://stackoverflow.com/questions/7437177/force-openssls-rngs-to-return-a-repeatable-byte-sequence

Could you please give me an advise on how it can be done with `EVP_RAND`  API or non-deprecated `RAND_` API?

Thanks,
Elena

**Comment by Majestro000** [comment]
@mattcaswell Can this technique be used to generate deterministic SSL records in tests? (Same payload => same SSL record)
Or are there other dynamic components like time?
