### ISSUE TITLE
Question on loading keys into a provider

### ISSUE THREAD

**Issue by selvanair** [openssl/openssl#16807]
I see two ways of getting an external/opaque key into a provider's keydata and thus into an EVP_PKEY object:

(i)  use the store interface which interacts with `keymgmt_load`
(ii) use a custom set of params and invoke `keymgmt_import` through `EVP_PKEY_fromdata`

Though it seems like the design intent in OpenSSL is to use store for "loading", and import for generating key from fundamental data like n, e, d, I have a situation where the use of store feels and looks awkward. So I use (ii), and the question is whether that's a bad approach. The docs do not seem anticipate such a usage. This is a built-in provider.

The  application has direct access to the certificate, and  signing of messages/digest is done by passing it to a process that also handles user interface, connected via a socket. The application is agnostic about the backend key storage, so there is no store that it "loads" from -- one can cook up a URI for key loading with pointers to an opaque handle and the public key pickled into a string.  Very awkward.

Instead,  I can  define a set of OSSL_PARAMS like: `{.key="pubkey", .data_type=octet_ptr, data=pubkey}`, `{.key="handle", data_type=octet_ptr, data=handle}` etc., plus a parameter to indicate that this is custom data, pass it to `EVP_PKEY_fromdata` and parse the params when it arrives in `keymgmt_import`.

Is there any reason to shy away from this approach and stick to loading via a "uri" and store interface, even if that looks even more fragile?

**Comment by mattcaswell** [comment]
Personally, I don't see a problem with loading a key via import. Import is intended exactly for the situation where all the various parameters are coming in as individual fields. Store is generally intended for scenarios where you are loading from some backend storage mechanism. If you don't have such a thing then no need to artificially invent something. Of course the advantage of store is that you can use the URI for things like the command line apps - which you can't really do for the import mechanism. But maybe that isn't important to you and your application.
