### ISSUE TITLE
If strip at compile test will fail

### ISSUE THREAD

**Issue by gamecss** [openssl/openssl#16810]
if strip at compile (./Configure …… -s …… linux-x86_64), test will fail.

**Comment by gamecss** [comment]
> This indicates what happens:
> 
> > `not ok 4 - check that there are no missing symbols in libssl.so`
> 
> Basically, the consequence of that configuration is that the shared libraries are also stripped of their symbol information, which is sure to render them useless.
> 
> Just to prove the point.
> 
> ```
> $ cp libcrypto.so.3 libcrypto.so.3.stripped
> $ strip libcrypto.so.3.stripped
> $ nm libcrypto.so.3
> [ ... listing of lots of symbols removed ... ]
> $ nm libcrypto.so.3.stripped 
> nm: libcrypto.so.3.stripped: no symbols
> ```
> 
> Simple answer: don't do that.

ubuntu’s openssl (from apt “libssl”) stripped, “$ nm “ not detect symbols, but it working right

**Comment by levitte** [comment]
Hmmm, ok, I can see that I was wrong here

**Comment by levitte** [comment]
Fix in #16822
