### ISSUE TITLE
Building OpenSSL 1.1.0b for android-armeabi under Debian 8.5 x86_64

### ISSUE THREAD

**Issue by atnaguzin** [openssl/openssl#1681]
When I try build version 1.1.0b with [manual](https://wiki.openssl.org/index.php/Android), get that output:
```
arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl/android-9\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot= -Wa,--noexecstack  -march=armv7-a -Wa,--noexecstack -fPIC -c -o crypto/bio/b_addr.o crypto/bio/b_addr.c
In file included from /usr/include/bits/byteswap.h:35:0,
                 from /usr/include/endian.h:60,
                 from /usr/include/bits/string2.h:51,
                 from /usr/include/string.h:635,
                 from crypto/bio/b_addr.c:10:
crypto/bio/b_addr.c: In function 'addr_strings.part.2':
crypto/bio/b_addr.c:229:26: error: invalid 'asm': invalid operand for code 'w'
                          ntohs(BIO_ADDR_rawport(ap)));
                          ^
Makefile:858: recipe for target 'crypto/bio/b_addr.o' failed
make[1]: *** [crypto/bio/b_addr.o] Error 1
make[1]: Leaving directory '/opt/openssl-1.1.0b'
```

Android NDK version - r13

**Comment by dot-asm** [comment]
> arm-linux-androideabi-gcc  ... --sysroot= ...
> In file included from /usr/include/bits/byteswap.h:35:0,

Empty --sysroot means that compiler will try to use headers for the *host* system, which is obviously no match.  As per commentary in Configurations/10-main.cf it takes CROSS_SYSROOT environment variable pointing at proper location [such as /some/where/ndk/platforms/android-14/arch-arm] to get it working. As for referred page, it applies 1.0.x...

**Comment by atnaguzin** [comment]
@dot-asm, thank you!
I added `export CROSS_SYSROOT="$ANDROID_SYSROOT"` in setenv-android.sh, and openssl compiled.

**Comment by atnaguzin** [comment]
@dot-asm, thank you!
I added `export CROSS_SYSROOT="$ANDROID_SYSROOT"` in setenv-android.sh, and openssl compiled.
