### ISSUE TITLE
cannot pass RSA EVP_PKEY to keymgmt

### ISSUE THREAD

**Issue by AntonioSanta** [openssl/openssl#16815]
Hello, I am using Openssl 3.0.
I am not able to pass correctly an RSA key loaded from a .pem file from the store mgmt load() back to the caller and the keymgmt.
What I do in the store load() func is this :

 	    FILE * fp;
	    RSA * rsa;
	    EVP_PKEY * res;
	    rsa = NULL;
	    res = NULL;
	    fp = NULL;
	    OSSL_PARAM params[4];
	    const char rsa_string[4] = "RSA";

        if (!(fp = fopen("pkey.pem", "r")))
        {
            return NULL;
        }
        rsa = RSA_new();
        if (!PEM_read_RSA_PUBKEY(fp, &rsa, NULL, NULL))
        {
            fclose(fp);
            return NULL;
        }
         if (!(res = EVP_PKEY_new()))
         {
             RSA_free(rsa);
             return NULL;
         }

         EVP_PKEY_assign_RSA(res, rsa);

         int object_type = OSSL_OBJECT_PKEY;
         params[0] = OSSL_PARAM_construct_int(OSSL_OBJECT_PARAM_TYPE, &object_type);
     	   char* keytype = rsa_string;
         params[1] = OSSL_PARAM_construct_utf8_string(OSSL_OBJECT_PARAM_DATA_TYPE,
                                               (char *)keytype, 0);
         params[2] =
             OSSL_PARAM_construct_octet_string(OSSL_OBJECT_PARAM_REFERENCE,
                                               &res, sizeof(res));
         params[3] = OSSL_PARAM_construct_end();
     	ret = object_cb(params, object_cbarg);

the obj_cb is the callback call and it's the library's ossl_store_handle_load_result() , I can't change it.
The key object retrieved by the default key manager results in wrong content and then it also clears the original reference to this "res" here .  Is it wrong how I generate the EVP_PKEY and link the rsa struct into it and then package into OSSL_PARAM array to communicate it to the callback by reference ? I don't understand what is wrong. thank you

**Comment by levitte** [comment]
For this to work properly, you must have one of two things:

- a keymgmt in the same provider, which *intimately* understands the reference you're passing with `OSSL_OBJECT_PARAM_REFERENCE`, or...
- an export_object function in your storemgmt implementation, which *intimately* understands the reference you're passing with `OSSL_OBJECT_PARAM_REFERENCE`, and can convert the contents to an OSSL_PARAM array of data suitable for the key type.
