### ISSUE TITLE
TLS connection gets rejected once in a 50-100 iterations when running a loop in 1.1.1 onwards

### ISSUE THREAD

**Issue by shobhit064** [openssl/openssl#16823]
We are  using a multithreaded Openssl server application and a client application , Client is  establishing and breaking the TLS connection to the Server in a while loop , and we have noticed that in Openssl version 1.1.1d the client fails to connect with the server with this  SSL Error "ssl.SSLError: [SSL: BAD_SIGNATURE] bad signature and sometimes the error will be   " routines:ssl3_read_bytes:tlsv1 alert decrypt error' " and then in the other iteration of while loop client is  able to connect again to the server ,this issues is occurring only in 1.1.1 openssl versions occasionally  . but also we have checked in 1.0.2o  Openssl version we haven't seen this issue with more than 500 above iterations.

Please let me know if you need more info on this .

**Comment by mattcaswell** [comment]
No progress can be made here. Closing.
