### ISSUE TITLE
How to compile without deprecated function for windows

### ISSUE THREAD

**Issue by mezen** [openssl/openssl#16835]
I am using OpenSSL on windows as a compiled binary. My application is importing some functions, it is also written in a different language (Delphi).
So I cant get any deprecated warning from the compiler.

To be up to date I want to remove all deprecated functions from the compiled binary and try to import this one. If any imported functions no longer exported I get a error while starting my app.

ATM I am following the steps in https://github.com/openssl/openssl/blob/master/NOTES-WINDOWS.md and use VC:
```
perl Configure VC-WIN32
nmake
nmake test
nmake install
```

**Comment by t8m** [comment]
You could try to configure with no-deprecated.

`perl Configure no-deprecated VC-WIN32`

Then the deprecated functions cannot be used at all.
