### ISSUE TITLE
Unreleased pk->lock in evp_keymgmt_util_export_to_provider

### ISSUE THREAD

**Issue by ryancaicse** [openssl/openssl#16847]
Hi, developers, it seems the lock pk->lock **(Line 171)** is not released correctly when  `!evp_keymgmt_util_cache_keydata(pk, keymgmt, import_data.keydata)`. Should it be a bug, which potentially leads to recursively requiring the same lock?
https://github.com/openssl/openssl/blob/2f61bc17d42bce0d5958cabc971f4f1343353fb3/crypto/evp/keymgmt_lib.c#L171-L207

**Comment by levitte** [comment]
Nice find, fix in #16849

**Comment by ryancaicse** [comment]
Any security impacts with this bug? I guess due to multiple invocations of `evp_keymgmt_util_export_to_provider`, there could be a deadlock vulnerability induced by reacquiring the same lock.

**Comment by ryancaicse** [comment]
@levitte Many thanks for your explanation
