### ISSUE TITLE
OpenSSL 3.0 AES-NI performance regression?

### ISSUE THREAD

**Issue by branch-predictor** [openssl/openssl#16858]
With OpenSSL 3.0 I observe a severe performance degradation with AES when AES-NI (x86/32bit) is enabled.

For OpenSSL 1.1.0k, exact results from ```openssl speed``` are:
- non-EVP:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128 cbc      90320.55k   101336.58k   104107.69k   104910.78k   105305.43k   105294.51k
```
- EVP:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     496224.87k   590151.87k   631356.74k   642255.19k   646064.81k   648134.66k
```
Similar numbers are achievable with 1.1.1x.

With OpenSSL 3.0, things are getting weird:

- non-EVP:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc      85333.38k   100589.55k   105707.18k   107236.01k   107356.16k   107675.65k
```
- EVP:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-128-CBC      80014.09k    96027.24k   102592.94k   104554.50k   105130.67k   105168.90k
```
- EVP, with AES-NI disabled via ```OPENSSL_ia32cap``` env variable:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-128-CBC      85086.77k   102448.28k   107379.54k   203026.43k   203729.58k   204204.71k
```

All numbers are taken on same machine (Intel Core I3-4130t on Windows 8.1 x64 with 32-bit OpenSSL) , I tried different builds from different sources (SLProWeb builds, builds provided by ICS project, my own builds) but the results are the same. 

Is that a regression or using AES-NI with EVP now requires more steps to use correct implementation?

**Comment by branch-predictor** [comment]
There seems to be regression in just 32-bit code path, with OpenSSL 3.0 64-bit, I get the following numbers:

- non-EVP:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     505591.60k   606394.90k   639612.25k   647947.95k   650521.26k   650930.86k
```
- EVP
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-128-CBC     426434.65k   575840.30k   630705.83k   645863.77k   650507.61k   650952.70k
```
- EVP with AES-NI disabled via env var:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-128-CBC      96913.64k   118563.50k   125189.55k   273897.36k   280608.77k   281040.21k
```

Although I find it surprising that non-EVP version is that fast on x86/32.

**Comment by t8m** [comment]
How do you Configure the 32bit build?

Could you please paste here `./configdata.pm -d` output?

**Comment by branch-predictor** [comment]
The same as ```VC-WIN32``, the only thing that differs is /MD switch forced. But that's irrelevant, I observe the same behavior with different builds which use 100% stock configurations.
