### ISSUE TITLE
Some uses of DES miscompute with OpenSSL 3.0.0

### ISSUE THREAD

**Issue by solardiz** [openssl/openssl#16859]
I am concerned that OpenSSL's deprecation of DES appears to cause silent miscomputation, which e.g. in JtR we only detect due to our runtime tests against our included test vectors:

https://github.com/openwall/john/issues/4831#issuecomment-945964561

Wouldn't in some other application this result in encryption silently becoming a no-op, which is generally a lot worse than 3DES?

**Comment by mattcaswell** [comment]
It should not cause silent miscomputation? It's unclear from the linked comment where you think the silent miscomputation is happening. Can you be more specific?

Two things have changed wrt DES in 3.0:

- DES APIs are deprecated. This should have no functional impact if you still use these APIs other than lots of deprecation warnings.
- Moving of the EVP DES implementation into the legacy provider. This latter case only impacts you if you were using DES via EVP (e.g. EVP_EncryptInit, EVP_DecryptInit, etc). In this case the "init" calls should fail if you haven't loaded the legacy provider.

**Comment by t8m** [comment]
> it previously had unreachable and thus untested code and behavior there

It was reachable if the global variable was set to check.

**Comment by t8m** [comment]
The third option is implemented in #16944
IMO it is the correct way.

**Comment by solardiz** [comment]
> > it previously had unreachable and thus untested code and behavior there
> 
> It was reachable if the global variable DES_check_key was set to check.

I meant applications that didn't set this flag, which I guess are the majority. Some of those might nevertheless (in some places) check the return value from `DES_set_key`.

**Comment by paulidale** [comment]
OTC: we will fix the timing attacks in another PR.
