### ISSUE TITLE
ARM64 openssl 1.1.0 stable build failed: engines/afalg/e_afalg.c:107 error: '__NR_eventfd' undeclared

### ISSUE THREAD

**Issue by baiyz** [openssl/openssl#1685]
gcc  -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread  -Wa,--noexecstack -fPIC -MMD -MF engines/afalg/e_afalg.d.tmp -MT engines/afalg/e_afalg.o -c -o engines/afalg/e_afalg.o engines/afalg/e_afalg.c
engines/afalg/e_afalg.c: In function 'eventfd':
engines/afalg/e_afalg.c:107:20: error: '__NR_eventfd' undeclared (first use in this function)
     return syscall(__NR_eventfd, n);
                    ^
engines/afalg/e_afalg.c:107:20: note: each undeclared identifier is reported only once for each function it appears in
engines/afalg/e_afalg.c:108:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:6033: recipe for target 'engines/afalg/e_afalg.o' failed
make[1]: *** [engines/afalg/e_afalg.o] Error 1
make[1]: Leaving directory '/root/openssl/test1/openssl-test1'
Makefile:124: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by baiyz** [comment]
engines/afalg/e_afalg.c:107

static ossl_inline int eventfd(int n)
{
    return syscall(__NR_eventfd, n);       ---> not defined on arm64, maybe use __NR_eventfd2 instead?
}

**Comment by baiyz** [comment]
Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:05:42 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux

Ubuntu Xenial 16.04
libc6-dev: arm64, 2.23-0ubuntu3
linux-image-4.4.0-36-generic: arm64, 4.4.0-36.55

processor	: 47
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
CPU implementer	: 0x43
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x0a1
CPU revision	: 0

**Comment by mattcaswell** [comment]
Try using no-afalgeng during configure

**Comment by baiyz** [comment]
Thanks, ./config no-afalgeng works

**Comment by mattcaswell** [comment]
Ok. Closing.

**Comment by vielmetti** [comment]
I just ran into this problem, and was able to resolve it with the use of this item.

Shouldn't `configure` pick this up on its own?

**Comment by vadim-a-yegorov** [comment]
Changing __NR_eventfd to __NR_eventfd2 works well, successfully installed OpenSSL 1.1.0 on ARM

**Comment by lie-thorn** [comment]
编辑OpenSSL 1.1.0源码目录中的engines/afalg/e_afalg.c，将__NR_eventfd更改为__NR_eventfd2成功在ARM上安装了OpenSSL 1.1.0
