### ISSUE TITLE
OpenSSL 1.1.1l: verification problem of expired 'DST Root CA X3' certificate

### ISSUE THREAD

**Issue by epbk** [openssl/openssl#16861]
I have verification problem of expired 'DST Root CA X3' certificate in my C# application on Win7.

If the external certification bundle file is loaded then there is no problem. I have received 3 verification callbacks from openssl.
All 3 certificates are preverified by openssl. No need to verify them via Win store.

Certificate: Issuer:'ISRG Root X1' Subject:'ISRG Root X1'
Certificate: Issuer:'ISRG Root X1' Subject:'R3'
Certificate: Issuer:'R3' Subject:'somedomain.com'

If the external certification bundle file is not loaded then first verification callback is this:
Certificate: Issuer:'DST Root CA X3' Subject:'ISRG Root X1'

Win store reports that certificate is expired.

If I return 0 (as I should) it leeds to handshake failure.

If I ignore the error then I receive next 2 callbacks:

Certificate: Issuer:'ISRG Root X1' Subject:'R3'
Certificate: Issuer:'R3' Subject:'somedomain.com'

Both certificates are properly verified by Win store. So handshake is complete.

Here is the question: I'm doing something wrong during verification of expired 'DST Root CA X3' certificate or there is a bug in Open SSL?

**Comment by t8m** [comment]
> If I understand correctly, the openssl doesn't know the alternative chain path so I have to take a look for another root certificate with the same Subject and PublicKey in Win store and check it in X509Chain.

Yeah, that would work.
