### ISSUE TITLE
Brainpool curves for TLS 1.3 in OpenSSL 3.x (RFC8734)

### ISSUE THREAD

**Issue by fschmidberger** [openssl/openssl#16863]
What is the current status of brainpool curves (RFC8734, 31-33) for TLS 1.3 in OpenSSL 3.x

**Comment by bernd-edlinger** [comment]
Probably yes, but it is not really simple to make that work in the OpenSSL 3.x version.
At the moment the brain-pool support is only available in my 1.1.1 feature-branch #11900

**Comment by fschmidberger** [comment]
@bernd-edlinger thx a lot!
