### ISSUE TITLE
build master and openssl-1.0.2-stable failed on windows with msvc.

### ISSUE THREAD

**Issue by zhaozg** [openssl/openssl#169]
perl Configure VC-WIN32 --prefix=..\master
ms\do_ms
nmake -f ms\nt.mak

>> if replace ms\do_ms with ms\do_nt, fail same.
>>but build with nasm sucessful

```
...
        perl crypto\sha\asm\sha1-586.pl win32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS
  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_
MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL
_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -
DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH
_ASM -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOP
ENSSL_NO_DYNAMIC_ENGINE >tmp32\sha1-586.asm
        ml /nologo /Cp /coff /c /Cx /Zi /Fotmp32\sha1-586.obj tmp32\sha1-586.asm

 Assembling: tmp32\sha1-586.asm
tmp32\sha1-586.asm(1432) : error A2070:invalid instruction operands
tmp32\sha1-586.asm(1576) : error A2070:invalid instruction operands
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 10.
0\VC\BIN\ml.EXE"”: 返回代码“0x1”
Stop.
```

**Comment by schlenk** [comment]
Does not work with Visual Studio 2008 + NASM either.
NASM version 2.11.06 compiled on Oct 20 2014
This is perl 5, version 12, subversion 0 (v5.12.0) built for MSWin32-x86-multi-thread
cl /version
Microsoft (R) 32-Bit C/C++-Optimierungscompiler Version 15.00.30729.01 für 80x86

        perl crypto\sha\asm\sha1-586.pl win32 -DOPENSSL_NO_HEARTBEATS -DOPENSSL_NO_COMP  /MD /Ox /O2 /Ob2 -DOPENSSL_THRE
ADS  -DDSO_WIN32 -DOPENSSL_NO_HEARTBEATS -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDI
AN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2
m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSS
L_USE_APPLINK -I. -DOPENSSL_NO_IDEA -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_SSL3 -DOPENSSL_NO_K
RB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_STATIC_ENGINE >tmp32dll\sha1-586.asm
        ml /nologo /Cp /coff /c /Cx /Zi /Fotmp32dll\sha1-586.obj tmp32dll\sha1-586.asm
 Assembling: tmp32dll\sha1-586.asm
tmp32dll\sha1-586.asm(1427) : error A2070:invalid instruction operands
tmp32dll\sha1-586.asm(1571) : error A2070:invalid instruction operands
NMAKE : fatal error U1077: ""c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\ml.EXE"": Rückgabe-Code "0x1"
Stop.
'nmake -f ms\ntdll.mak' failed to execute, returncode 2

**Comment by mattcaswell** [comment]
Are you sure you are actually using NASM? You are calling ms\do_nasm right?
See this thread:
https://mta.openssl.org/pipermail/openssl-dev/2015-January/000329.html

**Comment by akallabeth** [comment]
Got the same issue here, 64 bit builds fine, 32bit builds fail.
Have a jenkins setup that previously worked well for both, 32 and 64 bit builds.
```s/do_nasm``` is called, 1.0.1l builds fine with the same configuration.

**Comment by schlenk** [comment]
Ah. Probably found my issue. 1.0.1l allowed to call ms\do_nasm.bat followed by ms\do_ms.bat and it worked. This fails with 1.0.2. But just calling ms\do_nasm.bat without an extra do_ms.bat afterwards seems to work.

**Comment by parthibdutta** [comment]
I am having the same problem too . ml.exe gives the same invalid operands error . Does anyone know any fix for MASM ?

**Comment by mattcaswell** [comment]
NASM is the only supported assembler, as per:
https://github.com/openssl/openssl/blob/master/INSTALL.W32

Nonetheless, Andy Polyakov has shown some willingness to look at this issue. See the thread I linked above and:
https://rt.openssl.org/Ticket/Display.html?id=3650&user=guest&pass=guest

An email to openssl-dev replying to that thread or RT ticket may get a response from Andy.

**Comment by parthibdutta** [comment]
Thanks a lot . The build was successful with NASM . I guess MASM is no longer supported . It doesn't matter as long as it gets the job done .

**Comment by mattcaswell** [comment]
Closing this issue as per comments above.

**Comment by mayankessar** [comment]
I am still getting the issue:
Assembling: tmp32dll\sha1-586.asm
 tmp32dll\sha1-586.asm(1427) : error A2070:invalid instruction operands
 tmp32dll\sha1-586.asm(1571) : error A2070:invalid instruction operands
 NMAKE : fatal error U1077: ""c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\ml.EXE"":
 Rückgabe-Code "0x1"
 Stop.

Visual Studio 2008
Active Perl latest
NASM latest version

Can somebody tell me is there any specific changes required with NASM. Please help.

**Comment by mattcaswell** [comment]
Please open this as a new issue and include a few of the lines prior to this error for context.

**Comment by ngjermundshaug** [comment]
@mattcaswell  I got it to work (1.0.2h) by using NASM - like people above said. 

Here's exactly what to do:

* Extract the source code to a new clean folder - failed appempts seem to leave a lot of crap
* Download Nasm.exe if you don't already have it - http://www.nasm.us/. Just put it in C:\Windows\System32 (or in your path)
* Start the VS2012 X86 Command prompt - and run the following:

    "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
    perl Configure VC-WIN32 --prefix=C:\Build-OpenSSL-VC-32
    ms\do_nasm.bat
    nmake -f ms\nt.mak
    nmake -f ms\nt.mak install
