### ISSUE TITLE
openssl-env missing variables

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#16903]
A quick check shows at least the following are not documented in openssl-env(7)
- OPENSSL_ia32cap
- OPENSSL_sparcv9cap
- OPENSSL_ppccap
- OPENSSL_armcap
- OPENSSL_s390xcap
- ~OPENSSL_malloc_failures~
- ~OPENSSL_malloc_fd~
- NO_PROXY
- HTTPS_PROXY
- HTTP_PROXY

Some of those have existing manpages that can be pointed to.

**Comment by paulidale** [comment]
The malloc ones are documented although in uppercase not lower.

**Comment by paulidale** [comment]
Added three additional HTTP related environment variables.
Also fixed the type in the SPARCv9 variable.

**Comment by paulidale** [comment]
#17044 documents: OPENSSL_ia32cap, OPENSSL_s390xcap, NO_PROXY, HTTPS_PROXY, HTTP_PROXY

Leaving:
- OPENSSL_sparcv9cap
- OPENSSL_ppccap
- OPENSSL_armcap

These have been added but there is no link to the gory details.

**Comment by paulidale** [comment]
With #17044 merged, the only remaining ones are covered by separate issues.  I think this issue can be closed at this point.
Anyone else agree?

**Comment by kroeckx** [comment]
Fine for me
