### ISSUE TITLE
Remove unused variable 'sctx'

### ISSUE THREAD

**Issue by JiangJias** [openssl/openssl#16908]
In the openssl-3.0.0 and system provided, the variable 'sctx' is unused in test_509_dup_cert. Therefore,
it might be better to remove the definition and operation of it.

Fixes: c045224 ("Ignore dups in X509_STORE_add_*")
Signed-off-by: Jiasheng Jiang <jiasheng@iscas.ac.cn>
---
 test/x509_dup_cert_test.c | 2 --
 1 file changed, 2 deletions(-)

diff --git a/test/x509_dup_cert_test.c b/test/x509_dup_cert_test.c
index af35afb..b09de70 100644
--- a/test/x509_dup_cert_test.c
+++ b/test/x509_dup_cert_test.c
@@ -17,7 +17,6 @@
```
 static int test_509_dup_cert(int n)
 {
     int ret = 0;
-    X509_STORE_CTX *sctx = NULL;
     X509_STORE *store = NULL;
     X509_LOOKUP *lookup = NULL;
     const char *cert_f = test_get_argument(n);
```
@@ -28,7 +27,6 @@ static int test_509_dup_cert(int n)
```
         && TEST_true(X509_load_cert_file(lookup, cert_f, X509_FILETYPE_PEM)))
         ret = 1;
 
-    X509_STORE_CTX_free(sctx);
     X509_STORE_free(store);
     return ret;
 }
```
-- 
2.7.4

**Comment by paulidale** [comment]
This was fixed by #16916
