### ISSUE TITLE
SipHash regression in 3.0.0

### ISSUE THREAD

**Issue by orignal** [openssl/openssl#16936]
Following code produces different results with openssl 1.1.1 and with openssl 3.0.0.  
Basically it calculates SipHash with digest size 8.

1.1.1 produces: 6d 3e 54 c2 2f f1 fe e2
3.0.0 produces: 1e a3 02 13 d5 82 56 89

`  

    uint8_t key[16];   
    memset (key, 1, 16); 
    EVP_PKEY * sipKey = EVP_PKEY_new_raw_private_key (EVP_PKEY_SIPHASH, NULL, key, 16);
    EVP_MD_CTX * mdCtx = EVP_MD_CTX_create ();
    EVP_PKEY_CTX * ctx = NULL;
    EVP_DigestSignInit (mdCtx, &ctx, NULL, NULL, sipKey);
    EVP_PKEY_CTX_ctrl (ctx, -1, EVP_PKEY_OP_SIGNCTX, EVP_PKEY_CTRL_SET_DIGEST_SIZE, 8, NULL);
    EVP_PKEY_free (sipKey);

    uint8_t buf[8], digest[8];
    memset (buf, 0, 8);
    EVP_DigestSignInit (mdCtx, NULL, NULL, NULL, NULL);
    EVP_DigestSignUpdate (mdCtx, buf, 8);
    size_t l = 8;
    EVP_DigestSignFinal (mdCtx, digest, &l);
`

**Comment by paulidale** [comment]
The best way would be to use the new EVP_MAC API.

**Comment by kroeckx** [comment]
We did not deprecate that usage. Even if we did, I'd still expect
it to keep working as in 1.1.1.

The behavior does not seem to be documented in the manpage.

**Comment by paulidale** [comment]
Call `EVP_DigestSignInit (mdCtx, NULL, NULL, NULL, NULL);` after the `EVP_DigestSignFinal` call.

**Comment by orignal** [comment]
That's what I do now, it works in 1.1.1 and doesn't work in 3.0.0.
If I don't call EVP_DigestSignInit as @mattcaswell suggests, it works for the first digest and doesn't for next digests.

**Comment by paulidale** [comment]
This produces the correct output thrice:
```C
#include <openssl/evp.h>
#include <string.h>
#include <stdlib.h>

int main() {
    uint8_t key[16];   
    memset (key, 1, 16); 
    EVP_PKEY * sipKey = EVP_PKEY_new_raw_private_key (EVP_PKEY_SIPHASH, NULL, key, 16);
    EVP_MD_CTX * mdCtx = EVP_MD_CTX_create ();
    EVP_PKEY_CTX * ctx = NULL;

    EVP_DigestSignInit (mdCtx, &ctx, NULL, NULL, sipKey);
    EVP_PKEY_CTX_ctrl (ctx, -1, EVP_PKEY_OP_SIGNCTX, EVP_PKEY_CTRL_SET_DIGEST_SIZE, 8, NULL);
    EVP_PKEY_free (sipKey);
    int i;
    for (i=0; i<3; i++) {
        uint8_t buf[8], digest[8];
        memset (buf, 0, 8);
        EVP_DigestSignUpdate (mdCtx, buf, 8);
        size_t l = 8;
        EVP_DigestSignFinal (mdCtx, digest, &l);
        EVP_DigestSignInit (mdCtx, NULL, NULL, NULL, NULL);
        BIO_dump_fp(stdout, digest, l);
    }
    return 0;
}
```

**Comment by orignal** [comment]
This code works in 3.0.0, but not in 1.1.1. Is it right?

**Comment by paulidale** [comment]
It works with 1.1.1f as well as 3.0.

**Comment by t8m** [comment]
This was actually fixed by #16422. @orignal could you please test the current openssl-3.0 branch with your code to verify?

**Comment by t8m** [comment]
> This was actually fixed by #16789 . @orignal could you please test the current openssl-3.0 branch with your code to verify?

Hmm, actually not.

**Comment by t8m** [comment]
Both the original and @paulidale testcases are incorrect because they do not check the return value. And the #16789 actually makes the second and third iterations to fail the EVP_DigestSignFinal() call meaning the hash value calculated from the first iteration is always printed out.

**Comment by paulidale** [comment]
This is what's happening :(
