### ISSUE TITLE
error:141A20F4:SSL routines:ossl_statem_server_read_transition:unexpected message:ssl/statem/statem_srvr.c:313

### ISSUE THREAD

**Issue by madhanreddy433** [openssl/openssl#16933]
when I try to test openssl connectivity getting below error

----------------------------------------------                             .......
ERROR
140054065153856:error:141A20F4:SSL routines:ossl_statem_server_read_transition:unexpected message:ssl/statem/statem_srvr.c:313:
shutting down SSL
CONNECTION CLOSED

-----------------------------------------------
running below commands 
./openssl s_server -accept 7681 -cert <cert path> -key <key file path> -debug

./openssl s_client -connect <server ip>:7681

Could anyone help me out with this?

**Comment by madhanreddy433** [comment]
If I run server and client on same box with any openssl version(openssl-1.0.1k, 1.0.2q, 1.0.2u), it is working fine .

I am facing an issue with "10.177.125.155" only. If I Install openssl-1.0.1k on this device, I am not facing the connectivity issue but if I change the version to openssl-1.0.2q or openssl-1.0.2u, I am facing connectivity issue.

we are not running any firewalls on this device. I wonder how it is working with openssl-1.0.1k.

**Comment by madhanreddy433** [comment]
on same setup if I use OpenSSL 1.1.1l 24 Aug 2021, it is working fine. what is the issue with openssl-1.0.2q?
with openssl-1.0.2q, if I use tls1_1 also it is working fine.
./openssl s_client -connect 10.176.6.62:7681 **-tls1_1**

do we have any issue with 1.0.2q and tls1_2?

**Comment by madhanreddy433** [comment]
when I use openssl-1.0.2q or 1.0.2u or 1.1.0k, client is not negotiating with server with default tls1_2 but with tls1_1 it is negotiating and establishing connection.

./openssl s_client -connect 10.176.6.62:7681  //connection is failing with below errors
on server
ERROR
140410523703104:error:141A20F4:SSL routines:ossl_statem_server_read_transition:unexpected message:ssl/statem/statem_srvr.c:232:
shutting down SSL
CONNECTION CLOSED

on client
verify return:1
4150571008:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:ssl/record/rec_layer_s3.c:1407:SSL alert number 10

./openssl s_client -connect 10.176.6.62:7681 -tls1_1   //this is negotiating and establishing connection


if I use openssl-1.1.1l, then it is working fine with default tls1_2.

could you please let me know why it is not working with other versions and working with 1.1.1l, anything is fixed on 1.1.1l?if yes, could you please share me the patch?

**Comment by t8m** [comment]
I am sorry but 1.0.2 versions are unsupported, or to be more specific they are supported only to premium support customers. Also the 1.0.2q version is an old fix release.

**Comment by madhanreddy433** [comment]
what about 1.1.0k?
could you please let me know why these versions are not negotiating with server?

**Comment by t8m** [comment]
1.1.0 is unsupported as well.

**Comment by mattcaswell** [comment]
One significant change between 1.1.1 and earlier versions is that SNI is enabled by default when using s_client, but in earlier versions it was not. I don't see why that would make a difference when s_client and s_server are talking to each other...but still it is a significant change in 1.1.1.

You say that 1.1.1l works. What happens if you use 1.1.1l and pass the "-noservername" option in the s_client command line (in order to suppress SNI)? Does it still work or does it stop working? If it stops working then it might suggest that something related to SNI is causing the problem.
