### ISSUE TITLE
XOF interface is unsuitable for truncated MACs

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16934]
Related: https://github.com/gost-engine/engine/issues/359

We have provider-converted GOST OMACs that could produce output from 1 to block_size length. We use the XOF interface for the MAC value. 

Specifying a truncation to 8 bytes and passing 8-byte buffer for 16-byte Kuznyechik-based MAC, we get an error
```
806BEB56E77F0000:error:0300009B:digital envelope routines:evp_mac_final:buffer too small:crypto/evp/mac_lib.c:156:
/home/dbelyavs/upstream/engine/test_digest.c:666: OpenSSL internal error: EVP_MAC_finalXOF(ctx, out, outsize)
```
The problem reveals with current master. I used the Clang 12.0.1 for 64 bit linux to see it (no problems with GCC/Clang11).

**Comment by mouse07410** [comment]
If you don't mind me asking - any updates?

**Comment by beldmit** [comment]
Not yet, unfortunately.

**Comment by beldmit** [comment]
Looks like it can and should be fixed on GOST provider side

**Comment by mattcaswell** [comment]
@beldmit - can we close this issue?

**Comment by beldmit** [comment]
I think yes. I'll try to look at it next Wednesday from the provider's side.
