### ISSUE TITLE
Definition of real seconds

### ISSUE THREAD

**Issue by hengyongming** [openssl/openssl#16932]
![image](https://user-images.githubusercontent.com/65388283/139191214-c94af10d-115c-4378-acd4-c5e3990003f5.png)

I am using the openssl s_time function to measure the performance of TLS connection.
However, I am unsure about the definition of real seconds.
I searched online and some sources stated that it is the number of seconds the CPU is being utilized.
Is this interpretation correct?

Thanks in advance!

**Comment by levitte** [comment]
Then begs the question, what are the 26.07 seconds...

**Comment by hengyongming** [comment]
@mattcaswell yep I have the same qn as @levitte

**Comment by mattcaswell** [comment]
26.07 seconds is "user time", i.e. the amount of time spent in user mode in this process. So 31 seconds elapsed. The processor spent 4.93 seconds doing other things, and 26.07 seconds actually doing s_time stuff.
