### ISSUE TITLE
Fails to build on cortex-a32/armv8a+crc platforms

### ISSUE THREAD

**Issue by rossburton** [openssl/openssl#16949]
When building for our Corstone700 platform, which has the following compiler flags:

```
arm-poky-linux-gnueabi-gcc  -mcpu=cortex-a32 -march=armv8-a+crc -mfpu=neon -mfloat-abi=hard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/yocto/ross/build/tmp/work/cortexa32hf-neon-poky-linux-gnueabi/openssl/3.0.0-r0/recipe-sysroot} -pthread -Wa,--noexecstack -O2 -pipe -g -feliminate-unused-debug-types -L.  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -Wl,-z,relro,-z,now
```

The link fails with lots of errors along these lines:

```
ld: ./libcrypto.so: undefined reference to `aes_gcm_dec_128_kernel'
ld: libcrypto.a(libdefault-lib-cipher_aes_gcm_hw.o): in function `armv8_aes_gcm_decrypt':
openssl-3.0.0/providers/implementations/ciphers/cipher_aes_gcm_hw_armv8.inc:50: undefined reference to `aes_gcm_dec_192_kernel'
```

Guessing the feature detection isn't entirely complete, and some code isn't being compiled but still being called.

**Comment by rossburton** [comment]
Looks like the problem is that my `-march` explicitly doesn't include the crypto instructions, so there must be some missing check in the build?

**Comment by rossburton** [comment]
Changing my flags to `-mcpu=cortex-a32 -march=armv8-a+crc+crypto -mfpu=neon` still results in the same failure, so either `-mcpu` is overriding or something else is happening.

**Comment by tom-cosgrove-arm** [comment]
@rossburton Thanks for reporting - fix upstreamed
