### ISSUE TITLE
Why OpenSSL and not OpenTLS?

### ISSUE THREAD

**Issue by tessus** [openssl/openssl#16959]
Afaik SSL is no longer used by anyone. I am not even sure, if there's still SSL code in OpenSSL.

I know that many people use the term SSL interchangeably with TLS, but maybe it's time to break with that sentiment.
On the other hand I understand that using a protocol in a product name can be tricky: trademarks, web pages, documentation, ... 

What happens, if TLS is superseeded by something else? I did look at the FAQ, but didn't find an entry, so please forgive me by asking here.

**Comment by mattcaswell** [comment]
> I am not even sure, if there's still SSL code in OpenSSL.

There is.

> I know that many people use the term SSL interchangeably with TLS, but maybe it's time to break with that sentiment.
On the other hand I understand that using a protocol in a product name can be tricky: trademarks, web pages, documentation, ...
>
> What happens, if TLS is superseeded by something else? I did look at the FAQ, but didn't find an entry, so please forgive me by asking here.

This has been discussed and rejected previously. See the comments in #6384 and #10830. I don't think anything has changed since then, and I don't think there is any appetite to make this disruptive change.

**Comment by tessus** [comment]
Thanks a lot for your reply.

> There is.

Maybe it's time to remove it. ;-) Besides the fact that unused code is maintenance overhead, it might also be a vector for adversaries. Or is there a valid reason to allow people to use SSL? Besides pen-testing and whatnow, but in this case the pen-tester should maintain a separate fork.

> make this disruptive change

I understand, especially if TLS might be replaced at one point. How about using something more generic then? e.g. OpenCrypto or OpenSecLayer.

Either way, I thank you for the links and your answer. I'll close this, since I'm sure you have more important things to do than discussing a topic you are probably tired of. Cheers.
