### ISSUE TITLE
OpenSSL 3.1 fails to test on NonStop x86 with enable-fips

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#16950]
At commit a87c3247ca, the nonstop-nsx configuration fails its FIPS install test - it looks like there is a significant cypher test failure.

### Test Results:
```
$ make test
make[1]: Entering directory '/home/ituglib/randall/openssl-3.0'
make[1]: Leaving directory '/home/ituglib/randall/openssl-3.0'
make[1]: Entering directory '/home/ituglib/randall/openssl-3.0'
( SRCTOP=. \
  BLDTOP=. \
  PERL="perl" \
  FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
  EXE_EXT= \
  perl ./test/run_tests.pl  )
00-prep_fipsmodule_cnf.t ..
# The results of this test will end up in test-runs/prep_fipsmodule
1..1
HMAC : (Module_Integrity) : Pass
SHA1 : (KAT_Digest) : Pass
SHA2 : (KAT_Digest) : Pass
SHA3 : (KAT_Digest) : Pass
TDES : (KAT_Cipher) : Pass
AES_GCM : (KAT_Cipher) : Pass
AES_ECB_Decrypt : (KAT_Cipher) : Pass
RSA : (KAT_Signature) : Fail
ECDSA : (PCT_Signature) : Fail
ECDSA : (PCT_Signature) : Fail
DSA : (PCT_Signature) : Fail
TLS13_KDF_EXTRACT : (KAT_KDF) : Pass
TLS13_KDF_EXPAND : (KAT_KDF) : Pass
TLS12_PRF : (KAT_KDF) : Pass
PBKDF2 : (KAT_KDF) : Pass
SSHKDF : (KAT_KDF) : Pass
KBKDF : (KAT_KDF) : Pass
HKDF : (KAT_KDF) : Pass
SSKDF : (KAT_KDF) : Pass
X963KDF : (KAT_KDF) : Pass
X942KDF : (KAT_KDF) : Pass
HASH : (DRBG) : Pass
CTR : (DRBG) : Pass
HMAC : (DRBG) : Pass
DH : (KAT_KA) : Pass
ECDH : (KAT_KA) : Fail
RSA_Encrypt : (KAT_AsymmetricCipher) : Pass
RSA_Decrypt : (KAT_AsymmetricCipher) : Fail
RSA_Decrypt : (KAT_AsymmetricCipher) : Fail
Failed to load FIPS module
INSTALL FAILED
00000000:error:1C8000D5:Provider routines:SELF_TEST_post:missing config data:/home/ituglib/randall/openssl-3.0/providers/fips/self_test.c:289:
00000000:error:1C8000E0:Provider routines:ossl_set_error_state:fips module entering error state:/home/ituglib/randall/openssl-3.0/providers/fips/self_test.c:387:
00000000:error:1C8000D8:Provider routines:OSSL_provider_init_int:self test post failure:/home/ituglib/randall/openssl-3.0/providers/fips/fipsprov.c:706:
00000000:error:078C0105:common libcrypto routines:provider_init:init fail:/home/ituglib/randall/openssl-3.0/crypto/provider_core.c:903:name=fips
../../util/wrap.pl ../../apps/openssl fipsinstall -module ../../providers/fips.so -provider_name fips -section_name fips_sect -out ../../test/fipsmodule.cnf => 1
not ok 1 - fips install

#   Failed test 'fips install'
#   at test/recipes/00-prep_fipsmodule_cnf.t line 33.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
00-prep_fipsmodule_cnf.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  2 wallclock secs ( 0.02 usr  0.00 sys +  0.62 cusr  0.00 csys =  0.65 CPU)
Result: FAIL
Died at ./test/run_tests.pl line 312.
Makefile:1535: recipe for target 'run_tests' failed
make[1]: *** [run_tests] Error 1
make[1]: Leaving directory '/home/ituglib/randall/openssl-3.0'
Makefile:1532: recipe for target 'tests' failed
make: *** [tests] Error 2
```
### Configuration:
Command line (with current working directory = .):

    perl ./Configure nonstop-nsx enable-fips

Perl information:

    perl
    5.26.3 for NSV-D-nonstop_kernel

Enabled features:

    acvp-tests
    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    egd
    engine
    err
    filenames
    fips
    fips-securitychecks
    gost
    idea
    legacy
    loadereng
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    asm                 [no asm_arch]    OPENSSL_NO_ASM
    buildtest-c++       [default]
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [default]        OPENSSL_NO_KTLS
    makedepend          [unavailable]
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]        OPENSSL_NO_SCTP
    threads             [config]
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]
    zlib-dynamic        [default]
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "qc",
    CC => "c99",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    bn_ops => "THIRTY_TWO_BIT",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-g -O2 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_neutral_library -Wverbose -Wtarget=tns/x -Wsystype=oss -Wilp32 -WIEEE_float",
    cppflags => "",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "OPENSSL_VPROC=\$(OPENSSL_VPROC)", "_XOPEN_SOURCE", "_XOPEN_SOURCE_EXTENDED=1", "_TANDEM_SOURCE", "B_ENDIAN", "_TANDEM_ARCH=3" ],
    disable => [ "threads" ],
    dso_scheme => "DLFCN",
    enable => [ "egd" ],
    ex_libs => "-lrld",
    includes => [  ],
    lflags => "-Wxld=\"-set systype oss\" -Wxld=\"-set floattype ieee_float\"",
    lib_cflags => "",
    lib_cppflags => "",
    lib_defines => [  ],
    module_cflags => "",
    module_cxxflags => undef,
    module_ldflags => "-Wshared",
    perl => "/usr/bin/perl",
    perl_platform => "Unix",
    shared_argfileflag => "-Wxld_obey=",
    shared_cflag => "",
    shared_defflag => "-Wxld_obey=",
    shared_defines => [  ],
    shared_extension => ".so",
    shared_ldflag => "-Wshared",
    shared_rcflag => "",
    shared_target => "nonstop-shared",
    sys_id => "TANDEM",
    thread_defines => [  ],
    thread_scheme => "(unknown)",
    unistd => "<unistd.h>",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = ar
    ARFLAGS         = qc
    CC              = c99
    CFLAGS          =
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          =
    PERL            = perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl

**Comment by rsbeckerca** [comment]
User error. Forgot to build with the `rdcpu` randomness.

**Comment by rsbeckerca** [comment]
Actually, there is an issue here:

```
04-test_encoder_decoder.t .......... 1/?
../../util/wrap.pl ../../test/endecode_test -rsa ../../test/certs/ee-key.pem -pss ../../test/certs/ca-pss-key.pem -context -config ../../test/default.cnf -provider default => 139
not ok 2
04-test_encoder_decoder.t .......... 3/? ---------------------------------------
04-test_encoder_decoder.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests
```

**Comment by mattcaswell** [comment]
Looks like a possible crash? Are you able to run the command line given in the test output manually to see what happens?

**Comment by rsbeckerca** [comment]
Interesting result:
```
In /home/ituglib/randall/openssl-3.0/test/recipes:
$ ../../util/wrap.pl ../../test/endecode_test -rsa ../../test/certs/ee-key.pem -pss ../../test/certs/ca-pss-key.pem -context -config ../../test/default.cnf -provider default
# INFO:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:1334
# Generating keys...
# INFO:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:1337
# Generating DH keys...
# INFO:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:1342
# Generating DSA keys...
# INFO:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:1346
# Generating EC keys...
# INFO:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:1359
# Loading RSA key...
# INFO:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:1361
# Loading RSA_PSS key...
# INFO:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:1363
# Generating keys done
1..114
ok 1 - test_unprotected_DH_via_DER
ok 2 - test_unprotected_DH_via_PEM
ok 3 - test_protected_DH_via_DER
ok 4 - test_protected_DH_via_PEM
ok 5 - test_public_DH_via_DER
ok 6 - test_public_DH_via_PEM
ok 7 - test_params_DH_via_DER
ok 8 - test_params_DH_via_PEM
ok 9 - test_unprotected_DHX_via_DER
ok 10 - test_unprotected_DHX_via_PEM
ok 11 - test_protected_DHX_via_DER
ok 12 - test_protected_DHX_via_PEM
ok 13 - test_public_DHX_via_DER
ok 14 - test_public_DHX_via_PEM
ok 15 - test_params_DHX_via_DER
ok 16 - test_params_DHX_via_PEM
ok 17 - test_unprotected_DSA_via_DER
ok 18 - test_unprotected_DSA_via_PEM
ok 19 - test_protected_DSA_via_DER
ok 20 - test_protected_DSA_via_PEM
ok 21 - test_public_DSA_via_DER
ok 22 - test_public_DSA_via_PEM
ok 23 - test_params_DSA_via_DER
ok 24 - test_params_DSA_via_PEM
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:632
# Test not available if using a non-default library context or FIPS provider
ok 25 - test_unprotected_DSA_via_legacy_PEM # skipped
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:753
# Test not available if using a non-default library context or FIPS provider
ok 26 - test_protected_DSA_via_legacy_PEM # skipped
ok 27 - test_unprotected_DSA_via_MSBLOB
ok 28 - test_public_DSA_via_MSBLOB
ok 29 - test_unprotected_DSA_via_PVK
ok 30 - test_protected_DSA_via_PVK
ok 31 - test_unprotected_EC_via_DER
ok 32 - test_unprotected_EC_via_PEM
ok 33 - test_protected_EC_via_DER
ok 34 - test_protected_EC_via_PEM
ok 35 - test_public_EC_via_DER
ok 36 - test_public_EC_via_PEM
ok 37 - test_params_EC_via_DER
ok 38 - test_params_EC_via_PEM
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:632
# Test not available if using a non-default library context or FIPS provider
ok 39 - test_unprotected_EC_via_legacy_PEM # skipped
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:753
# Test not available if using a non-default library context or FIPS provider
ok 40 - test_protected_EC_via_legacy_PEM # skipped
ok 41 - test_unprotected_ECExplicitPrimeNamedCurve_via_DER
ok 42 - test_unprotected_ECExplicitPrimeNamedCurve_via_PEM
ok 43 - test_protected_ECExplicitPrimeNamedCurve_via_DER
ok 44 - test_protected_ECExplicitPrimeNamedCurve_via_PEM
ok 45 - test_public_ECExplicitPrimeNamedCurve_via_DER
ok 46 - test_public_ECExplicitPrimeNamedCurve_via_PEM
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:632
# Test not available if using a non-default library context or FIPS provider
ok 47 - test_unprotected_ECExplicitPrimeNamedCurve_via_legacy_PEM # skipped
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:753
# Test not available if using a non-default library context or FIPS provider
ok 48 - test_protected_ECExplicitPrimeNamedCurve_via_legacy_PEM # skipped
ok 49 - test_unprotected_ECExplicitPrime2G_via_DER
ok 50 - test_unprotected_ECExplicitPrime2G_via_PEM
ok 51 - test_protected_ECExplicitPrime2G_via_DER
ok 52 - test_protected_ECExplicitPrime2G_via_PEM
ok 53 - test_public_ECExplicitPrime2G_via_DER
ok 54 - test_public_ECExplicitPrime2G_via_PEM
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:632
# Test not available if using a non-default library context or FIPS provider
ok 55 - test_unprotected_ECExplicitPrime2G_via_legacy_PEM # skipped
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:753
# Test not available if using a non-default library context or FIPS provider
ok 56 - test_protected_ECExplicitPrime2G_via_legacy_PEM # skipped
ok 57 - test_unprotected_ECExplicitTriNamedCurve_via_DER
ok 58 - test_unprotected_ECExplicitTriNamedCurve_via_PEM
ok 59 - test_protected_ECExplicitTriNamedCurve_via_DER
ok 60 - test_protected_ECExplicitTriNamedCurve_via_PEM
ok 61 - test_public_ECExplicitTriNamedCurve_via_DER
ok 62 - test_public_ECExplicitTriNamedCurve_via_PEM
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:632
# Test not available if using a non-default library context or FIPS provider
ok 63 - test_unprotected_ECExplicitTriNamedCurve_via_legacy_PEM # skipped
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:753
# Test not available if using a non-default library context or FIPS provider
ok 64 - test_protected_ECExplicitTriNamedCurve_via_legacy_PEM # skipped
ok 65 - test_unprotected_ECExplicitTri2G_via_DER
ok 66 - test_unprotected_ECExplicitTri2G_via_PEM
ok 67 - test_protected_ECExplicitTri2G_via_DER
ok 68 - test_protected_ECExplicitTri2G_via_PEM
ok 69 - test_public_ECExplicitTri2G_via_DER
ok 70 - test_public_ECExplicitTri2G_via_PEM
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:632
# Test not available if using a non-default library context or FIPS provider
ok 71 - test_unprotected_ECExplicitTri2G_via_legacy_PEM # skipped
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:753
# Test not available if using a non-default library context or FIPS provider
ok 72 - test_protected_ECExplicitTri2G_via_legacy_PEM # skipped
ok 73 - test_unprotected_ED25519_via_DER
ok 74 - test_unprotected_ED25519_via_PEM
ok 75 - test_protected_ED25519_via_DER
ok 76 - test_protected_ED25519_via_PEM
ok 77 - test_public_ED25519_via_DER
ok 78 - test_public_ED25519_via_PEM
ok 79 - test_unprotected_ED448_via_DER
ok 80 - test_unprotected_ED448_via_PEM
ok 81 - test_protected_ED448_via_DER
ok 82 - test_protected_ED448_via_PEM
ok 83 - test_public_ED448_via_DER
ok 84 - test_public_ED448_via_PEM
ok 85 - test_unprotected_X25519_via_DER
ok 86 - test_unprotected_X25519_via_PEM
ok 87 - test_protected_X25519_via_DER
ok 88 - test_protected_X25519_via_PEM
ok 89 - test_public_X25519_via_DER
ok 90 - test_public_X25519_via_PEM
ok 91 - test_unprotected_X448_via_DER
ok 92 - test_unprotected_X448_via_PEM
ok 93 - test_protected_X448_via_DER
ok 94 - test_protected_X448_via_PEM
ok 95 - test_public_X448_via_DER
ok 96 - test_public_X448_via_PEM
ok 97 - test_unprotected_RSA_via_DER
ok 98 - test_unprotected_RSA_via_PEM
ok 99 - test_protected_RSA_via_DER
ok 100 - test_protected_RSA_via_PEM
ok 101 - test_public_RSA_via_DER
ok 102 - test_public_RSA_via_PEM
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:632
# Test not available if using a non-default library context or FIPS provider
ok 103 - test_unprotected_RSA_via_legacy_PEM # skipped
# SKIP:  @ /home/ituglib/randall/openssl-3.0/test/endecode_test.c:753
# Test not available if using a non-default library context or FIPS provider
ok 104 - test_protected_RSA_via_legacy_PEM # skipped
ok 105 - test_unprotected_RSA_PSS_via_DER
ok 106 - test_unprotected_RSA_PSS_via_PEM
ok 107 - test_protected_RSA_PSS_via_DER
ok 108 - test_protected_RSA_PSS_via_PEM
ok 109 - test_public_RSA_PSS_via_DER
ok 110 - test_public_RSA_PSS_via_PEM
ok 111 - test_unprotected_RSA_via_MSBLOB
ok 112 - test_public_RSA_via_MSBLOB
ok 113 - test_unprotected_RSA_via_PVK
ok 114 - test_protected_RSA_via_PVK
$ echo $?
139
```

**Comment by t8m** [comment]
That's a crash. Are you able to debug it to get a backtrace?

**Comment by rsbeckerca** [comment]
This looks like a normal stop with an uninitialized error code. The trace is a standard exit after return. In the code, `ret==0`, so this is probably something in `wrap.pl`, not interpreting an exit correctly.
```
Catchpoint 3 (Process STOP), 0xfffffffff083a43c in AsmBreakGentrap ()
(xInspect 2,1173):bt
#0  0xfffffffff083a43c in AsmBreakGentrap ()
#1  0xfffffffff081b351 in $n_Gentrap ()
#2  0xfffffffff0dd6b3c in NSKPO_GentrapOwnership_(int) ()
#3  0xfffffffff0dd7c6b in NSKPO_InformCondition_ ()
#4  0xfffffffff0dccdfc in PCTL_SETSTOP_RESTORE_ ()
#5  0xfffffffff0de5e4e in SELF_STOP_VIA_BID ()
#6  0xfffffffff0de673c in STOP_A_PROCESS ()
#7  0xfffffffff0de4fea in PROCESS_STOP_ ()
#8  0xfffffffff084ea43 in $n_EnterPriv ()
#9  0xfffffffff3d0d858 in CRE_TERMINATOR_ ()
#10 0xfffffffff3e1d256 in exit ()
#11 0x700c1eb7 in _MAIN () at \BLPROD.$RTAL.T8432ACM.CPLMAINC:52
```

**Comment by rsbeckerca** [comment]
As of commit c37ff82e7c, this still shows in `test/endecode_test`. Same symptoms. It looks like perl, not the actual test case, which reports completion 0. It is still coming down to die() that is reporting whatever is on the stack.

**Comment by rsbeckerca** [comment]
I am thinking of closing this case and opening a new one specifically for `3.1`. The test `04-test_encoder_decoder.t` continues to pass on NonStop x86 on the `3.0.0` branch.

**Comment by t8m** [comment]
@rsbeckerca Is this still relevant with 3.2?

**Comment by rsbeckerca** [comment]
This appears to have been resolved. Not sure how or why.
