### ISSUE TITLE
Non-default library context is not passed appropriately in chain verification/building routines

### ISSUE THREAD

**Issue by jetson23** [openssl/openssl#16965]
My application sets up 2 non-default library contexts, one for FIPS and one for non-FIPS. I  run into the same problem when using either of the fips or non-fips library contexts. I set up the SSL_CTX as follows:

 ```
    ctx = SSL_CTX_new_ex(non_fips_libctx, NULL, TLS_method());
 ```

Then eventually make a call to SSL_CTX_build_cert_chain():

 ```
    status = SSL_CTX_build_cert_chain(ctx, SSL_BUILD_CHAIN_FLAG_NO_ROOT);
 ```

Which fails with the following error messages from OpenSSL:

 ```
00B741558E7F0000:error:0308010C:digital envelope routines:(unknown function):unsupported:crypto/evp/evp_fetch.c:346:Global default library context, Algorithm (SHA1 : 96), Properties (<null>)
00B741558E7F0000:error:03000072:digital envelope routines:(unknown function):decode error:crypto/x509/x_pubkey.c:444:
00B741558E7F0000:error:03000072:digital envelope routines:(unknown function):decode error:crypto/x509/x_pubkey.c:444:
00B741558E7F0000:error:0580006C:x509 certificate routines:(unknown function):unable to get certs public key:crypto/x509/x509_vfy.c:1986:
00B741558E7F0000:error:0A000086:SSL routines:(unknown function):certificate verify failed:ssl/ssl_cert.c:905:Verify error:unspecified certificate verification error
 ```

Using the following OpenSSL version:

 ```
OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)
 ```

Originally posted the details of this specific problem here:

https://www.mail-archive.com/openssl-users@openssl.org/msg90238.html

**Comment by t8m** [comment]
So here the reason is again that the certs loaded into the X509_STORE used for the cert chain building are read without an libctx set. Am I correct? If so, please close this.

**Comment by jetson23** [comment]
I was wondering the same thing, and I actually just got done testing with SSL_CTX_build_cert_chain() added back into my code. This does work now, the problem was in my X509_STORE.

My apologies for the non-issue, thanks for the help.
