### ISSUE TITLE
pkcs12 passout file options throws error without newline

### ISSUE THREAD

**Issue by essandess** [openssl/openssl#16968]
`openssl pkcs12 -passout file:passphrase.txt` throws this error if the passphrase file doesn't end with a `\n`.

> ```
> Error reading password from BIO
> Error getting passwords
> ```

At best, this error is inconsistent with the `-passin` option, but I believe the behavior is a bug.

MWE (EC, but also fails for RSA):
```bash
# create a private key and certificate
echo foobar > passphrase.txt
openssl genpkey -out ca.key.pem -algorithm EC -pkeyopt ec_paramgen_curve:P-384 -aes256 -pass file:passphrase.txt
openssl req -new -x509 -days 1460 -sha256 -out ca.cert.pem -key ca.key.pem -passin file:passphrase.txt -batch
openssl verify -CAfile ca.cert.pem ca.cert.pem

# verify the passphrase for the private key using `-passin file:passphrase.txt`
openssl ec -noout -in ca.key.pem -passin file:passphrase.txt

# This fails with `Error reading password from BIO`
openssl pkcs12 -export -out ca.p12 -inkey ca.key.pem -in ca.cert.pem -passin file:passphrase.txt -passout file:passphrase.txt

# Add a newline and get a successful result
printf "\n" >> passphrase.txt
openssl pkcs12 -export -out ca.p12 -inkey ca.key.pem -in ca.cert.pem -passin file:passphrase.txt -passout file:passphrase.txt
```

See: https://github.com/openssl/openssl/blob/3841d0f6f02e1ad3a54beabf1d5395bd1c383254/apps/lib/apps.c#L330

**Comment by t8m** [comment]
What OpenSSL version are we talking here about?

**Comment by essandess** [comment]
```bash
openssl version
OpenSSL 1.1.1l  24 Aug 2021
```

**Comment by t8m** [comment]
The problem is not a missing newline - actually by doing `echo foobar > passphrase.txt` there is always one newline after the `foobar`. The problem is that you use the same passphrase.txt file for passin and passout. For some reason this does not work right.

**Comment by t8m** [comment]
Now the question is whether this is documented somewhere.

**Comment by t8m** [comment]
Yeah, this is documented in openssl-passphrase-options manual page.

**Comment by essandess** [comment]
Thanks for clarifying!

But ummm, does the “fix” to this “feature” above cause `openssl` to use a blank passphrase for the output file?

```bash
printf "\n" >> passphrase.txt
```

**Comment by essandess** [comment]
I concur—this is user error. Thanks again for the help!
