### ISSUE TITLE
Decoding of EC Public Keys is broken in OpenSSL 3.0

### ISSUE THREAD

**Issue by broken-bytes** [openssl/openssl#16979]
I am unable to import neither DER, nor PEM public keys in OpenSSL 3.

Note: This might be related to https://github.com/openssl/openssl/issues/16977 as my public key strings created with the encoder look similar.

Whenever I try reading a public key, I get the error routines::unsupported.
However, importing a private key works just fine. 
As we cannot share private keys of course, not being able to create an EVP_PKEY from our public key material is a crucial issue that makes us unable to continue at all.

We are trying to do a ECDH key exchange, but, as importing the public key material from the other peer does not work,  we have no chance of doing so. 
I have tried using both DER and PEM encodings as stated before, with private key imports being fine for both of them. 

Either the documentation needs to be updated - stating that EVP_PKEYs cannot be constructed from EC public keys, and additional information and workarounds habe to be provided - or the bug needs to be fixed asap.

This is a huge issue.

For further investigation, here is how we encode our public key.

```cpp
    constexpr char FORMAT[] = "DER"; // Either PEM or DER

    auto key = EVP_EC_gen(SN_brainpoolP256r1); 
    unsigned char* publicKey = nullptr;
    size_t publicLen = 0;
    auto ptr = OSSL_ENCODER_CTX_new_for_pkey(
                                             key,
                                             EVP_PKEY_PUBLIC_KEY,
                                             FORMAT,
                                             nullptr,
                                             nullptr
                                             );
    OSSL_ENCODER_to_data(ptr, &publicKey, &publicLen);
    OPENSSL_free(ptr);
``` 

`publicKey` is then sent to our backend, which stores it. 
Later, another peer downloads the publicKey, and passes the key material and its length (via strlen, as stated private keys work perfectly fine, so this isn't an issue of misconfiguration). The downloaded key is then passed to the derive function, which does the ECDH key exchange. 
As said before this does not work, as the public key part fails to create the needed EVP_PKEY.

This is how we are creating an EVP_PKEY from our public key:

```cpp
    constexpr char FORMAT[] = "DER"; // Either PEM or DER
    // Theirs is the downloaded public key material from the other peer, either in PEM or DER format
   void DeriveKey(..., const unsigned char* theirs, size_t theirsLen) {

    EVP_PKEY_CTX* ctx = nullptr;
    EVP_PKEY* peerKey = nullptr;
    auto ptr = OSSL_DECODER_CTX_new_for_pkey(
                                             &peerKey,
                                             FORMAT,
                                             nullptr,
                                             nullptr,
                                             EVP_PKEY_PUBLIC_KEY, // EVP_PKEY_KEYPAIR works fine when used with a private key; We also tried several other options, with none of them being successful on public keys. 
                                             nullptr,
                                             nullptr
                                             );
    auto result = OSSL_DECODER_from_data(ptr, &theirs, &theirsLen);
    // result == 0 
    auto err = ERR_get_error();
    auto buff = new char[512];
    ERR_error_string(err, buff); // error:1E08010C:DECODER routines::unsupported
}
```

**Comment by mattcaswell** [comment]
If you can supply the actual public key material we can determine whether it has been encoded correctly or not (i.e. whether it is actually issue #16977 or something different)

**Comment by broken-bytes** [comment]
@mattcaswell 
Encoding a public key in PEM format yields this:
`-----BEGIN EC PUBLIC KEY-----\nBJlgr2TNcLkBSbDdb9N0tc1Kr42RGMBdRMSddWpekPAyY5F4P7hZ5TJYiOgcJc9f\nbz+/+oyuan/b40nvCJhNUuM=\n-----END EC PUBLIC KEY-----\n\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa`

**Comment by broken-bytes** [comment]
this is taken right from the char buffer, without uploads or anything

**Comment by broken-bytes** [comment]
![Screenshot 2021-11-05 at 18 01 24](https://user-images.githubusercontent.com/5307161/140549686-3c03ab87-5120-4c9b-bac6-831fc9a6704d.png)
This is what the encoded key material looks like when using the fix mentioned in the other issue.

**Comment by broken-bytes** [comment]
![Screenshot 2021-11-05 at 18 03 10](https://user-images.githubusercontent.com/5307161/140549893-44ec20c8-11e9-4f3c-93bd-72edc4f8dba9.png)
And this is the opposite, prior to the workaround

**Comment by broken-bytes** [comment]
It appears that the only change is the lack of EC, e.g. `BEGIN PUBLIC KEY` instead of `BEGIN EC PUBLIC KEY`

**Comment by levitte** [comment]
It's not just about the header. The contents of the "EC PUBLIC KEY" isn't correct for a "PUBLIC KEY", as there's a difference in structure (the contents of that "EC PUBLIC KEY" is actually highly unstructured, it's simply a dumped big number, totally raw... it's not even DER).

**Comment by broken-bytes** [comment]
@levitte Well that’s unfortunate. 
As it has been made clear that this ticket is related to the other one, I’ll close this.
