### ISSUE TITLE
Openssl 1.1.1l, s_client cannot perform TLS1.3 handshake using chacha20

### ISSUE THREAD

**Issue by davidgao** [openssl/openssl#16978]
I'm trying to use `openssl s_client` to verify handshaking with servers.
I'm using OpenSSL 1.1.1l.

However it does not accept certain supported ciphers, including `TLS_CHACHA20_POLY1305_SHA256`, and I cannot complete a TLS 1.3 handshake to use chacha20.
Command: `openssl s_client -connect google.com:443 -cipher TLS_CHACHA20_POLY1305_SHA256`

The output looks like:
```
Error with command: "-cipher TLS_CHACHA20_POLY1305_SHA256"
139685586793856:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2571:`
```

It does accept `ECDHE-ECDSA-CHACHA20-POLY1305`, and can complete a TLS 1.2 handshake. Command: `openssl s_client -no_tls1_3 -cipher ECDHE-ECDSA-CHACHA20-POLY1305 -connect google.com:443`

The output contains:
```
New, TLSv1.2, Cipher is ECDHE-ECDSA-CHACHA20-POLY1305
```

As a library, the same openssl can complete TLS 1.3 handshake to use chacha20. This can be verified using curl. Command: `curl -v https://www.google.com --tls13-ciphers TLS_CHACHA20_POLY1305_SHA256`

The output contains:
```
* SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256
```

**Comment by mattcaswell** [comment]
Your s_client command is incorrect. It should look like this:

````
openssl s_client -connect google.com:443 -ciphersuites TLS_CHACHA20_POLY1305_SHA256
````

The TLSv1.2 and TLSv1.3 ciphersuites are treated separately. From the manual page:
````
-cipher cipherlist
This allows the TLSv1.2 and below cipher list sent by the client to be modified. This list will be combined with any TLSv1.3 ciphersuites that have been configured. Although the server determines which ciphersuite is used it should take the first supported cipher in the list sent by the client. See openssl-ciphers(1) for more information.

-ciphersuites val
This allows the TLSv1.3 ciphersuites sent by the client to be modified. This list will be combined with any TLSv1.2 and below ciphersuites that have been configured. Although the server determines which cipher suite is used it should take the first supported cipher in the list sent by the client. See openssl-ciphers(1) for more information. The format for this list is a simple colon (":") separated list of TLSv1.3 ciphersuite names.
````

**Comment by davidgao** [comment]
Thanks!
