### ISSUE TITLE
Implicit activation of the default provider

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16981]
Could anybody please point me to the place where the default provider is implicitly activated if no providers are loaded?

**Comment by paulidale** [comment]
Try:

https://github.com/openssl/openssl/blob/884400d78992d1da1573a3677876b06421b797eb/crypto/provider_core.c#L1187-L1257

**Comment by paulidale** [comment]
Assuming that this is answered, I'm closing it.
