### ISSUE TITLE
Windows 3.0.X build issue : dll naming for engines and ossl-modules

### ISSUE THREAD

**Issue by nono303** [openssl/openssl#16984]
Hi,
Currently building OpenSSL 3.0.0 for Windows with MSVC (vs17):

```
perl Configure VC-WIN64A shared no-unit-test no-external-tests no-ssl3 no-weak-ssl-ciphers no-tests zlib zlib-dynamic -threads --prefix=C:\sdk\release\vs17_x64-avx --with-zlib-include=C:/sdk/release/vs17_x64-avx/include --openssldir=C:\sdk\release\vs17_x64-avx\conf -DOPENSSL_USE_IPV6=1 -DOPENSSL_NO_HEARTBEATS -L"/OPT:ICF,REF /LTCG /DEBUG" +"/w /O2 /GL /MD /Zi /MP16 /arch:AVX" 
nmake /NOLOGO install_sw 
```
I have some warning when linking dlls for engines and ossl-modules:
```
5839 : engines\capi.def(5) : warning LNK4093: Drive/Directory component ignored in 'LIBRARY' statement
5841 : capi.exp : warning LNK4070: /OUT:capi-3-x64.dll directive in .EXP differs from output filename 'engines\capi.dll'; ignoring directive
5844 : capi.exp : warning LNK4070: /OUT:capi-3-x64.dll directive in .EXP differs from output filename 'engines\capi.dll'; ignoring directive
```
and 
I'll only focus for the next step on `capi` but same warnings for `dasync`, `loader_attic`, `ossltest`, `padlock` & `legacy` 
**Theses warning were not thrown with OpenSSL 1.1.X**

After a quick investigation, I found that `util/mkdef.pl` function `writer_windows` use `$libname = (platform->sharedname($name) )` value for `LIBRARY`
ex. for capi:

```
;
; Definition file for the DLL version of the engines\capi-3-x64 library from OpenSSL
;

LIBRARY         "engines\capi-3-x64"

EXPORTS
    bind_engine
    v_check
```
looking at `Configurations\platform\Windows.pm` function `sharedname` always concat `shlib_version` and `shlibvariant` (ex. x64 in my case) to the `$name` of the lib.
```
$name = "capi"
$libname = "capi-3-x64"
```
Looking at makefile (generated from `Configurations\windows-makefile.tmpl`), this is the good naming for `INSTALL_SHLIBS` but **NOT** for `INSTALL_ENGINES` and `INSTALL_MODULES`

```
INSTALL_SHLIBS="libcrypto-3-x64.dll" "libssl-3-x64.dll"
INSTALL_SHLIBPDBS="libcrypto-3-x64.pdb" "libssl-3-x64.pdb"
INSTALL_ENGINES="engines\\capi.dll" "engines\\loader_attic.dll" "engines\\padlock.dll"
INSTALL_ENGINEPDBS="engines\\capi.pdb" "engines\\loader_attic.pdb" "engines\\padlock.pdb"
INSTALL_MODULES="providers\\legacy.dll"
INSTALL_MODULEPDBS="providers\\legacy.pdb"
```
As i understand:
1. for **LNK4093** : `util/mkdef.pl` must be call without **path** in `--name` option in generated makefile

`"$(PERL)" util\mkdef.pl --ordinals util\engines.num --name engines\capi --OS windows > engines\capi.def`
might be
`"$(PERL)" util\mkdef.pl --ordinals util\engines.num --name capi --OS windows > engines\capi.def`

2. for **LNK4070**:
    a. if the good name is **capi.dll** (and capi.pdb) : `util/mkdef.pl` must **NOT** use `$libname` but `$name` for engines & providers
    b. if the good name is **capi-3-x64.dll** (and capi-3-x64.pdb) : `INSTALL_ENGINES`, `INSTALL_ENGINEPDBS`, `INSTALL_MODULES` & `INSTALL_MODULEPDBS` values in makefile  must use `$libname` and not `$name`

Don't hesitate if you need more information or test on this case

**Comment by mattcaswell** [comment]
@levitte?

**Comment by levitte** [comment]
Using `platform->sharedname($name)` is wrong for DSOs.  The call should be `platform->dsoname($name)`

So it seems that `util/mkdef.pl` needs to learn how to differentiate between shared libraries that programs should be build time linked with, and DSOs (which are essentially shared libraries that should be dynamically loaded)

**Comment by levitte** [comment]
I suggest that util/mkdef.pl gets a new command line flag, say `--type`, which can take two values, `lib` and `dso`, and use that to indicate if `platform->sharedname` or `platform->dsoname` should be used.
