### ISSUE TITLE
RIPEMD160 does not work

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#16994]
In short: OpenSSL-3 (and master) build normally (config attached), passes all the tests, pretends that RIPEMD is there - but fail to actually **use** it when asked.

With 3.0.0:
```
$ openssl speed ripemd160
Doing rmd160 for 3s on 16 size blocks: rmd160 error!
006E861201000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:346:Global default library context, Algorithm (RIPEMD160 : 101), Properties ()
006E861201000000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:crypto/evp/digest.c:234:
version: 3.0.0
built on: built on: Thu Oct 14 00:15:47 2021 UTC
options:bn(64,64) 
compiler: /usr/bin/clang -fPIC -arch x86_64 -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk
CPUINFO: OPENSSL_ia32cap=0x7ffef3ffffebffff:0x139efffb
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
rmd160               0.00         0.00         0.00         0.00         0.00         0.00 
```

With `master`:
```
$ openssl3 speed ripemd160
Doing rmd160 for 3s on 16 size blocks: rmd160 error!
004E5D0401000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RIPEMD160 : 97), Properties ()
004E5D0401000000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:crypto/evp/digest.c:235:
version: 3.1.0-dev
built on: Mon Nov  8 14:51:48 2021 UTC
options: bn(64,64)
compiler: clang -fPIC -arch x86_64 -O3 -std=gnu18 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -g -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DZLIB_SHARED
CPUINFO: OPENSSL_ia32cap=0x7ffef3ffffebffff:0x139efffb
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
rmd160               0.00         0.00         0.00         0.00         0.00         0.00 
```

Also, are dynamically-loaded engines no longer supported?!
```
$ openssl3 engine -t
(rdrand) Intel RDRAND engine
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]
(gost) Reference implementation of GOST engine
     [ available ]
$ openssl3 version
OpenSSL 3.1.0-dev  (Library: OpenSSL 3.1.0-dev )
$ 
```

### Update
My configurator did not include `enable-rmd160`. Re-testing with it added.

**Comment by paulidale** [comment]
Load the legacy provider by adding `-provider legacy` to the path.  You might also need to set the provider path, also via command line option.

Yes, engines are still supported.

**Comment by mouse07410** [comment]
> Load the legacy provider by adding `-provider legacy` to the path. You might also need to set the provider path, also via command line option.

Could you please clarify: I want RIPEMD160 be available **by default**, without any special _command line_ flag. How can I do it through, e.g., build process, or, at the very least, via `openssl.cnf` file?

> Yes, engines are still supported.

Excellent. Could you please help understanding what are the meaning and the implications of this message:
```
(dynamic) Dynamic engine loading support
     [ unavailable ]
```
and what do I need to do to make that support "available"?

**Comment by paulidale** [comment]
You need to use a config file along these lines:
```
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```
The [migration guide](https://www.openssl.org/docs/manmaster/man7/migration_guide.html) is a good starting place for things like this.


Try loading an engine.  I'm seeing the same message here and _can_ load them okay.  `openssl3 list -disabled` will say if engines aren't supported (it doesn't mention ENGINE if they are).

**Comment by mouse07410** [comment]
@paulidale thank you!

Taking care of `openssl.cnf` the way you showed above, resolved the problem.

Remaining question regarding RIPEMD160:  do I need to add `enable-rmd160` to `./config ......`? Or is legacy provider gets built with all the associated algorithms included, unless I explicitly configure _not_ to do that?

Re. engine: 
```
$ openssl3 list -disabled
Disabled algorithms:
SCTP
SSL3
$ 
```
I suspect I don't need either of them. 

I am able to use PKCS#11 engine. But I'm still concerned about that "unavailable" message - it does not look right.

**Comment by paulidale** [comment]
RIPEMD is there by default but it doesn't hurt including it in the config line.  The legacy is built by default.

**Comment by cculianu** [comment]
Question to the OpenSSL devs -- reading the above.. this looks like a regression to me.  Are you guys really happy with this incredibly cumbersome way to use ripemd160?  

Like I didn't look at the details all I am seeing is that you need like to edit a config file or something for it to work, or something insane.

Do you feel this is a quality product for people to use? Really?  I mean.. ask yourselves -- if someone handed you OpenSSL 1.1 and it "just worked" mostly.. and then they hand you OpenSSL 3.0 and you have *increased* complexity for no real benefit to the average user -- is this a good thing?

**Comment by paulidale** [comment]
The choice as to which algorithms should be placed into the legacy provider is extremely conservative.  The algorithms there have all been considered broken for a very long time.  Rather than removing them completely, the [decision](https://mta.openssl.org/pipermail/openssl-project/2020-January/001720.html) was made to not make them available by default.

Honestly, nobody should be using these old algorithms.  How many **decades** do folks need to update their cryptography use?

**Comment by cculianu** [comment]
These sound like excuses.  At the end of the day OpenSSL 3.0 has gotten worse for some percentage of your install base.  You are ok with that it seems.

I, as a software developer, do not believe in communism.  I don't see myself as some central planning komissar that "knows better" than my users.  I give my users the tools they need.  Like it or not, ripemd160 **is used globally** by millions of people each day!  It is used in some mission-critical systems moving billions of dollars around.    Ripemd160 is used in bitcoin, for example, and many other cryptocurrencies to hash public keys (and thus to generate a bitcoin address).  Bitcoin, maybe you heard of it: It's a trilliojn-dollar blockchain.  They can't just hard-fork tomorrow because you don't like ripemd160.  

Now, bitcoin has its own implementation of ripemd160 internally.  But external toolchains in Python, for example, that interface with Bitcoin and other blockchains need easy access to ripemd160, which they get via openssl.

Now -- you guys decided to make like harder for all of those people.  And for all the package manager devs out there, and for everybody else.

In this decision you have generated negative value for the world.  All because of ego.  You guys are *not* central planners, despite your liking to believe you are.  You should strive to make tools that make life easier for people, not harder.

**Comment by daira** [comment]
> The choice as to which algorithms should be placed into the legacy provider is extremely conservative. The algorithms there have all been considered broken for a very long time. Rather than removing them completely, the [decision](https://mta.openssl.org/pipermail/openssl-project/2020-January/001720.html) was made to not make them available by default.

As a cryptographer, it's news to me that RIPEMD-160 is broken. As far as I know there is no feasible attack against either preimage resistance or collision resistance less costly than the generic attacks. The [best published cryptanalytic attack against CR](https://eprint.iacr.org/2018/652.pdf) only reaches 34 (out of 80) steps, i.e. it is nowhere near being applicable to full RIPEMD-160.

Sure, the 160-bit output size is less than preferred for new protocols, and that limits collision-resistance security to 80 bits. But RIPEMD-160 is used in a lot of places where that isn't a particular problem (for example in Bitcoin address hashing).

More to the point, disabling it in OpenSSL isn't actually helping. It's just breaking other software (including software that isn't *directly* using OpenSSL, for example when it's used via Python's hashlib), in ways that inconvenience people who have no ability to change or decide what algorithms are being used.

**Comment by RBKreckel** [comment]
I'm coming here from Debian [#10200695](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020695).

> The choice as to which algorithms should be placed into the legacy provider is extremely conservative. The algorithms there have all been considered broken for a very long time. Rather than removing them completely, the [decision](https://mta.openssl.org/pipermail/openssl-project/2020-January/001720.html) was made to not make them available by default.

Aha. So RIPEMD160 is considered broken? Citation Needed!

> Honestly, nobody should be using these old algorithms. How many decades do folks need to update their cryptography use?

If it was true, then MD5 and SHA1 should have been moved to the legacy provider many years ago. There are plenty of collisions for these. There is no publicly known collision for RIPEMD160.

As it stands, by moving RIPEMD160 to the legacy provider, OpenSSL breaks established crypto software with no known security weaknesses. This should be reverted.

**Comment by kanzure** [comment]
https://www.openssl.org/blog/blog/2022/10/18/rmd160-and-the-legacy-provider/ from #17722

**Comment by RBKreckel** [comment]
> Bitcoin itself has performed more than 2^94 sha256 operations -- way more than enough to find a collision in a 160 bit hash with low memory moderate communication algorithms (and sha2-256 has considerably higher area-time costs).

This is misleading. A (good) 160-bit has function requires about 2^160 attempts to find a collision except if we store enough values to mount a birthday attack. Basically, a birthday attack is a time-space trade-off: If we store 2^80 sorted values and search them for a collision in each go, then we still need roughly 2^80 such attempts to find a collision. And even Bitcoin is very very far from that.

Also, the maintenance argument seems to be a pretext to justify a past mistake. The algorithm's interface is the same as any other hash function based on the Merkle-Damgård construction and as far as I can see it never failed to compile.

The decision to remove RIPEMD160 was a mistake. Before removing it, the argument has been made that it's broken – while MD5 and SHA1 were left in. Then, the argument has been made that it is not standardized – but there's ISO/IEC 10118-3. And the argument has been made that it is not used – but there's Bitcoin.

Please stop fishing for arguments that the removal was the right thing to do. This discussion only creates fear, uncertainty, and doubt. It is perfectly okay to move away from RIPEMD160 and use more bits. But, for now, after all we know, applications are safe. (And especially so if second preimage is the sole concern.)

**Comment by petertodd** [comment]
@paulidale 

> Honestly, nobody should be using these old algorithms. How many **decades** do folks need to update their cryptography use?

I'm the founder of OpenTimestamps, and the maintainer of python-opentimestamps among others. I expect to be using ripemd160 to validate certain older Bitcoin timestamps for decades more, precisely because they're timestamps.

Not the end of the world to find a pure-Python alternate implementation. But annoying given that ripemd160 hasn't even had a cryptographic break yet.

(even sha1 is fine for timestamps: https://petertodd.org/2017/sha1-and-opentimestamps-proofs)
