### ISSUE TITLE
Does RSA use auxiliary primes compliant with NIST 186-4?

### ISSUE THREAD

**Issue by sugrbear1970** [openssl/openssl#16993]
Good Afternoon.

It appears that the auxiliary primes in RSA (p1, p2, q1, q2) are hardcoded at 101-bits. 
(These are the values which are the precursors to **p** and **q**)

NIST 186-4 indicates in Table B.1, that:

- A 2048-bit key would require auxiliary primes > 140-bits; and
- A 3072-bit key would require auxiliary primes > 170-bits.

Can anyone please confirm whether or not the auxiliary primes are compliant with NIST 186-4?
Thanks for your time.

**Comment by paulidale** [comment]
The FIPS provider in OpenSSL 3.0 should be compliant with [FIPS 186-4 section B.3.6](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-RSA.html#CONFORMING-TO).  It will be once it finishes the validation process but before then it's not possible to know if changes will be required.  If you **need** FIPS 186-4 compliance this is the only way to guarantee it.

Outside of the FIPS provider, they can be compliant but this hasn't and won't be formally validated.  It is also possible to generate non-compliant keys.

OpenSSL versions before 3.0 are not FIPS 186-4 compliant and never will be.

**Comment by t8m** [comment]
> It appears that the auxiliary primes in RSA (p1, p2, q1, q2) are hardcoded at 101-bits.
> (These are the values which are the precursors to **p** and **q**)

Could you tell please, where you see this hardcoded 101 bits value? I do not see that in the code. The functions bn_rsa_fips186_5_aux_prime_min_size() and bn_rsa_fips186_5_aux_prime_max_sum_size_for_prob_primes() determine the sizes and they are according to the FIPS 186-5 (which is compatible with FIPS 186-4 values).

**Comment by sugrbear1970** [comment]
> The FIPS provider in OpenSSL 3.0 should be compliant with [FIPS 186-4 section B.3.6](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-RSA.html#CONFORMING-TO). It will be once it finishes the validation process but before then it's not possible to know if changes will be required. If you **need** FIPS 186-4 compliance this is the only way to guarantee it.
> 
> Outside of the FIPS provider, they can be compliant but this hasn't and won't be formally validated. It is also possible to generate non-compliant keys.
> 
> OpenSSL versions before 3.0 are not FIPS 186-4 compliant and never will be.

Thank You.

**Comment by sugrbear1970** [comment]
> > It appears that the auxiliary primes in RSA (p1, p2, q1, q2) are hardcoded at 101-bits.
> > (These are the values which are the precursors to **p** and **q**)
> 
> Could you tell please, where you see this hardcoded 101 bits value? I do not see that in the code. The functions bn_rsa_fips186_5_aux_prime_min_size() and bn_rsa_fips186_5_aux_prime_max_sum_size_for_prob_primes() determine the sizes and they are according to the FIPS 186-5 (which is compatible with FIPS 186-4 values).

Thanks for the reply. 

The code I was looking at is /crypto/bn/bn_x931p.c lines 234 and 236.

**Comment by t8m** [comment]
> The code I was looking at is /crypto/bn/bn_x931p.c lines 234 and 236.

That code is not used by the fips provider at all.

**Comment by sugrbear1970** [comment]
Ok thanks.
