### ISSUE TITLE
OpenSSL 1.1.1l  24 Aug 2021 - s_server fails to execute DTLS1.2 PSK handshake

### ISSUE THREAD

**Issue by boaks** [openssl/openssl#16992]
For the open source project Eclipse/Californium I developed some [basic interoperability tests](https://github.com/eclipse/californium/tree/master/californium-tests/californium-interoperability-tests/src/test/java/org/eclipse/californium/interoperability/test/openssl).

Until that version 1.1.1l the tests worked well.
with that new version of openssl, the s_server now fails to execute a DTLS 1.2 PSK handshake.

```
> openssl s_server -4 -dtls1_2 -accept :5684 -listen -verify 5 -cipher PSK-AES128-CCM8 -psk_identity Client_identity -psk 73656372657450534B

verify depth is 5
Using default temp DH parameters
ACCEPT
ERROR
140701395044160:error:1419E0DF:SSL routines:tls_process_cke_psk_preamble:psk identity not found:../ssl/statem/statem_srvr.c:2969:
shutting down SSL
CONNECTION CLOSED
```

[dtls_1_2_psk_handshake.pcapng.gz](https://github.com/openssl/openssl/files/7496325/dtls_1_2_psk_handshake.pcapng.gz)

The handshake fails with the server's alert "UNKNOWN_PSK_IDENTITY".

**Comment by kaduk** [comment]
This looks likely to be a duplicate of #16707 (so, fixed in the development branches via #16838).

**Comment by boaks** [comment]
Yes. 
(I searched with the error message, but I didn't found something).

**Comment by boaks** [comment]
And, thanks for the very fast help!
