### ISSUE TITLE
need example code use tls 1.3 in c++

### ISSUE THREAD

**Issue by budibeta** [openssl/openssl#17008]
i cant visit website that has tls 1.3 enabled, err_connection_reset
because tls 1.2 handshake is different from tls 1.3

<img width="677" alt="Screenshot_3" src="https://user-images.githubusercontent.com/68463485/141208580-bfff2ea2-1c0e-4ebb-8de8-0a3c670de9de.png">

i need an example code tls 1.3 in c++ both client and server, especially for client, who could help me.

**Comment by mattcaswell** [comment]
There's a sample server here:

https://wiki.openssl.org/index.php/Simple_TLS_Server

It's not TLSv1.3 specific. It should work fine for multiple TLS versions and negotiate the highest version supported by the client.

**Comment by budibeta** [comment]
> There's a sample server here:
> 
> https://wiki.openssl.org/index.php/Simple_TLS_Server
> 
> It's not TLSv1.3 specific. It should work fine for multiple TLS versions and negotiate the highest version supported by the client.

my code is same as the reference you given. thats why i request the example.

**Comment by kroeckx** [comment]
You seem to be asking the same question over and over, and then deleting your previous questions. If you ask the same question, you will get the same answer. There is nothing specific you should do for TLS 1.3. If it's not working, you should probably show your complete code.

**Comment by budibeta** [comment]
this is my complete code
```
bool HandShake_WithServer(SOCKET s, SSL* &serverSession)
{
static SSL_CTX *ctx = NULL;
if (ctx == NULL)
{
	ctx = SSL_CTX_new(SSLv23_client_method());
	if (!ctx) {
		return false;
	}
	SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_COMPRESSION);
	SSL_CTX_set_mode(ctx, SSL_MODE_RELEASE_BUFFERS);
}
SSL* ssl = SSL_new(ctx);
//SSL_CTX_free(ctx);
if (!ssl) {
	return false;
}
SSL_set_connect_state(ssl);
SSL_set_fd(ssl, s);
SSL_set_options(ssl, SSL_OP_ALL);
if (SSL_connect(ssl) != 1) {
	SSL_free(ssl);
	return false;
}
serverSession = ssl;
return true;
}
```

this work on youtube, google, stackoverflow, because the server dont force client use tls 1.3
but, fail on unknowncheats.me, because that site force the user client to use tls 1.3 even if unknowncheats.me support tls .12

**Comment by budibeta** [comment]
> You seem to be asking the same question over and over, and then deleting your previous questions. If you ask the same question, you will get the same answer. There is nothing specific you should do for TLS 1.3. If it's not working, you should probably show your complete code.

this is my complete code

```
bool HandShake_WithServer(SOCKET s, SSL* &serverSession)
{
static SSL_CTX *ctx = NULL;
if (ctx == NULL)
{
	ctx = SSL_CTX_new(SSLv23_client_method());
	if (!ctx) {
		return false;
	}
	SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_COMPRESSION);
	SSL_CTX_set_mode(ctx, SSL_MODE_RELEASE_BUFFERS);
}
SSL* ssl = SSL_new(ctx);
//SSL_CTX_free(ctx);
if (!ssl) {
	return false;
}
SSL_set_connect_state(ssl);
SSL_set_fd(ssl, s);
SSL_set_options(ssl, SSL_OP_ALL);
if (SSL_connect(ssl) != 1) {
	SSL_free(ssl);
	return false;
}
serverSession = ssl;
return true;
}
```

this work on youtube, google, stackoverflow, because the server dont force client use tls 1.3
but, fail on unknowncheats.me, because that site force the user client to use tls 1.3 even if unknowncheats.me support tls 1.2
