### ISSUE TITLE
Changing EVP_PKEY_base_id to a macro breaks applications not updated for OpenSSL 3.0.0

### ISSUE THREAD

**Issue by marka63** [openssl/openssl#17003]
Changing `EVP_PKEY_base_id` to be a macro breaks every application that uses `AC_CHECK_FUNCS(EVP_PKEY_base_id)` to determine if `EVP_PKEY_base_id` is available.  This also applies to all the other cases where functions have been replaced by macros.

While you where intending to deprecate EVP_PKEY_base_id you actually removed it and replaced it by a macro.

**Comment by paulidale** [comment]
This change was made in #15405 (ed576acdf591d4164905ab98e89ca5a3b99d90ab) and was intentional.

Question to @openssl/otc, should the macro replacements be converted back to functions?

Thoughts and input welcomed before any discussion.

**Comment by t8m** [comment]
IMO such kind of breakage is acceptable for 1.1.1 -> 3.0 changes. I do not think we should (or even can) revert that.

**Comment by mattcaswell** [comment]
> breaks applications not updated for OpenSSL 3.0.0

This is the key point. OpenSSL 3.0 is a major version bump and does not guarantee source compatibility. We've tried to make it so that most applications will "just work" but this is not the case universally.

**Comment by paulidale** [comment]
OTC: the macro replacements will stay.

These changes were made deliberately.
The way to check for APIs is using the versioning scheme not checking for the calls directly.
