### ISSUE TITLE
OpenSSL build error

### ISSUE THREAD

**Issue by ladyBird-z** [openssl/openssl#17014]
OpenSSL build error
openssl 3.0
My command is

./Configure --prefix=/usr --sysconfdir=/etc/ssh --with-md5-passwords --with-privsep-path=/var/lib/sshd && make

error:
make[1]: Entering directory `/root/openssl-3.0.0'
make[1]: Leaving directory `/root/openssl-3.0.0'
make[1]: Entering directory `/root/openssl-3.0.0'
gcc  -I. -Iinclude -Iapps/include  -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 --sysconfdir=/etc/ssh --with-md5-passwords --with-privsep-path=/var/lib/sshd -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/ssl\"" -DENGINESDIR="\"/usr/lib64/engines-3\"" -DMODULESDIR="\"/usr/lib64/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF apps/lib/libapps-lib-app_libctx.d.tmp -MT apps/lib/libapps-lib-app_libctx.o -c -o apps/lib/libapps-lib-app_libctx.o apps/lib/app_libctx.c
gcc: error: unrecognized command line option '--sysconfdir=/etc/ssh'
gcc: error: unrecognized command line option '--with-md5-passwords'
gcc: error: unrecognized command line option '--with-privsep-path=/var/lib/sshd'
make[1]: *** [apps/lib/libapps-lib-app_libctx.o] Error 1
make[1]: Leaving directory `/root/openssl-3.0.0'
make: *** [build_sw] Error 2

**Comment by beldmit** [comment]
Looks like you try to build OpenSSH, not OpenSSL

**Comment by ladyBird-z** [comment]
What should I do

**Comment by beldmit** [comment]
You should build openssh, not openssl, I think
