### ISSUE TITLE
AIX7.1 Illegal instruction(coredump)

### ISSUE THREAD

**Issue by Fury-Fox** [openssl/openssl#17011]
![image](https://user-images.githubusercontent.com/25580391/141271948-d99538fd-0633-4883-b6d8-5ce8074a20c1.png)

How should I use crypto/ppccap.c? Is there a demo for this question?

**Comment by kroeckx** [comment]
It works like OPENSSL_ia32cap, but the environment variable is called OPENSSL_ppccap instead. For the supported bits, look at the ppccap.c file. A file documenting this like for ia32 and s390x would be useful.

**Comment by Fury-Fox** [comment]
Thanks very mush!
after export OPENSSL_ppccap=1 ,  well done.
