### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [openssl/openssl#1703]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
* And here is how you can sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by levitte** [comment]
We do sign our release tags since this summer.  However, I'm now discovering that github won't go look for keys in any key server to verify them...  it requires us to upload them to our accounts.  [sigh]

As for signed releases (as in detached signatures with the tarballs), we do that as well, but on [our site](https://www.openssl.org/source/)...

Remains signed commits.  I won't personally comment on that, but I'm sure other team members may be willing to say a few words.

**Comment by rugk** [comment]
> I'm now discovering that github won't go look for keys in any key server to verify them... it requires us to upload them to our accounts. [sigh]

Actually that's good IMHO as anyone can upload keys on any keyserver, so they have to tie this to your account.

> As for signed releases (as in detached signatures with the tarballs), we do that as well,

Yeah, of course, that's good, but git commit signing would also be nice. I mean otherwise GitHub could (theoretically) introduce backdoors or so. That's explained in this famous story: https://mikegerwitz.com/papers/git-horror-story

**Comment by rugk** [comment]
Basically the issue is you currently trust GitHub. What is when GitHub changes code?
AFAIK Linus Torvalds keeps a trusted copy of Linux source code on his personal computer for that reason. You might hear more [in this talk](https://www.youtube.com/watch?v=4XpnKHJAok8) (I don't know if I choose the right one).

**Comment by mattcaswell** [comment]
> I mean otherwise GitHub could (theoretically) introduce backdoors or so.

That isn't possible. At least it isn't for official releases distributed by OpenSSL. Github is just a mirror of our own repo which we host on our own infrastructure. All releases are created from our repo, not the Github one.

**Comment by rugk** [comment]
Okay, but if people want to use bleeding-edge versions directly from GitHub?

**Comment by mattcaswell** [comment]
Then yes, in theory, although it would be noticed very quickly I imagine. But no-one should be running in production from a version in Github. If you're doing anything other than testing then you should be using an official version.

**Comment by rugk** [comment]
No I am not...

Still commit signing would be a good thing. You can cryptographically prove that someone committed something or so. As said see this story: https://mikegerwitz.com/papers/git-horror-story

**Comment by richsalz** [comment]
Yes, if someone wanted to use a bleeding-edge version directly from github, they could perhaps get tricked.  But as far as OpenSSL is concerned, GitHub is a downstream read-only clone, and any chances some fakes into those repo's will get over-written by the very next real commit.

Our releases are signed.

Not everyone in the team believes, or wants to get involved with, signing every commit and we see no security reason to do so.  Closing this.

**Comment by rugk** [comment]
> GitHub is a downstream read-only clone

But you accept PRs here, so it can't really be 100% read-only... You somehow have to sync these repos.

**Comment by richsalz** [comment]
We pull them down, review the diffs, and merge into our private repo which then pushes out to GitHub.

**Comment by rugk** [comment]
Okay, this is good.
