### ISSUE TITLE
OpenSSL man pages as found by google give 404 error

### ISSUE THREAD

**Issue by hannob** [openssl/openssl#17038]
When I google for openssl command line options - e.g. "openssl genrsa" - I get forwarded to a page url of the form:
https://www.openssl.org/docs/man1.0.2/man1/openssl-genrsa.html

This gives a 404.

I think this should be fixed. I assume this may be because you deprecated old versions of the man pages. However as they are widely linked and found by search engines, I think just removing them is bad. Either forward them to the location of the most current version or re-add them with a note that they refer to an old version and link the current one.

**Comment by paulidale** [comment]
That's an old no longer supported version of OpenSSL.  It's not been supported for several years now.

I don't think this is a problem for OpenSSL to solve, the search engines are pointing to the incorrect location.

**Comment by hannob** [comment]
You shouldn't break existing links, and you absolutely shouldn't break existing links that are top google search results for people looking for documentation. Please forward them to the current version.

**Comment by paulidale** [comment]
You are asking that we maintain links forever and the search engines never need to adapt?  That seems fairly asymmetrical.

Remember that 1.0.2 ceased to be a supported version **two years** ago.  I feel that that is more than enough time for a search engine to recognise that the pages no longer exist.
