### ISSUE TITLE
SSL_connect tls 1.3 return -1 please help me

### ISSUE THREAD

**Issue by budibeta** [openssl/openssl#17039]
hey, i cannot solve this issue more than 30 days, because none people serious help me in this forum.

lets to the point.

1. how to build openssl with tls 1.3 enabled
2. how to use SSL_connect with server use tls 1.3

the server accept tls 1.2 -> SSL_connect work
the server only accept tls 1.3 -> SSL_connect fail return -1
i have using SSL_get_error to check the last error, but it return SSL_ERROR_SSL

please help me, i going to crazy with this problem. why SSL_connect dont work if server only accept tls 1.3

using SSL_connect google.com -> working
using SSL_connect youtube.com -> working
using SSL_connect stackoverflow.com -> working
using SSL_connect github.com -> working

using SSL_connect unknowncheats.me -> **not working**
using SSL_connect cpp.hotexamples.com -> **not working**

i write a ssl proxy server, everything working fine, **except SSL_connect on these websites**, return -1 **because these website is forcing client using tls 1.3 version**. even if they support tls 1.2

please give me the example in c++ language, i have no idea, i should finish my project in ASAP

**Comment by yangyangtiantianlonglong** [comment]
> i have using SSL_get_error to check the last error, but it return SSL_ERROR_SSL

can you get  the error code  to  `ERR_get_error() ` after  the `SSL_connect()`  returns  -1  ?

**Comment by paulidale** [comment]
If you are concerned about how slowly **volunteers** are answering your questions, purchase a support contract.

**Comment by mattcaswell** [comment]
> how to build openssl with tls 1.3 enabled

OpenSSL TLSv1.3 support is enabled by default. You don't need to do anything special.

> how to use SSL_connect with server use tls 1.3

Make sure you use `TLS_client_method()` when creating the `SSL_CTX`. This should work for all TLS protocol versions including TLSv1.3.

If possible please share your code so we can see what you are doing.

>> i have using SSL_get_error to check the last error, but it return SSL_ERROR_SSL
> can you get the error code to ERR_get_error() after the SSL_connect() returns -1 ?

Even better dump the whole error stack using something like `ERR_print_errors_fp(stdout);` and show us what you get.

**Comment by budibeta** [comment]
> > i have using SSL_get_error to check the last error, but it return SSL_ERROR_SSL
> 
> can you get the error code to `ERR_get_error() ` after the `SSL_connect()` returns -1 ?

sorry, i late answer your question because sleep

<img width="505" alt="Screenshot_5" src="https://user-images.githubusercontent.com/68463485/141865280-d439a7c1-7f17-4133-ada0-a27514cf3ec3.png">

<img width="736" alt="Screenshot_6" src="https://user-images.githubusercontent.com/68463485/141865294-1ebf1073-86a8-4386-bc9c-58797dd63be9.png">

**Comment by yangyangtiantianlonglong** [comment]
>  error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

The `336151568`  indicates that the peer end reports an error first. You should use `ERR_get_error()` to obtain the error code of the peer.

**Comment by budibeta** [comment]
> > error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
> 
> The `336151568` indicates that the peer reports an error first. You should use `ERR_get_error()` to obtain the error code of the peer. Or you can use the capture packet to find out which step of the handshake you made a mistake.

wait, what do you mean **You should use ERR_get_error() to obtain the error code of the peer**
did you see I used the ERR_get_error function in the image ?


does that mean I have to enable sslv3, because sslv3 is disabled by default during build.

however, yesterday I just rebuilt, and enabled sslv3, but the result is still the same, ssl_connect error

**Comment by yangyangtiantianlonglong** [comment]
What I want to say is that the error code of the client indicates that an error occurs on the server first. You should obtain the error code of the server.

**Comment by budibeta** [comment]
> What I want to say is that the error code of the client indicates that an error occurs on the server first. You should obtain the error code of the server.

what if you give me a example, because i dont understand what are you said.

**Comment by yangyangtiantianlonglong** [comment]
Here's a private sample for your reference.
https://github.com/TalkWithTLS/TalkWithTLS/blob/master/src/sample/openssl_tls13_server.c
https://github.com/TalkWithTLS/TalkWithTLS/blob/master/src/sample/openssl_tls13_client.c

**Comment by budibeta** [comment]
> I'm guessing you may have a configuration problem. Here's a private sample for your reference. https://github.com/TalkWithTLS/TalkWithTLS/blob/master/src/sample/openssl_tls13_server.c https://github.com/TalkWithTLS/TalkWithTLS/blob/master/src/sample/openssl_tls13_client.c
> 
> You can also use command line to check whether the fault is caused by the server. `openssl s_client -connect ip:port -tls1_3`

very well thanks, i think my code is same as the link reference

and about **error 336151568 error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure**
think i have a problem communicate with sslv3

one last question,
- can you tell me, how to build openssl with sslv3 enabled, i think i have wrong config with sslv3 when building openssl.
- just show me, how to enable sslv3 in build configure and the command line, thanks.

**Comment by paulidale** [comment]
Including SSLv3 is in the INSTALL.md guide.

**Comment by mattcaswell** [comment]
> and about error 336151568 error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

> think i have a problem communicate with sslv3

The error message does *not* indicate that you are attempting to communicate with SSLv3. The error message is slightly misleading in this regards. It just says you've had a handshake failure alert from the server (a handshake failure alert first appeared in SSLv3 but can be used in any SSL/TLS protocol version).

This problems looks like an issue with SNI (Server Name Indication) to me. "s_client" in OpenSSL 1.1.1 and above will automatically send SNI data in the ClientHello. But you do not have code to do this in the sample that you showed.

To demonstrate this I can get a successful connection using s_client like this:

````
$ openssl s_client -connect www.unknowncheats.me:443
````

However, if I disable sending SNI data then the connection fails in the same way that you are experiencing:

````
$ openssl s_client -connect www.unknowncheats.me:443 -noservername
CONNECTED(00000003)
139875020289856:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1543:SSL alert number 40
````

To fix this you should add a call to `SSL_set_tlsext_host_name` prior to your `SSL_connect` call:
https://www.openssl.org/docs/man1.1.1/man3/SSL_set_tlsext_host_name.html

e.g.

````
SSL_set_tlsexthost_name(ssl, "www.unknowncheats.me");
int err = SSL_connect(ssl);
````

**Comment by budibeta** [comment]
> > and about error 336151568 error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
> 
> > think i have a problem communicate with sslv3
> 
> The error message does _not_ indicate that you are attempting to communicate with SSLv3. The error message is slightly misleading in this regards. It just says you've had a handshake failure alert from the server (a handshake failure alert first appeared in SSLv3 but can be used in any SSL/TLS protocol version).
> 
> This problems looks like an issue with SNI (Server Name Indication) to me. "s_client" in OpenSSL 1.1.1 and above will automatically send SNI data in the ClientHello. But you do not have code to do this in the sample that you showed.
> 
> To demonstrate this I can get a successful connection using s_client like this:
> 
> ```
> $ openssl s_client -connect www.unknowncheats.me:443
> ```
> 
> However, if I disable sending SNI data then the connection fails in the same way that you are experiencing:
> 
> ```
> $ openssl s_client -connect www.unknowncheats.me:443 -noservername
> CONNECTED(00000003)
> 139875020289856:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1543:SSL alert number 40
> ```
> 
> To fix this you should add a call to `SSL_set_tlsext_host_name` prior to your `SSL_connect` call: https://www.openssl.org/docs/man1.1.1/man3/SSL_set_tlsext_host_name.html
> 
> e.g.
> 
> ```
> SSL_set_tlsexthost_name(ssl, "www.unknowncheats.me");
> int err = SSL_connect(ssl);
> ```

finally, i got the answer, youre right i should call **SSL_set_tlsext_host_name**
this is the golden answer, iam very thanks.

this is a genius answer, thank you very much for your hard work helping my problem,

i almost gave up for 1 month, and no clue even though i searched from google.

this is the golden answer, i have to call SSL_set_tlsext_host_name before ssl_connect.

very very grateful.
