### ISSUE TITLE
when running this command on encrypting a file with `text` file in my executing `dir` with no extention i got an error....

### ISSUE THREAD

**Issue by nityanand86876** [openssl/openssl#17042]
#### error  : `Can't open test for reading, No such file or directory
140110910460544:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('test','rb')
140110910460544:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:`

**Comment by t8m** [comment]
What is the bug here? Do you have a file `test` in your current directory where you are running the openssl enc command?

**Comment by paulidale** [comment]
It works fine here:
```sh
$ ls file1
ls: cannot access 'file1': No such file or directory
$ touch test
$ openssl enc -aes-256-cbc -e -in test -out file1
enter aes-256-cbc encryption password:
Verifying - enter aes-256-cbc encryption password:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
139910969013568:error:0200B015:system library:fread:Is a directory:../crypto/bio/bss_file.c:149:
139910969013568:error:20082002:BIO routines:file_read:system lib:../crypto/bio/bss_file.c:150:
$ ls file1
file1
```
You don't have a file named `test` where you are running the command.

**Comment by Makatoka** [comment]
Hello please help,
I'm trying to encrypt a txt file with a publickey, and i getting an error
ubuntu@ubuntu:~/test$ openssl rsautl -encrypt -in alice_hash.txt -pubin -inkey publiclovely.pub -out alice_hash_encrypted.txt   
Can't open publiclovely.pub for reading, No such file or directory
140079885243712:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('publiclovely.pub','r')
140079885243712:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load Public Key
--------------- the file is in the test directory
ubuntu@ubuntu:~/test$ dir
alice_encrypted.txt  alice.txt	  passwordkey.key
alice_hash.txt	     lovely.priv  publiclovely.pud
ubuntu@ubuntu:~/test$

**Comment by selvanair** [comment]
> ubuntu@ubuntu:~/test$ dir
> alice_encrypted.txt  alice.txt	  passwordkey.key
> alice_hash.txt	     lovely.priv  publiclovely.pud
                                                          
Typo: `pud` instead of `pub`:
               
You have "publiclovely.pud" in the test directory, but no "publiclovely.pub" which is what you are passing to the OpenSSL command.

**Comment by Makatoka** [comment]
Ho My God,
Thank you
