### ISSUE TITLE
RSA_public_encrypt and RSA_private_decrypted is showing deprecated in current openssl version(3)

### ISSUE THREAD

**Issue by aykejriw-ms** [openssl/openssl#17057]
I am seeing deprecated tag on RSA encrypt and decrypt methods? 

Do you recommend to use these methods as part of development? Or, 
Is there any other method which we should follow for Asymmetric encryption/decryption?

**Comment by paulidale** [comment]
I suggest that you read the answer in the [migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html#Deprecated-low-level-encryption-functions).  There are a lot of differences in 3.0 and while existing code will generally work, there are some differences and lots of deprecations.

**Comment by mattcaswell** [comment]
> I suggest that you read the answer in the migration guide.

Actually looking at the answer in the migration guide it isn't particularly helpful! For `RSA_public_encrypt` and `RSA_private_decrypt` it says "See Deprecated low-level encryption functions". That section says:

> Low-level encryption functions such as AES_encrypt(3) and AES_decrypt(3) have been informally discouraged from use for a long time. Applications should instead use the high level EVP APIs EVP_EncryptInit_ex(3), EVP_EncryptUpdate(3), and EVP_EncryptFinal_ex(3) or EVP_DecryptInit_ex(3), EVP_DecryptUpdate(3) and EVP_DecryptFinal_ex(3).

Which is all about symmetric encryption and isn't relevant to asymmetric encryption!

There should probably be a reference somewhere to `EVP_PKEY_encrypt` and `EVP_PKEY_decrypt` as being the preferred alternatives.
