### ISSUE TITLE
Verify certificate failed in Openssl 3.0.0 When I didn't use default context.

### ISSUE THREAD

**Issue by forston** [openssl/openssl#17068]
Hi Openssl Team

It seems there is a bug when I try to use non-default context to verify certificate.
I used official released version(Openssl 3.0.0).

My compile flag is "perl Configure VC-WIN64A no-asm no-shared no-autoload-config no-pinshared enable-fips"

Following is my certificate verification fuction.
```
void verifyCert(OSSL_LIB_CTX* libctx, const char *propq = NULL)
{
	auto * xstore = X509_STORE_new();
	if (xstore == NULL)
	{
		printf("new x509 store failed.\n");
		return ;
	}

	auto * trustCert = readCert("turstcert.crt");
	if (nullptr == trustCert)
	{
		X509_STORE_free(xstore);
		return;
	}
	else
	{
		X509_STORE_add_cert(xstore, trustCert);
	}

	auto * xstore_ctx = X509_STORE_CTX_new_ex(libctx, propq);
	if (nullptr == xstore_ctx)
	{
		X509_STORE_free(xstore);
		X509_free(trustCert);
		printf("new x509 store context failed.\n");
		return ;
	}

	auto * verifiedCert = readCert("verifiedCert.crt");
	if (nullptr == verifiedCert)
	{
		X509_STORE_free(xstore);
		X509_free(trustCert);
		X509_STORE_CTX_free(xstore_ctx);
		return;
	}

	int iret = X509_STORE_CTX_init(xstore_ctx, xstore, verifiedCert, NULL);
	if (iret == 0)
	{
		X509_STORE_free(xstore);
		X509_free(trustCert);
		X509_free(verifiedCert);
		X509_STORE_CTX_free(xstore_ctx);
		printf("init x509 store context failed.\n");
		return;
	}

	iret = X509_verify_cert(xstore_ctx);
	if (iret == 0)
	{
		auto errcode = X509_STORE_CTX_get_error(xstore_ctx);
		printf("verify certificate failed, error [%d].\n", errcode);
	}
	else
	{
		printf("verify certificate success.\n");
	}

	X509_STORE_free(xstore);
	X509_free(trustCert);
	X509_free(verifiedCert);
	X509_STORE_CTX_free(xstore_ctx);
}
```

Here is my calling fuction. Because I don't want to use default context, so I load a "null" provider in default context.
```
	auto* nonfipslibctx = OSSL_LIB_CTX_new();
	if (nonfipslibctx == nullptr)
	{
		return;
	}

	OSSL_PROVIDER *def;
	def = OSSL_PROVIDER_load(nonfipslibctx, "default");
	if (def == NULL) {
		printf("Failed to load base provider\n");
		exit(EXIT_FAILURE);
	}

	OSSL_PROVIDER *defctxnull = NULL;
	defctxnull = OSSL_PROVIDER_load(NULL, "null");

	{
		EVP_default_properties_enable_fips(nonfipslibctx, 0);
		verifyCert(nonfipslibctx, "fips=no");
	}

	OSSL_PROVIDER_unload(def);
	OSSL_LIB_CTX_free(nonfipslibctx);
```

**In this scenario, it wll get a return code 0 in ```X509_verify_cert```, ```X509_STORE_CTX_get_error(xstore_ctx)``` will return 1.

So when I commit ```//defctxnull = OSSL_PROVIDER_load(NULL, "null");```, it can verify success.**

Can you help to check if it's matched with "https://www.openssl.org/docs/manmaster/man7/fips_module.html#Programmatically-loading-the-FIPS-module-default-library-context".

Best regards
forston

**Comment by mattcaswell** [comment]
Firstly it will be helpful to see the OpenSSL error stack to see what hints it might give to the problem. For example after the failing call you could call `ERR_print_errors_fp(stdout);` to dump the error stack to stdout.

I suspect the problem is related to how `readCert` loads the certificates. My guess is the certificate being read is not being associated with the correct libctx and this is subsequently causing problems. Can you share the code behind `readCert`?

**Comment by forston** [comment]
Hi Mattcaswell
I add the ```ERR_print_errors_fp(stdout);```, it shows the following information:
```E06C0000:error:03000072:digital envelope routines:X509_PUBKEY_get0:decode error:crypto\x509\x_pubkey.c:444:
E06C0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto\evp\evp_fetch.c:346:Global default library context, Algorithm (SHA1 : 96), Properties (<null>)
E06C0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto\evp\evp_fetch.c:346:Global default library context, Algorithm (SHA1 : 96), Properties (<null>)```

It seems that it still used the default context.

Following is the code of ```readCert```, I didn't find any new interface to set context in this scenario.
```
X509 * readCert(const char* filename)
{
	FILE * fp = fopen(filename, "r");
	if (fp == NULL)
	{
		printf("open certificiate file fail\n");
		return NULL;
	}

	X509 * x = PEM_read_X509(fp, NULL, NULL, NULL);
	if (x == NULL)
	{
		fclose(fp);
		printf("read certificiate file fail\n");
		return NULL;
	}

	fclose(fp);

	return x;
}
```


By the way, the "Signature algorithm" of my certificiate is md5RSA and "Signature hash algorithm" is md5. So in no-fips mode ,it should be verified success with default provider. And in fips mode,it should be verified failed with fips provider. 

Please help to check this.

Best regards
forston

**Comment by mattcaswell** [comment]
> Following is the code of readCert, I didn't find any new interface to set context in this scenario.

From the man page for `PEM_read_X509`:
https://www.openssl.org/docs/man3.0/man3/PEM_read_X509.html
> Some operations have additional variants that take a library context libctx and a property query string propq. The X509, X509_REQ and X509_CRL objects may have an associated library context or property query string but there are no variants of these functions that take a library context or property query string parameter. In this case it is possible to set the appropriate library context or property query string by creating an empty X509, X509_REQ or X509_CRL object using X509_new_ex(3), X509_REQ_new_ex(3) or X509_CRL_new_ex(3) respectively. Then pass the empty object as a parameter to the relevant PEM function. See the "EXAMPLES" section below.

So, basically you need to change your `readCert` function to create an empty X509 object with associated libctx using `X509_new_ex()`, and then pass that object as the second parameter to your `PEM_read_X509` call.

**Comment by forston** [comment]
Hi Mattcaswell

Thanks for your help.
After change the code of ```readCert ```, it can get expected result.
Following is new code of  ```readCert ```:

```
X509 * readCert(const char* filename, OSSL_LIB_CTX* libctx, const char *propq = NULL)
{
	FILE * fp = fopen(filename, "r");
	if (fp == NULL)
	{
		printf("open certificiate file fail\n");
		return NULL;
	}
	X509 * x = X509_new_ex(libctx, propq);

	if (PEM_read_X509(fp, &x, NULL, NULL) == NULL)
	{
		fclose(fp);
		printf("read certificiate file fail\n");
		return NULL;
	}

	fclose(fp);

	return x;
}
```

Best regards
forston

**Comment by mattcaswell** [comment]
> After change the code of readCert , it can get expected result.

Great. So can this issue be closed now?

**Comment by forston** [comment]
yes, thanks
