### ISSUE TITLE
signature verification failed > openssl verify

### ISSUE THREAD

**Issue by RafaelMM1991** [openssl/openssl#17076]
Hello, we have a RSA signature verification fail in the following versions:
- OpenSSL 1.1.1f
- OpenSSL 3.0.0-alpha17
 
However in previous versions (to 1.1.1f), it does not show.

Complete error in ver. OpenSSL 1.1.1f:
error 7 at 0 depth lookup: certificate signature failure
140010599073088:error:04091068:rsa routines:int_rsa_verify:bad signature:../crypto/rsa/rsa_sign.c:220:
140010599073088:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:../crypto/asn1/a_verify.c:170:

Command issued:
openssl verify -verbose -CAfile CA.pem SUBCA.cer

**Comment by t8m** [comment]
Which are the latest openssl versions from the 1.1.1 branch that work for you?

**Comment by t8m** [comment]
The signature is invalid even when verified by GnuTLS certtool:
```
certtool --verify-chain --infile chain.pem 
Note that no verification profile was selected. In the future the medium profile will be enabled by default.
Use --verify-profile low to apply the default verification of NORMAL priority string.
	Subject: CN=vinCAsign nebulaSUITE2 Authority,O=VINTEGRIS SL,OU=vinCAsign,2.5.4.97=#0c0f56415445532d423632393133393236,L=HOSPITALET DE LLOBREGAT,ST=BARCELONA,C=ES
	Issuer: ST=Barcelona,CN=vinCAsign Qualified Authority,2.5.4.97=#0c0f56415445532d423632393133393236,L=Hospitalet de Llobregat,O=Víntegris SL,C=ES
	Checked against: ST=Barcelona,CN=vinCAsign Qualified Authority,2.5.4.97=#0c0f56415445532d423632393133393236,L=Hospitalet de Llobregat,O=Víntegris SL,C=ES
	Signature algorithm: RSA-SHA256
	Output: Not verified. The certificate is NOT trusted. The signature in the certificate is invalid. 

Chain verification output: Not verified. The certificate is NOT trusted. The signature in the certificate is invalid. 
```

**Comment by t8m** [comment]
If it was accepted by some earlier versions it was most probably accepted erroneously.

**Comment by vintegrisRMM** [comment]
Thank you, sir.
