### ISSUE TITLE
Using engine-provided keys in applications with OpenSSL 3.0

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#17081]
I fully understand that engines are deprecated in 3.0, but I see that the `-keyform engine` option is supported in command line applications. The keys are loaded via `ENGINE` loader present in `apps/lib`, and the loaded keys are legacy keys (though they may be, say, RSA keys). 

Can we do something to make engine-backed RSA keys work in 3rd-party applications?

**Comment by mattcaswell** [comment]
> Can we do something to make engine-backed RSA keys work in 3rd-party applications?

In what way do they not? I'm aware of #16738. Are there other reasons this doesn't work?

**Comment by beldmit** [comment]
If we have a PKCS#11-backed key, how do we get a legacy EVP_PKEY object from the engine (with some sort of handle)?

**Comment by beldmit** [comment]
E.g. the following Nginx config worked with 1.1.1 and does not work with 3.0.0:

```
server {
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        **ssl_certificate "engine:pkcs11:pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=883ea9a73e9cd15e;token=softhsm;id=%D0%EB%12%A0%BF%19%BC%14%C6%76%B2%ED%EA%4C%7D%4B%36%7D%1F%24;object=nginx;type=cert";**
        **ssl_certificate_key "engine:pkcs11:pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=883ea9a73e9cd15e;token=softhsm;id=%D0%EB%12%A0%BF%19%BC%14%C6%76%B2%ED%EA%4C%7D%4B%36%7D%1F%24;object=nginx;type=private?pin-value=123456";**
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers PROFILE=SYSTEM;
        ssl_prefer_server_ciphers on;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```

**Comment by mdounin** [comment]
In nginx, we use OPENSSL_SUPPRESS_DEPRECATED to suppress deprecation warnings about engines API, see [here](http://hg.nginx.org/nginx/rev/8f7107617550). This matches what `apps/engine.c` does and seems to be the only way to properly use engines API with OpenSSL 3.0.

Unless OpenSSL is built with `--no-deprecated` (which disables engines support completely), engines should work fine in nginx. Note though, that `ssl_certificate "engine:...` part is a configuration error in all nginx versions, as nginx only support loading keys from OpenSSL engines, not certificates.

**Comment by petrovr** [comment]
Currently "engine" keys are broken, and least rsa and dsa.

**Comment by mattcaswell** [comment]
> Currently "engine" keys are broken, and least rsa and dsa.

Broken how? Is there a specific issue number you are referring to?

**Comment by beldmit** [comment]
@mattcaswell  https://bugzilla.redhat.com/show_bug.cgi?id=2019369

**Comment by mattcaswell** [comment]
That issue seems to be s390 specific? We don't have access to s390 so that's going to be tricky to solve without some help from an s390 person! Or can the same problem be replicated on other platforms?

**Comment by beldmit** [comment]
Exactly this issue seems s390 specific. As far as I understand, the engine replaces RSA_METHOD, but openssh uses EVP API here - so offload does not happen. 

The PKCS#11 case seems more interesting for me - they work via engine key format and legacy keys are created, so everything works in openssl. 

In Nginx there was added a support for PKCS#11-based certs (https://gitlab.com/redhat/centos-stream/rpms/nginx/-/blob/c9s/0003-Support-loading-cert-hardware-token-PKC.patch) and there soon became necessary to amend this patch (https://gitlab.com/redhat/centos-stream/rpms/nginx/-/blob/c9s/0005-Init-openssl-engine-properly.patch) for 3.0.0 compatibility.

What we really need is a guideline describing

- How we use engine-backed keys for legacy
- MVP to stop using legacy (rewrite engine to provider, implementing funcs ...)
- How we use legacy HW accelerators (e.g. they will work if ...)
- MVP to turn legacy to provider

**Comment by mattcaswell** [comment]
> As far as I understand, the engine replaces RSA_METHOD, but openssh uses EVP API here - so offload does not happen.

This sounds wrong. If you use a custom RSA_METHOD then it should still be used regardless of whether you use EVP or not. So if that isn't happening it sounds like a bug.

**Comment by beldmit** [comment]
@p-steuer could you please assist with the possible debugging here?

**Comment by mattcaswell** [comment]
> This sounds wrong. If you use a custom RSA_METHOD then it should still be used regardless of whether you use EVP or not. So if that isn't happening it sounds like a bug.

Just to explore this further I created some test code to try out different methods of creating a key and setting the RSA_METHOD to be used by the key:

```` C
#include <openssl/rsa.h>
#include <openssl/evp.h>
#include <openssl/engine.h>
#include <openssl/param_build.h>
#include <string.h>

int my_rsa_priv_enc(int flen, const unsigned char *from, unsigned char *to,
                    RSA *rsa, int padding)
{
    printf("my_rsa_priv_enc was called\n");
    return 1;
}

int main(int argc, char *argv[])
{
    RSA_METHOD *meth = RSA_meth_new("my RSA meth", 0);
    RSA *key;
    EVP_PKEY *pkey = EVP_PKEY_new();
    EVP_PKEY_CTX *ctx;
    unsigned char sig[80];
    size_t siglen = sizeof(sig);
    BIGNUM *n = BN_new(), *e = BN_new();
    ENGINE *eng = NULL;

    if (argc != 3)
        goto usage;

    if (meth == NULL || pkey == NULL || n == NULL || e == NULL)
        abort();

    if (!BN_set_word(n, 1) || !BN_set_word(e, 1))
        abort();

    if (!RSA_meth_set_priv_enc(meth, my_rsa_priv_enc))
        abort();

    if (strcmp(argv[1], "defmeth") == 0) {
        printf("Setting a default RSA method\n");
        RSA_set_default_method(meth);
    } else if (strcmp(argv[1], "engmeth") == 0) {
        printf("Setting a default ENGINE RSA method\n");
        eng = ENGINE_new();

        if (eng == NULL)
            abort();

        if (!ENGINE_set_RSA(eng, meth))
            abort();
        if (!ENGINE_set_default_RSA(eng))
            abort();
    } else {
        goto usage;
    }

    if (strcmp(argv[2], "legkey") == 0) {
        printf("Creating a legacy RSA key\n");
        key = RSA_new();
        if (key == NULL)
            abort();

        if (!RSA_set0_key(key, n, e, NULL))
            abort();

        if (!EVP_PKEY_set1_RSA(pkey, key))
            abort();
    } else if (strcmp(argv[2], "provkey") == 0) {
        OSSL_PARAM_BLD *param_bld;
        OSSL_PARAM *params = NULL;

        printf("Creating a provided RSA key\n");
        param_bld = OSSL_PARAM_BLD_new();
        if (param_bld == NULL)
            abort();
        if (!OSSL_PARAM_BLD_push_BN(param_bld, "n", n)
                || !OSSL_PARAM_BLD_push_BN(param_bld, "e", e))
            abort();
        params = OSSL_PARAM_BLD_to_param(param_bld);
        if (params == NULL)
            abort();

        ctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL);
        if (ctx == NULL)
            abort();

        if (!EVP_PKEY_fromdata_init(ctx))
            abort();
        if (!EVP_PKEY_fromdata(ctx, &pkey, EVP_PKEY_PUBLIC_KEY, params))
            abort();
        EVP_PKEY_CTX_free(ctx);
    } else {
        goto usage;
    }


    ctx = EVP_PKEY_CTX_new(pkey, NULL);
    if (ctx == NULL)
        abort();

    if (EVP_PKEY_sign_init(ctx) <= 0)
        abort();

    if (EVP_PKEY_sign(ctx, sig, &siglen, NULL, 0) <= 0)
        abort();

    return 0;
 usage:
    printf("Usage: rsameth [defmeth|engmeth] [legkey|provkey]\n");
    return 1;
}
````
So this test code sets the RSA method either via `RSA_set_default_method` or via `ENGINE_set_default_RSA`, and then creates either a legacy RSA key or a provided RSA key.

Running this code I get this output:
```` sh
$ ./rsameth defmeth legkey
Setting a default RSA method
Creating a legacy RSA key
my_rsa_priv_enc was called

$ ./rsameth engmeth legkey
Setting a default ENGINE RSA method
Creating a legacy RSA key
my_rsa_priv_enc was called

$ ./rsameth defmeth provkey
Setting a default RSA method
Creating a provided RSA key
my_rsa_priv_enc was called

 ./rsameth engmeth provkey
Setting a default ENGINE RSA method
Creating a provided RSA key
my_rsa_priv_enc was called
````
So, no matter what I try, it seems the custom RSA_METHOD is always used. If you use a provided key then the above will only happen with the default provider. If you use a provided key and the FIPS provider, or a custom provider then you'll get provider specific behaviour - but I think that is the correct thing to do.

**Comment by t8m** [comment]
Also since there were definitely some related fixes committed in openssl-3.0 branch since the 3.0.0 release, which code are we talking about here?

(A side note, should we do 3.0.1 soon?)

**Comment by beldmit** [comment]
https://github.com/openssh/openssh-portable/blob/b7ffbb17e37f59249c31f1ff59d6c5d80888f689/sshkey.c#L4603-L4633 is how RSA object is obtained from file/blob. 

If I understand correctly, it will not use the engine-provided RSA_METHOD

**Comment by beldmit** [comment]
#17107 is related stuff

**Comment by mattcaswell** [comment]
I extended my reproducer code to instead load the key using `PEM_read_bio_PrivateKey`. Updated version:

```` C
#include <openssl/rsa.h>
#include <openssl/evp.h>
#include <openssl/engine.h>
#include <openssl/param_build.h>
#include <string.h>

int my_rsa_priv_enc(int flen, const unsigned char *from, unsigned char *to,
                    RSA *rsa, int padding)
{
    printf("my_rsa_priv_enc was called\n");
    return 1;
}

int main(int argc, char *argv[])
{
    RSA_METHOD *meth = RSA_meth_new("my RSA meth", 0);
    RSA *key;
    EVP_PKEY *pkey = EVP_PKEY_new();
    EVP_PKEY_CTX *ctx;
    unsigned char sig[512];
    size_t siglen = sizeof(sig);
    BIGNUM *n = BN_new(), *e = BN_new();
    ENGINE *eng = NULL;

    if (argc != 3)
        goto usage;

    if (meth == NULL || pkey == NULL || n == NULL || e == NULL)
        abort();

    if (!BN_set_word(n, 1) || !BN_set_word(e, 1))
        abort();

    if (!RSA_meth_set_priv_enc(meth, my_rsa_priv_enc))
        abort();

    if (strcmp(argv[1], "defmeth") == 0) {
        printf("Setting a default RSA method\n");
        RSA_set_default_method(meth);
    } else if (strcmp(argv[1], "engmeth") == 0) {
        printf("Setting a default ENGINE RSA method\n");
        eng = ENGINE_new();

        if (eng == NULL)
            abort();

        if (!ENGINE_set_RSA(eng, meth))
            abort();
        if (!ENGINE_set_default_RSA(eng))
            abort();
    } else {
        goto usage;
    }

    if (strcmp(argv[2], "legkey") == 0) {
        printf("Creating a legacy RSA key\n");
        key = RSA_new();
        if (key == NULL)
            abort();

        if (!RSA_set0_key(key, n, e, NULL))
            abort();

        if (!EVP_PKEY_set1_RSA(pkey, key))
            abort();
    } else if (strcmp(argv[2], "provkey") == 0) {
        OSSL_PARAM_BLD *param_bld;
        OSSL_PARAM *params = NULL;

        printf("Creating a provided RSA key\n");
        param_bld = OSSL_PARAM_BLD_new();
        if (param_bld == NULL)
            abort();
        if (!OSSL_PARAM_BLD_push_BN(param_bld, "n", n)
                || !OSSL_PARAM_BLD_push_BN(param_bld, "e", e))
            abort();
        params = OSSL_PARAM_BLD_to_param(param_bld);
        if (params == NULL)
            abort();

        ctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL);
        if (ctx == NULL)
            abort();

        if (!EVP_PKEY_fromdata_init(ctx))
            abort();
        if (!EVP_PKEY_fromdata(ctx, &pkey, EVP_PKEY_PUBLIC_KEY, params))
            abort();
        EVP_PKEY_CTX_free(ctx);
    } else if (strcmp(argv[2], "filekey") == 0) {
        BIO * bio = BIO_new_file("key.pem", "r");

        if (bio == NULL)
            abort();
        pkey = PEM_read_bio_PrivateKey(bio, NULL, NULL, NULL);
        BIO_free(bio);
        if (pkey == NULL)
            abort();
    } else {
        goto usage;
    }


    ctx = EVP_PKEY_CTX_new(pkey, NULL);
    if (ctx == NULL)
        abort();

    if (EVP_PKEY_sign_init(ctx) <= 0)
        abort();

    if (EVP_PKEY_sign(ctx, sig, &siglen, NULL, 0) <= 0)
        abort();

    return 0;
 usage:
    printf("Usage: rsameth [defmeth|engmeth] [legkey|provkey|filekey]\n");
    return 1;
}
````

This approach also successfully uses a custom RSA_METHOD:
````
$ ./rsameth defmeth filekey
Setting a default RSA method
my_rsa_priv_enc was called

$ ./rsameth engmeth filekey
Setting a default ENGINE RSA method
my_rsa_priv_enc was called
````

So, it seems to me, something else is going wrong in openssh case. It does not appear related to how OpenSSH loads the key.

**Comment by beldmit** [comment]
I will continue the investigation, thanks @mattcaswell

**Comment by beldmit** [comment]
OK. OpenSSH 8.7 seems to work well and use the HW acceleration. Thanks!

**Comment by petrovr** [comment]
> > This sounds wrong. If you use a custom RSA_METHOD then it should still be used regardless of whether you use EVP or not. So if that isn't happening it sounds like a bug.
> 
> Just to explore this further I created some test code to try out different methods of creating a key and setting the RSA_METHOD to be used by the key:
> 
> ```c
> #include <openssl/rsa.h>
> #include <openssl/evp.h>
> #include <openssl/engine.h>
> #include <openssl/param_build.h>
> #include <string.h>
> 
> int my_rsa_priv_enc(int flen, const unsigned char *from, unsigned char *to,
>                     RSA *rsa, int padding)
> {
>     printf("my_rsa_priv_enc was called\n");
>     return 1;
> }
> 
> int main(int argc, char *argv[])
> {
>     RSA_METHOD *meth = RSA_meth_new("my RSA meth", 0);
>     RSA *key;
>     EVP_PKEY *pkey = EVP_PKEY_new();
...

Sample does not make sence in context of "external keys"!.

Report  "E.g. the following Nginx config worked with 1.1.1 and does not work with 3.0.0:" is for pkcs11 engine and as is already reported "external keys" are broken in 3* release.
