### ISSUE TITLE
broken engine provided "external keys" in stable 3.0

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#17092]
Once again I try to get e_nss engine working with master branch but as usually tests fail.
So far so good it is development branch.

Issue is that stable(release) 3.0 branch is also broken - 7 tests fail.

sign-rsa-sha256.out:
```
Error signing data
404A3B57F92A0000:error:4000007B:E_NSS:nss_rsa_sign:Missing private key:.../origin-testing/engines/e_nss_rsa.c:488:
404A3B57F92A0000:error:1C880004:Provider routines:rsa_sign:RSA lib:providers/implementations/signature/rsa_sig.c:580:
TRACE_E_NSS:NSS_KEYCTX_free_rsa()  idx: 1, ptr: 0xa8bc70
```
vrfy-rsa-sha256.out:
```
TRACE_E_NSS:nss_rsa_init()  ^ ok
40CA675D9C2B0000:error:4000007A:E_NSS:nss_rsa_verify:Missing public key:.../origin-testing/engines/e_nss_rsa.c:624:
40CA675D9C2B0000:error:1C880004:Provider routines:rsa_verify:RSA lib:providers/implementations/signature/rsa_sig.c:766:
TRACE_E_NSS:NSS_KEYCTX_free_rsa()  idx: 1, ptr: 0x1db1980
```

So RSA is broken.

sign-dsa-sha1.out:
```
TRACE_E_NSS:nss_dsa_init()  ^ ok
Error signing data
409A87DF522B0000:error:4000007B:E_NSS:nss_dsa_do_sign:Missing private key:.../origin-testing/engines/e_nss_dsa.c:275:
TRACE_E_NSS:NSS_KEYCTX_free_dsa()  idx: 1, ptr: 0x266cc70
```
For DSA error is similar to RSA but there is no OpenSSL error.
Remark: dsa verify pass

No issue with EC keys.

**Comment by t8m** [comment]
Is this a regression on the 3.0 branch? Did it work with the openssl-3.0.0 release?

**Comment by petrovr** [comment]
Hint: key methods use application specific data. Error indicate that this is partially broken.

See OpenSSL CAPI engine. It is expected to fail on same operarions.

Dunno why projects does not test CAPI on windows.

**Comment by petrovr** [comment]
For protocal regression tests pass after correction in #14632 .

**Comment by petrovr** [comment]
Another report https://github.com/openssl/openssl/issues/17081#issuecomment-974277880 .

Unfortunately setup of pkcs11 engine tests against specific openssl version requires a lot of work. 
NSS engine allows you to build and tests with nss and openssl library and commands from custom locations.
Remark: add configuration options --enable-tests .

Dunno why e_nss EC tests pass. I will opens another issue with error for EC keys - different program code.

**Comment by petrovr** [comment]
Jush pushed some extra 'trace' lines to e_nss code activated with DEBUG=3 configuration option.
Remark: requires so called trace build.
Also standard error from commands is logged in separate file.

Results,in failed cases, for instance sign-rsa-sha1.err:
...
TRACE_E_NSS:nss_pass_func_ui_method()  UI result[0]='testing'
TRACE[e_nss] nss_load_key(): pvtkey=0x1af3400
TRACE[e_nss] nss_load_key(): pubkey=0x1af4850
TRACE[e_nss] nss_load_key(): q=0x1af3f40
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x1b0db20
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE[e_nss] nss_load_key(): pkey=0x1b0d6d0
TRACE_E_NSS:nss_load_key()  TRACE EVP_PKEY_{|base_}id(pkey)=6|6
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x1af3bf0
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE[e_nss] nss_load_key(): **keyctx=0x1af3bf0   <<< after keyload >>>**
TRACE[e_nss] nss_load_key(): keyctx->pvtkey=0x1af3400
TRACE[e_nss] nss_load_key(): keyctx->pubkey=0x1af4850
TRACE[e_nss] nss_load_key(): ^ pkey=0x1b0d6d0
TRACE[e_nss] nss_rsa_sign(): args: dtype=64, m=0x7ffcec3d4a00, m_length=20
TRACE[e_nss] nss_rsa_sign(): rsa=0x1b0da30, meth=0x1a29eb0, name=NSS PKCS#1 RSA method
TRACE[e_nss] nss_rsa_sign(): **keyctx=_0x1b0db20_   <<< for key operation, changed! >>>**
TRACE[e_nss] nss_rsa_sign(): keyctx->pvtkey=0x0
TRACE[e_nss] nss_rsa_sign(): ret=0
Error signing data
407AC5B5362B0000:error:4000007B:E_NSS:nss_rsa_sign:Missing private key:/work/src/MyProjects/e_nss/anon-access/origin-testing/engines/e_nss_rsa.c:492:
407AC5B5362B0000:error:1C880004:Provider routines:rsa_sign:RSA lib:providers/implementations/signature/rsa_sig.c:580:
TRACE_E_NSS:NSS_KEYCTX_free_rsa()  idx: 1, ptr: 0x1af3bf0
TRACE_E_NSS:NSS_KEYCTX_free_rsa()  idx: 1, ptr: 0x1b0db20
TRACE_E_NSS:nss_finish()  ...
...
As is visible in key operation application data is lost, i.e. RSA_get_ex_data.

Result in case of success, for instance sign-ec1-sha256.err
...
TRACE_E_NSS:nss_pass_func_ui_method()  UI result[0]='testing'
TRACE[e_nss] nss_load_key(): pvtkey=0x10d7850
TRACE[e_nss] nss_load_key(): pubkey=0x10d6400
TRACE[e_nss] nss_load_key(): q=0x10d8280
TRACE_E_NSS:nss_ec_init()  ...
TRACE_E_NSS:nss_ec_init()  idx: 1, ptr: 0x10f02d0
TRACE_E_NSS:nss_ec_init()  ^ ok
TRACE[e_nss] nss_load_key(): pkey=0x10f0460
TRACE_E_NSS:nss_load_key()  TRACE EVP_PKEY_{|base_}id(pkey)=408|408
TRACE_E_NSS:nss_ec_init()  ...
TRACE_E_NSS:nss_ec_init()  idx: 1, ptr: 0x10d8040
TRACE_E_NSS:nss_ec_init()  ^ ok
TRACE_E_NSS:nss_ec_init()  ...
TRACE_E_NSS:nss_ec_init()  idx: 1, ptr: 0x10ddd60
TRACE_E_NSS:nss_ec_init()  ^ ok
TRACE_E_NSS:NSS_KEYCTX_free_ec()  idx: 1, ptr: 0x10f02d0
TRACE_E_NSS:NSS_KEYCTX_free_ec()  idx: 1, ptr: 0x10d8040
TRACE[e_nss] nss_load_key(): **keyctx=0x10ddd60  <<< after keyload >>>**
TRACE[e_nss] nss_load_key(): keyctx->pvtkey=0x10d7850
TRACE[e_nss] nss_load_key(): keyctx->pubkey=0x10d6400
TRACE[e_nss] nss_load_key(): ^ pkey=0x10f0460
TRACE[e_nss] nss_ecdsa_do_sign(): args: dlen=32
TRACE[e_nss] nss_ecdsa_do_sign(): eckey=0x10f00e0, inv=0x0, rp=0x0
TRACE[e_nss] nss_ecdsa_do_sign(): **keyctx=0x10ddd60 <<< for key operation, i.e. match loaded context >>>**
TRACE[e_nss] nss_ecdsa_do_sign(): keyctx->pvtkey=0x10d7850
TRACE[e_nss] nss_ecdsa_do_sign(): keyctx->pvtkey->keyType=6
TRACE[e_nss] nss_ecdsa_do_sign(): rv=0
TRACE[e_nss] nss_ecdsa_do_sign(): result.len=64
TRACE_E_NSS:NSS_KEYCTX_free_ec()  idx: 1, ptr: 0x10ddd60
TRACE_E_NSS:nss_finish()  ...
...

**Comment by petrovr** [comment]
See [my comment for explicit set of key method](https://github.com/openssl/openssl/issues/18028#issuecomment-1097617180)

**Comment by beldmit** [comment]
@petrovr could you please help me with reproducing this?

I tried this code
```
static int test_custom_legacy_meth(int idx)
{
    EVP_PKEY *pkey = NULL;
    int testresult = 0;
    RSA *rsa = NULL;
    RSA_METHOD *meth = NULL;

    /* We call deprecated APIs so this test doesn't support a custom libctx */
    if (testctx != NULL)
        return 1;

    switch (idx) {
    case 0:
        pkey = load_example_rsa_key();
        break;
    default:
        TEST_error("Should not happen");
        goto err;
    }

    if (!TEST_ptr(pkey))
        goto err;

    if (idx == 0) {
        meth = RSA_meth_dup(RSA_get_default_method());
       rsa = EVP_PKEY_get1_RSA(pkey);

        RSA_set_method(rsa, meth);
        EVP_PKEY_set1_RSA(pkey, rsa);

        rsa = EVP_PKEY_get1_RSA(pkey);
       TEST_ptr_eq(RSA_get_method(rsa), meth);
    }

    testresult = 1;

 err:
    RSA_free(rsa);
    RSA_meth_free(meth);
    EVP_PKEY_free(pkey);
    return testresult;
}

```
But it's not enough to trigger the problem you are writing about. 
So how did you get the EVP_PKEY object with both keymgmt set and method cleared?

**Comment by petrovr** [comment]
The question is does QAPI engine part of OpenSSL code works with OpenSSL 3.0. From functional point of view E_NSS engine is same.

About sample code - it must not implement work-around. Long time ago I share a generic work-around with OpenSMTPD project - https://github.com/OpenSMTPD/OpenSMTPD/issues/1171#issuecomment-1274318925 .

**Comment by petrovr** [comment]
In particular case for E_NSS engine: Work-around is same but it is was enough to comment optimisations - see 
commit [work-around for buggy engine related key management in OpenSSL 3+](https://gitlab.com/e_nss/e_nss/-/commit/d1a73467ab0c7bdd4b03cde426d00654cb68c768). 

Remark: general issue is https://github.com/openssl/openssl/issues/17286 .
Tested code is more suitable to show work-around  in general.

**Comment by petrovr** [comment]
Now about engines. 
Usually working with external key code convert from key material DER to internal representation. For instance used methods are d2i_PUBKEY, d2i_X509 and d2i_X509_bio.  Method d2i_X509_AUX is not usefull for external DER representation.

E_NSS and CAPI engines set ENGINE_FLAGS_NO_REGISTER_ALL. It seems to me but this is not enough. Still exist cases when engine method is set on key material! If I remember well issue is not new one.

----

And now code to reproduce:
- setup configuration that defines engine with RSA key support.
- initialise engine in configuration (also test without this part)
- call d2i_PUBKEY or d2i_X509 ... 
- check PKEY structure attributes

Expected is **null key manager attribute** if key methods is different from OpenSSL implementation.

**Comment by beldmit** [comment]
Do I correctly understand that all 4 openssl issues mentioned in https://github.com/OpenSMTPD/OpenSMTPD/issues/1171 are engine-related?

**Comment by beldmit** [comment]
@petrovr 
I've built e_nss and commented out your workaround, and see RSA tests failures.
```
$ CONFIG_DIR=`pwd`/tests/nssdb OPENSSL_ENGINES=`pwd`/engines/.libs/ openssl dgst -sha256 -sign "E_NSS Certificate (client-rsa) - E_NSS Test Team cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω" -keyform ENGINE -engine e_nss -passin file:tests/nsspassfile /home/dbelyavs/upstream/e_nss-4.2/tests/openssl.cnf
```
gives me output
```
Engine "e_nss" set.
Could not read private key from org.openssl.engine:e_nss:E_NSS Certificate (client-rsa) - E_NSS Test Team cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω
80FB90535E7F0000:error:40000065:E_NSS:nss_load_key:DB is not initialized:e_nss_key.c:24:
80FB90535E7F0000:error:13000080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:79:
```

How do I setup the test db?

**Comment by beldmit** [comment]
nevermind, forgot to set OPENSSL_CONF

**Comment by beldmit** [comment]
Intermediate debug state:
`load_key` function from `apps/lib/apps.c` creates non-legacy key even for engine-loaded keys created via `ENGINE_load_private_key`

**Comment by beldmit** [comment]
Would you mind to test https://github.com/openssl/openssl/pull/19965 instead of your workaround? I've succeeded sign using NSS RSA key after removing your workaround

**Comment by petrovr** [comment]
Please note that my spare time is limited and this prevents immediate responses. 
In [p #19965 ](https://github.com/openssl/openssl/pull/19965) code changes ENGINE_load_private_key. 

E_NSS engine provides Store API as well - [e_nss_store.c](https://gitlab.com/e_nss/e_nss/-/blob/master/engines/e_nss_store.c).
Path is:
**nss_store_load_pkey**()
..+-> **nss_load_privkey_c**()
....+-> nss_load_key() ...
......+-> d2i_PUBKEY ...

Engine related code is:
**nss_load_privkey**() as "ENGINE" load_privkey function
..+-> **nss_load_privkey_c**() ...

OpenSSL could control engine load code but does not control store related code.
With other words I think that "work-around" must be keep.

**Comment by beldmit** [comment]
Sure, take your time.

If I'm no mistaken, i've seen `nss_load_privkey` in the call stack from `ENGINE_load_private_key`

I think that if we could move the legacy key detection to OpenSSL, it would be the best solution.

**Comment by petrovr** [comment]
build hint:
  CPPFLAGS="$CPPFLAGS -DENABLE_CALL_TRACE"
  CPPFLAGS="$CPPFLAGS -DENABLE_NSS_TRACE"

in nss_init_keyctx_rsa comment #ifndef HAVE_EVP_KEYMGMT_GET0_PROVIDER and closing #endif

test hint:
Update tests/openssl.cnf.in and uncomment DEBUG = 3

Let read sign-rsa-sha1.err :
...
DEBUG[e_nss] Signer's certificate found.
TRACE[e_nss] nss_load_key(): wincx=0x7ffcbed74ca0
TRACE_E_NSS:nss_pass_func()  args: slot=0x12182a0, retry=0, arg=0x7ffcbed74ca0
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetSlotName()='NSS User Private Key and Certificate Services'
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetTokenName()='NSS Certificate DB'
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetMinimumPwdLength()=0
TRACE_E_NSS:nss_pass_func_ui_method()  NSS_UI ui_method=0x1185d20, ui_data=0x7ffcbed74dc0
TRACE_E_NSS:nss_pass_func_ui_method()  prompt='Enter pass phrase for NSS Certificate DB:'
TRACE_E_NSS:nss_pass_func_ui_method()  buf1='testing'
TRACE_E_NSS:nss_pass_func_ui_method()  UI result[0]='testing'
TRACE[e_nss] nss_load_key(): pvtkey=0x1222520
TRACE[e_nss] nss_load_key(): pubkey=0x12210c0
TRACE[e_nss] nss_load_key(): q=0x1223510
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x1234210
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE[e_nss] nss_load_key(): pkey=0x1233dc0
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x1233390
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE_E_NSS:nss_init_keyctx_rsa()  RSA by default!
TRACE[e_nss] nss_load_key(): keyctx=0x1233390
TRACE[e_nss] nss_load_key(): keyctx->pvtkey=0x1222520
TRACE[e_nss] nss_load_key(): keyctx->pubkey=0x12210c0
TRACE[e_nss] nss_load_key(): ^ pkey=0x1233dc0
TRACE[e_nss] nss_rsa_sign(): args: dtype=64, m=0x7ffcbed74d20, m_length=20
TRACE[e_nss] nss_rsa_sign(): rsa=0x1234120, meth=0x1185fc0, name=NSS PKCS#1 RSA method
TRACE[e_nss] nss_rsa_sign(): keyctx=0x1234210
TRACE[e_nss] nss_rsa_sign(): keyctx->pvtkey=0x0
TRACE[e_nss] nss_rsa_sign(): ret=0
Error signing data
...

1.  Line TRACE[e_nss] nss_load_key(): q= ... is before conversion
2.  Line TRACE[e_nss] nss_load_key(): pkey= ... is after conversion
3.  Lines between are with nss_rsa_init, i.e. engine method is called. So during conversion OpenSSL code knows engine.

Please check pkey attribute on point 2. It is set!
The only function called is EVP_PKEY_get_base_id just after d2i_PUBKEY.

**Comment by petrovr** [comment]
Some more build details .

As build uses autotool "cash values" could be used. Let see builds with OpenSSL build tree:
```code:sh
    CPPFLAGS="$CPPFLAGS -I$opensslPREFIX/include"
    LDFLAGS="$LDFLAGS -L$opensslPREFIX"
    LDFLAGS="$LDFLAGS -Wl,-rpath,$opensslPREFIX"
    OPENSSL=$opensslPREFIX/util/opensslwrap.sh
```
Next is to set build environment, for instance path to OPENSSL program:
```code:sh
ac_cv_prog_OPENSSL=$OPENSSL
export ac_cv_prog_OPENSSL
```

Now configuration:
```code:sh
CPPFLAGS="$CPPFLAGS" \
LDFLAGS="$LDFLAGS" \
../condifure ... --enable-tests ... 
```

Above options to activate tests.

Check library dependencies:
$ ldd engines/.libs/e_nss.so 

One of tests, i.e. "echo" is to dump test environment. See result:
$ cat tests/echo.log

----
Hint: fgrep \_cv\_ config.log could help to tune builds.

**Comment by beldmit** [comment]
Thanks for your hint, I successfully built and tested the engine. I prefer use the locally built OpenSSL explicitly, and I see that the error you reported has gone with my patch. Could you please check?

**Comment by petrovr** [comment]
"Store" tests pass as goal is to output "public" part. Also these test shows that same as operation tests. For instance key load log is same in tests/sto-rsa-key.err.

**Comment by beldmit** [comment]
I have the signing test passed with my patch being executed directly
