### ISSUE TITLE
lost manual pages for X509 conversion functions

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#17091]
For instance let try to find manual page for d2i_X509_bio .

One of returned links is to OpenSSL site.

Issue is not to fact that OpenSSL site return error 404.
It is normal manual pages for old version to be removed.

It is not about that fact that OpenSSL site lack permanet redirection from removed to recent manual pages.
Issue is due to fact that after modification of URL to use 1.1.1 instead 1.0.2 site still return error.

Also on man3 listing is easy visible that page is missing.

**Comment by petrovr** [comment]
It seems to me pageas are lost long time ago with a mass update to a "generic TYPE page".
X509 is also ASN1 structure and dunno why is not in the list.

Not checked if other ASN1 structures are not listed.

**Comment by levitte** [comment]
Do note that `d2i_TYPE_bio` isn't part of what gets declared automatically with macros like `DECLARE_ASN1_FUNCTIONS` (nor implemented automatically with `IMPLEMENT_ASN1_FUNCTIONS`...

That being said, this appears to be a blunder that no one noticed.  The git log tells me that this happened with commit 4692340e31985681f95008d409483d5761b6c213, which was a fairly huge cleanup task.
In 3.0 source, we have a few files that list undocumented functions (all the `util/missing*.txt`)...  it would probably not be a hard task to take those lists and check against an 1.0.2 checkout to see if more documentation was erroneously dropped.

**Comment by levitte** [comment]
BTW, the same happened with `i2d_X509_bio` and `i2d_X509_fp`

**Comment by levitte** [comment]
Fixup for 1.1.1 in #17093, Fixup for 3.0 and master in ¤17094

**Comment by peterdjalaliev** [comment]
From the 1962 unique function/macro names in the util/missing*.txt files in the master branch, 35 were documented in the 1.0.2 man pages:

ASN1_STRING_length_set
BUF_memdup
BUF_strdup
BUF_strlcat
BUF_strlcpy
BUF_strndup
CRYPTO_num_locks
CRYPTO_set_dynlock_create_callback
CRYPTO_set_dynlock_destroy_callback
CRYPTO_set_dynlock_lock_callback
CRYPTO_set_locking_callback
CRYPTO_THREADID_cmp
CRYPTO_THREADID_cpy
CRYPTO_THREADID_current
CRYPTO_THREADID_get_callback
CRYPTO_THREADID_hash
CRYPTO_THREADID_set_callback
ERR_load_UI_strings
EVP_CIPHER_CTX_cleanup
EVP_CIPHER_CTX_init
EVP_MD_CTX_create
EVP_MD_CTX_destroy
EVP_MD_CTX_init
RSA_null_method
SSL_CTX_get_ex_new_index
SSL_CTX_set_default_read_ahead
SSL_CTX_set_ecdh_auto
SSL_CTX_set_tmp_rsa
SSL_CTX_set_tmp_rsa_callback
SSLeay_add_ssl_algorithms
SSL_get_ex_new_index
SSL_SESSION_get_ex_new_index
SSL_set_ecdh_auto
SSL_set_tmp_rsa
SSL_set_tmp_rsa_callback

Should all of those be re-added to the man pages? Any reasons any of them might have been intentionally skipped?

**Comment by kaduk** [comment]
Some of them are now no-op compatibility shims to avoid gratuitously breaking existing applications, like `CRYPTO_num_locks` and the `CRYPTO_THREADID_*` ones.  Others are functional compatibility shims like `EVP_MD_CTX_create()` that may or may not merit documentation as such.  There might be a few that should get real documentation, though -- `SSL_SESSION_get_ex_new_index()` looks like a candidate for such.
