### ISSUE TITLE
3.0.1 ETA

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#17105]
Is there an ETA on an official 3.0.1 release? I checked a few places on openssl.org and didn't see any commitments in terms of a regular cadence for patch releases, but it's certainly possible I overlooked something. I would anticipate that eventually the need for 3.0.x releases would be of irregular frequency and largely driven by CVEs, but thought perhaps initially there would be a desire to release bugfix patches regardless of the existence of any particular security vulnerabilities.

I think that some fixes in the 3.0 branch may help alleviate some seemingly concurrency-related issues we're seeing very infrequently in our environment. If a true release is coming relatively soon that would probably be preferable to us over attempting to identify and cherry-pick the specific commit(s) that help in our environment.

**Comment by paulidale** [comment]
Question for OTC: **is 3.0.1 now justified?**

Question for OTC/OMC: **what cadence would we like for patch releases?**

**Comment by kroeckx** [comment]
We're normally doing a release every 3 months. We've had this vote
related to it:
Release stable branch on the second last Tuesday of the last month
in each quarter as a regular cadence.

So 3.0.1 and 1.1.1m should get released on December 21, unless we
need to fix a CVE earlier.

**Comment by jwalch** [comment]
@kroeckx This was a mid-September 2020 vote recorded on openssl-project, correct?

I confess that I should have thought to search there, but I still think it may be helpful if the anticipated cadence is advertised a bit more prominently.

**Comment by mattcaswell** [comment]
OTC: We're currently planning to do a release on 14th December.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
