### ISSUE TITLE
[Migration] ENGINE_load_private_key for use in SSL_CTX equivalent in the provider world

### ISSUE THREAD

**Issue by space88man** [openssl/openssl#17107]
Existing ENGINE workflow:

- get reference to private key from ENGINE; `ENGINE_load_private_key` gives a `EVP_PKEY *`
- use this `EVP_PKEY *` in an `SSL_CTX *` with `SSL_CTX_usePrivateKey`

In the provider workflow: what is the equivalent of getting a `EVP_PKEY *` (by name/alias/label perhaps?) from a provider?

The docs mention:
* provider-keymgmt
* `EVP_PKEY`s have an associated `EVP_KEYMGMT `

More concretely: if you have a PKCS#11-provider, say, how do you fetch a reference to a `EVP_KEY` for use in TLS?

**Comment by t8m** [comment]
The PKCS11 provider would provide an OSSL_STORE implementation that you would use to load the key which would give you an EVP_PKEY * handle.
