### ISSUE TITLE
[v3.0.0] C++ v120 toolset support

### ISSUE THREAD

**Issue by biju2006** [openssl/openssl#17109]
Hi there,
I Couldn't find anywhere if the OpenSSL v3.0 supports compilation in v120 toolset on Windows platform.
I ask because I tried running the vcvarsall.bat from the VisualStudio v12.0 (2013).
The Configure part went smooth (perl Configure VC-WIN64A enable-fips)
The nmake part went smooth (nmake)
But the nmake test part fails on fips.dll problem.. 
Now before I provide more information maybe using v120 is not OK?

Thanks!

**Comment by mattcaswell** [comment]
Its almost certainly not been tested using that toolset and its not one of the explicitly supported toolchains listed here:
https://www.openssl.org/policies/platformpolicy.html

That said I might still expect it to just work - so I'd be interested to at least see what the failure is.

**Comment by biju2006** [comment]
Thanks for the fast response.
OK so first I tried several things so let me try to explain, maybe we'll focus just on 1 problem..

* On my own machine, I used VS 2013 and failed during the **nmake** (both with and without fips)
* On my own machine, I used VS 2019 and I succeed (both with and w\o fips)
* On my Build Machine, I used VS 2013 and failed on '**nmake test'** - OpenSSL crashes during some tests, AES_ENCRYPT test failed as well something with the fips.dll
* On my Build Machine, I downloaded the latest master version (instead of the official release), now the situation is better, my tests fail on 2 tests from 01-test_symbol_presence.t, which I saw [#16837](https://github.com/openssl/openssl/pull/16840/files) related.. but yet, it still fails: (and I checked that the fix exists in my code)

Test Summary Report
-------------------
01-test_symbol_presence.t        (Wstat: 512 Tests: 4 Failed: 2)
  Failed tests:  2, 4
  Non-zero exit status: 2

Now I think we can ignore the other scenarios and continue with my Build Machine with the latest master code using v120 toolset. I will try to get back on my own to the other scenarios to see what could be wrong.

Thanks.

**Comment by mattcaswell** [comment]
I have seen test_symbol_presence sometimes failing due to a dirty build environment, e.g. if the same environment has been used to build some other openssl version previously and there are left over files hanging around. One thing to try is to start from a completely clean checkout, rebuild and test.

If that doesn't fix it then getting more verbose output from the test might be helpful:

````
nmake TESTS=test_symbol_presence V=1 test
````

**Comment by biju2006** [comment]
Hi @mattcaswell !
I did it from a totally new cleaned master branch sources.
Added the verbosity, I remove A LOT of symbols that reported missing (~5000 symbols) so it will be easier to look.


01-test_symbol_presence.t ..
# The results of this test will end up in test-runs\test_symbol_presence
1..4
# NOTE: developer test!  It's possible that it won't run on your
# platform, and that's perfectly fine.  This is mainly for developers
# on Unix to check that our shared libraries are consistent with the
# ordinals (util/*.num in the source tree), something that should be
# good enough a check for the other platforms as well.
ok 1 - running 'cd ..\..; C:\Strawberry\perl\bin\perl.exe util\mkdef.pl --ordinals util\libcrypto.num --name crypto --OS linux' => 0
# Number of lines in @nm_lines before massaging: 0
# Number of lines in @def_lines before massaging: 5377
# Number of lines in @nm_lines after massaging: 0
# Number of lines in @def_lines after massaging: 5373
# The following symbols are missing in libcrypto-3-x64.dll:
#   ACCESS_DESCRIPTION_free
#   ACCESS_DESCRIPTION_it
#   ACCESS_DESCRIPTION_new
#   ADMISSIONS_free
......
#   X509v3_get_ext_count
#   ZINT32_it
#   ZINT64_it
#   ZLONG_it
#   ZUINT32_it
#   ZUINT64_it
#   a2d_ASN1_OBJECT
#   a2i_ASN1_ENUMERATED
.....
#   v2i_GENERAL_NAME_ex
not ok 2 - check that there are no missing symbols in libcrypto-3-x64.dll

#   Failed test 'check that there are no missing symbols in libcrypto-3-x64.dll'
#   at test\recipes\01-test_symbol_presence.t line 135.
ok 3 - running 'cd ..\..; C:\Strawberry\perl\bin\perl.exe util\mkdef.pl --ordinals util\libssl.num --name ssl --OS linux' => 0
# Number of lines in @nm_lines before massaging: 0
# Number of lines in @def_lines before massaging: 521
# Number of lines in @nm_lines after massaging: 0
# Number of lines in @def_lines after massaging: 517
# The following symbols are missing in libssl-3-x64.dll:
#   BIO_f_ssl
#   BIO_new_buffer_ssl_connect
.....
#   d2i_SSL_SESSION
#   i2d_SSL_SESSION
not ok 4 - check that there are no missing symbols in libssl-3-x64.dll

#   Failed test 'check that there are no missing symbols in libssl-3-x64.dll'
#   at test\recipes\01-test_symbol_presence.t line 135.
# Looks like you failed 2 tests of 4.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests

**Comment by mattcaswell** [comment]
> Number of lines in @nm_lines before massaging: 0

This line does not look correct. The output is showing lots of symbols missing because it hasn't found any symbols at all in the library. nm_lines is populated by this code:

https://github.com/openssl/openssl/blob/b33fb68a3230b8fc87f6663212ac3ffae0b361c5/test/recipes/01-test_symbol_presence.t#L45-L57

It runs the "nm" command to extract the symbols from the shared library. This all looks very "unixy" and my guess is that this was never supposed to run on Windows. The last "skip" line in the fragment above is supposed to detect that running the "nm" command failed and therefore skip the test. It looks like on your platform "nm" is appearing to *succeed* in that it is not returning an error code - and yet there is no output.

I wonder if you have some other implementation of "nm" on your build machine? What happens if you try and run "nm" from the command line. Does it try and run anything?

**Comment by biju2006** [comment]
I will try that, but in the meantime, I changed the 
unless $? == 0;
to 
unless 1 == 0;

and of course, it passed

**Comment by mattcaswell** [comment]
Thanks for the confirmation, and feedback on the patch. PR raised in #17119.

**Comment by levitte** [comment]
Hmmmmmmmm...  so this means that if the backquoted command can't be run for some reason, `$?` is set to zero on Windows?????  Or did you happen to have an `nm` command, but that gives surprising output?

> I will try that, but in the meantime, I changed the unless $? == 0; to unless 1 == 0;
> 
> and of course, it passed
> 
> Edit: Your fix is OK. just pay attention if you want the fixed string to be with **'** or **"** as the other lines are..
> 
> Thanks a lot! I will continue to the installation part.

**Comment by levitte** [comment]
> Nice direction, I do have the nm.exe, but, beside having it from cygwin64, it also installed with the Strawberry Perl that is needed for building OpenSSL.. I see it exists in C:\Strawberry\c\bin\nm.exe which its path added automatically to %PATH% during installation..
> 
> Edit: I just saw the note comment saying - "developer test! It's possible that it won't run on your platform, and that's perfectly fine. This is mainly for developers on Unix..."

Aha!  I glanced over this.

Strangely, though, I use StrawBerry perl as well, and I don't have `nm` on my path...

**Comment by levitte** [comment]
> Strangely, though, I use StrawBerry perl as well, and I don't have `nm` on my path...

Having looked further, it turns out I do...  and boy, that output is different
