### ISSUE TITLE
[ossl_store doc] OSSL_STORE_INFO_CERT instead of OSSL_STORE_INFO_X509 ?

### ISSUE THREAD

**Issue by space88man** [openssl/openssl#17121]
Version: 1.1.1., 3.0.0
The docs here: https://www.openssl.org/docs/man3.0/man7/ossl_store.html use `OSSL_STORE_INFO_X509` in the example.

Should that be `OSSL_STORE_INFO_CERT`?

**Comment by levitte** [comment]
Yes it should.  @paulidale made a fix, see #17125
