### ISSUE TITLE
Missing OSSL_FUNC_CRYPTO_*DUP definitions for provider core functions

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#17138]
Per [https://www.openssl.org/docs/manmaster/man7/provider-base.html](https://www.openssl.org/docs/manmaster/man7/provider-base.html), function `OSSL_provider_init()` gets passed a set of core functions through the `in` parameter. Per doc this includes the following *dup functions:

```
 CRYPTO_memdup                  OSSL_FUNC_CRYPTO_MEMDUP
 CRYPTO_strdup                  OSSL_FUNC_CRYPTO_STRDUP
 CRYPTO_strndup                 OSSL_FUNC_CRYPTO_STRNDUP
```
But `core_dispatch.h` does not define these functions. 

So either the doc is wrong, or the code misses these definitions.

**Comment by mattcaswell** [comment]
The documentation is wrong. They once existed in a pre-release version but they were removed by 037439c46. That removal missed the removal of the documentation.
