### ISSUE TITLE
When using the BN_kronecker, if both a and p are negative, the results may be incorrect.

### ISSUE THREAD

**Issue by Meichen1997** [openssl/openssl#17137]
```
int main() {
    BIGNUM *r = BN_new();
    BIGNUM *a = BN_new();
    BIGNUM *p = BN_new();
    BN_CTX *ctx = BN_CTX_new();
    char adata[] = "-6";
    char pdata[] = "-B";
    BN_hex2bn(&a, adata);
    BN_hex2bn(&p, pdata);
    int ret = BN_kronecker(a, p, ctx);
    printf("ret: %d\n", ret);
    BN_free(r);
    BN_free(a);
    BN_free(p);
    BN_CTX_free(ctx);
}
```
expect result : ret is 1
now result : ret is -1

**Comment by paulidale** [comment]
Wolfram Alpha gives -1 for [this](https://www.wolframalpha.com/input/?i=kronecker+symbol+%28-6%2C+-11%29).

**Comment by Meichen1997** [comment]
> Wolfram Alpha gives -1 for [this](https://www.wolframalpha.com/input/?i=kronecker+symbol+%28-6%2C+-11%29).
> 
> Where are you getting your expected result?

I think the Kronecker symbol is used to determine whether the square root can be computed, and if a=-6, p=-11, the square root can be computed.
Maybe there's a mistake in my thought.
Sorry to interrupt.
Thank you!
