### ISSUE TITLE
Memory leak due to include in afxwin.h (OpenSSL Ver1.1.1l)

### ISSUE THREAD

**Issue by YuSugie** [openssl/openssl#17143]
I am developing a Windows C ++ MFC application.
However, using openssl v1.1.1l in an MFC application causes a memory leak.
(Currently, 1.0.2p is used, and no memory leak occurs in this version.)
A memory leak occurs by including afxwin.h for MFC components and executing OPENSSL_init_crypto as shown in the following source code.

    ```
    #include <openssl/evp.h>
    #include <afxwin.h>                // MFC Component      // Cause!!!!!!!!!
    int main(int, char*[])
    {
        // Memory Leak Detection
   	    _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
 
  	   // ↓Memory Leak!↓
  	   OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_CIPHERS | OPENSSL_INIT_ADD_ALL_DIGESTS, NULL);
  	   return 0;
    }
    ```

If I don't include afxwin.h as below, no memory leak will occur.

      ```
     #include <openssl/evp.h>
     //#include <afxwin.h>                // MFC Component      // Cause!!!!!!!!!
     #include <crtdbg.h>                  // Memory Leak Detection
     int main(int, char*[])
     {
           // Memory Leak Detection
   	    _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
 
  	   // ↓Memory Leak!↓
  	   OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_CIPHERS | OPENSSL_INIT_ADD_ALL_DIGESTS, NULL);
  	   return 0;
    }
    ```
In addition to OPENSSL_init_crypto, the functions that have a memory leak by including afxwin.h are as follows.
- OpenSSL_add_all_algorithms ()

I would like to replace it with 1.1.1l due to a vulnerability issue, so please improve it.
Thank you.

**Comment by paulidale** [comment]
Do you know what memory is being leaked?

**Comment by YuSugie** [comment]
I don't know because there is a memory release omission in the OpenSSL function.

**Comment by paulidale** [comment]
I have to admit that I'm somewhat sceptical that OpenSSL is leaking memory here.  Including an unrelated header file causing a memory leak is very weird.  Moreover, others are not reporting similar problems in what is an old release.

This is not a lot to go on.  You are going to have to provide more information if we've any chance of figuring this out.  Where the leaked memory is allocated is the first thing we need.  You should be able to get this output.  I suggest [reading the documentation](https://docs.microsoft.com/en-au/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2022).

**Comment by mspncp** [comment]
If I recall correctly (it's been a long time), the debug crt check occurs immediately after exiting the `main` function and *before the `atexit` handlers are called*, which is where the OpenSSL library cleanup should occur. (I'm not 100% sure, but you could verify this in the debugger.) 

I'm not sure why you don't observe the leaks with 1.0.2. It could be caused by the fact that the openssl library is using its own (release) version of the crt? Did you set memory callbacks in 1.0.2 (`CRYPTO_set_mem_functions()`)?

**Comment by mspncp** [comment]
> If I don't include afxwin.h as below, no memory leak will occur.

What happens if you includ afxwin.h *before* openssl/evp.h?

**Comment by mattcaswell** [comment]
> I'm not sure why you don't observe the leaks with 1.0.2. It could be caused by the fact that the openssl library is using its own (release) version of the crt?

1.0.2 does not have the auto-deinit functionality that 1.1.0 and above have (i.e. there are no atexit handlers in 1.0.2).

> If I recall correctly (it's been a long time), the debug crt check occurs immediately after exiting the main function and before the atexit handlers are called, which is where the OpenSSL library cleanup should occur. (I'm not 100% sure, but you could verify this in the debugger.)

If that is true then this is not a real leak at all. In this case you could avoid the false positive by disabliing the atexit handlers and cleaning up explicitly, i.e.

Before any call to any other OpenSSL function call:

````
OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL);
````

You will then need to explicitly cleanup OpenSSL before "main" exits by calling:
````
OPENSSL_cleanup();
````

**Comment by mspncp** [comment]
Just calling `OPENSSL_cleanup()` before exiting main should be enough. No need to disable the atexit handlers, right @mattcaswell?

**Comment by mspncp** [comment]
OTOH, if they are not used anyway, it makes sense to disable them.

**Comment by mattcaswell** [comment]
> Just calling OPENSSL_cleanup() before exiting main should be enough. No need to disable the atexit handlers, right @mattcaswell?

Actually, yes that's probably true - although that means `OPENSSL_cleanup` will end up being called twice. Once explicitly by the application, and once automatically by the atexit handler. The second call would be a no-op.

**Comment by mspncp** [comment]
> 1.0.2 does not have the auto-deinit functionality that 1.1.0 and above have (i.e. there are no atexit handlers in 1.0.2).

Yeah, that’s exactly why I would expect leaks in 1.0.2 if the cleanup functions are not called explicitly.

**Comment by YuSugie** [comment]
Thank you for answering.
Calling OPENSSL_cleanup at the end of main () no longer detects memory leaks.
The atexit handlers have not changed. Please tell me how to disable them.

**Comment by mspncp** [comment]
See https://github.com/openssl/openssl/issues/17143#issuecomment-979872790.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
