### ISSUE TITLE
Deployment of openssl lib folder inconsistent between linux and windows x64

### ISSUE THREAD

**Issue by wbeck10** [openssl/openssl#17142]
If you configure openssl on linux x64 with prefix folder the prefix folder structure will contains:
|-bin
|-include
|-lib64
|-share
|-ssl

However if you config a windows x64 the prefix folder structure will be:
|-bin
|-html
|-include
|-lib
|-share
|-ssl

My configuration for winkdows was:
    "perlargv" => [
        "--prefix=C:\\Users\\beckw\\trunk\\openssl3\\openssl-3.0.0-windows_x64_msvc_install",
        "enable-trace",
        "enable-fips",
        "enable-md2",
        "enable-md4",
        "enable-rc5",
        "enable-rc2",
        "enable-weak-ssl-ciphers",
        "enable-ssl3",
        "enable-ssl3-method",
        "enable-ssl-trace",
        "no-shared",
        "no-asm",
        "--openssldir=ssl",
        "VC-WIN64A"
    ],

As you can see in linux the lib folder name is lib64 but in windows it is lib.

**Comment by levitte** [comment]
It's consistent with how things are usually organized on the different platforms.  Windows and Linux have very different installation philosophies.

Linux (like every Unix family platform on the planet) has programs and libraries explicitly separated, and (again, like most other Unix family platforms) libraries for different flavors (such as 32-bit and 64-bit) explicitly separated as well.

Windows doesn't come with the same philosophy.  There is no separation between programs and libraries.  However, there is a flavor separation on a package level; the `Program Files` folder serves as the default installation target for 64-bit programs and everything that belongs with it, while the `Program Files (x86)` folder serves as the default installation target for 32-bit programs and everything that belongs with it.

However, it's perfectly possible for you to force the library directory name of your choice.  Simply add this to your configuration command: `--libdir=lib64`
