### ISSUE TITLE
'openssl rsa -in rsapss.key -check' not working for RSA-PSS keys with OpenSSL 3.0

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#17167]
The OpenSSL `rsa` command line tool does not work anymore with RSA-PSS type keys in OpenSSL 3.0:

```
# openssl genpkey -algorithm RSA-PSS -pkeyopt rsa_keygen_bits:1024 --out rsapss.key
# openssl rsa -in rsapss.key -check
shows 'Not an RSA key'
```

This is caused by the following code in `apps/rsa.c`:
```
    if (!EVP_PKEY_is_a(pkey, "RSA")) {
        BIO_printf(bio_err, "Not an RSA key\n");
        goto end;
    }
```
This came in with commit https://github.com/openssl/openssl/commit/d7e498ac55f12bc2f4e7f948cbb8de2e3eeafc74
I guess it should check if the key is either "RSA" or "RSA-PSS" and accept both.

**Comment by t8m** [comment]
> grepping the codebase reveals a few other locations which at least look suspicious:

I am going to review these places in next sprint.
