### ISSUE TITLE
PKCS12_parse returns 'cert' as null with pkcs12 file created without a private key

### ISSUE THREAD

**Issue by viralmutant** [openssl/openssl#17173]
Hi

I am using `OpenSSL 1.0.2x-fips` in our product.

I was testing a `pkcs12` file that was created without the private key

My code snippet:

```
12117     if (!PKCS12_parse(pkcs12, passwd, &pkey, &cert, NULL)) {
12118        // return if error
12127     }
12128
12129     is_CA_cert = (X509_check_ca(cert) == 0) ? FALSE : TRUE;
```

The code crashed at line 12129 as the `cert` was `NULL`

Is this expected ? `PKCS12_parse` didn't return 0 but `cert` was `NULL`

**Comment by t8m** [comment]
Please note that 1.0.2 version is out of support for a long time (except for premium support customers).

**Comment by bernd-edlinger** [comment]
maybe your pkcs12 file does not contain private key, or it does not contain a cert that matches the private key?
PKCS12_parse will only return 0, when the pkcs12 file cannot be parsed at all.

**Comment by FdaSilvaYY** [comment]
One of the possible reason/issue with pkcs12 and Fips is `pbeWithSHA1And40BitRC2` algorithm.
This PBE algorithm is not supported when you enable fips mode.
I had to re-encrypt my p12 file with the other algorithm based on DES.

**Comment by FdaSilvaYY** [comment]
You can try to dump the error stack, or you can try to replicate the issue using the command-line tool.

**Comment by viralmutant** [comment]
> One of the possible reason/issue with pkcs12 and Fips is `pbeWithSHA1And40BitRC2` algorithm. This PBE algorithm is not supported when you enable fips mode. I had to re-encrypt my p12 file with the other algorithm based on DES.

FIPS was not enabled on my machine

**Comment by viralmutant** [comment]
> maybe your pkcs12 file does not contain private key, or it does not contain a cert that matches the private key? PKCS12_parse will only return 0, when the pkcs12 file cannot be parsed at all.

Yes, as I mentioned, I purposely created pkcs12 file without private key.
So, that would mean relying just on non-zero return code is not enough. We should check for `pkey` and `cert` being `!NULL` too.

Maybe we should add that in documentation ?

**Comment by vm2mv** [comment]
I have the same problem with OpenSSL 1.1.1l.
Are there any workarounds?

**Comment by Cogitri** [comment]
It seems like extracting the certificate with `openssl pkcs12 -in cert.pfx -clcerts -nokeys -out publicCert.pem` works though.

**Comment by FelixSchladt** [comment]
Hi,
I think I am encountering the same issue:
If I create the PKCS #12 file with a private key:
`openssl pkcs12 -export -inkey clientkey.pem -in clientcert.pem -certfile ../ca_folder/cacert.pem -out clientcertchain.pfx`
I can extract the client certificate with:
`openssl pkcs12 -in clientcertchain.pfx -clcerts`

If I do not include a key with:
`openssl pkcs12 -export -in clientcert.pem -certfile ../ca_folder/cacert.pem -out clientcertchain.pfx -nokeys`
I cannot extract the client certificate with
`openssl pkcs12 -in clientcertchain.pfx -clcerts`
the output is just empty.

The certificate seems to be instead placed together with cacertificate in the additional certificate section. 

I am currently using OpenSSL version OpenSSL 1.1.1l

**Comment by davidben** [comment]
PKCS#12 files do not store their certificates in any particular order. OpenSSL uses the private key to match find which one is "the" certificate vs. additional CA certs. Without a private key, there isn't any way to tell which one is it, so it needs to put them all in the generic list.

**Comment by FelixSchladt** [comment]
Thank you for your reply, that makes sense.

though I think it would be a bit more intuitive if it would default to the certificate supplied with the `-in` parameter

**Comment by davidben** [comment]
That's not in the format you've exported to here. The PKCS#12 format does not know what an `-in` parameter is, nor does it otherwise distinguish a certificate. It just contains a bundle of certificates without prescribing any relation between them. (Actually it prescribes even less... it's an extensible container of blobs with some encryption.)

You might ask why we're using such a ridiculous, unstructured format to store what is usually much more structured input (a key and a corresponding single, ordered certificate chain), and I would agree! But alas that's the format that people seem to like to use.
