### ISSUE TITLE
NULL v/s "" as third parameter to EVP_MD_fetch()

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#17170]
I wasn't able to find a clear explanation for using one over the other. I noticed that within evp/digest.c there's an instance where we use the empty string in evp_md_init_internal(). It seems like in most other instances we just pass NULL, for example the sample code in man7/crypto. It doesn't look like man7/property speaks to it.

I'm guessing that either is expected to work, I'm just trying to understand if there would be any particular benefit to one or the other.

**Comment by mattcaswell** [comment]
Functionally there is no difference between the two. They are entirely equivalent. Internally there is a shortcut taken when attempting to parse a property query if the input is NULL. If its NULL we don't even try to parse it. It its non-NULL we do, and some stuff gets allocated temporarily. So, probably, a NULL property query is slightly more efficient. Whether that difference is actually measurable though is another question. I'd generally prefer NULL over "".

**Comment by slontis** [comment]
@mattcaswell I am not sure if it make much of a difference to the caching.... but ossl_method_store_cache_set() returns early when prop_query is NULL. See inside inner_evp_generic_fetch().
