### ISSUE TITLE
How to pass the .cer/.der format certificate with openssl s_client while verifying the connectivity a server?

### ISSUE THREAD

**Issue by ravinjhajharia** [openssl/openssl#17174]
I see there is an option to pass as a trusted directory. I tried to give a local directory and also with hashed one but none of them worked

![image](https://user-images.githubusercontent.com/6805694/144175995-d96daac6-223e-4a9e-abdd-b6b9cb49f374.png)

Could someone provide what exactly has to be configured and how it can be achieved?

**Comment by t8m** [comment]
As documented the directory must contain trusted CA certificates in individual files that have the hash symlinks to work. You can create the symlinks with `openssl rehash` command.
