### ISSUE TITLE
EVP_DecodeBlock return value is incorrect for standard Base64

### ISSUE THREAD

**Issue by tsengjun** [openssl/openssl#17197]
Hello Maintainers,
Thanks for providing such a great library to the world!

Problem here is about base64 decoding:
    #include <openssl/evp.h>

    int main() {
                unsigned char *str=(unsigned char *)"YQ=="; /* "a" => "YQ==" */
                unsigned char dst[4] = {'\0', '\0', '\0', '\0'};
                int ret = EVP_DecodeBlock(dst, str, (int)strlen((const char *)str));

                printf("dst=%s, ret=%d\n", dst, ret);
    }

In this example, the return value of EVP_DecodeBlock is **3**. I'm expecting **1**.  As you can see, there are two padding equal signs there, according to https://datatracker.ietf.org/doc/html/rfc4648#section-4

Could you do me a favor and give me some guidance? I want to know the decoded data's actual length.

**Comment by tsengjun** [comment]
The original string is "a," with length 1, and its base64 encodes "YQ==.," so I'm expecting the same decoding result as its actual length 1.

**Comment by slontis** [comment]
See doc/man3/EVP_EncodeInit.pod

Basically the data is padded.

i.e.
````
EVP_DecodeBlock() will decode the block of B<n> characters of base 64 data
contained in B<f> and store the result in B<t>. Any leading whitespace will be
trimmed as will any trailing whitespace, newlines, carriage returns or EOF
characters. After such trimming the length of the data in B<f> must be divisible
by 4. For every 4 input bytes exactly 3 output bytes will be produced. The
output will be padded with 0 bits if necessary to ensure that the output is
always 3 bytes for every 4 input bytes. This function will return the length of
the data decoded or -1 on error.
````


There is some internal code from another function that does the following:
````
    outlen = EVP_DecodeBlock(outbuf, (unsigned char *)in, inlen);
    if (outlen < 0) {
        ERR_raise(ERR_LIB_CT, CT_R_BASE64_DECODE_ERROR);
        goto err;
    }

    /* Subtract padding bytes from |outlen|.  Any more than 2 is malformed. */
    i = 0;
    while (in[--inlen] == '=') {
        --outlen;
        if (++i > 2)
            goto err;
    }
````

**Comment by tsengjun** [comment]
@slontis Hello Shane,
Thank you so much for pointing out the correct code snippet!

I have to bring the function **ct_base64_decode** up; it returns the accurate number of bytes encoded. Clear and straightforward.

Is it possible to expose this function to the public?

Thanks!

**Comment by mattcaswell** [comment]
Most applications are expected to use `EVP_DecodeInit`/`EVP_DecodeUpdate`/`EVP_DecodeFinal` to process base 64 data. These functions properly handle variable length data and associated trailing "=" signs. It sounds like you should be using those functions instead.

**Comment by tsengjun** [comment]
@mattcaswell Hi Matt,
I've tried to draft the test code as below:
```
void base64decode()
{
    unsigned char *src = (unsigned char *)"YQ==";
    unsigned char dst[8];
    int dlen;
    EVP_ENCODE_CTX ctx;
    EVP_DecodeInit(&ctx);
    EVP_DecodeUpdate(&ctx, dst, &dlen, src, (int)strlen((const char *)src));
    _OPENSSL_assert(dlen == 1); /* ASSERT here, as dlen = 0 */
    EVP_DecodeFinal(&ctx, dst, &dlen);
    OPENSSL_assert(*dst == 'a');
    _OPENSSL_assert(dlen == 1); /* Or, ASSERT here, as dlen = 0 */
}
```
Some unexpected results are:

a. the decoded length dlen=0, not as expected 1.
b. struct EVP_ENCODE_CTX is a typedef of evp_Encode_Ctx_st. Unfortunately, defined in an internal header file: crypto\evp\evp_local.h
c. evp_local.h redefined "new" which is not compatible with C++.

Would you mind having a look at this test code? And thank you so much for your attention and participation.

**Comment by t8m** [comment]
> I noticed that EVP_DecodeUpdate only could handle 80 bytes per call. Because of this, my happy smile downgraded to facepalm.

Maybe it could be changed to allow more than that?

**Comment by tsengjun** [comment]
@t8m Hi Tomáš,
About 80 bytes, this is my fault, my misunderstanding. There is no 80 bytes limitation. General API works perfectly!

I'll edit the old post. Only leaves the example code there to give some light to the followers, who are curious about EVP_DecodeBlock return value.

**Comment by tsengjun** [comment]
Close as a problem solved perfectly. Thumbs up and applaud to all you guys for the great help!
