### ISSUE TITLE
External provider does not load on Windows, because OSSL_provider_init is not dllexport'ed

### ISSUE THREAD

**Issue by vt-alt** [openssl/openssl#17203]
I try to CI [gost-engine](https://github.com/gost-engine/engine) on Windows (on GA). It have provider implementation by @levitte. I [found](https://github.com/gost-engine/engine/pull/374#issuecomment-986504119) that openssl is unable to load gostprov provider:
```powershell
> & '.\_dest\Program Files\OpenSSL\bin\openssl.exe' list -provider gostprov
list: unable to load provider gostprov
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
E0150000:error:1280006A:DSO support routines:win32_bind_func:could not bind to the requested symbol name:crypto\dso\dso_win32.c:184:symname(OSSL_provider_init)
E0150000:error:1280006A:DSO support routines:DSO_bind_func:could not bind to the requested symbol name:crypto\dso\dso_lib.c:176:
E0150000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:906:name=gostprov
```
It seems that `OSSL_provider_init` symbol is absent. `dumpbin /export gostprov.dll` confirms that.
In compare to the definition of `bind_engine` it's missing `OPENSSL_EXPORT` which contains `__declspec(dllexport)` which is required  (AFAIK) for a symbol to be exported in DLL.

**Comment by mattcaswell** [comment]
This seems like a bug that should be reported to the gost-engine project and not here.

**Comment by vt-alt** [comment]
@mattcaswell gost-engine cannot solve this since `OSSL_provider_init` is declared in `core.h`. And adding dllexport to your `OSSL_provider_init` instance will cause redefinition error, such as `error C2375: 'OSSL_provider_init': redefinition; different linkage`.

We only can do tricks like `#define OSSL_provider_init OSSL_provider_init_disable` just before include `openssl/core_dispatch.h`, then `#undef OSSL_provider_init`, and then add `OPENSSL_EXPORT` to our `OSSL_provider_init` instance. If you think this is correct solution then OK.

**Comment by mattcaswell** [comment]
> I  found that openssl is unable to load gostprov provider:

Do you see the same problem with the legacy provider on Windows? The legacy provider also uses `OSSL_provider_init` as its entry point.

**Comment by levitte** [comment]
> @mattcaswell gost-engine cannot solve this since `OSSL_provider_init` is declared in `core.h`. And adding dllexport to your `OSSL_provider_init` instance will cause redefinition error, such as `error C2375: 'OSSL_provider_init': redefinition; different linkage`.

This is incorrect, the dllexport doesn't have to be specified in the header, it could as well be done with this patch in gost-engine:

``` diff
 diff --git a/gost_prov.c b/gost_prov.c
index e7fdd96..d1d2cdb 100644
--- a/gost_prov.c
+++ b/gost_prov.c
@@ -143,6 +143,7 @@ struct prov_ctx_st {
 # define OSSL_provider_init GOST_provider_init
 #endif
 
+__declspec(dllexport)
 int OSSL_provider_init(const OSSL_CORE_HANDLE *core,
                        const OSSL_DISPATCH *in,
                        const OSSL_DISPATCH **out,
```

(that's a quick hack, though...  it would be better to do this in a way that conforms with gost-engine's build system)

> We only can do tricks like `#define OSSL_provider_init OSSL_provider_init_disable` just before include `openssl/core_dispatch.h`, then `#undef OSSL_provider_init`, and then add `OPENSSL_EXPORT` to our `OSSL_provider_init` instance. If you think this is correct solution then OK.

I don't think that's the correct solution

**Comment by vt-alt** [comment]
> ```diff
> +__declspec(dllexport)
I just tried this method:
```
D:\a\gost-engine\gost-engine\gost_prov.c(147,5): error C2375: 'OSSL_provider_init': redefinition; different linkage [D:\a\gost-engine\gost-engine\gost_prov.vcxproj]
D:\a\gost-engine\gost-engine\_dest\Program Files\OpenSSL\include\openssl/core.h(198): message : see declaration of 'OSSL_provider_init' [D:\a\gost-engine\gost-engine\gost_prov.vcxproj]
```
@mattcaswell No, I did not try legacy provider and started to try to CI-build engine on Windows 4 days ago.

**Comment by levitte** [comment]
> > ```diff
> > +__declspec(dllexport)
> > ```
> 
> I just tried this method:
> 
> ```
> D:\a\gost-engine\gost-engine\gost_prov.c(147,5): error C2375: 'OSSL_provider_init': redefinition; different linkage [D:\a\gost-engine\gost-engine\gost_prov.vcxproj]
> D:\a\gost-engine\gost-engine\_dest\Program Files\OpenSSL\include\openssl/core.h(198): message : see declaration of 'OSSL_provider_init' [D:\a\gost-engine\gost-engine\gost_prov.vcxproj]
> ```

??? Oh!
Er, I stand corrected then...

**Comment by levitte** [comment]
So it turns out that this may indeed be a bug on our end.  The only reason we get away with it for our own providers is that we do the older dance with separate export definitions on Windows.

**Comment by levitte** [comment]
Something to be noted is that this affects 3.0 as well, i.e. our core.h ends up being hard to use there as well.  In all cases, only on Windows.

**Comment by beldmit** [comment]
As usual, GOST engine in its provider's incarnation come to serve :)

Thanks @vt-alt for digging this out!

**Comment by vt-alt** [comment]
Thanks much for the fix!
