### ISSUE TITLE
Should security levels of DH keys be (re)checked at time of use?

### ISSUE THREAD

**Issue by vdukhovni** [openssl/openssl#17216]
As noted in https://github.com/openssl/openssl/pull/17209#issuecomment-987094453 we're presently enforcing the DH key security level at time of configuration.  Are similar checks present and/or necessary at time of use?  The security level can change between the time the key is set and when it is actually time to negotiate a handshake.

**Comment by mattcaswell** [comment]
> Are similar checks present and/or necessary at time of use? 

We additionally check this at time of use. See:

https://github.com/openssl/openssl/blob/119f8145c3bde29aae5d5b18c44d1663df975ef5/ssl/statem/statem_srvr.c#L2458-L2486

**Comment by vdukhovni** [comment]
Thanks.  Closing the issue.

**Comment by paulidale** [comment]
It doesn't require it anymore.  I flagged this as something the OTC would have to make a call on but seeing as we already do the safest thing, I don't think any action is required.
