### ISSUE TITLE
[docs] What is a "legacy object/key" (c.f. Legacy Algorithms)?

### ISSUE THREAD

**Issue by space88man** [openssl/openssl#17229]
What is a "legacy' `EVP_PKEY` object vs provider-based-`EVP_PKEY`? Does the difference lie in the (opaque) implementation struct members?

Commit https://github.com/openssl/openssl/commit/0c9afd6918dfe5e818b3545ede88011adeb6e76b mentions
(typo in "concidered"?):

```
Engine-backed keys can be loaded via custom B<OSSL_STORE> implementation.
In this case the B<EVP_PKEY> objects created via L<ENGINE_load_private_key(3)>
will be concidered legacy and will continue to work.
```

I could only find a reference to "Legacy Algorithms" here: https://wiki.openssl.org/index.php/OpenSSL_3.0#Legacy_Algorithms
but no explanation of a "legacy" `EVP_PKEY` vs provider-based-`EVP_PKEY`.

**Comment by slontis** [comment]
doc/internal/man7/EVP_PKEY probably has the best explanation of this (see 'legacy origin')
Engines use the old format that points directly to a low level key (e.g RSA) which bypasses using the provider implementations.
Provider based ones use another pointer inside the EVP_PKEY object that contains an object that is created inside a provider implementation. This object is then passed to the provider implementation methods to do operations such as update and final. The legacy pkeys go thru the old method tables.
i.e. We have a whole lot of code that currently does
if (legacy) {
  ...
   call old legacy method
}  else {
   ...
  call provider method
}
