### ISSUE TITLE
OPENSSL_VERSION month in OpenSSL 3.0.0 and future releases

### ISSUE THREAD

**Issue by h-vn** [openssl/openssl#17228]
OpenSSL release 3.0.0 has the month in the release string spelled with lowercase first letter: 
```
% git describe
openssl-3.0.0

% cat VERSION.dat
MAJOR=3
MINOR=0
PATCH=0
PRE_RELEASE_TAG=
BUILD_METADATA=
RELEASE_DATE="7 sep 2021"
SHLIB_VERSION=3

% openssl version
OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)
```

The documentation https://www.openssl.org/docs/manmaster/man3/OPENSSL_VERSION_TEXT.html does not mandate uppercase first letter, but based on the previous releases I would have expected the above to be `Sep`. This is a minor nit, but now that when 3.0.1 will be released soon, maybe this could be addressed for consistency.

**Comment by faramir-dev** [comment]
I will take a look at this, it is interesting to do a little debugging of the openssl binary.

**Comment by levitte** [comment]
Hint: VERSION.dat is created/modified by the release script.

**Comment by mattcaswell** [comment]
Specifically here:
https://github.com/openssl/openssl/blob/eafd3e9d07e99583a1439bb027e4d6af43e2df27/dev/release-aux/release-version-fn.sh#L93-L114

**Comment by h-vn** [comment]
It might be related to locale environment variables that affect the date format when the release build scripts are run?

I noticed this when I was updating Perl `Net::SSLeay` tests to see that `OpenSSL_version(OPENSSL_VERSION)` returns a string in expected format. A regexp that checks for upper case month would have worked with all other versions except of 3.0.0.

**Comment by levitte** [comment]
> It might be related to locale environment variables that affect the date format when the release build scripts are run?

Yup. `export LANG=C` in the right spot should suffice to clear this
