### ISSUE TITLE
How to modify OPENSSL_API_COMPAT Macro？

### ISSUE THREAD

**Issue by trymine** [openssl/openssl#17233]
Hi，
I am using openssl v1.1.1j，but I need to use some old interfaces in my system.
Such as SSL_library_init()，it defined like this:
```
# if OPENSSL_API_COMPAT < 0x10100000L
#  define SSL_library_init() OPENSSL_init_ssl(0, NULL)
# endif 
```
However，In the openssl.conf file, it can not be edit.
And I only find define like #define OPENSSL_MIN_API 0x10100000L now.

I try to fit it，and add -DOPENSSL_API_COMPAT=0x10000000L while compile openssl.
like this:
```
./Configure --prefix=$PWD/output --cross-compile-prefix=${CROSS_COMPILE} \
-DOPENSSL_API_COMPAT=0x10000000L  ...etc
make 
```
But it still doesn't work.
Do any experts know how to change this macro to the required value during openssl compilation?
Thanks.

**Comment by paulidale** [comment]
Configure with the `--api=` option.  For 1.0.2: `--api=1.0.2`

**Comment by paulidale** [comment]
This is in the `INSTALL.md` instructions.

**Comment by trymine** [comment]
Yes, we can Configure (or config)with the --api= option. 
In addition， no-deprecated is the same as using "--api" and supplying the latest version number. 
Thanks.
