### ISSUE TITLE
Error S/MIME decrypt (Image) in the windows

### ISSUE THREAD

**Issue by raminfp** [openssl/openssl#17242]
Hi,

We use command `openssl smime -decrypt -in test.png.encrypt -inform DER -inkey key.private -out test.png` in the linux and it's working, but isn't work decrypt a image file but it's working decrypt other file like `.txt, .json` in the windows 

When we open png file in the windows i get error : `The image “test.png” cannot be displayed because it contains errors.`

Linux openssl version : 
```bash
openssl version                                                                                                                        130 ⨯
OpenSSL 1.1.1k  25 Mar 2021 (Library: OpenSSL 1.1.1l  24 Aug 2021)
```
Windows openssl version : 
```bash
openssl version
OpenSSL 1.1.1k  25 Mar 2021
```

With analysis with 010editor we see a byte was added to the photo file in the windows decryption,

<img width="703" alt="1" src="https://user-images.githubusercontent.com/10054759/145342597-c89b02ec-b452-46a2-9e77-737c7d842aa8.PNG">
<img width="704" alt="2" src="https://user-images.githubusercontent.com/10054759/145342599-2974e242-1606-42dc-99e5-48be47bc29c0.PNG">

Thanks,
Ramin

**Comment by t8m** [comment]
Could you try `-binary` option if it helps?

**Comment by beldmit** [comment]
Try to use -binary key

**Comment by raminfp** [comment]
Thanks @t8m , It working
