### ISSUE TITLE
1.1.1f: ENGINE_init fail without any helpful info

### ISSUE THREAD

**Issue by daixiang0** [openssl/openssl#17244]
I want to load `dynamic` engine but fail without any helpful info:
```
$ ./test
ENGINE_init error: error:00000000:lib(0):func(0):reason(0)
```
test.c:
```
#include <stdlib.h>
#include <openssl/err.h>
#include <openssl/engine.h>

void main() {
  const char *engine_id = "dynamic";
  ENGINE_load_dynamic();


  ENGINE* engine = ENGINE_by_id(engine_id);
  if (engine == NULL) {
      int err_num = ERR_get_error();
      char buf[128] = {0};
      printf("ENGINE_init error: %s\n", ERR_error_string(err_num, buf));
  }

  if (ENGINE_init(engine) == 0)  {
      int err_num = ERR_get_error();
      char buf[128] = {0};
      printf("ENGINE_init error: %s\n", ERR_error_string(err_num, buf));
  }

}

```

build:
```
$ gcc test.c -o test -lcrypto
```

My env:
```
$ strings /usr/lib/x86_64-linux-gnu/libcrypto.so | grep "^OpenSSL"
OpenSSL_version_num
OpenSSL_version
OpenSSL default
OpenSSL 1.1.1f  31 Mar 2020
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```

While `openssl` call as expect:
```
$ openssl speed -engine dynamic ecdsap256
engine "dynamic" set.
...
```
I do not know how to fix it.

**Comment by daixiang0** [comment]
Kind like https://www.mail-archive.com/openssl-users@openssl.org/msg87045.html, but do not find a way to fix it.

**Comment by beldmit** [comment]
You could try to check whether your engine is loaded at all (via strace)
and what happens in the bind function (via gdb)

**Comment by daixiang0** [comment]
@beldmit I am very new here, could you please share more details about it? Also, this error info should be improved in the case.

**Comment by paulidale** [comment]
strace and gdb are basic debugging tools that should be in the toolkit of every programmer.  They have nothing specifically to do with OpenSSL.

**Comment by daixiang0** [comment]
@beldmit I cannot jump into ENGINE_init function:
```
(gdb) break 16
Breakpoint 1 at 0x131d: file test.c, line 16.
(gdb) run
Starting program: /root/github/grpc/examples/cpp/helloworld/test
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at test.c:16
16        if (ENGINE_init(engine) == 0)  {
(gdb) s               <== 
17            int err_num = ERR_get_error();
(gdb)
```

**Comment by paulidale** [comment]
`br ENGINE_init` should work.  It might ask you if you want to set the break point based on a future shared library load.

**Comment by daixiang0** [comment]
@paulidale seems not work, even without any ask:
```
(gdb) br ENGINE_init
Breakpoint 1 at 0x1100
(gdb) run
Starting program: /root/github/grpc/examples/cpp/helloworld/test
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, 0x00007ffff7e3c730 in ENGINE_init () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) s
Single stepping until exit from function ENGINE_init,
which has no line number information.
main () at test.c:16
16        if (ENGINE_init(engine) == 0)  {
```

**Comment by t8m** [comment]
You need to build the openssl with the --debug option.

**Comment by daixiang0** [comment]
After debugging, I find that `dynamic` engine always return 0 when `ENGINE_init`, it is better to log this :)

**Comment by daixiang0** [comment]
Is anyone working on this?

**Comment by petrovr** [comment]
Hi Loong Dai,

Loong Dai wrote:
> Is anyone working on this?

To work on what?

Engine in test case above is for internal use. Goal is to load "real" engine. In this process it uses some commands like path to shared library.
You could read OpenSSL code if you needed to know how "real" engines are loaded with help of dynamic engine.

Another point is "real" engine.
During load, as expected, real engine cannot use OpenSSL error reporting. In the same time openssl raises a lot of errors if load fail. Errors in "init" could be reported by "real" engine.


Regards,
Roumen

**Comment by daixiang0** [comment]
I think dynamic engine should log something rather than let developers read source codes to get it.

**Comment by petrovr** [comment]
Loong Dai wrote:
> I think dynamic engine should log something rather than let developers read source codes to get it.
> 

It is not supposed for direct use. At end "id" is changed.


Regards,
Roumen Petrov


P.S. You test case lacks commands to load "real" engine.

$ openssl engine -vvv
(dynamic) Dynamic engine loading support
      SO_PATH: Specifies the path to the new ENGINE shared library
           (input flags): STRING
      NO_VCHECK: Specifies to continue even if version checking fails (boolean)
           (input flags): NUMERIC
      ID: Specifies an ENGINE id name for loading
           (input flags): STRING
      LIST_ADD: Whether to add a loaded ENGINE to the internal list (0=no,1=yes,2=mandatory)
           (input flags): NUMERIC
      DIR_LOAD: Specifies whether to load from 'DIR_ADD' directories (0=no,1=yes,2=mandatory)
           (input flags): NUMERIC
      DIR_ADD: Adds a directory from which ENGINEs can be loaded
           (input flags): STRING
      LOAD: Load up the ENGINE specified by other settings
           (input flags): NO_INPUT

Hint: path vs directory+id

**Comment by daixiang0** [comment]
Thanks, the bug label should be removed.
