### ISSUE TITLE
I want to enable aes128-sha in tlsv1, but disable aes128-sha in tlsv2. How should I configure it in nginx?

### ISSUE THREAD

**Issue by NotFound-SF** [openssl/openssl#17245]

**Comment by t8m** [comment]
What do you mean by tlsv1 and tlsv2? If you mean tlsv1.0 and tlsv1.2 - it is not possible to enable/disable ciphersuites on per protocol version basis except for the tlsv1.3 version which has completely separate ciphersuites settings from the other tls versions.

All this assumes nginx uses OpenSSL.
