### ISSUE TITLE
 no-dtls1-method no-dtls1_2 fails tests

### ISSUE THREAD

**Issue by benlaurie** [openssl/openssl#1724]
```
Test Summary Report
-------------------
../test/recipes/90-test_sslapi.t         (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=87, Tests=468, 76 wallclock secs ( 0.63 usr  0.09 sys + 45.42 cusr 37.74 csys = 83.89 CPU)
Result: FAIL
Failed 1/87 test programs. 1/468 subtests failed.
```

**Comment by richsalz** [comment]
Can you try
                make TESTS=test_sslapi V=1 tests
?

We should document that somewhere.

**Comment by mattcaswell** [comment]
> We should document that somewhere.

We do:

https://github.com/openssl/openssl/blob/master/INSTALL#L632

**Comment by richsalz** [comment]
Perhaps “make test” can be augmented to point there on any failures?

**Comment by benlaurie** [comment]
Splendid idea.

**Comment by benlaurie** [comment]
../util/shlib_wrap.sh ./sslapitest ../apps/server.pem ../apps/server.pem => 1

#   Failed test 'running sslapitest'
#   at ../test/recipes/90-test_sslapi.t line 20.
# Looks like you failed 1 test of 1.
../test/recipes/90-test_sslapi.t .. 
1..1
./sslapitest: 92 test cases
SSL_connect() failed -1, 1
No progress made
Unable to create SSL connection
** test_large_message_dtls failed **
--------
SSL_accept() failed -1, 1
SSL_connect() failed -1, 1
SSL_connect() failed -1, 1
SSL_accept() failed -1, 1
SSL_connect() failed -1, 1
SSL_accept() failed -1, 1
SSL_connect() failed -1, 1
SSL_accept() failed -1, 1
./sslapitest: 1 test failed (out of 92)
not ok 1 - running sslapitest
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

Test Summary Report
-------------------
../test/recipes/90-test_sslapi.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.18 cusr  0.03 csys =  0.23 CPU)
Result: FAIL
Failed 1/1 test programs. 1/1 subtests failed.

**Comment by mattcaswell** [comment]
Doesn't seem to be an issue any more either in current master or 1.1.0. Closing.
