### ISSUE TITLE
Openssl 1.1.1m test failure

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#17283]
I ran all the tests on x86_64 and I get this single error from the whole list, everything else passes. This is on QNX though but I don't think it has much to do with the platform.

> 
>     # Subtest: ./evp_test
>     1..1
>         # Subtest: run_file_tests
>         1..1
>         # INFO:  @ ../../dist/test/testutil/stanza.c:21
>         # Reading ../../../dist/test/recipes/30-test_evp_data/evpkdf.txt
>         # INFO:  @ ../../dist/test/testutil/stanza.c:121
>         # Starting "TLS1 PRF tests (from NIST test vectors)" tests at line 15
>         # INFO:  @ ../../dist/test/testutil/stanza.c:121
>         # Starting "HKDF tests (from RFC5869 test vectors)" tests at line 72
>         # INFO:  @ ../../dist/test/testutil/stanza.c:121
>         # Starting "id-scrypt tests (from draft-josefsson-id-scrypt-kdf-03 and others)" tests at line 255
>         # INFO:  @ ../../dist/test/evp_test.c:2390
>         # ../../../dist/test/recipes/30-test_evp_data/evpkdf.txt:298: Expected KDF_MISMATCH got KDF_DERIVE_ERROR
>         # 1:error:060B5041:digital envelope routines:EVP_PBE_scrypt:malloc failure:../../dist/crypto/evp/pbe_scrypt.c:242:
>         # INFO:  @ ../../dist/test/testutil/stanza.c:33
>         # Completed 39 tests with 1 errors and 0 skipped
>         not ok 1 - ../../../dist/test/recipes/30-test_evp_data/evpkdf.txt
>     not ok 1 - run_file_tests
> ../util/shlib_wrap.sh ./evp_test ../../../dist/test/recipes/30-test_evp_data/evpkdf.txt => 1
> not ok 4 - running evp_test evpkdf.txt
>

**Comment by kaduk** [comment]
scrypt is designed to use a lot of memory, so it's understandable that just this test is failing and in this way.
How much memory do you expect to be available to applications on this system?

**Comment by dlegaultbbry** [comment]
QEMU virtual target we run this on has 1GB of memory available for the system. This test has never failed in the same setup for all of 1.1.1 previous releases. I can try bumping the memory higher and see what happens only for this test.

**Comment by dlegaultbbry** [comment]
ok, I bumped memory to 2G and it works now, all good.
