### ISSUE TITLE
TLS1.3 client does not respond to certificate renegotiation

### ISSUE THREAD

**Issue by zhangjie928** [openssl/openssl#17288]
TLS1.3 I want the client and server to renegotiate the certificate authentication after the handshake is successful
1. Before the SSL handshake, the client uses SSL_set_post_handshake_auth to set 1 to add an extension for authentication
2. After the handshake is successful, the server uses SSL_verify_client_post_handshake and starts the handshake again
3. I saw that the server sent CertificateRequest packets, but the client did not respond to the decrypted TLS1.3 packets. May I ask why?
Does the client also need to call any interface after a successful handshake?

The screenshot of the packet is as follows:
![d6869524436df871f0ff5db1bd41fad](https://user-images.githubusercontent.com/90365779/146345946-f0ce9dc8-5b2b-4010-b3ae-00a31e74e747.png)

**Comment by mattcaswell** [comment]
I assume you are using OpenSSL on both client and server. Does the client attempt to read the data being sent from the server? The client needs to read data received from the server (e.g. via SSL_read()) in order to know that there is a CertificateRequest message waiting to be processed.

**Comment by zhangjie928** [comment]
1. I use OpenSSL for both server and client
2. After receiving a CertificateRequest packet, the client uses BIO_write BIO_pendig SSL_read to parse the packet. However, when SSL_read is used to parse the packet's buffer, -1 is returned
3. The following Application Data is encrypted HTTP. Use BIO_write BIO_pendig SSL_read to decrypt the HTTP buffer correctly

**Comment by kaduk** [comment]
Does the client actually configure a usable certificate and keypair?

**Comment by zhangjie928** [comment]
1. During client and server initialization, Both SSL_CTX_use_certificate_file and SSL_CTX_use_PrivateKey_file are called to configure the certificate and private key, and SSL_CTX_lode_verify_locations are called to configure the CA certificate
2. During the handshake, the server also sends a CertificateRequest. When the client replies with Change Cipher Spec, its certificate is also sent, as shown in the picture of the packet
3. After the handshake succeeds, do I need to reset the certificate configuration on the client?

**Comment by zhangjie928** [comment]
The problem has been solved

**Comment by vijayyande** [comment]
I am also facing same issue, Can you please post how you solved issue?

I am tying to find sequence of steps to request clients certificate for tls1.3
