### ISSUE TITLE
broken "external keys" in stable 3.0

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#17286]
Issue #17092 is for keys loaded using engine api.
This issue is for "external keys" using own "key method". Engine load is not related.

Issue is from PKIX-SSH, direct use of PKCS11 provider.

EC key from token:
ssh[32737]: Offering public key: 'x509v3-ecdsa-sha2-nistp256' .... SHA256:VE1ofEdcwJZNDGfGinLnpuyjB3bvGe3oKKgUpE/WgkA token
ssh[32737]: error: ssh_x509_EVP_PKEY_sign: final fail
ssh[32737]: error: ssh_x509_sign: crypto message: '**error:0800007D:elliptic curve routines::missing private key**'
ssh[32737]: error: sign_and_send_pubkey: signing failed for x509v3-ecdsa-sha2-nistp256 "...." - error in libcrypto

RSA key from token:
ssh[509]: Offering public key: 'x509v3-rsa2048-sha256' C=XX,ST=World,..... RSA+cert SHA256:aowOzXPHdq3BPj7J6HhMOgvpepYQ3L8lpFYa8mZgBCs token
ssh[509]: error: ssh_x509_EVP_PKEY_sign: final fail
ssh[509]: error: ssh_x509_sign: crypto message: '**error:020000B3:rsa routines::missing private key**'
ssh[509]: error: ssh_x509_sign: crypto message: '**error:1C880004:Provider routines::RSA lib**'
ssh[509]: error: sign_and_send_pubkey: signing failed for x509v3-rsa2048-sha256 "C=XX,ST=World,....." - error in libcrypto

For protocol key-method  implementation is in ssh-pkcs11-client.c . 
Remark: OpenBSD uses different code, and provides some regression test. It is expected to fail in similar way as key method functionality is similar. PKIX-SSH does not provide yet public tests due to huge list required third party software.

**Comment by petrovr** [comment]
There is indication that OpenSSL wrongly consider key with custom key method as "provider keys". As result it returns "cashed copy" in get{0|1} methods and as expected data set on "cache" are lost.

**Comment by beldmit** [comment]
I'm not sure it's an OpenSSL bug. It looks to me as intentional behavior change. 

If I'm not mistaken, the RSA key object is created via `d2i_PUBKEY`, and at this moment we don't have any information that it will be a legacy object. After that `EVP_PKEY_get1_RSA` creates a copy of RSA (behavior change) and then after setting the RSA_METHOD it's necessary to reassign this new RSA object to the old EVP_PKEY object. 

@petrovr Do I correctly understand what happens?

**Comment by petrovr** [comment]
build hint:
  CPPFLAGS="$CPPFLAGS -DENABLE_CALL_TRACE"
  CPPFLAGS="$CPPFLAGS -DENABLE_NSS_TRACE"

in nss_init_keyctx_rsa comment #ifndef HAVE_EVP_KEYMGMT_GET0_PROVIDER and closing #endif

test hint:
Update tests/openssl.cnf.in and uncomment DEBUG = 3

Let read sign-rsa-sha1.err :
...
DEBUG[e_nss] Signer's certificate found.
TRACE[e_nss] nss_load_key(): wincx=0x7ffcbed74ca0
TRACE_E_NSS:nss_pass_func()  args: slot=0x12182a0, retry=0, arg=0x7ffcbed74ca0
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetSlotName()='NSS User Private Key and Certificate Services'
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetTokenName()='NSS Certificate DB'
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetMinimumPwdLength()=0
TRACE_E_NSS:nss_pass_func_ui_method()  NSS_UI ui_method=0x1185d20, ui_data=0x7ffcbed74dc0
TRACE_E_NSS:nss_pass_func_ui_method()  prompt='Enter pass phrase for NSS Certificate DB:'
TRACE_E_NSS:nss_pass_func_ui_method()  buf1='testing'
TRACE_E_NSS:nss_pass_func_ui_method()  UI result[0]='testing'
TRACE[e_nss] nss_load_key(): pvtkey=0x1222520
TRACE[e_nss] nss_load_key(): pubkey=0x12210c0
TRACE[e_nss] nss_load_key(): q=0x1223510
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x1234210
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE[e_nss] nss_load_key(): pkey=0x1233dc0
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x1233390
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE_E_NSS:nss_init_keyctx_rsa()  RSA by default!
TRACE[e_nss] nss_load_key(): keyctx=0x1233390
TRACE[e_nss] nss_load_key(): keyctx->pvtkey=0x1222520
TRACE[e_nss] nss_load_key(): keyctx->pubkey=0x12210c0
TRACE[e_nss] nss_load_key(): ^ pkey=0x1233dc0
TRACE[e_nss] nss_rsa_sign(): args: dtype=64, m=0x7ffcbed74d20, m_length=20
TRACE[e_nss] nss_rsa_sign(): rsa=0x1234120, meth=0x1185fc0, name=NSS PKCS#1 RSA method
TRACE[e_nss] nss_rsa_sign(): keyctx=0x1234210
TRACE[e_nss] nss_rsa_sign(): keyctx->pvtkey=0x0
TRACE[e_nss] nss_rsa_sign(): ret=0
Error signing data
...

1.  Line TRACE[e_nss] nss_load_key(): q= ... is before conversion
2.  Line TRACE[e_nss] nss_load_key(): pkey= ... is after conversion
3.  Lines between are with nss_rsa_init, i.e. engine method is called. So during conversion OpenSSL code knows engine.

Please check pkey attribute on point 2. It is set!
The only function called is EVP_PKEY_get_base_id just after d2i_PUBKEY.

**Comment by beldmit** [comment]
Should this comment go to the issue #17092  instead of this issue?

**Comment by beldmit** [comment]
With my patch and commented `#ifndef HAVE_EVP_KEYMGMT_GET0_PROVIDER` in `nss_init_keyctx_rsa` I get

Unfortunately I don't know how to show the paths to a local copy of OpenSSL so I crafted the command myself.

```
$ CONFIG_DIR=`pwd`/tests/nssdb OPENSSL_ENGINES=`pwd`/engines/.libs/ OPENSSL_CONF=`pwd`/tests/openssl.cnf LD_LIBRARY_PATH=../openssl ../openssl/apps/openssl dgst -sha256 -sign "E_NSS Certificate (client-rsa) - E_NSS Test Team cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω" -keyform ENGINE -engine e_nss -passin file:tests/nsspassfile /home/dbelyavs/upstream/e_nss-4.2/tests/openssl.cnf > sign
TRACE_E_NSS:bind_helper()  args: e=0x13f46c0, id=<none>
TRACE_E_NSS:bind_nss()  args: e=0x13f46c0
TRACE_E_NSS:bind_nss_rsa_method()  nss_rsa_ctx_index=1
TRACE_E_NSS:bind_nss_rsa_method()  rsa_method=0x7f6dd4d2bd00[OpenSSL PKCS#1 RSA]
TRACE_E_NSS:bind_nss_dsa_method()  nss_dsa_ctx_index=1
TRACE_E_NSS:bind_nss_dsa_method()  dsa_method=0x7f6dd4d2a960[OpenSSL DSA method]
TRACE_E_NSS:bind_nss_ec_method()  ec_method=0x13f9170
TRACE_E_NSS:bind_nss_ec_method()  nss_ec_ctx_index=1
TRACE_E_NSS:nss_ctrl()  cmd=211/DEBUG: i=3, p=(nil), f=(nil)
TRACE_E_NSS:nss_ctrl()  cmd=210/CONFIG_DIR: i=0, p=0x13f57a0, f=(nil)
TRACE_E_NSS:nss_init()  args: e=0x13f46c0
TRACE_E_NSS:nss_init_eng_ctx()  e=0x13f46c0, nss_eng_ctx_index=-1
TRACE_E_NSS:nss_init_eng_ctx()  nss_eng_ctx_index=2
TRACE_E_NSS:nss_init_eng_ctx()  ctx=0x13f9650
TRACE_E_NSS:nss_init()  ^ ok
TRACE_E_NSS:nss_digests()  requested nid list
TRACE_E_NSS:nss_pkey_meths()  requested nid list
Engine "e_nss" set.
INFO[e_nss] Loading private key - 'E_NSS Certificate (client-rsa) - E_NSS Test Team cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω'.
TRACE[e_nss] nss_init_database(): NSS_Init('/home/dbelyavs/upstream/e_nss-4.2/tests/nssdb') ...
TRACE[e_nss] nss_init_database(): FIPS mode: 0, PK11_IsFIPS()=0
DEBUG[e_nss] Signer's certificate found.
TRACE[e_nss] nss_load_key(): wincx=0x7fff3dd96180
TRACE_E_NSS:nss_pass_func()  args: slot=0x1452e20, retry=0, arg=0x7fff3dd96180
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetSlotName()='NSS User Private Key and Certificate Services'
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetTokenName()='NSS Certificate DB'
TRACE_E_NSS:nss_pass_func_ui_method()  PK11_GetMinimumPwdLength()=0
TRACE_E_NSS:nss_pass_func_ui_method()  NSS_UI ui_method=0x13f5600, ui_data=0x7fff3dd962c0
TRACE_E_NSS:nss_pass_func_ui_method()  prompt='Enter pass phrase for NSS Certificate DB:'
TRACE_E_NSS:nss_pass_func_ui_method()  buf1='testing'
TRACE_E_NSS:nss_pass_func_ui_method()  UI result[0]='testing'
TRACE[e_nss] nss_load_key(): pvtkey=0x149cca0
TRACE[e_nss] nss_load_key(): pubkey=0x149e0e0
TRACE[e_nss] nss_load_key(): q=0x149ea50
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x14b0050
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE[e_nss] nss_load_key(): pkey=0x14a10c0
TRACE_E_NSS:nss_rsa_init()  ...
TRACE_E_NSS:nss_rsa_init()  idx: 1, ptr: 0x14afb40
TRACE_E_NSS:nss_rsa_init()  ^ ok
TRACE_E_NSS:nss_init_keyctx_rsa()  RSA by default!
TRACE[e_nss] nss_load_key(): keyctx=0x14afb40
TRACE[e_nss] nss_load_key(): keyctx->pvtkey=0x149cca0
TRACE[e_nss] nss_load_key(): keyctx->pubkey=0x149e0e0
TRACE[e_nss] nss_load_key(): ^ pkey=0x14a10c0
TRACE_E_NSS:NSS_KEYCTX_free_rsa()  idx: 1, ptr: 0x14b0050
TRACE[e_nss] nss_rsa_sign(): args: dtype=672, m=0x7fff3dd962b0, m_length=32
TRACE[e_nss] nss_rsa_sign(): rsa=0x14b0230, meth=0x13f8fe0, name=NSS PKCS#1 RSA method
TRACE[e_nss] nss_rsa_sign(): keyctx=0x14afb40
TRACE[e_nss] nss_rsa_sign(): keyctx->pvtkey=0x149cca0
TRACE[e_nss] nss_rsa_sign(): keyctx->pvtkey->keyType=1
TRACE[e_nss] nss_rsa_sign(): sigret=0x13fb310
TRACE[e_nss] nss_rsa_sign(): rv=0
TRACE[e_nss] nss_rsa_sign(): sigret=0x13fb310 len=256
TRACE[e_nss] nss_rsa_sign(): ret=1
TRACE_E_NSS:NSS_KEYCTX_free_rsa()  idx: 1, ptr: 0x14afb40
TRACE_E_NSS:nss_finish()  ...
TRACE_E_NSS:nss_finish()  NSS_Shutdown() ...
TRACE_E_NSS:nss_pkey_meths()  requested nid list
TRACE_E_NSS:nss_destroy()  ...
TRACE_E_NSS:destroy_nss_store()  e=0x13f46c0, nss_scheme='nss'
TRACE_E_NSS:destroy_nss_store()  loader=0x13f8eb0
```

**Comment by beldmit** [comment]
I still think it's related to #17092, and in **this** issue we have a completely different problem related to intentional OpenSSL behavior change.
