### ISSUE TITLE
Can't Build Program based on OpenSSL with C++ in CLion

### ISSUE THREAD

**Issue by LeviMarvin** [openssl/openssl#17290]
Can't Build Program based on OpenSSL with C++ in CLion
Env: OpenSSL 1.1.1l, mingw-64 9.0.0

ERROR INFO: OPENSSL_Uplink(00007FF8B47ECD30,08): no OPENSSL_Applink

When I try to add "#include <openssl/applink.c>", the complier echo a new error:

In file included from H:/Project/CLionProjects/ZetaCA/main.cpp:9:
H:/Project/CLionProjects/ZetaCA/include/openssl/applink.c: In function 'void** OPENSSL_Applink()':
H:/Project/CLionProjects/ZetaCA/include/openssl/applink.c:104:47: error: invalid conversion from 'void* (*)()' to 'void*' [-fpermissive]
(And More)

**Comment by mspncp** [comment]
applink.c is a C program which you attempt to compile as a C++ program (by #including it in main.cpp). Try to compile it as a separate C module and link it to your application instead.

**Comment by LeviMarvin** [comment]
I'm tried to including it in main.cpp but it can not be work!

**Comment by mspncp** [comment]
As I said in https://github.com/openssl/openssl/issues/17290#issuecomment-999818217: you can't include it in a C++ module because it is a C program which won't compile with a C++ compiler.

**Comment by LeviMarvin** [comment]
The final proposal is coercion type conversion (void *)  in applink.c

**Comment by LeviMarvin** [comment]
I'm tired using `extern "C"` but still notice "Uplink (xxxx) no OpenSSL_Applink"

**Comment by mspncp** [comment]
Have you tried to compile applink.c separately as C program into an object file and link the resulting object file statically against your program?

**Comment by mspncp** [comment]
Sorry, I was on the wrong track: the applink.c file actually checks whether `__cplusplus` is defined and uses `extern "C"` itself , so at least it seems like it should be includable in a C++ module.

https://github.com/openssl/openssl/blob/999cce6ea7393e1daa40e9994064b2955b24a831/ms/applink.c#L81-L83

**Comment by LeviMarvin** [comment]
The applink.c changed is also can be work in C programs. Just including it in main.cpp
