### ISSUE TITLE
Improving return value documentation of stack (push) function?

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#17314]
According to the documentation for [OpenSSL1.1.1](https://www.openssl.org/docs/man1.1.1/man3/DEFINE_SPECIAL_STACK_OF.html) and [OpenSSL3](https://www.openssl.org/docs/man3.0/man3/DEFINE_SPECIAL_STACK_OF.html) this statement holds

> sk_TYPE_insert(), sk_TYPE_push() and sk_TYPE_unshift() return the total number of elements in the stack and 0 if an error occurred

When reviewing the code for this functionality in [OPENSSL_sk_push](https://github.com/openssl/openssl/blob/0d4c52320d245be80bd69346fdda4b12b4961eae/crypto/stack/stack.c#L370-L375) a return value of -1 can also occur (if there's no proper stack to work on).

Would it be prudent to add this as a "warning" return value to the documentation? 

Reason: I was tripped up by this when reviewing code like the one for [OBJ_add_sigid](https://github.com/openssl/openssl/blob/0d4c52320d245be80bd69346fdda4b12b4961eae/crypto/objects/obj_xref.c#L139-L201) for improving tests (#17311) thinking an incorrectly initialized stack (of NID triplets in this case) can cause problems. Actually, in this instance this is not the case because of code guarding the parameters to `sk_nid_triple_new`. This "guard code" is essential to avoid an apparent "success" (non-0) return value when using the `push` functions. 

But then again, this is code so old that it's probably already well-known to any user of OpenSSL's stack functions.

**Comment by t8m** [comment]
IMO this documentation issue should be fixed.

**Comment by baentsch** [comment]
> IMO this documentation issue should be fixed.

When starting to write this up, it emerged that `OPENSSL_sk_push` is the only function with this weird behaviour. All others treat an uninitialized stack as an error (retval = 0 or NULL) -> Might it not be more sensible (safe?) to change the code (to also return 0 when `OPENSSL_STACK *`==NULL)?

**Comment by t8m** [comment]
> Would it be prudent to add this as a "warning" return value to the documentation?

-1 is not a "warning" return value - usually it means something like a fatal error.

Anyway, with strict interpretation we should not change the return value as it is part of the API. On the other hand to make the API more uniform, we could change it in master branch to 0. I do not think such change would be eligible for backport though.

**Comment by baentsch** [comment]
> -1 is not a "warning" return value - usually it means something like a fatal error.

Again I learned something new. I thought retval=0 is error and !=0 is OK -- as is also [encoded in the test harness](https://github.com/openssl/openssl/blob/0d4c52320d245be80bd69346fdda4b12b4961eae/test/testutil/tests.c#L260-L274).

> On the other hand to make the API more uniform, we could change it in master branch to 0.

That I'd like. Less room for errors.

> I do not think such change would be eligible for backport though.

That would be sad. That would mean 3 PR's: Documentation update for `openssl-1.1.1` and `openssl3.0` and code change for `master`, correct?

**Comment by t8m** [comment]
> I thought retval=0 is error and !=0 is OK -- as is also [encoded in the test harness](https://github.com/openssl/openssl/blob/0d4c52320d245be80bd69346fdda4b12b4961eae/test/testutil/tests.c#L260-L274).

Nope, this is not universally true across the functions. Many of them return just 0 or 1 to indicate failure or success, but there are also plenty of functions which indicate 1 as success, 0 as failure and -1 as a fatal or operation error. Such as the functions that verify signatures.

**Comment by t8m** [comment]
> That would be sad. That would mean 3 PR's: Documentation update for `openssl-1.1.1` and `openssl3.0` and code change for `master`, correct?

Yes

**Comment by t8m** [comment]
The documentation was changed on all branches. Closing.
