### ISSUE TITLE
Openssl stucks on SSL_library_init() when compiled on FreeBSD (clang9 and clang11) when using -fsanitize=address

### ISSUE THREAD

**Issue by juanmitaboada** [openssl/openssl#17339]
I am getting my software stuck when starting Openssl on **FreeBSD 13** (OpenSSL 1.1.1k-freebsd  25 Mar 2021) when using **-fsanitize=address** in **clang11**, same problem happens with **clang9**.

The problem happens indistinctly with:
- OpenSSL_add_all_algorithms();
- SSL_library_init()
- SSL_load_error_strings();

To reproduce the problem:
```
#include <openssl/ssl.h>

int main(int argc, char *argv[]) {
    SSL_library_init();
    return EXIT_SUCCESS;
}
```

Then compile and execute:
```
clang  -lssl -lcrypto -fsanitize=address -o test test.c && ./test
```

Compilation happens fine but the program stuck on **SSL_library_init()** using **100% of CPU**. Once the **-fsanitize=address** is **removed** everything works as expected.

Thank you,

**Comment by kaduk** [comment]
A few notes:

- It's no longer necessary for the application to call any of those three functions; openssl 1.1.0 and later will automatically initialize itself.
- The indicated openssl version is the one provided by FreeBSD, which is not exactly the version maintained here.  It would be helpful if you could build a "stock" version of openssl to confirm the report
-  can you attach a debugger or otherwise trace execution to see where the binary is "stuck"?

I have a VM with an old 13-CURRENT snapshot handy, and in the build tree for the `OpenSSL_1_1_1-stable` branch (as of commit f2f7cff20377f7402b132a19d953a9d998be26aa), trying to run the test program in question produces:
```
$ LD_LIBRARY_PATH=. ./test
==50111==Sanitizer CHECK failed: /usr/src/contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_procmaps_bsd.cpp:71 ((Err)) == ((0)) (-1, 0)
```
which makes it hard to say that this is an openssl issue per se.
I will see if I can find time to play around with some other combinations, but getting more data from your end would be very helpful.

**Comment by kaduk** [comment]
If I also build openssl with asan (`./config --enable-asan`), it fails differently;
```
$ LD_LIBRARY_PATH=. ./test
ld-elf.so.1: ./libssl.so.1.1: Undefined symbol "__asan_option_detect_stack_use_after_return"
```

**Comment by juanmitaboada** [comment]
I made the same [question at stackoverflow](https://stackoverflow.com/questions/70452645/openssl-stucks-on-ssl-library-init-when-compiled-on-freebsd-clang9-and-clang1) and somebody commented on it:

> You're encountering this bug: [reviews.llvm.org/D84509](https://reviews.llvm.org/D84509) - ssl is calling qsort, which is broken when run with the address sanitizer. I do not have the search-fu to know when it gets fixed.

My doubt about this answer is: did nobody after all this time realized there was a problem with LLVM9-LLVM11 and SSL?, did nobody on the world compiled with sanitize until now? Am I that lucky?

LLVM releases:
- 25 Feb 2021	- **11.1.0**
- 14 Jan 2021	- **11.0.1**
- 12 Oct 2020	- **11.0.0**
- 6 Aug 2020	- **10.0.1**
- 24 Mar 2020	- **10.0.0**
- 20 Dec 2019	- **9.0.1**

Sincerely,

**Comment by t-j-h** [comment]
Don't use LLVM or clang. 
You can use GCC with ASAN support. I use it all the time across a range of GCC versions.

I have no issues with gcc ASAN usage.

**Comment by juanmitaboada** [comment]
I can confirm the problem also happens in **LLVM12** (8 July 2021 - **12.0.1**).

**Comment by juanmitaboada** [comment]
The bug was mentioned before about LLVM seems been fixed on 1 sept 2020 ( github.com/llvm/llvm-project/issues/46176 ) so I am not sure we are pointing at the same bug. LLVM12 was released on 8 july 2021 and the problem also happens with LLVM12. In the other hand the behaviour is exactly as described in that bug.

**Comment by paulidale** [comment]
The OpenSSL CI address sanitiser build uses clang.  On an Ubuntu VM not a FreeBSD one.

Did you build OpenSSL with address sanitisation enabled?  By passing `enable-asan` to the configuration command?

**Comment by juanmitaboada** [comment]
I backtraced the bug and this is not an OpenSSL bug, I have confirmed this is a LLVM bug as pointed before:
```
(gdb) bt
#0  0x000000000027ffa7 in wrapped_qsort_compar (a=0x80087ed60, b=0x80087eef0)
    at /usr/src/contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:9741
#1  0x0000000800d6e974 in qsort () from /lib/libc.so.7
#2  0x0000000000280083 in __interceptor_qsort (base=<optimized out>, nmemb=44, size=80, 
    compar=<optimized out>)
    at /usr/src/contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:9761
#3  0x0000000800d6f846 in qsort () from /lib/libc.so.7
#4  0x0000000000280083 in __interceptor_qsort (base=<optimized out>, nmemb=164, size=80, 
    compar=<optimized out>)
    at /usr/src/contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:9761
#5  0x000000080082b6af in ?? () from /usr/lib/libssl.so.111
#6  0x000000080083120e in ?? () from /usr/lib/libssl.so.111
#7  0x0000000800835f39 in ?? () from /usr/lib/libssl.so.111
#8  0x0000000800b8fe23 in pthread_once () from /lib/libthr.so.3
#9  0x00000008009a1019 in CRYPTO_THREAD_run_once () from /lib/libcrypto.so.111
#10 0x0000000800835ce2 in OPENSSL_init_ssl () from /usr/lib/libssl.so.111
#11 0x00000000002b37a9 in main ()
(gdb) 
```

Thank you for your help.

**Comment by kaduk** [comment]
https://github.com/freebsd/freebsd-src/commit/cbcfe28f9d5f975f97b7fb4a0d72bc9780eb0c46 seems to claim to have resolved the underlying issue on the FreeBSD side.
