### ISSUE TITLE
LDAP support for s_client -starttls

### ISSUE THREAD

**Issue by ChadSikorra** [openssl/openssl#1733]
It would be very useful to support LDAP for a starttls protocol. It is actually implemented as an extended operation in LDAP. There are some basic details in section 4.14 of this RFC: http://www.rfc-editor.org/rfc/rfc4511.txt

**Comment by ChadSikorra** [comment]
Interestingly enough I found the following patch, though it seems like it never made it in:

https://groups.google.com/forum/#!topic/mailing.openssl.users/1OOwXp45iIw

**Comment by ChadSikorra** [comment]
I created a PR here: https://github.com/openssl/openssl/pull/1735. In case anyone is interested in pursuing this.

**Comment by quanah** [comment]
Would be extremely useful to have this functionality.

**Comment by robert-scheck** [comment]
PR #2293 got merged, so this could be closed now?

**Comment by richsalz** [comment]
yes, thanks :)
