### ISSUE TITLE
Is RSA_sign thread-safety?

### ISSUE THREAD

**Issue by lougxing** [openssl/openssl#17335]
int RSA_sign(int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, _RSA_ _*rsa);_

I use RSA_sign,    **rsa**  is a global variable. **_rsa_** is initialized at startup,  I am sure that It will not be modified.

threads call RSA_sgin with the same _**rsa**_.

INFO : 
os :  centos6.2 
version : openssl-devel-1.0.1e-57.el6.x86_64

**Comment by mattcaswell** [comment]
No. You cannot assume `RSA_sign` is thread safe when using an RSA object shared between multiple threads.

**Comment by lougxing** [comment]
Do RSA_sign alter the  RSA object ？ @mattcaswell

**Comment by mattcaswell** [comment]
Yes, it may change it (for example for blinding) although it does so under a lock. If any other thread makes a change to the RSA though then RSA_sign() will not be thread safe. I just realised you said that you are sure that it won't be modified - so under those conditions RSA_sign() should be ok.

**Comment by lougxing** [comment]
Can RSA object  be a thread local var, and reuse for every request ?

**Comment by t8m** [comment]
The accesses to the blinding are under lock so if you do not modify the RSA object yourself, it should be safe to call RSA_sign() in multiple threads concurrently with the same RSA object.

**Comment by lougxing** [comment]
Thanks @t8m. This is a good news.  
I think I can now optimize our service with confidence，The original coder was afraid that there was an RSA contention problem, creating a temporary RSA object before calling RSA_sign, which affected the throughput of the service.
