### ISSUE TITLE
KTLS with openssl 3.0 fail with error ENOTCONN(Transport endpoint is not connected)

### ISSUE THREAD

**Issue by jaingaurav2712** [openssl/openssl#17337]
**Kernel Support for KTLS:**
kernel version is 5.15
CONFIG_TLS=y
CONFIG_TLS_DEVICE=y
CONFIG_CRYPTO_TLS=y

**Openssl:**
$ ./ Configure enable-ktls linux-aarch64
$ make

**Server**
$ ./openssl version
OpenSSL 3.0.2-dev 14 Dec 2021 (Library: OpenSSL 3.0.0 7 sep 2021)
$ ./openssl s_server -key rsa.key -cert server.pem -accept 443

**error**
file: crypto/bio/bio_sock2.c
function: BIO_socket()
ktls_enable(sock); failed with ENOTCONN error
setsockopt failed, 107, Transport endpoint is not connected

**server logs( added some debug logs)**
root@imx8mmevk:~# ./openssl s_server -key rsa.key -cert server.pem -accept 443
sk->sk_state != TCP_ESTABLISHED (log added in kernel net/tls/tls_main.c)
sk->sk_state != TCP_ESTABLISHED
BIO_socket sock_family = 10, sock_type = 1, sock_protocol = 6, return = 3
setsockopt failed, 107, Transport endpoint is not connected
BIO_socket, ktls_enable(asock) = 0
ACCEPT
setsockopt failed, 17, File exists
BIO_new_socket, ktls_enable(s) = 0
-----BEGIN SSL SESSION PARAMETERS-----
MF8CAQECAgMDBALAMAQABDAC9MHCSSlLXrS0D8tq2hCZtW0vmB1EC6HQerBThuev
PdX7VOUnD1a2bybdw1LfEiqhBgIEYcLciaIEAgIcIKQGBAQBAAAArQMCAQGzAwIB
HQ==
-----END SSL SESSION PARAMETERS-----
Shared ciphers:ECDHE-RSA-AES256-GCM-SHA384
Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:DSA+SHA256:DSA+SHA384:DSA+SHA512
Supported Elliptic Curve Point Formats: uncompressed:ansiX962_compressed_prime:ansiX962_compressed_char2
Supported groups: x25519:secp256r1:x448:secp521r1:secp384r1
Shared groups: x25519:secp256r1:x448:secp521r1:secp384r1
CIPHER is ECDHE-RSA-AES256-GCM-SHA384
Secure Renegotiation IS supported
Using Kernel TLS for sending fail
Using Kernel TLS for receiving fail

**Comment by mattcaswell** [comment]
Its unclear what you have done to get this output. It seems to me you have added additional debug logging to the OpenSSL source? If so, please supply further details of exactly what you have changed.

From the supplied output it looks to me like a connection was successfully established - but it didn't use KTLS? I would not have expected it to since you did not supply the "-ktls" option to s_server.

**Comment by jaingaurav2712** [comment]
I added additional logs for debugging. as I am not getting the success log (Using Kernel TLS for sending).
log added in kernel(file net/tls/tls_main.c)
kernel is returning error -ENOTCONN when (sk->sk_state != TCP_ESTABLISHED) in function static int tls_init(struct sock *sk)

you are right that connection is establishing but it is not using ktls.

As per openssl changelog(https://www.openssl.org/news/changelog.html#openssl-30), support for Kernel TLS (KTLS) was added in openssl 3.0 and I am using OpenSSL 3.0.2-dev.
"-ktls" option was introduced in OpenSSL 3.1.0.(https://www.openssl.org/docs/manmaster/man1/openssl-s_server.html)

I am not sure if ktls support was added in openssl 3.0, then why "-ktls" option is introduced in 3.1.0.

can you confirm which openssl version has the working support for ktls?

**Comment by jaingaurav2712** [comment]
As suggested by you, i tried with -ktls option with openssl 3.1.0, but still ktls is not working

**$ openssl version**
OpenSSL 3.1.0-dev  (Library: OpenSSL 3.1.0-dev )

**$ openssl s_server -ktls -key rsa.key -cert server.pem -accept 443**
sk->sk_state != TCP_ESTABLISHED

ACCEPT
-----BEGIN SSL SESSION PARAMETERS-----
MF8CAQECAgMDBALAMAQABDADNEkWucVTZpiKPtRz48bGM1wHHnOUlta9WcSH9Q3y
4jdP8DgTAZAkrkD9SbCbs6uhBgIEYdQH96IEAgIcIKQGBAQBAAAArQMCAQGzAwIB
HQ==
-----END SSL SESSION PARAMETERS-----
Shared ciphers:ECDHE-RSA-AES256-GCM-SHA384
Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:DSA+SHA256:DSA+SHA384:DSA+SHA512
Supported Elliptic Curve Point Formats: uncompressed:ansiX962_compressed_prime:ansiX962_compressed_char2
Supported groups: x25519:secp256r1:x448:secp521r1:secp384r1
Shared groups: x25519:secp256r1:x448:secp521r1:secp384r1
CIPHER is ECDHE-RSA-AES256-GCM-SHA384
Secure Renegotiation IS supported

**$ openssl s_client -quiet -connect 192.168.0.139:443 -cipher 'ECDHE-RSA-AES256-GCM-SHA384' -tls1_2 -ktls**
[1119274.610941] sk->sk_state != TCP_ESTABLISHED
Connecting to 192.168.0.139
Can't use SSL_get_servername
depth=0 C=IN, ST=NOIDA, L=NOIDA, O=NXP, OU=EP, CN=Gaurav, emailAddress=gaura.jain@nxp.com
verify error:num=18:self-signed certificate
verify return:1
depth=0 C=IN, ST=NOIDA, L=NOIDA, O=NXP, OU=EP, CN=Gaurav, emailAddress=gaura.jain@nxp.com
verify return:1

**Comment by jaingaurav2712** [comment]
I debugged further the invalid argument error reported from setsockopt called in ktls_start().
Problem is with **crypto_info->tls_crypto_info_len.**
when I applied the below change I could run s_server, s_client on linux with KTLS support. 
below patch enables the aes_gcm_128 ciphers
1. AES128-GCM-SHA256
2. ECDHE-RSA-AES128-GCM-SHA256

diff --git a/include/internal/ktls.h b/include/internal/ktls.h
index 95492fd065..30ed5072de 100644
— a/include/internal/ktls.h
+++ b/include/internal/ktls.h
@@ -285,7 +285,7 @@ static ossl_inline int ktls_start(int fd, ktls_crypto_info_t *crypto_info,
                                   int is_tx)
 {
     return setsockopt(fd, SOL_TLS, is_tx ? TLS_TX : TLS_RX,
  -crypto_info, crypto_info->tls_crypto_info_len) ? 0 : 1;
 +crypto_info, sizeof(crypto_info->gcm128)) ? 0 : 1;
 }

When trying to enable other 2 ciphers, I am getting build errors in openssl.
3. AES256-GCM-SHA384
4. ECDHE-RSA-AES256-GCM-SHA384
when trying to build openssl for gcm256, getting compilation errors:

In file included from crypto/bio/bio_sock2.c:15:
include/internal/ktls.h:251:46: error: field '**gcm256' has incomplete type**
         struct tls12_crypto_info_aes_gcm_256 gcm256;
                                              ^~~~~~
By default Openssl has support for  aes_gcm_128 ciphers.
When include kernel tls.h file in openssl, aes_gcm_256 ciphers can be built and run without errors.

I feel that Openssl KTLS support for Linux is broken.

**Comment by jaingaurav2712** [comment]
https://github.com/openssl/openssl/issues/17451
answered in above ticket.
