### ISSUE TITLE
Issue building on Mac M1 - 

### ISSUE THREAD

**Issue by sloughin** [openssl/openssl#17347]
Based on https://github.com/openssl/openssl/issues/13854#issuecomment-762508476 I switched my terminal to arm64 mode before attempting the build.  I then ran ./Configure followed by make per the instructions.  After compiling a number of source files, the build fails with the output shown below.  Thanks in advance for any advice on how to proceed.

rm -f apps/libapps.a
ar qc apps/libapps.a apps/lib/libapps-lib-app_libctx.o apps/lib/libapps-lib-app_params.o apps/lib/libapps-lib-app_provider.o apps/lib/libapps-lib-app_rand.o apps/lib/libapps-lib-app_x509.o apps/lib/libapps-lib-apps.o apps/lib/libapps-lib-apps_ui.o apps/lib/libapps-lib-columns.o apps/lib/libapps-lib-engine.o apps/lib/libapps-lib-engine_loader.o apps/lib/libapps-lib-fmt.o apps/lib/libapps-lib-http_server.o apps/lib/libapps-lib-names.o apps/lib/libapps-lib-opt.o apps/lib/libapps-lib-s_cb.o apps/lib/libapps-lib-s_socket.o apps/lib/libapps-lib-tlssrp_depr.o
/opt/local/bin/ranlib: object: apps/libapps.a(libapps-lib-app_libctx.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[1]: *** [apps/libapps.a] Error 1
make: *** [build_sw] Error 2

--- Config ---
perl configdata.pm --dump

Command line (with current working directory = .):

    /opt/local/bin/perl ./Configure

Perl information:

    /opt/local/bin/perl
    5.16.3 for darwin-thread-multi-2level

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    idea
    legacy
    loadereng
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    acvp-tests          [cascade]        OPENSSL_NO_ACVP_TESTS
    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    buildtest-c++       [default]        
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]        OPENSSL_NO_EGD
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fips                [default]        
    fips-securitychecks [cascade]        OPENSSL_NO_FIPS_SECURITYCHECKS
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [default]        OPENSSL_NO_KTLS
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]        OPENSSL_NO_SCTP
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]        
    zlib-dynamic        [default]        
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "qc",
    CC => "cc",
    CFLAGS => "-O3 -Wall",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib -c",
    RC => "windres",
    asm_arch => "x86_64",
    bn_ops => "SIXTY_FOUR_BIT_LONG",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-arch x86_64",
    cppflags => "-D_REENTRANT",
    defines => [ "OPENSSL_BUILDING_OPENSSL" ],
    disable => [  ],
    dso_scheme => "dlfcn",
    enable => [  ],
    includes => [  ],
    lflags => "-Wl,-search_paths_first",
    lib_cflags => "",
    lib_cppflags => "-DL_ENDIAN",
    lib_defines => [  ],
    module_cflags => "-fPIC",
    module_cxxflags => undef,
    module_ldflags => "-bundle",
    perl_platform => "Unix",
    perlasm_scheme => "macosx",
    shared_cflag => "-fPIC",
    shared_defines => [  ],
    shared_extension => ".\$(SHLIB_VERSION_NUMBER).dylib",
    shared_ldflag => "-dynamiclib -current_version \$(SHLIB_VERSION_NUMBER) -compatibility_version \$(SHLIB_VERSION_NUMBER)",
    shared_rcflag => "",
    shared_sonameflag => "-install_name \$(libdir)/",
    shared_target => "darwin-shared",
    sys_id => "MACOSX",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar
    ARFLAGS         = qc
    CC              = cc
    CFLAGS          = -O3 -Wall
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = /opt/local/bin/perl
    RANLIB          = ranlib -c
    RC              = windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl

**Comment by paulidale** [comment]
Was this a clean build or was some stuff left lying around from the earlier tries?

**Comment by sloughin** [comment]
Clean build, but just to be sure I removed the local copy and cloned it again...
rm -rf openssl
stephenloughin@steve-macmini dev % arch
arm64
stephenloughin@steve-macmini dev % git clone https://github.com/openssl/openssl.git
Cloning into 'openssl'...
remote: Enumerating objects: 419232, done.
remote: Total 419232 (delta 0), reused 0 (delta 0), pack-reused 419232
Receiving objects: 100% (419232/419232), 242.08 MiB | 10.94 MiB/s, done.
Resolving deltas: 100% (294624/294624), done.
Updating files: 100% (24308/24308), done.
stephenloughin@steve-macmini dev % cd openssl
stephenloughin@steve-macmini openssl % ./Configure
stephenloughin@steve-macmini openssl % make
... 
rm -f apps/libapps.a
ar qc apps/libapps.a apps/lib/libapps-lib-app_libctx.o apps/lib/libapps-lib-app_params.o apps/lib/libapps-lib-app_provider.o apps/lib/libapps-lib-app_rand.o apps/lib/libapps-lib-app_x509.o apps/lib/libapps-lib-apps.o apps/lib/libapps-lib-apps_ui.o apps/lib/libapps-lib-columns.o apps/lib/libapps-lib-engine.o apps/lib/libapps-lib-engine_loader.o apps/lib/libapps-lib-fmt.o apps/lib/libapps-lib-http_server.o apps/lib/libapps-lib-names.o apps/lib/libapps-lib-opt.o apps/lib/libapps-lib-s_cb.o apps/lib/libapps-lib-s_socket.o apps/lib/libapps-lib-tlssrp_depr.o
/opt/local/bin/ranlib: object: apps/libapps.a(libapps-lib-app_libctx.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[1]: *** [apps/libapps.a] Error 1
make: *** [build_sw] Error 2

**Comment by paulidale** [comment]
Hmmmmm, I just did a clean build here on an M1 without problem.  Is there anything special or odd about the toolchain being used?

**Comment by sloughin** [comment]
If all the tools used are those installed with XCode under MacOS Monterey, then it's just the standard issue stuff, but I will attempt a reinstall of the XCode and the command line tools and try again. Thanks for letting me know it's possible. I will post again if I discover what the problem is.

**Comment by levitte** [comment]
Earlier in your build log, there should be the build of libapps-lib-app_libctx.o itself, followed by errors/warnings. Please find it and show us.

**Comment by sloughin** [comment]
Sorry @levitte, was away for a few days.  There are no errors or warnings after building that module.

cc  -I. -Iinclude -Iapps/include  -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF apps/lib/libapps-lib-app_libctx.d.tmp -MT apps/lib/libapps-lib-app_libctx.o -c -o apps/lib/libapps-lib-app_libctx.o apps/lib/app_libctx.c
cc  -I. -Iinclude -Iapps/include  -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF apps/lib/libapps-lib-app_params.d.tmp -MT apps/lib/libapps-lib-app_params.o -c -o apps/lib/libapps-lib-app_params.o apps/lib/app_params.c

as you can see, it just moves on to the next compilation.  Here's the version info on my cc compiler:

% cc --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by paulidale** [comment]
I'm a release behind Monterey.  That's likely the smoking gun.  Still no ideas as to why unfortunately.

**Comment by sloughin** [comment]
Here's my [.o file](https://drive.google.com/file/d/1_gSUeWQBXEGqcttBUxwu0ZRYh3bDXtF2/view?usp=sharing) if you want to try diffing it -- probably no difference.  I bet the linker is the culprit.  Guess I'll wait for the next update of XCode to see if that helps.

**Comment by tom-cosgrove-arm** [comment]
@sloughin The `.o file` you provided a link to is an `x86_64` Mach-O file

@paulidale OpenSSL builds correctly "out of the box" on macOS Monterey 12.1 (although I am using the latest Command Line Tools, rather than Xcode specifically).

I'm not sure what the problem is, but it seems to be a local problem, and I suggest closing this issue (sorry).

Output of clone and build (and `file` on my `libapps-lib-app_libctx.o` and the one provided above) below.

```
$ uname -mrsv
Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
$ xcode-select -p
/Library/Developer/CommandLineTools
$ cc --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ git clone https://github.com/openssl/openssl.git
Cloning into 'openssl'...
remote: Enumerating objects: 422138, done.
remote: Total 422138 (delta 0), reused 0 (delta 0), pack-reused 422138
Receiving objects: 100% (422138/422138), 245.46 MiB | 8.49 MiB/s, done.
Resolving deltas: 100% (297004/297004), done.
Updating files: 100% (24332/24332), done.
$ cd openssl
$ git log -n1
commit d71151ae704847f4ac3f4a5f394ea64f1d229815 (HEAD -> master, origin/master, origin/HEAD)
Author: Nicola Tuveri <nic.tuv@gmail.com>
Date:   Wed Feb 23 23:05:22 2022 +0200

    [ssl] Add tests for Perfect Forward Secrecy criteria on SECLEVEL >= 3
    
    Reviewed-by: Dmitry Belyavskiy <beldmit@gmail.com>
    Reviewed-by: Paul Dale <pauli@openssl.org>
    Reviewed-by: Tomas Mraz <tomas@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/17763)
$ ./Configure
Configuring OpenSSL version 3.1.0-dev for target darwin64-arm64
Using os-specific seed configuration
Creating configdata.pm
Running configdata.pm
Creating Makefile.in
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************
$ make
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/asn1.h.in > include/openssl/asn1.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/asn1t.h.in > include/openssl/asn1t.h
:
:
chmod a+x util/shlib_wrap.sh
rm -f "util/wrap.pl"
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" util/wrap.pl.in > "util/wrap.pl"
chmod a+x util/wrap.pl
$ echo $?
0
$ file apps/lib/libapps-lib-app_libctx.o
apps/lib/libapps-lib-app_libctx.o: Mach-O 64-bit object arm64
$ file /tmp/downloaded/libapps-lib-app_libctx.o
/tmp/downloaded/libapps-lib-app_libctx.o: Mach-O 64-bit object x86_64
```

**Comment by paulidale** [comment]
@tom-cosgrove-arm, I agree.  Closing this.
