### ISSUE TITLE
SSL_CTX_set_cert_store does not increment store ref

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#1734]
`SSL_CTX_set_cert_store` does not increment the passed store's reference count.

Suggested fix to avoid breaking ABI is to add a new function `SSL_CTX_set1_cert_store` that does increment the reference.

Found by @wahern

**Comment by kaduk** [comment]
We added a SSL_CTX_set1_cert_store() to our local copy at some point; let me see how hard the patch is to extract.
(cc @tmshort )

**Comment by kaduk** [comment]
#1755

**Comment by daurnimator** [comment]
Fixed in b50052dbe822271c9d7b2559a38a127fca87e4ab.
