### ISSUE TITLE
ln: failed to create symbolic link 'libcrypto.so': Operation not supported

### ISSUE THREAD

**Issue by BABOU51** [openssl/openssl#17346]
This error shows up when $ make

rm -f libcrypto.so && \
ln -s libcrypto.so.3 libcrypto.so
ln: failed to create symbolic link 'libcrypto.so': Operation not supported
make[1]: *** [Makefile:4417: libcrypto.so] Error 1
make[1]: Leaving directory '/home/etudiant/partage/ProjetsVM/OignonVert/Dependencies/openssl'
make: *** [Makefile:3259 : build_sw] Erreur 2
![openssl](https://user-images.githubusercontent.com/62405336/147266816-71ca2841-bf66-405c-9248-36b14bf0105e.png)

**Comment by paulidale** [comment]
This isn't much to go on.  What operating system?  What file system?
Can you create a symbolic link manually in that directory?

**Comment by trungnmh90** [comment]
I think I saw this error couple times, but it is not openssl's fault. 
One time I built openssl on a guest virtualbox and set --prefix to the vboxfs folder which is shared with Windows. Unsurprisingly, Windows filesystem does not support symbolic link. It could be similar issue with yours. Set the prefix to the *nix native filesystem and see if it is resolved.
