### ISSUE TITLE
AVX2 CPU not detected by rsaz_avx2_eligible

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#17342]
My /proc/cpuflags has bmi1 bmi2 avx avx2 and adx, yet `rsaz_avx2_eligible()` returns false.

I've removed the `rsaz_avx2_eligible()` check at https://github.com/openssl/openssl/blob/a595e3286ae9f033c56452967b3add2145f9085f/crypto/bn/bn_exp.c#L664 and tested `RSAZ_1024_mod_exp_avx2()`, it doesn't crash and it produces the correct results, so rsaz_avx2_eligible() should probably return true in my case.

**Comment by paulidale** [comment]
You've got both BMI and AD*X which disables the AVX2 support:
```asm
$code.=<<___;
.extern	OPENSSL_ia32cap_P
.globl	rsaz_avx2_eligible
.type	rsaz_avx2_eligible,\@abi-omnipotent
.align	32
rsaz_avx2_eligible:
	mov	OPENSSL_ia32cap_P+8(%rip),%eax
___
$code.=<<___	if ($addx);
	mov	\$`1<<8|1<<19`,%ecx
	mov	\$0,%edx
	and	%eax,%ecx
	cmp	\$`1<<8|1<<19`,%ecx	# check for BMI2+AD*X
	cmove	%edx,%eax
___
$code.=<<___;
	and	\$`1<<5`,%eax
	shr	\$5,%eax
	ret
.size	rsaz_avx2_eligible,.-rsaz_avx2_eligible
```

The first $code block is checking for BMI2 and AD*X.  If they are present, it forces the result to zero.
The second $code block is checking for AVX2 but will always be false if BMI2 and AD*X are present.

Presumably, the AVX2 code path is slower.  At least for some processors.

You could force matters by setting the `OPENSSL_ia32cap` environment variable.

**Comment by guidovranken** [comment]
Oh ok, thanks, apologies for the false positive.
