### ISSUE TITLE
Possible Poly1305 modular reduction bug

### ISSUE THREAD

**Issue by Keith-Cancel** [openssl/openssl#17352]
Hello, so I was looking at out various libraries perform modular reduction for poly1305.

So I was looking at the assembly here:
line 110 of: [poly1305-x86_64.pl](https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/crypto/poly1305/asm/poly1305-x86_64.pl#L110)

I decided to run test vector number 5 from here: [IETF Test Vector](https://datatracker.ietf.org/doc/html/rfc8439#appendix-A.3) through the poly1305_iteration code. 

This test vector will set:
```
r0 = 0x02
r1 = 0x00
h0 = 0xffffffffffffffff
h1 = 0xffffffffffffffff
h2 = 0x01
```
After the multiplication stage in this code one does get:
```
0x3fffffffffffffffffffffffffffffffe
```
This is correct, but then the reduction stage [here](https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/crypto/poly1305/asm/poly1305-x86_64.pl#L138) does not reduce it further. It should reduce to ```0x03``` but just remains the same.
```
0x3fffffffffffffffffffffffffffffffe mod (2^130 - 5) = 0x03
```

What is interesting is crandall's reduction normally requires a subtraction as you can see from this image here, but I do not see such a subtraction in the code, this code is just performing the first part of the reduction with shifts and adds.
![crandall's reduction](https://user-images.githubusercontent.com/8355441/147343860-d3001376-a021-42ea-987a-3fbe9ea771f8.png)

While this seems highly unlikely to happen if R is chose randomly like it's supposed to be for poly1305. This seems like a bug unless there is something to correct the accumulator h0, h1, and h2 elsewhere but I don't see it.

**Comment by bernd-edlinger** [comment]
I don't know how it is corrected,
but the test rector No. 5 is part of our test suite, see:
https://github.com/openssl/openssl/blob/2080da84a49b0c52fc8c6e6caef5d373235bd3e4/test/recipes/30-test_evp_data/evpmac_poly1305.txt#L36-L40
So in the end the result seems to be correct.

**Comment by Keith-Cancel** [comment]
Interesting because it just returns here after calling the main loop. [poly1305_iteration](https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/crypto/poly1305/asm/poly1305-x86_64.pl#L272)

It is possible to perform one final reduction on the partially reduced result and still be correct. Like I do see the function poly1305_emit, but I don't see how it's being called after poly1305_blocks. If that test vector is passing on the scalar assembly code I guess something outside of this file must being calling something like poly1305_emit. That's why I said possible bug since at least invoking these assembly routines directly was failing in this case.

**Comment by t8m** [comment]
@Keith-Cancel the function poly1305_emit() is always invoked in the final step of the mac calculation. See `Poly1305_Final()` implementation in poly1305.c.

**Comment by Keith-Cancel** [comment]
Ah okay. I guess that's what I get for testing something too isolated from the rest of the code base.
