### ISSUE TITLE
Can RSA objects be reused with RSA_sign(...)  

### ISSUE THREAD

**Issue by yibubuyi** [openssl/openssl#17355]
version ：openssl-devel-1.0.1e-57.el6.x86_64
 os： centos

function：
  int RSA_sign(int type, const unsigned char *m, unsigned int m_len,
              unsigned char *sigret, unsigned int *siglen, RSA *rsa);
  

Can RSA objects be reused with RSA_sign(...)?  the RSA object only can be accessed by one thread.

**Comment by t8m** [comment]
Yes, they can be reused.
