### ISSUE TITLE
Bypassing Purpose/Trust Mechanism in X.509 Validation

### ISSUE THREAD

**Issue by insignificantman** [openssl/openssl#17367]
OpenSSL Version: 1.1.1l

I'm parsing and checking an X.509 cert's Key Usage and Extended Key Usage fields manually. So I think I don't need OpenSSL's built-in purpose-checking and trust-checking mechanisms as they serve the same purpose with less accuracy (and I don't think they are implemented properly because of funny comments asking questions in relevant functions' code). So I want to completely disable purpose and trust checking for X509_verify_cert() and such similar functions. 

How can I accomplish that? Setting purpose to X509_PURPOSE_ANY using X509_STORE_CTX_set_purpose() doesn't seem to work.

**Comment by mattcaswell** [comment]
> How can I accomplish that? Setting purpose to X509_PURPOSE_ANY using X509_STORE_CTX_set_purpose() doesn't seem to work.

Calling `X509_STORE_CTX_set_purpose()` using `X509_PURPOSE_ANY` should do what you need it to do. Can you elaborate more on the behaviour you are seeing?

**Comment by insignificantman** [comment]
It gives an error with string:
 
ˊˊˊ
error:0B086079:x509 certificate routines:X509_STORE_CTX_purpose_inherit:unknown purpose id
ˊˊˊ

**Comment by mattcaswell** [comment]
Interesting! That looks like a bug to me. This might work as a workaround. Instead of:

````
X509_STORE_CTX_set_purpose(ctx, X509_PURPOSE_ANY);
````
Try:
````
X509_STORE_CTX_set_purpose_inherit(ctx, X509_PURPOSE_ANY, X509_PURPOSE_ANY, 0);
````

**Comment by mattcaswell** [comment]
Note also that checking a purpose only occurs if a purpose has actually been set. So simply omitting a call to `X509_STORE_CTX_set_purpose` should also work.

**Comment by mattcaswell** [comment]
Fix for this issue in #17382.

**Comment by insignificantman** [comment]
@mattcaswell First of all thanks for the patch. This seemed weird to me it's why I mentioned "funny comments asking questions" in OpenSSL code.

I will ask something more: Is there anything I need to do to disable trust checking? or this is enough for both?

**Comment by mattcaswell** [comment]
Sorry for the slow response, I've been away on vacation.

> I will ask something more: Is there anything I need to do to disable trust checking? or is this enough for both purpose and trust?

Unless you do something else you will just get the default trust checking. I don't think there is an easy way to disable trust checking completely. Probably you could do it by adding a custom X509_TRUST object via `X509_TRUST_add` - but this appears to be undocumented and you would definitely be trailblazing if you went that route.

**Comment by insignificantman** [comment]
Hmm as I'm parsing and checking an X.509 cert's Key Usage and Extended Key Usage fields manually, do you think I need purpose & trust checking mechanisms at all?

**Comment by insignificantman** [comment]
Hmm as I'm parsing and checking an X.509 cert's Key Usage and Extended Key Usage fields manually, do you think I need purpose & trust checking mechanisms at all?

**Comment by mattcaswell** [comment]
If you don't have any certs with "Trust" settings then you don't need the trust features. Its unclear to me how widely used this feature is. I suspect hardly at all. At least my "/etc/ssl/certificates" store doesn't contain any certs with trust settings. That said if you don't have any certs with trust settings then I guess the built-in trust feature is harmless (i.e. a no-op).

The built-in purpose checking can do checks beyond just Key Usage and Extended Key Usage. I would be hesitant to completely remove the built-in checking with something custom without a very clear understanding of all the checks that the built-in support performs (you'd need to check the code for this).
