### ISSUE TITLE
dll name

### ISSUE THREAD

**Issue by ITSweets** [openssl/openssl#17361]
Hello, I would like to ask which is the name of the dll generated by OpenSSL under the windows VC compiler? I compiled the 1.1.1m version, and the default one is libcrypto-1_1.dll. How to modify it? Is the naming location and modification method the same as the version 3?

**Comment by Tobats1992** [comment]
go to Device settings and click About the whole info of ur Device info that
is connected to your own device also web is in there , check ur regulatory
and open sources ,all sources u will seen there is definitely ur Device
sources

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
