### ISSUE TITLE
Potential locking problem between methods open_console and lose_console

### ISSUE THREAD

**Issue by ycaibb** [openssl/openssl#17364]
Hi, I found a potential locking bug in methods open_console and close_console.

The lock `ui->lock` is acquired in the open_console.
https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/crypto/ui/ui_openssl.c#L373-L379

When `OPENSSL_SYS_VMS`  enabled and `status != SS$_NORMAL`, the lock `ui->lock` is not released in method close_console
https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/crypto/ui/ui_openssl.c#L552-L569

**Comment by t8m** [comment]
Fix in #17365
