### ISSUE TITLE
Why don't we have something similar to EVP_CIPHER_CTX_set_iv when OpenSSH supports it?

### ISSUE THREAD

**Issue by justinlolful** [openssl/openssl#17369]
I am trying to encrypt/decrypt large number data of size smaller than blocksize with AES on OpenSSL 1.1.1. All with same key but different IV.

For performance concern, instead of using standard flow of 

> `EVP_CIPHER_CTX_new`
> `EVP_CipherInit`
> `EVP_CipherUpdate`
> `EVP_CipherFinal`
> `EVP_CIPHER_CTX_free`

I am trying to use it as below to remove calls to `EVP_CIPHER_CTX_new`, `EVP_CipherInit` and `EVP_CIPHER_CTX_free`:

> `EVP_CIPHER_CTX_new`
> `EVP_CipherInit`
> `EVP_CipherUpdate`
> `EVP_CipherFinal`
> update iv and cipher_data
> `EVP_CipherUpdate`
> `EVP_CipherFinal`
> update iv and cipher_data
> `EVP_CipherUpdate`
> `EVP_CipherFinal`
> ......
> update iv and cipher_data
> `EVP_CipherUpdate`
> `EVP_CipherFinal`
> `EVP_CIPHER_CTX_free`

The way I update IV and cipher_data is: 
1. update IV with a pointer from `EVP_CIPHER_CTX_iv_noconst`.
2. update cipher_data from a copy of the initial cipher_data with `EVP_CIPHER_CTX_get_cipher_data` and `EVP_CIPHER_impl_ctx_size` (I dont think i need to update cipher_data for AES-CBC but apparently for AES-GCM, it contains information other than just the key)

So, my question is:
1. Why don't we have something similar to EVP_CIPHER_CTX_set_iv when OpenSSH supports it? Memcpy to pointer from `EVP_CIPHER_CTX_iv_noconst` looks less graceful to me.
2. If I upgrade to OpenSSL 3.0,  `EVP_CIPHER_CTX_iv_noconst` and `EVP_CIPHER_impl_ctx_size` are going to become deprecated and I haven't found replacement for them. Is it for security concern to remove them?

**Comment by t8m** [comment]
You do not need to recreate the context and recreate the key schedule.

You can set the IV (and keep the key schedule), by calling EVP_CipherInit() with NULL key and with the new iv.

**Comment by justinlolful** [comment]
Using `EVP_CIPHER_CTX_iv_noconst` still saves me about 10% (using a simple timer) compare to `EVP_CipherInit`. So It is just no longer going to be my option in the future?

**Comment by t8m** [comment]
Yes, at some point in future they are going to be removed.

The problem with EVP_CIPHER_CTX_iv_noconst  is that it forces the cipher implementations in the provider to do some particular things which they would not have to do if there were no such API calls.

EVP_CIPHER_CTX_set_iv() would be truly equivalent to EVP_CipherInit with just iv set and there would be always some overhead over directly setting the iv in the memory buffer obtained from EVP_CIPHER_CTX_iv_noconst.

**Comment by justinlolful** [comment]
Thanks! 

> there would be always some overhead over directly setting the iv in the memory buffer obtained from EVP_CIPHER_CTX_iv_noconst.

I will take that into consideration. (I think from source code, it's the difference between memcpy and setting iv in some kind of loop in `CRYPTO_gcm128_setiv` )
