### ISSUE TITLE
openssl/ec.h: EVP_EC_gen requires strstr

### ISSUE THREAD

**Issue by graywolf** [openssl/openssl#17362]
When porting a program to openssl, compilation failed because EVP_EC_gen requires strstr, but does not include string.h header. I've noticed this in released 3.0.1, but seems to be same on current master. This does not seem to be documented: https://www.openssl.org/docs/manmaster/man3/EVP_EC_gen.html .

I think it should be either mentioned in the documentation or just included in ec.h.

**Comment by t8m** [comment]
IMO just adding the include to the documentation would be the right fix. Always including it from ec.h seems a little overkill as the ec.h would be used mostly for the legacy EC function calls in existing software and these do not require string.h.

**Comment by mattcaswell** [comment]
I'm struggling to understand what the purpose of that `strstr` is anyway. Can we just remove it? It looks like a no-op?? Am I missing something? Perhaps @DDvO can shed some light?

**Comment by t8m** [comment]
Is it some kind of weird way to cast out the const?

**Comment by mattcaswell** [comment]
> Is it some kind of weird way to cast out the const?

But the underlying `EVP_PKEY_Q_keygen` uses a `va_arg` list anyway...so I would not expect that to make a difference.

**Comment by DDvO** [comment]
I would not have recalled myself why I introduced that weird-looking `strstr(..., "")` call but just found that I mentioned this in https://github.com/openssl/openssl/pull/14695#discussion_r613131677:
> I added `strstr(curve, "")` in order to provide type checking also for the string variadic arg.

@paulidale liked this and commented:

> Using `strstr(curve, "")` is clever. Another possibly would be `strchr(curve, *curve)`. I don't see much difference between the two, so this isn't a request to change. My initial thought for checking the string type was `curve ""` which doesn't work for pointers so I skipped it. I was in a rush so didn't dwell over other possibilities.

I responded:
> I checked also other possibilities and found that `strstr(curve, "")` is best because, as opposed to alternatives, it is linear in the curve parameter, so macro expansion does not cause problems in case the actual argument filled in for curve has side effects.

**Comment by paulidale** [comment]
I suggest just including string.h and adding a comment explaining why the strstr call is there.

**Comment by DDvO** [comment]
> I suggest just including string.h and adding a comment explaining why the strstr call is there.

Yes, this is what I had in mind, too. Done in #17380.
