### ISSUE TITLE
error:1408E0F4:SSL routines:ssl3_get_message:unexpected message:s3_both.c:408:

### ISSUE THREAD

**Issue by UniqueDavidQian** [openssl/openssl#17386]
i am building kafka cluster with ssl, when I check ssl configuration with

```
openssl s_client -connect kafka-server1:9093 -tls1_2 -servername kafka-server1
```

it shows that:

```
CONNECTED(00000003)
depth=1 emailAddress = test@qq.com
verify error:num=19:self signed certificate in certificate chain
140231283939216:error:1408E0F4:SSL routines:ssl3_get_message:unexpected message:s3_both.c:408:
---
Certificate chain
 0 s:/C=CN/ST=./L=./O=./OU=./CN=kafka-server1
   i:/emailAddress=test@qq.com
 1 s:/emailAddress=test@qq.com
   i:/emailAddress=test@qq.com
---
Server certificate
-----BEGIN CERTIFICATE-----
... ...
```

I don't know what it means. Please help me.

**Comment by yangyangtiantianlonglong** [comment]
Which OpenSSL version do you use? 
` openssl version`
Use the command line to get more information
`openssl s_client -connect kafka-server1:9093 -tls1_2 -servername kafka-server1 -msg`

**Comment by yangyangtiantianlonglong** [comment]
I suggest you try openssl-1.1.1 or later, you're probably using 1.0.x.

**Comment by UniqueDavidQian** [comment]
> 

yes, my openssl version info is 'OpenSSL 1.0.2k-fips  26 Jan 2017', I will try new version later

**Comment by UniqueDavidQian** [comment]
> I suggest you try openssl-1.1.1 or later, you're probably using 1.0.x.

yes, my openssl version info is 'OpenSSL 1.0.2k-fips  26 Jan 2017'. I will try new version later.

**Comment by UniqueDavidQian** [comment]
> I suggest you try openssl-1.1.1 or later, you're probably using 1.0.x.

well,I try:
```
openssl s_client -connect kafka-server1:9093 -tls1_2 -servername kafka-server1 -msg
```

it shows:
```
CONNECTED(00000003)
>>> ??? [length 0005]
    16 03 01 00 d3
>>> TLS 1.2, Handshake [length 00d3], ClientHello
    ... ... some codes ... ...
<<< ??? [length 0005]
    00 00 00 00 00
140536276289344:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:332:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 216 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1641123091
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
and openssl version is :
```
OpenSSL 1.1.1m  14 Dec 2021
```

**Comment by kaduk** [comment]
```
>>> ??? [length 0005]
    16 03 01 00 d3
```
That's a TLS record header.  Type handshake(22, 0x16), version 0x0301, length 0xd3.
```
>>> TLS 1.2, Handshake [length 00d3], ClientHello
    ... ... some codes ... ...
```
That's the payload of the handshake record.
```
<<< ??? [length 0005]
    00 00 00 00 00
```
That's supposed to be the record header of the server's reply, but it's malformed (all zeros).  ContentType 0 is explicitly invalid, the protocol version 0x0000 is invalid, and the length is zero.

The server is not speaking any version of TLS.

**Comment by UniqueDavidQian** [comment]
> ```
> >>> ??? [length 0005]
>     16 03 01 00 d3
> ```
> 
> That's a TLS record header. Type handshake(22, 0x16), version 0x0301, length 0xd3.
> 
> ```
> >>> TLS 1.2, Handshake [length 00d3], ClientHello
>     ... ... some codes ... ...
> ```
> 
> That's the payload of the handshake record.
> 
> ```
> <<< ??? [length 0005]
>     00 00 00 00 00
> ```
> 
> That's supposed to be the record header of the server's reply, but it's malformed (all zeros). ContentType 0 is explicitly invalid, the protocol version 0x0000 is invalid, and the length is zero.
> 
> The server is not speaking any version of TLS.

Howevery, I checked kafka-server1 starting logs and it shows:
```
 ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = 
        ssl.engine.factory.class = null
        ssl.key.password = [hidden]
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.certificate.chain = null
        ssl.keystore.key = null
        ssl.keystore.location = /usr/local/kafka_2.13-3.0.0/ssl/server.keystore.jks
        ssl.keystore.password = [hidden]
        ssl.keystore.type = JKS
        ssl.principal.mapping.rules = DEFAULT
        ssl.protocol = TLSv1.2
```

I think I have set TLS version settings. Is there any other settings should be written?

**Comment by t8m** [comment]
> I think I have set TLS version settings. Are there any other settings should be written?

I'd recommend asking on Kafka issue tracker.

**Comment by UniqueDavidQian** [comment]
> > I think I have set TLS version settings. Are there any other settings should be written?
> 
> I'd recommend asking on Kafka issue tracker.

yes, sorry for my rudeness
