### ISSUE TITLE
error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:365

### ISSUE THREAD

**Issue by UniqueDavidQian** [openssl/openssl#17384]
I am configuring ssl for my kafka cluster. when I checked my configuration by this:

`openssl s_client -connect kafka-9092:9093 -tls1_2 -servername kafka-9092`

I got the error like this:

140365818021776:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:365:
no peer certificate available
No client certificate CA names sent
SSL handshake has read 5 bytes and written 7 bytes
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol : TLSv1.2
Cipher : 0000
Session-ID:
Session-ID-ctx:
Master-Key:
Key-Arg : None
Krb5 Principal: None
PSK identity: None
PSK identity hint: None
Start Time: 1640917883
Timeout : 7200 (sec)

Could somebody tell me how to fix? merci

**Comment by yangyangtiantianlonglong** [comment]
>140365818021776:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:365:
>SSL handshake has read 5 bytes and written 7 bytes

openssl s_client had read 5 bytes record header that can't paresed it. 
I guess Kafka is not configured with the correct TLS.

**Comment by UniqueDavidQian** [comment]
> > 140365818021776:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:365:
> > SSL handshake has read 5 bytes and written 7 bytes
> 
> openssl s_client had read 5 bytes record header that can't paresed it. I guess Kafka is not configured with the correct TLS.

follow your suggestion I add the config in server.properties of kafka and it works. Thanks bro.
`ssl.enabled.protocols=TLSv1.2`

**Comment by Ashwin0816** [comment]
FetchError: request to https://localhost:3000/api/getTweets failed, reason: write EPROTO 139701963396992:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
