### ISSUE TITLE
[master] The ocsp app at the command line doesn't return response text, the response outputs on the running ocsp responder, but not when testing it

### ISSUE THREAD

**Issue by Steven23456** [openssl/openssl#17387]
I built openssl using VC 2022, nasm following the posted directions for Windows (no issues)

At the command line I run the following
```
openssl ocsp -port 9080 -index ./CA/root-ca/db/index -rsigner ./CA/root-ca/ocsp.crt -rkey ./CA/root-ca/keys/ocsp.key -CA ./CA/root-ca/root-ca.crt -text -passin pass:password
```
that starts an instance of the responder

then I run in a second shell:
```
ocsp -issuer ./CA/root-ca/root-ca.crt -CAfile ./CA/root-ca/root-ca.crt -cert ./CA/root-ca/ocsp.crt -url http://localhost:9080
```
 I get no response text at all ... and even when I add the -text option .. I only get the request text .. not the response text.

when I do the exact same thing (less the -passin option) using the stable 1.1.1 branch .. I have no issues .. I get the response text back from the second command as expected.

**Comment by t8m** [comment]
@DDvO does it look like some regression from the HTTP client patches?

**Comment by DDvO** [comment]
> @DDvO does it look like some regression from the HTTP client patches?

Could well be, but without more detailed information I cannot reproduce this.

@Steven23456, could it be that the problem only occurs with Windows,
or can you reproduce it, e.g., in Linux, too?

It may also help of you provide the referenced test certs or invocations that refer only to test certs available within OpenSSL, e.g.,
```
touch /tmp/t
apps/openssl ocsp -port 9999 -index /tmp/t -rsigner test/certs/ca-cert.pem -rkey test/certs/ca-key.pem -CA test/certs/root-cert.pem -text
apps/openssl ocsp -issuer test/certs/ca-cert.pem -CAfile test/certs/root-cert.pem -cert test/certs/ee-cert.pem -url http://localhost:9999
```
With these parameters, I cannot reproduce the issue.

**Comment by Steven23456** [comment]
Perhaps it was a flaky build that I had, I cloned and built today and it seems to have been fixed. At least on my end; as for specifics 
`openssl ocsp -issuer CA/root-ca/root-ca.crt -CAfile CA/root-ca/root-ca.crt -cert CA/root-ca/ocsp.crt -url http://localhost:9080`

is giving me the proper response
```
Response verify OK
CA/root-ca/ocsp.crt: good
        This Update: Jan  7 21:08:07 2022 GMT
```
as for being able to re-produce it .. the path I took to build the certs form root to ocsp responder to test .. is verbatim what is in   Feisty Ducks OpenSSL Cookbook ... "Creating a Private Certificate Authority"

I don't have the experience (yet) to properly build it in Linux (I keep getting a library missing error)
