### ISSUE TITLE
coding style: Are intra-statement comments acceptable?

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#17381]
In a review https://github.com/openssl/openssl/pull/17310#discussion_r771865957 the question came up whether it is okay to use comments that (do no stretch over several lines but) are between the start and the end of a C statement.

A classical use case is, e.g.,
```
foo(a, b, NULL /* not relevant here */, d);
```
which is already in use at various places.
In the concrete situation of #17310, it is
```
info->use_proxy = /* workaround for callback design flaw, see #17088 */
    proxy_host != NULL;
```

This again touches the issue #10725 that the [official coding style guidelines](https://www.openssl.org/policies/codingstyle.html) have not been updated since long.

**Comment by levitte** [comment]
I see a huge difference between the two example.  Example one is a note about one specific argument, while example two is about the whole statement.  In example two, I find the intra-statement comment to make the flow harder to read.

**Comment by DDvO** [comment]
Can I conclude from your response that in general intro-statement comments are acceptable (as long as readability is not hampered)?

So example 1 is certainly fine, 
and in cases like example 2 it depends?

In #17310 I've just moved the comment above the statement to which https://github.com/openssl/openssl/pull/17310#discussion_r771865957 refers.

**Comment by levitte** [comment]
I only expressed my opinion.  Don't take it as gospel.  If there's a project decision to be made, that will probably have to wait a bit, as many of us are currently on vacation (myself included).

**Comment by t8m** [comment]
I do not think we need an explicit rule about this. This should be at the reviewer(s) discretion whether such comment is acceptable or not. As for the two examples above I agree with @levitte that 1 is clearly acceptable and 2 rather not.

**Comment by DDvO** [comment]
Thanks @levitte and @t8m for your responses.
So I take this question as answered, and no addition needed to #10725 .

**Comment by paulidale** [comment]
We use comments within expressions in the tests as part of `if !TEST_xxx` sequences.

**Comment by DDvO** [comment]
> We use comments within expressions in the tests as part of `if !TEST_xxx` sequences.

Yes, just found this in
```
test/bntest.c:            || !TEST_true(BN_div(ret, NULL /* rem */ , lshift1, two, ctx))
test/bntest.c:    if (!TEST_false(BN_rand(bn, 0, 0 /* top */ , 0 /* bottom */ ))
test/bntest.c:            || !TEST_false(BN_rand(bn, 0, 1 /* top */ , 1 /* bottom */ ))
test/bntest.c:            || !TEST_true(BN_rand(bn, 1, 0 /* top */ , 0 /* bottom */ ))
test/bntest.c:            || !TEST_false(BN_rand(bn, 1, 1 /* top */ , 0 /* bottom */ ))
test/bntest.c:            || !TEST_true(BN_rand(bn, 1, -1 /* top */ , 1 /* bottom */ ))
test/bntest.c:            || !TEST_true(BN_rand(bn, 2, 1 /* top */ , 0 /* bottom */ ))
```
