### ISSUE TITLE
Unclear if EVP_DigestInit and EVP_DigestUpdate can be pared with EVP_VerifyFinal

### ISSUE THREAD

**Issue by DemiMarie** [openssl/openssl#17390]
In OpenSSL 1.1.1, it is not clear if `EVP_DigestInit` and `EVP_DigestUpdate` can be used with `EVP_VerifyFinal`.

**Comment by levitte** [comment]
Is there anything suggesting that it *should* work?

**Comment by DemiMarie** [comment]
> Is there anything suggesting that it _should_ work?

Right now, `<openssl/evp.h>` contains:

```c
# define EVP_VerifyInit(a,b)              EVP_DigestInit(a,b)
```

So it is guaranteed to work today, both on 1.1.1 and 3.0.

**Comment by t8m** [comment]
It is guaranteed by implementation, not by documentation. IMO there is no point in overdocumenting this. We could only say - EVP_VerifyInit is currently an alias for EVP_DigestInit however it can be changed in future. Which is kind of obvious thing.

**Comment by DemiMarie** [comment]
> It is guaranteed by implementation, not by documentation. IMO there is no point in overdocumenting this. We could only say - EVP_VerifyInit is currently an alias for EVP_DigestInit however it can be changed in future. Which is kind of obvious thing.

At least RPM actually relies on this behavior, and an OpenPGP implementation I am writing in C++ does too.  One advantage is that it avoids having to calculate a hash twice in some situations, such as when verifying a SHA256 hash and a RSA-SHA256 signature.

**Comment by t8m** [comment]
**OTC decision: Should we explicitly document that EVP_VerifyFinal (and EVP_SignFinal) can be used after EVP_DigestInit and EVP_DigestUpdate?**

**Comment by mattcaswell** [comment]
OTC: We should not explicitly document the above. Application authors should not assume that these things are the same.
