### ISSUE TITLE
Build on Windows fails if cloned with git

### ISSUE THREAD

**Issue by ENikS** [openssl/openssl#174]
There is a repeatable problem with building of openssl cloned with GIT on Windows. 
 When source comes from official distribution all line endings are preserved and remain normal unix style endings. But when git clones repository it may convert these into windows style endings.
MinGW comes bundled with pretty outdated Perl (5.8.8 if memory serves...) which could get confused by these different styles and produce unexpected behavior.  This is what happening during execution of Configure script. When ignored ciphers are determined this code is executed:
```
    if ($sdirs) {
        my $dir;
		foreach $dir (@skip) {
			s/(\s)$dir /$1/;
			s/\s$dir$//;
			}
		}
	$sdirs = 0 unless /\\$/;
```
In code **$sdirs = 0 unless /\\$/;** under normal circumstances pattern **/\\$/** returns **1** if it is still processing these directories but if line ending is not normal unix style it will return **nothing** and allow **$sdirs = 0**. So only the first line of **SDIRS= \** gets processed and the rest ... objects \ md2 md4 md5 sha mdc2 hmac ripemd whrlpool \ …  is skipped.

Result of this error is a Makefile which is trying to process ALL ciphers disregarding **no-cipher** attributes and will produce this error:
```
gcc -I.. -I../.. -I../asn1 -I../evp -I../../include  -DOPENSSL_THREADS 
-DDSO_WIN32 -mno-cygwin -DL_ENDIAN -DOPENSSL_NO_CAPIENG 
-fomit-frame-pointer -O3 -march=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS 
-DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM 
-DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DWHIRLPOOL_ASM   -c -o 
md2_dgst.o md2_dgst.c 
In file included from md2_dgst.c:62: 
../../include/openssl/md2.h:64:2: #error MD2 is disabled. 
make[2]: *** [md2_dgst.o] Error 1 
make[2]: Leaving directory 
```

Unfortunately I am not that good with Perl and could not provide constructive solution for the problem. The best would be to fix Perl itself but I do not think that will fly. So the next best thing would be the different means of checking if end of the list is reached.

**Comment by turboj** [comment]
Found a workaround (disable crlf for openssl repository):
`git config core.autocrlf false`
`git rm --cached -r .`
`git reset --hard`

Now all files are without crlf line endings.

**Comment by ENikS** [comment]
This is a global setting. It would break other projects on the PC.
 
This method would work if used on each repository individually as described here:
https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings

It is still half baked solution requiring user to search for an answer once issue has been encountered.

**Comment by mattcaswell** [comment]
I have a per-repository setting on my Windows system which seems to work fine. From the checked out openssl repo:

git config --local core.autocrlf false
git config --local core.eol lf

You probably need to refresh your files after doing that (make sure you
don't have any local uncommitted changes before doing this):

git rm --cached -r .
git reset --hard

I also have my windows text editor (notepad++) set to only use lf not crlf.

**Comment by ENikS** [comment]
I've decided to reopen this issue. 
It is well-known fact that only ActivePerl could be used on Windows to build openssl because of this bug. Adding this line: $/= "\r\n"; to Perl script makes it compatible with any other implementation.
I've successfully built openssl with Perl distributed with Git as well as Strawberry Perl.

**Comment by Speakus** [comment]
I got this issue (It was solved with install new Perl) But could I know: where exactly you could put the line `"$/= "\r\n";` ?
I tried to put this line to top of file `Configure` but i got error:

> Backslash found where operator expected at Configure line 1, near ""$/= "\" (Missing operator before \?) Backslash found where operator expected at Configure line 1, near "r\"

Pull request related with this issue could be helpful to understand.

Thanx.

**Comment by ENikS** [comment]
I've added it as a first line of the script. Unfortunately it is implementation specific and installing latest interpreter is the best option.

**Comment by Speakus** [comment]
Thanx for reply. Which script did you update? My msys also has 5.8.8 perl installed. So I just tried to understand what I did wrong. Although installing ActivePerl works like charm :)

**Comment by ENikS** [comment]
ActivePerl seems to be the only solution.

**Comment by levitte** [comment]
From `NOTES.PERL`:

> Notes on Perl on Windows
> ------------------------

> There are a number of build targets that can be viewed as "Windows".
> Indeed, there are VC-* configs targeting VisualStudio C, as well as
> MinGW and Cygwin. **The key recommendation is to use "matching" Perl,
> one that matches build environment**. For example, if you will build
> on Cygwin be sure to use the Cygwin package manager to install Perl.
> For MSYS builds use the MSYS provided Perl. For VC-* builds we
> recommend ActiveState Perl, available from
> http://www.activestate.com/ActivePerl.

Note the emphasised part.

**Comment by arkceajin** [comment]
> From `NOTES.PERL`:
> 
> > ## Notes on Perl on Windows
> > There are a number of build targets that can be viewed as "Windows".
> > Indeed, there are VC-* configs targeting VisualStudio C, as well as
> > MinGW and Cygwin. **The key recommendation is to use "matching" Perl,
> > one that matches build environment**. For example, if you will build
> > on Cygwin be sure to use the Cygwin package manager to install Perl.
> > For MSYS builds use the MSYS provided Perl. For VC-* builds we
> > recommend ActiveState Perl, available from
> > http://www.activestate.com/ActivePerl.
> 
> Note the emphasised part.

MSYS provide perl v5.8.8 but openssl require v5.10

**Comment by levitte** [comment]
I think MSYS2 is the new MSYS...

**Comment by mspncp** [comment]
> I think MSYS2 is the new MSYS...

I also noticed the missing '2' recently. In some locations, I see "MSYS[2]" mentioned. Should we maybe add a general note in the INSTALL instructions about preferring MSYS2 over MSYS, and replace all mentions uniformly by "MSYS2"?


```make
$ git grep -E  -i -n 'msys[^2]'
CHANGES:6737:     from a Windows bash shell such as MSYS. It is autodetected from the
NOTES.PERL:38: For MSYS builds use the MSYS provided Perl. For VC-* builds we
NOTES.WIN:8: compiler) and mingw[64]. "Hosted" platforms are Cygwin and MSYS[2]. Even
NOTES.WIN:12: and require --cross-compile-prefix option. While on MSYS[2] it's solved
test/recipes/02-test_errstr.t:35:# on Windows when built with msys perl.  Similar problems are also observed
test/recipes/02-test_errstr.t:37:plan skip_all => 'This is unsupported on MSYS/MinGW or MSWin32'
test/recipes/02-test_errstr.t:38:    if $^O eq 'msys' or $^O eq 'MSWin32';
```

**Comment by levitte** [comment]
Possibly.

I'm actually a bit surprised that there's no newer perl available with the older MSYS.  Is it actually *so old* that there isn't an upgrade package for things like perl?  After all, perl 5.8.8 is from 2006...

**Comment by mattcaswell** [comment]
> I also noticed the missing '2' recently. In some locations, I see "MSYS[2]" mentioned. Should we maybe add a general note in the INSTALL instructions about preferring MSYS2 over MSYS, and replace all mentions uniformly by "MSYS2"?

Yes, I think we should. I don't think MSYS is being maintained any more. At least the perl version certainly isn't.
