### ISSUE TITLE
Loading 3.0.0 FIPS provider in 3.x.x

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#17402]
It's my current understanding that one of the desired properties of the 3.0.0 FIPS provider is that it can be loaded even with future versions of OpenSSL. Is there any documentation about when the OpenSSL project may choose to do a compatibility break? e.g. 3.0.x will work, but 3.1.x will require a new module, or something like that.

Additionally, it seems like the current CI system doesn't have testing for this scenario -- should it be added to ensure that this behavior is preserved?

**Comment by paulidale** [comment]
Our [stability policy](https://github.com/openssl/technical-policies/blob/master/policies/stable-release-updates.md)  indicates 4.0 as the earliest breaking version.

**Comment by t8m** [comment]
I would add that the 3.0 FIPS provider might not be able to support all new features introduced in later 3.x releases. It should work for all functionality that was already there in the 3.0 release though.

**Comment by reaperhulk** [comment]
Great on the documentation! Is there any intent to add CI jobs that validate forward compatibility for this?

**Comment by paulidale** [comment]
Yes, we should add CI jobs.  Until the validation is complete, we don't have an official FIPS provider to test against.

**Comment by reaperhulk** [comment]
Would you like me to leave this open for now for that or is that in plan and I can just close it?

**Comment by paulidale** [comment]
A separate feature issue would be best I think.

**Comment by reaperhulk** [comment]
Done, #17430. Closing this one.
