### ISSUE TITLE
Openssl 1.1.1-dev Not linking its own libraries correctly

### ISSUE THREAD

**Issue by kn1ght0wl** [openssl/openssl#1740]
After compiling and installing Openssl on 'Oracle Linux Server release 7.2 (4.1.12-37.5.1.el7uek.x86_64)' using gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4):

$ ./config \
--prefix=/opt/openssl/1.1.1-dev \
--openssldir=/opt/ssl
$ make
$ make test
$ sudo make install

$ /opt/openssl/1.1.1-dev/bin/openssl help
/opt/openssl/1.1.1-dev/bin/openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

$ ldd /opt/openssl/1.1.1-dev/bin/openssl
        linux-vdso.so.1 =>  (0x00007ffff80da000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2bf83ca000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2bf81ae000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2bf7dee000)
        /lib64/ld-linux-x86-64.so.2 (0x000055e0dc109000)

$ export LD_LIBRARY_PATH=/opt/openssl/1.1.1-dev/lib

$ ldd /opt/openssl/1.1.1-dev/bin/openssl
        linux-vdso.so.1 =>  (0x00007ffea97ba000)
        libssl.so.1.1 => /opt/openssl/1.1.1-dev/lib/libssl.so.1.1 (0x00007f606ffd6000)
        libcrypto.so.1.1 => /opt/openssl/1.1.1-dev/lib/libcrypto.so.1.1 (0x00007f606fb53000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f606f945000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f606f729000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f606f369000)
        /lib64/ld-linux-x86-64.so.2 (0x00005581c8aa2000)

**Comment by kn1ght0wl** [comment]
I did see two warning during the compilation process, though I assume they are unrelated:

make[2]: Entering directory `/local/src/openssl-1.1.1-dev'
LD_LIBRARY_PATH=.:/oracle/nfs/client/linux/product/9.2.0/lib gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="/opt/openssl/1.1.1" -DENGINESDIR="/opt/openssl/1.1.1/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -fPIC -m64 -shared -Wl,-Bsymbolic -Wl,-soname=libssl.so.1.1 -o ./libssl.so.1.1 -Wl,--whole-archive,--version-script=ssl.map ./libssl.a -Wl,--no-whole-archive -L. -lcrypto -ldl
make[2]: Leaving directory `/local/src/openssl-1.1.1-dev'
gcc  -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/opt/openssl/1.1.1\"" -DENGINESDIR="\"/opt/openssl/1.1.1/lib/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack -fPIC -MMD -MF engines/afalg/e_afalg.d.tmp -MT engines/afalg/e_afalg.o -c -o engines/afalg/e_afalg.o engines/afalg/e_afalg.c
**engines/afalg/e_afalg.c:29:3: warning: #warning "AFALG ENGINE requires Kernel Headers >= 4.1.0" [-Wcpp]**
 # warning "AFALG ENGINE requires Kernel Headers >= 4.1.0"
   ^
**engines/afalg/e_afalg.c:30:3: warning: #warning "Skipping Compilation of AFALG engine" [-Wcpp]**
 # warning "Skipping Compilation of AFALG engine"
   ^

Output from config was:
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default] 
    no-zlib-dynamic [default] 
Configuring for linux-x86_64

PERL          =/usr/bin/perl
PERLVERSION   =5.16.3 for x86_64-linux-thread-multi
HASHBANGPERL  =/usr/bin/env perl
CC            =gcc
CFLAG         =-Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack
CXX           =g++
CXXFLAG       =-Wall -O3 -pthread -m64 -DL_ENDIAN 
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_STATIC_ENGINE OPENSSL_PIC OPENSSL_IA32_SSE2 OPENSSL_BN_ASM_MONT OPENSSL_BN_ASM_MONT5 OPENSSL_BN_ASM_GF2m SHA1_ASM SHA256_ASM SHA512_ASM RC4_ASM MD5_ASM AES_ASM VPAES_ASM BSAES_ASM GHASH_ASM ECP_NISTZ256_ASM POLY1305_ASM
EX_LIBS       =-ldl

**Comment by levitte** [comment]
Those warnings are unrelated, yes.

However, the automatic addition of RPATH components have recently been removed from OpenSSL.  If you want them, add this to your configuration options: `-Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'`  Another option is to add /opt/openssl/1.1.1-dev/lib to your `/etc/ld.so.conf`

The reason we removed the automatic RPATH addition was that it got in the way, and that we now install in standard directories by default.

**Comment by kn1ght0wl** [comment]
Config options fixed my issue!  Did not want to go the route of updating my ld.so.conf as I need to keep the RH version intact.  Though, since RH are using alternate library names for SSL I guess it would not have mattered...   In any case, Thank you very much!

**Comment by georg-x** [comment]
The same issue got introduced with the switch from openssl 1.1.0b to 1.1.0c, compiled with default options:

$ openssl-1.1.0b/apps/openssl version
OpenSSL 1.1.0b  26 Sep 2016
$ ldd openssl-1.1.0b/apps/openssl
        linux-vdso.so.1 =>  (0x00007ffc7197f000)
        libssl.so.1.1 => /usr/local/lib64/libssl.so.1.1 (0x00007fd918483000)
        libcrypto.so.1.1 => /usr/local/lib64/libcrypto.so.1.1 (0x00007fd91801d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003853c00000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003854000000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003853800000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003853400000)

$ openssl-1.1.0c/apps/openssl
openssl-1.1.0c/apps/openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
$ ldd openssl-1.1.0c/apps/openssl
        linux-vdso.so.1 =>  (0x00007fff285bb000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003853c00000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003854000000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003853800000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003853400000)

**Comment by levitte** [comment]
@georg-x, see [this comment](https://github.com/openssl/openssl/issues/1740#issuecomment-254606676)

**Comment by georg-x** [comment]
@levitte I've already tried to add that to my Makefile. Even though the behaviour didn't change.
I'll retry and update if I find out what went wrong.

**Comment by levitte** [comment]
@georg-x, what was your exact configuration command?

**Comment by georg-x** [comment]
@levitte very simple:
./config && make
I tried to build via the Makefile from 1.1.0b... but the output stays the same.
Or I might simply screw something up about where to exactly adding "-Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'" t o the compiler?

**Comment by levitte** [comment]
@georg-x, try to configure like this and see if that makes your life easier:

```
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
```

**Comment by dertin** [comment]
1- Install OpenSSL 1.1.0f in Debian 8.8:
 ```
  ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  make
  make test
  make install
  openssl version -v
```

2- Problems to install curl `./configure --with-nghttp2 --with-ssl`

> checking for OpenSSL headers version... 1.1.0 - 0x1010006fL
> checking for OpenSSL library version... 1.0.1
> checking for OpenSSL headers and library versions matching... no
> configure: WARNING: OpenSSL headers and library versions do not match.
> ...
> ...
> ...
> ...
> vtls/openssl.c: In function ‘Curl_ossl_seed’:
> vtls/openssl.c:279:5: error: implicit declaration of function ‘RAND_egd’ [-Werro r=implicit-function-declaration]
> int ret = RAND_egd(data->set.str[STRING_SSL_EGDSOCKET]?
> ^
> cc1: some warnings being treated as errors
> Makefile:2030: recipe for target 'vtls/libcurl_la-openssl.lo' failed
> make[2]: *** [vtls/libcurl_la-openssl.lo] Error 1
> make[2]: Leaving directory '/var/tmp/curl_build/curl_src/lib'
> Makefile:741: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/var/tmp/curl_build/curl_src/lib'
> Makefile:902: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1
> Making install in lib
> make[1]: Entering directory '/var/tmp/curl_build/curl_src/lib'
> CC vtls/libcurl_la-openssl.lo
> vtls/openssl.c: In function ‘Curl_ossl_seed’:
> vtls/openssl.c:279:5: error: implicit declaration of function ‘RAND_egd’ [-Werro r=implicit-function-declaration]
> int ret = RAND_egd(data->set.str[STRING_SSL_EGDSOCKET]?
> ^
> cc1: some warnings being treated as errors
> Makefile:2030: recipe for target 'vtls/libcurl_la-openssl.lo' failed
> make[1]: *** [vtls/libcurl_la-openssl.lo] Error 1
> make[1]: Leaving directory '/var/tmp/curl_build/curl_src/lib'
> Makefile:902: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1

**Comment by levitte** [comment]
@dertin, I would suggest you have something odd in your environment that the curl config is picking up.  This is a clear indication:

```
checking for OpenSSL headers version... 1.1.0 - 0x1010006fL
checking for OpenSSL library version... 1.0.1
checking for OpenSSL headers and library versions matching... no
```

Have a look at `/var/tmp/curl_build/curl_src/config.log`, you might find a hint there.  Have a look around in `/usr/local` to verify for yourself if the OpenSSL libraries and include files are in place.  In particular, you might want to check that `/usr/local/include/openssl/opensslv.h` has the version number you expect.

**Comment by dertin** [comment]
@levitte Thank you.

I forgot to comment that I am using Debian 8.8 x32bit

I'm going to Rebuild Droplet

I must compile OpenSSL with some other parameter, possibly indicating some library path.
I am not sure if it is necessary to add the parameter "no-shared or shared" 
or indicate something by 32-bit architecture

`./config shared --prefix=/usr/local --openssldir=/usr/local/ssl -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'`


I should also compile CURL indicating the same path as the OpenSSL library.
`./configure --with-ssl=/usr/local/ssl`

**Maybe this bug is affecting me:**
https://github.com/curl/curl/issues/719

Log files:
[opensslv.h](https://github.com/openssl/openssl/files/1082643/opensslv.h.txt)
[config.log](https://github.com/openssl/openssl/files/1082660/config.log.txt)

in config.log see:
> configure:23234: Added /usr/local/lib to LD_LIBRARY_PATH
> configure:23244: checking for OpenSSL headers version
> configure:23274: gcc -E   -I/usr/local/include   conftest.c
> configure:23274: $? = 0
> configure:23335: result: 1.1.0 - 0x1010006fL
> configure:23344: **checking for OpenSSL library version**
> configure:23412: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers   -I/usr/local/include   -L/usr/lib/i386-linux-gnu  -L/usr/local/lib  conftest.c -lssl -lcrypto -lssl -lcrypto  -llber -lldap -lz  >&5
> /tmp/cconm5OL.o: In function `main':
> conftest.c:(.text.startup+0x12): undefined reference to `SSL_CTX_set_not_resumable_session_callback'
> collect2: error: ld returned 1 exit status
> configure:23412: $? = 1
> configure: failed program was:

**Comment by levitte** [comment]
> @levitte Thank you.
> 
> I forgot to comment that I am using Debian 8.8 x32bit

Ok.  That shoudn't make a difference

> I'm going to Rebuild Droplet
> 
> I must compile OpenSSL with some other parameter, possibly indicating some library path.
> I am not sure if it is necessary to add the parameter "no-shared or shared" 
> or indicate something by 32-bit architecture
> 
> `./config shared --prefix=/usr/local --openssldir=/usr/local/ssl -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'`

With OpenSSL 1.1.0 and on, those are the default values for `--prefix` and `--openssldir`

> I should also compile CURL indicating the same path as the OpenSSL library.
> `./configure --with-ssl=/usr/local/ssl`

This is wrong, it should be `--with-ssl=/usr/local`...  however, that's the default when you just sa y `--with-ssl`.

> **Maybe this bug is affecting me:**
> https://github.com/curl/curl/issues/719

Possibly.  I can't judge that.

> in config.log see:
> > configure:23234: Added /usr/local/lib to LD_LIBRARY_PATH
> > configure:23244: **checking for OpenSSL headers version**
> > configure:23274: gcc -E   -I/usr/local/include   conftest.c
> > configure:23274: $? = 0
> > configure:23335: result: 1.1.0 - 0x1010006fL :thumbsup:
> > configure:23344: **checking for OpenSSL library version**
> > configure:23412: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers   -I/usr/local/include   -L/usr/lib/i386-linux-gnu  -L/usr/local/lib  conftest.c -lssl -lcrypto -lssl -lcrypto  -llber -lldap -lz  >&5

Ok, so this part is actually interesting!  Did you notice that you get `/usr/local/include` only for header files?  That means that yes, it will get the headers that you installed.  **However**, for libraries you're getting both `/usr/lib/i386-linux-gnu` *and* `/usr/local/lib`, in that order.  I'm going to venture a guess that if you look in `/usr/lib/i386-linux-gnu`, you will find `libcrypto.so.1.0.1`, or similar.  That will, of course, not match the headers found in `/usr/local/include`, but that's what the curl configuration is picking up.

How you ended up in that situation?  My guess is that you have the debian package `libssl1.0.1` installed.  That's only installing the shared libraries...  no corresponding header files.

This does look like a `configure` issue with curl, the ordering of `-L` arguments above creates problems.  I suggest you take it up with them.

**Comment by dertin** [comment]
@levitte Thanks for the help
I will investigate and ask the CURL team for help.
If I make it work, I'll let you know how.

Greetings.

**Comment by vikingjs** [comment]
I am having the same problem, and I do not see the disagreement between header and library versions.

However, I do see this when I run ./configure for OpenSSL:

>  Configuring OpenSSL version 1.1.0f (0x1010006fL)
>    . . .
>     no-egd          [default]  OPENSSL_NO_EGD
> 

and in openssl/rand.h I see:

> # ifndef OPENSSL_NO_EGD
> int RAND_query_egd_bytes(const char *path, unsigned char *buf, int bytes);
> int RAND_egd(const char *path);
> int RAND_egd_bytes(const char *path, int bytes);
> # endif

Which makes me think that RAND_egd() is not defined on my configuration intentionally. I don't see a configuration option that gives me control of that, but I'll keep looking. I'm certainly not an expert at this stuff, but I think curl's openssl code needs to recognize that RAND_egd() may not be exist.

**Comment by vikingjs** [comment]
A little more:

https://github.com/openssl/openssl/commit/0423f812dc61f70c6ae6643191259ca9e5692c7f

**Comment by atulyakr** [comment]
> 

how do i run all these commands on ubuntu? I mean the above commands just don't work on ubuntu
