### ISSUE TITLE
OpenSSL 3.0 in FIPS mode failed on PKCS12_set_mac

### ISSUE THREAD

**Issue by wxt** [openssl/openssl#17420]
Setup:
- OpenSSL 3.0 
- Windows x64 release build

With OpenSSL 3.0 and FIPS enabled, I am not sure why I am getting the following error message when calling PKCS12_set_mac():
```
error:0308010C:digital envelope routines::unsupported
```

- FIPS config and provider are loaded programmatically without any error.  
- No error when calling PKCS12_create() with NID_aes_256_cbc for both nid_key and nid_cert and I see the above error when using legacy algorithms in FIPS mode.  However, I am seeing the above error message when calling PKCS12_set_mac(p12, <pass_phrase>, -1, NULL, 0, PKCS12_DEFAULT_ITER, NULL); where p12 is from PKCS12_create and pass_phrase is also being used in PKCS12_create.  
- PKCS12_set_mac() call is successful in non-FIPS mode

When stepping through PKCS12_set_mac(), the furthest breakpoint that it hits in my local build is crypto\evp\evp_fetch.c::evp_generic_fetch() with the following call stack:
```
libcrypto-3-x64.dll!PKCS12_key_gen_utf8_ex() Line 61
libcrypto-3-x64.dll!pkcs12_key_gen_mac() Line 143
libcrypto-3-x64.dll!PKCS12_set_mac() Line 219
...
```
Am I using PKCS12_set_mac() correctly? Is there something else I am missing?

**Comment by t8m** [comment]
Unfortunately the PKCS12 MAC uses non-FIPS password based key derivation. That means it cannot be used with FIPS provider only. Either you have to skip adding MAC to the PKCS12 file or temporarily allow using the default provider.

**Comment by wxt** [comment]
Thanks @t8m I'll checkout the suggested approach.
