### ISSUE TITLE
Add CI validating the FIPS 3.0.0 provider loads in 3.x.x

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#17430]
Just a tracking issue to add this to CI as requested in #17402

**Comment by slontis** [comment]
@t8m is this addressed by https://github.com/openssl/openssl/pull/17671

**Comment by t8m** [comment]
Yes, IMO this should be sufficiently handled by #17671. Closing.

**Comment by slontis** [comment]
thanks..

**Comment by reaperhulk** [comment]
Thanks folks, this is great 😄
