### ISSUE TITLE
Meaningless for loop, can we remove them?

### ISSUE THREAD

**Issue by DK-DARKmatter** [openssl/openssl#17436]
https://github.com/openssl/openssl/blob/1b87116a0c43b8b4e1ad88b851d5bcf27c1a5f64/crypto/ec/curve25519.c#L1736
https://github.com/openssl/openssl/blob/1b87116a0c43b8b4e1ad88b851d5bcf27c1a5f64/crypto/ec/curve25519.c#L1779

When I learn about curve25519 I found these two for loops that might be unnecessary. They can be simply removed and does not change the logic of the code. Do I miss something about the code here?

**Comment by t8m** [comment]
I suppose they are there to make the code "self-explanatory" to match the "math". Any at least somewhat reasonable compiler should be able to eliminate them by itself. So I do not see the need to remove the loops.

**Comment by DK-DARKmatter** [comment]
Sounds reasonable to me. Thanks for the reply.
