### ISSUE TITLE
I need help with building things in some specific environment

### ISSUE THREAD

**Issue by sudeshna90** [openssl/openssl#17432]
I am having Linux zld02866 2.6.32-754.41.2.el6.x86_64 #1 SMP Sat Jul 10 04:20:37 EDT 2021 x86_64 x86_64 i386-64 GNU/Linux mechine    Linux mechine where all codes are compiling in 32 bit mode

I have installed openssl OpenSSL 1.1.1g  by compiling it manually as following
setarch i386 ./config --prefix=/opt/nc3/openssl --openssldir=/opt/nc3/openssl -m32

compilation , make make test all went fine 

and if I can see this with which
/opt/nc3/openssl/bin/openssl

now I have written a simple client server code and compiling it through progect specific nmake command
I can see all my lib is in proper place 
echo $LD_LIBRARARY_PATH is giving the exact output but at the time of compilation 
getting following error 
+++ CLVAR: action=install
+++ OPTNS: --jobs=18 --clobber='*' --nocompare
+ /opt/app/nc3/sfw/SolarisStudio12.4-linux-x86-bin/solarisstudio12.4/bin/CC '-library=stlport4' '-features=extensions' -fast -m32 '-xarch=sse2' -xprefetch -g -O '-xcheck=%all' '-fsimple=0' -fPIC -fpic '-features=extensions' -fast -m32 '-xarch=sse2' -xprefetch -g '-xcheck=%all' -lpthread '-fsimple=0' -L/build/prodag2/lib -L/opt/app/nc3/sfw/oracle/product/11.2.0.4/lib -L/opt/app/nc3/sfw/curl-7/lib -Wl,-z,origin '-Wl,-R,$ORIGIN/../lib' -o ssl_tls_encryption ssl_v2_client.o -lclntsh -lnsl -lrt -ldemangle -lioc -lcommon -ldatastore -lnc3dsfun -lnc3func -lnc3logfl -lnc3morph -lnc3ocos -lnc3pcktr -lnc3pcmpr -lnc3pconf -lnc3pepos -lnc3peqpr -lnc3pext -lnc3pisdn -lnc3pmisc -lnc3pmscc -lnc3pmult -lnc3po -lnc3pprc -lnc3ptrad -lnc3puser -lnc3pvv -lnc3subjn -lnc3sys -ldmun -ldmugen -lcurl
ssl_v2_client.o: In function `InitCTX':
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:49: undefined reference to `OPENSSL_init_crypto'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:50: undefined reference to `OPENSSL_init_ssl'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:51: undefined reference to `TLSv1_2_client_method'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:52: undefined reference to `SSL_CTX_new'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:55: undefined reference to `ERR_print_errors_fp'
ssl_v2_client.o: In function `ShowCerts':
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:65: undefined reference to `SSL_get_peer_certificate'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:69: undefined reference to `X509_get_subject_name'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:69: undefined reference to `X509_NAME_oneline'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:72: undefined reference to `X509_get_issuer_name'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:72: undefined reference to `X509_NAME_oneline'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:75: undefined reference to `X509_free'
ssl_v2_client.o: In function `main':
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:95: undefined reference to `OPENSSL_init_ssl'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:102: undefined reference to `SSL_new'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:103: undefined reference to `SSL_set_fd'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:104: undefined reference to `SSL_connect'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:109: undefined reference to `SSL_get_current_cipher'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:109: undefined reference to `SSL_CIPHER_get_name'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:111: undefined reference to `SSL_write'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:112: undefined reference to `SSL_read'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:115: undefined reference to `SSL_free'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:118: undefined reference to `SSL_CTX_free'
/opt/app/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption//ssl_v2_client.cpp:105: undefined reference to `ERR_print_errors_fp'
make: *** exit code 2 making ssl_tls_encryption
+++ FINISH: nmake in directory /opt/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption
+++ TIME: Thu Jan 6 02:27:44 EST 2022
make: *** exit code 1 making build
+++ FINISH: nmake in directory /opt/nc3/sr9166/nov21/src/apixml/ssl_tls_encryption
+++ TIME: Thu Jan 6 02:27:44 EST 2022

can any one please help me out why these libs are not linking but I have mentioned the path in make file as well

Thanks in advanced

**Comment by t8m** [comment]
On the link command above I do not see `-lcrypto` and `-lssl`. That needs to be there if you want to link against libcrypto and libssl.

**Comment by sudeshna90** [comment]
hi , thanks for reply,
here is my make if I  mentioned like this

include "$(VROOT)/global.mk"

.SOURCE.so : $(VROOT)/lib

.all : build

:INSTALL: .all

build clean : .FORCE .VIRTUAL
        export MY_INCLUDES="/opt/app/nc3/openssl/include"
        export MY_LIBS="-lcrypto -lssl"

        gen_mk `basename $PWD` > Makefile_gen
        if [ "$(>)" ]
    then
        nmake -F -f Makefile_gen $(-) $(=) $(action)
    else
        nmake -f Makefile_gen $(-) $(=) $(action)
    fi
~
**getting error**
make: don't know how to make .INSTALL : .ALL : ssl_tls_encryption : -lcrypto


but I  have already export LD_LIBRARY_PATH

**Comment by t8m** [comment]
LD_LIBRARY_PATH is an environment variable that affects the ld.so dynamic library loader, not something that is consulted during the build process.

Your questions are really nothing that is OpenSSL specific and they are quite basic. I do not think the OpenSSL issue tracker is the right place.
