### ISSUE TITLE
Exit code not set to nonzero for all dhparam -check errors

### ISSUE THREAD

**Issue by maroonbells** [openssl/openssl#17449]

**Comment by maroonbells** [comment]
Because OpenSSL set an errorlevel for an invalid key, I assumed that the lack of an errorlevel indicated the key was OK. But this is not the case.

I was using a batch file to validate some DH moduli.pem files where the batch file was using "openssl dhparam -noout -check -in filename" until it encountered a file where the errorlevel is set.

 I happened to click over to the automated task at a time when I noticed there was an "access denied" error displayed, and I could tell from the short time duration spent against that filename that no validation had been attempted. However, the errorlevel was not set, so the batch file was treating this as if the modulus had been validated as a safe prime.

While it might be bad to report an errorlevel for parameters that are not bad, it can be worse to allow potentially bad parameters to escape detection simply because openssl couldn't access the file at that time, for whatever reason.

I'm not able to test this, but based on what I described, I see the potential for an adversary to park a dhparams.pem on a network drive without giving read access to your openssl, allowing them to trick someone into accepting a composite DH modulus due to the lack of an errorlevel.

It seems reasonable that the only reason for errorlevel 0 should be the command being a success.

I don't know if this issue affects other sub-sections of openssl.

**Comment by mattcaswell** [comment]
I'm not actually sure what you mean by an "errorlevel" in this context. Can you explain further?

**Comment by bernd-edlinger** [comment]
I think he means something like that
```
$ cat test.pem 
-----BEGIN DH PARAMETERS-----
MEYCQQCtBvU8cgIOwhefRF2+d5ebIYLMHsHiY4+FAf/GURZ2EnCvstPCmy3vdA49
unoBCgTDW6TgQ1k7CdlvsrlJ8vcbAgEC
-----END DH PARAMETERS-----
$ ./openssl dhparam -noout -check -in test.pem
WARNING: p value is not prime
$ echo $?
0
```
I changed the first character in the second line of this dhparam file by hand.
originally it was `OnoBCgTDW6TgQ1k7CdlvsrlJ8vcbAgEC`

**Comment by bernd-edlinger** [comment]
Yes, $? and errorlevel have a similar meaning, just different O/S.

FYI, the test above was done with openssl 1.1.1m, with openssl built from latest master revision,
I get a slightly different result:
```
$ ./openssl dhparam -noout -check -in test.pem 
Error, invalid parameters generated
40870D85DE7F0000:error:02800075:Diffie-Hellman routines:(unknown function):check p not prime:crypto/dh/dh_check.c:129:
$ echo $?
1
```
So the "error level" is 1, when the parameter check fails.
And the error message is a bit hard to read, because the hint what went wrong (p not prime)
is a bit hard to decipher, because that is embedded between lots of useless information.

Note that I cannot see how an access permission error on read of the pem file can result in missing error return,
neither with 1.1.1 nor with master version.
Which openssl version did you use?

**Comment by maroonbells** [comment]
I was using v3.0 binary downloaded from overbyte.
I hadn't set permissions to deny it, so I don't know why the error happened. I dumped a bunch of pem's into a folder at set the batch file to checking them, so i was surprised to check on the processing later to find one taking way too little time to process and showing the "access denied" error. I waited a few seconds, and i saw another one showing it too. I don't know what would be causing the error, but I would have expected openssl to quit with a non-zero errorlevel

**Comment by paulidale** [comment]
> It is not quite clear whether this would be a bug or feature.

[It's a bug](https://www.youtube.com/watch?v=4F4qzPbcFiA).

It might also be behaviour that is assumed by scripts.

**Comment by t8m** [comment]
So this was already changed in 3.0 to return non-zero exit code. I do not think we want to change the behavior in 1.1.1.

**Comment by maroonbells** [comment]
Sorry, I don't understand the closure comment. Does this mean my issue had already been fixed in an update newer than the 3.0 binary I was using?

**Comment by t8m** [comment]
> Sorry, I don't understand the closure comment. Does this mean my issue had already been fixed in an update newer than the 3.0 binary I was using?

Now, I am really confused what is your issue. Could you please paste here the params that trigger the failure that still returns zero exit code with 3.0?

With 1.1.1 version the check for parameters validity did not return non-zero exit code for invalid params. With 3.0 the command is supposed to return non-zero exit code and I cannot reproduce it returning zero.

**Comment by t8m** [comment]
Also I cannot reproduce any issue with exit code after permissions do not allow reading the file:
```
$ openssl  dhparam -noout -check -in test.pem
Can't open "test.pem" for reading, Permission denied
C022F13A577F0000:error:8000000D:system library:BIO_new_file:Permission denied:../openssl3/crypto/bio/bss_file.c:67:calling fopen(test.pem, r)
C022F13A577F0000:error:10080002:BIO routines:BIO_new_file:system lib:../openssl3/crypto/bio/bss_file.c:77:
$ echo $?
1
```

**Comment by t8m** [comment]
I tried both with the latest commit from the openssl-3.0 branch and with openssl-3.0.0 and both worked fine.

**Comment by maroonbells** [comment]
The situation I encountered was not the same as when UAC controls are changed to deny read permissions to the file. When I do that, it shows 3 lines of cryptic error messages preceded by a message stating that it couldn't open the pem for reading, permission denied, and it does set errorlevel to 1.

What I encountered several days ago had no such error message displayed. I was using using a batch file to check all the DH pem's in a subfolder. After a while, I looked at the console window and could see that it was spending several seconds looking at each file and then displaying "DH parameters appear to be ok", then moves on to the next pem. However I saw a few times that the only text showing was "access denied", and it moved to the next file immediately without any delay and without showing either the 'ok' or the 'error' message, and there was no non-zero errorlevel set.

I had not altered any UAC settings on the file or the folder, so I don't even know why it was showing the access-denied warning. I just know that multiple pem's were not validated while I was watching the console window, and probably for unknown additional pem's while I wasn't watching, and there was no errorlevel being set.

**Comment by bernd-edlinger** [comment]
But it is reproducible at all?

**Comment by maroonbells** [comment]
It reproduced several times that day, but no I can't reproduce it on demand now :(

**Comment by t8m** [comment]
Unfortunately there is a little we can do with irreproducible issues.

**Comment by maroonbells** [comment]
Sorry, I guess this can be closed until I can reproduce it on demand. I couldn't recreate the behavior with UAC control settings, nor by having a program open the .pem in DENY_ALL read mode
