### ISSUE TITLE
Possible tsan issue with arm

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#17447]
Hi,
I've just noticed a single non-repeatable test failure with the CI that was run with
commit d4d8f163db1d32c98d8f956e6966263a7a22fac1:
See https://github.com/openssl/openssl/runs/4736882424?check_suite_focus=true
the config arm-linux-gnueabi fails here:
```
90-test_sysdefault.t ............... ok

    # ERROR: (bool) 'id = OBJ_create(oid, sn, ln) == true' failed @ test/threadstest.c:627
    # false
    # ERROR: (bool) 'multi_success == true' failed @ test/threadstest.c:320
    # false
    # 1050AAFE:error:04000066:object identifier routines:OBJ_create:oid exists:crypto/objects/obj_dat.c:765:
    # OPENSSL_TEST_RAND_ORDER=1641549105
    not ok 13 - test_obj_add
# ------------------------------------------------------------------------------
../../util/wrap.pl ../../test/threadstest -fips -config /home/runner/work/openssl/openssl/test/default-and-fips.cnf ../../test/recipes/90-test_threads_data => 1
not ok 1 - running test_threads with FIPS
# ------------------------------------------------------------------------------
# Looks like you failed 1 test of 2.90-test_threads.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```
by code inspection I would suppose the most plausible reason is that this function failed to produce
unique uid for concurrent threads:
https://github.com/openssl/openssl/blob/10481d33844218694929a7bad57314411a33ab74/test/threadstest.c#L48-L57

that is backed by an experiment I did here:
https://github.com/bernd-edlinger/openssl/blob/ecbf0cd19c230e450dc04f164f54afae4581448d/include/internal/tsan_assist.h#L131

indeed this does not compile for this target

**Comment by paulidale** [comment]
Seems the comment just below suggesting the #ifdef and locked fallback isn't widely known.
We've got four instances of the #ifdef check in the code but way more uses of the tsan_ functions.

The fallback should do some locking I suspect.

**Comment by paulidale** [comment]
After deeper digging, our TSAN support is a mess.  If it were a little more widespread, I'd call it a disaster.

Only a couple of places condition on things being available.  Virtually nothing does locking when TSAN isn't properly supported.  There isn't even a decent way to tell if locking is required or not.  The macros are polymorphic (accepting `int`, `unsigned int` and `unsigned long`) so can't easily be replaced with functions.

The only plus side is that TSAN is used where an error doesn't seem like it would be a massive problem (there's a few spots in ssl where I'm not sure).

Converting TSAN to be a structure and a lock in this case would be possible but it would also introduce a significant overhead.
