### ISSUE TITLE
openssl version

### ISSUE THREAD

**Issue by Nixia408** [openssl/openssl#17452]
How can I know which versions the current openssl version is compatible with, for example, the version on the server side is openssl_1_1_1L, then what is the minimum version of openssl on the client side?

**Comment by mattcaswell** [comment]
It's not entirely clear what you are asking. I assume you are referring to SSL/TLS support. Both OpenSSL 3.0 and OpenSSL 1.1.1, by default, will support TLS1.0, TLS1.1, TLS1.2 and TLS1.3. OpenSSL 1.0.2, by default, supports TLS1.0, TLS1.1 and TLS1.2.

All of the above OpenSSL versions have SSL/TLS versions in common and are therefore compatible with each other. It is *possible* to *configure* things such that they are not compatible. For example configuring OpenSSL 1.1.1 to only support TLS1.3 is possible, but in this case it would not be able to communicate with OpenSSL 1.0.2 which does not support TLS1.3.

**Comment by Nixia408** [comment]
Thank you for your answer. I have an another question. When I upgraded openssl to a higher version, I encountered the following problems, what is the reason for this, is it caused by the version?Looking forward to hearing from you.&nbsp;




Best wishes!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openssl/openssl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openssl/openssl] openssl version (Issue #17452)





 
It's not entirely clear what you are asking. I assume you are referring to SSL/TLS support. Both OpenSSL 3.0 and OpenSSL 1.1.1, by default, will support TLS1.0, TLS1.1, TLS1.2 and TLS1.3. OpenSSL 1.0.2, by default, supports TLS1.0, TLS1.1 and TLS1.2.
 
All of the above OpenSSL versions have SSL/TLS versions in common and are therefore compatible with each other. It is possible to configure things such that they are not compatible. For example configuring OpenSSL 1.1.1 to only support TLS1.3 is possible, but in this case it would not be able to communicate with OpenSSL 1.0.2 which does not support TLS1.3.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nixia408** [comment]
The problem is shown in the attached image of the email！
"Error in server certificate verification:EE certificate key too weak!"


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openssl/openssl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openssl/openssl] openssl version (Issue #17452)





  
... I encountered the following problems
  
You didn't include the actual problem, unfortunately
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
