### ISSUE TITLE
Remove the member peer  from a ticket to reduce the ticket size in session resumption?

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#17450]
In session resumption，the new session ticket msg is big size because the certificate of the peer end is loaded. 

Certificate authentication is not required for session reuse，I did not find the function of the peer certificate.

Remove the peer (openssl/ssl/ssl_asn1.c:27) can bring some benefits in session resumption which performed many times.

https://github.com/openssl/openssl/blob/328bf5adf9e23da523d4195db309083aa02403c4/ssl/ssl_asn1.c#L17-L47

**Comment by kaduk** [comment]
The peer's certificate is retained as a record of the authenticated entity of the party that completed the initial handshake.
For better or for worse, the public APIs that give authentication information (e.g., `SSL_get0_peer_certificate()`) assume that the whole certificate is present, and so the whole certificate must be retained in the session ticket in order for those APIs to function on a resumed connection.

**Comment by yangyangtiantianlonglong** [comment]
> The peer's certificate is retained as a record of the authenticated entity of the party that completed the initial handshake.

During certificate authentication during the initial handshake, the session still saves the peer certificate. It will not make SSL_get0_peer_certificate() unavailable.

> For better or for worse, the public APIs that give authentication information (e.g., SSL_get0_peer_certificate()) assume that the whole certificate is present, and so the whole certificate must be retained in the session ticket in order for those APIs to function on a resumed connection.

It is reasonable that SSL_get0_peer_certificate() returns NULL when the peer certificate is not used during session reuse.For example, in PSK authentication and anonymous authentication, SSL_get0_peer_certificate() returns NULL.

**Comment by yangyangtiantianlonglong** [comment]
```javascript
diff --git a/include/openssl/ssl.h.in b/include/openssl/ssl.h.in
index 9c00eb3d13..34a81cb39e 100644
--- a/include/openssl/ssl.h.in
+++ b/include/openssl/ssl.h.in
@@ -408,6 +408,8 @@ typedef int (*SSL_async_callback_fn)(SSL *s, void *arg);
      */
 # define SSL_OP_CRYPTOPRO_TLSEXT_BUG                     SSL_OP_BIT(31)

+# define SSL_OP_NEW_SESSION_TICKET_NO_PEER               SSL_OP_BIT(32)
+
 /*
  * Option "collections."
  */
diff --git a/ssl/ssl_asn1.c b/ssl/ssl_asn1.c
index 3503fdc210..f5d30843a1 100644
--- a/ssl/ssl_asn1.c
+++ b/ssl/ssl_asn1.c
@@ -167,7 +167,8 @@ int i2d_SSL_SESSION(const SSL_SESSION *in, unsigned char **pp)
     as.timeout = (int64_t)in->timeout;
     as.verify_result = in->verify_result;

-    as.peer = in->peer;
+    if (!(in->flags & SSL_SESS_FLAG_NO_PEER))
+        as.peer = in->peer;

     ssl_session_sinit(&as.tlsext_hostname, &tlsext_hostname,
                       in->ext.hostname);
diff --git a/ssl/ssl_local.h b/ssl/ssl_local.h
index ddae48b2af..0c490dd2e6 100644
--- a/ssl/ssl_local.h
+++ b/ssl/ssl_local.h
@@ -642,6 +642,8 @@ struct ssl_session_st {

 /* Extended master secret support */
 # define SSL_SESS_FLAG_EXTMS             0x1
+/* new sess ticket no peer */
+# define SSL_SESS_FLAG_NO_PEER           0x2

 # ifndef OPENSSL_NO_SRP

diff --git a/ssl/ssl_sess.c b/ssl/ssl_sess.c
index 765ae89916..6dedd0836b 100644
--- a/ssl/ssl_sess.c
+++ b/ssl/ssl_sess.c
@@ -474,6 +474,9 @@ int ssl_get_new_session(SSL *s, int session)
     if (s->s3.flags & TLS1_FLAGS_RECEIVED_EXTMS)
         ss->flags |= SSL_SESS_FLAG_EXTMS;

+    if (s->options & SSL_OP_NEW_SESSION_TICKET_NO_PEER)
+        ss->flags |= SSL_SESS_FLAG_NO_PEER;
+
     return 1;
 }
```

**Comment by kaduk** [comment]
> > The peer's certificate is retained as a record of the authenticated entity of the party that completed the initial handshake.
> 
> During certificate authentication during the initial handshake, the session still saves the peer certificate. It will not make `SSL_get0_peer_certificate()` unavailable.

For the initial handshake, yes.  For resumption handshakes, that information would no longer be available.
Making that change (unconditionally) would be considered an API break and is very likely to break real applications.

> > For better or for worse, the public APIs that give authentication information (e.g., SSL_get0_peer_certificate()) assume that the whole certificate is present, and so the whole certificate must be retained in the session ticket in order for those APIs to function on a resumed connection.
> 
> It is reasonable that `SSL_get0_peer_certificate()` returns NULL when the peer certificate is not used during session reuse.For example, in PSK authentication and anonymous authentication, `SSL_get0_peer_certificate() `returns NULL.

Whether it is reasonable for such an API in the abstract is subject to debate.  (OpenSSL does now include mechanisms that allow the application to include data in the session ticket, so if the API was designed this way from the start, applications that cared about the initial authenticated client identity could extract the identity and save it themselves.)  Whether the current OpenSSL APIs do so is not subject to debate, and we have to retain compatibility with those existing APIs.

One option for shrinking ticket sizes in this manner is to add a new API or flag so that applications can "opt in", as you propose with your `SSL_OP_NEW_SESSION_TICKET_NO_PEER` flag.  (Other implementations of similar functionality that I've seen just act directly on the `SSL_SESSION` without a flag on the `SSL`, but that's not a core question.)

If you offered such a change in a PR it would be able to get review and discussion from the team.

**Comment by yangyangtiantianlonglong** [comment]
Thanks for the detailed explanation.  ok, I'm going to raise a PR to discuss this.
