### ISSUE TITLE
Support EVP_Digest* functions with EVP_VerifyInit and EVP_VerifyUpdate

### ISSUE THREAD

**Issue by DemiMarie** [openssl/openssl#17467]
This allows an application to avoid calculating a SHA-256 digest twice if it also needs to verify an RSA-SHA256 signature

**Comment by t8m** [comment]
OTC said that We do not want this "feature".

**Comment by t8m** [comment]
See #17390

**Comment by t8m** [comment]
Also you can use EVP_PKEY_sign_init/sign and/or verify_init/verify to directly sign or verify the hash value. So there is no need to calculate the hash twice even without using EVP_DigestInit in place of EVP_VerifyInit.
