### ISSUE TITLE
We shouldn't use atexit() in our libraries (or modules, engines and providers alike)

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#17469]
The general recommendation is that atexit() should never be used in shared objects, because the processing of the handlers is done at process exit, and might therefore happen after the shared object is unloaded; this is especially true when said shared object is loaded dynamically.

Linux solves that by making atexit() a per "image" (executable program or shared object) list of handlers, and processes each list at each "image" unload (for an executable program, that's exit), which means that we don't really see the issue there... or presumably on any platform that uses GNU libc.

Here are a few cases when we can find ourselves in this sort of situation:

-   A program linked statically with libcrypto loads a provider that's linked with another libcrypto copy (statically or dynamically, that doesn't really matter), all linked with the same shared libc.
-   A program linked with the standard libcrypto loads a provider that's linked with a local libcrypto variant (built with a config target that has a `shlib_variant` attribute), all linked with the same shared libc.

An ugly workaround is to link each "image" with a static libc.  Modules (loadable engines and providers) will not get cleaned up properly, but at least, the atexit handler list (which resides in libc or crt0) in each "image" will not contain handlers that live in another "image".

A more robust solution is to duplicate what Linux does, i.e. have our own "atexit" in libcrypto, with its own handler list, and ensure that this handler list is processed on share object unload.  We already have stubs to place such processing in for certain platforms (notably WIndows, see https://github.com/openssl/openssl/blob/master/crypto/dllmain.c) or already know how to that sort of thing (see https://github.com/openssl/openssl/blob/7ee992a5d931ab5ad9df00d2d8e47e1b7a72d7ac/providers/fips/self_test.c#L77-L155).

-----

Related to #17059, where we have one of the example situations mentioned above

**Comment by levitte** [comment]
Note that I'm making this master only, as fixing the situation in the suggest more robust way will be quite a massive change that could potentially be too disruptive if applied to 3.0.

**Comment by bernd-edlinger** [comment]
#17112 tries to solve the issue with engines, but got ignored, as usual.

**Comment by levitte** [comment]
> #17112 tries to solve the issue with engines, 

Something like that would have to be done by every `OSSL_provider_init()`...  and with that comes what you've already noted, that the providers would end up cleaning nothing at all if their libcrypto copy isn't the same as the application's.

> ...  but got ignored, as usual.

Sorry...  I can't remember having seen it at all before now.  Either way, it's a bit of a hack...  but maybe that's the more acceptable way forward

**Comment by bernd-edlinger** [comment]
Yes, but the memory leak is not really a big issue, since it will all be statically reachable memory, because
even if the provider is unloaded later, the shared object can't go away, since the alternative libcrypto.so will
stay loaded in the process image due to OPENSSL_USE_NODELETE.

**Comment by rsbeckerca** [comment]
> Yes, but the memory leak is not really a big issue, since it will all be statically reachable memory, because even if the provider is unloaded later, the shared object can't go away, since the alternative libcrypto.so will stay loaded in the process image due to OPENSSL_USE_NODELETE.

It is not the memory leak that concerns me either; rather, it is any static variables in libcrypto.so that get duplicated - the `register_atexit` is a symbol of a more general problem. From the caller's perspective, there is no way to know which variable is updated when a call is made - the statically linked or dynamically linked instance. This could lead to other context-sensitive problems. I think we are just masking the problem. In principle, anyway, there should only be one loaded instance of a specific static variable of a .o file regardless of a static or dynamic link, unless the dynamic link is specifically trying to hide the static linked variable.

**Comment by bernd-edlinger** [comment]
Well, another effect of the duplicated static variable would be, if an engine pushes something on the error stack,
that won't be accessible by the caller, but probably the providers don't have the same issue here?

**Comment by levitte** [comment]
> ... pushes something on the error stack, ... but probably the providers don't have the same issue here?

Not if the error upcalls are used.

**Comment by paulidale** [comment]
The obvious alternative is to reintroduce the finalise call.
Not saying its a good idea, just that it's another possibility that avoids atexit().

**Comment by bernd-edlinger** [comment]
> And this is only a problem with engines because the error upcalls that existed in 1.0.2 and earlier were removed for 1.1.0...

Ouch, what a smart move...

**Comment by levitte** [comment]
> > And this is only a problem with engines because the error upcalls that existed in 1.0.2 and earlier were removed for 1.1.0...
> 
> Ouch, what a smart move...

Agreed, irony and all...

**Comment by levitte** [comment]
I don't think that we'll get rid of the internal atexit() call on 3.x...  although it would be easy to require that applications call `OPENSSL_cleanup()` explicitly or register it explicitly with `atexit(OPENSSL_cleanup)`.  But, that doesn't remove the need for providers to do a similar cleanup in a cooperative manner, as implemented with #17483 (and we will still have to do some more hackery to make that work smoothly)

**Comment by levitte** [comment]
#17483 ensures that providers don't leak, although that requires cooperation from provider authors

**Comment by UndefBehavior** [comment]
I wrote about the same issue 4 years ago:
https://github.com/openssl/openssl/issues/9581

With unmerged PR(#10465) which looks like #17112 but for openssl tool.

**Comment by simo5** [comment]
@levitte can you explain why an atexit handler would be needed in the first place?
Is it used to do some module unloading for providers loaded at runtime?
If that is the case applications should be instructued to call the proper OPENSSL_cleanup() function and let them leak as sieves otherwise, IMO.

**Comment by paulidale** [comment]
They were added to not need `OPENSSL_cleanup()`.  I don't know the _why_ of that.

I'm of the opinion that `OPENSSL_cleanup()` is the way to extricate ourselves from the current mess.
However, stopping a library globally cleaning up is probably required.

**Comment by mattcaswell** [comment]
> @levitte can you explain why an atexit handler would be needed in the first place?

Back in the 1.0.x days, OpenSSL library init and deinit was a mess. There was a whole set of different functions that you had to call to initialise the library, and whole set of other ones required to deinitialise it. Depending on what your application was doing you may or may not need to call certain functions. It was very confusing, poorly documented and applications almost always got it wrong (even OpenSSL devs had a hard time keeping it straight what you were supposed to call when, and there were many inconsistencies within our own code base).

The concept was to get away from all of that and simplify things to remove the need for all that complexity and to try and do so in the least breaking way that we could. The solution was to to make most of those init/deinit functions no-ops and to automatically init and deinit the library. This way, applications that "inherited" the old way of init/deinit would continue to work but we would recommend the new simpler of way of requiring no initialisation.

Unfortunately while solving one major problem we introduced a whole new one. Probably we should have taken the hit of having a "breaking" change of requiring a single de-init call (OPENSSL_cleanup). This is only actually breaking if you care about mem leaks on exit.

**Comment by t8m** [comment]
I do not think we can completely remove the atexit handling before 4.0. But IMO we should do so with that release and simply say - if you care about memory leaks on exit, you have to call OPENSSL_cleanup() from the application after ensuring everything using OpenSSL is stopped before.

**Comment by t8m** [comment]
And another thing to do to resolve this is to move everything global that needs cleanups in OPENSSL_cleanup() to libctx. And get all the things like softhsm to use a separate libctx.

**Comment by levitte** [comment]
So one of the objectives for 4.0 could be to move everything to libctx.  But, aren't we still getting into trouble with the default libctx?

**Comment by mattcaswell** [comment]
If everything is moved to libctx then I could eventually envisage `OPENSSL_cleanup()` as being synonymous with:
 
````
OSSL_LIB_CTX_free(OSSL_LIB_CTX_get0_global_default());
````

> But, aren't we still getting into trouble with the default libctx?

Well, if we remove atexit() and people don't call `OPENSSL_cleanup()` then the default libctx won't be freed on exit. This isn't a problem per se, unless you are using tools like valgrind/asan etc which will report mem leaks. So, it *is* a breaking change - which is why we probably can't do it until 4.0.

**Comment by levitte** [comment]
So the point is really that for 4.0, we would envisage making the `OPENSSL_cleanup()` call "mandatory".  What it does under the hood is not really relevant for the application.

**Comment by rsbeckerca** [comment]
[like]  Randall Becker reacted to your message:
________________________________

**Comment by simo5** [comment]
Note that all the problems (crashes) seen with atexit() will move to OPENSSL_cleanup() if nothing else is changed.

The main issue here is that the cleanup functions are not following an ordering that allows libraries used by a provider that need to do some final openssl operation to successfully complete, because the provider de-initialization is done too late after some other context apparently have been freed or rendered unusable.

**Comment by simo5** [comment]
(of course those libraries should use their own contexts preferably, but freeing those contexts needs to be accounted for in the general design if OPENSSL_cleanup() is called before all the user did a OSSL_LIB_CTX_free() of their contexts.

**Comment by rsbeckerca** [comment]
> In addition to issues with dynamic libraries, `atexit` is hazardous in multi-threaded applications. `atexit` runs when the main thread returns from `main`, but there's no guarantee that other threads have stopped by this point. This seems to be the cause of a shutdown crash in Python here: [python/cpython#114653](https://github.com/python/cpython/issues/114653)

PRs #17483 and #23394 both try to address this.

**Comment by davidben** [comment]
#17483 does not appear to address the threading issue, no. It is ultimately not safe for a thread-compatible library to use `atexit`. You need to know something about how the application uses threads to use that, and OpenSSL is not in a position to know this. #23394 seems to make it a configuration option only set by NonStop, which similarly does not address the underlying problem on other platforms.

**Comment by davidben** [comment]
Looks like this has also come up in https://github.com/sfackler/rust-openssl/issues/1293 and https://github.com/openssl/openssl/issues/6214. `OPENSSL_INIT_NO_ATEXIT` was added, but that once again has an issue with the wrong defaults. Also given that individual libraries may each independently initialize OpenSSL, this leads to very unclear semantics if they disagree on the options. (Looks like first one wins?)

The interaction of all this with `optsdone` is also interesting.

**Comment by bernd-edlinger** [comment]
strictly speaking even the function 'exit()' is not thread safe,
see e.g. https://man7.org/linux/man-pages/man3/exit.3.html
> The exit() function uses a global variable that is not protected,
so it is not thread-safe.

You must call _exit if you dont join your threads.

**Comment by davidben** [comment]
I think that is merely saying that two threads can't both call `exit`. TBH it's pretty horrifying that libc implementations don't guard against that one, but hopefully only the top-level application calls `exit`.

That's not the scenario that broke CPython and rust-openssl. The `atexit` problem is that *any* thread which outlives the `main` function, but calls into OpenSSL, immediately has a race condition due to OpenSSL's use of `atexit`. Only one thread is calling `exit` in this case, so it's not running afoul of that rule.

**Comment by bernd-edlinger** [comment]
No that simply means that exit is not in the class of thread-safe functions.
It can potentially race with lots of things.
BTW: this use case is also not safe for global C++ objects.  They get destructed by an atexit handler too.

**Comment by alex** [comment]
Is there any chance that https://github.com/openssl/openssl/pull/23394 could be backported to 3.2.2, so we don't have to wait years to resolve this? It's an ongoing source of issues.

**Comment by rsbeckerca** [comment]
> Is there any chance that #23394 could be backported to 3.2.2, so we don't have to wait years to resolve this? It's an ongoing source of issues.

This is a question for the OTC as it changes the interface of an already published product version.

**Comment by alex** [comment]
To be specific: I'm interested in the compilation option being available. I don't need the NonStop behavior to be backported.

**Comment by t8m** [comment]
**OTC: Would it be OK to backport the no-atexit support (without the NonStop changes) to 3.2?**

**Comment by mattcaswell** [comment]
> Is there any chance that https://github.com/openssl/openssl/pull/23394 could be backported to 3.2.2, so we don't have to wait years to resolve this?

Note that #23394 will be available in 3.3 which is being released in April.

**Comment by t8m** [comment]
**OTC: A vote https://github.com/openssl/technical-policies/issues/89 was held and it allows to backport no-atexit support without the NonStop changes to all 3.x branches.**

**Comment by nhorman** [comment]
Given that no-atexit support is available and backported:
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input

**Comment by greghudson** [comment]
> Well, if we remove atexit() and people don't call OPENSSL_cleanup() then the default libctx won't be freed on exit. This isn't a problem per se, unless you are using tools like valgrind/asan etc which will report mem leaks. So, it is a breaking change - which is why we probably can't do it until 4.0.

valgrind and asan don't report memory as leaked if it is still reachable from global variables at process exit.  valgrind can separately report still-reachable allocated memory, but I think it would be straining to consider that reporting a break.  libc can leave still-reachable memory around at process exit in various circumstances, such as any use of dlopen() with RTLD_NODELETE.

Uncleaned global state would be reported as leaked if libcrypto is unloaded, and could be an actual problematic leak if libcrypto is loaded and unloaded repeatedly.  Historically this could happen if a dependent library (such as a PAM module) is loaded and unloaded repeatedly, and this concern most likely led to introduction of the atexit() calls.  But since 1.1.0, libcrypto prevents itself from being unloaded (commits 5836780f436e03be231ff245f04f2f9f2f0ede91 and b6d5ba1a9f004d637acac18ae3519fe063b6b5e1).  (As an aside, `-z nodelete` should work on any ELF platform, as it existed on Solaris.)

So I would argue against the belief that removing the atexit handling is a breaking change for 3.x.
