### ISSUE TITLE
quic

### ISSUE THREAD

**Issue by rootnk** [openssl/openssl#17475]
Any chance of adding QUIC functionality before 1.1.1n and 3.0.2 ?  I notice a separate branch for quic / openssl develoement .

Maybe it is time to merge?

**Comment by t8m** [comment]
No QUIC support will be added into existing stable branches. We do not add new features to released minor versions.

**Comment by t8m** [comment]
Also there is nothing yet to be merged.

**Comment by rootnk** [comment]
On Wed, Jan 12, 2022 at 01:08:40AM -0800, Tom???? Mr??z wrote:
> No QUIC support will be added into existing stable branches. We do not add new features to released minor versions.
>

So that will you work with openssl quic so that they are up to date
with nightly patches?

> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/openssl/openssl/issues/17475#issuecomment-1010814399
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Member - Liberal International This is doctor@@nl2k.ab.ca Ici doctor@@nl2k.ab.ca
Yahweh, Queen & country!Never Satan President Republic!Beware AntiChrist rising!
Look at Psalms 14 and 53 on Atheism https://www.empire.kred/ROOTNK?t=94a1f39b  
Birthdate 29 Jan 1969 Redhill Surrey England  Beware https://mindspring.com

**Comment by rootnk** [comment]
On Wed, Jan 12, 2022 at 01:09:25AM -0800, Tom???? Mr??z wrote:
> Also there is nothing yet to be merged.
>

I would disagree.  I tried to merge a created diff file from openssl 1.1.1.m
and openssl 1.1.1.m+quic 

And still quite a significant cunk was missing.

> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/openssl/openssl/issues/17475#issuecomment-1010814991
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Member - Liberal International This is doctor@@nl2k.ab.ca Ici doctor@@nl2k.ab.ca
Yahweh, Queen & country!Never Satan President Republic!Beware AntiChrist rising!
Look at Psalms 14 and 53 on Atheism https://www.empire.kred/ROOTNK?t=94a1f39b  
Birthdate 29 Jan 1969 Redhill Surrey England  Beware https://mindspring.com

**Comment by mattcaswell** [comment]
> openssl 1.1.1.m+quic

I think you are referring to quictls which is a fork of OpenSSL not maintained or managed by the OpenSSL project. That code will not be merged here.
