### ISSUE TITLE
openssl 3.0.1 TLS 1.1/1.0 negotiation failed

### ISSUE THREAD

**Issue by qunying** [openssl/openssl#17476]
Under openssl 3.0.1
Running with  `openssl s_server -cert /tmp/.ossl3.pem -key /tmp/ossl3.key`,
Then run `openssl s_client -tls1_1`, or `openssl s_client -tls1` got error from s_server:
```
Using default temp DH parameters
ACCEPT
ERROR
80A19282E37F0000:error:0A000076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:3331:
shutting down SSL
CONNECTION CLOSED
```

Then I try on openssl 1.1.1m acting as server, openssl3.0 as s_client, I got error of:
```
ACCEPT
ERROR
139869616887616:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1543:SSL alert number 80
shutting down SSL
CONNECTION CLOSED
```

TLS 1.2 and 1.3 work as expected.

The same commands with openssl 1.1.1m as server and client works fine for all protocol.
[cert-key.tar.gz](https://github.com/openssl/openssl/files/7849486/cert-key.tar.gz)

**Comment by qunying** [comment]
add the configuration dump
[conf.dump.gz](https://github.com/openssl/openssl/files/7849553/conf.dump.gz)

**Comment by t8m** [comment]
SHA1 is required for TLS1.0 and 1.1 and it is not available at the default SECLEVEL. You need to use `-cipher DEFAULT:@SECLEVEL=0` with OpenSSL-3.0 to be able to use TLS1.0 or TLS1.1.

**Comment by qunying** [comment]
That works. Thanks.
