### ISSUE TITLE
Bug in `evp_keymgmt_util_match`

### ISSUE THREAD

**Issue by manison** [openssl/openssl#17482]
I believe I have found a bug in `evp_keymgmt_util_match` function (worker function used by `X509_check_private_key` for instance). This function is supposed to match two keys. If each come from different keymgmt, the function should export the first key and match it against second keymgmt. If the second keymgmt does not provide the `match` function, the function should try the other way around, i.e. export the second key and match it against the first keymgmt. This mechanism is IMHO flawed.

The flag `ok` is set to `1` at start.

https://github.com/openssl/openssl/blob/a4e01187d3648d9ce99507097400902cf21f9b55/crypto/evp/keymgmt_lib.c#L363-L373

and then when the first try fails the second try is not executed.

https://github.com/openssl/openssl/blob/a4e01187d3648d9ce99507097400902cf21f9b55/crypto/evp/keymgmt_lib.c#L406-L408

I suppose the flag `ok` should be set to `0` at start.

OpenSSL 3.0.1 (present at current master a4e01187).

**Comment by t8m** [comment]
Your analysis is correct. Do you want to submit a PR? It would be acceptable even with CLA: trivial.

**Comment by manison** [comment]
I can prepare PR. The fix itself is simple. Are there any tests affected?

**Comment by t8m** [comment]
> Are there any tests affected?

I do not think so. Although it would be nice to have a testcase for this, it is not required.
