### ISSUE TITLE
Explicitly flag which function parameters may be NULL

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#17493]
This very general topic came up (most likely not the first time) with https://github.com/openssl/openssl/pull/17488#issuecomment-1012017772.

It would be great if for each pointer parameter it was made clear already from the function declaration whether it is allowed to be `NULL`.
* It would certainly help users of a function to see immediately if a pointer parameter is optional or not. Sometimes this is explicitly mentioned in the documentation, but for the most part this is implicit, and there are many cases where this is unclear, and users would need to dig into the function implementation.
* It could also be very beneficial for static analysis tools to have direct information on this, rather than having to infer this (more or less correctly and completely) from the code itself.

What do you think about the relevance of this issue, 
and are you aware of a good solution?

I've just learned from https://github.com/openssl/openssl/pull/17488#issuecomment-1012026961 that some compilers like `gcc` offer attributes for this can enforce this, but likely they are not portable and they can be more or less cumbersome to specify and use.

Here is a pretty trivial solution that I've introduced in https://github.com/siemens/libsecutils/blob/master/include/secutils/basic.h#L29:
```
#define OPTIONAL /*!< marks non-required parameter, i.e., NULL pointer allowed */
```
such that a function header could read like this:
```
int load_cert_certs(const char *uri,
                    OPTIONAL X509 **pcert, OPTIONAL STACK_OF(X509) **pcerts,
                    int exclude_http, OPTIONAL const char *pass, 
                    OPTIONAL const char *desc,
                    OPTIONAL X509_VERIFY_PARAM *vpm)
```
Of course the name used could be adapted, e.g., to `OSSL_OPT`.

What I like about such a notation is:
* By default the reader has to assume that a pointer parameter must not be NULL, 
which certainly is the correct assumption for the majority of cases 
and in doubt errs on the safe side.
* The attribute, just like `const` etc., is given directly with the parameter it refers to,
which is pretty robust on changing the order of parameters, as opposed to the `gcc` way of specifying the non-NULL parameters via their position index, e.g, `__attribute__((nonnull (1, 3)))`.

**Comment by DDvO** [comment]
Any comments on this by @openssl/otc?

**Comment by t8m** [comment]
**OTC: do we want to mark pointer arguments that are allowed to be NULL with the OPTIONAL macro**

**Comment by paulidale** [comment]
OTC: we won't do this.
