### ISSUE TITLE
Undefined behavior (null pointer passed as argument 1, which is declared to never be null) in pkcs12kdf_derive

### ISSUE THREAD

**Issue by CindyZhouYH** [openssl/openssl#17505]
Hello.
I am using latest OpenSSL on ubuntu 20.04. I compiled with clang++ and UBSan.
It seems that funtion `pkcs12kdf_derive` in [providers/implementations/kdfs/pkcs12kdf.c](https://github.com/openssl/openssl/blob/master/providers/implementations/kdfs/pkcs12kdf.c) doesn't do validation check on param `*out`. When `*out` is nullptr, UBSan detects a runtime error:
<img width="748" alt="1642156308(1)" src="https://user-images.githubusercontent.com/60092417/149501987-5dd7e8f9-c7f2-4022-b88c-2b24cb56f298.png">

**Comment by t8m** [comment]
Do you have a concrete code example which invokes this code with NULL *out?

**Comment by CindyZhouYH** [comment]
Try this:
```
void test(){
    int keySize = 0;
    EVP_KDF_CTX* kctx = nullptr;
    const EVP_MD* md = nullptr;
    OSSL_PARAM params[7], *p = params;
    uint8_t* out = nullptr;

    std::vector<uint8_t> password;
    password.push_back(0xcc);
    password.push_back(0xd2);
    *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_PASSWORD, password.data(), password.size());

    std::vector<uint8_t> salt;
    *p++ = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SALT, salt.data(), salt.size());

    unsigned int iterations = 2;
    *p++ = OSSL_PARAM_construct_uint(OSSL_KDF_PARAM_ITER, &iterations);

    unsigned int id = 1;
    *p++ = OSSL_PARAM_construct_uint(OSSL_KDF_PARAM_PKCS12_ID, &id);

    md = EVP_blake2b512();
    std::string name(EVP_MD_name(md));
    *p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_DIGEST, name.data(), name.size() + 1);

    int pkcs5 = 0;
    *p++ = OSSL_PARAM_construct_int(OSSL_KDF_PARAM_PKCS5, &pkcs5);
    
    *p = OSSL_PARAM_construct_end();

    EVP_KDF* kdf = EVP_KDF_fetch(nullptr, "PKCS12KDF", nullptr);
    kctx = EVP_KDF_CTX_new(kdf);
    EVP_KDF_free(kdf);
    EVP_KDF_derive(kctx, out, keySize, params);    //trigger bug

    EVP_KDF_CTX_free(kctx);
    free(out);
}
```

**Comment by t8m** [comment]
This is not a bug. Using NULL pointer for out parameter of EVP_KDF_derive() is invalid use of the function. We do not add NULL pointer checks to such function calls. It would be a bug only if you could reproduce the crash with valid use of the public API calls.

**Comment by CindyZhouYH** [comment]
Okay. Thanks a lot.
