### ISSUE TITLE
SSL_connect always returned "decryption failed or bad record mac" in TLS 1.2 when I try to use session_ticket resumption

### ISSUE THREAD

**Issue by forston** [openssl/openssl#17501]
Hi Openssl Team

Can you help to check this question?

When I try to use session_ticket resumption, `SSL_connect` always returned -1, error code is **`SSL_R_DECRYPTION_FAILED_OR_BAD_RECORD_MAC`**.
I used `ERR_print_errors_fp(stdout);` to print the error details:
`21968:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl\record\ssl3_record.c:677:`

My openssl version is 1.1.1l, and compile cmd is "debug-VC-WIN64A no-asm no-shared no-autoload-config no-pinshared".

I checked the wireshark log, server has agreed to do session_ticket resumption, but SSL_connect send an alert and closed the session.

I have pasted the code and wireshark in following , **can you help to check if I missed any steps in my code?**
- client hello 
```
Secure Sockets Layer
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 512
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 508
            Version: TLS 1.2 (0x0303)
            Random: d95bd7afd75f39dbef065ecb1e4a1d098c8a34659891c72f...
            Session ID Length: 0
            Cipher Suites Length: 56
            Cipher Suites (28 suites)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 411
            Extension: ec_point_formats (len=4)
                Type: ec_point_formats (11)
                Length: 4
                EC point formats Length: 3
                Elliptic curves point formats (3)
            Extension: supported_groups (len=12)
                Type: supported_groups (10)
                Length: 12
                Supported Groups List Length: 10
                Supported Groups (5 groups)
            Extension: SessionTicket TLS (len=160)
                Type: SessionTicket TLS (35)
                Length: 160
                Data (160 bytes)
            Extension: encrypt_then_mac (len=0)
                Type: encrypt_then_mac (22)
                Length: 0
            Extension: extended_master_secret (len=0)
                Type: extended_master_secret (23)
                Length: 0
            Extension: signature_algorithms (len=48)
                Type: signature_algorithms (13)
                Length: 48
                Signature Hash Algorithms Length: 46
                Signature Hash Algorithms (23 algorithms)
            Extension: padding (len=159)
                Type: padding (21)
                Length: 159
                Padding Data: 000000000000000000000000000000000000000000000000...
```
- server response
```
Secure Sockets Layer
    TLSv1.2 Record Layer: Handshake Protocol: Server Hello
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 49
        Handshake Protocol: Server Hello
            Handshake Type: Server Hello (2)
            Length: 45
            Version: TLS 1.2 (0x0303)
            Random: 310c2d84467e803e74a22d3b3b4cc0a328e1456101961613...
            Session ID Length: 0
            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
            Compression Method: null (0)
            Extensions Length: 5
            Extension: renegotiation_info (len=1)
                Type: renegotiation_info (65281)
                Length: 1
                Renegotiation Info extension
    TLSv1.2 Record Layer: Change Cipher Spec Protocol: Change Cipher Spec
        Content Type: Change Cipher Spec (20)
        Version: TLS 1.2 (0x0303)
        Length: 1
        Change Cipher Spec Message
            [Expert Info (Note/Sequence): This session reuses previously negotiated keys (Session resumption)]
    TLSv1.2 Record Layer: Handshake Protocol: Encrypted Handshake Message
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 40
        Handshake Protocol: Encrypted Handshake Message
```
- Client sent an alert
```
Secure Sockets Layer
    TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Bad Record MAC)
        Content Type: Alert (21)
        Version: TLS 1.2 (0x0303)
        Length: 2
        Alert Message
```
Following is my code, i referred to `openssl-1.1.1l\test\clienthellotest.c`, session_secret_cb just returned 1:
```
	m_pSSLCTX = SSL_CTX_new(TLSv1_2_method());
	if (m_pSSLCTX == nullptr)
	{
		SL_ERROR_LOG("Create SSL_CTX failed.\n");
		return EN_SL_STATUS_CREATE_SSL_FAIL;
	}

	SSL_CTX_set_options(m_pSSLCTX, SSL_OP_ALL);

	m_pSSL = SSL_new(m_pSSLCTX);
	if (m_pSSL == nullptr)
	{
		SL_ERROR_LOG("Create SSL failed.\n");
		return EN_SL_STATUS_CREATE_SSL_FAIL;
	}

	if (!SSL_set_fd(m_pSSL, m_hSocket))
	{
		SL_ERROR_LOG("Bind Socket failed.\n");
		return EN_SL_STATUS_BIND_SOCKET_FAIL;
	}

	unsigned char* buff = new unsigned char[1024];
	size_t len = 0;
	if (!_access("testsession.txt", 4))
	{
		FILE* p = fopen("testsession.txt", "rb");
		len = fread(buff, 1, 1024, p);
		fclose(p);

		int ret = SSL_set_session_ticket_ext(m_pSSL, buff, len);

		SL_ERROR_LOG("set ticket session, ret %d", ret);
		tls_session_secret_cb_fn cb = session_secret_cb;
		SSL_set_session_secret_cb(m_pSSL, cb, NULL);
	}

	int iret = SSL_connect(m_pSSL);
	ERR_print_errors_fp(stdout);
	SL_ERROR_LOG("SSL_connect, ret %d", iret);

	SSL_SESSION* sslSession = SSL_get_session(m_pSSL);
	if (SSL_SESSION_has_ticket(sslSession))
	{
		SL_ERROR_LOG("There is a ticket session");
		const unsigned char* buff = NULL;
		size_t len = 0;
		SSL_SESSION_get0_ticket(sslSession, &buff, &len);
		SL_ERROR_LOG("Has got a ticket session, len %d", len);
		FILE* p = fopen("testsession.txt", "wb");
		fwrite(buff, 1, len, p);
		fclose(p);
	}
	else
	{
		SL_ERROR_LOG("There is no a ticket session");
	}
```

forston

**Comment by mattcaswell** [comment]
> i referred to openssl-1.1.1l\test\clienthellotest.c

This is not a good place to start. That test is testing various corner cases about creating ClientHellos to ensure that they are created as we expect. It does *not* do a resumption handshake and should not be considered a demonstration of how to do that.

To resume a session you should not be saving out just the ticket. You need much more state than just that. The ticket just encapsulates the server side resumption state. The client also needs to restore its own state. You need to store the whole SSL_SESSION object - which includes the ticket data (for example you could write this to a file using a function such as PEM_write_bio_SSL_SESSION).

When resuming you need to set the session on the client's SSL object before you start. For example see:
https://github.com/openssl/openssl/blob/71396cd048072b69559b46d98cfebfd4474cd712/apps/s_client.c#L1953-L1972

You may also want to consider calling `SSL_SESSION_is_resumable()` to confirm whether an SSL_SESSION object is even valid for resumption.

**Comment by forston** [comment]
Hi Mattcaswell
Thanks for your help.
After store and restore session information, the resumption is ok now.
Following is my partial code

	if (!_access("biosession.txt", 4))
	{
		SSL_SESSION *sess;
		BIO *stmp = BIO_new_file("biosession.txt", "r");
		if (stmp == NULL)
		{
			SL_ERROR_LOG("Read session file failed");
		}
		sess = PEM_read_bio_SSL_SESSION(stmp, NULL, 0, NULL);
		BIO_free(stmp);
		if (sess == NULL) {
			SL_ERROR_LOG("Read session failed");
		}

		SL_ERROR_LOG("session reusableflag %d", SSL_SESSION_is_resumable(sess));

		if (!SSL_set_session(m_pSSL, sess)) {
			SL_ERROR_LOG("Set session failed");
		}
		SSL_SESSION_free(sess);
	}

	int iret = SSL_connect(m_pSSL);
	ERR_print_errors_fp(stdout);
	SL_ERROR_LOG("SSL_connect, ret %d", iret);
	SSL_SESSION* sslSession = SSL_get_session(m_pSSL);
	if (SSL_SESSION_has_ticket(sslSession))
	{
		SSL_SESSION *sess;
		BIO *stmp = BIO_new_file("biosession.txt", "w");
		if (stmp == NULL)
		{
			SL_ERROR_LOG("Open session file failed");
		}
		int len = PEM_write_bio_SSL_SESSION(stmp, sslSession);
		BIO_free(stmp);
	}
	else
	{
		SL_ERROR_LOG("There is no a ticket session");
	}
