### ISSUE TITLE
`PEM_write_bio_PKCS8PrivateKey()` doesn't accept empty passphrase strings anymore

### ISSUE THREAD

**Issue by RaisinTen** [openssl/openssl#17506]
At Node.js, in order to pass an empty passphrase string to `PEM_write_bio_PKCS8PrivateKey()` without running the default callback which unwantedly opens up a user input prompt, we were passing these variables:
```cc
char* kstr = reinterpret_cast<char*>(-1)
size_t klen = 0
```
This was working okay up to 1.1.1l but from 3.0.1, we started noticing some unexpected malloc failures.

I found the cause of the malloc failure:
* https://github.com/openssl/openssl/blob/71396cd048072b69559b46d98cfebfd4474cd712/crypto/o_str.c#L55-L59
Along with the return value of `CRYPTO_malloc()` being `NULL`, `errno` too should be checked for an `ENOMEM` value to consider this to be a malloc failure.
* https://github.com/openssl/openssl/blob/71396cd048072b69559b46d98cfebfd4474cd712/crypto/passphrase.c#L43-L48
Along with the return value of `OPENSSL_memdup()` being `NULL`, `errno` too should be checked for an `ENOMEM` value to consider this to be a malloc failure.

I tried fixing those locally but now I get:
```js
[Error: error:07880106:common libcrypto routines::passed invalid argument] {
  opensslErrorStack: [ 'error:1C80009F:Provider routines::unable to get passphrase' ],
  library: 'common libcrypto routines',
  reason: 'passed invalid argument',
  code: 'ERR_OSSL_CRYPTO_PASSED_INVALID_ARGUMENT'
}
```

Locally I had also tried passing a custom callback as a workaround:
```cc
auto pass_cb = [](char *buf, int size, int rwflag, void *u) -> int {
  return 0;
};
```
but that fails with:
```js
[Error: error:14000065:UI routines::result too small] {
  opensslErrorStack: [
    'error:1C80009F:Provider routines::unable to get passphrase',
    'error:07880109:common libcrypto routines::interrupted or cancelled',
    'error:0480006D:PEM routines::problems getting password',
    'error:1400006B:UI routines::processing error'
  ],
  library: 'UI routines',
  reason: 'result too small',
  code: 'ERR_OSSL_UI_RESULT_TOO_SMALL'
}
```

Bug report in the Node.js repo: https://github.com/nodejs/node/issues/41428
Relevant code area in Node.js: https://github.com/nodejs/node/blob/426df1b836432bb6c4dd2beb127d40d804db7aeb/src/crypto/crypto_keys.cc#L292-L390

**Comment by RaisinTen** [comment]
PR to fix the invalid malloc failure reports: https://github.com/openssl/openssl/pull/17507

**Comment by bernd-edlinger** [comment]
I wonder if an empty passphrase is valid at all.
You cannot enter it with `-password pass:` for instance.
When entering from the console you have to enter 4 letters min.

**Comment by bernd-edlinger** [comment]
Aehm, disregard my comment about less than 4 letter password, that is a pkcs12 feature.
pkcs8 accepts even empty passwords...
