### ISSUE TITLE
Process calling EVP_PBE_scrypt() killed by Linux OOM before it can exit gracefully

### ISSUE THREAD

**Issue by kennbr34** [openssl/openssl#17502]
https://github.com/openssl/openssl/blob/4c5c2a5efbc315d7926cafbd5a19044ee3e087fa/crypto/evp/pbe_scrypt.c#L240-L244

Sometimes the OOM kills the program calling EVP_PBE_scrypt() before OPENSSL_malloc() can return NULL and exit gracefully. This prevents any clean-up calls to OPENSSL_cleanse() from running in the calling program. Which behavior occurs seems very random.

OpenSSL Version: 1.1.1k from distro repositories
Distro: Debian 11.1
Kernel: Linux 5.10.09
scrypt work factors: N=1048576,r=8,p=1
System memory: 2048 MB
Swap: None

**Comment by kennbr34** [comment]
I just built a memory check into the calling application, but was just not sure if this was a bug or not.

**Comment by kennbr34** [comment]
> Scrypt works by making it costly to attack due to requiring large amounts of memory. It is a fundamental feature of the algorithm that memory usage is high. So - not a bug IMO.

Hmm I think I may have been less than clear in my attempt to be brief.

The library code tests for sufficient memory by first attempting to allocate, and then determining whether that allocation was successful or not. If not, then there was not sufficient memory, and then it attempts to exit gracefully and perform clean-up routines.

However, under Linux with default Out Of Memory Manager settings, then what instead happens is that sometimes the OOM kills the process before the allocation can be evaluated as successful or not. This then prevents any of the subsequent clean-up routines from being able to run. Worse yet, if there is any sensitive data that needs to be cleared via OPENSSL_cleanse() or similar, then it also prevents that from happening as well. As you can see by the link below, this is called "Heuristic overcommit handling" and causes the unpredictability.

https://www.kernel.org/doc/Documentation/vm/overcommit-accounting

The OOM is an integral feature, and one that is not necessarily trivial to reconfigure, if privileges allow configuring it at all. If the library code is intended to run on a Linux environment, then should it not consider the default OOM configuration of that environment?

Given that the code attempts to do one thing, but only accomplishes doing that thing some of the time, I think that constitutes a bug. I guess you could also argue that this is a platform/environment dependent issue, and to simply disable and/or reconfigure the OOM or reduce the scrypt work factors. However, neither of those seem like ideal solutions that really address the root issue: the library code is failing to do what it intended independent what platform and/or environment it is running in.

**Comment by paulidale** [comment]
There is **nothing** the library can do to circumvent the OOM killer.
This is **not** a bug in the library.

The **only** solution here is for **you** to disable the kernel's memory overcommitment.

**Comment by kennbr34** [comment]
> There is **nothing** the library can do to circumvent the OOM killer.

It's not possible to check the amount of available memory against what is needed **without** attempting to allocate that amount and triggering the OOM?

**Comment by paulidale** [comment]
The kernel is lying about the amount of available memory.  Get it to stop.

**Comment by kennbr34** [comment]
> Also not calling the OPENSSL_cleanse() in this situation is completely irrelevant as the process is killed and the physical (or swap) memory of the process will never be allocated to any other process without cleaning it first by the kernel.

Isn't this only true if the kernel is configured to use hardened_malloc?

**Comment by t8m** [comment]
> Isn't this only true if the kernel is configured to use hardened_malloc?

No, please think about it. Physical memory can be mapped and unmapped to different processes at any time (if you have swap). It would be a major security hole if the memory was not cleaned when being mapped to a different process.

**Comment by kennbr34** [comment]
> > Isn't this only true if the kernel is configured to use hardened_malloc?
> 
> No, please think about it. Physical memory can be mapped and unmapped to different processes at any time (if you have swap). It would be a major security hole if the memory was not cleaned when being mapped to a different process.

I misinterpreted what you were saying. I thought you meant the kernel would zero out the memory when it was freed. That's why I mentioned hardened_malloc.
