### ISSUE TITLE
Is OpenSSL_version_num() deprecated?

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#17517]
The function `OpenSSL_version_num()` is not marked as deprecated in the header file or in the source code or in libcrypto.num. But in the documentation, it is described in the "BACKWARD COMPATIBILITY" section which says this at the beginning of it:

> For compatibility, some older macros and functions are retained or
synthesised.
They are all considered deprecated.

Its also listed as deprecated in the synopsis section of the man page.

The situation is similar with the OPENSSL_VERSION_NUMBER macro, i.e. its not marked as deprecated in the header file, but it is in the docs. This one is additionally marked as deprecated in other.syms.

It seems very unclear whether they really are deprecated or not.

**Comment by mattcaswell** [comment]
Yes, I'm not really sure why we wanted to deprecate this function. It's actually quite useful to have a single value to represent the whole version number - and it exists in old versions too. In my response to #17516 I wanted to say that the easiest way to compare the header version against the library version is to compare OPENSSL_VERSION_NUMBER against the output of `OpenSSL_version_num()` but felt unable to because of the ambiguous deprecation status.

**Comment by t8m** [comment]
I would treat this issue as a documentation bug and simply undeprecate. But perhaps we need to discuss this within OTC?

**Comment by mattcaswell** [comment]
> But perhaps we need to discuss this within OTC?

Yes. I think so

**Comment by mattcaswell** [comment]
**Question for OTC: Should `OPENSSL_VERSION_NUMBER` and `OpenSSL_version_num()` be undeprecated in the documentation? Alternatively should they be marked as deprecated in the header files?**

**Comment by levitte** [comment]
Because the bit arrangement in that number has changed over time, resulting in, uhm, pretty *creative* was to handle it, I thought that the new macros were much easier to interpret.

Deprecating the old was meant to be in the interest of not trying to have two ways to check.

**Comment by t-j-h** [comment]
I agree that this should be undeprecated in the documentation - the documentation is wrong.
Warning that this has challenges when we get to a much later major version would have been more appropriate IMHO.

**Comment by paulidale** [comment]
These should be undeprecated.

**Comment by t8m** [comment]
**OTC Decision: the OPENSSL_VERSION_NUMBER macro and OpenSSL_version_num() function should be undeprecated on the 3.0 branch in the documentation**
