### ISSUE TITLE
Is  reaonable which the ENGINE_free()  free up the public key meths ?

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#17513]
https://github.com/openssl/openssl/blob/71396cd048072b69559b46d98cfebfd4474cd712/crypto/engine/eng_lib.c#L71-L98

The `engine_free_util():86-87` caused to re-release memory, that is a very obscure point.

When I use the engine, the ciphers meths and digest meths need to be applied for and released by the user. The public key meths is applied for by the user and the ENGINE_free is released.

I don't understand the purpose of this, , Can you help explain?  and I'll add documentation for it.
@mattcaswell

**Comment by beldmit** [comment]
Looks like it's a historical inconsistency between registering/freeing digests/ciphers and public key methods. Before making EVP_MD/EVP_CIPHER opaque engine could declare its own structs and register them in global tables. asymmetric-related structs were opaque from the very beginning and memory was allocated by libcrypto API

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
