### ISSUE TITLE
Error:OpenSSL SSL_read: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca, errno 0

### ISSUE THREAD

**Issue by ziasultan2** [openssl/openssl#17519]
I created a certificate and when I try to run it with curl it gives me this error

**Comment by t8m** [comment]
I suppose you're trying to use the certificate as a client certificate? That alert means the server does not recognize the certification authority that signed your certificate as a trusted CA. Or it might signalize other problems with the certificate.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
