### ISSUE TITLE
Are versions in util/libssl.num supposed to increment alongside minor version? 

### ISSUE THREAD

**Issue by satmandu** [openssl/openssl#17516]
https://github.com/openssl/openssl/blob/b4e83ed7cd99c12d27e0e220c3afa1745a68f921/util/libssl.num#L512

Should these be 3_0_1 now with OpenSSL 3.0.1?

Asking because I believe curl is comparing header version with library versions via a call to `SSL_CTX_load_verify_dir` which finds the library version here.

**Comment by mattcaswell** [comment]
> Should these be 3_0_1 now with OpenSSL 3.0.1?

No. They need to remain stable across patch/minor change bumps. If we add *new* symbols then *they* would get the higher version number
