### ISSUE TITLE
bio_asn1 infinite loop

### ISSUE THREAD

**Issue by voices117** [openssl/openssl#1752]
When using an asn1 BIO and the sink BIO fails to write returning -1 (error), the state machine keeps retrying in an infinite loop.

The problem is caused by [this line](https://github.com/openssl/openssl/blob/master/crypto/asn1/bio_asn1.c#L211).

I assume the intention of the `break` was to exit the `for` loop, but it only makes the `switch case` end and thus returning to the same state over and over.

It could be solved by replacing the `break` in the indicated line by a `goto done;`.

**Comment by mattcaswell** [comment]
This was fixed with f125430 in master and 723f616 in 1.1.0.
