### ISSUE TITLE
I there a way to selectively add flags when linking executables?

### ISSUE THREAD

**Issue by yanovich** [openssl/openssl#17523]
Is there a way to selectively add flags when linking test executables?

I am trying to add `-Wl,-E,--whole-archive libcrypto.a -Wl,--no-whole-archive` to tests that use engines, but there is no obvious way either in code or docs. You may see #17509 for context.

Thanks for your time, if you are reading this )

**Comment by levitte** [comment]
No, we only support selectiveness in term of type of output (i.e. you can select optional flags on the basis of shared objects, themselves being divided in shared libraries to link with and dynamically loadable modules, executables and static libraries), but not on individual output.  The idea was that build.info files should be platform independent, and compiler flags aren't that at all.

It wouldn't be impossible to add language to support that sort of thing, but for the thing you ask, this isn't a small job...

**Comment by yanovich** [comment]
For reference, a patch in #17509 allows to pass simple flags like `-Wl,-E` which don't depend on the order. `/Configure` uses hash to process data and reorders tokens in `DEPEND` and all the other fields.
