### ISSUE TITLE
SSL_write failed with SSL_ERROR_SYSCALL, errno:41

### ISSUE THREAD

**Issue by shubhamk14** [openssl/openssl#17524]
Hello OpenSSL community,

My openssl version is 1.1.1g, and compiled on Mac Catalina x86-64.

**Issue: SSL_write failed with SSL_ERROR_SYSCALL on TCP socket after many writes.**
_SSL_write failed with SSL_ERROR_SYSCALL, errno:41_
**Environment: Big Sur and Monterey**

Also not able to understand that after many writes why suddenly errno 41 i.e. invalid prototype appeared and also ERR_error_string() is not giving any error string as well.
From wireshark capture there's no SSL packet sent by the client hence the message is not even making to the interface.

Please help in understanding and resolving the SSL_write() error on TCP socket.
Thanking you.
Shubham Kaushal

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
