### ISSUE TITLE
Building tests in parallel

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#17535]
I have an impression that building the test binaries takes much more time than building the library itself, especially when `make -s` is used. If I understand correctly, it happens because of low parallelization of building test binaries. Am I wrong? If so, can we add a parallelized build for tests?

**Comment by paulidale** [comment]
They do build in parallel already:
```sh
$ touch libcrypto.a libcrypto.so.3
$ time make -s

real	0m18.292s
user	0m13.436s
sys	0m4.836s

$ touch libcrypto.a libcrypto.so.3
$ time make -s -j20

real	0m3.323s
user	0m37.883s
sys	0m12.645s
```
