### ISSUE TITLE
Whether the cryptographic operations used to generate random numbers cannot use async

### ISSUE THREAD

**Issue by hijj** [openssl/openssl#17530]
When using the interface drbg_bytes to generate random numbers, since public_drbg is a per-thread variable, if the encryption and decryption operations in the process of generating random numbers are asynchronous, will it cause an exception? Whether it is necessary to distinguish these encryption and decryption at the engine layer and prevent asynchronous execution？

**Comment by paulidale** [comment]
I'm not sure I follow the question.  Since you mention encryption, I assume you are using CTR-DRBG which uses AES-CTR and AES-ECB internally.  You also seem to be using an engine to provide the AES support.  What I'm not clear about is the asynchronous part.  I'm not sure how that is relevant -- the DRBG calls EVP_Cipher functions which are always synchronous.

**Comment by hijj** [comment]
What I want to express is exactly AES-CTR and AES-ECB in CTR-DRBG. Currently, the openssl asynchronous coroutine mechanism is used, and the aes-ctr algorithm is registered through the opened openssl ENGINE, and the aes-ctr encryption is handed over to the hardware encryption card to do it, and then call ASYNC_pause_job to switch back, wait for the hardware card encryption to complete and call ASYNC_start_job to switch back to continue Execute to achieve asynchronous, is this use not allowed in aes-ctr and aes-ecb?

**Comment by hijj** [comment]
> What I want to express is exactly AES-CTR and AES-ECB in CTR-DRBG. Currently, the openssl asynchronous coroutine mechanism is used, and the aes-ctr algorithm is registered through the opened openssl ENGINE, and the aes-ctr encryption is handed over to the hardware encryption card to do it, and then call ASYNC_pause_job to switch back, wait for the hardware card encryption to complete and call ASYNC_start_job to switch back to continue Execute to achieve asynchronous, is this use not allowed in aes-ctr and aes-ecb?

What I want to express is exactly AES-CTR and AES-ECB in CTR-DRBG. Currently, the openssl asynchronous coroutine mechanism is used, and the aes-ctr algorithm is registered through the opened openssl ENGINE, and the aes-ctr encryption is handed over to the hardware encryption card to do it, and then call ASYNC_pause_job to switch back, wait for the hardware card encryption to complete and call ASYNC_start_job to switch back to continue Execute to achieve asynchronous, is this use not allowed in aes-ctr and aes-ecb?

**Comment by paulidale** [comment]
I don't see why it would not work.  There might be a conflict if simultaneous attempts are made to use the cipher but the engine should handle this.

**Comment by hijj** [comment]
> I don't see why it would not work. There might be a conflict if simultaneous attempts are made to use the cipher but the engine should handle this.

openssl1.1.1l：
I'm guessing there might be the following(Suppose there is only one thread)：

async_job1:  EVP_CipherInit(public_drbg->data.ctr， )  --》 EVP_CipherUpdate(public_drbg->data.ctr) --> ASYNC_pause_job() 
async_job2:   EVP_CipherInit(public_drbg->data.ctr， )  --》 EVP_CipherUpdate(public_drbg->data.ctr)                                                                                                                  

When using EVP_CipherInit in async_job2, since async_job1 is still returning asynchronously from EVP_CipherUpdata, public_drbg->data.ctr is reinitialized, which should not be perceived in ENGINE?

**Comment by paulidale** [comment]
That will be a problem.  I still think the engine shouldn't let the second encrypt start while the first is outstanding.

**Comment by hijj** [comment]
> That will be a problem. I still think the engine shouldn't let the second encrypt start while the first is outstanding.

async_job1 and async_job2 correspond to two SSL connections. I understand that SSL asynchronous coroutines allow this operation. per thread variable and coroutine seem to be naturally incompatible

**Comment by paulidale** [comment]
Yes they are problematic.  In 3.0, enabling locking on the DRBG will somewhat address this but there is likely a deadlock risk.

@mattcaswell, any thoughts here?

**Comment by kaduk** [comment]
> async_job1: EVP_CipherInit(public_drbg->data.ctr， ) --》 EVP_CipherUpdate(public_drbg->data.ctr) --> ASYNC_pause_job()

While the public DRBG is accessible via `RAND_get0_public()`, its internal counter state is not.
Shouldn't it be the case that the only ways to access the counter are via full-fledged RAND requests that complete their use of it synchronously, providing no opportunity for the `ASYNC_pause_job()` call to intervene?

**Comment by paulidale** [comment]
It's the engine that calling ASYNC_pause_job I think.

**Comment by kaduk** [comment]
Right, but what's the call path into the library that engages EVP_CipherInit without subsequent EVP_CipherFinal, on the public DRBG data?

**Comment by paulidale** [comment]
There won't be one.

The DRBG needs AES-CTR, and calls EVP_CIpherInit.  During this the engine triggers a context switch.  The next coroutine does the same thing.

**Comment by kaduk** [comment]
Oh, this is where the engine is doing the AES for the DRBG, got it.
Sorry for the noise.

**Comment by mattcaswell** [comment]
The DRBG should probably be calling `ASYNC_block_pause`

**Comment by paulidale** [comment]
That would set a bad precedent -- the DRBG is ours.

We don't call this in any other operation that might go to an engine and have the same problem.

**Comment by mattcaswell** [comment]
The `ASYNC_block_pause` API exists for precisely this type of reason. We used to call it from the old DRBG in 1.1.0:

https://github.com/openssl/openssl/blob/a3b54f0f5de1ad17889fd23aee7c230eefc300cd/crypto/rand/md_rand.c#L349-L354

**Comment by paulidale** [comment]
Our DRBGs typically aren't locked anymore, so the reason in the comment isn't valid anymore.  Still, there is a problem but I'm concerned that we're not at all good at stopping coroutine switches.  For example, we don't call it in the digest & sign operations which will have exactly the same problem.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
