### ISSUE TITLE
Add fallback in `try_key_ref` to fetch the keymgmt from the provider of the store

### ISSUE THREAD

**Issue by manison** [openssl/openssl#17531]
The `try_key_ref` function tries to transform data from the store into the `EVP_PKEY`. It first looks up a keymgmt that can handle the data type returned from the store given by the `OSSL_OBJECT_PARAM_DATA_TYPE` param. It then depends on the order of providers - first one that can handle the data type is selected. It is not necessarily the one that actually provided the data. When this is the case the function tries to export the key from the provider that actually provided it and import it into the selected provider. This will fail if the private key cannot be exported.

https://github.com/openssl/openssl/blob/144316d276adf5b8172316f7bc20b372b8e31ac8/crypto/store/store_result.c#L186-L239

A fallback in the `try_key_ref` needs to be added to try to fetch the keymgmt from the provider of the store if the key is unexportable.

**Comment by t8m** [comment]
Please try #17554

**Comment by manison** [comment]
I tried the changes from the PR but they don't work. Not because an issue with the PR itself but because is doesn't kick in at all.

The scenario is as follows:
1. I want to sign a CMS (`openssl cms -sign -signer myprov:cert=1234`)
2. OpenSSL fetches the signer's certificate from my provider's store.
3. OpenSSL fetches signer's private key from my provider's store (store's expectation is `OSSL_STORE_INFO_PKEY`).
4. I return private key from the provider by reference (`OSSL_OBJECT_PARAM_REFERENCE`).
5. `try_key_ref` looks for keymgmt that can interpret the key's data type (`OSSL_OBJECT_PARAM_DATA_TYPE`).
6. The default provider is found first and my provider is then asked to export everything about the key (`OSSL_KEYMGMT_SELECT_ALL`).
7. My provider exports everything but the private key (since it's not exportable).
8. `try_key_ref` is happy because it has `EVP_PKEY` from the default provider. The fallback implemented in the PR does not kick in since a `PKEY` has been created. It contains only the public part though.
9. Store queries the created `EVP_PKEY` and enqueues the `OSSL_STORE_INFO_PUBKEY`, not the expected `OSSL_STORE_INFO_PKEY`.
10. Boom! Store expectation is not met, private key loading fails.

Maybe my export is bad (point 7). My understanding of `OSSL_KEYMGMT_SELECT_ALL` was _give me all you CAN_. But maybe is should be interpreted rather as _you MUST give me all I'm asking for_. But this interpretation would be IMHO bad for future extension. Should I fail if I can't provide private key? Should I also fail if I can't provide `OSSL_KEYMGMT_SELECT_OTHER_PARAMETERS`? What is it anyway? The documentation says that these flags _should be_ (not _must be_) considered, so I think my interpretation of NOT providing the private key AND NOT failing the export is correct.

I think the idea of choosing ANY provider that can interpret the key data (point 5) and completely ignoring the reference at that point is flawed. When a key is returned by a reference then it is the provider that issued the reference and that provider only can interpret it.

**Comment by t8m** [comment]
Your export is bad. You should fail the export if OSSL_KEYMGMT_SELECT_ALL is set, the key **has** a private key data and you're unable to export it. If there are no **other parameters** with the key type then you can ignore that selection bit. The same for **domain parameters** - if a key such as an RSA key does not have any **domain parameters**. Maybe the manual page should be clarified. Feel free to suggest better wording for it as a PR.

However you have a good point in that last paragraph that maybe the order of the tried key managements should be inverted. @levitte what is your opinion? It seems to me, this is a little bit different situation than with the operation fallbacks because here  is no point in trying to export the key to a different provider prematurely.

**Comment by manison** [comment]
OK, so I modified my export as told and this time the fallback kicks in and the `EVP_PKEY` is constructed from my provider. So far so good (although the export is first tried unnecessarily).

I believe in this case loading public keys from the store might be broken. When the store's expectation is set to `OSSL_STORE_INFO_PUBKEY` and we get there, then the export is only tried with `OSSL_KEYMGMT_SELECT_ALL`. So although the provider could export the public key, it has to fail since it is instructed to export the complete keypair.

I also see asymmetry in export and import semantics. The export is told to fail for unexportable private keys when `OSSL_KEYMGMT_SELECT_PRIVATE_KEY` is present and on the other hand the import is OK when `OSSL_KEYMGMT_SELECT_PRIVATE_KEY` is present but the imported data does not contain private key data.

There's one more thing that needs clarification. In my previous description I was not accurate when describing the export (point 6):

> The default provider is found first and my provider is then asked to export everything about the key (OSSL_KEYMGMT_SELECT_ALL).

It's not the provider's keymgmt that is asked to export, it is actually the provider's store to do the export (store's `store_export_object` function). And there is no selection bitmask specified, it is me who delegates the export object call to provider's keymgmt `export` function with `OSSL_KEYMGMT_SELECT_ALL` selection. Is this correct? Should store's expectation be consulted eventually?

But back to my initial problem with CMS signing. Once the private key is now successfully loaded from my provider it is then passed to `CMS_add1_signer`. That in turn calls `X509_check_private_key`. Now we are in `evp_keymgmt_util_match` and since my provider does not implement the `match` function the attempt to export key from my provider and import it into the default provider is made (#17487 must be applied). The export is tried with `OSSL_KEYMGMT_SELECT_PRIVATE_KEY` and it now obviously fails. For matching signer's certificate with a private key public keys should be sufficient (and it worked before I modified my export).

**Comment by manison** [comment]
> I think it would actually make sense to consult the expectation in this case.

It might be. But what to do in case the expectation is not set (either because it really has not been set or it could not be set because multiple different types are expected)? Probably export as much as I can?
