### ISSUE TITLE
Building static fails

### ISSUE THREAD

**Issue by Timpy123** [openssl/openssl#17534]
# steps to reproduce:
./Configure  --static
make
<snip>
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

**Comment by mattcaswell** [comment]
Use `Configure no-shared` instead.

**Comment by Timpy123** [comment]
Tried it.:
gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -L. -Wl,-z,defs -Wl,-znodelete -shared -Wl,-Bsymbolic   \
        -o providers/legacy.so -Wl,--version-script=providers/legacy.ld \
        providers/legacy-dso-legacyprov.o \
        providers/liblegacy.a providers/libcommon.a -lcrypto -ldl -pthread 
providers/liblegacy.a(liblegacy-lib-pbkdf1.o): In function `kdf_pbkdf1_free':
pbkdf1.c:(.text+0x7a): undefined reference to `ossl_prov_digest_reset'
providers/liblegacy.a(liblegacy-lib-pbkdf1.o): In function `kdf_pbkdf1_reset':
pbkdf1.c:(.text+0x192): undefined reference to `ossl_prov_digest_reset'
providers/liblegacy.a(liblegacy-lib-pbkdf1.o): In function `kdf_pbkdf1_set_ctx_params':
pbkdf1.c:(.text+0x20d): undefined reference to `ossl_prov_digest_load_from_params'
providers/liblegacy.a(liblegacy-lib-pbkdf1.o): In function `kdf_pbkdf1_derive':
pbkdf1.c:(.text+0x422): undefined reference to `ossl_prov_digest_md'
providers/liblegacy.a(liblegacy-lib-pvkkdf.o): In function `kdf_pvk_free':
pvkkdf.c:(.text+0x6e): undefined reference to `ossl_prov_digest_reset'
providers/liblegacy.a(liblegacy-lib-pvkkdf.o): In function `kdf_pvk_new':
pvkkdf.c:(.text+0x183): undefined reference to `ossl_prov_digest_load_from_params'
pvkkdf.c:(.text+0x1a4): undefined reference to `ossl_prov_digest_reset'
providers/liblegacy.a(liblegacy-lib-pvkkdf.o): In function `kdf_pvk_reset':
pvkkdf.c:(.text+0x206): undefined reference to `ossl_prov_digest_reset'
pvkkdf.c:(.text+0x2b7): undefined reference to `ossl_prov_digest_load_from_params'
pvkkdf.c:(.text+0x2c3): undefined reference to `ossl_prov_digest_reset'
providers/liblegacy.a(liblegacy-lib-pvkkdf.o): In function `kdf_pvk_set_ctx_params':
pvkkdf.c:(.text+0x2f6): undefined reference to `ossl_prov_digest_load_from_params'
providers/liblegacy.a(liblegacy-lib-pvkkdf.o): In function `kdf_pvk_derive':
pvkkdf.c:(.text+0x4c4): undefined reference to `ossl_prov_digest_load_from_params'
pvkkdf.c:(.text+0x5c5): undefined reference to `ossl_prov_digest_md'
collect2: error: ld returned 1 exit status
Makefile:12904: recipe for target 'providers/legacy.so' failed
make[1]: *** [providers/legacy.so] Error 1
make[1]: Leaving directory '/usr/src/openssl'
Makefile:2582: recipe for target 'build_sw' failed
make: *** [build_sw] Error 2
This was solved by first doing a make clean. Probably obvious, but might still indicate some missing logic in the Makefile. It builds fine after the clean. Thanks for the answer.

**Comment by MohammedZwayen** [comment]
I tried this and worked :

./Configure --prefix=/home/build/openssl --openssldir=/home/build/openssl/ssl --libdir=lib --with-zlib-lib=/home/build/zlib/lib --with-zlib-include=/home/build/zlib/include --static -static
make 
make install

and got this output :
build/openssl> tree -L 2
.
├── bin
│   ├── c_rehash
│   └── openssl
├── include
│   └── openssl
├── lib
│   ├── engines-3
│   ├── libcrypto.a
│   ├── libssl.a
│   ├── ossl-modules
│   └── pkgconfig
├── share
│   ├── doc
│   └── man
└── ssl
    ├── certs
    ├── ct_log_list.cnf
    ├── ct_log_list.cnf.dist
    ├── misc
    ├── openssl.cnf
    ├── openssl.cnf.dist
    └── private

but you are totally right **no-shared** is never worked with me. I hope some one can clarify the perfect config if I did it wrong
