### ISSUE TITLE
openssl-1.1 -- zlib-dynamic on Windows with no --with-zlib-lib argument causes problems.

### ISSUE THREAD

**Issue by dbroady1** [openssl/openssl#1753]
Commit 5a5c0b953f8f97b4e604da494a65de034bbaaceb introduced a new way to load zlib, allowing for the possibility of the user configuring a different name for the library, via --with-zlib-lib.  Supposed, if --with-zlib-lib is not specified, it will fall back to using the defaults of zlib1 on Windows, libz on VMS and z on Unix.  These defaults are only activated if the preprocessor symbol LIBZ is not defined.  However, on the Windows platform, per 10-main.conf lines 1254-1277, it unconditionally sets the LIBZ variable to the empty string "" is zlib-dynamic is set, but --with-zlib-lib is not set.  This means that openssl will attempt to load a library named ".dll" to get zlib code.

There are 2 ways to "fix this":
1.  Workaround -- always require --with-zlib-lib with zlib-dynamic on Windows.
2.  Change 10-main.conf to check for an empty $withargs{zlib_lib} and not define LIBZ is it's empty.

**Comment by levitte** [comment]
Actually, for VMS, the default is found in `Cofnigurations/10-main.conf`...  anyway, you're right, the way this is done on Windows is clumsy.  Also, I just noticed that `ex_libs` remains unaffected if OpenSSL is configure with the `zlib` option, which is equally bad.

So, thinking about it now, I think we should mimic the way it's done for VMS, i.e. have `vc_win32_info()` et al provide the proper info.

**Comment by levitte** [comment]
Please check out #1772

**Comment by dot-asm** [comment]
Since https://github.com/openssl/openssl/pull/1772 is closed, I suppose this should be closed too.
