### ISSUE TITLE
Same BIO_flags macro definition

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#17545]
https://github.com/openssl/openssl/blob/15b7175f558bf9eb057ec3266685486f727dd70f/include/internal/bio.h#L51
https://github.com/openssl/openssl/blob/15b7175f558bf9eb057ec3266685486f727dd70f/include/openssl/bio.h.in#L210

**Comment by t8m** [comment]
This seems like a fairly bad bug. Thank you for finding it. Having internal and public flags sharing the same value space is totally error prone.

**Comment by yangyangtiantianlonglong** [comment]
> This seems like a fairly bad bug. Thank you for finding it. Having internal and public flags sharing the same value space is totally error prone.

My work benefits from OpenSSL and I hope to make some contributions to the development of OpenSSL.

**Comment by neverpanic** [comment]
FYI, this fixes a memory leak in ssl3_setup_write_buffer that seems to occur when connections are closed without a complete handshake.

See https://bugzilla.redhat.com/show_bug.cgi?id=2134754, https://bugzilla.redhat.com/show_bug.cgi?id=2128412 and https://github.com/acassen/keepalived/issues/2199, which are reports of this problem.
