### ISSUE TITLE
Wrong Return Type for BIO_ptr_ctrl

### ISSUE THREAD

**Issue by Thomas1664** [openssl/openssl#17549]
The return type of `BIO_ptr_ctrl` is according to every version of the [documentation](https://www.openssl.org/docs/man1.1.1/man3/BIO_ctrl.html) `char*`. However, in the header file (`bio.h`), the return type is `void*` (at least on `master` and in version 1.1.1).

**Comment by faramir-dev** [comment]
I will take a look, it looks there is already a commit with a change in the documentation.

**Comment by t8m** [comment]
@Thomas1664 Did you want to submit your patch as a PR?

**Comment by Thomas1664** [comment]
> @Thomas1664 Did you want to submit your patch as a PR?
> 

Yes but I didn't include that no cla is required in the commit message

**Comment by t8m** [comment]
You can fix that with `git commit --amend` and `git push --force`.

**Comment by Thomas1664** [comment]
> You can fix that with `git commit --amend` and `git push --force`.
> 

@t8m Thanks. You will receive my PR in the next hours!
