### ISSUE TITLE
openssl base64: decode URL safe Base64

### ISSUE THREAD

**Issue by stokito** [openssl/openssl#17559]
Currently the base64 util can't  parse base64 url safe. But basically this is the same encoding just two symbols are differs and no any padding. So it's easy and safe just to parse both forms.
The coreutils have a separate command `basenc --base64url` to parse the b64u but actually there is no any sense to make it as a separate command.

Currently **many** shell scripts uses additional transformation like:

```sh
base64_padding()
{
  local len=$(( ${#1} % 4 ))
  local padded_b64=''
  if [ ${len} = 2 ]; then
    padded_b64="${1}=="
  elif [ ${len} = 3 ]; then
    padded_b64="${1}="
  else
    padded_b64="${1}"
  fi
  echo -n "$padded_b64"
}

base64url_to_b64()
{
  base64_padding "${1}" | tr -- '-_' '+/'
}
```

But this over complicates everything, reduces performance and error prone.

**Comment by stokito** [comment]
If you confirm that the feature make sense then I can send a PR with an implementation.

**Comment by paulidale** [comment]
I'm leaning towards having this as a separate function rather than blindly doing either format.
What does the rest of the @openssl/otc think?

**Comment by stokito** [comment]
Having it as a separate function (i.e. flag?) is a good thing to do for a better correctness. Still many unexpirienced users will not fail just because they copied a first answer on SO. This makes the feature much less useful. Especially the big problem is that some base64 data may be decoded successfully during a development and testing and the code with bugs may be delivered to end users. Again, this is a very widely used tool.

**Comment by stokito** [comment]
I created a similar ticked for coreutils base64 https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53400

**Comment by stokito** [comment]
I sent a proposition to coreutils base64 to add a new flag. But anyway even now the = padding don't  break decoding and just sets an error code that may be ignored. The +/ symbols can be easily replaced so I don't think anymore that this is a really important issue.
I close the ticket but if coreutils will decide to support bade64url I'll send a pr to the openssl b64 too.
Thank you
