### ISSUE TITLE
Software vulnerabilities detected during code analysis with ESBMC-WR tool

### ISSUE THREAD

**Issue by janislley** [openssl/openssl#17560]
Hello,

3 potential software vulnerabilities were found in code.
To identify this kind of vulnerabilities I used tool ESBMC-WR: https://github.com/thalestas/esbmc-wr

More about the tool: https://arxiv.org/pdf/2102.02368.pdf

**Expected behaviour:**

Our main objective was to check memory safety
properties (e.g., pointer dereference and memory leaks) while
performing the verification code.

**Please, check the logs of analysis:**

[FILE] crypto/poly1305/poly1305_ieee754.c

State 1 file poly1305_ieee754.c line 227 function poly1305_blocks thread 0
----------------------------------------------------
st = ( poly1305_internal *)(invalid-object)

State 20 file poly1305_ieee754.c line 314 function poly1305_blocks thread 0
----------------------------------------------------
Violated property:
file poly1305_ieee754.c line 314 function poly1305_blocks
dereference failure: invalid pointer

**Comment by paulidale** [comment]
What version/git tag did you check against?

Line 314 looks harmless: https://github.com/openssl/openssl/blob/5288303da96084b41b062d99eb37177fb4cf471e/crypto/poly1305/poly1305_ieee754.c#L313-L318

**Comment by janislley** [comment]
Hello @paulidale 
Thanks for the reply and analysis.

We checked in version 3.1. Same as you already shared.
For dereference failure: invalid pointer, we would like your support to check line 227:

`poly1305_internal *st = (poly1305_internal *)ctx;`

BR.

**Comment by paulidale** [comment]
Line 227 isn't dereferencing anything.  `st` is de-referenced later, which will likely crash the caller but we don't consider this to be a vulnerability -- lots of the OpenSSL APIs crash if passed a null pointer.

I think I'm missing something here.

**Comment by janislley** [comment]
Hello @t8m 
Sorry for the long delay.

About the issues. Follow more evidences:

**Issue #1: file crypto/poly1305/poly1305_ieee754.c:** 

State 1 file poly1305_ieee754.c line 227 function poly1305_blocks thread 0
----------------------------------------------------
st = ( poly1305_internal *)(invalid-object)

State 20 file poly1305_ieee754.c line 314 function poly1305_blocks thread 0
----------------------------------------------------
Violated property:
file poly1305_ieee754.c line 314 function poly1305_blocks
dereference failure: invalid pointer

This issue comes from code:

> static void poly1305_emit(void *ctx, unsigned char mac[16],
>                           const u32 nonce[4])
> {
>     poly1305_internal *st = (poly1305_internal *) ctx;

**Could you please confirm if the implementation of ctx variable is okay?**

**Comment by t8m** [comment]
I do not see any new information in your message above. What @paulidale wrote above still applies.
