### ISSUE TITLE
new architecture

### ISSUE THREAD

**Issue by Mrsclong** [openssl/openssl#17561]
I want to add a performance optimization about the loongarch architecture to the openssl algorithm library, and the optimization results are remarkable. Is it possible?

**Comment by paulidale** [comment]
This is definitely possible and desirable from the project's viewpoint.
We don't back port such changes but it would be included in minor/major releases going forwards.

You need to raise a pull request with the changes so it can be reviewed.  You will also need to send us a signed [CLA](https://www.openssl.org/policies/cla.html) (and possibly your employer will too).

**Comment by Mrsclong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        May i use apache's cla?
        
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                shichenlong
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 01/21/2022 ***@***.***> wrote： 



This is definitely possible and desirable from the project's viewpoint.
We don't back port such changes but it would be included in minor/major releases going forwards.
You need to raise a pull request with the changes so it can be reviewed.  You will also need to send us a signed CLA (and possibly your employer will too).

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by paulidale** [comment]
No, you must sign our CLA.  OpenSSL is not part of the Apache Foundation.  Our CLA almost identical to Apache's.
