### ISSUE TITLE
Best way to force an engine to be loaded by default?

### ISSUE THREAD

**Issue by mlindgren** [openssl/openssl#17566]
Hi,
My team is building [an OpenSSL engine](https://github.com/microsoft/SymCrypt-OpenSSL) which we want to be used by default for **all** applications running on a custom Linux distribution. We're currently using OpenSSL 1.1.1. Initially we tried to accomplish this by adding the engine to openssl.cnf, but that didn't work for applications which only use libcrypto, because auto-initialization does not call `OPENSSL_init_crypto` with `OPENSSL_INIT_LOAD_CONFIG`. Instead, we found that in order to reliably load our engine for all OpenSSL callers, we had to patch `OPENSSL_init_crypto` as shown in [this Gist](https://gist.github.com/mlindgren/89403ed7e666c423ce8d95384882eee5). However, we're somewhat concerned about the maintainability of this approach.

My questions are:
1. Is there a better way to do this in OpenSSL 1.1.1?
2. Is/will there be a better way to do this with the OpenSSL 3.0 provider model?
3. If not, is this something that could be considered for upstreaming, possibly as a compile-time option allowing the user to specify which custom engine(s) to load by default?

Thanks!

**Comment by paulidale** [comment]
You can do this via configuration: https://www.openssl.org/docs/man1.1.1/man5/config.html

**Comment by paulidale** [comment]
Configuration is the recommended way to do what you want.  3.0 loads providers in a similar manner -- via configuration.

I doubt we'd consider adding an option to load an engine via a compile time option.  A provider, perhaps.

**Comment by mlindgren** [comment]
Thanks. But config files don't work for applications which only use libcrypto and not libssl, unless the application is changed to manually call `OPENSSL_init_crypto` with the appropriate flags, which we may not have control over. Am I wrong about that? If not, is that changing in 3.0?

**Comment by paulidale** [comment]
3.0 should load the config automatically.

**Comment by mattcaswell** [comment]
> Thanks. But config files don't work for applications which only use libcrypto and not libssl, unless the application is changed to manually call OPENSSL_init_crypto with the appropriate flags, which we may not have control over. Am I wrong about that?

You are correct. Libssl applications will load the config file automatically, but libcrypto ones do not in 1.1.1.

> If not, is that changing in 3.0?

Yes. The config file always loads automatically in 3.0.

**Comment by mlindgren** [comment]
I tested this on my end and confirms that it works the way we need it to in 3.0. Thanks!
