### ISSUE TITLE
The Maximum Fragment Length extension support is not optional on the server side

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#17573]
1. https://github.com/openssl/openssl/blob/master/doc/man3/SSL_CTX_set_split_send_fragment.pod#notes
_**The Maximum Fragment Length extension support is optional on the server side.** If the server does not support this extension then SSL_SESSION_get_max_fragment_length() will return: TLSEXT_max_fragment_length_DISABLED._

    **issue:**  TLSEXT_max_fragment_length_DISABLED  is invalid on the server side.

2. https://www.rfc-editor.org/rfc/rfc6066.txt  
   _If a server receives a maximum fragment length negotiation request
   for a value other than the allowed values, it MUST abort the
   handshake with an "illegal_parameter" alert.  Similarly, **if a client
   receives a maximum fragment length negotiation response that differs
   from the length it requested**, it MUST also abort the handshake with
   an "illegal_parameter" alert._

   **issue:** client always receives a maximum fragment length negotiation response that same from the length it requested.

**Comment by mattcaswell** [comment]
Whether a server supports the RFC 6066 max_fragment_length *at all* is optional. There is nothing which says RFC6066 *must* be supported. *If* the server chooses to support it *then* it must behave in accordance with the requirements of RFC6066.

**Comment by yangyangtiantianlonglong** [comment]
@mattcaswell  Thank you for your reply

You mean that OpenSSL does not support RFC6066 max_fragment_length on the server? I read this comment and thought that OpenSSL supports RFC6066 max_fragment.
https://github.com/openssl/openssl/blob/44a563dde1584cd9284e80b6e45ee5019be8d36c/ssl/statem/extensions_srvr.c#L183-L187

**Comment by bernd-edlinger** [comment]
The server must explicitly allow this extension.
Start the server with `-max_send_frag X` where 512 <= X <= 4096
`$ ../util/shlib_wrap.sh ./openssl s_server -max_send_frag 4096`

**Comment by yangyangtiantianlonglong** [comment]
> The server must explicitly allow this extension.
> Start the server with -max_send_frag X where 512 <= X <= 4096
> $ ../util/shlib_wrap.sh ./openssl s_server -max_send_frag 4096

@bernd-edlinger   
sorry, I didn't understand what you said.  That does not affect the `Extension: max_fragment_length` shown below.
```
TLSv1.2 Record Layer: Handshake Protocol: Client Hello
    Content Type: Handshake (22)
    Version: TLS 1.0 (0x0301)
    Length: 194
    Handshake Protocol: Client Hello
        Handshake Type: Client Hello (1)
        Length: 190
        Version: TLS 1.2 (0x0303)
        Random: b9888a9a2fe067d643a090ae9ca53d10654fa9013f677ab214753824f7e56da0
        Session ID Length: 0
        Cipher Suites Length: 56
        Cipher Suites (28 suites)
        Compression Methods Length: 1
        Compression Methods (1 method)
        Extensions Length: 93
        Extension: max_fragment_length (len=1)
            Type: max_fragment_length (1)
            Length: 1
            Maximum Fragment Length: 512 (1)
        Extension: ec_point_formats (len=4)
            Type: ec_point_formats (11)
            Length: 4
            EC point formats Length: 3
            Elliptic curves point formats (3)
        Extension: supported_groups (len=12)
            Type: supported_groups (10)
            Length: 12
            Supported Groups List Length: 10
            Supported Groups (5 groups)
        Extension: session_ticket (len=0)
            Type: session_ticket (35)
            Length: 0
            Data (0 bytes)
        Extension: encrypt_then_mac (len=0)
            Type: encrypt_then_mac (22)
            Length: 0
        Extension: extended_master_secret (len=0)
            Type: extended_master_secret (23)
            Length: 0
        Extension: signature_algorithms (len=48)
            Type: signature_algorithms (13)
            Length: 48
            Signature Hash Algorithms Length: 46
            Signature Hash Algorithms (23 algorithms)
```

**Comment by yangyangtiantianlonglong** [comment]
> SSL_CTX_set_tlsext_max_fragment_length() sets the default maximum fragment length negotiation mode via value mode to ctx. This setting affects only SSL instances created after this function is called. It affects the client-side as only its side may initiate this extension use.

**issue：** How to disable the `Extension: max_fragment_length` , that shown below on the server side?
```
 TLSv1.2 Record Layer: Handshake Protocol: Server Hello
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 70
        Handshake Protocol: Server Hello
            Handshake Type: Server Hello (2)
            Length: 66
            Version: TLS 1.2 (0x0303)
            Random: cda918996ff1cf54674858add533fcfefdd62e0be95b18ff444f574e47524401
            Session ID Length: 0
            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
            Compression Method: null (0)
            Extensions Length: 26
            Extension: renegotiation_info (len=1)
                Type: renegotiation_info (65281)
                Length: 1
                Renegotiation Info extension
            Extension: max_fragment_length (len=1)
                Type: max_fragment_length (1)
                Length: 1
                Maximum Fragment Length: 512 (1)
            Extension: ec_point_formats (len=4)
                Type: ec_point_formats (11)
                Length: 4
                EC point formats Length: 3
                Elliptic curves point formats (3)
            Extension: session_ticket (len=0)
                Type: session_ticket (35)
                Length: 0
                Data (0 bytes)
            Extension: extended_master_secret (len=0)
                Type: extended_master_secret (23)
                Length: 0
    TLSv1.2 Record Layer: Handshake Protocol: Certificate (fragment)
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 512
        Handshake Protocol: Certificate (fragment)
        Reassembled Handshake Message in frame: 6
    TLSv1.2 Record Layer: Handshake Protocol: Certificate
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 307
        Handshake Protocol: Certificate (last fragment)
        [2 Reassembled Handshake Fragments (819 bytes): #6(512), #6(307)]
        Handshake Protocol: Certificate
            Handshake Type: Certificate (11)
            Length: 815
            Certificates Length: 812
            Certificates (812 bytes)
    TLSv1.2 Record Layer: Handshake Protocol: Server Key Exchange
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 300
        Handshake Protocol: Server Key Exchange
            Handshake Type: Server Key Exchange (12)
            Length: 296
            EC Diffie-Hellman Server Params
    TLSv1.2 Record Layer: Handshake Protocol: Server Hello Done
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 4
        Handshake Protocol: Server Hello Done
            Handshake Type: Server Hello Done (14)
            Length: 0

```

**Comment by mattcaswell** [comment]
> You mean that OpenSSL does not support RFC6066 max_fragment_length on the server?

No. What I mean is that when OpenSSL as a client talks to a server and sends the max_fragment_length extension then it has to be able to deal with the situation where a server does not support that extension. This is what this text in the docs is referring to:

"The Maximum Fragment Length extension support is optional on the server side"

So just because you call `SSL_CTX_set_tlsext_max_fragment_length` on the client it does not mean that a server will honour it.

OpenSSL from 1.1.1 onwards *does* support max_fragment_length on the server. If the client requests it then the server will honour it. You cannot disable this.

> The server must explicitly allow this extension.
Start the server with -max_send_frag X where 512 <= X <= 4096

This is not correct. The server does not need to explicitly allow the extension. It is always available if the client requests it. The "max_send_frag" option has a different purpose and does not (directly) impact the "max_fragment_length" extension.

**Comment by yangyangtiantianlonglong** [comment]
> OpenSSL from 1.1.1 onwards does support max_fragment_length on the server. If the client requests it then the server will honour it. You cannot disable this.

ok, I see that. 

> What I mean is that when OpenSSL as a client talks to a server and sends the max_fragment_length extension then it has to be able to deal with the situation where a server does not support that extension. This is what this text in the docs is referring to:
> "The Maximum Fragment Length extension support is optional on the server side"

The OpenSSL document states that the behavior of the OpenSSL server is not the behavior of the OpenSSL server. It may only be a document issue. But I'm not going to force the issue.
