### ISSUE TITLE
EVP_PKEY_size() == RSA_size() for RSA keys ?

### ISSUE THREAD

**Issue by selvanair** [openssl/openssl#17570]
For RSA-PSS signature with saltlen="max" one would have calculated the saltlen as `RSA_size(rsa) - hashlen - 2` [*]. As RSA_size() is deprecated, is it safe to replace it with `EVP_PKEY_get_size(pkey)` ? 

Asking this because the docs seem to indicate that `EVP_PKEY_get_size()` could be larger than the minimum required number of bytes. If its over-estimated, the resulting saltlen calculation will be off. An option would be to compute the number of bytes from EVP_PKEY_get_bits(), but trying to keep the old logic. This is for use when signing with external keys.

---
[*] And an extra -1 if (modBits-1) is a multiple of 8

**Comment by t8m** [comment]
I'd follow the manual page definition of these two functions and rather use the `(EVP_PKEY_get_bits() + 7) / 8` value. As the EVP_PKEY_get_size() does not guarantee the size would be exact. Yeah, the `EVP_PKEY_get_bits()` value is also defined only for the concrete algorithm but here the algorithm is RSA by definition so the value is fairly cleanly defined as the number of bits of N.
