### ISSUE TITLE
Unhandled critical CRL extensions not detected if they appear after the handled ones

### ISSUE THREAD

**Issue by john-chuah** [openssl/openssl#1757]
The following line should be a 'continue' rather than 'break': 
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/asn1/x_crl.c#L266

Otherwise, unhandled critical CRL extensions that appear after any of the currently supported ones would slip through the check.

**Comment by richsalz** [comment]
fixed with commit 3ade92e.  thanks.

**Comment by john-chuah** [comment]
No problem. Will it be ported to 1.0.1-stable too?

**Comment by richsalz** [comment]
Only if you can make the argument that it is a security bug.  1.0.1 goes out of service at the end of 2016 as well.
