### ISSUE TITLE
Regression on PPC64LE cross-compilation build

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#17588]
The regression happened after merging #16854 
There are breakages in evp_test with aes-128-gcm and also in ssl tests with aes-256-gcm ciphers.
See https://github.com/openssl/openssl/runs/4915736203?check_suite_focus=true

@dannytsen can you please look?

**Comment by t8m** [comment]
Unless this is resolved quickly we would have to revert.

**Comment by dannytsen** [comment]
@t8m I'll take a look.

**Comment by dannytsen** [comment]
@t8m The failure looks strange.  In evp_test with aes-128-gcm,it failed in these instances with the mismatched last byte.  I have no clues at this point and have to look into it further.

        # aes-128-gcm is fetched
        # ERROR: (memory) 'expected == got' failed @ test/evp_test.c:108
        # --- expected
        # +++ got
        # 0000: 56b3373ca9ef6e4a 2b64fe1e9a17b614 25f10d47a75a5fce 13efc6bc784af24f
        # 0020: 4141bdd48cf7c770 887afd573cca5418 a9aeffcd7c5ceddf c6a78397b9a85b49
        # 0040: 9da558257267caab 2ad0b23ca476a53c b17fb41c4b8b475c b4f3f7165094c229
        # 0060: c9e8c4dc0a2a5ff1 903e501511221376 a1cdb8364c5061a2 0cae74bc4acd76ce
        # 0080: b0abc9fd3217ef9f 8c90be402ddf6d86 97f4f880dff15bfb 7a6b28241ec8fe18
        # 00a0:-3c2d59e3f9dfff65 3c7126f0acb9e642 11f42bae12af462b 1070bef1ab5e3606
        # 00a0:+3c2d59e3f9dfff65 3c7126f0acb9e642 11f42bae12af462b 1070bef1ab5e3625
        #                                                                        ^^
        # 
        # INFO:  @ test/evp_test.c:3365
        # ../../test/recipes/30-test_evp_data/evpciph_aes_common.txt:860: Source of above error (aligned in-place, fragmented); unexpected error VALUE_MISMATCH
        # INFO:  @ test/evp_test.c:589
        # aes-128-gcm is fetched
        # ERROR: (memory) 'expected == got' failed @ test/evp_test.c:108
        # --- expected
        # +++ got
        # 0000: 56b3373ca9ef6e4a 2b64fe1e9a17b614 25f10d47a75a5fce 13efc6bc784af24f
        # 0020: 4141bdd48cf7c770 887afd573cca5418 a9aeffcd7c5ceddf c6a78397b9a85b49
        # 0040: 9da558257267caab 2ad0b23ca476a53c b17fb41c4b8b475c b4f3f7165094c229
        # 0060: c9e8c4dc0a2a5ff1 903e501511221376 a1cdb8364c5061a2 0cae74bc4acd76ce
        # 0080: b0abc9fd3217ef9f 8c90be402ddf6d86 97f4f880dff15bfb 7a6b28241ec8fe18
        # 00a0: 3c2d59e3f9dfff65 3c7126f0acb9e642 11f42bae12af462b 1070bef1ab5e3606
        # 00c0: 872ca10dee15b324 9b1a1b958f23134c 4bccb7d03200bce4 20a2f8eb66dcf364
        # 00e0:-4d1423c1b5699003 c13ecef4bf38a3b6
        # 00e0:+4d1423c1b5699003 c13ecef4bf38a325
        #                                      ^^
        # 
        # INFO:  @ test/evp_test.c:3365
        # ../../test/recipes/30-test_evp_data/evpciph_aes_common.txt:869: Source of above error (aligned in-place, fragmented); unexpected error VALUE_MISMATCH
        # INFO:  @ test/evp_test.c:589
        # aes-128-gcm is fetched
        # ERROR: (memory) 'expected == got' failed @ test/evp_test.c:108
        # --- expected
        # +++ got
        # 0000: 56b3373ca9ef6e4a 2b64fe1e9a17b614 25f10d47a75a5fce 13efc6bc784af24f
        # 0020: 4141bdd48cf7c770 887afd573cca5418 a9aeffcd7c5ceddf c6a78397b9a85b49
        # 0040: 9da558257267caab 2ad0b23ca476a53c b17fb41c4b8b475c b4f3f7165094c229
        # 0060: c9e8c4dc0a2a5ff1 903e501511221376 a1cdb8364c5061a2 0cae74bc4acd76ce
        # 0080: b0abc9fd3217ef9f 8c90be402ddf6d86 97f4f880dff15bfb 7a6b28241ec8fe18
        # 00a0: 3c2d59e3f9dfff65 3c7126f0acb9e642 11f42bae12af462b 1070bef1ab5e3606
        # 00c0: 872ca10dee15b324 9b1a1b958f23134c 4bccb7d03200bce4 20a2f8eb66dcf364
        # 00e0: 4d1423c1b5699003 c13ecef4bf38a3b6 0eedc34033bac190 2783dc6d89e2e774
        # 0100:-188a439c7ebcc067 2dbda4ddcfb27946 13b0be41315ef778 708a70ee7d75165c
        # 0100:+188a439c7ebcc067 2dbda4ddcfb27946 13b0be41315ef778 708a70ee7d751625
        #                                                                        ^^
        #

**Comment by dannytsen** [comment]
@t8m I may have found the problem.  It looks like it's counter overflow.  Will have a solution.

**Comment by dannytsen** [comment]
@t8m I believe I have fixed the problem.  Here is the test result.  I'll double check.  So, What should do next?

All tests successful.
Files=241, Tests=3277, 387 wallclock secs ( 6.48 usr  0.34 sys + 362.64 cusr 21.22 csys = 390.68 CPU)
Result: PASS

**Comment by dannytsen** [comment]
@t8m Should I create another PR for the fix?  Thanks.

**Comment by paulidale** [comment]
Yes, please create a PR for the fix.

**Comment by hlandau** [comment]
Closing this as it's been fixed.
