### ISSUE TITLE
MaxProtocol in conf file overwritten by application

### ISSUE THREAD

**Issue by yusshi** [openssl/openssl#17593]
With openssl 1.1.1l, I need to force max TLS version to 1.2, so I have below in conf file and expected TLS version should be capped at version 1.2.
'''
[ssl_sect]
system_default = ssl_default_sect

[ssl_default_sect]
MaxProtocol = **TLSv1.2**
'''
But on application side, if SSL_CTX_set_max_proto_version(ctx, **TLSv1.3**), or SSL_CTX_set_max_proto_version(cts, **0**) is called, TLS version 1.3 is used.

Shouldn't SSL_CTX_ctrl() check the default config and apply the default limit if what application requests is above the default value?

We need default config to take effect since there is a big number of applications that need TLS and changing config for all of them is  not efficient. 

Thanks,
yusshi

**Comment by t8m** [comment]
No, the configuration file just sets the default. Applications can still override it with an API call. This is by design and not something we would change.

In other words the values in the configuration are not a "hard policy limit".
