### ISSUE TITLE
SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking

### ISSUE THREAD

**Issue by Arnosir** [openssl/openssl#1760]
Hi all ,

Tengine version: Tengine/2.1.2 (nginx/1.6.2)
Openssl Version: openssl-1.0.2j

issue：

``` shell
2016/10/21 17:57:22 [crit] 8005#0: *837695 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking, client: 115.193.226.146, server: 0.0.0.0:443
2016/10/21 18:00:13 [crit] 8004#0: *865240 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking, client: 103.3.97.65, server: 0.0.0.0:443
2016/10/21 18:01:26 [crit] 8003#0: *892047 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking, client: 103.40.223.35, server: 0.0.0.0:443
```

How can i fix it ?  Thanks.  :smile:

**Comment by mdounin** [comment]
Upgrade to a newer version of nginx, these alerts were fixed in nginx 1.9.2:

    *) Workaround: "called a function you should not call" and "shutdown
       while in init" messages might appear in logs when using OpenSSL
       1.0.2f.

See [this commit](http://hg.nginx.org/nginx/rev/062c189fee20) for more details.

**Comment by Arnosir** [comment]
@mdounin Thanks for your comment.
Tengine at the same time support HTTP v2 protocol and SPDY v3 protocol
So I can't replace it with nginx.

**Comment by mdounin** [comment]
@Arnosir, you can, try comparing http://caniuse.com/#feat=http2 and http://caniuse.com/#feat=spdy. And you actually have to if this and other fixes from nginx wasn't yet merged into Tengine - this effectively makes it unsupported and unsafe to use.

Either way, this doesn't look related to OpenSSL. You may want to open an issue in Tengine instead.

**Comment by simbalion** [comment]
I'm using nginx 1.9.10 and am experiencing this issue on one of my servers. I'm also having a weird issue with php5-fpm/nginx periodically hanging and I wonder if it could be related to this. It was working fine until about 2 weeks ago, but I'm uncertain if it began failing following a system update or Wordpress update.

**Comment by hamburml** [comment]
@simbalion Did you find a solution? I am also using nginx 1.9.10 and I get this error message a lot. Some users of the page also mentioned to us that sometimes content can't be loaded. After they refresh the page the content is there. Maybe that's because of the SSL handshaking error.

Server is debian jessie and I installed nginx from jessie-backports.

```
openssl version -v
OpenSSL 1.0.1t  3 May 2016 (Library: OpenSSL 1.0.2k  26 Jan 2017)
```

```
nginx -V
nginx version: nginx/1.9.10
built with OpenSSL 1.0.2j  26 Sep 2016 (running with OpenSSL 1.0.2k  26 Jan 2017)
```

Maybe I can solve this problem by updating nginx to 1.10.3 (https://packages.debian.org/jessie-backports/nginx) and openssl to 1.0.2k (But I do not understand the openssl version -v output... It says I have 1.0.1t, the library is 1.0.2k and nginx runs with openssl 1.0.2k but was built with 1.0.2j).

**Comment by hamburml** [comment]
@mdounin You have a typo, you mean 1.9.12 and not 1.9.2.

**Comment by mdounin** [comment]
@hamburml, sure, fixed.

**Comment by untra** [comment]
Seeing this issue on nginx 1.8.0 with openssl 1.0.2k

**Comment by richsalz** [comment]
This appears to be an nginx issue, and you have to upgrade to 1.9.12  If it still happens after that, please re-open this issue.

**Comment by tastatur** [comment]
Have upgraded ngix to the 1.9.12, the error  is still present:

```
openssl version -v
OpenSSL 1.0.2k  26 Jan 201

nginx -v
nginx version: nginx/1.9.12
```
