### ISSUE TITLE
Add support to get modules-dir via pkg-config

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#17602]
I currently can get the engins-dir via `pkg-config --variable=enginesdir libcrypto` to find out where to install engines, but there is no way to find out where to install providers via pkg-config. 

A `pkg-config --variable=modulessdir libcrypto` would make sense and should be easy to add in Configurations/unix-Makefile.tmpl.

I know that I can find out the modules dir via `openssl version -m`, but pkcs-config is more convenient in many situations.

**Comment by levitte** [comment]
#17605 adds it

**Comment by ifranzki** [comment]
Wow that was quick, thanks a lot!
