### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line when openin file 164.cert.pem

### ISSUE THREAD

**Issue by snorberhuis** [openssl/openssl#1761]
I am getting a strange bug when opening a certificate with sTunnel:

```
2016.10.21 03:04:43 LOG3[main]: error queue: 140DC009: error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib
2016.10.21 03:04:43 LOG3[main]: SSL_CTX_use_certificate_chain_file: 906D06C: error:0906D06C:PEM routines:PEM_read_bio:no start line
2016.10.21 03:04:43 LOG3[main]: Service [certificate-based server]: Failed to initialize SSL context
2016.10.21 03:04:43 LOG3[main]: Failed to reload the configuration file
```

I think this bug is in the SSL library. I am trying to open a file called `164.cert.pem`. If I change it to `certfile.cert.pem` it does work. The error message is misleading.

**Comment by kaduk** [comment]
Can you use strace or similar to confirm that the application is actually opening the 164.cert.pem file and not some other file?

**Comment by mattcaswell** [comment]
No response from reporter to earlier question from @kaduk. Closing.
