### ISSUE TITLE
Call OCSP server during TLS peer certificate validation

### ISSUE THREAD

**Issue by OlegPekar** [openssl/openssl#17618]
We have a well known flow for validation of TLS peer certificate during TLS handshake. When other checks are done peer certificate is ok - the code in crypto/x509/x509_vfy.c::check_cert() checks the revocation against the CRL if present for the CA certificate of peer certificate. In my product I need to check first revocation of peer certificate against OCSP server if configured for the given CA in the product. Thus I inserted OCSP check as a callback into check_cert(). OCSP callback returns indication whether revocation status was checked or not. If not - then can continue to CRL as in the original flow. Thus the final result of revocation check consists of both possible OCSP and CRL checks.

I would like to add this flow into master OpenSSL also. Please suggest whether it fits the architecture and plans.

**Comment by OlegPekar** [comment]
Moving the conversation to Issue [#8449](https://github.com/openssl/openssl/issues/8499) where the same question was discussed deeply

**Comment by livius-ungureanu** [comment]
Hi @OlegPekar - Are there any news on this issue? I'm also interested in a toggle a openssl level in order to enable OCSP during TLS handshake.

**Comment by nhorman** [comment]
Given that this conversation has been moved to #22584 
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
