### ISSUE TITLE
OpenSSL 3.0.1 fails to generate .pem files with the same command that works successfully with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by sludewig** [openssl/openssl#17617]
Platform: Windows
OpenSSL version: 3.0.1 from https://slproweb.com/products/Win32OpenSSL.html

We generate a certificate with the following command:

```
makecert -sv RP_Private_Key.pvk -n "CN=Company Name Relying Party" -b 01/01/2015 -e 12/31/2199 -sky exchange -ss My -a sha256 -len 2048 -r -pe RP_Cert.cer
```

Then we attempt to create a .pem file from the .pvk file with the following command:

```
openssl rsa -inform pvk -in RP_Private_Key.pvk -outform pem -out RP_Private_Key.pem
```

This successfully generates the .pem file when using OpenSSL 1.1.1
However when using Open 3.0.1, then OpenSSL fails with the following error:

```
"Could not read private key from RP_Private_Key.pvk
F0310000:error:1608010C:STORE
routines:ossl_store_handle_load_result:unsupported:crypto\store\store_result.c:151:"
```

**Comment by t8m** [comment]
The PVK format support requires algorithms present only in the legacy provider. You need to use the -provider options to load the legacy and default provider to make the command work with OpenSSL 3.0.
