### ISSUE TITLE
evp_test: Expected KDF_MISMATCH got KDF_DERIVE_ERROR / openssl 1.1.1 2022-01-30

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#17612]
```
    # Subtest: ../evp_test
    1..1
        # Subtest: run_file_tests
        1..1
        # INFO: 
        # Reading ../recipes/30-test_evp_data/evpkdf.txt
        # INFO: 
        # Starting "TLS1 PRF tests (from NIST test vectors)" tests at line 15
        # INFO: 
        # Starting "HKDF tests (from RFC5869 test vectors)" tests at line 72
        # INFO: 
        # Starting "id-scrypt tests (from draft-josefsson-id-scrypt-kdf-03 and others)" tests at line 255
        # INFO: 
        # ../recipes/30-test_evp_data/evpkdf.txt:298: Expected KDF_MISMATCH got KDF_DERIVE_ERROR
        # 140561529620224:error:060B5041:digital envelope routines:EVP_PBE_scrypt:malloc failure:crypto/evp/pbe_scrypt.c:242:
        # INFO: 
        # Completed 39 tests with 1 errors and 0 skipped
        not ok 1 - ../recipes/30-test_evp_data/evpkdf.txt
    not ok 1 - run_file_tests
../../util/shlib_wrap.sh ../evp_test ../recipes/30-test_evp_data/evpkdf.txt => 1
not ok 4 - running evp_test evpkdf.txt
```
```
$ cat /etc/redhat-release 
CentOS release 6.10 (Final)
```
```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
```

```
CFLAGS="-Wall -O3"      # default
CFLAGS="$CFLAGS -g"
CFLAGS="$CFLAGS -Wextra"
CFLAGS="$CFLAGS -Wno-unused-parameter"
```

configuration with zlib and enable-unit-test

----
Remark: not reproducible in my other builds.

**Comment by Ajax-Light** [comment]
Hey, can I know the steps to reproduce this issue?

**Comment by petrovr** [comment]
Hello,

Ujwal Kundur wrote:
> Hey, can I know the steps to reproduce this issue?
> 

There is nothing special. Initial post has information for os version, compiler version, used compiler flags and configuration.
Output sniped is from verbose test only for failed part.

Regards,
Roumen Petrov

**Comment by paulidale** [comment]
This is odd.  None of the files involved seem to have changed recently and the code looks like it could never succeed since this is an out of memory test.

**Comment by Ajax-Light** [comment]
I've run the tests with `make VF=1 test` under WSL on Windows and there are no errors. Probably OS related?

**Comment by dlegaultbbry** [comment]
This test never ran properly before until it was 'fixed' in 1.1.1m. Apparently you need to bump the amount of RAM available to run the test to something higher than 1GB. I stumbled on the same issue when porting to QNX where embedded targets don't have that much RAM.

https://github.com/openssl/openssl/commit/dc3520b1ad3e1d70b899210bacc002318ebe276a#diff-c11b72a13e3b238ba8de4ada35805d58786b5570a80f9263acac448e30ce9142

**Comment by paulidale** [comment]
If the memory allocation *works*, the result will be KDF_MISMATCH since there is no result specified.
The test is expected to fail due to insufficient memory.

**Comment by petrovr** [comment]
Pauli wrote:
> If the memory allocation *works*, the result will be KDF_MISMATCH since there is no result specified.
> The test is expected to fail due to insufficient memory.
> 
> 


Dunno when I will have time to run again test on "retired" build/test environments.
My primary goal is to run PKIX-SSH tests on some OS releases. Once with system cryptographic library and once with more recent "stable" release.
On recent release first is run unit/regression test to avoid needless investigation if PKIX-SSH test fail.

Usually those tests are run once in year on ancient OS releases.
Ancient mean that neither configuration nor system is updated. It is same for long time.
And now for first time EVP related test fail.


Error is in Microsoft style, i.e. nothing related to real issue. Error in open source style, i.e. exact reasons will be more helpful.
It will avoid OpenSSL issue system to be flooded.

Also error raises another question. What should be cryptographic library behaviour if it runs out of memory?
But this general question is more for master branch and out of scope to current issue.

Regards,
Roumen Petrov
