### ISSUE TITLE
x509 command writes output to NULL handle

### ISSUE THREAD

**Issue by Futaura** [openssl/openssl#17613]
The code starting at the below line attempts to print output to a handle that has not yet been opened:

https://github.com/openssl/openssl/blob/7fde39de848f062d6db45bf9e69439db2100b9bb/apps/x509.c#L714

**Comment by t8m** [comment]
I think these auxiliary messages should just go to bio_err instead.

**Comment by t8m** [comment]
> I think these auxiliary messages should just go to bio_err instead.

And that was also the case in 1.1.1 version.

**Comment by Futaura** [comment]
I should have added that I realize that ultimately, BIO_printf() checks for a NULL pointer anyway, so its not a major issue, but a bug nonetheless as the output doesn't get output. I wouldn't have even noticed, except for AmiSSL we have to do some funky remapping of the output routines and those output a warning for NULL pointers like this, and I then also realised that OpenSSL 1.1.1 didn't have this issue.
