### ISSUE TITLE
Unable to convert .key to .pem

### ISSUE THREAD

**Issue by uhlhosting** [openssl/openssl#17672]
We have the following:

```
root@post:/opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/post.uhlhosting.ch# ls -latr
total 28
drwx------ 4 postal users 4096 Nov 24 15:43 ..
-rw------- 1 postal users  227 Jan 29 14:43 post.uhlhosting.ch.key
-rw------- 1 postal users  157 Jan 29 14:43 post.uhlhosting.ch.json
-rw------- 1 postal users 5329 Jan 29 14:43 post.uhlhosting.ch.crt
-rw-r--r-- 1 root   root  1578 Feb  9 12:41 post.uhlhosting.ch.pem
-rw-r--r-- 1 root   root     0 Feb  9 12:44 post.uhlhosting.ch.key.pem
drwx------ 2 postal users 4096 Feb  9 12:44 .
root@post:/opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/post.uhlhosting.ch# rm -rf post.uhlhosting.ch.key.pem 
root@post:/opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/post.uhlhosting.ch# openssl rsa -in post.uhlhosting.ch.key -text > key.pem
139943793616192:error:0607907F:digital envelope routines:EVP_PKEY_get0_RSA:expecting an rsa key:../crypto/evp/p_lib.c:469:
root@post:/opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/post.uhlhosting.ch# 
```

It seems openssl refuses to convert my .key into .pem format.

**Comment by t8m** [comment]
Is it a binary DER format? If so then `-inform DER` can help.

**Comment by uhlhosting** [comment]
So this would be `openssl rsa -inform DER -in post.uhlhosting.ch.key -text > key.pem` ?

**Comment by t8m** [comment]
Yes, or even better without the -text unless you want there also the human readable representation of the key.

**Comment by t8m** [comment]
The file is quite small for an RSA key. Isn't it something else? Is it a binary file?
If so, `openssl asn1parse -inform DER -in ...key` might help to identify what is in the file.

**Comment by uhlhosting** [comment]
I got: 

```
0:d=0  hl=2 l=  45 cons: <ASN1 13>         
Error in encoding
140223973463360:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:../crypto/asn1/asn1_lib.c:91:
root@post:/opt/postal/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/post.uhlhosting.ch# 
```

This is a SSL .key generated by Caddy server for one of our servers.

**Comment by t8m** [comment]
I am afraid that we cannot really help you unless you show us the file (of course that would mean generating a new key afterwards).

**Comment by uhlhosting** [comment]
[priv.key.zip](https://github.com/openssl/openssl/files/8040038/priv.key.zip)
here is the key, I had to .zip it.

**Comment by t8m** [comment]
The key is already in PEM format so it does not need to be converted in any way. The key is an EC key, so it cannot be loaded by the `openssl rsa` command. If you want to load it by an openssl command to examine it, you can use `openssl ec` or `openssl pkey` commands.

**Comment by t8m** [comment]
Of course you'll also need to generate it again as you've published the key here.

**Comment by uhlhosting** [comment]
> The key is already in PEM format so it does not need to be converted in any way. The key is an EC key, so it cannot be loaded by the `openssl rsa` command. If you want to load it by an openssl command to examine it, you can use `openssl ec` or `openssl pkey` commands.

So it would suffice to duplicate the file and rename from .key to .pem ? And the key is valid and will work, great!
