### ISSUE TITLE
Building with `no-shared` still builds dynamic ossl-modules

### ISSUE THREAD

**Issue by jeroen** [openssl/openssl#17679]
Is there a way to build a static version of openssl3, including the "legacy" OSSL_PROVIDER? 

I maintain bindings for the R programming language, which require that on Windows everything is statically linked, no runtime dll dependencies. This was easy with openssl 1.1.1 but with openssl3 we need to use:

```c
OSSL_PROVIDER_load(NULL, "legacy");
OSSL_PROVIDER_load(NULL, "default");
```

However it seems that the legacy library is always built as a shared library, even when building openssl with `no-shared`? Is there a way to build a static `legacy.a` library that we can link to the bindings at build time?

**Comment by mattcaswell** [comment]
Configure with `no-shared no-module`. The legacy provider is then part of libcrypto.a. You still need to "load" it via `OSSL_PROVIDER_load()` - but no .so file is required in that case.

**Comment by jeroen** [comment]
Thanks I'll try that! Maybe it would make sense if `no-shared` implies `no-module` (as modules are by definition shared)?
