### ISSUE TITLE
the specific test case failed with environment variable not  replaced by Perl

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#17681]
##Issue:
./test/ssl_test ./test-runs/test_ssl_new/17-renegotiate.cnf.default， this test case failed with the  environment variable not  replaced by Perl.
NCONF_load  failed with “./test/ssl_test ./test-runs/test_ssl_new/17-renegotiate.cnf.default”. As strdup will failed in case of “${ENV::TEST_CERTS_DIR}/*” .
##Error information:
ERROR: (int) 'NCONF_load(conf, test_get_argument(0), NULL) > 0' failed @ test/ssl_test.c:550
[0] compared to [0]
ERROR:  @ test/ssl_test.c:553

##Background:
 “make V=1 TESTS='test_ssl_new*' test”, the error information could not help to local the issue, and tried run and debug the specific test case.
../../util/wrap.pl /usr/bin/perl -I ../../util/perl ../../test/generate_ssl_tests.pl ../../test/ssl-tests/17-renegotiate.cnf.in none > 17-renegotiate.cnf.none => 0
    ok 1 - Getting output from generate_ssl_tests.pl.
    ok 2 - Comparing generated 17-renegotiate.cnf.none with ../../test/ssl-tests/17-renegotiate.cnf.
        # Subtest: ../../test/ssl_test
        1..1
            # Subtest: test_handshake
            1..17
              ERROR: (int) 'peer->status == PEER_RETRY' failed @ test/helpers/handshake.c:868
             [2] compared to [1]
             ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:36
             [3] compared to [1]
             INFO:  @ test/ssl_test.c:37
             ExpectedResult mismatch: expected ServerFail, got InternalError.
             OPENSSL_TEST_RAND_ORDER=1644408281
            not ok 12 - iteration 12
            ok 13 - iteration 13
             ERROR: (int) 'peer->status == PEER_RETRY' failed @ test/helpers/handshake.c:868
             [2] compared to [1]
             ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:36
             [3] compared to [2]
             INFO:  @ test/ssl_test.c:37
             ExpectedResult mismatch: expected ClientFail, got InternalError.
             OPENSSL_TEST_RAND_ORDER=1644408281
            not ok 14 - iteration 14
             ERROR: (int) 'result->server_alert_sent == result->server_alert_received' failed @ test/ssl_test.c:66
             [552] compared to [0]
             INFO:  @ test/ssl_test.c:68
             Server sent alert handshake failure but client received no alert.
            ok 15 - iteration 15
            ok 16 - iteration 16
            ok 17 - iteration 17
        # OPENSSL_TEST_RAND_ORDER=1644408281
        not ok 1 - test_handshake

**Comment by mattcaswell** [comment]
> ./test/ssl_test ./test-runs/test_ssl_new/17-renegotiate.cnf.default， this test case failed with the environment variable not replaced by Perl.

If you run the test manually and directly then it is your responsibility to ensure that the environment variable is set. See the file README.ssltest and in particular the section "Running a test manually"

Try running the test like this and see what happens:

````
    $ CTLOG_FILE=test/ct/log_list.cnf  TEST_CERTS_DIR=test/certs \
      util/wrap.pl test/ssl_test ./test-runs/test_ssl_new/17-renegotiate.cnf.default default
````

**Comment by KanPlus** [comment]
> 

This working,thanks.
