### ISSUE TITLE
Conflicting license Information in OpenSSL 3.0.1 codebase few files

### ISSUE THREAD

**Issue by Gagu2** [openssl/openssl#17684]
Hi All,

Please note headers of few files in OpenSSL version 3.0.1 codebase, mention that the files are under OpenSSL license but the link referred in the file header mentions that the OpenSSL component 3.0 release, and later releases derived from that are under Apache License v2.

Hence, this is conflicting information, should these files be treated under Apache v2 license or OpenSSL license. The LICENSE.text file in OpenSSL 3.0.1 mentions Apache v2 license and majority of the files header information also mention that the files are under Apache v2 license but few files have this conflicting information.

Please find below the header information of these files and files paths:

Header:

* Licensed under the OpenSSL license (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html

File path of these files:

openssl-openssl-3.0.1/crypto/ec/curve448/arch_64/f_impl64.c
openssl-openssl-3.0.1/crypto/ec/curve448/arch_64/f_impl.h
openssl-openssl-3.0.1/crypto/ec/curve448/arch_64/arch_intrinsics.h
openssl-openssl-3.0.1/include/crypto/pem.h
openssl-openssl-3.0.1/test/recipes/03-test_internal_sm3.t
openssl-openssl-3.0.1/test/dane-cross.in
openssl-openssl-3.0.1/crypto/ec/asm/ecp_nistp521-ppc64.pl
openssl-openssl-3.0.1/apps/lib/engine_loader.c
openssl-openssl-3.0.1/apps/include/engine_loader.h
openssl-openssl-3.0.1/doc/man1/openssl-cmp.pod.in
openssl-openssl-3.0.1/test/pbetest.c
openssl-openssl-3.0.1/test/sm3_internal_test.c

Please clarify the license of these files, should these be treated as under Apache 2.0 license or OpenSSL license, and change the header information if required for more clarity

Thank you

**Comment by t8m** [comment]
The PR #17606 already fixed that. It is merged to both master and 3.0 branches.

**Comment by t8m** [comment]
So yeah Apache v2 license is the correct one.

**Comment by t8m** [comment]
Hmm, a few of the files were not fixed by the PR. Reopening and adding a new PR.

**Comment by t8m** [comment]
Fix in #17686

**Comment by Gagu2** [comment]
Dear t8m,

Please note that I only see 5 files being corrected in 3.0.1 and not all 12 files, thanks

![image](https://user-images.githubusercontent.com/75708407/153573067-c25a1679-676c-4e26-ad48-75b93f59d473.png)

**Comment by mattcaswell** [comment]
As previously noted by @t8m, PR #17606 already fixed the other files. You won't see the fixes by examining the 3.0.1 tag in github. The 3.0.1 release is done and released and cannot be changed. The fixes will be in 3.0.2 when it is released. You need to look at the openssl-3.0 branch instead:

https://github.com/openssl/openssl/blob/openssl-3.0/crypto/ec/curve448/arch_64/f_impl64.c

**Comment by Gagu2** [comment]
Thank you for the reply.
