### ISSUE TITLE
[OpenSSL 1.1.1a] Hi Team, my SSL/TLS server crashed with the attached call stack. Your advice will be highly appreciated.

### ISSUE THREAD

**Issue by Syllinia** [openssl/openssl#17680]
Hi Team,

My SSL/TLS server crashed with the following call stack.
I'm using OpenSSL 1.1.1a.
Your advice will be highly appreciated.

(gdb) 0 0x00007f4cf7844ce6 in ASN1_OBJECT_free ()
   from /lib/libcrypto.so.1.1
1 0x00007f4cf7859468 in asn1_primitive_free ()
   from /lib/libcrypto.so.1.1
0000002 0x00007f4cf7859890 in asn1_template_free ()
   from /lib/libcrypto.so.1.1
3 0x00007f4cf78596e6 in asn1_item_embed_free ()
   from /lib/libcrypto.so.1.1
4 0x00007f4cf7859852 in asn1_template_free ()
   from /lib/libcrypto.so.1.1
5 0x00007f4cf78596e6 in asn1_item_embed_free ()
   from /lib/libcrypto.so.1.1
6 0x00007f4cf7859890 in asn1_template_free ()
   from /lib/libcrypto.so.1.1
7 0x00007f4cf78596e6 in asn1_item_embed_free ()
   from /lib/libcrypto.so.1.1
8 0x00007f4cf78597d5 in ASN1_item_free () from /lib/libcrypto.so.1.1
9 0x00007f4cf5e5563c in ssl_cert_clear_certs ()
   from /lib/libssl.so.1.1
10 0x00007f4cf5e556d5 in ssl_cert_free () from /lib/libssl.so.1.1
11 0x00007f4cf5e6068c in SSL_CTX_free () from /lib/libssl.so.1.1

Thanks,
Allen

**Comment by Syllinia** [comment]
Hi Pauli,

Thanks for your advice. Actually the core was related with OpenSSL 1.1.1a.
I recompiled OpenSSL libraries with config -g and after gdb with the core I get the following call stack.

Program terminated with signal SIGSEGV, Segmentation fault.
#0  ASN1_OBJECT_free (a=0x9567f0720d56aa34) at crypto/asn1/a_object.c:352
352	crypto/asn1/a_object.c: No such file or directory.
[Current thread is 1 (Thread 0x7f49f4bff700 (LWP 6681))]
(gdb) bt
#0  ASN1_OBJECT_free (a=0x9567f0720d56aa34) at crypto/asn1/a_object.c:352
#1  0x00007f4cf7859468 in asn1_primitive_free (pval=<optimized out>, it=<optimized out>, embed=<optimized out>)
    at crypto/asn1/tasn_fre.c:185
#2  0x00007f4cf7859890 in asn1_template_free (pval=0x7f49a0d8a430, tt=tt@entry=0x7f4cf7c96440 <X509_EXTENSION_seq_tt>)
    at crypto/asn1/tasn_fre.c:142
#3  0x00007f4cf78596e6 in asn1_item_embed_free (pval=0x7f49f4bfc1b8, it=0x7f4cf7c8cf20 <X509_EXTENSION_it>, embed=0)
    at crypto/asn1/tasn_fre.c:110
#4  0x00007f4cf7859852 in asn1_template_free (pval=0x7f4a097c97e8, tt=tt@entry=0x7f4cf7c968c8 <X509_CINF_seq_tt+360>)
    at crypto/asn1/tasn_fre.c:137
#5  0x00007f4cf78596e6 in asn1_item_embed_free (pval=0x7f49f4bfc250, it=0x7f4cf7c8d2a0 <X509_CINF_it>, embed=4096)
    at crypto/asn1/tasn_fre.c:110
#6  0x00007f4cf7859890 in asn1_template_free (pval=0x7f49f4bfc250, tt=tt@entry=0x7f4cf7c966e0 <X509_seq_tt>)
    at crypto/asn1/tasn_fre.c:142
#7  0x00007f4cf78596e6 in asn1_item_embed_free (pval=0x7f49f4bfc2f8, it=0x7f4cf7c8d220 <X509_it>, embed=0)
    at crypto/asn1/tasn_fre.c:110
#8  0x00007f4cf78597d5 in ASN1_item_free (val=<optimized out>, it=it@entry=0x7f4cf7c8d220 <X509_it>) at crypto/asn1/tasn_fre.c:20
#9  0x00007f4cf79ccedc in X509_free (a=<optimized out>) at crypto/x509/x_x509.c:86
#10 0x00007f4cf5e5563c in ssl_cert_clear_certs (c=c@entry=0x7f4a0b817000) at ssl/ssl_cert.c:212
#11 0x00007f4cf5e556d5 in ssl_cert_free (c=0x7f4a0b817000) at ssl/ssl_cert.c:240
#12 0x00007f4cf5e6068c in SSL_CTX_free (a=0x7f4a0b41f000) at ssl/ssl_lib.c:3117

I checked multiple frames and was unable to find some clues except ASN1_ITEM_st.sname in asn1_item_embed_free(). Any advice? Thanks in advance.

(gdb) f 0
#0  ASN1_OBJECT_free (a=0x9567f0720d56aa34) at crypto/asn1/a_object.c:352
352	in crypto/asn1/a_object.c
(gdb) info args
a = 0x9567f0720d56aa34
(gdb) set print pretty
(gdb) p *a
Cannot access memory at address 0x9567f0720d56aa34
(gdb) f 11
#11 0x00007f4cf5e556d5 in ssl_cert_free (c=0x7f4a0b817000) at ssl/ssl_cert.c:240
240	ssl/ssl_cert.c: No such file or directory.
(gdb) p *c
$1 = {
  key = 0x7f4a0b817020, 
  dh_tmp = 0x0, 
  dh_tmp_cb = 0x55eab16c9ed0 <_su_tmpdh_cb>, 
  dh_tmp_auto = 0, 
  cert_flags = 0, 
  pkeys = {{
      x509 = 0x7f4a097c9780, 
      privatekey = 0x7f4980ff01b0, 
      chain = 0x0, 
      serverinfo = 0x0, 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
      serverinfo = 0x0, 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
      serverinfo = 0x0, 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
      serverinfo = 0x0, 
--Type <RET> for more, q to quit, c to continue without paging-- 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
      serverinfo = 0x0, 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
      serverinfo = 0x0, 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
      serverinfo = 0x0, 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
      serverinfo = 0x0, 
      serverinfo_length = 0
    }, {
      x509 = 0x0, 
      privatekey = 0x0, 
      chain = 0x0, 
--Type <RET> for more, q to quit, c to continue without paging--
      serverinfo = 0x0, 
      serverinfo_length = 0
    }}, 
  ctype = 0x0, 
  ctype_len = 0, 
  conf_sigalgs = 0x0, 
  conf_sigalgslen = 0, 
  client_sigalgs = 0x0, 
  client_sigalgslen = 0, 
  shared_sigalgs = 0x0, 
  shared_sigalgslen = 0, 
  cert_cb = 0x0, 
  cert_cb_arg = 0x0, 
  chain_store = 0x0, 
  verify_store = 0x0, 
  custext = {
    meths = 0x0, 
    meths_count = 0
  }, 
  sec_cb = 0x7f4cf5e55160 <ssl_security_default_callback>, 
  sec_level = 0, 
  sec_ex = 0x0, 
  psk_identity_hint = 0x0, 
  references = 0, 
  lock = 0x7f4a0a4af1d0
}
(gdb) f 10
#10 0x00007f4cf5e5563c in ssl_cert_clear_certs (c=c@entry=0x7f4a0b817000) at ssl/ssl_cert.c:212
212	in ssl/ssl_cert.c
(gdb) p i
$2 = <optimized out>
(gdb) p cpk-c->pkeys
$3 = 0
(gdb) f 8
#8  0x00007f4cf78597d5 in ASN1_item_free (val=<optimized out>, it=it@entry=0x7f4cf7c8d220 <X509_it>) at crypto/asn1/tasn_fre.c:20
20	crypto/asn1/tasn_fre.c: No such file or directory.
(gdb) p *val
value has been optimized out
(gdb) p *it
$4 = {
  itype = 1 '\001', 
  utype = 16, 
  templates = 0x7f4cf7c966e0 <X509_seq_tt>, 
  tcount = 3, 
  funcs = 0x7f4cf7c8d260 <X509_aux>, 
  size = 352, 
  sname = 0x7f4cf7a1d6dd "IR"
}
(gdb) f 5
#5  0x00007f4cf78596e6 in asn1_item_embed_free (pval=0x7f49f4bfc250, it=0x7f4cf7c8d2a0 <X509_CINF_it>, embed=4096)
    at crypto/asn1/tasn_fre.c:110
110	in crypto/asn1/tasn_fre.c
(gdb) p **pval
$5 = <incomplete type>
(gdb) p *pval
$6 = (ASN1_VALUE *) 0x7f4a097c9780
(gdb) p *it
$7 = {
  itype = 1 '\001', 
  utype = 16, 
  templates = 0x7f4cf7c96760 <X509_CINF_seq_tt>, 
  tcount = 10, 
  funcs = 0x7f4cf7a1e760, 
  size = 136, 
  sname = 0x7f4cf7a1e727 "ces"
}
(gdb) p i
$8 = 0
(gdb) f 3
#3  0x00007f4cf78596e6 in asn1_item_embed_free (pval=0x7f49f4bfc1b8, it=0x7f4cf7c8cf20 <X509_EXTENSION_it>, embed=0)
    at crypto/asn1/tasn_fre.c:110
110	in crypto/asn1/tasn_fre.c
(gdb) p *it
$9 = {
  itype = 1 '\001', 
  utype = 16, 
  templates = 0x7f4cf7c96440 <X509_EXTENSION_seq_tt>, 
  tcount = 3, 
  funcs = 0x0, 
  size = 40, 
  sname = 0x7f4cf7a1e638 "de digital signature"
}
(gdb) p i
$10 = 2
(gdb) f 2
#2  0x00007f4cf7859890 in asn1_template_free (pval=0x7f49a0d8a430, tt=tt@entry=0x7f4cf7c96440 <X509_EXTENSION_seq_tt>)
    at crypto/asn1/tasn_fre.c:142
142	in crypto/asn1/tasn_fre.c
(gdb) p *tt
$11 = {
  flags = 0, 
  tag = 0, 
  offset = 0, 
  field_name = 0x7f4cf7a1fabb "e", 
  item = 0x7f4cf7c700c0 <ASN1_NULL_it>
}
(gdb) p *(tt->item)
$12 = {
  itype = 0 '\000', 
  utype = 6, 
  templates = 0x0, 
  tcount = 0, 
  funcs = 0x0, 
  size = 0, 
  sname = 0x7f4cf79e41d2 "nown object type"
}
(gdb) f 1
#1  0x00007f4cf7859468 in asn1_primitive_free (pval=<optimized out>, it=<optimized out>, embed=<optimized out>)
    at crypto/asn1/tasn_fre.c:185
185	in crypto/asn1/tasn_fre.c
(gdb) p *it
value has been optimized out
(gdb) info args
pval = <optimized out>
it = <optimized out>
embed = <optimized out>
(gdb) info locals
utype = <optimized out>
embed = <optimized out>
it = <optimized out>
pval = 0x7f49a0d8a430
utype = <optimized out>
pf = <optimized out>
typ = <optimized out>
(gdb) f 0
#0  ASN1_OBJECT_free (a=0x9567f0720d56aa34) at crypto/asn1/a_object.c:352
352	crypto/asn1/a_object.c: No such file or directory.
(gdb) p *a
Cannot access memory at address 0x9567f0720d56aa34
(gdb)

**Comment by t8m** [comment]
Is this trace from some well known opensource application, or is this your own server application calling OpenSSL? Is the crash intermittent, or does it always happen?

**Comment by Syllinia** [comment]
@t8m Hi, thanks for your reply. It's from my own server application. And the crash is intermittent.

**Comment by Syllinia** [comment]
Hi Team, I'll do more investigation and thanks for your help.

**Comment by t-j-h** [comment]
Single threaded or multi-threaded?

> thread apply all bt

Have you tried an ASAN build (-fsanitize=address)?

That would assist you in tracking down any application errors.

**Comment by KVolodin** [comment]
> Hi Team, I'll do more investigation and thanks for your help.

Hi, I have the same problem, how did you solve it?
