### ISSUE TITLE
A potential redundant call to X509_free()

### ISSUE THREAD

**Issue by Wentao-Liang** [openssl/openssl#17695]
I find a potential redundant call to X509_free in OpenSSL-1.1.1m, which is in function execute_test_large_message (./test/sslsaptest.c)

Specifically, at line 754, variable 'chaincert' is freed by X509_free() when SSL_CTX_add_extra_chain_cert fails. However, variable 'chaincert' is freed again at line 774. We believe that the call to X509_free at line 754 is redundant. Directly removing it can fix the issue.

```
 707 static int execute_test_large_message(const SSL_METHOD *smeth,
 708                                       const SSL_METHOD *cmeth,
 709                                       int min_version, int max_version,
 710                                       int read_ahead)
 711 {
 
 ...
 
 753         if (!SSL_CTX_add_extra_chain_cert(sctx, chaincert)) {
 754             X509_free(chaincert);
 755             goto end;
 756         }

 ...
 
 773  end:
 774     X509_free(chaincert);
 
 ...
 
 781 }
```
I am looking forward to your confirmation.

Best,

Wentao

**Comment by mattcaswell** [comment]
No, the code is correct as it stands. This particular failure occurs just after an "up-ref" of `chaincert`:

````
        if (!X509_up_ref(chaincert))
            goto end;
````

After a successful call to `X509_up_ref()` there are *2* references to the `X509` object held by the test code. One of those references is immediately passed to, and owned by, the `SSL_CTX` object via the call to `SSL_CTX_add_extra_chain_cert`. However in the event that that call fails then the test still retains 2 references to the `X509` object and so needs to call `X509_free` twice.
