### ISSUE TITLE
request for an AES key reversal API

### ISSUE THREAD

**Issue by fionatrahe** [openssl/openssl#17699]
Due to OpenSSL v3.0 deprecations qatlib can no longer use AES_set_encrypt_key().

To resolve this, we'd like to request a new api for AES key reversal, i.e. expand the key and take the last round, similar to what’s done 
(1) in the linux kernel https://elixir.bootlin.com/linux/latest/source/drivers/crypto/qat/qat_common/qat_algs.c#L477 
or 
(2) in QATLib using AES_set_encrypt_key()  https://github.com/intel/qatlib/blob/878b00989b81625737df43ddb11a7e2f2377ea4c/quickassist/utilities/osal/src/linux/user_space/OsalCryptoInterface.c#L302    Note  OSAL_AES_SET_ENCRYPT = AES_set_encrypt_key

**Comment by t8m** [comment]
I do not think this is going to happen. This is totally out of alignment with the provider API design.

**Comment by fionatrahe** [comment]
thanks for your rapid response

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
