### ISSUE TITLE
Returned error code is 1 in set_string_internal even though val is not assigned to p->data

### ISSUE THREAD

**Issue by DreamTeam24** [openssl/openssl#17696]
Why is the returned error code in line 1154 of params.c in OpensSSL-3.0.0 equal to 1, indicating success? Since val is not assigned to p->data (because it's NULL), I would expect 0, indicating failure.

```
static int set_string_internal(OSSL_PARAM *p, const void *val, size_t len,
                               unsigned int type)
{
    p->return_size = len;
    if (p->data == NULL)
        return 1;
    if (p->data_type != type || p->data_size < len)
        return 0;

    memcpy(p->data, val, len);
    /* If possible within the size of p->data, add a NUL terminator byte */
    if (type == OSSL_PARAM_UTF8_STRING && p->data_size > len)
        ((char *)p->data)[len] = '\0';
    return 1;
}
```

**Comment by t8m** [comment]
That's because this is valid mode of the operation of the call that is used to obtain the required size in p->return_size to hold the val. See the manual page for the OSSL_PARAM_set_utf8_string() function for example.
