### ISSUE TITLE
FTP-ES: cannot abort current downloaded zip file (loop forever)

### ISSUE THREAD

**Issue by Alexey-T** [openssl/openssl#177]
I described issue https://github.com/Alexey-T/SynFTP/issues/65
To repeat it, 
- install SynWrite editor ( uvviewsoft.com/synwrite/ )
- open FTP tab in left panel (near Tree/Project)
- call gear icon and make connection to test.rebex.net / FTPES / demo/password
- connect to this 
- start downloading zip (one zip there)
- press Abort--> cannot abort, no red line in FTP log and queue item remains

@tbeu comment:

Please see CUT_WSClient::DisconnectSSL in ut_clnt.cpp. First call of SSL_shutdown in line 711 returns 0. Then it never returns from the while loop and calls SSL_read repeatedly with SSL_read returning 256.

**Comment by richsalz** [comment]
This seems more like a bug in the application using openssl and non-blocking or something.  Not an openssl bug.
