### ISSUE TITLE
request for new EVP_DigestTransform API

### ISSUE THREAD

**Issue by fionatrahe** [openssl/openssl#17700]
Due to OpenSSL v3.0 deprecations qatlib can no longer use <digest>_Transform() APIs.

To resolve this, we'd like to request a new api 
EVP_DigestTransform() to provide the intermediate hash for HMAC as previously provided by MD5_transform, SHAx_Transform, etc.
Example usage:
https://github.com/intel/qatlib/blob/878b00989b81625737df43ddb11a7e2f2377ea4c/quickassist/utilities/osal/src/linux/user_space/OsalCryptoInterface.c#L150

Note, the lower level APIs used here:
https://github.com/intel/qatlib/blob/878b00989b81625737df43ddb11a7e2f2377ea4c/quickassist/utilities/osal/src/linux/user_space/OsalCryptoInterface.c#L163  
can be replaced by EVP APIs, but for the intermediate hash transform there is no EVP alternative available.

**Comment by fionatrahe** [comment]
thanks for the rapid response

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
