### ISSUE TITLE
Enc command documentation not accessible 

### ISSUE THREAD

**Issue by EasySec** [openssl/openssl#17702]
The enc command documentation is not accessible inline for the master and 3.0 branches as for 1.1.1 or 1.0.2 branches. 
They link to a general cmd help instead.

[enc 1.1.1](https://www.openssl.org/docs/man1.1.1/man1/enc.html)
[enc 3.0](https://www.openssl.org/docs/man3.0/man1/enc.html)

**Comment by t8m** [comment]
This is not a bug, if you read the page it contains explanation that you need to look at the openssl-enc manual page instead.
