### ISSUE TITLE
DRBG fails to initialize cipher_data prior to EVP_EncryptUpdate leading to segfault

### ISSUE THREAD

**Issue by vh571964** [openssl/openssl#17715]
Version: OpenSSL 1.1.1a

We're experiencing intermittent segfaults when using RAND_DRBG. 
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/bin/pan_comm -t 0 -v 0'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000fff567515c in aes_ecb_cipher (ctx=<optimized out>, out=0xffb400d690 "",
    in=0xffc000e800 "\f\017D\300\067\372\247A\251\327\023\222\071S\370\207a\236\005*", len=0) at crypto/evp/e_aes.c:2860
#2  0x000000fff56813fc in EVP_EncryptUpdate (ctx=0xffc00048d0, out=0xffb400d690 "",
    outl=0xfff12ad8dc,
    in=0xffc000e800 "\f\017D\300\067\372\247A\251\327\023\222\071S\370\207a\236\005*", inl=<optimized out>) at crypto/evp/evp_enc.c:385
#3  0x000000fff56819fc in EVP_CipherUpdate (ctx=<optimized out>,
    out=<optimized out>, outl=<optimized out>, in=<optimized out>,
    inl=<optimized out>) at crypto/evp/evp_enc.c:259
#4  0x000000fff56c65b4 in drbg_ctr_generate (drbg=0xffc000e710, out=0xffb400d690 "",
    outlen=32, adin=<optimized out>, adinlen=<optimized out>)
    at crypto/rand/drbg_ctr.c:340
#5  0x000000fff56c7914 in RAND_DRBG_generate (drbg=0xffc000e710,
    out=0xffb400d690 "", outlen=32, prediction_resistance=<optimized out>, adin=0x0,
    adinlen=0) at crypto/rand/drbg_lib.c:693
#6  0x000000fff56c7bdc in RAND_DRBG_bytes (drbg=0xffc000e710, out=<optimized out>,
    outlen=<optimized out>) at crypto/rand/drbg_lib.c:734
#7  0x000000fff56c9e28 in RAND_priv_bytes (buf=0xffb400d690 "", num=<optimized out>)
    at crypto/rand/rand_lib.c:827
#8  0x000000fff55ffb24 in bnrand (bottom=<optimized out>, top=<optimized out>,
    bits=256, rnd=0xffb4001010, flag=PRIVATE) at crypto/bn/bn_rand.c:46
#9  bnrand (flag=flag@entry=PRIVATE, rnd=rnd@entry=0xffb4001010,
    bits=bits@entry=256, top=top@entry=-1, bottom=bottom@entry=0)
    at crypto/bn/bn_rand.c:21
#10 0x000000fff55ffe68 in bnrand_range (range=0xffb400e820, r=0xffb4001010,
    flag=PRIVATE) at crypto/bn/bn_rand.c:162
#11 bnrand_range (flag=<optimized out>, r=0xffb4001010, range=0xffb400e820)
    at crypto/bn/bn_rand.c:113
#12 0x000000fff5648488 in ec_key_simple_generate_key (eckey=0xffb4000f10)
    at crypto/ec/ec_key.c:319
#13 0x000000fff56481f8 in EC_KEY_generate_key (eckey=0xffb4000f10)
    at crypto/ec/ec_key.c:270
...
```
Initially we suspected this was an internal bug, perhaps from a memory corruption or an incorrect parameter. After investigating further, however, it appears that ctx->cipher_data is not being initialized.
```
(gdb) p ctx
$3 = (EVP_CIPHER_CTX *) 0xffc00048d0
(gdb) p *ctx
$4 = {cipher = 0xfff57fd538 <aes_256_ecb>, engine = 0x0, encrypt = 1, buf_len = 0,
  oiv = '\000' <repeats 15 times>, iv = '\000' <repeats 15 times>,
  buf = '\000' <repeats 31 times>, num = 0, app_data = 0x0, key_len = 32, flags = 0,
  cipher_data = 0xffb4003010, final_used = 0, block_mask = 15,
  final = '\000' <repeats 31 times>}
(gdb) p *((EVP_AES_KEY*) ctx->cipher_data)
$5 = {ks = {align = 0, ks = {rd_key = {0 <repeats 60 times>}, rounds = 0, cvmkey = {
        0, 0, 0, 0}, cvm_keylen = 0}}, block = 0x0, stream = {cbc = 0x0, ctr = 0x0}}
(gdb) p *(ctx->cipher)
$6 = {nid = 426, block_size = 16, key_len = 32, iv_len = 0, flags = 4097,
  init = 0xfff5674aa8 <aes_init_key>, do_cipher = 0xfff56750d8 <aes_ecb_cipher>,
  cleanup = 0x0, ctx_size = 304, set_asn1_parameters = 0x0,
  get_asn1_parameters = 0x0, ctrl = 0x0, app_data = 0x0}
(gdb) x/80xg ctx->cipher_data-304
0xffb4002ee0:   0x000000ffb4002ea0      0xce769a3632f1a70f
0xffb4002ef0:   0x212200c4bb5daf52      0xe2d468035251527a
0xffb4002f00:   0x000000ffb4003430      0x0000000000000035
0xffb4002f10:   0x000000ffb4002ed0      0xd332f19cd8c61387
0xffb4002f20:   0x5a8aa953aee67c90      0xc5cdd44f8dda45f7
0xffb4002f30:   0x000000ffb4003430      0x0000000000000035
0xffb4002f40:   0x000000ffb4002f00      0x0bd27107bc2e24d9
0xffb4002f50:   0xd718b1cbba6e1441      0xc310e97d2ee1da97
0xffb4002f60:   0x0000000000001e00      0x0000000000000035
0xffb4002f70:   0x000000ffb4002f30      0x4efc001ec2d9d9a8
0xffb4002f80:   0x4555b09d579fd555      0xaee8d890bdd1588c
0xffb4002f90:   0x0000000000001e90      0x0000000000000035
0xffb4002fa0:   0x000000ffb4002f60      0x2166bd9ed11316bb
0xffb4002fb0:   0x2e49c9dabd8e83aa      0x62ad04a0c8ff6120
0xffb4002fc0:   0x0000000000000000      0x0000000000000045
0xffb4002fd0:   0x000000ffb400e490      0x5ed1d3e555f23f07
0xffb4002fe0:   0x99e6ee3c09a7a4df      0x8d39ca8c279e52d6
0xffb4002ff0:   0x0000000000000000      0xffffffff00000001
0xffb4003000:   0x0000000000000040      0x0000000000000145
0xffb4003010:   0x0000000000000000      0x0000000000000000
0xffb4003020:   0x0000000000000000      0x0000000000000000
0xffb4003030:   0x0000000000000000      0x0000000000000000
0xffb4003040:   0x0000000000000000      0x0000000000000000
0xffb4003050:   0x0000000000000000      0x0000000000000000
0xffb4003060:   0x0000000000000000      0x0000000000000000
0xffb4003070:   0x0000000000000000      0x0000000000000000
0xffb4003080:   0x0000000000000000      0x0000000000000000
0xffb4003090:   0x0000000000000000      0x0000000000000000
0xffb40030a0:   0x0000000000000000      0x0000000000000000
0xffb40030b0:   0x0000000000000000      0x0000000000000000
0xffb40030c0:   0x0000000000000000      0x0000000000000000
0xffb40030d0:   0x0000000000000000      0x0000000000000000
0xffb40030e0:   0x0000000000000000      0x0000000000000000
0xffb40030f0:   0x0000000000000000      0x0000000000000000
0xffb4003100:   0x0000000000000000      0x0000000000000000
0xffb4003110:   0x0000000000000000      0x0000000000000000
0xffb4003120:   0x0000000000000000      0x0000000000000000
0xffb4003130:   0x0000000000000000      0x0000000000000000
0xffb4003140:   0x0000000000000000      0x0000000000000045
0xffb4003150:   0x000000ffb4000e00      0x0000019f00000000
```
From the available data we can see
1) ctx and ctx->cipher appear to be correctly populated
2) ctx->cipher_data is populated with 0's
3) The memory preceding where cipher_data is allocated is not populated with 0's. This implies it's unlikely that there's an out-of-bound write. 

As mentioned above, we only see this issue intermittently. We have seen this occur for different ciphers, such as DH key generation as opposed to ECDH key generation. We don't have a strong theory as to why this is occurring intermittently yet.

Please let us know if you concur with our analysis or what other debug info we can provide. Thank you for the help!

**Comment by paulidale** [comment]
Adding 3.0 and master since they'll need to be checked for this as well as 1.1.1.

**Comment by t8m** [comment]
The 1.1.1a is very old. Could you please retest with the latest release from the 1.1.1 branch?

**Comment by vh571964** [comment]
Unfortunately not. OpenSSL is integrated into our hardware platform; it's a non-trivial task to upgrade/modify the OpenSSL version. 
If you suspect this is an issue that has already been patched, please point me to the commit/patch; I can manually patch to test the fix.

**Comment by vh571964** [comment]
Found 2 more back traces, hopefully this might provide a bit more context.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffff4b448aa in aesni_ecb_encrypt ()
[Current thread is 1 (Thread 0x7fffeecfd700 (LWP 11210))]
Thread 1 (Thread 0x7fffeecfd700 (LWP 11210)):
#0  0x00007ffff4b448aa in aesni_ecb_encrypt ()
#1  0x00007ffff4c100c7 in aesni_ecb_cipher () 
#2  0x00007ffff4c1dc4b in EVP_EncryptUpdate () 
#3  0x00007ffff4c54ff0 in drbg_ctr_generate () 
#4  0x00007ffff4c56036 in RAND_DRBG_generate () 
#5  0x00007ffff4c562fa in RAND_DRBG_bytes () 
#6  0x00007ffff4b8388e in bnrand () 
...
```
```
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000000000 in ?? ()

Thread 1 (LWP 1435):
#0  0x0000000000000000 in ?? ()
#1  0x000000fff567815c in ?? () 
#2  0x000000fff56843fc in EVP_EncryptUpdate () 
#3  0x000000fff56849fc in EVP_CipherUpdate () 
#4  0x000000fff56c95b4 in ?? () 
#5  0x000000fff56ca914 in RAND_DRBG_generate () 
#6  0x000000fff56cabdc in RAND_DRBG_bytes () 
#7  0x000000fff56cce28 in RAND_priv_bytes () 
#8  0x000000fff5602b24 in ?? () 
#9  0x000000fff562ab14 in ?? () 
...
```
For second back trace, we don't load OpenSSL debug symbols on our release builds, hence the ?? in the stack. 

Should cipher_data always be initialized in DRBG? From code review, it looks like it should always be populated in EVP_CipherInit_ex(), as DRBG code should always pass in a key. I'm not 100% certain of this though, would appreciate confirmation from experts.

**Comment by vh571964** [comment]
Is there any debug info I can provide to help diagnose this issue? As mentioned above, if we have a guess as to which commit might solve this issue, I can manually patch my OpenSSL to test it.

**Comment by paulidale** [comment]
There are a lot of changes between 1.1.1a and the latest 1.1.1.  I suggest trying each in turn -- either by inspecting the change and disregarding it or applying it.

One thing that does come to mind is the entropy source.  There were a lot of improvements to this throughout the life of 1.1.1 -- the most important being waiting for entropy to become available.  It would be possible that your platform is hitting this snag.  It's quite common on embedded devices.

**Comment by vh571964** [comment]
@paulidale 
>waiting for entropy to become available
Can you clarify the expected behavior if OpenSSL is waiting for an entropy source to become available? We do use a 3rd party chip in some of our HW platforms to generate entropy, but we've also seen this issue in platforms without said chip available. If the entropy source isn't available, will OpenSSL continue to use the old DRBG instance, or will it enter an error state?

In regards to walking through the changes between 1.1.1a and latest 1.1.1, as you mentioned there's a lot of changes. Do you have suggestions on narrowing down the set of changelists to look through? Else it'll be like looking for a needle in a haystack.

**Comment by paulidale** [comment]
1.1.1a seeds from /dev/urandom which always returns something even if it isn't seeded, so no error state.  I'm not sure this is the cause of the problem your are seeing but it is a relevant security issue.  Later versions of 1.1.1 seed properly and wait if required.

No, I can't help narrow things down significantly, the traces thus far haven't been  enlightening.  I.e. you'll be looking through the same haystack as I would be but you can access the hardware to test.

**Comment by vh571964** [comment]
Quick update, I haven't had much luck winnowing through the OpenSSL changelists. There are a lot, and nothing in particular leapt out to me as a possible root cause.

**Comment by t8m** [comment]
Could you please at least provide some simple isolated reproducer? It is really hard to do anything further with this issue without being able to reproduce the segfault.

**Comment by vh571964** [comment]
Temporarily closing the issue, as we're unable to locally reproduce. We've introduced a patch in our fork of OpenSSL to poison the cipher_data buffer on allocation; if crash is observed with poisoned buffer, then initialization was not executed and we can re-open this ticket.
