### ISSUE TITLE
install in kunpeng with newest version of openssl

### ISSUE THREAD

**Issue by rongmou1994** [openssl/openssl#17711]
when i try to install the newest version of openssl in kunpeng920,it failured.because kunpeng920 not support sha3 extension.how can i jump this?

**Comment by t8m** [comment]
Unfortunately we have no idea what kunpeng920 is. Also are you trying to install some pre-built openssl or are you building one of our releases by your own?

**Comment by mattcaswell** [comment]
> Unfortunately we have no idea what kunpeng920 is.

Google tells me its an ARM chip.

> when i try to install the newest version of openssl in kunpeng920,it failured.because kunpeng920 not support sha3 extension.how can i jump this?

So how does it "fail"? Is this a compilation or a runtime failure? Can you provide further details?

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
