### ISSUE TITLE
OpenSSL 3.0 and OpenSSL 1.x coexistence compatility 

### ISSUE THREAD

**Issue by wxt** [openssl/openssl#17728]
Hello,

We have recently consumed OpenSSL 3.0.1 in our product. However, we have few Open Source modules that are still compiled with OpenSSL 1.1.x and we can't upgrade them to use OpenSSL 3.0.x for various reasons. By including both versions of OpenSSL (.dll, .so) in the installation, the product and modules worked fine in our sanity test. However, we wanted to understand what kind of issues we may encounter if we proceed further with this approach. Our product runs on Windows, Linux and MacOS. Any suggestions and/or insights are highly appreciated.

**Comment by t8m** [comment]
Unless these independent modules try to share the internal data of the OpenSSL library across the different versions, this should be fine.

An example of broken scenario is to try to pass a pointer to an X509* certificate object or EVP_PKEY* object across the versions.

However the scenario where you link in an application two independent libraries that use different versions of OpenSSL to do unrelated things should work fine.
