### ISSUE TITLE
v3.0.1 Error Creating CA Signed Certificate using req Command

### ISSUE THREAD

**Issue by Andrewiski** [openssl/openssl#17736]
**Using OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)**

### Issue Description

I assume either REQ is not designed to sign a certificate using only the CA Key but reading the code it looks like it was intended to do so but the error "Must provide a signature key using -key" is returned. 
CA and CA Key are set and -in is csr so pkey == NULL  is true but shouldn't it be as I am passing in a CSR and not a Private Key

'''
if (newreq || gen_x509) {
        if (pkey == NULL /* can happen only if !newreq */) {
            BIO_printf(bio_err, "Must provide a signature key using -key\n");
            goto end;
        }
'''

### Steps to Reproduce

**Create CA Certs**
'''

openssl genpkey -quiet -algorithm RSA -out ca.localhost.pem.key -pkeyopt rsa_keygen_bits:4096
openssl req -verbose -x509 -subj "/CN=ca.localhost" -keyca.localhost.pem.key -addext "basicConstraints= critical,CA:TRUE,pathlen:1" -addext "keyUsage= critical,keyCertSign,cRLSign,digitalSignature,nonRepudiation,keyEncipherment" -addext "subjectKeyIdentifier= hash" -addext "authorityKeyIdentifier= keyid,issuer" -addext "extendedKeyUsage= serverAuth" -addext "subjectAltName= DNS:ca.localhost" -out ca.localhost.pem.crt

'''

**Create Signing Request**
'''
openssl genpkey -quiet -algorithm RSA -out dev.localhost.pem.key -pkeyopt rsa_keygen_bits:4096
openssl req -verbose -new -subj "/CN=dev.localhost" -key dev.localhost.pem.key -addext "basicConstraints= critical,CA:FALSE" -addext "keyUsage= digitalSignature, nonRepudiation, keyEncipherment" -addext "subjectKeyIdentifier= hash" -addext "extendedKeyUsage= serverAuth" -addext "subjectAltName= DNS:dev.localhost,DNS:www.dev.localhost,IP:127.0.0.1" -out dev.localhost.csr
'''

**Create Certificate using Signing Request and CA Certs**  -- This Fails with Error "Must provide a signature key using -key"

'''
openssl req -x509 -in dev.localhost.csr -days 999 -subj "/CN=dev.localhost" -CA ca.localhost.pem.crt -CAkey ca.localhost.pem.key -copy_extensions copy -addext "basicConstraints= critical,CA:TRUE,pathlen:1" -addext "keyUsage= critical,keyCertSign,cRLSign,digitalSignature,nonRepudiation,keyEncipherment" -addext "subjectKeyIdentifier= hash" -addext "authorityKeyIdentifier= keyid,issuer" -addext "extendedKeyUsage= serverAuth" -addext "subjectAltName= DNS:dev.localhost" -out dev.localhost.pem.crt
'''

I am able to sign the cert using the x509 cmd but I don't seem to be able to override the extensions like I can using -addext and req command.

Looking at the source code and Docs it would appear the intent was if -in is a CSR  then -key should not be passed and CSR can be signed by CA.

**Comment by hlandau** [comment]
Created a PR to fix this: https://github.com/openssl/openssl/pull/17782

**Comment by t8m** [comment]
Reopening as there needs to be a separate PR for 3.0 branch.

**Comment by hlandau** [comment]
@t8m Created, #17805.
