### ISSUE TITLE
X509_free

### ISSUE THREAD

**Issue by e2002e** [openssl/openssl#17732]
Hi, I am compiling code in which there is need for X509_free (it's ruby) but I see this function is no declared anywhere although there seem to be some kind of wrapper in the test/ossl_shim folder, which version should I use to intrinsically have X509_free function.

**Comment by t8m** [comment]
The function is declared by macros. It should be available by including openssl/x509.h however I do not know how that is handled with Ruby.

**Comment by e2002e** [comment]
Ruby compiles it's own openssl.so library using openssl, I saw nowhere in the code the X509_free function asis.
I thought that this function was created with another function or passed through a macro so that would explain it, but no.
I am certainly not using the correct version: tried with 1.1.1l, 1.1.1m. My header does NOT contain this declaration.

**Comment by t8m** [comment]
As I said the declaration is done via macro expansion - concretely the `DECLARE_ASN1_FUNCTIONS(X509)` in openssl/x509.h.
