### ISSUE TITLE
KTLS packet out of order in async/nonblocking and partial/moving mode

### ISSUE THREAD

**Issue by jay92834893** [openssl/openssl#17747]
I have problem creating this problem manually because it needs high async load to trigger, but since the problem disappears when I disable kTLS in the kernel I am quite sure it is kTLS-releated.

If I have 30 threads holding 500 open SSL sockets writing data asynchronously to all the 500 sockets. The 30 threads have a buffer they use to get inpud data and send to the SSL sockets with SSL_write. The receiving part of the SSL socket sometimes receive invalid data (but valid SSL packet).
SSL_CTX was created with ENABLE_PARTIAL_WRITE and ACCEPT_MOVING_WRITE_BUFFER
OpenSSL 3.0.1

I am not sure, but it may seem there is an issue with partial write/moving buffers in kTLS. Is this known perhaps?
The same code works fine without kTLS.

**Comment by mattcaswell** [comment]
> I am not sure, but it may seem there is an issue with partial write/moving buffers in kTLS. Is this known perhaps?

Not a known issue AFAIK.

But without something more concrete its going to be very difficult for us to narrow down :-(

**Comment by jay92834893** [comment]
I guess I need to find a way to trigger this bug in a better way. Ill be back :)
