### ISSUE TITLE
FIPS documentation outdated and contradictory

### ISSUE THREAD

**Issue by waldiTM** [openssl/openssl#17749]
Version is latest master (f596bbe4da779b56eea34d96168b557d78e1149a).

There is several FIPS related documentation in OpenSSL
* `README-FIPS.md`,
* `doc/man5/fips_config.pod`,
* `doc/man7/fips_module.pod`

Those are in parts outdated or contradict each other.

* The main FIPS README still talks about FIPS 140-2. This should 140-3?
* The main FIPS README asks the user to generate a FIPS module config by calling `openssl fipsinstall`, but the `fips_module` man page tells users to include the shipped `fipsmodule.cnf` into the main `openssl.cnf`. What is the preferred way?

**Comment by mattcaswell** [comment]
> The main FIPS README still talks about FIPS 140-2. This should 140-3?

No, the README is correct. Our in-progress validation was for 140-2.

**Comment by paulidale** [comment]
You should use `openssl fipsinstall` to generage the `fipsmodule.cnf` which you then include into the main `openssl.cnf`.
Seems the wording in fips_module isn't ideal.

**Comment by paulidale** [comment]
We don't ship a fipsmodule.cnf, it has to be generated but the fipsinstall process.  If an operating system includes this it is because they generated the file.  If this was not done on the machine the OS is running on, it won't be FIPS compliant.

**Comment by t8m** [comment]
@paulidale There are two checksums in fipsmodule.cnf. If the configuration checksum is not present and only the module binary checksum is, the self-tests will be always run on module load and that means having the fipsmodule.cnf generated on the build system and not on every deployment machine would still be compliant.

**Comment by paulidale** [comment]
Agreed, it can be set up this way but I view it as more prone for error (or deliberate bypassing).

**Comment by aniljadaun** [comment]
Hi @paulidale @t8m @mattcaswell 

I see @t8m mentioned if fipsmodule.cnf doesn't have configuration checksum but only the module binary checksum,In such case self-test will be run on module load and in such cases fipsmodule.cnf shipped with package would be considered fips compliant ?  Is this correct ?

**Comment by paulidale** [comment]
**No, such an installation would not be considered FIPS compliant.**

In what way wasn't this answered in the [discussion](https://github.com/openssl/openssl/discussions/21703) you raised?  Specifically @t8m's [comment](https://github.com/openssl/openssl/discussions/21703#discussioncomment-6691353) there that covers exactly this?

> For example fipsmodule.cnf without the install checksum means the FIPS module will perform the self tests on each start up so in the sense of compliance of FIPS module operational requirements this is compliant, but you would not be compliant with the security policy letter.

If you want to pursue this option, you should consult with a FIPS validation lab.  They can provide authoritative answers to FIPS compliance questions and possibly suggest a path you could follow.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
