### ISSUE TITLE
PSK ciphersuites at SECLEVEL=3

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#17743]
https://github.com/openssl/openssl/blob/7b3041eba1c6e177eede0d6311d53a6b9ff58051/ssl/ssl_cert.c#L1035-L1038 permits using only SSL_kEDH and SSL_kEECDH KEX modes because of Forward Security. In fact, SSL_kECDHEPSK and SSL_kDHEPSK are also forward-secure, so they may be missed here by accident.

Is it a bug or a design decision?

**Comment by tomato42** [comment]
Also, should we really disable the only post-quantum secure ciphersuites (SSL_kPSK) when user selected high security level?

**Comment by beldmit** [comment]
https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_security_level.html is SECLEVEL definiton thanks @mattcaswell

**Comment by beldmit** [comment]
https://security.stackexchange.com/questions/68293/forward-secrecy-in-tls-psk says PSK KEX doesn't provide PFS thanks @slontis

**Comment by paulidale** [comment]
@romen to investigate the forward security of these ciphersuites

**Comment by romen** [comment]
> @romen to investigate the forward security of these ciphersuites

During the OTC meeting today, I asked some time to check my notes for known problems (regarding PFS) about PSK +(EC)DHE ciphersuites, in versions of TLS before 1.3.
I have had time to check: consider my concerns cleared!

**Comment by beldmit** [comment]
@romen Do I correctly understand they match PFS requirements?

**Comment by romen** [comment]
As far as I can tell yes, `SSL_kECDHEPSK` and `SSL_kDHEPSK` should provide the required PFS guarantees expected at SECLEVEL=3

**Comment by romen** [comment]
Reopening for `1.1.1`, tackled by #17791

**Comment by romen** [comment]
Closing now that #17791 is merged for the `1.1.1` backport.
