### ISSUE TITLE
Unexpected behavior under Valgrind

### ISSUE THREAD

**Issue by iFuSiiOnzZ** [openssl/openssl#17751]
I am making use of OpenSSL through Poco to generate a client/server program. The problem I have is that the handshake (I think) fails randomly and sometimes even with different errors. The problem only happens under Valgrind, does anyone have any idea what it could be?

One of the errors:
```txt
name: SSL Exception
code: 0
className: Poco::Net::SSLException
message: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
displayText: SSL Exception: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
```

Another error:
```txt
name: SSL Exception
code: 0
className: Poco::Net::SSLException
message: error:140940F5:SSL routines:ssl3_read_bytes:unexpected record
displayText:  SSL Exception: error:140940F5:SSL routines:ssl3_read_bytes:unexpected record
```

And another error:
```txt
name: SSL Exception
code: 0
className: Poco::Net::SSLException
message: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
displayText:  SSL Exception: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

Development environment 
```txt
Poco: 1.9
Valgrind: 3.18.1
GCC 4.8.5
OS: Ubuntu 16.04 
```

EDIT: I have also noticed that sometimes the socket stays blocked, on a read for example, even if `shutdown` and `close` are called.

**Comment by t8m** [comment]
Unfortunately there is not much we can help with here. There is not enough information. Running things through valgrind should not break things though. It might very well be a valgrind bug given the old system version.

**Comment by iFuSiiOnzZ** [comment]
I think there is some kind of synchronization problem between the server and the client, don't know if it related to Poco layer because if I force the handshake works, needs more investigation, but anyway I will close the issue for now. Thank you!
