### ISSUE TITLE
include/openssl/applink.c missing in Windows builds

### ISSUE THREAD

**Issue by Thomas1664** [openssl/openssl#17767]
See #16570 
Version: 3.0.1
Platform: Windows

```
CMake Error at C:/a/1/s/scripts/buildsystems/vcpkg.cmake:572 (_add_library):
  Target "lua-ssl" links to target "OpenSSL::applink" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```
[Configuration](https://github.com/microsoft/vcpkg/blob/7249fa4d64ead1428249895810146134be8eb881/ports/openssl/windows/portfile.cmake)

Then `target_link_libraries([...] PRIVATE OpenSSL::applink)`

Note that the configuration and `OpenSSL::applink` work with OpenSSL 1.1.1m.

**Comment by florinspatar** [comment]
I just built OpenSSL 3.0.1 for Windows, and I can find `include/openssl/applink.c`

```
[fspatar@nx-server-x64c:~/new/trunk]$ unzip -t OPSWopenssl_fips-3.0.1.00-x64.zip | grep "applink.c"
    testing: OPSWopenssl_fips/3.0.1.00/x64/include/openssl/applink.c   OK
```

I can also see the file being copied in the build logs:

```
[...]
Thu Feb 24 04:59:29 2022:I  _rCI: *** Installing development files
Thu Feb 24 04:59:29 2022:I  _rCI: created directory `F:/build/fspatar/win32/6.3-X64/build/OPSWopenssl/install/OPSWopenssl_fips/3.0.1.00/x64/include'
Thu Feb 24 04:59:29 2022:I  _rCI: created directory `F:/build/fspatar/win32/6.3-X64/build/OPSWopenssl/install/OPSWopenssl_fips/3.0.1.00/x64/include/openssl'
Thu Feb 24 04:59:29 2022:I  _rCI: Copying: ./ms/applink.c to F:/build/fspatar/win32/6.3-X64/build/OPSWopenssl/install/OPSWopenssl_fips/3.0.1.00/x64/include/openssl/applink.c
Thu Feb 24 04:59:30 2022:I  _rCI: Copying: ./include/openssl/aes.h to F:/build/fspatar/win32/6.3-X64/build/OPSWopenssl/install/OPSWopenssl_fips/3.0.1.00/x64/include/openssl/aes.h
[...]
```

**Comment by Thomas1664** [comment]
> I just built OpenSSL 3.0.1 for Windows, and I can find `include/openssl/applink.c`
> 
> ```
> [fspatar@nx-server-x64c:~/new/trunk]$ unzip -t OPSWopenssl_fips-3.0.1.00-x64.zip | grep "applink.c"
>     testing: OPSWopenssl_fips/3.0.1.00/x64/include/openssl/applink.c   OK
> ```

It looks like you built it on Unix. However, I built in on my Windows machine and I can't find it.

**Comment by Thomas1664** [comment]
I further inspected CI logs and I could find it. Vcpkg builds openssl on its own. Is there anything in the build system that changed since 1.1.1m and may require adjusting our build system?

**Comment by levitte** [comment]
OpenSSL master branch:

``` console
$ grep -A1 applink Configurations/*.tmpl
Configurations/unix-Makefile.tmpl:	@$(ECHO) "install $(SRCDIR)/ms/applink.c -> $(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c"
Configurations/unix-Makefile.tmpl:	@cp $(SRCDIR)/ms/applink.c $(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c
Configurations/unix-Makefile.tmpl:	@chmod 644 $(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c
Configurations/unix-Makefile.tmpl-	@ : {- output_on() if $disabled{uplink}; "" -}
--
Configurations/unix-Makefile.tmpl:	@$(ECHO) "$(RM) $(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c"
Configurations/unix-Makefile.tmpl:	@$(RM) $(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c
Configurations/unix-Makefile.tmpl-	@ : {- output_on() if $disabled{uplink}; "" -}
--
Configurations/windows-makefile.tmpl:	@"$(PERL)" "$(SRCDIR)\util\copy.pl" "$(SRCDIR)\ms\applink.c" \
Configurations/windows-makefile.tmpl-				       "$(INSTALLTOP)\include\openssl"
```

OpenSSL 1.1.1 branch:

``` console
$ grep -A1 applink Configurations/*.tmpl
Configurations/unix-Makefile.tmpl:	@$(ECHO) "install $(SRCDIR)/ms/applink.c -> $(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c"
Configurations/unix-Makefile.tmpl:	@cp $(SRCDIR)/ms/applink.c "$(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c"
Configurations/unix-Makefile.tmpl:	@chmod 644 "$(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c"
Configurations/unix-Makefile.tmpl-	@ : {- output_on() unless grep { $_ eq "OPENSSL_USE_APPLINK" } (@{$target{defines}}, @{$config{defines}}); "" -}
--
Configurations/unix-Makefile.tmpl:	@$(ECHO) "$(RM) $(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c"
Configurations/unix-Makefile.tmpl:	@$(RM) "$(DESTDIR)$(INSTALLTOP)/include/openssl/applink.c"
Configurations/unix-Makefile.tmpl-	@ : {- output_on() unless grep { $_ eq "OPENSSL_USE_APPLINK" } (@{$target{defines}}, @{$config{defines}}); "" -}
--
Configurations/windows-makefile.tmpl:	@"$(PERL)" "$(SRCDIR)\util\copy.pl" "$(SRCDIR)\ms\applink.c" \
Configurations/windows-makefile.tmpl-				       "$(INSTALLTOP)\include\openssl"
```

Doesn't look like it changes much re installation.

However, I've found that Cmake's FindOpenSSL.cmake is making certain assumptions on Windows, it seems to be made to match a certain binary distribution with an installation layout *that isn't ours*

**Comment by levitte** [comment]
I had a look at FindOpenSSL.cmake, and indeed found that there was a bug that could result in this behavior.  It was fixed a few months ago:

https://gitlab.kitware.com/cmake/cmake/-/commit/586d483983a963ad2a73511080f591bc4aea8578

According to their current git history, this hasn't made it into a release yet, but will be part of Cmake 3.23, which is currently out as release candidate 2.

It may be that you'll have to patch your copy of FindOpenSSL.cmake, or build your own Cmake from their current release branch

**Comment by Thomas1664** [comment]
@levitte Because CMake can't build the target applink is it possible to build it manually using CMake?

**Comment by Thomas1664** [comment]
> I had a look at FindOpenSSL.cmake, and indeed found that there was a bug that could result in this behavior. It was fixed a few months ago:
> 
> https://gitlab.kitware.com/cmake/cmake/-/commit/586d483983a963ad2a73511080f591bc4aea8578
> 
> According to their current git history, this hasn't made it into a release yet, but will be part of Cmake 3.23, which is currently out as release candidate 2.
> 
> It may be that you'll have to patch your copy of FindOpenSSL.cmake, or build your own Cmake from their current release branch

@levitte This has no effect because ``if("${OPENSSL_VERSION_MAJOR}.${OPENSSL_VERSION_MAJOR}.${OPENSSL_VERSION_FIX}" VERSION_GREATER_EQUAL "0.9.8")`` would be true anyway because 3.3.1 is greater than 0.9.8.

The problem was that `OPENSSL_VERSION_MAJOR`, `OPENSSL_VERSION_MINOR` and `OPENSSL_VERSION_FIX` were not defined. It works now!

**Comment by levitte** [comment]
Ok, so this can be closed now?

**Comment by Thomas1664** [comment]
Yes, I think so
