### ISSUE TITLE
WIN64A build error: ssl/tls1.h: cannot parse: ()

### ISSUE THREAD

**Issue by MatrixManAtYrService** [openssl/openssl#1777]
Most of my team members can build OpenSSL_1_0_2j with no problem (Tested on Windows Server 2012 and Windows Server 2016), but two of them (Windows 7, Windows 8) experience the behavior described here: https://rt.openssl.org/Ticket/Display.html?id=4014 (user: `guest` password: `guest`)

The Powershell script that carries out the build is below:

```
param ( [string]$OpenSSLRoot = "C:\usr\local\OpenSSL" )
perl Configure debug-VC-WIN64A --prefix=$OpenSSLRoot
ms\do_win64a
cmd /c "`"${env:VS140COMNTOOLS}../../VC/vcvarsall.bat`" amd64 && nmake /f ms\nt.mak && nmake /f ms\nt.mak install"
```

This is described in more detail in the referenced bug, but his build halts after the following output:

```
>perl util\mkdef.pl 32 libeay                                        
1>ms\libeay32.def
File ssl/tls1.h: cannot parse: ()
#INFO::;
File ssl/tls1.h: cannot parse: ()
```

Any ideas about what might be making his machine different?

**Comment by mattcaswell** [comment]
Maybe perl version??

**Comment by MatrixManAtYrService** [comment]
The machines with the problem are both using v5.22.0, while the machines without have 5.24.0 or 5.22.1 seems close enough that a breaking change is unlikely, but I'm not familiar with the ways of perl.

**Comment by mattcaswell** [comment]
Right...but where did you get your perl from? It can make all the difference....ActiveState, Strawberry, mingw, cygwin etc.

**Comment by MatrixManAtYrService** [comment]
Unfortunately, IT-guy is already re-imaging the problematic machines with windows 10, so I can't check.  I know that one of the working machines was using ActiveState and the other two were using Strawberry.

If new details emerge when we try to use the re-imaged machines, I'll report back here.  If not, I'll go ahead and close this since we can't troubleshoot further.

**Comment by MatrixManAtYrService** [comment]
I ran across the issue again.  It occurs if I install git bash and during the install process check "Run Git and included Unix tools from the Windows Command Prompt".  

It goes away if I install Strawberry Perl and then modify my path so that the strawberry perl bin directory comes first.
