### ISSUE TITLE
Openssl git master build failure cross building Debian Stretch x86_64 to Debian Stretch arm64

### ISSUE THREAD

**Issue by userdocs** [openssl/openssl#17773]
I have an action that was compiling, successfully, openssl on multiple Debian based platforms.

All the configuration and settings are viewable in the modular actions steps.

https://github.com/userdocs/openssl-crossbuild/runs/5345431576?check_suite_focus=true

![image](https://user-images.githubusercontent.com/16525024/155853276-83948315-f756-4502-8429-d14f0c6cdeda.png)

Note about this build

I use action built [cmake ](https://github.com/userdocs/cmake-crossbuild/releases/latest)+ [zlib-ng 1.2.11](https://github.com/userdocs/zlib-ng-crossbuild/releases/latest) (compatibility mode) but it was working fine previously and it's only recently the build started failing on this OS + arch

It's failing on arm64 + Stretch and this is where it fails

```bash
aarch64-linux-gnu-gcc  -Icrypto -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DECP_NISTZ256_ASM -DKECCAK1600_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DOPENSSL_SM3_ASM -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DSM4_ASM -DVPAES_ASM -fPIC -pthread -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/etc/ssl\"" -DENGINESDIR="\"/root/build/opt/local/lib/engines-3\"" -DMODULESDIR="\"/root/build/opt/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include -c -o crypto/modes/libcrypto-shlib-aes-gcm-armv8-unroll8_64.o crypto/modes/aes-gcm-armv8-unroll8_64.S
crypto/modes/aes-gcm-armv8-unroll8_64.S: Assembler messages:
crypto/modes/aes-gcm-armv8-unroll8_64.S:5: Error: unknown architectural extension `sha3'
Makefile:9942: recipe for target 'crypto/modes/libcrypto-shlib-aes-gcm-armv8-unroll8_64.o' failed
make[1]: *** [crypto/modes/libcrypto-shlib-aes-gcm-armv8-unroll8_64.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/openssl'
make: *** [build_sw] Error 2
Makefile:3239: recipe for target 'build_sw' failed
Error: Process completed with exit code 2.
```

I have tried to google the error code but it does not help me.

Can anyone help me understand what might be going wrong?

**Comment by t8m** [comment]
This is regression on older assemblers from #15916

@xkqian Could you please look?

**Comment by xkqian** [comment]
Sure， seems it's caused by the compiler versions. I will triage it.
