### ISSUE TITLE
Segmentation Fault when using openssl ca (v1.1.1)

### ISSUE THREAD

**Issue by PierFio** [openssl/openssl#17772]
Having a config file with:
```
rand_serial    = yes
```
produces a segmentation fault in the rotation between the old and new database text files when using openssl ca.

I am using a fresh openssl built:
```
OpenSSL 1.1.1  11 Sep 2018 (Library: OpenSSL 1.1.1m  14 Dec 2021)
built on: Fri Feb 25 16:13:19 2022 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(8x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
Seeding source: os-specific
```

Commenting out the option makes the command terminate successfully.
This looks like a regression identical to issue #7412: Segmentation fault: 11 when using 'ca' command in 1.1.1

**Comment by t8m** [comment]
Please note that the bug is in the openssl application not in the library and you're apparently running the old 1.1.1 application against the current library.

See the version info:

> OpenSSL 1.1.1  11 Sep 2018 (Library: OpenSSL 1.1.1m  14 Dec 2021)
