### ISSUE TITLE
Windows RD Gateway manager Certificate import wizard is not taking the password set while creating .pfx

### ISSUE THREAD

**Issue by Zwithdtc** [openssl/openssl#17777]
I used the command below to created a .pfx file using the private key and the certificate.pem file. The command goes through and the .pfx is created, but when I go to import the .pfx with the Certificate Import Wizard in the windows remote desktop gateway manager, it does not accept the password that I put in the password.txt file. 

Is there a different password that is generated or a different one that I have to set? 

openssl pkcs12 -export  -inkey "c:\cert\private-key.txt" -in "C:\cert\certificate.pem" -out "c:\cert\createdcert.pfx" -passout "file:C:\cert\password.txt

![RD gateway manager](https://user-images.githubusercontent.com/100367660/156007964-58c543b3-02db-4c8a-a187-c1a2eac640fa.PNG)
"

**Comment by mattcaswell** [comment]
Are you using OpenSSL 3.0? If so, try using the "-legacy" argument to the pkcs12 app.

From the docs:
https://www.openssl.org/docs/man3.0/man1/openssl-pkcs12.html
````
-legacy
Use legacy mode of operation and automatically load the legacy provider.
If OpenSSL is not installed system-wide,
it is necessary to also use, for example, C<-provider-path ./providers>
or to set the environment variable B<OPENSSL_MODULES>
to point to the directory where the providers can be found.

In the legacy mode, the default algorithm for certificate encryption
is RC2_CBC or 3DES_CBC depending on whether the RC2 cipher is enabled
in the build. The default algorithm for private key encryption is 3DES_CBC.
If the legacy option is not specified, then the legacy provider is not loaded
and the default encryption algorithm for both certificates and private keys is
AES_256_CBC with PBKDF2 for key derivation.

````

**Comment by Zwithdtc** [comment]
> Are you using OpenSSL 3.0? If so, try using the "-legacy" argument to the pkcs12 app.
> 
> From the docs: https://www.openssl.org/docs/man3.0/man1/openssl-pkcs12.html
> 
> ```
> -legacy
> Use legacy mode of operation and automatically load the legacy provider.
> If OpenSSL is not installed system-wide,
> it is necessary to also use, for example, C<-provider-path ./providers>
> or to set the environment variable B<OPENSSL_MODULES>
> to point to the directory where the providers can be found.
> 
> In the legacy mode, the default algorithm for certificate encryption
> is RC2_CBC or 3DES_CBC depending on whether the RC2 cipher is enabled
> in the build. The default algorithm for private key encryption is 3DES_CBC.
> If the legacy option is not specified, then the legacy provider is not loaded
> and the default encryption algorithm for both certificates and private keys is
> AES_256_CBC with PBKDF2 for key derivation.
> ```

 I am using OpenSSL 3.0. I added the -legacy argument to the end of the command, and it returned the following: 
(Sorry for format, copying/pasting out of CMD is hell) 

pkcs12: unable to load provider legacy
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
10400000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\Program Files\OpenSSL\lib\ossl-
modules\legacy.dll)
10400000:error:12800067:DSO support routines:DSO_load:could not load the shared
library:crypto\dso\dso_lib.c:152:
10400000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto
\provider_core.c:907:name=legacy

**Comment by mattcaswell** [comment]
Looks like the legacy provider isn't installed where it expects to find it ("C:\Program Files\OpenSSL\lib\ossl-
modules\legacy.dll"). Possibly you have it in a non-standard location somewhere? Did you build OpenSSL yourself or did you download a precompiled version? If precompiled which versions did you use? OpenSSL will include legacy support by default but it is possible to turn it off at compile time. It's possible that your precompiled version does not have the legacy support included - which would mean you are out of luck. :-(

**Comment by Zwithdtc** [comment]
> Looks like the legacy provider isn't installed where it expects to find it ("C:\Program Files\OpenSSL\lib\ossl- modules\legacy.dll"). Possibly you have it in a non-standard location somewhere? Did you build OpenSSL yourself or did you download a precompiled version? If precompiled which versions did you use? OpenSSL will include legacy support by default but it is possible to turn it off at compile time. It's possible that your precompiled version does not have the legacy support included - which would mean you are out of luck. :-(

I did use a precompiled version from https://slproweb.com/products/Win32OpenSSL.html . It does not look like there is a "ossl-
modules" folder in lib. Hopefully I can install and compile correctly.

**Comment by Zwithdtc** [comment]
> Follow the instructions in the error message. It's not able to find the legacy provider. It ought to be using the default configuration file; so check the path in the error message to see if `legacy.dll` is there. `openssl version -a` can also be used to discover the directory the providers ought to be located in. If `legacy.dll` is not there (i.e. you didn't really install it); then you may need to update the configuration file (found in the OPENSSLDIR from `openssl version-a`) to cause it to be loaded.

I found the config file, if I enable legacy in my precompiled version would it created the openssl-modules folder and create the legacy.dll?

**Comment by Zwithdtc** [comment]
> > I found the config file, if I enable legacy in my precompiled version would it created the openssl-modules folder and create the legacy.dll?
> 
> Probably not, as the precompiled version doesn't seem to include them (it really ought to). And enabling it in the configuration file just causes it to be loaded; it still needs to exist. Did you use the "light" version from that site?

I did not use the light version, it really does seem like it should be included. 

Will running the legacy mode resolve the issue? I can generate the .pfx file without the -passout argument, but the certificate importer still has the password prompt. Would using DES or RC2 instead of AES resolve this?

**Comment by mattcaswell** [comment]
Just enabling the legacy provider in the config file is probably not sufficient anyway even if it did exist.  The "-legacy" option to the pkcs12 app does a little more than just load the provider.

> Will running the legacy mode resolve the issue? I can generate the .pfx file without the -passout argument, but the certificate importer still has the password prompt. Would using DES or RC2 instead of AES resolve this?

It's difficult to say for sure without trying it. But I think it is highly likely that windows is expecting the old legacy algorithms and is barfing when it encounters something different.

**Comment by Zwithdtc** [comment]
> Just enabling the legacy provider in the config file is probably not sufficient anyway even if it did exist. The "-legacy" option to the pkcs12 app does a little more than just load the provider.
> 
> > Will running the legacy mode resolve the issue? I can generate the .pfx file without the -passout argument, but the certificate importer still has the password prompt. Would using DES or RC2 instead of AES resolve this?
> 
> It's difficult to say for sure without trying it. But I think it is highly likely that windows is expecting the old legacy algorithms and is barfing when it encounters something different.

I can try to setup and compile OpenSLL to get this working, crossing my fingers.

**Comment by mattcaswell** [comment]
Or you could try a different pre-built binary. There's a list here:
https://wiki.openssl.org/index.php/Binaries

**Comment by Zwithdtc** [comment]
> Or you could try a different pre-built binary. There's a list here: https://wiki.openssl.org/index.php/Binaries

You were absolutely right. I used the Firedaemon binary with the windows installer, which let me use the -legacy argument. Using the -legacy with -passout let me use the password specified in passwords.txt. 
Solution: 
 openssl pkcs12 -export  -inkey "c:\cert\private-key.txt" -in "C:\cert\certificate.pem" -out "c:\cert\createdcert.pfx" -passout "file:C:\cert\password.txt" -legacy

**Comment by mattcaswell** [comment]
Great. Glad you got it sorted.
