### ISSUE TITLE
Why does OpenSSL needs Mono CA certs in its search path?

### ISSUE THREAD

**Issue by egberts** [openssl/openssl#17771]
When it comes to auditing CA certificates, one needs to know WhAT and WHERE are the OpenSSL is picking up their CA certificates.

Executing the `update-ca-certificates --fresh` using `strace -f` has enabled me to compile a list of files read and written.

The list of files that are opened and read-only by OpenSSL are in the following order:

```bash
/etc/ca-certificates.conf file
/usr/share/ca-certificates/* directory
/usr/share/ca-certificates/mozilla/* directory
/usr/share/ca-certificates/*/* directory
/usr/local/share/ca-certificates/* directory
/usr/local/share/ca-certificates/*/* directory
/etc/ssl/certs directory
$CWD/<all-certs-read-before> files
/usr/lib/ssl/openssl.cnf file
/etc/ca-certificates/update.d directory
/etc/ca-certificates/update.d/jks-keystore directory
/etc/default/cacerts directory
/etc/java-11-openjdk/security/nss.cfg file
/usr/share/ca-certificates-java directory
/usr/lib/jvm/java-11-openjdk-amd64/lib/jvm.cfg file
/usr/share/ca-certificates-java/ca-certificates-java.jar file
/etc/ca-certificates/update.d/mono-keystore directory
/etc/mono/4.5/machine.config file
/etc/mono/assemblies/cert-sync/cert-sync.config file
/etc/mono/assemblies/Mono.Security/Mono.Security.config file
/etc/mono/assemblies/mscorlib/mscorlib.config file
/etc/mono/assemblies/System/System.config file
/etc/mono/config file
/etc/ssl/certs/ca-certificates.crt file
$HOME/.mono/config file
/usr/lib/mono/4.5/cert-sync.exe.config file
/usr/lib/mono/4.5/cert-sync.exe.config file
/usr/lib/mono/4.5/mscorlib.dll.config file
/usr/lib/mono/gac/Mono.Security/4.0.0.0_0738eb9f132ed765/Mono.Security.dll.config file
/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll.config file
/usr/share/.mono/certs/Trust/ski-*.cer file
/usr/share/.mono/certs/new-certs/XXXXXXXX.0 file
$CWD/openssl EXECUTABLE!!! (why look in $CWD?)
/usr/bin/openssl
/usr/local/bin/openssl
/usr/local/sbin/openssl
/usr/sbin/openssl (VERY STRANGE ordering of /usr/[local/][s]bin/
```

OpenSSl also write writes to the following text files:

```bash
$CWD/ca-certificates.txt
/etc/ssl/certs/java/cacerts
```

so, why is Mono engaged in Trusted CA input?

**Comment by egberts** [comment]
misordered lookup sequence of
Observation of update-ca-certificates.

I noticed a very strange ordering of looking for the openssl binary.

Probably should have been something in the (re)order of:

```
$CWD/openssl (probably should NOT have this entry)
/usr/local/sbin/openssl
/usr/local/bin/openssl
/usr/sbin/openssl
/usr/bin/openssl
```

Auditable Impact Toward CA Certificates
-------------
Probably should OUTPUT various ‘modules’ being touched up during the rebuilding of CA certificates:

* MONO
* OpenJDK Java 11
* Mozilla

then list the following

* OS System

Auditable Output of CA Certificates
----------
Probably should OUTPUT what various CREATION of files:

```
$CWD/ca-certificates.txt
/etc/ssl/certs/java/cacerts
```

Better Summarization
------
Probably should indicate those summarization AT THE END of its output, broken down by CA-CERTIFICATE MODULES. Like:

```
      OS System:
        Added:   0
        Deleted: 0
        Used:    0
      Mozilla package:
        Added:   0
        Deleted: 0
        Used:  129
      OpenJDK package:
        Added:   0
        Deleted: 0
        Used:   86
      MONO package:
        Added:   0
        Deleted: 0
        Used:   44
      Total Merge:   129

  Master File:  /usr/share/ca-certificates  (depends on distro)
  Master File:  /etc/ca-certificates
  Master File:  /etc/ssl/certs
  Master File:  /etc/pki/tls/certs
```

**Comment by levitte** [comment]
`update-ca-certificates` isn't an OpenSSL program.  As far as I understand, it ensures that all programs that may need to verify a certificate can do so against one unified store of CA certificates.  `update-ca-certificates` comes from Debian's package `ca-certificates`

Manual: https://manpages.debian.org/bullseye/ca-certificates/update-ca-certificates.8.en.html
Debian's package page: https://packages.debian.org/sid/ca-certificates
