### ISSUE TITLE
Allow all demos to be built automatically, test in CI

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#17806]
We should have a make target `demos` which builds the demos and ensure that this passes CI.

**Comment by paulidale** [comment]
Since demos are considered part of the documentation, I think this is appropriate for 3.0 as well.

**Comment by mattcaswell** [comment]
> Since demos are considered part of the documentation, I think this is appropriate for 3.0 as well.

I'm less sure about that. The demos are part of the documentation, but the build system is not.

**Comment by levitte** [comment]
I'd rather think that demos should be possible to build independently.  For Unix, it should be sufficient to assume that `cc` and universally available (POSIX?) tools are available.

**Comment by levitte** [comment]
... that being said, I see nothing really wrong with using them in tests...  I'm pondering if they should have a separate test suite.

**Comment by mattcaswell** [comment]
> ... that being said, I see nothing really wrong with using them in tests... I'm pondering if they should have a separate test suite.

These are not tests. They are demonstrations of how to use the APIs for documentation purposes. While it doesn't necessarily hurt to run them as part of the test suite I think their test value is relatively low. I also do not think we should litter the demos with lots of "ifdef" conditional defines based on what features are available or not. The demos should be as simple and clear as possible. So I rather think they should be targeted at a "default" build with standard options.

**Comment by levitte** [comment]
> ... So I rather think they should be targeted at a "default" build with standard options.

I didn't see that this was in dispute...  but for what it's worth, I agree

**Comment by paulidale** [comment]
@levitte, these are **not** tests.  That much is very clear to me.  They are essentially useless as tests beyond proving that the code builds (which is a really low target).  If there is any KAT here that isn't part of our main test suite, it's a bug in the test suite which needs to be rectified.

These programmes are part of our documentation -- a long awaited and missing part IMO.  Without the recent work by @hlandau, I don't think I'd have reached this conclusion so readily.  I've wanted better demo code for several years now but didn't realise how good/useful it would be.

@mattcaswell, I'm completely fine with a **new** `make` target that builds these for 3.0 -- so long as it is completely new.  I.e. it is only additions to our build system: effectively the same as our `new` configuration definition.  I'd would accept local makefiles as a fallback but they will be less reliable -- of course, both would be ideal.  Let's do this properly and get it right.  I doubt we'll ever get such a juicy chance to improve things again.

I'm also fine building these by default in master -- in fact I believe we should do this.  For 3.0, it requires an OTC discussion.

**Comment by nhorman** [comment]
this was completed as part of https://github.com/openssl/openssl/pull/24047
