### ISSUE TITLE
Will openssl use OPENSSL_NO_* in more source files?

### ISSUE THREAD

**Issue by liyi77** [openssl/openssl#17801]
Hi,
Such as use OPENSSL_NO_EC in all ec related files, I noticed that it had be used in some header:
https://github.com/openssl/openssl/blob/8bfb7506d210841f2ee4eda8afe96441a0e33fa5/include/crypto/ec.h#L24-L29
maybe openssl can use it widely like in .c files.

In some projects, such as EDK2, it is difficult to customize source files for compilation based on a feature, the usual practice is to add all source files to the compilation list and then use macro definitions to control whether to use the code in the files.

If we can use  OPENSSL_NO_* more widely, the customization will also be more flexible.

Thanks,
Yi

**Comment by paulidale** [comment]
Yes we will.  If there is something you think get included by mistake, feel free to submit a pull request fixing it.

**Comment by liyi77** [comment]
> Yes we will. If there is something you think gets included by mistake, feel free to submit a pull request fixing it.

Thanks for your information, and I am not sure how broad these macro definitions should cover.
For example: Can I use OPENSSL_NO_EC to include all files in openssl/crypto/ec/. ?

**Comment by levitte** [comment]
> > Yes we will. If there is something you think gets included by mistake, feel free to submit a pull request fixing it.
> 
> Thanks for your information, and I am not sure how broad these macro definitions should cover. For example: Can I use OPENSSL_NO_EC to include all files in openssl/crypto/ec/. ?

Actually, yes, that's exactly what we do...  There are a number of configuration options like `disable-ec`, where we don't only define a corresponding `OPENSSL_NO_` macro (`OPENSSL_NO_EC` in this case), but also skip over the corresponding directory in `crypto/` (`crypto/ec/` in this case) entirely.  There are a few of those directories where we don't do this, like `crypto/err/`...  that one is never skipped over, even though it's possible to configure with the option `disable-err`.

Here's the section of Configure that generically defines the `OPENSSL_NO_` macros as well as aggregates the set of directories to skip over.

https://github.com/openssl/openssl/blob/8bfb7506d210841f2ee4eda8afe96441a0e33fa5/Configure#L1787-L1828

**Comment by liyi77** [comment]
> Actually, yes, that's exactly what we do... 

Thanks, got it.
And my idea is to directly use those macro definition in the files. 
For some project's compilation architectures, such as UEFI, it is inconvenient to 'skip' some files in the compilation list through options, and directly use the macro definition to make unnecessary files empty will be better.
I am glad to work on it if this idea can be confirmed.

**Comment by levitte** [comment]
> ... and directly use the macro definition to make unnecessary files empty will be better. I am glad to work on it if this idea can be confirmed.

There are files where we do just that.  However, do note that some compilers do not like to create empty object files.  To mitigate that, we have an internal macro `NON_EMPTY_TRANSLATION_UNIT` doing the magic.  I suggest you grep for that macro to see how we use it.

**Comment by liyi77** [comment]
> There are files where we do just that. However, do note that some compilers do not like to create empty object files. To mitigate that, we have an internal macro `NON_EMPTY_TRANSLATION_UNIT` doing the magic. I suggest you grep for that macro to see how we use it.

Very useful, thanks. I will handle this case with care.

**Comment by t8m** [comment]
@levitte @mattcaswell But when we were developing 3.0 we actually actively dropped the `#ifndef OPENSSL_NO_XXX` from files that would be empty in that case and adjusted build.info files instead to skip these.

I do not think we want to reintroduce these guards in files where the whole file should be skipped.

**Comment by levitte** [comment]
> @levitte @mattcaswell But when we were developing 3.0 we actually actively dropped the `#ifndef OPENSSL_NO_XXX` from files that would be empty in that case and adjusted build.info files instead to skip these.
> 
> I do not think we want to reintroduce these guards in files where the whole file should be skipped.

Yes and no.  We've done what you say for some individual files, but not for whole directories, see the very unconditional SUBDIRS in crypto/build.info:

https://github.com/openssl/openssl/blob/065442165a3d339a7de469b4cd18a3f902c73443/crypto/build.info#L3-L9

... and yes, we could arguably make the addition of subdirectories to SUBDIRS conditional, and through away the hard coded hack in Configure.

**Comment by liyi77** [comment]
> Yes and no. We've done what you say for some individual files, but not for whole directories, see the very unconditional SUBDIRS in crypto/build.info:
> ... and yes, we could arguably make the addition of subdirectories to SUBDIRS conditional, and throw away the hard coded hack in Configure.

Forgive my ignorance, I don't really know the history of this part of the code, does it means 'some individual files' related macro defines guards in files will be dropped, like 'no_egd'; And whole directories related macro defines guards can be used in files still, like 'no_ec'?

The openssl in EDK2 will definitely be upgraded to 3.0 in the future, I'm afraid I need to seek a clear answer:

Will openssl community accept to add directories related macro defines guards to all files in directories? If so, will openssl3 follow?

Any way, if it is inconsistent with the design goals of openssl community, I will also understand and will look for other ways to solve customization.

**Comment by levitte** [comment]
Well, quite frankly, that part isn't entirely consistent.  There are three existing methods:

-    using the `OPENSSL_NO_` macros to disable a whole translation unit (source file).  In 3.0, this seems to have been reduced to the error table source files:

https://github.com/openssl/openssl/blob/2cc7c9b6981d683711e76c3483f813701b686eb9/crypto/sm2/sm2_err.c#L14-L50

-   The Configure hack that I displayed above
-   `build.info` conditions:

https://github.com/openssl/openssl/blob/2cc7c9b6981d683711e76c3483f813701b686eb9/build.info#L4-L10
https://github.com/openssl/openssl/blob/2cc7c9b6981d683711e76c3483f813701b686eb9/apps/build.info#L5-L10

It's true, as @t8m says, that we've increasingly moved to the `build.info` conditions to determine what source files go in or not.  I'm sorry for leading you astray with the `OPENSSL_NO_` discussion.

(more in the next comment)

**Comment by levitte** [comment]
> I will also understand and will look for other ways to solve customization.

Your specific question is really to know exactly what files are included for a certain configuration, isn't it?  I had forgotten this yesterday, but there is another way:

``` console
$ Configure no-asm
Configuring OpenSSL version 3.0.1 for target linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Running configdata.pm
Creating Makefile.in
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************
$ ./configdata.pm -q 'get_sources("libcrypto")' | grep crypto/ec/
  crypto/ec/ec_pmeth.c \
  crypto/ec/ec_oct.c \
  crypto/ec/ec2_oct.c \
  crypto/ec/eck_prn.c \
  crypto/ec/ec_asn1.c \
  crypto/ec/curve448/arch_32/f_impl32.c \
  crypto/ec/ec_err.c \
  crypto/ec/ec_cvt.c \
  crypto/ec/ec_check.c \
  crypto/ec/ec_key.c \
  crypto/ec/ecx_key.c \
  crypto/ec/curve448/curve448_tables.c \
  crypto/ec/curve25519.c \
  crypto/ec/ec_ameth.c \
  crypto/ec/curve448/arch_64/f_impl64.c \
  crypto/ec/curve448/scalar.c \
  crypto/ec/ecp_oct.c \
  crypto/ec/ec_backend.c \
  crypto/ec/ec_kmeth.c \
  crypto/ec/ec_deprecated.c \
  crypto/ec/ecp_smpl.c \
  crypto/ec/ecdh_kdf.c \
  crypto/ec/curve448/f_generic.c \
  crypto/ec/ecx_meth.c \
  crypto/ec/curve448/eddsa.c \
  crypto/ec/ecdsa_ossl.c \
  crypto/ec/ecp_nist.c \
  crypto/ec/ec2_smpl.c \
  crypto/ec/ec_lib.c \
  crypto/ec/ec_curve.c \
  crypto/ec/curve448/curve448.c \
  crypto/ec/ecdh_ossl.c \
  crypto/ec/ecdsa_sign.c \
  crypto/ec/ecp_mont.c \
  crypto/ec/ec_print.c \
  crypto/ec/ec_mult.c \
  crypto/ec/ecdsa_vrf.c \
  crypto/ec/ecx_backend.c \
```

`configdata.pm` only supports the `--query` / `-q` option in OpenSSL 3.0.  However, it's quite easy to re-create it with a simple perl script:

``` perl
#!/usr/bin/perl

use OpenSSL::Config::Query;
use lib '.';
use configdata;

my $confquery = OpenSSL::Config::Query->new(info => \%unified_info,
                                            config => \%config);
my $result = $confquery->get_sources("libcrypto");

print $_, "\n" foreach @{$result->{libcrypto}};
```

Here's the result for 1.1.1, using OpenSSL::Config::Query from 3.0:

``` console
$ ./config no-asm
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1m (0x101010dfL) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
$ perl -I ../openssl-3.0.1/util/perl get_sources.pl | grep crypto/ec/
crypto/ec/ecx_meth.c
crypto/ec/eck_prn.c
crypto/ec/ec_pmeth.c
crypto/ec/ec_key.c
crypto/ec/ec2_oct.c
crypto/ec/ecp_nistp224.c
crypto/ec/ec_check.c
crypto/ec/ecdsa_vrf.c
crypto/ec/ecp_nistp521.c
crypto/ec/ec_err.c
crypto/ec/ecp_oct.c
crypto/ec/curve448/eddsa.c
crypto/ec/ecdsa_ossl.c
crypto/ec/ec_ameth.c
crypto/ec/ec_asn1.c
crypto/ec/ecdh_ossl.c
crypto/ec/curve448/curve448.c
crypto/ec/ec_lib.c
crypto/ec/curve25519.c
crypto/ec/ec_cvt.c
crypto/ec/ec_mult.c
crypto/ec/curve448/curve448_tables.c
crypto/ec/ec_oct.c
crypto/ec/ec_kmeth.c
crypto/ec/ecp_smpl.c
crypto/ec/ecp_nistputil.c
crypto/ec/ecp_nist.c
crypto/ec/ecdsa_sign.c
crypto/ec/ecdh_kdf.c
crypto/ec/ecp_nistp256.c
crypto/ec/ec_print.c
crypto/ec/ec_curve.c
crypto/ec/ecp_mont.c
crypto/ec/curve448/arch_32/f_impl.c
crypto/ec/curve448/f_generic.c
crypto/ec/ec2_smpl.c
crypto/ec/curve448/scalar.c
```

**Comment by liyi77** [comment]
Thanks very much, those make it more clear to me.

Actually, it is a sad story about bad compilation process of UEFI,
We only can put all source files to an INF file(roles like makefile):
https://github.com/tianocore/edk2/blob/4a68176cb548902cad93e6ebb5957d0cac94d297/CryptoPkg/Library/OpensslLib/OpensslLib.inf#L25-L34
Once put in, it must be compiled, no way to skip some files depend on 'option's.
We do not want there are so many INF files like OpensslEcLib/Ec&TlsLib/Ec&Tls&RsaLib/.inf, it looks like workaround and very ugly.
Today new crypto features and openssl 3.0 all be blocked due to binary size,
And the optimization of the relevant compilation process has been stagnant for three years :(

Just some digression, thanks again for your support.
