### ISSUE TITLE
openssl should not require keyCertSign in key-usage for non-CA self-signed certs

### ISSUE THREAD

**Issue by manishahluwalia** [openssl/openssl#1780]
Starting with [this fix](https://github.com/openssl/openssl/commit/f51e5ed6b4b91d12228da873db72aa28109d1797) openssl has the behavior that a self-signed cert must have the keyCertSign asserted in key usage (assuming the cert contains a key-usage) even if it is not a CA cert (e.g. a self signed TLS server cert).

According to the [key-usage section of the RFC](https://tools.ietf.org/html/rfc5280#section-4.2.1.3)
```
… If the
keyCertSign bit is asserted, then the cA bit in the basic
constraints extension (Section 4.2.1.9) MUST also be asserted.
```
Hence, openssl seems to be requiring non-CA end-entity certs be non-conforming before it will successfully verify them.

**Comment by dcooper16** [comment]
Hi @manishahluwalia ,

See issue #1418.

**Comment by manishahluwalia** [comment]
@dcooper16 , thanks for the cross-reference. I think your analysis and recommendation on #1418 are excellent. I will mark this one as a duplicate.

**Comment by manishahluwalia** [comment]
Actually, I can't figure out how to mark this issue as a duplicate. I'm sure the openssl committers can.

**Comment by richsalz** [comment]
:)  See #1418
