### ISSUE TITLE
Commit emails missing since 2022-02-25

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#17817]
This is about an OpenSSL project infrastruture issue. I didn't know a better place to report, sorry.

The last commit email I received via openssl-commits@openssl.org for either the 1.1.1, 3.0 or main branch was Feb 9th (1.1.1) and Feb 24th (3.0, main). It seems something is broken or has changed since Feb 25th.

Thanks and regards,

Rainer

**Comment by t8m** [comment]
I think it is not really mysterious given the migration from gitolite to ghe for the primary repository.

**Comment by mspncp** [comment]
> I think it is not really mysterious given the migration from gitolite to ghe for the primary repository.

Did we actually publicly announce that the ‚blessed‘ repository has moved? 🤔

**Comment by mspncp** [comment]
> The last commit email I received via [openssl-commits@openssl.org](mailto:openssl-commits@openssl.org) for either the 1.1.1, 3.0 or main branch was Feb 9th (1.1.1) and Feb 24th (3.0, main). It seems something is broken or has changed since Feb 25th.

I wonder whether these email updates are still in keeping with the times. Anyone could simply watch the GitHub repo for those push events.

**Comment by kaduk** [comment]
> I wonder whether these email updates are still in keeping with the times. Anyone could simply watch the GitHub repo for those push events.

I don't think it's a particularly analogous experience.  GitHub doesn't send notifications on pushes to the repo, just on PR merge/closure, which should be correlated per our process but there is no technical enforcement thereof.
And the commit mails include the actual commit contents, which github notifications do not.

**Comment by t8m** [comment]
The e-mails are generated and I receive them. @rainerjung are you subscribed to the openssl-commits mailing list?

**Comment by t8m** [comment]
You can see the e-mails in the archive: https://mta.openssl.org/pipermail/openssl-commits/2022-June/thread.html

**Comment by rainerjung** [comment]
Thank you. I am subscribed and indeed I get the mails. I was used to the nice feature of seeing the branch name in the subject. That's why I though mails for the 1.1.1 and 3.0 branches do not arrive. But in fact they do.

The public unavailability of the diffs is unfortunate, but for me as the reporter of the missing emails issue it would be fine to close this issue here.
