### ISSUE TITLE
Build problem on Solaris 8

### ISSUE THREAD

**Issue by teschulz** [openssl/openssl#1781]
I am trying to build openssl 1.1.0b on a Solaris 8 sparc box. Building on Solaris 10 sparc with the same
configure command works OK. The Configure command line is:

./Configure shared --prefix=/opt/verylocal enable-rc5 enable-mdc2 zlib-dynamic  -I/opt/verylocal
/include -R/opt/verylocal/lib solaris-sparcv9-cc

Perl is v5.22.2 and C is Forte Developer 7 C 5.4.

Make finishes without error and all the libraries are made. But if I type make test or just make, make
now complains as follows:

> gmake
> gmake depend && gmake _all
> gmake[1]: Entering directory `/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake[1]: Leaving directory`/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake[1]: Entering directory `/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake[1]: *** No rule to make target`crypto/co', needed by `libcrypto.a'. Stop.
> gmake[1]: Leaving directory`/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake: **\* [all] Error 2

If I create an empty crypto/co  with touch, make now proceeds to add crypto/co to libcrypto.a  and
then recreate the shared libraries and re-link everything. Now I can run make test without finding
any missing files.

**Comment by levitte** [comment]
Hmmmm...  I'm going to venture a guess that something is wrong in the Makefile, *or* that gmake has a line length limit.  I'd like to suggest that you have a look in Makefile, search for `libcrypto.a:` and have a look at the dependencies and see if it looks ok or if it's broken off somewhere.  A warning, the list of dependencies is rather larger and in one long line...

**Comment by teschulz** [comment]
The line is truncated. I thought I searched for 'crypto/co' in the Makefile but I must have done that wrong.

A few tests that I have done:

After Configure is run the dependencies line is not truncated. So the problem is not with Configure.
I ran make depend. The line is still not truncated.
Ran make depend a second time. The line is still not truncated.
Ran make. The build completes with no errors. The line is still not truncated.
Ran make depend. The Makefile was rewritten and the line is now truncated. So whatever rewrites the Makefile is truncating the dependencies line.

If I do all of this on a Solaris 10 machine, the truncation  does not occur. But I do need a build for Solaris 8.

**Comment by levitte** [comment]
Ok, that sounds like `sed` truncates lines.  Try this:

    perl -e 'my $num = 3277; print "0123456789" x $num, "\n";' | sed -e '/^# DO NOT DELETE THIS LINE.*/,$d' | wc -c

The correct output is `32771` (the formula is `$num * 10 + 1`).

If you get the expected output according to formula, try doubling the `$num` value until you don't.  I'm guessing that's going to correspond to the line length of that truncated line.

If my guess is correct, I'll work on a fix.

**Comment by levitte** [comment]
Alternatively, you can simply apply this patch and test it:

``` diff
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index c24ba62..b263832 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -302,7 +302,7 @@ distclean: clean
 depend:
        @: {- output_off() if $disabled{makedepend}; "" -}
        @if egrep "^# DO NOT DELETE THIS LINE" Makefile >/dev/null && [ -z "`find $(DEPS) -newer Makefile 2>/dev/null; exit 0`" ]; then :; else \
-         ( sed -e '/^# DO NOT DELETE THIS LINE.*/,$$d' < Makefile; \
+         ( $(PERL) -pe 'exit 0 if /^# DO NOT DELETE THIS LINE.*/' < Makefile; \
            echo '# DO NOT DELETE THIS LINE -- make depend depends on it.'; \
            echo; \
            for f in $(DEPS); do \
```

**Comment by teschulz** [comment]
It is sed that  is doing the truncate. The switch to perl fixes it.

**Comment by levitte** [comment]
Perfect, thank you for the feedback.

Closing this.
