### ISSUE TITLE
OpenSSL 3.x: Test error in test/run_tests.pl when using Perl without TAP::Parser::Aggregator

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#17818]
Running the unit tests immediately gives:

`Can't call method "has_errors" without a package or object reference at ./test/run_tests.pl line 312.`

Commit 7e8d6bafd0347de8653c336e6f067d8f3686a386 introduced the following hunk:

```
@@ -305,6 +307,10 @@ sub find_matching_tests {
 
 my $harness = $package->new(\%tapargs);
 my $ret =
+    $harness->runtests(map { [ abs2rel($_, rel2abs(curdir())), basename($_) ] }
+                       @preps);
+die if $ret->has_errors;
+$ret =
     $harness->runtests(map { [ abs2rel($_, rel2abs(curdir())), basename($_) ] }
                        sort { reorder($a) cmp reorder($b) } keys %tests);
```
 
Directly under this snippet the old code also uses has_error but only conditionally:

```
# If this is a TAP::Parser::Aggregator, $ret->has_errors is the count of
# tests that failed.  We don't bother with that exact number, just exit
# with an appropriate exit code when it isn't zero.
if (ref($ret) eq "TAP::Parser::Aggregator") {
    exit 0 unless $ret->has_errors;
```

The script run_tests.pl is written, so that TAP::Parser is optional. The new unconditional use of has_errors breaks that. If that module is now needed, it should be added to the Perl NOTES in the main directory.
Thanks and regards,
Rainer

**Comment by t8m** [comment]
@levitte should we make TAP:Parser mandatory or change the die condition to:

`die if ref($ret) eq "TAP::Parser::Aggregator" && $ret->has_errors;` ?

**Comment by hlandau** [comment]
Was just about to make a PR with the above tweak.
