### ISSUE TITLE
Reusing existing HMAC key not possible via EVP_MAC_init()

### ISSUE THREAD

**Issue by tobiasbrunner** [openssl/openssl#17811]
https://github.com/openssl/openssl/blob/2cc7c9b6981d683711e76c3483f813701b686eb9/providers/implementations/macs/hmac_prov.c#L172-L183

Since the above function does not call `hmac_setkey()` if no key is passed, it does not preserve the semantics of `HMAC_Init_ex()`, which allowed resetting the internal state but reusing the existing key. Is that on purpose?

**Comment by t8m** [comment]
This truly looks like a bug as the operation (apart from the hmac_set_ctx_params() call) looks like a no-op and that is something I would not expect.

**Comment by mattcaswell** [comment]
> This truly looks like a bug as the operation (apart from the hmac_set_ctx_params() call) looks like a no-op and that is something I would not expect.

Huh? It's only a no-op if key is NULL.

**Comment by t8m** [comment]
> Huh? It's only a no-op if key is NULL.

I mean that if key is NULL it's a no-op and successful no-op, which is very surprising, because it actually won't reset the internal `HMAC_CTX *`. This means everything will work fine but the HMAC calculated will be wrong.

**Comment by t8m** [comment]
If we did not have this possibility to reset the context without setting a key with HMAC_Init_ex() I'd say just keep things as is, however this behavior is useful for performance critical things and it was supported with the HMAC_Init_ex() call.

**Comment by xnox** [comment]
Note to self if this is fixed in all the distributions or not. And if there are gaps alert them.

**Comment by xnox** [comment]
Looks like RHEL 9.0 and derivatives are affected, but also likely too old to attempt to fix this.

RHEL 9.1 is EOL.
RHEL 9.2 is unaffected / resolved.
