### ISSUE TITLE
test_asn1_time fails on NonStop

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#17816]
As of commit 4c8cdcd1cf, a new test failure is added to the set of failing tests as follows:
```
    ok 6 - test_time_dup
        # Subtest: convert_asn1_to_time_t
        1..5
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:436
        # [210327235959Z] compared to [210328005959Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:438
        # asn1_string_to_time_t (210328005959Z) failed: expected 1616893199, got 1616889599
        #
        # OPENSSL_TEST_RAND_ORDER=1646484877
        not ok 72 - iteration 1
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:436
        # [210328000000Z] compared to [210328010000Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:438
        # asn1_string_to_time_t (210328010000Z) failed: expected 1616893200, got 1616889600
        #
        # OPENSSL_TEST_RAND_ORDER=1646484877
        not ok 73 - iteration 2
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:436
        # [210327235959Z] compared to [210328005959Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:438
        # asn1_string_to_time_t (20210328015959+0100) failed: expected 1616893199, got 1616889599
        #
        # OPENSSL_TEST_RAND_ORDER=1646484877
        not ok 74 - iteration 3
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:436
        # [210328000000Z] compared to [210328010000Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.0/test/asn1_time_test.c:438
        # asn1_string_to_time_t (20210328030000+0200) failed: expected 1616893200, got 1616889600
        #
        # OPENSSL_TEST_RAND_ORDER=1646484877
        not ok 75 - iteration 4
        ok 76 - iteration 5
    # OPENSSL_TEST_RAND_ORDER=1646484877
    not ok 7 - convert_asn1_to_time_t
../../util/wrap.pl ../../test/asn1_time_test => 255
not ok 1 - running asn1_time_test

#   Failed test 'running asn1_time_test'
#   at /home/ituglib/randall/openssl-3.0/util/perl/OpenSSL/Test/Simple.pm line 77.
```

**Comment by t8m** [comment]
@rsbeckerca do you have any idea what could be the cause? Apparently the timezone variable contains something wrong in NonStop. Does NonStop have timegm() function? If so would you please try building with this `#ifdef` https://github.com/openssl/openssl/blob/master/crypto/asn1/a_time.c#L600 replaced with `#if 1` ?

**Comment by rsbeckerca** [comment]
> @rsbeckerca do you have any idea what could be the cause? Apparently the timezone variable contains something wrong in NonStop. Does NonStop have timegm() function? If so would you please try building with this `#ifdef` https://github.com/openssl/openssl/blob/master/crypto/asn1/a_time.c#L600 replaced with `#if 1` ?

There is no `timegm()` function on the platform. What assumptions are being made here? Is there a simple test I can try in isolation? Currently, `time_t` is only 32 bits (long). There is a `time64_t`, in `sys/types.h`, but no way to get a time value other than through `stat64()`. I can create a synthetic `time64(time64_t*)` function for the box, but the timezone converts are not there.

**Comment by t8m** [comment]
It isn't a problem with 64 bit time_t value. Rather, it's a problem with the contents of timezone. I have strong suspicion that the current code isn't right not only on NonStop but also in other circumstances.

**Comment by t8m** [comment]
Could you please dump what are the contents of timestamp_tm and timezone when the timestamp_local is calculated?

**Comment by rsbeckerca** [comment]
> Could you please dump what are the contents of timestamp_tm and timezone when the timestamp_local is calculated?

Sure. Will try to find an appropriate place - suggestions would save time.

**Comment by t8m** [comment]
For example here: https://github.com/openssl/openssl/blob/e9492d1cecf459261f1f5ac0eb03e9c631600537/crypto/asn1/a_time.c#L632

**Comment by rsbeckerca** [comment]
> Could you please dump what are the contents of timestamp_tm and timezone when the timestamp_local is calculated?

```
(xInspect 3,941):p *timestamp_tm
$2 = {
  tm_sec = 59,
  tm_min = 59,
  tm_hour = 0,
  tm_mday = 28,
  tm_mon = 2,
  tm_year = 121,
  tm_wday = 0,
  tm_yday = 86,
  tm_isdst = 1
}
(xInspect 3,941):p timestamp_local
$3 = 1616914799
```

**Comment by rsbeckerca** [comment]
What the system actually reports is (when just run now):
```
tm_sec=25
tm_min=49
tm_hour=14
tm_mday=7
tm_mon=2
tm_year=122
tm_wday=1
tm_yday=65
tm_isdst=0
```

**Comment by t8m** [comment]
And the timezone global variable contents?

**Comment by t8m** [comment]
The time in timestamp_tm is not a current system time but a time from the test data. But yeah I actually wonder how is the code supposed to work when the current time and the timestamp_tm daylight saving time differs.

**Comment by rsbeckerca** [comment]
@t8m The call that is failing is `asn1_string_to_time_t (asn1_string=0x8001350 "210328005959Z")`. This time is across the Epoc boundary and cannot be represented in 32-bit time_t. I don't have a variable `timezone` in the process context. Not sure why not.
```
(xInspect 2,696):l
   627
   628      #ifdef USE_TIMEGM
   629          timestamp_utc = timegm(timestamp_tm);
   630          OPENSSL_free(timestamp_tm);
   631      #else
*  632          timestamp_local = mktime(timestamp_tm);
   633          OPENSSL_free(timestamp_tm);
   634
   635          timestamp_utc = timestamp_local - timezone;
   636      #endif
(xInspect 2,696):n
*  633          OPENSSL_free(timestamp_tm);
(xInspect 2,696):p timezone
Missing ELF symbol "timezone".

```

**Comment by rsbeckerca** [comment]
> > This time is across the Epoc boundary and cannot be represented in 32-bit time_t.
> 
> Ah right, but the failure is not associated with that fact. As you can see in the test output the difference between the times is exactly 3600 which indicates a DST issue.

Where is DST calculated?

**Comment by t8m** [comment]
> timezone is inferred to be: `25200` from:

Yeah, that makes the timezone contents definitely correct in respect to the MST.

**Comment by rsbeckerca** [comment]
After the call time mktime() at 632 (ref above), the `tm_isdst` value is set to 1. It is 0 before. mktime is non-reentrant and can modify `struct tm`. Is there an assumption that `tm_isdst` does not change? Might have to save it off first.

**Comment by t8m** [comment]
> Is there an assumption that `tm_isdst` does not change? Might have to save it off first.

No, that is not the problem. This is IMO actually the expected behavior from mktime(). I need to investigate why asn1_string_to_time_t() works on Linux at all.

**Comment by rsbeckerca** [comment]
> > Is there an assumption that `tm_isdst` does not change? Might have to save it off first.
> 
> No, that is not the problem. This is IMO actually the expected behavior from mktime(). I need to investigate why asn1_string_to_time_t() works on Linux at all.

Let me know how I can assist.

**Comment by rsbeckerca** [comment]
This is still broken as of commit 8547cd6790

**Comment by t8m** [comment]
@rsbeckerca Is this still relevant?

**Comment by rsbeckerca** [comment]
This appears to have been fixed by an unrelated change.
