### ISSUE TITLE
Can SSL Server  not dump peer Certificate while constructing session ticket?

### ISSUE THREAD

**Issue by JoeJoeNg** [openssl/openssl#17822]
SSL Server will dump the peer cert into the session ticket, which make session ticket big..
So can we provide an option to avoid dumping peer certificate?
such like this:

```
--- a/ssl/ssl_asn1.c
+++ b/ssl/ssl_asn1.c
@@ -167,7 +167,8 @@ int i2d_SSL_SESSION(const SSL_SESSION *in, unsigned char **pp)
     as.timeout = (int64_t)in->timeout;
     as.verify_result = in->verify_result;
 
-    as.peer = in->peer;
+    if (!(in->flags & SSL_SESS_FLAG_NO_PEER_CERT))
+        as.peer = in->peer;
```

**Comment by tmshort** [comment]
We've done something similar, and it will work. If `as.peer = NULL`, then the peer certificate is not included in the serialized SSL_SESSION. You do lose the ability to query the peer certificate on a rengotiation/resumption.

**Comment by tmshort** [comment]
Are you asking for this functionality? It would have to be done in master (which is targeted to be 3.1); tests and documentation would be required. Feel free to create a PR.

**Comment by JoeJoeNg** [comment]
I will create a PR later

**Comment by chensqecc** [comment]
Excuse me, is it necessary to dump certificates to  session ticket? 

from your side, which is the better way: remove this code " as.peer = in->peer;" or add an option for it? 

@JoeJoeNg  @tmshort

**Comment by tmshort** [comment]
IMHO, better to add an option; we don't want to completely remove existing functionality and possibly break something.
By having the certificate in the session, the server is able to look at that certificate for authorization purposes (the existence of the session ticket with a verified certificate state is the authentication piece).
