### ISSUE TITLE
Potential memory leak in append_ia5

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#17827]
If we didn't succeed duplicating passed email address we don't free the  STACK_OF(OPENSSL_STRING) *sk

https://github.com/openssl/openssl/blob/e9492d1cecf459261f1f5ac0eb03e9c631600537/crypto/x509/v3_utl.c#L541-L543

I think it can cause a memory leak in case of malloc failure.

**Comment by t8m** [comment]
Yeah, will you open a PR?

**Comment by beldmit** [comment]
Will do
