### ISSUE TITLE
Openssl 1.0.2j Not linking its own libcrypto correctly

### ISSUE THREAD

**Issue by EricDeveaud** [openssl/openssl#1783]
Hello, 

I compiled and installed openssl-1.0.2j with shared support, in a non standard directory and noticed that installed libgost.so is not linked versus embeded libcrypto

openssl was compiled using following config options:

`./config --prefix=/tmp/openssl threads zlib-dynamic shared -fPIC -Wl,--enable-new-dtags,-rpath,/tmp/openssl/lib`
(see https://github.com/openssl/openssl/issues/1740)

see for example: 

```
find /tmp/openssl/lib/ -name \*.so | xargs ldd | grep -v \(
/tmp/openssl/lib/libssl.so:
/tmp/openssl/lib/engines/libcswift.so:
/tmp/openssl/lib/engines/libpadlock.so:
/tmp/openssl/lib/engines/libaep.so:
/tmp/openssl/lib/engines/libsureware.so:
/tmp/openssl/lib/engines/lib4758cca.so:
/tmp/openssl/lib/engines/libatalla.so:
/tmp/openssl/lib/engines/libchil.so:
/tmp/openssl/lib/engines/libnuron.so:
/tmp/openssl/lib/engines/libubsec.so:
/tmp/openssl/lib/engines/libcapi.so:
/tmp/openssl/lib/engines/libgmp.so:
/tmp/openssl/lib/engines/libgost.so:
    libcrypto.so.1.0.0 => not found
/tmp/openssl/lib/libcrypto.so:
```

did I missed something ?

best regards

Eric

PS attached is a Dockerfile that allows to reproduce the problem
[Dockerfile-openssl.txt](https://github.com/openssl/openssl/files/552682/Dockerfile-openssl.txt)

**Comment by levitte** [comment]
I made a build according to your recipe and looked at `/tmp/openssl/lib/engines/libgost.so` with `objdump -x`.  'lo and behold, no `RUNPATH` set!  That explains your problem.

I'll have a look in the Makefiles, that's probably where the problem lies.

**Comment by levitte** [comment]
Please try #1803

**Comment by EricDeveaud** [comment]
yes it fixes the problem.

let's wait for next officiel 1.0.2 release

thanks

Eric

**Comment by levitte** [comment]
Grand.  Thank you.
