### ISSUE TITLE
What should be the Common Name for Root, Server and Client Certificate?

### ISSUE THREAD

**Issue by AliHaider104** [openssl/openssl#17835]
Hello Everyone,

I'm making Root, Client and Server certificate using openSSL but when I try to connect to the server I received an error that common name not matched with the expected common name. Please guide me on that. what should be the common name for ca-root, client and server certificate.

**Comment by t8m** [comment]
The CA and client certificate CNs can be anything. The server certificate should have the host name of the server as the certificate. However that is an old way of putting the host name into the certificate. Instead the X509v3 Subject Alternative Name extension should be used to store the host name(s) - there might be even multiple ones.

**Comment by AliHaider104** [comment]
Can i give a simple string like 'abc' as a host name?
