### ISSUE TITLE
Which license governs the contents of the `www.openssl.org` website?

### ISSUE THREAD

**Issue by keshav-space** [openssl/openssl#17830]
We're working on [VulnerableCode](https://github.com/nexB/vulnerablecode), it's an Opensource Software Vulnerability Database for FOSS.

For OpenSSL, we're fetching the vulnerability data from:  https://www.openssl.org/news/vulnerabilities.xml
We couldn't find any license for those security advisories.
`Could you tell us under which license those advisory data are provided?`

**Comment by paulidale** [comment]
Apache 2.

**Comment by pombredanne** [comment]
@paulidale Thank you ++ please feel free to close.
