### ISSUE TITLE
error:14094438:lib(20):func(148):reason(1080)

### ISSUE THREAD

**Issue by ErikasMasaitis** [openssl/openssl#17847]
Hello, im getting this kind of error: error:14094438:lib(20):func(148):reason(1080)
with openssl errstr it converts to: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

Im using MQTT broker in my router with ssl sertificates generated from here: https://mosquitto.org/man/mosquitto-tls-7.html
im using: ca.crt server.crt and server.key

and trying to connect to my broker from pc with: mosquitto_sub -h 192.168.1.1 -p 1883 --cafile ca.crt --cert client.crt --key client.key -t router/signal

my config:

user root
port 1883
cafile /etc/ca.crt
certfile /etc/server.crt
keyfile /etc/server.key
allow_anonymous true

tried to verify my ca.crt with:

openssl verify -CAfile ca.crt server.crt client.crt
server.crt: OK
client.crt: OK

maybe somebody knows what can be wrong?

**Comment by t8m** [comment]
What is the openssl version used?

**Comment by ErikasMasaitis** [comment]
found a mistake myself. common name has to be hostname (mosquitto protocol)
