### ISSUE TITLE
How to easily write my ECC public and private keys to strings? c++ api

### ISSUE THREAD

**Issue by sonnyparlin** [openssl/openssl#17856]
I have a working solution for POSIX systems:

```c
void Wallet::genKeyPair() {
    /* set our curve name */
    const char *curve = "secp256k1";
    
    /* Generate the key pair */
    EVP_PKEY *pkey = EVP_EC_gen(curve);
    if (pkey == NULL) {
        std::cerr << "Error generating the ECC key." << std::endl;
        return;
    }

    /* 
    Use some FILE stream magic to easily convert our 
    public and private keys into strings 
    */
    char *bp;
    size_t size;
    FILE *stream;
    
    stream = open_memstream (&bp, &size); // POSIX only
    PEM_write_PUBKEY(stream, pkey);
    fflush (stream);
    walletPublicKey = bp;
    fclose (stream);

    stream = open_memstream (&bp, &size); // POSIX only
    const EVP_CIPHER *cipher = EVP_get_cipherbyname(curve);
    PEM_write_PrivateKey(stream, pkey, cipher, NULL, 0, NULL, NULL);
    fflush (stream);
    walletPrivateKey = bp;
    fclose (stream);

    /* 
    The keys are stored in our wallet now so we can free the memory
    used for the keys.
    */
    EVP_PKEY_free(pkey);
}
```

I'm using the posix only ```open_memstream()``` to conveniently write my private / public keys to strings in PEM format. However as I'm trying to port this to Windows, I've learned that windows doesn't support ```open_memstream()``` .

Is there a function similar to ```PEM_write_PUBKEY()``` that either writes the PEM formatted key to a string or perhaps returns a PEM formatted string?

**Comment by mspncp** [comment]
OpenSSL has it's own stream abstraction, called a BIO (Basic I/O). You could create a [memory BIO](https://www.openssl.org/docs/manmaster/man3/BIO_s_mem.html) and use `PEM_write_bio_{PUBKEY,PrivateKey}` instead of `PEM_write_{PUBKEY,PrivateKey}` to serialize your public resp. private key. 

https://www.openssl.org/docs/man3.0/man3/PEM_write_bio_PrivateKey.html

**Comment by sonnyparlin** [comment]
Thank you, I believe this is what I'm looking for.
