### ISSUE TITLE
Enable to set cipher list sk

### ISSUE THREAD

**Issue by JoeJoeNg** [openssl/openssl#17858]
Now we have interface SSL_CTX_get_ciphers, it can return ctx->cipher_list;
I want the "SET" interface, enables to set cipher_list; 
```
int SSL_set_cipher_sk_list(SSL *s, STACK_OF(SSL_CIPHER) *sk)
{
    sk_SSL_CIPHER_free(s->cipher_list);
    s->cipher_list = sk;
    sk_SSL_CIPHER_free(s->cipher_list_by_id);
    s->cipher_list_by_id = sk_SSL_CIPHER_dup(sk);
    return 0;
}
```
It is different to SSL_set_cipher_list, because SSL_set_cipher_list passes strings, including some procedure to due with string.
But SSL_set_cipher_sk_list can easily set sk to cipher_list, more faster than SSL_set_cipher_list.

**Comment by t8m** [comment]
But the SSL_CIPHER is an opaque structure with just read-only accessors. How would you create a cipher list to set on the SSL_CTX?

**Comment by tmshort** [comment]
`SSL_set_cipher_list()` does more than just string processing; it applies rules to the cipher such that disabled ciphers are not included, etc. Defining a stack of SSL_CIPHERS directly is dangerous, as you could inadvertently create a cipher configuration that won't work.

**Comment by JoeJoeNg** [comment]
tmshort is right, it's dangerous.
However, SSL_set_cipher_list() can't handle  performance-sensitive scenario. Is there any solution to improve performance of SSL_set_cipher_list()?

**Comment by paulidale** [comment]
`SSL_CTX_set_cipher_list()` would be the recommendation.  Any SSL objects will inherit from this.
It might mean you need multiple SSL_CTX objects for the different variations you want.

**Comment by tmshort** [comment]
How often are you doing `SSL_set_cipher_list()`? As @paulidale wrote, `SSL_CTX_set_cipher_list()` can be used to create templates (or factories) for `SSL` objects with the appropriate settings. If you need to share a session cache; use one `SSL_CTX` for creating `SSL`s (the session cache is in the `SSL_CTX` used with `SSL_new()`),  then use `SSL_set_SSL_CTX()` for distinct settings from other `SSL_CTX`s.

**Comment by JoeJoeNg** [comment]
What I am doing is like a proxy, the proxy connects to thousands of clients, and also connects to thousands of servers.
In this scenario，SSL objects comes from different clients, and contains different cipher_list, so I can't reuse one SSL_CTX setting.

**Comment by tmshort** [comment]
Are you trying to provide the list the client gives the proxy to the server? Do you have a requirement for the connection to the server and the client to share the same cipher? If you have that requirement, IMHO, I think it's something that ought to be re-evaluated. You only really need to have a single cipher list that supports a wide variety of ciphers that both the servers and the clients support.

**Comment by JoeJoeNg** [comment]
client ---> proxy ---> server
Proxy will receive client-hello from client, and then create&send new client-hello to server. During this procedure, proxy needs to select the supported cipher-suits from the client-hello, and uses the new sk to construct a new client-hello, which will be send to server. 

Why choose new API SSL_set_cipher_sk_list? Because SSL_set_cipher_list can't satisfy my performance requirements.

SSL_CIPHER is read-only, the new API SSL_set_cipher_sk_list() won't change it. SSL_set_cipher_sk_list() will be used like this:
```
void proxy_set_cipher_list(STACK_OF(SSL_CIPHER) *client_sk)
{
    int cipher_num = sk_SSL_CIPHER_num(client_sk);
    STACK_OF(SSL_CIPHER) *sk = sk_SSL_CIPHER_new_null(); 

    for (int i = 0; i < cipher_num; i++) 
    {
        // 
        SSL_CIPHER c = sk_SSL_CIPHER_value(client_sk, i);
        if (validation)
        {
            (void)sk_SSL_CIPHER_push(sk, c);
        }
    }
    
    // set sk to SSL
    (void)SSL_set_cipher_sk_list(SSL, sk);
}
```
As we use sk_SSL_CIPHER_value() to get SSL_CIPHER, and use sk_SSL_CIPHER_push() to dump CIPHER into sk, we won't write SSL_CIPHER.

**Comment by huiyuexu** [comment]
@t8m 
As @JoeJoeNg's description, whether OpenSSL consider this scenario as reasonable and accept adding `SSL_set_cipher_sk_list`?

**Comment by t8m** [comment]
I do not really think such interface is a good idea. It was suggested to you above, that you should not really try to mimic the client cipher suite lists in the proxy. Why don't you just use the defaults?
