### ISSUE TITLE
undefined reference to `AES_decrypt' - build attempt RPi4b 64bit Bullseye

### ISSUE THREAD

**Issue by Fredrum** [openssl/openssl#17866]
Hello!

I'm trying to build the HOT master branch from today on my,
Rpi4b 8GB, 64bit RPiOS Bullseye
Linux raspberrypi 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux

I'm not super clear on how I should config but I have attempted to copy the flags I've seen on other ppl's raspberry builds:

```
./Configure --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -fPIC -pthread -Wa,--noexecstack -Wall -Wa,--noexecstack -g -march=armv8-a+crypto -mtune=cortex-a72 -O3 -fstack-protector-strong -Wformat -Werror=format-security -DMD5_ASM -DSHA1_ASM -DRMD160_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DKECCAK1600_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
```

Iv'e tried a few variants of that but keep getting the same build error:
```
/usr/bin/ld: libcrypto.a(libdefault-lib-cipher_aes_hw.o): in function `cipher_hw_aes_initkey':
/home/pi/dev/openssl/providers/implementations/ciphers/cipher_aes_hw.c:62: undefined reference to `AES_decrypt'
/usr/bin/ld: /home/pi/dev/openssl/providers/implementations/ciphers/cipher_aes_hw.c:62: undefined reference to `AES_decrypt'
/usr/bin/ld: /home/pi/dev/openssl/providers/implementations/ciphers/cipher_aes_hw.c:107: undefined reference to `AES_encrypt'
/usr/bin/ld: /home/pi/dev/openssl/providers/implementations/ciphers/cipher_aes_hw.c:107: undefined reference to `AES_encrypt'
... etc
```

I'm especially interested in trying out the 64bit Arm/Rpi acceleration that was merged into the master the other day.

Is there anyone that would be able to advice on how I should build on this system?

Cheers!

**Comment by paulidale** [comment]
Start by dropping all of the `-D...` options on the configure line.

The build system & library are generally smart enough to work out what is and isn't available for each platform.  Trying to outsmart it is asking for problems.

I'd just use: `./Configure --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -march=armv8-a+crypto -mtune=cortex-a72` and even the arch and tune options are probably optional -- they won't do anything for the assembly code which is where the real work is done.

**Comment by Fredrum** [comment]
Ok I just tried that and the build went through fine, great!

but when I do,
cd /usr/local/ssl/bin
LD_LIBRARY_PATH=/usr/local/ssl/lib ./openssl speed -decrypt -evp aes-256-cbc

It doesn't show me any _ASM flags. This is what I see,
options: bn(64,64)
compiler: gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -march=armv8-a+crypto -mtune=cortex-a72 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_armcap=0x83

I ran only the one comparison test.

Fresh build as above,
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-256-CBC      51215.51k    60253.57k    64598.05k    69888.00k    71729.15k    71614.46k

RaspiOS version:
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-cbc      44350.84k    53609.92k    64443.76k    69787.31k    71710.04k    71941.65k


Does that look correct?

**Comment by paulidale** [comment]
I've never built on the Pi, so can't tell.
The GNU tools include an assembler.

Do a configure with `no-asm` to see how fast a non-assembly build is.

**Comment by Fredrum** [comment]
I then get

type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-256-CBC      49894.77k    58338.08k    57286.06k    57788.42k    57961.13k    61746.11k

so definitely a bit worse than the above build. But not hugely so it seems?

I'll try again taking off the arch and tune hints.
