### ISSUE TITLE
how to make the  Extended Key Usage item of the certificate not show the brackets behind it and the oid in the brackets

### ISSUE THREAD

**Issue by zhen1129** [openssl/openssl#17878]
When I use OpenSSL to create a new CA certificate, how to make the  Extended Key Usage item of the certificate not show the brackets behind it and the oid in the brackets? like this：

![image](https://user-images.githubusercontent.com/26321654/158023218-e0621aa0-f54f-4b82-8a07-ef0a729d0ec9.jpeg)
Or how to make the certificate have these purposes without using the Extended key usage attribute：
* Proves your identity to a remote computer
* Ensures software came from software publisher
* Protects software from alteration after publication
* Allows data on disk to be encrypted
* Protects e-mail messages
* Allows secure communication on the Internet
* Ensures the identity of a remote computer
* Allows data to be signed with the current time
* All issuance policies

**Comment by tmshort** [comment]
I think you may be confusing how the Windows Operating System _displays_ certificates and the OIDs, with the contents of that certificate. You won't be able to change how Windows displays those certificates.
The OIDs are how those purposes are defined. The words "ClientAuthentication" are not in the certificate itself, the encoded OID `1.3.6.1.5.5.7.3.2` is contained within the Enhanced Key Usage property, along with those other OIDs.
If you were to dump the certificate using a different tool, you would still get the same information, but presented differently. Have you looked at the `openssl x509` command? To get the output you want, you may need to parse the `openssl x509` command output or write your own utility using OpenSSL APIs.

**Comment by zhen1129** [comment]
Yes, of course I know. Er, I mean, for example, the SSL certification authority of GitHub is digicert. You can see that its root certificate contains extended key usage on GitHub. The difference is that there is a property after this option, like this
![digiert](https://user-images.githubusercontent.com/26321654/158046957-07035b48-1042-44be-b565-4a050d428c26.jpeg)

When I downloaded it and opened it locally, I was surprised that it didn't have the extended key usage (property) option. Why?
![download](https://user-images.githubusercontent.com/26321654/158046972-74977358-c882-418f-b970-461fa0bd1313.jpeg)

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
