### ISSUE TITLE
Typo in inner_evp_generic_fetch() error handling (= / ==)

### ISSUE THREAD

**Issue by Futaura** [openssl/openssl#17876]
Just stumbled across this in 3.0.1 - should be self-explanatory (`=` instead of `==`):

https://github.com/openssl/openssl/blob/abdb2278d2b65ae87bee3121be83322e4219b396/crypto/evp/evp_fetch.c#L352

**Comment by mspncp** [comment]
Thanks for pointing it out to us. Would you like to create a pull request and earn the credit of fixing it yourself?

**Comment by Futaura** [comment]
Think I've done it correctly - let me know if I messed something up!
