### ISSUE TITLE
Does version 1.1.1 supports building for visual studio 2005

### ISSUE THREAD

**Issue by LinArcX** [openssl/openssl#17879]
Hello. We have a legacy codebase that uses c++98 and visual studio 2005.

My manager decided to use TLS in this codebase. I wanted to know is there any way to build version 1.1.1 of openssl for vistual studio 2005?

EDIT: I know it's insane to use an outdated TLS library. Also outdated c++ version and visual studio. But please let me know is it possible or not?

**Comment by levitte** [comment]
It's been a while that we have tested against that particular MSVC version, and it's possible that there are details that do not build.
However, we've tried to be careful with our code, to the best of our knowledge.
I suggest that you simply try, following available instructions, and also run the test suite (`nmake test`).  If there are specific build or test issues, raise issues specifically about those and we'll try to help as best we can.
