### ISSUE TITLE
macOS Monterey: installation failures with RVM, ASDF, rbenv caused by openssl/homebrew settings

### ISSUE THREAD

**Issue by belgoros** [openssl/openssl#17885]
I tried to install Ruby `2.6.5` using different version managers (RVM, ASDF, rbenv) - no success.
I have already had the same [issue](https://github.com/rvm/rvm/issues/4484) 3 years ago and the proposed [solution](https://github.com/rvm/rvm/issues/4484#issuecomment-484174669) worked for me.

But none of the proposed solutions worked anymore for masOS Monterey `12.3`, Apple M1 chip.
The current XCode version: `Version 13.3 (13E113)`.

Nevertheless, I installed successfully Ruby `3.1.0` version with rvm:
```
➜  ~ rvm list
=* ruby-3.1.0 [ arm64 ]

# => - current
# =* - current && default
#  * - default
```
Here are the installed openssl version details:
```
➜  ~ openssl version -a
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
built on: Tue Dec 14 16:16:25 2021 UTC
platform: darwin64-arm64-cc
options:  bn(64,64)
compiler: clang -fPIC -arch arm64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/opt/homebrew/etc/openssl@3"
ENGINESDIR: "/opt/homebrew/Cellar/openssl@3/3.0.1/lib/engines-3"
MODULESDIR: "/opt/homebrew/Cellar/openssl@3/3.0.1/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_armcap=0x7f
```
Checking `which openssl`: 
```
 ~ which openssl
/opt/homebrew/bin/openssl
```
Tried to install it with RV as usual:
```
 ~ rvm install "ruby-2.6.5"
ruby-2.6.5 - #removing src/ruby-2.6.5 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/12.3/arm64/ruby-2.6.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Updating certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem'
Requirements installation successful.
Installing Ruby from source to: /Users/serguei/.rvm/rubies/ruby-2.6.5, this may take a while depending on your cpu(s)...
ruby-2.6.5 - #downloading ruby-2.6.5, this may take a while depending on your connection...
ruby-2.6.5 - #extracting ruby-2.6.5 to /Users/serguei/.rvm/src/ruby-2.6.5 - please wait
ruby-2.6.5 - #configuring - please wait
ruby-2.6.5 - #post-configuration - please wait
ruby-2.6.5 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/serguei/.rvm/log/1647331075_ruby-2.6.5/make.log

There has been an error while running make. Halting the installation.
```
When trying to install it with ASDF (as you can see, the version `3.0.0` was installed without any issues), here is the output:
```
~ asdf list ruby
  3.0.0
➜  ~ asdf install ruby 2.6.5
Downloading openssl-1.1.1l.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/0b7a3e5e59c34827fe0c3a74b7ec8baef302b98fa80088d7f9153aa16fa76bd1
Installing openssl-1.1.1l...
Installed openssl-1.1.1l to /Users/serguei/.asdf/installs/ruby/2.6.5

Downloading ruby-2.6.5.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.bz2
Installing ruby-2.6.5...
ruby-build: using readline from homebrew

BUILD FAILED (macOS 12.3 using ruby-build 20211109)

Inspect or clean up the working tree at /var/folders/yy/ld5smmzd38v1q3z259dwh8_w0000gn/T/ruby-build.20220315084600.1481.TGiQNu
Results logged to /var/folders/yy/ld5smmzd38v1q3z259dwh8_w0000gn/T/ruby-build.20220315084600.1481.log

Last 10 log lines:
compiling ../.././ext/psych/yaml/emitter.c
compiling ../.././ext/psych/yaml/parser.c
5 warnings generated.
4 warnings generated.
linking shared-object zlib.bundle
1 warning generated.
linking shared-object psych.bundle
422 warnings generated.
linking shared-object date_core.bundle
make: *** [build-ext] Error 2
```
The result of running the suggested in the log file command `perl configdata.pm --dump`:
```
~ perl configdata.pm --dump
Can't open perl script "configdata.pm": No such file or directory
```
The result of running `brew info openssl`:
```
➜  ~ brew info openssl                                                                       
openssl@3: stable 3.0.1 (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/opt/homebrew/Cellar/openssl@3/3.0.1 (6,420 files, 27.8MB) *
  Poured from bottle on 2022-03-14 at 20:34:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates ✔
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /opt/homebrew/etc/openssl@3/certs

and run
  /opt/homebrew/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides LibreSSL.

If you need to have openssl@3 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@3 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"

For pkg-config to find openssl@3 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
```
I added (then commented out) as suggested above the variables to my `.zshrc` file:
```
#export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
#export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
#export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
#export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
```
No matter if the above variables are commented or not, the error is always the same and it seems to have no effect.

What am I missing?

**Comment by t8m** [comment]
I am afraid we cannot help you with your question. We did not produce these build scripts and in the logs above there is nothing really related to OpenSSL build issues or anything we could help with.

**Comment by tmshort** [comment]
After installing Xcode 13.3, ruby 2.6.8p205 is installed, so you shouldn't have to install ruby separately (of course, this depends on the version of macOS you are using).

I'm guessing that since you have OpenSSL installed via Homebrew and asdf is trying to install openssl, you are getting conflicts. Homebrew looks to have installed OpenSSL 3.0.1, while asdf wants OpenSSL 1.1.1l. There's either header conflicts or the asdf ruby installer can't yet build with OpenSSL 3.0.1 (which is why it's pulling down 1.1.1l).

My recollection is that [Homebrew](brew.sh) requires ruby, so I'm not sure why you are trying to install ruby again? It certainly won't be updating the Xcode install of ruby.

You could always just use the Xcode ruby (in /usr/bin/ruby) or remove Homebrew's OpenSSL and try again.

But, using multiple package managers is potential trouble, as is having multiple installs of of the same software.

Of course, macOS's "openssl" is really LibreSSL, which doesn't help matters.

**Comment by belgoros** [comment]
Finally, I could install ruby `2.6.5` both via [rbenv](https://github.com/rbenv/rbenv) and [asdf](https://asdf-vm.com).
I had to install/activate/deactivate some options for `ruby-build`, `readline` homebrew kegs, - you can see the required and available options/variables to set with `brew info XXX` keg name.
The only `PATH` variable that was set  in my `.zshrc` file was the one for `rbenv`:
```
. /opt/homebrew/opt/asdf/libexec/asdf.sh

#export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
#export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
#export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"

export PATH="$HOME/.rbenv/bin:$PATH"
```
As for installing Ruby `2.6.5` - I could not get it work.
Here is the output proving the installed Ruby versions:
<img width="164" alt="Screenshot 2022-03-18 at 10 34 13" src="https://user-images.githubusercontent.com/83579/158977944-3466cb34-b026-4040-af1f-bfc52b1ab8c8.png">

So when cd-ing to the Rails project using Ruby `2.6.5`, the Ruby version is detected automatically.
So I'll close the issue. It seems like there was an issue with providing Ruby < 3.0 binaries for Apple M1 chip.
