### ISSUE TITLE
No encoder found to obtain public key when using DSA or EC and an engine

### ISSUE THREAD

**Issue by SteveKing-Cbg** [openssl/openssl#17886]
A similar bug for RSA  (#16256) has been fixed in pull request #16289, however the problem still exists with the other algorithms.

**Comment by t8m** [comment]
As a workaround you should be able to use `openssl pkey` to export the public key as that command uses the PEM/i2d functions.

**Comment by SteveKing-Cbg** [comment]
Thanks, yes, using `openssl pkey` does export the public key correctly

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
