### ISSUE TITLE
perl configdata.pm --dump

### ISSUE THREAD

**Issue by mct500** [openssl/openssl#17880]

**Comment by levitte** [comment]
What's the question?

**Comment by JosueMerlos** [comment]
> What's the question?

Error on mac os when trying to install ruby ​​(specfic command asdf install ruby ​​3.0.3)

Installing openssl-1.1.1...

Build Failed (MacOS 12.2.1 using ruby-build 20220218)

**Comment by paulidale** [comment]
No error message?

I suspect this question would be better asked of the maintainers of the tool you are using to install (`asdf`?).
