### ISSUE TITLE
error in building openssl in windows in msys2

### ISSUE THREAD

**Issue by lsnnt** [openssl/openssl#17905]
the screenshot is given below
![image](https://user-images.githubusercontent.com/85880458/158607780-16af5f91-a44f-4717-87e8-164b86c60843.png)
not building please help!!!

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input

**Comment by lsnnt** [comment]
not using windows now closing issue!!
