### ISSUE TITLE
Configure incompatible with StrawberryPerl

### ISSUE THREAD

**Issue by marcstern** [openssl/openssl#17947]
Configure in 1.1.1n is incompatible with StrawberryPerl.
StrawberryPerl doesn't accept the "2>NUL" syntax as it's using a Unix-like shell.
First visible issue is the following message: "NASM not found - make sure it's installed and available on %PATH%".
Removing all "2>NUL" solves the problem and the scripts goes up to the end:

> Configuring OpenSSL version 1.1.1n (0x101010efL) for VC-WIN64A
> Using os-specific seed configuration
> Creating configdata.pm
> Creating makefile
> 

However, the makefile is not created.

**Comment by levitte** [comment]
Please give the result of this command: `perl configdata.pm --dump`
Also, what Unix-like shell are you talking about?

**Comment by marcstern** [comment]
> 
> Command line (with current working directory = .):
> 
>     C:\portable\perl\perl\bin\perl.exe Configure VC-WIN64A no-zlib no-comp no-heartbeats no-dtls no-psk no-srp no-sctp no-idea no-mdc2 no-rc5 no-unit-test no-shared no-tests
> 
> Perl information:
> 
>     C:\portable\perl\perl\bin\perl.exe
>     5.30.2 for MSWin32-x64-multi-thread
> 
> Enabled features:
> 
>     aria
>     asm
>     async
>     autoalginit
>     autoerrinit
>     autoload-config
>     bf
>     blake2
>     camellia
>     capieng
>     cast
>     chacha
>     cmac
>     cms
>     ct
>     deprecated
>     des
>     dgram
>     dh
>     dsa
>     dso
>     ec
>     ec2m
>     ecdh
>     ecdsa
>     engine
>     err
>     filenames
>     gost
>     hw(-.+)?
>     makedepend
>     md4
>     multiblock
>     nextprotoneg
>     pinshared
>     ocb
>     ocsp
>     pic
>     poly1305
>     posix-io
>     rc2
>     rc4
>     rdrand
>     rfc3779
>     rmd160
>     scrypt
>     seed
>     siphash
>     sm2
>     sm3
>     sm4
>     sock
>     srtp
>     sse2
>     ssl
>     static-engine
>     stdio
>     threads
>     tls
>     ts
>     ui-console
>     whirlpool
>     tls1
>     tls1-method
>     tls1_1
>     tls1_1-method
>     tls1_2
>     tls1_2-method
>     tls1_3
>     dtls1-method
>     dtls1_2-method
> 
> Disabled features:
> 
>     afalgeng                [not-linux]    OPENSSL_NO_AFALGENG
>     asan                    [default]      OPENSSL_NO_ASAN
>     buildtest-c++           [default]      
>     comp                    [option]       OPENSSL_NO_COMP (skip crypto\comp)
>     crypto-mdebug           [default]      OPENSSL_NO_CRYPTO_MDEBUG
>     crypto-mdebug-backtrace [default]      OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
>     devcryptoeng            [default]      OPENSSL_NO_DEVCRYPTOENG
>     dtls                    [option(dtls)] OPENSSL_NO_DTLS
>     dynamic-engine          [cascade]      
>     ec_nistp_64_gcc_128     [default]      OPENSSL_NO_EC_NISTP_64_GCC_128
>     egd                     [default]      OPENSSL_NO_EGD
>     external-tests          [default]      OPENSSL_NO_EXTERNAL_TESTS
>     fuzz-libfuzzer          [default]      OPENSSL_NO_FUZZ_LIBFUZZER
>     fuzz-afl                [default]      OPENSSL_NO_FUZZ_AFL
>     heartbeats              [option]       OPENSSL_NO_HEARTBEATS
>     idea                    [option]       OPENSSL_NO_IDEA (skip crypto\idea)
>     md2                     [default]      OPENSSL_NO_MD2 (skip crypto\md2)
>     mdc2                    [option]       OPENSSL_NO_MDC2 (skip crypto\mdc2)
>     msan                    [default]      OPENSSL_NO_MSAN
>     psk                     [option]       OPENSSL_NO_PSK
>     rc5                     [option]       OPENSSL_NO_RC5 (skip crypto\rc5)
>     sctp                    [option]       OPENSSL_NO_SCTP
>     shared                  [option]       
>     srp                     [option]       OPENSSL_NO_SRP (skip crypto\srp)
>     ssl-trace               [default]      OPENSSL_NO_SSL_TRACE
>     tests                   [option]       OPENSSL_NO_TESTS
>     ubsan                   [default]      OPENSSL_NO_UBSAN
>     unit-test               [option]       OPENSSL_NO_UNIT_TEST
>     weak-ssl-ciphers        [default]      OPENSSL_NO_WEAK_SSL_CIPHERS
>     zlib                    [option]       
>     zlib-dynamic            [default]      
>     ssl3                    [default]      OPENSSL_NO_SSL3
>     ssl3-method             [default]      OPENSSL_NO_SSL3_METHOD
>     dtls1                   [option(dtls)] OPENSSL_NO_DTLS1
>     dtls1_2                 [option(dtls)] OPENSSL_NO_DTLS1_2
> 
> Config target attributes:
> 
>     AR => "lib",
>     ARFLAGS => "/nologo",
>     AS => "nasm",
>     ASFLAGS => "-g",
>     CC => "cl",
>     CFLAGS => "/W3 /wd4090 /nologo /O2",
>     CPP => "\$(CC) /EP /C",
>     HASHBANGPERL => "/usr/bin/env perl",
>     LD => "link",
>     LDFLAGS => "/nologo /debug",
>     MT => "mt",
>     MTFLAGS => "-nologo",
>     RANLIB => "CODE(0x80aea0)",
>     RC => "rc",
>     aes_asm_src => "aes_core.c aes_cbc.c vpaes-x86_64.s aesni-x86_64.s aesni-sha1-x86_64.s aesni-sha256-x86_64.s aesni-mb-x86_64.s",
>     aes_obj => "aes_core.o aes_cbc.o vpaes-x86_64.o aesni-x86_64.o aesni-sha1-x86_64.o aesni-sha256-x86_64.o aesni-mb-x86_64.o",
>     apps_aux_src => "win32_init.c",
>     apps_init_src => "",
>     apps_obj => "win32_init.o",
>     aroutflag => "/out:",
>     asflags => "-Ox -f win64 -DNEAR",
>     asoutflag => "-o ",
>     bf_asm_src => "bf_enc.c",
>     bf_obj => "bf_enc.o",
>     bin_cflags => "/Zi /Fdapp.pdb /MT",
>     bin_lflags => "/subsystem:console /opt:ref",
>     bn_asm_src => "bn_asm.c x86_64-mont.s x86_64-mont5.s x86_64-gf2m.s rsaz_exp.c rsaz-x86_64.s rsaz-avx2.s",
>     bn_obj => "bn_asm.o x86_64-mont.o x86_64-mont5.o x86_64-gf2m.o rsaz_exp.o rsaz-x86_64.o rsaz-avx2.o",
>     bn_ops => "EXPORT_VAR_AS_FN SIXTY_FOUR_BIT",
>     build_file => "makefile",
>     build_scheme => [ "unified", "windows", "VC-common" ],
>     cast_asm_src => "c_enc.c",
>     cast_obj => "c_enc.o",
>     cflags => "/Gs0 /GF /Gy",
>     chacha_asm_src => "chacha-x86_64.s",
>     chacha_obj => "chacha-x86_64.o",
>     cmll_asm_src => "cmll-x86_64.s cmll_misc.c",
>     cmll_obj => "cmll-x86_64.o cmll_misc.o",
>     coutflag => "/Fo",
>     cppflags => "",
>     cpuid_asm_src => "x86_64cpuid.s",
>     cpuid_obj => "x86_64cpuid.o",
>     defines => [ "OPENSSL_SYS_WIN32", "WIN32_LEAN_AND_MEAN", "UNICODE", "_UNICODE", "_CRT_SECURE_NO_DEPRECATE", "_WINSOCK_DEPRECATED_NO_WARNINGS" ],
>     des_asm_src => "des_enc.c fcrypt_b.c",
>     des_obj => "des_enc.o fcrypt_b.o",
>     disable => [  ],
>     dso_cflags => "/Zi /Fddso.pdb",
>     dso_extension => ".dll",
>     dso_scheme => "win32",
>     ec_asm_src => "ecp_nistz256.c ecp_nistz256-x86_64.s x25519-x86_64.s",
>     ec_obj => "ecp_nistz256.o ecp_nistz256-x86_64.o x25519-x86_64.o",
>     enable => [  ],
>     ex_libs => "ws2_32.lib gdi32.lib advapi32.lib crypt32.lib user32.lib",
>     exe_extension => "",
>     includes => [  ],
>     keccak1600_asm_src => "keccak1600-x86_64.s",
>     keccak1600_obj => "keccak1600-x86_64.o",
>     ldoutflag => "/out:",
>     lflags => "",
>     lib_cflags => "/Zi /Fdossl_static.pdb /MT /Zl",
>     lib_cppflags => "",
>     lib_defines => [ "L_ENDIAN" ],
>     md5_asm_src => "md5-x86_64.s",
>     md5_obj => "md5-x86_64.o",
>     modes_asm_src => "ghash-x86_64.s aesni-gcm-x86_64.s",
>     modes_obj => "ghash-x86_64.o aesni-gcm-x86_64.o",
>     module_cflags => "",
>     module_cxxflags => "",
>     module_ldflags => "/dll",
>     mtinflag => "-manifest ",
>     mtoutflag => "-outputresource:",
>     multilib => "-x64",
>     padlock_asm_src => "e_padlock-x86_64.s",
>     padlock_obj => "e_padlock-x86_64.o",
>     perlasm_scheme => "auto",
>     poly1305_asm_src => "poly1305-x86_64.s",
>     poly1305_obj => "poly1305-x86_64.o",
>     rc4_asm_src => "rc4-x86_64.s rc4-md5-x86_64.s",
>     rc4_obj => "rc4-x86_64.o rc4-md5-x86_64.o",
>     rc5_asm_src => "rc5_enc.c",
>     rc5_obj => "rc5_enc.o",
>     rcoutflag => "/fo",
>     rmd160_asm_src => "",
>     rmd160_obj => "",
>     sha1_asm_src => "sha1-x86_64.s sha256-x86_64.s sha512-x86_64.s sha1-mb-x86_64.s sha256-mb-x86_64.s",
>     sha1_obj => "sha1-x86_64.o sha256-x86_64.o sha512-x86_64.o sha1-mb-x86_64.o sha256-mb-x86_64.o",
>     shared_cflag => "",
>     shared_defines => [  ],
>     shared_extension => ".dll",
>     shared_extension_simple => ".dll",
>     shared_ldflag => "/dll",
>     shared_rcflag => "",
>     shared_target => "win-shared",
>     sys_id => "WIN64A",
>     thread_defines => [  ],
>     thread_scheme => "winthreads",
>     unistd => "<unistd.h>",
>     uplink_aux_src => "",
>     uplink_obj => "",
>     wp_asm_src => "wp-x86_64.s",
>     wp_obj => "wp-x86_64.o",
> 
> Recorded environment:
> 
>     AR = 
>     ARFLAGS = 
>     AS = 
>     ASFLAGS = 
>     BUILDFILE = 
>     CC = 
>     CFLAGS = 
>     CPP = 
>     CPPDEFINES = 
>     CPPFLAGS = 
>     CPPINCLUDES = 
>     CROSS_COMPILE = 
>     CXX = 
>     CXXFLAGS = 
>     HASHBANGPERL = 
>     LD = 
>     LDFLAGS = 
>     LDLIBS = 
>     MT = 
>     MTFLAGS = 
>     OPENSSL_LOCAL_CONFIG_DIR = 
>     PERL = 
>     RANLIB = 
>     RC = 
>     RCFLAGS = 
>     RM = 
>     WINDRES = 
>     __CNF_CFLAGS = 
>     __CNF_CPPDEFINES = 
>     __CNF_CPPFLAGS = 
>     __CNF_CPPINCLUDES = 
>     __CNF_CXXFLAGS = 
>     __CNF_LDFLAGS = 
>     __CNF_LDLIBS = 
> 
> Makevars:
> 
>     AR              = lib
>     ARFLAGS         = /nologo
>     AS              = nasm
>     ASFLAGS         = -g
>     CC              = cl
>     CFLAGS          = /W3 /wd4090 /nologo /O2
>     CPP             = $(CC) /EP /C
>     CPPDEFINES      = 
>     CPPFLAGS        = 
>     CPPINCLUDES     = 
>     CXXFLAGS        = 
>     HASHBANGPERL    = /usr/bin/env perl
>     LD              = link
>     LDFLAGS         = /nologo /debug
>     LDLIBS          = 
>     MT              = mt
>     MTFLAGS         = -nologo
>     PERL            = C:\portable\perl\perl\bin\perl.exe
>     RC              = rc
>     RCFLAGS         = 
> 
> NOTE: These variables only represent the configuration view.  The build file
> template may have processed these variables further, please have a look at the
> build file for more exact data:
>     makefile
> 
> build file:
> 
>     makefile
> 
> build file templates:
> 
>     Configurations\common0.tmpl
>     Configurations\windows-makefile.tmpl
>     Configurations\common.tmpl

**Comment by marcstern** [comment]
I'm not sure exactly which shell it uses, but it creates an empty file "NUL" because it tries to be as close as possible to a Linux environment.

**Comment by levitte** [comment]
In that case, it's not an issue with StrawberryPerl ...
These bits are designed with cmd.exe in mind.  What happens if you try it again in that shell?

**Comment by marcstern** [comment]
Sorry, I guess I wasn't clear.
I run "perl Configure" from cmd but StrawberryPerl's system() doesn't seem to support the "2>..." syntax, it interpretes it like in a Linux shell (performs some parsing before calling cmd.exe?).
Removing this part of the command definitely solves the problem.

For the other problem, I enabled the debug on line 3237 and here is the result:
> DEBUG[run_dofile]: $cmd = "C:\\portable\\perl\\perl\\bin\\perl.exe" "-I." "-Mconfigdata" "util\dofile.pl" -o"Configure" "Configurations\common0.tmpl" "Configurations\windows-makefile.tmpl" "Configurations\common.tmpl" > "C:\cache\waf\src\apache24\srclib\openssl-1.1\makefile.new"
When I run "C:\\portable\\perl\\..." (copy/paste) from cmd, it correctly creates the file makefile.new, but not from Configure.
Any idea?

**Comment by levitte** [comment]
This is curious, 'cause the "2>..." syntax *is* valid, both with cmd.exe and with Linux shells.

Here are the offending lines, I assume you refer to one of those:

https://github.com/openssl/openssl/blob/fecae608a9ad366a1bc740ad94628520cdf38d25/Configurations/10-main.conf#L8
https://github.com/openssl/openssl/blob/fecae608a9ad366a1bc740ad94628520cdf38d25/Configurations/10-main.conf#L33-L34

What happens if you run one of those commands on the command line?  i.e. one of these?

```
nasm -v 2>NUL
```

```
nasmw -v 2>NUL
```

**Comment by marcstern** [comment]
On the command-line, it works obviously, only from StrawberryPerl it poses a problem

**Comment by mspncp** [comment]
IANAPP (I am not a perl programmer ;-) ), but a quick search brought up [IPC::Run3](https://metacpan.org/pod/IPC::Run3). Could this maybe be a portable solution to the redirection problem @levitte?

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.

**Comment by smallSwed** [comment]
This is still an issue in 3.5.8, I provided a PR to fix the issue
