### ISSUE TITLE
Jumbo MTU caused https connect failure

### ISSUE THREAD

**Issue by tedtoal** [openssl/openssl#17941]
I don't know if this is an openssl problem or not, but seems like it might be so I'm reporting it here.

I had my ethernet MTU set to Jumbo.  This turned out to cause a failure to be able to connect to https://portal.gdc.cancer.gov

Changing to MTU: Standard caused the connection to work.  I don't know why the MTU setting would affect ability to connect.

This was on an iMac running macos 12.3 and my openssl version was LibreSSL 2.8.3

**Comment by paulidale** [comment]
LibreSSL is not OpenSSL.  You should ask them about this.

**Comment by mattcaswell** [comment]
It seems unlikely that this is actually an OpenSSL issue. This kind of lower level configuration is invisible to OpenSSL. But as @paulidale says LibreSSL isn't OpenSSL anyway.

**Comment by tmshort** [comment]
Even then, the browsers on a Mac don't use LibreSSL; Chrome uses BoringSSL, FireFox uses NSS and Safari uses Secure Transport. And once you get into MTU issues, the whole network needs to be brought into play. Is this IPv6? Is the MTU the same all the way to the website? A router in between may not like the jumbo frames; IPv6 and TCP don't like fragmentation.

**Comment by tedtoal** [comment]
Ok, sounds like the problem is more likely in some other element of the macOS networking.  BTW, though, the problem happened not only in browsers (various) but also by using curl.  Also, it happened with a different SSL besides LibreSSL, OpenSSL 1.1.1m.

**Comment by kroeckx** [comment]
Changing your MTU is most likely to cause problems because people block
ICMP causing Path MTU Discovery to fail, both for IPv4 and IPv6.
