### ISSUE TITLE
new_session_ticket message may contain invalid ticket_lifetime when using TLSv1.3

### ISSUE THREAD

**Issue by vogoltsov** [openssl/openssl#17948]
## Summary
Currently when new_session_ticket is created during TLSv1.3 handshake, ticket_lifetime is populated from session timeout (see `ssl/statem/statem_srvr.c`):
```c
static int create_ticket_prequel(SSL *s, WPACKET *pkt, uint32_t age_add,
                                 unsigned char *tick_nonce)
{
    /*
     * Ticket lifetime hint: For TLSv1.2 this is advisory only and we leave this
     * unspecified for resumed session (for simplicity).
     * In TLSv1.3 we reset the "time" field above, and always specify the
     * timeout.
     */
    if (!WPACKET_put_bytes_u32(pkt,
                               (s->hit && !SSL_IS_TLS13(s))
                               ? 0 : s->session->timeout)) {
```
The session timeout is not limited by OpenSSL - e.g. vsftpd uses `INT_MAX` as session timeout.
But according to [TLSv1.3 RFC](https://datatracker.ietf.org/doc/html/rfc8446), ticket lifetime must not exceed 7 days:
> ticket_lifetime:  Indicates the lifetime in seconds as a 32-bit unsigned integer in network byte order from the time of ticket issuance.  Servers **MUST NOT** use any value greater than 604800 seconds (7 days).

## Suggested fix
I got everything working by capping ticket lifetime at 604800 seconds (see below). Don't know if this fix is correct though (e.g. maybe TLS session timeout should be limited to 1 week?).
```diff
--- ssl/statem/statem_srvr.c.orig	2022-03-23 16:49:38.910745404 +0300
+++ ssl/statem/statem_srvr.c	2022-03-23 16:49:34.418743176 +0300
@@ -3828,7 +3828,7 @@
      */
     if (!WPACKET_put_bytes_u32(pkt,
                                (s->hit && !SSL_IS_TLS13(s))
-                               ? 0 : s->session->timeout)) {
+                               ? 0 : (s->session->timeout <= 604800 ? s->session->timeout : 604800))) {
         SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_CREATE_TICKET_PREQUEL,
                  ERR_R_INTERNAL_ERROR);
         return 0;
```

## Backstory
I have vsftpd-3.0.5 which has only TLS 1.3 enabled (TLS 1.2 and lower is disabled in server configuration) and requires TLS session reuse:
```
ssl_enable=YES
require_ssl_reuse=YES
implicit_ssl=NO
ssl_sslv2=NO
ssl_sslv3=NO
ssl_tlsv1=NO
ssl_tlsv11=NO
ssl_tlsv12=NO
ssl_tlsv13=YES
```
My java application is able to successfully connect, establish a secure connection using `STARTTLS` and authenticate on the server. However, when it tries to list directories on server (which requires a data connection to be established with TLS session reuse), I get `javax.net.ssl.SSLProtocolException: Received close_notify during handshake`. Debugging through the TLS (with `-Djavax.net.debug=all` added to JVM args) I came across the following piece of log:
```
javax.net.ssl|FINE|01|main|2022-03-23 17:41:53.804 AMT|NewSessionTicket.java:328|Consuming NewSessionTicket message (
"NewSessionTicket": {
  "ticket_lifetime"      : "2,147,483,647",
  "ticket_age_add"       : "<omitted>",
  "ticket_nonce"         : "00 00 00 00 00 00 00 00",
  "ticket"               : "8B 82 33 79 BD D6 90 0F AE 75 24 E0 85 89 7C 1A CC 71 AA F3 35 EF 52 43 57 96 49 50 0F E4 36 DF A8 1E FB C3 54 D6 FE 80 B2 7D 76 42 B2 0D 28 82 43 0D 58 FA EC 45 3C 1F F5 DE B9 34 84 0F DA 7D CC D5 E4 70 D3 C4 FA 34 3B DB C3 71 4D 1D CC 43 F3 F5 D7 90 4B 2C 19 0B 8A F4 E4 AA 3F 16 1F 46 CC 64 AD 6E F3 3D F8 0A DB 3E 98 4A DA 72 1E 00 F5 E3 AC 34 48 E1 10 A5 1F 04 F0 6C D9 64 13 38 40 AB 50 C5 06 DD 6A BE 48 58 45 65 A8 9D C4 B9 04 A2 F5 3B FE C7 CC 29 D1 E2 F9 4B AE F1 64 E2 93 FE 80 C8 7D 29 E8 C3 9A 18 1B CE 0A 1E 48 52 32 DD 86 F6 4C 2A 58 B9 BA 0F 79 D0 AD 22 01 92 D6 4D 88 FD 06 E4 18 3B 1B D3 81 B8 2F C3 B5 AB",
  "extensions"           : [
    <no extension>
  ]
}
)
javax.net.ssl|FINE|01|main|2022-03-23 17:41:53.804 AMT|NewSessionTicket.java:336|Discarding NewSessionTicket with lifetime 2147483647 (
"NewSessionTicket": {
  "ticket_lifetime"      : "2,147,483,647",
  "ticket_age_add"       : "<omitted>",
  "ticket_nonce"         : "00 00 00 00 00 00 00 00",
  "ticket"               : "8B 82 33 79 BD D6 90 0F AE 75 24 E0 85 89 7C 1A CC 71 AA F3 35 EF 52 43 57 96 49 50 0F E4 36 DF A8 1E FB C3 54 D6 FE 80 B2 7D 76 42 B2 0D 28 82 43 0D 58 FA EC 45 3C 1F F5 DE B9 34 84 0F DA 7D CC D5 E4 70 D3 C4 FA 34 3B DB C3 71 4D 1D CC 43 F3 F5 D7 90 4B 2C 19 0B 8A F4 E4 AA 3F 16 1F 46 CC 64 AD 6E F3 3D F8 0A DB 3E 98 4A DA 72 1E 00 F5 E3 AC 34 48 E1 10 A5 1F 04 F0 6C D9 64 13 38 40 AB 50 C5 06 DD 6A BE 48 58 45 65 A8 9D C4 B9 04 A2 F5 3B FE C7 CC 29 D1 E2 F9 4B AE F1 64 E2 93 FE 80 C8 7D 29 E8 C3 9A 18 1B CE 0A 1E 48 52 32 DD 86 F6 4C 2A 58 B9 BA 0F 79 D0 AD 22 01 92 D6 4D 88 FD 06 E4 18 3B 1B D3 81 B8 2F C3 B5 AB",
  "extensions"           : [
    <no extension>
  ]
}
)
```
What got my attention was `NewSessionTicket` being discarded by the client. Debugging through JVM TLS implementation I discovered that ticket lifetime was in invalid range. Looking through other language implementations I encountered the same ticket lifetime validity checks.
So the issue is that vsftpd sets session timeout to `INT_MAX` (which is valid I guess) - and OpenSSL uses this value as ticket lifetime without capping which leads to invalid tickets being sent by the server.

**Comment by tmshort** [comment]
I'll take a look at this

**Comment by tmshort** [comment]
Pushed to master, 3.0, 1.1.1. Thank you!
