### ISSUE TITLE
Cygwin should perhaps be designated Community supported

### ISSUE THREAD

**Issue by BrianInglis** [openssl/openssl#17957]
See [Latest Release Announcement](https://cygwin.com/pipermail/cygwin-announce/2022-March/010500.html)
[Cygwin Source Package](https://cygwin.com/packages/summary/openssl-src.html)
[Cygwin Binary Packages](https://cygwin.com/packages/summary/openssl.html)
[Cygwin Cygport Package Build Script Definitions Repo](https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/openssl.git)
[Cygwin Scallywag CI](https://cygwin.com/cgi-bin2/jobs.cgi?srcpkg=openssl)
Scallywag CI back end may be (default) *Github Actions*, or (legacy) *Appveyor*, depending on maintainer philosophy re GH
Scallywag CI result may be (default) build & test or (optional) build & test & deploy test release; 
may be flipped to current stable once the build, test, and deploy is successful
*Cygwin* packages are currently built to support running under Windows Vista thru 10, both 32 and 64 bit supported, but Vista and Server 2008 has recently been dropped, and 32 bit x86 support will be deprecated in the next major release and most packages not released for 32 bit x86 after that, see [Deprecation Notes](https://cygwin.com/pipermail/cygwin-announce/2022-January/010438.html)

**Comment by t8m** [comment]
For something to be community supported we will need the person who is willing to be the point of contact to submit a pull request on the openssl/web repository adding that target into the community supported list.

**Comment by mattcaswell** [comment]
The platform policy has this definition for community support:

"Definition: Platforms that one or more members of the OpenSSL community have volunteered to support. May or may not be in project CI. Members of the community providing support do not have to be committers."

https://www.openssl.org/policies/platformpolicy.html

So first of all it needs at least one named volunteer. That volunteer needs to be prepared to contribute patches for the platform back into OpenSSL and be pinged every once in a while if a platform specific problem arises to help find a resolution.

The existence of packages distributing OpenSSL for that platform is a good sign that someone somewhere might be willing to step into the role - but is not sufficient in itself. It's unclear if the official cygwin source packages are based on an unmodified upstream OpenSSL version, or whether they apply additional patches (as is common with many Linux distros for example). Whoever the volunteer is, has to be willing to support the unmodified upstream OpenSSL version. It might be appropriate to port any cygwin maintained patches into upstream OpenSSL to make that job easier - but that would be up to whoever that volunteer is, and whether they are willing to jump through the necessary hoops to make that happen.

Volunteering is straight forward. The volunteer simply has to make a PR against the openssl/web repo to make the necessary modifications to the platform policy page and have that PR approved. Once approved and merged its official.

**Comment by BrianInglis** [comment]
Thanks - using GH may be an issue for them
