### ISSUE TITLE
Reading the 'friendly name' from a pkcs12 file

### ISSUE THREAD

**Issue by jeroen** [openssl/openssl#1796]
The example in [pkwrite.c](https://github.com/openssl/openssl/blob/master/demos/pkcs12/pkwrite.c) sets a "friendly name" via the 2nd argument in `PKCS12_create()`. However it is unclear how to retrieve this name back from the p12 object.

The example [pkread.c](https://github.com/openssl/openssl/blob/master/demos/pkcs12/pkread.c) uses `PKCS12_parse()` to parse the key, cert and ca. However it does not show how to parse the friendly name.

There exists a function `PKCS12_get_friendlyname()`  however it requires a `PKCS12_SAFEBAG` argument instead of `PKCS12`. It is unclear how we extract the `name` that was set in `PKCS12_create()` from the `PKCS12` object.

**Comment by geniuz** [comment]
`static char *find_friendly_name(PKCS12 *p12)
{
    STACK_OF(PKCS7) *safes = PKCS12_unpack_authsafes(p12);
    int n, m;
    char *name = NULL;
    if (safes == NULL) return NULL;
    for (n = 0; n < sk_PKCS7_num(safes) && !name; n++) {
        PKCS7 *safe = sk_PKCS7_value(safes, n);
        STACK_OF(PKCS12_SAFEBAG) *bags;
        if (OBJ_obj2nid(safe->type) != NID_pkcs7_data) continue;
        bags = PKCS12_unpack_p7data(safe);
        if (!bags) continue;
        for (m = 0; m < sk_PKCS12_SAFEBAG_num(bags) && !name; m++) {
            PKCS12_SAFEBAG *bag = sk_PKCS12_SAFEBAG_value(bags, m);
            name = PKCS12_get_friendlyname(bag);
        }
        sk_PKCS12_SAFEBAG_pop_free(bags, PKCS12_SAFEBAG_free);
    }
    sk_PKCS7_pop_free(safes, PKCS7_free);
    return name;
}`

**Comment by richsalz** [comment]
The sample code in the master branch has been updated; thanks!
