### ISSUE TITLE
Encode/Decode for FIPS module

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#17968]
Most of ASN.1 functions in ec_asn1.c are below `#ifndef FIPS_MODULE` compilation condition.
(https://github.com/openssl/openssl/blob/master/crypto/ec/ec_asn1.c#L24).

Where is the relevant implementation of encoders/decoders for FIPS module?

**Comment by mattcaswell** [comment]
There are no encoders/decoders in the FIPS module. This is outside the FIPS boundary. Typically you will load the "base" provider at the same time as "fips" to ensure you have the encoders/decoders available without having to have the whole "default" provider loaded.

**Comment by beldmit** [comment]
So it should use the same code from ec_asn1?

**Comment by mattcaswell** [comment]
> So it should use the same code from ec_asn1?

The base provider does - yes.
