### ISSUE TITLE
Misleading error message(undefined symbol: EVP_PKEY_get_base_id) with engine load from OpenSSL1.1.1n

### ISSUE THREAD

**Issue by Yogaraj-Alamenda** [openssl/openssl#17962]
When doing engine load we are  seeing error message  "undefined symbol: EVP_PKEY_get_base_id" from DSO_bind_func() which checks for "EVP_PKEY_get_base_id"  as mentioned below which is due to changed from PR #17541

Here I am using OpenSSL 1.1.1n with Engine built and linked against OpenSSL 1.1.1n. Although there are no failures but the error messages mentioned below are misleading.  Any thoughts on this ? 

Engine : https://github.com/intel/QAT_Engine

``
./openssl engine -t -c  qatengine
139953561638272:error:2506406A:DSO support routines:dlfcn_bind_func:could not bind to the requested symbol name:crypto/dso/dso_dlfcn.c:188:symname(EVP_PKEY_get_base_id): /root/yoga/openssl_install/lib/engines-1.1/qatengine.so: undefined symbol: EVP_PKEY_get_base_id
139953561638272:error:2506C06A:DSO support routines:DSO_bind_func:could not bind to the requested symbol name:crypto/dso/dso_lib.c:186:
(qatengine) Reference implementation of QAT crypto engine(qat_sw) v0.6.11
 [RSA, id-aes128-GCM, id-aes192-GCM, id-aes256-GCM, X25519, SM2]
     [ available ]
``

**Comment by bernd-edlinger** [comment]
You can ignore this, it was meanwhile fixed.

**Comment by Yogaraj-Alamenda** [comment]
Can you please let commit details of the fix ?

**Comment by bernd-edlinger** [comment]
I referred to d6bf4a2218aeb246ba7d34f02e895c37569c8265
