### ISSUE TITLE
Openssl trying to use the cipher algorithm from older version in newer version

### ISSUE THREAD

**Issue by furkankahvecinsider** [openssl/openssl#17982]
Could we use the cipher algorithms from older versions in the newer versions?

Like "SEED-ECB". OpenSSL 1.0.1t version includes that cipher algorithm but does not include it in 1.1.1g version. I wanna use that cipher algorithm in 1.1.1g version. 

Is it possible? If it is, how? :pray:

**Comment by paulidale** [comment]
You need to load the legacy provider.

Have a look at the [migration guide](https://wiki.openssl.org/index.php/OpenSSL_3.0) sections 1.5 and 6.2.

**Comment by mattcaswell** [comment]
> You need to load the legacy provider.
> 
> Have a look at the [migration guide](https://wiki.openssl.org/index.php/OpenSSL_3.0) sections 1.5 and 6.2.

@paulidale your answer was about OpenSSL 3.0. @furkankahvecinsider is specifically asking about 1.1.1.

> Like "SEED-ECB". OpenSSL 1.0.1t version includes that cipher algorithm but does not include it in 1.1.1g version. I wanna use that cipher algorithm in 1.1.1g version.

"SEED-ECB" support *is* included in OpenSSL 1.1.1. Why do you think it is not?

**Comment by t8m** [comment]
Perhaps you're using some build of OpenSSL-1.1.1 that uses no-seed?

**Comment by t8m** [comment]
You would have to rebuild the openssl with `enable-seed` build time option.

**Comment by furkankahvecinsider** [comment]
How can  I do to rebuild the OpenSSL with "enable-seed". I'm a little strange, sorry for that.

**Comment by tmshort** [comment]
If you are using an OS distribution, they are likely changing the configuration when they package it. You will need to either patch the OS distribution (e.g. download RPM source, build, etc). Or download the original source from github/openssl.org and configure it yourself. 

But this isn't really an OpenSSL issue, but a packaging issue.

You should ask the OS distributor why SEED is disabled.

**Comment by furkankahvecinsider** [comment]
Actually, I'm using this alpine Linux package, is this really matter?

**Comment by mattcaswell** [comment]
Yes. Alpine explicitly disable seed in their packages. See line 105 here:

https://git.alpinelinux.org/aports/tree/main/openssl/APKBUILD

**Comment by furkankahvecinsider** [comment]
Haha so ironic, what should I do in this situation? Should I change to another package?

**Comment by t8m** [comment]
That's really up to you. There are a few options. You can for example build openssl locally if you need the Seed algo just for your application. Or you can report an issue to alpinelinux asking to re-enable that support. Or you can switch to a different Linux distro.
