### ISSUE TITLE
Link OpenSSL 3.0 error in libcurl on MacOS

### ISSUE THREAD

**Issue by oyljerry** [openssl/openssl#17994]
I compiled OpenSSL 3.0.2 success on MacOS. However, when I build libcurl with compiled OpenSSL lib. It produce error.

```
Undefined symbols for architecture x86_64:
  "_EVP_PKEY_id", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_peer_certificate", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
ld: symbol(s) not found for architecture x86_64
```

PS. When I use OpenSSL 1.1.1n, The libcurl can make successfully.

**Comment by oyljerry** [comment]
Yes, It use openssl-3.0.2 header and lib, You can see below configure, and I build from fully cleaned libcurl source.
```
   Host setup:       x86_64-apple-darwin20.6.0
  Install prefix:   /Users/test/Downloads/curl-7.82.0/curl
  Compiler:         gcc
   CFLAGS:          -Qunused-arguments -Wno-pointer-bool-conversion -Os -Werror=partial-availability -pthread
   CPPFLAGS:        -isystem /Users/test/Downloads/zlib-1.2.11/zlib/include -isystem /Users/test/Downloads/openssl-openssl-3.0.2/openssl/include -DOPENSSL_SUPPRESS_DEPRECATED
   LDFLAGS:         -framework CoreFoundation -framework SystemConfiguration -L/Users/test/Downloads/zlib-1.2.11/zlib/lib -L/Users/test/Downloads/openssl-openssl-3.0.2/openssl/lib
   LIBS:            -lssl -lcrypto -lssl -lcrypto -lz

  curl version:     7.82.0
  SSL:              enabled (OpenSSL v3+)

```

PS. I can see libcurl use many openssl function in code, but only these two ` ("_EVP_PKEY_id" and "_SSL_get_peer_certificate")` link error.

**Comment by t8m** [comment]
Are you sure the 1.1.1 headers are not in the system /usr/inculude path?

**Comment by oyljerry** [comment]
Thanks @t8m , It seems libcurl will use system /usr/local/include/openssl, However, I have set **/Users/test/Downloads/openssl-openssl-3.0.2/openssl/include**

**Comment by oyljerry** [comment]
> -isystem dir
Search dir for header files, after all directories specified by -I but before the standard system directories. Mark it as a system directory, so that it gets the same special treatment as is applied to the standard system directories. If dir begins with =, then the = will be replaced by the sysroot prefix; see --sysroot and -isysroot.

https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
