### ISSUE TITLE
SSL_CTX_load_verify_store

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#18005]
Hi All,

We are trying to NOT use physical certificate or private key files in our TLS implementation of a client(REQUESTER_CONNECTION).
Instead we want to use certificates from our Windows Certificate Store.
I will split my queries into 3:

[1]
So, when peer verification is enabled, SSL_CTX_load_verify_locations cannot be used as this involves file or folder paths.
Was thinking if we could use SSL_CTX_load_verify_store instead.
Unfortunately, I am unable to understand how the CAStore (URI) parameter can be given.
Can someone throw some light on the same?

[2]
Instead, can I set a call back function to perform the same using SSL_CTX_set_cert_verify_callback ?
I am reluctant to do this as I see call back functions mostly for servers. 
Is it fine to use call backs even if it is a client?

[3]
SSL_CTX_set_verify has the provision to give call back directly as a the third parameter.
So, is it wrong to set the call back function separately using SSL_CTX_set_cert_verify_callback?

Sorry for raising too many queries.
This is unknown territory for me and so any pointers will be of much help.

Thanks in advance.

Regards,
Amal

**Comment by t8m** [comment]
You would need a provider with an implementation of OSSL_STORE that would serve the certificates from the windows CA store.

**Comment by amaljesudas** [comment]
@t8m 

Thanks for the inputs.
Just to try, I used SSL_CTX_set_cert_verify_callback  and in made the call back function return true(1) always.
Unfortunately, am still not able to establish association with the server.
The server is java based and throws up the below error:
_javax.net.ssl.SSLHandshakeException: Empty server certificate chain in State: Sta2 - Transport connection open_
What else should I do from the client side to make it work?

**Comment by beldmit** [comment]
The exception looks like a server-side problem to me.

**Comment by amaljesudas** [comment]
Just to clarify an additional point, if I am a client and I have set SSL_CTX_set_verify to SSL_VERIFY_NONE, do I still have to load my certificate and private key to openssl? I am thinking the server is set for SSL_VERIFY_PEER and causing the above issue.

**Comment by t8m** [comment]
This looks like the server is misconfigured or something. I do not think you can do anything on client to fix that.

**Comment by amaljesudas** [comment]
Thanks @t8m. 
It works on another server where peer authentication is set to false. 
So I agree with your view that it has to be something related to server configuration.
