### ISSUE TITLE
Smart-Card based OpenVPN fails after upgrade to openssl3

### ISSUE THREAD

**Issue by apollo13** [openssl/openssl#18028]
Hi there,

this is a complex issue and I am not yet 100% sure whether this is an OpenSSL/OpenVPN/OpenSC issue. From all my debugging I did till now I think this might be an OpenSSL issue; so please be gentle and redirect me to the relevant projects if you think I am wrong.

OpenVPN uses client TLS certificates and in my case I am using the certificate on a Yubikey. When connecting I get the following output from OpenVPN (in this specific case the output is the info callback from OpenSSL):

```
2022-04-02 18:44:07 us=508919 SSL state (connect): SSLv3/TLS read server hello
2022-04-02 18:44:07 us=511134 VERIFY OK: depth=2, C=US, O=Entrust, Inc., OU=See www.entrust.net/legal-terms, OU=(c) 2009 Entrust, Inc. - for authorized use only, CN=Entrust Root Certification Authority - G2
2022-04-02 18:44:07 us=511625 VERIFY OK: depth=1, C=US, O=Entrust, Inc., OU=See www.entrust.net/legal-terms, OU=(c) 2012 Entrust, Inc. - for authorized use only, CN=Entrust Certification Authority - L1K
2022-04-02 18:44:07 us=512109 VERIFY X509NAME OK: CN=*.tld
2022-04-02 18:44:07 us=512156 VERIFY OK: depth=0, CN=*.tld
2022-04-02 18:44:07 us=514372 SSL state (connect): SSLv3/TLS read server certificate
2022-04-02 18:44:07 us=514774 SSL state (connect): SSLv3/TLS read server key exchange
2022-04-02 18:44:07 us=514974 SSL state (connect): SSLv3/TLS read server certificate request
2022-04-02 18:44:07 us=515012 SSL state (connect): SSLv3/TLS read server done
2022-04-02 18:44:07 us=515086 SSL state (connect): SSLv3/TLS write client certificate
2022-04-02 18:44:07 us=515758 PKCS#11: __pkcs11h_openssl_ex_data_free entered - parent=0x558b129515d0, ptr=(nil), ad=0x558b12951610, idx=1, argl=0, argp=0x7fdd062e0b58
2022-04-02 18:44:07 us=516172 SSL state (connect): SSLv3/TLS write client key exchange
2022-04-02 18:44:07 us=517993 SSL alert (write): fatal: internal error
2022-04-02 18:44:07 us=518052 OpenSSL: error:020000B3:rsa routines::missing private key
2022-04-02 18:44:07 us=518078 OpenSSL: error:1C880004:Provider routines::RSA lib
2022-04-02 18:44:07 us=518107 OpenSSL: error:0A080006:SSL routines::EVP lib
2022-04-02 18:44:07 us=518138 TLS_ERROR: BIO read tls_read_plaintext error
2022-04-02 18:44:07 us=518171 TLS Error: TLS object -> incoming plaintext read error
```

When I recompile pkcs11-helper/opensc/openvpn against openssl 1.1 it instead starts querying pkcs11 and asking for a token password:
```
SSL state (connect): SSLv3/TLS write client certificate
PKCS#11: __pkcs11h_openssl_ex_data_free entered - parent=0x22ccd50, ptr=(nil), ad=0x22ccd90, idx=1, argl=0, argp=0x7fc3109e6fde
SSL state (connect): SSLv3/TLS write client key exchange
PKCS#11: __pkcs11h_openssl_rsa_enc entered - flen=51, from=0x22e14c0, to=0x22ea9a0, rsa=0x2265940, padding=1
PKCS#11: Performing signature
PKCS#11: pkcs11h_certificate_signAny_ex entry certificate=0x227b000, mech_type=1, source=0x22e14c0, source_size=0000000000000033, target=0x22ea9a0, *p_target_size=0000000000000100
PKCS#11: Getting key attributes
PKCS#11: __pkcs11h_certificate_getKeyAttributes entry certificate=0x227b000
PKCS#11: _pkcs11h_session_freeObjectAttributes entry attrs=0x7ffd8accb290, count=6
PKCS#11: _pkcs11h_session_freeObjectAttributes return
```

I also tried swapping /usr/lib64/pkcs11/opensc-pkcs11.so with /usr/lib64/pkcs11/opensc-pkcs11.so but that just resulted in the same issue. Is there any way to better debug openSSL here?

**Comment by apollo13** [comment]
I am closing here, looks like an issue in pkcs11-helper.

**Comment by petrovr** [comment]
I wonder how to clasify this report
- engine based, i.e. https://github.com/openssl/openssl/issues/17092
- by key method, i.e. https://github.com/openssl/openssl/issues/17286

Due to error "OpenSSL: error:020000B3:rsa routines::missing private key" looks like second case.

**Comment by apollo13** [comment]
The issue was that pkcs11-helper used [EVP_PKEY_get1_RSA.html](https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_get1_RSA.html) and altered the returned key, which no longer works: 

>     ... will be a cached copy of the provider's key. Subsequent updates to the provider's key will not be reflected back in the cached copy, and updates made by an application to the returned key will not be reflected back in the provider's key.

**Comment by petrovr** [comment]
So it is design failure in OpenSSL 3?

**Comment by apollo13** [comment]
No idea, I am not a OpenSSL developer -- it is not for me to say whether the new designer is better or worse. The proper solution seems to implement a custom provider. This is also what openvpn does for external keys coming up in openvpn 2.6.

**Comment by petrovr** [comment]
There is no announcement that OpenSSL will not support custom key method not engine based. Functionality is **deprecated** but **not removed**!

Remark: get0 returns constant instance so cannot be used for updates.

**Comment by mattcaswell** [comment]
3.0 is a major version change and consequently is not guaranteed to be 100% API compatible. We tried to minimise the places where the API was actually broken between 1.1.1 and 3.0, but this is one of those places. It was a deliberate design decision to do this (basically it was the least worse option).

**Comment by petrovr** [comment]
So get1[0|1|_<KEYTYPE> "return cached copy of the provider's key" **of provider key**. 
But case is NOT for provider keys. So cached copy does not make sense and get0/get1 must work as before.

As is reported in issue #17092 impacted are RSA and DSA keys, not EC keys. Why? The difference is how engine is associated with ecdsa/ec keys.
Let review ec process in e_nss:
a) pkey created by "DER to Internal" function over public key data
b) engine method is set unconditionally on key  obtained by get1_<KEYTYPE>
c) application context is set on key, Remark: obtained by get1_<KEYTYPE>

So in above scenario after point b) key and pkey should be considered as non-provider key.

RSA/DSA differ as exist API that allows program to get method associated with key.
Code  in e_nss engine has an "optimisation"  to avoid key recreation if key uses engine provided method. So b) looks like:
b) key  obtained by get1_<KEYTYPE>
b.1) if method match provide by engine go to c)
b.2) replace key: create new engine base key using <KEYTYPE>_new_method(e), copy public part and assign newly created key on pkey.
c) as for ecdsa/ec keys

Why does not work? Trace shows that key is already created with engine method! The lost application context indicates use of "cached copy".

What I do: I comment "optimisation" just for testing and RSA/DSA key tests pass.

---
Conclusion:
Explicit set of key method provided by engine works.

OpenSSL **defect** is that it consider as "provider key" a key that uses engine method set implicitly!
Remark: In case of e_nss method is d2i_PUBKEY. 

---
About this issue: if a key uses external method it cannot be considered as provider key.
