### ISSUE TITLE
Is there a way to download a tar.gz archive of 3.x like previous versions

### ISSUE THREAD

**Issue by iiordanov** [openssl/openssl#18027]
It doesn look like I can download 3.0.2 using the method (1.1.1n as example):

curl -Lo /tmp/OpenSSL_1_1_1n.tar.gz https://github.com/openssl/openssl/archive/OpenSSL_1_1_1n.tar.gz

Would you consider re-instating the availability of archives for 3.x versions as well?

Thank you!

**Comment by tmshort** [comment]
The archives are available on github:
https://github.com/openssl/openssl/releases/tag/openssl-3.0.2

The name of the file is based on the tag name which changed for OpenSSL 3.0.

The tarballs may also be found on openssl.org:
Information can be found here: https://www.openssl.org/source/

**Comment by iiordanov** [comment]
Thank you so much!

iordan

**Comment by mspncp** [comment]
Note: The official download location is `www.openssl.org/source/openssl-<version>.tar.gz`, e.g:

- https://www.openssl.org/source/openssl-3.0.1.tar.gz

If you visit www.openssl.org/source in the browser , you will notice that older versions are moved into the [source/old](https://www.openssl.org/source/old) subfolder. 

- https://www.openssl.org/source/old/3.0/openssl-3.0.1.tar.gz

However, the original download url remains valid, in order not to break automated downloads by build scripts.

**Comment by iiordanov** [comment]
Thanks!

In that case, I'll make a PR to FreeRDP to switch them over to the official download location.

**Comment by mspncp** [comment]
> In that case, I'll make a PR to FreeRDP to switch them over to the official download location.

That's indeed the better choice.

Please also note the following important difference: Although the GitHub achive is created from the same commit as the official tarball, the two are not absolutely identical, as you can see.

```
~/tmp/openssl$ curl -JOL https://www.openssl.org/source/openssl-3.0.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.3M  100 14.3M    0     0  39.3M      0 --:--:-- --:--:-- --:--:-- 39.3M
```

```
~/tmp/openssl$ curl -JOL https://github.com/openssl/openssl/archive/refs/tags/openssl-3.0.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   140  100   140    0     0    836      0 --:--:-- --:--:-- --:--:--   838
100 14.4M  100 14.4M    0     0  15.7M      0 --:--:-- --:--:-- --:--:-- 23.9M
```

```
~/tmp/openssl$ ls -l
total 29520
-rw-r--r-- 1 msp msp 15038141  3. Apr 15:24 openssl-3.0.2.tar.gz
-rw-r--r-- 1 msp msp 15183465  3. Apr 15:25 openssl-openssl-3.0.2.tar.gz
```

In particular the SHA256 hash of the GitHub archive is not identical with the one from the release announcement:
 
```
~/tmp/openssl$ sha256sum *.tar.gz 
98e91ccead4d4756ae3c9cde5e09191a8e586d9f4d50838e7ec09d6411dfdb63  openssl-3.0.2.tar.gz
9f54d42aed56f62889e8384895c968e24d57eae701012776d5f18fb9f2ae48b0  openssl-openssl-3.0.2.tar.gz
```

```
~/tmp/openssl$ curl -JOL https://www.openssl.org/source/openssl-3.0.2.tar.gz.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    66  100    66    0     0   1261      0 --:--:-- --:--:-- --:--:--  1269
```

```
~/tmp/openssl$ cat openssl-3.0.2.tar.gz.sha256 
 98e91ccead4d4756ae3c9cde5e09191a8e586d9f4d50838e7ec09d6411dfdb63
```

_**Note:** I took the effort to analyze why the two tarballs are different, and in particular why their sizes differ. It turns out that the extra `openssl-` prefix which you see in the name of the GitHub tarball also accounts for its extra size, because also the extracted directory has this prefix, which increases the length of all stored file paths. This is the only difference, the contents of the extracted directories are identical._

**Comment by iiordanov** [comment]
Thanks for the analysis @mspncp.
