### ISSUE TITLE
Function to retrieve value set by SSL_CTX_set1_verify_cert_store()

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#18035]
Currently we do not have a way to retrieve the `X509_STORE *` set in `SSL_CTX_set1_verify_cert_store`. We should consider adding a `SSL_CTX_get_verify_cert_store` function.

**Comment by nhorman** [comment]
Given that:
https://www.openssl.org/source/
indicated 1.1.1 is no longer supported, marking this as inactive, to be closed at the end of 3.4 dev
