### ISSUE TITLE
Setting unsupported cipher suites

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#18036]
I was trying to set DHE-DSS-AES256-GCM-SHA384 for my client-server communication.
The API SSL_CTX_set_cipher_list fails for the above cipher suite.
I listed out the ciphers supported by my version of openssl(v1.1.1l) using the command **openssl ciphers -v**
DHE-DSS-AES256-GCM-SHA384 was not part of the  list.
So, I assume that this is why SSL_CTX_set_cipher_list failed (Please correct me if I am wrong.).
Now, if the given set up is same, is there anything that I can do to get the cipher supported?
Will building openssl with some flag setting help?

Thanks in advance.

**Comment by t8m** [comment]
The cipher requires having a DSA key and certificate on the server. Are you sure you have such certificate?

What `openssl ciphers -v DHE-DSS-AES256-GCM-SHA384` prints?

**Comment by amaljesudas** [comment]
Hi @t8m 

Thanks for the inputs.
`openssl ciphers -v DHE-DSS-AES256-GCM-SHA384` prints the below lines:

_TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
DHE-DSS-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=DSS  Enc=AESGCM(256) Mac=AEAD_

As for the certificate support, I am not too positive. I was checking using the default certificates that came with the test server. If possible, can you shed some more light on the DSA key and certificate requirement?

Thank in advance.

**Comment by t8m** [comment]
You need to understand that the DHE-DSS ciphersuites require DSA certificates to be enabled. These are not really used in the real world anymore if they have ever been used. If you do not know this, why you're trying to enable this particular ciphersuite?

**Comment by amaljesudas** [comment]
Thanks @t8m 
I am just testing some cipher suites for a new implementation of secure library for a desktop application.
The above cipher suite was one that was already present for selection from the UI module.
It is the first time I am dealing with DHE-DSS ciphers, so there are gaps in my understanding on the same.

I just have one more query based on your comment:
I am getting this error when I try to set this cipher using SSL_CTX_set_cipher_list.
Assuming that I am a client and do not plan to provide my certificate or do peer authentication, why would SSL_CTX_set_cipher_list return error?
Is any internal certificate validation done when SSL_CTX_set_cipher_list is called?
Sorry if I understood anything differently.

**Comment by t8m** [comment]
Hmm, on client side it should not matter and `SSL_CTX_set_cipher_list(ctx, "DHE-DSS-AES256-GCM-SHA384")` shouldn't fail. Are there possibly any errors on the error stack? (Call `ERR_print_errors_fp(stderr);` to find out.)

**Comment by t8m** [comment]
BTW the `SSL_CTX_set_cipher_list(ctx, "DHE-DSS-AES256-GCM-SHA384")` call shouldn't fail even on the server side. But the server will not offer this ciphersuite if it does not have a DSA certificate.

This call would fail only in case the DSA support is disabled - which shouldn't be the case if `openssl ciphers -v DHE-DSS-AES256-GCM-SHA384` shows the ciphersuite. Unless you link to some other openssl build than the openssl ciphers command is using.

**Comment by amaljesudas** [comment]
I tried on a different machine and it worked.
Think some openssl library mismatch caused this.
I will analyze further but will close the issue for now.
Thanks.
