### ISSUE TITLE
s_server infinite loop bug

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#18047]
Under certain circumstances s_server can enter an infinite loop when using -dtls.

For example starting s_server like this (with a fips enabled build):

````
$ OPENSSL_CONF=test/fips.cnf openssl s_server -nocert -psk 01020304 -dtls1
````

And calling s_client like this:

````
$ openssl s_client -dtls1 -psk 01020304
````

Results in the following output from s_server:

````
Using default temp DH parameters
ACCEPT
ERROR
40771262307F0000:error:0A000129:SSL routines:tls_setup_handshake:no suitable digest algorithm:ssl/statem/statem_lib.c:121:The max supported SSL/TLS version needs the MD5-SHA1 digest but it is not available in the loaded providers. Use (D)TLSv1.2 or above, or load different providers
ERROR
40771262307F0000:error:0A000129:SSL routines:tls_setup_handshake:no suitable digest algorithm:ssl/statem/statem_lib.c:121:The max supported SSL/TLS version needs the MD5-SHA1 digest but it is not available in the loaded providers. Use (D)TLSv1.2 or above, or load different providers
ERROR
40771262307F0000:error:0A000129:SSL routines:tls_setup_handshake:no suitable digest algorithm:ssl/statem/statem_lib.c:121:The max supported SSL/TLS version needs the MD5-SHA1 digest but it is not available in the loaded providers. Use (D)TLSv1.2 or above, or load different providers
ERROR
...and so on...
````

The problem occurs because `SSL_accept` fails with `SSL_ERROR_SSL` before anything is read from the underlying BIO. However `do_server` in s_socket.c simply loops around again and tries to process the next connection, and exactly the same problem occurs again.

This is the same thing as this bug:
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1947588

That bug only affects Ubuntu packages - but it is the same underlying cause.

This particular instance of the bug only affects 3.0, but the underlying problem exists in earlier versions (1.1.1). The Ubuntu issue impacts 1.1.1 too.

**Comment by kaduk** [comment]
Seems to be fixed on 1.1.1 now.
