### ISSUE TITLE
OpenSSL* SHA Crash Bug

### ISSUE THREAD

**Issue by BlackSheepxs** [openssl/openssl#18044]
A workaround published by Intel in 2019 but a lot of unaware people run into this bug in 2022 . Can this be fixed so no tinkering required in the future?
Please check out this link from Intel site.
https://www.intel.com/content/www/us/en/developer/articles/troubleshooting/openssl-sha-crash-bug-requires-application-update.html

Have a great day.

**Comment by paulidale** [comment]
This has been fixed.  The referenced article claims it was fixed in 1.0.2L.  Anyone encountering this should upgrade to a fixed version.

Moreover, 1.0.2 is not a supported version.
