### ISSUE TITLE
double free caused by SSL_CTX_use_RSAPrivateKey()

### ISSUE THREAD

**Issue by zhou1615** [openssl/openssl#18040]
In SSL_CTX_use_RSAPrivateKey(),  the function RSA_free(rsa) will only be called on 
one error path.
However, all callers of SSL_CTX_use_RSAPrivateKey() will call RSA_free(rsa) 
right after SSL_CTX_use_RSAPrivateKey(), which could lead to a double free 
by calling RSA_free(rsa) twice.

This bug is found by a static analyzer, and I am not sure it is a feature or a bug.
If you agree it is a bug, I will submit a PR to fix it.

**Comment by hlandau** [comment]
```c
int SSL_CTX_use_RSAPrivateKey(SSL_CTX *ctx, RSA *rsa)
{
    int ret;
    EVP_PKEY *pkey;

    if (rsa == NULL) {
        ERR_raise(ERR_LIB_SSL, ERR_R_PASSED_NULL_PARAMETER);
        return 0;
    }
    if ((pkey = EVP_PKEY_new()) == NULL) {
        ERR_raise(ERR_LIB_SSL, ERR_R_EVP_LIB);
        return 0;
    }

    RSA_up_ref(rsa);
    if (EVP_PKEY_assign_RSA(pkey, rsa) <= 0) {
        RSA_free(rsa);
        EVP_PKEY_free(pkey);
        return 0;
    }

    ret = SSL_CTX_use_PrivateKey(ctx, pkey);
    EVP_PKEY_free(pkey);
    return ret;
}
```
It does not look like this is a double free to me, since `RSA_free` is only called if `RSA_up_ref` has previously been called. If either of the first two error cases occur the net change in the RSA refcount is zero.

**Comment by t8m** [comment]
Not a bug, closing.

**Comment by t8m** [comment]
@zhou1615 Please understand that many static analyzers do not understand refcounting.
