### ISSUE TITLE
Need add a api to get pctx->legacy_keytype for sm2 pkey in OpenSSL 3.0

### ISSUE THREAD

**Issue by Wenxing-hou** [openssl/openssl#18051]
We are updating OpenSSL to 3.0 for LibSPDM: [update openssl 3.0.2](https://github.com/DMTF/libspdm/issues/735).

When we use `pkey = X509_get_pubkey(x509_cert)` to get sm2 key from cert, we want get the pkey type: `EVP_PKEY_get_base_id(pkey)`.  We get **the pkey type is -1**. 

It is a regression issue.  In old solution, we use :
```
    EVP_PKEY_set_alias_type(pkey, EVP_PKEY_EC);
    ec_key = EVP_PKEY_get0_EC_KEY(pkey);
    EVP_PKEY_set_alias_type(pkey, EVP_PKEY_SM2);
```
to set the sm2 pkey type.  EVP_PKEY_EC is ec key type(408). EVP_PKEY_SM2 is sm2 key type(1172).

I find in function `evp_pkey_ctx_ctrl_to_param` :
```
int evp_pkey_ctx_ctrl_to_param(EVP_PKEY_CTX *pctx,
                               int keytype, int optype,
                               int cmd, int p1, void *p2)
{
    ...
    if (keytype == -1)
        keytype = pctx->legacy_keytype;
    ...
}
```

I think OpenSSL  3.0 should add a api to get the pctx->legacy_keytype to distinguish sm2 pkey type.
The code flow is such as:

```
pkey = X509_get_pubkey(x509_cert);
|
V
pkey_ctx = EVP_PKEY_CTX_new(pkey, NULL);
|
V
type = evp_pkey_ctx_get_legacy_keytype(pkey_ctx ); // the function we should support
|
V
if(type  == sm2_key_type) ;// the sm2_key_type is 1172
```

**Comment by t8m** [comment]
Is the `EVP_PKEY_is_a(pkey, "SM2")` returning 0 in your case?

**Comment by Wenxing-hou** [comment]
Thanks. I try the function and the return is 1 in my case.
```
    pkey = X509_get_pubkey(x509_cert);
    if (pkey == NULL) {
        goto done;
    }

    int test;
    test = EVP_PKEY_is_a(pkey, "SM2");
```

**Comment by t8m** [comment]
Maybe I do not really understand what do you need here.

The PKEY is already a SM2 key, to test whether some PKEY is a SM2 key you can use this `EVP_PKEY_is_a(pkey, "SM2")` function.

**Comment by Wenxing-hou** [comment]
Yes. I don't know the `EVP_PKEY_is_a`  function before. Thanks. I will call the `EVP_PKEY_is_a`  function  to distinguish sm2 pkey type.

**Comment by t8m** [comment]
I am closing this request then.
