### ISSUE TITLE
OCSP_basic_verify with flag OCSP_NOCHECKS returns positive result when it should not

### ISSUE THREAD

**Issue by metsma** [openssl/openssl#18053]
Using OCSP_basic_verify with flag OCSP_NOCHECKS and there are issues in chain verify function returns 1.
In code helper function ocsp_verify_signer claims to return only -1, 0 or 1 result
https://github.com/openssl/openssl/blob/master/crypto/ocsp/ocsp_vfy.c#L29-L30
```
/* Returns 1 on success, 0 on failure, or -1 on fatal error */
static int ocsp_verify_signer(X509 *signer, int response,
```
and when certificate verify fails, then chain error code is assigned to ret value (eg. X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY 20)
https://github.com/openssl/openssl/blob/master/crypto/ocsp/ocsp_vfy.c#L60-L65
```
    ret = X509_verify_cert(ctx);
    if (ret <= 0) {
        ret = X509_STORE_CTX_get_error(ctx);
        ERR_raise_data(ERR_LIB_OCSP, OCSP_R_CERTIFICATE_VERIFY_ERROR,
                       "Verify error: %s", X509_verify_cert_error_string(ret));
        goto end;
```
and later ret value is returned from function
https://github.com/openssl/openssl/blob/master/crypto/ocsp/ocsp_vfy.c#L70-L72
```
 end:
    X509_STORE_CTX_free(ctx);
    return ret;
```
In OCSP_basic_verify the ocsp_verify_signer result is checked ret <= 0.
If ocsp_verify_signer returns code 20 this check is skipped.
If flag OCSP_NOCHECKS is set then `res` is set to 1 and function returns positive result
https://github.com/openssl/openssl/blob/master/crypto/ocsp/ocsp_vfy.c#L122-L128
```
        ret = ocsp_verify_signer(signer, 1, st, flags, untrusted, &chain);
        if (ret <= 0)
            goto end;
        if ((flags & OCSP_NOCHECKS) != 0) {
            ret = 1;
            goto end;
        }
```

**Comment by kaduk** [comment]
Just to check that I'm understanding correctly: you seem to be saying that this chunk of code:
https://github.com/openssl/openssl/blob/801c638c50406c93d683c1ab8bd1d430cff4b6d0/crypto/ocsp/ocsp_vfy.c#L60-L65
should not be changing the value of `ret`, and should instead only use the value of `X509_STORE_CTX_get_error()` in the call to `ERR_raise_data()` (but not in the value returned from `ocsp_verify_signer()`)?
On first look that seems correct.
