### ISSUE TITLE
When calculate cmac with iv value using openssl.

### ISSUE THREAD

**Issue by xaqfan** [openssl/openssl#18067]
Hi,
Now ,I have a requirement。
That is calculate cmac value with iv.
But I have no idea,and  have methods with mbedtls.

polarssl:
```
     size_t mactlen;
    CMAC_CTX *ctx = CMAC_CTX_new();
    CMAC_Init(ctx, key, keysize/8, EVP_aes_128_ecb(), NULL);

    CMAC_Update(ctx, input, length);
    CMAC_Final(ctx, output, &mactlen);

    CMAC_CTX_free(ctx);
```

mbedtls:
```
     mbedtls_cipher_init( &ctx );
    if( ( ret = mbedtls_cipher_setup( &ctx, cipher_info ) ) != 0 )
        goto exit;
    ret = mbedtls_cipher_cmac_starts( &ctx, key, keylen );
    //add iv,state
    memcpy(ctx.cmac_ctx->state, iv, 16);    // this is important.
```

Any one have ideas?
Thanks.

**Comment by paulidale** [comment]
Have you read the [EVP_MAC man-page](https://www.openssl.org/docs/man3.0/man3/EVP_MAC.html)?

**Comment by xaqfan** [comment]
i have readed it .But i have no idea for replcace iv method

**Comment by paulidale** [comment]
Go back and look at the man page.  Understand it.  The example is for a CMAC/AES-128-CBC which is exactly what you are wanting.

As for your question, I suggest you look at [this](https://letmegooglethat.com/?q=does+cmac+have+an+iv).
The second from top result is relevant.

**Comment by xaqfan** [comment]
Hi,
thanks you for suggest ,And i have compiled openssl 3.0 and tested it .
But it seems wrong.

size_t mactlen = 0;
    EVP_MAC *mac = EVP_MAC_fetch(NULL, "CMAC", NULL);                                                                                                                                                              
    if(mac == NULL)
    {
        return -1;
    }

    OSSL_PARAM params[2] = {0};
    params[0] = OSSL_PARAM_construct_utf8_string("cipher","aes-128-ecb", 0);
    params[1] = OSSL_PARAM_construct_end();

    EVP_MAC_CTX *ctx = EVP_MAC_CTX_new(mac);
    if(ctx == NULL)
    {
        return -1;
    }
    EVP_MAC_init(ctx, (const unsigned char *)key, keysize/8,params);
    EVP_MAC_update(ctx, input,length);
    EVP_MAC_final(ctx, output, &mactlen, 4096);
    EVP_MAC_CTX_free(ctx);
    EVP_MAC_free(mac);

input:
00 00 00 00 00 00 00 00 00 00 00 04 00 00 80 01 bf c3 29 11 c7 18 c3 40 bc a2 84 d8 a9 45 a4 9d
or 
00 00 00 00 00 00 00 00 00 00 00 06 00 00 80 01 bf c3 29 11 c7 18 c3 40 bc a2 84 d8 a9 45 a4 9d

others argument is same. but result is same.

04 cf ff 1b 09 74 a5 82 31 b2 d6 60 27 f5 b2 db

**Comment by beldmit** [comment]
Why do you use ECB? It should ignore IV totally. CMAC implies CBC mode

**Comment by xaqfan** [comment]
Because it refer to the code implemented with mbedtls .

**Comment by xaqfan** [comment]
refered mbedtls code:
cipher_info = mbedtls_cipher_info_from_type( MBEDTLS_CIPHER_AES_128_ECB );

mbedtls_cipher_init( &ctx );
if( ( ret = mbedtls_cipher_setup( &ctx, cipher_info ) ) != 0 )
goto exit;
ret = mbedtls_cipher_cmac_starts( &ctx, key, keylen );
//add iv,state
memcpy(ctx.cmac_ctx->state, iv, 16); // this is important.

**Comment by xaqfan** [comment]
> Why do you use ECB? It should ignore IV totally. CMAC implies CBC mode

thanks ,i replace ecb  with cbc.now ,it successfully.
But ,now i have another problem.
When set iv parameter with cbc ,the value of  calculate is wrong.

EVP_MAC *mac = EVP_MAC_fetch(NULL, "CMAC", NULL);
    OSSL_PARAM params[3] = {0}; 
    params[0] = OSSL_PARAM_construct_utf8_string(OSSL_MAC_PARAM_CIPHER,"aes-128-cbc", 0);
    params[1] = OSSL_PARAM_construct_octet_string(OSSL_KDF_PARAM_SEED,iv,16);
    params[2] = OSSL_PARAM_construct_end();

    EVP_MAC_CTX *ctx = EVP_MAC_CTX_new(mac);
    EVP_MAC_init(ctx, key,keysize/8,params);
    EVP_MAC_update(ctx, input,length);
    EVP_MAC_final(ctx, output, &mactlen, 16);

**Comment by t8m** [comment]
> When set iv parameter with cbc ,the value of calculate is wrong.

What is the key, what is the IV and what is the expected and computed MACed data value?

**Comment by xaqfan** [comment]
I have implemented it  in other ways.
