### ISSUE TITLE
Question regarding RSA signature generation ACVP tests in 3.0.X

### ISSUE THREAD

**Issue by abkarcher** [openssl/openssl#18064]
Hello,

I have been reviewing acvp_test.c/.inc for some related work, and had a quick question. It looks like for RSA signature generation tests, a call is sent to a function called sig_gen to generate a signature with the given pkey, params, msg, etc. However, I do not understand where the given OSSL_PARAMs for padding type, digest, and salt len are used in the signature generation process. It appears that in sig_gen, the function call to EVP_DigestSignInit_ex on line 100:

```
        || !TEST_int_eq(EVP_DigestSignInit_ex(md_ctx, NULL, digest_name, libctx,
                                              NULL, pkey, NULL), 1)
  ```
references NULL instead of "params" even when params is provided to sig_gen.
Doesn't this mean that the RSA signature generation tests are all using the default padding/digest/salt len? Or are the params associated with this process somewhere else I am missing?

Thanks for your time!
Andrew

**Comment by paulidale** [comment]
> Doesn't this mean that the RSA signature generation tests are all using the default padding/digest/salt len?

Yes.

> Or are the params associated with this process somewhere else I am missing?

Nope.

The `acvp_test.c` file is an example of how ACVP tests might be written.  It is not an ACVP test suite.  It makes no attempt to cover everything required.

**Comment by abkarcher** [comment]
Hello,

Thanks for the explanation! That does make sense. I would still have a question as to why the RSA siggen tests provided in acvp_test.inc declare non-default parameters in them only to be not used, but either way it seems like a non issue. Closing - 

Thanks,
Andrew
