### ISSUE TITLE
Minor issue in EVP_SIGNATURE RSA documentation for PSS saltlen (3.0.X)

### ISSUE THREAD

**Issue by abkarcher** [openssl/openssl#18066]
Looking at this page here -
https://www.openssl.org/docs/man3.0/man7/EVP_SIGNATURE-RSA.html

Indicates that to set a salt len param for PSS padding for RSA signatures, you would use the "pss-saltlen" key with a utf8_string value representing an integer. 

Working with the code, the key seems to be just "saltlen" and you would use an integer for any specific lengths, or a utf8_string for one of the given special values.

Thanks for your time,
Andrew

**Comment by t8m** [comment]
You can actually use both an utf8_string with a decimal saltlen or an integer value. So the documentation is correct but incomplete in the sense that OSSL_PARAM_INTEGER values are also supported.
