### ISSUE TITLE
3.0.2: OSSL_ENCODER_to_data issue

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#18060]
I was working to convert old 1.1.1 code to the new 3.0 decoder/encoder API for handling keys and stumbled on this issue.

https://github.com/openssl/openssl/blob/948cf521798a801cfde47a137343e6f958d71f04/crypto/encode_decode/encoder_lib.c#L130

I think this line is wrong and should be

`*pdata_len += buf->length;`

Called the function with buf == NULL first to get the size, then allocated proper buffer and set the size, when function is called, size is 0 and the buffer pointer is altered.

**Comment by paulidale** [comment]
I'm pretty sure this is correct as it stands.  The length has been set earlier, this is advancing the pointer for the next lump of data.  @levitte can confirm.

**Comment by levitte** [comment]
This behavior is documented:

https://github.com/openssl/openssl/blob/bc6bac8561ead83d6135f376ffcbbb0b657e64fe/doc/man3/OSSL_ENCODER_to_bio.pod?plain=1#L36-L39

It's meant to mimic the behavior of d2i functions.

**Comment by t8m** [comment]
Closing.
