### ISSUE TITLE
For sslv23 , how to allow only TLSv1.2 and TLSv1.3

### ISSUE THREAD

**Issue by shaarang** [openssl/openssl#18078]
Hello,

In case of sslv23 , how to allow only TLSv1.2 and TLSv1.3 ?
Is there any configuration option available?

**Comment by t8m** [comment]
Yes, you can call SSL_CTX_set_min_proto_version(ctx, TLS1_2_VERSION) to limit the minimum TLS version to TLS1.2.

**Comment by ydroneaud** [comment]
Or you already use your own custom built OpenSSL, it can built without support for deprecated SSL/TLS versions: 

```
./Configure \
        no-ssl3    no-ssl3-method \
        no-tls1    no-tls1-method \
        no-tls1_1  no-tls1_1-method
```
