### ISSUE TITLE
Android issue with the latest NDK on OS X

### ISSUE THREAD

**Issue by wolfviking0** [openssl/openssl#18076]
Hello, 

I am trying to build OpenSSL (libcrypto.a and libssl.a) for Android using the NDK 21.4.7075529 and Android Platform 29 for arm64 

I was able to setup almost everything but I keep having this issue coming regarding 

```
~/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64//sysroot/usr/include/android/legacy_signal_inlines.h:138:10: error: 'bsd_signal' is unavailable: obsoleted in Android 21
  return bsd_signal(s, f);
         ^
~/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64//sysroot/usr/include/android/legacy_signal_inlines.h:41:14: note: 'bsd_signal' has been explicitly marked unavailable here
sighandler_t bsd_signal(int __signal, sighandler_t __handler) __REMOVED_IN(21);
```

I tried to find some workaround on google but so far I am stuck. Do you have any suggestion how I can fix that without using an older platform, because to support arm64 need to use 21+ version.

Thanks

**Comment by xtkoba** [comment]
Seems like `__ANDROID_API__` is not defined (properly). This reminds me of #16560.

BTW, what version of OpenSSL are you trying to build?

**Comment by paulidale** [comment]
I'm confused.  OpenSSL does not contain a call to `bsd_signal`.  So this feels more like an infrastructure issue.

**Comment by wolfviking0** [comment]
Yes I think you right, the problem is more with the argument parameter.

Anyway I decide to choose another approach to build openssl cross platform using cmake.

I was able to create the ssl and crypto lib this way for android.

Thanks
