### ISSUE TITLE
Question about RSA KeyGen FIPS algorithm cert

### ISSUE THREAD

**Issue by abkarcher** [openssl/openssl#18084]
Hello,

Quick question about FIPS cert for RSA KeyGen. The 3.0 FIPS provider ACVP cert claims capabilities of testing FIPS 186-4 with B.3.3 mode testing (probable primes). 

https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?product=14433

However, the documentation and a few issues prior to the submission claim FIPS to support B.3.6 (probable primes with conditions based on aux. probable primes).
https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-RSA.html#CONFORMING-TO
https://github.com/openssl/openssl/issues/15233
etc

Is it possible we could get some clarification on this?
 
Thanks so much for your time!
Andrew

**Comment by abkarcher** [comment]
Hello,

Without knowing much of the background information, I do have some info from purely an ACVP testing perspective. I was able to run B.3.3 testing fairly easily, as it is not particularly in depth testing. I passed a full session using the same registration capabilities currently on the ACVP cert.

When trying to run B.3.6 testing, I was having a fair amount of issues. Whenever I would try to set xP/xP1/xP2/xQ/xQ1/xQ2, upon running EVP_PKEY_keygen I would either get a failure (ret = 0) with no error message in the callback, or I would get stuck infinitely inside the "for" loop in bn_rsa_fips186_4_find_aux_prob_prime ([crypto/bn/bn_rsa_fips186_4.c:103](https://github.com/openssl/openssl/blob/master/crypto/bn/bn_rsa_fips186_4.c#L103)).

Thanks,
Andrew

**Comment by abkarcher** [comment]
Hello,

Is there any updated stance on this? The new alg certs also have B.3.3 listed; it would be nice to have our open source harness be completely consistent with the alg certs.

Thanks,
Andrew

**Comment by paulidale** [comment]
I'd guess we should 1-SUB to correct the certificate.

**Comment by slontis** [comment]
@paulidale 
test/acvp_test.c contains the method rsa_keygen_test() which is the old CAVP test for B 3.6

**Comment by slontis** [comment]
Here is some code that does the keygen that seems to pass..

````
static const unsigned char rsa_keygen0_e[] = {
    0x01,0x00,0x01
};

static const struct rsa_keygen_st rsa_keygen_data[] = {
    {
        2048,
        ITM(rsa_keygen0_e),
    },
    {
        3072,
        ITM(rsa_keygen0_e),
    },
    {
        4096,
        ITM(rsa_keygen0_e),
    },
};

static int rsa_keygen2_test(int id)
{
    int ret = 0;
    EVP_PKEY_CTX *ctx = NULL;
    EVP_PKEY *pkey = NULL;
    BIGNUM *e_bn = NULL;
    unsigned char *n = NULL, *d = NULL;
    unsigned char *p = NULL;
    unsigned char *q = NULL;
    size_t n_len = 0, d_len = 0;
    size_t p_len = 0;
    size_t q_len = 0;
    const struct rsa_keygen_st *tst = &rsa_keygen_data[id];

    if (!TEST_ptr(ctx = EVP_PKEY_CTX_new_from_name(libctx, "RSA", NULL))
        || !TEST_ptr(e_bn = BN_bin2bn(tst->e, tst->e_len, NULL))
        || !TEST_int_gt(EVP_PKEY_keygen_init(ctx), 0)
        || !TEST_int_gt(EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, tst->mod), 0)
        || !TEST_int_gt(EVP_PKEY_CTX_set1_rsa_keygen_pubexp(ctx, e_bn), 0)
        || !TEST_int_gt(EVP_PKEY_keygen(ctx, &pkey), 0)
        || !TEST_true(pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_RSA_FACTOR1,
                                        &p, &p_len))
        || !TEST_true(pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_RSA_FACTOR2,
                                        &q, &q_len))
        || !TEST_true(pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_RSA_N,
                                        &n, &n_len))
        || !TEST_true(pkey_get_bn_bytes(pkey, OSSL_PKEY_PARAM_RSA_D,
                                        &d, &d_len)))
        goto err;

    test_output_memory("p", p, p_len);
    test_output_memory("q", q, q_len);
    test_output_memory("n", n, n_len);
    test_output_memory("d", d, d_len);
    ret = 1;
err:
    BN_free(e_bn);
    OPENSSL_free(p);
    OPENSSL_free(q);
    OPENSSL_free(n);
    OPENSSL_free(d);
    EVP_PKEY_free(pkey);
    EVP_PKEY_CTX_free(ctx);
    return ret;
}
````

**Comment by slontis** [comment]
We are also testing rsa keygen in rsa_sp800_56b_test.c using lower level calls.

**Comment by slontis** [comment]
rsa_sp800_56b_gen.c makes it pretty clear what algorithms are being used.

**Comment by abkarcher** [comment]
If more reference helps at all, here is our harness code for running RSA keygen:
https://github.com/cisco/libacvp/blob/libacvp_2_0_0-throttle/app/app_rsa.c#L31

Our algorithm registration:
https://github.com/cisco/libacvp/blob/libacvp_2_0_0-throttle/app/app_main.c#L2664

Andrew

**Comment by paulidale** [comment]
Thanks for the comments and input.  I've asked our lab to clarify what went wrong.

Not sure when or how this will be addressed at this point but we are still chasing it.

**Comment by slontis** [comment]
Pauli the line that changed the number of iterations that we do was added after 3.0. That change stopped the keygen from failing (but it was a very tiny chance of failure). Maybe that is what they experienced with 3.0, and they just assumed the same for 3.1?

**Comment by paulidale** [comment]
The oldest sample data I've got (Aug 2021) is using B.3.3, so it's unlikely to be a later failure to test.

**Comment by paulidale** [comment]
Just FYI at this point: our lab has submitted the required paperwork for a B.3.6 validation on the CAVP certificate.
I've asked for a link since I cannot easily locate the change.

We have retained the B.3.3 test passes for the moment -- these give us credible continuity.

Thanks for pointing this out to us and helping expedite the resolution process.

**Comment by paulidale** [comment]
The [updated CAVP certificate](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?validation=36158).  Note that RSA has platforms listed twice once for B.3.3 and once for B.3.6.

**Comment by slontis** [comment]
I think the B.3.3 listing should be completely removed. We do not use it in the FIPS module.
