### ISSUE TITLE
TLS negotiation fails if client supported ECDH curves do not match server

### ISSUE THREAD

**Issue by aaronmdjones** [openssl/openssl#18089]
---

When constraining the permitted ECDH curves list on a TLSv1.3-capable server, like so:

```C
SSL_CTX_set1_curves_list(ssl_ctx, "X25519");
```

... and then trying TLS negotiation using a client that does not indicate support for any of those curves:

```sh
$ openssl s_client -curves prime256v1 -connect example.org:1234
```

Negotiation fails with:

```
CONNECTED(00000003)
139676982281536:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1543:SSL alert number 40
```

---

Is this the intended behaviour? I would have expected it to fall back to FFDH and/or TLSv1.2:

```sh
$ openssl s_client -curves prime256v1 -tls1_2 -connect example.org:1234

[...]
Server Temp Key: DH, 3072 bits
SSL handshake has read 4194 bytes and written 660 bytes
Verification: OK
New, TLSv1.2, Cipher is DHE-RSA-CHACHA20-POLY1305
[...]
```

---

Server (Gentoo GNU/Linux, amd64):

```sh
# openssl version -a
OpenSSL 1.1.1n  15 Mar 2022
built on: Sun Apr 10 06:08:57 2022 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: x86_64-pc-linux-gnu-gcc -fPIC -pthread -m64 -Wa,--noexecstack -O2 -pipe -gdwarf-4 -fno-strict-aliasing -Wa,--noexecstack -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG  -DOPENSSL_NO_BUF_FREELISTS
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific

# find / -xdev -name configdata.pm
#
```

Client (Linux Mint 20, amd64):

```sh
# openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Wed Mar  9 12:12:45 2022 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-2iuOVN/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific

# find / -xdev -name configdata.pm
#
```

**Comment by t8m** [comment]
@mattcaswell  What do you think?

**Comment by aaronmdjones** [comment]
> So in the above issue you are not just constraining the EC curves - you are constraining all the groups available for use in TLSv1.3. This includes FFDH groups - so the above configuration prevents either ECDH or FFDH being used in TLSv1.3.

Aha! That's what I was missing. That helps a lot. Thanks.

**Comment by aaronmdjones** [comment]
Okay, this is just weird. @mattcaswell If you could take a look at this I would be very grateful.

In short, I took your advice and switched to `SSL_CTX_set1_groups_list()`:

```C
    SSL_CTX_set1_groups_list(ssl_ctx, "X25519");
```

This behaves as expected given your explanation above:

```sh
$ openssl s_client -groups prime256v1 -connect example.org:1234
[...]
138030105003840:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
```

---

So, I looked into `/usr/include/openssl/obj_mac.h` (the only header file that contains the string `X25519`) for the string values to use for the FFDHE groups.

However, including an FFDHE group then allows the NIST groups to be used too, which seems to defeat the point:

```C
    SSL_CTX_set1_groups_list(ssl_ctx, "X25519:ffdhe3072");
```

```sh
$ openssl s_client -groups prime256v1 -connect example.org:1234
[...]
Server Temp Key: ECDH, P-256, 256 bits
```

Furthermore, s_client does not seem to be able to parse those properly:

```sh
$ openssl s_client -groups ffdhe3072 -connect example.org:1234
Error with command: "-groups ffdhe3072"
```

Is there an alternative name for the groups that will work? I notice that the manpage for `SSL_CTX_set1_groups_list` mentions using the group names "P-521:P-384:P-256" as an example, but I see those strings nowhere in OpenSSL's headers.

If it is the case that I have the incorrect name, perhaps it should be looked into why `SSL_CTX_set1_groups_list` fails open and allows other groups even if it included a valid group name in the list.

**Comment by mattcaswell** [comment]
> SSL_CTX_set1_groups_list(ssl_ctx, "X25519:ffdhe3072");

You should check the return value from this function call. A 0 return means it has failed and so your group list will be ignored. That is what is happening in your case. The `SSL_CTX_set1_groups_list` call fails, and consequently you are still using the default group list which includes support for P-256.

One detail about your original question that I missed was:

````
# openssl version -a
OpenSSL 1.1.1n  15 Mar 2022
````

In fact OpenSSL 1.1.1 does not support *any* FFDHE groups in TLSv1.3. This support was first added in OpenSSL 3.0.

**Comment by aaronmdjones** [comment]
> A 0 return means it has failed and so your group list will be ignored.

I only ask because other list APIs (e.g. `SSL_CTX_set_cipher_list()`) succeed if given *any* valid input, even if it also contained unparseable garbage, but this seems to fail if the list *in its entirety* is not valid, which is the opposite behaviour.

> In fact OpenSSL 1.1.1 does not support any FFDHE groups in TLSv1.3. This support was first added in OpenSSL 3.0.

Understood. Thank you.

**Comment by mattcaswell** [comment]
> I only ask because other list APIs (e.g. SSL_CTX_set_cipher_list()) succeed if given any valid input, even if it also contained unparseable garbage, but this seems to fail if the list in its entirety is not valid, which is the opposite behaviour.

Yes - there are some inconsistencies there. Basically always check the return value to make sure you get a success.
