### ISSUE TITLE
Useless call to SSL_CTX_check_private_key()  in apps\lib\s_cb.c

### ISSUE THREAD

**Issue by ghost** [openssl/openssl#18088]
Hi,

May I assume that, In apps\lib\s_cb.c, the call to `SSL_CTX_check_private_key()` inside `set_cert_key_stuff()` (line 170) is useless because in case of unmatched key, the error will be raised during the previous call of `SSL_CTX_use_PrivateKey()` (line 161) ?
Or am I missing something ?

**Comment by EasySec** [comment]
OK, thanks for confirmation.
