### ISSUE TITLE
Question about difference in behavior of API X509_get_extension_flags in openssl 1.1.1k when compared to 1.1.1b

### ISSUE THREAD

**Issue by mahendra-msp** [openssl/openssl#18097]
Hi All,

We are using X509_get_extension_flags() to check for certificate extensions. This API in openssl 1.1.1b returns EXFLAG_INVALID if certificate has invalid certificate extension.  However, the same API does not return the same error in 1.1.1k

Question is, is there a change in the behavior of the API in 1.1.1k when compared to 1.1.1b? 
Please suggest.

Thanks
Mahendra

**Comment by mahendra-msp** [comment]
To give more info on the extension, 
CRL Distribution Points in certificate had string of huge size and was invalid.

Thanks
Mahendra

**Comment by t8m** [comment]
Could you please provide such certificate?

**Comment by mahendra-msp** [comment]
@t8m Please find attached the certificate. Please rename to .cer as I was not allowed to upload .cer
[certificate.txt](https://github.com/openssl/openssl/files/8485673/certificate.txt)

**Comment by t8m** [comment]
Hmm the URL is huge but I do not see anything that would indicate that it is invalid.

**Comment by mahendra-msp** [comment]
@t8m  If we call X509_get_extension_flags() for this certificate using 1.1.1b, it returns EXFLAG_INVALID. No such error is returned if  we use 1.1.1k.

**Comment by mattcaswell** [comment]
I cannot replicate what you are describing. I wrote a small test program:

```` C
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <stdio.h>

int main(void)
{
    X509 *x = PEM_read_X509(stdin, NULL, NULL, NULL);

    if (x == NULL)
        abort();

    if (X509_get_extension_flags(x) & EXFLAG_INVALID) {
        printf("Cert invalid\n");
    } else {
        printf("Cert valid\n");
    }

    return 0;
}
````

And then ran it with the cert you provided with 1.1.1b:

```` sh
$ ./x509flags <cert.pem
Cert valid
$ openssl version
OpenSSL 1.1.1b  26 Feb 2019
````
Same behaviour with 1.1.1k:

```` sh
$ ./x509flags <cert.pem
Cert valid
$ openssl version
OpenSSL 1.1.1k  25 Mar 2021
````

**Comment by mahendra-msp** [comment]
@t8m Please try this certificate. Rename .txt to .pem
[latest-cert.txt](https://github.com/openssl/openssl/files/8497560/latest-cert.txt)

**Comment by mattcaswell** [comment]
> Please try this certificate. Rename .txt to .pem

Thanks with that certificate I am able to replicate the change in behaviour. The change first appeared in 1.1.1g. It is related to handling of the Basic Constraints extension which looks like this in the certificate you supplied:

````
            X509v3 Basic Constraints: critical
                CA:FALSE, pathlen:0
````
Basically `CA:FALSE, pathlen:0` is counted as invalid prior to 1.1.1g and valid from 1.1.1g onwards.

The change was introduced by PR #11463. The justification was:

>Do not mark such certificates with EXFLAG_INVALID although they
violate the RFC 5280, they are syntactically correct and
openssl itself can produce such certificates without any errors
with command such as:
>
>openssl x509 -req -signkey private.pem -in csr.pem -out cert.pem
-extfile <(echo "basicConstraints=CA:FALSE,pathlen:0")
>
>With the commit https://github.com/openssl/openssl/commit/ba4356ae4002a04e28642da60c551877eea804f7 the
EXFLAG_INVALID causes openssl to not consider such certificate
even as leaf self-signed certificate which is breaking existing
installations.

So the claim is that this PR is fixing behaviour incorrectly introduced a few weeks before in commit ba4356ae4. However my experiments (and your test results) indicate that we always makred "CA:FALSE, pathlen:0" as invalid (at least in 1.1.1 - I haven't tested older versions).

@t8m thoughts?

**Comment by t8m** [comment]
The ba4356a made the EXFLAG_INVALID being much more prominently checked during the certificate verification. Before that commit the certificate verification basically ignored the EXFLAG_INVALID and so such certificate would pass verification if it was signed by a trusted CA. Rather than reverting the ba4356a altogether I've decided to just ignore this particular problem in certificates because such otherwise correct certificates were reported as being in use.

There are much more serious reasons why EXFLAG_INVALID might be set on a certificate which should not be ignored by certificate verification so that was the reason for not reverting ba4356a.
