### ISSUE TITLE
Configure no-async has no effect

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#18107]
"Configure VC-WIN64A no-async" does not exclude the async functions. The generated libcrypto.def file includes them:
```
...
    ASYNC_WAIT_CTX_clear_fd
    ASYNC_WAIT_CTX_free
    ASYNC_WAIT_CTX_get_all_fds
...
```
The exports are listed in libcrypto.num file without any conditions:
```
...
ASYNC_WAIT_CTX_clear_fd                 1824	3_0_0	EXIST::FUNCTION:
...
```

I would expect them to be listed there with a ASYNC suffix:
```
ASYNC_WAIT_CTX_clear_fd                 1824	3_0_0	EXIST::FUNCTION:ASYNC
```

**Comment by mattcaswell** [comment]
This is by design. The "no-async" option works slightly differently to other "no" options. It causes the "null" async implementation to be used rather than the windows async implementation. The async APIs still exist but they will return failure codes when used.

**Comment by matbech** [comment]
Thank you for the explanation.
