### ISSUE TITLE
bug probably BN_is_prime_ex - wrong result for 1486 bit prime

### ISSUE THREAD

**Issue by spital** [openssl/openssl#1810]
Dear all, I am not sure about the following, but it looks like a bug .. please kindly check :

$ openssl prime -checks 5 -hex 200e937df7097e015a87f4481dd4c8ac693998671b54b40646635b32ec99559659800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004c99d9b

...... is not prime

$ openssl version
OpenSSL 1.0.2j-fips  26 Sep 2016

Tried (attached) is_prime_test.c  in openssl-1.1.0b/test (compiled on Fedora 24 x64 through ./config -fPIC && make)

$ gcc is_prime_test.c ../libcrypto.a ../libssl.a -ldl -lpthread

$ ./a.out
ERRR BN_is_prime_ex ..long..(0)
ERRR BN_is_prime_ex ..long..ctx..(0)
===end===

$ gcc --version
gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)

Tested with openssl from git
$ git branch -a
* master
and the result is wrong as well.

Please note it works fine with  openssl-1.0.1u/test

$ gcc is_prime_test.c ../libcrypto.a ../libssl.a -ldl

$ ./a.out
===end===

And with python + gmpy2 fine as well :

x = (0x200e937df7097e015a87f4481dd4c8ac693998671b54b40646635b32ec995596598 << 1220)+0x4c99d9b

In [56]: %time gmpy2.is_prime(gmpy2.mpz(x),5000)
CPU times: user 5.12 s, sys: 0 ns, total: 5.12 s
Wall time: 5.13 s
Out[56]: True

[is_prime_test.c.zip](https://github.com/openssl/openssl/files/562075/is_prime_test.c.zip)

**Comment by kroeckx** [comment]
When I run you openssl prime command, it always returns "is prime" for me, both with 1.0.2j and 1.1.0b

**Comment by kroeckx** [comment]
Your test program also works fine with both 1.0.2j and 1.1.0b

**Comment by spital** [comment]
I can confirm openssl-1.0.2j "prime" function returns proper result on my laptop.

It is strange issue, I suspect the reason may be some fancy new instructions or gcc6.x quirks.

$ ldd openssl-1.1.0b/test/a.out
	linux-vdso.so.1 (0x00007ffd93561000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0cd9b18000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0cd98fc000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0cd9539000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d6af480000)

# just to be sure, reinstalled shared libs
$ dnf reinstall glibc

The result is still wrong.

### CPU with incorrect result
$ grep -E "(flags|name)" /proc/cpuinfo | head -2
model name	: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp

### CPU with a correct result
model name	: Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz
flags	 missing ::: pdpe1gb art sdbg fma movbe abm 3dnowprefetch intel_pt tsc_adjust bmi1 hle avx2 bmi2 invpcid rtm mpx rdseed adx smap clflushopt xsavec xgetbv1 hwp hwp_notify hwp_act_window hwp_epp
flags not present in i5-6600 ::: epb

Skylake bug discovered with Prime95 using AVX instructions may be a connection : https://www.extremetech.com/computing/220953-skylake-bug-causes-intel-chips-to-freeze-in-complex-workloads

**Comment by kroeckx** [comment]
Have you run the test suite? Does it report any other issues?

Note that I'm not seeing any issues with gcc 6 myself.

**Comment by spital** [comment]
$ make test
make depend && make _tests
make[1]: Entering directory '...../openssl-1.1.0b'
...
skipped: md2, rc5, heartbeats - not supported by this OpenSSL build
...
All tests successful.
Files=86, Tests=464, 26 wallclock secs ( 0.26 usr  0.07 sys + 20.69 cusr  5.92 csys = 26.94 CPU)
Result: PASS

**Comment by spital** [comment]
Tested again with latest openssl-1.1.0c
is_prime_test.c does not return ERR on my desktop i5-6600
so this issue can be closed after 1.0.2 is corrected.

**Comment by dot-asm** [comment]
Fix was committed to 1.0.2 as 57c4b9f6a2f800b41ce2836986fe33640f6c3f8a. For reference, it was `adx` thing in /proc/cpuinfo terms. Thanks for report. Closing.
