### ISSUE TITLE
Compiling with Bazel

### ISSUE THREAD

**Issue by JoshuaSBrown** [openssl/openssl#18104]
So I wanted to add this sense I thought it would be useful to the community and I did not see any documentation about it that was up to date.

I was able to get Bazel to build with openssl and have included an example consisting of three files:

my_repo/WORKSPACE.bazel
my_repo/BUILD.bazel
my_repo/src/test_openssl.cpp

```cpp
//my_repo/src/test_openssl.cpp
#include <openssl/ssl.h>
int main() {
    const SSL_METHOD* method = TLSv1_2_client_method();
    return 0;
}
```
```Bazel
//my_repo/BUILD.bazel
load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")

configure_make(
    name = "openssl",
    lib_source = "@openssl//:all_srcs",
    out_shared_libs = ["libssl.so","libcrypto.so"],
    visibility = ["//visibility:public"],
    configure_command = "Configure",
    configure_options = ["-fPIC","-shared"],
    configure_in_place = True,
    out_lib_dir = "lib64",
    args = ["-j 8"],
)

cc_binary(
    name = "openssl_placeholder",
    srcs = ["src/test_openssl.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//:openssl",
    ],
)
```

```Bazel
// my_repo/WORKSPACE.bazel
workspace(
    name = "buildwithOpenSSL"
    )

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

_ALL_CONTENT = """\
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
"""

http_archive(
    name = "openssl",
    build_file_content = _ALL_CONTENT,
    strip_prefix = "openssl-openssl-3.0.2",
    urls = [
        "https://github.com/openssl/openssl/archive/refs/tags/openssl-3.0.2.tar.gz",
    ],
    sha256 = "9f54d42aed56f62889e8384895c968e24d57eae701012776d5f18fb9f2ae48b0",
)

# This is building external projects
http_archive(
    name = "rules_foreign_cc",
    sha256 = "bcd0c5f46a49b85b384906daae41d277b3dc0ff27c7c752cc51e43048a58ec83",
    strip_prefix = "rules_foreign_cc-0.7.1",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/1.11.1.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()

```

**Comment by aaronmondal** [comment]
It would be very nice to have something like this. Bazel support was discussed a couple of years ago in #3840 and as far as I understand the consensus was to add something like what @JoshuaSBrown  posted  to the wiki.

A native overlay would be incredibly useful as well. The `foreign_rules_cc` approach does not really make use of Bazel's full potential.

If there is enough interest in a native overlay I would consider creating one.

**Comment by yzhao1012** [comment]
> 



> It would be very nice to have something like this. Bazel support was discussed a couple of years ago in #3840 and as far as I understand the consensus was to add something like what @JoshuaSBrown posted to the wiki.
> 
> A native overlay would be incredibly useful as well. The `foreign_rules_cc` approach does not really make use of Bazel's full potential.
> 
> If there is enough interest in a native overlay I would consider creating one.

I would much appreciate such an effort!

**Comment by paulocoutinhox** [comment]
Please @aaronmondal

**Comment by carpenterjc** [comment]
A native overlay would be very useful. Or even a generator script which can be applied during WORKSPACE evaluation.
The other problem with `foreign_rules_cc` is it does not make use of the configured users toolchainn, so it is easy to get a mismatching compiler options.
