### ISSUE TITLE
3.0.x RC4-MD5 with TLS not interoperable with 1.1.1 or 1.0.2

### ISSUE THREAD

**Issue by tomcolley-b** [openssl/openssl#18112]
RC4-MD5 with in 3.0.x does not appear to interoperate with prior versions of openssl (e.g. 1.0.2, 1.1.1) when using tls1, 1_1, or 1_2.  It does appear to function correctly with ssl3.

A 1.1.1n (and an old 1.0.2) s_client connecting to a 3.0.2 s_server with ‘-tls1 -cipher RC4-MD5’ results in the server producing the following messages when processing the encrypted handshake message after the ChangeCipherSpec:

4033EA6D4B7F0000:error:1C800066:Provider routines:ossl_cipher_generic_stream_update:cipher operation failed:providers/implementations/ciphers/ciphercommon.c:470:
4033EA6D4B7F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:614:

With the client and server versions reversed--a 3.0.2 client connecting to a 1.1.1n server--will result in the 1.1.1n server indicating 
140466897142912:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:677:

Both 1.1.1n and 3.0.2 were configured with 
```./config enable-weak-ssl-ciphers enable-ssl3 enable-ssl3-method -DOPENSSL_TLS_SECURITY_LEVEL=0 --prefix=<path> --openssldir=<path>```

s_client command with 1.1.1n:
```OPENSSLDIR=. LD_LIBRARY_PATH=./lib ./bin/openssl s_client  -connect localhost:3737 -CAfile ./tc_test/SERVER.crt -tls1 -cipher RC4-MD5```

s_server command with 3.0.2:
```OPENSSLDIR=. LD_LIBRARY_PATH=./lib64 ./bin/openssl s_server -provider legacy -provider default -port 3737 -cert ./tc_test/SERVER.crt  -key ./tc_test/SERVER.key -trace```

3.0.2 s_client to 3.0.2 s_server does function correctly, as does 1.1.1n s_client to 1.1.1n s_server.

**Comment by t-j-h** [comment]
You need to enable the legacy provider for access to legacy algorithms under 3.0.

**Comment by tomcolley-b** [comment]
The legacy provider is loaded -- the s_server command line has ```-provider legacy -provider default```     lsof shows ossl-modules/legacy.so:
 
```openssl 2901572 testuser txt REG 253,0 999752 62950489 /workdir/openssl_install/inst_302/bin/openssl
openssl 2901572 testuser mem REG 253,0 160432 62950487 /workdir/openssl_install/inst_302/lib64/ossl-modules/legacy.so
openssl 2901572 testuser mem REG 253,0 5277960 62950334 /workdir/openssl_install/inst_302/lib64/libcrypto.so.3
openssl 2901572 testuser mem REG 253,0 801688 62950335 /workdir/openssl_install/inst_302/lib64/libssl.so.3
...
```

**Comment by mattcaswell** [comment]
I am investigating.

**Comment by tomcolley-b** [comment]
Appears to have broken with 8fece3355a
