### ISSUE TITLE
Windows OpenSSL 3.0.2: SSL_CTX_use_certificate_chain_file returns error:03000072:digital envelope routines::decode error

### ISSUE THREAD

**Issue by cyberflashguru** [openssl/openssl#18113]
When upgrading from OpenSSL 1.1.0 to 3.0.2 an error is being logged when using [SSL_CTX_use_certificate_chain_file](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_use_certificate_chain_file.html).

For example, here's pseudo code that shows a series of successful calls where 1.1.0h succeeds but 3.0.2 fails.

**OpenSSL 1.1.0h**

method=TLS_method()
ctx=SSL_CTX_new(method)
SSL_CTX_use_certificate_chain_file(ctx,"domain.crt")
---> Returns 1 (success)

**OpenSSL 3.0.2**

fips_libctx=OSSL_LIB_CTX_new()
OSSL_LIB_CTX_load_config(fips_libctx,"C:\Program Files\MyServer\openssl.cnf")
OSSL_PROVIDER_load(NULL,"fips")
method=TLS_method()
ctx=SSL_CTX_new_ex(fips_libctx,NULL,method)
SSL_CTX_use_certificate_chain_file(ctx,"domain.crt")
---> error:03000072:digital envelope routines::decode error
---> error:0A00018F:SSL routines::ee key too small

The domain.crt was constructed using this command:

openssl req -newkey rsa:2048 -nodes -keyout domain.key -x509 -days 365 -out domain.crt

Any ideas why SSL_CTX_use_certificate_chain_file would fail for 3.0.2 but work fine in 1.1.0?

**Comment by mattcaswell** [comment]
You don't show us what is in "C:\Program Files\MyServer\openssl.cnf". I assume it loads and activates the FIPS provider? Do you also load the base provider?

**Comment by cyberflashguru** [comment]
Here's the "C:\Program Files\MyServer\openssl.cnf"

```
config_diagnostics = 1
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect

[fips_sect]
activate = 1
install-version = 1
conditional-errors = 1
security-checks = 1
module-mac = 3A:EC:2E:53:3F:92:44:F9:50:13:70:6E:FD:38:37:08:8B:F2:68:56:CC:B4:ED:5F:A1:52:1B:93:15:37:0B:8C
```

The customers are required to use the FIPS 140-2 so I haven't looked at the base provider at all.

Thanks!

**Comment by mattcaswell** [comment]
> The customers are required to use the FIPS 140-2 so I haven't looked at the base provider at all.

You need to also load the base provider. It is designed to be used in conjunction with the FIPS provider and does not include any cryptographic algorithms (only encoders and decoders). See the fips module guide for a discussion about this:

https://www.openssl.org/docs/man3.0/man7/fips_module.html

The FIPS module does *not* include any decoders itself - which explains the "decode error" that you are seeing.

**Comment by cyberflashguru** [comment]
Works perfectly now!

As you suggested, loading the base provider 

`OSSL_PROVIDER_load(NULL,"base")`

and modifying the openssl.cnf to include the base provider section

```
config_diagnostics = 1
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1

[fips_sect]
activate = 1
install-version = 1
conditional-errors = 1
security-checks = 1
module-mac = 3A:EC:2E:53:3F:92:44:F9:50:13:70:6E:FD:38:37:08:8B:F2:68:56:CC:B4:ED:5F:A1:52:1B:93:15:37:0B:8C
```
