### ISSUE TITLE
DLL loading - FIPS mode

### ISSUE THREAD

**Issue by GenuineRex** [openssl/openssl#1812]
I have a custom FIPS mode openssl DLL and I need openssl.net to open this particular version/build of libeay23.dll and ssleay32.dll.

The problem I am having is that openssl is widely used and whenever a different program with some other version of openssl is loaded then openssl.net uses those dll's already in memory (documented in windows dll search so this is expected).

Any advice on applying a bindingRedirect to a native dll like libeay32.dll in a .net application so that I can load and use my specific version of libeay32.dll?

**Comment by levitte** [comment]
Hi.

We haven't responded to this before now, sorry about that.

I don't think we have any particular advice...  trying to use several different versions of the same DLL is shaky business to say the least.
