### ISSUE TITLE
xml sitemap reference permission 

### ISSUE THREAD

**Issue by AriesTriputran9** [openssl/openssl#18126]
https://github.com/parcel-bundler/website/blob/v2/src/languages/xml.md

**Comment by mspncp** [comment]
Please stop playing around in our repository, or we will have to block you.

You can create your own repositores under your own account to experiment and play without disturbing others,

**Comment by AriesTriputran9** [comment]
Thanks for responding .

AriesTriputranto

Pada tanggal Sen, 18 Apr 2022 06.09, Matthias St. Pierre <
***@***.***> menulis:
