### ISSUE TITLE
MinGW compiler error: [Error] openssl/configuration.h: No such file or directory

### ISSUE THREAD

**Issue by littlekan-gitee** [openssl/openssl#18120]
Here is the error message: 

| Line | Column | Unit | Message |
| ---- | ---- | ---- | ---- |
| 14 | 11 | D:\lksdata\apps\Embarcadero\Dev-Cpp\TDM-GCC-64\x86_64-w64-mingw32\include\openssl\opensslconf.h | [Error] openssl/configuration.h: No such file or directory |

I browsed all headers under OpenSSL and found that "configure.h" turned out to be "configure.h.in"!
So I modified the suffix and made a lot of mistakes!
Ask developers to solve it, thank you!

**Comment by levitte** [comment]
How did you configure?

**Comment by littlekan-gitee** [comment]
![image](https://user-images.githubusercontent.com/75866787/163697811-9572d6a5-6b61-45b0-ba64-cb2525b4db93.png)









![image](https://user-images.githubusercontent.com/75866787/163697837-2f98889a-5833-426a-9d11-59e063d86dc9.png)

**Comment by levitte** [comment]
You misunderstand.

Did you run the script `Configure`? After doing so, did you build using `make`?
Those two steps should produce what you need, including include/openssl/configure.h

**Comment by littlekan-gitee** [comment]
> You misunderstand.
> 
> Did you run the script `Configure`? After doing so, did you build using `make`? Those two steps should produce what you need, including include/openssl/configure.h

Oh, I forgot, thank you!

**Comment by Kachroud** [comment]
I have the same problem but I couldn't fix it , can you help me please ? I did not understand how to configure ? the terminal show me that no file called configuration.h after doing 'make" .

**Comment by ManikandanS8377** [comment]
I am also facing the same issue. Kindly help me to solve the issue

**Comment by MaazArfi** [comment]
> I am also facing the same issue. Kindly help me to solve the issue

To solve this what you need to do is dont include only "openssl" folder where ever you are using include "internal" and "crypto" folders as well.
In my case i was implementing this library in android. so fixed the issue by doing the steps i have mentioned above.
Let me know if it fixed.

**Comment by paulidale** [comment]
> To solve this what you need to do is dont include only "openssl" folder where ever you are using include "internal" and "crypto" folders as well. In my case i was implementing this library in android. so fixed the issue by doing the steps i have mentioned above. Let me know if it fixed.

This is **completely wrong** do **not** do this.  Both _internal_ and _crypto_ contain **internal** header files that cover stuff your application doesn't and shouldn't need to access.  They are also subject to change on any release and are not covered by any API stability.

Seriously, **never** do this.

**Comment by olekrisek** [comment]
I had this problem until I discovered that I had included the "include/openssl" folder from the download instead of the target folder where I produced the library. That last one had configuration.h that was made from the Configure; make steps.
