### ISSUE TITLE
OPENSSL_malloc limit

### ISSUE THREAD

**Issue by lucassdiass** [openssl/openssl#18128]
What's the limit of bytes to allocate with OPENSSL_malloc? 
For example, I encrypt a buffer of 10000 characters using EVP_aes_256_ecb.  Then I try to decrypt it, I have an error malloc(): invalid size (unsorted) of OPENSSL_malloc. For another hand, when I use the same code, changing from EVP_aes_256_ecb to EVP_aes_256_ctr, I encrypt and decrypt the buffer of 10000 characters correctly.

**Comment by t8m** [comment]
The OPENSSL_malloc() has basically the same limits as libc malloc() because that function is being called eventually. You have probably some trivial mistake in your decryption code. Could you paste a relevant part of it here?

**Comment by lucassdiass** [comment]
My problem was in the decryption function. It was not working when the input of the encryption function is a multiple of 16. Now, I fix it, and it's working. I disable the automatic padding. Thanks.
