### ISSUE TITLE
PKCS7_decrypt sometimes failed in openssl 1.1.1l

### ISSUE THREAD

**Issue by oyljerry** [openssl/openssl#18137]
Hi All:  
My app will use **PKCS7_decrypt** to decrypt data from server,  The data can be decrypted successfully, but sometimes, The API will return failed. The error information is as below.  

`PKCS7_decrypt(pPkcs7Data, pPrivateKey, pCert, pDecryptedBIO, 0)`

```
123145554374656:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:610:

``` 

I locate openssl code at here
```
n = ctx->final[b - 1];
if (n == 0 || n > (int)b) {
    EVPerr(EVP_F_EVP_DECRYPTFINAL_EX, EVP_R_BAD_DECRYPT);
    return 0;
}
```
I do not know what this error meaning and how to fix, Is there any comments about it? Thanks.

**Comment by t8m** [comment]
It means either the encrypted data is malformed or truncated or the decryption key is incorrect.

**Comment by oyljerry** [comment]
Is there any information to separate "encrypted data is malformed/truncated" and "decryption key is incorrect."?

**Comment by beldmit** [comment]
`-debug_decrypt` provides some information. Also if you have an idea how the decrypted data should look like, you can see the result and check if it is relevant.

**Comment by oyljerry** [comment]
@beldmit I use PKCS7_decrypt API, Is there any debug parameter to turn on? or use openssl command line can generate more detail information than PKCS7_decrypt API?

**Comment by beldmit** [comment]
Sorry, my fault. It is used by CMS API (CMS_DEBUG_DECRYPT flag).

**Comment by oyljerry** [comment]
I have tested, If use another decryption key to decrypt the data, The error is not same. 
So, Can I say the data is malformed/truncated?  @t8m  , Thanks.

```
4298489344:error:21070073:PKCS7 routines:PKCS7_dataDecode:no recipient matches certificate:crypto/pkcs7/pk7_doit.c:491:
4298489344:error:21072077:PKCS7 routines:PKCS7_decrypt:decrypt error:crypto/pkcs7/pk7_smime.c:500:
```

**Comment by t8m** [comment]
Yes, most probably.

**Comment by oyljerry** [comment]
Finally, We found that the private key is changed when decryption. Thanks.
