### ISSUE TITLE
Bug in OPENSSL_LH_flush implemenation

### ISSUE THREAD

**Issue by levlam** [openssl/openssl#18139]
Function [OPENSSL_LH_flush](https://github.com/openssl/openssl/blob/5adddcd96255112ff04b350d661518302159e7e2/crypto/lhash/lhash.c#L86) is supposed to delete all elements from a hash table. It goes over all allocated nodes and frees them, but it fails to adjust the field `lh->num_items` accordingly. The field is expected to be 0 after the call to the function, but it is kept as is. This forces hash table to think that it is still full and to expand indefinitely, leading to major memory leaks and performance issues.
To fix the issue, `lh->num_items` needs to be assigned to 0 at the end of the function. I would also suggest to contract the hash table after flushing if appropriate.

The function `OPENSSL_LH_flush` is called from [ossl_method_store_add](https://github.com/openssl/openssl/blob/5adddcd96255112ff04b350d661518302159e7e2/crypto/property/property.c#L284) when a TLS certificate is processed via `tls_process_server_certificate`, so this issue should affect all applications, creating outgoing HTTPS connections, dramatically degrading their performance over time.

**Comment by hlandau** [comment]
Fix in #18141.

**Comment by t8m** [comment]
@levlam Could you please contact me by e-mail at tomas@openssl.org?
