### ISSUE TITLE
Problems with OpenSSL 1.1.1j built using latest NDKs on a M1 laptop

### ISSUE THREAD

**Issue by joelbax** [openssl/openssl#18134]
Hello! 

I'm opening this as a question because I'm not totally sure it's a code bug or a framework bug.

I'm facing a very strange issue using latest 1.1.1 version built with NDK 23 (I've also tried with NDK 22 and 24) on a M1 Macbook laptop. The issue is that calling `RSA_generate_key_ex` get blocked. Looking into that in depth it happens that it eventually calls `BN_generate_prime_ex` that checks generated prime with `BN_is_prime_fasttest_ex` and that always returns 0 (actually, `witness` is always returning 1).

The strange part is that this same code is working fine when built with NDK 22 on an old macbook or when built for iOS with the same M1 laptop, so, it should be something related to word's size or endianness but I can't see what or how to fix it.

Thank you in advance.

**Comment by tom-cosgrove-arm** [comment]
A few questions:

- the title says "OpenSSL 1.1.1j" but the text says "latest 1.1.1" - which is currently 1.1.n. Which is it?
- what are you running the NDK-created code on? Is it a device (if so, which?) or an emulator?
- when you build for iOS, what version of Xcode are you using? And how are you running that code?
- how exactly are you building? Command-line (in which case, configure lines please) or what?

> something related to word's size or endianness

I presume you are building for 64-bit iOS. Are you building 32-bit or 64-bit Android? (I'm not up-to-date on Android development)

As far as I'm aware, all Android and iOS devices will be little-endian, so that shouldn't be an issue.

What could be an issue is the source of randomness for key generation, which will depend on exactly how you are running the code (hence the questions above).

**Comment by joelbax** [comment]
Thank you very much for your answer @tom-cosgrove-arm 

Trying to answer your questions:

- My bad, I've tried 1.1.1c and 1.1.1j with the same result. 
- Yeah, I'm running that on several devices: a Pixel 3a, Pixel 4a and Zebra TC52. All of them 64 bits.
- For iOS I'm running it in a iPhone 11 and building with XCode 13.3.1 command line tools.
- I'm building from the command line by using setenv-android.sh to set the environment variables and calling configure like:  `./Configure - shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/Users/joelbax/Dev/tmpLibs64/openssl/ -DOPENSSL_API_COMPAT=0x10002000L`

As I said, these same steps works when building on an old Macbook with NDK 22

**Comment by joelbax** [comment]
@tom-cosgrove-arm  @t8m . Do you have any idea I can try? I'm sorry but I'm not familiar with sources of randomness and I've tracked `BN_priv_rand` down to `crypto/bn/bn_rand.c` and the `bnrand` static function and, as far as I can tell, everything looks OK .

**Comment by joelbax** [comment]
`./configdata.pm --dump` dumps:
`Command line (with current working directory = .):

    perl ./Configure android-arm64 shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/Users/joelcentelles/Dev/bax/pjsip/tmpLibs64/openssl/ -DOPENSSL_API_COMPAT=0x10002000L -D__ANDROID_API__=24

Perl information:

    perl
    5.30.3 for darwin-thread-multi-2level

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    err
    filenames
    gost
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [cascade] OPENSSL_NO_AFALGENG
    asan                    [default] OPENSSL_NO_ASAN
    buildtest-c++           [default] 
    comp                    [option]  OPENSSL_NO_COMP (skip crypto/comp)
    crypto-mdebug           [default] OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default] OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default] OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default] OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default] OPENSSL_NO_EGD
    engine                  [option]  OPENSSL_NO_ENGINE (skip crypto/engine, engines)
    external-tests          [default] OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default] OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default] OPENSSL_NO_FUZZ_AFL
    heartbeats              [default] OPENSSL_NO_HEARTBEATS
    hw                      [option]  OPENSSL_NO_HW
    md2                     [default] OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default] OPENSSL_NO_MSAN
    rc5                     [default] OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default] OPENSSL_NO_SCTP
    ssl-trace               [default] OPENSSL_NO_SSL_TRACE
    ubsan                   [default] OPENSSL_NO_UBSAN
    unit-test               [default] OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default] OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default] 
    zlib-dynamic            [default] 
    ssl3                    [option]  OPENSSL_NO_SSL3
    ssl3-method             [default] OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    CXX => "g++",
    CXXFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c aesv8-armx.S vpaes-armv8.S",
    aes_obj => "aes_core.o aes_cbc.o aesv8-armx.o vpaes-armv8.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bin_cflags => "-pie",
    bn_asm_src => "bn_asm.c armv8-mont.S",
    bn_obj => "bn_asm.o armv8-mont.o",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-pthread  --sysroot=\$(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/darwin-x86_64/sysroot",
    chacha_asm_src => "chacha-armv8.S",
    chacha_obj => "chacha-armv8.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o",
    cppflags => "",
    cpuid_asm_src => "armcap.c arm64cpuid.S",
    cpuid_obj => "armcap.o arm64cpuid.o",
    cxxflags => "-std=c++11 -pthread  --sysroot=\$(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/darwin-x86_64/sysroot",
    defines => [  ],
    des_asm_src => "des_enc.c fcrypt_b.c",
    des_obj => "des_enc.o fcrypt_b.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-armv8.S",
    ec_obj => "ecp_nistz256.o ecp_nistz256-armv8.o",
    enable => [  ],
    ex_libs => "-ldl -pthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600-armv8.S",
    keccak1600_obj => "keccak1600-armv8.o",
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DOPENSSL_USE_NODELETE",
    lib_defines => [  ],
    md5_asm_src => "",
    md5_obj => "",
    modes_asm_src => "ghashv8-armx.S",
    modes_obj => "ghashv8-armx.o",
    module_cflags => "-fPIC",
    module_cxxflags => "",
    module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    padlock_asm_src => "",
    padlock_obj => "",
    perlasm_scheme => "linux64",
    poly1305_asm_src => "poly1305-armv8.S",
    poly1305_obj => "poly1305-armv8.o",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    sha1_asm_src => "sha1-armv8.S sha256-armv8.S sha512-armv8.S",
    sha1_obj => "sha1-armv8.o sha256-armv8.o sha512-armv8.o",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,--version-script=",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-soname=",
    shared_target => "linux-shared",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR = 
    BUILDFILE = 
    CC = aarch64-linux-android24-clang
    CFLAGS = 
    CPPFLAGS = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LDFLAGS = 
    LDLIBS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = llvm-ar
    ARFLAGS         = rs
    CC              = aarch64-linux-android24-clang
    CFLAGS          = -Wall -O3
    CPPDEFINES      = OPENSSL_API_COMPAT=0x10002000L __ANDROID_API__=24
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXX             = g++
    CXXFLAGS        = -Wall -O3
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = perl
    RANLIB          = :
    RC              = windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl`

**Comment by joelbax** [comment]
@t8m Thank you for the reply. 

I've tried those  configuration params and still no luck, `BN_is_prime_fasttest_ex` still thinks that generated random number is not secure. Also, my bad on the initial Configuration call, I missed the architecture there that already was `android-arm64`

I've also tried without `-DOPENSSL_API_COMPAT=0x10002000L` (we added that to prevent possible issues from calling code that is a bit old). So, I've tried with 

> ./Configure android-arm64 shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/Users/joelcentelles/Dev/bax/pjsip/tmpLibs64/openssl/ -DOPENSSL_API_COMPAT=0x10002000L -D__ANDROID_API__=24 '-DDEVRANDOM="/dev/urandom"'
> ./Configure android-arm64 shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/Users/joelcentelles/Dev/bax/pjsip/tmpLibs64/openssl/ -D__ANDROID_API__=24 '-DDEVRANDOM="/dev/urandom"'

and

>./Configure android-arm64 shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/Users/joelcentelles/Dev/bax/pjsip/tmpLibs64/openssl/ -D__ANDROID_API__=24 -DDEVRANDOM="/dev/urandom"

**Comment by bernd-edlinger** [comment]
can you try to add "no-asm" to your configure options?

**Comment by joelbax** [comment]
@bernd-edlinger  I've tried with `no-asm` but the build fails with because there's not definition for `CRYPTO_memcmp`:

> ${LDCMD:-aarch64-linux-android24-clang} -pie -pthread  --sysroot=/Users/joelcentelles/Library/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Wall -O3 -L.   \
		-o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
		 apps/libapps.a -lssl -lcrypto -ldl -pthread 
> ld: error: undefined symbol: CRYPTO_memcmp
> >>> referenced by speed.c
> >>>               apps/speed.o:(speed_main)

I've seen that, in `e_os.h` there's a forward definition of `CRYTO_memcmp` to OS' `memcmp` if `-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined. I've also tried with that but no luck.

**Comment by joelbax** [comment]
@bernd-edlinger @t8m @tom-cosgrove-arm Sorry to bother you but do you have any other suggestions?

**Comment by tom-cosgrove-arm** [comment]
Sorry, I really don't have any ideas at this point (there is a 3.0.2 RSA key generation issue at #18321 but probably unrelated)

**Comment by t8m** [comment]
> I've seen that, in `e_os.h` there's a forward definition of `CRYTO_memcmp` to OS' `memcmp` if `-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined. I've also tried with that but no luck.

Did you do a clean rebuild?

**Comment by joelbax** [comment]
@t8m you're totally right, I messed up with my previous build. I'm really sorry.

I've tried with the `no-asm` option and it works fine (no need to use `DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`).  Thank you very much.

My question is now if I need to open a bug for this scenario? as I've tried again without the `no-asm` (from a clean build this time) and `BN_is_prime_fasttest_ex` keeps failing

**Comment by t8m** [comment]
I can see two possible causes:
 - platform specific bug (maybe a compiler bug or something)  causing the BN_is_prime_fasttest_ex not being able to identify a prime
 - the build not producing valid random numbers at all so the prime test is for example testing always the same numbers which are non-prime. Can you run openssl rand or generate random numbers by RAND_bytes() to see if they are suspiciously non-random?

**Comment by joelbax** [comment]
@t8m Sorry for the delay. I've tried with RAND_bytes() and generated keys seems random enough:

`KEY: b8:F1:34:A0:39:38:6D:6F:A8:28:A7:01:CA:D5:E8:63
KEY: 93:2F:83:5F:94:FC:36:DF:AE:D8:07:02:BF:33:E2:80
KEY: 87:E5:11:C5:46:55:14:EC:35:3C:B5:36:73:A3:95:63
KEY: ef:42:0B:3D:B6:90:BC:06:B5:91:06:60:DD:2F:29:41
KEY: e1:EC:1C:E6:EF:BC:95:89:A5:00:8B:E3:B4:0D:A3:EA
KEY: 42:EB:D1:B9:AF:1E:9C:FE:48:EA:57:4F:23:9D:27:59
KEY: 37:B2:1F:A3:73:F5:67:04:3B:61:65:77:BB:6F:B0:B9
KEY: 43:FA:31:E4:20:49:99:0F:51:49:DD:B0:B4:05:E7:E6`

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
