### ISSUE TITLE
Missing warning when -in is ignored by openssl dhparam command

### ISSUE THREAD

**Issue by maroonbells** [openssl/openssl#18146]
Related to #17539

Feature + bug.

Feature:

Something also useful as a new option while checking safe primes would be the option to check whether the 'g' used produces Order=q or Order=2q. I see that OpenSSL has switched to preferring the former, and it won't generate a safe prime unless it has Order=q based on the -2 -3 or -5 switch used.

However -check doesn't seem to offer the ability to warn the user if the p/g combo has Order=2q.

Bug:

dhparam -check should not be generating safe primes, especially when the -in parameter is used.

While testing to make sure if the above functionality already existed, I found some misleading behavior, which could give the user the false idea that the safe prime in a .pem is valid. Example:

creates safe prime in dhparam.pem:
	openssl dhparam -out dhparam.pem -3

checks safe prime in dhparam.pem and outputs detail to dhparam.txt:
	openssl dhparam -check -in dhparam.pem -out dhparam.txt

adding the -3 switch causes -check to generate a brand new safe prime to the .txt with a message implying that it found that dhparam.pem held a valid safe prime

	openssl dhparam -check -3 -in dhparam.pem -out dhparam.txt

This can be confirmed by comparing the contents of the .pem against that of the .txt, and also by having the .pem contain a different bit length than the default 2048 generated by the final '-check' syntax. If the -in filename does not exist, there is no error generated either.

edit: to clarify this was tested in v3.01

**Comment by kroeckx** [comment]
-3 is no longer a valid option.

**Comment by t8m** [comment]
> -3 is no longer a valid option.

The command accepts it and the dh_builtin_genparams() that's invoked will also work with it. It will generate a safe prime.

**Comment by t8m** [comment]
Basically the -in option will be silently ignored.

**Comment by t8m** [comment]
@faramir-dev If you want to fix this one just add a warning, I do not think changing the functionality or erroring out would be a good idea due to backwards compatibility.

**Comment by maroonbells** [comment]
> -3 is no longer a valid option.
Just confirming that I do see -2 -3 and -5 being treated as valid options. They determine the 2/3/5 value for g that's attached to the generated safe prime so that Order=q. The -2 is default behavior which skips p if p-mod-24=11, and the -5 skips p unless p-mod-60=59
