### ISSUE TITLE
Reproduced crash  confirm when load FIPS module in Linux

### ISSUE THREAD

**Issue by Lei-2024** [openssl/openssl#18148]
Hi Openssl Team

I found a reproduced crash when I integrated Openssl 3.0.2 with FIPS module.
This crash happened in linux only, I try to reproduce in windows, but it can't be reproduced
Reproduce Actions:
1) Library A linked Openssl statically.
2) Execution B load Library A dynamically.
3) In Library A, it will load FIPS module with Openssl Configure file (OSSL_PROVIDER_set_default_search_path&&CONF_modules_load_file_ex).
4) Execution B unload Library A 
5) Crash will happened when unload.
6) It crashed at when FIPS library try to clean up its resource.

Callstack of crash:
![FIPS crash](https://user-images.githubusercontent.com/32726035/164615256-f422027f-4648-461b-97cc-c551a575ccca.png)

My compile flag:
./config no-asm no-shared no-autoload-config enable-fips no-pinshared -D_GNU_SOURCE

How to fix:
After I call OPENSSL_cleanup() explicitly, it didn't crash.
![FIPS crash fix](https://user-images.githubusercontent.com/32726035/164617056-857f690c-a730-4717-afa2-a83feea1480a.png)

My questions:
1) How to release resources in Openssl 3.0 with FIPS module? 
From this issue, it seems that Openssl has release resource of libcrypt and libssl first, and then it will release fips.so.
2) When I used this compile flag "no-pinshared", do I need to call OPENSSL_cleanup() explicitly?
Is there a memory  leak when I didn't call OPENSSL_cleanup() explicitly?
From the crash, openssl still release resource when i didn't call OPENSSL_cleanup() explicitly.

Best regards
forston

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input
