### ISSUE TITLE
Possible wrong behavior regarding used DTLS version in handshake (HelloRequestVerify and subsequent ServerHello)

### ISSUE THREAD

**Issue by maruu** [openssl/openssl#18149]
I am using OpenSSL in my application to write a DTLS 1.2 server. I am using pre-shared keys. I am testing my implementation using the OpenSSL s_client application.

The communication works, I just observed one possible deviation from the spec described in RFC 6347.

In the spec, specifically in section 4.2.1 (https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.1) one can find the following paragraph:

```
"The server_version field has the same syntax as in TLS.  However, in
order to avoid the requirement to do version negotiation in the
initial handshake, DTLS 1.2 server implementations SHOULD use DTLS
version 1.0 regardless of the version of TLS that is expected to be
negotiated.  DTLS 1.2 and 1.0 clients MUST use the version solely to
indicate packet formatting (which is the same in both DTLS 1.2 and
1.0) and not as part of version negotiation.  In particular, DTLS 1.2
clients MUST NOT assume that because the server uses version 1.0 in
the HelloVerifyRequest that the server is not DTLS 1.2 or that it
will eventually negotiate DTLS 1.0 rather than DTLS 1.2."
```

I have also found the code which implements this in the OpenSSL 3.0.0 tag: https://github.com/openssl/openssl/blob/openssl-3.0/ssl/statem/statem_srvr.c#L1277-L1286

The version is hardcoded to 1.0 and the RFC is properly referenced. So far, so good.

What surprises me is a sentence which comes later in the spec:

```
The server MUST use the same
version number in the HelloVerifyRequest that it would use when
sending a ServerHello.  Upon receipt of the ServerHello, the client
MUST verify that the server version values match.
```

How does this fit to the previous paragraph (and also the linked implementation), if the version used in the HelloVerifyRequest and the ServerHello need to match? In my captures I can clearly see that in the HelloVerifyRequest version 1.0 is used (as is specified as recommended behavior in the first linked paragraph from section 4.2.1), but the following ServerHello message then contains the configured version of DTLS 1.2 - so there is a version mismatch between the HelloVerifyRequest and the ServerHello.

Please note that the communication works regardless of that, I was just wondering how the recommended behavior fits together with the other, required section.

Thank you.

**Comment by mattcaswell** [comment]
This looks like an error in the RFC to me and indeed I note that it has previously been reported as an erratum to IETF previously:

https://www.rfc-editor.org/errata/eid4103

Maybe @kaduk might comment.

**Comment by maruu** [comment]
@mattcaswell Thanks for the quick response and clarification. I did not know about errata. Learned something new, great - thanks!

**Comment by kaduk** [comment]
I don't have a whole lot more to add -- the errata report in question is still in state "reported" and hasn't been officially processed, but its conclusions seem essentially sound.  (Its page numbers are off by one, though, as in the RFC format the page number appears at the bottom of the page, not the top of the page.)
For questions of the intent of RFC 6347, we can also consult its Section 8, "Changes since DTLS 1.0", which includes a dedicated item for "Recommend a fixed version number for HelloVerifyRequest."
