### ISSUE TITLE
OSS-Fuzz #46886: Out-of-bounds write in SipHash_Final

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#18140]
Reproducer:

```c
#include <openssl/evp.h>
#include <openssl/core_names.h>

#define CF_CHECK_EQ(expr, res) if ( (expr) != (res) ) { goto end; }

int main(void)
{
    size_t macSize;
    uint8_t* out = NULL;

    EVP_MAC* siphash = NULL;
    EVP_MAC_CTX *ctx = NULL;
    OSSL_PARAM params[3], *p = params;

    /* Initialize */
    {
        macSize = 8;
        siphash = EVP_MAC_fetch(NULL, "SIPHASH", NULL);
        ctx = EVP_MAC_CTX_new(siphash);

        unsigned int macSize_ui = macSize;
        *p++ = OSSL_PARAM_construct_uint(OSSL_MAC_PARAM_SIZE, &macSize_ui);

        *p = OSSL_PARAM_construct_end();

        CF_CHECK_EQ(EVP_MAC_init(ctx, NULL, 0, params), 1);

        out = malloc(macSize);
    }

    /* Finalize */
    CF_CHECK_EQ(EVP_MAC_final(ctx, out, &macSize, macSize), 1);

end:
    free(out);

    EVP_MAC_CTX_free(ctx);
    EVP_MAC_free(siphash);
    return 0;
}
```

Regression range according to OSS-Fuzz: https://github.com/openssl/openssl/compare/e915c3f5381cd38ebdc1824c3ba9896ea7160103...f5f288bdba3d2ca6f2ad4b39225b42f06ef28638

Documentation states:

> If key is NULL, the key must be set via params either as part of this call or separately using EVP_MAC_CTX_set_params().

Here, the key is NULL, but the key size (8) is set in the params. Additionally it is passed to `EVP_MAC_final`. Yet it attempts to write 16 bytes instead of 8, causing the OOB write.

**Comment by t8m** [comment]
Anyway, I suppose the EVP_MAC_init (or rather the provider implementation) should check and fail in this situation.

**Comment by davidben** [comment]
Whether it's properly set up or not, `EVP_MAC_final` seems to be passed an output bound of `macSize`, and is documented to honor that output bound:

> EVP_MAC_final() does the final computation and stores the result in the memory pointed at by out of size outsize, and sets the number of bytes written in *outl at. If out is NULL or outsize is too small, then no computation is made. To figure out what the output length will be and allocate space for it dynamically, simply call with out being NULL and outl pointing at a valid location, then allocate space and make a second call with out pointing at the allocated space.

https://www.openssl.org/docs/man3.0/man3/EVP_MAC_final.html

**Comment by t8m** [comment]
True, however it should actually fail outright because the initialization was not properly completed.
