### ISSUE TITLE
Core fetching synchronisation still has a race condition

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#18152]
[ This is a follow-up on #18150 ]

In the core method construction loop, we're testing and setting so called operation bits to avoid having methods recreated unnecessarily.  Setting and testing these bits themselves is guarded by a lock, but further than that, there is no synchronisation.

In short, what happens is the following:

1.  Check the appropriate operation bit for the methods about the be constructed
2.  If the operation bit was unset, construct methods
3.  Set the operation bit

With multiple threads doing this simultaneously, it should be obvious that several might end up seeing the operation bit cleared, and thereby constructing the same methods concurrently.

An idea to fix this is to have a construction lock, making the process this:

0.  Lock the construction lock
1.  Check the appropriate operation bit for the methods about the be constructed
2.  If the operation bit was unset, construct methods
3.  Set the operation bit
4.  Unlock the construction lock

#18151 refactors `algorithm_do_this()` in a way that may make it easy enough to add this sort of lock.

Ref: https://github.com/openssl/openssl/blob/c29cf39449f78008e39af8f83760f2464815248b/crypto/core_algorithm.c#L45-L78

**Comment by t8m** [comment]
> An idea to fix this is to have a construction lock, making the process this:
> 
>     0. Lock the construction lock
> 
>     1. Check the appropriate operation bit for the methods about the be constructed
> 
>     2. If the operation bit was unset, construct methods
> 
>     3. Set the operation bit
> 
>     4. Unlock the construction lock
> 
> 
> [](https://github.com/openssl/openssl/pull/18151)

This would require having the 0. lock the construction lock as a write lock. That would serialize things too much, wouldn't it?

Better do it as:
 0. Read lock the construction lock
 1. Check the appropriate operation bit for the methods about the be constructed
 2. If the operation bit was unset, unlock the read lock.
 3. Write lock the construction lock
 4. Check again the appropriate operation bit for the methods about the be constructed
 5. If the operation bit was unset, construct methods
 6. Set the operation bit
 7. Unlock the construction lock

**Comment by levitte** [comment]
I suggest looking at the proposed change in #18153 and see how your proposal fits

**Comment by t8m** [comment]
Hmm, right, it does not. However if I understand it properly in situation where the methods were already constructed we will never get to this code so yeah, my concern about the serialization is not really relevant.
