### ISSUE TITLE
Method store and query cache confusion in our code

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#18150]
Deep in the core of libcrypto, we have library context wide method stores for all methods constructed from provided implementation.
Associated with each method store, we also have a query cache, which caches the result from a combined \< algorithm, propquery \> tuple of individual method fetches.

The method stores and their contents are designed to be fairly permanent, i.e. have a lifespan similar to the providers that provide the implementations.  This lifespan is in turn within the lifespan of the library context in which the providers are loaded and the method stores created.
The query cache, on the other hand, can have a shorter lifespan...  it's basically flushed as soon as the correctness of the cache can no longer be guaranteed (for example, when loading another provider, which may give different fetch results for the same fetch input).

It seems, however, that the method store and the query cache have been confused with each other in places.  The result is that in some places, where the intention is clearly to just flush the cache, the corresponding method store is emptied!  (and furthermore, the records of having constructed methods is cleared, for *all* providers in a library context)  Under some circumstances, this leads to methods being reconstructed over and over.

**Comment by levitte** [comment]
PR coming up

**Comment by beldmit** [comment]
Is it just a performance issue or may it cause some races?

**Comment by levitte** [comment]
This in itself doesn't produce races. However, where there are races, they get bigger with this issue.
#18152 talks about the existing race condition
