### ISSUE TITLE
install openssl 3.0 with quic 

### ISSUE THREAD

**Issue by ShawnBian** [openssl/openssl#18162]
Hello,

I just follow this [link ](https://github.com/quictls/openssl/blob/openssl-3.0.2%2Bquic/INSTALL.md#quick-installation-guide)to install OpenSSL 3.0 with quic .it seems that the installation is successful. you can see the below:

install doc/html/man7/provider-kem.html -> /usr/local/share/doc/openssl/html/man7/provider-kem.html
install doc/html/man7/provider-keyexch.html -> /usr/local/share/doc/openssl/html/man7/provider-keyexch.html
install doc/html/man7/provider-keymgmt.html -> /usr/local/share/doc/openssl/html/man7/provider-keymgmt.html
install doc/html/man7/provider-mac.html -> /usr/local/share/doc/openssl/html/man7/provider-mac.html
install doc/html/man7/provider-object.html -> /usr/local/share/doc/openssl/html/man7/provider-object.html
install doc/html/man7/provider-rand.html -> /usr/local/share/doc/openssl/html/man7/provider-rand.html
install doc/html/man7/provider-signature.html -> /usr/local/share/doc/openssl/html/man7/provider-signature.html
install doc/html/man7/provider-storemgmt.html -> /usr/local/share/doc/openssl/html/man7/provider-storemgmt.html
install doc/html/man7/provider.html -> /usr/local/share/doc/openssl/html/man7/provider.html
install doc/html/man7/proxy-certificates.html -> /usr/local/share/doc/openssl/html/man7/proxy-certificates.html
install doc/html/man7/ssl.html -> /usr/local/share/doc/openssl/html/man7/ssl.html
install doc/html/man7/x509.html -> /usr/local/share/doc/openssl/html/man7/x509.html

but when I try to run OpenSSL , it throws the below error output:
root@ubuntu2004:~# which openssl
/usr/local/bin/openssl
root@ubuntu2004:~# openssl
openssl: error while loading shared libraries: libssl.so.81.3: cannot open shared object file: No such file or directory
root@ubuntu2004:~#

How should I resolve this issue?  Looking forward to you reply. thanks

**Comment by yangyangtiantianlonglong** [comment]
You may need to set an environment variable  to specify the path to the linked library.
For example  `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`

**Comment by ShawnBian** [comment]
tbank u for the feedback ,it has been resolved , in my case it should be:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64

**Comment by tmshort** [comment]
Or do an `ldconfig` to refresh the ld caches.

**Comment by FranklinYu** [comment]
Also note that this is OpenSSL repository. You should have reported the issue in QuicTLS repository: https://github.com/quictls/openssl
