### ISSUE TITLE
alma9 openssl 3.0 cannot ssh to some server when use public key

### ISSUE THREAD

**Issue by bighunter513** [openssl/openssl#18166]
I just install the alma9-beta server
ssh-keygen -t rsa  # generate a rsa pair
it can log to another alma8 server

but when I upload the rsa.pub to my company's server (which is a gateway server for security login)
I got the error msg :
ssh_dispatch_run_fatal: Connection to 10.1.x.x port xxxx: error in libcrypto

my local env Alma9-beta with：
openssh-8.7p1-7.el9.src.rpm
openssl-3.0.1-20.el9_0.src.rpm

**Comment by mattcaswell** [comment]
> ssh_dispatch_run_fatal: Connection to 10.1.x.x port xxxx: error in libcrypto

This error message appears to come from openssh. Possibly caused by a libcrypto error but there is insufficient information here for OpenSSL to do anything about it. This probably needs to be reported to OpenSSH first.

**Comment by beldmit** [comment]
If Alma uses Red Hat patches, it may be caused by limiting the usage of SHA1

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
