### ISSUE TITLE
Issue is observed during SSH authentication, where sshd crashes during SBAT validation sequence.

### ISSUE THREAD

**Issue by Jayavishnu** [openssl/openssl#18171]
Hello,

Currently i am facing an sshd crash when unlock SSH, during SBAT Validation

During SSH authentication, we hava an SBAT validation sequence in which the certificate is validated, Public key is stored and then the signature is verified.

During the normal SBAT validation sequence we dont see a crash and it is working properly.

But During SSH authentication there is an sshd crash. 

After debuging we found that during the Public Key generation the RSA key is 0 (pub_key->pkey.rsa ).

Steps we follow
1. we open the .PEM file in read byte
2. we read the PEM file --> PEM_read_X509()
3. we get the public key --> X509_get_pubkey()
4. from public key we take the rsa key --> pub_key->pkey.rsa 
5. Then we assign rsa to --> rsa_key->n
6. Then we return the size of BIGNUM in bytes --> BN_num_bytes
7. Then we convert to bin --> BN_bn2bin
8. Then we store the key in a .txt file for signature validation. 

Following is the actual code

int Get_Public_Key()
{
    int retval = enSUCCESS;
    FILE * sbat_cert_fp = NULL;
    X509 * sbat_cert = NULL;
    EVP_PKEY* pub_key = NULL;
    RSA *rsa_key = NULL;
    BIGNUM *modulus_n = NULL;
    int mod_len = 0;
    unsigned char *pub_key_buf = NULL;

    sbat_cert_fp = fopen(XXX_PEM, "rb");
    if(NULL != sbat_cert_fp) {
        sbat_cert = PEM_read_X509(sbat_cert_fp, NULL, NULL, NULL);

        if(NULL != sbat_cert) {
            pub_key = X509_get_pubkey(sbat_cert);
            if(NULL != pub_key) {
                rsa_key = pub_key->pkey.rsa;

                modulus_n = rsa_key->n;
                mod_len = (size_t) BN_num_bytes(modulus_n);

                pub_key_buf = (unsigned char *)malloc(mod_len + 1);
                if(NULL != pub_key_buf) {
                    retval = BN_bn2bin(modulus_n, (unsigned char *)pub_key_buf);
                    if (retval != mod_len) {
                        retval = CERT_PKEY_ERROR;
                    } else {
                        retval = enSUCCESS;
                        pub_key_buf[mod_len] = '\0';
                        retval = Print_CmdData_Fp(pub_key_buf, SBAT_PUBKEY_SGNTR_LEN);
                    }
                } else {
                    retval = CERT_MEM_ERROR;
                }
            } else {
                retval = CERT_PKEY_ERROR;
            }
        } else {
            retval = CERT_X509_ERROR;
        }

        file_opr_obj->iFileClose(sbat_cert_fp);
    } else {
        retval = ERROR;
    }

    if(NULL != pub_key_buf) {
        free(pub_key_buf);
    }

    return retval;
}

So this normally works during the SBAT validation sequence but during the SSH authentication is crashes.

Please support for this Query.

Thanks in advance.

**Comment by t8m** [comment]
Dereferencing RSA * pointer means you're using 1.0.2 version of OpenSSL. That version is out of support except for premium support customers.

**Comment by Jayavishnu** [comment]
Hello,

In that case if 1.0.2 version of OpenSSL is out of support which version to use?

**Comment by t8m** [comment]
The oldest supported version is 1.1.1. The newest LTS release is 3.0. Of course the changes between 1.0.2 and 3.0 are much bigger but this release will be supported for much longer time than 1.1.1.

**Comment by Jayavishnu** [comment]
Hello,

ok. But here the 1.0.2 version of OpenSSL works perfectly during the SBAT validation sequence alone (The validate certificate, get public key & Validate signature is successful)
And gets crashed during SSH authentication which includes SBAT validation sequence (The validate certificate is success, but get public key crashes as RSA key is 0 (pub_key->pkey.rsa )).

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input
