### ISSUE TITLE
The call to `ossl_init_casecmp` is in the wrong place

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#18172]
This code looks wrong:

https://github.com/openssl/openssl/blob/e5da68183410c06f7b350a0721bc2bd6057e438e/crypto/init.c#L473-L478

This is going through the RUN_ONCE code for the casecmp locale every single time we call `OPENSSL_init_crypto`. The beginning part of `OPENSSL_init_crypto` is supposed to be an optimisation to avoid doing that sort of thing every time. (e.g. see the `optsdone` optimisation).

We should also consider adding an "opt" for it to avoid doing the RUN_ONCE  in every location where `OPENSSL_init_crypto` is called regardless of whether it will end up doing an strcasecmp or not.

In master we should consider whether this would actually be better to be part of the newly refactored libctx init code, so we don't need a RUN_ONCE at all.

**Comment by t8m** [comment]
> We should also consider adding an "opt" for it to avoid doing the RUN_ONCE in every location where `OPENSSL_init_crypto` is called regardless of whether it will end up doing an strcasecmp or not.

That makes little sense to me as you need the OPENSSL_strcasecmp working for almost any real usage of OpenSSL in 3.0 and master.

**Comment by mattcaswell** [comment]
> That makes little sense to me as you need the OPENSSL_strcasecmp working for almost any real usage of OpenSSL in 3.0 and master.

All the more reason to tie it to the creation of the libctx then.

**Comment by beldmit** [comment]
I agree, but the code differs for master and for 3.0 here
