### ISSUE TITLE
error: dereferencing pointer to incomplete type ‘SSL’ {aka ‘struct ssl_st’}

### ISSUE THREAD

**Issue by alokrsinha** [openssl/openssl#18170]
I am migrating some code from openssl1.0.x to openssl1.1.1k.
I am gtting error-
error: dereferencing pointer to incomplete type ‘SSL’ {aka ‘struct ssl_st’}

code-
SSL *s;
if((op == 0 || op == 1) && (NULL != s->s3->rbuf.buf))
    {
        OPENSSL_free(s->s3->rbuf.buf);
        s->s3->rbuf.buf = NULL;
    }

**Comment by dlegaultbbry** [comment]
Everything is now an opaque type: https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes

You need to re-design your code for the API changes.
