### ISSUE TITLE
make install fails when an environment variable named APPS is defined

### ISSUE THREAD

**Issue by sjackman** [openssl/openssl#1818]
I'm still trouble shooting this issue, but that's my current guess. See the Linuxbrew issue at https://github.com/Linuxbrew/homebrew-core/issues/1116#issuecomment-257631354. I'll comment here if I confirm that this issue is resolved by
```sh
unset APPS
make install
```

The error message is
```
make[1]: Entering directory `/tmp/openssl-20161031-14729-wztb8k/openssl-1.0.2j/tools'
cp: omitting directory `/opt/apps'
chmod: cannot access `/home1/04497/kdfred/linuxbrew/.linuxbrew/Cellar/openssl/1.0.2j/bin//opt/apps.new': No such file or directory
mv: cannot stat `/home1/04497/kdfred/linuxbrew/.linuxbrew/Cellar/openssl/1.0.2j/bin//opt/apps.new': No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/tmp/openssl-20161031-14729-wztb8k/openssl-1.0.2j/tools'
make: *** [install_sw] Error 1
```
See https://github.com/Linuxbrew/homebrew-core/files/563108/nohup.txt

**Comment by sjackman** [comment]
The original poster confirmed that `unset APPS` resolves this issue.

**Comment by dot-asm** [comment]
Could you verify https://github.com/openssl/openssl/pull/1864?

**Comment by sjackman** [comment]
I'm afraid that I don't have the time to test this fix myself, but looks good to me. Thanks for the quick fix, Andy.

**Comment by dot-asm** [comment]
When closing I've failed to mention that https://github.com/openssl/openssl/pull/1864 is merged. I mean since @sjackman runs risk of failure to notice that.
