### ISSUE TITLE
openssl 3.0.2 module CMP : private key with BEGIN OPENSSH PRIVATE KEY is not supported

### ISSUE THREAD

**Issue by mickae1** [openssl/openssl#18181]
With Openssl 3.0.2 module CMP, the private key in format 

-----BEGIN OPENSSH PRIVATE KEY-----
-----END OPENSSH PRIVATE KEY-----

is not supported, I got this message:
Could not read private key for CMP client certificate from ......

**Comment by t8m** [comment]
The OPENSSH indicates the key is in the OPENSSH format which is not supported with OpenSSL.
