### ISSUE TITLE
AES128-SHA tls1 still works with openssl3 seclevel=1

### ISSUE THREAD

**Issue by akarl10** [openssl/openssl#18194]
in NEWS.md you say
```
SSL 3, TLS 1.0, TLS 1.1, and DTLS 1.0 only work at security level 0.
```
this news message was added here:
https://github.com/openssl/openssl/commit/aba03ae571ea677fc484daef00a21ca8f7e82708
in result of degrading sha1

by accident I discovered that contrary to my expectations
openssl s_client -connect reallylegacyserver.old -tls1 -cipher DEFAULT:@SECLEVEL=1

works with a server that does not offer pfs. As soon as pfs (ex. ECDHE-RSA-AES256-SHA), it fails and needs seclevel 0. If I understand this correctly this is because the server key exchange signature algorithm is SHA for tls1. But why is in this case AES128-SHA whitelisted without pfs?

**Comment by t8m** [comment]
That's because the RSA key exchange does not use SHA1 signatures. So yeah, the message in NEWS.md is incorrect.

However it is very questionable given the Bleichenbacher attack and so on to enable it in SECLEVELs > 0.

I think we should discuss this within OTC.

**Comment by t8m** [comment]
**Question for OTC: Is it correct that RSA key exchange is enabled on SECLEVEL=1?**

**Comment by t8m** [comment]
OTC: we will fix the NEWS.md and Changes.md in 3.0 branch. We should disallow these versions in SECLEVEL=1 on master.
