### ISSUE TITLE
SSL_CTX_set_security_level to 0

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#18193]
I am having to set security level to 0 if I need cipher suites like **NULL-SHA256** or **ADH-AES256-SHA256** to work in a client server environment.
Is this expected or is there some mismatch in my understanding?
Thanks in advance.

**Comment by mattcaswell** [comment]
> Is this expected or is there some mismatch in my understanding?

Yes, this is expected. They don't provide the minimum 80 bits of security required for level 1 for encryption (NULL-SHA256) or authentication (ADH-AES256-SHA256).

**Comment by amaljesudas** [comment]
Thanks @mattcaswell
