### ISSUE TITLE
Broken link: "bio" documentation

### ISSUE THREAD

**Issue by triska** [openssl/openssl#1819]
When you go to [https://www.openssl.org/](https://www.openssl.org/) and click on "Docs" or any of the other ways to reach the [manpages](https://www.openssl.org/docs/manpages.html), and from there click on any of the shown versions (for example, 1.0.2), and from there click "The ssl library", you see several links that contain **bio** in their&nbsp;URL, for example:

- [https://www.openssl.org/docs/man1.0.2/ssl/SSL_get_rbio.html](https://www.openssl.org/docs/man1.0.2/ssl/SSL_get_rbio.html)
- [https://www.openssl.org/docs/man1.0.2/ssl/SSL_set_bio.html](https://www.openssl.org/docs/man1.0.2/ssl/SSL_set_bio.html)

In the **SEE ALSO** section of these pages, there is a link labeled **bio**, and it leads to:

[https://www.openssl.org/docs/man1.0.2/ssl/bio.html](https://www.openssl.org/docs/man1.0.2/ssl/bio.html)

That page says:

# Page Not Found

**Comment by levitte** [comment]
Known fault.  I'm looking into redoing the documentation layout entirely, to mimic the Unix man1, man3, man5 and man7 layout.  Will happen this week.

**Comment by triska** [comment]
@richsalz: Please reopen this issue, since it is still present.

**Comment by tniessen** [comment]
There are still broken links (e.g. `/ssl/` where it should be `/crypto/`), how do we fix that?

**Comment by levitte** [comment]
This was finally fixed not long ago, see https://github.com/openssl/web/pull/107
