### ISSUE TITLE
locatetest doesn't seem to test properly

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#18205]
Refer:

https://github.com/openssl/openssl/blob/bbe909d00e9a593bd5954dfca4d3020467977565/test/localetest.c#L94-L103

Should the TEST_ptr on line 94 and the TEST_false on line 99 both be wrapped by `if (...) return 0;`?
Without this, the test won't fail but will log output with ERROR in it.  IMO, this is not a good thing.

**Comment by beldmit** [comment]
If we failed on line 94, all other tests don't have much sense and probably we should skip it. You are definitely correct about line 99, if we failed, we should return an error immediately.

**Comment by beldmit** [comment]
`TEST_note` has an intention to show if `strcasecmp` gives an expected result (yes for C, no for Turkish)
