### ISSUE TITLE
Broken link: SSL_CTX_set_tlsext_servername_callback

### ISSUE THREAD

**Issue by triska** [openssl/openssl#1820]
When you go to [https://www.openssl.org/](https://www.openssl.org/) and click on "Docs" or any of the other ways to reach the [manpages](https://www.openssl.org/docs/manpages.html), and from there click on any of the shown versions (for example, 1.0.2), and from there click "The ssl library", you see several links that contain **alpn** in their&nbsp;URL, for example:

- [https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_alpn_protos.html](https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_alpn_protos.html)
- [https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_alpn_select_cb.html](https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_alpn_select_cb.html)

In the **SEE ALSO** section of these pages, there is a link labeled **SSL_CTX_set_tlsext_servername_callback**, and it leads to:

[https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_set_tlsext_servername_callback.html](https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_set_tlsext_servername_callback.html)

That page says:

# Page Not Found

**Comment by richsalz** [comment]
the manpages link to manpages that don't exist :(  this won't be fixed in 1.0.2, and we have a general issue about adding missing documentation open.  Closing this specific issue.
