### ISSUE TITLE
SMTP banner received before STARTTLS is not fully flushed

### ISSUE THREAD

**Issue by bigon** [openssl/openssl#18214]
Hello,

When using `openssl` on a SMTP server with starttls (ie `openssl s_client -connect smtp.example.com:587 -starttls smtp `), the 2nd banner that the server is sending after `STARTTLS` is issued is not displayed completely (only the last line is here)

Version 1.1.1n

**Comment by t8m** [comment]
I think this is a misunderstanding. (And perhaps a different bug.)

What you see as an output is probably the last line of the first banner sent before the STARTTLS command is issued. It is probably not fully flushed out.

You need then to issue the EHLO command yourself (it is not done by s_client) to get the second banner.

**Comment by bigon** [comment]
Oups, you are actually correct.

The problem seems to be that the some replies sent before the STARTTLS command is issued are still be printed after the secure channel is negotiated

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input
