### ISSUE TITLE
SSL Handshake Error With Docker and Selenium trying to access website

### ISSUE THREAD

**Issue by thlorenzen** [openssl/openssl#18217]
I have a python script which is running Chrome with chromedriver and selenium. When I run the script without Docker it works normally and I access the website, if in Docker the Exception gets shown in the Browser with a 502 Gateway Error. My theory is that I need to configure the SSl Settings in the Docker Container, but I dont exactly know what to edit. I already set the  `DEFAULT@SECLEVEL=1/` in the cnf. Trying out different numbers is also not working.

Error shown in Chrome in Docker(Selenium) by trying to access "https://www.ea.com/de-de/fifa/ultimate-team/web-app/":
```
TlsProtocolException('Cannot establish TLS with accounts.ea.com:443 (sni: accounts.ea.com): 
TlsException("SSL handshake error: Error([(\'SSL routines\', \'\', \'unsafe legacy renegotiation disabled\')])")')```
```

**Comment by kaduk** [comment]
If Chrome is producing the diagnostic error, what component is using openssl such that you expect us to be able to help answer the question?  Chrome uses BoringSSL, not OpenSSL.
