### ISSUE TITLE
Elliptic Curve code without ASM is broken with Clang 14

### ISSUE THREAD

**Issue by jpboivin** [openssl/openssl#18225]
Hello,

It looks like on Linux (x86_64), starting with Clang 14, the code for Elliptic Curves (when assembler is not enabled) is broken when compiled with optimizations (O2/O3). It is totally fine when using assembler, but when using regular C code, some curves will fail in OpenSSL internals. It doesn't seem to be new (I tested a few older versions) and it seems to be also affecting the 3.0.x branch although I have personally experienced it on the 1.1.1 branch.

From running the tests, it seems to be only affecting a few curves (like `secp384r1`, `prime192v1`, `prime256v1`) and it seems to be that some validation does not pass, potentially due to bad codegen. I don't know if OpenSSL has some undefined behaviors in that section of the code as I haven't investigated yet. But, it was working well up to Clang 13, and GCC 11 is good too.

I've tested and generated logs for the following configs:
- 1.1.1n | Clang 14 | No ASM (**broken**)
- 1.1.1n | Clang 14 | ASM (working)
- 1.1.1n | GCC 11 | No ASM (working)

All these tests were done in a Docker container based on Ubuntu 22.04. I've also tested `1.1.1k | Clang 14 | No ASM` and `3.0.2 | Clang 14 | No ASM` which reproduce the exact same issue, so didn't generated logs for them.

[config_1_1_1n_noasm_clang14.txt](https://github.com/openssl/openssl/files/8606273/config_1_1_1n_noasm_clang14.txt)
[tests_1_1_1n_noasm_clang14.txt](https://github.com/openssl/openssl/files/8606276/tests_1_1_1n_noasm_clang14.txt)
[tests_verbose_1_1_1n_noasm_clang14.txt](https://github.com/openssl/openssl/files/8606278/tests_verbose_1_1_1n_noasm_clang14.txt)

[config_1_1_1n_asm_clang14.txt](https://github.com/openssl/openssl/files/8606272/config_1_1_1n_asm_clang14.txt)
[tests_1_1_1n_asm_clang14.txt](https://github.com/openssl/openssl/files/8606275/tests_1_1_1n_asm_clang14.txt)

[config_1_1_1n_noasm_gcc.txt](https://github.com/openssl/openssl/files/8606274/config_1_1_1n_noasm_gcc.txt)
[tests_1_1_1n_noasm_gcc.txt](https://github.com/openssl/openssl/files/8606277/tests_1_1_1n_noasm_gcc.txt)

**Comment by paulidale** [comment]
This looks to be a problem with Clang optimising better in version 14.  Compiling with `-fno-strict-aliasing` seems to address the issue.

**Comment by jpboivin** [comment]
Thanks @paulidale for pointing out that it was not an issue when disabling strict aliasing. I've identified `crypto/bn/bn_nist.c` as being the file causing the issues. I'll see if I can identity the actual problematic code and update this ticket with my findings.

**Comment by jpboivin** [comment]
The issue seems to be around the function `nist_cp_bn_0`, which is called by all `BN_nist_mod_XYZ` functions except for `BN_nist_mod_224` (likely why the 224 curve isn't affected). I don't see anything wrong with the `nist_cp_bn_0` function, which is basically a manually written loop to `memcpy` + `memset`. It doesn't seem to violate strict aliasing rules from what I've seen as both the source and destination are `BN_ULONG` arrays. 

I'm more a C++ programmer than a C programmer, so I might have missed something that is specific to C, but it can points you toward which section of the code is problematic. The rest of the `BN_nist_mod_XYZ` functions seem fine and the codegen doesn't seem to change that much except around the `nist_cp_bn_0` call.


I've compared the generated code against when strict aliasing is disabled and it seems that the whole copy is discarded (and additional operations from the same `else` block?). So it might be a compiler bug. I've been able to make it generate seemingly proper assembly by rewriting the copy operation with an explicit call to `memcpy` and `memset` instead of the loop.

[bn_nist_strict_aliasing.txt](https://github.com/openssl/openssl/files/8614294/bn_nist_strict_aliasing.txt)
[bn_nist_no_strict_aliasing.txt](https://github.com/openssl/openssl/files/8614293/bn_nist_no_strict_aliasing.txt)
[bn_nist_strict_aliasing_with_workaround.txt](https://github.com/openssl/openssl/files/8614312/bn_nist_strict_aliasing_with_workaround.txt)


I've dumped the preprocessed source file for easier debugging if it can help you:
[bn_nist_preprocessed.txt](https://github.com/openssl/openssl/files/8614315/bn_nist_preprocessed.txt)

Just need to pass these additional arguments to the compiler to match the OpenSSL buildsystem: `-fPIC -m64 -O3`

**Comment by paulidale** [comment]
Great work.  I agree that function should have no aliasing problems.

I've raised an issue with the LLVM folks.

**Comment by davidben** [comment]
I'm not sure that's right. I think there is a strict aliasing violation. C's strict aliasing and union rules are quite harsh. While there is a carve-out in C (but not C++, which is even stricter) for using unions to do type-punning, that only applies when you read or write directly to a union. Writing through a pointer to an inactive arm is UB.

See example 3 of 6.5.2.3 in [n1256](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf). (Whether these are the right rules is another matter. I doubt there is much C code out there that uses unions which is well-defined w.r.t. all this.)

Likewise, the strict aliasing rules (6.5, clause 7) doesn't include an allowance for unions in the effective type of the object, only the type of the lvalue expression (which doesn't involve a union).

**Comment by paulidale** [comment]
Agreed, example 3 is damning.

**Comment by paulidale** [comment]
This looks like the fundamental issue is if the array in the union is converted to a pointer or accessed directly as an array.  If it is converted, the behaviour is undefined.  The patch accesses the union as an array which solves this.

Interesting is that using memcpy/memset which both convert the array to a pointer, doesn't break the code.

At this point I'm satisfied that the problem is in the OpenSSL code.  I'm a little miffed that there were no warnings about undefined behaviour ever.

**Comment by boris-kolpackov** [comment]
Are there plans to fix this for the 1.1.1 release?

**Comment by mattcaswell** [comment]
> Are there plans to fix this for the 1.1.1 release?

I created a backport or the fix in #18948
