### ISSUE TITLE
*_fetch_by_number defined but not used

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#18227]
These internal functions exist but are never called:
```
ossl_decoder_fetch_by_number
ossl_encoder_fetch_by_number
evp_generic_fetch_by_number
evp_keymgmt_fetch_by_number
ossl_store_loader_fetch_by_number
```

Removing them would clean up the inner fetches a little.

**Comment by levitte** [comment]
... and if we find ourselves needing them at some point, are you willing to re-introduce them?

**Comment by paulidale** [comment]
Yes.  The current implementation is very inefficient since it walks the entire hash table looking for matches.

**Comment by levitte** [comment]
> The current implementation is very inefficient since it walks the entire hash table looking for matches.

It's a good point that the number could be part of the hash key...

**Comment by paulidale** [comment]
I don't think it could easily be, there are times when we know the name but not the number and need to look the number up.  The name2num calls are used (a lot).

A second array to convert the number to a list of names is the way to go but until we actually need it, it's not worth spending the effort (or memory) to implement it.
