### ISSUE TITLE
pem_read_bio_key has additional exceptions in openssl1.1.1 than openssl3

### ISSUE THREAD

**Issue by liuxingbaoyu** [openssl/openssl#18228]
This is an issue at https://github.com/nodejs/node/pull/42793.

In openssl3, exceptions generated by `pem_read_bio_key_decoder` are cleaned up internally.

But in openssl1.1.1 it will be preserved.

Use `ERR_peek_last_error` in nodejs to determine whether `PEM_read_bio_PrivateKey` is successful.

Is this an openssl1.1.1 bug or the wrong way to use it?

openssl3:
https://github.com/openssl/openssl/blob/5cffc49f7213c718ebcc2c1236cdd8c2fae7fb28/crypto/pem/pem_pkey.c#L232-L243

c++ Example:
```cpp
ERR_clear_error();
EVP_PKEY* key = PEM_read_bio_PrivateKey(bio, nullptr, PasswordCallback, passphrase);

unsigned long err = ERR_peek_last_error();
if (err != 0)
  key = NULL;
```
js Example:
```js
const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: {
    type: 'spki',
    format: 'pem'
  },
  privateKeyEncoding: {
    type: 'pkcs8',
    format: 'pem',
    cipher: 'aes-128-ecb',
    passphrase: 'abcdef'
  }
});
```

**Comment by paulidale** [comment]
It's more a limitation in the new world of 3.0 decoders.

**Comment by liuxingbaoyu** [comment]
Thanks for your answer!

What should I do to make openssl1.1.1 behave the same as openssl3? Without modifying the openssl source code.

**Comment by paulidale** [comment]
ERR_set_mark(); ... ERR_pop_to_mark(); might work.  #ifdef would be the alternative.

**Comment by liuxingbaoyu** [comment]
```c++
pkey->reset(PEM_read_bio_PrivateKey(bio.get(),
                                    nullptr,
                                    PasswordCallback,
                                    &passphrase));
// OpenSSL can fail to parse the key but still return a non-null pointer.
unsigned long err = ERR_peek_error();  // NOLINT(runtime/int)
if (err != 0) 
  pkey->reset();
```

The original code of nodejs used `ERR_peek_error` to determine whether `PEM_read_bio_PrivateKey` was successful.

`pem_read_bio_key_decoder` is called inside `PEM_read_bio_PrivateKey` and I can't find a way to just ignore this type of exception.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
