### ISSUE TITLE
CRYPTO_THREAD_write_lock hang on 3.0.1

### ISSUE THREAD

**Issue by mpietras** [openssl/openssl#18222]
We keep running into a hang situation in OpenSSL 3.0.1 which manifests like the following:

`(gdb) bt`
`#0  futex_abstimed_wait (private=<optimized out>, abstime=0x0, clockid=0, expected=3, futex_word=0x55ba31fd573c)
    at ../sysdeps/nptl/futex-internal.h:284`
`#1  __pthread_rwlock_wrlock_full (abstime=0x0, clockid=0, rwlock=0x55ba31fd5730) at pthread_rwlock_common.c:731`
`#2  __GI___pthread_rwlock_wrlock (rwlock=0x55ba31fd5730) at pthread_rwlock_wrlock.c:27`
`#3  0x000055ba306fb179 in CRYPTO_THREAD_write_lock ()`
`#4  0x000055ba3070f2dc in ossl_method_store_cache_set ()`
`#5  0x000055ba306d1216 in inner_evp_generic_fetch.constprop ()`
`#6  0x000055ba306d14a2 in evp_generic_fetch ()`
`#7  0x000055ba306c729a in EVP_MD_fetch ()`
`#8  0x000055ba306c7b18 in evp_md_init_internal ()`
`#9  0x000055ba306ea36d in HMAC_Init_ex ()`

We're seeing the lock itself in this state which is unclear on exactly how to interpret:
`(gdb) p *rwlock`
`$2 = {__data = {__readers = 19, __writers = 0, __wrphase_futex = 3, __writers_futex = 3, __pad3 = 0, __pad4 = 0,
    __cur_writer = 557540, __shared = 0, __rwelision = 0 '\000', __pad1 = "\000\000\000\000\000\000", __pad2 = 0,
    __flags = 0},`

But following that `__cur_writer` thread we find this stack in `OPENSSL_LH_doall_arg`:
`(gdb) bt`
`#0  0x000055ba306eb1b4 in OPENSSL_LH_doall_arg ()`
`#1  0x000055ba3084cee9 in ossl_sa_doall_arg ()`
`#2  0x000055ba3070f451 in ossl_method_store_cache_set ()`
`#3  0x000055ba306d1216 in inner_evp_generic_fetch.constprop ()`
`#4  0x000055ba306d14a2 in evp_generic_fetch ()`
`#5  0x000055ba306cf6ea in EVP_CIPHER_fetch ()`
`#6  0x000055ba306d01b0 in evp_cipher_init_internal ()`
`#7  0x000055ba306d05cb in EVP_CipherInit_ex ()`

As expected, there are other threads awaiting the read lock:
`(gdb) bt`
`#0  futex_abstimed_wait (private=<optimized out>, abstime=0x0, clockid=0, expected=3, futex_word=<optimized out>)
    at ../sysdeps/nptl/futex-internal.h:284`
`#1  __pthread_rwlock_rdlock_full (abstime=0x0, clockid=0, rwlock=0x55ba31fd5730) at pthread_rwlock_common.c:460`
`#2  __GI___pthread_rwlock_rdlock (rwlock=0x55ba31fd5730) at pthread_rwlock_rdlock.c:27`
`#3  0x000055ba306fb159 in CRYPTO_THREAD_read_lock ()`
`#4  0x000055ba3070f1b4 in ossl_method_store_cache_get ()`
`#5  0x000055ba306d10fc in inner_evp_generic_fetch.constprop ()`
`#6  0x000055ba306d14a2 in evp_generic_fetch ()`
`#7  0x000055ba306c729a in EVP_MD_fetch ()`
`#8  0x000055ba306c7b18 in evp_md_init_internal ()`
`#9  0x000055ba306d235c in EVP_BytesToKey ()`

And in this thread also in `EVP_BytesToKey` is awaiting the write lock:
`(gdb) bt`
`#0  futex_abstimed_wait (private=<optimized out>, abstime=0x0, clockid=0, expected=3, futex_word=0x55ba31fd573c) at ../sysdeps/nptl/futex-internal.h:284`
`#1  __pthread_rwlock_wrlock_full (abstime=0x0, clockid=0, rwlock=0x55ba31fd5730) at pthread_rwlock_common.c:731`
`#2  __GI___pthread_rwlock_wrlock (rwlock=0x55ba31fd5730) at pthread_rwlock_wrlock.c:27`
`#3  0x000055ba306fb179 in CRYPTO_THREAD_write_lock ()`
`#4  0x000055ba3070f2dc in ossl_method_store_cache_set ()`
`#5  0x000055ba306d1216 in inner_evp_generic_fetch.constprop ()`
`#6  0x000055ba306d14a2 in evp_generic_fetch ()`
`#7  0x000055ba306c729a in EVP_MD_fetch ()`
`#8  0x000055ba306c7b18 in evp_md_init_internal ()`
`#9  0x000055ba306d235c in EVP_BytesToKey ()`

Other threads awaiting the lock:
`(gdb) bt`
`#0  futex_abstimed_wait (private=<optimized out>, abstime=0x0, clockid=0, expected=3, futex_word=0x55ba31fd573c)
    at ../sysdeps/nptl/futex-internal.h:284`
`#1  __pthread_rwlock_wrlock_full (abstime=0x0, clockid=0, rwlock=0x55ba31fd5730) at pthread_rwlock_common.c:731`
`#2  __GI___pthread_rwlock_wrlock (rwlock=0x55ba31fd5730) at pthread_rwlock_wrlock.c:27`
`#3  0x000055ba306fb179 in CRYPTO_THREAD_write_lock ()`
`#4  0x000055ba3070e9fb in ossl_method_store_add ()`
`#5  0x000055ba306d0ca9 in put_evp_method_in_store ()`
`#6  0x000055ba306ec4c5 in ossl_method_construct_this ()`
`#7  0x000055ba306ec2ee in algorithm_do_this ()`
`#8  0x000055ba306fa497 in ossl_provider_doall_activated ()`
`#9  0x000055ba306ec3d9 in ossl_algorithm_do_all ()`
`#10 0x000055ba306ec6c4 in ossl_method_construct ()`
`#11 0x000055ba306d11b4 in inner_evp_generic_fetch.constprop ()`
`#12 0x000055ba306d14a2 in evp_generic_fetch ()`
`#13 0x000055ba306cf6ea in EVP_CIPHER_fetch ()`
`#14 0x000055ba3062e6ca in ssl_evp_cipher_fetch ()`
`#15 0x000055ba30623c92 in ssl_load_ciphers ()`
`#16 0x000055ba3062fa83 in SSL_CTX_new_ex ()`

`(gdb) bt`
`#0  futex_abstimed_wait (private=<optimized out>, abstime=0x0, clockid=0, expected=3, futex_word=<optimized out>) at ../sysdeps/nptl/futex-internal.h:284`
`#1  __pthread_rwlock_rdlock_full (abstime=0x0, clockid=0, rwlock=0x55ba31fd5730) at pthread_rwlock_common.c:460`
`#2  __GI___pthread_rwlock_rdlock (rwlock=0x55ba31fd5730) at pthread_rwlock_rdlock.c:27`
`#3  0x000055ba306fb159 in CRYPTO_THREAD_read_lock ()`
`#4  0x000055ba3070f1b4 in ossl_method_store_cache_get ()`
`#5  0x000055ba306d10fc in inner_evp_generic_fetch.constprop ()`
`#6  0x000055ba306d14a2 in evp_generic_fetch ()`
`#7  0x000055ba306d8e78 in EVP_KEYMGMT_fetch ()`
`#8  0x000055ba306e36c0 in int_ctx_new ()`
`#9  0x000055ba30636b44 in ssl_setup_sig_algs ()`
`#10 0x000055ba3062fa93 in SSL_CTX_new_ex ()`

We're unclear on what to do to keep this internal locking mechanism from entering this state... any help/guidance is appreciated.

**Comment by t8m** [comment]
Could you please test with the latest code from the openssl-3.0 branch? There were some locking fixes since 3.0.1 and other related changes.

**Comment by mpietras** [comment]
Thanks for the comment - were these locking fixes specific to the 3.0 branch or did they also apply to the 1.1.1 branch?  We switched to the 3.0 branch around the same time we started seeing these issues but cannot definitively pinpoint it.

**Comment by faramir-dev** [comment]
@mpietras Does the issue still exist in the latest openssl-3.0 branch? I tried to simulate the issue with a code that calls functions from backtraces in several threads and I was not able to achieve the lock hang.

**Comment by mpietras** [comment]
We're currently running with 3.0.3 and have not hit this issue since updating so things are looking positive.

**Comment by t8m** [comment]
Let's close this issue then. Please open a new issue if you still encounter something with current release.
