### ISSUE TITLE
DSA cert and key from pfx

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#18246]
I am trying to extract the cert and key from a pfx file but failing.

In my Windows key store I have a DSA certificate that I created and and converted using below commands:
    openssl dsaparam -out dsakey.pem -genkey 1024
    openssl req -x509 -new -key dsakey.pem -out dsacert.pem
    openssl pkcs12 -export -out dsa.p12 -inkey dsakey.pem -in dsacert.pem
I imported the generated p12 file to Windows key store with the Mark key as exportable option set.

Now, I export that certificate using the Windows key store export option, as a pfx file.
I run below openssl command to try and extract the key from the pfx file:
**openssl pkcs12 -in dsa.pfx -nocerts -out key.pem**

But, the command gives the below error once I give the password:
Error outputting keys and certificates
13544:error:0A073068:dsa routines:dsa_priv_decode:decode error:crypto\dsa\dsa_ameth.c:194:
13544:error:0606F091:digital envelope routines:EVP_PKCS82PKEY:private key decode error:crypto\evp\evp_pkey.c:44:

What could possibly be wrong?

Thanks in advance.

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input
