### ISSUE TITLE
What does ossl_property_read|write_lock protect?

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#18245]
I'm trying to wrap my head around how the locking in property.c (starting in 3.0.0) is intended to work.

Although the name refers to "property" the lock is actually a member of the OSSL_METHOD_STORE. So I guess it is meant to protect the other members of said store. For example, I see in ossl_method_store_flush_cache we take ossl_property_write_lock before manipulating various store members. In some cases we may take the lock a frame (or more?) higher. For example, in ossl_method_cache_flush we see manipulation of store members without lock; that's because ossl_property_write_lock is taken by the caller.

What I am trying to understand is why ossl_method_store_do_all does not need to take the lock for its access on the algs member. The callers of this method seem to all exist in other files, so it is not obvious to me that they would already be holding the lock. What is preventing concurrent access to the SPARSE_ARRAY_OF(ALGORITHM) in this case?

**Comment by paulidale** [comment]
This lock is protecting the underlying data structures in the other files in the directory.  The original intention was for all locking to be in property.c, more was added to property_string.c.  The lock is on the store because that's where all this is accessed from.

I'd assume, but haven't checked, that the store lock is used to guard ossl_method_store_do_all().

**Comment by jwalch** [comment]
ossl_method_store_do_all() itself does NOT take the ossl_method_store_st::lock.

The immediate callers logically cannot either, because they are all defined in other files (that live in other directories, eg store/store_meth.c) and the definitions of ossl_method_store_st and the various ossl_property_*lock() wrappers are local to property.c.

Unless the call stack goes through property.c first, it's impossible that ossl_method_store_st::lock is held at the end of ossl_method_store_do_all() when the ossl_method_store_st::algs is accessed. Putting it differently, supposing the lock in question is held, it must be getting taken at minimum two frames up.

So thus my confusion. There is, as far as I can reason, the following set of possibilities, none of which stood out to me as being obviously more likely than the others (as all of them have at least some reason to be doubted):

1. ossl_method_store_st::algs is NOT meant to be among the things protected by ossl_method_store_st::lock.
2. ossl_method_store_do_all() assumes the caller already has the ossl_method_store_st::lock.
3. ossl_method_store_do_all() is incorrect and SHOULD be taking the ossl_method_store_st::lock.

The initial phrasing of my question kind of most assumes (1) to be true. However, the code in ossl_method_store_flush_cache() kind of led me to believe it wasn't. Under the "hold locks as briefly as possible" principal I'd have expected the access to store->algs to happen outside the critical section were it safe to do so.

If (2) is true, I'd have expected some kind of comment(s) indicating as such. Usually this code is pretty good about explicitly indicating "lock contracts" of this sort to avoid future mistakes. As I already noted, this hypothetical "lock contract" would end up really being propagated up at least one function call.

If it's (3), it's unclear why this wouldn't have caused problems or otherwise been detected yet. I know in late alphas some pretty gnarly race conditions got caught by stuff like TSAN. There would have to be some other factor leading to this issue getting masked somehow.

Maybe I'm missing something and there's more possibilities to consider and the truth is among those I've missed.

**Comment by paulidale** [comment]
@levitte, any thoughts here?

The property lock was done very early before the store code was written.  I'll need to think this through.
