### ISSUE TITLE
Fault Attack Countermeasures

### ISSUE THREAD

**Issue by saadislamm** [openssl/openssl#18266]
In ECDSA, do you have any fault attack countermeasures like redundant signing to verify-after-sign?

If not, can you please tell where and how it can be added?

**Comment by mattcaswell** [comment]
> In ECDSA, do you have any fault attack countermeasures like redundant signing to verify-after-sign?

No - we don't

> If not, can you please tell where and how it can be added?

I guess it would go somewhere in this file:

https://github.com/openssl/openssl/blob/master/crypto/ec/ecdsa_ossl.c
