### ISSUE TITLE
Provider query operation not called anymore

### ISSUE THREAD

**Issue by juergenchrist** [openssl/openssl#18262]
Since 20b6d85ab2b9cfa4cd29d2422d69c3e3f4db0a41 our internal provider tests fail.  Debugging revealed that the query operation of our provider is not called anymore.  Instead, any fetch goes to the default provider (loaded first).  This happens for RSA, EC, and DH implementations (our provider does not provide more).

**Comment by juergenchrist** [comment]
Well, that is a little bit complicated.  We load another library in our provider initialization that does a FIPS integrity check on its own and loads the default provider and fetches implicitly for an HMAC with sha256 in the default library context.  So I see two loads of the default provider, one load of our provider, but no queries for functions in our provider.  If I revert the mentioned commit, our provider testcases work again.  They use `EVP_PKEY_CTX_new_from_name` to get a context, initialize key generation and check that the context is associated with the proper provider:
```
    ctx = EVP_PKEY_CTX_new_from_name(NULL, algo, "?provider=ibmca");
    if (ctx == NULL) {
        fprintf(stderr, "EVP_PKEY_CTX_new_from_name failed\n");
        goto out;
    }

    if (EVP_PKEY_keygen_init(ctx) <= 0) {
        fprintf(stderr, "EVP_PKEY_keygen_init failed\n");
        goto out;
    }

    provider = EVP_PKEY_CTX_get0_provider(ctx);
    if (provider == NULL) {
        fprintf(stderr, "Context is not a provider-context\n");
        goto out;
    }

    provname = OSSL_PROVIDER_get0_name(provider);
    if (strcmp(provname, "ibmca") != 0) {
        fprintf(stderr, "Context is not using the IBMCA provider, but '%s'\n",
               provname);
        goto out;
    }
```
Since the mentioned commit we get "default" as provider name.  There were no changes in the last couple of days to our provider, so I consider this a regression in OpenSSL.

**Comment by mattcaswell** [comment]
So in your example code above `algo` is the name of an algorithm that is available in both your provider and the default provider, such as `RSA`, `EC` or `DH`? Correct?

**Comment by juergenchrist** [comment]
Correct, `DH`, `DHX`, `EC`, `RSA`, or `RSA-PSS`.
