### ISSUE TITLE
openssl ecparam -list_curves is provider-agnostic

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#18273]
Code 
https://github.com/openssl/openssl/blob/3b836385679504579ee1052ed4b4ef1d9f49fa13/apps/ecparam.c#L68-L94

relies on (deprecated?) function `EC_get_builtin_curves` which in turn relies on the array with compile-time definitions for FIPS and non-FIPS cases. As we invoke `EC_get_builtin_curves` without providing any extra information, the default list is always used when invoking `openssl ecparam -list_curves`

**Comment by t8m** [comment]
The function EC_get_builtin_curves is NOT deprecated. And yeah, in apps it is invoked from libcrypto and not from fips provider meaning it will list all the curves in libcrypto/default provider.

IMO this is not a bug but a feature. Maybe it should be documented.

**Comment by t8m** [comment]
Also please note the documentation says:

       -list_curves
           If this options is specified ecparam will print out a list of all
           currently implemented EC parameters names and exit.

That kind of implies it is not affected by a provider selected as that does not talk about support in particular configuration but `implemented EC parameters names`.

**Comment by t8m** [comment]
A doc PR making this even more clear would be certainly welcome.

**Comment by junaruga** [comment]
I believe that this issue ticket is about the issue that I faced.

When calling `EC_get_builtin_curves(curves, crv_len)` in both non-FIPS and FIPS cases on OpenSSL latest master cf712830b7b5a20a768a1fc5f78dc48841b7617f (OpenSSl 3.2.0-dev), it seems to me that the value of the `curves` was same between the non-FIPS and FIPS cases.

I prepared the [reproducer (`ec_builtin_curves.c`)](https://github.com/junaruga/report-openssl-ec-builtin-curves/tree/main).

I can see that the `EC_get_builtin_curves` returns the `curve_list` in the `crypto/ec/ec_curve.c` below.

https://github.com/openssl/openssl/blob/a2608e4bc430d6216bbf36f50a29278e8759103a/crypto/ec/ec_curve.c#L3316-L3331

And it seemed that the `curve_list` is declared conditionally in both FIPS (`FIPS_MODULE` is defined) at [crypto/ec/ec_curve.c#L2827](https://github.com/openssl/openssl/blob/a2608e4bc430d6216bbf36f50a29278e8759103a/crypto/ec/ec_curve.c#L2827) and non-FIPS (`FIPS_MODULE` not defined) [crypto/ec/ec_curve.c#L2901](https://github.com/openssl/openssl/blob/a2608e4bc430d6216bbf36f50a29278e8759103a/crypto/ec/ec_curve.c#L2901). But if I debugged this in FIPS case, I find that the macro `FIPS_MODULE` is not defined in FIPS case. I appreciate that refactoring `curve_list` removing the `FIPS_MODULE` conditional case if it is not used any more and/or updating the document for the `EC_get_builtin_curves`.

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input
