### ISSUE TITLE
[Windows] availability of _create_locale() function

### ISSUE THREAD

**Issue by Keitagit-kun** [openssl/openssl#18277]
I was trying to update my curl setup with OpenSSL 3.0.3 lib,  but was prompted of unavailability of _create_locale() function
as it seems _create_locale() function is available from windows 8...
What I can do for OS before - W7 and XP?

**Comment by beldmit** [comment]
Does #18241 fix your issue?

**Comment by t8m** [comment]
BTW this function is not a system function but a function that is from MSVCRT.dll so it is not really depending on the system version but the Visual C runtime environment version installed.

**Comment by Keitagit-kun** [comment]
I tryed configure openssl-3.0.3 with -DOPENSSL_NO_LOCALE, but it not worked - _create_locale() function is found in ctype.c and fipsprov.c and guarded with:
# ifdef OPENSSL_SYS_WINDOWS
    loc = _create_locale(LC_COLLATE, "C");
# else
    loc = newlocale(LC_COLLATE_MASK, "C", (locale_t) 0);
# endif

i cannon find option OPENSSL_NO_LOCALE in sources of openssl-3.0.3 version

also - on my system _create_locale() function is not located in MSVCRT.dll, but in msvcr120.dll library and not getting picked up from there for some reason

**Comment by t8m** [comment]
> i cannon find option OPENSSL_NO_LOCALE in sources of openssl-3.0.3 version

I am sorry I mislead you. You'll also need to apply the fix from https://github.com/openssl/openssl/pull/18241 in addition to using `-DOPENSSL_NO_LOCALE`.

**Comment by Keitagit-kun** [comment]
Thanks! After appling #18241 everything works ok!
