### ISSUE TITLE
Add flag for only sending a certificate request at TLS 1.3 handshake.

### ISSUE THREAD

**Issue by MennoSt** [openssl/openssl#18272]
At the moment I am configuring a tls server with client side certificates in my application where I send a certificate request during the handshake by configuring: 

 ```
SSL_CTX* sslCtx = SSL_CTX_new(TLS_server_method());
SSL_CTX_set_verify(sslCtx, SSL_VERIFY_PEER|SSL_VERIFY_FAIL_IF_NO_PEER_CERT, NULL);
 ```

Now I only want to set this for TLS version 1.3 and not for previous versions of TLS since I don't want to use client side certificates there. I don't see a way to configure this in openssl.  Wouldn't this be a nice feature to add with something like e.g.  a ONLY_VERIFY_PEER_WITH_TLS13 flag?

Let me know how you think about this.

greetings,

Menno

**Comment by kaduk** [comment]
Not quite what you're asking for, but you could use a clienthello callback (https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_client_hello_cb.html) to inspect whether the client offered TLS 1.3 and call `SSL_set_verify(., SSL_VERIFY_PEER|SSL_VERIFY_FAIL_IF_NO_PEER_CERT, NULL)` only in that case.

**Comment by MennoSt** [comment]
Thanks for the suggestion, 

But how would you check the TLS version of the client in the callback function? Regarding the documentation SSL_version() is only reliable after the intitial tls handshake and SSL_client_version() is also not suitable.

https://www.openssl.org/docs/man1.1.1/man3/SSL_version.html
> SSL_version() returns the numeric protocol version used for the connection. They should only be called after the initial handshake has been completed. Prior to that the results returned from these functions may be unreliable.

I tried SSL_version() but that gives indeed the wrong tls version (TLS 13 when the client only supports TLS12).

**Comment by kaduk** [comment]
At the moment you'd have to use `SSL_client_hello_get0_ext()` to retrieve the contents of the "supported_versions" extension and parse it manually to see if the client offered TLS 1.3.  (Retrieving the extension would fail if the client didn't send the extension at all.)  There's been occaisonal talk of adding some helper functions to make this kind of processing more easy (for the SNI value it's pretty tedious at the moment), but that hasn't gotten to the top of anyone's queue yet.

**Comment by MennoSt** [comment]
Thanks, this solutions works for me. I will close the topic since I think there's no need to implement this feature.
