### ISSUE TITLE
FIPS Mode is not getting enabled in Tomcat9 using Openssl 3.0.2 post successful FIPS module installation in windows

### ISSUE THREAD

**Issue by Rupeshkryz** [openssl/openssl#18281]
Good Evening,
I have a issue while enabling the FIPS mode in Tomcat9 for windows where it throws me an error "Failed to enter fips mode". Below are the detail explanation and content. Sorry for the length but I am trying to provide all of the relevant details in hopes that the solution to this issue will be easily identifiable.

I have installed the **openssl version (3.0.2)** along with the FIPS Module installation as per the steps mentioned in the wiki (https://wiki.openssl.org/index.php/OpenSSL_3.0#Installation_and_Compilation_of_OpenSSL_3.0).

The openssl 3.0.2 and fips module got installed successfully.

OpenSSL version:

<img width="569" alt="openssl version" src="https://user-images.githubusercontent.com/51315280/167596526-54e758d5-44bb-41e6-bd68-65f5085bb3b6.PNG">

I am using openssl 3.0.2 to enable the FIPS Mode in only Tomcat9 for windows. As per the steps mentioned in the wiki referenced above, I have executed the steps under the section for **Using the FIPS Module in applications** and have made the changes to the openssl.cnf file. Since i need only Tomcat9 Application to be FIPS enabled i have also followed next step to set the environment variable along with the application name.

<img width="555" alt="openssl cnf" src="https://user-images.githubusercontent.com/51315280/167598088-6c7ab587-f8ab-45b3-805f-45cec6861aed.PNG">

<img width="424" alt="env var" src="https://user-images.githubusercontent.com/51315280/167598775-825540b1-f578-4e59-a01d-535a17729983.PNG">

Post these steps I tried enabling the FIPS mode in tomcat9, For that I have performed:

1. Added the FIPSMode="on"  for the APR listener:
<img width="653" alt="Fipsmode server xml" src="https://user-images.githubusercontent.com/51315280/167599324-73721d1a-7893-4d58-af87-63563d34c075.PNG">

2. Restarted the tomcat server and checked the catalina.log but i get a error which states "failed to enter fips mode".

<img width="764" alt="catilina" src="https://user-images.githubusercontent.com/51315280/167600525-e2f39d1b-6091-493c-8306-99f0fe6935cf.PNG">

Any help here would be greatly appreciated.

Thank you,
Rupesh P

**Comment by mattcaswell** [comment]
Two things:

First, the value you are setting the OPENSSL_CONF environment variable is not correct. It should just be the path to the openssl config file - it should not include the Tomcat9.exe part (probably you are confused by the bash syntax shown on the wiki which sets the OPENSSL_CONF environment variable and runs "myapplication" all on the same line).

Whatever process your application is running in needs to have access to that environment variable.

Second, according to this page:
https://tomcat.apache.org/tomcat-9.0-doc/apr.html

the APR component depends on:
OpenSSL 1.0.2+ development headers (libssl-dev package)

 So it looks like APR is written for OpenSSL 1.0.2 and will therefore use the old FIPS module not the new OpenSSL 3 one. Probably APR will need changes to support the OpenSSL 3 FIPS module.

**Comment by mattcaswell** [comment]
> Please do share your thoughts on to make Probably APR support OpenSSL 3.0 FIPS module for Tomcat 9.

This will almost certainly require some modification of the APR code. Unfortunately I know nothing about APR or Tomcat so I can't provide guidance as to specifically what would need to change.
