### ISSUE TITLE
EVP_EncryptUpdate works only if input data are equal multiple of cipher block size (OpenSsl 3.0)

### ISSUE THREAD

**Issue by Prochy** [openssl/openssl#18292]
Hi, 

I'm facing an issue in OpenSSL 3.0.3 (tested also with 3.0.1) that I'm not able to use EVP_EncryptUpdate if the input data are not multiplied by cipher block size.

I suppose I'm doing something wrong but I couldn't figure out what.  The problem is that I'm getting error result on EVP_EncryptUpdate everytime unless the input data size is cipher block size.

Example code: 
```
int do_crypt()
{
    unsigned char outbuf[1024];
    int outlen, tmplen;
    /*
     * Bogus key and IV: we'd normally set these from
     * another source.
     */
    unsigned char key[] = { 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 };
    unsigned char iv[] = { 1,2,3,4,5,6,7,8 };
    char intext[] = "Some Crypto Tex";
    EVP_CIPHER_CTX* ctx;

    ctx = EVP_CIPHER_CTX_new();
    auto result = EVP_EncryptInit_ex(ctx, EVP_aes_128_cbc_hmac_sha256(), NULL, key, iv);
    if (!EVP_EncryptUpdate(ctx, outbuf, &outlen, (const unsigned char*)intext, strlen(intext))) {
        /* Error */
        EVP_CIPHER_CTX_free(ctx);
        return 0;
    }
    /*
     * Buffer passed to EVP_EncryptFinal() must be after data just
     * encrypted to avoid overwriting it.
     */
    if (!EVP_EncryptFinal_ex(ctx, outbuf + outlen, &tmplen)) {
        /* Error */
        EVP_CIPHER_CTX_free(ctx);
        return 0;
    }
    outlen += tmplen;
    EVP_CIPHER_CTX_free(ctx);

    return 1;
}
```

If I change the "Some Crypto Tex" to "Some Crypto Text" it starts working.  "Some Crypto TextSome Crypto Text" work also. "Some Crypto TextSome Crypto Tex" nope. In OpenSSL 1.1.1 the code above works well.

I didn't notice any comment related to the EVP_EncryptUpdate in a guide how to upgrade OpenSSL to 3.0.

Am I missing something?

**Comment by mattcaswell** [comment]
> EVP_aes_128_cbc_hmac_sha256()

Do not use this cipher!!!

From the man page for this cipher:

> WARNING: this is not intended for usage outside of TLS and requires calling of some undocumented ctrl functions. These ciphers do not conform to the EVP AEAD interface.

https://www.openssl.org/docs/man3.0/man3/EVP_aes_128_cbc_hmac_sha256.html

This is a special cipher only intended for use by libssl, and is specifically designed for use in a TLS context. It works very differently to normal ciphers. It's also not available on all platforms (unlike most OpenSSL ciphers).

**Comment by Prochy** [comment]
🤦  I'm stupid. Then sorry for bothering you. I didn't find this warning. Will changed it accordingly.

**Comment by mattcaswell** [comment]
> facepalm I'm stupid. Then sorry for bothering you. I didn't find this warning. Will changed it accordingly.

It's no bother. Closing this.
