### ISSUE TITLE
[BUG] 82-test_tfo_cli hangs on NonStop x86 at startup on master.

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#18306]
I do not have much to go on, but as of e5f831a065df1d6e4640ef389f8594a5f10c9c8e, `82-test_tfo_cli` test does not start up successfully. Stopping the perl process allows the test to continue. This may be an artifact of a prior test not cleaning up. There are no messages indicating why this is happen when the test is run in verbose. After killing perl, I get:
```
82-test_tfo_cli.t .................. 
# The results of this test will end up in test-runs/test_tfo
1..8
Port: 61027
ok 1
depth=0 CN=server.example
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=server.example
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=server.example
verify return:1
ok 2
ok 3
ok 4
ok 5 # skip TFO not enabled
ok 6 # skip TFO not enabled
ok 7 # skip TFO not enabled
ok 8 # skip TFO not enabled
ok
```

**Comment by rsbeckerca** [comment]
More info available. I have the stack traces. This looks like a I/O deadlock between two openssl processes. I think I have seen these symptoms in other tests where the test was set up making assumptions about port parsing.

Stack trace 1:
```
Procedure call trace:
  AsmBreakDispatchNoRelink + 0x2 (Milli)
  $n_NSK_Event_Wait + 0xCA (Milli)
  Timer_WaitOnEmbeddedTLE_ + 0xDE (SLr)
  PROCESS_WAIT_ + 0x38 (SLr)
  WAIT + 0x36 (SLr)
  FS_REQUEST_WAIT_ + 0x4E (SLr)
  Pxfi_Request_CpuRemote_ + 0x220 (SLr)
  Pxfi_Request_Complete_ + 0x1A2 (SLr)
  Pxfi_Vop_Write_ + 0x35C (SLr)
  Pxvf_Vop_Write_ + 0x94 (SLr)
  PXL2_FILE_WRITE_ + 0x144 (SLr)
  PXFS_FILE_WRITE_COMMON_ + 0x332 (SLr)
  write64_ + 0xE4 (SLr)
  $n_EnterPriv + 0x542 (Milli)
  raw_write_stdout + 0x3A (UCr)
  s_client_main + 0x8FA1 (UCr)
  do_cmd + 0x191 (UCr)
  main + 0x38D (UCr)
  _MAIN + 0x3F (UCr)
```

Stack trace 2:
```
  AsmBreakDispatchNoRelink + 0x2 (Milli)
  $n_NSK_Event_Wait + 0xCA (Milli)
  Timer_WaitOnEmbeddedTLE_ + 0xDE (SLr)
  PROCESS_WAIT_ + 0x38 (SLr)
  WAIT + 0x36 (SLr)
  tsleep_l + 0x359 (DLL zcipdll)
  sosbwait + 0x143 (DLL zcipdll)
  csif_oss_recv64 + 0x11A1 (DLL zcipdll)
  QIOCIP_OSS_FS_RECV_ + 0x1C1 (SLr)
  Pxso_SocketRecv_Net_ + 0x44A (SLr)
  Pxso_Vop_Read_ + 0x10F (SLr)
  Pxsp_Vop_Read_ + 0xA2 (SLr)
  Pxvf_Vop_Read_ + 0x81 (SLr)
  PXL2_FILE_READ_ + 0x136 (SLr)
  PXFS_FILE_READ_COMMON_ + 0x67F (SLr)
  read64_ + 0xDE (SLr)
  $n_EnterPriv + 0x542 (Milli)
  sock_read + 0x72 (DLL libcrypto.so)
  bread_conv + 0x7D (DLL libcrypto.so)
  bio_read_intern + 0x26E (DLL libcrypto.so)
  BIO_read + 0x58 (DLL libcrypto.so)
  ssl3_read_n + 0x70A (DLL libssl.so)
  ssl3_get_record + 0x19C (DLL libssl.so)
  ssl3_read_bytes + 0x4D6 (DLL libssl.so)
  ssl3_shutdown + 0x186 (DLL libssl.so)
  SSL_shutdown + 0x145 (DLL libssl.so)
  ssl_free + 0x79 (DLL libssl.so)
  BIO_free + 0x1DF (DLL libcrypto.so)
  BIO_free_all + 0x65 (DLL libcrypto.so)
  www_body + 0x1845 (UCr)
  do_server + 0x625 (UCr)
  s_server_main + 0x5D46 (UCr)
  do_cmd + 0x191 (UCr)
  main + 0x38D (UCr)
  _MAIN + 0x3F (UCr)
```

**Comment by rsbeckerca** [comment]
Looking at the config data, `tfo` is not enabled by default. This test probably should not be executed. However, even using `enable-tfo` at the configuration stage, this makes no difference in the test, which still hangs in sub-test 2:
```
82-test_tfo_cli.t ..
# The results of this test will end up in test-runs/test_tfo
1..8
Port: 61687
ok 1
depth=0 CN=server.example
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=server.example
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=server.example
verify return:1
```
One of the hung perl processes runs as follows:
```
/home/ituglib/randall/openssl-3.0/apps/openssl s_server -accept :0 -cert ../../apps/server.pem -www -no_tls1_3 -na
```

**Comment by rsbeckerca** [comment]
Still failing at `524bac5707`. Would appreciate some help isolating why this hang is happening.

**Comment by rsbeckerca** [comment]
@mattcaswell Looking for some help tracking down why this test hangs on our platform. I think this may be a repeat of what happened on a different test where the listening server setup is wrong. This breaks our CI for `master` because it hangs forever.

**Comment by mattcaswell** [comment]
The initial implementation of the TFO feature only targets Linux, FreeBSD and MacOS. I imagine it would require some work to get it going on NonStop. It looks to me like a bug that there is no "skip" for that test if TFO is not enabled - and we should simply say that it should not be enabled on NonStop.

The 82-test_tfo_cli.t file should probably just have this line in it next to the other "skip" lines:

````
plan skip_all => "This test requires enable-tfo" if disabled("tfo");
````

@tmshort - don't know if you have any thoughts on this issue.

**Comment by rsbeckerca** [comment]
I have no idea what TFO would require on NonStop. I can do the PR to fix the test.

**Comment by rsbeckerca** [comment]
I am thinking that NonStop TFO support needs to be a separate issue. Submitting a PR for this one imminently.

**Comment by mattcaswell** [comment]
> I am thinking that NonStop TFO support needs to be a separate issue.

Agreed. I suspect that will be non-trivial.

**Comment by rsbeckerca** [comment]
> > I am thinking that NonStop TFO support needs to be a separate issue.
> 
> Agreed. I suspect that will be non-trivial.

I would like to investigate doing it. We can move the discussion to #18352. The PR #18352 is pretty trivial, disabling the test if TFO is not enabled.
