### ISSUE TITLE
How to Disable AVX / AVX2 on Openssl

### ISSUE THREAD

**Issue by quantropi-RYANTOTH** [openssl/openssl#18303]
Hello,

I'm trying to disable AVX/AVX2 instructions inside of Openssl. My machine automatically configures AVX / AVX2, but is there a way I can compile Openssl without AVX / AVX2?

I've researched online and throughout the repo, and found the following command to try but it didn't seem to work after executing it and recompiling.

`env OPENSSL_ia32cap=:0 apps/openssl`

I'm looking for any suggestions that might help me achieve this functionality. Thank you!

Note: I'm using a [fork](https://github.com/open-quantum-safe/openssl) provided by the Open Quantum Safe Project. My version is OpenSSL 1.1.1f  31 Mar 2020

**Comment by t8m** [comment]
One way, albeit a harsh one is to use no-asm and also proper -march when running Configure, if your default -march for gcc is something that uses avx/avx2.

**Comment by machinekoder** [comment]
@quantropi-RYANTOTH Did you find a working solution?
