### ISSUE TITLE
Question regarding SP800-56B key format support

### ISSUE THREAD

**Issue by abkarcher** [openssl/openssl#18300]
Hello!

I have a question regarding the key formats for KAS-IFC-SSC that the OpenSSL FIPS provider cert claims support for. The cert says OpenSSL supports rsakpg1/2-prime-factor keys, which use P/Q values for the private key instead of N. However, I cannot seem to figure out how this would be supported; it looks like using P/Q parameters in EVP_PKEY structures makes the library assume a CRT key is being used. 

Does OpenSSL support rsakpg-prime-factor keys at some internal level? Apologies if I am missing something obvious; I am still trying to wrap my head around this stuff :) 

Thanks for your time!
Andrew

**Comment by t8m** [comment]
I am not sure, but I suppose this just means the support in keygen - i.e. if you generate full crt params you also obtain the prime factors. It is not about being able to support keys generated elsewhere which contain just the factors.

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input
