### ISSUE TITLE
About tls1.3 PSK and NewSessionTicket

### ISSUE THREAD

**Issue by jay900323** [openssl/openssl#18316]
I created a site using the tls1.3 protocol on nginx and enabled the early_data configuration as follows
````
ssl_early_data on;
proxy_set_header Early-Data $ssl_early_data;
````
I execute the following command and capture the package
````
openssl s_client -connect x.x.x.x:8082 -sess_out session.pem
openssl s_client -connect x.x.x.x:8082 -sess_in session.pem -early_data request.txt
````
A total of two requests were made. The first clienthello did not have the PSK extension field, and the second clienthello had the PSK extension and early_data extension, but I did not see the NewSessionPacket package. According to my understanding, the PSK information is in the NewSessionPacket package. , and then send the early_data packet with the PSK extension field next time, but I don't see NewSessionPacket, what is the reason?
![image](https://user-images.githubusercontent.com/5362513/168513145-a3acc827-400b-42ca-a3b8-a792cb726f7a.png)
![image](https://user-images.githubusercontent.com/5362513/168513198-b8a18068-754f-46e5-97fb-f4020bc289d4.png)

**Comment by jay900323** [comment]
Replenish:
first execution
```
openssl s_client -connect x.x.x.x:8082 -sess_out session.pem
```
When the command output looks like this:
![image](https://user-images.githubusercontent.com/5362513/168513857-45d939c6-c9a4-42b4-bebd-f27a95a53178.png)
![image](https://user-images.githubusercontent.com/5362513/168513774-308222fb-fdd5-4f0c-9d5c-675e5dc7ab0b.png)

**Comment by mattcaswell** [comment]
> According to my understanding, the PSK information is in the NewSessionPacket package. , and then send the early_data packet with the PSK extension field next time, but I don't see NewSessionPacket, what is the reason?

I'm not entirely clear what you are asking. The NewSessionTicket message is sent post-handshake and is encrypted. You won't see it in wireshark because of the encryption. All you will see is "Application Data".

**Comment by jay900323** [comment]
Thanks for your answer. There was a problem with my understanding before. I thought that the newsessionticket was not encrypted. I verified that it was indeed encrypted in the applicaiton data. I can see it after decrypting the key log file of the browser.
