### ISSUE TITLE
SHAxxx files do not list the files they refer to internally

### ISSUE THREAD

**Issue by tbrowder** [openssl/openssl#18313]
For your "shaxxx" files for each download archive, each file should include the file name of the source of the shaxxxsum following the check sum. See, for example, "man sha256sum" for the -c (check option).

**Comment by nhorman** [comment]
Marking as inactive, to be closed when 3.4 dev cycle ends, barring further input

**Comment by doczkal** [comment]
Still facing the same issue with openssl-3.3.2.tar.gz.sha256 and openssl-3.2.3.tar.gz.sha256

**Comment by doczkal** [comment]
Note: There is a space at the beginning of the line containing the checksum which github removes.

### How the file looks like:
 52b5f1c6b8022bc5868c308c54fb77705e702d6c6f4594f99a0df216acf46239

### how the file should look like:
52b5f1c6b8022bc5868c308c54fb77705e702d6c6f4594f99a0df216acf46239  openssl-3.2.3.tar.gz
