### ISSUE TITLE
RSA key generation fails sporadically when under high load since OpenSSL 3.0.2

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#18321]
Since running with OpenSSL 3.0.2 we encounter sporadic RSA key generation failures. 
`EVP_PKEY_keygen()` fails but no error is set (`ERR_print_errors_fp()` shows nothing). This seems to be workload dependent, it seems to happen only if key gens a running concurrently (in different processes though).

I have debugged this and it turned out that it fails in `ossl_bn_rsa_fips186_4_derive_prime()` (file `crypto/bn/bn_rsa_fips186_4.c`) at step 8-10, where `i >= imax`. So it just took too many loops to derive the prime....

```
            /* (Step 8-10) */
            if (++i >= imax || !BN_add(Y, Y, r1r2x2))
                goto err;
```

What is an application program supposed to do in such case ? Just retry the key gen? 

Would also be nice if an appropriate error could be set in that case, so that the application has a chance to identify this situation. 

I understand that you don't want run the loop forever, but now the problem is just pushed to the application deciding how often to retry the RSA key gen....

In my case it happens for 2048 or 4096 bit keys, with an given public exponent of 3. I haven't seen it for any other public exponent so far.... Maybe a such small public exponent of 3 makes it more likely to required many iterations?

What is the reason for the too many loops being driven? Could it be that the random pool is depleted, because too many random bytes are read in relatively short time? Would this lead to such situation? Shouldn't the random-read just block until the entropy pool has been filled up instead?

This did not fail on OpenSSL 1.1.1. I can't tell if it also failed with earlier OpenSSL 3.0 releases...

**Comment by t8m** [comment]
The algorithm is taken from the FIPS standard verbatim. Notably the smallest public exponent allowed by FIPS standard is the Fermat number 4 - 65537. The algorithm requires the resulting prime value - 1 having GCD 1 with the public exponent. I suppose this might not work so well with public exponent being 3.

Why are you using 3 as the public exponent? There are some security implications of such small public exponent.

**Comment by t8m** [comment]
One option would be to fall back to the old key generation algorithm when public exponent is < 65537 (in default provider).

**Comment by t8m** [comment]
@slontis any opinions, Shane?

**Comment by neverpanic** [comment]
Note that the current draft for FIPS 186-5 changes the limits for these algorithms, specifically see [NIST FIPS 186-5, appendix B.9, step 9][fips186-5]. I suspect this may be related to Allen Roginsky's comment on FIPS 186-4 (see [Comments received on FIPS 186-4 (Dec. 2015), page 68][comments]), which mentioned a similar problem in Integer Factorization Cryptography Key Pair Generation using the "Generation of Random Primes that are Probably Prime" method (B.3.3 in 186-4, A.1.3 in 186-5 draft).

[fips186-5]: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf
[comments]: https://csrc.nist.gov/CSRC/media/Publications/fips/186/4/final/documents/comments-received-fips186-4-december-2015.pdf

**Comment by ifranzki** [comment]
> Why are you using 3 as the public exponent? 

Its a series of testcases testing various combinations of key sizes and exponents. Even though a public exponent of 3 is probably not the best choice for the real world, I still would like to continue to test it....

**Comment by ifranzki** [comment]
> Note that the current draft for FIPS 186-5 changes the limits for these algorithms

It now loops `20/2 * nbits` instead of `5/2 * nbits` as OpenSSL code does currently.

**Comment by t8m** [comment]
> This seems to be workload dependent, it seems to happen only if key gens a running concurrently (in different processes though).

I think this is a red herring - I would not expect this failure to be workload dependent.

**Comment by slontis** [comment]
The proper check for e using this algorithm is actually
e must be odd AND 2^16 < e < 2^256

For backwards compatibility we dont do this check. This is probably not a good starting point.

Potentially we could go back to using the simpler method in the default provider. This algorithm became quite a bit slower when the number of Miller Rabin rounds got increased.

**Comment by ifranzki** [comment]
>I think this is a red herring - I would not expect this failure to be workload dependent.

Yes, quite possible. I guess its simply more likely to happen the more key gens are performed.

**Comment by t8m** [comment]
> This algorithm became quite a bit slower when the number of Miller Rabin rounds got increased.

Actually it is slower even without that. I've tested that and changing the number of Miller-Rabin rounds even to much lower values did not have a big effect.

**Comment by slontis** [comment]
> 

Yes it is a way more complex algorithm

**Comment by ifranzki** [comment]
Just out of curiosity: 
Assuming that this condition is true: _e must be odd AND 2^16 < e < 2^256_, is it then guaranteed that the algorithm produces a key in any case, or could it still return with an error? 

If there is still the possibility that an error is returned, then the question remains: How is an application supposed to behave when the key gen fails, and how can it detect that its this situation?

 I guess the FIPS provider will keep this algorithm (even if you change the default provider to use  the simpler algorithm), so an application using the FIPS provider may have to be aware of such a situation anyway....

**Comment by ngg** [comment]
We also see sporadical RSA key generation failures in the `EVP_PKEY_generate` function, but we always use `e=65537`.
The probability of the failure is really low (a few times out of hundreds of thousands), we didn't have a chance to debug the cause yet.

**Comment by t8m** [comment]
It is still not guaranteed to generate the prime even with e=65537, just the probability of failure is much lower than with e=3.

That's the reason for the `20/2 * nbits` limit upgrade in FIPS 186-5. With that limit and e=65537 the probability of failure would be sufficiently negligible.

**Comment by paulidale** [comment]
As usual a PR would be welcomed.  I've raised an issue for the OpenSSL contractors to do this, but I've no idea as to the priority at this point.
