### ISSUE TITLE
OpenSSL FIPS 140-2 support

### ISSUE THREAD

**Issue by vikas-yadav77** [openssl/openssl#18329]
Hi,

We want to use FIPS capable OpenSSL(1.0.2) library for our ARM based platform, but we faced issue in Cross compilation of FIPS canister(openssl-fips-2.0.16).
The issue is similar to - https://github.com/openssl/openssl/issues/7498 

So to over come this issue, we have built fipscanister.o on ARM Architecture machine(raspberry-pi) and cross compiled openssl on x86 machine using below steps

Steps to build fipscanister.o on ARM machine(Followed steps from section 4.2.1 of OpenSSL_FIPS_UserGuide-2.0)
tar -xvf ~/openssl-fips-2.0.16.tar.gz
cd ~/openssl-fips-2.0.16
./config
make
make install INSTALLTOP=$PWD/../fips_built_pkg

since we are cross compiling the OpenSSL for ARM target on X86 host, so we have built openssl-fips(openssl-fips-2.0.16) for x86 also and took fips_standalone_sha1 from it and copied it in "fips_built_pkg" directory(created above) and used below steps to build FIPS Capable OpenSSL library
tar -xvf ~/openssl-1.0.2o.tar.gz
 cd ~/ openssl-1.0.2o
 ./config fips shared --with-fipsdir=~/fips_built_pkg/  --openssldir=/usr/lib/ssl/
make depend
make 
make install

Using above steps our OpenSSL library has been built successfully and integrity test passed on it.

**We have some questions around the FIPS 140-2 certification -**
Will the OpsnSSL library created using the above steps be valid as a FIPS enabled OpenSSL library?
Is openssl-fips-2.0.16 module FIPS 140-2 certification will be valid for our product?

**Comment by slontis** [comment]
Please read https://www.openssl.org/docs/fips.html
Click on the link to the certificate which discusses that the cert is on the historical list.

**Comment by vikas-yadav77** [comment]
Thanks Slontis for the quick response!

From the OpenSSL blog (https://www.openssl.org/blog/blog/2021/09/22/OpenSSL3-fips-submission/) we learned that OpenSSL has submitted FOM 3.0 for validation.

Do we have any idea by when NIST will provide FIPS 140-2 certification to FOM 3.0?

If we build OpenSSL 3.0 with FIPS support and take it into our product, does our product need to take a separate FIPS 140-2 certification or will the OpenSSL 3.0 certification be valid for us?

**Comment by mattcaswell** [comment]
> Do we have any idea by when NIST will provide FIPS 140-2 certification to FOM 3.0?

The progress of the certification can be tracked here:

https://csrc.nist.gov/Projects/cryptographic-module-validation-program/modules-in-process/Modules-In-Process-List

See the line "OpenSSL FIPS Provider" with the vendor name "The OpenSSL Project". As of right now we are in the "Coordination" phase which is the penultimate step before "Finalization" - at the end of which our certificate gets issued. The "Finalization" step is typically short. We don't know how long we will be in Coordination for - it depends on the amount and nature of the review comments that the reviewers have.

> If we build OpenSSL 3.0 with FIPS support and take it into our product, does our product need to take a separate FIPS 140-2 certification or will the OpenSSL 3.0 certification be valid for us?

It depends. Our certificate will cover a number of operational environments:

https://www.openssl.org/blog/blog/2021/09/22/OpenSSL3-fips-submission/

If your use of OpenSSL is on one of those operational environments and you abide by the (to-be-published) security policy then  you should be fine. If not you may be able to user/vendor affirm alternative environments without getting a new certificate. Engage a FIPS consultant to look at this - we can't advise you on it.

**Comment by paulidale** [comment]
This is a source validation so it should apply on platforms beyond those listed in the document @mattcaswell linked to.

It would still best to engage a FIPS consultant for meaningful advice.

**Comment by vikas-yadav77** [comment]
Your suggestions are really helpful, we will contact FIPS consultant!

Thanks @paulidale & @mattcaswell
