### ISSUE TITLE
OpenSSL 3.0.3 fails to auto-init rng on Windows 7

### ISSUE THREAD

**Issue by bagder** [openssl/openssl#18322]
curl users on Windows 7 immediately ran into problems with the bump to OpenSSL 3..0.3 as `RAND_status()` now returns false when expected to return true - and it worked fine in 3.0.2.

See further discussions in the curl issue https://github.com/curl/curl/issues/8849

**Comment by vszakats** [comment]
Likely related to: https://github.com/openssl/openssl/pull/18282

**Comment by t8m** [comment]
@bagder Could you please try the current openssl-3.0 branch if this resolves the issue?

**Comment by bagder** [comment]
Unfortunately, I submitted the issue here on others' behalf - I can't reproduce it. @vszakats could you repeat the problem and/or see if it is fixed?

**Comment by vszakats** [comment]
It's a long shot, as I stopped using OpenSSL on Windows (due the long-time unfixed engine/config-loading vulnerabilities) and also miss a Win 7 test env. But, I've kicked off a [CI build](https://ci.appveyor.com/project/curlorg/curl-for-win) with the latest OpenSSL snapshot (and the latest stable curl/libssh2 sources). I'm keeping an eye of the build and once ready, the artifacts can be freely tested on Win 7. 

[ It'd be nice to have built-in tests for this in OpenSSL itself, as engine loading seems just one of the more obvious issues `stricmp_l` may cause, and all this is unrelated to curl. ]

**Comment by vszakats** [comment]
Update: Binaries here: https://ci.appveyor.com/project/curlorg/curl-for-win/builds/43573097/artifacts

**Comment by DanTheMann15** [comment]
> Update: Binaries here: https://ci.appveyor.com/project/curlorg/curl-for-win/builds/43573097/artifacts

The CURL binary here does not work, still getting 35. - Windows 7 SP1

**Comment by Tarnum-tst** [comment]
@vszakats 
Try configuring OpenSSL 3.0.4-dev with -DOPENSSL_NO_LOCALE switch. I could be wrong but Windows 7 locale support could be broken...

**Comment by vszakats** [comment]
If this option is required for 3.0.x to work correctly on previously supported Windows versions, I think this options should be enabled by default. There is a fair chance that not everyone will be aware of this before running into some issues, potentially a silent and/or security-related one.

**Comment by rsbeckerca** [comment]
> @vszakats Try configuring OpenSSL 3.0.4-dev with -DOPENSSL_NO_LOCALE switch. Perhaps Windows 7 locale support could be broken...

I could not even build 3.0.3 on my platform because of locale issues. We are very explicit about specifying the randomizer in OpenSSL.

**Comment by beldmit** [comment]
It shouldn't be switched on by default because modern Windows versions work with locales correctly.

**Comment by vszakats** [comment]
grepping the list of places [1] where `OPENSSL_str[n]casecmp` is used, it's unclear why locale-dependent comparison is used now when comparing with 7-bit ASCII literals? For the remainder of cases, the question is what issues/breakage can be expected with `OPENSSL_NO_LOCALE` enabled? (As committed [here](https://github.com/openssl/openssl/commit/8b97bfcccc4328c65156bff6886db8733df39fde), Turkish locale can indeed break some of these because of the dotless-'i' in the alphabet, regardless of Windows version.)

[1]:
```
$ grep -R -E 'OPENSSL_strn?casecmp'

./asn1/ameth_lib.c:            && OPENSSL_strncasecmp(ameth->pem_str, str, len) == 0)
./asn1/asn1_gen.c:            && (OPENSSL_strncasecmp(tntmp->strnam, tagstr, len) == 0))
./trace.c:        if (OPENSSL_strcasecmp(name, trace_categories[i].name) == 0)
./LPdir_unix.c:        if (OPENSSL_strcasecmp((*ctx)->entry_name,
./ffc/ffc_dh.c:        if (OPENSSL_strcasecmp(dh_named_groups[i].name, name) == 0)
./ctype.c:int OPENSSL_strcasecmp(const char *s1, const char *s2)
./ctype.c:int OPENSSL_strncasecmp(const char *s1, const char *s2, size_t n)
./ctype.c:int OPENSSL_strcasecmp(const char *s1, const char *s2)
./ctype.c:int OPENSSL_strncasecmp(const char *s1, const char *s2, size_t n)
./encode_decode/decoder_lib.c:            && OPENSSL_strcasecmp(data_structure, "type-specific") == 0)
./encode_decode/decoder_lib.c:            && OPENSSL_strcasecmp(ctx->start_input_type, new_input_type) != 0) {
./encode_decode/decoder_lib.c:                || OPENSSL_strcasecmp(data_structure,
./encode_decode/decoder_lib.c:            if (OPENSSL_strcasecmp(new_input_structure,
./encode_decode/encoder_lib.c:                && OPENSSL_strcasecmp(current_output_type,
./encode_decode/encoder_lib.c:            if (OPENSSL_strcasecmp(data->ctx->output_structure,
./property/property_parse.c:    if (OPENSSL_strncasecmp(s, m, m_len) == 0) {
./rsa/rsa_backend.c:        if (OPENSSL_strcasecmp(param_mgf->data,
./ec/ec_lib.c:    if (OPENSSL_strcasecmp(ptmp->data, SN_X9_62_prime_field) == 0) {
./ec/ec_lib.c:    } else if (OPENSSL_strcasecmp(ptmp->data,
./ec/ec_backend.c:        if (OPENSSL_strcasecmp(name, encoding_nameid_map[i].ptr) == 0)
./ec/ec_backend.c:        if (OPENSSL_strcasecmp(name, check_group_type_nameid_map[i].ptr) == 0)
./ec/ec_backend.c:        if (OPENSSL_strcasecmp(name, format_nameid_map[i].ptr) == 0)
./objects/o_names.c:        name_funcs->cmp_func = OPENSSL_strcasecmp;
./objects/o_names.c:            ret = OPENSSL_strcasecmp(a->name, b->name);
./core_namemap.c:    return OPENSSL_strcasecmp(a->name, b->name);
./params_dup.c:    return OPENSSL_strcasecmp(l->key, r->key);
./params_dup.c:        diff = OPENSSL_strcasecmp((*p1cur)->key, (*p2cur)->key);
./x509/v3_tlsf.c:            if (OPENSSL_strcasecmp(extval, tls_feature_tbl[j].name) == 0)
./x509/v3_utl.c:        subject_len >= 4 && OPENSSL_strncasecmp((char *)subject, "xn--", 4) == 0)
./x509/v3_utl.c:                && len - i >= 4 && OPENSSL_strncasecmp((char *)&p[i], "xn--", 4) == 0)
./http/http_client.c:        if (add_host && OPENSSL_strcasecmp("host", hdr->name) == 0)
./http/http_client.c:                    && OPENSSL_strcasecmp(key, "Location") == 0) {
./http/http_client.c:                    && OPENSSL_strcasecmp(key, "Content-Type") == 0) {
./http/http_client.c:                if (OPENSSL_strcasecmp(rctx->expected_ct, value) != 0) {
./http/http_client.c:            if (OPENSSL_strcasecmp(key, "Connection") == 0) {
./http/http_client.c:                if (OPENSSL_strcasecmp(value, "keep-alive") == 0)
./http/http_client.c:                else if (OPENSSL_strcasecmp(value, "close") == 0)
./http/http_client.c:            } else if (OPENSSL_strcasecmp(key, "Content-Length") == 0) {
./evp/ec_support.c:            if (OPENSSL_strcasecmp(curve_list[i].name, name) == 0)
./evp/p_lib.c:        if (OPENSSL_strcasecmp(name, standard_name2type[i].ptr) == 0)
./evp/evp_lib.c:    if (OPENSSL_strcasecmp(type, "RSA") == 0) {
./evp/evp_lib.c:    } else if (OPENSSL_strcasecmp(type, "EC") == 0) {
./evp/evp_lib.c:    } else if (OPENSSL_strcasecmp(type, "ED25519") != 0
./evp/evp_lib.c:               && OPENSSL_strcasecmp(type, "X25519") != 0
./evp/evp_lib.c:               && OPENSSL_strcasecmp(type, "ED448") != 0
./evp/evp_lib.c:               && OPENSSL_strcasecmp(type, "X448") != 0) {
./evp/ctrl_params_translate.c:            if (OPENSSL_strcasecmp(ctx->p2, kdf_type_map->kdf_type_str) == 0) {
./evp/ctrl_params_translate.c:                && OPENSSL_strcasecmp(tmpl->ctrl_str, item->ctrl_str) == 0)
./evp/ctrl_params_translate.c:                     && OPENSSL_strcasecmp(tmpl->ctrl_hexstr,
./evp/ctrl_params_translate.c:                    && OPENSSL_strcasecmp(tmpl->param_key,
./rand/rand_lib.c:        if (OPENSSL_strcasecmp(cval->name, "random") == 0) {
./rand/rand_lib.c:        } else if (OPENSSL_strcasecmp(cval->name, "cipher") == 0) {
./rand/rand_lib.c:        } else if (OPENSSL_strcasecmp(cval->name, "digest") == 0) {
./rand/rand_lib.c:        } else if (OPENSSL_strcasecmp(cval->name, "properties") == 0) {
./rand/rand_lib.c:        } else if (OPENSSL_strcasecmp(cval->name, "seed") == 0) {
./rand/rand_lib.c:        } else if (OPENSSL_strcasecmp(cval->name, "seed_properties") == 0) {
./conf/conf_def.c:    if (OPENSSL_strcasecmp(pval, "on") == 0
./conf/conf_def.c:            || OPENSSL_strcasecmp(pval, "true") == 0) {
./conf/conf_def.c:    } else if (OPENSSL_strcasecmp(pval, "off") == 0
./conf/conf_def.c:            || OPENSSL_strcasecmp(pval, "false") == 0) {
./conf/conf_def.c:             && OPENSSL_strcasecmp(filename + namelen - 5, ".conf") == 0)
./conf/conf_def.c:                 && OPENSSL_strcasecmp(filename + namelen - 4, ".cnf") == 0)) {
./engine/tb_asnmth.c:            && OPENSSL_strncasecmp(ameth->pem_str, str, len) == 0)
./engine/tb_asnmth.c:                && OPENSSL_strncasecmp(ameth->pem_str, lk->str, lk->len) == 0) {
./store/store_result.c:            && (OPENSSL_strcasecmp(data->data_type, PEM_STRING_X509_TRUSTED) == 0))
./store/store_lib.c:        if (OPENSSL_strcasecmp(scheme_copy, "file") != 0) {
```

**Comment by beldmit** [comment]
Even when we compare 7-bit ASCII, we can trigger Turkish "i" effect. 
`OPENSSL_str[n]casecmp` is used consistently to avoid Unix/Windows string comparison functions mismatch.

**Comment by vszakats** [comment]
> Even when we compare 7-bit ASCII, we can trigger Turkish "i" effect.

Sorry for being unclear, that is what I meant.

Could it be a solution to use non-locale-dependent comparisons on both Unix and Windows for 7-bit ASCII strings? This would re-stabilize them, while making them work identically accross all platforms. Majority of comparisons seem to fall into this case (inside crypto and ssl libs at least).

**Comment by t8m** [comment]
@vszakats you misunderstand the problem, there is no such thing as non-locale-dependent comparisons for 7-bit ASCII strings. In the turkish locale the ASCII `i` will not match ASCII `I` in case insensitive comparison.

**Comment by beldmit** [comment]
Sorry, I don't get. The current solution was implemented to ensure locale-independent comparison where locale concept is implemented.

To avoid the locale stuff, we could switch to uppercase strings only and use `strcmp` instead of `strcasecmp` but it will break everything.

**Comment by bagder** [comment]
I'm so puzzled. Is there actually *ever* a need for locale-aware string comparisons in a TLS library?

**Comment by t8m** [comment]
@bagder please read my comment above about the case insensitive comparisons in Turkish locale.

**Comment by t8m** [comment]
Could you please test an OpenSSL build with the #18337 in place on Windows 7 to see if that helps?

**Comment by bagder** [comment]
That would highlight the need for something that **is not** locale aware, like I said.  Compare strings ignoring locale: don't use strcasecmp().

**Comment by bagder** [comment]
Like we do in curl since 2008: https://daniel.haxx.se/blog/2008/10/15/strcasecmp-in-turkish/

**Comment by icing** [comment]
Like Apache does since forever. HTTP header field names are not case sensitive. But the equality of different writings MUST NOT depend on any locale set on the client or server side.

Could you name an example where a crypto parameter name equality has need for locale specific equality checks? Would this not rather be a security issue if a server admin changes a locale and an EC parameter is not longer applied?

**Comment by paulidale** [comment]
I'll try to write a replacement tomorrow.

@icing, the direct concern is the Turkish locale where `strcasecmp("i", "I") != 0`

Could this be turned into a security issue?  Probably.....

**Comment by icing** [comment]
The Turkish locale is one (in-)famous example. I doubt that anyone of us has a complete understanding of all locale rules out there in the world. 

Also, those rules may be subject to change over time, just like timezones. For an example of that, you can read on the evolution of [the uppercase form of the German ß](https://en.wikipedia.org/wiki/ß).

**Comment by paulidale** [comment]
@icing exactly.  We don't know all of the problems.  This one has been raised as a specific issue which we want to address.

**Comment by vszakats** [comment]
@t8m: 7-bit ASCII is a-z and A-Z. There is definitely a locale-agnostic way to compare those case-insenstitvely.

**Comment by beldmit** [comment]
@vszakats yes, char-by-char and veeery slow

**Comment by vszakats** [comment]
@beldmit If speed is of any concern here, being locale-aware will only make it worse. By the list of places this is used, probably security (stability and consistency) is more of a concern here, than speed.

**Comment by vszakats** [comment]
Possibly related: https://github.com/openssl/openssl/issues/18339

**Comment by levicki** [comment]
> No, that is almost surely not related.

I agree, it should be unlinked.
