### ISSUE TITLE
Deprecate long

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#18338]
I think we should deprecate use of `long` and `unsigned long` in the OpenSSL codebase.

`long` is used a lot in the codebase in contexts where `size_t` or `ossl_ssize_t` would be more appropriate, for example to specify buffer lengths. There seems to be an assumption that `unsigned long` is the same as `size_t` but this is not the case on 64-bit Windows, where `long` is still 32-bit. We probably have a lot of subtle bugs on Windows because of this.

In general, I can't think of any circumstance where using long is a good idea.

**Comment by t8m** [comment]
The problem is with existing public APIs using long/unsigned long. What will we do with them?

**Comment by hlandau** [comment]
There's nothing we can do, they'll have to remain as is. Basically this would just be an update to the coding style policy that says that use of long is deprecated; thus any new APIs or code should not use long. Internal usage of long could be gradually converted at our convenience, but no rush.

**Comment by hlandau** [comment]
It's possible we could define a `typedef long OSSL_LONG`, move all public APIs using long to that, and allow Windows builds to be specially built (opt-in) so that it's defined as `long long` instead. This is not necessarily as big a deal as it seems since I imagine basically anyone using OpenSSL on Windows is building and distributing it themselves.

But that's a more radical suggestion and independent of this.

**Comment by levitte** [comment]
Don't we have uses of `long` that isn't a size or an index?  I know that we have a huge amount of uses where this is the case, but all?

For example, the BN code uses variants of `long` (such as `long long`) for the number limbs.  For those, it would probably be more appropriate to use something like `uint64_t` rather than `size_t`, especially considering that the latter can't be relied upon to have a fixed size.

**Comment by t8m** [comment]
> Basically this would just be an update to the coding style policy that says that use of long is deprecated; thus any new APIs or code should not use long.

If you'd like to submit a PR to add this to coding-style, it would be welcome.

**Comment by mattcaswell** [comment]
I think we've been informally avoiding long for quite a while. It's often necessary though due to it being in the public API. It would be good to have it explicitly in the coding style.

**Comment by hlandau** [comment]
> For example, the BN code uses variants of `long` (such as `long long`) for the number limbs. For those, it would probably be more appropriate to use something like `uint64_t` rather than `size_t`, especially considering that the latter can't be relied upon to have a fixed size.

This is one of those circumstances where one wants a type which is register-sized for performance reasons, without caring about the exact size. Unfortunately the C standard offers no good candidates: long is out because of Windows, `size_t` is only guaranteed to be large enough to contain an array index (which might be much smaller than a pointer on segmented architectures), and `uintptr_t` may be more than 64 bits on up-coming capability-based architectures, as I  understand it (and doesn't exist at all in existing capability-based systems such as IBM i).

We should maybe also introduce something like `ossl_uword` / `ossl_word` for circumstances like this, but its definition would probably have to be ifdef-based.

I'll get a policy PR up.

**Comment by t-j-h** [comment]
> I imagine basically anyone using OpenSSL on Windows is building and distributing it themselves.

You would be rather wrong on that assumption.
Most windows users are using a pre-built version these days.

**Comment by t8m** [comment]
This is being handled by https://github.com/openssl/technical-policies/pull/51
