### ISSUE TITLE
Dumb $hit


### ISSUE THREAD

**Issue by Kayd4400** [openssl/openssl#18336]
Secret Space Encryptor for Android - Changelog File
(home page: https://paranoiaworks.mobi/sse)
3.0.2 (maintenance release)
- Addressed some GUI challenges related to support for Android applications under Windows 11;
- Added an option of delayed activation to the "Lock Screen" function (Android 4.2 and later);
- Some other optimizations;

3.0.1 (maintenance release)
- FIX: The application crashes on some devices during the purchase workflow of the PRO version update (Google Play Version only);
- FIX: Some Xiaomi devices on Android 11 have reported "text invisibility" issues with the default system "Single Item Selection Dialog" - the dialog has been replaced by custom implementation;

3.0
- File Encryptor: Updated file encryptor's data format. Upgraded authentication algorithm (BLAKE2b → BLAKE3).
 (more: version 4);
- File Encryptor: Overall performance improvement on multi-core CPUs;
- PRO version: Added a new algorithm "Paranoia C4" which is a cascade of Threefish–Serpent–AES–SHACAL2;
- Updated application's target API (level 30) and Google Play API;

2.3.3 (maintenance release)
- Polished Russian localization (thanks to contributor Zemensis);
- Improved memory management and other optimizations;

2.3.2 (maintenance release)
- Unification of the Google Play Store version and the "F" edition version ("F" version - free of dependencies on Google services and distributed outside of the Google Play Store);
- Some other improvements;

2.3.1 (maintenance release)
- File Encryptor: Added warning "previous task forcibly terminated" when starting the application (if File Encryptor was forcibly terminated during a task in the previous run - killed by system, device restart, etc.);
- Performance and stability optimization;
+ First "F" edition release;

2.3
- Text Encryptor: The Copy / Paste buttons have been replaced by the Import / Export buttons, which provide more options;
- File Encryptor: Added notification for encryption / decryption procedures;

2.2.3
- FIX: Certain system events (such as a language change) can cause the application to crash on some devices;
- A new option in settings (Allow External Autofill);

2.2.2
- Maintenance release: Updated application target API (level 29) + optimizations for Android 11;
- A new feature in File Encryptor - Create Folder;

2.2.1
- Maintenance release: An updated help, some GUI improvements and other fixes;
- A new option in settings (Clear Clipboard on Exit);

2.2
- Password Vault: Added an option to use "Extended Items" — more complex entries with custom elements;

2.1.2
- FIX: The app crashes sometimes when browsing files in SAF mode;

2.1.1
- Maintenance release: Optimizations + preparations for Android 11 (forced scoped storage);

2.1
- Added support for the decryption of links created by https://linkenc.net
- Updated application's target API (level 28) and Google Play API;
- Text Encryptor: Added "fast scrollbars" to both text fields;
- Some GUI optimizations and other improvements;

2.0
- Password Vault: Updated password vault's data format;
 (KDF: scrypt → Argon2id); 
 (more: version 3);
- Text Encryptor: Updated text encryptor's data format;
 (compression DEFLATE → LZMA, KDF: scrypt → Argon2id); 
 (more: version 3);

1.8.1
- Improved steganography performance;
- Application's target API level has been raised to 27;
+ version C - FIX: (issue on Android 7+) - File Encryptor: Functions "Open File" and "Send to" always end with message "No apps can perform this action".

1.8.0
- File Encryptor: Updated file encryptor's data format;
 (encryption mode CBC → CTR, new key derivation function based on Argon2id); 
 (more: version 3);
- File Encryptor: SAF mode can be used directly for output operations (if custom destination folders are activated in app's settings - Settings: File Encryptor → Encrypted/Decrypted Files Destination);
- Added native code libraries for arm64-v8a and x86_64 architectures;

1.7.3
- Text Encryptor: Added new final encoding options: Base32 (RFC 4648), Numbers Only (0-9);
- Text Encryptor: File picker option for encrypted texts and steganograms (Android 4.4 or later);
- Text Encryptor: Lock screen function for the text encryptor;
- Application launch protection function - (related settings - Settings: Common Settings → Application Launch Protection);

1.7.2
- Password Vault: Merge feature - (More button → Merge Vaults)
- Text Encryptor: Steganography (concealing a text within an image - JPG) - (More button → ...)
- File Encryptor: Delete encrypted files after decryption (Settings: File Encryptor → Delete .enc File After Decryption)
+ version C - FIX: (issue on Android 2.3 - 4.1) - Password Vault: the cursor in the "Notes" text field cannot be positioned by a click when an active link (URL, email, ...) is present

1.7.1
- Password Vault: Passwords can be used directly in the Text/File Encryptor (Text/File Encryptor can be opened from the "item detail screen").
- Password Vault: The password is not a mandatory attribute - the vault can be used for notes easily.
- Password Vault: New category icons.
- Text Encryptor: Fullscreen button.
- File Encryptor: Support of "Share" (SEND and SEND_MULTIPLE (if a multiple file selection feature is enabled)) actions from other applications for all file types.
- Password Generator: Custom character set feature.
+ A web-based Text Encryptor (client-side AES) is newly available on: https://pteo.paranoiaworks.mobi

1.7.0
- File Encryptor: Changes in the data format (a new key derivation function based on scrypt).
  (more: version 2)
- Pro Version: SHACAL-2 512bit algorithm added

1.6.0
- Password Vault: Changes in the internal data format + in the pwv file format 
  (encryption mode CBC → EAX, compression DEFLATE → LZMA, new key derivation function based on scrypt). 
  (more: version 2)
- Password Vault: Auto backup feature.
- Text Encryptor: Changes in the data format 
  (encryption mode CBC → EAX, new key derivation function based on scrypt). 
  (more: version 2)
- File Encryptor: Image thumbnails.
+ version C - FIX: issue on Android 5.0+ - File Encryptor: "application has stopped" issue in case of specific file name/file path configurations using SAF mode

1.5.4
- File Encryptor: Custom destinations for Encrypted/Decrypted files.
- File Encryptor + Password Vault: Quick scroll feature.
- Password Vault: Password Detail Screen - URLs placed in the "Notes" field are clickable now.
- Text Encryptor: Font size can be changed.

1.5.3
- Text Encryptor: New feature - Load/Save encrypted text to a file
- Pro Version - File Encryptor: Multiple File Selection (batch processing)

1.5.2
- Password Vault (item detail screen - Notes): New feature Copy to Clipboard (All/Chosen Paragraph) + some UI changes
- Pro Version: Threefish 1024bit algorithm added

1.5.1
- version C - FIX: issue on Android 5.0 - File Encryptor/List Button - "application has stopped" issue when external SD card is not present
- Android 5 - SAF (Storage Access Framework) for external/removable storage
- some UI changes (mainly in File Encryptor)

1.4.10
- Encryption libraries update + some UI changes 
+ Text Encryption for iOS(iPhone/iPad/iPod) and for PC (Windows, Linux, Mac OS X, ...) are newly available

1.4.9
- Text Encryptor: New button "Send text to chosen application"
- Reported issues fixes

1.4.8
- File Encryptor – "Session (Master) Password" feature added
- File Encryptor – "Home/Default Directory" feature added
- Text Encryptor – "Clean Text Areas" feature added
- Some minor improvements

1.4.7
- Native Code MIPS processors support.
- Some minor improvements.

1.4.6
- Password Vault - Extended Import/Export function (unencrypted XML file).
- File Encryptor - Added "Send to" feature (for files).
- Some other improvements.

1.4.5
- File Encryptor – Preserve original file's "last modified time".
- File Encryptor – ENC file association feature added.
- Some other improvements.
+ Cross-Platform (Windows, Linux, Mac OS X, ...) GUI Version of the File Encryptor is now available on the application home page (download section).

1.4.4
- All algorithms are available in Native Code (ARM, x86).

1.4.3
- File Encryptor – Enhanced file integrity check.
- Some "cosmetic" changes.
+ Cross Platform (Java) Command Line Version of the File Encryptor is now available on the application home page (download section).

1.4.2
- All algorithms except Serpent are available in Native Code (ARM, x86).
- Some changes in the user interface.

1.4.1
- AES and RC6 algorithms in Native Code (ARM, x86) added. File END/DEC procedures should be significantly faster with compatible devices.
- Password Vault - Optional feature "Screen Lock" added. It can be enabled in the app Settings → Password Vault section → Lock Screen
- File Encryptor – Compression ON/OFF option added.

1.4.0
- New algorithms added - Blowfish 448bit, Twofish 256bit, GOST 256bit
- New application category "Other Utils"
- Some changes in the user interface

1.3.3
- Password Vault/Password Detail Screen - new feature "Password Generator" (icon next to the password field in new/edit mode)
- File Encryptor - Open File directly from the File Encryptor (long press on a file - Open File)

1.3.2
- File Encryptor - Compression algorithm (archive type) upgraded to Zip64
- File Encryptor - single pass decryption process
- minor fixes

1.3.1
- improved compatibility with some of new devices

1.3
- Allow Unicode Passwords - whole Unicode charset can be used for Passwords 
 (related setting - Application Settings: Common/Allow Unicode Passwords)
- File Encryptor - Delete with Wiping: select a File/Folder, press the Menu Button and choose Wipe 
 (related setting - Application Settings: File Encryptor/Wipe Source After Encryption)
- minor aesthetic changes(Password Vault/Folder List - more thematic icons, ...)
- "System Log Features" option has been removed

1.2.3
- FIX: application crash on startup (on some devices without external storage)
- Password Vault/Folder List - Bottom Menu is hidden by default (press "Menu Button" to Show/Hide the Bottom Menu)
- some minor fixes and aesthetic changes

1.2.1
- Password Vault/Folder List - new feature "Enforce Order" (enforce absolute positioning in the default alphabetical order)
- Password Vault/Folder List - more folder icons
- Password Vault/Password Item Detail - new feature "Move to Folder" (move item from the current folder to another)
- retested on Android 4.0

1.1
- new custom parameter 'Password List Font Size' (Settings - Password Vault)
- "graphical compatibility improvement fix" for some devices (mainly "high density" and Android 3.x devices)
- minor changes in the build-in Quick Help

1.0
- first public release (October 2011)

**Comment by levitte** [comment]
This seems misplaced
