### ISSUE TITLE
OpenSSL 3 cannot decrypt data encrypted with OpenSSL 1.1 with blowfish in OFB or CFB modes

### ISSUE THREAD

**Issue by tomhughes** [openssl/openssl#18359]
## OpenSSL versions

openssl-1.1.1n-1.fc35.x86_64
openssl-3.0.2-5.fc36.x86_64

## How to reproduce

Encrypt some data using OpenSSL 1.1:

```
openssl enc -bf-ofb -k test -in plaintext -out ciphertext
```

then copy the result to a machine with OpenSSL 3 and try and decrypt it:

```
openssl enc -d -provider legacy -provider default -bf-ofb -k test -in ciphertext
```

the result will be gibberish.

Equally encrypting with 3 and decrypting with 1.1 will fail.

## The root cause

The root cause is that OpenSSL 1.1 calls `BF_set_key` with a length of 16 which matches what `EVP_CIPHER_key_length` returns for this cipher while OpenSSL 3 calls it with a length of 8 instead so only uses half the key.

The reason for that is that `providers/implementations/ciphers/cipher_blowfish.c` specifies a shorter key length of 64 bits for the OFB and CFB modes but `crypto/evp/e_bf.c` defines all four BF ciphers with a key length of 16 bytes and while OpenSSL 1.1 sets the key length from the cipher OpenSSL 3 sets it from the context which gets it from the provider implementations.

When coding to the library interface you can work around this by calling `EVP_CIPHER_CTX_set_key_length` after setting the cipher on the context and before setting the key to get the old behaviour.

**Comment by t8m** [comment]
Fix in #18362
