### ISSUE TITLE
Add TFO support for NonStop x86

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#18352]
TFO is not yet supported on NonStop. This potentially could be added for 3.1.

Migrated from issue #18306

**Comment by mattcaswell** [comment]
> I will need some pointers/advice on making this happen.

Hopefully @tmshort can provide some guidance.

**Comment by rsbeckerca** [comment]
NonStop has supported `sendto()` for a long time - at least going back 3 CPU types - and I have used it successfully in the past, if that helps. Without a listener enabled (ifdef-ed out), this does explain why the `test-tfo-cli` hangs. It might be prudent to include some kind of hang detection here. Having too many `sendto()` outstanding calls might consume resources and result in a DoS situation - something to watch for.

**Comment by rsbeckerca** [comment]
As a side note: are we 100% sure that TFO does not introduce a critical vulnerability through packet injection?

**Comment by tmshort** [comment]
The implementation is designed to be easily extended to other platforms that share APIs with macOS, FreeBSD or Linux (each of which have different options).

The structure of `include/internal/bio_tfo.h` should be easy enough to interpret. So, the defines mentioned above ought to be part of the solution.

Since it's done via `sendto()`, then `OSSL_TFO_SENDTO` should be defined to an appropriate value (possibly `MSG_FASTOPEN`)? This ought to be the client.

How does NonStop specify TCP for a server socket?

**Comment by rsbeckerca** [comment]
> How does NonStop specify TCP for a server socket?

Pretty much like Linux. This shouldn't be hard, from what I can tell once we have that.

**Comment by nhorman** [comment]
marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by rsbeckerca** [comment]
@nhorman How does one enable tfo?

**Comment by nhorman** [comment]
As far as I know, it's not a feature enabled in openssl at all. For operating systems that support it, generally, you create a socket, and set the appropriate socket option prior to calling connect().  On Linux for example you set the socket option is TCP_FASTOPEN.  Other operating system may do things differently though. Nso in short:

1) create a socket
2) do whatever the os requires.to enable tfo on the socket
3) create your SSL_CTX
4) Create your SSL
5) Set the SSL to the socket from (1) using the SSL_set_sockfd() call
6) process as normal

**Comment by rsbeckerca** [comment]
It will take time to resolve this. I will look into it in future releases, but do not see anything in the latest OS that supports it. Nothing "Fast Open" - there is in CURL but not something I can see in `fcntl()` or `ioctl()` or `sockopt`. Please close.
