### ISSUE TITLE
security bits set by ossl_x509_init_sig_info OK?

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#18375]
~Is the [code setting security bits for X509 cert info](https://github.com/openssl/openssl/blob/a4e21d18d5b7cb4fef66c10f13b1b3b55945439f/crypto/x509/x509_set.c#L195-L276) sufficiently robust for public key algorithms losing in strength over time? The code seems to assign "secbits" exclusively based on the strength of the message digest without taking the strength of the public key (algorithm) into account.~

~Wouldn't it be more suitable to initialize `siginf->secbits` by `EVP_PKEY_get_security_bits(X509_PUBKEY_get(x->cert_info.key))` and then reduce the value of `siginf->secbits` by the strength of the MD algorithm?~

I encountered this code when working on integrating provider-implemented signature algorithms (#10512): [ossl_x509_init_sig_info](https://github.com/openssl/openssl/blob/a4e21d18d5b7cb4fef66c10f13b1b3b55945439f/crypto/x509/x509_set.c#L273) proved to be not correctly handling such algorithms (ones doing their own digesting, i.e., with mdnid=NID_undef), so code to delegate setting "siginf->secbits" to a provider needed to be added:

Please see [this diff](https://github.com/openssl/openssl/compare/master...baentsch:sigprovider?expand=1) if there'd be agreement with the assessment and a PR would be desirable.

**Comment by bernd-edlinger** [comment]
Doesn't ssl_security_cert_key check the public key strength here:

https://github.com/openssl/openssl/blob/163003a9bc36fb0cc0048fdb9adef9c0d7d562da/ssl/t1_lib.c#L3041-L3054

or is this somehow not working?

**Comment by baentsch** [comment]
Thanks for the pointer: This looks good and explains things for me: The function above calls `ssl_security_cert_sig` which in turn retrieves the `secbits` set by the function `ossl_x509_init_sig_info` referenced above: In other words, `ossl_x509_init_sig_info` indeed only is meant to set `secbits` representing the MD (strength), not the full signature. This was my misunderstanding: I always consider MD and sig alg to be "one item".

So there's no problem with key strength checking (text above suitably edited) -- but still one setting `secbits` for signature algorithms that don't need a message digest (i.e., non-legacy, provider-based ones): Those should set "secbits" based on the strength of that "MD-incl-sig" algorithm and not bail/fail as per https://github.com/openssl/openssl/blob/a4e21d18d5b7cb4fef66c10f13b1b3b55945439f/crypto/x509/x509_set.c#L216-L223

**Comment by mattcaswell** [comment]
> but still one setting secbits for signature algorithms that don't need a message digest (i.e., non-legacy, provider-based ones): Those should set "secbits" based on the strength of that "MD-incl-sig" algorithm and not bail/fail as per

Looks like you are correct to me.

**Comment by baentsch** [comment]
Closing as fixed by #18387
