### ISSUE TITLE
OpenSSL3: missing functions with custom OSSL_LIB_CTX*

### ISSUE THREAD

**Issue by lsh123** [openssl/openssl#18372]
I am implementing a custom library ctx for XMLSec library (https://github.com/lsh123/xmlsec/issues/346) and I run into a few functions that don't have the "_ex" variant that supports passing a custom LIB_CTX: 

* d2i_PUBKEY_ex_bio  (similar to d2i_PrivateKey_ex_bio)
 * d2i_PKCS12_ex_bio
 * PKCS12_verify_mac_ex
 * PKCS12_parse_ex
 * PKCS12_verify_mac
 * PKCS12_parse
 * d2i_PKCS8PrivateKey_bio

My current workaround is to set/restore default LIB_CTX with OSSL_LIB_CTX_set0_default() but it would be much nicer to have _ex() variants instead.

**Comment by t8m** [comment]
I do not think this is a bug, just a missing feature. There is the clear workaround with OSSL_LIB_CTX_set0_default() which is thread-specific so apart from it not being as simple to use as the functions with explicit libctx parameter, there should be no major downside of using the workaround.

**Comment by nhorman** [comment]
marking as inactive, to be closed at the end of 3.4 dev barring further input
