### ISSUE TITLE
About the problem of TLS1.3 reading early_data

### ISSUE THREAD

**Issue by jay900323** [openssl/openssl#18403]
When my server program uses the TLS1.3 protocol for handshake, it first uses SSL_read_early_data to read the early_data data, and prints the relevant information in the callback function registered with SSL_CTX_set_info_callback, but SSL_read_early_data always returns SSL_READ_EARLY_DATA_FINISH, no data can be read, and then The openssl client program shows that early_data is rejected, and I have called SSL_CTX_set_max_early_data at the beginning. What is the reason? I see that nginx also uses this way when reading early_data, and does not call SSL_do_handshake before calling SSL_read_early_data.

My info callback function output looks like this:

2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb: state [-] SSLv3/TLS read client hello
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb: state [-] SSLv3/TLS write server hello
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb: state [-] SSLv3/TLS write change cipher spec
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb: state [-] TLSv1.3 write encrypted extensions
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb: state [-] SSLv3/TLS write certificate
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb: state [-] TLSv1.3 write server certificate verify
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb: state [-] SSLv3/TLS write finished
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb_handshake_done: handshake [done] TLSv1.3 early data
2022/05/25 10:30:28 info: <tid 27942> ssl_state_cb_handshake_done: cipher: `TLS_AES_256_GCM_SHA384 TLSv1.3 Kx=any Au=any Enc=AESGCM(256) Mac=AEAD'
2022/05/25 10:30:28 debug: <tid 27942> SSL_read_early_data: 2, 0z

![image](https://user-images.githubusercontent.com/5362513/170170981-13d80d6c-01cd-4ea5-a27f-b08b460198f3.png)
![image](https://user-images.githubusercontent.com/5362513/170171035-5d5af8ca-542f-4161-8a4e-84e729b90a6b.png)
![image](https://user-images.githubusercontent.com/5362513/170171188-af382478-89eb-4242-83e0-2dcfd5145585.png)

**Comment by mattcaswell** [comment]
Your s_client output contains this line:

````
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
````
The "New" indicates that you are using a new session for this connection and have not resumed an old one. If you had used session resumption, and the resumption was successful, then the output would look like this:

````
Reused, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
````

Early data will only work on session resumption.

You don't show what command line arguments you pass to s_client. To create an initial connection and save the session you can do something like this:

````
$ openssl s_client -sess_out sess.pem
````
Quit s_client cleanly by typing "Q" and then enter (not exiting s_client cleanly will invalidate the session).

Then attempt to resume the session like this:

````
$ openssl s_client -sess_in sess.pem -early_data /path/to/my/early-data-file.txt
````

**Comment by jay900323** [comment]
The command I used is the same as you. I later debugged the openssl code and found that the value of s->hit in the final_early_data function was 0, resulting in s->ext.early_data being SSL_EARLY_DATA_REJECTED. I suspect that the PSK authentication may not have passed, and later I tried to call the SSL_CTX_sess_set_cache_size function when SSL_CTX is initialized, and early_data can be accepted.
![image](https://user-images.githubusercontent.com/5362513/170401227-9c9cf5a6-66fc-46ec-8cf7-c8342881c6e9.png)

But at this time, the server returned a New Session Ticket. I used the same command to send the early_data data again and it was rejected. I don't understand why the New Session Ticket will be sent again instead of using the last PSK information?

The command I use looks like this:
```
./openssl s_client -connect 10.67.8.195:7777 -sess_out session.pem -keylogfile tls_key.log
./openssl s_client -connect 10.67.8.195:7777 -keylogfile tls_key.log -sess_in session.pem -early_data request.txt
```

**Comment by mattcaswell** [comment]
> the value of s->hit in the final_early_data function was 0

This means the session was not resumed.

> But at this time, the server returned a New Session Ticket. I used the same command to send the early_data data again and it was rejected. I don't understand why the New Session Ticket will be sent again instead of using the last PSK information?

TLSv1.3 is designed to enable the use of single-use tickets (although it is not mandatory). OpenSSL will enforce single-use of tickets for the purposes of accepting early data as an anti-replay protection mechanism. See the following for more information:

https://datatracker.ietf.org/doc/html/rfc8446#section-8

Also see:

https://www.openssl.org/docs/man3.0/man3/SSL_read_early_data.html#REPLAY-PROTECTION

If you want to switch off OpenSSL's anti replay mechanism you can do so with the `SSL_OP_NO_ANTI_REPLAY` option. See:

https://www.openssl.org/docs/man3.0/man3/SSL_set_options.html

If you do this make sure you fully understand the security implications and how you will mitigate those risks in your application.

**Comment by jay900323** [comment]
When I enable the SSL_OP_NO_ANTI_REPLAY option and send early_data request multiple times with the same PSK information, the server accepts it normally every time. But I found that the server still returns a newsessionticket message every time, although the session ticket value in the newsessionticket message is always the same, I used the nginx server to test, and found that the newsessionticket will only be returned during the first complete authentication, The message will not be returned in the future, why is this?

nginx
![image](https://user-images.githubusercontent.com/5362513/170472935-79135aee-64f6-460b-8f7c-63737f936fc3.png)

my test program
![image](https://user-images.githubusercontent.com/5362513/170473038-140a2d7f-b1dc-4107-b6e5-07b45cbd3ac2.png)

**Comment by mattcaswell** [comment]
> I found that the server still returns a newsessionticket message every time

Yes. The NewSessionTicket behaviour and anit-replay are related but separate concepts. You can control the number of tickets issued using SSL_set_num_tickets or SSL_CTX_set_num_tickets as described here:

https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_num_tickets.html

> although the session ticket value in the newsessionticket message is always the same

Are you sure? They should be different every time.

> I used the nginx server to test, and found that the newsessionticket will only be returned during the first complete authentication, The message will not be returned in the future, why is this?

I'm not entirely sure I understand what you are asking here.

**Comment by mattcaswell** [comment]
> The difference is that when I test my own program, I can receive a newsessionticket every time . Are there any parameters that need to be set?

Like I mentioned above you can use `SSL_CTX_set_num_tickets` to do this. Probably nginx is using that.

> I want my server program send newsessionticket message only in a complete handshake, although it will reduce some security and improve program performance.

`SSL_CTX_set_num_tickets` can't do that directly. However you could set the number of tickets to 0 - so that new tickets are never sent automatically. In the case of a non-resumption handshake your application can request a ticket be sent by calling `SSL_new_session_ticket()`. You can check whether a resumption or non-resumption handshake occurred by calling `SSL_session_reused()`.

**Comment by jay900323** [comment]
Thank you for your answer, the problem has been solved, I forgot to close it。
when I access nginx, nginx has closed the connection before it returns a newsessionticket message, when I changed to http keep-alive connection The newsessionticket message will be received. According to my understanding, the newsessionticket message is returned at a uncertain time after the handshake is completed, not before the handshake is completed.
