### ISSUE TITLE
Error when trying to add wordpress website using webinoly on ubuntu 22.04

### ISSUE THREAD

**Issue by mendelsphotography** [openssl/openssl#18408]
Get this error on version 1.1.1.1

140698147750336:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:119:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140698147750336:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
140698147750336:error:0E07506E:configuration file routines:module_load_dso:error loading dso:crypto/conf/conf_mod.c:224:module=providers, path=providers
140698147750336:error:0E076071:configuration file routines:module_run:unknown module name:crypto/conf/conf_mod.c:165:module=providers

**Comment by t8m** [comment]
Apparently you're trying to use a configuration file that is supposed to be used with the 3.0 version with the 1.1.1 version. Do not do that.

**Comment by mendelsphotography** [comment]
tried fixing thar

**Comment by mendelsphotography** [comment]
also at this point, it's not worth anything since bricked the server trying to downgrade back to ubuntu 20.04. but would be interested to know how to do that since asked tons people I realized the config file is the issue but could not find for the life of me where it is.
