### ISSUE TITLE
Erorr with openssl and wordpress on Ubuntu 22.04 

### ISSUE THREAD

**Issue by mendelsphotography** [openssl/openssl#18409]
Hi so getting this error on my WordPress site after I forced an upgrade on the server from 20.04 to 22.04 in the WordPress plugin analytify

this is the error 
Oops!
OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
Don't worry, This error message is only visible to Administrators.

**Comment by t8m** [comment]
You'll get this error if the other side of the communication does not close the TLS communication cleanly but just terminates the connection. In most cases (depending on the protocol using the TLS) it can be ignored. I suppose this is using https and for that case it can be ignored.

**Comment by mendelsphotography** [comment]
I was using HTTPS on the site using Cloudflare and Cloudflare origin keys
