### ISSUE TITLE
KEMs may not return explicit failure in EVP_PKEY_decapsulate.

### ISSUE THREAD

**Issue by bhess** [openssl/openssl#18428]
The API documentation for KEM decapsulation - [EVP_PKEY_decapsulate](https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_decapsulate.html) - suggests that the function returns 0 or a negative value for failure.

However, most PQC KEMs such as those implemented by [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) don't return an error code if decapsulation failed (e.g. due to modified ciphertext). This is to avoid failure oracles.

For the caller of the API this can be unexpected reading the API documentation. It would be safer to document that `EVP_PKEY_decapsulate` may not return an explicit failure code if decapsulation failed.

**Comment by nhorman** [comment]
marking as inactive, to be closed at the end of 3.4 dev barring further input
