### ISSUE TITLE
Is there any better way to generate a RSA key?

### ISSUE THREAD

**Issue by CaledoniaProject** [openssl/openssl#18422]
I need to generate a PKCS1 format PEM key, aka `BEGIN RSA PUBLIC KEY`.

The following method looks so dumb to me, can I do that with openssl instead?

```
ssh-keygen -t rsa -b 2048 -f id_rsa 
ssh-keygen -f id_rsa.pub -e -m pem > pub.txt
ssh-keygen -p -N "" -m pem -f id_rsa
mv id_rsa priv.txt
```

**Comment by t8m** [comment]
```
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 | openssl pkey -traditional -out priv.pem
```
Should work.

**Comment by CaledoniaProject** [comment]
@t8m Which version works for you?

```
%> openssl pkey -traditional -out priv.pem
Unknown cipher traditional
Usage pkey [options]
where options are
-in file        input file
-inform X       input format (DER or PEM)
-passin arg     input file pass phrase source
-outform X      output format (DER or PEM)
-out file       output file
-passout arg    output file pass phrase source
```

**Comment by t8m** [comment]
Any currently supported version (i.e., 1.1.1 or 3.0) should work.

**Comment by CaledoniaProject** [comment]
@t8m It only generates the private key, how can I get the public key?

**Comment by t8m** [comment]
`openssl pkey -in priv.pem -pubout`

Of course that will output the public key in the PEM format (`-----BEGIN PUBLIC KEY-----`). If you need the ssh public key format you need to use utilities from OpenSSH.
