### ISSUE TITLE
getting public key from EVP_PKEY generated with private key

### ISSUE THREAD

**Issue by aizuon** [openssl/openssl#18437]
Before 3.0, I was able to get the public key of an EC private key using basic EC maths even if EC_KEY was generated only with private key information with the following function:
```cpp
std::vector<uint8_t> ECDSA::GetPubKeyFromPrivKey(EC_KEY* ec_key, const EC_GROUP* ec_group)
{
	auto* bn_ctx = BN_CTX_new();

	const auto* pub_key = EC_KEY_get0_public_key(ec_key);
	if (pub_key == nullptr)
	{
		auto* pub_key2 = EC_POINT_new(ec_group);
		const auto* priv_key = EC_KEY_get0_private_key(ec_key);
		if (!EC_POINT_mul(ec_group, pub_key2, priv_key, nullptr, nullptr, bn_ctx))
		{
			BN_CTX_free(bn_ctx);

			return {};
		}
		if (!EC_KEY_set_public_key(ec_key, pub_key2))
		{
			BN_CTX_free(bn_ctx);

			EC_POINT_free(pub_key2);

			return {};
		}
		if (!EC_KEY_check_key(ec_key))
		{
			BN_CTX_free(bn_ctx);

			EC_POINT_free(pub_key2);

			return {};
		}
		pub_key = pub_key2;
	}

	auto* pub_key_bn = BN_new();
	if (EC_POINT_point2bn(ec_group, pub_key, POINT_CONVERSION_COMPRESSED, pub_key_bn, bn_ctx) == nullptr)
	{
		BN_free(pub_key_bn);
		BN_CTX_free(bn_ctx);

		return {};
	}
	std::vector<uint8_t> pub_key_buffer(BN_num_bytes(pub_key_bn));
	if (!BN_bn2bin(pub_key_bn, pub_key_buffer.data()))
	{
		BN_free(pub_key_bn);
		BN_CTX_free(bn_ctx);

		return {};
	}
	BN_free(pub_key_bn);
	BN_CTX_free(bn_ctx);

	return pub_key_buffer;
}
```

As most of EC_ functions are now deprecated, I can not use this function anymore. I was able to successfully import the private key to an EVP_PKEY structure using params, however, after creating the EVP_PKEY structure, I can not get the public key via params(it is empty as it was the case with this function, thats why I use EC maths to calculate public key). I searched the docs for quite some time, however I can not find useful functions that can get me to calculate the public key from only private key. 

I really want to migrate to 3.0. Are there any useful examples regarding this issue I can check?

Extra:

The following does not work as pub_key is just nullptr. The same thing happened on OpenSSL 1 with EC_KEY_get0_public_key. That is why "if (pub_key == nullptr)" exists as I mathematically calculate it from private key using now deprecated EC_ functions. 

```cpp
std::vector<uint8_t> ECDSA::GetPubKeyFromPrivKey(const std::vector<uint8_t>& privKey)
{
	EVP_PKEY* ec_key = nullptr;

	EVP_PKEY_CTX* pCtx = EVP_PKEY_CTX_new_from_name(nullptr, "EC", nullptr);
	if (pCtx == nullptr)
	{
		return {};
	}
	EVP_PKEY_fromdata_init(pCtx);

	OSSL_PARAM params[3];
	params[0] = OSSL_PARAM_construct_utf8_string(OSSL_PKEY_PARAM_GROUP_NAME, const_cast<char*>(SN_secp256k1), 0);
	params[1] = OSSL_PARAM_construct_BN(OSSL_PKEY_PARAM_PRIV_KEY, const_cast<uint8_t*>(privKey.data()), privKey.size());
	params[2] = OSSL_PARAM_construct_end();

	EVP_PKEY_fromdata(pCtx, &ec_key, EVP_PKEY_KEYPAIR, params);
	if (ec_key == nullptr)
	{
		EVP_PKEY_CTX_free(pCtx);

		return {};
	}

	auto pub_key_buffer = GetPubKeyFromPrivKey(ec_key);
	if (pub_key_buffer.empty())
	{
		EVP_PKEY_CTX_free(pCtx);
		EVP_PKEY_free(ec_key);

		return {};
	}

	EVP_PKEY_CTX_free(pCtx);
	EVP_PKEY_free(ec_key);

	return pub_key_buffer;
}

std::vector<uint8_t> ECDSA::GetPubKeyFromPrivKey(EVP_PKEY* ec_key)
{
	BIGNUM* pub_key = nullptr;
	EVP_PKEY_get_bn_param(ec_key, OSSL_PKEY_PARAM_PUB_KEY, &pub_key);
	if (pub_key == nullptr)
	{
		return {};
	}

	std::vector<uint8_t> pub_key_buffer(BN_num_bytes(pub_key));
	if (!BN_bn2bin(pub_key, pub_key_buffer.data()))
	{
		return {};
	}

	return pub_key_buffer;
}
```

**Comment by mattcaswell** [comment]
> As most of EC_ functions are now deprecated, I can not use this function anymore. I was able to successfully import the private key to an EVP_PKEY structure using params, however, after creating the EVP_PKEY structure, I can not get the public key via params(it is empty as it was the case with this function, thats why I use EC maths to calculate public key). I searched the docs for quite some time, however I can not find useful functions that can get me to calculate the public key from only private key.

Only the `EC_KEY_*` functions are deprecated. Most of the remaining ones were deliberately left undeprecated - so `EC_POINT_new`, `EC_POINT_mul`, etc should all still work just fine. With that in mind your previous approach of mathematically calculating the key should still work. You will still an `EC_GROUP` object which you can create using one of the `EC_GROUP_new_*` functions.

We probably should add a feature at some point to automatically calculate the Public key from the private one.

**Comment by aizuon** [comment]
> > As most of EC_ functions are now deprecated, I can not use this function anymore. I was able to successfully import the private key to an EVP_PKEY structure using params, however, after creating the EVP_PKEY structure, I can not get the public key via params(it is empty as it was the case with this function, thats why I use EC maths to calculate public key). I searched the docs for quite some time, however I can not find useful functions that can get me to calculate the public key from only private key.
> 
> Only the `EC_KEY_*` functions are deprecated. Most of the remaining ones were deliberately left undeprecated - so `EC_POINT_new`, `EC_POINT_mul`, etc should all still work just fine. With that in mind your previous approach of mathematically calculating the key should still work. You will still need an `EC_GROUP` object which you can create using one of the `EC_GROUP_new_*` functions.
> 
> We probably should add a feature at some point to automatically calculate the Public key from the private one.

Thanks for the reply, I was able to successfully convert my code. It is written below if anybody is interested:

```cpp
std::vector<uint8_t> ECDSA::GetPubKeyFromPrivKey(EVP_PKEY* ec_key)
{
	size_t pub_key_size = 0;
	EVP_PKEY_get_octet_string_param(ec_key, OSSL_PKEY_PARAM_PUB_KEY, nullptr, 0, &pub_key_size);
	std::vector<uint8_t> pub_key_buffer(pub_key_size);
	if (!EVP_PKEY_get_octet_string_param(ec_key, OSSL_PKEY_PARAM_PUB_KEY, pub_key_buffer.data(), pub_key_buffer.size(),
	                                     &pub_key_size))
	{
		size_t group_name_size = 0;
		EVP_PKEY_get_utf8_string_param(ec_key, OSSL_PKEY_PARAM_GROUP_NAME, nullptr, 0, &group_name_size);
		std::vector<char> group_name(group_name_size + 1);
		if (!EVP_PKEY_get_utf8_string_param(ec_key, OSSL_PKEY_PARAM_GROUP_NAME, group_name.data(), group_name.size(),
		                                    &group_name_size))
		{
			return {};
		}

		int group_nid = OBJ_sn2nid(group_name.data());
		if (group_nid == NID_undef)
		{
			return {};
		}

		auto* ec_group = EC_GROUP_new_by_curve_name(group_nid);
		if (ec_group == nullptr)
		{
			return {};
		}

		auto* pub_key = EC_POINT_new(ec_group);
		if (pub_key == nullptr)
		{
			EC_GROUP_free(ec_group);

			return {};
		}
		BIGNUM* priv_key = nullptr;
		if (!EVP_PKEY_get_bn_param(ec_key, OSSL_PKEY_PARAM_PRIV_KEY, &priv_key))
		{
			EC_POINT_free(pub_key);
			EC_GROUP_free(ec_group);

			return {};
		}

		if (!EC_POINT_mul(ec_group, pub_key, priv_key, nullptr, nullptr, nullptr))
		{
			EC_POINT_free(pub_key);
			EC_GROUP_free(ec_group);

			return {};
		}

		pub_key_size = EC_POINT_point2oct(ec_group, pub_key, POINT_CONVERSION_COMPRESSED, nullptr, 0, nullptr);
		if (pub_key_size == 0)
		{
			EC_POINT_free(pub_key);
			EC_GROUP_free(ec_group);

			return {};
		}
		pub_key_buffer.resize(pub_key_size);
		if (!EC_POINT_point2oct(ec_group, pub_key, POINT_CONVERSION_COMPRESSED, pub_key_buffer.data(),
		                        pub_key_buffer.size(), nullptr))
		{
			EC_POINT_free(pub_key);
			EC_GROUP_free(ec_group);

			return {};
		}

		EC_POINT_free(pub_key);
		EC_GROUP_free(ec_group);

		if (!EVP_PKEY_set_octet_string_param(ec_key, OSSL_PKEY_PARAM_ENCODED_PUBLIC_KEY, pub_key_buffer.data(),
		                                     pub_key_buffer.size()))
		{
			return {};
		}

		auto* pCtx = EVP_PKEY_CTX_new_from_pkey(nullptr, ec_key, nullptr);
		if (pCtx == nullptr)
		{
			return {};
		}

		if (!EVP_PKEY_public_check_quick(pCtx))
		{
			EVP_PKEY_CTX_free(pCtx);

			return {};
		}

		EVP_PKEY_CTX_free(pCtx);
	}

	return pub_key_buffer;
}
```
