### ISSUE TITLE
Confusion: “organizationUnitName” vs. “organizationalUnitName”

### ISSUE THREAD

**Issue by FGasper** [openssl/openssl#1843]
http://oid-info.com/get/2.5.4.11
^^ This site gives the name for this OID as “organizationUnitName”.

OpenSSL has “organizationalUnitName” and rejects “organizationUnitName”.

Should OpenSSL accept both names since they are both in circulation?

**Comment by mattcaswell** [comment]
Looks like the linked site was corrected. Closing.
