### ISSUE TITLE
FreeTDS 1.3.10 with OpenSSL 1.1.1l (or newer) fails to connect to MS SQL server

### ISSUE THREAD

**Issue by CyberCr33p** [openssl/openssl#18433]
FreeTDS 1.3.10 with OpenSSL 1.1.1l (or newer) fails to connect to MS SQL server.

The last version that works is 1.1.1k.

Any idea what changed between 1.1.1k and 1.1.1l which can cause this issue?

The same bug is reported here too:

1) https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261967

2) https://github.com/FreeTDS/freetds/issues/458

**Comment by t8m** [comment]
There is already a fix in the FreeTDS, however it is unclear how that could help or change anything.

**Comment by CyberCr33p** [comment]
Yes just fixed in FreeTDS 1.3.11.
