### ISSUE TITLE
Not able to sign & verify using X25519

### ISSUE THREAD

**Issue by swanandb2** [openssl/openssl#18448]
[OpenSSLExample.zip](https://github.com/openssl/openssl/files/8814492/OpenSSLExample.zip)
PSA example.
I am able to sign and verify using Ed25519 but when I try to change curve name to X2219 then it did not work.
Following are findings.

  //Generate key
  EVP_PKEY *pkey = NULL;
  int nNid = GetNidFromOid(sOid);
  m_pCtx = EVP_PKEY_CTX_new_id(nNid, NULL);  //nNid = EVP_PKEY_X25519 (Fails) when it is nNid = EVP_PKEY_ED25519 works!
  EVP_PKEY_keygen_init(m_pCtx);
  EVP_PKEY_keygen(m_pCtx, &pkey);  //Keys are getting generated in both cases.
 hmac_it(hash, nHashSize, sig, pSiglen, pkey);

//For sign
int hmac_it(const unsigned char *msg, size_t mlen, unsigned char **sig, size_t *pSiglen, EVP_PKEY *pkey)
{   
  EVP_MD_CTX *mdctx = NULL;
  int ret = 0;
  *sig = NULL;

  /* Create the Message Digest Context */
  if (!(mdctx = EVP_MD_CTX_create())) goto err;

  /* Initialise the DigestSign operation - SHA-256 has been selected as the message digest function in this example */
 // if (1 != EVP_DigestSignInit(mdctx, NULL, NULL, NULL, pkey)) goto err; //Ed25519
  **//error:03000096:digital envelope routines::operation not supported for this keytype !!
  if (1 != EVP_DigestSignInit(mdctx, NULL, EVP_sha256(), NULL, pkey)) goto err;**  //I did try different SHA still get same error

  /* Call update with the message */
 // if (1 != EVP_DigestSignUpdate(mdctx, msg, mlen)) goto err;

  /* Finalise the DigestSign operation */
  /* First call EVP_DigestSignFinal with a NULL sig parameter to obtain the length of the
   * signature. Length is returned in slen */
  //if (1 != EVP_DigestSignFinal(mdctx, NULL, &slen)) goto err;
  /* Allocate memory for the signature based on size in slen */

  EVP_DigestSign(mdctx, NULL, pSiglen, msg, mlen);

  *sig = (unsigned char*)OPENSSL_zalloc(*pSiglen);

  ret = EVP_DigestSign(mdctx, *sig, pSiglen, msg, mlen);

  OPENSSL_free(*sig);
}

As per my understanding Ed25519 & X25519 both curve are supported by lib.
I am using latest master branch source. PSA attach file for complete source sample.

**Comment by t8m** [comment]
X25519 curve does not support signatures.

**Comment by davidben** [comment]
More specifically, neither Ed25519 nor X25519 are curves. Ed25519 is a signature scheme, thus you can sign with it. X25519 is a Diffie-Hellman primitive. You cannot sign with a Diffie-Hellman primitive, and you cannot run Diffie-Hellman with a signature scheme.

Both happen to, internally, use elliptic curves and indeed closely related curves. But that's part of their internals. In terms of actually using them, they are simply their corresponding cryptographic primitives.

**Comment by swanandb2** [comment]
Thanks you understood! I updated code to use 
I use other API, ECDSA_do_sign & ECDSA_do_verify it seems to be working with other curves. (ex: prime256v1, NID_secp192k1 etc..)
Can I get EC_KEY public part from generated EC_KEY part?

Following code works for me.

    EC_KEY *eckey = EC_KEY_new();
EC_GROUP *ecgroup = EC_GROUP_new_by_curve_name(NID_X9_62_prime256v1); //NID_ecdsa_with_SHA256
int set_group_status = EC_KEY_set_group(eckey, ecgroup);
 int gen_status = EC_KEY_generate_key(eckey);
 and then I use ECDSA_do_sign & ECDSA_do_verify 

I did check, following API
const EC_POINT *EC_KEY_get0_public_key(const EC_KEY *key);  --> Retrieve EC_POINT not EC_KEY public art

**Comment by davidben** [comment]
ECDSA and EC_KEY are the X9.62 of algorithms, which is a different formulation of elliptic curve cryptography altogether. It is completely separate from X25519 and Ed25519.

What are you trying to do?

**Comment by swanandb2** [comment]
Sorry for creating confusion for X25519. I understood that curve is not use for digital sign & verify.
I am trying following steps:
Parse x509 certificate
Get algorithm Id sha256ECDSA ( OID: 1.2.840.10045.3.1.7, which use curve prime256v1 curve and not X25519)
![image](https://user-images.githubusercontent.com/34519576/171557778-ce882c68-2ac2-412d-a823-89588682fda1.png)
Now, I am trying to perform sign & verify using using ECDSA.

I am able to sign & verify with following code. It works!!
But I want to extract public key so that I can separate sign and verify functions.
Kindly let me know in case of any query

int EcDSATest::DoSign(unsigned char* hash, const int& nHashSize)
{
    int function_status = -1;
    EC_KEY *eckey = EC_KEY_new();

    if (NULL == eckey)
    {
      printf("Failed to create new EC Key Error: %d %s\n", ERR_get_error(), ERR_error_string(ERR_get_error(), NULL));
      function_status = -1;
    }
    else
    {
      //NID_secp192k1
      //NID_X9_62_prime256v1
      EC_GROUP *ecgroup = EC_GROUP_new_by_curve_name(NID_X9_62_prime256v1); //NID_ecdsa_with_SHA256
      if (NULL == ecgroup)
      {
        printf("Failed to create new EC Group, Error: %d %s\n\n", ERR_get_error(), ERR_error_string(ERR_get_error(), NULL));
        function_status = -1;
      }
      else
      {
        int set_group_status = EC_KEY_set_group(eckey, ecgroup);
        const int set_group_success = 1;
        if (set_group_success != set_group_status)
        {
          printf("Failed to set group for EC Key, Error: %d %s\n", ERR_get_error(), ERR_error_string(ERR_get_error(), NULL));
          function_status = -1;
        }
        else
        {
          const int gen_success = 1;
          int gen_status = EC_KEY_generate_key(eckey);
          if (gen_success != gen_status)
          {
            printf("Failed to generate EC Key, Error: %d %s\n", ERR_get_error(), ERR_error_string(ERR_get_error(), NULL));
            function_status = -1;
          }
          else
          {
           **I want to extract public key from private EC_KEY?**

            **ECDSA_SIG *signature = ECDSA_do_sign(hash, nHashSize, eckey);**  Here I want to use Public key 
            if (NULL == signature)
            {
              printf("Failed to generate EC Signature, Error: %d %s\n", ERR_get_error(), ERR_error_string(ERR_get_error(), NULL));
              function_status = -1;
            }
            else
            {

              int verify_status = ECDSA_do_verify(hash, nHashSize, signature, eckey);
              const int verify_success = 1;
              if (verify_success != verify_status)
              {
                printf("Failed to verify EC Signature, Error: %d %s\n", ERR_get_error(), ERR_error_string(ERR_get_error(), NULL));
                function_status = -1;
              }
              else
              {
                printf("Verifed EC Signature\n");
                function_status = 1;
              }
            }
          }
        }
        EC_GROUP_free(ecgroup);
      }
      EC_KEY_free(eckey);
    }
    return function_status;
}

**Comment by swanandb2** [comment]
I am able to retrieve public key from private EC_KEY. I use following method & verification also work with public key.
Thanks!

EC_KEY *pPubKey = EC_KEY_new();
              EC_POINT const* pub = EC_KEY_get0_public_key(eckey); //ecKey is private key
              EC_KEY_set_public_key(pPubKey, pub);
              if (!pub)
              {
                std::cerr << "Error getting public key" << '\n';
                EC_KEY_free(eckey);
                return EXIT_FAILURE;
              }
              function_status = EC_KEY_set_group(pPubKey, ecgroup);  //Set group
              function_status = EC_KEY_set_public_key(pPubKey, pub); //Set public key
