### ISSUE TITLE
PR18353 breaks Windows build for x86 using nasm

### ISSUE THREAD

**Issue by kiyolee** [openssl/openssl#18459]
The `#ifdef` and `#endif` added by #18353 are not supported by nasm. (tested with version 2.15.05)
This breaks compiling `bf-586.pl` and `des-586.pl`.
Changing these directives to `%ifdef` and `%endif` seems to be able to get nasm to compile but not sure if this acheives the original desired effect for #18353.

**Comment by mattcaswell** [comment]
This reminds me of #18263.

I think perhaps we need some additional `GENERATE` lines to push the .S files through the preprocessor and create .s files??

**Comment by t8m** [comment]
Hmm, why don't we see it in our CI builds? We do 32 bit Windows builds with nasm.

**Comment by nhorman** [comment]
marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by kiyolee** [comment]
According to nasm doc https://www.nasm.us/xdoc/2.16.03/html/nasmdoc4.html#section-4.6, the correct macros should be `%ifdef` and `%endif`.
I am building for Windows in some kind of unofficial methods https://github.com/kiyolee/openssl3-win-build, and `#ifdef` and `#endif` do cause me compile errors.
With the official methods, does the `.pl` files pass through `cpp` before `perl`? That could be a reason why it succeed.

**Comment by t8m** [comment]
> With the official methods, does the `.pl` files pass through `cpp` before `perl`? That could be a reason why it succeed.

Yes, it does.
