### ISSUE TITLE
Non-repeatable CI failure in 30-test_acvp.t

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#18466]
I've just encountered a non-repeatable CI failure in a 3.0 pull request, reported here:
https://github.com/openssl/openssl/pull/18463#issuecomment-1144988708

When I repeated this test the issue went away, which is not good.

**Comment by bernd-edlinger** [comment]
No, it is not relevant.  I tried it both ways but that did not affect the test result.
I tried to lower the imax from 5 * bits to 1 * bits and that made the test fail in
very much the same way as if did in the CI run, where it happened unexpectedly.

**Comment by t8m** [comment]
IMO this is resolved by  #18429. Closing.
