### ISSUE TITLE
openssl1.1.1o can't run in android6.0，because openssl1.1.1o include unknow function "write_chk"

### ISSUE THREAD

**Issue by MouseSun846** [openssl/openssl#18478]
openssl1.1.1o can't run in android6.0，because openssl1.1.1o include unknow function "write_chk"

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__write_chk" referenced by

![image](https://user-images.githubusercontent.com/46400044/172082653-b9487bf4-1d51-4d9e-a807-17172ffacbc1.png)

**Comment by xtkoba** [comment]
`__write_chk` is introduced in Android API level 24. It is suggested that `__ANDROID_API__` be set properly. Example:

```bash
./Configure android-arm64 -D__ANDROID_API__=23
```

**Comment by MouseSun846** [comment]
Thank you very much!

**Comment by MouseSun846** [comment]
ok.
