### ISSUE TITLE
EVP_DigestSignFinal in OpenSSL 3.0 crashes if siglen is a null pointer

### ISSUE THREAD

**Issue by thkdev2** [openssl/openssl#18473]
EVP_DigestSignFinal in OpenSSL 3.0 crashes if siglen is a null pointer but sigret isn't a null pointer since commit https://github.com/openssl/openssl/commit/a4e01187d3648d9ce99507097400902cf21f9b55.

I'm not sure if it's allowed to do that since because the documentation isn't 100 % clear with this constellation.
Nevertheless it was used in our code before and worked for us as expected.
So I think either the documentation has to be clarified or the behavior should be changed to let it work again.

**Comment by davidben** [comment]
A NULL siglen doesn't make any sense. If sigret is non-NULL, siglen is an in/out parameter. It is necessary, on input, to specify the output buffer size. That, in turn, is necessary to avoid an out-of-bounds write in your application (security bug).

On output, it tells you the size of the signature. Skipping that is also ill-advised. You may know that a priori for an algorithm like RSA, but ECDSA typically uses a variable-length ASN.1 serialization. You won't know the size of the signature ahead of time.

I think this is also covered by the documentation, which says:

> If sig is not NULL then before the call the siglen parameter should contain the length of the sig buffer.

siglen == NULL cannot contain the length of the sig buffer.

**Comment by t8m** [comment]
> Nevertheless it was used in our code before and worked for us as expected.

That was simply a bug - yes, it might not crash but it should return error at least. It should NOT just blindly compute the signature and put it in a buffer of unknown length.

**Comment by thkdev2** [comment]
I agree that returning an error is a better solution than crashing.
But assuming the specified buffer length is correct is at least as uncertain as assuming the buffer is large enough when the parameter is NULL.
So I suggest keeping the old behavior or at least letting the provider decide.
For example, with SHA-1, the required buffer length is known before.
If you think that this isn't possible the documentation should be changed because "should contain the length of the sig buffer" means optional and not mandatory.

**Comment by thkdev2** [comment]
I mean HMAC-SHA1 and function EVP_DigestSignFinal.
And we already used a pointer to a sig_len variable because the function crashes otherwise.
In the meantime we don't use the function anymore because of the performance problems reported here: #17064.

> That's not what is happening. When the parameter is NULL, EVP_DigestSignFinal doesn't perform the operation at all. It merely tells you an upper bound on the output, if you don't know how to size the buffer. In effect, this is two functions jammed into one.

What you are writing here now is the behavior if the sig and not the sig_len parameter is NULL, see the documentation:
> Unless sig is NULL EVP_DigestSignFinal() signs the data in ctx and places the signature in sig. Otherwise the maximum necessary size of the output buffer is written to the siglen parameter.

Of course the maximum necessary size of the output buffer of the siglen parameter could only be written if sig_len is not NULL.
And even if sig is not NULL it is not necessary to use a non NULL sig_len parameter:
> If sig is not NULL then before the call the siglen parameter **should** contain the length of the sig buffer. If the call is successful the signature is written to sig and the amount of data written to siglen.
In this case, of course, the amount of data written cannot be returned.

That was how it worked before the change.

All I want now is to fix the new crash and either restore the old behavior or change the documentation.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
