### ISSUE TITLE
"openssl req" should accept -1 as "-days"

### ISSUE THREAD

**Issue by visweshn92** [openssl/openssl#18477]
Recent versions "openssl req" do not allow "-days" as -1:
 
```
openssl req -x509 -newkey rsa:2048 -days -1
req: Non-positive number "-1" for option -days
req: Use -help for summary.

```
It looks like "openssl req" does not take negative intergers

```
openssl req -help | grep '-days'
....
-days +int            Number of days cert is valid for
```

I believe the fix is following in apps/req.c

```
   - {"days", OPT_DAYS, 'p', "Number of days cert is valid for"},
    + {"days", OPT_DAYS, 'n', "Number of days cert is valid for"},
```

**Comment by t8m** [comment]
Setting expiration date in the past is not supported and there is no point in supporting that. Yes, it was possible to do it with 1.0.2.

**Comment by t8m** [comment]
Hmm, that seems more like a bug of x509 command to me although I do not think it should be changed on released branches.

**Comment by visweshn92** [comment]
@t8m Could you confirm if this is still "not a bug" after reading the previous update?

**Comment by t8m** [comment]
IMO there is no point. If you really need to create a testing certificate with expiration in the past you can use the x509 command.
