### ISSUE TITLE
Add salt length config for pkcs12 commad

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#18489]
> The current implement in PKCS12 command

1. The salt length could not setted by command

```
        if (maciter != -1)
            PKCS12_set_mac(p12, mpass, -1, NULL, 0, maciter, macmd);
```

2. the default length is 8 bytes

```
# define PKCS12_SALT_LEN 8
```

> The security required As per RFC7292

1. The security of Salt and the iteration was also refer NIST Special Publication 800-132 As per RFC7292
 ```
[4](https://datatracker.ietf.org/doc/html/rfc7292#section-4).  PFX PDU Syntax
The salt and (to a certain extent) the iteration count thwarts dictionary attacks against the integrity password.  See NIST Special Publication 800-132 [[12](https://datatracker.ietf.org/doc/html/rfc7292#ref-12)] about how to choose a reasonable value for the iteration count.
 ```
2. The salt shall be at least 128 bits(16 bytes) as define by  NIST SP 800-132
 ```
5.1 The Salt (S)
All or a portion of the salt shall be generated using an approved Random Bit Generator
(e.g., see [5]). The length of the randomly-generated portion of the salt shall be at least
128 bits. 
 ```

> Suggestion

1. Update the default length to 16

2. Add the salt length option in pkcs12 command.

**Comment by KanPlus** [comment]
If this Suggestion is fine, I will raise PR to fix, Please help check.

**Comment by t8m** [comment]
Please note that the PKCS12 password based key derivation function for the MAC is NOT the PBKDF2 algorithm which means even with the salt length of 16 the PKCS12 files will not be compliant with NIST SP 800-132.

Unfortunately the PKCS12 standard does not allow any other password based key derivation function for the MAC.

**Comment by t8m** [comment]
> PBKDF2 has a minimum salt length of 16 bytes.

Yes, but this is not a PBKDF2.

**Comment by KanPlus** [comment]
> > PBKDF2 has a minimum salt length of 16 bytes.
> 
> Yes, but this is not a PBKDF2.

Maybe this also required update to PBKDF2.
[Appendix B](https://datatracker.ietf.org/doc/html/rfc7292#appendix-B).  Deriving Keys and IVs from Passwords and Salt

   Note that this method for password privacy mode is not recommended
   and is deprecated for new usage.  The procedures and algorithms
   defined in PKCS #5 v2.1 [[13](https://datatracker.ietf.org/doc/html/rfc7292#ref-13)] [[22](https://datatracker.ietf.org/doc/html/rfc7292#ref-22)] should be used instead.
   Specifically, PBES2 should be used as encryption scheme, with PBKDF2
   as the key derivation function.

**Comment by t8m** [comment]
With PKCS12_set_mac() we are NOT talking about the password privacy mode but about the MAC! We are already using PBKDF2 with openssl-3.0 for the password privacy - i.e. the encryption of the key. However the MAC is still using the legacy key derivation because the standard does NOT provide a way to use PBKDF2 for it.

**Comment by KanPlus** [comment]
> With PKCS12_set_mac() we are NOT talking about the password privacy mode but about the MAC! We are already using PBKDF2 with openssl-3.0 for the password privacy - i.e. the encryption of the key. However the MAC is still using the legacy key derivation because the standard does NOT provide a way to use PBKDF2 for it.

Got it, the security of Salt and the iteration was also refer NIST Special Publication 800-132 As per RFC7292.
##Refer:
[4](https://datatracker.ietf.org/doc/html/rfc7292#section-4).  PFX PDU Syntax
The salt and (to a certain extent) the iteration count thwarts dictionary attacks against the integrity password.  See NIST Special Publication 800-132 [[12](https://datatracker.ietf.org/doc/html/rfc7292#ref-12)] about how to choose a reasonable value for the iteration count.
