### ISSUE TITLE
Wrong use of OSSL_PARAM_UTF8_STRING_PTR

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#18486]
In OpenSSL3 (master), provider sample code still contains references to `OSSL_PARAM_UTF8_STRING_PTR` instead of `OSSL_PARAM_UTF8_PTR`, e.g., https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_PROVIDER.pod#examples. Also the code doesn't compile because of a variable name typo.

Will provide PR if there's agreement this is an error.

**Comment by baentsch** [comment]
> There's also some instances here:

Thanks - fixing those too as part of #18490.

**Comment by faramir-dev** [comment]
I think this issue can be closed, `OSSL_PARAM_UTF8_STRING_PTR` has been replaced by `OSSL_PARAM_UTF8_PTR`.
