### ISSUE TITLE
While compairing the speedTest between openssl-1.1.1o vs openssl-1.1.1l on solaris64 Plateform.There is almost 100+ Ciphers for which there is degradation more than 5% .

### ISSUE THREAD

**Issue by 366anish** [openssl/openssl#18488]
1. Degradation reported with openssl-1.1.1o compair to openssl-1.1.1l.

**Comment by t8m** [comment]
Did you compile the sources with exactly the same options? Which concrete ciphers show the degradation? Is the degradation reproducible when averaging multiple runs?

**Comment by 366anish** [comment]
Yes , Sources compiled with same options. Some of  the Ciphers with degradation more than 13% are listed below -

1. md5_16   (-26%)
2.  sha384_16 (-19%)
4. sha224_16 (-19%)
5. md4_16 (-18%)
6. sha384_64 (-18%)
7. md5_64 (-16%)
8. seed-ofb_1024 (-16%)
9. seed-ofb_64 (-15%)
10. mdc2_16 (-15%)
11. sha512-224_64 (-15%)
12. aria-192-cfb_256
13. rc2-cfb_16
14. sha384_256
15. aria-256-cfb1_256
16. aria-192-cfb_1024
17. sha512-224_16
18. aria-256-ofb_1024
19. aria-256-ofb_8192
20. aria-256-ofb_16384

degradation is reproducible when averaging multiple runs. 
Also Performed the test on Isolated Machine.

**Comment by paulidale** [comment]
These figures are *not* the output from our `speed` command.
Could you please provide such output vs a baseline?

Several of these seem to be old obsolete ciphers & digests for which performance is not considered critical.

**Comment by t8m** [comment]
1.1.1 is out of support.
