### ISSUE TITLE
By when to provide PRs for inclusion in 3.1?

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#18500]
As I plan to submit further PRs for CMPv3 and likely also for some other new features,
are there already estimations when feature freeze is going to be?

**Comment by DDvO** [comment]
A very rough time estimation would be sufficient and helpful, e.g., "by next summer".

**Comment by DDvO** [comment]
Thanks Matt for answering. 
Good to know at least that, so far, there is no target date.

**Comment by mattcaswell** [comment]
An update on this. See item 6 in this [blog post](https://www.openssl.org/blog/blog/2022/09/21/OpenSSL-presentation-at-ICMC/).

> We shed some light on versioning to the OpenSSL releases that OMC agreed on.
>
> The OpenSSL 3.1 release will be about FIPS 140-3 validation submission
OpenSSL 3.1 will be the FIPS 140-3 submission release based on the current OpenSSL 3.0
>
> QUIC MVP release pushed to OpenSSL 3.2 release
> OpenSSL 3.1 was going to be the QUIC initial support release. We are pushing that to OpenSSL 3.2 (renaming the release). > This release is about a Minimal Viable Product (MVP) that provides a client-side, single stream (connection) only.

So 3.1 will be branched off 3.0. Current master will become 3.2

Still no date though.

**Comment by DDvO** [comment]
Thanks @mattcaswell for providing some news here and in https://github.com/openssl/openssl/pull/19025#issuecomment-1257799440, where you just wrote:

> New features go into the next "minor" release numbers, so 3.1 and 3.2. The current master branch is targeting 3.2. The 3.1 branch has not yet been created but will be taken from the existing 3.0 branch. We are only going to be allowing a very limited set of features to be merged there.

I'm a little surprised/confused by this. 
What is going to happen with those features that have been added to the `master` branch for the last 12 months - I hope that all these will go into 3.1?
And what you wrote seems to suggest that there is already de-facto feature freeze for 3.1? Or how are new features handled from now on - merge them to the master for inclusion into 3.2, while part of them might be ported to the new 3.1 branch?

**Comment by t8m** [comment]
Basically the plan to release the next version with the QUIC MVP support was changed to squeeze in another limited feature release in between that is based from 3.0 branch with a few selected PRs from master branch backported there.
All the rest will go into the 3.2 release which would have been the 3.1 release from the original plan.

See also: https://www.openssl.org/blog/blog/2022/09/21/OpenSSL-presentation-at-ICMC/

If you're concerned about when your PRs merged to master branch will be released - the introduction of the in-between 3.1 release does not move the expected time of the 3.2 release much as there will be no need for any extra effort spent on stabilization of the 3.1 release as it will contain only a few carefully selected feature patches.

**Comment by DDvO** [comment]
Thanks @t8m for your explanations.
With this change, we have to modify for more features recently added to `master` and  in existing PRs the references from version 3.1 to 3.2., in particular in `util/*.num` and the doc HISTORY sections.

**Comment by nhorman** [comment]
marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by DDvO** [comment]
This question is clearly outdated, so closing.
