### ISSUE TITLE
undefined reference to `engine_load_afalg_int'

### ISSUE THREAD

**Issue by lianglinhuan** [openssl/openssl#18505]
/usr/bin/ld: ./libcrypto.so: undefined reference to `engine_load_afalg_int'
/usr/bin/ld: ./libcrypto.so: undefined reference to `engine_load_padlock_int'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6460: apps/openssl] Error 1
make[1]: Leaving directory '/opt/openssl-1.1.1d'
make: *** [Makefile:174: all] Error 2

**Comment by lianglinhuan** [comment]
May I ask, why is Hui like this? How can I fix it.

**Comment by t8m** [comment]
How did you configure the build? What is the os/architecture/compiler where you're building it?

**Comment by lianglinhuan** [comment]
I am on the ubunut20.04 system in the gcc version 9.4.0 environment, using the source code to install, after downloading the tar package, unzip it, then ./config, make&&make install @t8m

**Comment by t8m** [comment]
> using the source code to install

Which tarball did you use? What release?

**Comment by t8m** [comment]
The 1.1.1d is quite old. Could you try the latest version from the 1.1.1 branch?

**Comment by lianglinhuan** [comment]
Thank you very much, I have completed the installation as you suggested
