### ISSUE TITLE
EVP_PKEY_derive() no longer accepts buffers larger than expected output

### ISSUE THREAD

**Issue by jeredfloyd** [openssl/openssl#18517]
Commit #6674 changed the behavior of EVP_PKEY_derive() to require the output buffer be the exact size of the output data, throwing KDF_R_WRONG_OUTPUT_BUFFER_SIZE if there is a mismatch.  This is a regression against OpenSSL 1.1 and can cause existing software to fail.

The documentation (https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_derive.html) still states:

>  If key is not NULL then before the call the keylen parameter should contain the length of the key buffer, if the call is successful the shared secret is written to key and the amount of data written to keylen.

However the code now says:

```
    if (prk_len != (size_t)EVP_MD_size(evp_md)) {
        KDFerr(KDF_F_HKDF_EXTRACT, KDF_R_WRONG_OUTPUT_BUFFER_SIZE);
        return 0;
    }

```

**Comment by mattcaswell** [comment]
This does seem to be a bug. For clarity this looks like HKDF only and the check in question looks a little different now to what it looked like when it was first introduced. The check is now here:

https://github.com/openssl/openssl/blob/5f4b3db624a83b812f23412e698ffd9c4284f87a/providers/implementations/kdfs/hkdf.c#L441-L448

Simply changing `!=` to `<=` would seem sufficient, although we should also have a test for this.

**Comment by jeredfloyd** [comment]
> Simply changing != to <= would seem sufficient, although we should also have a test for this.

Unfortunately, I do not believe this is sufficient.  The new signature for HKDF_derive() has prk_len as an in-variable only, and it is not (and cannot be) updated here to the actual output length.

**Comment by levitte** [comment]
@mattcaswell was unfortunately looking in the wrong place.  The KDF implementation "HKDF" is called with `EVP_KDF_derive()`, not `EVP_PKEY_derive()`, and the implementation is behaving correctly according to documentation:

> **EVP_KDF_derive()** processes any parameters in *Params* and then derives
> *keylen* bytes of key material and places it in the *key* buffer.  If the
> algorithm produces a fixed amount of output then an error will occur
> unless the *keylen* parameter is equal to that output size, as returned
> by *EVP_KDF_CTX_get_kdf_size()*

`EVP_PKEY_derive()` calls a KEX implementation, so the spot to look would be this:

https://github.com/openssl/openssl/blob/926c698c6f0a197e0322d4617db0ecd0d40f6e06/providers/implementations/exchange/kdf_exch.c#L91-L105

Notably, you do find a `EVP_KDF_derive()` call here...  but it seems that the code doesn't do enough to adapt the data to fit the requirements when calling `EPV_KDF_derive()`, so it ends up calling it with an `outlen` that's too large.

**Comment by levitte** [comment]
@jeredfloyd, would you mind testing the modification from #18533?

**Comment by jeredfloyd** [comment]
@levitte Thanks!  I'll try this patch against the RHEL 9 package and report back; if it works I will also submit it internally as a proposed backport.

**Comment by levitte** [comment]
@jeredfloyd, hold on...  that patch isn't quite right

**Comment by levitte** [comment]
I've added a test in a separate PR, #18536

**Comment by levitte** [comment]
> @jeredfloyd, hold on... that patch isn't quite right

I think I got it right now
