### ISSUE TITLE
Error message could use improvement

### ISSUE THREAD

**Issue by byrnejb** [openssl/openssl#1852]
CentOS-6.8 x86_64
OpenSSL 1.0.1e-fips 11 Feb 2013

We received this error message when attempting to sign a certificate.

OpenSSL Error 140128600782664:error:0E06D06C:configuration file
routines:NCONF_get_string:no value:conf_lib.c:335:group=TESTCA
name=email_in_dn

Much effort was expended in attempts to discover the cause
of this message.  We finally determined that this error message has nothing
to do with a configuration file error; or the presence or absence of
an email address in the certificate's DN; or anything else mentioned
in it.

The error message is triggered when attempting to sign a certificate
that has a DN identical to that of an existing certificate in the
index file 'index.txt' when the attribute 'unique_subject is set to
yes in 'index.txt.attr'.

It would be far more useful to give some indication of this
circumstance in the resulting error message in place of the generally
irrelevant and misleading details presently provided

**Comment by richsalz** [comment]
This looks to be fixed in the current source (see https://github.com/openssl/openssl/blob/master/apps/ca.c#L1624) and we're not changing any existing FIPS code.  So closing this.
