### ISSUE TITLE
Insufficient IPAddressFamily checking

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#18526]
Reported by @botovq:

Nothing checks that the data member of an `IPAddressFamily` contains a
BIT_STRING of length at most 3. Only `X509v3_addr_get_afi()` establishes
the lower bound of 2. In particular, `IPAddressFamily_cmp()` can compare too
short AFIs or take trailing garbage into account.

**Comment by grahamwoodward** [comment]
@mattcaswell can I look at fixing this please if it’s still open?

**Comment by levitte** [comment]
> @mattcaswell can I look at fixing this please if it’s still open?

The "help wanted" label is an indication that you can simply go ahead.  PR welcome!

**Comment by grahamwoodward** [comment]
How do I assign it to myself?

**Comment by grahamwoodward** [comment]
what am I doing wrong here...I'm trying to create a PR so I go to my fork of openssl but I only seemed to be able to open a new PR when I selected the openssl-3.0 and my master, but ended up with a PR with several 100 commits...[](https://github.com/openssl/openssl/pull/19272) presumably because my master is following the master branch, not the openssl-3.0. Not sure how I create the PR against the master branch and my new branch I've just created for this PR

**Comment by grahamwoodward** [comment]
I wonder whether I can just cap the `len` passed to the `memcmp` in IPAddressFamily_cmp() to 3?

**Comment by grahamwoodward** [comment]
Here's a couple of useful links for future reference that explain the AFI and SAFI

[AFI](https://www.iana.org/assignments/address-family-numbers/address-family-numbers.xhtml)
[SAFI](https://www.iana.org/assignments/safi-namespace/safi-namespace.xhtml )

**Comment by grahamwoodward** [comment]
@mattcaswell just out of interest why isn't there (well there isn't in the crypto/x509/v3_addr.c) a ...get_safi() function to return the 3rd octet?

**Comment by mattcaswell** [comment]
> @mattcaswell just out of interest why isn't there (well there isn't in the crypto/x509/v3_addr.c) a ...get_safi() function to return the 3rd octet?

Good question. I don't know. I guess no-one ever asked for it...

**Comment by botovq** [comment]
See also https://github.com/openssl/openssl/issues/18529

**Comment by grahamwoodward** [comment]
https://github.com/openssl/openssl/pull/19273

**Comment by preveen-stack** [comment]
@grahamwoodward can we mark this as closed, as the commit is already merged.
