### ISSUE TITLE
OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, settings) does not OPENSSL_INIT_LOAD_CRYPTO_STRINGS as it should

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#18535]
This is openssl-3.0.3 as of  commit
   47d8a1cb53e90 ("Change the SCT issuer key to RSA 2048")

I've been debugging testsuite failure of nodejs on mipsel, it passes on other architectures. On other architectures openssl initializes itself due a call to RAND_status().
This is missing on mipsel (for other reasons, not important) and it initializes itself via
   OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, settings);
and settings is not NULL. This leads to:

```
OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, settings)
 -> if (opts & OPENSSL_INIT_LOAD_CONFIG) {
    if (!loading) {
          CRYPTO_THREAD_set_local();
          CRYPTO_THREAD_write_lock(init_lock))
          ret = RUN_ONCE_ALT(&config, ossl_init_config_settings,
                             ossl_init_config);
          ->
                OPENSSL_init_crypto(OPENSSL_INIT_BASE_ONLY, NULL);
                -> ERR_set_mark()
                   ossl_err_get_state_int()

                   -> OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL);
                      if (!aloaddone)
                           if (!CRYPTO_atomic_load(&optsdone, &tmp, init_lock))

```
This means init_lock is RW lock then R which fails and as such the strings are not loaded.
The nodejs test suite fails because the error message is a "number" instead of the string expected.
Adding OPENSSL_INIT_LOAD_CRYPTO_STRINGS next to OPENSSL_INIT_LOAD_CONFIG works but I guess it would be nice if it would also work without it.

**Comment by t8m** [comment]
IMO we just need to avoid reusing the init_lock. See #18545.

**Comment by sebastianas** [comment]
This works, thank you.
