### ISSUE TITLE
How to integrate a custom TLS1_3 cipher into Openssl

### ISSUE THREAD

**Issue by quantropi-RYANTOTH** [openssl/openssl#18542]
Hello!

My OpenSSL version is: OpenSSL 1.1.1o  3 May 2022, Open Quantum Safe 2022-05 dev

I'm using the Open Quantum Safe fork, but I think my question applies more generally to OpenSSL.

Currently, I'm trying to integrate a custom symmetric cipher inside of the OpenSSL TLS1_3 protocol. My script to conduct this test is shown below (where `TLS_QEEP_256_CBC_SHA384` is the new cipher):

```
# Start a TLS1.3 test server based on OpenSSL accepting only the specified KEM_ALG
$OPENSSL_PATH s_server -cert $PERF_DIR/test/server.crt -key $PERF_DIR/test/server.key -curves $KEM_ALG -www -ciphersuites TLS_QEEP_256_CBC_SHA384 -accept localhost:4433&

# Give server time to come up first:
sleep 1

# Run handshakes for $TEST_TIME seconds
$OPENSSL_PATH s_time -curves $KEM_ALG -connect :4433 -new -time $TEST_TIME -verify 1 | grep connections
```

I've been following the tutorial to integrate a symmetric cipher referenced [here](https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher#EVP_Interface_Integration) and have ran a successful program that simply encrypts and decrypts using the new symmetric cipher. I've then attempted to make the necessary modifications to ADD my symmetric cipher to the list of TLS1_3 accepted ciphers.

However, I'm running into the following error when I run my script to test the new TLS1_3 cipher:

```
140415847070592:error:141B908A:SSL routines:tls13_setup_key_block:cipher or hash unavailable:ssl/tls13_enc.c:351:
ERROR
```

I've closely aligned my new cipher to the same structure as `TLS_AES_256_GCM_SHA384`, and have spent several hours trying to work through this issue.

Any suggestions or comments on how to move forward would be very appreciated. Thank you so much!

**Comment by beldmit** [comment]
You can try to use smth like that

https://github.com/gost-engine/engine/tree/ossl_patched/patches

These are patches adding Russian GOST ciphersuites to openssl 1.1.1 series, so I expect you will have to do smth similar

**Comment by mattcaswell** [comment]
Unfortunately you are way off the beaten track here. Adding a new TLSv1.3 cipher is not something for the faint-hearted. It is a non-trivial task.

In the case of this particular error did you add your cipher to `ssl_cipher_table_cipher`?

https://github.com/openssl/openssl/blob/d2399d8cd29f56e6614f0b3db4e7e563a745902a/ssl/ssl_ciph.c#L32-L58

Note by the way there are significant differences between 1.1.1 and 3.0 so if you ever want your code to run against 3.0 you will probably have significant rework to do.

**Comment by quantropi-RYANTOTH** [comment]
> Unfortunately you are way off the beaten track here. Adding a new TLSv1.3 cipher is not something for the faint-hearted. It is a non-trivial task.
> 
> In the case of this particular error did you add your cipher to `ssl_cipher_table_cipher`?
> 
> https://github.com/openssl/openssl/blob/d2399d8cd29f56e6614f0b3db4e7e563a745902a/ssl/ssl_ciph.c#L32-L58
> 
> Note by the way there are significant differences between 1.1.1 and 3.0 so if you ever want your code to run against 3.0 you will probably have significant rework to do.

Thanks for the quick reply. And yes, from what I can tell this integration looks difficult, but I am up for the challenge! 

My main goal is to _understand_ the integration process for adding a new cipher (I recognized that for OpenSSL 3.0 it will be different), and then make my new cipher compatible. 

My current implementation already had my cipher added to `ssl_cipher_table_cipher`, and I also incremented `SSL_ENC_NUM_IDX` to make room for it. I've tried to align my implementation of the new cipher very closely to `TLS_AES_256_GCM_SHA384`.  

Are you able to think of any other areas that might unblock this integration? Please let me know -- and I really appreciate your help and guidance.

**Comment by mattcaswell** [comment]
Ah....it appears to me that `TLS_QEEP_256_CBC_SHA384` does not look like an AEAD cipher? i.e. its based on CBC with HMAC? All existing TLSv1.3 ciphersuites are AEAD based - so there is no support in the current code for non AEAD TLSv1.3 ciphersuites.

**Comment by quantropi-RYANTOTH** [comment]
Ahhh ok that makes sense. I will look into making my cipher AEAD based. Thank you!
