### ISSUE TITLE
Fatal Decrypt Error

### ISSUE THREAD

**Issue by krisvamsi22** [openssl/openssl#1855]
Hello,

We have a very peculiar problem and needed help from this community. 

We are using an Embedded device, our Target Platform is MQX RTOS, Coldfire MCF54XX processor and Codewarrior IDE with SharkSSL TLS1.2 Webserver 

We are using a Cipher Suite TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256... Also we are using a Client Certificate for Client Authentication.

Now, the problem is,

SSL Handshake works with IE, Firefox and Safari browsers, but fails with Chrome with a fatal decrypt_error  After ServerHello, ServerCertificate, ClientCertificateRequest, ServerHelloDone (All sent in one packet) the client (Chrome Browser) returns this error.

After, some analysis we found that rest of the browsers and our dot net client uses different SSL stacks whereas Chrome uses OpenSSL, so the error was not from Chrome rather it was from OpenSSL.

Then we started reproducing command line openSSL and were able to reproduce same error, 

# openssl s_client -connect 192.168.0.138:443 -tls1_2 -cert certificate.cer -CAfile certificate.cer -msg 

# openssl pkcs12 -in cpoclientcertificate.pfx -out mycertificates.crt 

The result is that some times the command is able to connect to server, while some other times it fails with this error: 

<<< TLS 1.2 Handshake [length 0095], ServerKeyExchange 
    0c 00 00 91 03 00 17 41 04 e9 c7 c8 b4 2f ca 91 
    e0 3f ce af 6b 29 e7 b2 69 02 89 f1 9b 82 65 44 
    90 bf b0 bb ae 58 1f 3b ac c6 b2 46 d2 4a 67 6f 
    2f 8e 56 45 37 c3 4a 88 c2 01 09 90 77 96 cf fb 
    61 5d 6a 03 17 f2 ff ed 87 04 03 00 48 30 46 02 
    21 00 1c 85 7d 57 53 70 bd cf c2 66 e9 f3 ab 3a 
    db d7 b7 24 0e bd f8 89 45 09 df ac 50 c2 6d c0 
    02 f9 02 21 00 f6 72 eb 4f e0 a8 27 7e 71 10 c0 
    7c cc b0 1d ce d0 37 c1 a3 46 8b 74 a8 0f 81 2d 
    28 18 25 b8 b2 
>>> ??? [length 0005] 
    15 03 03 00 02 
>>> TLS 1.2 Alert [length 0002], fatal decrypt_error 
    02 33 
6280832:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:s3_clnt.c:1973: 

Which is the same error reported by Chromium. This seems to be a general issue with openssl

The version of openssl we've used to make these tests is 1.0.2d 

How other SSL stacks are able to communicate whereas only OpenSSL client throws an error, is there some thing specific to OpenSSL?

Another interesting point if we use RSA based encryption OpenSSL client also works, is there something specific to ECDSA?

Please help

Regards,
Vamsi

**Comment by kroeckx** [comment]
This is most likely an issue in SharkSSL, not OpenSSL.

The difference between all the browsers you mention and OpenSSL and Chrome is that OpenSSL and Chrome have sha512 as the first in the list of signature algorithms and that the others have sha256.

**Comment by krisvamsi22** [comment]
Thank you for the comment...

Little confusing though. If the issue with SharkSSL how it works fine with other Browsers? Also how Chrome works fine when used with RSA. The failure happens only with ECDSA. 

In what scenarios  routines ssl3_get_key_exchange from s3_clnt.c may fail? 

Need a help here...

**Comment by kroeckx** [comment]
The error message also says "bad signature", and the file/line info points to place where the signature is checked.

Like I explained before, the other browsers are using ECDSA/sha256, while OpenSSL and Chrome are using ECDSA/sha512.

I think it's highly unlikely that there would be a bug in OpenSSL and Chrome related to this, since this is just used too much. The only thing here that doesn't look standard is SharkSSL.

I have no idea why RSA would work.

**Comment by davidben** [comment]
ECDSA with hashes larger than the curve truncates the hash, which is an odd corner case. I would not be surprised if SharkSSL got that wrong.

Chrome actually uses BoringSSL, not OpenSSL, but we're similar enough. Although a future version of Chrome will be revising our signature algorithms list to prefer SHA-256 over SHA-512 anyway. But SharkSSL is still probably buggy. Please report a bug with them.

**Comment by sanggil** [comment]
Hi krisvamsi22 ,
Have you solved the this issue?
Our server is also using ECDSA/SHA386 and client get error code "SSL3 alert write:fatal:decrypt error"(1408D07B) during TLS handshake process.
And sometime connection is ok like you.
If you possible, Could you share the way you've fixed it ?

**Comment by krisvamsi22** [comment]
Hi,

Are you also using SharkSSL?

Yes we solved the problem upgrading to latest version of SharkSSL as there
were multiple fixes in the area of ECDSA in SharkSSL, we are not sure what
solved this issue exactly, however this concludes that it was neither a bug
with OpenSSL nor with Chrome.

I strongly agree with David Benjamin that "ECDSA with hashes larger than
the curve truncates the hash, which is an odd corner case. I would not be
surprised if SharkSSL got that wrong." so my opinion this could be one of
the fix done on SharkSSL which could have resolved the issue.

Please check around this area, probably may help,

Vamsi

**Comment by mattcaswell** [comment]
Since you solved this, we should probably close this issue.

**Comment by sanggil** [comment]
Thank you for information.
Can I ask one more?
SharkSSL you updated is for server side or client side?

**Comment by krisvamsi22** [comment]
Server side...

**Comment by sanggil** [comment]
Thank you a lot
It is a great help to us
