### ISSUE TITLE
Android build failed with Latest LTS Version (r23c) NDK

### ISSUE THREAD

**Issue by wangyoucao577** [openssl/openssl#18560]
Build for android failed with [Latest LTS Version (r23c) NDK](https://developer.android.com/ndk/downloads#lts-downloads). Full output as following:         

```bash
$ export ANDROID_NDK_ROOT=/root/Android/Sdk/ndk/23.2.8568313
$ ./Configure no-tests -D__ANDROID_API__=21 android-arm64
Configuring OpenSSL version 3.0.3 for target android-arm64
Using os-specific seed configuration

Failure!  build file wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

no NDK aarch64-linux-android-gcc on $PATH at (eval 10) line 142.
```

With `export ANDROID_NDK_ROOT=/root/Android/Sdk/ndk/21.4.7075529`, build works correct!         

OpenSSL version:  tag `openssl-3.0.3`

**Comment by mattcaswell** [comment]
Did you also adjust your `$PATH` as described here:

https://github.com/openssl/openssl/blob/openssl-3.0/NOTES-ANDROID.md

**Comment by wangyoucao577** [comment]
You're right, I forgot to reset `export PATH=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH` after switch `ANDROID_NDK_ROOT`. Thanks!
