### ISSUE TITLE
Cross compiling openssl3.0, there are some errors when running on ARM platform

### ISSUE THREAD

**Issue by XYQ202** [openssl/openssl#18569]
hello，openssl  team
       I cross-compiled openssl3.0 on ubuntu, the compilation process:
        1. ./Configure linux-armv4 --cross-compile-prefix=arm-himix200-linux- --prefix=/data/work/openssl_instasll
        2. make
        3. sudo make install
        I need to use the openssl tool on the 32-bit ARM platform, so the target of cross-compilation is the 32-bit ARM platform, the compilation is passed, and then the openssl binary under the bin file is ported to the ARM platform and the dynamic library under the lib library is ported to the ARM platform, I can run openssl applications like openss help, but when I want to generate RSA keys, I get an error, as follows:
       root@au:~# openssl genrsa -out cl_key.pem
        genrsa: Error generating RSA key
        What is the reason for this?

        I cross-compiled 64-bit openssl3.0, ported it to 64-bit ARM platform, I can use openssl tools normally, and can generate RSA keys normally, etc.

**Comment by paulidale** [comment]
This really is not a lot to go on.  Can you provide anything further?

Try setting a break point in `EVP_PKEY_keygen` and stepping through to find out what fails?

**Comment by xieyunquan** [comment]
> This really is not a lot to go on. Can you provide anything further?
> 
> Try setting a break point in `EVP_PKEY_keygen` and stepping through to find out what fails?
> 
> If you are only after the openssl tool, have you tried a static build?

I just cross-compile openssl3.0, and then transplant the generated bin file and lib library file to the corresponding directory of the ARM platform. I can run commands such as openssl version or openssl help, but I want to generate an RSA private key, but it cannot be generated.
I don't quite understand what you mean. The 32-bit ARM platform has insufficient performance to generate RSA private keys.
Where is EVP_PKEY_keygen and how to do it

**Comment by paulidale** [comment]
Do you have a debugger on the 32-bit ARM platform?  Can you use it to set breakpoints in the executable?  EVP_PKEY_keygen() is the function that generates an RSA key in OpenSSL, it is failing for reasons that are not possible to determine at this stage.

The reason for trying a static build is to remove all dependencies on shared libraries.  Getting the shared library installation incorrect is very easy, this would indicate if it is the problem or not.

**Comment by xtkoba** [comment]
`strace` may give us some clues as well:

```bash
strace openssl genrsa -out cl_key.pem 2> stderr.log
```

**Comment by xieyunquan** [comment]
> Do you have a debugger on the 32-bit ARM platform? Can you use it to set breakpoints in the executable? EVP_PKEY_keygen() is the function that generates an RSA key in OpenSSL, it is failing for reasons that are not possible to determine at this stage.
> 
> The reason for trying a static build is to remove all dependencies on shared libraries. Getting the shared library installation incorrect is very easy, this would indicate if it is the problem or not.

I don't know what static build is, can you provide a method

**Comment by paulidale** [comment]
Configure with the `no-shared` option.

**Comment by xieyunquan** [comment]
> Configure with the `no-shared` option.

![Uploading image.png…]()
![16552837006232](https://user-images.githubusercontent.com/97773232/173788447-c8847af2-2588-419e-9a0f-7039eaf3db32.png)

Tried many ways, still can't solve

**Comment by xieyunquan** [comment]
> Did you try configuring with `no-asm`? We would need a debug build and running the command in the debugger to see where the error is generated, unfortunately we cannot help you without more information provided.

Thanks, I tried no-asm, but it still fails. What information do I need to provide? i can provide it to you。

**Comment by xieyunquan** [comment]
> Did you try configuring with `no-asm`? We would need a debug build and running the command in the debugger to see where the error is generated, unfortunately we cannot help you without more information provided.

But why does the 64-bit ARM platform work fine？

**Comment by xieyunquan** [comment]
> Do you have a debugger on the 32-bit ARM platform? Can you use it to set breakpoints in the executable? EVP_PKEY_keygen() is the function that generates an RSA key in OpenSSL, it is failing for reasons that are not possible to determine at this stage.
> 
> The reason for trying a static build is to remove all dependencies on shared libraries. Getting the shared library installation incorrect is very easy, this would indicate if it is the problem or not.

Thanks, I don't have tools to debug online, I can only see by printing the information:
1.
![image](https://user-images.githubusercontent.com/97773232/174059329-a3614a73-b301-4bdf-a726-8bb809233ac7.png)

2. 
![image](https://user-images.githubusercontent.com/97773232/174059252-20176e1c-9737-4893-8596-6fa2510eaf6f.png)
 
 into this function
3. 
![image](https://user-images.githubusercontent.com/97773232/174059461-fdb5569c-2725-4ffa-aff7-48b66b64e7c8.png)
 
The value of ret is modified here, resulting in an RSA private key error。

**Comment by t8m** [comment]
The execution should eventually reach the ossl_rsa_fips186_4_gen_prob_primes() function in rsa_sp800_56b_gen.c. You can try to look where it errors out. You can also call `ERR_print_errors_fp(stderr)` to print out the error stack. Unfortunately without a debugger it would be very hard to find out what's happening.

**Comment by XYQ202** [comment]
> Configure with `--debug` even if you do not have access to debuggers. IIRC this sets the compiler optimization level as `-O0`. It is not uncommon that a code is miscompiled with some compiler optimizations due to bugs in either the compiler or the code. Alternatively you can explicitly specify `-O0` as the optimization level.
> 
> The target `arm-himix200-linux` is obscure to me but googling that target name I find some information about the toolchain, indicating that the GCC version is 6.3.0, which is fairly old.
> 
> FYI, this issue does not reproduce on Android (with Android NDK r24) nor user-space emulated Gentoo musl environment (with GCC 11.3.0), implying that this is difficult to reproduce without access to the toolchain for `arm-himix200-linux`.

The cross compiler I use is arm-xilinx-linux-gnueabi-gcc
The gcc version is 4.9.2, I guess the bottom layer of my ARM platform does not support openssl3.0。

**Comment by XYQ202** [comment]
> The execution should eventually reach the ossl_rsa_fips186_4_gen_prob_primes() function in rsa_sp800_56b_gen.c. You can try to look where it errors out. You can also call `ERR_print_errors_fp(stderr)` to print out the error stack. Unfortunately without a debugger it would be very hard to find out what's happening.

thanks，This error has not yet been executed in the rsa_sp800_56b_gen.c file. It has failed in the app_keygen function. The app_keygen function is called in the genrsa_main function. If it fails, the RSA private key will not be generated.

**Comment by XYQ202** [comment]
> 



> Configure with `--debug` even if you do not have access to debuggers. IIRC this sets the compiler optimization level as `-O0`. It is not uncommon that a code is miscompiled with some compiler optimizations due to bugs in either the compiler or the code. Alternatively you can explicitly specify `-O0` as the optimization level.
> 
> The target `arm-himix200-linux` is obscure to me but googling that target name I find some information about the toolchain, indicating that the GCC version is 6.3.0, which is fairly old.
> 
> FYI, this issue does not reproduce on Android (with Android NDK r24) nor user-space emulated Gentoo musl environment (with GCC 11.3.0), implying that this is difficult to reproduce without access to the toolchain for `arm-himix200-linux`.

Because I cross-compile openssl1.0.0 and port it to the 32-bit ARM platform, functions such as RSA private keys can be generated normally. So it should be that the openssl version configured in the bottom layer can only be openssl1.0, and the openssl3.0 version is too high to support

**Comment by t8m** [comment]
> This error has not yet been executed in the rsa_sp800_56b_gen.c file. It has failed in the app_keygen function.

This does not make much sense to me. The output as you printscreened above shows that some generation is being performed but then it fails.
Do you see the execution reaching rsa_gen() in rsa_keymgmt.c?
Then it should reach RSA_generate_multi_prime_key() function and from that into the rsa_keygen() function in rsa_gen.c.

Do you possibly have some openssl engine in place?

**Comment by XYQ202** [comment]
> > This error has not yet been executed in the rsa_sp800_56b_gen.c file. It has failed in the app_keygen function.
> 
> This does not make much sense to me. The output as you printscreened above shows that some generation is being performed but then it fails. Do you see the execution reaching rsa_gen() in rsa_keymgmt.c? Then it should reach RSA_generate_multi_prime_key() function and from that into the rsa_keygen() function in rsa_gen.c.
> 
> Do you possibly have some openssl engine in place?

Thank you, there should be some problems with the ARM platform

**Comment by XYQ202** [comment]
> Thanks, it's resolved. When cross-compiling openssl3.0, after configuration, you need to modify the compilation optimization level in the Makefile. The default is -O3, modify it to -O0 to succeed.
> Excuse me, can you simulate cmp server in openssl3.0?

Thanks, it's resolved. When cross-compiling openssl3.0, after configuration, you need to modify the compilation optimization level in the Makefile. The default is -O3, modify it to -O0 to succeed.
Excuse me, can you simulate cmp server in openssl3.0?

**Comment by XYQ202** [comment]
> 

Thanks, it's resolved. When cross-compiling openssl3.0, after configuration, you need to modify the compilation optimization level in the Makefile. The default is -O3, modify it to -O0 to succeed.
Excuse me, can you simulate cmp server in openssl3.0?

**Comment by DDvO** [comment]
> > Thanks, it's resolved. [...] modify the compilation optimization level in the Makefile. The default is -O3, modify it to -O0 to succeed
> 
> That's a workaround, not a resolution, to anything from a compiler bug to a bug in an assembler implementation :(

Yes, and either the error can be fixed (preferred) or at least some diagnostics/warning should be given that the workaround is needed and why.

**Comment by slontis** [comment]
Just looking at the sequence of the output '.+*' you can get a general idea of where it failed...
Inside ossl_bn_rsa_fips186_4_gen_prob_primes() it has got past the 2 calls to bn_rsa_fips186_4_find_aux_prob_prime()
since each call to this function will  output a sequence of [. 65{+}]* (it gets 65 pluses and a * when is_prime passes).

So it must be hitting an error inside ossl_bn_rsa_fips186_4_derive_prime()

**Comment by t8m** [comment]
Could you please try a recent snapshot? There was the fix in #22272 committed, that could possibly fix the issue.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
