### ISSUE TITLE
Openssl version 3.0.4 release dat

### ISSUE THREAD

**Issue by manonver121** [openssl/openssl#18562]
Hi
Could you please share the release date for openssl version 3.0.4 ?
I am facing this issue (https://github.com/openssl/openssl/issues/18468) with both centos7 and rocky linux8 
Thanks.

**Comment by mattcaswell** [comment]
Release date for 3.0.4/1.1.1p has been set as 21st June 2022.

**Comment by manonver121** [comment]
Thanks @mattcaswell

**Comment by manonver121** [comment]
Hi @mattcaswell 
Openssl 3.0.4 is not yet release, could you please share the plan ?
Thanks
