### ISSUE TITLE
x509/v3_purp.c: timestamping: questionable check of certificate purpose

### ISSUE THREAD

**Issue by ljaenicke** [openssl/openssl#18580]
The code verifying the certificate purpose for timestamping (crypto/x509/v3_purp.c: check_purpose_timestamp_sign()) says and implements
````
    /*
     * Check the optional key usage field:
     * if Key Usage is present, it must be one of digitalSignature
     * and/or nonRepudiation (other values are not consistent and shall
     * be rejected).
     */
````
The specification in the CA browser forum however says:
> keyUsage (required)
> This extension MUST be present and MUST be marked critical. The bit positions for 
> digitalSignature MUST be set. Bit positions for keyCertSign and cRLSign MUST NOT be set. 
> All other bit positions SHOULD NOT be set.

Updating the check would not be difficult (there don't seem to be tests anyway) but might risk effects on applications in the wild that do not follow the strict policy as in CAB forum (like in homegrown, for example).

**Comment by ljaenicke** [comment]
RFC 3161 (published in 2001) does not make any statement wrt the Key Usage extension and only addresses the Extended Key Usage in Section 2.3. Identification of the TSA:
"  ... The
   corresponding certificate MUST contain only one instance of the
   extended key usage field extension as defined in [RFC2459] Section
   4.2.1.13 with KeyPurposeID having value:

   id-kp-timeStamping.  This extension MUST be critical."

**Comment by mattcaswell** [comment]
This doesn't seem to be a bug to me - but more a case of which standards do you want to follow. The CA browser forum is targeted towards browser usage - but OpenSSL is used in more contexts than that. RFC 5280 says:

  "Conforming CAs MUST include this extension in certificates that
   contain public keys that are used to validate digital signatures on
   other public key certificates or CRLs.  When present, conforming CAs
   SHOULD mark this extension as critical."

This definitely leaves open the possibility of the extension not being present.

> Updating the check would not be difficult (there don't seem to be tests anyway) but might risk effects on applications in the wild that do not follow the strict policy as in CAB forum (like in homegrown, for example).

Right - this is a problem.

**Comment by t8m** [comment]
We follow RFC 5280 (and in some cases only with the strict check enabled). IMO the CAB requirements are in many cases too strict for openssl.

**Comment by ljaenicke** [comment]
ETSI EN 319 422 V1.1.1 (2016-03) states:
"The TSU certificate extended key usage setting shall be as defined in IETF RFC 3161 [1], clause 2.3."
which means there is no special requirement how key usage should be handled.

**Comment by t8m** [comment]
I would simply close this as notabug unless there is some strong argument that we should change this check.

**Comment by ljaenicke** [comment]
Can be closed as notabug. Nevertheless, I have added test cases for the behavior discussed in a pull request.

**Comment by mattcaswell** [comment]
Closing.
