### ISSUE TITLE
Enhancement: openssl-x509(1) fingerprinting of public keys

### ISSUE THREAD

**Issue by aaronmdjones** [openssl/openssl#1858]
Some programs and specifications use fingerprints of public keys only (i.e. the SubjectPublicKeyInfo structure), such as DANE.

At the moment, to calculate the fingerprint of a public key given a certificate, one has to do

` $ openssl x509 -pubkey -noout < foo.crt | grep -v 'PUBLIC KEY' | base64 -d | sha256sum`

The issue is that if you give the `-pubkey` argument, it ignores any `-outform` argument and always outputs PEM.

I have 2 enhancement suggestions:

1) Respect `-outform`. This would simplify the above to:
` $ openssl x509 -outform DER -pubkey -noout < foo.crt | sha256sum`

2) Fingerprint the public key only if `-fingerprint` and `-pubkey` are both given. This would simplify even further:
` $ openssl x509 -sha256 -fingerprint -pubkey -noout < foo.crt`

**Comment by vdukhovni** [comment]
The second "-fingerprint" suggestion breaks the expected interface.  As for outform DER for pubkey, that'd be a problem if any other output requested.  Instead use a better crafted recipe:

```
$ tlsa311() {
      cat |
      openssl x509 -noout -pubkey |
      openssl pkey -pubin -outform DER |
      openssl dgst -sha256 -binary |
      hexdump -ve '/1 "%02X"' # no trailing NL
   }
$ dgst=$(tlsa311 mail-cert.pem)
$ echo $dgst
5E078B3160569F165A69EB860395BBBDC7576C3603C3452B07139C276B26D01C
```


[tlsagen.txt](https://github.com/openssl/openssl/files/573509/tlsagen.txt)
[chaingen.txt](https://github.com/openssl/openssl/files/573508/chaingen.txt)
(Taken from my "tlsagen" and "chaingen" bash scripts, attached))
