### ISSUE TITLE
How was this problem finally solved? I also have this problem at present.

### ISSUE THREAD

**Issue by MouseSun846** [openssl/openssl#18589]
Hi - I think you can probably close this.
I think the issue is that we are running binaries built on a newer OS on a server with an older OS and we were getting away with it for some reason until OpenSSL 1.1.1n was released.
The server I'm building on is

```
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```

- I rebuilt our binary with OpenSSL at 1.1.1m and copied it to the problem server
- I ran the test that causes the crash and it worked fine
- I rebuilt the binary with OpenSSL 1.1.1n built **with the -g option** and copied it to the problem server
- I ran the test that causes the crash and it worked fine
- I rebuilt the binary with standard OpenSSL 1.1.1n and copied it to the problem server
- I ran the test and I get the crash 
- I can see the dynamic symbol ( I missed this previously because we daemonise our binary )

```mac-mini-11:acctests-sl build$ ../build/rttpd -r ./ -v
Reading config file /Users/build/workspace/CDev-SL4C-Git-develop-osx/rttpd/acctests-sl/etc/rttpd.conf
Reading config file /Users/build/workspace/CDev-SL4C-Git-develop-osx/rttpd/acctests-sl/etc/fields.conf
Reading config file /Users/build/workspace/CDev-SL4C-Git-develop-osx/rttpd/acctests-sl/etc/license-rttpd.conf
Reading config file /Users/build/workspace/CDev-SL4C-Git-develop-osx/rttpd/acctests-sl/etc/openauth.conf
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/build/workspace/CDev-SL4C-Git-develop-osx/rttpd/acctests-sl/../build/rttpd
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/build/workspace/CDev-SL4C-Git-develop-osx/rttpd/acctests-sl/../build/rttpd
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6 (core dumped)
```

This same test with this same binary works fine if everything runs on the server it was built on.

It looked like an OpenSSL issue because it happened when we upgraded. It is a bit odd that the issue goes away with 1.1.1m or 1.1.1n built with -g.

_Originally posted by @andysCaplin in https://github.com/openssl/openssl/issues/18192#issuecomment-1112069980_

**Comment by xtkoba** [comment]
You have to set the deployment target properly. See also https://developer.apple.com/forums/thread/680395.

**Comment by MouseSun846** [comment]
ok! Thanks for you.
