### ISSUE TITLE
Unusual test flakiness

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#18594]
Recently the GH action tests started to behave really erratically. I strongly suspect the GH Action runners to be the culprits and not bugs in the code but it still might be worth investigating.

See for example:

https://github.com/openssl/openssl/runs/6927836907?check_suite_focus=true
Many tests randomly fail here.

https://github.com/openssl/openssl/runs/6933235443?check_suite_focus=true
Here it looks like just the RSA is not refcounted properly.

https://github.com/openssl/openssl/runs/6933375241?check_suite_focus=true
Again many random test failures here.

**Comment by beldmit** [comment]
I had some suspicions about my changes in case 1 and 3, but there were failures in tests that cant' be affected (e.g. req)

**Comment by bernd-edlinger** [comment]
I saw something similar when in the CI run of 6d702cebfce3ffd9d8c0cb2af80a987d3288e7a3:

https://github.com/openssl/openssl/runs/6919246064?check_suite_focus=true

```
crypto/property/defn_cache.c:117: OpenSSL internal error: Assertion failed: old == NULL
../../util/wrap.pl ../../test/threadstest -config /home/runner/work/openssl/openssl/test/default.cnf ../../test/recipes/90-test_threads_data => 134
not ok 1 - running test_threads
```

My guess would be a weak bit in the DDR RAM banks of one of the servers.

**Comment by paulidale** [comment]
We do run some asan tests.  They are too slow to run lots.
