### ISSUE TITLE
Config file can't be found / specified on Windows

### ISSUE THREAD

**Issue by CoDEmanX** [openssl/openssl#186]
Did no dev ever test openssl on windows?
I doesn't find the config file, because it looks in `/etc/ssl/openssl.cnf`.

The command line parameter `-config` is ignored, what works is an environment variable, which is really tricky to set up on Windows 8 however (you need to locate `explorer.exe`, run with elevated rights, switch over to control panel and go to system settings > advanced).

**Comment by nick599** [comment]
@codemanx is the config file still missing on Win 8?

**Comment by CoDEmanX** [comment]
It wasn't ever missing, there is either an `openssl.cnf` or `openssl.cfg` file in the bin folder. The problem I reported is about OpenSSL looking in the wrong directory - `/etc/ssl/openssl.cnf` is a Linux path, it won't work on Windows.

**Comment by levitte** [comment]
That's also an installation directory, while you're talking about a bin directory... Did you build it yourself or did you install a ready made package? If the latter, you need to talk with whoever made that package.

**Comment by nick599** [comment]
@CoDEmanX what code and filename and location is the reference to /etc/ssl/openssl.cnf ?

**Comment by mattcaswell** [comment]
No response from OP to @levitte's questions. Closing this. Please reopen if this is still an issue.
