### ISSUE TITLE
How to use openssl-cmp function on openssl1.1.0

### ISSUE THREAD

**Issue by XYQ202** [openssl/openssl#18603]
hello, since openssl3.0 can't use the features of openssl-cmp on my 32bit ARM platform, I now found your fork of CMP https://github.com/mpeylo/cmpossl/tree/cmp
Can you help me, how do I use openssl1.1.0 version, I checked README.md to support openssl1.1.0 version, but I compiled libcmp dynamic library, but how to use openssl1.1.0 on openssl- what about cmp?

**Comment by t8m** [comment]
There is unfortunately no CMP implementation in openssl-1.1.0 if this is the question you're asking.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
