### ISSUE TITLE
1.1.1n compile failed with android ndk r23b

### ISSUE THREAD

**Issue by remarklx** [openssl/openssl#18617]
![image](https://user-images.githubusercontent.com/38095601/174779856-3b8fd4ba-5bc2-4d60-87b9-3ecef7cef1f4.png)
(architecture: android-arm  failed on WSL)

![image](https://user-images.githubusercontent.com/38095601/174798875-3152ed92-4937-444d-8861-bf1b14bc428b.png)
(architecture: android-arm64  failed on Linux)

works with  r22, r20. but failed with r23. 
don't konw why.....

there is a commit for r22 version iguessthislldo:igtd/android-ndk-r22-beta1
maybe need r23 solution

**Comment by xtkoba** [comment]
This does not happen to me. I'm using Android NDK r23c but it should not matter here.

```
$ export ANDROID_NDK_HOME=/usr/local/opt/android-ndk-r23c
$ PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
$ ./Configure android-arm -D__ANDROID_API__=21
Configuring OpenSSL version 1.1.1n (0x101010efL) for android-arm
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
$ make
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _all
make[1]: Entering directory '/var/tmp/openssl-1.1.1n'
make[1]: Leaving directory '/var/tmp/openssl-1.1.1n'
make[1]: Entering directory '/var/tmp/openssl-1.1.1n'
armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
In file included from <built-in>:371:
<command line>:18:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
        ^
<built-in>:364:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -MMD -MF apps/apps.d.tmp -MT apps/apps.o -c -o apps/apps.o apps/apps.c
[...]
```

**Comment by xtkoba** [comment]
The error message

```
clang-12: error: no input files
```

reminds me of #18454.

Are your `ANDROID_NDK_HOME` and `PATH` correctly set?

**Comment by remarklx** [comment]
> 


> This does not happen to me. I'm using Android NDK r23c but it should not matter here.
> 
> ```
> $ export ANDROID_NDK_HOME=/usr/local/opt/android-ndk-r23c
> $ PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
> $ ./Configure android-arm -D__ANDROID_API__=21
> Configuring OpenSSL version 1.1.1n (0x101010efL) for android-arm
> Using os-specific seed configuration
> Creating configdata.pm
> Creating Makefile
> 
> **********************************************************************
> ***                                                                ***
> ***   OpenSSL has been successfully configured                     ***
> ***                                                                ***
> ***   If you encounter a problem while building, please open an    ***
> ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
> ***   and include the output from the following command:           ***
> ***                                                                ***
> ***       perl configdata.pm --dump                                ***
> ***                                                                ***
> ***   (If you are new to OpenSSL, you might want to consult the    ***
> ***   'Troubleshooting' section in the INSTALL file first)         ***
> ***                                                                ***
> **********************************************************************
> $ make
> /usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
>     "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
> /usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
>     "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
> /usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
>     "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
> make depend && make _all
> make[1]: Entering directory '/var/tmp/openssl-1.1.1n'
> make[1]: Leaving directory '/var/tmp/openssl-1.1.1n'
> make[1]: Entering directory '/var/tmp/openssl-1.1.1n'
> armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
> In file included from <built-in>:371:
> <command line>:18:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
> #define __ANDROID_API__ 21
>         ^
> <built-in>:364:9: note: previous definition is here
> #define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
>         ^
> 1 warning generated.
> armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -MMD -MF apps/apps.d.tmp -MT apps/apps.o -c -o apps/apps.o apps/apps.c
> [...]
> ```

Thanks a lot for you for showing it can work with r23 which is very important to me! And it is amazing when I use real linux machine to compile it insead of WSL. Everything is correct just as what you show.  Thank you again : )

**Comment by remarklx** [comment]
> 

![image](https://user-images.githubusercontent.com/38095601/174798875-3152ed92-4937-444d-8861-bf1b14bc428b.png)
@xtkoba  Oh no! I failed when I choose x64
$ ./Configure android-arm64 -D__ANDROID_API__=21
Can you compile with android-arm64 configure

**Comment by xtkoba** [comment]
Do

```bash
make distclean
```
