### ISSUE TITLE
Too many files added to fips.module.sources

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#18618]
The recent 3.0.4 release added a significant number of header files to fips.module.sources:

https://github.com/openssl/openssl/commit/7d4c4e3113197bbcac7952e4494944a046b66a92

This doesn't seem right. Those header files should probably only be included conditionally, i.e. inside `#ifndef FIPS_MODULE`

**Comment by t8m** [comment]
I'll investigate. I suppose one of the recent changes pulled in some header that gave this cascading fallout.
