### ISSUE TITLE
1.1.1p Fails on NonStop - Looping in BN

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#18620]
Our test process for 10-test_bn went into a hard loop for all builds. This has not happened in prior versions. 3.0.4 is fine, as is 1.1.1o. For 10-test_bn, while in the hard loop, the stack is corrupt.

The other tests that also fail, but without the stack corruption are:
* 30-test_evp_extra
* 70-test_verify_extra
* 80-test_dane
* 80-test_ssl_new
* 80-test_ssl_old
* 90-test_sslapi

It is curious that this is virtually the same set of tests that fail at 3.1 but not 3.0 on this platform. I need some assistance tracking down why this patch is causing such an issue.

**Comment by mspncp** [comment]
My guess is that the loop is caused by one of the commits 0ed27fb7a8  and 8438d3a7b7. Would you mind to check whether that's correct and which one of the two commits causes the problem?


```
~/src/openssl/1.1.1$ git log --oneline --stat OpenSSL_1_1_1o..OpenSSL_1_1_1p -- crypto/bn
a3fc812c0c (OpenSSL_1_1_1-stable) Update copyright year
 crypto/bn/asm/x86_64-mont5.pl | 2 +-
 crypto/bn/rsaz_exp.c          | 2 +-
 crypto/bn/rsaz_exp.h          | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)

8438d3a7b7 Add an extra reduction step to RSAZ mod_exp implementations
 crypto/bn/rsaz_exp.c |  8 ++++++++
 crypto/bn/rsaz_exp.h | 23 +++++++++++++++++++++++
 2 files changed, 31 insertions(+)

0ed27fb7a8 Always end BN_mod_exp_mont_consttime with normal Montgomery reduction.
 crypto/bn/asm/x86_64-mont5.pl | 196 ----------------------------------------------------------------------------------
 crypto/bn/bn_exp.c            |  44 +++++++++++--------
 2 files changed, 26 insertions(+), 214 deletions(-)
```

**Comment by rsbeckerca** [comment]
> My guess is that the loop is caused by one of the commits [0ed27fb](https://github.com/openssl/openssl/commit/0ed27fb7a8d85685cb671bf0a1e41bcdfc2624dc) and [8438d3a](https://github.com/openssl/openssl/commit/8438d3a7b7309cbea521d3628fddeda7bd6d6e20). Would you mind to check whether that's correct and which one of the two commits causes the problem?
> 
> ```
> ~/src/openssl/1.1.1$ git log --oneline --stat OpenSSL_1_1_1o..OpenSSL_1_1_1p -- crypto/bn
> a3fc812c0c (OpenSSL_1_1_1-stable) Update copyright year
>  crypto/bn/asm/x86_64-mont5.pl | 2 +-
>  crypto/bn/rsaz_exp.c          | 2 +-
>  crypto/bn/rsaz_exp.h          | 2 +-
>  3 files changed, 3 insertions(+), 3 deletions(-)
> 
> 8438d3a7b7 Add an extra reduction step to RSAZ mod_exp implementations
>  crypto/bn/rsaz_exp.c |  8 ++++++++
>  crypto/bn/rsaz_exp.h | 23 +++++++++++++++++++++++
>  2 files changed, 31 insertions(+)
> 
> 0ed27fb7a8 Always end BN_mod_exp_mont_consttime with normal Montgomery reduction.
>  crypto/bn/asm/x86_64-mont5.pl | 196 ----------------------------------------------------------------------------------
>  crypto/bn/bn_exp.c            |  44 +++++++++++--------
>  2 files changed, 26 insertions(+), 214 deletions(-)
> ```

I will be looking in this today. Remerged the fix to see whether I did something wrong first.

**Comment by rsbeckerca** [comment]
This is for ia64 and x86 big endian on NonStop. Both 32 and 64 bit. I am not seeing the breakage at 3.0.4.

**Comment by rsbeckerca** [comment]
My plan is to revert each commit in isolation and retest - basically a manual bisect.

**Comment by t8m** [comment]
ia64 fails too? That's extra weird as those mod_exp changes should not touch it.

**Comment by t8m** [comment]
The stack corruption you see in gdb in bn_test might be a red herring as the assembler code probably does not keep the frame pointers right. I see the seeming stack corruption too when I break the bntest in gdb but the test works normally and passes. Please also note that the bntest takes a little while to finish.

**Comment by rsbeckerca** [comment]
> The stack corruption you see in gdb in bn_test might be a red herring as the assembler code probably does not keep the frame pointers right. I see the seeming stack corruption too when I break the bntest in gdb but the test works normally and passes. Please also note that the bntest takes a little while to finish.

Thanks. I do see the stack show up properly eventually. 3 hours is too long (it was about 10 minutes previously) and too many other tests also fail at 1.1.1p.

**Comment by rsbeckerca** [comment]
I reran the tests that passed on 1.1.1o, and am now seeing the same issues as with 1.1.1p. Still not seeing the issues in 3.0.4. I am suspecting a deeper issue, like uninitialized memory creating random fails.

**Comment by rsbeckerca** [comment]
@davidben I went back and manually executed the tests. They work fine at 1.1.1o when run individually in verbose mode.

**Comment by rsbeckerca** [comment]
All but 15-test_ecparam passed. So something seems amiss with quiet vs. verbose mode.
```
Test Summary Report
-------------------
../test/recipes/15-test_ecparam.t                (Wstat: 3840 Tests: 134 Failed: 15)
  Failed tests:  89-103
  Non-zero exit status: 15
```
This one also fails at 1.1.1o, so I think things are reasonable.

**Comment by rsbeckerca** [comment]
More info on this. Our CI/CD system is Jenkins - we cannot easily use github actions for security reasons (VPN to our system). Jenkins does some things with the various pipes, including merging stderr and stdout and making stdin invalid. So `istty()`-like methods return false. What we find is that when the above tests run inside Jenkins, they fail. When run manually from sh or bash, they succeed. (except for ecparam). This does allow us to move forward with approving deployment but requires a manual step to verify that any failed tests actually succeed externally. It is somewhat disconcerting as to why this occurs, but OpenSSL is not the only project with this particular difficulty. I would like to understand the cause.

**Comment by paulidale** [comment]
That's very weird.  I know I've said that before about NonStop :grin:

Is there a way to use `script` or similar to use a pty to avoid the `istty()` concern?
Note: OpenSSL doesn't use `istty()` in our tests that I'm aware of but it's worth considering.

An aside: `make test >output.txt 2>&1 <&-` works fine here, so maybe this isn't an issue.

**Comment by rsbeckerca** [comment]
> That's very weird. I know I've said that before about NonStop 😁
> 
> Is there a way to use `script` or similar to use a pty to avoid the `istty()` concern? Note: OpenSSL doesn't use `istty()` in our tests that I'm aware of but it's worth considering.

I do not have any control of what Jenkins does. If I do run Jenkins with a valid TTY, it prompts for SSH passphrases, so that is not an option.

> An aside: `make test >output.txt 2>&1 <&-` works fine here, so maybe this isn't an issue.
