### ISSUE TITLE
defn_cache assertion failure

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#18631]
This build:

https://github.com/openssl/openssl/runs/7004002993?check_suite_focus=true

From PR #18601, produced this assertion failure:

````
crypto/property/defn_cache.c:117: OpenSSL internal error: Assertion failed: old == NULL
../../util/wrap.pl ../../test/threadstest -config /home/runner/work/openssl/openssl/test/default.cnf ../../test/recipes/90-test_threads_data => 134
not ok 1 - running test_threads
````

The change in PR #18601 is a test change only and would have no impact on the above codepath.

The assertion failure comes from inside the function `ossl_prop_defn_set`. It would happen if the hash `property_defns` already contains an entry for the `prop` being set.

`ossl_prop_defn_set` is the only function that modifies the `property_defns` hash. The only caller of `ossl_prop_defn_set` is `ossl_method_store_add` which calls `ossl_prop_defn_get` immediately beforehand to confirm that no entry exists in `property_defns` for the property. All of this is done while holding a write lock on the method store lock.

So, if the only way for the assertion can fail is if an entry already exists, and we just checked that no entry exists, and we do all of this while holding a write lock, I cannot see how it is possible for this assertion to fail - but somehow it has???

**Comment by paulidale** [comment]
I can't see how that piece of code will fail.

@bernd-edlinger's suggestion is plausible.

**Comment by mattcaswell** [comment]
The other examples in #18594 appear to be random and widespread. This particular error seems to be of a different nature - so I tend to think this is a real bug. Note that I added the assertion that is failing here just recently - so it is entirely plausible that something about it is off. I just can't figure out what.

**Comment by nhamer** [comment]
The test isn't perchance building with threads_none.c is it? CRYPTO_THREAD_write_lock is a noop in that case.
