### ISSUE TITLE
Can you simulate CMP server in openssl3?

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#18636]
This was asked by @XYQ202 in https://github.com/openssl/openssl/issues/18569#issuecomment-1161717829.

**Comment by DDvO** [comment]
Yes, there is a very simple mock CMP server, which is used in the test suite.
One can invoke these specific tests using `make test TESTS=test_cmp_http`.

The server is called via the `cmp` app  when the `-port` option is given. See its man page for details.
The implementation is in 
* `apps/cmp.c` - the CLI option handling
* `apps/lib/cmp_mock_srv.c` - the application/mock code
* `apps/lib/http_server.c` - the HTTP server used
* `crypto/cmp/cmp_server.c` - the CMP server core; see e.g. [`OSSL_CMP_SRV_process_request()`](https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_CMP_SRV_CTX_new.pod)

**Comment by antonymsouza** [comment]
Is the OpenSSL CMP MOC server support HTTPS. I tried to connecting from CMP client with HTTS but no success. I think it is not. But want to confirm.

**Comment by t8m** [comment]
> Is the OpenSSL CMP MOC server support HTTPS. I tried to connecting from CMP client with HTTS but no success. I think it is not. But want to confirm.

It supports only HTTP.
