### ISSUE TITLE
exception error in vio_ssl_write(Vio*, const uchar*, size_t) in openssl

### ISSUE THREAD

**Issue by polestar1988** [openssl/openssl#18649]
I have a decryption method which decrypts data using private key:
   auto decrypt_private(const unsigned char* data,size_t data_len, 
    unsigned char* decrypted_data)-> int
    {
    std::string pr_key_name="mykey.pem";
    std::string keypass = "pass";
    char * keypass_byte= const_cast<char*>( keypass.c_str() );
    //open the private key file
    FILE *fp = fopen(pr_key_name.c_str(), "r");
    RSA *rsa = PEM_read_RSAPrivateKey(fp, NULL, NULL, keypass_byte);
    if(rsa==NULL)
       ERR_print_errors_fp(stderr);
    fclose(fp);
    int rsa_outlen  = RSA_private_decrypt(data_len, data, decrypted_data,rsa, 
    RSA_PKCS1_PADDING);
    RSA_free(rsa);
    return rsa_outlen;
    }
int main(){
    std::string encrypted_data;
    // encrypted data is in hex encoding
    cin>>encrypted_data;
    // I know the exact length of decrypted data
    unsigned char* decrypted_data = new unsigned char[DATA_SIZE];
    unsigned char* encrypted_data_byte= new unsigned char[encrypted_data.length()/2];
    int decrypted_data_size= decrypt_private(encrypted_data_byte, 
    encrypted_data.length()/2, decrypted_data);
    // catch error if decryption faild
    if(decrypted_data_size==-1){
         delete[] decrypted_data;
          delete[] encrypted_data_byte;
          std::cout<<"decryption faild";
          return 1;
      }
    delete[] decrypted_data;
    delete[] encrypted_data_byte;
    return 0;
    }

but as I add the if condition and the result of the decryption method is -1 I get error from viossl.cc :
../vio/viossl.cc:315: size_t vio_ssl_write(Vio*, const uchar*, size_t): Assertion `ERR_peek_error() == 0' failed.
and throw an exception and the program crashes. Does any body knows the reason? By the way I also removed the if condition and again I get the same error.
-->

**Comment by t8m** [comment]
vio_ssl_write is not a function in OpenSSL.

**Comment by polestar1988** [comment]
> vio_ssl_write is not a function in OpenSSL.

I am almost new in openssl, so do you know the reason of the crash?

**Comment by mattcaswell** [comment]
> Assertion `ERR_peek_error() == 0' failed.

This means that the code viossl.cc (whatever that is - it isn't distributed by OpenSSL) is asserting that the OpenSSL error stack is empty. Since this assertion is failing it means that it is expecting it to be empty but it isn't. You might want to examine why you've got an error in the error stack and possibly do something with it. See the various `ERR_*` functions listed here:

https://www.openssl.org/docs/man3.0/man3/

You can clear the error stack using `ERR_clear_error()`:

https://www.openssl.org/docs/man3.0/man3/ERR_clear_error.html

**Comment by polestar1988** [comment]
> You might want to examine why you've got an error in the error stack and possibly do something with it.

Thanks so much ERR_clear_error() solved the problem.
