### ISSUE TITLE
If the server requests the client certificate does the client require a key file?

### ISSUE THREAD

**Issue by navadev** [openssl/openssl#18643]
If the remote SSL server requested the client's certificate as part of the handshake, do I really require a key file on the client side along with its certificate?

For example, I am currently calling:
1. SSL_CTX_use_certificate_file
2. SSL_CTX_use_PrivateKey_file 
3. SSL_CTX_check_private_key

If I don't include step  2 (and 3), SSL_CTX_use_PrivateKey_file, the client wont send the certificate to the server. Is the private key file really required at the client side? If so, why is this the case?

**Comment by t8m** [comment]
Without the private key the client cannot prove to the server that is owns the certificate it is presenting to the server. A certificate is a _public thing_ that anybody can have. Being able to use the private key whose corresponding public key is in the certificate is the thing that proves the certificate belongs to you. This is public key authentication security basics.

**Comment by navadev** [comment]
Thank you for the clarification. I think I was confused about it due to (1) client certificate not normally requested (2) the certificate being self-signed.
