### ISSUE TITLE
Some special base64 cases decode error.

### ISSUE THREAD

**Issue by TomatoJal** [openssl/openssl#18648]
There are some cases which have different behavior between BIO and EVP 

**Case 1. "A===", There should only be at most two "="**

  | BIO Method | EVP Method
-- | -- | --
B64Len | 4
B64Data(hex) | 41 3D 3D 3D
B64Data(str) | A===
DataLen | 1 | 3
Data(hex) | 00 | 00 00 00
Data(str) |   |  

**Case2. B64Data length is less than 4**
In fact "QQ" is enough to decode to "A"

  | BIO Method | EVP Method
-- | -- | --
B64Len | 2
B64Data(hex) | 51 51
B64Data(str) | QQ
DataLen | 0 | -1
Data(str) |   |

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
