### ISSUE TITLE
OpenSSL nuget package installed without anything

### ISSUE THREAD

**Issue by SupporterMan** [openssl/openssl#1865]
When I install OpenSSL package version 1.0.2.1 on my VS2015 project, I get following error message:

> Package 'openssl 1.0.2.1' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly.

So I downloaded this package to local and install from my local nuget feed, it shows installed successful. But I don't find any libraries and references added into my project. Then I open the .nupkg file with NuGet Package Explorer, I found there doesn't contains any files in this package.

Is this a bug for OpenSSL package or there has something wrong on my operation?

**Comment by mattcaswell** [comment]
This is a question for whoever maintains the nuget OpenSSL package. That isn't maintained by the OpenSSL Project itself.
