### ISSUE TITLE
The hardcoded FIPSKEY break the intergrity security

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#18658]
The hardcoded FIPSKEY is HMAC key, this is sensitive data but hardcode, the intergrity will loss when the attacker changed the HMAC key and the signature file together.

The hardcoded FIPSKEY in [openssl](https://github.com/openssl/openssl)/Configure:
`$config{FIPSKEY}` =
    `'f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813';`

**Comment by levitte** [comment]
This is an ops problem

**Comment by paulidale** [comment]
This is what is mandated by NIST.

The intention of the integrity test is not to stop an attacker, it's to detect corruption of the module.

**Comment by KanPlus** [comment]
> 

So，this key was not regard as senstive data

**Comment by paulidale** [comment]
No, not sensitive at all.
