### ISSUE TITLE
Could EVP_PKEY_new_raw_public_key be supporting NID_X9_62_prime256v1 ? 

### ISSUE THREAD

**Issue by MQader** [openssl/openssl#18672]
I have a use case, that I'm receiving a key exchange from the client (using openssl, or gnutls-cli), I receive the client's public key as raw data, I need to convert it to EVP_PKEY to create the peer key using EVP_PKEY_new_raw_public_key() which would be used to derive the shared key... 
but unfortunately only limited curves are supported, e.g. EVP_PKEY_X25519, EVP_PKEY_ED25519, EVP_PKEY_X448 or EVP_PKEY_ED448.

would it be possible to support NID_X9_62_prime256v1 as well ? Are there any alternatives ?

**Comment by t8m** [comment]
You have to use different API calls for the generic EC curve support. You can for example use the EVP_PKEY_CTX_new_from_name(), EVP_PKEY_fromdata_init(), and EVP_PKEY_fromdata() to to import such EVP_PKEY.

These functions are available only in OpenSSL 3.0 though. If you need something that works in 1.1.1 too, you have to use
EVP_PKEY_CTX_new_id() to create EC paramgen context, EVP_PKEY_paramgen_init(), EVP_PKEY_CTX_set_ec_paramgen_curve_nid(), and EVP_PKEY_paramgen() to "generate" (actually just create) the appropriate parameters and then use EVP_PKEY_set1_tls_encodedpoint() to set the encoded public key into the EVP_PKEY containing the curve parameters.

**Comment by MQader** [comment]
Many thanks, I'm using 1.1.1. I will try with this solution.

**Comment by t8m** [comment]
You can look at the apps/speed.c - there is a snippet that sets up an ecdsa key (it includes generation of the ephemeral key which you will also need).
