### ISSUE TITLE
srptest: Test case failed

### ISSUE THREAD

**Issue by dharanlinux** [openssl/openssl#18681]
Hi Team, 

    While I am running the srptest test case in the arm platform, I am getting the below issue.

OpenSSL Version: **1.1.1P**
Arch: **ARM (BeagleBone Black)**

**Error log:**

```
# ERROR: (BIGNUM) 'Kclient == Kserver' failed @ test/srptest.c:94
# --- Kclient
# +++ Kserver
```

Attached full log:

[srptest-openssl-1.1.1P.log](https://github.com/openssl/openssl/files/9009901/srptest-openssl-1.1.1P.log)

**Comment by xtkoba** [comment]
This is a "negative" test and a mismatch is expected. The test is passing. I see nothing wrong with it.

**Comment by paulidale** [comment]
The test is passing, closing this.
