### ISSUE TITLE
OPENSSL client not responding to "SERVER HELLO" message

### ISSUE THREAD

**Issue by kanth1976** [openssl/openssl#18686]
We are using openssl-1.0.1g & integrated that with curl HTTP client. During SSL connection establishment, ssl client is not responding to "SERVER HELLO" message & once we restart the HTTP client process, it starts working again properly for sometime before hitting the issue again. Pls help with any suggestion or let us know if this is a known issue thats resolved in latest releases. Thanks

**Comment by paulidale** [comment]
OpenSSL 1.0.1g is long out of support.

If you can reproduce using a supported version (1.1.1 or 3.0), you're more likely to get assistance.  However, the upgrade isn't trivial.

You'll also need to supply quite a bit more information so the issue can be anaylsed.

**Comment by kanth1976** [comment]
Thanks for your comment. We will plan to upgrade to 1.1.1 & try to reproduce. Will get more logs & details if we see it on latest versions.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
