### ISSUE TITLE
About CRYPTO_mem_ctrl()

### ISSUE THREAD

**Issue by asali23** [openssl/openssl#18682]
Consider the following piece of code:
```
BIO *bio_err = NULL;
CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);
bio_err = BIO_new_fp(stderr, BIO_NOCLOSE);
CRYPTO_mem_leaks(bio_err);
CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_OFF);
```

When run, it prints the following:
`threads_none.c:43: OpenSSL internal error: Assertion failed: *(unsigned int *)lock == 1`

Am I using the `CRYPTO_mem_ctrl()` correctly? If not, then please guide me what’s the correct usage.

**Comment by slontis** [comment]
I would suggest using valgrind instead. The master branch no longer supports the memory checking functions..

In older versions of OpenSSL  debug into do_memdbg_init() and see what it does. The code it runs when pthreads is not enabled is fairly simple - so it should not take much to figure out what is wrong in a debugger. The call to CRYPTO_THREAD_lock_new() for this case just sets the lock to 1.. and then only sets it to zero on free..

**Comment by asali23** [comment]
Is there any documentation or example demonstrating the correct usage of these APIs?

**Comment by slontis** [comment]
When you call CRYPTO_mem_leaks(bio_err);  it does an OPENSSL_cleanup()

So you cant call
CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_OFF);
afterwards, since it will be freed at this point..

**Comment by slontis** [comment]
A lot has changed since 1.0.2. including the threading model.
See https://github.com/openssl/openssl/commit/38a6d7f89a6d060b7d463cbdd15eada434bb2d69
