### ISSUE TITLE
OpenSSL generates non-conforming 1024 bit RSA keys  

### ISSUE THREAD

**Issue by AnnieYousar** [openssl/openssl#18692]
If one runs
```
for i in $( seq 1 1 100 ); do  
  openssl genrsa -traditional -out x 1024; openssl asn1parse -in x | sed '5!d'; 
done
```
the private exponents of generated keys are shown.
About one third of the exponents are shown as, e.g.,
```
144:d=1  hl=3 l= 129 prim: INTEGER           :C203D2F5DEA2B2CE4B63A10E8582989A9C9CAE04DABF008B4D2FA96B4...
```
Why this is non-conformant to PKCS#1?

The length of 129 bytes (for a 128 byte key) occurs only if the upper bit of the upper byte of the private exponent is set. In this case an additional zero byte is required in front of the private exponent (not shown in the ASN1 parser).
But this cannot be, as the private exponent d is the inverse to the public exponent e, as required by PKCS#1 (https://datatracker.ietf.org/doc/html/rfc8017#section-3.2), modulo `\lambda(n)`:

$e * d == 1 (mod \lambda(n))$

with `\lambda(p*q)` being the least common multiple of (p-1 and (q-1). Now, because both are even, the LCM(p-1,q-1) is less or equal than `(p-1)*(q-1)/2 < p*q/2 = n/2`.

Therefore the upper bit in the upper byte of the private exponent can never be set in a PKCS#1 conformant key.
The funny part of this issue is, that this behavior disappears if the bit length is 2048 or greater.

**Comment by davidben** [comment]
The text doesn't *quite* require that. It only requires d be bounded by n. (Read the text immediately preceding the equation.) The mod lambda expression itself doesn't imply any bounds, just that the two sides of the equation are equal under that modulus.

In particular, this phrasing allows for RSA keygen using either the Euler totient, (p-1)*(q-1), or the Carmichael totient, lcm(p-1, q-1).

**Comment by AnnieYousar** [comment]
OK. Thanks for pointing that out to me.
