### ISSUE TITLE
missing API to access filed of timestamp struct fileds.

### ISSUE THREAD

**Issue by zhaozg** [openssl/openssl#1872]
Look this:  https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/crypto/ts/ts_lcl.h#L135-L183

Sometimes, we need to read fields(just like certs) of TS_resp_ctx or TS_verify_ctx, but 1.1.x make that private, and not given  TS_resp_ctx_get0_XXX or TS_verify_ctx_get0_XXX, that makes can't upgrade from 1.0x or below versions.

I want to know the thought of DEV team about this questions, and how should I do?

**Comment by mattcaswell** [comment]
If there are fields that you should be able to legitimately access, and you can't any more then please propose some specific API functions that would solve it, along with a justification. Even better create a pull request. We treat missing accessors as a bug.

**Comment by zhaozg** [comment]
thanks, I'll try to change my code to fit ts api.

**Comment by richsalz** [comment]
please re-open if this is still an issue.
