### ISSUE TITLE
Generating G with given P and Q DSA parameters

### ISSUE THREAD

**Issue by jvdsn** [openssl/openssl#18735]
Unless I'm missing something, there's no way to generate a specific G value with given P and Q DSA parameters in OpenSSL 3.

Previously, one could use the `DSA`, `openssl_dsa_set0_pqg`, and `FIPS_dsa_builtin_paramgen2` functions to generate a G (generator) value when P and Q are given. However, because `DSA` is no longer accessible in OpenSSL 3, I am now using `EVP_PKEY_paramgen_init` and `EVP_PKEY_paramgen`. The [attached file](https://github.com/openssl/openssl/files/9055524/pqg_gen.c.txt) contains some code which I would *expect* to work and emulate the old behavior. Unfortunately, running it shows that P and Q are regenerated (and thus the generated G is also incorrect).

Sample output:
```
p = A76807EF24FF1CF5379DB7D3543B97BD85E165C4ED42BA30AF795D669BB1C9D4ADF780681DB458BF2125ADD5A3E21B2928B6E9D15E58F356939A29AE01D50412584CA33008BFE6744B57EF1BE45628194FDDADC3EEE4ED38E7DBA84DCA97BB221BF52FFF2DDE827B3072409582C2B2389326C9D015B867D3C50D17ABF3A415ABC6E6DC89EE5A6F825DD58D5274E87961CB0B62DBA66CCDA7D3363D78A676065A324152A1B570FE5CB251C4505D33D3D75F0FF34A7B580013FFBFBF1F82C9E0A9227EEE36E8D2E9128357C5F920F8737E761D44CE3AEA547D064E812437023769B459769D0116CF1C7070B3054CF36281DA6D62A56E58472D1B295CF0767A501B
q = EFEE0A02CE8A067B146C6A1F49C441D61F488751C92CBDFAB3A643D3
  DSA-Parameters: (2048 bit)
  P:   
      00:9e:fb:b8:74:01:18:14:1c:81:a9:45:47:54:98:
      09:09:0d:bf:4f:8a:8d:54:3e:78:d7:fb:29:24:5c:
      bc:c2:3a:bc:f8:5d:d7:19:b8:ce:dc:61:f3:27:f4:
      e0:2f:05:79:2c:81:cc:f3:f0:80:d5:66:e0:c5:c3:
      2e:21:6f:e2:6c:32:5d:40:9a:0c:30:47:3a:a6:4b:
      26:0e:11:46:80:d5:ee:6e:51:7a:a2:67:08:0e:96:
      f7:ba:75:39:a3:ff:50:67:b1:8e:c3:8f:36:79:b4:
      9a:66:9e:e2:a0:15:13:b5:d5:88:8d:ed:0f:27:ce:
      6a:b9:f4:7e:d5:50:66:75:c6:ba:b8:3d:20:0a:ac:
      8e:26:da:7b:c7:af:ac:78:c1:3e:10:74:4f:ca:ad:
      74:ac:1c:67:b2:8d:ec:af:00:b3:46:a8:56:80:19:
      71:07:2f:f8:d7:eb:e2:00:5b:0f:73:0e:a9:6b:8b:
      f5:be:be:9e:5f:c0:4c:21:52:44:a2:67:5f:69:dc:
      54:fb:56:cb:43:4d:65:26:44:2c:b3:92:7e:b0:40:
      d8:18:bc:c0:0b:79:0a:27:e8:65:f0:57:95:95:af:
      ae:93:79:60:d5:5d:fb:0d:cc:68:f4:f4:87:1b:c0:
      0a:e1:c2:a7:ef:9a:6b:ed:d6:22:11:3a:4e:1d:1a:
      81:fb
  Q:   
      00:b0:aa:0f:b9:aa:9c:58:8d:6c:e8:22:d2:e0:76:
      1e:cd:55:28:4c:d7:4f:e9:22:29:7e:73:8c:23
  G:   
      00:9d:ac:85:91:68:59:e8:18:87:b9:c6:58:51:33:
      0e:6e:74:6c:89:ef:fd:ed:77:07:e0:23:76:a4:33:
      d0:17:1e:dc:f3:05:a3:8a:49:49:78:af:58:b0:da:
      87:4a:53:66:ac:f4:40:f5:ff:4c:a5:52:84:76:16:
      db:e4:d4:1a:ac:d2:92:41:59:d6:77:e1:ed:b3:dc:
      26:d6:b2:73:78:ac:2c:5c:63:55:37:b8:f8:0d:10:
      7d:b5:72:2f:84:2b:1d:a9:fd:4d:3b:e5:e4:6d:d7:
      7a:d4:d7:f8:ce:0b:a9:33:66:82:37:48:47:18:e5:
      ed:32:a5:55:64:53:7a:7b:70:b3:8b:1e:a5:85:96:
      97:16:65:65:8f:30:ee:25:76:37:b5:95:35:c3:c2:
      22:1a:2c:39:9b:80:7e:23:f0:98:b2:dc:c4:bb:89:
      f1:34:8c:df:54:02:c7:c8:5c:dd:21:4f:4e:bc:ff:
      d4:7d:d1:8e:91:77:25:27:c4:46:53:7b:54:d2:af:
      ae:de:8c:af:e8:e9:18:8f:c1:05:72:70:bd:f8:8a:
      bb:64:d2:5c:0c:37:66:ff:14:88:e2:27:3d:0c:cd:
      b8:eb:e6:4d:0c:6b:7f:32:dd:b1:c4:b1:d4:60:30:
      a9:12:55:25:ac:48:4b:37:71:45:0c:b4:50:fd:0d:
      75:7a
  SEED:
      c9:02:9a:87:ee:d8:b7:3b:02:44:53:09:62:5d:97:
      d9:a6:5c:33:1f:07:91:88:50:6c:a2:a5:b8
  pcounter: 426
  h: 2
```

Why do I expect this code to work? Because `ossl_ffc_params_FIPS186_4_gen_verify` in `ffc_params_generate.c` explicitly checks the provided FFC_PARAMS and skips P and Q generation if they are already present:
```
    /*
     * If p & q are passed in and
     *   validate_flags = 0 then skip the generation of PQ.
     *   validate_flags = VALIDATE_G then also skip the validation of PQ.
     */
    if (params->p != NULL && ((flags & FFC_PARAM_FLAG_VALIDATE_PQ) == 0)) {
        /* p and q already exists so only generate g */
        p = params->p;
        q = params->q;
        goto g_only;
        /* otherwise fall thru to validate p & q */
    }

```
(https://github.com/openssl/openssl/blob/master/crypto/ffc/ffc_params_generate.c#L614-L625)

Why does this code currently not work? Because `dsa_gen_set_params` in `dsa_kmgmt.c` does not copy the `OSSL_PKEY_PARAM_FFC_P` and `OSSL_PKEY_PARAM_FFC_Q` parameters to the `dsa_gen_ctx`. (https://github.com/openssl/openssl/blob/master/providers/implementations/keymgmt/dsa_kmgmt.c#L457)

I also tried importing the P and Q values first using `EVP_PKEY_fromdata`, and then re-using the same key object to call `EVP_PKEY_paramgen`, but this didn't seem to help: P and Q were still regenerated: [pqg_gen_2.c.txt](https://github.com/openssl/openssl/files/9055538/pqg_gen_2.c.txt)

Is this an oversight? Or is there a different way to emulate the old behavior? Or was it decided to remove this feature in OpenSSL 3?

**Comment by slontis** [comment]
It does not currently support this case. 
Could you give me some background on why you would want to do this? Is this for testing?

**Comment by slontis** [comment]
The template path does work for this use case....

    bld = OSSL_PARAM_BLD_new();
    OSSL_PARAM_BLD_push_int(bld, OSSL_PKEY_PARAM_FFC_PBITS, L);
    OSSL_PARAM_BLD_push_int(bld, OSSL_PKEY_PARAM_FFC_QBITS, N);

    p_bn = BN_new();
    BN_bin2bn(p, L / 8, p_bn);
    OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_P, p_bn);
    q_bn = BN_new();
    BN_bin2bn(q, N / 8, q_bn);
    OSSL_PARAM_BLD_push_BN(bld, OSSL_PKEY_PARAM_FFC_Q, q_bn);
    params = OSSL_PARAM_BLD_to_param(bld);

    ctx2 = EVP_PKEY_CTX_new_from_name(libctx, "DSA", NULL);
    EVP_PKEY_fromdata_init(ctx2);
    EVP_PKEY_fromdata(ctx2, &key, EVP_PKEY_KEY_PARAMETERS, params);

    /* This is the important line here */
    ctx = EVP_PKEY_CTX_new_from_pkey(libctx, key, NULL);
    EVP_PKEY_paramgen_init(ctx);
    EVP_PKEY_paramgen(ctx, &key2);

    EVP_PKEY_print_params(BIO_new_fp(stdout, 0), key2, 2, NULL);
    
    
    -----------------------------------------------------
    NOTE: If you ever need to validate p & q you would also need to set the seed used to generate p & q.

**Comment by jvdsn** [comment]
My usecase is a very specific kind of testing. But you're right, your example does work. Thanks a lot for the support and sorry for the ticket noise!
