### ISSUE TITLE
Belarussian CryptoAlgorithms

### ISSUE THREAD

**Issue by Not4me** [openssl/openssl#18749]
Hello.

I want to add implementation of Belarussian cryptography. 
First I want to add digest algorithms ([bash](http://apmi.bsu.by/assets/files/std/bash-spec24.pdf) and [belt-hash](http://apmi.bsu.by/assets/files/std/belt-spec371.pdf))

I have successfully built the algorithms into the openssl 1.1.1n

screenshot with digest algorithms (bash256, bash384, bash512, belt-hash)
<img width="499" alt="Screenshot 2022-07-07 at 20 55 09" src="https://user-images.githubusercontent.com/37382910/177838570-c3655c6d-3d3b-486f-bade-7db72b4f45b4.png">
<img width="997" alt="Screenshot 2022-07-07 at 21 08 09" src="https://user-images.githubusercontent.com/37382910/177841077-3d9c23ca-c167-4d18-989b-920137d727fd.png">

screenshot with cipher algorithms (belt-cbc256, belt-cfb256, belt-ctr256, belt-cfb256)
<img width="495" alt="Screenshot 2022-07-07 at 20 56 54" src="https://user-images.githubusercontent.com/37382910/177838991-710fe57a-b81a-43b4-bf40-4776b72778e2.png">

I understand that I have to change the name of the algorithms

**Comment by Not4me** [comment]
I know this implementation, but I don't use this on mobile platforms. Maybe not work at all on mobile.

**Comment by paulidale** [comment]
Nice work.

As a feature, this would only be allowed into the master branch (not 1.1.1 or 3.0).
It should be added to the default provider.

**Comment by beldmit** [comment]
I think it should go into a separate provider (similar to GOST)

**Comment by nhorman** [comment]
marking as inactive, to be closed at the end of 3.4 dev barring further input
