### ISSUE TITLE
Regression: Unable to set EC_KEY private_key to NULL starting in 1.1.1h

### ISSUE THREAD

**Issue by dpirotte** [openssl/openssl#18744]
OpenSSL 1.1.1h introduces a behavior change wherein one can no longer set an EC_KEY's private_key to NULL.

This behavior changes in 6a01f6f4b41d045e2a3abcb10163633d769db76a. Based on the original PR (https://github.com/openssl/openssl/pull/11127), it appears that this is hardening backported from 3.0.0 that unintentionally introduced a regression.

From https://github.com/openssl/openssl/commit/6a01f6f4b41d045e2a3abcb10163633d769db76a#diff-38a47bf175cde97de2df18870a9ab300366f191a848bdea84def068fe0fde69fR484-R486: 

```diff
+    tmp_key = BN_dup(priv_key);
+    if (tmp_key == NULL)
+        return 0;
```

`EC_KEY_set_private_key` returns early and never sets `key->priv_key` to NULL.

**Comment by romen** [comment]
So, before [the patch](https://github.com/openssl/openssl/commit/6a01f6f4b41d045e2a3abcb10163633d769db76a#diff-38a47bf175cde97de2df18870a9ab300366f191a848bdea84def068fe0fde69fR484-R486) in #11127, `EC_KEY_set_private_key(some_eck, NULL);` returned an error but also modified the inner field, which at the time looked like a bug.

Documentation said and says nothing about being allowed to pass `NULL` and what is the expected behavior.

So, questions for OTC:
- what do we think is the expected behavior for `1.1.1`? which one is the bug, original behavior or the one after hardening of #11127?
- depending on the answer above, what do we want for `3.0.0`?
- finally what about `master`?

**Comment by romen** [comment]
Formally my hold is to let OTC evaluate if the original report describes a regression or not.
I am not objecting to fixing it if we deem that it is a regression, but this statement needs more consideration:

> OpenSSL 1.1.1h introduces a behavior change wherein one can no longer set an EC_KEY's private_key to NULL.

As far as the public API is defined, passing NULL return an error code, so one can say that the API before 1.1.1h did not allow the semantic of passing NULL to unset the private key.

On the other hand, if the caller did not check the return value and relied on undocumented inner behavior, one can say this is a regression.

**Comment by t-j-h** [comment]
All those functions explicitly handle being passed NULL as an argument and set the corresponding value to NULL - that is their intent. It didn't happen by accident. 

BN_dup(NULL) returns NULL and that is not an error - as that is what it should do.

Changing long term explicit behaviour like this is one place where things get broken unnecessarily and we should not be backfitting this short of change into a stable release - that was a mistake to backfit it IMHO entirely independent of what you think about what the behaviour should be.

EC_KEY_set_group, EC_KEY_set_private_key, EC_KEY_set_public_key all operate the same way and changing one API out of a set of APIs to behave inconsistently was clearly the wrong choice to be making (for backfit or in any other context). 

Someone wanting to make a behaviour change like that should be explicitly flagging that as a separate PR and discussing the context and the scope - not including it in with other changes.

**Comment by romen** [comment]
I don't disagree with anything you said @t-j-h !

But the previous code was already considering the `BN_dup()` returning NULL as an error, and returning an error to the caller: https://github.com/openssl/openssl/blob/b5acbf914833a83368e51766de4cf2e2074a9436/crypto/ec/ec_key.c#L428-L429

**Comment by mattcaswell** [comment]
> So, questions for OTC:

OTC: We should revert to the old behaviour on all branches, where passing NULL sets the internal key to NULL and we get a failure result code back

**Comment by romen** [comment]
Thanks @dpirotte for reporting this and @robertohueso for the fix.

The fix has been merged:

- #18942 to `master` as:
   - b304b3e8f7 Fix EC_KEY_set_private_key() priv_key regression
   - d93f154d5a Add test for EC_KEY_set_private_key()
   - fae06b5779 Fix EC_KEY_set_private_key() NULL priv_key docs
- #18941 to `openssl-3.0` as:
   - f76cf4d988 Fix EC_KEY_set_private_key() priv_key regression
   - 66627cdfc2 Add test for EC_KEY_set_private_key()
   - c682dfdbdf Fix EC_KEY_set_private_key() NULL priv_key docs
- #18874 to `OpenSSL_1_1_1-stable` as:
   - 143d7d4c79 Fix EC_KEY_set_private_key() priv_key regression
   - 1c2f52bed3 Add test for EC_KEY_set_private_key()
   - 4648839300 Fix EC_KEY_set_private_key() NULL priv_key docs
