### ISSUE TITLE
How to migrate from HMAC_CTX fruntions to new EVP_MAC API?

### ISSUE THREAD

**Issue by gjasny** [openssl/openssl#18746]
Hello,

I'm trying to get rid of the deprecation warnings after switching from OpenSSL 1.1.1 to 3.0.x. For my HMAC code I have the following sequence right now:

* HMAC_CTX_new
* HMAC_Init_ex(..., EVP_sha1(), ...)
* HMAC_Update (multiple times)
* HMAC_Final
* HMAC_CTX_free

Now I struggle to figure out the proper parameters for `EVP_MAC_fetch` and `EVP_MAC_init`. Especially the absence of "well-known" values for the parameters makes the migration harder that it should be. I'd find a mapping table from `EVP_md5|sha1|sha256|...` to the required free-form strings helpful. And maybe another explicit example how to migrate away from the `HMAC_CTX` stuff.

Thanks,
Gregor

**Comment by t8m** [comment]
This is basically a duplicate of #14109

However if you look at the EVP_MAC-HMAC manual page and the demos/mac/gmac.c it should be fairly obvious how to change it to use HMAC instead of GMAC.

**Comment by t8m** [comment]
> I'd find a mapping table from `EVP_md5|sha1|sha256|...`

For this AFAIK just cutting off the `EVP_` from the function name should give you the string to use for the hash (although it might not be the canonical form at least some alias name should match).

**Comment by gjasny** [comment]
Thank you. That did the trick.
