### ISSUE TITLE
Create a TLS1.3 connection using Openssl v1.1.1

### ISSUE THREAD

**Issue by amanguptalibra** [openssl/openssl#18756]
Hello everyone,
I want to create a local server and a local client and would like to have establish TLS1.3 connection between them using ECDHE-ECDSA with NIST P256(or P-384) curve. Can someone help me with commands for setting up a server in Openssl (private-public key pair gen, dummy certificate file etc.) and similarly for Client. Thanks.

Below if what I have so far which seems to work, but **I am not sure how to specify ECDHE (key exchange) and ECDSA (sign/verify) algorithms here**.

**Server side**
openssl ecparam -genkey -name secp384r1 -out privatekey.pem

openssl req -new -sha256 -key privatekey.pem -out csr.csr -subj "/C=US/ST=FL/L=Orlando/O=Foo LLC/OU=IT/CN=www.example.com"

openssl req -x509 -sha256 -days 365 -key privatekey.pem -in csr.csr -out certificate.pem

openssl s_server -accept 8443 -cert certificate.pem -key privatekey.pem

**Client side**

openssl s_client -connect localhost:8443

**Comment by t8m** [comment]
If the server has just an ECDSA certificate it will use only the ECDSA for signing.

To specify the key exchange groups you can use the groups option: `-groups P-256:P-384`.
