### ISSUE TITLE
ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

### ISSUE THREAD

**Issue by JonasVautherin** [openssl/openssl#18754]
I am cross-compiling for iOS, as a static library. It works for OpenSSL 1, but I have the following error with OpenSSL 3:

```
ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
```

I am configuring with the following command:

```
CFLAGS=-fembed-bitcode ./Configure ios64-xcrun --prefix=<install_path> --release no-shared
```

Now it seems to me that `-bundle` is set [here](https://github.com/openssl/openssl/blob/master/Configurations/shared-info.pl#L44):

```
    'darwin-shared' => {
        module_ldflags        => '-bundle',
        shared_ldflag         => '-dynamiclib -current_version $(SHLIB_VERSION_NUMBER) -compatibility_version $(SHLIB_VERSION_NUMBER)',
        shared_sonameflag     => '-install_name $(libdir)/',
    },
```

Is there a way for me to not use `-bundle`, given that I need `-fembed-bitcode`? And what would be the consequence of that? I don't really understand what `-bundle` does :see_no_evil:.

**Comment by julianoes** [comment]
It looks like this could be similar to #5513.

**Comment by wyllys66** [comment]
Changing "darwin-shared->module_ldflags" from "-bundle" to "-dynamiclib" worked for me, I was then able to build 3.1.1 for iOS.

**Comment by julianoes** [comment]
I think this problem went away starting with XCode 14 which does not require bitcode any longer. We were able to go to openssl 3.0.9 in https://github.com/mavlink/MAVSDK/pull/2069/commits/3ff4ea3b0d1f413cfe6b5d201e91e166d5b36e08.

**Comment by JonasVautherin** [comment]
Yes, closing then :+1:
