### ISSUE TITLE
AxiosError: write EPROTO 1C3B0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

### ISSUE THREAD

**Issue by Laxuzer** [openssl/openssl#18757]
I get this error when I try to send a request via proxy with Axios. I've searched the Internet, but I haven't been able to reach any results.

```
const axios = require('axios')

axios({
    url: 'http://medal.tv',
    method:'GET',
    proxy: {
        protocol: 'http',
        host: 'xxx',
        port: 3000,
        auth: { username: 'xxx', password: 'xxx' }
    },  
}).then(e => console.log(e.data)).catch(e => console.log(e))
```

**Comment by Laxuzer** [comment]
this is my code```
const axios = require('axios')

axios({
    url: 'http://medal.tv',
    method:'GET',
    proxy: {
        protocol: 'http',
        host: 'xxx',
        port: 3000,
        auth: { username: 'xxx', password: 'xxx' }
    },  
}).then(e => console.log(e.data)).catch(e => console.log(e))```

**Comment by t8m** [comment]
This is a wrong place to ask questions about Axios.

Just a guess - you've configured a http proxy (unencrypted) but the Axios supports only https proxies (or you need something else to do to configure a http proxy).
