### ISSUE TITLE
openssl 3.0.3: error when running openssl speed ffdh

### ISSUE THREAD

**Issue by daytimothy** [openssl/openssl#18768]
When running openssl speed with the  command, openssl speed -seconds 1 -multi 256 ffdh, the following errors are reported:
40E747F2327F0000:error:1C80006A:Provider routines:dh_plain_derive:output buffer too small:../providers/implementations/exchange/dh_exch.c:162:

If the value for multi is reduced to around 30, the errors are not reported.

attached:log for command
[command.log](https://github.com/openssl/openssl/files/9077685/command.log)

**Comment by t8m** [comment]
Fix in #18777
