### ISSUE TITLE
Add OpenSSL License for v1.* into the License section in README.md on master branch

### ISSUE THREAD

**Issue by fu7mu4** [openssl/openssl#18767]
The Readme.md on master branch, it means v3.*, tell me that the License for OpenSSL is Apache License v2.0 but it does not tell us about License for old OpenSSL , ex v 1.1.1*. Yes, of course, I know the License update , https://www.openssl.org/blog/blog/2017/03/22/license/ . Now OpenSSL is released under Apache License v2.0 but Older version has been released under OpenSSL and SSLeay License. So please add some description for license updating into License section in README.md on master branch.

**Comment by paulidale** [comment]
I don't see why this is necessary.  If you are building an older version, you'll see the appropriate license.

**Comment by levitte** [comment]
The info is already in place where appropriate for historical records. Look in NEWS.md

**Comment by paulidale** [comment]
Also on our web site: https://www.openssl.org/source/license.html
