### ISSUE TITLE
OpenSSL3.0: Prerequisite to enable anonymous cipher

### ISSUE THREAD

**Issue by ravinjhajharia** [openssl/openssl#18771]
I know that anonymous was discouraged in earlier versions of openssl. The users must append SECLEVEL=0 if they wish to use these ciphers explicitly. I have tried the same with openssl-3.0 s_client and server utility but it fails with internal error 80.

**PS**: SECLEVEL=0 and legacy provider are configured.

I would appreciate it if anyone could provide the list of prerequisites to make use of anonymous ciphers. 

@mattcaswell: Any thoughts?

**Comment by mattcaswell** [comment]
You need to:

1) Ensure security level is 0
2) Ensure TLSv1.3 is not negotiated (there are no anon ciphersuites for TLSv1.3)
3) Ensure there is a common anon ciphersuite enabled between client and server (there are no anon ciphersuites in the default ciphersuite list)

E.g.

Server:
````
$ openssl s_server -no_tls1_3 -cipher "ADH-AES256-GCM-SHA384:@SECLEVEL=0"
````

Client:
````
$ openssl s_client -cipher "ADH-AES256-GCM-SHA384:@SECLEVEL=0"
````
