### ISSUE TITLE
Crash observed in EVP_DigestVerifyUpdate  with OpenSSL 3.0.5

### ISSUE THREAD

**Issue by AshishDurgapal** [openssl/openssl#18770]
We have an application which is using the deprecated EVP calls like EVP_DigestVerifyUpdate 

line : if (EVP_DigestVerifyUpdate(pCtxRSAverify, pucMsg, szMsgLen) <= 0)

but we are getting segmentation fault with OpenSSL 3.0.5 while it is working fine with older version of OpenSSL 1.1.1k.

Can You please share some quick observations/views on this.

**Comment by AshishDurgapal** [comment]
Stack trace

458	        if (pctx->flag_call_digest_custom
459	            && !ctx->pctx->pmeth->digest_custom(ctx->pctx, ctx))
460	            return 0;
461	        pctx->flag_call_digest_custom = 0;
462	    }
(gdb) p pctx->flag_call_digest_custom
$7 = 1
(gdb) p ctx->pctx
$8 = (EVP_PKEY_CTX *) 0x5555557d59d0 <update256>
(gdb) p ctx
$9 = (EVP_MD_CTX *) 0x55555abd9370
(gdb) p ctx->pctx->pmeth->digest_custom
Cannot access memory at address 0x842007
(gdb) p ctx->pctx->pmeth->
A syntax error in expression, near `'.
(gdb) p ctx->pctx->pmeth
$10 = (const EVP_PKEY_METHOD *) 0x841f0f
(gdb) p *ctx->pctx->pmeth
Cannot access memory at address 0x841f0f
(gdb) p *ctx
$11 = {reqdigest = 0x555555dcdb00 <sha256_md>, digest = 0x0, engine = 0x0, flags = 93825079878496, md_data = 0x555555e96910, pctx = 0x5555557d59d0 <update256>, update = 0x40, algctx = 0x61, 
  fetched_digest = 0x55555abd8c90}
(gdb) p *ctx->pctx
$12 = {operation = 610044232, libctx = 0xec8348f38948f824, propquery = 0xffb407e8d5894818 <error: Cannot access memory at address 0xffb407e8d5894818>, 
  keytype = 0x48de8948ea8948ff <error: Cannot access memory at address 0x48de8948ea8948ff>, keymgmt = 0x245c8b4810246c8b, op = {keymgmt = {genctx = 0x18c48348c7894808}, kex = {exchange = 0x18c48348c7894808, 
      algctx = 0x2e66660001275be9}, sig = {signature = 0x18c48348c7894808, algctx = 0x2e66660001275be9}, ciph = {cipher = 0x18c48348c7894808, algctx = 0x2e66660001275be9}, encap = {kem = 0x18c48348c7894808, 
      algctx = 0x2e66660001275be9}}, cached_parameters = {dist_id_name = 0x841f0f <error: Cannot access memory at address 0x841f0f>, dist_id = 0xffb3d7e808ec8348, dist_id_len = 14378102487850895615, 
    dist_id_set = 1}, app_data = 0x841f0f, pkey_gencb = 0xffb3b7e8f3894853, keygen_info = 0x5bc68948df8948ff, keygen_info_count = 19336169, legacy_keytype = 778462720, pmeth = 0x841f0f, 
  engine = 0x6c8948f0245c8948, pkey = 0xec8348f38948f824, peerkey = 0xffb387e8d5894818, data = 0x48de8948ea8948ff, flag_call_digest_custom = 1, rsa_pubexp = 0x18c48348c7894808}
(gdb) p *ctx->pctx->pmeth
Cannot access memory at address 0x841f0f
(gdb) p *ctx->pctx
$13 = {operation = 610044232, libctx = 0xec8348f38948f824, propquery = 0xffb407e8d5894818 <error: Cannot access memory at address 0xffb407e8d5894818>, 
  keytype = 0x48de8948ea8948ff <error: Cannot access memory at address 0x48de8948ea8948ff>, keymgmt = 0x245c8b4810246c8b, op = {keymgmt = {genctx = 0x18c48348c7894808}, kex = {exchange = 0x18c48348c7894808, 
      algctx = 0x2e66660001275be9}, sig = {signature = 0x18c48348c7894808, algctx = 0x2e66660001275be9}, ciph = {cipher = 0x18c48348c7894808, algctx = 0x2e66660001275be9}, encap = {kem = 0x18c48348c7894808, 
      algctx = 0x2e66660001275be9}}, cached_parameters = {dist_id_name = 0x841f0f <error: Cannot access memory at address 0x841f0f>, dist_id = 0xffb3d7e808ec8348, dist_id_len = 14378102487850895615, 
    dist_id_set = 1}, app_data = 0x841f0f, pkey_gencb = 0xffb3b7e8f3894853, keygen_info = 0x5bc68948df8948ff, keygen_info_count = 19336169, legacy_keytype = 778462720, pmeth = 0x841f0f, 
  engine = 0x6c8948f0245c8948, pkey = 0xec8348f38948f824, peerkey = 0xffb387e8d5894818, data = 0x48de8948ea8948ff, flag_call_digest_custom = 1, rsa_pubexp = 0x18c48348c7894808}


At line 459, !ctx->pctx->pmeth->digest_custom(ctx->pctx, ctx))
pmeth address is not valid.

**Comment by slontis** [comment]
I assume this is somehow related to using an engine.. it only hits this legacy path in that case.
There is only one place that sets  ctx->pctx->flag_call_digest_custom, which has code that does
````
    ctx->pctx->flag_call_digest_custom = 0;
    if (ctx->pctx->pmeth->digest_custom != NULL)
        ctx->pctx->flag_call_digest_custom = 1;
````
So I assume pmeth was valid at some point.. Maybe try to track down what changes this value?
Valgrind might also give some hint as to where it goes wrong..

**Comment by AshishDurgapal** [comment]
This problem has been resolved now.

Actually we have used multiple libs in our application having multiple version of OpenssSL.
