### ISSUE TITLE
OpenSSL-3: Decoding a public key from a bio not working 

### ISSUE THREAD

**Issue by jofaber** [openssl/openssl#18775]
I am working on replacing deprecated low level api calls by new recommended api calls in order to be OpenSSL-3 compliant. To decode a public RAS key in PEM format from a BIO we used this code:
```
    EC_KEY* ec_public_key(char pem[])
    {
      BIO* bio     = BIO_new_mem_buf(pem, -1);
      EC_KEY* pkey = ::PEM_read_bio_EC_PUBKEY(bio, NULL, NULL, NULL);
      BIO_free(bio);
      return pkey;
    }
```
which is still working correctly but has deprecated functions.

Following the documentation to [decode from a BIO](https://www.openssl.org/docs/man3.0/man3/OSSL_DECODER_from_bio.html), I replaced the code snippet above with the recommended example code from the cited documentation:
```
    EVP_PKEY* evp_public_key(char pem[])
    {
      BIO* bio     = BIO_new_mem_buf(pem, -1);

      OSSL_DECODER_CTX *dctx;
      EVP_PKEY* pPublicKey = NULL;
      const char *format = "PEM";   /* NULL for any format */
      const char *structure = NULL; /* any structure */
      const char *keytype = "RSA";  /* NULL for any key */

      dctx = OSSL_DECODER_CTX_new_for_pkey(&pPublicKey, format, structure,
                                      keytype,
                                      OSSL_KEYMGMT_SELECT_KEYPAIR,
                                      NULL, NULL);
      
      if(dctx == NULL) {
          fmt::printf("error: no suitable potential decoders found\n");
      }
      else if(OSSL_DECODER_from_bio(dctx, bio)){ //This call always fails
          fmt::printf("pkey is created with the decoded data from the bio\n");
      } else { 
          fmt::printf("decoding failure\n");
      }
      OSSL_DECODER_CTX_free(dctx);
      
      return pPublicKey;
    }
```
I am calling the new code in a small test function like this:
```
    void decode_from_bio()
    {
      static char somePublicRASKey[] = "-----BEGIN PUBLIC KEY-----\n" \
        "MGswVwYHKoZIzj0CATBMAgEBMBoGByqGSM49AQECDwD////////////////95zAG\n" \
        "BAEABAEDBA8CAAAAAAAAAAAAAAAAAAECDwEAAAAAAAAB7OpVGtg36QIBAQMQAALr\n" \
        "LgnD+KtMsai94cnWWw==\n" \
        "-----END PUBLIC KEY-----\n";
    
      bool use_ossl3_api = true; 
      if(use_ossl3_api)
        auto evp_pkey = evp_public_key(somePublicRASKey); // New impl
      else
        auto ec_pkey = ec_public_key(somePublicRASKey); // Old impl

    }
```
In function `evp_public_key` the call to `OSSL_DECODER_from_bio(dctx, bio)` **always fails**. What am I missing?

I am using OpenSSL-3.0.3 on a Mac M1 macOS 12.2.1 (Monterey) Apple clang version 13.0.0.
Same behavior happens on an older MacPro 10.15.6 (Catalina)  Apple clang version 12.0.0.

We have an own build of OpenSSL-3.0.3 but `perl configdata.pm --dump` fails. I only see a `perl configdata.pm.in` in the repository.

Thanks in advance

**Comment by levitte** [comment]
The old function is calling `PEM_read_bio_EC_PUBKEY()`, thusly it's expecting an *EC* key, not a *RSA* key.
Your new function is, however, expecting a RSA key, which is the reason it fails, 'cause your example public key is indeed an EC public key.

Change the keytype value to `"EC"`, that should get you a better result.

**Comment by jofaber** [comment]
Thank you a lot for the explanation and the hint of setting the key type to "EC". Well, I needed to change the `selection` argument to `OSSL_KEYMGMT_SELECT_PUBLIC_KEY` in addition. Now I get expected results :)
