### ISSUE TITLE
OpenSSL built and ready for iOS/macOS (repo)

### ISSUE THREAD

**Issue by blazorin** [openssl/openssl#18782]
### I've made a [repository](https://github.com/blazorin/EssentialLibs) which contains OpenSSL and Boost built and ready for iOS and macOS architectures.

**Includes thread-safe libraries aswell!**

**Comment by paulidale** [comment]
I'd suggest adding something to the 3rd party wiki page: https://wiki.openssl.org/index.php/Binaries
