### ISSUE TITLE
Support empty "renegotiation_info" as a ClientHello extension (rather than SCSV)

### ISSUE THREAD

**Issue by kaduk** [openssl/openssl#18790]
The forthcoming revision to BCP 195 (https://datatracker.ietf.org/doc/html/draft-ietf-uta-rfc7525bis) will provide guidance that clients MUST send renegotiation_info in the ClientHello.  When I asked for clarification about whether the SCSV suffices (https://github.com/yaronf/I-D/issues/369) the response noted that, per RFC 5746, the SCSV option was introduced as a way to reduce breakage in the face of old (SSLv3/TLS1.0) servers that don't support extensions at all, aborting the handshake when any extra data was seen at the end of the ClientHello.  Since this revision of BCP 195 is going to require TLS 1.2 support, we can assume that there is server support for extensions and thus the SCSV form is not useful.  However, as I mentioned recently in #18207, OpenSSL always uses the SCSV form in the ClientHello and has no option to send "renegotiation_info" as a regular extension in initial handshakes.  This SCSV-only implementation will be non-compliant to the BCP upon publication.

**Comment by t8m** [comment]
The question is - will the public internet servers start dropping connections from clients sending SCSV and no renegotiation_info? If so, when? Because in that case we might have to backport this to stable releases as well.

**Comment by mattcaswell** [comment]
> The question is - will the public internet servers start dropping connections from clients sending SCSV and no renegotiation_info? If so, when? Because in that case we might have to backport this to stable releases as well.

It seems unlikely any time soon. I would just change 3.1 to behave this way and not worry about backport to stable releases. If it really does become a problem later then we can consider backport then.

**Comment by davidben** [comment]
FWIW, looking back, it looks like we (BoringSSL) switched from SCSV to extension back in 2015 for TLS 1.0 and up. Never heard of any compat impact, so it should be safe to change.
https://boringssl-review.googlesource.com/5143

**Comment by kaduk** [comment]
FWIW, I agree with Matt -- there doesn't seem to be a very strong incentive for public internet servers to suddenly become more stongly enforcing in this regard.  So just changing behavior for 3.1 seems fine for now.

**Comment by pimterry** [comment]
It would be lovely to see some progress on this. This obvious difference between traffic from OpenSSL vs browser traffic from BoringSSL & NSS (and likely others) is something that makes OpenSSL's TLS fingerprint particularly recognizable, and makes it easy for providers (especially Cloudflare) to block OpenSSL clients completely.

**Comment by pimterry** [comment]
This is now fixed: #24161

**Comment by mattcaswell** [comment]
Closing
