### ISSUE TITLE
NPN / ALPN extensions callbacks don't allow handshake failure

### ISSUE THREAD

**Issue by Scottmitch** [openssl/openssl#188]
The interface for the ALPN/NPN protocol selection callbacks and protocol selection notification callbacks do not allow for the handshake to fail.  It is requested that the return value support for these methods be expanded to allow the handshake to fail.  This may be desirable (and explicitly called out in the ALPN specification) in the event there are no common protocols found during the selection process, or if the select protocol is not acceptable.

For example:
[ALPN RFC Section 3.2](http://tools.ietf.org/html/draft-ietf-tls-applayerprotoneg-05#section-3.2) specifies a new fatal alert definition `no_application_protocol(120)` which can be used.  This is currently not defined in openssl.

The NPN specification is not as explicit about the alert to be used in this case but it could just result in a generic handshake_failure alert (if the callbacks return the new failure value)?

**Comment by Scottmitch** [comment]
Now that HTTP/2 has been published as an RFC (and ALPN is already an RFC)....is there any chance of this getting re-prioritized?

**Comment by richsalz** [comment]
yeah, it probably should be.  can you bring it up on openssl-dev?

**Comment by Scottmitch** [comment]
@richsalz - Done. Haven't received feedback that the post went through yet though. Not sure if I'm required to join before posting or if the post has to be reviewed before it makes it to the archives.

**Comment by richsalz** [comment]
ah, yeah, you have to be a member of the list to post.  i think nabble has a UI that lets you post

**Comment by Scottmitch** [comment]
@richsalz - Join request sent.

**Comment by Scottmitch** [comment]
Question posted to mailing list http://marc.info/?l=openssl-dev&m=143285528815940&w=2

**Comment by richsalz** [comment]
See also http://rt.openssl.org/Ticket/Display.html?id=3463 (user/pass guest/guest)

**Comment by Scottmitch** [comment]
@richsalz - I checked out the [patch](http://rt.openssl.org/Ticket/Display.html?id=3463) and it looks good. The only thing from your point of view is whether you want to make the fatal alert failure behavior in s_server optional or not. This would be to preserve existing behavior, even though it goes against the spec.

What is the timeline on evaluating / merging / targeting this for a release?

**Comment by richsalz** [comment]
Finally closing this in 1.1;  we'll send the alert.  code to land in repo shortly.

**Comment by Scottmitch** [comment]
@richsalz - Thanks for the update! So this will not land in a 1.0.2 release?

**Comment by richsalz** [comment]
nope.  sorry.

**Comment by normanmaurer** [comment]
@richsalz did this ever land in openssl ? I am trying to find the changeset but no luck so far :/

**Comment by richsalz** [comment]
It was done in 1.1.0 and later.  not backported as faras i know.
