### ISSUE TITLE
Enter the patch of "master" branch,  Under what conditions will the "openssl-3.0" branch be merged

### ISSUE THREAD

**Issue by shipujin** [openssl/openssl#18806]
Hi,
Ask a question，enter the [patch](https://github.com/openssl/openssl/commit/b625e21e67666213ffd3ba6b1f2cd8a847ba6b66) of "master" branch,  Under what conditions will the "openssl-3.0" branch be merged, thanks~

**Comment by levitte** [comment]
Do you mean, under what conditions will the patch also be applied to the openssl-3.0 branch?  Anything that is a bug fix or a documentation fix.  If it's a new feature, it won't be applied to the openssl-3.0 branch.

What is a bug fix vs a new feature is determined on a case by case basis, subject to what reviewers say, and ultimately determined by the OTC.

**Comment by shipujin** [comment]
I submitted a new architecture to support [patch](https://github.com/openssl/openssl/commit/b625e21e67666213ffd3ba6b1f2cd8a847ba6b66) to the master branch of openssl,
master branch has merged the [patch](https://github.com/openssl/openssl/commit/b625e21e67666213ffd3ba6b1f2cd8a847ba6b66),
But now I want to use it in the "openssl-3.0" branch of openssl, do I need to resubmit patch to the "openssl-3.0" branch，
thanks~

**Comment by levitte** [comment]
Aha, from #17712.  A new config targets is a new feature, so is not eligible for adding to release branches.  Exceptions from this must be discussed by OTC and have a very good reason for being added to release branches.

**Comment by t8m** [comment]
@levitte  But new architecture targets do not require explicit exception if they do not require any code changes to be added.

**Comment by t8m** [comment]
Citing the stable release updates policy. `The addition of new platforms to LTS branches is acceptable so long as the required changes consist solely of additions to configuration.`

**Comment by t8m** [comment]
@shipujin create a PR against the 3.0 branch please.

**Comment by levitte** [comment]
> Citing the stable release updates policy. `The addition of new platforms to LTS branches is acceptable so long as the required changes consist solely of additions to configuration.`

Ah!  Thanks for the heads up, I totally forgot about that

**Comment by shipujin** [comment]
> @shipujin create a PR against the 3.0 branch please.

Ok, I created a PR for OpenSSL-3.0, thanks~

**Comment by shipujin** [comment]
Thank you for your answers. Thank you
I created a new PR
https://github.com/openssl/openssl/pull/18807
