### ISSUE TITLE
OpenSSL3 compatibility ?

### ISSUE THREAD

**Issue by jiapei100** [openssl/openssl#18815]
Can anybody help to take a look at this???

[https://github.com/Azure/azure-c-shared-utility/issues/601](https://github.com/Azure/azure-c-shared-utility/issues/601)

Thank you ...

**Comment by paulidale** [comment]
Either don't use deprecated functions or don't error when using them.

**Comment by ericwol-msft** [comment]
@jiapei100, that was a very snarky answer. Please be helpful in your future posts. 

**Define OPENSSL_NO_DEPRECATED instead. The macro OPENSSL_NO_DEPRECATED_3_0 is for internal use.**
