### ISSUE TITLE
DH_METHOD and providers

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#18817]
I wonder how does DH_METHOD works together with providers. 

DH_METHOD is a part of `DH` structure. 
In case of FIPS provider we refer to a particular implementation:
https://github.com/openssl/openssl/blob/af801ec89205aaf6ebf8522d510d0b1fc29e3233/crypto/dh/dh_key.c#L114-L118

But this particular implementation, in turn, implicitly relies on DH_METHOD:
https://github.com/openssl/openssl/blob/af801ec89205aaf6ebf8522d510d0b1fc29e3233/crypto/dh/dh_key.c#L80-L84

**Comment by mattcaswell** [comment]
In the case of the FIPS provider it is not possible to change the `DH_METHOD` (e.g. `DH_set_default_method` has no effect there). For the default provider it remains possible to change it.
