### ISSUE TITLE
Issue during upgrade from 1.0.2m to 3.0.4

### ISSUE THREAD

**Issue by pospione** [openssl/openssl#18826]
I am using 3DES (des_ede3_cbc) algorithm to encode and decode some information like following codes.
Following codes have worked well in Version 1.0.2m.
I have decided to upgrade 3.0.4 to avoid security issues announced from openssl.
but, I have got some issue during upgrade to 3.0.4.
Encoding is working well, but Decoding has problem about source length.

Originally, if the length of encrypted information is 16, I put 16 as nSourceLength in following function. 

	if (1 != EVP_DecryptUpdate(ctx, decodeBuf, &nOutLength, source, nSourceLength))

In 3.0.4, if I put 16 as nSourceLength, above function is decoding only 8 bytes. 
if I put 17 as nSourceLength, only then above function is decoding 16 bytes.

but if I am using other function like EVP_des_ede3_ofb instead of EVP_des_ede3_cbc, it's working well.
So, I tested various 3DES functions. Some is working well, some is working like des_ede3_cbc

I want to know why I have to put 1 + length of encrypted information as nSourceLength when using EVP_des_ede3_cbc.

Thanks in advance.

ho young.

'''
extern "C" __declspec(dllexport) int EncodeDES_EDE3_CBC(unsigned char *source, int nSourceLength, unsigned char *encodeBuf, unsigned char *key)
{
	EVP_CIPHER_CTX *ctx;
	DES_cblock iv;

	memset(iv, 0, 8);
	DES_set_odd_parity(&iv);

	ctx = EVP_CIPHER_CTX_new();
	if (ctx == NULL)
		return 0;

	if (1 != EVP_EncryptInit(ctx, EVP_des_ede3_cbc(), key, iv))
	{
		EVP_CIPHER_CTX_free(ctx);
		return 0;
	}

	int nOutLength;

	if (1 != EVP_EncryptUpdate(ctx, encodeBuf, &nOutLength, source, nSourceLength))
	{
		EVP_CIPHER_CTX_free(ctx);
		return 0;
	}

	EVP_CIPHER_CTX_free(ctx);

	return 1;
}
'''
'''
extern "C" __declspec(dllexport) int DecodeDES_EDE3_CBC(unsigned char *source, int nSourceLength, unsigned char *decodeBuf, unsigned char *key)
{
	EVP_CIPHER_CTX* ctx;
	DES_cblock iv;

	memset(iv, 0, 8);
	DES_set_odd_parity(&iv);

	ctx = EVP_CIPHER_CTX_new();
	if (ctx == NULL)
		return 0;

	if (1 != EVP_DecryptInit(ctx, EVP_des_ede3_cbc(), key, iv))
	{
		EVP_CIPHER_CTX_free(ctx);
		return 0;
	}

	int nOutLength;

	if (1 != EVP_DecryptUpdate(ctx, decodeBuf, &nOutLength, source, nSourceLength))
	{
		EVP_CIPHER_CTX_free(ctx);
		return 0;
	}

	EVP_CIPHER_CTX_free(ctx);

	return 1;
}
'''

**Comment by t8m** [comment]
By default the padding is enabled. Use EVP_CIPHER_CTX_set_padding to disable it.

**Comment by pospione** [comment]
Thanks for your comments.
It was resolved.
You are great!!!
