### ISSUE TITLE
PEM_write() causes segfault with header=NULL

### ISSUE THREAD

**Issue by liweitianux** [openssl/openssl#18825]
Hi, I just came across this segfault issue with `PEM_write()` when the `header` argument is `NULL`.

According to the [PEM_write(3)](https://www.openssl.org/docs/manmaster/man3/PEM_write.html) man page (bold format by me):

> PEM_write() writes to the file fp, while PEM_write_bio() writes to the BIO bp. The name is the name to use in the marker, the header is the header value **or NULL**, and data and len specify the data and its length.

So one could pass the `header` argument as `NULL` when there is no one.

However, the code just passes the `NULL` to `strlen(header)` and thus causes the segfault issue:

https://github.com/openssl/openssl/blob/master/crypto/pem/pem_lib.c#L627

```c
int PEM_write_bio(BIO *bp, const char *name, const char *header,
                  const unsigned char *data, long len)
{
...
    i = strlen(header);
...
```

If I pass an empty string (i.e., `""`) to `header`, then `PEM_write()` works as expected.

So the current code contradicts the documentation, and I believe it should be fixed.

Thanks.

**Comment by valdaarhun** [comment]
Hi. I have gone through this part of the code. I think adding an `if` check should fix this. I would like to take this up.
