### ISSUE TITLE
Configure Android arm64 fails on macOS 12.4 / ndk 20.0.5594570

### ISSUE THREAD

**Issue by rajohns08** [openssl/openssl#18844]
I'm on the `openssl-3.0.5` tag. I'm on an Intel Macbook Pro.

When executing:

```
export ANDROID_NDK_ROOT=~/Library/Android/sdk/ndk/20.0.5594570
PATH=$PATH:$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/bin:$ANDROID_NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin
./Configure android-arm64 -D__ANDROID_API__=29
```

I see the following output:
```
Configuring OpenSSL version 3.0.5 for target android-arm64
Using os-specific seed configuration

Failure!  build file wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

no NDK aarch64-linux-android-gcc on $PATH at (eval 13) line 142.
```

I searched and note that there are no *gcc files anywhere in the $ANDROID_NDK_ROOT. Moreover, the [NOTES-ANDROID.md](https://github.com/openssl/openssl/blob/openssl-3.0.5/NOTES-ANDROID.md) correctly calls out that in ndk > 19 (which I am on), configure should be invoking *clang and not *gcc. So why is the error output complaining about no *gcc when the NOTES-ANDROID implies it should be looking for *clang?

**Comment by xtkoba** [comment]
The `PATH` environment variable must be set so that `command -v clang` outputs the path to the NDK clang:

https://github.com/openssl/openssl/blob/c00fd2dece8ba54b2597a61c8db6a001025d05d5/NOTES-ANDROID.md#L62-L63

Typically, `PATH` should be set as

```bash
PATH=$ANDROID_NDK_ROOT/some/where:$PATH
```

instead of

```bash
PATH=$PATH:$ANDROID_NDK_ROOT/some/where # mostly this does not work
```

**Comment by rajohns08** [comment]
Thank you, that worked!
