### ISSUE TITLE
InterlockedOr64() breaks compatibility with Windows versions older than Vista

### ISSUE THREAD

**Issue by davidebeatrici** [openssl/openssl#18855]
SoftEtherVPN/SoftEtherVPN#1631

https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedor64

https://github.com/openssl/openssl/blob/eeb612021e220de734e1ff08499f42bb962c3916/crypto/threads_win.c#L207-L218

**Comment by dnobori** [comment]
https://github.com/openssl/openssl/pull/18856

**Comment by mdounin** [comment]
Note that the fix committed does not seem to address the case of newer compilers, such as MSVC2010, when Windows XP support is explicitly requested with `-D_WIN32_WINNT=0x0501`.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
