### ISSUE TITLE
X509_VERIFY_PARAM_move_peername doesn't duplicate string resulting in double free

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#1885]
`X509_VERIFY_PARAM_move_peername` doesn't create a copy of the `->peername` field, which will result in a double free.

**Comment by mattcaswell** [comment]
Why does this result in a double free? Before the call there is a single reference to peername in the "from" structure, and afterwards there is a single reference in the "to" structure...I don't see the double free here?

**Comment by daurnimator** [comment]
My mistake. I thought it didn't NULL out from (I.e. Was a copy, not a move) 

Is there a way to do a copy instead?

**Comment by mattcaswell** [comment]
Hmmm....not that I can see.

**Comment by daurnimator** [comment]
With the object lacking reference counting, I think a way to perform a copy of all members is important.

**Comment by vdukhovni** [comment]
That particular field is not an *input* parameter for certificate verification.  It is rather an ephemeral *output* field of verification via X509_verify_cert().  The caller of X509_verify_cert() (typically the SSL layer) then moves the result into stable storage of its own, disassociating it from X509_VERIFY_PARAMs.

Once the SSL handle takes control of the result, it can be accessed repeatedly via SSL_get0_peername().

**Comment by daurnimator** [comment]
> That particular field is not an input parameter for certificate verification. It is rather an ephemeral output field of verification via X509_verify_cert(). The caller of X509_verify_cert() (typically the SSL layer) then moves the result into stable storage of its own, disassociating it from X509_VERIFY_PARAMs.

I wish to have an `X509_VERIFY_PARAM` outlive the verify callback deep inside of `SSL_do_handshake` (e.g. for the construction of nicer error messages). The problem I had was that "copying" via `X509_VERIFY_PARAM_set1` doesn't copy (or move) across the `peername` field.
Is it save to use `X509_VERIFY_PARAM_move_peername` from inside of a verify callback? (I could imagine the caller still wanting the field). Even if so: wouldn't having a non-destructive method be clearer?

**Comment by vdukhovni** [comment]
I wanted to clear that field as quickly as possible.  Think of it as a function return value from X509_verify_cert() that for lack of a better channel lingers briefly in X509_VERIFY_PARAM.
If the value is kept around longer there is a security risk of it being misinterpreted in the wrong context.

**Comment by mattcaswell** [comment]
Can you not call `X509_VERIFY_PARAM_get0_peername()` from your callback and then `strdup()` to stash it away somewhere?

**Comment by daurnimator** [comment]
> Can you not call X509_VERIFY_PARAM_get0_peername() from your callback and then strdup() to stash it away somewhere?

Well I *can*. But it means I just end up with a structure of:
```C
struct {
    X509_VERIFY_PARAM* xvp;
    char *str;
}
```
.... when there's already a perfectly good member for that (just there's no setter for it)

**Comment by vdukhovni** [comment]
Yes, but this is safer, than leaving stale verification result data in a structure that is primarily intended to convey verification input parameters.  It is a trade-off.  If you know what you're doing and really need the data you can get it.  E.g. create your param structure and call "move", plus many other ways.

I am inclined to leave the safer interface in place. Some thought (whether ultimately correct or not) went into choosing the current design, it was not an oversight.
