### ISSUE TITLE
CI: cancel Windows builds when any of the *nix builds fails

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#18851]
Unfortunately, nobody has so far spent sufficient energy in significantly speeding up the Windows builds,
which would be possible by making use of Microsoft's (as often) non-standard way of parallelizing C compilation.

When any of the other CI runs fails, it usually is not of much help to let those painfully slow Windows builds continue,
so I suggest stopping them such that the CI machine is relieved from this burden and the user more quickly get the final CI result.

**Comment by levitte** [comment]
Do you have an idea how to do this?

**Comment by DDvO** [comment]
I thought something like this was already done in other situations because sometimes I noticed that some of the CI builds got canceled.
So I was hoping some CI expert would know how to do this.

**Comment by levitte** [comment]
Ah yeah, that's something included in github actions, when you have multiple targets for the same job.  Example:

https://github.com/openssl/openssl/blob/54a84f02998b72fa63cd5309d915e43cfd85a06b/.github/workflows/windows.yml#L20-L28

However, I don't know that there is a cross-job mechanism that does something similar...

**Comment by t8m** [comment]
IMO this would be non-trivial to do and not worth the effort.

**Comment by DDvO** [comment]
> IMO this would be non-trivial to do and not worth the effort.

So closing this FR.
