### ISSUE TITLE
How to sign with RSA PSS mode

### ISSUE THREAD

**Issue by Chaos-Crypto** [openssl/openssl#18869]
Hello, I want to use RSA PSS mode to sign,but the command I cannot find, could you give me some advises or examples? Thank you very much.

**Comment by mattcaswell** [comment]
It's unclear from your question whether you are asking about the OpenSSL command line application, or the libcrypto library. Are you looking for API examples or command line examples?

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
