### ISSUE TITLE
EVP API to know whether certain hash or symmetric algo is disabled by the crypto policy?

### ISSUE THREAD

**Issue by ni4** [openssl/openssl#18867]
I'm attempting to check programmatically whether certain OpenSSL 3.0 distribution supports certain hash (SHA-1 at the moment), or symmetric algorithm (like IDEA). However, on systems where those are disabled by the default crypto policy (Centos 9 Stream with SHA-1), I don't see a way to check that programmatically: `EVP_MD_fetch()`, `EVP_get_digestbyname()`  and other APIs return it as available. However, further functions, like `EVP_PKEY_CTX_set_signature_md()` fail.

Do I miss some other API to check for algo availability/using those functions in non-expected way?

P.S. Both legacy and default crypto providers are loaded via the `OSSL_PROVIDER_load()`.

**Comment by beldmit** [comment]
No, there is no EVP API for this purpose. Cryptopolicies have currently nothing to do with openssl upstream.

**Comment by beldmit** [comment]
In practice you can check whether `EVP_PKEY_CTX_set_signature_md` fails when the digest is fetchable. But nothing more direct :(

**Comment by t8m** [comment]
The problem is that the SHA1 in the crypto policies case is disabled for the signature API only. You can still use it as a plain message digest function. And there is no EVP api apart from trying to actually use it that would give you the information whether it will work or not.

**Comment by ni4** [comment]
Thanks for your replies! At this exact case `EVP_PKEY_CTX_set_signature_md()` try with manual PKCS#1.5 encoding as workaround should work fine. 

Details of the usecase if anyone interested: this is needed for Thunderbird's OpenPGP backend, [RNP](https://github.com/rnpgp/rnp/) , which as a possible option may use OpenSSL crypto backend for systems which doesn't ship Botan. While SHA1 in the OpenPGP world is (almost) ready to be deprecated for the document signatures, we experienced that it is still needed (via SHA1CD code) for the key signatures.

**Comment by beldmit** [comment]
It's a bad practice to use SHA1 for signatures nowadays

**Comment by ni4** [comment]
> It's a bad practice to use SHA1 for signatures nowadays

Agree on that. But reality shows that many users value their convenience (or better say inconvenience of changing something) much higher :-)
