### ISSUE TITLE
Memory corruption issue, crash at OPENSSL_free

### ISSUE THREAD

**Issue by TyphoonWu** [openssl/openssl#18884]
Platform: Android 12
Description:
1. Enable HWASAN detect corruption issue in libcrypto.so, crash tombstone info:
    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xxxx/PD2217/PD2217:12/SP2A.220305.013/compiler06222014:userdebug/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-07-12 16:24:51.287189180+0800
Process uptime: 0s
Cmdline: com.baidu.map.location
pid: 31733, tid: 31747, name: FinalizerDaemon  >>> com.baidu.map.location <<<
uid: 10044
tagged_addr_ctrl: 0000000000000001
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '==31733==ERROR: HWAddressSanitizer: tag-mismatch on address 0x00379d48ca60 at pc 0x00799d33f368
READ of size 8 at 0x00379d48ca60 tags: 03/0b (ptr/mem) in thread T31
    '#0 0x799d33f364  (/system/lib64/libcrypto.so+0xbb364)
    '#1 0x799d2e3648  (/system/lib64/libcrypto.so+0x5f648)
    '#2 0x799d2ebdf8  (/system/lib64/libcrypto.so+0x67df8)
    '#3 0x799d2ebc84  (/system/lib64/libcrypto.so+0x67c84)
    '#4 0x799d2eba28  (/system/lib64/libcrypto.so+0x67a28)
    '#5 0x799d2ebc3c  (/system/lib64/libcrypto.so+0x67c3c)
    '#6 0x799d2eba28  (/system/lib64/libcrypto.so+0x67a28)
    '#7 0x799d2ebc84  (/system/lib64/libcrypto.so+0x67c84)
    '#8 0x799d2eba28  (/system/lib64/libcrypto.so+0x67a28)
    '#9 0x799d2eb824  (/system/lib64/libcrypto.so+0x67824)
    '#10 0x79b7222244  (/apex/com.android.art/lib64/libart.so+0x222244)
    '#11 0x79b7211d0c  (/apex/com.android.art/lib64/libart.so+0x211d0c)

[0x00379d48ca60,0x00379d48ca80) is a small allocated heap chunk; size: 32 offset: 0
0x00379d48ca60 is located 288 bytes to the left of 19-byte region [0x00379d48cb80,0x00379d48cb93)
allocated here:
    '#0 0x79d2e52b84  (/apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so+0x1db84)
    '#1 0x79e858ee70  (/apex/com.android.runtime/lib64/bionic/libc.so+0x47e70)
    '#2 0x79c59dde10  (/system/lib64/liblog.so+0xee10)
    '#3 0x79c59d569c  (/system/lib64/liblog.so+0x669c)
    '#4 0x79c59d558c  (/system/lib64/liblog.so+0x658c)
    '#5 0x79e17b2ef0  (/system/lib64/libbase.so+0x17ef0)
    '#6 0x79e17b2c58  (/system/lib64/libbase.so+0x17c58)
    '#7 0x79bf6fe834  (/apex/com.android.art/lib64/libartbase.so+0x2f834)
    '#8 0x79e17b533c  (/system/lib64/libbase.so+0x1a33c)
    '#9 0x79c59d59d0  (/system/lib64/liblog.so+0x69d0)
    '#10 0x79c59d58e4  (/system/lib64/liblog.so+0x68e4)
    '#11 0x79cbb12e6c  (/system/lib64/libandroid_runtime.so+0x100e6c)
    '#12 0x70d09830  (/system/framework/arm64/boot-framework.oat+0x1a8830)

Thread: T0 0x007000002000 stack: [0x007fecc14000,0x007fed414000) sz: 8388608 tls: [0x0079fb01efc0,0x0079fb022000)
Thread: T48 0x007000066000 stack: [0x00799f175000,0x00799f27ecb0) sz: 1088688 tls: [0x00799f27efc0,0x00799f282000)
Thread: T53 0x00700000e000 stack: [0x0079a2cd2000,0x0079a2ddbcb0) sz: 1088688 tls: [0x0079a2ddbfc0,0x0079a2ddf000)
Thread: T46 0x00700005e000 stack: [0x00799f489000,0x00799f592cb0) sz: 1088688 tls: [0x00799f592fc0,0x00799f596000)
Thread: T50 0x00700006e000 stack: [0x00799ef59000,0x00799f062cb0) sz: 1088688 tls: [0x00799f062fc0,0x00799f066000)
Thread: T25 0x00700000a000 stack: [0x0079ac302000,0x0079ac3fbcb0) sz: 1023152 tls: [0x0079ac3fbfc0,0x0079ac3ff000)
Thread: T26 0x00700001a000 stack: [0x0079a3bf0000,0x0079a3cf9cb0) sz: 1088688 tls: [0x0079a3cf9fc0,0x0079a3cfd000)
Thread: T27 0x00700001e000 stack: [0x0079a3ae2000,0x0079a3bebcb0) sz: 1088688 tls: [0x0079a3bebfc0,0x0079a3bef000)
Thread: T28 0x007000022000 stack: [0x0079a3e04000,0x0079a3efdcb0) sz: 1023152 tls: [0x0079a3efdfc0,0x0079a3f01000)
Thread: T29 0x007000026000 stack: [0x0079a3f02000,0x0079a3ffbcb0) sz: 1023152 tls: [0x0079a3ffbfc0,0x0079a3fff000)
Thread: T30 0x00700002a000 stack: [0x0079a3cfe000,0x0079a3dffcb0) sz: 1055920 tls: [0x0079a3dfffc0,0x0079a3e03000)
Thread: T31 0x00700002e000 stack: [0x0079a39d4000,0x0079a3addcb0) sz: 1088688 tls: [0x0079a3addfc0,0x0079a3ae1000)
Thread: T32 0x007000032000 stack: [0x0079a38c6000,0x0079a39cfcb0) sz: 1088688 tls: [0x0079a39cffc0,0x0079a39d3000)
Thread: T33 0x007000036000 stack: [0x0079a37c8000,0x0079a38c1cb0) sz: 1023152 tls: [0x0079a38c1fc0,0x0079a38c5000)
Thread: T34 0x00700003a000 stack: [0x0079a3302000,0x0079a33fbcb0) sz: 1023152 tls: [0x0079a33fbfc0,0x0079a33ff000)
Thread: T35 0x00700003e000 stack: [0x0079a3204000,0x0079a32fdcb0) sz: 1023152 tls: [0x0079a32fdfc0,0x0079a3301000)
Thread: T36 0x007000042000 stack: [0x0079a2fc7000,0x0079a30d0cb0) sz: 1088688 tls: [0x0079a30d0fc0,0x0079a30d4000)
Thread: T37 0x007000046000 stack: [0x00799fc0b000,0x00799fd04cb0) sz: 1023152 tls: [0x00799fd04fc0,0x00799fd08000)
Thread: T38 0x00700004a000 stack: [0x00799fa0f000,0x00799fb08cb0) sz: 1023152 tls: [0x00799fb08fc0,0x00799fb0c000)
Thread: T40 0x00700004e000 stack: [0x00799f8c1000,0x00799f9cacb0) sz: 1088688 tls: [0x00799f9cafc0,0x00799f9ce000)
Thread: T49 0x00700006a000 stack: [0x00799f067000,0x00799f170cb0) sz: 1088688 tls: [0x00799f170fc0,0x00799f174000)
Thread: T42 0x007000056000 stack: [0x00799f6a5000,0x00799f7aecb0) sz: 1088688 tls: [0x00799f7aefc0,0x00799f7b2000)
Thread: T186 0x007000016000 stack: [0x0079a1716000,0x0079a180fcb0) sz: 1023152 tls: [0x0079a180ffc0,0x0079a1813000)
Thread: T602 0x007000012000 stack: [0x00799fef2000,0x00799fffbcb0) sz: 1088688 tls: [0x00799fffbfc0,0x00799ffff000)
Memory tags around the buggy address (one tag corresponds to 16 bytes):
  0x007479d48c20: 1c  1c  b7  df  e5  e5  96  96  da  da  82  82  b4  b4  a5  06 
  0x007479d48c30: 0a  0d  d2  69  89  0f  79  08  a5  a5  59  59  87  87  20  20 
  0x007479d48c40: 63  63  0a  a0  75  75  f8  09  61  a3  ce  ce  0b  f4  ef  ef 
  0x007479d48c50: 73  08  40  40  d1  d1  94  94  e9  e9  63  63  f5  f5  43  43 
  0x007479d48c60: 8b  8b  bc  bc  68  68  1a  1a  d0  01  ed  ed  0b  9f  d9  d9 
  0x007479d48c70: 20  20  8d  8d  0b  54  69  69  52  52  0b  42  5e  5e  c4  c4 
  0x007479d48c80: 16  16  0a  33  40  40  a0  a0  4e  0d  c4  c4  c0  c0  a7  a7 
  0x007479d48c90: 0b  80  8b  8b  7e  7e  d2  d2  0b  a6  b7  b7  cf  cf  d3  d3 
=>0x007479d48ca0: 1a  1a  fe  fe  32  08 [0b] 79  72  72  0b  b1  d4  d4  94  94 
  0x007479d48cb0: c6  78  2e  2e  e9  07  70  01  84  03  05  0b  08  08  84  84 
  0x007479d48cc0: 0a  4c  4e  4e  34  34  0e  ac  9f  9f  7c  7c  8b  0d  2f  d0 
  0x007479d48cd0: e8  e8  a2  5f  0b  f6  59  59  be  be  1f  1f  23  7d  64  64 
  0x007479d48ce0: 3a  3a  0b  41  0b  6a  f2  f2  a8  a8  80  80  0b  44  80  80 
  0x007479d48cf0: 4b  4b  92  06  0b  14  01  01  c9  b8  8d  8d  4f  cf  8f  0f 
  0x007479d48d00: d7  d7  69  08  cf  cf  17  a8  25  25  66  66  bc  bc  dd  05 
  0x007479d48d10: 0b  fb  f4  f4  75  75  71  91  50  50  61  2f  d8  d8  cf  cf 
  0x007479d48d20: f5  f5  55  06  15  15  d6  d6  93  93  ba  ba  ee  ee  1e  1e 
Tags for short granules around the buggy address (one tag corresponds to 16 bytes):
  0x007479d48c90: 78  ..  ..  ..  ..  ..  ..  ..  46  ..  ..  ..  ..  ..  ..  .. 
=>0x007479d48ca0: ..  ..  ..  ..  ..  32 [b3] ..  ..  ..  7a  ..  ..  ..  ..  .. 
  0x007479d48cb0: ..  ..  ..  ..  ..  00  ..  70  ..  84  69  05  00  00  ..  .. 
See https://clang.llvm.org/docs/HardwareAssistedAddressSanitizerDesign.html'#short-granules for a description of short granule tags
Registers where the failure occurred (pc 0x00799d33f368):
    x0  030000379d48ca68  x1  000000799d3e64a8  x2  0000000000000000  x3  000000379d49ef00
    x4  0000000000000020  x5  0000000000000014  x6  00000079a39d4000  x7  0000000000000001
    x8  0000000000000000  x9  0000007100000000  x10 000000799d2ebde8  x11 0000000000000058
    x12 0000000000000050  x13 0000000000000000  x14 000000000000f574  x15 00000c310ee46269
    x16 00000079d2e734c0  x17 00000079d2e566ac  x18 0000006d2f808000  x19 030000379d48ca60
    x20 0000007100000000  x21 f50000389d4ee068  x22 f50000389d4ee060  x23 000000799d3f1e98
    x24 00000079a3adbb70  x25 00000079a3ade000  x26 0040000e00005a06  x27 0000000000000002
    x28 00000079a3adbe40  x29 00000079a3adbb00  x30 000000799d33f368
SUMMARY: HWAddressSanitizer: tag-mismatch (/system/lib64/libcrypto.so+0xbb364) 
'
    x0  0000000000000000  x1  0000000000007c03  x2  0000000000000006  x3  ef000079a3adb730
    x4  00000079a3adb7b0  x5  0000000080808080  x6  0000000080808080  x7  8080808080808080
    x8  00000000000000f0  x9  00000079a3adb730  x10 000000789a3adb7b  x11 ef000079a3adb7b0
    x12 0000000000000000  x13 00000000000000ef  x14 02000070ffffffff  x15 000000079a3adb53
    x16 00000000000000ef  x17 00000079e861ae40  x18 0000006d2f808000  x19 6f000079a3adb7b0
    x20 0200007100000000  x21 2f000079a3adb720  x22 af000079a3adb700  x23 ef000079a3adb730
    x24 0000000000007bf5  x25 0000000000007c03  x26 00000000ffffffff  x27 0000000000000000
    x28 000000379d48ca60  x29 00000079a3adb830
    lr  00000079e85a4e58  sp  00000079a3adb700  pc  00000079e85a4e70  pst 0000000060001000

backtrace:
      '#00 pc 000000000005de70  /apex/com.android.runtime/lib64/bionic/libc.so (abort+360) (BuildId: 6b7f9749000a73aa8173911131a9d6d6)
      '#01 pc 000000000002b710  /apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so (__sanitizer::Abort()+60) (BuildId: c43f06ecec3119e9e2e588c25348b5a62e819c42)
      '#02 pc 000000000002a5f8  /apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so (__sanitizer::Die()+204) (BuildId: c43f06ecec3119e9e2e588c25348b5a62e819c42)
      '#03 pc 0000000000020cbc  /apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so (__hwasan::ScopedReport::~ScopedReport()+156) (BuildId: c43f06ecec3119e9e2e588c25348b5a62e819c42)
      '#04 pc 0000000000021358  /apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so (__hwasan::ReportTagMismatch(__sanitizer::StackTrace*, unsigned long, unsigned long, bool, bool, unsigned long*)+684) (BuildId: c43f06ecec3119e9e2e588c25348b5a62e819c42)
      '#05 pc 000000000001e96c  /apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so (__hwasan::HandleTagMismatch(__hwasan::AccessInfo, unsigned long, unsigned long, ucontext*, unsigned long*)+236) (BuildId: c43f06ecec3119e9e2e588c25348b5a62e819c42)
      '#06 pc 000000000001e87c  /apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so (__hwasan_tag_mismatch4+108) (BuildId: c43f06ecec3119e9e2e588c25348b5a62e819c42)
      '#07 pc 00000000000216f0  /apex/com.android.runtime/lib64/bionic/libclang_rt.hwasan-aarch64-android.so (__hwasan_tag_mismatch+140) (BuildId: c43f06ecec3119e9e2e588c25348b5a62e819c42)
      '#08 pc 00000000000bb364  /system/lib64/libcrypto.so (OPENSSL_free+52) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#09 pc 000000000005f648  /system/lib64/libcrypto.so (ASN1_OBJECT_free+140) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#10 pc 0000000000067df8  /system/lib64/libcrypto.so (ASN1_primitive_free+304) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#11 pc 0000000000067c84  /system/lib64/libcrypto.so (ASN1_template_free+284) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#12 pc 0000000000067a28  /system/lib64/libcrypto.so (asn1_item_combine_free+464) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#13 pc 0000000000067c3c  /system/lib64/libcrypto.so (ASN1_template_free+212) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#14 pc 0000000000067a28  /system/lib64/libcrypto.so (asn1_item_combine_free+464) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#15 pc 0000000000067c84  /system/lib64/libcrypto.so (ASN1_template_free+284) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#16 pc 0000000000067a28  /system/lib64/libcrypto.so (asn1_item_combine_free+464) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#17 pc 0000000000067824  /system/lib64/libcrypto.so (ASN1_item_free+112) (BuildId: 601d5d040d730c36af43ddecd0f340ce)
      '#18 pc 0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#19 pc 0000000000211d0c  /apex/com.android.art/lib64/libart.so (nterp_helper+1948) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#20 pc 0000000000034774  /apex/com.android.conscrypt/javalib/conscrypt.jar (com.android.org.conscrypt.OpenSSLX509Certificate.finalize+16)
      '#21 pc 00000000020f20f4  /memfd:jit-cache (deleted) (java.lang.Daemons$FinalizerDaemon.doFinalize+260)
      '#22 pc 00000000020ecb20  /memfd:jit-cache (deleted) (java.lang.Daemons$FinalizerDaemon.runInternal+544)
      '#23 pc 0000000000218c7c  /apex/com.android.art/lib64/libart.so (art_quick_osr_stub+60) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#24 pc 0000000000575a94  /apex/com.android.art/lib64/libart.so (art::jit::Jit::MaybeDoOnStackReplacement(art::Thread*, art::ArtMethod*, unsigned int, int, art::JValue*)+836) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#25 pc 0000000000bb31c0  /apex/com.android.art/lib64/libart.so (MterpMaybeDoOnStackReplacement+368) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#26 pc 0000000000208350  /apex/com.android.art/lib64/libart.so (MterpHelpers+240) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#27 pc 00000000000299be  /apex/com.android.art/javalib/core-libart.jar (java.lang.Daemons$FinalizerDaemon.runInternal+178)
      '#28 pc 0000000000b8ffa4  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+5784) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#29 pc 0000000000203814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#30 pc 00000000000296b6  /apex/com.android.art/javalib/core-libart.jar (java.lang.Daemons$Daemon.run+50)
      '#31 pc 0000000000b9bc28  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+5608) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#32 pc 0000000000203a14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#33 pc 00000000000ef030  /apex/com.android.art/javalib/core-oj.jar (java.lang.Thread.run+8)
      '#34 pc 000000000051af30  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+944) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#35 pc 0000000000b6fb30  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+2284) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#36 pc 0000000000222378  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#37 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#38 pc 00000000002c775c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+464) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#39 pc 0000000000966420  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+564) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#40 pc 0000000000968588  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+932) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#41 pc 00000000009f4048  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+2636) (BuildId: 0b6c29c9f5060bcca82de5ad1654dd53)
      '#42 pc 00000000000f2254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+140) (BuildId: 6b7f9749000a73aa8173911131a9d6d6)
      '#43 pc 0000000000060988  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 6b7f9749000a73aa8173911131a9d6d6)

2. the code the same as: https://android.googlesource.com/platform/external/boringssl/+/refs/tags/android-mainline-12.0.0_r126/src/crypto/asn1/
3.  Parse backtrace frame 08~17
    llvm-addr2line -Cfie libcrypto.so 00000000000bb364 000000000005f648 0000000000067df8 0000000000067c84 0000000000067a28 0000000000067c3c 0000000000067a28 0000000000067c84 0000000000067a28 0000000000067824
    OPENSSL_free
    external/boringssl/src/crypto\mem.c:149
    ASN1_OBJECT_free
    external/boringssl/src/crypto/asn1\a_object.c:258
    ASN1_primitive_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:209
    ASN1_template_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:180
    asn1_item_combine_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:155
    ASN1_template_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:175
    asn1_item_combine_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:155
    ASN1_template_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:180
    asn1_item_combine_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:155
    ASN1_item_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:70

**Comment by TyphoonWu** [comment]
2. the code the same as: https://android.googlesource.com/platform/external/boringssl/+/refs/tags/android-mainline-12.0.0_r126/src/crypto/asn1/
3.  Parse backtrace frame #08~#17
    llvm-addr2line -Cfie libcrypto.so 00000000000bb364 000000000005f648 0000000000067df8 0000000000067c84 0000000000067a28 0000000000067c3c 0000000000067a28 0000000000067c84 0000000000067a28 0000000000067824
    OPENSSL_free
    external/boringssl/src/crypto\mem.c:149
    ASN1_OBJECT_free
    external/boringssl/src/crypto/asn1\a_object.c:258
    ASN1_primitive_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:209
    ASN1_template_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:180
    asn1_item_combine_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:155
    ASN1_template_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:175
    asn1_item_combine_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:155
    ASN1_template_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:180
    asn1_item_combine_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:155
    ASN1_item_free
    external/boringssl/src/crypto/asn1\tasn_fre.c:70

**Comment by t8m** [comment]
This is boringssl and not OpenSSL.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
