### ISSUE TITLE
Regression in AES-GCM on Alpha and Arm platforms after the GCM refactoring

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#18896]
The on-push cross-compile builds in CI for Alpha and Arm platforms fail since the GCM refactoring was merged.

See: https://github.com/openssl/openssl/runs/7468446782?check_suite_focus=true https://github.com/openssl/openssl/runs/7468446918?check_suite_focus=true

Perhaps something like https://github.com/openssl/openssl/commit/48e35b99bd0071207cfe39da22eb2502db5c09dc will be needed?

**Comment by tmshort** [comment]
Despite the face that the PR CIs all passed... :(

**Comment by tmshort** [comment]
Thanks @t8m for the PR.

**Comment by paulidale** [comment]
The PR CIs only compile the source code for each platform.
The on commit CIs also do this but then run the tests using qemu.

The reason is that running the tests is glacially slow for multiple emulated platforms.
