### ISSUE TITLE
oqsprovider external test failing on master

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#18898]
The last two github CI master builds have failed in the oqsprovider external test:

https://github.com/openssl/openssl/runs/7551684870?check_suite_focus=true
https://github.com/openssl/openssl/runs/7554971041?check_suite_focus=true

But the one before that was fine:

https://github.com/openssl/openssl/runs/7541090009?check_suite_focus=true

The PR that got pushed where the state seemed to change (#18878) is a documentation only change so it doesn't seem like it could be the culprit. So I'm not sure what's changed to cause this.

**Comment by mattcaswell** [comment]
@baentsch

**Comment by t8m** [comment]
I am already working on this - at least with temporary fix.

**Comment by t8m** [comment]
Fix in #18899 hopefully.
