### ISSUE TITLE
Using OpenSSL 3 in code: Converting DES_crypt to EVP APIs

### ISSUE THREAD

**Issue by jmbords** [openssl/openssl#18890]
As stated in OpenSSL 3, DES_crypt macro is deprecated. We are encouraged to use the sequence EVP_EncryptInit_ex(3), EVP_EncryptUpdate(3) and EVP_EncryptFinal_ex(3) as stated here: https://www.openssl.org/docs/manmaster/man3/DES_crypt.html

Our old code is like this
```
char* theDESCrypt (const char *myBuf, const char *mySalt)
{
    // some code here
    // ...
    return DES_crypt(myBuf, mySalt);
}
```

Is the following converted code correct?
```
char* theDESCrypt (const char *myBuf, const char *mySalt)
{
    // some code here
    //
    
    /* setup Cipher Ctx */
    const EVP_CIPHER *des_cipher = EVP_CIPHER_fetch(NULL, "DES", NULL);
    EVP_CIPHER_CTX *p_Ctx =  EVP_CIPHER_CTX_new();
    EVP_CIPHER_CTX_init(p_Ctx);
    
    /* encrypt data*/
    int outLen = 0;
    int outLenFinal = 0;
    unsigned char *outBuf = (unsigned char *)calloc(32, 1);
    
    EVP_EncryptInit(p_Ctx, des_cipher, (unsigned char*)myBuf, (unsigned char*)mySalt)
    EVP_EncryptUpdate(p_Ctx, outBuf, &outLen, (unsigned char*)myBuf, strlen(myBuf))
    EVP_EncryptFinal(p_Ctx, outBuf + outLen, &outLenFinal)

    /* finalize encypted data */
    outLenFinal += outLen;
    unsigned char *returnData = OPENSSL_zalloc(outLenFinal);
    OPENSSL_strlcpy(returnData, outBuf, outLenFinal);
    
    /* free pointers */
    EVP_CIPHER_free(des_cipher);
    EVP_CIPHER_CTX_free(p_Ctx);
    free(outBuf);
    return (char*)returnData;
}
```

I used the **buff** as the **key**.
Then I used the **salt** as the **iv**.
Is my use of EVP_EncryptInit, EVP_EncryptUpdate and EVP_EncryptFinal correct?
Do I have to call EVP_EncryptFinal or EVP_EncryptUpdate is enough?
I'm also not sure if "DES" is the proper cipher to be fetched since our old code is just "DES_crypt(..)".

**Comment by t8m** [comment]
DES_crypt() cannot be directly replaced with EVP_Encrypt* functions because it implements the password crypt function.

**Comment by jmbords** [comment]
Does OpenSSL 3 have other APIs that we can use as alternative for DES_crypt?

**Comment by paulidale** [comment]
Would this be a regression?  It seems like it.

**Comment by jmbords** [comment]
I would assume yes. As I understand, I can remove this old code(with DES_crypt) since we will not be using it anymore in our future releases.
I'm just curious if OpenSSL 3 have any APIs to support it.

**Comment by t8m** [comment]
The DES_crypt API is available in 3.0 although deprecated. There is IMO no reason to add it to providers (although it would be probably possible to add it to the legacy provider as a KDF) as the DES_crypt is truly useless. With the current computing power of contemporary CPUs it does not provide sufficient protection for the hashed passwords in addition to the limitation of only up to 8 characters passwords being supported by it.

**Comment by levitte** [comment]
If we should add it back, it should end up in the legacy provider, and most probably as a KDF.

**Comment by mattcaswell** [comment]
I recall that we deliberately decided to not implement a `DES_crypt` replacement - although I can't find a record of that in CHANGES.md. We at least deliberately decided to remove its use from the passwd app without any replacement (see c87a7f31).

**Comment by levitte** [comment]
Side thing:

this sparked me during a pause from work, and well: https://github.com/provider-corner/extra
