### ISSUE TITLE
./config shared no-dso no-hw still fails as of 1.0.1j

### ISSUE THREAD

**Issue by bendiken** [openssl/openssl#189]
The resolution for [#1754](http://rt.openssl.org/Ticket/Display.html?id=1754) states that:

> Thu Jul 03 22:28:04 2014 Rich Salz: Was fixed awhile ago by someone.

However, this does not appear to in fact be the case, as `make install_sw` in release 1.0.1j (October 15, 2014) still fails in the same manner:

    ...
    making install in engines...
    make[2]: Entering directory `/src/openssl/1.0.1j/engines'
    installing 4758cca
    cp: cannot stat ‘lib4758cca.bad’: No such file or directory
    make[2]: *** [install] Error 1
    make[2]: Leaving directory `/src/openssl/1.0.1j/engines'
    make[1]: *** [install_sw] Error 1
    make[1]: Leaving directory `/src/openssl/1.0.1j'
    make: *** [install] Error 2

The aforementioned build was configured with `./config no-hw threads shared zlib-dynamic no-dso no-krb5`.

**Comment by mattcaswell** [comment]
It seems `./config shared no-dso` is sufficient to cause this problem (i.e. `no-hw` is not needed)

**Comment by Adamzynoni** [comment]
it need recoding.

**Comment by drewbug** [comment]
:+1:

**Comment by drewbug** [comment]
https://github.com/openssl/openssl/blob/master/Configure#L1773

Relevant?

**Comment by mattcaswell** [comment]
1.0.1 is only receiving security bug fixes. If this is a problem in 1.0.2 then please raise a separate issue. Closing.
