### ISSUE TITLE
Cross compile CI runs are failing on master after new SIV code

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#18911]
See the failures here:

https://github.com/openssl/openssl/actions/runs/2760678019

Started with commit 0113ec8460 (#18693)

**Comment by mattcaswell** [comment]
Ping @tmshort

**Comment by tmshort** [comment]
I suspect it has to do with big vs little endian.

**Comment by tmshort** [comment]
I'm able to reproduce a couple of the failing platforms (not all, I'm using Ubuntu 22.04 as a base rather than 20.04, so m68k seems to fail to build).

**Comment by tmshort** [comment]
I'm able to reproduce all affected platforms.

**Comment by tmshort** [comment]
I've found some of the big endian issues, but I'm running into trouble with ghash behavior on these platforms. This will take some time.

If we wanted to get those tests passing sooner rather than later, we could:
a) Disable SIV via `no-siv` for those platforms/tests (that would also disable AES-SIV)
b) Revert the commit

**Comment by juergenchrist** [comment]
Still failing on s390x though...
```30-test_evp.t .. 98/? 
        # INFO:  @ test/testutil/stanza.c:21
        # Reading ../../test/recipes/30-test_evp_data/evpciph_aes_gcm_siv.txt
        # INFO:  @ test/testutil/stanza.c:122
        # Starting "RFC8452 AES-GCM-SIV" tests at line 14
        # INFO:  @ test/evp_test.c:604
        # aes-128-gcm-siv is fetched
        # ERROR: (memory) 'expected == got' failed @ test/evp_test.c:107
        # --- expected
        # +++ got
        # 0000:-b5d839330ac7b786
        # 0000:+f16ad41c5c39f42b
        #       ^^^^^^^^^^^^^^^^
        # 
        # INFO:  @ test/evp_test.c:3532
        # ../../test/recipes/30-test_evp_data/evpciph_aes_gcm_siv.txt:16: Source of above error (aligned in-place, not fragmented); unexpected error VALUE_MISMATCH
        # INFO:  @ test/evp_test.c:604
        # aes-128-gcm-siv is fetched
        # ERROR: (memory) 'expected == got' failed @ test/evp_test.c:107
        # --- expected
        # +++ got
        # 0000:-7323ea61d0593226 0047d942
        # 0000:+892ca1ee76b9a693 4a8d4203
        #       ^^^^^^^^^^^^^^^^ ^^^^^^^^
...
```

**Comment by juergenchrist** [comment]
Problem is that s390 GHASH implementation assumes that it is used from inside a gcm128_context structure which you are not doing here.  So the implementation does not find its hash subkey.  This leads to wrong results of PolyVal computations.  Any chance to rework this to use gcm128_context?

**Comment by tmshort** [comment]
Make sure you are using the latest, as the CI *is* working now:
https://github.com/openssl/openssl/runs/7607317219?check_suite_focus=true

Is there a difference between "no-asm" and without on s390x?

Using the `gcm128_context` struct will be painful. I don't have access to a real s390x, so I can't do my own testing. Get me an answer to the above, and I'll see what I can do.

**Comment by juergenchrist** [comment]
I am using the latest.  I use a build without `no-asm` which then includes all the hardware acceleration.  That is a load of assembler code that unfortunately assumes that GHASH is always called out of a `gcm128_context`.

Another problem might be that qemu does not provide all the required functions.  In that case, the code falls back to a pure software implementation.  Not sure how much of CPACF made it to qemu...

**Comment by juergenchrist** [comment]
There is actually a comment in the assembler code hinting at the problem.  See https://github.com/openssl/openssl/blob/4842a27b902660b672d72d2ed23e941461ca481c/crypto/modes/asm/ghash-s390x.pl#L103.

**Comment by tmshort** [comment]
> I am using the latest. I use a build without `no-asm` which then includes all the hardware acceleration. 

But does a "no-asm" build work? I'm not suggesting that as a solution, but it's an important data point.

> There is actually a comment in the assembler code hinting at the problem.

Yes, as does AVX512; which may not have this problem, though.

**Comment by juergenchrist** [comment]
> But does a "no-asm" build work? I'm not suggesting that as a solution, but it's an important data point.

Yes, that works.  That part is understandable since it is the CPACF-based implementation that is having trouble finding its key.


> Yes, as does AVX512; which may not have this problem, though.

A quick look (sorry, not an expert on avx) seems to indicate that AVX has its own initialization where it actually does move the hash subkey and does not require the specific layout required by CPACF.  There, we really require in consecutive memory Xi as 128 bytes followed by the hash subkey as 128 bytes.  Unless I misunderstood the AVX implementation, that strict requirement is not present there.  And, unfortunately, this requirement is not satisfied by the AES-GCM-SIV implementation above.  So far, all I could come up with is create that packed structure on the stack and do a lot of copying.  Not nice, but since the current SIV implementation is anyway block-based, CPACF will not give as bit a benefit as it could.

**Comment by juergenchrist** [comment]
> If you are willing to test a branch from a private repo, I may have something for you soon.

As long as I can access it, I will happily test your branch.  Just have to postpone that until tomorrow.

**Comment by tmshort** [comment]
This is the branch:

https://github.com/tmshort/openssl/tree/fix-s390x-gcm-siv

I have tested it on x86, and the big-endian platforms that failed originally; all (including s390x) passed.
I would make the PR from this branch assuming it works.

**Comment by juergenchrist** [comment]
No, does not work on s390x.  The problem is still the same.  s390x needs a structure
```
uint64_t[2] chainingValue;
uint64_t[2] hashingSubkey;
```
for GHASH.

**Comment by tmshort** [comment]
Those fields are not part of the `gcm128_context`. But I think I know what I did wrong; I think I minimized it *too* much. I can give you an update, soon.

**Comment by mattcaswell** [comment]
> Those fields are not part of the gcm128_context. But I think I know what I did wrong; I think I minimized it too much. I can give you an update, soon.

Isn't this resolved via #18939?

**Comment by tmshort** [comment]
> Isn't this resolved via #18939?

Thanks, for pointing that out. It's new as of today, and I hadn't noticed it yet. (I also just woke up!

**Comment by tmshort** [comment]
@juergenchrist, I did update that branch, if you were willing to try it again without the assembly updates in #18939. It ought to have minimal performance impact (really none, since it's just copying to a different location).

**Comment by juergenchrist** [comment]
No, does not work.  The problem is still the input to `ossl_gcm_ghash_4bit`:
```
/* Implmentation of POLYVAL via existing GHASH implementation */
void ossl_polyval_ghash_hash(PROV_AES_GCM_SIV_HTABLE *args, uint8_t *tag, const uint8_t *inp, size_t len)
{
    uint64_t out[2];
    size_t i;

    byte_reverse16((uint8_t *)out, (uint8_t *)tag);

    /*
     * This implementation doesn't deal with partials, callers do,
     * so, len is a multiple of 16
     */
    for (i = 0; i < len; i += 16) {
        byte_reverse16((uint8_t *)args->Xi, &inp[i]);
        ossl_gcm_ghash_4bit((u64*)out, args->Htable, (uint8_t *)args->Xi, 16); // <- Here, s390x assumes H is behind out.
    }
    byte_reverse16(tag, (uint8_t *)out);
}
```
The problem here is that you are still using `Xi` in a non-traditional way.  If used within a `gcm128_context`, `Xi` contains the input chaining value and also the output chaining value.  So if you transform the above function to:
```
/* Implmentation of POLYVAL via existing GHASH implementation */
void ossl_polyval_ghash_hash(PROV_AES_GCM_SIV_HTABLE *args, uint8_t *tag, const uint8_t *inp, size_t len)
{
    uint64_t out[2];
    size_t i;

    byte_reverse16((uint8_t *)args->Xi, (uint8_t *)tag);

    /*
     * This implementation doesn't deal with partials, callers do,
     * so, len is a multiple of 16
     */
    for (i = 0; i < len; i += 16) {
        byte_reverse16((uint8_t *)out, &inp[i]);
        ossl_gcm_ghash_4bit((u64*)args->Xi, args->Htable, (uint8_t *)out, 16);
    }
    byte_reverse16(tag, (uint8_t *)args->Xi);
}
```
then it works on s390x without my assembler changes.
