### ISSUE TITLE
The s390x EC code is broken in openssl-3.0 branch

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#18912]
I packed the the openssl-3.0 branch as of commit  55461bf22a57a ("Don't try to make configuration leaner") into Debian unstable. Now build properly and the testsuite passed on s390x but then the testsuite for libnet-dns-sec-perl failed with:

```
1..13
ok 1 - use Net::DNS::SEC;
ok 2 - use Net::DNS::SEC::Private;
ok 3 - use Net::DNS::SEC::EdDSA;
ok 4 - set up EdDSA public key
ok 5 - set up EdDSA private key
ok 6 - set up non-EdDSA public key
ok 7 - set up non-EdDSA private key
not ok 8 - signature created using private key

#   Failed test 'signature created using private key'
#   at t/61-Ed25519.t line 99.
ok 9 - signature verified using public key
ok 10 - signature not verifiable if data corrupted
ok 11 - signature not created using wrong private key
ok 12 - verify fails using wrong public key
ok 13 - verify fails if signature undefined
# Looks like you failed 1 test of 13.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/13 subtests 

Test Summary Report
-------------------
t/61-Ed25519.t (Wstat: 256 Tests: 13 Failed: 1)
  Failed test:  8
  Non-zero exit status: 1

```
the same is true for 62-Ed448.t. If someone wants to look at it [here](https://sources.debian.org/src/libnet-dns-sec-perl/1.19-1/t/61-Ed25519.t/) it is.

According to bisect this was introduced by commit
   2af7ec5997730 ("Fix EC ASM flag passing")

Could someone from the s390x team (@juergenchrist ?) maybe look at it.

Sebastian

**Comment by rwfranks** [comment]
Please can you confirm that testsuite for libnet-dns-sec-perl runs successfully on 3.0.5 or earlier formal release.
I assume that you are using Net::DNS::SEC 1.19

**Comment by kroeckx** [comment]
As I understand it, commit 2af7ec5997730d4624d19814be1131ce5dd14304 broke things in the default provider. That commit has been merged after 3.0.5. My understanding is that that commit just had as effect some assembler code is now used in the default provider while it wasn't before. So the commit that broke things didn't actually introduce the broken code, it just enabled it.

1.19 is the current version of Net::DNS::SEC (libnet-dns-sec-perl) in Debian unstable (and testing). It's just the version that was in our CI. The full CI log is available at: https://ci.debian.net/data/autopkgtest/testing/s390x/libn/libnet-dns-sec-perl/24183888/log.gz

**Comment by rwfranks** [comment]
Thanks.
The cited CI log shows the same test failures also occur when using 3.0.3.
This appears to cast considerable doubt on your belief that this bug was introduced post 3.0.5.
```
# 
# These tests were run using:
# 	File::Spec                 3.80
# 	IO::File                   1.46
# 	MIME::Base64               3.16
# 	Net::DNS                   1.34
# 	Net::DNS::SEC              1.19
# 	Net::DNS::SEC::DSA         1853
# 	Net::DNS::SEC::Digest      1849
# 	Net::DNS::SEC::ECDSA       1853
# 	Net::DNS::SEC::EdDSA       1853
# 	Net::DNS::SEC::Keyset      1853
# 	Net::DNS::SEC::Private     1853
# 	Net::DNS::SEC::RSA         1853
# 	Net::DNS::SEC::libcrypto   1853 	OpenSSL 3.0.3 3 May 2022
# 	Test::More                 1.302183
```

**Comment by kroeckx** [comment]
3.0.3 is the version it was build against, not the version it's running against.

**Comment by kroeckx** [comment]
The logs clearly show that 3.0.5 was installed.

**Comment by kroeckx** [comment]
And Debian's 3.0.5-1 included that commit

**Comment by juergenchrist** [comment]
Could you please try to rerun your test suite with the environment variable `OPENSSL_s390xcap` set to `kdsa:0:0` and see if that fixes your issue?  Did you ever test OpenSSL 1.1.1?  The commit you mention just restores the functionality from OpenSSL 1.1.1 in OpenSSL 3.0.  We know that there are issues around EdDSA and different platforms (see, e.g., https://hdevalence.ca/blog/2020-10-04-its-25519am).

**Comment by rwfranks** [comment]
FYI:  Net::DNS::SEC uses the OpenSSL 1.1.1 interface.
Progress to 3.x.x stalled pending resolution of #16270 and preferably also #14133.

**Comment by sebastianas** [comment]
@juergenchrist: it passed with 

>export OPENSSL_s390xcap=kdsa:0:0

One thing I noticed: The expected signature has 64 bytes, the returned signature has 512 bytes. The first 64 bytes are correct, it is just the additional garbage that breaks things.

**Comment by sebastianas** [comment]
got it
