### ISSUE TITLE
Need help to cross compile OpenSSL for gcc-arm-none-eabi

### ISSUE THREAD

**Issue by TimePrinciple** [openssl/openssl#18927]
I'm trying to integrate OpenSSL into a embedded industrial Operating System (XiUOS) on board ok1052-c (cortex-m7). And the OS currently do not support install softwares from it's terminal or shell.
The cross compile tool-chain used for the OS is gcc-arm-none-eabi (gcc version 6.3.1).
The source code of the OS can be cloned throug: https://gitlink.org.cn/xuos/xiuos.git
I do not have any idea yet where to start and how to start, would you please give me some hint on this? I'll be very much appreciated.

**Comment by mattcaswell** [comment]
OpenSSL does have some support for cross-compilation through the cross-compile-prefix option. So you are likely to want a Configure command something like this:

````
perl Configure --cross-compile-prefix=arm-none-eabi- my-target
````

This assumes that the various tool chain tools are all called arm-none-eabi-something, e.g. arm-none-eabi-gcc.

The target ("my-target") needs to be one of the targets Configure already knows about, e.g. one from the list displayed by

````
perl Configure list
````

I am not familiar with XiUOS and it doesn't look like there is a suitable target name available for that OS. You are likely to need to create one yourself. Probably not a task for the faint hearted. The targets are defined in the various "conf" files in the Configurations directory of the source distro. Most likely you will want to start with something similar to what you need and modify it to suit your platform.
