### ISSUE TITLE
Does Openssl socket connect support binding special network cards?

### ISSUE THREAD

**Issue by XYQ202** [openssl/openssl#18936]
Hello, openssl team
    I am now using the new function **cmp** protocol of openssl3.0, but my device has two network cards, the actual physical connection is _eth0 (192.168.32.100)_, the other is the virtual network card _eth0.1 (192.168.32.200)_, I Now I need to send an IR request to the CA server to get a certificate. I want to use eth0.1 to send a request to the CA server. If I don't make any changes, the default openssl cmp will use eth0 to send an IR request to the CA server, So openssl cmp can specify the network card to send data, can you provide some help?
        
Can you provide more details, thanks.

**Comment by beldmit** [comment]
AFAIK it should be done on system level.

**Comment by XYQ202** [comment]
> AFAIK it should be done on system level.

Thank you for your answer, but I don't quite understand what you mean, so the openssl application cannot bind a fixed IP？

Can you provide more details, thanks.

**Comment by mattcaswell** [comment]
@DDvO

**Comment by DDvO** [comment]
Actually this is a question not about CMP itself but on the HTTP client that the `openssl cmp` command uses by default.
You can specify using the `-server` option which server to address by giving a domain name or IP address, and optionally a port.

For instance, adapting the example given in [`openssl-cmp.pod`](https://www.openssl.org/docs/manmaster/man1/openssl-cmp.html) one could use
```
openssl cmp -config apps/openssl.cnf -section insta -server 91.213.161.196:8700
```

>> AFAIK it should be done on system level.
> 
> Thank you for your answer, but I don't quite understand what you mean, so the openssl application cannot bind a fixed IP？

In your case the option (or configuration file entry) `-server 192.168.32.200` should be sufficient, 
assuming that the IP routing on your system correctly direct messages sent to this IP address over your `eth0.1` interface.

**Comment by XYQ202** [comment]
> Actually this is a question not about CMP itself but on the HTTP client that the `openssl cmp` command uses by default. You can specify using the `-server` option which server to address by giving a domain name or IP address, and optionally a port.
> 
> For instance, adapting the example given in [`openssl-cmp.pod`](https://www.openssl.org/docs/manmaster/man1/openssl-cmp.html) one could use
> 
> ```
> openssl cmp -config apps/openssl.cnf -section insta -server 91.213.161.196:8700
> ```
> 
> > > AFAIK it should be done on system level.
> > 
> > 
> > Thank you for your answer, but I don't quite understand what you mean, so the openssl application cannot bind a fixed IP？
> 
> In your case the option (or configuration file entry) `-server 192.168.32.200` should be sufficient, assuming that the IP routing on your system correctly direct messages sent to this IP address over your `eth0.1` interface.

I understand what you mean, but **-server** is specifying the IP address and port of the CA server, not what I want, my question is how to send the IR from **eth0.1** to the CA server, not through **eth0**, because I only have one  physical network card **eth0**, and **eth0.1** is the network card I simulated, both of which can send IR requests to the CA server, but in the case of both, openssl cmp is sent directly from eth0 by default, you can give openssl in cmp Functionally, the code of the source address when sending an IR request to the CA server, I can make appropriate modifications.

Because among so many commands of openssl, only the new **cmp** function needs to interact with the server side, which means that there should be a choice for the host's network card when sending an IR request, which may be a sequence, and the first network card can reach directly With the first one, the first one cannot be reached, and it will be postponed to the second network card. But I don't know the exact location in the source code.

can you provide some help？ Thanks.

**Comment by beldmit** [comment]
> Because among so many commands of openssl, only the new **cmp** function needs to interact with the server side

No. At least `s_client` may also gain of this option. But, AFAIU, it should be a local IP address option, not an interface, to work properly for all platforms.

I'm not a network programmer but I think that address should be set on creating the socket. If necessary, I could try to point to the code creating the socket more directly.

**Comment by DDvO** [comment]
> > Because among so many commands of openssl, only the new **cmp** function needs to interact with the server side
> 
> No. At least `s_client` may also gain of this option. But, AFAIU, it should be a local IP address option, not an interface, to work properly for all platforms.

I agree. There are some more OpenSSL applications that open a socket / TCP connection with some server, 
including the OCSP client and any other uses of the OpenSSL HTTP client, such as CRL or cert fetching.
So the question/issue being discussed here is not about CMP, and I've changed the title of this issue accordingly.

> I'm not a network programmer but I think that address should be set on creating the socket. If necessary, I could try to point to the code creating the socket more directly.

I'm not a network programmer either, but here is at least a stack trace by the CMP app (or any other use of the HTTP client) that goes down to the BIO socker layer when starting to set up the TCIP/IP connection for HTTP:
```
	BIO_new_connect() at bss_conn.c:694 0x7ffff508c459	
	http_new_bio() at http_client.c:888 0x7ffff5512a48	
	OSSL_HTTP_open() at http_client.c:981 0x7ffff55133c7	
	OSSL_HTTP_transfer() at http_client.c:1,234 0x7ffff5514fe9	
	OSSL_CMP_MSG_http_perform() at cmp_http.c:77 0x7ffff514f6c2	
	send_receive_check() at cmp_client.c:168 0x7ffff513cf49	
	initial_certreq() at cmp_client.c:657 0x7ffff5140919	
	OSSL_CMP_exec_certreq() at cmp_client.c:718 0x7ffff5140dd4	
	cmp_main() at cmp.c:2,966 0x555555701989	
	do_cmd() at openssl.c:418 0x5555557336d4	
	main() at openssl.c:298 0x555555732a80	
```

**Comment by XYQ202** [comment]
> 
_If necessary, I could try to point to the code creating the socket more directly._
**>>> Thanks, can you help point it out, I'll look into it myself**

**Comment by beldmit** [comment]
`BIO_new_connect` is defined in crypto/bio/bss_conn.c.

You will have to implement a new function(s) accepting an source IP, and pass it through the chain

**Comment by DDvO** [comment]
Though I'm not a network expert, I still believe that it should be possible - and most likely be much less effort - to fulfuil your need at system level, by adapting the routing tables such that messages to the server's IP address are routed via your special eth0.1 interface.

**Comment by XYQ202** [comment]
> Though I'm not a network expert, I still believe that it should be possible - and most likely be much less effort - to fulfuil your need at system level, by adapting the routing tables such that messages to the server's IP address are routed via your special eth0.1 interface.

I have tried to modify the route, but it still comes out from eth0, it may be necessary to modify the code.

**Comment by bernd-edlinger** [comment]
your network is mis-configured you should change both interfaces to use different ip address in different subnets,
alternatively you could change the subnet mask to 255.255.255.128

**Comment by XYQ202** [comment]
> your network is mis-configured you should change both interfaces to use different ip address in different subnets, alternatively you could change the subnet mask to 255.255.255.128

Does this have anything to do with network configuration?
What I need is when sending an IR request to the CA server, can this request be sent from eth0.1 and not from eth0 by default.
I think this is also a very useful function, that is, you can specify to send requests from different network cards.

**Comment by beldmit** [comment]
Network interface is too low-level abstraction level. The proper abstraction level here seems to be IP address. You should consider the new BIO ctrl option to specify the local IP address, though it still may require significant changes of the current API.

**Comment by DDvO** [comment]
Is this question meanwhile handled sufficiently?

**Comment by paulidale** [comment]
I think so.  Dealing with low level networking issues is not something that OpenSSL wants to do.

**Comment by XYQ202** [comment]
I have bound the network card and wait for the test
