### ISSUE TITLE
evp.h header missing when building openssl 3 for Android?

### ISSUE THREAD

**Issue by rajohns08** [openssl/openssl#18932]
When executing:
```
$ ./Configure android-arm64 -D__ANDROID_API__=29
$ make
```

Shouldn't I have an `evp.h` header in my build directory's `/include/openssl/`? Both the `Configure` and `make` commands complete successfully.

**Comment by mattcaswell** [comment]
Are you building in a different directory to the source tree? Some header files end up in the build directory's `/include/openssl/` if they are generated from a template. Not all header files are generated though (including evp.h), some just exist directly in the source directory's `/include/openssl/`. Those are not copied to the build directory. `make install` should sort it all out though and copy the right files to the right locations.

**Comment by rajohns08** [comment]
@mattcaswell, yes I am building in a different directory to the source tree. I made a sibling directory to `openssl-3.0.5` called `arm64`. So from the `arm64` directory, I'm running:

```
$ ../openssl-3.0.5/Configure android-arm64 -D__ANDROID_API__=29 enable-fips
$ make
```

I also tried `make install` instead of just `make`, but it still didn't copy `evp.h` into `arm64/include/openssl`. It required me to run as `sudo` and copied `evp.h` to `/usr/local/include/openssl/evp.h`

**Comment by rajohns08** [comment]
Oh I'm an idiot. I see the default directory for install is `usr/local`. Once I executed with:

```
$ ../openssl-3.0.5/Configure --prefix=$PWD android-arm64 -D__ANDROID_API__=29 enable-fips
$ make install
```

But now I see:

```
...
cp: /Users/rajohns/Downloads/openssl_building/arm64/include/openssl/asn1.h and ./include/openssl/asn1.h are identical (not copied).
make: *** [install_dev] Error 1
```

I do see that now I have `evp.h` in my headers, but I'm not sure if any other headers got left out because of this failure.

**Comment by rajohns08** [comment]
Ah ok, I just specified the --prefix to be a separate directory than the one I was running `make` inside of.
