### ISSUE TITLE
Building OpenSSL on aarch64 with fips in Ubuntu 20.04

### ISSUE THREAD

**Issue by sheikfaaruk** [openssl/openssl#18944]
In my system default Openssl version 1.1.1d and i have upgrade to openssl version 1.0.1 with fips 

For Upgrading openssl i followed below steps :

Getting openssl source:
```
wget http://www.openssl.org/source/openssl-1.0.1e.tar.gz
```
Getting fips object module source:
```
wget http://www.openssl.org/source/openssl-fips-2.0.5.tar.gz
````
Unpacking fips object module:
```
tar -xzvf openssl-fips-2.0.5.tar.gz
```
Moving into fips source dir:
```
cd openssl-fips-2.0.5
```
Configuring:
```
./config
```
Compiling:
```
sudo make
```
installing:
```
sudo make install
```
Moving back to home dir:
```
cd ~
```
Unpacking openssl source:
```
tar -xzvf openssl-1.0.1e.tar.gz
```
Moving into openssl source dir:
```
cd openssl-1.0.1e
```
Configuring with fips directive:
```
./config fips shared
```
Compiling:
```
sudo make
```
Error : 
```
make[2]: Entering directory '/home/user/openssl/openssl-1.0.1e'
[ -z "libcrypto" ] || gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -DTERMIO -O3 -fomit-frame-p\
        -DFINGERPRINT_PREMAIN_DSO_LOAD -o fips_premain_dso  \
        /usr/local/ssl/fips-2.0/lib/fips_premain.c /usr/local/ssl/fips-2.0/lib/fipscanister.o \
        libcrypto.a -ldl
make[3]: Entering directory '/home/user/openssl/openssl-1.0.1e'
make[4]: Entering directory '/home/user/openssl/openssl-1.0.1e'
FIPS_text_start() returns NULL
make[4]: *** [Makefile.shared:169: link_a.gnu] Error 1
make[4]: Leaving directory '/home/user/openssl/openssl-1.0.1e'
make[3]: *** [Makefile:347: do_linux-shared] Error 2
make[3]: Leaving directory '/home/user/openssl/openssl-1.0.1e'
make[2]: *** [Makefile:301: libcrypto.so.1.0.0] Error 2
make[2]: Leaving directory '/home/user/openssl/openssl-1.0.1e'
make[1]: *** [Makefile:110: shared] Error 2
make[1]: Leaving directory '/home/user/openssl/openssl-1.0.1e/crypto'
make: *** [Makefile:278: build_crypto] Error 1
```

**Comment by sheikfaaruk** [comment]
![openssl_standards](https://user-images.githubusercontent.com/49053429/183821020-9862b3b0-165e-43de-ac3a-41e743e21029.png)
.
Above mentioned standards i required in openssl .So which version should i use to achieve this standards for development in aarch64 Ubuntu 20.04

**Comment by mattcaswell** [comment]
You need OpenSSL 3.0 with the FIPS provider (configure OpenSSL with "enable-fips" during the build). Your application will then need to be written/configured to *use* the FIPS provider. See:

https://www.openssl.org/docs/man3.0/man7/fips_module.html

Note that the OpenSSL 3.0 FIPS provider is still undergoing its FIPS 140-2 validation. We don't yet have the validation certificate issued.
