### ISSUE TITLE
openssl cmp function has some problems

### ISSUE THREAD

**Issue by XYQ202** [openssl/openssl#18959]
Hello Team

      I am using your new function **cmp** and I can confirm that the device can communicate with the CA server.
But when I run the command below:
     `openssl cmp -cmd ir -server http://192.168.32.146:8080/pkix/ -srvcert ManagementCA.cacert.pem  -certout cl_cert.pem -newkey cl_key.pem -subject "/CN=rauser/O=ZJ/C=SE" -verbosity 8 --unprotected_requests`
     Some errors will appear, as follows:
![image001(08-02-14-29-50)](https://user-images.githubusercontent.com/97773232/183243214-474fe9b0-1248-45bf-846b-2d8505065e49.jpg)

![1](https://user-images.githubusercontent.com/97773232/183243441-fd904928-eedd-4b6a-8851-e2fbe5d6322b.png)
Through wireshark capture, you can see the requested packet, but the packet returned by the CA server indicates that there is an error.

Can you help me figure this out, thanks.

**Comment by XYQ202** [comment]
Can you help me to answer, what parameter is missing in the command, it keeps reporting lack of protection

**Comment by XYQ202** [comment]
I have solved

**Comment by mattcaswell** [comment]
> I have solved

Great. Closing.
