### ISSUE TITLE
Is there utility from openssl which can tell if the application running has fips enabled or not 

### ISSUE THREAD

**Issue by ravinjhajharia** [openssl/openssl#18954]
We know we need to activate FIPS either through configuration or programmatically. Do we have any utility to let the user know whether the running application is fips-compliant or not really?

**Comment by mattcaswell** [comment]
I assume you are talking about OpenSSL 3.0 (as opposed to the old FIPS module).

> Do we have any utility to let the user know whether the running application is fips-compliant or not really?

In 3.0 FIPS is not really "on" or "off". It is perfectly possible to write an application that uses the FIPS module for some crypto operations and not for others. There are also multiple ways to configure things such that FIPS will be/will not be used.

For example if you only ever load the FIPS provider and the base provider and never load the default or any other provider (either explicitly or implicitly) then you should only be using FIPS crypto regardless of your property settings. Another example is that you can load both the default and fips provider at the same time - and then at each call site specify a property query string to give "fips=yes" if appropriate.

Another common way to arrange things is to set the default properties for a given library context to "fips=yes". This means that, by default, all crypto within the scope of that library context will be fetched from a provider offering algorithms marked with "fips=yes" (which usually means they come from the OpenSSL fips provider). Even in this case it is possible to override things at each call site by specifying a different property query string.

There is a function `EVP_default_properties_is_fips_enabled()`. See the man page here:

https://www.openssl.org/docs/man3.0/man3/EVP_default_properties_is_fips_enabled.html

This tells you whether "fips=yes" has been set in the default properties for a given library context. That's probably the closest thing we have to doing what you are looking for.

**Comment by ravinjhajharia** [comment]
@mattcaswell: thanks for the info. Yeah, your assumption about the openssl version is correct. Our scenario is to have the application using FIPS by default by configuring fips and base provider along with the default property having "fips=yes". I know this would confirm the application would be fips-compliant, But I was looking for a utility which can explicitly provide information about the application fips-compliant at the run time. Some information like we see negotiated protocol version during the handshake.

**Comment by mattcaswell** [comment]
I'm unclear what you mean by a "utility". If you are looking for an API from within the application itself so that it can determine whether it is running in "FIPS mode" or not, then then only thing we have is the `EVP_default_properties_is_fips_enabled()` call that I described above.

If you are looking for some utility that can detect whether some external or remote process is FIPS compliant, then no. There is nothing like that.

If you are looking for some TLS protocol level indication that tells you this then, again, no - there is nothing like that.

**Comment by ravinjhajharia** [comment]
> I'm unclear what you mean by a "utility". If you are looking for an API from within the application itself so that it can determine whether it is running in "FIPS mode" or not, then the only thing we have is the `EVP_default_properties_is_fips_enabled()` call that I described above.

@mattcaswell, Thanks for the prompt response. I think it just checks whether the "fips=yes" set or not. Assuming this property is enforced, does it ensure the application would be FIPS-compliant? 

I was looking for a utility which can detect the running application FIPS-compliant and flag non-fips compliance if an application doesn't use some fips-compilance operations at run time.

**Comment by mattcaswell** [comment]
> Assuming this property is enforced, does it ensure the application would be FIPS-compliant?

No. It checks whether the specified libctx has the default "fips=yes" property set. By default that means correctly written applications that only use that libctx and don't override the default properties will only use FIPS validated crypto.

There are several scenarios which might mean non FIPS compliant algorithms are used. Ones that spring to mind:

1) There are many deprecated APIs (most significantly the "low-level" APIs such as `RSA_*`, or `DH_*` functions) which do no use the provider based crypto. If an application is using any of those it may not be FIPS compliant. Typically it is best to ensure an application avoids all deprecated APIs to be sure this isn't a problem.

2) It is perfectly possible for an application to use multiple libctxs. There is also the "default" libctx which exists implicitly. If you test one particular libctx for the "fips=yes" default property then there could be other libctxs that don't have this property.

3) Even if all libctxs in use have the default "fips=yes" property set, and no deprecated APIs are used, it is still possible for an application to override the default properties at individual call sites.

Conversely it is also possible to write an application that only uses FIPS compliant algorithms without using the "fips=yes" default property at all (for example if you only load the fips and base providers into the libctx and no other providers).

Much of this is discussed here:
https://www.openssl.org/docs/man3.0/man7/fips_module.html

**Comment by paulidale** [comment]
What you are asking for is impossible to do generally.

How do you programmatically verify that the build and installation steps from the upcoming security policy were followed?  If they were not followed **exactly**, the resulting installation is **not** FIPS compliant.  E.g. it is not compliant to do the installation once and then make copies across multiple machines.  The code works fine if this is done but it's not FIPS compliant.

We are also expecting there to be a number of items which will be enforced via the security policy rather than via code.  How does one go about programmatically detecting that these situations are not happening?
