### ISSUE TITLE
multithread

### ISSUE THREAD

**Issue by rollen1960** [openssl/openssl#1895]
I use OpenSSL 

OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL 1.0.0-fips 29 Mar 2010

in a multithread enviroment. I have two context: one for https request and one for wss connections. It's possible ? Wich functions cannot execute conncurrently ?

Thank you

**Comment by richsalz** [comment]
You cannot use SSL_CTX in multiple threads unless you lock it (with your own lock wrapper).  OpenSSL data structures are not built for concurrent multi-threads use.
