### ISSUE TITLE
SSL_Accept

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#18952]
Hi,

This is a general question related to an issue that I observed recently.
I have a server application that uses openssl to provide TLS based encrypted network communication.
A third party test client is used for testing the server implementation.
The test client also uses openssl, but I assume that it is a pretty old version.

I am facing an issue when trying to communicate with the server application from the test client.
The client just exits without leaving any clue.
I do not have the source at client side so am not able to investigate much.
Using WireShark I could see that Client Hello and Server Hello has happened, but no trace after that.
On debugging the server, all I could identify was that the client exits after SSL_Accept call is make at server side.

Can someone provide any input on this?
What more could I do to get information on what could be going wrong?

Thanks in advance.

Regards,
Amal

**Comment by mattcaswell** [comment]
> all I could identify was that the server exists after SSL_Accept call is make at client side

This sounds wrong. `SSL_accept` is a function for use by servers only. The equivalent client side function is `SSL_connect`.

**Comment by amaljesudas** [comment]
@mattcaswell You are right max. I got the usage of server and client wrong. I have edited my question to reflect the same. I apologize for not reviewing my post. Sorry.

**Comment by mattcaswell** [comment]
Perhaps if you supply the pcap file from your wireshark session we might get some clue.

**Comment by amaljesudas** [comment]
Have limitation in sharing files from work environment. Will check if I can regenerate same in some sample and share the same.

**Comment by amaljesudas** [comment]
@mattcaswell I found the reason why the client was exiting. The client is not supporting mutual authentication. Without mutual authentication it works. Do not know why it had to exit instead of throwing some error. Will try to check with the developers of the client application. For now will close this issue. Thanks.
