### ISSUE TITLE
Plesk panel is down after uninstalling OpenSSL version 3

### ISSUE THREAD

**Issue by mustafa-can** [openssl/openssl#18961]
Related on [this post](https://stackoverflow.com/questions/73258779/simplexml-load-file-ssl-operation-failed-with-code-1-openssl-error-messages) to solve the problem I tried to downgrade openssl 3 to openssl 2. Then in ssh run 'sudo apt remove openssl' command. Result is plesk panel down. After connecting ssh and reinstalling openssl3 again did not solve the problem. The server has installed Ubuntu 22.04 Plesk panel is still down. Can anyone has advice about this problem ?

**Comment by mattcaswell** [comment]
This seems more like a plesk issue than something OpenSSL can advise you on. You would be better off asking in some plesk forum.
