### ISSUE TITLE
Does OpenSSL support SM2 encryption in command line tools?

### ISSUE THREAD

**Issue by softpudding** [openssl/openssl#18964]
Hello. I do know that openssl now provides coding interfaces for SM2 encryption/decryption, but I fail to find these utilities in command line tools. So does OpenSSL support SM2 encryption in command line tools?

**Comment by mattcaswell** [comment]
Yes, you can do this with the `pkeyutl` app.

See the man page here:

https://www.openssl.org/docs/man3.0/man1/openssl-pkeyutl.html

There are some details on the SM2 specific support near the end of the page.

**Comment by softpudding** [comment]
Oh thanks. So 3.0 added this to command line.
