### ISSUE TITLE
OpenSSL standards required aarch64

### ISSUE THREAD

**Issue by sheikfaaruk** [openssl/openssl#18972]
![openssl_standards](https://user-images.githubusercontent.com/49053429/183821268-12a0d69d-ffe8-4ba4-9a7f-f2c33900fa71.png)

Above mentioned standards i required in openssl .So which version should i use to achieve this standards for development in aarch64 Ubuntu 20.04.

**Comment by mattcaswell** [comment]
You need OpenSSL 3.0 with the FIPS provider (configure OpenSSL with "enable-fips" during the build). Your application will then need to be written/configured to use the FIPS provider. See:

https://www.openssl.org/docs/man3.0/man7/fips_module.html

Note that the OpenSSL 3.0 FIPS provider is still undergoing its FIPS 140-2 validation. We don't yet have the validation certificate issued.
