### ISSUE TITLE
Support MODP well-known group 2

### ISSUE THREAD

**Issue by jrisc** [openssl/openssl#18981]
The 1024-bit MODP group 2 is defined in [RFC2409](https://datatracker.ietf.org/doc/html/rfc2409#section-6.2), [RFC2412](https://datatracker.ietf.org/doc/html/rfc2412#appendix-E.2) and [RFC7296](https://datatracker.ietf.org/doc/html/rfc7296#appendix-B.2). It may be considered outdated, but its support is still required by some protocols, like the PKINIT Kerberos extension ([RFC4556](https://datatracker.ietf.org/doc/html/rfc4556#page-13)) for which only groups 2 and 14 are mandatory to support. Group 2 is still used by default in [Heimdal](https://github.com/heimdal/heimdal).

Currently, a PKINIT pre-authentication process between a Heimdal client and a MIT krb5 KDC (relying on OpenSSL for DH key exchange) does not work because OpenSSL will not recognize the group 2, and will fallback to custom group verification, where it fails.

~~The primary failure cause is probably #18980, but fixing this bug alone will not be enough to have group 2 verification working, since there will be no match for the value of `N` in [`default_mdname()`](https://github.com/openssl/openssl/blob/openssl-3.0.1/crypto/ffc/ffc_params_generate.c#L446-L455).~~

**Comment by kaduk** [comment]
To be honest, I would rather update the PKINIT RFC to deprecate use of group 2 and remove the mandatory-to-implement status.

**Comment by kaduk** [comment]
E.g., the IETF CURDLE working group recently published RFC 9142 that deprecated this group from MTI status and left group 14 as "less bad" than it.

**Comment by jrisc** [comment]
Okay, I will initiate a discussion by email with MIT and Heimdal developers to propose to update the RFC.

Such a decision could have some impact, especially on Heimdal side, where this group is still the default one.

**Comment by mspncp** [comment]
I would guess that DH2 can be considered as quite unsecure by now, since it is one of the most attractive targets for a precomputation attack, as described in the [logjam paper](https://weakdh.org/imperfect-forward-secrecy.pdf).

![grafik](https://user-images.githubusercontent.com/11467854/185188291-24b98f56-59d3-4c74-8c51-28c309e784ff.png)

**Comment by kaduk** [comment]
> Okay, I will initiate a discussion by email with MIT and Heimdal developers to propose to update the RFC.

It is arguably more appropriate to have the discussion at the IETF KITTEN working group (https://datatracker.ietf.org/wg/kitten/about/) that maintains the Kerberos protocol.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
