### ISSUE TITLE
Decryption using DES in ECB mode with the EVP interface is failing

### ISSUE THREAD

**Issue by enaess** [openssl/openssl#18986]
Note that the encryption succeeds and EVP_CipherUpdate() at that point encrypts the entire buffer of 80 bytes.  In reverse, the decryption of the same data returns 72 bytes (1 block of 8 bytes less than the input), and call to EVP_CipherFinal() fails.

Running the following test on Ubuntu 22.04 with openssl installed:
ii  openssl        3.0.2-0ubuntu1.6 amd64        Secure Sockets Layer toolkit - cryptographic utility

```
#include <string.h>
#include <openssl/evp.h>

int test_des_decrypt()
{
    EVP_CIPHER_CTX* ctx = NULL;
    int success = 0;

    unsigned char key[8] = { 
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07
    };  

    unsigned char cipher[80] = { 
        0x5d, 0xa7, 0x47, 0xc5, 0x1a, 0xb1, 0x71, 0xff,
        0xc8, 0x45, 0x7c, 0xa7, 0x07, 0xec, 0x4b, 0x13,
        0x47, 0x55, 0x77, 0xbc, 0xcf, 0x71, 0xd9, 0x27,
        0x23, 0x12, 0x2a, 0x17, 0x20, 0xad, 0xc1, 0x19,
        0x3e, 0x74, 0x38, 0x29, 0x48, 0xb0, 0xd2, 0xe2,
        0x18, 0x45, 0xdd, 0x8a, 0x9b, 0x8d, 0x40, 0xec,
        0x9e, 0x0c, 0x41, 0xa3, 0x36, 0x40, 0xf5, 0x91,
        0x41, 0x44, 0xde, 0xa1, 0xb5, 0x9d, 0x39, 0x99,
        0x23, 0x12, 0x2a, 0x17, 0x20, 0xad, 0xc1, 0x19,
        0xee, 0xe3, 0xbe, 0x0b, 0x83, 0x36, 0xe1, 0x25
    };  

    unsigned char expect[80] = { 
        0x4f, 0x6e, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63,
        0x6c, 0x69, 0x65, 0x6e, 0x74, 0x20, 0x73, 0x69,
        0x64, 0x65, 0x2c, 0x20, 0x74, 0x68, 0x69, 0x73,
        0x20, 0x69, 0x73, 0x20, 0x74, 0x68, 0x65, 0x20,
        0x73, 0x65, 0x6e, 0x64, 0x20, 0x6b, 0x65, 0x79,
        0x3b, 0x20, 0x6f, 0x6e, 0x20, 0x74, 0x68, 0x65,
        0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x20,
        0x73, 0x69, 0x64, 0x65, 0x2c, 0x20, 0x69, 0x74,
        0x20, 0x69, 0x73, 0x20, 0x74, 0x68, 0x65, 0x20,
        0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x20
    };  

    unsigned char plain[80] = {}; 
    int outlen = 0;
    int offset = 0;

    ctx = EVP_CIPHER_CTX_new();
    if (ctx) {

        if (EVP_CipherInit(ctx, EVP_des_ecb(), key, NULL, 0)) {

            if (EVP_CipherUpdate(ctx, plain, &outlen, cipher, sizeof(cipher))) {

                offset += outlen;  // outlen seems to always be nblocks - 1 in length, i.e. (80 - 8)  = 72 bytes; since 80/8 = 10, I'd expect the entire buffer be decrypted.

                if (EVP_CipherFinal(ctx, plain+offset, &outlen)) { // at this point the EVP_CipherFinal returns 0, expected 1, and plain to be complete.

                    if (memcmp(plain, expect, 80) == 0) {

                        success = 1;
                    }
                }
            }
        }
        EVP_CIPHER_CTX_free(ctx);
    }   

    return success;
}
```

**Comment by mattcaswell** [comment]
>                 offset += outlen;  // outlen seems to always be nblocks - 1 in length, i.e. (80 - 8)  = 72 bytes; since 80/8 = 10, I'd expect the entire buffer be decrypted.

This is because, by default, standard padding of the data is assumed. OpenSSL is holding back the last block in case it turns out to be one containing padding data that needs to be stripped.

>                 if (EVP_CipherFinal(ctx, plain+offset, &outlen)) { // at this point the EVP_CipherFinal returns 0, expected 1, and plain to be complete.

It fails because the padding in the decrypted data is not as expected.

If your data is not padded then you need to switch padding off by calling the following immediately after your `EVP_CipherInit` call:

````
    EVP_CIPHER_CTX_set_padding(ctx, 0);
````

If you are not using padding then the plaintext must be a multiple of the blocksize.

Making the above change still does not end up in a "success" result. The memcmp fails. Probably there is something incorrect with the encrypted data.

**Comment by enaess** [comment]
You are right, when I update the code to disable padding; the decryption succeeds. Not sure why the example failed, but my version of the code worked (including the memcmp()).
