### ISSUE TITLE
Using EVP_CipherXYZ functions for EVP_des_ecb() fails, call to EVP_CIPHER_CTX_set_cipher_data is ignored.

### ISSUE THREAD

**Issue by enaess** [openssl/openssl#18987]
This is the encryption for MS-CHAP as described per https://www.rfc-editor.org/rfc/rfc2759.txt. Input Challenge, PasswordHash, and NTResponse is copied from the RFC and inserted in the below code. The generation fails in two places:

1. The use of EVP_CIPHER_CTX_set_cipher_data() should call DES_set_key() and it should succeed and finally call DES_set_key_unchecked(). However, that never happens, the output of the 1st cal of EVP_CipherUpdate() is correct; but after the call to EVP_CIPHER_CTX_set_cipher_data(), it seems like the original key passed in to the EVP_CipherInit() is re-used? When I debugged this, I tried to set a breakpoint on DES_set_key() and friends, function never got hit.

2. The call to EVP_CipherFinal() ends up doing another block encryption iteration and writes another 8 bytes to the response parameter thus overstepping the 24 bytes buffer and the application ends up with a corrupt stack.

This is reproducible on Ubuntu 22.04 with the following version of openssl:
openssl        3.0.2-0ubuntu1.6 amd64        Secure Sockets Layer toolkit - cryptographic utility
```
#include <openssl/evp.h>
#include <openssl/des.h>

static unsigned char
Get7Bits(const unsigned char *input, int startBit)
{
    unsigned int word;

    word  = (unsigned)input[startBit / 8] << 8;
    word |= (unsigned)input[startBit / 8 + 1];

    word >>= 15 - (startBit % 8 + 7);

    return word & 0xFE;
}

static unsigned char*
MakeKey(const unsigned char *key, unsigned char *des_key)
{
    /* key     IN  56 bit DES key missing parity bits */
    /* des_key OUT 64 bit DES key with parity bits added */
    des_key[0] = Get7Bits(key,  0);
    des_key[1] = Get7Bits(key,  7);
    des_key[2] = Get7Bits(key, 14);
    des_key[3] = Get7Bits(key, 21);
    des_key[4] = Get7Bits(key, 28);
    des_key[5] = Get7Bits(key, 35);
    des_key[6] = Get7Bits(key, 42);
    des_key[7] = Get7Bits(key, 49);
    
    DES_set_odd_parity((DES_cblock *)des_key);
    return des_key;
}

int test_des_encrypt_with_set_key()
{
    unsigned char Challenge[8] = { 
        0xD0, 0x2E, 0x43, 0x86, 0xBC, 0xE9, 0x12, 0x26
    };  

    unsigned char ZPasswordHash[21] = { 
        0x44, 0xEB, 0xBA, 0x8D, 0x53, 0x12, 0xB8, 0xD6,
        0x11, 0x47, 0x44, 0x11, 0xF5, 0x69, 0x89, 0xAE
    };  

    unsigned char expected[24] = { 
        0x82, 0x30, 0x9E, 0xCD, 0x8D, 0x70, 0x8B, 0x5E, 
        0xA0, 0x8F, 0xAA, 0x39, 0x81, 0xCD, 0x83, 0x54, 
        0x42, 0x33, 0x11, 0x4A, 0x3D, 0x85, 0xD6, 0xDF
    };  
    unsigned char Key[8] = {}; 
    unsigned char response[24] = {}; 
    unsigned int retval = 0;
    int offset = 0;
    int outlen = 0;

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (ctx != NULL) {

        if (EVP_CipherInit(ctx, EVP_des_ecb(), MakeKey(ZPasswordHash + 0, Key), NULL, 1)) {

            if (EVP_CipherUpdate(ctx, response + offset, &outlen, Challenge, sizeof(Challenge))) {
                offset += outlen;

                EVP_CIPHER_CTX_set_cipher_data(ctx, MakeKey(ZPasswordHash + 7, Key));
                if (EVP_CipherUpdate(ctx, response + offset, &outlen, Challenge, sizeof(Challenge))) {
                    offset += outlen;

                    EVP_CIPHER_CTX_set_cipher_data(ctx, MakeKey(ZPasswordHash + 14, Key));
                    if (EVP_CipherUpdate(ctx, response + offset, &outlen, Challenge, sizeof(Challenge))) {
                        offset += outlen;
                        outlen = 0;

                        if (EVP_CipherFinal(ctx, response + offset, &outlen)) {

                            if (memcmp(response, expected, sizeof(expected)) == 0) {
                                retval = 1;
                            }
                        }
                    }
                }
            }
        }

        EVP_CIPHER_CTX_free(ctx);
    }   
    return retval;
}

```

**Comment by mattcaswell** [comment]
> The use of EVP_CIPHER_CTX_set_cipher_data() should call DES_set_key() and it should succeed and finally call DES_set_key_unchecked().

It's unclear why you expect that to happen. `EVP_CIPHER_CTX_set_cipher_data()` is only really useful if you are writing a custom EVP_CIPHER. It allows a custom EVP_CIPHER to store internal state within the `EVP_CIPHER_CTX` for later retirival via `EVP_CIPHER_CTX_get_cipher_data()`. It should never be called directly by application code *using* the EVP_CIPHER.

Since you don't seem to be using a custom EVP_CIPHER in this code this just looks wrong - and in fact likely to make the code crash.

**Comment by enaess** [comment]
I was looking at the code in crypto/evp/e_des.c 
```
static int des_ecb_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out,
                          const unsigned char *in, size_t inl)
{
    BLOCK_CIPHER_ecb_loop()
        DES_ecb_encrypt((DES_cblock *)(in + i), (DES_cblock *)(out + i), 
                        EVP_CIPHER_CTX_get_cipher_data(ctx),
                        EVP_CIPHER_CTX_is_encrypting(ctx));
    return 1;
}
```

And I was hopeful that there was a replacement for the deprecated API function: DES_set_key(). 

I was hoping to replace the DES encrypt function by using the EVP interface. The description is here: https://www.rfc-editor.org/rfc/rfc2759.txt see section 8.5 for ChallengeResponse.

**Comment by mattcaswell** [comment]
> And I was hopeful that EVP_CIPHER_CTX_get_cipher_data() could be used as a replacement for the deprecated API function: DES_set_key().

It should not be used that way. How `des_ecb_cipher` works is internal implementation detail that you must not rely on.

If sounds like you want to update the key part way through the encryption. You should treat this as 3 separate encryption operations, each with EVP_CipherInit/EVP_CipherUpdate/EVP_CipherFinal. Provide the new key at each call to EVP_CipherInit.

**Comment by enaess** [comment]
I think you are right. 

However, deprecating the DES api calls and wanting everyone to use the EVP interface. It would seem natural that one would have a way to update/change the key. 

To resolve this problem, I ended up having to call _reset(), then _init() again with the new Key. To treat each of these iterations with it's own Init/Update/Final is probably the correct way to deal with it.

Thanks for the clarifiaction.

**Comment by enaess** [comment]
I suppose there could be a case for adding another control operation to update the key, but the workaround seems easier.

**Comment by kaduk** [comment]
Just to note explicitly, MS-CHAPv2 uses single DES to encrypt the NTLM hash, and there are cloud services that offer DES-cracking as a service for less than $100.  It does not provide any appreciable amount of security, and arguably the protocol itself ought to be marked historic.

**Comment by enaess** [comment]
I concur, the entire MS-CHAP(v2) algorithms should be tossed at see at a depth nobody could ever recover them. 

Unfortunately, they are very much alive today 20+ years later, and there are use-cases for where these are still very much in use in where protected by e.g. TLS. Think EAP-PEAP-MSCHAPv2, it's a compatibility thing. If administrators actually cared, they'd issue smart-cards and only allow VPN access using EAP-TLS.
