### ISSUE TITLE
Can OpenSSL Provide a Mechanism for Setting Entropy Sources?

### ISSUE THREAD

**Issue by WangLianH** [openssl/openssl#18999]
RAND_DRBG_set_callbacks can only set entropy for drbg created by RAND_DRBG_new, can OpenSSL Provide a Mechanism for setting custmer entropy Sources to default?

**Comment by paulidale** [comment]
This can already be done.  You need to create an EVP_RAND provider that provides entropy and this can be made the basis for all of OpenSSL's entropy requirements either via configuration or by calling `RAND_set_seed_source_type()`.

**Comment by WangLianH** [comment]
thanks！
