### ISSUE TITLE
ecp_nistz256-x86_64.asm(5) : error A2189:invalid combination with segment alignment on Windows x64

### ISSUE THREAD

**Issue by tagua** [openssl/openssl#190]
While building openssl current git revision for x64 using Microsoft Visual Studio 2003 update 3 (18.00.30723 for x64) there are conflict on  [ecp_nistz256-x86_64.pl#L3154](https://github.com/openssl/openssl/blob/c381b63764dfb4d5a812cc51abaef423e73c49e5/crypto/ec/asm/ecp_nistz256-x86_64.pl#L3154) with alignment value at [perlasm/x86_64-xlate.pl#L544](https://github.com/openssl/openssl/blob/902b30df193afc3417a96ba72a81ed390bd50de3/crypto/perlasm/x86_64-xlate.pl#L544)

Code in question generated at tmp32dll\ecp_nistz256-x86_64.asm  as following:
```asm
OPTION	DOTNAME
.text$	SEGMENT ALIGN(256) 'CODE'
PUBLIC	ecp_nistz256_precomputed

ALIGN	4096   ; <-- bug here. 4096 is more then 256 for segment.
...
```

Error text:
```
Building OpenSSL
        ml64 /c /Cp /Cx /Zi /Fotmp32dll\ecp_nistz256-x86_64.obj tmp32dll\ecp_nistz256-x86_64.asm
Microsoft (R) Macro Assembler (x64) Version 12.00.30723.0

Assembling: tmp32dll\ecp_nistz256-x86_64.asm
tmp32dll\ecp_nistz256-x86_64.asm(5) size
tmp32dll\ecp_nistz256-x86_64.asm(5) : error A2189:invalid combination with segment alignment
Stop.
```

**Comment by ben-crowhurst** [comment]
Has a solution be found for this issue?  I'm having the same problem with Visual Studio 2015 Win64.

**Comment by henrita** [comment]
ruskotron's trick, switching to the stable branch, worked for me and seems like a good idea anyway.

**Comment by ben-crowhurst** [comment]
Apologies, we should've confirmed @ruskotron fix worked for our project.  You can find build steps [here](https://github.com/corvusoft/restbed/issues/17).

**Comment by MrHacky** [comment]
this error seems to be back in openssl-1.1.0 (just encountered it with -pre3)

**Comment by mlt** [comment]
@MrHacky :+1:

**Comment by mlt** [comment]
The following did the trick for me
```diff
diff --git a/crypto/ec/asm/ecp_nistz256-x86_64.pl b/crypto/ec/asm/ecp_nistz256-x86_64.pl
index 824d7b5..eca842d 100755
--- a/crypto/ec/asm/ecp_nistz256-x86_64.pl
+++ b/crypto/ec/asm/ecp_nistz256-x86_64.pl
@@ -3064,7 +3064,7 @@ print <<___;
 .text
 .globl	ecp_nistz256_precomputed
 .type	ecp_nistz256_precomputed,\@object
-.align	4096
+.align	256
 ecp_nistz256_precomputed:
 ___
 while (@line=splice(@arr,0,16)) {
```

**Comment by mlt** [comment]
It looks like only ml64 is affected. There is no need for any patching if nasm is on PATH.

**Comment by luolin556** [comment]
With using the command line parameter no-asm
