### ISSUE TITLE
The PKCS7_verify interface does not support the PSS padding algorithm.

### ISSUE THREAD

**Issue by CloudQing1994** [openssl/openssl#19006]
When I use the PKCS7_verify interface to verify RSA-PSS-signed data, it fails. 

I checked the implementation of PKCS7_verify and found that when verifying the certificate chain, it read the signature padding algorithm flag from the certificate signature info and then initialized padding_mode by this flag. 

But for image data signature verification, the context is initialized based on the key type of the public key, and pad_mode is set to PKCS7#1 v1.5 by default. The verification fails.

The data signature verification context init as follow:

    pkctx = EVP_PKEY_CTX_new(pkey, NULL);
    if (pkctx == NULL)
        goto err;
    if (EVP_PKEY_verify_init(pkctx) <= 0)
        goto err;
    if (EVP_PKEY_CTX_set_signature_md(pkctx, EVP_MD_CTX_md(ctx)) <= 0)
        goto err;
    i = EVP_PKEY_verify(pkctx, sigbuf, siglen, m, m_len);

```pkctx``` is initialized by ```pkey```. The padding algorithm flag ```digest_enc_alg``` is not used. If the signaure algorithm is RSA, the pad_mode always initialized as ```RSA_PKCS1_PADDING```.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input
