### ISSUE TITLE
Can OpenSSL add (void)param to parameters that are not used in functions?

### ISSUE THREAD

**Issue by WangLianH** [openssl/openssl#19000]
Can OpenSSL add (void)param to parameters that are not used in functions?

such as:
  ```
  include/internal/refcount.h

  static __inline__ int CRYPTO_UP_REF(int *val, int *ret, void *lock)
  {
      (void)lock;
      *ret = __atomic_fetch_add(val, 1, __ATOMIC_RELAXED) + 1;
      return 1；
  }
  ```

**Comment by mattcaswell** [comment]
Why do you want this?

**Comment by levitte** [comment]
> Why do you want this?

I recall having seen some compilers warn about unused parameters, given certain flags.

**Comment by WangLianH** [comment]
We have requirements on the compilation option, and need to turn on the -Werror compile option.

**Comment by mattcaswell** [comment]
> I recall having seen some compilers warn about unused parameters, given certain flags.

For gcc at least I think you have to switch on `-Wunused-parameter` for this warning. This is switched on automatically if you pass `-Wextra`. OpenSSL builds under CI will often use `-Wall`, `-Wextra` and -`Werror`, but also switch off a few warnings including `-Wno-unused-parameter`.

There are extensive (and deliberate) unused parameters in OpenSSL. It would be a big pain to suppress all those warnings. I don't see that happening any time soon if at all.

**Comment by WangLianH** [comment]
ok, thanks!
