### ISSUE TITLE
Is there any example for openssl 3.0 ecc encryption

### ISSUE THREAD

**Issue by aphage** [openssl/openssl#19018]
Is there any example for openssl 3.0 ecc encryption

**Comment by t8m** [comment]
There is no ECC encryption support in OpenSSL. There is only a signature (ECDSA or EDDSA based on the key type) and key exchange (ECDH, X25519 or X445) support.

**Comment by aphage** [comment]
> There is no ECC encryption support in OpenSSL. There is only a signature (ECDSA or EDDSA based on the key type) and key exchange (ECDH, X25519 or X445) support.

Thank you

Is there a key exchange example?

**Comment by mattcaswell** [comment]
> There is no ECC encryption support in OpenSSL.

That's not entirely true. The Chinese algorithm SM2 is an ECC algorithm that supports encryption:

https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-SM2.html

There's an example using an RSA EVP_PKEY here. The process would be similar for an SM2 key:

https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_encrypt_init.html

> Is there a key exchange example?

There's a demo for X25519 here:

https://github.com/openssl/openssl/blob/master/demos/keyexch/x25519.c
