### ISSUE TITLE
Options `-ssl3`,, `-no_ssl3`, `-no_tls1`, `-no_tls1_1`, `-no_tls1_2`, `-no_tls1_3`,  not recognised

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19014]
_release:_ openssl-3.0.5

_manual reference:_
```
$ man 'OPENSSL(1ossl)'
(...)
       -ssl3, -tls1, -tls1_1, -tls1_2, -tls1_3, -no_ssl3, -no_tls1, -no_tls1_1, -no_tls1_2, -no_tls1_3
           These options require or disable the use of the specified SSL or TLS protocols. (...)
```
Hello. options `-ssl3`,, `-no_ssl3`, `-no_tls1`, `-no_tls1_1`, `-no_tls1_2`, `-no_tls1_3`,  not recognised; illustration:
```
$ openssl ciphers -ssl3
list: Use -help for summary.
```
As opposed, other options are recognised; illustration:
```
$ openssl ciphers -tls1_3 | sed 's/:/\n/g' | head -1
TLS_AES_256_GCM_SHA384
```

**Comment by t8m** [comment]
The no_* options do not apply to the ciphers command but they apply to other commands such as s_client. The -ssl3 option is probably not supported by your build but it is supported if enable-ssl3 is used with the build configuration. So perhaps some clarification in the manual page would be appropriate but the options should not be removed from the manual page.

**Comment by Ricky-Tigg** [comment]
That was much helpful. At the time the report was sent, i was not yet aware of the existence of `openssl help <command>`. Now I am. Consulting `openssl help ciphers` would have been beneficial before reporting. Then, by default,  version 3 of SSL was disabled which, if i interpret correctly, caused the output.
```
$ openssl list -disabled | column
Disabled algorithms:	MDC2	SM4	EC2M	SM2	SSL3
```
