### ISSUE TITLE
use “enable-weak-ssl-ciphers”  for windows 

### ISSUE THREAD

**Issue by nmangerian** [openssl/openssl#19017]
I am doing testing using  s_client and would like to use weak ciphers like triple DES, but this has been removed in newer versions (https://www.openssl.org/blog/blog/2016/08/24/sweet32/) . From research, I am able to figure out that the “enable-weak-ssl-ciphers” config option must be used. While, I was able to find various sources that instruct how to do this on a UNIX machine, how would this be done for a windows installation. Thank you for your help.

**Comment by mattcaswell** [comment]
"enable-weak-ssl-ciphers" is a compile time option - so you must build OpenSSL yourself on Windows (or find a binary distribution that was built with this option).

Assuming you are using OpenSSL 3.0 and have downloaded and unpacked the OpenSSL source, consult the [NOTES-WINDOWS.md](https://github.com/openssl/openssl/blob/openssl-3.0/NOTES-WINDOWS.md) file for notes on the build prerequisites.

Once you have the prerequisites building is much the same as on UNIX. Consult the [INSTALL.md](https://github.com/openssl/openssl/blob/openssl-3.0/INSTALL.md) file for details. In short, from the root of the OpenSSL source tree:

````
$ perl Configure VC-WIN64A enable-weak-ssl-ciphers
$ nmake
$ nmake install
````
You'll need a command line with administrator privileges for the last install step.

**Comment by nmangerian** [comment]
I tried what you suggested but I still am not able to use  triple DES as I have tested and as you can see in the cipher list. 
![image](https://user-images.githubusercontent.com/111443105/186489356-bf4bd4d3-6943-4886-8c0f-29dc08c9cb72.png)

![image](https://user-images.githubusercontent.com/111443105/186489270-1b5650ae-48c2-42da-99a9-e5077a578475.png)

**Comment by mattcaswell** [comment]
The `openssl ciphers` command will normally tell you information about the ciphers in the default cipher list. Even when support for weak ciphers are compiled in - they still do not appear in the default cipher list. To see information about 3DES ciphers you can do it like this:

````
$ openssl ciphers -v 3DES
````

**Comment by nmangerian** [comment]
This is the output of running that command. It appears that something is still not configured correctly for this. 
![image](https://user-images.githubusercontent.com/111443105/186669367-ef6e9842-0d87-4098-8b7c-4e7e533046cf.png)

**Comment by nmangerian** [comment]
I was able to attempt to install with nmake and this is the output below.

 **Is there any possible solutions to solve this or issues that could cause this?** 

![image](https://user-images.githubusercontent.com/111443105/188706549-2164a2ab-7f5e-4523-bb41-4d2a14ac3887.png)

**Comment by mattcaswell** [comment]
> Cannot open include file: `stdlib.h`

This error indicates some fundamental issue in your compiler environment. `stdlib.h` is a standard include file that should come supplied with the compiler.

Did you use the Visual Studio Developer Command prompt to attempt this build? From the file NOTES-WINDOWS.md:

>  4. Use Visual Studio Developer Command Prompt with administrative privileges,
    choosing one of its variants depending on the intended architecture.
    Or run `cmd` and execute `vcvarsall.bat` with one of the options `x86`,
    `x86_amd64`, `x86_arm`, `x86_arm64`, `amd64`, `amd64_x86`, `amd64_arm`,
    or `amd64_arm64`.
    This sets up the environment variables needed for `nmake.exe`, `cl.exe`,
    etc.
    See also
    <https://docs.microsoft.com/cpp/build/building-on-the-command-line>

**Comment by nmangerian** [comment]
Yes,  I used the Visual Studio Developer Command prompt to attempt this build. What I showed in my screenshot is all of the commands that I ran besides navigating to the root of the OpenSSL source tree.

**Comment by nmangerian** [comment]
I was able to get past my previous issue by modifying visual studio and I have now encountered a new error that involves openssl itself. 

no assembler found on %PATH% at crypto\rc4\asm\../../perlasm/x86_64-xlate.pl line 102.
error closing STDOUT: Invalid argument at crypto\rc4\asm\rc4-x86_64.pl line 706.

 **Is there any possible solutions to solve this or issues that could cause this?** 

![image](https://user-images.githubusercontent.com/111443105/191334787-4aeef280-a917-40a8-ac07-8f77a034115b.png)

**Comment by t8m** [comment]
You will need to install NASM. Or configure with no-asm which I would not recommend.

**Comment by mattcaswell** [comment]
From the NOTES.WINDOWS file I previously referred to:

````
2. Install NASM

3. Make sure both Perl and NASM are on your %PATH%
````

**Comment by nmangerian** [comment]
I have installed nasm, I have previously ran into the issue of not having it installed and an error, and that error no longer appears so I know that can't be the issue.  

![image](https://user-images.githubusercontent.com/111443105/191519408-dacc22c7-d524-448d-a4a7-9a7882526ec1.png)
