### ISSUE TITLE
Segfault in SSL_CTX_free on Solaris in Nmap

### ISSUE THREAD

**Issue by kulikjak** [openssl/openssl#19039]
When I compile Nmap with OpenSSL 3 and enable the legacy provider via the global configuration (openssl.cnf), Nmap segfaults during cleanup with the following trace:
```gdb
nmap:core> ::stack
libc.so.1`rw_write_held+0x10(0?)
libc.so.1`rw_rdlock_impl+0xf0(0?, 0?)
libcrypto.so.3`CRYPTO_THREAD_read_lock+4(0?, 0?, 0?, 7fc4fc7af2a40?, 0?, 1?)
libcrypto.so.3`ossl_lib_ctx_get_data+0x20(0?, 1?, 7fc4fc5d19318?, 4b58665f80?, 7fc4fc602ef90?, 7fc4fc5e00448?)
libcrypto.so.3`ossl_provider_deregister_child_cb+0x20(4b5865e0f0?, 4b586643c0?, 7fc4fc5d19248?, 3?, 4b58664378?, 4b58664330?)
libcrypto.so.3`ossl_provider_deinit_child+0x34(4b58664330?, 4b587317a0?, 4b58899f70?, 4b59151ad0?, 4b57fb5e80?, 4b58e146a0?)
libcrypto.so.3`OSSL_LIB_CTX_free+0x58(4b58664330?, 39c800?, 1190?, 1190?, 4b58e76220?, 4b58fd5970?)
legacy.so`legacy_teardown+0xc(4b58661950?, 6b0?, 4b57fb5e80?, 63?, 7fc4fc7027088?, 7fc4fc7038490?)
libcrypto.so.3`ossl_provider_teardown+0x20(4b5865e0f0?, 0?, 0?, 11?, 7fc4fc70385a8?, 0?)
libcrypto.so.3`ossl_provider_free+0xd8(4b5865e0f0?, 39bc00?, 7fc4fc702e040?, 7fc4fc7af2a40?, 0?, 1?)
libcrypto.so.3`evp_cipher_free_int+0x30(4b586987e0?, 7fc4fc5948140?, 668?, 7fc4fc7af2a40?, 0?, 1?)
libssl.so.3`SSL_CTX_free+0x1b8(4b58665a40?, 1?, 7fc4fc5b7f300?, 4b58665f80?, 7fc4fc602ef90?, 4b58665f20?)
nsock_pool_delete+0x4ac(4b57f9aae0?, 5?, 4b57f9ab40?, 5?, 4b57f9aba0?, 4b57f9ab88?)
_ZL7gc_poolP9lua_State+0x2c(0?, 4b57f98f20?, ffffffffffffffff?, 0?, 0?, 4b57f9b048?)
luaD_precall+0x200(4b57f980c8?, 4b5902faa0?, 0?, 7fc4fc7af2a40?, 7fc4fc7502cfc?, 4b57f98f20?)
luaD_callnoyield+0x44(4b57f980c8?, 4b5902faa0?, 0?, 7fc4fc74751ec?, 4b58d271b0?, 7fc4fc79017a8?)
luaD_rawrunprotected+0x48(4b57f980c8?, 7fc4fc7550ee4?, 0?, 4b595f5ea0?, 4b59270390?, 4b595f5ea0?)
luaD_pcall+0x30(4b57f980c8?, 7fc4fc7550ee4?, 4b57f98128?, 10?, 0?, 4b5898b630?)
GCTM+0x10c(4b57f980c8?, 0?, 250?, 1?, 1?, 4b57f98198?)
luaC_freeallobjects+0x64(4b57f980c8?, 4b5902fa90?, 4b57f98200?, 8523?, 7fc4fc7027088?, 4b57f98198?)
close_state+0x14(4b57f980c8?, 0?, 0?, 16?, 4b57f98198?, 0?)
_Z9close_nsev+0x28(0?, 1?, 7fc4fc702e040?, 7fc4fc7af2a40?, 0?, 0?)
_ZN7NmapOpsD1Ev+0x3d0(7fc4fc79017a8?, 2944?, 7fc4fc7af2a40?, 7fc4fc7af2a40?, 7fc4fc7af05c0?, 411?)
libc.so.1`_exithandle+0x7c()
libc.so.1`exit+4(0?, fffffffd59b2bef8?, fffffffd59b2bf30?, 7fc4fc7127c68?, 0?, 0?)
_start+0x6c(0?, 0?, 0?, 0?, 0?, 0?)
```
It seems that the OSSL_LIB_CTX passed to `CRYPTO_THREAD_read_lock` is unexpectedly NULL.

I am unsure whether this is Nmap or OpenSSL 3 related issue, though I would guess it's Nmap (as I didn't see this in other stuff we have compiled with OpenSSL3). Even so, any suggestion or idea of how to investigate this further (or what might be causing this) would be appreciated.

This is on Oracle Solaris 11.4 on both SPARC and Intel. When I remove the `SSL_CTX_free` call, everything seems to work as expected (except for it leaking memory a little bit).

I reported this issue also on the Nmap Github here, but so far, nothing was found: https://github.com/nmap/nmap/issues/2482

**Comment by mattcaswell** [comment]
Which patch version of OpenSSL are you using? nmap/nmaep#2482 mentions 3.0.2. I'd suggest trying again with the latest 3.0.5 to see if that makes a difference. There have been numerous bug fixes applied since 3.0.2 and I'm fairly sure that includes around the area of the code which is crashing. It may be that this problem is already fixed.

If that doesn't solve the issue then is it possible to get a stack trace where OpenSSL has been compiled with debug symbols on?

**Comment by kulikjak** [comment]
Sorry, I forgot to mention that. The stack trace is with the latest OpenSSL 3.0.5 (there is a slight difference compared to 3.0.2, but the problem seems to be the same).

I will recompile the OpenSSL with debug symbols and post the stack trace here.

**Comment by kulikjak** [comment]
Intel stack trace (from gdb) with OpenSSL 3 compiled with `-g -O0`:
```gdb
0x00007fe1b28423e3 in rw_write_held () from /lib/64/libc.so.1
0x00007fe1b284309e in rw_rdlock_impl () from /lib/64/libc.so.1
0x00007fe1b28431dc in rw_rdlock () from /lib/64/libc.so.1
0x00007fe1b15cecd2 in CRYPTO_THREAD_read_lock (lock=0x0) at ../../openssl-3.0.5/crypto/threads_pthread.c:97
0x00007fe1b15b8d7c in ossl_lib_ctx_get_data (ctx=0x7fe1b1877a40 <default_context_int>, index=1, meth=0x7fe1b184edc0 <provider_store_method>) at ../../openssl-3.0.5/crypto/context.c:362
0x00007fe1b15ca568 in get_provider_store (libctx=0x0) at ../../openssl-3.0.5/crypto/provider_core.c:339
0x00007fe1b15cd370 in ossl_provider_deregister_child_cb (handle=0x9554099a0) at ../../openssl-3.0.5/crypto/provider_core.c:1794
0x00007fe1b15c8fa9 in ossl_provider_deinit_child (ctx=0x955409ca0) at ../../openssl-3.0.5/crypto/provider_child.c:279
0x00007fe1b15b8aad in OSSL_LIB_CTX_free (ctx=0x955409ca0) at ../../openssl-3.0.5/crypto/context.c:247
0x00007fe1b0c1409f in legacy_teardown (provctx=0x955406cf0) at ../../openssl-3.0.5/providers/legacyprov.c:168
0x00007fe1b15ccaf1 in ossl_provider_teardown (prov=0x9554099a0) at ../../openssl-3.0.5/crypto/provider_core.c:1546
0x00007fe1b15cb1a2 in ossl_provider_free (prov=0x9554099a0) at ../../openssl-3.0.5/crypto/provider_core.c:696
0x00007fe1b1589ab5 in evp_cipher_free_int (cipher=0x9554254b0) at ../../openssl-3.0.5/crypto/evp/evp_enc.c:1638
0x00007fe1b1589b3c in EVP_CIPHER_free (cipher=0x9554254b0) at ../../openssl-3.0.5/crypto/evp/evp_enc.c:1653
0x00007fe1b1a7da6f in ssl_evp_cipher_free (cipher=0x9554254b0) at ../../openssl-3.0.5/ssl/ssl_lib.c:5953
0x00007fe1b1a78719 in SSL_CTX_free (a=0x954d6a680) at ../../openssl-3.0.5/ssl/ssl_lib.c:3478
0x00007fe1b2f547fb in nsock_pool_delete ()
0x00007fe1b2f35803 in gc_pool(lua_State*) ()
0x00007fe1b2f79666 in luaD_precall ()
0x00007fe1b2f798c1 in luaD_call ()
0x00007fe1b2f79914 in luaD_callnoyield ()
0x00007fe1b2f7b1df in dothecall ()
0x00007fe1b2f7907d in luaD_rawrunprotected ()
0x00007fe1b2f79b39 in luaD_pcall ()
0x00007fe1b2f7b0bd in GCTM ()
0x00007fe1b2f7b14c in callallpendingfinalizers ()
0x00007fe1b2f7bc98 in luaC_freeallobjects ()
0x00007fe1b2f7fe69 in close_state ()
0x00007fe1b2f8022d in lua_close ()
0x00007fe1b2f34615 in close_nse() ()
0x00007fe1b2ed63cc in NmapOps::~NmapOps() ()
0x00007fe1b275c494 in _exithandle () from /lib/64/libc.so.1
0x00007fe1b273c901 in exit () from /lib/64/libc.so.1
0x00007fe1b2ea3dce in _start ()
```
What I also found (but might be normal):
`ossl_lib_ctx_get_data` is called twice inside `OSSL_LIB_CTX_free` - the second one (that ultimately segfaults) with `ctx=NULL` and `ctx = ossl_lib_ctx_get_concrete(ctx);` sets it to that `<default_context_int>`.

This is different from when I run this without legacy provider enabled; there I can see three `ossl_lib_ctx_get_data` calls inside `OSSL_LIB_CTX_free` and all of them have `ctx` set (to the same value).

One thing I didn't mention originally is that this segfault occurs only when the legacy provider is enabled.

**Comment by mattcaswell** [comment]
> What I also found (but might be normal):
ossl_lib_ctx_get_data is called twice inside OSSL_LIB_CTX_free - the second one (that ultimately segfaults) with ctx=NULL and ctx = ossl_lib_ctx_get_concrete(ctx); sets it to that <default_context_int>.

This looks normal to me. The legacy provider uses a child libctx. It is that child libctx that is being freed here. As part of the free it is detaching itself from the parent libctx (i.e. the default or NULL libctx). The `ossl_provider_deregister_child_cb` callback you see in the stack trace is doing that.

> This is different from when I run this without legacy provider enabled

Without the legacy provider there is no child libctx being used so this probably ok.

The fact that the `lock` is NULL in the default libctx is very surprising. I can only really see 2 ways that this could happen (barring memory corruption issues).

1) The default libctx failed to initialise properly. But this seems very unlikely. We've got as far as loading a provider and we're now unloading it. If the default libctx had not successfully initialised we would have failed a long time ago.

2) The default libctx has already been de-initialised. This sounds more plausible - but how it could have occurred I cannot see. A libctx is freed via the `context_deinit` function:

https://github.com/openssl/openssl/blob/25c486762daf8a279676e3e98136855e2e021100/crypto/context.c#L116-L142

As you can see this frees the `lock` object for the libctx and then sets it to NULL. So if it was called prematurely for the default libctx then this might explain why the lock is NULL when we attempt to use it.

`context_deinit` gets called when `OSSL_LIB_CTX_free()` is called (for a non-default libctx). Or when the default libctx eventually gets freed as part of library cleanup (i.e. via `OPENSSL_cleanup()` which itself is only called when the process exits).

Do you see the `context_deinit` function being called anywhere prior to this seg fault? If so can you provide a stack trace for where that occurs? I'm particularly interested in calls to that function for the default libctx (i.e. as stored in the global variable `default_context_int`).

**Comment by kulikjak** [comment]
Seems like it's 2. When setting breakpoints on both `OSSL_LIB_CTX_free` and `context_deinit`, It seems that `default_context_int` is already deinitialized. First:
```gdb
context_deinit (ctx=0x7fd9fe077a40 <default_context_int>) at ../../openssl-3.0.5/crypto/context.c:121
0x00007fd9fddb884f in ossl_lib_ctx_default_deinit () at ../../openssl-3.0.5/crypto/context.c:159
0x00007fd9fddbd240 in OPENSSL_cleanup () at ../../openssl-3.0.5/crypto/init.c:427
0x00007fd9fef5c4a7 in _exithandle () from /lib/64/libc.so.1
0x00007fd9fef3c901 in exit () from /lib/64/libc.so.1
0x00007fd9ff6a3dce in _start ()
```
and then 
```gdb
0x00007fd9ff0423e3 in rw_write_held () from /lib/64/libc.so.1
0x00007fd9ff04309e in rw_rdlock_impl () from /lib/64/libc.so.1
0x00007fd9ff0431dc in rw_rdlock () from /lib/64/libc.so.1
0x00007fd9fddcecd2 in CRYPTO_THREAD_read_lock (lock=0x0) at ../../openssl-3.0.5/crypto/threads_pthread.c:97
0x00007fd9fddb8d7c in ossl_lib_ctx_get_data (ctx=0x7fd9fe077a40 <default_context_int>, index=1, meth=0x7fd9fe04edc0 <provider_store_method>) at ../../openssl-3.0.5/crypto/context.c:362
0x00007fd9fddca568 in get_provider_store (libctx=0x0) at ../../openssl-3.0.5/crypto/provider_core.c:339
0x00007fd9fddcd370 in ossl_provider_deregister_child_cb (handle=0x96f24a770) at ../../openssl-3.0.5/crypto/provider_core.c:1794
0x00007fd9fddc8fa9 in ossl_provider_deinit_child (ctx=0x96f24aa70) at ../../openssl-3.0.5/crypto/provider_child.c:279
0x00007fd9fddb8aad in OSSL_LIB_CTX_free (ctx=0x96f24aa70) at ../../openssl-3.0.5/crypto/context.c:247
0x00007fd9fd41409f in legacy_teardown (provctx=0x96f247bf0) at ../../openssl-3.0.5/providers/legacyprov.c:168
0x00007fd9fddccaf1 in ossl_provider_teardown (prov=0x96f24a770) at ../../openssl-3.0.5/crypto/provider_core.c:1546
0x00007fd9fddcb1a2 in ossl_provider_free (prov=0x96f24a770) at ../../openssl-3.0.5/crypto/provider_core.c:696
0x00007fd9fdd89ab5 in evp_cipher_free_int (cipher=0x96f266280) at ../../openssl-3.0.5/crypto/evp/evp_enc.c:1638
0x00007fd9fdd89b3c in EVP_CIPHER_free (cipher=0x96f266280) at ../../openssl-3.0.5/crypto/evp/evp_enc.c:1653
0x00007fd9fe27da6f in ssl_evp_cipher_free (cipher=0x96f266280) at ../../openssl-3.0.5/ssl/ssl_lib.c:5953
0x00007fd9fe278719 in SSL_CTX_free (a=0x96ebab310) at ../../openssl-3.0.5/ssl/ssl_lib.c:3478
....
0x00007fd9ff6d63cc in NmapOps::~NmapOps() ()
0x00007fd9fef5c494 in _exithandle () from /lib/64/libc.so.1
0x00007fd9fef3c901 in exit () from /lib/64/libc.so.1
0x00007fd9ff6a3dce in _start ()
```

**Comment by mattcaswell** [comment]
Ah!!! There is the problem. I hadn't spotted this before. It looks like `SSL_CTX_free` is being called from an exit handler:

````
0x00007fd9fe278719 in SSL_CTX_free (a=0x96ebab310) at ../../openssl-3.0.5/ssl/ssl_lib.c:3478
....
0x00007fd9ff6d63cc in NmapOps::~NmapOps() ()
0x00007fd9fef5c494 in _exithandle () from /lib/64/libc.so.1
0x00007fd9fef3c901 in exit () from /lib/64/libc.so.1
0x00007fd9ff6a3dce in _start ()
````
So is the OpenSSL `OPENSSL_cleanup()` routine. Unfortunately I don't think it is possible to say what order 2 different exit handlers are called in. In this case they are being called the "wrong" way around. OpenSSL has already been cleaned up, when the nmap exit handler is re-entering OpenSSL......leading to *boom*.

I see 2 potential solutions to this:

1) Nmap arranges its code such that `SSL_CTX_free()` is called earlier (outside of the exit handler).

or

2) Nmap calls `OPENSSL_init_crypto` explicitly using the `OPENSSL_INIT_NO_ATEXIT` option (*must* be the first call to any OpenSSL function). This means that `OPENSSL_cleanup` will not automatically be invoked on process exit. Instead Nmap must call it explicitly (and *after* `SSL_CTX_free` has been called).

**Comment by mattcaswell** [comment]
See `OPENSSL_INIT_NO_ATEXIT` on this page:

https://www.openssl.org/docs/man3.0/man3/OPENSSL_init_crypto.html

**Comment by kulikjak** [comment]
Great, thank you very much for looking into this! That makes a lot of sense.

I tried hacking `OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL)` and explicit `OPENSSL_cleanup()` into the code and can confirm that it now works now as expected.

As for the exit handlers; both Solaris and Linux man page say that they are called in the LIFO order, and so I curiously installed Fedora to test that, and it indeed segfaults as well... But that is an issue for Nmap to solve.

Thanks again.
