### ISSUE TITLE
Regression in 80-test_sslcorrupt.t and 90-test_sslapi.t on m68k and ppc64le after the read record layer refactoring

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#19037]
Please see:
https://github.com/openssl/openssl/runs/7902304314?check_suite_focus=true
and
https://github.com/openssl/openssl/runs/7902305025?check_suite_focus=true

**Comment by t8m** [comment]
@mattcaswell can you please look at this?

**Comment by mattcaswell** [comment]
Fix in #19048

**Comment by t8m** [comment]
I do not see any cross-compile failure on ppc64le and the m68k was fixed (now it fails again but it is unrelated).

So I am closing this.
