### ISSUE TITLE
util/wrap.pl hides information about segfault

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#19041]
When program run via `util/wrap.pl` terminates via SEGFAULT, it doesn't produce any output.

Is it possible to provide such indication?

**Comment by levitte** [comment]
What sort of output do you expect?  Have you looked at the exit code?  It should be 128+signal on all Unix like platforms

**Comment by beldmit** [comment]
Printing "Segmentation fault" to stderr looks reasonable

**Comment by levitte** [comment]
Usually, programs don't usually do that.  If you want your shell to do that, you need to write a `trap` function that does this.
I think this would be unexpected by most...

Since `util/wrap.pl` is sitting in between, I'm doubtful that's the right place to do this, and most of all, to force that output on everyone else.

**Comment by levitte** [comment]
Most of all, this is not a bug.

**Comment by beldmit** [comment]
OK, I can reevaluate it as a feature :)

I was badly surprised that my changes in code don't cause any change in output file - and then by accident I found out that the program was just crashing and not modifying a file at all :)

**Comment by levitte** [comment]
What command did you run, out of curiosity?

**Comment by mattcaswell** [comment]
>  If you want your shell to do that, you need to write a trap function that does this.

My shell prints "Segmentation fault (core dumped)" by default if a process crashes. So I can understand why it is surprising if you don't see this message any more when the process is wrapped by wrap.pl.

Couldn't we just pass the signal up to the parent process and get the default behaviour for your shell?

**Comment by levitte** [comment]
> Couldn't we just pass the signal up to the parent process and get the default behaviour for your shell?

But...  we do?  Or uhm, maybe not.  wrap.pl does what shells do, it constructs an exit code that's 128+signal number.

So it seems that the more proper solution is to re-issue the signal within wrap.pl itself; that should be caught properly by the shell

**Comment by levitte** [comment]
Ok, in that sense, maybe this is a bug after all...

**Comment by mattcaswell** [comment]
Just to demonstrate this, I wrote a script that always segfaults:

````
$ ./test.sh
Segmentation fault (core dumped)
$ echo $?
139
$ util/wrap.pl ./test.sh
$ echo $?
139
````

**Comment by mattcaswell** [comment]
````
$ cat test.sh
#!/bin/bash

kill -11 $$
````

**Comment by beldmit** [comment]
> What command did you run, out of curiosity?

I have a branch :)
It implements a probably new variation of PKCS#12, and I got messed with memory management that caused double-free.
