### ISSUE TITLE
HKDF, PRF, SM2 Pkey standard methods not available from OpenSSL3.0

### ISSUE THREAD

**Issue by Yogaraj-Alamenda** [openssl/openssl#19047]
From QAT Engine we are accessing OpenSSL's default implementation using EVP_PKEY_meth_find() and store it in a function pointer to use OpenSSL implementation from engine incase of hardware failure or when it is a synchronous request. From OpenSSL 3.0 the default implementation methods for HKDF, PRF SM2 are removed hence the corresponding call with EVP_PKEY_meth_find() fails and we are not able to use OpenSSL implementation from Engine. 

Is there any way we can get the OpenSSL default implementation from engine without fetching it from provider ? 

OpenSSSL 3.0 EVP_PKEY_METHOD: https://github.com/openssl/openssl/blob/36c269c3023f5eb626ec79777ed8b285ef939be2/crypto/evp/pmeth_lib.c#L54

OpenSSL 1.1.1 EVP_PKEY_METHOD : https://github.com/openssl/openssl/blob/9eae491721209f302a9a475bffd271370e8bcb8f/crypto/evp/pmeth_lib.c#L25

**Comment by paulidale** [comment]
To support hardware acceleration for these, you will need to write a provider that uses the hardware.  There is no way to use an engine as a provider.

**Comment by Yogaraj-Alamenda** [comment]
There is provider and engine implementation in hardware. Our intention is to get OpenSSL default methods for fallback scenario. OpenSSL 1.1.1 used to have this default methods accessible from engine whereas it is removed from OpenSSL 3.0. 
Hence the ask.

**Comment by paulidale** [comment]
There is no replacement at this point.  You can use properties to pick your provider.

Setting the default property query to `?provider!="default"` will prefer your provider rather than the default.
Better might be `?provider="your provider name"`

**Comment by imoan723** [comment]
Thank you for your reply

**Comment by Yogaraj-Alamenda** [comment]
@paulidale Sorry missed your last reply.  you are saying to use provider rather than engine in OpenSSL3.0.  We need for the engine without fetching it from default provider.

**Comment by t8m** [comment]
Unfortunately there is no way to fetch the internal implementation methods and there will not be with 3.0 and above.

You would have to reimplement them possibly by calling OpenSSL.

**Comment by ShuaiYuan21** [comment]
Hi @t8m May I understand why the community removed SM2, PRF and HKDF from the openssl3.0 engine framework, but keep ECX448/25519 and other PKEY methods? 
If we reimplement the legacy PRF, HKDF and SM2 algorithm APIs in openssl 3.0 (for engine framework), will the community be willing to accept our patch?

**Comment by paulidale** [comment]
I think it doubtful that the project would accept a patch adding features to the engine framework.
We want to get rid of engines and use providers for this kind of thing.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input
