### ISSUE TITLE
how to rpmbuild 1.1.0 on CentOS 7.2

### ISSUE THREAD

**Issue by seawolf1012** [openssl/openssl#1904]
there is no openssl.spec file in the  openssl-1.1.0c.tar.gz

BTW, i got a wrong tips when i rpmbuild openssl 1.0.2J on CentOS 7.2

# rpmbuild -ba openssl.spec
+ perl util/perlpath.pl /usr/bin/perl
Can't locate find.pl in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at util/perlpath.pl line 7.
error: Bad exit status from /var/tmp/rpm-tmp.IUEXE9 (%build)

how to fix it?

**Comment by levitte** [comment]
> perl util/perlpath.pl /usr/bin/perl

That one doesn't work and hasn't for a while.  Among other things, this is the reason we ended up removing openssl.spec.  Package specs is better left with packagers.

So, my advice is to fetch the last openssl source rpm from CentOS, copy their {whatever}.spec and associated files and adapt them to your OpenSSL workspace.
