### ISSUE TITLE
How to increase key length in DHE key exchange method?

### ISSUE THREAD

**Issue by ml16685** [openssl/openssl#19057]
Hello,

We have a  TLS server based on OpenSSL, and when the key exchange with the client
goes via Ephemeral Diffie Hellman (DHE) method, the server always generates a 1024 bit key, 
which is considered weak nowadays.

Below is the screenshot illustrating it:

![OpenSSL_DH_Key_Exchange_1024_bit](https://user-images.githubusercontent.com/60180072/186453446-a1f8b436-6221-4044-ad18-0b9a0770253c.jpg)

Could you please advice if there is a way to configure OpenSSL so it would generate
the ephemeral key of the specific length?

**Comment by t8m** [comment]
What OpenSSL version do you use?

**Comment by ml16685** [comment]
We are using version 1.0.2u.

**Comment by t8m** [comment]
In OpenSSL-1.0.2 the DH parameters have to be set by the application that uses OpenSSL so the 1024 bit parameters you're seeing from your server are set by the server application not by OpenSSL itself.

**Comment by ml16685** [comment]
@t8m Thank you for response. 

I've generated new DH parameters of 2048 bits length via "dhparam" openssl command
and provided them to the server app, and the issue was resolved.  The server now sends
2048 bits public keys to the clients.

But if to use "dhparam" without any other options, the generation of DH parameters 
takes quite a long time. 

Adding an option "-dsaparam" decreases the time significantly, but in this case,
according to documentation, the generated primes are not "strong". May it cause some
security drawbacks? 

One possible drawback is stated in "dhparam" documentation:

"Beware that with such DSA-style DH parameters, a fresh DH key should be created for each use
to avoid small-subgroup attacks that may be possible otherwise."    

Our server app generates new key for each session with the client, so this drawback doesn't seem 
to be applicable to us.

**Comment by t8m** [comment]
I'd recommend using the dhparam without the -dsaparam option, just in case. You just need to run it once so the time to generate these parameters should not be a problem.

**Comment by ml16685** [comment]
Yes, that was our initial intention. But the server (which is actually a Web Server
basing on lighttpd) is a part of the firmware that runs on embedded system.

And the only way to update these devices is to upgrade them to a new version 
of the firmare which has an additional openssl instruction of generating dhparams file
if it doesn't exist yet.

The problem is that CPU on the devices is rather weak, and, as we measured, 
regular "dhparam" generation takes about 25 minutes, which is too long for
the customers to wait, even once. With "-dsaparam" option it takes only about
15-30 seconds.

So "-dsaparam" option is probably the only option for us. But we are not fully
aware of the security risks that come with such speed up.

**Comment by t8m** [comment]
Could you just include a dhparam file in the firmware update? If it is generated with the regular dhparam generation the same dhparam file can be used for all the devices.

**Comment by ml16685** [comment]
That would also be an acceptable approach for us. 

But we have another concern here. 
Is there a limit on the number of devices that are allowed to have the same dhparam file,
if the file is generated with the regular dhparam generation? 
I mean when the number of devices is measured at industrial scale.

**Comment by gstrauss** [comment]
> And the only way to update these devices is to upgrade them to a new version
of the firmare which has an additional openssl instruction of generating dhparams file
if it doesn't exist yet.

FYI: since lighttpd 1.4.56 (released Nov 2020), lighttpd provides a default 2k dhparam of ffdhe2048 if one is not specified in lighttpd.conf.  If you're using lighttpd 1.4.56 or later, I recommend commenting out `ssl.dh-file` from lighttpd.conf and using the provided defaults.

From lighttpd mod_openssl.c:
```
/* https://tools.ietf.org/html/rfc7919#appendix-A.1
 * A.1.  ffdhe2048
 *
 * https://ssl-config.mozilla.org/ffdhe2048.txt
 * C code generated with: openssl dhparam -C -in ffdhe2048.txt
 */
```

**Comment by ml16685** [comment]
@t8m, @gstrauss,
Thank you for the info.
We will use the approach with one common dh file for all devices and will check if we can  upgrade lihttpd.
