### ISSUE TITLE
A potential bug of NPD

### ISSUE THREAD

**Issue by ash1852** [openssl/openssl#19050]
Hi, I found a potential null pointer dereference bug in the project source code of openssl, and I have shown the execution sequence of the program that may generate the bug on the graph below. The red text illustrates the steps that generate the bug, the red arrows represent the call relationships, the file path can be seen in the blue framed section.
![image](https://user-images.githubusercontent.com/87304478/186350353-da45a094-2fee-4910-a8c0-817fb88b5fc8.png)
Although the code shown is for version 1.1.1, this potential bug is still present in the current version
https://github.com/openssl/openssl/blob/bf16ee4f95c31a66e76056c691f25a0d2b4a39c4/apps/speed.c#L3483-L3487

would you can help to check if this bug is true?thank you!

**Comment by paulidale** [comment]
Looks like a bug.  Given where it is I don't believe it has a security impact but it should still be fixed.

**Comment by ash1852** [comment]
thank you for your effort.

**Comment by paulidale** [comment]
Upon further investigation, I don't think this can trigger.  It's parsing a string produced by code in the same file.
It's fragile nonetheless.
