### ISSUE TITLE
Cross compile openssl1.0.0s, add no-tls1, compile error

### ISSUE THREAD

**Issue by XYQ202** [openssl/openssl#19054]
Hello Team，

     I configure openssl1.0.0s by the following command：
     `./Configure linux-armv4 -march=armv7-a --cross-compile-prefix=/usr/petalinux-v2015.4-final/tools/linux-i386/arm-xilinx-linux-gnueabi/bin/arm-xilinx-linux-gnueabi- --prefix=/usr/local/openssl no-tls1 no-ssl`
     Prompt me to run **make depend** after configuration is complete，After I run **make depend**, I run **make** directly to compile，But an error occurred as follows:
    
![image](https://user-images.githubusercontent.com/97773232/186406846-9ed59027-4de6-4a05-9fca-c08c10310122.png)
     I don't have a good solution, because if I change the configuration command to the following:
     `./Configure linux-armv4 -march=armv7-a --cross-compile-prefix=/usr/petalinux-v2015.4-final/tools/linux-i386/arm-xilinx-linux-gnueabi/bin/arm-xilinx-linux-gnueabi- --prefix=/usr/local/openssl no-tls1_1 no-ssl`，Just replace no-tls1 with no-tls1_1, then the compilation succeeds, so that's weird, can you guys help. Thanks. 
     This seems to be a common problem.

**Comment by t8m** [comment]
The openssl-1.0.0 version is unsupported for a long time. Can you reproduce it with 1.1.1 or 3.0 versions?

**Comment by XYQ202** [comment]
> The openssl-1.0.0 version is unsupported for a long time. Can you reproduce it with 1.1.1 or 3.0 versions?

Thank you for your reply, it can be compiled with 1.1.1 or 3.0 versions of openssl, I have tried it, but now I just want to use 1.0.0 to compile the past, because the original device is all 1.0.0 library, no Significant revisions are required.
I'm just very strange, why can't tls1 be removed when compiling openssl 1.0.0, other tls1_1 or tls1_2 can be removed, this is a problem, can you help me solve it?

**Comment by XYQ202** [comment]
> The openssl-1.0.0 version is unsupported for a long time. Can you reproduce it with 1.1.1 or 3.0 versions?

This is mandatory in openssl1.0.0.  Other versions do not appear

**Comment by XYQ202** [comment]
When your openssl is configured, if you remove TLSv1, it will be in openssl1.0.2. no-tls1, an error will be reported when compiling.

I didn't solve how to remove TLSv1.0 version in openssl1.0.0 or 1.0.2

**Comment by paulidale** [comment]
OpenSSL 1.0.0 is **long** out of support.  OpenSSL 1.0.2 is also out of support.  I doubt anyone will answer your questions.
Upgrade to 1.1.1 or later.
