### ISSUE TITLE
Unix error: Error_string[error:12800067:DSO support routines::could not load the shared library]

### ISSUE THREAD

**Issue by jmbords** [openssl/openssl#19067]
Currently on Linux and AIX platforms, I encounter these error logs.
```
MyCryptoFunc() bf_cipher NULL!! : Error_string[error:12800067:DSO support routines::could not load the shared library]
MyCryptoFunc() FAILED EVP_EncryptInit_ex2() : Error_string[error:12800067:DSO support routines::could not load the shared library]
MyCryptoFunc() FAILED EVP_EncryptUpdate() : Error_string[error:078C0105:common libcrypto routines::init fail]
MyCryptoFunc() FAILED EVP_EncryptFinal_ex() : Error_string[error:0308010C:digital envelope routines::unsupported]
```

The code in question that causes this are:
```
/* fetch cipher */
bf_cipher = EVP_CIPHER_fetch(NULL, "BF-ECB", NULL);
if (NULL == bf_cipher) {
    printf("MyCryptoFunc() bf_cipher NULL!! : Error_string[%s]\n", ERR_error_string(ERR_get_error(), NULL));
}

/* encrypt data */
p_Ctx = EVP_CIPHER_CTX_new();
if (0 == p_Ctx) {
    printf("MyCryptoFunc() p_Ctx NULL!! : Error_string[%s]\n", ERR_error_string(ERR_get_error(), NULL));
}
EVP_CIPHER_CTX_init(p_Ctx);

if (0 == EVP_EncryptInit_ex2(p_Ctx, bf_cipher, md_value, md_value, NULL)) {
    printf("MyCryptoFunc() FAILED EVP_EncryptInit_ex2() : Error_string[%s]\n", ERR_error_string(ERR_get_error(), NULL));
}
if (0 == EVP_EncryptUpdate(p_Ctx, ucpOut, &iOutLen, ucpIn, iInLen)) {
    printf("MyCryptoFunc() FAILED EVP_EncryptUpdate() : Error_string[%s]\n", ERR_error_string(ERR_get_error(), NULL));
}
if (0 == EVP_EncryptFinal_ex(p_Ctx, &ucpOut[iOutLen], &iOutLenFinal)) {
    printf("MyCryptoFunc() FAILED EVP_EncryptFinal_ex() : Error_string[%s]\n", ERR_error_string(ERR_get_error(), NULL));
}
```

I'm not entirely sure why the code doesn't find the library. I already added it on the search path whenever I setup the OSSL Providers.

```
void initFunc() {
...
/* setup first */
OSSL_PROVIDER_set_default_search_path (NULL, myCryptoSearchPath);
provider_default = OSSL_PROVIDER_load(NULL, "default");
provider_legacy = OSSL_PROVIDER_load(NULL, "legacy");
provider_base = OSSL_PROVIDER_load(NULL, "base");
...
}
```

Inside the path of _myCryptoSearchPath_ is where the legacy.so file is located. (capi.so, loader_attic.so and padlock.so are also located here)
_myCyptoSearchPath_ looks like: **/scratch/myaccount/myapp/externals\bin\myfolder**

Are there other libraries I need to add in the OSSL Provider default search path? Is there any problem with my init function?

**Comment by paulidale** [comment]
Have you confirmed that the legacy provider has loaded successfully?

**Comment by jmbords** [comment]
Hi Paulidale,

I added some prints and it shows that the provider of legacy is NULL.

```
initFunc() provider_legacy is NULL
```
initFunc() provider_legacy is NULL
```
provider_legacy = OSSL_PROVIDER_load(NULL, "legacy");
printf("initFunc() OSSL_PROVIDER_load(NULL, \"legacy\") finished\n");
if (NULL == provider_legacy) {
    printf("initFunc() provider_legacy is NULL\n");
} else {
    printf("initFunc() provider_legacy is Not NULL\n");
}
```

Do you know if I have to add other libraries(generated from build of OpenSSL) in the search path? I already added legacy.so on the path of myCryptoSearchPath.
```
OSSL_PROVIDER_set_default_search_path (NULL, myCryptoSearchPath);
```

**Comment by xtkoba** [comment]
Try using `strace` command to see what is happening on handling files.

FWIW, the mixture of slash and backslash in the example of `myCyptoSearchPath` does not look normal to me.

**Comment by jmbords** [comment]
Hi, sorry for the delay.

I re-checked my logs during setup of OSSL providers and I found that the **LEGACY** provider is not properly loaded.
```
initFunc() myCryptoSearchPath : /scratch/myaccount/myapp/externals\bin\myfolder
initFunc() OSSL_PROVIDER_set_default_search_path finished
initFunc() OSSL_PROVIDER_load(NULL, "default") finished
initFunc() provider_default is Not NULL
initFunc() OSSL_PROVIDER_load(NULL, "legacy") finished
initFunc() provider_legacy is NULL
initFunc() OSSL_PROVIDER_load(NULL, "base") finished
initFunc() provider_base is Not NULL
initFunc() CRY_OK
```
We can see that provider for legacy: **provider_legacy is NULL**.
Here is the code that sets up the providers.
```
provider_default = OSSL_PROVIDER_load(NULL, "default");
printf("initFunc() OSSL_PROVIDER_load(NULL, \"default\") finished\n");
if (NULL == provider_default) {
    printf("initFunc() provider_default is NULL\n");
} else {
    printf("initFunc() provider_default is Not NULL\n");
}

provider_legacy = OSSL_PROVIDER_load(NULL, "legacy");
printf("initFunc() OSSL_PROVIDER_load(NULL, \"legacy\") finished\n");
if (NULL == provider_legacy) {
    printf("initFunc() provider_legacy is NULL\n");
} else {
    printf("initFunc() provider_legacy is Not NULL\n");
}

provider_base = OSSL_PROVIDER_load(NULL, "base");
printf("initFunc() OSSL_PROVIDER_load(NULL, \"base\") finished\n");
if (NULL == provider_base) {
	printf("initFunc() provider_base is NULL\n");
} else {
	printf("initFunc() provider_base is Not NULL\n");
}

if (RAND_status() != 1) {
    DbgMsg("initFunc() RAND_status() != 1\n");
    RAND_seed(rnd_seed, sizeof rnd_seed);
}
DbgMsg("initFunc() initFunc OK\n");
```


So now I fixed the path for myCryptoSearchPath so it now uses the backslash.

```
MyCryptoFunc() myCryptoSearchPath: /scratch/myaccount/myapp/externals/bin/myfolder
```
Here is the contents of myCryptoSearchPath:
```
bash-4.2$ ls -la /scratch/myaccount/myapp/externals/bin/myfolder
total 105624
drwxr-xr-x 2 qatest g680     4096 Aug 31 19:05 .
drwxr-xr-x 5 qatest g680     4096 Aug 31 19:05 ..
-rwxr-xr-x 1 qatest g680     6828 Aug 25 17:43 afalg.so
-rwxr-xr-x 1 qatest g680     6840 Aug 31 18:21 capi.so
-rwxr-xr-x 1 qatest g680   122692 Aug 31 18:21 legacy.so
-rwxr-xr-x 1 qatest g680    63628 Aug 31 18:21 loader_attic.so
-rwxr-xr-x 1 qatest g680    27336 Aug 31 18:21 padlock.so
```


On the logs, we can see the legacy provider is still NULL.
```
initFunc() myCryptoSearchPath: /scratch/myaccount/myapp/externals/bin/myfolder
initFunc() OSSL_PROVIDER_set_default_search_path finished
initFunc() OSSL_PROVIDER_load(NULL, "default") finished
initFunc() provider_default is Not NULL
initFunc() OSSL_PROVIDER_load(NULL, "legacy") finished
initFunc() provider_legacy is NULL
initFunc() OSSL_PROVIDER_load(NULL, "base") finished
initFunc() provider_base is Not NULL
```
But now I'm also having problems during setup.

After the OSSL_PROVIDER_load calls, we now call **RAND_status** then **RAND_seed**.
The problem is the program crashes after the print of "initFunc() provider_base is NULL". So it's possible that it crashes on RAND_status.

I haven't used strace yet since it immediately crashes at that point. I'll have to do some workarounds for it.

So I'm encountering problems during setup:
1. If I use forward slash(\\) for the OSSL provider path, legacy provider is NULL and the program is **not crashing** at RAND_status code.
2. If I use back slash(/) for the OSSL provider path, legacy provider is NULL and the program is **crashing** at RAND_status code.

**Comment by t8m** [comment]
I'd really recommend getting a backtrace of the segfault with gdb and use strace to see where the legacy provider is searched for.

**Comment by jmbords** [comment]
I double checked some files.
I checked some dependencies of legacy.so and found that it needs libcrypto.so.3
```
bash-4.2$ ldd legacy.so
        linux-gate.so.1 =>  (0xf77b9000)
        **libcrypto.so.3 => not found**
        libdl.so.2 => /lib/libdl.so.2 (0xf776c000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf7751000)
        libc.so.6 => /lib/libc.so.6 (0xf7586000)
        /lib/ld-linux.so.2 (0xf77bb000)
```
Is it enough to add libcrypto.so.3 in the path used in **OSSL_PROVIDER_set_default_search_path**?

**Comment by jmbords** [comment]
It seems to work now with the solution above(adding libcrypto.so.3 in the default_search_path). I'll have to run some further tests to see if this is the finally setup needed.
I'll update this ticket for the results.

**Comment by jmbords** [comment]
After further tests, I confirm that this is the solution.
I'll close this issue now.
Thanks for paulidale, xtkoba and t8m.

**Comment by kollodziej** [comment]
someone is still facing this issue?

**Comment by DeekshantDewari** [comment]
Does anyone know how to make this work in android facing same issue in android while loading oqs provider and legacy
