### ISSUE TITLE
About openssl 3.0 FIPS-140-2

### ISSUE THREAD

**Issue by oyljerry** [openssl/openssl#19069]
Hi All:  
    I saw that openssl 3.0 FIPS 140-2 Validation Certificate Issued from https://www.openssl.org/blog/blog/2022/08/24/FIPS-validation-certificate-issued/, So is that I can use any version 3.0.x (ex. 3.0.4, 3.0.5) which are all pass FIPS 140-2 Validation Certificate? or I must use **3.0.0** for FIPS 140-2? Thanks

**Comment by paulidale** [comment]
You **must** use 3.0.0 to build the FIPS provider and it **must** be built and used **exactly** as per the security policy.  If there is any deviation however slight, the result **will not** FIPS approved.

However, the 3.0.0 FIPS provider will work with any 3.0.x version of the OpenSSL libraries.  You should build these separately (without FIPS) and have them load the 3.0.0 FIPS provider.

**Comment by oyljerry** [comment]
@paulidale Thanks for the reply.

I want to confirm one thing about second paragraph, Below is my understanding

1. I should use openssl 3.0.0 to build FIPS provider (./Configure enable-fips),  get fips.dylib
2. I use openssl 3.0.5 to build crypto/ssl library,  when Configure, I should **NOT** use **enable-fips**? , then get libcrypto.dylib and libssl.dylib
3. use code to load FIPS provider,  ex OSSL_PROVIDER_set_default_search_path/OSSL_LIB_CTX_load_config and more...

In step 2, Can I build 3.0.5 with enable-fips, and use 3.0.0 fips provider file to replace 3.0.5 fips provider?

**Comment by paulidale** [comment]
I suggest that you don't use `enable-fips` when building 3.0.5.  It removes any possibility of using the non-validated provider & it builds and tests faster.  Mistakes happen and mitigating them as part of the process is much better than risking them.  At least in my opinion.

That said, building 3.0.5 with `enable-fips` and copying the 3.0.0 FIPS provider to the right place will work.

A third option is to build 3.0.0 with FIPS, 3.0.5 without and copy the 3.0.0 fips.dylib into the location 3.0.5 expects its providers to be in.  This removes the need to change the default search path etc.

As an aside: you can enable FIPS via configuration if you don't want to make code changes.  But that's another discussion.

**Comment by paulidale** [comment]
Also be careful about loading the default provider with FIPS.  Without correct property strings (or default properties), you risk running in an invalid setup.

It is better to load the base provider along with the FIPS provider.  This guarantees that only FIPS approved algorithms are used.
