### ISSUE TITLE
why we use srtp for video? why not the defualt funtion in openssl?

### ISSUE THREAD

**Issue by fengmao31** [openssl/openssl#19061]
I start to make a rtsp tcp project. I find webrtc project use libsrtp to encrypt data. but some rtsp with ssl use the default function SSL_Write and SSL_Read to encrypt data. openssl default encryption is 3DE CBC. Also, in the websockets hv project also only use openssl default encryption.
I only know default 3DE is weaker than AES in libsrtp.

**Comment by t8m** [comment]
> openssl default encryption is 3DE CBC

What is the OpenSSL version you use? Also where do you see this default? OpenSSL does not use 3DES by default.

**Comment by fengmao31** [comment]
sorry, I make the mistake. I get the answer from the Q&A website. Now, I find the TLS process will auto choose the cipher from ciper list. The result from the wireshark show it use TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.

I test this and lisrtp. The cipher is 50-100us in encryption and socket sent process, 50-500us in decryption and socket recive process. It is hard to cut down two process to test because it looks like some data in Bio is too long and it need more than one packages to send. The lisrtp need 80us to encryption and 100us to decryption. maybe the variance in time  because the repeat list check and HMAC function. 

By the way, I think the two functio is useless because TLS make sure no Man-in-the-Middle Attack.

![image](https://user-images.githubusercontent.com/19343842/187107522-5ee3cdaa-4c46-4697-bccd-8982e87cb310.png)

**Comment by fengmao31** [comment]
I test the speed again. The client encryption speed is 19-79us. The server decryption speed is 20-48us .The client decryption speed is 19-76us.  Most data is between 20-30us.

**Comment by fengmao31** [comment]
> It is not clear to me what you are asking us with this issue.
I need make the encryption function for a remote video system. and I find some project like webrtc use lisrtp, some use openssl function. I want to know which it better for me.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input
