### ISSUE TITLE
TLS Server-Certificate and Client-PSK

### ISSUE THREAD

**Issue by mdeihly** [openssl/openssl#19063]
If I have server with certificate and client with PSK, then it seems weird that the client can connect to server.
On Server side I loaded **Certificate** and **Private Key**. However on Client side I wrote this: **SSL_set_psk_client_callback(ssl, tls13_psk_out_of_bound_cb)** and it connects to Server .

**Comment by mattcaswell** [comment]
In TLSv1.2 if the client doesn't want to perform a certificate based handshake then it should be configured to not offer any non-PSK ciphersuites.

In TLSv1.3 I don't think there is an equivalent mechanism - so I don't think you can indicate at the protocol level that you only want to do a PSK based handshake. Although I suppose the client could force a failure if it doesn't trust any certificate that the server might offer.

Either way, falling back to a certificate based handshake is considered normal behaviour if configuration allows it and is not something we are likely to change.

**Comment by t8m** [comment]
I think we could accept a patch to add an option to enforce the client to fail if the PSK handshake fails.

**Comment by mdeihly** [comment]
> I think we could accept a patch to add an option to enforce the client to fail if the PSK handshake fails.

Thanks for your response.
In my application I need that when a server presents a certificate and client offers PSK, then the server should not accept the connection and eventually the handshake fails.
I am using TLS 1.3.
When I use PSK on client side, I do not call the verification function to **verify server certificate** since I do not expect that this handshake succeeds. However, it succeeds since client certificate is OPTIONAL and when server does not offer PSK, on the client side the function related to PSK is ignored.

**Comment by mdeihly** [comment]
> In TLSv1.2 if the client doesn't want to perform a certificate based handshake then it should be configured to not offer any non-PSK ciphersuites.
> 
> In TLSv1.3 I don't think there is an equivalent mechanism - so I don't think you can indicate at the protocol level that you only want to do a PSK based handshake. Although I suppose the client could force a failure if it doesn't trust any certificate that the server might offer.
> 
> Either way, falling back to a certificate based handshake is considered normal behaviour if configuration allows it and is not something we are likely to change.

Thanks for your repsonse.
Eventually in TLS 1.3 if server has certificate and on client side we have SSL_set_psk_client_callback(ssl, tls13_psk_out_of_bound_cb); --> the function is ignored? I expect to lead to handshake failure since on server side there is no PSK key shared.
