### ISSUE TITLE
PKCS12 man pages says that the default macalg is SHA1 but it's SHA256

### ISSUE THREAD

**Issue by sharhalakis** [openssl/openssl#19078]
This:
https://github.com/openssl/openssl/blob/5639ee79bdc905c1b7ed308fcd29e515e4f01a50/doc/man1/openssl-pkcs12.pod.in#L343-L345

does not agree with this:

https://github.com/openssl/openssl/blob/5639ee79bdc905c1b7ed308fcd29e515e4f01a50/crypto/pkcs12/p12_mutl.c#L207-L209

The man page should be changed to say SHA256.

**Comment by beldmit** [comment]
Would you mind to submit a PR?

**Comment by t8m** [comment]
Fix was merged.
