### ISSUE TITLE
'openssl-speed' | Apparent AEAD cipher reported as not being one

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19073]
_release:_ openssl-3.0.5

_reference:_ (outputs truncated)
```
$ man openssl-speed
 -aead
  Benchmark EVP-named AEAD cipher in TLS-like sequence
```
Hello. Above description gives place for interpretation. While investigating i finally found a reference to it.
```
$ openssl list -verbose -cipher-algorithms -select chacha20 | grep 'aead:'
      aead: integer (max 4 bytes large)
```
Thanks to the minimalistic context I could reasonably assume that nothing but *support** of AEAD is indicated, for instance in regard to MAC. Nevertheless the following output is in contradiction.
```
$ openssl speed -aead -evp chacha20
ChaCha20 is not an AEAD cipher
```

**Comment by mattcaswell** [comment]
The ChaCha20 man page should tell us what the various parameters mean:

https://www.openssl.org/docs/manmaster/man7/EVP_CIPHER-CHACHA.html

From there we discover that the only parameters it supports are the standard cipher parameters which we learn are documented here:

https://www.openssl.org/docs/manmaster/man3/EVP_EncryptInit.html#PARAMETERS

The aead parameter has this description:

> "aead" (OSSL_CIPHER_PARAM_AEAD) <integer>
> Gets 1 if this is an AEAD cipher algorithm, otherwise it gets 0. Use (EVP_CIPHER_get_flags(cipher) & EVP_CIPH_FLAG_AEAD_CIPHER) to retrieve the cached value.

So, this parameter is a flag indicating whether the cipher supports AEAD or not. The presence of the parameter does not imply AEAD is supported. You have to query the parameter to discover whether it is.

In fact ChaCha20 is not an AEAD cipher (although ChaCha20-Poly1305 is).

**Comment by Ricky-Tigg** [comment]
I should have been prepared to the probability that the project may rely, for reason, on such a methodology, which in my opinion is rather pleasant, as it brings an unusual aspect, that is the effect of surprise of either getting _0_ or _1_. Upon the decision took in 19053, i can suppose that developers themselves would likely opt for a pragmatic methodology it they could, like a such one that provides the knowledge of algorithm names having AEAD supported, as a list, thus as part of the `speed` command usage.

**Comment by Ricky-Tigg** [comment]
I should have been prepared to the probability that the project may rely, for reason, on such a methodology, which in my opinion is rather pleasant, as it brings an unusual aspect, that is the effect of surprise of either getting _0_ or _1_. Upon the decision took in 19053, i can suppose that developers themselves would likely opt for a pragmatic methodology if they could, like a such one that provides the knowledge of algorithm names having AEAD supported, as a list, thus as part of the `speed` command usage.
