### ISSUE TITLE
ed25519 key bits - 253 or 256?

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#19070]
So this is follow-up of one PKIX-SSH report - [ed25519 key length 253 instead of 256](https://gitlab.com/secsh/pkixssh/-/issues/12).

- Introduction:
PKIX-SSH unlike OpenSSH uses EVP functions. Also is stores key material into EVP PKEY if key type is supported by cryptographic library. 
Since version PKIX-SSH 13.0 PKCS#8 format for Ed25519 keys is preferred if is supported by cryptographic library, i.e. OpenSSL 1.1.1+.
For PKEY "key length" is obtained from function EVP_PKEY_bits(). So if builds is with OpenSSL 1.1.1+ for ed25519 identity bits are obtained from cryptographic library otherwise is returned 256 as in case of build-in support.

- Retalted 
Stack Exchange is a question -  [Why does OpenSSL show 253 bits?](https://crypto.stackexchange.com/questions/62024/why-does-openssl-show-253-bits) .

- OpenSSL 3+
If I remember well there is no OpenSSL utility that shows ed25519 key bits. It seems to me only TLS session shows bits. Let cheh with PKIX-SSH utility:
```sh
$ chmod 600 [openssl-3-build-tree]/test/certs/client-ed25519-key.pem
$ ./ssh-keygen -lv -f [openssl-3-build-tree]/test/certs/client-ed25519-key.pem
256 SHA256:B93KX0OMv7ZGFBcQF3zJdGUsykTiUQgqr/GN9T6MI/M no comment (ED25519)
+[ED25519 256]----+
|        ..o+oo**O|
|       . o.+.o+==|
|    . . . ooo.o+.|
|     o   o .oo.  |
|    . . S +  .+  |
|     + + o . ..o |
|    . o .o. ..o  |
|      o o.o  ... |
|       +E... ..  |
+[SHA256]---------+
$ nm ./ssh-keygen | grep -i openssl.*init
                 U OPENSSL_init_crypto@@OPENSSL_3.0.0
```

So with OpenSSL 3.0 bits are 256. Looks like regression.

**Comment by t8m** [comment]
Could you please clarify what is the regression? I.E., what is the difference between 1.1.1 and 3.0? I am unable to understand it from your report.

**Comment by petrovr** [comment]
Tomáš Mráz wrote:
> Could you please clarify what is the regression? I.E., what is the difference between 1.1.1 and 3.0? I am unable to understand it from your report.
> 

3+ return 256.

1.1.1 return 253 , see stack-exchange as well.

**Comment by t8m** [comment]
What returns these values? EVP_PKEY_bits()?

**Comment by petrovr** [comment]
Please read first post

Tomáš Mráz wrote:
> What returns these values? EVP_PKEY_bits()?
> 

quote:"
- Introduction:
PKIX-SSH unlike OpenSSH uses EVP functions. Also is stores key material into EVP PKEY if key type is supported by cryptographic library.
Since version PKIX-SSH 13.0 PKCS#8 format for Ed25519 keys is preferred if is supported by cryptographic library, i.e. OpenSSL 1.1.1+.

For PKEY "key length" is obtained from function EVP_PKEY_bits(). <====== this

So if builds is with OpenSSL 1.1.1+ <===== and this (includes OpenSSL 3+ build)

for ed25519 identity bits are obtained from cryptographic library <===== and this

otherwise is returned 256 as in case of build-in support.
"

Roumen

**Comment by t8m** [comment]
The Ed25519 private keys are different from the X25519 private keys in the sense that they do not hardcode the 2 MSBs of the private key, so they are really 256 bit keys. This was actually slightly incorrect in 1.1.1.

**Comment by petrovr** [comment]
Tomáš Mráz wrote:
> The Ed25519 private keys are different from the X25519 private keys in the sense that they do not hardcode the 2 MSBs of the private key, so they are really 256 bit keys. This was actually slightly incorrect in 1.1.1.
> 
> 

Interesting ecx_bits is the same in 1.1.1 and 3+! This means if a key is not provider based result will be 253 in 3+, right?
Remark: I guess that "low" level function ecx_bits in used in 1.1.1.

Roumen

**Comment by t8m** [comment]
> Interesting ecx_bits is the same in 1.1.1 and 3+! This means if a key is not provider based result will be 253 in 3+, right?

Yes, apparently. Not sure if we should fix it in 3.0. I would not change this in 1.1.1 surely.

**Comment by petrovr** [comment]
speed utility also shows 253 :
./util/opensslwrap.sh speed rsa2048 ecdsap256 ed25519 
```sh
...
                  sign    verify    sign/s verify/s
rsa 2048 bits ... ...    ...  ...
                              sign    verify    sign/s verify/s
 256 bits ecdsa (nistp256)   ... ...    ...  ...
                              sign    verify    sign/s verify/s
 253 bits EdDSA (Ed25519)   ... ...    ...  ...
```
Look like new to 3+ define ED25519_BITS is not widely used.

**Comment by salaalg178** [comment]
](url)
