### ISSUE TITLE
How use AES256CTR in newer version?

### ISSUE THREAD

**Issue by SC-One** [openssl/openssl#19083]
Version:  **openssl 1.1.1q**

1- I'm trying to encrypt and decrypt my  **const char***  data , but i got wrong result! it's not valid! I dont know why , I used a lot of ways that openssl prepared , but I thought best and correct way is like this:

``` cpp-lang
std::string  encryptCSR(const std::string& in   // in is a plaintext
                                      , const std::string& iv // iv is 16 byte random unsigned 
                                      , int outSize = 4096) {
                auto out = new unsigned char[outSize];
                int outlen1, outlen2;
                EVP_EncryptInit(ctx,
                                EVP_aes_256_ctr(),
                                reinterpret_cast<const unsigned char *>(ENC_CSR_HARD_KEY),
                                reinterpret_cast<const unsigned char *>(iv.c_str()));
                EVP_EncryptUpdate(ctx,
                                  reinterpret_cast<unsigned char*>(out) ,
                                  &outlen1,
                                  reinterpret_cast<const unsigned char*>(in.c_str()),
                                  in.size());
                EVP_EncryptFinal(ctx,
                                 reinterpret_cast<unsigned char*>(out)+outlen1,
                                 &outlen2);
                out[outlen1+outlen2] = '\0';
                LOGE("Item(%i): %s",outlen1+outlen2,out);
                auto const result = std::basic_string<unsigned char>(out); // I know it's waste casting because of last line , just was test.
                // cleanup
                delete[] out;
                EVP_CIPHER_CTX_free(ctx);
                return std::string ((const char*)result.data());
            }
```

2- another question is that is removed **AES_ctr256_encrypt** function from openssl? or moved other headers?! how

**Comment by t8m** [comment]
The first highly suspicious things in your code seem to be using C strings as binary data.

**Comment by SC-One** [comment]
> 

I'm wrapping to transparent c code and using C++ style outer scopes. it has not problem , and I found that it was correct , caller was using wrong way.
but how about second question? @t8m

**Comment by paulidale** [comment]
That function has been deprecated in 3.0.  The EVP APIs are the _proper_ way to access cryptographic functions (and as a bonus they use accelerated code paths).  Have a look at the [demo code for ARIA-CBC](https://github.com/openssl/openssl/blob/master/demos/cipher/ariacbc.c) to see how to drive the APIs for a basic cipher.

**Comment by SC-One** [comment]
> That function has been deprecated in 3.0. The EVP APIs are the _proper_ way to access cryptographic functions (and as a bonus they use accelerated code paths). Have a look at the [demo code for ARIA-CBC](https://github.com/openssl/openssl/blob/master/demos/cipher/ariacbc.c) to see how to drive the APIs for a basic cipher.

Your right , I just needed to be sure , and cause of that I solved my problem with EVP , not deprecated , thanks for answers.
