### ISSUE TITLE
Non-relevant printing of 'Invalid password argument, missing ':' within the first 5 chars'

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19089]
_release:_ openssl-3.0.5

_reference:_ (outputs truncated)
```
$ man openssl-passphrase-options
  pass:password
   The actual password is password.
```
Hello. Illustration of a non-relevant printing, while set pass-phrase is meeting related requirements.
```
$ cat pass-0
pass:linux
$ openssl genpkey -algorithm ED25519 -pass pass-0 -ChaCha20
Invalid password argument, missing ':' within the first 5 chars
```

**Comment by t8m** [comment]
This is simply misunderstanding. `pass:` is meant to be part of the command line option argument.

I.e.:
` $ openssl genpkey -algorithm ED25519 -pass pass:linux -ChaCha20` would work.

Or:
```
$ cat passfile
linux
$ openssl genpkey -algorithm ED25519 -pass file:passfile -ChaCha20
```
would work too.

**Comment by levitte** [comment]
We should probably add a few examples to clarify.  Sure, there's one example in the openssl-genpkey(1) manual, but...

**Comment by levitte** [comment]
> (outputs truncated)
> 
> ```
> $ openssl help genpkey
>  -pass val           Output file pass phrase source
> ```
> 
> That _file_ in above description leads most probably as having to be interpreted as self-explicit, which, as it is here revealed, must not. As we can observe it there is no such **file** involved in the operation when a pass-phrase is specified as part of the `-pass` argument.

Would it be helpful to rethink those help lines?  Something like this, perhaps?

```
 -pass val           Pass phrase source for the output file
```

**Comment by Ricky-Tigg** [comment]
It sounds to me, that the description of the exact usage would be reached with a such sentence.
