### ISSUE TITLE
EVP_PKEY_get_raw_private_key is returning error in case if public key is passed, but priv is NULL

### ISSUE THREAD

**Issue by ya-isakov** [openssl/openssl#19097]
Hello! I've found that behavior of EVP_PKEY_get_raw_private_key was changed in commit c19d89785075393d27287c90086fa2aeaa842e62. I'm using OpenSSL from commit fc5888ccb60f33b366972299f30b976c4dc12162.

The issue is that in OpenSSL before 3.0, I could pass EVP_PKEY, which has only public key, and use priv = NULL to get length of buffer. Now, in 3.0, EVP_PKEY_get_raw_private_key returns 0 in this case, as it cannot find private key in get_raw_key_details. Is it expected change in behavior?

**Comment by t8m** [comment]
I would qualify this is as undocumented corner-case that works only by accident on 1.1.1. I would not depend on it in application code.

**Comment by mattcaswell** [comment]
> I would qualify this is as undocumented corner-case that works only by accident on 1.1.1. I would not depend on it in application code.

Does it work if you provide an EVP_PKEY that *does* have a private key, but the parameter `priv` == NULL? If that fails then that definitely would be a bug.

**Comment by t8m** [comment]
> Does it work if you provide an EVP_PKEY that _does_ have a private key, but the parameter `priv` == NULL? If that fails then that definitely would be a bug.

I do not think that fails.

**Comment by ya-isakov** [comment]
@t8m according to doc, it's how it should work even in 3.0
```
EVP_PKEY_get_raw_private_key() fills the buffer provided by priv with raw private key data. The size of the priv buffer should be in *len on entry to the function, and on exit *len is updated with the number of bytes actually written. If the buffer priv is NULL then *len is populated with the number of bytes required to hold the key.
```
@mattcaswell unfortunately, I do not know how to fix XCA code, to put private key in EVP_PKEY - and I'm not sure that this is what they allow, anyway - as it won't work for signing with hardware tokens. From looking at the code, it fails in keymgmt code, because get_raw_key_details cannot get private key part - so, if it can find this part, it should work.

**Comment by mattcaswell** [comment]
> If the buffer priv is NULL then *len is populated with the number of bytes required to hold the key.

But in the case of an EVP_PKEY with no private key component then the number of bytes required in the buffer is 0. The documentation doesn't really say what the function will do in this case. Returning 0, returning what the private key length would be if it existed, or returning an error all seem like reasonable ways for the function to behave.

**Comment by ya-isakov** [comment]
@mattcaswell maybe it should be documented, then, to not being UB? I've got my answer, though - as it's UB, it definitely can be changed any time, and as @t8m said, apps should not depends on it. Closing this ticket.
