### ISSUE TITLE
Bug with PKCS12_newpass

### ISSUE THREAD

**Issue by GillesT78** [openssl/openssl#19092]
Hello

I try to use PKCS12_newpass in my code, and as I have an error, I replicate the same error with a small program based of the sample of OpenSSL

```` C
#include <stdio.h>
#include <stdlib.h>
// #include <openssl/pem.h>
#include <openssl/err.h>
#include <openssl/pkcs12.h>

#include <applink.c>

#pragma comment(lib, "ws2_32.lib")

int main(int argc, char **argv)
{
	FILE *fp;
	PKCS12 *p12;

	if (argc != 5) {
		fprintf(stderr, "Usage: pkread p12file password newpass opfile\n");
		return 1;
	}
	if ((fp = fopen(argv[1], "rb")) == NULL) {
		fprintf(stderr, "Error opening file %s\n", argv[1]);
		return 1;
	}
	p12 = d2i_PKCS12_fp(fp, NULL);
	fclose(fp);
	if (p12 == NULL) {
		fprintf(stderr, "Error reading PKCS#12 file\n");
		//ERR_print_errors_fp(stderr);
		return 1;
	}
	if (PKCS12_newpass(p12, argv[2], argv[3]) == 0) {
		fprintf(stderr, "Error changing password\n");
		//ERR_print_errors_fp(stderr);
		PKCS12_free(p12);
		return 1;
	}
	if ((fp = fopen(argv[4], "wb")) == NULL) {
		fprintf(stderr, "Error opening file %s\n", argv[4]);
		PKCS12_free(p12);
		return 1;
	}
	i2d_PKCS12_fp(fp, p12);
	PKCS12_free(p12);
	fclose(fp);
	return 0;
}
````

I always have an error with PKCS12_newpass, even if I have no error with PKCS12_parse (in my code).
Can you confirm that this function has no error ?
I am using OpenSSL 3.0.4 on Windows

Regards
Gilles

**Comment by GillesT78** [comment]
Hello

I thought that there was more reactivity on this project
Nobody has problem with this function ?

Regards
Gilles

**Comment by GillesT78** [comment]
Hello
Your response is very curious. I just take the sample in manpage of openssl 3.0 (https://www.openssl.org/docs/man3.0/man3/PKCS12_newpass.html) (and also 3.1)
So it isn't an old API, but a supported API.
I just use the sample in manpage, not more.
Otherwise, how can we change password of .p12 file in C ?

Regards
Gilles

**Comment by GillesT78** [comment]
Hello

I tested again the fix, and the modification of password is not possible.
Do you have another fix ?

Regards
Gilles

**Comment by selvanair** [comment]
If the file contains only one private key and corresponding certificate chain, you can extract them using `PKCS12_parse()` and then recreate with `PKCS12_create()` passing the new password. 
With OpenSSL 3.0 it would be necessary to load the legacy provider if the input file is encrypted by outdated algorithms.
