### ISSUE TITLE
Manual page mentions with no manual entries

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19099]
_release:_ openssl-3.0.5 (installed via Fedora's repository)

_reference:_ (output truncated)
```
$ man 7 crypto
EVP_EncryptInit(3), EVP_DigestInit(3), BIO_write(3), BIO_read(3), OSSL_LIB_CTX(3), OSSL_PROVIDER_load(3), EVP_DigestInit_ex(3), EVP_MD_fetch(3), (...)
```
Hello. Those mentions of manual pages are unknown. And yet this is a partial list. Illustration:
```
$ man 3 EVP_EncryptInit
No manual entry for EVP_EncryptInit in section 3
```

**Comment by levitte** [comment]
I get that man-page in my Debian installation, through their package, and I can tell you for sure that the man-page source file is there:

https://github.com/openssl/openssl/blob/openssl-3.0/doc/man3/EVP_EncryptInit.pod

I think you'd do better turning to Fedora, this may be an error in their packaging.

**Comment by t8m** [comment]
Do you have the openssl-devel package installed?

**Comment by Ricky-Tigg** [comment]
It wasn't installed. Now it is. man-pages are at last accessible. Thanks.
