### ISSUE TITLE
Engine, provider and EVP_PKEY_fromdata_init

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#19102]
This snippet of code 

https://github.com/isc-projects/bind9/blob/main/lib/dns/opensslrsa_link.c#L1723-L1755

fails when pkcs11 engine (implementing EVP_PKEY_METH) is loaded

with diagnostics
```
error:03000096:digital envelope routines::operation not supported for this keytype:crypto/evp/pmeth_gn.c:354:
```

If I read correctly, it happens because this snippet of code

https://github.com/openssl/openssl/blob/master/crypto/evp/pmeth_lib.c#L235-L247

creates a legacy key, and EVP_PKEY_fromdata_init fails because of lack of keymgmt.

Is there a short-term solution to use PKCS11 engine and providers simultaneously?

I believe the author of the code can provide the details, will tag him later.

**Comment by levitte** [comment]
To disable legacy code (which opensslrsa_link.c does) based on the OpenSSL version, but still work with legacy code (which everything ENGINE is) is a bit naïve.

Legacy EVP_PKEYs don't play well with OSSL_PARAM based functionality.  Don't mix the two, is my advice.

**Comment by beldmit** [comment]
@levitte probably we can add some flag to workaround legacy code path here - but I'm not sure what happens on the next step...

**Comment by pemensik** [comment]
The ultimate attempt in the failing function were to check whether or not is SHA1 algorithm disabled by a policy. I think there is some open issue for such case already.

How can we use PKCS11 engine or functionality with current OpenSSL 3.0.0, when production quality PKCS11 provider does not exist yet? The core of functionality it needs to do is in function [opensslrsa_verify2](https://gitlab.isc.org/isc-projects/bind9/-/blob/main/lib/dns/opensslrsa_link.c#L180). The algorithm_check could be modified, but it is not clear *how* to me.

**Comment by t8m** [comment]
You could encode the testing key with i2d_PUBKEY and load it with d2i_PUBKEY instead of using the EVP_PKEY_fromdata(). These functions should work with legacy keys.

**Comment by petrovr** [comment]
Duplicate, see https://github.com/openssl/openssl/issues/17092 .

**Comment by t8m** [comment]
It is not duplicate of #17092 - this issue is about fromdata functions not working when engine implementing an algorithm for the used keytype is loaded.

**Comment by pemensik** [comment]
Oh, BIND used those calls some before for EdDSA key support, removed by [commit](https://gitlab.isc.org/isc-projects/bind9/-/commit/112ffbaaa21b550810fcb9db776ac7e8061f5d19). That seems quite inconvenient and hackish. Are you sure this should be a prefered way also for RSA keys stored in engine?

Could just i2d_PUBKEY + d2i_PUBKEY 'convert' a PKEY created by EVP_PKEY_fromdata to a legacy compatible EVP_PKEY instance?

**Comment by t8m** [comment]
> Could just i2d_PUBKEY + d2i_PUBKEY 'convert' a PKEY created by EVP_PKEY_fromdata to a legacy compatible EVP_PKEY instance?

Yes, that should work. Not that it is much elegant.

**Comment by pemensik** [comment]
I have made it working by defining OPENSSL_API_COMPAT=10100 and adjusting the code to depend on OPENSSL_API_LEVEL instead of just OPENSSL_VERSION_NUMBER. That is not elegant solution, but this way it works with latest OpenSSL 3.0 the same way as with OpenSSL 1.1. Because BIND9 still supports that version, it does not require adding any new code.

Of course once provider has a working prototype which can be used by bind9, it should avoid legacy functions.

**Comment by pemensik** [comment]
More details in [MR 6711](https://gitlab.isc.org/isc-projects/bind9/-/merge_requests/6711)

**Comment by pemensik** [comment]
@oerdnj might be interested in this issue.

**Comment by nhorman** [comment]
@beldmit is this still something you are working on?

**Comment by beldmit** [comment]
I think this can be closed
