### ISSUE TITLE
Vulnerabilities page in website is empty

### ISSUE THREAD

**Issue by mor-cybellum** [openssl/openssl#19111]
Hi
I'm wasn't sure where to open this kind of issue but the vulnerabilities page in the official website doesn't seem to work:
https://www.openssl.org/news/vulnerabilities.html

It worked a few days ago and it seems to be blank now

**Comment by levitte** [comment]
Thanks for the heads up.  It seems our web production procedure got wonky at some point and left behind more empty files than we noticed a few days ago.  I'll have it restart production as soon as I've cleared an odd error

**Comment by levitte** [comment]
Problem resolved.
