### ISSUE TITLE
3.0 engine to provider - documentation conflict

### ISSUE THREAD

**Issue by alaakryeem** [openssl/openssl#19112]
I've an engine which uses ENGINE_load_private_key(). As I see, this API got deprecated in 3.0 (according to [ENGINE_load_private_key.html ](https://www.openssl.org/docs/man3.0/man3/ENGINE_load_private_key.html)), and in the migration_guide page, the following is written:
> Engine-backed keys can be loaded via custom OSSL_STORE implementation. In this case the EVP_PKEY objects created via [ENGINE_load_private_key(3)](https://www.openssl.org/docs/man3.0/man3/ENGINE_load_private_key.html) will be concidered legacy and will continue to work.

If I'm understanding it correctly, the ENGINE_load_private_key() should be replaced by custom OSSL_STORE implementation. While looking at OSSL_STORE* APIs documentation ([here](https://www.openssl.org/docs/man3.0/man3/OSSL_STORE_LOADER_CTX.html)), most of the APIs there are also deprecated.
How can a deprecated API be replaced with a deprecated API? Please let me know if I'm missing something, and if so, what should replace ENGINE_load_private_key() in 3.0 version and specifically when writing a provider?

**Comment by mattcaswell** [comment]
Not all of the OSSL_STORE APIs are deprecated. A new OSSL_STORE provider API was implemented in 3.0. Provider authors should look at the following man page for details:

https://www.openssl.org/docs/man3.0/man7/provider-storemgmt.html

You can look at a provider that implements a store in our test code here:

https://github.com/openssl/openssl/blob/master/test/fake_rsaprov.c

And some test code that uses that provider via a store is here:

https://github.com/openssl/openssl/blob/fc2be2d07acc0cfe954320c2491b8c5461cbef09/test/provider_pkey_test.c#L179-L228

**Comment by alaakryeem** [comment]
Thanks Matt, I'll look at it

**Comment by nhorman** [comment]
marking as inactiive, will be closed at the end of 3.4 dev barring further input
