### ISSUE TITLE
Doesn't the presence of usable elliptic curves therefore imply the implementation of EC-parameters?

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19120]
_release:_ openssl-3.0.5
_reference:_ (outputs truncated)
```
$ man openssl-genpkey
 -algorithm alg
  Valid built-in algorithm names for private key generation are RSA, RSA-PSS, EC, X25519, X448, ED25519 and ED448.

$ man openssl-ecparam
 -list_curves
  Print out a list of all currently implemented EC parameters
```
Hello. As attested by the manual openssl-genpkey, supports of algorithms X25519, X448, ED25519 and ED448, which have their foundation on elliptic curves, have been introduced to OpenSSL. The output of `openssl ecparam -list_curves` for reason i suppose, makes no mention of those algorithms' names, This leads me to consider either they have
- no implemented EC parameters
- or no EC parameter to implement

How then developers succeeded to implement those algorithms into the OpenSSL library. May it be a pertinent question.

**Comment by t8m** [comment]
These X25519, X448, ED25519 and ED448 key types although their foundation is elliptic curves, have completely separate implementation that does not share the API of the EC key type elliptic curve algorithms. They can be used only through the high level API and are not counted as elliptic curves for the EC key types which are the curves reported by the `openssl ecparam -list-curves` command.
