### ISSUE TITLE
Need a way to select provider during TLS connections

### ISSUE THREAD

**Issue by ashwanikadian** [openssl/openssl#19128]
We are loading "default" and "legacy" provider during our application initialization and then we are creating SSL_CTX for our TLS connections using the OSSL_LIB_CTX in which we have loaded "default" and "legacy" provider.

But we have implemented our own MCS provider to deal with Microsoft cert store for asymmetric key operations during the SSL handshake. So we are loading our MCS provider in the same OSSL_LIB_CTX, after SSL_CTX is already created. We are then creating EVP_PKEY (to be used in SSL handhsake) using that OSSL_LIB_CTX, by explicitly setting "provider=mcs" property, so that EVP_PKEY operations use the MCS provider. We then set that EVP_PKEY into SSL_CTX using SSL_CTX_use_PrivateKey() and then proceed for SSL handshake using that SSL_CTX.

But during the SSL handshake, OpenSSL somehow uses the "default" provider for some operations and is not redirecting the asymmetric key operations during SSL handshake to the MCS provider and hence it fails with "no private key" error.

But if I change the logic a little and load the MCS provider first in the OSSL_LIB_CTX, then load the "default" and "legacy" providers and then create the SSL_CTX using that OSSL_LIB_CTX, then SSL handshake redirects the asymmetric key operations to the MCS provider and handshake goes through fine. The EVP_PKEY is created in the same way in this approach as well, as mentioned above.

So, can someone please guide on the way we can force SSL_CTX/SSL objects to redirect all the asymmetric key operations to the MCS provider, if we load the MCS provider into OSSL_LIB_CTX, after SSL_CTX is created, as mentioned above in first approach. Please suggest if we can set some property/flag in SSL_CTX/SSL objects to use MCS provider for future asymmetric key operations?

**Comment by paulidale** [comment]
`SSL_CTX_new_ex()`?

**Comment by ashwanikadian** [comment]
@paulidale  Hi Pauli, We are using SSL_CTX_new_ex(), but the usecase is that we load the MCS provider into OSSL_LIB_CTX after SLS_CTX is created using SSL_CTX_new_ex(). So we need a way to select the provider during SSL handhshake in this usecase.

**Comment by paulidale** [comment]
You want to use `SSL_set_SSL_CTX()` to switch the context being used by the SSL.  Probably in the client hello call back.

**Comment by ashwanikadian** [comment]
But if we create a new SSL_CTX after loading MCS provider and then set that into SSL object (SSL_set_SSL_CTX()), then we would loose all the flags, trust store and other stuff set into the older SSL_CTX. We will have to replicate all that stuff to the new SSL_CTX somehow, to not impact any existing usecase?

**Comment by paulidale** [comment]
Yes, they will need to be replicated.

**Comment by ashwanikadian** [comment]
That will be very expensive for our usecases. 

If I load both the providers (MCS and default) initially itself (before creating SSL_CTX), then is there any way I can change the provider to be used for SSL handshake's asymmetric key operations at runtime? I mean, can I select MCS provider for SSL handshake for certain conditions in our code and "default" provider for some other conditions, once SSL_CTX is already created.

**Comment by paulidale** [comment]
I don't think so, but @mattcaswell might know a way.

**Comment by paulidale** [comment]
@mattcaswell is on vacation today and tomorrow.  I'm sure he'll respond afterwards if nobody else on the team has a solution.

**Comment by t8m** [comment]
What about using EVP_set_default_properties() to set the "provider=mcs", or, if it does not support all the operations needed then use "?provider=mcs" as the default property. That should make the mcs provider preferred for all the operations that it supports.

**Comment by ashwanikadian** [comment]
I tried setting "?provider=mcs" as the default property after loading both default and MCS provider in my libctx. But the SSL connection with the SSL_CTX, using that libctx is still throwing "rsa routines::missing private key" and says "decrypt error",

It looks like that the asymmetric decrypt operation during SSL handshake was still not redirected to the MCS provider, but was handled by the default provider only. Is there any other property that I can set in SSL_CTX or libctx to make this provider preference work for all asymmetric key operations during SSL handshake?

**Comment by paulidale** [comment]
Does setting the property query on the SSL_CTX when it is created help?

**Comment by ashwanikadian** [comment]
@paulidale Yes, If I set the property before creating SSL_CTX, then it affects the preference.

@t8m Another observation was that, incase I load the MCS provider first and then loaded the default provider in the libctx and then create SSL_CTX, then setting "?provider=mcs"  property works fine to use MCS provider during SSL handshake. But if I load default provider first and then MCS provider in libctx and then create SSL_CTX. Setting "?provider=mcs"  property does not seem to make MCS as preffered provider for asymmetric key operations using that SSL_CTX.

**Comment by paulidale** [comment]
TLS preloads algorithms, so you will need the property query set before this happens.  I'm not sure of the exact timing of this.  Setting it on SSL_CTX creation is the safest option I think.

**Comment by t8m** [comment]
This looks fairly weird. What version of openssl do you use? Is that the 3.0.5 version or something earlier? The query "?provider=mcs" should always prefer the MCS provider regardless of the order of loading of the providers.

**Comment by ashwanikadian** [comment]
I am using OpenSSL 3.0.2

**Comment by t8m** [comment]
Please try OpenSSL 3.0.5. There were some fixes related to optional property queries in versions after 3.0.2.

**Comment by ashwanikadian** [comment]
Unfortunately, I am seeing the same behavior with OpenSSL 3.0.5 as well.

**Comment by t8m** [comment]
This is really weird and unless you have some error in the mcs provider implementation, it should work as you expect. The `?provider=mcs` should prefer the mcs provider for all operations except for operations with keys that cannot be exported to the mcs provider. Unfortunately to fix the issue, we would need some kind of reproducer.

What is the exact operation that fails and could you find by running the application in a debugger how is the operation fetched?

**Comment by youyang-hub** [comment]
Also, if we use FIPS provider instead of default provider, would it be any differences? Can we achieve the case that asymmetric operation in TLS goes to MCS provider(routed to Microsoft FIPS validated CNG when MCS store is used), and other symmetric operations goes to OpenSSL FIPS module?

**Comment by t8m** [comment]
In fact, if everything is correctly implemented and your private keys are not exportable from the MCS provider (i.e., the mcs provider does not provide keymgmt export function for them, or the export function fails) you should not even need the `?provider=mcs` query. It should be sufficient to load the key with the `provider=mcs` and use the EVP_PKEY reference with the SSL_CTX. Then to use the fips provider for everything else than the operations on the private key in mcs you should use `?fips=yes` query string and load only the fips, base, and mcs providers into the libctx.

**Comment by ashwanikadian** [comment]
I am using following code to create the EVP_PKEY, which is set into SSL_CTX for TLS connections. The "libctx" has the MCS provider already loaded.
EVP_set_default_properties(libctx, "?provider=mcs")
X509 *cert_obj = X509_new_ex(libctx, "provider=mcs")
EVP_PKEY *keyobj = X509_get_pubkey(cert_obj) 

So if I don't call EVP_set_default_properties(libctx, "?provider=mcs") before this EVP_PKEY creation, then the TLS connection is not using the MCS provider ans is still going through default provider, even though I had passed "provider=mcs" property while EVP_PKEY creation. So it looks like that setting preferred provider at the OSSL_LIB_CTX level (or probably at SSL_CTX/SSL level) is necessary for TLS to use the new MCS provider. Creating EVP_PKEY with "provider=mcs" does not seem to be sufficient?

**Comment by ashwanikadian** [comment]
I see that https://www.openssl.org/docs/man3.0/man3/EVP_set_default_properties.html mentions:

EVP_set_default_properties() and EVP_default_properties_enable_fips() are not thread safe. They are intended to be called only during the initialisation phase of a libctx.

So is there any way that we can set the "?provider=mcs" property on per SSL_CTX or SSL object, instead of doing it on per OSSL_LIB_CTX basis? For multithreaded applications which share the OSSL_LIB_CTX and can have different SSL_CTX/SSL objects, we want to set different preferred providers. Please let us know if we can do this setting on SSL_CTX or SSL objects?

**Comment by mattcaswell** [comment]
`SSL_CTX_new_ex` takes a property query parameter which will be used for all fetches by the `SSL_CTX` and any associated `SSL` objects.

**Comment by ashwanikadian** [comment]
Is there any SSL_CTX/SSL API which can change the preferred provider for them after they have been created using SSL_CTX_new_ex()?

**Comment by mattcaswell** [comment]
No. Lots of fetches are cached and so long lived. If you want to change things you are best to create a new SSL_CTX.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input

**Comment by jsrikanth1608** [comment]
@ashwanikadian, I have a similar requirement to switch between providers in an SSL connection. Will this issue be addressed in 3.4 release? Will the functionality work regardless of the order in which providers loaded? Please let us know.

**Comment by nhorman** [comment]
@ashwanikadian to answer your direct question: no, its not likely to be addressed in 3.4 as we are very close to reaching our capacity planning.

that said, it seem like the direction above has already been provided, that you should use a new SSL_CTX to switch providers in your code.  Is there something else missing?

**Comment by jsrikanth1608** [comment]
@nhorman, Thank you for the information. I also want to understand whether loading a new provider will flush existing cache entries or they remain intact? Could you please suggest any references to learn more about this topic?

**Comment by nhorman** [comment]
yes, it should flush the cache, you should be able to see that take place in ossl_provider_add_to_store.

Typically, we don't document such minutae in our reference documents, but we do have an ongoing effort to start documenting our code with doxygen, which should slowly make the code an improved source of research for questions like these

**Comment by jsrikanth1608** [comment]
@nhorman, Thank you.
