### ISSUE TITLE
When SSL_set_verify(), what processing logic is the default callback for the underlying ctx?

### ISSUE THREAD

**Issue by fengmao31** [openssl/openssl#19123]
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_verify.html
SSL_set_verify() sets the verification flags for ssl to be mode and specifies the verify_callback function to be used. If no callback function shall be specified, the NULL pointer can be used for verify_callback. In this case last verify_callback set specifically for this ssl remains. If no special callback was set before, the default callback for the underlying ctx is used, that was valid at the time ssl was created with [SSL_new(3)](https://www.openssl.org/docs/man1.1.1/man3/SSL_new.html). Within the callback function, SSL_get_ex_data_X509_STORE_CTX_idx can be called to get the data index of the current SSL object that is doing the verification.

The openssl docs say it use  the default callback function to do with the SSL_set_verify()  process. I want to know the source code or  its processing logic. 

And I find it will refuse the same certificate from client in Peer verify and NULL verify_callback model. Which error is the situation in  the error list. I want catch the error and pass it to allow it keep to check other error if I use my callbacck function.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input
