### ISSUE TITLE
Improve the generic list data structure

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#19129]
There are lots of options here.  Some could include:

* Checking that on insertion of a node, the node isn't already in a list (i.e. next and prev are NULL and pray it's not in a singleton list)
* Validating that a node is in a list when it is removed
* Locking list operations for multiprocessor operation, this could include:
  * a list lock
  * node locks
  * lock free implementation
* Adding a _list_ field to the node structure so that:
  * list membership can be validated on remove quickly
  * automatic removal from a list on insertion into another or the same list
  * it's possible to go from a node to the list (feature)
* Adding additional operations
  * find node in list / check if node is in list
  * ???

Of course nothing will happen before #19115 is merged.

The big questions are which do we want, if any?

Note also that the other low level data structures do **not** do any of this kind of validation and sanity checking.

**Comment by hlandau** [comment]
I don't think we need any of these for now.

Sorted insert might be useful, as might a sorting function. Mergesort is a wonderful algorithm where linked lists are concerned.

**Comment by paulidale** [comment]
I can't see us needing a sort for a linked list.  If we do, use a priority queue instead.  If we really need to sort a list, we should use a [skip list](https://en.wikipedia.org/wiki/Skip_list).

Yeah, the accessor names are long.  Happy to shorten their names but I think we want this to isolate the implementation & keep them.

The `ossl_list_` prefix on the field name?  We can't do it on the function names.

**Comment by hlandau** [comment]
On the field name, yes.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input
