### ISSUE TITLE
why the function SSL_CTX_set_veriy don't check the IP in the certificate with the real IP in the communicate?

### ISSUE THREAD

**Issue by fengmao31** [openssl/openssl#19135]
I make two certificates with 127.0.0.1. One in the public server, One in my laptop clinet. And I use Peer veriy parameter. Why the SSL_CTX_set_veriy don't check the IP in the certificate with the real IP in the communicate?

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input
