### ISSUE TITLE
'list' command enhancement | output of symmetric cipher algorithms, command itself and its description

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19133]
_release:_ openssl-3.0.5
_reference:_ (output truncated)
```
$ openssl help list
 -cipher-algorithms        List of cipher algorithms
 -asymcipher-algorithms    List of asymmetric cipher algorithms
```
Hello. The cipher family (_asymmetric_), which is on purpose mentioned in the description associated to `-asymcipher-algorithms`, is not in the description associated to `-cipher-algorithms`. Yet despite the presence of `-asymcipher-algorithms` that last could be interpreted as it might be covering symmetric cipher algorithms, there is no explicit statement in this regard.

A worth considering action would be the reformulation of both the command and the description it is associated to; e.g. "`-cipher-algorithms        List of cipher algorithms`" could become "`-sym-cipher-algorithms        List of symmetric cipher algorithms`".

At last in subsequent output, arranging ciphers according to categories _block_ and _stream_ ciphers, would serve the user in the context of a selection of an appropriate cipher.

**Comment by paulidale** [comment]
Our stability policy wouldn't allow this option's removal.  That doesn't mean a `-sym-cipher-algorithms` couldn't be added or that the help text and manual page updated to be specific that these are symmetric ciphers.

I'd favour the latter as a documentation only change rather than introducing option aliases.

**Comment by t8m** [comment]
> I'd favour the latter as a documentation only change rather than introducing option aliases.

+1 to that, IMO changing the option name itself is unnecessary.

**Comment by Ricky-Tigg** [comment]
So there would be no enhancement planned in regard to **suggestion** _block_ and _stream_ ciphers as it was ignored. We might consider closing as _not planned_ as what would be left to be planned can not even qualified as trivial, at least for me.

**Comment by Ricky-Tigg** [comment]
So there would be no enhancement planned in regard to **suggestion** _block_ and _stream_ ciphers, as it was ignored. Therefore it is worth considering closing now as _not planned_ as what would be planned couldn't even be qualified as trivial.

**Comment by t8m** [comment]
It is still a documentation and the help text change to be done. So please do not close this.

**Comment by Ricky-Tigg** [comment]
Of course not, since we can't. Note that there is now one objection, yours, which is enough to keep it open.
