### ISSUE TITLE
OpenSSL-1.1.1: OpenSSL server sends only the host certificate from the certificate chain during the handshake

### ISSUE THREAD

**Issue by ravinjhajharia** [openssl/openssl#19137]
I had created one openssl s_server having a list of certificates in a single PEM and tried connecting it through s_client. It only lists the host certificate not all the certificates in the chain. I had tried to simulate the same behaviour through openssl-1.0.2 as well, where I could see all the certificates listed in the handshake output.

**OpenSSL-1.1.1**

s_server:
> **openssl s_server -accept <host>:<port> -key <key_file> -certform PEM -cert <cert_file>**

 s_clinet:
> **openssl s_server -accept <host>:<port> -key <key_file> -certform PEM -cert <cert_file>**
> Can't use SSL_get_servername
> depth=0 C = US, ST = GA, L = Atlanta, O = Delta Air Lines Inc, OU = DELTA, CN = evdla588.delta.com
> verify error:num=20:unable to get local issuer certificate
> verify return:1
> depth=0 C = US, ST = GA, L = Atlanta, O = Delta Air Lines Inc, OU = DELTA, CN = evdla588.delta.com
> verify error:num=21:unable to verify the first certificate
> verify return:1
> 
> Certificate chain
>  0 s:C = US, ST = GA, L = Atlanta, O = Delta Air Lines Inc, OU = DELTA, CN = evdla588.delta.com
>    i:C = US, DC = com, DC = delta, DC = rl, DC = delta, O = Delta Air Lines Inc., OU = DELTA, CN = DAL-SHA2 L3 Low Iss E1 CA

**OpenSSL-1.0.2**
s_server:
> **openssl s_server -accept <host>:<port> -key <key_file> -certform PEM -cert <cert_file>**

 s_clinet:
> **openssl s_server -accept <host>:<port> -key <key_file> -certform PEM -cert <cert_file>**

> _CONNECTED(00000150)
> depth=3 C = US, O = Delta Air Lines Inc., OU = DELTA, CN = DAL-SHA2 L3 Low Root CA
> verify error:num=19:self signed certificate in certificate chain
> verify return:0
> Certificate chain
>  0 s:/C=US/ST=GA/L=Atlanta/O=Delta Air Lines Inc/OU=DELTA/CN=evdla588.delta.com
>    i:/C=US/DC=com/DC=delta/DC=rl/DC=delta/O=Delta Air Lines Inc./OU=DELTA/CN=DAL-SHA2 L3 Low Iss E1 CA
> 
>  1 s:/C=US/DC=com/DC=delta/DC=rl/DC=delta/O=Delta Air Lines Inc./OU=DELTA/CN=DAL-SHA2 L3 Low Iss E1 CA
>    i:/C=US/O=Delta Air Lines Inc./OU=DELTA/CN=DAL-SHA2 L3 Low Int CA
> 
>  2 s:/C=US/O=Delta Air Lines Inc./OU=DELTA/CN=DAL-SHA2 L3 Low Int CA
>    i:/C=US/O=Delta Air Lines Inc./OU=DELTA/CN=DAL-SHA2 L3 Low Root CA
> 
>  3 s:/C=US/O=Delta Air Lines Inc./OU=DELTA/CN=DAL-SHA2 L3 Low Root CA
>    i:/C=US/O=Delta Air Lines Inc./OU=DELTA/CN=DAL-SHA2 L3 Low Root CA_

Do we have some implementation changes from openssl-1.0.2 to 1.1.1 which result in this behaviour?

**Comment by ravinjhajharia** [comment]
@mattcaswell / @paulidale: Any thoughts/suggestions??

**Comment by t8m** [comment]
There is a `-cert_chain` option that should be used for the certificate chain. I am not sure why your use-case worked with 1.0.2 though.

**Comment by ravinjhajharia** [comment]
@t8m : Thank you for your prompt response. Do we have some API which can be used to set the certificate chain(extracted from PKCS12) in the SSL CTX created for the server application? Have tried SSL_CTX_add_extra_chain_cert but it seems to add only one certificate.

**Comment by t8m** [comment]
The SSL_CTX_set1_chain() sets stack of X509 certs as the chain for the server.

**Comment by ravinjhajharia** [comment]
@t8m : SL_CTX_set1_chain(SSL_CTX *ctx, STACK_OF(X509) *sk) set the certificate chain associated with the current certificate of ctx to sk. We need it other way. We need to stack of certificates to context.

**Comment by t8m** [comment]
No, SSL_CTX_set1_chain sets the chain in sk to the SSL_CTX ctx.
