### ISSUE TITLE
Consider discontinuing the usage practise of command option aliases and the mention "(deprecated)" associated to command options

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19139]
_release:_ openssl-3.0.5
_reference:_ (outputs truncated)
```
$ man 'OPENSSL(1ossl)'
SYNOPSIS
 openssl list standard-commands | (...)
$ openssl help list
 -commands                 List of standard commands
 -standard-commands        List of standard commands
 -digest-commands          List of message digest commands (deprecated)
 -cipher-commands          List of cipher commands (deprecated)
```
Hello. The introductions of command option aliases and the mention "_(deprecated)_" in descriptions being associated to command options, are singular in an already complex enough environment. Their presence might have root in common practices and left as heritage.
- Creations of aliases are not even a necessity and could be avoided for the benefit of use.
- When it comes to the mention "_(deprecated_)", options being associated to it are not even depreciated as they are proven alive, as any other command options not being associated to it. 

Both cases illustrate an unhealthy heritage certainly not worth considering keeping.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input
