### ISSUE TITLE
Consider enabling GitHub Discussions

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#19132]
Currently we get a lot of questions/support requests reported via GitHub issues.

We should maybe consider trialling GitHub Discussions to separate out this kind of traffic.

People might want to try creating a test repository with Discussions enabled and see what they think of it.

**Comment by mattcaswell** [comment]
I'm a little sceptical that it will help. It will just give us somewhere else to check and respond to user queries.

**Comment by levitte** [comment]
> I'm a little sceptical that it will help.

help...  what?  If the desire is to separate out discussions from issues that need a simpler fix, then actually separating them should help, no?  So I wonder what point of view your scepticism comes from

**Comment by mattcaswell** [comment]
> If the desire is to separate out discussions from issues that need a simpler fix, then actually separating them should help, no?

I don't think separating out discussions from issues that needs a simpler fix helps us to manage those things any better. I would prefer them all to be contained within issues. I am unconvinced that people will raise discussions in the discussions area (some people might, but many will put them in an issue anyway), and I'm also unconviced that people won't raise bugs in the discussions section. All of that leaves us worse off - we have 2 different types of things to manage (issues and discussions), rather than 1 (issues). Even if people actually do what they are supposed to do and raise discussions and issues in the right places - I still don't think that it makes our job of responding to those things any easier.

**Comment by hlandau** [comment]
It is worth noting that GitHub makes it easy to turn discussions into issues and issues into discussions.

**Comment by t8m** [comment]
Is this still relevant?

**Comment by levitte** [comment]
Dunno.  I still see benefits with the discussions tab, but I don't have better arguments than last time we discussed it...

**Comment by hlandau** [comment]
This has received some more support after our OTC F2F. It seems like the next step is to determine how to trial this. Do we just turn it on?

We just need to agree on the categories. The defaults are:

- Announcements (read-only, replies can be open)
- General (open-ended mode))
- Ideas (open-ended mode
- Polls (poll mode)
- Q&A (Q&A mode)
- Show and tell (open-ended mode)

For now we could just keep it super simple and have maybe:

- General Discussion (open-ended mode)
  - This becomes available to use instead of openssl-users for non-support posts.
- Q&A (Q&A mode)
  - This replaces use of GitHub Issues for asking questions and becomes the GitHub-based alternative for asking questions on openssl-users.

or even just Q&A.

**Comment by mspncp** [comment]
I'd place Questions & Answers (unabbreviated) first 

* Questions & Answers(Q&A mode)

for the impatient newbie who is unable ir not willing to read all the way to the end before asking their question,

and I might also add one or two more specific discussion subjects before "general" discussions, like e.g.

* Feature Requests (open-ended mode)
* Contribution Proposals (open-ended mode)
* General Discussion (open-ended mode)


(just two discussion topics which sorang to my mind)

**Comment by hlandau** [comment]
Personally I see feature requests and contribution proposals as still being issues for now.

**Comment by mspncp** [comment]
Makes sense.

**Comment by nhorman** [comment]
Given that we have discussions enabled currently, I'm assuming this is resolved and closing
