### ISSUE TITLE
OpenSSL KDA TwoStep implementation

### ISSUE THREAD

**Issue by jvdsn** [openssl/openssl#19146]
OpenSSL 3 has a CAVP certificate (https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=1938) which specifices KDA TwoStep (SP 800-56Cr2) support. Could you point me to the code where this is implemented? A keyword search for "two step" doesn't turn up any code, and the only SP 800-56C reference in the code is in the Single Step (or "One Step") KDF file.

**Comment by slontis** [comment]
If you refer to the RFC for SP800-56Cr2 you will see a reference to RFC 5869.
This is HKDF..

**Comment by paulidale** [comment]
Thanks @slontis for the succinct response.

**Comment by jvdsn** [comment]
> If you refer to the RFC for SP800-56Cr2 you will see a reference to RFC 5869. This is HKDF..

Thanks for the explanation, I suppose it was a bit confusing for me because HKDF is a kind of specialization of the TwoStep KDF.
