### ISSUE TITLE
'list' command | Consider adding an empty row at the end of each printed list of commands and algorithms for easier readability

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19140]
_release:_ openssl-3.0.5

Hello. Adding an empty row at the end of each printed list of commands and algorithms would serve a better determination of which list is which when several printing of lists are invoked in a same command line. Printing illustrating an uneasy determination (output truncated):
```
$ openssl list -{digest,kdf}-algorithms
  (...)
  NULL @ default
Provided KDFs and PDFs:
  (...)
```

**Comment by t8m** [comment]
OK, makes sense.
