### ISSUE TITLE
'list' command | Consider adding an option for printing at once all lists of algorithms

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19145]
_release:_ openssl-3.0.5

Hello. There are use-cases where an inventory of implemented algorithms is needed. Illustration if needed: _Is _ED448_ implemented in library?_ | This we do not know, nor where to find it. We could be served by `openssl list -{digest,kdf,(...)}-algorithms` to reveal it, assuming that all algorithms-related options are part of the command. That would be fastidious, not to speak about elegance. Could that be enough to justify the introduction of an option aiming for that task; e.g either `-algorithms` or `-all-algorithms`. At last the resulting output would be suitable for redirection via a pipe; e.g `openssl list -{(...),(...)}-algorithms | grep -i ed448`.

**Comment by mattcaswell** [comment]
Seems reasonable.
