### ISSUE TITLE
Install latest version of OpenSSL on Debian

### ISSUE THREAD

**Issue by mitarthshende** [openssl/openssl#19147]

**Comment by mitarthshende** [comment]
How to install latest version of OPenSSL on Debian based linux ?
Please tell the steps followed

**Comment by levitte** [comment]
The same as on any Unix, I guess?

However, *do not replace the openssl that is installed by the system*.  Simply place your OpenSSL elsewhere.
The default configuration installs it under /usr/local, which is fine, that's out of the way of system installations.

Other than that, the [quick build and installation guide](https://github.com/openssl/openssl/blob/master/INSTALL.md#quick-installation-guide) should get you started.

**Comment by levitte** [comment]
You might get better help if you tell us what you've tried and what happened
