### ISSUE TITLE
OpenSSL 1.1.0c fails to compile - Undefined reference to 'padlock_XXX'

### ISSUE THREAD

**Issue by Justin-Bieber** [openssl/openssl#1915]
I am trying to build OpenSSL in Debian x64(on my Virtualbox) as a 32bit static library.

Guest OS: Debian-AMD64

When I do:

`./Configure linux-generic32 no-shared --debug -m32 --prefix=/usr/local/OpenSSL_1.1.0c/Debug32`

I get the usual output that it is configured.

![configure output](https://i.stack.imgur.com/ZU2FF.png)

And later using:

`make`

I get this output:

![make output](https://i.stack.imgur.com/NSeqT.png)

[log.txt](https://github.com/openssl/openssl/files/588354/log.txt)

It shows undefined references, something relating to padlock. Is this padlock stuff a bug in the new version or am I doing something wrong?

**Comment by levitte** [comment]
Use `linux-elf` instead of `linux-generic32` and see if that makes it better

**Comment by Justin-Bieber** [comment]
Seems to compile, test and install just fine when I use `linux-elf` as per your suggetsion. But I'm worried over what that does since I don't know what "elf" is. Could you explain why it works or if there is any major impact? How does it also know that it's 32bit, because I tell it with the `-m32` argument(without it it would have been 64bit?)?

Thank you for your help levitte.

**Comment by Justin-Bieber** [comment]
seems i can't edit my posts here. just wanted to make a side note that someone suggested using `no-hw-padlock` which works for `linux-generic32`, but it obviously disabled this padlock thing that I also don't know anything about.

**Comment by levitte** [comment]
Elf is the usual executable format on Linux (and an increasing number of other Unix-like platforms). The name "linux-elf" is really a bit aged, it's from the time there was a transition from the old a.out format to elf. 

However, you could make life much easier by using `config`, which figures out an appropriate config target for you. Like this:

   ./config -d no-shared --prefix=...

**Comment by Justin-Bieber** [comment]
`./config` doesn't work because it defaults to "linux-x86_64". I'm guessing it doesn't make sense to game x86_64 while trying to produce 32bit libs.

**Comment by Justin-Bieber** [comment]
Also, `linux-elf` doesn't even work without the `-m32` flag.

**Comment by levitte** [comment]
It seems it needs an update, and a name change.  I'll get on that.

But yes, it would seem that `linux-elf` with `-m32` is the way to go then.

**Comment by Justin-Bieber** [comment]
Thanks a lot levitte. I'll dedicate a song to you and sing it every morning in the shower.

**Comment by dot-asm** [comment]
> It seems it needs an update

Relevant question in the context is how far back you want to go. I for one occasionally take it for a spin with 32-bit compiler from 2001 that does *not* recognize `-m32` as valid option. So that if it's enforced in config line, it would be problematic. Well, I'll naturally survive... Though one possibility can be to keep linux-elf and then add presumably more fashionable linux-x86, which would simply inherit linix-elf and add -m32 to cflags. Well, I'll probably have to survive...

**Comment by levitte** [comment]
I think this issue can be closed at this point
