### ISSUE TITLE
qnx

### ISSUE THREAD

**Issue by 532810439** [openssl/openssl#19150]
Can the QNX system compile OpenSSL？

**Comment by paulidale** [comment]
QNX is not one of the standard configurations and it isn't mentioned in our [platform policy](https://www.openssl.org/policies/platformpolicy.html).  That doesn't mean it's not possible, just that the project doesn't support it.

**Comment by 532810439** [comment]
It means that no attempt has been made？？

**Comment by paulidale** [comment]
Not by the project.  I've no idea if anyone else has tried or not.

**Comment by dlegaultbbry** [comment]
QNX maintains the openssl ports internally as they require some adaptation for cross-compiling and testing the library properly on the OS.
