### ISSUE TITLE
Can not build 1.1.1q with ClangCl 15.0.0 on Windows

### ISSUE THREAD

**Issue by emmenlau** [openssl/openssl#19160]
I've been using ClangCl since version 13.0.0 through all the 14.x versions up until 14.0.6 on Windows, and it has worked very well. Now I've updated ClangCl to 15.0.0 and Visual Studio to 17.3.3, and suddenly the build fails.

The error is `call to undeclared library function '_InterlockedExchangeAdd64'`.

I will post more information tomorrow when I'm actually physically in front of the development machine.

**Comment by emmenlau** [comment]
So here is more info about the build.

Compiler flags:
```
CPPFLAGS='       /D_ITERATOR_DEBUG_LEVEL=0     /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DDEBUG     /D_CRT_SECURE_NO_DEPRECATE /D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS'
CFLAGS=' /D__STDC_NO_ATOMICS__=1        /D_ITERATOR_DEBUG_LEVEL=0     /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DDEBUG     /D_CRT_SECURE_NO_DEPRECATE /D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS  -march=skylake /MDd /Z7'
CXXFLAGS='        /D_ITERATOR_DEBUG_LEVEL=0     /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DDEBUG     /D_CRT_SECURE_NO_DEPRECATE /D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS  -march=skylake /std:c++20 /MDd /Z7'
LDFLAGS='   /DEBUG:FULL'
```

Configuration:
```
Configuring project with --prefix=C:/data/usr-dst-C10Sk32c193331629c1500/Debug --openssldir=C:/data/usr-dst-C10Sk32c193331629c1500/Debug --libdir=lib shared threads no-ssl2 no-zlib enable-capieng -utf-8 -FS --debug VC-WIN64A
```

Build log attached: [buildlog.txt](https://github.com/openssl/openssl/files/9546126/buildlog.txt)

**Comment by levitte** [comment]
`include/internal/tsan_assist.h` assumes that `_InterlockedExchangeAdd64` exists as an intrinsic if `_WIN64` is defined.  However, some of the text in https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedexchangeadd64 hints that the intrinsic might not always be there.
That could mean that it would be better not to try to outsmart the compiler, and use `InterlockedExchangeAdd64` (without the underscore).  I can't really say if that's true or not, though...

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
