### ISSUE TITLE
A bad algorithm in crypto/modes/ctr128.c

### ISSUE THREAD

**Issue by peiqy** [openssl/openssl#1916]
Hello
Found a bad algorithm in function ctr128_inc_aligned() in file ctr128.c. Using expression '((d - c) ^ d) >> (sizeof(size_t) * 8 - 1)' to get the value of c is not appropriate. When (d-c) is x'7fffffff' and d is x'8fffffff', the expression get value 1. But the value of c should be 0(no carry). At lease, this problem exists in OpenSSL 1.0.2h, I don't check other releases. Please check, thanks.

Attach the related code as below.

```
static void ctr128_inc_aligned(unsigned char *counter)
{
    ...........      /* omit  some code*/

    data = (size_t *)counter;
    c = 1;
    n = 16 / sizeof(size_t);
    do {
        --n;
        d = data[n] += c;
        /* did addition carry? */
        c = ((d - c) ^ d) >> (sizeof(size_t) * 8 - 1);
    } while (n);
}
```

**Comment by dot-asm** [comment]
Right, it should be `(d - c) & ~d`... Hmmm, I recall forming a test to check carry... Ah! It's in gcm and it's not that large carry... On it...

**Comment by peiqy** [comment]
Will it be fix in all affected releases?

**Comment by dot-asm** [comment]
> Will it be fix in all affected releases?

No, only those that are still supported. Fix committed, closing. Thanks for report!
