### ISSUE TITLE
Error while opening pk12 cert

### ISSUE THREAD

**Issue by chavy25** [openssl/openssl#19167]
I'm having issues with openssl in a newer version while opening a certificate in pk12 format, here are my tests:

*** Good and **working** on version OpenSSL 1.1.1f ***

in linux CLI:
`openssl pkcs12 -in Cert.p12 -nodes     -passin pass:"12345678" | openssl x509 -noout -subject`
subject=C = cr, ST = Some-State, O = Internet Widgits Pty Ltd, CN = mariscoychicharon.com

*** Newer version **not working** OpenSSL 3.0.2 ***

in linux CLI:
`openssl pkcs12 -in Cert.p12 -nodes     -passin pass:"12345678" | openssl x509 -noout -subject`
40E74B9CFF7E0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Could not read certificate from <stdin>
Unable to load certificate

Please any help is appreciated, I need to understand this error as I need to open these type of certificates in a PHP project. 

Thanks in advance

**Comment by beldmit** [comment]
Try load a legacy provider.

**Comment by FdaSilvaYY** [comment]
> The default encryption algorithm for PKCS12 files changed from RC2-40-CBC in older versions of OpenSSL to AES-256-CBC in OpenSSL 3.0. RC2-40-CBC is considered legacy and insecure.
> 
> 
> 
> In order to read files encrypted using RC2-40-CBC you need to load the legacy provider, e.g. try this:
> 
> 
> 
> ````
> 
> openssl pkcs12 -provider legacy -provider default -in Cert.p12 -nodes -passin pass:"12345678" | openssl x509 -noout -subject
> 
> ````
> 
> 

This deserves a FAQ entry, no ?

**Comment by mattcaswell** [comment]
> This deserves a FAQ entry, no ?

Yes - probably.

**Comment by chavy25** [comment]
Thank you all very much, I sincerely appreciate it. Regrettably my customer requires to support this format still. I will modify the openssl.conf file to enable legacy so that php does not complain and take it from there. 

Again I really appreciate it.
