### ISSUE TITLE
Error attempting to use -extfile

### ISSUE THREAD

**Issue by dazinator** [openssl/openssl#19165]
Im on windows 11, however I have tried this with both a native openssl install, as well as the latest `alpine/openssl` docker container.

I've tried to use the following command to generate an X509 cert, from a CSR, CA, and an `-extfile`. The problem is the `-extfile`:

```
docker run --rm -it -v C:/DockerHostMount/openssl:/tmp/ alpine/openssl x509 -req -in /tmp/foo.csr -passin pass:secret -CA /tmp/new-ca.crt -CAkey /tmp/new-ca.key -out /tmp/foo.crt -CAcreateserial -days 365 -sha256 -extfile "/tmp/foo.cnf"
```

This yields the error:

```
x509: Error on line 1 of config file "/tmp/foo.cnf"
```

If I run it natively on windows 11 (so not via the docker image) I get:

> x509: Error on line 1 of config file "C:/DockerHostMount/openssl/foo.cnf"
FC310000:error:07000065:configuration file routines:def_load_bio:missing equal sign:crypto\conf\conf_def.c:513:HERE--> ■kline 1

Here is my `-extfile` contents:

```
keyUsage = digitalSignature
```

I am not sure what I am doing wrong?

**Comment by beldmit** [comment]
Could you please check that your file doesn't contain BOM?

**Comment by dazinator** [comment]
@beldmit yep - that was answer it was BOM, apologies - I wasn't aware this could cause a problem. Removing the BOM worked.

**Comment by beldmit** [comment]
Which version of openssl do you use?

**Comment by dazinator** [comment]
I was using the latest alpine/openssl image from docker hub - don't have the openssl version number handy at the mo but perhaps that helps, if not will get version number and post back here later.

**Comment by dazinator** [comment]
Here is version info:
> docker run --rm -it -v C:/DockerHostMount/openssl:/tmp/ alpine/openssl version
OpenSSL 1.1.1g  21 Apr 2020

**Comment by beldmit** [comment]
Sorry. Can't reproduce at least for Linux :(

**Comment by dazinator** [comment]
@beldmit 
Maybe this will help, here is my conf file just produced in notepad on windows
Note I had to change the extension to .txt to upload it here
[foo.txt](https://github.com/openssl/openssl/files/9585857/foo.txt)

**Comment by dazinator** [comment]
@beldmit - thanks for attempting. I won't have time to try and repro this for a while now, if I come accross it again, i'll come back here and maybe see if I can add more details.

**Comment by beldmit** [comment]
I was able to add a BOM but couldn't get the same error for 3.0.

So I suggest closing it for now

**Comment by dazinator** [comment]
Ok @beldmit fine by me, sorry you couldn't repro, I just remove BOM's in my workflow anyway now to avoid whatever was happening in my scenario which seems to work.
