### ISSUE TITLE
'list' command | Description attached to option '-objects'

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19174]
_release:_ openssl-3.0.5
(outputs truncated):
```
$ man openssl-list
       -objects
           Display a list of built in objects,(...)
$ openssl help list
 -objects                  List built in objects (...)
```
Hello. _List built in objects_ means _Display a list of a built being present in objects_. I hardly believe the subsequent function was originally meant to reflect a description that appears to be a non-sense. Hence i am in favour to believe that the original intention was to mean _Display a list of objects that are built in_, where _built in_ is implicitly referring to _something_, whatever the interpretation of _something_ you would wish readers to make, e.g. _library_, or else. Hence a suitable description would be accordingly _List built-in objects_.

**Comment by Ricky-Tigg** [comment]
Who would not be ready to deal from time to time with a low-talented developer? At least, that's fine with me, but being chosen to observe a way that strange to make your revelation behind a screen, certainly not.. I feel you need help. I was indeed convinced when you interacted in my reports that you might have had **very hard** time to **understand**, perhaps not only **sometimes**. I totally agree. Here is my advice , for free: do compare yourself with your colleagues. i mean of course your comments too. That's should be all you need right now.

**Comment by t8m** [comment]
Do you really think such comments are appropriate?

**Comment by Ricky-Tigg** [comment]
Do we speak now the same language? Still not.
