### ISSUE TITLE
[OpenSSL 1.1.1] Server Authentication TLS 1.3

### ISSUE THREAD

**Issue by mdeihly** [openssl/openssl#19177]
How the server con force the client to authenticate server's certificate.
In my app, on client-side I wrote this code:
			SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);
			if(!SSL_CTX_load_verify_locations(ctx, servChar, NULL))
				{
					// error
				}

However, my idea is that the server should force the client to do it. Otherwise any client (without certificate) can connect to server.

**Comment by mdeihly** [comment]
Thanks.
This what I have actually already done in my app. And on the client side , I called:
SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL); Then I loaded the server's self-signed certificate:
SSL_CTX_load_verify_locations(ctx, servChar, NULL).

However, my point is that even if i dont call these 2 functions on the client side, the client will always be able to connect to server.

**Comment by t8m** [comment]
Calling these functions on the client is relevant for authenticating the server to the client (i.e., that the server has a certificate that is trusted through a chain to a CA certificate trusted by the client). The server has nothing to do with that. There is no way for the server to know, whether the client called these functions or not. What the server can do is to verify the certificate possessed by the client (set up via SSL_CTX_use_certificate() and SSL_CTX_use_PrivateKey()) is trusted by the server.

**Comment by mdeihly** [comment]
"_There is no way for the server to know, whether the client called these functions or not._" This is what I was looking for.
Thanks.
