### ISSUE TITLE
Consider adding support for NTRU algorithm (sntrup761)

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19175]
_release:_ openssl-3.0.5

Hello. Post-quantum cryptographic primitives sntrup761x25519-sha512@openssh.com and chacha20-poly1305@openssh.com were introduced in [OpenSSH](https://www.openssh.com/releasenotes.html) respectively in v. 8.5, now as default in v. 9.0, and v. 6.5, promoted default cipher in v. 6.9. Could that existing support for this NTRU algorithm, paired with the X25519 ECDH key exchange, be a source of motivation justified to add **native** support for KEM in TLS v. 1.3 to OpenSSL? The latter appears to lack that support as it can be attested by `openssl list -kem-algorithms`.

**Comment by mattcaswell** [comment]
We only accept algorithm implementations which have been standardised by a recognised national or internal standards body. AFAIK there is no such standard for NTRU. It's also worth noting that NIST has recently [decided](https://nvlpubs.nist.gov/nistpubs/ir/2022/NIST.IR.8413.pdf#page=47&zoom=100,120,546) NOT to standardise NTRU and have instead selected CRYSTALS-Kyber for standardisation. So it doesn't seem appropriate for us to incorporate NTRU any time soon.

**Comment by Ricky-Tigg** [comment]
Correction needed; my fault, i should have noticed it. chacha20-poly1305 isn't part of the PQ algorithm family but an AEAD. AFAIK it is out of scope for PQ work.

**Comment by levitte** [comment]
Do note that it's always possible to put together a provider for what you want.

**Comment by Ricky-Tigg** [comment]
OpenSSLNTRU makes it possible. It also supports a second NTRU Prime parameter set, sntrup857. As a technical demonstration it could be experimented.

**Comment by Ricky-Tigg** [comment]
When thinking to it; _chacha20-poly1305, not a PQ algorithm_. Is that even so? The assertion that it is one as well as any other symmetric cipher, might find support in the following observation: None of known quantum attacks against them are statically more efficient than the _Grover_ search. That implies the following assumptions: a suitable key size (bit value not too small), and no known specific Quantum attacks against them.

**Comment by Ricky-Tigg** [comment]
When thinking to it; _chacha20-poly1305, not a PQ algorithm_. Is that even so? The assertion that it is one as well as any other symmetric cipher, might find support in the following observation: None of known quantum attacks against them are statistically more efficient than the _Grover_ search. That implies the following assumptions: a suitable key size (bit value not too small), and no known specific Quantum attacks against them.

**Comment by DemiMarie** [comment]
> We only accept algorithm implementations which have been standardised by a recognised national or internal standards body. AFAIK there is no such standard for NTRU. It's also worth noting that NIST has recently [decided](https://nvlpubs.nist.gov/nistpubs/ir/2022/NIST.IR.8413.pdf#page=47&zoom=100,120,546) NOT to standardise NTRU and have instead selected CRYSTALS-Kyber for standardisation. So it doesn't seem appropriate for us to incorporate NTRU any time soon.

Would an IETF standards-track RFC qualify for this?

**Comment by mattcaswell** [comment]
> Would an IETF standards-track RFC qualify for this?

Yes. Although note that we'd also have to make a decision to incorporate NTRU on its own merits, i.e. having a standard is a necessary pre-condition but not the only condition required to incorporate this.
