### ISSUE TITLE
Suggestion: -help switch for either - output to disk, pause each screenful, or change output to stdout

### ISSUE THREAD

**Issue by maroonbells** [openssl/openssl#19188]
The output for -help goes to stderr, which for windows users means it can't be redirected to a disk file nor piped through more.exe

For the 'openssl help' output, and that of many of the standard commands such as 'openssl x509 -help', the output is very long, so all the user sees is the last 25 lines. Even adjusting the cmd.exe window to have 50 lines isn't enough for some of these screens.

Possible enhancements:
a -pause switch that requires a keypress for each screenful of info
something like -stdout that changes output that normally goes to stderr would either go to stdout instead, or to a listed diskfile.

Maybe there is such a switch, but it's part of the display that scrolls past too fast to see it :)

**Comment by beldmit** [comment]
First, AFAIR, Windows supports this or that paging (less/more)

Second, in terminal scrolling is definitely supported

And last, could you please check that smth like `openssl x509 -help 2>&1` also works in Windows? I think it should.

**Comment by maroonbells** [comment]
Thanks. It turned out that the properties for screen buffer size was set to same size as the window lines, so it wasn't scrolling. But as for the 2& part, that's something I'd never heard of, and I suspect many OpenSSL users don't know either. That explains how people were able to say how many dots were needed to generate a DH safe prime.

I don't know why it's necessary for the -help output to go to stderr, this is the only program I know of which doesn't just send it to stdout. To redirect the output to file I need to do something like

	openssl x509 -help 2>file

... and to be able to view things on screen 1 page at a time, I need to do something like

	openssl x509 -help 2>file | more <file

I haven't been able to find syntax for 'more' which doesn't require specifying a filename.
