### ISSUE TITLE
static libraries not copied when installing

### ISSUE THREAD

**Issue by AlexanderBarnt** [openssl/openssl#19187]
I compiled the library for Windows and I ran the command: `nmake install`, I realized that this does not copy the static version of libraries? looks like they do exist in the root src folder as `libcrypto_static.lib` and `libssl_static.lib`

Can I safely copy these files to the `<Installation folder>\lib` and expect for everything to work properly if I use the static versions in my projects?

EDIT:
I also realized that there is no *.pdb files for these static libraries even in debug mode

EDIT 2:
Also when compiling with --release it is still producing the debug symbols (pdb), the documentation says; `Build OpenSSL without debugging symbols. This is the default.`?

**Comment by nhorman** [comment]
last time I built for windows (openssl-3.3) the static libraries were installed in the target installation directories, can you check with the latest release

And yes, nominally debug info is not produced unless you build with the debug option enabled

Given the age of this issue, I'm marking it as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by levitte** [comment]
Which openssl version are you talking about, @AlexanderBarnt?
