### ISSUE TITLE
3.0.5 mingw64 build invalid format specifiers

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#19185]
This is compilation output generated by a gcc 11.3 mingw64 compiler.

From my understanding is that by default Windows printf specifiers don'T support certain ones like %z[u/d] for size_t.

Adding this compiler flag generally solves these issues: -D__USE_MINGW_ANSI_STDIO=1

> 
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/evp_pkey_ctx_new_from_name-bin-evp_pkey_ctx_new_from_name.d.tmp -MT test/evp_pkey_ctx_new_from_name-bin-evp_pkey_ctx_new_from_name.obj -c -o test/evp_pkey_ctx_new_from_name-bin-evp_pkey_ctx_new_from_name.obj ../../dist/test/evp_pkey_ctx_new_from_name.c
> In file included from ../../dist/test/dtls_mtu_test.c:18:
> ../../dist/test/dtls_mtu_test.c: In function 'mtu_test':
> ../../dist/test/dtls_mtu_test.c:107:23: warning: unknown conversion type character 'z' in format [-Wformat=]
>   107 |             TEST_info("record %zu for payload %zu", reclen, s);
>       |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../dist/test/testutil.h:500:60: note: in definition of macro 'TEST_info'
>   500 | #  define TEST_info(...)     test_info(__FILE__, __LINE__, __VA_ARGS__)
>       |                                                            ^~~~~~~~~~~
> ../../dist/test/dtls_mtu_test.c:107:32: note: format string is defined here
>   107 |             TEST_info("record %zu for payload %zu", reclen, s);
>       |                                ^
> In file included from ../../dist/test/dtls_mtu_test.c:18:
> ../../dist/test/dtls_mtu_test.c:107:23: warning: unknown conversion type character 'z' in format [-Wformat=]
>   107 |             TEST_info("record %zu for payload %zu", reclen, s);
>       |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../dist/test/testutil.h:500:60: note: in definition of macro 'TEST_info'
>   500 | #  define TEST_info(...)     test_info(__FILE__, __LINE__, __VA_ARGS__)
>       |                                                            ^~~~~~~~~~~
> ../../dist/test/dtls_mtu_test.c:107:48: note: format string is defined here
>   107 |             TEST_info("record %zu for payload %zu", reclen, s);
>       |                                                ^
> In file included from ../../dist/test/dtls_mtu_test.c:18:
> ../../dist/test/dtls_mtu_test.c:107:23: warning: too many arguments for format [-Wformat-extra-args]
>   107 |             TEST_info("record %zu for payload %zu", reclen, s);
>       |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../dist/test/testutil.h:500:60: note: in definition of macro 'TEST_info'
>   500 | #  define TEST_info(...)     test_info(__FILE__, __LINE__, __VA_ARGS__)
>       |                                                            ^~~~~~~~~~~
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/evp_pkey_dparams_test-bin-evp_pkey_dparams_test.d.tmp -MT test/evp_pkey_dparams_test-bin-evp_pkey_dparams_test.obj -c -o test/evp_pkey_dparams_test-bin-evp_pkey_dparams_test.obj ../../dist/test/evp_pkey_dparams_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/evp_pkey_provided_test-bin-evp_pkey_provided_test.d.tmp -MT test/evp_pkey_provided_test-bin-evp_pkey_provided_test.obj -c -o test/evp_pkey_provided_test-bin-evp_pkey_provided_test.obj ../../dist/test/evp_pkey_provided_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -DNO_LEGACY_MODULE -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/evp_test-bin-evp_test.d.tmp -MT test/evp_test-bin-evp_test.obj -c -o test/evp_test-bin-evp_test.obj ../../dist/test/evp_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/exdatatest-bin-exdatatest.d.tmp -MT test/exdatatest-bin-exdatatest.obj -c -o test/exdatatest-bin-exdatatest.obj ../../dist/test/exdatatest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/exptest-bin-exptest.d.tmp -MT test/exptest-bin-exptest.obj -c -o test/exptest-bin-exptest.obj ../../dist/test/exptest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/fatalerrtest-bin-fatalerrtest.d.tmp -MT test/fatalerrtest-bin-fatalerrtest.obj -c -o test/fatalerrtest-bin-fatalerrtest.obj ../../dist/test/fatalerrtest.c
> x86_64-w64-mingw32-gcc  -I. -Iinclude -I../../dist -I../../dist/include -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/helpers/fatalerrtest-bin-ssltestlib.d.tmp -MT test/helpers/fatalerrtest-bin-ssltestlib.obj -c -o test/helpers/fatalerrtest-bin-ssltestlib.obj ../../dist/test/helpers/ssltestlib.c
> x86_64-w64-mingw32-gcc  -I. -Iinclude -Iapps/include -I../../dist -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/ffc_internal_test-bin-ffc_internal_test.d.tmp -MT test/ffc_internal_test-bin-ffc_internal_test.obj -c -o test/ffc_internal_test-bin-ffc_internal_test.obj ../../dist/test/ffc_internal_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/gmdifftest-bin-gmdifftest.d.tmp -MT test/gmdifftest-bin-gmdifftest.obj -c -o test/gmdifftest-bin-gmdifftest.obj ../../dist/test/gmdifftest.c
> x86_64-w64-mingw32-gcc  -I. -Iinclude -Iapps/include -I../../dist -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/hexstr_test-bin-hexstr_test.d.tmp -MT test/hexstr_test-bin-hexstr_test.obj -c -o test/hexstr_test-bin-hexstr_test.obj ../../dist/test/hexstr_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/hmactest-bin-hmactest.d.tmp -MT test/hmactest-bin-hmactest.obj -c -o test/hmactest-bin-hmactest.obj ../../dist/test/hmactest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/http_test-bin-http_test.d.tmp -MT test/http_test-bin-http_test.obj -c -o test/http_test-bin-http_test.obj ../../dist/test/http_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/ideatest-bin-ideatest.d.tmp -MT test/ideatest-bin-ideatest.obj -c -o test/ideatest-bin-ideatest.obj ../../dist/test/ideatest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/igetest-bin-igetest.d.tmp -MT test/igetest-bin-igetest.obj -c -o test/igetest-bin-igetest.obj ../../dist/test/igetest.c
> x86_64-w64-mingw32-gcc  -I. -Iinclude -Iapps/include -I../../dist -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/keymgmt_internal_test-bin-keymgmt_internal_test.d.tmp -MT test/keymgmt_internal_test-bin-keymgmt_internal_test.obj -c -o test/keymgmt_internal_test-bin-keymgmt_internal_test.obj ../../dist/test/keymgmt_internal_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/lhash_test-bin-lhash_test.d.tmp -MT test/lhash_test-bin-lhash_test.obj -c -o test/lhash_test-bin-lhash_test.obj ../../dist/test/lhash_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/localetest-bin-localetest.d.tmp -MT test/localetest-bin-localetest.obj -c -o test/localetest-bin-localetest.obj ../../dist/test/localetest.c
> x86_64-w64-mingw32-gcc  -I. -Iinclude -Iapps/include -I../../dist -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/mdc2_internal_test-bin-mdc2_internal_test.d.tmp -MT test/mdc2_internal_test-bin-mdc2_internal_test.obj -c -o test/mdc2_internal_test-bin-mdc2_internal_test.obj ../../dist/test/mdc2_internal_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/mdc2test-bin-mdc2test.d.tmp -MT test/mdc2test-bin-mdc2test.obj -c -o test/mdc2test-bin-mdc2test.obj ../../dist/test/mdc2test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/memleaktest-bin-memleaktest.d.tmp -MT test/memleaktest-bin-memleaktest.obj -c -o test/memleaktest-bin-memleaktest.obj ../../dist/test/memleaktest.c
> x86_64-w64-mingw32-gcc  -I. -Iinclude -Iapps/include -I../../dist -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/modes_internal_test-bin-modes_internal_test.d.tmp -MT test/modes_internal_test-bin-modes_internal_test.obj -c -o test/modes_internal_test-bin-modes_internal_test.obj ../../dist/test/modes_internal_test.c
> In file included from ../../dist/test/keymgmt_internal_test.c:28:
> ../../dist/test/keymgmt_internal_test.c: In function 'test_pass_rsa':
> ../../dist/test/keymgmt_internal_test.c:252:27: warning: unknown conversion type character 'z' in format [-Wformat=]
>   252 |                 TEST_info("i = %zu", i);
>       |                           ^~~~~~~~~
> ../../dist/test/testutil.h:500:60: note: in definition of macro 'TEST_info'
>   500 | #  define TEST_info(...)     test_info(__FILE__, __LINE__, __VA_ARGS__)
>       |                                                            ^~~~~~~~~~~
> ../../dist/test/keymgmt_internal_test.c:252:33: note: format string is defined here
>   252 |                 TEST_info("i = %zu", i);
>       |                                 ^
> In file included from ../../dist/test/keymgmt_internal_test.c:28:
> ../../dist/test/keymgmt_internal_test.c:252:27: warning: too many arguments for format [-Wformat-extra-args]
>   252 |                 TEST_info("i = %zu", i);
>       |                           ^~~~~~~~~
> ../../dist/test/testutil.h:500:60: note: in definition of macro 'TEST_info'
>   500 | #  define TEST_info(...)     test_info(__FILE__, __LINE__, __VA_ARGS__)
>       |                                                            ^~~~~~~~~~~
> x86_64-w64-mingw32-gcc  -I. -Iinclude -Iapps/include -I../../dist -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/namemap_internal_test-bin-namemap_internal_test.d.tmp -MT test/namemap_internal_test-bin-namemap_internal_test.obj -c -o test/namemap_internal_test-bin-namemap_internal_test.obj ../../dist/test/namemap_internal_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/ocspapitest-bin-ocspapitest.d.tmp -MT test/ocspapitest-bin-ocspapitest.obj -c -o test/ocspapitest-bin-ocspapitest.obj ../../dist/test/ocspapitest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/ossl_store_test-bin-ossl_store_test.d.tmp -MT test/ossl_store_test-bin-ossl_store_test.obj -c -o test/ossl_store_test-bin-ossl_store_test.obj ../../dist/test/ossl_store_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/packettest-bin-packettest.d.tmp -MT test/packettest-bin-packettest.obj -c -o test/packettest-bin-packettest.obj ../../dist/test/packettest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/param_build_test-bin-param_build_test.d.tmp -MT test/param_build_test-bin-param_build_test.obj -c -o test/param_build_test-bin-param_build_test.obj ../../dist/test/param_build_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/params_api_test-bin-params_api_test.d.tmp -MT test/params_api_test-bin-params_api_test.obj -c -o test/params_api_test-bin-params_api_test.obj ../../dist/test/params_api_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/params_conversion_test-bin-params_conversion_test.d.tmp -MT test/params_conversion_test-bin-params_conversion_test.obj -c -o test/params_conversion_test-bin-params_conversion_test.obj ../../dist/test/params_conversion_test.c
> x86_64-w64-mingw32-gcc  -I. -Iinclude -Iapps/include -I../../dist -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/params_test-bin-params_test.d.tmp -MT test/params_test-bin-params_test.obj -c -o test/params_test-bin-params_test.obj ../../dist/test/params_test.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/pbelutest-bin-pbelutest.d.tmp -MT test/pbelutest-bin-pbelutest.obj -c -o test/pbelutest-bin-pbelutest.obj ../../dist/test/pbelutest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/pbetest-bin-pbetest.d.tmp -MT test/pbetest-bin-pbetest.obj -c -o test/pbetest-bin-pbetest.obj ../../dist/test/pbetest.c
> x86_64-w64-mingw32-gcc  -Iinclude -Iapps/include -I../../dist/include -I../../dist/apps/include  -m64 -Wall -O3 -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/pem_read_depr_test-bin-pem_read_depr_test.d.tmp -MT test/pem_read_depr_test-bin-pem_read_depr_test.obj -c -o test/pem_read_depr_test-bin-pem_read_depr_test.obj ../../dist/test/pem_read_depr_test.c
> ../../dist/test/params_api_test.c: In function 'test_param_construct':
> ../../dist/test/params_api_test.c:535:35: warning: unknown conversion type character 'z' in format [-Wformat=]
>   535 |             TEST_note("iteration %zu var %s", j + 1, int_names[j]);
>       |                                   ^
> ../../dist/test/params_api_test.c:535:43: warning: format '%s' expects argument of type 'char *', but argument 2 has type 'size_t' {aka 'long long unsigned int'} [-Wformat=]
>   535 |             TEST_note("iteration %zu var %s", j + 1, int_names[j]);
>       |                                          ~^   ~~~~~
>       |                                           |     |
>       |                                           |     size_t {aka long long unsigned int}
>       |                                           char *
>       |                                          %lld
> ../../dist/test/params_api_test.c:535:23: warning: too many arguments for format [-Wformat-extra-args]
>   535 |             TEST_note("iteration %zu var %s", j + 1, int_names[j]);
>       |                       ^~~~~~~~~~~~~~~~~~~~~~
> ../../dist/test/params_api_test.c:546:35: warning: unknown conversion type character 'z' in format [-Wformat=]
>   546 |             TEST_note("iteration %zu var %s", j + 1, uint_names[j]);
>       |                                   ^
> ../../dist/test/params_api_test.c:546:43: warning: format '%s' expects argument of type 'char *', but argument 2 has type 'size_t' {aka 'long long unsigned int'} [-Wformat=]
>   546 |             TEST_note("iteration %zu var %s", j + 1, uint_names[j]);
>       |                                          ~^   ~~~~~
>       |                                           |     |
>       |                                           |     size_t {aka long long unsigned int}
>       |                                           char *
>       |                                          %lld
> ../../dist/test/params_api_test.c:546:23: warning: too many arguments for format [-Wformat-extra-args]
>   546 |             TEST_note("iteration %zu var %s", j + 1, uint_names[j]);
>       |        

               ^~~~~~~~~~~~~~~~~~~~~~

**Comment by hlandau** [comment]
Yeah, our use of %zu has caused problems when I've compiled using mingw. It makes it impossible to compile with `--strict-warnings` AFAICT. We use it in a lot of places. Not sure what we should replace it with.

**Comment by t8m** [comment]
Could we just disable these warnings on mingw? The BIO_printf and friends support the %z.

**Comment by hlandau** [comment]
That sounds reasonable.

**Comment by dlegaultbbry** [comment]
This seems to be in test code. I'm more worried that error messages will be bogus / provide invalid info on failures.

**Comment by t8m** [comment]
The %zu is supported by the OpenSSL library BIO_printf() so the warnings are false positives.

**Comment by paulidale** [comment]
We could disable the printf format checking on mingw?

An extra conditional in the definition of `ossl_bio__attr__` in `include/openssl/bio.h.in` would be enough.  Line 841 after the not Apple check.
