### ISSUE TITLE
No X509_VERIFY_PARAM_dup?

### ISSUE THREAD

**Issue by wintersteiger** [openssl/openssl#19207]
Since there is no `X509_VERIFY_PARAM_dup`, how do I copy (or up_ref) a `X509_VERIFY_PARAM`?

**Comment by t8m** [comment]
1. Ensure X509_VP_FLAG_LOCKED is not set in the source verify param with X509_VERIFY_PARAM_get_inh_flags
2. Create new X509_VERIFY_PARAM object
3. Use X509_VERIFY_PARAM_set_inh_flags to set X509_VP_FLAG_OVERWRITE|X509_VP_FLAG_RESET_FLAGS on the new object.
4. Use X509_VERIFY_PARAM_inherit() to copy the object contents from source to the new object.
5. If you want to have also identical inh_flags on the destination use get_inh_flags/set_inh_flags to overwrite them.
