### ISSUE TITLE
bad dh value

### ISSUE THREAD

**Issue by Squid-Bomb** [openssl/openssl#19200]
When using openssl 1.1.1k with FIPS on in a RHEL8 Server I receive the following when using pip3 install:

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: BAD_DH_VALUE] bad dh value (_ssl.c:1131)'))': /simple/jupyterlab-widgets/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: BAD_DH_VALUE] bad dh value (_ssl.c:1131)'))': /simple/jupyterlab-widgets/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: BAD_DH_VALUE] bad dh value (_ssl.c:1131)'))': /simple/jupyterlab-widgets/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: BAD_DH_VALUE] bad dh value (_ssl.c:1131)'))': /simple/jupyterlab-widgets/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: BAD_DH_VALUE] bad dh value (_ssl.c:1131)'))': /simple/jupyterlab-widgets/
Could not fetch URL https://pypi.org/simple/jupyterlab-widgets/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/jupyterlab-widgets/ (Caused by SSLError(SSLError(1, '[SSL: BAD_DH_VALUE] bad dh value (_ssl.c:1131)'))) - skipping

This problem does not exist with openssl 1.1.1c with FIPS on in a RHEL8 Server

**Comment by t8m** [comment]
This might be something RHEL specific @beldmit ?

**Comment by nhorman** [comment]
Did you open the issue in red hat bugzilla as requested? can you post a link here please?

marking as inactive, will be closed at the end of the 3.4 dev cycle barring further updates
