### ISSUE TITLE
fd_gets() in crypto/bio/bio_fd.c eats \n

### ISSUE THREAD

**Issue by mcepl** [openssl/openssl#1921]
Originally the issue comes from https://github.com/fedora-infra/fedmsg/pull/389. When trying to read
[easy_rsa.pem](https://github.com/openssl/openssl/files/590127/easy_rsa.pem.txt) with this program:
```c
/* build with
 * gcc -Wall -o test-load_cert -lssl -lcrypto $<
 */
#include <fcntl.h>
#include <openssl/bio.h>
#include <openssl/err.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>

int main(void)
{
    X509 *cptr = NULL;

    // BIO *bio = BIO_new_fd(open("/tmp/easy_rsa.pem", O_RDONLY), BIO_NOCLOSE);
    BIO *bio = BIO_new_fp(fdopen(open("/tmp/easy_rsa.pem", O_RDONLY), "rb"), BIO_NOCLOSE);
    cptr = PEM_read_bio_X509(bio, NULL, 0, NULL);
    if (cptr == NULL) {
        printf("Troubles!\n");
        ERR_print_errors_fp(stderr);
    }
    
    printf("I got %s\n", cptr);
    BIO_free(bio);
    return 0;
}
```
everything works perfectly fine. However, when switching two lines creating ``bio`` (from ``BIO_new_fp`` to ``BIO_new_fd``) I get ``NULL`` in ``cptr``.

According to @t8m , the problem lies in ``fd_gets()`` which eats ``\n``, so the read breaks on the empty line below ``serial:....`` line.

**Comment by mattcaswell** [comment]
PR #3442 (which as been merged) fixed this. Closing.
