### ISSUE TITLE
Document what BIO_CTRL_* codes required to be handled when implementing a custom bio

### ISSUE THREAD

**Issue by cppdev123** [openssl/openssl#19229]
After upgrading from 1.1.1 to 3 the openssl async wrapper stopped working and it turned out that it was the custom bio fault. openssl was using `BIO_CTRL_EOF` very often to check if eof is reached and my custom `BIO_ctrl` set with `BIO_meth_set_ctrl` was returning 1 for all codes.
I want to know which codes should I handle to avoid depending on undocumented behavior.
the custom bio is of type `BIO_TYPE_SOURCE_SINK` and it operates on a pre allocated memory buffer

**Comment by meins111** [comment]
I've recently implemented a custom src_sink bio based on openssl 3, below my custom bio ctrl method, maybe it can help you.

`  long CustomBioControl(BIO* caller, int cmd, long argumentLength, void* controlArgument)
  {
    switch (cmd)
    {
      case BIO_CTRL_PUSH: // 6
        return 0;
      case BIO_CTRL_EOF: // 2
        return 0;
      case BIO_CTRL_FLUSH: // 11
        return 1;

      default:
        return 1;
    }
  }`

**Comment by nhorman** [comment]
marking as inactive, will close at the end of the 3.4 dev cycle baring further input

**Comment by alexshpilkin** [comment]
Uh, as someone currently implementing a custom BIO, why is this closed again? As things are, the docs basically document half a feature. Perhaps it is in fact a full feature, but well, if it isn’t in the docs it doesn’t exist.
