### ISSUE TITLE
Strange behavior in openssl mac (or bad documentation)

### ISSUE THREAD

**Issue by patriksevallius** [openssl/openssl#19227]
The man page for openssl-mac says the following about input:

```
       -in filename
           Input filename to calculate a MAC for, or standard input by default.  Standard input is used if the filename is '-'.  Files are expected to be in binary format, standard input uses hexadecimal text format.
```

However, when trying to pass in hexadecimal text through standard input, I don't get the same result as when I give it a file with binary format.

With binary file:
```
$ echo "00112233445566778899aabbccddeeff" | xxd -r -p > tmp.bin
$ openssl mac -cipher AES-128-CBC -macopt hexkey:00000000000000000000000000000000 -in tmp.bin CMAC
BD71DBE9D210A18355D7468BE38E5A3C
```

With binary input:
```
$ echo "00112233445566778899aabbccddeeff" | xxd -r -p | openssl mac -cipher AES-128-CBC -macopt hexkey:00000000000000000000000000000000 -in - CMAC
BD71DBE9D210A18355D7468BE38E5A3C
```

With hexadecimal text input:
```
$ echo "00112233445566778899aabbccddeeff" | openssl mac -cipher AES-128-CBC -macopt hexkey:00000000000000000000000000000000 -in - CMAC
57A65C246ED1AEA5278BD9022D17BAE7
```

Have I misunderstood the documentation, is the documentation wrong, or is this a bug?

Version used: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by t8m** [comment]
There is both bug in the documentation and in the implementation.

The bug in the documentation is that the input should be always binary.

The bug in the implementation is that it sets FORMAT_TEXT when the input is stdin which is wrong - this does not have anything with hex encoding, it just means the stdin will be opened in text mode on platforms such as Windows that distinguish text and binary modes. That is of course wrong if the input is never hex-decoded.

Perhaps @faramir-dev would like to look at fixing this?

**Comment by patriksevallius** [comment]
I can give it a go now that I understand that it wasn't me misunderstanding anything.

**Comment by patriksevallius** [comment]
I've created a pull request: https://github.com/openssl/openssl/pull/19234

**Comment by patriksevallius** [comment]
Should I close this issue now that my fix has been merged?

**Comment by MILASTARX84** [comment]
NO BECAUSE IM STILL LEFT HANGING

**Comment by t8m** [comment]
Closing

**Comment by MILASTARX84** [comment]
Yo
