### ISSUE TITLE
Openssl 3.0.5 - How to make default provider not available for fips

### ISSUE THREAD

**Issue by stperron** [openssl/openssl#19224]
I am building an application using the fips module.  I am following the [migration guide](https://www.openssl.org/docs/manmaster/man7/migration_guide.html). 

My openssl.cnf looks like this

```
openssl_conf = openssl_init

.include /usr/local/ssl/fipsmodule.cnf

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1

 ```
and fipsmodule.cnf

 ```
[fips_sect]
activate = 1
install-version = 1
conditional-errors = 1
security-checks = 1
module-mac = 01:FC:36:9C:48:0D:3D:46:B8:52:BC:7A:49:64:EA:91:69:FB:0E:7C:7C:64:B7:C4:FF:C4:82:D9:8B:45:FB:C0
install-mac = 41:9C:38:C2:8F:59:09:43:2C:AA:2F:58:36:2D:D9:04:F9:6C:56:8B:09:E0:18:3A:2E:D6:CC:69:05:04:E1:11
install-status = INSTALL_SELF_TEST_KATS_RUN

 ```

When i start my application i use the method OSSL_PROVIDER_available to see which provider are available as for example for fips

 ```
    if (OSSL_PROVIDER_available(NULL, "fips") == 1)
    {
       printf("LOADING fips provider.\n");
    }
 ```
With this configuration the providers fips, base and default are available.  However, i do not wish to have the default provider for my fips implementation so i did what was recommended in the documentation and added the code .

 ```
    /* Disallow falling back to the default library context */
    OSSL_PROVIDER* nullp = OSSL_PROVIDER_load(NULL, "null");
 ```
With this code i got only the providers fips and base as i think was correct for my fips only application (fips + base)

However is there a way to do this using only the configuration openssl.cnf file.  I have try several things such as adding the default provider in the file and remove the activate =1 such as

 ```
openssl_conf = openssl_init

.include /usr/local/ssl/fipsmodule.cnf

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
base = base_sect
default = default_sect

[base_sect]
activate = 1

[default_sect]
#activate = 1

  ```
But this did not work, i still got the providers fips, base and default as available.

I am still confused a little bit if i load the fips provider and the default provider would openssl fallback to the default provider if a cipher is not available in the fips provider ?

I also read in the wiki that the property fips=yes exists... Is this the way to go ... 

 ```
openssl_conf = openssl_init
  
  .include /usr/local/ssl/fipsmodule.cnf
  
  [openssl_init]
  providers = provider_sect
  alg_section = algorithm_sect
  
  [provider_sect]
  fips = fips_sect
  default = default_sect
  
  [default_sect]
  activate = 1
  
  [algorithm_sect]
  default_properties = fips=yes

  ```

Best regards

**Comment by t8m** [comment]
> ```
> [default_sect]
> #activate = 1
> ```
> 
> 
>     
>   
> 
> But this did not work, i still got the providers fips, base and default as available.

This is quite weird. What happens if you delete or comment out the default_sect and its reference altogether?

**Comment by stperron** [comment]
Hi,

I tried 2 things first i modified my openssl.cnf file so i have

```
openssl_conf = openssl_init

.include /usr/local/ssl/fipsmodule.cnf

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
base = base_sect
default = default_sect

[base_sect]
activate = 1

#[default_sect]
#activate = 1
 ```
and then i commented the line 

default = default_sect

But in both cases i still see that the provider fips, base and default are available... But is available means that the provider is loaded this is the part i am not sure but from the test i am doing it seems to fallback to the default provider for some of the ciphers.  I did not see in the OSSL_provider any method that can confirm me if a provider is actually loaded or not.

I am not actually working with fips context i am just using the method as is so basically i think i am using the default context and the only way right now to make un-available the default provider is to explicitly load the null provider using some code at the start of my main function as i explain in my previous comment.

Thanks

**Comment by t8m** [comment]
The `OSSL_PROVIDER_available()` indicates the provider is loaded into the libctx and is ready to use or already in use.

**Comment by t8m** [comment]
How do you load the configuration? I assume that the default provider is loaded by the means of the fallback and only after that the config file is loaded which would disable the fallback.
Maybe explicitly calling `OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL);` on startup of your application could help?

**Comment by mattcaswell** [comment]
It doesn't explain your main problem, but your config file attempts to load some providers into the default library context, and this:

````
   /* Disallow falling back to the default library context */
   OSSL_PROVIDER* nullp = OSSL_PROVIDER_load(NULL, "null");
````
additionally loads the null provider into the default library context. There is *no* point in loading the null provider *and* other providers into the default library context. IIUC from your description that seems like what you are doing. The null provider is a provider is usually only loaded into the default library context if no other providers are loaded there at all, and you want to stop accidental use of that library context.

**Comment by t8m** [comment]
I suppose the reason the load of the null provider helps is that the fallback load of the default provider is disabled by it and the config file is loaded after the default provider was already loaded into the context via the fallback. So my suggestion to do the explicit call to `OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL);` instead.

**Comment by stperron** [comment]
Hi, i have added the line

```
OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL);
 ```
at the start of my main function and now i can only see the fips and the base providers as expected. 

Thank you all very much for your quick answers.

Best regards

**Comment by t8m** [comment]
The default provider can be loaded by a so called fallback if there is no provider loaded yet into a libctx and you try to fetch an algorithm. The init call makes the fallback disabled for the NULL libctx because it loads explicitly the configuration file which you've set up to load the fips and base providers. Please see the `Explicit fetching` section of the crypto(7) manual page.

**Comment by t8m** [comment]
Once the default provider is loaded into the context, it will stay loaded even if the config file is later loaded. It can be loaded implicitly by some call that triggers internal OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG) call.

**Comment by mattcaswell** [comment]
> The default provider can be loaded by a so called fallback if there is no provider loaded yet into a libctx and you try to fetch an algorithm. The init call makes the fallback disabled for the NULL libctx because it loads explicitly the configuration file which you've set up to load the fips and base providers.

Doesn't this suggest a possible bug somewhere? Any fetch against the NULL libctx should surely implicitly load the config file if we might otherwise fallback?

**Comment by t8m** [comment]
Then the question is why do we have any other OPENSSL_init_crypto() calls than those with OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG) at all inside libcrypto. Because apart from some non-crypto manipulation functions such as ASN1 parsing or Base 64 encoding/decoding there is not much you can do with libcrypto without fetching an algorithm. I suppose if you never use NULL libctx it might have some reason though.

**Comment by beldmit** [comment]
Probably because we want to avoid an explicit initialization.

**Comment by mattcaswell** [comment]
There should only be a very small number of locations in the library where we actually need to init with `OPENSSL_INIT_LOAD_CONFIG`. Basically anywhere that we read a global (or default libctx global), variable that could be impacted by that config file. As far as providers are concerned that means anywhere that we read the `store->providers` stack - since that is where providers that are activated by config get stored. Currently that seems to be in the internal functions `ossl_provider_doall_activated` and `ossl_provider_find`. If there are any other locations that we read `store->providers` but don't call `OPENSSL_INIT_LOAD_CONFIG` then we might have an issue. Looks like `provider_activate_fallbacks` could be one such location.

**Comment by nhorman** [comment]
marking as inactive, will close at the end of the 3.4 dev cycle baring further input
