### ISSUE TITLE
OpenSSL 1.1.0c hitting WinAPI 32k character limit when building with msys2/mingw

### ISSUE THREAD

**Issue by greatwolf** [openssl/openssl#1923]
After doing a successful perl configure in a msys2 terminal, I ran `mingw32-make` getting the following output:

    mingw32-make -j 1
    perl "-I." -Mconfigdata "util/dofile.pl" \
        "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal
    /dso_conf.h
    perl "-I." -Mconfigdata "util/dofile.pl" \
        "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.
    h
    mingw32-make depend && mingw32-make _all
    mingw32-make[1]: Entering directory 'G:/openssl-1.1.0c'
    process_begin: CreateProcess(G:\msys64\usr\bin\sh.exe, G:/msys64/usr/bin/sh.exe
    -c "...", ...) failed.
    make (e=87): The parameter is incorrect.
    Makefile:205: recipe for target 'depend' failed
    mingw32-make[1]: *** [depend] Error 87
    mingw32-make[1]: Leaving directory 'G:/openssl-1.1.0c'
    Makefile:128: recipe for target 'all' failed
    mingw32-make: *** [all] Error 2

For brevity I replaced the wall of bash script with `...` above. Searching around the net, the `e=87 parameter incorrect` error indicates that the 32k character limit on the Windows API is being hit. Are there any known workarounds for building this natively on windows using mingw?

**Comment by levitte** [comment]
I assume that was one of the `ar` commands?  They are long, that's true.  We could change them to a series of `ar`s, one for each object file.  See if this patch helps you:

```
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index 84ceb76..d556bde 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -1059,10 +1059,12 @@ EOF
   sub obj2lib {
       my %args = @_;
       my $lib = $args{lib};
-      my $objs = join(" ", map { $_.$objext } @{$args{objs}});
+      my @objs = map { $_.$objext } @{$args{objs}};
+      my $objs = join(" ", @objs);
+      my $cmds = join("\n\t", map { '$(AR) $@ '.$_ } @objs);
       return <<"EOF";
 $lib$libext: $objs
-	\$(AR) \$\@ \$\?
+	$cmds
 	\$(RANLIB) \$\@ || echo Never mind.
 EOF
   }
```

**Comment by greatwolf** [comment]
Hmm, it looks like `mingw32-make` is subtly different from gnu `make`. I just installed make through msys2 `pacman -S make` and rerun the above build commands again but with `make` this time. It appears to be building now.

**Comment by dzmat** [comment]
I confirm. When I use QT Creator bundled **mingw32-make**, I hit that error too. But installed via pacman, **make** works.

**Comment by inbrahimnasson** [comment]
the problem is not with the QT Creator bundled mingw32-make but the make file generated so if you delete the line causing the error and rewrite it should  work well .i use notepad++ ,character encoding problem in the makefile

**Comment by dzmat** [comment]
What exactly needs to be edited? I can not figure out which character is wrong, all of them are normal ASCII character.

**Comment by inbrahimnasson** [comment]
“make (e=87): The parameter is incorrect.
Makefile:205: recipe for target 'depend' failed”

On line number 205 of the generated makefile
205 depend :
206          @:

Earse them and rewrite them i guess the problem is charater based or spacing
