### ISSUE TITLE
OpenSSL 3.x FIPS self test query

### ISSUE THREAD

**Issue by iamwum** [openssl/openssl#19246]
Hi,
As per the deatils provided in https://www.openssl.org/docs/man3.0/man7/fips_module.html (Making all applications use the FIPS module by default), I have updated Openssl 3.x config file to make sure FIPS module is enabled for all applications which are linking libcrypto. 

Based on above mentioned information, I have created a sample C++ application and compiled it by linking with libcrypto. On executing sample application binary, self test result is not getting printed on screen.

Note: On running OpenSSL fipsinstall command, self-test result is printed on screen.

Any suggestions?

Regards

**Comment by t8m** [comment]
Please look at the apps/fipsinstall.c. The `OSSL_SELF_TEST_set_callback(NULL, self_test_events, NULL);` call along with the self_test_events() callback function provide the self-test result printing.

**Comment by mattcaswell** [comment]
Note that the self tests are run during installation, but not each time that the module is loaded.

**Comment by iamwum** [comment]
> Please look at the apps/fipsinstall.c. The `OSSL_SELF_TEST_set_callback(NULL, self_test_events, NULL);` call along with the self_test_events() callback function provide the self-test result printing.

Does this mean that the sample application is suppose to explicitly call OSSL_SELF_TEST_set_callback API to know the self test result ?

**Comment by iamwum** [comment]
> Note that the self tests are run during installation, but not each time that the module is loaded.

As far as I know, for FIPS validation, any application linking libcrypto should run self test on every startup.

**Comment by paulidale** [comment]
NIST introduced IG 9.11 which relaxed the rules around when and how often the self tests needed to be run.  It suffices to run most of them at installation time which is what fipsinstall does.

**Comment by t8m** [comment]
> Does this mean that the sample application is suppose to explicitly call OSSL_SELF_TEST_set_callback API to know the self test result ?

You can find out the result of the self test implicitly - when OSSL_PROVIDER_load(libctx, "fips") returns NULL the self test failed (or the provider was not found). If you load the fips provider by means of loading the configuration file you can also test for it with OSSL_PROVIDER_available() function to avoid calling load/unload.

The provider is never loaded into the libctx if the self tests fail (or failed during the installation).

You can make the fips provider to always run the self tests on startup if you remove the install-mac and install-status variables from the fipsmodule.cnf file.

You can also trigger the self test explicitly by calling OSSL_PROVIDER_self_test().

**Comment by iamwum** [comment]
Thanks, it was very helful. Fips provider is loaded successfully in my sample application using the configuration method.
Is there a way to fail a particular selftest algorthim programatically?

**Comment by raghupcr** [comment]
@t8m 
Hi Tomas,
Sry to comment here as it is closed issue

we are also trying to run the self test on demand and not very much successful

i could see your comment as "You can make the fips provider to always run the self tests on startup if you remove the install-mac and install-status variables from the fipsmodule.cnf file."

but in our cnf file i dont see these attributes

[fips_sect]
#activate = 1
conditional-errors = 1
security-checks = 1
module-mac = 53:C8:

Any inputs please here

**Comment by iamwum** [comment]
@raghupcr 
Did you run “fipsinstall” command ?

**Comment by t8m** [comment]
> but in our cnf file i dont see these attributes

In that case you probably did not run the openssl fipsinstall command and that actually means the self tests will be always run on load of the fips provider.

**Comment by raghupcr** [comment]
> @raghupcr Did you run “fipsinstall” command ?

Hi we didnt run the fipsinstall command manually, but when we configure the openssl we gave enable-fips which intern calls the install-fips which intern calls the fipsinstall command is what we read? correct me if i m wrong plz

**Comment by raghupcr** [comment]
> > but in our cnf file i dont see these attributes
> 
> In that case you probably did not run the openssl fipsinstall command and that actually means the self tests will be always run on load of the fips provider.

Hi Tomas,

So when ever we do ossL_provider_load("fips") it will call the self test at the startup ?
is that right

**Comment by iamwum** [comment]
@raghupcr 
OpenSSL fipsinstall execution is required to calculate the MAC of fips.so which gets validated on the system.

**Comment by raghupcr** [comment]
> @raghupcr OpenSSL fipsinstall execution is required to calculate the MAC of fips.so which gets validated on the system.

Hi @iamwum ,

MAC is calculated already and is available in the fipsmodule.cnf

module-mac = 53:C8:E8:xxxxxxxxxxx

as we have installed with enable-fips in the configure it has taken care of this

**Comment by iamwum** [comment]
1. For on demand selftest (on application startup),  openssl.cnf can be updated to load fips provider which will enable fips mode in libcrypto  thus executing self test on startup (or) load it programmatically in your application as you stated earlier. OpenSSL.cnf change is simpler approach.

2. I doubt if fipsinstall got executed as part of install because fipsmodule.cnf is not updated with install-mac and install-status attributes, try running fipsinstall and launch your application, that should give some clarity.

**Comment by paulidale** [comment]
> So when ever we do ossL_provider_load("fips") it will call the self test at the startup ?
> is that right

Not entirely.  Fipsinstall runs the power up self tests.  When the FIPS provider is loaded, the power up self tests are not generally run.  There are some mandated tests which do get run -- entropy continuous tests e.g.

**Comment by paulidale** [comment]
> … which will enable fips mode in libcrypto …

A small point: libcrypto doesn't have a FIPS mode anymore.  Libcrypto knows nothing about FIPS.  All FIPS specific things are in the FIPS provider.

**Comment by raghupcr** [comment]
> > So when ever we do ossL_provider_load("fips") it will call the self test at the startup ?
> > is that right
> 
> Not entirely. Fipsinstall runs the power up self tests. When the FIPS provider is loaded, the power up self tests are not generally run. There are some mandated tests which do get run -- entropy continuous tests e.g.
> 
> On demand tests require your application to start them. That's the reason they are called _on demand_. If you want the self tests to run on load, rerun fipsinstall with the `-self_test_onload` command line option. Given the comments above, I suspect fipsinstall was run as part of the build process.

Thanks Dr.Paul,

Given the comments above, I suspect fipsinstall was run as part of the build process.
------- Means we need to run this command manually, will it not take place automatically when we configure enable-fips and build?

readme-fips.md
==============make install
effectively executes the following install targets

$ make install_sw
$ make install_ssldirs
$ make install_docs
$ make install_fips     # for `enable-fips` only

The Installation of the FIPS provider consists of two steps. In the first step, the shared library is copied to its installed location, which by default is

/usr/local/lib/ossl-modules/fips.so                  on Unix, and
C:\Program Files\OpenSSL\lib\ossl-modules\fips.dll   on Windows.
In the second step, the openssl fipsinstall command is executed, which completes the installation by doing the following two things:

**Comment by paulidale** [comment]
You'll only need to run it manually if you want the on load self tests.

**Comment by laogaolao** [comment]
hi Tomas & Paul @t8m @paulidale 
Sorry, I am searching the openssl selftest function and find this topic, and this topic helps a lot for me. But I have another questions is does openssl implemented the conditional test such as Pair-Wise Consistency Test when module generates public or private key pairs? I remember the conditional test function was implemented in the legacy versoin but not found in the 3.0, maybe I missed something, could you give some suggestion? Thanks in advance.

**Comment by paulidale** [comment]
Yes it does.

**Comment by laogaolao** [comment]
@paulidale Another question is reseed test, does the openssl also implemented it as a conditional test? Thanks.

**Comment by laogaolao** [comment]
@paulidale Thanks for confirmation. I asked this question because I remember reseed test is new requirement for fips-140-3, not sure openssl has implemented it. Thanks again.

**Comment by KPDeepa** [comment]
make file : CONFIG = ./Configure --config=config enable-fips --openssldir=/usr/local/lib/ossl-modules/ linux-mips-xlp enable-ec enable-ecdsa enable-ecdh shared threads -lpthread -D_REENTRANT
openssl.cnf: 
.include /mswitch/bin/fipsmodule.cnf

[openssl_init]
providers = provider_sect

# List of providers to load
[provider_sect]
default = default_sect
fips = fips_sect


[default_sect]
activate = 1

[fips_sect]
activate = 1

tryin to load from the application

    OSSL_LIB_CTX *libctx = OSSL_LIB_CTX_new();

    OSSL_PROVIDER *fipsProvider = NULL;
    fipsProvider = OSSL_PROVIDER_load(libctx, "fips");
    if (fipsProvider == NULL) {
         log("%s:%d unable to load fips provider",__FUNCTION__,__LINE__);
         print_openssl_error();
    }
    else {
       log("%s:%d fips provider loaded succesfully;",__FUNCTION__,__LINE__);
    }
And the error that i got is below 👍 
OpenSSL Error: error:1C8000D5:Provider routines::missing config data
OpenSSL Error: error:1C8000E0:Provider routines::fips module entering error state
OpenSSL Error: error:1C8000D8:Provider routines::self test post failure
OpenSSL Error: error:078C0105:common libcrypto routines::init fail

~ # find . -name *fips.so*
./usr/local/lib/ossl-modules/fips.so
./lib/fips.so

~ # find . -name *fipsmodule.cnf*
./mswitch/bin/fipsmodule.cnf
~ #

kindly help

**Comment by paulidale** [comment]
Kindly raise a new issue with your problem.
