### ISSUE TITLE
Why some TLS aync logic did not use the async in CRYPTO

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#19245]
Why some TLS aync logic did not use the async in CRYPTO, this make the miminor statemachine in TLS more complex.

TLS async logic:
```C 
    /* Finished parsing the ClientHello, now we can start processing it */
    /* Give the ClientHello callback a crack at things */
    if (sctx->client_hello_cb != NULL) {
        /* A failure in the ClientHello callback terminates the connection. */
        switch (sctx->client_hello_cb(ssl, &al, sctx->client_hello_cb_arg)) {
        case SSL_CLIENT_HELLO_SUCCESS:
            break;
        case SSL_CLIENT_HELLO_RETRY:
            s->rwstate = SSL_CLIENT_HELLO_CB;
            return -1;
        case SSL_CLIENT_HELLO_ERROR:
        default:
            SSLfatal(s, al, SSL_R_CALLBACK_FAILED);
            goto err;
        }
    }
```
The async in CRYPTO:
/crypto/async

**Comment by t8m** [comment]
There is no asynchronous processing in the code snippet above. So I do not quite understand how this is related to crypto/async.

**Comment by KanPlus** [comment]
> ```c
> sctx->client_hello_cb
> ```

The SSL_CLIENT_HELLO_RETRY was asynchronous processing. That is, the SSL_accept required called again to process this mini state.

**Comment by mattcaswell** [comment]
crypto/async is a much newer addition than the IO style async that most of libssl uses. Unfortunately crypto/async is not available on all platforms so cannot be used as a general replacement for the IO style of async. There would also be backwards compat issues swapping from one form to the other, even if it were desirable to do so.

**Comment by KanPlus** [comment]
> crypto/async is a much newer addition than the IO style async that most of libssl uses. Unfortunately crypto/async is not available on all platforms so cannot be used as a general replacement for the IO style of async. There would also be backwards compat issues swapping from one form to the other, even if it were desirable to do so.

got it,thanks.
