### ISSUE TITLE
Do we have any API like PKCS5_PBKDF2_HMAC_SHA256()

### ISSUE THREAD

**Issue by Praveer1981** [openssl/openssl#19247]
PKCS5_PBKDF2_HMAC, PKCS5_PBKDF2_HMAC_SHA1 - password based derivation routines with salt and iteration count
I want to use PBKDF2 with HMAC-SHA-256 and enough iterations - EVP_KDF-PBKDF2 with 310.000 iterations. Do we have any such kind of API. I can see  that we have an API PKCS5_PBKDF2_HMAC_SHA1, but it uses SHA1. I want to use SHA256

any suggestions ?

**Comment by Praveer1981** [comment]
@t8m Any thought or any idea how could I achieve my objective ?

**Comment by Praveer1981** [comment]
@t8m  

  int PKCS5_PBKDF2_HMAC( , , , , ,**EVP_sha256(void),**  ); 
should it work?

**Comment by paulidale** [comment]
Try looking at the PBKDF2 demo program: https://github.com/openssl/openssl/blob/master/demos/kdf/pbkdf2.c

**Comment by Praveer1981** [comment]
@paulidale  Thanks, any idea how the data of this arry has been computed ?
https://github.com/openssl/openssl/blob/master/demos/kdf/pbkdf2.c#L46

**Comment by mattcaswell** [comment]
It's just a test vector calculated by running a known-good implementation of the algorithm with the same parameters previously. You wouldn't need to do that in real-world usage.

**Comment by Praveer1981** [comment]
@mattcaswell Well,  let's say my password  is "**secretkey**", onece I apply the API's to get PBKDF2_SHA256 output, then how would I know that the given output is correct?

**Comment by t8m** [comment]
> Well, let's say my password is "**secretkey**", onece I apply the API's to get PBKDF2_SHA256 output, then how would I know that the given output is correct?

You cannot know that apart from computing it with a different implementation of the same algorithm and comparing the results.

**Comment by Praveer1981** [comment]
> You cannot know that apart from computing it with a different implementation of the same algorithm and comparing the results.

Sure, thanks for the clarification
