### ISSUE TITLE
Noob Question: Is there way to avoid calling SSL_read multiple times (SSL_pending erroneously returns 0)

### ISSUE THREAD

**Issue by devzzzero** [openssl/openssl#19250]
Hi everyone,

I am playing with OpenSSL-3.0.1, plugging it into an existing TCP/IP app.
There are two servers (Side A and Side B), and they both talk to each other.
```
Side A outgoing [4 bytes pending] [4 -> 26] 01000000   ->  17030300 1549ff48 31ff0dff 6d5cff56 ffff0a35 55ff120f ffff
Side B outgoing [4 bytes pending] [4 -> 26] 01000000   ->  17030300 15603f27 ff28ffff 150bff15 20ff56ff ff2668ff ffff
Side B incoming [26 bytes pending] [26 -> 4] 17030300 1549ff48 31ff0dff 6d5cff56 ffff0a35 55ff120f ffff  ->  01000000 
Side A incoming [3614 bytes pending] [3614 -> 0] 17030307 0a6bff3c ffff47ff ffffffff ffff02ff ff7c087d ff7fff58 0b531a0e   ->  (protocol stuff, ignored)
Side B outgoing [40 bytes pending] [40 -> 62] 02000000 270c2b0c ffff0000 00000000 116065ff ffffff53 00000000 00000000   ->  17030300 39ffff00 2cff563e ffff0fff ff1f4233 ffff4471 54ff6e67 6f69ffff 
Side A incoming [26 bytes pending] [26 -> 4] 17030300 15603f27 ff28ffff 150bff15 20ff56ff ff2668ff ffff  ->  01000000 
Side A incoming [62 bytes pending] [62 -> 40] 17030300 39ffff00 2cff563e ffff0fff ff1f4233 ffff4471 54ff6e67 6f69ffff   ->  02000000 270c2b0c ffff0000 00000000 116065ff ffffff53 00000000 00000000 
Side A outgoing [40 bytes pending] [40 -> 62] 02000000 280c2c0c ffff0000 00000000 116065ff ffffff53 33330000 00000000   ->  17030300 39ff7fff 57ff56ff 23ff7f20 1a016051 0affffff 72ffff1d ff1dff42 
*Side A outgoing [40 bytes pending] [40 -> 62] 09000000 0100110e ffff0000 00000000 116065ff ffffff53 33330000 00000000   ->  17030300 396b635a 28ffff13 ffffff5f 2472ff55 69ff7f01 3cffffff ff33ffff 
*Side A outgoing [40 bytes pending] [40 -> 62]  ......./some-data-here-here  ->  17030300 39ff500a 51ff66ff 3b5927ff 6a6fffff ffff6f30 ffff7fff 4d3c0226 
*Side A outgoing [8 bytes pending] [8 -> 30] 01000000 00000000   ->  17030300 19ff0fff 75ff68ff 28ffff6c ff374d4c ff43634b 242cffff ffff
Side B incoming [154 bytes pending] [154 -> 40] 17030300 396b635a 28ffff13 ffffff5f 2472ff55 69ff7f01 3cffffff ff33ffff  ->  09000000 0100110e ffff0000 00000000 116065ff ffffff53 33330000 00000000
```

What's happening here is that when Side A sends three packets in sequence (two 62  byte payloads and a 30 byte payload) to the other side, which are combined as a single 154 byte chunk received. The issue here is that ```SSL_pending``` doesn't seem to do the right thing here. Afer Side B unpacks the first 62 bytes (into the 40byte  payload), SSL_pending returns zero, even though there are two more payloads to unpack at Side B. This chunking behavior seems to be random....

This may be an artifact of how I am  testing this (I created a BIO pair on both sides, SSL uses one for both read and write, and the application side uses the other for read/write), but without repeatedly calling `SSL_read` there seems to be no way to see whether there is stuff left to unpack.

Any help would be great.
Thank you.
-Jason

**Comment by mattcaswell** [comment]
Let's check what the docs say for `SSL_pending`:

````
SSL_pending() returns the number of bytes which have been processed, buffered and are available inside ssl for immediate read.
````
https://www.openssl.org/docs/man3.0/man3/SSL_pending.html

So this tells us about bytes that OpenSSL has already processed and buffered inside the SSL object. It tells us nothing about data that might be waiting at the "network" layer. You normally have to ask the network about this. In your case (for a BIO pair) you can use `BIO_pending()` for this.

**Comment by devzzzero** [comment]
Yep. That did it. Thank you.

**Comment by devzzzero** [comment]
closing.
