### ISSUE TITLE
Sever send a ECDSA cert with KU which doesn't have digitalSignature bit, It still connects successfully with TLS 1.3 but failed with TLS 1.2.

### ISSUE THREAD

**Issue by joece** [openssl/openssl#19263]
According to the RFC8446, Server must select a certificate which allow the key to be used for siging(i.e., the digitalSignature bit must be set if the KU is present). 
![image](https://user-images.githubusercontent.com/14805707/191719220-2ce622bb-81bc-45a8-aa3c-0f3408d2536d.png)

When there is only one cert with KU doesn't have digitalSignature bit, OpenSSL server still send it to client. (using 1.1.1n TLS 1.3)
Why do choose to continue sending instead of reporting an error?

Beside, in TLS 1.2 client can check the server cert then alert error, but TLS 1.3 doesn't check it and connect successfully.
TLS 1.2: tls_process_server_done ->tls_process_initial_server_flight->ssl3_check_cert_and_algorithm--->return error
TLS 1.3: tls_process_finished ->tls_process_initial_server_flight->ssl3_check_cert_and_algorithm --->return success
![image](https://user-images.githubusercontent.com/14805707/191737024-c67dbb78-8b65-4bb3-a98b-5fd2f78da350.png)

**Why is there such a difference? Was it based on any considerations?**

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev cycle barring further input

**Comment by t8m** [comment]
Duplicate of #12721
