### ISSUE TITLE
Support port unification

### ISSUE THREAD

**Issue by nuuman** [openssl/openssl#1926]
An increasing number of server supports regular traffic and SSL traffic on the same port (especially prevalent in the Java space)

This means, detect SSL hello packet, then move to SSL for that client.

Would this be hard to implement? I suppose you need to put the hello packet back on the "read queue" so that the ssl api starts with the hello packet.

Ideas?

**Comment by mattcaswell** [comment]
You should be able to try to create an SSL connection and then check the error queue for an SSL_R_HTTP_REQUEST error.

**Comment by mattcaswell** [comment]
Well....I suppose that assumes you are looking for HTTP....

**Comment by mattcaswell** [comment]
So, I guess the slightly fuller answer is, you might get one of the following errors:
SSL_R_HTTP_REQUEST: It looks like HTTP
SSL_R_HTTPS_PROXY_REQUEST: It looks like a proxy
SSL_R_WRONG_VERSION_NUMBER: Don't know what it is but it doesn't look like TLS

**Comment by nuuman** [comment]
No, not HTTP, plain TCP traffic

**Comment by richsalz** [comment]
No, you cannot tell.  This is an impossible thing to do.  If you see the first couple of bytes, especially if your application protocol is not known to openssl, how can you tell if it's a handshake or not?

Closing this.  We can't do it.

**Comment by nuuman** [comment]
Well, it *can* be done, since there are port unified SSL solutions out there (like grizzly)

The thing they do is detect the handshake signature, then move to SSL. If not, use normal protocol parsing.

Maybe not correct to put it inside openssl, but clearly, it *can* work.

**Comment by mattcaswell** [comment]
Perhaps peek into the received data prior to OpenSSL and look for a ClientHello signature, i.e. something like check the first 6 bytes are in this format: 0x16, 0x03, 0x??, 0x??, 0x??, 0x01

**Comment by nuuman** [comment]
@mattcaswell exactly
@richsalz so it's possible. Reopen?

**Comment by richsalz** [comment]
No.  How can OpenSSL tell, in a generic way, that the application protocol doesn't start with those first six bytes, especially since three of them *can be anything*?  It can't.  Suppose, for example, someone is doing "port unification" (which is really a horrible thing anyway, from a security viewpoint) of a packet dumper?

The only place to do this is in the application layer, which knows what it's initial packets look like.

**Comment by nuuman** [comment]
@richsalz It doesn have to tell, in a generic way. You provide an API to tell OpenSSL what.

> which is really a horrible thing anyway, from a security viewpoint

Unfounded claim. It's used increasingly, exactly because it's more secure. Fewer fw rules too.

**Comment by richsalz** [comment]
Okay, "in my opinion" if you prefer.

**Comment by nuuman** [comment]
OK :) So how about the hello packet I mentioned in the updated comment?

**Comment by richsalz** [comment]
I am strongly opposed and not re-opening.  Maybe someone else on the team disagrees.  Or you can write the code and make a PR for review.

**Comment by nuuman** [comment]
OK, that's cool. But I suppose there is some BIO-trickery I can use to start OpenSSL after my application has read the hello packet?
