### ISSUE TITLE
Missing null checking

### ISSUE THREAD

**Issue by ycaibb** [openssl/openssl#19279]
Hi, it seems that msg could be NULL, dereferencing in Line 104.

https://github.com/openssl/openssl/blob/af16097febcd4fa31cd5fcd05ad09cf8b53659ea/crypto/cmp/cmp_util.c#L103-L104

Other places with NULL check:

https://github.com/openssl/openssl/blob/af16097febcd4fa31cd5fcd05ad09cf8b53659ea/crypto/cmp/cmp_util.c#L49-L54

https://github.com/openssl/openssl/blob/af16097febcd4fa31cd5fcd05ad09cf8b53659ea/crypto/cmp/cmp_util.c#L89-L91

**Comment by t8m** [comment]
@DDvO might be interested?

**Comment by grahamwoodward** [comment]
https://github.com/openssl/openssl/pull/19282
