### ISSUE TITLE
How do I change the name of the compiled library when OpenSSL 3.0.x is compiled on the Android platform?

### ISSUE THREAD

**Issue by 18709226050** [openssl/openssl#19283]
OpenSSL 3.0.x compiles libcrypto.so and libssl.so by default. I hope that libcryptosc.so and libsssltsc.so can be changed to libcryptotsc.so and libssltsc.so.
libcrypto.so --》libcryptotsc.so
libssl.so--》libssltsc.so.

**Comment by levitte** [comment]
In other words, you can write a small config file of your own, say `Configurations/99-all-mine.conf`, with something like this:

``` perl
(
    'all-mine' => {
        # {something} should be replaced with the config target you want to derive from
        inherit_from => '{something}',
        shlib_variant => 'tsc',
    }
);
```

**Comment by 18709226050** [comment]
> In other words, you can write a small config file of your own, say `Configurations/99-all-mine.conf`, with something like this:
> 
> ```perl
> (
>     'all-mine' => {
>         # {something} should be replaced with the config target you want to derive from
>         inherit_from => '{something}',
>         shlib_variant => 'tsc',
>     }
> );
> ```

Thank you very much！
Add the following configuration to Configurations\15-android.conf:
![image](https://user-images.githubusercontent.com/77600386/192684799-f76650b5-2638-491c-8463-913838392ad3.png)
