### ISSUE TITLE
return value of `i2d_re_X509_REQ_tbs()`

### ISSUE THREAD

**Issue by no6v** [openssl/openssl#19297]
Hello,

I found that the return value of `i2d_re_X509_REQ_tbs()` was changed since 8e39049d38ebe8b8398d6c4aa8a6f7cef9712132. 
Currently it returns `0` on some errors or `1` unexpectedly. Manpage says:

```
i2d_re_X509_tbs(), i2d_re_X509_CRL_tbs() and i2d_re_X509_REQ_tbs() return the length of encoded data or 0 on error.
```

I guess the `NULL` check for `req` parameter is enough, then returns the result of `i2d_X509_REQ_INFO()` straightforward.

**Comment by t8m** [comment]
Fix in #19299

**Comment by t8m** [comment]
> I guess the `NULL` check for `req` parameter is enough, then returns the result of `i2d_X509_REQ_INFO()` straightforward.

Yeah, I see no point in setting the modified flag just after i2d call. @DDvO ?

**Comment by DDvO** [comment]
> > I guess the `NULL` check for `req` parameter is enough, then returns the result of `i2d_X509_REQ_INFO()` straightforward.
> 
> Yeah, I see no point in setting the modified flag just after i2d call. @DDvO ?

Ah, yes, sounds very plausible.

**Comment by DDvO** [comment]
> Currently it returns `0` on some errors or `1` unexpectedly. Manpage says:
> ... `return the length of encoded data or 0 on error.`

Sorry for my mistake.
BTW, this would not have happened if the type `bool` was supported and used in OpenSSL.

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Kha, 29 Sep 2022, 5:58 PM Nobuhiro IMAI ***@***.***>
menulis:
