### ISSUE TITLE
Is there a use for a native linux/aarch64 system in the OpenSSL CI?

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [openssl/openssl#19295]
In the discussion about [problems with OpenSSL v3.0.3 on Tandem NonStop](https://github.com/openssl/openssl/issues/18232), Matt Caswell [talked about adding a buildbot worker to the OpenSSL project CI](https://github.com/openssl/openssl/issues/18232#issuecomment-1117534938).

In exactly this vein, would it be useful to have a native linux/aarch64 system running within the OpenSSL CI?

We (Arm) have an Ampere Altra-based server which we can run in one of our data centres, and have it connect out to the OpenSSL CI system.

It would be able to do native linux/aarch64 OpenSSL builds, possibly allowing a reduction in load on the main CI
(of course, it might useful to still test cross-compiling for linux/aarch64 as it's done by a lot of people).

But it would certainly be significantly faster than qemu for running the tests, and running on hardware would likely
have been able to catch something like [issue 18813](https://github.com/openssl/openssl/issues/18813) before it got into the wild.

**Comment by mattcaswell** [comment]
> In exactly this vein, would it be useful to have a native linux/aarch64 system running within the OpenSSL CI?

Yes - this would definitely be useful.

> We (Arm) have an Ampere Altra-based server which we can run in one of our data centres, and have it connect out to the OpenSSL CI system.

Awesome! That sounds great.

Pinging @levitte who is our buildbot expert

**Comment by levitte** [comment]
Please email levitte@openssl.org and let's talk details.

**Comment by tom-cosgrove-arm** [comment]
> Please email [levitte@openssl.org](mailto:levitte@openssl.org) and let's talk details.

Hopefully you've received an email from me just now!

**Comment by tom-cosgrove-arm** [comment]
As I understand it this is now connected and functional, so closing this issue as completed.
