### ISSUE TITLE
Need a way to retrieve OpenSSL FIPS library version info

### ISSUE THREAD

**Issue by ashwanikadian** [openssl/openssl#19293]
We need a way to retrieve OpenSSL FIPS library version from the application. Please let us know if there is already an OpenSSL API or macro for the same or any other way to get to know the FIPS library version.

Also, does OpenSSL maintain different library version name for FIPS provider library (fips.so) and the libcrypt library?

**Comment by paulidale** [comment]
There are macros `OPENSSL_VERSION_STR` and `OPENSSL_FULL_VERSION_STR` which contain the OpenSSL version information.

The FIPS provider uses the former and this can be queries by getting the `version` provider parameter.

**Comment by mattcaswell** [comment]
To further elaborate on @paulidale's answer, see `OSSL_PROVIDER_get_params()`:

https://www.openssl.org/docs/man3.0/man3/OSSL_PROVIDER_get_params.html

Also see the "Provider parameters" section on this page:

https://www.openssl.org/docs/man3.0/man7/provider-base.html

**Comment by ashwanikadian** [comment]
Thanks Pauli and Matt for quick help. This helps.
