### ISSUE TITLE
About keccak256 introduction

### ISSUE THREAD

**Issue by somoza** [openssl/openssl#19304]
I noticed that keccak256 was introduced here: https://github.com/openssl/openssl/issues/13033

I'm wondering which version shall I use in order to have that algorithm available on my C++ compilation. 

It is on 1.1 or 3.0? 

I'm asking this because I'm getting "Digest type not supported in this cryptolib."

I've installed libcrypt-dev 1:4.4.18-4 and libssl-dev/ 1.1.1n-0

Thanks in advance.

**Comment by somoza** [comment]
Thanks for your reply, there is a approximated date for that release? Can I see the roadmap somewhere?

**Comment by mattcaswell** [comment]
There is no definitive date for it. Probably next year some time.

**Comment by slontis** [comment]
The only thing that made it into 3.0 was (KECCAK-KMAC-128/256) which is only useful for KMAC support.

**Comment by mattcaswell** [comment]
3.1 will be our next release (planned for next week). 3.2 will be coming "later this year".

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input

**Comment by t8m** [comment]
3.2 with Keccak256 was released
