### ISSUE TITLE
Load certificates for client

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#19306]
I am developing a client application that uses openssl for TLS communication. 
A third party tool is acting as  a server.
Now, if peer authentication(SSL_VERIFY_PEER) is not set at both server and client side, should my client application load its certificates?
My understanding was, we set certificates only if peer authentication is set or if we are a server.
Please correct me if my understanding is wrong.

Reagrds,
Amal

**Comment by t8m** [comment]
Yes, unless you are required to or want to authenticate the client to the server, you do not need to set the certificate on client.

**Comment by amaljesudas** [comment]
Thanks for confirming @t8m
