### ISSUE TITLE
SSL_CTX_new take 7 seconds

### ISSUE THREAD

**Issue by remainfox** [openssl/openssl#19305]
`Openssl Version`: 1.1.1g
`Device Info`: Mips platform, Embedded environment
`Problem Description`: SSL_CTX_new(DTLSv1_2_method()) need take 7 seconds,
In the system boot phase, the time starts to call SSL_CTX_new after about 3s, not sure whether it is related to the random number call
`OpenSSL Code`:
```c
STATUS createSslCtx(PDtlsSessionCertificateInfo pCertificates, UINT32 certCount, SSL_CTX** ppSslCtx)
{
    ENTERS();
    STATUS retStatus = STATUS_SUCCESS;
    SSL_CTX* pSslCtx = NULL;
    EC_KEY* pEcKey = NULL;
    UINT32 i;

    CHK(pCertificates != NULL && ppSslCtx != NULL, STATUS_NULL_ARG);
    CHK(certCount > 0, STATUS_INTERNAL_ERROR);

#if (OPENSSL_VERSION_NUMBER < 0x10002000L)
    EC_KEY* ecdh = NULL;
#endif

#if (OPENSSL_VERSION_NUMBER >= 0x10100000L)
    pSslCtx = SSL_CTX_new(DTLSv1_2_method());
#elif (OPENSSL_VERSION_NUMBER >= 0x10001000L)
    pSslCtx = SSL_CTX_new(DTLSv1_method());
#else
#error "Unsupported OpenSSL Version"
#endif

    CHK(pSslCtx != NULL, STATUS_SSL_CTX_CREATION_FAILED);

#if (OPENSSL_VERSION_NUMBER >= 0x10002000L)
    SSL_CTX_set_ecdh_auto(pSslCtx, TRUE);
#else
    CHK((ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1)) != NULL, STATUS_SSL_CTX_CREATION_FAILED);
    CHK(SSL_CTX_set_tmp_ecdh(pSslCtx, ecdh) == 1, STATUS_SSL_CTX_CREATION_FAILED);
#endif

    #if USE_DTLS_ENABLE_CERT_VERIFY
    SSL_CTX_set_verify(pSslCtx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT, dtlsCertificateVerifyCallback);
    #endif

    CHK(SSL_CTX_set_tlsext_use_srtp(pSslCtx, "SRTP_AES128_CM_SHA1_32:SRTP_AES128_CM_SHA1_80") == 0, STATUS_SSL_CTX_CREATION_FAILED);

    for (i = 0; i < certCount; i++) {
        CHK(SSL_CTX_use_certificate(pSslCtx, pCertificates[i].pCert) == 1, STATUS_SSL_CTX_CREATION_FAILED);
        // CHK(SSL_CTX_use_PrivateKey(pSslCtx, pCertificates[i].pKey) == 1 || SSL_CTX_check_private_key(pSslCtx) == 1, STATUS_SSL_CTX_CREATION_FAILED);
        CHK(SSL_CTX_use_PrivateKey(pSslCtx, pCertificates[i].pKey) == 1, STATUS_SSL_CTX_CREATION_FAILED);
    }
    
    CHK(SSL_CTX_set_cipher_list(pSslCtx, "ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256") == 1, STATUS_SSL_CTX_CREATION_FAILED);
    *ppSslCtx = pSslCtx;
    
CleanUp:
    if (STATUS_FAILED(retStatus) && pSslCtx != NULL) {
        SSL_CTX_free(pSslCtx);
    }

    if (pEcKey != NULL) {
        EC_KEY_free(pEcKey);
    }

    LEAVES();
    return retStatus;
}
```

**Comment by mattcaswell** [comment]
> In the system boot phase, the time starts to call SSL_CTX_new after about 3s, not sure whether it is related to the random number call

If you are doing this on an embedded device during boot, this is almost certainly because of a lack of entropy. The library will block until sufficient entropy is available.

**Comment by remainfox** [comment]
@mattcaswell `Thank you` for your answer, I would like to ask if there is any way to `avoid this situation`, such as `changing the blocking problem` by `setting parameters`, or older OpenSSL versions, etc

**Comment by bernd-edlinger** [comment]
Use a hardware random number generator device.

**Comment by paulidale** [comment]
It is possible to _fix_ the RNG wanting entropy but the draw back is that you lose **all** security.

**Comment by t8m** [comment]
You can also think about running some jitter RNG to feed the kernel RNG such as haveged although there are debates on the entropy quality from these RNGs.

**Comment by paulidale** [comment]
Don't use haveged, it lies about the amount of entropy it's collected.  CPU Jitter is better but I doubt either would be much use on a small embedded device.

**Comment by bernd-edlinger** [comment]
For true random numbers, you will need a hardware circuit,
something that uses metastability of flip-flop states, which is a quantum
effect that happens when the input signal violates the setup and hold
time of the flip-flop. See: https://en.wikipedia.org/wiki/Metastability_(electronics)
once the flip-flop enters the metastable state this state decays
with exponentially decreasing probability over time.
You need to test that circuit at very low temperatures and at very
high temperatures though, because the setup/hold timings
are temperature dependent.
Altera and Xilinx FPGAs have IP logic cores to create such devices.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
