### ISSUE TITLE
DES-CBC3-SHA using TLS 1.2

### ISSUE THREAD

**Issue by nmangerian** [openssl/openssl#19318]
A connection was made using DES-CBC3-SHA, which should only support TLS1.0 and 1.1, but this says it is using 1.2. 

Source: https://ciphersuite.info/cs/TLS_RSA_WITH_3DES_EDE_CBC_SHA/

Is this correct?

![image](https://user-images.githubusercontent.com/111443105/193346981-b8297a8e-6bf1-4c3d-afed-0fd02b4f634d.png)

**Comment by davidben** [comment]
No, that page is incorrect. TLS 1.2 imports all the cipher suites from TLS 1.0 and 1.1. (Although one hopes your client and server support better ciphers by now.)
