### ISSUE TITLE
Undefined symbol "RAND_egd" in file modules/ssl/.libs/libmod_ssl.a(ssl_engine_rand.o)

### ISSUE THREAD

**Issue by MoMuBud** [openssl/openssl#19316]
while trying to build the apache httpd 2.4.54 server (apr module version 1.6.1). It complains about the missing symbol when following compilation command fails:

httpd-2.4.54/srclib/apr/libtool --silent --mode=link gcc -std=gnu99    -m32    -L/var/opt/sun/xvm/uce/opt/server/lib   -o httpd  modules.lo buildmark.o -export-dynamic server/libmain.la  modules/aaa/libmod_authz_host.la modules/aaa/libmod_authz_core.la modules/cache/libmod_cache.la modules/cache/libmod_cache_disk.la modules/cache/libmod_socache_dbm.la modules/core/libmod_so.la modules/filters/libmod_reqtimeout.la modules/filters/libmod_filter.la modules/filters/libmod_deflate.la modules/http/libmod_http.la modules/http/libmod_mime.la modules/loggers/libmod_log_config.la modules/metadata/libmod_mime_magic.la modules/metadata/libmod_headers.la modules/metadata/libmod_setenvif.la modules/proxy/libmod_proxy.la modules/proxy/libmod_proxy_connect.la modules/proxy/libmod_proxy_ftp.la modules/proxy/libmod_proxy_http.la modules/proxy/libmod_proxy_fcgi.la modules/proxy/libmod_proxy_scgi.la modules/proxy/libmod_proxy_uwsgi.la modules/proxy/libmod_proxy_wstunnel.la modules/proxy/libmod_proxy_ajp.la modules/ssl/libmod_ssl.la modules/arch/unix/libmod_unixd.la modules/dav/main/libmod_dav.la modules/generators/libmod_autoindex.la modules/generators/libmod_cgi.la modules/dav/fs/libmod_dav_fs.la modules/sigvalidate/libmod_sigvalidate.la modules/mappers/libmod_dir.la modules/mappers/libmod_alias.la modules/mappers/libmod_rewrite.la  server/mpm/prefork/libprefork.la  os/unix/libos.la -L/var/opt/sun/xvm/uce/opt/server/lib -R/var/opt/sun/xvm/uce/opt/server/lib -lpcre          -lz                         /scratch/rmozes/apache_upgrade_2.4.54/httpd-2.4.54/srclib/apr-util/libaprutil-1.la -lexpat /scratch/rmozes/apache_upgrade_2.4.54/httpd-2.4.54/srclib/apr/libapr-1.la -luuid -lsendfile -lrt -lpthread -lsocket -lnsl
Undefined                       first referenced
 symbol                             in file
RAND_egd                            modules/ssl/.libs/libmod_ssl.a(ssl_engine_rand.o)
ld: fatal: symbol referencing errors. No output written to .libs/httpd

I indeed couldn't find the symbol:
nm -gDC /var/opt/sun/xvm/uce/opt/server/lib/libssl.so | grep RAND_egd 

OS: solaris 10 x86 machine (Oracle Solaris 10 1/13 s10x_u11wos_24a X86)
SSL: bash-3.2$ /var/opt/sun/xvm/uce/opt/server/bin/openssl
OpenSSL> version
OpenSSL 1.1.1o  3 May 2022

[configdata.pm.txt](https://github.com/openssl/openssl/files/9685338/configdata.pm.txt)

**Comment by mattcaswell** [comment]
> I indeed couldn't find the symbol:
nm -gDC /var/opt/sun/xvm/uce/opt/server/lib/libssl.so | grep RAND_egd

Note that this is a libcrypto symbol not libssl - so I would not expect the above command to find it.

**Comment by MoMuBud** [comment]
bash-3.2$ nm -gDC /var/opt/sun/xvm/uce/opt/server/lib/libcrypto.so | grep RAND_egd
same result with libcrypto.so . not found

**Comment by MoMuBud** [comment]
I see the exact same issue when compiling with openssl-1.1.1q

**Comment by MoMuBud** [comment]
openssl was compiled with:
./Configure solaris-x86-gcc shared threads 386 no-ssl3 --prefix=/var/opt/sun/xvm/uce/opt/server --openssldir=/var/opt/sun/xvm/uce/opt/server
CNF_CFLAGS=-pthreads -Wa,--noexecstack
CNF_EX_LIBS=-lsocket -lnsl -ldl -pthreads -lrt

**Comment by MoMuBud** [comment]
Please see also https://bz.apache.org/bugzilla/show_bug.cgi?id=66297 
So far this looks to me like an openssl bug

**Comment by mattcaswell** [comment]
> ./Configure solaris-x86-gcc shared threads 386 no-ssl3 --prefix=/var/opt/sun/xvm/uce/opt/server --openssldir=/var/opt/sun/xvm/uce/opt/server

EGD support is disabled by default, and this Configure line does not enable it. What is in your "openssconf.h" header file? I would expect to see lines like this:

```` C
#ifndef OPENSSL_NO_EGD
# define OPENSSL_NO_EGD
#endif
````
If the above lines are present then OpenSSL is declaring that EGD support is disabled. The openssl/rand.h header file contains these lines:

```` C
# ifndef OPENSSL_NO_EGD
int RAND_query_egd_bytes(const char *path, unsigned char *buf, int bytes);
int RAND_egd(const char *path);
int RAND_egd_bytes(const char *path, int bytes);
# endif
````
So the declaration of `RAND_egd` is hidden in the event that `OPENSSL_NO_EGD` has been defined in opensslconf.h as I would expect.

**Comment by levitte** [comment]
> openssl was compiled with: ./Configure solaris-x86-gcc shared threads 386 no-ssl3 --prefix=/var/opt/sun/xvm/uce/opt/server --openssldir=/var/opt/sun/xvm/uce/opt/server

You need to add `enable-egd` in there

**Comment by MoMuBud** [comment]
@mattcaswell my files look the same as you mentioned 

in (my) opensslconf.h file I see the same  
#ifndef OPENSSL_NO_EGD
# define OPENSSL_NO_EGD
#endif

and rand.h contains the same lines 
# ifndef OPENSSL_NO_EGD
int RAND_query_egd_bytes(const char *path, unsigned char *buf, int bytes);
int RAND_egd(const char *path);
int RAND_egd_bytes(const char *path, int bytes);
# endif

So if all is defined correctly how come the Apache compilation decided it should be enabled? Is it then a bug in their configure process? feel free to comment inside https://bz.apache.org/bugzilla/show_bug.cgi?id=66297 or I can link it to your answer here. 

Thanks!

**Comment by mattcaswell** [comment]
It seems likely to me that one of two things is happening:

1) A bug in the Apache build process is incorrectly detecting that EGD is enabled when it is not

or

2) There are 2 sets of OpenSSL headers being used somehow. One set of headers has EGD enabled and one set does not. The apache module is being built using a set of headers that show EGD as enabled, but it is ultimately linking against a library that does not have this support.

Either way this does not seem to be an OpenSSL issue.

**Comment by MoMuBud** [comment]
@mattcaswell thanks for confirming this
