### ISSUE TITLE
[WinCE 6.0] Executable does not work

### ISSUE THREAD

**Issue by mdeihly** [openssl/openssl#19337]
I have compiled successfully OpenSSL 1.1.1 on WinCE 6.0.
However, when I use an OpenSSL function on device of WinCE 6.0 OS, the executable does not start (libcrypto-1_1.dll and libssl-1_1.dll available).
I would like to know what would be the problem? Is it related to WinCE 6.0? Because also QtWebkit functions create the same issue (executable does not start).
Thanks

**Comment by FdaSilvaYY** [comment]
Check your binaries with https://dependencywalker.com

You may have a mismatch somewhere

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Sel, 4 Okt 2022, 4:11 AM mdeihly ***@***.***> menulis:
