### ISSUE TITLE
Possible deadlock in malloc error reporting

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#19334]
Due to the changes from 5639ee79bdc905c1b7ed308fcd29e515e4f01a50
there is now a possible dead-lock if a malloc failure occurs in OPENSSL_init_crypto here:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/init.c#L507
-> ossl_init base calls CRYPTO_THREAD_lock_new here:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/init.c#L64
-> CRYPTO_THREAD_lock_new calls OPENSSL_zalloc here: https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/threads_pthread.c#L50
-> which is a macro:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/include/openssl/crypto.h.in#L98-L99
-> CRYPTO_zalloc calls CRYPTO_malloc with non-zero file/line
 https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/mem.c#L216
-> which fails to malloc some memory, and calls ERR_new here:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/mem.c#L205
-> which calls ossl_err_get_state_int here:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/err/err_blocks.c#L20
-> which calls OPENSSL_init_crypto(OPENSSL_INIT_BASE_ONLY, NULL) here:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/err/err.c#L216
-> which will be blocked at this line:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/init.c#L507
... trying to call ossl_init_base again

**Comment by t8m** [comment]
Fix in #19335
