### ISSUE TITLE
Possible endless recursion in malloc error reporting

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#19331]
Due to the changes from 5639ee79bdc905c1b7ed308fcd29e515e4f01a50
there is now a possible endless recursion if malloc suddenly starts to fail here (in CRYPTO_malloc):
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/mem.c#L206
-> and then (in ERR_set_debug):
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/err/err_blocks.c#L37
-> and then (in err_set_debug):
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/err/err_local.h#L60-L66
-> which is a macro:
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/include/openssl/crypto.h.in#L110-L111
-> and then (in CRYPTO_strdup):
https://github.com/openssl/openssl/blob/fcae2ae4f675def607d338b7945b9af1dd9bb746/crypto/o_str.c#L27
-> so this will enter a loop now

**Comment by t8m** [comment]
Fix in #19332
