### ISSUE TITLE
Question about  SSL_CTX_free function

### ISSUE THREAD

**Issue by masmeta** [openssl/openssl#19333]
Hello,
I need a clarification that is not provided by the SSL_CTX_free documentation.
Are the memory areas allocated by the SSL_CTX overwritten after the SSL_CTX_free?
I would like to be sure that there is no more sensitive information allocated in memory such as passwords.

Please inform me if you need more details.

Best Regards,

**Comment by mattcaswell** [comment]
> Also, the application data actually written and received over a TLS connection isn't erased in this way

...unless you are using the `SSL_OP_CLEANSE_PLAINTEXT ` option.
