### ISSUE TITLE
test_async causes system hang on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by RJPercival** [openssl/openssl#1934]
After checking out master (27a451e3739d8331b9c180b0373b88ab6c382409), I run `make test` and my system consistently hangs a few seconds into executing test_async. A hard reboot is required to recover.

Configuration options (from configdata.pm): "--debug --strict-warnings enable-asan enable-crypto-mdebug -Wa,--noexecstack no-crypto-mdebug-backtrace no-ec_nistp_64_gcc_128 no-egd no-external-tests no-fuzz-afl no-fuzz-libfuzzer no-heartbeats no-md2 no-msan no-rc5 no-sctp no-ssl-trace no-ssl3 no-ssl3-method no-tls1_3 no-ubsan no-unit-test no-weak-ssl-ciphers no-zlib no-zlib-dynamic"

**Comment by RJPercival** [comment]
I'm still experiencing this issue with the master branch.

**Comment by mattcaswell** [comment]
Sounds like a kernel bug if you need to hard reboot.

**Comment by mattcaswell** [comment]
Assumed to be a kernel bug. No further reports. Closing.
