### ISSUE TITLE
Unsafe use of memcpy() in EVP_enc_null()

### ISSUE THREAD

**Issue by abigailam2000** [openssl/openssl#1935]
The memcpy() routine is explicitly not safe if the source and destination buffers overlap. This can happen when the EVP_enc_null() cipher is used to decrypt longer text than BUF_OFFSET bytes because of this code in bio_enc.c:
EVP_CipherUpdate(&(ctx->cipher),
                             (unsigned char *)ctx->buf, &ctx->buf_len,
                             (unsigned char *)&(ctx->buf[BUF_OFFSET]), i);
It's the overwrite of the ctx->buf memory that is the problem.
Saw this on a SUSE 12 SP2 machine. It is not necessarily repeatable on other machines. Valgrind also complained.

**Comment by levitte** [comment]
Could you please tell us what OpenSSL version you're looking at?

**Comment by abigailam2000** [comment]
1.0.2d

**Comment by mattcaswell** [comment]
Looks like this has been fixed in master and 1.1.0 (e.g. see c1a7dcbe16). Fix is too complex for backport so I think we close this.
