### ISSUE TITLE
OSSL_PROVIDER_load(NULL, "legacy") failes to load + windows 10

### ISSUE THREAD

**Issue by Praveer1981** [openssl/openssl#19368]
Hi,
I built openssl on Windows 10:  Below are the commands:
>  perl Configure VC-WIN32 enable-fips --prefix=C:\OpenSSL\3.0.5-source\3.0.5-output\lib\x86\release --openssldir=C:\OpenSSL\3.0.5-source\3.0.5-output\ssl no-shared & nmake & nmake test & nmake install_sw

I shared the library with my colleague and he says that 
OSSL_PROVIDER_load(NULL, "fips"); & OSSL_PROVIDER_load(NULL, "legacy"); fails.
When I tested on my machine I found that `OSSL_PROVIDER_load(NULL, "legacy")` works.  The reason `OSSL_PROVIDER_load(NULL, "fips")` fails due to not having the fips.lib
Below is my code snippet.

```

#include <iostream>


#include <openssl/provider.h>

#include <openssl/err.h>
#include <openssl/rand.h>
#include <openssl/rc4.h>
#include <openssl/evp.h>
#include <openssl/aes.h>
#include <openssl/provider.h>
#include <openssl/crypto.h>

#include <openssl/param_build.h>
#include <openssl/core_names.h>
#include<tchar.h>
#include <openssl/dh.h>

#pragma comment(lib, "crypt32")
#pragma comment(lib, "ws2_32.lib")

int main()
{
	OSSL_PROVIDER *fipsProvider = NULL;
	OSSL_PROVIDER *legacyProvider = NULL;
	OSSL_PROVIDER *defaultProvider = NULL;

	fipsProvider = OSSL_PROVIDER_load(NULL, "fips");
	if (fipsProvider == NULL)
	{
		std::cout << "FIPS provider load failed\n";
	}
	else
	{
		std::cout << "FIPS provider is loaded\n";
	}
	legacyProvider = OSSL_PROVIDER_load(NULL, "legacy");
	if (legacyProvider == NULL)
	{
		std::cout << "legacy Provider loading failed \n";
	}
	else
	{
		std::cout << "legacy Provider is loaded\n";
	}

	defaultProvider = OSSL_PROVIDER_load(NULL, "default");

	if (defaultProvider == NULL)
	{
		std::cout << "default Provider loading failed \n";
	}
	else
	{
		std::cout << "default Provider is loaded\n";
	}

    std::cout << "Hello World!\n";
}
```
Q1 : it is expected not to have fips.lib when I build by passing `no-shared` flag ? If so then
[release1.zip](https://github.com/openssl/openssl/files/9745696/release1.zip)
 how can I make it work ?
Q2 :  why does `OSSL_PROVIDER_load(NULL, "legacy");` function fails in my colleauges machine when we use the exactly same code?

I have attached the built library 
**Note: I have removed the .pdb file to reduce the folder size** 
**Used VS2017 to build**

**Comment by paulidale** [comment]
A1: Yes, it is expected.  The FIPS provider is **only** available as a shared library.  By specifying `no-shared` you completely disable this functionality.

A2: I'm not sure.  In a `no-shared` build, legacy is internal to libcrypto and should always be found.  Is there a chance your colleague is somehow picking up a different build of OpenSSL?

**Comment by Praveer1981** [comment]
@paulidale Thanks : 
https://github.com/openssl/openssl/blob/master/test/recipes/90-test_fipsload.t#L20 , I can see it will skip all if it is not shared library.
I copied the same library in my other laptop and found that `OSSL_PROVIDER_load(NULL, "legacy");` failed.
I have already attached the library `release1.zip`. It is possible for you to verify this from your end?

**Comment by Praveer1981** [comment]
@t8m Could you please help me with this? I generated the library without passing `no-shared`
but still, my sample program does not work.   
Below is my command:
> perl Configure VC-WIN32 enable-fips --prefix=C:\OpenSSL\openssl-openssl-3.0.5.tar\openssl-openssl-3.0.5\OP\release --openssldir=C:\OpenSSL\openssl-openssl-3.0.5.tar\openssl-openssl-3.0.5\OP\ssl no-shared & nmake & nmake test & nmake install_sw

does it depend on any config file?

**Comment by levitte** [comment]
> A1: Yes, it is expected. The FIPS provider is **only** available as a shared library. By specifying `no-shared` you completely disable this functionality.
>
> A2: I'm not sure. In a `no-shared` build, legacy is internal to libcrypto and should always be found. Is there a chance your colleague is somehow picking up a different build of OpenSSL?

This is *incorrect*.  `no-shared` affects the building of `libcrypto*.dll` and `libssl*.dll`, not *dynamically loadable **modules*** (which are governed by the configuration option `no-module` / `enable-module`, which is enabled by default).

This is shown by the attached `release1.zip`, which does indeed contain `release1/lib/ossl-modules/legacy.dll`

However, the question is where that dll (the legacy provider module) is located when running the program.  The environment variable `OPENSSL_MODULES` can dictate where to find it, otherwise it's found in whatever directories Windows normally look (I believe that the same directory as the loading program is a possibility, but am unsure).

**Comment by Praveer1981** [comment]
@levitte  Thanks for your valuable input. 
We copied `legacy.dll` file to the working directory but still got the same error ` error:12800067:DSO support routines::could not load the shared library`
just curious, is there anything I am missing?

**Comment by Praveer1981** [comment]
@levitte  Exactly, this is what I am trying to achieve and have fallen into trouble with: 
https://stackoverflow.com/questions/71861980/completing-the-installation-of-the-openssl-3-0-2-fips-module
what could be the best solution for it?

**Comment by levitte** [comment]
Please use `ERR_print_errors_fp(stderr)` or another of the ERR printing functions to get all the data out of the error queue.  There may be more details there that explain things a little better

**Comment by Praveer1981** [comment]
@levitte Thanks for your prompt response. I will do it and share the details with you

**Comment by Praveer1981** [comment]
@levitte  I added the below **code** to trace the error
```
legacyProvider = OSSL_PROVIDER_load(NULL, "legacy");	
	if (legacyProvider == NULL)
	{
		**int err = ERR_get_error();
		char buf[256];
		ERR_error_string_n(err, buf, sizeof(buf));
		std::cout << buf << '\n';**
		std::cout << "legacy Provider loading failed \n";
	}
```
Here is the error _error:12800067:DSO support routines::could not load the shared library_

**Comment by levitte** [comment]
> @levitte I added the below **code** to trace the error
> 
> ```
> legacyProvider = OSSL_PROVIDER_load(NULL, "legacy");	
> 	if (legacyProvider == NULL)
> 	{
> 		**int err = ERR_get_error();
> 		char buf[256];
> 		ERR_error_string_n(err, buf, sizeof(buf));
> 		std::cout << buf << '\n';**
> 		std::cout << "legacy Provider loading failed \n";
> 	}
> ```
> 
> Here is the error _error:12800067:DSO support routines::could not load the shared library_

Not good enough, i'm afraid.  You may have multiple error records queued for the same error, you're only printing one of them.
But ok, I understand that you're using C++ and prefer not to use stdout / stderr, so how about this:

``` C++
extern "C" {
static int err_print_line(const char *str, size_t len, void *u)
{
    std::cout << str << '\n';
}
}

// .....

	legacyProvider = OSSL_PROVIDER_load(NULL, "legacy");
        if (legacyProvider == NULL)
	{
		ERR_print_error_cb(err_print_line, NULL);
		std::cout << "legacy Provider loading failed \n";
	}
```

**Comment by Praveer1981** [comment]
@levitte  it looks like `err_print_line` callback function returns a number, For the reference I as trying to understand how does it work in the test.
https://github.com/openssl/openssl/blob/master/test/testutil/tests.c#L185
https://github.com/openssl/openssl/blob/master/test/testutil/cb.c#L15
looking at the above to files it looks like it has it it's own way to compute the return value- as the code is written by you so it would be more clearer to you :)
However, I just returned 1 from the callback function and this is the call stack got:

```
FIPS provider load failed
F83D0000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\OpenSSL\3.0.5-source\3.0.5-output\lib\x86\release\lib\ossl-modules\fips.dll)
F83D0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:152:
F83D0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:920:name=fips
F83D0000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\OpenSSL\3.0.5-source\3.0.5-output\lib\x86\release\lib\ossl-modules\legacy.dll)
F83D0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:152:
F83D0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:920:name=legacy
legacy Provider loading failed
default Provider is loaded
Hello World!
```

**Comment by Praveer1981** [comment]
Hi @levitte  Help me on this.

**Comment by sfhacker** [comment]
We don't understand the issue reported here!
We have built OpenSSL from source on Windows 10 x64. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/195756135-6c3ef3e6-d53f-49c8-b999-656cada57c18.png)

**Comment by levitte** [comment]
This line was the missing detail:

```
F83D0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:920:name=legacy
```

This indicates that the dll was actually loaded, but that the call of its init function failed. 
That's a bit of a surprise. 

Now, a question: you built OpenSSL with the config target `VC-WIN32`, did your colleague use the same or did they use something else, like `VC-WIN64A`?

**Comment by Praveer1981** [comment]
> We don't understand the issue reported here! We have built OpenSSL from source on Windows 10 x64. No issues at all.
> 
> ![image](https://user-images.githubusercontent.com/25817529/195756135-6c3ef3e6-d53f-49c8-b999-656cada57c18.png)
@sfackler 
Might be you did not read the complete detail. I never mentioned that there is any problem with building the library. I said that when we use the library on another machine `legacy provider`  load fails. so the question is why it fails? does it mean that we can not reuse openssl library?

**Comment by Praveer1981** [comment]
> This line was the missing detail:
> 
> ```
> F83D0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:920:name=legacy
> ```
> 
> This indicates that the dll was actually loaded, but that the call of its init function failed. That's a bit of a surprise.
> 
> Now, a question: you built OpenSSL with the config target `VC-WIN32`, did your colleague use the same or did they use something else, like `VC-WIN64A`?

@levitte  Thanks for your response. we used the exactly same library. even I copied the same library on my other laptop and used the exact same test code to verify and got the same error.

**Comment by paulidale** [comment]
If you want priority responses: take out a [support contract](https://www.openssl.org/support/contracts.html).

**Comment by levitte** [comment]
> This line was the missing detail:
> 
> ```
> F83D0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:920:name=legacy
> ```
> 
> This indicates that the dll was actually loaded, but that the call of its init function failed. That's a bit of a surprise.
> 
> Now, a question: you built OpenSSL with the config target `VC-WIN32`, did your colleague use the same or did they use something else, like `VC-WIN64A`?

This was a false path...  it turns out that our code tries to call the init function even though loading the dll itself fails (??????)

A quick experiment was to extract your release1.zip and simply try the openssl.exe that's in there, like this (with release1.zip unpacked in `Documents\\release1`:

``` console
C:\\Users\\throwaway> cd Documents\\release1\\release1
C:\\Users\\throwaway\\Documents\\release1\\release1> bin\\openssl.exe -provider legacy -providers
list: unable to load provider legacy
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
18030000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\OpenSSL\3.0.5-source\3.0.5-output\lib\x86\release\lib\ossl-modules\legacy.dll)
18030000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:152:
18030000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:920:name=legacy
```

The path `C:\OpenSSL\3.0.5-source\3.0.5-output\lib\x86\release\lib\ossl-modules\legacy.dll` is obviously *your installation path*, which gets built into your `libcrypto.lib`.  I assume that, just like me, your colleague placed `legacy.dll` elsewhere, i.e. in a location that `libcryto.lib` doesn't know about, and that explains why the load fails.

However, there's a trick, which the command line already hinted at; setting the environment variable `OPENSSL_MODULES` tells `libcrypto.lib` an alternative place to look, in runtime.  Here's how I set it in my environment (I do it with a relative path, which only works when running from that specific directory, of course):

``` console
C:\\Users\\throwaway\\Documents\\release1\\release1> set OPENSSL_MODULES=lib\\ossl-modules
C:\\Users\\throwaway\\Documents\\release1\\release1> bin\\openssl.exe -provider legacy -providers
Providers:
  legacy
    name: OpenSSL Legacy Provider
    version: 3.0.5
    status: active
```

So, your colleague must either have *exactly* the same directory tree as you do (or at least create `C:\OpenSSL\3.0.5-source\3.0.5-output\lib\x86\release\lib\ossl-modules\` and place `legacy.dll` there), or set the environment variable `OPENSSL_MODULE` to the directory where they placed `legacy.dll` on their system.

**Comment by levitte** [comment]
NOTE: `OPENSSL_MODULES` is mentioned in the documentation for `OSSL_PROVIDER_load()`.  From [OSSL_PROVIDER_load(3)](https://www.openssl.org/docs/man3.0/man3/OSSL_PROVIDER_load.html) (bold mine, for emphasis):

> OSSL_PROVIDER_load() loads and initializes a provider. This may simply initialize a provider that was previously added with OSSL_PROVIDER_add_builtin() and run its given initialization function, or load a provider module with the given name and run its provider entry point, `OSSL_provider_init`. The _name_ can be a path to a provider module, in that case the provider name as returned by OSSL_PROVIDER_get0_name() will be the path. Interpretation of relative paths is platform dependent and they are relative to the configured "MODULESDIR" directory **or the path set in the environment variable OPENSSL_MODULES if set**.

**Comment by Praveer1981** [comment]
@levitte  I highly appreciate your help, guidance, and kind words. Many thanks for the help!
Let me try this

**Comment by Praveer1981** [comment]
@levitte  strange: the same command does not work for me :
![image](https://user-images.githubusercontent.com/24364597/196111251-11d39042-7b55-4743-b38b-53e31518551b.png)

**Comment by levitte** [comment]
> @levitte strange: the same command does not work for me : ![image](https://user-images.githubusercontent.com/24364597/196111251-11d39042-7b55-4743-b38b-53e31518551b.png)

That's because I pasted incorrectly, sorry about that.  Try this:

``` console
bin\openssl.exe list -provider legacy -providers
```

**Comment by levitte** [comment]
I'm curious why the "could not load the shared library" line doesn't display the file name that it failed to load...

**Comment by Praveer1981** [comment]
> I'm curious why the "could not load the shared library" line doesn't display the file name that it failed to load...

Yes, right, But, it does show the line number which might have thrown an error(File name - provider_core.c)

**Comment by levitte** [comment]
> > I'm curious why the "could not load the shared library" line doesn't display the file name that it failed to load...
> 
> Yes, right, But, it does show the line number which might have thrown an error(File name - provider_core.c)

No, the name of the file it tried to load.  From my example:

`18030000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\OpenSSL\3.0.5-source\3.0.5-output\lib\x86\release\lib\ossl-modules\legacy.dll)`

**Comment by Praveer1981** [comment]
> 

@levitte  Richard, in this case it looks like it had loaded the legacy.dll. but seems somehow it did not load the fips.dll. do let me know if my understanding is wrong.

**Comment by levitte** [comment]
Do you have `fips.dll` in the same location as `legacy.dll`?  Do you have that location in the environment variable `OPENSSL_MODULES`?

**Comment by levitte** [comment]
A run of `openssl list`, using only the files from `openssl-bin-New.zip`:

![openssl-bin-New](https://user-images.githubusercontent.com/698918/196184618-fe0043c9-eacc-4e69-9866-646891b61265.png)

Note that the last set of errors is expected, because proper configuration is missing.
The following files from the directory you configured with `--openssldir` should be included: `openssl.cnf` and `fipsmodule.cnf`.  `openssl.cnf` also need a bit of tweaking to be useful for the FIPS provider.  You might want to read [fips_module(7)](https://www.openssl.org/docs/man3.0/man7/fips_module.html)

**Comment by Praveer1981** [comment]
> Do you have `fips.dll` in the same location as `legacy.dll`? Do you have that location in the environment variable `OPENSSL_MODULES`?

@levitte  Yes, I do have fips.dll and I also set the path in the environment variable

**Comment by Praveer1981** [comment]
> 

@levitte  Thanks for your response, took some time to analyze. I did some more research on it and loaded `openssl.cnf` using OSSL_LIB_CTX_load_config() function , also I updated this config file in such a way that it can include `fipsmodule.cnf` file and  I also set fips =fips_sect
No good luck yet, still have the same error.
![image](https://user-images.githubusercontent.com/24364597/196688395-7a7ff103-90e8-4fa5-ac49-a0379af6db4a.png)

**Comment by levitte** [comment]
>  No good luck yet, still have the same error.

Do you mind showing it?  As you can see in my latest example, the error looks different if it couldn't load fips.dll and if it could but the init function failed.

**Comment by Praveer1981** [comment]
> > No good luck yet, still have the same error.
> 
> Do you mind showing it? As you can see in my latest example, the error looks different if it couldn't load fips.dll and if it could but the init function failed.
@levitte 
```
OSSL_PROVIDER *fipsProvider = NULL;
	if (!OSSL_LIB_CTX_load_config(NULL, "C:\\openssl-bin\\ssl\\openssl.cnf"))
		return 1;

	EVP_default_properties_enable_fips(NULL, 1);
	bool is_fips_enabled = EVP_default_properties_enable_fips(NULL, 1);
	std::cout << " is_fips_enabled = " << is_fips_enabled << '\n';
	fipsProvider = OSSL_PROVIDER_load(NULL, "fips");
	if (fipsProvider == NULL)
	{
		int err = ERR_get_error();
		char buf[256];
		ERR_error_string_n(err, buf, sizeof(buf));
		ERR_print_errors_cb(err_print_line, NULL);
		std::cout << "FIPS provider load failed\n";
	}
	else
	{
		std::cout << "FIPS provider is loaded\n";
	}
```
![image](https://user-images.githubusercontent.com/24364597/196739511-7d82c31d-52fc-48d6-a9c6-254459fbb8cc.png)
![image](https://user-images.githubusercontent.com/24364597/196739778-0b013c6d-efa6-4cdf-a85f-92cb516f3a0a.png)

**Comment by Praveer1981** [comment]
@levitte Hi Richard,
any suggestions/guidance here?

**Comment by levitte** [comment]
Side note: remove this chunk of code:

``` C
		int err = ERR_get_error();
		char buf[256];
		ERR_error_string_n(err, buf, sizeof(buf));
```

That leaves *all* the errors in the error queue to `ERR_print_errors_cb()`, which will be more consistent.

I'll get back on the rest later.

**Comment by mattcaswell** [comment]
These latest errors seem to suggest that fips.dll was successfully loaded, but that a failure subsequently occurred in the module self test. My guess is that fipsmodule.cnf file is failing to load, or is somehow incorrect.

The forward slashes you have in your path to fipsmodule.cnf look suspicious to me:
C:/openssl-bin/ssl/fipsmodule.cnf
Shouldn't they be back slashes?

**Comment by Praveer1981** [comment]
@mattcaswell  No, it didn't work I don't think it is the path issue

**Comment by levitte** [comment]
> These latest errors seem to suggest that fips.dll was successfully loaded, but that a failure subsequently occurred in the module self test. My guess is that fipsmodule.cnf file is failing to load, or is somehow incorrect.
> 
> The forward slashes you have in your path to fipsmodule.cnf look suspicious to me:
> C:/openssl-bin/ssl/fipsmodule.cnf
> Shouldn't they be back slashes?

Windows C library is capable of understanding forward slashes the same way as backward slashes, so that shouldn't be a problem.  Where that matters, our code has fallbacks that understand Unix directory separators as well.  So, that should be OK...  I think.

**Comment by levitte** [comment]
> @mattcaswell No, it didn't work I don't think it is the path issue

In conf files, `\` is an escape character, so the next character will not be interpreted in any special way.  That means that any `\` must be doubled, like so: `\\`.  If you didn't do that, i.e. have this:

```
.include C:\openssl-bin\ssl\fipsmodule.cnf
```

... then it will be interpreted as if you had written this:

```
.include C:openssl-binsslfipsmodule.cnf
```

In other words, with backslashes that line must be this:

```
.include C:\\openssl-bin\\ssl\\fipsmodule.cnf
```

**Comment by Praveer1981** [comment]
@levitte  Thanks a lot, as you mentioned it was the path issue, now I am able to load the fips module. Thanks a lot for the help.
I see that fsmodule.cfg has a key called `module-mac` . is it the mac address of the machine where we build the OpenSSL library? if it is, then if I share this library with other developers and ask them to use it, then will the fips provider would load?
because the different machines will have different mac addresses.

**Comment by levitte** [comment]
The MAC is not a MAC address, it's a [Message Authentication Code](https://en.wikipedia.org/wiki/Message_authentication_code), and is used to check the integrity of fips.dll.
You can spread around fips.dll + fipsmodule.cnf as you see fit.  As long as they are together and are used in conjunction as shown with this exercise, it's going to be fine.

**Comment by Praveer1981** [comment]
@levitte Thanks a lot for the help. It works now.
