### ISSUE TITLE
Did WolfSSL violate OpenSSL License?

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#19376]
OpenSSL could not meet Some  Memory-sensitive required, and wolSSL will be used.
WolfSSL release openssl compatibility layer without OpenSSL License, Did this violate OpenSSL License? 
If APP used WolfSSL with openssl compatibility layer, Did this complaince  with OpenSSL License? 
https://github.com/wolfSSL/wolfssl/tree/master/wolfssl/openssl

**Comment by mspncp** [comment]
Am right that with "openssl compatibility layer" you mean the [wolfSSL FIPS provider for OpenSSL 3.0](https://www.wolfssl.com/openssl-3-0-provider-solution-fips-2)?

I don't know about any restrictions on third party OpenSSL providers. But this question is probably best to be answered by an @openssl/omc member.

**Comment by KanPlus** [comment]
> wolfSSL has a compatible API as drop-in replacement for a subset of the OpenSSL API
--wolfSSL has a compatible API as drop-in replacement for a subset of the OpenSSL API. For this.

**Comment by slontis** [comment]
The also have an engine variant so this is not something new..

**Comment by KanPlus** [comment]
> The also have an engine variant so this is not something new..

The "OpenSSL Compatibility Layer" in WolfSSL  have similar declaration with OpenSSL API, not the engine or provider for OpenSSL.

Refer:
_wolfSSL has multiple ways you can migrate from OpenSSL to wolfSSL
OpenSSL Compatibility Layer - The [wolfSSL](https://www.wolfssl.com/products/wolfssl/) OpenSSL compatibility layer is a means to switch applications designed for OpenSSL over to use wolfSSL. The compatibility layer is a series of commonly used and essential API that users can utilize to transition from OpenSSL to wolfSSL.
[wolfEngine](https://www.wolfssl.com/wolfcrypt-engine-openssl-5/) - wolfEngine is a FIPS-certified crypto module ([wolfCrypt](https://www.wolfssl.com/products/wolfcrypt-2/)) with OpenSSL as an OpenSSL engine.
wolfSSL Provider for OpenSSL - wolfSSL has developed an OpenSSL 3.0 provider, allowing you to use the latest version of OpenSSL backed by our FIPS-certified wolfCrypt library._
https://www.wolfssl.com/docs/wolfssl-openssl/

**Comment by paulidale** [comment]
Being API compatible wouldn't violate the licence IMO.  Of course I'm not a lawyer.
WolfSSL looks like they've reimplemented the API rather than just copying it.  Last time I looked, a lot of it was non-function -- i.e. always return an error.

**Comment by levitte** [comment]
Unless it's a straight copy of our header files or large portions thereof, there's no possible copyright infringement, and can therefore not be a license violation.

As far as I know, names aren't copyrightable...  or at least, that seems to be a common consensus in the open source / free software communities.  Even if they were, I don't see how our license doesn't allow using them.

I wouldn't worry about this...  in fact, I think this issue can be closed.

All this being said, IANAL

**Comment by KanPlus** [comment]
> 

Got it,Thanks
