### ISSUE TITLE
Heap corruption at RSA_generate_key_ex

### ISSUE THREAD

**Issue by darkn0xus** [openssl/openssl#19378]
Using OpenSSL version 3.0.0-alpha3-dev x86 build (static linking)
Visual Studio 2019 Windows OS

This is the code that produce the following issue in my application:
```
RSA* rsa = RSA_new();
BIGNUM* exp = BN_new();

BN_set_word(exp, RSA_F4);
RSA_generate_key_ex(rsa, bits, exp, NULL); // bits are set to 1024
return rsa;
```

And here is the call stack trace:
![Capture](https://user-images.githubusercontent.com/114424000/195031793-ca8906b3-1bbb-4526-9435-840e8667cf3c.PNG)

had a painful time to finally catch where the heap corruption occurs, yet not sure if it's 100% accurate.

**Comment by slontis** [comment]
It looks like you are using an alpha build of OpenSSL.. You might want to update to a more recent version. I am not seeing anything like this on master when running similar code thru valgrind.. You may also want to check for errors such as checking for NULL
