### ISSUE TITLE
3.0 version of EC_KEY_set_public_key_affine_coordinates

### ISSUE THREAD

**Issue by wintersteiger** [openssl/openssl#19387]
I'm in the process of upgrading to 3.0 and I found a set of deprecated functions for which it is not obvious how to replace them. I'm given a public key in x/y coordinates (32 bytes each for P-256) and I currently construct an `EVP_PKEY` from them in the following fashion:

```
EVP_PKEY* pkey = EVP_PKEY_new();
EC_KEY* ec_key = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
CHECK1(EC_KEY_set_public_key_affine_coordinates(ec_key, x, y));
CHECK1(EVP_PKEY_set1_EC_KEY(pkey, ec_key));
```

After trawling the documentation and the internet for hours, I kind of sort maybe believe that I am supposed to use `EVP_PKEY_fromdata` in 3.0, but I can't find any information on what a corresponding `OSSL_PARAM` would look like. Is the short answer perhaps that I'll be better off converting those points into PEM/DER myself to be able to load them into an `EVP_PKEY`?

**Comment by mattcaswell** [comment]
Unfortunately there is no easy way to supply the public key as separate x and y co-ords. (We should add that capability)

You need to use `EVP_PKEY_fromdata` and supply the param called `OSSL_PKEY_PARAM_PUB_KEY`. 

https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-EC.html

> "pub" (OSSL_PKEY_PARAM_PUB_KEY) <octet string>
The public key value in encoded EC point format. This parameter is used when importing or exporting the public key value with the EVP_PKEY_fromdata() and EVP_PKEY_todata() functions.

One way to convert the x and y co-ords into the required format is to create an `EC_POINT` using `EC_POINT_new` and `EC_POINT_set_affine_coordinates`. Then encode the public key into the required format using `EC_POINT_point2oct`

See the man page here:

https://www.openssl.org/docs/man3.0/man3/EC_POINT_set_affine_coordinates.html

Note that although the EC_KEY functions are deprecated, the EC_POINT functions are still ok to use - so this method is still fine for use in 3.0.

**Comment by wintersteiger** [comment]
Thanks for the quick reply! I agree, this is a bit roundabout, it would be nice if there would be better support to make this easier to use. 

I did get it working with your instructions, only the OSSL_PARAMs took a bit of time figuring out. I wondered whether another deserialization function like `d2i_PUBKEY` could be used instead of `EVP_PKEY_fromdata`, which could perhaps achieve the same in fewer lines of code.
