### ISSUE TITLE
Build OpenSSL 0-9-8 for WINCE 6.0

### ISSUE THREAD

**Issue by mdeihly** [openssl/openssl#19399]
I am using Visual Studio 2008 Command prompt to build OpenSSL 0-9-8 for WINCE 6.0.
I followed the instructions in the following page:
https://documentation.unified-automation.com/uasdkcpp/1.6.0/html/CompileOpenSSLCE.html

However, when calling: nmake -f ms\cedll.mak
I got the following errors:
![image](https://user-images.githubusercontent.com/41584417/195286610-3746aed7-671c-4292-b189-1f2789b8d2e2.png)

**Comment by t8m** [comment]
Unfortunately 0.9.8 version is unsupported for a long time.

**Comment by t8m** [comment]
> Could you please answer me for this issue:
> #19354

Unfortunately WinCE is currently unsupported platform. That's why help wanted is set on that issue to see if somebody from the community knows the answer.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
