### ISSUE TITLE
OpenSSL 1.1.1g FIPS Validation

### ISSUE THREAD

**Issue by vennemp** [openssl/openssl#19403]
For compliance, our stack relies heavily on OpenSSL.  Currently we are using OpenSSL 1.0.2k-fips  26 Jan 2017.  We are looking to upgrade to OpenSSL 1.1.1g FIPS 2020 Apr 21 for compliance reasons as it is the latest currently FIPS validated version of OpenSSL.  However we are unable to find a download for the source of this.  There is only 1.1.1g 2020 Apr 21, but not for FIPS. We compared SHA256 hashes and they are indeed different.  However, I was wondering if there was a specific FIPS build of 1.1.1.g that OpenSSL had validated by NIST.  Or did you just validate the 1.1.1g build as outlined in the NIST CMVP FIPS Certificate [#4271](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4271.pdf)

<img width="747" alt="Screen Shot 2022-10-12 at 10 57 17 AM" src="https://user-images.githubusercontent.com/26049891/195377612-61a257b5-181b-4b59-ba07-17a1b09779bf.png">

If it is the latter - if we just install the 1.1.1g build and run the OS in FIPS mode would this suffice?  My suspicion is that the hash difference between the "FIPS" and "non-FIPS" version is due to inconsequential differences (comments in code etc)

**Comment by mattcaswell** [comment]
> We are looking to upgrade to OpenSSL 1.1.1g FIPS 2020 Apr 21 for compliance reasons as it is the latest currently FIPS validated version of OpenSSL. 

This is not correct. The latest FIPS validated version of OpenSSL is OpenSSL 3.0.0 which can be downloaded from our website:

https://www.openssl.org/source/

See further details about it here:

https://www.openssl.org/docs/man3.0/man7/fips_module.html

OpenSSL 1.1.1g (or any version based on OpenSSL 1.1.1) has not been validated by the OpenSSL Project and will never be validated. For this reason you will find no information about such a validation on our website or downloaded validated source from us.

Third parties may have independently validated OpenSSL 1.1.1. In this case it seems that you are looking at details of the *RedHat* FIPS module. You would need to get details about that from RedHat.

**Comment by vennemp** [comment]
Ah good point! Thank you for pointing this out.
