### ISSUE TITLE
Failure on Mutual authentication for TLS on Windows using Openssl

### ISSUE THREAD

**Issue by BrunoC34** [openssl/openssl#19405]
Hello
We are trying to do Mutual authentication for TLS on Windows using Openssl.
On server side, we have syslog-ng with peer-verify enabled.
On client side, we are sending client certs using SSL_CTX_use_certificate_file() and SSL_CTX_use_PrivateKey_file().
When 
-	valid client cert is sent, SSLConnect() is success, but unable to receive data on TLS channel.
-	invalid certificate is sent, SSLConnect() should fail ideally but handshake is success.

Details:
We use HCERTSTORE to load the CA files and use SSL_CTX_use_certificate_file() and SSL_CTX_use_PrivateKey_file() to send the client certs.

Note :. We have the same feature enabled on Linux, but both the cases work as per expectation.

**Comment by mattcaswell** [comment]
> On server side, we have syslog-ng with peer-verify enabled.

Do you also set `SSL_VERIFY_FAIL_IF_NO_PEER_CERT`?

> valid client cert is sent, SSLConnect() is success, but unable to receive data on TLS channel.

What do you mean to "uanble to receive data on TLS channel"? What actually happens? Does the server side SSL_accept() also succeed? When you try and send data is it (apparently) sent successfully? If not do you get an error message? On the receive side do you get an error when you try and read?

**Comment by DDabbiru** [comment]
>>Do you also set `SSL_VERIFY_FAIL_IF_NO_PEER_CERT`?
>We don't use openssl on server side, we use syslog-ng application as our server. In syslog-ng conf, we have verify-peer(required-trusted) tag which fails the handshake.
Handshake is failing when invalid cert provided wen coded for Linux. Now we are developing it for windows and the handshake doesn't fail
>> What do you mean to "uanble to receive data on TLS channel"? What actually happens? Does the server side SSL_accept() also succeed? When you try and send data is it (apparently) sent successfully? If not do you get an error message? On the receive side do you get an error when you try and read?
>We only do client side development.so we didn't use SSL_accept() on server side as mentioned earlier.
What I was mentioning was, when good client cert is provided, SSLConnect() is successful but when we send data from client side on the established TLS channel, the messages are not received on server side.

My observation was, when we do mutual auth in windows using openssl , on client side , with both good and bad client certs,  SSLConnect() always succeeds. But when we send data from client side using TLS channel nothing is being received on the server side.

**Comment by DDabbiru** [comment]
This is the order we have follwed,
   /* set the local certificate from CertFile */
    if (SSL_CTX_use_certificate_file(
            ssl_ctx,
            (char *)_syslog_config.syslog_tls_client_config.certificate_path
                .c_str(),
            SSL_FILETYPE_PEM) <= 0) {
      authenticate_client = 0;
      _error_message = "Error with the given client certificate file";
      _error_occurred = true;
    }

    if (!_error_occurred) {
      /* set the private key from KeyFile (may be the same as CertFile) */
      if (SSL_CTX_use_PrivateKey_file(
              ssl_ctx,
              (char *)_syslog_config.syslog_tls_client_config
                  .certificate_private_key_path.c_str(),
              SSL_FILETYPE_PEM) <= 0) {
        authenticate_client = 0;
        _error_message = "Error with the given private key file";
        _error_occurred = true;
      }

      if (!_error_occurred) {
        /* verify private key */
        if (!SSL_CTX_check_private_key(ssl_ctx)) {
          authenticate_client = 0;
          _error_message =
              "Private key does not match the given client certificate";
        }
      }

Also, added certs to ssl store

 HCERTSTORE cert_store;
  PCCERT_CONTEXT cert_context = NULL;
  X509 *x509_cert;

  cert_store =
      CertOpenStore(CERT_STORE_PROV_SYSTEM_A, 0, 0,
                    CERT_SYSTEM_STORE_LOCAL_MACHINE | CERT_STORE_READONLY_FLAG,
                    (const void *)"ROOT");

  if (NULL != cert_store) {
    while ((cert_context =
                CertEnumCertificatesInStore(cert_store, cert_context))) {
      x509_cert =
          d2i_X509(NULL, (const unsigned char **)&cert_context->pbCertEncoded,
                   cert_context->cbCertEncoded);

      if (x509_cert) {
        if (!(X509_STORE_add_cert(ssl_store, x509_cert))) {
          _error_message = "Failed to add Certificate to openssl store";
        } else {
          retval = true;
        }

        X509_free(x509_cert);
      }
    }
    CertFreeCertificateContext(cert_context);
    CertCloseStore(cert_store, 0);

then, added the sslstore to to ssl_ctx below way:
 SSL_CTX_set_cert_store(ssl_ctx, ssl_store);
 SSL_CTX_set_verify(ssl_ctx, SSL_VERIFY_PEER, NULL);


then, did ssl connect manner.:

  _secure_socket = SSL_new(ssl_ctx);
      if (nullptr != _secure_socket) {
        BIO *bio = BIO_new_socket(_socket, BIO_NOCLOSE);
        SSL_set_bio(_secure_socket, bio, bio);
#ifdef WIN32
        RAND_screen();
#elif __unix__
        RAND_poll();
#endif
        SSL_set_connect_state(_secure_socket);
        int err = SSL_connect(_secure_socket);
        if (err == 1) {
          X509 *server_cert = SSL_get_peer_certificate(_secure_socket);
          if (nullptr != server_cert) {
            if (SSL_get_verify_result(_secure_socket) == X509_V_OK) {
              _connected = true;
              _connected_time = time(&current_time);
              if (_comm_channel_event_handler) {
                _comm_channel_event_handler->OnChannelConnected(
                    tiny_csplog_api::SecureEventKey::TLS_CONN_OK, "TLS");
              }
            }
}


Kindly review the code and please let us know if we have missed any step or configured incorrectly. Thanks in advance.

**Comment by mattcaswell** [comment]
Probably we need to see a pcap trace of the communication to try and figure out what is going wrong.

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input
