### ISSUE TITLE
APIs For Setting Security Level in library context libctx provided by OSSL_LIB_CTX()

### ISSUE THREAD

**Issue by vk18anubhav** [openssl/openssl#19434]
Openssl provides APIs for Setting Security Levels for SSL ctx and SSL object required by SSL/TLS functionality (https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_security_level.html)
_void SSL_CTX_set_security_level(SSL_CTX *ctx, int level);
void SSL_set_security_level(SSL *s, int level);_

Are there any similar APIs for Setting Security Levels for library context libctx provided by OSSL_LIB_CTX() if we are using only the cryptographic algorithms functionality.

**Comment by mattcaswell** [comment]
No. There is no equivalent functionality for `OSSL_LIB_CTX()`.

**Comment by vk18anubhav** [comment]
Hi Matt
Thanks for the response. Is there any way we can restrict usage of minimum key sizes in cryptographic functionalities as is done by different levels in SSL_CTX_set_security_level() for SSL/TLS

**Comment by vk18anubhav** [comment]
Is there any global property we can set during OpenSSL initialization or provider loading for security levels  ?

**Comment by t8m** [comment]
No, there is no such global setting or API call.
