### ISSUE TITLE
OpenSSL STATIC for WinCE

### ISSUE THREAD

**Issue by mdeihly** [openssl/openssl#19431]
I would like to ask if it is possible to build OpenSSL **Statically** for WINCE.
When I add **no-shared** it does not work the compilation process.

perl Configure no-idea no-mdc2 no-rc5 no-ssl3 no-weak-ssl-ciphers no-async no-engine no-shared  VC-CE
Then **nmake** fails

For DLL i used to call: nmake build_generated libcrypto-1_1.dll libssl-1_1.dll

Thanks

**Comment by t8m** [comment]
What's the failure reported?

**Comment by t8m** [comment]
If you do not need the openssl application but just the libraries, you can try `nmake build_libs`

**Comment by mdeihly** [comment]
> If you do not need the openssl application but just the libraries, you can try `nmake build_libs`

Thank you very much.
I 've successfully got 2 .lib STATIC
I got these warning, do they affect performance?
![image](https://user-images.githubusercontent.com/41584417/196641619-2196127f-b894-4e03-b561-45cbe2ccb333.png)


But unfortunately the .exe on WINCE 6.0 machine still does not work when i use OpenSSL function

**Comment by t8m** [comment]
> I got these warning, do they affect performance?

In case of the ecp object files this means the optimized ECC implementation for NIST curves is not being built. Possibly no assembler?
Others are not relevant.



> But unfortunately the .exe on WINCE 6.0 machine still does not work when i use OpenSSL function

What exe are you talking about? Some application using openssl? What "does not work" exactly means? Unfortunately we are no WINCE experts, I'd suggest trying to find some forum of WINCE developers to seek help.

**Comment by mdeihly** [comment]
> What exe are you talking about? Some application using openssl? What "does not work" exactly means? Unfortunately we are no WINCE experts, I'd suggest trying to find some forum of WINCE developers to seek help.

Yes, When I use OpenSSL function, the project on VS2005 BUILD successfully, however when i use .exe on WINCE 6.0 it does not show up. Then when I remove from code the OpenSSL function used, the app shows up. So strange.

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input
