### ISSUE TITLE
[HEADER-ONLY Library] OpenSSL

### ISSUE THREAD

**Issue by mdeihly** [openssl/openssl#19430]
I have problems using OpenSSL 1.1.1 on WINCE 6.0 machine even if the compilation process worked well and i got libcrypto-1_1.dll and libssl-1_1.dll.
I would like to ask you if it is possible to use OpenSSL as Header-Only library on WINCE 6.0 by including header files on project.
Thanks

**Comment by t8m** [comment]
I have no idea how would you want to use OpenSSL as header-only library. The existing headers do not contain much code there are mostly declarations.
