### ISSUE TITLE
Not compiling for Windws

### ISSUE THREAD

**Issue by JorgeCarousel** [openssl/openssl#19448]
Hi guys,

I'm trying to compile your 3.2-dev for Windows with enable-quic and when running nmake I get this:

ssl\quic\quic_rx_depack.c(241): error C2065: 'SHUT_WR': undeclared identifier
ssl\quic\quic_rx_depack.c(267): error C2065: 'SHUT_RD': undeclared identifier

And it stops building there, can you fix this to start testing again?

Thanks.

**Comment by mattcaswell** [comment]
Ping @levitte

**Comment by mattcaswell** [comment]
I wonder why we have not seen this in our CI builds?

**Comment by t8m** [comment]
Fix is in https://github.com/openssl/openssl/pull/19345 already.

**Comment by t8m** [comment]
> I wonder why we have not seen this in our CI builds?

Because we did not enable-quic for them.

**Comment by JorgeCarousel** [comment]
Thanks much.
