### ISSUE TITLE
how to compile libcrypto.so.1.0.2o

### ISSUE THREAD

**Issue by CHNVigny** [openssl/openssl#19451]
I tried to compile libcrypto.so.1.0.2o using openssl.1.0.2o with command: `config shared` but only got the dynamic lib libcrypto.so.1.0.0. what's the difference between libcrypto.so.1.0.2o and libcrypto.so.1.0.0 and how to get libcrypto.so.1.0.2o?

**Comment by paulidale** [comment]
OpenSSL is long out of support.

**Comment by levitte** [comment]
Generally speaking, the shared object version does not reflect the version of the project it was built from. Rather, if the shared object continues to have the same version, it's an indication that they have (or should have) a compatible ABI, so an upgrade of that shared object is possible without having to relink all applications that use it.

That's the general idea.

**Comment by CHNVigny** [comment]
> Generally speaking, the shared object version does not reflect the version of the project it was built from. Rather, if the shared object continues to have the same version, it's an indication that they have (or should have) a compatible ABI, so an upgrade of that shared object is possible without having to relink all applications that use it.
> 
> That's the general idea.

concise comment, thank you!
