### ISSUE TITLE
htobe32/htobe64

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#19468]
Do we have our primitives/defines implementing htobe32/htobe64? These functions look glibc-specific...

**Comment by t8m** [comment]
No, apart from using BN_native2bn and BN_bn2bin to convert. :grin:

**Comment by beldmit** [comment]
I've also found `be32` func in `kdf.c`

**Comment by paulidale** [comment]
For 32 bit: just use `htonl(3)`.

We do have `PUTU32` in `crypto/modes.h`?  It's ugly but should work.
For 64 bits, we don't define `PUTU64` but do define the helper `BSWAP8`, it would be straightforward to add `PUTU64` I think.
