### ISSUE TITLE
Memory leaks with shared windows builds

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#19466]
I've been helping maintain openssl & cryptography in the conda-forge ecosystem, and one of our biggest stumbling blocks in that regard has been upgrading to OpenSSL 3. In large part that's due to me not being confident enough to raise an issue because I didn't feel I understood the failures well enough at the time.

After sorting out most build errors, we've been stuck that the very thorough cryptography test suite notices memory leaks (only) on windows. At the time I opened https://github.com/pyca/cryptography/issues/7379, but upstream cryptography cannot really help with debugging this due to infrastructural reasons (they compile against a prepared static build, we need to build against shared libs).

Even more curiously (and another reason that kept me from opening this issue here) is that the failures only show up for CPython 3.7, 3.9 & 3.10, but _not_ for CPython 3.8 or PyPy 3.8, 3.9. This makes it look like some sort of interaction with the Python runtime is happening, but truth be told, I don't know. Maybe the memory leaks are always there and being hidden through other interferences?

In any case, I wanted to kindly ask for help as this state of affairs keeps us in an uncomfortable in-between-state - essentially we're halfway through a so-called "migration" across all our packages, currently building everything for 1.1.1 & 3.0.0, until the remaining packages (all dependents of cryptography) have finished moving to 3.0.0, and we can then drop the 1.1.1-flavoured builds.

The windows builds script that we're using is [here](https://github.com/conda-forge/openssl-feedstock/blob/main/recipe/bld.bat), config step reproduced here for convenience:
```
:: Configure step
perl configure VC-WIN64A          ^
    --prefix=%LIBRARY_PREFIX%     ^
    --openssldir=%LIBRARY_PREFIX% ^
    enable-legacy                 ^
    no-fips                       ^
    no-module                     ^
    no-zlib                       ^
    shared
```

The failures can then be seen in e.g. https://github.com/conda-forge/cryptography-feedstock/pull/106 (previously https://github.com/conda-forge/cryptography-feedstock/pull/80), with a corresponding CI run [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=593097&view=results) (please ignore the failures on linux-aarch64 & linux-ppc64le, those are unrelated cross-compilation woes on the Rust side).

The failures all point to a memory leak occurring at [`crypto/provider_core.c:1616`](https://github.com/openssl/openssl/blob/openssl-3.0.5/crypto/provider_core.c#L1616), though not all tests from [`cryptography/tests/hazmat/backends/test_openssl_memleak.py`](https://github.com/pyca/cryptography/blob/main/tests/hazmat/backends/test_openssl_memleak.py) are failing, only:
```
=========================== short test summary info ===========================
FAILED tests/hazmat/backends/test_openssl_memleak.py::TestOpenSSLMemoryLeaks::test_x509_csr_extensions
FAILED tests/hazmat/backends/test_openssl_memleak.py::TestOpenSSLMemoryLeaks::test_x25519_pubkey_from_private_key
FAILED tests/hazmat/backends/test_openssl_memleak.py::TestOpenSSLMemoryLeaks::test_load_pkcs12_key_and_certificates[pkcs12/cert-aes256cbc-no-key.p12]
FAILED tests/hazmat/backends/test_openssl_memleak.py::TestOpenSSLMemoryLeaks::test_load_pkcs12_key_and_certificates[pkcs12/cert-key-aes256cbc.p12]
FAILED tests/hazmat/backends/test_openssl_memleak.py::TestOpenSSLMemoryLeaks::test_write_pkcs12_key_and_certificates
= 5 failed, 2816 passed, 56 skipped, 296 warnings, 85319 subtests passed in 340.54s (0:05:40) =
``` 

Happy to provide further information (or test patches on our infra), but I've reached the end of the line here, and would be very grateful for some help. 😅

**Comment by mattcaswell** [comment]
I guess to make any progress here we're going to need some kind of way of easily reproducing the problem. Is there anyway to get a simplified reproducer?

**Comment by h-vetinari** [comment]
Thanks for the quick response!

> Is there anyway to get a simplified reproducer?

Not that I'm aware of, except that the description is simple: create shared OpenSSL build on windows, build cryptography against that, run test suite. For context, we're running the full OpenSSL test suite in the builds for OpenSSL (well, as full as the default builds are tested, c.f. https://github.com/openssl/openssl/issues/16580), and the problem only appeared in the cryptography test suite so far.

> I guess to make any progress here we're going to need some kind of way of easily reproducing the problem. 

One thing I could imagine is to rig up the cryptography tests in this repo to consume a shared library rather than a static one (all within a PR of course). Do you think that'd work?

**Comment by pkgw** [comment]
I haven't tried this myself, but if one installs Conda and `conda-build` on a Windows machine, checks out the [rebuild-openssl3-0-1_h679916 branch of the regro-cf-autotick-bot/cryptography-feedstock repo][1], and does a build of the form:

```
conda build -m .ci_support\win_64_openssl3python3.10.____cpythonpython_implcpython.yaml recipe
```

[1]: https://github.com/regro-cf-autotick-bot/cryptography-feedstock/tree/rebuild-openssl3-0-1_h679916

... that *should* run the Cryptography build with the test suite step that fails. Whether that counts as a "simplified" reproducer might be up for debate ...

**Comment by pkgw** [comment]
Also, correct me if I'm wrong @h-vetinari, but I think we're *pretty* sure that the issue has something to do with building OpenSSL as a shared library on Windows, because the [Cryptography] CI works on Windows and that seems to be the biggest difference between our setups, but I don't think we've confirmed that 100%.

Furthermore, there's a chance that the problem lies in the [Cryptography] layer rather than OpenSSL per se, if it's maybe cleaning things up incorrectly. Based on the results of the test suite, which shows a leak of *only* some provider's `operation_bits` pointer, I think there must be some provider that is allocated and eventually freed in `ossl_provider_free`, but never gets `flag_initialized` set?

Or maybe the test suite has a problem — it's detecting leaks with [an exciting memory tracker that works at the Python level][1]. I could see that maybe getting confused if a pointer address is reused or something.

[1]: https://github.com/pyca/cryptography/blob/main/tests/hazmat/backends/test_openssl_memleak.py#L61-L79

[Cryptography]: https://github.com/pyca/cryptography

**Comment by h-vetinari** [comment]
Thanks @pkgw 

> Whether that counts as a "simplified" reproducer might be up for debate ...

Well, it's definitely simpler, and it'd reproduce the problem, but it wouldn't be possible to run it against the master branch here (which is possible, but quite a bit more work).

**Comment by reaperhulk** [comment]
We've taken this as far as we're willing to go in that we can't reproduce it ourselves in our CI (potentially due to differences in linking, although I'm skeptical). I think debugging this requires a pure C reproducer to make further progress.

**Comment by h-vetinari** [comment]
> I think debugging this requires a pure C reproducer to make further progress.

I don't think I can realistically take one of the failing test cases and turn it into a C equivalent...

But what about the idea to switch the cryptography submodule here to base itself on a shared windows lib (for testing within a PR)? You tend to keep that submodule up-to-date, so I guess you'd know best whether that's feasible. At least that would circumvent the impossibility of doing this in cryptography CI (without having to publish windows shared builds from pyca/infra)

**Comment by pkgw** [comment]
Digging into this. Uh, far be it from me to try to poke holes in the OpenSSL code, but should https://github.com/openssl/openssl/blob/master/crypto/provider_core.c#L1211 be a write lock rather than a read lock?

**Comment by pkgw** [comment]
Beyond the above, I can reproduce on Windows, and instrument the memory leak test a bit. Here are some notes from what I'm finding (NB, I know ~nothing about OpenSSL).

I ran the tester for the shortest test we have that's failing, which looks like this:

```
from cryptography.hazmat.primitives.asymmetric import x25519
private_key = x25519.X25519PrivateKey.generate()
private_key.public_key()
```

Based on the allocation pattern I'm seeing, the relevant provider allocation pattern seems to be:

- Allocate a provider store
- Allocate a provider
- Set one of its operation_bits
- Allocate another provider
- Register some child callbacks
- Allocate a child provider store
- Allocate a (child?) provider
- Allocate another (child?) provider
- Set some operation_bits
- Begin actual Python test code
- Set operation_bits in two provides
- End actual Python test code
- Remove store methods
- Free two providers
- Free a provider store
- Free one provider
- Free a provider store

So it looks like there is some parent provider that is not being freed appropriately?

For posterity, here's the specific output from my instrumentation of the leak tester:

```
# format is: op, pointer, size, src-file, src-line (relative to 3.0.5 tarball)
MALLOC: 1896719119456 80 crypto\provider_core.c 310
MALLOC: 1896719862304 224 crypto\provider_core.c 459
MALLOC: 1896733348160 8 crypto\provider_core.c 473
REALLOC: 0 => 1896733348000 1 crypto\provider_core.c 1616
MALLOC: 1896733447056 224 crypto\provider_core.c 459
MALLOC: 1896733348512 7 crypto\provider_core.c 473
MALLOC: 1896734159328 40 crypto\provider_core.c 1723
MALLOC: 1896719117824 80 crypto\provider_core.c 310
FREE: 1896733348528 crypto\provider_core.c 1740
MALLOC: 1896733445376 224 crypto\provider_core.c 459
MALLOC: 1896733348528 8 crypto\provider_core.c 473
MALLOC: 1896733442736 224 crypto\provider_core.c 459
MALLOC: 1896733347616 7 crypto\provider_core.c 473
REALLOC: 0 => 1896729536784 1 crypto\provider_core.c 1616
BEFORE
REALLOC: 1896733348000 => 1896729536816 2 crypto\provider_core.c 1616
REALLOC: 1896729536784 => 1896729537392 2 crypto\provider_core.c 1616
REALLOC: 1896729536816 => 1896733147760 3 crypto\provider_core.c 1616
REALLOC: 1896729537392 => 1896733147808 3 crypto\provider_core.c 1616
AFTER
FREE: 1896733147808 crypto\provider_core.c 1209
FREE: 1896734159328 crypto\provider_core.c 1805
FREE: 1896733348528 crypto\provider_core.c 721
FREE: 1896733445376 crypto\provider_core.c 729
FREE: 1896733347616 crypto\provider_core.c 721
FREE: 1896733442736 crypto\provider_core.c 729
FREE: 1896719117824 crypto\provider_core.c 305
FREE: 1896733348512 crypto\provider_core.c 721
FREE: 1896733447056 crypto\provider_core.c 729
FREE: 1896719119456 crypto\provider_core.c 305
```

**Comment by t8m** [comment]
> Digging into this. Uh, far be it from me to try to poke holes in the OpenSSL code, but should https://github.com/openssl/openssl/blob/master/crypto/provider_core.c#L1211 be a write lock rather than a read lock?

Reported as #19474 19474

**Comment by alex** [comment]
@pkgw nice debugging! Agreed that this looks like a bug on our side.

Does anyone understand what initialization actually leads to the call to `ossl_provider_set_operation_bit`? I don't think we want to simply ignore re-alloced things, otherwise you run the risk of a leak via an inifinitely growing array. But if we can trigger this initialization early on, that should solve it.

**Comment by pkgw** [comment]
FWIW, since this seems to be more of an issue for the Cryptography test suite rather than a big in OpenSSL (and the potential locking issue was filed as a separate bug), I'd suggest closing this issue and continuing the discussion in pyca/cryptography#7379.

**Comment by h-vetinari** [comment]
AFAIU the cryptography folks are still [interested](https://github.com/pyca/cryptography/issues/7379#issuecomment-1287920449) how `ossl_provider_set_operation_bit` is initialized, but I think this issue has served its purpose.

Thanks everyone for helping _finally_ fix this. 🙃

**Comment by mattcaswell** [comment]
Nice detective work @pkgw!
