### ISSUE TITLE
there is no <openssl/configuration.h> file

### ISSUE THREAD

**Issue by fengmao31** [openssl/openssl#19462]
![image](https://user-images.githubusercontent.com/19343842/197097050-12c4319d-dfe0-4b9e-ae5e-ba6518ca131a.png)
![image](https://user-images.githubusercontent.com/19343842/197097111-e9bf9c0b-998b-4e82-aca3-dc68c35c7c06.png)

**Comment by levitte** [comment]
Did you run the configuration script?  (did you read INSTALL.md?)

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input
