### ISSUE TITLE
X509_NAME_oneline misses reference to OPENSSL_free to release (for buf==NULL)

### ISSUE THREAD

**Issue by grooverdan** [openssl/openssl#19476]
This seems supported in the code:
* [ref 1](https://github.com/openssl/openssl/blob/79c8dcf3985a7b75eac8e53eb8652728af6c5d3d/crypto/x509/x509_cmp.c#L47-L68)
* [ref 2](https://github.com/openssl/openssl/blob/a73bdc24e14760413a65d478d7c88356b4b95bb5/crypto/x509/x_name.c#L508-L512)
* [ref 3](https://github.com/openssl/openssl/blob/e1e93f7a07dfc7a8dddd4ddbb79d1d9bc9760d32/crypto/cmp/cmp_vfy.c#L157-L162)

**Comment by t8m** [comment]
The manpage says `If buf is NULL then a buffer is dynamically allocated and returned, and size is ignored.` Anything allocated by OpenSSL must be released by OPENSSL_free() or a specialized freeing function if it is some kind of structured object. So I am not sure what's missing there. But feel free to suggest any addition to the manual page through a pull request.

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input
