### ISSUE TITLE
compilation issue with 'no-shared' in 1.1.0c

### ISSUE THREAD

**Issue by frankreppin** [openssl/openssl#1948]
Dear all,

OpenSSL - i.e. 1.1.0b and earlier - used to produce working binaries here on FreeBSD 10-stable
by simply doing:

./config no-shared
make
./apps/openssl version
<expected output of openssl version>

This somehow doesn't work anymore with 1.1.0c - doing the same configures and compiles fine,
but the resulting binary doesn't work at all - it somehow simply 'hangs' (but can be terminated by ctrl+c).
Running it with 'truss' doesn't show something obvious - so I am at a loss on what could be wrong.

TIA,
frank\

**Comment by mattcaswell** [comment]
This is a known issue that has been fixed in commit f56c786. See issue #1899.
