### ISSUE TITLE
Openssl can't find libssl.so.1.1 and libcrypto.so.1.1

### ISSUE THREAD

**Issue by egl35720** [openssl/openssl#19497]
Hello to all,

when I try to launch openssl I get this error messages

```
$ openssl version
openssl: /lib64/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
openssl: /lib64/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by openssl)
openssl: /lib64/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
openssl: /lib64/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by openssl)
```

I tried the solution described in the Git topic below 

  `OPENSSL_1_1_1' not found (required by openssl) #5845

But it doesn't solved my issue.

My Linux distro is CentOS Linux release 7.9.2009 (Core)

Here is the value of LD_LIBRARY_PATH and the libraries in in /usr/local/lib

```
$ sudo export -p | grep -i ld_libr
declare -x LD_LIBRARY_PATH="/usr/local/lib"
$ cd /usr/local/lib
$ ls -l
total 0
lrwxrwxrwx 1 root root 13 29 août  11:20 libssl.so.1.0.0 -> libssl.so.1.1
$
```

Please can you help me ?

Thanks a lot

**Comment by levitte** [comment]
Oh!  This looks a bit mysterious:

> ```
> $ cd /usr/local/lib
> $ ls -l
> total 0
> lrwxrwxrwx 1 root root 13 29 août  11:20 libssl.so.1.0.0 -> libssl.so.1.1
> $
> ```

So there's a symbolic link "libssl.so.1.0.0" pointing at "libssl.so.1.1"....  which doesn't exist?

That's one answer why you're getting errors.

Did you build this OpenSSL installation yourself?

**Comment by egl35720** [comment]
Hello levitte,

thanks for your response.

> So there's a symbolic link "libssl.so.1.0.0" pointing at "libssl.so.1.1".... which doesn't exist?

I don't know why I didn't get it !!! May be because I was focused on the error message.

No I didn't installed openssl by myself. 
The virtual machine is a docker-engine installed by our dev team. I just have to renew a certificate and I want to check certificate attributes with openssl. When I launched it I've have got the error.
Today I'll try to work arround this symlik issue and post a new comment in this post.

**Comment by egl35720** [comment]
Great 👍 
Removing broken symlink => OK
Installing openssl11-libs => OK
```
$ sudo openssl version
OpenSSL 1.1.1m  14 Dec 2021 (Library: OpenSSL 1.1.1k  FIPS 25 Mar 2021)

**Comment by t8m** [comment]
> $ sudo openssl version
> OpenSSL 1.1.1m  14 Dec 2021 (Library: OpenSSL 1.1.1k  FIPS 25 Mar 2021)

This is still quite interesting output as the openssl binary apparently runs against a different openssl library build - the version there is different.

**Comment by edmundlaugasson** [comment]
Having same issue on Arch Linux and its derivates. There is after OpenSSL upgrade: openssl 3.0.7-2 currently.

**Comment by koijigen** [comment]
Everyone, sorry for mentioning the issue by mistake.

On Arch, I installed the package `openssl-1.1` and the error went away.

After the fix, the version installed on Arch remains 3 as show bellow:

```
$ sudo openssl version
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
```

**Comment by egl35720** [comment]
Great 👍
Removing broken symlink => OK
Installing openssl11-libs => OK
``
$ sudo openssl version
OpenSSL 1.1.1m  14 Dec 2021 (Library: OpenSSL 1.1.1k  FIPS 25 Mar 2021)``
