### ISSUE TITLE
Self test in fips mode

### ISSUE THREAD

**Issue by iamwum** [openssl/openssl#19491]
Hi,
Can anyone suggest on ways to corrupt the self test KATs programatically?

**Comment by paulidale** [comment]
The `fipsinstall` command can do this.  Look at what it does.

**Comment by iamwum** [comment]
Thanks for the reply. 
Is there a way to register an application callback which can be hooked inside openSSL code ?
I'm looking to get the results of OSSL_SELF_TEST_onend and OSSL_SELF_TEST_oncorrupt_byte APIs in my callback API.

**Comment by paulidale** [comment]
Yes, look at the fipsinstall source code for details...
