### ISSUE TITLE
Configuring provider after load

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#19496]
We can easily load the providers via `OSSL_PROVIDER_load`. 

But many providers require configuration after load (e.g. our FIPS provider). How can we do this in software?

**Comment by levitte** [comment]
No, those capabilities are private / internal to the provider conf module.

What you can do is to use `CONF_modules_load()` with a `CONF *` that you have create using `NCONF_load_bio()` on a memory BIO that gets its data from a string.  It's a bit convoluted, but should work fine.

**Comment by beldmit** [comment]
So I parse the provider's config, and then pass it to `CONF_modules_load()` and then this function loads the provider and configures it?

**Comment by levitte** [comment]
Yes, that's the idea.

*NOTE: I have not tested this!  I only quickly read some manual pages and a header file*
Have fun playing :wink:

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input

**Comment by beldmit** [comment]
Completed by #21604
