### ISSUE TITLE
Error dumping CSR generated by MS Exchange 2019 (for SAN Certificate)

### ISSUE THREAD

**Issue by pgbrandolin** [openssl/openssl#19494]
When I try to dump a CSR (usinq OpenSSL 1.1.1q  5 Jul 2022) generated by MS Exchange 2019 I get an error.
The command line is:
>openssl req -in ExchangeCert3.txt -text
unable to load X509 request
19644:error:0909006C:PEM routines:get_name:no start line:crypto\pem\pem_lib.c:745:Expecting: CERTIFICATE REQUEST

The CSR is correctly parsed, accepted and processed by online tool (i.e. Actalis). In fact the certificate has been issued.
In attachment the CSR (I've also tried to remove the word "NEW" from the first and last line but I get the same error).
Thanks

 
[ExchangeCert3.txt](https://github.com/openssl/openssl/files/9859267/ExchangeCert3.txt)

**Comment by beldmit** [comment]
Please check that you file doesn't have a BOM in the beginning of the file.

**Comment by pgbrandolin** [comment]
Thank you Beldmit. You gave me a useful hint: it was something about encoding. The file was encoded "UTF-16 Little Endian". I converted it in ANSI (or UTF-8 that in this case it's the same) with Notepad++ and then openssl decoded it correctly.

Thanks
pg
