### ISSUE TITLE
Why mont5 is required and why only x86 has mont5?

### ISSUE THREAD

**Issue by cathy-sjh** [openssl/openssl#19490]
When I read the OpenSSL 1.1.1 source code, I wondered why mont5 was implemented. More importantly, why mont5 was implemented only on x86 but not on Arm?

**Comment by paulidale** [comment]
It's a performance improvement which tend to be architecture specific.

If somebody contributed something similar for ARM, it would be considered.

**Comment by shen-jinhao** [comment]
I want to ask whether the RSA private key is stolen in ARM, like this article said(http://www.daemonology.net/hyperthreading-considered-harmful/)？If this problem does not exist, is a policy similar to mont5 still required under arm?

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input
