### ISSUE TITLE
Add a lightweight buffer + length module

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#19503]
It would be nice to have a lightweight module that accepts a pointer and a maximum length and exposes various write functions that add into the buffer but don't exceed the length.

The library often has to add data into buffers with length constraints and while we have WPACKET it's quite heavy.

**Comment by slontis** [comment]
Is it going to get much simpler than what it does now?
````
    WPACKET pkt;

    /* labeled_ikm = concat("HPKE-v1", suiteid, label, ikm) */
    if (!WPACKET_init_static_len(&pkt, labeled_ikm, sizeof(labeled_ikm), 0)
            || !WPACKET_memcpy(&pkt, LABEL_HPKEV1, strlen(LABEL_HPKEV1))
            || !WPACKET_memcpy(&pkt, suiteid, suiteidlen)
            || !WPACKET_memcpy(&pkt, label, strlen(label))
            || !WPACKET_memcpy(&pkt, ikm, ikmlen)
            || !WPACKET_get_total_written(&pkt, &labeled_ikmlen)
            || !WPACKET_finish(&pkt))
````

**Comment by mattcaswell** [comment]
> WPACKET it's quite heavy

Is it?
