### ISSUE TITLE
Failure to add hash algorithms to OpenSSL v3.0.5

### ISSUE THREAD

**Issue by shaoyang-v** [openssl/openssl#19502]
Hi, I tried to add my own hash algorithm to openssl. In the version V1.1.1q, after I updated the code according to the following steps, the function is running normally. But when I tried to do the same operation in openssl v3.0.5, the function cannot be run.
My own hash algorithm is the same as SHA256, just it needs to set a new OID for it.

1. Add new OID to customized hash algorithms.
2. Copy the members defined by SHA256 and change their names.   **static const EVP_MD custom_sha256_md = {...}** is updated to update the corresponding OID values within the structure.
3. Create function   **const EVP_MD \*EVP_custom_sha256(void)**
4. Add the new customized hash function to **openssl_add_all_digests_int()**.
5. Compile the code and use the following command to run the error message.

$ ./openssl dgst -custom-sha256 readme.md
Error setting digest
4027045E457F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:368:Global default library context, Algorithm (custom-sha256 : 98), Properties ()
4027045E457F0000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:crypto/evp/digest.c:258:

From the prompt information, I guess the attributes or abilities related to the algorithm are not configured. I guess this is the new requirement of V3.0.5, so I refer to the SHA256 updated code, but did not work.
Has anyone had similar questions? Or do you have any debugging suggestions, thank you very much.

**Comment by t8m** [comment]
This will not work in 3.0. You need to create a provider and make the hash being provided by it. Your provider can of course itself depend on libcrypto to actually compute the SHA256.

**Comment by shaoyang-v** [comment]
> This will not work in 3.0. You need to create a provider and make the hash being provided by it. Your provider can of course itself depend on libcrypto to actually compute the SHA256.

Hi @t8m , thank you for your reply.
As your suggestion, I added a macro definition `IMPLEMENT_LEGACY_EVP_MD_METH` to create functions such as `custom_sha256_init()`. These functions call the functions provided by SHA256 such as `SHA256_Init ()`.

```c
IMPLEMENT_LEGACY_EVP_MD_METH(custom_sha256, SHA256)

static const EVP_MD custom_sha256_md = {
    NID_custom_SHA256,
    NID_custom_SHA256,
    SHA256_DIGEST_LENGTH,
    EVP_MD_FLAG_DIGALGID_ABSENT,
    EVP_ORIG_GLOBAL,
    LEGACY_EVP_MD_METH_TABLE(custom_sha256_init, custom_sha256_update, custom_sha256_final, NULL,
                             SHA256_CBLOCK),
};

const EVP_MD *EVP_custom_sha256(void)
{
    return &custom_sha256_md;
}
```

I tested the code and did not work.
I checked the contents of the two pages, and did not find more explanations in this area. Do you have any information recommended in this regard? Thank you.
https://www.openssl.org/docs/man3.0/man7/migration_guide.html
https://wiki.openssl.org/index.php/OpenSSL_3.0

**Comment by t8m** [comment]
Do you want to patch openssl or make a proper provider? If the former there might be some ways how to do it in some simpler way possibly making the OID just an alias for the SHA256. If the latter then you can look for examples of providers here: https://github.com/provider-corner/

**Comment by shaoyang-v** [comment]
Hi @t8m , by creating a new provider, the new algorithm is work. Thank you!
