### ISSUE TITLE
Configuring provider during load

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#19507]
It's worth having an API for configuring provider after load

`OSSL_PROVIDER_load_ex()` API with `OSSL_PARAM` array would be great.

Follow-up to #19496

**Comment by t8m** [comment]
IMO you cannot configure the provider after the initial load. So it is not really "after load" but during load. Also then the question is what should be the semantics of OSSL_PROVIDER_load_ex() if the provider is already loaded. However it is still IMO quite useful to have such API call.

**Comment by beldmit** [comment]
@t8m thanks for correcting! Yes, during load.

I think it should fail if the provider is already loaded.

**Comment by t8m** [comment]
I think ideally we would keep the OSSL_PARAM array used when loading and if it is the same it could succeed. But yeah, that would be quite more involved.

**Comment by beldmit** [comment]
@simo5 this ticket to propose a design

**Comment by beldmit** [comment]
Superseded by #21350
