### ISSUE TITLE
TLS Mutual authentication - Client side coding on Windows - Client cert failed with Unknown CA

### ISSUE THREAD

**Issue by DDabbiru** [openssl/openssl#19504]
<img width="960" alt="Capture TLS" src="https://user-images.githubusercontent.com/115703288/197981296-60563269-3ceb-46f4-be65-9d0b9596748e.PNG">
[Network capture - Unknown CA.zip](https://github.com/openssl/openssl/files/9867847/Network.capture.-.Unknown.CA.zip)

Hi ,

I'm working on Client side coding(c++) using openssl on Windows.
Im trying to do Mutual Authentication, while sending the client cert, the handshake failed with Unknown CA.
-> I have installed root CA in Root Cert store in Local Computer
-> I'm using SSL_CTX_use_certificate_chain_file to send the cert chain. I concatenated my client.pem and rootca.pem to form certificate chain file and passed it to the meth SSL_CTX_use_certificate_chain_file.
Kindly suggest what else i need to do.

I have attached the network capture. Kindly review and please let me know what went wrong

**Comment by hlandau** [comment]
It looks like the client is rejecting the certificate sent by the server as not being trusted. OpenSSL will not use the Windows root CA store by default, though functionality to do this has been added in master (which will become OpenSSL 3.2). However no release of 3.2 is available yet. Therefore, you will need to either instruct OpenSSL to load certificates from a file containing root certificates (similarly to how things are done on Linux), or alternatively write some code to load the trusted root CA certificates from the Windows certificate store (some code I wrote personally ages ago to do this [can be found here](https://gist.github.com/hlandau/7a9a8146af25a2c972aa1fe400a8a60f), though this comes with no guarantees and is entirely unofficial).

**Comment by DDabbiru** [comment]
Hi,

We already have "loading the trusted root CA certificates from the Windows certificate store" in our code.
When i disable mutual authentication, my code works well and TLS handshake succeeds. That means my code is able to verify the server certificate.
But when i enable the mutual auth, the handshake fails, i dont think its because of the server cert validation failure.
Could you please review my logs and confirm once again.
I can even attach my code if you want to review it.

**Comment by mattcaswell** [comment]
> It looks like the client is rejecting the certificate sent by the server as not being trusted. 

It's actually the other way around. Its the server that is rejecting the client's certificate.

You don't tell us anything about the server. Is that also OpenSSL or something else?

**Comment by DDabbiru** [comment]
Hi ,
Thanks for your reply and confirmation. Yes, its the server that's rejecting the client cert.
I'm using syslog-ng as my server, in the syslog-ng conf i'm specifying it to validate the peer using the tag:
    peer-verify(optional-trusted)

**Comment by DDabbiru** [comment]
Hi ,

Could you please help with this issue.

**Comment by t8m** [comment]
The client certificate must be signed by CA that is trusted by the server.

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input
