### ISSUE TITLE
Code development for the cipher-suite TLS_DHE_RSA_WITH_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by AhamedFayaz** [openssl/openssl#19512]
Actually, I wants to develop the c code for the encryption protocol TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 I am able to get the code for DHE, RSA and AES128GCM individually I don't know how to combine all there protocol's as per the cipher suite.  Please explain the how the TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 encryption is works.

Please give me the guidance. Thank you.

**Comment by t8m** [comment]
It is not completely clear what you're asking about. The TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 is a TLS 1.2 ciphersuite. It is implemented in libssl. To implement it independently of libssl you basically need to implement the whole TLS protocol.

**Comment by AhamedFayaz** [comment]
Thankyou Tomáš Mráz for your reply. 

Sample code for AES i was integrate in to my project and working fine.
https://stackoverflow.com/questions/44947883/compute-the-cbc-mac-with-aes-256-and-openssl-in-c


Sample code for RSA Also integrate the code and verified.
https://www.openssl.org/docs/man1.1.1/man3/RSA_sign.html

sameway i got the code for DHE,RSA,AES128,SHA256. That are working separately.


Now my question is 
How to Compian all algorithms as per the TLS_DHE_RSA_WITH_AES_128_GCM_SHA256?
I don't know how the TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 is perform?

**Comment by mattcaswell** [comment]
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 is a TLS ciphersuite. It combines all the stated algorithms as part of the TLS protocol. You do not need use AES or RSA or any other algorithm directly at all. You just use TLS and configure it to negotiate the ciphersuite you want and libssl will do the rest.

There's some demo code for using TLS here:

https://github.com/openssl/openssl/tree/master/demos/sslecho

**Comment by AhamedFayaz** [comment]
Thank you matt caswell. I will try to integrate the stack.

**Comment by AhamedFayaz** [comment]
Thank you matt caswell 
 I was planned to take this example, But I need some clarity about how to configure cipher suite 
https://github.com/wolfSSL/wolfssl-examples

**Comment by nhorman** [comment]
Marking as inactive, will be closed at the end of 3.4 dev cycle, barring further input
