### ISSUE TITLE
If I close server process，how can i reuse the connect after restart server？

### ISSUE THREAD

**Issue by Creep-9527** [openssl/openssl#19514]

**Comment by t8m** [comment]
You cannot reuse the connection. If your server maintains permanent TLS session cache, or permanently stores the key to decrypt the stateless session tickets, the client can resume the session after reconnecting not needing full TLS handshake with the server.

**Comment by Creep-9527** [comment]
> 

Thanks for your reply。So how can I save TLS session cache，and csn i save the information in redis？

**Comment by mmiyashi** [comment]
I'm following the thread.  I would also like to know how to save the TLS session cache or save the key to decrypt the stateless session tickets, and how to restore the state in the new process?  Is there any API available like PEM_read_bio_SSL_SESSION()/SSL_set_session()?  TIA!
