### ISSUE TITLE
Reports incorrect Signature Algorithm for certificate

### ISSUE THREAD

**Issue by Stretch96** [openssl/openssl#1952]
Using the domain sha1-2017.badssl.com as an exmaple, should it not report the certificate signature algorithm as SHA-1?

```
$ echo | openssl s_client -connect sha1-2017.badssl.com:443 2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm"
$ Signature Algorithm: sha256WithRSAEncryption
$ Signature Algorithm: sha256WithRSAEncryption
```

This is on both version 1.0.1f and 1.0.2g

**Comment by snhenson** [comment]
Looks like that host needs the servername extension. Try it with -servername sha1-2017.badssl.com

**Comment by Stretch96** [comment]
Ah, yeah that works 🌴 😐
Thanks 👍
