### ISSUE TITLE
Error building openssl.1.1.1m

### ISSUE THREAD

**Issue by av-user** [openssl/openssl#19533]
I'm trying to follow this instruction:
https://techviewleo.com/how-to-install-python-on-opensuse-linux/
and get an error processing make in openssl.1.1.1m directory just after successful configuration step.
![Untitled-1](https://user-images.githubusercontent.com/19575299/198825312-e718db43-be97-44e6-aec6-894ada94f53e.jpg)
![Untitled-2](https://user-images.githubusercontent.com/19575299/198825318-474c79be-46e7-4b4c-8fa2-c7b2375f4f79.jpg)

**Comment by t8m** [comment]
Please paste output of `./configdata.pm -d`
