### ISSUE TITLE
openssl speed support for provider-based kem and signature algorithms

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#19535]
Is the understanding correct that neither KEM (encaps/decaps) nor signature (sign/verify) algorithms implemented in providers can be triggered/tested via [openssl speed](https://www.openssl.org/docs/manmaster/man1/openssl-speed.html)? If so, would a PR be welcome to add such feature?

**Comment by paulidale** [comment]
Yes, such a PR would be welcomed.

**Comment by baentsch** [comment]
Resolved via #19968
