### ISSUE TITLE
FIPS provider missing KBKDF options

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#19545]
The [security policy](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4282.pdf) lists the following MACs for use with KBKDF: CMAC AES128, AES192, AES256 and HMAC-SHA-1, SHA2-224, SHA2-256, SHA2-384, SHA2-512.

Missing are HMAC SHA3, truncated HMAC SHA2 and KMAC algorithms (HMAC SHA3-224, HMAC SHA3-256, HMAC SHA3-384, HMAC SHA3-512, HMAC SHA2-512/224, HMAC SHA2-512/256, KMAC 256 and KMAC 512).

**Comment by t8m** [comment]
Is this security policy only thing or is there anything missing in code to support these?

**Comment by paulidale** [comment]
I'd guess that they were not tested.  I don't know if a security policy update alone would be sufficient.

The code explicitly checks for CMAC or HMAC and errors if neither is found.  So KMAC isn't currently possible.  I'll raise this as a separate non-FIPS issue.

**Comment by paulidale** [comment]
Closing.  The missing MACs have been added for the 140-3 validation.  They won't be added to the 140-2.
