### ISSUE TITLE
A possible null pointer dereference

### ISSUE THREAD

**Issue by ycaibb** [openssl/openssl#19542]
Hi, can `fdopen` return null value? the value should be checked before passing to `fgets`? Thank you for checking.
https://github.com/openssl/openssl/blob/9710d72b95f4fc218ed613f42dc90ad0d263b14f/apps/speed.c#L3511-L3512

**Comment by arendhummeling** [comment]
I think that if `fdopen` somehow fails, the `fgets` call will return `NULL`, so the while guard check will fail. The check seems redundant.

**Comment by paulidale** [comment]
`fgets` crashing when passed a NULL stream pointer is permitted behaviour I believe.
That some libc's check and fail gracefully, doesn't mean all do.

**Comment by akai54** [comment]
Should be closed, this issue has been resolved by the PR #19651.
