### ISSUE TITLE
x86 libssl-dev1.1.1f openssl will not check the private key.

### ISSUE THREAD

**Issue by fengmao31** [openssl/openssl#19541]
x86 libssl-dev 1.1.1f openssl SSL_CTX_check_prvate_key(ctx) will not check the private key. you can find I change the key to a mass string. it will load the pem and keep run. when it do the hand shark it will fail.
![image](https://user-images.githubusercontent.com/19343842/198873530-854e978b-22e8-446d-9ee8-c2b33add8d02.png)

![image](https://user-images.githubusercontent.com/19343842/198873492-4a485a5b-2a8f-49cd-9738-4458381c0ff0.png)

**Comment by t8m** [comment]
Have you tried a recent openssl-1.1.1 release?
