### ISSUE TITLE
Provider decoder man and header file mismatch

### ISSUE THREAD

**Issue by Lipovlan** [openssl/openssl#19543]
I'm working with OpenSSL version 3.2.0-dev.

On line 907 in `core_dispatch.h` there is declared `OSSL_FUNC_decoder_export_object` 
function. The return type is `int`. In documentation for [provider-decoder](https://www.openssl.org/docs/manmaster/man7/provider-decoder.html), the return type is `void *`. What should the `OSSL_FUNC_decoder_export_object` function return?

**Comment by levitte** [comment]
The header file is correct.
