### ISSUE TITLE
x509_store_ctx_get_current_cert() function behaviour

### ISSUE THREAD

**Issue by NorthHill-16** [openssl/openssl#19553]
Hi, in OpenSSL document, **X509_STORE_CTX_get_current_cert() returns the certificate in ctx which caused the error or NULL if no certificate is relevant.** However, in practice and test, I see X509_STORE_CTX_get_current_cert() actually will return every cert, include valid and invalid. As an example,

```
int cb(int ok, X509_STORE_CTX* ctx)
{
  X509 *cert = X509_STORE_CTX_get_current_cert();   <<<<<  here return correct/valid cert as well
...
}

int main()
{
  SSL_set_verify(ssl, cb);
}
```
In source code, 
'''
X509 *X509_STORE_CTX_get_current_cert(const X509_STORE_CTX *ctx)
{
    return ctx->current_cert;
}
'''

So, My question is, is document wrong or mu understanding is wrong? What is this function's behaviour, thanks.

**Comment by t8m** [comment]
@vdukhovni Could perhaps answer this question?

**Comment by vdukhovni** [comment]
When the "ok" parameter is 0 (reporting a chain construction/validation error), the current certificate will be the one that is most closely related to the error (either lacks a suitable issuer during construction, or has an unsuspported/invalid signature, is expired, doesn't meet the security level, ...).

Once chain construction is over, OpenSSL walks the chain performing signature checks and invokes the callback for each certificate in the chain in turn (from the topmost issuer down to the EE cert at depth 0), the callback is invoked whether or not there is an error, and the current certificate is the certificate at the (no surprise) current depth.  If all is well "ok = 1".  This supports application debugging/logging and additional scrutiny of the certificates *during* the handshake.

If the documentation suggests that current cert is always NULL in non-error situations, the documentation should be made more clear.  The text in question is talking about the error case, and basically indicates that *if* no relevant certificate is available, the current cert may be NULL, even though an error is reported. It is not saying the converse, namely it is not promising a NULL value when there is no error.

If this is actually confusing, someone should propose a doc patch that makes is clear, without further muddying the waters by confusing those who already understood it... :-)

**Comment by t8m** [comment]
I think this anwers the question clearly.

@NorthHill-16 if you want a clarification in the manual page could you please submit a PR with such clarification?

**Comment by NorthHill-16** [comment]
Hi, @t8m Sorry for late reply, yes, the question is answered. Not sure you mean "Pull Request" or "Feature Request"?

**Comment by vdukhovni** [comment]
> Hi, @t8m Sorry for late reply, yes, the question is answered. Not sure you mean "Pull Request" or "Feature Request"?

Pull Request, as in contribute a proposed documentation update if you still feel the current text is potentially misleading to others and additional/replacement text is warranted.

**Comment by NorthHill-16** [comment]
Hi, @vdukhovni , ok, thanks. I have 1 more question about above, 

> the current certificate will be the one that is most closely related to the error 

This sentence is not equivalent to "the current certificate will be the one that causes error", but what could happen if "closely related" not the "one that causes error"? My interpretation is, if ok=0, and current SSL verification error has no **directly** related certificate, then it will return either the closely related certificate or NULL?

**Comment by NorthHill-16** [comment]
Hi, @vdukhovni , thanks, the pull request 20038 is submitted, please check, first time do this, this pull request shall follow the related rules.
