### ISSUE TITLE
BN_mod_exp_mont_consttime or BN_mod_exp_mont?

### ISSUE THREAD

**Issue by cathy-sjh** [openssl/openssl#19551]
I see the **BN_mod_exp_mont_consttime** interface is to solve the Hyper-Threading vulnerability(Permits a malicious thread to monitor the execution of another thread, allowing in many cases for theft of cryptographic keys).
Whether this problem still exists on modern CPUs, I want to ask how to choose between **BN_mod_exp_mont_consttime** and **BN_mod_exp_mont** on modern CPUs, after all there is a performance gap between the two。

**Comment by paulidale** [comment]
Which you use depends entirely on the context where you are using it.

If you are dealing exclusively with public information, you can use **BN_mod_exp_mont**.  Otherwise, use **BN_mod_exp_mont_consttime**.  If you are unsure, play it safe and use **BN_mod_exp_mont_consttime**.

The problem still exists on modern CPUs.

**Comment by davidben** [comment]
@paulidale That's not quite right. Or, at least, it doesn't match what the algorithms do. It does seem to match OpenSSL's `BN_FLG_CONSTTIME` checks, but that seems to be a mistake (unnecessary perf regression).

First off, this is not just one single vulnerability, but a more cohesive notion of "constant-time". This is about code executing independent of various secrets. https://www.bearssl.org/constanttime.html

`BN_mod_exp_mont` and `BN_mod_exp_mont_consttime` are modular exponentiation, using Montgomery multiplication, with variable and fixed windows, respectively.

The two algorithms vary by what values you believe are secret. By using Montgomery reduction, both algorithms treat the base, `a`, as secret. There's no particular performance penalty to treating the base as secret, apart from dropping a few pointless special cases.

However, if you believe the exponent is secret, variable windows leak information about the exponent and you need to use fixed windows. This does come with a performance penalty.

Thus, if you are computing an inverse modulo a prime, as done in ECC, where the value is secret but the prime modulus is public, variable windows (`BN_mod_exp_mont`) are fine. But if you are exponentiating with a secret exponent (RSA private key operations), you must use fixed windows (`BN_mod_exp_mont_consttime`).

**Comment by davidben** [comment]
Looks like the mixup came from https://github.com/openssl/openssl/pull/4477

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further updates
