### ISSUE TITLE
use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'

### ISSUE THREAD

**Issue by xyxdaily** [openssl/openssl#19559]
crypto/thread/arch/thread_posix.c:25:28: error: use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'
    pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
                           ^
crypto/thread/arch/thread_posix.c:26:5: warning: implicit declaration of function 'pthread_setcanceltype' is invalid in C99 [-Wimplicit-function-declaration]
    pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
    ^
crypto/thread/arch/thread_posix.c:26:27: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'
    pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
                          ^
3 warnings and 2 errors generated.

**Comment by FdaSilvaYY** [comment]
What is your platform ? Os? Compiler ?

**Comment by rsbeckerca** [comment]
These definitions are usually in `/usr/include/pthread.h`. Is the include being ignored on your system?

**Comment by GVNG** [comment]
Guys, this is a really CRITICAL bug. OpenSSL doesn't compile at all with the NDK on Android. It happened about 2 or 3 months ago. Could you fix it with a high priority, please?

**Comment by mattcaswell** [comment]
Possible fix in #19779. Note this only affects master so a work around is to simply compile the latest stable version (3.0.7) instead.
