### ISSUE TITLE
Conan recipe error

### ISSUE THREAD

**Issue by gprosch** [openssl/openssl#19552]
The following conan command:

conan install "C:\dev\FieldRep.master\Projects\WebSDK\PreBuild\conanfile.txt" -s arch="x86_64" -s build_type="Release" -s compiler.version="17" -s compiler="Visual Studio" --update --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Yields the following error:

openssl/1.1.1n: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
openssl/1.1.1n: WARN: Build folder C:\Users\gregp\.conan\data\openssl\1.1.1n\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: openssl/1.1.1n: Error in build() method, line 757
        self._create_targets()
while calling '_create_targets', line 608
        ancestor = '[ "%s" ]' % self._ancestor_target
while calling '_ancestor_target', line 430
        compiler = "Visual Studio" if self.settings.compiler == "msvc" else self.settings.compiler
        ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

**Comment by t8m** [comment]
This is not something we could fix. We do not ship the Conan recipe.

**Comment by gprosch** [comment]
Understood, thank you.
