### ISSUE TITLE
Consider requiring OMC & OTC members to publish keys fully via keys.openpgp.org (or provide them in full via website)

### ISSUE THREAD

**Issue by thesamesam** [openssl/openssl#19567]
keys.openpgp.org allows a "simple" submission (anyone can submit anyone's keys), but for GDPR compliance, if one searches a key via keys.openpgp.org, unless a user verifies their email address and consents to publication, the returned keys don't include a UID.

For example:
```
gpg: keybox '/var/tmp/portage/dev-libs/openssl-3.0.7/temp/gemato.pr7ev5u7/pubring.kbx' created
gpg: key 36CEE4DEB00CFE33: no user ID
gpg: key D5E9E43F7DF9EE8C: no user ID
gpg: /var/tmp/portage/dev-libs/openssl-3.0.7/temp/gemato.pr7ev5u7/trustdb.gpg: trustdb created
gpg: key D9C4D26D0E604491: public key "Matt Caswell <matt@openssl.org>" imported
gpg: key 231C84CDDCC69C45: public key "Paul Dale <pauli@openssl.org>" imported
gpg: key 9195C48241FBF7DD: no user ID
gpg: key 2064C53641C25E5D: no user ID
gpg: Total number processed: 6
gpg:               imported: 2
```

See https://keys.openpgp.org/about/faq#non-email-uids and https://keys.openpgp.org/about/faq#search-substring. Alternatively, consider hosting a copy of the keys (including signatures) on the OpenSSL website.

(The reason I'm picking on keys.openpgp.org here is because https://www.openssl.org/community/omc.html and https://www.openssl.org/community/otc.html link to it.)

**Comment by thesamesam** [comment]
ping. This makes verifying releases quite hard downstream.

**Comment by mattcaswell** [comment]
Adding OTC hold so that it gets discussed at OTC.

**Comment by levitte** [comment]
Meanwhile, I'm certainly willing to do the necessary steps to verify my user id.  I was unaware of this issue...

**Comment by t8m** [comment]
OTC: All the release managers (as in https://github.com/openssl/openssl/blob/master/doc/fingerprints.txt) have full key ids on keys.openpgp.org so that should be sufficient for now.

**Comment by t8m** [comment]
@thesamesam Are you OK with the above?

**Comment by thesamesam** [comment]
@t8m This works for me. It might be worth putting a note somewhere that folks need to manually verify once they submit to keys.openpgp.org, in case a new release manager forgets, but it might be easy enough to remember now we've been through this.

Thank you for handling it folks!
