### ISSUE TITLE
'you may need to install the OpenSSL::fallback module' error when building OpenSSL source code

### ISSUE THREAD

**Issue by radovan-zach** [openssl/openssl#19599]
Hello,
 I am trying to build the OpenSSL 3.0.7 binaries for Windows x64 from the source code.
 
 When I run `perl Configure VC-WIN64A` or `perl Configure` commands to build the binaries I am getting:
 
```
Can't locate OpenSSL/fallback.pm in @INC (you may need to install the OpenSSL::fallback module) (@INC contains: C:/Temp/openssl-3.0.7/util/perl C:/perl/site/lib C:/perl/lib) at Configure line 20.
BEGIN failed--compilation aborted at Configure line 20.
```

The machine I am building on was initially using Strawberry Perl 5.32.1.1. In order to find out whether the missing OpenSSL::fallback module is part of the source-code-built Perl I downloaded the Perl v5.36.0 source code, built it and attempted to build the OpenSSL 3.0.7 again. The outcome was the same error message about missing OpenSSL::fallback.

I searched for the OpenSSL::fallback module using the "cpan -x OpenSSL::fallback" command and also searched for it at https://metacpan.org/. Did not find any suitable modules.

Where do I get the missing OpenSSL::fallback module?

The Perl script Configure refers to other modules in the OpenSSL namespace. Where do I get these?

Thank you,
Radovan

**Comment by levitte** [comment]
All the `OpenSSL::` modules are in the source, in `util/perl/OpenSSL`.  I'm a bit mystified by this failure, 'cause you have `C:/Temp/openssl-3.0.7/util/perl` in `@inc`, which should be exactly correct to be able to find `OpenSSL::fallback` as `C:/Temp/openssl-3.0.7/util/perl/OpenSSL/fallback.pm`

**Comment by levitte** [comment]
In what shell did you do this?

**Comment by radovan-zach** [comment]
Hello Levitte,
 thank you for your comment. I verified the the util/perl/ folder and there was no OpenSSL subfolder in it. Some other pieces of the source code were missing as well.

The source code did not get copied completely to the build machine. I was not aware of it. I apologise the fault was clearly on my part.

Thank you,
Radovan
