### ISSUE TITLE
Across version provider testing is failing

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#19601]
The test that checks that the 3.0 and master FIPS providers interoperate is [broken](https://github.com/paulidale/openssl/actions/runs/3388207103/jobs/5629908581).

In master and 3.1, triple DES has been removed from the FIPS provider because of an end of 2023 sunset.  Refer [SP 800-131Ar2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf).  The unit tests in 3.0 haven't the slightest clue that this is happening and fail because the triple DES algorithms cannot be fetched and tested.

Worse is that PKCS **⌗**1 version 1.5 padding is also being sunsetted at the end of 2023 and it's upcoming removal from the FIPS provider in master and 3.1 will cause a lot more errors to happen in the 3.0 cross version testing.

The underlying problem of algorithms going missing and been modified needs to be addressed somehow.

**Comment by t8m** [comment]
There seems to be one more failure unrelated to the DES https://github.com/openssl/openssl/actions/runs/3436392162/jobs/5729871998

**Comment by paulidale** [comment]
A FIPS provider from master doesn't include the PCT, so corrupting it isn't going to cause the expected failure.
It's not clear what a good fix is.  The PCT could be included in master even though it's redundant & will slow module startup or the 3.0 test suite could be made FIPS provider version aware.

**Comment by t8m** [comment]
Could you just for now modify the CI so it skips the test_fipsinstall?

**Comment by t8m** [comment]
Or the FIPS provider in master could do a fake PCT self test that won't do anything but just fail if it is corrupted.

**Comment by t8m** [comment]
This is fixed now.
