### ISSUE TITLE
OpenSSL Assertion Error While generating Ciphertext in v1.02

### ISSUE THREAD

**Issue by vsundriy** [openssl/openssl#19616]
Trying to use OpenSSL (version 1.02u) SM3 algorithm and getting an error stating

'''hmac.c(116): OpenSSL internal error, assertion failed: j <= (int)sizeof(ctx->key)'''

Can't post the code due to security issues but can anyone tell if in some way, this error could be related to the input data (plaintext and 32 bit key) that I am providing.

Thanks.

**Comment by tom-cosgrove-arm** [comment]
Do you really mean "32 bit key"?

**Comment by mattcaswell** [comment]
There are some curious things about your question. Firstly you say you are trying to use SM3, but OpenSSL 1.0.2u does not support SM3.
You don't mention hmac in your question, but the assertion is coming from the HMAC code. It is asserting that the digest block size <= max size of the key in the HMAC structure (128 bytes). It appears to be failing for your particular digest.

Unfortunately 1.0.2 is no longer receiving public support. So we can't really help you with this.

It seems like you are using a modified version anyway? Perhaps you are using a fork such as GmSSL? If so you should ask your question in the forums associated with the fork.

**Comment by vsundriy** [comment]
> There are some curious things about your question. Firstly you say you are trying to use SM3, but OpenSSL 1.0.2u does not support SM3. You don't mention hmac in your question, but the assertion is coming from the HMAC code. It is asserting that the digest block size <= max size of the key in the HMAC structure (128 bytes). It appears to be failing for your particular digest.
> 
> Unfortunately 1.0.2 is no longer receiving public support. So we can't really help you with this.
> 
> It seems like you are using a modified version anyway? Perhaps you are using a fork such as GmSSL? If so you should ask your question in the forums associated with the fork.

Thanks for the detailed response. Indeed I am using openssl_gmssl_1.0.2u. I am new to cryptography so just wanted to know  in which way the digest block size and max size of the key in the HMAC structure are related to the plaintext and the size of the key I am providing as input. Could you please tell?

**Comment by vsundriy** [comment]
> Do you really mean "32 bit key"?

Sorry if it did not make sense. I am new to cryptography so still learning stuff. What is the key size for HMAC SM3 algorithm?

**Comment by tom-cosgrove-arm** [comment]
> What is the key size for HMAC SM3 algorithm?

**Comment by tom-cosgrove-arm** [comment]
> What is the key size for HMAC SM3 algorithm?

SM3 is a hash algorithm - these don't have keys (sorry if you already know this, but you do say you are new to cryptography).

HMAC is a generic way to create a MAC from a hash function.  A MAC is a symmetric signature, that is, a signature that uses the same key to create the signature as to verify it.

HMAC supports arbitrary key sizes; the key is handled differently depending on whether it is shorter than the hash function's block size or not, so in practice (for "reasons") one should only use keys which are shorter than the hash function block size.

SHA-256 has a block size of 512 bits (64 bytes); SHA-512 has a block size of 1024 bits (128 bytes); and as I understand it SM3 has a block size of 512 bites (64 bytes).

Regarding minimum key length: in symmetric cryptography, a 32-bit key is considered trivially breakable by brute force. A 64-bit key (for RC5) was brute forced in 2002. AES uses a minimum key size of 128 bits.

So typically for HMAC-SM3 I would expect to see a key of at least 128 bits (16 bytes) and at most 512 bits (64 bytes).

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
