### ISSUE TITLE
Build with only "-static" option results in duplicate symbols in static library

### ISSUE THREAD

**Issue by Mrsvkarthik** [openssl/openssl#19620]
Hi All,

I tried to configure a build to only build static libs so I have added "-static" option in the Configuration parameters. Build was successful but seen some duplicate symbols .

Please let me know the command which I have used is correct

./Configure --prefix=/openssl-3.0.7/linux32-release --openssldir=/openssl-3.0.7/linux32-release-openssl --release -static

nm -a libcrypto.a | grep bn_mul_words
000002d0 T bn_mul_words
         U bn_mul_words
         U bn_mul_words
         U bn_mul_words
         U bn_mul_words
000002d0 T bn_mul_words

One of the duplicated symbols "bn_mul_words"

Please let me know if there is any change required in Configuration.

If I build without "-static"  then there is no duplicate symbols.

Thanks
Karthik

**Comment by t8m** [comment]
This is not the way to make static libraries of openssl. Use `no-shared no-modules` instead if you want a pure static build.

**Comment by Mrsvkarthik** [comment]
Thanks
