### ISSUE TITLE
CA operations with external provider fail CA certificate=private key check due to improper export

### ISSUE THREAD

**Issue by simo5** [openssl/openssl#19637]
This comes out of this issue: https://github.com/latchset/pkcs11-provider/issues/94

The gist of it is that EVP_PKEY_eq() is called to check if the private key provided correspond to the CA cert available and in case the private key is stored in an external provider an export->import operation is performed in order to compare the private key to the public key extracted from the cert.

Unfortunately the export function unconditionally tries to export all key data. In case of HSMs, SmartCards and other pkcs11 modules, private keys cannot be exported, so the operation simply fails.

Given the comparison requires only that the public keys match I see a few solutions:
1) the export function is changed to request to export only the corresponding public key.
   NOTE: this is not ideal because in some pkcs11 tokens (like PIV cards) a public key may not even be available, so extracting a public key from a private key may fail anyway, but would work with a number of other tokens.

2) instead of comparing keys, try a public key vs private key operation, like signing a known string with the provided private key, and verifying it with the public key.

3) Do not check at this stage, go through the certificate signing operation and verify it with the cert public key before writing the cert out.

This breaks using providers for CA operations in the 3.0.x series and ideally should be fixed there as well as 3.1 and master trees.

**Comment by t8m** [comment]
> 2\. instead of comparing keys, try a public key vs private key operation, like signing a known string with the provided private key, and verifying it with the public key.

That would have to be done in the X509_check_private_key() instead of the EVP_PKEY_eq() call. It would make sense. Or maybe this function could first try the eq() call and if it fails as a fallback that is more expensive it could do the sign&verify operation. (Or encrypt&decrypt if the certificate key usage is for public encryption.)

**Comment by simo5** [comment]
> > 2. instead of comparing keys, try a public key vs private key operation, like signing a known string with the provided private key, and verifying it with the public key.
> 
> That would have to be done in the X509_check_private_key() instead of the EVP_PKEY_eq() call. It would make sense. Or maybe this function could first try the eq() call and if it fails as a fallback that is more expensive it could do the sign&verify operation. (Or encrypt&decrypt if the certificate key usage is for public encryption.)

I still think that properly fixing EVP_PKEY_eq() is a good idea, as this problem may happen elsewhere as well.

For example I see it used in ssl_set_cert_and_key() again to check pub v private key { called from SSL_[CTX_]use_cert_and_key() }, if they come from different providers this will fail just like in openssl ca.

**Comment by beldmit** [comment]
In pre-3.0 time there was a flag allowing not compare public and private key. It was useful when the private key is not available as local file. Do we have smth like that now?

**Comment by t8m** [comment]
> I still think that properly fixing EVP_PKEY_eq() is a good idea, as this problem may happen elsewhere as well.

IMO doing keypair operation as part of EVP_PKEY_eq() would be really bad idea. So improving EVP_PKEY_eq() is possible only through the first option.

**Comment by simo5** [comment]
> > I still think that properly fixing EVP_PKEY_eq() is a good idea, as this problem may happen elsewhere as well.
> 
> IMO doing keypair operation as part of EVP_PKEY_eq() would be really bad idea. So improving EVP_PKEY_eq() is possible only through the first option.

I meant it as in doing the proper thing and use selection bits in EVP_PKEY_eq(), I was not suggesting doing keypair operation in EVP_PKEY_eq().

I think we should fix EVP_PKEY_eq() *and* potentially use a fallback keypair operation in X509_check_private_key()

I just do not think doing *only* keypair fallabck/checks in X509_check_private_key() is sufficient.

**Comment by simo5** [comment]
@t8m here https://github.com/latchset/pkcs11-provider/issues/94#issuecomment-1308311754 you mention the issue of caching in evp_keymgmt_util_export_to_provider(), the questions is ... do we actually need to cache? If we skip caching this becomes easier

**Comment by simo5** [comment]
The other option is to add a selection argument to OP_CACHE_ELEM ... is this acceptable ?

**Comment by t8m** [comment]
> @t8m here [latchset/pkcs11-provider#94 (comment)](https://github.com/latchset/pkcs11-provider/issues/94#issuecomment-1308311754) you mention the issue of caching in evp_keymgmt_util_export_to_provider(), the questions is ... do we actually need to cache? If we skip caching this becomes easier

I did not look at the code right now but if I remember correctly the implementation puts the reference to the keydata imported into the destination provider into the cache and then uses the reference from the cache. So skipping the cache if selection is not ALL might be more complicated than adding the selection argument to the cache. This needs to be examined more deeply though.

**Comment by simo5** [comment]
I am working on a patch, I think discussion will be easier once I post a PR at this point.

**Comment by simo5** [comment]
Resolved in #19648
