### ISSUE TITLE
Creation of testing labels

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#19640]
https://github.com/openssl/technical-policies/pull/57 has now merged. I'll go ahead and create the labels if nobody objects. How about this colour for the non-hold labels:

![test_d876e3](https://user-images.githubusercontent.com/2270010/201049037-661d6f96-3bfe-4d14-ae45-91da0691c0e3.png)

**Comment by mattcaswell** [comment]
Looks ok to me. We can always change it later.

**Comment by t8m** [comment]
I wonder how it will look like on white background. But yeah, go ahead and create the labels.

**Comment by hlandau** [comment]
Labels created.

@openssl/committers Please start using these! :tada:
