### ISSUE TITLE
Expansion of OSS-Fuzz targets

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#19642]
Is there any reason why you are not fuzzing for x86 (32 bit) on OSS-Fuzz? https://github.com/google/oss-fuzz/blob/0439d667e30d8ab82cc55ee683a8e193169cbfe8/projects/openssl/project.yaml#L14-L15

Even if x86 OpenSSL installs are not widely used in production, fuzzing x86 may occasionally find certain bugs faster than on x64, owing to alternative type widths (e.g. `size_t` being 32 rather than 64 bits) and other differences at the binary level.

Additionally, do you think it would be worthwhile to create targets specifically for the 1.1.1 tree, both for the TLS fuzzers in the OSS-Fuzz `openssl` project as well as for the API fuzzers in `cryptofuzz`?

I can take care of making the requisite modifications to OSS-Fuzz projects if any are desired.

**Comment by t8m** [comment]
I do not think we want new 1.1.1 specific targets. The 1.1.1 is security-fix only now

For master/3.0/3.1 yeah, 32 bit build fuzzing would be certainly useful.

**Comment by bernd-edlinger** [comment]
Well, but I would be interested in having the x86 fuzzing in my openssl-111-featrues branch here:
https://github.com/bernd-edlinger/openssl/tree/openssl-111-features

**Comment by guidovranken** [comment]
> I do not think we want new 1.1.1 specific targets. The 1.1.1 is security-fix only now
The aim of fuzzing is to find security bugs so imho it makes sense to fuzz 1.1.1

**Comment by guidovranken** [comment]
I've created a PR here https://github.com/google/oss-fuzz/pull/8969

This builds all the fuzzers for master, 1.1.1 and 32 bit.

Should I build @bernd-edlinger 's 111 feature branch instead? Any other changes I should make?

**Comment by bernd-edlinger** [comment]
> Should I build @bernd-edlinger 's 111 feature branch instead? Any other changes I should make?

That would make me of course very happy.
But may I suggest to also cover the openssl-3.0 branch?

The reason why I ask is the exprience with my "Add Reproducible Error Injection" patch #18355 

While the MTBF if this kind of error is probably measured in years on the 1.1.1 branch,
it is in a range of weeks in the master branch, but only minutes in the 3.0 branch.
Actually, I gave up chasing all those bugs by now.

**Comment by guidovranken** [comment]
Ok. Should it have `openssl/OpenSSL_1_1_1-stable` AND `bernd-edlinger/openssl-111-features` or only the latter?

**Comment by bernd-edlinger** [comment]
I can't speak for the OTC, but @t8m said something like:

> I do not think we want new 1.1.1 specific targets. The 1.1.1 is security-fix only now
> 
> For master/3.0/3.1 yeah, 32 bit build fuzzing would be certainly useful.

so that would probably imply only `bernd-edlinger/openssl-111-features` AND `openssl/openssl-3.0` AND `openssl/openssl-3.1` unless I misunderstood him.

**Comment by thesamesam** [comment]
I have to admit I don't agree with the official position on 1.1.1 CI changes. As long as it's supported for security fixes, we want to be running as much CI on it as reasonable so that we can find problems. Even non-fuzzing CI is useful because it'd be rather embarrassing to make a 1.1.1 security release only to find out it doesn't build. I'm happy to do the backporting work if folks can tolerate merging it.

**Comment by bernd-edlinger** [comment]
I already made a couple of CI improvements targeting 1.1.1: #18356 #18352 ...
all were denied although they did only contain additional test coverage:
the last response was https://github.com/openssl/openssl/pull/18356#issuecomment-1132575299

> @bernd-edlinger If you want to have a 1.1.1 feature fork I'd suggest to create it as a separate GitHub project.

...and that is what I did.

**Comment by kroeckx** [comment]
> While the MTBF if this kind of error is probably measured in years on the 1.1.1 branch,
> it is in a range of weeks in the master branch, but only minutes in the 3.0 branch.

Can you clarify why this is the case?

**Comment by mattcaswell** [comment]
>  bernd-edlinger/openssl-111-features 

IMO we should not be building this branch. This is an unofficial branch and not part of the project.

**Comment by bernd-edlinger** [comment]
> > While the MTBF if this kind of error is probably measured in years on the 1.1.1 branch, it is in a range of weeks in the master branch, but only minutes in the 3.0 branch.

> Can you clarify why this is the case?

I dont know why exactly, but this is the list of bugs I found in 1.1.1 due to the error injection:
```
1.1.1:

Date:   Fri May 20 08:02:47 2022 +0200    Fix a crash in asn1_item_embed_new
Date:   Fri May 20 16:15:44 2022 +0200    Fix a memory leak in ec_key_simple_oct2priv
Date:   Fri May 20 16:54:41 2022 +0200    Fix undefined behaviour in EC_GROUP_new_from_ecparameters
Date:   Sat May 21 15:41:46 2022 +0200    Fix a memory leak in X509_issuer_and_serial_hash
Date:   Sat May 21 07:50:46 2022 +0200    Fix a memory leak in crl_set_issuers
Date:   Sun May 22 20:12:56 2022 +0200    Fix a crash in ssl_security_cert_chain
Date:   Wed Jun 22 17:05:55 2022 +0200    Fix a memory leak in EC_GROUP_new_from_ecparameters
Date:   Fri Jul 1 13:47:11 2022 +1000     Fix bn_gcd code to check return value when calling BN_one()
Date:   Tue Jul 5 20:39:06 2022 +0200     Fix a memory leak in tls13_generate_secret
```
so you see 3 in the first day, 2 + 2 in the following two days
then 1 + 1 in the following two weeks
then 0 in the following months, although I started to use 8 parallel search engines.
I'd sey I see exponential growth in the MTBF here.

While in master there is no clear direction: 
```
master:

Date:   Fri May 20 16:15:44 2022 +0200    Fix a memory leak in ec_key_simple_oct2priv
Date:   Sat May 21 07:50:46 2022 +0200    Fix a memory leak in crl_set_issuers
Date:   Sat May 21 15:41:46 2022 +0200    Fix a memory leak in X509_issuer_and_serial_hash
Date:   Sun May 22 20:12:56 2022 +0200    Fix a crash in ssl_security_cert_chain
Date:   Thu May 26 11:09:58 2022 +0100    Fix a decoder mem leak on an error path
Date:   Thu May 26 11:30:09 2022 +0100    Fix another decoder mem leak on an error path
Date:   Fri May 27 11:07:37 2022 +0100    Don't call ossl_provider_free() without first setting refcnt
Date:   Thu Jun 2 11:14:32 2022 +0100     Fix a memory leak in ossl_method_store_add()
Date:   Thu Jun 2 13:54:45 2022 +0100     CONF_modules_unload should fail if CONF_modules_finish fails
Date:   Thu Jun 2 16:50:15 2022 +0200     Check return value of ossl_parse_property()
Date:   Fri Jun 3 14:01:22 2022 +0100     Fix a mem leak in evp_pkey_copy_downgraded()
Date:   Mon Jun 6 10:32:49 2022 +0100     Don't report success from ec_export if OSSL_PARAM_BLD_to_param failed
Date:   Wed Jun 22 17:05:55 2022 +0200    Fix a memory leak in EC_GROUP_new_from_ecparameters
Date:   Tue Jun 28 09:49:17 2022 +1000    Fix memory leak in cmp_calc_protection()
Date:   Fri Jul 1 13:47:11 2022 +1000     Fix bn_gcd code to check return value when calling BN_one()
Date:   Thu Jul 7 15:03:08 2022 +1000     Fix memory leak in EVP_PKEY_get1_encoded_public_key.
Date:   Tue Jul 12 14:28:37 2022 +1000    Check for EVP_MD being NULL inside ssl.
```
There are still issues unsolved, when you look at the history in #18355

But although all these bug-fixees were pack-ported to 3.0 as well, the test run did never
run for more than a few minutes on the openssl-3.0 branch as far as I remember.

**Comment by t8m** [comment]
I've misunderstood what this question was about I thought it was about test changes to the 1.1.1 branch. We do not want other things than serious bug and security fixes there as any change even to tests only has the potential to break builds for someone.

However now I understand it is about google oss-fuzz - of course there fuzzing 1.1.1 in 32 bits would be fine. I am definitely NOT saying nobody should attempt to find and fix serious issues in 1.1.1 via fuzzing.

**Comment by guidovranken** [comment]
I've updated the PR. It now builds the following targets:

Branches `[master, OpenSSL_1_1_1-stable, openssl-3.0]` x `[x64 ASAN, x64 UBSAN, x64 MSAN, i386 ASAN]` x `[individual fuzzers (client, server, x509, ...)]`

Let me know if this is incorrect otherwise I will merge the PR.

**Comment by guidovranken** [comment]
Consider updating the [corpora](https://github.com/openssl/openssl/tree/master/fuzz/corpora) directory with the latest fuzz corpora from OSS-Fuzz (can be downloaded at oss-fuzz.com).

All the fuzzers building from the newly added branches (1.1.1, 3.0) are regarded as distinct fuzzers by OSS-Fuzz and therefore don't automatically inherit the corpora from the existing fuzzers. By updating the corpora directory, this gives the newly added fuzzers the same coverage as the old ones.

However I caution against storing and updating all the little fuzzer inputs in the main `openssl` repository, as this tends to slow down all git operations; it would be better to store the corpora in a separate repository.

**Comment by guidovranken** [comment]
> I've updated the PR. It now builds the following targets:
> 
> Branches `[master, OpenSSL_1_1_1-stable, openssl-3.0]` x `[x64 ASAN, x64 UBSAN, x64 MSAN, i386 ASAN]` x `[individual fuzzers (client, server, x509, ...)]`
> 
> Let me know if this is incorrect otherwise I will merge the PR.

Can someone from OpenSSL give their approval of these changes? Then the OSS-Fuzz PR will be merged.

**Comment by paulidale** [comment]
What needs approval?  I've approve the linked PR (unofficially).

**Comment by guidovranken** [comment]
The OSS-Fuzz PR has been merged, closing this.
