### ISSUE TITLE
openssl-3.0.7 VC-WIN32 Installed successfully

### ISSUE THREAD

**Issue by rjremedios** [openssl/openssl#19650]
Having completed the install, without any errors using the Quick start steps, in the NOTES-WINDOWS.md file, if I run the command VERSION in an OPENSSL session, I see this:

OpenSSL> version
OpenSSL 1.1.1i  8 Dec 2020
OpenSSL>

Is this correct? Should not the version be 3.x?

Thanks in advance.

**Comment by t8m** [comment]
Most probably you have multiple openssl versions installed on your system and you're running the 1.1.1i version instead of the 3.0.7 you've just installed.

**Comment by rjremedios** [comment]
@t8m I did check the Windows Environment PATH (System and User) to confirm I am pointing to the 3.0.7 install location before opening this case. My previous version was 1.0.2 so I am not sure where the 1.1.1i version came from if not from the 3.0.7 package :) . Anyway I will dig further into this. Thanks for confirming I should expect the version command in OPENSSL to output 3.0.7.
Cheers

**Comment by levitte** [comment]
May I suggest using the command `where` to find out which openssl.exe cmd finds along PATH? 

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/where

**Comment by rjremedios** [comment]
@levitte Turns out Perl has an OPENSSL executable which I wasn't aware of. Thanks.
