### ISSUE TITLE
opt_legacy_okay() does not seem to work as intended

### ISSUE THREAD

**Issue by simo5** [openssl/openssl#19662]
At least on Fedora it seem the opt_legacy_okay() always returns 1 which doesn't seem the intended behavior.

I was testing this with the pkcs11 provider where I am implementing support for providing digest functions, and was using openssl dgst ... -propquery provider=pkcs11 to test the provider.

I quickly realized that the code was always falling back to the default provider if the pkcs11 provider did not support an algorithm.

I traced it down to opt_md_silent() calling opt_legacy_okay() to check if it is ok to fallback to EVP_get_digestbyname() which does not take properties.

This is the current code in 3.0.5 (where I found this) and master:
```
int opt_legacy_okay(void)                                                                                                   
{   
    int provider_options = opt_provider_option_given();
    int libctx = app_get0_libctx() != NULL || app_get0_propq() != NULL;                                                 
#ifndef OPENSSL_NO_ENGINE
    ENGINE *e = ENGINE_get_first();                                                                        
    
    if (e != NULL) {
        ENGINE_free(e);                                                                                                
        return 1;                                                                                          
    }
#endif                                                                                                                      
    /*
     * Having a provider option specified or a custom library context or                                                                                      
     * property query, is a sure sign we're not using legacy.                                                                                    
     */
    if (provider_options || libctx)                                                                         
        return 0;                                                                                          
    return 1;                                                                                                                                
}
```

Although provider_options is set to 1 the code proceeds to list engines, and it seem it always find one: "Intel RDRAND engine"

If an engine is found, for some reason, this function immediately returns that legacy is ok.

It is unclear to me why the availability of a random engine would override the fact we have a clear indicator we are using providers.

I think this may cause issues for the FIPS provider as well, because algorithms not supported in that provider will still allow for a fallback to the default provider when it is loaded.

Fun additional fact:
at least for SHA2-512/224 and SHA2-512/224, when this fallback happens, the openssl dgst command prints a different name in the output:
```
$ openssl dgst -sha512-224 README.md
SHA2-512/224(README.md)= 8cb74a95193e054eb182d8c5ab37bfb35990c93fa654e363d5cd342a
```
vs
```
$ openssl dgst -sha512-224 -propquery "provider=pkcs11" README.md
SHA512-224(README.md)= 8cb74a95193e054eb182d8c5ab37bfb35990c93fa654e363d5cd342a
```

note that both digest were created by the default provider as the token I am testing does not support SHA2-512/224

**Comment by mattcaswell** [comment]
> It is unclear to me why the availability of a random engine would override the fact we have a clear indicator we are using providers.

Seems odd to me. I guess the idea was that if the user has explicitly loaded an engine then that takes precedence over everything....but it seems like you're not explicitly loading an engine.

**Comment by simo5** [comment]
I am definitely not loading an engine, this seem to be an always available engine for the rng? It was surprising to say the least.

**Comment by beldmit** [comment]
`RDRAND` and `dynamic` are always present as output of `openssl engine -vvvv` though not present as files

**Comment by beldmit** [comment]
yes, rdrand is a built-in engine for Intel platform. 

@openssl/otc, should we reconsider it?

**Comment by t8m** [comment]
Yeah, I'd just drop the #ifndef OPENSSL_NO_ENGINE part. IMO if someone supplies propquery or provider we should not fallback to implicit.

**Comment by simo5** [comment]
@t8m see the PR, I was already working exactly along those lines.
