### ISSUE TITLE
I'm getting a different openssl version when building from source

### ISSUE THREAD

**Issue by khezerberg** [openssl/openssl#19667]
I'm currently running a linux container on ARM-64 Little Endian and I'm not sure when the versioning numbers for ARM changed or if they were always like this but when configuring openssl to build from source I run the following on my terminal:
```shell
$ ./Configure linux-x32
```
and I get the following output:
```
Configuring OpenSSL version 3.2.0-dev for target linux-x32
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
Created include/openssl/configuration.h
```
My question is, why is it showing that version number?
I thought the latest release was 3.0.7?
I also thought that the version numbers went from 3.0.x-3.1.x-dev?
I am sorry if I annoy some of you with this question as it may seem very obvious to some but it's not obvious to me. I'm very confused right now as I cannot find anything on that version of openssl and am a little spooked out.

I just want to build the latest openssl that is not vulnerable to the critical security vulnerabilities that were patched with 3.0.7 that apparently also affect 3.x from what I've read in the changelog documentations. 

Thank you for your time and patience.

**Comment by levitte** [comment]
What is your source?

**Comment by khezerberg** [comment]
> What is your source?

git://git.openssl.org/openssl.git 

I cloned the project to build from source.

**Comment by paulidale** [comment]
Checkout out to the appropriate tag for 3.0.7: `openssl-3.0.7`
Or download the sources from our releases page: https://www.openssl.org/source/

**Comment by khezerberg** [comment]
> Checkout out to the appropriate tag for 3.0.7: `openssl-3.0.7` Or (better) download the sources from our releases page: https://www.openssl.org/source/

yes I know you can checkout specific tags but my question is why is the version number showing that? I built openssl 3.1.0-dev this year around march. is 3.2.0-dev vulnerable to the vulnerabilities patched in 3.0.7?

I was a bit spooked out because version 3.2.0 doesn't even show up in the openssl website.

**Comment by khezerberg** [comment]
> Checkout out to the appropriate tag for 3.0.7: `openssl-3.0.7` Or (better) download the sources from our releases page: https://www.openssl.org/source/

oh thank you. I will do that. I'll download it from the release page.
I think this puts me at ease for now as I was just worried about the version numbers tied to the vulnerabilities that affect 3.0.1-3.0.7 and also apparently 3.x which I take it to mean 3.1.0 and 3.2.0.

**Comment by paulidale** [comment]
My guess is you cloned the git repository and, by default, this gives the latest development revision.
After 3.1.x was branched recently, 3.2.0-dev became the new latest development version.

**Comment by mattcaswell** [comment]
> I was a bit spooked out because version 3.2.0 doesn't even show up in the openssl website.

The latest stable branch is 3.0. There are 2 versions in development at the moment, 3.1 and 3.2. The master branch is for 3.2. If you just clone the git repo and build the default branch you will get 3.2.

**Comment by khezerberg** [comment]
Thank your so much for your responses and the time you took to solve my problem. Love you all.
