### ISSUE TITLE
Unable to compile OpenSSL 3.0.5 or upper version in MAC when not using "no-threads" flag

### ISSUE THREAD

**Issue by AshishDurgapal** [openssl/openssl#19661]
I am getting given error while compiling openssl 3.0.5 with multithreaded option .

**crypto/threads_pthread.c:232:16: error: cannot compile this atomic library call yet
        *ret = __atomic_or_fetch(val, op, __ATOMIC_ACQ_REL);**

Configure command which I am using : ./configure darwin-i386-cc no-shared no-asm  no-capieng no-rc4

Everything works fine when I configured with "no-threads" option but I need openSSL for multithreaded.

No issue is observed in older versions of openssl 1.1.1k

**Comment by hlandau** [comment]
What compiler and compiler version are you using?

**Comment by AshishDurgapal** [comment]
@hlandau ,
We are using clang

clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
