### ISSUE TITLE
punycode fuzzer is running on oss-fuzz

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#19679]
The punycode fuzzer is running on oss-fuzz. I think that's a waste of resources. After 1 minute it found all coverage.

**Comment by paulidale** [comment]
It was demanded, it was done.  It would have detected the CVE early but didn't exist.  Could it do the same if the code ever receives an update?

OTC: **keep this fuzzer or remove it?**

**Comment by thesamesam** [comment]
I'm not au fait enough with oss-fuzz yet, is there a way to give it a pretty low weight?

**Comment by kroeckx** [comment]
I think having written this fuzzer is useful. But at the certain point,
running it doesn't find anything useful anymore. For this fuzzer that
seems to happen after 5 minutes.

Oss-fuzz automatically picked up this fuzzer because it uses all the
binaries in the fuzz directory. Either we should update oss-fuzz to not
run all the fuzzers, or we should do something else so that oss-fuzz
doesn't pick it up.

I don't think we should remove it.
