### ISSUE TITLE
openssl req -newkey rsa:XXX failing

### ISSUE THREAD

**Issue by AlexandreGonzalo** [openssl/openssl#19680]
Hi OpenSSL team,

I am using my own build of OpenSSL for Android

```
openssl version
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
```

```
openssl req -x509 -days 3650 -newkey rsa:4096 -keyout ca_rsa_1.key -out ca_rsa_1.der -outform DER -nodes -subj "/C=FR/ST=PACA/L=Valbonne/O=Trustonic/CN=*.trustonic.com" -extensions my_ca_extension
F8F47E5878000000:error:0700006C:configuration file routines:NCONF_get_string:no value:crypto/conf/conf_lib.c:316:group=req name=default_bits
F8F47E5878000000:error:03000093:digital envelope routines:evp_pkey_ctx_ctrl_int:**command not supported**:crypto/evp/pmeth_lib.c:1324:
```

I think that the OSSL_PKEY_PARAM_BITS parameter is incorrectly translated to cmd = 0 when pkey_rsa_ctrl() is called.

**Comment by t8m** [comment]
I cannot reproduce the issue on Linux.

Could you please attach/paste your openssl.cnf file here?

**Comment by AlexandreGonzalo** [comment]
> I cannot reproduce the issue on Linux.
> 
> Could you please attach/paste your openssl.cnf file here?

Hi Tomáš,
Same for me, I can't reproduce this issue on Linux.
I am using an engine from the OpenSC/libp11 project and when I don't load this engine, I don't have the issue anymore.
There must be something wrong with the engine.
I will check with the OpenSC team.
Thanks for your help.
Alexandre.

**Comment by t8m** [comment]
Ah, actually the use of libp11 engine explains it.

**Comment by t8m** [comment]
Hmm, this really looks like a problem with the engine as the command seems to be translated correctly to EVP_PKEY_CTRL_RSA_KEYGEN_BITS.

**Comment by AlexandreGonzalo** [comment]
Actually, the engine is not implementing the CTRL callback, so the default pkey_rsa_ctrl() is called but the given type is not EVP_PKEY_CTRL_RSA_KEYGEN_BITS but 0.
I will continue to debug and let you know if I find something.

**Comment by t8m** [comment]
Yes, if the engine is made default for RSA, key generation will be broken. So do not do this.
