### ISSUE TITLE
how to find what code of OpenSSL libs we are using

### ISSUE THREAD

**Issue by suryaanand** [openssl/openssl#19682]
Hi Team, 

We all know OpenSSL had a high vulnerability notification on Nov 1 and an updated 3.0.7 library package.
My application is from java and we deploy the same docker etc. I want to find  if any openSSL code in my project needs updates with 3.0.7. Is there any specific functionality for cryptography etc? Please suggest.
I can see

```
if [ -f "/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2" ] ;then
  mv /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 /tmp/
```

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
