### ISSUE TITLE
complie failed use clang

### ISSUE THREAD

**Issue by EasonQu** [openssl/openssl#19691]
I meet a problem when I compile openssl:

here is details:

"crypto/thread/arch/thread_posix.c:25:5: warning: implicit declaration of function 'pthread_setcancelstate' is invalid in C99 [-Wimplicit-function-declaration]
    pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
    ^
crypto/thread/arch/thread_posix.c:25:28: error: use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'
    pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
                           ^
crypto/thread/arch/thread_posix.c:26:5: warning: implicit declaration of function 'pthread_setcanceltype' is invalid in C99 [-Wimplicit-function-declaration]
    pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
    ^
crypto/thread/arch/thread_posix.c:26:27: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'
    pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);"

compile tools is x86_64-linux-android28-clang , I don`t know what I can do to fix this problem.

**Comment by paulidale** [comment]
Did you read and follow the notes in the [NOTES-ANDROID.md](https://github.com/openssl/openssl/blob/master/NOTES-ANDROID.md) file?

It's also worth reading the [INSTALL.md](https://github.com/openssl/openssl/blob/master/INSTALL.md) instructions.

If you did both of these, you need to disable threading support.  That's in those documents.

**Comment by t8m** [comment]
Try #19695 
With that you should be able to configure with no-thread-pool and it should compile fine for you.
