### ISSUE TITLE
Missing Makefile depedencies?

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#1969]
I sometimes get something like:
```
In file included from crypto/bn/asm/x86_64-gcc.c:10:0:
crypto/bn/asm/../bn_lcl.h:21:32: fatal error: internal/bn_conf.h: No such file or directory
 #  include "internal/bn_conf.h"
                                ^
compilation terminated.
In file included from crypto/bn/bn_add.c:11:0:
crypto/bn/bn_lcl.h:21:32: fatal error: internal/bn_conf.h: No such file or directory
 #  include "internal/bn_conf.h"
                                ^
compilation terminated.
In file included from crypto/bn/bn_blind.c:12:0:
crypto/bn/bn_lcl.h:21:32: fatal error: internal/bn_conf.h: No such file or directory
 #  include "internal/bn_conf.h"
                                ^
compilation terminated.
````

I was running make -j4 fuzz/server-test

I can of course run make crypto/include/internal/bn_conf.h to get it, but make depend doesn't seem to pick this up.

@levitte: Is this something you can look at?

**Comment by kroeckx** [comment]
I also got:
```
In file included from crypto/dso/dso_dlfcn.c:19:0:
crypto/dso/dso_locl.h:13:31: fatal error: internal/dso_conf.h: No such file or directory
 #include "internal/dso_conf.h"
                               ^
In file included from crypto/dso/dso_dl.c:10:0:
crypto/dso/dso_locl.h:13:31: fatal error: internal/dso_conf.h: No such file or directory
 #include "internal/dso_conf.h"
                               ^
compilation terminated.
compilation terminated.
In file included from crypto/dso/dso_openssl.c:10:0:
crypto/dso/dso_locl.h:13:31: fatal error: internal/dso_conf.h: No such file or directory
 #include "internal/dso_conf.h"
                               ^
compilation terminated.
In file included from crypto/dso/dso_lib.c:10:0:
crypto/dso/dso_locl.h:13:31: fatal error: internal/dso_conf.h: No such file or directory
 #include "internal/dso_conf.h"
                               ^
compilation terminated.
```

**Comment by levitte** [comment]
You must run `make build_generated` first.

There's a catch 22 here, and it's the in the first run, no dependencies have built up yet, so there's no material for `make` to figure out if those files need to be generated or not.  And still, they are needed by some of the C source.

One *could* claim that `Configure` should run `make`...  except `Configure` can't know what the local make program is.  It could be `make`, it could be `gmake`, it could be `bsdmake`.  On VMS, it could be `MMS`, but if could as well be `MMK`...

If you have an elegant solution to fix this, I'm all ears!

**Comment by kroeckx** [comment]
So why isn't that build_generated part of the dependency of something?

**Comment by richsalz** [comment]
or why doesn't Configure generate the necessary files?

**Comment by levitte** [comment]
@kroeckx, it is a dependency of the main building targets. Feel free to suggest more. 

@richsalz, we moved away from precisely that for various reasons, among others that rebuilding them would require a reconfiguration, which causes building.h to be rebuilt, which causes a much larger rebuild of everything that ultimately depends on that one.

**Comment by kroeckx** [comment]
There are times I only want to build a certain app, one of the
test binaries, one of the fuzz binaries, or maybe the libraries.

**Comment by levitte** [comment]
As a compromise, I could make it so that all C files in crypto/bn are set to depend on bn_conf.h, all in crypto/dso on dso_conf.h and so on... That would fix your problem without us getting too excessive rebuilds.

**Comment by levitte** [comment]
On the other hand, there's really only one time when you should need to do `make build_generated`, and that's the first time you've checked out a new work directory.  After that, all necessary dependencies should be generated along with your builds.

So while I'm on the one hand thinking that we can make things just a teeny bit more helpful for this case, it will also attract the protests from those who don't like excessive rebuilds.  Part of me wants to go Pooh ("oh bother").

(*oh, and I haven't gone into `opensslconf.h` yet...*)

**Comment by levitte** [comment]
Just an update, I *may* have found a way.  It involves having specific targets being run before a selection of object files get compiled.  For example (and very simplistically), something like this could be generated for all crypto/bn/*.o:

``` make
crypto/bn/whatever.o: $(SRCDIR)/crypto/bn/whatever.c
	$(MAKE) crypto/include/internal/bn_conf.h include/openssl/opensslconf.h
	$(CC) -o crypto/bn/whatever.o -c $(SRCDIR)/crypto/bn/whatever.c
```

This will ensure that the generated header files will in fact be generated prior to any compilation happening, ensuring their presence even if dependencies didn't get them built automagically.

This *will* have a small impact on building time, but that may be worth it to reduce these kinds of questions.

Otherwise, my option is to make a select amount of object files depend on each generated header file.  Unfortunately, that means *all* of them for `include/openssl/opensslconf.h`, meaning that any time you reconfigure, you would rebuild *everything*.

**Comment by richsalz** [comment]
There are other tools to cut down building time.  *Use ccache.*  I don't think this is worth fixing for what that's worth.

**Comment by levitte** [comment]
Too late.  @kroeckx, would you mind trying #1976?

I figured that it's not the first time I've seen this very kind of question, and it won't be the last.  Fixing it or keep on fending that eternal question?  In that perspective, fixing is still worth it.

**Comment by levitte** [comment]
So #1976 wasn't as brilliant as I hoped.  The other option, instead of having a sub-make to generate those headers is to add them as extra dependencies instead.  *That will mean having all object files depend on `opensslconf.h`*, I hope you're all aware of this.

Otherwise, I'll leave this be and leave it to someone else to solve unless someone comes up with a better idea, 'cause I'm out of them...

**Comment by richsalz** [comment]
@kroeckx I am closing this.  Feel free to re-open, of course, but it seems like the "solutions" are far worse than the work-around.

**Comment by tanzislam** [comment]
This write-up may be relevant: http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/
