### ISSUE TITLE
Bad integer in asn1parse

### ISSUE THREAD

**Issue by harmjanblok** [openssl/openssl#19696]
I'm trying to understand the difference in `asn1parse` between openssl versions 1.0 and 1.1. Versions 1.1 and newer return a `BAD INTEGER` while 1.0 parsed the integer.

```bash
$ openssl version
OpenSSL 1.0.1k 8 Jan 2015

$ echo 'AgT/pBR1' | openssl asn1parse
    0:d=0  hl=2 l=   4 prim: INTEGER           :-5BEB8B
```

```bash
$ openssl version
OpenSSL 1.1.1n  15 Mar 2022

$ echo 'AgT/pBR1' | openssl asn1parse
    0:d=0  hl=2 l=   4 prim: INTEGER           :BAD INTEGER:[FFA41475]
```

**Comment by levitte** [comment]
That string is complete rubbish.  It's certainly not valid DER!  That 1.0.x accepted it (i.e. made an uneducated guess) was wrong, and clearly a bug.

``` console
$ echo 'AgT/pBR1' | od -t x1
0000000 41 67 54 2f 70 42 52 31 0a
0000011
```

The tag byte `41` means `APPLICATION 1`, which is undefined in this context, and the length byte `67` means that there should be 103 (= hex 67) bytes of data, which there is clearly not.

I played with PKI Inspector using the hex code of that string, and well, you can see for yourself:

https://asn1.io/PKI-inspector/default.aspx?databin=H4sIAAAAAAAEAHNMD9EvcAoy5AIABLTRVQkAAAA%3d&op=H4sIAAAAAAAEAFWMwQqDQAxE%2fyVnD%2fa6N1v0VhTsDwSNuJBulmyKldJ%2fN0Ivvcxh5s37wIA7C84QFuRCFdzxfVtRCwS41DVU0DDL1qrK2f2ga7TRtBN9ojnIlGbKZyTzRz8Z%2fe1Yphh9GFfZ%2bmxRkmsgmL7c9dgzOQPfA9rjLw2MAAAA

I'm rather amazed that OpenSSL ASN.1 parser actually tries to decode an integer from this!

**Comment by harmjanblok** [comment]
@levitte thanks for the in-depth explanation. Shouldn't the string be base64 decoded first?

```bash
$ echo 'AgT/pBR1' | base64 --decode | od -t x1
0000000    02  04  ff  a4  14  75
0000006
```

Although this still incorrect; PKI Inspector says 'Redundant leading byte(s) in the Value'.

**Comment by harmjanblok** [comment]
@levitte thanks a lot! Interesting detail on the redundant `ff`.

One remaining question is if there is a possibility to add a configuration to the `openssl.cnf` to be less strict.

In this specific case our supplier needs to provide an update, a configuration override would allow us to use a newer openssl version in the mean time.

**Comment by t8m** [comment]
No, unfortunately this behavior is not configurable.
