### ISSUE TITLE
Why is Ed25519 not implemented using radix-$2^{64}$ or radix-$2^{51}$ finite field layer?

### ISSUE THREAD

**Issue by Ji-Peng** [openssl/openssl#19702]
`crypto/ec/curve25519.c` is the source code of X25519 and Ed25519 implementation. The macro `X25519_ASM` and the specific software/hardware environment are used to decide if X25519 uses radix-$2^{64}$ (`fe64` type), radix-$2^{51}$ (`fe51` type), or radix-$2^{25.5}$ (`fe` type) finite field implementation.

But Ed25519's finite field layer is always implemented using only radix-$2^{25.5}$ (`fe` type) version.

I'm planning to develop an Ed25519 implementation using radix-$2^{64}$ or radix-$2^{51}$ finite field layer. Therefore, I'd like to know:
- Why is Ed25519 not implemented using radix-$2^{64}$ or radix-$2^{51}$ finite field layer?
- Are there other potential considerations?

**Comment by paulidale** [comment]
Did you find this code: https://github.com/openssl/openssl/blob/master/crypto/ec/asm/x25519-x86_64.pl ?

However, any faster implementation will always be considered.

**Comment by davidben** [comment]
@paulidale That's X25519, not Ed25519. I believe OpenSSL's Ed25519 is indeed always radix 25.5, which leaves a ton of perf on the table on 64-bit platforms.

**Comment by Ji-Peng** [comment]
I'm planning to develop a faster Ed25519 implementation with radix-64 or radix-51. I found that the existing X25519 implementation to be sub-optimal from a code size perspective. The basic pattern of `crypto/ec/curve25519.c` is as follows.
```c
#if defined(X25519_ASM) && (defined(__x86_64) || defined(__x86_64__) || \
                            defined(_M_AMD64) || defined(_M_X64))
# define BASE_2_64_IMPLEMENTED

// radix-64 finite filed implementation, i.e., fe64 type.

#endif

#if defined(X25519_ASM) \
    || ( (defined(__SIZEOF_INT128__) && __SIZEOF_INT128__ == 16) \
         && !defined(__sparc__) \
         && (!defined(__SIZEOF_LONG__) || (__SIZEOF_LONG__ == 8)) \
         && !(defined(__ANDROID__) && !defined(__clang__)) )
# define BASE_2_51_IMPLEMENTED

// radix-51 finite field implementation, i.e., fe51 type.

#endif

// radix-25.5 finite field implementation, i.e., fe type. This implementation is not wrapped by any conditional macros.

```

In a specific environment, it is possible for the `fe64` type and `fe51` type to exist at the same time.
The point that can be improved by refactoring the code is that if the `fe64` type exists then `fe51` type can not exist, which can reduce the code size.

After the Ed25519 is implemented using `fe64` type or `fe51` type. The ideal pattern of `curve25519.c` should be something like:

```c
#if defined(X25519_ASM) && (defined(__x86_64) || defined(__x86_64__) || \
                            defined(_M_AMD64) || defined(_M_X64))
# define BASE_2_64_IMPLEMENTED

// radix-64 finite field implementation and corresponding X25519/Ed25519 implementation.

#elif defined(X25519_ASM) \
    || ( defined(INT128_MAX) \
         && !defined(__sparc__) \
         && (!defined(__SIZEOF_LONG__) || (__SIZEOF_LONG__ == 8)) \
         && !(defined(__ANDROID__) && !defined(__clang__)) )
# define BASE_2_51_IMPLEMENTED

// radix-51 finite field implementation and corresponding X25519/Ed25519 implementation.

#else

// radix-25.5 finite field implementation and corresponding X25519/Ed25519 implementation.

#endif
```

In this way, only one of `fe64`, `fe51`, and `fe` can exist at the same time.

Do you have any opinions?
