### ISSUE TITLE
The crash happened outside the Java Virtual Machine in native code. Problematic frame: # C  [libssl.so.10+0x42680]  SSL_read+0x0

### ISSUE THREAD

**Issue by mmsoundher** [openssl/openssl#19701]
Hi Team,

We are using  OpenSSL 1.0.2k-fips with java version "1.8.0_151" in redhat 7.9 OS. we observed JVM crash once or twice in a month due to the problematic frame libssl.so.10+0x42680. I just want to know whether this crash occurs due to some issue with openssl 1.0.2k-fips native code or not.

Please find below jvm crash log details:
 A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x00007efe45160680, pid=4040, tid=0x00007efd633ea700
 JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libssl.so.10+0x42680]  SSL_read+0x0
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by mattcaswell** [comment]
> I just want to know whether this crash occurs due to some issue with openssl 1.0.2k-fips native code or not.

There's not enough information here to work out what the problem is. However 1.0.2 is no longer supported (unless you have a premium support contract).

**Comment by mmsoundher** [comment]
Hi,
Thanks for the quick response.                                                                                                                                                   Please check below stuff from jvm crash logs.. i hope this would help you to analyze in depth. And also i would like to know that which openssl version i can use in RHEL 7.9 since 1.0.2 is no longer supported for non premium users.

jvm crash logs:
Stack: [0x00007efd6336a000,0x00007efd633eb000],  sp=0x00007efd633e92e8,  free space=508k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libssl.so.10+0x42680]  SSL_read+0x0
C  0xe056d1d969657365

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 11694  org.apache.tomcat.jni.Socket.recvb(JLjava/nio/ByteBuffer;II)I (0 bytes) @ 0x00007efeaafa1ddb [0x00007efeaafa1d80+0x5b]
J 17736 C2 org.apache.tomcat.util.net.AprEndpoint$AprSocketWrapper.fillReadBuffer(ZLjava/nio/ByteBuffer;)I (445 bytes) @ 0x00007efeabe0de9c [0x00007efeabe0da00+0x49c]
J 17254 C2 org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (229 bytes) @ 0x00007efeaab774e4 [0x00007efeaab769a0+0xb44]
J 13245 C2 org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Lorg/apache/tomcat/util/net/SocketWrapperBase;Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (1172 bytes) @ 0x00007efeab42abd0 [0x00007efeab429780+0x1450]
J 18197 C2 org.apache.tomcat.util.net.SocketProcessorBase.run()V (35 bytes) @ 0x00007efeaaaf9128 [0x00007efeaaaf8f60+0x1c8]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run()V+4
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

**Comment by mmsoundher** [comment]
> > I just want to know whether this crash occurs due to some issue with openssl 1.0.2k-fips native code or not.
> 
> There's not enough information here to work out what the problem is. However 1.0.2 is no longer supported (unless you have a premium support contract).

Hi,
Thanks for the quick response. Please check below stuff from jvm crash logs.. i hope this would help you to analyze in depth. And also i would like to know that which openssl version i can use in RHEL 7.9 since 1.0.2 is no longer supported for non premium users.

jvm crash logs:
Stack: [0x00007efd6336a000,0x00007efd633eb000], sp=0x00007efd633e92e8, free space=508k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C [libssl.so.10+0x42680] SSL_read+0x0
C 0xe056d1d969657365

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 11694 org.apache.tomcat.jni.Socket.recvb(JLjava/nio/ByteBuffer;II)I (0 bytes) @ 0x00007efeaafa1ddb [0x00007efeaafa1d80+0x5b]
J 17736 C2 org.apache.tomcat.util.net.AprEndpoint$AprSocketWrapper.fillReadBuffer(ZLjava/nio/ByteBuffer;)I (445 bytes) @ 0x00007efeabe0de9c [0x00007efeabe0da00+0x49c]
J 17254 C2 org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (229 bytes) @ 0x00007efeaab774e4 [0x00007efeaab769a0+0xb44]
J 13245 C2 org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Lorg/apache/tomcat/util/net/SocketWrapperBase;Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (1172 bytes) @ 0x00007efeab42abd0 [0x00007efeab429780+0x1450]
J 18197 C2 org.apache.tomcat.util.net.SocketProcessorBase.run()V (35 bytes) @ 0x00007efeaaaf9128 [0x00007efeaaaf8f60+0x1c8]
j java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run()V+4
j java.lang.Thread.run()V+11
v ~StubRoutines::call_stub

**Comment by t8m** [comment]
I would suggest reporting this issue to Red Hat support.

You cannot replace system openssl library with another version.

**Comment by mmsoundher** [comment]
sure. Thanks a lot.
