### ISSUE TITLE
Configure fail on windows10 for openssl 3.0.5

### ISSUE THREAD

**Issue by moulidheek** [openssl/openssl#19707]
I was trying to run installation from Cmake ExternalProject_Add() . But on configure stage it was failing with the following lines.

Performing configure step for 'openssl_external'
  This version of D:\17-6-2022\main\src\external\openssl\config.com is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

My CMake code for installation : 
```
 ExternalProject_Add(
      openssl_external
      PREFIX openssl
      SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}"
	  CONFIGURE_COMMAND ${OPENSSL_CONFIGURE_COMMAND}
	  --prefix=${OPENSSL_INSTALL_DIR}
	  --openssldir=${OPENSSL_DATA_DIR}
	  --libdir=${OPENSSL_LIB_DIR}
	  no-shared
	  BUILD_COMMAND make
	  TEST_COMMAND ""
	  INSTALL_COMMAND make install
	  INSTALL_DIR ${OPENSSL_INSTALL_DIR}
      BUILD_IN_SOURCE 0)
```

This is working fine in Ubuntu . when i try to install the same in windows , its failing

**Comment by levitte** [comment]
I assume you've set something like this:

``` cmake
SET(OPENSSL_CONFIGURE_COMMAND config.com)
```

This is *completely* wrong, that's not a Windows command script, it's a [VMS](https://vmssoftware.com) command script.

Please use this for the configuration command:

``` cmake
SET(OPENSSL_CONFIGURE_COMMAND "perl Configure")
```

**Comment by moulidheek** [comment]
> I assume you've set something like this:
> 
> ```cmake
> SET(OPENSSL_CONFIGURE_COMMAND config.com)
> ```
> 
> This is _completely_ wrong, that's not a Windows command script, it's a [VMS](https://vmssoftware.com) command script.
> 
> Please use this for the configuration command:
> 
> ```cmake
> SET(OPENSSL_CONFIGURE_COMMAND "perl Configure")
> ```

Thanks for levitte. 

```
set(OPENSSL_INSTALL_DIR ${CMAKE_BINARY_DIR}/install)
set(OPENSSL_INCLUDE_DIR ${OPENSSL_INSTALL_DIR}/include)
set(OPENSSL_LIB_DIR ${OPENSSL_INSTALL_DIR}/lib)
set(OPENSSL_DATA_DIR ${OPENSSL_INCLUDE_DIR}/openssl-data)
set(OPENSSL_CONFIGURE_COMMAND ${CMAKE_CURRENT_LIST_DIR}/config)
```

these are the set commands i have used. We dont have perl installed in our windows. so its suggested to use config file and also it mentioned that i have to mention the Architecture version with perl Configure command. so its suggested in online forums to use ./config which will run config.com file to set the architecture os version automatically.

**Comment by levitte** [comment]
Yeah, the `config` script (without `.com`) is Unix only, and I can see how it gets conflated with `config.com`on Windows.

The `config` script (or `config.com`) is not for Windows, has never been, and with OpenSSL 3.0 (in fact, all the way back to 1.1.0), that's pretty much a legacy script, exactly because of this sort of confusion.

We did update the configuration scripts so that `Configure` would guess the correct architecture given Perl's setup, but that was after 3.0.5.  You should upgrade to 3.0.7 anyway, because security bug fix.

> We dont have perl installed in our windows.

You must, that's a base requirement to build OpenSSL.

**Comment by moulidheek** [comment]
> 

Thank you @levitte 

I will update openssl to 3.0.7 and try with perl Configure command. Have a good day :-)
