### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by AndersBillLinden** [openssl/openssl#1970]
Running GNU Make 3.82.90 Built for i686-pc-mingw32, I first encounter this error:

Parameter is incorrect

make (e=87): The parameter is incorrect.
Makefile:210: recipe for target 'depend' failed

````
# We check if any depfile is newer than Makefile and decide to
# concatenate only if that is true.
depend:
    @: 
    @if egrep "^# DO NOT DELETE THIS LINE" Makefile >/dev/null && [ -z "`find $(DEPS) -newer Makefile 2>/dev/null; exit 0`" ]; then :; else \
      ( $(PERL) -pe 'exit 0 if /^# DO NOT DELETE THIS LINE.*/' < Makefile; \
        echo '# DO NOT DELETE THIS LINE -- make depend depends on it.'; \
        echo; \
        for f in $(DEPS); do \
          if [ -f $$f ]; then cat $$f; fi; \
        done ) > Makefile.new; \
      if cmp Makefile.new Makefile >/dev/null 2>&1; then \
        rm -f Makefile.new; \
      else \
        mv -f Makefile.new Makefile; \
      fi; \
    fi
    @:
````
Line 210 is the @: after depend:. If I clear the rule, only leaving `depend:`, running make now compiles a lot of source files and ultimately results in a file rc.o being missing:

```
gcc.exe: error: rc.o: No such file or directory
Makefile.shared:296: recipe for target 'link_shlib.mingw' failed
make[2]: *** [link_shlib.mingw] Error 1
make[2]: Leaving directory 'D:/projekt/open_source/git/sub_repos/openssl'
Makefile:716: recipe for target 'libcrypto.dll.a' failed
make[1]: *** [libcrypto.dll.a] Error 2
make[1]: Leaving directory 'D:/projekt/open_source/git/sub_repos/openssl'
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

```
What I look further up I see this line:

C:/Program Files/Git/usr/bin/perl ./util/mkrc.pl libcrypto-1_1.dll | windres --target=pe-i386 -o rc.o

so having a space in the directory name makes the build fail.

**Comment by levitte** [comment]
Yes. Make implementations generally don't treat spaces in file names very well. 

In what kind of shell are you running your build?

**Comment by mattcaswell** [comment]
No response to @levitte's question and this is now very old with no movement. Closing.

**Comment by levitte** [comment]
I misread part of the original complaint, which was about this line:

```
        @:
```

Not sure why that fails, `:` is simply a no-op command in a POSIX shell.

As for the space in the perl command, it *is* actually possible to handle that.
