### ISSUE TITLE
PKCS12_parse_ex

### ISSUE THREAD

**Issue by pm-cfs** [openssl/openssl#19718]
There should be a `PKCS12_parse_ex` that allows setting the parser library context and/or property query to match similar functions introduced with OpenSSL 3's providers. Similar functions already exist within the PKCS12 namespace such as `PKCS12_create_ex` and `PKCS12_init_ex`.

If there is agreement, I can submit a simple PR that maintains backwards compatibility.

**Comment by mattcaswell** [comment]
Probably we should modify the PKCS12 structure to store the libctx/propq passed to `PKCS12_create_ex` so that it can be subsequently reused in `PKCS12_parse` without requiring a `PKCS12_parse_ex`.

**Comment by pm-cfs** [comment]
Except there is no way to set the libctx/propq on a loaded PKCS12 structure (`d2i_PKCS12_bio` and `d2i_PKCS12_fp`).
Looking at how `d2i_PKCS12_bio` is implemented, it uses `ASN1_item_d2i_bio`; there is already a `ASN1_item_d2i_bio_ex` but no friendly interface for it in PKCS12, but you can make it work with a simple cast.

If we went that route, it also means that you need to know the libctx/propq you want to use for parsing when you open/create the file. If you were to open it, analyze it and see it required legacy encryption, there is no way to change the libctx/propq for parsing without resorting to internal structures. Of course, you can close and reopen with the desired libctx/propq, but seems a bit limiting given how libctx/propq are handled elsewhere.

**Comment by slontis** [comment]
Have a closer look and you will see the following has been implemented:

````
p12 = PKCS12_init_ex(mode, ctx, propq);
p12 = d2i_PKCS12_bio(in, &p12);
````

This is the technique that has also been used for other objects.. i.e we create a object that contains a libctx/propq and then pass that to the d2i as an input. this is then stored within a PKCS7_CTX within  p12->authsafes

The problem with the PKCS12 code is that is composed of a whole lot of disjointed objects which dont know about the context.

**Comment by slontis** [comment]
i.e. Having a PKCS12_parse_ex() with a libctx is already too late.. The p12 object has already been loaded. The current method is trying to make it so you do not attempt to mutate the libctx/propq part way thru.
