### ISSUE TITLE
how to generate multiple private keys and certifications in a shot time？

### ISSUE THREAD

**Issue by fengmao31** [openssl/openssl#19711]
I want to generate multiple private keys and certifications in a shot time. It means it is not a good idea to generate one by one. I know it can share some processes or parameters to generate multiple private keys and certication. It can make the generation fastly.

But I donnot know how to progarm with openssl command. I can take some risks to reduce the secure because I use them to build socket connection to one streaming media server in same device.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
