### ISSUE TITLE
library is missing or cannot be opened: "libcrypto.so.1.1"

### ISSUE THREAD

**Issue by Joeldev1021** [openssl/openssl#19712]
hi, i done update manjaro linux, i try run test with mongo-memory-server show this error 

Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"

**Comment by levitte** [comment]
It looks like Manjaro Linux now ships with OpenSSL 3.0, which means you will need to recompile your program.

Ref: https://forum.manjaro.org/t/stable-update-2022-11-14-kernels-gnome-43-1-plasma-5-26-3-systemd-251-8-firefox-106-0-5-thunderbird-lxqt/126824
