### ISSUE TITLE
Issue installing OpenSSL 3

### ISSUE THREAD

**Issue by ceemoneyx** [openssl/openssl#19717]
Hoping someone can help me with an issue I'm having trying to install Open SSL 3.0 on my Raspberry Pi. I've compiled the code and installed (uninstalling current versions first). It seems to have installed as when I run `openssl version` it reads out: `Open SSL 3.0.0 17 Sept`

However when running `dpkg -l openssl` I get:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-fules/Unpacked/half-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/     Name                Version                              Architecture      Description
+++-============-===================-============-===================
ii     openssl		1.1.1n-0+deb11u3+rpt1	armhf		Secure Sockets Layer toolkit….

```

Not sure what I did wrong here, I've tried uninstalling openssl and re-compiling 3.0 but still leaves me in the same place.

**Comment by levitte** [comment]
That's the output you get for a perfectly healthy installation.
The first column (`i`) says that it was desired to be installed
The second column (`i`) says that it is indeed installed
The third column (` `) says that there are no errors

**Comment by ceemoneyx** [comment]
Yes but it's telling me that version 1.1.1 is installed and not 3.0? despite me downloading and compiling the code for 3.

 I need 3.0 because the program I'm running keeps giving me the error that "openssl 3.0.0 or higher is required"
