### ISSUE TITLE
[QUESTION][VULNERABILITY] Openssl in ios app

### ISSUE THREAD

**Issue by jhay06** [openssl/openssl#19722]
Hi ,
   Would like to ask if openssl uses srand and random in any of the codes ? 

I have an ios app that uses openssl,  and per immuniweb , 
we found out that there's a vulnerability found in the app 
Just want to confirm if openssl use those 2 codes 
![image](https://user-images.githubusercontent.com/5191437/202946661-fac1b571-2a50-4cb5-b18a-c06faabde586.png)

**Comment by paulidale** [comment]
OpenSSL does not use these calls.

**Comment by jhay06** [comment]
> OpenSSL does not use these calls.

Hi @paulidale , thanks for the response,
but unfortunately i dig some of the openssl codes and saw this line 

![image](https://user-images.githubusercontent.com/5191437/202952097-825407d4-5baa-4553-a030-bf48c4823a72.png)

**Comment by paulidale** [comment]
This use is not security relevant, it's simply burning some CPU cycles.  We use low quality RNGs in other places -- again none are security relevant.

**Comment by jhay06** [comment]
> This use is not security relevant, it's simply burning some CPU cycles. We use low quality RNGs in other places -- again none are security relevant.

noted on this , don't worry this is just to confirm if openssl uses the function "random" and "srand" because we need to defend the findings in the company infosec , and as you said , this is not security relevant . i think  it's enough for the company to tagged the findings as False positive thank you very much :)

**Comment by jhay06** [comment]
will close this now , will reopen this issue if we need some clarification regarding the usage of those codes in openssl if you don't mind , again thank you very much .
