### ISSUE TITLE
openssl sha1 hmac generation fails with no default digest error

### ISSUE THREAD

**Issue by bigbellyburger** [openssl/openssl#19727]
Using OpenSSL 3.0.7 on Arch Linux:

```
➜ ~ openssl version 
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
```

Using OpenSSL to generate a a sha1 hmac produces the following error:

```
➜ ~ echo test | openssl sha1 -hex -hmac abc
Error setting context
4027C592227F0000:error:0300009E:digital envelope routines:do_sigver_init:no default digest:crypto/evp/m_sigver.c:284:
```

The same happens for `openssl sha256 -hmac` and `openssl sha512 -hmac`

**Comment by t8m** [comment]
Thank you for the report. This was already fixed with PR #19606

**Comment by bchoii** [comment]
For anyone encountering the same issue, a workaround is to explicitly declare the digest.
```
~ echo test | openssl dgst -sha1 -hex -hmac abc
```

**Comment by bchoii** [comment]
Note that you can try declaring the digest explicitly.
```
echo test | openssl dgst -sha1 -hex -hmac abc
```

**Comment by bchoii** [comment]
Workaround: the digest can be declared explicitly.
```
echo test | openssl dgst -sha1 -hex -hmac abc
```
