### ISSUE TITLE
`i2d_PUBKEY()` and `i2d_PrivateKey()` are missing their prototype in `<openssl/x509.h>`

### ISSUE THREAD

**Issue by nicowilliams** [openssl/openssl#19733]
`i2d_PUBKEY()` is documented in `doc/man3/X509_PUBKEY_new.pod`, but there is no prototype for it in any public header.

Ditto `i2d_PrivateKey()`.

`i2d_PUBKEY_fp()` and `i2d_PUBKEY_bio()` and so on are also documented, but they do have prototypes in `<openssl/x509.h>`.

**Comment by t8m** [comment]
The prototype is declared by macro.
See `DECLARE_ASN1_ENCODE_FUNCTIONS_only_attr()` in asn1.h.

**Comment by nicowilliams** [comment]
Oh, thanks, so I wasn't including the correct header.  Thanks.
