### ISSUE TITLE
openssl enc -S behavior changed in 3.0 producing files not readable with 1.1.1

### ISSUE THREAD

**Issue by Iridias** [openssl/openssl#19730]
Here is a way to demonstrate and reproduce the issue.

First verify openssl version and prepare the environment on the host:
```
host> openssl version
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)

host> mkdir /tmp/openssl-test

host> echo 'Just say narf.
Just say narf!
Just say NARF!' > /tmp/openssl-test/test-input.txt

host> cat /tmp/openssl-test/test-input.txt
Just say narf.
Just say narf!
Just say NARF!

host> docker run --name ubuntu2 -d -v /tmp/openssl-test:/mnt -it ubuntu:18.04
host> docker exec -it ubuntu2 bash
```

Check openssl version in the container and encrypt the files (also verify that decryption works):
```
container> apt update && apt install openssl
container> openssl version
OpenSSL 1.1.1  11 Sep 2018

container> ls -alFh /mnt/
total 8.0K
drwxr-xr-x 2 1000 1000   60 Nov 22 12:45 ./
drwxr-xr-x 1 root root 4.0K Nov 22 12:43 ../
-rw-r--r-- 1 1000 1000   45 Nov 22 12:46 test-input.txt

container> cat /mnt/test-input.txt
Just say narf.
Just say narf!
Just say NARF!

container> openssl enc -p -aes256 -a -S CEED -pbkdf2 -iter 20000 -pass pass:NARF -in /mnt/test-input.txt -out /mnt/test-output.enc
hex string is too short, padding with zero bytes to length
salt=CEED000000000000
key=F3F404D5ABC2D888ADD1133ED9B3CCA77E4317369462D16FE70539643184E21D
iv =D00113672386E8CE59518BECD6835719

container> cat /mnt/test-output.enc
U2FsdGVkX1/O7QAAAAAAAMafQdZAkgr0JVD+lONLKNvB55ZaEaJz1hQUKIt2tIom
1XhCTf4axktE6CkX+j9mDQ==

container> openssl enc -d -p -aes256 -a -S CEED -pbkdf2 -iter 20000 -pass pass:NARF -in /mnt/test-output.enc -out /mnt/test-decrypt.txt.v1
salt=CEED000000000000
key=F3F404D5ABC2D888ADD1133ED9B3CCA77E4317369462D16FE70539643184E21D
iv =D00113672386E8CE59518BECD6835719

container> cat /mnt/test-decrypt.txt.v1
Just say narf.
Just say narf!
Just say NARF!
``` 

Decrypt the file on the host:
``` 
host> openssl enc -d -p -aes256 -a -S CEED -pbkdf2 -iter 20000 -pass pass:NARF -in /tmp/openssl-test/test-output.enc -out /tmp/openssl-test/test-decrypt.txt.v3
hex string is too short, padding with zero bytes to length
salt=CEED000000000000
key=F3F404D5ABC2D888ADD1133ED9B3CCA77E4317369462D16FE70539643184E21D
iv =D00113672386E8CE59518BECD6835719

host> cat /tmp/openssl-test/test-decrypt.txt.v3
KG^:���7▒��=AmV��
                 gf�����Ʞ�]Sust say narf!
Just say NARF!
``` 
-> **The first few bytes of the output are corrupted / garbage**

Try again with openssl 3 only:
``` 
host> openssl enc -p -aes256 -a -S CEED -pbkdf2 -iter 20000 -pass pass:NARF -in /tmp/openssl-test/test-input.txt -out /tmp/openssl-test/test-output.enc.v3
hex string is too short, padding with zero bytes to length
salt=CEED000000000000
key=F3F404D5ABC2D888ADD1133ED9B3CCA77E4317369462D16FE70539643184E21D
iv =D00113672386E8CE59518BECD6835719

host> cat /tmp/openssl-test/test-output.enc.v3
xp9B1kCSCvQlUP6U40so28HnlloRonPWFBQoi3a0iibVeEJN/hrGS0ToKRf6P2YN

host> openssl enc -d -p -aes256 -a -S CEED -pbkdf2 -iter 20000 -pass pass:NARF -in  /tmp/openssl-test/test-output.enc.v3 -out /tmp/openssl-test/test-v3-decrypt.txt
hex string is too short, padding with zero bytes to length
salt=CEED000000000000
key=F3F404D5ABC2D888ADD1133ED9B3CCA77E4317369462D16FE70539643184E21D
iv =D00113672386E8CE59518BECD6835719

host> cat /tmp/openssl-test/test-v3-decrypt.txt
Just say narf.
Just say narf!
Just say NARF!
``` 

_Host OS_: Arch Linux
_Host openssl version_: OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
_Container OS_: Ubuntu 18.04
_Container openssl version_: OpenSSL 1.1.1  11 Sep 2018

**Comment by t8m** [comment]
Thank you for the report. I can confirm this. Interestingly enough v3 is compatible with itself which probably means we won't be able to fix it by just reverting to the 1.1.1. We will have to introduce some backwards compat option to 3.0.

**Comment by mattcaswell** [comment]
Hmmm....what changed to break this?

**Comment by t8m** [comment]
Hm... it is the salt handling that changed this.

**Comment by t8m** [comment]
Actually the 1.1.1 encrypted file is possible to decrypt with 3.0 without problems - just drop the -S option from the command line.

**Comment by t8m** [comment]
So in the end I see it rather as a documentation issue.

**Comment by t8m** [comment]
To generate files readable with 1.1.1 you must not use -S option - which means generate a random salt and write it to the file.

**Comment by t8m** [comment]
The #4486 changed the behavior.

**Comment by Iridias** [comment]
Sorry for the late response.

> Actually the 1.1.1 encrypted file is possible to decrypt with 3.0 without problems - just drop the -S option from the command line.

Indeed that works.

> To generate files readable with 1.1.1 you must not use -S option.

That would be quite a hassle. Our current use-case is, that there is an app, that encrypts the files before pushing them in a private git-repo (and vice-versa). With a random salt, all files would be always recognized as changed, not only those that actually changed. For our case, the "auditability" is more important than the additional security gained by a random salt.

If the behavior of the "-S" option stays that way, we'd need a data-migration (and ensure, that the used openssl-version stays at version >=3.x)

**Comment by t8m** [comment]
I do not think we will change the behavior again as that would create incompatibility within the released minor versions.

Do you always use the same salt for all the files? If so then this has the same (bad) security properties as using -nosalt which should behave the same on 1.1.1 and 3.0.

**Comment by csware** [comment]
Not being able to use a fixed salt also break CICD pipelines relying on reproducible data.

**Comment by michael-db** [comment]
This problem just cost me a lot of time investigating. In my case, the motivation to use a fixed salt is to keep most of the base64 ciphertext the same when encrypting plain text which extends the existing plain text, i.e., with a common prefix. This means the same salt is used only for one (evolving) file, so it has a security value compared to -nosalt.

That might be unusual, but disregarding such specific use cases, this change was certainly a mistake. Someone somewhere will have lost the salt they used and, when they discover that it can no longer be recovered from the output, i.e., that they needed to keep the salt along with the password, there will be tears...
