### ISSUE TITLE
dgst command should use provider-keymgmt functions for dealing with private keys

### ISSUE THREAD

**Issue by Akretsch** [openssl/openssl#19742]
I am currently writing my own provider implementation to wrap the access to an external signature server.
Here the private key used for signature is not accessible. 
Unfortunately the `openssl dgst` app always uses the OSSL_OP_STORE/provider-storemgmt functions and not the OSSL_OP_KEYMGMT/provider-keymgmt functions (e.g. OSSL_FUNC_keymgmt_load()) to load and pass private keys.  As result the private key must be always loadable from file system and cannot be just an abstract reference.

**Comment by t8m** [comment]
Store can be anything, it does not necessarily have to be a file system store. Store handles URIs - if you invent a new URI scheme for your provider you can make it called via the store call with the URI scheme.

See for example the recently added winstore store provider that adds windows certificate store support.

You need to reference the key in one way or another anyway.

**Comment by Akretsch** [comment]
But in any case I have to provide the byte sequence of a real private key  to make the apps.c:load_key() function happy?

**Comment by t8m** [comment]
No, you don't. The store can create a key reference that is valid within your provider only.

**Comment by t8m** [comment]
And you do not need to provide a keymgmt export function.
