### ISSUE TITLE
Unable to Compile OpenSSL 3.0.7 in RHEL 6.10 Machine

### ISSUE THREAD

**Issue by mahender08** [openssl/openssl#19740]
Hi Team,

Please assist in fixing the compile error listed below.
[](url)
Command used: ./config enable-fips --prefix=/usr/local/ssl --openssldir=/usr/local/ssl --release no-shared

[MKAdmin@RHELMK openssl-3.0.7]$ ./config enable-fips --prefix=/usr/local/ssl --openssldir=/usr/local/ssl --release no-shared
Can't locate IPC/Cmd.pm in @INC (@INC contains: /home/MKAdmin/openssl-3.0.7/util/perl /usr/local/lib/perl5 /usr/local/share/perl5 /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5 /usr/share/perl5 . /home/MKAdmin/openssl-3.0.7/external/perl/Text-Template-1.56/lib) at /home/MKAdmin/openssl-3.0.7/util/perl/OpenSSL/config.pm line 19.
BEGIN failed--compilation aborted at /home/MKAdmin/openssl-3.0.7/util/perl/OpenSSL/config.pm line 19.
Compilation failed in require at /home/MKAdmin/openssl-3.0.7/Configure line 23.
BEGIN failed--compilation aborted at /home/MKAdmin/openssl-3.0.7/Configure line 23.
[MKAdmin@RHELMK openssl-3.0.7]$

**Comment by t8m** [comment]
You'll need to install perl-IPC-Cmd package and possibly other perl packages.

**Comment by tom-cosgrove-arm** [comment]
Have you tried `yum install perl-IPC-Cmd`?

The OpenSSL `Configure` script is a Perl script that requires several packages that are pre-installed on most Perl installations, but clearly not all
