### ISSUE TITLE
Enabling SSL in LibCurl on Raspberry / Ubuntu22.04

### ISSUE THREAD

**Issue by sqpp** [openssl/openssl#19749]
I have a single question. Is there a way to enable ssl in libcurl in any way?

Any help is really welcome!

```
marcell@raspberry:~$ curl -v ssl://pecl.php.net:443
* Protocol "ssl" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "ssl" not supported or disabled in libcurl
```

**OpenSSL Version:** OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
**CURL Version:** curl 7.81.0 (aarch64-unknown-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
```
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Comment by paulidale** [comment]
This is a question for the curl folks rather than OpenSSL.

**Comment by tom-cosgrove-arm** [comment]
Should the command line not be `curl -v https://pecl.php.net:443` ?

From `curl`'s perspective, the "protocol" would be `https` (as opposed to `http`).
