### ISSUE TITLE
Is there a way to install openssl 1.1.1 or later on centOS 6?

### ISSUE THREAD

**Issue by mrlerch** [openssl/openssl#19750]
Using centOS 6 (i know..eol, but I can't switch or upgrade quite yet.).

If relevant, please remember to tell us in what OpenSSL version you
found the issue.

Trying to install OpenSSL 1.1.1s by compiling from source

Downloaded the openssl source code from openss.org (openssl-1.1.1s.tar.gz) to /usr/src/openssl-1.1.1s.tar.gz

Then I unzipped it to to /usr/src/openssl-1.1.1s

Then I cd'ed into /usr/src/openssl-1.1.1s

issued the following commands
````
./config
make
make test
make install
````

After that it appears that it it installed the new open SSL binary in /usr/local/bin (so /usr/local/bin/openssl is the location), and that it installed shared objects? in /usr/local/lib64 (libssl.so.1.1, libcrypto.so.1.1, libcrypto.a, libssl.a). When I move the old openssl (v 1.0.1e-fips) for safekeeping and copy /usr/local/bin/openssl and then do a ./openssl version I get:

./openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

So, how can I get this to work? Any help is appreciated.

Thank you!

**Comment by t8m** [comment]
Do NOT replace the system openssl library, you will certainly break your system. The system applications built against the 1.0.1e version will not run with 1.1.1.

However, you can install the new version of openssl in /usr/local as you did. You might need to run ldconfig or configure the /usr/local/lib64 in /etc/ld.so.conf if the system cannot find the libcrypto.so.1.1 and libssl.so.1.1 placed there.

**Comment by t8m** [comment]
You just put a line with `/usr/local/lib64` in /etc/ld.so.conf and run `ldconfig` as root.

**Comment by mrlerch** [comment]
So this will not replace anything, but include that path, right?Martin Lerch
702.321.0908 (mobile)
-------------------------
Sent from my iPhone (mobile)
***************************
The information contained in this communication is potentially confidential, and intended only for the use of the addressee. If you received this communication in error, please notify us by return e-mail and delete this communication and all copies, including all attachments.
****************************On Nov 28, 2022, at 10:40 AM, Tomáš Mráz ***@***.***> wrote:﻿
You just put a line with /usr/local/lib64 in /etc/ld.so.conf and run ldconfig as root.

**Comment by t8m** [comment]
> So this will not replace anything, but include that path, right?Martin Lerch

Yes

**Comment by mrlerch** [comment]
Tomas, you rock. Thank you! That worked!

Martin

**Comment by mrlerch** [comment]
One more question. How can I get SSH to use the new OpenSSL?

SSH -v output:
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013

openssl version output:
OpenSSL 1.1.1s  1 Nov 2022

Is it even possible?

Thanks.

**Comment by t8m** [comment]
You would have to build the openssh yourself to link it against the new openssl build. I personally would not recommend doing that unless you know what you're doing.

**Comment by xiexiaoqian** [comment]
> You just put a line with `/usr/local/lib64` in /etc/ld.so.conf and run `ldconfig` as root.

help! It's not work for me. It also 'openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory'

environment: centos7 & python 3.8

This is my /etc/ld.so.conf:
```
include ld.so.conf.d/*.conf
/usr/local/openssl/lib
/usr/local/lib64/
```

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
