### ISSUE TITLE
Building OpenSSL fails

### ISSUE THREAD

**Issue by inline42** [openssl/openssl#19755]
I read this: https://github.com/openssl/openssl/blob/master/NOTES-WINDOWS.md
1. I cloned the repo: https://github.com/openssl/openssl.git
2. I downloaded perl and when I excute: ```perl -v``` I get output below,
```
This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)
Binary build 0000 [25391a6d] provided by ActiveState http://www.ActiveState.com
Built Oct 28 2020 18:24:51
```
3. I downloaded nasm and added it to the ```PATH``` and when I call in cmd ```nasm -v``` I get the below,
```NASM version 2.15.05 compiled on Aug 28 2020```
4. I then go to the openssl folder I open cmd and I run: ```perl Configure``` and I get the below,
```
Failure!  build file wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

Can't locate Win32/Console.pm in @INC (you may need to install the Win32::Console module) (@INC contains: H:/..../openssl/util/perl c:/Users/../AppData/Local/activestate/cache/.../site/lib c:/Users/../AppData/Local/activestate/cache/.../lib H:/..../openssl/external/perl/Text-Template-1.56/lib) at c:/Users/farid/AppData/Local/activestate/cache/cda7f279/site/lib/ActivePerl/Config.pm line 400.
Compilation failed in require at c:/Users/.../AppData/Local/activestate/cache/.../site/lib/ExtUtils/MakeMaker.pm line 10.
BEGIN failed--compilation aborted at c:/Users/.../AppData/Local/activestate/cache/.../site/lib/ExtUtils/MakeMaker.pm line 10.
Compilation failed in require at c:/Users/.../AppData/Local/activestate/cache/.../site/lib/IPC/Cmd.pm line 235.
```
I am using ```Windows 10 Pro```. OS Build: ```19044.2251```

Could you please help me? I need openssl to make boost asio work and I am stuck at this point.

**Comment by tom-cosgrove-arm** [comment]
As per the error text, you need to `install the Win32::Console module` which you should be able to do with

```
ppm install Win32-Console
```

It looks like [issues have cropped up before with ActiveState Perl](https://github.com/openssl/openssl/issues/12068), and Strawberry Perl is usually recommended now.

**Comment by inline42** [comment]
I am runing ```ppm install Win32::Console``` I get the below:
```
ppm' is not recognized as an internal or external command,
operable program or batch file.
```
:)

**Comment by tom-cosgrove-arm** [comment]
It looks like ActivePerl (still) has a number of problems. In the link I posted they suggest using Strawberry Perl instead

**Comment by inline42** [comment]
Thanks so much, I installed Strawberry and it works fine. Just still missing some header files e.g. <openssl/ssl.h> and <openssl/opensslv.h> only .in exists. How can generate these files please? I see in the page above I have to:
1. nmake
2. nmake test
3. nmake install

But I don't think that is the reason. Could you please help if on top of your head, otherwise thanks so much for helping configure :)

**Comment by mattcaswell** [comment]
> But I don't think that is the reason.

It is the reason. The real .h files don't get generated until later in the process.

**Comment by tom-cosgrove-arm** [comment]
For example, on the Linux system I am on right now

```
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/opensslv.h.in > include/openssl/opensslv.h
```

happens as part of `make`

**Comment by inline42** [comment]
I see thanks so much. I don't have nmake:
'''
'nmake' is not recognized as an internal or external command,
operable program or batch file.
'''
What is nmake? Should I install that too on top of perl and nasm please?
Thanks so much again!

**Comment by mattcaswell** [comment]
Note in particular step 4 of the "Quick start" section in the NOTES-WINDOWS file:

> Use Visual Studio Developer Command Prompt with administrative privileges, choosing one of its variants depending on the intended architecture. Or run cmd and execute vcvarsall.bat with one of the options x86, x86_amd64, x86_arm, x86_arm64, amd64, amd64_x86, amd64_arm, or amd64_arm64. This sets up the environment variables needed for nmake.exe, cl.exe, etc. See also https://docs.microsoft.com/cpp/build/building-on-the-command-line

If you successfully did that step then nmake should be present.

**Comment by inline42** [comment]
Thanks very much. I went to Tools > Command Line > Developer Command Prompt and then I run both:
'''
nmake
nmake test
'''
And the log looks fine. But when running the third command:
'''
nmake install
'''
It fails and loggs:
'''
H:\Mine\.....\openssl>nmake install

Microsoft (R) Program Maintenance Utility Version 14.31.31104.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\nmake.exe" /                   depend

Microsoft (R) Program Maintenance Utility Version 14.31.31104.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\nmake.exe" /                   _build_libs

Microsoft (R) Program Maintenance Utility Version 14.31.31104.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST .manifest DEL /F /Q .manifest
        IF EXIST libcrypto-3-x64.dll DEL /F /Q libcrypto-3-x64.dll
        cmd /C ""link" /nologo /debug /dll  /nologo /debug @C:\Users\farid\AppData\Local\Temp\nmFCEC.tmp /implib:libcrypto.lib || (DEL /Q libcrypto-3-x64.* libcrypto.lib & EXIT 1)"
crypto\aes\libcrypto-shlib-aes_cfb.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
Could Not Find H:\Mine\azra_final\azra\vendors\openssl\libcrypto-3-x64.*
NMAKE : fatal error U1077: 'cmd' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
'''

Thanks again. Any idea what this could be please?

**Comment by inline42** [comment]
This: [Issue](https://github.com/openssl/openssl/issues/19759) could be related :)

**Comment by amatyuko-intc** [comment]
You probably has to run `nmake` in the "**x64** Native Tools Command Prompt" to get x64 build environment. Mentioned issue is unrelated to your problem.
