### ISSUE TITLE
Symmetric key importance During encrypt and decrypt

### ISSUE THREAD

**Issue by shekharpaty** [openssl/openssl#19772]
Hello Experts,

I am performing a small command line operation the goal is to generate  a symmetric key using openssl and store the key in TPM FAPI keystore.
Issue: after modifying the symmetric key , the decryption should fail , but it decrypts , I am performing any wrong operation , please correct me.
Commands:

> `openssl rand 128 > symmetric_keyfile.key`
`echo "yyyyyyyyyyyyyyyyyyyyyyyyyyy" > sec.txt`
`openssl enc -in sec.txt -out secrets.txt.enc -e -aes256 -k symmetric_keyfile.key`
`echo "adding random characters literally modifying the symmetric key" >> symmetric_keyfile.key`
`openssl enc -in secrets.txt.enc -out secrets.txt.decrypted -d -aes256 -k symmetric_keyfile.key`
`cat secrets.txt.decrypted
yyyyyyyyyyyyyyyyyyyyyyyyyyy`
>
The goal is to seal  only symmetric key in FAPI keystore why because we cannot cipher text is too big to store , but if the key is modified and decryption is happening even after modifying the key, am i missing something?

**Comment by beldmit** [comment]
I don't remember how the -k option work. But if you just append some bytes to it, I'd expect that only the necessary first (unchanged) bytes will be used and decryption succeeds

**Comment by shekharpaty** [comment]
@beldmit any way to make decryption depend on symmetric key, without symmetric key or single master key the decrypt should fail.

**Comment by beldmit** [comment]
If I understand correctly, you don't change the secret key. You just append some bytes to it but it doesn't affect the bytes really used for encryption and decryption
