### ISSUE TITLE
Typo "Generating a RSA key"

### ISSUE THREAD

**Issue by nowakommunikation** [openssl/openssl#19771]
The guys (and girls) from OpenVPN sent me over here because I wrongly posted this error in their repository. Apparently my issue is actually openssl related since it's integrated in OpenVPN.

I'm using the latest version of OpenVPN and when it's generating the RSA key it reads: 

"Generating a RSA private key" 

but it should read 

"... an RSA private..."

Screenshot:

![unnamed](https://user-images.githubusercontent.com/44474606/204089202-47d8fbe6-421d-42ab-b3f9-d3ca59814188.jpg)

**Comment by mspncp** [comment]
Also, it seems that this message was deleted in commit https://github.com/openssl/openssl/commit/a7e4ca5b4e1932cb91ea21047403c87a033e524a#diff-3035acd5d175a93dc59622ed572ec6adc33f7fbb55deedd2997a9231a25a3212L676-L677

**Comment by mspncp** [comment]
I guess this is what is printed nowadays:

https://github.com/openssl/openssl/blob/055d029610712a281aed0c23ddd3c8f4dbf40f80/apps/lib/apps.c#L3380-L3382

**Comment by t8m** [comment]
Yeah. This is from 1.1.1 version. There is no a/an in the 3.0 and above in the verbose message.
I'm closing this as 1.1.1 is in security fixes only stage.
