### ISSUE TITLE
HMAC: State need for loading default provider into NULL libctx

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#19782]
When calling [HMAC](https://www.openssl.org/docs/manmaster/man3/HMAC.html) in a test provider there is no way to specify use of a (test provider) libctx: Thus, for HMAC to work in such a setting, the default provider must be loaded into libctx=NULL: 
```
    if (!OSSL_PROVIDER_available(NULL, "default"))
        if (!OSSL_PROVIDER_load(NULL, "default"))
            return 0;
```
Is [this intentional](https://github.com/openssl/openssl/blob/92a25e24e6ec9735dea9ec645502cb075a5f8d24/crypto/hmac/hmac.c#L231) or should this somehow be documented?

**Comment by mattcaswell** [comment]
I'm not quite sure what you mean. The old `HMAC*` functions are deprecated and don't support providers/libctx at all. The new `EVP_Q_mac` function takes a libctx as its first parameter.

**Comment by baentsch** [comment]
> The old HMAC* functions are deprecated

Apologies: I was of the opinion that only `HMAC_*` functions and not `HMAC()` are deprecated and thus used `HMAC()` -- but doing so means there's no way to pass a libctx: https://github.com/openssl/openssl/blob/92a25e24e6ec9735dea9ec645502cb075a5f8d24/crypto/hmac/hmac.c#L221-L223

Admittedly, I'm stupid to not immediately have recognized why the HMAC() call failed (missing default provider). Maybe other users are not so silly and thus don't need an explicit reminder for that when reading up on/using `HMAC()` (assuming that "main" API is not deprecated). But then again, not everyone may remember the provider concept when reading this API explanation. _I_ didn't -- all the while implementing a (test) provider :-/

**Comment by mattcaswell** [comment]
> Apologies: I was of the opinion that only HMAC_* functions and not HMAC() are deprecated and thus used HMAC()

Oh! You are absolutely right. I had complete forgotten that we did that. The old `HMAC` function was rewritten to just wrap `EVP_Q_mac` so as not to unnecessarily break apps using it - but it does mean that there is no way to pass a libctx. We *should* make this clear in the docs.

**Comment by t8m** [comment]
On the other hand it is kind of implicit that a function that does not have libctx argument or any other context argument, cannot really use non-default libctx.

**Comment by mattcaswell** [comment]
> On the other hand it is kind of implicit that a function that does not have libctx argument or any other context argument, cannot really use non-default libctx.

Right - but we could point users at what to use instead if they need to do this.
