### ISSUE TITLE
Enable tls 1.1

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#19780]
I am using openssl 1.1.1l and need to use TLS 1.1 ciphers.
Are these enabled by default during build or should I set some flag to enable TLS 1.1?
Also, can someone give the openssl name for any TLS1.1 cipher.
Most of the ciphers I check show mapping as 1.1, 1.2
I need to use a cipher that is explicitly TLS 1.1.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
