### ISSUE TITLE
undefined symbol: FIPS_mode

### ISSUE THREAD

**Issue by Arunkumar-M10** [openssl/openssl#19791]
Hi All,

I am facing an issue with openssl where it is throwing me errors like below,

../python3.8/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: **undefined symbol: FIPS_mode**

Initially, was using openssl 3.0.2 and had come across some errors when cryptography build was running, so have installed the openssl version 1.1.1h and cryptography build was successful. But now when I am trying to run some automated test in CI pipeline getting above errors. Below are the details,

Image: Ubuntu - 20.04
Openssl version 1.1.1h
steps followed to install openssl:
```
sudo wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz
sudo wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz.sha256
echo "$(cat openssl-1.1.1htar.gz.sha256) openssl-1.1.1h.tar.gz" | sha256sum --check
sudo tar -zxf openssl-1.1.1h.tar.gz
cd openssl-1.1.1h
./config
make
make install
sudo mv /usr/bin/openssl /usr/bin/openssl-1.1.1h
sudo ln -s /usr/local/bin/openssl /usr/bin/openssl
sudo ldconfig
openssl version
```

Have tried installing different version of openssl like 1.0.1e/1.0.2s/3.0.7 etc.., but still the issue exists, could someone please let me know how to overcome from this issue?

**Comment by t8m** [comment]
Is the python-cryptography package something you've built or does it come from the OS? If the later then you've probably overwritten the system openssl library with your own which is never a good idea. Try to reinstall the system packages.

**Comment by Arunkumar-M10** [comment]
@t8m it is one of the python package have installed from internet as a part of requirement,txt and that package installs the other required files/packages when it is getting installed and have not overwritten any system library. Also, I am trying this in virtual instance, is there anything I need to install separately to make it work?

**Comment by t8m** [comment]
I suppose you'll need to get the python-cryptography from the same source as the openssl library is. I am afraid we cannot help you more here.

**Comment by t8m** [comment]
To clarify - I do not recommend to overwrite the system openssl shared library with a library built by yourself. I assume it should be possible to get python-cryptography package built against the system openssl library on Ubuntu 20.04

**Comment by Arunkumar-M10** [comment]
@t8m sure, thanks for your comments on this
