### ISSUE TITLE
Avoiding repeated calls to `EVP_CIPHER_CTX`'s Init & Final functions

### ISSUE THREAD

**Issue by nikslyon19** [openssl/openssl#19809]
I have a question regarding the usage of `EVP_EncryptUpdate` and `EVP_DecryptUpdate`.

If we were to set padding to 0 via `EVP_CIPHER_CTX_set_padding`,
could we avoid calling the final APIs, i.e. `EVP_EncryptFinal_ex` and `EVP_DecryptFinal_ex` ?

Reason I ask because, I'm writing an application where I would be performing Symmetric Encrypt/Decrypt on the incoming/outgoing packet payloads, and I'm trying to minimize these `EVP_CIPHER_CTX` API calls.

In my application, I'm trying to cache the `EVP_CIPHER_CTX` for a given cipher,
so that for any Encrypt/Decrypt operation, I could just call `EVP_EncryptUpdate` / `EVP_DecryptUpdate` and that's it.

I don't wish to repeat the cycle of calling `Init, Update, Final` every single time.
Also, going by the documentation, I believe there is no harm calling the Update APIs multiple times?

```
        int out_len;

        int ret = EVP_DecryptUpdate(cipher_ctx, decrypted_data, &out_len,
                                        encrypted_data, encrypted_data_len);
        if (ret != 1) {
                printf("Decryption process failed");
                return -1;
        }

        *decrypted_data_len = out_len;
```

```
        int out_len;

        int ret = EVP_EncryptUpdate(cipher_ctx, encrypted_data, &out_len,
                                        plaintext_data, plaintext_data_len);
        if (ret != 1) {
                printf("Encryption process failed");
                return -1;
        }

        *encrypted_data_len = out_len;
```

**Comment by t8m** [comment]
You could use EVP_Cipher(). However, how do you handle the initial vector?

**Comment by nikslyon19** [comment]
Oh okay, I was not aware about the `EVP_Cipher()` , I'll check it out.

Currently, everytime I make a call to my encrypt/decrypt function, I pass the `symmetric key` and `IV` parameters to my function, which in-turn calls `EVP_DecryptInit_ex` /  `EVP_EncryptInit_ex` , followed by `Update` & `Final` call.

So, basically each session would have it's own key & IV, and it would go through the below series for encryption/decrytion.

```
        cipher_ctx = EVP_CIPHER_CTX_new();
        if (cipher_ctx == NULL) {
                printf("failed to create EVP Cipher context");
                return -1;
        }

        ret = EVP_EncryptInit_ex(cipher_ctx, EVP_aes_256_ctr(),
                                        NULL, sym_key, iv);
        if (ret != 1) {
                printf("failed to initialize encryption process");
                goto drop;
        }

        ret = EVP_EncryptUpdate(cipher_ctx, encrypted_data, &len,
                                plaintext_data, plaintext_data_len);
        if (ret != 1) {
                printf("encryption process failed");
                goto drop;
        }

        *encrypted_data_len += len;

        ret = EVP_EncryptFinal_ex(cipher_ctx, encrypted_data + len, &len);
        if (ret != 1) {
                printf("encryption finalize process failed");
                goto drop;
        }

        *encrypted_data_len += len;

        EVP_CIPHER_CTX_free(cipher_ctx);

        return 0;
 ```

Currently, I was thinking about, instead of storing key & IV per session, how about I store the `EVP_CIPHER_CTX` per session, and everytime I go for the above process, I would just call the `Update` function and move along, without having to do new/free & init, update, final cycle.

And since I would be setting padding to 0, I suppose I don't need to call the `Final` function either.

**Comment by nikslyon19** [comment]
@t8m regarding `EVP_Cipher()` :-

```
Due to the constraints of the API contract of this function it shouldn't be used in applications,
please consider using EVP_CipherUpdate() and EVP_CipherFinal_ex() instead.
```

so is it not recommended to use `EVP_Cipher()` for practical applications?
If it's okay and not much difference, I'll go with the `_Update` API itself.

also, need a small clarification, if I'm right to assume that I don't need to call Encrypt/Decrypt `Final` API if I have set the `EVP_CIPHER_CTX padding` to `0` ?

**Comment by t8m** [comment]
I still think it is safer to use EVP_Cipher() instead of depending on particular behavior of EVP_CipherUpdate().
If you know the constraints of the EVP_Cipher() API contract and it works for you, it is IMO OK to use it.

**Comment by nikslyon19** [comment]
@t8m just a suggestion.
I see the parameters of `EVP_Cipher()`:-

```
int EVP_Cipher(EVP_CIPHER_CTX *ctx, unsigned char *out,
               const unsigned char *in, unsigned int inl)
```

I think it would be helpful if we could also pass `int *outl` as a parameter, similar to `EVP_CipherUpdate()` .
Going by the definition of `EVP_Cipher()`,  it uses local variable `size_t outl` internally.

Right now, the idea of `int *outl` missing in `EVP_Cipher()` is holding me back from using it,
which is not in the case of `EVP_CipherUpdate()`.

Regarding Symmetric Ciphers, I understand in the case of AES-256-CTR (in my usecase), the encrypt/decrypt length are the same, but I'm not sure if it's the same for other Ciphers as well.

I think the `EVP_Cipher()` could use the extra `int *outl` parameter.

**Comment by paulidale** [comment]
Why do you want to avoid calling final?

In general, you should call final.  Some cipher modes will buffer data internally and only output all of it when final is called.  It's not just the length that can change: some of the CTS modes swap the final two blocks e.g.

Look at `EVP_CIPHER_CTX_dup()` for a way to avoid having to call init repeatedly.  This depends on reuse of key and IV etc so it's not applicable in all circumstances.

**Comment by nikslyon19** [comment]
```
If padding is disabled then EVP_EncryptFinal_ex() will not encrypt any more data
```

I have padding disabled in my EVP_CIPHER_CTX.
My EVP_CIPHER_CTX for a given session will remain the same (including key & IV),
I only require calling encrypt/decrypt on every payload it sends/receives.

**Comment by t8m** [comment]
We cannot change existing API calls to add more parameters. It would have to be a new call.

The EVP_Cipher API contract requires you to know what you're doing, i.e., what cipher/mode do you use and that means also whether the ciphertext length is the same as plaintext length (if you encrypt whole blocks) or not.

**Comment by nikslyon19** [comment]
Oh okay, basically the usage of `EVP_Cipher()` is up to the caller to decide if it works for their usecase.
I'll proceed accordingly then. Thanks.
