### ISSUE TITLE
SSLv3_client_method version OPENSSL_1_1_0 not defined

### ISSUE THREAD

**Issue by lystormenvoy** [openssl/openssl#19800]
I compiled new version openssl1.1.1 like 1.1.1o in my server.
Then some of commands can not run:
`NetworkManager: relocation error: /lib64/libcurl.so.4: symbol SSLv3_client_method version OPENSSL_1_1_0 not defined in file libssl.so.1.1 with link time reference`

ldd libcurl.so.4 print:
````
# ldd /lib64/libcurl.so.4
	linux-vdso.so.1 (0x00007ffc10bd9000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f3a88d7e000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f3a88d5c000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007f3a88cee000)
	libpsl.so.5 => /lib64/libpsl.so.5 (0x00007f3a88cdb000)
	libssl.so.1.1 => /usr/local/ssl/lib/libssl.so.1.1 (0x00007f3a88c45000)
	libcrypto.so.1.1 => /usr/local/ssl/lib/libcrypto.so.1.1 (0x00007f3a88956000)
        ……

````

strings /usr/local/ssl/lib/libssl.so.1.1 print:
````
# strings /usr/local/ssl/lib/libssl.so.1.1 | grep SSLv3_
SSLv3_server_method
SSLv3_client_method
SSLv3_method
SSLv3_enc_data
````

my compile command:
`./config shared enable-ssl3 enable-ssl3-method --prefix=/usr/local/ssl`

kernel:
`4.19.90-24.4.v2101.ky10.x86_64`

strings /usr/lib64/libssl.so.1.1.1f (The origin libssl.so in system.) print:
````
strings /usr/lib64/libssl.so.1.1.1f | grep SSLv3_
SSLv3_method
SSLv3_server_method
SSLv3_client_method
````

**Comment by mattcaswell** [comment]
You should not attempt to replace the system supplied OpenSSL version with a custom compiled version. It looks like you are attempting to run system binaries and run them against the custom OpenSSL. This is almost always a bad idea and usually leads to problems.

**Comment by lystormenvoy** [comment]
> You should not attempt to replace the system supplied OpenSSL version with a custom compiled version. It looks like you are attempting to run system binaries and run them against the custom OpenSSL. This is almost always a bad idea and usually leads to problems.

It  seems work fine in CentOS7. I compiled a new version of openssl because I want to update my sshd.

**Comment by urmyfaith** [comment]
how to solve this? @lystormenvoy
