### ISSUE TITLE
Unable to build static OpenSSL 3.0.7  on CentOS/8 + GCC toolset 11

### ISSUE THREAD

**Issue by tamama** [openssl/openssl#19804]
First, we configure:

```
./config \
  -static \
  no-threads \
  no-shared \
  no-dso \
  no-tests \
  --prefix=$PWD/.dist  \
  --openssldir=$PWD/.dist/.openssl
```

Second, we build:

```
make VERBOSE=1 -j8
```

Third, we observe this:
```
...
/opt/rh/gcc-toolset-11/root/usr/bin/ld: cannot find -ldl
/opt/rh/gcc-toolset-11/root/usr/bin/ld: cannot find -lc
```

I retried everything using system GCC (8.5) <- but still the same problem...

**Comment by t8m** [comment]
With -static you would need a static C library. Is this really what you want?

**Comment by t8m** [comment]
Then you would need static glibc to be installed. I do not know if CentOS 8 provides it.

**Comment by tamama** [comment]
@t8m That works like magic after I managed to install glibc-static.

This works

```
./config \
  -static \
  --prefix=$HOME/.workspace/opt/linux/openssl/openssl-3.0.7  \
  --openssldir=$HOME/.workspace/opt/linux/openssl/openssl-3.0.7/.openssl
```
