### ISSUE TITLE
evp_test crashes for 3.1.0-alpha1 on Solaris10

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#19814]
Commit https://github.com/openssl/openssl/commit/ed16b0fc282d29f755e656043e8a70553ef7bea5 added the following output line - probably for debugging purposes in test/evp_test.c:

    printf("test %s (%d %d)\n", t->name, t->s.start, t->s.curr);

When running  the tests, t->name is null. On Linux, it writes out "(null)" for the name, but on Solaris it crashes. So we should either

- drop printing the name, or
- make sure the name is initialized, or
- drop the line at all if it wasn't intended for permanent use, or
- find out why printing "(null)" only works for Linux, not on Solaris 10

The failing test are:
not ok 18 - running evp_test -config ../../test/default-and-legacy.cnf evpmd_sha.txt
not ok 51 - running evp_test -config ../../test/fips-and-base.cnf evpmd_sha.txt
not ok 91 - running evp_test -config ../../test/default-and-legacy.cnf evpmd_blake.txt
not ok 92 - running evp_test -config ../../test/default-and-legacy.cnf evpmd_md.txt
not ok 93 - running evp_test -config ../../test/default-and-legacy.cnf evpmd_mdc2.txt
not ok 94 - running evp_test -config ../../test/default-and-legacy.cnf evpmd_ripemd.txt
not ok 95 - running evp_test -config ../../test/default-and-legacy.cnf evpmd_sm3.txt
not ok 96 - running evp_test -config ../../test/default-and-legacy.cnf evpmd_whirlpool.txt
(each crashes with a core dump in the print statement).

Thanks and regards,

Rainer

**Comment by mattcaswell** [comment]
Fix in #19820
