### ISSUE TITLE
Documentation missing for `EVP_PKEY_CTX_get0_pkey` and `EVP_PKEY_CTX_get0_peerkey`

### ISSUE THREAD

**Issue by nikslyon19** [openssl/openssl#19813]
Documentation or info seems to be missing for `EVP_PKEY_CTX_get0_pkey` and `EVP_PKEY_CTX_get0_peerkey` in https://www.openssl.org/docs/man3.1/man3/

These APIs are mentioned in `include/openssl/evp.h`

Came across using `EVP_PKEY_CTX_get0_pkey` as I was writing code to validate the parameters of `EVP_PKEY_CTX`'s reference pkey, so I think it would be useful to document this formally.

**Comment by t8m** [comment]
Yes, we know that. There are still many undocumented API calls listed in util/missing{crypto,macro,ssl}.txt

**Comment by mattcaswell** [comment]
> If it is okay, I could try and take this up.

Please do

> For adding documentation for this, I'll need to create a .pod file for the same inside doc/man3/

Yes. Or possibly add them to an existing page if appropriate.

> and remove the mention of these 2 APIs from missingcrypto.txt and missingcrypto111.txt in the util/ directory?

Just missingcrypto.txt. You shouldn't need to touch missingcrypto111.txt.

**Comment by t8m** [comment]
Documentation PR is merged.
