### ISSUE TITLE
Build problem 3.1.0-alpha1 on Solaris10: timersub macro undefined

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#19812]
When building OpenSSL 3.1.0-alpha1 on Solaris 10, running the tests fails due to a missing timersub symbol.

timersub is used in test/timing_load_creds.c and eg. on Linux and Solaris 11 it is defined as an (obvious) macro.

I will attach a possible fix. The origin of this snippet is unclear, so is its license. I would guess it is trivial/obvious enough, that there should be no issue in using it.

I don't know, whether Solaris 10 will still be supported by OpenSSL 3.1, but if yes, then please consider the patch.

I will build and check, whether the tests succeed based on this patch.

**Comment by rainerjung** [comment]
`--- test/timing_load_creds.c    2022-12-01 18:34:34.482491000 +0000
+++ test/timing_load_creds.c    2022-12-01 20:05:16.333528353 +0000
@@ -21,6 +21,19 @@
 # include <openssl/bio.h>
 # include "internal/e_os.h"
 
+
+#ifndef timersub
+#define timersub(a, b, result)                       \
+{                                                    \
+    (result)->tv_sec = (a)->tv_sec - (b)->tv_sec;    \
+    (result)->tv_usec = (a)->tv_usec - (b)->tv_usec; \
+    if ((result)->tv_usec < 0) {                     \
+        --(result)->tv_sec;                          \
+        (result)->tv_usec += 1000000;                \
+    }                                                \
+}
+#endif 
+
 static char *prog;
 
 static void readx509(const char *contents, int size)
`

**Comment by t8m** [comment]
Fix in https://github.com/openssl/openssl/issues/19812
Could you please test it?

**Comment by mattcaswell** [comment]
> Fix in https://github.com/openssl/openssl/issues/19812

I think you meant: Fix in #19817

**Comment by t8m** [comment]
Yeah
