### ISSUE TITLE
An overflow in ssl/ssl_lib.c SSL_get_shared_ciphers()

### ISSUE THREAD

**Issue by Dr4gonEy3** [openssl/openssl#19837]
Hi, I found an overflow in ssl/ssl_lib.c Ln.3223.
```C
unsigned int n;
c = sk_SSL_CIPHER_value(clntsk, i);
if (sk_SSL_CIPHER_find(srvrsk, c) < 0)
  continue;
n = strlen(c->name);   // forced type conversion
if (n >= size) {
  if (p != buf)
    --p;
  *p = '\0';
  return buf;
  }
strcpy(p, c->name); // trigger
```
The return type of `strlen()` is `size_of`. If the length of `c->name` is over 2^31, then the `strcpy()` in Ln.3236 will trigger a overflow. Furthermore, `SSL_get_shared_ciphers()` is an exported functions. This represents a security issue for end user code that calls this function directly.

**Comment by mattcaswell** [comment]
>  If the length of c->name is over 2^31, then the strcpy() in Ln.3236 will trigger a overflow.

Well, yes - but not really. SSL_CIPHER is an opaque structure, and the only possible instances of it are ones created directly by libssl. They are all listed in ssl/s3_lib.c. None of them have such insanely long names - they are all relatively short. So there isn't any real risk of this happening.

That's not to say it wouldn't be a bad idea to fix the type confusion here.

**Comment by shourya5** [comment]
Wouldnt an easy fix for this would be to use strncpy (p, c->name,n);

**Comment by Anis-cpu-13** [comment]
I will work on this issue for my first contribution

**Comment by Anis-cpu-13** [comment]
Hello, it seems to me that the problem has been resolved, I verify the function in question, there is no memory overflow problem, the verification line was added

**Comment by bharsaklemukesh975** [comment]
If no one is working, I would like to take this as my first open source contribution.

Thanks!
