### ISSUE TITLE
undocumented key functionality in openssl 3 FIPS mode

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#19834]
It seems to me key related functionality is not documented when OpenSSL 3+ runs in FIPS mode.

In 3.0 FIPS is loadable module based on provider interface and module implements only cryptographic algorithms.
Also base provider is documented that contains algorithms to serialize and deserialize keys to files.

I cannot found documentation that details how a FIPS provider will interact with other loadable modules.
For instance as minimum:
- how to change provider;
- is use of RSA, DSA, EC key structure allowed.

---
P.S.
Inspired from following error:
....
Could not read private key from org.openssl.engine:e_nss:E_NSS Certificate (client-ec2) - E_NSS Test Team cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω
0067F47E817F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (id-ecPublicKey : 109), Properties (<null>)
0067F47E817F0000:error:030C0100:digital envelope routines:evp_pkey_copy_downgraded:malloc failure:crypto/evp/p_lib.c:2052:
0067F47E817F0000:error:030000CD:digital envelope routines:evp_pkey_copy_downgraded:keymgmt export failure:crypto/evp/p_lib.c:2068:key type = id-ecPublicKey
....

Result from following code:
 ... // Third-party part
pubkey = CERT_ExtractPublicKey(cert);
 ...
 ... = PK11_DEREncodePublicKey(pubkey);
 ... // OpenSSL part
pkey = d2i_PUBKEY(NULL, <data based on encoded pubkey>);
 ...
EC_KEY *pkey_ec = EVP_PKEY_get1_EC_KEY(pkey); // < return NULL!
 ...

As is visible code does not use cryptographic functionality yet.

**Comment by mattcaswell** [comment]
> is use of RSA, DSA, EC key structure allowed.

See the FIPS module documentation which says:

https://www.openssl.org/docs/man3.0/man7/fips_module.html

> Applications written to use the OpenSSL 3.0 FIPS module should not use any legacy APIs or features that avoid the FIPS module. Specifically this includes:
> 
> - Low level cryptographic APIs (use the high level APIs, such as EVP, instead)
> 
> - Engines
> 
> - Any functions that create or modify custom "METHODS" (for example EVP_MD_meth_new(), EVP_CIPHER_meth_new(), EVP_PKEY_meth_new(), RSA_meth_new(), EC_KEY_METHOD_new(), etc.)
> 
> All of the above APIs are deprecated in OpenSSL 3.0 - so a simple rule is to avoid using all deprecated functions. See [migration_guide(7)](https://www.openssl.org/docs/man3.0/man7/migration_guide.html) for a list of deprecated functions.

The RSA, DSA and EC_KEY structures are part of the "low level" cryptographic APIs. Importantly *all* functions that use them are deprecated. So if you apply the last rule of avoiding all deprecated functions then you will find yourself unable to use the RSA, DSA and EC_KEY structures.

> how to change provider;

The FIPS module man page as linked above provides a number of different examples of how to load the FIPS provider using different approaches (e.g. via config, or programatically), and also covers how to use it in conjunction with the base provider.

You might also want to review this page which provides some generic (not FIPS specific) overview of providers/libctx/fetching etc and how to use it in applications:

https://www.openssl.org/docs/man3.0/man7/crypto.html

Finally you may want to review the following pages which give some more details about what algorithms are supported by each of the various providers:

https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-FIPS.html
https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-base.html
https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-default.html
https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-legacy.html
https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-null.html
