### ISSUE TITLE
DSA_generate_key() replacement is not documented properly

### ISSUE THREAD

**Issue by Hlipa** [openssl/openssl#19845]
DSA_generate_key() was deprecated in 3.0+ but new documentation does not contain information how to properly generate DSA key when P, Q and G is already know. See following code:

```sslDSAKey = DSA_new();
sslDSAKey->p = BN_bin2bn(P, sizeof (P), sslDSAKey->p);
sslDSAKey->q = BN_bin2bn(Q, sizeof (Q), sslDSAKey->q);
sslDSAKey->g = BN_bin2bn(G, sizeof (G), sslDSAKey->g);
DSA_generate_key(sslDSAKey);
```

In new [documentation](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-DSA.html) there is only example with param generation.

**Comment by mattcaswell** [comment]
> In new [documentation](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-DSA.html) there is only example with param generation.

It looks to me like that page has an example of how to create the domain parameters EVP_PKEY, and then a subsequent example of how to use those domain parameters to generate a key. Isn't that exactly what you want?

**Comment by Hlipa** [comment]
I have original code for OSSL1.0 where P, Q and G are know, and I need to generate DSA key.  I'm expecting example like this:

```
pctx = EVP_PKEY_CTX_new_from_name(NULL, "DSA", NULL);                    
EVP_PKEY_fromdata_init(pctx);                                            
                                                                         
params[0] = OSSL_PARAM_construct_BN("p", P, sizeof (P));                 
params[1] = OSSL_PARAM_construct_BN("q", Q, sizeof (Q));                 
params[2] = OSSL_PARAM_construct_BN("g", G, sizeof (G));                 
params[3] = OSSL_PARAM_construct_end();                                  
                                                                         
EVP_PKEY_fromdata(pctx, &param_key, EVP_PKEY_KEY_PARAMETERS, params)     
EVP_PKEY_CTX_free(pctx);                                                 

gctx = EVP_PKEY_CTX_new_from_pkey(NULL, param_key, NULL);                
EVP_PKEY_keygen_init(gctx);                                              
EVP_PKEY_generate(gctx, &key);
```

note also that DSA key generation is not in demo examples as well.

**Comment by mattcaswell** [comment]
Ah, I see. Yes, we could benefit from such an example on that page. I see @t8m has already added the "help wanted" label.

**Comment by slontis** [comment]
There are some pitfalls related to doing this, especially if your params were generated with the old fips 186-2 standard.
I may need to do this.

**Comment by slontis** [comment]
Note that the above code is also not correct, it needs to use OSSL_PARAM_BLD in order to deal with BIGNUMS.

**Comment by slontis** [comment]
I would recommend regenerating p,q,g if possible to use the fips186-4 generation method. If you need to validate this key then you also need to store the seed, gindex, counter used for the generation.

**Comment by t8m** [comment]
> Note that the above code is also not correct, it needs to use OSSL_PARAM_BLD in order to deal with BIGNUMS.

Yeah, the OSSL_PARAM_construct_BN() expects the bignum data in native data order which means inverting the byte order on little endian machines.

**Comment by mattcaswell** [comment]
Closing since this is marked as "fixed".
