### ISSUE TITLE
corruption spreading to other SSL connections after receiving error:0A000126:SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by lano1106** [openssl/openssl#19854]
I have a WebSocket client opening 48 TLS connections from a single thread over TCP to a remote server that is behind Cloudflare.

My system is ArchLinux
kernel: 6.0.11

The problem did appear after the upgrade to openssl 3.0.7.

There are a few things that did change all at once so I am currently busy trying to isolate the issue as much as possible. I will first share the observations then I will continue by documenting everything that has changed since around the time the problem appeared.

The 48 TLS connections get established and the setup can work smoothly for hours without a glitch. However, as soon as the common error
'SSL routines::unexpected eof while reading' happens if the peer closes its side of the connection, all the OTHER connections shortly after are reporting random errors:

error:1C800066:Provider routines::cipher operation failed
error:0A000119:SSL routines::decryption failed or bad record mac
error:1C80006C:Provider routines::invalid aad
error:0A0C0103:SSL routines::internal error
error:0A00010B:SSL routines::wrong version number
error:0A0000F4:SSL routines::unexpected message
error:0A0000C6:SSL routines::packet length too long

When a connection gets closed, the client automatically attempts to reconnect with the server. However, for all the 48 connections EXCEPT 1 (so 47 of them), they will enter an infinite loop where:
- the SSL connection will be established,
- The initial HTTP request/reply will be communicated
- The HTTP connection will be upgraded to WebSocket
- Few WS messages will be exchanged back and forth between the client and the server.

until the connection will be closed after having reported one of the random errors enumerated above (the connections remain established 2-3 seconds max).

It is as if the reception of the initial error 'error:0A000126:SSL routines::unexpected eof while reading' was corrupting some static internal data shared among all the managed connections by openssl.

The only way to exit that condition is to fully restart the client from a fresh state

Notable observation:
2 other threads each having 1 SSL socket remain unaffected by the problem.

openssl is indirectly initialized with the following options via a 3rd party library:
```
    info.ssl_client_options_set = SSL_OP_ENABLE_KTLS|SSL_OP_NO_TLSv1_3;
    info.client_ssl_cipher_list = "AES128-GCM-SHA256";
    info.client_tls_1_3_plus_cipher_list = "TLS_AES_128_GCM_SHA256";
```
So, that mean that for all my connections, the cipher/protocol used is:
AES128-GCM-SHA256, 128 bits, TLSv1.2

So that bring us to the following section where I document what did change around the time the problem did appear:

Yes I did experiment with kTLS. The experience was not satisfactory. On my server box, the kernel was panicking after a few days of continuous kTLS usage. I suspect that there might still be an undiscovered memory leak inside kTLS code. (I use Software kTLS. I don't have access to one of those fancy Mellanox cards...)

On a desktop machine, using kTLS was making the UI unresponsive as if kTLS was inducing some contention by locking something stopping the kernel to dispatch events to other system processes.

I disabled kTLS by recompiling openssl with:
```
	./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib \
		shared disable-ktls enable-ec_nistp_64_gcc_128 linux-x86_64 \
		"-Wa,--noexecstack ${CPPFLAGS} ${CFLAGS} ${LDFLAGS}"
```

Official ArchLinux settings except that enable-ktls has been changed to disable-ktls.

Why did I choose to recompile instead of just removing SSL_OP_ENABLE_KTLS from the options?

I have a custom BIO and it was hammered by requests for BIO_CTRL_GET_KTLS_SEND and/or BIO_CTRL_GET_KTLS_RECV coming from openssl code despite not having requested to use kTLS at all for that connection or for the whole application. The only way that I have found to eliminate those useless BIO_ctrl calls was to recompile openssl with ktls disabled.

Detail worth noting, I initially did recompile with '-O3 -flto' switches. That has been my initial suspect for explaining the problem. Since then, I did recompile several times openssl with different settings:

openssl build compiler switches used where the problem has been observed:
compiler: -O3, -flto linker: -O3 -flto=auto
compiler: -O2, -flto linker: -O3 -flto=auto
compiler: -O3, linker: -O3

currently testing:
compiler: -O2, linker:

used compiler: gcc v12.2.0

Other things that I think trying out to attempt isolating the cause:
The initialization settings
```
    info.ssl_client_options_set = SSL_OP_ENABLE_KTLS|SSL_OP_NO_TLSv1_3;
    info.client_ssl_cipher_list = "AES128-GCM-SHA256";
    info.client_tls_1_3_plus_cipher_list = "TLS_AES_128_GCM_SHA256";
```
are new since 3.0.7 upgrade. If I can reproduce the issue with a vanilla build, my next attempt will be to remove those settings to use openssl default setting. I suspect that the problem may be located in code used only with those config settings in place... that is my latest guess...

**Comment by slontis** [comment]
What version did you upgrade from?

**Comment by lano1106** [comment]
previous version distributed by ArchLinux. Upon looking at https://github.com/archlinux/svntogit-packages/commits/packages/openssl/trunk

it appears that it was 1.1.1.q

**Comment by lano1106** [comment]
My diagnostic of something corrupting data was correct when EOF is received was correct. The only unknown variable was what was doing it.

openssl is clean.

it is my usage of io_uring in conjunction with its buffer rings. It recycles the buffer and does not return a buffer when the number of read bytes is 0. My code was not catching this special and rare condition and was returning buffer 0 back. The buffer 0 was referenced twice in the io_uring buffer ring and this is what was causing the corruption contagion to all the other sockets sharing the same buffer queue. This is the equivalent of dropping a wrench in the motor...

This might also be the cause of my kernel panics and not kTLS!
