### ISSUE TITLE
OCSP client verify fails when responder requires "Host" header

### ISSUE THREAD

**Issue by tlhackque** [openssl/openssl#1986]
Using `openssl ocsp` (client) to verify a certificate fails when the responder requires host header.

This is a "known" issue with startssl (startcom) responders- but it keeps tripping people up.  (It's only "known" to you once **you** trip over it and do the research, which is annoying.)

It is possible to work-around this with the undocumented `-header` switch as shown below.

- `-header` should be documented!
- `ocsp` (client) should send a host header with its request by default.
- `ocsp` (client) should probably also have a `-servername` option

Example:
````
# openssl version
OpenSSL 1.0.2h  3 May 2016
# openssl ocsp -issuer root_bundle.crt -cert avh.crt -url http://ocsp.startssl.com  -CAfile /etc/pki/tls/external-roots/ca_bundle.pem   -VAfile startcom_ocsp.pem
Error querying OCSP responder
3086117020:error:27076072:OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:314:Code=400,Reason=Bad Request
#
# # Add -header 'host' 'ocsp.startssl.com' to the command
#
# openssl ocsp -issuer root_bundle.crt -cert avh.crt -url http://ocsp.startssl.com -header 'host' 'ocsp.startssl.com' -CAfile /etc/pki/tls/external-roots/ca_bundle.pem   -VAfile startcom_ocsp.pem
WARNING: no nonce in response
Response verify OK
avh.crt: good
        This Update: Nov 23 10:23:57 2016 GMT
        Next Update: Nov 27 10:33:57 2016 GMT
````
This should be easy to reproduce - startcom offers free domain verified certificates (See [startssl.com](https://www.startssl.com), "free" option).  There's nothing special about mine.

But I've attached the files used in the example.  (The -CAfile is from the Perl Mozilla::CA module).

[startcom_ocsp.pem.txt](https://github.com/openssl/openssl/files/608769/startcom_ocsp.pem.txt)
[avh.crt.txt](https://github.com/openssl/openssl/files/608770/avh.crt.txt)
[root_bundle.crt.txt](https://github.com/openssl/openssl/files/608771/root_bundle.crt.txt)

This has been an issue since at least 2013 - see [this webpage](http://jfcarter.net/~jimc/documents/bugfix/21-openssl-ocsp.html), which is where I found it documented.

**Comment by MiWCryptoCurrency** [comment]
Hi,

I don't think its quite correct to call this 'SNI' as this is a TLS specific handshake parameter.
I would call this 'HTTP/1.1 Host Header'.

RFC6960 specifies that OCSP over HTTP use generic RFC2616 without requiring HTTP/1.1.
It also says that other headers MAY be sent and MAY be ignored by the server.

Name-based virtual hosting the norm and for compat for modern HTTP front ends for OCSP requests 
requires HTTP/1.1 with a host header.
My suggestion would be that the default behavior of the ocsp function would be to always send an HTTP host-header with HTTP/1.1; HTTP/1.0 without host header should be the switch alt behavior.

**Comment by tlhackque** [comment]
Thanks.  I agree that SNI wasn't the best description.  I fixed the original issue.

As you note, the essence is that the 'Host' header is required by OCSP responders behind name-based virtual hosts, which StartSSL's CDN (among others) uses.

I agree that sending the **Host** header by default is the right choice.  It should be OK to always send the **Host** header; HTTP 1.0 allows **Host** (and named VHs required it before HTTP 1.1). [rfc1945 section 7.1](https://tools.ietf.org/html/rfc1945#section-7.1) *Unrecognized header fields should be ignored by the recipient and forwarded by proxies.*  With respect to **Host**, HTTP/1.1 just formalized existing practice.

So OCSP could send **HTTP/1.0** with a **Host** header as a conservative choice.  I'm not sure that an **HTTP/1.1** option is required, but it wouldn't hurt.

**-servername** would be consistent with s_client's switch (which *does* imply SNI).  SNI is valid for OCSP over SSL/TLS.  Overloading it for sending a **Host** header over HTTP also allows for the odd case of connecting by ip address to a (non-SSL/TLS) HTTP server that requires a **Host** header.

**Comment by richsalz** [comment]
What version are you using?  Can you try 1.1.0?

**Comment by tlhackque** [comment]
Rich,

As shown in the original report's example:   
the original report  was generated with  `OpenSSL 1.0.2h  3 May 2016`  (from source)

I've also tested with `OpenSSL 1.0.1k-fips 8 Jan 2015` (fedora) - using the same files (NFS)

(`version -a`  for both below.)

Same result: without `-header host, ...`  a 400 response; with `-header host`  I get an OCSP response.

I don't have a 1.1.0 environment (bind has problems with the API changes).

But I attached the files necessary to reproduce this to the initial report, so you ought to be able to see how 1.1.0 behaves more easily than I can setup a new machine...

Actually, it really doesn't matter what certificate you query; the failure is in the server's front end - the verify request never makes it to the OCSP responder's (name-based) virtual host.  So you can send any OCSP query to `-url`&nbsp;`http://ocsp.startssl.com` and should get the same results.

Based on your hint, I took a look at apps/ocsp.c here on GitHub, and there seems to be code that would add a `host` header (unless one was specified with `-header host`).  Blame shows it was introduced in commit 76e0cd12f68f0b8173bc71ee6e9ad3ca453d5a28, which git says is only in master, 1.1.0 and 1.1.0_pre.   So, assuming it works, I guess this becomes a request to backport it.
 
This morning, I also get a rather confusing error (both versions) that claims a bad signature, but a 'good' response.  Technically, I understand how this can be true, but the error message could be a lot clearer... I suppose that's another issue.

````
Response Verify Failure
3086157980:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:rsa_pk1.c:103:
3086157980:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:rsa_eay.c:705:
3086157980:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:218:
3086157980:error:27069075:OCSP routines:OCSP_basic_verify:signature failure:ocsp_vfy.c:105:
avh.crt: good
        This Update: Dec  2 09:51:09 2016 GMT
        Next Update: Dec  6 10:01:09 2016 GMT
#echo $?
1
````

````
 openssl version -a
OpenSSL 1.0.1k-fips 8 Jan 2015
built on: Thu Aug 13 12:14:48 2015
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  dynamic

openssl version -a
OpenSSL 1.0.2h  3 May 2016
built on: reproducible build, date unspecified
platform: linux-elf
options:  bn(64,32) rc4(8x,mmx) des(ptr,risc1,16,long) idea(int) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -DL_ENDIAN -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/local/ssl"
````

**Comment by mattcaswell** [comment]
> So, assuming it works, I guess this becomes a request to backport it.

This would be counted as a feature. We only backport bug fixes to 1.0.2 so this would not be eligible.

**Comment by tlhackque** [comment]
I disagree with your characterization of the issue.

Failure to communicate with a major CA's responders without the use of an obscure, un-documented option seems like a bug to me.

**Comment by mattcaswell** [comment]
The fact that it is undocumented should be fixed. That then provides a workable solution in 1.0.2. If you need the more user friendly feature then you should upgrade to 1.1.0.

**Comment by tlhackque** [comment]
Sure.  I'll upgrade -- when BIND can compile and run with 1.1.0; ISC reports that you and they have issues with API changes in 1.1.0.  And assuming I don't encounter other software with issues.

For a 'workable' solution: you should at least document that *some OCSP responders require '-header host <the hostname from -url or -host>, and typically respond with an HTTP 400 or other error if this option is not specified.*  Just saying that *'-header name value' lets you add custom http headers* would not be helpful for most users.

It's your team's decision; I'm just a user.  When an engineer wants to do something about an issue, it's a bug.  When he doesn't, it's a feature.  Considering the small scope of the fix (or "feature") and the customer pain that it's caused for at least the past 3 years, if it were my project, I'd make the change.  

I've done my duty to report and research the issue.   I know what my fingers (and scripts) need to do for now.  Disposition is in the OpenSSL team's hands.

**Comment by richsalz** [comment]
Sorry for the delay, @tlhackque.  You're right, there's now a PR to fix the docs.

**Comment by tlhackque** [comment]
@richsalz Thanks for working on this.  I looked at the PR; it seems that you simply documented -header, not the important usage from .-2:

> For a 'workable' solution: you should at least document that _some OCSP responders require '-header host <the hostname from -url or -host>, and typically respond with an HTTP 400 or other error if this option is not specified._  **Just saying that _'-header name value' lets you add custom http headers_ would not be helpful for most users.**

I still think that including something to the effect that -header host is a mandatory option for some OCSP responders would avoid a fair bit of customer pain.

**Comment by richsalz** [comment]
I added a sentence and pushed an updated commit; hope that helps.

**Comment by richsalz** [comment]
fixed with 1f234f7 on 1.0.2

**Comment by jazzl0ver** [comment]
Hello. It would be awesome if you ported that docs update back to 1.0.1 - the standard library for CentOS 6.

**Comment by mattcaswell** [comment]
> Hello. It would be awesome if you ported that docs update back to 1.0.1 - the standard library for CentOS 6.

Unfortunately 1.0.1 is no longer supported by the OpenSSL project and receives no updates from us at all.

**Comment by richsalz** [comment]
Ping the CenOS maintainers.
