### ISSUE TITLE
Failing Apple API in OpenSSL 3.0.x

### ISSUE THREAD

**Issue by NamrataKSAP** [openssl/openssl#19871]
Hi 
I have a p12 certificate created using AES-256-CBC. 
(From [here](https://www.openssl.org/docs/man3.0/man1/openssl-pkcs12.html#:~:text=The%20default%20encryption%20algorithm%20is%20AES%2D256%2DCBC%20with%20PBKDF2%20for%20key%20derivation.))
This is the command I used to generate the .p12:
```
openssl pkcs12 -export -inkey CertKey.key -in cert.crt -out my.p12 -certpbe AES-256-CBC
 ```

A am parsing the p12 with ```PKCS12_parse```   and then passing data to Apple API ```SecPKCS12Import```
but in apple api is failing with following error
```
SecPKCS12Import Optional(Error Domain=NSOSStatusErrorDomain Code=-25293 "The user name or passphrase you entered is not correct." UserInfo={NSLocalizedDescription=The user name or passphrase you entered is not correct.})
```
Following is the code to reproduce the bug

```
let data = try Data(contentsOf: fileURL)

guard let pkcs12Data = OpenSSLHelperProxy.shared.createPKCS12fromPKCS12Data(data, passphraseOriginal: passphrase, passphraseNew: "") else {
            logger.error("Create PKCS #12 from PKCS #12 data failed")
            completionHandler(nil, IdentityError.failedToCreateIdentity)
            return
}
```

```
-(NSData* _Nullable)createPKCS12fromPKCS12Data:(NSData* _Nonnull)PKCS12Data passphraseOriginal:(NSString* _Nonnull)passphraseOriginal passphraseNew:(NSString* _Nonnull)passphraseNew {
    BIO* mem = createPKCS12fromPKCS12([PKCS12Data bytes], [PKCS12Data length], (char*)[passphraseOriginal UTF8String], (char*)[passphraseNew UTF8String]);
    NSData* data = [OpenSSLHelperProxy NSDataFromBIO:mem];
    return data;
}

+(NSData*)NSDataFromBIO:(BIO*)mem {
    NSData* data = nil;
    if (mem != NULL) {
        char* ptr = NULL;
        
        size_t size = BIO_get_mem_data(mem, &ptr);
        data = [NSData dataWithBytes:ptr length:size];
        BIO_free(mem);
    }
    return data;
}
```

```
BIO* createPKCS12fromPKCS12(const unsigned char* data, long dataLength, char* originalPassphrase, char* newPassphrase) {
   
    BIO* bp = BIO_new_mem_buf(data, (int)dataLength);
    PKCS12* originalPKCS12 = NULL;
    d2i_PKCS12_bio(bp, &originalPKCS12);
    BIO_free(bp);

    EVP_PKEY* privateKey;
    X509* x509;
    STACK_OF(X509)* caChain = NULL;
    PKCS12_parse(originalPKCS12, originalPassphrase, &privateKey, &x509, &caChain);
    PKCS12_free(originalPKCS12);
   

    PKCS12* newPKCS12 = PKCS12_create(newPassphrase, "", privateKey, x509, caChain, 0, 0, 0, 0, 0);
    EVP_PKEY_free(privateKey);
    X509_free(x509);
    sk_X509_free(caChain);

    BIO* mem = NULL;
    if (newPKCS12 != NULL) {
        mem = BIO_new(BIO_s_mem());
        i2d_PKCS12_bio(mem, newPKCS12);
        PKCS12_free(newPKCS12);
        
    }
    
    return mem;
}


```
Then do the following after getting  pkcs12Data, in the first code snippet
```
        let err = SecPKCS12Import(pkcs12Data as CFData, query as CFDictionary, &items)

```

Technology used:
Xcode: 14.0.1
OpenSSL: 3.0.5
iOS: 16

The result expected: SecPKCS12Import pass with no errors

**Comment by mattcaswell** [comment]
Most likely the Apple API does not like the default encryption algorithm that OpenSSL is using (AES_256_CBC). The default encryption algorithm was changed in 3.0. Previously it was `NID_pbe_WithSHA1And40BitRC2_CBC`. You can try passing that in the `nid_cert` parameter for `PKCS12_create`. You will need to load the legacy provider for that to work.

**Comment by slontis** [comment]
This looks like a continuation of https://github.com/openssl/openssl/issues/19495

**Comment by NamrataKSAP** [comment]
> This looks like a continuation of #19495

yeah I am also trying with a new certificate of the latest algo and openssl 3

**Comment by NamrataKSAP** [comment]
> Most likely the Apple API does not like the default encryption algorithm that OpenSSL is using (AES_256_CBC). The default encryption algorithm was changed in 3.0. Previously it was `NID_pbe_WithSHA1And40BitRC2_CBC`. You can try passing that in the `nid_cert` parameter for `PKCS12_create`. You will need to load the legacy provider for that to work.

Hi @mattcaswell I tried this, but still not working for me
```
PKCS12_create(newPassphrase, "ABC", privateKey, x509, caChain, 0, 149, 0, 0, 0);
```

**Comment by mattcaswell** [comment]
You might additionally try `NID_pbe_WithSHA1And3_Key_TripleDES_CBC` in the key_pbe parameter.

Did the amended PKCS12_create() call complete successfully? Did you load the legacy provider?

**Comment by NamrataKSAP** [comment]
i tried the changes, but did not work. Attaching my full code here also. PKCS12_create() call succeeded. Also, i am loading the legacy provider.
```
    PKCS12* newPKCS12 = PKCS12_create(newPassphrase, "ABC", privateKey, x509, caChain, 146, 149, 0, 0, 0);
```

```
BIO* createPKCS12fromPKCS12(const unsigned char* data, long dataLength, char* originalPassphrase, char* newPassphrase) {

    OSSL_PROVIDER *legacy = OSSL_PROVIDER_try_load(NULL, "legacy", 1);
    OSSL_PROVIDER *defaultProvider = OSSL_PROVIDER_try_load(NULL, "default", 1);
    
    
    BIO* bp = BIO_new_mem_buf(data, (int)dataLength);
    PKCS12* originalPKCS12 = NULL;
    d2i_PKCS12_bio(bp, &originalPKCS12);
    BIO_free(bp);

    EVP_PKEY* privateKey;
    X509* x509;
    STACK_OF(X509)* caChain = NULL;
    PKCS12_parse(originalPKCS12, originalPassphrase, &privateKey, &x509, &caChain);
    PKCS12_free(originalPKCS12);
    
    PKCS12* newPKCS12 = PKCS12_create(newPassphrase, "ABC", privateKey, x509, caChain, 146, 149, 0, 0, 0);
    unsigned long a = ERR_get_error();
    printf("%lu", a);
    EVP_PKEY_free(privateKey);
    X509_free(x509);
    sk_X509_free(caChain);
    BIO* mem = NULL;
    if (newPKCS12 != NULL) {
        mem = BIO_new(BIO_s_mem());
        i2d_PKCS12_bio(mem, newPKCS12);
        PKCS12_free(newPKCS12);
        
    }
    
    return mem;
}
```

**Comment by NamrataKSAP** [comment]
any suggestion here?

**Comment by mattcaswell** [comment]
> any suggestion here?

Sorry, I'm out of ideas here. Maybe someone else has some suggestions?

**Comment by NamrataKSAP** [comment]
Hi, 

sharing a project to reproduce the issue: https://github.com/NamrataKSAP/PKCS12TestApp 

check the console log for error

**Comment by khusboo7** [comment]
@NamrataKSAP Are you able to load legacy with following code ?
`OSSL_PROVIDER *legacy = OSSL_PROVIDER_try_load(NULL, "legacy", 1);`

**Comment by NamrataKSAP** [comment]
Hi @khusboo7 Yes, I get the value of legacy with this code.
To make it work You will first need to have the legacy provider module in place (either dynamic package or statically linked into OpenSSL libs by using "no-shared" & "no-modules" configure options.

Check this: https://github.com/conan-io/conan-center-index/issues/10409
https://github.com/openssl/openssl/blob/master/INSTALL.md

**Comment by NamrataKSAP** [comment]
The issue has been fixed for me.
solution is provided here: https://developer.apple.com/forums/thread/723242

**Comment by jameskitt616** [comment]
You can get it working with using the `-legacy -certpbe pbeWithSHA1And40BitRC2-CBC` parameters with the `openssl pkcs12 -export` command.
