### ISSUE TITLE
The Iteration could not setted by command

### ISSUE THREAD

**Issue by chenweihao9** [openssl/openssl#19870]
The current implement in PKCS12 command

The Iteration could not setted by command

if (maciter != -1)
    PKCS12_set_mac(p12, mpass, -1, NULL, 0, maciter, macmd);

the default length is 2048

int iter = PKCS12_DEFAULT_ITER, maciter = PKCS12_DEFAULT_ITER;

#  define PKCS12_DEFAULT_ITER     PKCS5_DEFAULT_ITER

# define PKCS5_DEFAULT_ITER              2048

Suggestion

Update the default length to 10000+

Add the iteration option in pkcs12 command.

**Comment by mattcaswell** [comment]
> Add the iteration option in pkcs12 command.

But the pkcs12 command already has this option?, i.e. the "-iter" option

**Comment by mattcaswell** [comment]
This feature seems to be present so closing.
