### ISSUE TITLE
Openssl Engine under EDKII

### ISSUE THREAD

**Issue by KongoHuster** [openssl/openssl#19887]
Hi，I have a question about openssl engine to ask.
1.Firstly, we can use a crypto accelerator like QAT of Intel and UADK of Huawei under Linux.The commad like this:
```
openssl dgst -engine uadk_engine test.txt
```
2.Does the OpenSSL engine support EDKII? 
(1) We know that Openssl load the engine share object to connect accelerator driver.
(2) But there is no share object under EDKII.  
(3) Is it possible to use accelerator driver under EDKII openssl?

**Comment by t8m** [comment]
We do not produce builds for EDKII so we unfortunately cannot answer your questions.

But I suppose that no, engines are not supported in UEFI builds and thus accelerators are not supported.

**Comment by KongoHuster** [comment]
Oh, thank you for your prompt answer. I have another question about openssl engine.

Is it possible to use accelerator driver under Windows like QAT of Intel?

We know that Openssl load the engine share object to connect accelerator driver. But how about dll file under windows.?
Is there a way to load the engine dll file to connect accelerator driver, so that opsnssl can use the accelerator under windows?

**Comment by t8m** [comment]
Engines are supported on Windows in form of .dll loadable modules. Whether any particular accelerator engine works under Windows is a different question that I do not know the answer for.

**Comment by KongoHuster** [comment]
Thank you for your answer. I get it.
