### ISSUE TITLE
Typo in install.md

### ISSUE THREAD

**Issue by matheushw** [openssl/openssl#19881]
There are some typos at the install OpenSSL to Windows section.

`The easiest way to elevate the Command Prompt is to press and hold down the both the <CTRL> and <SHIFT> key while clicking the menu item in the task menu.`

should be:

`The easiest way to elevate the Command Prompt is to press and hold down both the <CTRL> and <SHIFT> keys while clicking the menu item in the task menu.`

**Comment by akai54** [comment]
Should be closed.
