### ISSUE TITLE
Add ability to specify subprime (Q) bit length when generating DSA keys

### ISSUE THREAD

**Issue by lsh123** [openssl/openssl#19893]
Currently, openssl defaults subprime (Q) bit size to 224 bits for all DSA key lengths. However FIPS 186-3 defines four valid pairs of ( |p|,  |q]); (1024, 160), (2048, 224), (2048, 256) and (3072, 256). In order to be able to generate not only (2048, 224) but other valid DSA keys it should be possible to specify q-bit length in the "openssl dsaparam" command. 

The attached diff [dsaparam.txt](https://github.com/openssl/openssl/files/10214103/dsaparam.txt) implements the new optional "numqbits" parameter to address the issue.

**Comment by t8m** [comment]
Could you please submit it as a pull request?

**Comment by lsh123** [comment]
> Could you please submit it as a pull request?

Done
