### ISSUE TITLE
SQLite Database Ecnryption 

### ISSUE THREAD

**Issue by mdeihly** [openssl/openssl#19896]
I would like to ask if I can encrypt/decrypt SQLite Database using OpenSSL 1.1.1 and which is the most efficient way to do it?
Thanks

**Comment by tom-cosgrove-arm** [comment]
In the past, when I worked for a different company, SQLCipher was usually recommended for encrypting SQLite databases. IIRC it used OpenSSL to perform the actual encryption/decryption.

**Comment by mdeihly** [comment]
Thanks for response.
Is there a page that describes in details how I can compile SQLCipher for platform x86?
