### ISSUE TITLE
SSL_accept() after DTLSv1_listen() does not work without having called SSL_set_accept_state() first

### ISSUE THREAD

**Issue by kFYatek** [openssl/openssl#1989]
In OpenSSL 1.1.0 (I used 1.1.0c on Linux x86_64, to be precise), `SSL_accept()` will not work when invoked after `DTLSv1_listen()`, if `SSL_set_accept_state()` has not been called before either.

In such case, `SSL_accept()` will call `SSL_set_accept_state()` itself, which will in turn reset the state machine (`ossl_statem_clear()`), clearing the initial state set by `DTLSv1_listen()` (`d1_lib.c`, lines 804 onwards in 1.1.0c).

This changed when compared to the 1.0 branch - in 1.0.2g, there is no requirement to call `SSL_set_accept_state()`.

The documentation is entirely silent on this behaviour. The [manual for `DTLSv1_listen()`](https://www.openssl.org/docs/man1.1.0/ssl/DTLSv1_listen.html) suggests that this function itself is enough:
>When a ClientHello is received that contains a cookie that has been verified, then DTLSv1_listen() will return with the ssl parameter updated into a state where the handshake can be continued by a call to (for example) SSL_accept().

The [manual for `SSL_accept()`](https://www.openssl.org/docs/man1.1.0/ssl/SSL_accept.html) isn't helpful, either, while the [manual for `SSL_set_accept_state()`](https://www.openssl.org/docs/man1.1.0/ssl/SSL_set_connect_state.html) also suggests that calling this function is superfluous:
> When using the SSL_connect or SSL_accept routines, the correct handshake routines are automatically set.

I was able to fix my program only thanks to diving into the OpenSSL source code with a debugger and seeing what happens. I believe that either this behaviour shall be fixed (e.g. by adding a `if (s->handshake_func == NULL) SSL_set_accept_state(s);` statement to `DTLSv1_listen()`) or the documentation should be updated to reflect the actual requirement.

**Comment by mattcaswell** [comment]
`DTLSv1_listen()` was rewritten between 1.0.2 and 1.1.0. Looks like that aspect was missed. Fix in #1994.

**Comment by mattcaswell** [comment]
The fix for this is now in git so will be in the next 1.1.0 release.
