### ISSUE TITLE
Trace: Index error in trace_attach_cb and other functions

### ISSUE THREAD

**Issue by jbsgh** [openssl/openssl#19915]
With openssl 3.0.7 (other versions not tested) there is an out-of-bound access to array ```trace_categories``` in ```trace_attach_cb```, ```trace_detach_cb``` and ```trace_attach_w_callback_cb```:

```
        OSSL_TRACE2(TRACE, "Attach channel %p to category '%s'\n",
                    data, trace_categories[category].name);
```

The trace_categories array is defined as:

```
static const struct trace_category_st trace_categories[] = {
    TRACE_CATEGORY_(ALL),
    ...
TRACE_CATEGORY_(CONF),
#ifndef OPENSSL_NO_ENGINE
    TRACE_CATEGORY_(ENGINE_TABLE),
    TRACE_CATEGORY_(ENGINE_REF_COUNT),
#endif
    TRACE_CATEGORY_(PKCS5V2),
    ...
    TRACE_CATEGORY_(REF_COUNT)
};
```

Its length depends on whether ```OPENSSL_NO_ENGINE``` is defined or not. If it is not defined, the categories numbers are running from 0 to 17 with ```OSSL_TRACE_CATEGORY_NUM``` defined as 18 in trace.h, while the valid array indices are running from 0 to 15. Loops are correctly using ```OSSL_NELEM(trace_categories)``` as upper bound (resulting in a value of 16).

Accordingly, you must never access the array ```trace_categories``` with the category-number itself like in
 
```
        OSSL_TRACE2(TRACE, "Attach channel %p to category '%s'\n",
                    data, trace_categories[category].name);
```

As a solution, I've added an index-mapping function ```OSSL_trace_get_category_index``` in trace.c:

```
static int OSSL_trace_get_category_index(int num)
{
    size_t i;

    for (i = 0; i < OSSL_NELEM(trace_categories); i++)
        if (trace_categories[i].num == num)
            return (int)i;
    return -1; /* not found */
}

...

static int trace_attach_cb(int category, int type, const void *data)
{
int category_idx = OSSL_trace_get_category_index( category );

    if ( category_idx < 0 )
        return 0;

    switch (type) {
    case CHANNEL:
        OSSL_TRACE2(TRACE, "Attach channel %p to category '%s'\n",
                    data, trace_categories[category_idx].name);
    ...
```

The new function retrieves the array index of the entry with a given category.

**Comment by t8m** [comment]
Instead of this we should just never #ifdef out the trace category entries in the table.

**Comment by t8m** [comment]
My proposed fix is in https://github.com/openssl/openssl/pull/19917

IMO there is no point in making the trace categories disappear with no-engines.
