### ISSUE TITLE
OpenSSL 3.0.7 in CentOS 7.9.2009

### ISSUE THREAD

**Issue by sshcli** [openssl/openssl#19927]
Hello,
I have installed OpenSSL 3.0.7 in a server running CentOS 7.9.2009

#About the installation
These are the commands used for the installation:
sudo yum install perl-IPC-Cmd perl-Test-Simple
cd /usr/src
wget https://www.openssl.org/source/openssl-3.0.7.tar.gz
tar -zxf openssl-3.0.7.tar.gz
rm openssl-3.0.7.tar.gz
cd /usr/src/openssl-3.0.7
./config
make
make test
make install
ln -s /usr/local/lib64/libssl.so.3 /usr/lib64/libssl.so.3
ln -s /usr/local/lib64/libcrypto.so.3 /usr/lib64/libcrypto.so.3
openssl version

#About the problem
In the console, if I run “openssl version“, I can see the version installed is indeed 3.0.7, which is ok.
The problem is that Apache is still referencing the old version:
Server Version: Apache/2.4.54 (cPanel) OpenSSL/1.1.1s 

#My question:
How can I change it to the 3.0.7 version?

Thanks in advance for your kind support.

Regards,

**Comment by slontis** [comment]
This question relates to how do I build an 3rd party library. (So it is not really a question for OpenSSL).
I would imagine you need to compile Apache and link it with the relevant OpenSSL.

**Comment by sshcli** [comment]
I have created a feature request for this. 
See:
https://github.com/openssl/openssl/issues/19928

I'm closing this issue / question now.

**Comment by jasondee1992** [comment]
would this be listed under in the yum list after installation?

**Comment by t8m** [comment]
yum lists only rpm packages. We do not provide rpm or any other binary packages.
