### ISSUE TITLE
25-test_pkcs8 (test 3) failed on MSYS2/Win32/MinGW

### ISSUE THREAD

**Issue by Tarnum-tst** [openssl/openssl#19921]
Master branch, testing OpenSSL 3.2 dev after successful building process:
```
25-test_pkcs8.t ......................... 1/?
not ok 3 - compare test/certs/sm2.key to sm2.key
# ------------------------------------------------------------------------------
#   Failed test 'compare test/certs/sm2.key to sm2.key'
#   at /home/User/openssl-master/util/perl/OpenSSL/Test.pm line 913.
#          got: '1'
#     expected: '0'
25-test_pkcs8.t ......................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests
```
The reason is absolutely obvious and is related to the differences in new line styling between Windows (\r\n) and POSIX (\n) in file test/certs/sm2.key
I guess it's very easy to fix. Thanks!

**Comment by slontis** [comment]
Are you potentially changing the line endings when you pull the code? If so the problem may be on your end?

**Comment by Tarnum-tst** [comment]
@slontis 
No, I didn't touch anything. test\certs\sm2.key is in POSIX style but sm2.key generated by test on my system gets Windows style. It's not my fault.

**Comment by slontis** [comment]
We have Windows CI loops, so not sure why that would be different.

**Comment by t8m** [comment]
I assume the MinGW being a mix of POSIX and Windows probably somehow messes up the EOL handling in the perl scripts?

**Comment by t8m** [comment]
Please try #19957 fixes.

**Comment by Tarnum-tst** [comment]
@t8m 
This issue has been resolved, thanks a lot!
