### ISSUE TITLE
Could PR#19153 be added in 1.1.1x?

### ISSUE THREAD

**Issue by chengangc** [openssl/openssl#19922]
Hi, 

Our project needs the fix on GCC compiling warnings. If it's possible, could #19153 be added in the next 1.1.1x release? 
Thanks.

**Comment by t8m** [comment]
**OTC: Do we want the warning fix merged to 1.1.1 ***

**Comment by t8m** [comment]
@chengangc Could you just build the openssl code with -Wno-unused-but-set-variable ?

**Comment by bernd-edlinger** [comment]
out of curiosity, does #19738 also affect you?

**Comment by chengangc** [comment]
> 

no, this issue does affect me. 

On my side, it only shows the unused variable in PR#19153.

**Comment by t8m** [comment]
OTC: If someone submits a PR against 1.1.1 branch and it gets approvals it can be merged.

**Comment by chengangc** [comment]
Thanks for your review!

I uploaded the patch to 1_1_1_stable branch: https://github.com/openssl/openssl/pull/20347. Thanks.
