### ISSUE TITLE
[Feature Request] yum install OpenSSL3

### ISSUE THREAD

**Issue by sshcli** [openssl/openssl#19928]
This feature request, is to make it simple for people using Centos 7.9+

No more complications to install OpenSSL 3x in Centos 7.

Simple is better

This single line should do the magic

`yum install OpenSSL3`

**Comment by t8m** [comment]
We do not provide binaries of OpenSSL. That is a project policy.

**Comment by sshcli** [comment]
@t8m thanks for the feedback. 
IMHO, Maybe is time to reconsider a change in the project policy. 
The world changes, people changes, project changes   **;-)**

**Comment by t8m** [comment]
There are dozens of Linux distributions and versions, it would be quite big task to provide binaries for all of them. Besides they would not be replacing the system openssl packages which would not help that many people anyway.

So the answer is - get the OpenSSL binaries for Linux OSes from the OS vendor or the OS community.

**Comment by sshcli** [comment]
> So the answer is - get the OpenSSL binaries for Linux OSes from the OS vendor or the particular OS community.

Working on it. See: https://github.com/CentOS/sig-cloud-instance-images/issues/197
