### ISSUE TITLE
SSKDF with KMAC: "missing message digest"

### ISSUE THREAD

**Issue by jvdsn** [openssl/openssl#19934]
OpenSSL version: 3.0.7

When trying to derive keys using SSKDF with KMAC128 or KMAC256, OpenSSL returns an error:
```
40671FF4307F0000:error:1C800081:Provider routines:sskdf_size:missing message digest:providers/implementations/kdfs/sskdf.c:338:
```

However, the [man page](https://www.openssl.org/docs/man3.0/man7/EVP_KDF-SS.html) mentions that the digest parameter is only required for hash-based and HMAC-based SSKDF. Why does the SSKDF implementation assume the digest is present: https://github.com/openssl/openssl/blob/openssl-3.0/providers/implementations/kdfs/sskdf.c#L332-L343?

Perhaps the `ctx->out_len` value should be checked here first? This value is set by `OSSL_KDF_PARAM_MAC_SIZE` here: https://github.com/openssl/openssl/blob/openssl-3.0/providers/implementations/kdfs/sskdf.c#L475-L480

**Comment by jvdsn** [comment]
Also note that the man page example for KMAC128 also sets the digest parameter to SHA-256:
```
*p++ = OSSL_PARAM_construct_utf8_string(OSSL_KDF_PARAM_DIGEST,
                                        SN_sha256, strlen(SN_sha256));
```

**Comment by slontis** [comment]
The pod example seems wrong..

There is an example of how to set up a kmac in evp_kdf_ss_kmac (see test_kdf_ss_kmac).
It does not need the digest.

**Comment by slontis** [comment]
Can you provide the code you are using please, so I can see the difference between this and the expected usage in the test.?

**Comment by jvdsn** [comment]
Something like this:
```
int main() {
	const unsigned char in_key[16];
	const unsigned char salt[64];
	const unsigned char info[64];
	unsigned char out_key[64];
	size_t out_key_len = sizeof(out_key);
	int ret;

	OSSL_PARAM_BLD *bld = OSSL_PARAM_BLD_new();
	OSSL_PARAM_BLD_push_utf8_string(bld, OSSL_KDF_PARAM_MAC, "KMAC128", 0);
	OSSL_PARAM_BLD_push_size_t(bld, OSSL_KDF_PARAM_MAC_SIZE, 64);
	OSSL_PARAM_BLD_push_octet_string(bld, OSSL_KDF_PARAM_KEY, in_key, 16);
	OSSL_PARAM_BLD_push_octet_string(bld, OSSL_KDF_PARAM_SALT, salt, sizeof(salt));
	OSSL_PARAM_BLD_push_octet_string(bld, OSSL_KDF_PARAM_INFO, info, sizeof(info));
	OSSL_PARAM *params = OSSL_PARAM_BLD_to_param(bld);

	EVP_KDF *kdf = EVP_KDF_fetch(NULL, "SSKDF", NULL);
	if (kdf == NULL) {
		ERR_print_errors_fp(stdout);
		return 1;
	}
	EVP_KDF_CTX *ctx = EVP_KDF_CTX_new(kdf);
	if (ctx == NULL) {
		ERR_print_errors_fp(stdout);
		return 1;
	}
	if ((ret = EVP_KDF_CTX_set_params(ctx, params)) != 1) {
		ERR_print_errors_fp(stdout);
		return 1;
	}
	size_t kdf_size = EVP_KDF_CTX_get_kdf_size(ctx);
	if (kdf_size < SIZE_MAX) {
		out_key_len = kdf_size;
	}
	if ((ret = EVP_KDF_derive(ctx, out_key, out_key_len, NULL)) != 1) {
		ERR_print_errors_fp(stdout);
		return 1;
	}
	printf("Key generation successful!\n");
}
```

**Comment by slontis** [comment]
The output length is whatever size you want?

**Comment by slontis** [comment]
i.e One of the inputs to KMAC is the output length - since it is variable size..

**Comment by jvdsn** [comment]
According to https://www.openssl.org/docs/man3.0/man3/EVP_KDF_CTX_get_kdf_size.html:
> EVP_KDF_CTX_get_kdf_size() returns the output size if the algorithm produces a fixed amount of output and SIZE_MAX otherwise. If an error occurs then 0 is returned. For some algorithms an error may result if input parameters necessary to calculate a fixed output size have not yet been supplied.

So perhaps the KMAC length isn't the right output, but it should be SIZE_MAX?

**Comment by slontis** [comment]
Yeah probably, but I would tend to think that in the example that you present that you wouldnt want to call it at all? What use is a return value of SIZE_MAX to you use case?. I can change the code, but it doesnt really help you.

**Comment by slontis** [comment]
I will fix up the code.. But this logic does not make any sense for a variable length output..
````
	size_t kdf_size = EVP_KDF_CTX_get_kdf_size(ctx);
	if (kdf_size < SIZE_MAX) {
		out_key_len = kdf_size;
	}
````

**Comment by slontis** [comment]
You may want to free the kdf, ctx, params and bld..

**Comment by jvdsn** [comment]
Well, I actually perform different KDFs depending on the input arguments of my function. For some KDFs, the `EVP_KDF_CTX_get_kdf_size` call is useful. Yes, technically I could have a check for SSKDF with KMAC specifically to not invoke this call, but it's a bit unexpected. I would expect it to work, and it could actually be useful in a case like this (pseudocode):
```
// out_key_len = 0 means: determine output length automatically.
int do_kdf(const char *name, size_t out_key_len) {
    // Set up KDF...
    
    size_t kdf_size = EVP_KDF_CTX_get_kdf_size(ctx);
    if (kdf_size == 0) {
        printf("Error in EVP_KDF_CTX_get_kdf_size\n");
        return 1;
    }
    if (kdf_size == SIZE_MAX) {
        if (out_key_len == 0) {
            printf("expected out_key_len != 0\n");
            return 1;
        }
    } else {
        if (out_key_len != 0) {
            printf("expected out_key_len == 0\n");
            return 1;
        }
        out_key_len = kdf_size;
    }
    
    // Do KDF...
}

**Comment by slontis** [comment]
Fair enough.. You could potentially have truncated values for the else case that are valid so that logic might not be quite right..
I better go and check the code I added for HKDF to support KMAC a few days ago - it may have the same size related problem.. Thanks.

**Comment by jvdsn** [comment]
> You could potentially have truncated values for the else case that are valid so that logic might not be quite right..

What do you mean?

**Comment by slontis** [comment]
I mean the output length can be less than the digest size.

**Comment by slontis** [comment]
See the test vectors in test/recipies/30_test_evp_data/evpkdf_ss.txt for SHA1

**Comment by jvdsn** [comment]
Thanks, that makes sense, I'll fix that
