### ISSUE TITLE
TLS1.2 Failure v1.0.2

### ISSUE THREAD

**Issue by zwick88** [openssl/openssl#19949]
Hi, 

i have to crosscompile openssl v1.0.2 vor ARM11 Processor. This is the latest version we can use.

After building and install i got an error while downloading from a webserver
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

what does these error mean?

**Comment by t8m** [comment]
Could you try openssl s_client from that build? Is this error reported on all connections to any TLS server?

**Comment by zwick88** [comment]
Now i've found the failure. Wget and curl have to build with these new openssl version too.

**Comment by t8m** [comment]
Closing then.
