### ISSUE TITLE
Document limits on link/load of OpenSSL DLLs on HPE NonStop

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#19951]
The `NOTES-NONSTOP.md` file should document the current platform limitations regarding not both statically and dynamically linking OpenSSL libraries into a main program. This relates to #17537.

I will create a PR for the documentation update.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by rsbeckerca** [comment]
I completely forgot about this one, sorry. Will take a look. What I have seen is that some users are trying to build their own applications with OpenSSL without using DLLs. There good and bad reasons for this, but I'm not sure they differ from any other platform's use of OpenSSL.

**Comment by rsbeckerca** [comment]
This can be closed. Some other fix already has documented this in `NOTES-NONSTOP.md`.
