### ISSUE TITLE
3.1 migration guide? 

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#19953]
The [announcement](https://mta.openssl.org/pipermail/openssl-announce/2022-December/000247.html) for 3.1.0 beta 1 says:
> Specific notes on upgrading to OpenSSL 3.1 from previous versions are
   available in the OpenSSL Migration Guide, here:
> 
>        https://www.openssl.org/docs/man3.0/man7/migration_guide.html

Aside from pointing to `/man3.0` instead of `/man3.1`, there is no migration guide for 3.1.0 whatsoever under
* https://www.openssl.org/docs/man3.1/man7/migration_guide.html
* https://www.openssl.org/docs/manmaster/man7/migration_guide.html

Both just explain the migration to 3.0 - this may be fine, but then the respective section of the announcement email should be removed. 

Better still, a few notes about potential incompatibilities of 3.1 vs. 3.0 _or lack thereof_ would be wholly sufficient for the purpose for a "migration guide to 3.1". For example, according to the release strategy [page](https://www.openssl.org/policies/releasestrat.html): 
> API/ABI compatibility will be guaranteed for the same MAJOR version number. 

What I would be interested in (with my integrator hat on), is if there are any corner cases where this is _not_ the case (e.g. due to an OTC/OMC exception), and it would likewise be valuable to have it black-on-white if in fact there are no known cases of such incompatibilities.

**Comment by h-vetinari** [comment]
Can this be milestoned for 3.1.0 so that it will at least get a second look?

**Comment by paulidale** [comment]
The 3.1 series are forked from the 3.0 series.  There should be no changes to the migration guide.

Yeah, that's a bit hopeful but .....

**Comment by h-vetinari** [comment]
> The 3.1 series are forked from the 3.0 series. There should be no changes to the migration guide.

I don't think it's at all intuitive if a "migration guide" to 3.1 assumes implicitly you're migrating from 1.1.1. Possible to add that in the title of course, but it would be way more self-evident if there was just a section à la:

```diff
diff --git a/doc/man7/migration_guide.pod b/doc/man7/migration_guide.pod
index 75c8ed7..07edc68 100644
--- a/doc/man7/migration_guide.pod
+++ b/doc/man7/migration_guide.pod
@@ -11,11 +11,17 @@ See the individual manual pages for details.
 =head1 DESCRIPTION

 This guide details the changes required to migrate to new versions of OpenSSL.
-Currently this covers OpenSSL 3.0. For earlier versions refer to
+Currently this covers OpenSSL 3.0 & 3.1. For earlier versions refer to
 L<https://github.com/openssl/openssl/blob/master/CHANGES.md>.
 For an overview of some of the key concepts introduced in OpenSSL 3.0 see
 L<crypto(7)>.

+=head1 OPENSSL 3.1
+
+=head2 Main Changes from OpenSSL 3.0
+
+There are no substantial changes since OpenSSL 3.0.
+
 =head1 OPENSSL 3.0

 =head2 Main Changes from OpenSSL 1.1.1
```

**Comment by paulidale** [comment]
Please submit a pull request with these changes....
