### ISSUE TITLE
s_server doesn't accept certificate chains for -cert but does for -CAfile

### ISSUE THREAD

**Issue by dmuensterer** [openssl/openssl#19979]
When using the s_server CLI, the file specified with -cert should be able to contain a chain with leaf and intermediate certificates.
This does not work. Instead, what works is supplying -CAfile with a chain that contains intermediate certificates and the root certificate. This is against common SSL usage.

# Example:
## Works
`openssl s_server -key private.key -cert leaf.pem -CAfile root_chain.pem -accept 4433`
## Doesn't work
`openssl s_server -key private.key -cert leaf_intermediate_chain.pem -CAfile root_cert.pem -accept 4433`

**Comment by t8m** [comment]
There is a `-chain` option which allows specifying the intermediates without adding them to the CAfile.
