### ISSUE TITLE
Missing sk_POLICY_MAPPING_pop_free

### ISSUE THREAD

**Issue by Pedromdsn** [openssl/openssl#19973]
In the file [pcy_map.c](https://github.com/openssl/openssl/blob/61203c2c59df5d0022e316a4fe614e5d18907715/crypto/x509/pcy_map.c) we found the function sk_POLICY_MAPPING_pop_free but this one has no declaration.

![image](https://user-images.githubusercontent.com/57453260/209954921-88e3f986-9645-452e-a7ae-c6b3fc0f5671.png)

![image](https://user-images.githubusercontent.com/57453260/209954965-44aee1d1-8c8e-48a7-83f5-21f4dc4f9caf.png)

I can find in the file [stack.h](https://github.com/openssl/openssl/blob/master/include/openssl/stack.h) an OPENSSL_sk_pop_free function, but not a function with the exact name.

![image](https://user-images.githubusercontent.com/57453260/209954864-2a979276-17f0-4c0e-89ad-36964ef6804a.png)

**Comment by FdaSilvaYY** [comment]
There is a `DECLARE_STACK` macro, who created all these type-dedicated methods

**Comment by Pedromdsn** [comment]
> There is a `DECLARE_STACK` macro and a `DEFINE_STACK` , who create all these type-dedicated methods


Can you tell me the directory of this specific one?

**Comment by mspncp** [comment]
```make
PS C:\src\openssl> git grep -n POLICY_MAPPING -- include
include/openssl/cryptoerr_legacy.h:1439:#  define X509V3_F_V2I_POLICY_MAPPINGS                     0
include/openssl/x509v3.h.in:297:typedef struct POLICY_MAPPING_st {
include/openssl/x509v3.h.in:300:} POLICY_MAPPING;
include/openssl/x509v3.h.in:303:    generate_stack_macros("POLICY_MAPPING");
include/openssl/x509v3.h.in:306:typedef STACK_OF(POLICY_MAPPING) POLICY_MAPPINGS;
include/openssl/x509v3.h.in:599:DECLARE_ASN1_ITEM(POLICY_MAPPING)
include/openssl/x509v3.h.in:600:DECLARE_ASN1_ALLOC_FUNCTIONS(POLICY_MAPPING)
include/openssl/x509v3.h.in:601:DECLARE_ASN1_ITEM(POLICY_MAPPINGS)
```

```make
PS C:\src\openssl> git grep -n define.*STACK_OF -- include
include/openssl/safestack.h.in:34:# define STACK_OF(type) struct stack_st_##type
include/openssl/safestack.h.in:37:# define SKM_DEFINE_STACK_OF_INTERNAL(t1, t2, t3) \
include/openssl/safestack.h.in:67:# define SKM_DEFINE_STACK_OF(t1, t2, t3) \
include/openssl/safestack.h.in:178:# define DEFINE_STACK_OF(t) SKM_DEFINE_STACK_OF(t, t, t)
include/openssl/safestack.h.in:179:# define DEFINE_STACK_OF_CONST(t) SKM_DEFINE_STACK_OF(t, const t, t)
include/openssl/safestack.h.in:180:# define DEFINE_SPECIAL_STACK_OF(t1, t2) SKM_DEFINE_STACK_OF(t1, t2, t2)
include/openssl/safestack.h.in:181:# define DEFINE_SPECIAL_STACK_OF_CONST(t1, t2) \
```

**Comment by mspncp** [comment]
The `.h.in` files are templates which are processed by Perl to produce the corresponding `.h` files.
