### ISSUE TITLE
Add support for mandating use of EMS in TLS 1.2

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#19989]
[FIPS 140-3 Implementation Guidance](https://csrc.nist.gov/CSRC/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf) requires that only EMS KDF in TLS 1.2 can be used with modules validated after May 16, 2023 (see "D.Q Transition of the TLS 1.2 KDF to Support the Extended Master Secret").

Please add a setting that would enable and _require_ negotiation of EMS extension for TLS 1.2 connections. That setting then could default to enabled when operating in FIPS mode.

**Comment by DemiMarie** [comment]
Is there a reason to not require EMS unconditionally?

**Comment by tomato42** [comment]
@DemiMarie Backwards compatibility.

**Comment by DemiMarie** [comment]
@tomato42 then OpenSSL should disable DHE and RSA key exchange unless EMS is used.  Otherwise 3SHAKE works.

**Comment by t8m** [comment]
**OTC: We are OK with adding this feature off by default to 3.1 before the final release.**

**Comment by paulidale** [comment]
Confounding concern: for FIPS purposes, enforcement needs to be done inside the provider boundary.  It's not sufficient to force it from libssl.

**Comment by tomato42** [comment]
@paulidale Yes, but on TLS level, the correct time to reject it is right after receiving ClientHello (or right after receiving ServerHello that doesn't advertise EMS).

**Comment by paulidale** [comment]
Agreed.  Another FIPS oddity being born.

You have to enforce X even though it's never possible to encounter X.

**Comment by slontis** [comment]
@paulidale The change I have done here is at the KDF level, not the TLS level.

**Comment by tomato42** [comment]
Those patches seem to be just about the KDF calculation, I was asking for ability to control extension negotiation...

Could I get this issue re-opened? Or should I file a new one?

**Comment by slontis** [comment]
Apart from suggesting how this would be done, I dont see this is actually relevant for the OpenSSL validation.

**Comment by paulidale** [comment]
It isn't relevant to the OpenSSL validations.

It's something we'd probably want in libssl too.  As noted [above](https://github.com/openssl/openssl/issues/19989#issuecomment-1421694650), that's the sensible place for such a check.

**Comment by tomato42** [comment]
Yes, for FIPS validation the fix needs to be inside the validated module boundary, so `fips.so`.
But from UX point of view, additional check should be in libssl. Also, as pointed out [earlier](https://github.com/openssl/openssl/issues/19989#issuecomment-1370340993), it's useful for ensuring that the connection isn't vulnerable to 3SHAKE attack, even when not in FIPS mode.

**Comment by DemiMarie** [comment]
@tomato42 not only useful, but essential.  Otherwise there is a security vulnerability.

**Comment by beldmit** [comment]
Do we have anything else to do here?

**Comment by arapov** [comment]
@paulidale any work here?

**Comment by paulidale** [comment]
This has been done: #20241

**Comment by tomato42** [comment]
@paulidale sorry, but I don't think the linked PR https://github.com/openssl/openssl/pull/20241 addresses the reason why we re-opened this ticket: https://github.com/openssl/openssl/issues/19989#issuecomment-1460705997
