### ISSUE TITLE
Where is the definition of struct dh_st ?

### ISSUE THREAD

**Issue by BladeTail** [openssl/openssl#1998]
The code was below:

```
DH *dh=DH_new();
dh->p=BN_bin2bn(dh1024_p,sizeof(dh1024_p),NULL);
dh->g=BN_bin2bn(dh1024_g,sizeof(dh1024_g),NULL);
int iRet = SSL_CTX_set_tmp_dh(pctx,dh);
DH_free(dh);
```
While the dh->p line and the dh->g line occurred error: pointer to incomplete class type is not allowed.
I found the definition of DH in the ossl_typ.h at line 104 : 
`typedef struct dh_st DH;`
I tried to find out which header file contains the struct dh_st ,and I was directed to the dh.h ,but this file is appeared to be different from the same named file in the openSSL 1.0.1,there was absolutely no definition of it.
Do I have any other option?

**Comment by mattcaswell** [comment]
In OpenSSL 1.1.0 this is an opaque type and you cannot access its internal members. Use the function DH_get0_pqg() instead.

**Comment by mattcaswell** [comment]
Or DH_set0_pqg() to set!

**Comment by BladeTail** [comment]
Thank you @mattcaswell  very much，I tried as below:
        ```
        DH *dh=DH_new();
	BIGNUM *p=BN_bin2bn(dh1024_p,sizeof(dh1024_p),NULL);
	BIGNUM *g=BN_bin2bn(dh1024_g,sizeof(dh1024_g),NULL);
	DH_set0_pqg(dh , p, NULL, g);
	int iRet = SSL_CTX_set_tmp_dh(pctx,dh);
	DH_free(dh);
```
And I gonna take a test by tomorrow,Hope It works!
Thank you @mattcaswell  again!
