### ISSUE TITLE
Unable to verify certificate chain if "X509v3 Authority Key Identifier" contains Issuer name.

### ISSUE THREAD

**Issue by Larsjep** [openssl/openssl#19982]
Hi,

When trying to verify a certificate chain it fails with error 20. The problem seems to be related to the issuer name "X509v3 Authority Key Identifier" extension field.

When testing with a certificate with the Issuer name in AKID:
```openssl verify --partial_chain --trusted subinterCA.pem leaf-akid-issuer.pem```
It gives:
```error 20 at 0 depth lookup: unable to get local issuer certificate```

But when testing with a certificate without an 
issuer name in AKID it works as expected:
```openssl verify --partial_chain --trusted subinterCA.pem leaf.pem```
gives:
```leaf.pem: OK```

I have tested it with openssl version "OpenSSL 1.1.1  11 Sep 2018" and my own build from master(98663afce7a909be)
Certificates used for test: [test-certificates.zip](https://github.com/openssl/openssl/files/10331897/test-certificates.zip)

NOTE: GnuTLS ```certtool``` and Windows Schannel can verify both test certificates.

Regards
  Lars

**Comment by t8m** [comment]
The DirName in the AKID should be the name of the issuer of the intermediate certificate not the subject. The purpose of AKID is to uniquely identify the certificate and that is possible only by serial/issuer pair and not by serial/subject pair.

See RFC 5280.

**Comment by Larsjep** [comment]
Hi, 

I had read RFC 5280, but interpreted it differently. Thank you for clarifying.
I will go back to my certificate issuer and ask him to fix it.

Regards
  Lars

**Comment by t8m** [comment]
> I guess they don't look at this information.

Yeah, I think most of them just check the keyid and do not look at the issuer/serial.

**Comment by t8m** [comment]
I'd recommend the CA to not add the issuer/serial at all. The keyid should be sufficient to identify the right issuer certificate.
