### ISSUE TITLE
about the new PSS saltlen parameter in 3.1

### ISSUE THREAD

**Issue by selvanair** [openssl/openssl#19984]
Following the 3.1 docs for RSA signature [here](https://www.openssl.org/docs/man3.1/man7/EVP_SIGNATURE-RSA.html), the saltlen parameter has acquired a new posisble value: "auto-digestmax". Does it mean existing signature providers should be updated to handle this value?

Ours is a built-in provider used only to sign during TLS handshake when private key is external. And, it seems to always get called with saltlen set to "digest"  even in OpenSSL 3.1.0-beta1 --- as seen in OSSL_PARAMS passed to provider's digest_sign_init() or sign_init(). Is there a way to force TLS handshake to use different saltlen parameters for testing?

**Comment by t8m** [comment]
> Does it mean existing signature providers should be updated to handle this value?

Not necessarily. Callers must assume this value is not available with every provider - even the 3.0 won't have it.

However of course if you want to keep feature parity with OpenSSL default provider, it should be added.



> Is there a way to force TLS handshake to use different saltlen parameters for testing?

Nope, the standard requires that the saltlen is the same as the digest len and RSA keys smaller than those that would allow for the digest saltlen won't work with such sigalg in TLS-1.3. The code has checks to drop these sigalgs.
