### ISSUE TITLE
make -sj fail

### ISSUE THREAD

**Issue by YuleiXiao** [openssl/openssl#1999]
I compile openssl 1.0.2.j on ubuntu 14.04. I found that if I use ```make -sj```, it failed sometimes. If I just ```make```, it is ok. ```make -sj``` sometime fail, sometime success.

```
./config shared -fPIC --prefix=$HOME/openssl
make -sj
make install
```

last log:
```
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
SSL.3 => ssl.3
make: *** [openssl] Error 2
```

**Comment by levitte** [comment]
Try without `j`.  The 1.0.2 series Makefile isn't parallell friendly.
