### ISSUE TITLE
Build 1.0.2v for clang based compiler C++ Builder Embarcadero

### ISSUE THREAD

**Issue by kevinmoloney7** [openssl/openssl#19994]
As Per the following [documentation](https://github.com/openssl/openssl/blob/master/NOTES-WINDOWS.md#native-builds-using-embarcadero-cbuilder) openssl now supports building for embarcadero C++Builder for the new clang based compiler `bcc32c`. However is it possible to build for versions `1.0.2`. I was able to successfully build using latest master.

**Comment by t8m** [comment]
1.0.2 version is not supported anymore apart from premium support customers.

**Comment by kevinmoloney7** [comment]
When I use the latest version I get the following linker errors:
```
[ilink32 Error] Error: Unresolved external '_SSL_library_init' referenced from
[ilink32 Error] Error: Unresolved external '_SSL_load_error_strings'  referenced from
[ilink32 Error] Error: Unresolved external '_OPENSSL_add_all_algorithms_noconf  referenced from
[ilink32 Error] Error: Unresolved external '_CRYPTO_num_locks' referenced from
[ilink32 Error] Error: Unresolved external '_CRYPTO_set_locking_callback' referenced from
[ilink32 Error] Error: Unresolved external '_SSLv2_client_method' referenced from
[ilink32 Error] Error: Unresolved external '_SSLv23_client_method' referenced from
[ilink32 Error] Error: Unresolved external '_SSLv3_client_method' referenced from
```
I presume that is that these are deprecated functions or is their a compiler flag to enable them?

**Comment by paulidale** [comment]
Most no longer exist.

The SSLv3 stuff is not included in OpenSSL by default but can be included by _configuring_ OpenSSL with `enable-ssl3-method`.  Before blindly doing this, you might want to consider how much you want support a completely broken SSL version.

**Comment by kevinmoloney7** [comment]
Turns out those `sslv` methods were not used in our code base we only run `TLSv1_2_client_method`. I did however have an  initialization routine of 
```
static HANDLE* lock = NULL; 

SSL_library_init();
SSL_load_error_strings();
ERR_load_BIO_strings();
OpenSSL_add_all_algorithms();

if (lock == NULL)
{
        lock = (HANDLE*)OPENSSL_malloc(CRYPTO_num_locks() * sizeof(HANDLE));
        for (int i = 0; i < CRYPTO_num_locks(); i++)
        {
            lock[i] = CreateMutex(NULL, FALSE, NULL);
        }
        CRYPTO_set_locking_callback(win32_locking_callback);
   
 }
```

From doing a bit of research none of this code is required if building with newer versions as this initialization routine is handled automatically by the lib. Is that correct? This was only change required for me to get my code compiling with latest openssl master.

**Comment by mattcaswell** [comment]
> Is that correct?

Yes.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
