### ISSUE TITLE
Typo in macro use of OPENSSL_RAND_SEED_RDTSC

### ISSUE THREAD

**Issue by mclearn** [openssl/openssl#19996]
The macro appears to be mistyped in: https://github.com/openssl/openssl/blob/55e2dd8c3162d7313d9408cb20fca8a4fe6e6f5a/crypto/info.c#L134 .  
I believe it should be OPENSSL_RAND_SEED_RDTSC ('T' and 'D' are transposed).

**Comment by mattcaswell** [comment]
Yep - looks like a bug. Added the "good first issue" and "help wanted" labels.
