### ISSUE TITLE
Intermittent crashes due to error: PKCS7 routines:PKCS7_dataDecode:no recipient matches certificate

### ISSUE THREAD

**Issue by VimalKumarSindh** [openssl/openssl#20026]
I am facing this issue while catching the decryption error in Nodejs. Most of the times, its able to catch the error and throws error gracefully and doesn't crash the server, but sometimes, it crashes the server as it is not able to handle the decryption failed error and throws following error while crashing the server:

Error: 8670700224:error:21070073:PKCS7 routines:PKCS7_dataDecode:no recipient matches certificate:../deps/openssl/openssl/crypto/pkcs7/pk7_doit.c:491: 8670700224:error:21072077:PKCS7 routines:PKCS7_decrypt:decrypt error:../deps/openssl/openssl/crypto/pkcs7/pk7_smime.c:500:

Servers are crashing intermittently because of inability to catch the "Decryption failed" error

**Comment by t8m** [comment]
> Servers are crashing intermittently because of inability to catch the "Decryption failed" error

It is unclear from this if the crash is in the application that calls OpenSSL (perhaps in some incorrect way) or whether this is actually crash in the OpenSSL library itself.

We would need some more details to be able to investigate further.

**Comment by VimalKumarSindh** [comment]
The crash is happening in OpenSSL library itself, but intermittently, I have tried hardcoding the parameter values for PKCS7_Decrypt function but once in 100 times, it is crashing and not returning 1

**Comment by VimalKumarSindh** [comment]
Yeah, I will try that and get back, thanks

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
