### ISSUE TITLE
What/why is `s_client` sending 19 bytes of application data

### ISSUE THREAD

**Issue by franklee26** [openssl/openssl#20022]
Hey all,

I had a quick question on the behaviour of `s_client`. I noticed that after sending various payloads then openssl will always send an application record of 19 bytes (example trace reproduced below):

```
$ openssl11 s_client -connect localhost:8002 -debug -tlsextdebug -state -tls1_3 -ciphersuites TLS_CHACHA20_POLY1305_SHA256 -curves X25519

New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 21 (unable to verify the first certificate)
---
write to 0x1ac7de0 [0x1ae37f3] (32 bytes => 32 (0x20))
0000 - 17 03 03 00 1b 06 68 a7-d1 a9 cb 90 a1 91 0e 5c   ......h........\
0010 - 95 08 fb f4 48 ff b4 be-64 79 e8 50 fb b2 7c c8   ....H...dy.P..|.
write to 0x107ede0 [0x109a7f3] (24 bytes => 24 (0x18))
0000 - 17 03 03 00 13 a2 03 0c-67 c0 aa 77 08 7d 37 cb   ........g..w.}7.
0010 - 39 82 68 19 ba a2 39 bd-  
```

The first record sent is my payload. The 32 bytes is expected. What isn't expected is the 24 byte record following the 32 byte record. I don't know what this is and this is always sent and is always 24 bytes. 

As expected, this record changes size when I specify a non-zero `-record_padding` val. I'm not sure what this record is and if it's expected or not. Is this a close-notify alert? That's the only logical record to be sent since the connection closes after that, but the record type is 0x17 indicating application data and not 0x15

**Comment by mattcaswell** [comment]
> That's the only logical record to be sent since the connection closes after that, but the record type is 0x17 indicating application data and not 0x15

In TLSv1.3 all encrypted records are sent with the application data type. The "real" type is encrypted internally to the record. So a close_notify alert would look like an application data record.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
