### ISSUE TITLE
openssl cmp -server argument used as SNI even if URL or host:port

### ISSUE THREAD

**Issue by noxxi** [openssl/openssl#20031]
While debugging the issue https://serverfault.com/questions/1119743/ I realized that SNI handling in `openssl cmp` seems to be broken. It simply sets the SNI to the argument given by `-server` (or by `server` in the config), even though this argument is documented as being a URL or hostname:port in addition to a simple hostname.

From openssl-3.0.7 (but still presented in openssl-3.1.0-beta1) in apps/cmp.c

<pre>
1926         info->server = opt_server;
...
1935         (void)OSSL_CMP_CTX_set_http_cb(ctx, app_http_tls_cb);
</pre>

In line 1926 it sets `info->server` to the unchanged option from command line or config, i.e. the option which might be the full URL or hostname:port. It then uses `info->server` in `app_http_tls_cb` as it is to set the SNI as seen in apps/lib/apps.c:

<pre>
2466 BIO *app_http_tls_cb(BIO *bio, void *arg, int connect, int detail)
...
2491         SSL_set_tlsext_host_name(ssl, info->server); /* not critical to do */
</pre>

It looks to me like the proper setting for `info->server` in apps/cmp.c should be `host` instead of `opt_server`, but I did not test it.

**Comment by mattcaswell** [comment]
@DDvO

**Comment by DDvO** [comment]
Thanks @noxxi for pointing out this bug and providing a to-the-point analysis and suggestion how to fix this - 
fix is in #20034.

**Comment by dbuettiker** [comment]
Commented [https://github.com/openssl/openssl/pull/20034] on issue/fix #20034 after testing  and seeing that SNI is still broken, but approvals were already made.

**Comment by DDvO** [comment]
> Commented on [pullrequest](https://github.com/openssl/openssl/pull/20034#issuecomment-1383764220) and issue/fix #20034 after testing and seeing that SNI is still broken

Thank you - I've just pushed an extended fix there.

>, but approvals were already made.

The 2nd approval was/is missing anyway :)
