### ISSUE TITLE
Unable to use openssl (undefined reference)

### ISSUE THREAD

**Issue by martinfeussner** [openssl/openssl#20032]
I am new to all this so I hope I don't sound too dumb.

I have spent almost 20 hours the past week trying to "build and install" openssl to access the SHA2/SHA3 hash functions in Dev C++ using C. I have tried numerous approaches I have come accros and none seem to work. I have lost all hope at this point in time. I build and install correctly (this is pretty much the same in all the approaches), I know I am correctly linking the "include" and "lib" directories in the Compiler Options as well as putting the right linkers:
 -L"C:\Program Files\OpenSSL-Win64\lib\libssl.lib" -L"C:\Program Files\OpenSSL-Win64\lib\libcrypto.lib"
OR
-L"C:\Program Files\OpenSSL-Win64\lib\" -lssl -lcrypto

I also use the correct header:
 #include <openssl/sha.h>

Yet I always seem to get "undefined reference" errors when referencing any function.
e.g. bwv_2.c:(.text+0x2661): undefined reference to `SHA256'

	/// Compute the hash value
	char string[] = "hello world!";
	unsigned char hash[SHA256_DIGEST_LENGTH]; 
	
	//calculating the hash 
	SHA256(string, strlen(string), hash); 
	
	//printing the hash 
	for (i = 0; i < SHA256_DIGEST_LENGTH; i++) 
	printf("%02x",hash[i]); 
	
	printf("\n");

**Comment by hlandau** [comment]
One possibility is you are including the headers using a different calling convention for the function prototypes than when OpenSSL was built.

This is a linker error. I forget the exact command, but you should be able to run a command to dump the symbols in libcrypto.lib, and see if the symbol "SHA256" is there, or if it is being given a different name.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
