### ISSUE TITLE
Using Linuxtool

### ISSUE THREAD

**Issue by Furahadickson** [openssl/openssl#20037]
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

**Comment by t8m** [comment]
Unfortunately this question does not contain enough details to answer. This error is usually reported when a certificate is not issued by a trusted certificate authority or the store for trusted CA certificates is not set up properly or at all.

**Comment by Furahadickson** [comment]
Thank you for the reply
I tried to issues but still getting the same errors

**Comment by levitte** [comment]
Please show us in more detail what you did what command you used, etc

**Comment by Furahadickson** [comment]
Thank you, I will do that.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
