### ISSUE TITLE
How to get the exact same encrypted message as sent

### ISSUE THREAD

**Issue by robinren03** [openssl/openssl#20042]
This question is not about any specific OpenSSL version.

I'm trying to retrieve the exact same encrypted application data sent to peer by `SSL_write` in my code. I do know that some APIs or shell commands could encrypt given message, but they are definitely not the same as the one sent to the peer. I wonder if there are any APIs to deal with this problem while maintaining the normal communication flow.

**Comment by t8m** [comment]
TLS communication uses ephemeral symmetric keys derived from key exchange so you definitely cannot get the same encrypted data from anywhere else. Or do I misunderstand your question?

Any proper application of encryption even with static symmetric keys used should not give you the same encrypted data when encrypting the same plaintext as the encrypted data should also contain a random initialization vector (let's ignore SIV or XTS modes which have a specialized usage).

**Comment by robinren03** [comment]
Hi, thanks for your classification. My question is about how can the sender get a same copy of the encrypted data sent to the peer through certain API.

**Comment by mspncp** [comment]
Are you asking how you can *intercept* the encrypted traffic using OpenSSL‘s API?

If that’s the case, you could write and insert a filter BIO instead of connecting the SSL connection directly to the socket.

**Comment by robinren03** [comment]
Great. That should be exactly what I need. Thanks a lot.发自我的iPhone------------------ Original ------------------From: Matthias St. Pierre  ***@***.***>Date: Sat,Jan 14,2023 4:54 PMTo: openssl/openssl ***@***.***>Cc: Yanyu Ren ***@***.***>, Author ***@***.***>Subject: Re: [openssl/openssl] How to get the exact same encrypted message assent (Issue #20042)
Are you asking how you can intercept the encrypted traffic using OpenSSL‘s API?
If that’s the case, you could write and insert a filter BIO instead of connecting the SSL connection directly to the socket.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/openssl/openssl/issues/20042#issuecomment-1382694635",
"url": "https://github.com/openssl/openssl/issues/20042#issuecomment-1382694635",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
