### ISSUE TITLE
Ed25519 pubkey decode fails because parameters value is NULL

### ISSUE THREAD

**Issue by greenpdx** [openssl/openssl#20045]
There are two rust libraries that generate CSR with a NULL for  Subject Public Key Info: Public Key Algorithm: Parameters.
at crypto/x509/x_pubkey.c:458 it thinks that the key material is NULL. 

Here is the generated CSR
-----BEGIN CERTIFICATE REQUEST-----
MIGYMEoCAQAwFzEVMBMGA1UEAxYMRWQyNTUxOSBUZXN0MCwwBwYDK2VwBQADIQBf
cs+mW6kMRhwQziU4+Zt4F+PoHCdI24Vce3LlTpwbEjAHBgMrZXAFAANBADcl2YMq
y5UT3uH/stCUr2uhbzW8RlXrRYNEpjdF78xpkJyFT+8XU2RT+tt6cvHphb9EOwjQ
YN/YdOc1NZ3tyA0=
-----END CERTIFICATE REQUEST-----

 Here is the ASN1 decode using https://webencrypt.org/asn1js/
SEQUENCE (3 elem)
  SEQUENCE (3 elem)
    INTEGER 0
    SEQUENCE (1 elem)
      SET (1 elem)
        SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.4.3 commonName (X.520 DN component)
          IA5String Ed25519 Test
    SEQUENCE (2 elem)
      SEQUENCE (2 elem)
        OBJECT IDENTIFIER 1.3.101.112 curveEd25519 (EdDSA 25519 signature algorithm)
        NULL
      BIT STRING (256 bit) 0101111101110010110011111010011001011011101010010000110001000110000111…
  SEQUENCE (2 elem)
    OBJECT IDENTIFIER 1.3.101.112 curveEd25519 (EdDSA 25519 signature algorithm)
    NULL
  BIT STRING (512 bit) 0011011100100101110110011000001100101010110010111001010100010011110111…

Here is the openssl out
$ openssl req -in tst.csr -text
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: CN = Ed25519 Test
        Subject Public Key Info:
            Public Key Algorithm: ED25519
            Unable to load Public Key
40F72525827F0000:error:03000072:digital envelope routines:X509_PUBKEY_get0:decode error:../crypto/x509/x_pubkey.c:458:
        Attributes:
            Requested Extensions:
    Signature Algorithm: ED25519
    Signature Value:
        37:25:d9:83:2a:cb:95:13:de:e1:ff:b2:d0:94:af:6b:a1:6f:
        35:bc:46:55:eb:45:83:44:a6:37:45:ef:cc:69:90:9c:85:4f:
        ef:17:53:64:53:fa:db:7a:72:f1:e9:85:bf:44:3b:08:d0:60:
        df:d8:74:e7:35:35:9d:ed:c8:0d

Here is RFC2986 section about public key
   AlgorithmIdentifier {ALGORITHM:IOSet } ::= SEQUENCE {
        algorithm          ALGORITHM.&id({IOSet}),
        parameters         ALGORITHM.&Type({IOSet}{@algorithm}) OPTIONAL
   }

**Comment by jamuir** [comment]
In RFC 8410, the following syntax for an Ed25519 public key is given:

```
   SubjectPublicKeyInfo  ::=  SEQUENCE  {
       algorithm         AlgorithmIdentifier,
       subjectPublicKey  BIT STRING
   }
```
see https://www.rfc-editor.org/rfc/rfc8410

Note that there is no "parameters" field.

It seems as though `tst.csr` is not a valid csr for Ed25519.

For reference, here is the output of "asn1parse":

```
$ openssl asn1parse -dump  -in tst.csr 
    0:d=0  hl=3 l= 152 cons: SEQUENCE          
    3:d=1  hl=2 l=  74 cons: SEQUENCE          
    5:d=2  hl=2 l=   1 prim: INTEGER           :00
    8:d=2  hl=2 l=  23 cons: SEQUENCE          
   10:d=3  hl=2 l=  21 cons: SET               
   12:d=4  hl=2 l=  19 cons: SEQUENCE          
   14:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   19:d=5  hl=2 l=  12 prim: IA5STRING         :Ed25519 Test
   33:d=2  hl=2 l=  44 cons: SEQUENCE          
   35:d=3  hl=2 l=   7 cons: SEQUENCE          
   37:d=4  hl=2 l=   3 prim: OBJECT            :ED25519
   42:d=4  hl=2 l=   0 prim: NULL              
   44:d=3  hl=2 l=  33 prim: BIT STRING        
      0000 - 00 5f 72 cf a6 5b a9 0c-46 1c 10 ce 25 38 f9 9b   ._r..[..F...%8..
      0010 - 78 17 e3 e8 1c 27 48 db-85 5c 7b 72 e5 4e 9c 1b   x....'H..\{r.N..
      0020 - 12                                                .
   79:d=1  hl=2 l=   7 cons: SEQUENCE          
   81:d=2  hl=2 l=   3 prim: OBJECT            :ED25519
   86:d=2  hl=2 l=   0 prim: NULL              
   88:d=1  hl=2 l=  65 prim: BIT STRING        
      0000 - 00 37 25 d9 83 2a cb 95-13 de e1 ff b2 d0 94 af   .7%..*..........
      0010 - 6b a1 6f 35 bc 46 55 eb-45 83 44 a6 37 45 ef cc   k.o5.FU.E.D.7E..
      0020 - 69 90 9c 85 4f ef 17 53-64 53 fa db 7a 72 f1 e9   i...O..SdS..zr..
      0030 - 85 bf 44 3b 08 d0 60 df-d8 74 e7 35 35 9d ed c8   ..D;..`..t.55...
      0040 - 0d
```

**Comment by greenpdx** [comment]
Ok, I was looking at the earlier  RFC where is was optional.
