### ISSUE TITLE
SSL_client_hello_get0_ext() wrong documention

### ISSUE THREAD

**Issue by chai00xxdd** [openssl/openssl#20050]
version :1.1.1 and above
hey in the open ssl documention 
https://www.openssl.org/docs/man1.1.1/man3/SSL_client_hello_get0_ext.html
it says that

SSL_client_hello_get1_extensions_present() can be used prior to SSL_client_hello_get0_ext(), to determine which extensions are present in the ClientHello before querying for them. The out and outlen parameters are both required, and on success the caller must release the storage allocated for *out using OPENSSL_free(). The contents of *out is an array of integers holding the numerical value of the TLS extension types in the order they appear in the ClientHello. *outlen contains the number of elements in the array. In situations when the ClientHello has no extensions, the function will return success with *out set to NULL and *outlen set to 0.

in the documnetion it says that on sucess of SSL_client_hello_get0_ext
the caller need to release out with OPENSSL_FREE. but it doesnt look like it allocated there, so i think its wrong to call OPENSSL_free.
am i  right?
cus all what SSL_client_hello_get0_ext does is to loop on an array of extensions and then return a pointer if found the
requested extension. its not allocated it or copy it.

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/ssl/ssl_lib.c#L5222

**Comment by t8m** [comment]
IMO the documentation is fairly clear in the sense that  `the caller must release the storage allocated for *out using OPENSSL_free()`. The `out` in that sentence is an output parameter of the SSL_client_hello_get1_extensions_present() function as that sentence is in the paragraph for the SSL_client_hello_get1_extensions_present() and not SSL_client_hello_get0_ext().

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
