### ISSUE TITLE
Weird behavior when generating Diffie Hellman private keys

### ISSUE THREAD

**Issue by Marceb22** [openssl/openssl#20056]
Hey guys.

I've been testing around with fixed keys for Diffie Hellman Key Exchange and found a weird behavior that I can't find in the code and it doesn't seem to follow a fixed pattern.  I've used the RAND_set_rand_method() Method, to set a fixed buffer for the private key. When looking at the resulting keys I've noticed a strange behavior in the way that the first hex value was changed. 

I am using OpenSSL 1.1.1s on a Ubuntu machine. 

**Here an example of a 512 byte private key:**
**6121**2121212121212121212121212121212121212121212121212121212121212121212
12121212121212121212121212121212121212121212121212121212121212121212121
21212121212121212121212121212121212121212121212121212121212121212121212
12121212121212121212121212121212121212121212121212121212121212121212121
21212121212121212121212121212121212121212121212121212121212121212121212
12121212121212121212121212121212121212121212121212121212121212121212121
21212121212121212121212121212121212121212121212121212121212121212121212
121212121212121
The sequence of "0x21" is being repeated but the first hex value is changed from 2 to 6. 

For instance, the following changes have also been done:
**Case 1**
0x0 (0000 (bit representation))
changed to -> 4 (0100 (bit representation))

 **Case 2**
 0xb = **11** (1011 (bit representation))
 changed to -> 7  (0111 (bit representation))
 
 **Case 3**
0x4 = **4** (0100 (bit representation))
no change
 
It would seem like the integer 4 is added at first glance, but that doesn't apply and an XOR operation doesn't fit all the changes either. I couldn't find any code that actually makes these changes. Any idea where that happens? It really bugs me that I can't find the source of this changes. 

Thank you in advance. 
Marc

**Comment by t8m** [comment]
See https://github.com/openssl/openssl/blob/master/crypto/dh/dh_key.c#L320

The BN_RAND_TOP_ONE flag causes the topmost bit to be set to 1 by OR operation.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
