### ISSUE TITLE
Potentially incomplete check in X509V3_EXT_print()

### ISSUE THREAD

**Issue by nielsdos** [openssl/openssl#20066]
Hello.

I'm working on a static analysis tool to detect missing and incorrect error checking. It works by inferring an error specification for error-returning functions and later it verifies whether checks adhere to the specification.

My tool noticed that the following code checks whether the return value of `X509V3_EXT_METHOD*->i2r` is zero, and if it is, sets `ok = 0`.
https://github.com/openssl/openssl/blob/ed77c14d91ec008d4d78d7293f37bd4aa60071f0/crypto/x509/v3_prn.c#L124-L125

One of the possible call targets is `i2r_ADMISSION_SYNTAX`, which sets the return value to -1 if an error occurred, thus not setting `ok = 0` in the above code snippet.
https://github.com/openssl/openssl/blob/ed77c14d91ec008d4d78d7293f37bd4aa60071f0/crypto/x509/v3_admis.c#L200-L202

I was wondering whether this was a real bug. If it is I could create a PR that changes its return value to 0. If that solution would be a backwards compatible break, I would propose to change the check instead from `if (!method->i2r(method, ext_str, out, indent))` to `if (method->i2r(method, ext_str, out, indent) <= 0)`.

Thanks in advance!

**Comment by mattcaswell** [comment]
> I was wondering whether this was a real bug.

I agree. This looks like a bug to me.

> If it is I could create a PR that changes its return value to 0.

This seems like the most sensible solution. Please feel free to create a PR for that!
