### ISSUE TITLE
`verify` does not follow compile time value for `DOPENSSL_TLS_SECURITY_LEVEL`

### ISSUE THREAD

**Issue by maxmoehl** [openssl/openssl#20060]
While tracing a bug in HAProxy I found out that `openssl verify` does not follow the value for `DOPENSSL_TLS_SECURITY_LEVEL` set at compile time. When compiling with level 2 (like it is done in ubuntu jammy) and manually verifying a chain that uses SHA1 the chain is validated without an error. If the same openssl is used through HAProxy the compile time value is used and the error `X509_V_ERR_CA_MD_TOO_WEAK` is returned.

This can be reproduced by compiling openssl with `DOPENSSL_TLS_SECURITY_LEVEL=1` or higher and calling `openssl verify -CAfile ./ca.pem ./cert.pem` and comparing it to `openssl verify -auth_level 1 -CAfile ./ca.pem ./cert.pem`. The former will succeed and the latter will fail:

```
$ openssl version -a
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
built on: Thu Oct 27 17:06:56 2022 UTC
platform: debian-amd64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-WsPfAX/openssl-3.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-3"
MODULESDIR: "/usr/lib/x86_64-linux-gnu/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xfffa3203578bffff:0x7a9
$ openssl verify -CAfile ./root.pem ./cert.pem
./I6.pem: OK
$ openssl verify -auth_level 1 -CAfile ./root.pem ./cert.pem
--- cert details ---
error 68 at 0 depth lookup: CA signature digest algorithm too weak
error ./cert.pem: verification failed
```

Is this expected behaviour? [man 1 openssl-verification-options](https://man.archlinux.org/man/openssl-verification-options.1ssl.en#auth_level) states that not providing the `-auth_level` parameter sets it to `-1` (not set), I would expect the compile time value to be used if the value is not set. If this is expected: Is `-1` used or is it implicitly converted to `0`?

**Comment by t8m** [comment]
The `OPENSSL_TLS_SECURITY_LEVEL` affects only TLS and not the verify command or calls to X509_verify() by external applications. This is kind of implied by the TLS in the variable name.

**Comment by t8m** [comment]
Also the `-auth_level` not set means the level 0 will be used.

**Comment by maxmoehl** [comment]
Thanks a lot, that makes sense!
