### ISSUE TITLE
Use C23 nodiscard feature in functions where return values should be checked

### ISSUE THREAD

**Issue by schwabe** [openssl/openssl#20065]
First of all I understand I want to say that I understand that this might be a controversial topic but sometimes ignoring error from OpenSSL's function can lead to security vulnerabilities since people assume that some functions will always succeed.

To avoid this problem C23 (https://en.cppreference.com/w/c/language/attributes/nodiscard) and C++17 (https://en.cppreference.com/w/cpp/language/attributes/nodiscard) added a ``[[nodiscard]]`` annotation that will trigger compiler warnings in these situation.

I am willing to put some work and effort into adding this annotation but I think proposing a PR without previously discussing if that is desired feature and if so, how it should be implemented in term of preprocessor magic and so on is important.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
