### ISSUE TITLE
How to get EVP_PKEY_base_id after build?

### ISSUE THREAD

**Issue by Nitr0-G** [openssl/openssl#20075]
I did everything according to the instructions(https://github.com/openssl/openssl/blob/master/NOTES-WINDOWS.md#quick-start), but I didn't get these libraries after building openssl
```
TS_VERIFY_CTS_set_certs 
EVP_PKEY_base_id 
EVP_MD_size 
```
How can I get them?

**Comment by OSPFvX** [comment]
> All of these symbols are macros. You need to include appropriate header files (ts.h and evp.h) when building sources that use them.

I'll try it now thanks!

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
