### ISSUE TITLE
FIPs provider loading failed with digitally signed "fips.dll" but worked fine with unsigned "fips.dll".

### ISSUE THREAD

**Issue by durgakishore** [openssl/openssl#20071]
Hi team, 

We created a shared OpenSSL library 3.0.7 by compiling and using it in our code. When we use "fips.dll", the FIPs provider loads without any issues. We must sign all necessary OpenSSL files in accordance with our release methodology. However, FIPs provider is not loading and observed below errors after digitally signing fip.dll. 

error:1C8000D5:Provider routines::missing config data.
error:1C8000E0:Provider routines::fips module entering error state.
error:1C8000D8:Provider routines::self test post failure.
error:078C0105:common libcrypto routines::init fail.

We used the same fipsmodule.cnf, openssl.nf, and environment variable OPENSSL MODULES in both instances. We had a problem with "fips.dll," which was digitally signed.

Is there a verified technique to sign fips.dll that is based on open source openssl code?
After being digitally signed, has fips.dll undergone any changes?
How are digitally signed fips.dll file used in code?
Could someone please help us with this problem?

**Comment by t8m** [comment]
The fips provider DLL is checksummed during the selftest with the checksum stored in fipsmodule.cnf. If you modify the DLL file after that checksum is computed and stored (that is being done during the build), the checksum will not match and you'll see the self test post failure. One possibility would be to remove the fipsmodule.cnf and make it again by `make providers/fipsmodule.cnf` after signing the fips.dll.

**Comment by mattcaswell** [comment]
Note that the fips module must be built in accordance with the instructions in Appendix A of the security policy. If you don't follow the security policy then you're not FIPS.

https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4282.pdf

**Comment by durgakishore** [comment]
@t8m Thank you very much. I'll try it now.

**Comment by durgakishore** [comment]
@mattcaswell Yes, we followed the same procedure to get the FIPs support. Thanks for your response.

**Comment by ronglianglei** [comment]
@mattcaswell I have a question about the documentation "The FIPS module must have the self tests run, and the FIPS module config file output generated on every machine that it is to be used on. For OpenSSL 3.0, you must not copy the FIPS module config file output data from one machine to another." What's the "FIPS module config file"? Is the fips.dll? or fipsmodule.cnf or the checksum in fipsmodule.cnf? 
Windows server doesn't have openssl by default. I wondered if  Windows version of "openssl fipsinstall -out /usr/local/ssl/fipsmodule.cnf -module /usr/local/lib/ossl-modules/fips.so" command has to be ran in every machine?

**Comment by mattcaswell** [comment]
> "The FIPS module must have the self tests run, and the FIPS module config file output generated on every machine that it is to be used on. For OpenSSL 3.0, you must not copy the FIPS module config file output data from one machine to another."

I suppose you are referring to [README-FIPS.md](https://github.com/openssl/openssl/blob/e9cffe90f9aae9d5d8a00de5eabe66dc02fef792/README-FIPS.md?plain=1#L69-L79). That text is talking about fipsmodule.cnf.

**Comment by t8m** [comment]
Yes, you'll need to package openssl.exe and run the openssl fipsinstall during the installation of the fips provider on the target machine.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
