### ISSUE TITLE
EVP_MAC API should provide a way to query the digest algorithm used, if any

### ISSUE THREAD

**Issue by neverpanic** [openssl/openssl#20074]
The EVP_MAC and EVP_MAC_CTX APIs do not allow querying the digest algorithm they internally use. The essentially applies for the use of HMAC only, although a similar problem exists for CMAC and GMAC, where users cannot determine which cipher was used.

Having this information available would be helpful to determine whether the combination of mac and digest algorithm is acceptable in certain situations. For example, let's say I would want to add a check to ensure that KBKDF is not used with SHAKE128 or SHAKE256. However, in the implementation of KBKDF in `providers/implementations/kdfs/kbkdf.c`, there's only a reference to an `EVP_MAC_CTX *ctx_init`. There is no way to obtain the digest used in that MAC (if any). A KDF implementation could use its `set_ctx_params` function to also fetch a copy of the digest implementation to be used since the parameter names are the same, but this feels prone to errors because it duplicates information.

A `EVP_MAC_CTX_get0_md(EVP_MAC *)` function, or a gettable `digest` parameter on EVP_MACs could solve this.

**Comment by eenthropy** [comment]
That Is nice entry @@ Key.. goes up

**Comment by t8m** [comment]
> A KDF implementation could use its `set_ctx_params` function to also fetch a copy of the digest implementation to be used since the parameter names are the same, but this feels prone to errors because it duplicates information.

You would not fetch it but just record the algorithm name. But yeah, it would duplicate the information.

**Comment by t8m** [comment]
> > A KDF implementation could use its `set_ctx_params` function to also fetch a copy of the digest implementation to be used since the parameter names are the same, but this feels prone to errors because it duplicates information.
> 
> You would not fetch it but just record the algorithm name. But yeah, it would duplicate the information.

Actually instead of recording it I would just put the check for the disallowed algorithm there right at the call where the DIGEST or CIPHER is set.

**Comment by t8m** [comment]
> A `EVP_MAC_CTX_get0_md(EVP_MAC *)` function, or a gettable `digest` parameter on EVP_MACs could solve this.

Hmm, there is a further problem with this - provider calls cannot have EVP_MD parameter. So in the end you would need to fetch the algorithm anyway. Not sure what would the gettable `digest` parameter provide as that would be a UTF8 string anyway which you would have to fetch to compare against the canonical name with EVP_MD_is_a(). So I am not convinced this feature would be really useful.

**Comment by neverpanic** [comment]
No, you would have to fetch it, unless you want to compare against all possible names of an algorithm. Users could be doing

```c
OSSL_PARAM params[] = {
    OSSL_PARAM_utf8_string(OSSL_KDF_PARAM_DIGEST, "SHAKE-256"),
    OSSL_END
}
EVP_KDF_CTX_set_params(params)
```

or

```c
OSSL_PARAM params[] = {
    OSSL_PARAM_utf8_string(OSSL_KDF_PARAM_DIGEST, "2.16.840.1.101.3.4.2.11"),
    OSSL_END
}
EVP_KDF_CTX_set_params(params)
```

so unless you want to check on this string with every possible name of an algorithm, you'd have to fetch it and use `EVP_MD_is_a(digest, "SHAKE-256")`.

Checking for it and disallowing right when it is being set is an option, but also requires the same fetch (that is then repeated inside the EVP_MAC) – and that's only an option when you actually want to deny it outright, but in my case I just want to add a gettable parameter that returns a different value. That could also be done by keeping a copy of that parameter's supposed value in the `KBKDF` struct, but it would be much nicer to only compute that value on-demand if it is needed.

> Not sure what would the gettable digest parameter provide as that would be a UTF8 string anyway which you would have to fetch to compare against the canonical name with EVP_MD_is_a(). So I am not convinced this feature would be really useful.

The return value of `EVP_MD_get0_name()`, which from what I've seen is always the first name and thus stable.

**Comment by t8m** [comment]
OK, so you would require the MAC implementation to return the EVP_MD_get0_name() and not the name the user has passed in set_ctx_params(). That would work, except the case when some MAC implementation would not conform to this requirement.

**Comment by levitte** [comment]
> ... except the case when some MAC implementation would not conform to this requirement.

I think this is where the mantra "know your providers" comes in.  For each implementation, the first name in the name string is its canonical name.

That being said, the idea is really that the user is expected to take full control, i.e. decide what digest they want to use and go for that.  This is just as much the case with the old EVP_PKEY methods to do HKDF in 1.1.1 and older, as indicated by the lack of getters in https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/include/openssl/kdf.h

Of course, this leaves room for improvement...  but as you have already seen, some improvements may prove fragile for a number of reasons.
