### ISSUE TITLE
ChaCha20-Poly1305 fails to allow you to set a different IV length

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#20084]
The ChaCha20-Poly1305 man page suggests that you should be able to change the IV length from the default of 12.

However the following code will fail in the second `EVP_EncryptInit_ex` call:

```` c
   if (!EVP_EncryptInit_ex(ctx, EVP_chacha20_poly1305(), NULL, NULL, NULL))
        goto err;
    if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_IVLEN, ivlen, NULL) <= 0)
        goto err;
    if (!EVP_EncryptInit_ex(ctx, NULL, NULL, key, iv))
        goto err;
````

The ctrl actually succeeds, but then attempting to use an iv of that length issues an error:

````
40F70DB59A7F0000:error:1C80006D:Provider routines:ossl_cipher_generic_initiv:invalid iv length:providers/implementations/ciphers/ciphercommon.c:651:
````
Internally, in the provider implementation, there seems to be confusion between the `nonce_len` field and the `ivlen` fields.

**Comment by levitte** [comment]
Hmmm...  we essentially have two chacha20-poly1305 implementations, `providers/implementations/ciphers/cipher_chacha20_poly1305.c` and `providers/implementations/ciphers/cipher_chacha20_poly1305_hw.c`.  The former doesn't use the common cipher stuff...  I think? ...  and the latter has its own initiv:

https://github.com/openssl/openssl/blob/091f532e0ef57cff71ab710c07eb5f6f9bb88b22/providers/implementations/ciphers/cipher_chacha20_poly1305_hw.c#L76-L105

So I wonder, how did we end up in the generic initiv???

@slontis, might you lend us a hand here?  You have pretty much architected the cipher implementation, so you might know top of your head faster than Matt and I can dig...

**Comment by slontis** [comment]
@levitte the *1305poly.c file contains the provider dispatch table. Inside this file it contains a hw pointer used to access common lower level functions.
The _hw.c file  just implements these common set to lower level functions. (For implementations  with multiple platform implementations there are different lower level functions).

**Comment by slontis** [comment]
The generic cipher encrypt init does the following..
````
static int chacha20_poly1305_einit(void *vctx, const unsigned char *key,
                                  size_t keylen, const unsigned char *iv,
                                  size_t ivlen, const OSSL_PARAM params[])
{
    int ret;

    /* The generic function checks for ossl_prov_is_running() */
    ret = ossl_cipher_generic_einit(vctx, key, keylen, iv, ivlen, NULL);
    if (ret && iv != NULL) {
        PROV_CIPHER_CTX *ctx = (PROV_CIPHER_CTX *)vctx;
        PROV_CIPHER_HW_CHACHA20_POLY1305 *hw =
            (PROV_CIPHER_HW_CHACHA20_POLY1305 *)ctx->hw;

        hw->initiv(ctx);
    }
    ````

**Comment by slontis** [comment]
ossl_cipher_generic_einit() calls
````
static int cipher_generic_init_internal(PROV_CIPHER_CTX *ctx,
                                        const unsigned char *key, size_t keylen,
                                        const unsigned char *iv, size_t ivlen,
                                        const OSSL_PARAM params[], int enc)
{
    ctx->num = 0;
    ctx->bufsz = 0;
    ctx->updated = 0;
    ctx->enc = enc ? 1 : 0;

    if (!ossl_prov_is_running())
        return 0;

    if (iv != NULL && ctx->mode != EVP_CIPH_ECB_MODE) {
        if (!ossl_cipher_generic_initiv(ctx, iv, ivlen))
            return 0;
    }
    if (iv == NULL && ctx->iv_set
        && (ctx->mode == EVP_CIPH_CBC_MODE
            || ctx->mode == EVP_CIPH_CFB_MODE
            || ctx->mode == EVP_CIPH_OFB_MODE))
        /* reset IV for these modes to keep compatibility with 1.1.1 */
        memcpy(ctx->iv, ctx->oiv, ctx->ivlen);
        ....
        ....
````

**Comment by slontis** [comment]
Note this code was based of "e_chacha20_poly1305.c" - not off of a deep understanding of the chacha-poly1305 algorithm.

**Comment by slontis** [comment]
The e_*.c does this for the ctrl..

````
    case EVP_CTRL_AEAD_SET_IVLEN:
        if (arg <= 0 || arg > CHACHA20_POLY1305_MAX_IVLEN)
            return 0;
        actx->nonce_len = arg;
        return 1;
````

**Comment by slontis** [comment]
In the old e_code it has EVP_CIPH_CUSTOM_IV_LENGTH set as a flag. This is only used by AES and ARIA so I think this is why this happens for this cipher.

**Comment by slontis** [comment]
We obviously have no test vectors for this case but it basically looks like the counter is always 12 bytes.. The iv just gets left zero padded if it is less than 12.. So a test vector should be fairly easy to do.. I will try adding a custom init instead of using the generic one..

**Comment by romen** [comment]
Why do we even support IVs of less than 12 bytes? As far as I can read in all RFCs and documentation about regular ChaCha20-Poly1305 and its use in standard protocols, the nonce/IV is always 12 bytes, and the only mentions of "shorter nonces" is when part of the 12-bytes (usually the first 32-bits) are used as a counter/identifier and the remaining (usually 8) bytes as the only "random" part of the nonce.

**Comment by davidben** [comment]
https://www.openssl.org/news/secadv/20190306.txt is an example of a security advisory that OpenSSL had to issue because of its nonstandard ChaCha20-Poly1305 behavior. Indeed not covered in the advisory is that, because OpenSSL just pads short nonces up, short nonces of different lengths still collide with each other. A library user less familiar with ChaCha20-Poly1305 might incorrectly assume that OpenSSL's APIs conform to standard AEAD security expectations and use two colliding nonces of different lengths.

If OpenSSL decides to continue with this nonstandard behavior, the documentation should be updated clearly state that its ChaCha20-Poly1305 implementation doesn't conform to the specification and that using incorrect nonce lengths risks nonce reuse where one wouldn't expect it.

Alternatively, OpenSSL can align with the standard and all these issues go away.
