### ISSUE TITLE
New 'hybrid CRT' target for Windows

### ISSUE THREAD

**Issue by trueqbit** [openssl/openssl#20080]
Since Windows 7, Windows has delivered the ABI-stable subset of the C runtime as part of the operating system in the form of the "Universal CRT".
This allows libraries to be created without the ballast of a statically linked in runtime and without the need to deploy the "VC runtime", i.e. a kind of lightweight yet self-contained hybrid.

This approach is officially used by the "Windows App SDK" and is particularly useful for C libraries, as they usually encapsulate allocation/deallocation within the library.

This is very easy to achieve:

1. instruct the msvc compiler to link to the static runtime library using the compiler flag `/MT`.
2. instruct the linker to link against the 'shared' Universal CRT by using the linker flags `/NODEFAULTLIB:libucrt.lib /DEFAULTLIB:ucrt.lib`.

**Comment by matbech** [comment]
More information about Hybrid CRT can be found here:
https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/HybridCRT.md

**Comment by trueqbit** [comment]
Thanks everyone for your efforts!
