### ISSUE TITLE
MD2/MD4/MD5 man page recommends SHA-1

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#20083]
The MD2/MD5/MD5 man page has this recommendation:

> MD2, MD4, and MD5 are recommended only for compatibility with existing applications. In new applications, SHA-1 or RIPEMD-160 should be preferred.

https://www.openssl.org/docs/manmaster/man3/MD5_Init.html

We should probably recommend something better than SHA-1/RIPEMD-160, e.g SHA-256

**Comment by paulidale** [comment]
To play it safe, SHA3-512?

**Comment by hlandau** [comment]
I think SHA-256 or SHA-512 are reasonable recommendations. SHA-3 hasn't seen the same uptake or enthusiasm and the panic that was occurring when MD5 and SHA1 fell in quick succession (triggering the creation of the SHA-3 competition) hasn't continued to SHA-2. Unless I'm mistaken.

**Comment by mattcaswell** [comment]
Sounds good to me

**Comment by t8m** [comment]
I'll create a PR.

**Comment by t8m** [comment]
The fix in #20095 was merged.
