### ISSUE TITLE
OpenSSL 1.1.1 security support after EOL

### ISSUE THREAD

**Issue by shaheena86** [openssl/openssl#20094]
Hello Guys,

I wanted to check that once the OpenSSL 1.1.1x series packages are EOL can we still expect security fixes from source packages?
I am using Debian 11 hence I am on a 1.1.1n OpenSSL.

Regards,
Shaheena K

**Comment by t8m** [comment]
If you use Debian OpenSSL packages, you should ask Debian. I assume they will supply security fixes for OpenSSL as long as the Debian release is supported.

The OpenSSL project will supply security fixes for 1.1.1 release after EOL only to our premium support customers.
