### ISSUE TITLE
Potentially incorrect check in generate_q_fips186_4

### ISSUE THREAD

**Issue by nielsdos** [openssl/openssl#20100]
Hello.

I'm working on a static analysis tool to detect missing and incorrect error checking. It works by inferring an error specification for error-returning functions and later it verifies whether checks adhere to the specification.

The following code checks for an error return value of `RAND_bytes_ex`:
https://github.com/openssl/openssl/blob/c3bd630df0c3630c66155fb8c4baf54810d24695/crypto/ffc/ffc_params_generate.c#L330-L333

The documentation of RAND_bytes_ex says however:
> RAND_bytes_ex() and RAND_priv_bytes_ex() are the same as RAND_bytes() and RAND_priv_bytes() except that they both take additional strength and ctx parameters.

and also:
> RAND_bytes() and RAND_priv_bytes() return 1 on success, -1 if not supported by the current RAND method, or 0 on other failure.

So it seems to me that `RAND_bytes_ex` can also return 0 on failure. This is not handled by the above check.
Furthermore, looking at other usages of `RAND_bytes_ex`, like the one in `generate_q_fips186_2` in the same file; they also check for `<= 0` instead of `< 0`.

I was wondering whether this is a real bug. If it is I could create a PR that changes the check to `<= 0`.

Thanks in advance!

**Comment by mspncp** [comment]
> I was wondering whether this is a real bug. If it is I could create a PR that changes the check to <= 0.

Thank you for your report, it's indeed a bug. I checked the source code using grep (including manual checks of the non-obvious multiline cases) and fortunately it seems to be the only location. Pull request welcome! :-)

cc @slontis @paulidale

**Comment by nielsdos** [comment]
Thank you for your confirmation :) I created a PR to fix this.
