### ISSUE TITLE
Publish new Releases as Releases rather than under Tags

### ISSUE THREAD

**Issue by AachoLoya** [openssl/openssl#20114]
Virtually all projects on github publish releases under the [Releases category](https://github.com/openssl/openssl/releases) . Therefore, its easy to watch for new releases by using github's Watch feature (Watch -> Custom -> Select Releases option, and click Apply). 

Since OpenSSL releases are all under [Tags](https://github.com/openssl/openssl/tags), its not possible to get a notification when a new release is available. Considering its a critical security library, it would be helpful if releases were published in the Releases category, so we can get timely notifications and update our projects promptly.

**Comment by t8m** [comment]
We can consider this. I suppose OMC should discuss this, or is it rather an OTC topic?

**Comment by hlandau** [comment]
It's worth noting that 'Releases' are themselves based on tags. So basically it's just a question of hitting the button to make a tag count as a release. Seems like a reasonable proposal.

**Comment by mattcaswell** [comment]
I think there are some files (e.g. fuzz files???) that are in our repo, but don't make it into our release tar balls, i.e. so the releases on github and the releases from www.openssl.org would be different. The PGP signatures and digests would also not match.

**Comment by hlandau** [comment]
@mattcaswell Could also be argued as a reason to do this. As things stand, GitHub already provides autogenerated tarballs of any tag. Many projects don't recommend use of these (I believe one reason is these used to be nondeterministic, meaning their hashes could change, though I don't know if this is still the case), and therefore upload their own tarballs explicitly, which requires you to create a release. With a 'release' you can attach arbitrary files.

There is a `gh` CLI tool for managing releases so it probably wouldn't be hard to add this to our release automation, including upload of our official tarballs.

**Comment by mattcaswell** [comment]
If that's the case then that seems reasonable.

**Comment by t8m** [comment]
Yes, we can upload our tarballs into the GH releases.

**Comment by paulidale** [comment]
OMC: **does the OTC think that we should change our release process to do this?**

**Comment by levicki** [comment]
It would also be cool if we had official OpenSSL binaries built and published on Releases, but I guess that should be a separate topic?

**Comment by t8m** [comment]
This is definitely a separate topic and also very unlikely to happen.

**Comment by levicki** [comment]
@t8m Can you please clarify whether the reason for that being unlikely is technical or political in nature? It it is political there's no point in creating an issue to discuss it. If technical, then I will create a new issue.

**Comment by t8m** [comment]
There is definitely a technical reason - the possible number of target platforms, build environments and configuration options is so huge that it would be a quite big task to generate these binaries. But there are of course also organizational and "political" reasons.

**Comment by levicki** [comment]
@t8m Thanks, then I will still create an issue for further questions.

**Comment by t8m** [comment]
**OTC to OMC: We think we should extend the existing release process to create the GitHub releases where the tarballs and other artefacts of the existing release process would be uploaded.**

**Comment by t8m** [comment]
I've added the latest releases (3.0.7, 1.1.1s, 3.1.0-beta1).
