### ISSUE TITLE
Potential memory leak in `apps/s_server.c`

### ISSUE THREAD

**Issue by nikslyon19** [openssl/openssl#20110]
https://github.com/openssl/openssl/blob/c3bd630df0c3630c66155fb8c4baf54810d24695/apps/s_server.c#L226-L237

From the 3 function calls in the if-check, only `SSL_SESSION_set1_master_key()` seems to return a value other than 1.

Potentially, if `SSL_SESSION_set1_master_key()` fails, there is no attempt being made to free `tmpsess` at the moment.

**Comment by akai54** [comment]
Hey, can I take care of this ?, this is my first contribution as I'm still a CS student, thanks in advance

**Comment by paulidale** [comment]
Feel free to take it on.
