### ISSUE TITLE
X509_V_ERR_EC_KEY_EXPLICIT_PARAMS after upgrading from 1.1.1 to 3.0.2

### ISSUE THREAD

**Issue by user8547** [openssl/openssl#20117]
After upgrading from OpenSSL v1.1.1 to 3.0.2 (Ubuntu 22.04) I get  error "X509_V_ERR_EC_KEY_EXPLICIT_PARAMS" when verifying end-entity certificates that have explicit curve parameters (ICAO eMRTD certificates have them).

In the source code I see that in v1.1.1 the check was enforced only in the strict mode, but in v3.0.2 it is applied always and there is no way to opt out.

**Comment by t8m** [comment]
Yes, this is intentional. Explicit curve parameters are dangerous. The verification error can be dismissed if the application registers a verification callback.

**Comment by user8547** [comment]
I had an impression that explicit curve parameters have been deprecated and are dangerous in TLS context.
There is a good reason why ICAO standards mandate explicit curve parameters only.

Do you know whether it is possible to define such callback outside TLS/SSL use case? I.e., when using X509_STORE to verify certificate chain?

Thanks!

**Comment by t8m** [comment]
Yes, you set the verify callback on the X509_STORE_CTX by the X509_STORE_CTX_set_verify_cb() function. Please see the manual pages.

**Comment by user8547** [comment]
Thanks!
However, it seems that currently this functionality is not exposed in PyOpenSSL.
For now downgrading to v1.1.1 with a hope that in the future some verification flag enabling explicit EC curve parameters will be added to openssl :)

**Comment by t8m** [comment]
> For now downgrading to v1.1.1 with a hope that in the future some verification flag enabling explicit EC curve parameters will be added to openssl :)

That is very unlikely to happen.

I'd recommend asking PyOpenSSL to implement the verification callback functionality. That callback is useful in other scenarios too.

**Comment by Aaargh20318** [comment]
> Yes, you set the verify callback on the X509_STORE_CTX by the X509_STORE_CTX_set_verify_cb() function. Please see the manual pages.

This is not possible when verifying a CMS SignedData structure using CMS_verify as it does not expose the X509_STORE_CTX used.

**Comment by t8m** [comment]
> > Yes, you set the verify callback on the X509_STORE_CTX by the X509_STORE_CTX_set_verify_cb() function. Please see the manual pages.
> 
> This is not possible when verifying a CMS SignedData structure using CMS_verify as it does not expose the X509_STORE_CTX used.

It exposes X509_STORE and there is an equivalent X509_STORE_set_verify_cb() for X509_STORE.

**Comment by Aaargh20318** [comment]
> It exposes X509_STORE and there is an equivalent X509_STORE_set_verify_cb() for X509_STORE.

Thanks, I was looking for that but somehow missed it.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
