### ISSUE TITLE
Is there any expected release date for the fix of #19643 issue?

### ISSUE THREAD

**Issue by anton-kazlouski** [openssl/openssl#20111]
Hello! About a month or so our automatic scanner for vulnerabilities reported that there is a risk from one of dependencies, referencing to [this](https://github.com/openssl/openssl/issues/19643) issue. I was following the thread and if I understood correctly a fix has been merged to the master already. Thus I wonder if there is any estimated release date for that fix.

**Comment by mattcaswell** [comment]
There has been no release date announced for the next release as yet. Typically one comes along every few months or so. The last release was in early November.

**Comment by anton-kazlouski** [comment]
> There has been no release date announced for the next release as yet. Typically one comes along every few months or so. The last release was in early November.

Yeah... I was trying to find if there is any release schedule or something, but nothing, thus decided to ask.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by t8m** [comment]
Fix released long time ago
