### ISSUE TITLE
CCM8 support

### ISSUE THREAD

**Issue by boaks** [openssl/openssl#20115]
I currently try to test the interoperability of PR #18185.
(Commit 7ad8229f0663d7301fe6f6d8eda56a60197809e1 in [rpk-fixup](https://github.com/vdukhovni/openssl/commits/rpk-fixup))

Using `-cipher ECDHE-ECDSA-AES128-CCM8`, which was working in v1.1.1, seems to be not longer supported. I get: "statem_clnt.c:4093:No ciphers enabled for max supported SSL/TLS version"

```
openssl s_client -debug -dtls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -connect californium.eclipseprojects.io:5684
```

Is there a way to enable CCM8 for `s_client`/`s_server`?

**Comment by t8m** [comment]
You need to use `@SECLEVEL=0` with CCM8 ciphers. I.e., `ECDHE-ECDSA-AES128-CCM8:@SECLEVEL=0`

**Comment by boaks** [comment]
Thanks a lot for the fast answer!
