### ISSUE TITLE
SSL_shutdown() seems to break other SSL Server Connections

### ISSUE THREAD

**Issue by BlueCall** [openssl/openssl#20126]
We do use the following code to create a new SSL Server Connection:

SSL_load_error_strings();
SSL_library_init();
int SSLAppDataIndex = SSL_get_ex_new_index(0, (char*)"AppData", NULL, NULL, NULL);
pSSL_ctx= SSL_CTX_new(TLS_server_method());
SSL_CTX_set_verify(pSSL_ctx, SSL_VERIFY_NONE, NULL);

// Creating Server Session
pSSL = SSL_new(pSSL_ctx);
pBIOSocketReceive = BIO_new(BIO_s_mem());
pBIOSocketSend = BIO_new(BIO_s_mem());
SSL_set_bio(pSSL, pBIOSocketReceive, pBIOSocketSend);
SSL_set_ex_data(m_SSLSession.pSSL, SSLAppDataIndex, this);

There are multilpe SSL Server connections in the system seems working fine.

When we call SSL_shutdown() for a Server connection, after about 10 seconds its seems to impact an other SSL Server connection.
When we call only SSL_free() wihout SSL_shutdown() first this problem seems not to exist.

After SSL_shutdown() is called for a connection we get this error for an other connection when SSL_read() is called for the other connection:
error=1, message=error:00000001:lib(0)::reason(1)
error=167772567, message=error:0A000197:SSL routines::shutdown while in init

How can the SSL_shutdown() a connection impact an other SSL connection?

We use currently openssl-1.1.1s. We had this issue also with older versions. In the same App we do use also SSL Client Connections with an other SSL_CTX.

Thanks for any hint and Best Regards to the OpenSSL Team!

**Comment by BlueCall** [comment]
We added SSL_CTX_set_session_id_context() on server side. Same behave.
Should SSL_shutdown() never be used whenever SSL session cache is active?

**Comment by mattcaswell** [comment]
SSL_shutdown() should have no adverse interactions with the session cache and it should not impact other SSL connections. Sounds like a possible threading issue? Or maybe a memory corruption? Might be worth running it through tsan and asan.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
