### ISSUE TITLE
safestack and mutability

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#20135]
Our current abused stack implementation will sort its elements when a find operation is requested.  This is asking for problems and #20098 addresses the current problems.

We should investigate alternative implementations where the find doesn't mutate the stack.  Some possibilities include:

1. Falling back to a linear search is the stack isn't sorted.  This would require code to explicitly sort the stack to regain lost efficiency.
1. Introduce an auxiliary array in the stack structure which holds the sorted indicies and this is used (via an extra level of indirection) to do the find without modifying the stack's other contents.
2. A hybrid approach where we remember how much of the stack is sorted and binary search that followed by a linear search of any additional items.
3. Purging as much of our use of stack as possible and instead use data types are actually appropriate for purpose.

**Comment by davidben** [comment]
Ah yeah the mutating find is quite confusing! We do (1) in BoringSSL, and just initially did an explicit sort before each find when doing the conversion. And then from there you can triage the sorts and figure out which ones ought to work differently.

(External callers do not frequently set comparison functions or call find, so it's mostly an issue within the library.)

**Comment by t8m** [comment]
IMO 1) plus 4) is what we should do. Or alternatively we could keep the current find modifying the stack for external users so we do not regress performance for the external users, but internally ensure that we never call find in unsorted state (i.e., use sorted insert (or insert + sort) where appropriate or something like that).

**Comment by hlandau** [comment]
(1) + (4) sounds good to me.

**Comment by t8m** [comment]
OTC decision on the topic was: **OTC: We should go through each instance and decide which approach to take (pre-sort or locking or fallback to linear search).**
