### ISSUE TITLE
doc/man3/EVP_DigestInit.pod: example code should reflect dynamic algo providers

### ISSUE THREAD

**Issue by sdaoden** [openssl/openssl#20130]
[master] as of c3bd630df0c3630c66155fb8c4baf54810d24695.

The example code does
```
     md = EVP_get_digestbyname(argv[1]);
     if (md == NULL) {
         printf("Unknown message digest %s\n", argv[1]);
         exit(1);
     }

     mdctx = EVP_MD_CTX_new();
     EVP_DigestInit_ex2(mdctx, md, NULL);
     EVP_DigestUpdate(mdctx, mess1, strlen(mess1));
```

which to the best of my incomplete knowledge could crash since now "algorithm providers are dynamic" aka lazily resolved, so that EVP_DigestInit_ex2() could fail due to invalid "md"?

P.S.: if this is not true software like the postfix MTA should be notified, as they implemented according workarounds.
Thank you.

**Comment by t8m** [comment]
Fix in #20136
