### ISSUE TITLE
Partial error value check & possible memory leak in `crypto/cmp/cmp_msg.c`

### ISSUE THREAD

**Issue by nikslyon19** [openssl/openssl#20145]
https://github.com/openssl/openssl/blob/6e3b1c81736b1829584e3f40c2d00040fe1aa881/crypto/cmp/cmp_msg.c#L817-L821

If `sk_OSSL_CMP_CERTSTATUS_push()` fails, we should free the `certStatus` before `goto err;` as it has not been consumed by the `msg` at this point of time.

https://github.com/openssl/openssl/blob/6e3b1c81736b1829584e3f40c2d00040fe1aa881/crypto/stack/stack.c#L382-L387

Since `sk_OSSL_CMP_CERTSTATUS_push` is basically a macro for `OPENSSL_sk_push`,
the if check on `sk_OSSL_CMP_CERTSTATUS_push` should be on `<= 0` or `< 1` instead of only negation.

**Comment by mhjd** [comment]
Hello,

I'm a student at Université Paris 8 and I have a course for which I have to contribute to a free software.
I like OpenSSL so I want to work on it. Would it be okay for me to work on this issue?

**Comment by t8m** [comment]
> Hello,
> 
> I'm a student at Université Paris 8 and I have a course for which I have to contribute to a free software. I like OpenSSL so I want to work on it. Would it be okay for me to work on this issue?

Yes, sure. This is basically a one-line fix.

**Comment by mhjd** [comment]
So I tried to run `make` but I had this warning : 
```
In file included from crypto/cmp/cmp_local.h:17,
                 from crypto/cmp/cmp_msg.c:14:
crypto/cmp/cmp_msg.c: In function 'ossl_cmp_certConf_new':
crypto/cmp/cmp_msg.c:824:37: warning: passing argument 1 of 'ossl_check_OSSL_CMP_CERTSTATUS_sk_type' from incompatible pointer type [-Wincompatible-pointer-types]
  824 |         sk_OSSL_CMP_CERTSTATUS_free(certStatus);
      |                                     ^~~~~~~~~~
      |                                     |
      |                                     OSSL_CMP_CERTSTATUS * {aka struct ossl_cmp_certstatus_st *}
include/openssl/cmp.h:230:96: note: in definition of macro 'sk_OSSL_CMP_CERTSTATUS_free'
  230 | #define sk_OSSL_CMP_CERTSTATUS_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk))
      |                                                                                                ^~
In file included from include/openssl/crypto.h:34,
                 from include/internal/e_os.h:17,
                 from include/internal/common.h:18,
                 from include/internal/cryptlib.h:21,
                 from crypto/cmp/cmp_local.h:15,
                 from crypto/cmp/cmp_msg.c:14:
include/openssl/safestack.h:47:91: note: expected 'struct stack_st_OSSL_CMP_CERTSTATUS *' but argument is of type 'OSSL_CMP_CERTSTATUS *' {aka 'struct ossl_cmp_certstatus_st *'}
   47 |     static ossl_unused ossl_inline OPENSSL_STACK *ossl_check_##t1##_sk_type(STACK_OF(t1) *sk) \
      |                                                                                           ^
include/openssl/cmp.h:223:1: note: in expansion of macro 'SKM_DEFINE_STACK_OF_INTERNAL'
  223 | SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CMP_CERTSTATUS, OSSL_CMP_CERTSTATUS, OSSL_CMP_CERTSTATUS)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
And I remembered that my professor had a doubt on if it's `sk_OSSL_CMP_CERTSTATUS_free` or `OSSL_CMP_CERTSTATUS_free`. So I changed to `OSSL_CMP_CERTSTATUS_free` and `make` and `make test` work.

**Comment by DDvO** [comment]
> And I remembered that my professor had a doubt on if it's `sk_OSSL_CMP_CERTSTATUS_free` or `OSSL_CMP_CERTSTATUS_free`. So I changed to `OSSL_CMP_CERTSTATUS_free` and `make` and `make test` work.

Your professor was right - which can easily be seen also without compiling (or even running tests)
because `certStatus` has type `OSSL_CMP_CERTSTATUS`, so it must be freed using `OSSL_CMP_CERTSTATUS_free()`.

**Comment by t8m** [comment]
Fixed by https://github.com/openssl/openssl/pull/20406
