### ISSUE TITLE
error make: *** [configdata.pm] Error 1 when running make on openssl 1.1.1-dev

### ISSUE THREAD

**Issue by kumbulanit** [openssl/openssl#2014]
when i run make on centos 7  i get the error

make: *** [configdata.pm] Error 1

can anyone assist how i can go around this

**Comment by levitte** [comment]
What did the 10-ish lines just before that say?

**Comment by kumbulanit** [comment]
this is what it shows 



make: Warning: File `crypto/include/internal/bn_conf.h.in' has modification time 367409782 s in the future
Detected changed: Configure config Configurations/unix-Makefile.tmpl Configurations/common.tmpl build.info crypto/build.info ssl/build.info engines/build.info apps/build.info test/build.info util/build.info tools/build.info fuzz/build.info crypto/objects/build.info crypto/md4/build.info crypto/md5/build.info crypto/sha/build.info crypto/mdc2/build.info crypto/hmac/build.info crypto/ripemd/build.info crypto/whrlpool/build.info crypto/poly1305/build.info crypto/blake2/build.info crypto/des/build.info crypto/aes/build.info crypto/rc2/build.info crypto/rc4/build.info crypto/idea/build.info crypto/bf/build.info crypto/cast/build.info crypto/camellia/build.info crypto/seed/build.info crypto/chacha/build.info crypto/modes/build.info crypto/bn/build.info crypto/ec/build.info crypto/rsa/build.info crypto/dsa/build.info crypto/dh/build.info crypto/dso/build.info crypto/engine/build.info crypto/buffer/build.info crypto/bio/build.info crypto/stack/build.info crypto/lhash/build.info crypto/rand/build.info crypto/err/build.info crypto/evp/build.info crypto/asn1/build.info crypto/pem/build.info crypto/x509/build.info crypto/x509v3/build.info crypto/conf/build.info crypto/txt_db/build.info crypto/pkcs7/build.info crypto/pkcs12/build.info crypto/comp/build.info crypto/ocsp/build.info crypto/ui/build.info crypto/cms/build.info crypto/ts/build.info crypto/srp/build.info crypto/cmac/build.info crypto/ct/build.info crypto/async/build.info crypto/kdf/build.info test/ossl_shim/build.info Configurations/00-base-templates.conf Configurations/10-main.conf
Reconfiguring...
/usr/bin/perl ./Configure reconf
Reconfiguring with: linux-x86_64 --no -SSLv2 -SSLv3 -Wa,--noexecstack
    CC = gcc
    CXX = g++
    BUILDFILE = Makefile
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-external-tests [default]  OPENSSL_NO_EXTERNAL_TESTS
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-tls1_3       [default]  OPENSSL_NO_TLS1_3
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default] 
    no-zlib-dynamic [default] 
Configuring for linux-x86_64

PERL          =/usr/bin/perl
PERLVERSION   =5.16.3 for x86_64-linux-thread-multi
HASHBANGPERL  =/usr/bin/env perl
CC            =gcc
CFLAG         =-Wall -O3 -pthread -m64 -DL_ENDIAN  --no -SSLv2 -SSLv3 -Wa,--noexecstack
CXX           =g++
CXXFLAG       =-Wall -O3 -pthread -m64 -DL_ENDIAN 
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_STATIC_ENGINE OPENSSL_PIC OPENSSL_IA32_SSE2 OPENSSL_BN_ASM_MONT OPENSSL_BN_ASM_MONT5 OPENSSL_BN_ASM_GF2m SHA1_ASM SHA256_ASM SHA512_ASM RC4_ASM MD5_ASM AES_ASM VPAES_ASM BSAES_ASM GHASH_ASM ECP_NISTZ256_ASM PADLOCK_ASM POLY1305_ASM
EX_LIBS       =-ldl 
**************************************************
***                                            ***
***   Please run the same make command again   ***
***                                            ***
**************************************************
make: *** [configdata.pm] Error 1

**Comment by levitte** [comment]
Yes. Did you actually read the part that explicitly asks you to run the same make command again?

**Comment by kumbulanit** [comment]
i think if i had run it again and it did not give an error i wouldnt have posted this as an issue , i ran it more that once but still get the same error

 make
make: Warning: File `crypto/include/internal/bn_conf.h.in' has modification time 367396859 s in the future
Detected changed: Configure config Configurations/unix-Makefile.tmpl Configurations/common.tmpl build.info crypto/build.info ssl/build.info engines/build.info apps/build.info test/build.info util/build.info tools/build.info fuzz/build.info crypto/objects/build.info crypto/md4/build.info crypto/md5/build.info crypto/sha/build.info crypto/mdc2/build.info crypto/hmac/build.info crypto/ripemd/build.info crypto/whrlpool/build.info crypto/poly1305/build.info crypto/blake2/build.info crypto/des/build.info crypto/aes/build.info crypto/rc2/build.info crypto/rc4/build.info crypto/idea/build.info crypto/bf/build.info crypto/cast/build.info crypto/camellia/build.info crypto/seed/build.info crypto/chacha/build.info crypto/modes/build.info crypto/bn/build.info crypto/ec/build.info crypto/rsa/build.info crypto/dsa/build.info crypto/dh/build.info crypto/dso/build.info crypto/engine/build.info crypto/buffer/build.info crypto/bio/build.info crypto/stack/build.info crypto/lhash/build.info crypto/rand/build.info crypto/err/build.info crypto/evp/build.info crypto/asn1/build.info crypto/pem/build.info crypto/x509/build.info crypto/x509v3/build.info crypto/conf/build.info crypto/txt_db/build.info crypto/pkcs7/build.info crypto/pkcs12/build.info crypto/comp/build.info crypto/ocsp/build.info crypto/ui/build.info crypto/cms/build.info crypto/ts/build.info crypto/srp/build.info crypto/cmac/build.info crypto/ct/build.info crypto/async/build.info crypto/kdf/build.info test/ossl_shim/build.info Configurations/00-base-templates.conf Configurations/10-main.conf
Reconfiguring...
/usr/bin/perl ./Configure reconf
Reconfiguring with: linux-x86_64 --no -SSLv2 -SSLv3 -Wa,--noexecstack
    CC = gcc
    CXX = g++
    BUILDFILE = Makefile
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-external-tests [default]  OPENSSL_NO_EXTERNAL_TESTS
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-tls1_3       [default]  OPENSSL_NO_TLS1_3
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default] 
    no-zlib-dynamic [default] 
Configuring for linux-x86_64

PERL          =/usr/bin/perl
PERLVERSION   =5.16.3 for x86_64-linux-thread-multi
HASHBANGPERL  =/usr/bin/env perl
CC            =gcc
CFLAG         =-Wall -O3 -pthread -m64 -DL_ENDIAN  --no -SSLv2 -SSLv3 -Wa,--noexecstack
CXX           =g++
CXXFLAG       =-Wall -O3 -pthread -m64 -DL_ENDIAN 
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_STATIC_ENGINE OPENSSL_PIC OPENSSL_IA32_SSE2 OPENSSL_BN_ASM_MONT OPENSSL_BN_ASM_MONT5 OPENSSL_BN_ASM_GF2m SHA1_ASM SHA256_ASM SHA512_ASM RC4_ASM MD5_ASM AES_ASM VPAES_ASM BSAES_ASM GHASH_ASM ECP_NISTZ256_ASM PADLOCK_ASM POLY1305_ASM
EX_LIBS       =-ldl 
**************************************************
***                                            ***
***   Please run the same make command again   ***
***                                            ***
**************************************************
make: *** [configdata.pm] Error 1
mail 05:20:51 # make
make: Warning: File `crypto/include/internal/bn_conf.h.in' has modification time 367396851 s in the future
Detected changed: Configure config Configurations/unix-Makefile.tmpl Configurations/common.tmpl build.info crypto/build.info ssl/build.info engines/build.info apps/build.info test/build.info util/build.info tools/build.info fuzz/build.info crypto/objects/build.info crypto/md4/build.info crypto/md5/build.info crypto/sha/build.info crypto/mdc2/build.info crypto/hmac/build.info crypto/ripemd/build.info crypto/whrlpool/build.info crypto/poly1305/build.info crypto/blake2/build.info crypto/des/build.info crypto/aes/build.info crypto/rc2/build.info crypto/rc4/build.info crypto/idea/build.info crypto/bf/build.info crypto/cast/build.info crypto/camellia/build.info crypto/seed/build.info crypto/chacha/build.info crypto/modes/build.info crypto/bn/build.info crypto/ec/build.info crypto/rsa/build.info crypto/dsa/build.info crypto/dh/build.info crypto/dso/build.info crypto/engine/build.info crypto/buffer/build.info crypto/bio/build.info crypto/stack/build.info crypto/lhash/build.info crypto/rand/build.info crypto/err/build.info crypto/evp/build.info crypto/asn1/build.info crypto/pem/build.info crypto/x509/build.info crypto/x509v3/build.info crypto/conf/build.info crypto/txt_db/build.info crypto/pkcs7/build.info crypto/pkcs12/build.info crypto/comp/build.info crypto/ocsp/build.info crypto/ui/build.info crypto/cms/build.info crypto/ts/build.info crypto/srp/build.info crypto/cmac/build.info crypto/ct/build.info crypto/async/build.info crypto/kdf/build.info test/ossl_shim/build.info Configurations/00-base-templates.conf Configurations/10-main.conf
Reconfiguring...
/usr/bin/perl ./Configure reconf
Reconfiguring with: linux-x86_64 --no -SSLv2 -SSLv3 -Wa,--noexecstack
    CC = gcc
    CXX = g++
    BUILDFILE = Makefile
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-external-tests [default]  OPENSSL_NO_EXTERNAL_TESTS
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-tls1_3       [default]  OPENSSL_NO_TLS1_3
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default] 
    no-zlib-dynamic [default] 
Configuring for linux-x86_64

PERL          =/usr/bin/perl
PERLVERSION   =5.16.3 for x86_64-linux-thread-multi
HASHBANGPERL  =/usr/bin/env perl
CC            =gcc
CFLAG         =-Wall -O3 -pthread -m64 -DL_ENDIAN  --no -SSLv2 -SSLv3 -Wa,--noexecstack
CXX           =g++
CXXFLAG       =-Wall -O3 -pthread -m64 -DL_ENDIAN 
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_STATIC_ENGINE OPENSSL_PIC OPENSSL_IA32_SSE2 OPENSSL_BN_ASM_MONT OPENSSL_BN_ASM_MONT5 OPENSSL_BN_ASM_GF2m SHA1_ASM SHA256_ASM SHA512_ASM RC4_ASM MD5_ASM AES_ASM VPAES_ASM BSAES_ASM GHASH_ASM ECP_NISTZ256_ASM PADLOCK_ASM POLY1305_ASM
EX_LIBS       =-ldl 
**************************************************
***                                            ***
***   Please run the same make command again   ***
***                                            ***
**************************************************
make: *** [configdata.pm] Error 1
mail 05:20:58 #

**Comment by richsalz** [comment]
Please do "ls -l crypto/include/internal/bn_conf.h.in"

And perhaps also look at the other dates on various files you unpacked.

**Comment by mattcaswell** [comment]
> make: Warning: File `crypto/include/internal/bn_conf.h.in' has modification time 367396859 s in the future

Looks like a corrupt file to me.

**Comment by levitte** [comment]
That's quite a lot of seconds. What time does your computer think it is?

**Comment by levitte** [comment]
... and date

**Comment by kumbulanit** [comment]
the results for ls -l crypto/include/internal/bn_conf.h.in

-rw-r--r--. 1 root root 873 Nov 29 12:01 crypto/include/internal/bn_conf.h.in



the time and date  on  the server is 
 
date
Tue Nov 29 20:58:28 SAST 2016

**Comment by richsalz** [comment]
Then why does your system think that it is in the future?  I suggest you wipe everything and start over.  There is some strange local inconsistency going on.

**Comment by levitte** [comment]
This hasn't been responded to, which leaves it inconclusive.  I'm closing this.  Please open a new issue if the problem persists after having checked the time.

**Comment by benseshi** [comment]
unable to create configdata.pm: Permission denied

**Comment by benseshi** [comment]
can anyone resolve this 
thankyou

**Comment by benseshi** [comment]
Test Summary Report
-------------------
../test/recipes/15-test_dsa.t                    (Wstat: 768 Tests: 5 Failed: 3)
  Failed tests:  3-5
  Non-zero exit status: 3
../test/recipes/15-test_ec.t                     (Wstat: 768 Tests: 5 Failed: 3)
  Failed tests:  3-5
  Non-zero exit status: 3
../test/recipes/15-test_genrsa.t                 (Wstat: 1024 Tests: 5 Failed: 4)
  Failed tests:  2-5
  Non-zero exit status: 4
../test/recipes/15-test_rsa.t                    (Wstat: 768 Tests: 6 Failed: 3)
  Failed tests:  4-6
  Non-zero exit status: 3
../test/recipes/15-test_rsapss.t                 (Wstat: 512 Tests: 5 Failed: 2)
  Failed tests:  1, 5
  Non-zero exit status: 2
../test/recipes/20-test_enc.t                    (Wstat: 256 Tests: 60 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 118 tests but ran 60.
../test/recipes/20-test_enc_more.t               (Wstat: 256 Tests: 113 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
../test/recipes/25-test_crl.t                    (Wstat: 768 Tests: 7 Failed: 3)
  Failed tests:  2, 6-7
  Non-zero exit status: 3
../test/recipes/25-test_pkcs7.t                  (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
../test/recipes/25-test_req.t                    (Wstat: 768 Tests: 4 Failed: 3)
  Failed tests:  2-4
  Non-zero exit status: 3
../test/recipes/25-test_sid.t                    (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
../test/recipes/25-test_x509.t                   (Wstat: 1792 Tests: 9 Failed: 7)
  Failed tests:  2-8
  Non-zero exit status: 7
../test/recipes/40-test_rehash.t                 (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 5 tests but ran 0.
../test/recipes/60-test_x509_store.t             (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
../test/recipes/80-test_ca.t                     (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/80-test_cms.t                    (Wstat: 1024 Tests: 4 Failed: 4)
  Failed tests:  1-4
  Non-zero exit status: 4
../test/recipes/80-test_ocsp.t                   (Wstat: 512 Tests: 11 Failed: 2)
  Failed tests:  1, 10
  Non-zero exit status: 2
../test/recipes/80-test_ssl_new.t                (Wstat: 6144 Tests: 24 Failed: 24)
  Failed tests:  1-24
  Non-zero exit status: 24
../test/recipes/80-test_ssl_old.t                (Wstat: 1536 Tests: 6 Failed: 6)
  Failed tests:  1-6
  Non-zero exit status: 6
../test/recipes/80-test_tsa.t                    (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 20 tests but ran 0.
../test/recipes/90-test_store.t                  (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 199 tests but ran 0.
Files=137, Tests=845, 425 wallclock secs ( 5.91 usr  0.53 sys + 326.75 cusr 147.27 csys = 480.46 CPU)
Result: FAIL
Makefile:167: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/ben/openssl'
Makefile:165: recipe for target 'tests' failed
make: *** [tests] Error 2
 and this too

**Comment by richsalz** [comment]
"modification time in the future" indicates that something is wrong with your system.
There's no way openssl configuration stuff sets things AHEAD of the system time.

**Comment by benseshi** [comment]
So wt do I do

**Comment by richsalz** [comment]
Try removing the software, reboot the system. Reload and unpack the software.  Reconfigure and build.

**Comment by levitte** [comment]
@benseshi, it seems you don't have permission to write in `/home/ben/openssl`.  Is it a read-only directory?  Does it contain the OpenSSL source?  If both are true, then you need to do your build *somewhere else*, for example like this:

```
mkdir /tmp/benseshi-openssl-build
cd /tmp/benseshi-openssl-build
/home/ben/openssl/config
make
make test
```

**Comment by levitte** [comment]
@richsalz, the "modification time in the future" is an old thing from last year that has nothing to do with @benseshi.  @benseshi just used this old issue instead of creating a new one.

**Comment by benseshi** [comment]
Thanks for solution
