### ISSUE TITLE
OpenSSL 3.1 release date

### ISSUE THREAD

**Issue by krk** [openssl/openssl#20140]
OpenSSL 3.1 RC [was announced](https://www.openssl.org/blog/blog/2022/12/21/OpenSSL3.1Beta/) on 2022-12-21, there are 4 issues in the [3.1.0 milestone](https://github.com/openssl/openssl/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1.0) as of writing.

I was wondering if there is a target date for the release, whether another RC is required and whether the issues in the milestone are the only issues blocking the release.

**Comment by tom-cosgrove-arm** [comment]
As [@mattcaswell commented](https://github.com/openssl/openssl/issues/20111#issuecomment-1400379739) 2 days ago on [issue 20111 "Is there any expected release date for the fix of #19643 issue?"](https://github.com/openssl/openssl/issues/20111):

> There has been no release date announced for the next release as yet. Typically one comes along every few months or so. The last release was in early November.

**Comment by t8m** [comment]
@tom-cosgrove-arm That's more about stable releases.

However we do not have definitive date for 3.1.0 release either. So I cannot say more than that currently we do not plan another beta/RC release and that we want to release 3.1.0 soon.

I've cleaned up the Milestone 3.1.0 so here are the only issues/PRs that might potentially block the release: https://github.com/openssl/openssl/milestones/3.1.0

**Comment by paulidale** [comment]
The timeline is going to be more dependent upon the work going on behind the scenes with the FIPS documentation and testing.  We won't do a 3.1 release until we are certain that the CAVP tests are passing on all platforms using the to be released code base.

I'm not expecting any problems here but it adds an unavoidable delay late in the process.

**Comment by krk** [comment]
Is it possible to have an OpenSSL 3.1.0 release and have the FIPS certification bump a minor version, so that 3.2.0 would be the first FIPS certified version?

There are lots of performance fixed in 3.1.0 RC that are not in 3.0.7.

**Comment by paulidale** [comment]
No, the FIPS version is tied to the OpenSSL version.

**Comment by krk** [comment]
Is it possible to release a 3.0.9 with only 3 cherry picked commits in https://github.com/openssl/openssl/pull/20421 ?

**Comment by krk** [comment]
Now that OpenSSL 3.1 is released today, I am closing this issue. Thanks for your time and a great release!
