### ISSUE TITLE
Provide OpenSSL binaries under GitHub Releases

### ISSUE THREAD

**Issue by levicki** [openssl/openssl#20154]
I asked about the possibility to provide binaries under GitHub Releases in #20114 and @t8m provided some clarification but since it is a separate topic I am creating this feature request.

I understand that there are many possible build configurations and that not all of them can be provided but providing for a few major platforms would be nice.

On the other hand, if I am not mistaken this project uses automated builds as part of CI. For this to be useful they probably have to build binaries and run tests for a few platforms if not all of them. If the build process already produces binaries then I see no harm in releasing those.

Provided binaries don't need to come with support and/or warranty &mdash; they could have a disclaimer (e.g. "use at your own risk"), and if someone needs different build configuration than a couple of major ones provided, they can still clone and build OpenSSL themselves.

I would really appreciate OpenSSL maintainers' thoughts on this subject.

**Comment by paulidale** [comment]
OMC: the project will investigate this.

**Comment by paulidale** [comment]
OMC: we're looking into the possibility of a binary Windows release.

openssl/installer#2

**Comment by 1268** [comment]
not sure about author, but I would prefer just a normal Zip file against any other option. I would like to be able to just extract and run the program, similar to Linux. I dont need an installer.

**Comment by 1268** [comment]
not sure about author, but I would prefer just a normal Zip file against any other option. I would like to be able to just extract and run the program, similar to Linux. I dont need an installer. until then I am using this:

 https://indy.fulgan.com/SSL

**Comment by BugOfBugs** [comment]
Make _installer_ **separate** from _archive_. Would satisfy both: who likes to **unpack**, and who likes installers.

Publish binaries that other people **contribute** for various systems.

Post here **requests** to contribute binaries for missing systems.

Teach, and link how to configure. My **tutorial**:
https://github.com/openssl/openssl/issues/21643#issuecomment-1664927017

**Comment by 1268** [comment]
note that @BugOfBugs is a known spammer, please ignore

**Comment by 1268** [comment]
note that @BugOfBugs is a known spammer, please ignore

**Comment by nhorman** [comment]
we are planning an installer binary that will be buildable via the repository https://github.com/openssl/installer.  Thats available now, and are considering distributing a binary installer artifact for 3.5

**Comment by BugOfBugs** [comment]
>considering distributing a binary installer artifact

Do you mean ready to use _**archive**_, and _**installer**_? So there would be no need to **compile**.
User would simply **copy** them, and run.

**Comment by BugOfBugs** [comment]
>installer artifact

Do you mean ready to use _**archive**_, and _**installer**_? So there would be no need to **compile**.
User would simply **copy** them, and run.

**Comment by BugOfBugs** [comment]
>installer artifact

Do you mean ready to use _**archive**_, and _**installer**_? So there would be no need to **compile**.
User simply **copies**, and runs.
