### ISSUE TITLE
OSSL_STORE_LOADER_set_open_ex in not pre 3.0 function

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#20164]
OpenSSL 1.1.1* does not declare open_ex function. It is clear that function is part of 3* as arguments are library context and properties.

It seems to me between 3.0 alpha 6 and alpha 7 is was deprecated by mistake instead to be removed from public(installed) header.
Remark: at "deprecation" time name was ...with_libctx.

Request is to remove for library.

**Comment by t8m** [comment]
I am afraid it is too late. Even if it is deprecated in 3.0 it is still part of its API/ABI and thus cannot be removed earlier than in 4.0.

**Comment by t8m** [comment]
**OTC: this might be removed along the other deprecated OSSL_STORE_LOADER functions in a future major release. It cannot be removed from current or future minor releases due to API stability.**

**Comment by levitte** [comment]
I see where you're coming from, @petrovr, `OSSL_STORE_LOADER_set_open_ex()` was added as a deprecated function from the very start.  That was a deliberate choice, as that was needed exclusively for ENGINE based loaders (specifically, for `engines/e_loader_attic.c`), which are deprecated.
I frankly don't remember all the details at this point, but that's my (admitadly vague) historical recollection.
