### ISSUE TITLE
EVP_PKEY_CTRL_DSA_PARAMGEN_MD wrong md variable

### ISSUE THREAD

**Issue by metaroxx** [openssl/openssl#2016]
I believe this is wrong and should update "dctx->pmd = p2" instead of "dctx->md = p2" which makes the parameter generation always use SHA1 instead of the intended chosen MD in pkey_dsa_paramgen. It's fine in DH parameter generation when using DSA mode as the md is given as input to dsa_builtin_paramgen/dsa_builtin_paramgen2.

```
static int pkey_dsa_ctrl(EVP_PKEY_CTX *ctx, int type, int p1, void *p2)
...
    case EVP_PKEY_CTRL_DSA_PARAMGEN_MD:
        if (EVP_MD_type((const EVP_MD *)p2) != NID_sha1 &&
            EVP_MD_type((const EVP_MD *)p2) != NID_sha224 &&
            EVP_MD_type((const EVP_MD *)p2) != NID_sha256) {
            DSAerr(DSA_F_PKEY_DSA_CTRL, DSA_R_INVALID_DIGEST_TYPE);
            return 0;
        }
        dctx->md = p2;
        return 1;
...
```

**Comment by levitte** [comment]
I had a look through the code, and it seems you're right.  I also found a spot where `dctx-md` is used but it should be `dctx-pmd`.  PR coming up!

**Comment by mattcaswell** [comment]
This issue was fixed.
master: 8a05c4d
1.1.0: aaec49f
1.0.2: 16f013f
