### ISSUE TITLE
Issues with RSA_set_method() in 3.x

### ISSUE THREAD

**Issue by jjeffroberts** [openssl/openssl#20176]
We use libp11 in our smartcard stack. They make use of RSA_set_method() to plug in some custom functions.

This worked when we were using openssl 1.1.1q but no longer seems to work with openssl 3.x.  I've tested the openssl-3.0 branch, the openssl-3.0.5 tag and the master branch.

Here is a patch that adds a testcase to test/rsa_test.c. If the custom decrypt method is called, it sets a global and the test succeeds.

(The patch should apply cleanly to 1.1.1q and with slight modification to the newer branches)

```
From 12ff0fd28989d644f2f3ce7b5393ef16b0349325 Mon Sep 17 00:00:00 2001
From: "J. Jeff" <jjrobert@us-11mp5m3.lpdev.prtdev.lexmark.com>
Date: Mon, 30 Jan 2023 14:13:22 -0500
Subject: [PATCH 1/1] Modify test/rsa_test.c to test RSA_set_method()

---
 test/rsa_test.c | 76 +++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 76 insertions(+)

diff --git a/test/rsa_test.c b/test/rsa_test.c
index 15e8767a2e..e82c677f24 100644
--- a/test/rsa_test.c
+++ b/test/rsa_test.c
@@ -18,6 +18,7 @@
 #include <openssl/err.h>
 #include <openssl/rand.h>
 #include <openssl/bn.h>
+#include <openssl/evp.h>
 
 #include "testutil.h"
 
@@ -30,6 +31,8 @@ int setup_tests(void)
 #else
 # include <openssl/rsa.h>
 
+int ourDecryptWasCalled = 0;
+
 # define SetKey \
     RSA_set0_key(key,                                           \
                  BN_bin2bn(n, sizeof(n)-1, NULL),               \
@@ -349,11 +352,84 @@ err:
     return ret;
 }
 
+static int pkcs11_rsa_priv_dec_method(int flen, const unsigned char *from,
+		unsigned char *to, RSA *rsa, int padding)
+{
+    printf("In pkcs11_rsa_priv_dec_method\n");
+
+    ourDecryptWasCalled = 1;
+
+    return 1;
+}
+
+RSA_METHOD *PKCS11_get_rsa_method(void)
+{
+    static RSA_METHOD *ops = NULL;
+
+    ops = RSA_meth_dup(RSA_get_default_method());
+    if (!ops) {
+        printf("RSA_meth_dup() failed!\n");
+        return NULL;
+    }
+
+    RSA_meth_set1_name(ops, "libp11 RSA method");
+    RSA_meth_set_flags(ops, 0);
+    RSA_meth_set_priv_dec(ops, pkcs11_rsa_priv_dec_method);
+
+    return ops;
+}
+
+static int test_rsa_method(int idx)
+{
+    int ret = 0;
+
+    RSA *key;
+
+    rsa_setkey(&key, NULL, idx);
+
+    EVP_PKEY *pk = EVP_PKEY_new();
+    EVP_PKEY_set1_RSA(pk, key);
+
+    int rc  = RSA_set_method(key, PKCS11_get_rsa_method());
+    printf("RSA_set_method returns %d\n", rc);
+    RSA_set_flags(key, RSA_FLAG_EXT_PKEY);
+
+    EVP_PKEY_CTX *ctx = EVP_PKEY_CTX_new(pk, NULL);
+
+    if (ctx) {
+        unsigned char *crypto;
+        unsigned char to[1024];
+        size_t tlen;
+        unsigned char *from = (unsigned char*)strdup("This is encrypted test data!");
+        size_t flen = strlen((char*)from);
+
+        int keysize = RSA_size(key);
+        crypto = malloc(keysize);
+
+        int clen = RSA_public_encrypt(flen, from, crypto, key, RSA_PKCS1_PADDING);
+
+        if (EVP_PKEY_decrypt_init(ctx) > 0) {
+            if (EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_PADDING) == 1) {
+                if (EVP_PKEY_decrypt(ctx, NULL, &tlen, crypto, clen) == 1) {
+                    printf("tlen=%zu\n", tlen);
+                    EVP_PKEY_decrypt(ctx, to, &tlen, crypto, clen);
+                }
+            }
+        }
+
+        ret = ourDecryptWasCalled;
+    }
+
+
+    return ret;
+}
+
 int setup_tests(void)
 {
     ADD_ALL_TESTS(test_rsa_pkcs1, 3);
     ADD_ALL_TESTS(test_rsa_sslv23, 3);
     ADD_ALL_TESTS(test_rsa_oaep, 3);
+    ADD_ALL_TESTS(test_rsa_method, 3);
     return 1;
 }
 #endif
-- 
2.25.1
```

**Comment by beldmit** [comment]
Probably related to #17286

**Comment by levitte** [comment]
In what way doesn't it work? That functionality is deprecated, but not yet removed.

We don't support this way of doing things in providers, though, but I'm not sure if that's what you're concerned about.

**Comment by jjeffroberts** [comment]
The custom method is not called and the example test fails. In our actual build, unit tests that depend on libp11's use of the feature fail (and there is no openssl3 version of libp11 I can migrate to as of yet).

Deprecation is described in the Migration Guide as:

> You may still use them in your applications, but you may start to see deprecation warnings during compilation (dependent on compiler support for this). Deprecated APIs may be removed from future versions of OpenSSL so you are strongly encouraged to update your code to use the high level APIs instead.

I understand that the functionality is going away, and we are _starting_ our migration, but we expect this to continue working for now.

**Comment by t8m** [comment]
Your testcase will work fine if you call `EVP_PKEY_set1_RSA()` only after you set up the RSA key to use the external method. The reason is that the set1 operation creates a provided key if the original key uses the default method.

I am afraid that we cannot change this as that would break other usecases.

**Comment by jjeffroberts** [comment]
Thank you -- that does work for both my testcase and libp11. That should keep us running while we do further migration.

-Jeff
