### ISSUE TITLE
BrainpoolTls13 curves in OpenSSL

### ISSUE THREAD

**Issue by snachti** [openssl/openssl#20170]
Hello,

I have a question regarding the support for brainpooltls13 elliptic curves in TLS 1.3.
I have seen that the brainpooltls13 support was added in the master branch and wanted to task if there is any roadmap, when it will be released in a new OpenSSL version. 

I think the following Pull request  is about the brainpool support (https://github.com/openssl/openssl/pull/7485)

**Comment by paulidale** [comment]
At this point, there is no date set for a release that includes these.
