### ISSUE TITLE
SSL_renegotiate causes TLS handshake failure with SSL_clear:internal error

### ISSUE THREAD

**Issue by duxiaocheng** [openssl/openssl#20178]
Hello, all,

I want to update TLS certificate for existing connection. Below is my source code.
Unfortunately, SSL_do_handshake returns error with below info.
39815101156352:error:140A4044:SSL routines:SSL_clear:internal error:ssl/ssl_lib.c:601

Do you have any idea? Thanks!

    SSL_CTX* new_ctx = SSL_CTX_new(TLS_client_method());
    if (!new_ctx) {
        // handle error
    }
    if (SSL_CTX_use_certificate_file(new_ctx, "new_cert.pem", SSL_FILETYPE_PEM) <= 0) {
        // handle error
    }
    if (SSL_CTX_use_PrivateKey_file(new_ctx, "new_key.pem", SSL_FILETYPE_PEM) <= 0) {
        // handle error
    }
    SSL* ssl = SSL_new(new_ctx);
    if (!ssl) {
        // handle error
    }
    SSL_set_fd(ssl, socket); // socket is the existing connection
    if (SSL_set_ssl_method(ssl, SSL_get_ssl_method(ssl)) != 1) {
        // handle error
    }
    if (SSL_renegotiate(ssl) != 1) {
        // handle error
    }
    if (SSL_do_handshake(ssl) != 1) {
        // handle error
    }

**Comment by mattcaswell** [comment]
> SSL_set_fd(ssl, socket); // socket is the existing connection

If I understand you correctly you have an existing TLS connection on an fd and you are trying to set it into a new SSL object. You cannot do this. All the state about the existing TLS connection will be lost.

**Comment by duxiaocheng** [comment]
> > SSL_set_fd(ssl, socket); // socket is the existing connection
> 
> If I understand you correctly you have an existing TLS connection on an fd and you are trying to set it into a new SSL object. You cannot do this. All the state about the existing TLS connection will be lost.

Thanks! Yes, you are right. I want to update the certificate for existing TLS connection. Do you have any other idea to do this update?

**Comment by duxiaocheng** [comment]
Add more trying result:
1. It is OK to do SSL_renegotiate and SSL_do_handshake on that old SSL. There are Encrypted Handshake Messages.
2. Create new SSL and set existing socket into this new SSL, but DONOT call SSL_renegotiate before SSL_do_handshake. Encrypted Client Hello can be sent out. SSL_do_handshake return error.(140460282214144:error:140940CD:SSL routines:ssl3_read_bytes:invalid alert:ssl/record/rec_layer_s3.c:1497)

**Comment by mattcaswell** [comment]
> It is OK to do SSL_renegotiate and SSL_do_handshake on that old SSL. There are Encrypted Handshake Messages.

Yes. That is expected and the way renegotiation works. A new handshake is performed over the old connection and keys etc are updated.

> Create new SSL and set existing socket into this new SSL, but DONOT call SSL_renegotiate before SSL_do_handshake. Encrypted Client Hello can be sent out. SSL_do_handshake return error.(140460282214144:error:140940CD:SSL routines:ssl3_read_bytes:invalid alert:ssl/record/rec_layer_s3.c:1497)

Don't create a new SSL object with an existing socket that has an established TLS connection on it. This won't work.

> I want to update the certificate for existing TLS connection. Do you have any other idea to do this update?

Firstly - why do you want to do this at all? It is not really necessary. The certificate is used to authenticate the peer during the initial handshake and is then never used again during the lifetime of the connection unless a renegotiation occurs with a full handshake. After the initial handshake the peer is authenticated. If you trusted the peer is who they say they are at the beginning of the connection then you can only assume that they continue to have that identify for the duration of the connection. I suppose, for very long running connections, a certificate could expire during the course of that connection but does that really matter?

Is your application a client or a server?

Calling `SSL_renegotiate()` from the client side will initiate a renegotiation. Assuming that the server is configured to allow renegotiation then a full handshake will occur including sending a new certificate. This should be compared to `SSL_renegotiate_abbreviated()`  which does the same thing except that an abbreviated resumption handshake is used (which does not send a new certificate).

Technically, a server cannot initiate a renegotiation at all. Calling `SSL_renegotiate()` from the server side sends a message to the client requesting that a renegotiation takes place. The client is not obliged to respond to this, but if it does then it is up to the client to decide whether a full or resumption handshake takes place. An OpenSSL client, if it responds, will always respond with a resumption handshake (which does not incorporate a new certificate being sent from the server). Calling `SSL_renegotiate_abbreviated()` from the server behaves identically to calling `SSL_renegotiate()`.

**Comment by duxiaocheng** [comment]
Thanks @mattcaswell for your detail explanation. It is very useful. I chose to not do update certificate for existing TLS connection.
