### ISSUE TITLE
Timestamps can only be signed with SHA-1

### ISSUE THREAD

**Issue by gagliotti** [openssl/openssl#2018]
Dear all,

OpenSSL 1.0.2 seems to not allow us to sign timestamps using cryptographic hash algorithms other than SHA-1. See please https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/ts/ts_rsp_sign.c#L746. 

If my claim is not wrong, could you please provide a function such as TS_RESP_CTX_set_signer_md(EVP_MD*) which allows to define the hash to be used?

**Comment by richsalz** [comment]
There is ```TS_RESP_CTX_set_signer_digest``` in 1.1.0  New features are not added to releases, only bugfixes.
