### ISSUE TITLE
OpenSSL 1.1.1 fails to validate OCSP response signed by RSA-PSS key

### ISSUE THREAD

**Issue by gingerbeard-man** [openssl/openssl#20189]
I have a CA with OCSP responder using RSA-PSS keys throughout - root, intermediate and OCSP signer all have keys of type rsassaPss.

`openssl ocsp` is unable to verify the OCSP response:

```
s230358@localhost:~> openssl ocsp -url http://127.0.0.1:2560 -issuer ~/ocspd_test/TestCA/RSA-PSS-CA/subCA_cert.pem -cert ~/ocspd_test/TestCA/RSA-PSS-CA/user4_cert.pem -CAfile <(cat ~/ocspd_test/TestCA/RSA-PSS-CA/subCA_cert.pem ~/ocspd_test/TestCA/RSA-PSS-CA/rootCA_cert.pem)
Response Verify Failure
140166158198592:error:0D0C50C8:asn1 encoding routines:ASN1_item_verify:wrong public key type:crypto/asn1/a_verify.c:144:
140166158198592:error:27069075:OCSP routines:OCSP_basic_verify:signature failure:crypto/ocsp/ocsp_vfy.c:60:
140166158198592:error:0D0C50C8:asn1 encoding routines:ASN1_item_verify:wrong public key type:crypto/asn1/a_verify.c:144:
140166158198592:error:27069075:OCSP routines:OCSP_basic_verify:signature failure:crypto/ocsp/ocsp_vfy.c:60:
/home/s230358/ocspd_test/TestCA/RSA-PSS-CA/user4_cert.pem: good
	This Update: Feb  1 15:55:13 2023 GMT
```

ASN1_item_verify is checking the public key OID against the public key type:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/asn1/a_verify.c#L142-L146

The response has sha256WithRSAEncryption as signatureAlgorithm, resulting in EVP_PKEY_type(pknid) == NID_rsaEncryption whereas the certificate's public key id has NID_rsassaPss.  I believe the two should compare equal for the purpose of signature verification.

First experienced with OpenSSL 1.1.1d on Suse Linux Enterprise 15.3 and reproduced with my own build of 1.1.1n.

I tried modifying ASN1_item_verify to wrap an EVP_PKEY_type() also around `pkey->ameth->pkey_id` but that didn't change anything.  If I more drastically fudge the comparison to succeed then the signature is verified ok.

**Comment by t8m** [comment]
The certificates with rsassaPss public keys cannot be used to sign and verify PKCS#1 1.5 signatures.

This is IMO not a bug.

**Comment by gingerbeard-man** [comment]
Ok.  So the responder should be setting a different signatureAlgorithm when it creates an RSA-PSS signature (with an RSA-PSS key)?

**Comment by mattcaswell** [comment]
Right. It should be using the rsassaPss OID for RSA-PSS signatures.

**Comment by gingerbeard-man** [comment]
Mea culpa.  I have now taken a look at our old environment (SLES 12 with OpenSSL 1.0.2p) and the responder there does indeed set the algorithm to rsassaPss in this case.  So I need to go through the changes that were made to our responder moving it from 1.0.2 to 1.1.1 to figure out what is wrong.

Thanks.
