### ISSUE TITLE
Failed to do start tls handshake: SSL routines:tls_early_post_process_client_hello:unsupported protocol

### ISSUE THREAD

**Issue by marek22k** [openssl/openssl#20192]
Hello,

I am using the Ruby EventMachine library which uses OpenSSL for TLS. I tried to implement TIC with StartTLS, but the program crashes:
```
139943097670528:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:1685:
```

```
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```

I then tried again with a newer OpenSSL version (`OpenSSL 1.1.1n 15 Mar 2022`), but the same error happened.

Here is a dump of the handshake: https://paste.i2pd.xyz/?0b26082e7dcc61fe#7asPqnBaTAdENNydzEmj31nnQrafu3SyWWUWgSySk8Fo

**Comment by mattcaswell** [comment]
OpenSSL is failing to find a mutually supported protocol version. The ClientHello is only offering a maximum of TLSv1.0 which is very old. What protocol versions are enabled in your server?

**Comment by mattcaswell** [comment]
How do you create your `SSL_CTX` and how do you enable the protocol versions? (BTW: You certainly do not support SSLv2 since OpenSSL 1.1.1 does not support it. SSLv3 support is not compiled in by default.)

**Comment by marek22k** [comment]
Mhh, I use the EventMachine library, which in turn uses the Ruby OpenSSL library.

The documentation says the following:
https://www.rubydoc.info/github/eventmachine/eventmachine/EventMachine/Connection:start_tls
>  :ssl_version (Array) — default: TLSv1 TLSv1_1 TLSv1_2 —
indicates the allowed SSL/TLS versions. Possible values are: SSLv2, SSLv3, TLSv1, TLSv1_1, TLSv1_2.

**Comment by mattcaswell** [comment]
I suspect a configuration problem somewhere which means that TLSv1.0 is not actually available in your server. But, unfortunately I'm not familiar with Ruby or EventMachine to provide specific advice there.

Do you have control over the client? It would be worth trying to get the client to talk TLSv1.2 and see if your server then starts to work. That would confirm whether or not there is some other problem preventing the handshake or whether it is purely a version negotiation issue. You might also want to see if there are any Ruby/EventMachine forums where you could ask for help.

**Comment by marek22k** [comment]
Thanks for the advice. I will try to emulate a client. I have already opened an issue for EventMachine: https://github.com/eventmachine/eventmachine/issues/976
Unfortunately the protocol is very old and the reference client from 2007, which I used, can only do TLS1.0.
