### ISSUE TITLE
Why isn't `OSSL_HPKE_SUITE` opaque?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#20199]
Why isn't the `OSSL_HPKE_SUITE` opaque?
Why is it passed directly on the stack and returned, as opposed to pointers?
The project did lots of work to make *everything* opaque, this seems like a step backwards.

**Comment by mattcaswell** [comment]
IIRC, there was much discussion about this at the time and the conclusion was we would allow it (i.e. this wasn't accidental).

Hopefully @sftcd can chip in and provide the rationale here.

**Comment by sftcd** [comment]
On 03/02/2023 09:18, Matt Caswell wrote:> Hopefully @sftcd can chip in 
and provide the rationale here.

Basically, that type is two uint16_t's which is smaller than
a pointer. And both the type and values are in the RFC (or
the IANA registry) so it doesn't seem like there's anything
useful to "hide" or be opaque about in this case.

Cheers,
S.

**Comment by sftcd** [comment]
Sorry, typo - it's three uint16_t's

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
