### ISSUE TITLE
Problem with the sample pkread.c

### ISSUE THREAD

**Issue by GillesT78** [openssl/openssl#20198]
Hello

I try to use pkread.c to read a .p12 file (with a password)
In all my tests, I have an error in PKCS12_verify_mac (line CRYPTO_memcmp(mac, ASN1_STRING_get0_data(macoct), maclen) != 0)) with error PKCS12_R_MAC_VERIFY_FAILURE

If I run the command : openssl.exe  pkcs12 -in file.p12 -passin pass:xxxx -nokeys, I succeed to read .p12 file

Code is similar, but I don't understand why pkread return an error. Is there something that is missing in pkread.c ?

Cordialement
Gilles

**Comment by GillesT78** [comment]
Hello
I continueto try to understand without success.
Can somebody make a try ?

Regards
Gilles

**Comment by nhorman** [comment]
you note that your attempts to run openssl.exe pkcs12 failed until you ran specifically:
```
 openssl.exe pkcs12 -in file.p12 -passin pass:xxxx -nokeys
```

What were you executing in the failing cases?

**Comment by nhorman** [comment]
no response, marking as inactive, to be closed at the end of 3.4 dev barring further input
