### ISSUE TITLE
3.0 functions should be hidden when OPENSSL_API_COMPAT<30000

### ISSUE THREAD

**Issue by rustyx** [openssl/openssl#20207]
Currently it's too easy to introduce an incompatibility with OpenSSL 1.1 by accidentally using 3.0 API's.

Consider the following example:

```
#define OPENSSL_API_COMPAT 10101
#include <openssl/evp.h>
#include <openssl/rsa.h>

int main()
{
  EVP_RSA_gen(1024);
}
```

It's compiling fine on a platform with OpenSSL 3.0 installed, despite setting `OPENSSL_API_COMPAT` to `10101`.

I would expect that setting `OPENSSL_API_COMPAT` would make the program not compile since [`EVP_RSA_gen`](https://www.openssl.org/docs/man3.0/man3/EVP_RSA_gen.html) is a 3.0 API.

The problem arises later on any platform where OpenSSL 1.1.1 is installed, where the program of course does not compile.

**Comment by t8m** [comment]
The OPENSSL_API_COMPAT has a different purpose. It would be a major feature to provide some additional define that would mask all the new APIs. There are also other possible incompatibilities between versions especially between different major versions that would not be solved by such conditional declarations.

**Comment by gideonda1** [comment]
Do newer versions of OpenSSH have full OpenSSL 3.0 API support?
It seems that when the `configure` script turns on `-DOPENSSL_API_COMPAT=0x10100000L` when not cross-compiling, which masks a whole lot of "Deprecated API" warnings.

I found this on all the recent debian package versions of OpenSSH:
Bookworm: `9.2p1-2+deb12u2`
Trixie and Sid: `9.7p1-5`

**Comment by t8m** [comment]
I do not think this will get ever implemented. Closing this.
