### ISSUE TITLE
Signature_Algorithms_Cert Extension

### ISSUE THREAD

**Issue by snachti** [openssl/openssl#20203]
The RFC 8446 (https://www.rfc-editor.org/rfc/rfc8446 chapter 4.2.3 ) introduces a new  optional _signature_algorithms_cert_ extension.
From a short source code analysis, I assume that OpenSSL does not implement this extension on client and server side. 

My question is if my assumption is correct and if yes, are there any plans to add this extension to OpenSSL in the future.

Cheers

**Comment by nhorman** [comment]
Its been supported since 2018 I believe (see commit c589c34e619c8700ab16b152dd9c8ee58356b319)
