### ISSUE TITLE
All mips32 code appends -mips2 to CFLAGs

### ISSUE THREAD

**Issue by immolo** [openssl/openssl#20214]
While compiling openssl-3.0.7 for a mipsel3 device in Gentoo I've found it appends `-mips2` to the for all mips32 devices which causes it to fail to compile when using `-march=mips3`. The last time I did this using openssl-1.0.1 this problem didn't exist so doing a quick search I've seen the way configure detects which cflags to append has changed in openssl-1.1.1 and every 3.x release I've found. https://github.com/openssl/openssl/blob/master/Configure#L1481 shows what is causing the issue.

I wrote a small patch that works for me but this can't be PRed as is however I will try to find a more elegant solution when time allows if no one has solved this before I get around to it.

**Comment by matoro** [comment]
This same problem exists with the mips64 code which unconditionally appends `-mips3`, even when other CFLAGs specify a higher level.

```
cc1: error: '-mips3' conflicts with the other architecture options, which specify a mips64r2 processor
```
