### ISSUE TITLE
PEM_write_TYPE() wrong return value in man-pages

### ISSUE THREAD

**Issue by devio** [openssl/openssl#20218]
Affected: 

- openssl 1.1.1s
- openssl 3.0.7

Example: https://www.openssl.org/docs/man3.0/man3/PEM_write_bio_ECPrivateKey.html

> [...]
> PEM_write_TYPE() and PEM_write_bio_TYPE() return the number of bytes written or zero on error.
> [...]

Actually this is wrong. For example, `PEM_write_bio_ECPrivateKey` is implemented using macros (see `include/openssl/pem.h:133` for openssl 1.1.1s. The macro returns `PEM_ASN1_write_bio(...)` which is implemented in `crypto/pem/pem_lib.c` but returns `1` on success, and `0` on error. Length of data is never returned back to the caller.

This probably affects all `PEM_write_TYPE()` functions.

**Comment by LingkKang** [comment]
@paulidale Hi, can I work on this as my first contribution to open source?

**Comment by t8m** [comment]
> @paulidale Hi, can I work on this as my first contribution to open source?

Sure, just submit a PR, please

**Comment by blazmonster** [comment]
Hi, can I work on this if nobody is working ? I will wait for response for few hours.

**Comment by LingkKang** [comment]
@blazmonster Hi, can you find where this sentence is written in this repo?

> **PEM_write_*TYPE()*** and **PEM_write_bio_*TYPE()*** return the number of bytes written or zero on error.

 I went through the `doc` folder and tried to search but did not find it. 

Other functions' doc are correctly stated in the repo. For example [doc of `PEM_write_bio_CMS_stream`](https://github.com/openssl/openssl/blob/cd870db16348d0d09cb05b7393cf9281509c7795/doc/man3/PEM_write_bio_CMS_stream.pod#return-values) gives that '_returns 1 for success or 0 for failure._'

I'm not sure there anything I missed or not.

**Comment by Anis-cpu-13** [comment]
@paulidale Hi, can I work on this as my first contribution to open source?

**Comment by mattcaswell** [comment]
> @paulidale Hi, can I work on this as my first contribution to open source?

Please feel free to do so.

**Comment by Anis-cpu-13** [comment]
Hello, this issue is Always open, i would like work on this

**Comment by paulidale** [comment]
Feel free to work on this.

**Comment by blazmonster** [comment]
@LingkKang 
We can find the description (about PEM_write_TYPE() and PEM_write_bio_TYPE() return the number of bytes written or zero on error) in following link.
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1s/doc/man3/PEM_read_CMS.pod

you can find some hint from https://www.openssl.org/docs/man1.1.1/man3/PEM_write_bio_ECPrivateKey.html.
