### ISSUE TITLE
*ret is not NULL-ed in ENGINE_get_cipher

### ISSUE THREAD

**Issue by silabs-PeterK** [openssl/openssl#20227]
*ret is not NULL-ed in ENGINE_get_cipher in tb_cipher.c
When building OpenSSL on ARM (Raspberry Pi 400), this causes a serious bug.  OpenSSL version - 3.0.7.

From what I get about how engines work, "*ret" in ENGINE_get_cipher should be set to NULL. In OpenSSL, and in many other external engines, *_ciphers function depends on it.
```
static int openssl_ciphers(ENGINE *e, const EVP_CIPHER **cipher,
                           const int **nids, int nid)
{
    if (!cipher) {
```
Current state:
```
const EVP_CIPHER *ENGINE_get_cipher(ENGINE *e, int nid)
{
    const EVP_CIPHER *ret;
    ENGINE_CIPHERS_PTR fn = ENGINE_get_ciphers(e);
    if (!fn || !fn(e, &ret, NULL, nid)) {
        ERR_raise(ERR_LIB_ENGINE, ENGINE_R_UNIMPLEMENTED_CIPHER);
        return NULL;
    }
    return ret;
}
```

Should be:
```
const EVP_CIPHER *ENGINE_get_cipher(ENGINE *e, int nid)
{
    const EVP_CIPHER *ret = NULL;
    ENGINE_CIPHERS_PTR fn = ENGINE_get_ciphers(e);
    if (!fn || !fn(e, &ret, NULL, nid)) {
        ERR_raise(ERR_LIB_ENGINE, ENGINE_R_UNIMPLEMENTED_CIPHER);
        return NULL;
    }
    return ret;
}
```

**Comment by paulidale** [comment]
I am not convinced this is a bug in the code you're pointing to.

The engine that is being called should be setting the value of `ret` appropriately when it returns a success result.  If it isn't, the bug is in the engine.

**Comment by silabs-PeterK** [comment]
ret is an uninitialized variable that is sent to the engine. That shouldn't happen. It is a bug causing a fault in this particular engine (and all others btw.), but it is also a security issue. Please read this and reconsider your reply:

https://en.wikipedia.org/wiki/Uninitialized_variable#:~:text=In%20computing%2C%20an%20uninitialized%20variable,source%20of%20bugs%20in%20software.

In the engine (that I pointed to or any other), you want to know if there is a cipher already set when 
`static int *_ciphers(ENGINE *e, const EVP_CIPHER **cipher, const int **nids, int nid)` is called. This is done by checking against the NULL value, that is NOT SET. So there are some arbitrary data from memory, that we are able to read, but we are not able to distinguish from read cipher structure.

**Comment by paulidale** [comment]
It is an **output** from that function call.  It shouldn't need to be initialised.  If the engine can't fill the value in, it should return a failure which is checked for.

**Comment by silabs-PeterK** [comment]
I understand that. 
Can you explain to me then how line 227 in gost_ciphers, gost_eng.c works?
And line 301 in eng_openssl.c? Also line 775 in e_afalg.c, line 477 in e_dasync.c, 584 in e_devcrypto.c, 529 in e_ossltest.c, 538 e_padlock.c and many (all) other engines.
