### ISSUE TITLE
Disable default provider for Openssl-3

### ISSUE THREAD

**Issue by Pankul94** [openssl/openssl#20232]
I am using Openssl-3 with the FIPS provider in my `openssl.cnf` file. I understand that the default provider is built into libcrypto and is not provided like a shared object. While testing, I realized that I can always *override* the `openssl.cnf` file and load and activate the `default provider` which allows me to use non-FIPS algorithms like `ChaCha20`. I can use the following APIs to do this.

```
OSSL_PROVIDER_load(NULL, "default");
EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
EVP_CIPHER *temp = EVP_CIPHER_fetch(NULL,"chacha20","provider=default");
```

Is it possible to make `openssl.cnf` file the source of absolute truth for which provider is being used for cryptographic implementation. So if my `openssl.cnf` file looks like this:

>config_diagnostics = 1
openssl_conf = openssl_init
.include fipsmodule.cnf
>
>[openssl_init]
providers = provider_sect
alg_section = evp_properties
>
>[provider_sect]
fips = fips_sect
base = base_sect
>
>[base_sect]
activate = 1
>
>[evp_properties]
default_properties = fips=yes

I can be sure that there is no way for me to load and activate any other provider. Is there an API or a config which will stop me from loading another provider at runtime?

**Comment by paulidale** [comment]
There is no API call to do what you want.  A new provider can always be loaded.

If you want to force the FIPS provider's algorithms you can set the default property query: `EVP_set_default_properties(NULL, "fips=yes");`

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
