### ISSUE TITLE
Compile error in x509.h

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#20231]
Error
```
a_digest.c
openssl\openssl\include\crypto/x509.h(343): error C2143: syntax error: missing '{' before '*'
```

```
# ifndef OPENSSL_NO_DSA
----> DSA *ossl_d2i_DSA_PUBKEY(DSA **a, const unsigned char **pp, long length);
# endif /* OPENSSL_NO_DSA */
```

`Configure VC-WIN64A no-cmac no-ocsp no-ui-console no-sock no-dgram no-camellia no-idea no-rc2 no-md2 no-md4 no-sm2 no-sm3 no-sm4 no-mdc2 no-srp no-whirlpool no-seed no-rc4 no-rc5 no-engine no-cms no-scrypt no-cast no-err no-deprecated no-crypto-mdebug no-filenames no-async no-rmd160 no-comp no-ts no-gost no-ct no-chacha no-trace no-aria no-cmp no-legacy
`

Branch: master

I suspect the DSA struct is not declared. 

@t8m The regression is in this commit:
https://github.com/openssl/openssl/commit/604247bf75571c1c3fb6a1723346c61acd957221#diff-df82c30a4c3f4b998172ec654b6c982f4d4faace9e94cb2326a571131fa057ec

**Comment by t8m** [comment]
Fixed by a cherry-picked commit [03fd2dc](https://github.com/openssl/openssl/commit/03fd2dcb3431898e54e24b3021e9106257e0fdf0)
