### ISSUE TITLE
cant execute 'make install_fips' command

### ISSUE THREAD

**Issue by WilburZjh** [openssl/openssl#20236]

**Comment by WilburZjh** [comment]
I want to install openssl 3.0 version in my redhat machine. All commands execute fine until `make install_fips`. It returns an message: 
`The 'install_fips' target requires the 'enable-fips' option`
May I know how to setup this 'enable-fips' option?

**Comment by neverpanic** [comment]
Run ./Configure or ./config with the enable-fips parameter.

**Comment by WilburZjh** [comment]
Like: `./config --enable-fips`?

**Comment by neverpanic** [comment]
No, `./config enable-fips`.

**Comment by paulidale** [comment]
I'd strongly recommend reading the [security policy](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4282.pdf) and following the instructions there.
If you do not follow them **exactly**, you will not end up with a FIPS approved provider as is the case here.

**Comment by WilburZjh** [comment]
It works, thanks a lot!
