### ISSUE TITLE
Build problems: unrecognized command line option "-m64" , mipsel-linux-uclibc-gcc [openssl-1.0.2j]

### ISSUE THREAD

**Issue by phoebushome** [openssl/openssl#2024]
I compiled the openssl in the CentOS，and I encounter this error: 
/usr/bin/make64 MAC=64
making all in crypto...
make64[1]: Entering directory `/SourceCode/merlin/openssl-1.0.2j/crypto'
/usr/bin/perl ../util/mkbuildinf.pl "mipsel-linux-uclibc-gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H --host=mipsel-linux -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" "linux-x86_64" >buildinf.h
mipsel-linux-uclibc-gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H --host=mipsel-linux -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o cryptlib.o cryptlib.c
cc1: error: unrecognized command line option "-m64"
cc1: error: unrecognized command line option "-fhost=mipsel-linux"
make64[1]: *** [cryptlib.o] Error 1

More message:
build machine： CentOS 6.3 x86_64;
target：ASUS route RT-AC66u, SoC: BCM4706

I use the command: 
CC=mipsel-linux-uclibc-gcc CPP=mipsel-linux-uclibc-cpp CXX=mipsel-linux-uclibc-g++ LD=mipsel-linux-uclibc-ld AR=mipsel-linux-uclibc-ar ./config --host=mipsel-linux;
make

can anyone assist how i can go around this

**Comment by kaduk** [comment]
On 12/03/2016 03:06 AM, Phoebushome wrote:
>
> More message:
> build machine： CentOS 6.3 x86_64;
> target：ASUS route RT-AC66u, SoC: BCM4706
>
> I use the command:
> CC=mipsel-linux-uclibc-gcc CPP=mipsel-linux-uclibc-cpp
> CXX=mipsel-linux-uclibc-g++ LD=mipsel-linux-uclibc-ld
> AR=mipsel-linux-uclibc-ar ./config --host=mipsel-linux;
> make
>
> can anyone assist how i can go around this
>
>

Generally the advice is given that when cross-compiling, do not attempt
to use ./config; instead ./Configure with an explicit configuration
string for the target platform.  (I am no expert, but maybe linux-mips32
is better?  Look in ./Configurations for possible values.)

-Ben

**Comment by dot-asm** [comment]
> when cross-compiling, do not attempt to use ./config;

Absolutely correct. And recommended what to specify cross-compiler prefix is to use `--cross-compile-prefix` argument to ./Configure or set CROSS_COMPILE environment variable. It might be worth noting that in this case prefix would be `mipsel-linux-uclibc-`, i.e. it would end with dash.

**Comment by mattcaswell** [comment]
Question was answered. Closing this issue.

**Comment by bobpoekert** [comment]
If the recommendation for cross-compiling is not to use ./config then https://wiki.openssl.org/index.php/Android should be changed to reflect that.
