### ISSUE TITLE
Openssl 3.0 "unable to get issuer certificate" on a valid certificate

### ISSUE THREAD

**Issue by AppSecAmael** [openssl/openssl#20263]
Hello, 

I have reinstalled a fresh Kali 2022.04 virtual machine, by using the same vagrant+ansible scripts than usual. The ansible part is registring a private CA certificate in the system by adding it to `/usr/local/share/ca-certificates/myname.crt` and then running `update-ca-certificates`. My packages are up-to-date with a fresh upgrade to the latest versions : `openSSL version` reports `OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)`.

From that virtual machine I try to connect to internal websites of my company, but the certificate verification fails with `Return code 2 (unable to get issuer certificate)`. The same test on ALL of my other virtual machines is OK - this one seems to be the only one with OpenSSL 3.*. 

I have tried to run openssl in debug mode, lower the ciphers, select exactly the same curves on both VMs and I still get the error... 
Any idea ?

### Kali with OpenSSL 3.0.7

Command : `openssl s_client -connect  anytool.corp.tld:443 -CApath /etc/ssl/certs -cipher DEFAULT@SECLEVEL=0 -trace`
N.B. : same result with `-curves "P-256"`

Result : 
```    

-----END CERTIFICATE-----
subject=C = FR, ST = PARIS, L = PARIS, O = MyCompany, OU = DI, CN = anytool.corp.tld
issuer=DC = company, DC = activedirectory, CN = Corporate Internal Issuing CA
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 5122 bytes and written 407 bytes
Verification error: unable to get issuer certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 2B0700006EB9944C0264736B0F3E42F7FA2B4BA13ED3FCB9B75046E1EB52F326
    Session-ID-ctx: 
    Master-Key: 7BDFEBFD144B1F445482D7F2D501F496F4A2CDD0AC0EEBB833210F437452DBCC477F52C9CFAB54E2C46A8AD4ED29B512
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1676051188
    Timeout   : 7200 (sec)
    Verify return code: 2 (unable to get issuer certificate)
    Extended master secret: yes
---
                                                             
```

### Debian 10 with OpenSSL 1.1.1n  15 Mar 2022
Command :  `openssl s_client -connect anytool.corp.tld:443 -CApath /etc/ssl/certs -debug`
N.B. : same result on a CentOS Server with an older OpenSSL version that uses with P-256 curves

Result : 
```
[...]
-----END CERTIFICATE-----
subject=C = FR, ST = PARIS, L = PARIS, O = MyCompany, OU = DI, CN = anytool.corp.tld

issuer=DC = company, DC = activedirectory, CN = Corporate Internal Issuing CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 5122 bytes and written 403 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: EB390000BBEAD714BB8FFE1D729FA01A688504EB3B691E29ED0CA90B50D03EE1
    Session-ID-ctx:
    Master-Key: 658EA1353BAEFA4C43BA795FE16C68C3C7C5C270DED66C215D30AEA88F311173F7CCE400CA9B3AED0B1A774E3D7A852B
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1676051130
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---

```

**Comment by t8m** [comment]
Would you be able to attach the certificate and the issuer certificate here, please? Also could you please verify that the CA root certificate is in the /etc/ssl/certs directory and linked by the hash symlink xxxxxx.0 ? Or you use `-CAfile /usr/local/share/ca-certificates/myname.crt` to test whether the problem is in the trust store or anywhere else.
