### ISSUE TITLE
Is there a similar function in OpenSSL 3.x version as FIPS_mode() function in OpenSSL 1.x version?

### ISSUE THREAD

**Issue by WilburZjh** [openssl/openssl#20266]

**Comment by WilburZjh** [comment]
I realized that the old functions `FIPS_mode()` and `FIPS_mode_set()` are no longer present. And according to the `fips_module` described in this [site](https://www.openssl.org/docs/man3.0/man7/fips_module.html), is there any other functions that I can use to check if the current version of OpenSSL is FIPS capable or not?

**Comment by paulidale** [comment]
There is no direct equivalent.  There are helper functions that kind of do something similar but they come with caveats.
It is all [documented](https://www.openssl.org/docs/man3.0/man7/fips_module.html).

**Comment by mattcaswell** [comment]
> There are helper functions that kind of do something similar but they come with caveats.

In particular see these functions:

https://www.openssl.org/docs/man3.0/man3/EVP_default_properties_enable_fips.html

**Comment by WilburZjh** [comment]
I see, so if i want to only use the `OSSL_PKCS5_PBKDF2_HMAC` function by using FIPS provider, I would set something like:
```
EVP_MD *pbkdf2;

pbkdf2 = EVP_MD_fetch(NULL, "PBKDF2", "fips=yes");
```

Right?

**Comment by WilburZjh** [comment]
Btw, may I know what is OSSL_LIB_CTX? I could not find an detailed explanation...

**Comment by mattcaswell** [comment]
You should read the "Library Contexts" section of this page:

https://www.openssl.org/docs/man3.0/man7/crypto.html

As well as this page:

https://www.openssl.org/docs/man3.0/man3/OSSL_LIB_CTX.html

**Comment by slontis** [comment]
>

Or you can do this once..
````
EVP_default_properties_enable_fips(NULL, 1);
````
Which applies fips=true to all fetches...

pbkdf2 = EVP_KDF_fetch(NULL, "PBKDF2", NULL); //This merges in the global property fips=true

**Comment by WilburZjh** [comment]
Thanks! This is helpful.
