### ISSUE TITLE
[BUG]A double free bug in crypto/http/http_client.c

### ISSUE THREAD

**Issue by Kylin-1** [openssl/openssl#20278]
**File:** crypto/http/http_client.c
**Bug Function:** BIO *OSSL_HTTP_get
**Version:** Git-master(2023-02-11)

**Description:** In function `BIO *OSSL_HTTP_get`,` rctx `was allocated at line 1195.
 At line 1200, if`(!OSSL_HTTP_set1_request(rctx, path,......,0)` is true, `rctx`will be first freed at line 1206.
At line 1211,the condition `resp == NULL && redirection_url != NULL` is almost impossible to happen, so program will execute backwards.
When this function executes to line 1239, `rctx` will be freed in the second time by the code statement `if (!OSSL_HTTP_close(rctx, resp != NULL))` , which is a double free bug.

**Code Description:**

```
BIO *OSSL_HTTP_get(const char *url, const char *proxy,……,int timeout)
{
    ……
    OSSL_HTTP_REQ_CTX *rctx;
    BIO *resp = NULL;
    ……
    for (;;) {
        ……
1195:        rctx = OSSL_HTTP_open(host, port,……, timeout);    //rctx was allocated in here!
    new_rpath:
        if (rctx != NULL) {
            if (!OSSL_HTTP_set1_request(rctx, path,……,0))
1200:                OSSL_HTTP_REQ_CTX_free(rctx);     //rctx was freed in here the first time!
            else
                resp = OSSL_HTTP_exchange(rctx, &redirection_url);
        }
        OPENSSL_free(path);
1211:        if (resp == NULL && redirection_url != NULL) {    //this condition is almost impossible to happen
        ……
        }
        OPENSSL_free(host);
        OPENSSL_free(port);
1239:        if (!OSSL_HTTP_close(rctx, resp != NULL)) {    
             //rctx will be freed in here the second time,which will cause a double free bug
            BIO_free(resp);
            resp = NULL;
        }
        break;
    }
    OPENSSL_free(current_url);
    return resp;
}

**Comment by blazmonster** [comment]
Hi
I am trying to resolve this bug since nobody is working on this.
