### ISSUE TITLE
Confusing error message with SSL routines::ca md too weak 

### ISSUE THREAD

**Issue by kumarrishav** [openssl/openssl#20272]
Even though it was cert (not the ca) which has the issue (an error was thrown while using node 18 as it comes with openssl v3), it throws

`SSL routines::ca md too weak`.

Expectation: `SSL routines::cert md too weak`.

https://github.com/nodejs/node/discussions/46545#discussioncomment-4950757

**Comment by kroeckx** [comment]
Please note that the signature is generated by the CA, so it's the CA that used the weak MD.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
