### ISSUE TITLE
OpenSSL 1.1.1t: 32-bit builds using Visual Studio compiler broken

### ISSUE THREAD

**Issue by Dani-Hub** [openssl/openssl#20280]
When attempting to build the recent 1.1.1t release sources from scratch using Visual Studio (In my example: VS 2019) under 32-bit, I'm getting the following build error:
```
[INFO] libcrypto-1_1.lib(rsa_sup_mul.obj) : error LNK2019: unresolved external symbol __umul128 referenced in function __mul_limb [XXX\win32-x86-vc142\apps\openssl.vcxproj]
[INFO] XXX\bin\openssl\win32-x86-vc142\Debug\openssl.exe : fatal error LNK1120: 1 unresolved externals [XXX\win32-x86-vc142\apps\openssl.vcxproj]
[INFO] ExitValue: 1
```
The root of the problem becomes more evident by the following preceding warning:
```
[INFO] XXX\src\crypto\bn\rsa_sup_mul.c(114,9): warning C4163: '_umul128': not available as an intrinsic function [XXX\win32-x86-vc142\crypto\crypto.vcxproj]
```
So, it seems that the existing preprocessor conditional in line 112 of /crypto/bn/rsa_sup_mul.c,
```
#elif (BN_BYTES == 8) && (defined _MSC_VER)
```
is insufficient to be entered for a 32-bit build and according to the referred to Microsoft documentation https://learn.microsoft.com/en-us/cpp/intrinsics/umul128?view=msvc-170 the `_umul128` intrinsic is only on 64-bit available. I got the build fixed by extending the conditional to
```
#elif (BN_BYTES == 8) && (defined _MSC_VER) && defined(_WIN64)
```
which solved the problem.

I'm prepared to make a corresponding PULL request, if the direction of the fix seems plausible.

**Comment by beldmit** [comment]
Could you please check whether fix from https://github.com/openssl/openssl/pull/20244 fits your purposes?

**Comment by Dani-Hub** [comment]
> Could you please check whether fix from #20244 fits your purposes?

I tested the patch provided by https://github.com/openssl/openssl/pull/20244/files but the build now fails fast here:
```
src\crypto\bn\rsa_sup_mul.c(139,1): fatal error C1189: #error:  Only x64, ARM64 and IA64 supported. [XXX\crypto\crypto.vcxproj]
```
That patch seems still not to properly recognize that we perform a 32-bit build. So my originally suggested extended conditional seems to be required.

**Comment by beldmit** [comment]
Yes, feel free to raise the PR then

**Comment by Dani-Hub** [comment]
I prepared a PULL request #20285 but the CLA is missing. How can I grant it?

**Comment by zzl360** [comment]
see https://www.openssl.org/policies/cla.html
IMO, this PR could be trivial.

**Comment by t8m** [comment]
How could BN_BYTES==8 on 32 bit build? That does not seem right.

**Comment by t8m** [comment]
Here you can see that WIN32 build using MSVC is passing on current tip of the 1.1.1 tree: https://github.com/openssl/openssl/actions/runs/4151672870/jobs/7182124549

**Comment by t8m** [comment]
Could you please show the Configure command and/or configdata.pm -d output?

**Comment by Dani-Hub** [comment]
OK, I have understood the root of the issue. This is actual a problem of the cmake variant of this project, which leads to an incorrect outcome for the `SIXTY_FOUR_BIT` define on 32-bit. I'm opening an issue in that project instead.

I suggest to close this issue here as won't fix - thanks for giving me the right hints to find the root of the problem.
