### ISSUE TITLE
Typo in "config" man page

### ISSUE THREAD

**Issue by tomiii00** [openssl/openssl#20290]
The "config" master & 3.x man pages contains a typo in the description for the ".pragma" directive:

"If value is true or on, then foo$bar is a single seven-character name **_nad_** variable expansions must be specified using braces or parentheses."

**Comment by blazmonster** [comment]
Hi,
I want to contribute here.

**Comment by blazmonster** [comment]
can we close this bug since it is merged ?@paulidale
