### ISSUE TITLE
Regression in openssl 3.0.8 caused by https://github.com/openssl/openssl/commit/fab4973801bdc11c29c4c8ccf65cf39cbc63ce9b

### ISSUE THREAD

**Issue by tsdgeos** [openssl/openssl#20309]
https://github.com/openssl/openssl/commit/fab4973801bdc11c29c4c8ccf65cf39cbc63ce9b causes a regression in X509_check_issued

Before that commit calling X509_check_issued with two particular certs returned X509_V_OK and now does not.

You can find the code to reproduce the problem at https://invent.kde.org/-/snippets/2504

You can find the two certificates used in that example at https://invent.kde.org/libraries/qca/-/raw/master/unittest/pkits/certs/ValidDSAParameterInheritanceTest5EE.crt and https://invent.kde.org/libraries/qca/-/raw/master/unittest/pkits/certs/DSAParametersInheritedCACert.crt

**Comment by tsdgeos** [comment]
@t8m @mattcaswell @paulidale

**Comment by dcooper16** [comment]
This seems to be the same as #20233.

**Comment by t8m** [comment]
Duplicate of #20233
