### ISSUE TITLE
Replacement APIs for deprected API calls

### ISSUE THREAD

**Issue by stefanberger** [openssl/openssl#20313]
Hello!

  As part of trying to replace deprecated API calls and use OpenSSL 3 API calls instead I have come across a few issues when trying to convert a TPM 2 emulator code base:

1.  While trying to replace `EC_KEY_set_group()` I ran into an issue with a bnp256 curve (see TCG TPM Algorithms registry [here](https://trustedcomputinggroup.org/wp-content/uploads/TCG-_Algorithm_Registry_r1p32_pub.pdf) table 4). The problem seems to be that OpenSSL does not support this curve (at least on Fedora) and using the curve is rejected due to this gate here in `EC_GROUP_new_from_params()`:

https://github.com/openssl/openssl/blob/cd870db16348d0d09cb05b7393cf9281509c7795/crypto/ec/ec_lib.c#L1712-L1716

I suppose there is no way to use this curve unless one keeps on using the deprecated `EC_KEY_set_group()` API call. Is this correct?

2. Do you happen to know of a better way to assign an existing `EC_GROUP` to an `EVP_PKEY` or `EVP_PKEY_CTX` than going through converting the `EC_GROUP` to `OSSL_PARAM`? I have a PR for the TPM 2 emulator [here](https://github.com/stefanberger/libtpms/pull/352) where I am going through the somewhat expensive conversion of the `EC_GROUP` to `OSSL_PARAM` in the function `OpenSSLBuildEcParams()` that I wished I could avoid.

3. Is there any way to reach the code of the deprecated `EC_POINTs_mul()` via a higher level API call?

4. Lastly and probably most important: I suppose that the deprecated API calls won't disappear any time soon. Am I right?

**Comment by mattcaswell** [comment]
This looks like an OpenSSL bug to me. Looking at the implementation of `ec_group_explicit_to_named` it is supposed to return the input group in the event that the group is unrecognised (i.e. so that `named_group == group`). `EC_GROUP_new_from_params()` is then supposed to do the right thing and go on to return an explicit curve as a set of params.

Just from code inspection my guess is that  `ec_group_explicit_to_named` is actually finding a NID for the group, but then subsequently failing to create an `EC_GROUP` object for it (maybe support for the group is not compiled in, but the NID is still recognised??).

**Comment by beldmit** [comment]
Fedora strictly limits the set of curves and implements countermeasures to provide any custom curves. So probably it's not an OpenSSL bug.

**Comment by t8m** [comment]
> named_group = ec_group_explicit_to_named(group, libctx, propq, bnctx);

This should not reject an arbitrary explicit group. For such groups this function returns the group passed into it.

NULL return means there is something wrong with the parameters. You need to investigate further inside the ec_group_explicit_to_named() function what goes wrong there.

**Comment by stefanberger** [comment]
> NULL return means there is something wrong with the parameters. You need to investigate further inside the ec_group_explicit_to_named() function what goes wrong there.

It indeed seems to be the case that Fedora's OpensSSL 3.0.8 must have been patched in a way that it behaves differently than upstream OpenSSL.

I have the following code here in `ec_group_explicit_to_named` that ends up returning NID_undef and using the curve unknown to OpenSSL ends up failing --- the else branch is important:

```
1417        if ((curve_name_nid = ossl_ec_curve_nid_from_params(dup, ctx)) != NID_undef) {
1418            /*
1419             * The input explicit parameters successfully matched one of the
1420             * built-in curves: often for built-in curves we have specialized
1421             * methods with better performance and hardening.
1422             *
1423             * In this case we replace the `EC_GROUP` created through explicit
(gdb)
1424             * parameters with one created from a named group.
1425             */
[...]
1460        } else {
1461            goto err;
1462        }
```

The OpenSSL repo for 3.0.8 has this:

https://github.com/openssl/openssl/blob/31157bc0b46e04227b8468d3e6915e4d0332777c/crypto/ec/ec_lib.c#L1460-L1462

Well, it's unfortunate...

**Comment by stefanberger** [comment]
To the other part of my question. Is there and alternative for the deprecated `EC_POINTs_mul()` function.

https://github.com/openssl/openssl/blob/73b0126150b298f4c9cdccd1baac154c49cbaf46/crypto/ec/ec_lib.c#L1066-L1070

To me it looks like `EC_POINTs_mul()` provides a superset of functionality compared to `EC_POINT_mul()` and from that perspective `EC_POINT_mul()` should be deprecated because working around deprecated `EC_POINTs_mul()` seems difficult.

https://github.com/openssl/openssl/blob/73b0126150b298f4c9cdccd1baac154c49cbaf46/crypto/ec/ec_lib.c#L1114-L1115

**Comment by stefanberger** [comment]
To the other part of my question. Is there an alternative for the deprecated `EC_POINTs_mul()` function?

https://github.com/openssl/openssl/blob/73b0126150b298f4c9cdccd1baac154c49cbaf46/crypto/ec/ec_lib.c#L1066-L1070

To me it looks like `EC_POINTs_mul()` provides a superset of functionality compared to `EC_POINT_mul()` and from that perspective `EC_POINT_mul()` should be deprecated because working around deprecated `EC_POINTs_mul()` seems difficult.

https://github.com/openssl/openssl/blob/73b0126150b298f4c9cdccd1baac154c49cbaf46/crypto/ec/ec_lib.c#L1114-L1115

**Comment by mattcaswell** [comment]
Well the man page says this about the `EC_POINTs_mul()` deprecation: "Modern versions should instead use EC_POINT_mul(), combined (if needed) with EC_POINT_add() in such rare circumstances.". For reference the deprecation was implemented by #11807 based on an initial proposal in #8332.

**Comment by stefanberger** [comment]
So the man page gives this math here:

```
EC_POINT_mul calculates the value generator * n + q * m and stores the result in r.
```

```
Although deprecated in OpenSSL 3.0 and should no longer be used, EC_POINTs_mul calculates the value generator * n + q[0] * m[0] + ... + q[num-1] * m[num-1].
```

There are the scaling factors (m[0] ... m[num-1]) for the points it seems that seem to not allow a simple `EC_POINT_add()` unless the point was scaled before. It just seems a bit dangerous to get this wrong.

**Comment by bbbrumley** [comment]
Hi,

@stefanberger In your use case, what does your point multiplication look like? If it looks like any of `aG`or `bP`or `aG + bP`, all three of those use cases are covered by `EC_POINT_mul`.

**Comment by bbbrumley** [comment]
.. and maybe I missed it above, but if you share the code including the `EC_POINTs_mul` call, I'm happy to help shoehorning it into the API.

**Comment by stefanberger** [comment]
The code can be found here:

https://github.com/stefanberger/libtpms/blob/d08b929dede77bee05bd674d48c7a0548528ca9c/src/tpm2/crypto/openssl/TpmToOsslMath.c#L673-L700

```
LIB_EXPORT BOOL
BnEccModMult2(
	      bigPoint             R,         // OUT: computed point
	      pointConst           S,         // IN: optional point
	      bigConst             d,         // IN: scalar for [d]S or [d]G
	      pointConst           Q,         // IN: second point
	      bigConst             u,         // IN: second scalar
	      bigCurve             E          // IN: curve
	      )
{
    EC_POINT            *pR = EC_POINT_new(E->G);
    EC_POINT            *pS = EcPointInitialized(S, E);
    BIG_INITIALIZED(bnD, d);
    EC_POINT            *pQ = EcPointInitialized(Q, E);
    BIG_INITIALIZED(bnU, u);
    
    if(S == NULL || S == (pointConst)&(AccessCurveData(E)->base))
	EC_POINT_mul(E->G, pR, bnD, pQ, bnU, E->CTX);
    else
	{
	    const EC_POINT        *points[2];
	    const BIGNUM          *scalars[2];
	    points[0] = pS;
	    points[1] = pQ;
	    scalars[0] = bnD;
	    scalars[1] = bnU;
	    EC_POINTs_mul(E->G, pR, NULL, 2, points, scalars, E->CTX);
	}
[...]
```

**Comment by bbbrumley** [comment]
Thanks for sharing. How do you actually reach this code through a cryptographic primitive?

I'm curious, because in about 15 years, this is the first time I've seen code calling `EC_POINTs_mul` where `num != 1`.

**Comment by stefanberger** [comment]
@bbbrumley I am not the author of the TPM 2 code... What I have is a pretty extensive test suite for the TPM 2 that also doesn't provide coverage for this particular code: https://coveralls.io/builds/57233185/source?filename=src%2Ftpm2%2Fcrypto%2Fopenssl%2FTpmToOsslMath.c#L693  So I am afraid I cannot easily answer this question, either.

**Comment by bbbrumley** [comment]
Alright. Without a cryptographic use case, it's hard for me to say what a good way forward is.

But here's a guess, since this looks more like elliptic curve math functionality than crypto:

1. One `EC_POINT_mul` call for `pS`
2. One `EC_POINT_mul` call for `pQ`
3. One `EC_POINT_add` call to combine the two above outputs and get the result

You're right, it's not as smooth as the deprecated API. OTOH I am not aware of any `libcrypto` code that requires that level of generality.

Hope it helps,

BBB

**Comment by stefanberger** [comment]
The only caller that would invoke this function is from an SM2 related function here: https://github.com/stefanberger/libtpms/blob/master/src/tpm2/crypto/openssl/CryptEccKeyExchange.c#L360

**Comment by bbbrumley** [comment]
Good find, thanks.

It seems one of the scalars is `One == 1` there? So again just guessing, but it doesn't look like a "real" multi scalar multiplication. The programmer is just abusing the API like that.

(So in reality, to me, it looks like one point multiplication, and one point addition.)

**Comment by stefanberger** [comment]
> But here's a guess, since this looks more like elliptic curve math functionality than crypto:
> 
>     1. One `EC_POINT_mul` call for `pS`
> 
>     2. One `EC_POINT_mul` call for `pQ`
> 
>     3. One `EC_POINT_add` call to combine the two above outputs and get the result

```
	{
	    const EC_POINT        *points[2];
	    const BIGNUM          *scalars[2];
	    points[0] = pS;
	    points[1] = pQ;
	    scalars[0] = bnD;
	    scalars[1] = bnU;
	    EC_POINTs_mul(E->G, pR, NULL, 2, points, scalars, E->CTX);
	}
```

Since the generator is NULL this should translate to this here I suppose:

```
EC_POINT_mul(E->G, R1, NULL, pS, bnD, E->CTX);
EC_POINT_mul(E->G, R2, NULL, pQ, bnU, E->CTX);
EC_POINT_add(E->G, R, R1, R2, E->CTX);
```

**Comment by bbbrumley** [comment]
looks right, yup!

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
