### ISSUE TITLE
Is it possible to initialize a custom libctx w/o causing the default context to be initialized?

### ISSUE THREAD

**Issue by simo5** [openssl/openssl#20315]
In this comment https://github.com/OpenSC/OpenSC/pull/2712#issuecomment-1432221284 we have a trace that shows how openssl seem to end up initializing the default context even though a custom OSSL_LIB_CTX was created.

The custom OSSL_LIB_CTX was created explicitly to avoid interfering with the main application context, and explicitly using only the default (and sometimes legacy) providers and nothing else.

However due to the ordering of how the application is initializing this code ends up being called before any other crypto calls have been made.

This happens inside a loadable module, so we can't control how the calling application initialized or didn't.

The issue arise because in this case the code being called is within a module that is also loaded by one of the providers (pkcs11-provider) during initialization of the provider itself.

Does OpenSSL need to forcibly initialize the default context when a custom OSSL_LIB_CTX is being used?

It sounds to me like we should be able to initialize a custom context, and potentially with a custom configuration file, w/o interfering at all with the default context, but there may be internal reasons why this is not working.

In that case I traced it down to ossl_method_store_fetch() always and unconditionally initializing the default context with configuration loading:
```
 #ifndef FIPS_MODULE
    if (!OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL))
        return 0;
#endif
```

There does not seem to be a way to pass a OSSL_LIB_CTX to OPENSSL_init_crypto() anyway ...

**Comment by simo5** [comment]
@beldmit FYI

**Comment by mattcaswell** [comment]
Hmmm. Well, the default libctx can get automatically initialised if you start making any crypto calls, if the application has not already explicitly done so.

But what difference does it make if it gets initialised if you are not using it? The only way I can see that this makes a difference is if the application wants to do some non-default initialisation (e.g. block the loading of the config file). But if that is the case then the onus is very much on the application to ensure it does this before any other crypto calls.

**Comment by slontis** [comment]
You can also load the NULL provider into the default context. Once you do this it will not load the default provider unless you tell it to.

**Comment by t8m** [comment]
> In that case I traced it down to ossl_method_store_fetch() always and unconditionally initializing the default context with configuration loading:
> 
> ```
>  #ifndef FIPS_MODULE
>     if (!OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL))
>         return 0;
> #endif
> ```

@simo, could you please dump the backtrace when this gets called?

**Comment by beldmit** [comment]
@t8m probably this
https://github.com/OpenSC/OpenSC/pull/2712#issuecomment-1432221284

@simo5 correct me if I'm wrong

**Comment by simo5** [comment]
@beldmit correct, the backtrace is already there

@mattcaswell the problem is that what is causing the initialization is a loadable module that just happen to use OpenSSL services, but has no knowledge of what the application wants to do. This is why I wanted a compltely private initialization so that I would not interfere with anything the app may do.

Additionally because this same module can be loaded by one of the provider we are currently in a situation where a default initialization of the context ends up looping back into a global initialization function.

Now the loop is something we can deal with on our own, and I already have patches to handle that. But the problem of initializing OpenSSL potentially in ways the application doesn't want remain.

Of course we can document that an application should update OpenSSL as the very first thing if it cares about this, but it only works if the "thing" that initializes OpenSSL is an actual application, if it is yet another library/loadable module, the order of which ends up calling OpenSSL initialization first is somewhat indeterminate.

I feel like being able to have a completely private context (that does not influence the "default" context, should be possible, but clearly it seem that is not the current design of OpenSSL ...

I was wondering if I could work around this by:
1. create a new private libctx.
2. set the default_ctx with this private libctx
3. do my initialization
4. reset back the default_ctx to NULL

But looking at the code it seem this won't work because some of the init stuff uses "run once" calls that are global and not tied to a context, I wonder if all should be "contextualized" instead, or if there are things that would break in doing so.

**Comment by mattcaswell** [comment]
> I feel like being able to have a completely private context (that does not influence the "default" context), should be possible, but clearly it seem that is not the current design of OpenSSL ...

Correct. The current OpenSSL design is that the onus is on the application to ensure that it does any non-default initialisation as the first thing it does. If we're actually talking about another loadable module rather than the application itself directly, then it would seem quite strange to me for another loadable module to require non-default initialisation of the default context. Ideally, all modules would be using a custom context anyway (that was part of the intent behind the libctx design - to allow different modules to exist without stepping on each other's toes).

> I was wondering if I could work around this by:

I suspect this would not work for the reasons you have stated.

**Comment by simo5** [comment]
@mattcaswell:
> Ideally, all modules would be using a custom context anyway (that was part of the intent behind the libctx design - to allow different modules to exist without stepping on each other's toes).

But this doesn't seem to be really working currently as advertized, invoking something as simple a EVP_MD_fecth() causes OpenSSL to go through default context initialization.

If a module is loaded early on (for example in a library constructor) OpenSSL ends up being initialized before the main application can do anything about it.

I was wondering if OpenSSL should have a library constructor that always pre-initializes OpenSSL, given the current idea that "the app should do init first" is basically a lie.

At least it will be clear that just linking to OpenSSL initializes it and application writers go on about changing the default context configuration after the fact.

**Comment by mattcaswell** [comment]
Ok, I have a possible solution for the "fetch" case in #20341. It's an imperfect solution since it doesn't cover other instances where this could occur (which are less easy to resolve) - but at least it covers this commonly hit scenario.
