### ISSUE TITLE
crypto/evp/pmeth_gn.c as a part of fips module

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#20329]
I see the `crypto/evp/pmeth_gn.c` as a part of `fips.sources`. 

When I add a debug print under `#ifdef FIPS_MODULE` in `EVP_PKEY_generate` function, it shows that the call is not done from FIPS provider, though the file is linked to `libfips.a` according to the build log. Could you please explain how does it happen?

**Comment by mattcaswell** [comment]
Many source files are compiled twice - once for including into libcrypto, and once for including into fips.so. The FIPS provider must be entirely self-contained and does not link against libcrypto at all. When an application calls `EVP_PKEY_generate` you are calling the libcrypto version. That will in turn call other functions that exist within the fips provider to actually do the crypto work. It is possible that the FIPS provider *itself* might call EVP functions (including `EVP_PKEY_generate`). If it does so then it calls the copy that has been linked into fips.so and not libcrypto.

**Comment by beldmit** [comment]
Thank you!
