### ISSUE TITLE
openssl s_server started with tls_1.3 return handshake failure and the s_server started with tls_1.2 passed for s_client request with the same parameters

### ISSUE THREAD

**Issue by nghydj01** [openssl/openssl#20337]
Hi,

Started two openssl tls servers with s_server and they have the same parameters except for the tls version and listening ports. 

- TLS 1.2
> openssl s_server -accept 4455 -named_curve secp384r1 -Verify 3 -verify_return_error -x509_strict -cert ./ecdsa_leaf_521.crt -key ./private/ecdsa_leaf_521.key -CAfile ./ecdsa_ca_384.crt -www -tls1_2  -keylogfile os_key.log 

- TLS 1.3

> openssl s_server -accept 4433 -named_curve secp384r1 -Verify 3 -verify_return_error -x509_strict -cert ./ecdsa_leaf_521.crt -key ./private/ecdsa_leaf_521.key -CAfile ./ecdsa_ca_384.crt -www -tls1_3  -keylogfile os_key.log

Then using openssl s_clients to connect these two servers with the same parameters except for ports
- to connect tls 1.2
> openssl s_client -CAfile ./ecdsa_ca_521.crt -key private/ecdsa_leaf_384.key -cert ecdsa_leaf_384.crt -showcerts -servername client.com.cn -connect client.com.cn:4455 -sigalgs  "ECDSA+SHA256:ECDSA+SHA384" -client_sigalgs "ECDSA+SHA384" -keylogfile os_key.log -verify 3 -verify_return_error -x509_strict

-to connect tls 1.3
> openssl s_client -CAfile ./ecdsa_ca_521.crt -key private/ecdsa_leaf_384.key -cert ecdsa_leaf_384.crt -showcerts -servername client.com.cn -connect client.com.cn:4433 -sigalgs  "ECDSA+SHA256:ECDSA+SHA384" -client_sigalgs "ECDSA+SHA384" -keylogfile os_key.log -verify 3 -verify_return_error -x509_strict

The result is:
The TLS 1.3 server returned error 
> openssl s_server -accept 4433 -named_curve secp384r1 -Verify 3 -verify_return_error -x509_strict -cert ./ecdsa_leaf_521.crt -key ./private/ecdsa_leaf_521.key -CAfile ./ecdsa_ca_384.crt -www -tls1_3  -keylogfile os_key.log
> verify depth is 3, must return a certificate
> Using default temp DH parameters
> ACCEPT
> 
> 140224929047872:error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:../ssl/t1_lib.c:2759:
> 

The TLS 1.2 server passed and check the Server Key Exchange package from Server with wireshare. It is named_curve secp384r1 EC Diffie-Hellman Server Params with ecdsa_secp256r1_sha256 signature algorithm. 
Dose the secp256r1 algorithm can signature server exchange information with secp521r1 private key in server certificate? If it can be, why openssl s_server 1.3 returned no suitable signature algorithm?

The openssl version is: OpenSSL 1.1.1n  15 Mar 2022
Best Regards

**Comment by mattcaswell** [comment]
For the TLSv1.3 connection you are passing through the following sigalgs: "ECDSA+SHA256:ECDSA+SHA384"

However, based on the server certificate filename, the certificate is using the secp521r1 curve.

TLSv1.3 defines the following SignatureScheme values (see RFC8446):

````
          ecdsa_secp256r1_sha256(0x0403),
          ecdsa_secp384r1_sha384(0x0503),
          ecdsa_secp521r1_sha512(0x0603),
````
So in order to use the secp521r1 curve in TLSv1.3 you need to support the "ECDSA+SHA512" sigalg - which your s_client command line does not have.

**Comment by nghydj01** [comment]
Hi mattcaswell, 
Many thanks for your further explanation. I studied RFC8446, RFC5246 and RFC4492 again based on your comments. Does my following understanding correct. 
- In TLSv1.2, the sig algs and hash algs are defined separately and independently. The sig algs does not specify which curve is to use and only the type; ECDSA. So for my example above, although Wireshark show the Signature Algorithm as ecdsa_secp256r1_sha256, the TLSv1.2 server still use secp521r1 alg and hashed by sha256 to authenticate in Server Key Exchange. The client must public to support secp521r1 curve in supported_groups of Client Hello.
- At the same time, in TLSv1.3, it is impossible to authenticate with such combination above: secp521r + SHA256, it only have the three combinations of curve and hash in your first message. In other word, each curve must match one equivalent hash alg.
- No matter TLSv1.2 and TLSv1.3 and no matter server authentication and client authentication, for ecdsa authentication, the end node always use the same curve as that private key used in itself certificate to authenticate itself.

**Comment by mattcaswell** [comment]
Correct

**Comment by nghydj01** [comment]
mattcaswell, appreciated for your help, I will close this issue. Thanks again!
