### ISSUE TITLE
Error when using TLSv1_method()

### ISSUE THREAD

**Issue by jacky-xi** [openssl/openssl#20344]
Hi,

when my client uses 'TLS_server_method' to connect server,everything is ok; but when my client uses 'TLSv1_method ( )‘ to connect server,there is error `40A7BDBC2A7F0000:error:0A000438:SSL routines:(unknown function):tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1586:SSL alert number 80`;

I know that 'TLSv1_method ( )‘ has been deprecated and I am using OpenSSL 3.0.3 ,but is there any way to connect server using deprecated function?

**Comment by jacky-xi** [comment]
And the server is using 'TLS_server_method'  which I know client should using 'TLS_client_method'  to correspond , but for some historical reasons, the client have to keep using this deprecated function.  : (

**Comment by mattcaswell** [comment]
The error that you are receiving means that the server has rejected the connection attempt. Most likely this is because the server does not support the TLSv1 protocol version (although the "internal error" alert it is sending is a little strange). Conversely when using `TLS_server_method()` the client and server are able to negotiate a mutually acceptable protocol version and the connection succeeds. If the server doesn't support TLSv1 then using `TLSv1_method()` will never work (deprecated or not).

**Comment by jacky-xi** [comment]
Thanks for answering, but how can I figure out if my server support TLSv1 or not ?

**Comment by mattcaswell** [comment]
> Thanks for answering, but how can I figure out if my server support TLSv1 or not ?

A client can only know by attempting to connect to it with TLSv1 and see if it works. This is why "TLSv1_client_method()" is deprecated. It only knows how to talk TLSv1 and will fail if the server doesn't support it. "TLS_client_method()" is able to negotiate a mutually supported protocol version.

**Comment by jacky-xi** [comment]
So after the server upgrades to openssl3.0, the old client which is still using "TLSv1_method()" won't be able to connect to the server unless it upgrades?

**Comment by mattcaswell** [comment]
OpenSSL 3.0 supports TLSv1 but not by default. So the server can be configured to support it, but the server admin might not want to do that. Clients should seek to move off of TLSv1 where possible. The IETF have officially deprecated TLSv1 and TLSv1.1 (see RFC 8996).

**Comment by jacky-xi** [comment]
How can I configured the server to support TLSv1? For some historical reasons I need the server to support it after upgrading.

**Comment by mattcaswell** [comment]
The security level of the server needs to be set to 0. How you do that depends on the server application using OpenSSL. If you were using `s_server` you could do it like this:

````
$ openssl s_server -cipher "DEFAULT:@SECLEVEL=0" -cert server.pem -key server.pem
````

**Comment by jacky-xi** [comment]
Thanks a lot and wish you all the best ! :)
