### ISSUE TITLE
The default provider documentation does not list the NULL cipher

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#20340]
This page is supposed to list the ciphers that are available in the default provider:

https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-default.html

Under the "Symmetric ciphers" section it should list the NULL cipher - but it does not. Similarly there is no "EVP_CIPHER-NULL" page to give an overview for the cipher, e.g. compare to "EVP_CIPHER-AES" here:

https://www.openssl.org/docs/man3.0/man7/EVP_CIPHER-AES.html

**Comment by paulidale** [comment]
Is a null cipher really a cipher?

**Comment by mattcaswell** [comment]
> Is a null cipher really a cipher?

Yes? There is a provider implementation for it.

**Comment by paulidale** [comment]
There is provider implementation of a test RNG, that doesn't mean it's an RNG.
The null cipher isn't a cipher IMO.

**Comment by mattcaswell** [comment]
> There is provider implementation of a test RNG, that doesn't mean it's an RNG.
The null cipher isn't a cipher IMO.

I disagree. IMO the NULL cipher is a cipher that can be fetched and acts like all other ciphers in this regards. It should be documented. We should similarly document the test RNG if we don't already.
