### ISSUE TITLE
EC_POINT_point2oct fils buf with garbage

### ISSUE THREAD

**Issue by efendizadeh** [openssl/openssl#2035]
I am trying to get octets from EC_POINT, however when i using EC_POINT_point2oct most time  (aprox. 5 of 10) I am getting garbage in buffer ("\x02")

EC_POINT_point2hex work perfectly.

Curve id is: NID_secp521r1
same behavior with NID_secp256k1

> size_t public_key_hex_size;
unsigned char* public_key_oct
BN_CTX *bn_ctx = BN_CTX_new();
public_key_oct = (unsigned char*)OPENSSL_malloc(public_key_hex_size);
public_key_hex_size =  EC_POINT_point2oct(ec_group, ec_point,POINT_CONVERSION_COMPRESSED,public_key_oct,public_key_hex_size,bn_ctx);

**Comment by t-j-h** [comment]
Do you initialise public_key_hex_size? Your code fragment here does not. - you are performing the malloc using an uninitialised variable as the argument.

**Comment by mattcaswell** [comment]
> EC_POINT_point2hex work perfectly.

Which is odd because EC_POINT_point2hex ultimately *calls* EC_POINT_point2oct().

````
size_t public_key_hex_size;
unsigned char* public_key_oct
BN_CTX bn_ctx = BN_CTX_new();
public_key_oct = (unsigned char)OPENSSL_malloc(public_key_hex_size);
public_key_hex_size = EC_POINT_point2oct(ec_group, ec_point,POINT_CONVERSION_COMPRESSED,public_key_oct,public_key_hex_size,bn_ctx);
````
Is that the code that you are running exactly as written? If so it doesn't look right. `public_key_hex_size` is uninitialised. Normally you might expect to call `EC_POINT_point2oct()` twice: the first time with a NULL buffer to get the size, and then a second time with a correctly sized buffer. Also there are no error checks in the above code. If EC_POINT_point2oct() returns 0 then an error has occurred.

**Comment by efendizadeh** [comment]
Ohh sorry for part of the code. Sure first of all i am getting size 

> public_key_hex_size =  EC_POINT_point2oct(ec_group, ec_point,POINT_CONVERSION_COMPRESSED,NULL,0,bn_ctx);

**Comment by efendizadeh** [comment]
Full code

 int generate_ecdsa_keys(char *public_key, char *private_key)
{

    EC_KEY *ec_key = NULL;
    EC_GROUP *ec_group = NULL;
    BN_CTX *bn_ctx = BN_CTX_new();

    const EC_POINT *ec_point;
    char* public_key_hex = NULL;
    const BIGNUM *bignum;
    char* private_key_hex = NULL;

    size_t public_key_hex_size;
    unsigned char* public_key_oct = NULL;

    int STATUS = 1;

    //START:
    if ( NULL == (ec_key = EC_KEY_new()) )
    {
        STATUS = -1;
        goto ERROR;
    }

    if ( NULL == (ec_group = EC_GROUP_new_by_curve_name(NID_secp521r1)) )
    {
        STATUS = -2;
        goto ERROR;
    }

    if ( 1 != EC_KEY_set_group(ec_key,ec_group) )
    {
        STATUS = -3;
        goto ERROR;
    }

    if( 1 != EC_KEY_generate_key(ec_key))
    {
        STATUS = -4;
        goto ERROR;
    }

    if (1 != EC_KEY_check_key(ec_key))
    {
        STATUS = -5;
        goto ERROR;
    }

    ec_point = EC_KEY_get0_public_key(ec_key);
    public_key_hex_size =  EC_POINT_point2oct(ec_group, ec_point,POINT_CONVERSION_COMPRESSED,NULL,0,bn_ctx);


    public_key_oct = (unsigned char*)OPENSSL_malloc(public_key_hex_size);
    public_key_hex_size =  EC_POINT_point2oct(ec_group, ec_point,POINT_CONVERSION_COMPRESSED,public_key_oct,public_key_hex_size,bn_ctx);


    public_key_hex = EC_POINT_point2hex(ec_group,ec_point,POINT_CONVERSION_COMPRESSED,bn_ctx);
    memcpy(public_key,public_key_hex,public_key_hex_size*2);

    bignum = EC_KEY_get0_private_key(ec_key);
    private_key_hex = BN_bn2hex(bignum);

    memcpy(private_key,private_key_hex,public_key_hex_size*2-2);

    ERROR:

    OPENSSL_free(public_key_oct);
    EC_KEY_free(ec_key);
    EC_GROUP_clear_free(ec_group);
    BN_CTX_free(bn_ctx);
    OPENSSL_free(public_key_hex);
    OPENSSL_free(private_key_hex);
    return STATUS;
}

**Comment by efendizadeh** [comment]
When EC_POINT_point2oct fills with garbage there are already have size (67)

**Comment by mattcaswell** [comment]
In that code you don't seem to actually be doing anything with `public_key_oct`? i.e. you get it and then just throw it away. So when you say it fills with garbage, what exactly do you mean...i.e. how do you know?

**Comment by efendizadeh** [comment]
Under debug:

![deb-1](https://cloud.githubusercontent.com/assets/7306284/20967162/03a37154-bc8f-11e6-81f7-6465edac6836.png)
![deb-2](https://cloud.githubusercontent.com/assets/7306284/20967163/055bc348-bc8f-11e6-8e7a-6f64ec0c36e2.png)

**Comment by efendizadeh** [comment]
Yea, I am trying to switch from hex to oct.

**Comment by mattcaswell** [comment]
So why do you think that result is garbage?

**Comment by efendizadeh** [comment]
1. Its not looks like data with long 67
2. within 10 times running code in for loop with different newly generated keys same public ? :)

**Comment by mattcaswell** [comment]
> Its not looks like data with long 67

You're only looking at the first byte. This is binary data...there are 66 following bytes that you're not looking at.

> within 10 times running code in for loop with different newly generated keys same public ? :)

The first byte of an EC_POINT indicates the point conversion form. With POINT_CONVERSION_COMPRESSED, the first byte will *always* be either 2 or 3.

**Comment by richsalz** [comment]
*oct* means octets, not *octal readable output.*

**Comment by efendizadeh** [comment]
Its ok. I am also looking for octets :)
Thank you very much. Now I am trying to test all my work. I will inform you ASAP.

**Comment by efendizadeh** [comment]
Thanks guys, it is working.
