### ISSUE TITLE
EVP_PKEY *pk is freed twice resulting in a dealloc error / bad access.

### ISSUE THREAD

**Issue by haniewais** [openssl/openssl#20355]
I have code that calls CMS_Decrypt(), passing in the EVP_PKEY as one of the parameters, which results in dealloc error when trying to free the the EVP_PKEY:

```
   bio = BIO_new(BIO_s_mem())
   privateKey = getEVPPKEY() // makes bio, makes key from pemString, free's bio. 
   
   CMS_decrypt(pkcs7, privateKey, cert, null, bio, 0)

   // cleanup
   EVP_PKEY_free(privateKey)
   BIO_free(bio)   
```
After talking a look at the code, it seems that CMS_decrypt() passes the EVP_PKEY down the chain:

> https://github.com/openssl/openssl/blob/4596c20b86871b2bb0f9a7f6b855c0b7f0d4fbf3/crypto/cms/cms_smime.c#L859

Calls CMS_decrypt_set1_pkey(cms, pk, cert)) 

> https://github.com/openssl/openssl/blob/4596c20b86871b2bb0f9a7f6b855c0b7f0d4fbf3/crypto/cms/cms_smime.c#L879

CMS_decrypt_set1_pkey() then calls CMS_decrypt_set1_pkey_and_peer() 

> https://github.com/openssl/openssl/blob/4596c20b86871b2bb0f9a7f6b855c0b7f0d4fbf3/crypto/cms/cms_smime.c#L700

In CMS_decrypt_set1_pkey_and_peer(),
On line 745, the EVP_PKEY references is upped by one, (now we have ref count = 2)

> https://github.com/openssl/openssl/blob/4596c20b86871b2bb0f9a7f6b855c0b7f0d4fbf3/crypto/cms/cms_smime.c#L744-L749

Then the CMS_RecipientInfo_set0_pkey() function is called the fist time on 746 and frees the EVP_PKEY on line 487, which sets the reference counter form 2 down to 1.
> https://github.com/openssl/openssl/blob/c3aed7e4e6f1960eaa43ecbea2178b82481887af/crypto/cms/cms_env.c#L481-L490

Then back in CMS_decrypt_set1_pkey_and_peer() on line 748, we call the same function again, CMS_RecipientInfo_set0_pkey(), freeing the EVP_PKEY again and now the reference count is zero. 

Exiting CMS_decrypt() and back to my code, the EVP_PKEY has been freed and I get a bad access / dealloc error. 
Is this by design? 
Does the CMS_decrypt free the EVP_PKEY? 
This feels like unintended behavior.

**Comment by slontis** [comment]
@DDvO - this is fixed I assume?

**Comment by mattcaswell** [comment]
> Then the CMS_RecipientInfo_set0_pkey() function is called the fist time on 746 and frees the EVP_PKEY on line 487, which sets the reference counter form 2 down to 1.

Lines 487 and 488 in `CMS_RecipientInfo_set0_pkey` mean that any *existing* pkey is freed from the recipient info, and it is replaced with the new pkey. If the `EVP_PKEY_free(ri->d.ktri->pkey)` call on 487 is actually doing something, and decrementing the ref counter for the same pkey that you are adding, then this means that the pkey being added is already present in the recipient info. If that's the case then we would have expected the pkey to have 2 refs to it when you called `CMS_decrypt`, i.e. one ref for your application, and one ref for the recipient info.

So - how did the pkey get into the recipient info?

**Comment by DDvO** [comment]
> I have code that calls CMS_decrypt(), passing in the EVP_PKEY as one of the parameters, which results in dealloc error when trying to free the the EVP_PKEY:

Which exact version/commit ID of OpenSSL are you using?

The code snippet you provide appears to match nicely with `test_encrypt_decrypt()` in `test/cmsapitest.c`, which works fine. So I see little chance for reproducing the issue unless you provide a complete example.
