### ISSUE TITLE
Optimization for Miller Rabin < 2^81

### ISSUE THREAD

**Issue by maroonbells** [openssl/openssl#20358]
edited after post: correction of range variables through 2^81 instead of just 2^64

My reading of the code which calls Miller-Rabin, is that - after a trial division against the smallest primes - it then does 64 M/R rounds with random witnesses against all numbers of 512 bits and smaller.

However, something mentioned at the Wikipedia page for M/R, and is something that I don't see the OpenSSL code doing, is that odd numbers as large as 2^81 can be deterministically proven as prime vs composite with as few as 12 specific witnesses, and there are ranges of numbers below that which can be 100% proven with many fewer witnesses than that.

Wikipedia lists many ranges having the same witness count, so it's probably just as fast to branch only for the largest range at each witness count:

if (n < 3,317,044,064,679,887,385,961,981) {
if      n < 2,047, 1 witness a = 2;
else if n < 9,080,191, 2 witnesses a = 31 and 73;
else if n < 4,759,123,141, 3 witnesses a = 2, 7, and 61;
else if n < 1,122,004,669,633, 4 witnesses a = 2, 13, 23, and 1662803;
else if n < 2,152,302,898,747, 5 witnesses a = 2, 3, 5, 7, and 11;
else if n < 3,474,749,660,383, 6 witnesses a = 2, 3, 5, 7, 11, and 13;
else if n < 341,550,071,728,321, 7 witnesses a = 2, 3, 5, 7, 11, 13, and 17.
else if n < 3,825,123,056,546,413,051, 9 witnesses a = 2, 3, 5, 7, 11, 13, 17, 19, and 23.
else if n < 318,665,857,834,031,151,167,461, 12 witnesses a = 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, and 37.
else if n < 3,317,044,064,679,887,385,961,981, 13 witnesses a = 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, and 41.
}
else {
   normal call with 64 witnesses
}

Even though this optimization can allow results that are proven prime, not merely probable, I assume it would break fuctionality to change the return code to reflect that.

The existing code does not appear to check whether it's calling the same witnesses again, but the chance of that is extremely small, and is even less likely if the above optimization eliminates random witnesses being used in the smaller ranges.

**Comment by slontis** [comment]
There is some FIPS related code for RSA that uses ossl_bn_check_generated_prime() internally. This passes a parameter for the number of checks depending on the bitsize.

**Comment by paulidale** [comment]
Primes <2⁶⁴ is pretty small in a cryptographic context.  Even 2⁸¹ is too small for a cryptographicly useful prime.

So, while the optimistaion makes sense in a general purpose long integer mathematics library, it's not particularly relevant for cryptography.

One could argue that OpenSSL's bignum code is a general purpose mathematics library & it certainly has been used as such.  However, changes to introduce things like blinding and timing resistance are detrimental for general purpose use but critical for cryptographic use.

We'd consider a pull request introducing this change, but honestly it's never going to be a high priority item for the project team.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
