### ISSUE TITLE
Wrong Method call in X509_check_akid

### ISSUE THREAD

**Issue by meins111** [openssl/openssl#20367]
I am currently debugging why openssl rejects a certificate chain and I think in the Certificate Chain verification sub-method `X509_check_akid`, a wrong method is called, causing a verify failure in case of certificates using the authority key identifier extension.

Here the method for convenience of discussion:
```C
int X509_check_akid(const X509 *issuer, const AUTHORITY_KEYID *akid)
{
    if (akid == NULL)
        return X509_V_OK;
    /* Check key ids (if present) */
    if (akid->keyid && issuer->skid &&
        ASN1_OCTET_STRING_cmp(akid->keyid, issuer->skid))
        return X509_V_ERR_AKID_SKID_MISMATCH;
    /* Check serial number */
    if (akid->serial &&
        ASN1_INTEGER_cmp(X509_get0_serialNumber(issuer), akid->serial))
        return X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH;
    /* Check issuer name */
    if (akid->issuer) {
        /*
         * Ugh, for some peculiar reason AKID includes SEQUENCE OF
         * GeneralName. So look for a DirName. There may be more than one but
         * we only take any notice of the first.
         */
        GENERAL_NAMES *gens = akid->issuer;
        GENERAL_NAME *gen;
        X509_NAME *nm = NULL;
        int i;

        for (i = 0; i < sk_GENERAL_NAME_num(gens); i++) {
            gen = sk_GENERAL_NAME_value(gens, i);
            if (gen->type == GEN_DIRNAME) {
                nm = gen->d.dirn;
                break;
            }
        }
        if (nm != NULL && X509_NAME_cmp(nm, X509_get_issuer_name(issuer)) != 0)
            return X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH;
    }
    return X509_V_OK;
}
```

This is called by the greater verify logic for a chain element A, when considering a certificate B to be the issuer certificate of A.
So lets consider a chain like this: `A <---issued_by---- B <---issued_by--- C`

The above method is thus called with issuer set to B and akid set to the authority_key_id extension carried by A.
Fast forward to the last if statement.
nm now is the x509_name as given by akid->issuer (aka the name part of the authority_key_information extension).
As I understand the **intention** of the last check: compare nm and the name of the issuer, as they should match.

But what **actually** happens is a comparison between nm and the issuer_name of issuer.
So, the check will compare: akid to B.issuer (aka C) where it should be comparing akid to B.subject - which will obiously fail unless B is a root/self-signed certificate, where issuer==subject.

So, I guess that last if should actually read:
```C
        if (nm != NULL && X509_NAME_cmp(nm, X509_get_subject_name(issuer)) != 0)
```

**Comment by meins111** [comment]
A local debug build using the `X509_get_subject_name` method did indeed verify my certificate chain correctly.
I also tested the chain using the BouncyCastle library and it was verified as ok.

**Comment by Vinz2008** [comment]
When replacing X509_get_issuer_name by X509_get_subject_name, 3 tests fail. In these tests, there are errors where openssl can't get the local issuer certificate.  So you probably need to verify some cases to make it work (probably verify if it is using the authority key identifier extension and use X509_get_subject_name only in this case or something like that)

**Comment by meins111** [comment]
Well that last if is only ever reached in case ```C 
akid != NULL
```
So that is probably not the issue. But I'll look into the failed tests Monday and probably put a PR together then.

**Comment by meins111** [comment]
Alright, so the tests which do fail are all testing proxy certificates, which do in fact by their nature, have a "wrong" subject name compared to the CA name carried by the akid of the leaf certificate...

**Comment by meins111** [comment]
Hmmm, so we could of course just work with an OR there, so either subject or issuer name must match the akid->issuer.

That would be a quick fix and not completely "right" afaict.

The proper way would require to determine whether issuer is a proxy (then check for issuer name) or not (then check for subject name).

Thoughts?

**Comment by meins111** [comment]
@Vinz2008 : so, I've read a bit into RFC 4158 (regarding chain building) ...
and it seems the entire akid matching step of path building isn't actually supposed to eliminate an issuer cert from the list of candidates, just "lower its weight". 
Afaict from the code, openssl currently uses akid matching as just another elimination criteria within the `X509_check_issued` method.

[Relevant RFC section](https://www.rfc-editor.org/rfc/rfc4158#section-3.5.12):
> NOTE:  Although required to be present by [[RFC3280](https://www.rfc-editor.org/rfc/rfc3280)], it is extremely
   important that KIDs be used only as sorting criteria or as hints
   during certification path building.  KIDs are not required to match
   during certification path validation and cannot be used to eliminate
   certificates.  This is of critical importance for interoperating
   across domains and multi-vendor implementations where the KIDs may
   not be calculated in the same fashion.

Which does throw up more questions that it answers unfortunately.

**Comment by t8m** [comment]
The last check is correct - issuer name of the issuer should be compared as the serial+issuer name is what uniquely identifies a certificate and not serial + subject.  So your CA provides wrong issuer in AKID of the issued certificate.

However it is true that this check should be rather a hint and not absolute requirement on the chain validation. I.e. if I am able to build a chain that satisfies this check, all is good, but if not, I should still be allowed to use a chain that does not satisfy it.

The problem is that that would require very invasive changes of the certificate chain building code. One option would be to simply skip the issuer/serial AKID check if there is akid->keyid && issuer->skid as that hint should be sufficient to build the proper chain.

**Comment by meins111** [comment]
Thanks for taking the time to answer and explain.
