### ISSUE TITLE
Issue with 'ssl/quic/quic_reactor.c'

### ISSUE THREAD

**Issue by gvanem** [openssl/openssl#20368]
The file `ssl/quic/quic_reactor.c` does not compile on MSVC for these reasons:
* The code tests on the ancient `OSSL_SYS_WINDOWS` define. And not `OPENSSL_SYS_WINDOWS`.
 * Winsock2 does not have `poll()`. But `WSAPoll()`.

Compile warning: `warning C4013: 'poll' undefined; assuming extern returning int`
Link error: `error LNK2019: unresolved external symbol poll referenced in function poll_two_descriptors`

So, applying this patch, it compiles and links:
```diff
--- a/ssl/quic/quic_reactor.c 2023-02-17 20:40:03
+++ b/ssl/quic/quic_reactor.c 2023-02-18 15:12:35
@@ -126,13 +126,13 @@
                         int wfd, int wfd_want_write,
                         OSSL_TIME deadline)
 {
-#if defined(OSSL_SYS_WINDOWS) || !defined(POLLIN)
+#if defined(OPENSSL_SYS_WINDOWS) || !defined(POLLIN)
     fd_set rfd_set, wfd_set, efd_set;
     OSSL_TIME now, timeout;
     struct timeval tv, *ptv;
     int maxfd, pres;

-# ifndef OSSL_SYS_WINDOWS
+# ifndef OPENSSL_SYS_WINDOWS
     /*
      * On Windows there is no relevant limit to the magnitude of a fd value (see
      * above). On *NIX the fd_set uses a bitmap and we must check the limit.
@@ -225,7 +225,11 @@
             timeout_ms  = ossl_time2ms(timeout);
         }

+#if defined(OPENSSL_SYS_WINDOWS)
+        pres = WSAPoll(pfds, npfd, timeout_ms);
+#else
         pres = poll(pfds, npfd, timeout_ms);
+#endif
     } while (pres == -1 && get_last_socket_error_is_eintr());

     return pres < 0 ? 0 : 1;
```

But the comment in this file indicates a `enable-quic` could be used on Win-XP :
> WSAPoll() was introduced in Vista but has seemingly been buggy until relatively recent
>  versions of Windows 10. Moreover we support XP so this is not a suitable
>  target anyway. 

I doubt it.

But I failed to find a test-case for the above patch.

**Comment by mattcaswell** [comment]
PR #20348 contains fixes for at least the OSSL_SYS_WINDOWS part of this.

@hlandau?

**Comment by mattcaswell** [comment]
The change in your patch for WSAPoll seems redundant since with the OSSL_SYS_WINDOWS fix in place we won't hit that code on Windows (we'll use the alternative windows implementation instead).

**Comment by gvanem** [comment]
You're right. Brain-fart. How about:
```diff
--- a/ssl/quic/quic_reactor.c 2023-02-17 20:40:03
+++ b/ssl/quic/quic_reactor.c 2023-02-24 09:47:20
@@ -126,13 +126,13 @@
                         int wfd, int wfd_want_write,
                         OSSL_TIME deadline)
 {
-#if defined(OSSL_SYS_WINDOWS) || !defined(POLLIN)
+#if !defined(POLLIN)  /* poll() / WSAPoll() not available */
     fd_set rfd_set, wfd_set, efd_set;
     OSSL_TIME now, timeout;
     struct timeval tv, *ptv;
     int maxfd, pres;
```

And/or some `OPENSSL_NO_WSAPOLL` to support Win-XP?

**Comment by hlandau** [comment]
I don't intend to use WSAPoll at this time as it's known to have issues on older Windows and in any case we need to support XP.

The bug here is in testing the wrong define, which is fixed in my thread assist PR. Unfortunate that this wasn't caught by CI.

Rather than testing POLLIN simply test for `OPENSSL_SYS_WINDOWS` rather than `OSSL_SYS_WINDOWS`. Testing for POLLIN won't work correctly as we do not support WSAPoll. You can of course just wait for the TA PR to merge, though if you need this fixed urgently in master porting the applicable one-line change in the TA PR as a separate PR would probably get approved faster.

**Comment by t8m** [comment]
These issues are already fixed. Closing.
