### ISSUE TITLE
SSL_read fails with SSL_ERROR_SSL for non-blocking socket

### ISSUE THREAD

**Issue by Beosar** [openssl/openssl#20365]
I wrote a server that is using OpenSSL 3.0.7 (built myself on Windows) and 3.0.2 on Ubuntu 22.04 (system-provided).

When I added error handling, I ran into a bug that I cannot explain. It happens on both OS's.

For the first connection, it works (sometimes), but every client that connects after the first connection is closed will trigger SSL_ERROR_SSL when the socket has no data to read.

I do something like this (irrelevant error handling removed for better readability since there are no errors in those parts):

```
SOCKET ClientSocket = accept(Socket, NULL, NULL);
setsockopt(ClientSocket, IPPROTO_TCP, TCP_NODELAY, &value, sizeof(value));
SetSocketBlocking(ClientSocket, false); //set non-blocking
char value = 1;
setsockopt(ClientSocket, IPPROTO_TCP, TCP_NODELAY, &value, sizeof(value));
SSL* ssl = SSL_new(ctx);

```

This is being executed on a different thread right after:
```
SSL_set_fd(ssl, (int)ClientSocket);   
while(SSL_accept(ssl) != 1); 
```

On another different thread (looped) after previous operations are completed, called approximately every 1 second or earlier when data is available to read (using poll):
```
data_length = SSL_read(ssl, (char*)buffer, PendingBytes);
if (data_length <= 0) {
  HandleSSLError(SSL_get_error(ssl, data_length));			
  return false;
}
```

I also use SSL_write somewhere but the error happens before I call it.

This is the HandleSSLError function with my workaround. This should not work because SSL_ERROR_SSL is non-recoverable. But it does work without any issues whatsoever.

```
inline void HandleSSLError(const int SSLError){
  if(SSLError != SSL_ERROR_WANT_READ && SSLError != SSL_ERROR_WANT_WRITE && SSLError != SSL_ERROR_NONE){
    if (SSLError == SSL_ERROR_ZERO_RETURN) {
      ConnectionError = EConnectionError::ClosedRead;
    }
    else {
      if (SSLError == SSL_ERROR_SSL) { //workaround
        const auto Error = WSAGetLastError();
        if (Error == WSAEWOULDBLOCK) {
          std::array<char, 1024> Buffer = { 0 };
          ERR_error_string_n(ERR_get_error(), Buffer.data(), Buffer.size());
          std::cout << Buffer.data() << std::endl;
          return;
        }
      }
      ConnectionError = EConnectionError::ForceClose;
    }
  }
}
```

I feel like the error should be SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE.

The error message is: _error:0A000126:SSL routines::unexpected eof while reading_

Edit: I "fixed" it using ``SSL_CTX_set_options(ctx, SSL_OP_IGNORE_UNEXPECTED_EOF);`` but that leaves me vulnerable to truncation attacks. Well, they would not work for other reasons, but I would still not consider this a fix.

Edit 2: I've now gone through the relevant OpenSSL source code. If I understand it correctly, it uses a socket BIO, which correctly handles the WSA error code and must get the same as my code (WSAEWOULDBLOCK). But for some reason, it doesn't seem to set the flags for retry in the BIO, which causes an unexpected EOF error. But that is impossible unless for some reason it tries to read zero bytes. However, I do not attempt to read zero bytes (actually 1 byte), so it must be an internal error.

**Comment by mattcaswell** [comment]
> The error message is: error:0A000126:SSL routines::unexpected eof while reading

This means that the client abruptly terminated the connection without closing down gracefully. You should look into why the client is doing so - but in any case your server will need to be able to handle impolite clients like this. It is actually quite common for clients to close like this if they don't like the connection for some reason.

It might be worth capturing a pcap trace of the communication. Sometimes this reveals the cause of such failures.

> SSL_set_fd(ssl, (int)ClientSocket);   
while(SSL_accept(ssl) != 1); 

As an aside you probably also be calling SSL_get_error() here too and handle responses accordingly - an `SSL_ERROR_SSL` could occur at this point if the handshake fails and you could end up in an infinite loop.

**Comment by Beosar** [comment]
> This means that the client abruptly terminated the connection without closing down gracefully.

I am certain that it does not do that when the error occurs. Otherwise I could not ignore the error and continue as if nothing happened.

> As an aside you probably also be calling SSL_get_error() here too

I removed the error handling for this post for better readability because it was irrelevant, that part of the code does not fail in this case. The TLS handshake is performed and a single packet arrives at the server. Subsequent calls to SSL_read when there is no data available yet will trigger this error.

I do not understand how this could happen and why not on the very first connection. I restarted the client application, so it can't be that.

I just realized that I don't clear the error queue, so it could be an old error, actually. But that would not explain why I get SSL_ERROR_SSL.

**Comment by mattcaswell** [comment]
> I just realized that I don't clear the error queue, so it could be an old error, actually. But that would not explain why I get SSL_ERROR_SSL

`SSL_get_error()` does this:

```` C
    if ((l = ERR_peek_error()) != 0) {
        if (ERR_GET_LIB(l) == ERR_LIB_SYS)
            return SSL_ERROR_SYSCALL;
        else
            return SSL_ERROR_SSL;
    }
````
So, any stale error on the error queue results in `SSL_ERROR_SSL` (unless it happens to be a SYS error).

Plausibly you've got a previous connection finishing with an unexpected EOF, and that error is remaining on the error queue affecting the next connection.

**Comment by Beosar** [comment]
> Plausibly you've got a previous connection finishing with an unexpected EOF, and that error is remaining on the error queue affecting the next connection.

Oh my god, I missed that entirely, somehow. It even states in the documentation that the error queue must be empty.

Well, it is not the most intuitive library, you really need to take your time to read the documentation and I don't have much of that.

I think that should solve the issue. Thank you so much.
