### ISSUE TITLE
Dynamic provider test

### ISSUE THREAD

**Issue by silabs-PeterK** [openssl/openssl#20370]
Hello, how can I run all OpenSSL tests with the custom dynamic provider or can you please point me to the place where tests load the default provider, so I can modify it and run tests that way? Or is there a full test for external providers? 

Thanks,
Peter

**Comment by paulidale** [comment]
Most tests could be done via configuration to load your provider.  Set the `OPENSSL_CONF` environment variable to point to the configuration file.  You might want to set the default property query to prefer loading your provider using the `default_properties` setting.  Something like: `default_properties=?provider=<your provider>` or similar.

There are some tests that force the use of a specific configuration file.  These use files `test/*.cnf` and you'd also need to update these to include your provider as appropriate.  I suspect that some/most of these wouldn't be relevant but a lot would depend on your specific use case.

**Comment by silabs-PeterK** [comment]
setting OPENSSL_CONF doesn't seem to work for me. Let's say I want to test my implementation of sha256. I want to use sha_test.c for that. I set the OPENSSL_CONF to file where I disabled the default provider and enabled mine. But my provider load is never called if I run `make TESTS="test_sha" test`.  But I cannot track any calls to OSSL_PROVIDER_load or test_get_libctx from run_tests in driver.c. Where is the provider loaded for test_sha?

**Comment by mattcaswell** [comment]
> And I cannot track any calls to OSSL_PROVIDER_load or test_get_libctx from run_tests in driver.c. Where is the provider loaded for test_sha?

It's loaded implicitly. If you don't load any other provider explicitly then the default provider will be loaded automatically by libcrypto. So there is no explicit call to `OSSL_PROVIDER_load`.

You would have to run that test directly in order to be able override OPENSSL_CONF, e.g.

```` bash
cd test
OPENSSL_CONF=/path/to/myprovider.cnf ../util/shlib_wrap.sh ./sha_test
````
Unfortunately you can't override OPENSSL_CONF and just run `make test` because the test framework explicitly sets it.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
