### ISSUE TITLE
early_data and CCM ciphersuite (openssl 3.0.5)

### ISSUE THREAD

**Issue by vitalyk-radware** [openssl/openssl#20377]
i get an error 
```
00171B7AA27F0000:error:1C800066:Provider routines:(unknown function):cipher operation failed:providers/implementations/ciphers/ciphercommon_ccm.c:278:
```
in the following case:

server:
```
openssl s_server  -key ../conf/keys/server.pem    -cert ../conf/keys/server.pem  -port 7887 -recv_max_early_data  88888  -early_data  -tls1_3  -ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
```
client:
```
openssl s_client -connect 127.0.0.1:7887 -tls1_3 -sess_out ../tmp/sess -ciphersuites TLS_AES_128_CCM_SHA256
openssl s_client -connect 127.0.0.1:7887 -tls1_3 -sess_in ../tmp/sess -ciphersuites TLS_AES_128_CCM_SHA256 -early_data ../tmp/EARLY_DATA
openssl s_client -connect 127.0.0.1:7887 -tls1_3 -sess_in ../tmp/sess -ciphersuites TLS_AES_128_CCM_SHA256 -early_data ../tmp/EARLY_DATA
```
[tmp.zip](https://github.com/openssl/openssl/files/10832555/tmp.zip)

on the second reuse of a session with early data, i get this error on server when connection is closed.
it happens only with CCM ciphers, but does not happen with GCM.
it only happens when there is early_data.

with openssl 1.1.1 it worked fine.
please help. thank you.

**Comment by mattcaswell** [comment]
This is an OpenSSL bug. It seems we are leaving a spurious error on the error queue in the event that early data decryption fails (which is a normal event). Investigating further...

**Comment by mattcaswell** [comment]
3.1/3.0 backport of this in #20442
