### ISSUE TITLE
Clarification about "non-FIPS validated algorithms" in FIPS provider

### ISSUE THREAD

**Issue by jjeffroberts** [openssl/openssl#20376]
In this document:

https://www.openssl.org/docs/manmaster/man7/OSSL_PROVIDER-FIPS.html

Near the top, for 3.0, it says this:

> Properties
> 
> The implementations in this provider specifically have these properties defined:
> 
> "provider=fips"
> "fips=yes"
> 
> It may be used in a property query string with fetching functions such as [EVP_MD_fetch(3)](https://www.openssl.org/docs/manmaster/man3/EVP_MD_fetch.html) or [EVP_CIPHER_fetch(3)](https://www.openssl.org/docs/manmaster/man3/EVP_CIPHER_fetch.html), as well as with other functions that take a property query string, such as [EVP_PKEY_CTX_new_from_name(3)](https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_CTX_new_from_name.html).

> **It isn't mandatory** to query for any of these properties, except to make sure to get implementations of this provider and none other.

But in the **NOTES** section at the bottom, for 3.1, it says:

> The FIPS provider in OpenSSL 3.1 includes some non-FIPS validated algorithms, consequently the property query fips=yes **is mandatory** for applications that want to operate in a FIPS approved manner. The algorithms are:
> 
> Triple DES ECB
> Triple DES CBC
> EdDSA

1. Is the need for fips=yes only if you are using one of those three algorithms? 
2. Is there more discussion somewhere of this move that seems to affect the "purity" of the FIPS module?

I'm currently upgrading a bunch of repos to 3.0 but if this is going to be necessary in 3.1 it may change my approach.

**Comment by paulidale** [comment]
You are looking a the wrong manual page :grinning:  The only validated FIPS provider is the 3.0.0 one and the [relevant manual page](https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-FIPS.html) doesn't include this note.

When the OpenSSL 3.1 FIPS provider is validated (& you want to use it), you will need to include `fips=yes` as part of **all** FIPS relevant property queries.  The easiest way is to set default properties on the library context using [EVP_set_default_properties](https://www.openssl.org/docs/man3.0/man3/EVP_set_default_properties.html) but it can be done in other ways.

For the 3.0 FIPS provider, the situation is more complex.  Currently those three algorithms are permitted in FIPS mode.  A security policy update has been submitted to NIST and once it is approved, EdDSA will no longer be permitted in FIPS mode.  The triple DES algorithms transition away at the end of this year and once that happens they too will be forbidden.

The purity of the module was never going to last.  NIST imposes [transitions](https://csrc.nist.gov/publications/detail/sp/800-131a/rev-2/final) on FIPS modules which deprecate and then ban individual algorithms.  This is what is causing triple DES to become non-FIPS approved.  EdDSA is a different story, my limited understanding is that NIST changed their mind about allowing these algorithms in FIPS modules until a number of standards etc are finalised.
