### ISSUE TITLE
Creation of a PKCS7 object with a precomputed digital signature, privateKey in external device.

### ISSUE THREAD

**Issue by Andrei-Popilian** [openssl/openssl#20388]
Hi, I am using the OpenSSL ported library in an iOS project ,Swift.
OpenSSL version: **1.1.1t**

I am trying to generate a **PKCS7** object using the implemented macros in the library, to digitally sign a PDF file. 
However I don't have access to the private key as it is stored in the secure enclave of the phone, I precomputed the digital signature on the phone and I was looking into creating the **PKCS7** with a precomputed digital signature as I do have all the other details needed, public key, hash and signing algorithms.

By reading the OpenSSL documentation I understood the private key can be set to null in some cases, but while checking the C code, I saw that is required when using the `PKCS7_sign`.
Documentation: -> https://www.openssl.org/docs/man1.0.2/man3/PKCS7_sign.html

Am I missing the correct implementation/documentation? or there is no current support for creating a PKCS7 with a precomputed digital signature while using OpenSSL?

Thank you.

**Comment by beldmit** [comment]
In a real world you have to implement an engine (for 1.1.1) or a provider that will be able to get a signature using a custom method.

**Comment by DemiMarie** [comment]
@beldmit I think what @Andrei-Popilian wants is to be able to wrap an _existing_ signature in PKCS7.

**Comment by beldmit** [comment]
Yes, but I strongly doubt it's easily doable

**Comment by DemiMarie** [comment]
@Andrei-Popilian one other option would be to do the ASN.1 serialization manually.

**Comment by Andrei-Popilian** [comment]
Thank you @DemiMarie and @beldmit, I will check both,  I think the ASN.1 serialization might be simpler due to my lack of experience in the cryptographic world.

Thanks.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
