### ISSUE TITLE
test code in the production path when built with enable-fips 

### ISSUE THREAD

**Issue by rcarpa** [openssl/openssl#20389]
Hi team, 
I'm investigating right now an issue with an internal program which started to consume an order of magnitude more CPU when migrated from Centos 7 to AlmaLinux 9. 

I was surprised to see this output in `perf report` when I managed to isolate the offending operation:
![image](https://user-images.githubusercontent.com/2905943/221622373-26a602a1-e317-4b78-af39-cebf3b6aa482.png)

Checking the openssl source code, it seems like `get_entropy` has a special code path when FIPS is enabled (the RHEL9 RPM is, indeed, built with `enable-fips`):  https://github.com/openssl/openssl/blob/master/providers/implementations/rands/drbg.c#L201 

And that code path uses multiple test-related functions in the production code path since https://github.com/openssl/openssl/commit/7f9e74403677a995ded00f070d84297401f6e3fd

Did I correctly evaluate the issue, or am I missing something? 

Regards,
Radu

**Comment by paulidale** [comment]
The FIPS 140 standards mandate some testing of the entropy source, that's what you've pointed at.  It's normal and expected.

The FIPS installation process also does some failure testing but this should only happen once.  I wouldn't expect to see the failure testing code executing in normal operation.  Moreover, `OSSL_SELF_TEST_oncorrupt_byte()` should be extremely lightweight and isn't according to your trace.  Something odd is going on here.  I'd suggest build with debug symbols so you get a better trace...

**Comment by rcarpa** [comment]
Thank you for orienting me on the correct path. With debug symbols active, it becomes clear that the time is actually spent in `sa_doall`.  `OSSL_SELF_TEST_oncorrupt_byte` is located just before `sa_doall` in memory in the Alma9 binary, so perf picked and showed the incorrect symbol. Compiling with -O0, revealed that most time is spent in `X509_load_cert_crl_file_ex`, which gives me a very good lead for investigating the increased CPU consumption.

Sorry for the noise. I'm closing the issue.
