### ISSUE TITLE
use of SEED algorithm(TLS 1) in openssl 3.0.5

### ISSUE THREAD

**Issue by vitalyk-radware** [openssl/openssl#20393]
I try to use SEED algorithm

I use client  1.0.1 :
```
openssl s_client -connect 127.0.0.1:7777 -cipher SEED-SHA -tls1
```
I use server v 3.0.5:
``` 
./apps/openssl s_server -port 7777 -www -key server.pem -cert server.pem  -tls1   -provider-path providers/ -provider legacy -provider default -cipher SEED-SHA
```
the server has been configured this way:
```
./config enable-weak-ssl-ciphers enable-ssl3 enable-ssl3-method no-shared  no-zlib no-comp  enable-rc4 enable-seed enable-tls1_1 enable-tls1 enable-tls1_2 enable-tls1
```
i get this error when try to connect:

00E775D3A67F0000:error:0A000076:SSL routines:(unknown function):no suitable signature algorithm:ssl/t1_lib.c:3337:

what i am doing wrong? please advise...
thank you!

**Comment by paulidale** [comment]
You need to set the security level for TLS to zero.  This can be done as part of the cipher list as described in the [documentation](https://www.openssl.org/docs/manmaster/man1/openssl-ciphers.html#CIPHER-LIST-FORMAT).

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
