### ISSUE TITLE
[OpenSSL 3] Will ENGINE API be removed completely in the future?

### ISSUE THREAD

**Issue by ShuaiYuan21** [openssl/openssl#20395]
Hi, as the official notified, OpenSSL 1.1.1 will stop maintenance in September this year, and encourages users to migrate to OpenSSL 3.0 as soon as possible. 

At the same time, all API related to ENGINE have been marked with "deprecated" in OpenSSL 3.0, but as for whether the support of ENGINE will be removed entirely in the future, I still can't find any relevant information. 

Therefore, I want to know if the ENGINE API will be removed completely in the future of not? In other words, only the PROVIDER framework is supported.

Thanks!

**Comment by paulidale** [comment]
The intention is to eventually remove engines completely.  It won't happen before OpenSSL 4.0.
