### ISSUE TITLE
how to generate rsa key file using c on openssl3.0

### ISSUE THREAD

**Issue by xengine-qyt** [openssl/openssl#20397]
PEM_read_bio_RSAPrivateKey and PEM_write_bio_RSAPrivateKey api does not work on 3.0

how to write and read rsa key file, can't found example.

**Comment by slontis** [comment]
Debugging the code used by the commandline utils for genpkey.c and pkey.c should give you some guidance...
````
>../apps/openssl genpkey -algorithm rsa -out rsa.pem
>../apps/openssl pkey -in rsa.pem -text
````
