### ISSUE TITLE
Generate a CSR with Hardware Backed Keys (attestation keys)

### ISSUE THREAD

**Issue by BilalAkmal47** [openssl/openssl#20400]
I was searching for OpenSSL way to create CSR with secure key pair stored in Secure Module of hardware. Like we have TPM in windows, android have (StrongBox, TEE etc.). Those modules generate public private keys and only share the public key and attestation key/certificate. Whereas Private key is never shared.

Is there a way to create a CSR with such securely stored keys?
The [documentation to generate keys](https://www.openssl.org/docs/man3.0/man1/openssl-genpkey.html) and the [documentation to req CSR](https://www.openssl.org/docs/man1.0.2/man1/openssl-req.html) does not address such use case. 

Below are the commands I am using right now, that I am sure they are not using any secure hardware module to generate keys.

- Generate Keys
`openssl genpkey -genparam -algorithm ec -pkeyopt ec_paramgen_curve:P-256 -out ECPARAM.pem`

- CSR
`openssl req -newkey ec:ECPARAM.pem -keyout PRIVATEKEY.key -out ReqCSR.csr`

Please let me know if I am missing something?

**Comment by paulidale** [comment]
OpenSSL does not support secure hardware modules directly.  You need either an engine or a provider that supports the module you are using and then you need to tell OpenSSL to use it.  Manufacturers sometimes produce these as do third parties.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
