### ISSUE TITLE
Ed25519 EVP Support

### ISSUE THREAD

**Issue by salehelmaraghy** [openssl/openssl#20418]
I looks like the Ed25519 EVP is now supported in this [commit  ](https://github.com/openssl/openssl/commit/836080a89a1f5e45dac4e0df76b9270587f65d5b) 

My question is this commit is merged in which openssl version?

**Comment by kroeckx** [comment]
Note that Ed25519 was already supported, it's just the Ed25519ctx, Ed25519ph variants that are now also supported.

That commit is only part of the master branch, and is not in any release.

Ed25519 is supported since 1.1.1.

**Comment by slontis** [comment]
Note also that ED25519 and X25519 (as 448) are also not currently approved for FIPS mode.

**Comment by paulidale** [comment]
My understanding is that X25519 is permitted whereas Ed25519 isn't allowed.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
