### ISSUE TITLE
Incorrect cast sign?

### ISSUE THREAD

**Issue by simo5** [openssl/openssl#20424]
https://github.com/openssl/openssl/blob/e8ca529feb0d062ab9f869ac25a37cc4c6b8b329/crypto/evp/digest.c#LL460C7-L460C7

In this line size is cast to an (int) and then assigned to an unsigned int.
In the previous like it was checked against UNIT_MAX.
Sounds like the cast should be to (unsigned int).
In practice size is never larger than a few hundred bytes but I got curious if this was an oversight or I am missing something.

**Comment by paulidale** [comment]
It's a bug.
