### ISSUE TITLE
How to change auth tag length for AES GCM encryption function in 3.0?

### ISSUE THREAD

**Issue by GennadyDagman** [openssl/openssl#20426]
Recently upgraded from OpenSsl 1.0.2 to 3.0.7 and can't figure out a way of specifying auth tag length = 32 (that what we used before) for AES GCM encryption functions. Looks like only default value 16 is supported now for AES GCM encryption. Please advice.

**Comment by slontis** [comment]
I assume it was changed to match the standard SP800-38D which specifies valid values that range from (12..16) bytes (i.e 96...128 bits).
The old e_aes.c ctrl function also checks the range being less than 16. So this must be very old behaviour.

**Comment by slontis** [comment]
So it can be set, but it cant be larger than 16.

**Comment by t8m** [comment]
Given the block size of AES being 128 bits the auth tag length larger than 16 bytes does not make any sense.

**Comment by GennadyDagman** [comment]
Right - my bad. We allocated 32 bytes for tag previously but in really only 16 bytes were really used.
