### ISSUE TITLE
PEM_write_PrivateKey failed(app exit) on windows

### ISSUE THREAD

**Issue by spartucus** [openssl/openssl#2042]
- OS: Windows 10 x64

- Env: Visual Studio 2015

- OpenSSL version: 1.1.0c

## behavior
I'm trying to use `PEM_write_PrivateKey() `function to write the private keys into the file. It fails. The Win32 console screen closed automatically after this function called. And the _key.pem_ file contains nothing.

Same problem already occurred, [here](http://stackoverflow.com/questions/17206907/pem-write-privatekey-function-is-not-storing-the-rsa-private-key-in-private-pe) and [here](http://stackoverflow.com/questions/34174114/when-calling-pem-write-privatekey-using-openssl-fips-compiled-libraries-the-oupu). But nothing helpful.

Actually, `PEM_write_X509()` acts same way as `PEM_write_PrivateKey()`.

## How to reproduce
use [this](https://gist.github.com/nathan-osman/5041136#file-create-x509-cpp) code on windows.

**Comment by levitte** [comment]
Right about [here](https://gist.github.com/nathan-osman/5041136#file-create-x509-cpp-L90), you might want to add this line:

```
ERR_print_errors_fp(stderr);
```

Actually, there are a number of places where you might want to do that.  That will help you diagnose what goes wrong.

This being said, this is hardly an issue with OpenSSL itself.  The better place for this kind of question is the mailing list openssl-users@openssl.org.  See [here](https://www.openssl.org/community/mailinglists.html) for information on our mailing lists.

Closing this.

**Comment by spartucus** [comment]
@levitte Thank you.

**Comment by guptachetan** [comment]
@spartucus I came across this today. For windows, we should set **/MD**  (Use Run-Time Library). In both debug and release configuration. It worked for me.
