### ISSUE TITLE
Default and mandatory digest for provider-based signature algorithms

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#20428]
OpenSSL master in https://www.openssl.org/docs/man3.0/man7/provider-signature.html does not contain reference to the two parameters "OSSL_PKEY_PARAM_DEFAULT_DIGEST" and "OSSL_PKEY_PARAM_MANDATORY_DIGEST".

This is somewhat problematic when considering this code:  https://github.com/openssl/openssl/blob/d0a3b9d1eb1fc510ec3447b44803bbf5520a0c47/apps/ca.c#L805-L810

This works correctly if --and only if-- "UNDEF" (`SN_undef`) is properly reported by a provider not needing a default digest (such as `oqsprovider`).

So: Would it be sensible to add reference to these two parameters in the documentation -- or rather change the code above to accept a provider not delivering default/mandatory digest information? See https://github.com/open-quantum-safe/oqs-provider/pull/119 for what is required in the provider to enable proper operation of `openssl ca` (short of a code change in `openssl`).

**Comment by levitte** [comment]
> ... or rather change the code above to accept a provider not delivering default/mandatory digest information?

This would be my preference.  The `"UNDEF"` is a cludge for when we didn't detect a lack of response very well, we did fix that since...

**Comment by levitte** [comment]
> > ... or rather change the code above to accept a provider not delivering default/mandatory digest information?
> 
> This would be my preference. The `"UNDEF"` is a cludge for when we didn't detect a lack of response very well, we did fix that since then...

The corresponding older (legacy) function, `EVP_PKEY_get_default_digest_nid()`, returns -2 when the backend doesn't support that particular query.  The documentation says (in the RETURN VALUES section) that `EVP_PKEY_get_default_digest_name()` does the same, but the description of the function itself talks about `"UNDEF"`.  This is confusing...

**Comment by levitte** [comment]
There's a little bit of confusion here, BTW.  Are you saying that with oqs algorithms, the user *must not* use a digest, i.e. it works the same way as for example ed25519?  In that case, the "UNDEF" answer is exactly correct, a lack of response would rather say that the user should use a digest of their choice.

**Comment by baentsch** [comment]
> There's a little bit of confusion here, BTW. Are you saying that with oqs algorithms, the user _must not_ use a digest, i.e. it works the same way as for example ed25519? In that case, the "UNDEF" answer is exactly correct, a lack of response would rather say that the user should use a digest of their choice.

No - OQS algs do work without digest (by default), but a user may specify one to be used.

**Comment by levitte** [comment]
> > There's a little bit of confusion here, BTW. Are you saying that with oqs algorithms, the user _must not_ use a digest, i.e. it works the same way as for example ed25519? In that case, the "UNDEF" answer is exactly correct, a lack of response would rather say that the user should use a digest of their choice.
> 
> No - OQS algs do work without digest (by default), but a user may specify one to be used.

In that case, it's more sensible to respond with "" or "UNDEF" (either is allowed) on OSSL_PKEY_PARAM_DEFAULT_DIGEST, and not respond at all on OSSL_PKEY_PARAM_MANDATORY_DIGEST.

**Comment by levitte** [comment]
Documentation amendment coming up!

**Comment by baentsch** [comment]
> and not respond at all on OSSL_PKEY_PARAM_MANDATORY_DIGEST

Agreed. That was what the provider code did originally -- but the only way to get a "2" into "def_ret" was by responding to "OSSL_PKEY_PARAM_MANDATORY_DIGEST", too (thus labelling it a hack right now and thus, this issue).

Some self-reflection on my side: It seems I try to avoid doing PR's... still a bit exhausted by #19312 apparently (getting old :). Whatever: Please let me know if you'd also do a code change PR or whether I should propose one. If the latter, a suggestion where best to place a test would be very welcome.

**Comment by levitte** [comment]
See #20430 for documentation amendment.  I hope this can serve as an example for other documentation pages

**Comment by mattcaswell** [comment]
> still a bit exhausted by https://github.com/openssl/openssl/pull/19312

#19312 was a big PR! I would hope that most PRs are significantly smaller and easier to get through the process!!

**Comment by levitte** [comment]
> > and not respond at all on OSSL_PKEY_PARAM_MANDATORY_DIGEST
> 
> Agreed. That was what the provider code did originally -- but the only way to get a "2" into "def_ret" was by responding to "OSSL_PKEY_PARAM_MANDATORY_DIGEST", too (thus labelling it a hack right now and thus, this issue).

Why do you want the return value to be 2?  That signifies that "UNDEF" is mandatory, i.e. that the caller *must not* specify a digest with the signature algorithm.   That doesn't seem to match what you want.

As far as I understand you, the expected return value should 1, with the returned digest name being "UNDEF".  I would interpret this to mean that the caller *may*, but is *not obligated* to a digest with the signature algorithm...  although, I just realised that this is a *new* interpretation, which is not documented, and that `apps/ca.c` doesn't consider.  However, the inner implementation of `EVP_PKEY_get_default_digest_name()` does support this:

https://github.com/openssl/openssl/blob/08a11ba20461ce14b0a6b9c9e374fbea91fbd8cf/crypto/evp/keymgmt_lib.c#L554-L566

> Some self-reflection on my side: It seems I try to avoid doing PR's... still a bit exhausted by #19312 apparently (getting old :).

I totally get you.  That PR was large, heavy and dealt with a relatively difficult concept.  Some level of exhaustion isn't a surprise.

> Whatever: Please let me know if you'd also do a code change PR or whether I should propose one. If the latter, a suggestion where best to place a test would be very welcome.

Let's remember the code bit 'til next week, yeah?

**Comment by baentsch** [comment]
> As far as I understand you, the expected return value should 1, with the returned digest name being "UNDEF". I would interpret this to mean that the caller may, but is not obligated to a digest with the signature algorithm... although, I just realised that this is a new interpretation, which is not documented, and that apps/ca.c doesn't consider. 

Yes, that would be what I mean/expect. 

> However, the inner implementation of EVP_PKEY_get_default_digest_name() does support this

Correct, `EVP_PKEY_get_default_digest_name` supports this, but this code does not (it mandates _both_ params to be there): https://github.com/openssl/openssl/blob/d0a3b9d1eb1fc510ec3447b44803bbf5520a0c47/apps/ca.c#L810 

--> Would it be reasonable to just remove the test for `def_ret == 2`? Just did it as a quick sanity check and all openssl tests pass...

**Comment by levitte** [comment]
> Correct, `EVP_PKEY_get_default_digest_name` supports this, but this code does not (it mandates _both_ params to be there):
> 
> https://github.com/openssl/openssl/blob/d0a3b9d1eb1fc510ec3447b44803bbf5520a0c47/apps/ca.c#L810
> 
> --> Would it be reasonable to just remove the test for `def_ret == 2`? Just did it as a quick sanity check and all openssl tests pass...

That wouldn't be right, 'cause that means that `def_ret == 1` is treated as if it was mandatory to not specify a digest.  So basically, not quite that simple.  I'll give that some thought.

**Comment by levitte** [comment]
Oh, I forgot to mention here that the main documentation change for provider developers happened with #20430

**Comment by levitte** [comment]
For apps/ca.c modification, see #20460

**Comment by baentsch** [comment]
Closed via #20430 and #20460
