### ISSUE TITLE
PKCS12 in FIPS mode, PKCS12KDF vs. PBKDF2

### ISSUE THREAD

**Issue by radekslabyswi** [openssl/openssl#20427]
Hello, I have a question regarding usage of PKCS12 in FIPS mode. It is related to https://github.com/openssl/openssl/issues/19997, which claims that PKCS12KDF is not FIPS-compliant and thus cannot work in FIPS mode - I do not dispute that. But I also stumbled upon https://mta.openssl.org/pipermail/openssl-users/2021-January/013405.html that suggests that with PBKDF2 it should be ok...
I created a pfx file that looks like this:
```
$ openssl pkcs12 -info -noout -in test.pfx
Enter Import Password:
MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Certificate bag
PKCS7 Data
Shrouded Keybag: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
```
I can produce such pfx file both with openssl (with default provider) and wincrypt (regardless of FIPS mode of windows)...
But when trying to load this with openssl in FIPS mode, it fails on `EVP_KDF_fetch(NULL, "PKCS12KDF", NULL)` regardless of pfx file algorithms.
I tried to debug openssl code directly, I see that the call stack is like this:
```
p12_kiss.c:PKCS12_parse
p12_mutl.c:PKCS12_verify_mac
p12_mutl.c:pkcs12_gen_mac
p12_key.c:PKCS12_key_gen_utf8_ex
p12_key.c:PKCS12_key_gen_uni_ex
```
I see that the usage of PKCS12KDF is hardwired in PKCS12_key_gen_uni_ex().

I assumed that PKCS12KDF/PBKDF2 will be picked dynamically while processing the pfx. I see that PBKDF2 is available in FIPS mode.
If you can explain to me what's wrong with my understanding, I'd really appreciate. Thanks much.

PS: Currently on openssl 3.0.7. I checked quickly the 3.0.8/3.1.0-beta and saw that there is no significant changes with regard to PKCS12, just on latest main branch there is some enhancements allowing to work with PKCS12 from non-default OSSL_LIB_CTX...
To describe my scenario: I need to use the same cert and private key both on linux and windows. Now upgrading from 1.1.1 to 3.0 and have a requirement for FIPS compliance. The current implementation is using pfx to distribute the cert/key. My trouble is that wincrypt is not able to use anything but pfx to import the private key, while openssl (in FIPS) has trouble using pfx.

**Comment by slontis** [comment]
Please see the discussion in https://github.com/openssl/openssl/issues/19997.
Basically everything you have done is correct, however if you want to verify the integrity it uses PKCS12KDF (which is not FIPS).
So you either verify using a non fips algorithm, or you dont do the verify (with the -nomac option).

e.g:
````
LD_LIBRARY_PATH=. OPENSSL_CONF=./apps/openssl.cnf ./apps/openssl pkcs12 -export -out test.p12 -inkey test/certs/server-pss-key.pem -in test/certs/server-pss-cert.pem -certpbe AES-256-CBC -keypbe AES-256-CBC -macalg SHA256
....

LD_LIBRARY_PATH=. OPENSSL_CONF=test/fips-and-base.cnf OPENSSL_CONF_INCLUDE=test OPENSSL_MODULES=providers ./apps/openssl pkcs12 -provider fips -info -noout -in test.p12

Warning: -macsaltlen option ignored without -export
Enter Import Password:
MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
Error verifying PKCS12 MAC; no PKCS12KDF support.
Use -nomacver if MAC verification is not required.
````

**Comment by radekslabyswi** [comment]
Thank you for the prompt response @slontis, I do believe it helped me resolve my confusion.
The detail I was missing is the difference between the main PKCS12 document-level MAC (which mandates the usage of PKCS12KDF) and the individual nested bags that may employ different schemes/algorithms as they are defined by standards other than PKCS12.
The result being that PKCS12 may for now be used only without MAC verification when FIPS is enabled or without FIPS enabled.

**Comment by slontis** [comment]
The standard is horribly complex :)
