### ISSUE TITLE
size_t vs int confusion in recent commits

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#20435]
PRs #20250 and #20181 correctly pointed out that `RSA_public_decrypt()` and `CMS_SharedInfo_encode()` return `<= 0`  on error, so error checks doing `== 0` are incorrect.

The checks were changed from `== 0` to `<= 0`, however the variables `rslen` and `penclen` are of type `size_t`, so the correct fix would be to assign to an int, check that int for `<= 0` and only if that is not the case assign to the `size_t`.

**Comment by nielsdos** [comment]
Thanks for noticing this, you are correct. The type is indeed still incorrect.

> Can the static analysis tool be extended to flag such signedness issues?

I'll make sure to extend the analysis such that it can catch these kind of issues.

**Comment by botovq** [comment]
There's one more `int` to `size_t` assignment a few lines down in `CMS_SharedInfo_encode()` . The error check happens to be correct (`penc` should remain `NULL` whenever `i2d` returns something negative), so I suppose it's a matter of taste if this should be changed:

https://github.com/openssl/openssl/blob/10836921e52ff9110c12b4b9f984e7c5ef1c89cc/crypto/cms/cms_ec.c#L360-L362

**Comment by mspncp** [comment]
Would one of you volunteer to create a pull request for it?

**Comment by nielsdos** [comment]
I can maybe do it. The only problem is that I can't sign a CLA so the fix would need to be "CLA: trivial", and I'm not sure if this would still fall under trivial.

**Comment by t8m** [comment]
Fix in #20457
