### ISSUE TITLE
Memory leakage occurs during async processing

### ISSUE THREAD

**Issue by haiyang0520** [openssl/openssl#20445]
file: crypto/async/async.c
function：
```` C 
static void async_release_job(ASYNC_JOB *job) {
    async_pool *pool;

    pool = (async_pool *)CRYPTO_THREAD_get_local(&poolkey);
    if (pool == NULL) {
        ERR_raise(ERR_LIB_ASYNC, ERR_R_INTERNAL_ERROR);
        return;
    }
    OPENSSL_free(job->funcargs);
    job->funcargs = NULL;
    sk_ASYNC_JOB_push(pool->jobs, job);
}
````

bug:  
This function does not release job->fibrectx and job memory.  As a result, memory leakage occurs.

**Comment by mattcaswell** [comment]
> This function does not release job->fibrectx and job memory. As a result, memory leakage occurs.

Do you have a concrete reproducer demonstrating a memory leak? The function `async_release_job` is not intended to release all resources associated with a job. It just releases the resources allocated for the current function call and returns it to the job pool. The actual job itself is freed via `async_job_free`.

**Comment by haiyang0520** [comment]
> > This function does not release job->fibrectx and job memory. As a result, memory leakage occurs.
> 
> Do you have a concrete reproducer demonstrating a memory leak? The function `async_release_job` is not intended to release all resources associated with a job. It just releases the resources allocated for the current function call and returns it to the job pool. The actual job itself is freed via `async_job_free`.

When will the job memory be released? 1200 jobs are applied for on the device, but the memory is not released

**Comment by mattcaswell** [comment]
See the docs here:

https://www.openssl.org/docs/man3.0/man3/ASYNC_cleanup_thread.html

In particular:

> The creation of an ASYNC_JOB is a relatively expensive operation. Therefore, for efficiency reasons, jobs can be created up front and reused many times. They are held in a pool until they are needed, at which point they are removed from the pool, used, and then returned to the pool when the job completes. If the user application is multi-threaded, then ASYNC_init_thread() may be called for each thread that will initiate asynchronous jobs. Before user code exits per-thread resources need to be cleaned up. This will normally occur automatically (see [OPENSSL_init_crypto(3)](https://www.openssl.org/docs/man3.0/man3/OPENSSL_init_crypto.html)) but may be explicitly initiated by using ASYNC_cleanup_thread(). No asynchronous jobs must be outstanding for the thread when ASYNC_cleanup_thread() is called. Failing to ensure this will result in memory leaks.

**Comment by haiyang0520** [comment]
> See the docs here:
> 
> https://www.openssl.org/docs/man3.0/man3/ASYNC_cleanup_thread.html
> 
> In particular:
> 
> > The creation of an ASYNC_JOB is a relatively expensive operation. Therefore, for efficiency reasons, jobs can be created up front and reused many times. They are held in a pool until they are needed, at which point they are removed from the pool, used, and then returned to the pool when the job completes. If the user application is multi-threaded, then ASYNC_init_thread() may be called for each thread that will initiate asynchronous jobs. Before user code exits per-thread resources need to be cleaned up. This will normally occur automatically (see [OPENSSL_init_crypto(3)](https://www.openssl.org/docs/man3.0/man3/OPENSSL_init_crypto.html)) but may be explicitly initiated by using ASYNC_cleanup_thread(). No asynchronous jobs must be outstanding for the thread when ASYNC_cleanup_thread() is called. Failing to ensure this will result in memory leaks.

Can the cleanup only be invoked by users? If the cleanup is not invoked, is the jobs always stored in the resource pool?

**Comment by mattcaswell** [comment]
Final cleanup should happen automatically on process exit. Thread local resources are cleaned up as threads exit. The `OPENSSL_init_crypto` page linked above discussed some limitations and situations where this may not occur. `ASYNC_cleanup_thread()` typically only needs to be called if you want to force cleanup to occur earlier than it otherwise would do.
