### ISSUE TITLE
openssl3 thread safe on ssl_read and ssl_write

### ISSUE THREAD

**Issue by mickae1** [openssl/openssl#20446]
Hi,

I would like to know if openssl 3 provide more safety on using ssl_write and ssl_read on different thread ?

**Comment by mattcaswell** [comment]
You cannot call `SSL_write()` and `SSL_read()` on different threads to each other for the *same* `SSL` object. You can do so for *different* `SSL` objects.

**Comment by mickae1** [comment]
so it's impossible to do a TLS server in blocking mode.
Do you have an example for non blocking mode ?

**Comment by mattcaswell** [comment]
> so it's impossible to do a TLS server in blocking mode. ( read and write at the same time )

Right - you can't be reading and writing to the same SSL object at the same time.

> Do you have an example for non blocking mode ?

Take a look here. There are various examples of different styles. These are all client side only, but the same principles should apply to server side:

https://github.com/openssl/openssl/tree/master/doc/designs/ddd

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
