### ISSUE TITLE
DTLS_set_timer_cb() is being stopped after some interval in openssl 1.1.1k version.

### ISSUE THREAD

**Issue by MonicKumar** [openssl/openssl#20459]
DTLS_set_timer_cb() is being stopped after some interval in openssl 1.1.1k version. My cb function gives interval as 0,4,8,16 and continues with 16 sec. 
But at 16 sec, cb is triggered only for 10 times, after that openssl is not triggering any cb, seems to be idle. 

openssl version
OpenSSL 1.1.1k  25 Mar 2021

//code snippet
static uint32_t dtls_connection_timer_cb(SSL *s, uint32_t timer_us)
{

    if (timer_us == 0)
    {
        timer_us = 4;
    }
    else
    {
        if(timer_us >= 16)
        {
            timer_us = 16;
        }
        else
        {
            timer_us = timer_us * 2;
        }
    }

    return timer_us;
}

DTLS_set_timer_cb(ssl, dtls_connection_timer_cb);

**Comment by mattcaswell** [comment]
The timer is only relevant during the handshake phase. Once the handshake is complete it won't be called any more.

**Comment by MonicKumar** [comment]
anyway i'm not starting my dtls server, my expectation is openssl should keep on sending client hello infinitely, which is not happening in my case.

**Comment by mattcaswell** [comment]
OpenSSL  maintains an internal count of the number of timer timeouts that have occurred. If you get more than 12 then it gives up.

**Comment by MonicKumar** [comment]
thank you for your response, 

1. Is there a way to make this counter infinite ?
2. Is there an API/callback available to know that openssl has stopped connection retry ?

**Comment by mattcaswell** [comment]
> Is there a way to make this counter infinite ?

No, this is not configurable.

> Is there an API/callback available to know that openssl has stopped connection retry ?

If an OpenSSL endpoint stops retrying then it will abort the connection, and whatever IO function you were attempting will return an error. `SSL_get_error()` will return `SSL_ERROR_SSL`.

An endpoint cannot know if its remote peer has given up retransmission. It will just stop receiving datagrams and will need to implement some form of timeout.

**Comment by MonicKumar** [comment]
thank you for your response,
In my cause there is no DTLS server, i want to configure openssl to send client hello packet without timeout. It should keep on waiting for server devices. 
1. Is there a way to make openssl to send "client hello" packet infinitely?
2. Is there an API/callback available to know that openssl has stopped sending "client hello" packet?

**Comment by MonicKumar** [comment]
thank you for your guidance!  
Helped to gain knowledge.

**Comment by MonicKumar** [comment]
> OpenSSL maintains an internal count of the number of timer timeouts that have occurred. If you get more than 12 then it gives up.

hi, is there a way to read the value of this internal counter?
