### ISSUE TITLE
Source file crypto/bn/rsa_sup_mul.c does not have a copyright header

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#20461]
I wonder if the relatively new source file [crypto/bn/rsa_sup_mul.c](https://github.com/openssl/openssl/blob/931369429564b5a9bb09711de8e885fef546a0ac/crypto/bn/rsa_sup_mul.c) should not also have a copyright header like all the other source files?

**Comment by mattcaswell** [comment]
Yes, it should.
