### ISSUE TITLE
openssl 1.1.1 in FIPS mode

### ISSUE THREAD

**Issue by ssk199441** [openssl/openssl#20465]
How did you make openssl 1.1.1 FIPS compliant, given that openssl 1.0.2 and 3.0.x are officially certified FIPS versions?
I'm just curious how we can use openssl 1.1.1 in FIPS mode.

**Comment by t8m** [comment]
We (as in OpenSSL project) did not. There might be some independent validations of OpenSSL-1.1.1 + patches such as the one Red Hat did. However that was not done by us and it would not be possible without (possible heavy) patching the upstream codebase. So we cannot answer any questions related to these.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
