### ISSUE TITLE
Twofish and Threefish Cipher Implementations?

### ISSUE THREAD

**Issue by WAR10CKfreeworld** [openssl/openssl#2046]
I noticed that the Twofish-256 and Threefish-1024 block ciphers are not implemented in the project. Any plans on adding them? If so then tell me and feel free to close this issue.

**Comment by richsalz** [comment]
no plans.

**Comment by jcdutton** [comment]
why not?

**Comment by kroeckx** [comment]
Because we don't see a demand for it, and we would only like to support things that have been standardised.

**Comment by jcdutton** [comment]
Well, twofish is far more secure that AES. Why wouldn't there be demand for it?

**Comment by kroeckx** [comment]
Rijndael was selected as AES and Twofish was one of the other candidates. This resulted in various ways that AES has become the cipher that is used for many things, has hardware support and so on. Twofish on the other hand has not been standardised, but as far as I know is mentioned in the RFC for SSH and OpenPGP as one of the options. I really don't see a need to add Twofish.

**Comment by richsalz** [comment]
To further emphasize what Kurt said, we are *only* providing ciphers that have been standardized.
See https://www.openssl.org/blog/blog/2018/01/18/f2f-london/ for some details.

**Comment by jcdutton** [comment]
So, if an RFC for TWOFISH appeared, much like  "chacha20-poly1305", openssl would support it?

**Comment by kroeckx** [comment]
It's a minimum requirement. We'd still need to at least see a use case for it. And since at least the OpenPGP and ssh RFC mention it, some people might want to see it. Then we'd still need someone to write it.

**Comment by richsalz** [comment]
And Chacha/poly is in TLS 1.3 (and earlier).

**Comment by flawrist** [comment]
# Color blindness

![](https://i.ytimg.com/vi/j4rkRptT8jI/maxresdefault.jpg)

# Cipher blindness

>> I noticed that the Twofish-256 and Threefish-1024 block ciphers are not implemented in the project.

> We don't see a demand for it…

Actually, even Blake3 (hash function) is STILL not implemented.
This is not even an omission, but a kind of criminal negligence.

Are only those solutions worthy of implementation that have been approved by egg-headed government agencies for their own reasons, while all other intellectual breakthroughs are to be ignored?
