### ISSUE TITLE
Support for large PQC signature algorithms

### ISSUE THREAD

**Issue by VeronikaNguyen** [openssl/openssl#20478]
Thanks to the contribution by @baentsch openssl now supports plugable signature algorithms ([see PR](https://github.com/openssl/openssl/pull/19312)). As earlier mentioned in [https://github.com/openssl/openssl/issues/10512#issuecomment-1263184329](https://github.com/openssl/openssl/issues/10512#issuecomment-1263184329) and [https://github.com/open-quantum-safe/oqs-provider/issues/121](https://github.com/open-quantum-safe/oqs-provider/issues/121) the size constants returned by [ossl_statem_client_max_message_size](https://github.com/openssl/openssl/blob/2ba5bffa26c0c4677f48e730628c0b54c31c734c/ssl/statem/statem_clnt.c#L961-L1017) and [ossl_statem_server_max_message_size](https://github.com/openssl/openssl/blob/2ba5bffa26c0c4677f48e730628c0b54c31c734c/ssl/statem/statem_srvr.c#L1141-L1179) cause failures for PQC algorithms with large signature size. Could we continue the [discussion](https://github.com/openssl/openssl/issues/10512#issuecomment-1263184329) initiated by @baentsch to enable the use of PQC algorithms with large signature sizes for [oqsprovider](https://github.com/open-quantum-safe/oqs-provider)?

**Comment by mattcaswell** [comment]
I think what I said in this [comment](https://github.com/openssl/openssl/issues/10512#issuecomment-1263320034) still applies:

> Those constants are just to sanity check the sizes. We've never needed or supported larger sizes before, so it made sense. If the constants no longer represent what is sane then we can change them.

Do we know what sane alternative values for these should be?

**Comment by VeronikaNguyen** [comment]
To ensure that all PQC signature algorithms at all security levels standardized by NIST can function properly, my preference would be for the value to be set to `65538 = 2^16+2`, which aligns with the values specified in the TLS 1.3 specification and [oqs-openssl111](https://github.com/open-quantum-safe/openssl).

**Comment by mattcaswell** [comment]
> my preference would be for the value to be set to 65538 = 2^16+2

Which is essentially the max allowed by the protocol right?. I'd be ok with that. Before it made sense to restrict this because no valid handshake that we could actually complete would have such large signatures. Now this is possible.

**Comment by VeronikaNguyen** [comment]
Yes, according to 
```
      struct {
          SignatureScheme algorithm;
          opaque signature<0..2^16-1>;
      } CertificateVerify;
```
in the spec.

Linking the corresponding locations in [openssl1](https://github.com/open-quantum-safe/openssl) below: [statem_clnt.c](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/ssl/statem/statem_clnt.c#L984) and [statem_srvr.c](https://github.com/open-quantum-safe/openssl/blob/511f387437e7de2c21b23cebecb4ede6b7a99f40/ssl/statem/statem_srvr.c#L1166)

**Comment by mattcaswell** [comment]
PR welcome to make this change. I'd suggest a macro for the size in the same style as `SERVER_HELLO_MAX_LENGTH`.

**Comment by VeronikaNguyen** [comment]
Perfect, will do it by the end of the day.

**Comment by baentsch** [comment]
> Perfect, will do it by the end of the day.

Thanks @VeronikaNguyen for taking this up and @mattcaswell for the above suggestion. Very glad to see this getting resolved. Also FYIing the authors and interested parties from https://github.com/openssl/openssl/issues/10267 and https://github.com/openssl/openssl/issues/6433 , @alexmikhalevich, @christianpaquin, @mkwork.
