### ISSUE TITLE
DH_up_ref without DH_free

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#20476]
This lines 

https://github.com/openssl/openssl/blob/931369429564b5a9bb09711de8e885fef546a0ac/providers/implementations/exchange/dh_exch.c#L108-L109

may fail in theory.

We have an DH_up_ref call several lines before. Should we call DH_free in case of failure of these functions?

**Comment by mattcaswell** [comment]
If they fail, then the caller should then (eventually) call dh_freectx(), where DH_free() is then called. So I don't think this is a leak.

**Comment by mattcaswell** [comment]
No. On entry, 1 ref is owned by the key manager. During init we up ref, so ref 2 is owned by the key exchange ctx. When the key exchange ctx gets free, we down ref via DH_free(). When the key manager owned key is freed we call call DH_free() again (in dh_freedata() in dh_keymgmt.c)
