### ISSUE TITLE
New API function for constant-time blinding invert using ossl_bn_rsa_do_unblind?

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#20475]
The OpenSSL API provides several functions to support RSA blinding, e.g. `BN_BLINDING_create_param()`, `BN_BLINDING_update()`, `BN_BLINDING_convert_ex()`, `BN_BLINDING_invert_ex()`, etc.

With the recent change from commit https://github.com/openssl/openssl/commit/b1892d21f8f0435deb0250f24a97915dc641c807, the `rsa_ossl_private_decrypt()` function was changed to use the constant-time `ossl_bn_rsa_do_unblind()` function instead of `BN_BLINDING_invert_ex()`.

Unfortunately, the `ossl_bn_rsa_do_unblind()` functionality is not available via external OpenSSL API, so a provider implementer must re-invent or copy this in order to have a constant-time unblinding function.

Would it be possible to make the `ossl_bn_rsa_do_unblind()` functionality available as external OpenSSL API as well?
Kind of a `BN_BLINDING_invert_ex2()` that outputs the result in a byte array of modulus size instead of as a BIGNUM? Maybe even the intermediate input message could be supplied as byte array of modulus size right away, and not as a BIGNUM either.

**Comment by t8m** [comment]
If https://github.com/openssl/openssl/pull/20281 gets merged, it should resolve this problem without adding a new API.

**Comment by ifranzki** [comment]
With the alternate implementation from https://github.com/openssl/openssl/pull/20281 this is now obsolete. One can now simply use the BN_BLINDING_invert_ex() function (but make sure to use `BN_set_flags(f, BN_FLG_CONSTTIME);` on the message `f` to unblind).

**Comment by ifranzki** [comment]
I have a follow-on question for this:

With the alternate implementation from https://github.com/openssl/openssl/pull/20281 one can simply use `BN_BLINDING_invert_ex()`, that's great, but how can I know if the underlying OpenSSL does have the alternate implementation or not? On OpenSSL versions that don't yet have it yet, I should probably still use the `ossl_bn_rsa_do_unblind()` approach.

I certainly could do some build time checking on OPENSSL_VERSION_NUMBER to see if the OpenSSL that I am compiling against is a certain version (i.e. >= OpenSSL 1.1.1u - once available, >= OpenSSL 3.0.9 - once available, >= OpenSSL 3.1.1 - once available, or >= OpenSSL 3.2.0). But that way I still have to retain the `ossl_bn_rsa_do_unblind()` implementation. Also, I need to hope that its always run with the same OpenSSL version it got compiled with.... 

Is there another smart way of dealing with that?

**Comment by paulidale** [comment]
I can't think of any.  I can think of several ways of avoiding the version number checks (weak symbols, dlopen) but the version check is probably cleaner and is definitely more portable.

**Comment by ifranzki** [comment]
Right, that was my thinking, too.

Another question: As mentioned above, `BN_BLINDING_invert_ex()` is only constant-time if the application only uses the BIGNUM with `BN_bn2binpad()` and nothing else. 

In my case I do have the result of the Mod-Expo operation as byte array, not as BIGNUM. So I need to convert it to a BIGNUM first via `BN_bin2bn()` before I can then use if with `BN_BLINDING_invert_ex()` and finally with `BN_bn2binpad()` to get the result as byte array. 

`BN_bin2bn()` does not seem to be constant-time, but since it is the blinded message that it operates on, this should not matter. Do you agree?

**Comment by paulidale** [comment]
I think you're correct.

**Comment by ifranzki** [comment]
Thanks!
