### ISSUE TITLE
How can I use riscv64-unknown-linux-gnu to compile a C file (with the Kyber encryption algorithm) that uses the OpenSSL library on Ubuntu? Also, how can I run the generated binary executable with PK?

### ISSUE THREAD

**Issue by adamsir32** [openssl/openssl#20483]
How can I use riscv64-unknown-linux-gnu to compile a C file (with the Kyber encryption algorithm) that uses the OpenSSL library on Ubuntu? Also, how can I run the generated binary executable with PK?

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
