### ISSUE TITLE
Inconsistent generation of shared keys with ECDH algorithm

### ISSUE THREAD

**Issue by ddjonin** [openssl/openssl#20494]
In OpenSSL 3.0.7, in the following two cases, we get inconsistent shared key generation with ECDH with the same peer public key:

(A) local EVP_PKEY + peer public EVP_PKEY (rebuilt from raw peer public key)
(B) rebuilt local EVP_PKEY (from previously exported local raw public key and local raw private key) + peer public EVP_PKEY (rebuilt from raw peer public key - identical to the one in case A)

Both operations complete without SSL errors, but the keys are different. We think that these should end up being the same.

* Generating shared keys is performed as per: ```https://wiki.openssl.org/index.php/EVP_Key_Agreement```
* local EVP_PKEY is rebuilt according to **Creating an ECC keypair using raw key data** in ```https://www.openssl.org/docs/man3.1/man3/EVP_PKEY_fromdata.html```
* Lastly, local private key is extracted using:
```
unsigned char * openssl_ecdh_extract_privatekey(EVP_PKEY *pkey)
{
    OSSL_PARAM *params;
    unsigned char* pk = NULL;
    int ok = 1;

    if (!(EVP_PKEY_todata(pkey, EVP_PKEY_KEYPAIR, &params)))
        // Error

    while ((params->key != NULL) && ok) {
        if (strcmp(params->key, "priv") == 0) {
            pk = (unsigned char *) params->data;
            ok = 0;
        }
        params++;
    }
    return(pk);
}
```
* Similar approach is used to get the public raw key with substituting string "priv" with "pub"

Most likely, the EVP_KEY rebuilding operation in ```https://www.openssl.org/docs/man3.1/man3/EVP_PKEY_fromdata.html``` is not reconstructing the key exactly the same as original and probably something is missing in params setting.

We tried finding a test code that does this in openssl project, but tests in ectest.c seem to be for versions prior to OpenSSL 3.0.0.

**Comment by slontis** [comment]
demos/pkey/EVP_PKEY_EC_keygen.c should show you how to extract parameters via EVP_PKEY_get functions..


There is also a known answer test in providers/fips/self_test_kats.c that shows how to deal with ras input. See the function self_test_ka().

(The derive needs private key A and peer key B (Or private key B and peer Key A)

**Comment by slontis** [comment]
Also if you look at the doc for EVP_PKEY-EC.pod  you will notice that 'pub' is an octet string (which is just bytes) whereas 'priv' is an unsigned integer (which needs to be read into a BIGNUM).
