### ISSUE TITLE
What is the verion of libcrypto.so.10?

### ISSUE THREAD

**Issue by czmeng** [openssl/openssl#20495]
My system use the the libcrypto.so.1.0.2o. I need to customize it.
I download the code of openssl 1.0.2o (and try some versions nearby), then customize and build it. OS version is BigCloud Enterprise Linux For Euler release 21.10 (LTS-SP2).
But the soft said "version 'libcrypto.so.10' not found". I use readelf -d ld check the old libcrypto.so.1.0.2o. It does libcrypto.so.10.
And readelf -d ld libcrypto.so.1.0.2o what I build. It shows "Library soname: [libcrypto.so.1.0.2o]". But I can not find the code of version openssl 10.
What is the verion of libcrypto.so.10? or How to build libcrypto.so.10.

**Comment by t8m** [comment]
This library comes from the OS - most probably a descendant of Red Hat Enterprise Linux. The patched version of OpenSSL-1.0.2 from RHEL has the SONAME changed to libcrypto.so.10. As those OS provided openssl packages are usually quite heavily patched, it is not recommended to replace the system openssl library with one built from upstream sources.

**Comment by czmeng** [comment]
Thanks. How can I change some version config on the code to build to libcrypto.so.10 on no RHEL OS?

**Comment by levitte** [comment]
Let's take this from another angle.  You said:

> But the soft said "version 'libcrypto.so.10' not found"

What software is that?  Is it a software you're building?  In that case, you will need to rebuild it, and while doing so, ensure that it links against your installation of 1.0.2o instead of libcrypto.so.10.

**Comment by czmeng** [comment]
The soft is ceph. For some non-technical reasons, I can not modify it or change the version.

**Comment by levitte** [comment]
> The soft is ceph. For some non-technical reasons, I can not modify it or change the version.

I understand.  Then, I'm afraid you're stuck with its use of libcrypto.so.10, and the package that delivered it.  I can only repeat what @t8m already said:

> it is not recommended to replace the system openssl library with one built from upstream sources.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
