### ISSUE TITLE
Outdated copyright notice

### ISSUE THREAD

**Issue by JackCoplandGranta** [openssl/openssl#20496]
[A bit ago](https://github.com/openssl/openssl/commit/2a4b68ef01281b03e59d723d82ca547cede2fbd5) the copyright year was updated to 2023 in most places. But the copyright [at the bottom of the readme is still 2022](https://github.com/openssl/openssl/blob/master/README.md#copyright). Should this copyright notice also be updated?

**Comment by JackCoplandGranta** [comment]
I had presumed the readme copyright notice was indicating a copyright notice for the whole repo, not just the readme itself. Thanks.

**Comment by mattcaswell** [comment]
> I had presumed the readme copyright notice was indicating a copyright notice for the whole repo, not just the readme itself.

That's not an unreasonable interpretation for this particular file.

Possibly we should update the script to special case this file and always update it if the year has ticked over. Marking this as a bug because, either way, the script probably needs some fixing.

**Comment by DimitriPapadopoulos** [comment]
The copyright year has been updated (manually?) in #21225.

**Comment by DimitriPapadopoulos** [comment]
If the copyright in README.md has a global scope, shouldn't the start year be 1995 instead of 1998? Indeed:
```
$ grep -Re ' Copyright 1995-.... The OpenSSL Project Authors.' | wc -l
495
$ 
```

**Comment by DimitriPapadopoulos** [comment]
> Possibly we should update the script to special case this file and always update it if the year has ticked over. Marking this as a bug because, either way, the script probably needs some fixing.

File `README.md` contains:
```
Copyright (c) 1998-2023 The OpenSSL Project
```
while other files lack the `(c)`:
```
 * Copyright 1995-2022 The OpenSSL Project Authors. All Rights Reserved.
```

Yet the [script](https://github.com/openssl/tools/blob/988e13a8d44b7266cda11c5e6e815c6084451aed/release-tools/do-copyright-year#L15) does match that copyright notice (note the` .*`):
```sh
copyright="Copyright .*${year_range} .*${copyright_owner}"
```
