### ISSUE TITLE
ld warnings, use multi version of openssl in my project

### ISSUE THREAD

**Issue by AdiaLoveTrance** [openssl/openssl#20507]
Hi:
  I build my project use openssl shared library and I got link warning as :

> /usr/bin/ld: warning: libssl.so.1.0.0, needed by libmysqlclient.so, may conflict with libssl.so.1.1
> /usr/bin/ld: warning: libcrypto.so.1.0.0, needed by libmysqlclient.so, may conflict with libcrypto.so.1.1

because other lib I linked in my project use openssl 1.0.2, I wonder If different version of openssl will conflict in my project. And should I unify the openssl version used in my project?
Thank U!

**Comment by t8m** [comment]
It highly depends on the actual use, the OS platform, etc. Sometimes it works fine but it can also horribly break in other cases.

**Comment by t8m** [comment]
In other words it is always good idea to unify the OpenSSL version used if at all possible.

**Comment by AdiaLoveTrance** [comment]
Thank you! I will try to unify them.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
