### ISSUE TITLE
error: instruction requires: AVX-512 ISA AVX-512 VLX ISA

### ISSUE THREAD

**Issue by ryandesign** [openssl/openssl#20518]
openssl 3.1.0 fails to build on OS X 10.10.x when using Xcode 7.x; OS X 10.11.x; macOS 10.12.x; macOS 10.13.x; and macOS 10.14.x when using Xcode 10.0 or 10.1. The error is:

```
crypto/bn/rsaz-3k-avx512.s:22:2: error: instruction requires: AVX-512 ISA AVX-512 VLX ISA
 vpxord %ymm0,%ymm0,%ymm0
 ^
```

This was reported to MacPorts here: https://trac.macports.org/ticket/67099

Full build logs of failures on macOS 10.10-10.13, and successes on earlier and later versions, are available here: https://ports.macports.org/port/openssl3/builds/

The problem happens because you are deciding whether the compiler supports avx512 based on faulty criteria:

https://github.com/openssl/openssl/blob/738d43634a5192b1be0869f151682bb8e9157d5a/crypto/modes/asm/aes-gcm-avx512.pl#L62-L64

There, we see you try to use avx512 if the compiler is clang and its version is 7.0 or greater. The problem is that there are two different compilers named clang: the original project's, and Apple's fork which is included in Xcode on macOS. Apple's clang fork uses a different version numbering scheme than the original project's. Support for avx512 may indeed have appeared in the original clang version 7.0 but it evidently did not appear until a later version of Apple's fork of clang.

Based on the table at https://en.wikipedia.org/wiki/Xcode#Toolchain_versions it looks like Apple clang 10.0.1 is the first version that was based on the original project's clang 7.0.0. Apple clang 10.0.0 and earlier were based on original clang 6 and earlier.

Apple clang does identify itself as such in the version string, as in:

```
$ clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

or:

```
% clang -v
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

so it should be fairly easy to modify aes-gcm-avx512.pl to check for the `Apple` prefix and use Apple version numbering in that case. However the version number comparison will need to be enhanced to accommodate the third number. (The existing version number comparison code is wrong anyway since it treats the first two numbers as a floating point number.)

Instead of checking compiler version numbers, it would be more reliable to compile a small program using avx512 and see if it succeeds. If yes, use avx512 support; if not, don't. The way that most configure scripts figure out a system's capabilities.

If you want to continue looking at compiler version numbers and are able to access preprocessor macros, the macro `__apple_build_version__` is set for Apple clang and is not set for original clang. (You can also use the value of `__apple_build_version__` instead of looking at the clang version, if preferred.)

**Comment by ryandesign** [comment]
The same problem was already fixed in some of the other avx perl scripts in 523e0577305bbcc732d22bcb063c6c8ca658874a:

https://github.com/openssl/openssl/blob/738d43634a5192b1be0869f151682bb8e9157d5a/crypto/bn/asm/rsaz-4k-avx512.pl#L51-L62

**Comment by t8m** [comment]
Yes, the fixes for rsaz-3k-avx512.pl and rsaz-4k-avx512.pl were not backported.

**Comment by t8m** [comment]
Fix in #20519

**Comment by ryandesign** [comment]
> Fix in #20519

Thanks. #20519 only fixes rsaz-3k-avx512.pl and rsaz-4k-avx512.pl. It doesn't fix aes-gcm-avx512.pl. [That patch](https://github.com/openssl/openssl/issues/20518#issuecomment-1470093691) is also needed.

**Comment by t8m** [comment]
Ah, that one isn't fixed on master branch either.

**Comment by t8m** [comment]
Fixed.
