### ISSUE TITLE
Cannot get master key SSL_SESSION_get_master_key in either client or server

### ISSUE THREAD

**Issue by miguelarman** [openssl/openssl#20511]
I am building a TLSv1.3 client and server using the OpenSSL C libraries. I am trying to use PSK to set the master key with ```SSL_SESSION_set1_master_key``` inside the callback, which is set with ```SSL_CTX_set_psk_find_session_callback```. This function does not return any error code explained in the online documentation.

Next, I am trying to call ```SSL_SESSION_get_master_key``` in both the client and server programs, but they both return a value of 0. I am using the auxiliary function:
```
void print_handshake_info(SSL *ssl) {
    ...
    unsigned char *masterkeyout;
    masterkeyout = (unsigned char *)malloc(256 * sizeof(unsigned char));
    size_t masterkeylen = SSL_SESSION_get_master_key(SSL_get_session(ssl), masterkeyout, 256);
    printf("Master key for the session (%d): ", masterkeylen);
    for (int i = 0; i < masterkeylen; i++) {
        printf("%02x ", masterkeyout[i]);
    }
    printf("\n");
    free(masterkeyout);
}
```

I opened an issue last week (#20464) that was resolved in the way pointer and arrays were used, but this time I do not think that is the issue. The argument is not a double pointer, but a buffer as is called in the online references. I tried declaring both ```unsigned char *masterkeyout;``` and ```unsigned char masterkeyout[256];```, but the result was the same.

After some more tests, I also called this auxiliary function from my main loop (in the previous case it was called in a function that just processes each connection in the server), and now the output is a 256 elements array (the size I chose for the buffer) and the contents are all 00. I tried changing 256 to a different number and the result changed to that number.

So after searching for information and reading all documentation about this function I could find online, I am not sure if I am calling this function wrong or what can be done differently.

Thanks in advance!

**Comment by mattcaswell** [comment]
At what point in the handshake are you calling this function?

**Comment by miguelarman** [comment]
> At what point in the handshake are you calling this function?
- In the client program, at the end of the connection after ```SSL_read```.
- In the server program inside the loop for each connection after ```SSL_set_fd```

**Comment by mattcaswell** [comment]
In TLSv1.3 the "master secret" is actually the resumption secret for the session. This doesn't get set until session tickets are sent/received (because the resumption secret is tied to the ticket).

> In the client program, at the end of the connection after SSL_read.

This is probably too early. In TLSv1.3 a server does not send a session ticket until *post* handshake. See the man page for `SSL_get_session` here:

https://www.openssl.org/docs/man3.0/man3/SSL_get_session.html

Which says:

> The ssl session contains all information required to re-establish the connection without a full handshake for SSL versions up to and including TLSv1.2. In TLSv1.3 the same is true, but sessions are established after the main handshake has occurred. The server will send the session information to the client at a time of its choosing, which may be some while after the initial connection is established (or never). Calling these functions on the client side in TLSv1.3 before the session has been established will still return an SSL_SESSION object but that object cannot be used for resuming the session. See [SSL_SESSION_is_resumable(3)](https://www.openssl.org/docs/man3.0/man3/SSL_SESSION_is_resumable.html) for information on how to determine whether an SSL_SESSION object can be used for resumption or not.

...

> The preferred way for applications to obtain a resumable SSL_SESSION object is to use a new session callback as described in [SSL_CTX_sess_set_new_cb(3)](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_sess_set_new_cb.html). The new session callback is only invoked when a session is actually established, so this avoids the problem described above where an application obtains an SSL_SESSION object that cannot be used for resumption in TLSv1.3. It also enables applications to obtain information about all sessions sent by the server.

> In the server program inside the loop for each connection after SSL_set_fd

This is way too early. I'm assuming that you mean after "accept" has been called on the socket, and you are setting the fd on a new SSL object. The handshake has not even occurred at this point. Call `SSL_accept` (repeatedly if necessary and you are using non-blocking sockets) as per the man page, until it returns successfully. Although the tickets get sent after the handshake, an OpenSSL server will actually do this *immediately* after the handshake and will include it as part of the `SSL_accept` call.

**Comment by miguelarman** [comment]
> In TLSv1.3 the "master secret" is actually the resumption secret for the session. This doesn't get set until session tickets are sent/received (because the resumption secret is tied to the ticket).

I am ultimately trying to implement TLSv1.3 negotiation with a PSK that was previously established out-of-bounds (offline for example). In the [manual for ```SSL_CTX_set_psk_find_session_callback```](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_psk_find_session_callback.html) where it talks about TLSv1.3 servers, it says:
> The callback function is given a pointer to the SSL connection in ssl and an identity in identity of length identity_len. The callback function should identify an SSL_SESSION object that provides the PSK details and store it in *sess. The SSL_SESSION object should, as a minimum, set the master key, the ciphersuite and the protocol version

So I understand my PSK is what should be inserted as the master key. In [other code I found online](https://github.com/TalkWithTLS/TalkWithTLS/blob/master/src/sample/openssl_tls13_psk_out_of_band_server.c) it uses similar functions (but on the connection rather than on the context) and inserts the PSK there.

I am now trying to print the master key to see if the callbacks I implemented both on the client and the server are indeed inserting this value into the handshake (the callbacks are indeed being called, and with Wireshark I could see the mode PSK with (EC)DHE is been used so I understand the master key is not used by itself but rather combined with the secrets and key shares sent during the handshake).









> 
> > In the client program, at the end of the connection after SSL_read.
> 
> This is probably too early. In TLSv1.3 a server does not send a session ticket until _post_ handshake. See the man page for `SSL_get_session` here:
> 
> https://www.openssl.org/docs/man3.0/man3/SSL_get_session.html
> 
> Which says:
> 
> > The ssl session contains all information required to re-establish the connection without a full handshake for SSL versions up to and including TLSv1.2. In TLSv1.3 the same is true, but sessions are established after the main handshake has occurred. The server will send the session information to the client at a time of its choosing, which may be some while after the initial connection is established (or never). Calling these functions on the client side in TLSv1.3 before the session has been established will still return an SSL_SESSION object but that object cannot be used for resuming the session. See [SSL_SESSION_is_resumable(3)](https://www.openssl.org/docs/man3.0/man3/SSL_SESSION_is_resumable.html) for information on how to determine whether an SSL_SESSION object can be used for resumption or not.
> 
> ...
> 
> > The preferred way for applications to obtain a resumable SSL_SESSION object is to use a new session callback as described in [SSL_CTX_sess_set_new_cb(3)](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_sess_set_new_cb.html). The new session callback is only invoked when a session is actually established, so this avoids the problem described above where an application obtains an SSL_SESSION object that cannot be used for resumption in TLSv1.3. It also enables applications to obtain information about all sessions sent by the server.

In my still minimal client program (send request and print response) that is as late as I can, as it is literally the instruction before calling ```SSL_free```.







> 
> > In the server program inside the loop for each connection after SSL_set_fd
> 
> This is way too early. I'm assuming that you mean after "accept" has been called on the socket, and you are setting the fd on a new SSL object. The handshake has not even occurred at this point. Call `SSL_accept` (repeatedly if necessary and you are using non-blocking sockets) as per the man page, until it returns successfully. Although the tickets get sent after the handshake, an OpenSSL server will actually do this _immediately_ after the handshake and will include it as part of the `SSL_accept` call.

Yes, after ```accept``` is called and the descriptor is passed to SSL. I moved the print auxiliary function after ```SSL_accept```, and again just before ```SSL_free``` but the output is the same (empty array).


I do not know if I conceptually understand something wrong about TLSv1.3 handshakes or I am implementing something not in the right way. Anyway, thanks for the quick response!

**Comment by miguelarman** [comment]
If instead of using my client program I just use `curl`, I can print the session key with no modifications in the server code. So I am thinking there is some problem with my client code (?)

**Comment by miguelarman** [comment]
For further reference, I used [this email thread](https://mta.openssl.org/pipermail/openssl-users/2019-October/011386.html) as a starting point to understand this problem

**Comment by mattcaswell** [comment]
> I am now trying to print the master key to see if the callbacks I implemented both on the client and the server are indeed inserting this value into the handshake 

It doesn't work this way. The master key value does not get inserted into the handshake. Rather the *identity* is inserted. So, client and server in some out-of-band mechanism have the same resumption key (aka master key here), and an associated "identity" value for that key, e.g. "psk1". The identity can be public, but the key itself must not be. The client sends the identity to be used in the psk extension of the ClientHello. The server then looks up the master key to be used for that identity via the "find_session_callback". The callback provides it via a session object....but this is *not* the same object that you will get by calling SSL_get_session().

**Comment by miguelarman** [comment]
Got it. Sorry for my wording. I am trying to check if the master key I set independently in the server and the client (never sent in the handshake, loaded locally after checking the identity) is indeed being used for communication by the server and the client.

> The callback provides it via a session object....but this is not the same object that you will get by calling SSL_get_session().

This being the case, I fail to see how can I check that the master key is correctly established. In said callback, the created session object indeed returns my PSK if I call ```SSL_SESSION_get_master_key``` on it. But outside the callback itself I do not see how to check this functionality.

**Comment by miguelarman** [comment]
Thanks a lot for pointing that out! I am moving in the right direction finally!

However, I came across another problem. In both psk related callbacks I set the correct ciphersuite with `SSL_CIPHER_find` and `SSL_SESSION_set_cipher`. (In my case it is TLS_AES_128_GCM_SHA256 as I have a 128-bit AES key as psk). However, I left the server program with three TLSv1.3 ciphersuites for compatibility for cases where PSK is not used: 
```
SSL_CTX_set_ciphersuites(ctx, "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256");
```

In the case I set just this one ciphersuite in the client program (`SSL_CTX_set_ciphersuites(ctx, "TLS_AES_128_GCM_SHA256")`) or in `s_client` (via the `-ciphersuites` argument), the session is "reused" correctly (calling the function you pointed out I can see that) and also the `SSL_SESSION_get_master_key` returns my psk.

But when I leave some options to the client, it fails in doing this and with Wireshark I see that the ciphersuite that ends up being used is `TLS_AES_256_GCM_SHA384`, which of course does not work with my psk/key due to it being shorter.

What I assumed would happen is that when the callback selects the ciphersuite to be used (with `SSL_CIPHER_find` and `SSL_SESSION_set_cipher`), this would reflect on the negotiation and the Server Hello message would show this value as the result.

For now I can just restrict the client to this ciphersuite and every problem I described in this issue is solved (thanks a lot for everything!), but I would really like to leave some options for dynamic functionality like user input, and the handshake act accordingly.

As I said, thanks a lot for all your answers and your help!

**Comment by mattcaswell** [comment]
> What I assumed would happen is that when the callback selects the ciphersuite to be used (with SSL_CIPHER_find and SSL_SESSION_set_cipher), this would reflect on the negotiation and the Server Hello message would show this value as the result.

Unfortunately not. The ciphersuite supplied by the callback is *only* used to determine the hash function to be associated with the PSK (so if it is TLS_AES_128_GCM_SHA256 then it uses SHA256 for the PSK). It has no bearing on the ciphersuite negotiation. The handshake ciphersuite selection happens first. If the hash function in the negotiated ciphersuite is not compatible with the hash function in the PSK then the PSK will be rejected and a normal handshake will be attempted.

**Comment by miguelarman** [comment]
I was understanding it wrong then, sorry. I have to rethink how to approach some functionality then, but all my problems have been solved! Thanks again so much for all the help and the incredibly quick responses.
