### ISSUE TITLE
Ciphers unsupported  (unsupported:crypto/evp/evp_fetch.c:) in default provider OpenSSL3.0.8 configured from qatprovider 

### ISSUE THREAD

**Issue by Yogaraj-Alamenda** [openssl/openssl#20513]
We have provider implementation (https://github.com/intel/QAT_Engine) where we have ciphers implementation and if  particular ciphers is disabled in qatprovider it is configured to use default provider instead of qatprovider which was working fine till OpenSSL 3.0.7 but am seeing error like below from OpenSSL3.0.8. While I am trying to figure what went wrong, do you have any inputs on what changed in 3.0.8 that is causing this problem. 

openssl speed -provider qatprovider -elapsed -async_jobs 72 -evp chacha20-poly1305

speed: chacha20-poly1305 is an unknown cipher or digest
40A7F14EB77F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (chacha20-poly1305 : 0), Properties (<null>)
40A7F14EB77F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (chacha20-poly1305 : 0), Properties (<null>)

Here is chacha-poly is disabled in our provider build and supposed to use default provider but fails with the above error in OpenSSL3.0.8. This beahviour only observed with symmetric ciphers and not with asym algorithms

**Comment by mattcaswell** [comment]
> openssl speed -provider qatprovider -elapsed -async_jobs 72 -evp chacha20-poly1305

You don't seem to be loading the default provider in the above command (i.e. `-provider default`). You need to explicitly load the default provider if you are explicitly loading another one. This behaviour wasn't changed in 3.0.8 though and I can't think of any changes in 3.0.8 which would have impacted you.

**Comment by Yogaraj-Alamenda** [comment]
Thanks for the reply. Yes, Although default provider is not loaded, it uses default provider when algorithm is disabled in the qatprovider which stopped working form 3.0.8. Hence the query.

**Comment by paulidale** [comment]
I don't see anything in your provider that calls OpenSSL to implement functions that it's not supporting.
Without this, you **must** load the default provider for them to work.
I.e. `openssl speed -provider qatprovider -provider default -elapsed -async_jobs 72 -evp chacha20-poly1305`

If you don't specify `-provider qatprovider`, the default provider will load automatically and this might have been what you saw.  Once you've specified a provider, the default will not automatically load anymore.

**Comment by Yogaraj-Alamenda** [comment]
Sorry if it is a repeat. Regarding "Once you've specified a provider, the default will not automatically load anymore."  is this introduced in OpenSSL3.0.8 ? The reason for the ask is till 3.0.7 without having to provide "-provider default" in the speed it used to load automatically when the cipher is not supported. 

This behaviour is only with ciphers not with asym ciphers like RSA, ECDH, etc.

**Comment by paulidale** [comment]
No, this is not new.  It's always been like this.  Loading any provider prevents the automatic loading of the default provider.

What you think you saw isn't possible and hasn't been for any provider based OpenSSL.  There are a number of possibilities that could explain what happened without you realising it: default provider loaded via config, picked up a system OpenSSL, ...

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
