### ISSUE TITLE
The release script uses an unexpected local branch name

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#20510]
During the recent 3.1 release the release script was supplied with the "--final" argument indicating that the release was moving out of beta into a "final" release. In spite of this the script created a local branch name called "OSSL--openssl-3.1--3.1.0-beta2". The "beta2" in the name was unexpected and caused me some concern until I realised that it seemed to have done everything correctly, i.e. it really was creating a "final" release and not "beta2".

**Comment by mattcaswell** [comment]
@levitte

**Comment by levitte** [comment]
Noted, I can fix tomorrow

**Comment by levitte** [comment]
@matt, @t8m et all, let's pay attention to the branch name on next release.  This isn't anything specific to "final".

**Comment by arapov** [comment]
@levitte, I've brought this to the board for visibility. We will decide whether it is material or not when we do the release.
