### ISSUE TITLE
3.1.0 vs 3.0.8 branch?

### ISSUE THREAD

**Issue by AachoLoya** [openssl/openssl#20515]
Found this link: https://www.openssl.org/policies/releasestrat.html

```
Version 3.1 will be supported until 2025-03-14
Version 3.0 will be supported until 2026-09-07 (LTS).
```

Looks like 3.0 is LTS branch, 3.0.8 was released a couple of days ago. Does that mean that 3.0.x releases will continue with patch number until support-end date e.g. 3.0.9, 3.0.10 etc? 

Is there any benefit of switching to 3.1.x releases other than FIPS validation?

**Comment by mspncp** [comment]
There was a recent blog post about the[OpenSSL3.1 Release](https://www.openssl.org/blog/blog/2023/03/07/OpenSSL3.1Release).

**Comment by paulidale** [comment]
3.1 has additional performance fixes and some assembly code improvements.

**Comment by mattcaswell** [comment]
Designating a release as LTS imposes a significant support burden on the project for many years to come. If every release was LTS it would negate the point of having LTS in the first place. According to our policies we are committed to designating a release as LTS at least every four years. So we should expect to have designated a new one before 2025-09-07.

Yes, there will be a 3.2. Release date has not yet been set but hopefully later this year. It has not currently been designated as the next LTS (and my personal guess is that it won't be).

**Comment by paulidale** [comment]
I also expect some manner of support for the 3.1 FIPS 140-3 validation to be available.  Validations sunset after five years typically which is longer than 3.1 will be supported for (even if it were a LTS release).

As for what this will be, I've no idea.  The management committee is aware of this but haven't discussed it yet.
