### ISSUE TITLE
OpenSSL legacy providers can't be loaded on Windows

### ISSUE THREAD

**Issue by sdrilba** [openssl/openssl#20526]
Hi,

I am using OpenSSL on Windows, and trying to simply assess if a remote server has old ciphers (RC4) enabled.

My current OpenSSL version is v3.0.8. I am not re-compiling the software with modified sources, just trying to use the regular installed Win64-OpenSSL with legacy provider.
OpenSSL is installed in the following directory : C:\Program Files\OpenSSL-Win64

I actually already found some help here https://github.com/php/php-src/issues/9890 but it is not enough in my case. 

I've modified my OpenSSL configuration file to add and activate the legacy provider. I've also configured the OPENSSL_MODULES environment variable to find the legacy dll (in its default post-install location, under C:\Program Files\OpenSSL-Win64\bin).

Thanks to that, I can actually run this :
```
>openssl list -providers -provider legacy

Providers:
  legacy
    name: OpenSSL Legacy Provider
    version: 3.0.8
    status: active
```

However, if I run only "openssl list -providers", only the default one is listed. And if I try this : 
```
>openssl ciphers -provider legacy -v

6C1F0000:error:0A0000A1:SSL routines:SSL_CTX_new_ex:library has no ciphers:ssl\ssl_lib.c:3290:
```
I get this error saying the legacy library has no ciphers.

Note that I might be confused by the fact that there are 2 configurations files : 
- One under C:\Program Files\OpenSSL-Win64\bin, named openssl.cfg
- One under C:\Program Files\OpenSSL-Win64\bin\cnf, named openssl.cnf
To be sure, I modified both in the same way, but I have no clue which one is used. I attached the "openssl.cfg" (after changing its extension to txt to be accepted by GitHub) to the current issue.
[openssl.txt](https://github.com/openssl/openssl/files/10992720/openssl.txt)

I am not a developer, so I hope this issue still belongs here, but I really didn't find anyone having the same issue as me, despite having done the installation as "standard" as I could :) 
Thank you for your help.

**Comment by t8m** [comment]
You have to use both legacy and default providers (i.e., `-provider default -provider legacy`). The legacy provider by itself is not sufficient to make any SSL connection. 

Also to enable the RC4 ciphersuites you need to use `RC4@SECLEVEL=0` as the cipherstring.

**Comment by t8m** [comment]
And I've forgot to add - the `enable-weak-ssl-ciphers` option has to be enabled during the build of the openssl library.

**Comment by sdrilba** [comment]
Thank you for your very quick answer ! Alright I understand I need to use both providers in conjunction. 
But judging from your 2d answer, I would actually need to re-build my own OpenSSL bin ?

Just to give more insights of my understanding, I just tried this :
```
>openssl s_client -connect <myserver>:443 -provider default -provider legacy -cipher RC4-MD5@SECLEVEL=0
Call to SSL_CONF_cmd(-cipher, RC4-MD5@SECLEVEL=0) failed
103D0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl\ssl_lib.c:2760:
```

Would this command work if I re-build OpenSSL and enable the ``enable-weak-ssl-ciphers`` as you mentioned ? Or I am still missing something in the typo ?

**Comment by levitte** [comment]
> Would this command work if I re-build OpenSSL and enable the `enable-weak-ssl-ciphers` as you mentioned ? Or I am still missing something in the typo ?

That would help, yes.

**Comment by mattcaswell** [comment]
That command works just fine on my build with "enable-weak-ssl-ciphers" (note though if the server supports TLSv1.3 you will negotiate that instead and not use the RC4-MD5 ciphersuite - use "-no_tls1_3" to suppress it).

**Comment by sdrilba** [comment]
Great, thank you all for your help. I managed to build OpenSSL with the  ``enable-weak-ssl-ciphers`` and it looks like it works well now :)

**Comment by ezekiel201997** [comment]
How to enable the enable-weak-ssl-ciphers in openssl

**Comment by mattcaswell** [comment]
> How to enable the "enable-weak-ssl-ciphers" in openssl?

This is an option at OpenSSL compile time. You pass it to the Configure script. Refer to INSTALL.md in the OpenSSL source code distribution for details.
