### ISSUE TITLE
I want to use this code to read in and output the private key file, but it runs with some errors

### ISSUE THREAD

**Issue by ABSllk** [openssl/openssl#20549]
```
#include <openssl/pem.h>
#include <openssl/decoder.h>
#include <openssl/encoder.h>
#include <openssl/applink.c>
#include <openssl/provider.h>
#include <openssl/err.h>
#include <stdio.h>

int main() 
{
    const char* pass="123456";
    OSSL_PROVIDER *prov = OSSL_PROVIDER_load(NULL, "default");
    if (prov == NULL) 
    {
        ERR_print_errors_fp(stderr);
        return 1;
    }

    EVP_PKEY* pkey=NULL;

    BIO* in=BIO_new_file("client.pem","r");
    OSSL_DECODER_CTX* dctx=OSSL_DECODER_CTX_new_for_pkey(&pkey,"PEM",NULL,"text",OSSL_KEYMGMT_SELECT_ALL,NULL,NULL);
    if(dctx == NULL) 
    {
        ERR_print_errors_fp(stderr);
        return -1;
    }

    if(!OSSL_DECODER_CTX_set_passphrase(dctx,(const unsigned char*)pass,strlen(pass))) 
    {
        ERR_print_errors_fp(stderr);
        return -2;
    }

    if(!OSSL_DECODER_from_bio(dctx,in)) 
    {
        ERR_print_errors_fp(stderr);
        return -3;

    }

    BIO* mem=BIO_new(BIO_s_mem());
    OSSL_ENCODER_CTX* ectx=OSSL_ENCODER_CTX_new_for_pkey(pkey,OSSL_KEYMGMT_SELECT_ALL,"PEM","text",NULL);
    if(ectx == NULL) 
    {
        ERR_print_errors_fp(stderr);
        return -4;
    }

    if(!OSSL_ENCODER_to_bio(ectx,mem)) 
    {
        ERR_print_errors_fp(stderr);
        return -5;
    }

    char* data;
    long len=BIO_get_mem_data(mem,&data);
    printf("%.*s\n",(int)len,data);

    OSSL_ENCODER_CTX_free(ectx);
    OSSL_PROVIDER_unload(prov);
    BIO_free(mem);
    EVP_PKEY_free(pkey);

    return 0;
}
```

The wrong message is:
E01B0000:error:1E000066:DECODER routines:OSSL_DECODER_from_bio:reason(102):crypto\encode_decode\decoder_lib.c:59:No decoders were found. For standard decoders you need at least one of the default or base providers available. Did you forget to load them?

I try to search online , but it still can't working.

**Comment by mattcaswell** [comment]
Refer to the man page for `OSSL_DECODER_CTX_new_for_pkey()`:

https://www.openssl.org/docs/man3.1/man3/OSSL_DECODER_CTX_new_for_pkey.html

In particular the args to that function are:

```` C
OSSL_DECODER_CTX *
OSSL_DECODER_CTX_new_for_pkey(EVP_PKEY **pkey,
                              const char *input_type,
                              const char *input_struct,
                              const char *keytype, int selection,
                              OSSL_LIB_CTX *libctx, const char *propquery);
````

The fourth arg is `keytype`. Typical examples of a keytype might be "RSA", "DSA", "EC", "ED25519", etc. You can also use the `NULL` pointer for this value (which means "any" keytype). You have set it to "text" - but this is not a valid keytype. OpenSSL is searching all available providers for a decoder that can support the "text" keytype - but it can't find any and is thus giving the "No decoders were found" error message.

**Comment by ABSllk** [comment]
> Refer to the man page for `OSSL_DECODER_CTX_new_for_pkey()`:
> 
> https://www.openssl.org/docs/man3.1/man3/OSSL_DECODER_CTX_new_for_pkey.html
> 
> In particular the args to that function are:
> 
> ```c
> OSSL_DECODER_CTX *
> OSSL_DECODER_CTX_new_for_pkey(EVP_PKEY **pkey,
>                               const char *input_type,
>                               const char *input_struct,
>                               const char *keytype, int selection,
>                               OSSL_LIB_CTX *libctx, const char *propquery);
> ```
> 
> The fourth arg is `keytype`. Typical examples of a keytype might be "RSA", "DSA", "EC", "ED25519", etc. You can also use the `NULL` pointer for this value (which means "any" keytype). You have set it to "text" - but this is not a valid keytype. OpenSSL is searching all available providers for a decoder that can support the "text" keytype - but it can't find any and is thus giving the "No decoders were found" error message.

Thank you, it worked, the error also occurred with the OSSL_ENCODER_CTX_new_for_pkey()

**Comment by tom-cosgrove-arm** [comment]
(updated title to improve searchability)
