### ISSUE TITLE
X509_VERIFY_PARAM inh_flags member not exposed in 1.1.0

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#2054]
The `X509_VERIFY_PARAM_inherit` function uses the member `inh_flags` to change behaviour between inheriting/overwriting/defaulting/etc.
However since 1.1.0 there is no longer a way to change `inh_flags`, as the structure is now opaque with no method to edit the member.

Note: the values for the flag (`X509_VP_FLAG_*`) are still available.

Related: https://github.com/wahern/luaossl/commit/e9ecd299628b2af6a8aa74ce7956bb7ae902f69d

**Comment by richsalz** [comment]
So you need this?
```
void X509_VERIFY_PARAM_set_inh_flags(X509_VERIFY_PARAM *src, uint32_t flags);
```

**Comment by daurnimator** [comment]
Sort of: in some cases you need to 'or' with existing flags: in others you need to set explicitly.
In which case, I guess the simple solution is to also add 
```C
uint32_t X509_VERIFY_PARAM_get_inh_flags(X509_VERIFY_PARAM *src);
```

**Comment by richsalz** [comment]
commit a47bc28 in master and 6212179 in 1.1.0.
