### ISSUE TITLE
OSSL_PROVIDER_load(0, "fips") failed on Windows 10

### ISSUE THREAD

**Issue by tbswork1** [openssl/openssl#20559]
I use the same code provided in the example, but always get null `fips`. I use OSSL_PROVIDER_set_default_search_path() to specify a path where I put fips.dll and fipsmodule.cnf, but it doesn't help.

 ```
#include <openssl/provider.h>

int main(void)
{
    OSSL_PROVIDER *fips;
    OSSL_PROVIDER *base;

    fips = OSSL_PROVIDER_load(NULL, "fips");
    if (fips == NULL) {
        printf("Failed to load FIPS provider\n");
        exit(EXIT_FAILURE);
    }
    base = OSSL_PROVIDER_load(NULL, "base");
    if (base == NULL) {
        OSSL_PROVIDER_unload(fips);
        printf("Failed to load base provider\n");
        exit(EXIT_FAILURE);
    }

    /* Rest of application */

    OSSL_PROVIDER_unload(base);
    OSSL_PROVIDER_unload(fips);
    exit(EXIT_SUCCESS);
}
    ```

**Comment by paulidale** [comment]
Did you run fipsinstall as per the security policy?
Try printing the error stack to get a better idea as to what failed.

**Comment by tbswork1** [comment]
This is not mentioned in [https://www.openssl.org/docs/man3.0/man7/fips_module.html](url). But I run `fipsinstall` and it created a file same as `fipsmodule.cnf` with additional values `install-version` and `tls1-prf-ems-check`. 

Below is the error stack when `OSSL_PROVIDER_load()` returns null:

```
Failed to load FIPS provider
FC280000:error:1C8000D5:Provider routines:SELF_TEST_post:missing config data:providers\fips\self_test.c:354:
FC280000:error:1C8000E0:Provider routines:ossl_set_error_state:fips module entering error state:providers\fips\self_test.c:464:
FC280000:error:1C8000D8:Provider routines:OSSL_provider_init_int:self test post failure:providers\fips\fipsprov.c:724:
FC280000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:924:name=fips
```

**Comment by tbswork1** [comment]
`openssl version -d` gives `OPENSSLDIR: "C:\Program Files\Common Files\SSL"`. 
Put the fipsmodule.cnf in there, remove line `activate = 1`.  Rerun the code, and it is still giving the same error.

Also, what if the app is distributed and installed on another machine, i.e., do we need to distribute the `openssl.cnf` and `fipsmodule.cnf` as well?

**Comment by t8m** [comment]
The openssl.cnf must contain `.include` to include the fipsmodule.cnf with full path.

And yes, both openssl.cnf and fipsmodule.cnf must be installed at paths where expected by the OpenSSL library and the .include statement respectively on the machine where the application is to be executed.

**Comment by t8m** [comment]
Also, to comply with the FIPS security policy of the module, the fipsinstall command actually must be run on the target machine during the installation. The fipsmodule.cnf must be created by the fipsinstall command on the target machine otherwise you do not comply with the FIPS security policy.

**Comment by tbswork1** [comment]
@t8m How can we generate the fipsmodule.cnf on end-users' machine? Can we distribute the openssl.exe executable in the software package (commerical)?

**Comment by t8m** [comment]
Yes, sure, the Apache 2 license does not restrict distribution of the executable in any other way than of the library.

**Comment by mattcaswell** [comment]
> Yes, sure, the Apache 2 license does not restrict distribution of the executable in any other way than of the library.

Note that applies to an executable that you have built yourself. If you are using a third party distributed exe then they could (in theory) apply additional licence terms. In that case check with the third party - or just build it yourself.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by t8m** [comment]
Closing as the questions were answered.

**Comment by andriy-fd** [comment]
@t8m I have a question regarding the statement:
"Also, to comply with the FIPS security policy of the module, the fipsinstall command actually must be run on the target machine during the installation. The fipsmodule.cnf must be created by the fipsinstall command on the target machine otherwise you do not comply with the FIPS security policy."

There was another comment found: 
https://mta.openssl.org/pipermail/openssl-users/2022-February/014887.html

So just would like to double check what approach is correct. The one that is described here, or the one that is described in mta.openssl.org?

**Comment by t8m** [comment]
> @t8m I have a question regarding the statement: "Also, to comply with the FIPS security policy of the module, the fipsinstall command actually must be run on the target machine during the installation. The fipsmodule.cnf must be created by the fipsinstall command on the target machine otherwise you do not comply with the FIPS security policy."
> 
> There was another comment found: https://mta.openssl.org/pipermail/openssl-users/2022-February/014887.html
> 
> So just would like to double check what approach is correct. The one that is described here, or the one that is described in mta.openssl.org?

It depends on how strictly you need to adhere to the FIPS rules. In strict sense you need to follow the security policy which says use the fipsinstall command on the target machine. The mail above describes something that is still compliant with the FIPS requirement that selftests must run on the target machine. It is not compliant with the requirement to strictly follow the security policy installation instructions.
