### ISSUE TITLE
OBJ_nid2obj returns NULL for NID_undef in 3.1.0

### ISSUE THREAD

**Issue by chaen** [openssl/openssl#20555]
Hi,

I noticed a different behavior between `Openssl3.0.0` and `Openssl3.1.0`  regarding `OBJ_nid2obj`
In case the input value is `NID_undef`, starting from `3.1.0`, the return value is `NULL`, while it used to not be, and translate into `UNDEF` when using `OBJ_nid2sn`

```c
#include <openssl/x509.h>

int main(){
  const ASN1_OBJECT * obj = OBJ_nid2obj(NID_undef);
  printf("obj %p\n", obj);
}
```

Result with `3.0.0`

```
obj 0x7f8cc53e8060 
```

Result with `3.1.0`

```
obj (nil)
```

That change of behavior seems to come from a commit related to thread safety 

https://github.com/openssl/openssl/commit/196c57ee6a956169aadbd760c13110671773f371#diff-9c1ebb22ae4d666ae0cdda6014f30ec0c2e5090fc8e549200988274a8e550904L221-L237

Is that change of behavior expected ? 

Thanks ! 
Chris

**Comment by t8m** [comment]
Fix in #20556
