### ISSUE TITLE
Replacement for EVP_dss() & EVP_ecdsa() digest functions in OpenSSL 3.0

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#20575]
I'm migrating openSSL from 1.0.2z to openSSL 3.0. I'm not able to find the replacement of EVP_dss() & EVP_ecdsa() 

These were earlier declared in evp.h, now with openssl 3.0 these function are missing, what should I  do now.

**Comment by t8m** [comment]
Could you please show us in what context do you use these EVP digest methods? They aren't useful anymore.

**Comment by slontis** [comment]
dss was removed 9 years ago..
The docs state "The link between digests and signing algorithms was fixed in OpenSSL 1.0 and later, so now EVP_sha1() can be used with RSA and DSA; there is no need to use EVP_dss1() any more

**Comment by slontis** [comment]
See doc/man3/EVP_DigestSignInit.pod
There are signature demos in demos/signature

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
