### ISSUE TITLE
DTLS_set_timer_cb() is being stopped after some interval in openssl 1.1.1k version.

### ISSUE THREAD

**Issue by MonicKumar** [openssl/openssl#20577]
As far as I know, OpenSSL maintains an internal count of the number of timer timeouts that have occurred. If it get more than 12 then it gives up (OpenSSL stops sending "client hello" packets).

Is there a way to read the value of this internal counter?, if yes, kindly tell me API to be used.
Somehow i want to get to know that OpenSSL has stopped sending "client hello" packets.
I'm aware that SSL_get_error() will return SSL_ERROR_SSL for the above case. But it is not helping for my scenario.
I want to know exactly OpenSSL has stopped sending "client hello" packets.

**Comment by t8m** [comment]
No, there is no API currently to get the number of counts.

The SSL_R_READ_TIMEOUT_EXPIRED error is put on the error stack in case the count reaches 12.

**Comment by MonicKumar** [comment]
Thanks for your reply.

 Could you please suggest any optimized way of triggering OpenSSL to send "client hello" packet infinitely ?.

 In may case DTLS server can come up at any time, so whenever it comes up it should able to make connection with DTLS client with the help of continuous "client hello" packet.

**Comment by MonicKumar** [comment]
code flow:
ret = DTLSv1_handle_timeout(ssl);
if (ret > 0) {
sslerr = ERR_get_error();
}


in the above code , i'm getting sslerr value as "336847160" , does it has any unique meaning?

**Comment by MonicKumar** [comment]
Thanks for your support.
I got solution from the below ticket
https://github.com/openssl/openssl/issues/20459

Kindly close this issue.
