### ISSUE TITLE
[AES-GCM-NO-AUTH] New variant of AES-GCM allowing random data in the authentication tag

### ISSUE THREAD

**Issue by hselasky** [openssl/openssl#20584]
Hi,

TLS v1.2 and TLS v1.3 appends an authentication tag to every TLS record protecting against forging data in TLS records. 

In large scale applications transferring media content mostly, the authentication tag is expensive to compute. Especially in the case of TCP-retransmission. Even if accelerated by hardware, it can multiply the amount of traffic towards the memory, where the TLS record resides, because of the need to re-read previous data, in order to correctly re-compute the final TLS authentication tag. The AES-GCM XOR pattern can easily be forwarded by only using the length information of the segment to skip and no actual data needs to be re-read from memory!

The need of media content distributors is not the same as for typical banking companies. The purpose of using encryption for media content is to not reveal what contents the users are actually browsing. The authentication tag then has no purpose, because data is already protected by the IP checksum field, and this is more than enough for media content distribution, like video streaming.

Therefore I suggest that authentication of TLS records becomes negotiable, and that a no-auth mode is provided for AES-GCM.

Maybe this only means a new crypto codec value is needed, AES-GCM-NO-AUTH, for example.

Comments are welcome!

**Comment by t8m** [comment]
I think this is a wrong forum to propose such new TLS protocol modifications/features. The IETF TLS working group is the right place to discuss such things. https://datatracker.ietf.org/group/tls/about/

What you're proposing is an AES-CTR in fact - it's a nonsense to call such mode AES-GCM as the GCM difference from the CTR mode is the authentication where you want no authentication.

**Comment by hselasky** [comment]
@t8m: Thank you for your input about calling this AES-CTR. I'll make a request for comments at ietf.org instead. I was not sure where to start :-)
