### ISSUE TITLE
DH ephemeral history challenges 

### ISSUE THREAD

**Issue by jackokring** [openssl/openssl#20598]
Given hacks like LTT of recent, the session key of many sites is not secure enough for general operation by suckers.

Storing the DH channel keys used for a request in an encrypted form (or proxy for such) supplying the decrypt key to the site for later recall to decrypt a challenge "provide nth last ephemeral" (the encrypt key can be thrown away).

Any page request could then be challenged such that the browser (or better yet the socket layer) has to supply the last used ephemeral. As the ephemerals  are more unique to origin, an eventual collision from origin synchronization errors can flag as bad to invalidate sessions. It might need coordination on how the SSL supplies redirects to login (304?).

It might then reduce such attacks to DDoS, and rate limiting and statistical packet culling.

**Comment by jackokring** [comment]
So a 304:

Browser goes to home domain with default for page. Supplies cookies as a differential cookie set may be useful for filtering later (maybe an extra diff split cookie value must be supplied?). So how would the site do the invalidate? I'm imagining something like a 404.html, but the browser doesn't see it as it gets a 304 (keeping the webserver out of the loop, and it doesn't need a URL in the response). An execution hook? A localhost proxy 304 request? It's likely a CGI bin thing.

Any ideas for the service request URL? At some point the SSL layer is likely to want to notify some tracking URL, so the `wget` is like going to be in there.

**Comment by t8m** [comment]
IMO there are better places for discussing such potential protocol improvements such as the IETF TLS working group mailing list. This is nothing OpenSSL-specific, so it should be discussed within broader audience.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by t8m** [comment]
Closing as this issue is not OpenSSL-specific.
