### ISSUE TITLE
I wonder if DTLS 1.3 is supported this year，I think it's already necessary

### ISSUE THREAD

**Issue by redoriental** [openssl/openssl#20605]

**Comment by redoriental** [comment]
Now the QUIC protocol has begun to grow rapidly

**Comment by paulidale** [comment]
There is currently no time frame for the core team to add DTLS 1.3 to OpenSSL.  It is on the list of future things we want but not at a sufficiently high priority to mandate the team doing it as a matter of urgency.

Now, if a third party came along with most of an implementation, we would be very interested in getting it in.

**Comment by redoriental** [comment]
Do you know of any programs that support dtls1.3, which I really need

**Comment by meins111** [comment]
wolfSSL is supposed to have at least a beta version of DTLS 1.3 as of november 22.

+1 for the feature request though.

**Comment by redoriental** [comment]
thank you

**Comment by redoriental** [comment]
When this project comes out, I will use it as soon as possible

**Comment by redoriental** [comment]
> 截至 1 月 3 日，wolfSSL 应该至少有一个 DTLS 22.<> 的测试版。
> 
> 不过功能请求为 +1。

Can't this linked file be implemented（ https://github.com/wolfSSL/wolfssl-examples/blob/master/dtls/server-dtls13.c ）

**Comment by redoriental** [comment]
> 截至 1 月 3 日，wolfSSL 应该至少有一个 DTLS 22.<> 的测试版。
> 
> 不过功能请求为 +1。

I don't know if this linked file is useful（ https://github.com/wolfSSL/wolfssl-examples/blob/master/dtls/server-dtls13.c ）
