### ISSUE TITLE
Suspicious change to `github.com` server

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#20601]
This morning when pushing to `github.com`  I got warnings that the SSH key or IP address of `github.com` changed:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /home/david/.ssh/known_hosts to get rid of this message.
Offending RSA key in /home/david/.ssh/known_hosts:1
  remove with:
  ssh-keygen -f "/home/david/.ssh/known_hosts" -R "github.com"
```
and later, after executing the suggested removal command on `known_hosts`, I got:
```
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.121.3'
Offending key for IP in /home/david/.ssh/known_hosts:24
Matching host key in /home/david/.ssh/known_hosts:68
```
I also experience weird inconsistencies of the 3.0 and 3.1 branches with my local view on them, see https://github.com/openssl/openssl/pull/20277#issuecomment-1483759933.

Is someone impersonating `github.com` or did they make an error replicating servers?

**Comment by BenBE** [comment]
Github updated their SSH key …
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by DDvO** [comment]
> Github updated their SSH key … https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

Thank you - this explains the first issue I reported above, where I meanwhile provide more detail.

Yet according to that blog post
> Only GitHub.com’s RSA SSH key was replaced. No change is required for ECDSA or Ed25519 users.

whereas I also got an SSH warning on the ECDSA host key for `github.com`.

**Comment by DDvO** [comment]
Concerting the repo inconsistency issue I also reported above,
maybe the repo syncing done by OpenSSL is currently hampered by that key change?

**Comment by levitte** [comment]
> Concerning the repo inconsistency issue I also reported above, maybe the repo syncing done by OpenSSL is currently hampered by that key change?

Yes.  https://automation.openssl.org/#/builders/5/builds/3282

I'm fixing now

**Comment by levitte** [comment]
Done

**Comment by DDvO** [comment]
> Done

Thanks - and my recent pushes to the 3.0 and 3.1 branches now shop up :+1:

**Comment by DDvO** [comment]
Side question: 
Isn't there a better way of doing SSH host authentication that would avoid such - rather common - SSH hickups?

**Comment by levitte** [comment]
> Side question:
> Isn't there a better way of doing SSH host authentication that would avoid such - rather common - SSH hickups?

This sort of event should be viewed as extraordinary.  It is, after all, a key revocation following a (possible) key compromise.  I don't know how a key update for that sort of thing would be done without some human control.  To make matters worse, SSH uses a simple key scheme, there's no web of trust, so ensuring *trust* falls squarely into the hands of humans.

**Comment by DDvO** [comment]
>  To make matters worse, SSH uses a simple key scheme, there's no web of trust, so ensuring trust falls squarely into the hands of humans.

Yeah, this appears to be the root problem.
As long as SSH does not make use of some host name PKI, users get confused, annoyed, ...
