### ISSUE TITLE
Extract PEM from .p12 file legacy

### ISSUE THREAD

**Issue by GillesT78** [openssl/openssl#20607]
Hello

I want to create .pem from .p12 file with same encoding if I use "-legacy" in OpenSSL 3.0 (or Open SSL 1.1)
Is there a possibility to not use -legacy and set options (I think) 3DES_CBC for keys, RC2_CBC for certificate in command line ?

openssl.exe pkcs12 -in cert.p12 -passin "pass:xxx" -passout "pass:xxxx" -out cert.pem (-legacy)

As my goal is to manage this extraction in C language, I don't find how to set 3DES_CBC for keys, RC2_CBC for certificate with PKCS12_parse. Is it possible ?

Last question, is it possible to retrieve the type of encoding (3DES_CBC, RC2_CBC, ...) from PEM file ?

Regards
Gilles

**Comment by GillesT78** [comment]
Hello

Thank you for your response.
You are right certificate are not encrypted in the PEM, and also you are right, I want to replicate in C the parsing that pkcs12 command does.
I have a .p12 créated with OpenSSL 1.0. If I parse it with OpenSSL 3.1 with option "-legacy", I can extract PEM, but without -legacy, I have an error  Error outputting keys and certificates
B8610000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto\evp\evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

I don't find how to set algorithm in C language while extracting PEM, and is there a way to retrieve the algorithm used inside the .p12 (RC2-40-CBC , ...) ?
I don't want to use legacy library

Gilles

**Comment by t8m** [comment]
You have to load the legacy provider to be able to use the RC2-40-CBC when parsing the PKCS12 file. There is no way around that. However the legacy provider can be loaded only temporarily while you are parsing the file, you can then unload it.

**Comment by t8m** [comment]
If this is used just for encrypting the certificate, then it is OK because the certificate is usually a public information anyway. However if this algorithm encrypts also the private key then this means the private key basically unprotected.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by t8m** [comment]
Closing as the questions were answered.
