### ISSUE TITLE
openssl pkcs12 with nomac option

### ISSUE THREAD

**Issue by WilburZjh** [openssl/openssl#20617]
I am looking at this page of docs -> https://www.openssl.org/docs/man3.0/man1/openssl-pkcs12.html. Its mentioned in the `nomac` option that 

`Do not attempt to provide the MAC integrity. This can be useful with the FIPS provider as the PKCS12 MAC requires PKCS12KDF which is not an approved FIPS algorithm and cannot be supported by the FIPS provider.`

But as far as I know, FIPS does support MAC for pkcs12 keystore, could you provide the reference on which PKCS12 MAC algorithm openssl is used so I can double check on this in case Im wrong. Thanks in advance.

**Comment by slontis** [comment]
https://github.com/openssl/openssl/issues/19997

**Comment by WilburZjh** [comment]
Thanks for the information. My openssl version is `OpenSSL 1.1.1k  FIPS 25 Mar 2021`. May I know what is the difference if I create a pkcs12 keystore with and without the `nomac` option? It seems that I can create two keystores successfully within a fips version openssl. Does that mean the mac value is calculated in a fips version openssl?

**Comment by slontis** [comment]
Upstream OpenSSL does not have a 1.1.1 FIPS version. 
If you are using a third party OpenSSL version  such as Redhat, which is not a question that belongs here.
I can only comment on OpenSSL 3.0 FIPS which does not allow the integrity check, since the algorithm is not FIPS. Hence to need for the nomac option.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
