### ISSUE TITLE
Asymmetric keys zeroisation

### ISSUE THREAD

**Issue by Jayukie** [openssl/openssl#20618]
Hi, 
It seems that the asymmetric keys created with EVP_PKEY structure are not correctly zeroised by EVP_PKEY_free() function. For example, the n, e, p, q, etc values of RSA.  
Is there a method that can correctly reset relevant parameters to 0 ? The version I use is openssl 3.0.0 (FIPS certified version).
Thanks~

**Comment by slontis** [comment]
OpenSSL only zeroizes secrets and private values. It does not do the same for public values (it is not necessary).
If you put a debug breakpoint in RSA_free() you will see that it gets called from EVP_PKEY_free() which does..

````
    BN_free(r->n);
    BN_free(r->e);
    BN_clear_free(r->d);
    BN_clear_free(r->p);
    BN_clear_free(r->q);
    BN_clear_free(r->dmp1);
    BN_clear_free(r->dmq1);
    BN_clear_free(r->iqmp);
````

**Comment by Jayukie** [comment]
Which openssl version does this feature add? In addition, do ecdsa and dsa have corresponding function implementations?

**Comment by slontis** [comment]
This is the purpose of EVP_PKEY. It is a layer over the top of all low level keys that has methods for each key type including the free method. So yes all key types  including EC and DSA work this way. As far as I am aware all versions do this.

**Comment by beldmit** [comment]
@slontis if I understand correctly, FIPS-140-3 has requirements to cleanse public key data also, at least in some cases - at least our lab requested it for us.

**Comment by Jayukie** [comment]
Yes,  the FIPS 140-3 requirement requires to zeroize both public and private parameter.

**Comment by slontis** [comment]
Sounds like another stupid change.. @paulidale

**Comment by paulidale** [comment]
We've not been asked for this.  At least not yet.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
