### ISSUE TITLE
EVP_PKEY_get_bn_param() does not zeroize temporary buffer

### ISSUE THREAD

**Issue by iamnotacake** [openssl/openssl#20626]
Function `EVP_PKEY_get_bn_param()` (see [current implementation](https://github.com/openssl/openssl/blob/864c70e43ea5f1d7fe20bfea457e53e79fd46b6e/crypto/evp/p_lib.c#L2141-L2181)) uses temporary buffer (on stack or heap allocated) to store serialized bignum, but after deserializing it into BIGNUM*, the buffer is not erased and may contain sensitive data (private key parts) for undefined amount of time.

Simple solution may always erase used buffer before returning result, something like

```c
err:
    if (buf) {
        if (OSSL_PARAM_modified(params)) {
            OPENSSL_clear_free(buf, buf_sz);
        } else {
            OPENSSL_free(buf);
        }
    } else if (OSSL_PARAM_modified(params)) {
        // FIXME use more reliable function for filling the buffer
        memset(buffer, 0, params[0].data_size);
    }
    return ret;
```

and optionally use `OPENSSL_secure_{zalloc,clear_free,free}` instead of non-`secure` functions

Better solution may erase only if requested param is a private part (i.e. EC "priv", RSA "d", "factor1", "factor2" etc). But I'm not sure it's worth efforts and will be faster than always rewriting buffers. After all, is there any easy and fast way to find out whether requested param is considered private?

Wanted to open a PR, but since ICLA is not submitted yet, here's an issue with proposed solution instead.

**Comment by t8m** [comment]
You can open a PR and send ICLA after that, there is no problem with that.

I do not think there is a problem with doing the erasure for any BN param.

BTW the memset() should be OPENSSL_cleanse() instead.

**Comment by iamnotacake** [comment]
Now the PR is opened and ICLA submitted... I have a couple of thoughts regarding new API.
Two methods of extracting bignum property from a key are available:
1. Using `EVP_PKEY_get_bn_param()` to get `BIGNUM*`
2. Using `EVP_PKEY_get_params()` to fill a buffer with the bytes of that same bignum

But either one has issues

1. Overhead. The `EVP_PKEY*` most likely contains some `BIGNUM*` under the hood, but instead of cloning it with `BN_dup()`, `EVP_PKEY_get_params()` is called, it fills temporary buffer, then another `BIGNUM*` is created from it, then we need to do some cleanup

2. No control over byte order and padding. It uses native byte order which means we can't rely in it when serializing keys in custom format. It also won't add padding if the buffer is too big and there's no way to change this

 I imagine `EVP_PKEY_get_params()` much more useful if it had a couple of flags for bignum params:
* Big endian - if set, number is serialized in big endian byte order
* Little endian - if set, number is serialized in little endian byte order
* Can't set big endian + little endian at the same time; setting none will use native order
* Pad - whether to add padding bytes if provided buffer is too large

Similar story with `EVP_PKEY_fromdata()`. It is like `EVP_PKEY_get_params()` and you can't tell it which byte order to use when deserializing a bignum. As a result, one has to use param builder (`OSSL_PARAM_BLD`). But this builder also has the overhead: as far as I understood, `OSSL_PARAM_BLD_push_BN()` simply serializes bignum into a temporary buffer in proper byte order so that `EVP_PKEY_fromdata()` can deal with it. Plus, at least two allocations for `OSSL_PARAM_BLD*` and `OSSL_PARAM*`.

Right now struct `OSSL_PARAM` don't even have any kind of flags field, so it's quite unlikely that these ideas will come to life. Just wanted to shame my thoughts. Being able to use on stack params and feed serialized bignums right into `EVP_PKEY_fromdata()` may have visible effect in case a custom crypto library heavily uses custom key deserialization. Meanwhile, other types of params (UTF8 strings, octet strings etc) seem to be easy to use with `OSSL_PARAM` array on stack .

**Comment by paulidale** [comment]
The design of OSSL_PARAM didn't have these goals.  The intention was to provide a stable and simple API to talk to providers.  Due to our API stability requirements, changing function signatures isn't possible so we needed another way to change arguments to calls.

Bignums did turn out to be the nastiest part which is unfortunately.  They shouldn't need to be copied across the provider boundary all that often, so the performance hit is hopefully not too great.

**Comment by iamnotacake** [comment]
Well, since the PR was merged, this issue could be closed. Thank you for attention
