### ISSUE TITLE
Order of certs produced by openssl pkcs7 -inform DER -print_certs

### ISSUE THREAD

**Issue by jmssil** [openssl/openssl#20642]
I created a dummy chain of 4 levels of certificates with XCA.

Then I produced the .p7b of the chain.

If I run:

openssl pkcs7 -inform DER -in chain.p7b -print_certs

it outputs the certificates in the following order:

leaf
int2
int1
root

Is this intended?

Should the order be reversed?

Should it depend on the DER?

Thanks.

**Comment by paulidale** [comment]
They are printed in the order returned from the load.

**Comment by jmssil** [comment]
Thanks.
