### ISSUE TITLE
OSSL_HTTP_transfer ignores args from prctx

### ISSUE THREAD

**Issue by michal0722** [openssl/openssl#20641]
Function `OSSL_HTTP_transfer` from http_client.c ignores some arguments (e.g. path, content_type) from **prctx** structure. My version of OpenSSL is 3.0.8 .

**Comment by t8m** [comment]
@DDvO might want to look

**Comment by michal0722** [comment]
I used this function to exchange **OCSP** (Online Certificate Status Protocol) requests and responses on the client side. I assumed that the connection is set by callig using  `OCSP_sendreq_new` and  `OSSL_HTTP_REQ_CTX_set1_req`, which I called before the `OSSL_HTTP_transfer` function.

**Comment by DDvO** [comment]
Please read the doc:
```
OSSL_HTTP_transfer() exchanges an HTTP request and response
over a connection managed via I<prctx> without supporting redirection.
It combines OSSL_HTTP_open(), OSSL_HTTP_set1_request(), OSSL_HTTP_exchange(),
and OSSL_HTTP_close().
If I<prctx> is not NULL it reuses any open connection represented by a non-NULL
I<*prctx>.  It keeps the connection open if a persistent connection is requested
or required and this was granted by the server, else it closes the connection
and assigns NULL to I<*prctx>.
The remaining parameters are interpreted as described for OSSL_HTTP_open()
and OSSL_HTTP_set1_request(), respectively.
The caller is responsible for freeing the BIO pointer obtained.
```
You do not need to use the low-level context setup functions.
Just pass in a pointer to an `OSSL_HTTP_REQ_CTX *` pointer that is initialized with `NULL`,
and `OSSL_HTTP_transfer()` will manage the context for you.

**Comment by DDvO** [comment]
@michal0722 does this solve the question/issue for you?
If so, please close.
