### ISSUE TITLE
Build errors from master and 3.1.0 when using ./config --release threads

### ISSUE THREAD

**Issue by matthegg5** [openssl/openssl#20655]
Hello

I'm trying to build CPython on a basic GNU system that uses the FreeBSD 10.0 kernel. The build for CPython fails because it says it requires thread-safe OpenSSL.

I'm therefore building OpenSSL from scratch. Doing some research, it sounded like running the command "./config --release threads" is the solution, but the problem is this presents quite a few build reference errors. Please see attached log, this is what happens when I run 'make' after the above command.

Note that if I keep everything as default, OpenSSL compiles fine, but the CPython issue remains.

There is no package or repository available for this particular system, assume it to be similar to an LFS.

Thank you.

[openssl-errors-1.txt](https://github.com/openssl/openssl/files/11112950/openssl-errors-1.txt)

**Comment by t8m** [comment]
The problem is that this system probably requires some fine-tunnings in the build options. Especially it might require -lpthread or something.

As this is not a regular system I do not think this can be counted as a bug that we do not support it.

**Comment by matthegg5** [comment]
Would that be `./configure -Ipthread`?

Yeah that's fair, I originally wrote it as a question but the text suggested build errors to be a bug. 

I tried rebuilding it using a different guide which located it in /opt/openssl/bin and set the $LD_LIBRARY_PATH variables on login to the correct binary locations for openssl 3.1.0 but still the CPython build complains about it being not thread-safe.

Is the default build using `./configure` not using threading by default?

**Comment by matthegg5** [comment]
Please see attached output of your suggested command.

[openssl-configdata.txt](https://github.com/openssl/openssl/files/11115507/openssl-configdata.txt)

**Comment by t8m** [comment]
Yeah, so the config target as detected by Configure has the threads support disabled because it assumes it is unavailable. What kind of libc do you use?

**Comment by matthegg5** [comment]
`ldd --version` returns `ldd (Debian GLIBC 2.25-2) 2.25`
