### ISSUE TITLE
Is ECDH FIPS-approved in the OpenSSL v3.0?

### ISSUE THREAD

**Issue by afshinpir** [openssl/openssl#20659]
Hi,

I wonder if ECDH in the fips module is fips-approved or not. Because I see it in the security policy, but I don't see it listed in the approved algorithms here:
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282

**Comment by paulidale** [comment]
Table 5 in the [security policy](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4282.pdf) lists EdDSA as non-approved.

Originally, it was _allowed_ but NIST changed their stance and we submitted a change to the policy in January to move it to non-approved.  This change was published earlier this month.

**Comment by afshinpir** [comment]
@paulidale My question was regarding ECDH (key exchange) not EdDSA (signature as far as I know).

**Comment by paulidale** [comment]
ECDH is allowed I believe.

**Comment by slontis** [comment]
This primitive is used in the Key Agreement Scheme primitive - See SP800-56A section 5.7.1.2
You will also notice that there is a self test for ECDH KAS

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
