### ISSUE TITLE
ssltestlib.c lacks OpenSSL version guard

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#20652]
The problem is described here https://github.com/open-quantum-safe/oqs-provider/issues/132#issuecomment-1489670860
In short, using some source files from the OpenSSL master tree breaks compilation completely. Here's the proposed fix:
```diff
diff --git a/test/helpers/ssltestlib.c b/test/helpers/ssltestlib.c
index 94100b9ca4..e65b8cdd45 100644
--- a/test/helpers/ssltestlib.c
+++ b/test/helpers/ssltestlib.c
@@ -1179,7 +1179,12 @@ int create_bare_ssl_connection(SSL *serverssl, SSL *clientssl, int want,
              * give the DTLS timer a chance to do something. We only do this for
              * the first few times to prevent hangs.
              */
+#if OPENSSL_VERSION_MAJOR >= 3 && OPENSSL_VERSION_MINOR >= 2
             OSSL_sleep(50);
+#else
+#include <unistd.h>
+            sleep(1);
+#endif /* OpenSSL 3.2.0+ */
         }
     } while (retc <=0 || rets <= 0);
 

```

**Comment by mouse07410** [comment]
@mattcaswell I understand your point - but wouldn't applying something like my proposed patch be simple and cheap enough? **And** it will help the OQS provider (and potentially others who might be in the same boat).

What say you? ;-)

**Comment by t8m** [comment]
The change is confusing and making the code convoluted. Also where such changes start and where they end? IMO much better is for OQS provider, if it really wants to reuse the internal file, to adopt the changes and add the OSSL_sleep() function.

**Comment by mouse07410** [comment]
> The change is confusing and making the code convoluted. 

All this code is supposed to do is ensure that `OSSL_sleep()` is called only if OpenSSL version is 3.2.0 or newer. Hardly confusing?

> Also where such changes start and where they end? 

I'd say they start when a breaking change to the API is made, and end when the API is carved in stone. ;-)

But since you (and not I) are those who'd maintain it, I can't argue too much.

**Comment by baentsch** [comment]
> This looks like a problem for the oqs-provider to solve not the OpenSSL project. ssltestlib.c is a purely internal file used for our own testing. oqs-provider has taken the decision to reuse it for their own purposes - which is fine - but this surely means that it is an oqs-provider problem to solve version incompatibilities like this.

I tend to agree. The tests (with those internal dependencies) are meant to pinpoint low level deficiencies in `oqsprovider` (that would/should have become visible with the (OpenSSL version independent) high level tests). We thus meant them to run primarily in the `openssl` version enabling all `oqsprovider` capabilities (3.2 right now) -- so for now we'll probably simply add a guard against use of these `ssltestlib`-dependent tests in downlevel `openssl` installations. If there'd be utility for those tests in older `openssl` versions we may revise that approach.

**Comment by t8m** [comment]
> I'd say they start when a breaking change to the API is made, and end when the API is carved in stone. ;-)

There was no breaking change in the API made here. Internal source file is not an API.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
