### ISSUE TITLE
Context for Gettable and Settable methods

### ISSUE THREAD

**Issue by afshinpir** [openssl/openssl#20661]
Hi all,

I wonder what happens if I just return a `NULL` from gettable or settable method? Because I'm almost sure that no code in openssl uses these methods to check if it can get or set a value before calling get or set method. I have seen a value is requested in my provider's get methods while I have not mentioned it in my gettable list. I think there are no correct tests regarding gettable and settable methods too. As a result, you see very strange and misleading codes regarding these methods.
As an example, look at this wrapper over signature settable method:
https://github.com/openssl/openssl/blob/bbe9d2de6c643a2c6758fae4274c307943a59624/crypto/evp/signature.c#L381-L390
which is the **only** usage of signature settable which in turn is not used anywhere. As you see, the value of `NULL` is passed as first argument for calling context. Now see its implementation in RSA singature:
https://github.com/openssl/openssl/blob/67bfdfa17bc4ca8e2b819316299bb82748394c45/providers/implementations/signature/rsa_sig.c#L1403-L1411
or here in ECDSA signature:
https://github.com/openssl/openssl/blob/67bfdfa17bc4ca8e2b819316299bb82748394c45/providers/implementations/signature/ecdsa_sig.c#L554-L561
Even though these implementation don't create segmentation fault because of null check, from implementation it is obvious that they expect to get signature context to check `flag_allow_md`, but since value is `NULL`, it never happens.
From what I experienced in developing provider, I noticed that gettable and settable methods are almost useless because they don't affect how openssl works (at least in parts that I have checked till now). 

I think it will be much better to remove the requirement of implementing them at all or at least, provide correct context to them.

**Comment by levitte** [comment]
You might be happier to know that this particular function is also called from `EVP_PKEY_CTX_settable_params()`

Here's the code that performs the call:

https://github.com/openssl/openssl/blob/bbe9d2de6c643a2c6758fae4274c307943a59624/crypto/evp/pmeth_lib.c#L813-L820

**Comment by afshinpir** [comment]
@levitte Sorry about my mistake. I somehow missed this call from ctx. Thanks for the info .
