### ISSUE TITLE
openssl genrsa -aes256 -out server.key 2048  not prompting for pass phrase on Windows 11

### ISSUE THREAD

**Issue by roblatour** [openssl/openssl#20668]
The following command with OpenSSL 3.1 is not prompting for a pass phrase on Windows 11

openssl genrsa -aes256 -out server.key 2048 

downloaded executable from https://kb.firedaemon.com/support/solutions/articles/4000121705#Download-OpenSSL

Also, while a key is generated, the above command simply returns to a new line without an error/warning message.

![ss2](https://user-images.githubusercontent.com/5200730/229373101-cb6082fd-6a8d-4d87-97a8-bb5bd1fcd995.jpg)

**Comment by t8m** [comment]
Are you able to build openssl yourself? Could you please try to reproduce this issue with a build of openssl from sources?

**Comment by t8m** [comment]
Then please report this to the provider of the binaries.

**Comment by roblatour** [comment]
done
________________________________

**Comment by firedaemon-cto** [comment]
Hi @roblatour,

As described in the [Compilation and Build Script](https://kb.firedaemon.com/support/solutions/articles/4000121705#Compilation-and-Build-Script) heading we are currently compiling openssl with the following command line
```
..\Configure %toolset% no-asm no-ssl3 no-zlib no-comp no-ui-console no-autoload-config --api=1.1.0 --prefix="%installdir%" --openssldir="%commoninstalldir%" -DOPENSSL_NO_DEPRECATED
```
It includes `no-ui-console`, which maps to the `OPENSSL_NO_UI_CONSOLE` C macro.

Originally the purpose was to build openssl binaries without unnecessary stuff. However, we discussed this today and I will update our build scripts accordingly.

**Comment by paulidale** [comment]
Looks like this can be closed.

**Comment by firedaemon-cto** [comment]
For the records, FireDaemon Technologies Limited now provides Windows binaries built w/o the `no-ui-console` option:
- OpenSSL 1.1.1t
- OpenSSL 3.0.8
- OpenSSL 3.1.0
- Windows Installer for OpenSSL 3.0.8, 64-bit

@roblatour Thank you for letting us know!
