### ISSUE TITLE
openssl req uses X.509v1 even when using -copy_extensions

### ISSUE THREAD

**Issue by Raincode** [openssl/openssl#20667]
Hi,

I got a bit frustrated when using openssl to create a CSR from an actual certificate.
Probably not the best method, but when using -copy_extensions, I realized the CSR still reads Version 1 (0x00).
I would expect the inclusion of extensions to automatically yield Version 3 (0x02).
There seemed no clear way to specify via command line option the desired X.509 Version field.

When inspecting openssl/apps/req.c, I see the following code, which is the only call to this "set_version" and seemingly explains why Version 1 (0x00) was in the CSR, even when extensions are included:
```
    /* so far there is only version 1 */
    if (!X509_REQ_set_version(req, X509_REQ_VERSION_1))
        goto err;
```

I'd maybe expect something like make_REQ choosing Version 3 (0x02) based on `OPT_COPY_EXTENSIONS` or `ext_copy` somehow indicating that extensions will be included.

What do you think?

_P.S.: req_main seems very long, is that intentional?_

**Comment by davidben** [comment]
There's no such thing as a v3 (or v2) CSR, so this is correct and the suggestion would be wrong. The CSR and certificate versions are not connected to each other and CSR attributes exist in all versions. (CSRs have attributes, not extensions. And then there's one attribute type that carries arbitrary extensions.)

**Comment by Raincode** [comment]
> There's no such thing as a v3 (or v2) CSR, so this is correct and the suggestion would be wrong. The CSR and certificate versions are not connected to each other and CSR attributes exist in all versions. (CSRs have attributes, not extensions. And then there's one attribute type that carries arbitrary extensions.)

Ah, thanks for clearing that up, lack of knowledge on my part then. So the issuing CA must always fill that version then.

In that case, I noticed adding the "-text" option outputs Version 3 (0x02) (in the text added to the output CSR below the base64-encoded CSR, while the CSR still contains Version 1), so I'm not sure if that's also intended and "-text" somehow does not print the CSR but the "soon-to-be" certificate.

**Comment by davidben** [comment]
Can you give the full command and input? Lots of OpenSSL commands take`-text`.

If it's displaying a certificate, it'll show the version in the certificate. If it's displaying a CSR, it'll display the version in the CSR. It's quite possible you've got an invalid CSR on your hands. Some folks incorrectly assume you're supposed to copy the version over from the CSR into the certificate. (If you do, your CA probably can be made to misissue because you're not allowed to have extensions in a v1 or v2 certificate.)

**Comment by Raincode** [comment]
OpenSSL 3.1.0 14 Mar 2023
```
openssl x509 -x509toreq -key .\endUser_prv.key -in .\endUser.pem -copy_extensions copy -out endUser.csr -text
```
Output (redacted):
```
-----BEGIN CERTIFICATE REQUEST-----
…
-----END CERTIFICATE REQUEST-----
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: …
```

**Comment by davidben** [comment]
That seems to be printing a certificate. CSRs don't have serial numbers.

**Comment by davidben** [comment]
If you want to print the CSR, the `openssl req -text` command will probably work.

**Comment by Raincode** [comment]
I had a slight suspicion... Thanks for you quick and professional support.
