### ISSUE TITLE
What are the plans for the 3.0.x (LTS) version with regards to FIPS validation

### ISSUE THREAD

**Issue by Pankul94** [openssl/openssl#20686]
Hey team, as mentioned https://github.com/openssl/openssl/issues/20541#issuecomment-1475405398 , Openssl-3.0.0 has been FIPS certified and using the fips provider generated from Openssl-3.0.0 source is necessary to maintain FIPS validation.

OpenSSL has patched multiple CVEs after openssl-3.0.0 and my team has concerns about the impact of these CVEs on the fips provider generated by Openssl-3.0.0 source.

Do you plan to take Openssl-3.0.x through FIPS validation? If not, can you throw light on how these CVEs impact the fips provider generated by Openssl-3.0.0 source.

**Comment by t8m** [comment]
In practice if you use 3.0.0 FIPS provider with 3.0.8 libcrypto and libssl you should not be affected by any of these vulnerabilities.

But yes, we are in process of revalidating the 3.0 provider with 3.0.8 sources. Of course when that revalidation is finished is unknown.

**Comment by Pankul94** [comment]
Thanks!
