### ISSUE TITLE
What version of the FIPS provider should we use to declare that our module uses FIPS OpenSSL? 

### ISSUE THREAD

**Issue by bjayanax** [openssl/openssl#20689]
In our module (application), we need to use FIPS-compliant OpenSSL. If we use OpenSSL 3.0.8 in our deployment, can we claim our module is using FIPS OpenSSL?

**Comment by paulidale** [comment]
You **must** use the **3.0.0 FIPS provider** to claim FIPS compliance.

However, the 3.0.0 FIPS provider can be used with OpenSSL 3.0.8 (non-FIPS).  This is the recommended way to run it because 3.0.8 fixes lots of bugs.

The 3.0.0 FIPS provider can also be used with OpenSSL 3.1.0 (non-FIPS).

**Comment by bjayanax** [comment]
Thanks for the clarification.
