### ISSUE TITLE
Add interoperability tests with GnuTLS and NSS

### ISSUE THREAD

**Issue by not4Pedro** [openssl/openssl#20685]
Hi,

We would like to add TLS interoperability tests into OpenSSL upstream test suite. The motivation is to find problems sooner in the development process and therefore increase software quality.

In the past, we did something similar in the GnuTLS project (https://gitlab.com/gnutls/gnutls/-/pipelines/828498691/ - “test”/”fedora-interop/test”, basically testing TLS interoperability of GnuTLS changes with released OpenSSL and NSS).

Would you be open to including similar testing to OpenSSL? If so, are there some rules we should be aware of? Can we discuss the technical approach as part of this issue, or is there a better way?

Thanks, 
Peter

**Comment by t8m** [comment]
These could be handled as other external tests. Or, alternatively, these could be just tests in a new Github Action CI workflow to be run on-push.

**Comment by paulidale** [comment]
We would definitely be interested in having additional tests covering this.

**Comment by not4Pedro** [comment]
Thanks for the feedback. 
In this case, there are some technical questions, we would like to discuss with you.

1. What would be your preferred image for the test environment? Our tests depend on the TMT tool and Beakerlib but nowadays, it is not possible to fully use it on Ubuntu. Would you be fine with using Fedora image instead (or another RPM based distro)? (We could change it to Ubuntu (or other) when TMT is capable of doing so) https://github.com/teemtee/tmt

2. Considering changes which may appear in the distro images themselves, would it be better to try to set GnuTLS/NSS version in stone, or is the breakage a good piece of information to have? If we need to set it in stone, should we compile a specific commit from the upstream project, or is there any better way?

3. What should be the maximum duration of the tests? We don't want them to cause delays.

4.  Is there a way to mark tests as "non-blocking" - we could start with that to gather some initial experience.

5. Running tests using plain GitHub Actions, or we could use Packit service?

**Comment by paulidale** [comment]
1. I've got no preference on preferred image.  Whatever works?
2. Happy either way.  Latest released version would be ideal but it's probably not critical.
3. The maximum time would depend on when the test is being run.  We try to keep tests to half an hour to confirm PRs build; an hour for on commit builds and we don't really care too much for daily builds.  Interoperability tests would be fine running daily IMO.
4. If you mean each connection attempt, OpenSSL can do non-blocking TLS.  If you mean each test run, I've no idea.
5. We use GitHub Actions currently, so that would be our preference.

**Comment by not4Pedro** [comment]
Great, thanks, we will try to propose something.

4. I am thinking about a similar configuration as in GitLab (https://docs.gitlab.com/ee/ci/yaml/#allow_failure) we use. With this, the pipeline does not merely depend on results from our tests and will pass, even though the tests fail. In GitHub Actions, I have found `continue-on-error: true`. However, I am not sure if this is equivalent to the GitLab attribute. This might be a good starting point if the tests fail too much for now.

**Comment by paulidale** [comment]
`continue-on-error: true` keeps going and doesn't result in a test failure.  E.g. see the "early exit checks" in [this build](https://github.com/openssl/openssl/actions/runs/4744859890/jobs/8426659709).

**Comment by not4Pedro** [comment]
Thanks for explaining. 
Here, we would like to propose our rough [PR](https://github.com/not4Pedro/openssl/pull/9). 
The approach is not ideal, as containers are included, however, for now, this solution could be considered. We would appreciate your input on the workflow file, especially the [./config line](https://github.com/not4Pedro/openssl/pull/9/files#diff-50cffd505fe798970f550c9e84e9edc6036275a29193dd39cb2a1b7c18f90757R38), since we are not sure about a prefered prebuild configuration (./config arguments). 

ps: if you need a normal PR for review, just let me know and I will try to make it happen in a cleaner way.

**Comment by paulidale** [comment]
That looks reasonable to me.  Bring on a normal PR.

**Comment by not4Pedro** [comment]
So the tests will run for around 15 mins. 
- > In this case, I think running these tests on each `PR` and `push` would be okay. Do you agree?

**Comment by paulidale** [comment]
Yes, fifteen minutes is fine for them.

**Comment by not4Pedro** [comment]
The PR is finally here. 

To make things more efficient, I would like to suggest that an image registry would be used for the currently on the fly built image. I have tested the Github registry and it looked reasonable. 
However, this brings in the question of how will the image's source (dockerfile) be transparently saved. Just a file in this repository could possibly do it.
