### ISSUE TITLE
crash in ssl_write

### ISSUE THREAD

**Issue by dinesh1310** [openssl/openssl#20696]
Program terminated with signal SIGABRT, Aborted.
#0 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50 ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f65c1f63700 (LWP 13041))]
(gdb) bt
#0 0x00007f6ce330e8eb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
https://github.com/openssl/openssl/pull/1 0x00007f6ce32f9535 in __GI_abort () at abort.c:79
https://github.com/openssl/openssl/pull/2 0x00007f6ce3350648 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6ce345a2a0 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
https://github.com/openssl/openssl/pull/3 0x00007f6ce3356d6a in malloc_printerr (str=str@entry=0x7f6ce345844e "free(): invalid pointer") at malloc.c:5359
https://github.com/openssl/openssl/pull/4 0x00007f6ce335859c in _int_free (av=, p=, have_lock=) at malloc.c:4180
https://github.com/openssl/openssl/pull/5 0x00007f6ce3ef2d57 in () at /lib/x86_64-linux-gnu/libssl.so.1.1
https://github.com/openssl/openssl/pull/6 0x00007f6ce3ef2e9a in () at /lib/x86_64-linux-gnu/libssl.so.1.1
https://github.com/openssl/openssl/pull/7 0x00007f6ce3ef65d2 in () at /lib/x86_64-linux-gnu/libssl.so.1.1
https://github.com/openssl/openssl/pull/8 0x00007f6ce3ef6a56 in () at /lib/x86_64-linux-gnu/libssl.so.1.1
https://github.com/openssl/openssl/pull/9 0x00007f6ce3f09392 in () at /lib/x86_64-linux-gnu/libssl.so.1.1
https://github.com/openssl/openssl/pull/10 0x00007f6ce3f094c3 in SSL_write () at /lib/x86_64-linux-gnu/libssl.so.1.1
https://github.com/openssl/openssl/pull/11 0x00007f6ccc48baa4 in ws_raw_write (wsh=wsh@entry=0x7f62c782c580, data=data@entry=0x7f6ac805c660, bytes=bytes@entry=203) at ws.c:674
https://github.com/openssl/openssl/pull/12 0x00007f6ccc48cc12 in ws_write_frame (wsh=0x7f62c782c580, oc=, data=0x7f6ac838f9f0, bytes=199) at ws.c:1322
https://github.com/openssl/openssl/pull/13 0x00007f6ccc3ebaaa in ws_write_json(jsock_t*, cJSON**, switch_bool_t)
https://github.com/openssl/openssl/pull/14 0x00007f6ccc3f0461 in process_input(jsock_t*, uint8_t*, switch_ssize_t)
https://github.com/openssl/openssl/pull/15 0x00007f6ccc3f4e00 in ws_read_operation(jsock_t*, int, uint8_t*, conference*)
https://github.com/openssl/openssl/pull/16 0x00007f6ccc3f7287 in client_run(jsock_t*) (jsock=0x7f62c782c568) at mod_ws.cpp:4087
https://github.com/openssl/openssl/pull/17 0x00007f6ccc3ffcdc in g_client_thread(void*, void*) (data=0x7f62c782c568, user_data=0x0) at mod_ws.cpp:6008
https://github.com/openssl/openssl/pull/18 0x00007f6ce3018e73 in () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
https://github.com/openssl/openssl/pull/19 0x00007f6ce30184d5 in () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
https://github.com/openssl/openssl/pull/20 0x00007f6ce349efa3 in start_thread (arg=) at pthread_create.c:486
https://github.com/openssl/openssl/pull/21 0x00007f6ce33d006f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

we are getting these types of ssl_write crash in our server frequently.. any idea how to resolve this issue?

**Comment by paulidale** [comment]
The most likely culprit is a memory corruption from your application.

I'd suggest including debug symbols to give a better idea of the call chain.
I'd also suggesting running under valgrind or similar if you can reproduce this problem.

**Comment by t8m** [comment]
Another possibility is that you're using the SSL object from multiple threads simultaneously. This is not supported.

**Comment by t8m** [comment]
The multithread support enabled does not imply that you can use a single SSL object from multiple threads simultaneously such as calling SSL_read in one thread and SSL_write in another thread on the same SSL object. If you do that, this will inevitably cause crashes.
