### ISSUE TITLE
incorrect OSSL_CMP_MSG_update_recipNonce version number in 3.1 branch

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#20694]
```
BN_are_coprime                          5564	3_1_0	EXIST::FUNCTION:
OSSL_CMP_MSG_update_recipNonce          5565	3_0_9	EXIST::FUNCTION:CMP
```

It is expected in 3.1 branch function to be marked as 3_1_1. 

----
Off topic 
Once again OpenSSL team breaks binary compatibility. This is de facto standard for all releases since 1.1 nevertheless versioning policy.

**Comment by t8m** [comment]
Nope, this is not a bug. The function is present on 3.0 branch as well. The version string is correct.
