### ISSUE TITLE
Crash if ctx equal to NULL is passed to evp_pkey_ctx_get1_id_prov or evp_pkey_ctx_get1_id_len_prov

### ISSUE THREAD

**Issue by nv-dmd** [openssl/openssl#20701]
OpenSSL 3.0.7

If the first argument pointer EVP_PKEY_CTX *ctx equal to NULL is passed to the functions evp_pkey_ctx_get1_id_prov or evp_pkey_ctx_get1_id_len_prov (evp.h 893-894) then the application crashes with read access violation.

Maybe need to add a check EVP_PKEY_CTX *ctx to NULL like in a functions EVP_PKEY_CTX_get1_id and EVP_PKEY_CTX_get1_id_len?

**Comment by t8m** [comment]
> Might it be better to rewrite EVP_PKEY_CTX_get1_id() and EVP_PKEY_CTX_get1_id_len() using these functions rather than always going via the ctrl path?

Not sure, the CTRL path needs to be able to handle both provided implementations and legacy implementations anyway which means the code duplication would be inevitable.

**Comment by t8m** [comment]
> When we drop legacy it won't grin

Then we can revive it from history. Or, we can just `#if` 0 it out for now.

**Comment by nv-dmd** [comment]
Sorry, guys, what are the next steps on this issue? Do I need to prepare a patch with #if 0?

**Comment by t8m** [comment]
If you want, you can create a PR removing these functions. There is no point having them unused in the codebase.

**Comment by nv-dmd** [comment]
Ok, thank you. Then I will create a PR
