### ISSUE TITLE
Data type mismatch for padding modes

### ISSUE THREAD

**Issue by Lipovlan** [openssl/openssl#20707]
While writing my provider I stumbled upon the need to sign data with a PSS padding.

In [provider signature documentation](https://www.openssl.org/docs/manmaster/man7/provider-signature.html) there was no entry for the padding modes so I reffered to [documentation for EVP_SIGNATURE-RSA](https://www.openssl.org/docs/manmaster/man7/provider-signature.html](https://www.openssl.org/docs/manmaster/man7/EVP_SIGNATURE-RSA.html)). In it is stated that `OSSL_SIGNATURE_PARAM_PAD_MODE` is used as an UTF-8 string to signify the padding mode.

Yet in [statem_lib.c on line 366](https://github.com/openssl/openssl/blob/dfb8e185134df90fd3f21fb6ec625e7c295fdcea/ssl/statem/statem_lib.c#L366) when sending `pad-mode`, the value being sent is an integer with the value 6 (`RSA_PKCS1_PSS_PADDING`). That is what the provider receives in its `OSSL_FUNC_signature_set_ctx_params()` function.

Is that intentional and should be documented?

**Comment by t8m** [comment]
The OSSL_SIGNATURE_PARAM_PAD_MODE param is special - the provider implementation recognizes both UTF-8 string and integer types and handles them accordingly. Yeah, this is not documented properly.

**Comment by paulidale** [comment]
You should use the strings if possible.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
