### ISSUE TITLE
CIFuzz is currently failing

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#20712]
The project in google/oss-fuzz needs updating to init the fuzz/corpora submodule. Creating PR requires Google CLA. Perhaps @guidovranken would like to submit a PR to them to fix this?

**Comment by guidovranken** [comment]
Done

**Comment by t8m** [comment]
Perfect! Thank you @guidovranken

**Comment by guidovranken** [comment]
You're welcome, the OSS-Fuzz build is working again, I think this issue can be closed.

**Comment by guidovranken** [comment]
The OSS-Fuzz build is succeeding today after failing yesterday: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#openssl

As for CIFuzz I have no experience with that, @jonathanmetzman or @DavidKorczynski might be able to help here.

**Comment by t8m** [comment]
I have no idea how to fix this so I think we should temporarily disable the CIFuzz CI at least on PRs.

**Comment by t8m** [comment]
@Leo-Neat is the original author of the CIFuzz workflow, so he might be able to fix it?

**Comment by t8m** [comment]
Ha, recent runs are now passing. So perhaps it was just some issue with old caches of the oss-fuzz repo or something. Closing this.

**Comment by jonathanmetzman** [comment]
> Ha, recent runs are now passing. So perhaps it was just some issue with old caches of the oss-fuzz repo or something. Closing this.

Sorry I was OOO for the past couple days, otherwise I would have fixed this.
