### ISSUE TITLE
There should be information about desired endianness in EVP_PKEY-RSA documentation

### ISSUE THREAD

**Issue by Lipovlan** [openssl/openssl#20711]
When creating an `RSA` key, there is no documentation in `EVP_PKEY-RSA` about which endianness the modulus and public and private exponents should be in.

From my testing on x64 Windows 10 and OpenSSL 3.1.0, OpenSSL requires little endian.

**Comment by t8m** [comment]
Could you be please more specific? Do you talk about OSSL_PARAM params when creating a key via EVP_PKEY_fromdata() call?

It is highly recommended to use the helper functions for OSSL_PARAM params. However integer params are passed in native byte order. This is documented in the OSSL_PARAM man page.

**Comment by Lipovlan** [comment]
Ok, so when not stated otherwise, OpenSSL uses native endianness. Thanks for the info.
