### ISSUE TITLE
Request for a definition for end of OSSL_DISPATCH arrays

### ISSUE THREAD

**Issue by Lipovlan** [openssl/openssl#20710]
For `OSSL_PARAM` arrays we have an `OSSL_PARAM_END` for `{NULL, 0, NULL, 0, 0}`. Currently OSSL_DISPATCH arrays need to be ended with `{0, NULL}`. It would be neater if there were a `OSSL_DISPATCH_END` or something similar that could be used instead of it.

**Comment by irakr** [comment]
Can I work on this issue if no one is? It would be my first contribution to openssl.

Regarding the issue: Are we expecting this new macro `OSSL_DISPATCH_END` to be applied in whole of the openssl code base wherever the end of `OSSL_DISPATCH` array is used?

**Comment by levitte** [comment]
@irakr, do feel free to contribute.  I would expect it to be merged into the master branch.  For current release branches, that'll be a later decision.

**Comment by t8m** [comment]
> Regarding the issue: Are we expecting this new macro `OSSL_DISPATCH_END` to be applied in whole of the openssl code base wherever the end of `OSSL_DISPATCH` array is used?

Yes, it would be a good idea to use the macro within the codebase. It should be a separate commit from the one introducing the macro though.

**Comment by levitte** [comment]
> > Regarding the issue: Are we expecting this new macro `OSSL_DISPATCH_END` to be applied in whole of the openssl code base wherever the end of `OSSL_DISPATCH` array is used?
> 
> Yes, it would be a good idea to use the macro within the codebase. It should be a separate commit from the one introducing the macro though.

... but still in the same PR, right @t8m?

**Comment by t8m** [comment]
> ... but still in the same PR, right @t8m?

Yeah

**Comment by Lipovlan** [comment]
Neat! I’m glad the idea caught on!

**Comment by irakr** [comment]
> > ... but still in the same PR, right @t8m?
> 
> Yeah

Ok cool. Got it.

**Comment by irakr** [comment]
I guess this commit must be a **CLA:trivial**, is it?

**Comment by Lipovlan** [comment]
According to https://www.openssl.org/policies/cla.html as trivial things are considered one-liners and similar. 

Since you yourself aren’t sure I’d say that you should submit your CLA as per the link.

You said that you want to continue contributing so this will allow you to contribute bigger things than just trivial stuff ;)

**Comment by irakr** [comment]
> According to https://www.openssl.org/policies/cla.html as trivial things are considered one-liners and similar. 
> 
> Since you yourself aren’t sure I’d say that you should submit your CLA as per the link.
> 
> You said that you want to continue contributing so this will allow you to contribute bigger things than just trivial stuff ;)

Oh that sounds better then :) Thanks. I will do that.
