### ISSUE TITLE
Some cmp_ tests leave memory allocated

### ISSUE THREAD

**Issue by dcarpente** [openssl/openssl#20716]
I am seeing an issue where some cmp_ tests end with memory still allocated.

It looks like cmp_client_test, cmp_msg_test, cmp_protect_test, and cmp_vfy_test never free the static `default_null_provider` and `provider` objects. It also looks like cmp_ctx_test never frees the static `test_cert` object.

The memory leaks can be observed by running the test directly with valgrind, e.g.:
```
valgrind --leak-check=full --show-leak-kinds=all test/cmp_ctx_test test/certs/ee-cert.pem
valgrind --leak-check=full --show-leak-kinds=all test/cmp_client_test test/recipes/65-test_cmp_client_data/server.key test/recipes/65-test_cmp_client_data/server.crt test/recipes/65-test_cmp_client_data/client.key test/recipes/65-test_cmp_client_data/client.crt test/recipes/65-test_cmp_client_data/client.csr default test/default.cnf
```

We can also observe other tests don't have this issue:
```
valgrind --leak-check=full --show-leak-kinds=all test/cmp_server_test test/recipes/65-test_cmp_server_data/CR_protected_PBM_1234.der default test/default.cnf
```

I think these should be fixed by adding the following lines to `cleanup_tests()` in cmp_client_test.c, cmp_msg_test.c, cmp_protect_test.c, and cmp_vfy_test.c. This matches how it's handled in cmp_server_test which doesn't have the memory leak issue.
```
    OSSL_PROVIDER_unload(default_null_provider);
    OSSL_PROVIDER_unload(provider);
```

This can be fixed in `cleanup_tests()` in cmp_ctx_test.c with the following line replacing 'return;'.
```
    X509_free(test_cert);
```

I saw this issue in 3.0.5 but it looks like it's still unfixed in master.

**Comment by t8m** [comment]
Would you like to submit a PR?

**Comment by dcarpente** [comment]
Unless I can submit this change as "CLA: trivial" I'd prefer to leave it to someone else.

**Comment by t8m** [comment]
Adding those two OSSL_PROVIDER_unload() calls is IMO within CLA: trivial limits.

**Comment by dcarpente** [comment]
Done, thank you.
https://github.com/openssl/openssl/pull/20731

I was incorrect about cmp_ctx_test. This was an issue 3.0.5 but it looks like it's fixed in master.

**Comment by kostyafarber** [comment]
Can this be closed as its been fixed now?

**Comment by mattcaswell** [comment]
> Can this be closed as its been fixed now?

Yes
