### ISSUE TITLE
OpenSSL 3.1 versus 3.0 LTS

### ISSUE THREAD

**Issue by firedaemon-cto** [openssl/openssl#20722]
Hello everyone,

As stated in the newslog on [14-Mar-2023](https://www.openssl.org/news/newslog.html), the "Final version of OpenSSL 3.1.0 is now available: please download and upgrade!"

I understand that:
* 3.0 and 3.1 (or major.minor in general) are ["stable releases"](https://www.openssl.org/policies/technical/stable-release-updates.html#stable-release-updates-policy) as described in the release policy.
* The [release strategy](https://www.openssl.org/policies/releasestrat.html) clearly states that while you basically follow the semantic versioning scheme, you will designate certain "bands" as LTS releases.

However, three questions arise in the context of providing Windows installers for the binary distributions we provide.:
* Does the imperative "please upgrade" only refer to the 3.1.x release (i.e. upgrade from alpha+beta versions), or are users/programmers encouraged to upgrade from 3.0.x as well?
* The release strategy is somewhat contradictory in the sense that a minor update doesn't break the ABI/API, but in this case 3.0.x outlives 3.1.x.
* Should an OpenSSL 3.1 installer replace an OpenSSL 3.0 installation, or should they co-exist?

Thanks for your clarification.

**Comment by paulidale** [comment]
I think the answer to your questions depends on your specific circumstances.

- 3.1 is unlikely to be supported for as long as 3.0 due to the latter being an LTS release.
- We generally recommend using the most recent supported release (i.e. 3.1).
- 3.1 includes a number of performance fixes and enhancements over 3.0.
- We do not yet have a plan for supporting the 3.1 FIPS provider once it is validated.  I expect it will receive support until it is sunsetted but that's not decided at this point.
- Both 3.0 and 3.1 should be able to co-exist.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by firedaemon-cto** [comment]
Incidentally, the same question also arises in connection with all other interim versions, of which there are now 3.1, 3.2, 3.3 and probably soon 3.4.
If only API/ABI-compatible features are included in a new minor releases (as generally expected - or to put it the other way round: “No API or ABI breaking changes are allowed in a minor or patch release”), why should several minor releases exist at the same time?

**Comment by nhorman** [comment]
Because not all changes are reasonably backportable.  3.3 contains feature enhancements that may not be reasonably backported to 3.2/3.1/3.0.

**Comment by firedaemon-cto** [comment]
Understandably... However, I am not talking about backporting.

I'm talking about “fast-forwarding” to the next available minor version. All the features of the earlier minor versions are included in the minor versions.
For someone using 3.1.a, it should make no difference whether they update to 3.1.b or 3.3.c.

The effort to maintain such intermediate versions is certainly not without effort and complexity on OpenSSL's part, in addition to people like me having to ask questions and think about this particular release policy.
By the time 3.1 reaches the end of its life, there will probably be 2-3 more minor releases if you keep up the pace of good work...

**Comment by t8m** [comment]
The main reason is stability. Minor versions add new features (sometimes quite big ones such as the QUIC support). That adds of course a risk of introducing regressions.
