### ISSUE TITLE
Fuzz corpa updates aren't automatic

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#20723]
As noted in openssl/fuzz-corpora#2, there should be some automation to update the submodule across the current release branches.

**Comment by t8m** [comment]
I do not think it should be fully automatic, but there certainly could be some helper script to create a PR in automated way.

**Comment by t8m** [comment]
I think the helper script should live in the openssl/fuzz-corpora repo.

**Comment by t8m** [comment]
@paulidale please also note that for now we use the fuzz-corpora submodule only in the master branch.

**Comment by paulidale** [comment]
I thought the intention was to use the corpa on all branches, relying on the fuzzing programs to only use what they needed.

**Comment by levitte** [comment]
> I thought the intention was to use the corpa on all branches, relying on the fuzzing programs to only use what they needed.

That was an idea that was mentioned during a meeting, but I think that we concluded that *for now*, we'd only do this in the master branch, and defer doing this on the release branches 'til another time.  Baby steps, you know?

**Comment by levitte** [comment]
Actually, there already is such an issue: #20903
