### ISSUE TITLE
How to rename output dll & libs of openssl  1.1.1t on windows

### ISSUE THREAD

**Issue by nickychen123456** [openssl/openssl#20732]
I am using openssl 1.1.1t,  I just want to rename the out dll, like libssl-1_1.lib->libssl-test-1_1.lib, libcrypto-1_1.lib->libcrypto-test-1_1.lib, I have refer the issue #20439 , but it seems the solution did not work on windows. So do we havn another solution to do this, thanks

**Comment by levitte** [comment]
Yup, you are correct...  as build files templates currently stand with 1.1.1, only the Unix Makefile template supports `shlib_variant`.  That's an omission that should be easy to fix.

**Comment by paulidale** [comment]
1.1.1 is security fixes only and this wouldn't qualify.

**Comment by levitte** [comment]
> 1.1.1 is security fixes only and this wouldn't qualify.

Argh, forgot about that

**Comment by nickychen123456** [comment]
@levitte I haved tried your patch but it doesnot work for me, what I did is:

1. apply the patches like:

diff --git a/Configurations/descrip.mms.tmpl b/Configurations/descrip.mms.tmpl
index e1aecfa..1685941 100644
--- a/Configurations/descrip.mms.tmpl
+++ b/Configurations/descrip.mms.tmpl
@@ -13,6 +13,8 @@
   our $sover_dirname = sprintf "%02d%02d", split(/\./, $config{shlib_version_number});
   our $osslver = sprintf "%02d%02d", split(/\./, $config{version});
 
**+  our $shlibvariant = $target{shlib_variant} || "";**
+
   our $sourcedir = $config{sourcedir};
   our $builddir = $config{builddir};
   sub sourcefile {
@@ -47,13 +49,13 @@
       map { (my $x = $_) =~ s/\.a$//; $x }
       @{$unified_info{libraries}};
   our @shlibs =
-      map { $unified_info{sharednames}->{$_} || () }
+      map { $unified_info{sharednames}->{$_}.$shlibvariant || () }
       grep(!/\.a$/, @{$unified_info{libraries}});
   our @install_libs =
       map { (my $x = $_) =~ s/\.a$//; $x }
       @{$unified_info{install}->{libraries}};
   our @install_shlibs =
-      map { $unified_info{sharednames}->{$_} || () }
+      map { $unified_info{sharednames}->{$_}.$shlibvariant || () }
       grep(!/\.a$/, @{$unified_info{install}->{libraries}});
 
   # This is a horrible hack, but is needed because recursive inclusion of files
@@ -695,7 +697,7 @@ reconfigure reconf :
       }
       return map { $_ =~ /\.a$/
                    ? $`.".OLB"
-                   : $unified_info{sharednames}->{$_}.".EXE" } @_;
+                   : $unified_info{sharednames}->{$_}.$shlibvariant.".EXE" } @_;
   }
 
   # Helper function to deal with inclusion directory specs.
@@ -912,7 +914,7 @@ EOF
   sub libobj2shlib {
       my %args = @_;
       my $lib = $args{lib};
-      my $shlib = $args{shlib};
+      my $shlib = $args{shlib}.$shlibvariant;
       my $libd = dirname($lib);
       my $libn = basename($lib);
       my @objs = map { (my $x = $_) =~ s|\.o$|.OBJ|; $x }
diff --git a/Configurations/windows-makefile.tmpl b/Configurations/windows-makefile.tmpl
index 13716e0..96a3f6f 100644
--- a/Configurations/windows-makefile.tmpl
+++ b/Configurations/windows-makefile.tmpl
@@ -42,13 +42,15 @@
      (my $lib = shift) =~ s/\.a$//;
      $lib .= '_static'
          if (defined $unified_info{sharednames}->{$lib});
-     return $lib . $libext;
+     #return $lib . $libext;
+     return $lib . $shlibvariant . $libext;
  }
 
  sub shlib_import {
      my $lib = shift;
      return () if $disabled{shared} || $lib =~ /\.a$/;
-     return $lib . $shlibextimport;
+     #return $lib . $shlibextimport;
+     return $lib . $shlibvariant . $shlibextimport;
  }
 
  sub dso {
diff --git a/util/mkdef.pl b/util/mkdef.pl
index 3ac7982..0599f23 100644
--- a/util/mkdef.pl
+++ b/util/mkdef.pl
@@ -197,6 +197,7 @@ foreach (@ARGV, split(/ /, $config{options}))
 	}
 $libname = $unified_info{sharednames}->{libcrypto} if $do_crypto;
 $libname = $unified_info{sharednames}->{libssl} if $do_ssl;
+$libname .= $target{shlib_variant} || "";
 
 if (!$libname) {
 	if ($do_ssl) {

2. create an new config file named "99-ourtargets.conf", and the content is:
(
    "VC-WIN64A-masm-test" => {
        inherit_from => [ 'VC-WIN64A-masm' ],
        shlib_variant => "-test",
    }
);

3. run this command:
perl Configure VC-WIN64A-masm-test

But the lib and dll named were not changed, still libcrtpto.lib&libcrypto-1_1.dll, Did I do something wrong? Please help, thanks

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
