### ISSUE TITLE
Using "openssl pkcs12 -clcerts" on CSR-based certs leads to creating an empty output file

### ISSUE THREAD

**Issue by TheAzureGuy** [openssl/openssl#20730]
I would appreciate your advise on the following.

I have a password-less PFX with a cert that was issued based on a CSR. When attempting to run this command:

`openssl pkcs12 -in "with-csr.pfx" -nokeys -clcerts -out "with-csr.pem" -nodes`

I get a .pem file created with no data (zero file length). If I replace `-clcerts` with -`cacerts`, I get the expected output in the .pem file. However, the cert contained in the source .pfx file is indeed a client (not a CA) cert. 

Is there anything special that the cert needs to possess so that openssl correctly treats as a client cert?

Thank you in advance for your insights.

**Comment by TheAzureGuy** [comment]
Thank you, Tomáš. I realized this already after reviewing the source code. 

As far as localKeyID bag, would it be something that CA issuing the cert must introduce into the cert explicitly?

**Comment by t8m** [comment]
> Thank you, Tomáš. I realized this already after reviewing the source code.
> 
> As far as localKeyID bag, would it be something that CA issuing the cert must introduce into the cert explicitly?

It isn't part of the certificate itself. It is added to the PKCS12 file when the certificate is added.

**Comment by TheAzureGuy** [comment]
OK, if I understand correctly - this is a potential issue with the export logic that creates a PKCS12 file and does not (for whatever reasons) add the localKeyID bag, correct? Since this cert is issued on the basis of a CSR, there is no private key. Is that significant at all?

**Comment by t8m** [comment]
Yes, you understand this correctly. Perhaps there being no private key at all is the reason why they do not add the localKeyId attribute to the bag. IMO they could put some bogus value or something there.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
