### ISSUE TITLE
OpenSSL 1.0.2 with fips 2.0.16

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#20733]
Hi, 

I'm compiling openssl 1.0.2 with fips 2.0.16, I'm renaming the output binaries. with "m64" prefix. Earlier I was able to compile and rename in x86, but while compiling in x64 I'm facing linking errors.
If I dont rename output binaries in x64, then there is no linking error and I'm able to compile successfully, please help what I'm missing here.

Below steps I followed.

1. **set FIPSDIR=C:\SWTOOLS\OpenSSL_FIPS\openssl-fips-2.0.16**
2. **set FIPS_SIG=perl C:\SWTOOLS\OpenSSL_FIPS\openssl-fips-2.0.16\util\msincore**
3. **To rename**
**openssl-1.0.2zd\ms\do_nasm.bat -** 
Add prefix "m64" to the libeay and libeay32.def strings on line 7
Add prefix "m64" to the ssleay and ssleay32.def strings on line 8 
**util\[mkdef.pl](http://mkdef.pl/)**
Add prefix "m64" to ssleay on line 178
Add prefix "m64" to libeay on line 183
Add prefix "M64" to SSLEAY on line 253
Add prefix "M64" to LIBEAY on line 256 
**util\pl\[VC-32.pl](http://vc-32.pl/)** 
Add prefix "m64" to ssleay32 on line 6
Add prefix "m64" to libeay32 on line 7
Add prefix "m64" to libeay32 on line 16

**1. perl Configure VC-WIN64A fips
2. ms\do_win64a
3. nmake -f ms\ntdll.mak**

I'm getting following linking error
`   link /nologo /subsystem:console /opt:ref /debug /dll /out:out32dll\m64ssleay32.dll /def:ms/M64SSLEAY32.def @C:\Users\PRIYAN~2.CHA\AppData\Local\Temp\nm1717.tmp
   Creating library out32dll\m64ssleay32.lib and object out32dll\m64ssleay32.exp
d1_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_new
d1_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_new
s3_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_new
s3_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_new
s23_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_new
s23_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_new
d1_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_free
d1_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_free
ssl_lib.obj : error LNK2001: unresolved external symbol BUF_MEM_free
s3_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_free
s3_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_free
s23_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_free
s23_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_free
d1_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_grow
d1_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_grow
s3_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_grow
s3_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_grow
s23_srvr.obj : error LNK2001: unresolved external symbol BUF_MEM_grow
s23_clnt.obj : error LNK2001: unresolved external symbol BUF_MEM_grow
s3_srvr.obj : error LNK2019: unresolved external symbol BUF_MEM_grow_clean referenced in function ssl3_accept
s3_both.obj : error LNK2001: unresolved external symbol BUF_MEM_grow_clean
d1_both.obj : error LNK2001: unresolved external symbol BUF_MEM_grow_clean
ssl_cert.obj : error LNK2001: unresolved external symbol BUF_MEM_grow_clean
ssl_lib.obj : error LNK2001: unresolved external symbol BUF_strdup
ssl_sess.obj : error LNK2001: unresolved external symbol BUF_strdup
ssl_conf.obj : error LNK2001: unresolved external symbol BUF_strdup
tls_srp.obj : error LNK2001: unresolved external symbol BUF_strdup
s3_srvr.obj : error LNK2001: unresolved external symbol BUF_strdup
s3_clnt.obj : error LNK2001: unresolved external symbol BUF_strdup
s3_lib.obj : error LNK2001: unresolved external symbol BUF_strdup
t1_lib.obj : error LNK2001: unresolved external symbol BUF_strdup
s3_srvr.obj : error LNK2019: unresolved external symbol BUF_strndup referenced in function ssl3_get_client_key_exchange
s3_clnt.obj : error LNK2001: unresolved external symbol BUF_strndup
ssl_asn1.obj : error LNK2001: unresolved external symbol BUF_strndup
ssl_ciph.obj : error LNK2001: unresolved external symbol sk_num
t1_lib.obj : error LNK2001: unresolved external symbol sk_num
d1_srtp.obj : error LNK2001: unresolved external symbol sk_num
ssl_lib.obj : error LNK2001: unresolved external symbol sk_num
ssl_cert.obj : error LNK2001: unresolved external symbol sk_num
s3_srvr.obj : error LNK2001: unresolved external symbol sk_num
s3_clnt.obj : error LNK2001: unresolved external symbol sk_num
s3_lib.obj : error LNK2001: unresolved external symbol sk_num
s23_clnt.obj : error LNK2001: unresolved external symbol sk_num
ssl_ciph.obj : error LNK2001: unresolved external symbol sk_value
t1_lib.obj : error LNK2001: unresolved external symbol sk_value
d1_srtp.obj : error LNK2001: unresolved external symbol sk_value
ssl_lib.obj : error LNK2001: unresolved external symbol sk_value
ssl_cert.obj : error LNK2001: unresolved external symbol sk_value
s3_srvr.obj : error LNK2001: unresolved external symbol sk_value
s3_clnt.obj : error LNK2001: unresolved external symbol sk_value
s3_lib.obj : error LNK2001: unresolved external symbol sk_value
s23_clnt.obj : error LNK2001: unresolved external symbol sk_value
d1_srtp.obj : error LNK2001: unresolved external symbol sk_new_null
ssl_lib.obj : error LNK2001: unresolved external symbol sk_new_null
ssl_cert.obj : error LNK2001: unresolved external symbol sk_new_null
ssl_ciph.obj : error LNK2001: unresolved external symbol sk_new_null
s3_srvr.obj : error LNK2001: unresolved external symbol sk_new_null
s3_clnt.obj : error LNK2001: unresolved external symbol sk_new_null
s3_lib.obj : error LNK2001: unresolved external symbol sk_new_null
t1_lib.obj : error LNK2001: unresolved external symbol sk_new_null
ssl_sess.obj : error LNK2001: unresolved external symbol sk_free
ssl_ciph.obj : error LNK2001: unresolved external symbol sk_free
s3_srvr.obj : error LNK2001: unresolved external symbol sk_free
d1_srtp.obj : error LNK2001: unresolved external symbol sk_free
ssl_lib.obj : error LNK2001: unresolved external symbol sk_free
ssl_cert.obj : error LNK2001: unresolved external symbol sk_free
ssl_lib.obj : error LNK2001: unresolved external symbol sk_pop_free
ssl_cert.obj : error LNK2001: unresolved external symbol sk_pop_free
ssl_ciph.obj : error LNK2001: unresolved external symbol sk_pop_free
s3_srvr.obj : error LNK2001: unresolved external symbol sk_pop_free
s3_clnt.obj : error LNK2001: unresolved external symbol sk_pop_free
s3_lib.obj : error LNK2001: unresolved external symbol sk_pop_free
t1_lib.obj : error LNK2001: unresolved external symbol sk_pop_free
d1_srtp.obj : error LNK2001: unresolved external symbol sk_push
ssl_lib.obj : error LNK2001: unresolved external symbol sk_push
ssl_cert.obj : error LNK2001: unresolved external symbol sk_push
ssl_ciph.obj : error LNK2001: unresolved external symbol sk_push
s3_srvr.obj : error LNK2001: unresolved external symbol sk_push
s3_clnt.obj : error LNK2001: unresolved external symbol sk_push
s3_lib.obj : error LNK2001: unresolved external symbol sk_push
t1_lib.obj : error LNK2001: unresolved external symbol sk_push
s3_srvr.obj : error LNK2019: unresolved external symbol sk_shift referenced in function ssl3_get_client_certificate
ssl_cert.obj : error LNK2001: unresolved external symbol sk_shift
s3_srvr.obj : error LNK2019: unresolved external symbol sk_dup referenced in function ssl3_get_client_hello
ssl_lib.obj : error LNK2001: unresolved external symbol sk_dup
ssl_sess.obj : error LNK2001: unresolved external symbol sk_dup
ssl_ciph.obj : error LNK2001: unresolved external symbol sk_dup
bio_ssl.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
tls_srp.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
ssl_cert.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
ssl_sess.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
ssl_ciph.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
ssl_conf.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
d1_lib.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
d1_pkt.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
d1_both.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
ssl_lib.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
s3_pkt.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
s3_both.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
t1_lib.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
t1_enc.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
s3_srvr.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
s3_clnt.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
s3_lib.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
s3_enc.obj : error LNK2001: unresolved external symbol CRYPTO_malloc
tls_srp.obj : error LNK2001: unresolved external symbol CRYPTO_free
ssl_rsa.obj : error LNK2001: unresolved external symbol CRYPTO_free
ssl_asn1.obj : error LNK2001: unresolved external symbol CRYPTO_free
ssl_conf.obj : error LNK2001: unresolved external symbol CRYPTO_free
bio_ssl.obj : error LNK2001: unresolved external symbol CRYPTO_free
ssl_lib.obj : error LNK2001: unresolved external symbol CRYPTO_free
ssl_cert.obj : error LNK2001: unresolved external symbol CRYPTO_free
ssl_sess.obj : error LNK2001: unresolved external symbol CRYPTO_free
ssl_ciph.obj : error LNK2001: unresolved external symbol CRYPTO_free
t1_ext.obj : error LNK2001: unresolved external symbol CRYPTO_free
d1_lib.obj : error LNK2001: unresolved external symbol CRYPTO_free
d1_pkt.obj : error LNK2001: unresolved external symbol CRYPTO_free
d1_both.obj : error LNK2001: unresolved external symbol CRYPTO_free
s3_pkt.obj : error LNK2001: unresolved external symbol CRYPTO_free
s3_both.obj : error LNK2001: unresolved external symbol CRYPTO_free
t1_lib.obj : error LNK2001: unresolved external symbol CRYPTO_free
t1_enc.obj : error LNK2001: unresolved external symbol CRYPTO_free
s3_srvr.obj : error LNK2001: unresolved external symbol CRYPTO_free
s3_clnt.obj : error LNK2001: unresolved external symbol CRYPTO_free
s3_lib.obj : error LNK2001: unresolved external symbol CRYPTO_free
s3_enc.obj : error LNK2001: unresolved external symbol CRYPTO_free
t1_enc.obj : error LNK2019: unresolved external symbol OPENSSL_cleanse referenced in function tls1_alert_code
ssl_sess.obj : error LNK2001: unresolved external symbol OPENSSL_cleanse
tls_srp.obj : error LNK2001: unresolved external symbol OPENSSL_cleanse
s3_srvr.obj : error LNK2001: unresolved external symbol OPENSSL_cleanse
s3_clnt.obj : error LNK2001: unresolved external symbol OPENSSL_cleanse
s3_lib.obj : error LNK2001: unresolved external symbol OPENSSL_cleanse
s3_enc.obj : error LNK2001: unresolved external symbol OPENSSL_cleanse
bio_ssl.obj : error LNK2001: unresolved external symbol BIO_free
ssl_cert.obj : error LNK2001: unresolved external symbol BIO_free
ssl_rsa.obj : error LNK2001: unresolved external symbol BIO_free
ssl_txt.obj : error LNK2001: unresolved external symbol BIO_free
ssl_conf.obj : error LNK2001: unresolved external symbol BIO_free
s3_srvr.obj : error LNK2001: unresolved external symbol BIO_free
s3_lib.obj : error LNK2001: unresolved external symbol BIO_free
s3_enc.obj : error LNK2001: unresolved external symbol BIO_free
ssl_lib.obj : error LNK2001: unresolved external symbol BIO_free
bio_ssl.obj : error LNK2001: unresolved external symbol BIO_ctrl
ssl_cert.obj : error LNK2001: unresolved external symbol BIO_ctrl
ssl_rsa.obj : error LNK2001: unresolved external symbol BIO_ctrl
ssl_txt.obj : error LNK2001: unresolved external symbol BIO_ctrl
ssl_conf.obj : error LNK2001: unresolved external symbol BIO_ctrl
d1_lib.obj : error LNK2001: unresolved external symbol BIO_ctrl
d1_pkt.obj : error LNK2001: unresolved external symbol BIO_ctrl
d1_both.obj : error LNK2001: unresolved external symbol BIO_ctrl
ssl_lib.obj : error LNK2001: unresolved external symbol BIO_ctrl
s3_pkt.obj : error LNK2001: unresolved external symbol BIO_ctrl
s23_clnt.obj : error LNK2001: unresolved external symbol BIO_ctrl
d1_srvr.obj : error LNK2001: unresolved external symbol BIO_ctrl
d1_clnt.obj : error LNK2001: unresolved external symbol BIO_ctrl
s3_srvr.obj : error LNK2001: unresolved external symbol BIO_ctrl
s3_clnt.obj : error LNK2001: unresolved external symbol BIO_ctrl
s3_lib.obj : error LNK2001: unresolved external symbol BIO_ctrl
s3_enc.obj : error LNK2001: unresolved external symbol BIO_ctrl
s3_srvr.obj : error LNK2019: unresolved external symbol BN_CTX_new referenced in function ssl3_get_client_key_exchange
s3_clnt.obj : error LNK2001: unresolved external symbol BN_CTX_new
s3_srvr.obj : error LNK2019: unresolved external symbol BN_CTX_free referenced in function ssl3_get_client_key_exchange
s3_clnt.obj : error LNK2001: unresolved external symbol BN_CTX_free
s3_srvr.obj : error LNK2019: unresolved external symbol BN_num_bits referenced in function ssl3_send_server_key_exchange
s3_clnt.obj : error LNK2001: unresolved external symbol BN_num_bits
tls_srp.obj : error LNK2001: unresolved external symbol BN_num_bits
s3_srvr.obj : error LNK2019: unresolved external symbol BN_clear_free referenced in function ssl3_get_client_key_exchange
tls_srp.obj : error LNK2001: unresolved external symbol BN_clear_free
s3_srvr.obj : error LNK2019: unresolved external symbol BN_bin2bn referenced in function ssl3_get_client_key_exchange
s3_clnt.obj : error LNK2001: unresolved external symbol BN_bin2bn
tls_srp.obj : error LNK2001: unresolved external symbol BN_bin2bn
s3_srvr.obj : error LNK2019: unresolved external symbol BN_bn2bin referenced in function ssl3_send_server_key_exchange
s3_clnt.obj : error LNK2001: unresolved external symbol BN_bn2bin
tls_srp.obj : error LNK2001: unresolved external symbol BN_bn2bin
s3_srvr.obj : error LNK2019: unresolved external symbol BN_ucmp referenced in function ssl3_get_client_key_exchange
tls_srp.obj : error LNK2001: unresolved external symbol BN_ucmp
s3_srvr.obj : error LNK2019: unresolved external symbol ASN1_get_object referenced in function ssl3_get_client_key_exchange
ssl_asn1.obj : error LNK2001: unresolved external symbol ASN1_get_object
s3_srvr.obj : error LNK2019: unresolved external symbol RSA_private_decrypt referenced in function ssl3_get_client_key_exchange
s3_srvr.obj : error LNK2019: unresolved external symbol RSA_up_ref referenced in function ssl3_send_server_key_exchange
ssl_cert.obj : error LNK2001: unresolved external symbol RSA_up_ref
ssl_rsa.obj : error LNK2001: unresolved external symbol RSA_up_ref
s3_srvr.obj : error LNK2019: unresolved external symbol RSA_sign referenced in function ssl3_send_server_key_exchange
s3_clnt.obj : error LNK2001: unresolved external symbol RSA_sign
.
.
.
out32dll\m64ssleay32.dll : fatal error LNK1120: 377 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\link.EXE"' : return code '0x460'`

**Comment by t8m** [comment]
The 1.0.2 version is supported only for Premium support customers and the old FIPS module 2.0 is not supported anymore at all.

**Comment by ChauhanPriyanka** [comment]
We are premium customers via safeelogic, do I have to connect them ?

**Comment by t8m** [comment]
If you're Safelogic customers, please contact them.
