### ISSUE TITLE
How to disable AES-NI speeding when using evp.h?

### ISSUE THREAD

**Issue by galaxysmonkey** [openssl/openssl#20746]
I am using evp.h to write program and Implement several encryption modes of aes.But I have seen that OPENSSL_cpuid_setup is removed for security problems. So now ,how can I disable AES-NI or enable it? I have seen OPENSSL_init_crypto(), but I have no idea how to use it.

**Comment by paulidale** [comment]
Have a look at the man page for the [OPENSSL_ia32cap](https://www.openssl.org/docs/manmaster/man3/OPENSSL_ia32cap.html).

**Comment by galaxysmonkey** [comment]
How can I enable or disable it in my C program? OPENSSL_ia32cap is not in openssl/evp.h. What should I do？Or only what I can do is just like"OPENSSL_ia32cap="~0x200000200000000" openssl speed -elapsed -evp aes-256-cbc" on the terminal.

**Comment by paulidale** [comment]
Read the manual page for `putenv(3)` and/or `setenv(3)` to change it in C.
The terminal also works.

**Comment by galaxysmonkey** [comment]
Thanks！

**Comment by galaxysmonkey** [comment]
On linux it's actually work,but on windows I can‘t do that

**Comment by t8m** [comment]
> On linux it's actually work,but on windows I can‘t do that

Why? IMO it should be possible to call putenv(3) and/or setenv(3) on Windows as well.

There is no other way how to override the CPU feature detection.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
