### ISSUE TITLE
How to update SSL server cert in client hello callback when trusted_ca_keys extension is received

### ISSUE THREAD

**Issue by monkeyish-smart** [openssl/openssl#20744]

**Comment by Lipovlan** [comment]
Hi! What exactly is your question?

**Comment by monkeyish-smart** [comment]
Hi,

I need the following flow, and I have tried many ways to complete it. I hope to get your help. thank you.

1. The Client sends a Client_Hello message using the trusted_ca_keys message in Extensin.(trusted_ca_keys contains a list of supported certificates)
2. The Server receives the Client_Hello message and selects the corresponding certificate based on the trusted_ca_keys message in Extensin.

This feature requires the certificate to be populated during the SSL_accept phase.
My Server flow:
	1.SSL_CTX_new();(This step does not know which certificate to use, so no certificate has been loaded)
	2.SSL_CTX_add_server_custom_ext();(Set the TLSEXT_TYPE_trusted_ca_keys function callback through the SSL_CTX_add_server_custom_ext() function)
	2.tcp accept();
	3.SSL_new();
	4.SSL_accept()/
		1)The TLSEXT_TYPE_trusted_ca_keys callback is triggered when a Client_Hello message is received, matching the certificate in the callback function.
		2)parse_cb function flow (TLSEXT_TYPE_trusted_ca_keys callback function):
			SSL_CTX_use_certificate_chain_file()
			SSL_CTX_use_PrivateKey_file()
			SSL_CTX_check_private_key()
			parse_cb finish.
			
My Server flow did not live up to expectations. Because in SSL_new phase the certificate is copied from SSL_CTX *ctx to SSL *s. 
I found in SSL_accept phase, not only "SSL_CTX *ctx" needs to be updated, but also "SSL *s".
I need similar to "s->cert = ssl_cert_dup(ctx->cert);" This function, but openssl does not open this interface. 

I wonder if OPENSSL can do that?
thanks.

**Comment by monkeyish-smart** [comment]
Hi,

Is there any way to solve this problem?

**Comment by monkeyish-smart** [comment]
Hi, 
Is there a solution to this case?

**Comment by nhorman** [comment]
I think what you want is to use SSL_use_PrivateKey_file and SSL_use_certificate_chain_file instead
