### ISSUE TITLE
Doesn't base provider implement DECODER operation?

### ISSUE THREAD

**Issue by Lipovlan** [openssl/openssl#20742]
In the documentation about [base provider in section about implemented operations](https://www.openssl.org/docs/man3.1/man7/OSSL_PROVIDER-base.html#OPERATIONS-AND-ALGORITHMS) it states that only `Asymmetric Key Encoder` is implemented.

That kind of deviates from the naming convention since only `ENCODER` and `DECODER` operations exist. But that is not my point.

Since OpenSSL is able to load a DER or PEM encoded certificates don't the `base` and `default` providers implement both `ENCODER` and `DECODER` contrary to just `ENCODER` operation as stated in the manual pages for both the [base provider](https://www.openssl.org/docs/man3.1/man7/OSSL_PROVIDER-base.html#Asymmetric-Key-Encoder) and the [default provider](https://www.openssl.org/docs/man3.1/man7/OSSL_PROVIDER-default.html#Asymmetric-Key-Encoder)?

**Comment by paulidale** [comment]
The base provider implements decoders too.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
