### ISSUE TITLE
Key from an external provider fails to load when the default provider is activated in openssl.cnf

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#20747]
Hello. This is related to an external provider https://github.com/tpm2-software/tpm2-openssl

Everything worked fine until Fedora 38 in the default `openssl.cnf` set
```
[default_sect]
activate = 1
```

With this enabled, the keys from the TPM2 provider suddenly fail to load, even when the providers are specified explicitly. For example, when loading a TPM2 private key, the `object_cb` of `OSSL_FUNC_STORE_LOAD` fails (with no openssl warning). Exactly the same command however works perfectly fine when the `activate = 1` gets disabled.
```
openssl pkeyutl -provider tpm2 -provider default -inkey 'handle:0x81000003' -sign -rawin -in testdata -out testdata.sig
```

When I activate both the default and the tpm2 provider in the `openssl.cnf`, the `openssl list -providers` correctly lists both providers, but the above `openssl pkeyutl` command still fails, with or without explicitly loaded providers.

Please: is this an expected behaviour, or not? Is the `openssl.cnf` supposed to have this impact?

BTW, this is not a Fedora issue. I can reproduce the same behaviour with Ubuntu 22.04. It feels related to the `openssl.cnf` and provider activation. I always thought this has no effect when providers are loaded explicitly.

**Comment by paulidale** [comment]
Does adding `-propquery "provider!=default"` help?

**Comment by gotthardp** [comment]
It gets better. Some errors get solved. Funny to see both inclusion and exclusion of the default provider, but it works.

However, when I need to load both a TPM2 key and a certificate I now get an error when loading the certificate:
```
openssl s_server -provider tpm2 -provider default -propquery 'provider!=default' -accept 4432 -www -key handle:0x81000004 -cert testcert.pem
Could not open file or uri for loading server certificate from testcert.pem
40A7F745E67F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file
40A7F745E67F0000:error:1608010C:STORE routines:inner_loader_fetch:unsupported:../crypto/store/store_meth.c:359:No store loader found. For standard store loaders you need at least one of the default or base providers available. Did you forget to load them? Info: Global default library context, Scheme (file : 115), Properties (provider!=default)
Unable to load server certificate
```
Without the `propquery` I cannot read the key (my store gets called but the `object_cb` returns an error).
```
openssl s_server -provider tpm2 -provider default -accept 4432 -www -key handle:0x81000004 -cert testcert.pem
Could not read server certificate private key from handle:0x81000004
```

**Comment by paulidale** [comment]
Try this one instead: `-propquery "?provider!=default"` this prefers a non-default provider but still allows the default.

The TPM2 provider is defining a really weird `provider` property:
```c
#define TPM2_PROPS(op) ("provider=tpm2,tpm2." #op)
```
This essentially makes it impossible to filter based on it's `provider` property.

**Comment by gotthardp** [comment]
The `-propquery "?provider=tpm2"` solves all problems. Thank you!
Is this an expected behaviour considering no `propquery` was needed without `activate = 1` in the `openssl.cnf`?

I think I understand it now: the order of provider loading is important: the one loaded first is found first. When tpm2 is loaded before the default provider, the implementations from tpm2 are found first and thus everything works. Using `activate = 1` in the `openssl.cnf` means the default provider is loaded first (before tpm2), so the default implementations are found first and the behaviour changes. Therefore we need the `-propquery "?provider=tpm2"` to change the precedence explicitly.

If this interpretation is correct there is no bug. I just got confused by this behaviour change, which makes sense now.

We tried openssl 3.0.8 (Fedora 38) as well as 3.0.2 (Ubuntu 22.04).

**Comment by paulidale** [comment]
Almost: when multiple algorithms match query, there is (deliberately) no guarantee as which is returned.
So relying on the provider ordering is a time bomb: it is very likely to change at some point in the future.

**Comment by gotthardp** [comment]
Thank you again!

**Comment by t8m** [comment]
As I said, it is most probably a bug in the tpm2 provider around key export function. When a private key is loaded via store URL through the tpm2 provider, the provider should not export the public key. The libcrypto then ensures the tpm2 provider is always used for the private key operations with that key. If OTOH the tpm2 provider exports the public key if asked for exporting the key, the subsequent private key operation with the exported public key fails.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
