### ISSUE TITLE
EXC_BAD_INSTRUCTION in lib crypto.3.dylib when v3.1.0 is run under the debugger. v3.0.8 does not generate problem lib. (Apple M1/M2)

### ISSUE THREAD

**Issue by softeky** [openssl/openssl#20753]
Ventura 13.2.1/Apple MacBookPro M2 Max (same issue on M1 reported too).

Please see:

https://stackoverflow.com/questions/74059978/why-is-lldb-generating-exc-bad-instruction-with-user-compiled-library-on-macos/76032052#76032052

and

https://i.stack.imgur.com/iNxfX.png

for more details if needed. The test code to link with should not be relevant (crash is in pre-user-code initialization), though the example from:

https://stackoverflow.com/questions/60934066/mqtt-over-ssl-with-paho-c

was used (with paho libs installed).

**Comment by tom-cosgrove-arm** [comment]
This is a known problem which should be fixed by #20305, but which hasn't been released yet.

Note that this should only happen when run under the debugger, which is shown in the stackoverflow question, but stated in this issue - I will edit to reflect this.

**Comment by tom-cosgrove-arm** [comment]
(not sure how to set the labels for this - it's a bug report,. but for a bug that's already fixed, and other issues have mentioned this, so does that make it a duplicate?)

**Comment by paulidale** [comment]
Duplicate IMO

**Comment by Bo98** [comment]
> This is a known problem which should be fixed by #20305, but which hasn't been released yet.

Does it need porting to `openssl-3.1` branch? Don't see the commit on that branch yet.

(This issue appears to be labelled `branch: 3.0` but it sounds like it should be `branch: 3.1`)

**Comment by t8m** [comment]
This is not really a bug. Although inconvenient for debugging, this does not affect normal execution.

The #20305 was merged only to the master branch.

**Comment by cjnewman** [comment]
This bug just wasted a half hour of my time. It also leaves bad smell about OpenSSL project if I have to downgrade to an older version to debug on my MacBook.

**Comment by Bo98** [comment]
Given this is a regression introduced in 3.1, is there a reduced part of https://github.com/openssl/openssl/pull/20305 that could be backported rather than the whole thing? (@tom-cosgrove-arm might know?)

I agree and understand that a full backport is large and not eligible.

I'm asking because we've been asked on multiple occasions now downstream to withdraw OpenSSL 3.1 due to this issue.

**Comment by tom-cosgrove-arm** [comment]
I have a minimal fix, I just need to get it through internal review

**Comment by tom-cosgrove-arm** [comment]
I don't think the label `branch: 3.0` is right here, as there isn't a problem with 3.0, as I understand it

**Comment by tom-cosgrove-arm** [comment]
This should be fixed by #21261, which has now been merged
