### ISSUE TITLE
Cannot validate certificate but Chrome and Firefox can

### ISSUE THREAD

**Issue by swesemeyer** [openssl/openssl#20757]
Not sure whether this is a bug or intended behaviour...
The following URL is the issue:
https://opendap.larc.nasa.gov/
Both Firefox and Chrome show no problem in securing the connection.

However, openssl cannot verify the site certificate:

openssl s_client -connect opendap.larc.nasa.gov:443 -showcerts

CONNECTED(00000003)
depth=0 C = US, ST = Virginia, L = Hampton, O = NASA Langley Research Center, CN = opendap.larc.nasa.gov
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = Virginia, L = Hampton, O = NASA Langley Research Center, CN = opendap.larc.nasa.gov
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = US, ST = Virginia, L = Hampton, O = NASA Langley Research Center, CN = opendap.larc.nasa.gov
verify return:1
---
Certificate chain
 0 s:C = US, ST = Virginia, L = Hampton, O = NASA Langley Research Center, CN = opendap.larc.nasa.gov
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Thawte TLS RSA CA G1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Apr  7 00:00:00 2023 GMT; NotAfter: Apr 26 23:59:59 2024 GMT
<snip>

Adding the certificate chain as provided by Firefox to my cacert file fixes the issue but I am baffled by the discrepancy in behaviour between the browser and openssl.

This is on an up-to-date Fedora 37 instance running:
openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

Any ideas?

**Comment by zzl360** [comment]
because chrome and firefox all use nss library as trust root store while openssl not
