### ISSUE TITLE
RC4 and OpenSSL 3.0.8

### ISSUE THREAD

**Issue by pcaswell** [openssl/openssl#20769]
Hello OpenSSL,
I have tried to put this question in the openssl-users@openssl.org mailing list but I given up waiting for my request to join it to happen.  Anyway here goes:

I am porting a product from OpenSSL 1.1.1o to OpenSSL 3.0.8 and am trying to remove all deprecated code.  Things have progressed well so far but I’m stuck with RC4 (which I need to keep for backwards compatibility in the product).

Here’s the essence of the old implementation:
```
             const char* pKey = "Some arbitrary passphrase string";
             const char* pInput = "The quick brown fox jumped over the lazy frog";
             unsigned char* pOutput = new unsigned char[512];
             … etc   

             RC4_KEY oRC4Key;
             RC4_set_key(&oRC4Key, iKeyLen, (const unsigned char*)pKey);
             RC4(&oRC4Key, iInputLen, (const unsigned char*)pInput, pOutput);
```
My new implementation looks like this (note: I have already loaded the “legacy” and “default providers) …

```
            memset(pOutput, 0, iOutputLen);
            EVP_CIPHER_CTX* pRC4Ctx = EVP_CIPHER_CTX_new();
            if (!pRC4Ctx)
            {
                        printf("EVP_CIPHER_CTX_new() Failed\n");
                        return 1;
            }

            EVP_CIPHER* pRC4 = EVP_CIPHER_fetch(NULL, "RC4", NULL);
            if (!pRC4)
            {
                        printf("EVP_CIPHER_fetch() Failed\n");
                        return 1;
            }

            if (!::EVP_EncryptInit_ex2(pRC4Ctx, pRC4, (const unsigned char*)pKey, NULL, NULL))
            {
                        printf("EVP_EncryptInit_ex2() Failed\n");
                        return 1;
            }

            if (!::EVP_EncryptUpdate(pRC4Ctx, pOutput, &iOutLen, (const unsigned char*)pInput, iInputLen))
            {
                        printf("EVP_EncryptUpdate() Failed\n");
                        return 1;
            }

            ::EVP_EncryptFinal_ex(pRC4Ctx, pOutput + iOutLen, &iTmpLen);
            ::EVP_CIPHER_free(pRC4);
            ::EVP_CIPHER_CTX_free(pRC4Ctx);
```

I would expect the result of both pieces of code to produce the same cipher text given the same key and input data but this is not the case when the key is as above (i.e. some arbitrary string).  The results are the same if I make the key a 128 bit string (e.g. "0123456789ABCDEF") which makes me think I need to do something with the key before supplying it to EVP_EncryptInit_ex2(…) but I cannot find anything to say what that should be.  Any help would be much appreciated.

Thanks,
Paul

**Comment by t8m** [comment]
> I have tried to put this question in the [openssl-users@openssl.org](mailto:openssl-users@openssl.org) mailing list but I given up waiting for my request to join it to happen.

You need to subscribe to the mailing list via:
https://mta.openssl.org/mailman/listinfo/openssl-users

As for the arbitrary key length support, you need to set the OSSL_CIPHER_PARAM_KEYLEN OSSL_PARAM to set the actual key length, otherwise 128 bits is used by default.

```
size_t key_length;
OSSL_PARAM params[2]= {
        OSSL_PARAM_END, OSSL_PARAM_END
};

params[0] = OSSL_PARAM_construct_size_t(OSSL_CIPHER_PARAM_KEYLEN, key_length);

EVP_EncryptInit_ex2(........., params)
```

**Comment by pcaswell** [comment]
Thanks t8m,
I have subscribed (twice) at the URL you posted but I've got no response and cannot post.  Maybe I just need to wait longer. Thanks very much for your help, I'll give it a go.
Paul

**Comment by pcaswell** [comment]
Unfortunately I still get a different result.  Here's the test code "as is " with the key length parameter included.

```
	const int iOutputLen = 512;
	unsigned char* pOutput = new unsigned char[iOutputLen];
	memset(pOutput, 0, iOutputLen);
	const char* pInput = "The quick brown fox jumped over the lazy frog";
	const int iInputLen = (int)strlen(pInput);

#define TEST_RC4
#ifdef TEST_RC4
	{
		const char* pKey = "Some arbitrary passphrase string";
		int iKeyLen = (int)strlen(pKey);
		int iOutLen(0), iTmpLen(0);

		// OLD
		RC4_KEY oRC4Key;
		RC4_set_key(&oRC4Key, iKeyLen, (const unsigned char*)pKey);
		RC4(&oRC4Key, iInputLen, (const unsigned char*)pInput, pOutput);
		printf("(OLD) RC4 calculation\n");
		printf_array(pOutput, iInputLen);

		// NEW
		memset(pOutput, 0, iOutputLen);
		EVP_CIPHER_CTX* pRC4Ctx = EVP_CIPHER_CTX_new();
		if (!pRC4Ctx)
		{
			printf("EVP_CIPHER_CTX_new() Failed\n");
			return 1;
		}

		EVP_CIPHER* pRC4 = EVP_CIPHER_fetch(NULL, "RC4", NULL);
		if (!pRC4)
		{
			printf("EVP_CIPHER_fetch() Failed\n");
			return 1;
		}

		size_t iKeyLenParam = (strlen(pKey) * 8);   // I have tried this with both byte and bit length - neither work
		OSSL_PARAM oParams[2] = 
		{
			OSSL_PARAM_END, OSSL_PARAM_END
		};
		oParams[0] = OSSL_PARAM_construct_size_t(OSSL_CIPHER_PARAM_KEYLEN, &iKeyLenParam);

		if (!::EVP_EncryptInit_ex2(pRC4Ctx, pRC4, (const unsigned char*)pKey, NULL, oParams))
		{
			printf("EVP_EncryptInit_ex2() Failed\n");
			return 1;
		}

		if (!::EVP_EncryptUpdate(pRC4Ctx, pOutput, &iOutLen, (const unsigned char*)pInput, iInputLen))
		{
			printf("EVP_EncryptUpdate() Failed\n");
			return 1;
		}

		::EVP_EncryptFinal_ex(pRC4Ctx, pOutput + iOutLen, &iTmpLen);
		::EVP_CIPHER_free(pRC4);
		::EVP_CIPHER_CTX_free(pRC4Ctx);
		printf("(NEW) RC4 calculation\n");
		printf_array(pOutput, iOutLen + iTmpLen);
	}
#endif
```

The printf_array() function simply outputs the supplied buffer as a hex string to the console.  I'd expect the results to be the same but I get:

```
(OLD) RC4 calculation
4c7352e08f666d73502b513e5556c216d657f74a9d030ea3bb79540051c796ac2334cbabaf3e7eb0ca5131c053
(NEW) RC4 calculation
6688766fb4b0d5242e076989d87fe6eace96b1ab862120daaeb3a652da840fcb4c47cda1c5804bc74d7b3fe37e
```

I can't see any mistakes so any further thoughts much appreciated.  
Paul

**Comment by t8m** [comment]
> Thanks t8m, I have subscribed (twice) at the URL you posted but I've got no response and cannot post. Maybe I just need to wait longer. Thanks very much for your help, I'll give it a go. Paul

Hmm now I tried with gmail e-mail account and the confirmation e-mail ended up in the spam folder. We need to investigate that.

**Comment by pcaswell** [comment]
> 
> That's weird, you should receive the e-mail with confirmation link in a few minutes at the latest, I've verified that. Perhaps it is dropped by some spam filtering for you or something like that?

I've looked everywhere and can't find an e-mail.  I got one saying I needed to subscribe though (having already done so) but nothing else.

**Comment by levitte** [comment]
I have a sneaking suspicion that we don't quite treat the params right.  I made a small program from the code example above that I currently run through a debugger, and the keylen given through the OSSL_CIPHER_PARAM_KEYLEN doesn't quite catch on.  It should be 32, but what ends up being passed to the legacy provider's RC4_set_key() call is the key length 16...

I'll get back when I can say something more definitive.

**Comment by levitte** [comment]
Found it.

https://github.com/openssl/openssl/blob/04e0abc8bb1c24534d16cc930b611ac1d03bc9bf/crypto/evp/evp_enc.c#L237-L244

Line 239-240 passes the default key length (which happens to be 16 a.k.a. 128 bits), which `rc4_einit()` assumes to be the length of the passed key, no matter what key length is given through the passed `params`.

It's a bit of a catch-22.

The workaround is a two initialization steps (and oh, the key length should be given in bytes, not bits):

``` diff
-		size_t iKeyLenParam = (strlen(pKey) * 8);   // I have tried this with both byte and bit length - neither work
+		size_t iKeyLenParam = strlen(pKey);
 		OSSL_PARAM oParams[2] = 
 		{
 			OSSL_PARAM_END, OSSL_PARAM_END
 		};
 		oParams[0] = OSSL_PARAM_construct_size_t(OSSL_CIPHER_PARAM_KEYLEN, &iKeyLenParam);
+
+		if (!::EVP_EncryptInit_ex2(pRC4Ctx, pRC4, NULL, NULL, oParams))
+		{
+			printf("EVP_EncryptInit_ex2() with oParams Failed\n");
+			return 1;
+		}

-		if (!::EVP_EncryptInit_ex2(pRC4Ctx, pRC4, (const unsigned char*)pKey, NULL, oParams))
+		if (!::EVP_EncryptInit_ex2(pRC4Ctx, NULL, (const unsigned char*)pKey, NULL, NULL))
 		{
 			printf("EVP_EncryptInit_ex2() Failed\n");
 			return 1;
 		}
```

**Comment by levitte** [comment]
Note that this sort of multi-step init isn't new, the Cipher and Digest init functions have been designed for that sort of thing since way back.

**Comment by pcaswell** [comment]
> Note that this sort of multi-step init isn't new, the Cipher and Digest init functions have been designed for that sort of thing since way back.

Now you mention it I have seen that in the documentation somewhere.  Thanks very much for the help.

**Comment by pcaswell** [comment]
Yep, the two stage initialization identified by Richard Levitte does indeed work.
