### ISSUE TITLE
How to use digest in ED22519 algorithm?

### ISSUE THREAD

**Issue by shirley4** [openssl/openssl#20768]
Openssl version used:  3.1.0

I used the following steps with ED22519:

- Generate Ed25519 private key:
   ```openssl genpkey -algorithm Ed25519 -out <private_key_file>```
- Extract public key from private key:
  ```openssl pkey -in <private_key_file> -pubout -out <public_key_file>```
- Signed the binary with the private key:
  ``` openssl pkeyutl -sign -inkey <private_key_file> -out <signature_file> -rawin -in <binary_file>```
  
Until this point, the process had gone successfully. But when I tried to use digest, I received an error.

Command I used to sign with digest:
      ```openssl pkeyutl -sign -in <binary_file> -inkey <private_key_file> -out <signature_file> -keyform PEM -pkeyopt ed25519 -sigopt digest:sha512```

The error I received:

pkeyutl: Error initializing context
081C0000:error:03000096:digital envelope routines:evp_pkey_signature_init:operation not supported for this keytype:crypto\evp\signature.c:530:

Can anyone suggest how to include digest sha-512 while signing a binary with ED22519 algorithm?

**Comment by levitte** [comment]
You don't.  The choice of hash functions is a part of the signature scheme itself, not a parameter chosen or computed by a user.  It should be enough to remove `-sigopt digest:sha512` from that command line

**Comment by shirley4** [comment]
@levitte  Thank you for the quick reply!
How do we know the sha algorithm(sha-256 or sha-512) used while signing? Is sha-512 the default hashing algorithm used in Ed22519?

**Comment by t8m** [comment]
Please see the manual page for Ed22519 - https://www.openssl.org/docs/man3.0/man7/Ed25519.html and RFC 8032 https://www.rfc-editor.org/rfc/rfc8032

And yes, internally the PureEdDSA with the Ed22519 curve uses SHA512.

**Comment by shirley4** [comment]
@t8m Thank you for the help!

**Comment by song1chi** [comment]
I know it is closed but ...

What is ED22519 or Ed22519? 
Is it ED25519 or Ed25519?

**Comment by mspncp** [comment]
Ed22519 is just a misspelling of Ed25519.
