### ISSUE TITLE
SSL_is_init_finished returns 1 in client, despite it has not received handshake finish from server

### ISSUE THREAD

**Issue by MelznerDSA** [openssl/openssl#20771]
I wrote a client an server using OpenSSL 3.1 build on Windows 10.
I am using memory bios for handshake and transmit/receive payload, in order to handle the sockets in the application and just pass the buffers to the OpenSSL functions (SSL_write, BIO_read, BIO_write,and SSL_read).

So as long as **SSL_is_init_finished** does not return 1, I keep BIO_read/BIO_write from with the buffers that are coming from the socket (non-blocking). Now when the client has reached the state when it sends out "client finished", the SSL_is_init_finished returns 1, but it has not received the server finished yet (and any other messages the server might send with/before the finished).

Now as SSL_is_init_finished has returned 1, my client application starts sending payload data even before the server finished was received. This leads now to the problem that the client fails to decrypt the next message from the server that comes on the socket along with the server handshake finished message.

So my question: Is there any other API function to check if the server handshake finished message was received?
Or is there any practice to handle waiting for server finished after SSL_is_init_finished is 1 in a client when using memory bios and non blocking sockets.

**Comment by mattcaswell** [comment]
> Now when the client has reached the state when it sends out "client finished", the SSL_is_init_finished returns 1, but it has not received the server finished yet (and any other messages the server might send with/before the finished).

That sounds like unexpected behaviour. `SSL_is_init_finished()` should not return 1 until an endpoint has both sent and received its Finished messages.

What TLS protocol version is being negotiated? Note that in TLSv1.3, the client receives the server's "Finished" message *first*, so it is correct for `SSL_is_init_finished()` to return 1 immediately after the client's "Finished" has been sent in this case.

**Comment by MelznerDSA** [comment]
You are right, there was indeed 1.3 negotiated. But then could you help me unterstand what is send after this "finished" that causes a Problem.

The sequence is like this
-Client sends Hello (253 bytes)

-Server received Client Hello
-Server send Server Hello, 1.3 negotiated, Change Cipher Spec, finish (1619 bytes)

-Client received, Server Hello (1619 bytes)
-Client handshake complete and sends Change Cipher Spec + finish probably (94 bytes)

-Server received 94 bytes, handshake complete on server side.
-**Server BIO wants to send 478 bytes and those are send to Client - ???**

-Client starts to send payload data -> 41 bytes encrypted

-Server received those 41 bytes, sends payload answer with 43 bytes encrypted data.

-**Client received 478 bytes that the server BIO wanted to send**
-Client received the 43 bytes of the server encrypted payload

On the client then: OpenSSL Error:error:0A000119:SSL routines::decryption failed or bad record mac

**Comment by mattcaswell** [comment]
> -Server BIO wants to send 478 bytes and those are send to Client - ???

These are post-handshake NewSessionTicket messages. An OpenSSL server will automatically send 2 NewSessionTicket messages immediately after the handshake is complete.

**Comment by MelznerDSA** [comment]
Ah, I see.
I tested again and found a bug in my buffer handling that caused a wrong write to the BIO in that case. I fixed it and now got a successful decryption also in that sequence. 
Thank you very much!
