### ISSUE TITLE
Errors in config file values get swallowed, disable other directives

### ISSUE THREAD

**Issue by t184256** [openssl/openssl#20789]
OpenSSL master (c8093347, `./config no-shared)`.

I'm gonna define the following config
for use with `OPENSSL_CONF=openssl.cnf apps/openssl s_client ecc256.badssl.com:443`
and vary just the last two lines for brewity.

```
config_diagnostics = 1
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect
ssl_conf = ssl_module

[provider_sect]

[ssl_module]
system_default = policy

[policy]
SignatureAlgorithms = ECDSA+SHA256
#Groups = P-521
```

That allows me to establish a TLS 1.2 connection using ECDSA-SHA256 and prime256v1.

Uncommenting `Groups`:

```
SignatureAlgorithms = ECDSA+SHA256
Groups = P-521
```

leads to SSL alert number 40, which I'm OK with.

Now let's add an unrecognized value to `Groups`:

```
SignatureAlgorithms = ECDSA+SHA256
Groups = P-521:nonex
```

That results in a successful connection like in a baseline case,
so I'm assuming `Groups` reverts to whatever default it has.

What's worse, is that this effect works across lines:

```
SignatureAlgorithms = ECDSA+SHA256:nonex
Groups = P-521
```

also results in a successful connection, as if `Groups` is ignored!

Finally, switching the order of the directives

```
Groups = P-521
SignatureAlgorithms = ECDSA+SHA256:nonex
```

makes the masking effect go away (connection fails),
so I assume it's the rest of the config (section?) that gets ignored
after encountering one invalid value.

I'm aware of `config_diagnostics = 1`, but it doesn't seem to help here.

Please consider failing hard on encountering an invalid/unrecognized value.
Not only the current behaviour is painfully error prone,
(`Groups = P-384:P-512` is the same as `Groups = P-384,P-521`)
but also the scope of the resulting misconfiguration is much wider than my wildest imagination
(they both effectively mean "ignore this and following lines", somehow).
As a result, it becomes very hard to configure the algorithm selection in a robust and secure manner.

**Comment by mattcaswell** [comment]
> What's worse, is that this effect works across lines:

It should not have an impact across lines

> SignatureAlgorithms = ECDSA+SHA256:nonex

My assumption is that the default sigalgs are being used and some non-ec based cipher suite is negotiated meaning that the "Groups" config value is not relevant.

**Comment by t184256** [comment]
> My assumption is that the default sigalgs are being used and some non-ec based cipher suite is negotiated meaning that the "Groups" config value is not relevant.

That'd be great, but the last example (reordering of lines changing the outcome) seems to refute it.

**Comment by mattcaswell** [comment]
>That'd be great, but the last example (reordering of lines changing the outcome) seems to refute it.

Hmm. Good point. That does seem odd. There shouldn't be any across line effects...requires further investigation as to what is happening here.

**Comment by beldmit** [comment]
Looks like we totally missed this issue...

**Comment by beldmit** [comment]
Looks like high-level logic here is problematic:

https://github.com/openssl/openssl/blob/addbd743b5ceeca93dafd59600ba92b87f916e12/ssl/ssl_mcnf.c#L73-L80

If we got a "bad value" error here, we stop processing the directives

**Comment by t8m** [comment]
@beldmit Do you want to tackle this issue yourself? Otherwise I can look at it.

**Comment by t8m** [comment]
> If we got a "bad value" error here, we stop processing the directives

Yeah, we should just raise the error and continue processing (also mark that an error was found to return 0).

So that's one issue.

Another issue is that unknown algorithm in these algorithm lists should not be an error, it should be just ignored.

**Comment by beldmit** [comment]
I have drown in the callbacks calling callbacks so if you could take care of it, it would be great. We found that because of this issue we got stuck with enabling PQ groups when the oqs provider is not present

**Comment by beldmit** [comment]
Just for the record. Every provider-dependent parameter should be dealt with this way: we should ignore the values we don't know. 

I hardly can imagine the way to test it. Config low-level parsing functions are probably the best approach here...

**Comment by t8m** [comment]
The PR to fix the _ignore the remaining config entries after an incorrect one_ is in #23048. I'll do a separate PR to ignore unknown values in  Groups, SignatureAlgorithms, and ClientSignatureAlgorithms as that might be seen as something not desirable for stable branches.
