### ISSUE TITLE
State of tsget.pl

### ISSUE THREAD

**Issue by Lipovlan** [openssl/openssl#20794]
Similar question to https://github.com/openssl/openssl/issues/20793, what is the state of `tsget.pl`?

In `3.2.0` it is being built but not installed with `install_sw` from `makefile`.

It seems to me, that it has been superseded by the `openssl-ts` command, but it still remains in the repository and has a manpage.

**Comment by nhorman** [comment]
like with CA.pl, you're welcome to modify the build file to include it in the installation, but there are no plans to iinclude it in the official release
