### ISSUE TITLE
Debian 11 (bullseye) support openssl version >= 3?

### ISSUE THREAD

**Issue by dinesh1310** [openssl/openssl#20809]
does openssl 3 supports debian 11. we're planning to migrate our application from 1.1.1n to 3.0.8 . what happens if we migrate it into version 3 does it involve any breakage or better to use debian 12? because it comes with stable openssl 3 version

**Comment by t8m** [comment]
The migration guide should describe any potential issues and/or requirements for migrating applications from 1.1.1 to 3.0 versions:

https://www.openssl.org/docs/man3.0/man7/migration_guide.html
