### ISSUE TITLE
http_lib.c should not use getenv() directly

### ISSUE THREAD

**Issue by jpboivin** [openssl/openssl#20802]
Hello,

Most of the OpenSSL codebase uses `ossl_safe_getenv`, except for `cpuid` which has its own simplified `ossl_getenv`. `http_lib.c` does not follow this in `use_proxy`:
https://github.com/openssl/openssl/blob/4e5f3d691343a691ddae739c51f7ae71e9893c98/crypto/http/http_lib.c#L256

nor in `OSSL_HTTP_adapt_proxy:
https://github.com/openssl/openssl/blob/4e5f3d691343a691ddae739c51f7ae71e9893c98/crypto/http/http_lib.c#L278

This is a portability issue potentially for platforms without a working `getenv` (the system call is no longer localized). I didn't dig further to see if not using the "safe" variant of `getenv` as implemented by OpenSSL could also have security impacts in the HTTP code.

Let me know if I missed something and my report does not make sense!
Best regards

**Comment by t8m** [comment]
> can I work on this?

Sure, go ahead.

**Comment by t8m** [comment]
Fixed by #20810
