### ISSUE TITLE
OpenSSL 3.1 FIPS

### ISSUE THREAD

**Issue by srikar-rubrik** [openssl/openssl#20800]
Hello everyone,

I've gone through your [update](https://www.openssl.org/blog/blog/2023/03/07/OpenSSL3.1Release/) about OpenSSL 3.1 and I have a couple of questions about the FIPS provider:

1. It's mentioned that the FIPS provider module is now compliant with FIPS 140-3 validation. Does it mean it's still compliant with the FIPS 140-2?
2. It's mentioned that some of the algorithms are deprecated now with `fips=yes`. Is it done for getting FIPS 140-3 certification? Let's say, I'm okay if my application is compliant with 140-2, then can I ignore the `fips=yes` warning when I'm running only with FIPS provider as the default context?
3. I see that quite a lot of performance fixes have been made. Are these done only in the FIPS provider? Is there any documentation or writing showing the performance difference between FIPS vs non-FIPS mode?

**Comment by mattcaswell** [comment]
> It's mentioned that the FIPS provider module is now compliant with FIPS 140-3 validation. Does it mean it's still compliant with the FIPS 140-2?

No. We are submitting the 3.1.0 provider for a 140-3 validation only. It will not be 140-2 validated and is not designed with that in mind.

> It's mentioned that some of the algorithms are deprecated now with fips=yes. Is it done for getting FIPS 140-3 certification? Let's say, I'm okay if my application is compliant with 140-2, then can I ignore the fips=yes warning when I'm running only with FIPS provider as the default context?

The only current FIPS module we have that is 140-2 validated is 3.0.0. The 3.0.8 provider is currently undergoing validation for 140-2.

If 140-2 is important to you then you can use the OpenSSL 3.1 libraries, but use the 3.0.0 provider (this is a supported configuration). In which case the "fips=yes" notes in the update you refer to are irrelevant.

> I see that quite a lot of performance fixes have been made. Are these done only in the FIPS provider?

They are done throughout the source code. Some improvements maybe inside the FIPS boundary and some outside it. A number of performance improvements are inside the libraries and are beneficial whether or not use the FIPS provider.

> Is there any documentation or writing showing the performance difference between FIPS vs non-FIPS mode?

Not that I am aware of.

**Comment by t8m** [comment]
I would also add that using 3.1.0 library with 3.0.0 (or later 3.0.x provider when/if validated) should bring most performance improvement benefits. Of course some of them like new assembler implementations of some algorithms for some platforms won't apply. But things like improved multithreaded and decoder performance will.

**Comment by srikar-rubrik** [comment]
Thanks a lot, @mattcaswell and @t8m! Cool I'll try to use 3.1 with 3.0 FIPS.

Btw, currently, we were planning to use OpenSSL 3.0.7. So, isn't that FIPS validated? Only 3.0.0 is FIPS validated?

**Comment by mattcaswell** [comment]
Only 3.0.0 is validated. Again you can use 3.0.7 (or better 3.0.8) with the 3.0.0 FIPS provider if you wish. 3.0.8 is undergoing validation - but the validation queue is long and so this is unlikely to happen for some while.

**Comment by srikar-rubrik** [comment]
Got it! Thanks for your answer. I'll try using the 3.0.0 provider with a 3.1/3.0.7 base.
