### ISSUE TITLE
Building with shared dynamic zlib : undefined symbol: BIO_f_zlib

### ISSUE THREAD

**Issue by Stevemoretz** [openssl/openssl#20811]
Hello I'm trying to make stunnel's compression work, it gave me an error that it needs openssl to use zlib, so I downloaded the same version as  my Ubuntu 22 original openssl 3.0.2 then rebuilt it both dynamically and statically, I get this error
`undefined symbol: BIO_f_zlib`

There aren't exactly any working tutorials out there either, I didn't think doing this would be this hard.

**Comment by t8m** [comment]
You need to use `zlib` (or `enable-zlib` which is completely equivalent) during the Configure step of the build as written in INSTALL.md.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
