### ISSUE TITLE
How to modify the TLS version in the record layer of a client hello message 

### ISSUE THREAD

**Issue by akang026** [openssl/openssl#20817]
How to modify the TLS version in the record layer of a client hello message using OpenSSL version 1.1.1. By default, the version is set to TLS 1.0, but I want to modify it ( TLSPlaintext.version ) to TLS 1.2. 
In addition, I also want to ask whether the current version 1.1.1 can support this modification, if not, please recommend a feasible version.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/64126808/233885050-668d1957-e4e1-4e13-a4ca-e37bca4b58b8.png">

This is the result obtained after testing with two tools and my main purpose is to run on the first one (libwebsockets)
1. libwebsockets-full (v4.3.2) with openssl (v1.0.2u and v1.1.1d) (on ubuntu and openwrt)
2. openssl s_client (v3.1.0) with "-no_ssl3 -no_tls1 -no_tls1_1" (on windows 10)

regards

**Comment by mattcaswell** [comment]
OpenSSL does not offer an API for modifying the record layer version in the ClientHello. It is always set to TLSv1.0 for the initial ClientHello.

But why would you want to do this anyway? It should be ignored by the server.

**Comment by akang026** [comment]
Got it, thank you very much for your prompt reply and answer

**Comment by NannanMao** [comment]
curl -k -v https://umapmgs.test.abchina.com.cn/test/MBCM-OH/MDS/resource/updateAll
* Trying 223.72.214.81:443...
* Connected to umapmgs.test.abchina.com.cn (223.72.214.81) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:0A000152:SSL routines::unsafe legacy renegotiation disabled
* Closing connection 0
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled


The error message looks like: curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled


I used curl command to connect to the server, and I met this errorcode too.


The curl version I used is like this:
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

**Comment by mattcaswell** [comment]
@NannanMao - please raise this as a new issue rather than adding to an unrelated and closed old issue.

**Comment by KongLynn** [comment]
> It is always set to TLSv1.0 for the initial ClientHello.

Dear Author，
Why it is always set to TLSv1.0 for the initial ClientHello？

**Comment by sblackstone** [comment]
> > It is always set to TLSv1.0 for the initial ClientHello.
> 
> Dear Author， Why it is always set to TLSv1.0 for the initial ClientHello？In some blogs（[https://www.analysisman.com/2021/06/wireshark-tls1.2.html）](https://www.analysisman.com/2021/06/wireshark-tls1.2.html%EF%BC%89), it is written that the record layer version represents the minimum version supported by the client. If it is TLS 1.0, it means the client supports 1.0. Some security standards require clients to disable TLS 1.0 and 1.1.

https://datatracker.ietf.org/doc/html/rfc8446#section-5.1

The standard requires the server to completely ignore this field.  Furthermore, it says a client may set it to TLS1 on the initial client hello..
