### ISSUE TITLE
OpenSSL 3.0 may generate RSA keys with p < q

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#20823]
OpenSSL 1.x used to have a check during RSA key generation to avoid generating RSA keys where p < q. 

It seems that with OpenSSL 3.0 this check is no longer done. We are easily able to generate RSA keys with p < q with the following command:
```
# openssl genrsa -out testprivkey.pem 2048
# openssl rsa -noout -text -in testprivkey.pem
...
prime1: 
   00:c0:30:66:db:47:55:de:54:2c:34:6a:00:7b:b3: 
...
prime2: 
   00:e2:3b:79:7b:58:7a:a6:85:c9:db:0c:73:51:7b: 
...
```

`00c0...` is less than `00e2...`.

In OpenSSL 1.1.1 the check is in function `rsa_builtin_keygen()` in crypto/rsa/res_gen.c:

```
    if (BN_cmp(rsa->p, rsa->q) < 0) {
        tmp = rsa->p;
        rsa->p = rsa->q;
        rsa->q = tmp;
    }
```

It swaps p and q if p < q, and subsequently calculates the other key components. As a result you always have a key with p > q.

The same code is still there in OpenSSL 3.0 in function `rsa_multiprime_keygen()`, but it seems that in case of FIPS and also for keys >= 2K with 2 primes function `ossl_rsa_sp800_56b_generate_key()` is used instead. I don't see a check for p< q in `ossl_rsa_sp800_56b_generate_key()` or `ossl_rsa_fips186_4_gen_prob_primes()` ....

**Comment by t8m** [comment]
Is it really a problem?

**Comment by ifranzki** [comment]
Unfortunately yes. Some RSA hardware acceleration units don't like RSA keys with p < q.

**Comment by ifranzki** [comment]
In `s390x_crt()` in crypto/bn/bn_s390.c we check for p < q and fall back to software if so. So around half of the generated RSA keys won't be accelerated I guess....

**Comment by t8m** [comment]
@slontis would it break fips compliance if we added the p, q swap in the FIPS keygen as well?

**Comment by juergenchrist** [comment]
Not that it helps, but `s390x_crt` cannot be used in FIPS mode.  Also, having `p<q` for CRT makes the math kind of strange (finding the inverse of `q` modulo `p` when `q > p` is something that - depending on the definition used - is undefined).

**Comment by slontis** [comment]
Just looking at what the algorithm does indicates they are interchangeable:

````ossl_rsa_fips186_4_gen_prob_primes()```` uses the same function to generate random p & q and then just checks that |Xp -Xq| and |p-q| are both > 2^(nbitlen/2 - 100).

ossl_rsa_sp800_56b_generate_key() then calls derive_params_from_pq() so the swap would need to be before this call..

as long as the checks in ossl_rsa_check_crt_components() still hold e.g. 1 < qInv < p...

You also wouldnt want to do the swap if the ACVP_TESTS were being used..

**Comment by slontis** [comment]
This test must have been added for hardware because it doesnt matter for the keygen algorithm.

**Comment by davidben** [comment]
p > q comes up for RSA CRT, where it's not quite symmetric (iqmp). If p is the bigger prime, you avoid a reduction in one step, and worrying about the constant-time implications. (Otherwise you have to reason about whether p and q are allowed to have different bit lengths, and it's a whole nuisance.)

**Comment by t8m** [comment]
> (Otherwise you have to reason about whether p and q are allowed to have different bit lengths, and it's a whole nuisance.)

AFAIK in the FIPS keygen the p and q have the same bit length. @slontis?
