### ISSUE TITLE
Interesting TCP-level segmentation behavior during handshake due to write buffer size and buffer management

### ISSUE THREAD

**Issue by J-BLSec** [openssl/openssl#20820]
While studying TLS performance with PQC and hybrid cryptography, based on Open Quantum Safe’s OpenSSL 1.1.1 fork, an academic partner of ours ([Chair of Network Architectures and Services ](https://www.net.in.tum.de/)at Technical University of Munich) found some interesting OpenSSL behavior:

For some PQC KEM algorithms, the TLS 1.3 Server Hello would be sent back-to-back in the same TCP segment with the subsequent TLS messages (Change Cipher Spec etc.), like it is typical for traditional KEX algorithms as well. 

Example x25519, test.openquantumsafe.org: 
![image](https://user-images.githubusercontent.com/130991065/234060338-9f38eaf7-b175-422e-8927-a365f527e447.png)
 
But for others, the Server Hello would be the last message in a TCP segment (or sequence of TCP segments), even if the (last) TCP segment wasn’t completely full. And the following TLS message would start with a new TCP segment.

Example hqc128 test.openquantumsafe.org:
![image](https://user-images.githubusercontent.com/130991065/234060412-44ec7cc6-3374-46c8-a87d-c06571e34aae.png)

 Looking into the above, I found another interesting behavior: The TLS messages that follow the Server Hello are typically sent back-to-back, potentially spanning and filling multiple TCP segments. However, sometimes, a TCP segment somewhere in the middle of the flight would have a length shorter than the possible TCP MSS, and would have the TCP PSH flag set. And this does not coincide with TLS message boundaries.

Example OpenSSL website:
![image](https://user-images.githubusercontent.com/130991065/234060692-33581a91-6503-4096-bd70-bf744402cfdc.png)
 
Digging into this, I found that the observed behavior seems to come from the fact that [writing of the handshake messages to the network is buffered](https://github.com/openssl/openssl/blob/master/ssl/statem/statem.c#L456); that the [default (and minimal) buffer size is 4096 octets](https://github.com/openssl/openssl/blob/master/doc/man3/BIO_f_buffer.pod); and due to [how the buffer is being managed](https://github.com/openssl/openssl/blob/master/crypto/bio/bf_buff.c#L158). This combination explains the behavior above:

- When the Server Hello is written to the buffer, the buffer is typically empty. If the size of the Server Hello exceeds the buffer capacity (as it does with some PQC KEMs), [the entire Server Hello is written to the network right away](https://github.com/openssl/openssl/blob/master/crypto/bio/bf_buff.c#L212).

- When e.g. the Certificate message is written to the buffer, the buffer is typically NOT empty (it has at least the Change Cipher Spec, Encrypted Extensions, and possibly also the Server Hello in it). Now, when the certificate chain exceeds a certain length, trying to add the Certificate message to the buffer would [exceed the remaining buffer space](https://github.com/openssl/openssl/blob/master/crypto/bio/bf_buff.c#L173). As there is something in the buffer already, the [buffer is topped off with part of the Certificate message](https://github.com/openssl/openssl/blob/master/crypto/bio/bf_buff.c#L180), and then the [full buffer is written to the network](https://github.com/openssl/openssl/blob/master/crypto/bio/bf_buff.c#L189). As the 4096 octet buffer size typically does not align with a multiple of the TCP MSS, a TCP segment with length less than MSS results. 

- The remainder of the Certificate message is handled by starting again at the first bullet, i.e. try to put it into the buffer (which is now empty again). Thus, the partial Certificate message starts a new TCP segment.

While the behavior was originally found in a 1.1.1 fork, it seems it hasn’t changed since. I can provide examples e.g., with publicly deployed OpenSSL 3.0.1, and the involved code parts haven’t changed in this respect.

Considering those observations, I was wondering whether anyone more familiar with those aspects could shed some light on the following:

- Is this known behavior? (I did some research, didn’t find anything, but maybe I just missed it.)

- What was the reason behind this particular buffer management design for writing to the network? Any thoughts as to whether it might make sense to revisit that design and/or the default buffer size used during the TLS handshake?

- What are thoughts on whether it could make sense to always (or conditionally) force the Server Hello onto the wire right away without waiting for subsequent messages to become ready for sending? At least in some cases, that could improve handshake latency as it gives the client a head-start in processing the Server Hello already before the remaining TLS messages arrive as well.

**Comment by t8m** [comment]
> * What are thoughts on whether it could make sense to always (or conditionally) force the Server Hello onto the wire right away without waiting for subsequent messages to become ready for sending? At least in some cases, that could improve handshake latency as it gives the client a head-start in processing the Server Hello already before the remaining TLS messages arrive as well.

I cannot answer the other questions however this would make sense to me. At least making it a configurable option via a SSL_MODE flag would make some sense.

**Comment by t-j-h** [comment]
Refer to [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm) for the reason for handshake message buffering.
Many things will get somewhat upset with large certificate handling as you have noticed.
I do recollect a number of implementations existed at the time that choked on more than 4k turning up during processing.

**Comment by J-BLSec** [comment]
> > * What are thoughts on whether it could make sense to always (or conditionally) force the Server Hello onto the wire right away without waiting for subsequent messages to become ready for sending? At least in some cases, that could improve handshake latency as it gives the client a head-start in processing the Server Hello already before the remaining TLS messages arrive as well.
> 
> I cannot answer the other questions however this would make sense to me. At least making it a configurable option via a SSL_MODE flag would make some sense.

Ok, thanks. Indeed, while I put it in brackets, having this conditionally would have been my preference, too. There's too many factors that have a bearing on whether having this enabled in a specific context, or rather not, for there to be a one-size-fits-all solution (i.e., always enabled unconditionally). Thanks for the hint about the SSL_MODE flag, I'll explore that.

**Comment by J-BLSec** [comment]
> > What was the reason behind this particular buffer management design for writing to the network? Any thoughts as to whether it might make sense to revisit that design and/or the default buffer size used during the TLS handshake?
> 
> The reasoning behind all of this is lost in the mists of time. That particular code has existed since pre-OpenSSL times and was part of the original SSLeay import when OpenSSL was established. The original code is virtually unchanged from today's version:
> 
> https://github.com/openssl/openssl/blob/SSLeay_0_8_1b/crypto/bio/bf_buff.c#L211-L285

Ok, thanks for that clarification. Indeed, no hard proof, but the impression I got was that maybe initially, there was a desire to have some buffering during the handshake, the bf_buff mechanism already existed, and while maybe intended for a different context (or at least not specifically for writing to the network), it was reused. E.g. the default size of 4096 octets seems more typical in memory or storage organization contexts. And the bf_buff seems to be used e.g. in non-network-related contexts as well.

Initially, the intricacies of its buffer management likely were irrelevant as the default buffer size was large enough for them not to be exposed (server flight of TLS handshake messages fit well into the default buffer size). But when TLS message sizes grew, they eventually started outgrowing the default buffer size so that the buffer management mechanism started to become relevant.

Anyhow, if the exact reasoning is lost in the mists of time, it seems worthwhile to reassess and come up with an approach that makes sense from the current point of view.

> I'd be open to suggestions about how to improve things. Modifying the default buffer size has implications though. Increasing it for all users would presumably increase memory consumption on servers processing large numbers of connections. Conceivably an expandable buffer size which only consumes as much memory as needed might be worthwhile. That could even have the added benefit of _decreasing_ memory consumption for users that don't need it.

Ok, updating the buffering mechanism seems a bit more involved, i.e. takes a bit more thought and discussion. E.g. I am far from understanding the various plumbings of BIOs that are involved in a TLS session to fathom at this time what a different buffering approach would entail. So maybe a three-step approach could be taken to get there:

- Start with a slight increase in default buffer size so that the typical current server TLS message flight would fit into the buffer. Idea would be to simply avoid triggering the intricate buffer management mechanisms for the majority of current cases with minimal effort. (PQC will require updating size assumptions in other places anyway, so taking PQC into account for the default buffer size could be deferred until those other size assumptions will need to be updated anyway. And maybe a more flexible buffering mechanism will be in place by that time anyway.)
- Size the buffer to better reflect network-related granularities (i.e. typical MSS values).
- Update the buffering mechanism itself to be more flexible/dynamic, as you suggest.

Those steps are only conceptual, reflecting aspects to be addressed, but e.g. the second item could to some degree also be covered in the first step, or handled in conjunction with the third one.

> > What are thoughts on whether it could make sense to always (or conditionally) force the Server Hello onto the wire right away without waiting for subsequent messages to become ready for sending? At least in some cases, that could improve handshake latency as it gives the client a head-start in processing the Server Hello already before the remaining TLS messages arrive as well.
> 
> I'm a little sceptical about whether that actually would make a measurable difference. I'd probably want to see some evidence to show that this actually makes things better in practice.

Understood, and I agree. Our limited testing showed some benefits in some circumstances, but not in others. I see that I can consolidate those and share. But even then, there's too many factors that have a bearing on this - algorithms used and sizes of resultant TLS messages, CPU speeds, network speeds and latencies, networking optimization techniques such as segmentation offload, traffic patterns, ... - for this to be a clear binary decision. So I think allowing an application to enable this functionality if its considered useful by its use cases, but having it off unless the application decides to explicitly enable it, as suggested by [Tomáš Mráz](https://github.com/t8m), is a good approach.

**Comment by J-BLSec** [comment]
> Refer to [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm) for the reason for handshake message buffering.

I was not questioning the purpose of handshake message buffering as such. Rather, the particular choice of the buffer size and the buffer management approach chosen, as they are leading to some interesting TCP-level behavior on the wire.

> Many things will get somewhat upset with large certificate handling as you have noticed.

We didn't observe anything getting upset with large certificates (as in breaking). We just noticed some odd behavior on the TCP level. More of a cosmetic thing, arguably with likely rather small impact on performance (IP packets not being as full as they could be), but not any actual breakage.

> I do recollect a number of implementations existed at the time that choked on more than 4k turning up during processing.

That would be interesting to know, obviously, what those limitations were, so as to check whether they still exist. A quick check indicates that public services at e.g. Google, Amazon, or Microsoft return certificate chains of up to roughly 6800 octets. So I'd assume that the number of clients to have problems with such sizes is sufficiently small for those services to use such certificate chains. Or they have some work-arounds in place that are not readily visible based on a packet trace alone.

**Comment by mahendra-msp** [comment]
Hello, when using the certificate chain, we are also facing a similar issue. Once server hello is sent, we see that server packet trace indicates PSH and certificate data. However the handshake fails. When not using certificate chain, everything works fine. Please let me know what additional data is needed to confirm if the issue seen by us is same as the one discussed here. Also, could you please let me know if there is any option available in Openssl to fix this behavior.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
