### ISSUE TITLE
client infinite loop

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#20821]
The current `client` fuzzer on OSS-Fuzz seems to have an infinite loop (or is at least very slow to finish).

```
$ ./client timeout-aad79c599856ffa8fdb9acebd2db138d0213375e -timeout=5
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1178031846
INFO: Loaded 1 modules   (83798 inline 8-bit counters): 83798 [0x105b5b0, 0x106fd06), 
INFO: Loaded 1 PC tables (83798 PCs): 83798 [0x106fd08,0x11b7268), 
./client: Running 1 inputs 1 time(s) each.
Running: timeout-aad79c599856ffa8fdb9acebd2db138d0213375e
ALARM: working on the last Unit for 5 seconds
       and the timeout value is 5 (use -timeout=N to change)
==1255762== ERROR: libFuzzer: timeout after 5 seconds
    #0 0x4ac401 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x518578 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x4fd1c9 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5
    #3 0x7f6b333a441f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #4 0x5e3c51 in ssl3_read_bytes /src/openssl/ssl/record/rec_layer_s3.c:772:13
    #5 0x5754e3 in ssl3_read_internal /src/openssl/ssl/s3_lib.c:4510:9
    #6 0x575244 in ssl3_read /src/openssl/ssl/s3_lib.c:4533:12
    #7 0x59b272 in ssl_read_internal /src/openssl/ssl/ssl_lib.c:2291:16
    #8 0x59bcd7 in SSL_read /src/openssl/ssl/ssl_lib.c:2305:11
    #9 0x4dfa5f in FuzzerTestOneInput /src/openssl/fuzz/client.c:92:17
    #10 0x4dfc5f in LLVMFuzzerTestOneInput /src/openssl/fuzz/driver.c:28:12
    #11 0x4fe7f3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #12 0x4e9f52 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #13 0x4ef7fc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #14 0x518d32 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #15 0x7f6b3319d082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: libFuzzer: timeout
```

Base64 of the input:

```
FgPwAD0CAAA5AwDe2BEAAAAHCfsL/0AOAQUARzEAAAAAwEcABQAAMAAAAADAFQAAEf8BAAEAABYA
AGZvAACAxQAAFgMAACwMAAAkAwAdIMgH//////3//18AAAAABP/r4/8BAEFveQEAAAAAAAA1DgAA
ABQDAAABARYDAAA9FAAAJBdfy0mr5CEMetylO2MEB4ZxD3JVvKBxrZVbdAijnhIAAAAAAAAAAAAA
AAAAAAAAAwMAPQMDAAAAFxYDAAAUAwEBAAAAAAABFgM98RQAACQXX8s=
```

Run `./client input.bin` after decoding the base64 to `input.bin`.

You can close this if you're already aware of it (OSS-Fuzz should have notified you).

**Comment by mattcaswell** [comment]
No, we didn't already know about this. Thanks for the report.

Fix in #20824.

**Comment by guidovranken** [comment]
Do you have any existing timeouts on OSS-Fuzz for the `client` fuzzer? Other than with memory bugs, OSS-Fuzz can not distinguish between different timeout bugs; hence it will only show (and notify you of) a maximum of 1 timeout bug per fuzzer.

**Comment by guidovranken** [comment]
@jonathanmetzman I found this simply by downloading the latest public OSS-Fuzz corpus and running the latest OSS-Fuzz build on it. Shouldn't OSS-Fuzz have found this?

**Comment by guidovranken** [comment]
Thank you!

Here's how to reproduce:

```
gsutil cp gs://clusterfuzz-builds/openssl/openssl-address-202304250612.zip .
unzip openssl-address-202304250612.zip
gsutil cp gs://openssl-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/openssl_client/public.zip .
unzip public.zip -d corp/
./client corp/aad79c599856ffa8fdb9acebd2db138d0213375e -timeout=5
```

**Comment by jonathanmetzman** [comment]
This was reported by oss-fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57971&q=proj-openssl%20timeout%20client&can=2
OpenSSL team, is there anything we can do to make it easier to deal with our bug reports? It seems like openssl would benefit and oss-fuzz could improve based on this feedback.

**Comment by mattcaswell** [comment]
> This was reported by oss-fuzz

Hmm. I can see that report when I click on your link, but not when I look here:

https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label%3AProj-openssl

What am I doing wrong with that query?

> OpenSSL team, is there anything we can do to make it easier to deal with our bug reports? 

The biggest problem I have is the signal-to-noise ratio. I seem to get a large number of notifications in my inbox between the two relevant projects (openssl and cryptofuzz) to the point that I mentally filter most of them out and I'm probably missing important reports. In the cryptofuzz case I think there are quite a lot of notifications which aren't actually about OpenSSL at all. If we could find a way to reduce the number of notifications to only include important things that we really need to look at, then that would help a lot.

**Comment by mattcaswell** [comment]
> Hmm. I can see that report when I click on your link, but not when I look here:

Ah! I figured out why I couldn't see them...logged into the wrong google account. Probably it would be better to have my openssl.org email associated with oss-fuzz rather than my personal one.

**Comment by jonathanmetzman** [comment]
>Probably it would be better to have my openssl.org email associated with oss-fuzz rather than my personal one.

What's your openssl.org email? (is it a google account).
I can do this for you.

> > This was reported by oss-fuzz
> 
> Hmm. I can see that report when I click on your link, but not when I look here:
> 
> https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label%3AProj-openssl
> 
> What am I doing wrong with that query?
> 
> > OpenSSL team, is there anything we can do to make it easier to deal with our bug reports?
> 
> The biggest problem I have is the signal-to-noise ratio. I seem to get a large number of notifications in my inbox between the two relevant projects (openssl and cryptofuzz) to the point that I mentally filter most of them out and I'm probably missing important reports. In the cryptofuzz case I think there are quite a lot of notifications which aren't actually about OpenSSL at all. If we could find a way to reduce the number of notifications to only include important things that we really need to look at, then that would help a lot.

I think this is a problem that is sort of unique to cryptofuzz unfortunately and not easily solved.
Guido maybe we can recommend some mail filters for people?

**Comment by guidovranken** [comment]
I suggest removing Matt (and maybe others too, if they want) from the Cryptofuzz CC list. I'm always closely monitoring Cryptofuzz on OSS-Fuzz and will always report relevant issues manually. @mattcaswell do you agree?

**Comment by mattcaswell** [comment]
> I suggest removing Matt (and maybe others too, if they want) from the Cryptofuzz CC list. I'm always closely monitoring Cryptofuzz on OSS-Fuzz and will always report relevant issues manually. @mattcaswell do you agree?

That sounds good. I'd suggest also removing openssl-security in that case. Thanks @guidovranken.

**Comment by mattcaswell** [comment]
> What's your openssl.org email? (is it a google account).

As shown here:
https://www.openssl.org/community/omc.html

Yes, its a google account.
