### ISSUE TITLE
3.1 build issue on Amazon Linux

### ISSUE THREAD

**Issue by andysCaplin** [openssl/openssl#20836]
Building OpenSSL 3.1.0 on Amazon Linux we get this issue

```
2023/04/21-12:25:33: [INFO] OpenSSL: Building version 3.1.0 for aarch64-pc-linux-gnu
Text::Template version 1.46 required--this is only version 1.45 at /builds/platform/cdev-openssl/openssl/openssl-3.1.0/util/perl/OpenSSL/Template.pm line 41.
BEGIN failed--compilation aborted at /builds/platform/cdev-openssl/openssl/openssl-3.1.0/util/perl/OpenSSL/Template.pm line 41.
Compilation failed in require at /builds/platform/cdev-openssl/openssl/openssl-3.1.0/Configure line 22.
BEGIN failed--compilation aborted at /builds/platform/cdev-openssl/openssl/openssl-3.1.0/Configure line 22.
make: *** No targets specified and no makefile found.  Stop.
```

The build machine has Perl 5.16.3. installed and Perl's Text::Template 1.59 installed.

**Comment by rkarmaka98** [comment]
Working fine for me in latest `AmazonLinux 2023` with `perl 5.32.1` and `Text::Template 1.59` for Openssl 3.1.0. Maybe you need to install `perl-core` modules.

**Comment by andysCaplin** [comment]
Hi, sorry - I should have mentioned as well that we are building for ARM on AmazonLinux2 and we've discovered that the problem is

- AmazonLinux2 does not have Perl Text Template
- EPEL (which we load) has Perl Text Template 1.59 for x86_64, but only Perl Text Template 1.45 for ARM

**Comment by t8m** [comment]
I think you can still install the perl module from CPAN?

**Comment by andysCaplin** [comment]
Yes - thank you. We tried that here and it worked.
