### ISSUE TITLE
Loading OpenSSL Providers on Windows

### ISSUE THREAD

**Issue by pcaswell** [openssl/openssl#20847]
Hello OpenSSL,
Our application needs to load the legacy provider and so I'm following the example shown here:
https://github.com/openssl/openssl/blob/master/README-PROVIDERS.md

The essence of provider loading is: 
```
    /* Load Multiple providers into the default (NULL) library context */
    legacy = OSSL_PROVIDER_load(NULL, "legacy");
    if (legacy == NULL) {
        printf("Failed to load Legacy provider\n");
        exit(EXIT_FAILURE);
    }
    deflt = OSSL_PROVIDER_load(NULL, "default");
    if (deflt == NULL) {
        printf("Failed to load Default provider\n");
        OSSL_PROVIDER_unload(legacy);
        exit(EXIT_FAILURE);
    }
```

Our application installs libssl-3-x64.dll and libcrypto-3-x64.dll it <Application>\bin.  The legacy provider DLL is installed to  <Application>\bin\ossl-modules.  When our application executes it's unable to find the legacy.dll (using the above code) and therefore crashes at a later point.  If I set the environment variable OPENSSL_MODULES  to the location of the legacy DLL it will load but then the "default" provider doesn't load.

I could so with some help to clarify:
- Where should the DLLs reside? Same directory or as above?
- Where does OpenSSL look by default?
- Can I set the search directory programmatically? I tried using OSSL_PROVIDER_set_default_search_path() with a full path but that didn't work.

I'm obviously missing something so any help appreciated.
Paul

**Comment by pcaswell** [comment]
> ...
> This makes no sense to me. The success or otherwise of loading the legacy dll should have no impact at all on the success or otherwise of loading the default provider. The default provider is "built-in" so is not impacted by where other provider modules are located. 
...
> 
Hello Matt, 
Nice surname :-) and thanks for the input.  In this code :

```
	mpoLegacy = OSSL_PROVIDER_load(NULL, "legacy");
	if (mpoLegacy) 
	{
		mpoDefault = OSSL_PROVIDER_load(NULL, "default");
		if (!mpoDefault) 
		{
			OSSL_PROVIDER_unload(mpoLegacy);
		}
	}
```
The pointer returned from OSSL_PROVIDER_load(NULL, "legacy") is valid and NULL when OSSL_PROVIDER_load(NULL, "default") is called.  One question re: OSSL_PROVIDER_set_default_search_path() - does this expect an absolute or relative path?

Paul

**Comment by mattcaswell** [comment]
> The pointer returned from OSSL_PROVIDER_load(NULL, "legacy") is valid and NULL when OSSL_PROVIDER_load(NULL, "default") is called.

That is very curious! Please check the OpenSSL error stack to see if there is anything interesting on it, e.g. via

````
ERR_print_errors_fp(stdout);
````

> does this expect an absolute or relative path?

You should supply an absolute path to this function

**Comment by pcaswell** [comment]
I think this must have been operator error on my part as it's now working as expected. Closing.
