### ISSUE TITLE
When text content larger than 1K, all TAB character automatically convert to 8 SPACE characters.

### ISSUE THREAD

**Issue by giacdinh** [openssl/openssl#2084]
I try to transfer text file with TAB character. If the file less than 1K, thing transfer one-to-one. However, if the content larger than 1K all "TAB" replace by "8 SPACE", thus increase the content size to failed the validation. It happen to or sort of openssl version. From almost 10 years old (0.9.7h) to the few years old (1.0.0d) to recent (1.0.1m).
We push large video file (2G), didn't have any problem.

**Comment by levitte** [comment]
Could you give us an example?

**Comment by giacdinh** [comment]
Same file content at beginning.
Short file is 800bytes
Long file is 2000bytes

Original content before transfer
<config-metadata>^M
\t      <config>^M
\t\t            <admin_id>admin</admin_id>^M


Actual data after transfer at receiving end
NOTE: ‘\t’ is TAB and ‘.’ is space
Short file
<config-metadata>^M
\t      <config>^M
\t\t            <admin_id>admin</admin_id>^M

Long file
<config-metadata>^M
……..<config>^M
…………….<admin_id>admin</admin_id>^M

So short file of 800 bytes transfer exact 800 bytes. Receiving file size at the end of transfer 800 bytes
Long file of 2000 bytes transfer 2500 bytes. Receiving file size at the end of transfer 2500 bytes.

**Comment by richsalz** [comment]
How are you transferring the file.
This is deifnitely not openssl doing space/tab expansion.

**Comment by mattcaswell** [comment]
You're going to need to give us more than that. Do you have some example code that demonstrates the problem?

**Comment by giacdinh** [comment]
Here is app code the I use as unit test to push file.
It has 2 mode HTTP and HTTPs. It seems to have issue with HTTPs and file > 1K.

**Comment by richsalz** [comment]
please post something self-contained.  That program does not compile (various missing header files)

**Comment by FdaSilvaYY** [comment]
Try an open( file, O_BINARY | ... 
It will be better, i bet !:)

**Comment by richsalz** [comment]
for example, it appears that you are calling Flash2AppSMRead and Flash2AppSMWrite.  One of those functions is probably doing the tab expansion.

**Comment by mattcaswell** [comment]
No further progress. Closing.
