### ISSUE TITLE
b_print.c not compiling in OpenSSL-1_1_1-stable if OPENSSL_SYS_UEFI is defined

### ISSUE THREAD

**Issue by john-chuah** [openssl/openssl#20849]
openssl/crypto/bio/b_print.c:308:17: error: implicit
declaration of function 'ERR_raise' [-Werror=implicit-function-declaration]
openssl/crypto/bio/b_print.c:308:31: error: 'ERR_R_UNSUPPORTED' undeclared (first use in this function)
openssl/crypto/bio/b_print.c:308:31: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors

This bug is introduced by the backport commit b9e3749eb2ded7313459985978bb3ecc4374ff21 that added a call to ERR_raise which is not defined in OpenSSL-1_1_1-stable. ERR_raise is introduced in OpenSSL 3.0.0.

```
diff --git a/crypto/bio/b_print.c b/crypto/bio/b_print.c
...
+#ifndef OPENSSL_SYS_UEFI
            case 'f':
                if (cflags == DP_C_LDOUBLE)
                    fvalue = va_arg(args, LDOUBLE);
@@ -292,6 +298,16 @@ _dopr(char **sbuffer,
                           flags, G_FORMAT))
                    return 0;
                break;
+#else
+            case 'f':
+            case 'E':
+            case 'e':
+            case 'G':
+            case 'g':
+                /* not implemented for UEFI */
+                **ERR_raise(ERR_LIB_BIO, ERR_R_UNSUPPORTED);**
+                return 0;
+#endif
```

**Comment by t8m** [comment]
Fix in #20852
