### ISSUE TITLE
Openssl 3.0 static linking with FIPS mode.

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#20840]
We are migrating from Openssl 1.0.2zd  & openssl 1.1.1 to openssl 3.0
There are 5 applications in current product & each app can independently set FIPs mode. Currently we build 4 sets of openssl with fips compliance. 
a.	Set #1 - is build & linked statically with the application.
b.	Set #2 – for the C# (we rename the output openssl sll) 
c.	Set #3 – for the c++ app(we rename the output openssl sll)
d.	Set #4 – build with openssl 1.1.1 and statically linked with the app

Following are the apps details.
1.	C++ App 1 – Statically linked with this static lib – ssleay32.lib, libeaycompat32.lib, libeayfips32.lib Set#1
2.	C++ App 2 – Statically linked with this static lib – ssleay32.lib, libeaycompat32.lib, libeayfips32.lib Set#1
3.	C# application – A specific set of dll is reserved for C# - Set#2
4.	C++ App 3 – Dynamically loads the openssl binary – Set#2
5.	C++ App 4 - Statically linked the openssl 1.1.1q – Set#4

Now in openssl 3.0, is it possible to set fips mode statically for App 1, App2 and App 4? (Note here one app can be in fips mode, however other app cannot)
1.	C++ App 1 – Previously it was statically linked, is it possible to link statically with openssl 3.0?
2.	C++ App 2 – Previously it was statically linked, is it possible to link statically with openssl 3.0 ?
3.	C# application – A specific set of dll is reserved for C# - Set#1. This will be same as today.
6.	C++ App 3 – Dynamically loads the openssl binary – Set#2. This will be same as today.
4.	C++ App 4 – Previously it was statically linked, is it possible to link statically with openssl 3.0?

I have following questions.
1.	Static linking is possible in openssl 3.0 and I am able to load fips provider.
2.	If not, I have to dynamically link all 5 applications and I need to have 5 set of output openssl binaries, I can rename the openssl binaries, however what will happen to fips.dll. Will it be shared or I should have 5 copies of the dll,

**Comment by ChauhanPriyanka** [comment]
Alright, so you mean I can use same openssl files and fips.dll & share it across all 5 application.
I'm sorry for asking silly question, but I'm not able to process the fact of sharing Fips.dll in the current product.

As per current design all application resides inside the same directory on hard disk (for e.g C:/ProgramFiles/MyProj). Its a windows application. Each application can independently choose to either be in FIPS mode or Non FIPS mode depending upon some registry . Currently each application has its own copy of openssl binaries. (3 are statically compiled & 2 are using dynamically). So they can work in FIPS/Non FIPS independently.

With openssl 3.0
If I share the openssl binaries across all 5 application, can one applications be in FIPS mode and others in non FIPS mode independently.
For example App 1 can be in FIPS mode, however APP 2 chooses to be in non FIPS mode both are using same FIPS.dll  will this work ?

**Comment by mattcaswell** [comment]
> can one applications be in FIPS mode and others in non FIPS mode independently.

Yes.

> For example App 1 can be in FIPS mode, however APP 2 chooses to be in non FIPS mode both are using same FIPS.dll will this work ?

In this case both app1 and app2 would be linked against libcrypto/libssl. Neither are linked directly against fips.dll. App1 would load the fips provider at run time (fips.dll). App2 would not need to load the fips provider at all.

**Comment by ChauhanPriyanka** [comment]
To statically link openssl do I have to compile openssl with no-shared flag ?

**Comment by mattcaswell** [comment]
Yes

**Comment by paulidale** [comment]
No.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
