### ISSUE TITLE
SHLIB_EXT variable no longer honored building OpenSSL 3.0

### ISSUE THREAD

**Issue by alberanid** [openssl/openssl#20854]
I'm building OpenSSL 3.0.8 for android-arm, and I need the output file names to include major and minor version numbers (e.g. libssl_3_0.so).

With OpenSSL 1.1.1t, I set the `SHLIB_VERSION_NUMBER=` and `SHLIB_EXT=_1_1.so` variables of the `make` commands and it worked as expected. With OpenSSL 3.0.8, the compiled and installed files are always named `libssl.so` and `libcrypto.so` no matter how I set the environment variables.

Was this feature removed? I can still see some references in the build files.

My commands and their output:

* `./Configure android-arm -D__ANDROID_API__=23 --prefix=/vol/ssl`:  [ext_configure.log](https://github.com/openssl/openssl/files/11352122/ext_configure.log)
* `make SHLIB_VERSION_NUMBER= SHLIB_EXT=_3_0.so build_libs -j`: [ext_make.log](https://github.com/openssl/openssl/files/11352123/ext_make.log)
* `make SHLIB_VERSION_NUMBER= SHLIB_EXT=_3_0.so install_sw`: [ext_install.log](https://github.com/openssl/openssl/files/11352126/ext_install.log)

Thanks.

**Comment by t8m** [comment]
@levitte could you please take a look?

**Comment by alberanid** [comment]
@levitte I've just found your comments on issue #19283 and so I assume that setting `SHLIB_EXT` is now obsolete. The approach you proposed works fine for my use case.

In any case I guess that the reference to `SHLIB_EXT` should be removed from here: https://github.com/openssl/openssl/blob/56a51b5a1ecd54eadc80bed4bfe5044a340787c1/Configurations/descrip.mms.tmpl#L468

Thanks!

**Comment by levitte** [comment]
> In any case I guess that the reference to `SHLIB_EXT` should be removed from here:
> 
> https://github.com/openssl/openssl/blob/56a51b5a1ecd54eadc80bed4bfe5044a340787c1/Configurations/descrip.mms.tmpl#L468
> 
> Thanks!

Oh gods yes...  thanks for pointing it out!

**Comment by levitte** [comment]
Cleanup in #21007

**Comment by nhorman** [comment]
PR referenced is merged so I imagine this can be closed.  Marking as inactive, to be closed at the end of 3.4 dev

**Comment by t8m** [comment]
I'll just close it now.
