### ISSUE TITLE
Inconsistent API for read/write public key

### ISSUE THREAD

**Issue by KovalevVasiliy** [openssl/openssl#20863]
It looks very strange, what I can write a public key ONLY without password and cipher using PEM_write_bio_PUBKEY, but I can provide a password and callback in PEM_read_bio_PUBKEY(). I believe, API should be consistent.
Version: OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

    std::string filename = "public.pem";
    std::string password = "password";
    {
        std::unique_ptr<EVP_PKEY, decltype(&::EVP_PKEY_free)> key(EVP_RSA_gen(2048), ::EVP_PKEY_free);

        std::unique_ptr<BIO, decltype(&::BIO_free)> out(BIO_new(BIO_s_file()), ::BIO_free);
        if (out != nullptr) {
            if (BIO_write_filename(out.get(), const_cast<char *>(filename.c_str())) > 0) {
                int size = PEM_write_bio_PUBKEY(out.get(), key.get()); // can't pass password and cipher
                std::cout << size << std::endl;
            }
        }
    }
    {
        std::string invalidPassword = "invalid";
        std::unique_ptr<BIO, decltype(&::BIO_free)> in(BIO_new(BIO_s_file()), ::BIO_free);
        if (in != nullptr) {
            if (BIO_read_filename(in.get(), filename.c_str()) > 0) {
                EVP_PKEY *pkey = PEM_read_bio_PUBKEY(in.get(), nullptr, nullptr, const_cast<char*>(password.data()));
                std::cout << (pkey == nullptr) << std::endl;
            }
        }
    }

Maybe I have missed something and callback and password in PEM_read_bio_PUBKEY()  just ignored, but It should be fixed to make api similar.

**Comment by paulidale** [comment]
It is possible to read a public key from a private key file.  Hence the password option.

**Comment by KovalevVasiliy** [comment]
> It is possible to read a public key from a private key file. Hence the password option.

Thanks a lot for your answer
