### ISSUE TITLE
Make test failing

### ISSUE THREAD

**Issue by vivekptl9** [openssl/openssl#20861]
Please help me resolving this error while installing openssl 1.1 on Ubuntu 16.04 

```
./test/recipes/80-test_ssl_new.t                (Wstat: 256 Tests: 29 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=155, Tests=1466, 89 wallclock secs ( 1.89 usr  0.23 sys + 74.98 cusr  4.29 csys = 81.39 CPU)
Result: FAIL
Makefile:207: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/vivek/openssl-1.1.1g'
Makefile:205: recipe for target 'tests' failed
make: *** [tests] Error 2

```

**Comment by mattcaswell** [comment]
Please provide some more details about how you configured OpenSSL during your build.

Also please provide the output from this command:

````
make TESTS=test_ssl_new V=1 test
````

**Comment by vivekptl9** [comment]
Thank you for the quick reply.

To configure Openssl, I used the following command: 
`./config --prefix=/home/username/openssl --openssldir=/home/username/openssl no-ssl2
`
and on running `make TESTS=test_ssl_new V=1 test`
I get :
Test Summary Report
-------------------
..```
/test/recipes/80-test_ssl_new.t (Wstat: 256 Tests: 29 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=1, Tests=29, 13 wallclock secs ( 0.34 usr  0.06 sys + 10.82 cusr  0.41 csys = 11.63 CPU)
Result: FAIL
Makefile:207: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/vivek/openssl-1.1.1g'
Makefile:205: recipe for target 'tests' failed
make: *** [tests] Error 2
```

**Comment by mattcaswell** [comment]
I need the *full* output from the `make TESTS` command.

**Comment by vivekptl9** [comment]
[make_test.txt](https://github.com/openssl/openssl/files/11365003/make_test.txt)

**Comment by mattcaswell** [comment]
Looks like a problem with expired certificates in the test suite. You are are using an old version of 1.1.1. Please try the latest version 1.1.1t.

**Comment by vivekptl9** [comment]
Thanks Matt. True that, it was with the version. Now it seems it is working. Thank you so much for the help. :)

**Comment by mattcaswell** [comment]
No problem.
