### ISSUE TITLE
memory leak in engine_cleanup_add_first

### ISSUE THREAD

**Issue by Hripsimee** [openssl/openssl#20870]
The engine_cleanup_add_first function in the crypto/engine/eng_lib.c source file appears to contain a memory leak. Specifically, memory is allocated using int_cleanup_item in line 142:

item = int_cleanup_item(cb);

However, if the sk_ENGINE_CLEANUP_ITEM_insert function fails to add the item object to the stack, the application should take appropriate action to clean up the allocated memory to avoid memory leaks.

**Comment by mattcaswell** [comment]
Yes, this looks like a bug. Adding the help-wanted label.

**Comment by KovalevVasiliy** [comment]
@mattcaswell Can I try to solve this issue? Can I just open a PR with fix? Or what is the process?

**Comment by paulidale** [comment]
You'd be most welcome to solve this issue.

**Comment by KovalevVasiliy** [comment]
Created https://github.com/openssl/openssl/pull/20880
