### ISSUE TITLE
Parameter 'mod' shadows function 'mod'

### ISSUE THREAD

**Issue by motminh** [openssl/openssl#20887]
The upgrade 1.1.1s -> 1.1.1t added a new file crypto/bn/rsa_sup_mul.c which results in the following compiler errors (we build with -Werror):

```
./../../../../../src/crypto/openssl/crypto/bn/rsa_sup_mul.c: In function 'mod':
../../../../../../src/crypto/openssl/crypto/bn/rsa_sup_mul.c:337: warning: declaration of 'mod' shadows a global declaration
../../../../../../src/crypto/openssl/crypto/bn/rsa_sup_mul.c:339: warning: shadowed declaration is here
```

```
../../../../../../src/crypto/openssl/crypto/bn/rsa_sup_mul.c: In function 'mod_montgomery':
../../../../../../src/crypto/openssl/crypto/bn/rsa_sup_mul.c:421: warning: declaration of 'mod' shadows a global declaration
../../../../../../src/crypto/openssl/crypto/bn/rsa_sup_mul.c:339: warning: shadowed declaration is here
```

```
337 static void mod(limb_t *ret, limb_t *a, size_t anum, limb_t *mod,
338                size_t modnum, limb_t *tmp)
339 {
...
421 static void mod_montgomery(limb_t *ret, limb_t *a, size_t anum, limb_t *mod,
422                           size_t modnum, limb_t ni0, limb_t *tmp)
423 {   
```

Either the function or the parameters need to be renamed.

**Comment by paulidale** [comment]
Option three: disable that warning option when compiling.
It's not harmful in this case (but could be confusing).

**Comment by motminh** [comment]
> Option three: disable that warning option when compiling. It's not harmful in this case (but could be confusing).

This really isn't the approach one wants to take for critical security software.  Disabling the warning is not easy to do for *just* this file and *just* this instance.

**Comment by paulidale** [comment]
It was only a suggestion to get you going again.  If it's not acceptable, you'll have to wait for a proper fix and subsequent release.
