### ISSUE TITLE
`openssl version` does not return the version that was compiled

### ISSUE THREAD

**Issue by crackerjam** [openssl/openssl#20884]
I'm building openssl on a RHEL 9.1 host using these commands:

```
mkdir ~/openssl
cd ~/openssl
curl -O https://www.openssl.org/source/openssl-3.0.8.tar.gz
tar -xvf openssl-3.0.8.tar.gz
cd openssl-3.0.8
./Configure --prefix=/home/<username>/openssl --openssldir=/home/<username>/openssl
make -j 8
make install
```
This appears to build successfully. However, when I navigate to ~/openssl/bin and run `openssl version` I get this output:

```
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
```

It seems as though there is some bug in the 3.0.8 release that is causing it to report its version as 3.0.1.

**Comment by tom-cosgrove-arm** [comment]
If I do exactly the same as you

```
$ cd ~/openssl/bin
$ LD_LIBRARY_PATH=~/openssl/lib64 ./openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

Note the use of `./` in front open `openssl version`, since I don't have the current directory in my `PATH`, and the `LD_LIBRARY_PATH` since the link loader needs to know where the shared objects (library files) are

**Comment by crackerjam** [comment]
Wow, yep, you are absolutely correct. Apologies for the bogus issue, just my own error.
