### ISSUE TITLE
FIPS Provider with default Alpine OpenSSL 3.0.8

### ISSUE THREAD

**Issue by bdou** [openssl/openssl#20885]
Hello, I am trying to enable FIPS on my Alpine container image. I've been able to build the OpenSSL 3.0.0 FIPS Provider and configure it to work properly with OpenSSL 3.0.8 compiled and built from source. But when I try to use similar steps to configure the 3.0.0 FIPS Provider with the OpenSSL provided by the distro package manager (`apk add openssl`; the default version is also 3.0.8), the FIPS Provider does not seem to load. For reference here are the commands I am using:

```
apk update && apk add openssl tar perl gcc make linux-headers libc-dev

mkdir -p /tmp/openssl \
  && cd /tmp/openssl

wget --quiet https://www.openssl.org/source/openssl-3.0.0.tar.gz \
  && tar -xzf openssl-3.0.0.tar.gz

mkdir /usr/local/ssl

cd openssl-3.0.0
./config enable-fips && make && make install_fips \
  && openssl fipsinstall -out /usr/local/ssl/fipsmodule.cnf -module /usr/local/lib64/ossl-modules/fips.so

# Edit /etc/ssl/openssl.cnf according to instructions listed https://www.openssl.org/docs/man3.0/man7/fips_module.html
```
Are there additional configuration steps I need to take in order to get the FIPS provider to work? I would prefer to use the distro-provided openssl in order to be able to continue receiving updates as well as not to deal with the conflicts of having multiple openssl configurations on the system (Alpine already ships with libcrypto and libssl and a default openssl configuration in /etc/ssl).

**Comment by mattcaswell** [comment]
> the FIPS Provider does not seem to load.

Do you get any error message that might be helpful?

What is the value for OPENSSLDIR returned by `openssl version -d`? This is the default location where openssl will look for the default config file openssl.cnf. Most likely OPENSSLDIR/openssl.cnf probably just a link to /etc/ssl/openssl.cnf, but worth checking.

Please show us the change that you made to /etc/ssl/openssl.cnf.

**Comment by bdou** [comment]
Here are the lines I added to /etc/ssl/openssl.cnf:
```
.include /usr/local/ssl/fipsmodule.cnf

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1
```
I edit the existing file so other default lines like [openssl_init] remain. I also commented out the `default = default_sect` line under `[provider_sect]`.

When I run `openssl list -providers`, the FIPS Provider is not listed. My other change to the config file - removing the default provider and adding the base provider - does get picked up.

```
# openssl version -d
OPENSSLDIR: "/etc/ssl"

# openssl list -providers
Providers:
  base
    name: OpenSSL Base Provider
    version: 3.0.8
    status: active
```


Then, when I try to test whether FIPS is working under the covers, I get error for both sha1 and md5 hashes:

```
# openssl sha1 /dev/null
Error setting digest
481BFA27E17F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (SHA1 : 84), Properties ()
481BFA27E17F0000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:crypto/evp/digest.c:254:

# openssl md5 /dev/null
Error setting digest
48BBD649E37F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (MD5 : 91), Properties ()
48BBD649E37F0000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:crypto/evp/digest.c:254:

```

**Comment by mattcaswell** [comment]
MD5 is not in the list of digests supported by the FIPS provider so that should not work. See:

https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-FIPS.html

SHA1 is though, so that should work.

Please can you additionally show us the contents of `/usr/local/ssl/fipsmodule.cnf`

**Comment by bdou** [comment]
Yes, that's why I test SHA1 and MD5 - to test that OpenSSL and FIPS, respectively.

```
# cat /usr/local/ssl/fipsmodule.cnf
[fips_sect]
activate = 1
install-version = 1
conditional-errors = 1
security-checks = 1
module-mac = 15:81:AD:37:2D:A9:55:34:A2:99:BA:CB:2B:25:6D:B4:A6:52:64:68:A1:0C:A9:F1:07:64:41:30:BB:C7:95:2B
install-mac = 41:9C:38:C2:8F:59:09:43:2C:AA:2F:58:36:2D:D9:04:F9:6C:56:8B:09:E0:18:3A:2E:D6:CC:69:05:04:E1:11
install-status = INSTALL_SELF_TEST_KATS_RUN
```

**Comment by mattcaswell** [comment]
Sorry. Another question. Please show the output from `openssl version -m`. This is the location where the fips.so file should be installed. Is that where it is?

**Comment by bdou** [comment]
```
# openssl version -m
MODULESDIR: "/usr/lib/ossl-modules"
```

Should I be referencing the `fips.so` file somewhere?

**Comment by mattcaswell** [comment]
That directory is where the fips.so file needs to be placed, and you need to reference that location when you run `openssl fipsinstall`

**Comment by bdou** [comment]
I see! My fips.so lives in `/usr/local/lib64/ossl-modules` and that's what I've been using to run `openssl fipsinstall`. Should I move it and rerun the self-test?

**Comment by mattcaswell** [comment]
Yes. Move it to the correct location for the system (`/usr/lib/ossl-modules`) and re-run the fipsinstall.

By the way, it occurs to me that this might actually break your system because some system packages may rely on crypto not available within the FIPS provider. You might be better off leaving the system config file untouched and take a copy of it instead to make your edits. Then, for any processes for which you want to use fips for, set the `OPENSSL_CONF` environment variable to point to your edited openssl.cnf file instead of the default system one. This way you do not impact the configuration of standard packages, but for apps that you want to enforce fips for you can still use the standard system libcrypto/libssl - you just use a different config file for them.

**Comment by bdou** [comment]
Thank you so much Matt! That resolved my issue.
