### ISSUE TITLE
What function in OpenSSLv3.0 can replace the "PEM_read_bio_RSAPublicKey" function?

### ISSUE THREAD

**Issue by Lucy0418s** [openssl/openssl#20895]
when using "PEM_read_bio_RSAPublicKey" function, the public key is encoded using a PKCS#1 RSAPublicKey structure. But this function is deprecated in OpenSSLv3.0. Then I use "PEM_read_bio_PUBKEY" but it return error. I find its public key need to be encoded as a SubjectPublicKeyInfo structure. 
So what functions in OpenSSLv3.0 can replace the "PEM_read_bio_RSAPublicKey" function if I only have public key encoded using a PKCS#1 RSAPublicKey structure?

**Comment by KovalevVasiliy** [comment]
@Lucy0418s First of all, I'm not a maintainer of OpenSSL, I'm just a user like you.
But I've found, what EVP_PKEY_new_raw_public_key can be used, if you have only deprecated key data.
Something like this:
EVP_PKEY* create_public_key(const unsigned char* key_data, size_t key_data_len) {
    EVP_PKEY* pkey = EVP_PKEY_new_raw_public_key(EVP_PKEY_RSA, NULL, key_data, key_data_len);
    if (pkey == NULL) {
        // Handle error
    }
    return pkey;
}

**Comment by Lucy0418s** [comment]
@KovalevVasiliy thanks for your replay, but I find EVP_PKEY_new_raw_public_key don't support RSA according to the manual.

![image](https://user-images.githubusercontent.com/114052188/236723062-6759dddf-5618-4623-b885-3c8a8e77b7fe.png)

**Comment by mattcaswell** [comment]
Please refer to the DECODER functions:

https://www.openssl.org/docs/man3.1/man3/OSSL_DECODER_from_bio.html
