### ISSUE TITLE
EVP-based decryption of data encrypted with AES_decrypt()

### ISSUE THREAD

**Issue by jjeffroberts** [openssl/openssl#20894]
I'm trying to convert code that uses the low-level AES APIs to use the EVP APIs.

I need to be able to decrypt data that was encrypted by this old code.

The original code boils down to this:
```
const unsigned char keydata[] = {
    ... 32 bytes ...
}

AES_KEY dec_key;
AES_set_decrypt_key(keydata, sizeof(keydata) * 8, &dec_key);
AES_decrypt(dec_input, dec_out, &dec_key);
```
I can see that AES_set_decrypt_key() does 10 rounds of KeyExpansion() on the keydata to produce the AES_KEY.

I think the EVP version of this should look something like this:
```
int aes_decrypt(const unsigned char *input, int input_len, unsigned char *output, const unsigned char *key)
{
    int rc = 1;
    EVP_CIPHER_CTX *ctx = NULL;
    EVP_CIPHER *cipher = NULL;
    const unsigned char *iv = NULL;
    int outlen;
    int tmplen = 0;

    ctx = EVP_CIPHER_CTX_new();
    if (ctx == NULL) {
        fprintf(stderr, "Error creating context.\n");
        goto cleanup;
    }

    cipher = EVP_CIPHER_fetch(NULL, "AES-128-CBC", NULL);
    if (cipher == NULL) {
        fprintf(stderr, "Error fetching cipher.\n");
        goto cleanup;
    }

    if (EVP_DecryptInit_ex(ctx, cipher, NULL, key, iv) != 1) {
        fprintf(stderr, "Error in EVP_DecryptInit_ex.\n");
        goto cleanup;
    }

    if (EVP_DecryptUpdate(ctx, output, &outlen, input, input_len) != 1) {
        fprintf(stderr, "Error in EVP_DecryptUpdate\n");
        goto cleanup;
    }
    /*
     * Buffer passed to EVP_DecryptFinal() must be after data just
     * encrypted to avoid overwriting it.
     */
    if (EVP_DecryptFinal_ex(ctx, output + outlen, &tmplen) != 1) {
        fprintf(stderr, "Error in EVP_DecryptFinal_ex\n");
        goto cleanup;
    }

    rc = 0;

cleanup:
    if (ctx) {
        EVP_CIPHER_CTX_free(ctx);
    }
    if (cipher) {
        EVP_CIPHER_free(cipher);
    }

    if (rc == 1) {
        ERR_print_errors_fp(stderr);
    }

    return rc;
}
```

I chose "AES-128-CBC" only because the old code had a comment saying that's what they were doing,
but I've since noticed they aren't calling AES_cbc_encrypt(), and this:

https://www.highgo.ca/2019/08/08/the-difference-in-five-modes-in-the-aes-encryption-algorithm/

would lead me to believe they would have needed to call AES_cbc_encrypt() and send an initialization vector.

I'm not sure which mode of AES I should select, really.

As a first guess I sent 'keydata' raw as the key and using iv=NULL and unsurprisingly I'm not getting the right answer.

In fact, I'm getting an error when I get to EVP_DecryptFinal_ex():

80979566827F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:../openssl-3.0.5/providers/implementations/ciphers/ciphercommon_block.c:124:

I have referred to this:

https://github.com/saju/misc/blob/master/misc/openssl_aes.c

And I wonder if I need to call EVP_BytesToKey() with the key data to produce a key and iv, but I'm not sure how applying a salt and hash to the data could give me the same result as AES_set_decrypt_key().

We're out here TRYING to convert all these low-level API calls but sometimes it's hard to connect the dots - can anyone point me in the right direction?

**Comment by jjeffroberts** [comment]
If I choose AES-128-ECB and also call EVP_CIPHER_CTX_set_padding(ctx, 0) I at least get reasonable-looking output without any errors, although it doesn't yet match

**Comment by KovalevVasiliy** [comment]
@jjeffroberts could you provide a snippet for encryption? I recently migrated my project from old API to the EVP based. Maybe I can help you.

**Comment by jjeffroberts** [comment]
@KovalevVasiliy Yes, I will put something together in the morning.

**Comment by bernd-edlinger** [comment]
> const unsigned char keydata[] = {
    ... 32 bytes ...
}
AES_set_decrypt_key(keydata, sizeof(keydata) * 8, &dec_key);

that could probably mean AES-256-ECB

**Comment by jjeffroberts** [comment]
@bernd-edlinger Math for the win :-)

I appreciate the help. To recap, despite a misleading comment about AES-128-CBC, they were not calling AES_cbc_encrypt(), plus there was no iv, so ECB was likely.

And 32*8 is indeed 256.

Also, this error led me to try turning off padding:

80979566827F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:../openssl-3.0.5/providers/implementations/ciphers/ciphercommon_block.c:124:

I ended up with this:

```
int aes_256_ecb(int encrypt, const unsigned char *input, int input_len, unsigned char *output, const unsigned char *key)
{
    int rc = 0;
    EVP_CIPHER_CTX *ctx = NULL;
    EVP_CIPHER *cipher = NULL;
    const unsigned char *initializationVector = NULL;
    int outlen;
    int tmplen = 0;

    ctx = EVP_CIPHER_CTX_new();
    if (ctx == NULL) {
        fprintf(stderr, "Error creating context.\n");
        goto cleanup;
    }

    cipher = EVP_CIPHER_fetch(NULL, "AES-256-ECB", NULL);
    if (cipher == NULL) {
        fprintf(stderr, "Error fetching cipher.\n");
        goto cleanup;
    }

    if (encrypt == 1) {
        if (EVP_EncryptInit_ex(ctx, cipher, NULL, key, initializationVector) != 1) {
            fprintf(stderr, "Error in EVP_EncryptInit_ex.\n");
            goto cleanup;
        }
    } else {
        if (EVP_DecryptInit_ex(ctx, cipher, NULL, key, initializationVector) != 1) {
            fprintf(stderr, "Error in EVP_DecryptInit_ex.\n");
            goto cleanup;
        }
    }

    if (!EVP_CIPHER_CTX_set_padding(ctx, 0)) {
        fprintf(stderr, "EVP_CIPHER_CTX_set_padding() failed\n");
        goto cleanup;
    }

    if (encrypt == 1) {
        if (EVP_EncryptUpdate(ctx, output, &outlen, input, input_len) != 1) {
            fprintf(stderr, "Error in EVP_EncryptUpdate\n");
            goto cleanup;
        }
    } else {
        if (EVP_DecryptUpdate(ctx, output, &outlen, input, input_len) != 1) {
            fprintf(stderr, "Error in EVP_DecryptUpdate\n");
            goto cleanup;
        }
    }

    if (encrypt ==1) {
        if (EVP_EncryptFinal_ex(ctx, output + outlen, &tmplen) != 1) {
            goto cleanup;
        }
    } else {
        if (EVP_DecryptFinal_ex(ctx, output + outlen, &tmplen) != 1) {
            fprintf(stderr, "Error in EVP_DecryptFinal_ex\n");
            goto cleanup;
        }
    }

    rc = 1;

cleanup:
    if (ctx) {
        EVP_CIPHER_CTX_free(ctx);
    }
    if (cipher) {
        EVP_CIPHER_free(cipher);
    }

    if (rc == 0) {
        ERR_print_errors_fp(stderr);
    }

    return rc;
}
```
