### ISSUE TITLE
Setting IV length on GCM does not seem to work > 12 bytes

### ISSUE THREAD

**Issue by philippe44** [openssl/openssl#20905]
Using 1.1.1g to 1.1.u, it seems that setting the IV length beyond 12 bytes is not taken into account. Calling EVP_CIPHER_CTX_iv_length reports the correct length but only the first 12 bytes of IV are taken into account. The following code
```
uint8_t aesKey[] = "0123456789ABCDEF";
uint8_t aesIV[]= "FEDCBA9876543210";
uint8_t epk[32], tag[16];
int len;

// verified test vector
// aes_key: a043357cee40a9ae0731dd50859cccfb
// aes_iv: da36ea69a94d51d881086e9080dbaef8
// epk: 5de0f61622b0d41bc098b07f229863f49e1a1c1030908b0ec620386e089a20c4
// tag: 3b13d2e85f00555c6a05df5cb03a2105

//memset(aesIV + 12, 0, 4);
//aesIV[0] = 4;

EVP_CIPHER_CTX* gcm = EVP_CIPHER_CTX_new();
EVP_EncryptInit(gcm, EVP_aes_128_gcm(), aesKey, aesIV);
EVP_CIPHER_CTX_ctrl(gcm, EVP_CTRL_GCM_SET_IVLEN, sizeof(aesIV), NULL);
ivLen = EVP_CIPHER_CTX_iv_length(gcm);
EVP_EncryptUpdate(gcm, epk, &len, a_pub, sizeof(a_pub));
EVP_EncryptFinal(gcm, NULL, &len);
EVP_CIPHER_CTX_ctrl(gcm, EVP_CTRL_GCM_GET_TAG, sizeof(tag), tag);
```
Gave me an incorrect result (I have a test vector that is verified, I'm simply using another key/iv for the sake of the example). Now, if I un-comment the "memset", as long as I truncate any of the last 4 digits, the result is *always* the same which should obviously not be the case. Now, as expected if I change any other digit, the result changes.

**Comment by philippe44** [comment]
argh... I just realized, after many hours, that I need to call EVP_EncryptInit twice... once before and once after setting IV length. like that
```
EVP_EncryptInit(gcm, EVP_aes_128_gcm(), NULL, NULL);
EVP_CIPHER_CTX_ctrl(gcm, EVP_CTRL_GCM_SET_IVLEN, sizeof(aesIV), NULL);
EVP_EncryptInit(gcm, NULL, aesKey, aesIV);
EVP_EncryptUpdate(gcm, epk, &len, a_pub, sizeof(a_pub));
```
Funny or sadly enough, thanks chatGPT...

**Comment by paulidale** [comment]
Yeah, it's not the ideal API unfortunately.

**Comment by philippe44** [comment]
Well, I'm glad openssl is here anyway 😄
