### ISSUE TITLE
$ git clone git://git.openssl.org/openssl.git

### ISSUE THREAD

**Issue by Honestnature** [openssl/openssl#20902]
$ cd openssl
$ git config core.autocrlf false
$ git config core.eol lf
$ git checkout .

**Comment by mattcaswell** [comment]
Please elaborate on what your issue is?

**Comment by Honestnature** [comment]
2 B Truthfully speaking idk what the fu*¿ I'm doing but I'm really into this coding stuff I use to be really good at code academy back in 2014, I read allot about the basics I'm on a iphone11 though so idk what to do or start
