### ISSUE TITLE
Corpora in the 3.1/3.0 branches

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#20903]
In master we have the fuzz corpora coming in from a separate submodule. But in 3.1/3.0 the corpora still exist in the main repo. Should we make the same change we've done in master to 3.1/3.0?

**Comment by levitte** [comment]
I think so.  It's not like that makes us drive new features in the release branches...  they each have their test drivers, corpora that doesn't have a driver will simply remain unused.

**Comment by nhorman** [comment]
It seems like this discussion has reached a natural end, and we don't plan to do anything here.  Closing
