### ISSUE TITLE
when i update version from 1.1.1 to 3.0.7, i cannot generate dsa key shorter than 1024, such as 512

### ISSUE THREAD

**Issue by hxtzzz** [openssl/openssl#20915]
-   i use C library of openssl. The error is in the EVP_PKEY_keygen func when i input keyLen  such as 512, but it can success when i use openssl 1.1.1.

-  Thank you for review and check!

**Comment by FdaSilvaYY** [comment]
Minimal DSA key size has been increased to 1024 bits, since 3.0 for security reasons.

Take a look at Changes.mdfile

**Comment by hxtzzz** [comment]
> Minimal DSA key size has been increased to 1024 bits, since 3.0 for security reasons.
> 
> Take a look at Changes.mdfile

-  Great! Thank you for your reply. However, I cannot find the information about this key size change in Changes.md and detailed migration_guide, could you please give me the link of that part of information? 
-  Also, could I use low-level function "DSA_generate_key" to generate DSA key shorter than 1024?

**Comment by t8m** [comment]
It is actually possible to generate 512 bit DSA parameters and keys with openssl-3.x:
```
$ openssl genpkey -genparam -algorithm DSA -pkeyopt pbits:512 -out dsa.param
$ openssl genpkey -paramfile dsa.param -pkeyopt pbits:512 -out dsa.key
```

**Comment by t8m** [comment]
> * Also, could I use low-level function "DSA_generate_key" to generate DSA key shorter than 1024?

Unfortunately I do not think this is possible as this defaults to the new keygen and there is no way to override this.

**Comment by hxtzzz** [comment]
> You can try setting OSSL_PKEY_PARAM_FFC_VALIDATE_LEGACY param to 1 or OSSL_PKEY_PARAM_FFC_TYPE to "fips186_2" when calling EVP_PKEY_keygen().
> 
> Actually it is documented (partially incorrectly because the legacy methods still can generate 512 bit keys) in https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-DSA.html

> Thank you so much, I got it :)
