### ISSUE TITLE
Missing documetation

### ISSUE THREAD

**Issue by Exnadella** [openssl/openssl#20916]
Hell Team,

The below link is not available, this is an important source for us to know the default paths for the `paketo-buildpacks/ca-certificates` to define the path for the JVM providers to pick up the certificates and move to the trust store.  Can we check if this page is available or moved or in maintenance?

The link is referenced in several places in this folder: 
(https://github.com/paketo-buildpacks/ca-certificates/blob/main/cacerts/certs.go)
(https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html)

**Comment by t8m** [comment]
This is the current link: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_default_verify_paths.html

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
