### ISSUE TITLE
list all supported ciphers based on the signature algorithm and dh group.

### ISSUE THREAD

**Issue by vkosuri** [openssl/openssl#20917]
I am trying to find the all supported ciphers based on the signature algorithm and dh group.

``` bash
venv ❯ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

venv ❯ openssl ciphers -V RSA-PKCS1-SHA256RSA-PKCS1-SHA256
Error in cipher list
402761BA807F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2745:


venv ❯ openssl ciphers -V FFDHE2048 
Error in cipher list
40376037D07F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2745:

venv ❯ 
```

**Comment by paulidale** [comment]
The cipher names has to be one that is produced by the `openssl ciphers -v` command.

**Comment by vkosuri** [comment]
Thanks @paulidale, I have tried but nothing is returned on the machine. 

``` bash
bash-5.1# openssl ciphers -v | grep FFDHE
bash-5.1# 
bash-5.1# openssl ciphers -v | grep 2048
bash-5.1# 
```

**Comment by t8m** [comment]
That is not possible. For TLS <= 1.2 the ciphersuite contains specification of the key exchange and signature algorithm (but that does not include key size). For TLS-1.3 this is no longer the case and the ciphersuite is negotiated separately from the key exchange and signature algorithm.

In TLS<=1.2 you can grep for DHE ciphersuites if you're looking for ciphersuites using the finite field DH key exchange.  RSA in the ciphersuite name then indicates the RSA signature algorithm and RSA key exchange (in the ciphersuites without DHE/ECDHE).

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
