### ISSUE TITLE
SSL handshake failing with latest Apple clang from Command Line Tools for Xcode 14.3 on MacOS

### ISSUE THREAD

**Issue by pierre-aimi** [openssl/openssl#20937]
OpenSSL 1.1.1 stable has been working fine on multiple platforms until recently the MacOS version broke after installing the latest Xcode Command Line Tools, which includes Apple clang 14.0.3

The symptom we received (we use OpenSSL through CURL), was a Curl SSL connect error returning "error:1012606B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on a curve" which is an OpenSSL error.

After a long investigation, it was determined that the latest Apple clang 14.0.3 is the issue. This has been reproduced on two separate machines, across a number of 1.1.1 tags (k..t). Rolling back to clang 14.0.0 solves the problem.

**Comment by pierre-aimi** [comment]
I've tried to reproduce this on the sslecho demo - https://github.com/openssl/openssl/tree/master/demos/sslecho but wasn't able to. If there's more info you need about our SSL server details let me know and I can follow it up.

**Comment by t8m** [comment]
Please try `openssl s_client` if that reproduces the issue.

**Comment by pierre-aimi** [comment]
I tried s_client on our domain and it seems to connect ok:

```
---
SSL handshake has read 4161 bytes and written 351 bytes
---
New, TLSv1/SSLv3, Cipher is AEAD-CHACHA20-POLY1305-SHA256
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : AEAD-CHACHA20-POLY1305-SHA256
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1684127652
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by pierre-aimi** [comment]
Using it on what? Which domain?

**Comment by pierre-aimi** [comment]
So we ended up solving this by re-enabling asm.
Previously we did this
`./Configure darwin64-arm64-cc no-asm -isysroot ${CMAKE_OSX_SYSROOT}`

Removing the 'no-asm' fixed our issue.

**Comment by pierre-aimi** [comment]
Closing as this as resolved.

**Comment by pierre-aimi** [comment]
Actual there's more to the story, re-opening.

**Comment by tom-cosgrove-arm** [comment]
> Apple clang 14.0.3 is the issue

Do you mean that compiling with 14.0.3 created binaries that didn't work, but that the binaries complied with 14.0.0 did work?

Could you see if there was much difference in the generated object files, and if so, in which functions?

**Comment by pierre-aimi** [comment]
> Do you mean that compiling with 14.0.3 created binaries that didn't work, but that the binaries complied with 14.0.0 did work?
yes

I'll get back to you with the specific details...sorry don't have them on hand right now

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
