### ISSUE TITLE
OpenSSL3 with FIPS - error in RSA key generation command

### ISSUE THREAD

**Issue by danie007** [openssl/openssl#20939]
Hi,

I've built OpenSSL 3.0.3 with **FIPS** support (_on Ubuntu_) and when I change the configuration (_file attached below_) to use only FIPS compliant modules `openssl req -newkey rsa:2048` command fail with below error:

```sh
$ ~/tools/openssl/posix/bin/openssl req -newkey rsa:2048 -config ~/pki/tmp/openssl.cnf
Error allocating keygen context
4027977E8D7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (rsaEncryption : 106), Properties (<null>)
```

It's to be noted that I can other commands with FIPS module and verified FIPS module with `fipsinstall -verify` command as well.

### How to modify this command to make it compliant with **FIPS** module?

---

CC @tkmozhi

[openssl_cnf.txt](https://github.com/openssl/openssl/files/11449187/openssl_cnf.txt)

**Comment by aleksrosz** [comment]
Hi
@danie007 did you solve that?

**Comment by paulidale** [comment]
OpenSSL 3.0.3 is **not** FIPS compliant.  Only 3.0.0 and 3.0.8 are currently.  You **must** build the FIPS provider from one of these versions.  The provider can be used with any version of OpenSSL 3.0.x or 3.1. and we suggest using the latest release (3.0.9 or 3.1.1).

You should also use FIPS + base provider not FIPS + default.

**Comment by aleksrosz** [comment]
@paulidale you are right. I didn't check that author doesn't use correct version but I using git checkout refs/tags/openssl-3.0.8
 have this same error. 

openssl req -newkey rsa -keyout PRIVATEKEY.key -out MYCSR.csr
Error allocating keygen context
40D78E0B707F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (rsaEncryption : 104), Properties (<null>)


```
.include /home/xxx/xxx/fipsmodule.cnf

[openssl_init]
providers = provider_sect
alg_section = algorithm_sect

# List of providers to load
[provider_sect]
#default = default_sect
# The fips section name should match the section name inside the
# included fipsmodule.cnf.
fips = fips_sect
base = base_sect

[base_sect]
activate = 1

[algorithm_sect]
default_properties = fips=yes
# If no providers are activated explicitly, the default one is activated implicitly.
# See man 7 OSSL_PROVIDER-default for more details.
#
# If you add a section explicitly activating any other provider(s), you most
# probably need to explicitly activate the default provider, otherwise it
# becomes unavailable in openssl.  As a consequence applications depending on
# OpenSSL may not work correctly which could lead to significant system
# problems including inability to remotely access the system.
[default_sect]
# activate = 1
```

**Comment by aleksrosz** [comment]
I didn't check that author doesn't use correct version, but I have this same error with version 3.0.8 git checkout refs/tags/openssl-3.0.8 
test passed,
../test2/bin/openssl fipsinstall -out /home/xxx/test2/fipsmodule.cnf -module /home/xxx/openssl/providers/fips.so 
Install passed
then I changed config /usr/lib/ssl/openssl.cnf

```
.include /home/xxx/test2/fipsmodule.cnf

[openssl_init]
providers = provider_sect
alg_section = algorithm_sect

# List of providers to load
[provider_sect]
#default = default_sect
# The fips section name should match the section name inside the
# included fipsmodule.cnf.
fips = fips_sect
base = base_sect

[base_sect]
activate = 1

[algorithm_sect]
default_properties = fips=yes
# If no providers are activated explicitly, the default one is activated implicitly.
# See man 7 OSSL_PROVIDER-default for more details.
#
# If you add a section explicitly activating any other provider(s), you most
# probably need to explicitly activate the default provider, otherwise it
# becomes unavailable in openssl.  As a consequence applications depending on
# OpenSSL may not work correctly which could lead to significant system
# problems including inability to remotely access the system.
[default_sect]
# activate = 1
```



openssl req -newkey rsa -keyout PRIVATEKEY.key -out MYCSR.csr

```
Error allocating keygen context
40077C95FB7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (rsaEncryption : 104), Properties (<null>)
```

**Comment by paulidale** [comment]
@aleksrosz you are missing the `openssl_conf = openssl_init` line in your config.

**Comment by aleksrosz** [comment]
I have it but I didn't mentioned it because it is part of default config.

```
HOME                    = .

openssl_conf = openssl_init

config_diagnostics = 1

oid_section = new_oids

[ new_oids ]
tsa_policy1 = 1.2.3.4.1
tsa_policy2 = 1.2.3.4.5.6
tsa_policy3 = 1.2.3.4.5.7

.include /home/aroszig/test2/fipsmodule.cnf

[openssl_init]
providers = provider_sect
alg_section = algorithm_sect

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1

[algorithm_sect]
default_properties = fips=yes

[default_sect]
# activate = 1

and below is default CA config
```

**Comment by aleksrosz** [comment]
Fixed. I tested it with 3.0.8 and 3.0.9
I had to do
export LD_LIBRARY_PATH="/home/xxx/test2/lib64:$PATH"
 
 
 I think this ticket can be closed.

**Comment by Amutha-29** [comment]
Hi @aleksrosz & @paulidale, with reference to our earlier comment (https://github.com/openssl/openssl/issues/20939#issuecomment-1617961232), could you please provide your input on whether we need to upgrade to the latest release (3.0.9 or 3.1.1) in order to run with FIPS compliance?
