### ISSUE TITLE
Missing Tags for 3.1.1, 3.0.9 following March SecAdv

### ISSUE THREAD

**Issue by crunchyjoea** [openssl/openssl#20934]
Hey there

Per Vulnerabilities, announced 23 March, 2023, there were a few CVEs listed as being fixed in 3.1.1, 3.0.9, 1.1.1u but no tags appear to be available for those releases. Tags appear to be missing both here and on git://git.openssl.org/openssl.git. Are the 3.1.1, 3.0.9, and 1.1.1u versions pending release, or are they available for download?

Thanks!

Reference:
https://www.openssl.org/news/vulnerabilities.html

**Comment by paulidale** [comment]
These versions have not yet been released, therefore the tags cannot exist.
LOW severity CVEs are fixed in public but do not trigger a release (as per our security policy).
