### ISSUE TITLE
codebuild generic issue 

### ISSUE THREAD

**Issue by Ratul707** [openssl/openssl#20933]
We are trying to to perform a codebuild using aws pipeline on ec2 instance ..Looks like we require 1.1.1+ version for openssl ..Please help to provide the command to install the same so that we will add it in buildspec   

As per the logs  'ssl' module is compiled with OpenSSL 1.0.2k-fip

8261 | import urllib3
8262 | File "/usr/local/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
8263 | "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
8264 | ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168

</body>
</html>

**Comment by paulidale** [comment]
Note that for FIPS support, you must build the FIPS provider from OpenSSL 3.0.0.  No 1.1.1 version has been validated.

As for AWS support, I don't think any of the core team have much, if any, experience in this area.  Consider raising a ticket with AWS?

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
