### ISSUE TITLE
use shlib_variant to rename the lib,but the runtime dll do not match actually

### ISSUE THREAD

**Issue by mengzhisuoliu** [openssl/openssl#20942]
we can compile the lib with the dll with `shlib_variant` setting.
it comes out libcrypto-test.lib and libcrypto-1_1-test.dll, and the app can link with the libcrypto-test.lib,but it run with the libcrypto-1_1.dll actually,this is so weird.

we can use the lib.exe to check it out . 
lib.exe /LIST libcrypto-test.lib, it show the  libcrypto-1_1.dll

version:openssl-1.1.1t
system:window10
visual studio verison:2017

the attachment is the makefile config

**Comment by levitte** [comment]
You didn't attach the makefile config, but I understand the concern.  Let me have a look to see what may have happened

**Comment by levitte** [comment]
Yup, we're not doing it quite right in that OpenSSL version.  This patch should fix it, can you confirm?

``` diff
diff --git a/util/mkdef.pl b/util/mkdef.pl
index 3ac79821b0..0599f23f0b 100755
--- a/util/mkdef.pl
+++ b/util/mkdef.pl
@@ -197,6 +197,7 @@ foreach (@ARGV, split(/ /, $config{options}))
 	}
 $libname = $unified_info{sharednames}->{libcrypto} if $do_crypto;
 $libname = $unified_info{sharednames}->{libssl} if $do_ssl;
+$libname .= $target{shlib_variant} || "";
 
 if (!$libname) {
 	if ($do_ssl) {
```

**Comment by mengzhisuoliu** [comment]
> Yup, we're not doing it quite right in that OpenSSL version. This patch should fix it, can you confirm?
> 
> ```diff
> diff --git a/util/mkdef.pl b/util/mkdef.pl
> index 3ac79821b0..0599f23f0b 100755
> --- a/util/mkdef.pl
> +++ b/util/mkdef.pl
> @@ -197,6 +197,7 @@ foreach (@ARGV, split(/ /, $config{options}))
>  	}
>  $libname = $unified_info{sharednames}->{libcrypto} if $do_crypto;
>  $libname = $unified_info{sharednames}->{libssl} if $do_ssl;
> +$libname .= $target{shlib_variant} || "";
>  
>  if (!$libname) {
>  	if ($do_ssl) {
> ```

oh,my god ! it's working well. thank you very much.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
