### ISSUE TITLE
Configure VC-WIN64A fails using MSVC 2022 on Windows with OpenSSL 3.1.0

### ISSUE THREAD

**Issue by drppetrov** [openssl/openssl#20951]
I've run the config step successfully:
```
SET VS_ENVIRONMENT="C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/Tools/VsDevCmd.bat"
SET CERT_DIR="C:\Certs"
SET SRC_DIR="D:\X\OpenSSL3\openssl-3.1.0"
SET BUILD_DIR="D:\X\OpenSSL3\openssl-3.1.0-bin"

call %VS_ENVIRONMENT%
cd %SRC_DIR%
perl Configure VC-WIN64A shared --prefix=%BUILD_DIR% --openssldir=%CERT_DIR%
perl configdata.pm --dump > ../OUT-CONFIG.txt 2>&1
nmake
nmake test
nmake install
```

However during the build step I encounter the following error:

crypto\bn\rsa_sup_mul.c(139): fatal error C1189: #error:  Only x64, ARM64 and IA64 supported.

Please, see attached config and build outputs from terminal.

[OUT-BUILD.txt](https://github.com/openssl/openssl/files/11465073/OUT-BUILD.txt)
[OUT-CONFIG.txt](https://github.com/openssl/openssl/files/11465076/OUT-CONFIG.txt)

**Comment by t8m** [comment]
Are you sure you set your environment so the 64 bit build environment is used?

**Comment by t8m** [comment]
From NOTES-windows.md:  `run cmd and execute vcvarsall.bat with one of the options x86, x86_amd64, x86_arm, x86_arm64, amd64, amd64_x86, amd64_arm, or amd64_arm64` - did you do that - in your case concretely `vcvarsall.bat amd64`

**Comment by drppetrov** [comment]
Deleting the source folder and starting from clean did solve it. Apparently, some temp files inside the source folder were the culprit. Thanks for assistance, @t8m
