### ISSUE TITLE
OpenSSL is non-reproducible

### ISSUE THREAD

**Issue by tanvirroshid** [openssl/openssl#20954]
I am building dependencies from FDSK.

I am using this [git_tag](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tree/bb8337768b0a492431883cf73e09986eac976719) of FDSK for my project, which happens to reference this [version](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/bb8337768b0a492431883cf73e09986eac976719/elements/components/openssl.bst#L69) of openssl.

My issue is that openssl reports itself to be non-reproducible. From my understanding, it is because of this [file](https://github.com/openssl/openssl/blob/a92271e03a8d0dee507b6f1e7f49512568b2c7ad/crypto/modes/asm/aes-gcm-avx512.pl#L195), which happens to introduce random strings.

I need to know if I add a patch file to my system to seed the random number generator, if this would have potential security flaws?

For further info, please read: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1589

**Comment by tanvirroshid** [comment]
Update: the patch to seed the random generator makes openssl reproducible but I need to know about the security implications

**Comment by paulidale** [comment]
There won't be any security implications here.  It's generating assembly labels which should disappear come link time.
Still, it's not good practice to do this and a non-random alternative (counter based?) should be easy.

I consider this vile enough to be a bug rather than a nice to have.

**Comment by tanvirroshid** [comment]
> There won't be any security implications here. It's generating assembly labels which should disappear come link time. Still, it's not good practice to do this and a non-random alternative (counter based?) should be easy.
> 
> I consider this vile enough to be a bug rather than a nice to have.

Thank you for your response :)

**Comment by trigpolynom** [comment]
Can I take this issue on?

**Comment by kroeckx** [comment]
Yes
