### ISSUE TITLE
Add check_doc build to the list of actions that automatically run.

### ISSUE THREAD

**Issue by IDisposable** [openssl/openssl#20964]
While trying to push https://github.com/openssl/openssl/pull/20936 through the end I noticed _after maintainer approval_ that the document `doc_nits` build ran and found an error in my document changes. Sorry about that!

What would be awesome if if the CI process added the document check to the list of (6?) builds that run without approval so I could have caught my error sooner. This is especially important because it's really hard to get to the previous doc_nits output once another commit has been pushed because the preapproved builds will rerun and wipe out the prior run results.

This is what it looks like after I submit the PR and the initial checks run
<img width="843" alt="image" src="https://github.com/openssl/openssl/assets/874059/275850f1-c624-417b-80ce-4664085bcf2c">

**Comment by paulidale** [comment]
After your first commit to the repository, there is no approval required for running the tests.
Before your first commit, we need to approve because GitHub says we do.

**Comment by paulidale** [comment]
Not commits to the PR, but to the master repository.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
