### ISSUE TITLE
Static libcrypto uses DLL pinning

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#20977]
_Not sure whether this qualifies as a bug or just as surprising undocumented behaviour; since there exists a workaround, I open this issue anyway to document it._

A colleague noticed that one of our Windows DLLs which links statically to libcrypto could not be unloaded anymore using `FreeLibrary()` after switching from OpenSSL 1.0.2 to OpenSSL 1.1.1.

It seems like libcrypto unconditionally attempts to pin its parent DLL, even if it is not built as a shared library.

https://github.com/openssl/openssl/blob/43d5dac9d00ac486823d949f85ee3ad650b62af8/crypto/init.c#L140-L142

There is an option `no-pinshared` to prevent DLL pinning, which was introduced by @mattcaswell  to `master` in #7647 (to fix #7598) and backported to 1.1.1 in #7983, but currently `no-shared` does not imply `no-pinshared`.

_Configuring with `no-pinshared` as a workaround should fix my colleague's problem (not tested yet)._

However, I have two questions remaining

**Question 1**

Shouldn't `no-shared` imply `no-pinshared` to prevent such a surprising behaviour?

```patch
diff --git a/Configure b/Configure
index a6c9af9398..bb76d09788 100755
--- a/Configure
+++ b/Configure
@@ -633,7 +633,7 @@ my @disable_cascades = (
     # which cannot be guaranteed if shared libraries aren't present.
     # (note that even with shared libraries, both the app and dynamic engines
     # must be linked with the same library)
-    "shared"            => [ "dynamic-engine", "uplink" ],
+    "shared"            => [ "dynamic-engine", "uplink", "pinshared" ],
     "dso"               => [ "dynamic-engine", "module" ],
     # Other modules don't necessarily have to link with libcrypto, so shared
     # libraries do not have to be a condition to produce those.
```

**Question 2**

In https://github.com/openssl/openssl/pull/7647/commits/80d4efdc99cc11589ea2632a6a3f32a8a6c8d762, `atexit()` was replaced by `_onexit()` on Windows, because the latter is called on DLL unload. Doesn't that imply that DLL-Pinning is not necessary anymore on Windows?

**Comment by t8m** [comment]
I would not consider any of these bugs and backport them. Especially because if someone started to depend on the DLL being pinned, their application might be broken if we change the behavior. I consider this being a documentation issue.

**Comment by mspncp** [comment]
See #20985
