### ISSUE TITLE
How to resolve provider initialization dependencies

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#20975]
Is it conceivable to automatically resolve provider dependencies at initialization time?

See https://github.com/open-quantum-safe/oqs-provider/issues/159 for the concrete problem.

Background: [oqsprovider](https://github.com/open-quantum-safe/oqs-provider) depends on [liboqs](https://github.com/open-quantum-safe/liboqs) which in turn uses `openssl` for some classic crypto operations (SHA,SHAKE,AES). Now, if for some reason `oqsprovider` is initialized first (e.g., if passed first on the command line via `-provider` option), initialization fails as the default provider is not yet available to permit `liboqs` to initialize openssl's classic crypto code (due to resolving an "OpenSSL3 anti-pattern" https://github.com/open-quantum-safe/liboqs/issues/1427). Just turning around the parameters on the command line resolves the issue: `-provider default -provider oqsprovider` guarantees proper system startup. It may be pretty surprising to users that the order of providers listed on the command line decides whether or not the command works.

Also see discussion in https://github.com/open-quantum-safe/liboqs/issues/1462.

**Comment by paulidale** [comment]
Responded in the [linked issue](https://github.com/open-quantum-safe/liboqs/issues/1462#issuecomment-1549515703).

**Comment by baentsch** [comment]
Thanks @paulidale @t8m for feedback and suggestions. The acute issue for oqsprovider is thus resolved. 

But the nagging feeling remains (whether order of provider initialization should have a reading on their proper functioning)? Might it be an idea to add a "provider prerequisite" facility to OpenSSL? Along the lines "this provider requires these algorithms" -- such that OpenSSL itself can issue a warning if such dependencies are not met -- or can meet them by changing the initialization order suitably if all required providers are configured (possibly just in the wrong order)?

But then again, this seems too much effort for a corner case. Maybe all that's needed is some documented warning to provider implementers....

**Comment by t8m** [comment]
I am not sure making a list of algorithms a provider requires and provides makes that much sense as providing one algorithm might require one set of algorithms but providing another algorithm could imply requirement of completely different set. In other cases the required algorithms might be even depending on parameters of an algorithm.

I think documenting that provider initialization should not depend on another provider being initialized should be sufficient.

**Comment by baentsch** [comment]
> as providing one algorithm might require one set of algorithms but providing another algorithm could imply requirement of completely different set

Good point.

>  documenting that provider initialization should not depend on another provider being initialized should be sufficient.

OK ... stating rather "...provider initialization should not depend on another provider having been initialized..."?

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by baentsch** [comment]
@nhorman Please note #24884 closing this issue for good. If this "inactive" label disables notifications/requests for review(?), please also remove that. Thanks.

**Comment by nhorman** [comment]
@baentsch thanks for the heads up, the inactive label does nothing here regarding notifications.  It only serves as a marker for issue cleanup  later in the dev cycle.
