### ISSUE TITLE
SSL_SESSION_get_id returns length 0

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#2097]
I'm currently experiencing a strange behaviour. I'm calling SSL_SESSION_get_id and I got a valid id, but the length field is 0! How can I get the length field, because I want to copy the id value to another buffer and for mallocing I need it. I`m sure this was working in older version?! I use openssl version openssl-1.1.0.

```
const unsigned char *SSL_SESSION_get_id(const SSL_SESSION *s, unsigned int *len)
{
    if (len)
        *len = s->session_id_length;
    return s->session_id;
}
```

**Comment by mattcaswell** [comment]
Is this still an issue?

**Comment by mattcaswell** [comment]
Assuming this is no longer an issue so closing.

**Comment by ashwinikumar31** [comment]
I am observing this issue in version 3.0.0.

**Comment by paulidale** [comment]
This function always returns a non-NULL pointer.  If the returned length is zero, I'm guessing that it's not valid.

**Comment by bplu4t2f** [comment]
The `SSL_SESSION` might be a non-resumed TLSv1.2 session ticket, in which case the session ID is empty. When using TLSv1.2 session tickets, the session ID which is transmitted in the TLS handshake is an arbitrary value generated by the client (!).

At least as far as [rfc5077, section 3.4](https://datatracker.ietf.org/doc/html/rfc5077#section-3.4) is concerned. I'm assuming this directly maps to OpenSSL's `SSL_SESSION`'s session ID.

**Comment by kaduk** [comment]
My reading of the code suggests that we'll use a (sha256) digest of the received ticket as the session_id when using a session that's ticket-based.
But, the server is not going to verify that, so your conclusion that the value is not safe to use by the server for client identification seems to hold.

You may be interested in the `SSL_SESSION_has_ticket()` and `SSL_SESSION_get0_ticket()` APIs, which let you know whether you should be looking at the ticket (vs session ID) and obtain a (temporary) pointer to the ticket body, which would then be usable for identifying the client.  (You'd need to make a copy of the ticket contents, I expect.)

**Comment by bplu4t2f** [comment]
@kaduk `SSL_SESSION_has_ticket()` and `SSL_SESSION_get0_ticket()` don't work on the server side.

I have a secondary discussion ongoing regarding identifying clients as a server via TLS sessions, which appears to be an astonishingly non-trivial task, so I didn't expect to get a response here. I merely stumbled upon this ticket while searching, and noticed that the original question was still unanswered.
