### ISSUE TITLE
Generate fips provider as part of built-in provider of libcrypto

### ISSUE THREAD

**Issue by chaitu-venky** [openssl/openssl#20988]
The fips.dylb dynamic library is produced by the openssl version 3.x crypto construction process and has to be loaded dynamically. 
I see that there is an option to establish a legacy provider such that it is a part of the crypto library, but not for fips. 
In order to ship the entire crypto binary as part of my iOS framework rather than two frameworks (myframework + openssl_fips_provider framework), I need to produce fips as part of the libcrypto library.

**Comment by t8m** [comment]
The fips provider needs to be able to perform integrity check upon itself. For that reason it is not possible to have fips provider as a static library or a part of libcrypto.

**Comment by t8m** [comment]
> @t8m Thanks for the quick response. According to what I understand, fips won't run those checks if we specify the build with 'no-fips-securitychecks'? Is that a true comprehension?

Nope, this is about various FIPS-implied limitations on key sizes and other things. It does not affect the self testsm including the integrity check.

**Comment by paulidale** [comment]
Essentially if you static link the FIPS provider, the run time loader changes it's contents when it applies relocations and it's integrity checks will fail.  As a loadable library, we can checksum the file and the integrity checks pass.
