### ISSUE TITLE
How to encrypt data using RSA, with SHA-256 as hash function and MGF1

### ISSUE THREAD

**Issue by Sushi-FHE** [openssl/openssl#20984]
Dear all,

we try to migrate our code from openssl 1.0.2 to 3.1.0.

In openssl1.0.2, we followed the solution proposed here

https://stackoverflow.com/questions/17784022/how-to-encrypt-data-using-rsa-with-sha-256-as-hash-function-and-mgf1-as-mask-ge

i.e., we run

```
EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_OAEP_PADDING);

EVP_PKEY_CTX_set_rsa_oaep_md(ctx, EVP_sha256());

EVP_PKEY_CTX_set_rsa_mgf1_md(ctx, EVP_sha256());

ret = EVP_PKEY_decrypt(ctx, outData, &outLen, data, length);

```

In Openssl1.0.2, we had ret == 1, in openssl3.1.0 we have ret == 0.

I figured that this results from the call in `EVP_PKEY_decrypt()`, which calls the function `RSA_padding_check_PKCS1_OAEP_mgf1()`, which returns 1. However, I am unsure, how I should fix this.

Thanks a lot

**Comment by t8m** [comment]
At first sight I do not see a reason why this should not work for openssl-3.1.0. How do you import the public key and how do you initialize the decryption context? Does it work if you use the default mds for OAEP and MGF1? And/or is this an interop problem? I.e., if you encrypt with 1.0.2 and decrypt with 3.1.0 it fails, or even 3.1.0 encrypted data cannot be decrypted?

**Comment by Sushi-FHE** [comment]
I guess you are right, and that the error already happens beforehand. Thanks for having a look into it, and excuse the confusion.
Best
