### ISSUE TITLE
Is 3.0.7 FIPS certified? 

### ISSUE THREAD

**Issue by GennadyDagman** [openssl/openssl#20997]
I see that FIPS certification is done for 3.0.0 https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282 - I wonder if it covers all 3.0.x versions ?

**Comment by paulidale** [comment]
No.  3.0.7 will never be FIPS certified.
At the moment, **only** 3.0.0 is FIPS certified.

However, you can use the validated FIPS provider with any versions 3.0.x and 3.1.x and remain FIPS compliant.

**Comment by GennadyDagman** [comment]
>>However, you can use the validated FIPS provider with any versions 3.0.x and 3.1.x and remain FIPS compliant.How can I do it - are there any docs/instructions that you can point me to? I am building OpenSsl libs (for android app) while using this approach: "Making all applications use the FIPS module by defaultOne simple approach is to cause all applications that are using OpenSSL to only use the FIPS module for cryptographic algorithms by default." and thus I guess FIPS module (provider) is by default embedded (right?) during building of libcrypto lib. I assume it comes from providers/fips.* library - right? Does that mean that I need first to do the build process for OpenSsl 3.0.0, copy built fips.* library an then replace it somehow during 3.0.7 build?

    On Thursday, May 18, 2023 at 03:15:40 PM PDT, Pauli ***@***.***> wrote:  
 
 


No. 3.0.7 will never be FIPS certified.
At the moment, only 3.0.0 is FIPS certified.

However, you can use the validated FIPS provider with any versions 3.0.x and 3.1.x and remain FIPS compliant.

**Comment by paulidale** [comment]
The required documentation is in progress: https://github.com/openssl/openssl/pull/20907/files

**Comment by mspncp** [comment]
> No. 3.0.7 will never be FIPS certified. At the moment, **only** 3.0.0 is FIPS certified.
> 
> However, you can use the validated FIPS provider with any versions 3.0.x and 3.1.x and remain FIPS compliant.

@paulidale, @omc: since we are getting and answering questions of this type more frequently, wouldn't it make sense to place this information prominently onto our [FIPS-140](https://www.openssl.org/docs/fips.html) web page to a) reduce the number of redundant issues and b) have a link which we can post as a standard reply to such questions?

**Comment by paulidale** [comment]
Once it is approved and merged, it would make sense.

Honestly, we're getting lots of questions about building and installing the FIPS provider.
FIPS is fickle and obtuse.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
