### ISSUE TITLE
Is everything OK with this piece of code?

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#20993]
https://github.com/openssl/openssl/blob/859521e57970027c2ec763928753a1e5f843cf69/providers/implementations/asymciphers/rsa_enc.c#L164-L169

I think it should be the same as 
https://github.com/openssl/openssl/blob/859521e57970027c2ec763928753a1e5f843cf69/providers/implementations/asymciphers/rsa_enc.c#L249-L257

**Comment by t8m** [comment]
Yeah, the second case seems to be correct. Will you submit a PR?

**Comment by beldmit** [comment]
Yes
