### ISSUE TITLE
What coordinate system is “EC_POINT_mul” done in?

### ISSUE THREAD

**Issue by galaxysmonkey** [openssl/openssl#21000]
Does it depend on the point in which coordinate system I set? Or it switchs automatically to reach the maximum efficiency?

**Comment by galaxysmonkey** [comment]
Can I choose the coordinate system myself?

**Comment by mattcaswell** [comment]
You can influence the coordinate system that you supply the original point in. Typically you would supply affine co-ords via `EC_POINT_set_affine_coordinates()`. It is also possible to supply the co-ords in compressed form via `EC_POINT_set_compressed_coordinates()`.

Alternatively it is possible to supply them as projective co-ords via `EC_POINT_set_Jprojective_coordinates_GFp()` - but this is deprecated in OpenSSL 3.0.

See:
https://www.openssl.org/docs/man3.1/man3/EC_POINT_set_Jprojective_coordinates_GFp.html

You cannot influence the co-ordinate system used internally. OpenSSL will convert points between co-ordinate systems automatically as appropriate.

**Comment by galaxysmonkey** [comment]
Thank you so much for your help! I really appreciate it.😄
