### ISSUE TITLE
win10 VS2022 build openssl fail

### ISSUE THREAD

**Issue by injertao** [openssl/openssl#21014]
perl Configure VC-WIN64A

Using os-specific seed configuration

Failure!  build file wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

NASM not found - make sure it's installed and available on %PATH%

i use strawberry-perl-5.32.1.1-64bit

The PATH is also correct

I have almost looked at all the problems and still haven't solved them

**Comment by mattcaswell** [comment]
So I assume you have actually installed NASM and put it on your %PATH% as per the NOTES-WINDOWS.md file?

What happens when you try and run NASM directly from the command line, e.g.

````
> nasm --version
````

**Comment by injertao** [comment]
C:\Work\Code\openssl-openssl-3.1.0>nasm --version
NASM version 2.16.01 compiled on Dec 21 2022

**Comment by mattcaswell** [comment]
Hmmm. Curious. Let's confirm that you are picking up the expected version of perl. Please report the result of:

````
> perl --version
````

**Comment by injertao** [comment]
> 

C:\Work\Code\openssl-openssl-3.1.0>perl --version

This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by mattcaswell** [comment]
Hmm. I have no idea.

The error message comes from this piece of perl code in `Configurations\10-main.conf`:

```` perl
my $vc_win64a_info = {};
sub vc_win64a_info {
    unless (%$vc_win64a_info) {
        if (`nasm -v 2>NUL` =~ /NASM version ([0-9]+\.[0-9]+)/ && $1 >= 2.0) {
            $vc_win64a_info = { AS        => "nasm",
                                ASFLAGS   => "-g",
                                asflags   => "-Ox -f win64 -DNEAR",
                                asoutflag => "-o " };
        } elsif ($disabled{asm}) {
            # assembler is still used to compile uplink shim
            $vc_win64a_info = { AS        => "ml64",
                                ASFLAGS   => "/nologo /Zi",
                                asflags   => "/c /Cp /Cx",
                                asoutflag => "/Fo" };
        } else {
            $die->("NASM not found - make sure it's installed and available on %PATH%\n");
            $vc_win64a_info = { AS        => "{unknown}",
                                ASFLAGS   => "",
                                asflags   => "",
                                asoutflag => "" };
        }
    }
    return $vc_win64a_info;
}
````

So, it's checking that it can run nasm, and if it can that the version is >= 2.0 - which it is for you since you seem to have 2.16.01.

Maybe @levitte has some suggestions.

**Comment by dg0yt** [comment]
What is the output of 
~~~
perl -e "print `nasm -v 2>NUL`;"
~~~

**Comment by dg0yt** [comment]
(Basically I'm wondering if environment variable `PERL5SHELL` might be set to something which doesn't understand `2>NUL`, such as `powershell`.)

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by rhzxg** [comment]
> (Basically I'm wondering if environment variable `PERL5SHELL` might be set to something which doesn't understand `2>NUL`, such as `powershell`.)

```
perl -e "print `nasm -v 2>NUL`;"
```
This may output an empty line because perl can not parse backquote correctly; the reason remains unclear.

The output will be correct by using the absolute path of nasm:
```
perl -e "system('xxx\\nasm\\nasm-2.16.01\\nasm.exe -v');"
```

**Comment by rhzxg** [comment]
To solve this temporarily, modify `openssl.tar.gz` and one port file:

1. Open openssl.tar.gz by using 7zip
2. Find `Configurations\10-main.conf` and modify it to force using nasm(install it first of course).:
```
my $vc_win64a_info = {};
sub vc_win64a_info {
    unless (%$vc_win64a_info) {
        $vc_win64a_info = { AS        => "nasm",
                            ASFLAGS   => "-g",
                            asflags   => "-Ox -f win64 -DNEAR",
                            asoutflag => "-o ",
                            perlasm_scheme => "nasm" };
        
    }
    return $vc_win64a_info;
}

my $vc_win32_info = {};
sub vc_win32_info {
    unless (%$vc_win32_info) {
        $vc_win32_info = { AS        => "nasm",
                           ASFLAGS   => "",
                           asflags   => "-f win32",
                           asoutflag => "-o ",
                           perlasm_scheme => "win32n" };
    }
    return $vc_win32_info;
}
```
3. Update the modified tar.gz and calculate and copy its CRC SHA512 value
4. Find and open `vcpkg\...\versions\openssl\...\portfile.cmake` manually or by using `EveryThing`
5. Find `from github` field and edit the following SHA512 value to the value calculated above:
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO openssl/openssl
    HEAD_REF master
    REF "openssl-${VERSION}"
    SHA512 xxx
```
6. CMake again

**Comment by dg0yt** [comment]
> ```
> perl -e "print `nasm -v 2>NUL`;"
> ```
> 
> 
>     
>   
> 
> This may output an empty line because perl can not parse backquote correctly; the reason remains unclear.

Perl can do that when `nasm` is in `PATH`. But to reach perl, the backticks must not be expanded by the command line interpreter. In `sh` or `bash`, I would need to do

~~~
perl -e 'print `nasm -v 2>NUL`;'
~~~


> Update the modified tar.gz and calculate and copy its CRC SHA512 value

Actually this is where you create a diff and add it as a separate file which is applied with `PATCHES`.

**Comment by dg0yt** [comment]
> Find `Configurations\10-main.conf` and modify it to force using nasm(install it first of course):

IIUC the essence of the proposed modification is to not test for the nasm version, i.e. turn line 8 into `if (1) {` here:

https://github.com/openssl/openssl/blob/995e9489e62ff1965553c4e127183565ccfe4265/Configurations/10-main.conf#L6-L13

**Comment by rhzxg** [comment]
I am not familiar with `portfile.cmake`, so this is only a temporary solution. Thanks for your correction.

**Comment by dg0yt** [comment]
> The output will be correct by using the absolute path of nasm:
> 
> ```
> perl -e "system('xxx\\nasm\\nasm-2.16.01\\nasm.exe -v');"
> ```

This omits the part which had my attention: `2>NUL`.

But maybe it is enough to just remove this fragment: The pattern matching would pick the right part of the output anyways.
