### ISSUE TITLE
OpenSSL 3.0.8 Bug in EVP_get_digestbynid

### ISSUE THREAD

**Issue by urbanlion** [openssl/openssl#21017]
Hello OpenSSL-Experts,

I think i found an issue when calling EVP_get_digestbynid with sha384 (nid= 673). I tried it with OpenSSL 3.0.8 which failed. But OSSL 3.0.2 did not fail.

As example:

```
int main(){

    const EVP_MD *type = EVP_get_digestbynid(673);
    if(type == NULL){
        std::cout << "Error in " << std::hex << OpenSSL_version_num() << std::endl;
        return -1;
    }
    return 0;

}
```
**Expected Behavior**:
Main returns 0.

**Current Behavior**:
Main returns -1 using OpenSSL 3.0.8.

**Comment by mattcaswell** [comment]
That is very strange. This works perfectly for me against 3.0.8.

Where did you get your version of 3.0.8? Did you compile it yourself? What platform are you on?

**Comment by urbanlion** [comment]
Hi, yes the library is compiled by myself, i got it from GitHub regular 3.0.8 version. Platform is linux and compiled with clang14.

**Comment by urbanlion** [comment]
After quick testing, unfortunately i used the same build commands for Openssl 1.1.1. Some of the compile options may have been deprecated as i assume. I am closing this issue.
