### ISSUE TITLE
FIPS 140-3 certificate submission plans

### ISSUE THREAD

**Issue by vikas-yadav77** [openssl/openssl#21021]
Hello team,

Thanks for allowing us to ask questions on this forum and for providing us the latest features/certifications in crypto.

We would like to get the latest updates on FIPS 140-3 certification for OpenSSL 3.1. We learned from the following blog that the OpenSSL group has started working on FIPS 140-3. https://www.openssl.org /blog/blog/2022/09/30/fips-140-3/

Since the blog was updated in last year September, do we have current updates about FIPS certification, By when we are going for FIPS 140-3 submission and when will we have the certification

We know that FIPS certification is a very time consuming process and it is difficult to estimate the actual date so could you please give us a tentative date for the certification.

Thanks for the support!

**Comment by paulidale** [comment]
There is no tangible update for the 140-3 submission.  It hasn't been queued to the lab yet.  Once it is, expect a year or longer for the validation to complete.

**Comment by mattcaswell** [comment]
Our 140-3 submission was made:

https://www.openssl.org/blog/blog/2024/01/04/OpenSSL31-fips-submission/

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
