### ISSUE TITLE
openssl rsa  command no longer providing a pkcs1 formatted key

### ISSUE THREAD

**Issue by aufewl** [openssl/openssl#21025]
I may be misunderstanding this, so im putting it in as a question. To get the reverse proxy working for Apache HTTPD, the concatenated cert and key go into a single file. the key is required to be in pkcs1 format. In the past, this was done with the following command:

 
    "$ openssl rsa -in mypkcs8.key -out mypkcs1.key"
   
the pkcs8 cert would be:
------BEGIN PRIVATE KEY------

the pkcs1 would look like:
------BEGIN RSA PRIVATE KEY------

now when the command is ran, im only seeing the same pkcs8 formatted key as passed with -in, in the file -out.

current openssl package is:
openssl-1.0.2k-26.el7_9.x86_64 running on RHEL.

**Comment by lan1120** [comment]
Maybe you could try the -raditional parameter?

**Comment by aufewl** [comment]
that looked promising, but is not showing as an option for the version I have....

**Comment by t8m** [comment]
It's `openssl pkey -in pkcs8.pem -out pkcs1.pem -traditional`

**Comment by aufewl** [comment]
only options for pkey is -in, -inform, -passin, -outform, -out, -passout, -engine.... using pkey, i still only see the pkcs8 format, no change in out

**Comment by aufewl** [comment]
doing a search of the man page, no results for 'traditional'

**Comment by t8m** [comment]
Ah, you're using openssl-1.0.2k from Red Hat. That version does not support the `-traditional` option.

We do not support 1.0.2 version anymore except for premium support customers.

**Comment by aufewl** [comment]
does anyone know what version of openssl from redhat can still do this conversion?

**Comment by levitte** [comment]
Side note: I'm quite surprised that apache httpd wouldn't support pkcs8...
