### ISSUE TITLE
incorrect parameter verification in EVP_MD_CTX_get_params

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#21020]
ctx->digest->get_params is verified， but ctx->digest->get_ctx_params is used.

`
int EVP_MD_CTX_get_params(EVP_MD_CTX *ctx, OSSL_PARAM params[])
{
    EVP_PKEY_CTX *pctx = ctx->pctx;

    /* If we have a pctx then we should try that first */
    if (pctx != NULL
            && (pctx->operation == EVP_PKEY_OP_VERIFYCTX
                || pctx->operation == EVP_PKEY_OP_SIGNCTX)
            && pctx->op.sig.algctx != NULL
            && pctx->op.sig.signature->get_ctx_md_params != NULL)
        return pctx->op.sig.signature->get_ctx_md_params(pctx->op.sig.algctx,
                                                         params);

    if (ctx->digest != NULL && ctx->digest->get_params != NULL)
        return ctx->digest->get_ctx_params(ctx->algctx, params);

    return 0;
}
`

**Comment by JerryDevis** [comment]
fixed by #21022
