### ISSUE TITLE
openssl 3.0 setting OPENSSL_MODULES env variable to the installation directory path and loading fips provider

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#21024]
I'm distributing fips.dll to other VMs, therefore I need to give fips.dll path same as installation directory where I'm deploying fips.dll
However on setting the env variable, it tries to load the fips.dll from C:\Program Files (x86)\OpenSSL\lib\ossl-modules\fips.dll

What is the correct way to set the environment variable so that it should load fips.dll correctly from my installation directory.
_putenv_s is not working in windows.

If I manually set the system env variable; fips.dll is loading properly. However the challenge is the setting the env variable from code, seems limitation in windows c++.

> putenv_s("OPENSSL_MODULES", "D:\\lib");
>     OSSL_PROVIDER* fips;
>     if (!OSSL_LIB_CTX_load_config(NULL, "D:\\config\\openssl.cnf"))
>     {
>         ERR_print_errors_cb(err_print_line, NULL);
>     }
>     fips = OSSL_PROVIDER_load(NULL, "fips");
>     if (fips == NULL) {
>         ERR_print_errors_cb(err_print_line, NULL);
>     }

**Comment by ChauhanPriyanka** [comment]
OSSL_PROVIDER_set_default_search_path(NULL, "D:\\lib"); is solving the purpose and now there is no need to set the env variable.  Is this correct

**Comment by paulidale** [comment]
Be careful with what you are doing.  It is possible to do what you want, however there are restrictions on what files you can copy.  The security policy notes:

> The Module shall have the self-tests run, and the Module config file output generated on each
platform where it is intended to be used. The Module config file output data shall not be copied from
one machine to another.

The set default search path should be fine.

**Comment by ChauhanPriyanka** [comment]
Thank you @paulidale.
I'm shipping fips.dll, openssl.exe, libssl-3, libcrypto-3.dll & openssl.cnf file, however fipsconfig,cnf file will be generated in customers env or each VM using fips install command. Please let me know if this is correct way to align with FIPS compliance of openssl 3.0 .

**Comment by paulidale** [comment]
That complies to the best of my knowledge.
I figured the warning was useful because many don't do this but expect that it works.
Technically, it shouldn't be required.  Administratively, it is.

I'll also note that my knowledge is lacking here, the **only definitive response** is to ask your FIPS lab.

Anyway, closing this issue as resolved.
