### ISSUE TITLE
PKCS5_PBKDF2_HMAC reports invalid iteration count if the iteration argument is zero

### ISSUE THREAD

**Issue by code4lala** [openssl/openssl#21038]
The `PKCS5_PBKDF2_HMAC` interface reports `invalid iteration count` if the iteration argument is zero, but the document tells me it should work like the iteration argument is one.

the doc link:
https://www.openssl.org/docs/man3.1/man3/PKCS5_PBKDF2_HMAC.html
> iter is the iteration count and its value should be greater than or equal to 1. RFC 2898 suggests an iteration count of at least 1000. **Any iter less than 1 is treated as a single iteration.**

The docs in the version of 1.1.1, 3.0, 3.1, master have the same part for the iteration count.

example code:

``` c
#include <openssl/evp.h>
#include <openssl/err.h>
#include <openssl/x509.h>

#include "openssl/bn.h"
#include "openssl/crypto.h"
#include "openssl/dsa.h"
#include "print.h"
#include <stdbool.h>

enum {
    FAIL = -1,
    OK = 0,
};

int main()
{
    char mainKey[32] = {0};
    uint8_t salt[16] = {0};
    uint8_t derivedKey[32] = {0};
    const EVP_MD *md = EVP_sha256();

    int opensslRet = PKCS5_PBKDF2_HMAC(mainKey, sizeof(mainKey), salt, sizeof(salt),
        1000, md, sizeof(derivedKey), derivedKey);
    LOGI("it=1000 opensslRet = %d", opensslRet);
    if (opensslRet != 1) {
        LOGE("error! %d, %s", opensslRet, ERR_reason_error_string(ERR_get_error()));
    }

    opensslRet = PKCS5_PBKDF2_HMAC(mainKey, sizeof(mainKey), salt, sizeof(salt),
        0, md, sizeof(derivedKey), derivedKey);
    LOGI("it=0 opensslRet = %d", opensslRet);
    if (opensslRet != 1) {
        LOGE("error! %d, %s", opensslRet, ERR_reason_error_string(ERR_get_error()));
    }

    opensslRet = PKCS5_PBKDF2_HMAC(mainKey, sizeof(mainKey), salt, sizeof(salt),
        1, md, sizeof(derivedKey), derivedKey);
    LOGI("it=1 opensslRet = %d", opensslRet);
    if (opensslRet != 1) {
        LOGE("error! %d, %s", opensslRet, ERR_reason_error_string(ERR_get_error()));
    }

    return OK;
}
```

result with tag `OpenSSL_1_1_1n`:

```
[I][main][25]it=1000 opensslRet = 1
[I][main][32]it=0 opensslRet = 1
[I][main][39]it=1 opensslRet = 1
```

result with tag `openssl-3.0.7`, `openssl-3.1.0`

```
[I][main][25]it=1000 opensslRet = 1
[I][main][32]it=0 opensslRet = 0
[E][main][34]error! 0, invalid iteration count
[I][main][39]it=1 opensslRet = 1
```

If the behavior is as expected, the doc may be updated, or please fix the zero iteration bug, thanks!

**Comment by paulidale** [comment]
Looks like a bug introduced in 3.0 where the error is returned if the iteration count is below the minimum (which varies based on FIPS/not FIPS).

Suggest we amend the documentation, rather than providing a default minimum.

**Comment by nhorman** [comment]
this work is done, as the docs now indicate an iteration count less than 1 is invalid
