### ISSUE TITLE
failed to parse sm2 key encryped by legacy or 1.1.1

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#21036]
OpenSSL version：master
Command line test：
openssl genpkey -algorithm SM2  -out  sig.key
openssl ec -in sig.key -sm4 -out sig.key.enc
openssl ec -noout -text -in sig.key.enc

Result：
Could not find key etc. of private key from sig.key.enc

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
