### ISSUE TITLE
How to minimize the implementation of an RSA provider?

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#21031]
Private key separation scenario：
In OpenSSL 1.1.1, I use engine pmeth to set a user-defined signature algorithm. In OpenSSL 3.0, I want to use provider, but it seems necessary to implement the complete RSA algorithm in a new provider. How do I implement only the signature interface and use the default interface for others?  Can you help me?

**Comment by t8m** [comment]
Your provider must implement the full RSA signature support (of course depending on application but I am assuming you want to use the provider universally with various applications not just a single one).

I also assume you will be using just private keys within your provider, not public keys and that the private keys will not be exportable from your provider. In that case you need to just implement the STORE interface, the RSA signature interface and possibly some RSA key management interfaces (for example to be able to export the public key, if you need that operation).

Then the applications that use OSSL_STORE API to load keys from URIs can use an URI scheme defined by your STORE implementation to refer to the private keys inside your provider and then use these keys to sign.

**Comment by selvanair** [comment]
A minimal implementation for signature would need "Key Management" and "Signature" functions for the key types you want to support. When you load and use the provider, set the propquery as "?provider!=<your-provider-name>" or set it as the default propquery for the libctx where it is loaded. That will ensure that your provider gets called only for keys that it manages.

For loading the key, leveraging keymgmt_import() would be the easiest, but if you a store-like interface is needed, "Store Management" (OSSL_OP_STORE) also would have to be implemented.

**Comment by t8m** [comment]
Actually if the private keys are unexportable and keys are loaded through a store implementing dedicated URI scheme, there is no need for propquery manipulation. And the keymgmt just needs to be able to import the key by reference from the store.

**Comment by lan1120** [comment]
@selvanair @t8m Thank you for your reply.
It seems unnecessary to implement necessary key management and signature functions, because PKI only provides signature and decryption functions. I should describe the following application scenarios in detail:
(1) The PKI has the private key and public key certificate. The TLS server has only a public key certificate and needs to invoke the PKI to sign messages.
Ideally, only replace the rsa_sign function in the default implementation of the rsa_digest_sign_final interface.
(2) The PKI has the private key and public key certificate. The TLS server has only the public key certificate. The TLS client uses the public key to encrypt the pre-master key. The TLS server needs to invoke the PKI to decrypt the pre-master key.
Ideally, only replace the RSA_private_decrypt function in the default implementation of the rsa_decrypt interface.

**Comment by selvanair** [comment]
In the provider framework there is no way to just "replace the rsa_sign function in the default implementation" etc.. 

As far as I know, the minimum we have to implement for signing with an "external" private key is what I have in the "xkey-provider" implementation internally used in OpenVPN. Its a builtin provider and handles three kinds of external keys (Windows CNG, PKCS#11 and signature via management interface), so there is some excess and some oddities, but its supposed to be minimalistic otherwise. If there is a way to simplify it like the way we used to hook into sign methods in the past, please do tell.

**Comment by t8m** [comment]
@selvanair you have it completely right. There is no way to further simplify. Some provider boilerplate is always needed, that's a price for an extended compatibility across current and future OpenSSL versions that the providers provide.

**Comment by lan1120** [comment]
Thank you for your reply. I got the default method through the OSSL_PROVIDER_query_operation interface and set it in my provider.
