### ISSUE TITLE
We're using the version OpenSSL 1.0.2k-fips on CentOs7 , but it has reached it's EOL already. So, the new version available 3.0 is not compatible with CentOs7. So, what could be the possible solution we can implement for it's usage on CentOs7/RHEL-7.

### ISSUE THREAD

**Issue by kritika-1720** [openssl/openssl#21043]

**Comment by paulidale** [comment]
OpenSSL 3.0 should build for CentOs7.
You'll have to port your application across to use it.

**Comment by kritika-1720** [comment]
![openssl](https://github.com/openssl/openssl/assets/64278152/dc4727a6-4aa4-4dbd-a727-9d502efdfc2f)
As you have suggested to port application across, so is it meant to do code changes and make compatible.

**Comment by paulidale** [comment]
Yes, update your application so it works with 3.0.

**Comment by t8m** [comment]
Please note we cannot provide you a RPM package that would replace the CentOS 7 system openssl package. That is heavily patched and replacing it with openssl built from pristine sources (even the premium support 1.0.2 sources) is not at all recommended.

Replacing it with 1.1.1 or 3.0 package is practically impossible.

The only thing you could do is, if you have a particular application that uses OpenSSL on that system, to build that application against separate 3.0 build.

**Comment by kritika-1720** [comment]
We have OS RHEL 7.9 , please recommend the version that will go best with RHEL 7.9. 
Please provide the download link for the stable version for RHEL 7.9
Also, whether we need to make any major changes to upgrade version from 1.0.2 to recommended version mentioned above.

**Comment by t8m** [comment]
Any version should be compilable and usable on RHEL-7.9. We do not provide binary packages currently.

There are numerous changes that need to be done with applications that were intended to be built with 1.0.2 version if you want to use them with the current stable versions (3.0, 3.1).

Please see https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes (that's for migration from 1.0.2->1.1.1)
And https://www.openssl.org/docs/man3.1/man7/migration_guide.html (migration from 1.1.1->3.0, 3.1)

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
