### ISSUE TITLE
Which configuration am I supposed to use for android cross compilation?

### ISSUE THREAD

**Issue by Sushi-FHE** [openssl/openssl#21056]
Hi,

I need to compile the openssl lib (version 3.10) for i486-android-llvm and i486-64-android-llvm. (cross compilation from a RHEL8 Machine)
To my understanding, these architectures match to the configurations android-x86 and android64-x86_64 respectively.
When I compile the project with the configurations set, I receive following compilation error:

```
/usr/lib/gcc/x86_64-redhat-linux/8/include/limits.h:194:61: error: no include path in which to search for limits.h
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
In file included from include/openssl/types.h:32,
                 from apps/include/app_libctx.h:13,
                 from apps/lib/app_libctx.c:9:
include/openssl/e_os2.h:234:12: fatal error: inttypes.h: No such file or directory
 #  include <inttypes.h>
            ^~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:3567: apps/lib/libapps-lib-app_libctx.o] Error 1
```

I use the same workflow as when I compile the libs for the arm processors (with the arm configurations), and there it works just fine.

Any help is much appreciated
Best

**Comment by zzqAlex** [comment]
@Sushi-FHE hi, have you solved this problem?
