### ISSUE TITLE
genrsa is not really deprecated although documented so

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#21055]
The notice from openssl-genrsa(1) manpage should be removed.

**Comment by Abdullah-03** [comment]
I'll fix it and open a pull request.

**Comment by Abdullah-03** [comment]
@t8m The [history section](https://www.openssl.org/docs/manmaster/man1/openssl-genrsa.html) of genrsa is only comprised of the statement: _"This command was deprecated in OpenSSL 3.0."_.

Removing it will make it so it will be empty. Is that fine or should something else be added there, if it is to be added then please let me know as I'm not versed enough to do so myself.

**Comment by t8m** [comment]
Replace the statement with `This command was erroneously marked as deprecated in OpenSSL 3.0. It is not deprecated.`

**Comment by Abdullah-03** [comment]
Done.

First issue fixed! Took longer than I expected (forgot to fork, then fixed the change in a different branch in the fork 🙈).

**Comment by paulidale** [comment]
It was deprecated deliberately.  The `erroneously` part isn't correct.

I do agree with keeping the command and undeprecating it.

**Comment by t8m** [comment]
@paulidale No, it was not deprecated. There was originally a decision to deprecate all these gendsa/dsa/rsa/genrsa and similar commands but none of them was in the end deprecated for good reasons. The only deprecated command that should stay deprecated that is related is the `rsautl` command.

**Comment by petrovr** [comment]
Tomáš Mráz wrote:
> @paulidale No, it was not deprecated. ...
Then use another word - legacy , or obsolete, or etc. + reference to new model .

> The only deprecated command that should stay deprecated that is related is the `rsautl` command.

sample, based on rsautl description "This command <STATUS> The <NEW COMMAND> command should be used instead."

Roumen
