### ISSUE TITLE
OpenSSL 3.0 - with and without FIPS enable

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#21053]
Our application (windows) is supported with both FIPS and Non FIPS mode.
Enabling/ Disabling of FIPS mode is controlled by reg key, after updating the reg key, restart of application is required.

As per openssl 3.0 - _what is the role of openssl.cnf file **without** fips mode._.

The content of openssl.cnf file is also be limited as mentioned below (removed other content) - _what will be the impact of removing other content._

> openssl_conf = openssl_init
> config_diagnostics = 1
> .include fipsmodule.cnf
> [openssl_init]
> providers = provider_sect
> [provider_sect]
> fips = fips_sect
> base = base_sect
> [base_sect]
> activate = 1

 **do I have to load openssl.cnf file always irrespective of fips.?**
I was planning to load openssl.cnf file only when reg key is set to load application with FIPS. Is this correct ?

**Comment by t8m** [comment]
If you need only default provider then the openssl.cnf file is not needed.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
