### ISSUE TITLE
TLSv1.2 handshake failed when using OpenSSL 3 legacy engine API

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#21062]
### Issue Description
When using the engine APIs of OpenSSL 3 to test TLSv1.2，the cipher is TLS_RSA_WITH_AES_128_CBC_SHA256，SSL_accept failed.

### SSL server error log
70D51BB8FFFF0000:error:02000090:rsa routines:pkey_rsa_ctrl:illegal or unsupported padding mode:crypto/rsa/rsa_pmeth.c:486:
70D51BB8FFFF0000:error:03000093:digital envelope routines:evp_pkey_ctx_ctrl_int:command not supported:crypto/evp/pmeth_lib.c:1354:
70D51BB8FFFF0000:error:0A000093:SSL routines:tls_process_cke_rsa:decryption failed:ssl/statem/statem_srvr.c:3127:

### Root cause
(1) pkey_rsa_ctrl() does not support the RSA_PKCS1_WITH_TLS_PADDING.
(2) evp_pkey_ctx_set_params_to_ctrl() does not support the "tls-client-version" and "tls-negotiated-version" params.

### There are two plans here
**1. Make rsa pmeth to support RSA_PKCS1_WITH_TLS_PADDING**
(1) modify pkey_rsa_ctrl() to support the RSA_PKCS1_WITH_TLS_PADDING, 
(2) modify pkey_rsa_ctrl() to support "tls-client-version" and "tls-negotiated-version" params, need add client_version and alt_version to RSA_PKEY_CTX.
(3) modify evp_pkey_ctx_set_params_to_ctrl() to support the "tls-client-version" and "tls-negotiated-version" params, so these two parameters are passed to RSA_PKEY_CTX.
(4) modify pkey_rsa_decrypt() to to support the RSA_PKCS1_WITH_TLS_PADDING, and call ossl_rsa_padding_check_PKCS1_type_2_TLS() after RSA_private_decrypt()
then EVP_PKEY_decrypt() can get 48 bytes pre-master key

**2. In tls_process_cke_rsa(), if privatekey is legacy, call tls_process_cke_rsa_legacy(), its implementation is almost identical to version 1.1.1**

**Can you help me analyze which solution is more suitable for OpenSSL 3.0? Maybe you have a better plan, please tell me, thank you.**

**Comment by t8m** [comment]
I do not think adding features to rsa pmeth makes any sense so either we do 2) or we will have to accept that these ciphers won't work with legacy keys anymore as a known issue.

**Comment by t8m** [comment]
But @mattcaswell might have different opinion?

**Comment by mattcaswell** [comment]
> or we will have to accept that these ciphers won't work with legacy keys anymore as a known issue.

I personally think this is a "won't fix". Neither 1 nor 2 sound particularly appealing.

**Comment by t8m** [comment]
I agree.

**Comment by lan1120** [comment]
Thank you for your reply. I'll probably use the provider.

**Comment by assurend** [comment]
Hello @lan1120 
Could you kindly provide the location of the function "tls_process_cke_rsa_legacy()" as mentioned in plan 2? I've been unable to find it within the OpenSSL 3.0 directory.
