### ISSUE TITLE
CA.pl does not allow to use env var OPENSSL_CONFIG

### ISSUE THREAD

**Issue by gurucubano** [openssl/openssl#21064]
We compile openssl 1.1.1t on SuSE Linux SLES15 and run into the following bug:
```
export OPENSSL=/usr/local/sisis-pap/bin/openssl
export OPENSSL_CONFIG=/usr/local/sisis-pap/openssl.cnf
cp -p /usr/local/sisis-pap/misc/CA.pl .
./CA.pl -newca
CA certificate filename (or enter to create)

Making CA certificate ...
====
/usr/local/sisis-pap/bin/openssl req /usr/local/sisis-pap/openssl.cnf -new -keyout ./demoCA/private/cakey.pem -out ./demoCA/careq.pem
req: Use -help for summary.
==> 256
====
```
The problem comes out of the definition for the command to run in CA.pl as:
```
grep 'my $REQ' CA.pl
my $REQ = "$openssl req $OPENSSL_CONFIG";
```
while the command `req` does not accept as next parameter such file name.

**Comment by t8m** [comment]
You have to use `export OPENSSL_CONFIG="-config /usr/local/sisis-pap/openssl.cnf"` instead.

This cannot be changed as existing users would be broken otherwise.

**Comment by gurucubano** [comment]
El día viernes, mayo 26, 2023 a las 02:49:14a. m. -0700, Tomáš Mráz escribió:

> You have to use `export OPENSSL_CONFIG="-config /usr/local/sisis-pap/openssl.cnf"` instead.
> 
> This cannot be changed as existing users would be broken otherwise.

Is this stated somewhere in the man page?

	matthias

**Comment by gurucubano** [comment]
Maybe the man page for CA.pl should outline a clear example for this unusual setting of an env var.

**Comment by t8m** [comment]
It is mentioned in the man page in the ENVIRONMENT section.
