### ISSUE TITLE
Error while creating pkey with EVP_PKEY_fromdata() - Cannot set pkey values from params

### ISSUE THREAD

**Issue by OneProgrammerMore** [openssl/openssl#21069]
I am trying to create a pkey using the function EVP_PKEY_fromdata() from openssl but sadly I am having some troubles and getting continuous errors.
```
                   BIGNUM* qOne = BN_new();
                   BIGNUM* nOne = BN_new();
                   /* Init and calculation of all variables... */


                    sizeModulusNOne = BN_num_bits(nOne);

                    if (bldOne == NULL
                      || !OSSL_PARAM_BLD_push_BN(bldOne, "n", nOne)
                      || !OSSL_PARAM_BLD_push_BN(bldOne, "e", eOne)
                      || !OSSL_PARAM_BLD_push_BN(bldOne, "d", dValueOne)
                      || !OSSL_PARAM_BLD_push_BN(bldOne, "rsa-factor1", pBoth)
                      || !OSSL_PARAM_BLD_push_BN(bldOne, "rsa-factor2", qOne)
                      || !OSSL_PARAM_BLD_push_int(bldOne, "bits", sizeModulusNOne)
                      || (paramsOne = OSSL_PARAM_BLD_to_param(bldOne)) == NULL){

                        printf("Error while pushing ossl param bld \n");
                      }else{
                        printf("Correct while pushing ossl param bldOne \n");
                      }
                    ctxOne = EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL);
                    pkeyOne = NULL;

                      if (ctxOne == NULL
                      || paramsOne == NULL
                      || EVP_PKEY_fromdata_init(ctxOne) <= 0
                      || EVP_PKEY_fromdata(ctxOne, &pkeyOne, EVP_PKEY_KEYPAIR, paramsOne) <= 0){
                        printf("ERROR while creating the private key for One \n");
                    }
```

When I call the function EVP_PKEY_fromdata with EVP_PKEY_KEY_PARAMETERS instead of EVP_PKEY_KEYPAIR it does not give any error, nonetheless when I try to read the values as below all of them are zero.
All the other lines seem to work and setting paramsOne does not show any error.

```
                   EVP_PKEY_get_bn_param(pkeyOne, "d",  auxBN);
                  auxBNStr = BN_bn2dec(auxBN);
                  printf("bn D = %s \n", auxBNStr);

                  EVP_PKEY_get_bn_param(pkeyOne, "e",  auxBN);
                  auxBNStr = BN_bn2dec(auxBN);
                  printf("bn E = %s \n", auxBNStr);

                  EVP_PKEY_get_bn_param(pkeyOne, "n",  auxBN);
                  auxBNStr = BN_bn2dec(auxBN);
                  printf("bn N = %s \n", auxBNStr);

```

Any hint why it does not work properly? I have tried almost everything I thought about but nothing seems to work.
My goal is to set a pkey and a ctx in order to decrypt a message using rsa. I have already all the values from the private and public key and the message itself, but it does not seem to work because I cannot create correctly the pkey setting the values.

Any hint will be welcome.

Thanks for your time.

**Comment by t8m** [comment]
You cannot just set the p and q, i.e., the factors. You have to also compute and add all the remaining CRT parameters. Or, alternatively, you can just set n, d, and e as non-CRT RSA key, but signing with that will be of course slower.

**Comment by t8m** [comment]
And yes, importing EVP_PKEY_PARAMETERS is a no-op for RSA keys as they do not really have domain parameters.

**Comment by OneProgrammerMore** [comment]
I do not know if I understood you correctly.
All parameters introduced are already calculated and not NULL or zero. With that I mean that nOne, eOne, dValueOne, pBoth, qOne and sizeModulusNOne are correct BigNums and int. I just did not post the code, where there are computed in order to be more clear. I see it has been the opposite.
Could you please explain me what do you mean by all CRT parameters? I have looked online for CRT meaning but I doubt "Cathode-ray tube" is what are you meaning with it.

My problem resides on the line:
EVP_PKEY_fromdata(ctxOne, &pkeyOne, EVP_PKEY_KEYPAIR, paramsOne) <= 0

I do not why it gives me an error. Furthermore I have just copied the code from the openssl documentation.
Here the link for EVP_PKEY_fromdata function:
https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_fromdata_init.html
And here the link for  OSSL_PARAM_BLD_to_param(bldOne) and pushing to paramsOne struct.
https://www.openssl.org/docs/man3.0/man3/OSSL_PARAM_BLD_push_BN.html

With your last message you mean I cannot get the parameters from the pkey with this function? Could you recommend me a way to read them?

**Comment by levitte** [comment]
When you give *p* and *q*, you also need to give the CRT coefficient. In https://datatracker.ietf.org/doc/html/rfc3447, it's called *qInv*

However, for a minimal RSA keypair, *n*, *e* and *d* are enough. That's why giving only those works.

**Comment by OneProgrammerMore** [comment]
Thank you! Now I understand the answer from t8m... I thought you could add all parameters you would like and it should work as a private key. Did not know it is a MUST to add the CTR if you add "p" and "q". Did not even know about the existence of this parameter. Thank you both for your help!

**Comment by OneProgrammerMore** [comment]
> And yes, importing EVP_PKEY_PARAMETERS is a no-op for RSA keys as they do not really have domain parameters.

Excuse me sir..
Could you please explain me what you mean by "EVP_PKEY_PARAMETERS is a no-op for RSA keys as they do not really have domain parameters.". 
I am trying to get the setted parameter on one EVP PKEY but it is sadly giving me a Segmentation Fault:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7c3c621 in BN_num_bits () from /lib/x86_64-linux-gnu/libcrypto.so.3

`


    int validate_pkey_rsa(EVP_PKEY *pkey)
    {


    const BIGNUM *eRSA = BN_new();
    const BIGNUM *nRSA = BN_new();
    const BIGNUM *dRSA = BN_new();

    const RSA *rsa_key = RSA_new();

    char *eStr, *nStr, *dStr;


    rsa_key = EVP_PKEY_get0_RSA(pkey);

    printf("RSA Key =  %p  \n", rsa_key);

    if (rsa_key == NULL){
        return -3;
    }

    if(rsa_key != NULL){

      /* //Here if I uncomment the code it gives segmentation fault
      eRSA = RSA_get0_e(rsa_key);
      nRSA = RSA_get0_n(rsa_key);
      dRSA = RSA_get0_d(rsa_key);
      */

      eStr = BN_bn2dec(eRSA);
      nStr = BN_bn2dec(nRSA);
      dStr = BN_bn2dec(dRSA);
      /*
      BN_free(eRSA);
      BN_free(nRSA);
      BN_free(dRSA);
      RSA_free(rsa_key);
      */
      printf("n RSA = %s \n", nStr);
      printf("e RSA = %s \n", eStr);
      printf("d RSA = %s \n", dStr);

      return 1;
    }


    if (eRSA != NULL  && nRSA != NULL  && dRSA != NULL   ) {
        //RSA_free(rsa_key);
        BN_free(eRSA);
        BN_free(nRSA);
        BN_free(dRSA);
        return 2;
    }

    BN_free(eRSA);
    BN_free(nRSA);
    BN_free(dRSA);
    //RSA_free(rsa_key);

    return 0;
      }


`



I tried also to do it on the main thread as:



`


                    rsa_key = EVP_PKEY_get0_RSA(pkeyOne);

                    //If I comment the following 3 lines the segmentation code disappears
                    eRSA = RSA_get0_e(rsa_key);
                    nRSA = RSA_get0_n(rsa_key);
                    dRSA = RSA_get0_d(rsa_key);
                    
                    EVP_PKEY_get_bn_param(pkeyOne, "e", &eRSA);
                    EVP_PKEY_get_bn_param(pkeyOne, "n", &nRSA);
                    EVP_PKEY_get_bn_param(pkeyOne, "d", &dRSA);

                    eStr = BN_bn2dec(eRSA);
                    nStr = BN_bn2dec(nRSA);
                    dStr = BN_bn2dec(dRSA);

                    printf("n RSA = %s \n", nStr);
                    printf("e RSA = %s \n", eStr);
                    printf("d RSA = %s \n", dStr);

`


But it also gives me segmentation fault.


Furthermore in the documentation of the function  RSA_get0_d() it says it is deprecated since version 3.0 and quoting:

> All of the functions described on this page are deprecated. Applications should instead use [EVP_PKEY_get_bn_param(3)](https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_get_bn_param.html) for any methods that return a BIGNUM.

That's why I thought I could use this method in order to obtain the RSA parameters.

Link: https://www.openssl.org/docs/man3.0/man3/RSA_get0_d.html

**Comment by t8m** [comment]
> Could you please explain me what you mean by "EVP_PKEY_PARAMETERS is a no-op for RSA keys as they do not really have domain parameters.".

I meant that if you use `EVP_PKEY_KEY_PARAMETERS` as the `selection` argument in `EVP_PKEY_fromdata()` it will not fail but it will not create a valid RSA key.

**Comment by t8m** [comment]
If you import the RSA key to an EVP_PKEY correctly, it should be possible to use EVP_PKEY_get0_RSA() and to examine the RSA_KEY n, d, and e values with RSA_get0_n/d/e().

**Comment by nhorman** [comment]
marking as inactive, will close at end of 3.4 dev, barring further input
