### ISSUE TITLE
i'm trying to install Openssl 1.1.1l in 2.04.1-Ubuntu and after "make test" it's showing following error.

### ISSUE THREAD

**Issue by CJRam333** [openssl/openssl#21074]
$ make test

Test Summary Report
-------------------
../test/recipes/80-test_cms.t                    (Wstat: 1280 Tests: 6 Failed: 5)
  Failed tests:  1-5
  Non-zero exit status: 5
../test/recipes/80-test_ssl_new.t                (Wstat: 256 Tests: 29 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=158, Tests=2433, 161 wallclock secs ( 1.20 usr  0.35 sys + 124.94 cusr 25.42 csys = 151.91 CPU)
Result: FAIL
make[1]: *** [Makefile:208: _tests] Error 1
make[1]: Leaving directory '/home/theguy/openssl-1.1.1k'
make: *** [Makefile:205: tests] Error 2

$ make install

make depend && make _build_libs
make[1]: Entering directory '/home/theguy/openssl-1.1.1k'
make[1]: Leaving directory '/home/theguy/openssl-1.1.1k'
make[1]: Entering directory '/home/theguy/openssl-1.1.1k'
make[1]: Nothing to be done for '_build_libs'.
make[1]: Leaving directory '/home/theguy/openssl-1.1.1k'
*** Installing runtime libraries
*** Installing development files
Cannot create directory /usr/include/openssl: No such file or directory
make: *** [Makefile:323: install_dev] Error 2

My system info

Linux cjram-Lenovo-E41-25 5.19.0-42-generic #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by t8m** [comment]
The 1.1.1l has expired certificates in these testcases so it naturally fails the tests. You should use up-to-date version from the 1.1.1 branch.

**Comment by CJRam333** [comment]
> The 1.1.1l has expired certificates in these testcases so it naturally fails the tests. You should use up-to-date version from the 1.1.1 branch.

Thanks

**Comment by CJRam333** [comment]
Do you have any idea how to change from openssl 3.0.4 to openssl 1.1.1, in ubuntu

**Comment by CJRam333** [comment]
> The 1.1.1l has expired certificates in these testcases so it naturally fails the tests. You should use up-to-date version from the 1.1.1 branch.

Do you have any idea how to change from openssl 3.0.4 to openssl 1.1.1, in ubuntu

**Comment by t8m** [comment]
If you're talking about the openssl version provided by the system, I do not think this is reasonably possible.

**Comment by Khnaz35** [comment]
I am getting this on my Centos7 when updating to openssl 1.1.1
```Test Summary Report
-------------------
../test/recipes/80-test_cms.t                    (Wstat: 1280 Tests: 6 Failed: 5)
  Failed tests:  1-5
  Non-zero exit status: 5
../test/recipes/80-test_ssl_new.t                (Wstat: 256 Tests: 29 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=158, Tests=2432, 123 wallclock secs ( 1.02 usr  0.31 sys + 92.55 cusr 36.78 csys = 130.66 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make[1]: Leaving directory `/root/openssl-1.1.1k'
make: *** [tests] Error 2
```
I am following this gist [https://gist.github.com/Bill-tran/5e2ab062a9028bf693c934146249e68c](url)

**Comment by paulidale** [comment]
1.1.1 is out of support.  Suggest you take this up with the gist provider.
