### ISSUE TITLE
Error with EVP_PKEY_decrypt RSA - Unable to decrypt (because of padding?) - Working with RSA_private_decrypt

### ISSUE THREAD

**Issue by OneProgrammerMore** [openssl/openssl#21073]
Hi!
I am trying to decrypt a RSA encrypted message using the function EVP_PKEY_decrypt().

I am able to decrypt it using the function RSA_private_decrypt(), nonetheless with the same parameters it does not work with the function EVP_PKey_Decrypt.

The code is:
`

                   unsigned char toOne[2048];
                  unsigned char toTwo[2048];

                  RSA_private_decrypt(sizeLengthOneBin, bufferOneBin, toOne, rsaOne, RSA_PKCS1_PADDING);
                  printf("to = %s \n", toOne);

                  printf("BufferOneBin %s \n", bufferOneBin);

                  RSA_private_decrypt(sizeLengthTwoBin, bufferTwoBin, toTwo, rsaTwo, RSA_PKCS1_PADDING);
                  printf("to = %s \n", toTwo);

                  printf("BufferTwoBin %s \n", bufferTwoBin);

                  EVP_PKEY_CTX *ctxOneM = EVP_PKEY_CTX_new(pkeyOne,NULL);
                  if (ctxOneM) {
                     if (EVP_PKEY_decrypt_init(ctxOneM) > 0) {

                         if (EVP_PKEY_CTX_set_rsa_padding(ctxOneM, RSA_PKCS1_PADDING) > 0) {
                             unsigned char toAuxOne[2048];
                             size_t tlen;
                             if (EVP_PKEY_decrypt(ctxOneM, NULL, &tlen, bufferOneBin, sizeLengthOneBin) > 0) {
                                 int rc;
                                 secretBufferOneBin = OPENSSL_malloc(tlen);
                                 if ((rc = EVP_PKEY_decrypt(ctxOneM, secretBufferOneBin, &tlen, bufferOneBin, sizeLengthOneBin)) <= 0) {
                                     printf("Error decrypting output buffer, rc=%d \n", rc);
                                     ERR_print_errors_fp(stdout);
                                 } else {
                                     printf("Decrypt appeared to work, tlen=%zu \n", tlen);
                                     printf("DEcrypted Message = %s \n", secretBufferOneBin);
                                 }
                             }
                         }else{
                           printf("Padding setting failed for one.");
                         }
                     }else{
                       printf("Init with contextOne not possible.");
                     }
                   }else{
                      printf("ctxOneM Null  = %p",ctxOneM);
                   }

`

The following code works giving me the decrypted message:

`

                  unsigned char toOne[2048];
                  unsigned char toTwo[2048];

                  RSA_private_decrypt(sizeLengthOneBin, bufferOneBin, toOne, rsaOne, RSA_PKCS1_PADDING);
                  printf("to = %s \n", toOne);

                  printf("BufferOneBin %s \n", bufferOneBin);

                  RSA_private_decrypt(sizeLengthTwoBin, bufferTwoBin, toTwo, rsaTwo, RSA_PKCS1_PADDING);
                  printf("to = %s \n", toTwo);

                  printf("BufferTwoBin %s \n", bufferTwoBin);

`

The following code does not work:

`

                  EVP_PKEY_CTX *ctxOneM = EVP_PKEY_CTX_new(pkeyOne,NULL);
                  if (ctxOneM) {
                     if (EVP_PKEY_decrypt_init(ctxOneM) > 0) {

                         if (EVP_PKEY_CTX_set_rsa_padding(ctxOneM, RSA_PKCS1_PADDING) > 0) {
                             unsigned char toAuxOne[2048];
                             size_t tlen;
                             if (EVP_PKEY_decrypt(ctxOneM, NULL, &tlen, bufferOneBin, sizeLengthOneBin) > 0) {
                                 int rc;
                                 secretBufferOneBin = OPENSSL_malloc(tlen);
                                 if ((rc = EVP_PKEY_decrypt(ctxOneM, secretBufferOneBin, &tlen, bufferOneBin, sizeLengthOneBin)) <= 0) {
                                     printf("Error decrypting output buffer, rc=%d \n", rc);
                                     ERR_print_errors_fp(stdout);
                                 } else {
                                     printf("Decrypt appeared to work, tlen=%zu \n", tlen);
                                     printf("DEcrypted Message = %s \n", secretBufferOneBin);
                                 }
                             }
                         }else{
                           printf("Padding setting failed for one.");
                         }
                     }else{
                       printf("Init with contextOne not possible.");
                     }
                   }else{
                      printf("ctxOneM Null  = %p",ctxOneM);
                   }

`

It gives me the following errors:

`
      4087EE05C67F0000:error:0200006C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len:../crypto/rsa/rsa_ossl.c:406:
      4087EE05C67F0000:error:0200009F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error:../crypto/rsa/rsa_pk1.c:269:
       4087EE05C67F0000:error:02000072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:507:
       4087EE05C67F0000:error:0200006C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len:../crypto/rsa/rsa_ossl.c:406:

`
OR

`
     40B7F067027F0000:error:0200006C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len:../crypto/rsa/rsa_ossl.c:406:
     40B7F067027F0000:error:0200006C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len:../crypto/rsa/rsa_ossl.c:406:
`

I have tryed with all paddings in the following link:
https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_CTX_set_rsa_padding.html

> RSA parameters

> EVP_PKEY_CTX_set_rsa_padding() sets the RSA padding mode for ctx. The pad parameter can take the value RSA_PKCS1_PADDING for PKCS#1 padding, RSA_NO_PADDING for no padding, RSA_PKCS1_OAEP_PADDING for OAEP padding (encrypt and decrypt only), RSA_X931_PADDING for X9.31 padding (signature operations only), RSA_PKCS1_PSS_PADDING (sign and verify only) and RSA_PKCS1_WITH_TLS_PADDING for TLS RSA ClientKeyExchange message padding (decryption only).

The padding used in ordert to encrypt the message is the PKCSv1 5, nonetheless it does not seem to work for the second method using EVP_PKEY_decrypt. Setting the padding for the context does not give any error. 

Any idea why it does not work with EVP_PKEY_decrypt()? 

Thank you for your time

EDIT:
I forgot some important part of the code, where I initialize the RSA struct, set the values and initialize the pKeyOne:

This part of the code is of couse before the code above.

`

                    RSA *rsaOne = RSA_new();
                    RSA *rsaTwo = RSA_new();

                    RSA_set0_key(rsaOne, nOne, eOne, dValueOne);
                    RSA_set0_key(rsaTwo, nTwo, eTwo, dValueTwo);

                    eRSA = RSA_get0_e(rsaOne);
                    nRSA = RSA_get0_n(rsaOne);
                    dRSA = RSA_get0_d(rsaOne);

                    eStr = BN_bn2dec(eRSA);
                    nStr = BN_bn2dec(nRSA);
                    dStr = BN_bn2dec(dRSA);

                    printf("n RSA = %s \n", nStr);
                    printf("e RSA = %s \n", eStr);
                    printf("d RSA = %s \n", dStr);

                    //NOOOO
                    //RSA_free(rsaOne);
                    EVP_PKEY *pkeyOne = EVP_PKEY_new();
                    EVP_PKEY_set1_RSA(pkeyOne, rsaOne);
                    EVP_PKEY *pkeyTwo = EVP_PKEY_new();
                    EVP_PKEY_set1_RSA(pkeyTwo, rsaTwo);

`

**Comment by mattcaswell** [comment]
> 4087EE05C67F0000:error:0200006C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len:../crypto/rsa/rsa_ossl.c:406:
4087EE05C67F0000:error:0200009F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error:../crypto/rsa/rsa_pk1.c:269:
4087EE05C67F0000:error:02000072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:507:
4087EE05C67F0000:error:0200006C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len:../crypto/rsa/rsa_ossl.c:406:

It's slightly suspicious that you get the "data greater than mod len" error twice on the error stack (once at the beginning and once at the end). This might suggest that it has failed with this error twice. You don't actually check the return value of your call to `RSA_private_decrypt()`. Are you sure that it is actually succeeding?

The "data greater than mod len" error means that input length (`sizeLengthOneBin`) is greater than the value that `EVP_PKEY_size()` reports.

So, what is the value of `sizeLengthOneBin` at the point that you pass it to the `EVP_PKEY_decrypt()` function, and what is the value that `EVP_PKEY_size()` reports?

**Comment by nhorman** [comment]
marking as inactive.  will close at the end of 3.4 dev barring further input
