### ISSUE TITLE
make[1]: *** [Makefile:2600: apps/lib/libapps-lib-app_libctx.obj] Error 1

### ISSUE THREAD

**Issue by shelman-zl** [openssl/openssl#21075]
Hello，I compile openssl 3.1.0 under msys2 （mingw32），
configure is：
**_./Configure mingw --prefix=$PWD/../../install/x86 shared no-asm no-async_**
then, I run make in msys2 shell, occur next error:

**_make depend && make _build_sw
make[1]: Entering directory '/home/ASUS/workspace/packages/openssl-3.1.0'
make[1]: Leaving directory '/home/ASUS/workspace/packages/openssl-3.1.0'
make[1]: Entering directory '/home/ASUS/workspace/packages/openssl-3.1.0'
gcc  -I. -Iinclude -Iapps/include  -m32 -Wall -O3 -fomit-frame-pointer -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/home/ASUS/workspace/packages/openssl-3.1.0/../../install/x86/ssl\"" -DENGINESDIR="\"/home/ASUS/workspace/packages/openssl-3.1.0/../../install/x86/lib/engines-3\"" -DMODULESDIR="\"/home/ASUS/workspace/packages/openssl-3.1.0/../../install/x86/lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG   -c -o apps/lib/libapps-lib-app_libctx.obj apps/lib/app_libctx.c
make[1]: *** [Makefile:2591: apps/lib/libapps-lib-app_libctx.obj] Error 1
make[1]: Leaving directory '/home/ASUS/workspace/packages/openssl-3.1.0'
make: *** [Makefile:1542: build_sw] Error 2_**

please help me to fix this problem, thank you.

**Comment by nhorman** [comment]
marking as inactive. will close at the end of 3.4 dev barring further input
