### ISSUE TITLE
Is it OK that RAND_bytes in openssl-3.x does not use additional data

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#21071]
While 1.1.1 at least attempts to add some entropy in every RAND_bytes call,
openssl-3.x does not do that at all, and passes no additional data whatsoever.
Whenever a call to EVP_RAND_generate is done it looks like
`EVP_RAND_generate(rand, buf, num, strength, 0, NULL, 0);` except in some KAT tests.

**Comment by bernd-edlinger** [comment]
BTW: This was changed in #11682 but I do not see this any mention of why additional data is
no longer used in the PR

**Comment by paulidale** [comment]
Additional input is optional and isn't counted as entropy.  That we're not using it shouldn't impact the quality of the output in the least.

Users can supply additional data via the reseed calls, but again it's not essential.

**Comment by nhorman** [comment]
Given the comments above, this appears asked and answered.  Marking as inactive, will be closed at the end of 3.4 dev

**Comment by t8m** [comment]
I am closing this as the question was answered.
