### ISSUE TITLE
C++ compilation error while trying to include "internal/constant_time.h"

### ISSUE THREAD

**Issue by waseem-sophos** [openssl/openssl#21085]
Openssl version: openssl-3.0.8

When i try to add "internal/constant_time.h" in my c++ application, i get the following errors:

```
openssl/include/internal/constant_time.h:334:14: error: expected unqualified-id before 'xor' token
     uint32_t xor = *a ^ *b;
              ^~~
openssl/include/internal/constant_time.h:336:5: error: expected primary-expression before 'xor' token
     xor &= mask;
     ^~~
```

This is because xor is a reserved keyword in C++ and we cant include this file from any C++ application. I tried to encapsulate it within `extern C` block but still same issue.

**Comment by t8m** [comment]
This is not a bug. This file is internal include that is not supposed to be used from any external application.

**Comment by paulidale** [comment]
Compiling with `-Dxor=foobar` on the command might "fix" this one.
