### ISSUE TITLE
80-test_cmp_http  breaks at 3.0.9 

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#21083]
80-test_cmp is failing on NonStop. This test previously (at 3.0.8) did not fail. I am checking 1.1.1u and 3.1.0. The first subtest is failing:
```
80-test_cmp_http.t ................. 
# The results of this test will end up in test-runs/test_cmp_http
1..6
Current directory is /home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/test/recipes/80-test_cmp_http_data/Mock
Launching mock server: ../../../../util/wrap.pl ../../../../apps/openssl cmp -config server.cnf
Pid is: 318767136
Server output: cmp_main:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2832:CMP info: using section(s) 'cmp' of OpenSSL configuration file 'server.cnf'
Server output: ACCEPT [::]:61687 PID=1224736923
# Subtest: CMP app CLI Mock connection
    1..37
# cmp_main:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2832:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2316:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2009:CMP info: will contact http://127.0.0.1:61687/pkix/
# CMP info: sending IR
# CMP error: connect timeout
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:61687' -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 => 255
    not ok 1 - default config

    #   Failed test 'default config'
    #   at test/recipes/80-test_cmp_http.t line 136.
    #          got: '0'
    #     expected: '1'
```
The configuration is:
```

Command line (with current working directory = .):

    perl ./Configure nonstop-nsx_64 --prefix=/usr/local-ssl3.0 --openssldir=/usr/local-ssl3.0/ssl --with-rand-seed=rdcpu enable-fips no-egd

Perl information:

    perl
    5.30.3 for NSV-D-nonstop_kernel

Enabled features:

    acvp-tests
    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    fips
    fips-securitychecks
    gost
    idea
    legacy
    loadereng
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    asm                 [no asm_arch]    OPENSSL_NO_ASM
    buildtest-c++       [default]
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [option]         OPENSSL_NO_EGD
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [default]        OPENSSL_NO_KTLS
    makedepend          [unavailable]
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]        OPENSSL_NO_SCTP
    threads             [config]
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]
    zlib-dynamic        [default]
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "qc",
    CC => "c99",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    bn_ops => "SIXTY_FOUR_BIT",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-g -O2 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_neutral_library -Wverbose -Wtarget=tns/x -Wsystype=oss -Wlp64 -WIEEE_float",
    cppflags => "",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "OPENSSL_VPROC=\$(OPENSSL_VPROC)", "_XOPEN_SOURCE", "_XOPEN_SOURCE_EXTENDED=1", "_TANDEM_SOURCE", "B_ENDIAN", "_TANDEM_ARCH=3" ],
    disable => [ "threads" ],
    dso_scheme => "DLFCN",
    enable => [ "egd" ],
    ex_libs => "-lrld",
    includes => [  ],
    lflags => "-Wxld=\"-set systype oss\" -Wxld=\"-set data_model lp64\" -Wxld=\"-set floattype ieee_float\"",
    lib_cflags => "",
    lib_cppflags => "",
    lib_defines => [  ],
    module_cflags => "",
    module_cxxflags => undef,
    module_ldflags => "-Wshared",
    multilib => "64",
    perl => "/usr/bin/perl",
    perl_platform => "Unix",
    shared_argfileflag => "-Wxld_obey=",
    shared_cflag => "",
    shared_defflag => "-Wxld_obey=",
    shared_defines => [  ],
    shared_extension => ".so",
    shared_ldflag => "-Wshared",
    shared_rcflag => "",
    shared_target => "nonstop-shared",
    sys_id => "TANDEM",
    thread_defines => [  ],
    thread_scheme => "(unknown)",
    unistd => "<unistd.h>",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = ar
    ARFLAGS         = qc
    CC              = c99
    CFLAGS          =
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          =
    PERL            = perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
```

**Comment by rsbeckerca** [comment]
This does not appear to be a issue at 3.1.1 on the same build machine (HPE NonStop x86)

**Comment by rsbeckerca** [comment]
I reran the test a few times directly from a shell and it passed. The diagnostics are slightly different, which hints that running tests in Jenkins might be slightly different from a pipes standpoint. I am going to rerun the build/test again when 3.1.1 and 1.1.1u all finish.
```
80-test_cmp_http.t ..
# The results of this test will end up in test-runs/test_cmp_http
1..6
Current directory is /home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/test/recipes/80-test_cmp_http_data/Mock
Launching mock server: ../../../../util/wrap.pl ../../../../apps/openssl cmp -config server.cnf
Pid is: 2013265946
Server output: cmp_main:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2832:CMP info: using section(s) 'cmp' of OpenSSL configuration file 'server.cnf'
Server output: ACCEPT [::]:61228 PID=1342177520
# Subtest: CMP app CLI Mock connection
    1..37
cmp: Received request, 1st line: POST /pkix/ HTTP/1.0
CMP DEBUG: received IR
CMP DEBUG: validating CMP message
CMP DEBUG: trying to build chain for own CMP signer cert
CMP DEBUG: success building chain for own CMP signer cert
CMP DEBUG: sending IP
cmp: Received request, 1st line: POST /pkix/ HTTP/1.0
CMP DEBUG: received CERTCONF
CMP DEBUG: validating CMP message
CMP DEBUG: sending PKICONF
# cmp_main:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2832:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2316:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2009:CMP info: will contact http://127.0.0.1:61228/pkix/
# CMP info: sending IR
# CMP info: received IP
# CMP info: sending CERTCONF
# CMP info: received PKICONF
# save_free_certs:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2057:CMP info: received 1 enrolled certificate(s), saving to file '../../../../test-runs/test_cmp_http/test.cert.pem'
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:61228' -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 => 0
    ok 1 - default config
```

**Comment by rsbeckerca** [comment]
Rerunning on our Jenkins build engine a second time passes. This seems to indicate that there is something unstable in the code that depends on either timing or something uninitialized.

**Comment by rsbeckerca** [comment]
@t8m Is there anything I can do to help investigate this, apparently transient issue?

**Comment by t8m** [comment]
Probably rather a question for @DDvO.

**Comment by DDvO** [comment]
The output of the failing test run:
```
Server output: ACCEPT [::]:61687 PID=1224736923
# Subtest: CMP app CLI Mock connection
    1..37
# cmp_main:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2832:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2316:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Pipeline/apps/cmp.c:2009:CMP info: will contact http://127.0.0.1:61687/pkix/
# CMP info: sending IR
# CMP error: connect timeout
```
indicates a TCP/IP connection issue.

This is surely independent of CMP.
Unfortunately we do not have independent tests for connecting any HTTP client 
to the HTTP test server implemented in `apps/lib/http_server.c` via a local port/socket
(but just on BIO level, in `test/http_test.c`).

I have no idea why it works just partially on your system.

No changes have been merged to that server code in the 3.0 branch since commit 2c31d942af28a20e87979cbc76c3dd8d162c1a9c of Apr 2022.
so the issue must be elsewhere, deeper in the socket layer.

It could also be on the HTTP client side, but with, e.g., 
```
git log -p openssl-3.0 crypto/http/
```
I did not notice any recent changes in openssl-3.0 that look relevant.

How is the behavior with the master branch?
There some HTTP server diagnostics improvements have been done recently, see e.g.
```
git log master apps/lib/http_server.c
```

**Comment by rsbeckerca** [comment]
I am having difficulty compiling off `master` because of a dependency added to `poll.h` in `include/internal/sockets.h`, which does not exist on NonStop. I am retrying on `openssl-3.1`.

**Comment by DDvO** [comment]
> @DDvO The one line I think may be contributing is:

> https://github.com/openssl/openssl/blob/168d93a21d512028572777ea5bc96994f2df6c36/crypto/http/http_client.c#L1179
> 
> The ia64 and x86 platforms have a slightly different stack behaviour when it comes to uninitialized stack.

Hmm, commit 849586c7db4740be3c12b320b66c57b2a4527ab9 should just improve memory management and variable initialization,
so I don't think it can cause the regression.

> However, what I noticed here:
> https://github.com/openssl/openssl/blob/168d93a21d512028572777ea5bc96994f2df6c36/crypto/http/http_lib.c#L53-L59
> 
> 
> is that `pport_num` is not being initialized. A `0` return in the first `if block` can result in junk in the `pport_num`. It might be safer to add:
> ```
>     init_pint(pport_num);
> ```
> 
> in that block of code.

Yeah, but on error return of `OSSL_parse_url()`, `*pport_num` should be ignored.
Also all the pointer output parameters should be ignored in this case,
and just for precaution (to prevent memory corruption) they are initialized.

You can try adding
```
     init_pint(pport_num);
```
but I'm sure it will not help in your case, where the port numbers of client and server do match even on the failure reported above (with the value being 61687).

**Comment by rsbeckerca** [comment]
@DDvO Running a full test with the above change. Will set up a PR if it works.

**Comment by DDvO** [comment]
>  Running a full test with the above change. Will set up a PR if it works.

For a test where just part of the apps or libcrypto code changed,
the following is sufficient and more efficient than running `make test`:
```
make -s -j4 apps/openssl libcrypto.so.3 && \
  make run_tests TESTS=test_cmp_http OPENSSL_CMP_ASPECTS=connection
```

**Comment by DDvO** [comment]
Since it is very hard for others to reproduce the issue,
so far the only two ways to find the reason that I am aware of are:
* add `puts()` at interesting places in the HTTP client and server code to see where the connect/accept mismatches or hangs
* bisect the commits between `openssl-3.0.8` and  `openssl-3.0.9` that are related to the HTTP client and server and the underlying socks support, which likely would be tedious

**Comment by rsbeckerca** [comment]
> Since it is very hard for others to reproduce the issue, so far the only two ways to find the reason that I am aware of are:
> 
>     * add `puts()` at interesting places in the HTTP client and server code to see where the connect/accept mismatches or hangs
> 
>     * bisect the commits between `openssl-3.0.8` and  `openssl-3.0.9` that are related to the HTTP client and server and the underlying socks support, which likely would be tedious

The failure was fast, under 1 second, well short of a reasonable timeout. The bisect is unlikely to work because running outside of our main build (Jenkins) has never failed. I think the best course is just to make the code a little safer.

**Comment by DDvO** [comment]
> The failure was fast, under 1 second, well short of a reasonable timeout.

Interesting - then the reason cannot just be a mismatch of port numbers and interfaces expected/provided by the client/server side.
And the `error: connect timeout` must be misleading here because the client-side connect timeout is 5 seconds here.

> I think the best course is just to make the code a little safer.

Did adding `init_pint(pport_num);` help?

**Comment by rsbeckerca** [comment]
> > The failure was fast, under 1 second, well short of a reasonable timeout.
> 
> Interesting - then the reason cannot just be a mismatch of port numbers and interfaces expected/provided by the client/server side. And the `error: connect timeout` must be misleading here because the client-side connect timeout is 5 seconds here.
> 
> > I think the best course is just to make the code a little safer.
> 
> Sure, but so far I have no idea where something less safe than in 3.0.8 could have crept in.

This is why I am suspecting something transient on the stack. When running in Jenkins on the x86 system, stack memory tends to have a lot more junk. The ia64 system is much more idle and the test stack often finds itself in previously unused memory, so 0 initializations are far more likely on the stack.

**Comment by DDvO** [comment]
> > Sure, but so far I have no idea where something less safe than in 3.0.8 could have crept in.
> 
> This is why I am suspecting something transient on the stack. When running in Jenkins on the x86 system, stack memory tends to have a lot more junk. The ia64 system is much more idle and the test stack often finds itself in previously unused memory, so 0 initializations are far more likely on the stack.

I see. Yet this explanation requires that something on the stack has become *less* initialized at some point between 3.0.8 and 3.0.9, and I'm not aware of any such thing within the HTTP client and server code.

**Comment by rsbeckerca** [comment]
> > > Sure, but so far I have no idea where something less safe than in 3.0.8 could have crept in.
> > 
> > 
> > This is why I am suspecting something transient on the stack. When running in Jenkins on the x86 system, stack memory tends to have a lot more junk. The ia64 system is much more idle and the test stack often finds itself in previously unused memory, so 0 initializations are far more likely on the stack.
> 
> I see. Yet this explanation requires that something on the stack has become _less_ initialized at some point between 3.0.8 and 3.0.9, and I'm not aware of any such thing within the HTTP client and server code.

On this platform, the stack contents can come from a prior process that made use of the same part of virtual memory if there is no explicit initialization of the stack variable. This is not the case with global memory which always initializes to 0 (c99 spec). The transient nature of this problem hints at something systemic - I have seen this in other projects.

**Comment by rsbeckerca** [comment]
Unit test passes. I am running a full regression just in case. This change can be applied to master, 3.1, and 3.0.

**Comment by rsbeckerca** [comment]
We are now getting failures of this test on a more regular basis. Is there anything I can do to try to get more info? This does not happen when the test is run on its own. Only when run during a full test cycle, which is weird, and may be a statistical anomaly.
```
80-test_cmp_http.t ................. 
# The results of this test will end up in test-runs/test_cmp_http
1..6
Current directory is /home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Monitor/test/recipes/80-test_cmp_http_data/Mock
Launching mock server: ../../../../util/wrap.pl ../../../../apps/openssl cmp -config server.cnf
Pid is: 1845493884
Server output: cmp_main:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Monitor/apps/cmp.c:2833:CMP info: using section(s) 'cmp' of OpenSSL configuration file 'server.cnf'
Server output: ACCEPT [::]:61153 PID=1811939568
# Subtest: CMP app CLI Mock connection
    1..37
# cmp_main:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Monitor/apps/cmp.c:2833:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Monitor/apps/cmp.c:2317:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:/home/ituglib/randall/jenkins/.jenkins/workspace/OpenSSL-3.0_Monitor/apps/cmp.c:2009:CMP info: will contact http://127.0.0.1:61153/pkix/
# CMP info: sending IR
# CMP error: connect timeout
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:61153' -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 => 255
    not ok 1 - default config
```
