### ISSUE TITLE
PR 20305 (Aarch64  feature detection) not available in latest openssl v3.0.9 or v3.1.1

### ISSUE THREAD

**Issue by skynet1381** [openssl/openssl#21094]
Hi,

Below issue is affecting us on Apple M1/M2 debugging. 
https://github.com/openssl/openssl/issues/20753

Thanks for the fix which was merged with below PR to 'master' branch.
https://github.com/openssl/openssl/pull/20305

The question is about I see branch 3.1 was added as label to the issue but I couldn't find the fix in latest openssl v3.1.1 release or v3.0.9.
Was this oversight? could this be marked for merging to branch 3.1?

**Comment by t8m** [comment]
OTC decided that the PR #20305 is not eligible for backporting to branch 3.1.

**Comment by skwijeratne** [comment]
@t8m When can we expect this to be fixed on a openSSL 3.1 version?

**Comment by skwijeratne** [comment]
@t8m any more explanation on the decision by OTC?

**Comment by tom-cosgrove-arm** [comment]
Please see [this comment](https://github.com/openssl/openssl/issues/21541#issuecomment-1658204573) in #21541, and PR #21583 for 3.1

**Comment by skwijeratne** [comment]
@tom-cosgrove-arm thank you! 🙏

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
