### ISSUE TITLE
Creating Openssl 3.0  fips.dll renamed to some other custom name . ex- custom_fips.dll

### ISSUE THREAD

**Issue by aniljadaun** [openssl/openssl#21092]
I am creating static libs for libcrypto.lib and libssl.lib and dll for fips module as fips.dll . I am experimneting on how to create fips.dll with custom name. I am kind of stuck at this step.
Steps done by  me :
1. cloned openssl repo .
2. perl Configure VC-WIN64A enable-fips enable-capieng --prefix=D:\outlibsopenssl\Modifiedopenssllibs\release  --openssldir=D:\outlibsopenssl\Modifiedopenssllibs\openssldir no-shared  
3. nmake
4. nmake test
5. nmake install
Doing 5th step generates openssl libs and  fips.dll . We are experimenting on creating fips.dll with custom name.

Is loading of fips.dll controlled via openssl.cnf file ? Loadlibrary for fips.dll is called from libcrypto.lib ?

**Comment by paulidale** [comment]
I think this would work.

fips.dll can either be loaded from openssl.cnf or via a library call.  The choice is up to you.
In both cases, some configuration is necessary to ensure the power up self tests execute properly.
The [documentation](https://www.openssl.org/docs/man3.0/man7/fips_module.html) covers this.

**Comment by aniljadaun** [comment]
Hi @paulidale 

Thanks for your response.   please bear with me if question is too basic. I have some doubt regarding this .

So just simply renaming the generated fips dll. let's say fips.dll as fips_test.dll and then using the same code as in ex:

 OSSL_PROVIDER_set_default_search_path(NULL, "path to dll");
 if (!OSSL_LIB_CTX_load_config(NULL, "path to openssl.cnf")) {
	   cout<<("err OSSL_LIB_CTX_load_config\n ");
	}
 fips = OSSL_PROVIDER_load(NULL, "fips");
//Or do we need to load dll using windows 
LoadLibrary("path to dll with dll name");

"some configuration is necessary to ensure the power up self tests execute properly"-->
What configuration are you talking about in the above line ?

I didn't get much referenace about the renaming dll part from the above documenation shared. Can you point me to the exact part which talks about this.

**Comment by levitte** [comment]
``` C
fips = OSSL_PROVIDER_load(NULL, "fips");
```

The string that you pass is condsidered the module file name (without extension), so it directly translates to "fips.dll" in this case.  If you want to rename the DLL to "fips_test.dll", then you must also change this loading call to:

``` C
fips = OSSL_PROVIDER_load(NULL, "fips_test");
```

-----

``` C
//Or do we need to load dll using windows
LoadLibrary("path to dll with dll name");
```

If you do that, that you must treat it as a built-in provider.  More or less this (I haven't tested):

``` C
module = LoadLibrary("fips_test.dll");
symbol = GetProcAddress(module, "OSSL_provider_init");
OSSL_PROVIDER_add_builtin(NULL, "fips_test", symbol);
OSSL_PROVIDER_load("fips_test");
```

As you can see, it would be rather pointless :wink:

**Comment by levitte** [comment]
All the above being said, if you specify it in a configuration file, with the correct DLL name, then you don't have to `OSSL_PROVIDER_load(NULL, "fips_test");`, as this should be done for you.

**Comment by levitte** [comment]
The [documentation](https://www.openssl.org/docs/man3.0/man7/fips_module.html) doesn't talk about renaming the FIPS module, 'cause that's not something we encourage.  However, the more generic [configuration documentation](https://www.openssl.org/docs/man3.0/man5/config.html#Provider-Configuration) does show you how you can specify the module name explicitly.  You would have to add this line in `[fips_sect]`:

```
identity = fips_test
```

That section is in the fipsmodule.cnf

**Comment by aniljadaun** [comment]
Hi @levitte 

Thank you for your response. It seems to answer all my questions. However, only one of the two ways suggested by you worked for me. I am not able to load fips_test.dll without changing the conf file. Mentioning the identity of the fips module in the conf file worked. However, if I do not do that and instead use the following call:
fips = OSSL_PROVIDER_load(NULL, "fips_test");

fips_test.dll is loaded and unloaded. The following error is logged:

98630000:error:1C8000D5:Provider routines:SELF_TEST_post:missing config data:providers\fips\self_test.c:354:
98630000:error:1C8000E0:Provider routines:ossl_set_error_state:fips module entering error state:providers\fips\self_test.c:464:
98630000:error:1C8000D8:Provider routines:OSSL_provider_init_int:self test post failure:providers\fips\fipsprov.c:751:
98630000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:934:name=fips_test

This seems to be error of the hash mismatch which should not be the case because using identity = fips_test in cnf file works without any error for same dll.

Below is openssl.cnf and fipsmodule.cnf in non working case :

openssl.cnf
-----------------
config_diagnostics = 1
openssl_conf = openssl_init

.include "D:\\outlibsopenssl\\SSL\\fipsmodule.cnf"
[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1

fipsmodule.cnf
-------------------------
[fips_sect]
activate = 0
install-version = 1
conditional-errors = 1
security-checks = 1
tls1-prf-ems-check = 0
module-mac = F7:17:C3:6B:1C:1A:A8:DF:32:6A:0F:5D:35:52:98:BA:40:8E:3F:F0:85:F5:75:64:26:27:D4:8A:28:7D:F5:52

**Comment by aniljadaun** [comment]
please suggest

**Comment by aniljadaun** [comment]
Hi @levitte 

Please suggest if i am doing anything wrong here .Refer my previous comment for details.

**Comment by levitte** [comment]
> However, if I do not do that and instead use the following call:
> `fips = OSSL_PROVIDER_load(NULL, "fips_test");`
> 
> fips_test.dll is loaded and unloaded. The following error is logged:

Yeah...  I had to refresh my memory on this.  The issue here is that the fips self test configuration (i.e. the contents of `fips_sect`) are only associated with the loaded FIPS module *if it's loaded via config*.  So the explicit load that you do that's failing is dissociated from the config data, and that's why it fails.

**Comment by aniljadaun** [comment]
any suggestions on how to fix this ?

**Comment by levitte** [comment]
Actually, the `fips_module(7)` manual tells you multiple variants.  In summary, you don't get away from the configuration file, it's simply a *must*.  However, it's still possible to have it work in such a way that you can load programmatically: https://www.openssl.org/docs/man3.0/man7/fips_module.html#Programmatically-loading-the-FIPS-module-default-library-context

**Comment by aniljadaun** [comment]
@levitte I am grateful for your help and prompt responses.
I am ok with using configuration file, but i just wanted to be sure about adding identity in fips_sect for new named fips module is must or their other ways to do it as well ? I think the link you shared talks about default activating fips module from cnf file or programmatically . it doesn't have much info about loading name changed fips_module programmatically.

**Comment by t8m** [comment]
You can add
```
[fips_sect]
identity = fips_test
```

To the main openssl.cnf file and it should work IMO.

**Comment by t8m** [comment]
> ... and `activate = 0` if you want to load it programmatically.

Unfortunately I do not believe that will work. See provider_conf_load() - mere presence of `activate` value enables activation of the provider.

**Comment by aniljadaun** [comment]
Dear @t8m and @levitte,

I wanted to thank you both for your suggestions. Your responses have been very helpful.

As @t8m mentioned, setting activate=0 did not help. However, removing the activate parameter altogether does delay the loading of the DLL until the OSSL_PROVIDER_load(NULL, "fips_test"); call is made.

We can now close this issue. Thank you both again for your help and guidance.
