### ISSUE TITLE
Change openssl version in centos 7 - yum list

### ISSUE THREAD

**Issue by jasondee1992** [openssl/openssl#21101]
Good day,

Centos7
I installed openssl 3.0.7  version. 

But when I installed it didn't change the version on "yum list" Is it possible to change it because when I'm installing the "pyenv install 3.11.0" I got this error.

Traceback (most recent call last): File "", line 1, in File "/home//.pyenv/versions/3.11.0/lib/python3.11/ssl.py", line 100, in import _ssl # if we can't import it, let the error propagate ^^^^^^^^^^^ ModuleNotFoundError: No module named '_ssl' ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem. https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (CentOS Linux 7 using python-build 2.3.18)

Inspect or clean up the working tree at /tmp/python-build.20230601095845.30587 Results logged to /tmp/python-build.20230601095845.30587.log

Last 10 log lines: LD_LIBRARY_PATH=/tmp/python-build.20230601095845.30587/Python-3.11.0 ./python -E -m ensurepip
$ensurepip --root=/ ; \

Here's how I install
sudo yum install perl-IPC-Cmd perl-Test-Simple
cd /usr/src
wget https://www.openssl.org/source/openssl-3.0.7.tar.gz
tar -zxf openssl-3.0.7.tar.gz
rm openssl-3.0.7.tar.gz
cd /usr/src/openssl-3.0.7
./config
make
make test
make install
ln -s /usr/local/lib64/libssl.so.3 /usr/lib64/libssl.so.3
ln -s /usr/local/lib64/libcrypto.so.3 /usr/lib64/libcrypto.so.3
openssl version
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)

but when I type
yum info openssl
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
Release     : 26.el7_9
Size        : 814 k
Repo        : installed
From repo   : updates
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.

It didn't change.

Here's my current openssl after the installation
yum list installed openssl
penssl.x86_64                                                          1:1.0.2k-26.el7_9                                                          @updates

**Comment by t8m** [comment]
We do not provide rpm binary packages nor any other binary packages.

It is also practically impossible to replace the system openssl package (1.0.2) with one that is having completely different API/ABI (3.0).

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
