### ISSUE TITLE
What is the story behind lastUpdate vs thisUpdate in CRLs?

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#21104]
According to [the manual][1]

    X509_CRL_get0_lastUpdate() and X509_CRL_get0_nextUpdate() return the lastUpdate and nextUpdate fields of crl.

However, there is no such field in CRLs according to the [ASN.1 specification][2]. The ASN.1 template calls the thisUpdate field lastUpdate for some reason that is not discernible from the git history (it's been this way since the import of the CVS repo).

This is confusing. What is the history behind this discrepancy and what is it good for? Should the documentation not call out that this is normally called thisUpdate?

I found that BoringSSL documents this in [its x509.h][3].

[1]: https://www.openssl.org/docs/man3.1/man3/X509_CRL_set1_lastUpdate.html
[2]: https://www.rfc-editor.org/rfc/rfc5280#section-5.1
[3]: https://boringssl-review.googlesource.com/c/boringssl/+/53310

**Comment by levitte** [comment]
You may have found something that's lost in history.  I went back to the first commit in our git history, and that name `lastUpdate` is there.

https://github.com/openssl/openssl/commit/d02b48c63a58ea4367a0e905979f140b7d090f86#diff-76ca4bb81ebadf664b3c22ed43b1c2c5418d6ad54a102597f8a4e4888fc30e13

**Comment by botovq** [comment]
I'm sorry, but this does not answer my question. I already stated that it was this way since the beginning of the CVS import.

**Comment by botovq** [comment]
On Thu, Jun 01, 2023 at 08:17:36AM -0700, Tomáš Mráz wrote:
> IMO the answer is that nobody knows, the answer is lost. The only one who might possibly answer here is @t-j-h but I would not expect that he knows either.

This is well possible. Another part of my question is whether this
should be called out in the documentation (which refers to a
non-existent field).

**Comment by t8m** [comment]
Yeah, somehow documenting this and maybe even adding an alias function/macro with the right name would be nice to have.

**Comment by botovq** [comment]
Thank you. I will leave it to you to handle that. I'll also leave this question open for a while since it will have a greater chance to be answered if it is still visible in the issues. Feel free to close it if it gets in the way.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
