### ISSUE TITLE
EVP_PKEY_derive_set_peer  in 3.1 : new vs legacy 

### ISSUE THREAD

**Issue by vitalyk-radware** [openssl/openssl#21128]
We noticed that EVP_PKEY_derive_set_peer  always calls EVP_PKEY_derive_set_peer_ex with validate==1.
The "legacy" flow does  not do anything about "validate" , but non-legacy calls very expensive code that makes a ctx and does "public_check".

we would like to ask:
1) why there is this difference ? why validate is done in the new code, but not in the legacy ?
2) can we make this code more efficient ?  for example, make "validate" optional , or make the public_check  consume less of CPU ?
 ( please see the issue 21106  for details https://github.com/openssl/openssl/issues/21106 )

thanks!

**Comment by mattcaswell** [comment]
Looks like this change was introduced by #14717 and seems to resolve a discrepancy where the DH algorithm did this check, but other algorithms (e.g. EC) did not.

The problem you describe in #21106 is related to libssl calling `EVP_PKEY_derive_set_peer`.

@slontis...should libssl be using this, or should it call `EVP_PKEY_derive_set_peer_ex` with validate == 0??

**Comment by t8m** [comment]
@mattcaswell I believe FIPS mandates the verification. On the other hand maybe the verification is needlessly expensive and there might be some optimizations possible?

**Comment by slontis** [comment]
Probably worth reading SP800-56A (Key Agreement Schemes) which includes requirements for key validation.
(Basically - keys coming from an untrusted source should be validated). Perhaps it could be configurable?
There are probably quite a few places (e.g CMS) where validation could be applied.

**Comment by paulidale** [comment]
libssl would need to know if it's running in a FIPS approved mode and set the validation flag accordingly.
Currently, libssl doesn't know this.

**Comment by slontis** [comment]
It may be a FIPS requirement, but it is really a security issue.

**Comment by vitalyk-radware** [comment]
I would like to understand it better.
It is a check of validity of peer's public key,  right?
What could possibly happen if this key is invalid?  What kind of negative security consequences it may have? 
Thank you.

**Comment by paulidale** [comment]
If the key isn't valid -- literally **anything** goes.

**Comment by richsalz** [comment]
> libssl would need to know if it's running in a FIPS approved mode and set the validation flag accordingly. Currently, libssl doesn't know this.

That seems very easy to fix.  Store a flag "fips_enabled" when parsing the query string and let libssl query that.

It's unfortunate that nobody thought performance, or measured the impact when reviewing #14717, but here's where we are.  I cannot imagine how a bad-key could cause anything other than a crash, and OpenSSL if that happens, that is a bug to fix. Right now you've got a performance bug caused by this only-FIPS-requires it issue.

**Comment by t8m** [comment]
It isn't matter of crash but a false sense of security if the peer provides invalid key.

**Comment by richsalz** [comment]
Please explain the false sense of security.  What is the server's exposure, and how is it different than if the client posts the derived key?

**Comment by nhorman** [comment]
seems like there is no further debate here
marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by t8m** [comment]
The PR #24816 will resolve this issue.

**Comment by t8m** [comment]
As #24816 was merged the performance concerns from this change should mostly disappear (at least in the common TLS case with the NIST prime groups).
