### ISSUE TITLE
Why is http_cb_arg used to determine whether to use tls in the CMP?

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#21120]
OpenSSL version：3.0
In OSSL_CMP_MSG_http_perform(),  use http_cb_arg to determine whether to use TLS. If http_cb is set but http_cb_arg is not set, the selection of the default port and https_proxy will be affected.
Must both http_cb and http_cb_arg be set?

**@crypto/cmp/cmp_http.c 71**
`tls_used = OSSL_CMP_CTX_get_http_cb_arg(ctx) != NULL;`

**Comment by t8m** [comment]
@DDvO might want to chime-in ?

**Comment by t8m** [comment]
Also please see the OSSL_CMP_CTX_set_http_cb_arg() manual page.

**Comment by DDvO** [comment]
Generally, for the HTTP client functions like `OSSL_HTTP_transfer`,
the optional callback function `OSSL_HTTP_bio_cb_t bio_update_fn` and its optional argument `void *arg`
may be any function and argument value needed for manipulating the connection `BIO`.
See the man page of `OSSL_HTTP_bio_cb_t` for details.

The CMP client CLI implementation in `apps/cmp.c` uses this to set up the optional TLS layer of HTTP connection to the CMP server. Here the `http_cb_arg` points to information about the TLS layer such as an `SSL_CTX` pointer.

Good point that this is not sufficiently documented.
Indeed, if for the CMP client implementation the (default) HTTP transfer (implemented in `cmp_http.c`) is used,
the `http_cb_arg` must be non-NULL if and only if TLS is used.
So with the CMP client the HTTP callback mechanism cannot be used for anything else than for HTTPS.
It would have been better to have in the CMP context `OSSL_CMP_CTX` an independent flag
that tells whether TLS is used or not.

**Comment by DDvO** [comment]
@lan1120 would you like, or do you need, to use the CMP HTTP callback mechanism for anything else than attaching TLS to the HTTP transfer?

**Comment by lan1120** [comment]
@DDvO I think the modification of # 21176 makes cmp tls_use clear.

Other:
We have a lot of scenarios where we need to set up our own bio for cmp:
If can set a customized bio for CMP_CTX and pass it to OSSL_HTTP_transfer in the OSSL_CMP_MSG_http_perform function, the usability is much better, because implementing a transfer_cb is expensive, although OSSL_HTTP_transfer is an external interface.

**Comment by DDvO** [comment]
> @DDvO I think the modification of # 21176 makes cmp tls_use clear.

Pleased to hear. 

> Other: We have a lot of scenarios where we need to set up our own bio for cmp: If can set a customized bio for CMP_CTX and pass it to OSSL_HTTP_transfer in the OSSL_CMP_MSG_http_perform function, the usability is much better, because implementing a transfer_cb is expensive, although OSSL_HTTP_transfer is an external interface.

Good point. 
Could you please file this as feature request, 
also providing what you currently use as a workaround.

**Comment by DDvO** [comment]
@lan1120, are you planning to file a FR for this as I suggested?

**Comment by DDvO** [comment]
@lan1120 wrote:

> We have a lot of scenarios where we need to set up our own bio for cmp:
> If can set a customized bio for CMP_CTX and pass it to OSSL_HTTP_transfer in the OSSL_CMP_MSG_http_perform function, the usability is much better, because implementing a transfer_cb is expensive, although OSSL_HTTP_transfer is an external interface.

Again my question: would you like to file a feature request for this?
