### ISSUE TITLE
Provider compatibility across versions CI needs fixes

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#21134]
The provider compatibility CI needs fixes as it currently fails.

https://github.com/openssl/openssl/actions/workflows/provider-compatibility.yml

It should be also run on-push for future failures to be more visible.

**Comment by paulidale** [comment]
My question is why aren't there any notifications of daily test failures?
We've been hit by their absence before and will be again...

**Comment by paulidale** [comment]
An email sent on build failure would be ideal.

No notification on failure isn't good.

**Comment by t8m** [comment]
Unfortunately the implicit notification from GitHub for scheduled runs go to the person who last touched the .yml file in regards to the schedule: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs
