### ISSUE TITLE
GCM and CCM support in OpenSSL

### ISSUE THREAD

**Issue by Ashok-d-attikatti** [openssl/openssl#21142]
Hello,

I am working on the RISC-V Development board. and we have a Hardware crypto accelerator that supports the AES - (ECB, CBC, GCM, and CCM ).

From the Linux level, we are trying to access the HCA block using the OpenSSL utility. the ECB and CBC are able to access and able to do the encryption and decryption through the devcrypto engine. used the below command to access the HCA.
```
$ ./openssl aes-192-ecb -a -in secrets.txt -out secrets.txt.enc -engine devcrypto -nopad
$ ./openssl aes-192-cbc -a -in secrets.txt -out secrets.txt.enc -engine devcrypto -nopad
```
but we can't able to access the gcm and ccm using the OpenSSL utility. please anyone can suggest the command line interface for GCM and CCM in the OpenSSL utility to encrypt and decrypt.?
Is there any OpenSSL version that supports the GCM and CCM to verify from the command line interface or any application? 

Thanks,
Ashok

**Comment by t8m** [comment]
If you just want to check whether OpenSSL uses the devcrypto engine, you can use the `openssl speed -evp ...` command - it is able to test speed of GCM and CCM mode algorithms.

**Comment by t8m** [comment]
There is no direct support for just doing encryption and decryption with GCM and CCM modes in the openssl command-line utility.

For AES-GCM the `openssl cms` tool can utilize this algorithm for encryption/decryption. CCM is not supported.

**Comment by Ashok-d-attikatti** [comment]
Could you please provide the commands for the AES-GCM with `openssl cms`

**Comment by Ashok-d-attikatti** [comment]
Hi Tomáš 
Any update for the openssl cms command.?

**Comment by t8m** [comment]
Please see the manual page for openssl cms.
https://www.openssl.org/docs/man3.1/man1/openssl-cms.html

**Comment by Ashok-d-attikatti** [comment]
Hi Tomáš,
I went through the manual page for openssl cms.
I could able to verify the GCM support from the software. but I want to use the Hardware devcrypto engine.

Please let me know, how I can parse the **-engine devcrypto**  to verify GCM.

Thanks,

**Comment by beldmit** [comment]
One possible option is loading the engine via the config file.

**Comment by Ashok-d-attikatti** [comment]
Could you please suggest more info, on how to load or the procedure for configuring the engine via config file.?

**Comment by beldmit** [comment]
https://www.openssl.org/docs/man1.1.1/man5/config.html contains the general engine documentation
you can either change the system-wide config file or copy it and specify the path to the config via the OPENSSL_CONF environment variable.

I have no idea whether you can check that the devcrypto is really in use, BTW

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
