### ISSUE TITLE
RSA_set_method & EVP_PKEY_set1_RSA was deprecated since OpenSSL 3.0, how can I set the RSA (along with the rsa_meth_st define) to the EVK_PKEY publicKey instance

### ISSUE THREAD

**Issue by totti0858** [openssl/openssl#21144]
Originally we use the RSA_set_method as what libp11 done by below key steps:

RSA_METHOD *PKCS11_get_rsa_method(void)
{
	static RSA_METHOD *ops = NULL;

	if (!ops) {
		alloc_rsa_ex_index();
		ops = RSA_meth_dup(RSA_get_default_method());
		if (!ops)
			return NULL;
		RSA_meth_set1_name(ops, "libp11 RSA method");
		RSA_meth_set_flags(ops, 0);
		RSA_meth_set_priv_enc(ops, pkcs11_rsa_priv_enc_method);
		RSA_meth_set_finish(ops, pkcs11_rsa_free_method);
	}
	return ops;
}

RSA *rsa;
EVP_PKEY *tmpKey;
EVP_PKEY *pk;

tmpKey = X509_get_pubkey(x509Cert);
rsa = EVP_PKEY_get1_RSA(tmpKey);
RSA_set_method(rsa, PKCS11_get_rsa_method());
EVP_PKEY_set1_RSA(publicKey, rsaKey);

(sample code in https://github.com/OpenSC/libp11/blob/master/src/p11_rsa.c#L272-L278)

But these method like RSA_set_method, EVP_PKEY_set1_RSA & EVP_PKEY_get1_RSA are deprecated since OpenSSL 3.0. If I still want to use this mechanism to set my customized function pkcs11_rsa_priv_enc_method, how can I do it without using these deprecated methods.

I know these methods are deprecated but not dropped, people sometimes still can use it under OpenSSL 3.0. But we are not sure when these methods will be dropped totally. So I'd like to find another mechanism to do the similar thing. Any suggestion about it?

**Comment by t8m** [comment]
The provider API is the interface for adding or replacing algorithm implementations used by OpenSSL. The deprecated methods will be dropped by 4.0 release at the earliest. There is no schedule for that release yet.

**Comment by t8m** [comment]
See also:

https://www.openssl.org/docs/man3.1/man7/migration_guide.html
https://www.openssl.org/docs/man3.1/man7/provider.html

**Comment by totti0858** [comment]
could you please provide some sample project on how to use provider API?

**Comment by totti0858** [comment]
from the migration guide, we can see the words "All these methods such as RSA_new_method() and RSA_meth_new() are now deprecated and can be replaced by using providers instead."

We know that OpenSSL has provided different providers like default, base or legacy providers,  what about the "provide" means here? or it means a customized provider by our self?

**Comment by t8m** [comment]
> or it means a customized provider by our self?

Yes, exactly that.

**Comment by totti0858** [comment]
I want to create a builtin provider but seldom find the sample of init the provider by using the method "OSSL_provider_init" in main app.

Is the right method "OSSL_provider_init" to load a builtin provider or some method else like "OSSL_PROVIDER_load" to load a simple builtin library? 

By the way how to determine the provider name of one bubiltin provider?

**Comment by mattcaswell** [comment]
Use `OSSL_PROVIDER_add_builtin()` to add a new built-in provider:

https://www.openssl.org/docs/man3.0/man3/OSSL_PROVIDER_add_builtin.html

That function enable you to give the provider a name, and a pointer to it's initialisation function (which could be called `OSSL_provider_init` or anything else).

Once added you need to load the provider via `OSSL_PROVIDER_load()`.

**Comment by totti0858** [comment]
In another words, how to replace the below mechanism of specify the function handler in “**RSA_meth_set_priv_enc**” and "**RSA_meth_set_sign**" methods?
> 	RSA_meth_set_priv_enc(ops, pkcs11_rsa_priv_enc_method);
>      RSA_meth_set_sign(ops, pkcs11_rsa_sign_method);
As we all know it should be replace by Provider, but how to implement the sample Provider? Do we need the reimplement the Provider-signature (https://www.openssl.org/docs/man3.0/man7/provider-signature.html) or Provider-encoder (https://www.openssl.org/docs/man3.0/man7/provider-encoder.html)?

**Comment by t8m** [comment]
You will need to implement the provider signature and provider key management interfaces at least. For the key management it should be sufficient to implement the basic key life time management, key import functions and the has and match functions.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
