### ISSUE TITLE
memory leak in CRYPTO_set_ex_data

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#2115]
Under low memory a memory leak was observed with openssl-1.0.2j:

Reason is a bit unclear, probably it is possible that in def_get_class
an unnoticed error happens on lh_EX_CLASS_ITEM_insert, which
makes int_new_ex_data succeed, but int_free_ex_data fails,
and does not even remove the sk object.

The following patch makes the memory leak go away.
The first hunk may be unnecessary.

```
Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f6ba50fa310 in __interceptor_malloc ../../../../gcc-7-20161211/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x2153e5a in CRYPTO_malloc crypto/mem.c:346
    #2 0x21ac96c in sk_new crypto/stack/stack.c:162
    #3 0x21ac96c in sk_new_null crypto/stack/stack.c:154
    #4 0x215920c in CRYPTO_set_ex_data crypto/ex_data.c:614
    #5 0x236b017 in ssl_verify_cert_chain ssl/ssl_cert.c:734
    #6 0x239dd44 in ssl3_get_server_certificate ssl/s3_clnt.c:1255
    #7 0x23aacc8 in ssl3_connect ssl/s3_clnt.c:345
    #8 0x233e3ae in ssl23_get_server_hello ssl/s23_clnt.c:799
    #9 0x233e3ae in ssl23_connect ssl/s23_clnt.c:228
    #10 0x233f744 in ssl23_write ssl/s23_lib.c:173

--- crypto/ex_data.c.orig       2016-09-26 11:49:07.000000000 +0200
+++ crypto/ex_data.c    2016-12-17 19:02:12.862512254 +0100
@@ -501,9 +501,9 @@ static void int_free_ex_data(int class_i
     void *ptr;
     CRYPTO_EX_DATA_FUNCS **storage = NULL;
     if (ex_data == NULL)
-        return;
+        goto err;
     if ((item = def_get_class(class_index)) == NULL)
-        return;
+        goto err;
     CRYPTO_r_lock(CRYPTO_LOCK_EX_DATA);
     mx = sk_CRYPTO_EX_DATA_FUNCS_num(item->meth);
     if (mx > 0) {
@@ -517,7 +517,7 @@ static void int_free_ex_data(int class_i
     CRYPTO_r_unlock(CRYPTO_LOCK_EX_DATA);
     if ((mx > 0) && !storage) {
         CRYPTOerr(CRYPTO_F_INT_FREE_EX_DATA, ERR_R_MALLOC_FAILURE);
-        return;
+        goto err;
     }
     for (i = 0; i < mx; i++) {
         if (storage[i] && storage[i]->free_func) {
@@ -528,6 +528,7 @@ static void int_free_ex_data(int class_i
     }
     if (storage)
         OPENSSL_free(storage);
+ err:
     if (ad->sk) {
         sk_void_free(ad->sk);
         ad->sk = NULL;

```

**Comment by richsalz** [comment]
@bernd-edlinger  at this point you've opened more than 20 issues/bugfixes.  We have gotten past the point of considering these to be trivial  Please sign our CLA.

**Comment by bernd-edlinger** [comment]
yes, I agree, will do that ASAP,
but it will take a while because I need a corporate CLA to be signed by
company, www.softing.com

The good news is that with these changes the openssl survives our
OPC/UA stress test so far, while it crashed immediately before.

**Comment by richsalz** [comment]
That is really good news.  While waiting for the CCLA paperwork, perhaps you could start a pull request that has all your changes? :)

**Comment by bernd-edlinger** [comment]
All patches combined?
Note: I am not sure if #2114 is the right way to fix or if in this case it would be better
to set the SSL object in an error state, also for #2113 might be the wrong place
to handle the error.  What is clear is that there is no crash or memory leak with these
patches at least.
