### ISSUE TITLE
Disallow use of deprecated methods while loading openssl 3.0 binaries using P/Invoke

### ISSUE THREAD

**Issue by casidapulak** [openssl/openssl#21154]
We are using P/Invoke to load openssl 3.0 dlls in our c# application. We do not want to use deprecated methods(like PEM_read_bio_RSAPublicKey) in our code. Is there a way we can make the invoke of those methods fail since the OPENSSL_NO_DEPRECATED flag is relevant only during implicit linking where we include the header files and not during runtime loading of dlls. Thanks in advance

**Comment by t8m** [comment]
Unfortunately no, that is not possible. However you can build OpenSSL with no-deprecated which will completely remove these deprecated methods.

**Comment by preveen-stack** [comment]
@casidapulak can we close this issue, if you are satisfied with the answer
