### ISSUE TITLE
SSL_connect() can result in SSL_ERROR_WANT_READ in QUIC in blocking mode

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#21164]
For TLS the documentation for `SSL_connect()` says this:

````
If the underlying BIO is B<blocking>, SSL_connect() will only return once the
handshake has been finished or an error occurred.
````

If we are using blocking then we never expect `SSL_connect()` to indicate `SSL_ERROR_WANT_READ`. However when we are using a QUIC connection it *does* do this. I would have expected `SSL_connect()` to continue blocking until the handshake is complete like it does with TLS.

Aside: the `SSL_connect` documentation probably needs updating for QUIC since it is no longer the blocking nature of the underlying BIO that matters for QUIC, but whether the SSL object has been set to block or not.

**Comment by hlandau** [comment]
Fix:

```diff
diff --git a/ssl/quic/quic_impl.c b/ssl/quic/quic_impl.c
index d00f4455b0..e9bfaff503 100644
--- a/ssl/quic/quic_impl.c
+++ b/ssl/quic/quic_impl.c
@@ -324,6 +324,7 @@ SSL *ossl_quic_new(SSL_CTX *ctx)
     qc->default_stream_mode     = SSL_DEFAULT_STREAM_MODE_AUTO_BIDI;
     qc->default_ssl_mode        = qc->ssl.ctx->mode;
     qc->default_blocking        = 1;
+    qc->blocking                = 1;
     qc->incoming_stream_policy  = SSL_INCOMING_STREAM_POLICY_AUTO;
     qc->last_error              = SSL_ERROR_NONE;
```
