### ISSUE TITLE
Migration from openssl 1.1.1 to openssl 3.0 cleanup functions

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#21166]
In OpenSSL 1.1.1 we are using following cleanup function on app shutdown.
These are deprecated in openssl 3.0. Are there any alternates to these function or I can directly removed these function from my app code.

> OBJ_cleanup(); EVP_cleanup(); ENGINE_cleanup(); 
> CRYPTO_cleanup_all_ex_data(); ERR_remove_thread_state(NULL); 
> ERR_free_strings();

**Comment by t8m** [comment]
You can just remove them.

**Comment by mattcaswell** [comment]
All of things were actually already deprecated even in 1.1.1 (they were first deprecated in 1.1.0). They are all no-ops and can be safely removed.
