### ISSUE TITLE
ossl_config.json disables all BoringSSL failure case tests

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#2118]
It's probably worth taking a pass over all the disabled tests. You're losing a large chunk of the test suite's coverage right now. A lot of tests hit illegal cases and assert that the TLS stack rejects them (bad signatures, bad Finished, etc.), but our tests usually assert on the shim-side error code, which is different between OpenSSL and BoringSSL. (BoringSSL just prints the name of the reason code while OpenSSL first lowercases and converts _ to space.)

There's a couple of options here. The config file has an `ErrorMap` key that lets you convert error code expectations. You can also try to map them on the shim side when dumping to stderr. Or some combination of the two. There's also a `-loose-errors` flag (probably should be moved to the config file), that just causes us to not check on the error code and only whether or not the shim failed to complete.

Given it's a textual transformation a lot of the time, I'd probably suggest starting with the shim-side mapping to get the reason code's name back.

See https://boringssl.googlesource.com/boringssl/+/master/ssl/test/PORTING.md

**Comment by davidben** [comment]
To quantify things, I see 1186 disabled tests and the test suite itself is 2637 tests, so that's nearly half of them.

**Comment by mattcaswell** [comment]
This was fixed (at least we now run lots more of the errors and implemented the ErrorMap stuff). Closing.
