### ISSUE TITLE
OpenSSL 1.1.1u 30 May 2023 cannot export public key from certificate in ARM

### ISSUE THREAD

**Issue by yubaihe** [openssl/openssl#21196]
The cross compilation method is:
export CXX=arm-linux-gnueabihf-g++
export CC=arm-linux-gnueabihf-gcc
./config no-asm shared --prefix=$(shell pwd)/out
Copy the compiled files to the development board and execute the export command, which is different from the execution results in ubuntu
-----------------------------------------ARM START-----------------------------------------------
openssl x509 -in client.crt  -pubkey -noout -text
-----BEGIN PUBLIC KEY-----
MIIBFjANBgkqhkiG9w0BAQEFAAOCAQMAMIH/AoH5ngAAAACey/+7AAAAAGp3Y+oA
AAAALcslvAAAAADTN4j9AAAAABpu3xcAAAAA5GdBqgAAAABMqVj5AAAAACUgt7oA
AAAAZEQZfgAAAACSG6euAAAAALhD71QAAAAAZk7lYwAAAAAyp0EsAAAAAAk58wEA
AAAAJHA5SQAAAAClTWoFAAAAAIuH7ZMAAAAA67BaagAAAACxdwv4AAAAAFLD6aUA
AAAAdz7ZqgAAAAAkdfYKAAAAAFj85mMAAAAAwi3pogAAAADdFEFqAAAAAKrcbH8A
AAAAgQv5TwAAAABYnSKBAAAAANJckKsAAAAAR1io3AAAAADVzkCrAgEB
-----END PUBLIC KEY-----
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            26:59:a2:3b:23:c7:63:6e:33:6c:24:43:95:aa:58:4f:c7:b7:db:c8
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = CN, ST = JiangSu, L = ChangZhou, O = StarCharge, OU = StarCharge, CN = RootCA
        Validity
            Not Before: May 29 08:11:10 2023 GMT
            Not After : May 26 08:11:10 2033 GMT
        Subject: C = CN, ST = JiangSu, L = ChangZhou, O = StarCharge, OU = StarCharge, CN = CsCA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (1985 bit)
                Modulus:
                    00:9e:00:00:00:00:9e:cb:ff:bb:00:00:00:00:6a:
                    77:63:ea:00:00:00:00:2d:cb:25:bc:00:00:00:00:
                    d3:37:88:fd:00:00:00:00:1a:6e:df:17:00:00:00:
                    00:e4:67:41:aa:00:00:00:00:4c:a9:58:f9:00:00:
                    00:00:25:20:b7:ba:00:00:00:00:64:44:19:7e:00:
                    00:00:00:92:1b:a7:ae:00:00:00:00:b8:43:ef:54:
                    00:00:00:00:66:4e:e5:63:00:00:00:00:32:a7:41:
                    2c:00:00:00:00:09:39:f3:01:00:00:00:00:24:70:
                    39:49:00:00:00:00:a5:4d:6a:05:00:00:00:00:8b:
                    87:ed:93:00:00:00:00:eb:b0:5a:6a:00:00:00:00:
                    b1:77:0b:f8:00:00:00:00:52:c3:e9:a5:00:00:00:
                    00:77:3e:d9:aa:00:00:00:00:24:75:f6:0a:00:00:
                    00:00:58:fc:e6:63:00:00:00:00:c2:2d:e9:a2:00:
                    00:00:00:dd:14:41:6a:00:00:00:00:aa:dc:6c:7f:
                    00:00:00:00:81:0b:f9:4f:00:00:00:00:58:9d:22:
                    81:00:00:00:00:d2:5c:90:ab:00:00:00:00:47:58:
                    a8:dc:00:00:00:00:d5:ce:40:ab
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         ba:23:a3:f7:23:21:94:c2:45:3e:49:6c:fb:a7:c0:fc:59:c8:
         3d:85:71:8b:97:06:e2:12:38:10:16:05:3e:7d:9a:75:97:b7:
         64:98:a8:fc:aa:a9:c4:b4:50:63:9b:66:5c:cc:c8:24:8d:0d:
         e5:a1:a6:af:df:50:0f:67:bf:0e:06:92:6e:03:bf:43:7d:33:
         92:69:34:2a:85:f8:cf:39:ce:65:c2:80:26:a2:11:9c:c6:9c:
         29:08:33:be:e0:6e:12:5a:ce:1d:86:88:3d:3b:f8:c5:c7:d8:
         ad:d5:18:70:c7:8e:86:b4:0e:0d:7f:65:16:fe:6a:55:ee:50:
         e6:b6:cf:44:cf:6c:0e:26:bb:06:9b:cd:b3:f3:37:74:72:48:
         65:80:d9:66:1e:49:9f:64:fb:73:a7:19:72:2c:14:32:6d:d9:
         fc:ae:d3:90:83:d7:6a:53:7b:49:8b:92:16:f1:7f:f8:93:8e:
         00:16:54:78:84:3d:d8:b1:8d:d9:0a:0b:34:07:6d:10:96:56:
         8c:e2:a5:27:ce:27:4f:78:06:a1:18:3b:d6:0d:7e:d0:48:4a:
         94:4c:ed:ce:cf:89:a7:45:d2:f1:38:80:f5:a8:9b:78:07:5b:
         65:4a:0c:48:92:bc:af:91:e8:40:d1:54:9a:f4:72:6b:01:c2:
         f9:43:50:40
-----------------------------------------ARM END-----------------------------------------------
-----------------------------------------UBUNTU START-----------------------------------------
openssl x509 -in client.crt  -pubkey -noout -text
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz7On4JxkP54EWBwUnsv/
u8VBAdxqd2PqsmkcOS3LJbxoY+b80zeI/X89DDgabt8XNmxYL+RnQaq2z7irTKlY
+ai/fS8lILe65s9FWmREGX5PALSJkhunrlr090q4Q+9U9t71imZO5WO6nFsMMqdB
LBmhPFYJOfMBbTbE4SRwOUmb4IOjpU1qBb5YY7aLh+2TYA7q/+uwWmq6pNi/sXcL
+KxatzxSw+mldL4gq3c+2aoLIOgaJHX2CofLUwFY/OZjicts+cIt6aKDROl03RRB
asVEASaq3Gx/GlHQG4EL+U/Au7wJWJ0igS+3kdfSXJCrokdwsEdYqNy4+4Sr1c5A
qwIDAQAB
-----END PUBLIC KEY-----
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            26:59:a2:3b:23:c7:63:6e:33:6c:24:43:95:aa:58:4f:c7:b7:db:c8
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=CN, ST=JiangSu, L=ChangZhou, O=StarCharge, OU=StarCharge, CN=RootCA
        Validity
            Not Before: May 29 08:11:10 2023 GMT
            Not After : May 26 08:11:10 2033 GMT
        Subject: C=CN, ST=JiangSu, L=ChangZhou, O=StarCharge, OU=StarCharge, CN=CsCA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:cf:b3:a7:e0:9c:64:3f:9e:04:58:1c:14:9e:cb:
                    ff:bb:c5:41:01:dc:6a:77:63:ea:b2:69:1c:39:2d:
                    cb:25:bc:68:63:e6:fc:d3:37:88:fd:7f:3d:0c:38:
                    1a:6e:df:17:36:6c:58:2f:e4:67:41:aa:b6:cf:b8:
                    ab:4c:a9:58:f9:a8:bf:7d:2f:25:20:b7:ba:e6:cf:
                    45:5a:64:44:19:7e:4f:00:b4:89:92:1b:a7:ae:5a:
                    f4:f7:4a:b8:43:ef:54:f6:de:f5:8a:66:4e:e5:63:
                    ba:9c:5b:0c:32:a7:41:2c:19:a1:3c:56:09:39:f3:
                    01:6d:36:c4:e1:24:70:39:49:9b:e0:83:a3:a5:4d:
                    6a:05:be:58:63:b6:8b:87:ed:93:60:0e:ea:ff:eb:
                    b0:5a:6a:ba:a4:d8:bf:b1:77:0b:f8:ac:5a:b7:3c:
                    52:c3:e9:a5:74:be:20:ab:77:3e:d9:aa:0b:20:e8:
                    1a:24:75:f6:0a:87:cb:53:01:58:fc:e6:63:89:cb:
                    6c:f9:c2:2d:e9:a2:83:44:e9:74:dd:14:41:6a:c5:
                    44:01:26:aa:dc:6c:7f:1a:51:d0:1b:81:0b:f9:4f:
                    c0:bb:bc:09:58:9d:22:81:2f:b7:91:d7:d2:5c:90:
                    ab:a2:47:70:b0:47:58:a8:dc:b8:fb:84:ab:d5:ce:
                    40:ab
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         ba:23:a3:f7:23:21:94:c2:45:3e:49:6c:fb:a7:c0:fc:59:c8:
         3d:85:71:8b:97:06:e2:12:38:10:16:05:3e:7d:9a:75:97:b7:
         64:98:a8:fc:aa:a9:c4:b4:50:63:9b:66:5c:cc:c8:24:8d:0d:
         e5:a1:a6:af:df:50:0f:67:bf:0e:06:92:6e:03:bf:43:7d:33:
         92:69:34:2a:85:f8:cf:39:ce:65:c2:80:26:a2:11:9c:c6:9c:
         29:08:33:be:e0:6e:12:5a:ce:1d:86:88:3d:3b:f8:c5:c7:d8:
         ad:d5:18:70:c7:8e:86:b4:0e:0d:7f:65:16:fe:6a:55:ee:50:
         e6:b6:cf:44:cf:6c:0e:26:bb:06:9b:cd:b3:f3:37:74:72:48:
         65:80:d9:66:1e:49:9f:64:fb:73:a7:19:72:2c:14:32:6d:d9:
         fc:ae:d3:90:83:d7:6a:53:7b:49:8b:92:16:f1:7f:f8:93:8e:
         00:16:54:78:84:3d:d8:b1:8d:d9:0a:0b:34:07:6d:10:96:56:
         8c:e2:a5:27:ce:27:4f:78:06:a1:18:3b:d6:0d:7e:d0:48:4a:
         94:4c:ed:ce:cf:89:a7:45:d2:f1:38:80:f5:a8:9b:78:07:5b:
         65:4a:0c:48:92:bc:af:91:e8:40:d1:54:9a:f4:72:6b:01:c2:
         f9:43:50:40
-----------------------------------------UBUNTU END-----------------------------------------
What is the reason for this problem? How should I solve it。Thank you

**Comment by t8m** [comment]
You need to manually configure the build for cross-compiled builds. Please see the file INSTALL and especially the part about cross-compilation.

**Comment by yubaihe** [comment]
> You need to manually configure the build for cross-compiled builds. Please see the file INSTALL and especially the part about cross-compilation.

Thank you. Cross compiled OpenSSL can run on the board, but there may be issues when exporting public key certificates. Should I add any configuration items?

**Comment by yubaihe** [comment]
./Configure linux-armv4 solved
