### ISSUE TITLE
OpenSSL 3.0.7 Using 'RSA3072 OAEP SHA256 MGF1_SHA256' Decrypt Error: oaep decoding error

### ISSUE THREAD

**Issue by hxtzzz** [openssl/openssl#21195]
-   I use C library of OpenSSL 3.0.7. The error happens when I do EVP_PKEY_decrypt using 'RSA3072 OAEP SHA256 MGF1_SHA256' and it succeed when I do EVP_PKEY_encrypt. The input data of decrypt is the output of encrypt and the input byte array length is 384, which is the same as RSA3072's module. 
- This is not always a failure, sometimes, it can do the decrypt successfully, and sometimes, it throws the error as 'oaep decoding error'. The probality of failure is about 50%.

**Comment by t8m** [comment]
To be able to help we will need relevant code snippets and example of key and data that it fails with.

**Comment by hxtzzz** [comment]
> To be able to help we will need relevant code snippets and example of key and data that it fails with.

Unfortunately, the key and ciphertext are not available at this time. However, I rebuild the OpenSSL 3.0.7 and found that the error code of decryption is changed when the error code in line 314 in the picture is changed, which means the error is thrown in that line.
The initial error code in that line is RSA_R_OAEP_DECODING_ERROR. I have read the whole function RSA_padding_check_PKCS1_OAEP_mgf1, it seems that if no define FIPS_MODULE, it can throw that error whenever it check succssfully or not.
![image](https://github.com/openssl/openssl/assets/54026189/736aad6e-9601-4982-a02e-121fdf4f9267)

**Comment by t8m** [comment]
> The initial error code in that line is RSA_R_OAEP_DECODING_ERROR. I have read the whole function RSA_padding_check_PKCS1_OAEP_mgf1, it seems that if no define FIPS_MODULE, it can throw that error whenever it checked oaep succssfully or not.

The err_clear_last_contant_time() ensures the error is cleared if there is no error.

**Comment by hxtzzz** [comment]
> > The initial error code in that line is RSA_R_OAEP_DECODING_ERROR. I have read the whole function RSA_padding_check_PKCS1_OAEP_mgf1, it seems that if no define FIPS_MODULE, it can throw that error whenever it checked oaep succssfully or not.
> 
> The err_clear_last_constant_time() call ensures the error is cleared if there is no error.

> Yep, I got that. Does it mean the error happend in this func before line 314 and any kind of error is thrown as RSA_R_OAEP_DECODING_ERROR to avoid chosen ciphertext attacks?

**Comment by t8m** [comment]
Yes

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by t8m** [comment]
The question was answered. Closing
