### ISSUE TITLE
timestamp (ts) verification code needs to be updated to RFC 5816 & 5035

### ISSUE THREAD

**Issue by ldgibbons** [openssl/openssl#2119]
The timestamp (ts) app and crypto are designed to RFCs 3161 & 2634. These RFCs from 2001 and 1999 have been updated by RFCs 5816 & 5035, yet the timestamp code has not kept pace. As a result the current code is unable to verify valid timestamp responses from TSAs which use the newer attributes SigningCertificateV2 and ESSCertIDv2.

**Comment by richsalz** [comment]
Yes.  The TS code is not a priority for the openssl dev team, so if you want it consider making a pull request.

**Comment by FdaSilvaYY** [comment]
See also PR #206

**Comment by richsalz** [comment]
Both PR's merged, closing this issue.
