### ISSUE TITLE
Is the list of permitted operations complete

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#21192]
https://github.com/openssl/openssl/blob/ef2a438d9d94c323b70bf8bd0b4c6ef6542d1a9d/providers/implementations/signature/rsa_sig.c#LL1221C1-L1228C1

Shouldn't VERIFYRECOVER and SIGNCTX/VERIFYCTX also be permitted here?

**Comment by t8m** [comment]
IMO, no. SIGNCTX/VERIFYCTX op cannot be set there at all. And I do not think VERIFYRECOVER is really supported for PSS padding.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input

**Comment by t8m** [comment]
I am closing this as the question was answered.
