### ISSUE TITLE
X509_STORE_CTX_init manual page missing function name

### ISSUE THREAD

**Issue by ereisch** [openssl/openssl#21203]
https://www.openssl.org/docs/man3.1/man3/X509_STORE_CTX_init.html

The text in the section covering {presumably} X509_STORE_CTX_init() does not properly name the function.

Currently:

> It must be called before each call to X509_verify_cert(3) or X509_STORE_CTX_verify(3), i.e., a context is only good for one verification. [...]

Should be:

> X509_STORE_CTX_init() initializes the internal state and resources of the X509_STORE_CTX, and must be called before each call [...]

**Comment by preveen-stack** [comment]
@ereisch I have been working on this and it is my first attempt for a contribution. Let me know if the below meets the expectation,
```
.....
       X509_STORE_CTX_free() completely frees up ctx. After this call ctx is no longer valid.  If
       ctx is NULL nothing is done.

       X509_STORE_CTX_init() initializes the internal state and resources of the X509_STORE_CTX,
       and must be called before each call to X509_verify_cert(3) or X509_STORE_CTX_verify(3),
       i.e., a context is only good for one verification.  If you want ...
....
```

**Comment by mattcaswell** [comment]
Please raise this as a pull request so that it can be properly reviewed.

**Comment by heygauri** [comment]
@mattcaswell can I work on this issue?
Also the above mentioned change by the @ereisch is what needs to be exactly implemented.

**Comment by shahsb** [comment]
I've rolled out the PR - https://github.com/openssl/openssl/pull/23435

@ereisch @t8m - Could you please review it?
