### ISSUE TITLE
int EVP_DigestVerifyFinal(EVP_MD_CTX *ctx, const unsigned char *sig, size_t siglen)

### ISSUE THREAD

**Issue by kvijay1918** [openssl/openssl#21201]
This function returns 1. What are the posibilities of failure here?

**Comment by paulidale** [comment]
Verification failure is probably the most interesting.

It can produce a number of other errors:

https://github.com/openssl/openssl/blob/fbff5b57715471910ea99d28f03ba6a417b45135/crypto/evp/m_sigver.c#L612-L717

This includes whatever the provider decides is an error and this is pretty open ended.

**Comment by kvijay1918** [comment]
Error code : 67625094 Error str : error:0407E086:rsa routines:RSA_verify_PKCS1_PSS_mgf1:last octet invalid

This is the exact error string am getting. What could be wrong from my end?

**Comment by paulidale** [comment]
The error is being raised here:

https://github.com/openssl/openssl/blob/eb4129e12cdf7fe64b3ce352f539e3dbeb1b1321/crypto/rsa/rsa_pss.c#L94-L97

The last byte being passed in isn't 0xBC and it must be.  This is before anything cryptographic happens, so probably bad input data.

**Comment by kvijay1918** [comment]
what should be done with the public key being passed? My public key looks like this,

-----BEGIN RSA PUBLIC KEY-----
MIIBigKCAYEAvefHOp7FtJeC8un5E3ADbD5vRfgbg6q27qYFZur4ZhOJBWLwtyHo
0E7ZBoX1ZoJpIPhJvHXvJ8ws7W/qniGKGNYdLW44NIOlfNQVgK66x8ovaEtZ7xPp
w1M2GAlaxA8nZrBNRBQkPoukwuaiz+NRvfv/jrWSP8awHLb8HmzVkPc72qetrwSU
AMuyICQEBA/sp7laRWf3JbVvAeKzUJ9CxM1eKvD0CI47GBVi4i6BkF12QOTe0gHw
p9GkLgWzzE6lyKIGEiIJu+rTMCpaVOXZsnnXTCK74WLcjuUXd0+TfrLrF+rXlJY0
9NvIhvGHknHV4O7zwmGVYMKEFF4oM9xL4tYOrBHXmv7fWQyFWdLrfUYJAqT+1ERy
e/dsSm7c2g26jbu0NRMC2igEKH89S2ow1w6Ypb3R1IsTbDA3H9KRVp5F9D4gQcDi
N/ArLGdDTo1hBc//gutKQK/0Khv1+OTvHdz+RfR6ybAMcBYEXc9n9x9sTpJYTGUO
RZ7NW4DZobc7AgMBAAE=
-----END RSA PUBLIC KEY-----

**Comment by t8m** [comment]
> The error is being raised here:
> 
> https://github.com/openssl/openssl/blob/eb4129e12cdf7fe64b3ce352f539e3dbeb1b1321/crypto/rsa/rsa_pss.c#L94-L97
> 
> The last byte being passed in isn't 0xBC and it must be. This is before anything cryptographic happens, so probably bad input data.

It's after the signature is decrypted by the public key so probably either the public key is wrong or the signature is corrupted.

**Comment by kvijay1918** [comment]
Great thanks

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
