### ISSUE TITLE
Does flag SSL_OP_ALLOW_CLIENT_RENEGOTIATION  allows unpatched clients to connect to secure server ?

### ISSUE THREAD

**Issue by vk18anubhav** [openssl/openssl#21207]
Hi ,
I am using Openssl 3.0.8. I have a query regarding flag SSL_OP_ALLOW_CLIENT_RENEGOTIATION. 
Does flag SSL_OP_ALLOW_CLIENT_RENEGOTIATION  allows unpatched clients to connect to secure server ?

**Comment by mattcaswell** [comment]
By "unpatched clients" I assume you mean clients that do not support secure renegotiation. In that case the answer is "no". The option "SSL_OP_ALLOW_CLIENT_RENEGOTIATION" switches on client initiated renegotiation which is off by default. Any client initiated renegotiation that then occurs will still use secure renegotiation (or it will fail if the client does not support it).

**Comment by vk18anubhav** [comment]
Thanks a lot for the information

**Comment by vk18anubhav** [comment]
If the server has "SSL_OP_ALLOW_CLIENT_RENEGOTIATION" set , any unpatched client that do not support secure renegotiation will not be allowed to renegotiate. 

Are the unpatched client not allowed to connect also to the server ? I mean initial connection would not happen ?

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
