### ISSUE TITLE
Difference in no-gost and -DOPENSSL_NO_GOST

### ISSUE THREAD

**Issue by Pankul94** [openssl/openssl#21205]
Hi there

I am reading the compilation and installation wiki: https://wiki.openssl.org/index.php/Compilation_and_Installation and going through the configure options.

If I want to disable a cipher, for example gost, should I use `no-gost` or `-DOPENSSL_NO_GOST` as my configure option. Are they both essentially doing the same thing and it doesnt matter which one do I use?

Thanks

**Comment by paulidale** [comment]
`no-gost` is correct.

**Comment by Pankul94** [comment]
Thanks!
