### ISSUE TITLE
SSL_OP_CRYPTOPRO_TLSEXT_BUG is missing in doc version 1.1.1

### ISSUE THREAD

**Issue by code4lala** [openssl/openssl#21213]
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_options.html#NOTES
https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_options.html#NOTES
Hi, I found that there are 4 bug workarounds for openssl 3, but 3 bug workarounds for openssl 1.1.1 in documents

man3.0

> The following bug workaround options are available:
> 
> SSL_OP_CRYPTOPRO_TLSEXT_BUG
> Add server-hello extension from the early version of cryptopro draft when GOST ciphersuite is negotiated. Required for interoperability with CryptoPro CSP 3.x.
> 
> SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS
> Disables a countermeasure against a SSL 3.0/TLS 1.0 protocol vulnerability affecting CBC ciphers, which cannot be handled by some broken SSL implementations. This option has no effect for connections using other ciphers.
> 
> SSL_OP_SAFARI_ECDHE_ECDSA_BUG
> Don't prefer ECDHE-ECDSA ciphers when the client appears to be Safari on OS X. OS X 10.8..10.8.3 has broken support for ECDHE-ECDSA ciphers.
> 
> SSL_OP_TLSEXT_PADDING
> Adds a padding extension to ensure the ClientHello size is never between 256 and 511 bytes in length. This is needed as a workaround for some implementations.
> 
> SSL_OP_ALL
> All of the above bug workarounds.

man1.1.1

> The following bug workaround options are available:
> 
> SSL_OP_SAFARI_ECDHE_ECDSA_BUG
> Don't prefer ECDHE-ECDSA ciphers when the client appears to be Safari on OS X. OS X 10.8..10.8.3 has broken support for ECDHE-ECDSA ciphers.
> 
> SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS
> Disables a countermeasure against a SSL 3.0/TLS 1.0 protocol vulnerability affecting CBC ciphers, which cannot be handled by some broken SSL implementations. This option has no effect for connections using other ciphers.
> 
> SSL_OP_TLSEXT_PADDING
> Adds a padding extension to ensure the ClientHello size is never between 256 and 511 bytes in length. This is needed as a workaround for some implementations.
> 
> SSL_OP_ALL
> All of the above bug workarounds plus SSL_OP_LEGACY_SERVER_CONNECT as mentioned below.

SSL_OP_CRYPTOPRO_TLSEXT_BUG is missing in doc version 1.1.1

But I searched SSL_OP_CRYPTOPRO_TLSEXT_BUG in tag `OpenSSL_1_1_1a`, `OpenSSL_1_1_1u`, `OpenSSL_1_1_1`, it exists and is included in SSL_OP_ALL, so is it just missing in doc?

**Comment by mattcaswell** [comment]
> is it just missing in doc?

Yes, its just missing in the doc.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
