### ISSUE TITLE
Encrypt RSA key with SM2

### ISSUE THREAD

**Issue by deepakgodavarthi** [openssl/openssl#21215]
```SM2``` key can theoretically wrap ```RSA``` keys. Openssl does not show an error when encrypting an ```RSA``` key with ```SM2```. It is silently failing. However, the decrypt operation shows an error because the encrypted `RSA` key is invalid.

Here are the steps to recreate this issue:
This is on `OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)`

Generate RSA-2048 key in PKCS#8 format:

```
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -outform DER -out rsa_csk.der
openssl pkcs8 -topk8 -in rsa_csk.der -outform der -nocrypt -out rsa_csk_pkcs8.der
```

Generate SM2 key:
```
openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2 -out sm2-key.pem
openssl pkey -in sm2-key.pem -pubout -out sm2-key-public.pem
```

Encrypt and decrypt the RSA key with SM2 key pair:

```
openssl pkeyutl -encrypt -inkey sm2-key.pem -in rsa_csk_pkcs8.der -out Encrypted.bin
openssl pkeyutl -decrypt -inkey sm2-key.pem -in Encrypted.bin -out rsa_decrypted.bin 
```
`decrypt` operation fails because ```Encrypted.bin``` is invalid. The main catch is the `encrypt` command does NOT throw an error

**Comment by t8m** [comment]
The encrypt/decrypt operation can encrypt only limited size data. Yes, it would be nice if the data size was checked and error printed.

**Comment by deepakgodavarthi** [comment]
Can you give me an example on how to use cms in this case?

**Comment by nhorman** [comment]
I believe there are several examples given in the openssl-cms man page
