### ISSUE TITLE
TLS 1.3 PSK depends on the sequence of cipher suites

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#21226]
OpenSSL version：3.X

I use psk_find_session_cb() and psk_use_session_cb() to implement TLS 1.3 PSK：
The client invokes psk_use_session_cb() to set the SHA256 cipher suite.
The server invokes psk_find_session_cb() to set the SHA256 cipher suite.

Test cases：The server uses the default cipher suite 
(1) The client is configured with TLS_AES_128_GCM_SHA256. The handshake succeeds.
(2) The client is configured with TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384. The handshake succeeds.
(3) The client is configured with TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256. **The handshake fails**. The error message "**no suitable signature algorithm**" is displayed.

Root cause:
The server selects the cipher suite first and does not pay attention to the cipher suite set by psk_find_session_cb(). Therefore, TLS_AES_256_GCM_SHA384 is selected, but the hash algorithm is SHA384, so tls_parse_ctos_psk() fails.

Question:
Is there any way to make use case (3) successful?

**Comment by davidben** [comment]
Yeah, TLS 1.3 external PSKs weren't quite designed right and aren't really suitable for a public API. PSK importers were designed to fix this, but that may be challenging given OpenSSL already exposed the unsuitable version via the PSK callback.
https://www.rfc-editor.org/rfc/rfc9258.html

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.

**Comment by vdukhovni** [comment]
I'm currently implementing RFC9258 support in OpenSSL, this does introduce a new API for registering the PSKs (no longer callback based), but this subsumes and replaces the need for callbacks. Just register the PSKs as either the 8446-style fixed digest variants or 9258-style import-based poly-digest PSKs.

The only limitation is that the agreed cipher between the client and server needs to be associated with a KDF in the IANA registry (currently just SHA256 and SHA384). So SM3 is out until Paul Yang gets an IANA code point in the KDF registry.
If some day an SM4 + SM3 user wants to use a PSK, perhaps the code point will exist by then, though it would require a code change, the KDF id table is not externally configurable.
