### ISSUE TITLE
tlsext_hb_pending missing setter in 1.1

### ISSUE THREAD

**Issue by aircrack-ng** [openssl/openssl#2122]
Working on some code and porting it to 1.1.0 (using Kali, who switched from OpenSSL 1.0.2j to 1.1.0c), I ran into 2 issues compiling. One was easy to fix, a macro was renamed.

The other issue is ```tlsext_hb_pending``` variable in the SSL structure (in 1.0) that I'm setting in the code. I can find a getter function in 1.1.0 but I couldn't find any setter.

I wish I could do a PR as suggested in the mailing list but I'm not familiar with the OpenSSL code enough to do so. My guess would be in tls1.h (and the equivalent .c file), but I'm not sure how to modify it exactly.

**Comment by aircrack-ng** [comment]
Any update on this?

**Comment by richsalz** [comment]
Why do you need a settor?  That's an internal state variable (and it's completely gone in the next release).

**Comment by aircrack-ng** [comment]
For https://github.com/aircrack-ng/aircrack-ng/tree/master/patches/wpe/hostapd-wpe

**Comment by richsalz** [comment]
Sorry, I don't have time to read code. Just answer here, as a comment.  Why do you need to set that variable, and what about when it goes away in the next release?

**Comment by aircrack-ng** [comment]
Because it's used for attacking heartbleed flaw.

**Comment by richsalz** [comment]
Then configure with "no-heartbeats" or build with -DOPENSSL_NO_HEARTBEATS and the code is removed.  Being able to set an internal state machine flag is not something we want to expose.

**Comment by richsalz** [comment]
Also, from the CHANGES file:
```
 *) Heartbeat for TLS has been removed and is disabled by default
     for DTLS; configure with enable-heartbeats.  Code that uses the
     old #define's might need to be updated.
     [Emilia K<C3><A4>sper, Rich Salz
```
