### ISSUE TITLE
OpenSSL aesni_encrypt takes longer than compared to IPP k0_DecryptCFB128_RIJ128pipe_AES_NI

### ISSUE THREAD

**Issue by nid-g-s** [openssl/openssl#21222]
With OpenSSL 3.0.8 version, when decrypting an  buffer using AES_CFB_NOPAD, we have observed that the decryption functions in OpenSSL take approximately 5 times longer compared to IPP. 
Specifically, the decryption process takes 300 seconds in IPP, while it takes 1650 seconds in OpenSSL.

Upon further analysis, we have noticed that the number of function calls differs between IPP and OpenSSL. In IPP, there are 8 calls to the ippsAESDecryptCFB() function, which directly leads to 8 calls to the DecryptCFB128_RIJ128pipe_AES_NI() function. Each call to DecryptCFB128_RIJ128pipe_AES_NI() involves approximately 9000 instructions.
In contrast, OpenSSL utilizes the CRYPTO_cfb128_encrypt() function, which is called 8 times. Each call to CRYPTO_cfb128_encrypt() results in 2044 calls to the aesni_encrypt() function. Each call to aesni_encrypt() involves approximately 256 sub-calls to aesni_encrypt(). Thus overall CRYPTO_cfb128_encrypt() function consumes a substantial number of instructions, total approximately 19,000.

Is there any specific reason why OpenSSL aesni_encrypt takes longer than compared to IPP.

**Comment by preveen-stack** [comment]
@nid-g-s guess you are referring to https://github.com/intel/ipp-crypto and you are on an intel processor. Possibly ipp-crypto is using hardware crypto acceleration supported on intel processors.

**Comment by paulidale** [comment]
No one has spent the effort creating an assembly implementation that is comparable to Intel's.
Intel puts a lot of effort into IPP.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
