### ISSUE TITLE
TLS Client-Server and assigning private keys to SSL context without exporting it from windows cert store

### ISSUE THREAD

**Issue by michalpura** [openssl/openssl#21221]
Hello,
currently, I am on the way of Client/Server test application code refactoring (mostly upgrade to openssl3.x). In general we are getting the certificates/keys from Windows Cert Storage. During initialization phase we use the _SSL_use_PrivateKey()_ to assign the private key to SSL context. 

The problem is that to assign the private key I need to export it from WCS. Due to security reasons I do not want to do it. I would like to use the WCS for keeping the private keys, use but not export them, but I have no idea how to do it. 

Is any way to establish TLS connection between Client<->Server without exporting the private keys form WCS but use them if needed ?

**Comment by t8m** [comment]
You would need a provider that would be able to provide the private key operations via calls to the Windows crypto api using the key stored in WCS. AFAIK there is no such provider yet.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
