### ISSUE TITLE
EC_POINT_set_Jprojective_coordinates_GFp does not check if point is on curve

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#21228]
Unlike `EC_POINT_set_affine_coordinates`, `EC_POINT_set_Jprojective_coordinates_GFp` does not check that the provided coordinates form a point that is on the curve. It would be better if it did. If you will accept it, I can provide a PR for this.

**Comment by t8m** [comment]
This would not be a good idea because EC_POINT_set_affine_coordinates is implemented as call to EC_POINT_set_Jprojective_coordinates_GFp. So there would be a double checking done which is inefficient.

EC_POINT_set_Jprojective_coordinates_GFp is also a deprecated function. So I am closing this RFE.
