### ISSUE TITLE
SM2 encrypt and decrypt by OpenSSL

### ISSUE THREAD

**Issue by xiaonan-INTC** [openssl/openssl#21237]
Hi, OpenSSL developers,

Could you provide a sample code for SM2 encrypt and decrypt based on OpenSSL?
I can't find such in anywhere. Thanks a lot for your support!

**Comment by t8m** [comment]
There could be a demo added to demos/encrypt

**Comment by xiaonan-INTC** [comment]
> There could be a demo added to demos/encrypt

Dear t8m, 

Yes, here is a sample code in demos/encrypt/, it is for rsa, but for sm2, maybe a little different, do you have a plan of adding a sample code sm2? :)

**Comment by paulidale** [comment]
It isn't on our roadmap currently.
It shouldn't be all that different from the RSA example.

**Comment by xiaonan-INTC** [comment]
> It isn't on our roadmap currently. It shouldn't be all that different from the RSA example.

Thanks a lot, paulidale.
