### ISSUE TITLE
OpenSSL 3.1.0 - VC-WIN64A Build fails 

### ISSUE THREAD

**Issue by mnik17** [openssl/openssl#21243]
Hello, I was trying to build OpenSSL 3.1.0 on a 64-bit Windows system. I configured it for VC-WIN64A using Strawberry Perl (which has always worked for me before) `perl Configure VC-WIN64A`. After invoking nmake from the Developer Command Prompt for VS 2019 I get the following error: 

```
crypto\bn\rsa_sup_mul.c(139): fatal error C1189: #error:  Only x64, ARM64 and IA64 supported.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```

I have seen some other issues relating to that e.g. #20280, but if I'm configuring for 64-bit, I'd assume I should not be getting this error.

Thanks!

**Comment by mattcaswell** [comment]
Please try using 3.1.1 instead. The problematic rsa_sup_mul.c file has been removed in that version.

**Comment by mnik17** [comment]
I managed to build 3.1.1. Closing the issue.
