### ISSUE TITLE
libcrypto.3.dylib and libssl.3.dylib name without version no

### ISSUE THREAD

**Issue by aniljadaun** [openssl/openssl#21249]
Can you please suggest step to created shared libcrypto and libssl dylib for mac without the version no in name ? 
i.e currently i get libcrypto.3.dylib and libssl.3.dylib , i want this to be generated with out the version no in name.

Generated libs should be libcrypto.lib and libssl.lib

**Comment by tmshort** [comment]
Hello! I have a few questions.
What version are you using?
Are you self-building (`get clone`, etc), or using `brew` or `macports`
When self-building, or using `brew`, there is a symlink as @levitte describes.

**Comment by aniljadaun** [comment]
HI @levitte @tmshort 

I am doing self build. yes i do get static libraries libcrypto.a and libssl.a as well. But we were previously using dylib in our project and i am supposed to use the same unless we have a strong reason to make a change. 

Can we created libcrypto.dylib and libssl.dylib without the version no ?

**Comment by levitte** [comment]
I assume you want those in the *build directory*?  Then this should suffice:

``` console
$ ln -s libcrypto.3.dylib libcrypto.dylib
$ ln -s libssl.3.dylib libssl.dylib
```

**Comment by tmshort** [comment]
Those files should already be there, this is after a build of `openssl-3.0`:
```
macopenssl (openssl-3.0=)$ ls *.dylib *.a
libcrypto.3.dylib	libcrypto.a		libcrypto.dylib		libssl.3.dylib		libssl.a		libssl.dylib
mac openssl (openssl-3.0=)$ 
```
The `*.dylib` are already symlinked to `*.3.dylib`.

Is it an issue that they are symlinks?

**Comment by tmshort** [comment]
I'm more familiar with Linux shared objects than macOS dynamic libraries. Under linux, the SONAME in the linked shared object is put into the resulting executable. So, linking to a non-versioned shared library, which symlinks to a versioned file, will have the versioned name in it. Even if you rename the actual shared library when linking, the SONAME in the shared library will reference the versioned file.

It appears that macOS acts similarly, but not identially (i.e. `otool -D libssl.3.dylib`)

It is possible to add a new case in `Configurations/10-main.conf` to use a different shared library name. e.g.
```diff
diff --git a/Configurations/10-main.conf b/Configurations/10-main.conf
index 8010087b46..ec3a76fa04 100644
--- a/Configurations/10-main.conf
+++ b/Configurations/10-main.conf
@@ -1683,6 +1683,10 @@ my %targets = (
         asm_arch         => 'aarch64',
         perlasm_scheme   => "ios64",
     },
+    "darwin64-arm64-nv" => {
+        inherit_from => [ "darwin64-arm64" ],
+        shared_extension => ".dylib",
+    },
 
 ##### GNU Hurd
     "hurd-x86" => {
```
Although this is not recommended, as not having the version number in the shared library name could cause confusion with other OpenSSL versions (including LibreSSL, which is the default on macOS).

**Comment by aniljadaun** [comment]
@levitte Thanks for your repsonse and sorry for not so clear description of my request. As @tmshort suggested i don't want to create symbolic link to version named file, instead i want to create a file with the name which doesn't have version info.
 
 @tmshort Thanks for your suggestion . Please suggest what should be step to create the same for x86_64..

**Comment by levitte** [comment]
Like @tmshort mentions, that is a bad idea. If you have a 1.1.1 libcrypto.dylib in your dylib load path, the application won't know the difference, but either won't be able to start for lack of symbols, or will break, possibly in "interesting" ways.

Do. Not. Do. That.
I cannot emphasise this strongly enough

**Comment by tom-cosgrove-arm** [comment]
@aniljadaun Is this related to your issue #21246, where you seem to have deleted the symlinks and renamed the libraries? Having the same fundamental question/problem over two issues means you will likely only get half the attention you want - may I suggest you delete one or the other and clarify the question?

**Comment by aniljadaun** [comment]
@tom-cosgrove-arm Sure , i understand your concern. Please delete/close the other issue.

**Comment by aniljadaun** [comment]
Hi @tmshort 

Thanks for your suggestion , it works.

@levitte As always thanks for sharing your thoughts , though it would still be very helpful if you could elaborate a little on the problem we might run in to. 
Are we talking about accidentally missing out on updating openssl libs while updating and then using two version of openssl libs while linking/building the code ?

**Comment by paulidale** [comment]
That is what @levitte was concerned about.

If you really need the libraries without version numbering and are aware of the inevitable problems this will cause, you should rename them earlier -- specifically before linking anything.  You'll probably have to dodgy up the libssl build to not use a versioned libcrypto.

Honestly, you're heading down a dark and painful path here.  Live with the versioning and forget about the myriad problems you are yet to encounter.  As a project, we cannot support you once you start down the path.

**Comment by aniljadaun** [comment]
@paulidale Ok...This sounds like lots and lots of problems to handle. I think we should be ok with using versioned openssl build as well. 

Though i am still curious Is there no way to make this work without versioning info? Suppose we generate libssl and libcrypto using @tmshort suggestion . This way i would have consistent libssl and libcrypto build (no versioned dylib using another unversioneddylib). Then replacing old libs with new libs in our project. Supposing we updated replaced all old openssl libs with new openssl libs . Can we still get issues ? Due to the older version of libs in other apps as well ?

**Comment by paulidale** [comment]
Feel free to experiment with unversioned libraries.  I suspect that it is possible.  I just noted that the project cannot provide any support if you follow this path.  As for you questions, they fall under _the project cannot provide any support_.  Figure it out yourself if you must.

**Comment by tmshort** [comment]
A similar change for `x86_64` can be made, copy/paste/edit the other patch. Reviewing macOS's equivalent of SONAME, it uses the full pathname of libraries destination, which makes this even more convoluted (i.e. `LD_LIBRARY_PATH` doesn't work). See the results of `otool -D <library>`. This path can be modified by `--prefix` and similar options to `Configure`.

See: https://www.usenix.org/legacy/publications/library/proceedings/als00/2000papers/papers/full_papers/browndavid/browndavid_html/index.html for reasons why shared objects/dynamic libraries are versioned (it's specifically about Linux/Solaris, but applies to macOS as well).

**Comment by aniljadaun** [comment]
Hi @levitte , @paulidale , @tmshort 

FIrst of all thanks for your suggestions.
I tried both the ways to make it work.
Generated libssl and libcrypto
1. Without version in the name.
This works as expected .

2. With version no in the name as libssl.3.dylib and libcrypto.3.dylib
This is giving crash as soon as any cryptographic operation is touched.

System configuration 
 Mac Monterey , Apple M1 Chip
 
 Are we aware about any such use case ? Is using real name supported on mac ?

**Comment by tmshort** [comment]
You are seeing the behavior of loading against an old library.

|| New Lib | Old Lib |
| - | - | - |
| Old App | :+1: | :+1: |
| New App | :+1: | :x:

On macOS, the full path of the library is put into the library, rather than the name. Unless you installed the new libraries, you are likely using old/stale libraries from a previous install.

So, try this:
Do your build, etc. In your repo do `otool -D <library>`. In the output there should be a path/filename. 
e.g.
```
libcrypto.3.dylib:
/usr/local/lib/libcrypto.3.dylib
```
Does that file already exist on your system? How old is it? Is it the library you just built, or something older?
e.g.
```
strings /usr/local/lib/libcrypto.3.dylib | grep --fixed "OpenSSL 3."
```

To be honest, I think you want to build statically (i.e. `no-shared` option to OpenSSL's `Configure`, along with a `--static` link option).

Or, you need to update the installed library to the latest via `make install`.

**Comment by aniljadaun** [comment]
Hi @tmshort 

I am doing dynamic linking on mac. 
Does installing requires seprate installation of openssl 3.0 other that generating openssl libs. doesn't generating openssl also installs openssl.

Secondly, otool -L  shows the binaries are referenced from the --prefix path or the path where libs were generated . We would be shipping them in our package. Do we need additional steps to change the referenced path in the library to a generic path rpath which can load libs at run time?
For loading libs do we also need to install them on every machine our project will run on ?

**Comment by aniljadaun** [comment]
@tmshort 
We basically want to turn on fips compliant behaviour. Currently we do dynamic building for mac and static building for win. Win update to openssl3.0 has been smooth but mac is giving us issue and to be honest i too don't have much experience with mac that could be one of the reason for added trouble for the entire upgrade process.

**Comment by aniljadaun** [comment]
Thanks @tmshort  for patiently listening on this .
Yes, i have downloaded source code from github .Process done for generating openssl libs is:

make clean
./Configure darwin64-x86_64-cc enable-fips enable-capieng --prefix=/Users/anils/opensslrpathinstall/x86_64/shared/release --openssldir=/Users/anils/opensslrpathinstall/openssldir 
make
make test
make install

on doing otool -L on generated libcrypto.3.dylib and libssl.3.dylib , i get the path corresponding to --prefix option "/Users/anils/opensslrpathinstall/x86_64/shared/release/lib/libcryoto.3.dylib"

This is from where my app is trying to load openssl libs at run time. I updated reference path in the openssl lib using install_name_tool path to @rpath/libcrypto.dylib .

From your previous comment it seems we also need to install openssl on system . Is it correct ? if yes how do we do that ? What libs do we need for the same ? can you guide me to some documentation ?

Though i understand why you are asking us to move to static linking but right now moving to static linking would be a arch change for us which we might not be willing to do.

let me know if you need any other piece of information on this.
