### ISSUE TITLE
X509: cert_info no longer accessible

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2124]
While porting an application to OpenSSL 1.1.0, I found that the `cert_info` struct member that was previously freely accessible for `X509` data types seems now no longer accessible by any means.

If possible, please add a function or macro to access `X509->cert_info`.

The application I am porting hashes this field and uses the hash as part of a certificate representation. If `cert_info` can now no longer be exposed, please suggest a different part of the data I can use for the same purpose.

Thank you!

**Comment by richsalz** [comment]
But cert_info is also an opaque structure.  And then you'll want accessors for all of that information, just so you can digest it.  Not sure that is the best way to go.  Can't you just digest the DER of the cert?

**Comment by bernd-edlinger** [comment]
Could you at least make the sha1_hash member of x509_st and x509_crl_st accessible?
I mean if you internally have the sha1_hash already why should it be necessary to
do the whole computation again?

**Comment by richsalz** [comment]
Yes, adding two accessors X509_hash() and X509CRL_hash() makes sense.

**Comment by richsalz** [comment]
3e5d9da on master and 550f0f9 on 1.1.0

**Comment by johny7** [comment]
Hello,

The X509_hash() and X509CRL_hash() still didn't make it into version 1.1.1a. This is quite a miss - it's necessary for implementation of get_by_fingerprint callback of X509_LOOKUP_METHOD struct.

**Comment by levitte** [comment]
You're looking for the wrong name, we used "digest" rather than "hash", so...

https://www.openssl.org/docs/man1.1.1/man3/X509_digest.html

**Comment by johny7** [comment]
Yes, it seems X509_digest(cert,  EVP_sha1(), outputbuffer, ..) can be used to retrieve the sha1 hash from a certificate.
Thank you.
