### ISSUE TITLE
Can I use the FIPS module on android

### ISSUE THREAD

**Issue by trampster** [openssl/openssl#21245]
I'm wanting to use the fips certified openssl 3.0.8 on Android.

However I'm not sure if it's supported/fips certified there for the following reasons:

- The [security policy](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4282.pdf) does not mention android and only has install instructions for Unix, Linux, macOS and Windows.
- The security policy specifies the following:

> Note: The Module shall have the self-tests run, and the Module config file output generated on each
> platform where it is intended to be used. The Module config file output data shall not be copied from
> one machine to another.

I don't know how to comply with this on android. Where things are prebuilt and installed via an APK and are not installed via make install or openssl fipsinstall.

i.e. is there a way to run the self-tests and generate the Module config in an Android app installed via and APK? Such that it is not copied from one machine to another?

Is there to a way use the FIPS module on android in a way that is FIPS compliant?

**Comment by paulidale** [comment]
To be strictly compliant, you **must** follow the instructions in the security policy to the letter.  If you are unable to do so, you won't be.  There is a workaround they adheres to the _spirit_ of the requirements but not the _letter_: run `fipsinstall` with the `-self_test_onload` option and _then_ copy the configuration across.

This ensures that the self tests are always run and that's the intention of the no copying requirement.  As per the policy, the self tests are run on installation and not run subsequently.  Copying the configuration between machines or VMs means the self tests aren't re-run which is forbidden.  By setting that option, they will be run after copying.

This will mean that you are _not_ FIPS compliant, despite doing what the no-copying clause intended.
FIPS is fickle.

**Comment by trampster** [comment]
Thanks,

Our customers require FIPS so 'doing what the no-copying clause intended' will not be enough.

When OpenSSL is next submitted to NIST for validation would it be possible to reword the Security Policy such that using it on Android would be possible?

**Comment by paulidale** [comment]
The upcoming 3.1 validation changes the self test requirement to on load, so it would be okay.  We're not going to see this get through the process for at least a year after submission (which hasn't happened yet).

We've no plans to validate on Android, lack of knowledge on the part of the team precludes this.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.

**Comment by DeekshantDewari** [comment]
@trampster Hey buddy I need to ask were you able to access oqs provider in openssl for android ?
If you are able to do can you tell how you access the oqs provider  in openssl.
