### ISSUE TITLE
provider upcall test under MSVC

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#21241]
Question: Is there any test case building and loading a test provider via the "external" load mechanism, i.e., not using `OSSL_PROVIDER_add_builtin`? I'd then like to extend it like e.g. [here](https://github.com/openssl/openssl/compare/master...baentsch:openssl:extendtestcreateupcall?expand=1).

Reason for asking: `oqsprovider` faces one of the most bizarre test case problems it has ever seen: _Always_ when building/running `oqsprovider`, the upcall via `c_obj_create` (`OSSL_FUNC_core_obj_create`) succeeds; but _only_ under MSVC a subsequent check whether a NID has really been assigned receives `NID_undef` (checked e.g. via `OBJ_sn2nid`).

This failure however only happens if the configuration file activating `oqsprovider` is loaded by using `OSSL_LIB_CTX_load_config` If in turn "OPENSSL_CONF" points to the very same file a NID gets properly returned (as _always_ is the case under UNiX).

The good test case can be observed [here](https://github.com/baentsch/oqs-provider/actions/runs/5311626648/jobs/9615083988), the bad test case [here](https://github.com/baentsch/oqs-provider/actions/runs/5309570734/jobs/9610389715): In the latter case, "OPENSSL_CONF" has not been set for the first 3 (failing) tests. A check added to testing is [here](https://github.com/openssl/openssl/compare/master...baentsch:openssl:extendtestcreateupcall?expand=1) -- but passes testing also on MSVC -- presumably because as it's using `OSSL_PROVIDER_add_builtin`. Hence the original question. 

Thanks in advance for any thoughts. Hunch: Does the logic loading providers differ (under MSVC) when being passed a specific "libctx" vs. loaded "globally" by setting "OPENSSL_CONF"?

**Comment by t8m** [comment]
Unfortunately there is no internal test provider built as shared module.

**Comment by baentsch** [comment]
> Unfortunately there is no internal test provider built as shared module.

Thanks for this re-confirmation. I'd like to suggest this then as a feature (request) for any possibly upcoming discussions regarding provider development.

**Comment by mattcaswell** [comment]
> Unfortunately there is no internal test provider built as shared module.

Errr.....p_test.so? See test/p_test.c

**Comment by mattcaswell** [comment]
Loaded from test/provider_test.c

**Comment by t8m** [comment]
Ouch, sorry for forgetting about that one.

**Comment by baentsch** [comment]
Thanks for the pointer. I tried to reproduce the error behaviour with `p_test` but failed. This issue thus is resolved -- but might be followed up by sth else if/when I understand better why `oqsprovider` behaves so differently under Windows as compared to Unix.
