### ISSUE TITLE
Problem when extracting the public key from the EC private key using a version of openSSL >= 3.0

### ISSUE THREAD

**Issue by Diego-AltF4** [openssl/openssl#21253]
I am trying to extract the public key from the EC private key using a version of openSSL >= 3.0. Previously, it was something simple:

```c
EVP_PKEY* extractPublicKey(EVP_PKEY *privateKey)
{
    EC_KEY *ecKey = EVP_PKEY_get1_EC_KEY(privateKey);
    EC_POINT *ecPoint = EC_KEY_get0_public_key(ecKey);

    EVP_PKEY *publicKey = EVP_PKEY_new();

    EC_KEY *pubEcKey = EC_KEY_new_by_curve_name(NID);

    EC_KEY_set_public_key(pubEcKey, ecPoint);

    EVP_PKEY_set1_EC_KEY(publicKey, pubEcKey);

    EC_KEY_free(ecKey);
    EC_POINT_free(ecPoint);

    return publicKey;
}
```
But right now I see that many of these functions are deprecated. I have tried quite a few solutions, but none of them works for me. Among them, [the implementation that aizuon developed](https://github.com/openssl/openssl/issues/18437).

Is there any official method that deals with this case instead of a workaround as shown in the example above?

Thanks in advance

**Comment by paulidale** [comment]
You should try the [`EVP_PKEY_todata()` function](https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_todata.html).  The exported fields are documented on the [EC page](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-EC.html).

**Comment by Diego-AltF4** [comment]
Your solution worked flawlessly, thank you very much.
I have another question. Using EVP_PKEY_todata I can get an OSSL_PARAM and from there the value associated to the "pub" field. My new problem is, how can I create a new EVP_PKEY variable using that public key?
I have tried to generate a BIGNUM with the content of the pub field and using EVP_PKEY_set_bn_param set this big num to the EVP_PKEY, but when doing the key derivation, it gives problems. 

Thanks in advance.

```c
    BIGNUM *pubKeyBN = BN_new();

    BN_bin2bn(data, sizeof(data), pubKeyBN);

    EVP_PKEY *publicKey = EVP_PKEY_new();
    EVP_PKEY_set_bn_param(publicKey, "pub",pubKeyBN);
```
Clarification: data contains the value associated with the "pub" field.

**Comment by Diego-AltF4** [comment]
Your solution worked flawlessly, thank you very much.
I have another question. Using EVP_PKEY_todata I can get an OSSL_PARAM and from there the value associated to the "pub" field. My new problem is, how can I create a new EVP_PKEY variable using that public key?
I have tried to generate a BIGNUM with the content of the pub field and using EVP_PKEY_set_bn_param set this big num to the EVP_PKEY, but when doing the key derivation, it gives problems. 

Thanks in advance.

```c
    BIGNUM *pubKeyBN = BN_new();

    BN_bin2bn(data, sizeof(data), pubKeyBN);

    EVP_PKEY *publicKey = EVP_PKEY_new();
    EVP_PKEY_set_bn_param(publicKey, "pub",pubKeyBN);
```
Clarification: data contains the value associated with the "pub" field.

**Comment by paulidale** [comment]
`EVP_PKEY_fromdata` is the magic call.  There should be examples in the documentation.

**Comment by Diego-AltF4** [comment]
Perfect, thank you very much!

**Comment by TrafalgarSX** [comment]
> Your solution worked flawlessly, thank you very much.您的解决方案完美无缺，非常感谢您。 I have another question. Using EVP_PKEY_todata I can get an OSSL_PARAM and from there the value associated to the "pub" field. My new problem is, how can I create a new EVP_PKEY variable using that public key? 我有另一个问题。使用 EVP_PKEY_todata 我可以获得 OSSL_PARAM 并从那里获取与“pub”字段关联的值。我的新问题是，如何使用该公钥创建新的 EVP_PKEY 变量？ I have tried to generate a BIGNUM with the content of the pub field and using EVP_PKEY_set_bn_param set this big num to the EVP_PKEY, but when doing the key derivation, it gives problems. 我尝试使用 pub 字段的内容生成一个 BIGNUM 并使用 EVP_PKEY_set_bn_param 将这个大数字设置为 EVP_PKEY，但是在进行密钥派生时，它会出现问题。
> 
> Thanks in advance. 提前致谢。
> 
> ```c
>     BIGNUM *pubKeyBN = BN_new();
> 
>     BN_bin2bn(data, sizeof(data), pubKeyBN);
> 
>     EVP_PKEY *publicKey = EVP_PKEY_new();
>     EVP_PKEY_set_bn_param(publicKey, "pub",pubKeyBN);
> ```
> 
> Clarification: data contains the value associated with the "pub" field.说明：数据包含与“pub”字段关联的值。

How did you do that? I called `EVP_PKEY_fromdata` to generate `EVP_PKEY *private_key` from `uint8_t private_key[32]`, but I cannot obtain the `pub` field's `param` from `EVP_PKEY_todata`.

**Comment by TrafalgarSX** [comment]
> Your solution worked flawlessly, thank you very much. I have another question. Using EVP_PKEY_todata I can get an OSSL_PARAM and from there the value associated to the "pub" field. My new problem is, how can I create a new EVP_PKEY variable using that public key? I have tried to generate a BIGNUM with the content of the pub field and using EVP_PKEY_set_bn_param set this big num to the EVP_PKEY, but when doing the key derivation, it gives problems.
> 
> Thanks in advance.
> 
> ```c
>     BIGNUM *pubKeyBN = BN_new();
> 
>     BN_bin2bn(data, sizeof(data), pubKeyBN);
> 
>     EVP_PKEY *publicKey = EVP_PKEY_new();
>     EVP_PKEY_set_bn_param(publicKey, "pub",pubKeyBN);
> ```
> 
> Clarification: data contains the value associated with the "pub" field.
How did you do that? I called EVP_PKEY_fromdata to generate EVP_PKEY *private_key from uint8_t private_key[32], but I cannot obtain the pub field's param from EVP_PKEY_todata.
