### ISSUE TITLE
OpenSLL API fails with following error when loaded from Memory

### ISSUE THREAD

**Issue by swanandb2** [openssl/openssl#21250]
/* Create a context for the digest operation */
   EVP_MD_CTX * md_ctx = EVP_MD_CTX_new();
    if (md_ctx != NULL)
    {
      EVP_MD * sha3 = EVP_MD_fetch(NULL, "SHA3-512", NULL);
     if (sha3 == NULL)
      { 
       /*I am getting sha3 as null with following openssl error*/
             int nRet = ERR_get_error();
        printf("nRet:%d %s OpenSSL error: %s\n", nRet,  __FUNCSIG__, ERR_error_string(nRet, NULL));
   
      }
   }
      Return error code:50856204 OpenSSL error: error:0308010C:lib(6)::reason(268)

**Comment by paulidale** [comment]
What error?

**Comment by paulidale** [comment]
Perhaps ask the MemoryModule folks?
I suspect this is outside of the team's experience.

**Comment by swanandb2** [comment]
May I know, meaning of Error codes receive from OpenSSL. How can i find them?

**Comment by paulidale** [comment]
As far as I can tell, the error is "unsupported" coming from the EVP subsection.
This looks like a _fetch_ has failed -- possibly because things aren't loading properly?
