### ISSUE TITLE
Configuration step for DJGPP/Watt32 does not work

### ISSUE THREAD

**Issue by Neo-Desktop** [openssl/openssl#21259]
Hi there, attempting to build OpenSSL on linux using the DJGPP/Watt32 toolchain does not work as intended

Simply running the following configure statement:

```
# ./Configure no-threads -DOPENSSL_DEV_NO_ATOMICS --prefix=$HOME/djgpp DJGPP
Configuring OpenSSL version 1.1.1u (0x1010115fL) for DJGPP
```

renders the following output:

```
#  perl configdata.pm --dump

Command line (with current working directory = .):

    /usr/bin/perl ./Configure no-threads -DOPENSSL_DEV_NO_ATOMICS --prefix=/root/djgpp DJGPP

Perl information:

    /usr/bin/perl
    5.34.0 for x86_64-linux-gnu-thread-multi

[cut]

Config target attributes:

[cut]
    CFLAGS => "-fomit-frame-pointer -O2 -Wall",
[cut]
    cflags => "-I/dev/env/WATT_ROOT/inc -DTERMIOS -DL_ENDIAN",
[cut]
    lflags => "-L/dev/env/WATT_ROOT/lib",

[truncated]

```

the above configuration obviously does not work.
I'm not sure what distribution/os exposes `/dev/env/*` but certainly not ones I'm familiar with

----------------------

that being said, the following proposed patch corrects what I believe the configuration developer intended

```diff
diff --git a/Configurations/50-djgpp.conf b/Configurations/50-djgpp.conf
index a8853a81..b2809054 100644
--- a/Configurations/50-djgpp.conf
+++ b/Configurations/50-djgpp.conf
@@ -7,9 +7,9 @@ my %targets = (
         inherit_from     => [ asm("x86_asm") ],
         CC               => "gcc",
         CFLAGS           => "-fomit-frame-pointer -O2 -Wall",
-        cflags           => "-I/dev/env/WATT_ROOT/inc -DTERMIOS -DL_ENDIAN",
+        cflags           => "-I$ENV{'WATT_ROOT'}/inc -DTERMIOS -DL_ENDIAN",
         sys_id           => "MSDOS",
-        lflags           => add("-L/dev/env/WATT_ROOT/lib"),
+        lflags           => add("-L$ENV{'WATT_ROOT'}/lib"),
         ex_libs          => add("-lwatt"),
         bn_ops           => "BN_LLONG",
         perlasm_scheme   => "a.out",

```

**Comment by Neo-Desktop** [comment]
this also applies to the 3x branches as well

**Comment by jwt27** [comment]
This works in the CI cross-builds since the Watt-32 include path there is added
by a `gcc.specs` file.  The `/dev/env` paths are then ignored - they only exist
in a native build.

Proposed patch looks good to me, that should work for all configurations.

**Comment by jwt27** [comment]
That would work, yes.  Even nicer would be to omit the `-I`/`-L` flags
altogether in that case.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
