### ISSUE TITLE
X509_CRL: crl no longer accessible

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2125]
While porting an application to OpenSSL 1.1.0, I found that the `crl` struct member that was previously freely accessible for `X509_CRL` data types seems now no longer accessible by any means.

If possible, please add a function or macro to access `X509_CRL->crl`.

The application I am porting hashes this field and uses the hash as part of a certificate revocation representation. If `crl` can now no longer be exposed, please suggest a different part of the data I can use for the same purpose.

Thank you!

**Comment by richsalz** [comment]
Same issue as #2124: why not a (truncated) digest of the DER?

**Comment by richsalz** [comment]
3e5d9da on master and 550f0f9 on 1.1.0
