### ISSUE TITLE
sbrk calls resulting in high memory allocations in Openssl APIs

### ISSUE THREAD

**Issue by vk18anubhav** [openssl/openssl#21251]
We are using Openssl 3.0.8 on linux and we are seeing high memory allocations with sbrk(135kb each) in following 4 stacks :

#0  sbrk from /lib64/libc.so.6
#1  __default_morecore from /lib64/libc.so.6
#2  sysmalloc from /lib64/libc.so.6
#3  _int_malloc from /lib64/libc.so.6
#4  malloc from /lib64/libc.so.6
#5  malloc ()
#6  CRYPTO_strndup 
#7  ossl_algorithm_get1_first_name
#8  evp_kdf_from_algorithm
#9  construct_evp_method
#10 ossl_method_construct_this
#11 algorithm_do_this
#12 ossl_provider_doall_activated
#13 ossl_algorithm_do_all
#14 ossl_method_construct
#15 inner_evp_generic_fetch
#16 evp_generic_fetch 
#17 EVP_KDF_fetch
#18 ossl_pkcs5_pbkdf2_hmac_ex

#0  sbrk from /lib64/libc.so.6
#1  __default_morecore from /lib64/libc.so.6
#2  sysmalloc from /lib64/libc.so.6
#3  _int_malloc from /lib64/libc.so.6
#4  malloc from /lib64/libc.so.6
#5  malloc ()
#6  ossl_namemap_doall_names
#7  evp_cipher_from_algorithm 
#8  construct_evp_method
#9  ossl_method_construct_this 
#10 algorithm_do_this 
#11 ossl_provider_doall_activated
#12 ossl_algorithm_do_all
#13 ossl_method_construct
#14 inner_evp_generic_fetch
#15 evp_generic_fetch
#16 EVP_CIPHER_fetch

#0  sbrk from /lib64/libc.so.6
#1  __default_morecore from /lib64/libc.so.6
#2  sysmalloc from /lib64/libc.so.6
#3  _int_malloc from /lib64/libc.so.6
#4  malloc from /lib64/libc.so.6
#5  malloc ()
#6  ossl_namemap_doall_names 
#7  evp_cipher_from_algorithm 
#8  construct_evp_method 
#9  ossl_method_construct_this
#10 algorithm_do_this 
#11 ossl_provider_doall_activated 
#12 ossl_algorithm_do_all 
#13 ossl_method_construct
#14 inner_evp_generic_fetch
#15 evp_generic_fetch
#16 EVP_CIPHER_fetch
#17 drbg_ctr_instantiate_wrapper
#18 EVP_RAND_instantiate
#19 rand_new_drbg 
#20 RAND_get0_primary 
#21 RAND_get0_public
#22 RAND_bytes_ex

#0  sbrk from /lib64/libc.so.6
#1  __default_morecore from /lib64/libc.so.6
#2  sysmalloc from /lib64/libc.so.6
#3  _int_malloc from /lib64/libc.so.6
#4  malloc from /lib64/libc.so.6
#5  malloc ()
#6  OPENSSL_LH_insert 
#7  ERR_load_strings_const 
#8  ossl_err_load_EC_strings 
#9  ossl_err_load_crypto_strings
#10 ossl_init_load_crypto_strings_ossl_
#11 __pthread_once_slow
#12 CRYPTO_THREAD_run_once 
#13 OPENSSL_init_crypto
#14 ossl_err_get_state_int
#15 ERR_peek_error

The memory mapped with sbrk due to malloc does not get freed back to the system. So even though the memory was freed with a free() call, it stays to be used by a future malloc call and till end of session.

Is there any way sbrk is avoidable or configurable ?

**Comment by paulidale** [comment]
Unfortunately no.  A malloc library that returned memory to the systems might exist and using such do what you want.

**Comment by tom-cosgrove-arm** [comment]
OpenSSL only calls `malloc()` - from the traces you provided it's within `libc` that the `sbrk` call is made - we can't control this

**Comment by paulidale** [comment]
Agreed, OpenSSL never calls sbrk or brk directly, however it does call malloc et al a lot.
Reducing the number of such calls is something the project is interested in doing eventually.  Currently other priorities are higher.

As I mentioned earlier, find a malloc implementation that returns unused storage to the OS and use that.  It should help reduce memory usage.

**Comment by vk18anubhav** [comment]
I investigated this further and took the pmap output in my test application  before and after calling RAND_bytes()

Before RAND_bytes():
-bash-4.4$ sudo pmap -x PID | head -10
Kbytes     RSS   Dirty Mode  Mapping
8               8       4 r----  mytestapplication
12            12       4 r-x--  mytestapplication
8               8       0 r----  mytestapplication
4               4       4 r----  mytestapplication
4               4       4 rw---  mytestapplication
132         112     112 rw---  [ anon ]
96            96       4 r-x--  libgcc_s-8-20210514.so.1
2044         0       0 -----  libgcc_s-8-20210514.so.1

After RAND_bytes()
-bash-4.4$ sudo pmap -x PID | head -10
Kbytes     RSS   Dirty Mode  Mapping
8               8       4 r----  mytestapplication
12            12       4 r-x--  mytestapplication
8               8       0 r----  mytestapplication
4               4       4 r----  mytestapplication
4               4       4 rw---  mytestapplication
392       312     312 rw---  [ anon ]
96           96       4 r-x--  libgcc_s-8-20210514.so.1
2044        0       0 -----  libgcc_s-8-20210514.so.1

Alone RAND_bytes() lead to increase of 260 Kbytes memory with 2 sbrk() calls. 260K bytes is a lot of memory for a function like RAND_bytes(). I suspect this might be resulting from high number of mallocs done in RAND_bytes()

**Comment by vk18anubhav** [comment]
Input buffer I used for calling above RAND_bytes() was of size 1Kbyte

**Comment by levitte** [comment]
Seeing the initial traceback, it's clear that it's our initialization of all sorts of methods that cause this allocation.

So yeah, our initialization when algorithms are fetched (internally, we fetch them in bulk) allocates a larger bit of memory than one might think, but that's only partially responsible for what you see, as malloc() implementations have some sort if memory bookkeeping as well (and in some cases, some amount of overallocation for efficiency) that's beyond our control.

**Comment by paulidale** [comment]
RAND_bytes() doesn't allocate anything like that much memory for itself.  As @levitte noted, it's all the other initialisation that happens.  These should be a once off.

**Comment by vk18anubhav** [comment]
- The use case where we are seeing anon memory growth in 4 stack traces as mentioned in my first comment is multiprocess and APIs of concern are OPENSSL_init_crypto(), RAND_bytes(), EVP_CIPHER_fetch(), PKCS5_PBKDF2_HMAC(). Memory growth that happens with these crypto operations is 600KB per process and in realtime environment with thousand of processes this memory will blow up. 600 MB for 1k sessions

- Compared to other crypto toolkit, this anon memory allocation is huge. For ex. calling alone RAND_bytes() leads to 260K memory increase while in the other toolkit this was not seen for random number generation

- Is there any way for memory optimisation and reduce unnecessary mallocs in Openssl toolkit?

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
