### ISSUE TITLE
use libwebsockets with OpenSSL was upgraded from 1.1.1u to 3.0.9 on the android-arm platform, and when connecting to WebSocket, an error occurred: SSL routines::legacy sigalg disallowed or unsupported

### ISSUE THREAD

**Issue by chanhomer** [openssl/openssl#21254]
Hi, I have setup my project, using libwebsockets(v2.1.0) with OpenSSL was upgraded from 1.1.1u to 3.0.9 on the android-arm platform, and when the app connecting to WebSocket, an error occurred: “SSL routines::legacy sigalg disallowed or unsupported”

ERROR : SSL connect error 167772493: error:0A00014D:SSL routines::legacy sigalg disallowed or unsupported

while there was no problem with android-arm64 platform when use OpenSSL 3.0.9. At the same time, using OpenSSL 1.1.x version on android-arm platform also did not have any problems.

OpenSSL compilation command:
./Configure android-arm -D__ANDROID_API__=16 -static no-tests

**Comment by preveen-stack** [comment]
can you do 
```
$ openssl errstr 0x0A00014D
```

**Comment by chanhomer** [comment]
error:0A00014D:lib(20)::reason(333)

**Comment by chanhomer** [comment]
errstr is : error:0A00014D:lib(20)::reason(333)

**Comment by mattcaswell** [comment]
> legacy sigalg disallowed or unsupported

Looks like something is going wrong with the sig alg negotiation and you are falling back to a legacy sig alg.

Can you get a pcap/wireshark trace of the failing handshake?

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
