### ISSUE TITLE
FIPS provider as built-in provider instead of default provider

### ISSUE THREAD

**Issue by pgarba** [openssl/openssl#21264]
Hi,

I want to avoid to load the shared FIPS library and directly compile the FIPS provider as the default built-in provider like its done with the default provider. Is this possible ? Or do you see any problems with that ?

Thanks,
Peter

**Comment by paulidale** [comment]
It is not possible to build in the FIPS provider.  It can only be used as a loadable module.
This is due to the mandated integrity check.
