### ISSUE TITLE
X509_verify_cert: error check self-signed?

### ISSUE THREAD

**Issue by algv** [openssl/openssl#2126]
Command: `verify -CAfile test.cer test.cer` out: 
```
error 20 at 0 depth lookup:unable to get local issuer certificate
error in verify
```
X509_verify_cert function uses:

```
/* Return 1 is a certificate is self signed */
static int cert_self_signed(X509 *x)
{
    X509_check_purpose(x, -1, 0);
    if (x->ex_flags & EXFLAG_SS)
        return 1;
    else
        return 0;
}
```

For my certificate return 0, but it self-signed certificate. I see what x509v3_cache_extensions set value 0x00000133 to x->ex_flags and then compare `x->ex_flags & EXFLAG_SS` (0x2000)

Error in openssl code or in my certificate purpose?

My certificate:

> -----BEGIN CERTIFICATE-----
> MIIB/zCCAaygAwIBAgIBATAKBggqhQMHAQEDAjA1MSAwHgYJKoZIhvcNAQkBFhF0
> ZXN0QGNyeXB0b3Byby5ydTERMA8GA1UEAwwIdGVzdF9wZngwHhcNMTYxMDIwMDYx
> NjUzWhcNMzAxMDAxMDYxNjUzWjA1MSAwHgYJKoZIhvcNAQkBFhF0ZXN0QGNyeXB0
> b3Byby5ydTERMA8GA1UEAwwIdGVzdF9wZngwZjAfBggqhQMHAQEBATATBgcqhQMC
> AiQABggqhQMHAQECAgNDAARApU3tMftURMSc5Ue/M4gEKlqFVJmOa29UL91cf4I/
> mLHzqOyRB9LL986wZsS0nVZrjmYAg40+N7Sy+WH2/axejqOBnzCBnDAdBgNVHQ4E
> FgQU6oiBf0rq0aRj4i6K5RU606MVcW4wCwYDVR0PBAQDAgO4MA8GA1UdEwQIMAYB
> Af8CAQEwXQYDVR0BBFYwVIAU6oiBf0rq0aRj4i6K5RU606MVcW6hOaQ3MDUxIDAe
> BgkqhkiG9w0BCQEWEXRlc3RAY3J5cHRvcHJvLnJ1MREwDwYDVQQDDAh0ZXN0X3Bm
> eIIBATAKBggqhQMHAQEDAgNBAG3hxe4dH9wxFxfTN7UDrdG+irrqUyAo70fQgf8e
> H/aBKKOc4SwNNfCgETiOBeWzmacuR5GeHgomzNP+p7e+6bk=
> -----END CERTIFICATE-----

**Comment by algv** [comment]
ASN.1 structure for key usage:
```
OBJECT IDENTIFIER 2.5.29.15
OCTET STRING (1 elem)
BIT STRING (5 bit) 10111
```
[RFC 5280](https://tools.ietf.org/html/rfc5280#page-29):

```
KeyUsage ::= BIT STRING {
           digitalSignature        (0),
           nonRepudiation          (1), -- recent editions of X.509 have
                                -- renamed this bit to contentCommitment
           keyEncipherment         (2),
           dataEncipherment        (3),
           keyAgreement            (4),
           keyCertSign             (5),
           cRLSign                 (6),
           encipherOnly            (7),
           decipherOnly            (8) }
```

And I dont see restrictions for use 10111 bits

**Comment by algv** [comment]
Find commit https://github.com/openssl/openssl/commit/f51e5ed6b4b91d12228da873db72aa28109d1797 Why need add certificate signing to self-signed?

**Comment by algv** [comment]
In RFC 5280, [6.1.3.  Basic Certificate Processing](https://tools.ietf.org/html/rfc5280#section-6.1.3): 

>  If i is not equal to n, continue by performing the preparatory steps
>    listed in Section 6.1.4.  If i is equal to n, perform the wrap-up
>    steps listed in Section 6.1.5.

Section 6.1.4: 

> (n)  If a key usage extension is present, verify that the
>            keyCertSign bit is set.

But no need check keyCertSign bit for self-sign. I think need revert https://github.com/openssl/openssl/commit/f51e5ed6b4b91d12228da873db72aa28109d1797

keyCertSign must check only in [check_ca(const X509 *x)](https://github.com/openssl/openssl/blob/master/crypto/x509v3/v3_purp.c#L503)

**Comment by vdukhovni** [comment]
There are multiple ways to ensure that a certificate is not inadvertently misused as a CA:

* Set CA=false
* Set subject key identifier, but not authority key identifer.
* Set key usage bits incompatible with being a CA

You seem to have hit 2 out of 3.  Don't do that if you want the certificate to be a trust anchor.  If you just want to allow trusted (found in CAfile or CApath) leaf certs to match themselves (self-signed or otherwise), then with OpenSSL 1.0.2 or later you can set `X509_V_FLAG_PARTIAL_CHAIN` and it won't matter whether the certificate is self-signed or not.

**Comment by algv** [comment]
Please, you can help me find it in RFC?
I don't understand why need check keyCertSign in [cert_self_signed(X509 *x)](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2j/crypto/x509/x509_vfy.c#L154)

**Comment by algv** [comment]
https://github.com/openssl/openssl/issues/1418
