### ISSUE TITLE
Mismatch text format output of x509 certificate attribute from Openssl API and Openssl command

### ISSUE THREAD

**Issue by AnilChoudhury-Eaton** [openssl/openssl#21263]
Hello,

We are updating our openssl version from 1.1.1q to 3.0.8.
We are observing one mismatch output issue with 3.0.8 version for getting text format for x509 RSA certificate using API and command.

in 1.1.1q version gives the same output for command ( openssl x509 -text -noout) and API (X509_print_fp()) but 3.0.8 not.
In the 3.0.8 version, the API call gives "Public-Key" as a key whereas the command call gives "RSA Public-Key". The command works as the old version but the API changed. But both output should be consistent. This is causing our automation failure.

What changes can be done for this?

#### Using Openssl Command:
'''
~ $ openssl x509 -text -noout -in /flash/certificates/pki1/server/059a0016.0
'''
**Output:**
> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number:
>             ba:86:c6:d5:dc:d8:e5:42
>         Signature Algorithm: sha256WithRSAEncryption
>         Issuer: C = US, ST = NC, L = Raleigh, O = Eaton Corporation, OU = Electrical Division, CN = PowerXpert-52-54-00-12-34-02
>         Validity
>             Not Before: Jun 21 00:00:00 2023 GMT
>             Not After : Jun 17 00:00:00 2038 GMT
>         Subject: C = US, ST = NC, L = Raleigh, O = Eaton Corporation, OU = Electrical Division, CN = PowerXpert-52-54-00-12-34-02
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 **RSA Public-Key**: (2048 bit)
> 

#### Using Openssl API
'''
void Details( X509_T &cert)
{
	FILE *fp_details = fopen( "/tmp/details", "w" );
	X509_print_fp( fp_details, *cert );
	fclose( fp_details );
}
'''
**Output:**
> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number:
>             ba:86:c6:d5:dc:d8:e5:42
>         Signature Algorithm: sha256WithRSAEncryption
>         Issuer: C=US, ST=NC, L=Raleigh, O=Eaton Corporation, OU=Electrical Division, CN=PowerXpert-52-54-00-12-34-02
>         Validity
>             Not Before: Jun 21 00:00:00 2023 GMT
>             Not After : Jun 17 00:00:00 2038 GMT
>         Subject: C=US, ST=NC, L=Raleigh, O=Eaton Corporation, OU=Electrical Division, CN=PowerXpert-52-54-00-12-34-02
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 **RSA Public-Key**: (2048 bit)

#### Using Openssl Command:
'''
~ $ openssl x509 -text -noout -in /flash/certificates/pki1/server/059a0016.0
'''
**Output:**
> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number:
>             ba:86:c6:d5:dc:d8:e5:42
>         Signature Algorithm: sha256WithRSAEncryption
>         Issuer: C = US, ST = NC, L = Raleigh, O = Eaton Corporation, OU = Electrical Division, CN = PowerXpert-52-54-00-12-34-02
>         Validity
>             Not Before: Jun 21 00:00:00 2023 GMT
>             Not After : Jun 17 00:00:00 2038 GMT
>         Subject: C = US, ST = NC, L = Raleigh, O = Eaton Corporation, OU = Electrical Division, CN = PowerXpert-52-54-00-12-34-02
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 **RSA Public-Key**: (2048 bit)
> 

#### Using Openssl API
'''
void Details( X509_T &cert)
{
	FILE *fp_details = fopen( "/tmp/details", "w" );
	X509_print_fp( fp_details, *cert );
	fclose( fp_details );
}
'''
**Output:**
> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number:
>             ba:86:c6:d5:dc:d8:e5:42
>         Signature Algorithm: sha256WithRSAEncryption
>         Issuer: C=US, ST=NC, L=Raleigh, O=Eaton Corporation, OU=Electrical Division, CN=PowerXpert-52-54-00-12-34-02
>         Validity
>             Not Before: Jun 21 00:00:00 2023 GMT
>             Not After : Jun 17 00:00:00 2038 GMT
>         Subject: C=US, ST=NC, L=Raleigh, O=Eaton Corporation, OU=Electrical Division, CN=PowerXpert-52-54-00-12-34-02
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 **Public-Key**: (2048 bit)

**Comment by t8m** [comment]
This is not going to be changed. It is already mentioned in the migration guide:

       The print format has cosmetic changes for some functions
       
       The output from numerous "printing" functions such as
       X509_signature_print(3), X509_print_ex(3), X509_CRL_print_ex(3), and
       other similar functions has been amended such that there may be
       cosmetic differences between the output observed in 1.1.1 and 3.0. This
       also applies to the -text output from the openssl x509 and openssl crl
       applications.
