### ISSUE TITLE
Postfix (client side), OpenSSL 1.1.1 to 3.0.9, TLS handshake always fails

### ISSUE THREAD

**Issue by PyBonnetainNesterenko** [openssl/openssl#21276]
Gentoo recently stabilized OpenSSL 3.0.9, we upgraded, and now no TLS connection can be made from our OpenSSL3'ed mail clients (posfix) to our mail server (postfix, whatever OpenSSL version).

Client side, postfix error messages (smtp_tls_log_level 2) are

initializing the client-side TLS engine
setting up TLS connection to XXXX:587
XXXX:587: TLS cipher list "aNULL:-aNULL:HIGH:@STRENGTH:!aNULL"
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS read server hello
XXXX:587: depth=2 verify=1 subject=/C=FR/ST=AAA/L=BBB/O=CCC/OU=Autorit\xC3\xA9 de certification/CN=ZZZ
XXXX:587: depth=1 verify=1 subject=/C=FR/ST=AAA/L=BBB/O=CCC/OU=OU1/CN=YYY
XXXX:587: depth=0 verify=1 subject=/C=FR/ST=AAA/L=BBB/O=CCC/OU=OU2/CN=TTT
SSL_connect:SSLv3/TLS read server certificate
SSL3 alert write:fatal:internal error
SSL_connect:error in error
SSL_connect error to XXX:587: -1
warning: TLS library problem: error:0A00014D:SSL routines::legacy sigalg disallowed or unsupported:../openssl-3.0.9/ssl/statem/statem_clnt.c:2254:

Server side, error log (smtpd_tls_log_level 2) is

setting up TLS connection from BBBB
BBBB TLS cipher list "aNULL:-aNULL:HIGH:MEDIUM:+RC4:@STRENGTH"
SSL_accept:before SSL initialization
SSL_accept:before SSL initialization
SSL_accept:SSLv3/TLS read client hello
SSL_accept:SSLv3/TLS write server hello
SSL_accept:SSLv3/TLS write certificate
SSL_accept:SSLv3/TLS write key exchange
SSL_accept:SSLv3/TLS write server done
SSL3 alert read:fatal:internal error
SSL_accept:error in error
SSL_accept error from BBBB: -1
warning: TLS library problem: error:0A000438:SSL routines::tlsv1 alert internal error:../openssl-3.0.9/ssl/record/rec_layer_s3.c:1586:SSL alert number 80:
lost connection after STARTTLS from BBBB

Downgrading OpenSSL to 1.1.1 on the clients solve this problem (whatever the version on the server).

**Note** this could be the same bug/problem as #21254 with different tools/environments

Attached a tcpdump of the handshake.

[postfix.zip](https://github.com/openssl/openssl/files/11857107/postfix.zip)

**Comment by preveen-stack** [comment]
> SL_connect:SSLv3/TLS read server certificate
SSL3 alert write:fatal:internal error
SSL_connect:error in error
SSL_connect error to XXX:587: -1
warning: TLS library problem: error:0A00014D:SSL routines::legacy sigalg disallowed or unsupported:../openssl-3.0.9/ssl/statem/statem_clnt.c:2254

Looks like the  algorithm used for signing server certificate is not supported by openssl 3.0.9

**Comment by PyBonnetainNesterenko** [comment]
> Looks like the algorithm used for signing server certificate is not supported by openssl 3.0.9

We are using sha256WithRSAEncryption, shouldn't it be okay ?

`Certificate:`
 `   Data:`
`        Version: 3 (0x2)`
`         Serial Number: something `
`        Signature Algorithm: sha256WithRSAEncryption`

**Comment by preveen-stack** [comment]
`openssl x509 -in certificate.pem -text`
can you check

**Comment by PyBonnetainNesterenko** [comment]
> `openssl x509 -in certificate.pem -text`

Removing « useless » stuff, we get 

`Signature Algorithm: sha256WithRSAEncryption`
`            Public Key Algorithm: rsaEncryption               `
`Signature Algorithm: sha256WithRSAEncryption                `

**Comment by preveen-stack** [comment]
Ok. Perhaps somebody can analyze the tcpdump you shared.

**Comment by paulidale** [comment]
Are you loading the legacy provider?

**Comment by PyBonnetainNesterenko** [comment]
> Are you loading the legacy provider?

How can I check that (and test if it solves the problem) ?

**Comment by mattcaswell** [comment]
> Are you loading the legacy provider?

This issue isn't related to the legacy provider.

The problem is that the server has negotiated TLSv1.0 which is deprecated by IETF and no longer considered secure. The ServerKeyExchange message sent by the server is signed using a legacy signature algorithm. In TLSv1.0 this was essentially an RSA signature of a composite MD5 and SHA1 hash.

The correct solution to this problem is to upgrade the server so that it uses a secure TLS version. Assuming that this isn't possible, then you can resolve it by lowering the default security level on the client side to allow MD5/SHA1. I don't know how you do that in postfix, but in many applications which accept an OpenSSL ciphersuite list you can add "@SECLEVEL=0" into the ciphersuite list to reduce the default security level to 0.

**Comment by PyBonnetainNesterenko** [comment]
> The problem is that the server has negotiated TLSv1.0 which is deprecated by IETF and no longer considered secure. The ServerKeyExchange message sent by the server is signed using a legacy signature algorithm. In TLSv1.0 this was essentially an RSA signature of a composite MD5 and SHA1 hash.
> 
> The correct solution to this problem is to upgrade the server so that it uses a secure TLS version. Assuming that this isn't possible, then you can resolve it by lowering the default security level on the client side to allow MD5/SHA1. I don't know how you do that in postfix, but in many applications which accept an OpenSSL ciphersuite list you can add "@SECLEVEL=0" into the ciphersuite list to reduce the default security level to 0.

Just for the sake of completeness, the problem was indeed in our configurations, not in OpenSSL. Clients were configured with improper/invalid cipher suites. We changed that (to TLS v1.2 at least), and we are now slowly upgrading our clients and servers to OpenSSL 3.

Thanks for the help.
