### ISSUE TITLE
bio_meth allocates a reference counter (lock) and never frees it

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#21277]
This code in bio_meth.c allocates a lock on first use but never frees it:

https://github.com/openssl/openssl/blob/a9e6100bc98439ca787aa1fce541550ad1ff3e84/crypto/bio/bio_meth.c#L13-L35

It's also abusing the reference counter and should be changed to use atomic operations instead.

**Comment by mattcaswell** [comment]
> This code in bio_meth.c allocates a lock on first use but never frees it:

It gets freed here:

https://github.com/openssl/openssl/blob/810f7dc1c7cc5441097b398f753e33652848a4cc/crypto/bio/bio_lib.c#L951-L960

It *is* quite confusing that this free occurs in a completely different file to where it is allocated.
