### ISSUE TITLE
After install of 1.1.1u still showing the 1.0.2k

### ISSUE THREAD

**Issue by bingsta2602** [openssl/openssl#21273]
The install 1.1.1u went fine, but when id the bin location and executing the openssl version command coming up with the previous version of 1.0.2k. there was a couple times it would error openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No su
history of commands:
  854  yum -y remove openssl openssl-devel
  855  openssl version
  856  yum -y groupinstall "Development Tools"
  857  ./config
  858  make
  859  make test
  860  make install
  861  openssl version
  862  mv /usr/bin/openssl /root/
  863  ln -s /usr/local/bin/openssl /bin/openssl
  864  openssl version
  865  ls .usr/local/bin
  866  ls /usr/local/bin
  867  ls /usr/local/bin/openssl
  868  ls /bin/
  869  ls /bin/openssl
  870  find / -namee openssl
  871  find / -name openssl
  872  ls /usr/local/bin/openssl
  873  ls /usr/local/bin/openssl/usr/local/bin/openssl
  874  ls /usr/local/bin/openssl
  875  ls /usr/local/bin/
  876  ls /bin
  877  ls /bin/openssl
  878  ls /usr/local
  879  ls /usr/local/bin
  880  ls /usr/local/bin/openssl
  881  cd /usr/local/src
  882  tar -zxfv openssl-1.1.1u.tar.gz
  883  ls
  884  tar -zxf openssl-1.1.1u.tar.gz
  885  cd openssl-1.1.1u
  886  ./config
  887  make
  888  make install
  889  ls /usr/local/bin/openssl
  890  openssl version
  891  mv /usr/bin/openssl /root/
  892  ln -s /usr/local/bin/openssl /bin/openssl
  893  openssl version
  894  ln -s /usr/local/bin/openssl usr/bin/openssl
  895  make install
  896  open ssl
  897  openssl version
  898  ls /usr/local/ssl/bin/openssl
  899  ls /usr/local/ssl/
  900  ls /usr/local/
  901  ls /usr/local/bin
  902  ls /usr/local/bin/openssl
  903  ls /usr/local/bin/openssl
  904  ln -s /usr/local/bin/openssl usr/bin/openssl
  905  ls /bin/openssl
  906  rm -rf /bin/openssl
  907  ln -s /usr/local/bin/openssl bin/openssl
  908  ln -s /usr/local/bin/openssl /bin/openssl
  909  openssl version
  910  ./config
  911  make
  912  make test
  913  make install
  914  ls /usr/local
  915  ls /usr/local/bin
  916  ls /usr/local/bin/openssl
  917  ls /usr/local/
  918  ls /usr/local/ssl
  919  ls /usr/local/sbin
  920  ls /home/eric.eng/openssl-1.1.1u
  921  ls /home/eric.eng/openssl-1.1.1u/apps
  922  ls /home/eric.eng/openssl-1.1.1u/ssl
  923  ls /usr/local
  924  ls /usr/local/src
  925  ls /usr/local/src/openssl-1.1.1u
  926  ln -s /usr/local/bin/openssl /bin/openssl
  927  ln -s /usr/local/bin/openssl /usr/bin/openssl
  928  rm -rf /bin/openssl
  929  ln -s /usr/local/bin/openssl /bin/openssl
  930  openssl version
  931  rm -rf usr/bin/openssl
  932  ln -s /usr/local/bin/openssl usr/bin/openssl
  933  ln -s /usr/local/bin/openssl /usr/bin/openssl
  934  rm -rf /usr/bin/openssl
  935  ln -s /usr/local/bin/openssl /usr/bin/openssl
  936  openssl
  937  export gencert=eps.metrics.nosql.mcboss.usmc.mil
  938  openssl genrsa -out $gencert/$gencert.key 2048
  939  find / -name libssl.so.1.1
  940  ls/usr/local/lib64/libssl.so.1.1
  941  ls /usr/local/lib64/libssl.so.1.1
  942  yum install openssl
  943  openssl version
  944  ls /bin/openssl
  945  ./config
  946  make
  947  make install
  948  openssl version
  949  ls /root
  950  cp /root/openssl /usr/bin/openssl
  951  openssl
  952  rm /usr/bin/openssl
  953  ln -s /usr/local/bin/openssl /usr/bin/openssl
  954  openssl version
  955  rm /bin/openssl
  956  ln -s /usr/local/bin/openssl /bin/openssl
  957  openssl version
  958  find -name openssl
  959  find / -name openssl
  960  rm /root/openssl
  961  openssl version
[eric.eng@s-appn-web-301 ~]$ which openssl
/usr/local/bin/openssl
[eric.eng@s-appn-web-301 ~]$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

Pearl Dump:
[root@s-appn-web-301 openssl-1.1.1u]# perl configdata.pm --dump

Command line (with current working directory = .):

    /usr/bin/perl ./Configure linux-x86_64

Perl information:

    /usr/bin/perl
    5.16.3 for x86_64-linux-thread-multi

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [too-old-kernel] OPENSSL_NO_AFALGENG
    asan                    [default]        OPENSSL_NO_ASAN
    buildtest-c++           [default]
    crypto-mdebug           [default]        OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]        OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]        OPENSSL_NO_EGD
    external-tests          [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]        OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]        OPENSSL_NO_HEARTBEATS
    md2                     [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]        OPENSSL_NO_MSAN
    rc5                     [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]        OPENSSL_NO_SCTP
    ssl-trace               [default]        OPENSSL_NO_SSL_TRACE
    ubsan                   [default]        OPENSSL_NO_UBSAN
    unit-test               [default]        OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]
    zlib-dynamic            [default]
    ssl3                    [default]        OPENSSL_NO_SSL3
    ssl3-method             [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    CXX => "g++",
    CXXFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c vpaes-x86_64.s aesni-x86_64.s aesni-sha1-x86_64.s aesni-sha256-x86_64.s aesni-mb-x86_64.s",
    aes_obj => "aes_core.o aes_cbc.o vpaes-x86_64.o aesni-x86_64.o aesni-sha1-x86_64.o aesni-sha256-x86_64.o aesni-mb-x86_64.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "asm/x86_64-gcc.c x86_64-mont.s x86_64-mont5.s x86_64-gf2m.s rsaz_exp.c rsaz-x86_64.s rsaz-avx2.s",
    bn_obj => "asm/x86_64-gcc.o x86_64-mont.o x86_64-mont5.o x86_64-gf2m.o rsaz_exp.o rsaz-x86_64.o rsaz-avx2.o",
    bn_ops => "SIXTY_FOUR_BIT_LONG",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-pthread -m64",
    chacha_asm_src => "chacha-x86_64.s",
    chacha_obj => "chacha-x86_64.o",
    cmll_asm_src => "cmll-x86_64.s cmll_misc.c",
    cmll_obj => "cmll-x86_64.o cmll_misc.o",
    cppflags => "",
    cpuid_asm_src => "x86_64cpuid.s",
    cpuid_obj => "x86_64cpuid.o",
    cxxflags => "-std=c++11 -pthread -m64",
    defines => [  ],
    des_asm_src => "des_enc.c fcrypt_b.c",
    des_obj => "des_enc.o fcrypt_b.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-x86_64.s x25519-x86_64.s",
    ec_obj => "ecp_nistz256.o ecp_nistz256-x86_64.o x25519-x86_64.o",
    enable => [ "afalgeng" ],
    ex_libs => "-ldl -pthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600-x86_64.s",
    keccak1600_obj => "keccak1600-x86_64.o",
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DOPENSSL_USE_NODELETE -DL_ENDIAN",
    lib_defines => [  ],
    md5_asm_src => "md5-x86_64.s",
    md5_obj => "md5-x86_64.o",
    modes_asm_src => "ghash-x86_64.s aesni-gcm-x86_64.s",
    modes_obj => "ghash-x86_64.o aesni-gcm-x86_64.o",
    module_cflags => "-fPIC",
    module_cxxflags => "",
    module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    multilib => "64",
    padlock_asm_src => "e_padlock-x86_64.s",
    padlock_obj => "e_padlock-x86_64.o",
    perlasm_scheme => "elf",
    poly1305_asm_src => "poly1305-x86_64.s",
    poly1305_obj => "poly1305-x86_64.o",
    rc4_asm_src => "rc4-x86_64.s rc4-md5-x86_64.s",
    rc4_obj => "rc4-x86_64.o rc4-md5-x86_64.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    sha1_asm_src => "sha1-x86_64.s sha256-x86_64.s sha512-x86_64.s sha1-mb-x86_64.s sha256-mb-x86_64.s",
    sha1_obj => "sha1-x86_64.o sha256-x86_64.o sha512-x86_64.o sha1-mb-x86_64.o sha256-mb-x86_64.o",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,--version-script=",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-soname=",
    shared_target => "linux-shared",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp-x86_64.s",
    wp_obj => "wp-x86_64.o",

Recorded environment:

    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = ar
    ARFLAGS         = r
    CC              = gcc
    CFLAGS          = -Wall -O3
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXX             = g++
    CXXFLAGS        = -Wall -O3
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          =
    PERL            = /usr/bin/perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl

**Comment by t8m** [comment]
I assume the 1.0.2k is the one from the system (/usr/lib /usr/lib64) where the 1.1.1 is installed into /usr/local/lib or /usr/local/lib64 and respectively for binaries.

**Comment by bingsta2602** [comment]
I'm assuming that I will have to use something like this to move the libraries:
sudo tee /etc/profile.d/openssl.sh<<EOF
export PATH=/usr/local/openssl/bin:\$PATH
export LD_LIBRARY_PATH=/usr/local/openssl/lib:\$LD_LIBRARY_PATH
EOF

**Comment by t8m** [comment]
It shouldn't be necessary to set the LD_LIBRARY_PATH variable if the dynamic linker searches the /usr/local/lib64. 1.1.1 and 1.0.2 should have different SONAME so there should be no conflict.

**Comment by imation618** [comment]
After successfully installing 1.1.1v, and cmd openssl version show me the correct version. But when I do ssh -v, it show openssl 1.0.2k-fips.  The file in lib64/lib64crypto.so.1.02.k still exist and the scan still pick it up.  I do fix it?

**Comment by t8m** [comment]
This is basically a duplicate of the discussion issue #21776

It is virtually impossible to replace the system 1.0.2k openssl library with 1.1.1 version. You can install a new version, but then you have to build all the software that you need to use the new version against that version, the system software packages will be always linked against the 1.0.2k version and use that version.

To summarize, unless you really know what you're doing and there is only one or two services that you need to be using the current OpenSSL version that you can rebuild yourself, either use properly supported OS version from a vendor or upgrade to a never version of CentOS.
