### ISSUE TITLE
OpenSSL version 3.0.8 download link is missing from OpenSSL website

### ISSUE THREAD

**Issue by nagu1137** [openssl/openssl#21289]
Hi Team,

we are planning to upgrade open SSL version 3.0.8 from 1.0.2 Q.

As per the information in the open SSL website 3.0.8 is fips validated so we decided to go with it. Bu the link to source code is missing from https://www.openssl.org/source/old/3.0/

please let us know if this version is not a stable version or how to get the source code for the same.

**Comment by mattcaswell** [comment]
It is available from this link:

https://www.openssl.org/source/old/3.0/openssl-3.0.8.tar.gz

Also from here:

https://github.com/openssl/openssl/releases/tag/openssl-3.0.8

It looks like the "old" page has not regenerated the list of available old releases

**Comment by t8m** [comment]
https://github.com/openssl/web/pull/405 might fix it @mattcaswell @hlandau @paulidale please approve

**Comment by t8m** [comment]
Fixed now. However changing the Makefile triggered the regeneration anyway, so we need to hope the fix was right and the next time we release the index will be regenerated properly.
