### ISSUE TITLE
Is there a way to disable TLS Secure Renegotiation

### ISSUE THREAD

**Issue by ranierimazili** [openssl/openssl#21285]
Hello,

I need to make a test consuming and api with TLS Secure Renegotiation completely disabled.
For this I've configured the apache httpd 2 server with only TLS 1.2 enabled and I think it rely on openssl to discover if TLS Secure Renegotiation is available or not.
I've tried to edit the openssl.cnf file adding the following properties:

```
[system_default_sect]
Options = SSL_OP_NO_RENEGOTIATION
```

After this I've restarted the apache http server and then made the test with the command:
```
openssl s_client -connect localhost:443 -tls1_2
```

Even after this setup, the output of the command above still shows that Secure Renegotiation is enabled:
```
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: D9A880F24D13040E379D7BE35AFEFBDF5FE09CE408F0BE71195D1B441DC23098
    Session-ID-ctx:
    Master-Key: 03CB453428DE0DA3D537A56DBCF523AA520E75B20F2797EFDB99DCF2DF3304FD72F51C041C0523300C88887CCABD4B71
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1687810869
    Timeout   : 7200 (sec)
    Verify return code: 18 (self-signed certificate)
    Extended master secret: yes
---
```

Is there a effective way to disable it?

**Comment by paulidale** [comment]
I think you should be specifying `NoRenegotiation` instead of `SSL_OP_NO_RENEGOTIATION` in the configuration.
This is [documented](https://www.openssl.org/docs/man3.0/man3/SSL_CONF_cmd.html#Options) but not in the most obvious place.

**Comment by mattcaswell** [comment]
You cannot disable secure renegotiation. OpenSSL will always attempt to negotiate it. You can only influence what happens if the peer does not support it, or disable renegotiation completely. Even disabling renegotiation completely does not prevent the client and server from agreeing secure renegotiation support - it just prevents renegotiation from actually taking place.
