### ISSUE TITLE
Impossible to clear the label with EVP_PKEY_CTX_set0_rsa_oaep_label()

### ISSUE THREAD

**Issue by hxtzzz** [openssl/openssl#21288]
The version of OpenSSL is 3.0.7 and the 3.0 doc shows that 
'EVP_PKEY_CTX_set0_rsa_oaep_label() sets the RSA OAEP label to binary data label and its length in bytes to len. If label is NULL or len is 0, the label is cleared. The library takes ownership of the label so the caller should not free the original memory pointed to by label. The padding mode must have been set to RSA_PKCS1_OAEP_PADDING.'
But when I use the input of NULL or 0 length, the return value is 0 and it seems that it is same as the wrong use situation. 
Shoud it return 1 instead of 0 as well as the common return value?

**Comment by t8m** [comment]
Is the return value 0 for non-NULL input label pointer but with 0 length?

**Comment by hxtzzz** [comment]
Yes, when the input value is non-null and 0 length, the return value is still 0.

**Comment by hxtzzz** [comment]
> Is the return value 0 for non-NULL input label pointer but with 0 length?

Yes, when the input value is non-null and 0 length, the return value is still 0.

**Comment by t8m** [comment]
This should be now fixed.
