### ISSUE TITLE
x509_vfy.h(1.0.2q) is now x509_vfy.h.in in 3.0.8

### ISSUE THREAD

**Issue by nagu1137** [openssl/openssl#21294]
Hi Team,

we are using few APIs from x509_vfy.h and in the 3.0.8 version this .h file is renamed to x509_vfy.h.in.

how can we use the API from this file now?

**Comment by mattcaswell** [comment]
You need to configure and build OpenSSL before you can use the header files. The *.h.in files are template files that are used to generate the .h files.

**Comment by nagu1137** [comment]
Thank you so much for the quick response.

we are doing analysis related APIs which are deprecated from 1.0.2 to 3.0.8 with respect to our application.

So if the API is present in the .in file means we can consider that function API is not deprecated in the latest version right?

For example:

X509_STORE_add_lookup is present in x509_vfy.h(1.0.2q)

X509_STORE_add_lookup is present in x509_vfy.h.in(3.0.8)

can we consider above function is present in 3.0.8 and not deprecated.

**Comment by paulidale** [comment]
No.  Deprecated functions are still present in the header files, they are flagged with deprecation macros.
Look for DEPRECATED.

**Comment by mattcaswell** [comment]
Here are some examples of deprecations in the header files:

https://github.com/openssl/openssl/blob/f2ade1527b44848081c8d16c9acdd9acc8847c6e/include/openssl/x509.h.in#L375-L382

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
