### ISSUE TITLE
RUN_ONCE*() always returns 0 during UEFI PEI phase

### ISSUE THREAD

**Issue by liyi77** [openssl/openssl#21304]
During the UEFI PEI (Pre-EFI Initialization) phase, the BIOS runs on the ROM (in-place), which means that all global variables are read-only during the PEI phase.

After the provider is introduced in 3.0, most crypto APIs will eventually call ```RUN_ONCE*()``` related functions (such as ```crypto_init()```). This causes the crypto API to fail in the PEI phase.

Are these ```RUN_ONCE*()``` function used in multi-threaded situation or common situation? UEFI BIOS is a single-threaded program, will there be security risks if we remove the single-shot protection?

https://github.com/openssl/openssl/blob/9f0cc5d09a89731f1cd9b111f12aa3ac9667b6a0/include/internal/thread_once.h#L37-L44

https://github.com/openssl/openssl/blob/9f0cc5d09a89731f1cd9b111f12aa3ac9667b6a0/include/internal/thread_once.h#L129-L130

**Comment by paulidale** [comment]
They are mostly but not completely about threading.  The set up various state too.

Can you modify the linker command line or script to put the global variables into RAM?
I envisage a world of pain if this isn't possible.

**Comment by mattcaswell** [comment]
> After the provider is introduced in 3.0, most crypto APIs will eventually call RUN_ONCE*() related functions (such as crypto_init()). This causes the crypto API to fail in the PEI phase.

I don't think this is much to do with the introduction of providers. RUN_ONCE has been a thing in OpenSSL since 1.1.0. So, I'm not really sure what has changed for UEFI in 3.0.

> Are these RUN_ONCE*() function used in multi-threaded situation or common situation?

They do once only initialisation of various global state. That applies whether or not the application is using threads or not. In a "no-threads" build of OpenSSL the `RUN_ONCE` implementation ends up being quite simple:

https://github.com/openssl/openssl/blob/f2ade1527b44848081c8d16c9acdd9acc8847c6e/crypto/threads_none.c#L65-L74

**Comment by liyi77** [comment]
> I don't think this is much to do with the introduction of providers. RUN_ONCE has been a thing in OpenSSL since 1.1.0. So, I'm not really sure what has changed for UEFI in 3.0.

Yes, these 1.1.1 exist. But in 1.1.1, some legacy API codes will not call here, such as hash, hmac, aes, hkdf... Only complex EVP implementations will call ```RUN_ONCE()```, such as Pkcs7.

But after 3.0 we turned to the provider, hmac, hkdf (UEFI used in the PEI) and others deleted the legacy implementation, and the new implementation will eventually call ```RUN_ONCE()```. 

>They do once only initialisation of various global state. That applies whether or not the application is using threads or not. In a "no-threads" build of OpenSSL the RUN_ONCE implementation ends up being quite simple:

Yes, RUN_ONCE always return global ```init##_ossl_ret_``` whether or not the application is using threads. Got it, I take this to mean that there is no way to avoid globle variables here :( .

**Comment by mattcaswell** [comment]
> Yes, RUN_ONCE always return global init##_ossl_ret_ whether or not the application is using threads. Got it, I take this to mean that there is no way to avoid globle variables here :( .

Correct

**Comment by liyi77** [comment]
> They are mostly but not completely about threading. The set up various state too.
> 
> Can you modify the linker command line or script to put the global variables into RAM? I envisage a world of pain if this isn't possible.

This is very difficult due to the design of the PEI module... I will try, thanks
