### ISSUE TITLE
Disable UI manually with external OpenSSL

### ISSUE THREAD

**Issue by KovalevVasiliy** [openssl/openssl#21303]
I'm building my project with external OpenSSL. How can I disable UI interactions? Because now OpenSSL tries to read phrase from the console.

I've tried to use UI_set_default_method(UI_null()), but it doesn't work.

**Comment by t8m** [comment]
It depends on what APIs are you using that invoke the prompt.

**Comment by KovalevVasiliy** [comment]
> It depends on what APIs are you using that invoke the prompt.

I'm trying to call PEM_read_bio_PrivateKey() with invalid or empty password. And then OpenSSL starts the prompt.
Could you help me to find out the way how to aboid it? Is there possible way to disable all UI?

@t8m

**Comment by KovalevVasiliy** [comment]
I've found, what I can set a callback. Is it a good approach? How can I disable UI for all places?
```
int passphrase_callback(char *, int , int , void *) {
    return -1;
}
```

```
if (isPrivate) {
    pkey = PEM_read_bio_PrivateKey(in.get(), nullptr, passphrase_callback, const_cast<char*>(passData));
} else {
    pkey = PEM_read_bio_PUBKEY(in.get(), nullptr, passphrase_callback, const_cast<char*>(passData));
}
```

Should I also update writing?

```
if (isPrivate) {
    pkey = PEM_read_bio_PrivateKey(keybio.get(), nullptr, 0, nullptr);
} else {
    pkey = PEM_read_bio_PUBKEY(keybio.get(), nullptr, 0, nullptr);
}
```

@t8m

**Comment by t8m** [comment]
Yes, for PEM reading functions that have a callback this is the right solution.

Similarly for PEM writing. If you want to write something that is protected by a password you need the callback to supply the password of course.

**Comment by KovalevVasiliy** [comment]
> Yes, for PEM reading functions that have a callback this is the right solution.
> 
> Similarly for PEM writing. If you want to write something that is protected by a password you need the callback to supply the password of course.

How can I disable UI for all places?

**Comment by KovalevVasiliy** [comment]
> Yes, for PEM reading functions that have a callback this is the right solution.
> 
> Similarly for PEM writing. If you want to write something that is protected by a password you need the callback to supply the password of course.

I've tried to do the same for writing, but got an error:

`PEM_write_bio_PrivateKey(out.get(), &pkey, cipher, nullptr, 0, passphraseCallback, const_cast<char*>(passData));`

write has been failed: error:1C80009F:Provider routines::unable to get passphrase

**Comment by t8m** [comment]
The callback needs to supply the passphrase.

**Comment by t8m** [comment]
> > Yes, for PEM reading functions that have a callback this is the right solution.
> > Similarly for PEM writing. If you want to write something that is protected by a password you need the callback to supply the password of course.
> 
> How can I disable UI for all places?

Other than at build time (no-ui option) no.

**Comment by KovalevVasiliy** [comment]
> The callback needs to supply the passphrase.

What does it mean? I need to copy password to the input buffer or what?
