### ISSUE TITLE
Openssl 3.0 update crashing on Mac

### ISSUE THREAD

**Issue by aniljadaun** [openssl/openssl#21308]
This is in continuation to the closed issue  https://github.com/openssl/openssl/issues/21249

I am not sure what am i doing wrong here. 

As suggested by @levitte @tmshort . i moved on to use openssl with realname . 

Steps done to generate openssl libs are : 
./Configure darwin64-arm64-cc enable-fips enable-capieng --prefix=/Users/anils/openssl/arm64/dll/release --openssldir=/Users/anils/openssl/openssldir 

Similary created x86_64 libs. I used both these archs to create a universal libs as libcrypto.3.dylib and libssl.3.dylib .

I am using these libs in my project. runtime load is not working for me ...generated libs initially reference to /Users/anils/openssl/arm64/dll/release/lib/ which is --prefix path for me . I updated this rpath using install_tool_name to @rpath/libcrypto.3.dylib . 

Now i don't understand why libs are not getting loaded into my project which eventually results in crash.

Not being able to resolve this myself need help from the community.

**Comment by aniljadaun** [comment]
Incorrectly taged this as bug. :(

**Comment by tmshort** [comment]
I'm not sure how much more I'm able to help. You might need to get help from the Mac development community, as this seems to be a Mac-specific issue. It very well may be a path-related issue, specific to your application, and where you intend  to locate the libraries and application.

You mention "crash", but I'd bet there are error messages emitted by macOS that would be helpful in solving this.

**Comment by aniljadaun** [comment]
Hi  @levitte @tmshort 

Is it fine if we use a custom name for libcrypto.3.dylib and libssl.3.dylib say libcrypto_test.dylib and libssl_test.dylib . Custom name doesn't have version info . Would this be fine or is it must to be using name with version name appended ?

**Comment by tmshort** [comment]
Using version info in the library name is _STRONGLY RECOMMENDED_, especially if you are installing the libraries for general use (e.g. like what `brew` would do).

That being said, if this is your application that you're packaging, and only your application will have access to those libraries (because they're in a `.app` or something), then it doesn't really matter what you call them.
