### ISSUE TITLE
OpenSSL 3.0 FIPS Module/provider related question

### ISSUE THREAD

**Issue by prashsuv** [openssl/openssl#21313]
We download OpenSSL source from here : https://www.openssl.org/source/ and use the 3.0.x (latest one available).
We then build the openssl source code using the below steps : 
```
./Configure --prefix=/usr --openssldir=/usr/lib/ssl --libdir=lib/x86_64-linux-gnu enable-fips
make
```
We then create our own packages (libssl3, libssl-dev and openssl) for debian 10 & 11. This is because debian does not provide a FIPS enabled version of openssl 3.0 for Debian 10 & 11.

The latest OpenSSL code drop is 3.0.9 version. However, the FIPS compliant FIPS module is from 3.0.8 version as per https://www.openssl.org/source/ 

Because we use this in a FedRAMP environment, we now have to figure out how to package the fips module separately. This means, we should be able to install OpenSSL 3.0.9 but use FIPS module version 3.0.8. Is there a list of files that make up the FIPS module? Is `fips.so` the only thing in FIPS module? Or are there other header files that go along with the FIPS module?

My second question is, does OpenSSL community do any level of testing for inter-compatibility between say OpenSSL 3.0.9 code running with 3.0.8 version of FIPS module?

**Comment by paulidale** [comment]
The relevant instructions are in #20907 which hasn't been approved or merged yet.
If Debian is shipping OpenSSL 3.0, you'd be able to just install the FIPS provider from 3.0.8.

OpenSSL does do cross version testing and we expect FIPS providers from all validated 3.x releases to work with all 3.y releases.

**Comment by prashsuv** [comment]
Thank you @paulidale
