### ISSUE TITLE
"no OPENSSL_Applink" with Native builds using MinGW

### ISSUE THREAD

**Issue by pluto0327** [openssl/openssl#21323]
I decided to code with openssl and Visual Studio 2019 on Windows 11.  I followed steps from ["Native builds using MinGW"](https://github.com/openssl/openssl/blob/master/NOTES-WINDOWS.md#native-builds-using-mingw) .

I passed the "make test" and "make install". As follows
> 99-test_fuzz_bndiv.t ............... ok
99-test_fuzz_client.t .............. ok
99-test_fuzz_cmp.t ................. ok
99-test_fuzz_cms.t ................. ok
99-test_fuzz_conf.t ................ ok
99-test_fuzz_crl.t ................. ok
99-test_fuzz_ct.t .................. ok
99-test_fuzz_server.t .............. ok
99-test_fuzz_x509.t ................ ok
All tests successful.
Files=251, Tests=3186, 2027 wallclock secs ( 0.55 usr  0.58 sys + 69.08 cusr 97.81 csys = 168.02 CPU)
Result: PASS
make[1]: Leaving directory '/home/user/openssl-3.1.1/openssl-3.1.1'

And then I tried to build openssl_test.c  at "msys2 x64 command prompt"
>user@DESKTOP-EJSDMLU MINGW64 ~
$ gcc -c  openssl_test.c

>user@DESKTOP-EJSDMLU MINGW64 ~
$ gcc openssl_test.o -lcrypto -lssl

Finally, I trid to execute the binary code "a.exe". But it failed and showed the link error.
>C:\msys64\home\user>a.exe
OPENSSL_Uplink(00007FFC0A02D068,07): no OPENSSL_Applink

I guessed I may did some wrong steps or missed something.
May I know any suggestions or solutions?

**Comment by mattcaswell** [comment]
If you pass `FILE *` pointers between your application and OpenSSL on Windows then you must build and link the file applink.c into your application (found alongside the OpenSSL header files).

See:
https://www.openssl.org/docs/man3.1/man3/OPENSSL_Applink.html

**Comment by mattcaswell** [comment]
The NOTES-WINDOWS.md file that you referenced does mention this in the "Linking native applications" section - but I guess its easy to miss:

> If you link with OpenSSL .DLLs, then you're expected to include into your application code a small "shim" snippet, which provides the glue between the OpenSSL BIO layer and your compiler run-time. See also the OPENSSL_Applink manual page.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
