### ISSUE TITLE
No pointer check for NULL before it is dereferenced in evp_pkey_asn1_ctrl

### ISSUE THREAD

**Issue by nv-dmd** [openssl/openssl#21330]
OpenSSL 3.0.7

In function evp_pkey_asn1_ctrl, there is no pointer check to NULL before it is dereferenced. This function is used in functions
EVP_PKEY_set1_encoded_public_key, EVP_PKEY_get1_encoded_public_key, EVP_PKEY_get_default_digest_nid. 
Functions EVP_PKEY_set1_encoded_public_key and EVP_PKEY_get1_encoded_public_key are deprecated in OpenSSL 3.0, but function EVP_PKEY_get_default_digest_nid can be used. In EVP_PKEY_get_default_digest_nid (and other depreceted functions) can be passed NULL as the 1st argument, next this NULL pointer is passed as 1st argument in call to function evp_pkey_asn1_ctrl, where it is dereferenced.

Maybe need to add a check EVP_PKEY *pkey to NULL in a function evp_pkey_asn1_ctrl and return -2 if it equal NULL?

**Comment by nv-dmd** [comment]
What about this issuer? Can I make PR?

**Comment by t8m** [comment]
We do not do similar NULL checks in other similar functions. I am not sure this is really worth it.

**Comment by nv-dmd** [comment]
Maybe then add a check to NULL the 1st argument in the functions EVP_PKEY_set1_encoded_public_key, EVP_PKEY_get1_encoded_public_key, EVP_PKEY_get_default_digest_nid and return 0 if equal NULL?

**Comment by paulidale** [comment]
That would be okay I think.

**Comment by nv-dmd** [comment]
Sorry. I missed that this issue has already been fixed in the pull request #20294. 
Close this issue/
