### ISSUE TITLE
TLS1.0 error with no cert configuration

### ISSUE THREAD

**Issue by lucadjc** [openssl/openssl#21343]
Hello,
I’ve the following snipped code workin on OpenSsl 3.0.8 while with 3.1.1 it’s not working anymore.
Please can someone help with the correct setting? Thanks in advance

    def create_connection(self):
        try:
            self.logger.info(ssl.OPENSSL_VERSION)
            sslSocket = None
            cfg = self._cfg
            self.logger.info("Creating ssl context")
            sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
            
            self.logger.info("Setting up ciphers")
            sslContext.set_ciphers("HIGH:!DH:!aNULL")
            self.logger.info("Setting up verify mode")
            sslContext.verify_mode = (
                ssl.CERT_REQUIRED if cfg.cert is not None else ssl.CERT_NONE
            )
            if cfg.cert is not None:
                sslContext.set_ciphers("ALL:@SECLEVEL=0")
                self.logger.info("Setting up verify location: {}".format(cfg.cert))
                sslContext.load_verify_locations(cafile=cfg.cert)
                self.logger.info("Setting up load cert chain: {}".format(cfg.cert))
                sslContext.load_cert_chain(cfg.cert)
                
            else:
                self.logger.info("Cert is empty, skipping verification")
                sslContext.check_hostname = False
                
            self.logger.info("Wrapping socket")
            sslSocket = sslContext.wrap_socket(
                socket(AF_INET, SOCK_STREAM), server_hostname=cfg.host
            )
            self.logger.info(
                "Socket wrapped: {}".format(True if sslSocket is not None else False)
            )

            if sslSocket is not None:
                self.logger.info("Connecting with {}:{}".format(cfg.host, cfg.port))
                sslSocket.connect((cfg.host, cfg.port))
                # sslSocket.setblocking(0)
                self.handle_socket_response(sslSocket)
            else:
                self.logger.info("Wrapping socket failed")
        except:
            self.logger.error(
                "Error: {}".format(traceback.format_exc())
            )

**Comment by vdukhovni** [comment]
* It is not clear why you disable peer certificate verification when `cfg.cert` is not set.
    - Also unclear whether this is a client EE-cert file or a trust anchor CA cert file.
    - Seems to be used for both, but you probably don't want to conflate the two.
* Specifically to your issue, it seems that when `cfg.cert` is not set, you don't call:
```
sslContext.set_ciphers("ALL:@SECLEVEL=0")
```
And this is likely now required for `TLSv1` (no longer enabled at security level 1) which it seems you're forcing for some reason as the only (rather than minimum) protocol version.

Bottom line, the issue seems be substantially self-inflicted.  The code you show makes multiple poor choices. Find and use a well tested, widely used, reputable high-level TLS connection setup API, and avoid low-level tweaks which even when well intentioned are often counterproductive.

**Comment by lucadjc** [comment]
Ciao Paulidale, 
The communication is established with very old Samsung air conditioner where only this old protocol and cypher suite is enabled. 
this snippet was working with previous OpenSsl 3.0.8 version, which checks/changes do you suggest to apply?

**Comment by mattcaswell** [comment]
> it’s not working anymore.

You need to be more explicit about what exactly is not working any more, and whether you get any errors.

As @vdukhovni points out you don't call `sslContext.set_ciphers("ALL:@SECLEVEL=0")` in the `cfg.cert` is not set case. This is likely to be required since TLSv1.0 does not work unless SECLEVEL is 0. Although, AFAIK, I don't think this changed between 3.0 and 3.1 so its not clear why it worked for you before.

**Comment by vdukhovni** [comment]
There is some observable difference in the failure mode with @SECLEVEL=1 between OpenSSL 3.0 and 3.1:
```
$ OpenSSL_3.0/bin/openssl s_client -brief -cipher 'ALL:@SECLEVEL=1' -tls1 ...
00D66D0E01000000:error:0A00014D:SSL routines:tls_process_key_exchange:legacy sigalg disallowed or unsupported:ssl/statem/statem_clnt.c:2255:

$ OpenSSL_3.1/bin/openssl s_client -brief -cipher 'ALL:@SECLEVEL=1' -tls1 ...
00661F1901000000:error:0A0000BF:SSL routines:tls_setup_handshake:no protocols available:../openssl/ssl/statem/statem_lib.c:104:
```
Both fail, but 3.1 fails earlier/harder.
Both 3.0 and 3.1 succeed with `@SECLEVEL=0`:
```
$ OpenSSL_3.0/bin/openssl s_client -brief -cipher 'ALL:@SECLEVEL=0' -tls1 ...
CONNECTION ESTABLISHED
Protocol version: TLSv1
Ciphersuite: AECDH-AES256-SHA
No peer certificate
Supported Elliptic Curve Point Formats: uncompressed:ansiX962_compressed_prime:ansiX962_compressed_char2
Server Temp Key: X25519, 253 bits

$ OpenSSL_3.1/bin/openssl s_client -brief -cipher 'ALL:@SECLEVEL=0' -tls1 ...
CONNECTION ESTABLISHED
Protocol version: TLSv1
Ciphersuite: AECDH-AES256-SHA
No peer certificate
Supported Elliptic Curve Point Formats: uncompressed:ansiX962_compressed_prime:ansiX962_compressed_char2
Server Temp Key: X25519, 253 bits
```

**Comment by t8m** [comment]
Yes, in 3.1 we explicitly disable TLS < 1.2 in seclevel > 0. Where in 3.0 it was disabled just implicitly via disallowing SHA1.

**Comment by vdukhovni** [comment]
Yes, the `NEWS` file notes the change:
```
### Major changes between OpenSSL 3.0 and OpenSSL 3.1.0 [14 Mar 2023]

  * SSL 3, TLS 1.0, TLS 1.1, and DTLS 1.0 only work at security level 0.
```
This is sadly not mentioned in `CHANGES.md`, I think that oversight should be corrected. This sort of change should be mentioned in both places IMHO (retroactively if necessary).

**Comment by lucadjc** [comment]
> * Specifically to your issue, it seems that when `cfg.cert` is not set, you don't call:
> 
> ```
> sslContext.set_ciphers("ALL:@SECLEVEL=0")
> ```
> 
I set it before the if with the statement
sslContext.set_ciphers("HIGH:!DH:!aNULL")

To add more details, the certificate on the "Server" (that is my air conditioner) is expired 

 Executing the command this is the result that I get
**sslscan 192.168.1.51:2878**

Testing SSL server 192.168.1.51 on port 2878 using SNI name 192.168.1.51

SSL/TLS Protocols:
SSLv2     enabled
SSLv3     enabled
TLSv1.0   enabled
TLSv1.1   disabled
TLSv1.2   disabled
TLSv1.3   disabled

  TLS Fallback SCSV:
Connection failed - unable to determine TLS Fallback SCSV support

  TLS renegotiation:
Session renegotiation not supported

  TLS Compression:
OpenSSL version does not support compression
Rebuild with zlib1g-dev package for zlib support

  Heartbleed:
TLSv1.0 not vulnerable to heartbleed

  Supported Server Cipher(s):
Preferred TLSv1.0  128 bits  TLS_RSA_WITH_RC4_128_MD5     
Preferred TLSv1.0  128 bits  TLS_RSA_WITH_RC4_128_SHA     
Preferred TLSv1.0  128 bits  TLS_RSA_WITH_IDEA_CBC_SHA    
Preferred TLSv1.0  56 bits   TLS_RSA_WITH_DES_CBC_SHA     
Preferred TLSv1.0  112 bits  TLS_RSA_WITH_3DES_EDE_CBC_SHA
Preferred TLSv1.0  40 bits   TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
Preferred TLSv1.0  56 bits   TLS_DHE_RSA_WITH_DES_CBC_SHA 
Preferred TLSv1.0  112 bits  TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
Preferred TLSv1.0  ?? bits    TLS_RSA_WITH_SEED_CBC_SHA    
Preferred TLSv1.0  ?? bits    TLS_DHE_RSA_WITH_SEED_CBC_SHA
Certificate information cannot be retrieved.

Trying this configuration
sslContext.set_ciphers("ALL:@SECLEVEL=1")

This is the error message that I get
/home/lucadjc/test.py:105: DeprecationWarning: ssl.PROTOCOL_TLSv1 is deprecated
  sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
Setting up ciphers
Setting up verify mode
Cert is empty, skipping verification
Wrapping socket
Socket wrapped: True
Connecting with 192.168.1.51:2878
Error: Traceback (most recent call last):
  File "/home/lucadjc/test.py", line 144, in <module>
    sslSocket.connect((serverName, serverPort))
  File "/usr/lib/python3.10/ssl.py", line 1375, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.10/ssl.py", line 1366, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: BAD_DH_VALUE] bad dh value (_ssl.c:997)

**Comment by mattcaswell** [comment]
> bad dh value

There is some problem with the DH parameters being sent from the server. Interestingly you have this line:

> sslContext.set_ciphers("HIGH:!DH:!aNULL")

Which should disable DH based ciphersuites. I'm not sure where in the sequence you've added the `sslContext.set_ciphers("ALL:@SECLEVEL=0")`, but that enables DH ciphersuites again. You could combine these with `sslContext.set_ciphers("HIGH:!DH:!aNULL:@SECLEVEL=0")`

**Comment by vdukhovni** [comment]
I doubt the `!DH' is either a well-informed intention or wise. Especially when trying to interoperate with a legacy device, via a legacy protocol, the cipher settings should not include ad-hoc exclusions.  The sensible choice is:

* For unauthenticated TLS, i.e. when not validating the peer certificate:
```
aNULL:-aNULL:ALL:@SECLEVEL=0
```
this will use the strongest shared symmetric bulk cipher, and skip even sending a certificate if that's also supported by the server.
* For authenticated TLS (when validating the peer certificate):
    -  Including the server name, otherwise pointless
    - unless matching an explicit EE certificate by specifying a CAfile with the leaf cert and enabling "partial chains"
```
DEFAULT:@SECLEVEL=0
```

Perhaps the intent was to disable the *fixed DH* (and fixed ECDH) legacy ciphers.  In that case, the exclusions should be:
```
!kDH:!kECDH
```
which disable fixed DH key exchange, but it is unlikely that the server supports those in the first place, so not especially important to do.

**Comment by lucadjc** [comment]
Perfect!!!
This is working for my case!!!
Many many thanks to all of you for the support!

> `sslContext.set_ciphers("HIGH:!DH:!aNULL:@SECLEVEL=0")`

**Comment by vdukhovni** [comment]
Is the reason for `!DH` that your server's DHE key implementation broken?  Does it then negotiate ECDHE key exchange or RSA?  I rather suspec the latter, in which case, assuming the server also doesn't support CAMELIA your effective cipher list is basically equivalent to just the two below:
```
$ openssl ciphers -s -v -tls1 'AES+HIGH+kRSA:@SECLEVEL=0'
AES256-SHA                     SSLv3   Kx=RSA      Au=RSA   Enc=AES(256)               Mac=SHA1
AES128-SHA                     SSLv3   Kx=RSA      Au=RSA   Enc=AES(128)               Mac=SHA1
```
You could simply your cipher list to just `AES128-SHA:@SECLEVEL=0` if the script in question is dedicated to communicating with just that server.
