### ISSUE TITLE
SSL_do_handshake failed for varies reasons

### ISSUE THREAD

**Issue by mcdullbloom** [openssl/openssl#21347]
I got some errors below when I use openssl in Nginx with QAT for asynq mode.  @mattcaswell , could you give me some suggestions to fix it? Much appreciate.

Nginx: 1.19.3.1
Openssl : 1.1.1n
QAT: QAT crypto engine(qat_sw) v0.6.18

> 2023/07/03 15:22:08 [crit] 43398#43398: *102515615882 SSL_do_handshake() failed (SSL: error:141B306E:SSL routines:tls_collect_extensions:bad extension) while SSL handshaking, client: 111.48.134.22, server: 0.0.0.0:443
> 2023/07/03 15:22:09 [crit] 43427#43427: *102515662350 SSL_do_handshake() failed (SSL: error:141B306E:SSL routines:tls_collect_extensions:bad extension) while SSL handshaking, client: 111.48.134.167, server: 0.0.0.0:443
> 2023/07/03 15:22:11 [crit] 43407#43407: *102515718900 SSL_do_handshake() failed (SSL: error:800640A8:lib(128):aes_gcm_tls_cipher:gcm tag verify failure error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac) while SSL handshaking, client: 111.48.114.203, server: 0.0.0.0:443
> 2023/07/03 15:22:13 [crit] 43448#43448: *102515803442 SSL_do_handshake() failed (SSL: error:800640A8:lib(128):aes_gcm_tls_cipher:gcm tag verify failure error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac) while SSL handshaking, client: 111.48.134.63, server: 0.0.0.0:443
> 2023/07/03 15:22:14 [crit] 43416#43416: *102515843377 SSL_do_handshake() failed (SSL: error:800640A8:lib(128):aes_gcm_tls_cipher:gcm tag verify failure error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac) while SSL handshaking, client: 111.48.114.56, server: 0.0.0.0:443
> 2023/07/03 15:22:16 [crit] 43380#43380: *102515959222 SSL_do_handshake() failed (SSL: error:141B306E:SSL routines:tls_collect_extensions:bad extension) while SSL handshaking, client: 111.48.114.35, server: 0.0.0.0:443

**Comment by nhorman** [comment]
marking inactive barring further input, will be closed at the end of the 3.4 dev cycle
