### ISSUE TITLE
OpenSSL 3.0 real name with version name on macOS

### ISSUE THREAD

**Issue by aniljadaun** [openssl/openssl#21353]
Hi 

I have query regarding openssl libs loading at runtime . We are using real name for openssl libs as libssl.3.dylib and libcrypto.3.dylib . As suggested by @levitte using modified names as libssl.dylib and libcrypto.dylib is not recommended as it may result in dylib conflict and we may end up loading 1.1.1 or any other version of libssl and libcrypto. Now my doubt is how does we make sure with usage of libssl.3.dylib real name we would avoid such issues when update has been done for say libssl.3.1.dylib. which i think would have real as libssl.3.dylib as well.

**Comment by nhorman** [comment]
marking as inactive.  Wiill close at the end of 3.4 dev cycle barring further input
