### ISSUE TITLE
Fix PowerPC assembler for ISA < 2.06 (i.e. restore non-VSX fallback)

### ISSUE THREAD

**Issue by barracuda156** [openssl/openssl#21354]
Apparently https://github.com/openssl/openssl/commit/791cc3029bd2aee7fc6b766b9841ce1e0a14484a commit has broken PPC assembler on earlier ISA, and then https://github.com/openssl/openssl/pull/20543 fixed the build by disabling it.
Is it possible instead to have a non-VSX fallback, since the code existed and worked? Just prior to a breaking commit results were reported for PPC 970 (G5), which means it actually worked and has been tested.

**Comment by t8m** [comment]
Perhaps @rohanmclure @erichte-ibm @naynajain @dannytsen @pkubaj could help with this?

**Comment by dannytsen** [comment]
@t8m I thought this has been addressed in #22860 and #22818.

**Comment by barracuda156** [comment]
> @t8m I thought this has been addressed in #22860 and #22818.

@dannytsen I do not think so. 3.2.0 was initially broken on PowerPC, and that _is_ apparently addressed now, but what I refer to here is restoring asm support for G5, which was broken in https://github.com/openssl/openssl/commit/791cc3029bd2aee7fc6b766b9841ce1e0a14484a

**Comment by dannytsen** [comment]
@barracuda156 I don't believe assembly support for G5 will be available from us from my understanding.  @naynajain may have more info.

**Comment by barracuda156** [comment]
> @barracuda156 I don't believe assembly support for G5 will be available from us from my understanding.  @naynajain may have more info.

@dannytsen It should be certainly possible at least to restore what was already there and got removed with that commit.

(I can do testing and share logs, if that helps you.)

**Comment by dannytsen** [comment]
That's up to @t8m decision and we will take it from there.  That's my opinion.

**Comment by barracuda156** [comment]
@t8m I need your help with approving this.

For the testing, I can do whatever necessary from my end. Got two G5 PowerMacs and some G4 ones, with 10.6 ppc, 10.5.8 ppc/ppc64 and 10.4.11 ppc.

**Comment by dannytsen** [comment]
If this is for chacha20 enhancement, G5 will use the old code not the p10 code from looking at the build.info.

  $CHACHAASM_ppc32=chacha_ppc.c chacha-ppc.s
  IF[{- $target{sys_id} ne "AIX" && $target{sys_id} ne "MACOSX" -}]
    $CHACHAASM_ppc32=chacha_ppc.c chacha-ppc.s chachap10-ppc.s
  ENDIF
  $CHACHAASM_ppc64=$CHACHAASM_ppc32

**Comment by barracuda156** [comment]
As a matter of fact that change has broken OpenSSL, since unsupported instructions were added. That might not have been an original intention, perhaps a case of earlier ISA was just forgotten. Solution via disabling worked as a quick fix, but is clearly suboptimal.

I can find logs tomorrow why that failed or just try the build from that commit to generate new logs.

**Comment by t8m** [comment]
I think there is some confusion here. The https://github.com/openssl/openssl/pull/20543 disabled build of the chachap10-ppc.s which is definitely not applicable to G5 at all. The chacha-ppc.s is buildable on Macs and there should be no breakage from https://github.com/openssl/openssl/commit/791cc3029bd2aee7fc6b766b9841ce1e0a14484a on Macs AFAIK.

So indeed @dannytsen is right and there is no issue here.

**Comment by barracuda156** [comment]
@t8m I guess my concern was from that `chacha-ppc.pl` added VSX stuff, but looks like I misunderstood what it does. If VSX instructions do not get used on macOS, but assembler is still used, we are all good, and the issue is to be closed as solved, indeed.

**Comment by barracuda156** [comment]
@t8m @dannytsen Thanks! And sorry for the hassle.
