### ISSUE TITLE
OBJ_create API in openssl30 vs in openssl102

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#21352]
Hi Team,
We are migrating from OpenSSL v102 to OpenSSL 30.
We noticed that API behaves differently in these version. Please see the sample code.
I'm creating the objects with same ids.
```
void objCreate1()
{
    int nid_msgType = OBJ_create("2.1.8.1.9.2", "message", "message");
    cout << "objCreate1: "<<nid_msgType ;
}

void objCreate2()
{
   int nid_msgType = OBJ_create("2.1.8.1.9.2", "message", "message");
    cout << "objCreate2: "<<nid_msgType ;
}

int main()
{
    objCreate1();
    objCreate2();
     return 0;
}

```
> //Output in version 102
> objCreate1: 961
> objCreate2: 961

> //Output in version 30
> objCreate1: 961
> **objCreate2: 0**  

In case of version 30 the I'm not able to get the nid second time. Is it because the object was already created. Does version 30 creates object globally ? Also is there any way to get the already created object with same oids.

**Comment by paulidale** [comment]
Check the error stack, it should contain an OID exists error.  This is present in 1.1.1 but not 1.0.2.
Try `OBJ_txt2obj`.

**Comment by mattcaswell** [comment]
> Try OBJ_txt2obj.

`OBJ_txt2nid()` is probably a better fit here, i.e.

````
    int mid_msgType = OBJ_txt2nid("2.1.8.1.9.2");
````

**Comment by paulidale** [comment]
We are wanting to move away from NIDs but it's not going to be for a long time yet.

**Comment by ChauhanPriyanka** [comment]
I'm able to get the nid's with OBJ_txt2nid(), I'm exploring OBJ_txt2obj to fit in current code.
As per existing code, we are creating the objects via OBJ_create() and triggering the same flow multiple times (i.e. requesting and parsing certs). To conclude my understanding,  once the object is created it will be there until the lifespan of application. Is this correct ? So we dont have to create object in all requests.

**Comment by mattcaswell** [comment]
> To conclude my understanding, once the object is created it will be there until the lifespan of application.

Correct.
