### ISSUE TITLE
When to use `RC4_CHAR` or `RC4_INT` for configuration targets?

### ISSUE THREAD

**Issue by fwh-dc** [openssl/openssl#21358]
When implementing new configuration targets in https://github.com/openssl/openssl/pull/21309 it is suggested to use `RC4_CHAR` and `RC4_INT` in bn_opts. Looking at the documentation on these I understand that it is related to the RC4 key schedule and it has implications on the performance. However it is not clear to me which cpu archs performs well with `RC4_INT` over `RC4_CHAR` and vice versa. 

What is the guideline when using these definitions?

**Comment by paulidale** [comment]
I suggest neither.  RC4 is old and lives in the legacy provider.  It shouldn't be used for anything new.

**Comment by fwh-dc** [comment]
Can I contribute a change to the documentation then?

**Comment by paulidale** [comment]
Please do contribute the change.
