### ISSUE TITLE
Performance improvement for CFB on 3.0 branch

### ISSUE THREAD

**Issue by sanumesh** [openssl/openssl#21366]
There has been a performance enhancement patch added to openssl 3.1 and master branch.
https://github.com/openssl/openssl/pull/18267

When this patch is added to openssl 3.0.8 tag, performance enhancement is also seen on 64bit openssl build on AIX.

This issue is reported to include the above pull request onto 3.0 branch.
Please let me know if I need to request a separate pull request for it ?
Thanks

**Comment by paulidale** [comment]
Our [stable release update policy](https://www.openssl.org/policies/technical/stable-release-updates.html) explicitly rules out performance enhancements being back ported, so this isn't going to happen.

**Comment by t8m** [comment]
The fix is fairly trivial and should be safe. So IMO we should at least discuss within OTC whether we want an exception for this.

**Comment by sanumesh** [comment]
Thank you.
To add on, we are seeing close to 50% improvement with this patch when measured through openssl speed command. 

With Openssl 3.0 having LTS, it gives us more flexibility to have it in 3.0 branch than 3.1 branch.

**Comment by t8m** [comment]
**OTC: we will hold a vote for this.**

**Comment by mattcaswell** [comment]
Removing the "won't fix" label.

The vote was held and passed (i.e. allowing a backport):

https://github.com/openssl/technical-policies/issues/70

I can't find a record of the backport actually occurring though.

@t8m - since you proposed the vote, do you recall if anything further happened about this?

**Comment by t8m** [comment]
@mattcaswell Created https://github.com/openssl/openssl/pull/23463 - please approve

**Comment by t8m** [comment]
#23463 was merged to 3.0 branch.
