### ISSUE TITLE
High memory allocations of around 46 KB in CONF_modules_load() 

### ISSUE THREAD

**Issue by vk18anubhav** [openssl/openssl#21376]
We are using Openssl 3.0.8 and we are seeing high memory allocations of around 46 KB in CONF_modules_load() related to different error strings

 Openssl init crypto has been done with following flags :

OPENSSL_init_crypto( OPENSSL_INIT_NO_ADD_ALL_CIPHERS | OPENSSL_INIT_NO_ADD_ALL_DIGESTS | OPENSSL_INIT_NO_LOAD_CONFIG, NULL)

Is it feasible to use OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS in above Openssl init crypto which seems to avoid allocations for error strings ? What will be the impact if we use OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS ?

PFA the stacks and respective memory allocations (Generated with valgrind massif tool):
->52.03% (46,340B) : CRYPTO_malloc (mem.c:190)
| ->33.98% (30,264B) : OPENSSL_LH_insert (lhash.c:120)
| | ->29.40% (26,184B) : err_load_strings (err.c:265)
| | | ->27.19% (24,216B) : ERR_load_strings_const (err.c:302)
| | | | ->07.84% (6,984B) in 14 places, all below massif's threshold (1.00%)

| | | | ->03.10% (2,760B) : ossl_err_load_ASN1_strings (asn1_err.c:209)
| | | | | ->03.10% (2,760B) : ossl_err_load_crypto_strings (err_all.c:66)
| | | | |   ->03.10% (2,760B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->03.10% (2,760B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->03.10% (2,760B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->03.10% (2,760B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->03.10% (2,760B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->03.10% (2,760B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->03.10% (2,760B) : ERR_set_mark (err.c:882)
| | | | |                 ->03.10% (2,760B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->03.10% (2,760B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->03.10% (2,760B) : CONF_modules_load (conf_mod.c:128)

| | | | ->02.94% (2,616B) : ossl_err_load_EVP_strings (evp_err.c:205)
| | | | | ->02.94% (2,616B) : ossl_err_load_crypto_strings (err_all.c:58)
| | | | |   ->02.94% (2,616B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->02.94% (2,616B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->02.94% (2,616B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->02.94% (2,616B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->02.94% (2,616B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->02.94% (2,616B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->02.94% (2,616B) : ERR_set_mark (err.c:882)
| | | | |                 ->02.94% (2,616B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->02.94% (2,616B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->02.94% (2,616B) : CONF_modules_load (conf_mod.c:128)

| | | | ->02.21% (1,968B) : ossl_err_load_RSA_strings (rsa_err.c:163)
| | | | | ->02.21% (1,968B) : ossl_err_load_crypto_strings (err_all.c:54)
| | | | |   ->02.21% (1,968B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->02.21% (1,968B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->02.21% (1,968B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->02.21% (1,968B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->02.21% (1,968B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->02.21% (1,968B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->02.21% (1,968B) : ERR_set_mark (err.c:882)
| | | | |                 ->02.21% (1,968B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->02.21% (1,968B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->02.21% (1,968B) : CONF_modules_load (conf_mod.c:128)

| | | | ->02.02% (1,800B) : ossl_err_load_EC_strings (ec_err.c:129)
| | | | | ->02.02% (1,800B) : ossl_err_load_crypto_strings (err_all.c:73)
| | | | |   ->02.02% (1,800B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->02.02% (1,800B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->02.02% (1,800B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->02.02% (1,800B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->02.02% (1,800B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->02.02% (1,800B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->02.02% (1,800B) : ERR_set_mark (err.c:882)
| | | | |                 ->02.02% (1,800B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->02.02% (1,800B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->02.02% (1,800B) : CONF_modules_load (conf_mod.c:128)

| | | | ->01.83% (1,632B) : ossl_err_load_X509V3_strings (v3err.c:144)
| | | | | ->01.83% (1,632B) : ossl_err_load_crypto_strings (err_all.c:78)
| | | | |   ->01.83% (1,632B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->01.83% (1,632B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->01.83% (1,632B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->01.83% (1,632B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->01.83% (1,632B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->01.83% (1,632B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->01.83% (1,632B) : ERR_set_mark (err.c:882)
| | | | |                 ->01.83% (1,632B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->01.83% (1,632B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->01.83% (1,632B) : CONF_modules_load (conf_mod.c:128)

| | | | ->01.81% (1,608B) : ossl_err_load_CMS_strings (cms_err.c:172)
| | | | | ->01.81% (1,608B) : ossl_err_load_crypto_strings (err_all.c:94)
| | | | |   ->01.81% (1,608B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->01.81% (1,608B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->01.81% (1,608B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->01.81% (1,608B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->01.81% (1,608B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->01.81% (1,608B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->01.81% (1,608B) : ERR_set_mark (err.c:882)
| | | | |                 ->01.81% (1,608B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->01.81% (1,608B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->01.81% (1,608B) : CONF_modules_load (conf_mod.c:128)

| | | | ->01.16% (1,032B) : ossl_err_load_RAND_strings (rand_err.c:104)
| | | | | ->01.16% (1,032B) : ossl_err_load_crypto_strings (err_all.c:80)
| | | | |   ->01.16% (1,032B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->01.16% (1,032B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->01.16% (1,032B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->01.16% (1,032B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->01.16% (1,032B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->01.16% (1,032B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->01.16% (1,032B) : ERR_set_mark (err.c:882)
| | | | |                 ->01.16% (1,032B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->01.16% (1,032B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->01.16% (1,032B) : CONF_modules_load (conf_mod.c:128)

| | | | ->01.16% (1,032B) : ossl_err_load_X509_strings (x509_err.c:91)
| | | | | ->01.16% (1,032B) : ossl_err_load_crypto_strings (err_all.c:65)
| | | | |   ->01.16% (1,032B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->01.16% (1,032B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->01.16% (1,032B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->01.16% (1,032B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->01.16% (1,032B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->01.16% (1,032B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->01.16% (1,032B) : ERR_set_mark (err.c:882)
| | | | |                 ->01.16% (1,032B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->01.16% (1,032B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->01.16% (1,032B) : CONF_modules_load (conf_mod.c:128)

| | | | ->01.05% (936B) : ossl_err_load_TS_strings (ts_err.c:85)
| | | | | ->01.05% (936B) : ossl_err_load_crypto_strings (err_all.c:83)
| | | | |   ->01.05% (936B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->01.05% (936B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->01.05% (936B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->01.05% (936B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->01.05% (936B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->01.05% (936B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->01.05% (936B) : ERR_set_mark (err.c:882)
| | | | |                 ->01.05% (936B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->01.05% (936B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->01.05% (936B) : CONF_modules_load (conf_mod.c:128)

| | | | ->01.05% (936B) : ossl_err_load_BIO_strings (bio_err.c:83)
| | | | | ->01.05% (936B) : ossl_err_load_crypto_strings (err_all.c:76)
| | | | |   ->01.05% (936B) : ossl_init_load_crypto_strings (init.c:190)
| | | | |     ->01.05% (936B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | | |       ->01.05% (936B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | | |         ->01.05% (936B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | | |           ->01.05% (936B) : OPENSSL_init_crypto (init.c:549)
| | | | |             ->01.05% (936B) : ossl_err_get_state_int (err.c:704)
| | | | |               ->01.05% (936B) : ERR_set_mark (err.c:882)
| | | | |                 ->01.05% (936B) : _CONF_get_number (conf_lib.c:374)
| | | | |                   ->01.05% (936B) : conf_diagnostics (conf_mod.c:112)
| | | | |                     ->01.05% (936B) : CONF_modules_load (conf_mod.c:128)

| | | | ->01.02% (912B) : ossl_err_load_PKCS7_strings (pkcs7err.c:95)
| | | |   ->01.02% (912B) : ossl_err_load_crypto_strings (err_all.c:77)
| | | |     ->01.02% (912B) : ossl_init_load_crypto_strings (init.c:190)
| | | |       ->01.02% (912B) : ossl_init_load_crypto_strings_ossl_ (init.c:181)
| | | |         ->01.02% (912B) : __pthread_once_slow (in /usr/lib64/libpthread-2.28.so)
| | | |           ->01.02% (912B) : CRYPTO_THREAD_run_once (threads_pthread.c:156)
| | | |             ->01.02% (912B) : OPENSSL_init_crypto (init.c:549)
| | | |               ->01.02% (912B) : ossl_err_get_state_int (err.c:704)
| | | |                 ->01.02% (912B) : ERR_set_mark (err.c:882)
| | | |                   ->01.02% (912B) : _CONF_get_number (conf_lib.c:374)
| | | |                     ->01.02% (912B) : conf_diagnostics (conf_mod.c:112)
| | | |                       ->01.02% (912B) : CONF_modules_load (conf_mod.c:128)

**Comment by mattcaswell** [comment]
The impact is that human readable error strings are no longer available. Instead you just get error codes. Error codes can be converted into human readable strings later using the `openssl errstr` command line app.

**Comment by nhorman** [comment]
Question has been answered, no bug to fix, closing.
