### ISSUE TITLE
High memory allocations in RAND_bytes() API for EVP_CIPHER_fetch() call

### ISSUE THREAD

**Issue by vk18anubhav** [openssl/openssl#21374]
We are using Openssl 3.0.8 and we are seeing high memory allocations of around 200-230 KB in EVP_CIPHER_fetch( only for a single call of RAND_bytes() where openssl init crypto has been done with following flags :

OPENSSL_init_crypto( OPENSSL_INIT_NO_ADD_ALL_CIPHERS | OPENSSL_INIT_NO_ADD_ALL_DIGESTS | OPENSSL_INIT_NO_LOAD_CONFIG, NULL)

PFA the stacks and respective memory allocations (Generated with valgrind massif tool):

186 KB
->70.25% (186,886B) : CRYPTO_malloc (mem.c:190)
| ->49.64% (132,056B) : CRYPTO_zalloc (mem.c:197)
| | ->12.99% (34,560B) : alloc_node (sparse_array.c:176)
| | | ->12.80% (34,048B) : ossl_sa_set (sparse_array.c:205)
| | | | ->12.80% (34,048B) : ossl_sa_ALGORITHM_set (property.c:96)
| | | |   ->12.80% (34,048B) : ossl_method_store_insert (property.c:294)
| | | |     ->12.80% (34,048B) : ossl_method_store_add (property.c:352)
| | | |       ->12.80% (34,048B) : put_evp_method_in_store (evp_fetch.c:210)
| | | |         ->12.80% (34,048B) : ossl_method_construct_this (core_fetch.c:123)
| | | |           ->12.80% (34,048B) : algorithm_do_map (core_algorithm.c:77)
| | | |             ->12.80% (34,048B) : algorithm_do_this (core_algorithm.c:122)
| | | |               ->12.80% (34,048B) : ossl_provider_doall_activated (provider_core.c:1431)
| | | |                 ->12.80% (34,048B) : ossl_algorithm_do_all (core_algorithm.c:162)
| | | |                   ->12.80% (34,048B) : ossl_method_construct (core_fetch.c:153)
| | | |                     ->12.80% (34,048B) : inner_evp_generic_fetch (evp_fetch.c:344)
| | | |                       ->12.80% (34,048B) : evp_generic_fetch (evp_fetch.c:396)
| | | |                         ->12.27% (32,640B) : EVP_CIPHER_fetch (evp_enc.c:1632)
| | | |                         | ->12.27% (32,640B) : drbg_ctr_set_ctx_params (drbg_ctr.c:703)
| | | |                         |   ->12.27% (32,640B) : drbg_ctr_instantiate_wrapper (drbg_ctr.c:334)
| | | |                         |     ->12.27% (32,640B) : evp_rand_instantiate_locked (evp_rand.c:505)
| | | |                         |       ->12.27% (32,640B) : EVP_RAND_instantiate (evp_rand.c:518)
| | | |                         |         ->12.27% (32,640B) : rand_new_drbg (rand_lib.c:600)
| | | |                         |           ->12.27% (32,640B) : RAND_get0_primary (rand_lib.c:647)
| | | |                         |             ->12.27% (32,640B) : RAND_get0_public (rand_lib.c:678)
| | | |                         |               ->12.27% (32,640B) : RAND_bytes_ex (rand_lib.c:363)
| | | |                         |                 ->12.27% (32,640B) : RAND_bytes (rand_lib.c:374)

31KB
| | ->12.08% (31,744B) : evp_cipher_new (evp_enc.c:1436)
| | | ->12.08% (31,744B) : evp_cipher_from_algorithm (evp_enc.c:1488)
| | |   ->12.08% (31,744B) : construct_evp_method (evp_fetch.c:239)
| | |     ->12.08% (31,744B) : ossl_method_construct_this (core_fetch.c:109)
| | |       ->12.08% (31,744B) : algorithm_do_map (core_algorithm.c:77)
| | |         ->12.08% (31,744B) : algorithm_do_this (core_algorithm.c:122)
| | |           ->12.08% (31,744B) : ossl_provider_doall_activated (provider_core.c:1431)
| | |             ->12.08% (31,744B) : ossl_algorithm_do_all (core_algorithm.c:162)
| | |               ->12.08% (31,744B) : ossl_method_construct (core_fetch.c:153)
| | |                 ->12.08% (31,744B) : inner_evp_generic_fetch (evp_fetch.c:344)
| | |                   ->12.08% (31,744B) : evp_generic_fetch (evp_fetch.c:396)
| | |                     ->12.08% (31,744B) : EVP_CIPHER_fetch (evp_enc.c:1632)
| | |                       ->12.08% (31,744B) : drbg_ctr_set_ctx_params (drbg_ctr.c:703)
| | |                         ->12.08% (31,744B) : drbg_ctr_instantiate_wrapper (drbg_ctr.c:334)
| | |                           ->12.08% (31,744B) : evp_rand_instantiate_locked (evp_rand.c:505)
| | |                             ->12.08% (31,744B) : EVP_RAND_instantiate (evp_rand.c:518)
| | |                               ->12.08% (31,744B) : rand_new_drbg (rand_lib.c:600)
| | |                                 ->12.08% (31,744B) : RAND_get0_primary (rand_lib.c:647)
| | |                                   ->12.08% (31,744B) : RAND_get0_public (rand_lib.c:678)
| | |                                     ->12.08% (31,744B) : RAND_bytes_ex (rand_lib.c:363)
| | |                                       ->12.08% (31,744B) : RAND_bytes (rand_lib.c:374)

17KB
| | ->06.50% (17,280B) : OPENSSL_LH_new (lhash.c:59)
| | | ->06.21% (16,512B) : lh_QUERY_new (property.c:55)
| | | | ->06.21% (16,512B) : ossl_method_store_add (property.c:349)
| | | |   ->06.21% (16,512B) : put_evp_method_in_store (evp_fetch.c:210)
| | | |     ->06.21% (16,512B) : ossl_method_construct_this (core_fetch.c:123)
| | | |       ->06.21% (16,512B) : algorithm_do_map (core_algorithm.c:77)
| | | |         ->06.21% (16,512B) : algorithm_do_this (core_algorithm.c:122)
| | | |           ->06.21% (16,512B) : ossl_provider_doall_activated (provider_core.c:1431)
| | | |             ->06.21% (16,512B) : ossl_algorithm_do_all (core_algorithm.c:162)
| | | |               ->06.21% (16,512B) : ossl_method_construct (core_fetch.c:153)
| | | |                 ->06.21% (16,512B) : inner_evp_generic_fetch (evp_fetch.c:344)
| | | |                   ->06.21% (16,512B) : evp_generic_fetch (evp_fetch.c:396)
| | | |                     ->05.97% (15,872B) : EVP_CIPHER_fetch (evp_enc.c:1632)
| | | |                     | ->05.97% (15,872B) : drbg_ctr_set_ctx_params (drbg_ctr.c:703)
| | | |                     |   ->05.97% (15,872B) : drbg_ctr_instantiate_wrapper (drbg_ctr.c:334)
| | | |                     |     ->05.97% (15,872B) : evp_rand_instantiate_locked (evp_rand.c:505)
| | | |                     |       ->05.97% (15,872B) : EVP_RAND_instantiate (evp_rand.c:518)
| | | |                     |         ->05.97% (15,872B) : rand_new_drbg (rand_lib.c:600)
| | | |                     |           ->05.97% (15,872B) : RAND_get0_primary (rand_lib.c:647)
| | | |                     |             ->05.97% (15,872B) : RAND_get0_public (rand_lib.c:678)
| | | |                     |               ->05.97% (15,872B) : RAND_bytes_ex (rand_lib.c:363)
| | | |                     |                 ->05.97% (15,872B) : RAND_bytes (rand_lib.c:374)

**Comment by mattcaswell** [comment]
This is expected. The first time you do a fetch it caches lots of things. Subsequent calls to RAND_bytes shouldn't do this.

**Comment by vk18anubhav** [comment]
Can we avoid these fetches all together for rand_bytes if they are not necessary for the operation ?

**Comment by mattcaswell** [comment]
No. They are necessary.

**Comment by wbeck10** [comment]
I was debugging it and it seems this memory allocation is mainly used by creating a name map table and some hash tables. I guess this is to find the algorithms faster. Anyway there are OPENSSL_init_crypto options:
OPENSSL_INIT_NO_ADD_ALL_CIPHERS
OPENSSL_INIT_NO_ADD_ALL_DIGESTS

When using those options, the hash and name map tables are smaller which saves 20kbytes of memory allocation which is used until process is exiting. The peak is much higher (I think it was around 120kbytes) that would be saved.

If I init OpenSSL with those OPENSSL_INIT flags, tls connections and wallet operations are failing because they try to find the cipher / digest using the has table and name map table.
My question here is:
Why are those OPENSSL_INIT_NO_ALL_CIPHER / DIGESTS flags there to be used but OpenSSL relies internally on name maps and complete hash tables?
Is this a bug or feature?

Cheers,
 WB

**Comment by paulidale** [comment]
There are operations OpenSSL can perform without requiring ciphers or digests (e.g. HMAC doesn't require ciphers).  These options make such slightly more efficient.

So, a feature that needs to be enabled with care.

**Comment by wbeck10** [comment]
Hi Pauli,
Yep, that makes sense.
Thanks mate

**Comment by slontis** [comment]
The first fetch for an operation type fetches and caches all other operations of the same type. (The operation types are of the form OSSL_OP_XXX See core_dispatch.h).
This is why prefetching is recommended.

**Comment by nhorman** [comment]
There appears to be no further work to do here, and no bug to fix. Closing
