### ISSUE TITLE
fipsinstall module-mac depends upon what settings

### ISSUE THREAD

**Issue by aniljadaun** [openssl/openssl#21375]
Hi 

Can you please confirm what does fipsinstall generated module-mac depends upon and when can a module mac change for user without user actually changing the module used?
What are hardware configuration impacting the module-mac ?
Does a user logging into a system with different account would also impact the module mac ?

**Comment by paulidale** [comment]
The module-mac should **never** change.  It is a cryptographic checksum of the FIPS provider -- nothing more, nothing less.  If you change the FIPS provider, it will change.  Otherwise is **must** not.

If you are seeing a change, you have a problem.

**Comment by aniljadaun** [comment]
Hi @paulidale 

Thank you for your response. I understand that the module-mac should never change. However, I would like to know what hardware the module-mac for fips.dll  depends on when the user runs the fipsinstall command to generate it.

We will be shipping OpenSSL with our package, and we will be running the fipsinstall command on each user machines to generate the fips_module.cnf file, which includes the module-mac. We want to understand what other factors  other than updating fips module can impact the module-mac, so that we can suggest the user to regenerate the module-mac for the fips.dylib module if those factors change.

**Comment by paulidale** [comment]
The module mac depends only on the module, nothing else.

**Comment by aniljadaun** [comment]
Ok, So are you saying fipsinstall on fips.dylib shipped with our package will generate same module-mac on every machine it is installed on?

**Comment by paulidale** [comment]
For the third time, yes it will be the same.

The reason for not allowing you to copy the file across is to ensure that the self tests are run.  This is a FIPS requirement.

Yes, the tests can be run at runtime but that doesn't meet the requirement and the installation would not be FIPS compliant.

**Comment by aniljadaun** [comment]
Hi @paulidale 

Thank you so much for your response. You've been incredibly helpful throughout this process, and I really appreciate your guidance.
I know I've asked a lot of questions, and I apologize if I'm being annoying. I just want to be double sure that I'm not missing anything important. This is a big change for our organization, and I'm trying to be very sure with all the workflow dependencies and requirements.

I really appreciate your patience and understanding. Thank you again for your help.

**Comment by paulidale** [comment]
Make sure you follow the process listed in the security policy (appendix A) and your installation will be compliant.
Any deviation, no matter how smaller or seemingly insignificant, results in a non-compliant installation.

If you need to make a change, contract with a FIPS lab for advice.  They are the experts and are the only people who can give definitive advise.

**Comment by aniljadaun** [comment]
Sure @paulidale .I have gone through the document .

I am successfully able to load fips.dll on my machine , which means fipsinstall and self test is fine for me.

Though i have one more question,  i see fipsmodule.cnf generated for me is different from some i see posted on internet

The version created for me doesn't have
install-mac = 41:9C:38:C2:8F:59:09:43:2C:AA:2F:58:36:2D:D9:04:F9:6C:56:8B:09:E0:18:3A:2E:D6:CC:69:05:04:E1:11

Is it a problem ? Am i missing something here ? Would that impact our shipping package , when installed in external environment ?

**Comment by slontis** [comment]
The number produced is a HMAC_SHA256 MAC of the fips.dll that you built. If someone else builds it with different options, or has different code, (or compiler) or builds on another platform etc then the dll will be different. 
It has really has no meaning other than to tell you if the dll has changed since you generated the checksum.

**Comment by AbhishekRimus** [comment]
Hi @aniljadaun ,

I am trying to load fips module in my sample application for mac.

I am getting error of missing config data.

I have copied all the files required such as config files and fips.dylib to my program.
I have cross checked that all this files i have placed in my program are correct but still I am getting error.
Can you please help me with this?
