### ISSUE TITLE
Enable ARM SHA3 instruction accelerated implementation of SHA3

### ISSUE THREAD

**Issue by sdlyyxy** [openssl/openssl#21380]
To enable ARM SHA3 instruction accelerated implementation of SHA3, I tried to change the `SHA3_absorb` function in `providers/implementations/digests/sha3_prov.c` to `SHA3_absorb_cext`.

```C++
static size_t generic_sha3_absorb(void *vctx, const void *inp, size_t len)
{
    KECCAK1600_CTX *ctx = vctx;
    return SHA3_absorb(ctx->A, inp, len, ctx->block_size);
}
```

```C++
static size_t generic_sha3_absorb(void *vctx, const void *inp, size_t len)
{
    KECCAK1600_CTX *ctx = vctx;
    size_t SHA3_absorb_cext(uint64_t A[5][5], const unsigned char *inp, size_t len,
                    size_t r);
    return SHA3_absorb_cext(ctx->A, inp, len, ctx->block_size);
}
```

I can't find other configuration options to setup this. Is this the right way to do it?

**Comment by zorrorffm** [comment]
You should redefine SHA3_SET_MD to point to Arm accelerated implementation for Arm architecture. You can take s390's implementation at line 238 as a reference.

What you need to notice is that the accelerated code is not good as expected, the author mentioned the performance behavior in keccak1600-armv8.pl as follows. You have to justify the performance of the accelerated code is better than the default implementation before you employ the accelerated code.
`# February 2018.
#
# Add hardware-assisted ARMv8.2 implementation. It's KECCAK_1X_ALT
# variant with register permutation/rotation twist that allows to
# eliminate copies to temporary registers. If you look closely you'll
# notice that it uses only one lane of vector registers. The new
# instructions effectively facilitate parallel hashing, which we don't
# support [yet?]. But lowest-level core procedure is prepared for it.
# The inner round is 67 [vector] instructions, so it's not actually
# obvious that it will provide performance improvement [in serial
# hash] as long as vector instructions issue rate is limited to 1 per
# cycle...`

**Comment by sdlyyxy** [comment]
Thanks for answering! I tested it on Apple M1 and it shows a solid 36% improvement for large blocks. I'll try to make a PR to enable the code on Apple Silicon.
