### ISSUE TITLE
Invalid version number reported when intalling openSSL v1.1.0c

### ISSUE THREAD

**Issue by gunjanbhasin** [openssl/openssl#2139]
What I did:

    1. Login into Linux m/c
    2. run command: su
    3. run command: wget https://www.openssl.org/source/openssl-1.1.0c.tar.gz (To get the latest openSSL code)
    4. run command: gzip –d openssl-1.0.1c.tar.gz
    5. run command: tar -xvf openssl-1.1.0c.tar.gz
    6. run command: cd openssl-1.1.0c
    7. run command: ./config shared --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
    8. run command: gmake clean depend
    9. run command: gmake
    10. run command: gmake install
    11. run command: cd /usr/local/ssl/bin
    12. verify the openSSL version; run command: ./openSSL version

**Expected result:** OpenSSL 1.1.0c 10 Nov 2016
**Actual result:** OpenSSL 0.9.8j-fips 07 Jan 2009

**Comment by levitte** [comment]
I assume you have openssl installed through some distribution package as well, i.e. there is a `/usr/bin/openssl`.

There are two solutions for this:

1.  add `-Wl,--enable-new-dtags,-rpath='$(LIBRPATH)'` to your configuration command, i.e.:

    ```
    ./config shared --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -Wl,--enable-new-dtags,-rpath='$(LIBRPATH)'
    ```

2.  Add `/usr/local/ssl/lib` to your ld.so configuration (i.e. `/etc/ld.so.conf`) and run `ldconfig` (see `man ldconfig`)

**Comment by mattcaswell** [comment]
Question was answered. Closing.
