### ISSUE TITLE
"openssl ciphers RSA" omits many ciphers that use RSA authentication

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2141]
The documentation of `openssl ciphers` states:

<pre>
       <b>kRSA, aRSA, RSA</b>
           Cipher suites using RSA key exchange, authentication or either
           respectively.
</pre>

However, `openssl ciphers RSA` shows significantly *fewer* ciphers than `openssl ciphers aRSA`.

In particular, I get with OpenSSL 1.1.0c:

<pre>
<b>$ openssl ciphers RSA</b>
AES256-GCM-SHA384:AES256-CCM8:AES256-CCM:AES128-GCM-SHA256:AES128-CCM8:AES128-CCM:AES256-SHA256:CAMELLIA256-SHA256:AES128-SHA256:CAMELLIA128-SHA256:NULL-SHA256:AES256-SHA:CAMELLIA256-SHA:AES128-SHA:SEED-SHA:CAMELLIA128-SHA:IDEA-CBC-SHA:NULL-SHA:NULL-MD5
</pre>

And:

<pre>
<b>$ openssl ciphers aRSA</b>
ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES256-CCM8:DHE-RSA-AES256-CCM:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:... (many more omitted)
</pre>

Since the documentation states "or *either*", I expect these ciphers to also occur when using&nbsp;`RSA`.

The difference currently comprises the following ciphers:

<pre>
ECDHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES256-GCM-SHA384
ECDHE-RSA-CHACHA20-POLY1305
DHE-RSA-CHACHA20-POLY1305
DHE-RSA-AES256-CCM8
DHE-RSA-AES256-CCM
ECDHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES128-CCM8
DHE-RSA-AES128-CCM
ECDHE-RSA-AES256-SHA384
DHE-RSA-AES256-SHA256
ECDHE-RSA-CAMELLIA256-SHA384
DHE-RSA-CAMELLIA256-SHA256
ECDHE-RSA-AES128-SHA256
DHE-RSA-AES128-SHA256
ECDHE-RSA-CAMELLIA128-SHA256
DHE-RSA-CAMELLIA128-SHA256
ECDHE-RSA-AES256-SHA
DHE-RSA-AES256-SHA
DHE-RSA-CAMELLIA256-SHA
ECDHE-RSA-AES128-SHA
DHE-RSA-AES128-SHA
DHE-RSA-SEED-SHA
DHE-RSA-CAMELLIA128-SHA
ECDHE-RSA-NULL-SHA
RSA-PSK-AES256-GCM-SHA384
RSA-PSK-CHACHA20-POLY1305
RSA-PSK-AES128-GCM-SHA256
SRP-RSA-AES-256-CBC-SHA
RSA-PSK-AES256-CBC-SHA384
RSA-PSK-AES256-CBC-SHA
RSA-PSK-CAMELLIA256-SHA384
SRP-RSA-AES-128-CBC-SHA
RSA-PSK-AES128-CBC-SHA256
RSA-PSK-AES128-CBC-SHA
RSA-PSK-CAMELLIA128-SHA256
RSA-PSK-NULL-SHA384
RSA-PSK-NULL-SHA256
RSA-PSK-NULL-SHA
</pre>

**Comment by vdukhovni** [comment]
While the documentation says "or" (and perhaps that's the more desirable meaning) the implementation is "and".  And since kRSA requires aRSA, you end up with RSA == kRSA.  It seems that this equivalence goes way back to the root commit in the OpenSSL git repository:

    commit d02b48c63a58ea4367a0e905979f140b7d090f86
    Author: Ralf S. Engelschall <rse@openssl.org>
    Date:   Mon Dec 21 10:52:47 1998 +0000

    Import of old SSLeay release: SSLeay 0.8.1b

So even if "or" is the more useful meaning, at this point it probably makes more sense to update the documentation to match reality.

**Comment by triska** [comment]
Thank you for looking into this!

Personally, I would prefer if the implementation were made to behave according to the current documentation in this case. This is because using `RSA` to denote the *union* of `kRSA` and `aRSA` is more intuitive to&nbsp;use, and will also make it easier to *disable* all RSA-based ciphers at&nbsp;once.

In my opinion, the fact that this error has not been reported until recently can be taken as indication that only very few users, if any, rely on either of the two meanings. Thank&nbsp;you!

**Comment by vdukhovni** [comment]
Note that of necessity we have `kRSA` &#8838; `aRSA`, so "and" is just `kRSA` while "or" is just `aRSA`. So the issue boils down to whether `RSA` should denote `kRSA` or `aRSA`. There's likely more risk in making an incompatible change than benefit.  You can just use `aRSA` to block all use of RSA. I'm still more favourably inclined towards an update of the documentation.

**Comment by richsalz** [comment]
We can't rely on 'nobody spoke up so nobody cares.'  Few people read the documentation.  It is far more likely that users are just relying on the current behavior.  We can't change the semantics; we should just fix the docs.

**Comment by t-j-h** [comment]
The documentation is simply wrong and should be fixed - rarely is the documentation considered more correct than the actual code.

And if you read the "original" documentation for the "ciphers" command it actually states that RSA==kRSA (i.e. kRSA, RSA was noted as "cipher suites using the RSA key exchange").

The change to have kRSA, aRSA, RSA and state "or either respectively" came in 2012 in commit ffa457967982689149fa8403a1d57cee1dbee805

This is clearly a documentation error - the documentation used to match the code and was updated in a way that doesn't match the code so the documentation should be fixed.

**Comment by triska** [comment]
> of necessity we have kRSA ⊆ aRSA

@vdukhovni: As far as I understand, that's not *necessarily* the case (even if it's the case&nbsp;currently): There could be a cipher that uses ephemeral RSA&nbsp;keys for key&nbsp;exchange, and a completely different algorithm for authentication. A provision for this appeared for example in TLS&nbsp;1.0 (section&nbsp;7.4.3), and has fallen out of the specification in later&nbsp;versions.

**Comment by davidben** [comment]
That turned out to be kind of an [unfortunate](https://censys.io/blog/freak) decision and, given [upcoming](https://tlswg.github.io/tls13-spec/) TLS developments, is not likely to resurface. :-)

**Comment by triska** [comment]
Definitely not with such an extreme limitation (I hope).

**Comment by spacekitteh** [comment]
Possibly related: https://github.com/NixOS/nixpkgs/issues/21408

**Comment by mattcaswell** [comment]
Documentation was fixed. cc92ac7 on 1.1.0, f2bcff4 on master. Closing.
