### ISSUE TITLE
EVP_EncryptUpdate performance deterioration due to if branch

### ISSUE THREAD

**Issue by huiyuexu** [openssl/openssl#21423]
EVP_EncryptUpdate performance deterioration:
```shell
# Test Case
openssl speed -evp aes-256-gcm

# Test Result: （The 'numbers' are in 1000s of bytes per second processed.）
# openssl 1.1
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-gcm     218627.95k   622300.74k  1305089.45k  1568429.06k  1782939.65k  1806772.91k
# openssl 3.0.8
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-256-GCM     185969.54k   563552.77k  1255227.99k  1549153.96k  1769059.67k  1789323.95k
```

I find that the cause of deterioration is some "if" branches are added in OpenSSL 3.0 version, such as

https://github.com/openssl/openssl/blob/d13017c6bd54b4fa2db064b556fdc4669080a811/crypto/evp/evp_enc.c#L615

https://github.com/openssl/openssl/blob/d13017c6bd54b4fa2db064b556fdc4669080a811/crypto/evp/evp_enc.c#L623

https://github.com/openssl/openssl/blob/d13017c6bd54b4fa2db064b556fdc4669080a811/crypto/evp/evp_enc.c#L628

If delete the all new “if” branched of openssl 3.0, its performance will be improved:
```shell
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-256-GCM     217403.67k   612533.33k  1312510.63k  1551821.14k  1763557.38k  1775353.86k
```

Plus I tried the __builtin_expect optimization for openssl 3.0 as

```
+#define likely(x) __builtin_expect((x), 1)

@@ -615,7 +615,7 @@ int EVP_EncryptUpdate(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl,
-    if (outl != NULL) {
+   if (likely(outl != NULL)) {
```

The performance will be improved too:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-256-GCM     214061.95k   606078.85k  1298458.03k  1558545.07k  1771831.30k  1812190.55k
```
Could we use branch optimization for the specific compilers?
```
#if defined(__GNUC__) || defined(__clang__)
    #define likely(x) __builtin_expect((x), 1)
#endif
```

**Comment by t8m** [comment]
Unfortunately we cannot remove any checks unless they are fully redundant. However adding the `likely()` macro and using it as appropriate would be a very nice enhancement.
