### ISSUE TITLE
OPENSSL_CONF_INCLUDE does not seem to work in openssl 3.0.8

### ISSUE THREAD

**Issue by casidapulak** [openssl/openssl#21448]
### Discussed in https://github.com/openssl/openssl/discussions/21447

<div type='discussions-op-text'>

<sup>Originally posted by **casidapulak** July 13, 2023</sup>
Hello,
We are using openssl dlls in our c# application using p/invoke. We need to provide relative path for fipsmodule.cnf file in openssl.cnf.
We cant use the absolute path since our customers can choose to install our application anywhere and the path to openssl.cnf and fipsmodule.cnf(both of which will be deployed in same directory) will be dependent on the installation location.
So we tried using the environment variable OPENSSL_CONF_INCLUDE in our code before setting the config path like below:
`Environment.SetEnvironmentVariable("OPENSSL_CONF_INCLUDE", AppDomain.CurrentDomain.BaseDirectory,EnvironmentVariableTarget.Process);`

But that environment variable does not seem to have any impact. Our application is working only when we give absolute path or if we change the current working directory. 
Also is there a way to make openssl.cnf pick fipsmodule.cnf from the same directory that openssl.cnf file is in?
Request your help with this. Thanks in advance
</div>

**Comment by paulidale** [comment]
I don't think we need two items for this.  Closing this one.
