### ISSUE TITLE
Unbounded memory growth when receiving QUIC data

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#21460]
While running the test in #21368 against PR #21458 I noticed that the test fails with:

````
$ ../util/shlib_wrap.sh ./quicapitest -test 10 default default.cnf certs recipes/75-test_quicapi_data/
# ERROR:  @ test/quicapitest.c:796
# No back pressure seen
# 
# OPENSSL_TEST_RAND_ORDER=1689331090
not ok 1 - test_back_pressure
````

AFAICT from brief analysis, the problem seems to be that the recipient of data will just keep receiving more and more data without adjusting flow control limits even if the application has not kept up with reading that data, i.e. if the sender is sending faster than the receiver is receiving then we get unbounded memory growth.

This has both performance and security implications (e.g. an attacker able to transmit fast enough could eventually cause an out-of-memory condition on the peer).

**Comment by hlandau** [comment]
I'm confused by the test:

https://github.com/openssl/openssl/pull/21368/commits/0144f1058fa4b71b35a63069883ffda34e57fd3b#diff-f9407343ba04a08927702900c5d8b144ae95f3fdbf95051e668f777aef73c932R789

Since this calls `ossl_quic_tserver_read` it is retiring data from the receive end and thus naturally no backpressure will occur?

**Comment by mattcaswell** [comment]
The client is writing data at a rate of 1024 bytes every time it goes around the loop. The server is reading data at a rate of 64 bytes every time it goes around the loop, i.e. every time we go around the loop 960 more bytes are sent than are retired.

**Comment by hlandau** [comment]
It looks like you aren't testing the value of `written` after the call to `SSL_write_ex`, so it is quite possible each call to `SSL_write_ex` (after the first few calls fill the send buffer) is only sending 64 bytes.

**Comment by mattcaswell** [comment]
SSL_write_ex is all or nothing (unless partial writes are enabled - which they aren't in this test)....so if its only sending 64 bytes then that is incorrect behaviour (although I don't believe that is what is happening).

**Comment by mattcaswell** [comment]
Thanks to @hlandau for investigating. This turns out to be a non-issue. The test just wasn't looping enough to build up sufficient back pressure.
