### ISSUE TITLE
SSL_set_cipher_list/`openssl ciphers ALL:-EXP:-SRP:-SEED:-CAMELLIA:-DSS:-RC2:-DES-CBC-MD5:-DES-CBC3-MD5 | grep DH-DSS-AES256-GCM-SHA384` returns a result when it shouldn't

### ISSUE THREAD

**Issue by spacekitteh** [openssl/openssl#2146]
...I think (I don't think it should?)

Copying from https://github.com/NixOS/nixpkgs/issues/21408

## Issue description
The underlying call, SSL_set_cipher_list, appears to not correctly parse the filter list. This occurs both from the commandline, (running `openssl ciphers ALL:-EXP:-SRP:-SEED:-CAMELLIA:-DSS:-RC2:-DES-CBC-MD5:-DES-CBC3-MD5` ) and from calling the function directly ([as AOSP's conscrypt does](https://github.com/multi-os-engine/conscrypt/blob/master/src/main/java/org/conscrypt/NativeCrypto.java#L696))

### Steps to reproduce
run `openssl ciphers ALL:-EXP:-SRP:-SEED:-CAMELLIA:-DSS:-RC2:-DES-CBC-MD5:-DES-CBC3-MD5` with 

## Technical details
* OpenSSL: 1.0.2j

**Comment by vdukhovni** [comment]
There is no problem with parsing.  The cipher in question does not match `DSS`, and hence is not removed via `-DSS`.  The definition of `DSS` is as a synonym for `aDSS`, while this cipher uses fixed DH auth, with DH/DSS key exchange such ciphers match `kDHd`.

The documentation in ciphers(1) matches this behaviour:
```
       aDSS, DSS
           cipher suites using DSS authentication, i.e. the certificates carry
           DSS keys.
```
