### ISSUE TITLE
Documentation of SSL_CTX_use_certificate to replace a certificate

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2147]
Regarding certificates of different types, the documentation of `SSL_CTX_use_certificate` states:

>       The internal certificate store of OpenSSL can hold several private
>       key/certificate pairs at a time. The certificate used depends on the
>       cipher selected, see also SSL_CTX_set_cipher_list(3).

Please document what happens if several certificates of the **same&nbsp;type** are loaded successively. My expectation in this case is that the most recently loaded certificate **replaces** any previously loaded certificate of the same&nbsp;type. This also seems to be the implemented behaviour.

My use case for this is to *update* certificates while keeping the server running. If, in addition to simply replacing the certificate and possibly the certificate&nbsp;chain, there is anything unusual that should be taken into account regarding `SSL_CTX_use_certificate` for this use&nbsp;case, please also add it to the documentation. Thank&nbsp;you!

**Comment by vdukhovni** [comment]
Perhaps the best way to replace the certificate in a running process is to create and configure a new SSL_CTX, and then switch to using that new SSL_CTX.

Whether you do that and dispose of the original SSL_CTX or update the SSL_CTX in place, you need to make sure that no threads are currently using that original SSL_CTX before modifying it or disposing of it.

**Comment by triska** [comment]
> Perhaps the best way to replace the certificate in a running process is to create and configure a new SSL_CTX, and then switch to using that new SSL_CTX.

I sincerely hope that this can be *avoided* for this specific use&nbsp;case. The reason is that, as you correctly note, this must be made thread&nbsp;safe. However, from user's point of&nbsp;view, replacing the **context** is *much&nbsp;harder* to make thread safe than simply calling `SSL_CTX_use_certificate` to replace only the&nbsp;**certificate**. The reason is that in latter case, I expect the OpenSSL library itself to correctly handle multiple threads, by placing appropriate locks on the certificate in those parts of the code that destructively modify&nbsp;it or copy&nbsp;it (for example, if a new connection is initialized from a&nbsp;context). The library&nbsp;itself (or at least every sufficiently recent&nbsp;version) must guarantee&nbsp;this regardless of what `SSL_CTX_use_certificate` is actually *meant* to&nbsp;do when calling it multiple&nbsp;times with the same type of&nbsp;certificate, so I can rely on the OpenSSL&nbsp;library itself to do&nbsp;this. On the application level, I only have to ensure that I manage the used&nbsp;certificates in a thread&nbsp;safe way.

In contrast, when replacing the **context**, I have to manually place locks around all&nbsp;parts that may directly or indirectly use the&nbsp;context, which is at much coarser granularity than what would be sufficient in this&nbsp;case, and also much more error&nbsp;prone and a lot of redundant work for all affected&nbsp;applications. For instance, at the application level, I cannot place a lock at exactly the point where an existing context is&nbsp;copied, since this happens as one small part of higher-level OpenSSL library&nbsp;calls, which may take much longer to&nbsp;complete and therefore make locking much more&nbsp;impractical.

Still, I may have to resort to replacing the whole context in other use cases. An example of this is *removing* a certificate altogether from a context. As far as I can tell, there is no API for this&nbsp;(yet), so replacing the whole context may be the only way&nbsp;out. However, for simply *updating* a certificate, I really hope that `SSL_CTX_use_certificate` is sufficient, or can be made so more&nbsp;easily. Thank you very much for looking into&nbsp;this!

**Comment by snhenson** [comment]
You may find setting certificates at the SSL level instead of SSL_CTX is more appropriate for your use case. It is possible to clear all certificates from an SSL structure using SSL_certs_clear().

**Comment by triska** [comment]
A corresponding `SSL_CTX_certs_clear` (affecting the **context**) would be ideal for my use case, since this would allow me to *replace* and also to *remove*&nbsp;certificates from the&nbsp;context.

Please note that I need to clear the certificates for the *context* in order to propagate this to all connections that are negotiated using this context in the&nbsp;future. Connections that have already been negotiated can continue with the certificates they used at the time of the&nbsp;negotiation. Therefore, the SSL&nbsp;level is not ideal for my use&nbsp;case.

**Comment by triska** [comment]
I have now looked at the implementation of `SSL_CTX_use_certificate`: It seems to do precisely what I need in this case, i.e., it *replaces* an existing certificate of the same&nbsp;type. Therefore, my questions:

1. If applicable, could you please add this to the documentation, so that it is clear we can rely on this behaviour?
2. Is this call thread safe? If not, could you please make it thread safe, or alternatively document the conditions for its safe&nbsp;use?

For example, I see the following in `SSL_CTX_use_certificate`, used when replacing an existing certificate:

<pre>
    X509_free(c->pkeys[i].x509);
</pre>

In addition, when a new connection is initialized from a context with `SSL_new`, then `ssl_cert_dup` is called which contains:

<pre>
        CERT_PKEY *cpk = cert->pkeys + i;
        CERT_PKEY *rpk = ret->pkeys + i;
        if (cpk->x509 != NULL) {
            rpk->x509 = cpk->x509;
            X509_up_ref(rpk->x509);
        }
</pre>

There seems to be a race condition: A different thread could have replaced, by calling `SSL_CTX_use_certificate`, the certificate with a different one between any of these instructions, freeing the previous&nbsp;one and causing a reference to freed memory, potentially leading to a&nbsp;crash.

However, even if that is the&nbsp;case, I could mitigate this in the application by retaining a reference to the existing certificate, so that is not freed when it may still be needed by other&nbsp;threads. Alternatively, I could simply remove all other&nbsp;threads, exchange the certificate, and respawn the&nbsp;threads.

I would greatly appreciate if you could clarify these two&nbsp;issues (actual meaning of the call, and its thread&nbsp;safety) in the documentation. For long running servers, I would be very&nbsp;glad to use this functionality of the&nbsp;library, to exchange&nbsp;certificates while the server is&nbsp;running.

**Comment by richsalz** [comment]
As with all other openssl data structures, they are not thread-safe; you have to do application-level locking.

**Comment by triska** [comment]
Could you please clarify this? The [ChangeLog](https://www.openssl.org/news/cl110.txt) of version 1.1.0 states:

<pre>
  *) OpenSSL now uses a new threading API. <b>It is no longer necessary to
     set locking callbacks to use OpenSSL in a multi-threaded environment.</b> There
     are two supported threading models: pthreads and windows threads. It is
     also possible to configure OpenSSL at compile time for "no-threads". The
     old threading API should no longer be used. The functions have been
     replaced with "no-op" compatibility macros.
     [Alessandro Ghedini, Matt Caswell]
</pre>

What can I take for granted from this?

**Comment by kroeckx** [comment]
It means that you used to set locking callbacks before and that that is no longer required. It does not say anything about fixing all possible thread issues.

Some structures like X509 have a reference counter that you can change using something like X509_up_ref(). There is a lock for that, and that should should do the right thing. But that is just a reference counter. On the other hand if you call something like X509_set_ex_data() no lock is taken. It's best to call such function before you pass the X509 to anything. If we have to take locks to make that work properly in all cases things would get very complicated, and I also think that's a bad design.

In most cases, once you pass something you should not modify it anymore. The library becomes the owner and should internally be multi-thread safe. But if you start to modify things it probably won't be.

That being said, I think that if SSL makes a copy of the those things in the SSL_CTX, and adjusts the reference counter, it might be possible to support your use case. At first sight it looks like it just needs to take the lock in the SSL_CTX for that. But it's probably going to be more complicated than it looks at first sight.

**Comment by triska** [comment]
Thank you for this clarification. What I primarily care about in this case is that the actual functionality is *documented*, so that I know whether I can rely on&nbsp;it.

For example, it would be great for this use case if an explanation like the following were added to the documentation of `SSL_CTX_use_certificate`:

<pre>
If a certificate A of type T is already loaded into a context&nbsp;C, and you call
SSL_CTX_use_certificate to load a certificate&nbsp;B of that same type&nbsp;T into&nbsp;C,
then B <b>replaces</b>&nbsp;A in&nbsp;C.

Please note that this operation is not thread safe: While a certificate
is being replaced, other threads must not use the context.
</pre>

**Comment by richsalz** [comment]
Perhaps an overall statement in man7 sections saying that the objects cannot be used concurrently in multiple threads?

**Comment by triska** [comment]
That would definitely subsume the second sentence of the suggestion above.

For the specific use case I mentioned, I am also interested in covering the first sentence. Please consider adding a statement that covers&nbsp;it to the documentation as&nbsp;well.

**Comment by richsalz** [comment]
*any* modification of openssl data structures is not safe.  Your first sentence is just a special-case of the general warning.

**Comment by triska** [comment]
My impression is that your statements are becoming much too general: If you add a sentence like "the objects cannot be used concurrently in multiple threads", that would render almost all multi-threaded applications of the library&nbsp;invalid. If you add "*any* modification of OpenSSL data structures is not safe", I can no longer use the library at all, because I need to modify most data structures before I can use&nbsp;them. It seems to me that only much more specific usage patterns should be&nbsp;precluded.

What I, as a user of the library, would like to know is:

1. What the functions of the library are doing.
2. How I can use them safely.

You are now suggesting a solution to point (2). That's great, and part of my question. In addition, I would be very grateful for a solution of point&nbsp;(1) too, when you have&nbsp;time.

**Comment by kroeckx** [comment]
What I understand is that you want to document is that you can have different types of certificates, but only 1 of each type. And that if you try to use the same type again it removes the old one of that type and adds the new one. And that would clearly be useful to document.

**Comment by richsalz** [comment]
@triska what I am saying is this:  OpenSSL has never supported concurrent use of its data objects.  It might have worked in some cases, but the general rule has always been true.

**Comment by triska** [comment]
@richsalz: Currently, the documentation on OpenSSL [**threads**](https://www.openssl.org/docs/man1.0.2/crypto/threads.html) states (at least for version&nbsp;1.0.2):

<pre>
<b>OpenSSL can safely be used in multi-threaded applications</b> provided that at least two 
callback functions are set, locking_function and threadid_func.
</pre>

Could you please explain how this can be reconciled with your statement that "OpenSSL has never supported concurrent use of its data objects"? If necessary, please update the pertaining section in the documentation. Thank&nbsp;you!

**Comment by kaduk** [comment]
My understanding is that the OpenSSL model is that you create a SSL_CTX, potentially make modifications to its settings/configuration, then start making SSL objects from the SSL_CTX and never make any subsequent modifications to the SSL_CTX.  Attempting to deviate from that (i.e., modify the SSL_CTX object after SSL objects refer to it) may work with certain versions for some particular operations, but is not expected to be retained from version to version as an ABI compatibility guarantee.  That said, I think I blame @davidben for my understanding, so he can chime in here if I am wrong.

> Could you please explain how this can be reconciled with your statement that "OpenSSL has never supported concurrent use of its data objects"?

The safety for use in multi-threaded applications means that there is not (unlocked) global state in the library that could be modified by concurrent calls from different threads, such as a global error queue or a static counter for the next free index into an array.  The library itself will not corrupt itself if you make function calls into it from multiple threads, but each individual data structure is expected to be owned by a single thread only.

**Comment by kroeckx** [comment]
That at least matches my understanding, and maybe we should be
more clear in the documenatation about that.

**Comment by vdukhovni** [comment]
If I had to write an application that wanted to dynamically change the SSL_CTX used by future connections, I'd create a new SSL_CTX each time that is required, and use it for all new connections. The previous SSL_CTX can be freed once all the threads that used have exited.  Once all new SSL objects are built from the new SSL_CTX, one can IIRC call SSL_CTX_free() on the old SSL_CTX, and it will be automatically freed when destruction of the last associated SSL object decrements the retired SSL_CTX's refcount to zero.

I don't recall any documented MT-safe modifications of SSL_CTX, beyond calling SSL_new() which bumps up the SSL_CTX reference count, and SSL_free() which decrements the reference count.  While some updates may in fact be safe, there is AFAIK no "contract" to ensure said behaviour.

**Comment by kaduk** [comment]
I guess we should do what the OP requests and put a description of what we mean by thread safety and what is left to the application into the documentation.  Any thoughts about where would be best to put such a thing?

**Comment by richsalz** [comment]
for example, searching the mailing list about concurrent use of SSL objects for read and write in different threads ...

**Comment by triska** [comment]
@richsalz: OK, I have filed #2165 to discuss the more general issue of thread safety, which affects many other functions&nbsp;too.

For the present issue, I would be very grateful if one sentence were added to the documentation of `SSL_CTX_use_certificate`, describing what happens if a certificate of the same&nbsp;type as an already existing certificate is specified. This would solve this concrete&nbsp;issue for&nbsp;me. Thank&nbsp;you!

**Comment by richsalz** [comment]
Something like "If this function is called more than once with the same type of certificate (such as key and signature algorithm), the previous cert is free'd." ?

**Comment by vdukhovni** [comment]
Well, freed or not, the key observation is that any certificate/key of the same type is *replaced* by a new certificate/key of the same type.  Applications should call SSL_CTX_check_private_key(3) after replacing both, to check that the private key and certificate match.
