### ISSUE TITLE
EVP_Cipher API return value for AAD calls is unclear from documentation

### ISSUE THREAD

**Issue by samuel-lee-msft** [openssl/openssl#21485]
Using OpenSSL 1.1.1 or 3.x, using [EVP_Cipher](https://www.openssl.org/docs/man3.1/man3/EVP_Cipher.html#EVP_Cipher) with an AEAD cipher such as AES-GCM or Chacha20-Poly1305, it is possible to provide `AAD` by calling with a NULL `out` parameter before providing plaintext/ciphertext.

These AEAD ciphers have the `EVP_CIPH_FLAG_CUSTOM_CIPHER` flag set.

The documentation for 1.1.1 to present says the following about the return value:
> EVP_Cipher() returns the amount of encrypted / decrypted bytes, or -1 on failure if the flag EVP_CIPH_FLAG_CUSTOM_CIPHER is set for the cipher.

Strictly AAD is not encrypted or decrypted, so it is unclear whether the value returned should be:
`inl` (i.e. the number of AAD bytes ingested), or
`0` (i.e. the number of bytes written to out)

From a cursory look at the OpenSSL implementation, it would appear that the former has been what is returned from libcrypto today for AES-GCM and Chacha20-Poly1305, but I have not done an exhaustive search.

If the existing OpenSSL implementations are the intended behavior it should be clear in the documentation, and I would suggest that the documentation should read something like:
> EVP_Cipher() returns the number of bytes processed (i.e. encrypted / decrypted / authenticated), or -1 on failure if the flag EVP_CIPH_FLAG_CUSTOM_CIPHER is set for the cipher.

If alternatively it is just not supported to use EVP_Cipher with an AEAD cipher, this should be explicitly documented.

**Comment by t8m** [comment]
@samuel-lee-msft would you like to submit a PR with your suggestion? I think it is correct.

**Comment by samuel-lee-msft** [comment]
Sure, I'll make a PR

I'm not sure how documentation fixes are applied to previous versions, but I can make a PR against master in the first instance and we can cherry-pick it wherever it makes sense

**Comment by samuel-lee-msft** [comment]
Looking at this a bit closer when creating the PR, I realized that for AES wrap functions, the value returned is the number of bytes written to out (i.e. with padding added on encryption and padding removed on decryption), so I thought it was clearer to split out the cases of passing AAD specifically from encryption/decryption.

I also believe the same behaviour for AAD applies to outl for (En|De)cryptUpdate, so I called that out in the AEAD section.

Really I think that for AAD calls the return value _should_ be 0; but I tried to make the documentation reflect what I understand is the reality of the OpenSSL implementation today.

**Comment by t8m** [comment]
> Really I think that for AAD calls the return value _should_ be 0; but I tried to make the documentation reflect what I understand is the reality of the OpenSSL implementation today.

It would not be a good idea to change it as existing callers can depend on the current behavior. IMO it does not really matter, in terms of correctness of the API, whether 0 or inlen is returned.
