### ISSUE TITLE
OpenSSL chooses providers for operations they don't support

### ISSUE THREAD

**Issue by fhars** [openssl/openssl#21500]
My scenario:
  - I use OpenSSL 3.0.9 and tpm2-openssl 1.2.0-rc1
  - I use a program (Rauc 1.8 with some local changes to use ossl_store) that honors `OPENSSL_CONF` and uses the OpenSSL CMS API to decrypt and verify data that has been signed and encrypted with CMS. 
  - I have the default and the tpm2-openssl provider activated
  - The decryption key is a private key residing in a TPM, and can only be used using the tpm2-openssl provider.
  - The signing key has a 4096 bit RSA CA-key in its certificate chain.

As far as I can tell, there is no configuration that works for this case: 
 - I can tell OpenSSL to prefer the default provider (e.g., `?provider=!tpm2` as property query). In that case, it will use the tpm2-provider to load the private key, and then happily pass the PKEY object to the decryption routine of the default provider, which will balk on the inaccesible private key. 
 - Or I can tell OpenSSL to prefer the tpm2 provider (`?provider=tpm2`). In that case it can decrypt the data using the key stored in the TPM. But then it will defer all RSA operations to the TPM, which is inefficient for keys that are present as files, and will fail for the 4096-bit CA key, since most TPMs don't support larger keys than 2048 bit.

The same behaviour on the command line:
```
$ openssl cms -provider tpm2 -provider default -propquery '?provider=tpm'  -decrypt -in foo.enc -inkey handle:0x81008000
Foo
$ openssl cms -provider tpm2 -provider default -propquery '?provider!=tpm2'  -decrypt -in foo.enc -inkey handle:0x81008000
Error decrypting CMS using private key
8032D449897F0000:error:0800007D:elliptic curve routines:ossl_ecdh_simple_compute_key:missing private key:crypto/ec/ecdh_ossl.c:72:
$ openssl cms -provider tpm2 -provider default -propquery '?provider=tpm2' -verify -in foo.sig -CAfile chain.crt
WARNING:esys:src/tss2-esys/api/Esys_LoadExternal.c:314:Esys_LoadExternal_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_LoadExternal.c:108:Esys_LoadExternal() Esys Finish ErrorCode (0x000002c4) 
CMS Verification failure
80724A7B167F0000:error:4000000C:tpm2:ensure_key_loaded:cannot load key:src/tpm2-provider-signature.c:120:708 tpm:parameter(2):value is out of range or is not correct for the context
80724A7B167F0000:error:06880006:asn1 encoding routines:ASN1_item_verify_ctx:EVP lib:crypto/asn1/a_verify.c:196:
80724A7B167F0000:error:17000064:CMS routines:cms_signerinfo_verify_cert:certificate verify error:crypto/cms/cms_smime.c:289:Verify error: certificate signature failure
$ openssl cms -provider tpm2 -provider default -propquery '?provider!=tpm2' -verify -in foo.sig -CAfile chain.crt
Foo
CMS Verification successful
```

**Comment by t8m** [comment]
IMO this is some bug in the tpm2 provider where it exports a public key when it is actually asked to export a private key and it should fail that operation.

The `?provider!=tpm2` would work fine if the tpm2 provider properly refused to export the key instead of exporting just the public key.

**Comment by fhars** [comment]
But the tpm2 provider doesn't even know the public key, how can it export it?

Where in the code should I look to verify your suspision? Which datastructure would contain the wrong information at which moment in the execution, and how do I detect it?

**Comment by fhars** [comment]
And even if that fixes the `?provider!=tpm2` case, the '?provider=tpm2` case would still be broken, as the tpm2 provider is then still chosen fo an operation it does not support, no?

**Comment by t8m** [comment]
The `?provider=tpm2` case is know to be broken unless you use the query string only when you want to explicitly use the tpm2 provider if available. You cannot use it as default property query. This limitation is by design so this is not a bug.

**Comment by t8m** [comment]
There is a bug in https://github.com/tpm2-software/tpm2-openssl/blob/master/src/tpm2-provider-keymgmt-rsa.c#L549-L589 tpm2_rsa_keymgmt_export() function will export a public key even if the selection contains the OSSL_KEYMGMT_SELECT_PRIVATE_KEY bit.

**Comment by t8m** [comment]
Similarly for EC keys export function.

**Comment by fhars** [comment]
Yes, thanks, adding a strategic
```C
    if ((selection & OSSL_KEYMGMT_SELECT_PRIVATE_KEY) != 0)
        return 0;
```
in the export functions seems to fix my use case.
