### ISSUE TITLE
Unreachable code and many other problems in x509\by_file.c

### ISSUE THREAD

**Issue by nv-dmd** [openssl/openssl#21534]
OpenSSL 3.0, 3.1, master

I see a number of problems in file x509\by_file.c:
1) Unreachable code
It is impossible to get to lines 146-147 and 208-209
```
if (ret == 0)
    ERR_raise(ERR_LIB_X509, X509_R_NO_CERTIFICATE_FOUND);
```
in functions `X509_load_cert_file_ex()`  and `X509_load_crl_file`

2) Lots of redundant code
For example, in function `X509_load_cert_file_ex`
on line 99, if `in` equal NULL call goto and execute free `in` (it`s NULL) and `x` (it`s NULL also). On lines 132-133 execute free `x`, but after that we go to the lines under `err`, where we free again `x`.
And similar in other places in code.

3) No oiptimal check
On lines 104-107 in `X509_load_cert_file_ex` there is check 
```
if (type != X509_FILETYPE_PEM && type != X509_FILETYPE_ASN1) {
    ERR_raise(ERR_LIB_X509, X509_R_BAD_X509_FILETYPE);
    goto err;
}
```
but it would be more optimal to use `else` on line 146 instead of it

4) Breaking the code style

What about this? Can I fix it all in one PR?

**Comment by t8m** [comment]
In general just cleanups or refactorings should go into master branch. If there is anything that is a bug fix (unreachable code isn't such case, but maybe some unreachable code can be a consequence of a bug), it should go into all 3.x branches. 

So please submit one PR for this kind of changes but if you find a bug, a separate PR for 3.x backport might be needed.
