### ISSUE TITLE
A typo in openssl-pkeyutil(1) manpage

### ISSUE THREAD

**Issue by hkc94501** [openssl/openssl#21543]
Openssl version 3 and above.
Manual page for openssl-pkeyutil.
### RSA-PSS ALGORITHM
We find the following sentence:

> If the key has parameter restrictions than the digest, MGF1 digest and salt length are set to the values specified in the parameters.<

I cannot parse that sentence.  perhaps s/than/then/   That would make sense.

**Comment by t8m** [comment]
Yes, s/than/then/ is the correct fix. Would you like to submit a PR? (It would be acceptable with CLA: trivial).
