### ISSUE TITLE
X509 Error Loading Extensions

### ISSUE THREAD

**Issue by ayesjm** [openssl/openssl#2155]
i am trying to update a certificate for vm upgrade manager and using the following command:

openssl req -x509 -sha256 -newkey rsa:2048 -keyout rui.key -extensions x509 -config updatemanager.cfg -out rui.crt -days 3650 

i get the following error message: 

Error Loading extension section x509 - 

anyone have any insight? i am using OpenSSL 1.0.2h (64-bit) on windows 2008 r2

**Comment by vdukhovni** [comment]
This is not a source code issue. Post a question to the openssl-users list instead. Closing.
