### ISSUE TITLE
core dump ssleay_rand_bytes 

### ISSUE THREAD

**Issue by ylkcy** [openssl/openssl#21557]
openssl version: 1.0.2o

stack:
#0  0x00007fedd246251c in sha1_block_data_order_shaext () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#1  0x00007fedd2460227 in SHA1_Update () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#2  0x00007fedd252f207 in ssleay_rand_add () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#3  0x00007fedd252f658 in ssleay_rand_bytes () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#4  0x00007fedd251c5cb in RSA_padding_add_PKCS1_OAEP_mgf1 () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#5  0x00007fedd251c86a in RSA_padding_add_PKCS1_OAEP () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#6  0x00007fedd251abd6 in RSA_eay_public_encrypt () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#7  0x00007fedd24025b9 in CFtdcUserApiImplBase::UserApiEncryptAlg(char const*, int, char*, int&) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#8  0x00007fedd240338f in CFtdcUserApiImplBase::AddEncryptField(CUFIntType const&) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#9  0x00007fedd240760f in CFtdcUserApiImplBase::OnRspQryCryptInfo(CFTDCPackage*) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#10 0x00007fedd2407ca5 in CFtdcUserApiImplBase::HandlePackage(CFTDCPackage*, CFTDCSession*) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#11 0x00007fedd23c810d in CProtocol::HandlePackage(CPackage*, CProtocol*) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#12 0x00007fedd23cc044 in CCompressProtocol::Pop(CPackage*) () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#13 0x00007fedd23c810d in CProtocol::HandlePackage(CPackage*, CProtocol*) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#14 0x00007fedd23c810d in CProtocol::HandlePackage(CPackage*, CProtocol*) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#15 0x00007fedd23c8b85 in CChannelProtocol::HandleInput() () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#16 0x00007fedd2414d27 in CSelectReactor::DispatchIO(fd_set&, fd_set&, bool) ()
   from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#17 0x00007fedd2415135 in CSelectReactor::DispatchIOs() () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#18 0x00007fedd2413b19 in CEventDispatcher::Run() () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#19 0x00007fedd2414469 in CThread::_ThreadEntry(void*) () from libs20230725/home/ldpfutu/bin/bizcomponents/libmduserapi.so
#20 0x00007fee051f0f2b in ?? () from libs20230725/usr/lib64/libpthread.so.0
#21 0x00007fee051286bf in clone () from libs20230725/usr/lib64/libc.so.6

disass:
   0x00007fedd24624d7 <+471>:   sha1msg1 %xmm4,%xmm7
   0x00007fedd24624db <+475>:   sha1msg2 %xmm5,%xmm6
   0x00007fedd24624df <+479>:   movdqa %xmm0,%xmm1
   0x00007fedd24624e3 <+483>:   sha1rnds4 $0x3,%xmm2,%xmm0
   0x00007fedd24624e8 <+488>:   sha1nexte %xmm4,%xmm1
   0x00007fedd24624ec <+492>:   pxor   %xmm5,%xmm7
---Type <return> to continue, or q <return> to quit---
   0x00007fedd24624f0 <+496>:   sha1msg2 %xmm6,%xmm7
   0x00007fedd24624f4 <+500>:   movdqu (%rsi),%xmm4
   0x00007fedd24624f8 <+504>:   movdqa %xmm0,%xmm2
   0x00007fedd24624fc <+508>:   sha1rnds4 $0x3,%xmm1,%xmm0
   0x00007fedd2462501 <+513>:   sha1nexte %xmm5,%xmm2
   0x00007fedd2462505 <+517>:   movdqu 0x10(%rsi),%xmm5
   0x00007fedd246250a <+522>:   pshufb %xmm3,%xmm4
   0x00007fedd246250f <+527>:   movdqa %xmm0,%xmm1
   0x00007fedd2462513 <+531>:   sha1rnds4 $0x3,%xmm2,%xmm0
   0x00007fedd2462518 <+536>:   sha1nexte %xmm6,%xmm1
=> 0x00007fedd246251c <+540>:   movdqu 0x20(%rsi),%xmm6
   0x00007fedd2462521 <+545>:   pshufb %xmm3,%xmm5
   0x00007fedd2462526 <+550>:   movdqa %xmm0,%xmm2
   0x00007fedd246252a <+554>:   sha1rnds4 $0x3,%xmm1,%xmm0
   0x00007fedd246252f <+559>:   sha1nexte %xmm7,%xmm2
   0x00007fedd2462533 <+563>:   movdqu 0x30(%rsi),%xmm7
   0x00007fedd2462538 <+568>:   pshufb %xmm3,%xmm6
   0x00007fedd246253d <+573>:   movdqa %xmm0,%xmm1
   0x00007fedd2462541 <+577>:   sha1rnds4 $0x3,%xmm2,%xmm0
   0x00007fedd2462546 <+582>:   sha1nexte %xmm9,%xmm1
   0x00007fedd246254b <+587>:   pshufb %xmm3,%xmm7
   0x00007fedd2462550 <+592>:   paddd  %xmm8,%xmm0
   0x00007fedd2462555 <+597>:   movdqa %xmm1,%xmm9
   0x00007fedd246255a <+602>:   jne    0x7fedd2462350 <sha1_block_data_order_shaext+80>
   0x00007fedd2462560 <+608>:   pshufd $0x1b,%xmm0,%xmm0
   0x00007fedd2462565 <+613>:   pshufd $0x1b,%xmm1,%xmm1
   0x00007fedd246256a <+618>:   movdqu %xmm0,(%rdi)
   0x00007fedd246256e <+622>:   movd   %xmm1,0x10(%rdi)
   0x00007fedd2462573 <+627>:   repz retq 

memory:
0x7fedd2b7ffd8: 0x0000000000000000      0x0000000000000000
0x7fedd2b7ffe8: 0x0000000000000000      0x0000000000000000
0x7fedd2b7fff8: 0x0000000000000000       0xffffffffffffffff
0x7fedd2b80008: 0x000000000004ce00      0x000000000004d280
0x7fedd2b80018: 0x000000000004e330      0x0000000000058de0
0x7fedd2b80028: 0x0000000000059c90      0x000000000005b8f0
0x7fedd2b80038: 0x0000000000068210      0x000000000007c460
0x7fedd2b80048: 0x00000000000a1e10      0x0000000000000000

**Comment by mattcaswell** [comment]
Unfortunately OpenSSL 1.0.2 is no longer supported by the project (except via a paid for support contract).

**Comment by ylkcy** [comment]
Does the latest version fix this issue?

**Comment by t8m** [comment]
> Does the latest version fix this issue?

This might not even be an OpenSSL issue at all but some problem in the application calling it.
