### ISSUE TITLE
openssl s_client -connect does not work

### ISSUE THREAD

**Issue by shantouchen** [openssl/openssl#21563]
Hi Openssl,

I build 3.1.0 on my Windows 10 machine, and integrated it to my own application. During testing I found that getaddrinfo() returns null address. Then I tried to check if openssl.exe works, and got following results:

```
C:\Users\t9167\source\repos\openssl-3.1.0\apps>openssl s_client -connect https://www.google.com
00410000:error:10080002:BIO routines:BIO_lookup_ex:system lib:crypto\bio\bio_addr.c:738:The specified class was not found.
connect:errno=10109
```

To verify, I downloaded a pre-compiled 3.1.1 package from a website listed in Openssl's webpage. I got the same results.

```
C:\Users\t9167\Downloads\openssl-3.1.1\openssl-3\x86\bin>openssl s_client -connect https://wwww.google.com
34250000:error:10080002:BIO routines:BIO_lookup_ex:system lib:..\crypto\bio\bio_addr.c:738:The specified class was not found.
connect:errno=10109
```

Could you please check if this is a bug?

Thanks,
Feng Chen

**Comment by mattcaswell** [comment]
From the man page for s_client:

````
       -connect host:port
           This specifies the host and optional port to connect to. It is
           possible to select the host and port using the optional target
           positional argument instead.  If neither this nor the target
           positional argument are specified then an attempt is made to
           connect to the local host on port 4433.
````

It does *not* take a URI but a host and optional port. So to connect to https://www.google.com you need to use the https port (443), i.e. the correct syntax is `-connect www.google.com:443`

**Comment by shantouchen** [comment]
Thanks a lot!
Sorry for my ignorance.

Have a good day.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
