### ISSUE TITLE
Error in verify certificate signature 

### ISSUE THREAD

**Issue by junniorcarlos** [openssl/openssl#21589]
Hi everyone,

I'm facing a issue in Openssl that I trying to verify the certificate, I"m using currently the Openssl version 1.0.2u through  this command
openssl verify -CAfile and brought  the following  message:

 error 7 at 0 depth lookup:certificate signature failure
139637387744576:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:rsa_sign.c:220:
139637387744576:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:170

I'm tested with other certificates and the message given is OK, I'm already checked too, the signature is the same to verify the certificate.

```[tasklist]
### Tasks
```

**Comment by t8m** [comment]
1.0.2u is unsupported (apart from premium support).

Have you tried newer versions? Also without the certificates which cause this, there is not much we can help with here.

**Comment by t8m** [comment]
No response. Closing.
