### ISSUE TITLE
ssl3_get_message() is mentioned in source code comments, but it does not exist

### ISSUE THREAD

**Issue by fwh-dc** [openssl/openssl#21582]
I expect the name to have changed at some point, what is the new name?

**Comment by mattcaswell** [comment]
It got split into two in OpenSSL 1.1.0 and is now called `tls_get_message_header` and `tls_get_message_body`

**Comment by heygauri** [comment]
Hello, I'm interested in contributing to this issue. Additionally, I'd like to clarify the scope of the work involved. It seems that the tasks can be summarized as follows:

- Replacing instances of "ssl3_get_message()" with "tls_get_message_header" or "tls_get_message_body" in source code comments.
- Ensuring that the documentation is updated to reflect these changes.

Could you please confirm if this understanding is accurate? If so, I'm keen on working on this issue. Thank you!

**Comment by mattcaswell** [comment]
> Replacing instances of "ssl3_get_message()" with "tls_get_message_header" or "tls_get_message_body" in source code comments.

Yes.

> Ensuring that the documentation is updated to reflect these changes.

As far as I can tell this isn't referred to anywhere outside of the source code comments so there shouldn't be anything else to do.

You should target the master branch in any change that you make.
