### ISSUE TITLE
OCSP verify produces misleading errors when -VAfile certificate has expired

### ISSUE THREAD

**Issue by tlhackque** [openssl/openssl#2159]
OpenSSL 1.0.2h  3 May 2016

When ocsp is used to verify a certificate and the (responder) certificate specified by -VAfile has expired, ocsp should report an error related to the -VAfile certificate.   (E.g. "responder certificate expired")

Instead, it reports errors indicating corruption of the response, including:
````
Response Verify Failure
3086837916:error:04067084:rsa routines:RSA_EAY_PUBLIC_DECRYPT:data too large for modulus:rsa_eay.c:670:
3086837916:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:218:
3086837916:error:27069075:OCSP routines:OCSP_basic_verify:signature failure:ocsp_vfy.c:105:

and

Response Verify Failure
139938102994800:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:rsa_pk1.c:102:
139938102994800:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:rsa_eay.c:797:
139938102994800:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:241:
139938102994800:error:27069075:OCSP routines:OCSP_basic_verify:signature failure:ocsp_vfy.c:101:
````

This led to several weeks of troubleshooting, as there were legitimate data corruption issues with a responder just prior to its certificate's expiration.  Thus, certificate expiration masqueraded as a recurrence of those issues.

The attached .zip file can be used to demonstrate this issue.  It includes a valid certificate (avh.cer), an issuer cert (root_bundle.crt), an expired responder certificate (startcom_ocsp_dec16.pem) and a current responder certificate (startcom_ocsp.pem).

Below is the full failing command with output:
````
openssl ocsp -issuer root_bundle.crt -cert avh.crt -url http://ocsp.startssl.com -header 'host' 'ocsp.startssl.com' -CAfile /mnt/wikiworld/usr/local/share/perl5/Mozilla/CA/cacert.pem   -VAfile startcom_ocsp_dec16.pem
WARNING: no nonce in response
Response Verify Failure
3086837916:error:04067084:rsa routines:RSA_EAY_PUBLIC_DECRYPT:data too large for modulus:rsa_eay.c:670:
3086837916:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:218:
3086837916:error:27069075:OCSP routines:OCSP_basic_verify:signature failure:ocsp_vfy.c:105:
avh.crt: good
        This Update: Dec 30 10:29:17 2016 GMT
        Next Update: Jan  3 10:39:17 2017 GMT
````

A reasonable error would be something like "Certificate in -VAfile invalid: expired"

With the valid certificate in -VAfile, the sample certificate validates normally.

[expired.ZIP.txt](https://github.com/openssl/openssl/files/678600/expired.ZIP.txt)

**Comment by mattcaswell** [comment]
Since this is not 1.1.1 specific (impacts 1.0.2), removing the 1.1.1 milestone.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
