### ISSUE TITLE
OpenSSL security team PGP key should be listed on source page

### ISSUE THREAD

**Issue by atsampson** [openssl/openssl#21617]
The OpenSSL 1.1.1v release is signed with a new "OpenSSL security team" PGP key EFC0A467D613CB83C7ED6D30D894E2CE8B3D79F5. This is available from keyservers but I couldn't see an obvious way to verify that it's legitimate.

On the [source page](https://www.openssl.org/source/), it says <q>PGP keys for the signatures are available from the [OTC page](https://www.openssl.org/community/otc.html)</q>, but this new key isn't on that list, and it also wasn't mentioned in the release announcement or the blog. (Other projects that use a "team" key for signing releases usually announce when it changes and how long it will be valid for.)

**Comment by t8m** [comment]
There is one way to confirm that it is legitimate - you can find the fingerprint of the key in the doc/fingerprints.txt file of the previously released tarballs.

But yeah I agree the website should be fixed.

**Comment by t8m** [comment]
https://github.com/openssl/web/pull/415 fixes this.

**Comment by atsampson** [comment]
Brilliant - thanks!
