### ISSUE TITLE
Configure List of External Pre Shared Keys

### ISSUE THREAD

**Issue by Tamec1** [openssl/openssl#21640]
### Discussed in https://github.com/openssl/openssl/discussions/21520

<div type='discussions-op-text'>

<sup>Originally posted by **Tamec1** July 21, 2023</sup>
According to the TLS 1.3 rfc8446 the client should be able to send a list of PSK Identities 
within its Pre-Shared Key extension (https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.11).

We are implementing TLS 1.3 Server & Client within our application using OpenSSL 3.1.0
using the callback pair SSL_CTX_set_psk_use_session_callback & SSL_CTX_set_psk_find_session_callback
to set up PSK sessions with externally established PSKs.

But we could not find a suitable API functionality to configure a client to send multiple PSK identities
in the corresponding extension. the psk_use_session_callback only allows to set one 
const unsigned char* id with size_t idlen

Did we miss something or is it possible that sending multiple psk ids is not yet supported by the library?

Thanks in advance!

Kind regards
Tamec

</div>

**Comment by mattcaswell** [comment]
Closing this since it is a repeat of a discussion item
