### ISSUE TITLE
AFL++ fuzzer takes a  long time

### ISSUE THREAD

**Issue by toralf** [openssl/openssl#21645]
Fuzz testing gave for bignum a long runtime - but I do run the AFL with AFL_SKIP_CPUFREQ=1 - is that the culprit or shall I expect for _bignum_ such long runtime values ?

One reproducer (more are under ./defaults within that archive):
```
$ time ./bignum-test default/hangs/id\:000000\,src\:000020\,time\:2829871\,execs\:3384009\,op\:havoc\,rep\:16 
# default/hangs/id:000000,src:000020,time:2829871,execs:3384009,op:havoc,rep:16

real    3m36.656s
user    3m36.056s
sys     0m0.038s
```
or
```
# default/hangs/id:000004,src:000020+000427,time:2837663,execs:3388228,op:splice,rep:2

real    24m34.725s
user    24m31.106s
sys     0m0.037s
```
[openssl_bignum_20230803-123300_1e7cc86b7516.tar.gz](https://github.com/openssl/openssl/files/12251822/openssl_bignum_20230803-123300_1e7cc86b7516.tar.gz)

 uname -a
Linux mr-fox 6.4.8 #9 SMP Thu Aug  3 09:33:23 UTC 2023 x86_64 AMD Ryzen 9 5950X 16-Core Processor AuthenticAMD GNU/Linux

**Comment by toralf** [comment]
FWIW I observed for "decoder" fuzzer runtimes of half a minute and more.

**Comment by nhorman** [comment]
What run times are you comparing them to?  you have two time outputs above, 1 at 3 minutes and one at 25.  What openssl versions were used in each?

**Comment by toralf** [comment]
do wonder if this is solved with issue #15356 too ?

**Comment by nhorman** [comment]
Unsure, did you recheck with the latest master branch?

**Comment by toralf** [comment]
> Unsure, did you recheck with the latest master branch?

yes, at least I do use the default: https://github.com/toralf/fuzz-utils/blob/main/fuzz-lib-openssl.sh#L41

**Comment by nhorman** [comment]
@toralf in the older bug (duplicated here), you describe this problem as, not a hang, but rather excessively long run times (ranging above from 3 to 25 minutes).  I think that it is likely as @davidben described in the other ticket, an artifact of the size of the input buffer that AFL fuzz provides.  I'm trying to get alf-clang-fast to work properly on my workstation to confirm, but that certainly sounds like the case.

**Comment by kroeckx** [comment]
We do that for some other fizzers too, and might want to do it for all of them.

**Comment by kroeckx** [comment]
We've told oss fuzz not to test files bigger than 1200 bytes for bignum, because the math just takes too long. Even 1200 doesn't really make sense. Maybe we should enforce that limit in the fuzzer instead of having an external file for it.

**Comment by nhorman** [comment]
@toralf since I don't have the AFL fuzzer running yet, could you test with this patch please:
https://github.com/openssl/openssl/pull/25013

It limits bignum generation to be no more than 128 bytes for any value.  thats probably too small, but if it makes your latency abate, we can probably be sure we're on the right track here

**Comment by toralf** [comment]
> @toralf since I don't have the AFL fuzzer running yet, could you test with this patch please: #25013

Sure, usually it takes few hours before AFL complaint.
FWIW _asn1_ and _decode_ are 2 more OpenSSL fuzzers where I had to call AFL++ with "-t 5" and "-t 10" respectively to avoid that AFL++ detects a too long runtime as a "hang".

**Comment by nhorman** [comment]
Thanks, looks like I'm not getting AFL running anytime soon on my workstation:
https://bugzilla.redhat.com/show_bug.cgi?id=2297764

**Comment by toralf** [comment]
> @toralf since I don't have the AFL fuzzer running yet, could you test with this patch please: #25013
> 
> It limits bignum generation to be no more than 128 bytes for any value. thats probably too small, but if it makes your latency abate, we can probably be sure we're on the right track here

It is the right track, _bignum_ now run flawlessly.

FWIW I reduced the fuzzer set to bignum, decoder and asn. The fuzzer decoder complaints about "hangs" (== too long runtime) too, asn1 is not yet tested.

**Comment by nhorman** [comment]
Ok, so I suppose the question then is, what is an appropriate size to fuzz on.  128 byte bignum, just based on gut feeling, seems small.  128 bytes  makes for at most 1024 bit keys.  Is that sufficient for fuzz testing?

**Comment by nhorman** [comment]
@toralf I've updated the PR to use 512 bytes as the max, can you please test again?

**Comment by toralf** [comment]
> @toralf I've updated the PR to use 512 bytes as the max, can you please test again?

works fine, no hangs

**Comment by nhorman** [comment]
ok, I'll take it out of draft then
