### ISSUE TITLE
Add X509_STORE_CTX_set_get_crl and X509_STORE_CTX_set_current_reasons

### ISSUE THREAD

**Issue by vm-vloz** [openssl/openssl#21679]
Hello,

I work on a product that supplies its own Certificate Revocation List when verifying a certificate.
In OpenSSL 1.0.2, this was done by setting a callback to X509_STORE_CTX->get_crl.

Currently, in OpenSSL 3.x, setting the get_crl callback must be done by calling X509_STORE_set_get_crl and then creating a X509_STORE_CTX object using the X509_STORE object.
But, this may not always be practical (or possible).
Our product uses SSL_CTX_set_cert_verify_callback in conjunction with X509_STORE_CTX->get_crl. When the verify_callback is invoked, the X509_STORE_CTX object has already been created, and recreating it is not possible.

In addition, X509_STORE_CTX->get_crl cannot work properly without the ability to modify X509_STORE_CTX->current_reasons. Please see a prior issue for more details: https://github.com/openssl/openssl/issues/10211

As such, please consider adding methods X509_STORE_CTX_set_get_crl and X509_STORE_CTX_set_current_reasons.

I am able to contribute these changes myself, but I wanted to first gauge the interest of such a change and verify that these methods are not purposefully left out.

**Comment by vm-vloz** [comment]
@t8m The changes for this feature were merged to master.
Would it be OK to crossport this change to openssl-3.0 and openssl-3.1 branches?
If so, I can do this work.

**Comment by t8m** [comment]
Unfortunately this is a new feature and as such it is not eligible for stable branches. OTC could hold a vote to give an exception for this feature. Not sure how much it is likely whether the vote would pass.
