### ISSUE TITLE
rand_win.c may use BCryptGenRandom with BCRYPT_USE_SYSTEM_PREFERRED_RNG

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#2168]
I believe there's a few issues with [rand_win.c](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_win.c).

First, `BCryptGenRandom` is called with `BCRYPT_USE_SYSTEM_PREFERRED_RNG`. On some version of Windows, I believe that's the infamous Dual EC generator. Apparently Microsoft has been infiltrated by the NSA, too (as if [`NSA_KEY`](https://en.wikipedia.org/wiki/NSAKEY) was not evidence enough).

Second, `BCryptGenRandom` is used without a call to `BCryptOpenAlgorithmProvider`. I'm fairly certain using `BCryptOpenAlgorithmProvider` like below avoids Dual EC. Its not as convenient as using `BCRYPT_USE_SYSTEM_PREFERRED_RNG` (gee, what a coincidence):

```
#ifdef RAND_WINDOWS_USE_BCRYPT
# include <bcrypt.h>
# ifndef BCRYPT_SUCCESS
#  define BCRYPT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)
# endif
#else
# include <wincrypt.h>
#endif
...

#if RAND_WINDOWS_USE_BCRYPT
NTSTATUS ret = ::BCryptOpenAlgorithmProvider(&m_handle,
                                             BCRYPT_RNG_ALGORITHM,
                                             MS_PRIMITIVE_PROVIDER, 0);
ASSERT(BCRYPT_SUCCESS(ret));
...
#endif
```

Third, the Bcrypt library defines success as `(NTSTATUS)ret >= 0`, and not `(NTSTATUS)ret == STATUS_SUCCESS`.

**Comment by Mari2411** [comment]
(NTSTATUS)ret >= 0, (NTSTATUS)ret 

== STATUS_SUCCESS

**Comment by richsalz** [comment]
Fixed with the recent RAND system updates.
