### ISSUE TITLE
How to wait until SSL_stream_conclude() is done

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#21688]
The manpage of SSL_stream_conclude() says that all data will be written in a reliable manner. Is there some way to know that this happened? When can SSL_free() be called on the QUIC stream SSL object?

It seems you can call this on an QUIC connection SSL object. Is that just for the default stream mode?

**Comment by t8m** [comment]
> It seems you can call this on an QUIC connection SSL object. Is that just for the default stream mode?

Yes, that should be kind of obvious but perhaps the documentation should be cleared - currently it says `If called on a QUIC connection SSL object, it signals the end of the single stream to the peer.` which is confusing.

**Comment by t8m** [comment]
> The manpage of SSL_stream_conclude() says that all data will be written in a reliable manner. Is there some way to know that this happened? When can SSL_free() be called on the QUIC stream SSL object?

To enforce reliable delivery SSL_shutdown() without SSL_SHUTDOWN_FLAG_NO_STREAM_FLUSH must be called and checked for 1 being returned before the SSL_free() can be called. Or of course application protocol signalling can be used.

**Comment by mattcaswell** [comment]
> > The manpage of SSL_stream_conclude() says that all data will be written in a reliable manner. Is there some way to know that this happened? When can SSL_free() be called on the QUIC stream SSL object?
> 
> To enforce reliable delivery SSL_shutdown() without SSL_SHUTDOWN_FLAG_NO_STREAM_FLUSH must be called and checked for 1 being returned before the SSL_free() can be called. Or of course application protocol signalling can be used.

The question was about calling SSL_free() on the *stream* SSL object. You should be able to do that immediately after SSL_stream_conclude(). Any unsent/unacked data will continue to be sent while the connection is still active.

The above answer is of course correct when we are talking about the QUIC connection SSL object.

**Comment by t8m** [comment]
> The question was about calling SSL_free() on the _stream_ SSL object.

Ah yeah, I've somehow overlooked that.

**Comment by t8m** [comment]
I think that in the end resolving that in the application protocol is the right fix. Because checking that data was delivered to the peer is not equal to the peer actually confirming that it accepted that data. It could be just sitting in the receive buffers of the peer and not being really used by the peer's application.

**Comment by hlandau** [comment]
> So there is no API to check the reliable delivery per stream? I'm wondering if this is a problem for some applications or not, where the connection stays open for a long time, but you create streams from time to time. I guess this can either be handled in the application protocol or you could use SSL_read() and check for SSL_ERROR_ZERO_RETURN to check that the other side also did a stream conclude.

It's not really any different to TCP. Even if TCP data is acked by a peer, this just means the peer's kernel received it, not that it made it to the application. While we could have some kind of "is stream totally acked" API even this doesn't mean the data acked by the peer has been actually read and processed by an application. Fundamentally if you want to handle application-level messages reliably the processing of those messages needs to be acknowledged at an application level.

> This of course makes me wonder how the application knows on which SSL object SSL_read() should be called.

In the future we will need to have some select() like call. Admittedly this is a fairly major capability like gap at the moment.

**Comment by kroeckx** [comment]
> It's not really any different to TCP.

But you can get that behaviour with TLS, if you rely on the other side to call SSL_shutdown() after it has received and processed all the data.

I do agree that it would be better to handle this at the application level.

**Comment by hlandau** [comment]
> > It's not really any different to TCP.
> 
> But you can get that behaviour with TLS, if you rely on the other side to call SSL_shutdown() after it has received and processed all the data.
At the connection level you can do this with `SSL_shutdown`, of course. At the stream level QUIC doesn't really provide any protocol semantics to allow an application to communicate "I have processed everything".

*If* you are using an RPC-style application-layer protocol which has a strict request-response pattern on each bidirectional stream, you could of course take a FIN sent by the peer after its response as indication that application processing has been completed.

We *could* provide an API along the lines of `SSL_is_all_stream_data_acked` (better name needed), and I'm not massively against providing this, but my feeling is it is going to lull applications into a false sense of security and encourage poor application protocol design. Just because a QUIC engine has acked something doesn't mean the peer application has called SSL_read, so it's not that useful.

**Comment by t8m** [comment]
> We _could_ provide an API along the lines of `SSL_is_all_stream_data_acked` (better name needed), and I'm not massively against providing this, but my feeling is it is going to lull applications into a false sense of security and encourage poor application protocol design. Just because a QUIC engine has acked something doesn't mean the peer application has called SSL_read, so it's not that useful.

Yeah, I do not think providing this would be a good idea.

**Comment by hlandau** [comment]
Deferred until after 3.2.0

**Comment by hlandau** [comment]
Not for 3.3. Not necessarily a good idea either.

**Comment by hlandau** [comment]
@nhorman Not for 3.3. I am dubious whether this is a good idea. Definitely not earlier than 3.4.

**Comment by nhorman** [comment]
Ok, lets consider this for 3.4 then

**Comment by nhorman** [comment]
@hlandau any thoughts on this?  Should we still consider this?  If not, please close

**Comment by nhorman** [comment]
Agreed, and thank you
