### ISSUE TITLE
Documentation of EVP_blake2b_512 and EVP_blake2s_256

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2169]
On the man page for `$ man EVP_blake2b_512`, we see with OpenSSL 1.1.0c:

<pre>
const EVP_MD *EVP_<b>blake2b_512</b>(void);
const EVP_MD *EVP_<b>blake2s_256</b>(void);</b>
</pre>

However, the *actual* names of these functions are, respectively (see `evp.h`):

<pre>
const EVP_MD *EVP_<b>blake2b512</b>(void);
const EVP_MD *EVP_<b>blake2s256</b>(void);
</pre>

Please change either the functions or their prototypes in the man page so that the names match.

Thank you!

**Comment by richsalz** [comment]
the manpage will be fixed, thanks!
