### ISSUE TITLE
crypto/x509/x509_cmp.c: return value of i2d_X509_NAME is not checked

### ISSUE THREAD

**Issue by 3lswear** [openssl/openssl#21694]
OpenSSL 3.0, 3.1, master

Function `i2d_X509_NAME()` is called in functions `X509_NAME_hash_old`, `X509_NAME_hash_ex` (file crypto/x509/x509_cmp.c, lines [297](https://github.com/openssl/openssl/blob/6d38ccedb25f31dfab232e2669415fd4db18b20e/crypto/x509/x509_cmp.c#L297C1-L297C28), [328](https://github.com/openssl/openssl/blob/6d38ccedb25f31dfab232e2669415fd4db18b20e/crypto/x509/x509_cmp.c#L328) ) and its return value isn't checked in these 2 instances, but checked in others.

Per documentation, `i2d_TYPE()` returns negative value if an error has occurred. Should I submit a PR to add checks of return value of  `i2d_X509_NAME()` for these 2 instances?

**Comment by t8m** [comment]
Yes, a PR is definitely welcome!

**Comment by 3lswear** [comment]
Thank you for a timely response!
