### ISSUE TITLE
ssl2

### ISSUE THREAD

**Issue by Xurcr0h** [openssl/openssl#217]
If I try to use -ssl2 it tells me: unknown parameter. Do you have the same issue or does anyone know, why its not working? ssl3 and the tls versions are working properly.

**Comment by mattcaswell** [comment]
What version of OpenSSL are you using it and where did you get it from? If you're using a distro version then it is quite likely that SSLv2 support has been compiled out as it is considered insecure.

**Comment by steakknife** [comment]
Matt's advice is solid: SSLv2 is terrible these days.  [SSLv3 is not good either](https://disablessl3.com/) and should also be avoided for green-field deployments.

**Comment by mattcaswell** [comment]
No response from OP. Closing this issue.
