### ISSUE TITLE
Rename SSL_set_initial_peer_addr() to set1

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#21701]
The function `SSL_set_initial_peer_addr()` has been newly introduced into the master branch. It sets the BIO_ADDR for the remote peer for a QUIC connection.

Shouldn't this function really be called `SSL_set1_initial_peer_addr`? Ownership of the BIO_ADDR is not passed as part of the function call and so the caller is still responsible for freeing it afterwards.

There is no mention of the memory semantics on the man page, so either way this should probably be clarified.

**Comment by tom-cosgrove-arm** [comment]
@mattcaswell should this be a discussion? :)
