### ISSUE TITLE
EXC_BAD_INSTRUCTION  in openssl 3.1.1 and Mac with M1 proc

### ISSUE THREAD

**Issue by nechytailov** [openssl/openssl#21735]
MacOS version 13.5, Xcode version 14.3.1, M1 proc
Own openssl 3.1.1 build.
If I try to run I had `EXC_BAD_INSTRUCTION` in `_armv8_sve_probe` call
```
eor z0.d, z0.d, z0.d
```
If I re-build openssl 3.1.1 with `no_asm` option  I can run program.

**Comment by t8m** [comment]
This is fixed with #21583

**Comment by tom-cosgrove-arm** [comment]
Note also that this issue only occurs when running under the debugger - when run at the command-line the checks execute successfully, not finding SVE, SVE2 or RNG

**Comment by nechytailov** [comment]
Yes, I noticed it, thank you!

**Comment by tom-cosgrove-arm** [comment]
To link up these issues: this is a duplicate of #20753 (both are specifically 3.1)
