### ISSUE TITLE
BN_mod_mont interface processing modulus is 1 optimization

### ISSUE THREAD

**Issue by liwei62** [openssl/openssl#21738]
In the BN_mod_mont interface, the return value is usually 0 when the modulus is 1. Why not add the check before the interface calculation to optimize the calculation?

**Comment by t8m** [comment]
Having the modulus of just 1 is something that will never happen in real cryptographic operations. The primary purpose of the BN library is crypto so there is IMO no point in optimizing (quite meaningless) use cases of these functions.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
