### ISSUE TITLE
ImageMagick 7.1

### ISSUE THREAD

**Issue by kritika-1720** [openssl/openssl#21730]
Hi ,

We're using below version of imagemagick on our RHEL 8:
Version: ImageMagick 7.1.0-53 Q16 x86_64 20646 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher
Delegates (built-in): jpeg lzma tiff zlib
Compiler: gcc (8.5)
It's displaying below in traces:
Magick++ exception: Magick: ASCII value for tag "DocumentName" contains null byte in value; value incorrectly truncated during reading due to implementation limitations. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/951

Is there any way to resolve this, what could be the possible reason of this.

**Comment by tom-cosgrove-arm** [comment]
Closing this, as it seems to be a question about `libtiff`, not OpenSSL, so this is the wrong project to ask.

When you do have an OpenSSL question, please open a discussion rather than an issue
