### ISSUE TITLE
Providers and contexts relationships

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#21739]
A follow-up to #21604 

The question is what and where of this information should go.

Separate instances of the provider can be loaded in the separate library contexts.

Several instances of the same provider in the same context using different section names, module names (e.g. via symlinks) and provider names. But unless the provider does not support some configuration options, the algorithms in this case will have the same `provider` property and the result of fetching is not determined. We strongly discourage against this trick.

The run-time change of the loaded provider configuration is not supported. If it is necessary, the calls to `OSSL_PROVIDER_unload` with the following call to the `OSSL_PROVIDER_load` or `OSSL_PROVIDER_load_ex` should be used.

**Comment by beldmit** [comment]
@mattcaswell is there anything I missed from the discussion? Where should this information go?

**Comment by mattcaswell** [comment]
Other edge cases to consider are:
1) The case where configuration exists and "activate = 1"
2) The case where configuration exists and there is no "activate" line, what config take precedence (config, app provided, or a merge of config and app provided). 

There should be some document discussing the various API choices and edge cases. I'd put it in doc/designs

**Comment by beldmit** [comment]
Thanks, pushed as a part of #21604
