### ISSUE TITLE
X509_VERIFY_PARAM: check_time not gettable 

### ISSUE THREAD

**Issue by pwpo1999** [openssl/openssl#2176]
While porting an application to OpenSSL 1.1.0, I founded that X509_VERIFY_PARAM struct changed opaque struct. 

My application needs to access check_time in X509_VERIFY_PARAM struct.

But, That is set only, not get

If possible, please add a function or macro to access X509_VERIFY_PARAM->check_time.

I use that for make my own "check revocation" function.

Please confirm.
Thank you.

**Comment by richsalz** [comment]
It is possible to work around this by using the NO_CHECK_TIME flag and then checking the time in your function.  But will add a PR to add the gettor.

**Comment by richsalz** [comment]
fix pushed to 1.1.0 and master.
