### ISSUE TITLE
memory leaks in malloc (/home/root/sp/Dataset/openssl_aflpp/install/my_bin/openssl+0x4b9a6d) when using openssl speed

### ISSUE THREAD

**Issue by shinibufa** [openssl/openssl#21766]

**Comment by t8m** [comment]
I am sorry but we would need much more information about the leaks - preferably what exactly is executed, which version of openssl it is, and the lines of the code where the memory that leaks is allocated. Otherwise we cannot do much with this report.

**Comment by nhorman** [comment]
agreed, running your application under valgrind and posting the resultant logs would be a good start

**Comment by shinibufa** [comment]
I am sorry for replying so late. Here is the detailed descrption of this memory leak situation.

Version: 
OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
Ubuntu 20.04

Command to Reproduce:
openssl speed -evp des -cmac aes128 -config [fips.cnf](https://github.com/shinibufa/crash_seeds/blob/main/openssl/fips.cnf)

ASAN Report:
=================================================================
==2577573==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 208 byte(s) in 1 object(s) allocated from:
    #0 0x4b9a6d in malloc (/home/root/sp/Dataset/openssl_aflpp/install/my_bin/openssl+0x4b9a6d)
    #1 0x7fecb6705574 in CRYPTO_malloc /home/root/sp/Dataset/openssl_aflpp/crypto/mem.c:190:12
    #2 0x7fecb67055e6 in CRYPTO_zalloc /home/root/sp/Dataset/openssl_aflpp/crypto/mem.c:197:11
    #3 0x7fecb69909fe in OSSL_STORE_LOADER_new /home/root/sp/Dataset/openssl_aflpp/crypto/store/store_register.c:46:16
    #4 0x692a9f in setup_engine_loader /home/root/sp/Dataset/openssl_aflpp/apps/lib/engine_loader.c:171:19
    #5 0x58d0e4 in apps_startup /home/root/sp/Dataset/openssl_aflpp/apps/openssl.c:71:11
    #6 0x58c7b1 in main /home/root/sp/Dataset/openssl_aflpp/apps/openssl.c:265:35
    #7 0x7fecb5ba6082 in __libc_start_main /build/glibc-5hggjy/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).

**Comment by t8m** [comment]
I assume the openssl speed command fails for some reason in which case it will not properly clean up things on exit. I do not see this to be a real bug. The leak is one-off and just for the speed application.

**Comment by nhorman** [comment]
It looks like the leak is likely caused by a lack of a default config file.  If CONF_get1_default_config_file in the main routine returns null, the speed command bails out without cleaning up, so, like you noted @t8m , not a real problem.

That said, it looks like a reasonably easy fix.  @shinibufa if you want to try this patch, the problem should be corrected:
```
diff --git a/apps/openssl.c b/apps/openssl.c
index a3056c799f..f19ab3aba9 100644
--- a/apps/openssl.c
+++ b/apps/openssl.c
@@ -274,8 +274,10 @@ int main(int argc, char *argv[])
     pname = opt_progname(argv[0]);
 
     default_config_file = CONF_get1_default_config_file();
-    if (default_config_file == NULL)
-        app_bail_out("%s: could not get default config file\n", pname);
+    if (default_config_file == NULL) {
+        BIO_printf(bio_err, "%s: could not get default config file\n", pname);
+        goto out_no_config;
+    }
 
     /* first check the program name */
     f.name = pname;
@@ -303,7 +305,7 @@ int main(int argc, char *argv[])
     OPENSSL_free(arg.argv);
     if (!app_RAND_write())
         ret = EXIT_FAILURE;
-
+ out_no_config:
     BIO_free(bio_in);
     BIO_free_all(bio_out);
     apps_shutdown();
```

**Comment by shinibufa** [comment]
Thank for your working and replying. It helps a lot. I will close this issue.
