### ISSUE TITLE
BN_mod_exp the interface returns 1, when the modulus and base are both 0

### ISSUE THREAD

**Issue by liwei62** [openssl/openssl#21767]
In the BN_mod_exp, when the modulus and base are both 0, the interface returns 1. The calculation result is incorrect because the modulus cannot be 0.

**Comment by t8m** [comment]
This is basically a duplicate of #21740. Or rather the answer is practically the same. BN_mod_exp is not supposed to be used with non-cryptographic parameters.

**Comment by nhorman** [comment]
closing this as a duplicate of #21740
