### ISSUE TITLE
Unreachable code in crypto/md5/md5_sha1.c

### ISSUE THREAD

**Issue by 3lswear** [openssl/openssl#21779]
In file crypto/md5/md5_sha1.c there are multiple cases of using functions like  
`MD5_Final()`:
https://github.com/openssl/openssl/blob/79cdbe893da0c613db97356d05c0b088e885707f/crypto/md5/md5_sha1.c#L36

that are ultimately expanded from macro `HASH_FINAL()`, that always return 1.

And checks of return value of functions like
https://github.com/openssl/openssl/blob/79cdbe893da0c613db97356d05c0b088e885707f/crypto/md5/md5_sha1.c#L61

which in this case calls  `SHA1_Update()` which is in turn a `HASH_UPDATE()`, which always returns 1,

Therefore the conditions in these cases will never be true, and code under these conditions won't be reached. Does the code act as intended in the current state, and is it something worth considering for fixing because of unreachable code?

**Comment by t8m** [comment]
The checks are harmless and it is better to keep them in case the HASH_FINAL or HASH_UPDATE change in future.

**Comment by 3lswear** [comment]
Understood, thank you for explanation
