### ISSUE TITLE
Weak key in dh generate key

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#21781]
Version: OpenSSL3.x
There is no public key validation  in DH_generate_key, and weak public key may generated ,this will result weak DH key.

**Comment by kroeckx** [comment]
We can not assume p is a safe prime. Some RFCs even publish DH groups
that are not safe primes. Only when q is present do we know it's a safe
prime and we already do things differently in that case. When it's not
present, it can be a safe prime, but we don't know.

**Comment by KanPlus** [comment]
> We can not assume p is a safe prime. Some RFCs even publish DH groups that are not safe primes. Only when q is present do we know it's a safe prime and we already do things differently in that case. When it's not present, it can be a safe prime, but we don't know.

Yes, As we don't know p, so the private key could not be limited with p; Add the public key validation with the present q will aviod some possible weak key.

**Comment by bernd-edlinger** [comment]
Hmm, you refer to RFC 5114 ?  Those parmeters define g, p and q.  That is not the case we discussed here.

But in the case where q is not present, the DH_check will fail unless p is in fact a safe prime, see:

https://github.com/openssl/openssl/blob/7a5f58b2cf0d7b2fa0451603a88c3976c657dae9/crypto/dh/dh_check.c#L213-L220

**Comment by bernd-edlinger** [comment]
Also this code can only be understood on the assumption that p is a safe prime,
otherwise we would have to test that bit1 == 1, but all safe primes (except 5) have bit0 and bit1 == 1
https://github.com/openssl/openssl/blob/7a5f58b2cf0d7b2fa0451603a88c3976c657dae9/crypto/dh/dh_key.c#L327-L335

**Comment by nhorman** [comment]
marking as inactive.  Will close without further comment at the end of the 3.4 dev cycle
