### ISSUE TITLE
Decryption of file fails with 1.1.0c-2, but succeeds with 1.0.1t

### ISSUE THREAD

**Issue by flixman** [openssl/openssl#2178]
I have a file encrypted with openssl aes-256-cbc, which I decrypt with
        openssl aes-256-cbc -d -pass file:<file>
Today I have updated (on Debian testing) to 1.1.0c-2 and the message I obtained was:
        140629787522176:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:529:

However, if I downgrade to the last Debian stable package, 1.0.1t, the file is successfully decrypted.

**Comment by kroeckx** [comment]
As documented in the manpage, the default digest changed.
