### ISSUE TITLE
Calling SSL_set_SSL_CTX loses supported client TLS extensions

### ISSUE THREAD

**Issue by notr1ch** [openssl/openssl#2180]
It's common to use SNI and call SSL_set_SSL_CTX with a new context once the host name has been negotiated, for example the nginx webserver does this (https://github.com/nginx/nginx/blob/f8a9d528df92c7634088e575e5c3d63a1d4ab8ea/src/http/ngx_http_request.c#L888)

Unfortunately SSL_set_SSL_CTX replaces the the certificate (ssl->cert, https://github.com/openssl/openssl/blob/7d152a3c4f58bc2c4e94946e2a8dbf1a855a52f2/ssl/ssl_lib.c#L3484), which also contains the client extensions from the ClientHello in ssl->cert->cli_ext. So when an extension later checks for client support, nothing is found (https://github.com/openssl/openssl/blob/7d152a3c4f58bc2c4e94946e2a8dbf1a855a52f2/ssl/t1_ext.c#L44).

This breaks things like the certificate transparency extension which needs to be negotiated after SNI (see https://github.com/grahamedgecombe/nginx-ct/issues/13 for an affected use case).

**Comment by kaduk** [comment]
Just to clarify, this is for custom extensions only?

**Comment by notr1ch** [comment]
I believe so, unless any internal code also relies on custom_ext_parse.

**Comment by notr1ch** [comment]
I'd like to bump this issue, as I've just become aware that Google have announced that certificate transparency will be required as of October 2017 in order for certificates to be trusted in Chrome. Let's Encrypt for example does not currently support CT in their x509 certificates or OCSP responses, so the only way to deliver SCTs is to use a custom TLS extension, which is currently not functioning in OpenSSL 1.1.0.

A workaround has been posted at https://github.com/grahamedgecombe/nginx-ct/issues/13#issuecomment-270949197 - perhaps someone with more knowledge of the OpenSSL code could review this or refactor it into an official patch?

**Comment by richsalz** [comment]
@mattcaswell can you look at this?

**Comment by mattcaswell** [comment]
Fix in #3425

**Comment by mattcaswell** [comment]
Fix in 2118188 for master, c645f9d for 1.1.0 and ea3fc60 for 1.0.2

**Comment by tatsuhiro-t** [comment]
Any plan to release 1.1.0 and 1.0.2 with this fix?

**Comment by richsalz** [comment]
yes, there will be a release soon and it will include the fixes.
