### ISSUE TITLE
The EVP_PKEY_PRIVATE_KEY does not exist elsewhere than in documentation

### ISSUE THREAD

**Issue by Jakuje** [openssl/openssl#21809]
While trying to search how to use `EVP_PKEY_todata` to get private key data, search for the `EVP_PKEY_PRIVATE_KEY` (respective to the public counterpart) revealed the only match in documentation:

https://github.com/openssl/openssl/blame/617cab094f0f0d4e71f8b9da5663be8ab06cba92/doc/man3/d2i_RSAPrivateKey.pod#L208

This constant unexpectedly does not exist in the source code:

https://github.com/openssl/openssl/blob/617cab094f0f0d4e71f8b9da5663be8ab06cba92/include/openssl/evp.h#L88

So my assumption is that the example should say `OSSL_KEYMGMT_SELECT_PRIVATE_KEY` or `EVP_PKEY_KEYPAIR` or openssl should really provide the constant in `EVP_PKEY_PRIVATE_KEY` for convenience. 

I was not sure with the preferred solution so leaving this as low-hanging issue to solve. If you will hint which direction to take, I can submit a PR.

**Comment by t8m** [comment]
EVP_PKEY_KEYPAIR should be used in the documentation instead.

**Comment by t8m** [comment]
Would you like to submit a PR?

**Comment by slontis** [comment]
@t8m For RSA PSS it needs the other parameters also.. 

EVP_PKEY_KEY_PARAMETERS | EVP_PKEY_KEYPAIR

**Comment by t8m** [comment]
> @t8m For RSA PSS it needs the other parameters also..
> 
> EVP_PKEY_KEY_PARAMETERS | EVP_PKEY_KEYPAIR

Please look how EVP_PKEY_KEYPAIR is defined - it includes that set already.

**Comment by Jakuje** [comment]
Thank you for the inputs and clarifications!

I can do the PR.
