### ISSUE TITLE
openssl genpkey with RSA-PSS does not accept -pkeyopt rsa_keygen_pubexp:65537

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#21813]
As of the current master, the following command fails:

```
# openssl genpkey -algorithm rsa-pss -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 -out key.pem
genpkey: Error setting rsa_keygen_pubexp:65537 parameter:
000003FF8C0F7720:error:03000093:digital envelope routines:default_fixup_args:command not supported:crypto/evp/ctrl_params_translate.c:578:[action:2, state:4] name=rsa_keygen_pubexp, value=65537
```

Note that it only fails when generating an RSA-PSS key, but it works for a regular RSA key.

Looking at the translations in `crypto/evp/ctrl_params_translate.c`  I see the following:

```
    { SET, EVP_PKEY_RSA, 0, EVP_PKEY_OP_KEYGEN,
      EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP, "rsa_keygen_pubexp", NULL,
      OSSL_PKEY_PARAM_RSA_E, OSSL_PARAM_UNSIGNED_INTEGER, NULL },
```

So this translation is only valid for `EVP_PKEY_RSA`, but not for `EVP_PKEY_RSA_PSS`.

I would assume this should be changed to:

```
    { SET, EVP_PKEY_RSA, EVP_PKEY_RSA_PSS, EVP_PKEY_OP_KEYGEN,
      EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP, "rsa_keygen_pubexp", NULL,
      OSSL_PKEY_PARAM_RSA_E, OSSL_PARAM_UNSIGNED_INTEGER, NULL },
```

The same is probably true for 

```
    { SET, EVP_PKEY_RSA, 0, EVP_PKEY_OP_KEYGEN,
      EVP_PKEY_CTRL_RSA_KEYGEN_PRIMES, "rsa_keygen_primes", NULL,
      OSSL_PKEY_PARAM_RSA_PRIMES, OSSL_PARAM_UNSIGNED_INTEGER, NULL },
```
and
```
    { SET, EVP_PKEY_RSA, 0, EVP_PKEY_OP_TYPE_CRYPT,
      EVP_PKEY_CTRL_RSA_IMPLICIT_REJECTION, NULL,
      "rsa_pkcs1_implicit_rejection",
      OSSL_ASYM_CIPHER_PARAM_IMPLICIT_REJECTION, OSSL_PARAM_UNSIGNED_INTEGER,
      NULL },
```

Or are there any reasons why those control commands are only valid for regular RSA, but not for RSA-PSS?
Looking at the default provider implementation for RSA-PSS I would say it also accepts those params just like regular RSA. 

I am happy to submit a pull request if you confirm that those 3 should also be used for `EVP_PKEY_RSA_PSS`.

**Comment by ifranzki** [comment]
Additionally, `crypto/evp/ctrl_params_translate.c` also contains functions like

```
static int get_rsa_payload_n(enum state state,
                             const struct translation_st *translation,
                             struct translation_ctx_st *ctx)
{
    const BIGNUM *bn = NULL;

    if (EVP_PKEY_get_base_id(ctx->p2) != EVP_PKEY_RSA)
        return 0;
    bn = RSA_get0_n(EVP_PKEY_get0_RSA(ctx->p2));

    return get_payload_bn(state, translation, ctx, bn);
}
```

which are also just checking for `EVP_PKEY_RSA`. I wonder if it should also allow `EVP_PKEY_RSA_PSS` here? 

Not sure where exactly these functions are used, but if they are called on a RSA-PSS key, I would assume they will fail.

**Comment by mattcaswell** [comment]
> I would assume this should be changed to:
> 
>     { SET, EVP_PKEY_RSA, EVP_PKEY_RSA_PSS, EVP_PKEY_OP_KEYGEN,
>       EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP, "rsa_keygen_pubexp", NULL,
>       OSSL_PKEY_PARAM_RSA_E, OSSL_PARAM_UNSIGNED_INTEGER, NULL },

Yes.

> The same is probably true for
> 
>     { SET, EVP_PKEY_RSA, 0, EVP_PKEY_OP_KEYGEN,
>       EVP_PKEY_CTRL_RSA_KEYGEN_PRIMES, "rsa_keygen_primes", NULL,
>       OSSL_PKEY_PARAM_RSA_PRIMES, OSSL_PARAM_UNSIGNED_INTEGER, NULL },

Yes.

> and
> 
>     { SET, EVP_PKEY_RSA, 0, EVP_PKEY_OP_TYPE_CRYPT,
>       EVP_PKEY_CTRL_RSA_IMPLICIT_REJECTION, NULL,
>       "rsa_pkcs1_implicit_rejection",
>       OSSL_ASYM_CIPHER_PARAM_IMPLICIT_REJECTION, OSSL_PARAM_UNSIGNED_INTEGER,
>       NULL },

No. This one is not relevant to PSS.

> I am happy to submit a pull request if you confirm that those 3 should also be used for EVP_PKEY_RSA_PSS.

Yes please!

> which are also just checking for EVP_PKEY_RSA. I wonder if it should also allow EVP_PKEY_RSA_PSS here?

Yes, probably they should.

> Not sure where exactly these functions are used, but if they are called on a RSA-PSS key, I would assume they will fail.

Used for example when calling `EVP_PKEY_get_bn_param()` when supplying a legacy (i.e. not provider based) key and getting the param (in this case) `OSSL_PKEY_PARAM_RSA_N`.

**Comment by ifranzki** [comment]
> > I am happy to submit a pull request if you confirm that those 3 should also be used for EVP_PKEY_RSA_PSS.
> 
> Yes please!

See https://github.com/openssl/openssl/pull/21818

> > Not sure where exactly these functions are used, but if they are called on a RSA-PSS key, I would assume they will fail.
> 
> Used for example when calling `EVP_PKEY_get_bn_param()` when supplying a legacy (i.e. not provider based) key and getting the param (in this case) `OSSL_PKEY_PARAM_RSA_N`.

Do we have any tests that work with legacy keys where this could be tested?

**Comment by ifranzki** [comment]
A grep for cases where `EVP_PKEY_RSA` is used but not `EVP_PKEY_RSA_PSS` revealed the following places where handling of RSA_PSS might also be missing:

In crypto/evp/p_lib.c: 
```
int EVP_PKEY_can_sign(const EVP_PKEY *pkey)
{
    if (pkey->keymgmt == NULL) {
        switch (EVP_PKEY_get_base_id(pkey)) {
        case EVP_PKEY_RSA:   <--- shouldn't RSA_PSS keys also return 1 here, as RSA-PSS keys can sign?
            return 1;
# ifndef OPENSSL_NO_DSA
        case EVP_PKEY_DSA:
            return 1;
# endif
   ...
```

and

```
static void detect_foreign_key(EVP_PKEY *pkey)
{
    switch (pkey->type) {
    case EVP_PKEY_RSA:
        pkey->foreign = pkey->pkey.rsa != NULL
                        && ossl_rsa_is_foreign(pkey->pkey.rsa);
        break;
   ....
```
This is called from `EVP_PKEY_assign()` and I guess this should also work for a pkey object that has been initialized as RSA-PSS.

**Comment by mattcaswell** [comment]
> A grep for cases where EVP_PKEY_RSA is used but not EVP_PKEY_RSA_PSS revealed the following places where handling of RSA_PSS might also be missing:

Yes...those look missing too.

Probably very few people are using RSA_PSS with an ENGINE so it hasn't really impacted anyone.

**Comment by ifranzki** [comment]
Should I fix those, too, in a 3rd patch in PR https://github.com/openssl/openssl/pull/21818 or do you want me to open a new PR ?

**Comment by ifranzki** [comment]
This one is solved by PR https://github.com/openssl/openssl/pull/21818 and PR https://github.com/openssl/openssl/pull/21819 and can be closed.
