### ISSUE TITLE
Unable to PEM encode RSA keys created with `EVP_PKEY_fromdata()` with missing dmp1 and dmq1 coeffitients

### ISSUE THREAD

**Issue by Jakuje** [openssl/openssl#21826]
The SSH is using its own file format which does not contain the dmp1 and dmq1 parameters for RSA keys. So we are building the EVP_PKEYs with `EVP_PKEY_fromdata()` with all information we have.

1. This fails when the dmp1 and dmq1 OSSL_PARAMs (`OSSL_PKEY_PARAM_RSA_EXPONENT1` and `OSSL_PKEY_PARAM_RSA_EXPONENT2` are missing, but it does not give any useful error, which is a problem and the only option is to dive into the openssl code to see whats the problem. This is at least inconvenient.

2. The workaround that we have now implemented is to build the RSA key only from the basic parameters (n, e, d) and set the remaining (p, q, iqmp) using `EVP_PKEY_set_bn_param()`. This works all along until we try to export this private key to PEM format using `PEM_write_bio_PrivateKey()`. Here we get very vague message `error:068000DE:asn1 encoding routines::illegal zero content` which after some debugging points out to the missing exponents.

3. I was trying to find an API to calculate the missing exponents, but did not find one yet. If we are supposed to call that API manually, it needs to be documented. Otherwise I think this should be called automatically when they are expected/required by some of the code (PEM encoder). The error code should also be nicer.

Using OpenSSL 3.0.9 now.

I can probably put together some reproducer when the above description will not be enough.

**Comment by beldmit** [comment]
`ossl_rsa_sp800_56b_derive_params_from_pq` is the internal function that can be used for this purpose and it's worth having a public API to call it. I have an impression it's currently called only from FIPS key generation.

**Comment by t8m** [comment]
I see only one clear bug here - that is the missing raised error by EVP_PKEY_fromdata() call if the OSSL_PKEY_PARAM_RSA_EXPONENT1 and/or OSSL_PKEY_PARAM_RSA_EXPONENT2 is missing.

That EVP_PKEY_set_bn_param() allows you to subsequently add the p,q, iqmp  and without dmp1 and dmq1 is debatable - IMO it should not allow that, but I assume we are not going to change that.

If CRT is to be used for the private key operations these parameters are needed. Otherwise the private key operations will not use CRT -> will be much slower.

How does OpenSSH use such keys? Does it compute the missing parameters?

The parameters can be computed but we would have to do that on import as in general we aim for having immutable EVP_PKEYs.

**Comment by t8m** [comment]
> `ossl_rsa_sp800_56b_derive_params_from_pq` is the internal function that can be used for this purpose and it's worth having a public API to call it. I have an impression it's currently called only from FIPS key generation.

I do not think exposing such call publicly would be a good idea. Instead I think we should either do it automatically on EVP_PKEY_fromdata() if the params are missing, or we could add a flag to the OSSL_PARAMS to enforce this computation.

**Comment by beldmit** [comment]
Adding a param to `EVP_PKEY_fromdata` to enforce the calculation looks like a reasonable way forward.

**Comment by Jakuje** [comment]
> I see only one clear bug here - that is the missing raised error by EVP_PKEY_fromdata() call if the OSSL_PKEY_PARAM_RSA_EXPONENT1 and/or OSSL_PKEY_PARAM_RSA_EXPONENT2 is missing.

Yes, this is one thing to fix.

> How does OpenSSH use such keys? Does it compute the missing parameters?

The OpenSSH computes the parameters manually, which is something I would like to avoid:

https://github.com/openssh/openssh-portable/blob/17fa6cd10a26e193bb6f65d21264d2fe553bcd87/ssh-rsa.c#L336

> The parameters can be computed but we would have to do that on import as in general we aim for having immutable EVP_PKEYs.

Sounds like a resonable suggestion.

**Comment by nhorman** [comment]
Looking at the rsa_import function, it appears to explicitly allow the creation of an RSA key without the additional parameters, so I think what we need is an option that allows us to independently generate the missing parameters, and test to ensure that they are set (generating an error if they are not).  Let me try work something up.

**Comment by nhorman** [comment]
Sorry it's taking me a bit to get this written, fixing up some use cases and adding a self test.  Should have something by monday

**Comment by nhorman** [comment]
https://github.com/openssl/openssl/pull/21875

ok, I've got something put together.  I added a boolean parameter to direct fromdata to derive p and q when our exponents are set.  Wasn't sure if it would be better to do it automatically when p and q were omitted but exponents/coefficients were set.  Opted for the latter to avoid changing existing behavior.  Also added a few ERR raises to let you know what was going on if there were any failures.

**Comment by nhorman** [comment]
gah, I just realized what I did, sorry, I totally got this backwards

**Comment by nhorman** [comment]
Ok, sorry for the wait, got it all cleaned up and its working now.  Still not super happy with the way I cloned ossl_rsa_sp800_56b_derive_params_from_pq, but it enough to test with now, including the test I added to confirm that we can do a derivation of our exponents/coefficients.

**Comment by nhorman** [comment]
updated pr to clean up/deduplicate some functionality, and added support for multiprime key generation
