### ISSUE TITLE
openssl speed test fails for evp(DES-CBC, DES-CFB,DES-CFB1, DES-CFB8) with afalg or cryptodev engine. "EVP_CipherInit_ex failure"

### ISSUE THREAD

**Issue by jaingaurav2712** [openssl/openssl#21828]
**$ openssl version**
OpenSSL 3.1.1
**$ openssl list -cipher-algorithms**
  DES-CBC
  DES-CFB
  DES-CFB1
  DES-CFB8
**$ openssl speed -engine afalg -multi 8 -elapsed -evp des-cbc**
Forked child 0
Forked child 1
Forked child 2
Forked child 3
Engine "afalg" set.
+DT:DES-CBC:3:16

EVP_CipherInit_ex failure
20B0FBA0FFFF0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:/usr/src/debug/openssl/3.1.1-r0/crypto/evp/evp_fetch.c:341:Globa)

Child exited with 1
version: 3.1.1
built on: Tue May 30 12:13:24 2023 UTC
options: bn(64,64)
compiler: aarch64-poky-linux-gcc  -march=armv8-a+crc+crypto -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-sG
CPUINFO: OPENSSL_armcap=0xbd
evp                  0.00         0.00         0.00         0.00         0.00         0.00

**Comment by t8m** [comment]
The afalg engine supports only AES-CBC (of all three possible key sizes).

**Comment by jaingaurav2712** [comment]
what about cryptodev engine?

**Comment by t8m** [comment]
> what about cryptodev engine?

That should support DES-CBC and DES3-CBC.
