### ISSUE TITLE
Duplicated pub_key * order operation in ossl_ec_key_public_check()

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#21834]
This was added IMO incorrectly by the FIPS 140-3 changes in 3.1.

**Comment by t8m** [comment]
This is quite expensive operation (see #21833) and duplicating it does not make any sense.

**Comment by mattcaswell** [comment]
In particular see:

https://github.com/openssl/openssl/blob/8c5284ff194f444877ae25012d3d07ee46e46219/crypto/ec/ec_key.c#L579-L588

We seem to do the exact same point mul twice, throwing away the answer from the first one.

**Comment by slontis** [comment]
Looks like a block copy or merge error... Maybe @paulidale will know..

**Comment by t8m** [comment]
This comes from the KeyPair changes. There was this comment before: `FIPS 140-3: IG10.3.A Add'l commnet 1: Perform a second check on the public key`

Which, frankly, still does not make any sense as IG10.3.A is about self-tests.

I'd just remove it.

**Comment by mattcaswell** [comment]
After checking with the original authors this is confirmed as a mistake. We can remove it.
