### ISSUE TITLE
Openssl 1.0.2 has no compatibility with FIPS object module v2.0.

### ISSUE THREAD

**Issue by MSAtos** [openssl/openssl#2185]
I tested FIPS object module v2.0 and Openssl 1.0.1 on my source code.
Openssl 1.0.1 was EOL at End of 2016 then I shifted to Openssl 1.0.2j.
However I got compile error on same source code. 
"error: unknown type name 'ASN1_OBJECT'"

I found typedef ASN1_OBJECT was missing since OpenSSL 1.0.2.
/usr/local/ssl/fips-2.0/include/openssl/evp.h
 -> /usr/local/ssl/include/openssl/objects.h
  -> /usr/local/ssl/include/openssl/asn1.h

OpenSSL 1.0.1:
```/*
 * These are used internally in the ASN1_OBJECT to keep track of whether the
 * names and data need to be free()ed
 */
 # define ASN1_OBJECT_FLAG_DYNAMIC         0x01/* internal use */
 # define ASN1_OBJECT_FLAG_CRITICAL        0x02/* critical x509v3 object id */
 # define ASN1_OBJECT_FLAG_DYNAMIC_STRINGS 0x04/* internal use */
 # define ASN1_OBJECT_FLAG_DYNAMIC_DATA    0x08/* internal use */
typedef struct asn1_object_st {
    const char *sn, *ln;
    int nid;
    int length;
    const unsigned char *data;  /* data remains const after init */
    int flags;                  /* Should we free this one */
} ASN1_OBJECT;
```

OpenSSL 1.0.2 and OpenSSL 1.1.0:
```/*
 * These are used internally in the ASN1_OBJECT to keep track of whether the
 * names and data need to be free()ed
 */
 # define ASN1_OBJECT_FLAG_DYNAMIC         0x01/* internal use */
 # define ASN1_OBJECT_FLAG_CRITICAL        0x02/* critical x509v3 object id */
 # define ASN1_OBJECT_FLAG_DYNAMIC_STRINGS 0x04/* internal use */
 # define ASN1_OBJECT_FLAG_DYNAMIC_DATA    0x08/* internal use */
struct asn1_object_st {
    const char *sn, *ln;*
    int nid;
    int length;
    const unsigned char *data;  /* data remains const after init */
    int flags;                  /* Should we free this one */
};
```

Could you check this issue to use FIPS object module v2.0 and Openssl 1.0.2?

**Comment by snhenson** [comment]
The typedef is in ossl_typ.h in 1.0.2.

**Comment by MSAtos** [comment]
Dear snhenson,
Thank you for your support.
I will check it.

**Comment by KrishVikram** [comment]
Facing the following error when trying FIPS 2.0 with SSL 1.0.2n:
[('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad record mac')]

Could this be because of any compatibility issues with the two?
