### ISSUE TITLE
Information regarding openssl upgrade of i2d_X509_REQ() api

### ISSUE THREAD

**Issue by gunaMect** [openssl/openssl#21947]
Hi team, 

I have upgraded from openssl 1.1.1 to opessl 3.0.5. I am getting error in the i2d_X509_REQ(X509_REQ* req, nullptr) api to get the length of the content in openssl 3.0.5. I am getting the error of length of -1. Can anyone guide me fix this compatability issue? Many thanks in advance. Also, is it possible to print the reason for error due to openssl api's? It will be used to find the exact error occurred.

**Comment by t8m** [comment]
There should not be any compatibility issues on i2d_X509_REQ() however it is possible that something else silently fails before that call. Could you please try to create a simple reproducer to share here?

**Comment by pbu-avn** [comment]
I'm facing the same issue. Please find the sample reproducer
`#include <iostream>
#include <openssl/evp.h>
#include <openssl/rsa.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/engine.h>
#include <filesystem>
#include <openssl/x509.h>
using namespace std;


int main()
{
    EVP_PKEY_CTX *ctx;
    EVP_PKEY *pkey = NULL;
    ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, NULL);
    if (!ctx) {
        std::cout<<"ctx error"<<std::endl;
    }
        /* Error occurred */
    if (EVP_PKEY_keygen_init(ctx) <= 0) {
        std::cout<<"EVP_PKEY_CTX_new_id error"<<std::endl;
    }

    if (EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, 4096) <= 0) {
        std::cout<<"EVP_PKEY_CTX_set_rsa_keygen_bits error"<<std::endl;
    }

    /* Generate key */
    if (EVP_PKEY_keygen(ctx, &pkey) <= 0) {
        std::cout<<"EVP_PKEY_keygen error"<<std::endl;
    }

    /* Writes the generated key to file*/
    FILE *fp;
    fp = fopen("/home/tpb1cob/1day/openssl/public_key.txt","w");
    if (0 == PEM_write_PUBKEY(fp,pkey)) {
        std::cout<<"file write fail"<<std::endl;
    }
    fclose(fp);

    /*Encode the key and write to buffer*/
    unsigned char* p;
    int ret = -1;
    ret = i2d_PublicKey(pkey,&p);
    if(ret < 0) {
        std::cout<<"i2d_PublicKey returns negative value"<<ret<<std::endl;
    }
    std::cout<<"i2d_PublicKey returns value "<<ret<<std::endl;
    std::cout<<p<<std::endl;

    /*Decodes buffer contents and assign to EVP_Key structure*/
    EVP_PKEY *pkey1 = NULL;
    if(NULL == d2i_PublicKey(EVP_PKEY_RSA,&pkey1,(const unsigned char**)&p,526)) {
        std::cout<<"d2i_PrivateKey_fp returns NULL pointer"<<std::endl;
    }

    /* Writes the decoded key to file*/
    FILE *fpq;
    fpq = fopen("/home/tpb1cob/1day/openssl/public_key_decoded.txt","w");
    if (0 == PEM_write_PUBKEY(fpq,pkey1)) {
        std::cout<<"file write fail"<<std::endl;
    }
    fclose(fpq);
    
    /* checks the parameters of keys pkey and pkey1 for equality */
    if(1 == EVP_PKEY_eq(pkey,pkey1)) {
        std::cout<<"EVP_PKEY_eq success"<<std::endl;
    }
    

    //"C=UK, O=Disorganized Organization, CN=Joe Bloggs"

    X509_NAME *nm;
    X509_REQ *CR;

    nm = X509_NAME_new();
    CR = X509_REQ_new();    
    if (nm == NULL) {
        std::cout<<"X509_NAME_new failed"<<std::endl;
    }
        /* Some error */

    int ii = -1;

     if (1 == X509_NAME_add_entry_by_txt(nm, "C", MBSTRING_ASC,(const unsigned char*)"UK", -1, -1, 0)) {
        std::cout<<"X509_NAME_add_entry_by_txt country success"<<std::endl;
    }
        /* Error */
    if (1 == X509_NAME_add_entry_by_txt(nm, "O", MBSTRING_ASC,(const unsigned char*)"Disorganized Organization", -1, -1, 0)) {
        std::cout<<"X509_NAME_add_entry_by_txt organization success"<<std::endl;
    }
    
    if (1 == X509_NAME_add_entry_by_txt(nm, "OU", MBSTRING_ASC,(const unsigned char*)"Organization Unit", -1, -1, 0)) {
        std::cout<<"X509_NAME_add_entry_by_txt organization unit success"<<std::endl;
    }
        /* Error */
    if (1 == X509_NAME_add_entry_by_txt(nm, "CN", MBSTRING_ASC,(const unsigned char*)"Joe Bloggs", -1, -1, 0)) {
        std::cout<<"X509_NAME_add_entry_by_txt common name success"<<std::endl;
    }

    if (1 == X509_REQ_set_subject_name(CR, nm)) {
        std::cout<<"X509_REQ_set_subject_name success"<<std::endl;
    }
    
    X509_NAME_free(nm);

    if(1 == X509_REQ_set_pubkey(CR, pkey)) {
        std::cout<<"X509_REQ_set_pubkey success"<<std::endl;
    }

    int length = i2d_X509_REQ(CR, NULL);
    const char** file;
    int* line;

    if (length <= 0) {
        std::cout<<"i2d_X509_REQ fail"<<length<<std::endl;
    }
    
    return 0;
}`

**Comment by t8m** [comment]
> I'm facing the same issue. Please find the sample reproducer [test.zip](https://github.com/openssl/openssl/files/12597379/test.zip)

You do not sign the X509_REQ, that's most probably the reason for the failure.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle without further input
