### ISSUE TITLE
Windows 11 ARM / MSYS2 : "apps/openssl.res.o: machine type x64 conflicts with arm64"

### ISSUE THREAD

**Issue by FSOL-XDAG** [openssl/openssl#21943]
Hello ! 

I'm trying to compile OpenSSL requested by [XMRig ](https://github.com/xmrig/xmrig)inside Win 11 ARM (through M2 Mac / Parallels Desktop).

I follow theses recommandations : https://www.msys2.org/wiki/arm64/

So I get `clangarm64.exe` and type theses commands : 

```
pacman -S mingw-w64-clang-aarch64-gcc-compat mingw-w64-clang-aarch64-cmake automake libtool autoconf git make
git clone https://github.com/xmrig/xmrig.git
mkdir xmrig/build && cd xmrig/scripts
./build_deps.sh
```

build_deps.sh call [build.openssl.sh](https://github.com/xmrig/xmrig/blob/master/scripts/build.openssl.sh) .

Then I get this error : 
![265291674-d460a2ca-2300-47b9-a420-26f4f9512cde](https://github.com/openssl/openssl/assets/128682335/4b82aca2-1cef-43a4-9a67-a2c989e8fe1e)

Here is the complete log :

[build_deps.log.txt](https://github.com/openssl/openssl/files/12511090/build_deps.log.txt)

SChernykh (XMRig dev) [said ](https://github.com/xmrig/xmrig/issues/3326#issuecomment-1704696316)"_This script wasn't designed for cross-compilation, I don't see any way to select the compiler there_.".

Does anybody knows how to do that ?

**Comment by t8m** [comment]
Neither build_deps.sh nor [build.openssl.sh](https://github.com/xmrig/xmrig/blob/master/scripts/build.openssl.sh) is our code. Cross-compilation is supported by openssl via the https://github.com/openssl/openssl/blob/master/INSTALL.md#cross-compile-prefix Configure option.

**Comment by FSOL-XDAG** [comment]
I've informed XMRig dev about that. Thanks a lot for your help.
