### ISSUE TITLE
Native Windows absolute paths are treated as URIs.

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#21970]
### Discussed in https://github.com/openssl/openssl/discussions/21969

<div type='discussions-op-text'>

<sup>Originally posted by **njbelf** September  5, 2023</sup>
I'm sure I'm missing something.    Following is the error, the public key itself and pertinent config file entry.     What am I missing?

 ./openssl dgst -sha3-384 -verify C:\SampleKeys\key-a_public_key_secp384r1.pem -signature  H:\SHATestVectors\SHA3_384\SHA3_384_384_in.bin

Could not open file or uri for loading public key from C:\SampleKeys\key-a_publi
c_key_secp384r1.pem
78B80000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered s
cheme:crypto\store\store_register.c:237:scheme=file
78B80000:error:1608010C:STORE routines:inner_loader_fetch:unsupported:crypto\sto
re\store_meth.c:383:No store loader found. For standard store loaders you need a
t least one of the default or base providers available. Did you forget to load t
hem? Info: Global default library context, Scheme (file : 0), Properties (<null>
)
78B80000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered s
cheme:crypto\store\store_register.c:237:scheme=C
78B80000:error:1608010C:STORE routines:inner_loader_fetch:unsupported:crypto\sto
re\store_meth.c:383:No store loader found. For standard store loaders you need a
t least one of the default or base providers available. Did you forget to load t
hem? Info: Global default library context, Scheme (C : 0), Properties (<null>)

This public key PEM file is readable by everything else on my Windows 10 machine and looks like this:
-----BEGIN PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAECK3Ptkmy1euJ0DNogEgMnSFzsCKh+gx0
peZQCWIexEgNipGisfyHv1Tb2wa5p26Rq1mGnYZwDrxdTlpDJjuSFbOszCjufhXF
4biHkt2HmjTH0d3vNUILhqdZrdyH+wc+
-----END PUBLIC KEY-----

I'm automatically loading providers in my config file with this line:
openssl_conf = openssl_init

</div>

**Comment by t8m** [comment]
The backslashes get interpreted I assume. I do not think this is a real bug - the discussion topic was closed by the reporter.

**Comment by beldmit** [comment]
The reporter found a workaround - quoting a filename. But file name interpretation on Windows seems deserving a separate treatment.

**Comment by t8m** [comment]
What? This was not a workaround. The path as it got to OpenSSL was not the real path anymore. And yeah, there is a fallback that treats the path as URI if there is a colon `:` inside. But I do not think this is a problem.

**Comment by beldmit** [comment]
@t8m if you have a Windows machine (I don't), could you please check the behavior on 1.1.1 and 3.x with absolute paths?

**Comment by BuHToPe3** [comment]
@beldmit I have tested OpenSSL 3.0.10 on Windows 10.

.\openssl.exe genrsa -out D:\ossl30_key.pem 4096
.\openssl.exe rsa -in D:\ossl30_key.pem -pubout > D:\ossl30_pubkey.pem
.\openssl.exe dgst -sign D:\ossl30_key.pem -keyform PEM -sha256 -out D:\ossl30.sign C:\vars.bat

.\openssl.exe dgst -verify D:\ossl30_pubkey.pem -keyform PEM -sha256 -signature D:\ossl30.sign C:\vars.bat
Verified OK

**Comment by beldmit** [comment]
OK, if it doesn't reproduce as is, let's close.
