### ISSUE TITLE
Return value confusion in cms_sd_asn1_ctrl()

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#21986]
In `cms_sd.c`,  the function `cms_sd_asn1_sign()` is error checked as if it had a Boolean return value. However, since #13088, it can also return -1.

**Comment by paulidale** [comment]
The function changed in that PR that can return -1 appears to be `cms_sd_asn1_ctrl()`.
It's return code is checked via `!cms_sd_asn1_ctrl()` and should be `cms_sd_asn1_ctrl() <= 0`.
