### ISSUE TITLE
Crash in BIO_ssl_shutdown() in OpenSSL 1.1.0c

### ISSUE THREAD

**Issue by bester** [openssl/openssl#2199]
I've encountered a crash in BIO_ssl_shutdown() in OpenSSL 1.1.0c. It looks like the BIO_get_data() return value is being interpreted as an "SSL *" instead of as a "BIO_SSL *". For my case, this is resulting in a NULL pointer dereference.

This program (invoke with ./a.out <ssl server>) exhibits the crash:
[bio_ssl_shutdown.c](https://github.com/openssl/openssl/files/693920/bio_ssl_shutdown.c.txt)

I think this patch resolves the issue:
[bio_ssl.diff](https://github.com/openssl/openssl/files/693931/bio_ssl.diff.txt)

**Comment by richsalz** [comment]
Yes, you're right.  we'll fix soon.

**Comment by richsalz** [comment]
do you think this is trivial, or can you sign our CLA?

**Comment by bester** [comment]
It seems trivial to me.

**Comment by richsalz** [comment]
I agree it's trivial, since we do this in several other places as well.  Thanks!

**Comment by t-j-h** [comment]
Other references check for ssl!=NULL before using it - if this was the following I would be +1
i.e. name the variable bdata to be consistent - calling it "b" tends to be what is used for a BIO - and check for ssl not being NULL before dereference occurs in SSL_shutdown as it doesn't check - most of the other code paths do check this.

--- a/ssl/bio_ssl.c	2016-11-10 09:03:46.000000000 -0500
+++ b/ssl/bio_ssl.c	2017-01-09 10:51:05.312232036 -0500
@@ -518,11 +518,12 @@
 void BIO_ssl_shutdown(BIO *b)
 {
     SSL *s;
+    BIO_SSL *bdata;
 
     b = BIO_find_type(b, BIO_TYPE_SSL);
     if (b == NULL)
         return;
 
-    s = BIO_get_data(b);
-    SSL_shutdown(s);
+    bdata = BIO_get_data(b);
+    if (bdata->ssl != NULL)
+      SSL_shutdown(bdata->ssl);
 }

**Comment by bernd-edlinger** [comment]
Ping? @richsalz

**Comment by richsalz** [comment]
I have to do all the work? :)  Fine, I'll make a PR that does what @t-j-h wants.  Later today.

**Comment by richsalz** [comment]
See #2651

**Comment by mattcaswell** [comment]
This was fixed: 9015d34 in master and 5180091 in 1.1.0. Closing.
