### ISSUE TITLE
OpenSSL 3.2.0-alpha1 - uintptr_t is not portable

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#22002]
`uintptr_t` is not available on every platform. This breaks the NonStop builds using c99.
```
c99: running /usr/cmplr/ccomfe -Z8 -ZBL --c99 -ZO2 -Zg3 -ZS/tmp/t771752031ABDACF.T -D_XOPEN_SOURCE -ZR8 -m -Zf -ZT -D_TANDEM_SOURCE -ZNW203 -ZNW220 -ZNW272 -ZNW734 -ZNW770 -ZNW1506 -Zz -I. -Iinclude -Iapps/include -I/usr/include -DOPENSSL_PIC -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib64/engines-3" -DMODULESDIR="/usr/local/lib64/ossl-modules" -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_VPROC= -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED=1 -D_TANDEM_SOURCE -DB_ENDIAN -DNDEBUG apps/lib/app_libctx.c
          uintptr_t   custom_ui;
          ^
"/home/randall/openssl/include/openssl/bio.h", line 417: error(114): identifier
          "uintptr_t" is undefined
```

**Comment by hlandau** [comment]
Thanks for the report. Can you advise on a suitable substitute type? For example, is `unsigned long` guaranteed to be able to contain a pointer on Nonstop systems?

**Comment by levitte** [comment]
I'd like to point out that `uintptr_t` is, in fact, a standard C99 type, that should be defined in `<stdint.h>`, at least according to https://en.cppreference.com/w/c/types/integer

**Comment by rsbeckerca** [comment]
We need to update our config to include the define `__NSK_OPTIONAL_TYPES__` to turn that on. I will try it and possibly get a PR shortly.

**Comment by hlandau** [comment]
> I'd like to point out that `uintptr_t` is, in fact, a standard C99 type, that should be defined in `<stdint.h>`, at least according to https://en.cppreference.com/w/c/types/integer

Almost! C99 does actually state that definition of `intptr_t` and `uintptr_t` are optional.

This actually comes in relevant where strange platforms like IBM i is concerned &mdash; since it is a capability based architecture `sizeof(void*) == 16`, pointers are unforgeable and cannot be cast to or from integers, and `uintptr_t` is therefore not defined.

**Comment by levitte** [comment]
> > I'd like to point out that `uintptr_t` is, in fact, a standard C99 type, that should be defined in `<stdint.h>`, at least according to https://en.cppreference.com/w/c/types/integer
> 
> Almost! C99 does actually state that definition of `intptr_t` and `uintptr_t` are optional.

Ah, hah!  Okie, thanks for the clarification.

**Comment by levitte** [comment]
> We need to update our config to include the define `__NSK_OPTIONAL_TYPES__` to turn that on. I will try it and possibly get a PR shortly.

Cool!  Easy solutions are good 🙂
