### ISSUE TITLE
OpenSSL 3.2.0-alpha1: build failure on linux

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#22021]
Tried to [build](https://github.com/conda-forge/openssl-feedstock/pull/137) the alpha in conda-forge, ran into a build error on linux-64:

```
[...]
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-3.2.0.alpha1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wa,--noexecstack  -Iapps -I. -Iinclude -Iapps/include  -pthread -m64 -Wa,--noexecstack -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-3.2.0.alpha1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wa,--noexecstack -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -MMD -MF apps/openssl-bin-version.d.tmp -MT apps/openssl-bin-version.o -c -o apps/openssl-bin-version.o apps/version.c
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-3.2.0.alpha1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wa,--noexecstack  -Iapps -I. -Iinclude -Iapps/include  -pthread -m64 -Wa,--noexecstack -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-3.2.0.alpha1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wa,--noexecstack -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -MMD -MF apps/openssl-bin-x509.d.tmp -MT apps/openssl-bin-x509.o -c -o apps/openssl-bin-x509.o apps/x509.c
rm -f fuzz/cmp-test
${LDCMD:-$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-3.2.0.alpha1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wa,--noexecstack} -pthread -m64 -Wa,--noexecstack -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openssl_split-3.2.0.alpha1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wa,--noexecstack  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib \
	-o fuzz/cmp-test \
	fuzz/cmp-test-bin-cmp.o fuzz/cmp-test-bin-fuzz_rand.o \
	fuzz/cmp-test-bin-test-corpus.o \
	libcrypto.a -ldl -pthread 
/home/conda/feedstock_root/build_artifacts/openssl_split_1694128181501/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: libcrypto.a(libcrypto-lib-bss_dgram.o): in function `dgram_sendmmsg':
bss_dgram.c:(.text.dgram_sendmmsg+0x1ef): undefined reference to `sendmmsg'
```

Main config:

```
+ perl ./Configure --libdir=lib --prefix=$PREFIX enable-legacy no-fips no-module no-zlib shared threads enable-ktls linux-x86_64 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
Configuring OpenSSL version 3.2.0-alpha1 for target linux-x86_64
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
Created include/openssl/configuration.h

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************
```

I'm leaving out how we point CC etc. to our compilers, set up CFLAGS etc., but can provide that if desired.

Interestingly, the build does not fail for linux on other arches (aarch64 / ppc64le), nor on other platforms.

**Comment by paulidale** [comment]
`sendmmsg(2)` was introduced in Linux 3.0 and glibc 2.14.
Are you running older versions than these?

**Comment by h-vetinari** [comment]
> `sendmmsg(2)` was introduced in Linux 3.0 and glibc 2.14.
> Are you running older versions than these?

Ah, that explains it. Even though our CI is CentOS 7 based, we're still building with an aim of CentOS 6 compatibility (that means glibc 2.12). We've deprecated that support now, but haven't yet removed it completely. I'd be the first to throw out such ancient systems, but some consumers move glacially...

> Since you're not configuring QUIC support, this looks like an error in our conditioning.

That's more interesting. We'll definitely want QUIC support (I just hadn't adapted our config setup from 3.1 yet), but as I understand it, that won't be possible with such old glibc?

**Comment by h-vetinari** [comment]
> Since you're not configuring QUIC support, this looks like an error in our conditioning.

I tried adding `quic` the the config and ran into:
```
target already defined - quic (offending arg: linux-x86_64)
```
on all platforms. It seems that `quic` is on by default?

**Comment by paulidale** [comment]
It is on by default, memory lapse on my part.

I'm not sure what the approach to fix this should be:
* disable building the code that requires `sendmmsg(2)` -- disabling QUIC I suspect.
* implement our own version of `sendmmsg(2)` for platforms that don't have it.

Thoughts?  @hlandau @mattcaswell @t8m

**Comment by h-vetinari** [comment]
TBH, I think it's fair enough to drop support for glibc that old. CentOS 6 has been EOL since 2020. We'll be able to handle things even if this is not changed.

**Comment by hlandau** [comment]
This is not a QUIC configuration issue as `BIO_sendmmsg` is a general new BIO feature and should be available even if QUIC is disabled.

This **is** a bug in our code because we have a `sendmsg`-based fallback we can use if `sendmmsg` is unavailable. If even `sendmsg` is unavailable we also support `sendto`.

@h-vetinari See crypto/bio/bss_dgram.c line 56 &mdash; we currently detect availability of sendmmsg/recvmmsg based on `MSG_WAITFORONE` being defined. However you can override this by defining `NO_RECVMSG`. So configuring with `-DNO_RECVMMSG` should work around this for now.

**Comment by paulidale** [comment]
The project still kind of supports PA-RISC (10 years), Alpha (15 years) and Itanium (3 years although lawsuits were involved).  All are well past their use by dates and essentially stopped being used well before their end of support dates.

We should support a port to the PDP-11 since they are still available :wink:

**Comment by t8m** [comment]
I assume that on most old platforms the `MSG_WAITFORONE` would not be defined. But this one is fairly special configuration and we might be able to support it only by adding the support for `-DNO_RECVMMSG`.

We IMO do not want to get into the business of doing configure feature checks.

**Comment by rainerjung** [comment]
Just wanted to confirm, that I also ran into a linux version (RHEL 6.1) which does not have the recvmmsg/sendmmsg API but nevertheless unconditionally defines MSG_WAITFORONE in /usr/include/bits/socket.h. The system is on an extremely outdated patch level though. I worked around it by setting "-DNO_RECVMMSG" during Configure.

**Comment by t8m** [comment]
**OTC: is requiring `-DNO_RECVMMSG` on some old glibc based platforms acceptable?**

**Comment by mattcaswell** [comment]
I wonder if there is something else we can test to identify these platforms?

**Comment by mattcaswell** [comment]
> sendmmsg(2) was introduced in Linux 3.0 and glibc 2.14.

But recvmmsg(2) was introduced in Linux 2.6.33, glibc 2.12. The `MSG_WAITFORONE` flag was introduced in Linux 2.6.34.

So, there are some versions where recvmmsg exists (and the `MSG_WAITFORONE` flag) but sendmmsg does not.

**Comment by mattcaswell** [comment]
Possible fix for this in #22036.

@rainerjung - would you be able to test the path?

**Comment by rainerjung** [comment]
@mattcaswell - the patch from #22036  worked well for me on old and new platforms. The correct API (recv|send)(mmsg|msg) gets automatically selected. Thanks.

**Comment by mattcaswell** [comment]
> @mattcaswell - the patch from https://github.com/openssl/openssl/pull/22036 worked well for me on old and new platforms. The correct API (recv|send)(mmsg|msg) gets automatically selected. Thanks.

Great! Thanks for testing this.
