### ISSUE TITLE
RSA PCT in FIPS mode

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#22035]
I have an impression that in FIPS mode we execute the RSA PCT test twice
https://github.com/openssl/openssl/blob/ebce766bb82b472eb3b796c5ee5ee2c19beb71f5/crypto/rsa/rsa_gen.c#L430-L451

First, it happens in https://github.com/openssl/openssl/blob/ebce766bb82b472eb3b796c5ee5ee2c19beb71f5/crypto/rsa/rsa_sp800_56b_gen.c#L413-L414

Then we set the flag that enforces calling the `rsa_keygen_pairwise_test` function: https://github.com/openssl/openssl/blob/ebce766bb82b472eb3b796c5ee5ee2c19beb71f5/crypto/rsa/rsa_gen.c#L479

What is the exact requirement for PCT?

**Comment by nhorman** [comment]
The [FIPS 140-2 implementation guide, section 9.9](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Module-Validation-Program/documents/fips140-2/FIPS1402IG.pdf) indicates that a pairwise test shall be preformed any time a public/private keypair is generated, using either a encrypt/decrypt operation or a signature/validation option.

There isn't anything in there about having to run the tests multiple times, and I think you're right, in rsa_keygen when built with FIPS enabled, we implicitly call rsa_keygen_pairwise_test once when we generate the key in ossl_rsa_sp800_56b_generate_key, and again if pairwise_test is set to true (which it always will be with FIPS enabled)

It looks like theres a specific unit test that expects the pairwise test to be run every time ossl_rsa_sp800_56b_generate_key is called (and its called directly from test_sp80056b_keygen)

I would think the solution here would be to just drop the pairwise_test = 1 statement from rsa_keygen

**Comment by nhorman** [comment]
scratch some of what I said before, the test in ossl_rsa_sp800_56b_pairwise_test is different from the one in rsa_keygen_pairwise_test.  the former is taken from SP800-56Br1 6.3.1.3 , and is a general validity recommendation while the latter is taken from the FIPS 140-2 installation guide, and is specifically for FIPS

It does raise the question why the test in rsa_keygen isn't conditional on FIPS_MODULE being defined, but looking at it, it seems like a reasonable sanity test in all cases, which might explain the lack of FIPS_MODULE conditions

**Comment by beldmit** [comment]
I understand that the checks are different here. My question is whether one is sufficient.

**Comment by nhorman** [comment]
I don't believe so, sp80056b mandates that that specific test be performed, and I believe an inconsistent key may still be able to encode and decode a message (i.e. the former test could fail, while the latter passes).

The only thing I see that would be optional here would be running the rsa_keygen_pairwise_test when not running in a FIPS environment

**Comment by paulidale** [comment]
@slontis? thoughts here?

**Comment by slontis** [comment]
pairwise_test is set to 1 when FIPS_MODULE is defined, otherwise it is not used.
An Encrypt/Decrypt pairwise test is the self test that is required by fips 140 IG requirements.

The other test as explained above is a sanity test that is part of the spec for the standard keygen. Incuding or omitting it will make no difference to the speed of the algorithm. The speed is affected by having to loop multiple times + doing prime tests using Miller Rabin.

**Comment by slontis** [comment]
Note that I didnt come up with the names for pairwise for these 2 cases, they both come from the standards.

**Comment by nhorman** [comment]
This seems to be complete, so I'm marking it as inactive.  Will close at the end of the 3.4 dev cycle without further input

**Comment by t8m** [comment]
IMO this can be closed outright given the @slontis response.
