### ISSUE TITLE
invalid aes-128-cbc encryption

### ISSUE THREAD

**Issue by rbignon** [openssl/openssl#2206]
Hello,

There is a problem with cipher `aes-128-cbc` with openssl 1.1.0c. If I try to encrypt a string:

> $ openssl version
> OpenSSL 1.1.0c  10 Nov 2016
> $ echo "lol" | openssl enc -aes-128-cbc -salt -base64 -A -pass pass:password
> U2FsdGVkX1913Wiht6GTal3Fi2TAAlNMue381sAJoaY=
 
Then I can't uncrypt it with an older version of openssl:
 
> $ openssl version
> OpenSSL 1.0.1t  3 May 2016
> $ echo "U2FsdGVkX1913Wiht6GTal3Fi2TAAlNMue381sAJoaY=" | openssl enc -d -aes-128-cbc -salt -base64 -A -pass pass:password
> bad decrypt
> 139678358040088:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:516:

**Comment by levitte** [comment]
OpenSSL 1.0.1t's `openssl enc` uses MD5 to make keydata from the password.  OpenSSL 1.1.0c's `openssl enc` uses SHA256 instead.

You can remedy this by tell OpenSSL 1.1.0c's `openssl enc` to use MD5, like this:

```
echo "lol" | openssl enc -e -aes-128-cbc -salt -base64 -A -pass pass:password -md md5
```

You should also be able to do the reverse, by telling OpenSSL 1.0.1t's `openssl enc` to use sha256.  I'm a little unsure about the latter.

Hope that helped.

**Comment by rbignon** [comment]
Ok you're right, that fixes my problem.

Thank you.
