### ISSUE TITLE
d2i_X DECODER example(s) absent

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#22068]
The d2i_X man page(s) could use some help for using OSSL_DECODER stuff. It does have some quick starter code for the OSSL_ENCODER part relating to i2d_X functions.

https://www.openssl.org/docs/manmaster/man3/d2i_ECPKParameters.html

Something along the lines of a section called `Migrating d2i functions to OSSL_DECODER`

Trying to see how this could potentially be done to replace d2i_ECPKParameters in existing code, but really can't seem to string the dots to getting a group (EC_GROUP) in the end. I did check in apps/ecparams.c which has a nice unused `OSSL_DECODER_CTX *dctx_params`variable in the code (same with a dctx in ec.c). All the apps stuff goes down the OSSL_STORE route (from apps/lib) which I don't need.

**Comment by t8m** [comment]
There is no OSSL_DECODER based replacement for d2i_ECPKParameters() as there is no way to get EC_GROUP from inside of a provider. Please note that d2i_ECPKParameters() function is not deprecated.

**Comment by dlegaultbbry** [comment]
I guess what threw me off is that it says this on the man page `All functions described here are deprecated. Please use OSSL_DECODER(3) instead of the d2i functions and OSSL_ENCODER(3) instead of the i2d functions. See "Migration" below.`

If it isn't deprecated, perhaps change the man pages for these specific functions that continue to be supported to avoid talking about any of the OSSL_[DE|EN]CODER stuff? I presume the inverse i2d is also not deprecated then.

**Comment by t8m** [comment]
The fix is quite easy - these should be documented in the other d2i manpage, not the one documenting the deprecated functions.
