### ISSUE TITLE
difficulties building under MacOS Ventura

### ISSUE THREAD

**Issue by steve-summit** [openssl/openssl#22071]
Trying to build under MacOS 13.0 Ventura, using clang version 14.0.3.

Configure ran fine.  But the build generates thousands of errors, chief among them:
* include/openssl/macros.h:155: error: "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
* include/internal/cryptlib.h:62: warning: type specifier missing, defaults to 'int' [for the line `DEFINE_LHASH_OF_EX(MEM);`, suggesting that the `DEFINE_LHASH_OF_EX` is not expanding correctly]
* error: unknown type name 'OSSL_LIB_CTX'

Happy to run experiments, provide more info, etc.

Config info:
[config_dump.txt](https://github.com/openssl/openssl/files/12581242/config_dump.txt)

**Comment by steve-summit** [comment]
Whoops... looks like it was an obscure issue in my compilation environment.  Closing.

**Comment by tom-cosgrove-arm** [comment]
Glad you've got it sorted.

If you're able to give a quick summary of the problem in your environment, and what you did to fix it, this could help people in the future who have the same problem
