### ISSUE TITLE
1.1.1w still marked as dev in version info

### ISSUE THREAD

**Issue by krishean** [openssl/openssl#22080]
It looks like `README` and `include/openssl/opensslv.h` were missed when the 1.1.1w tag was created yesterday.

Edit: `CHANGES` also has "[xx XX xxxx]", and `NEWS` "[under development]"

**Comment by mattcaswell** [comment]
Actually it looks to me like the tag is on the wrong commit. Should be on e04bd3433f

**Comment by krishean** [comment]
That would do it

**Comment by t8m** [comment]
Fixed now.
