### ISSUE TITLE
Using multiple streams and the default stream results in two SSL objects pointing to the same stream

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#22106]
The `SSL_set_default_stream_mode` man page says this:

````
It is recommended that new applications and applications which rely on multiple
streams forego use of the default stream functionality, which is intended for
legacy applications.
````

The `SSL_accept_stream` man page says this:

````
Depending on whether default stream functionality is being used, it may be
necessary to explicitly configure the incoming stream policy before streams can
be accepted; see L<SSL_set_incoming_stream_policy(3)>. See also
L<openssl-quic(7)/MODES OF OPERATION> for more information on default stream
functionality.
````

So, while it is not recommended, it is allowed to have a multi-stream application while still using a default stream.

I have encountered the following unexpected behaviour:

- Client does not change the default stream mode and sets the incoming stream policy to `SSL_INCOMING_STREAM_POLICY_ACCEPT`
- Server sends first on a new bidi stream
- Client attempts to read via `SSL_read_ex` and passing the QCSO
- The read is successful
- Server creates another new bidi stream and sends data on it
- The client calls `SSL_accept_stream()`
- The client successfully receives back a new QSSO object (that is different to the QCSO)

Reads on the QSSO then fail. It seems that the QSSO is actually referring to the *first* stream and not the second stream created on the server, i.e. we now have two SSL Objects pointing to the same stream - the original QCSO and the new QSSO.

This doesn't seem like correct behaviour!

**Comment by paulidale** [comment]
> So, while it is not recommended, it is allowed to have a multi-stream application while still using a default stream.

I think we should ban this.  Either your application is stream aware or it isn't and used the default stream.
I'm sure we discussed this at some point.

**Comment by hlandau** [comment]
I don't see the need to ban this and this looks like a bug.

**Comment by hlandau** [comment]
The issue appears to be that `qc_wait_for_default_xso_for_read` assumes that the first stream created by the peer will have a stream ordinal of 0 (which is correct), but because of this it doesn't call `ossl_quic_stream_map_remove_from_accept_queue`. Should be an easy fix; just add this call to `qc_wait_for_default_xso_for_read`.
