### ISSUE TITLE
FIPS 140 / FIPS 186-5: Edwards curves are approved for ECDSA but not for key exchange.

### ISSUE THREAD

**Issue by swkeypair** [openssl/openssl#22105]
The categorization of PROV_NAMES_X25519 and PROV_NAMES_X448 in providers/fips/fipsprov.c seems to be the opposite of the current NIST position on Edwards curves in FIPS 186-5. 

These PROV_NAMES are treated as:

- [FIPS_DEFAULT_PROPERTIES in fips_keyexch[]](https://github.com/openssl/openssl/blob/master/providers/fips/fipsprov.c#L413-L414) 
- [FIPS_UNAPPROVED_PROPERTIES in fips_keymgmt[]](https://github.com/openssl/openssl/blob/master/providers/fips/fipsprov.c#L474-L477)
- [FIPS_UNAPPROVED_PROPERTIES in fips_signature](https://github.com/openssl/openssl/blob/master/providers/fips/fipsprov.c#L430-L432)

[FIPS 140-3 Implementation Guidance article C.K Resolution 5](https://csrc.nist.gov/CSRC/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf#page=113) specifically disallows use of X25519 and X448 relative to SP 800-56A, while [FIPS 186-5](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf#page=35) and [SP800-140C](https://csrc.nist.gov/projects/cryptographic-module-validation-program/sp-800-140-series-supplemental-information/sp800-140c#digital-signature) specifically recognize and approve Ed25519 and Ed448.

Possible resolution: 
- fips_keyexch: change instances of X25519 and X448 to FIPS_UNAPPROVED_PROPERTIES 
- fips_keymgmt: change instances of X25519 and X448 to FIPS_UNAPPROVED_PROPERTIES
- fips_keymgmt: change instances of ED25519 and ED448 to FIPS_DEFAULT_PROPERTIES
- fips_signature: change instances of  ED25519 and ED448 to FIPS_DEFAULT_PROPERTIES

**Comment by paulidale** [comment]
Refer to an earlier discussion about this: https://github.com/openssl/openssl/discussions/22054

It is our understanding, from our lab, that X25519 and X448 can remain with the default properties, they aren't approved by are still allowed to be available.

Ed25519 and Ed448 could be changed to approve if the corresponding self tests are also implemented.

**Comment by swkeypair** [comment]
I replied in issue #22054 - I'm unsure what the etiquette is for where to reply in this case.
It seems fairly clear from the current IG C.K and SP 800-186 that the Edwards curves are specifically disallowed for key agreement (key exchange).

I will move those updates to this post if that is more appropriate.

**Comment by paulidale** [comment]
Fine to comment in #22054.  Best to keep the information & discussion together.

**Comment by paulidale** [comment]
I've not looked into the power up testing required for the Ed curves.  I expect it's straightforward but needs to be done.

**Comment by slontis** [comment]
Already added a PR, not as straight forward as you would hope since it uses the DigestSign API (oneshot) which needed to be exposed to the FIPS provider.
