### ISSUE TITLE
Commit "Add size limit to X509_NAME structure" to 1.0.1t cause failure on CRL greater than 1MB

### ISSUE THREAD

**Issue by slonvpalto** [openssl/openssl#2213]
This [commit](https://git.openssl.org/?p=openssl.git;a=commit;h=53d6c14befdf0414f658e663a0e7a4cf6382588f) to 1.0.1t generates error on processing CRL with size greater than 1MB. Example:

[root@dev-na-olpekar1 ~]# openssl crl -in CRL1.crl -inform DER -noout -text
unable to load CRL
140376834422440:error:0D09E09B:asn1 encoding routines:X509_NAME_EX_D2I:too long:x_name.c:203:
140376834422440:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:697:Field=issuer, Type=X509_CRL_INFO
140376834422440:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:697:Field=crl, Type=X509_CRL

Other openssl versions parse this CRL fine (e.g. 1.0.2j, 0.9.8r)

**Comment by mattcaswell** [comment]
It was later fixed in this commit b583c1bd06.

I'd suggest trying 1.0.1u, except that the 1.0.1 series is now out of support as of 1st January. Therefore I'd instead suggest upgrading to 1.0.2j
