### ISSUE TITLE
openssl s_client -cipher - not works!

### ISSUE THREAD

**Issue by ClemFandango2** [openssl/openssl#22141]
For example, which ciphersuites github.com supports?
https://www.ssllabs.com/ssltest/analyze.html?d=github.com
There is TLS_RSA_WITH_AES_128_CBC_SHA, no matter how weak it is.
According to https://ciphersuite.info/cs/TLS_RSA_WITH_AES_128_CBC_SHA/ , its openssl name is AES128-SHA.
I type:
```
openssl s_client -cipher AES128-SHA -connect github.com:443
```
But get:
```

Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
...
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
...
    Cipher    : TLS_AES_128_GCM_SHA256
...
```

Version:

    OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

How to set exactly this ciphersuite? I need it.

**Comment by beldmit** [comment]
If you want to use exactly this ciphersuite, use `-no_tls1_3` or `-tls1_2`

       -cipher cipherlist
           This allows the TLSv1.2 and below cipher list sent by the client to be modified.  This list will be combined with any TLSv1.3 ciphersuites that have been configured. Although the server determines which ciphersuite is
           used it should take the first supported cipher in the list sent by the client. See openssl-ciphers(1) for more information.

       -ciphersuites val
           This allows the TLSv1.3 ciphersuites sent by the client to be modified. This list will be combined with any TLSv1.2 and below ciphersuites that have been configured. Although the server determines which cipher suite is
           used it should take the first supported cipher in the list sent by the client. See openssl-ciphers(1) for more information. The format for this list is a simple colon (":") separated list of TLSv1.3 ciphersuite names.

**Comment by ClemFandango2** [comment]
Ah, thanks. May be closed.
