### ISSUE TITLE
OpenSSL should support a method for providers to self-activate by installing a file

### ISSUE THREAD

**Issue by neverpanic** [openssl/openssl#22148]
To support the OQS provider of PKCS11 provider in distributions, it would be best if installation of the package that contains the provider module can automatically add the provider to OpenSSL's configuration.

One possible solution for this would be a `include.d` directive that works like `include` but instead takes a directory and includes all `.cnf` files in that directory. This would allow distributions to configure their copy of OpenSSL with a default include directory for configuration files, e.g., `/etc/openssl/providers.conf.d`, add `include.d /etc/openssl/providers.conf.d` to the main `openssl.cnf`.

3rd party providers such as oqsprovider or pkcs11-provider could then install `/etc/openssl/providers.conf.d/oqs.cnf` or `/etc/openssl/providers.conf.d/pkcs11.cnf` that load and enable these providers, and automatically remove the configuration when uninstalling the package.

**Comment by beldmit** [comment]
A side comment: currently we have a recursive parsing of config. It means that, to activate a provider, we need a ref to its section from the providers section. I'm not sure if smth like 

```
[provider_sect]
my_prov = my_sect
[my_sect]
```

in the included file will work. If it doesn't, we should deal with it.

**Comment by mattcaswell** [comment]
I like this idea, although the issue @beldmit raises is a concern, so we'd need to figure out a solution to that.

**Comment by neverpanic** [comment]
This already works, but it does introduce a dependency between the configuration files:

`openssl.cnf`:
```ini
openssl_conf = openssl_init

config_diagnostics = 1

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
[default_sect]
activate = 1

.include legacyprov.cnf
```

`legacyprov.cnf`:
```ini
[provider_sect]
legacy = legacy_sect

[legacy_sect]
activate = 1
```

```bash
OPENSSL_CONF=openssl.cnf openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.0.9
    status: active
  legacy
    name: OpenSSL Legacy Provider
    version: 3.0.9
    status: active
```

The included configuration file needs to know the name of the provider section in the main OpenSSL config file. If that name changes, this stops working.

**Comment by beldmit** [comment]
> The included configuration file needs to know the name of the provider section in the main OpenSSL config file. If that name changes, this stops working.

It shouldn't be a big deal for a distribution, right?

**Comment by Deepanshi3112** [comment]
@beldmit a nice idea though

**Comment by xhanulik** [comment]
The described functionality for `include.d` should be already implemented as `include` directive supports taking directory and including all configuration files in that directory. I've implemented test which covers including configuration files with the provider section in #22598.

**Comment by t8m** [comment]
So do we still have an issue here?

**Comment by beldmit** [comment]
I think no, it just works

**Comment by t8m** [comment]
Closing this then.
