### ISSUE TITLE
3% Performance degredation in low level ECDSA_Sign vs. 1.1.1

### ISSUE THREAD

**Issue by wbl** [openssl/openssl#22165]
We have observed a 3% performance degredation between 3.0.9 and 1.1.1t when using the ECDSA-Sign routines. It appears that the random number generation is the cause of the slowdown, with a number of expensive provider calls. We're investigating if this still happens in 3.1 or later releases, although testing with later releases can be more complicated due to the stomping on the quic API support we added in.

**Comment by wbl** [comment]
This gets worse on a bigger CPU machine, although we're still investigating exactly which parts are OpenSSL vs. our secure memory allocator.

**Comment by nhorman** [comment]
ping @wbl  can you provide performance statistics to guide this issue?

**Comment by nhorman** [comment]
No response, marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by wbl** [comment]
Unfortunately I've moved on to other projects and we're just going to take the hit. Will investigate sometime and reopen if the problem still exists.

**Comment by nhorman** [comment]
Understood, apologies.  FWIW, We have several ground up performance efforts underway independent of this, so there is a real possibility that this may get fixed in that interim.
