### ISSUE TITLE
NonStop Port: Add pure Guardian support

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#22175]
I am working on configuration and code for allowing OpenSSL to work in a pure NonStop Guardian environment. This has to be a 32-bit build without threading and has limited POSIX facilities.

If anyone wants to help, I would be grateful of that support.

**Note:** The current `nonstop-nsx_g` configuration does not build correctly in 3.0-3.2, so will be modified once (if) this effort is complete. I hope I can make 3.2 for this feature.

My intent is to make use of as much of the existing code supporting Guardian as possible and similarly as little actual code changes as practical to align with the working NonStop OSS port.

**Comment by nhorman** [comment]
ping @rsbeckerca , unsure of the status of this issue.  Did you ever do anything with it?  I don't see an attached pull request

**Comment by rsbeckerca** [comment]
I think this can be closed. I'm not going to work on it. The user who wanted this feature has not responded, so let's drop this.

**Comment by rsbeckerca** [comment]
The only addendum to the above is that I think the `_g` rules should be removed before we close this. While they are documentation only, they are presenting confusion. I can do this as a fix for this issue.

**Comment by nhorman** [comment]
ACK, if you have interest in fixing the documentation, please open a PR for it at your convenience
Thanks!

**Comment by rsbeckerca** [comment]
@nhorman Can you reopen, to allow the PR

**Comment by tmshort** [comment]
#24579 was merged to `master`.
