### ISSUE TITLE
Default to P-256 in absence of supported_groups extension

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#2219]
As was discussed on the [devel mailing list](https://mta.openssl.org/pipermail/openssl-dev/2016-September/008488.html), defaulting to X25519 curve for ECDHE is likely to cause interoperability issues.

both master (928933f92fa214f) and OpenSSL_1_1_0-stable (d257b86caadb) branches exhibit the same problematic behaviour

**Comment by richsalz** [comment]
Please see https://github.com/openssl/openssl/pull/1597

**Comment by mattcaswell** [comment]
Ping @richsalz. Can this be closed?
