### ISSUE TITLE
Is the assignment of ctx->fetched_cipher required even if EVP_CIPHER object used is the same?

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#22191]
### Discussed in https://github.com/openssl/openssl/discussions/22189

<div type='discussions-op-text'>

<sup>Originally posted by **KostasTsiounis** September 26, 2023</sup>
In our application we are using the `EVP_CipherInit_ex/EVP_CipherUpdate/EVP_CipherFinal_ex` set of methods to perform AES/GCM. After moving to OpenSSL 3.x from 1.1.1, we saw a significant regression in multithreaded performance scenarios. After getting call graph data using `perf`, we found out that a lot of the time is spent in `EVP_CipherInit_ex` -> `EVP_CIPHER_up_ref`, which results in a substantial amount of thread-locking and unlocking.

Looking further into the openssl code, we found this particular part: https://github.com/openssl/openssl/blob/91bc783a93a2a695fe6a2f8da93cf5b5e086ba42/crypto/evp/evp_enc.c#L204

In this part, the `ctx->fetched_cipher` is freed, then a call to `EVP_CIPHER_up_ref` is made and, finally `ctx->fetched_cipher = (EVP_CIPHER *)cipher;`. However, we think that this whole if statement could be avoided if `ctx->fetched_cipher == cipher`.

After changing the condition to `if ((cipher != ctx->fetched_cipher) && (cipher->prov != NULL))`, building and retesting, we saw a 3x improvement when using multiple threads.

The question here is, is there a scenario where even if `cipher` and `ctx->fetched_cipher` point to the same struct, the steps that are part of this if statement still need to be executed?</div>

**Comment by t8m** [comment]
Fix in #22198

**Comment by nhorman** [comment]
Given @t8m comment above, It seems this can be closed
