### ISSUE TITLE
asn1 encoding routines:ASN1_mbstring_ncopy:invalid utf8string:.\crypto\asn1\a_mbstr.c:132:

### ISSUE THREAD

**Issue by soenter** [openssl/openssl#222]
<b>command:</b>

openssl req -x509 -newkey rsa:1024 -subj "/CN=中文/OU=中文/O=中文/L=中文/ST=中文/C=CN" -passout pass:123456 -keyout private/S1234567_key.pem -out certs/S1234567.cer -outform PEM -days 365 -utf8

<b>error message:</b>
Loading 'screen' into random state - done
Generating a 1024 bit RSA private key
.......++++++
.....++++++

-----
problems making Certificate Request
6004:error:0D07A086:asn1 encoding routines:ASN1_mbstring_ncopy:invalid utf8string:.\crypto\asn1\a_mbstr.c:132:

<b>use openssl-1.0.1j</b>

**Comment by levitte** [comment]
I just checked with the newly released 1.0.1r.  Works like a charm.  So my suggestion is to upgrade.

**Comment by winrey** [comment]
it's happened again in v1.0.2j :(
