### ISSUE TITLE
QUIC support stomps on quic_ prefix and SSL_is_quic

### ISSUE THREAD

**Issue by wbl** [openssl/openssl#22204]
Like many users of OpenSSL we have maintained a patch that uses the BoringSSL originated QUIC API. While this patch wasn't accepted upstream by OpenSSL, we've continued to rebase our work on it. Unfortunately the current work on QUIC in the master branch has stomped over the quic_ prefix, making it hard to continue.

**Comment by t8m** [comment]
Yeah, such things happen to forks. It was not intentional as you have to agree that using quic_ prefix for various internal symbols when implementing the QUIC protocol is quite logical thing to do. I'd recommend using a different prefix in your fork if you plan to rebase it on top of 3.2.

And for public symbols OpenSSL 3.2 does not use the quic_ prefix. Any new public symbols should be prefixed with OSSL_ and even any new private symbols that would appear in static libraries should be prefixed with ossl_. So the use of quic_ prefix is purely internal.

**Comment by wbl** [comment]
SSL_is_quic is also involved, but that one is really the sensible name for both of us to use, so I guess I'll just be unhappy

**Comment by wbl** [comment]
Could you consider prefixing as OSSL_is_quic? Changing the name of the existing function in the forks is a binary compatibility issue that would be very painful to work out.

**Comment by paulidale** [comment]
As you already noted `SSL_is_quic` is the sensible name.  I doubt we're going to change it.
This is part of the burden forks accept if they want to continue consuming from the mainline.

**Comment by levitte** [comment]
I'll note that `SSL_is_quic()` has (almost, there's a const difference) the same signature in both.  I'd suggest living with that and do something under the hood to determine which underlying code path you should use.

**Comment by mattcaswell** [comment]
So our implementation is:

````
int SSL_is_quic(const SSL *s)
{
#ifndef OPENSSL_NO_QUIC
    if (s->type == SSL_TYPE_QUIC_CONNECTION || s->type == SSL_TYPE_QUIC_XSO)
        return 1;
#endif
    return 0;
}
````

Can't you just change that in your fork to:

````
int SSL_is_quic(const SSL *s)
{
#ifndef OPENSSL_NO_QUIC
    if (s->type == SSL_TYPE_QUIC_CONNECTION || s->type == SSL_TYPE_QUIC_XSO)
        return 1;
#endif
    return do_your_implementation_of_ssl_is_quic(s);
}
````

**Comment by wbl** [comment]
What do you think we picked for our feature switch?  But that's a lot easier for us to change. Thanks for your suggestions.

**Comment by hlandau** [comment]
In any case, this is not a bug. All `quic_` prefixed symbols are static and internal to a translation unit and we offer no namespacing guarantees here. The `SSL_` namespace is reserved to OpenSSL, as is `OSSL_`; however using the latter would make no sense here as `SSL_is_quic` is a method on an SSL object.
