### ISSUE TITLE
Performing DTLS handshake with bogus versions

### ISSUE THREAD

**Issue by bathooman** [openssl/openssl#22208]
**Affected Version**: 3.1.2

During our tests, we noticed that a client can complete a DTLS handshake with non-existent DTLS versions. In the following screenshot, the marked packet contains a `CKE` with the non-existent version `0xfe00` (Wireshark does not recognize the packet due to the bogus version).

![image](https://github.com/openssl/openssl/assets/3464382/40f05f49-1d08-4d3d-a005-64b26aec3f40)

I attached the handshake PCAP file for more info.

[openssl-0.zip](https://github.com/openssl/openssl/files/12739159/openssl-0.zip)

**Comment by mattcaswell** [comment]
I believe this is deliberate. We only verify that the major version number is the same and ignore the minor version number.

**Comment by nhorman** [comment]
@mattcaswell given your comment above, it should like this should be labeled notabug.  Is that the case?  Or is there something else to be done here?

**Comment by mattcaswell** [comment]
Nothing to be done I think - so closing.
