### ISSUE TITLE
openssl cms -encrypt command with -aes-128-ctr / -aes-256-ctr

### ISSUE THREAD

**Issue by gilweis** [openssl/openssl#22225]
Hi,
openssl cms -encrypt command with -aes-128-ctr / -aes-256-ctr failed.
The output cms file is corrupted.
The command return 0 (another bug?)

```
$ openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

$ openssl cms -encrypt -in /tmp/data.txt -AES-256-CTR -out /tmp/data.enc.cms  -recip /tmp/cert.der
$ echo $?
0
$ openssl cms -cmsout -in /tmp/data.enc.cms -print
Error reading SMIME Content Info
40E7E535A77F0000:error:0680006E:asn1 encoding routines:b64_read_asn1:decode error:../crypto/asn1/asn_mime.c:151:
40E7E535A77F0000:error:068000CB:asn1 encoding routines:SMIME_read_ASN1_ex:asn1 parse error:../crypto/asn1/asn_mime.c:500:

```

Same command with -AES-256-CBC parameter works fine.

**Comment by t8m** [comment]
AES-256-CTR has no OID so it cannot be properly encoded into the CMS message. That no error is printed and the exit value is 0 is clearly a bug.

**Comment by jamuir** [comment]
I can take a look at this.

**Comment by jamuir** [comment]
you can use the cert `demos/cms/signer.pem` to reproduce this (if you do not want to create a new cert).

**Comment by jamuir** [comment]
In this case, `SMIME_write_CMS()` actually does return an error (inside `cms.c`), but it is lost because `ret` gets clobbered:

https://github.com/openssl/openssl/blob/cd138c33d82cc889fe6a16d18806fbe939279d25/apps/cms.c#L1244C1-L1268C13

**Comment by jamuir** [comment]
I have opened a PR that fixes this.
