### ISSUE TITLE
Limit the number of http headers when receiving the http response

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#22264]
Currently the http server can push infinite number of headers and the processing of them in http_client.c will never stop.

This is not a security issue according to our policy as it is not really useful for DoS attack purposes as the http server has to keep a connection open.

**Comment by t8m** [comment]
@DDvO might be interested in fixing this issue.

**Comment by DDvO** [comment]
Any (type of) server could also send regular responses (http body etc.) of 'infinite' length.

**Comment by DDvO** [comment]
If a client wants to be immune on anything like this, limits need to be configurable with sensible defaults,
such that an application that wants to handle unusually large input is not limited by the (http) client component.

**Comment by DDvO** [comment]
I'm not sure if this topic is worth special support.

**Comment by t8m** [comment]
**OTC: Do we need to limit the number of HTTP headers processed on response or just keep the code as is?**

**Comment by t8m** [comment]
**OTC: This is not a security issue however we should limit the number processed headers to some reasonably high number for hardening.**

**Comment by hlandau** [comment]
This should not be backfitted.
