### ISSUE TITLE
It is no longer possible to insert a second identical unsigned attribute into a CMS/CAdES signature

### ISSUE THREAD

**Issue by gaugo87** [openssl/openssl#22266]
Hi All,

I'm using OpenSSL 3.0.11 (previously 3.0.8).
Since this change https://github.com/openssl/openssl/pull/21505, it is no longer possible to insert a second identical unsigned attribute into a CMS/CAdES signature (like many archiveTimestamp attributes for example).

The problem lies in the CMS_unsigned_add1_attr_by_NID function, which relies on X509at_add1_attr_by_NID.

Thanks.

**Comment by t8m** [comment]
**OTC: Should we revert #21505 ?**

**Comment by t8m** [comment]
**OTC: We should not revert #21505 but this needs to be investigated and possibly a different fix is needed.**
