### ISSUE TITLE
DH_check_pub_key() return code confusion

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#22287]
The implementation of DH_check_pub_key_ex() seems to presume that DH_check_pub_key() will return a non-zero value as long as the check could be performed and that any specific validation failures can be fished out after via the error flags:

https://github.com/openssl/openssl/blob/456e6ca5d73972cdb4228e6c5ec9acdf19237308/crypto/dh/dh_check.c#L230-L245

However, this assumption does not seem to hold (any validation failure seems to result in return value of 0), and so the various ERR_raise() don't seem to occur as intended.

The way I discovered this was via the EVP_PKEY_public_check() API (ie, the non-deprecated one) which seems to call into this under the covers. It appeared that the error stack obtained via ERR_print_errors() was empty upon failure, which made sorting out what was wrong with the peer-generated key being checked a bit more of a chore than I'd have liked.

**Comment by paulidale** [comment]
I'm not sure I understand the question here.  This function is only raising one of three particular errors, so you shouldn't expect to always get one.

The function is returning 0 on failure and 1 on success.  Success being that the key appears valid and failure that it isn't.

**Comment by jwalch** [comment]
Perhaps you don't understand the question because there wasn't one. This is a bug report.

My point is that lines 238, 240, & 242 are effectively unreachable because if key is invalid for any reason it seems we execute line 235 and return before the error mapping anyway. As it happens in my case, DH_CHECK_PUBKEY_INVALID was the relevant one... but the ERR_raise() never happens because DH_check_pub_key() returns 0 in that scenario.

**Comment by jwalch** [comment]
Honestly this whole internal DH_check_pub_key() interface seems unnecessarily convoluted.

The error codes:
https://github.com/openssl/openssl/blob/11f69aa50771d50151fa24c55fd0858db30517df/include/openssl/dh.h#L162-L165

or is it these:

https://github.com/openssl/openssl/blob/11f69aa50771d50151fa24c55fd0858db30517df/include/internal/ffc.h#L72-L79

The answer is that it's both! At the site of generation, the FFC codes are used. I couldn't find any case where the DH ones are assigned (they seem to exist for the sole purpose of the checks in this code that... uh, yeah). Good thing they at least align...

Also, what good is a bitmask doing here? I mean, a number obviously can't be both too small and too large at the same time and public/private is also mutually exclusive. Perhaps the intent was for the pub_key^q == 1 mod p check (which seems to be the only use of FFC_ERROR_PUBKEY_INVALID) to happen independently of the range check, but it's not hard to read ossl_ffc_validate_public_key() and realize THAT ain't happenin'. **shrug**

Independently of whether it's a bitmask or not, why not just use the return value instead of requiring an output parameter? Like, if the intent is to distinguish "weird internal errors" (allocation failure, for example) from the mathematical improprieties, you could just partition the integer range... you don't need two different integers...

**Comment by t8m** [comment]
Fix in #22291 

And no, I do not think we should change the API - the function is deprecated anyway.

**Comment by jwalch** [comment]
I hadn't intended to suggest a public-facing API change. I mistakenly thought that DH_check_pub_key() (rather than DH_check_pub_key_ex()) was internal, but apparently it is exposed via the public header and is merely undocumented. In that case I definitely agree that restoring the behavior of DH_check_pub_key() back to what it originally was (and what the DH_check_pub_key_ex() implementation expects) is the most immediate course of action.

I think the fact that both functions are deprecated is a bit misleading, since the "blessed" EVP_PKEY_public_check() calls into them internally anyway. Of course, that could be changed and it could conceivably call into more simplified versions of the same functionality without being a breaking change.

Really my point in bringing it up was to illustrate that perhaps the bug as originally reported shouldn't have been too surprising. The original DH_check_pub_key() semantics are a bit unusual... which I guess is why DH_check_pub_key_ex() became the preferred public entry point (hence being the one that is documented) in the first place (before the Great EVP_PKEY refactoring in more recent releases superseded that apparent preference).
