### ISSUE TITLE
random number during dsa

### ISSUE THREAD

**Issue by ariesding0520** [openssl/openssl#22308]
Can I get the random number generated by openssl during the DSA?

**Comment by jamuir** [comment]
I'm not sure if this needs to be a feature.

@ariesding0520 : would it suffice if we instead provided an example of how to modify the dsa-sign function to print the nonce? (i.e. the value of `k`) ?

**Comment by ariesding0520** [comment]
I have modified the code and print the nonce. Thank you! But it would be great if you can offer this feature because someone like me may apply openssl as the golden data source for their hardware design. If we can get the nonce, then we can calculate the dsa with the hardware design and compare the result with the openssl to verify my hardware design.

**Comment by nhorman** [comment]
Is the OSSL_PKEY_PARAM_FFC_SEED param not available for just this purpose?  the openssl gendsaparam applet uses this param to set the seed (and optioinally write it out via the --writerand optiion)

**Comment by t8m** [comment]
No, the k number here is the DSA signature nonce. You can use the low level functions DSA_sign_setup()/DSA_sign_ex() but this still won't give you access to the raw nonce only to the kinv value computed from the nonce.

However I do not think this is a feature that should be provided. What would be the purpose? Leaking the nonce completely invalidates the security of the private key.

**Comment by nhorman** [comment]
There was another issue (need to find it) in which the request was to extract the nonce for verification purposes (they were validating a hardware signature algorithm against gold data, and using openssl to independently verify the signatures, for which they needed to use the same k value on both.  That said, I agree about the privacy concerns, so I'm fine just rejecting this as a feature request.

**Comment by t8m** [comment]
> There was another issue (need to find it) in which the request was to extract the nonce for verification purposes (they were validating a hardware signature algorithm against gold data, and using openssl to independently verify the signatures, for which they needed to use the same k value on both. That said, I agree about the privacy concerns, so I'm fine just rejecting this as a feature request.

Yeah, for such thing, they can IMO patch OpenSSL to print out the k value.
