### ISSUE TITLE
Incomplete error message from `openssl -in bad:prefix`

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#22306]
In OpenSSL 3.0.10 and 3.1.2, calling `openssl` with a bad `-in` prefix prints a nice error message:
```
$ openssl rsa -in bad:prefix -modulus -noout
Could not open file or uri for loading private key from bad:prefix
```

Since OpenSSL 3.0.11 and 3.1.3 however the first portion of the error message is missing, which makes it incomprehensible:
```
$ openssl rsa -in bad:prefix -modulus -noout
 private key from bad:prefix
```

**Comment by t8m** [comment]
Caused by  #21659 @DDvO
