### ISSUE TITLE
When using  openssl command to generate  keys, it will randomly fail

### ISSUE THREAD

**Issue by qiangfu1** [openssl/openssl#22326]
The following is a python script: 
genrsakey.py

import subprocess
import os
command = "openssl genrsa -out private_test.pem -3 3072"
for i in range(2000):
    result = subprocess.run(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        print(f"failed to gen RSA\n")

If this Python script is executed, it will fail to generate RSA keys twice on my machine.

sgx@intel:~/tmptest$ openssl  version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by levitte** [comment]
Might I suggest having a look at the resulting stdout / stderr output?  When the commands fail, they usually display an error

**Comment by qiangfu1** [comment]
genrsa: Error generating RSA key

**Comment by qiangfu1** [comment]
genrsa: Error generating RSA key

**Comment by t8m** [comment]
Please also note that using the option `-3` is not recommended for security reasons.

**Comment by nhorman** [comment]
Given that there was no response to posting the output of the python script, i'm marking this as inactive, to be closed at the end of the 3.4 dev cycle.  Please respond if there is an update here
