### ISSUE TITLE
Anonymous ciphers missing in OpenSSL 1.1.0c

### ISSUE THREAD

**Issue by PeterSurda** [openssl/openssl#2232]
I use the `AECDH-AES256-SHA` cipher for link encryption in https://github.com/Bitmessage/PyBitmessage. Since it's a P2P protocol, there is no node hierarchy and authentication doesn't have any meaning.

When doing compatibility tests with Debian testing, which comes with OpenSSL 1.1.0c, the cipher (along with all other anonymous ciphers AKA `aNULL`) is missing from the list of available ciphers (obtained by executing `openssl ciphers`). I tried to enable it with build-time options, but no matter what options I pass to `./config`, the list of ciphers remains the same. On Ubuntu 16.04 I got the same result (it comes with 1.0.2, but if you build 1.1.0c from source, anonymous ciphers are missing).

I checked the OpenSSL Changelog, and haven't found any mention of anonymous ciphers being disabled. I haven't found any way to enable them either even by looking at the code. The `ifdef`s in s3_lib.c show that if `OPENSSL_NO_EC` is not set, the cipher should be built. It's not excluded by `OPENSSL_NO_WEAK_SSL_CIPHERS`.

Can you please help me to understand:

- where is the code that disables anonymous ciphers
- how do I re-enable them again

?

**Comment by kroeckx** [comment]
You need to add @SECLEVEL=0 in your cipher string to enable them.

**Comment by PeterSurda** [comment]
Thanks, that indeed solved it. And it looks like that was introduced in 21e0c1d23afff48601eb93135defddae51f7e2e3, so for backwards compatibility, I should only use the new string for versions >= 0x10100000, correct?

**Comment by kroeckx** [comment]
Yes, otherwise you're going to get an error that it can't parse the cipherlist.

**Comment by vdukhovni** [comment]
If you're using the OpenSSL API in C, then instead of a custom cipher string, it may be easier to call:
```
#ifdef SSL_SECOP_PEER
    SSL_CTX_set_security_level(client_ctx, 0);
#endif
```
The `SSL_SECOP_PEER` macro was added as part of the introduction of security levels.  That said, testing for `OPENSSL_VERSION_NUMBER >= 0x10100000UL` also works, provided you're not compiling against LibreSSL (don't do that, LibreSSL is IMHO increasingly irrelevant).

**Comment by PeterSurda** [comment]
Thanks.

**Comment by PeterSurda** [comment]
@vdukhovni I'm not actually compiling anything, I'm using python, I just looked at the source of OpenSSL to find out why it wasn't working.
