### ISSUE TITLE
OS API usage auditing

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#22330]
@nhorman raised an interesting idea that we adopt some sort of policies on what OS APIs we do and don't use. In order to address this we would really need to start with some kind of visibility into what OS APIs we already do depend on. Having an automated API usage audit mechanism here would allow us to put this into CI and have a CI notice trigger automatically if a PR starts depending on an OS API we have never used before.

For symbols (functions/globals), some kind of objdump-based solution may work. It would need to have a way to exempt specific APIs which are approved. But it would also need to have a way to exempt only specific call sites (e.g. for malloc).

Auditing use of OS macros and structure definitions would be harder and would probably require use of compiler-specific functionality, though this is OK if it is something we just use in CI.

Not necessarily a priority but could be quite worthwhile in future to make our use of OS APIs more disciplined.

**Comment by nhorman** [comment]
Could we use a linker directive here, with some macros?  Perhaps a macro to identify an allowed call site for a function that encodes a string indicating such in the elf .comments section?  I've done that before with gcc, but I'm not sure is sufficiently supported on non gcc platforms

**Comment by paulidale** [comment]
Do you mean something like:
```c
#define memcpy allowed
#define strcpy allowed
…
```
then "compile" the sources and check what symbols remain?

Or are you thinking of something different?

**Comment by nhorman** [comment]
Something like that

Specifically I was thinking about macros in the form of:
#define ALLOW_API_USAGE(call) char* __call_notes= "Json to indicate that a given platform.call is allowed at this location" __attribute__((section(".comments")))

Or something similar to build notes into the elf file so when we scan for unwrapped platform calls, we can.filter.out.ones.we.allow


That's obviously not the right syntax, but you get the gist

**Comment by nhorman** [comment]
https://github.com/openssl/openssl/pull/22478

This should represent the start of some reasonable symbol monitoring.  It doesn't check for usage locations yet, but it will cause an error if we add  an external symbol to any openssl library without also updating the expected symbol list, which we can use to visually audit and discuss the need for said symbol(s)
