### ISSUE TITLE
OBJ_new_nid: lock may not be initialized before used by this function

### ISSUE THREAD

**Issue by SBKarr** [openssl/openssl#22337]
On platforms, where `TSAN_REQUIRES_LOCKING` defined (e.g. MSC with stdatomics), in [OBJ_new_nid](https://github.com/openssl/openssl/blob/8d120aef951d7bb7deac0b8b559f8003f5ea6384/crypto/objects/obj_dat.c#L227C8-L227C29), `ossl_obj_nid_lock` may not be initialized before `CRYPTO_THREAD_write_lock` on it. The lock init [here](https://github.com/openssl/openssl/blob/8d120aef951d7bb7deac0b8b559f8003f5ea6384/crypto/objects/obj_dat.c#L65), but it called only from `OBJ_obj2nid` or `OBJ_create`.

In [this](https://github.com/gost-engine/engine/blob/2a8a5e0ecaa3e3d6f4ec722a49aa72476755c2b7/gost_eng.c#L338) usage pattern, `ossl_obj_nid_lock` remains uninitialized when first used.

**Comment by nhorman** [comment]
https://github.com/openssl/openssl/pull/22350

Please test with that PR, should fix the issue

**Comment by t8m** [comment]
This applies to master and 3.1 only as in 3.0 the OBJ_new_nid (and any other OBJ_ calls) aren't supposed to be thread safe.

**Comment by nhorman** [comment]
@t8m ACK the problem won't appear there as OBJ_new_nid attempts no locking operations
