### ISSUE TITLE
Leak of los after ossl_X509_ALGOR_from_nid() failure in rsa_cms_encrypt()

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#22336]
If `ossl_X509_ALGOR_from_nid()` fails in `rsa_cms_encrypt()`, `los` is leaked.

https://github.com/openssl/openssl/blob/8d120aef951d7bb7deac0b8b559f8003f5ea6384/crypto/cms/cms_rsa.c#L150-L174

All other callers of `ossl_X509_ALGOR_from_nid()` free the last argument on failure (if it is non-NULL).

The bug was introduced with the addition of `ossl_X509_ALGOR_from_nid()` in #17363, which doesn't seem to be present in the 3.0 and 3.1 branches.

**Comment by t8m** [comment]
Thank you for the report. We will look at this soon.

**Comment by jamuir** [comment]
@botovq :  please take a look at #22495

**Comment by jamuir** [comment]
> The bug was introduced with the addition of ossl_X509_ALGOR_from_nid() in #17363

I'm not sure if I agree with that.  I think the potential leak was there before #17363 .

**Comment by botovq** [comment]
Yes, [I agree](https://github.com/openssl/openssl/pull/22495#issuecomment-1778406773).
