### ISSUE TITLE
test/drgbtest fails for entropy factors other than 1 (VMS on Alpha, but not only)

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#22332]
Running `mms test /MAC=(TESTS="test_rand",V=1)` reveals this:

```
    # ERROR: (bool) 'EVP_RAND_instantiate(x, 0, 0, NULL, 0, NULL) == true' failed @ USER:[LEVITTE.TEST.openssl-3_2_0-alpha3-dev.test]drbgtest.c;2:820
    # false
    # 80CEAF7B00000000:error:1200007D:random number generator:(unknown function):random pool overflow:USER:[LEVITTE.TEST.openssl-3_2_0-alpha3-dev.crypto.rand]rand_pool.c;2:252:
    # 80CEAF7B00000000:error:030000D6:digital envelope routines:(unknown function):generate error:USER:[LEVITTE.TEST.openssl-3_2_0-alpha3-dev.crypto.evp]evp_rand.c;2:560:
    # 80CEAF7B00000000:error:1C8000BD:Provider routines:(unknown function):error retrieving entropy:USER:[LEVITTE.TEST.openssl-3_2_0-alpha3-dev.providers.implementations.rands]drbg.c;2:449:


pipe MCR dsa10:[axp.perl-5_20.][000000]perl.exe;1 [--.util]wrap.pl MCR [--.test]drbgtest.exe => 2
```

**Comment by levitte** [comment]
I applied a diff to find out a bit more:

``` diff
diff --git a/crypto/rand/rand_pool.c b/crypto/rand/rand_pool.c
index 8dc230b540..a5d5798e3b 100644
--- a/crypto/rand/rand_pool.c
+++ b/crypto/rand/rand_pool.c
@@ -249,7 +249,11 @@ size_t ossl_rand_pool_bytes_needed(RAND_POOL *pool, unsigned int entropy_factor)
 
     if (bytes_needed > pool->max_len - pool->len) {
         /* not enough space left */
-        ERR_raise(ERR_LIB_RAND, RAND_R_RANDOM_POOL_OVERFLOW);
+        ERR_raise_data(ERR_LIB_RAND, RAND_R_RANDOM_POOL_OVERFLOW,
+                       "entropy_factor=%u,entropy_needed=%zu,bytes_needed=%zu,"
+                       "pool->max_len=%zu,pool->len=%zu",
+                       entropy_factor, entropy_needed, bytes_needed,
+                       pool->max_len, pool->len);
         return 0;
     }
 
```

With that, the output tells me a little more:

```
    # 80CEAF7B00000000:error:1200007D:random number generator:(unknown function):random pool overflow:USER:[LEVITTE.TEST.openssl-3_2_0-alpha3-dev.crypto.rand]rand_pool.c;3:252:entropy_factor=20,entropy_needed=256,bytes_needed=640,pool->max_len=32,pool->len=0
```

The entropy factor indicates that we're using a lousy entropy gatherer, which is our fallback on VMS when the system service `SYS$GET_ENTROPY` isn't present (it's fairly new, and as I recall, only available on IA64 and x86_64), with an assumed entropy factor of 1 bit of entropy per 20 bits of data.

These definitions in `include/crypto/rand_pool.h` make ample space for even that lousy gatherer:

https://github.com/openssl/openssl/blob/2b8d81534479b161dda063477272363fb2caef08/include/crypto/rand_pool.h#L17-L41

However, `ossl_rand_pool_new()` allows a *smaller* customized max length, and it seems that at least some calls assume a much better entropy factor, and that's what causes this failure.

Not really sure what's the right thing to do with this.

**Comment by levitte** [comment]
It turns out that it's pretty easy to simulate this sort of failure on Unix too:

``` diff
diff --git a/providers/implementations/rands/seeding/rand_unix.c b/providers/implementations/rands/seeding/rand_unix.c
index 9a936d800d..8fae3a0621 100644
--- a/providers/implementations/rands/seeding/rand_unix.c
+++ b/providers/implementations/rands/seeding/rand_unix.c
@@ -641,7 +641,7 @@ size_t ossl_pool_acquire_entropy(RAND_POOL *pool)
         /* Maximum allowed number of consecutive unsuccessful attempts */
         int attempts = 3;
 
-        bytes_needed = ossl_rand_pool_bytes_needed(pool, 1 /*entropy_factor*/);
+        bytes_needed = ossl_rand_pool_bytes_needed(pool, 2 /*entropy_factor*/);
         while (bytes_needed != 0 && attempts-- > 0) {
             buffer = ossl_rand_pool_add_begin(pool, bytes_needed);
             bytes = syscall_random(buffer, bytes_needed);
```

I'm going to guess that this means that the other vOS gatherer may fail this test as well, 'cause:

https://github.com/openssl/openssl/blob/636ee1d0b864f29a70573a4894958958e940c01e/providers/implementations/rands/seeding/rand_unix.c#L155

**Comment by paulidale** [comment]
There are implicit assumptions that the entropy being grabbed is full strength (i.e. 8 bits per byte).
I've been aware of this for a while now and wondered when we'd hit it.

Time to think...

**Comment by paulidale** [comment]
The underlying assumption is the generate call which is assuming 8 bits per byte of entropy gets produced.  The seed source doesn't achieve this on all platform so the call fails due to insufficient space.

**Comment by slontis** [comment]
FYI @mspncp

**Comment by mspncp** [comment]
I might have found a more satisfying solution to the problem. Working on a patch...

**Comment by mspncp** [comment]
See #22394
