### ISSUE TITLE
PEM_read_PUBKEY does memory corruption on malformed input - security issue?

### ISSUE THREAD

**Issue by dierberg** [openssl/openssl#22349]
Hello openssl devs,

I amusing PEM_read_PUBKEY to read following PEM from file:

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqIBCgKCAQEA17SFrRcnYAjmxioP28zrouMe+CN0oQIDAQAB
-----END PUBLIC KEY-----

The content is invalid - I know, but after that, memory in program code is corrupted. Functions they usually work fine does:

(process:12463): libsoup-CRITICAL **: 07:05:00.453: soup_connection_get_ever_used: assertion 'SOUP_IS_CONNECTION (conn)' failed
(process:12463): libsoup-WARNING **: 07:05:06.026: (../libsoup-2.74.2/libsoup/soup-session.c:2023):soup_session_process_queue_item: runtime check failed: (item->new_api)

Any recommendations? Help would be appreciated. 

Thanks in advance - Sascha

**Comment by t8m** [comment]
Could you please specify the openssl version? Also could you please show us the part of the code that calls the PEM_read_PUBKEY() function? There might be some bug in the invocation.

**Comment by dierberg** [comment]
We use the current Yocto Kirkstone version which is 3.0.8

The code works fine when the PEM file is not manipulated:

`static EVP_PKEY* readPublicRSA(const char* kid)
{
	FILE* file;
	char* name = g_strdup_printf("/etc/keycloak/%s.pem", kid);
	if (NULL == (file = fopen(name, "rb")))
	{
		DRHIP_TRACE(trcHera, TRACE_SERVER, DRHIP_WARNING, "%s: cant open file: '%s'", __func__, name);
		g_free(name);
		return NULL;
	}
	EVP_PKEY *publicRSA = PEM_read_PUBKEY(file, NULL, NULL, NULL);
	fclose(file);
	g_free(name);
	return publicRSA;
}`

**Comment by t8m** [comment]
OK, so the returned value will be NULL in this case (or isn't it?)

What does the code that calls readPublicRSA() do with the returned EVP_PKEY ?

**Comment by vdukhovni** [comment]
This call sequence with the given input file does not result in any problem reports from `valgrind`. Seek the problem in your application code.

The stand-alone program:
```c
#include <stdio.h>
#include <openssl/evp.h>
#include <openssl/pem.h>

int main()
{
    char* name = "/tmp/truncated-pubkey.pem";
    FILE* file;
    EVP_PKEY *publicRSA;

    if (NULL == (file = fopen(name, "rb")))
    {
        return 1;
    }

    publicRSA = PEM_read_PUBKEY(file, NULL, NULL, NULL);
    EVP_PKEY_free(publicRSA);
    fclose(file);

    return 0;
}
```

The input file: `/tmp/truncated-pubkey.pem`
```pem
----BEGIN PUBLIC KEY-----
MIIBIjANBgkqIBCgKCAQEA17SFrRcnYAjmxioP28zrouMe+CN0oQIDAQAB
-----END PUBLIC KEY-----
```

Valgrind output:
```
==4710== Memcheck, a memory error detector
==4710== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==4710== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==4710== Command: ./repro
==4710== 
==4710== 
==4710== HEAP SUMMARY:
==4710==     in use at exit: 1,247 bytes in 5 blocks
==4710==   total heap usage: 2,484 allocs, 2,479 frees, 98,644 bytes allocated
==4710== 
==4710== LEAK SUMMARY:
==4710==    definitely lost: 0 bytes in 0 blocks
==4710==    indirectly lost: 0 bytes in 0 blocks
==4710==      possibly lost: 0 bytes in 0 blocks
==4710==    still reachable: 1,247 bytes in 5 blocks
==4710==         suppressed: 0 bytes in 0 blocks
==4710== Rerun with --leak-check=full to see details of leaked memory
==4710== 
==4710== For lists of detected and suppressed errors, rerun with: -s
==4710== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
