### ISSUE TITLE
Intermittent failure of quic_multistream_test on Windows and MacOS

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#22348]
This is a new QUIC CI failure as of today:

https://github.com/openssl/openssl/actions/runs/6480442670/job/17595984416

**Comment by mattcaswell** [comment]
> ERROR: (uint64_t) 'error_code == cc_info.error_code' failed @ ..\test\quic_multistream_test.c:1643
> # [5] compared to [10]

The test expects `QUIC_ERR_STREAM_STATE_ERROR` (5), but we seem to get `QUIC_ERR_PROTOCOL_VIOLATION` (10)

**Comment by t8m** [comment]
Another instance of the same failure happening on MacOS https://github.com/openssl/openssl/actions/runs/6602304852/job/17942081332

**Comment by rsbeckerca** [comment]
Just to add to this, both NonStop x86 and ia64 platforms hang in this test when using SPT threads (not helpful, the process is waiting to receive a message, from this trace:
```
Procedure call trace:
  AsmBreakDispatchNoRelink + 0x10 (Milli)
  $n_NSK_Event_Wait + 0x140 (Milli)
  Timer_WaitOnEmbeddedTLE_ + 0xA0 (SLr)
  PROCESS_WAIT_ + 0x80 (SLr)
  AWAITIOX + 0x1C60 (SLr)
  FILE_COMPLETE_ + 0x790 (SLr)
  $n_EnterPriv + 0x280 (Milli)
  cma__io_available + 0x1C0 (DLL zsptdll)
  cma___null_thread + 0x100 (DLL zsptdll)
  cma__thread_base + 0x200 (DLL zsptdll)
  GTHREAD_START_ + 0xD0 (SLr)
```
There is an error `EWOULDBLOCK` on the AF_INET TCP socket in this test. I'm not at all certain why a AF_INET socket is being used. We have access to PRNGD with AF_UNIX.

**Comment by hlandau** [comment]
This should be fixed by #22578.

**Comment by rsbeckerca** [comment]
> This should be fixed by #22578.

Will hold off on my other issue in hope. Thanks.

**Comment by mattcaswell** [comment]
> On 3.2.0-beta1, to add to this, both NonStop x86 and ia64 platforms hang in this test when using SPT threads (not helpful, the process is waiting to receive a message, from this trace. We did not see this with alpha2.

This sounds like a completely different issue. @rsbeckerca - can you raise a new issue for this?

**Comment by rsbeckerca** [comment]
> > On 3.2.0-beta1, to add to this, both NonStop x86 and ia64 platforms hang in this test when using SPT threads (not helpful, the process is waiting to receive a message, from this trace. We did not see this with alpha2.
> 
> This sounds like a completely different issue. @rsbeckerca - can you raise a new issue for this?

@mattcaswell Opened as #22588
