### ISSUE TITLE
use ECDSA, e.g., if it's all we have

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2237]
From @vdukhovni in the thread on #1597 

we must not fail to use an ECDSA certificate (supposing it is the only one we have) even if we share no curves with the client. That's a more complex fix, since it will likely require a second pass over the shared ciphersuites with a less stringent filter. I'd suggest a separate PR for that. This is also needed for supported signature algorithms (SHA1 cert when client only offers SHA256, ...)

**Comment by richsalz** [comment]
We will not delay 1.1.1 for this.

**Comment by vdukhovni** [comment]
A simple short-term fix is possible.  If we have exactly one certificate, then don't check its conformance with client's "supported <mumble>" extensions. Provided the leaf public is acceptable, proceed with the handshake. This will cover the vast majority of cases. In most of the other cases we'll have a vanilla RSA cert and an ECDSA cert, and the vanilla RSA cert will be fine.

**Comment by richsalz** [comment]
If @vdukhovni cares, he can re-open this. Apparently it's a nice-to-have more than a real requirement (and the upcoming PQ world, and @davidben's keyshare prediction draft, probably changes things), so I'm closing this.
