### ISSUE TITLE
call to function property_hash through pointer to incorrect function type

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#22375]
An ubsan build is generating this for me:
```
crypto/lhash/lhash.c:291:12: runtime error: call to function property_hash through pointer to incorrect function type 'unsigned long (*)(const void *)'
openssl/crypto/property/property_string.c:51: note: property_hash defined here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior crypto/lhash/lhash.c:291:12 in 
```

**Comment by levitte** [comment]
https://github.com/openssl/openssl/blob/eaee1765a49c6a8ba728e3e2d18bb67bff8aaa55/crypto/lhash/lhash.c#L291

That was weirdly written...  why not just this:

``` C
    hash = lh->hash(data);
```

**Comment by nhorman** [comment]
Its been that way since the initial import of SSLeay to the git tree, but yes, it definately looks, at least odd.  I changed this in the conversion I'm doing of the hash tables to be lh->hash(data), and it works fine

**Comment by kroeckx** [comment]
I would like to point out that this is preventing fuzzing with ubsan, since everything seems to be using this.

**Comment by thesamesam** [comment]
FWIW, we can disable this specific class of error but I think that's unwise.

**Comment by t8m** [comment]
Do I understand it right that a cast does not help here and that we would have to change the type of the first argument of `lh_*_new()` functions to be `unsigned long (*)(const void *)` and change all the callers?

That is bad.

Surprisingly there are the DECLARE_LHASH_HASH_FN() and IMPLEMENT_LHASH_HASH_FN() which were supposed to overcome this problem, but they are not used (except for one thing in apps.c).

**Comment by t8m** [comment]
I am afraid we'll have to disable this error class.

**Comment by kroeckx** [comment]
So your recommendation is to ignore undefined behaviour?

Do we plan to fix it at some later point?

**Comment by thesamesam** [comment]
See http://maskray.me/blog/2022-12-18-control-flow-integrity#fsanitizefunction (cc @maskray). This will mean OpenSSL is incompatible with CFI which is an important security mitigation.

**Comment by t8m** [comment]
I assume we can do something.

We can add:
```
    static ossl_unused ossl_inline LHASH_OF(type) * \
    lh_##type##_new_ex(OPENSSL_LH_HASHFUNC hfn, \
                    OPENSSL_LH_COMPFUNC cfn) \
    { \
        return (LHASH_OF(type) *) \
            OPENSSL_LH_new(hfn, cfn); \
    } \
```
And use the _ex function throughout. And for the hashfunc and compfunc type safety we can use the IMPLEMENT_LHASH_HASH_FN() IMPLEMENT_LHASH_COMP_FN() macros over the existing hash and comp functions.

**Comment by t8m** [comment]
However I do not think this would be for backporting to stable branches -> master branch only.

**Comment by davidben** [comment]
See for some links to how we avoid this class of UB in BoringSSL. It's pretty annoying, but doable. https://github.com/openssl/openssl/issues/22896#issuecomment-1834579201

**Comment by t8m** [comment]
Duplicate of #22896
