### ISSUE TITLE
error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’

### ISSUE THREAD

**Issue by whxloveyrh** [openssl/openssl#2239]
/root/truffleHog/ettercap/src/ec_sslwrap.c: In function ‘sslw_create_selfsigned’:
/root/truffleHog/ettercap/src/ec_sslwrap.c:978:13: error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’
          ext->value->data[7] = 0xe7;
             ^
src/CMakeFiles/lib_ettercap.dir/build.make:1142: recipe for target 'src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o' failed
make[2]: *** [src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o] Error 1
CMakeFiles/Makefile2:337: recipe for target 'src/CMakeFiles/lib_ettercap.dir/all' failed
make[1]: *** [src/CMakeFiles/lib_ettercap.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@ubuntu:build# 

note that:
my operating system  is ubuntu 16.04

**Comment by levitte** [comment]
Against what OpenSSL version?  Ubuntu 16.04 carries 1.0.2g by default, and you should get your issue with that version.

If you're building against OpenSSL 1.1.0 (regardless of letter release), then X509_EXTENSION has become opaque and you must use available accessor functions to create and use them.

**Comment by mattcaswell** [comment]
Question was answered. Closing.
