### ISSUE TITLE
FTBFS with no-ec in 1.0.2

### ISSUE THREAD

**Issue by sbyx** [openssl/openssl#224]
Since 1.0.2 openssl fails to build with no-ec due to an unconditional include of ec.h in ssl/t1_lib.c

Offending line: https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/t1_lib.c#L117

Example fix: https://dev.openwrt.org/browser/trunk/package/libs/openssl/patches/220-fix-no-ec-build.patch

**Comment by mattcaswell** [comment]
Fixed in b5dc90121. Thanks.
