### ISSUE TITLE
BIO* pub = BIO_new(BIO_s_mem()); is failing in openssl 3.0 it worked fine with openssl 1.0.2zg

### ISSUE THREAD

**Issue by aniljadaun** [openssl/openssl#22409]
Hi 

BIO* pub = BIO_new(BIO_s_mem()); is not allocating any memory and ERR_print_errors_fp doesn't log any error . Can you please help me in getting this issue diagnosed ? i am using openssl 3.1 with inbuilt legacy module.

**Comment by mattcaswell** [comment]
So, by "is not allocating any memory", do you mean that the `BIO_new` call returns NULL? There aren't very many reasons that would occur without logging an error and none of them seem particularly likely!!
