### ISSUE TITLE
Intermittent quic_tserver_test timeout failure

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#22424]
This is a newly appearing intermittent CI failure:

https://github.com/openssl/openssl/actions/runs/6557674958/job/17809737418?pr=22408

**Comment by mattcaswell** [comment]
Maybe we should just try upping the timeout?

**Comment by hlandau** [comment]
> Maybe we should just try upping the timeout?

Ordinarily I wouldn't be too keen on that but if it's in non-caching that may actually be reasonable.

**Comment by arapov** [comment]
has been merged.
