### ISSUE TITLE
Custom IV length issues in authenticated encryption

### ISSUE THREAD

**Issue by kjackiewicz** [openssl/openssl#22469]
Hi,

I think I found few issues related to IVs of custom length in authenticated encryption:

### Order of GCM context initialization (legacy API)
When using legacy API to set the custom GCM IV length the proper order of context initialization is important. However, if a wrong order is used (as in the snippet below), the encryption and decryption succeeds, silently truncating the IV to the default length. I think that the encryption/decryption should fail in such case not to mislead the caller.
```
unsigned char key[32];
unsigned char iv[16];
EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
EVP_CIPHER *type = EVP_CIPHER_fetch(NULL, "aes-256-gcm", NULL);
EVP_CipherInit_ex(ctx, type, NULL, NULL, NULL, 1);
EVP_CipherInit_ex(ctx, NULL, NULL, key, iv, -1);
EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, sizeof(iv), NULL);
```
I prepared a test for it and a possible fix that forbids increasing the IV length after it has been set in the following PR: https://github.com/openssl/openssl/pull/22507
Perhaps the above logic should be even more strict.

### Custom GCM IV length (params API)
I also checked how it works with the current "params API". I took the code from /demos/cipher/aesgcm.c as an example. I was unable to properly decrypt it.

I prepared a test that encrypts data using the legacy API with 16B IV and decrypts it using params API and a possible fix that changes the internal order of context initialization in the following PR https://github.com/openssl/openssl/pull/22507

### Custom CCM IV length (params API)
I know that CCM also allows IV length to be customized so I decided to check it as well using /demos/cipher/aesccm.c as an example. In case of CCM I wasn't even able to properly initialize the context.

The test and two fixes similar to GCM are included in https://github.com/openssl/openssl/pull/22507

In all above cases I used the latest openssl from master branch. The tests that I provided fail without the fixes and pass after applying them. I tested it on Linux OS using:
```
./Configure --strict-warnings
make test
```

I suppose that beside fixing it, some changes in the /demos/ and documentation may be necessary. Perhaps some other encryption modes/ciphers that I'm unaware of are affected as well.

**Comment by t8m** [comment]
This should be fixed now. If there is anything remaining please open a new PR.
