### ISSUE TITLE
Crash if SSL *s equal to NULL is passed to SSL_ctrl()

### ISSUE THREAD

**Issue by nv-dmd** [openssl/openssl#22466]
OpenSSL 3.0, 3.1, master

If the first argument pointer SSL *s equal to NULL is passed to the function SSL_ctrl() then the application crashes with read access violation.

At the same time, the function SSL_CTX_ctrl() checks for such a case
```
    /* For some cases with ctx == NULL perform syntax checks */
    if (ctx == NULL) {
        switch (cmd) {
        case SSL_CTRL_SET_GROUPS_LIST:
            return tls1_set_groups_list(ctx, NULL, NULL, parg);
        case SSL_CTRL_SET_SIGALGS_LIST:
        case SSL_CTRL_SET_CLIENT_SIGALGS_LIST:
            return tls1_set_sigalgs_list(NULL, parg, 0);
        default:
            return 0;
        }
    }
```
Maybe need to add a check SSL *s in SSL_ctrl() ?

**Comment by t8m** [comment]
Many API calls of OpenSSL do not check for NULL arguments where they obviously must be non-NULL for the functions to work.

**Comment by nv-dmd** [comment]
Oh, if you think that there is no problem in this case, then I don’t have to create the PR. That's why I asked the issue, to know your opinion.

**Comment by nv-dmd** [comment]
> Many API calls of OpenSSL do not check for NULL arguments where they obviously must be non-NULL for the functions to work.

Oh, if you think that there is no problem in this case, then I don’t have to create the PR. That's why I asked the issue, to know your opinion.
