### ISSUE TITLE
No check of the result of the EVP_PKEY_copy_parameters() function apps\ca.c

### ISSUE THREAD

**Issue by nv-dmd** [openssl/openssl#22471]
OpenSSL 3.0, 3.1, master

There is no check of the result of the EVP_PKEY_copy_parameters() function in apps\ca.с on line 1904, although in my opinion there should be one:

```
    pktmp = X509_get0_pubkey(ret);
    if (EVP_PKEY_missing_parameters(pktmp) &&
        !EVP_PKEY_missing_parameters(pkey))
        EVP_PKEY_copy_parameters(pktmp, pkey);
```
Maybe need to add a check of result the EVP_PKEY_copy_parameters()?

**Comment by t8m** [comment]
It might make sense to try to continue anyway. We at least have similar cases elsewhere.

**Comment by nv-dmd** [comment]
Oк. Thank you. Really, there is such a case. Then I close issue.

**Comment by nv-dmd** [comment]
Oк. Thank you. Really, there is such a case. Then I close issue.
