### ISSUE TITLE
build openssl for android refer a  "undefined referenc" eerror

### ISSUE THREAD

**Issue by chenTest2013** [openssl/openssl#2249]
I build openssl static library follow the openssl [wiki](https://wiki.openssl.org/index.php/Android) on my ubuntu PC(Linux ubuntu 4.4.0-60-generic 16.04 x86_64 x86_64 x86_64 GNU/Linux)
my build environment is as follows:
openssl-1.0.1g
ndk:android-ndk-r13b
android-api:android-21
android_arch=arch-arm
1:  ./config shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/usr/local/ssl/$ANDROID_API
this setp is ok
2:   make depend  this setp is ok
3: make all , 
dhparam.o:dhparam.c:function dhparam_main: error: undefined reference to 'setup_engine'

what can i do fix this problem? Thanks

**Comment by yan12125** [comment]
Could you paste all commands you've entered? Include ```export XYZ=abc``` ones.

**Comment by mattcaswell** [comment]
No response from OP to above question. Closing.
