### ISSUE TITLE
QUIC client fuzzer hang

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#22530]
OSSfuzz have found a new hang in the QUIC client fuzzer. Fuzzer file attached.
[clusterfuzz-testcase-minimized-quic-client-6245605980372992.gz](https://github.com/openssl/openssl/files/13186096/clusterfuzz-testcase-minimized-quic-client-6245605980372992.gz)

**Comment by kroeckx** [comment]
It doesn't hang, it's just really slow.

**Comment by mattcaswell** [comment]
This is related to PING frames and congestion control again.

We have determined that we need to send a PING frame but congestion control is preventing us from doing so. So we keep going around in a loop trying to send one. Each time around we do update the ping_deadline - but we only increment it by 1ms. This is because the peer has told us to use a max_idle_timeout of 2ms:

https://github.com/openssl/openssl/blob/09298141592c579504966f1907a44cb95f37cc6e/ssl/quic/quic_channel.c#L3443-L3454

Because of the excessively small max_idle_timeout value you might expect that the very small increments in ping_deadline wouldn't matter because we would also close the connection due to an idle timeout very quickly. But actually we ignore excessively small idle timeouts requested by the peer:

https://github.com/openssl/openssl/blob/09298141592c579504966f1907a44cb95f37cc6e/ssl/quic/quic_channel.c#L3421-L3432

**Comment by hlandau** [comment]
Possible fix in #22533

**Comment by t8m** [comment]
Fix was merged.
