### ISSUE TITLE
More uniform treatment of stacks

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2254]
Currently, several OpenSSL functions return `NULL` to denote "empty stack". An example is `SSL_get_peer_cert_chain`.

Thus, when I want to make the certificate chain available to other parts of the application, I must do something like this (which is from an actual application I am maintaining):

<pre>
static int
unify_certificates_inorder(term_t certs, STACK_OF(X509)* stack)
{ term_t item = PL_new_term_ref();
  term_t list = PL_copy_term_ref(certs);
  STACK_OF(X509) *copy = <b>stack ? sk_X509_dup(stack) : NULL;</b>
  X509* cert = sk_X509_shift(copy);
  int retval = 1;

  while (cert != NULL && retval == 1)
  { retval &= PL_unify_list(list, item, list);
    retval &= unify_certificate(item, cert);
    cert = sk_X509_shift(copy);
  }
  sk_X509_free(copy);
  return retval && PL_unify_nil(list);
}
</pre>

Please note the anomalous case distinction between `NULL` and an "actual" stack. That is, I cannot simply write this as:

<pre>
  STACK_OF(X509) *copy = <b>sk_X509_dup(stack)</b>
</pre>

because `SSL_get_peer_cert_chain` might have returned `NULL`, leading to a crash.

One way to solve this was proposed in #2246 and rejected: Make `sk_TYPE_dup` simply return `NULL` when given `NULL`, in analogy to many other stack functions that currently do this.

The more useful alternative, in my opinion, would be to return actual stacks in all situations, with the exceptions of errors, where `NULL` can be used to signal extraordinary circumstances.

If `SSL_get_peer_cert_chain` worked like this, then code like shown above need not distinguish between zero and any other number of elements in the stack, which I think would be more convenient and less error-prone.

**Comment by levitte** [comment]
I started looking at the functions we have that return a stack of stuff, and I realise that this needs to be treated carefully, as a returned NULL can be seen as an error condition, and therefore needs to be checked by the caller directly after calling the stack-fetching function.

In the general and ideal case, one could also question why functions like `unify_certificates_inorder` are called with a NULL stack if that's regarded as an error, and why that didn't cause some kind of error return or exception earlier in the calling code.  However, to ensure that a NULL stack can be treated as an error, we must make sure that a returned NULL stack is an error at all times.

This is, btw, quite a bit of work.  I've just started...

**Comment by triska** [comment]
In my application, it is not an error if the transmitted certificate chain is empty. In that case, (it is a Prolog application), the certificate chain is represented as the **empty list** in Prolog, i.e.,&nbsp;`[]`. This simply means that the peer has not provided any certificates. Whether that's OK is for the user-level application to decide, which is called within Prolog with appropriate&nbsp;hooks.

In my application, `unify_certificates_inorder` is called like this:

<pre>
  return unify_certificates_inorder(chain,
                                    <b>SSL_get_peer_cert_chain(instance->ssl)</b>);
</pre>

So, it simply and directly uses the result of `SSL_get_peer_cert_chain`, which returns `NULL` to mean "empty list", and in that case I *must&nbsp;not* use `sk_X509_dup`, because that will invariably lead to a&nbsp;crash!

There are other cases like this too in my application, where I simply take a stack of certificates (or CRLs), and ideally do not want any case distinction whether there are 0, 1, or 50 elements in the stack. Often in such cases, the stack is directly passed onto the Prolog layer for further inspection, and there again, whether there are zero, or two or five certificates typically does not need any case distinction, because I simply store, analyze or use such elements in many ways, no matter how many of them there&nbsp;are.

**Comment by levitte** [comment]
Hmmm...  I've just looked at the code that sets the peer cert chain, both in server and client mode, and as far as I can read the code, *they both get an appropriate stack (possibly empty) when receiving the peer certificates*.  So the question is, are you trying to fetch the peer cert chain before those have been passed in the SSL handshake?  I would regard that as an error, and in that case, a NULL return from `SSL_get_peer_cert_chain()` is perfectly appropriate.

If you're getting a NULL from `SSL_get_peer_cert_chain()` after the peer chain has been received, then there are reasons to have a look at the code that sets the peer chain.  In 1.0.2, that happens in the functions `ssl3_get_client_certificate` and `ssl3_get_server_certificate`.  In master and 1.1.0, that happens in the functions `tls_process_client_certificate` and `tls_process_server_certificate`.  Note that those functions might not set the peer chain if they encountered some error, which might also get you a NULL when you call `SSL_get_peer_cert_chain()`.

**Comment by vdukhovni** [comment]
Note that the chain will always be uninitialized when a session is resumed, an aNULL ciphersuite is negotiated, or a client presents no certificate (server-side optional client cert).

**Comment by levitte** [comment]
> or a client presents no certificate (server-side optional client cert).

Ah, good point, I missed that detail.  That gets us back to the earlier complaint, that `peer_chain` (or `cert_chain` in 1.0.2) probably should be initialised with an empty stack rather than just NULL.

**Comment by levitte** [comment]
#2256 should address the key issue here.  I'm not entirely sure if this is appropriate, or if a NULL stack from `SSL_get_peer_cert_chain()` should simply be regarded as an error to be checked as such by the calling application.

**Comment by mattcaswell** [comment]
Linked PR is set on hold and for 1.2.0. Setting milestone accordingly.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by triska** [comment]
I am closing this issue since I no longer care about this library. Thank you a lot!
