### ISSUE TITLE
HTTPS(TLS 1.2/1.3) performance of openresty drop about 50% when switch openssl form 1.1.1 to 3.0.11

### ISSUE THREAD

**Issue by yfaker** [openssl/openssl#22560]
Openresty version: 1.21.4.2， work as a Layer 7 reverse proxy 
openssl version: 3.0.11
CPU info: Intel(R) Xeon(R) Platinum 8378A CPU @ 3.00GHz   32 Cores
Test mode:               
                HTTP2(TLS1.2/1.3)                            HTTP/1.1(TLS1.2) 
Client        <----------->              Openresty      <----------->            Content Server 

We tested downloading 2B size file and the CPS dropped from 22600 to 10900, nearly 51%  degredation 

As openssl 1.1.1 is out of support , is there any solution to fix the performace issue in openssl 3.x?

Thanks

**Comment by nhorman** [comment]
possibly, but we're going to need something to understand where the slowdown is.  Can you provide performance profiling data of any kind?  a perf report from the machine in question would be a good start.

Also, is it possible to test with 3.1 (or better 3.2 beta)?  There have been several performance improvements made in those releases.

**Comment by tom-cosgrove-arm** [comment]
@openssl/otc Since performance of the 3.x series is a concern, and there are several issues about it, would it make sense to create a `performance` label to tag issues about it (and PRs that address it)?

**Comment by nhorman** [comment]
I'd support such a label

**Comment by paulidale** [comment]
@tom-cosgrove-arm, #17627 was created to track performance issues.  It's not been maintained.

**Comment by tom-cosgrove-arm** [comment]
That's why I wonder about a label - much easier to add where necessary, when other labelling is being done

**Comment by t8m** [comment]
It should be a `triaged: performance` label. :grin: but I support it.

**Comment by mspncp** [comment]
Creating separate labels for different bug flavors just causes a label inflation which devaluates the labels (to stay within the metaphor) and makes them less useful. Creating a dedicated tracking issue which summarizes related issues and links to them would be more helpful in such cases imo.

**Comment by t8m** [comment]
@mspncp except the performance fixes are explicitly not treated as bug fixes in many cases. And although I agree we should not create new labels lightly, this one IMO deserves it.

**Comment by mspncp** [comment]
I very much prefer `triaged: performance` over `performance`.

**Comment by mspncp** [comment]
It fits in the general scheme.

**Comment by mspncp** [comment]
> It should be a `triaged: performance` label. :grin: but I support it.

(our posts crossed)

**Comment by tom-cosgrove-arm** [comment]
I've created such a label. We can always delete it if other people disagree. The intent is that it is for performance issues/concerns/regressions, not to be applied to code optimisations (such as assembler implementations of crypto algorithms)

**Comment by t8m** [comment]
> The intent is that it is for performance issues/concerns/regressions, not to be applied to code optimisations (such as assembler implementations of crypto algorithms)

This is debatable. I would actually apply it to all changes that improve performance but otherwise do not introduce any new feature - i.e. not to a new optional TLS feature from some RFC that also improves performance. But IMO assembler optimizations should have this label as well.

**Comment by tom-cosgrove-arm** [comment]
> IMO assembler optimizations should have this label as well.

I am happy with that if the group is

**Comment by nhorman** [comment]
Given that there has been no response to the initial question asking for details of the slowdown, I'm marking this as inactive for closure at the end of the 3.4 dev cycle
