### ISSUE TITLE
I am linking the 3.0.8 libraries to use it as crypto for kerberos installation

### ISSUE THREAD

**Issue by pekumar** [openssl/openssl#22565]
yes I am linking the 3.0.8 libraries to use it as crypto for kerberos installation 
here is the line where I am trying to use openssl 
&& ./configure --with-crypto-impl=openssl --with-prng-alg=os --localstatedir=/var/lib/ \

_Originally posted by @pekumar in https://github.com/openssl/openssl/discussions/22564#discussioncomment-7432963_

**Comment by pekumar** [comment]
can anyone please help me with the resolution of my issue.

**Comment by pekumar** [comment]
@tom-cosgrove-arm

**Comment by t8m** [comment]
Please do not open such duplicate issues.
