### ISSUE TITLE
Configure cannot detect gcc when the compiler's filename is `cc`

### ISSUE THREAD

**Issue by kyungminlee** [openssl/openssl#2258]
Currently `Configure` checks whether the compiler is `gcc` or `clang` to set `makedepprog` by calling the compiler with `--version` option. (https://github.com/openssl/openssl/blob/master/Configure#L1220)
However, when `gcc` is called through a symlink with another name, `/usr/bin/cc` for instance, it prints the name of the symlink, and not `gcc`.
Checking the predefined macros should be a better way IMO. A quick fix would be to use `cc -v` instead of `cc --version` and check the complete output (not just the first two lines).

**Comment by dot-asm** [comment]
This was effectively addressed in #4281.
