### ISSUE TITLE
OpenSSL 3.1.4 breaks make diff-fips-checksum

### ISSUE THREAD

**Issue by wbl** [openssl/openssl#22581]
It appears that exchange.c has changed. While this is itself fine, it's not clear to me why the checksums shouldn't also be updated: we FIPS certify releases right that appear in the security documentation, so I don't know why the checksums couldn't also be updated.

**Comment by t8m** [comment]
I do not see the change of exchange.c in 3.1.4 release.

This is `git log exchange.c` on the openssl-3.1 branch:
```

commit 1d6c45694a1ae4ac5f9aa8f76dc1de68089f8a72
Author: Pauli <pauli@openssl.org>
Date:   Thu Jul 14 15:17:41 2022 +1000

    evp: make all _is_a functions accept and handle a NULL argument
    
    Makes life easier for callers.
    
    Fixes Coverity 1503326
    
    Reviewed-by: Tomas Mraz <tomas@openssl.org>
    Reviewed-by: Dmitry Belyavskiy <beldmit@gmail.com>
    Reviewed-by: Hugo Landau <hlandau@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/18799)
    
    (cherry picked from commit ee8db8c5fb5b091f48d29914126d35a7e29cdcf2)

commit ee71383a8d35bebbd1debf366d9c9205a04e4993
Author: Matt Caswell <matt@openssl.org>
Date:   Tue Mar 15 13:52:58 2022 +0000

    Update copyright year
    
    Reviewed-by: Tomas Mraz <tomas@openssl.org>
    Reviewed-by: Matt Caswell <matt@openssl.org>

...
```

The last change done there went in 3.1.3 which has updated fips checksum for this source file.

**Comment by wbl** [comment]
Hmm. I'll poke around a bit more

**Comment by wbl** [comment]
Sorry guys, I had patched it locally to solve the quick_check for ephemeral keys issue, and forgot I did it.
