### ISSUE TITLE
openssl 3.x compilation errors with icx and nvc

### ISSUE THREAD

**Issue by AIIleG** [openssl/openssl#22594]
Hello,

openssl 3.0.12 and 3.1.4 fail to compile with icc (now oneapi) 2023 and pgi (now nvidia hpc) 23. both show the same error:

```
crypto/x86_64cpuid.s:492:31: error: expected string
        .section .note.gnu.property, #alloc
crypto/md5/md5-x86_64.s:684:31: error: expected string
        .section .note.gnu.property, #alloc
```

openssl 1.1.1w works fine.

**Comment by nhorman** [comment]
I don't believe icc or pgi are officially supported, though generally speaking icc _should_ work as it tries to be largely compatible with gcc.  No idea about pgi though, not sure anyone has even tried that

looking at the 1.1.1w code, that .section directive is unchanged between the two releases

when you built 1.1.1w were you using the new icx compiler from intel, or were you using the classic icc compiler toolchain?

**Comment by nhorman** [comment]
I think icx and nvc are both forks of llvm, so I wouldn't be too surprised if they behaved similarly.

Unfortunately, Neither the icx or nvc manuals provide significant detail as to how they handle .section directives, so I'm not sure we will be able to help you much here.  I think your best course of action will be to raise an issue with either nvidia or intel (possibly both), to get their input on what might be going wrong here.

**Comment by t8m** [comment]
But clang works fine as we run it all the time in CI.

**Comment by t8m** [comment]
Could you please paste here output of `./configdata.pm -d` for both cases?

**Comment by nhorman** [comment]
I suppose you could try building with asm disabled as a temporary workaround, but that I think is just going to hide the issue, as it just won't build the affected files.

**Comment by nhorman** [comment]
As I mentioned above, The only thing in the configs that I see as noteworthy is the enabling of the asm feature, and while disabling that would be a potential workaround, it doesn't really address the compiler issue.

FWIW:
1) I downloaded the oneapi basekit container, and managed to get a successful build by configuring with no-asm.  Its a workaround, but it doesn't address the issue
2) I played with it for a bit, and it appears that in the .section declaration, replacing the #alloc parameter with an actual corresponding string "a" fixes the issue

That said, T[he gnu assembler manual ](https://ftp.gnu.org/old-gnu/Manuals/gas-2.9.1/html_node/as_117.html#SEC119), indicates support for using #alloc, #write, etc in the flags field instead of quoted strings.  It seems like nvc/icx declined/neglected to support those flags.  Thats likely what you need to report to the developers there.

**Comment by t8m** [comment]
Actually it seems to be pretty well fixable if we set `$gnuas` for these compilers. There is this detection currently:

```
# Find out if we're using GNU as
elsif (`$ENV{CC} -Wa,-v -c -o /dev/null -x assembler /dev/null 2>&1`
        =~ /GNU assembler version ([2-9]\.[0-9]+)/)
{
    $gnuas=1;
}
elsif (`$ENV{CC} --version 2>/dev/null`
        =~ /clang .*/)
{
    $gnuas=1;
}
```

This could be expanded appropriately.

**Comment by nhorman** [comment]
Interestingly icx doesn't seem to support that detection:
```
root@bb967f8769e8:/# icx  -Wa,-v -c -o /dev/null -x assembler /dev/null 2>&1
icx: error: unsupported argument '-v' to option '-Wa,'
```

The oneAPI compiler does report a specific version:
```
root@bb967f8769e8:/# icx --version
Intel(R) oneAPI DPC++/C++ Compiler 2023.2.0 (2023.2.0.20230721)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2023.2.1/linux/bin-llvm
Configuration file: /opt/intel/oneapi/compiler/2023.2.1/linux/bin-llvm/../bin/icx.cfg
```

That we could use to disable gnuas, but then we would have to use that to create a define that we can ifdef our way around in the asm code.  Do we want to do that without setting up ci to more completely support the compiler?  Theres also nvc to consider here (haven't checked that behavior yet)

**Comment by t8m** [comment]
> Interestingly icx doesn't seem to support that detection:
> 
> ```
> root@bb967f8769e8:/# icx  -Wa,-v -c -o /dev/null -x assembler /dev/null 2>&1
> icx: error: unsupported argument '-v' to option '-Wa,'
> ```
> 
> The oneAPI compiler does report a specific version:
> 
> ```
> root@bb967f8769e8:/# icx --version
> Intel(R) oneAPI DPC++/C++ Compiler 2023.2.0 (2023.2.0.20230721)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /opt/intel/oneapi/compiler/2023.2.1/linux/bin-llvm
> Configuration file: /opt/intel/oneapi/compiler/2023.2.1/linux/bin-llvm/../bin/icx.cfg
> ```
> 
> That we could use to disable gnuas, but then we would have to use that to create a define that we can ifdef our way around in the asm code. Do we want to do that without setting up ci to more completely support the compiler? Theres also nvc to consider here (haven't checked that behavior yet)

I assume as they are llvm based, this is just a matter of making them to use the `$gnuas = 1;`. I do not think there would be any further changes needed.

This is supported by the patches posted by @AIIleG above.

**Comment by t8m** [comment]
I have this on mind:

```diff
diff --git a/crypto/perlasm/x86_64-xlate.pl b/crypto/perlasm/x86_64-xlate.pl
index 359670a2da..6b93cfb84f 100755
--- a/crypto/perlasm/x86_64-xlate.pl
+++ b/crypto/perlasm/x86_64-xlate.pl
@@ -111,7 +111,12 @@ elsif (`$ENV{CC} -Wa,-v -c -o /dev/null -x assembler /dev/null 2>&1`
     $gnuas=1;
 }
 elsif (`$ENV{CC} --version 2>/dev/null`
-               =~ /clang .*/)
+               =~ /(clang .*|Intel.*oneAPI .*)/)
+{
+    $gnuas=1;
+}
+elsif (`$ENV{CC} -V 2>/dev/null`
+               =~ /nvc .*/)
 {
     $gnuas=1;
 }
```

@AIIleG could you please try this instead of your patch?

**Comment by t8m** [comment]
[x86_64-xlate.patch.txt](https://github.com/openssl/openssl/files/13318180/x86_64-xlate.patch.txt)

Please try this
