### ISSUE TITLE
Same Issuer/Subject between multiple client certificates

### ISSUE THREAD

**Issue by ApoorvaShetty16** [openssl/openssl#22591]
Scenario:
Two clients have independently created self-signed certificates for SSL/TLS communication. These certificates share identical information in their "Subject" and "Issuer" fields. Both client certificates are getting added into the server's truststore. However, when attempting to establish an SSL connection, the server is able to accept first connection from client and other client connection attempt fails with 'self signed certificate error'.

Client-1 cert :

Certificate:
...
Issuer: C=US, ST=California, L=Palo Alto, O=xyz, Inc./emailAddress=[client@xyz.com](mailto:client@xyz.com), CN=abc
Subject: C=US, ST=California, L=Palo Alto, O=xyz, Inc./emailAddress=[ssl-certificates@xyz.com](mailto:ssl-certificates@xyz.com), CN=abc
...

Client-2 cert:

Certificate:
...
Issuer: C=US, ST=California, L=Palo Alto, O=xyz, Inc./emailAddress=[client@xyz.com](mailto:client@xyz.com), CN=abc
Subject: C=US, ST=California, L=Palo Alto, O=xyz, Inc./emailAddress=[ssl-certificates@xyz.com](mailto:ssl-certificates@xyz.com), CN=abc
...

Question:
-Is Same Issuer/Subject the reason for failure here? Is it mandatory to have clients with unique "Issuer" and "Subject" fields in this context ?

-What parameters will be considered while verifying the certificates?

**Comment by t8m** [comment]
Please do not create duplicate issues. This is already filed in as https://github.com/openssl/openssl/discussions/22582
