### ISSUE TITLE
Windows MSYS mingw can't build openssl 1.0.2 

### ISSUE THREAD

**Issue by talshadow** [openssl/openssl#226]
forom msys console i run
perl Configure mingw 
after finish i run make and have error

$ make
making all in crypto...
mingw32-make[1]: Entering directory 'c:/worktools/build/openssl-1.0.2/crypto'
C:/worktools/msys/bin/perl.exe ../util/mkbuildinf.pl "gcc -I. -I./.. -I../include  -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -fomit-f
rame-pointer -O3 -march=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_
ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM" "mingw" >buildinf.h
g++ -m32 -march=i686 -mtune=core2 -mcx16 -msahf -mfpmath=sse -mstackrealign -mmmx -msse -msse2 -mms-bitfields -O2 -fms-extensions -fomit-frame-pointer -Wall -fu
nswitch-loops -fpredictive-commoning -ftree-vectorize -fvect-cost-model -fgcse-after-reload -ftree-loop-vectorize -ftree-slp-vectorize  -fvisibility-ms-compat -
ftemplate-depth-256 -std=gnu++11   -c -o cryptlib.o cryptlib.c
In file included from cryptlib.c:117:0:
cryptlib.h:65:19: fatal error: e_os.h: No such file or directory
 # include "e_os.h"
                   ^
compilation terminated.
<builtin>: recipe for target 'cryptlib.o' failed
mingw32-make[1]: *** [cryptlib.o] Error 1
mingw32-make[1]: Leaving directory 'c:/worktools/build/openssl-1.0.2/crypto'
make: *** [build_crypto] Error 1

if i copy e_os.h from parent directory - this not fix error - i have some alse errors

cryptlib.c:170:3: error: #error "Inconsistency between crypto.h and cryptlib.c"
 # error "Inconsistency between crypto.h and cryptlib.c"
   ^
cryptlib.c:172:1: error: too many initializers for 'const char* const [36]'
 };

**Comment by talshadow** [comment]
Remove old version before build - and starting compile

**Comment by White-Tiger** [comment]
not sure what you mean by "Remove old version before build" as I also got this kind of error...
I've just downloaded OpenSSL and tried to build it, so there shouldn't be any "old version".
Also, my command line looks a bit differently... 
```
g++    -c -o cryptlib.o cryptlib.c
In file included from cryptlib.c:117:0:
cryptlib.h:65:19: fatal error: e_os.h: No such file or directory
 # include "e_os.h"
                   ^
```

I've tried to follow this howto: http://qt-project.org/wiki/Compiling-OpenSSL-with-MinGW
as well as INSTALL.W32 (INSTALL.W64 is outdated, I actually want to compile for x86_64 but I can do neither)

**Comment by lilianmoraru** [comment]
I confirm the issue with 1.0.2a.
I tried to compile on a clean machine...
I did ```mingw32-make clean``` and then ```./Configure mingw no-idea no-mdc2 no-rc5 shared``` after which ```mingw32-make depend```.

```cryptlib.c:170:3: error: #error "Inconsistency between crypto.h and cryptlib.c"
 # error "Inconsistency between crypto.h and cryptlib.c"
   ^
uid.c:77:11: error: #include expects "FILENAME" or <FILENAME>
 # include OPENSSL_UNISTD```

**Comment by Ri0n** [comment]
The problem is in implicit make rules.

I don't know why gnumake decided to use g++ instead of gcc but by the same reason it does not use declared CFLAGS what leads to the lost e_os.h header.
It seems there are no way o force gcc but explicit make rule. So in my case I've added next code to crypto/Makefile
<pre>
%.o:	%.c
	$(CC) $(CFLAGS) -c -o $@ $<
</pre>
and it compiled a little more.

Unfortunately all other makefiles do not have such explicit rule too.

**Comment by c-sonntag** [comment]
Hey !
With MSYS2 it's work !
Maybe you try this simple script to build : 
`#! /bin/bash

# Free script to build openssl
# Author : Christophe Sonntag (https://github.com/c-sonntag)


# Add MINGW to path if is not set
export PATH=${PATH}:/r/my-mingw-folder/bin

# Set the system for the ./config script, 
# use "mingw64" for x64 build
export SYSTEM="mingw"

# Go in openssl folder
cd my-openssl-path

# Clean Build
make clean
if [ $? -eq 0 ]; then echo "OK : make clean"; else echo "FAIL : make clean"; exit;  fi

# Configure Build 
./config --prefix=$(pwd)/builds/mingw no-idea no-mdc2 no-rc5 shared
if [ $? -eq 0 ]; then echo "OK : ./config"; else echo "FAIL : ./config"; exit;  fi

# Check depend
make depend
if [ $? -eq 0 ]; then echo "OK : make depend"; else echo "FAIL : make depend"; exit;  fi

# Build with 8 jobs
make -j8
if [ $? -eq 0 ]; then echo "OK : make -j8"; else echo "FAIL : make -j8"; exit;  fi

# Install to prefix
make install_sw
if [ $? -eq 0 ]; then echo "OK : make install_sw"; else echo "FAIL : make install_sw"; exit;  fi
`
