### ISSUE TITLE
quic-client fuzzer crash

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#22607]
Running with the code from #22592, with this file:
[crash-a194cdde40cabb7116f839e39810ec5e95597fd8.gz](https://github.com/openssl/openssl/files/13248688/crash-a194cdde40cabb7116f839e39810ec5e95597fd8.gz)

I got:
ssl/quic/quic_txp.c:294: OpenSSL internal error: Assertion failed: !h->done_implicit

**Comment by mattcaswell** [comment]
Fix in #22611

**Comment by t8m** [comment]
This was fixed by merging #22615
