### ISSUE TITLE
Performance measuring framework/numbers for master vs 3.0?

### ISSUE THREAD

**Issue by wbl** [openssl/openssl#22604]
Is the performance measurement framework for whole handshakes that got the results previewed at the OMC meeting going to be available/numbers?

This would be helpful for planning what releases to follow and what the impact of performance improving patches is. Right now we have to make up our own which doesn't help us know if we're going to regress others if they get upstreamed or get the same numbers for everyone.

**Comment by mattcaswell** [comment]
> Is the performance measurement framework for whole handshakes that got the results previewed at the OMC meeting going to be available/numbers?

Thanks for the ping. We should make that public - but not too sure its currently working. Will investigate.

**Comment by arapov** [comment]
Make grafana performance dashboards open to public.

**Comment by slontis** [comment]
Is this item still on the backlog?, so hopefully at some point more graphs can be added? This would be important for the performance items that are on the Working Group backlog.

**Comment by mattcaswell** [comment]
Yes - it is in the backlog.

The framework already exists and is running and the graphs are generated, but its not publicly accessible at the moment. Also one of the graphs looks broken (the 1.1.1 performance numbers are terrible, which we know not to be correct). The work required is to figure out what happened to the 1.1.1 performance numbers, make the graphs public and add the ability to easily extend this.
