### ISSUE TITLE
Creating certificate using openssl in ubuntu os

### ISSUE THREAD

**Issue by june8070** [openssl/openssl#2262]
i have to generate a digital certificate for any server lets say pkilabsever.com using the CA
I have a directory build with the following subdirectories
home/
demoCA/
certs
crl
index.txt
newcerts
openssl.cnf
serial
the problem is when i generate certificate using the following command ...

ghazal@ghazal-VirtualBox:/demoCA$ openssl ca -in server.csr -out server.crt -cert ca.crt -keyfile ca.key -config openssl.cnf
Using configuration from openssl.cnf
Enter pass phrase for ca.key:
I am unable to access the ./demoCA/newcerts directory
./demoCA/newcerts: No such file or directory
ghazal@ghazal-VirtualBox:/demoCA$

it is unable to find the subdirectories....
any suggestions??

**Comment by levitte** [comment]
I'm sorry, this is more of a question for openssl-users@openssl.org.  See https://www.openssl.org/community/mailinglists.html for links to the subscription pages.

Closing here.

**Comment by june8070** [comment]
fazul
