### ISSUE TITLE
openssl rand - please allow to generate more than 2 GiB of data. 

### ISSUE THREAD

**Issue by jirka-h** [openssl/openssl#22622]
Hello,

could you please consider enhancing `openssl rand` to generate more than 2GiB of random data?

```
$openssl rand 2147483648
rand: Value "2147483648" outside integer range
rand: Use -help for summary.
```
The current limit of `2^31-1` Bytes seems to be arbitrary. For example, when preparing a hard-drive for the encryption, you need to fill the entire drive with random data first. Ideally, `openssl rand` should allow much higher limit, possibly 2^63-1 Bytes or even an endless stream of random data (for example when `openssl rand 0` is used). 

Thanks a lot!
Jirka

**Comment by nhorman** [comment]
https://github.com/openssl/openssl/pull/22624

It seems easy enough to do, but I'm not sure its the right thing to do for a few reasons:
1) 2^63-1 isn't any more or less arbitrary a limit on request size than 2^32-1
2) parsing 64 bit values requires the use of strtoll, which, while part of POSIX 2008, might not be supported on all platforms that openssl supports
3) The easy workaround in either case (including the unending case), is something of the form:
$(while true; do openssl rand <value>; done)

**Comment by mspncp** [comment]
Instead of just accepting larger integers on the command line, it would be more user friendly to introduce a new `size_t` valued command line argument type, which allows using the common size suffixes like `256k`, `30M`, or `8G`.

**Comment by nhorman** [comment]
@mspncp I could get behind that approach.

**Comment by mspncp** [comment]
Sure, go ahead :-)

**Comment by mspncp** [comment]
Note: I wouldn't care about the suffixes the [powers of 10](https://simple.wikipedia.org/wiki/Gibibyte), only about the [powers of two](https://simple.wikipedia.org/wiki/Gigabyte). Those can be implemented easily by bit-shifting combined with an overflow check.

**Comment by jirka-h** [comment]
+1 to support binary suffixes. This how coreutils handles it as well - see for example `man head` or source code here:
https://github.com/coreutils/coreutils/blob/56e9acb2927874770363462cc6f5d2ee7d2b4c6d/src/head.c#L910

Thank you!

**Comment by paulidale** [comment]
SP 800-90C limits DRBG output to 2⁶⁴ **bits** per instantiation.  That 2⁶¹ bytes.
There are reseed rules that kick in earlier but they are only reseedings & should be handled already.

**Comment by jirka-h** [comment]
Thank you!

Could we add support for TiB as well?

**Comment by paulidale** [comment]
Surely there is a better way to do this than using openssl rand.  `dd if=/dev/urandom of=/dev/hdd bs=1M` perhaps?

**Comment by jirka-h** [comment]
There is a HUGE difference in performance (by factor 5x) between `/dev/urandom` and `openssl rand`


```
dd if=/dev/urandom bs=1M  | pv > /dev/null
312MiB/s

openssl rand 2000000000 | pv > /dev/null
1.56GiB/s
```
