### ISSUE TITLE
Windows/MinGW path separator 

### ISSUE THREAD

**Issue by gz15028** [openssl/openssl#2263]
Hi,
In versions 1.1.x, there seems to be a issue in the configuring step with Windows/MinGW:
`C:\Perl64\bin\perl.exe "-I." -Mconfigdata "util\dofile.pl" \
            "-oMakefile" crypto\include\internal\bn_conf.h.in > crypto\include\internal\bn_conf.h
/bin/sh: C:Perl64binperl.exe: command not found
make: *** [crypto\include\internal\bn_conf.h] Error 127
perl "-I." -Mconfigdata "util\dofile.pl" \
	    "-oMakefile" crypto\include\internal\bn_conf.h.in > crypto\include\internal\bn_conf.h
Couldn't open file cryptoincludeinternalbn_conf.h.in: No such file or directory
make: *** [crypto\include\internal\bn_conf.h] Error 2`
The path separators are misinterpreted as escape characters. Any one care to patch a fix in the config script? Thanks!

**Comment by mattcaswell** [comment]
What version of perl are you using. Please note this comment from NOTES.PERL:
````
Notes on Perl on Windows
 ------------------------

 There are a number of build targets that can be viewed as "Windows".
 Indeed, there are VC-* configs targeting VisualStudio C, as well as
 MinGW and Cygwin. The key recommendation is to use "matching" Perl,
 one that matches build environment. For example, if you will build
 on Cygwin be sure to use the Cygwin package manager to install Perl.
 For MSYS builds use the MSYS provided Perl. For VC-* builds we
 recommend ActiveState Perl, available from
 http://www.activestate.com/ActivePerl.
````

So, for a mingw/msys build you need to be using msys perl.

**Comment by gz15028** [comment]
Thanks for the hint! The current msys distro comes with perl 5.8 while openssl requires 5.10+, so I had to use the Perl-MinGW (https://sourceforge.net/projects/perl-mingw/).
Here is the verification of perl version in msys:

`$ perl -version
This is perl 5, version 24, subversion 0 (v5.24.0) built for MSWin32-x86-multi-thread-64int
Copyright 1987-2016, Larry Wall
Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.
Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.`

And if I clean up and retry, the same problem happened again:

`$ make
C:\msys\msys\1.0\bin\perl.exe "-I." -Mconfigdata "util/dofile.pl" \
            "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/bin/sh: C:msysmsys1.0binperl.exe: command not found
make: *** [crypto/include/internal/bn_conf.h] Error 127`

May it be a problem of "Perl-MinGW"? Thanks!

**Comment by mattcaswell** [comment]
That's still not the right perl version. Msys perl supports sufficiently recent perl. Here is mine which works fine with OpenSSL 1.1.0:
````
$ perl --version

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-msys-thread-                                       multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
````

**Comment by gz15028** [comment]
Did you rebuild perl in msys? The msys catalogue says msys-perl 5.8.8.  How do I find the updated msys perl? Thanks!

**Comment by mattcaswell** [comment]
No, I just used the package manager. You are using msys2 right? IIRC original msys has some fairly prehistoric packages in it.

**Comment by gz15028** [comment]
That's the reason! Thanks! I will renew my msys and try it again.
