### ISSUE TITLE
document our assert policy

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2264]
From a comment by @mattcaswell in #2259:
```
I thought the consensus was heading towards using soft asserts followed by an "if" for the same condition. That should mean that a debug build that fails the assert will abort, but a non debug build will just return from the function with an error. That at least was the approach we took in the original WPACKET implementation (as you can see elsewhere in the file).
```

That's sensible and good, we should vote and make it an explicit part of our style doc.  There's bound to be some discussion.

**Comment by vdukhovni** [comment]
That'd be something like:

```
    if (should_not_happen) {
        assert(should_not_happen);
        /* push internal error onto error stack */
       return BAD /* for appropriate value of BAD */;
    }
```

**Comment by levitte** [comment]
@vdukhovni, that doesn't seem like quite the right way to use assertions...  they should assert something that *should* happen...  So for example, I'd expect this:

``` C
    assert(foo > 0);
    if (foo <= 0) {
        /* push internal error onto error stack */
        return BAD /* for appropriate value of BAD */;
    }
```

**Comment by vdukhovni** [comment]
My example was too terse, sorry, it main aim is to improve readability, by nesting the assert inside the test that runs all the time.
```
    if (!should_not_happen) {
        assert(!should_not_happen);
        /* push internal error onto error stack */
       return BAD /* for appropriate value of BAD */;
    }
```

**Comment by mattcaswell** [comment]
See #3496

**Comment by nickthetait** [comment]
Associated PR has been merged, please close this ticket.

**Comment by richsalz** [comment]
The code was changed, but did we write it down anywhere, like coding style?

**Comment by nickthetait** [comment]
Aha, I misread the title. So we'd be looking for a new chapter "Assertions" or would this fall under "Miscellaneous"?

Rough draft:
> Chapter #???: Assertions
> Prefer usage of a soft assertion followed by an "if" for the same condition. This ensures the following behavior in the case of a failed condition:
>    * Debug build would abort
>    * Production build would return from the function with an error

> Example code:
```
    if (!should_not_happen) {
        assert(!should_not_happen);
        /* push internal error onto error stack */
       return BAD /* for appropriate value of BAD */;
    }
```

**Comment by mattcaswell** [comment]
We should use our internal `ossl_assert` function so that there is need to duplicate the assert condition:

    if (!ossl_assert(!should_not_happen)) {
        /* push internal error onto error stack */
        return BAD;
    }

We should avoid use of the "old" style `OPENSSL_assert()`. In some cases just calling `assert()` directly may be justified - such as where there is no initial "if" condition, e.g. we see this idiom in a couple of places:

    switch(val) {
    case VAL1:
        /* handle VAL1 */
        break;
    case VAL2:
        /* handle VAL2 */
        break;
    default:
        assert("We forgot to handle a value" == NULL);
    }

**Comment by richsalz** [comment]
Moved to https://github.com/openssl/web/issues/49
