### ISSUE TITLE
quic-client fuzz: Assertion failed: !h->done_implicit

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#22658]
With the fix from #22615 applied, this file 
[crash-023364fbccd9d4db290b1a30e33461ea5c8b55e8.gz](https://github.com/openssl/openssl/files/13293855/crash-023364fbccd9d4db290b1a30e33461ea5c8b55e8.gz)

still produces:
ssl/quic/quic_txp.c:294: OpenSSL internal error: Assertion failed: !h->done_implicit

**Comment by mattcaswell** [comment]
This appears to be because we decide to use implicit length for stream data, but then continue to try to send more stream related frames for subsequent streams in the same packet. Fix on the way.
