### ISSUE TITLE
Tiny flaw in openssl 1.0.2 source code

### ISSUE THREAD

**Issue by cam888eron** [openssl/openssl#2266]
Tiny flaw found in openssl source code.

Cannot find demos/easy_tls/ in latest 1.1 version. Also cannot not find any mention
of it being removed in changelog. If demo removed, feel free to ignore this.

openssl/1.0.2j.6.1.140/src/demos/easy_tls/easy-tls.c#L322:        va_start(args, fmt);

Missing its va_end call, looks like it should be right after #L324.

**Comment by richsalz** [comment]
We did remove many demos in 1.1.0:
```
commit ec59112a822e16a539bc5dd1b8bed12afbcb82b8
Author: Rich Salz <rsalz@akamai.com>
Date:   Mon Mar 7 14:55:44 2016 -0500

    Remove really old demo's

    Reviewed-by: Richard Levitte <levitte@openssl.org>
```

But the bug you found in 1.0.2 we should fix.
