### ISSUE TITLE
CMP not working with TLS

### ISSUE THREAD

**Issue by henrikjehgmti** [openssl/openssl#22675]
Hi

I am running CMP against a commercial CA (one.digicert.com), and it fails due to a "CMP error: tlsv1 unrecognized name:SSL alert number 112". I am using the following example command:

./openssl  cmp -verbosity 8 -cmd kur -server https://one.digicert.com:443 -path /iot/api/<OUR_CA_PATH> -cert ssl_oper_cert.pub.pem -key ssl_oper_cert.pem -certout NewCert.pem -extracertsout NewChain.pem -newkey NewCert.key -subject <OUR_DISTINGUISED_NAME> -expect_sender <OUR_ISSUINGCA_DN> -recipient <OUR_ISSUINGCA_DN> -tls_used -tls_cert ssl_host_cert.pub.pem -tls_key ssl_host_cert.pem

I have debugged the failure and found that the failure happens because the server certificate from the server is for "one.digicert.com", but the name stored in the "APP_HTTP_TLS_INFO *info" is "https://one.digicert.com:443". 

If I don't include "https" in the server name, it will fail due to inconsistency between missing https and -tls_used parameter. 

I have then fixed it by including the "host" instead of the "server_opt" in the info structure, as indicated in the patch shown below.

My question is: Is it a bug in openssl, or is my command line incorrect?

I am using openssl 3.0.7 Forgive me if it is fixed in later versions. If not, and you find my solution appropriate, feel free to use it.

Patch:
```
Index: sw_apps_linux/openssl/src/apps/cmp.c
===================================================================
--- sw_apps_linux/openssl/src/apps/cmp.c        (revision 2336)
+++ sw_apps_linux/openssl/src/apps/cmp.c        (working copy)
@@ -1923,8 +1923,10 @@
         if ((info = OPENSSL_zalloc(sizeof(*info))) == NULL)
             goto err;
         (void)OSSL_CMP_CTX_set_http_cb_arg(ctx, info);
-        info->server = opt_server;
-        info->port = server_port;
+        info->server = host;
+        info->port = port;
+        host = NULL;
+        port = NULL;
         /* workaround for callback design flaw, see #17088: */
         info->use_proxy = proxy_host != NULL;
         info->timeout = OSSL_CMP_CTX_get_option(ctx, OSSL_CMP_OPT_MSG_TIMEOUT);
@@ -1959,8 +1961,6 @@
     ret = 1;

  err:
-    OPENSSL_free(host);
-    OPENSSL_free(port);
     OPENSSL_free(path);
     return ret;
  oom:

```

**Comment by mattcaswell** [comment]
@DDvO

**Comment by DDvO** [comment]
Thank you for your report and sorry that I did not notice it before to respond to it.

It turns out that this issue has already been fixed by #20034 for version 3.0.9+.

BTW, don't you use a `-tls_trusted` option to provide a TLS trust anchor cert?
You'd better do so in order to make the CMP client authenticate the server at TLS level.

And I wonder why you use the `-subject` option in conjunction with `-cmd kur`, which overrides the subject DN of the certificate to be updated?

**Comment by DDvO** [comment]
@mattcaswell, which label should now be set for this issue to indicate that 
this issue is about a bug that has already been fixed (and the fix has been released)?

**Comment by t8m** [comment]
resolved: fixed

**Comment by henrikjehgmti** [comment]
Thanks for the reply, and good to know that it is fixed in later versions. I will, when the dust settles, update to a later version.

And I am very happy about your comments - especially with why I still use -subject. It is simply a lack of CMP understanding. 

Regarding trust anchor, then my use of Digicert is in this case a question of that I am right now using it as a test. Real life Key Update Requests are to a HTTP server in a closed network, but preparing for that other customers will use HTTPS with CMP.

**Comment by DDvO** [comment]
> Thanks for the reply, and good to know that it is fixed in later versions. I will, when the dust settles, update to a later version.

Pleased to hear.


> And I am very happy about your comments - especially with why I still use -subject. It is simply a lack of CMP understanding.

I see. Then it may be particularly worth paying attention to the warnings given by the CMP client CLI,
which aims at catching at least basic (likely) mistakes using it.

 
> Regarding trust anchor, then my use of Digicert is in this case a question of that I am right now using it as a test. Real life Key Update Requests are to a HTTP server in a closed network, but preparing for that other customers will use HTTPS with CMP.

So I understand that in our case the use of TLS is not for real/strong extra protection.
Anyway (apart from any privacy concerns), CMP has been designed for security regardless which (potentially unprotected, insecure) transfer channel is used underneath.
