### ISSUE TITLE
Setting ciphers can be surprisingly expensive

### ISSUE THREAD

**Issue by wbl** [openssl/openssl#22683]
We've discovered that when setting ciphers for TLS 1.2 on a per SSL basis (as we need to see the client hello first) that this takes up time comparable to the ECDH derivation. It seems that at least part of the issue is on every call reordering the compiled in cipher suites to the default order regardless of what the string actually says to do, although the flamegraphs haven't shed all that much light on the exact problem.

This seems to be a long-standing issue, but fixing it might get back some of the performance lost other places.

**Comment by nhorman** [comment]
Can you post the flame graph?  Or alternatively a perf data sample would be helpful.
Also, what version of openssl are you testing with?
Thanks!

**Comment by wbl** [comment]
I'll try to work on a reproducer. This is on 3.1.4.

**Comment by nhorman** [comment]
ping, any update here @wbl

**Comment by wbl** [comment]
We rewrote the offending code privately, but with less features that are adequate to our case and got a tremendous improvement. In this case we only support full names of cipher suites, and so can do a simple lookup in the strings.

Sorry, I reported this issue while in the midst of some very urgent performance work, and then after it was done forgot entirely about it.

**Comment by nhorman** [comment]
Understood, thank you.  Given that you've rewritten your code, and realized significant improvement in performance, I'm working under the assumption that this is not something that can be further investigated and can be closed?  Do you agree?  Or is there more to do here?

**Comment by wbl** [comment]
To be clear, we replaced SSL_set_ciphers with a custom SSL_set_ciphers_akamai, which was written to use a much simpler lookup operation. I believe this pinpoints the root cause of the issue, namely the cipher setting is a very slow process even when none of the harder to implement features are used.

**Comment by beldmit** [comment]
@wbl would you mind providing an example implementation?

**Comment by wbl** [comment]
The one we use doesn't support anything beyond just using ciphersuite names exactly as IANA has them. If it is of interest I can provide it.

**Comment by t8m** [comment]
Actually SSL_set_ciphersuites() behaves in such way almost. I am thinking if we could generalize it.
