### ISSUE TITLE
DigestSqueeze support for SHAKE broken on some architectures

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#22692]
After merging the DigestSqueeze support for SHAKE we have 3 on-push CI failures. The broken architectures are powerpc64le, arm-linux-gnueabi and arm-linux-gnueabihf.

This is urgent problem as on-push CI is broken on the master branch.

**Comment by t8m** [comment]
ping also @rohanmclure for PPC64LE

**Comment by tom-cosgrove-arm** [comment]
Can you give links to failing builds?

**Comment by slontis** [comment]
Looks like the FIPS self tests are failing 
https://github.com/openssl/openssl/actions/runs/6824803374/job/18561441571
Note that S390 was fixed by a separate PR.

**Comment by slontis** [comment]
The PR is here..
https://github.com/openssl/openssl/pull/21511/files#diff-9590d35b68900ed82e824f86e47561914891ea3a876b9bc1eccba5e70cfcc7d8

Maybe it doesnt like the assembler changes?

**Comment by slontis** [comment]
I changed a couple of lines (I have no idea if they are wrong).. And I dont have access to arm/ppc machine(s) so not sure how I can fix this easily.

**Comment by slontis** [comment]
Note that the assembler changes did work on a arm64 M1

**Comment by t8m** [comment]
@slontis armv8 is supposedly OK. The failures are on 32 bit ARM.

**Comment by slontis** [comment]
Was moving house today so no time to even look at this.. Is there any way to get access to a 32 bit arm machine otherwise I am shooting in the dark.

**Comment by t8m** [comment]
You can use the qemu emulator to reproduce.

**Comment by davidben** [comment]
Possible causes: https://github.com/openssl/openssl/pull/21511#pullrequestreview-1727752719

Though I might suggest that it's worth having a way to run tests on the appropriate platforms before landing, whenever you all make asm changes. Including those fixes, since that's just the result of me looking at it for 30 seconds, not a careful review.

**Comment by tom-cosgrove-arm** [comment]
Can this issue be closed now?
