### ISSUE TITLE
AFL++ fuzer asn1 seems to really hang

### ISSUE THREAD

**Issue by toralf** [openssl/openssl#22717]
The reproducer is attached, unpack and run:
```
cd ./openssl_asn1_20231111-111205_9e75a0b911ff
./asn1  ./default/hangs/id\:000000\,src\:004220+004352\,time\:156687783\,execs\:483554479\,op\:splice\,rep\:16 
```
seems not to stop. The fuzzing system is a hardened Gentoo Linux [1]

[1] https://github.com/toralf/fuzz-utils
[Uploading openssl_asn1_20231111-111205_9e75a0b911ff.tar.gz…]()

**Comment by t8m** [comment]
@toralf the link is broken.

**Comment by toralf** [comment]
[openssl_asn1_20231111-111205_9e75a0b911ff.tar.gz](https://github.com/openssl/openssl/files/13335736/openssl_asn1_20231111-111205_9e75a0b911ff.tar.gz)

**Comment by nhorman** [comment]
I've not used it outside of CI, but looking at that command line, I don't  think thats a valid way to run the asn1 fuzzer.  

Running it under strace shows this:
```
strace ./asn1 ./default/hangs/id\:000000\,src\:004220+004352\,time\:156687783\,execs\:483554479\,op\:splice\,rep\:16
execve("./asn1", ["./asn1", "./default/hangs/id:000000,src:00"...], 0x7ffecffbcc88 /* 81 vars */) = 0
brk(NULL)                               = 0x561eb45fd000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffeb8411d80) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f31ef079000
...
sysinfo({uptime=82705, loads=[15840, 40768, 55008], totalram=67414962176, freeram=30763941888, sharedram=161812480, bufferram=2184712192, totalswap=8589930496, freeswap=8589930496, procs=1888, totalhigh=0, freehigh=0, mem_unit=1}) = 0
futex(0x561eb3ca1988, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x561eb3ca1990, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(0x561eb4647000)                     = 0x561eb4647000
read(0, 
```

Looks like its waiting for input on stdin

**Comment by mattcaswell** [comment]
You are supposed to run crash files through asn1-test

**Comment by t8m** [comment]
The crash file does not seem to hang for me when I run it against asn1-test.

@toralf could you please provide a backtrace from the hang?

**Comment by toralf** [comment]
Tried to reproduce it - cannot do it tillnow - ok, so sry, will close this is invalid.
