### ISSUE TITLE
Transition to treating NULL pointers as errors

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2271]
During discussion of #2246, the following decision was mentioned:

> We did decide quite some time ago now **to go away from checking for `NULL` pointers**. The argument was that it was to be considered a programming error and has also helped uncover bugs in our own code.

In addition, the following statement was made to justify this:

> Consider the C library which never checks for NULL.

Personally, I find both the decision and its justification suprising. Consider for example the documentation of&nbsp;`free()`, which is an example of a C library&nbsp;function that *does* check for `NULL`:

<pre>
     The free() function deallocates the memory allocation pointed to by ptr.
     <b>If ptr is a NULL pointer, no operation is performed.</b>
</pre>

This is one example of a C function that simplifies applications in that they can call `free(ptr);` also if they *know* that the pointer is `NULL`.

In my own application that uses OpenSSL, I rely in several cases on the currently **documented behaviour** of OpenSSL, which guarantees for example that `X509_free()` does *nothing* if the pointer is&nbsp;`NULL`:

<pre>
       X509_free() decrements the reference count of X509 structure a and
       frees it up if the reference count is zero. <b>If a is NULL nothing is
       done.</b>
</pre>

Therefore, if the decision to *remove* this guarantee is really made, please consider removing such statements from the man pages, since more and more applications will rely on it as long as the documentation itself guarantees this&nbsp;behaviour.

This is also related to #2254, since many applications currently rely on *no* error being raised when the stack is `NULL`, which is also guaranteed in the documentation. Thank you!

**Comment by vdukhovni** [comment]
> @triska [writes about `free()` checking for a `NULL` argument]

The example of `free()` is not relevant.  `NULL` is a *valid* input to `free()`.  It is *not* an error to pass `NULL` to `free()`. The function `free()` is not checking for an invalid `NULL` input and  returning an error indication.

**Comment by richsalz** [comment]
And we extended that behavior of free to all OpenSSL free routines.

**Comment by richsalz** [comment]
The current behavior cannot change until we do an API-breaking release, 1.2.  The earliest that would happen is 2018.

**Comment by triska** [comment]
Since I thus may have less than 1 year to adapt my applications, I want to start as early as possible with the then necessary changes. Therefore, please clarify: Will functions like `X509_free()` also be affected? That is, will they *continue* to check for `NULL` and do nothing if `NULL` is specified? Or do I have to take care to *not* call such functions with `NULL` as argument?

**Comment by richsalz** [comment]
All free functions, like C free will be a no-op for NULL.  No other  changes are planned at this time.
Having said that, I am only one member of the team, and I may leave or get out-voted by others. What I *can* promise is that we are going to try to avoid semantic changes before 1.2, which is unlikely to happen this year.

IMO, the safest thing for you to do is to adapt to what all releases of OpenSSL currently do.

**Comment by kroeckx** [comment]
If we make changes related to checking NULL, it would be for cases
where passing that NULL doesn't make sense. For instance if you
call SSL_new(), ctx really shouldn't be NULL. It currently checks
for that NULL and returns an error in that case. Also note that
it's not documented what the behaviour is when you pass a NULL
to SSL_new().

Calling free() with NULL is expected and documented behaviour, we
actually changed it in all functions to work. It seems very
unlikely that we will change that.

**Comment by t-j-h** [comment]
There are a mix of views on this topic in the team. I for one am in favour of not dereferencing NULL pointers in library code ever and returning an error indication where possible. The current OpenSSL implementation is inconsistent in its handling of NULL parameters.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by triska** [comment]
I am closing this issue since I no longer care about this library. Thank you a lot!
