### ISSUE TITLE
Passing NULL poiter to free() or free_impl() in err_clear()

### ISSUE THREAD

**Issue by huiyuexu** [openssl/openssl#22716]
**Issue Description:** Passing NULL poiter to `free()` or `free_impl()` in `err_clear()`, when `es->err_file[i]` is `NULL`.

**Cause Analysis:**

Backtrace as following.

```
#0  in free
#1  in CRYPTO_free
#2  in ERR_new ()
#3  in BIO_new_file () 
#4  in def_load ()
#5  in CONF_modules_load_file_ex ()
#6  in ossl_config_int ()
#7  in ossl_init_config_ossl_ () 
#9  in CRYPTO_THREAD_run_once ()
#10 in OPENSSL_init_crypto ()
#11 in ossl_engine_table_select ()
#12 in EVP_DigestInit_ex ()
```

In `def_load` , `BIO_new_file` return `NULL` because of the program is without config file. Then call `ERR_raise_data` -> `ERR_new` and `es->err_file[i]` is `NULL`.

**My Suggestions:**
Although mostly standards compilant version of the C library treat free(NULL) as no-op, free null pointer is still an undefined behavior. In particular when users call `CRYPTO_set_mem_functions` set the free_impl, uncontrollable effects will occur. And some versions of free would crash on free(NULL).

So I think that `es->err_file[i]` should be check not NULL in `err_clear()`. Is it accepted by the community? If accepted, I will submit a PR to fix it.

**Comment by t8m** [comment]
Nope. It is absolutely required throughout the codebase that `free(NULL);`  or any openssl implemented public and private `XYZ..._free(NULL);` functions work.

**Comment by nhorman** [comment]
Just out of curiosity, is this a multithreaded application?  Can you post the backtraces of all the threads when this occurs?

**Comment by huiyuexu** [comment]
@nhorman  It is a single thread application. If no configuration file is available for any application, `free(NULL)` can be reproduced.

**Comment by nhorman** [comment]
Can you produce the full stack trace, or better still, the asan output if you can reproduce with enable asan?

**Comment by huiyuexu** [comment]
My application call CRYPTO_set_mem_functions to set the `my_free` callback and the `NULL` pointer is asserted in `my_free`. The assertion is triggered using the OpenSSL 3.0, but not be triggered using OpenSSL 1.1.

In fact, my application didn't crash. I raise this issue mainly to discuss the strategy of `free(NULL)`.

Backstrace:
```
#0  in my_free
#1  in CRYPTO_free
#2  in ERR_new ()
#3  in BIO_new_file () 
#4  in def_load ()
#5  in CONF_modules_load_file_ex ()
#6  in ossl_config_int ()
#7  in ossl_init_config_ossl_ () 
#9  in CRYPTO_THREAD_run_once ()
#10 in OPENSSL_init_crypto ()
#11 in ossl_engine_table_select ()
#12 in EVP_DigestInit_ex ()
```

**Comment by huiyuexu** [comment]
Sorry, the original issue description is not clear enough. I just want a clear strategy. 1 or 2?
1. Null Pointer should be check in OpenSSL.
2. Null Pointer should br check in free callbacks set by `CRYPTO_set_mem_functions `.

**Comment by paulidale** [comment]
#2.  Your free replacement is responsible for checking for NULL and doing nothing in that case.

**Comment by JerryDevis** [comment]
> 2. Your free replacement is responsible for checking for NULL and doing nothing in that case.

OK, thanks for your reply.

**Comment by huiyuexu** [comment]
> 2. Your free replacement is responsible for checking for NULL and doing nothing in that case.

OK. Thanks for your reply.

**Comment by davidben** [comment]
> Although mostly standards compilant version of the C library treat free(NULL) as no-op, free null pointer is still an undefined behavior.

The question has been answered, but I'll correct this last point: free of a null pointer is *not* undefined behavior. The C standard is quite clear that free(null) is required to do nothing.

> The free function causes the space pointed to by ptr to be deallocated, that is, made
 available for further allocation. If ptr is a null pointer, no action occurs. Otherwise, if
 the argument does not match a pointer earlier returned by a memory management
 function, or if the space has been deallocated by a call to free or realloc, the
 behavior is undefined.

**Comment by huiyuexu** [comment]
Thank you, I've seen this definition in Standard C. ([C90(https://www.yodaiken.com/wp-content/uploads/2021/05/ansi-iso-9899-1990-1.pdf), C99(https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf))
