### ISSUE TITLE
`openssl dgst -list` is missing entries

### ISSUE THREAD

**Issue by jamuir** [openssl/openssl#22736]
The output of `openssl dgst -list` is missing some entries (e.g. `keccak-kmac-128` and `keccak-kmac-256`):

```
$ LD_LIBRARY_PATH=../.. ../../apps/openssl version
OpenSSL 3.3.0-dev  (Library: OpenSSL 3.3.0-dev )
```
```
$ LD_LIBRARY_PATH=../.. ../../apps/openssl dgst -list
Supported digests:
-blake2b512                -blake2s256                -md4                      
-md5                       -md5-sha1                  -mdc2                     
-ripemd                    -ripemd160                 -rmd160                   
-sha1                      -sha224                    -sha256                   
-sha3-224                  -sha3-256                  -sha3-384                 
-sha3-512                  -sha384                    -sha512                   
-sha512-224                -sha512-256                -shake128                 
-shake256                  -sm3                       -ssl3-md5                 
-ssl3-sha1                 -whirlpool
```
```
$ echo -n "hello" | LD_LIBRARY_PATH=../.. ../../apps/openssl dgst -keccak-kmac-128
KECCAK-KMAC-128(stdin)= 13a9d38981dd1bbd8b31cba69740f147e47a80161e72ab1e3ad24449d2331f5a
```

**Comment by nhorman** [comment]
I think its because keccak is implemented as a provider and never calls EVP_add_digest, which is what adds the present names to the OBJ_NAME hash table.  Not sure how to go about fixing that

**Comment by t8m** [comment]
Yeah, it's actually debatable whether it should be listed - probably not.  Those digests are meant to be usable in various places where object id is needed.

**Comment by jamuir** [comment]
It is interesting to compare the output of these two commands:

- `openssl dgst -list`
- `openssl list -digest-algorithms`

I think the only discrepancy is the two kmac digests.

**Comment by jamuir** [comment]
> Yeah, it's actually debatable whether it should be listed - probably not. Those digests are meant to be usable in various places where object id is needed.

are you saying that `keccak-kmac-128` and `keccak-kmac-256` should not be listed in the output of `openssl dgst -list` because they do not have object-ids assigned to them?

**Comment by t8m** [comment]
Yep

**Comment by alecov** [comment]
Makes no sense, honestly.

If it's supported, it should be listed, or indicate clearly that "Supported digests:" should be replaced by "(Some) supported digests, see openssl list -digest-algorithms for a real list:".
