### ISSUE TITLE
64-bit SHA-3 assembly changes violate ABI for int parameter

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#22757]
#21511 introduced an `int` parameter to a bunch of assembly functions. `int` is 32-bit, even on 64-bit architectures.

Taking a 32-bit parameter in 64-bit assembly is a little subtle. Many 64-bit calling conventions say that 32-bit parameters, when passed in registers, leave the upper half of the register unspecified. This means assembly functions cannot rely on them being any particular value, like zero. Reading the upper half of the register can then, depending on how the compiler happens to emit code, generate the wrong value.

For example, clause C.9 in AAPCS64 only promises the least significant bits of the register are filled in.
https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#parameter-passing-rules

You can see this in action here. Observe how Clang does not do anything to mask off the upper half of the register here.
https://godbolt.org/z/ao3WxMfr7

When I last looked at this years ago, I was unable to find a citation that officially said x86_64 calling conventions (SysV or Windows) did this too, but I was able to observe compiler output which implied this was the case. No idea about ppc64.

The assembly added in #21511 seems to access the values as 64-bit. That means, on architectures with the above calling convention, they can get the wrong value, depending on how the compiler chooses to generate code.

**Comment by davidben** [comment]
> No idea about ppc64.

Looks like this is what past me wrote about ppc64.

```
  // ELFv2, section 2.2.2.3 says the parameter save area sign- or zero-extends
  // parameters passed in memory. Section 2.2.3 is unclear on how to handle
  // register parameters, but section 2.2.2.3 additionally says that the memory
  // copy of a parameter is identical to the register one.
```

So I think that means accessing the 64-bit register on ppc64 is fine? But you all might want to double-check that.

**Comment by davidben** [comment]
@slontis FYI

**Comment by slontis** [comment]
Would you recommend setting the type to a uint64_t ?

looking at aes_platform.h there are quite a few int params being used in there. 
'bits' and 'enc'.

**Comment by t8m** [comment]
I would prefer properly accessing the arguments as 32 bit and not changing the type. I'll add that to  #22750

**Comment by slontis** [comment]
@davidben Note that I havent forgotten about your ABI testing comments.
