### ISSUE TITLE
Provider sigalgs not loaded from openssl.cnf

### ISSUE THREAD

**Issue by martinschmatz** [openssl/openssl#22761]
**_Issue_**

When specifying a provider supplied signature algorithm in `SignatureAlgorithms` in `openssl.cnf`, the code point of this signature algorithm is not added to the `ClientHello`. Rather, the processing of the  `SignatureAlgorithms` list is stopped and all available signature algorithms (including all provider sigalgs) are added to the `ClientHello`. 

The equivalent for `Groups` in `openssl.cnf` is working correctly for provider supplied groups.

**_Root cause_**

The `tls1_set_sigalgs_list` [function](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/t1_lib.c#L2943) is [using](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/t1_lib.c#L2947C10-L2947C25) `CONF_parse_list` with `sig_cb` [callback function](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/t1_lib.c#L2874). The callback function limits the search for signature algorithms to the [content](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/t1_lib.c#L1375) of the sigalg_lookup_tbl and does not check any provider. 

**_Possible mitigation_**

By adding a code segment [here](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/t1_lib.c#L2899) to first check whether a provider would support a signature algorithm, the provider based signature algorithms can be correctly added to the `ClientHello`. 

A dummy, zeroized `SSL_CTX` is used which is initialized solely with the provider supplied signature algorithms using the [function](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/t1_lib.c#L707) `ssl_load_sigalgs`. Algorithm names and code points are then available from the `TLS_SIGALG_INFO` [structure](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/ssl_local.h#L772) which is [part of](https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/ssl/ssl_local.h#L1172) `SSL_CTX`.
```
    if (p == NULL) {
        /* We first check the providers */
        SSL_CTX *ctx_helper = OPENSSL_zalloc(sizeof(*ctx_helper));
        /* load provider sigalgs */
        if (!ctx_helper || !ssl_load_sigalgs(ctx_helper)) {
            ERR_raise(ERR_LIB_SSL, ERR_R_SSL_LIB);
            return 0;
        }
        /* Check if a provider supports the sigalg */
        for (int i=0; i < ctx_helper->sigalg_list_len; i++) {
            if (ctx_helper->sigalg_list[i].sigalg_name != NULL && strcmp(etmp, ctx_helper->sigalg_list[i].sigalg_name) == 0) {
                sarg->sigalgs[sarg->sigalgcnt++] = ctx_helper->sigalg_list[i].code_point;
                SSL_CTX_free(ctx_helper);
                return 1;
            }
        }
        SSL_CTX_free(ctx_helper);
        /* Check the built-in sigalgs */
        for (i = 0, s = sigalg_lookup_tbl; i < OSSL_NELEM(sigalg_lookup_tbl);
            ....
            ....
```

**_Test environment_** 

OpenSSL 3.2.0-beta1 26 Oct 2023 (Library: OpenSSL 3.2.0-beta1 26 Oct 2023) commit 26ecab1fd7fa7f5103ac57ef41ee0dd38fbe2ddc
liboqs v0.8.0 (+) commit 7c3a0e9aa7f9568e4dcafaf908ff8aa0008f0b71
oqs provider OQS Provider v0.5.2 commit b32dfe2be5eb8cd506838777a8c83cff5bb15545
Linux ae23f6b39618 6.1.19 #1 SMP PREEMPT_DYNAMIC Sat Mar 25 09:19:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
curl 8.5.0-DEV (x86_64-pc-linux-gnu) libcurl/8.5.0-DEV OpenSSL/3.2.0 nghttp2/1.58.0 commit c868b0e30f10cd0ac71aa3f6b040af51592e36a5
Wireshark Version 4.0.6 (Git v4.0.6 packaged as 4.0.6-1-exp1-ubuntu22.04.0~ppa1).

**Comment by martinschmatz** [comment]
Addendum: This is instrumental to have full control over the sigalgs announced by a client in a `ClietHello` and hence would make sense to be added to the upcoming v3.2 release such that the great work of @baentsch can be fully leveraged. 

A PR can be provided on short notice.

**Comment by t8m** [comment]
@mattcaswell should this be treated as a bug? IMO too late for 3.2.0 but could it be fixed in 3.2.1? Or is it a feature -> for 3.3?

**Comment by martinschmatz** [comment]
I posted it as bug because provider capabilities are not scanned at all, which leads to the effect that the following line in `openssl.cnf` 
```
SignatureAlgorithms =  dilithium5:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:ed25519:ed448:RSA+SHA256:RSA+SHA384:RSA+SHA512
```
will result in ALL available signature algorithms to be included in the `ClientHello`, even if the [OQS provider](https://github.com/open-quantum-safe/oqs-provider) is loaded. If no debug mode is active, this happens _silently_ and is therefore difficult to detect. 

It is also not the case that the `dilithium5` sigalg is simply ignored and the other specified sigalgs (`ECDSA+SHA256:ECDSA+SHA384:...`) are used, but all available sigalgs are added (probably as fallback?!?)- even algs that the user does not intend to offer in the `ClientHello`. 

And while @baentsch enabled provider based signatures and hence the usage of QSC certificates, the only way to make use of that feature is to NOT specify `SignatureAlgorithms` in `openssl.cnf` and therefore have all kinds of old, unwanted sigalgs in the `ClientHello` - which in my nomenclature qualifies as bug and not as feature. 

I leave it up to you experts to decide whether it should be included in v3.2.0 or wait for v3.2.1.

**Comment by mattcaswell** [comment]
This looks like a bug to me since it is intended to work in 3.2.

> A PR can be provided on short notice.

Yes please!

**Comment by martinschmatz** [comment]
@mattcaswell Where do you want the PR to land? In master or v3.2 branch?

I assume it should go to master and you folks will make sure it's 'backported' to v3.2 but wanted to double-check.

**Comment by mattcaswell** [comment]
Yes - please target the master branch initially. We will mark it for backport to 3.2. If it can't be cherry-picked cleanly then we may need a second PR - but we'll cross that bridge when we come to it.

**Comment by ajbozarth** [comment]
On @martinschmatz request I'm taking his patch, cleaning it up (code style, tests, etc) and will open an initial draft PR by EOD (CST).
