### ISSUE TITLE
 crash issue on X509_getm_notAfter

### ISSUE THREAD

**Issue by DanielKongWK** [openssl/openssl#22760]
The crash happening on below environment
libssl-dev (libcrypto.so.3) on ubuntu 22.04

This function trigger the segmentation fault crash issue. Below i put the detail of the crash from gdb debugger

ASN1_TIME ***X509_getm_notAfter**(const X509 *x)
{
    return x->cert_info.validity.notAfter;
}

![img1](https://github.com/openssl/openssl/assets/151133402/8b2e16dc-32f6-4f45-a475-c1a654ff20aa)

The gdb debugger

![img2](https://github.com/openssl/openssl/assets/151133402/0379ccfe-797a-4564-a168-c2e49c6448af)

The code calling the openssl function

![img3](https://github.com/openssl/openssl/assets/151133402/6e8a8397-3c6d-4ac6-9012-f2e38efff0c0)

**Comment by nhorman** [comment]
What version of openssl are you using, and what command are you running to trigger this behavior?

Also, how is x509_cert defined in your code?

**Comment by DanielKongWK** [comment]
I am using OpenSSL 3.0.2 15 Mar 2022. In my code **after** PKCS12_parse(p12, password, &pkey, &x509_cert, &additional_certs); i check for the time after and before and this trigger the segmentation fault.

If commented checking time and after, there will be no segmentation fault and can proceed with x509_cert getting the cert.

**Comment by DanielKongWK** [comment]
We have resolved the issue after make some changes on openssl.cnf for legacy. Thanks for your assistance.
