### ISSUE TITLE
Confusing Empty Lines

### ISSUE THREAD

**Issue by fengsuiyvmin** [openssl/openssl#22781]
![image](https://github.com/openssl/openssl/assets/51240758/02c7f452-b7fa-4813-b6ec-a5e5fe5baae6)
every time when I was pressing "y" or "n" for signing, there will be some empty lines that needs me to press Enter key for several times.
Is it an aimed design or just a bug?
By the way, windows 10/11 system.

**Comment by mattcaswell** [comment]
Which version of OpenSSL are you seeing this with? What command line options did you supply?

**Comment by fengsuiyvmin** [comment]
这是来自QQ邮箱的自动回复邮件。This is an auto reply from my email.非常抱歉我最近无法亲自回复您的邮件。I'm sorry I can't reply to you by myself.我将在有空时尽快给您回复。I'll reply as soon as possible if I was convenient.

**Comment by fengsuiyvmin** [comment]
I was using 3.1.4 on win10/win11 enviroment, with dos command line.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openssl/openssl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月21日(星期二) 晚上7:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openssl/openssl] Confusing Empty Lines (Issue #22781)





 
Which version of OpenSSL are you seeing this with? What command line options did you supply?

**Comment by jamuir** [comment]
@fengsuiyvmin :  could you provide some steps-to-reproduce?  What command did you run?

**Comment by fengsuiyvmin** [comment]
这是来自QQ邮箱的自动回复邮件。This is an auto reply from my email.非常抱歉我最近无法亲自回复您的邮件。I'm sorry I can't reply to you by myself.我将在有空时尽快给您回复。I'll reply as soon as possible if I was convenient.

**Comment by nhorman** [comment]
marking as inactive, will close at the end of the 3.4 dev cycle
