### ISSUE TITLE
[Docs] EVP_RAND-SEED-SRC Example fails (uninstantiated Seed Src)

### ISSUE THREAD

**Issue by Jamie-Cui** [openssl/openssl#22810]
- Version: 3.0.12
- sha256: 9a7a7355f3d4b73f43b5730ce80371f9d1f97844ffc8c4b01c723ba0625d6aad

The example in https://www.openssl.org/docs/man3.0/man7/EVP_RAND-SEED-SRC.html fails
```
...
EVP_RAND_instantiate(rctx, strength, 0, NULL, 0, params); // ret = 0
...
```

After some digging, the problem is that the fetched `seed` is uninstantiated, when its child `rctx` is in the process of instantiating.

So I presume the simple fix is to instantiate `seed` after its creation, i.e.,
```
  /* Create a seed source */
  rand = EVP_RAND_fetch(nullptr, "SEED-SRC", NULL);
  seed = EVP_RAND_CTX_new(rand, NULL);
  EVP_RAND_instantiate(seed, strength, 0, NULL, 0, NULL); // add this line
  EVP_RAND_free(rand);
```

**Comment by t8m** [comment]
Would you like to create a pull request correcting this issue?

**Comment by Jamie-Cui** [comment]
> Would you like to create a pull request correcting this issue?

Sure :)
