### ISSUE TITLE
unable to compile 'mknum.pl' 3.2.0 on Linux

### ISSUE THREAD

**Issue by adamskiii** [openssl/openssl#22841]
I have recently upgraded from OpenSSL 3.1.4 to 3.2.0 and no longer able to compile on Linux Redhat 9/8/7. It seems to be dying in mknum.pl and unable to identify the cause

Full output of failing comment

> /bin/perl ./Configure threads -D_GNU_SOURCE -D_REENTRANT -D_POSIX_C_SOURCE=199506 no-idea no-rc5 no-asm no-ssl no-autoload-config enable-fips debug-linux-x86_64 shared --prefix=/build/openssl31rh9gcc1120/openssl/3.2-branch/outDEBUG64 --openssldir=openssl --debug no-engine no-dynamic-engine

> /usr/bin/perl ./util/mknum.pl --version 3.2.0 --no-warnings \
>                 --ordinals ./util/libcrypto.num \
>                 --symhacks ./include/openssl/symhacks.h \
>                 include/internal/asn1.h include/internal/dso.h include/internal/err.h include/internal/o_dir.h include/internal/sslconf.h include/openssl/aes.h include/openssl/asn1.h include/openssl/asn1err.h include/openssl/asn1t.h include/openssl/async.h include/openssl/asyncerr.h include/openssl/bio.h include/openssl/bioerr.h include/openssl/blowfish.h include/openssl/bn.h include/openssl/bnerr.h include/openssl/buffer.h include/openssl/buffererr.h include/openssl/camellia.h include/openssl/cast.h include/openssl/cmac.h include/openssl/cmp.h include/openssl/cmp_util.h include/openssl/cmperr.h include/openssl/cms.h include/openssl/cmserr.h include/openssl/comp.h include/openssl/comperr.h include/openssl/conf.h include/openssl/conferr.h include/openssl/configuration.h include/openssl/conftypes.h include/openssl/core.h include/openssl/core_dispatch.h include/openssl/core_names.h include/openssl/core_object.h include/openssl/crmf.h include/openssl/crmferr.h include/openssl/crypto.h include/openssl/cryptoerr.h include/openssl/cryptoerr_legacy.h include/openssl/ct.h include/openssl/cterr.h include/openssl/decoder.h include/openssl/decodererr.h include/openssl/des.h include/openssl/dh.h include/openssl/dherr.h include/openssl/dsa.h include/openssl/dsaerr.h include/openssl/e_os2.h include/openssl/e_ostime.h include/openssl/ec.h include/openssl/ecdh.h include/openssl/ecdsa.h include/openssl/ecerr.h include/openssl/encoder.h include/openssl/encodererr.h include/openssl/engine.h include/openssl/engineerr.h include/openssl/err.h include/openssl/ess.h include/openssl/esserr.h include/openssl/evp.h include/openssl/evperr.h include/openssl/fips_names.h include/openssl/fipskey.h include/openssl/hmac.h include/openssl/hpke.h include/openssl/http.h include/openssl/httperr.h include/openssl/idea.h include/openssl/kdf.h include/openssl/kdferr.h include/openssl/lhash.h include/openssl/macros.h include/openssl/md2.h include/openssl/md4.h include/openssl/md5.h include/openssl/mdc2.h include/openssl/modes.h include/openssl/obj_mac.h include/openssl/objects.h include/openssl/objectserr.h include/openssl/ocsp.h include/openssl/ocsperr.h include/openssl/opensslv.h include/openssl/ossl_typ.h include/openssl/param_build.h include/openssl/params.h include/openssl/pem.h include/openssl/pem2.h include/openssl/pemerr.h include/openssl/pkcs12.h include/openssl/pkcs12err.h include/openssl/pkcs7.h include/openssl/pkcs7err.h include/openssl/prov_ssl.h include/openssl/proverr.h include/openssl/provider.h include/openssl/rand.h include/openssl/randerr.h include/openssl/rc2.h include/openssl/rc4.h include/openssl/rc5.h include/openssl/ripemd.h include/openssl/rsa.h include/openssl/rsaerr.h include/openssl/safestack.h include/openssl/seed.h include/openssl/self_test.h include/openssl/sha.h include/openssl/srp.h include/openssl/stack.h include/openssl/store.h include/openssl/storeerr.h include/openssl/thread.h include/openssl/trace.h include/openssl/ts.h include/openssl/tserr.h include/openssl/txt_db.h include/openssl/types.h include/openssl/ui.h include/openssl/uierr.h include/openssl/whrlpool.h include/openssl/x509.h include/openssl/x509_vfy.h include/openssl/x509err.h include/openssl/x509v3.h include/openssl/x509v3err.h
> Unable to open ./util/libcrypto.num at ./util/mknum.pl line 126.
> make[1]: *** [Makefile:5072: util/libcrypto.num] Error 13
> make[1]: Leaving directory '/build/openssl31rh9gcc1120/3.2-branch/src'
> make: *** [Makefile:3671: build_libs] Error 2

**Comment by mspncp** [comment]
This is the error message:

> Unable to open ./util/libcrypto.num ...

**Comment by adamskiii** [comment]
> This is the error message:
> 
> > Unable to open ./util/libcrypto.num ...

I did see that originally but unsure as to why it would suddenly appear in 3.2 and not 3.1 . The file exists and has the correct permissions

**Comment by mspncp** [comment]
Could you please run the configure command through strace?

```
strace /bin/perl ./Configure threads  <...your arguments...>   |&  grep -F libcrypto.num
```

**Comment by mspncp** [comment]
> > > Unable to open ./util/libcrypto.num ...
> 
> ... The file exists and has the correct permissions

Just to be sure: did you also check the ownership? Did you try 

```
cat ./util/libcrypto.num
```

**Comment by adamskiii** [comment]
> Could you please run the configure command through strace?
> 
> ```
> strace /bin/perl ./Configure threads  <...your arguments...>   |&  grep -F libcrypto.num
> ```
> 
> _(not that there is no space between `|`and `&`)_

Running the command outputs the following : 

`newfstatat(AT_FDCWD, "util/libcrypto.num", {st_mode=S_IFREG|0444, st_size=399806, ...}, 0) = 0
newfstatat(AT_FDCWD, "util/libcrypto.num", {st_mode=S_IFREG|0444, st_size=399806, ...}, 0) = 0`

**Comment by levitte** [comment]
`...0444...`

Oh, so you don't have any write permissions on `util/libcrypto.num`!  That explains it, 'cause `util/mknum.pl` does try to open it for writing.

**Comment by levitte** [comment]
...  and this is probably another reason why we previously only ran mknum.pl with `make update`.  It doesn't happen very often, but every now and then, we stumble onto someone that has a read-only source tree, such as this case.  That should be perfectly legitimate!

**Comment by adamskiii** [comment]
My goodness, thank you! I thought I changed the permissions to the file but I guess I never did. It compiles now :)

**Comment by mspncp** [comment]
... and this is probably another reason why we previously only ran mknum.pl with `make update`. 

It surprises me that this behaviour was changed. During a normal build, it shouldn't be necessary to modify a versioned file. (That feels like a step backwards into the 1.0.2 era imo.) Explicitly calling `make update` when developing seemed a better choice. Do you plan to fix this, @levitte?

Reopening, because it's a bug.

**Comment by levitte** [comment]
I have a fix underway.  It might not fix everything caused by a read-only source tree, but at least the mknum runs

**Comment by levitte** [comment]
Note that #22890 only fixes the deeper issue partially: that we don't treat read-only source directories well.  But perhaps that should be raised as a separate issue...

**Comment by mspncp** [comment]
See issue #22907.
