### ISSUE TITLE
SIGSEGV from EVP_MAC_CTX_get_mac_size()

### ISSUE THREAD

**Issue by Hal-Murray** [openssl/openssl#22842]
My test environment is OpenSSL 3.1.1 on Fedora.
James Muir reports it fails on the "master" branch.  (2023-Nov-27)

The example is a ctx that is ready but hasn't been used yet.

Calling EVP_MAC_init() fixes the problem.

Example file is a .txt because the web form said it didn't like .c
[bug.c.txt](https://github.com/openssl/openssl/files/13483202/bug.c.txt)

**Comment by nhorman** [comment]
This seems like an expected error (or at least unsurprising behavior).  EVP_MAC_init initializes the context in which this instance of the EVP_MAC is used.  The documentation could be more clear here, but any use of the context structure prior to its initialization is effectively using uninitialized data.

In this specific case the segfault is occurring because EVP_MAX_CTX_get_mac_size is attempting to fetch the mac size from the underlying algctx struct, which has not yet been set up properly via EVP_MAC_init

**Comment by mattcaswell** [comment]
> The documentation could be more clear here, but any use of the context structure prior to its initialization is effectively using uninitialized data.

I don't think I agree here. This seems to occur after `EVP_MAC_CTX_new()` which should return a properly initialised (and empty) `EVP_MAC_CTX` object. Failing to initialise the mac with `EVP_MAC_init` is certainly an error, but I would not expect `EVP_MAC_CTX_get_mac_size()` to seg fault if you fail to do so.

**Comment by nhorman** [comment]
I think what you are describing is exactly what is happening.  Calling EVP_MAC_CTX_new returns a new empty ctx.  Most notably that ctx has an internal algctx for which the cipher is set to NULL.  Its only after EVP_MAC_init is called through the call chain EVP_MAC_init->cmac_init->cmac_set_ctx_params, that the provider loads the cipher from the provided params and assigns a cipher to the ctx->algctx->cipher struct.

This seems to be the same pattern for other objects, so this same behavior may be present in other apis as well (just doing a visual inspection of the EVP digest code, I've not tested).

regarding the EVP_MAC api here, it would seem like the thing to do might be to augment cmac_get_ctx_params such that  an error is returned if the algctx cipher struct isn't set yet.  But that really just turns the segfault into an error case, the application fix would still need to be calling EVP_MAC_init.

**Comment by mattcaswell** [comment]
> But that really just turns the segfault into an error case, the application fix would still need to be calling EVP_MAC_init.

Right - That's all was saying. It should not seg fault, it should return an error instead.

**Comment by jamuir** [comment]
we discussed this some on the "openssl-users" list.

I'm not sure if an error should be emitted.

the documentation says `EVP_MAC_CTX_get_mac_size()` should return 0 in this situtation.

https://www.openssl.org/docs/manmaster/man3/EVP_MAC_init.html

> EVP_MAC_CTX_get_mac_size() returns the expected output size, or 0 if it isn't set. If it isn't set, a call to EVP_MAC_init() will set it.

**Comment by nhorman** [comment]
That sounds right though.  A zero return code is in keeping both with the docs, and with the typical return code scheme openssl uses (i.e. 0 == something has gone wrong). 

So it sounds like we're all on the same page then, that EVP_MAC_init is required for EVP_MAC_CTX_get_mac_size to not fail, and EVP_MAC_CTX_get_mac_size should return 0 if EVP_MAC_init hasn't been called on the context

**Comment by t8m** [comment]
Actually the implementation could be able to return the MAC size even after the set params call which sets the AES cipher. So it could be made to work even without the init() call.
