### ISSUE TITLE
Bug in Configure out-of-tree directory path computation

### ISSUE THREAD

**Issue by b-spencer** [openssl/openssl#22853]
I think there's a bug in OpenSSL 3.2.0's `Configure` script that breaks out-of-tree configuration generation when the source tree is "several parent directories" away (and likely in other circumstances) and the source tree's parents to that same depth are not owned by you.

For example, with a freshly checked out copy of the `openssl-3.2.0` tag:

```
~/sandbox/parent/openssl$ git log -n1
commit cf2877791ce7508684109664f467c9e40987692f (HEAD, tag: openssl-3.2.0)

~/sandbox/one/two/three/four/five$ ../../../../../parent/openssl/Configure linux-x86_64
Configuring OpenSSL version 3.2.0 for target linux-x86_64
Using os-specific seed configuration

Failure!  Makefile wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

mkdir /home/bspencer/sandbox/parent/openssl/../../../../../parent: Permission denied at ../../../../../parent/openssl/Configure line 1916.
```

I think this is caused by a small mistake in [`Configure` on line 2476](https://github.com/openssl/openssl/blob/openssl-3.2.0/Configure#L2476) (on the openssl-3.2.0 tag).

I think the `$d` variable needs to be computed using the _original_ value of `$i` obtained from the regex match, before `$i` was recomputed by passing through `cleanfile()`.  Changing this locally seemed to work for many different configuration targets and seems to produce the intended value in `$d`, although I couldn't be sure (thus I haven't prepared a PR).

**Comment by zhzhzoo-autra** [comment]
I agree with bspencer. https://github.com/openssl/openssl/pull/23482/files#diff-6defafa2caa65304173956e3fbc26b6947c50bc769c08c3da32c1032fa6519d4 solved the problem for me. And I think https://github.com/openssl/openssl/commit/b8e98c34170fad3080d2b053a872719634404d43 did not actually fix the root cause of the problem.

**Comment by levitte** [comment]
I agree, that does look pretty odd.

Also, there are actually more bugs in there.  For paths that are known to be directories, `cleandir` should be used rather than `cleanfile`

**Comment by levitte** [comment]
Please try #23500

**Comment by levitte** [comment]
... and apologies for the wait.  For some reason, this went under my radar for a bit.
