### ISSUE TITLE
On VMS with 64-bit pointers: No "64" in OSSL$INSTROOT:[SYS$STARTUP] DCL scripts

### ISSUE THREAD

**Issue by Antinode-org** [openssl/openssl#22899]
OpenSSL version 3.0.7, 3.0.12, and, I assume, many others. 
(Inspection suggests that 3.2.0 is similarly afflicted, so I'd guess
that 3.1.x is, too, as well as older ones.)

   On VMS, in a build with 64-bit pointers, various file specs and
logical names in the OSSL$INSTROOT:[SYS$STARTUP] DCL scripts are not
getting the desired/expected "64" modifier.  Many things fail when the
wrong ("64"-less) names are used.

   Cause: Error in templates for OSSL$INSTROOT:[SYS$STARTUP] DCL
scripts:

      [.VMS]openssl_ivp^.com.in
      [.VMS]openssl_shutdown^.com.in
      [.VMS]openssl_startup^.com.in:

   In each of these "*^.com.in" templates:

$       pz   := {- $target{pointer_size} -}

should be:

$       pz   := {- $config{pointer_size} -}

(Compare "pz" with, for example, "OPENSSLDIR" in
"[.VMS]openssl_startup^.com.in".  Refer to "[]vmsconfig.pm" to see where
"pointer_size" really is.)

   Note: The actual _files_ (.OLB, .EXE) are created with the "64" in
their names; only the OSSL$INSTROOT:[SYS$STARTUP] DCL scripts which
(should) point to them are wrong.

--------

   While we're looking at VMS stuff, here's an unrelated complaint:

   Some VMS-specific code uses obsolete conditions like:

      # ifdef __alpha
      #if defined __alpha

which, I'd venture, should be replaced by things like, say:

      # ifndef __VAX
      $if !defined __VAX

   For many purposes, the VMS world is divided into (1) VAX and
(2) everything after VAX (Alpha, IA64, x86_64, ...).  In almost all
cases, testing for VAX makes more sense than testing for any particular
post-VAX architecture (such as "__alpha").

      [.apps.lib]vms_term_sock.c
      [.providers.implementations.rands.seeding]rand_vms.c

--------

   Around here:

   ITS $ @ config -64 --prefix=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.3_0_12-64z] - 
   _ITS $  --openssldir=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.3_0_12-64z]

   ITS $ mms
   ITS $ mms test
   ITS $ mms install

   ITS $ tcpip show version ! (Not that it matters much)

     HP TCP/IP Services for OpenVMS Industry Standard 64 Version V5.7 - ECO 5
     on an HP rx2600  (1.50GHz/6.0MB) running OpenVMS V8.4-2L3

   ITS $ cc /version

   VSI C V7.4-001 on OpenVMS IA64 V8.4-2L3

**Comment by jamuir** [comment]
@levitte , do you have any VMS-related suggestions here?

**Comment by Antinode-org** [comment]
>    For many purposes, the VMS world is divided into (1) VAX and
> (2) everything after VAX (Alpha, IA64, x86_64, ...). [...]

   This is true for vms_term_sock.c, but rand_vms.c is more complicated. 
In rand_vms.c, the "#if defined __alpha" conditions may be correct, but
the "#if defined __ia64" might want to include __x86_64 as well.  (Or be
replaced by "#if !defined __VAX && !defined __alpha".)

   _My_ suggestions should be available at/under: http://antinode.info/ftp/openssl/3_0_12/

**Comment by levitte** [comment]
I frankly haven't looked at the pointer-size issue for some time, and things have slipped.  Full admission.

I do have it on my personal TODO list to take a closer look at this again.  Thanks, @Antinode-org, for the reminder and the pointers, they will certainly help.

**Comment by levitte** [comment]
Re rand_vms.c, I fully expected SYS$GET_ENTROPY to be present on x86_64, so the data collection method shouldn't be relevant there.  I do not know, though, 'cause I've only just started building on x86_64, and am encountering other building issues that I've had some trouble figuring out

**Comment by Antinode-org** [comment]
> [...] I fully expected SYS$GET_ENTROPY to be present on x86_64, [...]

   I was too lazy to figure out when which method gets used, and it
looked easy enough to adjust the old one to work everyplace.

> [...] am encountering other building issues that I've had some trouble
> figuring out

   With my weak psychic powers, there's not much I can do with "other
building issues" as a problem description.  With my changes, the worst I
saw were a couple of %CC-I-IMPLICITFUNC (socket_fd and getpid -- header
files not included), and a typical assortment of %CC-I-QUESTCOMPARE,
where some type or other is unsigned on VMS.

   I haven't been keeping my x86_64 software up to date, so I used:

V87 $ cc /version
VSI C X7.4-785 (GEM 50X65) on OpenVMS x86_64 V9.2-1  

and I haven't yet installed the available OS update kits.

**Comment by levitte** [comment]
> > [...] I fully expected SYS$GET_ENTROPY to be present on x86_64, [...]
> 
> I was too lazy to figure out when which method gets used, and it looked easy enough to adjust the old one to work everyplace.
> 
> > [...] am encountering other building issues that I've had some trouble
> > figuring out
> 
> With my weak psychic powers, there's not much I can do with "other building issues" as a problem description.

At the time I wrote that, I didn't remember the details.  I do now.  Here's the trouble I stumble into:

```
LIBRARY/CREATE/OBJECT OSSL$libcrypto.OLB
...
LIBRARY/REPLACE OSSL$libcrypto.OLB [.providers.implementations.ciphers]libdefault-lib-cipher_aes_ocb.OBJ
%LIBRAR-E-DUPGLOBAL, global symbol aes_ocb_cipher from file USER:[LEVITTE.WRK._OPENSSL-3_3_0-DEV-X86_64.providers.implementations.ciphers]libdefault-lib-cipher_aes_ocb.OBJ;2 already in library USER:[LEVITTE.WRK._OPENSSL-3_3_0-DEV-X86_64]OSSL$LIBCRYPTO.OLB
%MMS-F-ABORT, For target OSSL$LIBCRYPTO.OLB, CLI returned abort status: %X108680B2.
%MMS-F-ABORT, For target BUILD_SW, CLI returned abort status: %X10EE8034.
```

It is true that this particular symbol exists in two places, but...:

``` console
$ git grep ' aes_ocb_cipher('
crypto/evp/e_aes.c:static int aes_ocb_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out,
providers/implementations/ciphers/cipher_aes_ocb.c:static int aes_ocb_cipher(void *vctx, unsigned char *out, size_t *outl,
```

... considering they're *static*, I'm a bit stumped, can't quite figure out why they became global.  As building issues go, this one got the better of me for the moment.

(I'm still trying to put together a small example that reproduces this, to make a simple bug report...  but alas, it eludes me)

This is, BTW, with a fully updated kit:

``` console
$ cc/version                                                                   
VSI C x86-64 X7.4-843 (GEM 50XB9) on OpenVMS x86_64 V9.2-1  
```

**Comment by levitte** [comment]
Re my LIBRARY issue, I just saw on VSI's forum that someone else has reported that same issue, with a working reproducer.  I'll work my way from there

**Comment by levitte** [comment]
Regarding the `$target{pointer_size}` vs `$config{pointer_size}`, the move to using the former was deliberate: e30545e9bd84e3ace70fb1e1c5ad6d824545fe36

However, it seems that build of vmsconfig.pm wasn't adapted accordingly, which is the cause of the discrepancy you see.  So, I'll propose a different change to try (coming up in a few)

**Comment by levitte** [comment]
@Antinode-org, #23081 is my proposed fix for the main issue you reported here.  It's in draft pending tests, but may be worth having a look at and try out?

Not sure how comfortable you are with git, so I'm attaching a tarball with the modified files as well:

[fix-22899.tar.gz](https://github.com/openssl/openssl/files/13703588/fix-22899.tar.gz)

**Comment by Antinode-org** [comment]
> Re my LIBRARY issue, I just saw on VSI's forum [...]

   Yeah, %LIBRAR-E-DUPGLOBAL was instantly recognizable.  I've been
following that VSI forum thread, but my software-update laziness seems
to have protected me from that problem, so far.

> Not sure how comfortable you are with git, [...]

   Less than I should be, I'm sure.

> fix-22899.tar.gz

   Thanks.  That seems to work on IA64.  On x86_64,
Configurations/10-main.conf still needs some help.  (Add sections for
"vms-x86_64-p32" and "vms-x86_64-p64", else "@ config -32" or
"@ config -64" fails on x86_64.)  My x86_64 build is still running, but
I expect it to work.

   Also, I claim that apps/lib/vms_term_sock.c should use <iosbdef.h> on
all post-VAX architectures, not only Alpha, but that's more of an
esthetic problem than a practical one.

http://antinode.info/ftp/openssl/3_0_12/apps/lib/vms_term_sock.c
http://antinode.info/ftp/openssl/3_0_12/Configurations/10-main.conf

**Comment by levitte** [comment]
Regarding preprocessor selectors, there's really no need to check for `__VAX`, as we've dropped support for VAX builds a long time ago.  Remaining VAX stuff is really just that, remains of a time passed.  So regarding the iosb fixup, the condition can be safely removed altogether.

**Comment by Antinode-org** [comment]
> [...] I expect it to work.

   And it did, eventually, which should shut me up for a while.  Thanks.

**Comment by levitte** [comment]
I'll raise another issue for the cleanups to be done that have been mentioned here
