### ISSUE TITLE
We're not treating read-only source trees very well

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#22907]
See #22841, where this turned out to be the source problem.

It was seen as quite important that the source tree should remain untouched during a normal build, test and install, at least when building out-of-source (separate build tree).
There are environments where this is important, and taken so far that the source tree is to be on a disk that's mounted read-only, or made read-only in some other way (that's the bottom line case in #22841).

This is, unfortunately, untested, and seems to have been forgotten over time, and should be restored in my opinion.

Two things would need to happen:

- Add a workflow that makes the checkout source tree read-only, and try to build, test, and install from a separate build tree.
- Fix whatever ends up trying to write in the source tree.

**Comment by togtalk** [comment]
في السبت، ٢ ديسمبر ٢٠٢٣ ١:٠١ م Richard Levitte ***@***.***>
كتب:
