### ISSUE TITLE
OSSL_PARAM_locate called ~500 times per session. is it ok?

### ISSUE THREAD

**Issue by vitalyk-radware** [openssl/openssl#22923]
hi,
 we see that in openssl 3.1.4 s_server, for each client connection we get 485 (or more) calls to the function OSSL_PARAM_locate .
 there is a performance cost of these calls, and they were not present in openssl 1.1 .
 the question is - what may be done to reduce this cost? 

thank you!
p.s. the same question is about OPENSSL_LH_retrieve that is being called very many times

**Comment by nhorman** [comment]
Need to:

- [ ] Reproduce the problem with openssl s_server to validate that we do in fact call OSSL_PARAM_locate and OPENSSL_LH_retireve  that frequently
- [ ] Need to characterize the performance impact of doing so
- [ ] Investigate approaches to reducing the number of calls to those functions and/or their per-call overhaead (assuming the above is validated)
- [ ] Implement a fix based on the investigation above

**Comment by nhorman** [comment]
Notes:
 Can confirm that a connection to s_server results in 407 passes through OSSL_PARAM_locate, mostly originating from call paths through EVP_CIPHER_CTX_get_[key|iv]_length.  There are simmilar numbers of calls to OPENSSL__LH_retrieve (likely from ossl_method_store_cache_get).
that said, profiling with sprof shows the following:
```
 25.13  21013.79 21013.79        0     0.00           ossl_sm2_decrypt
 18.70  36652.81 15639.02        0     0.00           ossl_sm2_compute_z_digest
 12.32  46950.08 10297.27        0     0.00           sm2_sig_gen
  8.07  53696.57  6746.49        0     0.00           ossl_sm3_block_data_order
  7.54  60000.20  6303.63        0     0.00           ossl_sm2_encrypt
  7.21  66024.63  6024.43        0     0.00           sm2_sig_verify
  6.49  71447.78  5423.15        0     0.00           sm2_compute_msg_hash
  4.89  75535.22  4087.44        0     0.00           ossl_sm2_internal_sign
  4.85  79591.65  4056.43        0     0.00           ossl_sm2_internal_verify
  2.32  81527.53  1935.88        0     0.00           ossl_sm2_key_private_check
  0.91  82291.56   764.03        0     0.00           ossl_sm3_init
  0.64  82826.44   534.88        0     0.00           ossl_sm2_do_sign
  0.32  83097.24   270.80        0     0.00           ossl_sm2_do_verify
  0.28  83332.49   235.25        0     0.00           sm3_int_final
  0.25  83544.17   211.68        0     0.00           ossl_err_load_SM2_strings
  0.08  83610.78    66.61        0     0.00           sm3_int_update
```

The sprof output shows that there is a negligble impact of these calls on the run time of s_server

Is there a particular performance issue you are encountering here?

**Comment by paulidale** [comment]
is a [design](https://github.com/openssl/openssl/blob/master/doc/designs/fast-param-find.md) to improve this.  Not actioned yet outside of GCM mode ciphers.

**Comment by t8m** [comment]
@nhorman It is interesting that you see sm2 decryption in the profile - we do not have SM2 support in TLS, how this is possible?

**Comment by nhorman** [comment]
Hmm, that is odd.  Data was gathered with sprof, not sure what could have gone wrong.  Let me run it again

**Comment by nhorman** [comment]
ah, thats odd, building libcrypto.so with the default -O3 and -pg seemed to be throwing sprof for a loop.  building without -pg corrects that it seems.  The proper profiling data seems to be:

```
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  us/call  us/call  name
 10.82   8963.66  8963.66        0     0.00           X509_aux_print
  8.35  15876.36  6912.70        0     0.00           make_addressRange
  7.62  22190.56  6314.20        0     0.00           i2r_IPAddrBlocks
  6.32  27424.05  5233.49        0     0.00           i2r_address
  5.99  32386.84  4962.79        0     0.00           X509_ocspid_print
  5.38  36845.74  4458.90        0     0.00           range_should_be_prefix
  5.29  41226.29  4380.55        0     0.00           X509_STORE_CTX_print_verify_cb
  5.10  45448.62  4222.33        0     0.00           X509_signature_print
  4.51  49183.73  3735.11        0     0.00           ossl_x509_print_ex_brief
  4.31  52756.40  3572.67        0     0.00           make_addressPrefix
  3.72  55838.30  3081.90        0     0.00           X509_signature_dump
  3.62  58838.57  3000.27        0     0.00           IPAddressOrRange_cmp
  3.44  61692.01  2853.44        0     0.00           make_IPAddressFamily
  2.71  63939.74  2247.73        0     0.00           print_certs
  2.60  66095.05  2155.31        0     0.00           addr_expand
  2.25  67954.88  1859.83        0     0.00           i2r_IPAddressOrRanges
  2.23  69799.05  1844.17        0     0.00           make_prefix_or_range
  1.44  70994.20  1195.15        0     0.00           d2i_IPAddressOrRange
  1.43  72177.32  1183.12        0     0.00           i2d_IPAddressChoice
  1.40  73339.77  1162.45        0     0.00           X509v3_addr_add_inherit
  1.29  74406.55  1066.78        0     0.00           print_store_certs
  0.77  75042.14   635.59        0     0.00           lh_MEM_cfn_thunk
  0.74  75654.39   612.25        0     0.00           d2i_IPAddressRange
  0.72  76250.90   596.51        0     0.00           i2d_IPAddressRange
  0.72  76847.08   596.18        0     0.00           IPAddressRange_free
  0.72  77442.94   595.86        0     0.00           i2d_IPAddressOrRange
  0.71  78027.34   584.40        0     0.00           ossl_check_IPAddressOrRange_sk_type
  0.69  78601.97   574.63        0     0.00           IPAddressChoice_free
  0.69  79175.94   573.97        0     0.00           d2i_IPAddressFamily
  0.59  79663.77   487.83        0     0.00           v6IPAddressOrRange_cmp
  0.54  80113.79   450.02        0     0.00           IPAddressFamily_free
  0.53  80555.48   441.69        0     0.00           ossl_check_const_IPAddressFamily_sk_type
```

tough its still interesting that the call counts don't seem accurate (which I think may be an artifact of the fact that s_server is terminated with a SIGINT)   This looks much better though, and continues to suggest the numerous calls to OSSL_PARAM_locate produce negligible impact

**Comment by t8m** [comment]
This still looks weird - why would these particular functions take the most time. Is this because they are blocked on the stdout output??

**Comment by t8m** [comment]
IMO we should use the proper benchmark (the tls handshake one) for profiling.

**Comment by nhorman** [comment]
Not sure where this leave us.  We are conducting profiling runs in https://github.com/openssl/project/issues/579

So, I'm not sure whats left to do here, as the question was "Is calling OSSL_PARAM_locate 500 times per session a performance impact"?

I suppose the right thing to do is, as an adjunct of https://github.com/openssl/project/issues/579, look at the data and see if that function appears on any profiling data, and answer the question

**Comment by nhorman** [comment]
based on the handshake test results here https://github.com/openssl/project/issues/577, we can see that, while performance from 1.1 to 3.3 has dropped, between 3.0 and 3.3 we have improved significantly.  I think the answer to the above question is that, yes, its ok to make that many calls, and its likely that there is not much we can do to limit the number given the api design
