### ISSUE TITLE
OPENSSL_cleanup() emits error due to decoder cache flush after it has been freed 

### ISSUE THREAD

**Issue by Futaura** [openssl/openssl#22939]
This could be a bug or a complete non-issue, but I thought it was worth mentioning my obervations on behaviour I stumbled upon while porting OpenSSL 3.2.0 for use in AmiSSL. It has never been an issue in any previous version of OpenSSL, but since 3.2.0 I noticed `OPENSSL_cleanup()` has started generating errors (although you don't tend to see them because `err_cleanup()` is called before OPENSSL_cleanup()) completes).

I has been hard to trace the exact flow of the code, but basically this code is first executed by `OPENSSL_cleanup()`:

https://github.com/openssl/openssl/blob/7ebaab7689f66ede1f960c42be3446922e3f5e21/crypto/context.c#L245-L248

This frees the decoder cache and shortly after the following is executed:

https://github.com/openssl/openssl/blob/7ebaab7689f66ede1f960c42be3446922e3f5e21/crypto/context.c#L264-L268

During `ossl_provider_store_free()`, it calls `provider_deactivate()` and this in turn calls `ossl_decoder_cache_flush()` which emits an error because the cache was already previously freed by `ossl_decoder_cache_free()`.

I only happened to notice it because AmiSSL calls `OpenSSL_cleanup()` after thread related data relating to `errno` had been freed, resulting in a crash (reference to freed memory).

**Comment by t8m** [comment]
I think the right fix is to just drop the problematic ERR_raise() call from ossl_decoder_cache_flush().
