### ISSUE TITLE
KU_* and X509v3_KU_* constants are redundant

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#22955]
OpenSSL currently defines two sets of identical constants:
https://github.com/openssl/openssl/blob/master/include/openssl/x509.h.in#L70-L79
https://github.com/openssl/openssl/blob/master/include/openssl/x509v3.h.in#L425-L433

Except that one set has `X509v3_KU_UNDEF`. Most code uses the `KU_*` ones within the library, but some actually use `X509v3_KU_*`.

Interestingly, the `X509v3_KU_*` ones are actually older. They date to the SSLeay:
https://github.com/openssl/openssl/blob/58964a492275ca9a59a0cd9c8155cb2491b4b909/crypto/x509/v3_x509.c#L105
https://github.com/openssl/openssl/blob/58964a492275ca9a59a0cd9c8155cb2491b4b909/crypto/x509/v3_x509.c#L134

The unprefixed ones were added later in https://github.com/openssl/openssl/commit/673b102c5b265bd6c517ac40ab76e1606a243c08

I'm guessing this was simply a mistake and no one noticed the constants already existed. Also interesting is that `X509v3_get_key_usage` returns `X509v3_KU_UNDEF` (0xffff) when the extension isn't present. Now that constant isn't used. `X509v3_get_key_usage` is long since gone, but a very similar function `X509_get_key_usage`, now exists. That one, however, returns `UINT32_MAX` (0xffffffff) when the extension isn't present.

It is... unclear which would have been better. On the one hand, `X509_get_key_usage` returns `uint32_t`, so it makes sense to assert all ones as a `uint32_t` when unconstrained. However, both `X509_get_key_usage` and the old `X509v3_get_key_usage` only look at the first 16 bits of keyUsage, so `X509v3_KU_UNDEF` arguably matches the other behavior better. It's weird that a hypothetical bit 27 would be returned in the unconstrained case but not when explicitly listed.

I would suggest:
* Align on `X509v3_KU_*` just because it's a bit better namespaced than `KU_*` and deprecate the others.
* Keep returning `UINT32_MAX`. That ship has probably sailed.
* Deprecate `X509v3_KU_UNDEF` because it's meaningless now.

**Comment by t8m** [comment]
**OTC: Do we want to follow the above suggestion and for which branches?**

**Comment by davidben** [comment]
Oh, another reason to prefer the `X509v3_KU_*` constants is that they actually collide with another project! NSS defines the same `KU_*` constants. Thankfully with the same values, but it will trigger warnings about redefined macros in projects that include both headers together.
https://github.com/nss-dev/nss/blob/ecab6a135bda33b8ea3aa887dd9944a8dcb27129/lib/certdb/certt.h#L562-L569

**Comment by t8m** [comment]
**OTC: We do not want to explicitly deprecate these KU_ constants because it would potentially break many applications with no-deprecated builds. However we should clean up our code to not use these constants and make sure they are aliases of the X509v3_KU_ constants. We could also define the KU_ constants only when they aren't defined yet. The documentation needs to be updated as well.**

**Comment by vdukhovni** [comment]
Note that the KU_ constants are also in use some external packages, I don't see a compelling need to urgently deprecate these, but defining one set in terms of the other makes sense.

Therefore, I also don't see a benefit to using the longer `X509v3_`-prefixed names internally, this introduces code churn and forces folding of code lines, with little tangible benefit.  If some day the `KU_` constants are in-fact deprecated, we can switch the `KU_` to be internal constants.

As for `X509v3_KU_UNDEF`, it is used in [Rust's OpenSSL API](https://docs.rs/openssl-sys/latest/openssl_sys/constant.X509v3_KU_UNDEF.html), to little harm. I am not inclined to force code churn in external APIs, unless the benefit is demonstrable.

**Comment by davidben** [comment]
> As for X509v3_KU_UNDEF, it is used in [Rust's OpenSSL API](https://docs.rs/openssl-sys/latest/openssl_sys/constant.X509v3_KU_UNDEF.html), to little harm. I am not inclined to force code churn in external APIs, unless the benefit is demonstrable.

They don't actually use that constant anywhere. Some background here is that this crate is split into `openssl` and `openssl-sys` crates. The latter would normally just be the output of `bindgen`, but due to wanting to support some old OpenSSLs, they ended up copy-pasting a bunch of function signatures, usually without too much attention to what they did and didn't use.

As for harm in keeping it around, it just confuses callers because `0xffff` is *not* what `X509v3_get_key_usage` returns when there is no key usage. That API returns `0xffffffff`. See the original report, which discusses this. I don't believe there is any use of that symbol that would be correct. It's not a coherent bitmask to construct a keyUsage extension out of, nor is it something you can check the output of an OpenSSL API against, when consuming a keyUsage extension.

**Comment by vdukhovni** [comment]
I agree the value is useless, but I am not convinced we should risk some external project failing to compile by removing it. We could document it as vestigial. I still don't see a pressing case for removal, but if there's zero risk of downstream impact, I am not opposed. It may still be prudent to separate deduplication of the definitions from removal of vestigial values.

**Comment by nhorman** [comment]
I understand the desire to not break downstream projects, but at some point, we need to have a mechanism to remove items that are vestigial.  My suggestion would be to wrap the duplicate defines in a:
```
#ifdef ENABLE_DUPLICATE_KU_CONSTANTS
```
macro or some such, so that enabling them is opt-in, and see who complains during the 3.4 development cycle.  Given that we are just at the start of 3.4, this is likely an optimal time to do this, as it maximizes soak time for potential users to complain.  Then during the 3.5 LTS release, starting in october, assuming no unsolvable complaints, we can remove them at will.
