### ISSUE TITLE
OpenSSL 3.1.4 DH performance implications

### ISSUE THREAD

**Issue by tvgpr** [openssl/openssl#22956]
Noticed huge difference in performance of DH operations between OpenSSL 1.1.1 and 3.1.x while gathering profiling data

Below is the output of  ``` openssl speed ffdh``` on OpenSSL 1.1.1j and OpenSSL 3.1.4. Is this kind of degradation expected in 3.1.4 due to the major architecture/design changes it went over or is it a performance issue in 3.1.4 that can be addressed?

```
Doing 2048 bits  ffdh's for 10s: 20010 2048-bits FFDH ops in 9.99s
Doing 3072 bits  ffdh's for 10s: 7880 3072-bits FFDH ops in 10.00s
Doing 4096 bits  ffdh's for 10s: 3765 4096-bits FFDH ops in 10.00s
Doing 6144 bits  ffdh's for 10s: 1658 6144-bits FFDH ops in 10.00s
Doing 8192 bits  ffdh's for 10s: 834 8192-bits FFDH ops in 10.00s
version: 3.1.4
built on: Mon Dec  4 17:09:54 2023 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0xfffa3203478bffff:0x7a9
                       op     op/s
2048 bits ffdh   0.0005s   2003.0
3072 bits ffdh   0.0013s    788.0
4096 bits ffdh   0.0027s    376.5
6144 bits ffdh   0.0060s    165.8
8192 bits ffdh   0.0120s     83.4
```

```
Doing 2048 bits  dh's for 10s: 468331 2048-bit DH ops in 9.99s
Doing 3072 bits  dh's for 10s: 215150 3072-bit DH ops in 9.99s
Doing 4096 bits  dh's for 10s: 165073 4096-bit DH ops in 9.99s
Doing 5120 bits  dh's for 10s: 55888 5120-bit DH ops in 9.99s
OpenSSL 1.1.1j  16 Feb 2021
built on: Mon Dec 4 15:25:08 2023 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
```

**Comment by jamuir** [comment]
What platform are you testing?

Note that the output you provided shows that the options used to build 1.1.1j and 3.1.4 are quite different.

It looks like your build of 1.1.1j uses more performant code, as per the flags `-DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5`.

**Comment by tvgpr** [comment]
Platform is linux-x86_64

I haven't specified any additional options while building 1.1.1j & 3.1.4. Did the default configure options change between 1.1.1j & 3.1.4?

```
./config --prefix=XXX --openssldir=XXX
make
make install
```

**Comment by jamuir** [comment]
I tried building 1.1.1j and 3.1.4 and the compile flags I see printed by `openssl speed` are consistent with the ones you posted.

What command did you test dh against 1.1.1j?

`openssl speed ffdh` works against 3.1.4, but not against 1.1.1j.

**Comment by tvgpr** [comment]
Forgot to mention about DH test agains 1.1.1j. I have added the code in speed.c for that. Here is the patch for the code.

[t.patch](https://github.com/openssl/openssl/files/13588435/t.patch)
