### ISSUE TITLE
OPENSSL_showfatal uses the fmt variable uninitialized

### ISSUE THREAD

**Issue by randomswdev** [openssl/openssl#2296]
In OPENSSL_showfatal (openssl/crypto/cryptlib.c), when it si defined STD_ERROR_HANDLE, the first call to _vsnprintf uses the variable fmt uninitialized, causing a failure of the library.

**Comment by levitte** [comment]
Which OpenSSL version are you refering to?

**Comment by randomswdev** [comment]
It is the FIPS stable version. In particular this file:

https://github.com/openssl/openssl/blob/OpenSSL-fips-2_0-stable/crypto/cryptlib.c

**Comment by jselbie** [comment]
Around line 300 of cryptlib.c:

    len=_vsnprintf((char *)buf,sizeof(buf),fmt,ap);

Should be "fmta" instead of "fmt"

    len=_vsnprintf((char *)buf,sizeof(buf),fmta,ap);

**Comment by richsalz** [comment]
ping @snhenson

**Comment by jselbie** [comment]
This was already fixed in the dev branch.

https://github.com/openssl/openssl/commit/493119b1a81ccd447a88654cbc95aaab73289d85

https://github.com/openssl/openssl/blob/OpenSSL-fips-2_0-dev/crypto/cryptlib.c

**Comment by mattcaswell** [comment]
Fixed in dev. Closing.
