### ISSUE TITLE
Move ossl_asn1_string_to_time_t() to libtestutil?

### ISSUE THREAD

**Issue by Futaura** [openssl/openssl#22965]
Not a bug per se, but a trivial observation... Would it not make more sense to locate the `ossl_asn1_string_to_time_t()` function in `libtestutil` instead of `libcrypto`? It is currently only used by tests and not by anything in libcrypto, Tests do not necessarily have access to this function normally as it is an internal function of libcrypto (would avoid having to forcibly link the involved tested with the static libcrypto).

**Comment by coolshrid** [comment]
Where should this new function be placed in `libtestutil`? Can I create a new .c/.h file and move the `ossl_asn1_string_to_time_t` to this new file?

**Comment by t8m** [comment]
Create a new .c file in test/testutil and add the prototype to test/testutil.h. Probably good idea to also rename the function to test_asn1_string_to_time_t() or something like that.

**Comment by coolshrid** [comment]
created a new file called `testutil/helper.c` and moved the function and renamed it to `test_asn1_string_to_time_t` from `ossl_asn1_string_to_time_t`.

**Comment by coolshrid** [comment]
Fixed code formatting issues.
