### ISSUE TITLE
openssl 3.2 pkcs12 regression - requires configuration

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#22994]
Regression projects pkix-ssh and e_nss tests create pkcs#12 files. Since about 20 years for first time OpenSSL 3.2 fail to create pkcs#12 file with utility from build directory.

----
Sample from e_nss:
```
...
creating client pkcs#12 (rsa) ...
Can't open "..../openssl64/3.2.0_stable_inplace/ssl/openssl.cnf" for reading, No such file or directory
C085E75B817F0000:error:80000002:system library:BIO_new_file:No such file or directory:crypto/bio/bss_file.c:67:calling fopen(..../openssl64/3.2.0_stable_inplace/ssl/openssl.cnf, r)
C085E75B817F0000:error:10000080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:75:
...
```
```sh
...
  ( cat ../$N-priv.pem
    cat ../$N-cert.pem
    cat ./crt/level1.crt.pem
    cat ./crt/root0.crt.pem
  ) | \
  $OPENSSL pkcs12 -export \
    -passin $keypass -passout $p12pass \
    -out $TMPDIR/$N.p12
...
```

**Comment by nhorman** [comment]
It looks like your config file is missing or unreadable.  Have you checked the readability of the path elements leading to your openssl.cnf file?

**Comment by petrovr** [comment]
Neil Horman wrote:
> It looks like your config file is missing or unreadable.  Have you checked the readability of the path elements leading to your openssl.cnf file?
> 

OMG. I thy to explain differently...

All releases before 3.2 allows to test without to install cryptographic library. For instance is used wrapper script to run an openssl utility.
"openssl 3.2 pkcs12 regression - requires configuration" i.e., 3.2 unlike version before requires configuration file in installation location.


Regards,
Roumen Petrov

**Comment by nhorman** [comment]
I think we you say "install cryptographic library" what you mean is that sometime prior to 3.2 the openssl pkcs12 applet could be used without the presence of a configuration file, correct?

If so, yes, that was added intentionally in commit e869c867c1c405de3b6538586f17b67937556a4b, when the ability to specify pkcs12 bag attributes was added.

I'm not sure how to proceed with this.  It would be easy enough to make attribute parsing conditional on config file load, but its unclear as to weather or not config file presence is mandated as part of an installation

**Comment by nhorman** [comment]
OTC: Is the functionality of openssl apps contingent on a configuration file being present?

**Comment by t8m** [comment]
@nhorman IMO this is just a bug. We should have reverted the config file loading addition that happened as part of https://github.com/openssl/openssl/commit/e869c867c1c405de3b6538586f17b67937556a4b when this was changed to be an option instead of a config file thing in 21f7a09.

**Comment by t8m** [comment]
@petrovr Fix in #23005

**Comment by nhorman** [comment]
I'm agree with the fix (its clear thats what we should do here in isolation, since the option in question no longer exists), but I think the question should be answered in general: Do we require a config file to be present for using the openssl application?  This has implications for users, i.e. if we don't require a config file, and a user inadvertently places a config file in a non-standard location, the result is configuration settings get ignored.

**Comment by t8m** [comment]
We currently do not require a config file anywhere except for the certificate request/signing and this requirement in pkcs12 was added inadvertently. If anything it would have to be done properly - i.e. documented in the manpage and CHANGES.md, etc.
