### ISSUE TITLE
How to disable dlopen?

### ISSUE THREAD

**Issue by Gaobo-Hp1** [openssl/openssl#23002]
Hello, 
I build openssl into a static lib, 
the `configure command` is :
![eff04b7e28286dcaf96313fda8d7aaa8](https://github.com/openssl/openssl/assets/69666438/129e133d-4a6b-426d-ba8e-37d3f609f254)

i add `no-dso` and `no-engine`,  i wan't it not invoke `dlopen`, because i get the `libssl.a` and `libcrypto.a`.
then i have a project that static link thel ibrary, and build the project by emscripten(wasm). 
when i run it at browser, i got this error:
![image](https://github.com/openssl/openssl/assets/69666438/1b3b49b5-1e59-4be0-af43-e87acb5c2908)

i watched the trace of call, 
![e5e1ffe6a7acd8152f66a5e166656e32564592667d6591c7252233880aa2b603QzpcVXNlcnNcQWRtaW5cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDY4NTg1OTQwNF92MlxJbWFnZUZpbGVzXDE3MDIyODc0Mzg4OTBfMUU4NDY1RTctQzkwOC00OWU2LUJCQjItNEVEQjc4QTYyRTVDLnBuZw==](https://github.com/openssl/openssl/assets/69666438/7aa4b81b-2ba4-4c7e-a8f7-6017d3c07b4c)

why? why `no-dso`、`no-engine` useless?

**Comment by Gaobo-Hp1** [comment]
> What does your file `include/crypto/dso_conf.h` look like?

![image](https://github.com/openssl/openssl/assets/69666438/78c0d33c-7260-42a5-a6da-28bf85e351fd)

sry, i miss the version of openssl, my version is 1.1.1

**Comment by mattcaswell** [comment]
If I build 1.1.1 with the no-dso option, my dso_conf.h file looks very different:

```` C
/* WARNING: do not edit! */
/* Generated by Makefile from include/crypto/dso_conf.h.in */
/*
 * Copyright 2016-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OSSL_CRYPTO_DSO_CONF_H
# define OSSL_CRYPTO_DSO_CONF_H
# define DSO_NONE
# define DSO_EXTENSION ".so"
#endif
````

So, it looks to me like the "no-dso" you passed didn't take for some reason.

**Comment by Gaobo-Hp1** [comment]
> based on the stack trace, the dso_scheme is set to dlfcn. Looking at the 10-main.conf template it appears that x86_64 builds all inherit from linux-generic64 platform template, which in turn inherits from linux-generic32, which sets the dso_scheme to dlfcn.
> 
> I'm not sure if those can be overridden on the Configure command line, but an in field workaround would be to edit 10-main.conf and explicitly set your dso_schemem="" to force the definition of DSO_NONE, which will build the null DSO loader method

![image](https://github.com/openssl/openssl/assets/69666438/6946b3d7-48fe-4bf1-9391-1b9b0bcf6823)
thx for your reply,
Is that mean i need replace "dlfcn" to "" ?

**Comment by Gaobo-Hp1** [comment]
> What is the output from running `perl configdata.pm --dump` in the top level directory?

Thx for your reply.
This one is complier by my co-worker, so i need to ask him tomorrow. 

> perl configdata.pm --dump

And What is the purpose of this statement. Because by the time I get back to you tomorrow, you'll probably already be resting.
So you can tell me in advance what I can see from the result of this statement. 
Thx :)

**Comment by mattcaswell** [comment]
This will dump a lot of information about how OpenSSL believes it is has been configured. I am mostly interested in the "no-dso" option trying to figure out why it hasn't resulted in the expected output in include/crypto/dso_conf.h

If I configure without the "no-dso" option, I can see certain lines in my perl configdata.pm --dump output:

````
$ perl configdata.pm --dump | grep dso
    dso
    dso_extension => ".so",
    dso_scheme => "dlfcn",
````
But, if I configure with the "no-dso" option, the output looks different:

````
$ perl configdata.pm --dump | grep dso
    /usr/bin/perl ./Configure linux-x86_64 --debug --strict-warnings no-dso
    dso                     [option]  OPENSSL_NO_DSO
    dso_extension => ".so",
    dso_scheme => "dlfcn",
````

We are seeking to learn whether no-dso has been correctly reflected in the configdata.pm or not.

If it has then I would turn our attention to why the build scripts have apparently ignored the configuration and built for dlfcn anyway. If it has not, I would turn our attention to why not (which would probably point to your build scripts).
