### ISSUE TITLE
[OpenSSL 3.2 - SSL - wpacket] wpacket default length is not correct, leads to dropped https requests 

### ISSUE THREAD

**Issue by LAc1985** [openssl/openssl#23015]
Hello,

**background:**
We are using a 4 aligned system and we have memory pools there.
OpenSSL 3.2 is integrated.
I set the define in openssl like this: #define SSL3_ALIGN_PAYLOAD     4
We are using https.

**symptom:**
In an edge case we get an error from OpenSSL from here:

WPACKET_reserve_bytes
if (pkt->maxsize - pkt->written < len)

**traces:**

FL: tls_setup_write_buffer: defltlen1: 16472, max_frag_len: 16384, headerlen: 5, align: 3, eivlen: 0
FL: tls_setup_write_buffer: defltlen2: 16472
FL: tls_write_records_default: initialise_write_packets
FL: tls_initialise_write_packets_default 1: buf: 3970289788, len: 16472 type: 23
FL: tls_initialise_write_packets_default - align
FL: tls_initialise_write_packets_default - align1: 3970289788
FL: tls_initialise_write_packets_default - align2: 3970289793
FL: tls_initialise_write_packets_default - align3: 3
FL: tls_initialise_write_packets_default : buf: 3970289788, len: 16472
FL: WPACKET_init_static_len: maxsize: 16472, max: -1, len: 16472
 FL: WPACKET_reserve_bytes: max: 16472, written: 0, len: 3
 FL: WPACKET_reserve_bytes: max: 16472, written: 3, len: 1
 FL: WPACKET_reserve_bytes: max: 16472, written: 4, len: 2
 FL: WPACKET_reserve_bytes: max: 16472, written: 6, len: 2
 FL: WPACKET_reserve_bytes: max: 16472, written: 8, len: 16384
 FL: WPACKET_reserve_bytes: max: 16472, written: 8, len: 16384
 FL: WPACKET_reserve_bytes: max: 16472, written: 16392, len: 1
 FL: tls_write_records_default -  call preapre for encryption
 FL: WPACKET_reserve_bytes: max: 16472, written: 16393, len: 80
 FL: WPACKET_reserve_bytes return - 2
 FL: WPACKET_reserve_bytes  FAILED

**problem:**
In case when the align is maximal (in my case it is 3), then we will always fail at that check in WPACKET_reserve_bytes.
align + headers + data + _dont_know_ + overhead is bigger than the max length.
3 + 5 + 16384 + 1 + 80 = 16473 which is bigger than 16472.

**cause:**
I think the cause is that the default length calculation is not correct.
tls_setup_write_buffer
defltlen = rl->max_frag_len + SSL3_RT_SEND_MAX_ENCRYPTED_OVERHEAD
                   + headerlen + align + rl->eivlen;
In my traces I can see, that this plus 1 byte after the data (I marked it with _dont_know_) is not calculated into the default length.
If it should be the eivlen, then that is wrong. If not then it is just missing.

@mattcaswell What do you think about it?

Best regards,

Laszlo

**Comment by mattcaswell** [comment]
Is this 3.2 only? Or did you see this/test it in 3.1 or 3.0?

**Comment by LAc1985** [comment]
> Is this 3.2 only? Or did you see this/test it in 3.1 or 3.0?

We used OpenSSL 3.0 line earlier. We did not get such an errors. I never tried the 3.1 line.

**Comment by mattcaswell** [comment]
> plus 1 byte after the data (I marked it with dont_know)

I assume you are using TLSv1.3? There is an extra byte added after the data to indicate the content type in that protocol version.

Interestingly we have a test which should have caught this. I wonder why it didn't?

https://github.com/openssl/openssl/blob/6ebdbba76a45294e22006ede1442847cdee24f03/test/sslapitest.c#L1506-L1665

**Comment by LAc1985** [comment]
> > plus 1 byte after the data (I marked it with dont_know)
> 
> I assume you are using TLSv1.3? There is an extra byte added after the data to indicate the content type in that protocol version.
> 
> Interestingly we have a test which should have caught this. I wonder why it didn't?
> 
> https://github.com/openssl/openssl/blob/6ebdbba76a45294e22006ede1442847cdee24f03/test/sslapitest.c#L1506-L1665

Yes, it is TLSv1.3.
With 8 aligned memory pool buckets I also dont see this problem. So probably that is why you could not catch it.

**Comment by LAc1985** [comment]
> > With 8 aligned memory pool buckets I also dont see this problem. So probably that is why you could not catch it.
> 
> Ah. Do you explicitly define SSL3_ALIGN_PAYLOAD in your build? Do you run the tests afterwards? I just tried this with SSL3_ALIGN_PAYLOAD set to 4, and the test did actually fail. So it seems we don't ever normally run into platforms where its defined to something different than the default (otherwise we would have spotted this problem before).

Yes, I explicitly defined it.
No, the test are not integrated into our system.
