### ISSUE TITLE
Backport #21933 to 3.0 branch

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#23018]
https://github.com/openssl/openssl/pull/21933 needs backporting to 3.0 branch

**Comment by Liu-ErMeng** [comment]
> #21933 needs backporting to 3.0 branch

Hi @nhorman , what's the plan to do this operation(backport to 3.0 branch)? Or may I raise a PR to do this?

**Comment by nhorman** [comment]
If you have cycles to do the back port, I would certainly appreciate it
