### ISSUE TITLE
1.0.2k regression: util/domd fails on Solaris /bin/sh

### ISSUE THREAD

**Issue by mitchblank** [openssl/openssl#2302]
The #1370 PR from @orgads (see 62f16de2d17af4ac1f3df4622b7bec850b60820a) added a use of `if !` to the `util/domd` shellscript:

```
 +if ! cmp -s Makefile Makefile.new; then
 +    mv Makefile.new Makefile
 +else
 +    rm -f Makefile.new
 +fi
```

However, older versions of /bin/sh (like the one that comes with Solaris) doesn't support that:

```
making depend in ssl...
make[1]: Entering directory `/home/build/build-src/manual-build/contrib/openssl-1.0.2k/ssl'
../util/domd: !: not found
```

The simplest fix is probably just to reverse the `if` and `else` parts so the negation isn't needed.

cc @rsalz, @levitte

**Comment by makr** [comment]
Hi, I ran into this, too. The effect is that make depend runs without any change and a subsequent make then fails as it cannot find header files. Example: run Configure with no-idea, then make depend just reports above mentioned message and then make fails with

> 19:02:39 cc -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include -KPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -xtarget=generic64 -xtarget=ultra -xarch=v9 -xO5 -xstrconst -xdepend -Xa -DB_ENDIAN -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DGHASH_ASM  -c  e_bf.c
> 19:02:39 cc: Warning: -xarch=generic64 is deprecated, use -m64 to create 64-bit programs
> 19:02:39 cc: Warning: -xarch=v9 is deprecated, use -m64 to create 64-bit programs
> 19:02:39 make: Fatal error: Don't know how to make target '../../include/openssl/idea.h'
> 19:02:39 Current working directory /FS/xxx/workspace/OpenSSL_1.0.2_BuildUx/BIT_MODE/64/label/xxx/build/openssl-1.0.2k/crypto/evp

**Comment by levitte** [comment]
Please verify that #2303 fixes your issue.

**Comment by makr** [comment]
Yes, it does. Thanks!

**Comment by levitte** [comment]
Grand. Thanks
