### ISSUE TITLE
`SSL->session` double free after ssl3_send_alert()

### ISSUE THREAD

**Issue by citrus-it** [openssl/openssl#23031]
I recently upgraded an [OmniOS](https://omnios.org) system to a new release, which also upgraded OpenSSL from 3.0 to 3.1.
Since that upgrade, I have been seeing frequent crashes in Cyrus IMAP that I believe to be an issue with OpenSSL. It's of course possible that Cyrus is not correctly using the API but I haven't been able to spot anything there.

This is a system-provided OpenSSL package:

```
mailstore0# openssl version
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)
```

The following analysis is from a core file created while the application was running under the illumos libumem memory allocator, with debugging turned on.

The crash occurs when attempting to free an `SSL` structure via `SSL_free()`

```
fffffaffffdf8a60 libcrypto.so.3`CRYPTO_free_ex_data+0x4c()
fffffaffffdf8a80 libssl.so.3`SSL_SESSION_free+0x44()
fffffaffffdf8ab0 libssl.so.3`SSL_free+0x14e()
fffffaffffdf8ae0 libcyrus_imap.so.0.0.0`tls_reset_servertls+0x2b(46fcd0)
fffffaffffdf8b60 service_main+0x438(2, a34f20, fffffaffffdfb8a0)
fffffaffffdfb830 main+0x71c(2, fffffaffffdfb888, fffffaffffdfb8a0)
fffffaffffdfb860 _start_crt+0x87()
fffffaffffdfb870 _start+0x18()
```

The `SSL` object concerned was originally allocated by `SSL_new()`, as can be seen by looking at the allocation stack trace:

```
> 46fcd0/K | ::whatis
d87010 is d87000+10, allocated from umem_alloc_8192:
            ADDR          BUFADDR        TIMESTAMP           THREAD
                            CACHE          LASTLOG         CONTENTS
          d8aee0           d87000  10cdb04daa6b9b7                1
                           9d7028           8f3c00                0
                 libumem.so.1`umem_cache_alloc_debug+0x213
                 libumem.so.1`umem_cache_alloc+0xe3
                 libumem.so.1`umem_alloc+0x9f
                 libumem.so.1`umem_malloc+0x46
                 libcrypto.so.3`CRYPTO_zalloc+0x11
                 libssl.so.3`SSL_new+0x3b
                 libcyrus_imap.so.0.0.0`tls_start_servertls+0xaf
                 cmd_starttls+0x82
                 service_main+0x684
                 main+0x71c
                 _start_crt+0x87
                 _start+0x18
```

The crash occurs because `SSL->session` was previously freed in `ssl3_send_alert()`:

```
> 46fcd0/K | ::print SSL session | ::whatis
df9b50 is df9b40+10, freed from umem_alloc_1152:
            ADDR          BUFADDR        TIMESTAMP           THREAD
                            CACHE          LASTLOG         CONTENTS
          dfae00           df9b40  10cdb04e39240fa                1
                           9b8028           7e1c00                0
                 libumem.so.1`umem_cache_free_debug+0x16e
                 libumem.so.1`umem_cache_free+0x48
                 libumem.so.1`umem_free+0xb4
                 libumem.so.1`process_free+0x111
                 libumem.so.1`umem_malloc_free+0x1d
                 libssl.so.3`SSL_CTX_remove_session+0xee
                 libssl.so.3`ssl3_send_alert+0xdd
                 libssl.so.3`ossl_statem_fatal+0xb0
                 libssl.so.3`ssl3_read_n+0x405
                 libssl.so.3`ssl3_get_record+0xb5
                 libssl.so.3`ssl3_read_bytes+0x248
                 libssl.so.3`ssl3_read+0x60
                 libssl.so.3`SSL_read+0x29
                 libcyrus.so.0.0.0`prot_fill+0x19e
                 service_main+0x3b9
```

Looking at `ssl3_send_alert()`:

https://github.com/openssl/openssl/blob/58eeb4350ca89c52d603b42119a0893129a25c09/ssl/s3_msg.c#L60-L62

The call to `SSL_CTX_remove_session(s->session_ctx, s->session);` seems problematic as it is possible that `s->session` was freed if the reference count dropped to 0, but nothing sets `s->session = NULL`.

Please let me know if there is anything I can do to help track this down.

**Comment by mattcaswell** [comment]
> The call to SSL_CTX_remove_session(s->session_ctx, s->session); seems problematic as it is possible that s->session was freed if the reference count dropped to 0, but nothing sets s->session = NULL.

Hmmm. But this should never happen. The SSL object itself should be holding a reference, and the session cache held in `s->session_ctx` should also be holding a reference. Therefore the ref count should always be at least 2 prior to calling this function at this location.

Does Cyrus IMAP ever call `SSL_SESSION_free` directly? Plausibly if the ref count is decremented incorrectly, then it would not cause a problem at the site of the incorrect free call, but later on when `SSL_free` is called as you are experiencing.

**Comment by citrus-it** [comment]
Thanks for looking.

> Does Cyrus IMAP ever call `SSL_SESSION_free` directly?

It does, in a few places. I'll see if I can reproduce this by triggering `ssl3_send_alert()` and watch the reference - I'll report back when I have more data.

**Comment by citrus-it** [comment]
I am suspicious of a change fairly recently in Cyrus IMAP - https://github.com/cyrusimap/cyrus-imapd/commit/a3523d4067c502a52cb7ee859c1493d1a980b7e0
I am now running a build with this patch reverted. It was previously crashing several times a day so I'll be fairly confident if there are no crashes in the next 24 hours.

**Comment by t8m** [comment]
@citrus-it Yeah, that change is wrong. The SSL_SESSION objects are refcounted but the refcount is not bumped when this the remove_session_cb is called, so there should be no SSL_SESSION_free() call done. If they are seeing leaks under valgrind there is probably another case where there is a missing SSL_SESSION_free() call but this place is not right.

**Comment by citrus-it** [comment]
Thank you, and apologies for wrongly assuming this was a problem with OpenSSL. I've opened https://github.com/cyrusimap/cyrus-imapd/issues/4785 and will close this issue.
