### ISSUE TITLE
Some tests failed in windows mysys2-mingw

### ISSUE THREAD

**Issue by rainsdm** [openssl/openssl#23046]
I was compiling version v3.2.0 beta1, RELEASE_DATE="26 Oct 2023". 
Everything was successful, but after I tested my make result, it return some error infomation.
Then it reported some error infomation and it failed.
What should I do next?

The environment has listed in title.

Here's the stdout of `make test` : 
[output_error.txt](https://github.com/openssl/openssl/files/13673958/output_error.txt)

And this is my dump info:
`perl configdata.pm --dump`
[dump.txt](https://github.com/openssl/openssl/files/13673982/dump.txt)

Could anyone help me?

**Comment by t8m** [comment]
Could you please try the final 3.2.0 release?

**Comment by rainsdm** [comment]
> Could you please try the final 3.2.0 release?

I'll try it tomorrow. I just reinstalled mysys2. Give me some time pls. 

It spands from 1 to 2 hours each time. I don't have any automatic build script( I'm writing it ).

**Comment by rainsdm** [comment]
It looks like msys2 has already had openssl installation, and ca-certificates, curl, libcurl and libssh2 are dependent on it. So I can't uninstall it. But I still want to compile it to the 3.2.0 release.

**Comment by rainsdm** [comment]
> Could you please try the final 3.2.0 release?

It looks like msys2 has already had openssl installation, and ca-certificates, curl, libcurl and libssh2 are dependent on it. So I can't uninstall it. But I still want to compile it to the 3.2.0 release.

**Comment by tom-cosgrove-arm** [comment]
Should this issue be converted to a discussion?

**Comment by rainsdm** [comment]
> Should this issue be converted to a discussion?

Maybe you can. I think this is a conflicat error. Because there's an openssl-3.1.4 version after I first reinstall the msys2 program. And it still exist after I run the `./Configure mingw64` command and `make uninstall`.
I also can't uninstall openssl-3.1.4 version with `pacman -R openssl` because ca-certificates, curl, libcurl and libssh2 are dependent on it

**Comment by rainsdm** [comment]
I reinstalled mysys2, and switched compiler from `mingw-w64-i686-gcc` to `mingw-w64-x86_64-gcc`, but the same error is still here.
[output_error.txt](https://github.com/openssl/openssl/files/13691380/output_error.txt)
[dump.txt](https://github.com/openssl/openssl/files/13691382/dump.txt)
But it seems successfully installed: 
[install_info.txt](https://github.com/openssl/openssl/files/13691409/install_info.txt)
@t8m @tom-cosgrove-arm
