### ISSUE TITLE
Why openssl-1.0.2 makes libssl.so.1.0.0  shared library?

### ISSUE THREAD

**Issue by marko-lazic** [openssl/openssl#2306]
I am trying to run program that uses libssl.so.1.0.2 shared library. When i try to configure and compile this library using [https://github.com/openssl/openssl/releases/tag/OpenSSL_1_0_2](url) release i end up with libssl.so.1.0.0 which indeed is not library i need. Anyone know why?

**Comment by mattcaswell** [comment]
1.0.2 is the software version.
The numbers on the end of lbssl.so.1.0.0 refer to the ABI version - which is different. Software version 1.0.2 is a drop in replacement for 1.0.1, which is a drop in replacement for 1.0.0 - hence they all have the same ABI version.

**Comment by marko-lazic** [comment]
But how can i build 1.0.2 version? I don't understand :(

**Comment by mattcaswell** [comment]
You did build the 1.0.2 version. The 1.0.2 version creates libssl.so.1.0.0. There is no version that ever creates libssl.so.1.0.2

**Comment by marko-lazic** [comment]
Thank you for this explanation matt. Here's the thing. When i try to execute an aplication i get console output: `error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory`. This is what i'm trying to solve.

**Comment by marko-lazic** [comment]
However if i rename 1.1 library to be 1.0.2 i get an different type od output `version `OPENSSL_1.0.2d' not found`

**Comment by mattcaswell** [comment]
That is very odd. Like I said there is no such version as libssl.so.1.0.2. At least not an official one produced by the OpenSSL project. Different OS distributions usually bundle their own version of OpenSSL. Often the distros will add their own patches on top of OpenSSL - so it is possible that a distro has added a patch to create a libssl.so.1.0.2. If so you would need to contact the distro. Another possibility is that whoever created the application you are trying to use also patched OpenSSL to create that file.

Renaming 1.1 to 1.0.2 is not going to work. 1.1 and 1.0.2 are not binary compatible.

One solution that might work is to just create a sym link from libssl.so.1.0.2 to libssl.so.1.0.0.

**Comment by marko-lazic** [comment]
Both may be possible. While googling i may seen this in Debian. I will continue investigation, symlinking didn't help. Thanks for all the leads!

**Comment by levitte** [comment]
I suspect that the program you're attempting to run was linked to the vendor version of libssl, could that be correct?  As you said, Debian has for some reason made the SONAME include 1.0.2 instead of 1.0.0 somewhere along the say, I cannot say exactly why.

For demonstration, here's what it looks like on my personal system (running Debian Sid):

``` text
lapdog:~# ls /usr/lib/x86_64-linux-gnu/libssl*
/usr/lib/x86_64-linux-gnu/libssl3.so  /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.a    /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/libssl.so   /usr/lib/x86_64-linux-gnu/libssl.so.1.1
lapdog:~# ls -l /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 1 root root 357024 Oct 30 00:20 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 735998 Nov 21 22:20 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root     13 Nov 21 22:20 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
-rw-r--r-- 1 root root 434968 Jul  9  2015 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
-rw-r--r-- 1 root root 427072 Dec 31 14:09 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
-rw-r--r-- 1 root root 438792 Nov 21 22:20 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
lapdog:~# dpkg -S /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
libssl1.0.0:amd64: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
lapdog:~# dpkg -S /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
libssl1.0.2:amd64: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
lapdog:~# apt show libssl1.0.0:amd64
Package: libssl1.0.0
Version: 1.0.2d-1
Status: install ok installed
Priority: important
Section: libs
Source: openssl
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Installed-Size: 3,586 kB
Depends: libc6 (>= 2.14), debconf (>= 0.5) | debconf-2.0
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
Description: Secure Sockets Layer toolkit - shared libraries
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It provides the libssl and libcrypto shared libraries.

N: There is 1 additional record. Please use the '-a' switch to see it
lapdog:~# apt show libssl1.0.2:amd64
Package: libssl1.0.2
Version: 1.0.2k-1
Priority: important
Section: libs
Source: openssl1.0
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Installed-Size: 3,631 kB
Depends: libc6 (>= 2.14), debconf (>= 0.5) | debconf-2.0
Homepage: https://www.openssl.org
Tag: role::shared-lib
Download-Size: 1,294 kB
APT-Sources: http://ftp.se.debian.org/debian unstable/main amd64 Packages
Description: Secure Sockets Layer toolkit - shared libraries
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It provides the libssl and libcrypto shared libraries.

N: There is 1 additional record. Please use the '-a' switch to see it
```

**Comment by kroeckx** [comment]
The reason the soname has been changed in Debian from 1.0.0 to
1.0.2 is to be able to change the ABI. That is, the 1.0.0 and 1.0.2
version in Debian are not binary compatible, because some compile
time options changed.

**Comment by nosun** [comment]
how to resolve the problem @kroeckx

**Comment by kaduk** [comment]
It's still not entirely clear what you think "the problem" is.
That said, have you considered something like "sudo apt-get install devscripts build-essential && sudo apt-get build-depends openssl && apt-get source openssl && cd openssl* && debuild -uc -us"?

**Comment by nosun** [comment]
I use python to do development work, python package depends on libssl.so.1.0.2, but my operating system（ubuntu 16.04） does not have this file, when run  python script then occur the error, I spent a lot of time to find a solution, try a lot methods, but can not solve this problem:

The error is like this:

```
File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.0.2: cannot open shared object file: No such file or directory
```

**Comment by nosun** [comment]
I want to konw how I change something to resolve the problem: “This problem has affected a lot of my software”

**Comment by kaduk** [comment]
https://packages.debian.org/stretch/libssl1.0.2 is what kroeckx was trying to point you at.
But your question is really a Debian/Ubuntu question, not an openssl question, so that would be a better place for you to get good answers.  (You can update your apt sources.list.d configuration to pull in packages from debian stretch and retain cryptographic trust chain verification, but definitely go to an Ubuntu forum if you have issues with that process.)

**Comment by nosun** [comment]
Thank you for your guidance～
