### ISSUE TITLE
Merged to the master, 3.2, 3.1, and 3.0 branches. Thank you.

### ISSUE THREAD

**Issue by PTMARGAHAYUSETIAJAYA** [openssl/openssl#23092]
Merged to the master, 3.2, 3.1, and 3.0 branches. Thank you.

_Originally posted by @t8m in https://github.com/openssl/openssl/issues/23042#issuecomment-1862495033_

**Comment by mattcaswell** [comment]
@PTMARGAHAYUSETIAJAYA - you have created several "nonsense" issues, which I have closed. Please refrain from creating further issues that contain no real content.
