### ISSUE TITLE
Could I get retaken license for linux kernel

### ISSUE THREAD

**Issue by hzhuang1** [openssl/openssl#23156]
As I observed, the aes-cbc algorithm on armv8 works a little better in OpenSSL than in linux kernel. I want to port it from OpenSSL into linux kernel. But the licenses are different.

Could I get a retaken license on GPL 2.0, just as sha512-armv8.pl?

**Comment by mattcaswell** [comment]
Copyright in OpenSSL files is collectively owned by all authors and contributors to OpenSSL. In order to change the licence you would need to get permission from all contributors/copyright holders that have supplied non-trivial changes to the files you want to change. At least one of the copyright holders is the OpenSSL Software Foundation (OSF) so you would also need to seek permission from OSF. I don't know if they would do that or not. Anyway this is not something OSF can do unilaterally.

**Comment by hzhuang1** [comment]
> Copyright in OpenSSL files is collectively owned by all authors and contributors to OpenSSL. In order to change the licence you would need to get permission from all contributors/copyright holders that have supplied non-trivial changes to the files you want to change. At least one of the copyright holders is the OpenSSL Software Foundation (OSF) so you would also need to seek permission from OSF. I don't know if they would do that or not. Anyway this is not something OSF can do unilaterally.
> 
> 

Andy Polyakov <appro@openssl.org> is the main contributor of aes algorithm. But I failed to contact him with this email address. How could I contact him?

**Comment by mattcaswell** [comment]
Unfortunately Andy is no longer active on the project. AFAIK he still maintains cryptogams and it seems to have an AES on armv8 implementation there (possibly with some common history of our own implementation - I didn't check):

https://github.com/dot-asm/cryptogams/blob/master/arm/aesv8-armx.pl

You might be able to contact Andy through that project.

**Comment by hzhuang1** [comment]
> Unfortunately Andy is no longer active on the project. AFAIK he still maintains cryptogams and it seems to have an AES on armv8 implementation there (possibly with some common history of our own implementation - I didn't check):
> 
> https://github.com/dot-asm/cryptogams/blob/master/arm/aesv8-armx.pl
> 
> You might be able to contact Andy through that project.

Thanks. Let me contact Andy through that project.

**Comment by mattcaswell** [comment]
No further action to be taken here. Closing.
