### ISSUE TITLE
SSL_add_dir_cert_subjects_to_stack(): Return values undocumented

### ISSUE THREAD

**Issue by minfrin** [openssl/openssl#23171]
In the man page for SSL_add_dir_cert_subjects_to_stack(), the functions returning int have undocumented return values.

https://www.openssl.org/docs/man3.2/man3/SSL_add_dir_cert_subjects_to_stack.html

**Comment by shahsb** [comment]
@minfrin - Could you please help with all possible return values that should be documented?

**Comment by shahsb** [comment]
@minfrin @t8m - Can I work on this?

**Comment by shahsb** [comment]
> > @minfrin @t8m - Can I work on this?
> 
> Sure. All the functions in this manpage that return int return 1 for success and 0 in case of failure.

Sure. Thanks.

**Comment by shahsb** [comment]
I've rolled out the PR - https://github.com/openssl/openssl/pull/23433

@t8m @minfrin - Could you please review it?

**Comment by minfrin** [comment]
This is excellent, much appreciated.
