### ISSUE TITLE
OpenSSL 3.0.12 headers work with 1.1.1 libraries with no visible errors produced.

### ISSUE THREAD

**Issue by mavavilj** [openssl/openssl#23179]
I am successfully deploying OpenSSL on Android via

https://github.com/tangramor/OpenSSL-Android-iOS/tree/master

which includes .a libraries for 3.0.12.

I tried switching the .a libraries to 1.1.1 ones got from:

https://github.com/PurpleI2P/OpenSSL-for-Android-Prebuilt/tree/master

The test code in the first link runs flawlessly.

This led me to speculate that I see no problem in using 3.0.12 headers with 1.1.1 libraries even though this is non-sensical and should not work.

**Comment by levitte** [comment]
This depends on what you actually use.  Much of libcrypto is exactly the same in both versions.  In that sense, this isn't exactly a bug, at least on our end...  but you are playing with fire.

**Comment by mavavilj** [comment]
I think it should not be allowed. This way it's also not possible to be really sure what version is being used.

**Comment by t8m** [comment]
> I think it should not be allowed. This way it's also not possible to be really sure what version is being used.

It is impossible to prevent it by OpenSSL itself.

There are ways to do so, but they require a cooperation from the application - i.e. compare OpenSSL_version_num() with OPENSSL_VERSION_NUMBER in the application appropriately with masking the lower bits. These checks were historically done in many applications using OpenSSL but they were incorrect - usually too strict. So it is nowadays not recommended to have them.

**Comment by levitte** [comment]
There are other ways to discourage mixed version uses...  like embedding the version number into the library file name, and include directory name.  That would be absurdly counter productive, though.

This "problem" isn't unique for OpenSSL, BTW.

**Comment by nhorman** [comment]
I suppose we could add a VALIDATE_OPENSSL_VERSION function, which drew the Openssl version from the header file and compared it to the version embedded into the library, but that would require an application call it, and it would be a runtime failure, rather than a link time failure, but...perhaps better than nothing

**Comment by rsbeckerca** [comment]
> I suppose we could add a VALIDATE_OPENSSL_VERSION function, which drew the Openssl version from the header file and compared it to the version embedded into the library, but that would require an application call it, and it would be a runtime failure, rather than a link time failure, but...perhaps better than nothing

AFAIK, Curl already does this. There is an option that disables the check, which is on by default. The check is aggressive, which goes down to the bug-fix level, so if even the build is different, the check fails (making 3.0.12 incompatible with 3.0.11). If this is going to be added, it might be good to have a level argument to control how deep the check goes.

**Comment by mavavilj** [comment]
Yes I would've done it so that the library checks for the match of headers. And the library defines the version.

**Comment by nhorman** [comment]
A linker check is going to be tricky though, as there are some cases in which mismatched headers are ok (i.e. patch level differences should be ok, like 3.2.0 headers vs a 3.2.1 library).  It could possibly be done though if we could guarantee a global symbol in the library gets called from an application (which currently we can't guarantee in several configurations)

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
