### ISSUE TITLE
undefined struct/union evp_cipher_st

### ISSUE THREAD

**Issue by mohamad-z** [openssl/openssl#2321]
Recently I compiled openssl for VC-WIN32 traget using visual studio 11 (2012) under windows10 and it builds and installs both libraries and include files for the given location.

When I come to actually reference openssl in my win32 c program, it is not compiled and gives me this error:

1>c:\CODE\src\myprogram.c(517): error C2037: left of 'key_len' specifies undefined struct/union 'evp_cipher_st'

Digging more into the problem and compiling my old installed openssl in linux box it sounds evp_cipher_st is defined in evp.h file while for the newly installed one, there is no definition in evp.h

Here is the reference for the detailed question in stackoverflow site:

http://stackoverflow.com/questions/41909017/evp-get-cipherbyname-and-undefined-struct-union-evp-cipher-st

**Comment by levitte** [comment]
That's correct.  Since 1.1.0, `EVP_CIPHER` is an opaque type.  You have to create it using the functions described [here](https://www.openssl.org/docs/man1.1.0/crypto/EVP_CIPHER_meth_new.html)
