### ISSUE TITLE
ecparams genkey generates keys twice for named curves

### ISSUE THREAD

**Issue by afshinpir** [openssl/openssl#23239]
Hi all,

Is there any specific reason that `ecparams genkey` will generate keys twice if we pass curve as argument?
When we run this command **with a specific curve**, it will generate a key once here:
https://github.com/openssl/openssl/blob/0a22436ea5826d0089db7f1cd97b7c90135ca165/apps/ecparam.c#L237-L242
then it will regenerate it again here as well:
https://github.com/openssl/openssl/blob/0a22436ea5826d0089db7f1cd97b7c90135ca165/apps/ecparam.c#L326-L332
I think Is there any reason that this need to be done twice? I think it wants to use first key as template for second generation, but I'm not sure if it is necessary to do so. It is very inefficient I think.

**Comment by mattcaswell** [comment]
> I think Is there any reason that this need to be done twice? I think it wants to use first key as template for second generation, but I'm not sure if it is necessary to do so. It is very inefficient I think.

Right. The first gen creates a parameters only key, and the second gen creates the key itself. Historically this was the only way to do things, but in more recent versions of OpenSSL you can just pass the curve name directly in a single keygen operation (or even more easy is to use the `EVP_EC_gen` macro, or the `EVP_PKEY_Q_keygen()` function.

However this code predates the newer approaches and also needs to support explicit params which don't have these shortcut approaches. So it does it the old way. It would be possible to refactor it to make it more efficient, but I would call this a bug.
