### ISSUE TITLE
Usage of pre-RFC standard values for GOST signature schemes

### ISSUE THREAD

**Issue by fwh-dc** [openssl/openssl#23231]
The values for the GOST signature schemes seems to be out of date.
https://github.com/openssl/openssl/blob/7054fc1ca3945342777f588fba43b77f669509ad/ssl/ssl_local.h#L2206-L2207

Referencing the RFC diff (see section 5.):
https://author-tools.ietf.org/iddiff?url1=draft-smyshlyaev-tls12-gost-suites-04&url2=rfc9189&difftype=--html

Is it just a matter of updating them or are there any compatibility concerns?

**Comment by nhorman** [comment]
ping @beldmit

**Comment by beldmit** [comment]
I don't follow the recent state of Russian GOST but I think it's not necessary to keep these constants any more

**Comment by nhorman** [comment]
Ok, thank you.

Given that the associated PR was closed due to compatibility concerns, I think this can just be closed
