### ISSUE TITLE
Unable to build 1.0.2k on Solaris 10 using no-bf, no-camellia or no-mdc2 options

### ISSUE THREAD

**Issue by jfharvie** [openssl/openssl#2325]
I'm unable to build 1.0.2k on Solaris 10 (both Sparc and x86) when using either the no-bf, no-camellia or no-mdc2 options. We were previously able to build 1.0.2j without any problems.

We build OpenSSL using these commands:

./config no-asm no-bf no-camellia no-capieng no-gmp no-jpake no-md2 no-mdc2 no-rc5 no-zlib no-shared fips  --prefix="${TARGET}/local/ssl" ${OPTS}
make depend
make

This now causes a series of errors like this (the errors changes slightly based which of the options I include)

make[2]: Entering directory `/home/jon_h/3rdparty/openssl/src/crypto/evp'
make[2]: *** No rule to make target `../../include/openssl/blowfish.h', needed by `e_bf.o'.  Stop.
make[2]: Leaving directory `/home/jon_h/3rdparty/openssl/src/crypto/evp'
make[1]: *** [subdirs] Error 1
make[1]: Leaving directory `/home/jon_h/3rdparty/openssl/src/crypto'
make: *** [build_crypto] Error 1

I believe this was caused by the recent change to util/domd file as /bin/sh on Solaris 10 does not understand "if !" syntax.

**Comment by mattcaswell** [comment]
This is a known issue. Fixed in 0d37bd8058.
