### ISSUE TITLE
OpenSSL 3.2.0, QUIC, macOS, error 56 on connected UDP socket

### ISSUE THREAD

**Issue by icing** [openssl/openssl#23251]
### Description
Working on integrating OpenSSL 3.2 QUIC API into the [curl](https://github.com/curl/curl) project, I encounter an error in providing a connected UDP socket to a QUIC connection `SSL*`. macOS errors the `sendmsg()` invocation by a `BIO_s_dram` with `errno` 56 (Socket is already connected). Giving it an unconnected UDP socket works.

The rough code outline is as follows:

```
sock = socket(AF_INET6, SOCK_DGRAM, IPPROTO_UDP);
/* set non block */
connect(sock, peer_addr, peer_addr_len);
bio = BIO_new_dgram(sock, BIO_NOCLOSE);
BIO_ctrl_set_connected(bio, BIO_ADDR_from(peer_addr));
SSL_set1_initial_peer_addr(ssl, BIO_ADDR_from(peer_addr);
SSL_set_blocking_mode(ssl, 0));
SSL_set_bio(ssl, bio, bio);
SSL_set_connect_state(ssl);

err = SSL_do_handshake(ssl);  /* fails to send */
```

This seems possibly related to #7675 where macOS just is more picky than linux.

### Expectation

I expect `BIO_s_dram` in QUIC, which is recommended to get a connected socket - rightly so, to choose the proper OS call.

Thanks for your help in resolving this.

**Comment by hlandau** [comment]
This appears to be a bug. Fix under consideration.

The most expedient workaround for this for now is to avoid calling `connect()` and `BIO_ctrl_set_connected`, which is not necessary if `SSL_set1_initial_peer_addr` is set.

**Comment by icing** [comment]
Thanks, I am proceeding for now with an unconnected socket.

**Comment by Sashan** [comment]
My gut feeling told me `OpenBSD` may suffer from the same issue as `MacOS`. It took me a while to reproduce it on OpenBSD, because I hit some unexpected corners (see #23312). It took me a while to workaround them.

The problem is  `sendmmsg()` on OpenBSD won't send messages which have `msg_name` set in `msg_hdr` using connected `socket()`
