### ISSUE TITLE
Unable to run asm code on OpenBSD

### ISSUE THREAD

**Issue by Sashan** [openssl/openssl#23312]
perlasm files should keep constants/data in '.section .rodata':

Running openssl tests on OpenBSD is futile unless build is configured with `./Configure  no-asm` which disables optimized routines written in assembly. I'll demonstrate the issue on simple example. This is a `main.c`
```
#include <stdio.h>

extern int get_fee();
extern int get_foo();

int
main(int argc, const char *argv[0])
{
        printf("%x\n", get_fee());
        printf("%x\n", get_foo());

        return (0);
}
```
The code above is linked with .o file which is produced from .s below:
```
.global  get_foo
.type   get_foo,@function
get_foo:
        mov .foo(%rip), %rax
        ret

.global  get_fee
.type   get_fee,@function
get_fee:
        mov .fee(%rip), %rax
        ret

.foo:
        .long 0x00f00f00

.section .rodata

.fee:
        .byte 0x00,0xfe,0xef,0xee
```
The module above defines functions `get_foo()` and `get_fee()`. both functions return `int` which
is a constant `foo` (`fee`) in module `test.s` Code can be built using Makefile as follows:
```
test: main.o test.o
        $(CC) -o test main.o test.o

main.o: main.c
        $(CC) -g -O0 -c -o main.o main.c

test.o: test.s
        $(CC) -c  test.s 

clean:
        rm -f test.o main.o
``` 
Building it and running it as-is on linux (Ubuntu) yields following output:
```
sashan@ubuntu:~/rodata$ make && ./test
cc -g -O0 -c -o main.o main.c
cc -c  test.s 
cc -o test main.o test.o
eeeffe00
f00f00
```
doing the same on OpenBSD box gives me a .core file.
```
lifty$ make && ./test
cc -g -O0 -c -o main.o main.c
cc -c  test.s 
cc -o test main.o test.o
eeeffe00
Segmentation fault (core dumped) 
```
Poking at core file we see we die as soon as we load constant `foo` to `eax` output register
```
lifty$ egdb test test.core  
...
Core was generated by `test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000b9e9d689a20 in get_foo ()
(gdb) disassemble get_foo
Dump of assembler code for function get_foo:
=> 0x00000b9e9d689a20 <+0>:     mov    0x9(%rip),%rax        # 0xb9e9d689a30 <.foo>
   0x00000b9e9d689a27 <+7>:     retq   
End of assembler dump.
(gdb) quit
```
Apart from returning different constants the functions `get_foo()` and `get_fee()` are identical
```
(gdb) disassemble get_fee
Dump of assembler code for function get_fee:
   0x00000b9e9d689a28 <+0>:     mov    -0x1523(%rip),%rax        # 0xb9e9d68850c
   0x00000b9e9d689a2f <+7>:     retq   
End of assembler dump.
```
What makes difference here is where `fee` and `foo` constants/data are placed. The constant `fee` is found in .rodata segment, while constant `foo` is placed to .text segment along the code. OpenBSD does not like variables/constants (a.k.a. data) to be placed into .text segment where code lives.

The CPU I was using to convey my test was amd ryzen.

**Comment by t8m** [comment]
IMO this would be a feature to fix all the relevant assembler files.

**Comment by tom-cosgrove-arm** [comment]
Any objections if I change the title to "Unable to run asm code on OpenBSD"? That might make this issue more discoverable...

**Comment by Sashan** [comment]
No objections, please go ahead.
thanks.

**Comment by tom-cosgrove-arm** [comment]
Note that this might not just be x86_64, since [OpenBSD supports several platforms](https://www.openbsd.org/plat.html), including [an AArch64 one](https://www.openbsd.org/arm64.html)

**Comment by Sashan** [comment]
I could not figure out the easy `no-asm` way to disable asm code on boirngssl which we need to run cloudflare quic server to perform our unit test. the hard way is to apply boring-ssl diff below to get clouddlare-quiche server running on OpenBSD too.
```
diff --git a/linux-x86_64/crypto/fipsmodule/aesni-gcm-x86_64.S b/linux-x86_64/crypto/fipsmodule/aesni-gcm-x86_64.S
index 65ab5c78f..304e4f71b 100644
--- a/linux-x86_64/crypto/fipsmodule/aesni-gcm-x86_64.S
+++ b/linux-x86_64/crypto/fipsmodule/aesni-gcm-x86_64.S
@@ -835,6 +835,7 @@ aesni_gcm_encrypt:
 	.byte	0xf3,0xc3
 .cfi_endproc	
 .size	aesni_gcm_encrypt,.-aesni_gcm_encrypt
+.section .rodata
 .align	64
 .Lbswap_mask:
 .byte	15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
diff --git a/linux-x86_64/crypto/fipsmodule/aesni-x86_64.S b/linux-x86_64/crypto/fipsmodule/aesni-x86_64.S
index b98107f36..8745b205d 100644
--- a/linux-x86_64/crypto/fipsmodule/aesni-x86_64.S
+++ b/linux-x86_64/crypto/fipsmodule/aesni-x86_64.S
@@ -2480,6 +2480,7 @@ __aesni_set_encrypt_key:
 	.byte	0xf3,0xc3
 .size	aes_hw_set_encrypt_key,.-aes_hw_set_encrypt_key
 .size	__aesni_set_encrypt_key,.-__aesni_set_encrypt_key
+.section .rodata
 .align	64
 .Lbswap_mask:
 .byte	15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
@@ -2502,5 +2503,6 @@ __aesni_set_encrypt_key:
 
 .byte	65,69,83,32,102,111,114,32,73,110,116,101,108,32,65,69,83,45,78,73,44,32,67,82,89,80,84,79,71,65,77,83,32,98,121,32,60,97,112,112,114,111,64,111,112,101,110,115,115,108,46,111,114,103,62,0
 .align	64
+.section .text
 #endif
 .section	.note.GNU-stack,"",@progbits
diff --git a/linux-x86_64/crypto/fipsmodule/ghash-x86_64.S b/linux-x86_64/crypto/fipsmodule/ghash-x86_64.S
index 3eb1af435..f55f0f180 100644
--- a/linux-x86_64/crypto/fipsmodule/ghash-x86_64.S
+++ b/linux-x86_64/crypto/fipsmodule/ghash-x86_64.S
@@ -1112,6 +1112,7 @@ gcm_ghash_avx:
 	.byte	0xf3,0xc3
 .cfi_endproc	
 .size	gcm_ghash_avx,.-gcm_ghash_avx
+.section .rodata
 .align	64
 .Lbswap_mask:
 .byte	15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
diff --git a/linux-x86_64/crypto/fipsmodule/sha256-x86_64.S b/linux-x86_64/crypto/fipsmodule/sha256-x86_64.S
index 0bacd6a4a..3ecf0f706 100644
--- a/linux-x86_64/crypto/fipsmodule/sha256-x86_64.S
+++ b/linux-x86_64/crypto/fipsmodule/sha256-x86_64.S
@@ -1738,6 +1738,7 @@ sha256_block_data_order:
 	.byte	0xf3,0xc3
 .cfi_endproc	
 .size	sha256_block_data_order,.-sha256_block_data_order
+.section .rodata
 .align	64
 .type	K256,@object
 K256:
@@ -1781,6 +1782,7 @@ K256:
 .long	0xffffffff,0xffffffff,0x03020100,0x0b0a0908
 .long	0xffffffff,0xffffffff,0x03020100,0x0b0a0908
 .byte	83,72,65,50,53,54,32,98,108,111,99,107,32,116,114,97,110,115,102,111,114,109,32,102,111,114,32,120,56,54,95,54,52,44,32,67,82,89,80,84,79,71,65,77,83,32,98,121,32,60,97,112,112,114,111,64,111,112,101,110,115,115,108,46,111,114,103,62,0
+.section .text
 .type	sha256_block_data_order_ssse3,@function
 .align	64
 sha256_block_data_order_ssse3:
diff --git a/linux-x86_64/crypto/fipsmodule/sha512-x86_64.S b/linux-x86_64/crypto/fipsmodule/sha512-x86_64.S
index afc47f139..82d913288 100644
--- a/linux-x86_64/crypto/fipsmodule/sha512-x86_64.S
+++ b/linux-x86_64/crypto/fipsmodule/sha512-x86_64.S
@@ -1736,6 +1736,7 @@ sha512_block_data_order:
 	.byte	0xf3,0xc3
 .cfi_endproc	
 .size	sha512_block_data_order,.-sha512_block_data_order
+.section .rodata
 .align	64
 .type	K512,@object
 K512:
@@ -1823,6 +1824,7 @@ K512:
 .quad	0x0001020304050607,0x08090a0b0c0d0e0f
 .quad	0x0001020304050607,0x08090a0b0c0d0e0f
 .byte	83,72,65,53,49,50,32,98,108,111,99,107,32,116,114,97,110,115,102,111,114,109,32,102,111,114,32,120,56,54,95,54,52,44,32,67,82,89,80,84,79,71,65,77,83,32,98,121,32,60,97,112,112,114,111,64,111,112,101,110,115,115,108,46,111,114,103,62,0
+.section .text
 .type	sha512_block_data_order_avx,@function
 .align	64
 sha512_block_data_order_avx:
diff --git a/linux-x86_64/crypto/fipsmodule/x86_64-mont5.S b/linux-x86_64/crypto/fipsmodule/x86_64-mont5.S
index c86b3b0a5..63bb6d025 100644
--- a/linux-x86_64/crypto/fipsmodule/x86_64-mont5.S
+++ b/linux-x86_64/crypto/fipsmodule/x86_64-mont5.S
@@ -3781,6 +3781,7 @@ bn_gather5:
 .LSEH_end_bn_gather5:
 .cfi_endproc	
 .size	bn_gather5,.-bn_gather5
+.section .rodata
 .align	64
 .Linc:
 .long	0,0, 1,1
diff --git a/src/crypto/fipsmodule/aes/asm/aesni-x86_64.pl b/src/crypto/fipsmodule/aes/asm/aesni-x86_64.pl
index 2abc8d03b..bef4fad62 100644
--- a/src/crypto/fipsmodule/aes/asm/aesni-x86_64.pl
+++ b/src/crypto/fipsmodule/aes/asm/aesni-x86_64.pl
@@ -4727,6 +4727,7 @@ ___
 }
 
 $code.=<<___;
+.section .rodata
 .align	64
 .Lbswap_mask:
 	.byte	15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
@@ -4749,6 +4750,7 @@ $code.=<<___;
 
 .asciz  "AES for Intel AES-NI, CRYPTOGAMS by <appro\@openssl.org>"
 .align	64
+.section .text
 ___
 
 # EXCEPTION_DISPOSITION handler (EXCEPTION_RECORD *rec,ULONG64 frame,
diff --git a/src/crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl b/src/crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl
index 793f34c51..5f6b89e3e 100644
--- a/src/crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl
+++ b/src/crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl
@@ -982,6 +982,7 @@ $code.=<<___;
 ___
 
 $code.=<<___;
+.section .rodata
 .align	64
 .Lbswap_mask:
 	.byte	15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
@@ -994,6 +995,7 @@ $code.=<<___;
 .Lone_lsb:
 	.byte	1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
 .asciz	"AES-NI GCM module for x86_64, CRYPTOGAMS by <appro\@openssl.org>"
+.section .text
 .align	64
 ___
 if ($win64) {
diff --git a/src/crypto/fipsmodule/modes/asm/ghash-x86_64.pl b/src/crypto/fipsmodule/modes/asm/ghash-x86_64.pl
index 1aeb7b7d2..9fc821364 100644
--- a/src/crypto/fipsmodule/modes/asm/ghash-x86_64.pl
+++ b/src/crypto/fipsmodule/modes/asm/ghash-x86_64.pl
@@ -1275,6 +1275,7 @@ ___
 }
 
 $code.=<<___;
+.section .rodata
 .align	64
 .Lbswap_mask:
 	.byte	15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
@@ -1285,6 +1286,7 @@ $code.=<<___;
 .align	64
 
 .asciz	"GHASH for x86_64, CRYPTOGAMS by <appro\@openssl.org>"
+.section .text
 .align	64
 ___
 
diff --git a/src/crypto/fipsmodule/sha/asm/sha1-x86_64.pl b/src/crypto/fipsmodule/sha/asm/sha1-x86_64.pl
index 512602535..93485178e 100755
--- a/src/crypto/fipsmodule/sha/asm/sha1-x86_64.pl
+++ b/src/crypto/fipsmodule/sha/asm/sha1-x86_64.pl
@@ -1815,6 +1815,7 @@ ___
 }
 }
 $code.=<<___;
+.section .rodata
 .align	64
 K_XX_XX:
 .long	0x5a827999,0x5a827999,0x5a827999,0x5a827999	# K_00_19
@@ -1828,6 +1829,7 @@ K_XX_XX:
 .long	0x00010203,0x04050607,0x08090a0b,0x0c0d0e0f	# pbswap mask
 .long	0x00010203,0x04050607,0x08090a0b,0x0c0d0e0f	# pbswap mask
 .byte	0xf,0xe,0xd,0xc,0xb,0xa,0x9,0x8,0x7,0x6,0x5,0x4,0x3,0x2,0x1,0x0
+.section .text
 ___
 }}}
 $code.=<<___;
diff --git a/src/crypto/fipsmodule/sha/asm/sha512-x86_64.pl b/src/crypto/fipsmodule/sha/asm/sha512-x86_64.pl
index 61f67cb60..052864c1d 100755
--- a/src/crypto/fipsmodule/sha/asm/sha512-x86_64.pl
+++ b/src/crypto/fipsmodule/sha/asm/sha512-x86_64.pl
@@ -407,6 +407,7 @@ ___
 
 if ($SZ==4) {
 $code.=<<___;
+.section .rodata
 .align	64
 .type	$TABLE,\@object
 $TABLE:
@@ -450,9 +451,11 @@ $TABLE:
 	.long	0xffffffff,0xffffffff,0x03020100,0x0b0a0908
 	.long	0xffffffff,0xffffffff,0x03020100,0x0b0a0908
 	.asciz	"SHA256 block transform for x86_64, CRYPTOGAMS by <appro\@openssl.org>"
+.section .text
 ___
 } else {
 $code.=<<___;
+.section .rodata
 .align	64
 .type	$TABLE,\@object
 $TABLE:
@@ -540,6 +543,7 @@ $TABLE:
 	.quad	0x0001020304050607,0x08090a0b0c0d0e0f
 	.quad	0x0001020304050607,0x08090a0b0c0d0e0f
 	.asciz	"SHA512 block transform for x86_64, CRYPTOGAMS by <appro\@openssl.org>"
+.section .text
 ___
 }
```
I filed boringssl [ticket](https://bugs.chromium.org/p/boringssl/issues/detail?id=678) to let them know.

**Comment by davidben** [comment]
Re BoringSSL, we moved x86_64 data to .rodata about a year ago in https://boringssl-review.googlesource.com/c/boringssl/+/57445. Most aarch64 data was moved even longer ago, though we'd missed a spot in https://boringssl-review.googlesource.com/c/boringssl/+/57446

Cloudflare QUICHE seems to just be using a very very old version.

**Comment by Sashan** [comment]
On Wed, Jan 17, 2024 at 08:26:44AM -0800, David Benjamin wrote:
> Re BoringSSL, we moved x86_64 data to .rodata about a year ago in https://boringssl-review.googlesource.com/c/boringssl/+/57445. Most aarch64 data was moved even longer ago, though we'd missed a spot in https://boringssl-review.googlesource.com/c/boringssl/+/57446
> 
> Cloudflare QUICHE seems to just be using a very very old version.

sorry for the noise. I've forgot to check the version quiche server is pulling
as a dependency. Entirely my fault.

**Comment by botovq** [comment]
I have been maintaining patches for the OpenSSL ASM for the OpenBSD ports tree for the 3.1 and 3.2 branches: https://github.com/openbsd/ports/tree/master/security/openssl/3.2/patches . I have an ICLA on file, you are more than welcome to take them and bring them into shape acceptable for the OpenSSL project.

To my knowledge only the T4 assembly is broken on sparc64 #20523

**Comment by Sashan** [comment]
@tom-cosgrove-arm sorry to coming to it after a while. I'm still waiting for my arm box to arrive, so I can give it a try. I took OpenBSD patches @botovq maintains and applied them. all tests do pass on amd64.

my question is: is it good enough to take care of amd64 and 64-bit arm for now? Or shall I look at other platforms such as sparc64, octeon, ... etc? I can test those changes on amd64/arm nothing else. IMO additional platforms can be handled later in separate pull-request.

this is what I got from @botovq:
https://github.com/openssl/openssl/compare/master...Sashan:openssl:issue.23312

**Comment by Sashan** [comment]
> @Sashan I would make changes for one architecture in one PR (i.e. one PR for x86_64, one for AArch64), which means you don't need to do all of them

@tom-cosgrove-arm so what else I should take care of? current stuff I have comes from openssl port for OpenBSD. It deals with amd64 and arm64. I don't know which other OS (than OpenBSD) does really care about splitting data and code into different sgements/pages. I feel OpenSSL on OpenBSD is really small set of usecases. OpenBSD is very specific here and same applies to openssl on OpenBSD: it's very unusual to run install openssl on OpenBSD now.

**Comment by huiyuexu** [comment]
> @Sashan I would make changes for one architecture in one PR (i.e. one PR for x86_64, one for AArch64), which means you don't need to do all of them

@tom-cosgrove-arm  When do you plan to submit your work as a PR?

**Comment by Sashan** [comment]
@huiyuexu I took a look at PR [#23984](https://github.com/openssl/openssl/pull/23984) which does take care of .rodata on arm. It is different to stuff I got from @botovq:
```
        adrp    @x[0],.Lsigma                                                                                                                                                                                                                                                                                               
        add     @x[0],@x[0],#:lo12:.Lsigma 
```
while code I got from @botovq reads as follows:
```
        adrp    @x[0],.Lsigma
        add     @x[0],@x[0],:lo12:.Lsigma
```
Do I understand right the `#` is optional? At least [9.1.3.1](https://sourceware.org/binutils/docs/as/AArch64_002dChars.html) section says so. I don't have an arm box to try it out. So I will be happy if someone will confirm I managed to find the right answer: `#` is just optional cosmetic detail.

Besides this cosmetic detail the @botovq stuff for example here in `ecp_nistz256_to_mont:` Code from libressl (@botovq)
```
132         adrp    $bi,.LRR
133         ldr     $bi,[$bi,:lo12:.LRR]    // bp[0]
134         ldp     $a0,$a1,[$ap]
135         ldp     $a2,$a3,[$ap,#16]
136         adrp    $poly3,.Lpoly
137         add     $poly3,$poly3,:lo12:.Lpoly
138         ldr     $poly1,[$poly3,#8]
139         ldr     $poly3,[$poly3,#24]
140         adrp    $bp,.LRR                // &bp[0]
141         add     $bp,$bp,:lo12:.LRR
```

and the same  code from #23984:
```
132         adrp    $bi,.LRR
133         add     $bi,$bi,#:lo12:.LRR
134         ldr     $bi,[$bi]               // bp[0]
135         ldp     $a0,$a1,[$ap]
136         ldp     $a2,$a3,[$ap,#16]
137         adrp    $poly1,.Lpoly+8
138         add     $poly1,$poly1,#:lo12:.Lpoly+8
139         ldr     $poly1,[$poly1]
140         adrp    $poly3,.Lpoly+24
141         add     $poly3,$poly3,#:lo12:.Lpoly+24
142         ldr     $poly3,[$poly3]
143         adrp    $bp,.LRR                // &bp[0]
144         add     $bp,$bp,#:lo12:.LRR     // &bp[0]
```
I code above the line 134 can be deleted, `$bi` it is not going to be used anywhere later. It seems to me those code differ in order how numbers are added.

anyway I've just submitted PR #23997

thanks for bearing with me.

**Comment by Sankyou** [comment]
When will your modification be merged to master branch? Hope to see that! 
Actually my work depends on it，PR #23984 is my modification, if your work has covered mine，I'll use yours in the future instead, but only can I use when it be merged. 
Thank you for your work and wish you can speed to finish the work of separating data from .text to .rodata section (in aarch64 architecture)！：）@tom-cosgrove-arm@Sashan

**Comment by Sashan** [comment]
I'm working on intel bits. everything seems to work except macos-13. So I'm thinking of introducing an option/env-variable which will explicitly ask build system to produce .rodata sections. I think this is a good first step. It can be fine tuned in follow-up steps as we learn how things work for different build targets.

**Comment by tom-cosgrove-arm** [comment]
> I'm thinking of introducing an option/env-variable which will explicitly ask build system to produce .rodata sections

Since OpenSSL assembly code (all architectures? Certainly Intel and Arm...) is run through a translation Perl script, can't the assembly instructions be included in the `.pl` files then removed by `xlate.pl` if the target system doesn't support it? Exactly this mechanism is used to support Apple's assembler in the Arm assembly

**Comment by Sashan** [comment]
Sorry I was not clear in my comment. I did not mean to say .rodata sections are not supported on Mac-OS. They just require yet another syntax form to declare them.

To give you a context. I'm currently working x86_64 part only. It fails here on macos-13:
```
Run make -s -j4
crypto/aes/aes-x86_64.s:1855:17: error: unexpected token in '.section' directive
.section .rodata
                ^
make[1]: *** [crypto/aes/libcrypto-lib-aes-x86_64.o] Error 1
make[1]: *** Waiting for unfinished jobs....
crypto/aes/aesni-sha1-x86_64.s:2709:17: error: unexpected token in '.section' directive
.section .rodata
                ^
make[1]: *** [crypto/aes/libcrypto-lib-aesni-sha1-x86_64.o] Error 1
make: *** [build_sw] Error 2
Error: Process completed with exit code 2.
```
this error can be found at [CI run](https://github.com/openssl/openssl/actions/runs/8469428620/job/23204753806) for my [pull request](https://github.com/openssl/openssl/pull/23997) It currently takes care of x86_64.

My original idea was to introduce a hint for MAC-OS build to generate .rodata to make toolchain on MACOS-13 happy. Then I've took a step back and opted for more conservative option to explicitly ask for rodata sections via ./Configure. 

Thank you for pointer to boring. Will take a look.

**Comment by davidben** [comment]
Ah, for x86_64, these are the transformations we added. Or rather, by "we", I mean we accepted a contribution by @botovq to add them. :-)
https://boringssl-review.googlesource.com/c/boringssl/+/57445/7/crypto/perlasm/x86_64-xlate.pl

I suspect that will clear the error. macOS and Windows name these sections differently. See this discussion for Windows:
https://boringssl-review.googlesource.com/c/boringssl/+/57445/comment/0f56c161_48c7db5f/

For macOS, this documentation has the names of sections:
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/CodeFootprint/Articles/MachOOverview.html

**Comment by Sashan** [comment]
Everything looks almost good. Unfortunately changes we have fail to build on Windows 2019 server. The error is as follows:
```
crypto\aes\aes-x86_64.asm(1921) : error A2189:invalid combination with segment alignment : 64
crypto\aes\aes-x86_64.asm(2311) : error A2189:invalid combination with segment alignment : 64
crypto\aes\aes-x86_64.asm(2709) : error A2189:invalid combination with segment alignment : 64
crypto\aes\aes-x86_64.asm(2713) : error A2189:invalid combination with segment alignment : 16
crypto\aes\aes-x86_64.asm(2770) : error A2189:invalid combination with segment alignment : 16
crypto\aes\aes-x86_64.asm(2827) : error A2189:invalid combination with segment alignment : 16
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\ml64.EXE"' : return code '0x1'
Stop.
```
Looks like older linker version considers this as hard error, while newer version shows just [warning,](https://learn.microsoft.com/en-us/cpp/assembler/masm/ml-nonfatal-error-a2189?view=msvc-170) therefore build succeeds. To better understand what's going on here I made a diff between two `aes-x86_64.asm` files. One comes from build _without_ changes in [PR#23997](https://github.com/openssl/openssl/pull/23997) , while the other file comes from openssl with those changes in:
```
--- ../openssl.sashan.master/aes-x86_64.asm     Wed Apr  3 15:51:02 2024
+++ ./crypto/aes/aes-x86_64.asm Wed Apr  3 14:03:11 2024
@@ -1915,6 +1915,7 @@
        DB      0F3h,0C3h               ;repret
 
 $L$SEH_end_AES_cbc_encrypt:
+section        .rdata rdata align=8
 ALIGN  64
 $L$AES_Te:
        DD      0xa56363c6,0xa56363c6
@@ -2704,6 +2705,7 @@
 DB     112,112,114,111,64,111,112,101,110,115,115,108,46,111,114,103
 DB     62,0
 ALIGN  64
+
 EXTERN __imp_RtlVirtualUnwind
 
 ALIGN  16
```
It seems to me the problem is caused by `align=8` in section definition. The linker complains it can not fit larger alignments to such section. The `section` is generated by snippet below found in `x86_64-xlate.pl`:
```
 894                 /\.section/ && do { my $v=undef;
 895                                     $$line =~ s/([^,]*).*/$1/;
 896                                     $$line = ".CRT\$XCU" if ($$line eq ".init");
 897                                     $$line = ".rdata" if ($$line eq ".rodata");
 898                                     if ($nasm) {
 899                                         $v="section     $$line";
 900                                         if ($$line=~/\.([prx])data/) {
 901                                             $v.=" rdata align=";
 902                                             $v.=$1 eq "p"? 4 : 8;
 903                                         } elsif ($$line=~/\.CRT\$/i) {
 904                                             $v.=" rdata align=8";
 905                                         }
 906                                     } else {
```
The `ALIGN` directive comes from `.align 64` which follows `.section .rodata` line in `aes-x86_64.pl` file. Perhaps the best option to fix it is to allow optional `align=...` parameter to `.section` directive we have in `.pl` files and let `x86_64-xlate.pl` deal with it.

I was also considering two other alternatives:
   - introduce a kind of context to `x86_64-xlate.pl` so it can deduce/guess correct align size as MAX() of all align directives found in section
   - or let `x86_64-xlate.pl` do two passes. The first pass would be identical to what we have now the new second pass would just fix the align option in section definitions.

from all those three I'm leaning towards introducing `align` option into .section definition in .pl assembly files and let xlate to deal with it. This makes things explicit and avoids any kind auto-magic which can bite us later.
