### ISSUE TITLE
OpenSSL 1.0.2 parallel make during Configure can disable tests

### ISSUE THREAD

**Issue by ekasper** [openssl/openssl#2331]
Repro instructions:

$ MAKE='make -j8' ./config

Normally, in Configure, 'make links' creates symlinks for the unit tests from their respective directories to test/. Thereafter, 'make gentests' links tests of disabled features to dummytest.c.

With parallel make, 'make links' and 'make gentests' race.and where 'make gentests' gets first, it links the tests to dummytest.c.

Unlike https://github.com/openssl/openssl/issues/298, this is a completely silent failure. The tests will appear to be passing but in fact no tests are run. So, I think that this should be fixed even if changing the 1.0.2 build to fully support parallel make would be too invasive of a change.

Attached the start of a Configure log with parallel make:

DES_UNROLL used
DES_INT used
RC4_CHUNK is unsigned long
created directory 'include'
**generating dummy tests (if needed)...**
created directory 'include/openssl'
make[1]: Entering directory 'openssl/test'
bntest.c => dummytest.c
e_os2.h => include/openssl/e_os2.h
ecdhtest.c => dummytest.c
ideatest.c => dummytest.c
ectest.c => dummytest.c
ecdsatest.c => dummytest.c
md4test.c => dummytest.c
hmactest.c => dummytest.c
wp_test.c => dummytest.c
**making links in crypto...**
md2test.c => dummytest.c
md5test.c => dummytest.c
make[1]: Entering directory 'openssl/crypto'
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
rc2test.c => dummytest.c
rc4test.c => dummytest.c
sha1test.c => dummytest.c
rc5test.c => dummytest.c
destest.c => dummytest.c
shatest.c => dummytest.c
dhtest.c => dummytest.c
randtest.c => dummytest.c
mdc2test.c => dummytest.c
rmdtest.c => dummytest.c
crypto.h => ../include/openssl/crypto.h
opensslv.h => ../include/openssl/opensslv.h

**Comment by levitte** [comment]
Gotcha.  The easy fix is to make sure those targets get a make call each.  PR coming up.

**Comment by levitte** [comment]
Have a look at #2332
