### ISSUE TITLE
slow build process for openssl3.2.0

### ISSUE THREAD

**Issue by Deknas1995** [openssl/openssl#23322]
Hi, Im building openSSL3.2.0 for windows and Linux and for both is is very slow 
for windows Im building:
win32 debug.cmd
win32 release.cmd 
win64 debug.cmd 
win64 release.cmd 

using nmake It takes about 2h... how can I make it faster?

**Comment by nhorman** [comment]
That seems like an environmental issue.  you can set the /MP flag to have nmake do parallel building, and that still takes a while, though no openssl build should take 2 hours on modern hardware.  Is there a particular command its getting stuck on, or is it consistently slow for each compile command run during make?  If its the latter I would initially suspect some file system latency, like if you were compiling with a source tree on a particularly slow nfs share.

**Comment by nhorman** [comment]
Given the lack of response, i'm marking this as inactiive, to be closed at the end of the 3.4 development cycle
