### ISSUE TITLE
buf2hexstr_sep ebcdic2ascii translation off by 1

### ISSUE THREAD

**Issue by abaez004** [openssl/openssl#23363]
I found this issue working with OpenSSL 3.0. This function was updated in OpenSSL 3.0 so that the buffer q points to the last character in the buffer buf. Because of this change, the calculation for ebcdic2ascii is off by 1. q - str - 1 is 1 less than the length of buf, which results in all characters but the last to be translated in buf. Suggest changing to ebcdic2ascii(str, str, q - str) or even using the calculated length len instead, ebcdic2ascii(str, str, len - 1).

**Comment by shahsb** [comment]
I've rolled out the PR - https://github.com/openssl/openssl/pull/23434

@abaez004 @t8m - Could you please review it?
