### ISSUE TITLE
Invalid URL in Security Advisory emails

### ISSUE THREAD

**Issue by Sp1l** [openssl/openssl#23395]
Security Advisory emails to apache-announce@ and text files in news/secadv contain a link to the security policy in the footer

https://www.openssl.org/policies/secpolicy.htm

This link results in a 404, the correct link is

https://www.openssl.org/policies/general/security-policy.html

**Comment by mattcaswell** [comment]
The link is supposed to be this one (note the added "l" on the end):

https://www.openssl.org/policies/secpolicy.html

So the latest security advisory inadvertently had the final "l" removed.

**Comment by Sp1l** [comment]
Thanks! I thought it was everywhere, but with the "l" appended, the redirect gets you where you need to be.
