### ISSUE TITLE
Update 3.0.11 to 3.0.12 PKCS#11 Engine TLS 

### ISSUE THREAD

**Issue by embetrix** [openssl/openssl#23397]
When Updating OpenSSL from 3.0.11 to 3.0.12 Version I noticed that a TLS Session using PKCS#11 (SoftHSM) is using :
**CKM_RSA_X_509** instead of **CKM_RSA_PKCS_PSS** mechanisms 

With Spy Logs

OpenSSL  3.0.11 (And Previous Versions)
```
32: C_SignInit
P:568; T:0x3070124064 2024-01-26 15:48:22.387
[in] hSession = 0x1
[in] pMechanism->type = CKM_RSA_PKCS_PSS             
[in] pMechanism->pParameter->hashAlg = CKM_SHA256                   
[in] pMechanism->pParameter->mgf = CKG_MGF1_SHA256
[in] pMechanism->pParameter->sLen = 32
[in] hKey = 0x2
Returned:  0 CKR_OK
```
OpenSSL  3.0.12:
```
32: C_SignInit
P:9884; T:0x3069210656 2024-01-26 15:15:09.336
[in] hSession = 0x1
[in] pMechanism->type = CKM_RSA_X_509                
[in] pMechanism->pParameter[ulParameterLen] NULL [size : 0x0 (0)]
[in] hKey = 0x2
Returned:  0 CKR_OK
```

This behaviour is NOT correct and cause a lot of issues since not all Tokens implement **CKM_RSA_X_509** mechanisms

**Comment by t8m** [comment]
Would it be possible for you to try to isolate which change caused this? It is not obviously clear to me.

**Comment by petrovr** [comment]
Let assume engine for libp11 project not from opencryptoki.


embetrix wrote:
> When Updating OpenSSL from 3.0.11 to 3.0.12 Version I noticed that a TLS Session using PKCS#11 (SoftHSM) is using :
> **CKM_RSA_X_509** instead of **CKM_RSA_PKCS_PSS** mechanisms
>
> With Spy Logs
>
> OpenSSL  3.0.11 (And Previous Versions)
> 32: C_SignInit ...
> [in] pMechanism->type = CKM_RSA_PKCS_PSS

Only pkey method could support following map:
RSA_PKCS1_PSS_PADDING <=> CKM_RSA_PKCS_PSS

> OpenSSL  3.0.12:
> 32: C_SignInit ...
> [in] pMechanism->type = CKM_RSA_X_509
> ....
RSA method could support only following:
RSA_NO_PADDING <=> CKM_RSA_X_509
RSA_PKCS1_PADDING (default) <=> CKM_RSA_PKCS

Dunno why is not default.


After second review of libp11 code. It seem to me engine mix "basic" key method with pkey method. Load does not assign engine to basic key but set engine on pkey.
Most probably this mismatch does not allow OpenSSL to determine properly that key and pkey use classical methods.


Regards,
Roumen Petrov

**Comment by embetrix** [comment]
@t8m : this commit https://github.com/openssl/openssl/commit/02b87cc189fa8cae8d6f69d68449a9aecc0e34f0  is the cause of the issue, after reverting it, it works as it was before.

**Comment by embetrix** [comment]
@petrovr thanks for the analysis, yes in the fact I use **libp11** for engines.

**Comment by t8m** [comment]
We already have #23063 waiting for an approval to be merged. Unfortunately it will miss the today's patch releases.

**Comment by t8m** [comment]
The revert was merged. Closing this.
