### ISSUE TITLE
Possible bug in AES CBC-CS1 decrypt

### ISSUE THREAD

**Issue by bhight** [openssl/openssl#23402]
I wrote some code to generate some partial block test vectors for the AES CBC-CS1 algorithm.  The code is based on the CBC-CS1 encrypt example code on the page.  https://www.openssl.org/docs/manmaster/man3/EVP_CIPHER_iv_length.html.  I made a couple modifications to the encrypt function so it would accept a non-constant input buffer and I added a parameter to select encrypt or decrypt.  The modified function is named cbccs_enc_dec.  I am using the 256-bit key CBC data from the NIST Special Publication 800-38A test vectors.

The main routine first encrypts all four test blocks (64 bytes) and then decrypts the encrypted data.  The encrypt routine copies the test vector PT byte array into an inbuf byte array.  inbuf is a pointer to the cbccs_enc_dec function (encrypt selected).  The ciphertext data is returned in the outbuf byte array and is printed using the BIO dump (applink).  The outbuf array is then copied to the inbuf array and the cbccs_enc_dec function is called again with decrypt selected.  The plaintext data is returned in the outbuf array and is printed.

Next I run the partial block test in a for loop.  I encrypt and then decrypt, in the same manner as above, the data plaintext vector from 49 to 63 bytes.  All of the tests return the correct plaintext data except for the test with 50 bytes.  In this case, the plaintext data in the first two blocks is correct, but the entire third block and partial fourth block are wrong.  I manually checked the encrypted data for this case and it appears to be correct.

I have attached the log file with the output and the C code.

"""
[cbc_cs1_test.c.txt](https://github.com/openssl/openssl/files/14068759/cbc_cs1_test.c.txt)
[log.txt](https://github.com/openssl/openssl/files/14068760/log.txt)

**Comment by jamuir** [comment]
what version of openssl are you using?

did you build openssl?  if so, then could you provide the output of `perl configdata.pm --dump`?

**Comment by bhight** [comment]
I am using the FireDaemon OpenSSL 3 installation (https://www.firedaemon.com/get-openssl).  Their version.txt file states openssl-3.2.0-0-gcf2877791c.  I'm not much of a programmer and it looked like trying to install from the source was not going to be trivial.

**Comment by jamuir** [comment]
In your code, if you change each `strncpy()` to `memcpy()`, then the failure goes away (i.e. all the generated plaintexts are correct, including the one for length 50).

`strncpy()` has special handling for null characters, so it shouldn't be used in this situation.

**Comment by jamuir** [comment]
not a bug.

**Comment by bhight** [comment]
jamuir,

Thanks for your help.  It's strange that strncopy was messing up only the one case.

**Comment by bhight** [comment]
Thanks again to jamuir.  No bug in openssl.
