### ISSUE TITLE
Newer than 3.0 versions of fipsinstall cannot install 3.0 FIPS module to avoid selftests running on each start up

### ISSUE THREAD

**Issue by wbl** [openssl/openssl#23400]
With changes to the fipsinstall command we cannot install a 3.0 FIPS module when using the 3.1 binary as the configuration file comes out different from when the 3.0 fipsinstall is used. We naively assumed that module compatibility meant the FIPS install process could use future binaries to achieve the install: this seems not to be the case. Is there a compatibility flag we can pass? In the alternative we'd have to extensively rework our internal packaging and releasing.

Relatedly having to run the fipsinstall command on every machine seems suboptimal: will this be relaxed in 3.1?

**Comment by t8m** [comment]
In 3.1, running the fipsinstall command will not be mandated by the security policy. Just using the fipsmodule.cnf file as generated by make install step will be sufficient.

**Comment by wbl** [comment]
Good to know that won't affect us going forward, but it's still an issue for installing 3.0. Would you want a compatibility mode for that? We're going to have to build one and I'd be happy to contribute it.

**Comment by t8m** [comment]
Yes, it would a feature for master branch though. It would be nice if we could detect the version of the provider and if it was 3.0.x it would use the compat mode.

**Comment by richsalz** [comment]
I think if 3.1 requires 3.0 provider to have a 3.0 executable around, that is arguably a bug in 3.1 and you should fix it in 3.1

The project has said multiple times that you can use an older provider with a newer library, but breaking `fipsinstall` means that the promise doesn't really work.

**Comment by t8m** [comment]
@slontis or other @openssl/otc members Any opinions here?

**Comment by slontis** [comment]
The reason for the fipsinstall running on every machine was that it was running the self tests just once and setting the config to indicate this.
Due to changes in rules the self tests always run so that is no longer an issue.

**Comment by slontis** [comment]
As to the fipsinstall, are you using the 3.0 fips install or the 3.1 fips install exe with the FIPS 3.0 provider?

**Comment by wbl** [comment]
Let me explain a little more about how we package the software: we have a package that contains the FIPS provider and the configuration. However, we install a different package for the openssl executable and the openssl shared library. Right now that's 3.0.12 and 3.0.8. So the fipsinstall command gets run again, and if there is a difference between what it generates on the build machine and the install machine the installation errors.

What we'd like to do is run the 3.1 fipsinstall because that's the openssl binary with the FIPS 3.0 provider. Even if the security policy changes for the 3.1 provider, we still have this issue until that module goes through the process and we adopt it, and due to some patches we had to apply for performance this might get tricky.

**Comment by slontis** [comment]
So I guess we need to figure out if this is really allowed,
My personal opinion is that it feels a little bit wrong to be using the fips installer from 3.1 with the fips 3.0 provider. (Input from others welcome). i.e. I dont this fits in with a security policy.
@t-j-h do you have any thoughts on this?

**Comment by richsalz** [comment]
> Due to changes in rules the self tests always run so that is no longer an issue.

When did the rules change?

**Comment by slontis** [comment]
FIPS 140-3

**Comment by richsalz** [comment]
But you don't yet have a validated 140-3 module, and according to https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4282.pdf `fipsinstall` is outside the module boundary so there is no reason this cannot be made to work. As it standards right now, it is inconvenient to some users and, personal feelings aside, it doesn't square with the commitment that had been made.

**Comment by slontis** [comment]
It really depends on how the security policy is worded...

**Comment by richsalz** [comment]
> It really depends on how the security policy is worded...

Yes.  And I've read it multiple times. And just now I re-read Appendix A.

**Comment by slontis** [comment]
My comments related to self tests changing refer to the 3.1 FIPS provider.. self test behaviour for FIPS 140-2 validations wont change. 

The other way to avoid the fips install on each machine would be not to write out the field to the config saying that self tests have already run (this would of course mean they run every time on startup).

**Comment by richsalz** [comment]
So does the current release support the currently-validated FIPS module or not?  Right now it does not. It could. Fixing that would be more in line with the promise that the FIPS module will be forward-compatible, and it would be much less inconvneient to the current userbase.

**Comment by slontis** [comment]
**OTC: we are currently looking into this issue.**

**Comment by slontis** [comment]
The following steps appeared to work for me..

I just built 3.1.2 and 3.0.9 using the tar sources and then ran the following on both directories.
./config enable-fips
I then copied the 3.0.9/providers/fips.so file to 3.1.2.providers/fips.so
And then ran the following for 3.1.2
LD_LIBRARY_PATH=.  ./apps/openssl fipsinstall -module providers/fips.so -out providers/fipsmodule.cnf

And then did

./util/wrap/pl -fips apps/openssl list -provider-path providers -provider default -provider fips -providers

Are you doing something different to this?

**Comment by richsalz** [comment]
I would expect that to work.  Did the config file get updated with the digest and verification flag?

**Comment by slontis** [comment]
The fields
install-mac and install-status are not currently written out by 3.1. (This is because the related OpenSSL provider 3.1 does not do self tests just once). Which means the self tests run every time. With this scenario the .cnf file can be copied without running fips install on every machine.

Can you explain what scenario doesnt work?

**Comment by wbl** [comment]
Well, aren't its contents different from what the install instructions say to produce? As it is we process the fips module with its fipsinstall and then check the file is unchanged on install and rerunning: if it was possible to comply with a file that didn't need this we would have done that in the first place, but that wasn't our read of the security policy. Maybe the recent certificate revision has changed it.

**Comment by slontis** [comment]
In terms of the actual FIPS 140-2 the requirement is that the self tests run before using the module. 
The FIPS 140-2 IG also allows the scenario where the self tests are run just once (i.e. it is optional). So the instructions we have relate to running once. If these config items are not present then the self tests always run, which also meets the requirement..

So the options are either
1) We make 3.1 always generate these config items (they will just get ignored by 3.1 fips provider anyway).
2) The security policy for 3.0 is modified to allow this alternate setup. The option -self_test_onload does not write out the fields.

**Comment by slontis** [comment]
Just to be clear - you are not getting any error here? This is just about not having the field in the config file?

**Comment by wbl** [comment]
Not having that field and having two other fields that weren't in what came out in 3.0. I can upstream the patch to the behavior of the 3.1 fipsinstall so we can all see exactly what I did to make it work for us.

**Comment by slontis** [comment]
It is still not clear to me what steps you are doing, and what the result is.
Just showing me a patch doesnt give me any idea of why it is a problem. Especially since I can see it working without changing anything..

**Comment by wbl** [comment]
The problem is that the fips configuration generated by the 3.1 tool is different from the 3.0 tool, which suggests that it doesn't do what is required to comply with the security policy of 3.0.8 and 3.0.9. It's possible that we are being overly cautious here.

**Comment by richsalz** [comment]
We want to run the selftest once at system install.  Not every time a program starts.

**Comment by t8m** [comment]
> We want to run the selftest once at system install. Not every time a program starts.

Then unfortunately you have to use the 3.0 fipsinstall (at least for now).

It also won't be possible with 3.1 FIPS provider at all.

**Comment by richsalz** [comment]
> > We want to run the selftest once at system install. Not every time a program starts.
> 
> Then unfortunately you have to use the 3.0 fipsinstall (at least for now).

Is that your view or was that a formal OTC decision? (see https://github.com/openssl/openssl/issues/23400#issuecomment-1929221405)

Will you take a PR to bring back the current behavior for the 3.1 module?

Adding seconds of startup time to every OpenSSL FIPS application is not helpful to your community. In the 3.0 design meetings, being able to do this *once* was touted as a benefit after all.
 
> It also won't be possible with 3.1 FIPS provider at all.

Sure, but it's not yet validated and we have years until the 140-2 validation expires.

**Comment by t8m** [comment]
> > Then unfortunately you have to use the 3.0 fipsinstall (at least for now).
> 
> Is that your view or was that a formal OTC decision? (see [#23400 (comment)](https://github.com/openssl/openssl/issues/23400#issuecomment-1929221405))

This is a statement of the current state of the code. It does not say anything about possible future.

> Will you take a PR to bring back the current behavior for the 3.1 module?

I assume you mean a PR that allows creating a fipsmodule.cnf by new fipsinstall when running against the 3.0 FIPS module in such way that it is fully equivalent to a fipsmodule.cnf file running by 3.0 fipsinstall. Yes, I think such PR would be welcome. Whether such PR would be acceptable only for the master branch or whether it would be also OK for backporting to 3.2 and 3.1 stable branches is a question that would have to be answered by OTC.

**Comment by slontis** [comment]
It would be ok for the 3.1 fips provider to still have these fields in since they would be ignored anyway.
@paulidale  would have removed them since they were no longer needed (for the 3.1 version). So I dont see any harm in adding them back in to support the older 3.0, 3.08 fips providers. It would make sense to backport them to 3.1/3.2 if we are going to add this change to master.

**Comment by slontis** [comment]
Added the hold so it gets discussed next week.

**Comment by richsalz** [comment]
It sure does seem that removing the fields was a mistake/bug that affected forward/backward compatibility.

**Comment by t8m** [comment]
**OTC: If the patch autodetected the fips module version and did not require any additional options being added then the OTC hold would not apply and it could go through normal review proces.**

**Comment by paulidale** [comment]
The FIPS provider ought to be installed using the `fipsinstall` from the same version.
`fipsinstall` can and does change.  I have no expectation that a new `fipsinstall` should work with an older FIPS provider.

In fact, we ought to not support this.  The older version has been built to get the associated FIPS provider, use the same `fipsinstall`.  Maintaining backward compatibility is only going to cause pain.

**Comment by richsalz** [comment]
One could extend the argument to say the older FIPS provider should not be usable with the current library, and the project explicitly says otherwise. Requiring a mix of old provider, old library, old executable and *new* library is a burden on your downstream users that you should avoid. Fortunately, the OTC decided to allow that.

**Comment by slontis** [comment]
It will be up to the end user to decide if using a tool that is not part of the FIPS tarball to generate the config file is a good idea or not.

**Comment by wbl** [comment]
To be clear, we check the results of rerunning the tool against our generation with the version generated with the utility shipped with the FIPS module. Because of binary load paths and the like installing both the openssl utility and libraries from the fips module version and the new one is a real PITA, although potentially doable. I'd prefer to see a compatibility mode, and will work to autodetect the FIPS provider version.

**Comment by slontis** [comment]
The extra fields should make no difference at all, since the fips provider has no way of interpreting them, so it will silently ignore them (just like any other param that the provider doesnt know about).

 The only change you really need to do is make sure that the self test fields are present..
