### ISSUE TITLE
FIPS 140-3 - Required KAT for SHA2-256 appears to be missing

### ISSUE THREAD

**Issue by corkyduke** [openssl/openssl#23424]
3.0, 3.1, 3.2 FIPS Provider -> self_test_data.inc has the below:

static const ST_KAT_DIGEST st_kat_digest_tests[] =
{
    {
         OSSL_SELF_TEST_DESC_MD_SHA1,
         "SHA1",
         ITM_STR(sha1_pt),
         ITM(sha1_digest),
    },
    {
         OSSL_SELF_TEST_DESC_MD_SHA2,
         "SHA512",
         ITM_STR(sha512_pt),
         ITM(sha512_digest),
    },
    {
         OSSL_SELF_TEST_DESC_MD_SHA3,
         "SHA3-256",
         ITM(sha3_256_pt),
         ITM(sha3_256_digest),
    },
};

As per 10.3.A Cryptographic Algorithm Self-Test Requirements of FIPS 140-3 Implementation Guidance, 
"if the module implements a SHS function (FIPS 180-4), the following shall be the minimal requirements for SHS algorithms:
•	a CAST for SHA-1 is required;
•	**a CAST for SHA-256 is required;**
•	a CAST for SHA-224 is required if SHA-224 is implemented without SHA-256;
•	a CAST for SHA-512 is required;
•	a CAST for SHA-512/224 or SHA-512/256 is required if the SHA-512 CAST is not performed;
•	a CAST for SHA-384 is required if SHA-384 is implemented without SHA-512.

It would appear that the SHA-256 KAT is missing.  There is a SHA3-256 KAT, however FIPS 140-3 requires that there be a SHA2-256 KAT to be compliant.

**Comment by t8m** [comment]
We have a HMAC-SHA-256 self test so we should still be compliant under the 10.3.B  section of the FIPS 140-3 Implementation Guidance.

**Comment by t8m** [comment]
@slontis might want to further comment on this.

**Comment by t8m** [comment]
Please note that the HMAC-SHA-256 KAT is happening in integrity_self_test() function.

**Comment by slontis** [comment]
Yes, @t8m is correct - you only have to do it once.
@t8m there may be a requirement to test the algorithm used in the integrity check before using it. Can you read the 140-3 IG and see it this is correct..

**Comment by beldmit** [comment]
I think that I came across this requirement

**Comment by t8m** [comment]
> @t8m there may be a requirement to test the algorithm used in the integrity check before using it. Can you read the 140-3 IG and see it this is correct..

Yes, AFAIK such requirement is there and we comply with it.

**Comment by slontis** [comment]
The relevant statement in the FIPS 140-3 IG is the following on page 70.

"All underlying approved algorithms used within a higher-level algorithm shall be self tests, either with their own self test or as part of a self test for the higher level algorithm"

**Comment by slontis** [comment]
@corkyduke - I think this can be closed unless you have other questions?

**Comment by corkyduke** [comment]
Thanks for all of the analysis and assistance. I will close it.
