### ISSUE TITLE
OpenSSL 3.0.10 seems to have a bug in PEM_read_bio_PrivateKey

### ISSUE THREAD

**Issue by njbelf** [openssl/openssl#23445]
I am using a build that I built with FIPS on 64-bit Windows 10.

openssl version returns:
OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)

I execute the following command on a command prompt:

openssl ec -in <private key .PEM file>  -param_out -noout -text and I get the following:

<code>
Private-Key: (384 bit)
priv:

pub:

ASN1 OID: secp384r1
NIST CURVE: P-384
</code>

<p>
I use PEM_read_bio__PrivateKey() to read this private key in and found I was getting doman mismatches on my DH calculation.    I put some debug code in to dump the parameters  with EVP_PKEY_print_params and lo and behold it thinks my private key is a P-256 curve key.   
</p>
The code to read it is very simple:
<code>
	key_bio = BIO_new_file(location.c_str(), "r");
	BIO_reset(key_bio);
	PEM_read_bio_PrivateKey(key_bio, &private_key, nullptr, NULL);
</code>

Am I doing something wrong or is this a bug in PEM_read_bio_PrivateKey?

**Comment by t8m** [comment]
We would need an example of such broken private key file to be able to investigate further.

**Comment by njbelf** [comment]
I do not believe it is a broken private key file.   Openssel ec can read it fine.

**Comment by t8m** [comment]
Does it happen for you on any EC secp384r1 private key you just generate with `openssl ecparam -genpkey` ?

**Comment by njbelf** [comment]
No it does not anymore
