### ISSUE TITLE
Minor optimization to MD5 ARM64: constant 0xffff5bb1

### ISSUE THREAD

**Issue by Myriachan** [openssl/openssl#23466]
In the ARM64 assembly language implementation of MD5, there is the following two lines: https://github.com/openssl/openssl/blob/master/crypto/md5/asm/md5-aarch64.pl#L176C1-L177C80
```
        movz x11, #0x5bb1             // Load lower half of constant 0xffff5bb1
        movk x11, #0xffff, lsl #16    // Load upper half of constant 0xffff5bb1
```
I think that this can be optimized to one instruction, taking advantage of the happenstance that the high half is 0xFFFF:
```
        movn w11, #0xa44e             // Load constant 0xffff5bb1; takes advantage of 0xffff upper half
```
The destination here could be `x11` also because it's referenced as `w11` later; I'm not sure it affects performance.

**Comment by jamuir** [comment]
Would you consider opening a PR with your proposed changes?
