### ISSUE TITLE
Wrong release version for EVP_DigestSqueeze() in documentation

### ISSUE THREAD

**Issue by tobiasbrunner** [openssl/openssl#23461]
https://github.com/openssl/openssl/blob/ed0f79c7ae63f7f29c9bfce2e0f960f0803be350/doc/man3/EVP_DigestInit.pod?plain=1#L808-L809

This is not correct, `EVP_DigestSqueeze()` has not yet been in any release.

**Comment by shahsb** [comment]
@tobiasbrunner @mattcaswell @t8m - I've fixed it in https://github.com/openssl/openssl/pull/23467

Could you please take a look?

**Comment by tobiasbrunner** [comment]
@shahsb That's not correct either as `EVP_MD_CTX_dup()` has already been released, probably with 3.1. Although, the docs on that are not consistent as the [3.1 man page claims](https://www.openssl.org/docs/man3.1/man3/EVP_MD_CTX_dup.html) it's 3.1, while the [3.2 man page claims](https://www.openssl.org/docs/man3.2/man3/EVP_MD_CTX_dup.html) it's 3.2.
