### ISSUE TITLE
Can't use EVP_CIPHER_CTX array

### ISSUE THREAD

**Issue by CryptoBIUUser** [openssl/openssl#2348]
Hi,

I'm using CentOS 7 and OpenSSL v1.1.0.
When I'm trying to use EVP_CIPHER_CTX as an array, my code does not compile.
I understand that this is caused by making the structures opaque.
Is there any way to reference the structure as array.
code snippet is attached below.

```
static void InitAESKey(AES_KEY_CTX* ctx, BYTE* keybytes, int numkeys)
        {
                BYTE* pBufIdx = keybytes;
                for (int i = 0; i < numkeys; i++)
                {
                        OTEXT_AES_KEY_INIT(ctx + i, pBufIdx);
                        pBufIdx += AES_KEY_BYTES;
                }
        }
```

While `OTEXT_AES_KEY_INIT` is macro defined like this:
```
#define OTEXT_AES_KEY_INIT(ctx, buf) { \
        EVP_CIPHER_CTX_init(ctx); \
        EVP_EncryptInit_ex(ctx, EVP_aes_128_ecb(), NULL, buf, ZERO_IV); \
        }
```

**Comment by mattcaswell** [comment]
Not sure what an `AES_KEY_CTX` is, but I'm assuming it is a synonym for `EVP_CIPHER_CTX`. You cannot create an array of `EVP_CIPHER_CTX`. You can however make an array of `EVP_CIPHER_CTX *`.

This isn't a bug in OpenSSL so would be better raised on the openssl-users email list (https://mta.openssl.org).
