### ISSUE TITLE
iOS: Support Apple Privacy Manifest 

### ISSUE THREAD

**Issue by SergeyChereshnyuk** [openssl/openssl#23494]
Hi Tema,

Apple has mandated that all third-party SDKs must include a privacy manifest and digital signature starting in spring 2024. More details here: https://developer.apple.com/news/?id=r1henawx

It would be good to add a privacy file to be ok with Apple's new requirements. Without it, all iOS applications that use OpenSSL will not be able to submit new versions in AppStore in spring.

**Comment by slontis** [comment]
Would something similar to 
https://boringssl.googlesource.com/boringssl/+/refs/heads/master/PrivacyInfo.xcprivacy
be sufficient here..

**Comment by manwithsteelnerves** [comment]
As OpenSSL isn't using any required reason api's, adding .xcprivacy file can be optional. It doesn't make sense to insist to have empty privacy file as it will have no data to influence the final merged file.

Considering the successful submission (for many) with AFNetworking (it's deprecated, no usage of required reason apis and doesn't include xcprivacy in the framework), I think we can ignore adding the file.

Will confirm in couple of days post submission!

**Comment by mattcaswell** [comment]
Since #24260 has been merged (some while ago) I think this can now be closed.
