### ISSUE TITLE
Missing calls to SSLerr in ALPN set functions.

### ISSUE THREAD

**Issue by wahern** [openssl/openssl#235]
Neither SSL_CTX_set_alpn_protos nor SSL_set_alpn_protos update the error stack when OPENSSL_malloc fails.

Should probably add something like:
SSLerr(SSL_F_SSL_CTX_ALPN_PROTOS, ERR_R_MALLOC_FAILURE);

**Comment by richsalz** [comment]
fixed in master with 72e9be3

**Comment by nick599** [comment]
@richsalz Can this issue be closed now?

**Comment by nick599** [comment]
This closes #235

**Comment by richsalz** [comment]
thanks!
