### ISSUE TITLE
The recent no-atexit support is failing in CI

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#23505]
There was a new option no-atexit added recently by PR #23394

The builds (which are in Run-checker daily CI) of configuration with no-atexit are failing in test_shlibload:
https://github.com/openssl/openssl/actions/runs/7810611466/job/21304298339

```

readline() on closed filehandle $fh at test/recipes/90-test_shlibload.t line 69.
not ok 2
# ------------------------------------------------------------------------------
readline() on closed filehandle $fh at test/recipes/90-test_shlibload.t line 69.
not ok 4
# ------------------------------------------------------------------------------
readline() on closed filehandle $fh at test/recipes/90-test_shlibload.t line 69.
not ok 6
# ------------------------------------------------------------------------------
readline() on closed filehandle $fh at test/recipes/90-test_shlibload.t line 69.
not ok 8
# ------------------------------------------------------------------------------
# Looks like you failed 4 tests of 10.90-test_shlibload.t ..................... 
Dubious, test returned 4 (wstat 1024, 0x400)
```

**Comment by t8m** [comment]
@rsbeckerca Would you be able to look at this?

**Comment by rsbeckerca** [comment]
This test works correctly under Cygwin64.

**Comment by rsbeckerca** [comment]
@t8m Need a suggestion on proceeding. Cannot reproduce.

**Comment by t8m** [comment]
I assume it reproduces on Linux only.

**Comment by nhorman** [comment]
The problem is occuring because the shlibload tests rely on atexit handlers getting run to output symbol information to a text file that gets parsed by the test harness recipe.   With no-atexit specified, the handler never runs, the symbol file never gets written and the test recipe fails on trying to close a file handle for a non-existant file.

Most reasonable fix seems to be just skipping the tests if no-atexit is built.

**Comment by rsbeckerca** [comment]
> The problem is occuring because the shlibload tests rely on atexit handlers getting run to output symbol information to a text file that gets parsed by the test harness recipe. With no-atexit specified, the handler never runs, the symbol file never gets written and the test recipe fails on trying to close a file handle for a non-existant file.
> 
> Most reasonable fix seems to be just skipping the tests if no-atexit is built.

Ok. Working on that path.

**Comment by nhorman** [comment]
I've got it

**Comment by rsbeckerca** [comment]
> @nhorman I've got it

You sure? I'm almost done ;)

**Comment by rsbeckerca** [comment]
@nhorman Will undo. Thanks for handling this.
