### ISSUE TITLE
MSVC and 'test/json_test.c'

### ISSUE THREAD

**Issue by gvanem** [openssl/openssl#23516]
Building from `git master` today and with MSVC and this new QLOG feature:
  `Configure enable-unstable-qlog ...`, 

has some C-issues. Compiling `test/json_test.c`. there are bundles of errors like:
```c
json_test.c(154): error C2099: initializer is not a constant
json_test.c(154): warning C4047: 'initializing': 'const char *' differs in levels of indirection from 'unsigned __int64'
json_test.c(159): error C2099: initializer is not a constant
...
```

The statements at line 152-154 expands and [Astyle](https://astyle.sourceforge.net/)-ed to:
```c
static const struct script_info *get_script_null (void)
{
  const char *const script_name = "null";
  const char *const script_title = "\"serialize a single null\"";
  static const struct script_word script_words[] = {
    { ( (void *) 0), (OPK_INIT_FLAGS) },
    { ( (void *) 0), (0) },
    { ( (void *) 0), (OPK_CALL) },
    { ( (void *) 0), 0, 0, 0, (void (*) (void)) (ossl_json_null) }, 
    { ( (void *) 0), (OPK_END) },
  };

  static const struct script_info script_info = {
    script_name,  
    script_title,
    script_words,  
    (sizeof (script_words) / sizeof ( (script_words) [0])),
    ("null"),
    (sizeof ("null") - 1)
  };
  return &script_info;
}
```

The `cl` compiler doesn't say which `initializer is not a constant`. (or it could be some issue with the expansion of some macro?)

Using `clang-cl` to build these tests is no problem. But adding `-clang:-pedantic -clang:-std=c89 -Wpedantic` to my `CFLAGS`,
 I'd expect some hints for this issue. Like `warning: initializer element is not computable at load time`.
But there's no warning. Hence I'm lost on this and have removed `enable-unstable-qlog` from my build.

I'm on Win-10, using `cl` ver. 14.39.33519 (x64).
And `clang-cl` ver. 17.0.1.

**Comment by hlandau** [comment]
Curious. We do test MSVC in CI. I'll look into this.

**Comment by gvanem** [comment]
@hlandau 
```
perl.exe -I. -I./util/perl -I./crypto/perlasm -I./crypto/bn/asm -I./crypto/des/asm 
  Configure VC-WIN64A-ONECORE
  enable-quic no-makedepend enable-tls1_3 enable-md2 enable-asm 
  enable-brotli enable-zlib enable-zstd enable-crypto-mdebug enable-trace 
  no-ec_nistp_64_gcc_128 enable-unstable-qlog enable-asan enable-aria 
  enable-rc5 enable-heartbeats
  --prefix=F:/MinGW32/src/inet/Crypto/OpenSSL 
  --openssldir=F:/MinGW32/src/inet/Crypto/OpenSSL
Configuring OpenSSL version 3.3.0-dev for target VC-WIN64A-ONECORE
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created makefile.in
Created makefile
Created include\openssl\configuration.h
...
```
`perl configdata.pm --dump` [output](https://github.com/openssl/openssl/files/14206290/configdata-dump.txt).

It's this 10 year old Strawberry Perl ` uname='Win32 strawberry-perl 5.18.4.1 #1 Thu Oct  2 12:10:29 2014 i386'`

**Comment by hlandau** [comment]
> > We do test MSVC in CI.
> 
> With `enable-unstable-qlog`? Show me where.

Looks like this was an omission when adding qlog to CI. Will raise a PR.

**Comment by hlandau** [comment]
I have a resolution to this issue.
