### ISSUE TITLE
ECDSA sign verify failing

### ISSUE THREAD

**Issue by gsharma-ad** [openssl/openssl#23515]
### Discussed in https://github.com/openssl/openssl/discussions/23508

<div type='discussions-op-text'>

<sup>Originally posted by **gsharma-ad** February  7, 2024</sup>
Unable to verify signatures when signature is generated using OpenSSL 1.1.1 compatible code and verification is done using OpenSSL 3.0.8 compatible code or vice versa. 
**Please let me know why signature verification is failing in these cases. Below is the code snippet-:**

Common digest code
```
EVP_MD_CTX_init(md_ctx);
EVP_DigestInit(md_ctx, EVP_sha256());
EVP_DigestUpdate(md_ctx, (const void *)InData, InDataLen);
EVP_DigestFinal(md_ctx, digest, &dgst_len);
```
OpenSSL 1.1.1 compatible signing
```
ECDSA_sign(0, digest, dgst_len, OutData , OutDataLen, EVP_PKEY_get1_EC_KEY(ec));
```
OpenSSL 3.0.8 compatible signing
```
EVP_DigestSignInit(md_ctx, NULL, NULL, NULL, ec);
EVP_DigestSign(md_ctx, NULL, &sig_len, digest, dgst_len);
sig_value = (unsigned char*) OPENSSL_malloc(sig_len);
EVP_DigestSign(md_ctx, sig_value, &sig_len, digest, dgst_len);
memcpy(OutData, sig_value, sig_len);
*OutDataLen = sig_len;
```
OpenSSL 1.1.1 compatible verification
```
ECDSA_verify(0, digest, dgst_len, InData_signv ,InDataLen_signv, EVP_PKEY_get1_EC_KEY(ec));
```

OpenSSL 3.0.8 compatible verification
```
EVP_DigestVerifyInit(md_ctx, NULL, NULL, NULL, ec);
EVP_DigestVerify(md_ctx, InData_signv, InDataLen_signv, digest, dgst_len);
```</div>

Same key has been used for sign verify with OpenSSL 1.1.1 and OpenSSL 3.0.8.

**Comment by bernd-edlinger** [comment]
The openssl 3.0.8 code is wrong.
you should not pass the pre-computed sha256 hash to this function but the raw InData.
And your code will not work correctly because you compute two signatures and the
resulting sig_len is variable length for ECDSA, so it is possible that the first signature is
smaller than the second one, so that may fail because the allocated memory is too small.

**Comment by gsharma-ad** [comment]
> The openssl 3.0.8 code is wrong. you should not pass the pre-computed sha256 hash to this function but the raw InData.
> 
> P.S.: your OpenSSL 1.1.1 compatible verification will result in memory leak, you should use EVP_PKEY_get0_EC_KEY instead.

Thanks, it is working now.
