### ISSUE TITLE
3.2: Invoking PKCS7_verify() multiple times on the same data no longer possible

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#23561]
m2crypto has this selftest
    https://gitlab.com/m2crypto/m2crypto/-/blob/a746cef769151f680758e9b4edc78cc7fc9c7be5/tests/test_smime.py#L145

where it invokes PKCS7_verify() multiple times. In line 163 it supposed to fail (due to the callback set in line 155) and it does. Then the callback is cleared and verify is invoked again without a failure. Then in line 170 verify is invoked after the callback function has been invoked again without a parameter (so the default should be used, which should be the same as in line 165). This fails in 3.2.1 since commit
      30adf6d20900 ("Revert unnecessary PKCS7_verify() performance optimization")

If I comment the previous verify invocation in line 166 then the one in line 170 passes. OpenSSL sets "digest failure" as error code. 
Is it illegal to invoke PKCS7_verify() multiple times the way m2crypto does it or was the change more than just "unnecessary performance optimization"?

Sebastian

**Comment by t8m** [comment]
I would not call this a bug. If anywhere this is a bug in m2crypto which depends on this _optimization_. If any other BIO than memory BIO was passed PKCS7_verify() would not work if called multiple times on the same data BIO as there is missing a seek to the beginning of the BIO before the subsequent verify call. This should be handled in m2crypto.

**Comment by sebastianas** [comment]
Okay, thank. Let me forward this then.
