### ISSUE TITLE
Please add SSL_export_keying_material support for quic

### ISSUE THREAD

**Issue by textshell** [openssl/openssl#23560]
Currently calling SSL_export_keying_material on a quic connection SSL object results in an error (via ssl3_undef_enc_method used in the quic methods).

Using channel binding with quic should be possible.

It seems fairly simple to special case a quic connection in SSL_export_keying_material as is done in many other SSL_\* apis and delegate this to a quic specific function that can forward the call to `ctx.qc->tls` where the actual tls state is available.

**Comment by hlandau** [comment]
This appears to be a bug. Thanks for reporting it. Fix is in https://github.com/openssl/openssl/pull/23567 and should be in 3.2.2.
