### ISSUE TITLE
OpenSSL License still applied for some source files

### ISSUE THREAD

**Issue by schuetzle-vector** [openssl/openssl#23570]
Found in OpenSSL 3.2.1 and master branch.

The following files
* include/openssl/hpke.h
* crypto/hpke/hpke.c
* crypto/ec/asm/ecp_sm2p256-armv8.pl
* crypto/chacha/asm/chacha-loongarch64.pl

still seem to be released under the OpenSSL License instead of the Apache 2 license.

Is this intentional or can the files be released under Apache 2.0 as well?
Right now I assume that formally the OpenSSL license applies for OpenSSL 3 as well.

**Comment by mattcaswell** [comment]
This is an error. All files should be released under Apache 2.0

**Comment by shahsb** [comment]
@schuetzle-vector @t8m @mattcaswell - I've rolled out the fix for this. please review - #23576
