### ISSUE TITLE
SSL_set_mode(..., SSL_MODE_ENABLE_PARTIAL_WRITE) not working on quic stream

### ISSUE THREAD

**Issue by textshell** [openssl/openssl#23578]
SSL_set_mode does not seem to work right with quic streams.

I'm trying to set partial write mode with code similar to this:
```
SSL *stream = SSL_new_stream(quic_connection, 0);
SSL_set_mode(stream, SSL_MODE_ENABLE_PARTIAL_WRITE);
```
It seems that `ossl_ctrl_internal` exits out too early with quic streams, because `sc` is NULL, and the check via `IS_QUIC` is only done after the check for `sc`.

Moving the `IS_QUIC` check before the `sc` check seems to fix the problem.

I believe the problem exists on the master branch as well, but I'm testing on a branch from master from mid January.

**Comment by hlandau** [comment]
Thanks for the report. Fix in https://github.com/openssl/openssl/pull/23581.
