### ISSUE TITLE
Backport .gitignore changes

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#23574]
When the `master` branch adds new entries to `.gitignore` they should be backported to the supported release branches. Otherwise downstream users who do multi-branch development in one git tree will get spurious noise messages.

(And BTW, aren't you behind the names in not changing the name from master to main?)

**Comment by DimitriPapadopoulos** [comment]
Also, old entries still used in supported release branches, should not been removed from the _master_ branch. For example, I see that #20878 removed `/*.pc` after 3.2:
```diff
@@ -7,5 +7,4 @@
 /MINFO
 /TABLE
-/*.pc
 /rehash.time
 /inc.*
```

**Comment by dgbkn** [comment]
@t8m can we create github action for this bug,i wanted to contribute to this issue

**Comment by oliviagallucci** [comment]
Please LMK if there is anything I can do to help fix this issue :) I would like to contribute to this project for a class.

**Comment by t8m** [comment]
To fix this issue there needs to be pull requests created against the openssl-3.x branches which would backport the additions to .gitignore file from the master branch.

**Comment by oliviagallucci** [comment]
Ok cool. Working on this now

**Comment by dgbkn** [comment]
@t8m Please check i have opened the pull requests.

**Comment by t8m** [comment]
Backports are now completed.
