### ISSUE TITLE
micalg mismatch in EVP_MD_CTX_settable_params

### ISSUE THREAD

**Issue by commel** [openssl/openssl#23580]
The issue is in master documentation and before as well. 

https://www.openssl.org/docs/manmaster/man3/EVP_MD_CTX_settable_params.html

In section "Parameters":

"micalg" (OSSL_PARAM_DIGEST_KEY_MICALG) <UTF8 string> is defined, but `OSSL_PARAM_DIGEST_KEY_MICALG` does not exist.

However short below `OSSL_DIGEST_PARAM_MICALG` is mentioned, which exists. Should this be aligned towards the existing definition?

**Comment by tamtam96** [comment]
I think I have a bug
