### ISSUE TITLE
HTTPS Changing SSL/TLS Certificate Without Closing Connection

### ISSUE THREAD

**Issue by KFKMan** [openssl/openssl#23605]
i want to change SSL/TLS Certificate (On HTTPS Protocol)(both Client and Server Certificate) Without Closing Connection.

1- Create HTTPS Connection
2- Get String Data From Server With This Connection
3- Change Certificate for Both Server And Client
4- Get New String Data
5- .... Other Parts
(I Want No Any Connection Closing In This Steps)

You think why i need that? You can look at my [other issue](https://github.com/dotnet/runtime/issues/98304#issuecomment-1942297913) [https://github.com/dotnet/runtime/issues/98304#issuecomment-1942297913]

**Comment by t8m** [comment]
It is not possible to reauthenticate the server with TLS-1.3 as the authentication is done as part of the handshake and there is a handshake only at the beginning of the TLS-1.3 connection. In theory we could support re-authentication of the client on demand but it would be possible only if the client allows post-handshake authentication.

**Comment by KFKMan** [comment]
Thanks for your answer.

> In theory we could support re-authentication of the client on demand but it would be possible only if the client allows post-handshake authentication.

Can't we perform a re-handshake without closing the connection optionally in TLS 1.3? Can't OpenSSL control/prevent the feature of closing the connection at the end of the transaction in TLS 1.3? Or is this something that operating systems can do?

**Comment by t8m** [comment]
Ah, so you do not mean to do a renegotiation but establishment of a new SSL connection over the same TCP connection. That is definitely possible. If both peers shutdown the SSL connection this does not necessarily mean that the TCP connection must be closed. It is very well possible to start a completely new SSL handshake over the existing TCP connection. The libssl APIs already enable this. Of course both client and server applications would have to behave the same way and AFAIK it is not something that would be supported by HTTPS protocol.
