### ISSUE TITLE
ossl_quic_tx_packetiser_set_peer() always returns 1

### ISSUE THREAD

**Issue by nv-dmd** [openssl/openssl#23603]
In quic_txp.c function int ossl_quic_tx_packetiser_set_peer() always returns 1
```
int ossl_quic_tx_packetiser_set_peer(OSSL_QUIC_TX_PACKETISER *txp, const BIO_ADDR *peer)
{
    if (peer == NULL) {
        BIO_ADDR_clear(&txp->args.peer);
        return 1;
    }

    txp->args.peer = *peer;
    return 1;
}
```
But in the code where this function is used, the return value is checked
```
    /* Inform QTX of peer address. */
    if (!ossl_quic_tx_packetiser_set_peer(ch->txp, &ch->cur_peer_addr))
        return 0;
```

Does it really have to be this?

**Comment by hlandau** [comment]
It's not necessary with the current implementation, it is just a pattern that avoids the need for refactoring in case it can fail later. Not sure it's worth "fixing" this.

Always worth asking though, thanks for noting it.
