### ISSUE TITLE
ssl_set_new_record_layer(): redundant check or no check

### ISSUE THREAD

**Issue by nv-dmd** [openssl/openssl#23628]
There is a check s->session != NULL in the function ssl_set_new_record_layer() on line 1327 (ssl\record\rec_layer_s3.c). But on the line 1348 the pointer s is passed to the function ossl_get_max_early_data(), where s->session is dereferenced witout checking. 
It seems like the check s->session != NULL is redundant in ssl_set_new_record_layer().
Or need to add a check before calling the function ossl_get_max_early_data(), where s->session is dereferenced.

**Comment by t8m** [comment]
There must be a s->session when use_early_data is set. So this cannot really happen, however perhaps we could add an ossl_assert() check? @mattcaswell

**Comment by nv-dmd** [comment]
> There must be a s->session when use_early_data is set. So this cannot really happen, however perhaps we could add an ossl_assert() check? @mattcaswell

In this case, may be should just remove the redundant check s->session != NULL on the line 1327?

**Comment by mattcaswell** [comment]
That would be incorrect. It is *not* redundant. There are situations where `s->session` may be NULL such as when the SSL object has just been constructed (in which case `level == OSSL_RECORD_PROTECTION_LEVEL_NONE`).

On line 1348, the situation is different. We can only get here if `level == OSSL_RECORD_PROTECTION_LEVEL_EARLY` - in which case `s->session` is guaranteed to be non-NULL. An `ossl_assert()` as suggested by @t8m might be appropriate.

**Comment by nv-dmd** [comment]
Ok. Thank you very match. I created the issue to check my doubts. You explained everything clearly. I think that nothing need to do in this case. Can I close the issue?

**Comment by mattcaswell** [comment]
Closing.
