### ISSUE TITLE
EVP_PKEY_base_id(pkey) is 0，EVP_DigestVerifyFinal fail

### ISSUE THREAD

**Issue by Nichanghao-xiaohao** [openssl/openssl#23636]
Using the following code, the public key can be correctly imported, but the output of EVP_PKEY_base_id(pkey) is 0. When continuing to use EVP_DigestVerifyFinal, an error occurs: ossl_sm2_internal_verify:reason(104):/usr/src/debug/openssl/3.1.0-r0/crypto/sm2/sm2_sign.c:488:
`
int main() {
    EVP_PKEY *pkey = NULL;
    OSSL_PARAM_BLD *param_bld = NULL;
    OSSL_PARAM *params = NULL;
    BIGNUM *x = NULL, *y = NULL;
    unsigned char public_key[65];
    public_key[0] = 0x04;

    if (!BN_hex2bn(&x, "529387D6912A3394521BA49A9EC4E2E713165CBDB241A0286F9D80EFFA207637") ||
        !BN_hex2bn(&y, "ED40BF2954B37341254F6EFA8E415D63DCD366A9307E1BC7032D2F7B42CC3E6E")) {
        std::cerr << "Error converting hex to BIGNUM.\n";
    }

    BN_bn2binpad(x, public_key + 1, 32);
    BN_bn2binpad(y, public_key + 1 + 32, 32);
    EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new_from_name(NULL, "SM2", NULL);
    if (!pctx)
    {
        std::cerr << "Error creating EVP_PKEY_CTX.\n";
    }
    param_bld = OSSL_PARAM_BLD_new();
    if (!param_bld) 
    {
        std::cerr << "Error creating OSSL_PARAM_BLD.\n";
    }
    if (!OSSL_PARAM_BLD_push_utf8_string(param_bld, OSSL_PKEY_PARAM_GROUP_NAME, "SM2", 0))
    {
        std::cerr << "Error setting group name." << std::endl;
    }
    
    if (!OSSL_PARAM_BLD_push_octet_string(param_bld, OSSL_PKEY_PARAM_PUB_KEY, public_key, 65))
    {
        std::cerr << "Error pushing public key to param builder.\n";
    }
    
    params = OSSL_PARAM_BLD_to_param(param_bld);
    if (EVP_PKEY_fromdata_init(pctx) <= 0 ||
        EVP_PKEY_fromdata(pctx, &pkey, EVP_PKEY_PUBLIC_KEY, params) <= 0) {
        ERR_print_errors_fp(stderr);
        std::cerr << "Error: EVP_PKEY_fromdata failed\n";
    }

    FILE *pem_file = fopen("sm2_pubkey.pem", "w");
    if (pem_file == NULL) {
        std::cerr << "Error: Cannot open file\n";
    }
    PEM_write_PUBKEY(pem_file, pkey);
    EVP_MD_CTX *md_ctx = EVP_MD_CTX_new();
    EVP_PKEY_CTX* pkeyCtx = EVP_PKEY_CTX_new(pkey, NULL);
    std::cerr << "111: " << EVP_PKEY_base_id(pkey) << std::endl;
    EVP_DigestVerifyInit(md_ctx, &pkeyCtx, EVP_sm3(), NULL, pkey);
    if(EVP_DigestVerifyUpdate(md_ctx, "1234567812345678", 16))
    {
        ERR_print_errors_fp(stderr);
    }
    
    return 0;
}
`

**Comment by t8m** [comment]
Let's keep the discussion in the original discussion thread. (https://github.com/openssl/openssl/discussions/23629) There is no need to open a new issue.
