### ISSUE TITLE
TLS handshake fails(radsecproxy) with OpenSSL 3.0.8 but succeeds with OpenSSL 1.1.1t

### ISSUE THREAD

**Issue by SatheshkA** [openssl/openssl#23658]
Radsecproxy application is unable to establish secure connection with the RADSEC server. The TLS handschake fails with failed: error:0A000086:SSL routines::certificate verify failed . However with OpenSSL 1.1.1t the TLS handshake succeeds, without changing anything.

Radsecproxy version : v1.9.1

**Comment by SatheshkA** [comment]
Platform: openwrt
In openssl 1.1.1t root CA certificate issue was not happen, after upgrading openssl to 3.0.8 we could observe these issue.

**Comment by t8m** [comment]
I am sorry but this is not enough information to be able to help you. Either there is some problem with the certificate chain, or the root CA is not present in the trust store for the 3.0.8 version, which could happen if the build configuration for the 1.1.1t and 3.0.8 is different, i.e. has different OPENSSLDIR.
