### ISSUE TITLE
[rt.openssl.org #3884] [PATCH] Add support for Win64 in o_str.c

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2366]
Migrated from [rt.openssl.org#3884](https://rt.openssl.org/Ticket/Display.html?id=3884) (status was 'new')

Requestors:
* tshort@akamai.com

Attachments:
* [0003-Add-support-for-Win64-in-o_str.c.patch](https://rt.openssl.org/Ticket/Attachment/54066/31801/0003-Add-support-for-Win64-in-o_str.c.patch)

From tshort@akamai.com on 2015-05-30 07:48:32:
```
Hello OpenSSL Org:

This is a change that Akamai has made to its implementation of OpenSSL.

Version: master branch
Description:  Add support for Win64 in o_str.c

OPENSSL_SYS_WIN64 is missing in a check for windows.

Github link:

https://github.com/akamai/openssl/commit/a4204b839be4b33cd0f4e7e2639aae6384e1c2d7

And attachment.

Thank you.
--
-Todd Short
// tshort@akamai.com
// âOne if by land, two if by sea, three if by the Internet.â
```

**Comment by richsalz** [comment]
@tmshort is this still an issue?

**Comment by kaduk** [comment]
After commit 7233bea26350d0541909a2fe30e87a95327fb065 the strings.h include is gone, so this can be closed.
