### ISSUE TITLE
Generated file params_idx.c  is non-deterministic

### ISSUE THREAD

**Issue by nanonyme** [openssl/openssl#23672]
We found with OpenSSL 3.2.1 that generated file params_idx.c is not deterministic. This results in breakage of OpenSSL debuginfo reproducibility. diffoscope output in https://gitlab.com/freedesktop-sdk/freedesktop-sdk/uploads/f54f9019c1351af40fa950e4843c08a7/artifacts.zip

**Comment by slontis** [comment]
Generatating params_idx.c multiple times does seem to result in different results.. Note that they are 'equivalent' in terms of .o files since the values that change have multiple mappings to the same number. I assume this is related to the unordered nature of perl hash tables.
