### ISSUE TITLE
Build failures in oss-fuzz

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#23673]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66975&q=openssl&can=2

It seems starting this morning we had 3 build failures (on openssl 3.0 3.1 and 3.2 in which the coverage report failed to generate

It seems the build of openssl completed successfully for each branch, but the reading of profile data for the coverage report failed.  the reason is unclear from the logs, but attempting to reproduce locally suggests that for some reason, the build of the fuzzers (with clang 15 in the container), produces profiling version 4 data, which the fuzzing infrastructure attempts to manually upgrade to version 7, but fails.

Unsure how to continue here, as the builder container is taken from a base container maintained by oss-fuzz.  This may be a transient error that will get fixed with a container update, but I wanted to record it here in the event that its an ongoing issue.

**Comment by bernd-edlinger** [comment]
Thanks for pointing that out,
this seems to be an unexpected side-effect of my attempt to fix the out of disk space issue in our CIFuzz builds:
https://github.com/google/oss-fuzz/commit/2144b19fa6b101e1fec8f1893aba37024ab93479

**Comment by bernd-edlinger** [comment]
Probable fix in https://github.com/google/oss-fuzz/pull/11638

**Comment by nhorman** [comment]
issue auto closed on oss fuzz, thanks @bernd-edlinger !
