### ISSUE TITLE
Trust Anchor for CMP IR

### ISSUE THREAD

**Issue by sumanth797** [openssl/openssl#23706]
Hi,
I'm performing CMP IR operation by setting the CMP CTX APIs.

But I don't have the trust anchor for setting it to CMP_CTX for performing IR. we have gone through the docs and tried using the OSSL_CMP_CTX_set_option(cmpCtx, **OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR**, 1); so that extracerts output that is generated as part of IR will be used as trust anchor.  So, I'm not setting the **OSSL_CMP_CTX_set0_trustedStore** , thinking after setting that option(**OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR**)  will be enough to perform IR, but IR is failing saying, 
**00C73F5B8D7F0000:error:1D0000B3:CMP routines:OSSL_CMP_validate_msg:missing trust anchor:crypto/cmp/cmp_vfy.c:624:
00C73F5B8D7F0000:error:1D00008C:CMP routines:ossl_cmp_msg_check_update:error validating protection:crypto/cmp/cmp_vfy.c:716:**

Since we **don't have trust anchor CA cert** how can we achieve **IR**. **Also, we don't want to use the Preshared Key and reference number (OSSL_CMP_CTX_set1_referenceValue, OSSL_CMP_CTX_set1_secretValue)**.

**Is there any way we can get trust anchor on the go?**

Thanks in advance.

**Comment by DDvO** [comment]
The `OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR` is just a quirk to support some legacy 3GPP feature.
It is not advisable to use, which I'm going to make more clear in the doc.

> **Is there any way we can get trust anchor on the go?**

Are you aware that this is dangerous?
Note that the certificate received in the extraCerts field has not been authenticated at all.
Taking it over as a trust anchor (TA) implements trust-on-first-use (TOFU) and can go pretty wrong
unless the client can verify by some other means that this cert is authentic and acceptable to use as a TA.

Don't you have a better way of (securely) obtaining a trust anchor beforehand?

**Comment by DDvO** [comment]
Nevertheless, it turns out that when adding the check leading to the error quoted above 
in #19729, I made a mistake, which is going to be fixed by #23814.

For the time being, as a workaround you can add a dummy trust store to the client to make the call succeed
If you still **really** want/need to use `OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR)`.

**Comment by sumanth797** [comment]
Hi @DDvO ,
Thanks for the reply, For time being can you suggest us how to add dummy trust store on the client side to make it succeed. 
Any steps?

**Comment by DDvO** [comment]
> For time being can you suggest us how to add dummy trust store on the client side to make it succeed. Any steps?

`X509_STORE *store = X509_STORE_new();`

**Comment by sumanth797** [comment]
Hi @DDvO ,

This is how i tried using dummy trust store,

OSSL_CMP_CTX_set_option(cmpCtx, OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR, 1);

X509_STORE *store = X509_STORE_new();
if (!OSSL_CMP_CTX_set0_trustedStore(cmpCtx, store))
{
  std::cout << "CMPClient:CMPIRRequest::setting OSSL_CMP_CTX_set0_trustedStore failed.\n";
}

And then i executed IR, and it failed,

0027DBF4427F0000:error:1D000091:CMP routines:check_msg_find_cert:no suitable sender cert:crypto/cmp/cmp_vfy.c:518:for msg sender name = /C=FI/O=MN/CN=RootCA
0027DBF4427F0000:error:1D00008C:CMP routines:ossl_cmp_msg_check_update:error validating protection:crypto/cmp/cmp_vfy.c:716:

Am I missing something for dummy store?

**Comment by DDvO** [comment]
Does the response meet the documented conditions?
> If the option OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR was set by calling
L<OSSL_CMP_CTX_set_option(3)>, for an Initialization Response (IP) message
any self-issued certificate from the I<msg> extraCerts field may be used
as a trust anchor for the path verification of an 'acceptable' cert if it can be
used also to validate the issued certificate returned in the IP message.

The following option allows tracing the validation of the protection of the response message:
```
OSSL_CMP_CTX_set_log_verbosity(cmpCtx , OSSL_CMP_LOG_TRACE)
```
