### ISSUE TITLE
TLS1.3 ClientHello's handshake version issue

### ISSUE THREAD

**Issue by SmallTown123** [openssl/openssl#23702]
The RFC document specification for the ClientHello message legacy_version field is as follows:

legacy_version: In previous versions of TLS, this field was used for
version negotiation and represented the highest version number
supported by the client. Experience has shown that many servers
do not properly implement version negotiation, leading to "version
intolerance" in which the server rejects an otherwise acceptable
ClientHello with a version number higher than it supports. In
TLS 1.3, the client indicates its version preferences in the
"supported_versions" extension ([Section 4.2.1](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.1)) and the
legacy_version field MUST be set to 0x0303, which is the version
number for TLS 1.2. TLS 1.3 ClientHellos are identified as having
a legacy_version of 0x0303 and a supported_versions extension
present with 0x0304 as the highest version indicated therein.
(See [Appendix D](https://datatracker.ietf.org/doc/html/rfc8446#appendix-D) for details about backward compatibility.)

However, when we test in openssl 3.1.2 server, we found that when the legacy_version field is 0x0301,0x0302,0x0304, or even a random value, the server still responds normally.

This seems to be inconsistent with the RFC8446 document specification, and furthermore, does this pose a new security threat?

**Comment by davidben** [comment]
The text you cite discusses rules for the sender, not the receiver. Can you elaborate on what kind of security threat you're concerned about here?

**Comment by davidben** [comment]
Further on the specification says:

>    If this extension is present in the ClientHello, servers MUST NOT use
>   the ClientHello.legacy_version value for version negotiation and MUST
>   use only the "supported_versions" extension to determine client
>   preferences.

I suppose one could argue that, having negotiated TLS 1.3, the `ProtocolVersion legacy_version = 0x0303;` line in the structure definition (but not the text you cited) goes into effect. But it's a bit unclear and I don't think there's any significant consequence either way here.

**Comment by davidben** [comment]
> But it's a bit unclear and I don't think there's any significant consequence either way here.

Actually, there is one consequence. Doing as you suggest means we forever prevent the protocol from reviving the `legacy_version` field in the future. So that's probably not desirable.

**Comment by SmallTown123** [comment]
@davidben , Thank you for your reply, I got it.

**Comment by mattcaswell** [comment]
This behaviour is deliberate, so we don't plan to make any changes here.
