### ISSUE TITLE
d2i_X509 functions unpredictible refcount decrement of passed in object in error case

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#23713]
This affects all ref-counted objects: X509, X509_REQ and X509_CRL
and the functions d2i_X509(), d2i_X509_ALT(), d2i_X509_REQ(), d2i_X509_CRL and
further complicates the semantic of corresponding PEM_read_ function family
similar to #22780 just with the additional problem that if a ref-counted object
is passed in with more than one reference, it is possible that the ref-count of the
object is sometimes decremented and sometimes not decremented, but the pointer
is only set to NULL if the last reference was deleted.
so most likely a double free will be the result.

The problem is that most d2i functions are implemented using this function:
https://github.com/openssl/openssl/blob/2d70cc9cecf8b322d795985efecee06242b203b3/crypto/asn1/tasn_dec.c#L114-L121
so when any error happens, the passed in object is deleted by `ASN1_item_ex_free(pval, it); `
But in case this is a reference counted object and this is not the last reference that is detected here:
https://github.com/openssl/openssl/blob/2d70cc9cecf8b322d795985efecee06242b203b3/crypto/asn1/tasn_fre.c#L86-L93
so the reference count is decremented but it was not the last reference, now the `*pval` is not set to NULL,
while in all other cases this code does set the passed in `*pval` to NULL:
https://github.com/openssl/openssl/blob/2d70cc9cecf8b322d795985efecee06242b203b3/crypto/asn1/tasn_fre.c#L114-L117
To further complicate the situation there are is also the function `d2i_X509_AUX` here:
https://github.com/openssl/openssl/blob/2d70cc9cecf8b322d795985efecee06242b203b3/crypto/x509/x_x509.c#L207-L216
where the passed in reference is not decremented in case of error, and the `*pval` is again not set to NULL,
so from the caller's perspective it is impossible to decide what to do now.

**Comment by Sashan** [comment]
I think there are lot more problems in those code paths. just took a look at `CRYPTO_THREAD_lock_free()` function here:
```
132 void CRYPTO_THREAD_lock_free(CRYPTO_RWLOCK *lock) {
133     if (lock == NULL)
134         return;
135
136     *(unsigned int *)lock = 0;
137     OPENSSL_free(lock);
138
139     return;
140 }
```
looks like lines 136 and 137 are just swapped. I believe there is no point to call `OPENSSL_free(NULL);` I will keep poking around. But I don't know what to think about all that now.

**Comment by bernd-edlinger** [comment]
I would set the passed in reference to NULL in tasn_fre.c in both cases,
when it was the last reference and when it was not the last reference.
I would extend #22809 to cover the case of ref-counted objects, and
expect the application to store additional references elsewhere.

**Comment by t8m** [comment]
I wonder if there is any meaningful use of this API that would be broken by such change. Perhaps we should fix this only in a subsequent minor release, not in stable branches?

**Comment by bernd-edlinger** [comment]
> I wonder if there is any meaningful use of this API that would be broken by such change.

I doubt that very much.

If a caller passes in a ref-counted object, like the modified test case(s) in #22809 demonstrate,
he will be surprised (new test with idx&1 failed without the fix), and encounter a
double free at the same time, unless he did not clear the references in his error handling,
which implies a memory leak in other error cases.
