### ISSUE TITLE
SSL error differs for SSL_write()/SSL_sendfile() in broken pipe  scenario.

### ISSUE THREAD

**Issue by sergiusz-n** [openssl/openssl#23722]
After upgrading from openssl1.0.x in the application implementing some HTTPS server, we attempted to  substitiute `SSL_write()` calls  in favour of `SSL_sendfile()` . Skipping the details the transition went smoothly, however, some discrepancy was noticed in the discrepancy in a few failure scenarios.
For instance, TCP connection drop by the peer scenario while doing write operation
  - for `SSL_write()` ends up with `SSL_get_error() ==  SSL_ERROR_SYSCALL` and `errno == EPIPE`;
  - for `SSL_sendfile()` ends up with `SSL_get_error() == SSL_ERROR_SSL` and `errno == EPIPE`.

would it be better for `SSL_sendfile` to raise `SSL_ERROR_SYSCALL` error instead, considering the fact they mostly come out s _sendfile()_ system call. It was confusing (to say the least) to see `error:0A000114:SSL routines::uninitialized` for the session, where previous writes were successful.
The error handing is quite poor here in [ssl_lib.c](https://github.com/openssl/openssl/blob/openssl-3.2/ssl/ssl_lib.c#L2596), only `EAGAIN`/`EBUSY`/`EINTR` seem to be differentiated.
Please advise.

Definition of Done
```[tasklist]
### Tasks
- [x] Encode SSL_sendfile to raise SSL_ERROR_SYSCALL when epipe is returned from sendfile syscall
```

**Comment by nhorman** [comment]
Can you test with this PR please:
https://github.com/openssl/openssl/pull/23723
I think it will fix the discrepancy

**Comment by nhorman** [comment]
was the issue corrected with the patch?

**Comment by sergiusz-n** [comment]
@nhorman thanks for the quick response. the code changes seem to be promising. it will take a couple of days to verify it in practice. I'll get back to you once I am done.

**Comment by jay29387432** [comment]
There's also a breaking change between 3.1 and 3.2 with KTLS, nonblocking and SSL_write returning SSL_EROR_SSL and errno EAGAIN.
Version 3.1 didnt have this behaviour. It looks like it returned SSL_ERROR_WANT_WRITE directly.

Sidenote: The captcha for registering an account with github is insane. I dont want to spend 5 minutes clicking on dart-boards.

**Comment by sergiusz-n** [comment]
> was the issue corrected with the patch?

the patch has been tested against EPIPE failure scenario.
Although the `SSL_get_error()` is  become `SSL_ERROR_SYSCALL` with the patch applied, there is a tiny discrepancy remained.
 - for `SSL_write()`:  the error value retrieved via _ERR_peek_error()_ is equal to 0, and the system error is available in `errno` only. 
 - for `SSL_sendfile()`:  _ERR_peek_error()_ is non-zero (`0x80000020`), and  `ERR_GET_REASON(ERR_peek_error()) == errno` (EPIPE = 0x20)
 
 the question is  as follows: 
 in order to have a common error handling in the application what should be a reliable source  for error reason: `errno` or   `ERR_GET_REASON(...)`?
 Please advise.

**Comment by sergiusz-n** [comment]
I have just grep'd throughout the code and found that the pattern:
```c
ERR_raise_data(ERR_LIB_SYS, get_last_socket_error(),
      "calling some_socket_system_function()"); 
```
is widely used in `crypto/bio/*.c` files for the most of socket operations like _ioctl()_, _getsockopt()_, _accept()_, _connect()_ etc,  but never met when doing write/read. 
was it done intentionally or omitted?

**Comment by nhorman** [comment]
I believe thats being discussed in the PR

**Comment by nhorman** [comment]
ok, thank you for the clarification, so in both cases ERR_peek_error on the SSL_write case, regardless of the patch status returns 0 for you.  That makes more sense.

Though, its still confusing.  SSL_get_error calls ossl_ssl_get_error to determine the error return code, and SSL_ERROR_SYSCALL is returned if and only if the following conditions are met:
1) the passed in check_err parameter is 1 (which it is)
2) ERR_peek_error does _not_ return zero
3) The ERR_GET_LIB  value of the value returned from ERR_peek_error is ERR_LIB_SYS

That suggests to me that the error stack is being cleared between the time you call SSL_get_error and the time you call ERR_peek_error.

do you happen to have a small reproducer I can use to try this here?

**Comment by sergiusz-n** [comment]
@nhorman 

I have come up with some _artificial_  failure snippet based on sslecho client/server sample from the `demos` folder in the repo.
Please find it  [here](https://github.com/sergiusz-n/openssl/commit/d6ec5e4400403121e666999a938b97fbcdc84ea4).

**Comment by nhorman** [comment]
thank you, I see whats happening now.  Not sure theres a great way to bubble errno up to the SSL_write call, but let me see what I can come up with

**Comment by nhorman** [comment]
updated the PR to take care of this
