### ISSUE TITLE
CMP several SAN extensions in certificate request message

### ISSUE THREAD

**Issue by SevenInside** [openssl/openssl#23725]
Using openssl cmp for performing IR request, I faced a strange behavior. 
The authentication between the sender and the RA relies on a certificate trusted by the RA (cmp_identity_authentication.pem). I'm requesting a certificate matching the CSR in parameter. The CSR has two entries in the SAN: one dNSName and one URI.

```bash
$ openssl cmp -cmd ir -server mycmpserver -path cmp_profile -srvcert cmp_server_cert.pem -cert cmp_identity_authentication.pem -key cmp_identity_authentication.key -certout my_new_certificate.pem -newkey my_new_certificate.key -csr my_new_certificate.csr

cmp_main:apps/cmp.c:3077:CMP info: using section(s) 'cmp' of OpenSSL configuration file '/tmp/openssl-3.2.1/openssl.cnf'
cmp_main:apps/cmp.c:3085:CMP info: no [cmp] section found in config file '/tmp/openssl-3.2.1/openssl.cnf'; will thus use just [default] and unnamed section if present
setup_client_ctx:apps/cmp.c:2088:CMP info: will contact http://mycmpserver:80/cmp_profile 
CMP info: sending IR
CMP error: received error:code=500
CMP error: error receiving:server=http://mycmpserver:80
CMP error: transfer error:request sent: IR, expected response: IP
```

From the traces and from the RA logs, two SANs are present in the certificate request.
On RA logs: « repeated extension found: 2.5.29.17 »

From traces
![image](https://github.com/openssl/openssl/assets/6161813/f46a0586-55e0-4787-a2bf-172d56f2fa3b)

The extension `id-ce-subjectAltName (2.5.29.17)` appears twice. The first extension contains the value of the authentication certificate SAN (a single dNSName in my case). The second extension has the correct values from the CSR. Every other values from the IR request seem ok (public key, other extensions, etc.). Would it be possible to remove the SAN added by the authentication certificate from the demand?

I've faced this issue on `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)` and on `OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)`

**Comment by ayushiays** [comment]
Could observe the same behavior which was resolved by passing_-san_nodefault_ in the IR command.
Quoting from the CMP doc:

```
-san_nodefault
When Subject Alternative Names are not given via -sans nor defined via -reqexts, they are copied by default from the reference certificate (see -oldcert). This can be disabled by giving the -san_nodefault option.
```

 Looks like this has to be explicitly disabled.
