### ISSUE TITLE
[rt.openssl.org #3933] [PATCH] 1.0.2d engines/e_capi: enable the SHA-2 message digests

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2372]
Migrated from [rt.openssl.org#3933](https://rt.openssl.org/Ticket/Display.html?id=3933) (status was 'new')

Requestors:
* beat.bolli@isc-ejpd.admin.ch

Attachments:
* [0001-engines-e_capi-enable-the-SHA-2-message-digests.patch](https://rt.openssl.org/Ticket/Attachment/54813/32403/0001-engines-e_capi-enable-the-SHA-2-message-digests.patch)

From beat.bolli@isc-ejpd.admin.ch on 2015-07-10 10:47:31:
```
Hi

This patch is needed to support the modern TLSv1.2 cipher suites
with the Windows CryptoAPI. In ticket #3366, it has been submitted
earlier as part of someone else's patch but abandoned by its author.

I have tested it with 1.0.2d, but it should apply to all branches.

Thanks,
Beat Bolli
```

**Comment by FdaSilvaYY** [comment]
See also https://github.com/openssl/openssl/pull/1051
or https://github.com/openssl/openssl/pull/785
