### ISSUE TITLE
Add support for EVP_aes_192_xts

### ISSUE THREAD

**Issue by ironyman** [openssl/openssl#23742]
Can we add support EVP_aes_192_xts? Our team is trying to test with this key length for AES-XTS. I can make PR for this.

**Comment by mattcaswell** [comment]
IIUC the standard only specifies AES-128-XTS and AES-256-XTS. There is no specification for 192 bit. OpenSSL only implements standardised encryption algorithms - so, if I'm right, then 192 bit XTS would not be acceptable.
