### ISSUE TITLE
Mismatch in function signature between doc and header file for `SSL_group_to_name()`

### ISSUE THREAD

**Issue by romen** [openssl/openssl#23775]
The [documentation](https://www.openssl.org/docs/man3.2/man3/SSL_group_to_name.html) reports:

```c
const char *SSL_group_to_name(const SSL *ssl, int id);
```

but the header includes:

https://github.com/openssl/openssl/blob/74fd6823884e27c18ec3fe7bd99b9bc02e6f31f3/include/openssl/ssl.h.in#L1511

**Comment by romen** [comment]
This was noticed by @botovq in https://github.com/sfackler/rust-openssl/pull/2201#discussion_r1516756496

**Comment by nhorman** [comment]
I think this makes sense for master, but I'm not sure we can make the corresponding change in 3.1 or 3.2 as it would constitute an API change in a stable release

**OTC**: Can we modify a public api to qualify a type as const in a stable release

**Comment by mattcaswell** [comment]
> Can we modify a public api to qualify a type as const in a stable release

No, but we can change the documentation to match reality.

**Comment by nhorman** [comment]
fixed
