### ISSUE TITLE
EVP_PKEY_fromdata does not set EVP_PKEY's key management

### ISSUE THREAD

**Issue by afshinpir** [openssl/openssl#23808]
Hi All,

When I was trying to create an `EVP_PKEY` using `EVP_PKEY_fromdata()` method, I noticed something that I consider a potential bug. The problem is that `EVP_PKEY_fromdata()` does not set `pkey->keymgmt` to the key management that is created that key. Why it is important? Because if we don't, `EVP_PKEY_CTX_new_from_pkey` cannot detect key management from it. 

Here is a simplified example:
```
EVP_PKEY_CTX *ctx = NULL, *ctx2 = NULL;
OSSL_PARAM *params = NULL;
ctx = EVP_PKEY_CTX_new_from_name(NULL, "ec", "provider=myprovider");
EVP_PKEY_fromdata_init(ctx);
//setup params...
EVP_PKEY_fromdata(ctx, &pkey, OSSL_KEYMGMT_SELECT_ALL, params);
EVP_PKEY_CTX_free(ctx);

ctx2 = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, NULL); 
```
Here, key management for `ctx2` can be different from key management of `ctx` which I think can be considered an unwanted situation since internal structure of each pkey need to be managed by its own key management to prevent excessive export/import mechanisms.
If I use something like this:
```
ctx2 = EVP_PKEY_CTX_new_from_pkey(NULL, pkey, "provider=myprovider"); 
```
Everything is just fine and works perfectly, but a code like this removes generalization of the code. I mean by passing `NULL` as query string for `EVP_PKEY_CTX_new_from_pkey()`, you want to easily handle different keys from different providers.

Finally, from `EVP_PKEY_CTX_new_from_pkey()` implementation it seems that it want to consider obtaining key management from pkey as well:
https://github.com/openssl/openssl/blob/85cf92f55d9e2ac5aacf92bedd33fb890b9f8b4c/crypto/evp/pmeth_lib.c#L275-L284
But it seems it is a little tricky how we want to select these conditions. I think condition should be something like this:
```
        if (pkey != NULL && pkey->keymgmt != NULL && propquery == NULL) {
            if (!EVP_KEYMGMT_up_ref(pkey->keymgmt))
                ERR_raise(ERR_LIB_EVP, EVP_R_INITIALIZATION_ERROR);
            else
                keymgmt = pkey->keymgmt;
        } else {
            keymgmt = EVP_KEYMGMT_fetch(libctx, keytype, propquery);
        }
        if (keymgmt == NULL)
            return NULL;   /* EVP_KEYMGMT_fetch() recorded an error */
```
A condition like this helps to use pkey's key management if no query string is forced.

What do you think about this? Do you also think this should be considered as bug?

Best Regards

**Comment by nhorman** [comment]
I might be wrong here, but I think this is ok.  I'm looking at the head of the master branch for reference:

1) EVP_PKEY_CTX_new_from_name calls int_ctx_new, which finds the keymgmt provider and assigns it to ret/ctx -> keymgmt
2) EVP_fromdata_init calls fromdata_init, which confirms the ctx->keymgmt is assigned
3) evp_keymgmt_util_fromdata calls evp_keymgmt_util_fromdata->evp_keymgmt_util_assign_pkey ->EVP_PKEY_set_type_by_keymgmt , which assigns the keys keymgmt pointer  
4) EVP_PKEY_CTX_new_from_pkey, seeing that pkey has an assigned keymgmt pointer, uses that for assignment to the new CTX

So I think this makes sense, the context you establish in EVP_PKEY_CTX_new_from_name, is the one that gets copied to the pkey you create, and is then copied back to ctx2 on EVP_PKEY_CTX_new_from_pkey.

So I don't quite see a way for the context to be modified through that path

If you did want to modify the keymgmt provider, I believe you can explicitly call EVP_PKEY_set_type_by_keymgmt.

You said you noticed this while using EVP_PKEY_fromdata.  Do you mean to say that you actually observed a different keymgmt structure being used on the return from EVP_PKEY_fromdata?  Does your above example produce this observation?

**Comment by afshinpir** [comment]
@nhorman 
Hi,
Yes, I observed different key managements here. This is part of my main code.
The issue that I encountered was the fact that when I called `EVP_PKEY_sign_init` on the `ctx2`, the assigned key management was FIPS provider rather than my own provider.
I had FIPS, base and my provider loaded only without default provider.
I don't want to manually change key management, and I was expecting to see that the `ctx2` ends up with teh same key management as `ctx` which is the one that comes for `myprovider`. But it didn't work like that at least.

Best Regards

**Comment by nhorman** [comment]
ok, understood, thank you.  Unfortunately, without a more complete reproducer, I'm not quite sure how to determine what the 'right' thing to do here is (if in fact the current implementation isn't for some definition 'right').  Looking at your proposed changes to pmeth_lib, I'm also not sure I see how that helps the situation, as it adds control flow around the the specifying of a propquery, and your simplified reproducer code sets no properties in its call to EVP_PKEY_CTX_new_from _pkey.

Currently, as I see it, given the reproducer code, the keymgmt from the pkey when created is going to get reused when the new ctx is created.  I don't see how int_ctx_new will fetch a new keymgmt if it is provided in the pkey on entry to int_ctx_new.  Starting at the top:
```
if (id == -1) {     /*line 163*/
   if (pkey != NULL && !evp_pkey_is_provided(pkey) {
      id = pkey->type;
   } else {
      if (pkey != NULL) {
         keytype = EVP_KEYMGMT_get0_name(pkey->keymgmt);
      }
      if (keytype != NULL) {
         id = evp_pkey_name2type(keytype);
...
```
Starting on line 163 id starts as -1, and pkey is non-null (assuming we re running the call to EVP_PKEY_CTX_new_from_pkey).

evp_pkey_is_provided should return true, as we have a keymgmt pointer, indicating we fall into the else clause of the conditional, lookup a keytype, and assign id to the value of that type

```
/* If no ID was found here, we can only resort to find a keymgmt */
    if (id == -1) {   /* lline 188 */
```
id should no longer be -1 here, so we skip this clause

```
if (e != NULL)   /* line 208 */
        keytype = NULL;
 if (e == NULL && (pkey == NULL || pkey->foreign == 0))
        keytype = OBJ_nid2sn(id);
```
e was passed in as NULL, and pkey is non null, so we skip both of these clauses. You've also indicated that you're using providers so I'm assuming no application specified engine or application pmeth will be found

```
 if (e == NULL && app_pmeth == NULL && keytype != NULL) { /* line 246*/
        /*
         * If |pkey| is given and is provided, we take a reference to its
         * keymgmt.  Otherwise, we fetch one for the keytype we got. This
         * is to ensure that operation init functions can access what they
         * need through this single pointer.
         */
        if (pkey != NULL && pkey->keymgmt != NULL) {
            if (!EVP_KEYMGMT_up_ref(pkey->keymgmt))
                ERR_raise(ERR_LIB_EVP, EVP_R_INITIALIZATION_ERROR);
            else
                keymgmt = pkey->keymgmt;
        } else {
            keymgmt = EVP_KEYMGMT_fetch(libctx, keytype, propquery);
        }
        if (keymgmt == NULL)
            return NULL;   /* EVP_KEYMGMT_fetch() recorded an error */
...
```
we should have a keytype, no engine, and no app_pmeth, so we should fall into this clause, at which point we note that the pkey is not null and has a keymgmt pointer, at which point we up its reference count and use it in assigning the new context the pkeys keymgmt ops.

Is it possible for you to provide a more complete reproducer using the default and fips provider perhaps to illustrate the change in keymgmt you are observing?

**Comment by t8m** [comment]
This works as designed. The provider to be used for an operation is primarily defined by the property query and not by the place where the key was stored originally. Only in case the key is not exportable and the property query still allows it (i.e. contains only a preference) the original provider will be used.

**Comment by afshinpir** [comment]
What determines that key is not exportable? Not having export method implemented or returning `0` from export method? In my case, I can export public keys but not private keys. Should I return `0` when private key in selection is set?

**Comment by t8m** [comment]
> Not having export method implemented or returning `0` from export method?

Both ways work.

>  In my case, I can export public keys but not private keys. Should I return 0 when private key in selection is set?

Yes, that's the correct thing to do.
