### ISSUE TITLE
Unable to create EC private key using named curve SM2

### ISSUE THREAD

**Issue by rwfranks** [openssl/openssl#23816]
Unable to create EC private key using named curve SM2.

```
584 	checkerr( OSSL_PARAM_BLD_push_utf8_string( bld, OSSL_PKEY_PARAM_GROUP_NAME, "SM2", 0 ) );
585 	checkerr( OSSL_PARAM_BLD_push_BN( bld, OSSL_PKEY_PARAM_PRIV_KEY, qx=SV2BN(qx_SV) ) );
586 	params = OSSL_PARAM_BLD_to_param(bld);
587 	ctx = EVP_PKEY_CTX_new_from_name( libctx, "EC", NULL );
588 	checkerr( EVP_PKEY_fromdata_init(ctx) );
589 	checkerr( EVP_PKEY_fromdata( ctx, &RETVAL, EVP_PKEY_KEYPAIR, params ) );
590 	OSSL_PARAM_free(params);
```

EVP_PKEY_fromparams() fails with nothing written to the error stack.

```
ok 4 - set up SM2SM3 private key
libcrypto error (SEC.xs line 589) at blib/lib/Net/DNS/SEC/SM2.pm line 64.
# Looks like your test exited with 255 just after 4.
make: *** [Makefile:1109: test_dynamic] Error 255
```

OpenSSL 3.2.1 built from distribution tarball.
Fedora 39  x86_64 GNU/Linux

**Comment by nhorman** [comment]
the evp_extra_test2 has an SM2 test exercises SM2 (both todata, and fromdata), and it appears to pass.  can you please provide a reproducer that we can use to observe the problem your describing?

**Comment by rwfranks** [comment]
```
#include <stdio.h>
#include <openssl/core_names.h>
#include <openssl/param_build.h>
#include <openssl/bn.h>
#include <openssl/evp.h>
#define checkerr(x) if (!(x)) printf("error in " #x "\n")

int main()
{
        const char *privkey = "C3E0233E8EB9D0803C0D6784AB942A6762D6629B82FE878469868613566F2B20";
        BIGNUM *privbn = NULL;
        OSSL_LIB_CTX *libctx = NULL;
        OSSL_PARAM *params;
        OSSL_PARAM_BLD *bld = OSSL_PARAM_BLD_new();
        EVP_PKEY_CTX *ctx;
        EVP_PKEY *RETVAL = NULL;

        checkerr( BN_hex2bn(&privbn, privkey) );
        checkerr( OSSL_PARAM_BLD_push_utf8_string( bld, OSSL_PKEY_PARAM_GROUP_NAME, "SM2", 0 ) );
        checkerr( OSSL_PARAM_BLD_push_BN( bld, OSSL_PKEY_PARAM_PRIV_KEY, privbn ) );
        params = OSSL_PARAM_BLD_to_param(bld);
        ctx = EVP_PKEY_CTX_new_from_name( libctx, "EC", NULL );
        checkerr( EVP_PKEY_fromdata_init(ctx) );
        checkerr( EVP_PKEY_fromdata( ctx, &RETVAL, EVP_PKEY_KEYPAIR, params ) );  /* fails here */
        BN_clear_free(privbn);
        EVP_PKEY_CTX_free(ctx);
        OSSL_PARAM_free(params);
        OSSL_PARAM_BLD_free(bld);

        return 0;
}
```

**Comment by nhorman** [comment]
oh, I see the problem, you created an evp context using the name EC, which set your keymanagement to the general elliptic curve keymanagement, rather than the sm2 key management.  if you change this line:
```
ctx = EVP_PKEY_CTX_new_from_name( libctx, "EC", NULL );
```
to 
```
ctx = EVP_PKEY_CTX_new_from_name( libctx, "SM2", NULL );
```
It works as expected

**Comment by rwfranks** [comment]
Thanks.
This does not appear to be documented anywhere.

This was merely the hors d'œuvres before the main course!

**Comment by nhorman** [comment]
The documentation is somewhat vague on this, because the fan out of possible names that can handle the corresponding created keys is large, and the assumption is that a context that is capable of handling the created PKEY will be used.  We should probably an ERR in common_check_sm2 to indicate that a context not using an SM2 curve was requested for a key that has an SM2 curve applied.

In the future though, if you want to harden this code to errors like, this, it may be advisable to create the context with EVP_PKEY_CTX_new_from_pkey(). That api will create a context that is appropriate for whatever key type has been created, obviating the need to determine the key type in your application when creating the context

**Comment by rwfranks** [comment]
On Fri, 15 Mar 2024 at 15:27, Neil Horman ***@***.***> wrote:

> In the future though, if you want to harden this code to errors like,
> this, it may be advisable to create the context with
> EVP_PKEY_CTX_new_from_pkey(). That api will create a context that is
> appropriate for whatever key type has been created, obviating the need to
> determine the key type in your application when creating the context
>
 I fail to see how that would work given that the context is created before
the key:

        ctx = EVP_PKEY_CTX_new_from_name( libctx, "SM2", NULL );
        checkerr( EVP_PKEY_fromdata_init(ctx) );
        checkerr( EVP_PKEY_fromdata( ctx, &pkey, EVP_PKEY_KEYPAIR, params )
);

--rwf
