### ISSUE TITLE
SSL_shutdown() might incorrectly return EAGAIN on FreeBSD using KTLS resulting in data corruption

### ISSUE THREAD

**Issue by gstrauss** [openssl/openssl#23824]
SSL_shutdown() might incorrectly return EAGAIN on FreeBSD using KTLS.
Data corruption with large images and mp3 may also occur.

SSL_shutdown() *should not* return SSL_ERROR_SYSCALL with errno EAGAIN.
SSL_shutdown() should return SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE
if unable to read or write, respectively.

Note: SSL_shutdown() works as expected *without* KTLS.

Reported on machine:
FreeBSD 14
OpenSSL 3.0.12  (system provided)
network device: igb0 and igb1
ktls_ocf.ko is compiled into kernel
sysctl.conf
```
  # KLTS
  kern.ipc.tls.enable=1
  kern.ipc.mb_use_ext_pgs=1
```
Application: lighttpd web server (64-bit)
  (affects all versions of lighttpd since lighttpd 1.4.68, which first enabled KTLS)
Reporter noted:
Tested client is local Firefox ESR 115.8.0, lynx, and with my phone.

Even if lighttpd is patched to retry if SSL_shutdown() returns EAGAIN,
larger files (images and mp3) served by lighttpd are still being corrupted.

On issue reporter's machine with FreeBSD 14 and OpenSSL 3.0.12,
the issue reliably occurs, and has never worked.  (An older version of
FreeBSD or OpenSSL was not available for comparison.)

lighttpd has supported OpenSSL with KTLS on FreeBSD and Linux since
lighttpd 1.4.68 (released Jan 2023).  There have been no other reports to
lighttpd developers of this issue on FreeBSD in the past year.

I was not able to reproduce issue in a FreeBSD 14 virtual machine,
but have asked the original reporter to subscribe here to help answer
questions.

What steps might be taken to troubleshoot this further?

On issue reporter's machine:
```
> sysctl kern.ipc.tls.stats
kern.ipc.tls.stats.ocf.retries: 0
kern.ipc.tls.stats.ocf.separate_output: 1039
kern.ipc.tls.stats.ocf.inplace: 185
kern.ipc.tls.stats.ocf.tls13_chacha20_encrypts: 0
kern.ipc.tls.stats.ocf.tls13_chacha20_decrypts: 0
kern.ipc.tls.stats.ocf.tls13_gcm_recrypts: 0
kern.ipc.tls.stats.ocf.tls13_gcm_encrypts: 1224
kern.ipc.tls.stats.ocf.tls13_gcm_decrypts: 62
kern.ipc.tls.stats.ocf.tls12_chacha20_encrypts: 0
kern.ipc.tls.stats.ocf.tls12_chacha20_decrypts: 0
kern.ipc.tls.stats.ocf.tls12_gcm_recrypts: 0
kern.ipc.tls.stats.ocf.tls12_gcm_encrypts: 0
kern.ipc.tls.stats.ocf.tls12_gcm_decrypts: 0
kern.ipc.tls.stats.ocf.tls11_cbc_encrypts: 0
kern.ipc.tls.stats.ocf.tls11_cbc_decrypts: 0
kern.ipc.tls.stats.ocf.tls10_cbc_encrypts: 0
kern.ipc.tls.stats.destroy_task: 0
kern.ipc.tls.stats.ifnet_disable_ok: 0
kern.ipc.tls.stats.ifnet_disable_failed: 0
kern.ipc.tls.stats.switch_failed: 0
kern.ipc.tls.stats.switch_to_sw: 0
kern.ipc.tls.stats.switch_to_ifnet: 0
kern.ipc.tls.stats.failed_crypto: 0
kern.ipc.tls.stats.corrupted_records: 0
kern.ipc.tls.stats.active: 0
kern.ipc.tls.stats.enable_calls: 52
kern.ipc.tls.stats.offload_total: 52
kern.ipc.tls.stats.sw_rx_inqueue: 0
kern.ipc.tls.stats.sw_tx_inqueue: 0
kern.ipc.tls.stats.sw_tx_pending: 0
kern.ipc.tls.stats.threads: 32
```

**Comment by gstrauss** [comment]
corrupted image example:

![ktls-corrupted](https://github.com/openssl/openssl/assets/839103/7e1a0cca-395a-41c5-9951-8990b2eb43ef)

**Comment by gstrauss** [comment]
To rule out potential relation to #21202, reporter tested *without* `SSL_MODE_ENABLE_PARTIAL_WRITE` and *without* `SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER`.  This issue still occurs without those flags being specified in `SSL_CTX`.

**Comment by Pauli-CoE** [comment]
I have tested it with openssl 3.0.13 without patches. FreeBSD-14.0-p5 with KTLS enabled works fine with it.
The issue appears to have been fixed.

**Comment by gstrauss** [comment]
@Pauli-CoE built openssl 3.0.12 from openssl source and that worked, too, so @Pauli-CoE suggested looking at the patches in the FreeBSD openssl package.

@Sp1l there may be an issue with the KTLS patch https://cgit.freebsd.org/ports/tree/security/openssl/files/extra-patch-ktls

**Comment by gstrauss** [comment]
@Sp1l there may be an issue with the KTLS patch https://cgit.freebsd.org/ports/tree/security/openssl/files/extra-patch-ktls where downloads might get corrupted and `SSL_shutdown()` might incorrectly return EAGAIN on FreeBSD using KTLS.
