### ISSUE TITLE
Un-prefixed #define constants causing compilation issues in unrelated downstream headers

### ISSUE THREAD

**Issue by mark-99** [openssl/openssl#23853]
\providers\implementations\ciphers\cipher_aes_gcm_siv.h

```
#define BLOCK_SIZE 16
#define NONCE_SIZE 12
#define TAG_SIZE   16

/* AAD manipulation macros */
#define UP16(x) (((x) + 15) & ~0x0F)
#define DOWN16(x) ((x) & ~0x0F)
#define REMAINDER16(x) ((x) & 0x0F)
#define IS16(x) (((x) & 0x0F) == 0)
```

It's been standard practise for decades that preprocessor defines in headers should either be prefixed in lieu of a namespace, or #undef'd at the end of the header.

In particular `BLOCK_SIZE` is a template parameter in another library we're using, which then fails to compile when it's textually substituted by `16`.

**Comment by nhorman** [comment]
How are any downstream headers picking up these defines?  The header being referenced is part of the aes_gcm_siv implementation and shouldn't to the best of my reading be included in any compilation unit outside of that provider.  From my read, within openssl its only included in cipher_aes_gcm_siv.c cipher_aes_gcm_siv_hw.c and cipher_aes_gcm_siv_polyval.c, which implies that its not transitively included to any public api header

**Comment by t8m** [comment]
This header is purely internal and should never be included by applications using OpenSSL. This is clearly not a bug.

**Comment by mark-99** [comment]
I'll try and get more detail. It's the only `#define BLOCK_SIZE` that I can find anywhere in the source tree, and an `#undef BLOCK_SIZE` fixes the compilation error.

**Comment by nhorman** [comment]
I expect its actually coming from /usr/include/linux/fs.h:
```
#define BLOCK_SIZE_BITS 10
#define BLOCK_SIZE (1<<BLOCK_SIZE_BITS)
```
Which is copied into sys/mount.h (why I'm not sure)

but linux/fs.h in included in io_uring.h, which in turn is included by liburing.h

**Comment by mark-99** [comment]
Seems likely.

Apologies for the misattribution.
