### ISSUE TITLE
Linker warning with LTO enabled ('OPENSSL_ia32cap_P' declaration mismatch)

### ISSUE THREAD

**Issue by vszakats** [openssl/openssl#239]
Linking 1.0.2 statically to an app with mingw x86/32-bit (4.9.2) 
LTO option enabled, this warning is displayed at link phase: 

```
gcm128.c:697:0: warning: type of 'OPENSSL_ia32cap_P' does not match original declaration 
cryptlib.c:656:0: note: previously declared here 
```

Referenced declarations: 
[gcm128.c](https://github.com/openssl/openssl/blob/master/crypto/modes/gcm128.c#L685): `extern unsigned int OPENSSL_ia32cap_P[2];`
[cryptlib.c](https://github.com/openssl/openssl/blob/master/crypto/cryptlib.c#L129): `extern unsigned int OPENSSL_ia32cap_P[4];`

Also reported here: https://groups.google.com/d/msg/mailing.openssl.dev/xii2zuBCR7c/HZ7eX1fIvw0J

**Comment by vszakats** [comment]
This is a public array declared in two separate source files, but with _different sizes_. LTO linker detects this and shows a warning. Without LTO, the problem is still present but goes undetected at build time.

The solution would be to find out what the true array size is under the target platform (x86 32-bit - haven't tested other targets) and update the two declarations to match that.

**Comment by vszakats** [comment]
The configuration to reproduce:

1. Add these options to Configure's `mingw` line:
`-m32 -flto -ffat-lto-objects`

2.
```
perl Configure mingw no-shared no-ssl2 no-ssl3 no-dso no-sse2
```

**Comment by vszakats** [comment]
Similar issue on 64-bit:
```
e_aes_cbc_hmac_sha1.c:97:21: warning: type of 'OPENSSL_ia32cap_P' does not match original declaration
gcm128.c:697:0: warning: type of 'OPENSSL_ia32cap_P' does not match original declaration
cryptlib.c:656:0: note: previously declared here
```

**Comment by vszakats** [comment]
Any OpenSSL maintainers with questions or request for further information?

**Comment by richsalz** [comment]
looks like a bug we should fix.

**Comment by vszakats** [comment]
Thanks for jumping in. Let me know if there is anything I can add to this on the reporting/testing front.

**Comment by richsalz** [comment]
simplest for us (me) is if you have a diff.  then I can get someone else to review and it can go in quickly

**Comment by vszakats** [comment]
The true size of the memory area appears to be 4x32 bits, so I've extended the array size of 2 to 4 to fix this warning. PR: https://github.com/openssl/openssl/issues/299

**Comment by vszakats** [comment]
@richsalz I have submitted a PR, here are the two diffs in it:
https://github.com/vszakats/openssl/commit/412fad51b8794380038f08f92ca3b583d5d45f8c.diff
https://github.com/vszakats/openssl/commit/49bbecc776927032a39396437078026c83228e98.diff

Can you get someone to review them?

**Comment by richsalz** [comment]
Andy has a different fix in progress, changing the declaration to just use "[]"  It will be submitted soon.

**Comment by vszakats** [comment]
Great, thank you!

**Comment by vszakats** [comment]
Thanks for the patch. It fixes this issue, though two similar 
problems addressed in my PR are still open, please see my comment here:
https://github.com/openssl/openssl/commit/75c4827dfe6f52ccd687a283e6108a88ba3b8ec4

**Comment by vszakats** [comment]
Fixes committed:
https://github.com/openssl/openssl/commit/f0fa5c8306236ce742168d664d53b1551649a47b
https://github.com/openssl/openssl/commit/75c4827dfe6f52ccd687a283e6108a88ba3b8ec4
