### ISSUE TITLE
OSSL_sleep does not work for NonStop _PUT_MODEL_ above 1000ms

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#23923]
There is a limit on what `usleep()` supports on NonStop. The code needs to be modified to conform to how other platforms handle large sleep values.

**Comment by rsbeckerca** [comment]
I'm working on this fix.

**Comment by rsbeckerca** [comment]
I should point out that the justification for this PR is the widely documented limit on `usleep` for time values less than 1000000. The NonStop runtime appears to be sensitive to this situation.

**Comment by rsbeckerca** [comment]
This PR is based on `master` but can be (and should be) applied to any and all of the 3.x series releases.

**Comment by nhorman** [comment]
to be clear, this can be applied to all 3.x branches, but the issue encountered only presents on master and 3.3 (as the failing test was added shortly prior to the 3.3 branch.  As such 3.3 and master are required merge points, others are optional at the moment

**Comment by rsbeckerca** [comment]
> to be clear, this can be applied to all 3.x branches, but the issue encountered only presents on master and 3.3 (as the failing test was added shortly prior to the 3.3 branch.  As such 3.3 and master are required merge points, others are optional at the moment

That is what I have found. The bug does not present itself prior to 3.3 only because the test suite does not hit it but it is still there as a potential problem. 3.3 and master. Since 3.2 and before still supports SPT, I think I need to do a different fix. I will get that done shortly.
