### ISSUE TITLE
ocsp: unusual alarm syscall behavior on alpine, thread maxes cpu-core, tcp stuck in CLOSE_WAIT

### ISSUE THREAD

**Issue by hypersonic07** [openssl/openssl#23934]
**Affects:**
**OpenSSL 3.2.1** 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
of **alpine** linux (kernel: 6.6.22-1)

**Wrongful Behavior:**
If an invalid request is made (in this case using a port checker)
- the connection remains in `CLOSE_WAIT` status. 
- OpenSSL OCSP (affected thread) uses 100% CPU (one core).
- Nothing is displayed or recorded when using `-reqout` or `-req_text`
- `-timeout 5` has no effect, the problem persists indefinately
- setting the `/proc/sys/net/ipv4/tcp_keepalive_time` value to low (aka 5) has no effect
- No error is appearing on stdout or stderr
- NOT using `-ignore_err` has no effect either. It does not terminate on the malformed request

**Other observations**
- If `-multi` is used, exactly one thread is affected. You can use multiple malformed requests to affect multiple threads

**Reproduction**
Using [https://portchecker.co] or any similar tool on an OCSP port causes the problem immideately.

**Desired behavior**
Discard request after the timeout and resume normal operations on the thread.

**Comment by nhorman** [comment]
Could you by any chance run the application under a debugger and provide a stack trace while the application is in its hung state?

**Comment by hypersonic07** [comment]
Here you go. It keeps this stacktrace in its hung state as far as I can tell. Did three runs.
This is not exactly my speciality, so if you want me to use another debugger, (or flags/cmd) please ring.

Here is the output of EU-STACK

```
ocsp:/opt/ocsp# eu-stack -id -p 8973
PID 8973 - process
TID 8973:
#0  0x00007f04c0410844 __syscall3
#1  0x00007f04c0410844 setitimer
#2  0x00007f04c0424c2f alarm
#3  0x000055dbae11ee76 http_server_get_asn1_req
#4  0x000055dbae0ebbfa do_responder
#5  0x000055dbae0ebbfa ocsp_main
#6  0x000055dbae0ecfe7 do_cmd
#7  0x000055dbae0cd2c4 main
#8  0x00007f04c03df6d1 libc_start_main_stage2
#9  0x000055dbae0cd371 _start
eu-stack: dwfl_thread_getframes tid 8973 at 0x55dbae0cd370 in /usr/bin/openssl: no matching address range

```

And here is the output of gdb attached
`(gdb) bt
#0  0x00007f04c0410844 in __syscall3 (a3=140730159571744, a3@entry=140730159571664, a2=140730159571712, a2@entry=140730159571632, a1=0, n=38) at ./arch/x86_64/syscall_arch.h:29
#1  setitimer (which=which@entry=0, new=new@entry=0x7ffe4b2ba300, old=old@entry=0x7ffe4b2ba320) at src/signal/setitimer.c:25
#2  0x00007f04c0424c2f in alarm (seconds=seconds@entry=5) at src/unistd/alarm.c:8
#3  0x000055dbae11ee76 in http_server_get_asn1_req (it=0x7f04c0203940, preq=preq@entry=0x7ffe4b2bb5b0, ppath=ppath@entry=0x0, pcbio=pcbio@entry=0x7ffe4b2bb598, acbio=acbio@entry=0x7f04c02ea560, found_keep_alive=found_keep_alive@entry=0x0, prog=0x55dbae171280 <prog> "ocsp", accept_get=1, timeout=5)
    at apps/lib/http_server.c:312
#4  0x000055dbae0ebbfa in do_responder (timeout=5, acbio=0x7f04c02ea560, pcbio=0x7ffe4b2bb598, preq=0x7ffe4b2bb5b0) at apps/ocsp.c:1209
#5  ocsp_main (argc=<optimized out>, argv=<optimized out>) at apps/ocsp.c:666
#6  0x000055dbae0ecfe7 in do_cmd (prog=prog@entry=0x7f04c0307df0, argc=14, argv=0x7ffe4b2bb850) at apps/openssl.c:426
#7  0x000055dbae0cd2c4 in main (argc=14, argv=0x7ffe4b2bb850) at apps/openssl.c:307`

**Comment by nhorman** [comment]
thats wierd.  Thats suggesting that you're getting stuck in the alarm syscall, which should really never block.  It also doesn't seems to jive with the 100% cpu usage you are reporting.

I've treid to reproduce it here, but have been unable to:
1) Start oscp server (/apps/openssl ocsp -index ./index.txt -port 9999 -rsigner ./test/certs/rootCA.pem  -rkey ./test/certs/rootCA.key -CA ./test/certs/rootCA.pem -text -out log.txt)
2) Run a port scan on port 9999 with nmap (nmap -sT 127.0.0.1 -p 9999). 

The nmap run indicates port 9999 is open, but the oscp server doesn't hang.  

Can you provide a more detailed reproducer to try track your issue down?

**Comment by hypersonic07** [comment]
Then there might be something else in my setup causing this behavior. Given that, I will run more tests on it to try and figure it out and get back to you about the results. Will need to set up a controlled environment for testing, might take a few days.
