### ISSUE TITLE
How to downgrade openSSL 1.1.1

### ISSUE THREAD

**Issue by yqi19** [openssl/openssl#23930]
^. Thank you! I found on the official website that only 3.0+ OpenSSL is supported.

**Comment by yuqi0166** [comment]
Resolved this. 
Please see: https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by tom-cosgrove-arm** [comment]
Closing this as the OP has raised the same question as a discussion in #23931
