### ISSUE TITLE
Apply OSSL_sleep fix fo larger times for NonStop PUT model to 3.2, 3.1, 3.0

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#23961]
This defect is a request to merge #23926 into 3.2, 3.1, 3.0, as this is a defect that may cause problems in the PUT thread runtime if `OSSL_sleep(1000)` or greater is called. The defect has existed a long time but just came to light in 3.3.0-alpha1.

**Comment by nhorman** [comment]
openssl-3.2 cherry pick was clean.  3.1 and 3.0 require separate prs

**Comment by nhorman** [comment]
It occurs to me that, in the openssl 3.0 and 3.1 branches that we sill allowed SPT model builds, correct?  As such, this probably isn't the right fix there, is it?

**Comment by rsbeckerca** [comment]
> It occurs to me that, in the openssl 3.0 and 3.1 branches that we sill allowed SPT model builds, correct? As such, this probably isn't the right fix there, is it?

Actually, the fix will work with SPT or any NonStop supported threading model as long as `_REENTRANT` is defined.

**Comment by rsbeckerca** [comment]
> openssl-3.2 cherry pick was clean. 3.1 and 3.0 require separate prs

Working on 3.0 first. Stay tuned.

**Comment by rsbeckerca** [comment]
@nhorman The missing `sleep()` for other platforms exists in 3.0 and 3.1. Should I fix that?

**Comment by nhorman** [comment]
Thats kind of why I ask, the calls were private prior to 3.0 and largely unused until 3.2 (it was ossl_sleep prior, not OSSL_sleep).  We could fix it, but i'm wondering if its worthwhile (given that those builds could still use the SPT model, which would require further finagling to the patch.  it might be better to leave it alone until we hit an issue

**Comment by rsbeckerca** [comment]
> Thats kind of why I ask, the calls were private prior to 3.0 and largely unused until 3.2 (it was ossl_sleep prior, not OSSL_sleep). We could fix it, but i'm wondering if its worthwhile (given that those builds could still use the SPT model, which would require further finagling to the patch. it might be better to leave it alone until we hit an issue

It is a bug, nonetheless. Adding in correct code will not break openssl and I will run a full regression. Look in PR #23972. Testing will take about an hour or two.

**Comment by nhorman** [comment]
Given that the referenced PRs are merged, I believe this can be closed
