### ISSUE TITLE
Request latency with OpenSSL 3.0.11 vs. OpenSSL 1.1.1d

### ISSUE THREAD

**Issue by jc2479** [openssl/openssl#23975]
As reported in the [libcurl](https://github.com/curl/curl/issues/12873#issue-2120176536) project, since openssl 3 requests needs about 20-30ms more time. In this case I'm comparing Debian10 (OpenSSL 1.1.1d) with Debian12(OpenSSL 3.0.11)

See also the tcpdumps from [here](https://github.com/curl/curl/issues/12873#issuecomment-1929185122)

Is there a resolution expected?

**Comment by t8m** [comment]
Please try 3.2.1 or 3.3.0-alpha1. There should be some improvements already.

**Comment by jc2479** [comment]
@t8m thank you for your quick response.
3.2.1 seems to do the trick. 

Unfortunately, this version is currently only being offered on the "experimental" debian release/repo. But ok.
