### ISSUE TITLE
optimization capabilities missing in openssl fips provider

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#23979]
### Discussed in https://github.com/openssl/openssl/discussions/23978

<div type='discussions-op-text'>

<sup>Originally posted by **sanumesh** March 26, 2024</sup>
Hello

I am using openssl 3.0.10 version and have built the fips provider using the make enable_fips flags for aix-cc platform.

However the openssl speed command shows that it is not using the hardware capabilities of Power, and instead uses the software implementations of the algorithms. 
This is seen when fips provider is enabled in the openssl.cnf configuration file (with default disabled).

The issue is that the OPENSSL_cpuid_setup function which sets the power hardware capabilities (OPENSSL_ppccap_P variable) gets called only in the context of default provider.
Since fips provider is loaded as a shared object, it has its own copy of OPENSSL_ppccap_P which gets initialized to 0 as we do not call OPENSSL_cpuid_setup function in the context of FIPS provider. Since this value is 0, any algorithm implementation calls done with fips provider uses the software based implementation of the algorithms.

Can you advice how to fix this?

Thanks

</div>

**Comment by paulidale** [comment]
I'm guessing the easy fix is to call `OPENSSL_cpuid_setup` from `OSSL_provider_init_int`.
