### ISSUE TITLE
 Get incorrect package from SSL_read() with 3.0.10 ver.

### ISSUE THREAD

**Issue by sasakiakaya** [openssl/openssl#23981]
Hi,

I got incorrect package from SSL_read for DTLSv1.2, with OPENSSL 3.0.10.

I have called SSL_read 10 times. The return values of the 1, 2, 3, 5, 7, and 9 are > 0, and the return values of the 4, 6, 8, and 10 are less than zero. 
Among the results with return values greater than zero, the package message of the third package is incorrect.

I logged the buffer at the start of the dtls1_read_bytes() and after the line memcpy(buf, &(SSL3_RECORD_get_data(rr)[SSL3_RECORD_get_off(rr)]), n). Here I name the log at the start of the dtls1_read_bytes() as "log1", and name the log after memcpy as "log2". And I add a serial number to the log in the format of [id1][id2]."[id1]" indicates the [id1]th time the SSL_read function is called, and "[id2]" indicates the [id2]th time the SSL_read dtls1_read_bytes is called.
In log1, I found the incorrect message [3][11] is a part of [4][12], which is no return by SSL_read.

Here is my code for getting the log:

log1:
/-------------------------------------/

 start:
    s->rwstate = SSL_NOTHING;

    /*-
     * s->s3.rrec.type     - is the type of record
     * s->s3.rrec.data,    - data
     * s->s3.rrec.off,     - offset into 'data' for next read
     * s->s3.rrec.length,  - number of bytes.
     */
    rr = s->rlayer.rrec;
    dump_ssl_buf(&(SSL3_RECORD_get_data(s->rlayer.rrec)[SSL3_RECORD_get_off(s->rlayer.rrec)]), len,"/data/ssl_log/log1.txt",log_id);
    /*
     * We are not handshaking and have no data yet, so process data buffered
     * during the last handshake in advance, if any.
     */
	 
	 
/-------------------------------------/

log2:
/-------------------------------------/

        if (len > SSL3_RECORD_get_length(rr))
            n = SSL3_RECORD_get_length(rr);
        else
            n = len;

        memcpy(buf, &(SSL3_RECORD_get_data(rr)[SSL3_RECORD_get_off(rr)]), n);
        dump_ssl_buf(buf, n,"/data/ssl_log/log2.txt",log_id);

        if (peek)
        {
        
/-------------------------------------/
[log1.txt](https://github.com/openssl/openssl/files/14769163/log1.txt)
[log2.txt](https://github.com/openssl/openssl/files/14769164/log2.txt)

**Comment by sasakiakaya** [comment]
Additionally, I found the buffer address in log1 [3][11] is different from other, so I guess this bug is caused by the address offset.

**Comment by t8m** [comment]
> I got incorrect package from SSL_read for DTLS1.3, with OPENSSL 3.0.10.

DTLS-1.3 is not supported by OpenSSL yet. So this is confusing report.

Is your application multithreaded?

**Comment by sasakiakaya** [comment]
Sorry for confusing by mistake. I actually use DTLSv1.2.

Is your application multithreaded?
->Yes. but there is only one receive thread

**Comment by nhorman** [comment]
Theres not enough information here to make a solid determination as to whats going on.  Lets start at a high level and work our way down.  When you call SSL_read, and get a return value < 0, whats the output of SSL_get_error?

**Comment by t8m** [comment]
> ->Yes. but there is only one receive thread

What about the writer thread(s)? Is it separate from the receive thread or is it the same thread? If they are separate thread, can reads and writes happen simultaneously?

**Comment by sasakiakaya** [comment]
My high level stack is LwM2M -> CoAP -> DTLS. When LwM2M run bootstrip process, I found some packages were truncated from SSL_read(), Also, SSL_read has high failure frequency，with SSL_get_error = 2.
I've checked my TX/RX threads, SSL_read and SSL_write are protected by mutex_lock.

**Comment by nhorman** [comment]
When you get an SSL_read error, what is the output of ERR_print_errors?

**Comment by sasakiakaya** [comment]
After I modify the size for SSL_read, this issue seems fixed.

Before:

            numBytes = recvfrom(fd, buffer, 1024,MSG_PEEK, (struct sockaddr*)&addr_str, (int32_t*)&addrLen);
              SSL_read(ssl, buffer, numBytes );

After
            numBytes = recvfrom(fd, buffer, 1024,MSG_PEEK, (struct sockaddr*)&addr_str, (int32_t*)&addrLen);
              SSL_read(ssl, buffer, 1024);
