### ISSUE TITLE
SO_KEEPALIVE on an UDP-socket!

### ISSUE THREAD

**Issue by gvanem** [openssl/openssl#24005]
Trying to run `ossl-nghttp3-demo.exe www.google.com:443` on Windows,  I found to my surprise it used the 
option `SO_KEEPALIVE` for a UDP-socket. Basically, during start-up it did:
```c
crypto/bio/bio_sock2.c(49) (BIO_socket+46)
socket (AF_INET, SOCK_DGRAM, IPPROTO_UDP) --> 612.
...
crypto/bio/bio_sock2.c(95) (BIO_connect+177)
setsockopt (612, SOL_SOCKET, SO_KEEPALIVE, 1, 4) --> WSAENOPROTOOPT (10042).
```
(using my [Wsock-tracing](https://github.com/gvanem/wsock-trace) library).

Because of the above, these errors were printed:
```c
003B0000:error:8000273A:system library:BIO_connect:Unknown error:crypto/bio/bio_sock2.c:96:calling setsockopt()
003B0000:error:10000089:BIO routines:BIO_connect:unable to keepalive:crypto/bio/bio_sock2.c:98:
003B0000:error:8000273A:system library:conn_state:Unknown error:crypto/bio/bss_conn.c:211:calling connect(www.google.com, 443)
003B0000:error:10000067:BIO routines:conn_state:connect error:crypto/bio/bss_conn.c:264:
003B0000:error:0A000183:SSL routines:ossl_quic_port_raise_net_error:quic network error:ssl/quic/quic_port.c:596:port failed due to network BIO I/O error
003B0000:error:0A0000CF:SSL routines:quic_do_handshake:protocol is shutdown:ssl/quic/quic_impl.c:1690:
003B0000:error:400C0103:lib(128):OSSL_DEMO_H3_CONN_handle_events:internal error:demos/http3/ossl-nghttp3.c:650:writing HTTP/3 data to network failed
003B0000:error:400C0107:lib(128):main:operation fail:demos/http3/ossl-nghttp3-demo.c:137:cannot handle events
```

[MSDN](https://learn.microsoft.com/en-us/windows/win32/winsock/so-keepalive#return-value) explains:

>[WSAENOPROTOOPT](https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2)
The option is unknown or unsupported by the indicated protocol family. This error is returned if the socket descriptor passed in 
> the s parameter was for a datagram socket.

So `SO_KEEPALIVE` is only supported for connection-oriented sockets (`SOCK_STREAM`, `SOCK_RDM` etc.). No idea what Linux supports. 

When running `quic-client-block.exe  www.google.com 443`, I do not see any use of `SO_KEEPALIVE`.
So how/why is it used in `demos/nghttp3/*.c`?

**Comment by gvanem** [comment]
I dug a bit deeper into this bio-stuff and with this patch:
```diff
--- a/crypto/bio/bio_sock2.c 2022-11-07 10:33:03
+++ b/crypto/bio/bio_sock2.c 2024-03-30 09:43:04
@@ -90,6 +90,11 @@
     if (!BIO_socket_nbio(sock, (options & BIO_SOCK_NONBLOCK) != 0))
         return 0;

+#if defined(OPENSSL_SYS_WIN32)
+    if (BIO_ADDRINFO_protocol(addr) != SOCK_STREAM)
+       options &= ~BIO_SOCK_KEEPALIVE;
+#endif
+
     if (options & BIO_SOCK_KEEPALIVE) {
         if (setsockopt(sock, SOL_SOCKET, SO_KEEPALIVE,
                        (const void *)&on, sizeof(on)) != 0) {
@@ -307,6 +312,11 @@
     if (!BIO_socket_nbio(sock, (options & BIO_SOCK_NONBLOCK) != 0))
         return 0;

+#if defined(OPENSSL_SYS_WIN32)
+    if (BIO_ADDRINFO_protocol(addr) != SOCK_STREAM)
+       options &= ~BIO_SOCK_KEEPALIVE;
+#endif
+
     if (options & BIO_SOCK_KEEPALIVE) {
         if (setsockopt(sock, SOL_SOCKET, SO_KEEPALIVE,
                        (const void *)&on, sizeof(on)) != 0) {

```

I got a lot of data from `demos\http3\ossl-nghttp3-demo.exe www.google.com:443`: [ossl-nghttp3-demo.txt](https://github.com/openssl/openssl/files/14811293/ossl-nghttp3-demo.txt)
And the trace: [ossl-nghttp3-demo-trace.txt](https://github.com/openssl/openssl/files/14811296/ossl-nghttp3-demo-trace.txt)


I've no idea if it's a correct patch.

**Comment by nhorman** [comment]
I think the more correct patch here is to detect UDP sockets and either just not set SO_KEEPALIVE on them or return an error in the event keepalive is requested for udp sockets.  It appears that linux just ignores the request and returns 0 in the event we try this here.

**Comment by gvanem** [comment]
> It appears that linux just ignores the request 

Really? Amazing.

**Comment by nhorman** [comment]
That's how it looks to me.  I'm starting at sock_setsockopt in the kernel code right now, and it doesn't change the rc value from zero, even if the sk_prots keepalive method is unset

**Comment by hlandau** [comment]
@gvanem I've raised a fix in https://github.com/openssl/openssl/pull/24015. Could you test it?

**Comment by gvanem** [comment]
@hlandau The patch works fine. 
Although the demo gets stuck for 30 sec for servers w/o HTTP/3 before giving up. Maybe not surprising? Like:
```
timer & demos\http3\ossl-nghttp3-demo.exe www.vg.no:443 > NUL & timer
Timer 1 on: 11:34:32
78250000:error:0A0000CF:SSL routines:quic_do_handshake:protocol is shutdown:ssl/quic/quic_impl.c:1717:
78250000:error:400C0103:lib(128):OSSL_DEMO_H3_CONN_handle_events:internal error:demos/http3/ossl-nghttp3.c:650:writing HTTP/3 data to network failed
78250000:error:400C0107:lib(128):main:operation fail:demos/http3/ossl-nghttp3-demo.c:137:cannot handle events
Timer 1 off: 11:35:02  Elapsed: 0:00:30,725
```
And testing `docs.trafficserver.apache.org:443` sometimes takes 2 sec. Other times 37 sec!

**Comment by hlandau** [comment]
> @hlandau The patch works fine. Although the demo gets stuck for 30 sec for servers w/o HTTP/3 before giving up. Maybe not surprising? Like:
> 
> ```
> timer & demos\http3\ossl-nghttp3-demo.exe www.vg.no:443 > NUL & timer
> Timer 1 on: 11:34:32
> 78250000:error:0A0000CF:SSL routines:quic_do_handshake:protocol is shutdown:ssl/quic/quic_impl.c:1717:
> 78250000:error:400C0103:lib(128):OSSL_DEMO_H3_CONN_handle_events:internal error:demos/http3/ossl-nghttp3.c:650:writing HTTP/3 data to network failed
> 78250000:error:400C0107:lib(128):main:operation fail:demos/http3/ossl-nghttp3-demo.c:137:cannot handle events
> Timer 1 off: 11:35:02  Elapsed: 0:00:30,725
> ```
> 
> And testing `docs.trafficserver.apache.org:443` sometimes takes 2 sec. Other times 37 sec!

Thanks. Can you open a separate issue for this?
