### ISSUE TITLE
3.3.0-alpha1: CPU loop in threadstest (torture_rw_low) on old Linux RHEL6 and SLES11

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#24000]
Hi there,
I observe a reproducible CPU loop during threadstest on old Linux platforms RHEL6 and SLES11.
The test method is torture_rw_low. The two writer threads have finished, the two reader threads are looping. Due to the debugger, variable contents are:

rwwriter_ptr (int *) 0xad72f0
*rwwriter_ptr 7
rw_torture_result 1
rwwriter2_iterations 3
rwwriter1_iterations 3
rwreader2_iterations 882251533
rwreader1_iterations 914844064
rwwriter1_done 0
rwwriter2_done 0
contention 0

So it seems somehow the post-writer increment of the done variables has not been applied or is not visible.

I added some debug logging around

CRYPTO_atomic_add(&rwwriter1_done, 1, &local, NULL);

and indeed the add does not happen. The rwwriter1_done variable stays at 0.

The man page of CRYPTO_atomic_add states:

"If atomic operations are not supported and lock is NULL, then the function will fail."

Looking at the impl for CRYPTO_atomic_add it only works on Linux if __ATOMIC_ACQ_REL exists. gcc docs state, that it was introduced with gcc 4.7.

So these platforms / compiler versions do not support that style of atomics:

SLES11:
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux) 
Linux 2.6.32.12-0.7-default #1 SMP 2010-05-20 11:14:20 +0200 x86_64 x86_64 x86_64 GNU/Linux

RHEL6:
gcc version 4.4.5 20110214 (Red Hat 4.4.5-6) (GCC) 
Linux 2.6.32-131.0.15.el6.x86_64 #1 SMP Tue May 10 15:42:40 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux

Maybe the test should be disabled then? 

I can try patches and I have some strace output but it does not seem to be helpful.

Best regards,

Rainer

**Comment by nhorman** [comment]
No, i can fix this, but for reference the minimum supported gcc version for x860_64 is currently gcc 9

**Comment by nhorman** [comment]
Definition of Done
Currently, the lack of a lock in the calls to CRYPTO_atomic_add in the rcu and rw torture test cause that call to fail when an older gcc is used in compilation that does not define __ATOMIC_ACQ_REL

- [ ] Need to modify the rw torture test to allocate an RWlock for use with the atomic reads/adds in that test so that the exit variables are updated accordingly
- [ ] Need to modify the rcu torture test to allocate an RWlock for use with the atomic reads/adds in that test so the exit variables are updated accordingly

**Comment by nhorman** [comment]
please test with the attached PR

**Comment by rainerjung** [comment]
I tried the part of the PR which applies to test/threadstest.c and it fixes the observed problem for RHEL6 and SLES11 with old gcc.

I will compile and test beta1 plus this patch on a few platforms (also more modern ones and Solaris 10) and report back again.

**Comment by rainerjung** [comment]
Looks good to me. I applied the PR on top of 3.3.0-beta1 and it compiles and tests fine for RHEL 6, 7, 8 and 9 and SLES 11, 12 and 15 plus Solaris 10. Thanks!

**Comment by rsbeckerca** [comment]
This is not specific to Linux. NonStop is seeing this loop also.

**Comment by rainerjung** [comment]
Backport to 3.3.x is still missing.

**Comment by t8m** [comment]
> Backport to 3.3.x is still missing.

Thank you for the heads up. I've cherry picked the fix to the 3.3 branch.
