### ISSUE TITLE
Missing function in 3.x: EVP_PKEY -> EC_GROUP

### ISSUE THREAD

**Issue by SmallLars** [openssl/openssl#24018]
When I generate a key with
```
openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve:brainpoolP256r1 -outform der | xxd -ps
```
I am able to import it with `d2i_PrivateKey`. The result is an `EVP_PKEY`.
Using **deprecated** functions it is easy to get the **EC_GROUP**.

- `EVP_PKEY_get1_EC_KEY` -> `EC_KEY`
- `EC_KEY_get0_group` -> `EC_GROUP`

I would like to avoid to use deprecated functions but I am not able to find a function to get the `EC_GROUP` from an `EVP_PKEY`.

The [migration_guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html) points to [EVP_PKEY-EC](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-EC.html). But there is only an entry to get a string if it is a named curve. While I use the named curve `brainpoolP256r1` in my example, I need to consider also unnamed curves so I can not use `OSSL_PKEY_PARAM_GROUP_NAME`. Is it possible to add the missing function or give me a hint how it is possible?

**Comment by t8m** [comment]
EC_GROUP functions are deprecated altogether so there is no way to have EVP_PKEY conversion to EC_GROUP being done via non-deprecated functions.

What particular things do you need to do with the EC_GROUP?

In general arbitrary unnamed curves are not something that we to expand support for.

**Comment by SmallLars** [comment]
We have a protocol where keys provided by the user are used. In a handshake the public keys are given to the communication partner. The partner calculates its own public key to start a ECDH keyexchange. At this step we only receive the raw public point and an ID of the key he choosed. So what we need to do is:
1. Load our private key with the ID.
2. Get the privat part with EVP_PKEY_get_bn_param ... "priv" ....
3. Get the curve from our key.
4. Use EC_POINT_new and EC_POINT_oct2point to interpret the raw public point.
5. Use EC_POINT_mul with our private key.
For step 4 and 5 we need the curve (even for named curves).

Btw, this is also interesting for #23996 to get curve attributes again.

**Comment by t8m** [comment]
This is an absolutely normal ECDH operation. You can do all this without using the deprecated APIs or EC_POINT. 

Copying some relevant code snippets from libssl which does the same:

```
    ckey = EVP_PKEY_new();
    if (ckey == NULL || EVP_PKEY_copy_parameters(ckey, skey) == 0) {
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_R_COPY_PARAMETERS_FAILED);
        goto err;
    }

    if (!EVP_PKEY_set1_encoded_public_key(ckey, data, i)) {
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, ERR_R_INTERNAL_ERROR);
        goto err;
    }
```
This creates EVP_PKEY ckey (pubkey) by copying the parameters (curve) from skey (privkey).

And this can be used in ECDH derive operation as follows:

```
    pctx = EVP_PKEY_CTX_new_from_pkey(sctx->libctx, privkey, sctx->propq);

    if (EVP_PKEY_derive_init(pctx) <= 0
        || EVP_PKEY_derive_set_peer(pctx, pubkey) <= 0
        || EVP_PKEY_derive(pctx, NULL, &pmslen) <= 0) {
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, ERR_R_INTERNAL_ERROR);
        goto err;
    }

    pms = OPENSSL_malloc(pmslen);
    if (pms == NULL) {
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, ERR_R_CRYPTO_LIB);
        goto err;
    }

    if (EVP_PKEY_derive(pctx, pms, &pmslen) <= 0) {
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, ERR_R_INTERNAL_ERROR);
        goto err;
    }

```

**Comment by t8m** [comment]
> Btw, this is also interesting for #23996 to get curve attributes again.

You can get the individual EC curve params by using EVP_PKEY_get_BN_param() or EVP_PKEY_todata(). Please see https://www.openssl.org/docs/manmaster/man7/EVP_KEYMGMT-EC.html

**Comment by t8m** [comment]
@nhorman IMO there is nothing to implement here. Documentation improvements including examples would be of course beneficial.

**Comment by SmallLars** [comment]
Thank you very much. That helped a lot. It is a little bit more code as before but works as expected.
```
QByteArray SimulatorCard::ecMultiplication(const QByteArray& pPoint) const
{
	if (mCardKey.isNull())
	{
		qCCritical(card) << "Missing private key";
		return QByteArray();
	}

#if OPENSSL_VERSION_NUMBER >= 0x30000000L
	const auto& terminalKey = EcUtil::create(EVP_PKEY_new());
	if (terminalKey.isNull() || EVP_PKEY_copy_parameters(terminalKey.data(), mCardKey.data()) == 0)
	{
		qCCritical(card) << "Initialization of the terminal key failed";
		return QByteArray();
	}
	if (!EVP_PKEY_set1_encoded_public_key(
			terminalKey.data(),
			reinterpret_cast<const unsigned char*>(pPoint.data()),
			static_cast<size_t>(pPoint.length())))
	{
		qCCritical(card) << "Interpreting the terminal key failed";
		return QByteArray();
	}

	const auto& ctx = EcUtil::create(EVP_PKEY_CTX_new_from_pkey(nullptr, mCardKey.data(), nullptr));
	size_t resultLen = 0;
	if (EVP_PKEY_derive_init(ctx.data()) <= 0
			|| EVP_PKEY_derive_set_peer(ctx.data(), terminalKey.data()) <= 0
			|| EVP_PKEY_derive(ctx.data(), nullptr, &resultLen) <= 0)
	{
		qCCritical(card) << "Initialization or calculation of the result failed";
		return QByteArray();
	}

	QByteArray result(static_cast<qsizetype>(resultLen), '\0');
	if (EVP_PKEY_derive(ctx.data(), reinterpret_cast<uchar*>(result.data()), &resultLen) <= 0)
	{
		qCCritical(card) << "Calculation of the result failed";
		return QByteArray();
	}

	return result;

#else
	const auto& curve = EcUtil::create(EC_GROUP_dup(EC_KEY_get0_group(mCardKey.data())));
	auto point = EcUtil::oct2point(curve, pPoint);
	if (!point)
	{
		qCCritical(card) << "Interpreting the point failed";
		return QByteArray();
	}

	QSharedPointer<EC_POINT> result = EcUtil::create(EC_POINT_new(curve.data()));
	const auto& privateKey = EcUtil::create(BN_dup(EC_KEY_get0_private_key(mCardKey.data())));
	if (!EC_POINT_mul(curve.data(), result.data(), nullptr, point.data(), privateKey.data(), nullptr))
	{
		qCCritical(card) << "Calculation of the result failed";
		return QByteArray();
	}

	return EcUtil::point2oct(curve, result.data(), true);

#endif
}
```

**Comment by nhorman** [comment]
Given that the modified code worked for @SmallLars , I'm marking this as closed.  Please comment f there is more work to be done here
