### ISSUE TITLE
Cannot lazy load providers specified in configuration file correctly

### ISSUE THREAD

**Issue by afshinpir** [openssl/openssl#24020]
Hi All

I have raised this discussion as a bug:
https://github.com/openssl/openssl/discussions/23731
because it seems that expectation does not match behavior correctly. Here is the problem.
I'm trying to define an entry inside `openssl.cnf` and lazy load it later. So I wrote a config file like this:
```
...
[openssl_init]
providers = provider_sect

# List of providers to load
[provider_sect]
# default = default_sect
# The fips section name should match the section name inside the
# included fipsmodule.cnf.
base = base_sect
fips = fips_sect
myprovider= myprovider_sect

[myprovider_sect]
module = /data/myprovider.so
additional_info = test
...
```
As you see I have added entry without `activate=1` to my config file. I'm also only using fips and base provider and disabled default provider. Now, I was expecting that if I try to load config file and then use `OSSL_PROVIDER_load()`, I should be able to load my provider. So I wrote a code like this:
```
int func(OSSL_PROVIDER *provider, void *cbdata) {
        std::cout << "provider: " << OSSL_PROVIDER_get0_name(provider) << "\n";
        return 1;
}

int main(int argc, char** argv) {
    if (OSSL_LIB_CTX_load_config(NULL, "openssl.cnf") <= 0) {
        std::cout<< "FATAL: error loading configuration file\n";
        ERR_print_errors_fp(stderr);
        exit(1);
    }

    int ret = -1;
    OSSL_PROVIDER *ctx;
    ctx= OSSL_PROVIDER_load(NULL, "myprovider");
    if (ctx== NULL) {
        std::cout << "Failed to load Default provider\n";
        ERR_print_errors_fp(stderr);
        return -1;
    }
    std::cout << "load done\n";
    OSSL_PROVIDER_do_all(NULL, func, NULL);
    OSSL_PROVIDER_unload(ctx);
}
```
But this code does not work as expected. I traced openssl codes to some extend and I noticed that an entry for non-activated provider is added to internal structures, but it seems it is not searched and activated by calling `OSSL_PROVIDER_load()`. 
One major problem is the fact that module path will not be set if we try to load module in this way. `template.path` should have module path here and it is need to be set after this line:
https://github.com/openssl/openssl/blob/5677992679b38950c6a0c3775fd57378e1879ba5/crypto/provider_core.c#L575
similar to what happens here:
https://github.com/openssl/openssl/blob/5677992679b38950c6a0c3775fd57378e1879ba5/crypto/provider_conf.c#L237-L238
but module path is not set. I try to add this myself and test things out, but module still does not load correctly.
I have yet to test if I'm missing something or not, but I always to load provider like this.
I'm using version 3.0.13 right now, but this code is similar in all version. And as you see in my config file, I'm using FIPS module and have disabled default provider.

**Comment by nhorman** [comment]
FWIW, The activate setting has changed somewhat between 3.0 and the head of the tree (and in 3.3).  In 3.0 the activate setting was an implied boolean whos presence meant activate if it was present (i.e. you could set activate=no and that would still activate the provider).  In 3.3 it was updated such that activate was a positively asserted boolean (i.e. activate=[1|yes|true] means activate, 0|no|false means don't activate.  Omitting the parameter is an error.  you might need to check that.

But I don't think thats whats going on here.  I think whats happening is that we're expressly forgetting to set the path when creating a provider.  When we call provider_conf_load, if its not going to be activated, we create a template in which we do wet the path in the OSSL_PROVIDER_INFO struct, but unlike the activate path we don't call ossl_provider_set_module_path (which makes sense, as we don't have an OSSL_PROVIDER struct yet).  However, in the provider_new call which we make during a manual call to OSSL_PROVIDER_load, we get the template, but we never set the allocated provider path with a call to ossl_provider_set_module_path.  I think we probably need to.  Can you augment thee ossl_provider_new code to add a call to that function prior to the call to provider_new call there passing the value of template.path as the argument?

**Comment by nhorman** [comment]
Can you attempt to run your reproducer with the referenced PR and see if the problem is fixed please?

**Comment by afshinpir** [comment]
@nhorman 
Hi

I have tested this PR and it works well. It loads provider as expected.
Will this PR be merged into 3.0 branch as well?

**Comment by nhorman** [comment]
Thank you, I've marked it for inclusion in all the 3.x branches.  It will take.a.bit though as we're about to freeze for the final 3.3 release

**Comment by t8m** [comment]
> Omitting the parameter is an error. you might need to check that.

@nhorman I would strongly disagree with that. Omitting the parameter completely must be supported for backwards compatibility and the default value must be not to activate.

**Comment by nhorman** [comment]
Yeah, you're right, omitting the parameter still defaults to don't activate, which is correct.  It's adding the parameter key without a value that generates.ab error

**Comment by t8m** [comment]
Still present on 3.0 and 3.1

**Comment by nhorman** [comment]
backport to 3.0:
https://github.com/openssl/openssl/pull/24197
