### ISSUE TITLE
OpenSSL Wiki Error - Binaries.

### ISSUE THREAD

**Issue by lelik107** [openssl/openssl#24053]
Hello! Curl is mentioned here https://wiki.openssl.org/index.php/Binaries as one of the sources for the binaries - OpenSSL for Windows.
It's wrong for the long time already. Because Curl switched to LibreSSL by default and don't provide OpenSSL binaries anymore.
You can see it here: https://github.com/curl/curl-for-win#features 

> Uses [LibreSSL](https://www.libressl.org/) TLS backend.

and check it out here https://curl.se/windows/  for libressl or maybe you can see OpenSSL?
So, please, delete this source to not misinform the users.

**Comment by t8m** [comment]
I've removed the invalid entry. Thank you for the report.
