### ISSUE TITLE
riscv: chacha_internal_test failed with Zvkb Implementation

### ISSUE THREAD

**Issue by cyyself** [openssl/openssl#24070]
commit: 4a3e8f08306c64366318e26162ae0a0eb7b1a006

How to reproduce:

using qemu (v8.2 I tested on):

```bash
qemu-system-riscv64 -M virt -cpu rv64,sscofpmf=true,v=true,vlen=256,zvkb=true
```

Then add some args boot a mainline Linux kernel (v6.9-rc3 I tested on) and any rootfs as you like.

Then cd to openssl and test:

```console
cd openssl
export OPENSSL_riscvcap=rv64gc_v_zba_zbb_zbc_zbs_zvkb
make test -j `nproc`
```

We will get errors like:

```console
# ------------------------------------------------------------------------------
        # ERROR: (unsigned char) 'buf[j] == ref[j]' failed @ test/chacha_internal_test.c:175
        # [0] compared to [228]
        # INFO:  @ test/chacha_internal_test.c:176
        # 1023 failed at 960 (00)
        #
        # OPENSSL_TEST_RAND_SEED=1712650600
        not ok 1023 - iteration 1023
# ------------------------------------------------------------------------------
    # OPENSSL_TEST_RAND_SEED=1712650600
    not ok 1 - test_cha_cha_internal
# ------------------------------------------------------------------------------
../../util/wrap.pl ../../test/chacha_internal_test => 1
not ok 1 - running chacha_internal_test
03-test_internal_chacha.t ............... 1/? ----------------------------------
#   Failed test 'running chacha_internal_test'
#   at /home/cyy/openssl/util/perl/OpenSSL/Test/Simple.pm line 77.
03-test_internal_chacha.t ............... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

However, if we don't set `OPENSSL_riscvcap` in env and openssl uses chacha implementation in C, it will pass.

**Comment by cyyself** [comment]
#21923 @JerryShih @phoebesv @nibrunieAtSi5 @bjoto

**Comment by JerryShih** [comment]
Ohh...
That chacha20 test in `test/chacha_internal_test.c` call `ChaCha20_ctr32()` function directly without the evp and the interfaces in [link](https://github.com/openssl/openssl/blob/8bc5b0a570c8a2c9886a3cae9dea2016d510578d/providers/implementations/ciphers/cipher_chacha20_hw.c).
The input length is not a multiple of chacha block size. That's a bug.
But should we handle that corner case since we will use the wrapper.
The wrapper will split and handle the tail elements. Do we need to handle that again in the implementation?

**Comment by JerryShih** [comment]
cc @levitte (the original test case author).

**Comment by t8m** [comment]
@JerryShih the ChaCha20_ctr32() must be able to work on non-multiple of block length. Of course only the last block will be unfinished. It is not as generic interface as the EVP one is.

**Comment by JerryShih** [comment]
Thanks.
I will fix the non-multiple of block issue.
