### ISSUE TITLE
Builds broken in 3.3.0 in conf-lib.c

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#24075]
The following compile errors occur because `conf-lib.c` incorrectly defines `_XOPEN_SOURCE_EXTENDED`. This define must be set to 1 if specified. Platforms that already specify this `#define` break and cannot compile.
```
 #define _XOPEN_SOURCE_EXTENDED   /* To get a definition of strdup() */
          ^
"/home/jenkinsbuild/.jenkins/workspace/OpenSSL-3.3_Pipeline/crypto/conf/conf_lib.c", line 10: warning(140):
          macro redefined differently

  #if _XOPEN_SOURCE_EXTENDED == 1
                             ^
```

This is a critical breakage and stops OpenSSL from compiling.

**Comment by rsbeckerca** [comment]
The code should have an `#ifdef/undef` guard around it.

This was not present at `beta1`

**Comment by nhorman** [comment]
@levitte could you look at this please?

**Comment by t8m** [comment]
Hmm, I think the proper fix would be to move the define to the VMS configuration the same way the NonStop and BASE-unix configs have it.

**Comment by rsbeckerca** [comment]
> Hmm, I think the proper fix would be to move the define to the VMS configuration the same way the NonStop and BASE-unix configs have it.

Is there anything I can do for this one? I don't have a VMS system available for testing if I change that config.

**Comment by rsbeckerca** [comment]
This also occurs in `crypto/conf/conf_sap.c` and `apps/ocsp.c`,

**Comment by t8m** [comment]
Yeah, @levitte should fixup his VMS fix.

**Comment by t8m** [comment]
To avoid such regressions in future it would help if @rsbeckerca you could try to build the git tree from the branch before the release.

**Comment by t8m** [comment]
Unfortunately it is inevitable that such regressions occasionally happen for platforms that we do not have in CI.

**Comment by rsbeckerca** [comment]
> To avoid such regressions in future it would help if @rsbeckerca you could try to build the git tree from the branch before the release.

@t8m I run build/test cycles at least once a week. This one slipped past because I did not get time to test it. Last announce was beta1. I'm happy to keep trying and have a monitor running on this. Not sure why we did not see the failure earlier.

**Comment by rsbeckerca** [comment]
Also, I do build from the git tree. Still not sure why I missed this. We had no failures until 3.3.0 came out.

**Comment by nhorman** [comment]
I wonder if it would be beneficial, when we freeze the tree for a release (alpha/beta/final) that, in addition to emailing the comitters list, we also cc the community platform maintainers, indicating that during these freeze periods that target release branches should undergo additional community ci (daily build/test, etc) to help ensure changes admitted during freeze dont have adverse effects on those community platforms.  

@t8m do we maintain a canonical list of community maintainers which we can use for that?

**Comment by rsbeckerca** [comment]
> I wonder if it would be beneficial, when we freeze the tree for a release (alpha/beta/final) that, in addition to emailing the comitters list, we also cc the community platform maintainers, indicating that during these freeze periods that target release branches should undergo additional community ci (daily build/test, etc) to help ensure changes admitted during freeze dont have adverse effects on those community platforms.
> 
> @t8m do we maintain a canonical list of community maintainers which we can use for that?

I really like this idea. We could turn around test results in a few hours on x86. If something goes sideways on ia64 we would likely just not release on that variant.

**Comment by tom-cosgrove-arm** [comment]
> @t8m do we maintain a canonical list of community maintainers which we can use for that?

Yes, there is the list at https://www.openssl.org/policies/general-supplemental/platforms.html

**Comment by levitte** [comment]
Fix in #24083 (made against the openssl-3.3 branch), please try it out

**Comment by levitte** [comment]
> Also, I do build from the git tree. Still not sure why I missed this. We had no failures until 3.3.0 came out.

The offending PR was merged in last thursday.

**Comment by tkoecker** [comment]
> Fix in #24083 (made against the openssl-3.3 branch), please try it out

I've tried the fix, and it now builds on both systems where I encountered the issues (AIX and Solaris)

**Comment by rsbeckerca** [comment]
> > I wonder if it would be beneficial, when we freeze the tree for a release (alpha/beta/final) that, in addition to emailing the comitters list, we also cc the community platform maintainers, indicating that during these freeze periods that target release branches should undergo additional community ci (daily build/test, etc) to help ensure changes admitted during freeze dont have adverse effects on those community platforms.
> > @t8m do we maintain a canonical list of community maintainers which we can use for that?
> 
> I really like this idea. We could turn around test results in a few hours on x86. If something goes sideways on ia64 we would likely just not release on that variant.

Just a quick followup. We have a CI monitor job now that will check every merge to 3.3 and run 64-bit and PUT build/test cycles. Hopefully, we will catch issues earlier. Another will be made for master.

**Comment by t8m** [comment]
There can be a lot of merges from time to time. IMO doing a CI run once or twice day would be sufficient.

**Comment by rsbeckerca** [comment]
> There can be a lot of merges from time to time. IMO doing a CI run once or twice day would be sufficient.

@t8m The poll is scheduled between 2am and 3am daily. That should work.
