### ISSUE TITLE
openssl-3.3.0 ossl_rcu_lock_new() memory leak

### ISSUE THREAD

**Issue by kmiya-culti** [openssl/openssl#24085]
Duplicate ...

156    new->write_lock = ossl_crypto_mutex_new();
...
161    new->write_lock = ossl_crypto_mutex_new();

https://github.com/openssl/openssl/blob/60f69680b280bc847819afa8421cdeddb98db87f/crypto/threads_win.c#L156

**Comment by t8m** [comment]
Thanks for the report. Fortunately RCU is still almost unused so this leak is not a big problem.

**Comment by nhorman** [comment]
thats odd though, its almost unused, but its not _not_ used (at minimum we have a test that uses it).  I wonder why the asan CI runs didn't catch this

**Comment by t8m** [comment]
> thats odd though, its almost unused, but its not _not_ used (at minimum we have a test that uses it). I wonder why the asan CI runs didn't catch this

I do not think we have a Windows leak check CI build.
