### ISSUE TITLE
Application hangs on exit [VMS, and possibly others]

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#24096]
*Note: this only affects master and the 3.3 branch*

This is reproducable in the build directory tree like this:

``` console
$! This corresponds to './test/sanitytest.exe` on Unix
$!
$ run [.test]sanitytest.exe
1..8
ok 1 - test_sanity_null_zero
ok 2 - test_sanity_enum_size
ok 3 - test_sanity_twos_complement
ok 4 - test_sanity_sign
ok 5 - test_sanity_unsigned_conversion
ok 6 - test_sanity_range
ok 7 - test_sanity_memcmp
ok 8 - test_sanity_sleep
*INTERRUPT*

```

``` console
$! This corresponds to './util/wrap.pl ./apps/openssl version` on Unix
$!
$ perl [.util]wrap.pl [.apps]openssl.exe version
OpenSSL 3.3.1-dev  (Library: OpenSSL 3.3.1-dev )
*CANDEL*

```

(In both cases, `*INTERRUPT*` and `*CANCEL*` are printed as a system response to pressing Ctrl-C)

## Debugging

I did some debugging, and found that the hang happens during automated cleanup, in [`ossl_synchronize_rcu`](https://github.com/openssl/openssl/blob/5a13d35f243be66f6ad914aefe99fb708812dff1/crypto/threads_pthread.c#L521-L562), with the [`pthread_cond_wait()`](https://github.com/openssl/openssl/blob/5a13d35f243be66f6ad914aefe99fb708812dff1/crypto/threads_pthread.c#L548) call, in the following call stack:

``` console
DBG> show calls
 module name    routine name     line           rel PC           abs PC
*threads_pthread 
                ossl_synchronize_rcu 
                                30013       0000000000001870 000000000006D7F0
*conf_mod       CONF_modules_unload 
                                51510       0000000000002AA0 0000000000186570
*conf_mod       ossl_config_modules_free 
                                51586       0000000000003140 0000000000186C10
*init           OPENSSL_cleanup 
                                54547       0000000000000FB0 00000000000C48C0
 SHARE$DECC$SHR_CODE0                       0000000000000EC0 FFFFFFFF84514EC0
                                            FFFFFFFF801AFF30 FFFFFFFF801AFF30
                                            FFFFFFFF80A3D490 FFFFFFFF80A3D490
                                            FFFFFFFF80A3A800 FFFFFFFF80A3A800
 SHARE$DECC$SHR_CODE0                       00000000003A3860 FFFFFFFF848B7860
 SHARE$DECC$SHR_CODE0                       00000000003A38B0 FFFFFFFF848B78B0
*main           __main          48401       0000000000000130 00000000000314C0
 SHARE$PTHREAD$RTL_CODE2                    000000000004AE80 FFFFFFFF844D2E80
 SHARE$PTHREAD$RTL_CODE2                    00000000000006C0 FFFFFFFF844886C0
                                            FFFFFFFF80A3DF10 FFFFFFFF80A3DF10
```

(note: the line numbers are compiler generated and do not correspond to per file source code line numbers)

## Impact

This is likely to affect all VMS applications linking with OpenSSL 3.3.0.

I cannot say if this affects other platforms as well.  This is, after all, happening in a pthread call, and this may be caused by a pthread implementation hickup that isn't unique to VMS.

**Comment by levitte** [comment]
`test/sanitytest.c` is a single-thread program, isn't it?   So, it's safe to say that there shouldn't be any other thread the needs the attention of `ossl_synchronize_rcu`, i.e. there shouldn't a mismatch between `lock->next_to_retire` and `ID_VAL(count)` in that while loop, right?

**Comment by levitte** [comment]
Ah, something to be noted, though, is that there are two `ossl_synchronize_rcu` calls happening as part of `OSSL_cleanup`...  actually further in, through [`ossl_config_modules_free`](https://github.com/openssl/openssl/blob/7f04bb065d9d948d049ef1ef1bd4062cb7831392/crypto/init.c#L427) → [`CONF_modules_unload`](https://github.com/openssl/openssl/blob/7f04bb065d9d948d049ef1ef1bd4062cb7831392/crypto/conf/conf_mod.c#L620), within which there are these two call paths:

1. [`conf_modules_finish_int`](https://github.com/openssl/openssl/blob/7f04bb065d9d948d049ef1ef1bd4062cb7831392/crypto/conf/conf_mod.c#L512) → [`ossl_synchronize_rcu`](https://github.com/openssl/openssl/blob/7f04bb065d9d948d049ef1ef1bd4062cb7831392/crypto/conf/conf_mod.c#L577)

   This one runs perfectly OK.

2. [`ossl_synchronize_rcu`](https://github.com/openssl/openssl/blob/7f04bb065d9d948d049ef1ef1bd4062cb7831392/crypto/conf/conf_mod.c#L544)

   This is the call where the hang happens.

So, am I reading this right, that in the first call (1), `lock->next_to_retire` matches `ID_VAL(count)`, and thereby doesn't wait for the cond, and then increments `lock->next_to_retire`, so in the second call (2), `lock->next_to_retire` doesn't match `ID_VAL(count)` any longer, and it thereby waits on the cond...  which never happens ('cause single-thread, yeah?).

Why this doesn't cause a problem elsewhere, I do not know...

**Comment by levitte** [comment]
> EDIT: I realise that there are other RCU calls surrounding `ossl_synchronize_rcu()` calls. I'll do some debugging to see what conditions are changed from one call to another.

Nope.  A quick run of sanitytest.exe revealed that in the first `ossl_synchronize_rcu()` call, `lock->next_to_retire == 0` and `count == 0`, while in the second call, `lock->next_to_retire == 1` and `count == 0`.

**Comment by levitte** [comment]
I did the exact same run on Linux, and was surprised to see `count == 4294967296` (4294967296 is 0x100000000) on the second call.  That had me take a closer look at this:

https://github.com/openssl/openssl/blob/5a13d35f243be66f6ad914aefe99fb708812dff1/crypto/threads_pthread.c#L542

And yeah, while this call expands to this on Linux:

            count = (uint64_t)__atomic_load_n(&qp->users, __ATOMIC_ACQUIRE);

... on VMS, it expands to:

            count = (uint64_t)fallback_atomic_load_n((void **)&qp->users);

A closer look at that function (yeah, casting whatever to a pointer is quite ugly, but works, usually):

https://github.com/openssl/openssl/blob/5a13d35f243be66f6ad914aefe99fb708812dff1/crypto/threads_pthread.c#L86-L94

Looks like it should work, yeah?  It should...  if you assume that pointers are 64-bit values.  However, the default with VMS C is 32-bit pointers, so `qp->users` ends up being truncated to the lower 32 bits, and the result is that `ID_VAL(count)` will always be zero.

At this point, I've enough food to fix this.  It turns out that VMS C actually supports real atomics, we just haven't caught up.  Now's the time, if any.

**Comment by t8m** [comment]
What about other 32 bit architectures that fallback to this. They will have the same problem, won't they?

**Comment by levitte** [comment]
Yup

**Comment by levitte** [comment]
I do have an idea or two how to fix this.  It's going to be a bit of refactoring...

**Comment by rsbeckerca** [comment]
There are platforms still requiring 32-bit builds - One of the NonStop builds does, so maintaining 32-bit compatibility is highly desirable. Threaded builds on NonStop are 64-bit.
