### ISSUE TITLE
A memory leak defect exists at line 570 in /openssl/crypto/provider_core.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [openssl/openssl#24095]
In /openssl/crypto/provider_core.c, a variable named 'template' is defined at line 524. Its member 'template.parameters' is dynamically allocated at line 561 using the function sk_INFOPAIR_new_null. When the if statement at line 562 returns false, it indicates a successful allocation of dynamic memory for 'template.parameters'. However, if the if statement at line 568 returns true, the program will return at line 570 without executing the memory release operation for 'template.parameters' at line 578, resulting in a memory leak as shown below:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_3.png

**Comment by t8m** [comment]
Fix in #24100

**Comment by LuMingYinDetect** [comment]
> Fix in #24100
> 
> Thank you for the report.

I am happy to be able to contribute to OpenSSL!
