### ISSUE TITLE
There is a memory leak defect on line 413 of the file /openssl/crypto/x509/v3_addr.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [openssl/openssl#24098]
1.On line 410 of the file /openssl/crypto/x509/v3_addr.c, a pointer variable named 'aor' is defined and a dynamic memory area is allocated through the function IPAddressOrRange_new. When the if statement on line 412 returns true, the program will return on line 413, thereby bypassing the release operation on the memory area pointed to by the 'aor' pointer on line 430. This constitutes a memory leak defect, as shown in the diagram below:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_4.png

**Comment by t8m** [comment]
Fix in #24102
