### ISSUE TITLE
GOST engine dll name in mingw

### ISSUE THREAD

**Issue by turboj** [openssl/openssl#241]
The GOST engine DLL gets named: `gosteay32.dll`, but loading the engine only works when renamed to `gost.dll`. This makes the gost test fail by default in `make test`. 

After renaming the file in `engines/ccgost/` to `gost.dll` the test works.

Is this a bug in the engine loader or should the name be `gost.dll` in Windows OS?

**Comment by galeksandrp** [comment]
@turboj Could you please mention full path on which dll should be placed to work? I'm trying to enable GOST engine on `OpenSSL 1.0.2j` on `Git Bash/MSYS2`.

**Comment by richsalz** [comment]
GOST is now a separate release, not part of OpenSSL.  Not going to fix this for 1.0.2
