### ISSUE TITLE
There is a memory leak defect on line 28 of the file /openssl/test/prov_config_test.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [openssl/openssl#24106]
On line 23 of the file /openssl/test/prov_config_test.c, a pointer variable named 'ctx' is defined and dynamic memory is allocated for it through the function OSSL_LIB_CTX_new. When the if statement on line 27 returns true, the program will return on line 28. The if statement on line 27 primarily tests whether the pointer 'configfile' is available. When 'configfile' is unavailable, it is still possible for the dynamic memory area pointed to by the variable 'ctx' to be successfully allocated. However, since the program returns on line 28, the release operation on the dynamic memory area pointed to by the 'ctx' pointer on line 45 is not executed, resulting in a memory leak, as shown in the diagram below:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_11.png

**Comment by t8m** [comment]
The configfile pointer actually cannot be NULL as it is tested in setup_tests().

However as a cleanup it would be nice to remove this redundant call. And there is a potential leak further down.
