### ISSUE TITLE
EVP_PKEY_CTX_add1_hkdf_info no longer accept empty argument

### ISSUE THREAD

**Issue by trinity-1686a** [openssl/openssl#24130]
We got [a report](https://gitlab.torproject.org/tpo/core/tor/-/issues/40928#note_3018785) that `tor` tests no longer pass with the latest commits of openssl.
After investigation, it seems `EVP_PKEY_CTX_add1_hkdf_info` (modified in 6b566687b58fde08b28e3331377f050768fad89b) used to allow infolen=0, and would then behave as a no-op, but it now returns an error instead. It's simple enough to fix on our end, but I feel like this change could take other projects by surprise.

How to reproduce:
```c
//main.c
#include <openssl/evp.h>
#include <openssl/kdf.h>
#include <stdio.h>

int main() {
  EVP_PKEY_CTX *evp_pkey_ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_HKDF, NULL);
  EVP_PKEY_derive_init(evp_pkey_ctx);
  EVP_PKEY_CTX_set_hkdf_md(evp_pkey_ctx, EVP_sha256());
  if (EVP_PKEY_CTX_add1_hkdf_info(evp_pkey_ctx, NULL, 0) == 1)
    printf("OK\n");
  else
    printf("KO\n");
}
```
```sh
> gcc main.c -o main -lssl -lcrypto
> ./main # with system openssl: OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
OK
> LD_LIBRARY_PATH=/opt/openssl/lib64 ./main # build from 491bbb4
KO
```

**Comment by trinity-1686a** [comment]
some code analysis
this happens only if this is the first call to `EVP_PKEY_CTX_add1_hkdf_info` (i.e. appending something and then nothing works, but appending nothing directly doesn't), and comes from this bit of code:
https://github.com/openssl/openssl/blob/d4188f24866f88b4269110ce86f9545edd44c846/crypto/evp/pmeth_lib.c#L1043-L1045
on the first call, the current size is zero, and the newly added size is also zero.

a possible fix could look like this:
```patch
diff --git a/crypto/evp/pmeth_lib.c b/crypto/evp/pmeth_lib.c
index 65f5fcb804..0a561323f1 100644
--- a/crypto/evp/pmeth_lib.c
+++ b/crypto/evp/pmeth_lib.c
@@ -1027,6 +1027,8 @@ static int evp_pkey_ctx_add1_octet_string(EVP_PKEY_CTX *ctx, int fallback,
     if (datalen < 0) {
         ERR_raise(ERR_LIB_EVP, EVP_R_INVALID_LENGTH);
         return 0;
+    } else if (datalen == 0) {
+        return 1;
     }
 
     /* Get the original value length */
```

**Comment by t8m** [comment]
@trinity-1686a Would you like to submit a PR with the proposed fix?
