### ISSUE TITLE
[BUG] SSL_read bad length when upload 2.9GB file

### ISSUE THREAD

**Issue by adlternative** [openssl/openssl#24143]
I encountered an nginx error while uploading a large 2.9GB file to my server. Does anyone know how to resolve this issue?

```
2024/04/15 19:07:40 [crit] 6348#6348: *51273  SNI: xxx.xxx.com SSL_read() failed (SSL: error:140DF10F:SSL routines:SSL_read:bad length), client: xx.xx.xx.xx, server:xxx.xxx.com, request: "PUT /adl/lfs-test-repo2.git/info/lfs/objects/fcac6f56113d2923b67739da64b92793b7254c855e84de801e4b6c6bdd8e2f2a/3145728000 HTTP/1.1", host: "xxx.xxx.com"
```

nginx version: nginx/1.18.0

**Comment by nhorman** [comment]
My guess would be that nginx, using SSL_read wrapped the number of bytes in num parameter, becoming < 0, which would trigger the above error.

Proper fix is llikely to have ngingx switch to using SSL_read_ex, which passes the number of bytes to read properly as a size_t, rather than an int value
