### ISSUE TITLE
ossl_asn1_string_to_time_t fails on NonStop in 3.3.0

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#24176]
I have encountered an issue with `ossl_asn1_string_to_time_t` having issues in a big-endian x86_64 situation. What I am seeing is below:
```
90-test_asn1_time.t .....................
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:439
        # [210327235959Z] compared to [210328005959Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:443
        # ossl_asn1_string_to_time_t (210328005959Z) failed: expected 1616893199, got 1616889599
        #
        # OPENSSL_TEST_RAND_SEED=1713349126
        not ok 74 - iteration 1
# ------------------------------------------------------------------------------
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:439
        # [210328000000Z] compared to [210328010000Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:443
        # ossl_asn1_string_to_time_t (210328010000Z) failed: expected 1616893200, got 1616889600
        #
        # OPENSSL_TEST_RAND_SEED=1713349126
        not ok 75 - iteration 2
# ------------------------------------------------------------------------------
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:439
        # [210327235959Z] compared to [210328005959Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:443
        # ossl_asn1_string_to_time_t (20210328015959+0100) failed: expected 1616893199, got 1616889599
        #
        # OPENSSL_TEST_RAND_SEED=1713349126
        not ok 76 - iteration 3
# ------------------------------------------------------------------------------
        # ERROR: (time_t) 'testdateutc == asn1_to_utc[idx].expected' failed @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:439
        # [210328000000Z] compared to [210328010000Z]
        # INFO:  @ /home/ituglib/randall/openssl-3.3.0/test/asn1_time_test.c:443
        # ossl_asn1_string_to_time_t (20210328030000+0200) failed: expected 1616893200, got 1616889600
        #
        # OPENSSL_TEST_RAND_SEED=1713349126
        not ok 77 - iteration 4
# ------------------------------------------------------------------------------
    # OPENSSL_TEST_RAND_SEED=1713349126
    not ok 7 - convert_asn1_to_time_t
# ------------------------------------------------------------------------------
../../util/wrap.pl ../../test/asn1_time_test => 255
not ok 1 - running asn1_time_test
```

**Comment by rsbeckerca** [comment]
> AFAIK we do not see the issue on linux big endian cross-compiled targets so this is most probably something NonStop specific.

The difference is exactly 1 hour. This looks like a timezone problem. I am checking whether this is a system setup problem or exists across multiple boxes in different timezones.

**Comment by rsbeckerca** [comment]
This is not a valid assumption:
```
#if ((ULONG_MAX >> 31) >> 31) >= 1
```
`time_t` can be 32 bits on some platforms. We have a specific need to support 32-bit builds. Has OpenSSL specifically stated no 32-bit time_t support?

**Comment by rsbeckerca** [comment]
If I set `export TZ=MDT` the test passes. I suspect the time configuration on the test box I am using may be wrong.

**Comment by levitte** [comment]
> This is not a valid assumption (although unrelated to the case):
> 
> ```
> #if ((ULONG_MAX >> 31) >> 31) >= 1
> ```
> 
> `time_t` can be 32 bits on some platforms. We have a specific need to support 32-bit builds. Has OpenSSL specifically stated no 32-bit time_t support?

That's in this section of code, in a different test than the one failing:

https://github.com/openssl/openssl/blob/4e3c1e6206251c59855362d6d2edab4621c31dec/test/asn1_time_test.c#L449-L471

The failing test is this function, which doesn't have the 64-bit requirement as far as I can see:

https://github.com/openssl/openssl/blob/4e3c1e6206251c59855362d6d2edab4621c31dec/test/asn1_time_test.c#L433-L447

> If I set `export TZ=MDT` the test passes. I suspect the time configuration on the test box I am using may be wrong.

That starts to seem likely.  Does the command `date` (if you have that command) give you a clue?

**Comment by rsbeckerca** [comment]
I am waiting on the person who configured the system to get back to me with DST table information. The system is only 2 days old, so there are likely issues. Will report back.

**Comment by nhorman** [comment]
Any update here?  I think you're right about the timezone issue.  If I don't hear back in 30 days, I'll assume this is resolved.

**Comment by rsbeckerca** [comment]
> Any update here? I think you're right about the timezone issue. If I don't hear back in 30 days, I'll assume this is resolved.

At conference for a few days ($DAYJOB). Will get back in about a week.

**Comment by MeerMusik** [comment]
Hello. Sorry no Solution but a Question from my end and partially Sorry for HighJacking this Issue, as I did not found a Solution on the Web.

I have the same Issue under MSYS2 with all 32-Bit Builds failing this specific Test, while 64-Bit work fine (except the known as broken Tests 2 and 3 for which there is already an open Issue from April).

My Question: Is there a way to disable or ignore this Test specifically, while running all other default Tests, through a configure Flag, an Environment Varable like ```export Test90=Disabled``` etc. when building OpenSSL with ```make --jobs=$(nproc) test```? I am running Shell Scripts in MSYS2 to automatically build stuff.

Thanks in advance!

**Comment by t8m** [comment]
You can use `make test TESTS='-test_<failing_test_name>'`

**Comment by MeerMusik** [comment]
> You can use `make test TESTS='-test_<failing_test_name>'`

Thank you very much! Have a nice relaxing weekend :)
