### ISSUE TITLE
25391ac broke llvm-mingw x86_64

### ISSUE THREAD

**Issue by Andarwinux** [openssl/openssl#24184]
[Crash](https://github.com/mpv-player/mpv/issues/13918) when using mpv to access https via ffmpeg(--enable-openssl)

Backtrace: 
[mpv.txt](https://github.com/openssl/openssl/files/15022190/mpv.txt)

Fixed this with `git revert --no-edit 25391ac`

**Comment by tom-cosgrove-arm** [comment]
The commit is from #23997 (to have the back-link here)

**Comment by t8m** [comment]
@Sashan I think there is missing `.previous` in ecp_nistz256-x86_64.pl before line 4739

**Comment by Sashan** [comment]
I'm sorry about that. I think @t8m is right. I'm going to take a look into it and hopefully get back with fix soon. If you need to get unstuck either blackout the change (as you did) or build with `no-asm` option.

**Comment by Sashan** [comment]
@Andarwinux can you give a try to one-liner change in pull request here:
https://github.com/openssl/openssl/pull/24192/files

thank you very much.

**Comment by Sashan** [comment]
> > @Andarwinux can you give a try to one-liner change in pull request here: https://github.com/openssl/openssl/pull/24192/files
> > thank you very much.
> 
> Sorry for the late reply, unfortunately #24192 does not fixes the problem. Just a `.text` at ecp_nistz256-x86_64.s line 2376, and the backtrace makes no difference.

can you attach ecp_nistz256-x86_64.s which Is created with fixed file? the issue might be hiding  in `crypto/perlasm/x86_64-xlate.pl` This is the script which modifies output of `ecp_nistz256-x86_64.pl` depending on your build configuration. Therefore I prefer to obtain also `.s` file so I can compare the results and see where to look for bug. Thanks a lot.

**Comment by Sashan** [comment]
@Andarwinux thanks for link I'll take a look. I'm struggling with github workflows. I was trying to get openssl unit tests working in CYGWIN on windows. I've managed to sort out unix vs. dos line terminators. but there seems to be lot of friction in runtime part. more time will be required. I'll look at your `msys2` if I'll be able to get it working with openssl build.

there is another [commit](https://github.com/openssl/openssl/pull/24192/commits/540bc815f833db5d37efba694753be7a40d6aa5a) in my pull request. it is a fix to `x86_64-xlate.pl` script. it should hopefully fix the assembly file for `ecp_nistz256-x86_64.s`. Will appreciate if you will be able to try it. thanks for help.

**Comment by Sashan** [comment]
thank you very much for quick testing. I still have to figure out how to run tests for mingw/cygwin bits, so that type of glitch can be discovered earlier.
