### ISSUE TITLE
[rt.openssl.org #4664] Enhancement: better handling of CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2420]
Migrated from [rt.openssl.org#4664](https://rt.openssl.org/Ticket/Display.html?id=4664) (status was 'open')

Requestors:
* floppym@gentoo.org

From floppym@gentoo.org on 2016-08-28 16:33:33:
```
With the current build system, user-defined CFLAGS are accepted as any
unrecognized command line argument passed to Configure. This seems a
little dangerous to me since it means a simple typo could end up
getting passed to the C compiler.

As well, the current build system forcibly enables optimization (-O3)
or debug symbols (-g) depending on the build type (--release or
--debug).

There does not appear to be any method for the user to pass additional
LDFLAGS to the build system.

I would like to propose the following changes:

1. Read CFLAGS and LDFLAGS from the environment within the Configure script.
2. Allow the user to opt-out of the default release or debug cflags,
perhaps by adding a third build type (neither release nor debug).

These changes would my job as a distro maintainer on Gentoo Linux just
a little bit easier.

```

From tmraz@redhat.com on 2016-08-29 07:36:49:
```
I would like to join this request as maintainer of OpenSSL for Fedora
and Red Hat Enterprise Linux. It would clean up things for us as well.

-- 
Tomas Mraz
No matter how far down the wrong road you've gone, turn back.
                                              Turkish proverb
(You'll never know whether the road is wrong though.)



```

From appro@openssl.org on 2016-08-29 12:27:59:
```
> With the current build system, user-defined CFLAGS are accepted as any
> unrecognized command line argument passed to Configure. This seems a
> little dangerous to me since it means a simple typo could end up
> getting passed to the C compiler.

Is it more dangerous than interactive access? But on serious note I
don't quite grasp the problem. How do you pass CFLAGS? Or rather how is
it specific to OpenSSL? I mean you either set CFLAGS environment
variable and call 'make -e' or call 'make CFLAGS=something', right? But
this is the way *make* is. Or is suggestion that we should implement own
internal .ext1.ext2 rules independent on CFLAGS?

> As well, the current build system forcibly enables optimization (-O3)
> or debug symbols (-g) depending on the build type (--release or
> --debug).

Could you elaborate on the problem? If you need release build with debug
symbols you can simply add -g when configuring...

> There does not appear to be any method for the user to pass additional
> LDFLAGS to the build system.

You can pass them as arguments to ./Configure script. It recognizes -L,
-l and -Wl,.

> I would like to propose the following changes:
> 
> 1. Read CFLAGS and LDFLAGS from the environment within the Configure script.
> 2. Allow the user to opt-out of the default release or debug cflags,
> perhaps by adding a third build type (neither release nor debug).
> 
> These changes would my job as a distro maintainer on Gentoo Linux just
> a little bit easier.

Or maybe ("maybe" is reference to "I don't quite grasp" above) what we
are talking about is Configure reading CFLAGS and LDFLAGS and *adding*
them to generated Makefile. I mean we are not talking about passing them
to 'make', but "freezing" them to their values at configure time. Could
you clarify?


```

From levitte@openssl.org on 2016-08-29 14:27:18:
```
On Mon Aug 29 12:27:59 2016, appro wrote:
> > With the current build system, user-defined CFLAGS are accepted as
> > any
> > unrecognized command line argument passed to Configure. This seems a
> > little dangerous to me since it means a simple typo could end up
> > getting passed to the C compiler.
>
> Is it more dangerous than interactive access? But on serious note I
> don't quite grasp the problem. How do you pass CFLAGS? Or rather how
> is
> it specific to OpenSSL? I mean you either set CFLAGS environment
> variable and call 'make -e' or call 'make CFLAGS=something', right?
> But
> this is the way *make* is. Or is suggestion that we should implement
> own
> internal .ext1.ext2 rules independent on CFLAGS?
>
> > As well, the current build system forcibly enables optimization (-O3)
> > or debug symbols (-g) depending on the build type (--release or
> > --debug).
>
> Could you elaborate on the problem? If you need release build with
> debug
> symbols you can simply add -g when configuring...
>
> > There does not appear to be any method for the user to pass
> > additional
> > LDFLAGS to the build system.
>
> You can pass them as arguments to ./Configure script. It recognizes
> -L,
> -l and -Wl,.
>
> > I would like to propose the following changes:
> >
> > 1. Read CFLAGS and LDFLAGS from the environment within the Configure
> > script.
> > 2. Allow the user to opt-out of the default release or debug cflags,
> > perhaps by adding a third build type (neither release nor debug).
> >
> > These changes would my job as a distro maintainer on Gentoo Linux
> > just
> > a little bit easier.
>
> Or maybe ("maybe" is reference to "I don't quite grasp" above) what we
> are talking about is Configure reading CFLAGS and LDFLAGS and *adding*
> them to generated Makefile. I mean we are not talking about passing
> them
> to 'make', but "freezing" them to their values at configure time.
> Could
> you clarify?

I assume, and please correct me if I'm wrong, that the request is to treat the
environment variables CFLAGS and LDFLAGS the same way we treat CC, i.e. as an
initial value to be used instead of what we get from the configuration target
information.

This should be quite easy to implement, and we can also continue to use
whatever additional Configure arguments as compiler or linker flags to be used
*in addition* to the initial value (that comes from the config target
information, or if we decide to implement it, CFLAGS)

Cheers,
Richard

-- 
Richard Levitte
levitte@openssl.org
```

From tmraz@redhat.com on 2016-08-29 16:00:21:
```
On Po, 2016-08-29 at 14:27 +0000, Richard Levitte via RT wrote:
> On Mon Aug 29 12:27:59 2016, appro wrote:
> >Â 
> > Or maybe ("maybe" is reference to "I don't quite grasp" above) what
> > we
> > are talking about is Configure reading CFLAGS and LDFLAGS and
> > *adding*
> > them to generated Makefile. I mean we are not talking about passing
> > them
> > to 'make', but "freezing" them to their values at configure time.
> > Could
> > you clarify?
> I assume, and please correct me if I'm wrong, that the request is to
> treat the
> environment variables CFLAGS and LDFLAGS the same way we treat CC,
> i.e. as an
> initial value to be used instead of what we get from the
> configuration target
> information.
> 
> This should be quite easy to implement, and we can also continue to
> use
> whatever additional Configure arguments as compiler or linker flags
> to be used
> *in addition* to the initial value (that comes from the config target
> information, or if we decide to implement it, CFLAGS)

Ideally the optimization/debugging flags not affecting directly the
code that is being compiled would be replaced with what is placed into
CFLAGS/LDFLAGS. But things like -D would be kept from the config target
information.

--Â 
Tomas Mraz
No matter how far down the wrong road you've gone, turn back.
                                              Turkish proverb
(You'll never know whether the road is wrong though.)



```

**Comment by rcombs** [comment]
Honestly the current situation is pretty terrible. The mechanism for adding custom CFLAGS or LDFLAGS is undocumented and extremely confusing; it's not surprising that many build scripts resort to running `sed` on `Makefile`. I'm currently just sticking flags in `CC` and `LD` and running `make -e`, which is a bit of deep magic that nobody ever expects to have to do when configuring a build system. Some basic rules that pretty much other system follows:

- When running the configure tool (`cmake`, `configure`, `waf`, etc…), all relevant env vars (CC, LD, CFLAGS, LDFLAGS, etc…) are recorded. Never rely on the user to run `make -e`, to set env vars at compile-time, or to set flags as additional arguments to `make`. Nobody expects this.
- For tool names/paths, empty values are filled with detected ones and filled values are left alone.
- For flags, additional strings are appended to the end of the one passed in.

I understand that OpenSSL doesn't use CMake, autoconf, etc…, but there are certain behaviors that everybody expects because they're near-universal. For instance, ffmpeg's configure script is entirely custom, but it still follows these conventions. The only other systems I deal with that don't handle this are poorly-written configure-less Makefiles (gha) and Boost's bjam (just kill me now).

**Comment by burlen** [comment]
agree, it's preferable to have "config" handle CFLAGS in the usual way, the same as autotools and CMake handle them. eg I would like to pass them this way:
```
CFLAGS="-O3 -march=native -mtune=native" ./config
```
This is the standard way for like 20-30 years, no?

Context: shipping a CMake script that builds our library with its dependencies, one of which is OpenSSL. Automating these builds is simpler when folks follow the well established conventions.

**Comment by richsalz** [comment]
So should the environment's CFLAGS variables replace what is in the default config?  Or agument them?  It should probably replace.

**Comment by levitte** [comment]
I was rather thinking that these two would mean the same:

```
./config -O3 -march=native -mtune=native
```

```
CFLAGS="-O3 -march=native -mtune=native" ./config
```

The difference is that with the latter, the user says exactly which flags should be considered C flags, LD flags, etc etc etc, instead of having `Configure` guessing.

**Comment by rcombs** [comment]
The standard autoconf behavior is that whatever's in the env at config-time replaces the default flags, `-g -O2` (iirc, without the optimization flag in debug builds), but flags added by the configure.ac script explicitly are generally augmenting (as opposed to being replaced).

**Comment by burlen** [comment]
> ‘variable=value’
> Set the value of the variable variable to value. This is used to override the default values of commands or arguments in the build process. For example, the user could issue ‘configure CFLAGS=-g CXXFLAGS=-g’ to build with debugging information and without the default optimization.
> 
> Specifying variables as arguments to configure, like this:
> 
> ./configure CC=gcc
> is preferable to setting them in environment variables:
> 
> CC=gcc ./configure
> as it helps to recreate the same configuration later with config.status. However, both methods should be supported.


https://www.gnu.org/prep/standards/html_node/Configuration.html

**Comment by richsalz** [comment]
OpenSSL sets a whole bunch of other flags in CLFAGS, including various defines – take a look at the CLFAGS output after running config, for example. It does not follow the GNU conventions. Therefore, this request is very very hard to do.  Probably impossible to get right.

**Comment by rcombs** [comment]
A lot of configure scripts have similar behavior; that just means the config-defined flags need to be appended, rather than being replaced.

**Comment by levitte** [comment]
> OpenSSL sets a whole bunch of other flags in CLFAGS, including various defines – take a look at the CLFAGS output after running config, for example. It does not follow the GNU conventions. Therefore, this request is very very hard to do.  Probably impossible to get right.

I disagree.  Those added definitions would be similar to, as @rcombs put it, "but flags added by the configure.ac script explicitly are generally augmenting (as opposed to being replaced)"

**Comment by richsalz** [comment]
Look forward to your PR, @levitte :)

**Comment by levitte** [comment]
I'm sure.  Not tonight, though, it's time I drop into bed o'er here.

**Comment by mattcaswell** [comment]
Hey @levitte are you out of bed yet? What do we do with this issue?

**Comment by levitte** [comment]
Heh...

Thanks for the reminder.  This has actually been on my mind for a bit, and recent changes in the config stuff has actually made this easier.
