### ISSUE TITLE
"Error finalizing cipher loop" when running openssl speed -evp -decrypt for sm4-gcm and sm4-ccm

### ISSUE THREAD

**Issue by ravulapx** [openssl/openssl#24250]
While running speed decrypt for sm4-gcm and sm4-ccm in openssl3.2 getting **Error finalizing cipher loop** error.

![image](https://github.com/openssl/openssl/assets/138493920/c0d2c3a5-da83-4080-ad32-bbcec2a5683d)
![image](https://github.com/openssl/openssl/assets/138493920/c6627cb4-07c3-49df-99c9-cbae83ecbff0)

Note: Similar issue seen in [openssl#23657](https://github.com/openssl/openssl/issues/23657) and they mentioned that fix was available in [PR#23757](https://github.com/openssl/openssl/pull/23757) and it got merged into master branch. But still seeing an issue with master branch for sm4-gcm and sm4-ccm.

**Comment by ravulapx** [comment]
Issue is seen with master branch as well
Any update on this please convey

**Comment by t8m** [comment]
Fixed on all the branches thanks to @zelda923
