### ISSUE TITLE
pkg-config files are no longer relocatable with 3.3

### ISSUE THREAD

**Issue by lazka** [openssl/openssl#24298]
Starting with 3.3.0 the pkg-config files are missing a prefix and are using hardcoded paths instead of `${prefix}`, breaking relocation on Windows:

new:

```
libdir=/clang64/lib
includedir=/clang64/include

Name: OpenSSL-libssl
Description: Secure Sockets Layer and cryptography libraries
Version: 3.3.0
Requires.private: libcrypto
Libs: -L${libdir} -lssl
Cflags: -I${includedir}
```

old:

```
prefix=/clang64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: OpenSSL-libssl
Description: Secure Sockets Layer and cryptography libraries
Version: 3.2.1
Requires.private: libcrypto
Libs: -L${libdir} -lssl
Cflags: -I${includedir}
```

On Windows (and Unix) to make .pc files relocatable, paths should use `${prefix}`, or if that's for some reason isn't possible then there is a fallback where every path that starts with the `prefix` recorded in the file is converted to use `${prefix}` internally.

Starting with 3.3 the paths are no longer derived from `${prefix}` and `prefix` is missing, which breaks relocation (also on Unix, but it's not that commonly used there)

**Comment by jasagredo** [comment]
Unless I am mistaken, it seems to me that this is also manifesting in macOS via `brew`. Notice the difference in `.pc` files for openssl 3.0.13 and 3.3.0:

```
bash-3.2$ cat /opt/homebrew/Cellar/openssl\@3.0/3.0.13/lib/pkgconfig/libssl.pc
prefix=/opt/homebrew/Cellar/openssl@3.0/3.0.13
exec_prefix=${prefix}
libdir=/opt/homebrew/Cellar/openssl@3.0/3.0.13/lib
includedir=${prefix}/include

Name: OpenSSL-libssl
Description: Secure Sockets Layer and cryptography libraries
Version: 3.0.13
Requires.private: libcrypto
Libs: -L${libdir} -lssl
Cflags: -I${includedir}


bash-3.2$ cat /opt/homebrew/Cellar/openssl\@3/3.3.0/lib/pkgconfig/libssl.pc
libdir=/opt/homebrew/Cellar/openssl@3/3.3.0
includedir=/opt/homebrew/Cellar/openssl@3/3.3.0/include

Name: OpenSSL-libssl
Description: Secure Sockets Layer and cryptography libraries
Version: 3.3.0
Requires.private: libcrypto
Libs: -L${libdir} -lssl
Cflags: -I${includedir}
```

**Comment by h-vetinari** [comment]
There are also tools that do `pkg-config --variable=prefix openssl` for populating `OPEN_SSL_ROOT`. This obviously broke too.

**Comment by h-vetinari** [comment]
Gentle ping @levitte

**Comment by levitte** [comment]
Tanks for the ping, this issue slided under my radar.  I'll have a look in the coming week

**Comment by h-vetinari** [comment]
Another month, another gentle ping @levitte :)

**Comment by levitte** [comment]
Thanks for the gentle pings, @h-vetinari.  Please have a look at #24687
