### ISSUE TITLE
engine.pod out of date

### ISSUE THREAD

**Issue by djw1149** [openssl/openssl#243]
doc/crypto/engine.pod is the primary documentation on the engine feature and was last edited 7 years ago.  It is out of date.  In particular, it discusses the 0.9.7 and 0.9.8 engine code differences and talks about "Future developments" at the end of the document.  Can someone who knows the current status of engines update it a bit, please?

**Comment by mattcaswell** [comment]
Looks like that discussion has been removed from the latest version in master, and I see numerous commits in that file. Closing.
