### ISSUE TITLE
`SSL_SESSION_set_time` incorrect documentation

### ISSUE THREAD

**Issue by ctz** [openssl/openssl#24322]
Version: main at time of writing.

Of `SSL_SESSION_set_time`, the docs say:

https://github.com/openssl/openssl/blob/067fbc01b9e867b31c71091d62f0f9012dc9e41a/doc/man3/SSL_SESSION_get_time.pod?plain=1#L63

This is not correct: `SSL_SESSION_set_time` returns the new time, or 0 on error.

**Comment by mattcaswell** [comment]
Agreed, this looks incorrect. Adding good first issue and help wanted labels.
