### ISSUE TITLE
There is a memory leak defect at line 95 of the file /openssl/ssl/quic/quic_trace.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [openssl/openssl#24340]
At line 79 of the file /openssl/ssl/quic/quic_trace.c, a pointer variable named ack_ranges is defined. This variable allocates a dynamic memory region via the function OPENSSL_zalloc at line 86. Since the function OPENSSL_zalloc at line 86 is within an if statement, when this if statement returns false, it indicates successful allocation of the dynamic memory region pointed to by ack_ranges. Subsequently, at line 90, the program assigns the dynamic memory region pointed to by ack_ranges to ack.ack_ranges. Similarly, ack is also a local variable defined within this function. When the if statement at line 94 returns true, the program will return at line 95 without executing the release operation for the dynamic memory region pointed to by ack_ranges at line 115. This constitutes a memory leak defect, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_21.png

**Comment by changkhothuychung** [comment]
Hi, this is my first time trying openssl, can this issue be assigned to me? I would like to give it a try, thanks!

**Comment by paulidale** [comment]
Go for it...
I don't think there is a need to assign it to you.
Just include a line `Fixes #24340` in the commit message of your fix.
