### ISSUE TITLE
Cannot build libssl.a in isolation: "make build_ssl" also builds apps

### ISSUE THREAD

**Issue by byron-hawkins** [openssl/openssl#24428]
In any environment, with any build configuration, sub-targets like `build_ssl` and `build_crypto` will not only build `libssl.a` and/or `libcrypto.a`, but will continue with other targets that were not indicated on the `make` command line. Instead, the command `make build_ssl` should only build `libssl.a` and anything it depends on. No apps or tests or engines should be built.

This is a blocking failure for use cases like generating a bitcode version of `libssl.a`, which requires the `-emit-llvm` flag on `CC`. If `make` attempts to build any executable with `-emit-llvm`, `clang` exits with an error that it cannot produce bitcode while linking. So we need targets that build only `*.a` files, without attempting to link anything.

**Comment by levitte** [comment]
In our build file (Makefile) templates, there are no `build_ssl` and `build_crypto`, so dunno how you ended up using them.  There is a `build_libs`, though, did you try that one?  It *shouldn't* cause the apps to be built (but if you run `make test`, that will indeed cause the app to be built, 'cause many of our tests depend on it).

**Comment by byron-hawkins** [comment]
From the top `Makefile` in the `1.0.2d` release:

    build_crypto:
            @dir=crypto; target=all; $(BUILD_ONE_CMD)
    build_ssl: build_crypto
            @dir=ssl; target=all; $(BUILD_ONE_CMD)

These do cause apps to be built. Target `build_libs` also causes apps to be built, without invoking `make tests` anywhere. Not having much expertise in makefiles, I would suggest that `target=all`  is causing make to ascend and build all from the top. At some point I may resort to patching this with `target=libs` to prevent this.

**Comment by nhorman** [comment]
1.0.2d has been out of support for some time, and those targets no longer exist.

**Comment by byron-hawkins** [comment]
A legacy build is unfortunately necessary in this case.

**Comment by nhorman** [comment]
then I'm afraid you will have to manually fixup the makefile to build just what you want.  though , I just tried:
```
make build_libcrypto
```
on 1.0.2.d and it only appears to have built libcrypto.so and libcrypto.a

**Comment by byron-hawkins** [comment]
For me, sometimes it builds apps, sometimes it doesn't. It would take some investigation to figure out why. For now it looks like I can move forward to 13.0.3, where the target `build_libs` is reliably stopping after generating the `lib*.a` files. That solves it for me.
