### ISSUE TITLE
There is a memory leak defect at line 495 in the /openssl/test/bad_dtls_test.c file.

### ISSUE THREAD

**Issue by LuMingYinDetect** [openssl/openssl#24444]
In the /openssl/test/bad_dtls_test.c file, at line 469, a pointer variable named sess is defined. This variable is allocated a block of dynamic memory at line 487 through the function client_session. If the if statement at line 488 returns false, it indicates that the dynamic memory allocation to which sess points was successful. When the if statement at line 492 returns true, the program will jump to the end label due to the goto statement at line 495, thereby skipping the deallocation of the dynamic memory pointed to by sess at line 511. The end label does not deallocate the memory pointed to by sess, resulting in a memory leak defect, as shown in the figure below:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_23.png

**Comment by erbsland-dev** [comment]
@nhorman Seems this is an autogenerated issue, the memory leak is fixed in the master branch.
