### ISSUE TITLE
Missing image on https://mta.openssl.org/mailman/listinfo/openssl-announce   (low priority)

### ISSUE THREAD

**Issue by schneidergithub** [openssl/openssl#24451]
The icon in the footer for debian returns a 404 error: 

https://mta.openssl.org/mailman/listinfo/openssl-project/images/mailman/debianpowered.png

**Comment by nhorman** [comment]
![Image](https://github.com/openssl/openssl/assets/1032926/61f61027-60ab-4ef5-bc38-9bd50c0e07eb)

**Comment by nhorman** [comment]
This appears to be fixed
