### ISSUE TITLE
 There is a memory leak defect in line 112 of the /openssl/test/cmp_hdr_test.c file.

### ISSUE THREAD

**Issue by LuMingYinDetect** [openssl/openssl#24469]
In line 105 of the /openssl/test/cmp_hdr_test.c file, a pointer variable named x509name is defined and a block of dynamic memory is allocated through the X509_NAME_new function. If the if statement on line 107 returns false, it indicates that the dynamic memory allocation for x509name was successful. If the if statement on line 111 returns true, the program will return at line 112, thereby skipping the memory release operation for the dynamic memory pointed to by x509name at line 120, resulting in a memory leak defect, as shown in the figure below (note that the defect path provided in the figure does not match my description; my description should be considered accurate):
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_26.png

**Comment by keybodhi** [comment]
i want  help u to sort this promble ：）

**Comment by mattcaswell** [comment]
> i want help u to sort this promble

Please go ahead and create a PR.

**Comment by keybodhi** [comment]
![pic](https://github.com/openssl/openssl/assets/167082422/7dd725c8-3f3f-4e3c-ac30-b43c483a3c3d)
I find this bug had been fix, it doesn't need to be fixed anymore

**Comment by nhorman** [comment]
based on last comment, closing
