### ISSUE TITLE
3.3.0 build problem on VMS IA64 -- Defect in <stdlib.h>

### ISSUE THREAD

**Issue by Antinode-org** [openssl/openssl#24466]
Possibly related to: https://github.com/openssl/openssl/issues/24075

   This is a VMS bug rather than an OpenSSL bug, but it affects OpenSSL.

ITS $ cc /version
VSI C V7.4-001 on OpenVMS IA64 V8.4-2L3

   An ordinary build excites a defect in system header file, <stdlib.h>,
when compiling [.crypto.conf]conf_lib.c:

#if defined _XOPEN_SOURCE || _XOPEN_SOURCE_EXTENDED || !defined _ANSI_C_SOURCE
....................................................^
%CC-W-BADCONSTEXPR, Syntax error in constant expression.
at line number 283 in module STDLIB of text library SYS$COMMON:[SYSLIB]DECC$RTLDEF.TLB;1

   The (known, but not widely distributed) fix is to add the missing
"defined" keyword to the STDLIB module in the appropriate text library,
typically, SYS$COMMON:[SYSLIB]DECC$RTLDEF.TLB.

ITS $ gdiff  decc_include:stdlib.h stdlib.h
283c283
< #if defined _XOPEN_SOURCE || _XOPEN_SOURCE_EXTENDED || !defined _ANSI_C_SOURCE
---
> #if defined _XOPEN_SOURCE || defined _XOPEN_SOURCE_EXTENDED || !defined _ANSI_C_SOURCE

   I haven't checked on Alpha.  It's not a problem on x86_64 with:

V87 $ cc /version
VSI C x86-64 V7.5-009 (GEM 50XBR) on OpenVMS x86_64 V9.2-2  

   See also:
      https://forum.vmssoftware.com/viewtopic.php?f=12&t=9085

**Comment by levitte** [comment]
It is the same sort of thing as #24075, indeed.  The fix should be this, please try it:

``` diff
--- a/Configurations/10-main.conf
+++ b/Configurations/10-main.conf
@@ -2061,7 +2061,8 @@ my %targets = (
                               ? "/WARNINGS=DISABLE=(".join(",",@warnings).")" : (); }),
         cflag_incfirst   => '/FIRST_INCLUDE=',
         lib_defines      =>
-            add("OPENSSL_USE_NODELETE", "_XOPEN_SOURCE", "_XOPEN_SOURCE_EXTENDED",
+            add("OPENSSL_USE_NODELETE",
+                "_XOPEN_SOURCE", "_XOPEN_SOURCE_EXTENDED=1",
                 sub {
                     return vms_info()->{def_zlib}
                         ? "LIBZ=\"\"\"".vms_info()->{def_zlib}."\"\"\"" : ();
```

I'm submitting a fixup PR in a minute.

**Comment by Antinode-org** [comment]
> It is the same sort of thing as #24075, indeed. [...]

   Ah, yes.  I was confusing "CC/DEFINE=FRED", which is equivalent to
"#define FRED 1", with "#define FRED", which is not.

> [...] The fix should be this, please try it: [...]

   Yup.  Given the impracticality of ever getting all the bad <stdlib.h>
in the universe fixed, adding the "=1" work-around here looks to me like
the right way.  Sorry to waste the time.


   Off topic: My "mms test" (IA64, x86_64) hangs after the second test:
      01-test_fipsmodule_cnf.t ................ skipped: Test only [...]
Already known or worth reporting?

**Comment by levitte** [comment]
> Sorry to waste the time.

Not at all, I'm glad it was an easy fix

**Comment by levitte** [comment]
> Off topic: My "mms test" (IA64, x86_64) hangs after the second test:
> 01-test_fipsmodule_cnf.t ................ skipped: Test only [...]
> Already known or worth reporting?

This is nothing I've seen.  Might be worth an `mms test /macro=(V=1)` for verbosity to see a bit better what's going on, and reporting if you can't figure it out.
