### ISSUE TITLE
[rt.openssl.org #4082] Patch: Unable to read SMIME message if there is no signer

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2449]
Migrated from [rt.openssl.org#4082](https://rt.openssl.org/Ticket/Display.html?id=4082) (status was 'new')

Requestors:
* fboranek@atlas.cz

Attachments:
* [smime.p7m](https://rt.openssl.org/Ticket/Attachment/57299/34463/smime.p7m)
* [no_signer.diff](https://rt.openssl.org/Ticket/Attachment/57299/34464/no_signer.diff)
* [smime.p7s](https://rt.openssl.org/Ticket/Attachment/57299/34465/smime.p7s)

From fboranek@atlas.cz on 2015-10-08 19:05:51:
```
_______________________________________________
openssl-bugs-mod mailing list
openssl-bugs-mod@openssl.org
https://mta.openssl.org/mailman/listinfo/openssl-bugs-mod
```

**Comment by mattcaswell** [comment]
There is no description of an issue here, only a patch which makes it impossible to properly evaluate it. Closing.

**Comment by FdaSilvaYY** [comment]
There was a glitch while importing from RT the description of this issue.
The original submission has a description :

> I found that Outook for MAC can generate (depends on setting) signed message where is not included sender's certificate. It works pretty good, but verification requires that recipients must already have sender certificate. Such message is attached.
>...
