### ISSUE TITLE
[rt.openssl.org #4087] Patch for openssl_1_0_2 link failure when OPENSSL_NO_SHA512 defined

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2451]
Migrated from [rt.openssl.org#4087](https://rt.openssl.org/Ticket/Display.html?id=4087) (status was 'open')

Requestors:
* peck@bay2sierra.com

Attachments:
* [Fix_OPENSSL_NO_SHA512_link_error.patch](https://rt.openssl.org/Ticket/Attachment/57388/34544/Fix_OPENSSL_NO_SHA512_link_error.patch)

From peck@bay2sierra.com on 2015-10-11 00:52:40:
```
I discovered that when OPENSSL_NO_SHA512 is defined, the openssl_1_0_2 stable branch build fails during the link step with unresolved symbol EVP_sha384. The attached patch fixes this issue. 

peck@bay2sierra.com 

```

From rsalz@openssl.org on 2016-02-05 17:37:27:
```
Can you re-org the patch so that it doesn't break into the middle if a
compound statement? (across the else)
thanks.
-- 
Rich Salz, OpenSSL dev team; rsalz@openssl.org
```

**Comment by mattcaswell** [comment]
Rich requested changes to this patch, and none were provided so closing.
