### ISSUE TITLE
Latent bugs due to slight misuse of CRYPTO_THREAD locking APIs

### ISSUE THREAD

**Issue by samuel-lee-msft** [openssl/openssl#24517]
Looking at https://www.openssl.org/docs/manmaster/man3/CRYPTO_THREAD_run_once.html, specifically the lines here: https://github.com/openssl/openssl/blob/05faa4ffee7f20fcee129f77d153f2dcc609bdc8/doc/man3/CRYPTO_THREAD_run_once.pod?plain=1#L207-L229

The documentation says "This example safely initializes and uses a lock.", but there's technically a race condition in the example.

Specifically, let's suppose we have threads A, B, and C and lock is already initialized:

A calls mylock() and for whatever reason `CRYPTO_THREAD_write_lock` fails
B calls mylock() and succeeds
A calls myunlock() and succeeds
C calls mylock() and succeeds
B and C modify state which is supposed to be guarded by the lock at the same time 

Based on feedback from Tomas Mraz and Matt Caswell, _current_ implementations of the CRYPTO_THREAD lock APIs will not ever trigger this condition as either:
a) `CRYPTO_THREAD_unlock` fails when the lock is taken by another thread (pthread), or
b) `CRYPTO_THREAD_write_lock` never fails (Windows)

So the issue is more of a latent reliability bug - if locking APIs change under OpenSSL code, callers of the locking APIs of this form could start to fail.
This form of unconditional unlocking is also potentially problematic if taking the lock fails due to the thread already having the lock (i.e. EDEADLK returned from pthread). This almost certainly would indicate a separate bug in the calling application.

I found that the unconditional unlocking pattern occurs in production OpenSSL code (though almost all callers of CRYPTO_THREAD_*_lock immediately return on error, a few do not):

BIO_lookup_ex: https://github.com/openssl/openssl/blob/05faa4ffee7f20fcee129f77d153f2dcc609bdc8/crypto/bio/bio_addr.c#L808
ossl_engine_table_select: https://github.com/openssl/openssl/blob/05faa4ffee7f20fcee129f77d153f2dcc609bdc8/crypto/engine/eng_table.c#L220

I also spotted some potential deadlocks due to codepaths returning when a global lock is held (again I understand that with current implementation, these return paths should never be triggered, so just a latent bug):

ENGINE_get_first, ENGINE_get_last, ENGINE_get_next, ENGINE_get_prev: https://github.com/openssl/openssl/blob/05faa4ffee7f20fcee129f77d153f2dcc609bdc8/crypto/engine/eng_list.c#L247

**Comment by nhorman** [comment]
So, in an effort to understand what request this issue is making, I read this as:

1) The example in openssl/doc/man3/CRYPTO_THREAD_run_once.pod could be improved - i.e. if a lock fails, we shouldn't provide an example that indicates you still need to unlock the lock, as it failed to lock in the first place
2) You would like to see the call in ossl_engine_table_select be modified such that a failed lock call does not then unlock the mutex at the end label of that function
3) There is a current real bug in eng_list.c, in which a successful write lock, followed by a failed up_ref count in  ENGINE_get_first results in the global_engine_lock remaining locked on exit, resulting in potential deadlock.

Is that a complete current enumeration?

**Comment by nhorman** [comment]
No response, but i'm assuming the above rephrasing is an accurate statement of the issue here.  Marking as a community issue

**Comment by cchinchole** [comment]
I'll investigate and see if I can get to a solution. I see this as 3 tasks to tackle and could make a PR for the first 2, then another separately for the third.

**Comment by nhorman** [comment]
thank you @cchinchole , I'll assign this to you, please add links to the PRs here as you create them

**Comment by cchinchole** [comment]
Opened a PR against the first 2 issues presented here:
https://github.com/openssl/openssl/pull/24779

**Comment by cchinchole** [comment]
https://github.com/openssl/openssl/pull/24780

Opened a PR against the third issue.

**Comment by nhorman** [comment]
looks like we have merged pull requests for all the enumerated issues.  marking as closed
