### ISSUE TITLE
OpenSSL 3.x.How to enable legacy algorithm support?

### ISSUE THREAD

**Issue by qwe857359351a** [openssl/openssl#24512]
Sorry,I know this is a discussion.
But I didn't receive a response, so I turned it into an issue.
OpenSSL compile as static library, I tried loading the old provider.No error is reported, but the old algorithm is still not supported.
```
OSSL_PROVIDER_load(NULL, "legacy");
OSSL_PROVIDER_load(NULL, "default");
```
### Discussed in https://github.com/openssl/openssl/discussions/24506

<div type='discussions-op-text'>

<sup>Originally posted by **qwe857359351a** May 27, 2024</sup>
The system is written in C++,the OpenSSL library is now upgraded to version 3.x.
In order to ensure that the project can be upgraded smoothly, functional testing is performed.
The parsing failed when calling the **PKCS12_parse** function. After debugging, it was found that some PKCS12 data used an old encryption algorithm, which is no longer supported by default. However, the data has been distributed and cannot be directly replaced. How should this be handled in the code?</div>

**Comment by FdaSilvaYY** [comment]
SHA1 enabling also depends on security level, AFAIK.
Look for SECLEVEL too in documentation

**Comment by t8m** [comment]
Closing in favor of the discussion.

**Comment by t8m** [comment]
Please do not open duplicate issues.
