### ISSUE TITLE
Enablement of certificate_authorities TLS extension via openssl.cnf not working

### ISSUE THREAD

**Issue by martinschmatz** [openssl/openssl#24516]
__Intro__
OpenSSL has support to add `certificate_authorities` as TLS extension in TLS `ClientHello`. See [here](https://github.com/openssl/openssl/blob/434e7f7cb4259f8c8c1463fd38fe723b3efca887/doc/man3/SSL_CONF_cmd.pod?plain=1#L338) (and [here](https://github.com/openssl/openssl/blob/434e7f7cb4259f8c8c1463fd38fe723b3efca887/doc/man1/openssl-s_client.pod.in#L353)). This is relevant for a client to have a means to indicate to the server which CAs it would support.

__Issue__
However, when adding `requestCAFile = <path/to/ca-cert-file-selection/pem-format>` to `openssl.cnf` in the relevant `ssl_conf` sesction (see below), no such extension is sent in the `ClientHello`. This can easily be verified by monitoring a the content of the `ClientHello` with e.g. `WireShark`.

The reason is believed to be caused by [this](https://github.com/openssl/openssl/blob/434e7f7cb4259f8c8c1463fd38fe723b3efca887/ssl/ssl_conf.c#L768) line which seemingly is not parsed as intended during an OpenSSL context configuration.

__Remediation__
When inserting a single line with `SSL_CONF_CMD_STRING(RequestCAFile, "requestcafile", 0),` right below [this line](https://github.com/openssl/openssl/blob/434e7f7cb4259f8c8c1463fd38fe723b3efca887/ssl/ssl_conf.c#L748), the `certificate_authorities` extension is created in the `ClientHello` as expected, obviously only when also adding a `requestCAFile = <path/to/ca-cert-file>` line to `openssl.cnf` (IOW, it is not created when no such line is in `openssl.cnf`). 

It is further suggested to check for client or server mode flags [here](https://github.com/openssl/openssl/blob/434e7f7cb4259f8c8c1463fd38fe723b3efca887/ssl/ssl_conf.c#L560). Not 100% sure whether this is required or has a benefit.

__Additional info__
Remediation checked with OpenSSL v3.3.0 (commit 4cb31128b5790819dfeea2739fbde265f71a10a2), via s_client and cURL as client applications.
For completeness, example excerpt of `openssl.cnf':
```
ssl_conf = ssl_module

[ ssl_module ]
system_default = tls_system_default

[ tls_system_default ]
TLS.MinProtocol = TLSv1.2
TLS.MaxProtocol = TLSv1.3
DTLS.MinProtocol = DTLSv1.2
DTLS.MaxProtocol = DTLSv1.2
Groups = secp521r1:secp384r1:X25519:prime256v1:X448
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
CipherString = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
requestCAFile = /etc/pki/tls/certs/ca-bundle.crt
```

**Comment by martinschmatz** [comment]
I would argue that adding `certificate_authorities` to a `ClientHello` has nothing to do with certificate _configuration_ options. From my perspective, it's in the same class as specifying Sigalgs, Groups, or Ciphers via the `openssl.cnf' file.

**Comment by t8m** [comment]
No, IMO it is something that is closely related to individual application settings. There could be different acceptable CAs for an application connecting to some private internal server and different for public internet web access.

The intent for the `system_default` configuration is for _system-wide policy settings_ such as minimal protocol versions, minimal security level, etc.

**Comment by martinschmatz** [comment]
I understand your point. 

My motivation was two-fold (sequence is [strong] priority): 
1) Enable the likes of cURL _without the need to change application code_, where per request control can readily be achieved by using `$ENV::currentValue` in `openssl.cnf`. Absence of the ENV variable automatically results in not generating/sending the extension, at which point it "hurts" nobody else. 
2) Have a means to simplify experiments with "fake" root certs added to the `certificate_authorities` extension. The term "fake" in this context means "pack information about trust stores" in the `certificate_authorities` extension by using carefully tailor made values for CN etc. This to find out whether a new extension `trust_expressions` is really required in the context of [this](https://github.com/davidben/tls-trust-expressions/issues/19) discussion. 

Given the former, I still think enabling control over the `certificate_authorities` extension via `openssl.cnf` makes sense. 
For the latter, I have my own build which I can use. And others can see above how to enable the feature. 

Somewhat related to this (don't know whether I should start a fresh issue): The client can at least indicate to the server which root cert _type_ it would support via the `signature_algorithms` and `signature_algorithms_cert` extensions. 
The TLSv1.3 standard ([RFC8446 in section 4.2.3](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.3)) states that
```
If no "signature_algorithms_cert" extension is present, 
then the "signature_algorithms" extension also applies 
to signatures appearing in certificates.
```
Given that generating `signature_algorithms_cert` extension [is not supported](https://github.com/openssl/openssl/blob/90e7c12f1b238ed714786fafc26d05b59a63752b/ssl/statem/extensions.c#L303), I made an experiment specifying exactly one entry in the `signature_algorithms` extension, but had to notice that the cert-chain - which had certs with different algs - was successfully verified. This seems to indicate deviation from the standard ?!? 
Specifically, I used the OQS provider, specified `dilithium5` as the one-and-only signature algorithm, and issued a cURL request against https://test.openquantumsafe.org:6156/. Result: Verification succeeded against the OQS interop server [root cert](https://test.openquantumsafe.org/CA.crt) (RSA4k). 
Same successful verification when limiting to ECDSA sigalgs against an RSA root cert.

**Comment by martinschmatz** [comment]
OK, understood. As I have what I need, I'm closing this issue for good house-keeping.

While I perfectly understand that specifying the expected sigalgs for cert-chains in the `ClientHello` is not necessarily sufficient to make the best choice for a purely Q-safe cert chain, it nevertheless would be a easy first step in that direction. It would therefore have been appreciated if OpenSSL would adhere to this aspect of the standard.

**Comment by t8m** [comment]
> Given that generating `signature_algorithms_cert` extension [is not supported](https://github.com/openssl/openssl/blob/90e7c12f1b238ed714786fafc26d05b59a63752b/ssl/statem/extensions.c#L303), I made an experiment specifying exactly one entry in the `signature_algorithms` extension, but had to notice that the cert-chain - which had certs with different algs - was successfully verified. This seems to indicate deviation from the standard ?!?

This is a separate issue - AFAIK we currently do not validate the signature algorithm in certs against the sigalgs. @mattcaswell might want to confirm this. It would be a valid feature request.

**Comment by t8m** [comment]
It is already filled as https://github.com/openssl/openssl/issues/11438
