### ISSUE TITLE
Support for UTF-16/32 encoded buffer in ASN1_get_object

### ISSUE THREAD

**Issue by pruthig** [openssl/openssl#24554]
Hi Team,
I am using the API ```ASN1_get_object``` to parse my ASN.1 buffer that contains a sequence of two strings. First string is of type UTF-8 and another one is of type UniversalString . The second string, which is of UniversalString type, has UTF-16 encoded characters.  While parsing the ASN.1 buffer, I am able to retrieve the value of first string successfully, but I am getting the empty ("") value of the second string. Following is the signature of the API I am using -
```ASN1_get_object(const unsigned char **ber_in, long *plength, int *ptag, int *pclass, long omax); ```
As we can see, first argument of this API is a buffer of type ```unsigned char``` that cannot hold wide-characters. Can we add support for UTF-16/32 by enhancing the current implementation and have equivalent APIs for ```char16_t``` and ```char32_t``` buffer types to store wide-character strings?

**Comment by FdaSilvaYY** [comment]
A good resource about Unicode, UTF-8 and co : 

https://tonsky.me/blog/unicode/

Derived from an old article, I read 20 years ago
