### ISSUE TITLE
In OpenSSL 3, ASN1_item_verify*() can return 2 on error.

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#24575]
Introduced in https://github.com/openssl/openssl/pull/10942  as part of extracting `ASN1_item_verify_ctx()` from `ASN1_item_verify()` when a `ret = -1;` was deleted after the `goto err` here:

https://github.com/openssl/openssl/blob/5bbdbce856c7ca132e039a24a315618484874c81/crypto/asn1/a_verify.c#L143-L154

If `item_verify()` returns `2` (which it usually will for RSA-PSS for example) the control flow would skip here and return 2 if `ASN1_item_i2d()` errors:

https://github.com/openssl/openssl/blob/5bbdbce856c7ca132e039a24a315618484874c81/crypto/asn1/a_verify.c#L202-L210

**Comment by t8m** [comment]
Fix in #24576
