### ISSUE TITLE
(Premium contract) OpenSSL 1.1.1y version string needs to be fixed

### ISSUE THREAD

**Issue by visweshn92** [openssl/openssl#24578]
For all users with premium contracts, the versioning has an issue with the recent release of `OpenSSL_1_1_1y`
$ openssl version
OpenSSL 1.1.1y-dev  xx XXX xxxx

Looking at `include/openssl/opensslv.h`, the following line edit was missed during release
># define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1y-dev  xx XXX xxxx"

**Comment by nhorman** [comment]
thank you for your report, we're already aware of the problem and are planning to issue a fix, pending a few additional fixes we would like to wait for.  if you are in a hurry, you can fix this in the field by changing the line in opensslv.h:
# define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1y-dev  xx XXX xxxx"
+# define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1y  04 JUN 2024"

**Comment by t8m** [comment]
Please report issues with premium releases through the premium support channels. Do not use the public github openssl repository.
