### ISSUE TITLE
[rt.openssl.org #4139] bug: lacking OPENSSL_load_builtin_modules() docs 

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2460]
Migrated from [rt.openssl.org#4139](https://rt.openssl.org/Ticket/Display.html?id=4139) (status was 'new')

Requestors:
* daniel@haxx.se

From daniel@haxx.se on 2015-11-13 16:19:03:
```
Hey

The man page for the function OPENSSL_load_builtin_modules() doesn't include 
any details on how the memory it allocates is supposed to get freed by a user.

I assume CONF_modules_free() is the funtion to use for this purpose?

-- 

  / daniel.haxx.se

_______________________________________________
openssl-bugs-mod mailing list
openssl-bugs-mod@openssl.org
https://mta.openssl.org/mailman/listinfo/openssl-bugs-mod
```

**Comment by richsalz** [comment]
ping @mattcaswell

**Comment by levitte** [comment]
That is for 1.0.2.  With 1.1.1, it's cleaned up automagically (or with OPENSSL_cleanup).  So it seems to me like this is missing docs in 1.0.2 and doesn't have much to do with 1.1.1.

**Comment by richsalz** [comment]
I think we should close this as WONTFIX.
