### ISSUE TITLE
x509 -certopt ca_default documentation mismatch

### ISSUE THREAD

**Issue by ttanner** [openssl/openssl#247]
According to the manpage "-textopt ca_default" suppresses the signature:

       ca_default
           the value used by the ca utility, equivalent to no_issuer, no_pubkey, no_header, no_version, no_sigdump and no_signame.

but  "openssl x509 -noout -in file.pem -text -certopt ca_default" shows both  Signature Algorithm and the dump. Only if no_signame,no_sigdump are added, they are suppressed.

**Comment by mattcaswell** [comment]
Congratulations - you found a 15 year old documentation bug! Fixed now. :-)
