### ISSUE TITLE
[rt.openssl.org #4249] ECDSA method flags

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2471]
Migrated from [rt.openssl.org#4249](https://rt.openssl.org/Ticket/Display.html?id=4249) (status was 'new')

Requestors:
* openssl@roumenpetrov.info

Attachments:
* [0003-move-some-ECDSA_METHOD-declarations-after-descriptio.patch](https://rt.openssl.org/Ticket/Attachment/59740/36541/0003-move-some-ECDSA_METHOD-declarations-after-descriptio.patch)
* [0004-public-flag-ECDSA_FLAG_FIPS_METHOD.patch](https://rt.openssl.org/Ticket/Attachment/59740/36542/0004-public-flag-ECDSA_FLAG_FIPS_METHOD.patch)
* [0005-remove-unused-flag-EC_FLAG_FIPS_CHECKED.patch](https://rt.openssl.org/Ticket/Attachment/59740/36543/0005-remove-unused-flag-EC_FLAG_FIPS_CHECKED.patch)

From openssl@roumenpetrov.info on 2016-01-16 15:37:39:
```
In 1.0.2 branch commit 94c2f77a62be7079ab1893ab14b18a30157c4532 add 
functions to set ECDSA_METHOD structure.
One on functions is to set flags. Until now ECDSA flags are defined only 
in non-installed header.


1) "0003-move-some-ECDSA_METHOD-declarations-after-descriptio.patch"
First patch is cosmetic correction of above mentioned commit - move some 
declarations after description.

2) "0004-public-flag-ECDSA_FLAG_FIPS_METHOD.patch"
Actual patch that moves ECDSA flags to public header.

3) "0005-remove-unused-flag-EC_FLAG_FIPS_CHECKED.patch"

OpenSSL describes flag EC_FLAG_FIPS_CHECKED but this flags is not used 
in fips enabled openssl build. It seems to me is enough to set flag 
ECDSA_FLAG_FIPS_METHOD to allow ECDSA method to work in fips mode.


Regards,
Roumen Petrov


```

**Comment by mattcaswell** [comment]
These patches are too old. Please reopen as a PR if still relevant.
