### ISSUE TITLE
Base 64 decoding truncation

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#24728]
Decoding multi-line Base64 data longer than 1024 bytes from a memory buffer created with BIO_new(BIO_s_mem()) may result in the truncation of the decoded data. No error is reported that could alert the application about this data truncation.

Memory BIO created with BIO_new(BIO_s_mem()) is affected, while memory BIO created with BIO_new_mem_buf() is not affected. No other BIO types were tested.

All tested versions of OpenSSL were found to be affected, including 0.9.7m, all stable branches, and the current GitHub master branch.
```[tasklist]
### Tasks
```

**Comment by t8m** [comment]
The linked PR was merged. Closing.
