### ISSUE TITLE
add default cases to switch statements

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#24751]
recent updates in the alpine container deployed clang-18

clang-18 enables checks for -Wswitch-default (which was previously ignored), causing lots of build failures for openssl, as we have lots of switch statements without default cases.

currently other build environments use older clangs, so its not a problem there (yet), but it will be.

This issue tracks the identification and addition of default cases for all our switch statements

**Comment by nhorman** [comment]
OTC: The number of switch statements we have without default cases is large, so this is potentially a significant undertaking, and it has been suggested that it may be better to simply remove the warning option from the --strict-warnings set.  Should we just disable the warning, or go about fixing all the missing default cases?

**Comment by nhorman** [comment]
For reference there are 351 switch statements in openssl missing a default case:

```
awk -v myfile=$1 'BEGIN {depth=0;inswitch=0;founddefault=0}
     /.*switch.*/ {inswitch=1;}
     /{/ {if (inswitch==1) { depth=depth+1;}}
     /}/ {if (inswitch==1) {
                                depth=depth-1;
                                if (depth==0) {
                                    inswitch=0;
                                    if (founddefault==0) {
                                        print "Missing default case on line " NR  " of " myfile;
                                    }
                                    founddefault=0;
                                }
                           }
         }
     /default:/ {if (inswitch==1) {founddefault=1}}' $1

```

```
for i in `find . -name '*.c'`
do
   ./find-missing-defaults.sh $i
done | wc -l
351
```

**Comment by beldmit** [comment]
> I believe the warning is only marginally useful but I would not be against making the code free of this warning. However such change should be done only on the master branch and it will require non-trivial effort

I concur

**Comment by paulidale** [comment]
A missing default is perfectly well defined in C and always has been.  This warning is idiotic.

Nonetheless, people will compile with it and report it as a problem.  It's probably easier to add `default: break` to all such switch statements.  The above awk script could easily be modified to do this I suspect and any false "fixes" quickly manually corrected.

**Comment by paulidale** [comment]
There are fourteen `.h` and two `.inc` files that also match.  Plus three false positives on the `.h` files.

**Comment by paulidale** [comment]
I've done the required changes in #24756.

**Comment by paulidale** [comment]
@nhorman, if you drop the hold here, I'll drop it on the PR.  So far four OTC members have commented in favour and none against.

**Comment by nhorman** [comment]
@paulidale I appreciate the offer, but I wouldn't feel right about it.  By my count 3 OTC members have voiced opinions here, and my read says that both @t8m @beldmit seem to be in favor of just dropping the warning (though I would be in favor of fixing the default cases, not that I'm an OTC member).  I think it would be fair to wait until we can discuss it tuesday, and, if there is consensus, we can just take your patch (though I think theres some indentation issues from the awk script that need fixing)

**Comment by paulidale** [comment]
No problem.

I didn't notice indentation issues but it was a fairly quick scan over the diffs.  Since I took the spaces from the switch, it's possible that indentation problems stem from incorrect indentation of the case labels.  I'm pretty sure I've seen such.

**Comment by paulidale** [comment]
Oops, forgot.  Issue of process: only OTC members can apply an OTC hold.

**Comment by nhorman** [comment]
I might be misreading the diff re: indentation as well, its late here.  We'll get this sorted and put to bed at the next OTC

**Comment by paulidale** [comment]
I've done a pass over the changes.  There were two instances of bad indentation, which I've fixed.  More where I've fixed the errant existing indentation.  I also cleaned things up by adding `break` before the default label where there wasn't one (to avoid `fall through` whinges`).

**Comment by t8m** [comment]
**OTC: As the warning flag was explicitly added to the Clang strict warning list, it is better to just remove it there.**
