### ISSUE TITLE
-Werror missing from many unit tests

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#24757]
We built a lot of our unit tests with `--strict-warnings` but few also include `-Werror` or `-Wall`.
We should add the latter two options where ever possible.

**Comment by t8m** [comment]
> We built a lot of our unit tests with `--strict-warnings` but few also include `-Werror` or `-Wall`. We should add the latter two options where ever possible.

Can you please elaborate? As `--strict-warnings` includes `-Werror -Wall` + some exceptions for warnings that we do not consider useful or too pervasive to fix, what would be the difference?

**Comment by paulidale** [comment]
I didn't think it did.  Closing this.
