### ISSUE TITLE
OpenSSL 3.0.13 can't decrypt file encrypted with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by AussieScorpio** [openssl/openssl#24772]
I have backups that were encrypted with OpenSSL 1.1.1 by piping to;
    ```
openssl enc -e -aes-256-cbc -salt -pass file:${DIR}/key.bin
    ```

I can decrypt the resulting file with OpenSSL 1.1.1 using;
    ```
openssl enc -d -aes-256-cbc -salt -in $DIR/$BACKUP_FILE.sql.dat -out $DIR/$BACKUP_FILE.sql -pass file:$DIR/key.bin
    ```

Using the same with OpenSSL 3.0.13 results in;
    ```
bad decrypt
408742C9B87C0000:error:1C80006B:Provider routines:ossl_cipher_generic_block_final:wrong final block length:../providers/implementations/ciphers/ciphercommon.c:443:
    ```

I've tried specifying the -md as md5 and sha256, as the issue is reminiscent of the issues last time the default hashing algorithm changed. Neither of these options has made any difference.

I can't stress strongly enough; OpenSSL MUST be backwards compatible. It's simply not good enough to have a DR situation where a new server is built that has a different version of OpenSSL and backups cannot be restored. Whilst it's possible to uninstall OpenSSL and then install the same version used for backups, this burns time and leads to excessive downtime. It seems that this has been an issue every time we build a new server; our old backups become worthless. Fortunately this has not occurred during a DR operation, so we haven't had the downtime hit. We have however lost of a lot of man hours to it.

**Comment by t8m** [comment]
@AussieScorpio Unfortunately I cannot reproduce this. If I encrypt with 1.1.1 with your command I can normally decrypt with the 3.0.13 version and the decrypted file is the original plaintext.

**Comment by t8m** [comment]
There was one known breakage for the enc command that is documented in the manual page but that affects the `-S` option only. Otherwise the command should be fully compatible between 1.1.1 and 3.x.

**Comment by AussieScorpio** [comment]
Ok, finally got to the bottom of it. I'm piping from AWS | OpenSSL | MySQL. I tried removing parts of this one at a time and found even with the simplest case of CATing a file into AWS and downloading from AWS, piping to md5sum, I was getting different hashes. It turned out that because AWS is running in Docker and my docker exec call had the flags -it instead of just -i, the stdout data was being changed. In simple cases like "Hello World", this wasn't even noticeable to the eye, but hashing or outputting as Hex showed it. So, in short Docker was causing changed data to go to stdout which was then consumed by OpenSSL resulting in the issue. Thanks for taking the time to respond to my post, and BEWARE THE -t FLAG IN DOCKER WHEN PIPING..!
