### ISSUE TITLE
X509_sign fails when building with address sanitizer on FreeBSD

### ISSUE THREAD

**Issue by Aragormy** [openssl/openssl#24793]
I have a problem with the function `int ret = X509_sign(cert.get(), pkey.get(), EVP_sha256()); ` when using address sanitizer specifically on FreeBSD. 

I'm building the code using: 
`clang++ -Wall -std=c++11 -g -fsanitize=address -fno-omit-frame-pointer  main.cpp -lcrypto -o main`  
or 
`clang++ -Wall -std=c++11 -g main.cpp -lcrypto -o main`. 

If tested the code on the following systems:
 Ubuntu 22.04.4 LTS - OpenSSL 3.0.2 15 Mar 2022
   -> building without address sanitizer: WORKS
   -> building with address sanitizer: WORKS
 
 FreeBSD 14.0-RELEASE - OpenSSL 3.0.12 24 Oct 2023
   -> building without address sanitizer: WORKS
   -> building with address sanitizer: building works but execution fails on given line

ONLY on FreeBSD with address sanitizer the code fail on execution. 
Note: I am not getting any output from the address sanitizer, it seems like X509_sign is just failing.  

Does anyone have any ideas for possible solutions?

Here is my code (just a sample method for creating/signing a certificate).

```
#include <memory>
#include <string>
#include <openssl/x509.h>
#include <openssl/rsa.h>
#include <openssl/evp.h>

#define RSA_KEY_LENGTH 2048

int main(int argc, char* argv[])
{    
    std::string certFileName = "MyTestCert";
    std::string keyFileName = "MyKeyFile";
    long daysValid = 31;

    std::unique_ptr<BIO, void (*)(BIO *)> certFile  { BIO_new_file(certFileName.data(), "wb"), BIO_free_all  };
    std::unique_ptr<BIO, void (*)(BIO *)> keyFile { BIO_new_file(keyFileName.data(), "wb"), BIO_free_all };

    if (certFile && keyFile)
    {
        std::unique_ptr<RSA, void (*)(RSA *)> rsa { RSA_new(), RSA_free };
        std::unique_ptr<BIGNUM, void (*)(BIGNUM *)> bn { BN_new(), BN_free };

        BN_set_word(bn.get(), RSA_F4);
        int rsa_ok = RSA_generate_key_ex(rsa.get(), RSA_KEY_LENGTH, bn.get(), nullptr);

        if (rsa_ok == 1)
        {
            // --- cert generation ---
            std::unique_ptr<X509, void (*)(X509 *)> cert { X509_new(), X509_free };
            std::unique_ptr<EVP_PKEY, void (*)(EVP_PKEY *)> pkey { EVP_PKEY_new(), EVP_PKEY_free};

            // The RSA structure will be automatically freed when the EVP_PKEY structure is freed.
            EVP_PKEY_assign(pkey.get(), EVP_PKEY_RSA, reinterpret_cast<char*>(rsa.release()));
            ASN1_INTEGER_set(X509_get_serialNumber(cert.get()), 1); // serial number

            X509_gmtime_adj(X509_get_notBefore(cert.get()), 0); // now
            X509_gmtime_adj(X509_get_notAfter(cert.get()), daysValid * 24 * 3600); // accepts secs

            X509_set_pubkey(cert.get(), pkey.get());

            // 1 -- X509_NAME may disambig with wincrypt.h
            // 2 -- DO NO FREE the name internal pointer
            X509_name_st* name = X509_get_subject_name(cert.get());

            const unsigned char country[] = "RU";
            const unsigned char company[] = "MyCompany, PLC";
            const unsigned char common_name[] = "localhost";

            X509_NAME_add_entry_by_txt(name, "C",  MBSTRING_ASC, country, -1, -1, 0);
            X509_NAME_add_entry_by_txt(name, "O",  MBSTRING_ASC, company, -1, -1, 0);
            X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, common_name, -1, -1, 0);

            X509_set_issuer_name(cert.get(), name);
            int ret = X509_sign(cert.get(), pkey.get(), EVP_sha256()); // some hash type here
            if(!ret)
            {
                printf("Error!!!\n");
            }
        }
    }

    return 0;
}
```

**Comment by nhorman** [comment]
a few notes:
1) The above test case doesn't compile without the addition of several header files:
#include <memory>
#include <string>
#include <openssl/x509.h>
#include <openssl/rsa.h>
#include <openssl/evp.h>

2) I don't have a freebsd system setup at the moment, can you post the tsan output that you get when running here please?

**Comment by cryptechsurpport** [comment]
I started trading Crypto on Binary options, at first everything was going smoothly till I tried withdrawing. I was made to believe that I had to build my account to a certain point before withdrawing, I had lost total sum of 10.000btc. After weeks of turmoil and sadness that investment brought me and my family. I saw recommendations to 
P E R F E C T R E C L A I M R E C O V E R I N G O N   I N S T A and i was lucky they helped me recover all of my funds without any hassle in less than 48 hours, I am so happy doing this because I know how many people would benefit from this useful information. Fortunately for me I was able to recover all i lost P E R F E C T R E C L A I M RECOVERY CONSULTANT is a real refund professional feel free to reach out to them for quick response if you’re having similar issues

**Comment by cryptechsurpport** [comment]
I started trading Crypto on Binary options, at first everything was going smoothly till I tried withdrawing. I was made to believe that I had to build my account to a certain point before withdrawing, I had lost total sum of 10.000btc. After weeks of turmoil and sadness that investment brought me and my family. I saw recommendations to 
P E R F E C T R E C L A I M R E C O V E R I N G O N   I N S T A and i was lucky they helped me recover all of my funds without any hassle in less than 48 hours, I am so happy doing this because I know how many people would benefit from this useful information. Fortunately for me I was able to recover all i lost P E R F E C T R E C L A I M RECOVERY CONSULTANT is a real refund professional feel free to reach out to them for quick response if you’re having similar issues

**Comment by cryptechsurpport** [comment]
I started trading Crypto on Binary options, at first everything was going smoothly till I tried withdrawing. I was made to believe that I had to build my account to a certain point before withdrawing, I had lost total sum of 10.000btc. After weeks of turmoil and sadness that investment brought me and my family. I saw recommendations to 
P E R F E C T R E C L A I M R E C O V E R I N G O N   I N S T A and i was lucky they helped me recover all of my funds without any hassle in less than 48 hours, I am so happy doing this because I know how many people would benefit from this useful information. Fortunately for me I was able to recover all i lost P E R F E C T R E C L A I M RECOVERY CONSULTANT is a real refund professional feel free to reach out to them for quick response if you’re having similar issues

**Comment by Aragormy** [comment]
> 1\. The above test case doesn't compile without the addition of several header files:
>        #include 
>        #include 
>        #include <openssl/x509.h>
>        #include <openssl/rsa.h>
>        #include <openssl/evp.h>

Oh sorry, i have updated the code above

> 2\. I don't have a freebsd system setup at the moment, can you post the tsan output that you get when running here please?

I get no tsan output at all. Neither when executing `./main` nor from `TSAN_OPTIONS="verbosity=2+" ./main` 
I compiled using "clang++ -Wall -std=c++11 -g -fsanitize=address -fno-omit-frame-pointer  main.cpp -lcrypto -o main".

**Comment by tom-cosgrove-arm** [comment]
> building with address sanitizer: FAILS

Could you post the full commands you are running and the full output please?

**Comment by Aragormy** [comment]
> > building with address sanitizer: FAILS
> 
> Could you post the full commands you are running and the full output please?

If updated my original message and added the used build comments. 

Here the full build output:
```
main.cpp:23:53: warning: 'RSA_new' is deprecated [-Wdeprecated-declarations]
        std::unique_ptr<RSA, void (*)(RSA *)> rsa { RSA_new(), RSA_free };
                                                    ^
/usr/include/openssl/rsa.h:201:1: note: 'RSA_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 RSA *RSA_new(void);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
main.cpp:23:64: warning: 'RSA_free' is deprecated [-Wdeprecated-declarations]
        std::unique_ptr<RSA, void (*)(RSA *)> rsa { RSA_new(), RSA_free };
                                                               ^
/usr/include/openssl/rsa.h:293:1: note: 'RSA_free' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
main.cpp:27:22: warning: 'RSA_generate_key_ex' is deprecated [-Wdeprecated-declarations]
        int rsa_ok = RSA_generate_key_ex(rsa.get(), RSA_KEY_LENGTH, bn.get(), nullptr);
                     ^
/usr/include/openssl/rsa.h:260:1: note: 'RSA_generate_key_ex' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int RSA_generate_key_ex(RSA *rsa, int bits, BIGNUM *e,
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
main.cpp:36:13: warning: 'EVP_PKEY_assign' is deprecated [-Wdeprecated-declarations]
            EVP_PKEY_assign(pkey.get(), EVP_PKEY_RSA, reinterpret_cast<char*>(rsa.release()));
            ^
/usr/include/openssl/evp.h:1329:1: note: 'EVP_PKEY_assign' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
4 warnings generated.
```

On execution i don't get any output, other than my "Error!!!" debug print when executing the code under bsd (with asan)

**Comment by tom-cosgrove-arm** [comment]
> If updated my original message and added the used build comments.

How did you configure OpenSSL?

**Comment by Aragormy** [comment]
> How did you configure OpenSSL?

I'm using the default configuration as deployed by bsd. 
Which file is from relevance here? /etc/ssl/openssl.cnf?

**Comment by tom-cosgrove-arm** [comment]
> I'm using the default configuration as deployed by bsd.

Ah, sorry, it's the system OpenSSL - I'd missed that.

If you run `openssl version -f` you should get most of the options that it was built with

**Comment by Aragormy** [comment]
> If you run `openssl version -f` you should get most of the options that it was built with

`openssl version -f` returns `compiler: clang`

here the output from `openssl version -a`: 

```
OpenSSL 3.0.12 24 Oct 2023 (Library: OpenSSL 3.0.12 24 Oct 2023)
built on: reproducible build, date unspecified
platform: FreeBSD-amd64
options:  bn(64,64)
compiler: clang
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib/engines-3"
MODULESDIR: "/usr/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x5eda2203478bffff:0x842529
```

**Comment by Aragormy** [comment]
Hi everyone,

I wanted to check in and ask if there have been any updates regarding this issue. There hasn't been any activity for some time, and I was wondering if there have been any updates or workarounds.

**Comment by nhorman** [comment]
No, I'm afraid not.  I still don't have a freebsd system setup here, but are you able to step through X509_sign with gdb to see where the function is failing?

**Comment by oschonrock** [comment]
This may be related... 

https://github.com/curl/curl/issues/15477

**Comment by botovq** [comment]
This is the same FreeBSD/NetBSD toolchain bug with SHA-2 interceptors as https://github.com/openssl/openssl/issues/25456, see also https://github.com/llvm/llvm-project/issues/110215. It will be fixed once these BSDs update to LLVM-19.

**Comment by t8m** [comment]
Thank you @botovq
