### ISSUE TITLE
Compling error in x509v3.h when building with powrprof.h header

### ISSUE THREAD

**Issue by fborges22** [openssl/openssl#24813]
Greetings,

I noticed a problem building my program using this OpenSSL 3.0.8 header: x509v3.h. The compiling error occurs in MSVC and these are the errors reported:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\powrprof.h(339,9): error C2365: 'ACCESS_DESCRIPTION': redefinition; previous definition was 'typedef'
D:\myprogram\third_libraries\openssl\3.0.13\win64\include\openssl/x509v3.h(199): note: see declaration of 'ACCESS_DESCRIPTION'
```

I noticed that the typedef ACCESS_DESCRIPTION defined by the x509v3.h header is conflicting with the Windows powrprof.h header that has a typedef containing an enum with the same name as the ACCESS_DESCRIPTION used earlier by the OpenSSL header (x509v3.h).

To reproduce this problem you need to build something in MSVC and use these two headers (powrprof.h and x509v3.h) at the same time.

I would strongly recommend changing the name of the typedef in the x509v3.h to SSL_ACCESS_DESCRIPTION or something that does not conflict with the existing ACCESS_DESCRIPTION typedef used by the Windows header powrprof.h.

Best regards,
F.Borges

**Comment by mattcaswell** [comment]
Hmm. That type name has been part of our public API for 24 years having been first introduced in OpenSSL 0.9.5 in February 2000. Since it forms part of the public API changing it is not really an option (at least not in a minor release) since that would break any application using it.

**Comment by fborges22** [comment]
Interesting. Yes, indeed it would break other applications using this specific typedef. I am currently working on a way to use the Power Profile header of Windows with the X509v3 header.

Could you please suggest some approaches to solve this issue?

**Comment by mattcaswell** [comment]
I've not tried it, but I wonder if you could temporarily rename the type to something else via a macro, e.g.

```` C
#define ACCESS_DESCRIPTION TMP_ACCESS_DESCRIPTION
#include <openssl/x509v3.h>
#undef ACCESS_DESCRIPTION
#include <powrprof.h>
````

**Comment by fborges22** [comment]
In my particular case, I do need to include both x509v3 and powerprof headers.

**Comment by t8m** [comment]
> In my particular case, I do need to include both x509v3 and powerprof headers.

Then the `#define` hack as suggested above should work.

**Comment by tom-cosgrove-arm** [comment]
... and note you can do the `#define` trick either way round, as long as you're not using the Windows enum value `ACCESS_DESCRIPTION` in your code

**Comment by fborges22** [comment]
Okay I fixed successfully using namespace {...}
