### ISSUE TITLE
Certificate name most me changed

### ISSUE THREAD

**Issue by wifi19999** [openssl/openssl#24834]
The OpenSSL "brand" has to be changed to tsl <!--
Thank you for your bug report. If this is your first one,
please take the time to read the following lines before posting it.

NOTE:

    If you're asking about how to use OpenSSL, this isn't the right
    forum.  Please see our User Support resources:
    https://github.com/openssl/openssl/blob/master/SUPPORT.md

Please remember to tell us in what OpenSSL version you found the issue.

For build issues:

    If this is a build issue, please include the configuration output
    as well as a log of all errors.  Don't forget to include the exact
    commands you typed.

**Comment by nhorman** [comment]
@wifi19999 I'm not sure what you are trying to do here, but please stop opening  issues with no content.
