### ISSUE TITLE
Quoting $(MAKE) leads to a build error

### ISSUE THREAD

**Issue by Ray-V** [openssl/openssl#24857]
Re: commit aba621934696ca52193bd41cd35816649b6b321b

Quoting $(MAKE) in Configurations/unix-Makefile.tmpl leads to a build error for 3.0.14
```
"make -j6" depend && "make -j6" _build_libs
/bin/sh: line 1: make -j6: command not found
make: *** [Makefile:3231: build_libs] Error 127
```

What I need to see is
```
make -j6 depend && make -j6 _build_libs
make[1]: Entering directory '/tmp/openssl-3.0.14'
...
```

Reverting to the previous line as in 3.0.13
```
return "$target: build_generated\n\t\$(MAKE) depend && \$(MAKE) _$target\n_$target";
```
enables the build to proceed and complete.

**Comment by t8m** [comment]
The quotes are supposed to be helpful when $MAKE contains a full path and that path contains spaces. Unfortunately that breaks if you use $MAKE to set additional command line arguments. Choose your breakage.

I assume we could add some additional variable ($MAKEARGS for example) which you could use to pass the `-jx` arguments when inner make is being invoked.

**Comment by levitte** [comment]
> I assume we could add some additional variable ($MAKEARGS for example) which you could use to pass the `-jx` arguments when inner make is being invoked.

That's quite a convoluted idea.  So basically, we'd tell people *"No, don't use 'make -j8', use 'make MAKEARGS=-j8' instead"*?

**Comment by nhorman** [comment]
generally speaking, $(MAKE) is a "magic" variable that takes on the name of the full path of the invoking call.  i.e. if you call /usr/bin/make then $(MAKE) is /usr/bin/make.  As such, shouldn't users of make just be calling make (ensuring that make is in their path), obviating the need to do any quoting?

**Comment by levitte** [comment]
From a purely POSIX perspective, whatever flags were passed in the `make` invocation should end up in the macro `MAKEFLAGS`, and the macro `MAKE` should only contain the full path of the `make` program itself.  Sub-makes should get `MAKEFLAGS` passed to them via the environment.

Strictly speaking, you *can* do what @t8m suggested with any POSIX compliant `make`, by using `MAKEFLAGS` like this:

``` console
$ make MAKEFLAGS=-j6
```

or:

``` console
$ MAKEFLAGS=-j6 make
```

This shouldn't be necessary, though...

@nhorman said thusly:
> ... obviating the need to do any quoting?

Well, er, no.  If `$(MAKE)` is supposed to always be the full path of the program, and the path contains spaces (someone installed their own build of GNU make in, I dunno, something like `/Users/John Doe/.local/bin`?), then the quotes are needed.  Same if system installations are in paths that contain spaces...

**Comment by t8m** [comment]
Ah then it really does not make any sense to have `MAKE="make -j6"`. Closing as notabug.

**Comment by levitte** [comment]
Hmmm, it's possible that "full path" was wishful reading on my part...  But it still comes to the same with your example, if someone does `"/Users/John Doe/.local/bin/make"`, and either way, the command flags shouldn't appear in `$(MAKE)`
