### ISSUE TITLE
[rt.openssl.org #4477] [PATCH] enc command enhancement and small fixes

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2486]
Migrated from [rt.openssl.org#4477](https://rt.openssl.org/Ticket/Display.html?id=4477) (status was 'new')

Requestors:
* michel.sales@free.fr

Attachments:
* [enc-fixes_v2-1.1.0.patch](https://rt.openssl.org/Ticket/Attachment/65228/40618/enc-fixes_v2-1.1.0.patch)
* [test_enc.cmds](https://rt.openssl.org/Ticket/Attachment/65228/40619/test_enc.cmds)

From michel.sales@free.fr on 2016-03-24 23:48:24:
```
Hi,



While I was at it (allowing wrap/unwrap mode), I finally decided to remedy
some unnecessary restrictions of the 'enc' command.

The general idea is to allow to decrypt a file using the original passphrase
even when it is not internally salted (hence produced by another software),
in which case the salt must be supplied as an argument (along with the same
iteration count). I also added support for PKCS5 v2.
The previous behavior of the command is not modified.

I didn't work on the AEAD ciphers problem as I know someone else applied for
this job.

Regards,

Michel.
```

**Comment by EasySec** [comment]
This patch was a first attemtp to solve several distincts problems. Some of them may need more discussions (wrap modes). It is too old now and I believe it contains errors. A new thread was launched in #2083. I think it is not worth fixing salt handling as long as PBKDF2 is not implemented however I have an updated patch for that, but it may conflict with a future new 'magic' format.

**Comment by richsalz** [comment]
Okay, closing per @EasySec 's comments.
