### ISSUE TITLE
CMake config broken [master and 3.3]

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#24876]
While fixing pkg-config bugs, it appears that the corresponding CMake config got broken.

From https://github.com/openssl/openssl/pull/24687#issuecomment-2227085012 : 

> Sadly, this seems to have broken the CMake config. Before the patch, we got the following output:
> 
> ```
> # Directories and names
> set(OPENSSL_INCLUDE_DIR "${_ossl_prefix}/include")
> set(OPENSSL_LIBRARY_DIR "${_ossl_prefix}/lib")
> set(OPENSSL_ENGINES_DIR "${_ossl_prefix}/lib/engines-3")
> set(OPENSSL_MODULES_DIR "${_ossl_prefix}/lib/ossl-modules")
> set(OPENSSL_RUNTIME_DIR "${_ossl_prefix}/bin")
> ```
> 
> Now, it only produces
> 
> ```
> # Directories and names
> set(OPENSSL_INCLUDE_DIR "${_ossl_prefix}/")
> set(OPENSSL_LIBRARY_DIR "${_ossl_prefix}/")
> set(OPENSSL_ENGINES_DIR "${_ossl_prefix}/")
> set(OPENSSL_MODULES_DIR "${_ossl_prefix}/")
> set(OPENSSL_RUNTIME_DIR "${_ossl_prefix}/")
> ```
> 
> My limited understanding of the patch is that the variables `LIBDIR_REL`, `INCLUDEDIR_REL`, … are no longer produced?

**Comment by nhorman** [comment]
I've attached a proposed fix

**Comment by levitte** [comment]
dup #24874
