### ISSUE TITLE
REGR: various `OPENSSL_<...>_DIR` variables not set in CMake anymore 

### ISSUE THREAD

**Issue by h-vetinari** [openssl/openssl#24874]
Sadly, this (https://github.com/openssl/openssl/pull/24687) seems to have broken the CMake config. Before the patch, we got the following output:

```
# Directories and names
set(OPENSSL_INCLUDE_DIR "${_ossl_prefix}/include")
set(OPENSSL_LIBRARY_DIR "${_ossl_prefix}/lib")
set(OPENSSL_ENGINES_DIR "${_ossl_prefix}/lib/engines-3")
set(OPENSSL_MODULES_DIR "${_ossl_prefix}/lib/ossl-modules")
set(OPENSSL_RUNTIME_DIR "${_ossl_prefix}/bin")
```

Now, it only produces

```
# Directories and names
set(OPENSSL_INCLUDE_DIR "${_ossl_prefix}/")
set(OPENSSL_LIBRARY_DIR "${_ossl_prefix}/")
set(OPENSSL_ENGINES_DIR "${_ossl_prefix}/")
set(OPENSSL_MODULES_DIR "${_ossl_prefix}/")
set(OPENSSL_RUNTIME_DIR "${_ossl_prefix}/")
```

My limited understanding of the patch is that the variables `LIBDIR_REL`, `INCLUDEDIR_REL`, … are no longer produced?

_Originally posted by @xhochy in https://github.com/openssl/openssl/issues/24687#issuecomment-2227085012_

**Comment by nhorman** [comment]
@h-vetinari can you try the patch in the referenced PR and confirm that it fixes your problem please?

**Comment by xhochy** [comment]
I can confirm that with the linked PR the values look like before.
