### ISSUE TITLE
[rt.openssl.org #4536] Android arm-v8/arm64/aarch64 Support

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2490]
Migrated from [rt.openssl.org#4536](https://rt.openssl.org/Ticket/Display.html?id=4536) (status was 'new')

Requestors:
* ndof@gmx.li

From ndof@gmx.li on 2016-05-05 17:19:36:
```
Hello,
in the Configure file only support for Android arm-v7 are found.
But general arm-v8/arm64/aarch64 are included for the Linux target.

```

**Comment by xsacha** [comment]
The ./Configure script does not deal with Android at all so I assume you mean ./config.
I'd also like to add there is no x86_64 support or mips32/64.

The targets do exist in 10-main.conf but you have to manually specify it.

**Comment by mattcaswell** [comment]
The master branch now properly deals with android. Closing this.

**Comment by mspncp** [comment]
> The master branch now properly deals with android. Closing this.

Addendum: Since the FIPS 2.0 object module has support for Android Arm 64-bit, but it depends on OpenSSL 1.0.2, the `android64-aarch64` target has been retrofitted to 1.0.2 in #8713.
