### ISSUE TITLE
[BUG] Use of strnlen() is not portable

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#24908]
strnlen() in fuzz/provider.c is not portable. Causes build failures on NonStop (at least).

```
      found_len = strnlen((const char *) *buf, *len);
                  ^
"/home/ituglib/randall/openssl-klt/fuzz/provider.c", line 163: error(114):
          identifier "strnlen" is undefined
```

**Comment by nhorman** [comment]
Seems like the most reasonable thing to do would be to create an OPENSSL_strnlen(const char *s, size_t maxlen) function for this and replace the call in the fuzzer.

**Comment by nhorman** [comment]
I can give it a shot here

**Comment by nhorman** [comment]
actually, scratch that, we have an implementation of OPENSSL_strnlen already, just need to switch to using it

**Comment by nhorman** [comment]
PR for you @rsbeckerca should fix your issue

**Comment by rsbeckerca** [comment]
> PR for you @rsbeckerca should fix your issue

Will work on it when I'm back at the office.

**Comment by rsbeckerca** [comment]
> PR for you @rsbeckerca should fix your issue

PR is ready to go.

**Comment by tom-cosgrove-arm** [comment]
Is there a way we can check automatically for use of `strnlen()` (and maybe others?) in new code, so that we don't have to go through this dance everything someone only tests their PR on Linux?

**Comment by levitte** [comment]
> Is there a way we can check automatically for use of `strnlen()` (and maybe others?) in new code, so that we don't have to go through this dance everything someone only tests their PR on Linux?

Yup.  In `.github/workflows/ci.yml`, we have a `-ansi` build that enables POSIX.1-2008 (through the `_POSIX_C_SOURCE` C macro).  A `-ansi` build with an older POSIX version would probbaly put these discrepancies on display.  See https://www.man7.org/linux/man-pages/man7/feature_test_macros.7.html for a set of possible values.

Note: `strnlen()` is specified in POSIX.1-2008, that's why our CIs aren't reacting on this one.

**Comment by levitte** [comment]
Re NonStop, I've lost track of what POSIX version it's supposed to support...  from earlier iterations, it also seems like that support is partial, if I remember correctly.  Is that your recollection too, @rsbeckerca?

**Comment by tom-cosgrove-arm** [comment]
> In `.github/workflows/ci.yml`, we have a -ansi build that enables POSIX.1-2008

Is there some (relatively easy) way we could implement a `banned-apis.list` where we put `strnlen()` along with `sprintf()`? :)

**Comment by levitte** [comment]
How's that easier than making a change to `check-ansi`?

**Comment by nhorman** [comment]
we actually have this check:
https://github.com/openssl/openssl/actions/runs/9960819468/workflow?pr=24912
Which would have caught the new abi addition, it just currently doesn't build the fuzzers, perhaps it should

**Comment by tom-cosgrove-arm** [comment]
> How's that easier than making a change to `check-ansi`?

I interpreted the comment "[NonStop POSIX] support is partial" as meaning there isn't one POSIX level that would catch exactly what NonStop provides. If there is, then clearly that would be easier

**Comment by levitte** [comment]
> > How's that easier than making a change to `check-ansi`?
> 
> I interpreted the comment "[NonStop POSIX] support is partial" as meaning there isn't one POSIX level that would catch exactly what NonStop provides. If there is, then clearly that would be easier

I was hoping that there was a minimum POSIX level that was supported enough for OpenSSL.

**Comment by rsbeckerca** [comment]
In practice, there are POSIX compliance levels but looking at POSIX-1.* in the NonStop context, it does support POSIX from around 2008 with a lot of additions from POSIX-2* seemingly at random (or more specifically what many of us whined about loudly enough). The next OS release may bring some new changes, but we are stuck with having to support OS releases from 5 years back (HPE's general policy on support). I think the fuzz check would be better as things are discovered missing, like `posix_memalign` (not at all), `aligned_alloc` (only c11, which as of today does not generate good thread code - reported).
