### ISSUE TITLE
A0340100:error:8000274C:system library:BIO_connect:Unknown error:crypto\bio\bio_sock2.c:178:calling connect()

### ISSUE THREAD

**Issue by ZJRui** [openssl/openssl#24957]
win11
> openssl version
OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)

# error

 openssl s_client -connect www.google.com:443
A0340100:error:8000274C:system library:BIO_connect:Unknown error:crypto\bio\bio_sock2.c:178:calling connect()
A0340100:error:10000067:BIO routines:BIO_connect:connect error:crypto\bio\bio_sock2.c:180:
connect:errno=0

**Comment by nhorman** [comment]
That looks like a system level error, rather than a library error (i.e. the connect syscall failed for an unknown reason in the os.  Are you able to connect to other ssl enabled locations successfully?

**Comment by nhorman** [comment]
no response, marking as inactive

**Comment by abdi2000** [comment]
I am getting this error - 50610000:error:8000274D:system library:BIO_connect:Unknown error:../openssl-3.2.3/crypto/bio/bio_sock2.c:178:calling connect()
50610000:error:10000067:BIO routines:BIO_connect:connect error:../openssl-3.2.3/crypto/bio/bio_sock2.c:180:
connect:errno=0

I am getting this for any of the server I try to connect.

**Comment by Sashan** [comment]
what is your OS is it windows? any chance there is firewall/antivirus software enabled? if so then you might need to allow openssl application to reach network in firewall/antivirus settings.

The error you see comes from `connect()` syscall so you need to investigate why the syscall fails for openssl application.

**Comment by abdi2000** [comment]
Thanks for reply. The issue was due to an inactive port number of the server in my openssl command. With active and a valid port number it works fine.

**Comment by JeffreyMercado** [comment]
I just wanted to add that this set of errors can occur if the target server is not up and listening to that port. Was having issues verifying a connection with known working certificates. Turned out the server was down.

```
$ openssl s_client -connect [myserverhost]:443 -servername [myservername] -cert [mycert].pem -key [mycertkey].pem -CAfile root-ca.pem
9C900000:error:8000274D:system library:BIO_connect:Unknown error:../openssl-3.5.4/crypto/bio/bio_sock2.c:178:calling connect()
9C900000:error:10000067:BIO routines:BIO_connect:connect error:../openssl-3.5.4/crypto/bio/bio_sock2.c:180:
connect:errno=0
```
