### ISSUE TITLE
ossl_cipher_unpadblock rejecting valid plaintexts by default (3.3.1 Windows MSVC)

### ISSUE THREAD

**Issue by Convery** [openssl/openssl#24967]
As OpenSSL's `EVP` has padding enabled by default, it will naturally call `ossl_cipher_unpadblock` after decrypting. However, `unpadblock` assumes that there will always be a padding block in the stream, and as such the encryption equivalents will add an unnecessary block of padding if the plaintext is divisible by the blocksize. While this workaround works for OpenSSL <-> OpenSSL systems, a lot of other implementations (especially in embedded) will not waste the extra block. 

As noted in the function, it assumes that there have been other checks before it's called. https://github.com/openssl/openssl/blob/aececda752d182f271bf2263f5ef9020a64668c5/providers/implementations/ciphers/ciphercommon_block.c#L102 

So to handle such clients; we'd either need to treat all data as unpadded and remove the padding ourselves, relax `ossl_cipher_unpadblock` so that if it fails to validate the padding; the block is left untouched rather than throwing a `PROV_R_BAD_DECRYPT`, or try calling the padded decrypt by default and then fallback to unpadded on failure.

The latter idea has some inconsistencies between versions and compilers. Where Clang (OpenSSL 1.1.1g) will decrypt all data into the buffer but return 0 for the size, while MSVC (OpenSSL 3.3.1) will not copy any decrypted data before returning 0. While the former may be preferable as one can use the output (ignoring outlen, assuming inlen == plainlen), the better solution would be to not assume/require that there's a padding-block at the end.

Repro: https://godbolt.org/z/nE8oG9P6s
```cpp
#include <array>
#include <cstdio>
#include <cstdint>
#include <cassert>
#include <openssl/evp.h>
#pragma comment(lib, "libssl.lib")
#pragma comment(lib, "libcrypto.lib")

int main() 
{
    constexpr std::array<uint8_t, 16> Key{ 0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c };
    constexpr std::array<uint8_t, 16> IV{ 0x16, 0x15, 0x7e, 0x2b, 0xa6, 0xd2, 0xae, 0x28, 0x88, 0x15, 0xf7, 0xab, 0x3c, 0x4f, 0xcf, 0x09 };
    constexpr std::array<uint8_t, 16> Data{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 64 };
    std::array<uint8_t, 16> Buffer{};

    // Encrypt without padding.
    {
        EVP_CIPHER_CTX *Context = EVP_CIPHER_CTX_new();
        int Encryptionlength = 0;

        EVP_EncryptInit(Context, EVP_aes_128_cbc(), Key.data(), IV.data());
        EVP_CIPHER_CTX_set_padding(Context, 0);

        EVP_EncryptUpdate(Context, Buffer.data(), &Encryptionlength, Data.data(), int(Data.size()));
        printf("ENC len: %u\n", Encryptionlength);

        EVP_EncryptFinal_ex(Context, Buffer.data() + Encryptionlength, &Encryptionlength);
        printf("ENC len: %u\n", Encryptionlength);

        EVP_CIPHER_CTX_free(Context);
    }

    std::array<uint8_t, 16> Decrypted_pad{ Buffer }, Decrypted_nopad{ Buffer };

    // Try to decrypt with padding.
    {
        EVP_CIPHER_CTX *Context = EVP_CIPHER_CTX_new();
        int Decryptionlength = 0;

        EVP_DecryptInit_ex(Context, EVP_aes_128_cbc(), nullptr, Key.data(), IV.data());

        EVP_DecryptUpdate(Context, Decrypted_pad.data(), &Decryptionlength, Decrypted_pad.data(), int(Decrypted_pad.size()));
        printf("DEC_pad len: %u\n", Decryptionlength);

        EVP_DecryptFinal_ex(Context, Decrypted_pad.data() + Decryptionlength, &Decryptionlength);
        printf("DEC_pad len: %u\n", Decryptionlength);

        EVP_CIPHER_CTX_free(Context);
    }

    // Try to decrypt without padding.
    {
        EVP_CIPHER_CTX *Context = EVP_CIPHER_CTX_new();
        int Decryptionlength = 0;

        EVP_DecryptInit_ex(Context, EVP_aes_128_cbc(), nullptr, Key.data(), IV.data());
        EVP_CIPHER_CTX_set_padding(Context, 0);

        EVP_DecryptUpdate(Context, Decrypted_nopad.data(), &Decryptionlength, Decrypted_nopad.data(), int(Decrypted_nopad.size()));
        printf("DEC_nopad len: %u\n", Decryptionlength);

        EVP_DecryptFinal_ex(Context, Decrypted_nopad.data() + Decryptionlength, &Decryptionlength);
        printf("DEC_nopad len: %u\n", Decryptionlength);

        EVP_CIPHER_CTX_free(Context);
    }

    printf("Original : %02X %02X %02X %02X %02X\n", Data[0], Data[1], Data[2], Data[3], Data[4]);
    printf("Encrypted: %02X %02X %02X %02X %02X\n", Buffer[0], Buffer[1], Buffer[2], Buffer[3], Buffer[4]);
    printf("Padded   : %02X %02X %02X %02X %02X\n", Decrypted_pad[0], Decrypted_pad[1], Decrypted_pad[2], Decrypted_pad[3], Decrypted_pad[4]);
    printf("Unpadded : %02X %02X %02X %02X %02X\n", Decrypted_nopad[0], Decrypted_nopad[1], Decrypted_nopad[2], Decrypted_nopad[3], Decrypted_nopad[4]);

    return 0;
}
```

Outputs on when encrypted without padding: 
```
// Clang OpenSSL 1.1.1g
ENC len: 16	// EVP_EncryptUpdate
ENC len: 00	// EVP_EncryptFinal_ex
DEC_pad len: 00	// EVP_DecryptUpdate
DEC_pad len: 00	// EVP_DecryptFinal_ex
DEC_nopad len: 16	// EVP_DecryptUpdate
DEC_nopad len: 00	// EVP_DecryptFinal_ex
Original : 00 01 02 03 04
Encrypted: 39 FD 86 74 F1
Padded   : 00 01 02 03 04
Unpadded : 00 01 02 03 04
```
```
// MSVC OpenSSL 3.3.1
ENC len: 16	// EVP_EncryptUpdate
ENC len: 00	// EVP_EncryptFinal_ex
DEC_pad len: 00	// EVP_DecryptUpdate
DEC_pad len: 00	// EVP_DecryptFinal_ex
DEC_nopad len: 16	// EVP_DecryptUpdate
DEC_nopad len: 00	// EVP_DecryptFinal_ex
Original : 00 01 02 03 04
Encrypted: 39 FD 86 74 F1
Padded   : 39 FD 86 74 F1
Unpadded : 00 01 02 03 04
```

For readers encountering the same issue, example implementation to strip padding:
```cpp
std::vector<uint8_t> Decrypt_AES(std::span<uint8_t> Input, std::span<uint8_t> Key, std::span<uint8_t> IV)
{
    std::vector<uint8_t> Buffer(Input.size());

    EVP_CIPHER_CTX *Context = EVP_CIPHER_CTX_new();
    int Decryptionlength = 0;

    EVP_DecryptInit(Context, EVP_aes_128_cbc(), Key.data(), IV.data());
    EVP_CIPHER_CTX_set_padding(Context, 0);

    EVP_DecryptUpdate(Context, Buffer.data(), &Decryptionlength, Input.data(), int(Input.size()));
    EVP_DecryptFinal_ex(Context, Buffer.data() + Decryptionlength, &Decryptionlength);
    EVP_CIPHER_CTX_free(Context);

    const auto Padding = Buffer.back();

    // Invalid padding.
    if (Padding == 0 || Padding > 16)
        return Buffer;

    // Validate padding.
    for (size_t i = Buffer.size() - Padding; i < Buffer.size(); ++i)
        if (Buffer[i] != Padding)
            return Buffer;

    Buffer.resize(Buffer.size() - Padding);
    return Buffer;
}
```

**Comment by Convery** [comment]
Additional info: This was discovered on Windows with MSVC 17.10.4 and OpenSSL 3.3.1 built via VCPKG.
The Godbolt version has the exact opposite issue where the version without padding fails for OpenSSL 1.1.1 with Clang https://godbolt.org/z/WTo7491aP

**Comment by mattcaswell** [comment]
If you encrypt a plaintext which has a size that is a multiple of the block size, then we expect the size of the ciphertext output to be the length of the plaintext plus the length of the block size. So if you pass a 16 byte plaintext to AES-128-CBC then the encrypted output will be 32 bytes. The last block is all padding.

Your reproducer seems to truncate the final 16 bytes of the ciphertext - which is why you get the bad decrypt error.

**Comment by Convery** [comment]
Maybe I wasn't clear enough, so have updated the comment in the repro for clarity.
Consider both the situation where the result-buffer is 16 and 32 bytes. 
In the case of 16 bytes the result varies by OpenSSL version/compiler. 
The 32-byte case always succeeds, but will (sometimes) waste 16 bytes,
A more permissive `ossl_cipher_unpadblock` would solve both issues.

For `std::array<uint8_t, 16> Buffer{};`:
On Clang with OpenSSL 1.1.1 the padded decrypt **succeeds ** and the unpadded **fails**: https://godbolt.org/z/57n1brbxr
On MSVC with OpenSSL 3.3.1 the padded decrypt **fails** and the unpadded **succeeds **.

For `std::array<uint8_t, 32> Buffer{};`:
On Clang with OpenSSL 1.1.1 the padded decrypt **succeeds ** and the unpadded **succeeds**: https://godbolt.org/z/1eKh4hWqT
On MSVC with OpenSSL 3.3.1 the padded decrypt **succeeds ** and the unpadded **succeeds**.

**Comment by mattcaswell** [comment]
> In the case of 16 bytes the result varies by OpenSSL version/compiler.

In the case where you have truncated the result then you basically have undefined behaviour. 

>         EVP_EncryptFinal_ex(Context, Buffer.data() + Encryptionlength, &Encryptionlength);

Encryptionlength will be 16 at this point. OpenSSL will now attempt to write another 16 bytes of data beyond the end of the allocated buffer. This is undefined behaviour and may crash or give spurious results. Don't do that.

**Comment by Convery** [comment]
The main issue isn't really about the padding being truncated, it's about it being unnecessarily added by default. 
Then when decrypting a block, without the unnecessary padding there's inconsistencies between versions/compilers.

Let's step through the lines on each version / compiler:

For `std::array<uint8_t, 16> Buffer{};` on `MSVC, OpenSSL 3.3.1`:
```
EVP_EncryptUpdate // Encryptionlength = 16
EVP_EncryptFinal_ex // Encryptionlength = 16

// Padded
EVP_DecryptUpdate // Decryptionlength = 0
EVP_DecryptFinal_ex // Decryptionlength = 0
// Buffer unchanged.

// Unpadded
EVP_DecryptUpdate // Decryptionlength = 16
EVP_DecryptFinal_ex // Decryptionlength = 0
// Decrypted block in buffer.
```

For `std::array<uint8_t, 16> Buffer{};` on `Clang, OpenSSL 1.1.1`:
```
EVP_EncryptUpdate // Encryptionlength = 16
EVP_EncryptFinal_ex // Encryptionlength = 16

// Padded
EVP_DecryptUpdate // Decryptionlength = 0
EVP_DecryptFinal_ex // Decryptionlength = 0
// Decrypted block in buffer.

// Unpadded
EVP_DecryptUpdate // Decryptionlength = 0
EVP_DecryptFinal_ex // Decryptionlength = 0
// Buffer unchanged.
```

For `std::array<uint8_t, 32> Buffer{};` on `MSVC, OpenSSL 3.3.1`:
```
EVP_EncryptUpdate // Encryptionlength = 16
EVP_EncryptFinal_ex // Encryptionlength = 16

// Padded
EVP_DecryptUpdate // Decryptionlength = 16
EVP_DecryptFinal_ex // Decryptionlength = 0
// Decrypted block in buffer.

// Unpadded
EVP_DecryptUpdate // Decryptionlength = 32
EVP_DecryptFinal_ex // Decryptionlength = 0
// Decrypted block in buffer.
```

For `std::array<uint8_t, 32> Buffer{};` on `Clang, OpenSSL 1.1.1`:
```
EVP_EncryptUpdate // Encryptionlength = 16
EVP_EncryptFinal_ex // Encryptionlength = 16

// Padded
EVP_DecryptUpdate // Decryptionlength = 16
EVP_DecryptFinal_ex // Decryptionlength = 0
// Decrypted block in buffer.

// Unpadded
EVP_DecryptUpdate // Decryptionlength = 16
EVP_DecryptFinal_ex // Decryptionlength = 0
// Decrypted block in buffer.
```

**Comment by mattcaswell** [comment]
> If you assume that the input will always be padded, it will fail on data encrypted via other systems (that don't add padding if not needed).

Ultimately, adding padding or not by default is a choice. You have to go one way or the other. Adding padding by default seems like a sensible default to me in most cases. Without padding you cannot handle plaintexts that are not multiples of the block length. Either way we cannot change the default now without breaking lots of existing applications that assume OpenSSL will add the padding.

> As such the simple fix would be for ossl_cipher_unpadblock to check if the padding is valid and leave the block untouched if not. 

This is not a viable approach. A non negligible amount of the time (a little over 1/256) a random non padded decryption will appear to have valid padding just by chance resulting in an incorrect decryption. You really need to know the protocol you are working with and whether padding is expected or not.


> Let's step through the lines on each version / compiler to check Decryptionlength:
> For std::array<uint8_t, 16> Buffer{}; on MSVC, OpenSSL 3.3.1:

Any results where you are using a 16 byte buffer cannot be relied upon since you have written 32 bytes of data into that 16 bytes buffer. Undefined behaviour results.

> // Unpadded
EVP_DecryptUpdate   // Decryptionlength = 16

This result for clang with 1.1.1 is slightly unexpected since I assume you have passed in 32 bytes of ciphertext. With 32 bytes of input and no padding I would expect 32 bytes of output. Its a bit unclear though because you don't show how big the ciphertext is. 1.1.1 is also EOL.

**Comment by Convery** [comment]
Let's simplify the example by directly using unpadded encryption as that seems to be a hangup. The example doing unpadded encryption, then padded and unpadded decryption: https://godbolt.org/z/nE8oG9P6s

```
// Clang OpenSSL 1.1.1g
ENC len: 16	// EVP_EncryptUpdate
ENC len: 00	// EVP_EncryptFinal_ex
DEC_pad len: 00	// EVP_DecryptUpdate
DEC_pad len: 00	// EVP_DecryptFinal_ex
DEC_nopad len: 16	// EVP_DecryptUpdate
DEC_nopad len: 00	// EVP_DecryptFinal_ex
Original : 00 01 02 03 04
Encrypted: 39 FD 86 74 F1
Padded   : 00 01 02 03 04
Unpadded : 00 01 02 03 04
```
```
// MSVC OpenSSL 3.3.1
ENC len: 16	// EVP_EncryptUpdate
ENC len: 00	// EVP_EncryptFinal_ex
DEC_pad len: 00	// EVP_DecryptUpdate
DEC_pad len: 00	// EVP_DecryptFinal_ex
DEC_nopad len: 16	// EVP_DecryptUpdate
DEC_nopad len: 00	// EVP_DecryptFinal_ex
Original : 00 01 02 03 04
Encrypted: 39 FD 86 74 F1
Padded   : 39 FD 86 74 F1
Unpadded : 00 01 02 03 04
```

**Comment by mattcaswell** [comment]
The only difference I'm seeing in your latest set of output is in the line that starts "Padded"

Looking at your latest reproducer it seems you attempt to encrypt without padding, and then decrypt with padding. Since the padding is invalid this decryption attempt is going to fail. If the decryption fails then anything in the decryption buffer is garbage. It may contain partially decrypted data, or the original ciphertext, or random data. You should check the return code from all EVP_* calls to confirm whether they have succeeded or not. If the decrypt-with-padding calls have failed then it makes no sense to print the contents of `Decrypted_pad` since it contains garbage. I assume the different results you see above are the result of different internal implementation details which emit different garbage on 1.1.1 compared to 3.3.1.

**Comment by Convery** [comment]
Reworked the issue to be clearer rather than going back and forth in the comments.

**Comment by mattcaswell** [comment]
From your original issue:

> However, unpadblock assumes that there will always be a padding block in the stream, and as such the encryption equivalents will add an unnecessary block of padding if the plaintext is divisible by the blocksize. While this workaround works for OpenSSL <-> OpenSSL systems, 

This isn't a workaround. It's simply how PKCS#5 padding works. It's not specific to OpenSSL. PKCS#5 requires that there is *always* at least 1 padding byte. PKCS#5 is designed to work with arbitrary variable length data that may or not be a multiple of the block size. Without requiring at least 1 padding byte it is not possible to distinguish between a padded block, and an unpadded block that happens to be equal to the the block size.

> a lot of other implementations (especially in embedded) will not waste the extra block.

If there are implementations that do this then either:

1) they are simply doing unpadded encryption/decryption
or
2) they are using some other padding scheme that isn't PKCS#5

This sort of behaviour would normally be specified in the protocol that you are using. Do you have a reference to the protocol? If they are using some other padding scheme, then (assuming it is standardised) the correct answer would be to add support for that padding scheme to OpenSSL

**Comment by tom-cosgrove-arm** [comment]
> While this workaround works for OpenSSL <-> OpenSSL systems, a lot of other implementations (especially in embedded) will not waste the extra block.

This is just not true.

In embedded, if you know you always have a whole number of blocks, or an out-of-band data length indicator, then yes you can not add standard PKCS#5 padding, and just take the first N bytes that were decrypted.

However, even in libraries like [Mbed TLS](https://github.com/Mbed-TLS/mbedtls), which specifically targets embedded systems, standard padding mechanisms such as PKCS#5 (also known as PKCS#7 padding) are used, and do indeed result in an entire extra block of padding bytes if the input plaintext is a whole number of blocks.
