### ISSUE TITLE
Random change to download URLs without redirection

### ISSUE THREAD

**Issue by dirkf** [openssl/openssl#24990]
In order to build historic software for testing, we have to use specific ancient OpenSSL versions like 1.0.2. We fetch these from the source archive at https://www.openssl.org/source/, eg https://www.openssl.org/source/1.0.2/openssl-1.0.2u.tar.gz.

The download path to these ancient source releases has suddenly acquired `/old/` in the path, but no redirect was set, thus breaking links to the source bundles **for everyone who had used the original URL**.

Obviously you can withdraw any download if you wish , and putting `/old/` in the canonical URL seems fine and reasonable, but not setting a redirect is very unhelpful and breaks our attempt to maintain access to the desired archive with `curl -L ...`.

Please don't do this again.

**Comment by t-j-h** [comment]
This is in the process of being fixed now - a few things were missed in the site change over that are being resolved as quickly as we can.

**Comment by dirkf** [comment]
Thanks. At least you didn't blue-screen 8.5M Windows machines!

Is there an ETA, or should I just commit my work-around?

**Comment by dirkf** [comment]
Actually, the `/1.0.2/` is new too.

**Comment by vavroch2010** [comment]
The issue has been fixed. In your case, you should use: 
https://www.openssl.org/source/openssl-1.0.2u.tar.gz
https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz

I think this was never working https://www.openssl.org/source/1.0.2/openssl-1.0.2u.tar.gz (according to directory structure)

**Comment by dirkf** [comment]
Yes, that was a typo. Thanks for the very rapid response.

**Comment by t-j-h** [comment]
Thanks for the quick feedback on the issue!

**Comment by dirkf** [comment]
And I confirm that our original workflow ran successfully after your update.
