### ISSUE TITLE
https://www.openssl.org/source/license.html is down

### ISSUE THREAD

**Issue by smallSwed** [openssl/openssl#25003]
I am not sure this is the right place to report but the license on the website cannot be accessed anymore. 

I get the following instead of the license:
```html
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by nhorman** [comment]
We're working on fixing the missing links from our recent website migration.  You can find the license page here:
https://openssl-library.org/source/license/

@vavroch2010 can we add a redirect for the old link to the new page?  Old link is https://www.openssl.org/source/license.html

**Comment by vavroch2010** [comment]
Fixed please confirm.

**Comment by nhorman** [comment]
ACK, works for me now
