### ISSUE TITLE
Openssl tar file issue while downloading using CURL command in docker file

### ISSUE THREAD

**Issue by pekumar** [openssl/openssl#25027]
I am using openssl 3.0.11 version in my kerberos service. 

Here are the commands im using to install the openssl 3.0.11 on a debian bookworm image

'''
ARG OPENSSL_VERSION=3.0.11

RUN set -ex \
    && apt-get update -y \
    && apt-get -y install curl perl build-essential libssl-dev \
    && cd / \
    && rm -rf dist \
    && mkdir -p dist \
    && cd dist \
    && curl -O https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz  \
    && tar -xzvf openssl-${OPENSSL_VERSION}.tar.gz \
    && cd openssl-${OPENSSL_VERSION} && ./config  && make install 
    
  '''
  
  During this process im getting this following error, though im using a valid openssl URL it could not download the file properly or its not downloading in tar file ,im not sure but i used to use the same lines of commands previously and it worked. I am seeing this issue sometimes from some days.
  
 Here is the error:
 + cd /
+ rm -rf dist
+ curl -O https://www.openssl.org/source/openssl-3.0.11.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
+ tar -xzvf openssl-3.0.11.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Kindly help.

**Comment by pekumar** [comment]
fews days back i saw this issue as a intermittent issue , slowly when i tried for multiple times . It was able to get downloaded and install. Now again i started seeing this issue
<img width="1080" alt="Screenshot 2024-07-29 at 8 53 13 PM" src="https://github.com/user-attachments/assets/0df313c7-716c-4775-a316-b516490c4cc4">


"
```
+ cd /
+ rm -rf dist
+ mkdir -p dist
+ cd dist
+ curl -O https://www.openssl.org/source/openssl-3.0.11.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
+ tar -xzvf openssl-3.0.11.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by pekumar** [comment]
@tom-cosgrove-arm / @paulidale , sorry for  tagging , just trying to get some quick response. since we have a prod issue. Trying to get some solution for the above issue.

**Comment by nhorman** [comment]
add -L to your curl command.  A redirect was recently added to point to the new location of this file, and curl needs to be able to follow those redirects

**Comment by tom-cosgrove-arm** [comment]
I'm going to close this as @nhorman's response is the correct one - this is very common, and annoying that `curl` doesn't default to `-L` in this day and age

**Comment by rsbeckerca** [comment]
Also, `.curlrc` can be modified to include `-L`. That avoids having to remember to do it on every command.

**Comment by pekumar** [comment]
Thank you for the quick response.
