### ISSUE TITLE
[rt.openssl.org #4607] improve quietness for s_client ... also documentation for s_client + s_server

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2502]
Migrated from [rt.openssl.org#4607](https://rt.openssl.org/Ticket/Display.html?id=4607) (status was 'open')

Requestors:
* jsd@av8n.com

Attachments:
* [0001-make-s_client-more-quiet-when-quiet-is-specified.patch](https://rt.openssl.org/Ticket/Attachment/70005/43922/0001-make-s_client-more-quiet-when-quiet-is-specified.patch)
* [0002-when-a-write-to-stdout-has-failed-sending-a-message-.patch](https://rt.openssl.org/Ticket/Attachment/70005/43923/0002-when-a-write-to-stdout-has-failed-sending-a-message-.patch)
* [0003-document-the-verify_quiet-option-to-s_client.patch](https://rt.openssl.org/Ticket/Attachment/70005/43924/0003-document-the-verify_quiet-option-to-s_client.patch)
* [0004-document-the-verify_quiet-option-to-s_server.patch](https://rt.openssl.org/Ticket/Attachment/70005/43925/0004-document-the-verify_quiet-option-to-s_server.patch)

From jsd@av8n.com on 2016-07-05 19:00:25:
```
Hi --

Attached are four simple patches.
They make the apps more usable.
They should be pretty much self-explanatory.
Let me know if you have questions.
```

From rsalz@openssl.org on 2016-07-05 21:42:41:
```
this is for 1.0.2, right?
```

From jsd@av8n.com on 2016-07-06 00:09:32:
```
On 07/05/2016 02:42 PM, Rich Salz via RT wrote:
> this is for 1.0.2, right?

:; openssl version
OpenSSL 1.1.0-pre6-dev

:; git log
commit c2d551c01930df54bce6517cfecd214db6e98e80
Date:   Wed Apr 27 14:47:45 2016 +0100

```

**Comment by mattcaswell** [comment]
These patches are too old. If they are still useful please resubmit as a PR.
