### ISSUE TITLE
TLS1.3 client does not reject HRR without supported_versions field

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#25041]
TLS1.3 client does not reject HRR without supported_versions field，and continues to complete the link establishment.
This behavior does not seem to conform to the rfc8446.

according to [rfc8446](https://www.rfc-editor.org/rfc/rfc8446#section-4.1.4):
   **The server's extensions MUST contain "supported_versions"**.
   Additionally, it SHOULD contain the minimal set of extensions
   necessary for the client to generate a correct ClientHello pair.  As
   with the ServerHello, a HelloRetryRequest MUST NOT contain any
   extensions that were not first offered by the client in its
   ClientHello, with the exception of optionally the "cookie" (see
   [Section 4.2.2](https://www.rfc-editor.org/rfc/rfc8446.html#section-4.2.2)) extension.

   Upon receipt of a HelloRetryRequest, the client MUST check the
   legacy_version, legacy_session_id_echo, cipher_suite, and
   legacy_compression_method as specified in [Section 4.1.3](https://www.rfc-editor.org/rfc/rfc8446#section-4.1.3) and then
   process the extensions, **starting with determining the version using
   "supported_versions"**.  Clients MUST abort the handshake with an
   "illegal_parameter" alert if the HelloRetryRequest would not result
   in any change in the ClientHello.  If a client receives a second
   HelloRetryRequest in the same connection (i.e., where the ClientHello
   was itself in response to a HelloRetryRequest), it MUST abort the
   handshake with an "unexpected_message" alert.

**Comment by mattcaswell** [comment]
This is a bug. Fix coming up.

**Comment by mattcaswell** [comment]
Fix in #25068
