### ISSUE TITLE
In TLS1.3, the client provides the ”psk_dhe_ke“ mode. When the server selects the ”psk_ke“ mode, the alert description is not "illegal_parameter"

### ISSUE THREAD

**Issue by baoyi84930** [openssl/openssl#25040]
openssl version:3.0.9
according to [rfc8446](https://www.rfc-editor.org/rfc/rfc8446#section-4.2.11)

> Clients MUST verify that the server's selected_identity is within the
   range supplied by the client, that the server selected a cipher suite
   indicating a Hash associated with the PSK, and that **a server
   "key_share" extension is present if required by the ClientHello
   "psk_key_exchange_modes" extension.**  If these values are not
   consistent, the client MUST abort the handshake with an
   **"illegal_parameter"** alert.

The client sends the psk_dhe_ke mode. Then the server hello was received without the "key_share" extension, and the "missing_extension" alert was sent in `extensions.c:final_key_share`
```C
    if (!s->server
            && !sent
            && (!s->hit
                || (s->ext.psk_kex_mode & TLSEXT_KEX_MODE_FLAG_KE) == 0)) {
        /* Nothing left we can do - just fail */
        SSLfatal(s, SSL_AD_MISSING_EXTENSION, SSL_R_NO_SUITABLE_KEY_SHARE);
        return 0;
    }
```

**Comment by mattcaswell** [comment]
Fix in #25059
