### ISSUE TITLE
[OpenSSL 3.1.4][FIPS provider]: 80-test_ssl_old.t failing with make test run

### ISSUE THREAD

**Issue by suresh043** [openssl/openssl#25052]
### OpenSSL version: 3.1.4
FIPS provider is enabled. 

Command : make test

Errors:
```
80-test_ssl_new.t .................. ok
80-test_ssl_old.t .................. 8/?
     Testing ciphersuites for -tls1_2
OpenSSL: FIPS 140-3 self-tests passed!
4067FECD557F0000:error:0A0000B9:SSL routines:(unknown function):no cipher match:ssl/ssl_lib.c:2761:
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/fips-and-base.cnf -provider fips -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher 'OpenSSL:@SECLEVEL=0' -ciphersuites '' -tls1_2 => 1
    not ok 3 - Testing OpenSSL:@SECLEVEL=0
 ------------------------------------------------------------------------------
     Testing ciphersuites for -tls1_3
OpenSSL: FIPS 140-3 self-tests passed!
40673E87407F0000:error:0A0000B9:SSL routines:(unknown function):no cipher match:ssl/ssl_ciph.c:1347:
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/fips-and-base.cnf -provider fips -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' -ciphersuites OpenSSL => 1
    not ok 56 - Testing
 ------------------------------------------------------------------------------

    #   Failed test 'Testing '
    #   at test/recipes/80-test_ssl_old.t line 507.
OpenSSL: FIPS 140-3 self-tests passed!
4037B5434E7F0000:error:0A0000B9:SSL routines:(unknown function):no cipher match:ssl/ssl_ciph.c:1347:
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/fips-and-base.cnf -provider fips -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' -ciphersuites ' FIPS 140-3 self-tests passed!' => 1
    not ok 57 - Testing
 ------------------------------------------------------------------------------
     Looks like you failed 3 tests of 59.
not ok 9 - Testing ciphersuites
80-test_ssl_old.t .................. 9/? ---------------------------------------
80-test_ssl_old.t .................. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/13 subtests
80-test_ssl_test_ctx.t ............. ok
80-test_sslcorrupt.t ............... ok
```
######################

Changes:
File: /openssl/provider/fips/self_test.c
```
/* This API is triggered either on loading of the FIPS module or on demand */
int SELF_TEST_post(SELF_TEST_POST_PARAMS *st, int on_demand_test)
{
    int ok = 0;
    int kats_already_passed = 0;
    . . .
    ok = 1;
    **printf("OpenSSL: FIPS 140-3 self-tests passed!\n");
    fflush(stdout);**
end:
    EVP_RAND_free(testrand);
    OSSL_SELF_TEST_free(ev);
```
######
 Need to print log message once FIPS self test passes, for that added printf statement. But make test are failing with printf statement.

1) If we remove printf statement i am not seeing make test failure.
2) If we run like this "make TESTS='alltests -test_ssl_old' test" it run all remaining test successfully.

**Comment by ifranzki** [comment]
This seems to be a duplicate of https://github.com/openssl/openssl/issues/25039

**Comment by suresh043** [comment]
Thanks @ifranzki, yeah some extent it is. 
But here it is printing printf log message and throwing error. Looks like it is taking printf log as a input for ciphersuites. That is strange

### OpenSSL: FIPS 140-3 self-tests passed!
4037B5434E7F0000:error:0A0000B9:SSL routines:(unknown function):no cipher match:ssl/ssl_ciph.c:1347:
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/fips-and-base.cnf -provider fips -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' ### -ciphersuites ' FIPS 140-3 self-tests passed!' => 1
not ok 57 - Testing

**Comment by mattcaswell** [comment]
Please can you provide details of how you configured OpenSSL. You say you are using OpenSSL 3.14 - is that for both the main library and the fips provider itself? Or are these two versions different?

**Comment by suresh043** [comment]
Hi @mattcaswell,
It's just normal configure with enable-fips mode as

./Configure \
    --prefix=%{_prefix} --openssldir=%{_sysconfdir}/pki/tls ${sslflags} \
    enable-fips  \
    ${sslarch} -Wa,--noexecstack \
    -I%{devfsdir}/usr/include -L%{devfsdir}/usr/%{_lib} \
    -Wno-cpp -Wno-strict-aliasing -Werror

make -j all  -> passes
make -j test  -> fails for 80-test_ssl_old.t

**Comment by t8m** [comment]
This is not a duplicate of https://github.com/openssl/openssl/issues/25039

If you patch the fips provider to print things to stdout you can expect some things to be broken. Namely the testcases where output of a binary to stdout is parsed.

**Comment by t8m** [comment]
You could try to printing this to stderr instead.

**Comment by suresh043** [comment]
Thanks @t8m ,
Indeed we are patching fips provider. And replacing printf with stderr resolved test issue.
