### ISSUE TITLE
Provider compatibility test across version is broken in evp_test in the HKDF testcase

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#25089]
Please see https://github.com/openssl/openssl/actions/runs/10251248216/job/28359378698

**Comment by t8m** [comment]
This must have been broken by the HMAC key size check changes

**Comment by t8m** [comment]
@paulidale @slontis could you please look at it ASAP?

**Comment by nhorman** [comment]
Its not a specific error in the execution of the HKDF, the test is just failing because the output of the derivation operation doesn't match whats expected.
