### ISSUE TITLE
Receives any other change_cipher_spec value MUST abort the handshake with an "unexpected_message" alert in TLS1.3

### ISSUE THREAD

**Issue by lan1120** [openssl/openssl#25086]
When openssl receives an other change_cipher_spec value, it abort the handshake with an "illegal_parameter",  this does not follow the rfc8446.
according to [rfc8446](https://www.rfc-editor.org/rfc/rfc8446#section-5):

>    An implementation which receives any other change_cipher_spec value or
>    which receives a protected change_cipher_spec record **MUST** abort the
>    handshake with an "**unexpected_message**" alert.

The problem may be in the **tls_get_more_records** function (master branch):
```
if (num_recs == 1
        && thisrr->type == SSL3_RT_CHANGE_CIPHER_SPEC
           /* The following can happen in tlsany_meth after HRR */
        && rl->version == TLS1_3_VERSION
        && rl->is_first_handshake) {
    /*
     * CCS messages must be exactly 1 byte long, containing the value 0x01
     */
    if (thisrr->length != 1 || thisrr->data[0] != 0x01) {
        RLAYERfatal(rl, SSL_AD_ILLEGAL_PARAMETER,
                    SSL_R_INVALID_CCS_MESSAGE);
        return OSSL_RECORD_RETURN_FATAL;
    }
```

**Comment by mattcaswell** [comment]
Looks correct. This is a minor conformance issue. Adding help wanted and good first issue labels.
