### ISSUE TITLE
Regarding fix for creating PKCS12 file with FIPS provider.

### ISSUE THREAD

**Issue by ChauhanPriyanka** [openssl/openssl#25117]
Hi team,

We are waiting for the fix - https://github.com/openssl/openssl/issues/20072 
Could you please update the release date. 
Our expectation is - with this fix PKCS12_create API will work in FIPS mode.

**Comment by beldmit** [comment]
#24577 is just merged to master branch. Will be released in some future.

**Comment by t8m** [comment]
This will be included in the 3.4.0 release that will be done in October 2024.
