### ISSUE TITLE
EVP_PKEY_CTX_set_kem_op documentation

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#25142]
Is this part of the documentation still relevant? Looks like we support KEM at least for EC/ECX

https://github.com/openssl/openssl/blob/fd39d1c80cd5bd9cb5c64e3fc96102397e5e860f/doc/man3/EVP_PKEY_CTX_ctrl.pod?plain=1#L653-L657

**Comment by slontis** [comment]
There is a second type now..
#define OSSL_KEM_PARAM_OPERATION_RSASVE     "RSASVE"
#define OSSL_KEM_PARAM_OPERATION_DHKEM      "DHKEM"

**Comment by ebleass** [comment]
Which of the two do I use if using the new ML-KEM algorithms in openssl v3.5.x?

Thanks.

**Comment by slontis** [comment]
You dont need to set it for mlkem.. (The original intention for this API was that it would allow us to have multiple ops for the same algorithm).
