### ISSUE TITLE
Segmentation fault for  acert-test

### ISSUE THREAD

**Issue by toralf** [openssl/openssl#25158]
I do run the AFL++ fuzzer against latest git HEAD and got today:
```
torproject@mr-fox ~/findings/openssl_acert_20240811-190937_ed7a8bfd7409 $ for i in default/crashes/*; do time ./acert-test $i; done
# default/crashes/id:000000,sig:11,src:000551+000294,time:54280,execs:1656680,op:splice,rep:2
Segmentation fault

real    0m0.004s
user    0m0.000s
sys     0m0.003s
# default/crashes/id:000001,sig:11,src:000091+000294,time:916570,execs:23135141,op:splice,rep:1
Segmentation fault

real    0m0.003s
user    0m0.000s
sys     0m0.003s
# default/crashes/id:000002,sig:11,src:000535,time:1082420,execs:27620166,op:havoc,rep:6
Segmentation fault

real    0m0.003s
user    0m0.003s
sys     0m0.000s
# default/crashes/id:000003,sig:11,src:000792,time:1088153,execs:27755629,op:havoc,rep:2
Segmentation fault

real    0m0.003s
user    0m0.000s
sys     0m0.002s
# default/crashes/id:000004,sig:11,src:000807,time:1090032,execs:27800729,op:havoc,rep:1
Segmentation fault

real    0m0.003s
user    0m0.003s
sys     0m0.000s
# default/crashes/id:000005,sig:11,src:000551+000294,time:1546646,execs:40368988,op:splice,rep:1
Segmentation fault

real    0m0.003s
user    0m0.002s
sys     0m0.000s
# default/crashes/id:000006,sig:11,src:000551+000294,time:1630324,execs:42674828,op:splice,rep:2
Segmentation fault

real    0m0.003s
user    0m0.002s
sys     0m0.000s
# default/crashes/README.txt
```
I attached the fuzzer
[openssl_acert_20240811-190937_ed7a8bfd7409.tar.gz](https://github.com/user-attachments/files/16576043/openssl_acert_20240811-190937_ed7a8bfd7409.tar.gz)

**Comment by nhorman** [comment]
hmm, did you have commit 7bcfb41489903543546d25ec13f8c58f36a147b3 in your tree?  We just fixed something in the acert fuzzer that clusterfuzz caught.  See https://github.com/openssl/project/issues/799

**Comment by toralf** [comment]
> hmm, did you have commit [7bcfb41](https://github.com/openssl/openssl/commit/7bcfb41489903543546d25ec13f8c58f36a147b3) in your tree? We just fixed something in the acert fuzzer that clusterfuzz caught. See [openssl/project#799](https://github.com/openssl/project/issues/799)

That commit was not in the tested version. Plus the current git HEAD does not reproduce the segfault.
