### ISSUE TITLE
[rt.openssl.org #4656] [BUG] print_bin could access memory off the end of a buffer

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2517]
Migrated from [rt.openssl.org#4656](https://rt.openssl.org/Ticket/Display.html?id=4656) (status was 'new')

Requestors:
* graeme.perrow@sap.com

From graeme.perrow@sap.com on 2016-08-22 13:56:17:
```
In file crypto/ec/eck_prn.c, if the function print_bin is called with len >= 15 and off >= 124, we would eventually hit line 261:

memset( &(str[1]), ' ', off + 4 );

which would write >= 128 bytes into a 127-byte buffer.


```

**Comment by mattcaswell** [comment]
This was fixed.

master: 8fce04e
1.1.0: b5cd178
1.0.2: f65ee71
