### ISSUE TITLE
FIPSVersion should not limit an evp_test testcase to the fips provider

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#25199]
When updating #22910 I noticed that most of the test cases in `test/recipes/30-test_evp_data/evppkey_ecx.txt` (and in similar files) are disabled for non-FIPS builds, due to lines like 
```
FIPSversion = >=3.2.0
```
Is this on purpose?

**Comment by t8m** [comment]
Please see #24996, it is a temporary issue to be fixed.
