### ISSUE TITLE
can compitible libtool as a archive maker?

### ISSUE THREAD

**Issue by xiedeacc** [openssl/openssl#25205]
for some reason, I must set libtool as archiver, but openssl call archiver with specified options(qc) that libtool not support, so archive stage will fail, request openssl compitible with libtool, thanks very much
```
ar qc libssl.a ssl/libssl-lib-bio_ssl.o... --> libtool qc libssl.a ssl/libssl-lib-bio_ssl.o...
```

**Comment by nhorman** [comment]
The definitions for AR and ARFLAGS are found in Configurations/00-base-templates.conf (see the BASE_unix template defintion).  If you have a need to override those, you can set AR=libtool ARFLAGS="" on the configure command line

**Comment by xiedeacc** [comment]
libtool will output libcrypto.a twice, and sencond time will override first one, lead many undefined symbols when link to libcrypto, libcrypto.3.dylib has all symbols. why libtool output libcrypto.a twice?(caused too many object files??), can compitibable this situations? 
my ARFLAGS is -static -o
![image](https://github.com/user-attachments/assets/0241457e-1cf6-46dd-87cd-485adf21432e)

**Comment by xiedeacc** [comment]
maybe it's libtool's problem
