### ISSUE TITLE
OpenSSL CMS decryption not working with external providers

### ISSUE THREAD

**Issue by vchandap** [openssl/openssl#25224]
### Discussed in https://github.com/openssl/openssl/discussions/25138

<div type='discussions-op-text'>

<sup>Originally posted by **vchandap** August  8, 2024</sup>
Hi,

I am trying to use OpenSSL CMS with an external provider (https://github.com/NXPPlugNTrust/se05x-openssl-provider/tree/main).

Currently, decryption is failing due to incorrect padding. It seems that OpenSSL RSA decryption doesn't call EVP_PKEY_CTX_set_rsa_padding when PKCS1.5 padding is used and expects providers to use RSA_PKCS1_PADDING as the default.

Is the above assumption correct, and is there any documentation available for this?

Thanks, in advance </div>

**Comment by t8m** [comment]
Answered in the discussion.
