### ISSUE TITLE
The behavior of `--libdir` changed in 3.3.1 — previously it took an entire path, and now perhaps only wants `lib` or `lib64`.


### ISSUE THREAD

**Issue by satmandu** [openssl/openssl#25249]
This change broke the libdir lines in our pkgconfig files on Linux/Chromebrew, and building from the current 3.3 branch didn't fix it. I'm attempting to rebuild now to see if just setting `--libdir` differently fixed this issue.

```
cat /usr/local/lib/pkgconfig/libcrypto.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/.
includedir=${prefix}/include
enginesdir=${libdir}/lib/engines-3
modulesdir=${libdir}/lib/ossl-modules

Name: OpenSSL-libcrypto
Description: OpenSSL cryptography library
Version: 3.3.2-dev
Libs: -L${libdir} -lcrypto
Libs.private: -ldl -pthread
Cflags: -I${includedir}
```

```
cat /usr/local/lib/pkgconfig/libssl.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/.
includedir=${prefix}/include

Name: OpenSSL-libssl
Description: Secure Sockets Layer and cryptography libraries
Version: 3.3.2-dev
Requires.private: libcrypto
Libs: -L${libdir} -lssl
Cflags: -I${includedir}
```

```
cat /usr/local/lib/pkgconfig/openssl.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/.
includedir=${prefix}/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries and tools
Version: 3.3.2-dev
Requires: libssl libcrypto
```

_Originally posted by @satmandu in https://github.com/openssl/openssl/issues/24986#issuecomment-2301579358_

**Comment by levitte** [comment]
The interesting bit here is what you got as default libdir...  `.`?  That might actually lead to an answer to what's going on on Mac.

**Comment by satmandu** [comment]
Setting `--libdir` to `lib` or `lib64` does appear to resolve this for our Linux `i686`, `x86_64`, and `armv7l` builds.

I would suggest either a warning if a full path is set in `--libdir`, or just trimming `prefix` off of whatever `libdir` is set to.

One could also use a separate option that doesn't conflict with the standardized autotools definition, such as lib_suffix (which cmake uses), which for instance could be set to `64`.

Any of these approaches would be appreciated for those of us packaging builds who like to just try incrementing a version number and then attempting a build. 

I would of course note that there's a [sordid history of trying to get a lib vs libdir set properly in autotools configure scripts](https://bugzilla.redhat.com/show_bug.cgi?id=1510073) as well... So there's maybe no _right_ solution... But it would be useful to have a _consistent_ solution per software package.

(Also, it would have been nice for there to have been a check that would fail if libdir was set wrong in the pkgconfig file.)

In any case, here is the success I see setting `--libdir=lib` for our `armv7l` build building from the top of the 3.3 branch:

```
cat /usr/local/lib/pkgconfig/libcrypto.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
enginesdir=${libdir}/engines-3
modulesdir=${libdir}/ossl-modules

Name: OpenSSL-libcrypto
Description: OpenSSL cryptography library
Version: 3.3.2-dev
Libs: -L${libdir} -lcrypto
Libs.private: -ldl -pthread
Cflags: -I${includedir}
```

**Comment by nhorman** [comment]
@satmandu can you by any chance test with the recent 3.4 alpha release? Several changes went into the generation of package-config files that I think may have addressed this

**Comment by satmandu** [comment]
We have built with the recent tagged release, and used libdir=lib or libdir=lib64, and that seems to have worked for us.

**Comment by levitte** [comment]
> @satmandu can you by any chance test with the recent 3.4 alpha release? Several changes went into the generation of package-config files that I think may have addressed this

Those changes (bug fixes) went into 3.3 as well, FYI

**Comment by satmandu** [comment]
```bash
cat /usr/local/lib64/pkgconfig/openssl.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries and tools
Version: 3.3.2
Requires: libssl libcrypto
```

**Comment by nhorman** [comment]
excellent, thank you for the quick turn around.  closing this then
