### ISSUE TITLE
ossl_ec_key_dup() takes two engine references

### ISSUE THREAD

**Issue by kristskrilovs** [openssl/openssl#25260]
I am using qat engine with proxy type TLS application and noticed that my engine references are going up with each connection. I suspected memory leak somewhere so I debugged this issue further and turns out that it's not a memory leak but just a ref leak.

ossl_ec_key_dup() calls ossl_ec_key_new_method_int() which initializes and sets ret->engine.

But then further there's code

```
        if (src->meth != NULL) {
#if !defined(OPENSSL_NO_ENGINE) && !defined(FIPS_MODULE)
            if (src->engine != NULL && ENGINE_init(src->engine) == 0)
                goto err;
            ret->engine = src->engine;
#endif
            ret->meth = src->meth;
        }
```

which takes yet another engine reference and again sets ret->engine to src->engine.

So you have engine references go up by 2 with each ossl_ec_key_dup() call but only one reference is released in EC_KEY_free().

**Comment by mattcaswell** [comment]
It looks to me like this bit of code could simply be deleted:

```` C
#if !defined(OPENSSL_NO_ENGINE) && !defined(FIPS_MODULE)
            if (src->engine != NULL && ENGINE_init(src->engine) == 0)
                goto err;
            ret->engine = src->engine;
#endif
````

**Comment by zimirza** [comment]
I hope it is ok if I create a pull request for this issue.
