### ISSUE TITLE
TLS index that holds fipsctx->thread_event_handler is not freed

### ISSUE THREAD

**Issue by zhihaoy** [openssl/openssl#25278]
The FIPS-specific `thread_event_handler` is a pointer stored in TLS index https://github.com/openssl/openssl/blob/2e966354956e55825331f61bf98976ffe60e4332/crypto/initthread.c#L269-L278

You may need to do similar to how `rcu_local_key` is handled
https://github.com/openssl/openssl/blob/2e966354956e55825331f61bf98976ffe60e4332/crypto/context.c#L348-L363

The problem is revealed by AppVerifier on Windows 10, with and without using a non-default OpenSSL library context.

**Comment by nhorman** [comment]
I'm not sure I follow, The thread_event_handler is cleaned up in context_deinit_objs is called during context teardown.

What did AppVerifier show you?

**Comment by zhihaoy** [comment]
> [...] The thread_event_handler is cleaned up in context_deinit_objs is called during context teardown.

This code in `context_deinit_objs`
https://github.com/openssl/openssl/blob/81259299499e81d0b3850e09c9366aa67c65b07c/crypto/context.c#L320-L324
freed only the resource that `thread_event_handler` pointers to
https://github.com/openssl/openssl/blob/81259299499e81d0b3850e09c9366aa67c65b07c/crypto/initthread.c#L297-L300
The TLS index created by `CRYPTO_THREAD_init_local` is still there.

> What did AppVerifier show you?

```
0:000> g
ModLoad: 00007ffb`b0cb0000 00007ffb`b1354000   [some].dll
ModLoad: 00007ffc`85b30000 00007ffc`85c8e000   C:\windows\System32\CRYPT32.dll
ModLoad: 00007ffb`bc630000 00007ffb`bc992000   [path]\fips.dll


=======================================
VERIFIER STOP 0000000000000350: pid 0xB69C: Unloading DLL that allocated TLS index that was not freed. 

	000000000019ABBA : TLS index
	00007FFBBC7B133D : Address of the code that allocated this TLS index.
	000001AB39442FE6 : DLL name address. Use du to dump it.
	00007FFBBC630000 : DLL base address.


=======================================
This verifier stop is continuable.
After debugging it use `go' to continue.

=======================================
```

**Comment by nhorman** [comment]
The individual thread context objects should be deallocated when the threads that allocated them exit, or when the library context that allocated that correspond to them are freed.

The fact that this occurs when (ostensibly the libcrypto and fips dlls are unloaded suggests that you have a thread which is still running with openssl library context at the time of cleanup.

Do you have a minimal reproducer that illustrates this behavior?

**Comment by zhihaoy** [comment]
> The fact that this occurs when (ostensibly the libcrypto and fips dlls are unloaded suggests that you have a thread which is still running with openssl library context at the time of cleanup.

I have only the main thread.

> 
> Do you have a minimal reproducer that illustrates this behavior?

I have a minimal reproduce, but it's still the company's code, and I don't think I can share it. But it's very simple: `some.dll` is a library that links a static copy of `libcrypto` that has `no_pinshared`. An `.exe` `LoadLibrary` `some.dll`, calling into a function in `some.dll`, and unloads it. The function in `some.dll` does the following:
```
OSSL_LIB_CTX_new
OSSL_PROVIDER_set_default_search_path
OSSL_LIB_CTX_load_config
OSSL_PROVIDER_load(fips)
OSSL_PROVIDER_load(base)
X509_new_ex
d2i_X509
X509_free
OSSL_PROVIDER_unload(base)
OSSL_PROVIDER_unload(fips)
OSSL_LIB_CTX_free
```

**Comment by nhorman** [comment]
I believe that the ordering of the last two calls is the problem.  I'm not 100% sure, and its a bit counter-intuitive, but freeing the libctx that you've allocated call OPENSSL_thread_stop, which triggers all the needed callbacks to cleanup the allocations made in your main thread against the thread_event_handler key, prior to the OSSL_PROVIDER_unload call unloading the DLL.

Try backing out your proposed changed, and reversing those last two calls, and I think the problem will abate.

**Comment by zhihaoy** [comment]
> I believe that the ordering of the last two calls is the problem. I'm not 100% sure, and its a bit counter-intuitive, but freeing the libctx that you've allocated call OPENSSL_thread_stop, which triggers all the needed callbacks to cleanup the allocations made in your main thread against the thread_event_handler key, prior to the OSSL_PROVIDER_unload call unloading the DLL.
> 
> Try backing out your proposed changed, and reversing those last two calls, and I think the problem will abate.

If you mean doing this
```
OSSL_LIB_CTX_free
OSSL_PROVIDER_unload(fips)
```

The result is an access violation.

```
ModLoad: 00007ffd`2ac50000 00007ffd`2afb2000   [some].dll
(6e60.6eec): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
[some]!ossl_lib_ctx_get_data+0x86:
00007ffc`b7814176 488b80b8000000  mov     rax,qword ptr [rax+0B8h] ds:0000015f`bf8e3f68=????????????????
0:000> k
 # Child-SP          RetAddr               Call Site
00 00000029`8b2ff7e0 00007ffc`b780e60a     [some]!ossl_lib_ctx_get_data+0x86 [src\crypto\context.c @ 564] 
01 00000029`8b2ff820 00007ffc`b7810097     [some]!get_provider_store+0x2a [src\crypto\provider_core.c @ 331] 
02 00000029`8b2ff860 00007ffc`b7810752     [some]!provider_deactivate+0x97 [provider_core.c @ 1096] 
03 00000029`8b2ff8c0 00007ffc`b78123e1     [some]!ossl_provider_deactivate+0x32 [src\crypto\provider_core.c @ 1324] 
04 00000029`8b2ff900 00007ffc`b78094e3     [some]!OSSL_PROVIDER_unload+0x21 [src\crypto\provider.c @ 73] 
```
