### ISSUE TITLE
[rt.openssl.org #4676] Error converting to p12 crt

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2528]
Migrated from [rt.openssl.org#4676](https://rt.openssl.org/Ticket/Display.html?id=4676) (status was 'open')

Requestors:
* eneges.correo@gmail.com

Attachments:
* [Sin título.png](https://rt.openssl.org/Ticket/Attachment/71647/45198/Sin%20tí­tulo.png)

From eneges.correo@gmail.com on 2016-09-16 13:54:00:
```
Hi. I use openssl to convert a certificate with * . * . crt to p12 . I
do this through a .bat withthe following command line :
openssl pkcs12 -export -in -inkey SierrasClave.key
Cert1_7a79ea64423417fd.crt -out Cert1_7a79ea64423417fd.p12 -name "
Cert1_7a79ea64423417fd "
pause

The error message is attached .
OpenSSL use for 64 -bit Win7.
I hope your answer. Thank you very much
```

From rsalz@akamai.com on 2016-09-28 12:34:51:
```
You did not cut/paste the command line properly because you wrote "-in -inkey" which is wrong.  Or maybe that is your error?


```

From rsalz@akamai.com on 2016-09-28 12:41:02:
```
Try putting a "dir" command before the openssl command, to make sure that the file exists.

```

**Comment by levitte** [comment]
Looks like usage error.  Closing.
