### ISSUE TITLE
Segmentation fault in RSA_pkey_ctx_ctrl

### ISSUE THREAD

**Issue by cr-galrosen** [openssl/openssl#25295]

**Comment by cr-galrosen** [comment]
#8  0x00007fc8103f0b55 in RSA_pkey_ctx_ctrl () from /lib64/libcrypto.so.3
#9  0x00007fc815ef03a3 in pgpVerifySigRSA () from /lib64/librpmio.so.9
#10 0x00007fc815edc55e in pgpVerifySignature () from /lib64/librpmio.so.9
#11 0x00007fc815ee418f in pgpPrtParams () from /lib64/librpmio.so.9
#12 0x00007fc815eefb81 in rpmPubkeyNew () from /lib64/librpmio.so.9
#13 0x00007fc815e697c5 in loadKeyring () from /lib64/librpm.so.9
#14 0x00007fc815e69c38 in rpmtsInitIterator () from /lib64/librpm.so.9
#15 0x00007fc815e580f1 in matchesIterator () from /lib64/librpm.so.9
#16 0x00007fc815e58672 in initQueryIterator () from /lib64/librpm.so.9
#17 0x00007fc815e59617 in rpmcliArgIter () from /lib64/librpm.so.9
#18 0x00007fc815e599fa in rpmcliQuery () from /lib64/librpm.so.9

**Comment by cr-galrosen** [comment]
It happened on RHEL 9

**Comment by vdukhovni** [comment]
There isn't sufficient detail here to make progress, and RedHat patches OpenSSL extensively in support of "Crypto Policies". If the RPM utilities are having issues with RSA keys, you should start with the vendor, rather than the OpenSSL project.

**Comment by beldmit** [comment]
Let me reopen it - low-level functions are normally not modified by Red Hat patches. But I agree with @vdukhovni, there is not enough information so could you please install debug libraries and provide more information?

**Comment by beldmit** [comment]
No until you have a reproducer

**Comment by vdukhovni** [comment]
While many low level functions are not modified by Redhat, signature verification functions definitely are, in particular crypto policies restrict verification of RSA with SHA1 signatures, and perhaps also set minimum key size limits, ...

I still think the issue should first be reported to RedHat, and if found by RedHat customer support to be an issue in the underlying upstream OpenSSL code, then RedHat can open an issue with OpenSSL.

**Comment by nhorman** [comment]
Concur with @vdukhovni , while we would like to help, if this is on the RHEL9 distro's version of openssl, reported by a distro customer without a reproducer, seems like the only reasonable course to progress here is to have the RHEL support team take first stab at it.  If RHEL discovers this is reproducible on upstream openssl, please feel free to open  an issue here

**Comment by cr-galrosen** [comment]
BTW, the command that was run: "rpm -ql --dump <package name>"
While running with the additional 2 flags: --nodigest --nosignature it does not crash.

**Comment by beldmit** [comment]
I don't think this command can reveal any private keys, so you may ask clients to get a full backtrace or raise an issue in Red Hat tracker
