### ISSUE TITLE
Allow explicit declaration of calling convention

### ISSUE THREAD

**Issue by rtollert** [openssl/openssl#25324]
Presently, the OpenSSL API leaves function calling conventions at their compiler defaults. Under Visual C++ the default calling convention is [__cdecl](https://learn.microsoft.com/en-us/cpp/cpp/cdecl?view=msvc-170), aka `/Gd`. This is proving problematic under environments where mixed calling conventions are in use: some components are compiled with `/Gd`; others are compiled with `/Gz` ([__stdcall](https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170)); each component's API typically fixes their calling conventions in their function declarations, so that each can call the other transparently. But because OpenSSL does not declare their calling convention one way or another, components compiled for the opposite calling convention can't link, because the calling convention results in a different name mangling. And while you can explicitly set the calling convention of individual declarations, you can't set those of an entire block at once, so we can't, e.g., do something like `__cdecl { #include <openssl/evp.h> }` or whatever to fix the calling convention on the calling-side; one way or another, the headers themselves must change.

Obviously there are multiple ways of solving this, and most of them do not involve upstream changes. But just in case, I wanted to float the idea of a PR to allow the calling convention of API functions to be explicitly declared, in case anybody had any strong opinions about it one way or another. AFAIK, what this would look like is
- `openssl/macros.h`: New definition `OPENSSL_DECL`, defaults to empty except on Win32, where it is `__cdecl`.
- For every function in `utility/*.num`: change its header declaration to include `OPENSSL_DECL`.
- I'm not sure I have a good answer for automating this yet; there remains the risk of new function declarations missing `OPENSSL_DECL`. I'm open to suggestions.

**Comment by t8m** [comment]
This would truly uglify the header files. I am seriously not fond of it.

**Comment by nhorman** [comment]
I'm not sure I fully agree with the notion that every component explicitly specifies the calling convention for each function in its api.  I suppose I could see that being the case for components that are binary only so that linking works properly, but for open source components, it should be fairly straight forward to set the calling convention globally at compile time.  That is to say if you have a component that uses the cdecl convention, you should just be able to add /Gd to the Configure command to enforce passing that flag to every object build, which as I understand it, should be equivalant to setting cdecl on each individual function.

Or is this more complex?  I.e. do you have two components with differing conventions that each need to use a different calling convention because they are binary distributions?  If so, I'm not sure that using an attribute on the exported functions will help, as you still have to pick a global convention, against which at least one of those two components will fail.

**Comment by levitte** [comment]
If I'm not mistaken, it's possible to mix modules with different internal calling conventions, as long as each module is aware of what calling convention is used by functions in all other modules.

I assume that is when it becomes important to declare it explicitly, to place the knowledge of what's what in a promptly accessible place (like header files) and avoid having the meta information about how a module (like the OpenSSL libraries) was built from, er, *somewhere else*...

**Comment by levitte** [comment]
Do note that for VMS, we do have some build specific headers that are included before everything else (`__DECC_INCLUDE_PROLOGUE.H`) as well as after (`__DECC_INCLUDE_EPILOGUE.H`)

**Comment by rtollert** [comment]
> If I'm not mistaken, it's possible to mix modules with different internal calling conventions, as long as each module is aware of what calling convention is used by functions in all other modules.
> 
> I assume that is when it becomes important to declare it explicitly, to place the knowledge of what's what in a promptly accessible place (like header files) and avoid having the meta information about how a module (like the OpenSSL libraries) was built from, er, somewhere else...

AFAIK MSVC doesn't really even provide any other way to override the default calling convention except through the header files, and only on a per-declaration basis. Which is kind of curious now that I think about it, because the problem statement is broadly very analogous to that of controlling structure alignment, and MSVC [does](https://learn.microsoft.com/en-us/cpp/preprocessor/pack?view=msvc-170) provide a way to control *that* on a header-by-header basis. If that existed, then we could just override the calling convention while #include'ing any OpenSSL headers.

**Comment by nhorman** [comment]
So, I'm unsure where we are on this.  I don't think we're going to undertake the effort to support mixed calling conventions, but I'm happy to defer to other opinions.  @levitte @t8m ?

**Comment by t8m** [comment]
I concur.

**Comment by nhorman** [comment]
ok, thats enough for me, closing as not planned

**Comment by rtollert** [comment]
(yes, I'm OK with this getting closed; just figured I'd ask)
