### ISSUE TITLE
Error message when requesting too many threads in argon2id is wrong

### ISSUE THREAD

**Issue by alex** [openssl/openssl#25344]
https://github.com/openssl/openssl/blob/0cd9dd703ea575699b2d3cd74f1b8224447f4352/providers/implementations/kdfs/argon2.c#L1073-L1075

The message indicates that `"requested %u threads, available: 1"`, however what it actually shows is the number of maximum threads as requested.

**Comment by vdukhovni** [comment]
Should I hope automatically close when the PR is merged.

**Comment by nhorman** [comment]
PR merged
