### ISSUE TITLE
use libtool as archiver will generate libcrypto.a twice

### ISSUE THREAD

**Issue by xiedeacc** [openssl/openssl#25358]
when use libtool as achiver, libcrypto.a will genrated twice, second one will override first one, this made a lot of symbol missed,
two generation with different object files, does it caused libtool can only achive a limited number of object files?

os: macosx Darwin Kernel Version 22.6.0

**Comment by levitte** [comment]
When using `ar`, the default flags are `qc`, which means to quickly append the given object files, and to create the .a file if it doesn't already exist.

If you use `libtool`, you must also make sure to use the appropriate flags that allow incremental addition of the object files.

**Comment by xiedeacc** [comment]
does libtool has such flags? I cannot found corresponding suce flags from https://www.unix.com/man-page/osx/1/libtool/

I believe if openssl build system only trigger libtool just once can fix this problem.

![image](https://github.com/user-attachments/assets/8dde9280-4306-4e24-9dd4-e72a43436d94)

**Comment by levitte** [comment]
From that manual page, it seems that libtool doesn't support incremental buildups of a static library.

We did the split, 'cause there are so many object files that the total command line length was larger than some shells out there can handle (I forget the details).

The manual you're pointing at shows that `ar` is also present, and it has all the necessary flags for incremental archive buildup.  Why not use that instead?

**Comment by xiedeacc** [comment]
because out build system is bazel, bazel only support libtool on macosx, but I found archive all object files if use ar, I know command line length problem, can made this length number larger on macosx? or can tell me how to change this limit, I can patch it just for my self

**Comment by levitte** [comment]
Sure, all you really need to do is to have a (very much) higher number on this line:

https://github.com/openssl/openssl/blob/56502897431d785ab93cdffd6857a667fe2b6d20/Configurations/unix-Makefile.tmpl#L1956

I *think* that's the only spot.

**Comment by xiedeacc** [comment]
it works, thanks very much
