### ISSUE TITLE
Latest releases do not seem to be hosted under https://www.openssl.org/source/

### ISSUE THREAD

**Issue by morganava** [openssl/openssl#25386]
We have some build automation for checking for, downloading, and building new openssl releases in the Tor Browser build system. We are currently using the 3.0.X version. The expected location for sources and shas do not currently exist:

- https://www.openssl.org/source/openssl-3.0.15.tar.gz
- https://www.openssl.org/source/openssl-3.0.15.tar.gz.sha256

Is this intended behaviour? Should we migrate our system to the linked github artifacts instead, or was there some hiccup in the release process?

Thanks!

**Comment by nhorman** [comment]
we're currently in the process of migrating all of our downloads to github only.  the downloads page here:
https://openssl-library.org/source/index.html

Shows links to their new locations

**Comment by morganava** [comment]
Ok, thank you!
