### ISSUE TITLE
[rt.openssl.org #4695] calloc issue in crypto\LPdir_win.c

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2539]
Migrated from [rt.openssl.org#4695](https://rt.openssl.org/Ticket/Display.html?id=4695) (status was 'new')

Requestors:
* gjcoram@gmail.com

From gjcoram@gmail.com on 2016-10-03 07:00:26:
```
Hi -
I had a link failure due to an unresolved external "calloc" when 
trying to build a WindowsCE application using OpenSSL 1.0.2j.

calloc appears in crypto\LPdir_win.c on line 98.

I think one is supposed to use LocalAlloc for WindowsCE instead of 
malloc or calloc.

I didn't get a link error for malloc that appears on line 72 of that 
file (on line 77, that memory is zeroed out), so it seems like a fix 
for me would be to use a malloc and memset instead of calloc.


calloc also appears in ssl\kssl.c, though my application does not use 
functions from that file.  I was puzzled to see calls to "calloc" and 
also "kssl_calloc"

-Geoffrey

```

**Comment by richsalz** [comment]
calloc is part of the C standard library, like malloc and free.  The work-around is fine.

**Comment by levitte** [comment]
Another option is to add this:

``` C
#include <stdlib.h>
```

**Comment by gjcoram** [comment]
In the book "Making Win32 Applications Mobile: Porting to Windows CE" by Nancy Nicolaisen, it says: "Don't use the C runtime functions to allocate memory on CE; doing so will cause unpredictable behavior.

Porting Tip: Eliminate all calls to calloc(), malloc(), and alloc(). Replace these with the Windows CE memory allocation APIs that best suit your needs."

**Comment by gjcoram** [comment]
According to the MSDN reference for Win CE 5, https://msdn.microsoft.com/en-us/library/ms859607.aspx 
calloc() is declared in malloc.h (not in stdlib.h, where malloc() is found).

**Comment by gjcoram** [comment]
So, I just had to do my work-around again. Is there any chance a change can be checked in so I don't have to keep making my own updates?

**Comment by richsalz** [comment]
See PR #4587

**Comment by levitte** [comment]
Hi @gjcoram, we finally got a solution in, freshly approved and merged.  See #4594 for details.

**Comment by gjcoram** [comment]
Thanks - 1.0.2m compiled (and linked!) for me just fine.
