### ISSUE TITLE
Check sk_<name>_push function result

### ISSUE THREAD

**Issue by JohnnySavages** [openssl/openssl#25397]
In all cases listed below, the result of the sk_<name>_push function is not checked. However, when you try to add records with call stack: sk_<name>_push -> OPENSSL_sk_push -> sk_reserve -> OPENSSL_realloc, memory manipulation occurs, which can give an error regardless of the input parameters. Therefore, I think that it is necessary to check the result, but I decided to ask for an opinion before creating PR.

1. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/apps/engine.c#L355
2. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/apps/engine.c#L358
3. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/apps/engine.c#L373
4. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/apps/engine.c#L378
5. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/apps/lib/apps.c#L2493
6. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/apps/lib/apps.c#L2499
7. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/apps/pkcs12.c#L331

**Comment by t8m** [comment]
Yes, this is a minor bug. A PR would be welcome.

**Comment by JohnnySavages** [comment]
What about
1. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/crypto/conf/conf_lib.c#L231
2. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/crypto/conf/conf_mod.c#L547
3. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/crypto/property/property.c#L470

Should we change function return type to int and start checking for it in the calling code?

**Comment by t8m** [comment]
> What about
> 
>     1. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/crypto/conf/conf_lib.c#L231
> 
>     2. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/crypto/conf/conf_mod.c#L547
> 
>     3. https://github.com/openssl/openssl/blob/8af4c02ea952ca387691c4a077c260ba045fe285/crypto/property/property.c#L470
> 
> 
> Should we change function return type to int and start checking for it in the calling code?

Nope. But they should be marked with `(void)` to indicate the result is ignored.

**Comment by JohnnySavages** [comment]
Thanks.
Related PR: https://github.com/openssl/openssl/pull/25412

**Comment by skazaozet** [comment]
What about
https://github.com/openssl/openssl/blob/ad33d62396b7e9db04fdf060481ced394d391688/apps/smime.c#L315
https://github.com/openssl/openssl/blob/ad33d62396b7e9db04fdf060481ced394d391688/apps/smime.c#L321
https://github.com/openssl/openssl/blob/ad33d62396b7e9db04fdf060481ced394d391688/apps/smime.c#L346
https://github.com/openssl/openssl/blob/ad33d62396b7e9db04fdf060481ced394d391688/apps/smime.c#L351
