### ISSUE TITLE
Online documentation return values are wrong for some expressions (missing `>` greater than symbols)

### ISSUE THREAD

**Issue by jay** [openssl/openssl#25407]
It looks like the generator for the online documentation does not properly handle the greater than symbol in some cases.

For example see [SSL_read](https://docs.openssl.org/master/man3/SSL_read/#return-values) and [SSL_write](https://docs.openssl.org/master/man3/SSL_write/#return-values). In both cases a return value of `> 0` is used to indicate that the operation was successful, however the pages are generated in a way that it seems `>` is interpreted as an html `<blockquote>` and so it looks like:

> 0

instead of the correct > 0

![Capture](https://github.com/user-attachments/assets/df7f2b29-4921-4e0d-b9b7-b05fa69444f0)
![Capture2](https://github.com/user-attachments/assets/c645ab4e-0fd7-4fea-a21a-e92fe17d1cf2)
![Capture3](https://github.com/user-attachments/assets/5578cd00-d921-4360-bd87-c8a122717b83)

/cc @bagder

**Comment by andrewkdinh** [comment]
Yes, this is also something I've noticed. I think the way to get around this is to either use `\>` or put it in a code snippet, but I'm not sure which will render well in manpages in CLI as well as on the website.

```markdown
- \> 0
- `> 0`
```

@quarckster do you know?

**Comment by levitte** [comment]
The source is absolutely fine:

https://github.com/openssl/openssl/blob/7845ff7692ac3a2bc1f8bf1eb9fa1ec1119f9b79/doc/man3/SSL_write.pod?plain=1#L151

So I take it that rendering has its faults, indeed

**Comment by levitte** [comment]
Found the issue.  Thank you for reporting!

**Comment by levitte** [comment]
This issue turns out to be how pod2markdown is used.  There's an extra option one can use to have it protect certain characters that are otherwise interpreted by markdown or HTML in a "funny" way.

See https://github.com/openssl/openssl-docs/pull/3 for the fix.

**Comment by quarckster** [comment]
The fix has been merged and deployed. Thank you.
