### ISSUE TITLE
Just received release 3.0.0 message

### ISSUE THREAD

**Issue by BrianInglis** [openssl/openssl#25418]
I have just received a release message for 3.0.0! 
```
Date: Mon, 09 Sep 2024 10:52:24 -0700
From: Dmitry Misharov <notifications@github.com>
```
I have been subscribed to watch and receive your release messages since at least early 2023. 
Any reason why this could occur?

**Comment by levitte** [comment]
3.0.0 was released a few years before 2023:

``` console
$ git show openssl-3.0.0
tag openssl-3.0.0
Tagger: Richard Levitte <richard@levitte.org>
Date:   Tue Sep 7 13:46:40 2021 +0200

OpenSSL 3.0.0 release tag
...
```

**Comment by levitte** [comment]
Ah, you're getting those messages because old releases are currently added to the release timeline here on github: https://github.com/openssl/openssl/releases

**Comment by BrianInglis** [comment]
But not as far back as 3.0.0 unless some early or old releases are hidden?

**Comment by mattcaswell** [comment]
Something happened with the tag I think. I got the same notification and it pointed me at:

https://github.com/openssl/openssl/releases/tag/openssl-3.0.0

@quarckster might have some insight?

**Comment by quarckster** [comment]
I experimented with creating release for old tags. It's a part of the effort to upload old openssl releases to GitHub. After internal discussion I'll make an announcement.
