### ISSUE TITLE
Add SSL_dup capability for QUIC SSL objects

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#25411]
Currently, calling SSL_dup on QUIC SSL objects fails, as the SSL_CONNECTION_FROM_SSL macro has no support for detecting QUIC_CONNECTION types.  It would be very useful to be able to dup a QUIC SSL object to rapidly create multiple connections to an endpoint.  This requires the augmentation of SSL_dup to understand SSL_QUIC_CONNECTION types, and to implement an SSL_method call to duplicate quic SSL objects

**Comment by t8m** [comment]
I suspect this is fairly non-trivial, especially for the semantics. Do we want to be able to dup any SSL object? QUIC stream object probably cannot be duplicated trivially. A QUIC connection could be duplicated trivially if connection is not started yet, however what should be the semantics on already started QUIC connection? We now have also a QUIC listeners with the server support - how that would be handled?

**Comment by nhorman** [comment]
From my read of the RFC it doesn't make sense to duplicate stream SSL objects, as their lifecycle state machine terminates once all data is sent and received.

Duplicating already started connections doesn't make much sense either, as the connection semantics are such that an endpoint can have multiple connections that get negotiated independently.  What we really want is the ability to create an SSL connection object, set all its settings (hostname, alpn, verification mode, etc), and then duplicate that for use in individual calls to SSL_connect, which will be transported over the same underlying dgram BIO.

QUIC listeners for the server is an interesting question.  I could see there being an advantage in creating sematics that allow for duplicated listeners using REUSE_PORT to do application level parallel recieves from a listening socket, but I agree, thats likely non-trivial.

I would suggest limiting this to only allowing duplication of unconnected SSL connection objects.  Duplicating streams and listeners should still trigger an error from SSL_dup, and we can revisit how listeners should work another day.

**Comment by nhorman** [comment]
hmm, yeah.  for quic, I suppose what we might actually want is, as long as its not connected yet, is an SSL_copy type of operation, so we get a unique object for use in establishing a new independent connection on the same dgram BIO

**Comment by vavroch2010** [comment]
@nhorman please come up with a really good reason why we should keep it otherwise will not be implemented

**Comment by nhorman** [comment]
yeah, there isn't a great reason to have this.  Being able to dup connection objects might be a nice to have feature, but its certainly not required for any MVP effort.  closing
