### ISSUE TITLE
https://docs.openssl.org/master/man7/EVP_SIGNATURE-RSA/ web page looks incorrect

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#25433]
https://docs.openssl.org/master/man7/EVP_SIGNATURE-RSA/ web page looks incorrect

https://docs.openssl.org/master/man7/EVP_SIGNATURE-RSA/#algorithm-names section should have much more bullet points than it has now

**Comment by levitte** [comment]
Yeah, it's wrong.  That's being corrected in https://github.com/openssl/openssl/pull/25422
