### ISSUE TITLE
Add provider lookup tracing category to our TRACE api

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#25439]
One area that the TRACE api (available via the enable-trace option) has a gap in it.  Specifically it does not currently trace provider lookup events, which, as a complex syntax is somewhat ripe for enhancement.

The request here is to:
1) Add a new trace category name PROVIDER
2) Augment the provider lookup path to output trace information when parsing provider query strings and illustrating what provider they resolve to.

This is in pursuit of aiding the debugability of creating new providers.

This should be useable during any provider creation, and may benefit from being implemented as a stacked provider (or perhaps a shim between the provider call out functions

**Comment by baentsch** [comment]
> may benefit from being implemented as a stacked provider

Can you please provide a pointer to documentation of this feature (what is a stacked provider, how to register, use, implement it), @nhorman ? 

Second question: Does this pertain only to lookup operations or _any_ provider interaction? The latter would be required to debug into provider-triggered problems. Without this complete tracing capability, a provider will always have to add its own tracing capabilities, like for example in [oqsprovider](https://github.com/open-quantum-safe/oqs-provider/blob/26c18a106cb4b0a29ca5a6472ff5400750c8a117/oqsprov/oqsprov.c#L23-L37).

**Comment by nhorman** [comment]
There is no documentation as such.  by stacked provider the only thing I mean to say is that a provider implementation could be created to act as a pass through to the real provider such that it logged a trace message, then called the underlying provider implementation.  That may be overkill however.

It would be useful if you could enumerate specific events you would like to see logged in pursuit of this

**Comment by baentsch** [comment]
> a provider implementation could be created to act as a pass through to the real provider such that it logged a trace message, then called the underlying provider implementation.

This is a good idea. Just not sure how to implement that, given all providers are treated "equally", i.e. loaded when listed in openssl.conf. This somehow would mean the tracing provider would be the only one listed and it would need to be passed a parameter what other provider it should load in turn. On UNIX'ish systems I'd have an idea how to do that; no idea on Windows, let alone statically built systems, though... Another topic where @levitte may have suggestions (?)

**Comment by nhorman** [comment]
yeah, I think actually creating a "real" tracing provider is probably more effort than its worth.  more likely what I would look to do (my opinion only) would be to, in provider_init, allocate two provider structs when tracing was in use, and repoint all the provider functions to the "tracing" functions, which do nothing but but print a tracing message that is informative, and then calls  the "real" provider function

**Comment by baentsch** [comment]
> yeah, I think actually creating a "real" tracing provider is probably more effort than its worth. more likely what I would look to do (my opinion only) would be to, in provider_init, allocate two provider structs when tracing was in use, and repoint all the provider functions to the "tracing" functions, which do nothing but but print a tracing message that is informative, and then calls the "real" provider function

That'd be very good (and generic). Even better would be output of the return code/value, too. Is there a file containing all these calls so I may try to do this? Or are these calls split into different locations? Arguably much better than putting tracing in all provider(s)...

**Comment by nhorman** [comment]
call assignment is handled in a huge case statement in the provider_init function if you would like to look.  I've been investigating this as well, so i'm happy to lend a hand here

**Comment by baentsch** [comment]
> i'm happy to lend a hand here

That'd be great! My own "spot check" investigation led me to some very sad result, namely that the calls into these provider function(array)s are "all over the place", see e.g., for `gen_settable_params` (and we've got dozens of these functions). Thus, indeed if there'd be a single place (e.g., in init) where they all could be replaced/wrapped with "tracing" variants) in one go would be perfect -- but still, it's _many_ (26 for key management alone; 13 for KEM; 32 for sigs; etc.)

**Comment by nhorman** [comment]
the calls themselves are indeed all over the place, and so we should not implement tracing at the call sites.  instead, what we should do, given that the calls are made through function pointers, is to replace the "real" functions they point to with "shim" functions that do the trace output, then call the providers "real" function pointers.  That way we only have to assign the trace functions once at assignment time (in provider_init) rather than spam trace code throughout the code base
