### ISSUE TITLE
EVP_PKEY_encapsulate/decapsulate documentation error 

### ISSUE THREAD

**Issue by alexzas** [openssl/openssl#25448]
Hi OpenSSL, 
I believe there is a small typo in EVP_PKEY_encapsulate and EVP_PKEY_decapsulate manuals (OSSL versions 3.0-3.4) in the example section.

ctx = EVP_PKEY_CTX_new_from_pkey(libctx, rsa_pub_key, NULL);
if (ctx = NULL)
    /* Error */

The above code makes ctx equal NULL regardless of the value returned by EVP_PKEY_CTX_new_from_pkey.

Relevant link: https://docs.openssl.org/3.4/man3/EVP_PKEY_encapsulate/#examples
Thanks,
Alex

**Comment by mattcaswell** [comment]
Yes, this is a clear error:

https://github.com/openssl/openssl/blob/2a53df6947e195ac08bc04c9d2fec1fed977668f/doc/man3/EVP_PKEY_encapsulate.pod?plain=1#L73-L74

and

https://github.com/openssl/openssl/blob/2a53df6947e195ac08bc04c9d2fec1fed977668f/doc/man3/EVP_PKEY_decapsulate.pod?plain=1#L67-L68

PRs to fix this welcome

**Comment by zimirza** [comment]
I hope it is ok if I create a pull request for this. Seems to be a simple fix.
