### ISSUE TITLE
Openssl1.1.0c is rejected by Apple for using non-public API

### ISSUE THREAD

**Issue by dumganhar** [openssl/openssl#2545]
Hi OpenSSL team,
I'm a developer of Cocos2d-x. Recently, I upgraded `openssl` to `1.1.0c`, one of our game developer submitted his game to App Store, but it was rejected by Apple.  The main reason is:

```
Non-public API usage:

The app references non-public symbols in : _getcontext, _makecontext, _setcontext
```

You could refer this thread https://github.com/cocos2d/cocos2d-x/issues/17257 for more details.

I noticed that `setcontext` is used in `async_posix.h` and `getcontext, makecontext` is used in `async_posix.c`.
`async_posix.h/c` are both in the `openssl-1.1.0c`

Please help. :)

**Comment by dumganhar** [comment]
Should be use `no-async` configuration to disable async functionality for iOS platform?
I'm not familiar with `openssl`, any drawbacks if we disable this?

**Comment by richsalz** [comment]
Yes, if you don't need the async API you will be fine.

**Comment by mattcaswell** [comment]
Yes just use `no-async`. It's only useful if you have an engine capable of offloading crypto work asynchronously (which typically means specialist hardware). If you're not using an engine then you're not going to notice it not being there.

**Comment by dumganhar** [comment]
@richsalz , @mattcaswell , thank you. :)
