### ISSUE TITLE
chacha20 is broken on linux/powerpc64/power10 (big-endian) host

### ISSUE THREAD

**Issue by pmur** [openssl/openssl#25451]
This was first noticed as garbled text, and other strange ssh errors when using ssh to connect to power10 powerpc64 host running openssh using the chacha20-poly1305 cipher.

This can be reproduced by running the unit tests on the master branch on a power10 be host, e.g `./Configure linux-ppc64 && make && make test`.

**Comment by t8m** [comment]
Could you please help with this issue? We unfortunately do not have such hardware and the linux-ppc64 platform is currently unadopted -  https://openssl-library.org/policies/platforms/

Could you please try to isolate when this regression happened (i.e., by git bisect) ?

**Comment by pmur** [comment]
I'll investigate. Admittedly, this is a rare configuration. I use it to test go on BE on power10 using debian unstable.

I am guessing the power10 implementation never worked on BE as it was explicitly disabled for AIX/darwin, there are only two potential commits 7e1f3ffcc5bc15fb9a12b9e3bb202f544c6ed5aa or f596bbe4da779b56eea34d96168b557d78e1149a.

I changed the macro to test for `IS_LITTLE_ENDIAN` instead of the contrived AIX/darwin test, and all tests pass. I can post that patch for review.

**Comment by pmur** [comment]
I did some debugging and fixed the issue with the BE implementation. It appears to be a typo in some of the BE specific permutes. I think this is also a trivial fix.

**Comment by t8m** [comment]
@erichte-ibm @naynajain @sanumesh are possible other reviewers?
