### ISSUE TITLE
bad_certificate instead of illegal_parameter alert in compressed certificate

### ISSUE THREAD

**Issue by GeorgePantelakis** [openssl/openssl#25469]
When a compressed certificate is used we send the following compressed certificate message:

struct {
CertificateCompressionAlgorithm algorithm;
uint24 uncompressed_length;
opaque compressed_certificate_message<1..2^24-1>;
} CompressedCertificate;

When we are changing the `CertificateCompressionAlgorithm` section to some algorithm that OpenSSL doesn't know we get back a bad_certificate alert instead of an illegal_parameter alert

**Comment by GeorgePantelakis** [comment]
For testing you can use https://github.com/tlsfuzzer/tlsfuzzer/blob/master/scripts/test-tls13-client-certificate-compression.py against and OpenSSL server.

**Comment by mattcaswell** [comment]
Do you have an RFC reference for the correct alert to use here?

**Comment by mattcaswell** [comment]
Hmm...I suppose you really mean that you are setting it to some algorithm that was not offered in the ClientHello? Which would suggest illegal parameter would be appropriate.

**Comment by GeorgePantelakis** [comment]
Exactly and since this behavior was not overridden by RFC 8879 we should fall to the default/previous behavior which is illegal parameter.

**Comment by mattcaswell** [comment]
Probably requires some changes to be made here:

https://github.com/openssl/openssl/blob/1f0cb850473048eef5dc597d8cd42dd7c3cf5a5f/ssl/statem/statem_lib.c#L2831-L2900

The are a number of bad_certificate alerts sent there which look suspect. We need to compare against the RFC for these.

**Comment by tmshort** [comment]
Closing due to #25845
