### ISSUE TITLE
SOURCE_DATE_EPOCH Value of 0 Does Not Override Date

### ISSUE THREAD

**Issue by ajortega8** [openssl/openssl#25475]
I discovered this on OpenSSL version 1.1.1d, but it is present in the latest master branch as well. The issue is that if you use a SOURCE_DATE_EPOCH value of 0, the test in util/mkbuildinf.pl will always grab the current time. Setting SOURCE_DATE_EPOCH to a value of 0 is useful for other projects that use it to disable certain timestamp inclusions in their compiled binaries to generate reproducible builds.

This issue was introduced by this commit:

https://github.com/openssl/openssl/commit/8a8d9e190533ee41e8b231b18c7837f98f1ae231#diff-60728b88cb2b16f42e41cee0c1ca3c632f2f951619d6b26dac54d2bd38e39958

Something like this could work:

```
my $source_date_epoch = $ENV{'SOURCE_DATE_EPOCH'};

my $date="";
if (defined $source_date_epoch){
    $date = gmtime($source_date_epoch);
}
else{
    $date = gmtime(time());
}
$date .= " UTC";
```

**Comment by levitte** [comment]
Have a look at #25699, it should do it right
