### ISSUE TITLE
HASH is mismatching for larger size of file

### ISSUE THREAD

**Issue by Ashok-d-attikatti** [openssl/openssl#25487]
Hello Team,

I have attached the file here that is the HASH generator for the SHA
[sha.txt](https://github.com/user-attachments/files/16795189/sha.txt)

Could you give me a suggestion for this code?

We are checking the hardware crypto accelerator using the /dev/crypto, and the code is working as expected for the lower file size.
If it is more than the 20/30MB file our system will hang because it cannot handle the large memory at a time. So we made changes in the code as below in the code
[sha1.txt](https://github.com/user-attachments/files/16795099/sha1.txt)
but in this code, we are not able to get the HASH value as we expected.

Can anyone suggest a different way to handle the whole data?

Thanks,
Ashoka A D

**Comment by tom-cosgrove-arm** [comment]
This feels like it should be raised as a discussion as it is a question rather than an issue (problem) with OpenSSL

**Comment by Ashok-d-attikatti** [comment]
This is not an issue with the OpenSSL
The issue with my test application. 
I tried some other way to get the HASH value using the attached applications but could not resolve this. 

My question is how the openssl is handling the whole file for generating the HASH using devcrypto engine.?

**Comment by mattcaswell** [comment]
This question needs to be asked in some other forum. This is not a question or issue with OpenSSL.
