### ISSUE TITLE
Windows DLL and no-comp configuration option adds but hides some symbols

### ISSUE THREAD

**Issue by schlenk** [openssl/openssl#255]
When openssl is configured with `no-comp` to disable compression, there are still some default dummy functions compiled into the library. (`SSL_COMP_get_name()`, `SSL_get_current_compression()`, `SSL_get_current_expansion()`), those just return dummy results.

Those symbols are then removed from the public interface of the DLL via a `.def` file entry. This is a totally different approach than used with many other optional (like no-ssl3), which are simple not defined at all.

This is a problem for building pyca/cryptography#1675. Either it works with a static openssl library or with a dynamic one, but supporting both is unecessarily hard.

It would be nice if either those dummy symbols are not hidden via .def or if the functions are not compiled into the library in the first place, like it is done in most other cases when functionality can be configured out of the library.

**Comment by mattcaswell** [comment]
This seems to be fixed already in 1.1.0, but remains an issue in 1.0.2.

**Comment by mattcaswell** [comment]
Fixed by a79a40a9fe.
