### ISSUE TITLE
URGENT: Getting Spammed by openssl release notifications emails

### ISSUE THREAD

**Issue by AachoLoya** [openssl/openssl#25506]
Probably something wrong with the build system. Cause I'm getting a new openssl release notification email (from github) every second. Each email is about separate build/version. Received 100+ emails so far!

**Comment by martinscholz83** [comment]
Yeah, pls check what is going wrong here.

**Comment by debohman** [comment]
Github should have some sort of limit in place to prevent this sort of thing from happening.

**Comment by herbetom** [comment]
Looks to me that they created github releases for all the old releases. But it is indeed not a nice user experience to receive ~231 emails over this. But at least now that it's done that should be it.

**Comment by Sahil12524** [comment]
Suddenly 99+ emails here damn
![Screenshot_20240921_191656_Gmail](https://github.com/user-attachments/assets/ae61fb0d-e8fb-4ee5-b701-26abd8befcd4)
![Screenshot_20240921_191706_Gmail](https://github.com/user-attachments/assets/96cf601f-1a7e-484e-884b-530379383176)

**Comment by gh0sti** [comment]
For now I turned off notifications for updates and just went to comments and @" stinks that this happens sometimes on GitHub.

**Comment by paulidale** [comment]
Any ideas @openssl/foundation-members @openssl/corporation-members  ?

**Comment by t-j-h** [comment]
It is an unfortunate side effect of all the older releases having been made available on github.
It appears it was not anticipated that notifications would be sent out when this was done.

It is a one-time event as part of transitioning CDN providers and to have everything consistently accessible via github.

All releases the project has ever made are now accessible at https://github.com/openssl/openssl/releases

I apologise for the spam on behalf of the team (but I'm also not sure it was avoidable for getting all releases available).

**Comment by t-j-h** [comment]
Closing

**Comment by paulidale** [comment]
Thanks for the explanation.  I figured it was something mundane like this, but if it weren't a heads up was in order.
