### ISSUE TITLE
ManPage Return value of RSA_generate_key_ex not documented

### ISSUE THREAD

**Issue by koeppea** [openssl/openssl#2552]
Hello,

the current man page for **RSA_generate_key_ex** which is meant to be the successor of the function  **RSA_generate_key** doesn't explain the meaning of the return value of the function **RSA_generate_key_ex**:
```
RETURN VALUE

If key generation fails, RSA_generate_key() returns NULL.

The error codes can be obtained by ERR_get_error(3).
```
Only the meaning of the return value of the pre-decessor function is detailed.

**Comment by richsalz** [comment]
fixed on master and 1.1.0, thanks for reporting.
