### ISSUE TITLE
Broken links to www.openssl.org in source files

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#25543]
The website re-org broke many links in files in the releases and repository.  For example, the CODE_OF_CONDUCT, ACKNOWLEDGEMENTS, etc.

**Comment by quarckster** [comment]
I fixed the redirect for https://www.openssl.org/community/conduct.html, https://www.openssl.org/community/thanks.html is on the way. I also checked all links in the master branch with this script:

```
for link in $(grep -hRoE 'https://www\.openssl\.org\/[^>")]+' . | sort | uniq -u); do curl -LsSI > /dev/null $link --fail || echo $link ; done
```

and found only https://www.openssl.org/source/OCB-patent-grant-OpenSSL.pdf which will be fixed too
