### ISSUE TITLE
Undefined behavior in openssl-3.0.15/crypto/bn/rsaz_exp_x2.c:500:16

### ISSUE THREAD

**Issue by aljohnston112** [openssl/openssl#25554]
>>> Messages generated by process 189594 on 2024-09-27 02:06:59 -00 for package dev-libs/openssl-3.0.15:

QA: configure
Appending non-library to LIBS (-Wl,--push-state,--as-needed,-latomic,--pop-state); Other linker flags should be passed via LDFLAGS
QA: other
QA Notice: Package triggers severe warnings which indicate that it
           may exhibit random runtime failures.
../openssl-3.0.15/crypto/bn/rsaz_exp_x2.c:500:16: warning: iteration 19 invokes undefined behavior [-Waggressive-loop-optimizations]
Please do not file a Gentoo bug and instead report the above QA
issues directly to the upstream developers of this software.
Homepage: https://openssl-library.org/

**Comment by paulidale** [comment]
I'm not seeing an error there.  Can you elucidate further?  Have you verified that this isn't a false positive?
