### ISSUE TITLE
SSL_CTX_load_verify_locations() overrides default CAdir, but not default CAfile, essentially preventing distributions from using CAdir

### ISSUE THREAD

**Issue by neverpanic** [openssl/openssl#25551]
If I create an `SSL_CTX` and call `SSL_CTX_set_default_verify_paths()` to load the system trust store, followed by `SSL_CTX_load_verify_locations(ctx, additional_ca, NULL)`, it depends on whether the system trust store is in a CAfile (`certs.pem`), or a CAdir (`certs/*`) whether the system trust store is considered in the following TLS connection.

This is counter-intuitive. Either the call to `SSL_CTX_load_verify_locations()` should remove *all* previously trusted certificates, or it should remove none. It should not selectively remove just the ones in a CAdir.

In practice, nobody seems to be aware of this counter-intuitive behavior. This means there are many applications out there that load an additional trusted root CA by calling `SSL_CTX_load_verify_locations(ctx, additional_ca, NULL)`, but this breaks verification against the system trust store if the system trust store uses a CAdir. This essentially prevents distributions from using a CAdir, which would be helpful because it offers faster startup times for applications using OpenSSL.

A reproducer is available at https://github.com/neverpanic/openssl-cadir-vs-cafile-weirdness/. It's a copy of `demos/sslecho` with modifications to `configure_client_context()`. To see the behavior in effect, clone the repo, run `make`, then run `./reproduce.sh`. The sslecho server is started with a certificate issued by `ca.pem`, which is both in `ca-trust/certs` and `ca-trust/certs-with-ca.pem`. When the client attempts to load an additional CA file using `SSL_CTX_load_verify_locations()` (i.e., if the `ADDITIONAL_CA` env variable is set), it forgets the certificates in `SSL_CERT_DIR`, but not those in `SSL_CERT_FILE`.

**Comment by neverpanic** [comment]
Note: I tested this against current master, which was 4f899849ceec7cd8e45da9aa1802df782cf80202 at the time.

**Comment by t8m** [comment]
I disagree this should be treated as a bug. IMO if the behavior is changed in a PR such change should go only into the master branch.

**Comment by t8m** [comment]
**OTC: Bug or feature?**

**Comment by beldmit** [comment]
For me it looks like smth counter intuitive.

**Comment by t8m** [comment]
Counter-intuitive, yes, bug, very much debatable. It certainly has potential to break things if fixed.

**Comment by beldmit** [comment]
I'm not sure about breaking things. If an extra trusted cert is taken into account when we have the trusted certs in a bundle, why it should not be accepted having the trusted certs in the folder with symlinks?

**Comment by t8m** [comment]
Let's say you  already have a system bundle in CAdir but you DON'T want the system bundle to be in effect but you load it anyway during application initialization and then you depend on the fact that SSL_CTX_load_verify_locations() overrides it.

We would potentially even open a security hole by changing the behavior.

I know this scenario is quite contrived but not unimaginable. For that reason I am against backporting it to stable releases.

**Comment by beldmit** [comment]
I agree it's worth discussing

**Comment by beldmit** [comment]
For the record
I don't insist on backporting these changes to all 3.x series. 
On the other hand I disagree with your scenario because the current behavior is not only counterintuitive but also undocumented and systems shouldn't rely on it

**Comment by t8m** [comment]
Shouldn't doesn't mean that don't. Also we have pretty many undocumented behaviors that systems rely on.

**Comment by neverpanic** [comment]
> Let's say you already have a system bundle in CAdir but you DON'T want the system bundle to be in effect but you load it anyway during application initialization and then you depend on the fact that SSL_CTX_load_verify_locations() overrides it.
> 
> We would potentially even open a security hole by changing the behavior.

I agree that this is a concern. However, in this case we should also consider the behavior that existing CAs in a system CAfile are not removed by a subsequent `SSL_CTX_load_verify_locations()` as the same security bug, no?

To me, there's really no good explanation for the behavior difference between a CAfile and a CAdir here.

Let's say a distribution currently uses CAdir, but for some reason they are switching to CAfile. Applications that use `SSL_CTX_load_verify_locations()` would suddenly start trusting the system CAs, even though the set of trusted system CAs hasn't changed, just their storage format. If that's a vulnerability, where would it be? In the ca-certificates package that switched to CAfile? I doubt you'd find good arguments for that. That leaves us to conclude that the vulnerability — if it is one — must be in OpenSSL, in which case OpenSSL should be changed to discard CAs from the system store when `SSL_CTX_load_verify_locations()` is called.

This leaves two options:
- Either consider the fact that `SSL_CTX_load_verify_locations()` keeps the system CAs if loaded from a file as a bug, possibly even vulnerability, and fix it, breaking many programs that have been relying on this behavior, or
- Consider the fact that `SSL_CTX_load_verify_locations()` does not keep the system CAs in a CAdir as a bug.

I don't think "it's been this way" is a good reason to stick with this broken behavior.

**Comment by beldmit** [comment]
** OTC opinion (non-quorate) **
1. The behavior should be tested in 4 combinations and documented
2. The discussion is delayed to the quorate meeting, @openssl/otc to read the issue and make the opinion

**Comment by petrovr** [comment]
So, OpenSSL provides more than one X.509 lookup methods: by file, by directory, and recently by store. Also program could use them with different arguments . For instance PKIX-SSH uses "system" or "user" configurations. 

- by file:
This method is quite specific. It preload all certificates and crls on initialisation time.
- by dir:
This method load certificates or crls on requests.
- by store:
Similar to by dir.

Also do not forget run-time logic. OpenSSL program code load once certificate but clrs are reloaded at run-time. This is evolution and I cannot remember when was implemented. As expected functionality for reload is not applicable for "by file" method.

With other words methods are not similar.

**Comment by petrovr** [comment]
When a x.509 lookup method is added program code should remove errors. PKIX-SSH code has following comment : "NOTE: After X509_LOOKUP_{add_dir|load_file} calls we must call ERR_clear_error() otherwise if first call of control function fail then second call fail too! "
It is related to OpenSSL "aggregate" functions that set lookup path and directory. If I remember well verification may fail if OpenSSL error queue is not empty.

So, PKIX-SSH code does not use "aggregate" functions and clear errors after each lookup addition.

**Comment by petrovr** [comment]
About test case. It seems to me logic is not correct.

test1 uses empty  file for default store. It seems to me code ignores errors when is initialised default store. So, empty file does not add certificates and then load is at run time "by dir".

test2*: use file with correct(!!!) ca. root ca is preloaded and "by dir" is not used.

test3*: hmm, it use file with"broken" ca. root ca is preloaded and "by dir" is not used as certificate is found in store. It seem to me program code cannot construct certificate chain and this is reason test to fail.  

With other words test3 does not show error in "aggregate" function or use of x509 lookup methods.

**Comment by neverpanic** [comment]
The test does indeed not fail if I repeat it with a certificate that uses a different subject.

In other words, this is broken:
```
[root@8fa6d399b75e openssl-cadir-vs-cafile-weirdness]# openssl x509 -noout -in ca.pem -subject
subject=O=Example CA
[root@8fa6d399b75e openssl-cadir-vs-cafile-weirdness]# openssl x509 -noout -in otherca.pem -subject
subject=O=Example CA
```

But this works:
```
[root@8fa6d399b75e openssl-cadir-vs-cafile-weirdness]# openssl x509 -noout -in ca.pem -subject
subject=O=Example CA
[root@8fa6d399b75e openssl-cadir-vs-cafile-weirdness]# openssl x509 -noout -in otherca.pem -subject
subject=O=MyOther CA
```

I guess that actually makes this a non-issue, then, and the test should just not be using the same subject for the CA.

**Comment by t8m** [comment]
Closing the issue as there is no _real_ override apart from being the artifact of how CA dir works.
