### ISSUE TITLE
Unable to load fips provider in second load getting init fail error

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#25553]
### Discussed in https://github.com/openssl/openssl/discussions/25466

<div type='discussions-op-text'>

<sup>Originally posted by **absrivas-in** September 16, 2024</sup>
We are encountering an error while loading the` fips.so` module in a specific use case. The issue arises when using OpenSSL 3.0.15.
We are building a static library (SDK) that contains SDK-related APIs, along with the object files of OpenSSL's libcrypto.a and libssl.a. This allows us to deliver the SDK without including the `libcrypto.a `and `libssl.a` binaries.

The SDK provides a public `load_fips` API that loads the OpenSSL FIPS provider.

**Use Case:**
1. The consumer calls the `load_fips` API from the main process.
2. The consumer then calls the `load_fips` API again, but this time from their own shared library, which is loaded using `dlopen`.

During the second attempt to load fips.so, an error occurs at this line:
[provider_seeding.c#L30](https://github.com/openssl/openssl/blob/openssl-3.0/providers/common/provider_seeding.c#L30)
The error is triggered by a call from:
[fipsprov.c#L551](https://github.com/openssl/openssl/blob/openssl-3.0/providers/fips/fipsprov.c#L551)

**Reason for Failure:** 

During the first FIPS provider load, a global variable [c_get_entropy](https://github.com/openssl/openssl/blob/master/providers/common/provider_seeding.c#L14C34-L14C47) is assigned a function pointer. 
However, when attempting to load the FIPS provider a second time, the function pointer does not match, causing the initialization to fail (`init error`). This behavior is caused by the following sanity check:

`#define set_func(c, f) if (c == NULL) c = f; else if (c != f) return 0;`
As a result, the second attempt to load the FIPS provider fails with an error.

**Sample Logs:**

> Using OpenSSL libs from: openssl/lib/ossl-modules
> Loading base provider...
> Loading fips provider...
> All providers have been loaded!
> call_load_crypto 1
> 
> _init_vtabel
> Using OpenSSL libs from: openssl/lib/ossl-modules
> Loading base provider...
> Loading fips provider...
> Loading fips provider failed! => FAIL
> - Detailed error: init fail
> call_load_ssl 0

Please provide assistance in resolving this issue. The attached sample code can be used to reproduce the problem.
[test5.tar.gz](https://github.com/user-attachments/files/17006212/test5.tar.gz)

</div>

**Comment by mattcaswell** [comment]
The real feature request here is for the fips.so provider module to support multiple different libcrypto instances calling it at the same time. At the moment it detects this scenario and errors out. The real issue is that the callbacks provided by core are stored in global variables. If they were stored in the provider context then I guess the problem goes away. It's not clear whether we always have access to the provider context everywhere that we need to make a call to a callback.

**Comment by nhorman** [comment]
Just to add some historical context, The null check here was added in 7b9f02798f68d9108623f5879f3fc73c06f9a2c7, which explicitly notes in the comments that we don't support this sort of scenario.

It would seem that fully supporting this scenario would imply not just fixing c_get_entropy (moving it from a global to a per-provider context), but also several other functions (c_cleanup_entropy, c_get_nonce, and c_cleanup_nonce)

**Comment by paulidale** [comment]
There are a lot more callbacks than just the entropy ones.  `c_CRYPTO_malloc` and similar have exactly the same problem and they definitely **do not have** the provider context available.  Adding such would be extremely invasive.

**Comment by mattcaswell** [comment]
> There are a lot more callbacks than just the entropy ones. c_CRYPTO_malloc and similar have exactly the same problem and they definitely do not have the provider context available. Adding such would be extremely invasive.

Right. Which I guess is why this has never been done before. It's a hard problem to solve.

**Comment by nhorman** [comment]
So I guess the question here, is whats the risk/reward balance here? 

The desire to load multiple copies of fips.so seems clear, but implementing this seems seriously invasive, including but not limited to:
1) Moving all global function pointers (about 24) to a context structure
2) Modifying global functions in fips.so to use them in the context structure
3) Potentially modifying the global functions (like CRYPTO_malloc) to accept a context parameter so the functions can be fetched.

So I suppose the first question to ask is: Do we want to commit to this?  I assume that is a BAC/TAC decision when those are established (hopefully october for at least part of it), before then is it an OTC choice?

If we move forward on it, it seems like we need a feature branch for this

**Comment by paulidale** [comment]
IMO, this change would be insanely invasive and very risky.

**Comment by mattcaswell** [comment]
> The desire to load multiple copies of fips.so seems clear,

To be clear here we are talking about multiple provider instances from a single fips.so. Even more specifically we are talking about where those multiple instances are coming from different instances of libcrypto. There should be no problem with having multiple fips provider instances from a single libcrypto instance (i.e. via multiple libctxs). So this is quite a corner case (but we do see reports like this from time-to-time, so it does happen in practice).

**Comment by mattcaswell** [comment]
> or we would have to make the context stored in a thread-local storage

Surely for this to work, you would have to set the thread-local storage at every entry point into the provider? So this still sounds very invasive?

> problematic in no-threads builds or on platforms not having thread-local storage.

thread-local storage in no-threads builds is just a global variable isn't it?

**Comment by paulidale** [comment]
>… or we would have to make the context stored in a thread-local storage, which is IMO workable, but problematic in no-threads builds or on platforms not having thread-local storage.

Which would also be _extremely_ invasive.  Every public API that could potentially make use of any of the up calls however indirectly (i.e. pretty much all of them) would need to set the thread local (and probably restore it after).

Happy to discuss at OTC but honestly, this is too invasive.

**Comment by t8m** [comment]
Yeah, using TLS would be also very invasive, but at least it would not require adding so many additional core callbacks.

**Comment by nhorman** [comment]
Just to ask the question, these functions, are they likely to be invariant between contexts?  I.e. would we expect c_CRYPTO_malloc to point to the same function for every context within an application?  If so, would it be possible to just eliminate the failure case of the NULL check on these functions?  The sanity check in https://github.com/openssl/openssl/commit/7b9f02798f68d9108623f5879f3fc73c06f9a2c7 says no if there are different libcrypto versions, but could we require identical versions instead?  If we could check and fail on that, then we could just allow rewriting of the pointers, knowing that the write would update to the same pointer.

Still feels too invasive to me, but might be worth considering

**Comment by t8m** [comment]
The pointers would be different as different instances of libcrypto would have different CRYPTO_malloc functions. Of course they might be pretty much functionally identical but they will have different global data associated - such as the error queues or the malloc callbacks (if they are set).

**Comment by paulidale** [comment]
The use case is two different versions of libcrypto loading the same FIPS provider, so they will be different.  The reason there are two different libcryptos is due to used libraries also including libcrypto -- we can't force the versions to be the same.

The workaround I suggested in the discussion was to make multiple copies of fips.so and have each libcrypto load a different one.  This isn't too onerous IMO and avoids us making significant and dangerous changes.

**Comment by mattcaswell** [comment]
> The pointers would be different as different instances of libcrypto would have different CRYPTO_malloc functions. Of course they might be pretty much functionally identical but they will have different global data associated - such as the error queues or the malloc callbacks (if they are set).

The global data here is critical. Even if the implementations of the functions are identical using the wrong one is asking for trouble (e.g. imagine trying to take a lock from one of those callbacks - but the lock has already been cleaned up because you ended up in the "wrong" libcrypto instance).

**Comment by paulidale** [comment]
OTC: too invasive to add this feature.
