### ISSUE TITLE
Potential memory leak in PKCS7_signatureVerify

### ISSUE THREAD

**Issue by nielsdos** [openssl/openssl#25594]
Hello. I'm working on a static analysis tool to detect incomplete error handling code.

My tool reported the following.

The following code:

https://github.com/openssl/openssl/blob/c262cc0c0444f617387adac3ed4cad9f05f9c526/crypto/pkcs7/pk7_doit.c#L1110-L1111

Jumps to an error block when `EVP_VerifyUpdate` fails. This error block does not free `abuf` and `abuf` does not seem to escape the function as far as I understand. In the success path the `abuf` memory is freed, just not in the error path.

I understand this is quite an unlikely bug.
I could also be wrong because my results are based on static analysis even though I manually read the code as well.

Thanks in advance

**Comment by t8m** [comment]
Yeah, your analysis is right. This is a bug.

**Comment by nielsdos** [comment]
Thank you for confirming.
I submitted a PR in https://github.com/openssl/openssl/pull/25596
