### ISSUE TITLE
1.0.2a can't be compiled under msys2

### ISSUE THREAD

**Issue by CompileMaster** [openssl/openssl#256]
make[4]: Entering directory '/c/deps/openssl-1.0.2a'
libcrypto.a(aesni-sha256-x86_64.o):fake:(.pdata+0x0)▒▒▒ԡ▒.LSEH_begin_aesni_cbc_s                     ha256_enc_xop▒▒δ▒▒▒▒▒▒▒▒▒
libcrypto.a(aesni-sha256-x86_64.o):fake:(.pdata+0x4)▒▒▒ԡ▒.LSEH_end_aesni_cbc_sha                     256_enc_xop▒▒δ▒▒▒▒▒▒▒▒▒
libcrypto.a(aesni-sha256-x86_64.o):fake:(.pdata+0x8)▒▒▒ԡ▒.LSEH_info_aesni_cbc_sh                     a256_enc_xop▒▒δ▒▒▒▒▒▒▒▒▒
libcrypto.a(aesni-sha256-x86_64.o):fake:(.pdata+0xc)▒▒▒ԡ▒.LSEH_begin_aesni_cbc_s                     ha256_enc_avx▒▒δ▒▒▒▒▒▒▒▒▒
libcrypto.a(aesni-sha256-x86_64.o):fake:(.pdata+0x10)▒▒▒ԡ▒.LSEH_end_aesni_cbc_sh                     a256_enc_avx▒▒δ▒▒▒▒▒▒▒▒▒
libcrypto.a(aesni-sha256-x86_64.o):fake:(.pdata+0x14)▒▒▒ԡ▒.LSEH_info_aesni_cbc_s                     ha256_enc_avx▒▒δ▒▒▒▒▒▒▒▒▒
collect2.exe: error: ld returned 1 exit status
Makefile.shared:279: recipe for target 'link_a.cygwin' failed
make[4]: *** [link_a.cygwin] Error 1
make[4]: Leaving directory '/c/deps/openssl-1.0.2a'
Makefile:349: recipe for target 'do_cygwin-shared' failed
make[3]: *** [do_cygwin-shared] Error 2
make[3]: Leaving directory '/c/deps/openssl-1.0.2a'
Makefile:302: recipe for target 'libcrypto.dll.a' failed
make[2]: *** [libcrypto.dll.a] Error 2
make[2]: Leaving directory '/c/deps/openssl-1.0.2a'
Makefile:109: recipe for target 'shared' failed
make[1]: *** [shared] Error 2
make[1]: Leaving directory '/c/deps/openssl-1.0.2a/crypto'
Makefile:279: recipe for target 'build_crypto' failed
make: *** [build_crypto] Error 1

**Comment by CurrencyMaster** [comment]
1.0.1m can be compiled success under msys2.

**Comment by Lyoko-Jeremie** [comment]
my have a similar one in 1.0.2a.

use msys2
$ cd d:/Code/openssl-1.0.2a
and
$ perl Configure mingw64 no-shared --prefix=/d/Code/openssl-1.0.2a/build-x64-PT-seh
and 
$ mingw32-make depend

then 

Administrator@Jeremie-Win7 MSYS /d/Code/openssl-1.0.2a
$ mingw32-make
making all in crypto...
mingw32-make[1]: Entering directory 'D:/Code/openssl-1.0.2a/crypto'
D:/Code/msys64/usr/bin/perl.exe ../util/mkbuildinf.pl "gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -O3 -Wall -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" "mingw64" >buildinf.h
g++    -c -o cryptlib.o cryptlib.c
In file included from cryptlib.c:117:0:
cryptlib.h:65:19: fatal error: e_os.h: No such file or directory
 # include "e_os.h"
                   ^
compilation terminated.
<builtin>: recipe for target 'cryptlib.o' failed
mingw32-make[1]: *** [cryptlib.o] Error 1
mingw32-make[1]: Leaving directory 'D:/Code/openssl-1.0.2a/crypto'
makefile:279: recipe for target 'build_crypto' failed
mingw32-make: *** [build_crypto] Error 1


so i copy the "e_os.h" file from openssl-1.0.2a root directory to "crypto" directory
run it again
i get a new error


Administrator@Jeremie-Win7 MSYS /d/Code/openssl-1.0.2a
$ mingw32-make
making all in crypto...
mingw32-make[1]: Entering directory 'D:/Code/openssl-1.0.2a/crypto'
g++    -c -o cryptlib.o cryptlib.c
In file included from cryptlib.h:65:0,
                 from cryptlib.c:117:
e_os.h:62:34: fatal error: openssl/opensslconf.h: No such file or directory
 # include <openssl/opensslconf.h>
                                  ^
compilation terminated.
<builtin>: recipe for target 'cryptlib.o' failed
mingw32-make[1]: *** [cryptlib.o] Error 1
mingw32-make[1]: Leaving directory 'D:/Code/openssl-1.0.2a/crypto'
makefile:279: recipe for target 'build_crypto' failed
mingw32-make: *** [build_crypto] Error 1


i see the "opensslconf.h" file in the "crypto" directory, but not a "openssl" directory in "crypto" directory.
so ,i create "openssl" directory and copy it again
but did not use



now , i try to compile 1.0.1

**Comment by Lyoko-Jeremie** [comment]
1.0.1m has the same error
this time ,i found the compiler's directory "opt\include\" have the directory "openssl" and file opensslconf.h and e_os.h
i think the msys2 cannot find the include path.
so , i use this bat to start msys2 to point to include path.

@SET PATH=d:\Code\C++\x86_64-4.9.2-release-posix-seh-rt_v4-rev2\mingw64\bin\;D:\Code\Perl64\site\bin;D:\Code\Perl64\bin
@SET CPLUS_INCLUDE_PATH=d:\Code\C++\x86_64-4.9.2-release-posix-seh-rt_v4-rev2\mingw64\opt;d:\Code\C++\x86_64-4.9.2-release-posix-seh-rt_v4-rev2\mingw64\opt\include;d:\Code\openssl-1.0.2a\openssl-1.0.2a
cd /d d:\
cd d:\Code\msys64\
msys2_shell.bat
pause

![2015-05-17 02_00_52-](https://cloud.githubusercontent.com/assets/6566869/7667399/9b481df2-fc38-11e4-9966-91e4a2734e83.png)


try again.
its solution!
BUT, 1.0.1m and 1.0.2a have a new same error.

Administrator@Jeremie-Win7 MSYS /d/Code/openssl-1.0.2a/openssl-1.0.2a
$ mingw32-make
making all in crypto...
mingw32-make[1]: Entering directory 'D:/Code/openssl-1.0.2a/openssl-1.0.2a/crypto'
g++    -c -o cryptlib.o cryptlib.c
cryptlib.c: In function 'void CRYPTO_THREADID_set_pointer(CRYPTO_THREADID*, void*)':
cryptlib.c:437:40: error: invalid conversion from 'void*' to 'unsigned char*' [-fpermissive]
     unsigned char *dest = (void *)&id->val;
                                        ^
cryptlib.c:447:38: error: cast from 'void*' to 'long unsigned int' loses precision [-fpermissive]
         id->val = (unsigned long)id->ptr;
                                      ^
cryptlib.c:463:49: error: invalid conversion from 'void*' to 'const unsigned char*' [-fpermissive]
         const unsigned char *src = (void *)&id->ptr;
                                                 ^
cryptlib.c: In function 'int OPENSSL_isservice()':
cryptlib.c:820:74: error: invalid conversion from 'HANDLE {aka void*}' to 'HMODULE {aka HINSTANCE__*}' [-fpermissive]
             _OPENSSL_isservice.p = GetProcAddress(h, "_OPENSSL_isservice");
                                                                          ^
In file included from D:/Code/C++/x86_64-4.9.2-release-posix-seh-rt_v4-rev2/mingw64/x86_64-w64-mingw32/include/winbase.h:24:0,
                 from D:/Code/C++/x86_64-4.9.2-release-posix-seh-rt_v4-rev2/mingw64/x86_64-w64-mingw32/include/windows.h:70,
                 from D:/Code/C++/x86_64-4.9.2-release-posix-seh-rt_v4-rev2/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from d:\Code\openssl-1.0.2a\openssl-1.0.2a/e_os.h:288,
                 from cryptlib.h:65,
                 from cryptlib.c:117:
D:/Code/C++/x86_64-4.9.2-release-posix-seh-rt_v4-rev2/mingw64/x86_64-w64-mingw32/include/libloaderapi.h:135:29: note: initializing argument 1 of 'INT_PTR (* GetProcAddress(HMODULE, LPCSTR))()'
   WINBASEAPI FARPROC WINAPI GetProcAddress (HMODULE hModule, LPCSTR lpProcName);
                             ^
cryptlib.c:820:74: error: invalid conversion from 'FARPROC {aka long long int (*)()}' to 'void*' [-fpermissive]
             _OPENSSL_isservice.p = GetProcAddress(h, "_OPENSSL_isservice");
                                                                          ^
cryptlib.c: In function 'int CRYPTO_memcmp(const void*, const void*, size_t)':
cryptlib.c:1008:30: error: invalid conversion from 'const void*' to 'const unsigned char*' [-fpermissive]
     const unsigned char *a = in_a;
                              ^
cryptlib.c:1009:30: error: invalid conversion from 'const void*' to 'const unsigned char*' [-fpermissive]
     const unsigned char *b = in_b;
                              ^
<builtin>: recipe for target 'cryptlib.o' failed
mingw32-make[1]: *** [cryptlib.o] Error 1
mingw32-make[1]: Leaving directory 'D:/Code/openssl-1.0.2a/openssl-1.0.2a/crypto'
makefile:279: recipe for target 'build_crypto' failed
mingw32-make: *** [build_crypto] Error 1



![2015-05-17 02_03_22-](https://cloud.githubusercontent.com/assets/6566869/7667411/fcc6af30-fc38-11e4-82ae-5e6a8e25cc47.png)

**Comment by Ri0n** [comment]
regarding e_os.h header
https://github.com/openssl/openssl/issues/226#issuecomment-103754700

I think it's a bug in GNU Make port for mingw.

to reproduce try next:
* make new folder and enter it
* create empty file test.c
* create Makefile with contents "test:" w/o quotes.
* try mingw32-make CC=gcc
* notice mingw anyway tries to use g++

**Comment by dot-asm** [comment]
The original issue is addressed in 82c4a079395223c0063100854a0981976db9848f

**Comment by Ri0n** [comment]
and again regarding e_os.h header...
just if it's interesting for anyone I made openssl compilable with next script started from openssl source root
<pre>
find ./ -name Makefile | while read f; do echo >> $f; echo "%.o: %.c" >> $f; echo -e '\t$(COMPILE.c) $(OUTPUT_OPTION) $<;' >> $f; done
</pre>

**Comment by richsalz** [comment]
so this doesn't appear to be an openssl issue, but a tools bug issue.  closing.  please re-open if there is something for openssl to do.

**Comment by c-sonntag** [comment]
Hey !
With MSYS2 it's work !
Maybe you try this simple script to build : [easy-openssl-build-example.sh](https://github.com/c-sonntag/bash-building-script/blob/master/easy-openssl-build-example.sh)
