### ISSUE TITLE
openssl s_client -crl_download doesn't work

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#25603]
Command `openssl s_client -connect redhat.com:443 -crl_download -showcerts` doesn't download CRL

Looks like `crls_http_cb` callback is installed only when `-verifyCAfile` or friends are specified but even then it is not called.

**Comment by nhorman** [comment]
can you please set a break in check_cert and see if get_cert_delta is called

**Comment by beldmit** [comment]
I put breakpoints to `check_cert`, `get_cert_delta`, and `crls_http_cb` and built openssl with -O0. None of the breakpoints were triggered :(

**Comment by mattcaswell** [comment]
> Looks like crls_http_cb callback is installed only when -verifyCAfile or friends are specified but even then it is not called.

It does get installed elsewhere - so specifying -verifyCAfile isn't necessary.

This could probably be called a documentation bug. The `-crl_download` option doesn't seem to do anything unless you also specify `-crl_check`

Adding that does cause the callback to be called. Unfortunately it then subsequently fails because:
````
807BE4F7FF7F0000:error:1E800075:HTTP routines:check_set_resp_len:max resp len exceeded:crypto/http/http_client.c:511:length=16236077, max=102400
807BE4F7FF7F0000:error:1E800067:HTTP routines:OSSL_HTTP_REQ_CTX_exchange:error receiving:crypto/http/http_client.c:1002:server=http://crl3.digicert.com:80
````

**Comment by beldmit** [comment]
I agree about documentation bug, thanks.

I wonder if we can do smth to workaround the size, BTW

**Comment by mattcaswell** [comment]
This function:

https://github.com/openssl/openssl/blob/4f48629c9d791c9105f2d68f4a4d0b0085e8e0ca/crypto/x509/x_all.c#L187-L191

Calls this one:

https://github.com/openssl/openssl/blob/4f48629c9d791c9105f2d68f4a4d0b0085e8e0ca/crypto/x509/x_all.c#L115-L131

Which uses `OSSL_HTTP_DEFAULT_MAX_RESP_LEN` (100k) for max response length. This sounds like it could be a bit too short for a CRL.
