### ISSUE TITLE
EVP_CIPHER_CTX_ctrl has to be called before EVP_DecryptUpdate

### ISSUE THREAD

**Issue by tgummerer** [openssl/openssl#2561]
Hi,

We noticed that the documentation for `EVP_CIPHER_CTX_ctrl()` with `EVP_CTRL_GCM_SET_TAG` states that the call is only legal before the first call of `EVP_DecryptUpdate()`.  This seems to be a change between 1.0.1 and 1.0.2.  Looking at the code however, it doesn't matter whether it's called before or after that for normal GCM ciphers, as long as it's called before `EVP_DecryptFinal()`. 

It only seems to matter if the tls_aad_len is set first, and we have a TLS GCM cipher instead of the normal GCM cipher.  

Is this something that might change in the future, so `EVP_CIPHER_CTX_ctrl()` with setting the GCM tag always has to be called before `EVP_DecryptUpdate` even with non-tls GCM ciphers, or should the documentation be updated with this distinction?

**Comment by mattcaswell** [comment]
It doesn't seem to say that any more. At least in master. Closing.
