### ISSUE TITLE
Potential memory leaks in ossl_quic_calculate_retry_integrity_tag

### ISSUE THREAD

**Issue by nielsdos** [openssl/openssl#25625]
Hello. I'm working on a static analysis tool to detect incomplete error handling code.

My tool reported the following.

In `ossl_quic_calculate_retry_integrity_tag` there are several error handling code blocks that return a value without cleaning up the allocated objects.

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L912-L915

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L918-L922

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L924-L928

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L930-L935

All of these return 0 immediately without going through the `err` label or without cleaning up at least `cctx`, `cipher`, and `wpkt`.

I could also be wrong because my results are based on static analysis even though I manually read the code as well.

Thanks in advance

**Comment by mattcaswell** [comment]
Yes this looks like a bug to me. Simply replacing those `return 0` lines with `goto err` seems like a reasonable fix.

Adding the "good first issue" and "help wanted" labels. Are you interested in creating a PR to fix this?

**Comment by nielsdos** [comment]
Thanks for confirming.
I would, but the thing is that I can't sign a CLA at the moment as it requires approval of my university as well. I have contacted the department for that but it may take some time.
It was heavily suggested that I should get a CLA signed here: https://github.com/openssl/openssl/pull/25604#pullrequestreview-2347690255

**Comment by mattcaswell** [comment]
A CLA is always preferred. Especially if you are a frequent contributor. But in its absence this fix could probably be accepted as a "CLA: trivial" change.
