### ISSUE TITLE
Struggling while building 1.0.2k

### ISSUE THREAD

**Issue by satnatantas** [openssl/openssl#2563]
I am building with MinGW64 (GCC 5.4.0) inside MSYS with
`perl Configure --openssldir=/g/openssl/build no-idea no-mdc2 no-rc5 shared mingw64`
and I am getting this upond `mingw32-make depend`:
`../e_os.h:62:34: fatal error: openssl/opensslconf.h: No such file or directory
...
mem.c:61:28: fatal error: openssl/crypto.h: No such file or directory
...` etc and various other failed includes if I try to fix this one which start with `openssl/`.

The issue is that there is not a single `openssl` directory in the source tree and renaming the source tree to `openssl` does not help either so this is defective by design for people who do not have openssl already installed in system include path. What am I doing wrong?

**Comment by satnatantas** [comment]
At the same time 1.1.0d builds well for me because it has `include/openssl` directory in root of source tree.

**Comment by levitte** [comment]
Did the 1.0.2k configuration command work as expected?  I.e. before you even did `make depend`?

**Comment by dot-asm** [comment]
Let's sing in unison: matching perl... matching perl...

**Comment by dot-asm** [comment]
I mean "inside MSYS with ActiveState Perl" is enough to answer question "What am I doing wrong?".

**Comment by satnatantas** [comment]
@levitte Yes.
@dot-asm oh wait I am lying! I am using cygwin's perl which is in Path.

**Comment by dot-asm** [comment]
Well, it's not like we know it doesn't work, it's rather we don't want answer questions if it doesn't. It's obviously impossible to cover all possible combinations, instead we pick what we know works and ready to support, i.e. "matching perl", and stick with it.

**Comment by satnatantas** [comment]
@dot-asm well I am not asking for a ready solution but could you probably hint me how can `openssl/crypto.h` not reside inside `openssl` directory at least. Or is it created and populated by `Configure` script?

**Comment by satnatantas** [comment]
`*) <openssl/opensslconf.h> (which is created by Configure) now contains
     sections with information on -D... compiler switches used for
     compiling the library so that applications can see them.  To enable
     one of these sections, a pre-processor symbol OPENSSL_..._DEFINES
     must be defined.  E.g.,
        #define OPENSSL_ALGORITHM_DEFINES
        #include <openssl/opensslconf.h>
     defines all pertinent NO_<algo> symbols, such as NO_IDEA, NO_RSA, etc.
     [Richard Levitte, Ulf and Bodo Möller]`

Ok I see it now, it should be created by configure...

**Comment by dot-asm** [comment]
> I am using cygwin's perl which is in Path.

Even though it have much better changes to work, there might be small things that cause problems. But if you have cygwin, then just fetch migw for cygwin and configure with `--cross-compile-prefix=x86_64-w64-mingw32-` at cygwin prompt, *that* would be supported combination. For reference "matching perl" refers rather to build system, than to target. I.e. if you use cygwin make and toolchain, then cygwin perl is the one to use for any target, be it cygwin itself or any cross-compiled target.

**Comment by satnatantas** [comment]
@dot-asm Thanks for the tip.

**Comment by satnatantas** [comment]
@dot-asm I was using Cygwin's perl because 1.1.0d required 5.20 and MSYS has 5.8.8 only. After I removed Cygwin from PATH it went as expected. Thank again.

**Comment by mattcaswell** [comment]
The original msys has some pre-historic packages including perl. Use msys2 for up to date packages.

**Comment by dot-asm** [comment]
Perl minimum requirement for 1.1.x is 5.10, not 5.20. But as already said/implied, it's mixing-n-matching different Perls, different in terms of their run-time-ness, that is not supported. You have to pick single whole environment and stick with it for *everything*. Cygwin? Cygwin for everything, i.e. perl, make, compilers. MSYS2? MSYS2 for everything, i.e. perl, make, compilers. Well, compilers are actually least of the problem, it's other things on boundaries between make, shell and perl, things like passing error codes, piping, preferred path delimiter that are potentially problematic...

**Comment by satnatantas** [comment]
@mattcaswell true but MSYS2 does not offer a convenient way of installing previous versions of the components. Getting GCC 5.4.0 from `pacman` is impossible and installing from downloaded copy makes me resolve all dependencies myself.
