### ISSUE TITLE
SSL module not getting created while installing Python 3.11.10 version with openssl1.1.1w

### ISSUE THREAD

**Issue by idasaurabh** [openssl/openssl#25641]
<!--
Thank you for your bug report. If this is your first one,
please take the time to read the following lines before posting it.

NOTE:

    If you're asking about how to use OpenSSL, this isn't the right
    forum.  Please see our User Support resources:
    https://github.com/openssl/openssl/blob/master/SUPPORT.md

The issue is found in openssl-1.1.1w

For build issues:

[sab@MKX1102 ~]$ pyenv install 3.11.10
Installing Python-3.11.10...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sab/.pyenv/versions/3.11.10/lib/python3.11/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named '_ssl'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (Oracle Linux Server 7.9 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20241008225505.26487
Results logged to /tmp/python-build.20241008225505.26487.log

Last 10 log lines:
                install|*) ensurepip="" ;; \
        esac; \
        LD_LIBRARY_PATH=/tmp/python-build.20241008225505.26487/Python-3.11.10:/usr/local/lib/python3.11/openssl-1.1.1w:/usr/lib64:/usr/lib64: ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmph41fmznd
Processing /tmp/tmph41fmznd/setuptools-65.5.0-py3-none-any.whl
Processing /tmp/tmph41fmznd/pip-24.0-py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-24.0 setuptools-65.5.0

    With OpenSSL before 1.1.1, the configuration output comes from the
    configuration command.  With OpenSSL 1.1.1 and on, it's the output
    of `perl configdata.pm --dump`

**Comment by tom-cosgrove-arm** [comment]
OpenSSL 1.1.1w has been out of support (end of life) for over a year now. If you need support for it, there are premium support contracts available, but those have to be paid for.
