### ISSUE TITLE
A probable crash in sha1_block_data_order on windows with sha1 ext capable CPU

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#25661]
By code review it looks likely that the function sha1_block_data_order
migth crash under windows when a CPU supports sha1 extension,
because of the code here:
https://github.com/openssl/openssl/blob/6afaa3f41f5b65432b6700064b077032b9e0c625/crypto/sha/asm/sha1-x86_64.pl#L374-L383
because the register rax is not initialized, here:
https://github.com/openssl/openssl/blob/6afaa3f41f5b65432b6700064b077032b9e0c625/crypto/sha/asm/sha1-x86_64.pl#L263-L273

probably something like this is missing:
```
diff --git a/crypto/sha/asm/sha1-x86_64.pl b/crypto/sha/asm/sha1-x86_64.pl
index 30c545cf41..85c76de3d3 100755
--- a/crypto/sha/asm/sha1-x86_64.pl
+++ b/crypto/sha/asm/sha1-x86_64.pl
@@ -375,6 +375,7 @@ _shaext_shortcut:
 .cfi_startproc
 ___
 $code.=<<___ if ($win64);
+       mov     %rsp,%rax
        lea     `-8-4*16`(%rsp),%rsp
        movaps  %xmm6,-8-4*16(%rax)
        movaps  %xmm7,-8-3*16(%rax)
```

but I cannot test that, and maybe there is also a reason why that cannot happen,
since I do not understand why this was never reported in the last 10 years...

**Comment by t8m** [comment]
> but I cannot test that, and maybe there is also a reason why that cannot happen,
> since I do not understand why this was never reported in the last 10 years...

Yeah, either the code is not exercised for some reason or there must be something else in play here as otherwise we would see the crashes even in the CI.

**Comment by nhorman** [comment]
Is it possibly just good luck?  i.e. cdecl I think says that RAX gets saved by the caller, and it just so happens that all callers save the "right" value to RAX prior to the call?

**Comment by bernd-edlinger** [comment]
Hmm, I was able to look into a native windows generated crypto/sha/sha1-x86_64.asm
```
sha1_block_data_order	PROC PUBLIC
	mov	QWORD PTR[8+rsp],rdi	;WIN64 prologue
	mov	QWORD PTR[16+rsp],rsi
	mov	rax,rsp
$L$SEH_begin_sha1_block_data_order::
	mov	rdi,rcx
	mov	rsi,rdx
	mov	rdx,r8



	mov	r9d,DWORD PTR[((OPENSSL_ia32cap_P+0))]
	mov	r8d,DWORD PTR[((OPENSSL_ia32cap_P+4))]
	mov	r10d,DWORD PTR[((OPENSSL_ia32cap_P+8))]
	test	r8d,512
	jz	$L$ialu
	test	r10d,536870912
	jnz	_shaext_shortcut
```
So out of nowhere this `mov rax,rsp` appears here on windows.
Well, it works, but this is what I would call a really bad hack, what's going on here...

**Comment by tom-cosgrove-arm** [comment]
@bernd-edlinger I don't understand why you've closed this issue. Your analysis looks sound - we are missing a `mov rax,rsp` and we are lucky that it's current emitted by the compiler in code just before ours. Surely we should keep this issue open until we add such a `mov` in?

**Comment by bernd-edlinger** [comment]
@tom-cosgrove-arm I closed this issue because I found out that this code is emitted here:
https://github.com/openssl/openssl/blob/99548cd16e9dfd850a3958e417b9e02950f208f4/crypto/perlasm/x86_64-xlate.pl#L533-L535

So it is not by accident, but by "design"...

What remains is the bad feeling that this is kind of unmaintainable, yet a PR like #9603 which was about to
introduce a misaligned `movaps` could easily pass all the CIs, get approved, committed and would have caused
some very real damage.

**Comment by tom-cosgrove-arm** [comment]
> So it is not by accident, but by "design"...

Ah, yes, and it's not likely to change:

```
# 8. In order to provide for structured exception handling unified
#    Win64 prologue copies %rsp value to %rax. For further details
#    see SEH paragraph at the end.
```
