### ISSUE TITLE
An unexpected_message alert is reported when the OpenSSL client using the ssl_write command to initiate renegotiation but receives an app message

### ISSUE THREAD

**Issue by liwei62** [openssl/openssl#25676]
version: 3.0.9

Description
In tls1.2, the client uses ssl_write to initiate renegotiation. The client sends a client hello message and attempts to receive the message from the server. However, an unexpected_message alert is reported when the app message is received from the server. 

Question
1. If the app message is received, does it mean that the server does not want to renegotiate and should continue to use the original session? But now this makes the original session unusable. Is there a problem with this?
2. If the app message is received when the renegotiation is initiated through the ssl_read command, the link is not disconnected and the communication can continue. Why is the difference?

Code
Send an alert here, ssl/record/rec_layer_s3.c:1783
https://github.com/openssl/openssl/blob/de90e54bbe82e5be4fb9608b6f5c308bb837d355/ssl/record/rec_layer_s3.c#L1754-L1785

I look forward to hearing from you. Thanks.

**Comment by mattcaswell** [comment]
> If the app message is received, does it mean that the server does not want to renegotiate and should continue to use the original session? But now this makes the original session unusable. Is there a problem with this?

It would typically mean that there was still data in flight coming from the server when the client initiated the renegotiation. The server should not send any more app data using the old keys once it receives the reneg request (it should either process the reneg or fail).

> If the app message is received when the renegotiation is initiated through the ssl_read command, the link is not disconnected and the communication can continue. Why is the difference?

What application protocol is this? It is unusual for a client to initiate new app data writes before it has finished reading all the data that the server has to send. I would advise against initiating a reneg via  SSL_write unless you know for sure the server has finished sending app data using the old keys. In fact as you have discovered it appears we don't even support this corner case. But it is even unclear how we would support it if we wanted to - there is the potential for deadlock here, i.e. the client is trying to write app data, but a reneg has started and the server is still sending app data using the old keys. The new handshake cannot complete until the client reads that app data, but the client is stuck trying to send app data and no further progress can be made.

There are potential solutions I could imagine but not particularly nice ones and implementing this would be tricky to get right. I suppose you could consider this a missing feature - but not one I expect us to ever implement (renegotiation does not exist in TLSv1.3 - so this is considered legacy).

**Comment by baoyi84930** [comment]
@mattcaswell 
> I would advise against initiating a reneg via SSL_write unless you know for sure the server has finished sending app data using the old keys. 


Generally, the renegotiation initiator, regardless of the client or server,  initiates a reneg via SSL_read and determines whether the renegotiation is complete via SSL_renegotiate_pending.
Am I right?

**Comment by mattcaswell** [comment]
> Calling SSL_write() or SSL_do_handshake() may cause an alert after receiving an app data.

Yes. Continue to call SSL_read() until all data has been received.
