### ISSUE TITLE
why so many errors in configuration.h.in

### ISSUE THREAD

**Issue by NahilTheDolfin** [openssl/openssl#25681]
hello, im trying to make my own cryptocurrency project and so i installed Openssl sha.h for security and crypto reasons and so. some of the files haves errors its only errors like #includes errors. but the source of all the problems is configuration.h.in here are all the errors i met

[{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "169",
	"severity": 8,
	"message": "expected a declaration",
	"source": "C/C++",
	"startLineNumber": 28,
	"startColumn": 1,
	"endLineNumber": 28,
	"endColumn": 2
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "7",
	"severity": 8,
	"message": "unrecognized token",
	"source": "C/C++",
	"startLineNumber": 28,
	"startColumn": 8,
	"endLineNumber": 28,
	"endColumn": 8
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "7",
	"severity": 8,
	"message": "unrecognized token",
	"source": "C/C++",
	"startLineNumber": 29,
	"startColumn": 16,
	"endLineNumber": 29,
	"endColumn": 16
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "7",
	"severity": 8,
	"message": "unrecognized token",
	"source": "C/C++",
	"startLineNumber": 35,
	"startColumn": 14,
	"endLineNumber": 35,
	"endColumn": 14
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "7",
	"severity": 8,
	"message": "unrecognized token",
	"source": "C/C++",
	"startLineNumber": 39,
	"startColumn": 9,
	"endLineNumber": 39,
	"endColumn": 9
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "7",
	"severity": 8,
	"message": "unrecognized token",
	"source": "C/C++",
	"startLineNumber": 40,
	"startColumn": 16,
	"endLineNumber": 40,
	"endColumn": 16
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "169",
	"severity": 8,
	"message": "expected a declaration",
	"source": "C/C++",
	"startLineNumber": 50,
	"startColumn": 1,
	"endLineNumber": 50,
	"endColumn": 2
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "77",
	"severity": 8,
	"message": "this declaration has no storage class or type specifier",
	"source": "C/C++",
	"startLineNumber": 50,
	"startColumn": 60,
	"endLineNumber": 50,
	"endColumn": 69
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"$config\" is undefined",
	"source": "C/C++",
	"startLineNumber": 56,
	"startColumn": 4,
	"endLineNumber": 56,
	"endColumn": 11
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "253",
	"severity": 8,
	"message": "expected a ','",
	"source": "C/C++",
	"startLineNumber": 56,
	"startColumn": 11,
	"endLineNumber": 56,
	"endColumn": 12
},{
	"resource": "/c:/Program Files/OpenSSL-Win64/include/openssl/configuration.h.in",
	"owner": "C/C++: IntelliSense",
	"code": "65",
	"severity": 8,
	"message": "expected a ';'",
	"source": "C/C++",
	"startLineNumber": 56,
	"startColumn": 49,
	"endLineNumber": 56,
	"endColumn": 57
}]

between all the errors i met, is there a fixed version of this file please? Thank you
![Capture d'écran 2024-10-13 174108](https://github.com/user-attachments/assets/2a278cb3-f001-48c2-95b9-2c0172566cb1)

**Comment by levitte** [comment]
This isn't a file you should use directly. When building OpenSSL, this file is a template from which `include/openssl/configuration.h` is generate, which is what you will want to use.

**Comment by NahilTheDolfin** [comment]
oh and how do i get Configuration.h please?

**Comment by NahilTheDolfin** [comment]
when i try to run configure or nconfiguration.h.in it tells this 
![Capture d'écran 2024-10-13 200619](https://github.com/user-attachments/assets/ee14e045-0073-4a99-af43-87614bfbefb7)

**Comment by NahilTheDolfin** [comment]
fixed. got the code from another site. i got the entire confoguration.h
