### ISSUE TITLE
openssl 3.4.0-beta1: OpenSSL_version(OPENSSL_DIR); changed behaviour.

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#25690]
OpenSSL_version(OPENSSL_DIR) changed behavior:
pre 3.4/ e6c77f2685566 ("convert users of build time defaults to use new defaults api"):
`OPENSSLDIR: "/usr/lib/ssl"`
After that commit:
`/usr/lib/ssl`

The missing `OPENSSLDIR:` breaks the testsuite of Crypt::SSLeay/ crypt-ssleay 0.73.06.
If this is intended please say so and I forward this to Crypt::SSLeay asking them to update their testsuite.

Sebastian

**Comment by t8m** [comment]
Should be fixed by #25692

**Comment by sebastianas** [comment]
On 2024-10-15 02:22:47 [-0700], Tomáš Mráz wrote:
> Should be fixed by #25692 

Oh. Thank you for taking care of it.

Sebastian
