### ISSUE TITLE
Import Error of module and compilation error 

### ISSUE THREAD

**Issue by Prabal1998** [openssl/openssl#25691]
### Discussed in https://github.com/openssl/openssl/discussions/25686

<div type='discussions-op-text'>

<sup>Originally posted by **Prabal1998** October 13, 2024</sup>
![image](https://github.com/user-attachments/assets/6270d8c1-59b9-4a92-943c-be1aded585a3)

</div>

**Comment by t8m** [comment]
Please do not open duplicate issues.
