### ISSUE TITLE
Performance optimization of pbkdf2_derive

### ISSUE THREAD

**Issue by bangcheng** [openssl/openssl#25703]
There are some performance issues with pbkdf2_derive. The performance test program used is as follows:
```
#include <stdio.h>
#include <openssl/evp.h>

char buff[10000];
int main (int argc, char *argv[]) {
    int iterations = 200;
    int key_length = atoi(argv[1]);

    for (int i = 0; i < iterations; ++i) {
        int ret = PKCS5_PBKDF2_HMAC("12345678996", 11, "123456789123456789", 18, 10000, EVP_sha256(), key_length, buff);
         if (ret == 0) {
            printf("PKCS5_PBKDF2_HMAC failed\n");
            return 0;
         }
    }
    return 1;
}
```
The performance flame graph of the above program is as follows:
![image](https://github.com/user-attachments/assets/1de5a2dc-b9ac-4f2d-b0df-0a88f9404acb)

Through analysis, it was found that there are some problems with the implementation of EVP_MD_CTX_copy_ex. The EVP_MD_CTX_copy_ex interface clears all member variables of out (EVP_MD_CTX) every time, and then copies `in` to `out`, even if out and in are the same type of EVP_MD (out->digest == in->digest && out->fetched_digest == in->fetched_digest && out->reqdigest == in->reqdigest).  This results in a large amount of memory being repeatedly requested and released, causing performance degradation. This problem exists in all versions of openssl.

**Solution**: Add CTX copy function for EVP_MD. In the function EVP_MD_CTX_copy_ex, if the MD types of the parameters `out` and `in` are the same, the copy will be completed by copying instead of the previous method.

**Comment by t8m** [comment]
There is actually already a special case for when the fetched digest is the same in in and out contexts so we at least keep the fetched EVP_MD implementation. The thing that is being cleared is the digest context inside the provider. We would have to add a provider function that copies the context data into an existing data but that would require adding support also in third party providers.

**Comment by levitte** [comment]
It's not impossible to add a copy function in the provider interface, and then have `EVP_MD_CTX_copy_ex` use that copy function *if it's available*, and fall back to the duplication function otherwise.

**Comment by t8m** [comment]
> It's not impossible to add a copy function in the provider interface, and then have `EVP_MD_CTX_copy_ex` use that copy function _if it's available_, and fall back to the duplication function otherwise.

Yeah, that fallback would be obviously needed.

**Comment by bangcheng** [comment]
> It's not impossible to add a copy function in the provider interface, and then have `EVP_MD_CTX_copy_ex` use that copy function _if it's available_, and fall back to the duplication function otherwise.

I have implemented a draft which I will submit later.
