### ISSUE TITLE
bad_certificate instead of decode_error alert when empty compress certificate message

### ISSUE THREAD

**Issue by GeorgePantelakis** [openssl/openssl#25705]
When a compressed certificate is used we send the following compressed certificate message:

struct { CertificateCompressionAlgorithm algorithm; uint24 uncompressed_length; opaque compressed_certificate_message<1..2^24-1>; } CompressedCertificate;

When we are sending an empty compressed_certificate_message with a length of 0 bytes then we should get a decode error since the minimum accepted message is of size 1 byte. Instead, we are getting a bad_certificate error.

## Steps to Reproduce:
* Run https://github.com/tlsfuzzer/tlsfuzzer/blob/master/scripts/test-tls13-client-certificate-compression.py against an OpenSSL server.

Test "Empty compressed message" from test-tls13-client-certificate-compression.py should pass

**Comment by mattcaswell** [comment]
@tmshort

**Comment by Sashan** [comment]
The linked pull request was merged already. closing the issue.
