### ISSUE TITLE
test_acvp failed, if configure with 'no-ec2m'

### ISSUE THREAD

**Issue by jbmsg** [openssl/openssl#25729]
branch: main, openssl-3.4
Configure option: no-ec2m

those curve K-283 related tests failed

**Comment by t8m** [comment]
Fix in #25731

**Comment by st-rnd** [comment]
The fix can solve the test failure.
But in crypto/ec/ec_support.c, NID_sect283k1 is enclosed in #ifndef OPENSSL_NO_EC2M ... #endif, and in crypto/evp/ec_curve.c and ssl/t1_lib.c, it's not. So some api can find the curve, and some cannot.
Not sure is it an issue?

**Comment by jbmsg** [comment]
The fix can solve the test failure.
In crypto/ec/ec_support.c, NID_sect283k1 is enclosed in #ifndef OPENSSL_NO_EC2M ... #endif, but in crypto/evp/ec_curve.c and ssl/t1_lib.c, it's not. So some api can find the curve, and some cannot.
Not sure is it an issue?

**Comment by t8m** [comment]
> The fix can solve the test failure. In crypto/ec/ec_support.c, NID_sect283k1 is enclosed in #ifndef OPENSSL_NO_EC2M ... #endif, but in crypto/evp/ec_curve.c and ssl/t1_lib.c, it's not. So some api can find the curve, and some cannot. Not sure is it an issue?

These mappings are harmless and can be kept.
