### ISSUE TITLE
SSL routines:ssl3_get_client_hello:no shared cipher

### ISSUE THREAD

**Issue by 404notfoundhard** [openssl/openssl#2572]
**SERVER:**

root@notfound:# openssl version 
OpenSSL 1.0.2g  1 Mar 2016
root@notfound:# openssl ciphers -v | grep "^DH-RSA"
DH-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AESGCM(256) Mac=AEAD
DH-RSA-AES256-SHA256    TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AES(256)  Mac=SHA256
DH-RSA-AES256-SHA       SSLv3 Kx=DH/RSA   Au=DH   Enc=AES(256)  Mac=SHA1
DH-RSA-CAMELLIA256-SHA  SSLv3 Kx=DH/RSA   Au=DH   Enc=Camellia(256) Mac=SHA1
DH-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AESGCM(128) Mac=AEAD
DH-RSA-AES128-SHA256    TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AES(128)  Mac=SHA256
**DH-RSA-AES128-SHA**       SSLv3 Kx=DH/RSA   Au=DH   Enc=AES(128)  Mac=SHA1
DH-RSA-SEED-SHA         SSLv3 Kx=DH/RSA   Au=DH   Enc=SEED(128) Mac=SHA1
DH-RSA-CAMELLIA128-SHA  SSLv3 Kx=DH/RSA   Au=DH   Enc=Camellia(128) Mac=SHA1
DH-RSA-DES-CBC3-SHA     SSLv3 Kx=DH/RSA   Au=DH   Enc=3DES(168) Mac=SHA1
root@notfound:~# openssl s_server  -key key.pem -cert cert.pem -accept 44443 -WWW -cipher DH-RSA-AES128-SHA
Using default temp DH parameters
ACCEPT
140465032079000:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:s3_srvr.c:1417:
ACCEPT

**LOCAL CLIENT:**

root@notfound:# openssl s_client -connect localhost:44443 -cipher DH-RSA-AES128-SHA
CONNECTED(00000003)
140693073794712:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:

no peer certificate available

No client certificate CA names sent

SSL handshake has read 7 bytes and written 99 bytes

New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1486525221
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

PS: and DH-RSA-AES128-SHA256 too

**Comment by davidben** [comment]
DH-RSA are the static Diffie-Hellman ciphers. They require that you have a Diffie-Hellman X.509 certificate, not an RSA one. (The RSA here refers to the issuing certificate's key.) You probably don't have one of those, so OpenSSL is silently filtering it out. DHE-RSA are the ones that use an RSA certificate and generate an ephemeral Diffie-Hellman keypair.

(PS: You probably want ECDHE-RSA. DHE-RSA is pretty slow and the TLS construction is problematic.)

**Comment by 404notfoundhard** [comment]
Thanks for answer!
