### ISSUE TITLE
OpenSSL 1.0.2j not compiling with no-dh option

### ISSUE THREAD

**Issue by sankalp135** [openssl/openssl#2573]
OpenSSL 1.0.2j is not compiling with no-dh option

./config solaris-sparcv9-cc no-shared no-asm no-dh
make

e_capi.o e_capi.c                                                                                  
echo                                                                                                 

/bin/sh: syntax error at line 1: `;' unexpected
make[1]: *** [subdirs] Error 2                 
make[1]: Leaving directory `/vobs/OpenSSL/1.0.2j/prod/openssl-1.0.2j/engines'
make: *** [build_engines] Error 1

**Comment by levitte** [comment]
The only reason I can see for that to happen is if ENGDIRS is empty.  What do you get from this (in the top OpenSSL source directory)?

`grep ENGDIRS Makefile`

**Comment by sankalp135** [comment]
I got following result

bash-2.03$ grep ENGDIRS Makefile
ENGDIRS= ccgost
                PERL='$(PERL)' ENGDIRS='$(ENGDIRS)'             \
bash-2.03$

**Comment by mattcaswell** [comment]
I cannot replicate this. Is this still an issue?

**Comment by levitte** [comment]
Unsure...  we don't have the whole story.  If someone can reproduce it, I'd like a full log

**Comment by sankalp135** [comment]
The issue is resolved there is a error while creating linking to test files
