### ISSUE TITLE
SSL3_ALIGN_PAYLOAD does not take DTLS record header size into account

### ISSUE THREAD

**Issue by fwh-dc** [openssl/openssl#25746]
This is an observation found during the implementation of variable length headers for DTLS 1.3.

OpenSSL has a couple of places were it aligns the records written in memory for performance reasons.

1. Shouldn't the full record size be taken in to account when doing byte alignment?
2. Is it intentional  that the alignment is calculated in many places only depending on `SSL3_RT_HEADER_LENGTH` even for DTLS?
3. Why is the alignment calculation differing between read and write functions?

Here are the places that alignment is calculated.

`tls1_initialise_write_packets()` (Not called by DTLS):
https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/ssl/record/methods/tls1_meth.c#L628-L632

`tls_setup_write_buffer()`
https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/ssl/record/methods/tls_common.c#L162-L164

`tls_initialise_write_packets_default()`
https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/ssl/record/methods/tls_common.c#L1578-L1583

`tls_setup_read_buffer()`
https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/ssl/record/methods/tls_common.c#L242-L244

`tls_default_read_n()`
https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/ssl/record/methods/tls_common.c#L315-L318

**Comment by bernd-edlinger** [comment]
I think this comment is relevant to your question, somehow it seems to be deleted in master:
```C
    /*
     * Using SSL3_RT_HEADER_LENGTH here instead of DTLS1_RT_HEADER_LENGTH for
     * consistency with ssl3_read_n. In practice it should make no difference
     * for sensible values of SSL3_ALIGN_PAYLOAD because the difference between
     * SSL3_RT_HEADER_LENGTH and DTLS1_RT_HEADER_LENGTH is exactly 8
     */
```
FYI, I found this comment here:
https://github.com/bernd-edlinger/openssl/blob/openssl-111-features/ssl/d1_lib.c#L514-L519

**Comment by fwh-dc** [comment]
That helps a lot thanks. So it seems that the idea is to align the record body which happens in `tls_default_read_n()` and `tls_initialise_write_packets_default()`. And then `tls_setup_read_buffer()` and `tls_setup_write_buffer()` just calculates the maximal alignment that can occure. 

I would expect `tls_setup_read_buffer()` and `tls_setup_write_buffer()` to calculate the same value?

**Comment by mattcaswell** [comment]
> tls1_initialise_write_packets() (Not called by DTLS):

In this case that function is not relevant to DTLS - it handles processing any *prefix* and then defers the rest of the processing to `tls_initialise_write_packets_default`. In DTLS `tls_initialise_write_packets_default` is just called directly.

The prefix is only relevant to TLSv1.0 or below (countermeasure against known-IV weaknesses in CBC ciphersuites which doesn't apply to DTLS).

If you look at `tls_initialise_write_packets_default` then that function does take into account whether DTLS is being used or not.

**Comment by mattcaswell** [comment]
> tls_setup_write_buffer()

This one does seem to take into account the DTLS header length?

> tls_setup_read_buffer()

As does this one?

> tls_default_read_n()

Hmm....this one does look potentially suspect.

**Comment by mattcaswell** [comment]
But @bernd-edlinger's comment also looks valid.

**Comment by fwh-dc** [comment]
> > tls_default_read_n()
> 
> Hmm....this one does look potentially suspect.

This one, right? :
tls_setup_read_buffer()

https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/ssl/record/methods/tls_common.c#L242-L244

Should I make a PR to make it similar to this? :

https://github.com/openssl/openssl/blob/f4c467452694e1211395d17c2c027d99c35ee1e1/ssl/record/methods/tls_common.c#L162-L164

> > tls_setup_write_buffer()
> This one does seem to take into account the DTLS header length?

This is the only one that takes it in to account. Except if you take in to account the assumptions given in the comment from @bernd-edlinger 's example.

I'll make a separate function for the alignment calculation and include it in the DTLS variable header PR.

**Comment by mattcaswell** [comment]
> This one, right? :
tls_setup_read_buffer()

Oh....right, yeah...

> I'll make a separate function for the alignment calculation and include it in the DTLS variable header PR.

Makes sense
