### ISSUE TITLE
Need to know which OpenSSL version supports TLS 2.0 and build procedure for building it on VS 2010  x64bit windows 2008 R2

### ISSUE THREAD

**Issue by shekhardpatil** [openssl/openssl#2576]
Hello,

I have two quetions

1) I have built my application with OpenSSL 1.0.1.g but its read me file says it supports TLS v1.
I need to know which version of OpenSSL supports TLS 2.0, so I can take code from Git hub and built?
2) what are the steps for building that code with Microsoft Visual Studio 2010 X 64 bit on Windows Servers 2008 R2 Operating system?
3) is their configuration to make openSSL to use TLS instead of SSL?

**Comment by mattcaswell** [comment]
> I have two quetions

That's three ;-)

> I have built my application with OpenSSL 1.0.1.g but its read me file says it supports TLS v1.
I need to know which version of OpenSSL supports TLS 2.0, so I can take code from Git hub and built?

There is no such thing as TLS 2.0. SSL/TLS versions in order of oldest to newest are:
SSLv2
SSLv3
TLS1.0
TLS1.1
TLS1.2
TLS1.3 (still in development - spec not yet finalised)

OpenSSL 1.0.1g supports all of the above except TLS1.3. However the 1.0.1 series is now out of support and no longer receiving security updates. Unless you got your version of OpenSSL from an O/S vendor (in which case the O/S vendor will be supporting it), you should upgrade to a newer version.

> what are the steps for building that code with Microsoft Visual Studio 2010 X 64 bit on Windows Servers 2008 R2 Operating system?

Windows build instructions are included in the INSTALL.W64 file in 1.0.1 and 1.0.2. If you upgrade to 1.1.0 then instructions are in INSTALL.

> is their configuration to make openSSL to use TLS instead of SSL?

OpenSSL will use TLS by default wherever possible.

**Comment by shekhardpatil** [comment]
I have already built my application with OpenSSL 1.0.1g and it connects to the web service with TLS 1.2 and our initial communication handshake still fails and there is no response from web service ? what could be wrong?

where to find INSTALL.W64 this file? on git hub or OpenSSL.org site? on git hub what is directory hierarchy?

**Comment by mattcaswell** [comment]
> I have already built my application with OpenSSL 1.0.1g and it connects to the web service with TLS 1.2 and our initial communication handshake still fails and there is no response from web service ? what could be wrong?

It could be any number of things. You could try using the openssl s_client application to connect to your server to see if that succeeds or not. If you can't figure it out then you should send a question to the openssl-users email list (details at https://mta.openssl.org). Provide as much information as you can, e.g. what you were trying to do, any error messages that you saw, what the output from s_client was etc.

> where to find INSTALL.W64 this file? on git hub or OpenSSL.org site? on git hub what is directory hierarchy?

It's in the top level directory of the download. The 1.0.1 version is also viewable here:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_1-stable/INSTALL.W64

**Comment by shekhardpatil** [comment]
Hello mattcaswell,

Thanks for quick answer to my previous questions.

We are connecting to one web service by extracting SSL client  certificate  using OpenSSL client but it only shows SSL certificate information in debug logs. There is no way to identify which protocol we are using to connect to webservice SSL or TLS?  is there a way to know which protocol is being used to connect to web service?

**Comment by richsalz** [comment]
Please go to the mailing list as Matt said.

**Comment by shekhardpatil** [comment]
Hey rochsalz,

 When I tried to subscribe to openssl-users mailing list, I dint receive any mail to confirm.
Not sure how to get information needed by me?

**Comment by richsalz** [comment]
email postmaster@openssl.org and say you want to join
