### ISSUE TITLE
dh_cms_set_peerkey(): Wrong condition in 'if' statement

### ISSUE THREAD

**Issue by partimScurra** [openssl/openssl#25824]
Left part of this binary statement may be removed easily, as the right part fulfills this condition when true:

https://github.com/openssl/openssl/blob/a3660729e68dc11c01edb4a349ff2610b6b59ee0/crypto/cms/cms_dh.c#L38

**Comment by t8m** [comment]
I believe the bug is different - the correct check should be `atype != V_ASN1_UNDEF && atype != V_ASN1_NULL`

**Comment by partimScurra** [comment]
Makes more sense! Should I edit the issue then?
