### ISSUE TITLE
APPS/pkeyutl: wrong claim about digest automatically chosen for sign/verify

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#25827]
Due to a PR review https://github.com/openssl/openssl/pull/22910#discussion_r1818417863, I had a closer look at 
the `pkeyutl` documentation stating on its `-digest` option added in PR #8186:

> If this option is omitted but the signature algorithm requires one, a default value will be used. 
> For signature algorithms like RSA, DSA and ECDSA, SHA-256 will be the default digest algorithm.
> For SM2, it will be SM3.

and compared this with the actual behaviour - and found that this claim is at least to most extent not true.
This can be verified with all active OpenSSL versions for instance as follows:
```
echo -n "0123456789ABCDEF0123456789ABCDEF" >test256.dat
cat test256.dat <(printf "extended") >test256+.dat
ls -l test256*.dat | sort | awk '{print $9": "$5" bytes" }'
# test256.dat: 32 bytes
# test256+.dat: 40 bytes

export EC256KEY=test/certs/server-ecdsa-brainpoolP256r1-key.pem
openssl pkeyutl -inkey $EC256KEY -in test256.dat -sign   -out     test256.sig
openssl pkeyutl -inkey $EC256KEY -in test256.dat -verify -sigfile test256.sig
# Signature Verified Successfully
openssl pkeyutl -inkey $EC256KEY -in test256+.dat -verify -sigfile test256.sig
# Signature Verified Successfully :-(
```
That is, with 256-bit ECDSA and without `-digest`, signature and/or verification take into account 
only the first 256 bits of input (which is the actual input size of the respective operation).
Which implies that no automatic hashing kicks in.

For SM2 (also 256 bits input size), things look more like as being documented:
```
export SM2KEY=test/certs/sm2.key
openssl pkeyutl -inkey $SM2KEY -in test256.dat -sign   -out     test256.sig
openssl pkeyutl -inkey $SM2KEY -in test256.dat -verify -sigfile test256.sig
# Signature Verified Successfully
openssl pkeyutl -inkey $SM2KEY -in test256+.dat -verify -sigfile test256.sig
Signature Verification Failure
```
Yet from the following test it appears that no digest gets used automatically:
```
export SM2KEY=test/certs/sm2.key
openssl pkeyutl -inkey $SM2KEY -in test256.dat  -sign -out test.sm2.sig
openssl pkeyutl -inkey $SM2KEY -in test256+.dat -sign -out test.sm2.sig
# Public Key operation error
```
Looks like SM3 gets used (only?) when explicitly asked for:
```
openssl pkeyutl -inkey $SM2KEY -in test256+.dat -sign   -out     test.sm2.sig -rawin -digest SM3
openssl pkeyutl -inkey $SM2KEY -in test256+.dat -verify -sigfile test.sm2.sig -rawin -digest SM3
# Signature Verified Successfully
```

As a solution, I propose not to add the claimed automatism, but to simply remove 
(or at least cut down the above quoted claims to whatever actually happens special for SM2)
because this command is supposed to provide just rather low-level crypto functionality.

What would be nice though is an input truncation warning when `-digest` is not given 
and the input size is any larger than the input length of the sign/verify operation for the given key.
So far there is just a coarse error thrown in case "non-raw" input ist larger than 64 bytes (`EVP_MAX_MD_SIZE`).

**Comment by DDvO** [comment]
Initially I had copied part of the mentioned test procedure in unsuitable locations of the OP; fixed by directly editing it.

**Comment by DDvO** [comment]
Further updated the OP because I just noticed that for SM2 at least some special treatment is actually done.

**Comment by DDvO** [comment]
According to https://github.com/openssl/openssl/pull/22910#discussion_r1821799551 and https://github.com/openssl/openssl/pull/22910#discussion_r1822021875,
maybe the text on `-digest` can be cured simply by prepending a precondition on `-rawin` like the following? 

> If this option is omitted but the signature algorithm requires one and the `-rawin` option is given or implied, a default digest algorithm will be used. ...

**Comment by levitte** [comment]
> According to [#22910 (comment)](https://github.com/openssl/openssl/pull/22910#discussion_r1821799551) and [#22910 (comment)](https://github.com/openssl/openssl/pull/22910#discussion_r1822021875), maybe the text on `-digest` can be cured simply by prepending a precondition on `-rawin` like the following?
> 
> > If this option is omitted but the signature algorithm requires one and the `-rawin` option is given or implied, a default digest algorithm will be used. ...

Regarding this, it's already there, but perhaps not prominent enough.  You can find the man-page text for `-digest` here:

https://github.com/openssl/openssl/blob/a3660729e68dc11c01edb4a349ff2610b6b59ee0/doc/man1/openssl-pkeyutl.pod.in#L71-L79

Did you notice the last sentence?  "If this option is present, then the B<-rawin> option must be also specified."

This implies that you can use `-rawin` without `-digest`, but not the other way around, and that the defaults mentioned in the `-digest` documentation are only valid when `-rawin` is used.  I tried one of your experiments with that in mind:

``` console
$ echo -n "0123456789ABCDEF0123456789ABCDEF" >test256.dat
$ cat test256.dat <(printf "extended") >test256+.dat
$ ls -l test256*.dat | sort | awk '{print $9": "$5" bytes" }'
test256.dat: 32 bytes
test256+.dat: 40 bytes
$ export SM2KEY=test/certs/sm2.key
$ openssl pkeyutl -inkey $SM2KEY -in test256+.dat -sign -out test.sm2.sig
Public Key operation error
$ openssl pkeyutl -inkey $SM2KEY -in test256+.dat -sign -out test.sm2.sig -rawin
$ openssl pkeyutl -inkey $SM2KEY -in test256+.dat -verify -sigfile test.sm2.sig -rawin
Signature Verified Successfully
```

So it does seem like a default digest was applied indeed, just because I used `-rawin`

**Comment by levitte** [comment]
I agree that the remark about `-rawin` in the documentations of `-digest` could be made more prominent

**Comment by DDvO** [comment]
> I agree that the remark about `-rawin` in the documentations of `-digest` could be made more prominent

Yes - but note that it just says:
> If this option is present,  then the `-rawin` option must be also specified.

The PR #22910 also will help in this regard. So far, failing to add -`rawin` when `-digest` throws a (nur useful) error, but with one of the proposed changes the `rawin` gets implied by `-digest`, which is pretty convenient.

**Comment by DDvO** [comment]
Note that my documentation bug report here is about the case that `-digest` is NOT given.
Then, without `-rawin`, no automatic hashing is performed (for good reason, being a low-level operation).

**Comment by levitte** [comment]
It should probably be clarified that those defaults are only applicable with `-rawin`

**Comment by DDvO** [comment]
> It should probably be clarified that those defaults are only applicable with `-rawin`

Yes - this is what I suggested [above](https://github.com/openssl/openssl/issues/25827#issuecomment-2446059906).

If this is the agreed way forward, I could either add this to #22910 in a separate commit,
which then should be backported (together with further doc fixes already included in a separate commit here)
or do all those fixes in a separate bugfix PR.

**Comment by levitte** [comment]
I'd suggest a separate documentation enhancement PR

**Comment by DDvO** [comment]
> I'd suggest a separate documentation enhancement PR

Done - see #25831
