### ISSUE TITLE
openssl-1.0.2k - domd - ../../util/domd: !: not found

### ISSUE THREAD

**Issue by atuzhilova** [openssl/openssl#2588]

**Comment by atuzhilova** [comment]
The changes in util/domd  file leads to errors:

ccbohadm@mpssolbld01 {68} make depend
making depend in crypto...
makedepend: warning:  cryptlib.c: 150: #error("Unrecognized compiler protocol for variable argument lists")
../util/domd: !: not found
.......
making depend in crypto/cmac...
../../util/domd ../.. -MD makedepend -- -KPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -xcode=pic32 -xtarget=ultra -xarch=v8plus -xO5 -xstrconst -xdepend -Xa -DB_ENDIAN -DBN_DIV2W -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DGHASH_ASM -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include -DOPENSSL_NO_DEPRECATED -DOPENSSL_NO_EC_NISTP_64_GCC_128 -DOPENSSL_NO_GMP -DOPENSSL_NO_IDEA -DOPENSSL_NO_JPAKE -DOPENSSL_NO_LIBUNBOUND -DOPENSSL_NO_MD2 -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_SCTP -DOPENSSL_NO_SSL_TRACE -DOPENSSL_NO_SSL2 -DOPENSSL_NO_STORE -DOPENSSL_NO_UNIT_TEST -DOPENSSL_NO_WEAK_SSL_CIPHERS --  cmac.c cm_ameth.c cm_pmeth.c
makedepend: warning:  cmac.c: 150: #error("Unrecognized compiler protocol for variable argument lists")
../../util/domd: !: not found
making depend in ssl...
makedepend: warning:  s2_meth.c: 150: #error("Unrecognized compiler protocol for variable argument lists")
../util/domd: !: not found
making depend in engines...
makedepend: warning:  e_4758cca.c: 150: #error("Unrecognized compiler protocol for variable argument lists")
makedepend: warning:  e_padlock.c: 92: #   error "Only OpenSSL >= 0.9.7 is supported"
../util/domd: !: not found
making depend in engines/ccgost...
makedepend: warning:  gost2001.c: 150: #error("Unrecognized compiler protocol for variable argument lists")
../../util/domd: !: not found
making depend in apps...
makedepend: warning:  openssl.c: 150: #error("Unrecognized compiler protocol for variable argument lists")
../util/domd: !: not found
making depend in test...
makedepend: warning:  bntest.c: 150: #error("Unrecognized compiler protocol for variable argument lists")
../util/domd: !: not found
making depend in tools...

**Comment by mattcaswell** [comment]
This is a known issue on some platforms. See fix here: 0d37bd8058.

**Comment by atuzhilova** [comment]
This issue does not appear on 1.0.2j version 
and it has gone on 1.0.2k version after domd file was replaced with the one from previous version.
