### ISSUE TITLE
OQS provider submodule in feature/quic-server branch failing tests

### ISSUE THREAD

**Issue by nhorman** [openssl/openssl#25911]
The oqsprovider external tests are failing on the feature/quic-server branch. See [here](https://github.com/openssl/openssl/actions/runs/11727985526/job/32717463711?pr=25890) for an example.

The problem appears to be that the submodule commit level is at a point where the x25519_kyber512 group isn't recognized by openssl s_client during testing, causing the test to fail (specifically resulting in the cloudflaire server sending a handshake alert about it).

Fix appears to be updating the submodule to the commit level held in the master branch, and porting the test/reciepies/95-test-oqsprovider_data/* files to the quic-server feature branch

**Comment by t8m** [comment]
We simply need to rebase the quic-server branch.

**Comment by t8m** [comment]
The quic-server branch was rebased.
