### ISSUE TITLE
Should jitter RNG use salt for nonce generation?

### ISSUE THREAD

**Issue by xnox** [openssl/openssl#25917]
In 

https://github.com/openssl/openssl/blob/012353bdf21b98def920ac317b94c4a9ed501b79/crypto/rand/prov_seed.c#L114

salt is being passed in.

But in

https://github.com/openssl/openssl/blob/012353bdf21b98def920ac317b94c4a9ed501b79/providers/implementations/rands/seed_src_jitter.c#L170

addin is not used at all.

Should it be added to the pool at least the same way as it is done here in this non-EVP get_nonce implementation?

https://github.com/openssl/openssl/blob/012353bdf21b98def920ac317b94c4a9ed501b79/crypto/rand/prov_seed.c#L91

**Comment by paulidale** [comment]
I'm not sure if this should be treated as a bug or a feature request: if the RNG is working, the salt isn't doing anything useful.

Still, it won't cause any harm adding the salt so we should do it at some point.
