### ISSUE TITLE
Does RAND_bytes() use /dev/random, or /dev/urandom() on Linux ?

### ISSUE THREAD

**Issue by vk18anubhav** [openssl/openssl#25946]
Does RAND_bytes() use /dev/random, or /dev/urandom() on Linux ?  Is this in some way configureable ?

Is the behaviour of RAND_bytes() same for FIPS and non-FIPS mode ?

**Comment by tom-cosgrove-arm** [comment]
This question should really be asked in the Discussions, not raised as an issue

**Comment by vk18anubhav** [comment]
https://github.com/openssl/openssl/discussions/25951

Asked in discussion. Closing this one
