### ISSUE TITLE
build fails if older OpenSSL pre-installed on system [master branch]

### ISSUE THREAD

**Issue by mandree** [openssl/openssl#2597]
When trying to build OpenSSL "master" from Git (on x64_64 = amd64 Ubuntu 16.04 LTS), the configuration succeeds, but the build fails because the compiler grabs incompatible system includes for OpenSSL, when it should prefer the new includes in the Git checkout.

Workaround:
```./config -I$(pwd)/include```

(where ```$(pwd)``` means: expand the results of ```pwd``` here, formerly ``` `pwd` ```)

Please make the equivalent of this "prefer local includes over system includes" part of all relevant branches.

**Comment by levitte** [comment]
I'm not sure I understand...  if you do `make`, all compile commands already have at least one `-I` option.  Why does that one make a difference?

**Comment by mandree** [comment]
It does make a difference because it makes sure that the local include files from the new source hierarchy (Git checkout, for instance) get preference over the older stuff in /usr/[local/]include. Try building OpenSSL master while you have 1.0.2 includes in /usr/include, it will break. Making sure that the compiler prefers /path/to/checkout/include over the old droppings in the system permits you to build a bleeding-edge OpenSSL even if old stuff remains installed.

The underlying issue remains invisible though in continuous-integration, chroot or jail or other clean-room builds.

**Comment by levitte** [comment]
That's an operation I do every day on my laptop, and here's a random command line picked now:

```
clang  -I. -Iinclude -I../master -I../master/include -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O0 -g -pthread -m64 -DL_ENDIAN -Wextra -Qunused-arguments  -DDEBUG_UNUSED -Wswitch -DPEDANTIC -pedantic -Wno-long-long -Wall -Wsign-compare -Wmissing-prototypes -Wshadow -Wformat -Wtype-limits -Wno-parentheses-equality -Werror -Qunused-arguments -Wextra -Wswitch-default -Wno-unused-parameter -Wno-missing-field-initializers -Wno-language-extension-token -Wno-extended-offsetof -Wconditional-uninitialized -Wincompatible-pointer-types-discards-qualifiers -Wmissing-variable-declarations -fPIC -DOPENSSL_USE_NODELETE -MMD -MF ssl/d1_msg.d.tmp -MT ssl/d1_msg.o -c -o ssl/d1_msg.o ../master/ssl/d1_msg.c
```

That's from a build of current master, and there's nothing special at all with this, I configured like this: `../master/config -d --strict-warnings`

In that line, I see this: `-I. -Iinclude -I../master -I../master/include`
That gives the build paths to all the include files it needs.  Specifically, the last one corresponds exactly to the additional `-I` you suggest.
This is standard, this is how things are supposed to work, so I'm asking for a somewhat deeper analysis of why it's not working for you specifically.

**Comment by mandree** [comment]
Understood. I've tried to reproduce this in several ways, but failed.
