### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by Rayray-nel** [openssl/openssl#25973]
openssl genpkey -algorithm RSA -out key.pem

**Comment by tom-cosgrove-arm** [comment]
I'm closing this issue as it doesn't really say anything.

If you wish to ask a question about using OpenSSL, then please [start a discussion](https://github.com/openssl/openssl/discussions).

If you have found an issue with OpenSSL itself, then please raise another issue, but include a descriptive title and enough information that we're about to reproduce any problem that you have found.
