### ISSUE TITLE
OS Zoo CI emails for forks

### ISSUE THREAD

**Issue by sevan** [openssl/openssl#25974]
I have a fork of this repo which I sync on the rare occasion.
I've noticed that despite not committing any changes to the repo, the email about build runs keep on coming from the OS Zoo CI.
I was wondering is that intentional? it is pretty annoying and for sure a waste of resources.
On average I'm getting around 6 email per day about failed build attempts.

**Comment by nhorman** [comment]
Just turn off actions in your forked repo

**Comment by sevan** [comment]
Thanks, I did that some hours ago, received an email again to notify me that the run failed, maybe it's a delayed response.
I thought I'd file this in case it wasn't the desired behaviour (you actually want to work like this across 10,000+ forks?).
I'll keep an eye on the email to see if it stops over the next couple of days.

**Comment by sevan** [comment]
Disabling github actions on my fork and waiting for a couple of days stopped the emails. Sync'd fork again and no new emails have showed up. Thanks :)
