### ISSUE TITLE
Sending decrypt_error alert in the processing of  RSA-encrypted premaster secret message.

### ISSUE THREAD

**Issue by Liu-ErMeng** [openssl/openssl#26019]
https://github.com/openssl/openssl/blob/0c64b1ca0315edf6c3e947b53ea13fecc6da7dad/crypto/rsa/rsa_ossl.c#L560-L564
Accroding to the [recommendations ](https://tools.ietf.org/html/rfc5246#section-7.4.7.1)of RFC5246:
```
   In any case, a TLS server MUST NOT generate an alert if processing an
   RSA-encrypted premaster secret message fails, or the version number
   is not as expected.  Instead, it MUST continue the handshake with a
   randomly generated premaster secret. 
```
But I found when the ciphertext larger than the bytes of RSA's public key, openssl will terminated and send a decryption error alert.

**Comment by Sashan** [comment]
Hello,

can you share more details on how to reproduce the issue? ideally if you can provide us with some script or reproducer.

thanks a lot.

**Comment by Liu-ErMeng** [comment]
> Please note that failing in such situation where the ciphertext is larger than n value of the RSA key before actually performing any decryption is not revealing any information to the attacker. Thus the recommendation does not apply.

Emm, that's make sense, I get it.
