### ISSUE TITLE
tls 1.3 client handshake error

### ISSUE THREAD

**Issue by nutinshell** [openssl/openssl#2602]
```openssl s_client -tls1_3 -connect test.com:443
CONNECTED(00000003)
140379806160640:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1458:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 215 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1486914407
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

server using the same version OpenSSL

**Comment by kroeckx** [comment]
test.com doesn't seem to support TLS 1.3. You're telling s_client
to only support TLS 1.3, so I think it's normal that you get an
error message. The reason that the server directly sends an alert
is because we only send TLS 1.3 ciphers and it doesn't know any of
them.

**Comment by nutinshell** [comment]
@kroeckx test.com is just a fake local domain, server is my own server.

**Comment by noloader** [comment]
@kroeckx, @nutinshell.

> test.com doesn't seem to support TLS 1.3. 

It looks like the TLS working group has a small list of TLS 1.3 test machines at [tlswg/tls13-spec | Implementations](https://github.com/tlswg/tls13-spec/wiki/Implementations). Maybe a test server can be found on the page. I'm guessing Mozilla's `ls13.crypto.mozilla.org` is available to the public.

**Comment by richsalz** [comment]
TLS 1.3 is still a work in progress.  Closing this.
