### ISSUE TITLE
doc/build.info.in is a horrible name

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#26076]
*EVERYWHERE ELSE* if a file foo.bar.in exists, then the makefile treats it as a dependency and builds foo.bar and it does that during the `make` process.

The file `doc/build.info.in` isn't like that. I understand why: you can't regenerate a makefile on the fly.  The file should be called something else, like `mk-build-info` or `util/doc-mk-build-info`

**Comment by t8m** [comment]
doc/build.info.in is called doc/build.info.in because it is a template from which doc/build.info is built. Yeah, it is not done during regular make but only during `make update`. That IMO is not a reason to call it with a name that would sound like this is an actual script.

Yeah we might want to consider to call it doc/build.info.template but I am not convinced it is a good idea.

@levitte might have an opinion?

**Comment by levitte** [comment]
We commonly use `{foo}.in` as template files to generate `{foo}` from, that was never tied to the Makefile per se (like `configdata.pm` is built from `configdata.pm.in`, and that happens in `Configure`).

I never saw that as strictly tied to the dependency mechanism in the Makefile, albeit we do have a ton of such cases (specifically generated by DEPEND[foo]=foo.in` and `GENERATE[foo]=foo.in` pairs in the `build.info` files).

I'm not sure I see the need for a separate script to build `doc/build.info`, if that's just going to wrap around `util/dofile.pl`.
Renaming `doc/build.info.in` → `doc/build.info.template` could be a thing if you must...  from my perspective, that would be confusing, but if others find that to be clearer, sure, why not.

**Comment by levitte** [comment]
Perhaps the thing that was confusing the matter was a belief that the `{foo}.in` → `{foo}` generation rules in Makefile were just added magically.  This is not so...  they're all *very* explicitly defined in the diverse `build.info` files

**Comment by richsalz** [comment]
I don't have anything else to add beyond my initial comment.  If you prefer to close those, that's fine.
