### ISSUE TITLE
Update Makefile to make build successful when override CDPATH

### ISSUE THREAD

**Issue by lenage** [openssl/openssl#261]
I set my `CDPATH` to `~/Project` in someday, and when i run `make` in openssl root dir.

It shows `cd: no such directory` error to me.

and then i removed `CDPATH` export and it works again.

is it possible to update Makefile to avoid this error?

**Comment by richsalz** [comment]
What would you have us do?

**Comment by lenage** [comment]
something like using absolute path in Makefile? (or can't do that in Makefile, I'm sorry that i don't know much for Makefile).

**Comment by richsalz** [comment]
CDPATH should only be used when you can't find the path.  OpenSSL makefiles never cd to non-existant paths.  Something is wrong with your shell.  There is nothing for us to do here.
