### ISSUE TITLE
Bug using flag "--with-rand-seed" for non x86 architectures

### ISSUE THREAD

**Issue by eyalgolan1337** [openssl/openssl#26117]
The build.info file found under rands/seeding/build.info has several condition relating to the type of the target configuration.
Here is the code from that file:

```
$COMMON=rand_unix.c rand_win.c rand_tsc.c
IF[{- $config{target} =~ /vxworks/i -}]
  $COMMON=$COMMON rand_vxworks.c
ENDIF
IF[{- $config{target} =~ /vms/i -}]
  $COMMON=$COMMON rand_vms.c
ENDIF
IF[{- !$disabled{asm} && $config{target} =~ '.*aarch64' -}]
  $COMMON=$COMMON rand_cpu_arm64.c
ELSE
  $COMMON=$COMMON rand_cpu_x86.c
ENDIF

SOURCE[../../../libdefault.a]=$COMMON
```

I believe that due to oversight, the conditions don't take into consideration the fact that the target architecture configured to use openssl with the requested flag might differ from all the options provided by these conditions.
In addition, since the default behavior for not following any of the conditions provided in the file is using the file "rand_cpu_x86.c", builds for architectures (such as PPC, MIPS, etc) may fail due to the usage of an incompatible implementation for the target architecture. 

A quick fix for this issue can be to change the "ELSE" in the file into a condition, as described in the following code block:

```
IF[{- $config(target) =~ '.*x86.*' -}]
``` 

This way, the usage of "rand_cpu_x86.c" will be guaranteed to only be used for x86 architectures (such as IA32, and AMD64) .

**Comment by mattcaswell** [comment]
> I believe that due to oversight, the conditions don't take into consideration the fact that the target architecture configured to use openssl with the requested flag might differ from all the options provided by these conditions.

I'm somehow missing the point of the bug you are trying to report here. Can you give a concrete example of how we can go wrong here?

**Comment by paulidale** [comment]
It's not ideal and ought to be addressed but I'm not seeing a bug here.

You have to explicitly configure with `--with-rand-seed=rdcpu` when building for a platform where that isn't supported.
I'd suggest choosing another seed source that is supported for that target.

If you've got a specific target where you want this option supported, feel free to submit a pull request.

**Comment by t8m** [comment]
In INSTALL.md, it is explicitly mentioned:

**rdcpu**
Use the RDSEED or RDRAND command on x86 or RNDRRS command on aarch64 if provided by the CPU.

I interpret that meaning you cannot use `rdcpu` on other architectures.

Please feel free to submit a pull request with any documentation improvements you see fit.

**Comment by tom-cosgrove-arm** [comment]
> The problem is basically that the default behavior uses the x86 architecture file, while not supporting any other that may still need to use the flag.

Only x86 and aarch64 currently support this flag. To support additional architectures, changes similar to those in #15361 would need to be made for that architecture.
