### ISSUE TITLE
OpenSSL accepts a v1 certificate which has subject unique ID

### ISSUE THREAD

**Issue by chenchuAtXidian** [openssl/openssl#2611]
Summary: As for a certificate which has subject unique ID, its version should be v2 or v3.
   
   Versions of OpenSSL: 1.0.1u, 1.0.2j, and 1.1.0b
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  openssl verify -CAfile basicCA.pem 5.pem 
   
   Actual results: 5.pem: OK
   Expected results: OpenSSL should reject such a certificate.
   
   The attachement contains basicCA.pem and 5.pem.
   
   Please rename the file "test cases.txt" as "test cases.zip" and extract it.

[test cases.txt](https://github.com/openssl/openssl/files/771186/test.cases.txt)

**Comment by richsalz** [comment]
Thanks, but we try to be very liberal in what we accept, as there are all sorts of bad/bogus/malformed certificates out there.  If an application cares, it can do its own checks.
