### ISSUE TITLE
OpenSSL accepts a v2 certificate which has no unique ID but extensions

### ISSUE THREAD

**Issue by chenchuAtXidian** [openssl/openssl#2613]
Summary: As for a certificate which has no unique ID but extensions, its version should be v3.
   
   Versions of OpenSSL: 1.0.1u, 1.0.2j, and 1.1.0b
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  openssl verify -CAfile basicCA.pem 9.pem 
   
   Actual results: 9.pem: OK
   Expected results: OpenSSL should reject such a certificate.
   
   The attachement contains basicCA.pem and 9.pem.
   
   Please rename the file "test cases.txt" as "test cases.zip" and extract it.

[test cases.txt](https://github.com/openssl/openssl/files/771250/test.cases.txt)

**Comment by richsalz** [comment]
Thanks, but we try to be very liberal in what we accept, as there are all sorts of bad/bogus/malformed certificates out there.  If an application cares, it can do its own checks.
