### ISSUE TITLE
Cannot add new compression schemes

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2615]
In 1.1.0, by making ```COMP_METHOD``` and ```COMP_CTX`` we inadvertently made it impossible to add new compression schemes at run-time; you have to modify the OpenSSL source.

By our definitions, this is a bug.  This issue records that bug.

**Comment by vdukhovni** [comment]
I chatted with Christos Zoulas, and we've arrived at:

* The function should return an error if called.
* The function should be removed from the relevant public headers, leading to compile-time warnings/errors.

Since there was no way to use it in 1.1.0, there is no need to bring it back.

**Comment by richsalz** [comment]
I am going to close this.  It's a bug, but one we will not fix.  Compression is moving out of the TLS layer because of security concerns.  So not worth fixing.
