### ISSUE TITLE
Off-by-one output buffer size requirement in EVP_UpdateDecrypt documentation

### ISSUE THREAD

**Issue by plopresti** [openssl/openssl#26169]
OpenSSL version: Any, up to and including 3.4.0

The [documentation for EVP_DecryptUpdate](https://github.com/openssl/openssl/blob/openssl-3.4.0/doc/man3/EVP_EncryptInit.pod#user-content-evp_decryptinit_ex2-evp_decryptinit_ex-evp_decryptupdate-and-evp_decryptfinal_ex) currently says:

> The parameters and restrictions are identical to the encryption operations except that if padding is enabled the decrypted data buffer out passed to EVP_DecryptUpdate() should have sufficient room for (inl + cipher_block_size) bytes

I believe this is incorrect, and the actual requirement is identical to the encryption operations; that is, the true minimum output buffer size is (inl + cipher_block_size - 1).

One way to see this by reasoning about it. The "worst case" for the relative size of inl vs outl is to encrypt one byte at a time until you overflow the internal buffer. For both encryption and decryption operations, this ends with providing one byte of input (inl == 1) and getting one block of output (outl == cipher_block_size). The difference in how encrypt and decrypt flush their blocks do not change this; you always get at most cipher_block_size bytes of output when you provide one byte of input.

We can also demonstrate this with a test program. The following program repeatedly calls EVP_UpdateDecrypt with randomly-sized input blocks and checks if the output length is within the proposed bounds. The test results indicate that the output length is at most inl + cipher_block_size - 1 bytes, similar to EVP_UpdateEncrypt.

```
#include <openssl/evp.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

int main() {
    EVP_CIPHER_CTX *ctx;
    const EVP_CIPHER *cipher;
    unsigned char key[EVP_MAX_KEY_LENGTH] = "0123456789abcdef";
    unsigned char iv[EVP_MAX_IV_LENGTH] = "0123456789abcdef";
    unsigned char in[32];
    unsigned char out[EVP_MAX_BLOCK_LENGTH + 32];
    int outl, inl;
    int cipher_block_size;

    OpenSSL_add_all_algorithms();
    cipher = EVP_aes_128_cbc();
    cipher_block_size = EVP_CIPHER_block_size(cipher);

    ctx = EVP_CIPHER_CTX_new();
    EVP_DecryptInit_ex(ctx, cipher, NULL, key, iv);

    srand(time(NULL));

    for (int i = 0; i < 10000 ; i++) {
        inl = rand() % 33; // Random length between 0 and 32
        for (int j = 0; j < inl; j++) {
            in[j] = rand() % 256; // Random byte values
        }

        if (!EVP_DecryptUpdate(ctx, out, &outl, in, inl)) {
            fprintf(stderr, "Error in EVP_DecryptUpdate\n");
            return 1;
        }
        if (outl > inl + cipher_block_size - 1) {
            fprintf(stderr, "Output length exceeds expected maximum\n");
            return 1;
        }
        printf("Iteration %d: Input length = %d, Output length = %d\n", i, inl, outl);
    }

    EVP_CIPHER_CTX_free(ctx);
    return 0;
}
```

No matter what sequence of blocks you feed to EVP_DecryptUpdate, outl is always at most inl + cipher_block_size - 1.

**Comment by paulidale** [comment]
This is a documentation issue, although the current documentation isn't terrible -- using the documented size won't result in an error.  I cannot think of a reason why other cipher modes would require the extra byte.  Anyone?  

BTW: a systematic variation of the length would be more reliable than the stochastic variation.  Nonetheless, 10,000 iterations will make the probability of not getting a specific length pretty small.

**Comment by plopresti** [comment]
I agree the documented value will work.

However, in my application, I have a pre-existing output buffer and I am adjusting the inl value to avoid overflowing it. (Think of a zlib-like streaming interface.) Since the output of DecryptUpdate is always an integral number of cipher blocks, having this calculation off by one will generally cause me to waste a block, not just one character, on each call.

I agree my test case is imperfect. One reason I am filing this bug report is to confirm my belief so I can write my code accordingly.

Thanks for your reply!

**Comment by kroeckx** [comment]
An other way to look at this is that we will maximally cache `cipher_block_size - 1`, so we can maximally return `inl` more.

**Comment by plopresti** [comment]
@kroeckx That reasoning is correct for EVP_UpdateEncrypt, where each block is encrypted as soon as the final byte arrives.

I believe it is not quite correct for EVP_UpdateDecrypt, where the full block (of `cipher_block_size` bytes) remains cached until the _next_ byte arrives. It is necessary to hold the full block during decryption because the block might be the final padding block, with the next call being EVP_DecryptFinal(). (Aside: I am basing this on my understanding of CBC mode padding; I have not tried to read the source code. I am pretty sure it is correct though.)

In fact, I suspect this difference is what caused someone to conclude the output buffer requirements are different for encrypt vs. decrypt.

But the requirements are actually the same. Whether you cache `cipher_block_size - 1` bytes and then flush on the next byte (encrypt), or you cache `cipher_block_size` bytes, flush on the next byte, and then cache the new byte (decrypt), you still only ever need `inl + cipher_block_size - 1` bytes in the output buffer.

**Comment by KanPlus** [comment]
The inl in  EVP_UpdateDecrypt is the length of ciphertext. The padding is for plaintext，but not for ciphertext, what is the case that the output length is at most inl + cipher_block_size - 1 bytes?

**Comment by plopresti** [comment]
@KanPlus Run the test program at the top of this issue for an example.

The ciphertext size is a multiple of the cipher block size. The padding extends the plaintext so that both its and the ciphertext's size are such a multiple.

Both encrypt and decrypt keep an internal buffer of cipher_block_size bytes to handle being fed input in arbitrary-size pieces; e.g. one byte at a time. When they need to flush that buffer, outl can be larger than inl. Although encrypt and decrypt handle this buffer and its flushing slightly differently, in both cases the output can be up to (but no more than) inl + cipher_block_size - 1 bytes.
