### ISSUE TITLE
There is a memory leak defect at line 407 in the file /openssl/providers/implementations/kem/ecx_kem.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [openssl/openssl#26184]
In the file /openssl/providers/implementations/kem/ecx_kem.c, at line 391, a pointer variable named privkey is defined. This variable is assigned a new dynamically allocated memory region by the function ossl_ecx_key_allocate_privkey at line 400. According to the implementation of ossl_ecx_key_allocate_privkey, the newly allocated memory region points to key->privkey. When the if statement at line 401 returns false, it indicates that the dynamic memory region pointed to by privkey has been successfully allocated. If the if statement at line 406 returns true, the function will jump to the err label via the goto statement at line 407. During this process, the dynamic memory region pointed to by privkey is neither used, as seen at line 413, nor freed, resulting in a memory leak defect, as shown in the diagram below:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_33.png

Please note that the defect detection report is generated by the static analysis tool. Although it has been manually verified, false positives may still exist.

**Comment by tom-cosgrove-arm** [comment]
Err, no, this isn't a leak. The returned value from `ossl_ecx_key_allocate_privkey()` is an alias to `key->privkey`, and this is released by the call to `ossl_ecx_key_free()` in `err:` (specifically, `ossl_ecx_key_free()` does `OPENSSL_secure_clear_free(key->privkey, key->keylen);`

**Comment by LuMingYinDetect** [comment]
> Err, no, this isn't a leak. The returned value from `ossl_ecx_key_allocate_privkey()` is an alias to `key->privkey`, and this is released by the call to `ossl_ecx_key_free()` in `err:` (specifically, `ossl_ecx_key_free()` does `OPENSSL_secure_clear_free(key->privkey, key->keylen);`

Thank you for your reply!
