### ISSUE TITLE
OpenSSL accepts a certificate which has a fractional validity

### ISSUE THREAD

**Issue by chenchuAtXidian** [openssl/openssl#2620]
Summary: As for a certificate, its validity should not be fractional. However, OpenSSL accepts such a certificate.
   
   Versions of OpenSSL: 1.0.1u, 1.0.2j, and 1.1.0b
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  openssl verify -CAfile ca.pem 22.pem 
   
   Actual results: 22.pem: OK
   Expected results: OpenSSL should reject such a certificate.
   
   The attachement contains ca.pem and 22.pem.
   
   Please rename the file "test cases.txt" as "test cases.zip" and extract it.

[test cases.txt](https://github.com/openssl/openssl/files/772818/test.cases.txt)

**Comment by richsalz** [comment]
What do you mean by fractional validity?

And please just cut and pate the PEM objecdts into your issue.

**Comment by levitte** [comment]
... Or into a gist

**Comment by chenchuAtXidian** [comment]
The notBefore of 22.pem is "Not Before: Aug  1 10:30:26.6 2008 GMT", in which the part of seconds (i.e.  "26.6") is fractional.  According to RFC 5280, "GeneralizedTime values MUST NOT include fractional seconds". Thank you @richsalz and @levitte.

**Comment by bernd-edlinger** [comment]
X509_cmp_time ignores the fractional seconds on purpose:

```
    /*
     * Note that the following (historical) code allows much more slack in the
     * time format than RFC5280. In RFC5280, the representation is fixed:
     * UTCTime: YYMMDDHHMMSSZ
     * GeneralizedTime: YYYYMMDDHHMMSSZ
     */
...
        /*
         * Skip any (up to three) fractional seconds...
         * TODO(emilia): in RFC5280, fractional seconds are forbidden.
         * Can we just kill them altogether?
         */
```

But it also allows time zones, i.e. +-HH:MM instead of Z,
the ASN1_UTCTIME_print and ASN1_GENERALIZEDTIME_print
look like they do not print this offset.

**Comment by chenchuAtXidian** [comment]
@bernd-edlinger Some functions may ignore the fractional parts. If we use the command "openssl x509 -in 22.pem -noout -text", the fractional parts will be shown. Is it better to give warnings for the fractional seconds or reject correponding certificates?  Thank you @bernd-edlinger!

**Comment by bernd-edlinger** [comment]
Actually the time zone is adjusted in the wrong direction.
And it can be up to +/-100 hours, that may be surpisisng...

**Comment by bernd-edlinger** [comment]
Maybe we should ask @ekasper ?

**Comment by chenchuAtXidian** [comment]
OK @bernd-edlinger

**Comment by ekasper** [comment]
The open TODO around sloppy X509 time formats is here:
https://github.com/openssl/openssl/blob/master/crypto/x509/x509_vfy.c#L1806

@davidben I checked that BoringSSL hasn't removed this either - any particular backwards compat reasons, or do you think we can just make the parsing reject times that don't comply with RFC 5280?

**Comment by richsalz** [comment]
why should we?  just to enforce correctness?

**Comment by snhenson** [comment]
Note that the RFC5280 says "GeneralizedTime values MUST NOT include fractional seconds" that is generated certificates complying with the profile must not include fractional seconds.

It does not IMHO explicitly say what should be done if a certificate containing fractional seconds is encountered.

**Comment by ekasper** [comment]
@richsalz - yes, and also to simplify the behaviour and the parsing code. The reason I went into this code in the first place was that there was a security vuln in it.

**Comment by davidben** [comment]
@ekasper Re BoringSSL, we consider everything in crypto/asn1 and crypto/x509 to be legacy baggage. We're replacing it wholesale, API and all, rather than working on it incrementally. Don't take anything in there as an indication of how we think ASN.1 and X.509 should work. :-P

Enforcing this in code sounds like a good idea. The new certificate code we're working on in Chromium rejects fractional seconds, though I don't know if it's been battle-tested against the real world yet. Check CT logs?

**Comment by bernd-edlinger** [comment]
and time zones?

**Comment by davidben** [comment]
Not sure if that was directed at me. The code in Chromium requires GMT.

**Comment by kroeckx** [comment]
There have been very few certificates that don't follow my very strict checks in x509lint. I think it's like a total of 3.

**Comment by richsalz** [comment]
would you be willing to merge your x509lint into a "-strict" option in verify?

**Comment by kroeckx** [comment]
There are all kinds of strict things that could be enabled, and I'm not sure we want to do all of them.

**Comment by briansmith** [comment]
I wrote Firefox's certificate parser in mozilla::pkix. It doesn't accept fractional seconds and requires the timezone to be expressed as "Z" (Zulu, GMT time), not in "[+-]HH:MM" notation. See https://github.com/briansmith/mozillapkix/blob/2fe3687441c06946b6d00a658a7ab8d981246737/lib/pkixder.cpp#L462-L477.

I only remember one compatibility bug report for one website in Firefox regarding this, so I think it is a safe change to make.

**Comment by richsalz** [comment]
@briansmith thanks, that's very useful to know!

**Comment by kroeckx** [comment]
The checks that x509lint does is a strict conformance to RFC5280, which includes:
- No fractions
- Only UTC, the Z is required
- Between 1950 and 2050 it must be UTCTime, otherwise GeneralizedTime
- It checks that the date and time are valid

As far as I remember, most certificates that had a problem with any of those checks where using GeneralizedTime while they shouldn't. NSS doesn't seem to enforce that part, but does all the others.

I seem to have 35 certificates that chain to the mozilla root store that fail one of the above checks.

**Comment by ekasper** [comment]
https://github.com/openssl/openssl/pull/2668

Now enforcing:

* no fractions
* no offsets
* seconds must be present
* Z is required
* digits must be 0-9 (but we don't check that the date/time is valid)

For the test certificate we now get

```
error 13 at 0 depth lookup: format error in certificate's notBefore field
error 22.pem: verification failed
```
