### ISSUE TITLE
OpenSSL accepts a certificate which has duplicate certificate policy IDs without any warning

### ISSUE THREAD

**Issue by chenchuAtXidian** [openssl/openssl#2621]
Summary: As for a certificate, its certificate policy IDs should not be duplicate. However, OpenSSL accepts such a certificate.
   
   Versions of OpenSSL: 1.0.1u, 1.0.2j, and 1.1.0b
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  openssl verify -CAfile ca.pem 43.pem 
   
   Actual results: 43.pem: OK
   Expected results: OpenSSL should reject such a certificate.
   
   The attachement contains ca.pem and 43.pem.
   
   Please rename the file "test cases.txt" as "test cases.zip" and extract it.

[test cases.txt](https://github.com/openssl/openssl/files/772838/test.cases.txt)

**Comment by briansmith** [comment]
In general it's pretty unreasonable to detect and reject duplicates in all the cases where the spec says that duplicates are not allowed. In particular, the extra work to reject duplicates requires extra code which means more room for vulnerabilities. Therefore I think bug reports like this should be closed as "works as intended" unless the duplicate values actually lead to a real security problem.

**Comment by chenchuAtXidian** [comment]
I am afriad I cannot agree with briansmith's comment "In particular, the extra work to reject duplicates requires extra code which means more room for vulnerabilities. "  Developers should make their programs more and more robust and bugs will be eliminated early or late. Threefore, in my opinion, OpenSSL should give warnings for this case at least. Not all bugs lead to security problems but bugs should be fixed once they are found.

**Comment by briansmith** [comment]
> Not all bugs lead to security problems but all bugs should be fixed once they are found.

Does RFC 6818 say that the *receiver* (verifier) of a certificate chain is required to reject duplicates? IIRC, it doesn't require that. It only requires that the *producer* to ensure there are no duplicates. The receiver/verifier isn't required to check that the producer did everything correctly.

**Comment by richsalz** [comment]
We disagree.  Unless or until duplicate policy OID's are found to be a security flaw, there is nothing wrong with the current behavior.

**Comment by chenchuAtXidian** [comment]
@brainsmith  According to Sec 4..2.1.4 of RFC 5280, "A certificate policy OID MUST NOT appear more than once in a certificate policies extension". Here "MUST NOT" indicates absolute prohibitions of specifications.

**Comment by richsalz** [comment]
Yes.  But we will do it anyway.  There are *many* real-world cases where specs are not followed.

**Comment by briansmith** [comment]
> @brainsmith According to Sec 4.2.1.4 of RFC 5280, "A certificate policy OID MUST NOT appear more than once in a certificate policies extension". Here "MUST NOT" indicates absolute prohibitions of specifications (RFC 2119).

Yes, one MUST NOT produce such a certificate. However, there is no requirement that one MUST reject such a certificate. It's a requirement on the producer, not the consumer.

**Comment by chenchuAtXidian** [comment]
@briansmith 

Do producer and consumer rules have definitions? If not, how to understand them? Can rules involving "conforming CAs" or "CAs conforming ..." be regarded as producer rules. Are there other cases?

**Comment by perlun** [comment]
> Do producer and consumer rules have definitions? If not, how to understand them?

The robustness principle: _Be conservative in what you do, be liberal in what you accept from others_, a.k.a Postel's Law. [More information](https://en.wikipedia.org/wiki/Robustness_principle)
