### ISSUE TITLE
Server silently accepts ClientHello messages with invalid Extension lengths

### ISSUE THREAD

**Issue by jurajsomorovsky** [openssl/openssl#265]
While playing with the OpenSSL server (version 1.0.2a), I found out it is possible to send ClientHello messages with invalid extension lengths where the extension length is larger than the amount of the extension data. If the server receives such a ClientHello message, it correctly omits further extension processing. However, it does not return any decoding error and proceeds with the handshake.

Even though this does not lead to any security vulnerability, I believe returning a decoding alert would be a correct practice (or is there any compatibility reason for not returning such an alert?)
I believe, this issue should be fixed here:
https://github.com/openssl/openssl/blob/master/ssl/t1_lib.c#L1941

**Comment by x64architecture** [comment]
Just to note this behavior was changed in [this](https://github.com/openssl/openssl/commit/c27c9cb4f7ab74d772521fd927918f354724c2fc) commit

**Comment by mattcaswell** [comment]
This was fixed a while ago in d27259927. Closing.
