### ISSUE TITLE
Problems with curve ordering and Letsencrypt ECDSA-certificate

### ISSUE THREAD

**Issue by Tributh** [openssl/openssl#2658]
Hi,
in ssl/t1_lib.c I find the following code:
 /* The default curves */
static const unsigned char eccurves_default[] = {
    0, 29,                      /* X25519 (29) */
    0, 23,                      /* secp256r1 (23) */
    0, 25,                      /* secp521r1 (25) */
    0, 24,                      /* secp384r1 (24) */
};

when i run an application with auto/default curve selection and an RSA certificate
everything is fine, but with an 384bit ECDSA certificate(Letsencrypt) a lot of clients are not negotiating an TLS connection.
I see always log lines with 
...(SSL_accept): error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher

When i just change the curve order to

/* The default curves */
static const unsigned char eccurves_default[] = {
    0, 29,                      /* X25519 (29) */
    0, 25,                      /* secp521r1 (25) */
    0, 24,                      /* secp384r1 (24) */
    0, 23,                      /* secp256r1 (23) */
};

everything works fine.
For me it looks like that secp256r1 is the first offered curve for older clients
(with are unable to recognize X25519) and this curve is not matching with an ECDSA-384bit certificate,
so that the clients fail to negotiate. 
When i have changed the order, all these clients are able to connect and use secp384r1 for the connection.
Is there a special reason for the actual curve order?
Could it be an incompatibility with Letsencrypt ECDSA 384bits certificates. or is there a MUST to negotiate the curve with at least the curve of the certificate which is also secp384r1?

Any hints or a bug in curve offering with 384bit certificates?

Regards Torsten Tributh

**Comment by TerraX-net** [comment]
Which OpenSSL version (1.0.x/1.1.x/master) do you use?

If you are using a Letsencrypt P-384 ECDSA certificate, secp384r1 just has to be in the curve list. The position is irrelevant. But I'm currently having problems with nginx and X25519 with TLS1.3 from master (can generate keypair and do speed test, but couldn't use it for ECDHE since a few days).
And secp256r1 has another name: prime256v1. It think OpenSSL works with both fine.
I hope others could help you if you tell us your version number.

**Comment by Tributh** [comment]
I am using 1.1.0e actually, but have realized the problem for the first time already in 1.0.2.
I took some time to understand that another curve ordering helped to fix the connection issue.
So i think the problem exist in 1.1.0 and also in 1.0.2. I see only few installations using the auto curve feature from 1.0.2 or now named "default" in 1.1.0. Most installations have just configured one fixed curve, which suppresses this issue.
With the master version and nginx in dual-cert installation, i see with a cipherscan only the RSA-cert with  prime256v1 curve and no chance to get ECDSA running or more than one curve, but thats another story.

**Comment by mattcaswell** [comment]
Is this still happening with the latest OpenSSL versions? I've run various tests but cannot recreate behaviour like this.

**Comment by TTributh** [comment]
Sorry,
for not updating the ticket.
It happened when TLS-Ciphers(uite) had to be added by hand, before TLS13
ciphers became mandatory in the code.
My openssl 1.1.1 (alpha) client wanted to negotiate TLS13 while the
server code was not prepared to use an TLS13 cipher.
I had always special selected ciphers per Application, but the TLS13
ciphers where added a bit later, when I realized that it was needed.

Just in short now, the problem has disappeared in the actual code.
Cheers Torsten

**Comment by mattcaswell** [comment]
Ok - no problem. Thanks for the update. Closing.
