### ISSUE TITLE
Performance issues due to non-blocking IO

### ISSUE THREAD

**Issue by Byron** [openssl/openssl#267]
The subject is the result of some debugging done while trying to trace down the source of my problems. These shall be explained in detail as I am sure the authors of this project and possibly [hyper](https://github.com/hyperium/hyper/) will know a workaround or fix.

When trying to upload a multi-gigabyte video to youtube, I notice that the transfer doesn't start until the entire input stream was read into memory. The call-trace looks like this:
![screen shot 2015-04-28 at 11 00 52](https://cloud.githubusercontent.com/assets/63622/7367004/b7add324-ed9c-11e4-8c3e-e683065f2456.png)
Note the io::copy call coming from the [hyper client](https://github.com/Byron/hyper/blob/master/src/client/mod.rs#L188), which I believe would block in case of a standard TCP connection.
A process trying to send a 1.1GB video (after loading it into memory) looks like this - note the 1.2GB of real memory:
![screen shot 2015-04-28 at 08 13 49](https://cloud.githubusercontent.com/assets/63622/7366913/dab4b15e-ed9b-11e4-86f4-24eef0699533.png)
A second observation is the high CPU usage. Even if the entire input is cached, I would have expected the send operation to saturate the 100Mb connection to the internet, yet the CPU seems to be bottlenecking, producing a mere ~2.5Mb per second.
![screen shot 2015-04-28 at 08 15 59](https://cloud.githubusercontent.com/assets/63622/7366945/2ee5e6da-ed9c-11e4-802f-f2f72766422b.png)
When looking at the tcp send calls of the process, they will come in at about 4 to 5 calls per second, which seems to confirm that the CPU is not producing enough encrypted bytes.
![screen shot 2015-04-28 at 08 14 00](https://cloud.githubusercontent.com/assets/63622/7366966/67565dec-ed9c-11e4-8536-963210aa216d.png)
Finally, this call-trace shows that the actual TCP send operation commences only when hyper attempts to [end the operation](https://github.com/Byron/hyper/blob/master/src/http.rs#L257).
![screen shot 2015-04-28 at 10 55 29](https://cloud.githubusercontent.com/assets/63622/7367071/3872055c-ed9d-11e4-9fb9-de60482d6e95.png)

The CPU bottleneck seems to be originating within OpenSSL, but that's just a guess of mine.

## How to reproduce
Download the `youtube3` executable from the [Google APIs for Rust release page](https://github.com/Byron/google-apis-rs/releases), then extract and run:
```bash
$ ./youtube3 videos insert -r snippet title=sometitle description=TBD  tags=test category-id=22 ..status public-stats-viewable=true privacy-status=private -u simple SOME_BIG_MOVIE_FILE.mov application/octet-stream"
# Once authenticated, it will attempt an upload to your youtube account. It fails in any way due to another reason (https://github.com/serde-rs/serde/issues/65), so it will mean no harm to try it.
```

## Meta
* Using `openssl 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)`
```
✗ rustc --version
rustc 1.0.0-nightly (f46c4e158 2015-04-20) (built 2015-04-20)
```

CC @seanmonstar @reem

Thanks for your help ! This is a major issue for me and I can help if you give me some hints on how to solve this.

**Comment by x64architecture** [comment]
@Byron You should send this to openssl-dev@openssl.org, as github is not regularly checked by the OpenSSL team.

**Comment by Byron** [comment]
Do you truly believe this is a bug in openssl ? From what I could see, openssl supports [blocking and non-blocking IO](https://www.openssl.org/docs/crypto/BIO_s_connect.html) naturally. There is a function called `BIO_set_nbio(int)` which should be set to zero to get blocking IO.
There are many other clients who use openssl who don't have this particular issue either.
Maybe you see a chance to review the way `openssl-rust` handles things, perhaps the option could be exposed, for example.

Something that caught my attention is the implementation of [`MemBio`](https://github.com/sfackler/rust-openssl/blob/master/openssl/src/bio/mod.rs), which I would read as 'Memory Blocking IO' ... it makes no sense to me that it would have non-blocking semantics by default.

So far I couldn't find any hunk of code who would explicitly enable non-blocking IO, neither in hyper nor here. From what I see, `openssl` uses blocking-IO by default, as people only ask to [get non-blocking IO](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=openssl+blocking+io). Also I could reproduce the issue on OSX 10.10 and Ubuntu 12 LTS, who certainly used different versions of openssl.

I hope this makes sense to you, and maybe you see another way than to send me to openssl-dev.
Thank you

**Comment by Byron** [comment]
ooooooh !
Sorry, this was destined for openssl-rust !
