### ISSUE TITLE
openssl dhparam -C generates incompatible code

### ISSUE THREAD

**Issue by BjarniRunar** [openssl/openssl#2675]
I am on Debian testing, trying to build Pound against libssl1.0.

Debian testing has helpfully installed the latest openssl command-line tool, version 1.1.0d.

Part of the Pound build process invokes `openssl dhparam` to generate a couple of .h files. Unfortunately, the code generated is only compatible with libssl1.1, so the Pound build fails. I can make the build work by generating DH parameters on a machine with an older OpenSSL and copying the files over.

Would it be possible/reasonable for `openssl dhparam` to generate code which uses some clever `#define` magic to remain backwards compatible with older versions of OpenSSL?

**Comment by richsalz** [comment]
No, the generate command is only compatible with the same runtime.  Sorry.

**Comment by BjarniRunar** [comment]
Fair enough. It seemed like an easy fix to just keep old code around in the template, but I might well be underestimating the maintenance burden.

I'll see about filing a bug against the Debian libssl1.0-dev package then, it's not fully usable without the appropriate openssl binary.

Thank you for the prompt reply!
