### ISSUE TITLE
OpenSSL 1.1.0-stable sends empty extension as the last on in Client Hello

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#2691]
When running f4cdd19a6a8a0845c08c, the Client Hello ends with two extensions, both empty: EtM and EMS. This behaviour on OpenSSL part causes extension intolerance in some TLS servers.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1243641 for the same issue in NSS.

**Comment by richsalz** [comment]
Fixed via the PR's listed above.  Thanks!
