### ISSUE TITLE
Custom BIO's

### ISSUE THREAD

**Issue by rrip** [openssl/openssl#2700]
Since the file bio.h no longer includes the structure definition of bio_st, custom BIO's are no longer possible. Our application requires a custom BIO and has compiled under versions prior to 1.1.

**Comment by richsalz** [comment]
Look at ```BIO_meth_new()``` and the ```BIO_meth_set/get``` functions.

**Comment by t-j-h** [comment]
Have you tried to port across to the APIs @richsalz noted? Have you identified specific items that are missing?

**Comment by rrip** [comment]
Okay that works. Nothing was missing, and the code even looks better.
