### ISSUE TITLE
ALPN extension, protocol selection does not follow RFC 7301

### ISSUE THREAD

**Issue by 7echno** [openssl/openssl#2708]
There is a issues within the way OpenSSL respond when client advertises the protocols that server is not supporting. 

As described in [RFC 7301](https://tools.ietf.org/html/rfc7301#section-3.2) ,server shall respond with a fatal "no_application_protocol" alert. 
Seems that server is not responding with alert.

I have test it with openssl-1.0.2

Reproducer:

`openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes`
 `openssl s_server -cert cert.pem -key key.pem -accept 4433 -www -alpn h2`

In another console:

`git clone https://github.com/tomato42/tlsfuzzer.git`
`pushd tlsfuzzer`
`git checkout alpn-test`
`git clone https://github.com/tomato42/tlslite-ng.git .tlslite-ng`
`ln -s .tlslite-ng/tlslite tlslite`
`git clone https://github.com/warner/python-ecdsa.git .python-ecdsa`
`ln -s .python-ecdsa/src/ecdsa ecdsa`
`PYTHONPATH=. python scripts/test-alpn-negotiation.py 'only http/1.1'`

**Comment by kaduk** [comment]
Fixed by 062178678f5374b09f00d70796f6e692e8775aca in OpenSSL_1_1_0 (but would be a breaking behavior change in 1.0.2 so is probably not appropriate to backport).

**Comment by richsalz** [comment]
As the 1.1.0 work points out, many servers don't do this.  I'm willing to keep this bug open, but the commit that @kaduk pointed to is pretty big.  This is unlikely to get fixed in 1.0.2 unless someone submits a PR.

**Comment by tmshort** [comment]
The code right now only handles the ACK and NOACK return codes. Perhaps if the fatal or warning alert return codes were handled, then this could be done relatively simply; at least by the ALPN callback; this would permit following RFC 7301 by those servers that supply an ALPN callback.

**Comment by tomato42** [comment]
So openssl does not send `no_application_protocol` error on ALPN protocol mismatch with current OpenSSL 1.1.0 (bbe75a29dfdb65) and 1.1.1c either

Bisecting the issue, I found a504540fcbc77 as the commit that undid that change in 1.1.0, and it was discussed in #2570.

So my question is: how can openssl send the alert when the callback decides that there is a mismatch between list advertised by client and the list supported by server?

**Comment by t8m** [comment]
The callback has to return SSL_TLSEXT_ERR_ALERT_FATAL instead of SSL_TLSEXT_ERR_NOACK. So this is basically just a s_server bug.
