### ISSUE TITLE
invalid preprocessor expression

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#2710]
I'm getting this (with clang 4.0):
crypto/o_dir.c:27:5: error: token is not a valid binary operator in a preprocessor subexpression
    (defined __VMS_VER && __VMS_VER >= 70000000)
    ^

@levitte: Can you look at that?

I guess it's missing a ||

**Comment by richsalz** [comment]
+1 from me to anyone to fix it.

**Comment by levitte** [comment]
Fixed
