### ISSUE TITLE
Make EVP_DigestVerifyFinal usable with HMAC

### ISSUE THREAD

**Issue by Philipp91** [openssl/openssl#2711]
I don't know if there is a particular technical reason why HMAC signatures currently cannot be verified with `EVP_DigestVerifyFinal`. The wiki clearly explains that this is the case and provides a code sample that illustrates how to verify HMACs instead: https://wiki.openssl.org/index.php/EVP_Signing_and_Verifying

Nevertheless, I think it would be consistent to let users verify their HMAC with the same API, unless there is a strong reason against. As an added bonus, the implementation by OpenSSL itself would ensure that `CRYPTO_memcmp` is actually used.

This issue originally came up in rust-openssl: https://github.com/sfackler/rust-openssl/issues/588

**Comment by mattcaswell** [comment]
Yes, this is definitely needed IMO. I think the same is true for CMAC. Perhaps @snhenson has a view.

**Comment by levitte** [comment]
With the new EVP MAC API, this has become irrelevant, hasn't it?

**Comment by paulidale** [comment]
The wiki page is a bit misleading, showing how to manually create an HMAC signature, rather than using the dedicated functions.  The examples could be rewritten using the EVP_MAC API which, I think, would go a long way here.

We discussed merging the MAC and digest computations previously and the result was that they are different enough in usage to justify separate APIs.

**Comment by levitte** [comment]
We have to remember that the `EVP_MAC  API doesn't exist in any release yet.  The wiki pages must be judged with that in mind...

But back to the matter of this issue.  We now have `EVP_MAC`...  has MACs through the `EVP_DigestSign` fallen enough out of favor for use to dismiss this issue, or do we want to make MACs verifiable with `EVP_DigestVerify` functions for those who want to hold on to that way of doing it?

**Comment by mattcaswell** [comment]
With EVP_MAC I see no reason to do this now. Obviously that doesn't help for already released versions - but we wouldn't backport a feature to those anyway.

**Comment by levitte** [comment]
In that case, this issue has lost its relevance.  Closing it.
