### ISSUE TITLE
Setters missing for X509_STORE_CTX

### ISSUE THREAD

**Issue by kouril** [openssl/openssl#2724]
Except the possibility to set the verification callback, OpenSSL 1.1.0 doesn't provide setter calls for other attributes and functions for X509_STORE_CTX. According to https://github.com/openssl/openssl/pull/1294 the values are supposed to be copied from the X509_STORE at the time when X509_STORE_CTX is being initialized and X509_STORE_CTX should be used only as a cache. Unfortunately, that idea doesn't work always since sometimes it's possible to only work with an X509_STORE_CTX structure established out of our control. An example is the OpenSSL's ssl_verify_cert_chain() call that initializes an X509_STORE_CTX based on one of several possible X509_STOREs.

I'd love to be able to customize the check_issued() call to better support X.509 proxy certificates for grid software. Additional complicating factor is that I'd only need to provide something that can be invoked from a callback since I don't control the SSL structure (the application extends mod_ssl from Apache with some additional checks). For older versions of OpenSSL we have a call set by SSL_CTX_set_cert_verify_callback() that sets the fields in X509_STORE_CTX and invokes the standard verification call. This doesn't seem possible with OpenSSL 1.1.0.

**Comment by levitte** [comment]
There was a discussion revolving around this on openssl-dev [back in july](https://mta.openssl.org/pipermail/openssl-dev/2016-July/007787.html).

I'm curious, though, what the better support involves.  It may very well be that there are bugs in OpenSSL that this better support is covering for, or that there were bugs that have been fixed ever since.

**Comment by levitte** [comment]
I do recall there was a lot of discussions around this in other threads.  I frankly don't recall the conclusion for the moment, but considering there's been no discussion here, I'm going to assume that it isn't interesting to keep.  Closing.
