### ISSUE TITLE
1.0.2 branch fails to build on VC-32

### ISSUE THREAD

**Issue by GyrosGeier** [openssl/openssl#2726]
Hi,

I'm getting a build failure on 1.0.2:

    link /nologo /subsystem:console /opt:ref /debug /dll /out:out32dll\libeay32.dll /def:ms/LIBEAY32.def @C:\Users\Build\AppData\Local\Temp\nm432E.tmp
       Creating library out32dll\libeay32.lib and object out32dll\libeay32.exp
    ec_asn1.obj : error LNK2019: unresolved external symbol _OSSL_NELEM referenced in function _EC_GROUP_get_basis_type
    out32dll\libeay32.dll : fatal error LNK1120: 1 unresolved externals

[Full Build Log](http://ci.kicad-pcb.org/job/windows-openssl-msvc/625/build=release,cpu=x86,label=windows/consoleFull) and [List of Changes](http://ci.kicad-pcb.org/job/windows-openssl-msvc/625/changes).

   Simon

**Comment by levitte** [comment]
See #2713 for the solution.  All that remains is having it merged into the 1.0.2 branch

**Comment by richsalz** [comment]
fix merged, sorry for the inconvenience.
