### ISSUE TITLE
Allow configuring X509_STORE_CTX for which signature algorithms to allow

### ISSUE THREAD

**Issue by alex** [openssl/openssl#2729]
Currently `X509_STORE_CTX` allows any known algorithm to be used when verifying X.509 signatures (in `X509_verify` -> `ASN1_item_verify`).

It'd be great if this could be configured on which algorithms to allow, or perhaps which to disallow. My specific interest is being able to configure software which interacts with WebPKI to not accept MD5 or SHA-1 signatures -- right now when using OpenSSL in this context we're relying on the CABForum + browsers for enforcement.

**Comment by levitte** [comment]
This isn't the forum for user questions.  May I suggest going to openssl-users@openssl.org (see https://www.openssl.org/community/mailinglists.html for links to subscription information)?

**Comment by alex** [comment]
@levitte This wasn't a question, this was a feature request. There's no current API for what I'm requesting.

**Comment by levitte** [comment]
Are you sure that `X509_verify` is what you're actually after?  After all, all that one does is to check that the cert signature matches the key you give it.  `X509_STORE_CTX` isn't involved here.

Are you actually talking about `X509_verify_cert` and wanting it to not validate certificates with specific signature algos (MD5 and SHA1)?  There's a callback you can register, which can be used to override the internal verification process, and that can be used for what you ask.

**Comment by alex** [comment]
Sorry, I guess my issue was unclear. `X509_verify_cert` is the API that ultimately needs to be reflect this, I included `X509_verify` and `ASN1_ITEM_verify` because they're part of the current callchain that actually looks at signatures.

While the callback can be used for this, my view is that this is a sufficiently common validation requirement that it should be supported natively. Obviously if you disagree you can close this issue :-)

**Comment by levitte** [comment]
I won't close this, as others may have a different opinion.

I'm trying to think generally.  I mean, sure, having some array that stores NIDs of unwanted algos could be easy.  Perhaps....  but I'm also thinking that there's no way to predict the future.  What will it be in a month?  In a year?  What other stuff might people want to opt out (or for that matter, in)?
So yes, I'm of the opinion that it's better to leave it to the application authors to make this kind of decision, and to codify it precisely like they want to.

**Comment by Lukasa** [comment]
> So yes, I'm of the opinion that it's better to leave it to the application authors to make this kind of decision, and to codify it precisely like they want to.

So I don't think @alex is proposing that OpenSSL would make this decision on behalf of application authors, but that OpenSSL would expose an API that allows configuration of excluded signature algorithms in a declarative way, rather than requiring that users write custom code that introspects certificates and makes those judgements. That way, you can provide a blacklist of algorithms you don't like (or a whitelist of the ones you do) as an author, and keep that in one place, rather than write a bunch of X509 handling code to work this out.

**Comment by levitte** [comment]
> So I don't think @alex is proposing that OpenSSL would make this decision on behalf of application authors, but that OpenSSL would expose an API that allows configuration of excluded signature algorithms in a declarative way, rather than requiring that users write custom code that introspects certificates and makes those judgements.

That's what I meant with "having some array that stores NIDs of unwated algos"...  that array would be maintained through an application-callable API.

**Comment by richsalz** [comment]
But why stop there?  Why not a list of keysizes?  Why not a list of "too old"?  etc...  This is a slippery slope, and until we have more than one data point I'm reluctant to draw a line around an API.

**Comment by richsalz** [comment]
The application can control what things it wants to put into an X509_STORE and should do so using whatever criteria it wants :)  Closing this.
