### ISSUE TITLE
Openssl verify fails with critical crlDistributionPoint extension

### ISSUE THREAD

**Issue by zviratko** [openssl/openssl#2730]
Already reported in issue #660

This is still an issue on version 1.0.2k
The actual error with openssl verify is:

`error 34 at 0 depth lookup:unhandled critical extension`

-ignore_critical makes it go away, but that's obviously wrong.

I'm not sure if there are other implications (whether e.g. s_client would work with such certificate)

**Comment by richsalz** [comment]
OpenSSL does not handle the crlDistributionPoint extension, therefore it is doing the right thing when it is marked as critical.  Closing this.

**Comment by zviratko** [comment]
I do not believe that is correct. Openssl verify has a -crl_download option (which I have tried and seems to do nothing even when crlDistributionPoint is non critical).
Changelog says:

*) New option -crl_download in several openssl utilities to download CRLs
     from CRLDP extension in certificates.
     [Steve Henson]

**Comment by richsalz** [comment]
Ah, was this in certificates or crl's?

**Comment by zviratko** [comment]
In a certificate
Happens with both a list of several URIs or a single URI

          X509v3 CRL Distribution Points: critical

                Full Name:
                  URI:http://some.thi.ng/ca.crl

or

            X509v3 CRL Distribution Points: critical

                Full Name:
                  URI:http://some1.thi.ng/ca.crl

                Full Name:
                  URI:http://some2.thi.ng/ca.crl

                Full Name:
                  URI:http://some3.thi.ng/ca.crl

**Comment by richsalz** [comment]
fix with the closing of #3087.
