### ISSUE TITLE
dhparams creating wrong key size 

### ISSUE THREAD

**Issue by jrothrock** [openssl/openssl#2731]
I'm currently using Ubuntu 16.04 on DO, and I have tried this with multiple key sizes - 4096, 3072, and 2048. Here's a picture of an attempt with 2048 producing, what I believe is, a 256 bit key.

![screen shot 2017-02-23 at 2 42 09 pm](https://cloud.githubusercontent.com/assets/14958993/23280632/37802578-f9d7-11e6-9843-95bf74856cbc.png)

**Comment by richsalz** [comment]
are you counting the output and thinking it's 256 bits?  that's not accurate.  it's just an indication of trying to find a key.

**Comment by jrothrock** [comment]
Ahh okay. I'm also running this through ssllabs and I'm getting that they are 1024 bits, when generating a 4096 bit key.

**Comment by richsalz** [comment]
Most likely a config error.  Try, for example, to print the DH params
```
openssl dhparam -C -in /etc/ssl/certs/dhparam.pem
```
did you restart your server?

**Comment by jrothrock** [comment]
Ha, yup. I failed to copy correctly on both servers, forgot the ssl_dhparam. Sorry about that. Also, if you don't mind me asking, why is the output longer for bigger keys? Is it just pulling keys from an openssl repository?

**Comment by richsalz** [comment]
it takes longer to prove that a bigger number is prime.
glad you got it working.
