### ISSUE TITLE
1.1.0e mingw/msys2 build error - OPENSSLDIR macro in crypto/include/internal/cryptlib.h

### ISSUE THREAD

**Issue by MSP-Greg** [openssl/openssl#2734]
I've built several package updates using mingw/msys2, including OpenSSL 1.1.0c and 1.1.0e.  When I first build 1.1.0e, I had some issues and manually hacked it thru the process.

Test result was - Failed 1/91 test programs, 1/436 subtests failed. That was a 32 bit version, and I didn't keep very good notes.  I'm currently using 1.1.0e with Ruby, and no issues connecting to GitHub, etc.

Now I've gone back to building again (both 32 bit and 64 bit), and I keep having an error in [crypto/include/internal/cryptlib.h](https://github.com/openssl/openssl/blob/master/crypto/include/internal/cryptlib.h#L47).

See [Git Gist](https://gist.github.com/MSP-Greg/d790d4379aeebdcd97d752aef3b66c51) for full detail.

Any help would be appreciated.  I'm not really a c type, more C#, Ruby & JS...

FWIW, tried with both 1.1.0e and 1.1.0 stable (22Feb), same error.

**Comment by levitte** [comment]
Ok, so here's the weird part:

```
gcc  -I. -Icrypto/include -Iinclude -DZLIB -DZLIB_SHARED -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG \
  -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_PART_WORDS \
  -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM \
  -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM \
  -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_API_COMPAT=0x10000000L -DOPENSSLDIR=/mingw32 \
  -DENGINESDIR=/mingw32/lib/engines-1_1 -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m32 \
  -Wall -O3 -fomit-frame-pointer -D_MT  -D_WINDLL -MMD -MF \
  crypto/ct/ct_log.d.tmp -MT crypto/ct/ct_log.o -c -o crypto/ct/ct_log.o crypto/ct/ct_log.c
```

The definition of OPENSSLDIR (`-DOPENSSLDIR=/mingw32`) is missing a few quotes that would make it an actual C string, which is the intention.  Compare that to the following (a quick build of the same object file that I did a minute ago on my Linux box):

```
: ; make crypto/ct/ct_log.o 
clang  -I. -Icrypto/include -Iinclude -I../master -I../master/crypto/include -I../master/include -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O0 -g -pthread -m64 -DL_ENDIAN -Wextra -Qunused-arguments  -DDEBUG_UNUSED -Wswitch -DPEDANTIC -pedantic -Wno-long-long -Wall -Wsign-compare -Wmissing-prototypes -Wshadow -Wformat -Wtype-limits -Werror -Qunused-arguments -Wextra -Wswitch-default -Wno-unused-parameter -Wno-parentheses-equality -Wno-missing-field-initializers -Wno-language-extension-token -Wno-extended-offsetof -Wconditional-uninitialized -Wincompatible-pointer-types-discards-qualifiers -Wmissing-variable-declarations -fPIC -DOPENSSL_USE_NODELETE -MMD -MF crypto/ct/ct_log.d.tmp -MT crypto/ct/ct_log.o -c -o crypto/ct/ct_log.o ../master/crypto/ct/ct_log.c
```

See all that quoting around the OPENSSLDIR value?  That's what it supposed to look like.  Is something in the installer massaging the Makefile after `Configure` created it?

**Comment by MSP-Greg** [comment]
@levitte My mistake.

I've been bouncing between two build systems, one runs in a Windows command window, the other (mingw/msys2) in a bash window.  I had issues with backslash/forwardslash separators/demiters on the Windows system, and that was something I previously hacked, and, my notes weren't the best.  Removed my sed line that was modifying the Makefile, and it's fine, although I haven't gotten to install yet...

I'm trying to move all my building to msys2/mingw, so I can push package updates to [Alexpux/MINGW-packages](https://github.com/Alexpux/MINGW-packages).

Thanks for your help.

**Comment by levitte** [comment]
Glad I could point you in the right direction.

**Comment by MSP-Greg** [comment]
@levitte 

Thanks again.  Built with 22Feb 1.1.0f stable, all tests passed, both 32 & 64.  Config'd with `--api=1.0.0` & `enable-capieng`.

**Comment by levitte** [comment]
Cool! Thanks for the feedback
