### ISSUE TITLE
Bug - SSL Library Error - BUF_MEM_grow:malloc failure

### ISSUE THREAD

**Issue by nomalatha** [openssl/openssl#2763]
Hi,

Our product (32-bit process) uses OpenSSL third-party libraries for EAP protocols. During the debugging of a customer issue in PEAP protocol, we got to understand that SSL_Accept has returned failure.

STATE_HANDSHAKE SSL_ERROR_SSL error retrun code [1] and peak error translate code [39] and err_get_reason [1048] // Error code, Error cases(Reason)
8900:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:.\ssl\s3_pkt.c:1235:SSL alert number 48 // Error Queue
SSL_ERROR_SSL Handshake failure

On further analyzing, we found that handshake failure is due to the "BUF_MEM_grow : malloc failure" in the server after the 'n' number of authentications.
The memory buffer gets completely allocated and handshake is failed when we tried to allocate the memory.

STATE_HANDSHAKE SSL_ERROR_SSL error retrun code [1] and peak error translate code [2] and err_get_reason [65]
7820:error:07064041:memory buffer routines:BUF_MEM_grow:malloc failure:.\crypto\buffer\buffer.c:122:
SSL_ERROR_SSL Handshake failure

Total memory that is installed on the server: 4GB
Process memory size when the issue occurs: 360 ~ 370 MB

Operating System Version - Windows Server 2008
OpenSSL version - 0.9.7e, 1.0.0s, 1.0.2h

Please let us know if there are known issues related to the same or let us know if you require further information for your debugging.

Regards,
Nomalatha A

Note: This issue was highlighted earlier in RT as https://rt.openssl.org/Ticket/Display.html?id=4657

**Comment by FdaSilvaYY** [comment]
https://www.openssl.org/policies/releasestrat.html

**Comment by nomalatha** [comment]
Thank you for sharing the Release Strategy. I understand that 0.9.7e and 1.0.0s is no longer supported.
The issue that I have reported above is also observed in OpenSSL version 1.0.2.h

Since our customer has reported the issue again recently, in order to raise GIT ticket, I have just copied and pasted the old RT ticket contents. Now I have updated to reflect OpenSSL 1.0.2h version as well in the original description.

**Comment by richsalz** [comment]
How do you know the memory is allocated?  How do you know that you don't have a pointer-reuse problem? How do you know that you don't have a "we didn't free this resource" problem?

There is not sufficient information for us to *help you* debug this.

**Comment by nomalatha** [comment]
Thank you for your response and we would definitely provide the requested information in a few days.
Actually this particular issue cannot be simulated in our Engineering Lab and only occurs in our customer site. Therefore we need to add more instrumentation to our build and then collect the logs from the customer site and get back to you with our log analysis by answering your questions.

**Comment by richsalz** [comment]
You should spend some time trying to see what your application is doing as well.  There is no promise that, if you send a backtrace, anyone here can or will debug the situation.   The best way forward is to make a small reproducible test case.  Yes this is very difficult.  So is long-distance debugging for free.

**Comment by snhenson** [comment]
One thing you can do is to check to see what parameters were passed to BUF_MEM_grow when it fails to see if it gets passed an abnormal parameter or if it is sane and your system is just running out of memory.

**Comment by nomalatha** [comment]
As you have suggested, we will try to create a small reproducible test case and narrow down the problem which will help us get to the root cause. During the process of debugging, if we have any queries in OpenSSL we would like to get it clarified by this ticket. Since the issue faced by our end customer is of high priority, we are working on it actively and I would request you to keep this ticket open for a few days till we get to the root cause.

**Comment by richsalz** [comment]
it's been three weeks with no update.  closing ticket.
