### ISSUE TITLE
ALPN extension behaviour with renegotiation 

### ISSUE THREAD

**Issue by 7echno** [openssl/openssl#2767]
Seems that ALPN extension behaviour with secure renegotiation is not explicitly explained, or explained enough in RFC 7301 in the way that can be clearly understood. 
So testing this two extensions together I got results which seems more like not desired ones.

I have test it with openssl-1.0.2

Three different scenarios I have tested with renegotiation:
1. First handshake/session with ALPN
    Second handshake with same ALPN protocol
2. First handshake/session with ALPN
    Second handshake with changed ALPN protocol
3. First handshake/session without ALPN
    Second handshake with ALPN

All three of them resulted with second handshake ServerHello without ALPN extension.
First handshake ServerHello was as expected.

From RFC 7301 - 3.2.  Protocol Selection
"The protocol identified in the "application_layer_protocol_negotiation" extension type in the ServerHello SHALL be definitive for the connection, until renegotiated."

Does this means that the ALPN protocol specified in new handshake shall be used after renegotiation? 
Also server should reply with ServerHello and selected ALPN protocol if ALPN is supported and if protocol can be selected from what client advertised. After renegotiation seems that this is not the case.

Reproducer: 
`openssl req -x509 -newkey rsa:2048 -keyout localhost.key -out localhost.crt -nodes -batch -subj /CN=localhost`
`openssl s_server -cert localhost.crt -key localhost.key -accept 4433 -www -alpn h2,'http/1.1'`

In another terminal:
`git clone https://github.com/7echno/tlsfuzzer.git`
`pushd tlsfuzzer`
`git checkout alpn-test`
`git clone https://github.com/tomato42/tlslite-ng.git .tlslite-ng`
`ln -s .tlslite-ng/tlslite tlslite`
`git clone https://github.com/warner/python-ecdsa.git .python-ecdsa`
`ln -s .python-ecdsa/src/ecdsa ecdsa`

Run tests:
`PYTHONPATH=. python scripts/test-alpn-negotiation.py 'renegotiation with protocol change'`
`PYTHONPATH=. python scripts/test-alpn-negotiation.py 'renegotiation without protocol change'`
`PYTHONPATH=. python scripts/test-alpn-negotiation.py 'renegotiation 2nd handshake alpn'`

**Comment by richsalz** [comment]
The *intent* is that renegotiation cannot change the ALPN.

**Comment by richsalz** [comment]
ping @kaduk, @mattcaswell : close this?

**Comment by mattcaswell** [comment]
I think close. It is unclear that there is a bug here (well perhaps a bug in the spec for not being more clear about it). Nor is it clear that we should be making a change.

**Comment by tomato42** [comment]
@richsalz @mattcaswell 
no, the intent is that it _can_ be changed/added/removed as part of renegotiation. That "until renegotiated" was added as a result of discussion about handling ALPN with renegotiation:
https://mailarchive.ietf.org/arch/msg/tls/cg48FtE3--9TYaueqC8dTGV3zN0

**Comment by richsalz** [comment]
I see your Andrei post and raise you an Adam: https://mailarchive.ietf.org/arch/msg/tls/Kfbmn0rYZKC1euBNIW_8Z6_Ia0A :)

**Comment by tomato42** [comment]
Adam isn't completely opposed to that idea either, so I'm not sure what you're trying to say... 

even if we follow his requirements for renegotiation, in the above quoted test scripts no application data is exchanged before the second handshake...

**Comment by davidben** [comment]
Having no application data exchanged is certainly necessary for sanity here, but I do not think it is sufficient. Applications typically do not query the protocol lazily once bytes come in. They need to dispatch to some protocol-specific handler early in the connection's lifetime. Indeed as HTTP/2 has both client and server simultaneously speak first, this dispatch *cannot* be deferred like that.

That means the application needs to assume there is some particular point in time when ALPN is resolved, for it to do the dispatch. The natural point is after the first handshake as it has no particular reason to believe there will be a second handshake. (Second handshakes are also a bad idea given renegotiation's various security flaws.)

Introducing the ability for ALPN to change is thus not only backwards-incompatible but will break reasonable assumptions made by applications, which means introducing (possibly security-impacting) bugs. It is also unclear what changing the application protocol mid-connection would even mean. Only handling ALPN on the initial handshake is the clear answer when considering simplicity, security, and ease of use.

**Comment by tomato42** [comment]
hmm, true, existing behaviour does make the writing applications easier and renegotiation isn't available to TLS 1.3 so it makes it more consistent wrt. protocol...

ok, then I have a technical question: if we have situations as described above (i.e. an attempt to change, remove, or add ALPN through renegotiation), are the ALPN protocols advertised by client in second ClientHello exposed to application using OpenSSL? or does the API allow only inspection of the first ClientHello only? and will return the protocol negotiated in the first handshake only, no matter how many renegotiations take place?

neither s_server nor s_client report the ALPN status after renegotiation (it's excluded from output of `GET / ...` with `-www` option on s_server)

**Comment by kaduk** [comment]
```
int tls_parse_ctos_alpn(SSL *s, PACKET *pkt, unsigned int context, X509 *x,
                        size_t chainidx)
{
    PACKET protocol_list, save_protocol_list, protocol;

    if (!SSL_IS_FIRST_HANDSHAKE(s))
        return 1;
```

**Comment by tomato42** [comment]
so it's not even parsed, interesting...

@kaduk thanks!
