### ISSUE TITLE
compile OpenSSL 1.0.2a + FIPS 2.0.9 + ZLIB 1.2.8 fails in Windows 32bit

### ISSUE THREAD

**Issue by Gopalaraju** [openssl/openssl#278]
In VS 9.0 Command prompt executed following commands:

cd c:\openssl-fips-2.0.9
ms\do_fips.bat   [SUCCESSFULL]

cd c:\http(2.2.29)\srclib\zlib

nmake -f win32\Makefile.msc

nmake -f win32\Makefile.msc test

cd c:\http\srclib\openssl

perl Configure enable-zlib VC-WIN32 --with-zlib-include=../zlib --with-zlib-lib=../zlib/zlib.lib fips --with-fipsdir=c:\openssl-fips-2.0.9

ms\no_asm.bat

nmake -f ms\ntdll.mak

    cl /Fotmp32dll\gost_sign.obj  -Iinc32 -Itmp32dll /MD /Ox /O2 /Ob2 

-DZLIB
 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32
 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PA
RT_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -Ic:\op
enssl-fips-2.0.9/include -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160
_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_USE_APPLINK -I.
 -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_FIPS -DOPENSSL_NO
_JPAKE -DZLIB -DOPENSSL_NO_DYNAMIC_ENGINE  -I../zlib /Zi /Fdtmp32dll/lib -D_WIND
LL  -DOPENSSL_BUILD_SHLIBCRYPTO -c .\engines\ccgost\gost_sign.c
gost_sign.c
        rc /fo"tmp32dll\libeay32.res" /d CRYPTO ms\version32.rc
        link /nologo /subsystem:console /opt:ref /debug /out:out32dll\fips_prema
in_dso.exe @C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\1\nmB1.tmp

   Creating library out32dll\fips_premain_dso.lib and object out32dll\fips_prema
in_dso.exp
c_zlib.obj : error LNK2019: unresolved external symbol _deflateInit_ referenced
in function _zlib_stateful_init
c_zlib.obj : error LNK2019: unresolved external symbol _inflateInit_ referenced
in function _zlib_stateful_init
c_zlib.obj : error LNK2019: unresolved external symbol _deflateEnd referenced in
 function _zlib_stateful_finish
c_zlib.obj : error LNK2019: unresolved external symbol _inflateEnd referenced in
 function _zlib_stateful_finish
c_zlib.obj : error LNK2019: unresolved external symbol _deflate referenced in fu
nction _zlib_stateful_compress_block
c_zlib.obj : error LNK2019: unresolved external symbol _inflate referenced in fu
nction _zlib_stateful_expand_block
c_zlib.obj : error LNK2019: unresolved external symbol _zError referenced in fun
ction _bio_zlib_read
out32dll\fips_premain_dso.exe : fatal error LNK1120: 7 unresolved externals
NMAKE : fatal error U1077: 'link' : return code '0x460'
Stop.

Can someone help me one of this issues? Basically, I need to build apache-2.2.29 with OpenSSL 1.0.2a + FIPS 2.0.9 + ZLIB 1.2.8

**Comment by Gopalaraju** [comment]
We got stuck for a while now. Can someone help me on this ASAP?

**Comment by sandprddy** [comment]
Did you find any solution?

**Comment by mattcaswell** [comment]
Please raise this issue on the openssl-users email list. Details here: https://mta.openssl.org
