### ISSUE TITLE
[test/cipher_overhead_test] Error 2

### ISSUE THREAD

**Issue by scanor** [openssl/openssl#2804]
![image](https://cloud.githubusercontent.com/assets/12003972/23444188/6af0dcae-fe6e-11e6-8b87-cf7784137762.png)
when I run "./Configure linux-x86_64 no-shared -fPIC; make " , I get this error? But I ensure that the there function in the picture exits in the right place! Can anybody help me out of this issues?
More Info:
 {
host : centos6  64bit
perl : perl5.10
}

**Comment by richsalz** [comment]
what version of openssl?  that test builds all the time ... any previous error?

**Comment by scanor** [comment]
the most refresh version of openssl i think , because i just clone it from this repo

**Comment by richsalz** [comment]
ssl3_num_ciphers is in ssl/s3_lib.c  did that library build correctly?

**Comment by scanor** [comment]
![image](https://cloud.githubusercontent.com/assets/12003972/23444531/b00e1d40-fe70-11e6-87a7-a46be8360e29.png)
yeph,it is in.

**Comment by richsalz** [comment]
that doesn't show the library being built.  libssl.so,.a,etc in the toplevel directory

**Comment by scanor** [comment]
![image](https://cloud.githubusercontent.com/assets/12003972/23444617/41debb80-fe71-11e6-9ef7-30220c9310ff.png)

**Comment by richsalz** [comment]
I am out of ideas, sorry.  Maybe someone else has a clue.

**Comment by scanor** [comment]
thanks any way ,Sincerely

**Comment by scanor** [comment]
interesting， i run “make clean” and run "./Configure linux-x86_64 no-shared -fPIC; make | tee log.txt" which i try to record the long build log.  and the error just gone~~~@richsalz

**Comment by mattcaswell** [comment]
So it seems your problem is resolved. Closing this.
