### ISSUE TITLE
Fail make install ubuntu vivid

### ISSUE THREAD

**Issue by ralph3991** [openssl/openssl#282]
## Installation fails arbitrarily during sudo make install

SSL_want_write.3 => SSL_want.3
SSL_want_x509_lookup.3 => SSL_want.3
installing man3/SSL_write.3
installing man3/d2i_SSL_SESSION.3
i2d_SSL_SESSION.3 => d2i_SSL_SESSION.3
installing man3/ssl.3
SSL.3 => ssl.3
making install in engines...
make[1]: Entering directory '/home/rafael/Work/Sites/openssl/engines'
making install in engines/ccgost...
make[2]: Entering directory '/home/rafael/Work/Sites/openssl/engines/ccgost'
[ -n "/usr/local/ssl" ] # should be set by top Makefile...
if [ -n "" ]; then \
	set -e; \
	echo installing gost; \
	pfx=lib; \
	if expr "linux-x86_64" : "Cygwin" >/dev/null; then \
		sfx=".so"; \
		cp cyggost.dll /usr/local/ssl/lib/engines/${pfx}gost$sfx.new; \
	else \
		case "-I../../include -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -Wall -O3 -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" in \
		*DSO_DLFCN*) sfx=`expr ".so.1.1" : '.*\(\.[a-z][a-z]*\)' \| ".so"`;; \
		*DSO_DL*) sfx=".sl";; \
		*DSO_WIN32*) sfx="eay32.dll"; pfx=;; \
		*) sfx=".bad";; \
		esac; \
		cp ${pfx}gost$sfx /usr/local/ssl/lib/engines/${pfx}gost$sfx.new; \
	fi; \
	chmod 555 /usr/local/ssl/lib/engines/${pfx}gost$sfx.new; \
	mv -f /usr/local/ssl/lib/engines/${pfx}gost$sfx.new /usr/local/ssl/lib/engines/${pfx}gost$sfx; \
fi
make[2]: Leaving directory '/home/rafael/Work/Sites/openssl/engines/ccgost'
make[1]: Leaving directory '/home/rafael/Work/Sites/openssl/engines'
making install in apps...
make[1]: Entering directory '/home/rafael/Work/Sites/openssl/apps'
installing openssl
installing CA.pl
installing tsget
make[1]: Leaving directory '/home/rafael/Work/Sites/openssl/apps'
making install in tools...
make[1]: Entering directory '/home/rafael/Work/Sites/openssl/tools'
make[1]: Leaving directory '/home/rafael/Work/Sites/openssl/tools'
installing libcrypto.a
installing libssl.a
cp libcrypto.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/libcrypto.pc
cp libssl.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/libssl.pc
cp openssl.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/openssl.pc

**Comment by richsalz** [comment]
what failed?  I see no error message.

**Comment by ralph3991** [comment]
What do I do here to finish the install? It stops here

**Comment by mattcaswell** [comment]
It has finished installing into /usr/local/ssl.

**Comment by ralph3991** [comment]
oh ok, thank you I was just confused since running openssl --version gave old version.  But I did find it like you said in `/usr/local/ssl/bin` I should uninstall openssl and then put this one in my PATH variable?

**Comment by mattcaswell** [comment]
No. Don't uninstall the system openssl. Just keep it. There may be conflicts if you attempt to replace the system version with your own version. The ubuntu version may have distro specific patches applied. It's perfectly possible to have both installed at the same time. Just ensure you set up your environment variables appropriately for whichever version you want to use.
