### ISSUE TITLE
Backport a CRLF fix for Windows into 1.0.1/1.0.2

### ISSUE THREAD

**Issue by nurse** [openssl/openssl#283]
Could you backport 7bb98eee3c9e4694dfc2217001d5075ce8d2906e into 1.0.1/1.0.2?

**Comment by richsalz** [comment]
can you see if "chomp" (not chop) works on your platforms?

**Comment by nurse** [comment]
Don't work; Perl's chomp remove only LF even if it runs on Windows.
openssl master seems to be changed because of the reason.

**Comment by richsalz** [comment]
thanks.  we'll just backport the commit to those releases.

**Comment by nurse** [comment]
thanks!

**Comment by levitte** [comment]
Quite frankly, the need for this patch has me worried.  Why is it needed, specifically there?  Considering we use chop in a number of other perl scripts, we should see failure all over the place, so why only this spot, specifically?

Perl under Windows is supposed to convert \r\n in text files to \n on the fly, the perl script isn't supposed to see anything other than \n.  Just like the C library usually does.  So why it doesn't do so, in that specific spot?  Has me wonder what's actually going on.

**Comment by nurse** [comment]
@levitte it is because Perl on MSYS runs Unix mode even if it sometimes handles CRLF files

**Comment by nurse** [comment]
@levitte For example, perl.exe of Git for Windows or RubyInstaller devkit are msys version. It doesn't convert CRLF
