### ISSUE TITLE
build error using no-psk

### ISSUE THREAD

**Issue by tedescn** [openssl/openssl#2847]
When compiling the dev code on OSX "s_server" is throwing errors regards "early_data". I'm guessing this is part of recent cleaup of "s_server.c"?

See debug below:

cc  -I. -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/openssl-1.1.1-dev/ssl\"" -DENGINESDIR="\"/usr/local/openssl-1.1.1-dev/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall   -MMD -MF apps/s_server.d.tmp -MT apps/s_server.o -c -o apps/s_server.o apps/s_server.c
apps/s_server.c:1518:13: error: use of undeclared identifier 'early_data'
            early_data = 1;
            ^
apps/s_server.c:2213:9: error: use of undeclared identifier 'early_data'
    if (early_data) {
        ^
2 errors generated.
make[1]: *** [apps/s_server.o] Error 1
make: *** [all] Error 2

Regards
Nigel

**Comment by kroeckx** [comment]
The early data is something that got added recently.

How did you configure it? Did you build without PSK support?

**Comment by tedescn** [comment]
Kroeckx you are correct - thank you, I had previously included -no-psk. I have removed this directive, recompiled and retested. All is well. 

new config is: ./config --prefix=/usr/local/openssl-$OPENSSL_VERSION --openssldir=/usr/local/openssl-$OPENSSL_VERSION/ssl shared enable-tls1_3  

Regards
Nigel
