### ISSUE TITLE
SHA Extention routine is not called on AMD Ryzen cores

### ISSUE THREAD

**Issue by kanshuzhi** [openssl/openssl#2848]
Hi, 

- AMD has released their Ryzen CPU with SHA extention. But when I run OpenSSL in Ryzens, it still calls sha for SSSE3 routine and shows no improvement.
-  I guess that CPUID routine doesn't work for AMD series CPU. 
- I can see such issue in master branch and 1.1 stable branch.
- If I forcely jump to routine for sha extention, I can see the obvious performance improvement.
- I build the following code for SHA extention detection and it actually return true.
```
int CheckForIntelShaExtensions() {
   int a, b, c, d;

   // Look for CPUID.7.0.EBX[29]
   // EAX = 7, ECX = 0
   a = 7;
   c = 0;

   asm volatile ("cpuid"
        :"=a"(a), "=b"(b), "=c"(c), "=d"(d)
        :"a"(a), "c"(c)
       );

   // Intel® SHA Extensions feature bit is EBX[29]
   return ((b >> 29) & 1);
}
```
Any suggestion for this issue?
Thanks

**Comment by dot-asm** [comment]
#2849 should do the trick, please confirm.

**Comment by kanshuzhi** [comment]
Thank @dot-asm I have tested it. It works well.

**Comment by dot-asm** [comment]
Would it possible to see some numbers?

**Comment by desrce** [comment]
Hi,

Can you provide some details about the test that has been made around this commit ?

Does this commit has been tested with various CPU types ? (e.g. AMD & Intel with/without sha extension) 
Does this commit has been tested against other open source solution that requires openssl ?

I have backported the fix in Ubuntu and got 3 autopkgtest regression
http://people.canonical.com/~ubuntu-archive/proposed-migration/update_excuses.html

**Comment by dot-asm** [comment]
I don't have access to Ryzen system, so I didn't test it explicitly on Ryzen. Reported did confirm it tough. Myself I tested on Intel processors, yes, with/without.

> I have backported the fix in Ubuntu and got 3 autopkgtest regression

Can you point out them? Looking for word "regression" doesn't work as there is a lot of them. Tell even where to look for relevant error messages. I mean the logs are long and end with "fail", but it's not clear where the failure was...

**Comment by desrce** [comment]
Thanks dot-asm, disregard the regression stuffs. 
The autopkgtest cluster was under heavy load and some test simply timeout.

I have tested the patch on Ryzen cpu[1] (with SHA extension capability) and old AMD without the capability and it works perfectly. 

With the patched openssl in Ubuntu using a Ryzen CPU, I do see a significant performance improve (~75% increase).

The test I have made are
- Generate a checksum of a big file (e.g. 5GB)
- Use "openssl speed" command

[1] - Ryzen CPU I used
vendor_id	: AuthenticAMD
model name	: AMD Ryzen 5 1600 Six-Core Processor
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 mwaitx hw_pstate vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt **sha_ni** xsaveopt xsavec xgetbv1 xsaves clzero irperf arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic overflow_recov succor smca

**Comment by dot-asm** [comment]
> disregard the regression stuffs.

I.e. everything is cool.

> I do see a significant performance improve (~75% increase).

You should try speed sha256, you should see several *times* improvement...

**Comment by bubble932** [comment]
> Hi,
> 
> * AMD has released their Ryzen CPU with SHA extention. But when I run OpenSSL in Ryzens, it still calls sha for SSSE3 routine and shows no improvement.
> * I guess that CPUID routine doesn't work for AMD series CPU.
> * I can see such issue in master branch and 1.1 stable branch.
> * If I forcely jump to routine for sha extention, I can see the obvious performance improvement.
> * I build the following code for SHA extention detection and it actually return true.
> 
> ```
> int CheckForIntelShaExtensions() {
>    int a, b, c, d;
> 
>    // Look for CPUID.7.0.EBX[29]
>    // EAX = 7, ECX = 0
>    a = 7;
>    c = 0;
> 
>    asm volatile ("cpuid"
>         :"=a"(a), "=b"(b), "=c"(c), "=d"(d)
>         :"a"(a), "c"(c)
>        );
> 
>    // Intel® SHA Extensions feature bit is EBX[29]
>    return ((b >> 29) & 1);
> }
> ```
> Any suggestion for this issue?
> Thanks

@DLPAT  Would you tell me how to use openssl Intel SHA extension codes to compute the SHA1 or SHA256 in AMD Ryzen CPUs instead of other implementations？Thanks！

**Comment by keval149** [comment]
Is there support for AVX2 in openssl 1.1.1 for SHA
