### ISSUE TITLE
X509_check_{host,email,ip,ip_asc} fails to check Name Constraints

### ISSUE THREAD

**Issue by grooverdan** [openssl/openssl#2853]
Name constraints aren't checked in these function calls.

**Comment by richsalz** [comment]
The nameConstraints are on the signing CA, not the cert, right?  Or am I confused?

**Comment by grooverdan** [comment]
Yes they are on the CA. https://tools.ietf.org/html/rfc5280#section-4.2.1.10

I'm assuming X509 is a chain/array when this function is called. Apologies for any wrong assumptions.

**Comment by grooverdan** [comment]
Sorry I looked a bit more and the correct way to do chain validation is X509_verify_cert after constructing X509_VERIFY_PARAM_set1_{host,ip,email,ip_asc} and binding (SSL_CTX_set1_param) that to the context?

**Comment by richsalz** [comment]
No, it's to see if the end entity cert has extensions that match the ```peername``` being passed in.  No problem.

**Comment by richsalz** [comment]
Please take this to the openssl-users mailing list; see https://mta.openssl.org for details.
