### ISSUE TITLE
CA file rotation is not atomic

### ISSUE THREAD

**Issue by moloughlin** [openssl/openssl#2867]
If multiple `openssl ca` commands in parallel, there is a race condition when two processes create a new serial/index file (e.g. serial.new and index.txt.new) and then rename them. If one process performs it's rename between file creation and file rename on another process, this other process will fail with:
```
Write out database with 1 new entries
unable to rename etc/ca/serial.new to etc/ca/serial
reason: No such file or directory
```
Shouldn't each openssl process establish some lock before creating it's own serial.new then unlock after the rename?

**Comment by kaduk** [comment]
WARNINGS
       The ca command is quirky and at times downright unfriendly.

       The ca utility was originally meant as an example of how to do things in a CA.
       It was not supposed to be used as a full blown CA itself: nevertheless some
       people are using it for this purpose.

       The ca command is effectively a single user command: no locking is done on the
       various files and attempts to run more than one ca command on the same
       database can have unpredictable results.

**Comment by richsalz** [comment]
Closing.
