### ISSUE TITLE
OpenSSL(1.1.0d) with Libcurl(7.52.1) gives error "Unknown SSL protocol error in connection to <server_url>:443

### ISSUE THREAD

**Issue by gnanagurun** [openssl/openssl#2869]
Sometime libcurl (using openssl) reports this error while connecting the tomcat server. Both client and server using the SSL protocol versions TLSv1,TLSv1.1,TLSv1.2 and also using the ciphers which are supported by both of them. Please note that i'm not seeing this error always but sometime. In my application client won't verify the server's certificate (i.e both CURLOPT_SSL_VERIFYHOST and CURLOPT_SSL_VERIFYPEER are disabled). 

If there is any error code (source code) is available which can be used in OpenSSL for debugging, please let me know. I will include that and see what makes this error

**Comment by richsalz** [comment]
To start, you need to find out where that error is coming from. Hint: it's not OpenSSL.  Then you can track down details of the actual error within openssl (if it is).  Then post to the openssl-users mailing list.  Closing this.
