### ISSUE TITLE
openssl verify -crl_check_all -crl_download tries to download CRL to check self-signed certificate

### ISSUE THREAD

**Issue by Xiami2012** [openssl/openssl#2873]
Root CA certificate do not need revocation check since this do not add any security.

```
Root CA
|--Intermediate CA #1
   |--Intermediate CA #2
      |--End entity
```

All certificates have cRLDP set except Root CA's.

1. Make 3 crls together to a big file(``cat root.crl inter1.crl inter2.crl > all.crl``) and call ``openssl verify`` with ``-crl_check_all -CRLfile all.crl`` **succeed**
2. Call ``openssl verify`` with ``-crl_check_all -crl_download`` **failed** with error 3(X509_V_ERR_UNABLE_TO_GET_CRL: unable to get certificate CRL) due to Root CA's certificate do not have cRLDP set.

I'm using openssl-1.0.2k

Maybe we should let CRL check ignore root CA's (self-signed) certificate?

**Comment by richsalz** [comment]
You are telling to to check all.  Don't do that :)  A trust anchor can be revoked, saying "it does not add any security" is wrong.

**Comment by Xiami2012** [comment]
Of course a trust anchor can be revoked. That's by mechanism. Making it's own serial in CRL profile is easy. But it indeed **does not provide any security**. You have no trusted mechanism to verify this, in pure technology. (None of your friends acknowledge you)

A trust anchor is trusted where trust is **assumed** and **not derived**. We trust it **unconditional**.

When a trust anchor becomes untrustworthy, the reason may be:
1. Private key compromised
    In such case, legal key owner would revoke itself and sign a new CRL. But illegal key owner can also sign a valid CRL without itself in. How can you tell them? HTTP do not protect data from tampering.
    If you know that root ca certificate is no longer valid before, why not just remove it from your trust anchors list???
2. Your trust anchor is doing evil
    Anyway but remove it from your trust anchors list work???
3. Superseded by a new trust anchor
    It seems work! But revoking a self-signed certificate brings you a paradox situation.
    1. Get trust anchor
    2. Check if it's in our trust anchors list
    3. Yes it's in. Do CRLs check
    4. Oh it's revoked!
    5. Since the trust anchor is invalid, the CRL signed by it is invalid, too.
    6. Is it revoked?
    7. Go to step 2

# OK. PUT ALL THE ABOVE **ASIDE**. JUST TALK ABOUT ``openssl verify`` ITSELF

All world-widely trusted root CA certificates do not have cRLDP extension or something like that.
Tring to download a CRL will always fail.
However, ``Intermediate CA #1``'s CRL is fetchable and signed by ``Root CA``.
That CRL can be used to do revocation check both for ``Root CA`` and ``Intermediate CA #1``.
Why not **reuse** it?
``-CRLfile`` does, ``-crl_download`` doesn't.

That's a bug. I have downloaded what I want, but i don't use it and raise an error.

**Comment by levitte** [comment]
Did you tell `openssl verify` that the root CA is a trust anchor? No openssl command assumes that a self-signed cert is a trusted cert, *and that's correct behavior*. Please have a closer look at options lika `-CApath` and `-trusted`.
