### ISSUE TITLE
RSASSA-PSS certificates are not supported in TLS

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#2878]
When openssl client receives a RSASSA-PSS certificate from the server, it aborts with:
```
CONNECTED(00000003)
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140553937921792:error:1416F0F7:SSL routines:tls_process_server_certificate:unknown certificate type:ssl/statem/statem_clnt.c:1715:
---
Certificate chain
 0 s:/CN=localhost
   i:/CN=localhost
---
no peer certificate available
```

If the server is started with a RSASSA-PSS certificate it aborts with:
```
Using default temp DH parameters
error setting certificate
139907243718400:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:691:Expecting: DH PARAMETERS
139907243718400:error:140BF0F7:SSL routines:ssl_set_cert:unknown certificate type:ssl/ssl_rsa.c:324:
```

The certificate was created using:
```
openssl req -x509 -newkey rsa-pss -keyout localhost.key -out localhost.crt \
-subj /CN=localhost -nodes -batch -config /etc/pki/tls/openssl.cnf \
-pkeyopt rsa_keygen_bits:2048 -sha256
```

that's using master (777f1708a88f85569)

**Comment by Lekensteyn** [comment]
Regarding the server error (presumably `s_server`), I think you are missing the dhparam file:

    openssl dhparam -out dhparam 2048

... but for some reason passing `-dhparam dhparam` to `s_server` resulted in a weird `Error with command: "-dhparam dhparam"` message (tested with master at a8c5ed812d). So passing `-no_dhe` will workaround that.

Having that said, the `unknown certificate type` still persists. RSASSA-PSS appears not to be supported as signature for certificates.

Were you looking at implementing RSASSA-PSS for TLS 1.3? There are two places were signatures can occur:
- signing/verification of the handshake in the CertificateVerify message (or ServerKeyExchange in TLS 1.2).
- verification of x509v3 certs (which must be allowed when pss is advertised according to https://tools.ietf.org/html/draft-ietf-tls-tls13-21#section-4.4.2.2)

No idea to what extent the latter is implemented, but the TLS 1.3 draft requires the salt length to be 20 while the test certificate generated by openssl shows a different value (222).
___
Here are two test certs loaded in an ASN.1 decoder, one using [RSA (PKCS#1)][1], the other using [RSA-PSS][2].

RSA Algorithm Identifier (for the PKCS#1 variant) is decoded as:
```
SEQUENCE(2 elem)
  OBJECT IDENTIFIER 1.2.840.113549.1.1.11 sha256WithRSAEncryption (PKCS #1)
  NULL
```
which matches with https://tools.ietf.org/html/rfc8017#page-71:
```
   PKCS1-v1-5DigestAlgorithms    ALGORITHM-IDENTIFIER ::= {
       ...
       { OID id-sha256     PARAMETERS NULL }|
```

The same field for the RSA-PSS cert is decoded as:
```
SEQUENCE(2 elem)
  OBJECT IDENTIFIER 1.2.840.113549.1.1.10 rsaPSS (PKCS #1)
  SEQUENCE (3 elem)
  [0] (1 elem)
    SEQUENCE (1 elem)
      OBJECT IDENTIFIER 2.16.840.1.101.3.4.2.1 sha-256 (NIST Algorithm)
  [1] (1 elem)
    SEQUENCE (2 elem)
      OBJECT IDENTIFIER 1.2.840.113549.1.1.8 pkcs1-MGF (PKCS #1)
    SEQUENCE (1 elem)
      OBJECT IDENTIFIER 2.16.840.1.101.3.4.2.1 sha-256 (NIST Algorithm)
  [2] (1 elem)
    INTEGER 222
```
which matches with [RSASSA-PSS description](https://tools.ietf.org/html/rfc8017#appendix-A.2.3) (using the default trailerField value):
```
   The object identifier id-RSASSA-PSS identifies the RSASSA-PSS
   encryption scheme.

       id-RSASSA-PSS    OBJECT IDENTIFIER ::= { pkcs-1 10 }

   The parameters field associated with this OID in a value of type
   AlgorithmIdentifier SHALL have a value of type RSASSA-PSS-params:

   RSASSA-PSS-params ::= SEQUENCE {
       hashAlgorithm      [0] HashAlgorithm      DEFAULT sha1,
       maskGenAlgorithm   [1] MaskGenAlgorithm   DEFAULT mgf1SHA1,
       saltLength         [2] INTEGER            DEFAULT 20,
       trailerField       [3] TrailerField       DEFAULT trailerFieldBC
   }
```

 [1]: https://lapo.it/asn1js/#308202E1308201C9A003020102021430A24FE5C922C05B5526867C3AEE72A4EB700521300D06092A864886F70D01010B05003000301E170D3137303930383137313533345A170D3137313030383137313533345A300030820122300D06092A864886F70D01010105000382010F003082010A0282010100AFE0D9B0D2F108BB177AF8741EAA477DCB9B318E8F4F7B6860471BAA6A978DFDCD59F735337B1AB44F79A1BB94A9E0C63877A6967D9E635C1505C9F22619D57B7A5A0E9B3B533612A9E432B3FD970205AA08DE3AD32FEC24400077201A4F695B0D688DAE737B8CC7B3EF508BC56A2D382EDAA8F7A8874A603529F9A64A153568D8460B484F974357D053EF66A23CCE6DB0AC2498EC390304CCAA68B765957E8BB654B401E4E9375970EBF0D39D23F6BCFFA7090E44991673D3C9C0B97EA0E16086708F6ABB45816B2B140BA0F55B4964CF1AC48CB86F8331DD771A42285FDCABC9EF7B51DD9FD1E103E556FEB65948DF73565F6B813DD9AB92283071C85C91E10203010001A3533051301D0603551D0E04160414ED622CC00992DD41B2C5EA0E6390E66CD47CEBA3301F0603551D23041830168014ED622CC00992DD41B2C5EA0E6390E66CD47CEBA3300F0603551D130101FF040530030101FF300D06092A864886F70D01010B0500038201010094C84554F9C267A6BCC68669C317C4EB37DE89308017E9FEEC47B253D77CC87539F1C49AB760CCD312C3984DA0242C7C3FA4B4418E617480475F70B35F67C859F2C549A58CC98FD12CACADE48B6B916A571F636C59DE538FCBB239E2267C2D19460827A602CCD590051F4AEF13DBBD1CC2F038D10ACBB90C5F0DE9C52C7E2533B70C9471BC236B3F962300952D6BF1E356C5507DD7C3509DA6DE144328EB5C96A6F438B113787702138ADA6FDEF84C4BE4C29B21E89B72886F0EA99909248F3734C65B43E9DAB3243358D7EBC0CEC336A8A8E66BB7F3D7126B9E87E2C3F31DA26930F8A47518FD279F98808835A4C194CC37FD3AB192E94659D2E4855F4836F1
 [2]: https://lapo.it/asn1js/#30820341308201F8A0030201020214667E46A5EF988EF0AD17F1CE26E8E3A61B82ACDE303E06092A864886F70D01010A3031A00D300B0609608648016503040201A11A301806092A864886F70D010108300B0609608648016503040201A204020200DE3000301E170D3137303930383137303335395A170D3137313030383137303335395A300030820120300B06092A864886F70D01010A0382010F003082010A0282010100C8ADC2A90C6DC8A27AF2081E738C6C0421035E27FBED6886887EDBB9A824ACBFBC062432608692ECA457B7363EAC0A3CA50A4A716A9AAD5A7F80736C1B86E5A3111549E44F4313139B43A6E14A3CBE3DFBFEC3F3F411D1BD785AE6A647F8459FF6016BC68BE63F124D26C58F61C936595A84D9B799A6B540597017CAA4DEF5AF01553D746D4AB187DDA41ED29473AB4237C8487812219C753EB3A1966BF2D8E6AE052CC25F68D8A6E385CDBDD08E2A36B1283B41453C52071D6910AB0AF3468FB3F8E0B0A362172A4D0F692E6EBCFEE3682AC850B46FB330414FB3087411A4E89090C214B738B357F5BF3E1382CC60DEF70B2A2CA28CBB20F45640CB975254D10203010001A3533051301D0603551D0E041604149EEB7F605C5C250BCE13847D805AF546D34D9A0F301F0603551D230418301680149EEB7F605C5C250BCE13847D805AF546D34D9A0F300F0603551D130101FF040530030101FF303E06092A864886F70D01010A3031A00D300B0609608648016503040201A11A301806092A864886F70D010108300B0609608648016503040201A204020200DE0382010100BB2D3BCF9BEEF5282B10EDE4830449DA644378516201C4ECB36B0C0F97613E536C257645B4052F606CD993282E51E7E280BAEE24B383FA2B4876E62B8BBD0879274E87369A371C3C3F4D1C1B561E4893787F90F2BCB59AD77C0F58AEF1F161AEACC424EB0BB9FDCD2CC308DAFF9C22D6E9122346BF76A7967ECA2CDFA203CA3F3CCC79F40C87ED05814A2C02EF5F189522754126B4236E478FB9BE81531789B236077B91568A3B1C261C63EAEE9C3673F9DE1428900C0F29C0174A062DD56F3A787FB57AE781576423DE3F538CCD260F51FEABBF17290C025894EDCB2A0118316E4A9853F56BE291BEA531CDCD2434ED0B4249F6AC403C9851D73D72D6B57417

**Comment by snhenson** [comment]
Yes that's correct RSASSA-PSS certificates are not currently supported. They're very rarely encountered in practice partly because they weren't supported at all before TLS 1.3. Anyone know of any test servers carrying an RSASSA-PSS certificate?

**Comment by Lekensteyn** [comment]
I was working on adding RSASSA-PSS support to Go crypto/tls and can try to create a test server based on that, are you looking for an port to connect?

Relevant discussions at the IETF list:
- [[TLS] PSS and TLS 1.3][1]
- [[Re: [TLS] TLS RSA-PSS and various versions of TLS][2]

I'll try to query the list since this seems to be a problem with the spec.

 [1]: https://www.ietf.org/mail-archive/web/tls/current/msg22326.html
 [2]: https://www.ietf.org/mail-archive/web/tls/current/msg22458.html

**Comment by tomato42** [comment]
GnuTLS and tlslite-ng supports RSA-PSS certificates, don't think there are any example servers that use them though.

> I'll try to query the list since this seems to be a problem with the spec.

which part of it? It does allow rsa-pss signatures in certificates, and rsa-pss keys in certificates are not far from that. Also, given that all the upsides of RSA-PSS go out the window the second the same key is used for regular RSA-PKCS#1 v1.5 singing, using rsa-pss keys in certificates is not entirely crazy idea - this way you know that the key can't be abused (see also: DROWN).

**Comment by tomato42** [comment]
@Lekensteyn "I think you are missing the dhparam file:"

You can't use custom DH parameters in TLS 1.3, the parameters are encoded in the library. Also, you don't need them in TLS 1.2 either as RFC 7919 is defined for earlier protocols and is implemented in OpenSSL.

**Comment by Lekensteyn** [comment]
The problem I see is that the restrictions on RSASSA-PSS certs are not explicit and that implementations might have different interpretations which might give headaches in deployment later, see https://www.ietf.org/mail-archive/web/tls/current/msg24440.html

> Also, given that all the upsides of RSA-PSS go out the window the second the same key is used for regular RSA-PKCS#1 v1.5 singing, using rsa-pss keys in certificates is not entirely crazy idea

Assuming a cert "C" signed by a CA "CA", then the RSA-PSS signature in cert "C" is done using the private key from "CA" while handshake messages use the private key from "C". You can normally not use the "CA" key in an oracle, so whether cert "C" uses a RSA-PSS or PKCS#1 signature should not matter right? (Cert signature is independent from the handshake message signing.)

As for cross-protocol (version) attacks due to key reuse, it seems that mixing PSS with PKCS1 does not have known issues: https://www.ietf.org/mail-archive/web/cfrg/current/msg08834.html

**Comment by tomato42** [comment]
I think you are confusing rsa-pss keys in certificates and rsa-pss signatures in certificates.

If you have a rsa-pss public key in certificate, then all signatures you make using it must be rsa-pss signatures. If that is an EE certificate, that certificate can't be used for TLS 1.1 and earlier and in TLS1.2 requires the use of RSA-PSS signatures over CV or SKE. Note, that this holds _irrespective_ of signature in the certificate itself, which are made by the CA and can still be made using PKCS#1.

**Comment by Lekensteyn** [comment]
Yep, I was solely considering rsa-pss signatures and not public keys. I do agree with your view regarding rsa-pss public keys.

I am still confused by the TLS 1.3 draft though, it says that "the EE cert public key must be compatible with the selected authentication algorithm (currently RSA, ECDSA, EdDSA)" which does not mention the RSA-PSS variant explicitly.

It says that all (not just the EE) cert must by signed by a signature algorithm in the signature_algorithms extension. So that means that a client must support rsa-pss signatures *in* certificates? If so, which of these *must* (not) be supported if a client advertises rsa_pss_sha256:
- signature=sha256WithRSAEncryption, pubkey=id-RSASSA-PSS
- signature=id-RSASSA-PSS+params, pubkey=rsaEncryption (what params exactly? Ilari has listed a subset here: https://www.ietf.org/mail-archive/web/tls/current/msg24441.html)
- signature=sha256WithRSAEncryption, pubkey=rsaEncryption (support use of this for easier deployment...? This is done by https://tls.ctf.network)

**Comment by tomato42** [comment]
> I am still confused by the TLS 1.3 draft though, it says that "the EE cert public key must be compatible with the selected authentication algorithm (currently RSA, ECDSA, EdDSA)" which does not mention the RSA-PSS variant explicitly.

Because on TLS level you can make only RSA-PSS signatures. But such signatures can be made using RSA-PKCS#1 v1.5 keys and RSA-PSS keys.

> It says that all (not just the EE) cert must by signed by a signature algorithm in the signature_algorithms extension.

yes, it also says that server may choose a different certificate if it cannot find one that matches exactly:
```
   If the server cannot produce a certificate chain that is signed only
   via the indicated supported algorithms, then it SHOULD continue the
   handshake by sending the client a certificate chain of its choice
   that may include algorithms that are not known to be supported by the
   client.
```

> If so, which of these must (not) be supported if a client advertises rsa_pss_sha256:

if client sends only this one, then I'd say the certificate can have only the following parameters:

 * signature=id-RSASSA-PSS+params, pubkey=id-RSASSA-PSS

anything else is guesswork on server's part.

But If the client sends both `rsa_pss_sha256` and `rsa_pkcs1_sha256` then given section 9.1:
```
   A TLS-compliant application MUST support digital signatures with
   rsa_pkcs1_sha256 (for certificates), rsa_pss_sha256 (for
   CertificateVerify and certificates)
```

I'd say that all the combinations you provided are allowed, and the additional one I added.
Regarding parameters, I'd say the certificates should use the salt the same length as the hash output, but for PKIX it's probably not necessary (and may be counter-productive) to be strict about it. Either way, I wouldn't see it as a bug if the PKIX part allowed full freedom for RSA-PSS parameters, with exception of allowing deprecated hashes and RSA key sizes.

**Comment by snhenson** [comment]
See #4368

**Comment by mattcaswell** [comment]
Linked PR was merged. Closing this.
