### ISSUE TITLE
Error 126 during MinGW install

### ISSUE THREAD

**Issue by reesul** [openssl/openssl#2879]
When trying to run make install in msys2, it makes it through installing development files, engines, runtime files.  As shown in the image, it creaks off around where it says installing manpages, citing that something is already a directory.  I have 2 accounts on this PC, "foo" and "foo admin" and it looks like this may be causing a problem with file naming due to the similarity and the space.  Any ideas on how to fix this?  I'm sure it wouldn't hurt to change the name of the admin account (I'll do this anyway), but beyond that, I am unsure what I can do here.  Thanks

![image](https://cloud.githubusercontent.com/assets/25847720/23714597/7454e1b0-03ef-11e7-8e79-393ad29a9c7c.png)

**Comment by levitte** [comment]
Spaces in file names are a known problem with no easy solution. Avoid them.

**Comment by levitte** [comment]
This is particularly true with Unix like systems. `make` doesn't generally have any good mechanism to deal with them.
