### ISSUE TITLE
DSA_sign segfault when DSA->priv_key is null (meth == DSA_OpenSSL())

### ISSUE THREAD

**Issue by bartonjs** [openssl/openssl#2905]
DSA->priv_key is never checked for null before being passed to BN_mod_mul (https://github.com/openssl/openssl/blob/8cc44d970ced1004db0727d7a7b3e2709c442e55/crypto/dsa/dsa_ossl.c#L95), which eventually segfaults in BN_mul.

`p`, `q`, or `g` missing result in DSA_R_MISSING_PARAMETERS; so the function already shows a bit of expecting bad input.

**Comment by bartonjs** [comment]
While I found this interfacing with 1.0.2, it looks like it's still there in 1.1.x/master.

**Comment by richsalz** [comment]
The checks for missing-params are "old school."  We don't check that the object has all its fields set.  Just like C doesn't check for a NULL to strcpy.  :)

**Comment by bartonjs** [comment]
@richsalz Is there a non-segfaulting way to determine if a DSA (or RSA/ECC/etc) instance has private parameters?  I know that the original caller should know what sort of structure they've loaded in, but it feels like something that should be runtime checked, vs crashing.

**Comment by richsalz** [comment]
You could get the private key and see if it's non-null
