### ISSUE TITLE
How to get the source code for openssl including "libssl.so.1.0.0"

### ISSUE THREAD

**Issue by JunHuang023** [openssl/openssl#2908]

**Comment by richsalz** [comment]
https://www.openssl.org/source/  Or, you know, clone this git repo.

**Comment by levitte** [comment]
It sounds like you're asking for building instructions.  Here's a quickie:

```
./config shared
make
```

If you have any further questions, please subscribe to openssl-users@openssl.org, see subscription links [here](https://www.openssl.org/community/mailinglists.html)

**Comment by JunHuang023** [comment]
Sorry,  I guess this is not even an issue. I was looking for the source code for "OpenSSL" but somehow could not find out. I tried installing "openssl-1.0.0k.tar.gz" but after the installation I could not find the "libssl.so.1.0.0",$ ldd ./openssl 
	linux-vdso.so.1 =>  (0x00007fffb5dd0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003cae000000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003cad800000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003cad400000)
I assumed the “libssl.so.1.0.0” should be find in “openssl-1.0.0*”, 
after two attempts with “openssl-1.0.0k”, "openssl-1.0.0l". I doubted about my assumption.  Looking for suggestions.

**Comment by richsalz** [comment]
We only distribute source  code that you will need to configure and compile.  See the README file, for example.

**Comment by JunHuang023** [comment]
@richsalz . Thanks for your reply. Sorry that I did not explain very well. By "installation", I meant: 
```
    tar xvzf openssl-1.0.0k.tar.gz 
    cd openssl-1.0.0k
    ./config --prefix=$HOME/Programme/openssl --openssldir=$HOME/Programme/ssl # https://wiki.openssl.org/index.php/Compilation_and_Installation seemed to strongly suggest to specify "openssldir"
    make && make install
```
I noticed levitte's reply. so I tried:
`$ ./config shared --prefix=$HOME/Programme/openssl --openssldir=$HOME/Programme/ssl
`
```
 ldd ./openssl 
	linux-vdso.so.1 =>  (0x00007fff5abfd000)
	libssl.so.1.0.0 => /somewhere/Jun/Programme/openssl/lib/libssl.so.1.0.0 (0x00002b524de5c000)
	libcrypto.so.1.0.0 => /somewhere/Jun/Programme/openssl/lib/libcrypto.so.1.0.0 (0x00002b524e0c1000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003cae000000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003cad800000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003cad400000)
```
Things look pretty good.  I did not include "share" when configuration. I guess I am all set. Thanks.

**Comment by qazzaq1017** [comment]
> It sounds like you're asking for building instructions. Here's a quickie:
> 
> ```
> ./config shared
> make
> ```
> 
> If you have any further questions, please subscribe to [openssl-users@openssl.org](mailto:openssl-users@openssl.org), see subscription links [here](https://www.openssl.org/community/mailinglists.html)

hello, I have tried this but I have no root. So I got the following error when trying 'make install':

 Cannot create directory /usr/local/ssl: Permission denied
make: *** [Makefile:594: install_docs] Error 13

Any solution to avoid root?
