### ISSUE TITLE
Wrong server alert message when client advertised obsolete/bogus sign. algorithm ( 1.0.2 )

### ISSUE THREAD

**Issue by 7echno** [openssl/openssl#2919]
Seems that server is responding with "illegal_parameter(47)" instead of "handshake_failure(40)"
when client advertised obsolete or bogus signature algorithms.

version:  openssl-1.0.2
Behaviour is different then in 1.0.1, where handshake_failure(40) is sent.

Reproducer:
`openssl req -x509 -newkey rsa:2048 -keyout localhost.key -out localhost.crt -nodes -batch -subj /CN=localhost`
`openssl s_server -cert localhost.crt -key localhost.key -accept 4433 -www`

In another terminal:
`git clone https://github.com/7echno/tlsfuzzer.git`
`pushd tlsfuzzer`
`git clone https://github.com/tomato42/tlslite-ng.git .tlslite-ng`
`ln -s .tlslite-ng/tlslite tlslite`
`git clone https://github.com/warner/python-ecdsa.git .python-ecdsa`
`ln -s .python-ecdsa/src/ecdsa ecdsa`

`PYTHONPATH=. python scripts/test-clienthello-md5.py`

**Comment by mattcaswell** [comment]
This seems to be already fixed in master. Fixes for 1.1.0 and 1.0.2 in #6010 and #6011 respectively.

Changing the milestone to 1.1.0 since this doesn't impact master

**Comment by mattcaswell** [comment]
Fixed by the above 2 PRs. Closing.
