### ISSUE TITLE
Syntax error in Configure / windows / perl

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#2923]
Hello

Using perl [1] on Windows, I have a syntax error for perl ./Configure for version openssl-SNAP-20170313

perl ./Configure gcc -E
Backslash found where operator expected at ./Configure line 1868, near "if ($dest ne "" && $d =~ /\"
  (Might be a runaway multi-line // string starting on line 1859)
    (Do you need to predeclare if?)
Scalar found where operator expected at ./Configure line 1868, near ")$/"
    (Missing operator before $/?)
Global symbol "$e" requires explicit package name at ./Configure line 1859.
syntax error at ./Configure line 1868, near "if ($dest ne "" && $d =~ /\"
Can't use global $_ in "my" at ./Configure line 1871, near "{ $_ "
syntax error at ./Configure line 1927, near "}"
Execution of ./Configure aborted due to compilation errors.

Can you help me ?

Thanks a lot !

[1] :

This is perl, v5.8.8 built for msys-64int

Copyright 1987-2006, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by kaduk** [comment]
Check out NOTES.PERL; in particular, 5.8.8 is too old.
IIRC you want msys2 instead of msys.

**Comment by qualitesys** [comment]
Thanks a lot, it's perfect !
