### ISSUE TITLE
Inconsistency in OPENSSL_sk_find

### ISSUE THREAD

**Issue by pauli-oracle** [openssl/openssl#2925]
The way the sk_TYPE_find function works differently depending on the presence of a sorting function or not.

The test case below outputs:
```
linear search of 3 reveals: -1
binary search of 3 reveals: 2
```

The difference being that the linear search is performing a comparison of pointers and the binary search is performing a comparison of values.  This could be problematic if, e.g., two items that compare equal are inserted into the stack -- searching for one could find the other.

The program that produces the output above is:
```
#include <stdio.h>
#include <string.h>
#include <openssl/safestack.h>

DEFINE_STACK_OF(int);

static int compare(const int *const *a, const int *const *b)
{
    if (**a < **b)
        return -1;
    if (**a > **b)
        return 1;
    return 0;
}

int main(int argc, char *argv[]) {
    int v[3] = { 1, 3, 2 };
    int i;
    STACK_OF(int) *s = sk_int_new_null();

    for (i=0; i<3; i++)
        sk_int_push(s, v+i);

    i = 3;
    printf("linear search of 3 reveals: %d\n", sk_int_find(s, &i));
    sk_int_set_cmp_func(s, &compare);
    printf("binary search of 3 reveals: %d\n", sk_int_find(s, &i));
    sk_int_free(s);
    return 0;
}
```

**Comment by levitte** [comment]
This behavior is documented.  From doc/man3/DEFINE_STACK_OF.pod through `perldoc` (see the Note:):

```
    sk_TYPE_find() and sk_TYPE_find_ex() search sk using the supplied
    comparison function for an element matching ptr. sk_TYPE_find() returns
    the index of the first matching element or -1 if there is no match.
    sk_TYPE_find_ex() returns a matching element or the nearest element that
    does not match ptr. Note: if a comparison function is set then sk is
    sorted before the search which may change its order. If no comparison
    function is set then a linear search is made for a pointer matching ptr
    and the stack is not reordered.
```

**Comment by pauli-oracle** [comment]
I had read that, it is correct but isn't terribly clear.

**Comment by levitte** [comment]
I can understand that...  but I don't dare think of the ramifications of changing that.  "Here be dragons" 'n all that...

**Comment by pauli-oracle** [comment]
Perhaps the documentation could use an update.  I should be able to get to it today.

I've also located a problem with sk_TYPE_find_ex: the _nearest_ element to the one searched for can either be the one after or the one before -- I initially read nearest as the closest in value but that's impossible given the comparison function's return values.  A documentation update is likely safer than changing the code here too.

**Comment by levitte** [comment]
I look forward to that doc update

**Comment by richsalz** [comment]
doc update merged, closing this.
