### ISSUE TITLE
Cipherstring parsing does not recognize TLSv1.3

### ISSUE THREAD

**Issue by ekasper** [openssl/openssl#2936]
In test_ssl_old, we have the following block

```	
my $ciphers = "-EXP:-PSK:-SRP:-kDH:-kECDHe";
my @protocols = ();
# FIXME: I feel unsure about the following line, is that really just TLSv1.2, or is it all of the SSLv3/TLS protocols?
push(@protocols, "TLSv1.3") unless $no_tls1_3;
push(@protocols, "TLSv1.2") unless $no_tls1_2;
push(@protocols, "SSLv3") unless $no_ssl3;
my $protocolciphersuitcount = 0;
my %ciphersuites =
  map { my @c =
    map { split(/:/, $_) }
              run(app(["openssl", "ciphers", "${_}:$ciphers"]),
              capture => 1);
    map { s/\R//; } @c;  # chomp @c;
    $protocolciphersuitcount += scalar @c;
    $_ => [ @c ] } @protocols;
```

However this doesn't actually end up testing TLS1.3 ciphers. Rather, it fails with

```
Error in cipher list
47344346143168:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../openssl/ssl/ssl_lib.c:2348:
../util/shlib_wrap.sh ../apps/openssl ciphers 'TLSv1.3:-EXP:-PSK:-SRP:-kDH:-kECDHe' => 1
```

because 'TLSv1.3' is not a recognized cipher string.

@mattcaswell

**Comment by kroeckx** [comment]
I'm not sure it's a good idea to introduce TLS1.3 as a cipher string. Having SSLv3 in there has already caused enough confusion. What does this test use it for?

**Comment by richsalz** [comment]
I strongly agree, it's a protocol version not a cipher string.

**Comment by levitte** [comment]
Is there a reason it does recognise `TLSv1.0` and `TLSv1.2`, considering they are also protocol versions?

**Comment by richsalz** [comment]
see kurt's comment.

**Comment by levitte** [comment]
That didn't answer at all why it recognise *some* TLS version strings as cipher strings.

```
: ; ./util/shlib_wrap.sh apps/openssl ciphers TLSv1.0
ECDHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-CAMELLIA256-SHA384:RSA-PSK-CAMELLIA256-SHA384:DHE-PSK-CAMELLIA256-SHA384:PSK-AES256-CBC-SHA384:PSK-CAMELLIA256-SHA384:ECDHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-CAMELLIA128-SHA256:RSA-PSK-CAMELLIA128-SHA256:DHE-PSK-CAMELLIA128-SHA256:PSK-AES128-CBC-SHA256:PSK-CAMELLIA128-SHA256:ECDHE-PSK-NULL-SHA384:ECDHE-PSK-NULL-SHA256:RSA-PSK-NULL-SHA384:RSA-PSK-NULL-SHA256:DHE-PSK-NULL-SHA384:DHE-PSK-NULL-SHA256:PSK-NULL-SHA384:PSK-NULL-SHA256
```

**Comment by richsalz** [comment]
It's a mis-feature.  We can't kill it, but we shouldn't make it worse.  The meaning of those strings is confusing to everyone.

**Comment by levitte** [comment]
Ok.

I'll have a look to see if I can figure out a better way to get the desired ciphers...

**Comment by richsalz** [comment]
Just name the ciphers as we currently do.  It is deliberate that TLS 1.3 didn't create any new ciphers.  The TLS1.1,etc., strings mean (I think) ciphers that were introduced in that version.

**Comment by levitte** [comment]
Have a look at #2956

**Comment by mattcaswell** [comment]
This was fixed by the linked PR. Closing.
