### ISSUE TITLE
id-aes256-GCM not working

### ISSUE THREAD

**Issue by MrOutput** [openssl/openssl#294]
Ubuntu 15.04
Kernel 4.1.0-rc2
OpenSSL 1.0.2a 19 Mar 2015

```
rafael@rcepeda:/usr/local/ssl/bin$ ./openssl genpkey -algorithm rsa -id-aes256-GCM -out ~/key.pem rsa_keygen_bits:4096
.................................................++++++
............++++++
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
Error writing key
140027112167056:error:23077006:PKCS12 routines:PKCS12_pbe_crypt:EVP lib:p12_decr.c:99:
140027112167056:error:2306C067:PKCS12 routines:PKCS12_item_i2d_encrypt:encrypt error:p12_decr.c:188:
140027112167056:error:2307D067:PKCS12 routines:PKCS8_encrypt:encrypt error:p12_p8e.c:96:
```

**Comment by h-yamamo** [comment]
some relation to the following.

```
$ openssl enc -aes-256-gcm -in hoo -out bar
AEAD ciphers not supported by the enc utility
```
debian 8, openssl 1.0.1k-3

**Comment by amitkhannacs** [comment]
I've run into the same issue. I'm on the latest build for openssl (1.0.2e) but still get the error "AEAD ciphers not supported by the enc utility" when using aes-256-gcm.

Were you able to resolve the issue? If yes, can you share the steps you took?

**Comment by richsalz** [comment]
There is no resolution.  AEAD ciphers do not work with the enc program in openssl 1.0.1/1.0.2.

**Comment by MrOutput** [comment]
Thank you @richsalz  closing this now

**Comment by VishalVMishra** [comment]
How about in the latest version - OpenSSL 1.1.0  25 Aug 2016 ?

**Comment by richsalz** [comment]
not in 1.1.0; hopefully the next release.

**Comment by ppdouble** [comment]
> some relation to the following.
> 
> ```
> $ openssl enc -aes-256-gcm -in hoo -out bar
> AEAD ciphers not supported by the enc utility
> ```
> 
> debian 8, openssl 1.0.1k-3

`enc: AEAD ciphers not supported` for OpenSSL 1.1.1d FIPS  10 Sep 2019 in fedora 29 x64 workstation.

**Comment by RobertKoenig19** [comment]
can't use aes-256-cgm in openssl 3.5.0 on Windows 11

Please help me

**Comment by mattcaswell** [comment]
> can't use aes-256-cgm in openssl 3.5.0 on Windows 11

You've posted this on the end of an old issue which has been closed for over 9 years. Please create a new discussion item and explain what you are trying to achieve, what you have tried so far and what happened.

https://github.com/openssl/openssl/discussions/new?category=q-a

**Comment by RobertKoenig19** [comment]
Dear writer mattcaswell,

Thanks for the reply. I”ve opens a new bug report.

Best regards 
Robert
