### ISSUE TITLE
make test hangs in OSX (while good in CentOS).

### ISSUE THREAD

**Issue by tedescn** [openssl/openssl#2950]
When running "make test" on OSX recent changes cause "test_tls13kexmodes.t" to hang, The same test is currently good for CentOS Linux.

see output below.

Regards
Nigel

make test
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _tests
( cd test; \
	  SRCTOP=../. \
	  BLDTOP=../. \
	  PERL="/opt/local/bin/perl5.24" \
	  EXE_EXT= \
	  OPENSSL_ENGINES=.././engines \
	  OPENSSL_DEBUG_MEMORY=on \
	    /opt/local/bin/perl5.24 .././test/run_tests.pl  )
../test/recipes/01-test_abort.t ............... ok   
../test/recipes/01-test_sanity.t .............. ok   
../test/recipes/01-test_symbol_presence.t ..... ok   
../test/recipes/02-test_ordinals.t ............ ok   
../test/recipes/03-test_exdata.t .............. ok   
../test/recipes/03-test_internal_asn1.t ....... ok   
../test/recipes/03-test_internal_chacha.t ..... ok   
../test/recipes/03-test_internal_mdc2.t ....... ok   
../test/recipes/03-test_internal_modes.t ...... ok   
../test/recipes/03-test_internal_poly1305.t ... ok   
../test/recipes/03-test_internal_siphash.t .... ok   
../test/recipes/03-test_internal_x509.t ....... ok   
../test/recipes/03-test_ui.t .................. ok   
../test/recipes/04-test_pem.t ................. ok     
../test/recipes/05-test_bf.t .................. ok   
../test/recipes/05-test_cast.t ................ ok   
../test/recipes/05-test_des.t ................. ok   
../test/recipes/05-test_hmac.t ................ ok   
../test/recipes/05-test_idea.t ................ ok   
../test/recipes/05-test_md2.t ................. skipped: md2 is not supported by this OpenSSL build
../test/recipes/05-test_mdc2.t ................ ok   
../test/recipes/05-test_rand.t ................ ok   
../test/recipes/05-test_rc2.t ................. ok   
../test/recipes/05-test_rc4.t ................. ok   
../test/recipes/05-test_rc5.t ................. skipped: rc5 is not supported by this OpenSSL build
../test/recipes/05-test_sha1.t ................ ok   
../test/recipes/05-test_sha256.t .............. ok   
../test/recipes/05-test_sha512.t .............. ok   
../test/recipes/10-test_bn.t .................. ok   
../test/recipes/10-test_exp.t ................. ok   
../test/recipes/15-test_dh.t .................. ok   
../test/recipes/15-test_dsa.t ................. ok   
../test/recipes/15-test_ec.t .................. ok   
../test/recipes/15-test_ecdh.t ................ ok   
../test/recipes/15-test_ecdsa.t ............... ok   
../test/recipes/15-test_genrsa.t .............. ok   
../test/recipes/15-test_rsa.t ................. ok   
../test/recipes/15-test_rsapss.t .............. ok   
../test/recipes/20-test_enc.t ................. ok       
../test/recipes/20-test_enc_more.t ............ ok       
../test/recipes/20-test_passwd.t .............. ok     
../test/recipes/25-test_crl.t ................. ok   
../test/recipes/25-test_d2i.t ................. ok     
../test/recipes/25-test_pkcs7.t ............... ok   
../test/recipes/25-test_req.t ................. ok   
../test/recipes/25-test_sid.t ................. ok   
../test/recipes/25-test_verify.t .............. ok       
../test/recipes/25-test_x509.t ................ ok   
../test/recipes/30-test_afalg.t ............... skipped: test_afalg not supported for this build
../test/recipes/30-test_engine.t .............. ok   
../test/recipes/30-test_evp.t ................. ok   
../test/recipes/30-test_evp_extra.t ........... ok   
../test/recipes/30-test_pbelu.t ............... ok   
../test/recipes/30-test_pkey_meth.t ........... ok   
../test/recipes/40-test_rehash.t .............. ok   
../test/recipes/60-test_x509_store.t .......... ok   
../test/recipes/60-test_x509_time.t ........... ok   
../test/recipes/70-test_asyncio.t ............. ok   
../test/recipes/70-test_bad_dtls.t ............ ok   
../test/recipes/70-test_clienthello.t ......... ok   
../test/recipes/70-test_key_share.t ........... ok    
../test/recipes/70-test_packet.t .............. ok   
../test/recipes/70-test_recordlen.t ........... ok   
../test/recipes/70-test_renegotiation.t ....... ok   
../test/recipes/70-test_sslcbcpadding.t ....... ok   
../test/recipes/70-test_sslcertstatus.t ....... ok   
../test/recipes/70-test_sslextension.t ........ ok   
../test/recipes/70-test_sslmessages.t ......... ok     
../test/recipes/70-test_sslrecords.t .......... ok    
../test/recipes/70-test_sslsessiontick.t ...... ok    
../test/recipes/70-test_sslsigalgs.t .......... ok    
../test/recipes/70-test_sslsignature.t ........ ok   
../test/recipes/70-test_sslskewith0p.t ........ ok   
../test/recipes/70-test_sslversions.t ......... ok   
../test/recipes/70-test_sslvertol.t ........... ok   
../test/recipes/70-test_tls13cookie.t ......... ok   
../test/recipes/70-test_tls13kexmodes.t ....... 1/?  **<----- tests hang at this point.**

**Comment by mattcaswell** [comment]
Does it consistently hang in the same place?

**Comment by tedescn** [comment]
Yes, hangs at the same place - I repeated "make test" 3 or 4 times to confirm. With --debug directive nothing obvious stands out.

**Comment by mattcaswell** [comment]
What config options did you use?

**Comment by tedescn** [comment]
config is reasonably basic.

./config --prefix=/usr/local/openssl-$OPENSSL_VERSION --openssldir=/usr/local/openssl-$OPENSSL_VERSION/ssl shared enable-tls1_3

**Comment by mattcaswell** [comment]
Please could you try the patch in #2955.

**Comment by mattcaswell** [comment]
> Please could you try the patch in #2955 

Or just pull down a fresh copy of master - I just merged that PR.

**Comment by tedescn** [comment]
I should be able to test this evening. 

I will initially attempt to pull the master. If there are issues, I will try the patch against the source of yesterday.

**Comment by tedescn** [comment]
Just to confirm I pulled down a fresh copy of the master and all tests completed successfully :-)

The efforts of the OpenSSL team is greatly appreciated.

Regards
Nigel

**Comment by mattcaswell** [comment]
Great - thanks for the confirmation.
