### ISSUE TITLE
Failed to run openssl test after revision 22cef4e (Split test/recipes/03_test_internal.t into individual tests) on Windows.

### ISSUE THREAD

**Issue by KarenHuang2016** [openssl/openssl#2959]
Hi,

I tried to build openssl using VS2015 update 3 on Windows. I noticed that openssl test failed to run after revision [22cef4e ](https://github.com/openssl/openssl/commit/22cef4e1f1f8f4346cc8b10b3374936c6b33624f)(Split test/recipes/03_test_internal.t into individual tests). The following is the steps I used to build and run test for openssl:
1. git clone https://github.com/openssl/openssl D:\openssl\src
2. cd D:\openssl\src
3. perl Configure VC-WIN32
4. nmake clean
5. where cl.exe
6. nmake
7. nmake test

Here is the error message:
[executing command] nmake test 
Microsoft (R) Program Maintenance Utility Version 14.10.25113.0
Copyright (C) Microsoft Corporation.  All rights reserved.
	set SRCTOP=.
	set BLDTOP=.
	set PERL=C:\Perl\bin\perl.exe
	set OPENSSL_DEBUG_MEMORY=on
	"C:\Perl\bin\perl.exe" ".\test\run_tests.pl" 
test\recipes\01-test_abort.t ............... ok
test\recipes\01-test_sanity.t .............. ok
test\recipes\01-test_symbol_presence.t ..... ok
test\recipes\02-test_ordinals.t ............ ok
test\recipes\03-test_exdata.t .............. ok
**Bailout called.  Further testing stopped:  Must run setup() first
FAILED--Further testing stopped: Must run setup() first**
NMAKE : fatal error U1077: 'C:\Perl\bin\perl.exe' : return code '0xff'
Stop.

Could you please take a look at this? Thanks!

**Comment by dot-asm** [comment]
I've ran into it yesterday and it's not addressed in b3068d0ac48c827403115a3b5cbc3655243e2cf0. Thanks for report.
