### ISSUE TITLE
Remove EGD support or make EGD support configurable

### ISSUE THREAD

**Issue by Sp1l** [openssl/openssl#296]
The next release of OpenSSL 1.0.2 still seems to contain code supporting the Perl Entropy Gathering Daemon. No current platform requires EGD, all platforms have a far superior and more secure source of entropy. 

OS | EGD needed until | OS released | End-of-support
------------ | ------------- | ------------ | -------------
IRIX | 6.5.19 | Feb 2003 | Dec 2013
Solaris | 2.6 | Jul 1997 | Jul 2006
AIX | 5.2 | Oct 2002 | Apr 2009
Tru64 | 5.1B | Sep 2002 | Dec 2012
HP-UX | 11i v2 | Sep 2003 | Dec 2015

"Legacy platforms that are unlikely to have wide deployment will be removed from the code." suggests that you no longer need to support systems requiring Perl EGD as source of randomness and I believe this should be removed.

**Comment by richsalz** [comment]
done.
