### ISSUE TITLE
Openssl1.0.2k configuration failed on AIX

### ISSUE THREAD

**Issue by mywordsarjun** [openssl/openssl#2973]
I'm building openssl 1.0.2k on AIX but on configuring step, it fails. I followed the following step:

1. export PATH=$PATH:/usr/vacpp/bin:/usr/vac/bin/

2. ./config shared --openssldir=/san5/aix/dev/32/openssl_32/install | tee configure_32bit.log

### Error: 
bash-4.2$ ./config shared --openssldir=/san5/aix/dev/32/openssl_32/install | tee configure_32bit.log
Operating system: 00C38FD54C00-ibm-aix
WARNING! If you wish to build 64-bit kit, then you have to
         invoke './Configure aix64-cc' *manually*.
Configuring for aix-cc
Configuring for aix-cc
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-krb5         [krb5-flavor not specified] OPENSSL_NO_KRB5
    no-libunbound   [experimental] OPENSSL_NO_LIBUNBOUND (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-rfc3779      [default]  OPENSSL_NO_RFC3779 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-ssl2         [default]  OPENSSL_NO_SSL2 (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS (skip dir)
    no-zlib         [default]
    no-zlib-dynamic [default]
IsMK1MF=0
CC            =cc
CFLAG         =-DOPENSSL_THREADS -qthreaded -D_THREAD_SAFE -DDSO_DLFCN -DHAVE_DLFCN_H -q32 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DVPAES_ASM
EX_LIBS       =
CPUID_OBJ     =ppccpuid.o ppccap.o
BN_ASM        =bn-ppc.o ppc-mont.o ppc64-mont.o
EC_ASM        =
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes_core.o aes_cbc.o aes-ppc.o vpaes-ppc.o aesp8-ppc.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4_enc.o rc4_skey.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =
SHA1_OBJ_ASM  =sha1-ppc.o sha256-ppc.o sha512-ppc.o sha256p8-ppc.o sha512p8-ppc.o
RMD160_OBJ_ASM=
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
MODES_OBJ     =ghashp8-ppc.o
ENGINES_OBJ   =
PROCESSOR     =
RANLIB        =/usr/ccs/bin/ranlib
ARFLAGS       =-X 32
PERL          =/usr/bin/perl
**THIRTY_TWO_BIT mode
BN_LLONG mode
RC4 uses uchar
RC4_CHUNK is undefined
make: *** No rule to make target `links'.  Stop.**

Please suggest if I am missing any step?

**Comment by levitte** [comment]
Read the warning at the beginning of the configuration output.

**Comment by mywordsarjun** [comment]
@levitte are you pointing to below warrning: 
WARNING! If you wish to build 64-bit kit, then you have to
invoke './Configure aix64-cc' manually.

 Its a warning if one want to configure 64-bit. Since I'm configuring for 32-bit we can ignore it, right? I did similarly for Solaris and HP and it worked fine.
Please suggest!

**Comment by levitte** [comment]
Ah, sorry, misread your intention there.

Do you have a `Makefile`?  Can you grep `links` from it and get output that looks about like this?

```
: ; grep links Makefile
links:
	@set -e; target=links; $(RECURSIVE_BUILD_CMD)
```
