### ISSUE TITLE
dso_win32.c error

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#2979]
Hi 
I build the openssl-SNAP-20170317 version on windows with msys2

perl ./Configure mingw 

Configuring OpenSSL version 1.1.1-dev (0x10101000L)
    no-aria         [default]  OPENSSL_NO_ARIA (skip dir)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-external-tests [default]  OPENSSL_NO_EXTERNAL_TESTS
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-tls1_3       [default]  OPENSSL_NO_TLS1_3
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default] 
    no-zlib-dynamic [default] 
Configuring for mingw

PERL          =perl
PERLVERSION   =5.24.1 for x86_64-msys-thread-multi
HASHBANGPERL  =/usr/bin/env perl
CC            =gcc
CFLAG         =-DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m32 -Wall -O3 -fomit-frame-pointer -D_MT 
CXX           =c++
CXXFLAG       =-DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m32 -Wall -O3 -fomit-frame-pointer -D_MT 
DEFINES       =OPENSSL_USE_APPLINK DSO_WIN32 NDEBUG OPENSSL_THREADS OPENSSL_NO_STATIC_ENGINE OPENSSL_PIC OPENSSL_BN_ASM_PART_WORDS OPENSSL_IA32_SSE2 OPENSSL_BN_ASM_MONT OPENSSL_BN_ASM_GF2m SHA1_ASM SHA256_ASM SHA512_ASM RC4_ASM MD5_ASM RMD160_ASM AES_ASM VPAES_ASM WHIRLPOOL_ASM GHASH_ASM ECP_NISTZ256_ASM PADLOCK_ASM POLY1305_ASM
EX_LIBS       =-lws2_32 -lgdi32 -lcrypt32 

I get a lot of errors for make (here an extract) :
crypto/dso/dso_win32.c:96:5: error: unknown type name 'HINSTANCE'
     HINSTANCE h = NULL, *p = NULL;
     ^~~~~~~~~
crypto/dso/dso_win32.c:96:19: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     HINSTANCE h = NULL, *p = NULL;
                   ^~~~
crypto/dso/dso_win32.c:104:9: warning: implicit declaration of function 'LoadLibraryA' [-Wimplicit-function-declaration]
     h = LoadLibraryA(filename);
         ^~~~~~~~~~~~

Is there a special option for this config ?

Thanks for your help

**Comment by mattcaswell** [comment]
This happens if you attempt to build OpenSSL using the msys gcc compiler rather than the mingw compiler. When you start up the msys shell be sure to pass either -mingw32 or -mingw64 as an argument to msys2_shell.cmd. Also ensure that you configure the correct OpenSSL target to match the environment (either mingw for 32 bit or mingw64 for 64 bit). Alternative don't invoke Configure directly and just do ./config which should detect the correct target automatically.
