### ISSUE TITLE
make -j parallel support ?

### ISSUE THREAD

**Issue by centminmod** [openssl/openssl#298]
curious any plans to fix openssl source compiles with make -j http://openssl.6102.n7.nabble.com/parallel-make-broken-td45613.html ?

**Comment by richsalz** [comment]
The patch mentioned there is specific to GNU make which is why we won't take it.

**Comment by centminmod** [comment]
thanks @richsalz so there's no other work or plans for parallel support besides that patch ?

**Comment by richsalz** [comment]
no, we're looking at a big overhaul of the make "systems" for the next release.  I hope something will show up in master in a couple of months.

**Comment by centminmod** [comment]
Sounds great looking forward to that as source compilations for openssl running pretty slow i.e. when trying to statically compile openssl for Nginx source compiles.
