### ISSUE TITLE
tls1.3-draft-18 Branch nginx error tls_parse_ctos_psk:internal error

### ISSUE THREAD

**Issue by Henrocker** [openssl/openssl#2983]
I compiled the `tls1.3-draft-18` Branch against nginx and use TLS13-* Ciphersuites.

Now whenever I visit my website and try to access a non existent directory or file (So it gives me a 404 error), in the nginx error log it says:

`
2017/03/18 12:54:54 [crit] 29903#29903: *5 SSL_do_handshake() failed (SSL: error:141F9044:SSL routines:tls_parse_ctos_psk:internal error) while SSL handshaking, client: 88.77.244.66, server: 0.0.0.0:443` and my site is no longer accessable due to openssl crash.

Any ideas?
Thanks

**Comment by richsalz** [comment]
not without a backtrace, no.
does nginx work with openssl 1.1.0?
is it CRASHING or failinlg to do the handshake?
Are you sure that the browser is using tls1.3-draft18?

**Comment by mattcaswell** [comment]
What client are you using to connect? Does that client manage to complete the handshake if you just connect to s_server?

**Comment by mattcaswell** [comment]
Bug!! I have recreated this issue in s_server/s_client. The problem was introduced by 6b1bb98f. You get this problem if you are trying to resume *and* the server issues a HelloRetryRequest.

**Comment by Henrocker** [comment]
@mattcaswell That's right. I used Google Chrome for visiting my Website over TLS 1.3 and the error appeared: ERR_SSL_PROTOCOL_ERROR, when I tried to revisit it after a while.

**Comment by mattcaswell** [comment]
Patch for this is in #2996

**Comment by mattcaswell** [comment]
It is interesting that we generate an HRR at all in nginx with Google Chrome. A default OpenSSL will not do this. It appears that nginx is disabling X25519 support. This will have a performance penalty for nginx and TLSv1.3 when talking to Chrome because Chrome only ever sends an X25519 key_share in its initial ClientHello. This forces a HelloRetryRequest - which obviously means an extra server round trip.

**Comment by Henrocker** [comment]
I don't know if this is why, but for the X25519 Curve to be used in a connection, The ECDHE string in the ciphersuite-string must be given, otherwise OpenSSL refuses to use that curve. On TLS13-* suites, this is not the case.

**Comment by kroeckx** [comment]
I'm not sure why this would surprise you. ECDHE are the cipher suites that use ECC key exchange. In TLS1.3 the key exchange is no longer part of the cipher suite.

**Comment by mattcaswell** [comment]
Should be fixed now.
