### ISSUE TITLE
Bus error in 30-test_evp.t (alignment issue on Solaris Sparc 32 Bit)

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#2985]
I get a bus erro when running 30-test_evp.t for OpenSSL 1.0.1e on Solaris Sparc 32 Bit.

gdb tells me:

Program terminated with signal 10, Bus error.
#0  CRYPTO_ocb128_aad (ctx=ctx@entry=0x3d238, aad=aad@entry=0x3d304 "", len=len@entry=16) at crypto/modes/ocb128.c:297
297             ocb_block16_xor(&ctx->offset_aad, aad_block, &tmp1);

and the stack is:

#0  CRYPTO_ocb128_aad (ctx=ctx@entry=0x3d238, aad=aad@entry=0x3d304 "", len=len@entry=16) at crypto/modes/ocb128.c:297
        lookup = <optimized out>
        aad_block = 0x3d304
        i = 1
        all_num_blocks = 1
        num_blocks = 1
        last_len = <optimized out>
        tmp1 = {a = {289644378304612875, 4891209677880525503}, c = "\004\005\006\a\b\t\n\vC▒\021I\214\005\202▒"}
        tmp2 = {a = {11092886392772803782, 11740981833994026278}, c = "\231▒▒f▒▒Ƣ▒X▒\211\207=&"}
#1  0xff2a0c90 in aes_ocb_cipher (ctx=0x2cbe8, out=0x0, in=0x3ca30 "", len=0) at crypto/evp/e_aes.c:2599
        remaining = 1
        buf = 0x3d304 ""
        buf_len = 0x3d318
        written_len = 0
        trailing_len = <optimized out>
        octx = 0x3d040
...

Looking at aad_block, the address 0x3d304 is not aligned correctly for the 64 bit data type use in ocb_block16_xor().
This goes back to buf in crypto/evp/e_aes.c, which in turn shares alignment with &octx->aad_buf. It loks like the layout of EVP_AES_OCB_CTX does not make sure that its member aad_buf is 8 byte aligned.

A short check of master suggests the same problem will happen there as well.

Regards,

Rainer

**Comment by dot-asm** [comment]
Please double-check #2994.

**Comment by dot-asm** [comment]
#2994 is committed since I had opportunity to confirm the problem and fix myself. Closing this too. Thanks for great report!
