### ISSUE TITLE
Crash in test during ossltest_destroy() for OpenSSL 1.1.0e on Linux x86_64.

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#2987]
I see crashes in several tests on SLES 10, RHEL 6 and RHEL 7, all 64 Bit, OpenSSL version 1.1.0e.

Example stack:

#0  0x0000003f6d60aaaa in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f6c4ebf3609 in CRYPTO_THREAD_write_lock (lock=<value optimized out>) at crypto/threads_pthread.c:66
No locals.
#2  0x00007f6c4eb818cc in ERR_unload_strings (lib=128, str=0x7f6c4f0bc860) at crypto/err/err.c:310
No locals.
#3  0x00007f6c4eebad8a in ERR_unload_OSSLTEST_strings (e=<value optimized out>) at engines/e_ossltest_err.c:73
No locals.
#4  ossltest_destroy (e=<value optimized out>) at engines/e_ossltest.c:340
No locals.
...

The lock passed to CRYPTO_THREAD_write_lock() (and to pthread_rwlock_wrlock()) is NULL when the crash happens.

Crashes are reproducible.

Example list of failing tests:

../test/recipes/70-test_sslcbcpadding.t  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslcertstatus.t  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslextension.t   (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslmessages.t    (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 5 tests but ran 1.
../test/recipes/70-test_sslrecords.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslsessiontick.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslskewith0p.t   (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslvertol.t      (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_tlsextms.t       (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output

I alsoreran the test with 1.1.0e plus two patches:

commit 0adaabf6cd9ef104468edd353d721cd2d7afca5e
Author: Benjamin Kaduk <bkaduk@akamai.com>
Date:   Tue Feb 28 16:09:53 2017 -0600

    Don't free in cleanup routine
    
    Cleanse instead, and free in the free routine.

and

commit bf9ee8a810971b6bd7eb5fe84ac97a61514607d8
Author: Richard Levitte <levitte@openssl.org>
Date:   Wed Mar 1 10:48:34 2017 +0100

    Don't use deprecated EVP_CIPHER_CTX_cleanup() internally
    
    Use EVP_CIPHER_CTX_reset() instead

but that didn't help,

I haven't tried with master.

Thanks!

Rainer

**Comment by richsalz** [comment]
No plan found message means something is wrong with your configuration.

**Comment by kroeckx** [comment]
Do you have perl-core insalled?

**Comment by rainerjung** [comment]
I should have said, the pasted test output snippet was from the summary. The full output is:

make depend && make _tests
make[1]: Entering directory `/shared/build/autobuild/workdirs/20170319_161405/bld/openssl110'
make[1]: Leaving directory `/shared/build/autobuild/workdirs/20170319_161405/bld/openssl110'
make[1]: Entering directory `/shared/build/autobuild/workdirs/20170319_161405/bld/openssl110'
( cd test; \
          SRCTOP=../. \
          BLDTOP=../. \
          PERL="/usr/bin/perl" \
          EXE_EXT= \
          OPENSSL_ENGINES=.././engines \
          OPENSSL_DEBUG_MEMORY=on \
            /usr/bin/perl .././test/run_tests.pl  )
../test/recipes/01-test_abort.t ............ ok
../test/recipes/01-test_sanity.t ........... ok
../test/recipes/01-test_symbol_presence.t .. ok
../test/recipes/02-test_ordinals.t ......... ok
../test/recipes/03-test_ui.t ............... ok
../test/recipes/05-test_bf.t ............... ok
../test/recipes/05-test_cast.t ............. ok
../test/recipes/05-test_des.t .............. ok
../test/recipes/05-test_hmac.t ............. ok
../test/recipes/05-test_idea.t ............. ok
../test/recipes/05-test_md2.t .............. skipped: md2 is not supported by this OpenSSL build
../test/recipes/05-test_md4.t .............. ok
../test/recipes/05-test_md5.t .............. ok
../test/recipes/05-test_mdc2.t ............. ok
../test/recipes/05-test_rand.t ............. ok
../test/recipes/05-test_rc2.t .............. ok
../test/recipes/05-test_rc4.t .............. ok
../test/recipes/05-test_rc5.t .............. skipped: rc5 is not supported by this OpenSSL build
../test/recipes/05-test_rmd.t .............. ok
../test/recipes/05-test_sha1.t ............. ok
../test/recipes/05-test_sha256.t ........... ok
../test/recipes/05-test_sha512.t ........... ok
../test/recipes/05-test_wp.t ............... ok
../test/recipes/10-test_bn.t ............... ok
../test/recipes/10-test_exp.t .............. ok
../test/recipes/15-test_dh.t ............... ok
../test/recipes/15-test_dsa.t .............. ok
../test/recipes/15-test_ec.t ............... ok
../test/recipes/15-test_ecdh.t ............. ok
../test/recipes/15-test_ecdsa.t ............ ok
../test/recipes/15-test_rsa.t .............. ok
../test/recipes/20-test_enc.t .............. ok
../test/recipes/20-test_passwd.t ........... ok
../test/recipes/25-test_crl.t .............. ok
../test/recipes/25-test_d2i.t .............. ok
../test/recipes/25-test_pkcs7.t ............ ok
../test/recipes/25-test_req.t .............. ok
../test/recipes/25-test_sid.t .............. ok
../test/recipes/25-test_verify.t ........... ok
../test/recipes/25-test_x509.t ............. ok
../test/recipes/30-test_afalg.t ............ skipped: test_afalg not supported for this build
../test/recipes/30-test_engine.t ........... ok
../test/recipes/30-test_evp.t .............. ok
../test/recipes/30-test_evp_extra.t ........ ok
../test/recipes/30-test_pbelu.t ............ ok
../test/recipes/40-test_rehash.t ........... ok
../test/recipes/70-test_asyncio.t .......... ok
../test/recipes/70-test_bad_dtls.t ......... ok
../test/recipes/70-test_clienthello.t ...... ok
../test/recipes/70-test_packet.t ........... ok
../test/recipes/70-test_sslcbcpadding.t ....
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_sslcertstatus.t ....
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_sslextension.t .....
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_sslmessages.t ......
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/5 subtests
../test/recipes/70-test_sslrecords.t .......
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_sslsessiontick.t ...
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_sslskewith0p.t .....
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_sslvertol.t ........
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_tlsextms.t .........
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
../test/recipes/70-test_verify_extra.t ..... ok
../test/recipes/80-test_ca.t ............... ok
../test/recipes/80-test_cipherlist.t ....... ok
../test/recipes/80-test_cms.t .............. ok
../test/recipes/80-test_ct.t ............... ok
../test/recipes/80-test_dane.t ............. ok
../test/recipes/80-test_dtls.t ............. ok
../test/recipes/80-test_dtlsv1listen.t ..... ok
../test/recipes/80-test_ocsp.t ............. ok
../test/recipes/80-test_pkcs12.t ........... ok
../test/recipes/80-test_ssl_new.t .......... ok
../test/recipes/80-test_ssl_old.t .......... ok
../test/recipes/80-test_ssl_test_ctx.t ..... ok
../test/recipes/80-test_sslcorrupt.t ....... ok
../test/recipes/80-test_tsa.t .............. ok
../test/recipes/80-test_x509aux.t .......... ok
../test/recipes/90-test_async.t ............ ok
../test/recipes/90-test_bio_enc.t .......... ok
../test/recipes/90-test_bioprint.t ......... ok
../test/recipes/90-test_constant_time.t .... ok
../test/recipes/90-test_fuzz.t ............. ok
../test/recipes/90-test_gmdiff.t ........... ok
../test/recipes/90-test_heartbeat.t ........ skipped: heartbeats is not supported by this OpenSSL build
../test/recipes/90-test_ige.t .............. ok
../test/recipes/90-test_memleak.t .......... ok
../test/recipes/90-test_p5_crpt2.t ......... ok
../test/recipes/90-test_secmem.t ........... ok
../test/recipes/90-test_shlibload.t ........ ok
../test/recipes/90-test_srp.t .............. ok
../test/recipes/90-test_sslapi.t ........... ok
../test/recipes/90-test_threads.t .......... ok
../test/recipes/90-test_v3name.t ........... ok

Test Summary Report
-------------------
../test/recipes/70-test_sslcbcpadding.t  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslcertstatus.t  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslextension.t   (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslmessages.t    (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 5 tests but ran 1.
../test/recipes/70-test_sslrecords.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslsessiontick.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslskewith0p.t   (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_sslvertol.t      (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
../test/recipes/70-test_tlsextms.t       (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=91, Tests=440, 214 wallclock secs ( 0.96 usr  2.31 sys + 83.38 cusr 87.02 csys = 173.67 CPU)
Result: FAIL
make[1]: Leaving directory `/shared/build/autobuild/workdirs/20170319_161405/bld/openssl110'


and stderr is:

exit code 139 from server process
exit code 139 from server process
exit code 139 from server process
exit code 139 from server process
# Looks like you planned 5 tests but ran 1.
# Looks like your test exited with 255 just after 1.
exit code 139 from server process
exit code 139 from server process
exit code 139 from server process
exit code 139 from server process
exit code 139 from server process
Failed 9/91 test programs. 0/440 subtests failed.
make[1]: *** [_tests] Error 255
make: *** [tests] Error 2

The core files really point to the tests, e.g. the "file" command on the 19 core files shows:

ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '../apps/openssl s_client -engine ossltest -connect localhost:4453'

and gdb shows as the complete stack:

#0  0x0000003f6d60aaaa in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00007fbd6eb33609 in CRYPTO_THREAD_write_lock (lock=<value optimized out>) at crypto/threads_pthread.c:66
#2  0x00007fbd6eac18cc in ERR_unload_strings (lib=128, str=0x7fbd6effc860) at crypto/err/err.c:310
#3  0x00007fbd6edfad8a in ERR_unload_OSSLTEST_strings (e=<value optimized out>) at engines/e_ossltest_err.c:73
#4  ossltest_destroy (e=<value optimized out>) at engines/e_ossltest.c:340
#5  0x00000000004ec8ee in engine_free_util (e=0xd690e0, locked=<value optimized out>) at crypto/engine/eng_lib.c:91
#6  0x00000000004ed09f in engine_list_remove (e=<value optimized out>) at crypto/engine/eng_list.c:131
#7  ENGINE_remove (e=<value optimized out>) at crypto/engine/eng_list.c:245
#8  0x00000000004ed185 in engine_list_cleanup () at crypto/engine/eng_list.c:44
#9  0x00000000004ec796 in engine_cleanup_cb_free (item=0xd4faa0) at crypto/engine/eng_lib.c:153
#10 0x0000000000554280 in OPENSSL_sk_pop_free (st=0xd4f760, func=0x4ec790 <engine_cleanup_cb_free>) at crypto/stack/stack.c:265
#11 0x00000000004ec75c in sk_ENGINE_CLEANUP_ITEM_pop_free () at crypto/engine/eng_int.h:62
#12 engine_cleanup_int () at crypto/engine/eng_lib.c:160
#13 0x000000000050cd2d in OPENSSL_cleanup () at crypto/init.c:480
#14 0x0000003f6d236072 in exit () from /lib64/libc.so.6
#15 0x0000000000425c95 in main (argc=<value optimized out>, argv=<value optimized out>) at apps/openssl.c:261

The platform here is rhel6, susing /usr/bin/perl which is 5.10.1, but the same problem happens also e.g. on RHEL7 with more recent perl. And yes, perl-core is installed (all in all about 63 perl packages).

If it wouldn't try to run the tests, I wonder why it should write core files from the ossltest engine ...

I can try to run the test under the debugger or add more debug output to find out, when/where the lock gets nulled.

I also started a new build using "HARNESS_VERBOSE=yes make test" so I might get more convincing output.

Thanks!

Rainer

**Comment by richsalz** [comment]
It doesn't matter that you posted an excerpt.  The "plan being wrong" implies that something's wrong.  For example, the wrong perl could configure the source wrong leading to crashes.

**Comment by levitte** [comment]
Something to be noted is that all the tests that failed are those using TLSProxy. If it was a configuration issue, we would probably see crashes elsewhere as well. 

The "plan being wrong" only implies that the test recipe exited before the planned number of "ok" / "not ok" didn't show up.

**Comment by levitte** [comment]
I'm looking forward to the verbose output of those tests.

**Comment by levitte** [comment]
Also, please show us your configuration line.

**Comment by bernd-edlinger** [comment]
to produce verbose test output: make test V=1

**Comment by dot-asm** [comment]
For reference, I can't reproduce this with RHEL 6.4. Vanilla `./config; make; make test`

**Comment by rainerjung** [comment]
My original crash was due to having the openssl binary linked statically against libcrypto (and libssl) but engines/ossltest was a shared object linked against libcrypto.so. So when running the test, there were two copies of symbols from libcrypto. The ones included in the openssl file and the ones in libcrypto.so loaded by the ossltest engine. Thus init/destroy was no longer consistent.

So I would like to close this issue. Other people who also saw similar symptoms should open s separate issue, if this root cause doesn't match their situation.

**Comment by siutung** [comment]
I had the same problem like that:
(./config;make;make test)
../test/recipes/01-test_abort.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
...................................................
  Parse errors: No plan found in TAP output

../test/recipes/90-test_v3name.t         (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=95, Tests=0,  2 wallclock secs ( 0.28 usr  0.24 sys +  1.76 cusr  0.42 csys =  2.70 CPU)
Result: FAIL
make[1]: *** [_tests] Error 95
make[1]: Leaving directory `/upgrade/openssl-1.1.0f'
make: *** [tests] Error 2



How I can upgrade the openssl(1.1.0f)?

**Comment by siutung** [comment]
I had the same problem like that:
(centos 6.5 x86_64;./config;make;make test)
../test/recipes/01-test_abort.t (Wstat: 65280 Tests: 0 Failed: 0)
Non-zero exit status: 255
...................................................
Parse errors: No plan found in TAP output

../test/recipes/90-test_v3name.t (Wstat: 65280 Tests: 0 Failed: 0)
Non-zero exit status: 255
Parse errors: No plan found in TAP output
Files=95, Tests=0, 2 wallclock secs ( 0.28 usr 0.24 sys + 1.76 cusr 0.42 csys = 2.70 CPU)
Result: FAIL
make[1]: *** [_tests] Error 95
make[1]: Leaving directory `/upgrade/openssl-1.1.0f'
make: *** [tests] Error 2

How I can upgrade the openssl(1.1.0f)?

**Comment by mixrat** [comment]
Had the exact problem as @rainerjung. I ran `make install` anyway; the install went fine and am now running 1.1.0g without issue.

**Comment by 1265578519** [comment]
yum -y install perl-core
