### ISSUE TITLE
openssl was built without bitcode. You must rebuild it with bitcode enabled

### ISSUE THREAD

**Issue by AdrianaPineda** [openssl/openssl#302]
I'm getting this warning: 
URGENT: all bitcode will be dropped because [path to openssl class] was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. Note: This will be an error in the future.

Can you please update the version to one that contains bitcode?

**Comment by richsalz** [comment]
We distribute source, not binaries...
