### ISSUE TITLE
Can't link openssl 1.0.2k on macOS 10.12.3

### ISSUE THREAD

**Issue by vladimirkrstic** [openssl/openssl#3024]
I get stuck with openssl 0.9.8zh preloaded with macOS. Tried almost every workaround I've found online(all are written for macOS 10.11.xx) and could not make it work.

With Homebrew I always get:
Warning: Refusing to link: openssl Linking keg-only openssl means you may end up linking against the insecure, deprecated system OpenSSL while using the headers from Homebrew’s openssl.

Can anyone help?

**Comment by dot-asm** [comment]
This sounds like environment-specific problem, and you are probably better off asking this question elsewhere, like <openssl-users> or homebrew lists. Keyword here is that we, team, are bound to work with problems we can reproduce ourselves, i.e. on more or less vanilla OS installation(s), and problems with openssl itself, build and tests. We naturally can give some advice about using OpenSSL utilities and API, but we stand no chance identifying problems that are environment-specific and/or not specific to our build and test.

However! This doesn't mean that somebody from public can't/won't step up *here* and provide some words of wisdom. But if nobody will, this issue will be simply closed within few days...

**Comment by vladimirkrstic** [comment]
Got it. Thanks.

**Comment by kencu** [comment]
The Macports version works all the way back to 10.4 Tiger PPC and on every system since then, so there should be some way to make the homebrew version catch up / be compatible. Here's a link to the current 1.02k portfile <https://github.com/macports/macports-ports/blob/52c27c394bfb0babf5c83b6784e766cd95a3fa6b/devel/openssl/Portfile>
