### ISSUE TITLE
Support Trusted CA Indication extension

### ISSUE THREAD

**Issue by matthauck** [openssl/openssl#3029]
Are there any plans to support the ["Trusted CA Indication"](https://tools.ietf.org/html/rfc6066#page-12) extension? 

Supposing:
- an application had its own PKI with multiple roots 
- clients know about subset `M` of `N` total roots and have certificates from each of them
- clients want to communicate with each other and mutually authenticate 

Client A need to be able to indicate to their peer which `M0` roots it knows about, so that Client B can choose which of its `M1` roots intersect and which certificate to use in its "server hello", such that Client A will trust its certificate chain.

As far as I know, this problem is solved by Trusted CA Indication, and is a compelling use case for implementing it in my opinion. 

Second, given this extension is not supported at present by OpenSSL is there a way with the current TLS support to accomplish this same goal? Thank you!

**Comment by richsalz** [comment]
There are no plans to implement it at this time.  A PR would help :)  How useful is this?  Do servers often have multiple trust chains to present to a client?

**Comment by matthauck** [comment]
Tried to illustrate the usefulness above. This is obviously not for an HTTPS web server scenario, but an application where different clients are communicating to each other with mutual TLS auth.

**Comment by richsalz** [comment]
Okay, I get it.  Can you do it with the client sending the CA DN's list?  It's a reasonable thing to want, but it's not on our radar now.

**Comment by matthauck** [comment]
Not sure what you mean by the client sending the CA "DN's list".

I suppose we can probably hack it together with encoding something into SNI for client->server as well as using `SSL_add_client_CA` for server->client. Not as clean as this TLS extension, but that would probably work.

**Comment by richsalz** [comment]
oops, it's the certificate_authorities list  and it's sent by the server.  sorry.

**Comment by matthauck** [comment]
Okay, well, you can feel free to close this issue I guess if supporting this isn't on your radar. Duly noted that PR's are welcome, and I may get to that one day, but probably not soon. :)

**Comment by paoloelefante** [comment]
Hello,
I was looking for the official support of Trusted CA Indication extension (rfc 6066) in openssl and I found this issue written two years ago.
From [OpenSSL changelog](https://www.openssl.org/news/changelog.txt) I understand that rfc 6066 is only partially supported.
Is there any plan to add this support the "Trusted CA Indication extension" in the future?

Thanks. 
BR, Paolo

**Comment by mattcaswell** [comment]
There are no plans to add support for this extension at the moment. However we would consider a PR that added it.

**Comment by nhorman** [comment]
closing, as it seems we still haven't gotten to this.  Extensions other than trusted_ca_keys were added several years ago.  If there is a desire to see trusted_ca_keys implemented, I would suggest the best approach would be to open a new issue that we can triage and consider.
