### ISSUE TITLE
Small typo/grammar issue in the license text

### ISSUE THREAD

**Issue by pombredanne** [openssl/openssl#303]
There is this weird sounding statement in the license:
`... as long as the following conditions are aheared to.`

See:  https://github.com/openssl/openssl/blob/9770924f9bd6de3d64041f4a725dea7c958721b7/LICENSE#L79 , found also in over 400 repo files containing the license text: https://github.com/openssl/openssl/search?utf8=%E2%9C%93&q=aheared and in about a million files in the wild web: https://www.google.com/search?q=%22conditions%20are%20aheared%22

In order to correct both spelling and grammar, I suggest the following change to the text:

`… as long as you adhere to the following conditions…`

If you prefer to keep the grammar and just correct the spelling you could simply make this change:

`… as long as the following conditions are adhered to…`

**Comment by mattcaswell** [comment]
There are other issues in the licence text too, e.g. search for "rouines". The original SSLeay licence text predates OpenSSL and is as we inherited it and as defined by Eric. It is not for us to change someone else's licence. Unfortunately these are known issues that we can't fix.
