### ISSUE TITLE
Problem compiling 1.1.0e on mingw

### ISSUE THREAD

**Issue by aryajur** [openssl/openssl#3030]
I am using mingw to build openssl. I use

    perl Configure mingw shared
    make

The result does not have libcrypto shared library. I checked the output and the only place I see an error is this:

    C:\MinGW\bin\ar.exe: creating libcrypto.a
    C:\MinGW\bin\ar.exe: creating libssl.a
    ./libcrypto.a(b_addr.o):b_addr.c:(.text+0xaa): undefined reference to `getnameinfo'
    ./libcrypto.a(b_addr.o):b_addr.c:(.text+0xb48): undefined reference to `getaddrinfo'
    ./libcrypto.a(b_addr.o):b_addr.c:(.text+0x819): undefined reference to `freeaddrinfo'
    ./libcrypto.a(init.o):init.c:(.text+0x1d2): undefined reference to `GetModuleHandleEx'
    ./libcrypto.a(init.o):init.c:(.text+0x8e4): undefined reference to `GetModuleHandleEx'
    ./libcrypto.a(o_str.o):o_str.c:(.text+0x5db): undefined reference to `strerror_r'
    collect2.exe: error: ld returned 1 exit status
    make[2]: *** [link_shlib.mingw] Error 1
    make[1]: *** [libcrypto.dll.a] Error 2

I have tried several things with whatever I could find on the internet. Like doing make distclean before Configure or to configure using no-async option. Nothing seems to work. 

Any hints or guidance will be really helpful to get this to work. Also after the configure step I had to manually go into the make file and set the PERL variable from C:\MinGW\msys\1.0\bin\perl.exe to C:/MinGW/msys/1.0/bin/perl.exe otherwise make would not be able to find perl in the msys shell.

**Comment by dot-asm** [comment]
We probably have to proclaim that minimum requirement for 1.1.x is MSYS2. I mean report sounds like your environment is too old. And there were other problems reported with older MSYS. But the last part about replacing backslashes with slashes sounds utterly strange. I even have hard time imagining how did backslashes got there... To summarize, switch to MSYS2, and run perl and make from MinGW prompt. That's what is actually supported.

**Comment by aryajur** [comment]
Thank you for the response. I switched to msys2 and after the basic installation installed perl, gcc and make.  After Configure ran make and it got an error:

crypto/dso/dso_win32.c:96:5: error: unknown type name 'HINSTANCE'
     HINSTANCE h = NULL, *p = NULL;
     ^~~~~~~~~

Maybe I am missing something in the msys installation. What should I install more to make it work?

**Comment by dot-asm** [comment]
You have to install mingw compilers, not just "gcc" and even start appropriate MinGW command window... For reference, "just gcc" is compiler that targets MSYS itself. MinGW compiler generates binaries that can be executed on any Windows system, while MSYS compiler generates binaries that can be executed only in MSYS environment.

**Comment by aryajur** [comment]
I did do this:

    pacman -S base-devel msys2-devel mingw-w64-i686-toolchain

Would this install them? I get the same error after this. Which package do I need to install?

**Comment by aryajur** [comment]
It worked after I used the the MinGW command window. Thank you very much.
