### ISSUE TITLE
The enable-aria option has disappeared from travis.yml

### ISSUE THREAD

**Issue by pauli-oracle** [openssl/openssl#3038]
The additional option to build and test the aria cipher (see #2337) has disappeared.

**Comment by dot-asm** [comment]
Would you prefer to create merge request or should I? If former, then pick cases that also enable-rc5 and enable-md2.

**Comment by pauli-oracle** [comment]
PR done.

I was more concerned about raising visibility of the procedural failure that omitted the option.
