### ISSUE TITLE
Support for ChaCha20-Poly1305

### ISSUE THREAD

**Issue by MichalStaruch** [openssl/openssl#304]
ChaCha20-Poly1305 is modern, high performance cipher working in AEAD mode. It was standardized recently as [RFC 7539](https://tools.ietf.org/html/rfc7539).

I've noticed work on this already started (or maybe even finished?) in OpenSSL forks, but taking into account that [current draft of TLSv1.3](https://tlswg.github.io/tls13-spec/) requires using AEAD ciphers and relying solely on single AES-GCM might be not the best idea I think it's a good moment to include ChaCha20-Poly1305 in main OpenSSL repository.

**Comment by mattcaswell** [comment]
Andy is already working on it.

**Comment by MichalStaruch** [comment]
@mattcaswell Nice to hear :+1:. I haven't found it on issues list, so I thought it might be worth adding - people might be interested if it's included in OpenSSL plans or when it might be available.

**Comment by mattcaswell** [comment]
I hope it should be available in OpenSSL 1.1.0 (no release date set for that yet).

**Comment by HLFH** [comment]
@mattcaswell Any news ? :)

**Comment by mattcaswell** [comment]
Andy has reference implementations for both ChaCha20 and Poly1305. He is probably better placed to give an update. Ping @dot-asm

**Comment by shouze** [comment]
There's a patch from cloudflare available here:
https://github.com/cloudflare/sslconfig/blob/master/patches/openssl__chacha20_poly1305_cf_latest_git.patch

Wy don't integrate it into openssl ASAP?

**Comment by richsalz** [comment]
We don't add features to releases, just fixes. Also, the cipher has changed from the CF patches. We'll be putting the official version into 1.1, most likely.

**Comment by mattcaswell** [comment]
This just hit master and therefore will be in 1.1.0. Closing this.

**Comment by zx2c4** [comment]
Is there a reason why the only ASM implementation for this is a poly1305 implementation for Sparc, but not the avx and avx2 implementations for both chacha20 and poly1305 written by Intel that was found in the cloudflare patch?

**Comment by richsalz** [comment]
Two reasons.  The CF code implements the earlier version.  And we have folks working on the other assemblers.  Will be released in 1.1.

**Comment by wmark** [comment]
The way OpenSSL authors use versioning systems makes it very hard to track the sources of changes, or maintainig patchfix branches.

I've identified this changeset to be introducing the cipher:
bd989745b7a4796dceff89d93b6b7ac1561c6227

**Comment by zx2c4** [comment]
I thought I saw that recent Intel AVX chacha implementations switched to using the 12byte nonce, actually. Were there other "earlier versions" than the 12byte/8byte nonce change?

**Comment by richsalz** [comment]
The AEAD construct was changed from the initial drafts (and what is used in QUIC) to the final RFC version, based on feedback from the CFRG as I recall.  I don't remember details.
