### ISSUE TITLE
Fix tag mirroring

### ISSUE THREAD

**Issue by rhuijben** [openssl/openssl#305]
Somehow tags aren't properly mirrored here. On security updates the relevant commits are mirrored from git://git.openssl.org/openssl within minutes, but it appears mirroring the tags is still a manual process. Can somebody please fix the mirroring script?

**Comment by levitte** [comment]
That's *very* odd.  We do a mirroring push (`remote.github.mirror` is `true`), so it should push all kinds of refs/, including tags...

**Comment by rhuijben** [comment]
Thanks for fixing for yesterdays release... But now there are new releases (and no tags yet)

**Comment by bbolli** [comment]
I've seen this too with the 1.0.2 releases. The tags appear hours later than the commits. Maybe it's a Github problem?

**Comment by richsalz** [comment]
not an openssl issue.

**Comment by kaduk** [comment]
If this is not an openssl issue, what sort of issue is it?  Where would it more properly be reported?

**Comment by richsalz** [comment]
We’re going the right thing; we mirror and push tags.  Welcome to the modern internet.  What do you think openssl can/should do?

**Comment by levitte** [comment]
@richsalz was a bit hasty in his comments.  We have had issues with tags not propagating from our repo to github et al.  I hope we've cleared them up now, though.

**Comment by richsalz** [comment]
Hasty, moi?  Yes, we had some issues, but we've done all we can do so I closed this.
