### ISSUE TITLE
The SRP API has lots of problems

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#3055]
These functions should probably not be in the public API:

````
SSL_CTX_SRP_CTX_init()
SSL_CTX_SRP_CTX_free()
SSL_SRP_CTX_init()
SSL_SRP_CTX_free()
````

AFAICT  `SSL_CTX_SRP_CTX_init()` and `SSL_CTX_SRP_CTX_free()` get called automatically whenever you call `SSL_CTX_new()` and `SSL_CTX_free()` respectively. Similarly with the `SSL_SRP_CTX_*()` functions with respect to `SSL_new()` and `SSL_free()`. I can't think of a good reason why you would ever want to "reinitialise" the SRP_CTX, or free it early.

The question is what should we do about it? We can't remove them because that would be an ABI break. Just make the public functions noops? Should we deprecate them? Can we even deprecate things between 1.1.0 and 1.1.1??

**Comment by richsalz** [comment]
make them no-ops and return an error.  it's what I did for the RSA init in the #2244 PR.  Hint hint.

**Comment by mattcaswell** [comment]
I think this needs to go to the 1.2.0 milestone.

**Comment by mattcaswell** [comment]
`SRP_Calc_A_param` is another function that looks like it is supposed to be internal, but isn't. Not only that but it's actually a libssl function in spite of the SRP prefix.

**Comment by mattcaswell** [comment]
*barf* everytime I look at the SRP API I feel ill.

Here are some more problems I've identified with it:

- The API provides a function for parsing a verifier file (SRP_VBASE_init()). As far as I can tell this is an entirely OpenSSL proprietary format. However there is no function for *creating* such a verifier file. That logic is entirely contained within the srp command line app.

- The API requires you to have an intimate knowledge of the SRP RFC to be able to use it. It provides functions for generating various values such as "u" and "x". But these seem entirely temporary intermediate values that you just need to calculate and then pass back to subsequent function calls. All of this should be wrapped up and hidden in some SRP_CTX object

- There *is* no SRP_CTX. All the values needed are passed around individually - and there are quite a few of them. This makes the whole thing unnecessarily complex.

**Comment by mattcaswell** [comment]
Another one:

- The "seed_key" value is supposed to contain random data - but it must also be NUL terminated, so the "random" data cannot contain NUL bytes.

**Comment by mattcaswell** [comment]
- There is no constructor function for creating a new SRP_user_pwd object. You can only get one by querying an existing SRP_VBASE, or by manually creating an instance of the (transparent) structure and manually filling in all of the fields.

- There is no function for inserting a new user into an SRP_VBASE. You have to create the user manually and then fiddle around with the right field in the transparent SRP_VBASE structure in order to push the new user onto the stack.

**Comment by mattcaswell** [comment]
The SRP verifier file format has support for "I" entries which enable you go configure your own "N" and "g" values. However there is no support anywhere for *creating* such verifier file entries, so it is likely that this code isn't actually used by anyone.

**Comment by mattcaswell** [comment]
The SRP code uses its own special variant of base64. This seems to have been inherited from libsrp. At some point there seems to have been an attempt to support reading the same config files as libsrp. At least the comment in front of SRP_VBASE_init() suggests that the file format is the same as the one from libsrp. However the format that is actually implemented is different - so we don't actually support libsrp verifier files. Therefore the use of the non-standard base64 seems fairly pointless and unfortunate. However we probably need to continue to support it for backwards compat reasons. See [this comment](https://github.com/openssl/openssl/pull/7522#discussion_r229991827).

**Comment by richsalz** [comment]
Perhaps close this as background info for #14167 ?

**Comment by t8m** [comment]
Well #14167 is rather about the low level SRP_xxx API. Where this one is about the SRP related calls in the libssl.

**Comment by t8m** [comment]
But yeah, this could be also closed on the basis that the API is now deprecated and #14167 deals with the possible future non-deprecated implementation.

**Comment by t8m** [comment]
Closing this then.
