### ISSUE TITLE
Macro arguments should be in parentheses

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#3063]
I think this is a more general problem,
it starts with the following example in  https://www.openssl.org/policies/codingstyle.html:
```
    #define macrofun(a, b, c)   \
        do {                    \
            if (a == 5)         \
                do_this(b, c);  \
        } while (0)
```

which is more or less the way how not to do it, because at least if (a == 5)
should always be written as if ((a) == 5).

And a grep reveals many macros with un-parenthesed macro arguments:
```
crypto/bio/b_print.c:#define char_to_int(p) (p - '0')
crypto/bio/b_print.c:#define OSSL_MAX(p,q) ((p >= q) ? p : q)
include/openssl/ssl.h:# define SSL_set_app_data(s,arg)         (SSL_set_ex_data(s,0,(char *)arg))
include/openssl/ssl.h:# define SSL_SESSION_set_app_data(s,a)   (SSL_SESSION_set_ex_data(s,0,(char *)a))
include/openssl/ssl.h:# define SSL_CTX_set_app_data(ctx,arg)   (SSL_CTX_set_ex_data(ctx,0,(char *)arg))
```

(this is only an incomplete list)

**Comment by dot-asm** [comment]
Well, I wouldn't say that presented example from the coding style guide should be blamed for this. After all, one can argue that the example has different focus, namely how to write macros that can't be implemented as expressions. Secondly I wouldn't say that our guide is meant to describe every aspect, mostly project-specific "quirks". For example it doesn't say "don't you use parenthesis in macros", does it? Building up on the presented example, guide doesn't say that preferred way to implement a macro is actually as expression. It's just so well-recognized thing that it's not specific to this project...

However! Above runt is *not* an excuse for missing parenthesis. I don't dispute the fact that they *can* make macros more robust. At the same time they don't actually *have to* be there, unless actually required. It's kind of a grey area... But I'd definitely subscribe to suggestion that there ought to be parenthesis in public headers. As for private... it varies... Would you like to start with public headers?

**Comment by bernd-edlinger** [comment]
Yes, I can add some parentheses on the public headers.
