### ISSUE TITLE
Cancel OpenSSL RSA key generation via command line

### ISSUE THREAD

**Issue by mbigras** [openssl/openssl#3076]
When generating an [RSA key](https://en.wikipedia.org/wiki/RSA_(cryptosystem)) with the [OpenSSL](https://en.wikipedia.org/wiki/OpenSSL) cli you are prompted to enter your passphrase.

With most command-line interfaces pressing `C-d` or `C-c` will exit the process; however, with openssl it seems like it's impossible to exit the program once you've started the key generation process.

Shown below is a session where I'm trying `C-c` and `C-d`, only after entering `foobar` twice do I exit:

    $ openssl genrsa -aes128 -out fd.key 2048
    Generating RSA private key, 2048 bit long modulus
    .........+++
    .................................................+++
    e is 65537 (0x10001)
    Enter pass phrase for fd.key:
    73496:error:28069065:lib(40):UI_set_result:result too small:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/crypto/ui/ui_lib.c:850:You must type in 4 to 1023 characters
    Enter pass phrase for fd.key:
    73496:error:28069065:lib(40):UI_set_result:result too small:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/crypto/ui/ui_lib.c:850:You must type in 4 to 1023 characters
    Enter pass phrase for fd.key:
    Enter pass phrase for fd.key:
    Enter pass phrase for fd.key:
    Enter pass phrase for fd.key:
    Enter pass phrase for fd.key:
    Enter pass phrase for fd.key:
    Verifying - Enter pass phrase for fd.key:

* How do I exit the `genrsa` openssl command?

See this [security stackexchange question](https://security.stackexchange.com/questions/155237/cancel-openssl-rsa-key-generation-via-command-line) for more details

**Comment by richsalz** [comment]
Use SIGQUIT (control-backslash) instead of SIGINT (control-c)?

On the other hand, typing control-c works for me just fine.

**Comment by mbigras** [comment]
I'm running `macOS 10.12.1` with `OpenSSL 0.9.8zh 14 Jan 2016`

It works if quit immediately but if you try to quit after pressing your first enter `openssl` doesn't seem to respond. Attached is a gif.


![](http://g.recordit.co/9eholvLfiC.gif)

**Comment by richsalz** [comment]
okay, that's a bug in that very old and unsupported openssl version.  tty reading has had a number of fixes.

**Comment by mbigras** [comment]
Also confirmed with `OpenSSL 1.0.1 14 Mar 2012`. Which version was it fixed in?

**Comment by richsalz** [comment]
I don't know.  Maybe read the CHANGES or git log files?  But 1.0.1 from *five years ago* is also buggy.
