### ISSUE TITLE
Decrypt should automatically try multiple Message Digest formats

### ISSUE THREAD

**Issue by Mister-Meeseeks** [openssl/openssl#3078]
Between 1.0 and 1.1, there seems to be a fair bit of confusion regarding the change from ```md5``` to ```sha1``` as the default. I'm sure, I'm not the only one who panicked after not being able to initially decrypt something in one version that I encrypted in the other.

I propose that the logic should change on a decrypt command. If the initial decrypt fails, then the program should try again with the same password/key using the other major Message Digest formats. For example the output would look like that:

    $ openssl aes-256-cbc -d -a -in mySecrets.aes25 -out secrets.txt -k superSecretPassword
    bad decrypt (using sha1 message digest)
    warning: decrypt successful, but used alternative message digest md5

 I'd still raise a warning to let the user know that the first format didn't work, and possibly add a command flag to disable this behavior. But in the vast majority of use cases the cost of additional run-time is much lower than a failed decrypt.

**Comment by pauli-oracle** [comment]
How would this proposal deal with data being piped through the decryption command?

**Comment by richsalz** [comment]
this would work for files, but not pipes, as pauli says.  closing this.  you can write a wrapper script that calls it twice for files, e.g.

**Comment by Mister-Meeseeks** [comment]
That's an excellent point about pipes. However I'd still contend that this behavior should be implemented specifically for regular files. If we're processing stdin (or ```fstat``` indicates a named pipes, devices, etc.), then fall back to the old behavior. Decrypt once with the the message digest. Otherwise with files, then try alternative message digests on failure.

This change wouldn't break any existing behavior. Pipes would still do exactly the same thing as they do now. Files, which I'm guessing constitute 90%+ of use cases, would only be improved. I don't see any downside.

(Btw, I probably should have made this as a pull request. I'm happy to implement, if main contributors approve).

**Comment by richsalz** [comment]
Discuss on the openssl-dev mailing list, see what the community thinks

**Comment by pauli-oracle** [comment]
Pipes can be handled -- do both checksums in parallel.  Probably not a great idea by default though.
