### ISSUE TITLE
Is there rfc6979 support?

### ISSUE THREAD

**Issue by Koshub** [openssl/openssl#308]
Is there any version with http://tools.ietf.org/html/rfc6979 support to make deterministic ECDSA signature?

**Comment by richsalz** [comment]
it's in master, planned for the next release.

**Comment by Koshub** [comment]
@richsalz  Can you please tell what functions are implement rfc6979 ?

**Comment by richsalz** [comment]
Still under development; not yet submitted.

**Comment by mvayngrib** [comment]
@richsalz has this been submitted (and if yes, which version)? Thanks!

**Comment by richsalz** [comment]
I’m not sure.  Ask on the mailing list; https://mta.openssl.org for list info.
