### ISSUE TITLE
s_client does display server key key for TLSv1.3

### ISSUE THREAD

**Issue by dcooper16** [openssl/openssl#3081]
When I run s_client with the "master" branch, and the connection is with TLSv1.3, the "Server Temp Key" line is missing, but it appears if the connection is with TLSv1.2 or below. I don't understand the code well enough to submit a pull request, but I was able to get it to work with the following change:
```
--- ssl/s3_lib.c.save   2017-03-29 15:38:03.243026386 -0400
+++ ssl/s3_lib.c        2017-03-29 16:34:01.265884952 -0400
@@ -3272,12 +3272,18 @@
 
     case SSL_CTRL_GET_SERVER_TMP_KEY:
 #if !defined(OPENSSL_NO_DH) || !defined(OPENSSL_NO_EC)
-        if (s->server || s->session == NULL || s->s3->peer_tmp == NULL) {
+        if (s->server || s->session == NULL) {
             return 0;
-        } else {
+        } else if (s->s3->peer_tmp != NULL) {
             EVP_PKEY_up_ref(s->s3->peer_tmp);
             *(EVP_PKEY **)parg = s->s3->peer_tmp;
             return 1;
+        } else if (s->s3->tmp.pkey != NULL) {
+            EVP_PKEY_up_ref(s->s3->tmp.pkey);
+            *(EVP_PKEY **)parg = s->s3->tmp.pkey;
+            return 1;
+        } else {
+            return 0;
         }
 #else
         return 0;
```

**Comment by mattcaswell** [comment]
The patch above actually returns the client's temp key for TLSv1.3. For s_client this makes no difference because it only prints summary information which will be the same for both the client's and the server's temp key. However other caller's of the SSL_get_server_tmp_key() macro will get the wrong value.

My fix in #3114.
