### ISSUE TITLE
Support for key exchange using Curve25519 and Curve448

### ISSUE THREAD

**Issue by MichalStaruch** [openssl/openssl#309]
Curve25519 is described in [Curve25519 for ephemeral key exchange in Transport Layer Security (TLS)](https://tools.ietf.org/html/draft-ietf-tls-curve25519-00) IETF draft. It's designed with speed, simplicity and security in mind, and seems to be very nice alternative to NIST curves like secp256r1 or secp384r1 - especially when we think about [rigidity](http://safecurves.cr.yp.to/rigid.html) and susceptibility to secret attacks.

It would be very nice to have it supported in OpenSSL to speed up adoption of ECDHE key exchange (kEECDH), especially among those people who don't trust curves coming from NIST.

**Comment by richsalz** [comment]
it's being worked on for the next release.

**Comment by MichalStaruch** [comment]
@richsalz Forgive me my strictness, but usually "being worked" mean feature is not complete, so... why closing the issue? Can I checkout the sources, compile and run it with working Curve25519?

**Comment by richsalz** [comment]
I thought it was a question and encouragement to do it.  It's planned for the next release.  You want to re-open?  Feel free.

**Comment by MichalStaruch** [comment]
@richsalz I though it would be have this issue hanging as feature request to have it clearly visible when this feature will be publicly available (merged to master in main repo).

About the re-opening: GitHub blocks this option for non-collabolators when issue was closed by collabolator.

**Comment by MichalStaruch** [comment]
[Latest draft](https://tools.ietf.org/html/draft-ietf-tls-curve25519-01) also added Curve448. It's pretty strong, meets all the [SafeCurves](http://safecurves.cr.yp.to/) requirements, and highly efficient implementations should be possible on both 32-bit and 64-bit architectures. More details (including benchmarks vs NIST curves on x86-64 and ARM) are available in [this publication](https://eprint.iacr.org/2015/625) from Mike Hamburg.

**Comment by ChALkeR** [comment]
Guess https://github.com/nodejs/node/issues/1495 should be linked here to get a status badge there =).

**Comment by nick599** [comment]
@richsalz Has this development been done and released? / If not, when is the release planned for it?

**Comment by richsalz** [comment]
In progress planned for 1.1

**Comment by asthaaggarwal** [comment]
@richsalz: is it released?curve25519 support is avaialble now??

**Comment by mattcaswell** [comment]
It's in the latest beta for OpenSSL 1.1.0

**Comment by richsalz** [comment]
Yes, it is in the master branch.  It will be released in 1.1

**Comment by asthaaggarwal** [comment]
ok.
I downloaded this package openssl-1.1.0-pre4.tar.gz
It should be available in this package right??

**Comment by mattcaswell** [comment]
Yes

**Comment by asthaaggarwal** [comment]
Thanks for d updates.
Where can i find the example for curve25519?how to use it?

**Comment by richsalz** [comment]
You could look ☺

But yes.

**Comment by richsalz** [comment]
Please ask your questions on openssl-users, https://mta.openssl.org for list information.

**Comment by JLHwung** [comment]
@asthaaggarwal
`openssl genpkey -algorithm EC -out some_x25519.key -pkeyopt ec_paramgen_curve:X25519 -pkeyopt ec_param_enc:named_curve`

**Comment by asthaaggarwal** [comment]
Thanks JLHwung for ur response.

@richsalz : I would like to know if ECDHE-ECDSA-CHACHA20-POLY1305 is compatible to TLS 1.2
As per my project requirement i m suppose to exclude less than TLS1.2 so during openssl building time when excluding, its removing ECDHE-ECDSA-CHACHA20-POLY1305 cipher support also.

**Comment by richsalz** [comment]
I suggest you do a search through RFC's for TLS and CHACHA for your project and find out :)

**Comment by asthaaggarwal** [comment]
ok..
One more issue i m facing in cross compiling of openssl-1.1.0-pre4 build. I am not able to cross compile it for arm. Before this build all other builds are working. Can you please confirm if there is any issue in cross compiling the code.

export INSTALLDIR=build-output
export PATH=$INSTALLDIR/bin:$PATH
export TARGETMACH=arm-none-linux-gnueabi
export BUILDMACH=i686-pc-linux-gnu
export CROSS=arm-none-linux-gnueabi
export CC=${CROSS}-gcc
export LD=${CROSS}-ld
export AS=${CROSS}-as
export AR=${CROSS}-ar
export PATH=$PATH:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin

./Configure -DOPENSSL_NO_HEARTBEATS --openssldir=/home/user/priti/workbench/openssl/src/openssl-1.1.0-pre4/build-output shared os/compiler:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc

Configuring OpenSSL version 1.1.0-pre4 (0x0x10100004L)
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG (skip dir)
    no-crypto-mdebug-backtrace [forced]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE (skip dir)
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-egd          [default]  OPENSSL_NO_EGD (skip dir)
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-ssl3         [default]  OPENSSL_NO_SSL3 (skip dir)
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS (skip dir)
    no-zlib         [default]
    no-zlib-dynamic [default]
Configuring for os/compiler:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc
**Warning! target os/compiler:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc doesn't exist!
**

**Comment by stas730** [comment]
I think the E-521 curve need to be included to OpenSSL. It is the best curve from SafeCurves.

**Comment by richsalz** [comment]
To repeat:  issues are not the place for discussions or general questions and answers.  Join the mailing lists; see https://mta.openssl.org

**Comment by richsalz** [comment]
x25519 is in 1.1
closing this issue.
please open a separate issue for goldilocks/448 support and what you want (note that the IETF CFRG isn't done with 448 signatures yet.)
