### ISSUE TITLE
RSA fails in Apache using OpenSSL in FIPS mode.

### ISSUE THREAD

**Issue by hitched97** [openssl/openssl#3093]
I've run into a problem on a FreeBSD system with OpenSSL and Apache mod_ssl.  I'm unsure who to say has a bug, I suspect it's a little of both OpenSSL and Apache.

FreeBSD (and OpenBSD) provide a crypto accelerator device, /dev/crypto, for which OpenSSL builds a built-in engine.

Apache's mod_ssl calls ENGINE_load_builtin_engines() as part of its startup, resulting in that engine being active.  That leads to this bit of code from ENGINE_load_cryptodev() being called:

```
    if (ENGINE_set_RSA(engine, &cryptodev_rsa)) {
        const RSA_METHOD *rsa_meth = RSA_PKCS1_SSLeay();

        cryptodev_rsa.bn_mod_exp = rsa_meth->bn_mod_exp;
        cryptodev_rsa.rsa_mod_exp = rsa_meth->rsa_mod_exp;
        cryptodev_rsa.rsa_pub_enc = rsa_meth->rsa_pub_enc;
        cryptodev_rsa.rsa_pub_dec = rsa_meth->rsa_pub_dec;
        cryptodev_rsa.rsa_priv_enc = rsa_meth->rsa_priv_enc;
        cryptodev_rsa.rsa_priv_dec = rsa_meth->rsa_priv_dec;
```

Which is fine, *unless* you call FIPS_mode_set(1), which results in those RSA operations running this code from crypto/rsa/rsa_pmeth.c:

```
#ifdef OPENSSL_FIPS
    ret = pkey_fips_check_ctx(ctx);
    if (ret < 0) {
        RSAerr(RSA_F_PKEY_RSA_SIGN, RSA_R_OPERATION_NOT_ALLOWED_IN_FIPS_MODE);
        return -1;
    }
#endif
```

The upshot is that the server rejects all connections if it is configured with a certificate signed with RSA, even if the certificate meets FIPS requirements.  The issue is not just an Apache one, s_server exhibits the same behavior.

Does anyone know why the cryptodev engine diverts RSA (and DH and DSA) operations to the internal code?  And is there a reliable way to get it to use the FIPS module when that is appropriate?

**Comment by hitched97** [comment]
Oh, I should add, this is with OpenSSL 1.0.2k.  Apache is version 2.4.25 if that matters.

**Comment by richsalz** [comment]
You cannot use the cryptodev engine with FIPS because the kernel code wasn't part of the fips audit.

**Comment by hitched97** [comment]
OpenSSL's `s_server` command, and I suspect `s_client` as well, are doing exactly that.  openssl,c calls `FIPS_mode_set()` if that was requested, and then s_server.c calls `ENGINE_load_builtin_engines()`.

I understand that the built-in engines are not FIPS certified.  Is it unreasonable for FIPS mode to prevent them from being loaded, or to unload them if that already are?  Although, that would prevent hardware acceleration in the cases where /dev/crypto actually passes operations to certified hardware.  Which is definitely not the case here, as the cryptodev engine is explicitly claiming RSA, DH, and DSA operations, but using OpenSSL's own code to complete them.  I see that as defective behavior.

**Comment by richsalz** [comment]
Does configure with no-engine get the right behavior?

**Comment by hitched97** [comment]
ENGINE_load_builtin_engines() and ENGINE_load_cryptodev() still exist in libcrypto.so, but a quick test of s_server looks like it is working correctly with no-engine.

**Comment by hitched97** [comment]
trying...

**Comment by hitched97** [comment]
Adding no-engine does prevent s_server from calling `ENGINE_load_builtin_engines()`.  'ENGINE_load_builtin_engines()' still exists in the library though, and I don't know what mod_ssl will do...
