### ISSUE TITLE
can't find code path of EVP_aes_256_gcm() function.

### ISSUE THREAD

**Issue by gohyeonjoo** [openssl/openssl#3109]
Hello.
I am checking dvp demo(Aesgcm.c).
I can't find source code of EVP_aes_256_gcm() function.
Does anybody know the location of the EVP_aes_256_gcm() function?

**Comment by mattcaswell** [comment]
It is defined via the `BLOCK_CIPHER_custom()` macro in crypto/evp/e_aes.c:

````
    BLOCK_CIPHER_custom(NID_aes, 256, 1, 12, gcm, GCM,
                    EVP_CIPH_FLAG_AEAD_CIPHER | CUSTOM_FLAGS)
````
