### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by danielkaneider** [openssl/openssl#311]
Hi, 
compiling OpenSSH is not that easy, especially on Windows and on 64bit. CMake would improve that situation, as it is nowadays used by a lot of open source projects. There seem to be some non-official repos or some scripts around, which provide some CMake scripts, but nothing official till now. 
Thanks

**Comment by richsalz** [comment]
We're looking at revamping the build system, and tracking that in other tickets/issues, but cmake isn't likely.
