### ISSUE TITLE
When Subject and Authority Key Identefier don't match, certificate path validation fails

### ISSUE THREAD

**Issue by dtillemans** [openssl/openssl#3110]
Dear,

In the source-file x509_vfy.c, I found you block the certificate path validation process when the Authority Key Identifier (AKI) of the certificate doesn't correspond to the subject key identifier (SKI) of the issuing certificate.
In our old CA implementation we have an AKI and SKI, which was set before any standards existed. When another CA has cross-certified the old CA, it set the SKI to hash of the public key. Which will lead to certificate path validation with problem with openssl.

Now verifying with the standard RFC5280, Applications are not required to verify that AKI and SKI match. 

[[[
4.2.1.2.  Subject Key Identifier

   The subject key identifier extension provides a means of identifying
   certificates that contain a particular public key.

   To facilitate certification path construction, this extension MUST
   appear in all conforming CA certificates, that is, all certificates
   including the basic constraints extension (Section 4.2.1.9) where the
   value of cA is TRUE.  In conforming CA certificates, the value of the
   subject key identifier MUST be the value placed in the key identifier
   field of the authority key identifier extension (Section 4.2.1.1) of
   certificates issued by the subject of this certificate.  Applications
   are not required to verify that key identifiers match when performing
   certification path validation.
]]]

Verifying RFC-4158:
[[[
3.5.12.  Matching Key Identifiers (KIDs)

   May be used to eliminate certificates:  No
   Number of possible values:  Three
   Components required:  None

   Forward Method:  Certificates whose subject key identifier (SKID)
   matches the current certificate's authority key identifier (AKID)
   have highest priority.  Certificates without a SKID have medium
   priority.  Certificates whose SKID does not match the current
   certificate's AKID (if both are present) have zero priority.  If the
   current certificate expresses the issuer name and serial number in
   the AKID, certificates that match both these identifiers have highest
   priority.  Certificates that match only the issuer name in the AKID
   have medium priority.

   Reverse Method:  Certificates whose AKID matches the current
   certificate's SKID have highest priority.  Certificates without an
   AKID have medium priority.  Certificates whose AKID does not match
   the current certificate's SKID (if both are present) have zero
   priority.  If the certificate expresses the issuer name and serial
   number in the AKID, certificates that match both these identifiers in
   the current certificate have highest priority.  Certificates that
   match only the issuer name in the AKID have medium priority.

   Justification:  Key Identifier (KID) matching is a very useful
   mechanism for guiding path building (that is their purpose in the
   certificate) and should therefore be assigned a heavy weight.

   NOTE:  Although required to be present by [RFC3280], it is extremely
   important that KIDs be used only as sorting criteria or as hints
   during certification path building.  KIDs are not required to match
   during certification path validation and cannot be used to eliminate
   certificates.  This is of critical importance for interoperating
   across domains and multi-vendor implementations where the KIDs may
   not be calculated in the same fashion.
]]]

So giving errors for certificate path validation is too strict, when the AKI and SKI don't match. Can we skip the verification?

Greetings,
David

**Comment by euter** [comment]
you can set a callback function, which change default validation process, in X509_STORE_CTX structure.

**Comment by mattcaswell** [comment]
Does not appear to be 1.1.1 specific so removing that milestone.

**Comment by t8m** [comment]
I do not think we are going to change this behavior. This is candidate for closing.

**Comment by t8m** [comment]
Closing now.
