### ISSUE TITLE
problem using openssl static library

### ISSUE THREAD

**Issue by tanhuazh** [openssl/openssl#3129]
I am using 1.1.0b on Ubuntu linux.

I did the following:
./config no-shared
make

Does this allow me to use openssl static without any shared libraries?

I linked against libcrypto.a. I still got the problem when running the application:
error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

What should I do?

Thanks for help.

**Comment by levitte** [comment]
Please show us how you linked against libcrypto.a

**Comment by tanhuazh** [comment]
I am using like:

-L/path/to/openssl -lcrypto

**Comment by kaduk** [comment]
You should show the full linker command line.  If there are other directories earlier in the search path, that contain a different installation of openssl, that will be preferred.

**Comment by tanhuazh** [comment]
I did another build from scratch(deleted previous). And built a small test app, it is working. It seems if I did a './config' and build before, and do another './config no-shared' and build, the result might not be what i wanted.

**Comment by levitte** [comment]
Yeah, I usually to this:

```
make clean; ./config ...
```

exactly to make sure I start from a clean slate
