### ISSUE TITLE
Test "test\recipes\04-test_asn1_encode.t" failed on Windows x64

### ISSUE THREAD

**Issue by KarenHuang2016** [openssl/openssl#3133]
I tried to build openssl and run tests using VS2015 update 3 on Windows. I noticed that test "test\recipes\04-test_asn1_encode.t" failed on Windows x64 after revision 37332ec (Add a test of encoding and decoding LONG, INT32, UINT32, INT64 and UI…). This test is added by revision 37332ec. And it only failed on Windows x64. It passed on Windows x86. Could you please take a look at that? Thanks!

The following is the steps I used to build and run test for openssl:
1.git clone https://github.com/openssl/openssl D:\openssl\src
2.cd D:\openssl\src
3.perl Configure VC-WIN64A
4.nmake clean
5.where cl.exe
6.nmake
7.nmake test

Here is the error message:

```
Failed test 'running asn1_encode_test' at test\testlib/OpenSSL/Test/Simple.pm line 77.
Looks like you failed 1 test of 1.
test\recipes\04-test_asn1_encode.t ......... 
**Dubious, test returned 1 (wstat 256, 0x100)**
Failed 1/1 subtests 
```

**Comment by levitte** [comment]
Please do this and give us the full output:

```
nmake test TESTS=test_asn1_encode V=1
```

**Comment by dot-asm** [comment]
```
..\openssl\test\recipes\04-test_asn1_encode.t ..
1..1
Failed encode/decode round trip 2 of LONG
1504:error:0D0A6080:asn1 encoding routines:long_c2i:integer too large for long:..\openssl\crypto\asn1\x_long.c:164:
1504:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:..\openssl\crypto\asn1\tasn_dec.c:609:Field=test_long, Type=ASN1_LONG_DATA
Encode/decode round trip 3 of LONG mismatch
asn1_encode_test.exe: 6 test cases
** test_long_32bit failed **
--------
asn1_encode_test.exe: 1 test failed (out of 6)
asn1_encode_test.exe => 1

not ok 1 - running asn1_encode_test
#   Failed test 'running asn1_encode_test'
#   at ..\openssl\test\testlib/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by levitte** [comment]
Thanks. Interesting that appveyor didn't catch this :-/

**Comment by dot-asm** [comment]
It might happen that it did, just didn't flag it red. I didn't look for this case, but have a look at the bottom of https://ci.appveyor.com/project/openssl/openssl/build/master.9335/job/g8vf3ed1fa436785.

**Comment by levitte** [comment]
Errrr, that's not good...

**Comment by dot-asm** [comment]
Ought to be my fault... I mean I was last to modify appveyor.yml. There will be request...

**Comment by dot-asm** [comment]
Looks like compiler bug, because if I drop optimization to 0, test passes...

**Comment by KarenHuang2016** [comment]
Thanks for fixing this issue!
