### ISSUE TITLE
Cross compiling Qt 5.8 for arm fails due to OpenSSL

### ISSUE THREAD

**Issue by GitAnonymous** [openssl/openssl#3134]
I know that big changes within the OpenSSL API have been made between 1.1.0 and 1.0.2 (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes). However, I can not resolve the following problem: I have to compile Qt with WebEngine-support, OpenSSL is required. 

**1.)**
When compiling **Qt 5.8 with OpenSSL 1.1.0** I get the following error:  

`error: invalid use of incomplete type ‘X509 {aka struct x509_st}’`

 (see: http://stackoverflow.com/questions/35488166/error-compiling-qt5-with-openssl-linked)

**2.)**
Compiling **Qt 5.8 with OpenSSL 1.0.2 (or less)** results in the following error:  

Qt 5.8 can not find **_async.h_**. This file is indeed missing in the earlier OpenSSL versions. 

So how am I supposed to resolve this? Both versions do not work. What are my options?

**// Edit:**
I just checked OpenSSL 1.1.0 with Qt 5.9. Still getting errors such as
```

ssl/qsslkey_openssl.cpp:182:49: error: invalid use of incomplete type ‘DSA {aka struct dsa_st}’
         case QSsl::Dsa: return q_BN_num_bits(dsa->p);
                                                 ^
In file included from /home/swg/opensslcross/opensslArm/include/openssl/crypto.h:35:0,
```

**Comment by mattcaswell** [comment]
The last updates on this page suggest that OpenSSL 1.1.0 support won't be added until Qt 5.10:

https://bugreports.qt.io/browse/QTBUG-52905

I don't know about the async.h issue - but it sounds like a question for the Qt team rather than OpenSSL.
