### ISSUE TITLE
Curve25519 support

### ISSUE THREAD

**Issue by sab24** [openssl/openssl#3140]
Hi,

I'm trying to generate X.509 certificates with Curve25519 encryption. I try to run

`openssl ecparam -genkey -name X25519 -out key.pem`

which gives

`unable to create curve (X25519)`

The following command does seem to do something

`openssl genpkey -algorithm X25519 -out key.pem -outform PEM`

which seems to create a private key with Curve25519. 

How can I generate an X.509 certificate with curve25519? Is it only partially supported in Openssl? I am using 1.1.0e.

**Comment by richsalz** [comment]
X25519 is only for key exchange.
For signatures you need Ed25519 which is not yet implemented.
