### ISSUE TITLE
Format modifiers in 1.1.0

### ISSUE THREAD

**Issue by dot-asm** [openssl/openssl#3143]
According to https://travis-ci.org/openssl/openssl/branches 1.1.0 has "fallen out" the loop. --strict-warnings builds fail complaining [at least?] about pre-C9x format strings. Even though in master it's worked around by effectively masking the warning in pre-C9x builds, one should recall that format modifiers recently introduced in BIO_print are master-only.

**Comment by levitte** [comment]
And on my laptop, `--strict-warnings` builds flawlessly...  that makes it harder to predict these failures :-/

Also, the `%ju` modifier should of course be replaced with `PRIu64`, but what about `%jd`?

**Comment by levitte** [comment]
Of course, internet has the answer...  `PRId64`...  but then we need to define it along with `PRIu64`...

**Comment by dot-asm** [comment]
`PRI*64` applies to printf, but not *necessarily* to BIO_printf. For example on earlier MSVC it would have to defined as `I64*`, but does BIO_printf understand I64? No. For example UEFI contributors chose Lu, but does BIO_printf understand it [in integer context]? No...

**Comment by levitte** [comment]
> For example UEFI contributors chose Lu, but does BIO_printf understand it [in integer context]? No...

Not sure I understand...  from looking at `b_print.c`, I can't see why it should understand `Ld` less than it does `Lu`...

**Comment by levitte** [comment]
(and mind you, I'm looking in the 1.1.0 branch)

**Comment by dot-asm** [comment]
```
            case 'L':
                cflags = DP_C_LDOUBLE;
                ch = *format++;
                break;
```
*DOUBLE*.

**Comment by levitte** [comment]
Yes?  That doesn't answer my question.  But to make it clear, does `b_print.c` understand `Lu`?  If so, why would it not understand `Ld`?  Looking at the code, I looks to me like it should be able to handle (or at least accept) both equally.

**Comment by dot-asm** [comment]
If you follow DP_C_LDOUBLE you'll see that it's effective only with 'f', 'e' and 'g' formats. With int it's a no-op.

**Comment by levitte** [comment]
Ok, that's what you're saying.  Thanks.

Maybe that should be addressed as well (not in #3144, though)

**Comment by dot-asm** [comment]
> Maybe that should be addressed as well

Point is that `PRI*64` is about whatever C RTL there is, not about BIO_printf. Or in other words it's error-prone to use `PRI*64` with BIO_printf, it just shouldn't be done. I'm closing this and will proceed in #3144.

**Comment by levitte** [comment]
Ok.  We *do* already use `PRIu64` in 1.1.0, we should probably address that
