### ISSUE TITLE
TLSv1.3: How to send signed_certificate_timestamp extension from server?

### ISSUE THREAD

**Issue by tatsuhiro-t** [openssl/openssl#3151]
In TLSv1.2, we use `SSL_CTX_add_server_custom_ext` to send signed_certificate_timestamp extension.
With TLSv1.3, it does not seem to work.  Probably it may be expected since signed_certificate_timestamp is moved to Certificate message as opposed to ServerHello in previous version of TLS.
I checked OpenSSL documentation, but I only found the cilent side functionality (ct_log_list.cnf), and could not find how to send it from server properly.
Could you tell us how to achieve this with TLSv1.3?

**Comment by mattcaswell** [comment]
Use `SSL_CTX_add_custom_ext()` instead:

https://www.openssl.org/docs/manmaster/man3/SSL_CTX_add_custom_ext.html

**Comment by tatsuhiro-t** [comment]
Thank you. It works for me perfectly.
