### ISSUE TITLE
Signature algorithm  RSASSA-PSS / RSAES-OAEP with openssl

### ISSUE THREAD

**Issue by Tdimsch** [openssl/openssl#3178]
Hi, since a few days I have been searching for an answer:

How do I create certificates with:

- Signature algorithm  RSASSA-PSS  
- Key encryption:  RSAES-OAEP
- Content encryption:  AES-128 CBC or AES-192 CBC  

Currently I use openssl version 1.0.2g.

**Comment by richsalz** [comment]
RSA-PSS is not available in 1.0.2, only in the current master.

**Comment by richsalz** [comment]
I didn't say 1.1.0, I said master.

**Comment by Tdimsch** [comment]
What do you mean with "master", the last version 1.1. 0e?

**Comment by richsalz** [comment]
No, I mean the current development branch for what will become 1.1.1
You might want to read up a bit on git and master, if the concept isn't clear.

**Comment by Tdimsch** [comment]
Shortly, only from version 1.1.1openssl will support RSASSA-PSS / RSAES-OAEP, correct?

**Comment by richsalz** [comment]
yes.  and you can get a "pre-release" version now in the master branch
