### ISSUE TITLE
 "openssl x509 -in" always treat the file as a TRUSTED CERTIFICATE

### ISSUE THREAD

**Issue by kaichieh** [openssl/openssl#3180]
version: 1.1.0e
"openssl x509 -in" always call PEM_read_bio_X509_AUX to decode the certificate even if its name is CERTIFICATE but not TRUSTED CERTIFICATE
May I know is it expected behavior?

**Comment by mattcaswell** [comment]
Yes, this is expected behaviour. That routine can read either type of certificate PEM file.
