### ISSUE TITLE
Alignment issue when the ASN.1 types INT32, UINT32 or Z variants are used

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#3191]
With `enable-ubsan`, the test from #3190 triggers an alignment error.  The reason for this is that the contents of a ASN.1 "mapped" structure is expected to be a bunch of pointers to further ASN.1 items, while the types LONG, LONG, INTxx, UINTxx and Z variants are immediate values rather than pointers.  This is handled deep down with a bit of magic casting, and worked as long as these immediate types matched pointers in size.  This seems to be fine for LONG (i.e. the C type `long`), since it's usually the same size as a pointer.

Enter INT32 and UINT32 (C types `int32_t` and `uint32_t`), which is half the pointer size on LP64 systems.  This results into an alignment issue for any item following one of these, which ubsan makes plainly visible.

Most of the time, we seem to get away with this...  printing being the exception.  The issue happens when trying to fetch from `*fld` [here](https://github.com/openssl/openssl/blob/master/crypto/asn1/tasn_prn.c#L155)

I don't know the asn1 code well enough to propose a viable solution, and would need some help (at least with creative ideas).  @snhenson?  @dot-asm?  @mattcaswell?  Anyone else?

**Comment by levitte** [comment]
The obvious solution is to throw away INT32...  Unfortunately, somewhere in the future when LP128 start making their appearance, we will have the exact same problem with INT64...

**Comment by richsalz** [comment]
you could memcopy it into a local variable of the right type.

**Comment by levitte** [comment]
Thing is that the more general code has no idea these are immediate values rather than pointers.  The "conversion" is done with cast magic in the lowest level routines in `x_int64.c`...  so for starters, we would really need a flag saying that these are immediate values...  which will basically affect any code that handles `ASN1_ITYPE_PRIMITIVE`.

**Comment by levitte** [comment]
It should be doable, but will affect many places...

**Comment by levitte** [comment]
Ah, or use ASN1_TFLG_EMBED

**Comment by levitte** [comment]
Yup, EMBED was the answer.  PR coming up soon.

**Comment by dot-asm** [comment]
Just in case for reference. Sanitizer report means that those fuzzing tests should actually crash on processors that don't tolerate unaligned access. And I can confirm that it is in fact the case, e.g. they do crash with SIGBUS on SPARC.

**Comment by levitte** [comment]
Fixes are in...  @dot-asm, I'm interested to know if the fixes work on SPARC as well.

**Comment by levitte** [comment]
The top description isn't entirely correct. This issue was mainly triggered when two `int32_t` (or the unsigned variant follow one another on a P64 system, like this:

``` C
struct {
    int32_t one;
    int32_t two;
} ;
```

If these aren't marked as embedded, the upper levels of the asn1 code will treat them as pointers. This works fine most of the times if the PRIMITIVE has a set of private functions to treat them and compensates for the upper level assumption. However, there are places where you find things like `*fld == NULL`, which will trigger an alignment issue for the field `two`. 

Marking such fields as embedded removes that problem by working with a temporary pointer in the code that is set to point at the embedded data. *That's the right thing to do*
