### ISSUE TITLE
Option to specify iteration count for PKCS#8

### ISSUE THREAD

**Issue by rfkrocktk** [openssl/openssl#32]
See: https://github.com/openssl/openssl/blob/master/apps/pkcs8.c#L210

PKCS#8 only allows you to set the password iterations to 1, but it doesn't allow you to actively change the iteration count.

**Comment by FdaSilvaYY** [comment]
fixed here 8a6c6bbf21cc11ea0fed69a106250af0d734d786, no ?

**Comment by kroeckx** [comment]
I think so too, so closing.
