### ISSUE TITLE
Support for Camellia cipher suites in TLS

### ISSUE THREAD

**Issue by MichalStaruch** [openssl/openssl#320]
Camellia is modern and standardized cipher (by means of ISO, NESSIE and CRYPTREC and IETF), uses higher number of rounds than AES, and no attack able to break full Camellia exists (SFAIK).

Camellia cipher suites for TLS are standardized under [RFC 6367](https://tools.ietf.org/html/rfc6367), including both GCM and CBC modes (with HMAC-SHA-256 and HMAC-SHA-384).

I think they're worth adopting, especially the AEAD modes.

**Comment by richsalz** [comment]
Camellia-CBC is supported now.  I don't see any real interest in camelia-aead, so I'm leaning toward closing this.

**Comment by MichalStaruch** [comment]
@richsalz It won't be possible to use non-AEAD version of any cipher in [TLSv1.3](https://tools.ietf.org/html/draft-ietf-tls-tls13-07), so not supporting it means banning non-US ciphers in TLSv1.3.

It it big change to support Camellia GCM mode to OpenSSL, in your opinion? I've looked at the NSS patch adding support for Camellia GCM mode (see [NSS bug #940119](https://bugzilla.mozilla.org/show_bug.cgi?id=940119)), and it was pretty small change, under 100 lines of code.

**Comment by richsalz** [comment]
I don’t know how big a change it would be; I haven't looked.  Nobody has ever asked about it, in several years.  AES isn't really a US cipher, it's Dutch :)

**Comment by MichalStaruch** [comment]
@richsalz OK, let it be Dutch and approved in the US :). Anyway, AES-256 is not as strong as it should be (susceptible to related-key attack - not really an issue in case of TLS, but still, some kind of weakness), so if someone wants standardized 256-bit grade cipher without any serious flaw we have ChaCha20-Poly1305 (efficient and looks solid, but still pretty young and not yet standardized in TLS context) and Camellia-256 (years passed, no flaw found, fully standardized - including GCM mode in TLS context).

IMO it's worth having more than one 256-bit grade cipher without any known weakness, that will be compatible with TLSv1.3. Up to you, of course.

**Comment by mattcaswell** [comment]
Whilst GCM exists as a mode within libcrypto, it has not been exposed through EVP for anything other than AES. Therefore adding a TLS Camellia GCM ciphersuite would first require the libcrypto work to expose some EVP_camellia_*_gcm() functions. That's probably non trivial. If someone does that work then adding the TLS ciphersuite (should be) relatively easy.

**Comment by ghedo** [comment]
I added Camellia GCM support in #374. Testing is very welcome :)

**Comment by wolfbeast** [comment]
For the record, Camellia-GCM will be added to NSS (opening it up to the Firefox users) and seems to already have been implemented in other SSL libs. I'd very much like to see this added to OpenSSL so it can be used in downstream applications like nginx and offering a non-US (origins of the algo aside) choice for encryption that is at equal level of maintenance as AES.

**Comment by richsalz** [comment]
Camellia is in NSS but will not be supported by FireFox.  Nor will it be supported by boringSSL or Chrome. The organization that standardized it also chose AES, which was created by Belgians, had a global review, and was first chosen by a US organization.  The AEAD construction used in Camellia is the one first defined for AES, GCM.

So support in other places is not strong, it doesn't work for TLS without significant work, nobody has looked at it in terms of constant-time stuff, the "anything but US" argument doesn't really hold, it's not on the major list of things we need to do for 1.1, and unless someone else on the team steps up to "own" the implementation, it's not going to happen.

Realistically, I should close this issue and the PR. But I know people will want to argue. :)

**Comment by wolfbeast** [comment]
> Camellia is in NSS but will not be supported by FireFox.

Umm.. I think you're wrong. Although they've removed the CBC variants (still supported by others) they do have things in the works for adding Camellia-GCM, to be supported by Firefox when done.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=940119

> Rationale: We should support the ECDHE and AES-GCM variants for any symmetric cipher we expect to support long-term. As Camellia seems to have some international support (ENISA, NESSIE, CRYPTREC, at least), it seems reasonable to support it long term.

> It's usage in TLS context is described in RFC 6367 (https://tools.ietf.org/html/rfc6367) and I think it's GREAT idea to have it included in future releases of NSS, especially the in GCM (AEAD) modes with forward secrecy (TLS_ECDHE_ECDSA_*, TLS_ECDHE_RSA_* and TLS_DHE_RSA_* variants).

So, not to argue, but adoption of a cipher is also dependent on servers being able to offer it. If OpenSSL doesn't, then it in turn prevents widely-used server implementations (like nginx) from offering it. For being such a fundamental and widely-used library, I'm surprised to see this kind of resistance here. Is Google really determining the direction of the open source communities these days?... o.O

IMHO: If there is already an implementation and an updated patch available, then use it already!

**Comment by kaduk** [comment]
An implementation is not enough; there needs to be energy to support it or it will just cause problems years down the road.

**Comment by richsalz** [comment]
@wolfbeast, I am not wrong; I spoke directly to ekr about their plans.  And @kaduk is right, throwing code into the distro without ongoing commitment to support and fix issues is wrong.

**Comment by wolfbeast** [comment]
Got to love the status quo, I guess.

**Comment by richsalz** [comment]
I closed the OpenSSL tickets on this and some discussion has started up.  But what's happening now is that without someone from the team actively taking an interest, it won't happen.  Sorry.

**Comment by supradix** [comment]
Sounds like someone here is on the NSA payroll, or at least mentally owned.  Typical.  No wonder OpenSSL has become a global cypherjoke in recent years.  I started down this road with the first ssl-eay patches and if I am saddened to see this recalcitrant, retrograde mindset so thoroughly ensconced in its progeny.  Camellia is a no-brainer.  Wake up an smell the future, or, at the very least, stop trying to crush it for others.  Resistance is futile, but it's also harmful... well, depending on which team you're batting for, or guess.

**Comment by supradix** [comment]
Oh, look.  CAMELLIA-GCM (and CHACHA20-POLY1305) in the *current* version of GnuTLS.

http://nmav.gnutls.org/2015/11/an-overview-of-gnutls-34x.html
https://www.gnutls.org/manual/html_node/Supported-ciphersuites.html
http://www.gnutls.org/download.html

Imagine that.  Seems everyone's head isn't up their ass.  Go team freedom! :D
