### ISSUE TITLE
Private key size difference on Asian O/S?

### ISSUE THREAD

**Issue by nathanpocock** [openssl/openssl#3202]
Hello, we have identified a problem where the size of the private key that is generated for a new certificate is different for Asian versions of Windows. This problem leads to interoperability problems where secure connections are unable to be established using Asian systems.

Replication steps:
1. Prepare an Asian O/S (you might choose to install an English language pack)
2. Generate a public/private key-pair
3. The size of the private key is approx. 2-bytes larger than an equivalent for an English based O/S

Note: you cannot use an English-based O/S with an Asian language-pack; this will not produce the desired result.

Is this a known issue? is there a work-around? Any help/suggestions would be appreciated. Thank you.

**Comment by mattcaswell** [comment]
Please can you provide the steps you used to create the private key (what kind of key is it?). Also provide details of how you know that the size is different, and the interoperability problems that result.

**Comment by nathanpocock** [comment]
Well, I must apologize. My engineer has just informed me that he is now no longer able to reproduce this. He's unsure if recent Windows Updates may have resolved this issue. So I will close this case.
