### ISSUE TITLE
pkeyutl return 0 if the verification succeeded

### ISSUE THREAD

**Issue by junfx** [openssl/openssl#3214]
If return non-zero, which not consistent with shell conventions, the shells/scripts treat the cmd as failed.

**Comment by levitte** [comment]
Why did you close #3213?

**Comment by junfx** [comment]
need cla

**Comment by levitte** [comment]
Unless it's seen as trivial. You can signal that view by having the following line in the commit message 👍 

```
CLA: trivial 
```

**Comment by mattcaswell** [comment]
The linked PR was merged so closing.
