### ISSUE TITLE
Unable to build FIPS compliant OpenSSL library (for Android) (v 1.1.0c)

### ISSUE THREAD

**Issue by akothari1118** [openssl/openssl#3215]
I am following the instructions present at https://wiki.openssl.org/index.php/FIPS_Library_and_Android but there are a couple of problems that I am facing while building the library.

I am using version 1.1.0c and openssl-fips-2.0.14 

1) From the wiki,
when trying to execute this
**perl -pi -e 's/install: all install_docs install_sw/install: install_docs install_sw/g' Makefile.org**

I don't find a Makefile.org in the file directory. There is only a "Makefile.shared" present.

2) When I execute the "make all" command after executing the below as given in the wiki

**./config fips shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/usr/local/ssl/$ANDROID_API \
  --with-fipsdir=/usr/local/ssl/$ANDROID_API --with-fipslibdir=/usr/local/ssl/$ANDROID_API/lib/**

I get the following error

i686-linux-android-gcc: error: unrecognized command line option '--with-fipsdir=/usr/local/ssl/$ANDROID_API'
make[1]: *** [crypto/cversion.o] Error 1

Following are the values being set from the setenv-android.sh
ANDROID_NDK : android-ndk-r11c
ANDROID_ARCH : arch-x86
ANDROID_API : android-19
ANDROID_EABI : x86-4.9

Please let me know if any further information is needed.

**Comment by levitte** [comment]
1.1.0 builds *differently* from previous versions.  Read `INSTALL`.

Also, 1.1.0 is not FIPS capable.  Later 1.1.*x* might get that added back, but there's no promise for now.
