### ISSUE TITLE
OpenSSL encryption error is FIPS mode

### ISSUE THREAD

**Issue by srahul123** [openssl/openssl#3216]
OpenSSL crypto library (version 1.0.2k) gets a different checksum for the same plain text in FIPS and non-FIPS mode. The code is attached. The code is not encrypting any data - just using AES-GCM for computing a MAC. In FIPS mode, the checksum is "16 d b9 5 6 6 72 4 42 29 bc 84 94 7b c9 50" and in non-FIPS mode the checksum is "b ac 9c 22 25 f8 c6 67 2f 8f d2 fe de ae c4 ce".
[openssl-test.txt](https://github.com/openssl/openssl/files/919229/openssl-test.txt)

**Comment by srahul123** [comment]
The above code has a bug - bad buffer lengths. Please see the following code.
[openssl-test.txt](https://github.com/openssl/openssl/files/919223/openssl-test.txt)

**Comment by abhispra** [comment]
bump

**Comment by richsalz** [comment]
We are not making any changes to the existing FIPS code.  Closing this.
