### ISSUE TITLE
renew a valid certificate without database error

### ISSUE THREAD

**Issue by RaSchmidt1960** [openssl/openssl#3224]
Hi,
when I create a certificate with the same subject openssl print out a database error and do not accept the request.

Most users want to extend / renew their certificate befor it expired or revoked.

How can I extend/renew a valid certificate without revoke?

Openssl show a database error by renew an valid certificate, but I must renew certificate befor its expired or revoke.

OK, I can write a program that temporarily changes the index.txt, but that is not a real solution.

**Comment by richsalz** [comment]
The openssl "ca" program is not a full-fledged CA.  It does what it does :)

**Comment by FlorianMickler** [comment]
man openssl-ca
-> set unique_subject = no in your config file

**Comment by t8m** [comment]
Closing as the feature is there for a long time. Maybe the default could be changed but probably not worth it.
