### ISSUE TITLE
Writing to a full disk does not result in "no space left on device"

### ISSUE THREAD

**Issue by saraedum** [openssl/openssl#3232]
Writing to a file on a full disk should produce an error message or at least a non-zero exit code. However, with version 1.0.2k (and equally with the latest version from master 7db0289ea70b9bec94e32350cc8ec9da96ab2776) the following happens:
```
% df /tmp/small                                                           
Filesystem     1K-blocks  Used Available Use% Mounted on
none                   4     4         0 100% /tmp/small
% openssl aes-256-cbc -a -pass pass:pass -in /dev/null                    
U2FsdGVkX1/uWnU+dbf+vINloOWFI6NpaZ3YfKCjJCg=
% openssl aes-256-cbc -a -pass pass:pass -in /dev/null -out /tmp/small/out
% echo $?
0
% cat /tmp/small/out                                                      
% openssl aes-256-cbc -a -pass pass:pass -in /dev/null | cat > /tmp/small/out
cat: write error: No space left on device
```

**Comment by saraedum** [comment]
The problem could be a missing check on the return value of `fflush()` in https://github.com/openssl/openssl/blob/f7970f303f849f0d0c8eb1717efd35b559c47964/crypto/bio/bss_file.c#L323.

**Comment by bernd-edlinger** [comment]
@richsalz I think this one is fixed...
