### ISSUE TITLE
segmentation fault in remove_session_lock OpenSSL 1.0.2k

### ISSUE THREAD

**Issue by stefanu21** [openssl/openssl#3250]
in OpenSSL 1.0.2k file openssl/ssl/ssl_sess. 
function remove_session_lock() line 831
`lh_SSL_SESSION_delete()` can return NULL 
line 839 `r->not_resumeable = 1` can cause segmentation fault...

**Comment by bernd-edlinger** [comment]
I don't think so, because  lh_SSL_SESSION_retrieve above returned already non-zero,
and the CRYPTO_LOCK_SSL_CTX is held.
So lh_SESSION_delete should be guaranteed to succeed.

**Comment by levitte** [comment]
@stefanu21, do you have a use case, or is this a hypothesis from reading the code?

**Comment by mattcaswell** [comment]
No response from OP to above comments. Closing.
