### ISSUE TITLE
SSL_accept hangs in TLS_ST_SR_CERT_VRFY state for DTLS connections

### ISSUE THREAD

**Issue by mahesh116** [openssl/openssl#3251]
We are using Openssl release 01.01.00e on RHEL 7.0 with kernel version 3.0. We are using non-blocking sockets. 

While processing Auth Certificate Verify  ( handshake message number 22) for DTLS connection, SSL_accept hangs in TLS_ST_SR_CERT_VRFY.

![untitled](https://cloud.githubusercontent.com/assets/27770135/25179661/7a5c214a-2528-11e7-868d-fc78a8d8b554.png)

![image 1](https://cloud.githubusercontent.com/assets/27770135/25179728/ba0fd8b8-2528-11e7-800f-4cbe48cc0b70.png)

![image](https://cloud.githubusercontent.com/assets/27770135/25179727/ba0f90e2-2528-11e7-9119-3bbee451416a.png)

The check in function "ossl_statem_server_post_process_message" for the case "TLS_ST_SR_CERT_VRFY" does the following

1) If the socket is Datagram SCTP : This is true (1) because of DTLS enabled for SCTP socket.

2) "renegotiate" flag is set to 2. This value is set to 2 in function "tls_post_process_client_hello".

3) "BIO_dgram_sctp_msg_waiting" checks if any message is waiting at SCTP layer. In our case next message in handshake "Auth Change Cipher Spec" with length 14 has arrived at SCTP. So this function returns true (1).

Post processing function "ossl_statem_server_post_process_message" return "WORK_MORE_A". caller function "read_state_machine" switch case the post processing stage returns "SUB_STATE_ERROR" which intern returns (-1). Application check the SSL_accept return -1 which is passed to "SSL_get_error". "SSL_get_error" returns "SSL_ERROR_WANT_READ". 

As per the guidelines of SSL_accept documentation,  SSL_accept should be called again after checking for readFD's on the socket. I have attached the application code.

[testcode.txt](https://github.com/openssl/openssl/files/934370/testcode.txt)

SSL_accept again repeats the same flow and it hangs at TLS_ST_SR_CERT_VRFY state. 

What is the idea behind the check below  in function "ossl_statem_server_post_process_message" ? It looks to be incomplete as it is possible that next message "Auth Change Cipher Spec" is received at SCTP before post processing the  "Auth Certificate Verify"

        if (                    /* Is this SCTP? */
               BIO_dgram_is_sctp(SSL_get_wbio(s))
               /* Are we renegotiating? */
               && s->renegotiate && BIO_dgram_sctp_msg_waiting(SSL_get_rbio(s)))

**Comment by mahesh116** [comment]
When i tried to run the same call flow with the latest SNAPSHOT code. This issue does not occur. SSL negotiation is successful.

**Comment by mattcaswell** [comment]
Hmm. That is strange. I don't think there have been any SCTP related fixes that have gone in recently.

**Comment by mattcaswell** [comment]
This is still an issue even in master if client auth is done during a renegotiation over an SCTP connection.

**Comment by mattcaswell** [comment]
Fix in #3286 for master. I will create a separate PR for 1.1.0 backporting various bits from #3286 in due course.

**Comment by mattcaswell** [comment]
@mahesh116 the 1.1.0 backported fixes are in #3287. I can't backport any of the new SCTP tests I have implemented because they require the use of a new function which I am not allowed to backport. Therefore, could you test this out and confirm it fixes the issue?

**Comment by mahesh116** [comment]
@mattcaswell Thanks for the fix. I tested your fix and DTLS handshake is successful. Do we get any formal release for these fixed. If yes, can you let me know the approximate timelines ?

**Comment by mattcaswell** [comment]
Assuming #3287 is approved in a timely manner then those fixes will be automatically included in 1.1.0f when that is released. Timelines for that are not yet decided and are typically dictated by the need to release security fixes. Usually a release comes along every 2 or 3 months.

**Comment by mattcaswell** [comment]
All fixes are now in git for both master and 1.1.0.
