### ISSUE TITLE
version 1.1.0d - Generate CRL empty file fail return code 1 without any further information

### ISSUE THREAD

**Issue by aRkadeFR** [openssl/openssl#3258]
Hello,

I have an existent PKI infrastructure that was created with openssl version `1.0.0f`. I copied the CA cert, CA key, and the other certs to a new server with openssl version `1.1.0d`.

When I try to generate a new empty CRL file with the following command, I get a return code "1" without any error message printed in the stderr. And I see no error in the strace.
```
# . ./vars
# strace -s 1024 -o /tmp/openssl.strace openssl ca -config ./openssl.cnf -gencrl -keyfile keys/ca.key -cert keys/ca.crt -out /tmp/crl.pem
Using configuration from openssl.cnf
# echo $?
1
# ls /tmp/crl.pem
ls: cannot access '/tmp/crl.pem': No such file or directory
```

I'd like to know how can I debug this.

Thank you,

Have a good day

**Comment by mattcaswell** [comment]
Please post such queries on openssl-users email list:

https://mta.openssl.org

Closing.
