### ISSUE TITLE
openssl-1.1.0e compilation in solaris 10 for 64 bit with 'shared' option. please help; it's on urgent basis

### ISSUE THREAD

**Issue by KaviSel** [openssl/openssl#3270]
Hi,

Please guide or prefer to refer for the below error while getting on openssl-1.1.0e compilation in solaris 10 for 64 bit with 'shared' option.

If run with 'no-shared', getting error on product compilation of same `libcrypto.so'

```
make: Fatal error: Command failed for target `link_shlib.solaris'
Current working directory /***/openssl-1.1.0e
*** Error code 1
make: Fatal error: Command failed for target `libcrypto.so'
Current working directory /***/openssl-1.1.0e
*** Error code 1
make: Fatal error: Command failed for target `all'
```

advance Thanks

**Comment by levitte** [comment]
Please show us the lines before that... Or put the entire build log into a gist and link it here. The lines you've pasted contain nothing of value...

**Comment by KaviSel** [comment]
Hi, Thanks for fast replying. Please find the attached make.log for reference



[make_err.txt](https://github.com/openssl/openssl/files/946664/make_err.txt)

**Comment by KaviSel** [comment]
Hi,

Attached make.log in GitHub. please refer and guide me

**Comment by levitte** [comment]
Ah, it seems you configured with `--enable-tlsext`. Skip the starting dashes, the configuration option is `enable-tlsext`

**Comment by mattcaswell** [comment]
Actually that option doesn't exist at all in 1.1.0. Drop that option completely.

**Comment by levitte** [comment]
Good catch

**Comment by KaviSel** [comment]
Intitally I ran without dashes. But got error as 'Unsupported options: enable-tlsext'; Hence referred google and added :) Will try without ./Configure solaris64-sparcv9-cc --prefix=/**/openssl/v1.1.0e/solaris64 shared and confirm

**Comment by KaviSel** [comment]
Thank you Levitte

**Comment by KaviSel** [comment]
I guessed. for 32 bit no other options added such like 64bit. it compiled
successfully. Thanks you
