### ISSUE TITLE
'Cannot open include file: 'openssl/opensslconf.h'' error for MSVC parallel builds on Windows

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#3272]
Since '`nmake`' utility doesn't provide parallelism like '`make -j<n>`' do, a 3rd party tools, like [Qt Jom](https://wiki.qt.io/Jom), could be used for this purpose. It allow greatly speedup CI builds using MSVC through utilizing all CPU cores.

Parallel builds using MSVC with Jom finished successfully for [OpenSSL-1.1.0-pre5](https://www.openssl.org/source/old/1.1.0/openssl-1.1.0-pre5.tar.gz). But after commit 27ffb86c209c456c40ec82b80ebb922b5f377992 they fail with error even if jobs number == 1:
```
perl Configure threads no-deprecated shared VC-WIN64A >_Configure.log && jom -j1

jom 1.1.2 - empower your cores

        set ASM=nasm
        "C:\ProgramData\Perl64\bin\perl.exe" "crypto\aes\asm\aes-x86_64.pl" "auto" crypto\aes\aes-x86_64.asm
        cl  /I "." /I "crypto\include" /I "include" -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_API_COMPAT=0x10100000L "-DENGINESDIR=\"C:\\Program Files\\OpenSSL\\lib\\engines-1_1\"" "-DOPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /O2 /Zi /Fdossl_static -c /Focrypto\aes\aes_cfb.obj "crypto\aes\aes_cfb.c"
aes_cfb.c
c:\libOPENSSL-1.1.1-dev\build\include\openssl/aes.h(13): fatal error C1083: Cannot open include file: 'openssl/opensslconf.h': No such file or directory
jom: C:\libOPENSSL-1.1.1-dev\build\Makefile [crypto\aes\aes_cfb.obj] Error 2
```
If commit 27ffb86c209c456c40ec82b80ebb922b5f377992 is reverted, build finishes successfully even for recent OpenSSL-1.1.1-dev master.

Is it possible to fix it?
CC:@levitte

Environment:
- Windows 10 x64,
- MSVC 2015 Update 3,
- Windows SDK 10.0.14393.33,
- Active Perl 5.24.1,
- [jom 1.1.2](http://download.qt.io/official_releases/jom/jom_1_1_2.zip),
- OpenSSL-1.1.1-dev (dc99b885ded3cbc586d5ffec779f0e75a269bda3).

Alexander

**Comment by levitte** [comment]
Since nmake doesn't provide parallellism, I must admit I didn't care to check.

To fix this, we need to provide the same kind of dependency hack as Ben provided for the Unix Makefile in 27c40a93175d4dcb559325db9354910b3d16cd4e.  I'll deal with it later today.

**Comment by sav-ix** [comment]
Thank you in advance.
BTW, in case you're going to test OpenSSL parallel builds using MSVC with jom, a compiler key '[`-FS`](https://msdn.microsoft.com/en-us/library/dn502518.aspx)' required to prevent errors. Although the compiler explicitly tell it in error messages '`crypto\aes\aes_cfb.c: fatal error C1041: cannot open program database 'c:\libOPENSSL-1.1.1-dev\build\ossl_static.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS`'.

**Comment by levitte** [comment]
See if #3277 solves the problem for you.  It might require a `jom clean` before everything can get in sync

**Comment by sav-ix** [comment]
Going to test it and report asap.
I mentioned '`-FS`' just FYI. But adding it as a default build key for all MSVC builds could be 
superfluous, since it not supported by Visual Studio [prior to 2013](https://msdn.microsoft.com/en-us/library/fwkeyyhe(v=vs.110).aspx).

**Comment by levitte** [comment]
Oh...  *argh*

No time to deal with this now on my part.  Ping me again on Monday

**Comment by sav-ix** [comment]
Tested patch https://github.com/levitte/openssl/commit/8058420b5105ace06d0dbf08349576a5b4080b3a on OpenSSL master, and all builds using `<ICC|MSVC><Debug|Release><Shared|Static>` configurations finished successfully.

**Comment by levitte** [comment]
Perfect.  The change got approved too, so in it goes.

**Comment by sav-ix** [comment]
Thank you.

**Comment by levitte** [comment]
I've added support in #6007 (for master / 1.1.1) and #6008 (for 1.1.0).  It might need some work, depending on how old compilers we want to support (see@sav-ix' remark)
