### ISSUE TITLE
Share AppVeyor Nightly Builds

### ISSUE THREAD

**Issue by dizel3d** [openssl/openssl#3279]
Could you provide Windows users with AppVeyor Nightly Builds? I'm not very sure it's technically possible. But I hope it is, because you can [package artifacts](https://www.appveyor.com/docs/packaging-artifacts/) and [place badges](https://www.appveyor.com/docs/status-badges/). I think everyone dislikes building sources, so it would be very useful.

**Comment by dot-asm** [comment]
Short answer no. Long answer is that we don't want to be entangled by something we don't understand. But by "understand" I don't mean our source code or how it's compiled and works on Windows, but rather what do Windows developers expect to see. Situation is intensified by the fact that they seem to be bound by choice of compiler version, and this would kind of discriminative if we were to make the choice. In other words it's too many parameters to make it work reliably/meaningfully. Besides, we don't maintain *any* binary packages... Sorry :-)
