### ISSUE TITLE
[openssl-1.0.1m] After successful TLSv1.0 negotiation in  SSLv23 mode, openssl fails to send the data in one ssl_write() API call.

### ISSUE THREAD

**Issue by robelsharma** [openssl/openssl#329]
Version: openssl-1.0.1m
System: CentOS 6.5 (64-bit and 32-bit)
Environment: Lync Server 2010 and an openssl client.

After successful TLSv1.0 negotiation the client is not able to send the data to Lync Server 2010 with *ssl_write()* API.  The data reach the server if I use*ssl_write()* API 2 times with the same data.
openssl context has been initiated using *sslv23 method*. 

But in openssl-1.0.1g  with method *sslv3* it works fine for SSL. Is their any specific configuration necessary or is that not related to openssl?

**Comment by mattcaswell** [comment]
It's unclear from the description what the problem is. Please raise such question on the openssl-users email list. Details here https://mta.openssl.org.
