### ISSUE TITLE
DTLS1.2 Version mismatch in HelloVerifyRequest

### ISSUE THREAD

**Issue by StephanIFX** [openssl/openssl#3295]
Hi,

I am trying to pair a proprietary DTLS1.2 client with openSSL s_server implementation. 

I am facing an issue, because the client rejects the HelloVerify Request returned by openssl. 

It think the client behaves well, because the DTLS version in Hello Verify Request (DTLS1.0) sent by the server does not match the one of the Client Hello (DTLS1.2)

citing RFC 6347: "The server MUST use the same version number in the HelloVerifyRequest that it would use when sending a ServerHello."

Actually in a simple test I did I can also see this behavior:

openssl s_server -dtls1_2 -port 10000 -key key.pem -cert cert.pem

openssl s_client -dtls1_2 -connect 127.0.0.1:10000 -key key_client.pem -cert cert_client.pem                                                            

furthermore I can see, that openssl constantly uses DTLS1.0 in the in the Record Layer even though the Handshake itself is DTLS1.2  which might be another potential source of trouble ...

In the attached zipfile have attached a port capture in which the problem can be seen.

[s_server_s_client.zip](https://github.com/openssl/openssl/files/954303/s_server_s_client.zip)

same behavior can  be observed on Release OpenSSL 1.1.0d  26 Jan 2017 as well as a recent commit on  master :05d775288effa21c39e9d6b4e1c82cf06cf9ba43

In this case as I test s_server vs s_ client the problem doesn't matter, as the handshake continues  ... but in case of different client, the handshake fails.

Any hint how I can solve this issue is highly appreciated.

Best Regards
Stephan

**Comment by mattcaswell** [comment]
> It think the client behaves well, because the DTLS version in Hello Verify Request (DTLS1.0) sent by the server does not match the one of the Client Hello (DTLS1.2)
>
> citing RFC 6347: "The server MUST use the same version number in the HelloVerifyRequest that it would use when sending a ServerHello."

If you look just one paragraph above where the RFC says that you will see the following paragraph:

    The server_version field has the same syntax as in TLS.  However, in
    order to avoid the requirement to do version negotiation in the
    initial handshake, DTLS 1.2 server implementations SHOULD use DTLS
    version 1.0 regardless of the version of TLS that is expected to be
    negotiated.  DTLS 1.2 and 1.0 clients MUST use the version solely to
    indicate packet formatting (which is the same in both DTLS 1.2 and
    1.0) and not as part of version negotiation.  In particular, DTLS 1.2
    clients MUST NOT assume that because the server uses version 1.0 in
    the HelloVerifyRequest that the server is not DTLS 1.2 or that it
    will eventually negotiate DTLS 1.0 rather than DTLS 1.2.

This apparent contradiction between the two paragraphs is resolved in the errata:

https://www.rfc-editor.org/errata_search.php?rfc=6347

    It should say:

    [p. 15]            DTLS 1.2 server implementations MAY use DTLS
    version 1.0 regardless of the version of TLS that is expected to be
    negotiated, or the version that is expected to be negotiated.

    [p. 15]      DTLS 1.2 and 1.0 clients MUST use the version solely to
    indicate packet formatting (which is the same in both DTLS 1.2 and
    1.0) and not as part of version negotiation.  In particular, DTLS 1.2
    clients MUST NOT assume that because the server uses version 1.0 in
    the HelloVerifyRequest that the server is not DTLS 1.2 or that it
    will eventually negotiate DTLS 1.0 rather than DTLS 1.2.

    [p. 16] [Delete text relating to HelloVerifyRequest.server_version]

So, I believe that the OpenSSL behaviour is correct and allowed by the spec.

> furthermore I can see, that openssl constantly uses DTLS1.0 in the in the Record Layer even though the Handshake itself is DTLS1.2 which might be another potential source of trouble ...

Using DTLS1.0 in the record layer version is fine for the ClientHello. From RFC6347:

    Implementations that speak both DTLS 1.2 and DTLS 1.0 can
    interoperate with those that speak only DTLS 1.0 (using DTLS 1.0 of
    course), just as TLS 1.2 implementations can interoperate with
    previous versions of TLS (see Appendix E.1 of [TLS12] for details),
    with the exception that there is no DTLS version of SSLv2 or SSLv3,
    so backward compatibility issues for those protocols do not apply.

The referred appendix E.1 discusses allowed record layer version numbers.

s_client uses DTLS1.0 in the record layer version for its ClientHello (which is fine and allowed by the spec), and OpenSSL responds with DTLS1.0 in the HelloVerifyRequest (also fine). The second ClientHello from the client still uses DTLS1.0 in the record layer (still fine). After that all remaining messages in that trace use DTLS1.2 for the record layer version.
