### ISSUE TITLE
Bad local_depend rule in apps/Makefile

### ISSUE THREAD

**Issue by juhaszviktor** [openssl/openssl#330]
depend: local_depend
	@if [ -z "$(THIS)" ]; then $(MAKE) -f $(TOP)/Makefile reflect THIS=$@; fi
local_depend:
	@[ -z "$(THIS)" ] || $(MAKEDEPEND) -- $(CFLAG) $(INCLUDES) $(DEPFLAG) -- $(SRC); \

Here I think the '\' at the end of the line is incorrect and in some case causes the failing of make depend

**Comment by levitte** [comment]
Because it's followed by the empty line, it shouldn't cause an error...  but you are entirely correct that this is faulty.  Fix coming up!

**Comment by juhaszviktor** [comment]
Thx

**Comment by levitte** [comment]
Fixed.
