### ISSUE TITLE
OpenSSL: Change in Utf8 quoting between 1.0 and 1.1

### ISSUE THREAD

**Issue by Spindel** [openssl/openssl#3306]
in openssl < 1.1,   `openssl x509 -in foo.crt -noout -subject` would return unicode escaped like this:
`ST=\xC3\x96sterg\xC3\xB6tland`

In openssl 1.1.0,  it outputs the following:
`ST = \C3\96sterg\C3\B6tland`

Which is both difficult to parse, and doesn't escape according to normal unicode escaping tactics. Is this an expected "upgrade" telling us to not parse the output of `openssl x509`, or is it a regression?

**Comment by Spindel** [comment]
further,  it's no longer valid to do:
```
SUBJECT=$(openssl x509 -in foo.crt -noout -subject)
openssl req -subj "${SUBJECT/subject= }"
```

**Comment by Spindel** [comment]
further, "DirName" and "Subject" are now parsed and quoted differently in `openssl x509 -text`  output.

**Comment by nickthetait** [comment]
Any interest from core developers in having this feature? I may be interested in helping fix...

**Comment by mattcaswell** [comment]
I'd be interested to know where the difference was introduced and whether it was deliberate or accidental.

**Comment by richsalz** [comment]
I believe it's a bug.  Not sure of when we did it tho.

**Comment by kaduk** [comment]
In 1.0.2, we use X509_NAME_oneline(), which open-codes the hex escaping (even in master!  blech!):

```
            if ((n < ' ') || (n > '~')) {
                *(p++) = '\\';
                *(p++) = 'x';
                *(p++) = hex[(n >> 4) & 0x0f];
                *(p++) = hex[n & 0x0f];
```

In master, we use apps/apps.c:print_name(), which goes through X509_NAME_print_ex() (when XN_FLAG_COMPAT is not set), which ends up having crypto/asn1/a_strex.c:do_esc_char() doing the escaping:

```
    if (chflgs & (ASN1_STRFLGS_ESC_CTRL
                  | ASN1_STRFLGS_ESC_MSB
                  | ASN1_STRFLGS_ESC_2254)) {
        BIO_snprintf(tmphex, 11, "\\%02X", chtmp);
        if (!io_ch(arg, tmphex, 3))
            return -1;
        return 3;
```

At first glance, one wonders if the 'x'-less form should only be used for ASN1_STRFLGS_ESC_2254, since RFC 2254 does specify this specific escape format.  (But I didn't check what the other two flags are supposed to do, though they seem to be for internal use.)

**Comment by levitte** [comment]
RFC 2253 also stipulates the same kind of quoting...  I wonder, actually, why `ASN1_STRFLGS_ESC_2253` isn't part of that condition...

... but anyway, it seems like the RFCs that say anything about it agree on the 'x'-less hex escape...  Do we have some RFC or other standard document saying something else?

**Comment by levitte** [comment]
Ok, not a peep.  Given that, I think this should be closed with WONTFIX.  Will do so tomorrow unless someone speaks up.

**Comment by richsalz** [comment]
Is it tomorrow yet? :)  Removing the 1.1.1 milestone as this isn't just 1.1.1 behavior.
