### ISSUE TITLE
Could x509 sign csr with alternative name?

### ISSUE THREAD

**Issue by clouds56** [openssl/openssl#3308]
If I've get a csr with alternative name (say generated via certtool in gnutls)

```shell
certtool --generate-privkey --outfile server.key
cat << _EOF_ >server.tmpl
cn = "server"
dns_name = "localhost"
ip_address = "127.0.0.1"
organization = "Test"
expiration_days = 10
signing_key
encryption_key #only if the generated key is an RSA one
tls_www_server
_EOF_
certtool --generate-request --load-privkey server.key --template server.tmpl --outfile server.csr
```
and `openssl req -noout -text -in server.csr` shows

        ...
        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:localhost, IP Address:127.0.0.1
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: critical
                TLS Web Server Authentication
        ...

while when I run `openssl x509` to generate certificate file via:

```shell
cat <<_EOF_ >ext.cnf
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
_EOF_
openssl x509 -req -days 400 -extfile ext.cnf -extensions v3_req -CA ca.crt -CAkey ca.key -CAcreateserial -in server.csr -out server.crt
```

the `openssl x509 -noout -text -in server.crt` shows only:

        ...
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
        ...

the "X509v3 Subject Alternative Name" is gone!
Is there any parameters for `openssl x509` to keep the extensions in csr?

**Comment by clouds56** [comment]
In this example, I found that `openssl x509` would only care about the extensions in `-extfile ext.cnf -extensions v3_req`, while ignore any requested extensions in csr file.
Is it intended to behave in this way?

**Comment by richsalz** [comment]
Yes this is working as designed.
If you want extensions copied over from the CSR to the cert, they need to be in the conf file.

**Comment by clouds56** [comment]
So how? I've tried google for it but with no luck.
I would like to read the extensions from CSR (since it is provided by others) and copy them to CSR.

Thanks.

**Comment by richsalz** [comment]
Look at https://www.openssl.org/docs/manmaster/man5/x509v3_config.html  See the "copy" tag.

**Comment by richsalz** [comment]
Look at https://www.openssl.org/docs/manmaster/man5/x509v3_config.html  See the "copy" tag.  Only valid for email.  If you want other nametypes supported, please open an issue for that.

**Comment by richsalz** [comment]
It is not possible to "just copy over" every extension from the CSR.  You'll have to modify the source to do that.

**Comment by clouds56** [comment]
where would the email:copy copy from?
*This will automatically include any email addresses contained in the certificate subject name in the extension.*
So, I think it is copy the email address from the DN (distinguished name), but not the subject alternative name in the CSR.

I've tried add a email entries in CSR like this

        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:localhost, IP Address:127.0.0.1, email:me@example.org
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: critical
                TLS Web Server Authentication

and add `subjectAltName=email:copy` to ext.cnf -> v3_req, the result goes

        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name: 
                <EMPTY>

So, I still wonder "Could x509 sign csr with alternative name?"
That is to say I've already got a csr with "DNS:localhost, IP Address:127.0.0.1, email:me@example.org" could I copy these into the certificate output via x509?

**Comment by snhenson** [comment]
The "ca" utility can copy requested extensions over if you set the option in the config file. The "x509" utility doesn't have an option to do that.

The thinking was that this should be something explicitly requested and not by default because if you just copy all requested extensions over without scrutiny someone could request a CA certificate.
