### ISSUE TITLE
openssl req: Interactively specify subjectAltName (SAN)

### ISSUE THREAD

**Issue by leonklingele** [openssl/openssl#3311]
Firefox & Chrome now require the `subjectAltName` (SAN) X.509 extension for certificates.

Please provide a way to specify the SAN interactively (along the CN) when generating certs & reqs using the openssl command line tool (`openssl req`).

Currently one has to [do some ugly trickery](https://security.stackexchange.com/questions/74345/provide-subjectaltname-to-openssl-directly-on-command-line/91556#91556) to generate a self-signed certificate:
```sh
openssl req -new -key private.key -sha256 -nodes -x509 -days 365 -out public.crt \
    -subj "/C=US/ST=CA/O=Acme, Inc./CN=example.com" \
    -reqexts SAN \
    -extensions SAN \
    -config <(cat /etc/ssl/openssl.cnf \
              <(printf "[SAN]\nsubjectAltName=DNS:example.com,DNS:www.example.com"))
```

__EDIT__:
By "interactively" I mean asking for the SAN when running `openssl req` (without a `-subj`):
```sh
$ openssl req ..
[ .. ]
Common Name (eg, fully qualified host name) []: mydomain.com
Subject Alternative Name (eg, list of host names) []: mydomain.com,www.mydomain.com
[ .. ]
```

**Comment by richsalz** [comment]
A PR would help expedite this.

You can also use the $ENV construct in your config file and set the SAN field in the environment.

**Comment by tedescn** [comment]
My assumption is there are two separate requirements here:
  1. Copy the CN value to the default SAN DNS value, and
  2. Additionally capture a list of additional SANs, appending these to the default SAN.

If I've understood the requirement correctly? Is part 1. partially addressed by PR #341?

**Comment by sidshetye** [comment]
@richsalz the $ENV approach adds unnecessary complexity and also makes the scripts harder to be cross-platform. Plus it still requires even having a .conf file ...

**Comment by richsalz** [comment]
Sure, it's sub-optimal.  See the other part of my comment :)

**Comment by JamesTheAwesomeDude** [comment]
Is this "true"? https://certsimple.com/blog/openssl-csr-command

These guys say that I can use `-subj '/CN=example.com/subjectAltName=DNS.1=example.com, DNS.2=www.example.com` but I can't seem to get such syntax working on version 1.1.0g on Debian Stretch.

**Comment by levitte** [comment]
@JamesTheAwesomeDude, I would say that's possible if the signing CA knows to pick out subjectAltName from the csr's subject and make an extension of it. I don't know any CA that does this, though...

**Comment by milosivanovic** [comment]
Yeah, it doesn't create the appropriate "Subject Alternative Name" field, it just adds it to the "Subject" field, which isn't where it should be.

**Comment by richsalz** [comment]
Many commercial CA's add the CN field to the SAN extension, but not all.  And as others pointed out, it is not added to the CSR.

**Comment by JamesTheAwesomeDude** [comment]
Just wanted to say thanks so much for bfa470a4f64313651a35571883e235d3335054eb and resolving this Issue

Looking forward intensely to its inclusion in Debian. This will make manual CSR generation so much less painful!
