### ISSUE TITLE
Support for 64-bit Android cpu targets

### ISSUE THREAD

**Issue by brodybits** [openssl/openssl#333]
PR #251 was issued last march to support 64-bit Android cpu targets in the build. This is needed to build [SQLCipher for Android](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/) on 64-bit CPUs (see sqlcipher/android-database-sqlcipher#151). When can you guys look at #251?

**Comment by Malachiasz** [comment]
any progress?

**Comment by xrubioj** [comment]
Still no changes on this?

**Comment by mattcaswell** [comment]
This is in 1.1.0. Closing.
