### ISSUE TITLE
Openssl1.1.0e building on Windows7 MSVS-2005

### ISSUE THREAD

**Issue by KaviSel** [openssl/openssl#3330]
Hi,
I have done Openssl Environment setup as per Notes.Win, Notes.perl and followed the below links and tried to build for 32 and 64 bit. After those steps also still my perl version reflects on MSWIN32 not VC-WIN32 and not finding NASM(installed)

PERL Version:
This is perl 5, version 24, subversion 1 (v5.24.1) built for MSWin32-x64-multi-thread

https://www.activestate.com/blog/2010/10/how-install-cpan-modules-activeperl
https://www.activestate.com/blog/2016/01/installing-cpan-modules-activeperl-518-and-later

"Configuring for VC-WIN32
NASM not found - please read INSTALL and NOTES.WIN for further details" 

Please any of you guide me to build for VisualStudio

Advance Thanks

**Comment by levitte** [comment]
Unfortunately, the NASM install doesn't add the directory where it's install to your %PATH%, you have to do so yourself.  As soon as that's done, `Configure` will find it.
