### ISSUE TITLE
Command /usr/bin/make failed with exit code 72

### ISSUE THREAD

**Issue by sacidpak** [openssl/openssl#3350]
I downloaded this project but i cant build it.I have this error.

"Command /usr/bin/make failed with exit code 72"

I think this problem associated with /usr/bin/make but i cant solve.

I'm using;
Xcode Version 8.3.2
OS Sierra 10.12.2

Please help me.

Best Regards.

Error Full Text:
ExternalBuildToolExecution openssl-master
    cd /Users/SacidPAK/Downloads/openssl-master
    export ACTION=
    export ALTERNATE_GROUP=staff
    export ALTERNATE_MODE=u+w,go-w,a+rX
    export ALTERNATE_OWNER=SacidPAK
    export ALWAYS_SEARCH_USER_PATHS=YES
    export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY=NO
    export APPLY_RULES_IN_COPY_FILES=NO
    export ARCHS=i386
    export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
    export BITCODE_GENERATION_MODE=marker
    export BUILD_ACTIVE_RESOURCES_ONLY=NO
    export BUILD_COMPONENTS="headers build"
    export BUILD_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products
    export BUILD_ROOT=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products
    export BUILD_STYLE=
    export BUILD_VARIANTS=normal
    export BUILT_PRODUCTS_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products/Debug
    export CACHE_ROOT=/var/folders/g9/8m4h6px112j1rb17gd3xr6y00000gn/C/com.apple.DeveloperTools/8.3.2-8E2002/Xcode
    export CLANG_MODULES_BUILD_SESSION_FILE=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation
    export CLASS_FILE_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build/JavaClasses
    export CLONE_HEADERS=NO
    export CODE_SIGNING_ALLOWED=NO
    export COLOR_DIAGNOSTICS=NO
    export CONFIGURATION=Debug
    export CONFIGURATION_BUILD_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products/Debug
    export CONFIGURATION_TEMP_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug
    export COPYING_PRESERVES_HFS_DATA=NO
    export COPY_HEADERS_RUN_UNIFDEF=NO
    export COPY_PHASE_STRIP=NO
    export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
    export DEAD_CODE_STRIPPING=NO
    export DEBUGGING_SYMBOLS=YES
    export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
    export DEFINES_MODULE=NO
    export DEPLOYMENT_LOCATION=NO
    export DEPLOYMENT_POSTPROCESSING=NO
    export DERIVED_FILES_DIR=
    export DERIVED_FILE_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build/DerivedSources
    export DERIVED_SOURCES_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE=English
    export DO_HEADER_SCANNING_IN_JAM=NO
    export DSTROOT=/tmp/openssl-master.dst
    export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME=.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
    export DWARF_DSYM_FOLDER_PATH=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products/Debug
    export EMBEDDED_PROFILE_NAME=embedded.provisionprofile
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
    export ENABLE_BITCODE=NO
    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
    export ENABLE_HEADER_DEPENDENCIES=YES
    export ENABLE_ON_DEMAND_RESOURCES=NO
    export ENABLE_TESTABILITY=NO
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
    export FILE_LIST=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build/Objects/LinkFileList
    export FRAMEWORK_VERSION=A
    export GCC3_VERSION=3.3
    export GCC_DYNAMIC_NO_PIC=NO
    export GCC_ENABLE_FIX_AND_CONTINUE=YES
    export GCC_GENERATE_DEBUGGING_SYMBOLS=YES
    export GCC_OPTIMIZATION_LEVEL=0
    export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
    export GCC_WARN_ABOUT_RETURN_TYPE=YES
    export GCC_WARN_UNUSED_VARIABLE=YES
    export GENERATE_MASTER_OBJECT_FILE=NO
    export GENERATE_PKGINFO_FILE=NO
    export GENERATE_PROFILING_CODE=NO
    export GENERATE_TEXT_BASED_STUBS=NO
    export GID=20
    export GROUP=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
    export HEADERMAP_USES_VFS=NO
    export HIDE_BITCODE_SYMBOLS=YES
    export HOME=/Users/SacidPAK
    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
    export INFOPLIST_OUTPUT_FORMAT=same-as-input
    export INFOPLIST_PREPROCESS=NO
    export INLINE_PRIVATE_FRAMEWORKS=NO
    export INSTALLHDRS_COPY_PHASE=NO
    export INSTALLHDRS_SCRIPT_PHASE=NO
    export INSTALL_DIR=/tmp/openssl-master.dst
    export INSTALL_GROUP=staff
    export INSTALL_MODE_FLAG=u+w,go-w,a+rX
    export INSTALL_OWNER=SacidPAK
    export INSTALL_ROOT=/tmp/openssl-master.dst
    export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES=YES
    export JAVA_ARCHIVE_TYPE=JAR
    export JAVA_COMPILER=/usr/bin/javac
    export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
    export JAVA_JAR_FLAGS=cv
    export JAVA_SOURCE_SUBDIR=.
    export JAVA_USE_DEPENDENCIES=YES
    export JAVA_ZIP_FLAGS=-urg
    export KEEP_PRIVATE_EXTERNS=NO
    export LD_DEPENDENCY_INFO_FILE=//openssl-master_dependency_info.dat
    export LD_GENERATE_MAP_FILE=NO
    export LD_MAP_FILE_PATH=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build/openssl-master-LinkMap--.txt
    export LD_NO_PIE=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
    export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LIBRARY_FLAG_NOSPACE=YES
    export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
    export LINKER_DISPLAYS_MANGLED_NAMES=NO
    export LINK_WITH_STANDARD_LIBRARIES=YES
    export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
    export LOCAL_APPS_DIR=/Applications
    export LOCAL_DEVELOPER_DIR=/Library/Developer
    export LOCAL_LIBRARY_DIR=/Library
    export MAC_OS_X_PRODUCT_BUILD_VERSION=16C67
    export MAC_OS_X_VERSION_ACTUAL=101202
    export MAC_OS_X_VERSION_MAJOR=101200
    export MAC_OS_X_VERSION_MINOR=1202
    export METAL_LIBRARY_FILE_BASE=default
    export METAL_LIBRARY_OUTPUT_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products/Debug/
    export MODULE_CACHE_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/ModuleCache
    export OBJECT_FILE_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build/Objects
    export OBJROOT=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates
    export ONLY_ACTIVE_ARCH=YES
    export OS=MACOS
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
    export PLATFORM_NAME=macosx
    export PLIST_FILE_OUTPUT_FORMAT=same-as-input
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
    export PRECOMP_DESTINATION_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
    export PRODUCT_MODULE_NAME=openssl_master
    export PRODUCT_NAME=openssl-master
    export PROFILING_CODE=NO
    export PROJECT=openssl-master
    export PROJECT_DERIVED_FILE_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/DerivedSources
    export PROJECT_DIR=/Users/SacidPAK/Downloads/openssl-master
    export PROJECT_FILE_PATH=/Users/SacidPAK/Downloads/openssl-master/openssl-master.xcodeproj
    export PROJECT_NAME=openssl-master
    export PROJECT_TEMP_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build
    export PROJECT_TEMP_ROOT=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates
    export REMOVE_CVS_FROM_RESOURCES=YES
    export REMOVE_GIT_FROM_RESOURCES=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
    export REMOVE_HG_FROM_RESOURCES=YES
    export REMOVE_SVN_FROM_RESOURCES=YES
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
    export SDKROOT=/Users/SacidPAK/Downloads/openssl-master/macosx10.6
    export SEPARATE_STRIP=NO
    export SEPARATE_SYMBOL_EDIT=NO
    export SHARED_DERIVED_FILE_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products/Debug/DerivedSources
    export SHARED_PRECOMPS_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/PrecompiledHeaders
    export SKIP_INSTALL=YES
    export SOURCE_ROOT=/Users/SacidPAK/Downloads/openssl-master
    export SRCROOT=/Users/SacidPAK/Downloads/openssl-master
    export STRINGS_FILE_OUTPUT_ENCODING=UTF-16
    export STRIP_BITCODE_FROM_COPIED_FILES=NO
    export STRIP_INSTALLED_PRODUCT=YES
    export STRIP_STYLE=all
    export SUPPORTED_PLATFORMS=macosx
    export SUPPORTS_TEXT_BASED_API=NO
    export SYMROOT=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products
    export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
    export SYSTEM_APPS_DIR=/Applications
    export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
    export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
    export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
    export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR=/System/Library
    export TAPI_VERIFY_MODE=ErrorsOnly
    export TARGETNAME=openssl-master
    export TARGET_BUILD_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products/Debug
    export TARGET_NAME=openssl-master
    export TARGET_TEMP_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build
    export TEMP_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build
    export TEMP_FILES_DIR=
    export TEMP_FILE_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates/openssl-master.build/Debug/openssl-master.build
    export TEMP_ROOT=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Intermediates
    export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
    export UID=501
    export USER=SacidPAK
    export USER_APPS_DIR=/Users/SacidPAK/Applications
    export USER_LIBRARY_DIR=/Users/SacidPAK/Library
    export USE_HEADERMAP=YES
    export WATCH_BUILT_PRODUCTS_DIR=/Users/SacidPAK/Library/Developer/Xcode/DerivedData/iOSVNCInputClient-flpnpwdmerakpgagrenirofoekqv/Build/Products/Debug-watchos
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=8E2002
    export XCODE_VERSION_ACTUAL=0832
    export XCODE_VERSION_MAJOR=0800
    export XCODE_VERSION_MINOR=0830
    export arch=i386
    export variant=normal
    /usr/bin/make

make: error: unable to find utility "make", not a developer tool or in PATH
Command /usr/bin/make failed with exit code 72

**Comment by levitte** [comment]
I suggest you install `make`

Also, this is not an OpenSSL issue per se...  if anything, it looks like a packager issue, and you should turn to those maintaining the repository you downloaded that package from.

**Comment by sacidpak** [comment]
Can you tell me how to install make? @levitte

**Comment by sacidpak** [comment]
And i must use libcrypto.a in my project but i cant find it. @levitte
