### ISSUE TITLE
Crash due to NULL function pointer in openssl getrn

### ISSUE THREAD

**Issue by VladimirPlus** [openssl/openssl#3358]
Hi, 
One of our users has sent us dump (please see screenshot from windbg below)

![1](https://cloud.githubusercontent.com/assets/28286796/25604994/101b15b6-2f32-11e7-987e-8c0e23b02a3b.png)

I have found the same issue:
https://quickview.cloudapps.cisco.com/quickview/bug/CSCtb25580
but status is "Terminated" without explanation.

OpenSSL 1.1.0e is used.

I can't reproduce the error on my system, maybe this happens infrequently.
Please let me know if you need other info to fix the error or you have workaround to eliminate the issue.

Thanks,
Vladimir

**Comment by mattcaswell** [comment]
The stack trace indicates this happens inside OpenSSL_add_all_algorithms_no_conf() which is not thread safe. It should be called prior to starting up other threads that use OpenSSL. Are you doing that?

**Comment by VladimirPlus** [comment]
Thank you, Matt.
Yes, you're right, OpenSSL_add_all_algorithms_no_conf() is called in background threads only.
So it had happened infrequently.
