### ISSUE TITLE
[OpenSSL 1.0.2k  26 Jan 2017] Bad file descriptor

### ISSUE THREAD

**Issue by alexbowers** [openssl/openssl#3363]
I am getting a bad file descriptor error when trying to run the following command:

```
sudo openssl req \
 -newkey rsa:4096 \
 -x509 \
 -nodes \
 -keyout server.pem \
 -new \
 -out server.crt \
 -reqexts SAN \
 -extensions SAN \
 -config <(cat /usr/local/etc/openssl/openssl.cnf \
    <(printf '[SAN]\nsubjectAltName=IP:10.20.30.40')) \
 -sha256 \
 -days 3650
```

The error happens on Mac OS 10.11.6 (El Capitan), and inside Vagrant on that machine (Ubuntu 16.04.2 LTS)

```

error on line -1 of /dev/fd/11
140735122718800:error:02001009:system library:fopen:Bad file descriptor:bss_file.c:175:fopen('/dev/fd/11','rb')
140735122718800:error:2006D002:BIO routines:BIO_new_file:system lib:bss_file.c:184:
140735122718800:error:0E078002:configuration file routines:DEF_LOAD:system lib:conf_def.c:197:
```

**Comment by alexbowers** [comment]
Version reported by OpenSSL:

```
OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by alexbowers** [comment]
The issue lies in the `config` section. Is it possible to get better error reporting than this?

My temporary solution is to edit the file to add [SAN] subjectAltName... to it.

Alternatively, allow for subjectAltName to be requested interactively so config doesn't require changing

**Comment by levitte** [comment]
The issue is your use of `<(` and not specific to openssl.  Essentially, `/dev/fd/11` exists in the context of your pre-sudo process, while not existing in the context of the process that runs openssl, since that's run with sudo.

For comparison:

```
: ; cat <(cat ~/.bashrc)
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files for examples
... yadayadayada ...
```

```
: ; sudo cat <(cat ~/.bashrc)
cat: /dev/fd/63: No such file or directory
```

**Comment by alexbowers** [comment]
Thanks for the reply @levitte What would be the suggested way to do subjectAltName without having to edit the openssl.cnf file then if the <(...) thing does not work?

Or is the fix to not use sudo?

**Comment by levitte** [comment]
The fix is not to use sudo

**Comment by levitte** [comment]
... or to write the content of openssl.cnf with the `[SAN]` entry added to a temporary file and use that instead.

**Comment by alexbowers** [comment]
Ok thank you.
