### ISSUE TITLE
DSO errors on HPUX 11.31 (ia64) when initializing

### ISSUE THREAD

**Issue by kdekker** [openssl/openssl#3372]
I'm using openSSL 1.1.0e. Consider the following code:

```
bool SSLContext::initialize_library ()
{
	static bool	sInitialized	= false;
	bool lSuccess = true;

	if (!sInitialized) {
		sInitialized	= true;
#ifdef _WIN32
		// Use thread-safe system allocator. This MUST be done as the very first thing.
		int SetMemFuncs = CRYPTO_set_mem_functions(wrap_malloc,wrap_realloc,wrap_free);
		ASSERT(SetMemFuncs);	// returns FALSE when we are too late to install our own allocator functions
#endif
		/* Global system initialization*/
		SSL_library_init();
		SSL_load_error_strings();

#ifdef _WIN32
		// From the manual page at https://linux.die.net/man/3/crypto_set_locking_callback
		// OpenSSL can safely be used in multi-threaded applications provided that at least
		// two callback functions are set, locking_function and threadid_func. However, the 2nd set of
		// threadid_func functions are defined-away in the source of the current OpenSSL, so
		// don't bother with those. The example program mttest.c also doesn't use them, yet
		// the manual page still demands them.
		int i;
		lock_cs = (HANDLE *) OPENSSL_malloc(CRYPTO_num_locks() * sizeof(HANDLE));
		for (i = 0; i < CRYPTO_num_locks(); i++) {
			lock_cs[i] = CreateMutex(NULL, FALSE, NULL);
		}

		CRYPTO_set_locking_callback(win32_locking_callback);
#endif
	}
	return lSuccess;
}
```

This code works fine, but if I still check the last error, see code below:

```
void SSLContext::s_log_error( const char *aFileName, int aLineNumber, string const &aString )
{
	ostringstream lOStringStream;

	unsigned long	lLastError =  ERR_peek_last_error();

	if (lLastError == 0) {
		lOStringStream << aString;
	} else {
		char	lErrorString[256];
		ERR_error_string_n(lLastError, lErrorString, sizeof(lErrorString));
		lOStringStream << aString << ", last SSL Error: <" << lErrorString << ">";
	}

	string	lString	= lOStringStream.str();

	// first log, as the call back may change errno/GetLastError().
	// the log functions are assumed to leave errno the same.
	log_mesg(aFileName, aLineNumber, "SSLContext::log_error", TO_SET | sLogMesgType, "%s", lString.c_str());

	if (lLastError != 0) {
		// prints the error strings for all errors that OpenSSL has recorded
		// to a memory BIO,
		// emptying the OpenSSL error queue.
		CBIO_s_mem	lCBIO_s_mem;

		ERR_print_errors(lCBIO_s_mem);

		// add terminating 0 byte
		lCBIO_s_mem.write("", 1);

		BUF_MEM *	lBUF_MEM;
		lCBIO_s_mem.get_mem_ptr(&lBUF_MEM);

		if ( 2 <= lBUF_MEM->length && lBUF_MEM->data[lBUF_MEM->length - 2] == '\n') {
			// remove terminating newline
			lBUF_MEM->data[lBUF_MEM->length - 2]	= '\0';
		}

		log_mesg(aFileName, aLineNumber, "SSLContext::log_error", TO_SET | sLogMesgType, "All OpenSSL errors: %s", lBUF_MEM->data);
	}

	s_debug("%s", lString.c_str());
}

```

Then I get (only) on HP messages like:

```
All OpenSSL errors: 0:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/data/Infor/erplnora/bse/bin/blogind6.2): '/data/Infor/erplnora/bse/bin/blogind6.2' is not a valid load module: Bad object file type
2017-04-21[15:21:25(UTC+00:00)]:I:root: 0:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
```

Can anyone tell me why OpenSSL is trying to load the binary with dlopen() (of argv[0])?
Is there any benefit in dynamically loading the program itself as shared object?
Because the binary itself is already loaded/being executed, I don't understand why a dlopen() is called in crypto/dso/dso_dlfcn.c:113.

Any comments/clarifications are welcome.

**Comment by levitte** [comment]
[Here](https://github.com/openssl/openssl/blob/master/crypto/init.c#L108-L117)'s the answer.  Basically, it's a trick to make sure all loaded DSOs stick around until the process dies.  Since the code itself can't know for sure if it's part of a binary (an executable program) or a binary (a DSO), it does the same either way and doesn't care when it doesn't work.

**Comment by kdekker** [comment]
Thanks, but as a result, even if the initialization succeeds, the ERR_peek_last_error() still points to 'noise' from this DSO loading. There is no reset_error() functionality as far as I know.

Is it not strange that initialization succeeds, but leaves messages in the error buffers of OpenSSL?

**Comment by mattcaswell** [comment]
Probably we should be using ERR_set_mark() and ERR_pop_to_mark() in that code. Or (possibly)  just ERR_clear_error().

**Comment by levitte** [comment]
I think that ERR_set_mark() and ERR_pop_to_mark() is the safer bet.  That should be good enough.

**Comment by mattcaswell** [comment]
@kdekker please try the fix in #3383

**Comment by kdekker** [comment]
@mattcaswell: thanks. I will try the fix as soon I've more time. This is most probably when we update our openSSL versions (about 2-4 times per year). So it may take some months before I pick a newer openSSL version. Based on the changes I saw in your fix, it looks great. Sorry that I don't have the possibility to test sooner.

**Comment by mattcaswell** [comment]
Ok - no problem. This fix is now in git so I've closed this issue. Please create a new one if you have any problems when you do try it out.

**Comment by kdekker** [comment]
Many thanks.
