### ISSUE TITLE
DLL version always built with dynamic runtime when using Visual Studio

### ISSUE THREAD

**Issue by sergey-shambir** [openssl/openssl#3377]
DLL version always has `/MD` flag even if `/MT` can be more suitable to avoid distributing Visual Studio runtime DLLs. There is no option in Configure script.

**Comment by dot-asm** [comment]
This has been discussed several times over. If you want to decide over which compiler flag to use when linking *your* application (or wrap OpenSSL in another DLL), build static OpenSSL libs. Static OpenSSL libs bear no reference to any specific CRT and can be linked with ether dynamic or static CRT (debug or not). Which one is decided by flags *you* use to compiler *your* application code. If you consider including copy of static CRT to OpenSSL DLLs, you would have to recognize that own copy will be linked into *both* DLLs. I'm not sure that it will work, and to be honest not sure if it would be good idea to try to support it. Besides there is contradiction in the statement. If you want to avoid distributing CRT DLLs, why would you want to distribute OpenSSL DLLs? Just build everything static...
