### ISSUE TITLE
The hardcoded implication of -new with -x509 in openssl req command breaks some use-cases

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#3396]
This commit
https://github.com/openssl/openssl/commit/599e5904b22f3d50c5f4720aa3bc8ab8af0ffa98
and equivalent on 1.0.2 branch broke legitimate use-case.

Namely you can generate a request with openssl req invocation and then later you want to convert it to self-signed x509 certificate via the openssl req -x509 command. The -new should not be implicitly set at least for the case the command line specifies -in <cert.req> option. There it is clear that user does not want to generate a new request but wants to read existing request file.

**Comment by t8m** [comment]
Ping, can you please at least tell whether you consider this breakage as a bug or not and the current behavior will be kept?

**Comment by richsalz** [comment]
Seems like a bug.  A bit tricky to figure out the right thing to do tho.

**Comment by mattcaswell** [comment]
Ping @levitte. Thoughts?

**Comment by levitte** [comment]
I don't think this was an intentional breakage... In other words, I'm inclined to see this as a bug that happened with the option processing changes about a year ago... 

So I'd say this is a bug and should be fixed.
