### ISSUE TITLE
Provide a public way to parse ASN1_GENERALIZEDTIME

### ISSUE THREAD

**Issue by rcombs** [openssl/openssl#340]
The `ASN1_GENERALIZEDTIME` struct is used to return some important pieces of information related to OCSP, but as far as I can tell, there's no built-in way to convert it to a `time_t` or `tm`. This forces applications to parse the string themselves, which works, but is a pain. Since `asn1_generalizedtime_to_tm` exists, I don't see why it isn't public API.

One confusing point here: I'm not entirely clear on what time zone the returned `tm` is, but either ensuring it's UTC or providing a way to find out, and then documenting that either way, seems sane enough.

**Comment by richsalz** [comment]
In 1.1.0 ASN1_GENERALIZEDTIME_set was added.  Sadly not documented, but that's another generic issue.

**Comment by rcombs** [comment]
`ASN1_GENERALIZEDTIME_set` appears to convert a `time_t` to an `ASN1_GENERALIZEDTIME`; I'm looking for the inverse.

**Comment by richsalz** [comment]
hey @tmshort ... :)  wanna do this?

**Comment by snhenson** [comment]
You could use ASN1_TIME_diff to convert by determining the time difference from the epoch.

**Comment by tmshort** [comment]
There's PR #2753 (open); and I already tried to do the inverse (I think in PR #2632 which was closed)... but that didn't go well...

**Comment by tmshort** [comment]
(Don't get me wrong, I can resurrect it...)
