### ISSUE TITLE
Some utilities perform actions before checking if outfile is valid, and don't produce output if it isn't

### ISSUE THREAD

**Issue by acz13** [openssl/openssl#3404]
Arises in situations like `openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096` if the `/etc/nginx/ssl` directory doesn't exist. The program will do the action (which takes a long time), then fail with no output AFTER the action has finished (often several minutes or hours later). Other utilities such as `genrsa` and `rsa` seem to catch this, but a few like `dhparam` and `req` don't.

(I absentmindedly made a PR from my fork with this earlier when I meant to make an issue since I realized it wasn't only `dhparam`...)

Credit to `DeVito` for finding this

**Comment by acz13** [comment]
bump

**Comment by richsalz** [comment]
Seems like a valid issue.  Best way to get it fixed is to submit a PR with the needed changes; I don't know that anyone on the team feels this is a high priority item.

**Comment by InfoHunter** [comment]
Although Windows platform is not supported yet, but the original issue only relates to Unix platform, so it seems this issue could be closed...

**Comment by petrovr** [comment]
First using a non-standard command to write into system configuration is definitely user mistake. Report like this one has to be rejected.
For installations into system configuration must be used tools from package management.
The correct way is project commands to write into directory writable by user and then with other tools and respective permissions files to be installed. In perfect word is installation of a package. Exceptional case is program like install.

No credits for anyone that found such situation as defect!

Also report contain one remark - difference between utilities like genrsa and dhparam. If true this look like more feature request -  openssl utilities to manage output in same way. It could be defect but with very low priority.

**Comment by levitte** [comment]
`dhparams` identified.  Any other?

**Comment by levitte** [comment]
It turns out that the fix was quite simple.  See #6051.

We will have to accept that `-out` may create empty or cluttered output files if calculations end up with a fault.  Much like what happens when redirecting stdout.

**Comment by InfoHunter** [comment]
It seems very hard to have a win-win solution to address this issue and #904 ...

**Comment by richsalz** [comment]
Yes it is hard.  And it looks like we'll get a bit better, but not the "perfect" solution, this release.  That's fine.
