### ISSUE TITLE
1.0.2k not compiling with nginx 1.12

### ISSUE THREAD

**Issue by ledzepp4eva** [openssl/openssl#3411]
Hi,
I have a custom rpm for nginx that is built with openssl version 1.0.2k for ALPN support. This is working fine for 1.10.3, but I have attempted to upgrade this to 1.12, but upon rpmbuild I run into the error:
<pre>
-Wl,-z,relro -Wl,-z,now -pie -Wl,-E -Wl,-E -ldl -lpthread -lpthread -lcrypt -L/usr/lib -lm -lluajit-5.1 -ldl -Wl,-rpath,/usr/lib64/ -L/usr/lib64/ -lmodsecurity -lmaxminddb -lmaxminddb -lpcre /root/rpmbuild/BUILD/openssl-1.0.2k/.openssl/lib/libssl.a /root/rpmbuild/BUILD/openssl-1.0.2k/.openssl/lib/libcrypto.a -ldl -lz \
-Wl,-E
/usr/bin/ld: /root/rpmbuild/BUILD/openssl-1.0.2k/.openssl/lib/libssl.a(s23_meth.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/root/rpmbuild/BUILD/openssl-1.0.2k/.openssl/lib/libssl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/nginx-1.12.0'
make: *** [build] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.6yTdt1 (%build)
</pre>

Since the upgrade of nginx the spec file from the source rpm now includes the cc-opts 
<pre>
'--with-cc-opt=-fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'
</pre>

I was wondering if someone could have a look at why openssl is failing to compile with this compile option please?

Thanks,
Liam

**Comment by kroeckx** [comment]
That seems to be how you configure nginx, not how you configure
openssl.

In 1.0.2 openssl defaults to a static build, and so doesn't use
-fPIC. If you configure it shared instead it might work.

**Comment by ledzepp4eva** [comment]
Cheers for this, that did the trick. I appreciate that it isn't really a bug from an openssl stand point, but I know you guys would have the best knowledge for assisting me.

Liam
