### ISSUE TITLE
Openssl-1.0.2h failed compilation 

### ISSUE THREAD

**Issue by Openssl-Michelle** [openssl/openssl#3417]
Hello, 

I try to cross-compile openssl-1.02h on ARM. 

First, I set the environment variable: 

export ARCH=arm64 
export CROSS_COMPILE=aarch64-poky-linux- 

Then I configured it: 
./config shared --prefix=/opt/poky/aarch64-poky-linux/usr 

 When I do make I have the following error: 

aarch64-poky-linux-gcc: error: unrecognized command line option '-m64' 
<builtin>: recipe for target 'cryptlib.o' failed 
make[1]: *** [cryptlib.o] Error 1 
make[1]: Leaving directory '/opt/poky/libssl1.0.2/openssl-1.0.2h/crypto' 
Makefile:285: recipe for target 'build_crypto' failed 
make: *** [build_crypto] Error 1 

How can I fix this problem?

**Comment by dot-asm** [comment]
Quoting INSTALL:
```
       $ ./config [options]

     This guesses at your operating system (and compiler, if necessary) and
     configures OpenSSL based on this guess. Run ./config -t to see
     if it guessed correctly. If you want to use a different compiler, you
     are cross-compiling for another platform, or the ./config guess was
     wrong for other reasons, go to step 1b.
```
