### ISSUE TITLE
Error while compiling openssl-1.0.2h

### ISSUE THREAD

**Issue by Openssl-Michelle** [openssl/openssl#3429]
Hello,

I try to compile openssl-1.0.2h on linux x86_64. When I do make I get the following issue:

libcrypto.a(sha256-x86_64.o): Relocations in generic ELF (EM: 62)
libcrypto.a(sha256-x86_64.o): error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile.shared:169: recipe for target 'link_a.gnu' failed
make[4]: *** [link_a.gnu] Error 1
make[4]: Leaving directory '/opt/poky/2.0.2_building/work/libssl1.0.2/openssl-1.0.2h'
Makefile:356: recipe for target 'do_linux-shared' failed
make[3]: *** [do_linux-shared] Error 2
make[3]: Leaving directory '/opt/poky/2.0.2_building/work/libssl1.0.2/openssl-1.0.2h'
Makefile:309: recipe for target 'libcrypto.so.1.0.0' failed
make[2]: *** [libcrypto.so.1.0.0] Error 2
make[2]: Leaving directory '/opt/poky/2.0.2_building/work/libssl1.0.2/openssl-1.0.2h'
Makefile:109: recipe for target 'shared' failed
make[1]: *** [shared] Error 2
make[1]: Leaving directory '/opt/poky/2.0.2_building/work/libssl1.0.2/openssl-1.0.2h/crypto'
Makefile:286: recipe for target 'build_crypto' failed

Any ideas about how can I fix that ? Do I need to add other libraries so make builds well? 
PS: when I made make depend after executing ./config all went fine.
Thanks.

**Comment by levitte** [comment]
> when I made make depend after executing ./config all went fine.

Errr, so does that mean you don't have an issue any more?  If you do, I'd like to know how you configured.
