### ISSUE TITLE
Why is [Loading 'screen' into random state] being set as an error?

### ISSUE THREAD

**Issue by ChaseFlorell** [openssl/openssl#345]
I'm looking at the source code [here](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/apps/app_rand.c#L124) and it appears as though it's intended on being an error

    #ifdef OPENSSL_SYS_WINDOWS
        BIO_printf(bio_err, "Loading 'screen' into random state -");
        BIO_flush(bio_err);
        RAND_screen();
        BIO_printf(bio_err, " done\n");
    #endif

I'm just wondering why this is? Is there something I'm doing wrong in my invocation?

    # Called from powershell
    openssl.exe pkcs12 -export -inkey $key -in $crt -out $pfx -name $certData.name -passout pass:$password

essentially, I don't get an error in the console, and my `$lastexitcode` variable is still `0`, but when I do a deployment via Octopus Deploy, the output of `Loading 'Screen' into random state` is being picked up as an error.

![](https://i.imgur.com/vSm6wxL.png)

but the console doesn't seem to pick it up as an error

![](https://i.imgur.com/K4HSO7Z.png)

To me, it doesn't seem to be an error, but rather just normal output information. Now I don't claim to know anything about the C language, but in the above snippet I do see `bio_err` which tells me that this particular output is intended to be an error.

**Comment by richsalz** [comment]
yeah, it's a mis-feature.  we'll fix it.

**Comment by ChaseFlorell** [comment]
:+1:

**Comment by richsalz** [comment]
Sorry... after discussion it's gonna stay at stderr since it's not "useful" program output.

**Comment by ChaseFlorell** [comment]
@richsalz you're saying that because it's not useful, it's considered an error? 

Right now tools like Octopus Deploy treat that as an exception which in turn fails a deployment. But as far as I can tell, I can't get rid of that message.

Powershell is treating it as an exception with a 0 exit code. I guess I just don't understand why a "not useful" program output is to be considered an error.

**Comment by richsalz** [comment]
so Powershell and Octopus treat any output to stderr as cause for concern, even with a zero exit-code?  Seems kinda broken, but we should reconsider if that's so.

**Comment by ChaseFlorell** [comment]
I posted my octopus output in the first question. Here it is again.

![](https://camo.githubusercontent.com/93613780e0dbb5bd9590769f2da9d5f34705076d/68747470733a2f2f692e696d6775722e636f6d2f76536d3677784c2e706e67)

**Comment by richsalz** [comment]
Fixed in master and 1.0.2; thanks for the extra info.
