### ISSUE TITLE
OpenSSL does not have any of the ciphers that Microsoft Outlook uses

### ISSUE THREAD

**Issue by indinfer** [openssl/openssl#3450]
I installed the required libeay32.dll and libssl32.dll that LispWorks requires to receive emails as an SMTP with CTX and SSL. I don't understand secure socket layer very well because I don't program at a low enough level. 

I start up my server program. Then from Outlook, I send a test email on server (port) 25 to localhost. My server program receives the connection. But on the HELO stage gives this error:

SSL failure in #<COMM:SOCKET-STREAM 220F362F>:
error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher

I think that error means that OpenSSL cannot do even one of the many ciphers that Outlook can do. 

Would be nice if someone can prove me wrong so I can get on with my program. But if I am not wrong, then I am right. And seems that OpenSSL would want to support writing email servers that can interface with the ubiquitous Microsoft Outlook client.

I'm running Windows 10 64-bit, Outlook 2016 64-bit, and Lispworks 32-bit. LispWorks can use C language generated DLLs through its "Foreign Language Interface" (foreign language meaning C and not Lisp).

Let me know what you need from me to analyze. I hope I can supply whatever you ask.

**Comment by richsalz** [comment]
This is almost definitely a configuration mismatch; OpenSSL supports almost every cipher, but some of them are not enabled by default, for example, because they are no longer considered secure.  What version of OpenSSL did you install?  Can you list the available ciphers in your server?  Can you figure it to use anythting other than DEFAULT? Can you get a packet trace?

**Comment by indinfer** [comment]
I really appreciate your taking interest. The main problem has got to be my own ignorance.

I downloaded Win32OpenSSL-1_0_2k.exe and Win32OpenSSL_Light-1_0_2k.exe 
from https://slproweb.com/products/Win32OpenSSL.html . **So, my version is 1.0.2k.**

Each is an installation program. The Light is for users and the other for developers. I don't really know which I need because I'm not sure what developer means. Maybe when programming at a high level, the user version is fine. The developer did not seem to give me a more detailed error message.

Running either installation programs was not enough to make my program run. But copying two of the resulting DLLs (libeay32.dll and libssl32.dll) into the same directory as LispWorks.exe (actual executable is "lispworks-7-0-0x86-win32.exe") got me past the first error. The first error said something like "cannot not finding libssl32.dll". I moved these DLL files into the "Windows\System32" directory. That also works.

So, now I get the current error I mentioned in my first post of "no shared cipher". 

After I posted, I ran into the ebook "OpenSSL Cookbook" and the program in the OpenSSL installation "OpenSSL.exe". I'm making a wild guess that my server's list of ciphers has to do with PEM files. And just like my server could not find the libssl32.dll and the libeay32.dll, it can't find any PEM. And the reason it cannot find any shared cipher is because it doesn't have even one cipher. And it doesn't have even one cipher because it doesn't have even one PEM file. 

I don't know whether what I'm thinking and typing here makes any sense. But maybe my next step is to read the OpenSSL Cookbook to learn how to use OpenSSL.exe and for what OpenSSL.exe can be used. It might make PEM or other files. Maybe it configures something for me.

In LispWorks COMM package, I think so much is done for me that I'm a lot in the dark about what's going on underneath. I don't see a function to list the available ciphers. And my not seeing could be because I don't know what it's called in LispWorks or because I don't know where to look for such a function. 

Maybe you can tell me whether my thinking makes sense about how the Server doesn't find any PEM files, therefore doesn't have any ciphers. Or is there no connection between PEM's and ciphers?

And I am interested whether you think I might be helped along by my reading OpenSSL Cookbook and learning how to use OpenSSL.exe and for what to use it.

Am I on a good track? Or can you point me to something more likely to help?

**Comment by mattcaswell** [comment]
> Each is an installation program. The Light is for users and the other for developers. I don't really know which I need because I'm not sure what developer means. Maybe when programming at a high level, the user version is fine. The developer did not seem to give me a more detailed error message.

The page doesn't really explain it, but my guess is the developer version include debug symbols.

> After I posted, I ran into the ebook "OpenSSL Cookbook" and the program in the OpenSSL installation "OpenSSL.exe". I'm making a wild guess that my server's list of ciphers has to do with PEM files. And just like my server could not find the libssl32.dll and the libeay32.dll, it can't find any PEM. And the reason it cannot find any shared cipher is because it doesn't have even one cipher. And it doesn't have even one cipher because it doesn't have even one PEM file.

To run a server you need to have a Certificate and an associated private key (typically stored in PEM files). "openssl.exe" will help you to create those things. Without those things you will not have any ciphers available, which is probably why you are getting the error message. Reading the cookbook would be a very good start - I recommend it. The cookbook is an extract from a larger book on SSL/TLS in general (not OpenSSL specific) which would give you an excellent grounding in the subject if you are after a more detailed understanding. I recommend this book too:

https://www.feistyduck.com/books/bulletproof-ssl-and-tls/

**Comment by indinfer** [comment]
Thank you for the encouragement and the tip.

**Comment by richsalz** [comment]
Please re-open the issue is needed.
