### ISSUE TITLE
ECDSA SHA256 hash of either the private key, CSR or X509 value to file is good, while the on screen rendering indicates errors. 

### ISSUE THREAD

**Issue by tedescn** [openssl/openssl#3457]
I'm wondering if there is a better solution to my problem?

To ensure my Private Key, CSR and X509 certificate sets match, I'm generating a sha256 hash of the associated public key in der format. The generated values are good and match, hence my confidence that a ECDSA private key, CSR and x509 certificate belong together is good.

**However, the onscreen rendering looks something like:**
"140095872128928:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:asn1_lib.c:150:"

The three forms of command line queries I use are:
**Create sha256 hash from ECDSA p256 Private key**
openssl ec -in alice-ECDSA.key -inform PEM -pubout | openssl asn1parse -strparse 23 -out alice-ECDSA-key-pubkey.der
sha256_value=openssl  sha256 -c alice-ECDSA-key-pubkey.der

**Create sha256 hash from a CSR p256 public key**
openssl req -in alice-ECDSA.csr -inform PEM -pubkey -noout | openssl asn1parse -strparse 23 -out alice-ECDSA-csr-pubkey.der
sha256_value=openssl  sha256 -c alice-ECDSA-csr-pubkey.der

**Create sha256 from Public Key Certificate p256 public key**
openssl x509 -noout -in alice-ECDSA.pem -pubkey | openssl asn1parse -strparse 23 -out alice-ECDSA-x509-pubkey.der
sha256_value=openssl  sha256 -c alice-ECDSA-x509-pubkey.der

I'm wondering is this an issue? or simply a result of my approach to generating the SHA256 hash of the der encode public key?

Regards
Nigel

**Comment by mattcaswell** [comment]
This question is better asked on the openssl-users email list:

https://mta.openssl.org

Closing.
