### ISSUE TITLE
Problem with lifetime and ownership of use info in SRP_CTX

### ISSUE THREAD

**Issue by diego-santacruz** [openssl/openssl#3466]
Hi,

I have started using TLS-SRP with Apache httpd and I have encountered a problem with the lifetime management of the user info in _SRP_CTX_ (i.e. _info_ member).
The ownership rules are not clear and they are different to those of the login member of the same structure.

The problem I have is that Apache httpd calls _SSL_set_srp_server_param()_ with the user info obtained via _SRP_VBASE_get1_by_user()_ and then frees it with _SRP_user_pwd_free()_ right after. The _SSL_set_srp_server_param()_ does a deep-copy of all its arguments except _info_, for which it merely copies the pointer. Hence, after _SRP_user_pwd_free()_ is called, _info_ points to freed memory, and it will be used by Apache httpd whenever the _SSL_SRP_USERINFO_ variable is referenced in the configuration files. This problem did not really occur when the older _SRP_VBASE_get_by_user()_ function was used as the user data was not freed.

While this could probably be fixed in Apache httpd by using _SSL_set_ex_data()_ and friends to duplicate the user info and free it when the SSL object is freed, I feel it would be much better and cleaner if the info member of _SRP_CTX_ had the same ownership as login, although I am no expert in OpenSSL.

This issue was being addressed by #227, but as far as I get it that was closed and never integrated.

**Comment by diego-santacruz** [comment]
I created a patch against master, that I submitted in the pull-request above.

**Comment by bernd-edlinger** [comment]
fixed on master & 1.1.0, Thanks!
