### ISSUE TITLE
Compile Git Bash + MinGW fails

### ISSUE THREAD

**Issue by Lnc** [openssl/openssl#347]
I try to compile master (commit 5e8b24dbfb98ed7c5b355cb6a959906a418e264b) under Windows 7 32 bit with Git Bash and MinGW.
```
vm@VM_WIN_7_32BIT ~/Git/openssl (master)
$ perl config shared
Operating system: i686-whatever-mingw
Configuring for mingw
Configuring for mingw
    no-deprecated   [default]  OPENSSL_NO_DEPRECATED (skip dir)
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-rfc3779      [default]  OPENSSL_NO_RFC3779 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-zlib         [default]
    no-zlib-dynamic [default]
IsMK1MF=0
CC            =gcc
CFLAG         =-D_WINDLL -DOPENSSL_USE_APPLINK -DOPENSSL_PIC -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL
_ENDIAN -DWIN32_LEAN_AND_MEAN -march=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOP
ENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM
-DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
EX_LIBS       =-lws2_32 -lgdi32 -lcrypt32
CPUID_OBJ     =x86cpuid.o uplink.o uplink-x86.o
BN_ASM        =bn-586.o co-586.o x86-mont.o x86-gf2m.o
EC_ASM        =ecp_nistz256.o ecp_nistz256-x86.o
DES_ENC       =des-586.o crypt586.o
AES_ENC       =aes-586.o vpaes-x86.o aesni-x86.o
BF_ENC        =bf-586.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4-586.o
RC5_ENC       =rc5-586.o
MD5_OBJ_ASM   =md5-586.o
SHA1_OBJ_ASM  =sha1-586.o sha256-586.o sha512-586.o
RMD160_OBJ_ASM=rmd-586.o
CMLL_ENC      =cmll-x86.o
MODES_OBJ     =ghash-x86.o
ENGINES_OBJ   =e_padlock-x86.o
PROCESSOR     =
RANLIB        =/c/Program Files/mingw-w64/i686-4.9.2-posix-dwarf-rt_v3-rev1/mingw32/bin/ranlib.exe
ARFLAGS       =
PERL          =/bin/perl.exe
THIRTY_TWO_BIT mode
DES_PTR used
DES_RISC1 used
DES_UNROLL used
BN_LLONG mode
RC4_INDEX mode
RC4_CHUNK is undefined

Configured for mingw.
```

But make fails:
```
vm@VM_WIN_7_32BIT ~/Git/openssl (master)
$ mingw32-make.exe
makefile:456: target 'tags' given more than once in the same rule
making all in crypto...
"C:/Program Files/Git/bin/sh.exe": c:/Program: No such file or directory
makefile:283: recipe for target 'build_crypto' failed
mingw32-make: *** [build_crypto] Error 1
```

If I hack Makefile (just for testing) to replace `$(MAKE)` and `$(PERL)` by `"$(MAKE)"` and `"$(PERL)"`:
```
vm@VM_WIN_7_32BIT ~/Git/openssl (master)
$ mingw32-make.exe
makefile:456: target 'tags' given more than once in the same rule
making all in crypto...
mingw32-make[1]: Entering directory 'c:/Users/vm/Git/openssl/crypto'
"C:/Program Files/Git/bin/perl.exe" ../util/mkbuildinf.pl "gcc -I. -I.. -I../include -Iinclude  -D_W
INDLL -DOPENSSL_USE_APPLINK -DOPENSSL_PIC -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -DWIN32_LEA
N_AND_MEAN -march=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -
DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_A
SM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" "mingw" >buildinf.h
g++    -c -o cryptlib.o cryptlib.c
cryptlib.c:117:31: fatal error: internal/cryptlib.h: No such file or directory
 #include "internal/cryptlib.h"
                               ^
compilation terminated.
<builtin>: recipe for target 'cryptlib.o' failed
mingw32-make[1]: *** [cryptlib.o] Error 1
mingw32-make[1]: Leaving directory 'c:/Users/vm/Git/openssl/crypto'
makefile:283: recipe for target 'build_crypto' failed
mingw32-make: *** [build_crypto] Error 1
```

**Comment by atarjoe** [comment]
I'm also have the same issue:

WIN7-TEST@WIN7-TEST-PC MINGW64 ~/Desktop/openssl-git/openssl (master)
$ ./config
Operating system: x86_64-whatever-mingw
Configuring for mingw
Configuring for mingw
    no-deprecated   [default]  OPENSSL_NO_DEPRECATED (skip dir)
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-shared       [default]
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-zlib         [default]
    no-zlib-dynamic [default]
IsMK1MF=0
CC            =gcc
CFLAG         =-DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -march=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
EX_LIBS       =-lws2_32 -lgdi32 -lcrypt32
CPUID_OBJ     =x86cpuid.o
BN_ASM        =bn-586.o co-586.o x86-mont.o x86-gf2m.o
EC_ASM        =ecp_nistz256.o ecp_nistz256-x86.o
DES_ENC       =des-586.o crypt586.o
AES_ENC       =aes-586.o vpaes-x86.o aesni-x86.o
BF_ENC        =bf-586.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4-586.o
RC5_ENC       =rc5-586.o
MD5_OBJ_ASM   =md5-586.o
SHA1_OBJ_ASM  =sha1-586.o sha256-586.o sha512-586.o
RMD160_OBJ_ASM=rmd-586.o
CMLL_ENC      =cmll-x86.o
MODES_OBJ     =ghash-x86.o
ENGINES_OBJ   =e_padlock-x86.o
PROCESSOR     =
RANLIB        =/c/Users/WIN7-TEST/Desktop/mingw64/bin/ranlib.exe
ARFLAGS       =
PERL          =/usr/bin/perl.exe
THIRTY_TWO_BIT mode
DES_PTR used
DES_RISC1 used
DES_UNROLL used
BN_LLONG mode
RC4_INDEX mode
RC4_CHUNK is undefined

Configured for mingw.

WIN7-TEST@WIN7-TEST-PC MINGW64 ~/Desktop/openssl-git/openssl (master)
$ make
makefile:464: target 'tags' given more than once in the same rule
making all in crypto...
make[1]: Entering directory 'C:/Users/WIN7-TEST/Desktop/openssl-git/openssl/crypto'
C:/Program Files/Git/usr/bin/perl.exe ../util/mkbuildinf.pl "gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -march=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" "mingw" >buildinf.h
/usr/bin/sh: C:/Program: No such file or directory
makefile:63: recipe for target 'buildinf.h' failed
make[1]: *** [buildinf.h] Error 127
make[1]: Leaving directory 'C:/Users/WIN7-TEST/Desktop/openssl-git/openssl/crypto'
makefile:285: recipe for target 'build_crypto' failed
make: *** [build_crypto] Error 1

**Comment by sav-ix** [comment]
Had similar troubles with building OpenSSL and few other libs.
The trouble was in using 'make.exe' from MinGW distributive instead of MSYS.
Try to remove from $PATH variable all 'make.exe' except from Bash directory.

Recent OpenSSL-1.1.0-pre could be build using recent MSYS2+MinGW-W64. So I'm not sure that this issue concern OpenSSL.
