### ISSUE TITLE
Adding Support for x509v3 Extension: Subject Directory Attributes

### ISSUE THREAD

**Issue by matthiasballreich** [openssl/openssl#3473]
Hi there,

please integrate the needed functions, structures and data types for full handling (read / parse and create) the X509v3 Subject Directory Attributes Extensions within OpenSSL. 

Or maybe someone of the great community can do this and make a pull request? I can't do it by own, because i don't have enough skills for that.

**Comment by JonathanWilbur** [comment]
@matthiasballreich I know it's been a long time since you've asked the question, but I am working on this now!

**Comment by JonathanWilbur** [comment]
Just for transparency, I actually implemented this already in a fork. I plan to create a PR for this now: https://github.com/TrustedComputingGroup/openssl/pull/8/files

**Comment by JonathanWilbur** [comment]
Can this be closed out?

**Comment by nhorman** [comment]
given that you're pull request is merged, yes.  Thank you!
