### ISSUE TITLE
Regarding _ssl.so upgradation

### ISSUE THREAD

**Issue by leelaram41** [openssl/openssl#3477]
I am facing one issue in python ssl.py file.
we are using python 2.7.3 version where ssl.py file supports only three version of protocol but 
For our new feature we require new protocol PROTOCOL_TLSv1_2  is required. When we copy the new ssl.py 
We are getting an error of 

Traceback (most recent call last):
     from _ssl import _SSLContext
ImportError: cannot import name _SSLContext

This error is coming because of _ssl.so file not finding the _SSLContext. Can you please help 

How to get the binary files of _ssl.so  for 64 bit platform.  Even we upgraded the openssl to 1.02k 
But still this error is coming. If you have any idea please help us in it.

**Comment by levitte** [comment]
This issue doesn't belong here, but with [the python project](https://github.com/python/cpython).

Pure guess, though: you might want to upgrade python.

**Comment by leelaram41** [comment]
yes.. i kept it here because that error coming because of ssl file.

**Comment by levitte** [comment]
I understand what lead you here.  Still, it's part of the python project (look for `_ssl.c` in their source.
