### ISSUE TITLE
create root.crt and personal.crt, but chrome still ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by drormu1** [openssl/openssl#3479]
I have  c# client lisetner to  Javascript via wss (site required client digital certificate + https).
I try create "127.0.0.1"  cert and use the for the client.
while check via browser to https://127.0.0.1:8181  on chrome consist they are not trusted.
boot on win7 + win10, both on Machine store and on CurrentUser store

#create the root
set OPENSSL_CONF=openssl2.cnf
openssl genrsa -out ca.key 2048
openssl req -new -x509 -sha256 -days 3000   -key ca.key -out ca.crt  -nodes -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=127.0.0.1ca"

#create the personal
openssl genrsa -out ia.key 2048
openssl  req -new     -sha256 -key ia.key -out ia.csr -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=127.0.0.1" 
openssl  x509 -req -days 3000 -in ia.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out ia.crt  -extensions v3_req -extfile openssl2.cnf

#install them
openssl  pkcs12 -export -out ia.p12 -inkey ia.key -in ia.crt -chain -CAfile ca.crt

# check the cert
[1.docx](https://github.com/openssl/openssl/files/1004410/1.docx)

openssl x509 -in ia.crt -text -noout

**Comment by richsalz** [comment]
This is almost definitely a chrome/trust-store issue and not an openssl issue.
What happens when you connect with openssl's s_client program?

**Comment by drormu1** [comment]
try on goole.com worksf fine.

c:\Temp>openssl s_client -connect 127.0.0.1:443
connect: Result too large
connect:errno=0

**Comment by richsalz** [comment]
goole.com ?  Whatever.  If you say it works fine, then this is a Chrome issue, not an openssl issue.
