### ISSUE TITLE
Smart card PIV sign certificate not able to verify signature because of requiring smimesign attribute

### ISSUE THREAD

**Issue by vsrinu26f** [openssl/openssl#3486]
I am using OpenSSL 1,0.2j 26 Sep 2016 version.

I could not get OpenSSL to verify the signature made using the PIV smart card, with sign cert in yubikey which I provisioned with "Digital Signature", "Non Repudiation" attributes as per the PIV-I Smart card standard.

I cannot add smimesign attribute to PIV as microsoft crypto will not sign with that attribute set.
I believe smimesign is to restrict to signing email or email attachments. But with "Digital Signature", "Non Repudiation" we should be able to sign and verify. Again, restricting signing makes sense than restricting verification. I might be missing here. Please fill me in.

![nosmime](https://cloud.githubusercontent.com/assets/5361462/26159386/1724d9ce-3ae4-11e7-9c50-dd0e5e0e0488.PNG)

PIV-I standard for sign certificate: see worksheet 6 ,  pages 31 and 32 (page 32 has the attributes information).

[X.509 Certificate and Certificate Revocation List (CRL) Extensions Profile for Personal Indentity Verification Interoperable (PIV-I) Cards.pdf](https://github.com/openssl/openssl/files/1008099/X.509.Certificate.and.Certificate.Revocation.List.CRL.Extensions.Profile.for.Personal.Indentity.Verification.Interoperable.PIV-I.Cards.pdf)

**Comment by richsalz** [comment]
"I could not get OpenSSL to verify the signature " What is the actual command you ran and the error that you got?  Try to cut/paste the text, not a screenshot.

**Comment by vsrinu26f** [comment]
The signature was done from wincrypt in c++ and dumped into a signature file.

## as per the c++ codes the same error message I was getting.
$ openssl smime -verify -in signature.der -inform DER -content data.txt -signer extractedsignpubkey.pem -noverify
This is text to be signedVerification failure
31604:error:21071065:PKCS7 routines:PKCS7_signatureVerify:digest failure:pk7_doit.c:1108:
31604:error:21075069:PKCS7 routines:PKCS7_verify:signature failure:pk7_smime.c:400:


$ openssl rsautl -verify -pubin -inkey extractedsignpubkey.pem < signature-sha256.bin > verified.bin
$ openssl asn1parse -inform der -in verified.bin
    0:d=0  hl=2 l=  49 cons: SEQUENCE
    2:d=1  hl=2 l=  13 cons: SEQUENCE
    4:d=2  hl=2 l=   9 prim: OBJECT            :sha256
   15:d=2  hl=2 l=   0 prim: NULL
   17:d=1  hl=2 l=  32 prim: OCTET STRING      [HEX DUMP]:600812E95D50476A50BBDBAC5A6D12D54E3EA9A0C013A7F8EBBACC2ED1E3B5CA
[signature.pem.txt](https://github.com/openssl/openssl/files/1008234/signature.pem.txt)
[ee-9c-sign-crt-chain.crt.txt](https://github.com/openssl/openssl/files/1008236/ee-9c-sign-crt-chain.crt.txt)
[ee-9c-sign-crt.crt.txt](https://github.com/openssl/openssl/files/1008239/ee-9c-sign-crt.crt.txt)
[extractedsignpubkey.pem.txt](https://github.com/openssl/openssl/files/1008241/extractedsignpubkey.pem.txt)

**Comment by richsalz** [comment]
The digest does not verify.  The most likely cause of this is, somehow, what you gave to wincrypt to sign is not the same as what you gave to openssl to verify.

The key usage bits you initially flagged are not relevant.

Look at how you handled the content -- the data.txt file?  for example, are the newline mappins the same/different.

**Comment by vsrinu26f** [comment]
It was a simple string coming from unit test. and it is the same variable passed to sign and verify functions.
string text = "This is text to be signed";
I saved this text to a file for doing it in commandline, I tried to come close to string by not typing a command line at the end of the string in data.txt file. 

I even tried ANSI, UTF-8 file formats.

**Comment by vsrinu26f** [comment]
why does OpenSSL smime error out while OpenSSL rsautil decrypts the signature and gives the digest information?

**Comment by richsalz** [comment]
if you saved it in a file, then the file probably has a trailing newline.

**Comment by richsalz** [comment]
because rsautil is not verifying the digest against the original contents.

**Comment by vsrinu26f** [comment]
How to do detatch sign using rsautl?
$ openssl rsautl -sign -inkey ee-9c-sign-key.pem -pkcs < data.txt > signature.pem
$ openssl rsautl -verify -in signature.pem -inkey ee-9c-sign-key.pem
This is text to be signed

if the second command is verifying, I am good as rsautl was returning the decrypted digest information from the detached signature produced by wincrypt.  I am not sure it also verified the decrypted digest from the detached signature.

All I need is how to do rsautl -verify from c++ codes, only if the "rsautl -verify" means not just decrypt signature to get digest information but also verify the digest too?

**Comment by richsalz** [comment]
Make sure data.txt is EXACTLY THE SAME as what you gave to wincrypt.
If you need more help, go to the openssl-users mailing list; https://mta.openssl.org for details.

**Comment by vsrinu26f** [comment]
Sure, thank you.
