### ISSUE TITLE
tar xzf openssl-1.0.2d

### ISSUE THREAD

**Issue by MrOutput** [openssl/openssl#349]
root@localhost:~# tar xzf openssl-1.0.2d.tar.gz 
tar: A lone zero block at 52140

I am receiving this extracting openssl. I have looked into the issue and some suggest that this is an issue with the file from openssl. I have checked the files integrity with the checksums provided.

**Comment by richsalz** [comment]
It is a spurious warning from GNU tar.  We are going to be using different tools to avoid this warning in the future.

**Comment by MrOutput** [comment]
Oh okay sir, thank you for the quick response!
