### ISSUE TITLE
auto option for -named_curve switch missing in man pages

### ISSUE THREAD

**Issue by 7echno** [openssl/openssl#3490]
Seems that 'auto' option is missing in man pages under -named_curves, for current master and 1.1.0 also.

**Comment by richsalz** [comment]
Can you show where?  I don't see "auto" in the apps/*.c source...

**Comment by 7echno** [comment]
I was kind of confused in the first, as I thought that it was missing from man pages.
It's in the man of SSL_CONF_cmd, but it looks more like issue in the code as passing 'auto' to s_server '-named_curve' option was/is working on 1.0.2

And now on 1.1.0 I got :

`# openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt -subj /CN=localhost -nodes -batch`
`# openssl s_server -key server.key -cert server.crt -www -named_curve auto`
`Error with command: "-named_curve auto"`

**Comment by t8m** [comment]
Perhaps for better compatibility of applications with 1.0.2 the auto keyword could be ignored by the SSL_CONF_cmd ?

**Comment by t8m** [comment]
I can prepare a pull request against master.

**Comment by richsalz** [comment]
Thanks, please do so.  And include a note in the CHANGES file for this.

**Comment by t8m** [comment]
Do you have some suggestion for the CHANGES text?

**Comment by richsalz** [comment]
The auto (or automatic) keyword in configuration files is ignored, because ...
