### ISSUE TITLE
Missing doc for X509_STORE_set_flags and others 

### ISSUE THREAD

**Issue by m-lw** [openssl/openssl#3492]
There is no documentation for X509_STORE_set_depth, X509_STORE_set_flags, X509_STORE_set_purpose and X509_STORE_set_trust which are exported from include/openssl/x509_vfy.h.

X509_STORE_set_flags is called in apps/verify.c and the latest release of gsoap uses it as well.

**Comment by richsalz** [comment]
lots of things aren't documented; see #2390 for example.  Closing this as a duplicate.
