### ISSUE TITLE
Unsupported option: -no-canonical-prefixes on Android

### ISSUE THREAD

**Issue by xsacha** [openssl/openssl#3493]
Running config with '-no-canonical-prefixes' gives an error about it being an unsupported option.

`MACHINE=armv7-a CC=/opt/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc RELEASE=2.6.37 SYSTEM=android ARCH=arm ./config "-march=armv7-a -marm -mfpu=neon -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -fexceptions --sysroot=/opt/ndk/platforms/android-19/arch-arm -fPIC" threads no-shared`

This option should be supported.

Error:
> Operating system: armv7-a-whatever-android
> Configuring for android-armeabi
> ***** Unsupported options: no-canonical-prefixes
> Configuring OpenSSL version 1.1.0e (0x1010005fL)
> make[2]: *** [OpenSSL-prefix/src/OpenSSL-stamp/OpenSSL-configure] Error 255

Full compile output: https://travis-ci.org/ingenue/hunter/jobs/215460184

**Comment by richsalz** [comment]
why? what does it do?  openssl configure normally looks at all no-XXX options as configuring openssl things.

**Comment by levitte** [comment]
Ahem, because some people wouldn't stop using arguments like `-no-asm` instead of `no-asm`, `Configure` does `s/^-no-/no-/` on all arguments (*). This was added eons ago, I'm surprised it took so long before someone got bitten. Congrats, @xsacha, you're it ;-)

We should really remove that line... 

-----

(*) it's commented "# some people just can't read the instructions"

**Comment by xsacha** [comment]
So as a workaround I should be doing s/^-no/--no/ on flags sent to config?
Thanks.

Strange it is from eons ago, I have only noticed in 1.1.0+.

**Comment by levitte** [comment]
> So as a workaround I should be doing s/^-no/--no/ on flags sent to config?

If your compiler takes `--no-canonical-prefixes`, then yes, that's a workaround

**Comment by levitte** [comment]
> Strange it is from eons ago, I have only noticed in 1.1.0+.

Interesting... 'cause I find that same line in 1.0.2's `Configure`

**Comment by richsalz** [comment]
perhaps we should teach Configure that -- means end of options, and everything else is just added to the CC flags?

**Comment by petrovr** [comment]
Rich Salz wrote:
> perhaps we should teach Configure that -- means end of options, and everything else is just added to the CC flags?
I'm not sure that is good idea unrecognized options to be added to CC

If options is "unrecognized" as work around user should set manually CC .

Or may be openssl script could be enhanced to recognize compiler flags 
similarly as linker -Wl... -Wc...

As alternative -Xlinker vs -Xcompiler : used by another wrappers.

Roumen

**Comment by xsacha** [comment]
What is the expected way to set CFLAGS to config right now because I am doing CC=clang ./config "$CFLAGS"

**Comment by xsacha** [comment]
> If your compiler takes --no-canonical-prefixes, then yes, that's a workaround
Yes, that won't actually work then because it only does the replace if there's a single hyphen. What is everyone else currently doing?

**Comment by petrovr** [comment]
Sacha wrote:
>> If your compiler takes --no-canonical-prefixes, then yes, that's a workaround
> Yes, that won't actually work then because it only does the replace if there's a single hyphen.

Hmm --<FLAG> should be set in makefile macro(variable) CFLAGS. Please 
check. Perhaps is ignored then by compiler.

> What is everyone else currently doing?
To set compiler and options in environment variable CC.

**Comment by xsacha** [comment]
So you set CC="$CC $CFLAGS" and then set CC back after compiling OpenSSL?
That doesn't sound like a good idea for usage.

**Comment by petrovr** [comment]
This issue is indirectly fixed by "Environment variable assignments on Configure command line" #4818 (master branch, upcoming 1.1.1) .
Compiler flags like -no-canonical-prefixes could be added to CFLAGS .

**Comment by levitte** [comment]
Closing this, as the `CFLAGS` env var can be used, starting with 1.1.1
