### ISSUE TITLE
'make test' says "Result: FAIL", yet CI is green...

### ISSUE THREAD

**Issue by dot-asm** [openssl/openssl#3497]
To reproduce 'make test TESTS=test_test; echo $?'. Last modification to test/run_tests.pl somehow makes it exit(0) irregardless of tests outcome.

**Comment by levitte** [comment]
Ah, `runtests` returns a TAP::Harness::Aggregator, and we should check the status explicitly (method `get_status`). 

I'm on the road right now, commenting from my mobile... Not exactly the means to produce a PR, but if you do, I can review. 

Ref: http://search.cpan.org/~leont/Test-Harness-3.39/lib/TAP/Parser/Aggregator.pm

**Comment by dot-asm** [comment]
#3501
