### ISSUE TITLE
logging to pcap file

### ISSUE THREAD

**Issue by mahantesh19** [openssl/openssl#3498]
I want to log the packet before it gets encrypted (out going) and after decryption (incoming) packets  to a file in pcap format using libpcap library. is it possible to get IP+TCP headers of the packet in SSL_read() and SSL_write() methods ?

**Comment by richsalz** [comment]
Not without source modifications.  You can create the socket outside of openssl, and query the address parameters from that (getpeeraddr, etc), and then you can "fake up" the data before&after ssl_read/ssl_write.
to massage is into libpcap format.
