### ISSUE TITLE
passing slot/key to pkcs11 engine broken on smime app

### ISSUE THREAD

**Issue by derrotebaron** [openssl/openssl#3504]
When using the smime app the -inkey argument is always considered to be a filename and access to the file is checked. It is not always the case that this argument needs to be a file, for example with the pkcs11 engine "slot_3-id_10" can be passed as the -inkey argument in order to access a private key stored on a smartcard.

The problem seems to stem from the commandline argument parsing in https://github.com/openssl/openssl/blob/master/apps/smime.c#L73
Here '<' signifies that the -inkey argument is expected to be an input file.

**Comment by richsalz** [comment]
merged.
