### ISSUE TITLE
-fingerprint    - print the certificate fingerprint

### ISSUE THREAD

**Issue by jwilleke** [openssl/openssl#3509]
I am assuming that as the "fingerprint" is not part of the certificate that the "fingerprint" is calculated by OpenSSL. However the wording of "print the certificate fingerprint" implies it is just being displayed.

Can the man pages (and docs) be changed to show that the "fingerprint" is calculated.

**Comment by InfoHunter** [comment]
A "fingerprint" of a certificate usually refers to an SHA-1 digest of the whole certificate, and there is no 'fingerprint' section in an X509 certificate. This is not invented by OpenSSL, you can also find it in your browsers as Chrome or Firefox.

So it may not be necessary to change that expression...

**Comment by nickthetait** [comment]
This issue can be closed as the associated PR has been merged
