### ISSUE TITLE
It's not possible to create EVP_MD_CTX on the stack (even though the documentation claims it would be)

### ISSUE THREAD

**Issue by peti** [openssl/openssl#3513]
Compiling the simple program

~~~
#include <openssl/objects.h>

int main()
{
  EVP_MD_CTX mctx;
  EVP_MD_CTX_init(&mctx);
}
~~~

fails with the following error:

~~~
test.c:5:14: error: storage size of ‘mctx’ isn’t known
   EVP_MD_CTX mctx;
~~~

According to the man page for `EVP_DigestInit(3)`, however, this should be legal code. The NOTES section says:

> Stack allocation of EVP_MD_CTX structures is common, for example:
>
>       EVP_MD_CTX mctx;
>       EVP_MD_CTX_init(&mctx);

Which one is wrong? The manual or the header files?

**Comment by levitte** [comment]
Errrr, the manual page from *what version*?  There's been some radical changes for 1.1.0, so if you're looking at a pre-1.1.0 manual and try to apply that to 1.1.0 libraries, you're going to be disappointed.

**Comment by peti** [comment]
Evidently. 😞 So I reckon that this is intended behavior and that I must create that type with `EVP_MD_CTX_new()`.

**Comment by levitte** [comment]
Yes, you must.
