### ISSUE TITLE
"error, no objects specified in config file" when creating CSR with ECDSA key & config file

### ISSUE THREAD

**Issue by neilstuartcraig** [openssl/openssl#3536]
Hi

I've just been creating an ECDSA-keyed CSR using a config file and ran into what I think is a bug. If i just hit <enter> when prompted for e.g. Country Code (to accept the value in my config file) then i get an error and output:

```sh
error, no objects specified in config file
problems making Certificate Request
```
The issue and solution (to re-enter the prompted-for values) is described here:
https://superuser.com/a/944378

The same procedure works fine with an RSA-keyed CSR request so I suspect the issue may be a bug in the EC implementation of `openssl req`.

I'm using a homebrew-installed openssl on my Mac (Sierra, 10.2.3):

```sh
# openssl version
OpenSSL 1.0.2k  26 Jan 2017
```

My config file is:

```sh
[ req ]
distinguished_name = req_distinguished_name
req_extensions     = req_ext
[ req_distinguished_name ]
countryName                 = GB
stateOrProvinceName         = London
localityName               = London
organizationName           = <redacted>
commonName                 = <redacted>
[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = <redacted>
DNS.2   = <redacted>
DNS.3	= <redacted>
```

and i am running:

```sh
openssl req -nodes -new -days 365 -key <domain>.ec.key -config <domain>.ec.conf -out <domain>.ec.csr
```

Hopefully that all makes sense. Please let me know if you need any more info, i search so i'm hoping this isn't a dupe but apologies if it is.

Cheers
Neil

**Comment by doug-fish** [comment]
Neil - I *just* went through this same issue. While the command ran I was seeing prompts like "US []:" and I was just hitting enter because the values I wanted were in the file.

I added the line prompt=no to the [req] section and my request ran without error. like this:

`[req]
distinguished_name=req_distinguished_name
req_extensions = v3_req
prompt = no`

Hope this helps!

**Comment by levitte** [comment]
This isn't a bug.  What happens when you just press Enter on all prompts where no default is given, you end up with an empty subject.  That's what the error complains about.

`prompt = no` is exactly the right way to handle things if you want to specify the DN entirely in the config file.  Or, as suggested on superuser.com, `-subj` on the command line.

**Comment by neilstuartcraig** [comment]
Hi @levitte. 
I take your point but I believe the UI is misleading and doesn't fit well with the principal of least surprise. It appears to at least me (and others based on what I have seen via Googling) that pressing <enter> will use the value shown. Compounding that is a pretty unhelpful error message when the creation of the cert fails; worth noting that the behaviour differs between ECC and RSA-based certs. I personally believe this could be relatively easily tidied up (though i fully appreciate it's not exactly earth-shattering in priority).

Does that make sense? I'd be interested to hear your thoughts on this.

Cheers

**Comment by levitte** [comment]
In a way it makes sense...  We do, however, expect people to read the manual, which says this re this business:

```
DISTINGUISHED NAME AND ATTRIBUTE SECTION FORMAT
       There are two separate formats for the distinguished name and attribute
       sections. If the prompt option is set to no then these sections just
       consist of field names and values: for example,

        CN=My Name
        OU=My Organization
        emailAddress=someone@somewhere.org

       This allows external programs (e.g. GUI based) to generate a template
       file with all the field names and values and just pass it to req. An
       example of this kind of configuration file is contained in the EXAMPLES
       section.

       Alternatively if the prompt option is absent or not set to no then the
       file contains field prompting information. It consists of lines of the
       form:

        fieldName="prompt"
        fieldName_default="default field value"
        fieldName_min= 2
        fieldName_max= 4
...
```

It's not like we're making it a mystery...  I can understand, though, if it's not particularly intuitive for those who haven't read the manual.

I agree, though, that the error message isn't the best (read: it's actually quite bad)...  so that could change to something better.

**Comment by mghatiy** [comment]
Below worked for me, without creating any config.
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout "cert.key" -out "cert.pem" -subj "/"

**Comment by awarre** [comment]
> In a way it makes sense... 

No, it doesn't.

> It's not like we're making it a mystery...

Yes, you are.

The user experience is terrible. Fix it.

**Comment by dcolakchile** [comment]
Jesus christ, I lost FOUR HOURS trying to add subject alternative name... Still NO GO.

Are you guys crazy?!

**Comment by m1stermanager** [comment]
yeah i'm here on purpose and I can't make heads or tails of whats going on. not _great_?

**Comment by amayii0** [comment]
Just found this trying to find documentation for config file options.
This is awful, for anyone finding this, have a look at : https://apfelboymchen.net/gnu/notes/openssl%20multidomain%20with%20config%20files.html

**Comment by jeremyakers** [comment]
I just ran into this again: (It's very easy to forget about this little nuance unless you use these tools on a regular basis)
```
$ openssl req -key private.key.pem -new -sha256 -out csr.pem -config csr.cnf 
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
US []:
```
The message from the tool specifically says "For some fields there will be a default value,
If you enter '.', the field will be left blank." which pretty clearly implies that hitting "enter" will use the default value that's present in the config file, and that you have to enter a PERIOD to get a blank value if that's what's desired.

So this is either a bug in the behavior, or a bug in the displayed message. Either way I find it hard to accept the argument that this isn't a bug. The behavior doesn't match the message that's presented to the user. So either the message or wrong, or the behavior is wrong. Which is it?

**Comment by Arkady-Karasin** [comment]
> Below worked for me, without creating any config. openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout "cert.key" -out "cert.pem" -subj "/"

I did with config, but received an error. -subj "/" solved my problem.

**Comment by gongfan99** [comment]
I got the same problem and ended up here. Yes, the user should read the manual. But the user experience is horrible.

**Comment by ScottABrown** [comment]
openssl is a maze of twisty passages. I've worked with it fairly extensively and still find the CLI inscrutable, the documentation obtuse, and usage completely unintuitive. I laugh at someone above who said "just read the docs". The docs are at best a messy demonstration of the principle "people who don't know the difference between notes to remind people who already have a deep understanding and actual documentation shouldn't write documentation".

No one *likes* openssl documentation. We do our best to tolerate it.

**Comment by RT-Tap** [comment]
I am so glad i found this thread i was beginning to think I was stupid.

**Comment by MrRubberDucky** [comment]
Hi to everyone from search engines, I'm one of them...
