### ISSUE TITLE
rfc3161 implementation in openssl: Wrong OID for id-smime-aa-signingCertificateV2  pulled from  771

### ISSUE THREAD

**Issue by brauckmann** [openssl/openssl#3537]
I think you merged the wrong OID into openssl master with pull request 771 https://github.com/openssl/openssl/pull/771

The OID for  id-smime-aa-signingCertificateV2 that was pulled:

https://github.com/kleinmrk/openssl/blob/cert_id_v2/crypto/objects/objects.txt#L297

`id-smime-aa 30`

The OID for id-smime-aa-signinCertificateV2 in RFC 5035:
https://tools.ietf.org/html/rfc5035#section-5.4.1

`  id-aa-signingCertificateV2 OBJECT IDENTIFIER ::= { iso(1)  member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs9(9)  smime(16) id-aa(2) 47 }`

The wrong OID has the effect that openssl cannot generate standard conformant SHA-2-signed timestamps and cannot verify timestamps with SHA-2 signatures generated by other applications.

**Comment by richsalz** [comment]
thanks, fixed!
