### ISSUE TITLE
openssl-1.1.0-latest.tar.gz is no longer available

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#3560]
Sometime between 1.1.0e and 1.1.0f the download link https://www.openssl.org/source/openssl-1.1.0-latest.tar.gz was disabled. This link was very useful for being able to fetch the latest version via CI tooling after a new release occurred. Without it a CI process requires input of the updated release value rather than just triggering when a new announcement goes out. It would be nice to retain the `latest` download link, or, failing that, a simple endpoint that can identify the latest version of a given release series (e.g. not screen scraping openssl.org's front page :smile:)

**Comment by mattcaswell** [comment]
Oops. Mea culpa. We had a problem during the release and it looks like this link was a casualty. I just fixed it but it may take a couple of hours to propagate.

**Comment by reaperhulk** [comment]
Thanks @mattcaswell!
