### ISSUE TITLE
https://openssl.org/source/openssl-1.0.2h.tar.gz is no longer available

### ISSUE THREAD

**Issue by backmeupplz** [openssl/openssl#3561]
I might be missing something, but this source is used by one of our iOS project dependencies and recently it disappeared :'( is there a way to get https://openssl.org/source/openssl-1.0.2h.tar.gz work again or is this change permanent?

**Comment by kroeckx** [comment]
It has moved to the old directory: https://www.openssl.org/source/old/1.0.2/openssl-1.0.2h.tar.gz

But I suggest you use the latest 1.0.2 release.

**Comment by mattcaswell** [comment]
Actually it should still be available under the old URL too. I just fixed it but it may take a couple of hours to propagate.
