### ISSUE TITLE
cms decrypt corrupts binary payload

### ISSUE THREAD

**Issue by someshi** [openssl/openssl#3571]
EnvelopedData with binary cleartext payloads get corrupted upon decryption using the cms commandline app in version 1.1.0f

To reproduce:
Input payload is a valid ASN.1 structure so the following parses correctly
`openssl asn1parse -in binaryfile -inform DER`

Create an envelopedData block using either openssl 1.0.2L or 1.1.0f
`openssl cms -encrypt -in binaryfile -binary -outform DER -out envdata recipient.crt`

...and decrypt it
`openssl1.1.0f\openssl cms -decrypt -in envdata -inform DER -recip recipient.crt -inkey recipient.key -out envdata_dec_ossl110f`

`openssl1.0.2l\openssl cms -decrypt -in envdata -inform DER -recip recipient.crt -inkey recipient.key -out envdata_dec_ossl102l`

`binaryfile` and `envdata_dec_ossl102l` match and
`openssl asn1parse -in envdata_dec_ossl102l -inform DER` parses correctly

`binaryfile` and `envdata_dec_ossl110f` do not match  and
`openssl asn1parse -in envdata_dec_ossl110f -inform DER` gives 
`Error in encoding
35548:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:crypto\asn1\asn1_lib.c:91:`
Part of the parsed structure is correct and probably some extraneous character is getting embedded a few blocks down.

Note that decryption is successful with both versions of openssl. I was also able to decrypt the ephemeral key (using `rsautl -decrypt`) and decrypt the content (using for e.g. `aes-128-cbc -d`) and it seemed to work correctly for both versions of openssl. Running `cms -decrypt` is where the differences show up.

**Comment by richsalz** [comment]
Just to clarify, the "envdata" you get out from step one does not match the "envdata_dec" you get from the second step?

Or are you saying that the envdata in 1.1.0 is not the same as the envdata in 1.0.2?  (That's to be expected, the key is random each time)

**Comment by someshi** [comment]
Sorry I made a mistake in the question, comment updated above. Essentially the input to `cms -encrypt` does not match the output from `cms -decrypt`

**Comment by snhenson** [comment]
What happens if you pass `-binary` to `cms -decrypt`?

**Comment by someshi** [comment]
Thank you, it works if `-binary` is passed to the decrypt command!!
As happens in these situations sometimes, I could swear that I tried it before but ...
