### ISSUE TITLE
Calling SSL callbacks (not the CTX) is breaking wpa_supplicant (possibly other software)

### ISSUE THREAD

**Issue by lsiudut** [openssl/openssl#3594]
https://github.com/openssl/openssl/pull/2870 is breaking wpa_supplicant (and possibly other software that uses openssl). You can check for context Arch Linux bug tracker https://bugs.archlinux.org/task/54233 .

I reverted the change and rebuild openssl - it fixed the issue. I don't really understand the context of this diff - can one of you take a look on it and evaluate whether it's really necessary / performed in correct manner?  It looks like it changes compatibility with already existing software. 

Let me know if you need more details.

**Comment by mattcaswell** [comment]
Hmm. There are two copies of the default_password_callback pointers. One held in the SSL_CTX and one held in the SSL object. When the SSL object is created the value for the default_password_callback is initialised from the SSL_CTX one. This then gives you the flexibility to be able to change the callback on a per SSL basis should you wish to. It should not break existing applications because (unless you explicitly override it at an SSL level), the value held in the SSL object should be the same one held in the SSL_CTX (due to the initialisation when the SSL object is created). This was clearly the intention when the code was originally written, but the bug fixed by #2870 meant that the SSL_CTX version was always used regardless of what you have set at an SSL level.

The only scenarios I can think of where this would cause breakage are:

1) An application is explicitly overriding the callback on a per SSL basis to something incorrect

2) An application is changing the callback in the SSL_CTX *after* the SSL object has been created

In the case of (1) this seems to me like a latent bug in the application that was previously masked by the OpenSSL bug.

In the case of (2), changing the SSL_CTX after you have created SSL instances is generally an unwise thing to do. A similar argument could be made to say that this is a latent bug in the application masked by the OpenSSL bug.

Do either of the above 2 scenarios apply in the wpa_supplicant case? Or is something else unexpected going wrong?

**Comment by lsiudut** [comment]
@mattcaswell it makes sense, I guess the (2) applies here:
```
SSL_CTX_set_default_passwd_cb(ssl_ctx, tls_passwd_cb);
SSL_CTX_set_default_passwd_cb_userdata(ssl_ctx, passwd);
if (
    SSL_CTX_use_PrivateKey_file(ssl_ctx, private_key,
                                SSL_FILETYPE_ASN1) != 1 &&
    SSL_CTX_use_PrivateKey_file(ssl_ctx, private_key,
                                SSL_FILETYPE_PEM) != 1 &&
    tls_read_pkcs12(data, NULL, private_key, passwd)) {
```
The names of functions used do suggest that it should work though - `set_default_passwd_cb`, `set_default_passwd_cb_userdata`?

Link to related code http://w1.fi/cgit/hostap/tree/src/crypto/tls_openssl.c#n2920 .

I can definitely let them know that it needs to be fixed but since change in OpenSSL broke wpa_supplicant I'd also like to confirm and understand why this is wrong approach.

**Comment by mattcaswell** [comment]
Well that code does not seem to be an instance of (2) as far as I can tell and I can't think of a good reason why #2870 would break that. The change in that PR only amends the functions SSL_use_certificate_file(), SSL_use_RSAPrivateKey_file() and SSL_use_PrivateKey_file(), i.e. it only changed the SSL versions not the SSL_CTX versions. None of the amended functions are called either directly or indirectly by the above wpa_supplicant code.

**Comment by lsiudut** [comment]
Can you follow up on this? I guess that more applications may be broken in a way similar to wpa_supplicant once 1.1.0f is widely deployed/installed.

If you can't then I'm happy to try. In such case I'd appreciate a hint where to start though.

**Comment by mattcaswell** [comment]
Are you sure the above code is where things are failing? In the linked bug report I see this line in the log:
````
mai 29 13:28:23 mypc wpa_supplicant[3208]: OpenSSL: SSL_use_certificate_file (PEM) --> OK
````
But in the code above we see there is no call to SSL_use_certificate_file().

Basically I think the next steps are on the wpa_supplicant side to step things through and understand which of the relevant OpenSSL functions are being called, in what order. Also the expected and actual values of SSL_get_default_passwd_cb() and/or SSL_CTX_get_default_passwd_cb() are at each of those function calls.

**Comment by lsiudut** [comment]
Pretty sure - I tracked this by looking at debug output and function names. Only this one was a match. I'll follow up on that anyway and get back here, thanks for the comment!

**Comment by lsiudut** [comment]
Ok I think I have it. You were right that this was not the code, but it was mostly my mistake in paste - the code that triggered that is identical.

Here's what I think.

These functions are setting callbacks only in the context: https://github.com/openssl/openssl/blob/master/ssl/ssl_lib.c#L2847-L2855 (used here http://w1.fi/cgit/hostap/tree/src/crypto/tls_openssl.c#n2799)

Now wpa_supplicant calls this function: http://w1.fi/cgit/hostap/tree/src/crypto/tls_openssl.c#n2852 and it uses only callbacks from the SSL object https://github.com/openssl/openssl/blob/OpenSSL_1_1_0f/ssl/ssl_rsa.c#L256-L257. I guess that the problem is that callbacks in SSL object are not updated in SSL_CTX_set_default_passwd_cb function? Or is it (2) after all, when you change callbacks after SSL was initialized?

**Comment by lsiudut** [comment]
I can see that there's a different function to use the key from the context - `SSL_CTX_use_RSAPrivateKey_file` - I guess that it should be used instead... I'll give it a try later on.

**Comment by mattcaswell** [comment]
Hmm, ok so this *is* an instance of (2). The code [here](https://w1.fi/cgit/hostap/tree/src/crypto/tls_openssl.c#n2799) sets the password callback/userdata in the SSL_CTX, and then a few lines later [here](https://w1.fi/cgit/hostap/tree/src/crypto/tls_openssl.c#n2852) it attempts to use it from a pre-existing SSL object. Really the code at line 2799/2800 should be calling SSL_set_default_passwd_cb() and SSL_set_default_passwd_cb_userdata() instead.

I'm guessing the code was written like this in the first place to work around the OpenSSL bug. Unfortunately the work around broke when we fixed the bug :-(. This presents us with a bit of a dilemma. If wpa_supplicant fixes this issue to remove the work around (as per my suggestion above) it will fail if it is ever compiled against an earlier version of OpenSSL where the bug still exists.

One option is to call *both* the SSL_CTX_*() functions *and* the SSL_*() equivalent functions at line 2799/2800. This should work when using pre-bug-fix or post-bug-fix versions of OpenSSL, although it is a bit messy.

One other thought: I don't know if wpa_supplicant is multi-threaded or not. If it is and each SSL object is handled in a different thread with a shared SSL_CTX, then changing the underlying SSL_CTX password callback/userdata in this way is not going to be thread safe (but that is an existing problem irrespective of this issue in that case).

**Comment by lsiudut** [comment]
Thank you :). I'll try to contact wpa_supplicant people and let them know about the issue! I guess that this bug can be closed...

**Comment by dcbw** [comment]
> One other thought: I don't know if wpa_supplicant is multi-threaded or not. If it is and each SSL object is handled in a different thread with a shared SSL_CTX, then changing the underlying SSL_CTX password callback/userdata in this way is not going to be thread safe (but that is an existing problem irrespective of this issue in that case).

@mattcaswell wpa_supplicant is not multi-threaded, but uses an event-based callback mechanism instead.  So thread safety shouldn't be an issue.

**Comment by koeppea** [comment]
@lsiudut Have the wpa_supplicant guys reacted?

**Comment by jmalinen** [comment]
This was first addressed in the following commit:
https://w1.fi/cgit/hostap/commit/?id=f665c93e1d28fbab3d9127a8c3985cc32940824f

And after that, the use of the default_passwd_cb was actually removed completely:
https://w1.fi/cgit/hostap/commit/?id=63942cf0f309e067bc5bfef95194bd17e48bf5ef
