### ISSUE TITLE
Missing message Alert on ssl23_get_server_hello negotiation failure

### ISSUE THREAD

**Issue by vmartin-avaya** [openssl/openssl#3595]
Issue was reported earlier against OpenSSL 1.0.1l, see https://mta.openssl.org/pipermail/openssl-dev/2015-March/001020.html for details.

I am still seeing this issue in OpenSSL 1.0.2j.

Seems it was closed without resolution, see https://mta.openssl.org/pipermail/openssl-dev/2016-October/008638.html.

**Comment by mattcaswell** [comment]
I have created a fix for this issue in #3598. Its value is somewhat limited because we have failed to agree a protocol version so the server is likely to reject our alert anyway. Nonetheless that PR does bring us in line with the RFC.

**Comment by mattcaswell** [comment]
This was fixed via #3598.
