### ISSUE TITLE
CLAs use http://www.openssl.org/licenses but should use https://openssl.org/licenses

### ISSUE THREAD

**Issue by dkg** [openssl/openssl#3610]
The [individual](https://www.openssl.org/policies/openssl_icla.pdf) and [Corporate](https://www.openssl.org/policies/openssl_ccla.pdf) Contributor License Agreements both have in their header the following URL:

    http://www.openssl.org/licenses

There's a way to transmit information securely over the web, where you wrap HTTP in a Transport Layer Security (TLS) tunnel and use port 443 instead of port 80.  Have you heard of TLS?  it's pretty neat!  Perhaps the CLAs should explicitly request the use of this security feature by using `https` instead of `http` !

**Comment by levitte** [comment]
Oh, right, I think I may have heard of that feature!

**Comment by richsalz** [comment]
The cobbler's children have no shoes.  Fixed, thanks!
