### ISSUE TITLE
thread issues on thread termination

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#3615]
commit 7dca72af91936d246700b78e06def16561a36028 seems to have caused regressions in various packages in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863707
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864177
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864186

I'm not sure what is going on, but reverting that commit makes the problem go away.

**Comment by mattcaswell** [comment]
This is already fixed. See 7dca72af91 in 1.1.0.

**Comment by kroeckx** [comment]
That's the broken commit.

**Comment by kroeckx** [comment]
There is no problem with the 1.1.0e version, they fail with the 1.1.0f version

**Comment by mattcaswell** [comment]
Oh, oops sorry I meant 73bc53708. Although that's the master version. It doesn't seem to have been backported to 1.1.0 although #3592 did get approval for the backport.

**Comment by noloader** [comment]
It looks like [Issue 3584](https://github.com/openssl/openssl/issues/3584) could be related.

**Comment by richsalz** [comment]
Yes, #3592 is the fix for #3584 and I had forgotten to backport it, which I just did as commit c8ec34109cab8c92685958ddfef0776a4b3b8460
