### ISSUE TITLE
Missing error string for 4069506C:lib(64):func(1685):reason(108)

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#3616]
```
$ /usr/bin/openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
$ /usr/bin/openssl errstr 0x04069506C
error:4069506C:lib(64):func(1685):reason(108)

$ /usr/local/bin/openssl version
OpenSSL 1.0.2k  26 Jan 2017
$ /usr/local/bin/openssl errstr 0x04069506C
error:4069506C:lib(64):func(1685):reason(108)
```

And building Master:

```
$ LD_LIBRARY_PATH=. ./apps/openssl errstr 0x4069506C
error:4069506C:lib(64):func(1685):reason(108)
```

Based on the operation, I believe the `openssl errstr` should be reporting the error string for `RSAREF_F_RSA_PRIVATE_DECRYPT` and `RSA_R_DATA_GREATER_THAN_MOD_LEN`.

**Comment by InfoHunter** [comment]
What kind of operation generates this '0x4069506C' error string? The `openssl errstr` is just a simple parser that works on what you feed it (the string).

**Comment by noloader** [comment]
@InfoHunter,

See [Error when trying to RSA-decrypt a parameter string with libcrypto](https://stackoverflow.com/q/44366099/608639).

**Comment by t-j-h** [comment]
Closing this.

@noloader - your reference has the answer - just look further down.

But here is a simple answer separate from that thread - and it involves not using the typo of a seven character number and actually using the corrected version later in the thread where the original author does a ERR_load_crypto_strings() so they can see the decoded value in context.

openssl version; openssl errstr 0406506C
OpenSSL 0.9.8g 19 Oct 2007
error:0406506C:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data greater than mod len

Or off master:

OpenSSL 1.1.1-dev  xx XXX xxxx
error:0406506C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len

**Comment by noloader** [comment]
Thanks @t-j-h,

> it involves not using the typo of a seven character number and actually using the corrected version later

Something seems bent here.

Earlier version of OpenSSL required the `0x` prefix because it would treat the value as decimal rather than hexadecimal. That is, it failed to decode a decimal value. Its the reason I learned to use the `0x` prefix.

Later versions of OpenSSL cannot seem to parse a hexadecimal value. I think its noteworthy that an error code is an `unsigned long`, and that's 8 characters on most systems. Its very odd that OpenSSL cannot parse it.

**Comment by levitte** [comment]
I wonder what earlier version that is...  just looking at the code and how it parses the arguments, I see the exact same sscanf being done through all the OpenSSL history all the way back to SSLeay.  It looks like this:

``` C
        if (sscanf(argv[i], "%lx", &l)) {
```

(note, `argv[i]` is `*argv` in 1.1.0 and on, but that should make no difference at all)

**Comment by richsalz** [comment]
Please open a separate issue about this.  We tried to intuit the number correctly, the hacks/guesses/heuristics are perhaps wrong.
