### ISSUE TITLE
Setting security level in s_client and s_server

### ISSUE THREAD

**Issue by nkarstens** [openssl/openssl#3619]
It is currently not possible to use s_client / s_server to test cipher suites associated with security level 0 without recompiling. For example, older versions of OpenSSL would allow you to test ADH cipher suites by first starting the s_server:

`openssl s_server -nocert -cipher ADH`

and then using the s_client to connect:

`openssl s_client -connect localhost:4433 -cipher ADH`

Newer versions of OpenSSL introduced the concept of security levels, which may be changed using `SSL_CTX_set_security_level()` or `SSL_set_security_level()`. However, there is no way to set these for the s_client / s_server. Instead, these use the default of 1 unless OpenSSL is recompiled with a different value for `OPENSSL_TLS_SECURITY_LEVEL`.

One way to accomplish this would be to introduce a new command-line parameter to s_client / s_server that allows this to be configured. Any other ideas, or reasons this is not a good idea?

**Comment by mattcaswell** [comment]
It is already possible to do this in s_server and s_client. For your example above the equivalent commands in 1.1.0 are:

    openssl s_server -nocert -cipher "ADH:@SECLEVEL=0"

and

    openssl s_client -connect localhost:4433 -cipher "ADH:@SECLEVEL=0"

**Comment by nkarstens** [comment]
@mattcaswell -- OK, thanks!
