### ISSUE TITLE
pkcs certificate passing requires filehandle ( this is not good for secure implementation )

### ISSUE THREAD

**Issue by openfly** [openssl/openssl#3626]
In ssl/ssl_rsa.c we eventually find in the function:

BIO_read_filename(in,file) 
If you dig far enough into the BIO code (part of openssl) you'll eventually come to a normal fopen():

fp=fopen(ptr,p);
So it looks like as it's currently written. It must be in a file openable by C's fopen().

reference : https://stackoverflow.com/questions/12336239/how-to-open-ssl-socket-using-certificate-stored-in-string-variables-in-python

**Comment by richsalz** [comment]
There are other functions such as SSL_use_certificate, and so on, that do not use a file.

**Comment by openfly** [comment]
ah... good call.  thanks!
