### ISSUE TITLE
How to compile openssl without AES instruction set support?

### ISSUE THREAD

**Issue by benben2301** [openssl/openssl#3637]
Hello,

I found there is no "no-hw" option in the latest version. So if I want to compile it without any hardware instruction speedup (e.g. AES-NI ), what should I do? 

Thanks,
Hua

**Comment by richsalz** [comment]
You should not need to do this; OpenSSL determines at run-time if the instructions are available.

**Comment by benben2301** [comment]
Thanks for your reply. 
I am going to do some test on the T-table version of AES. So I want to have an AES-NI free version of openssl. So what should I do?

**Comment by benben2301** [comment]
Thanks for your reply.
I am going to do some test on the T-table version of AES. I want to have an AES-NI free version of openssl. So what should I do?

**Comment by richsalz** [comment]
So can you just use no-asm?  If not, you’ll have to edit the code.

**Comment by dot-asm** [comment]
It looks like this can be closed. If no-asm is not an option, then there is nothing we can do. Well, there is nothing we should or have to do. It sounds like kind of research query, and we don't have to facilitate overly specific ones. I mean if neither of available options do the trick, then you are on your own.
