### ISSUE TITLE
Support "copy_extensions" also with x509 CSR signing

### ISSUE THREAD

**Issue by aitrfi** [openssl/openssl#3638]
While already supported with "openssl ca", basic signing does not support the "copy_extension" mode. Basic signing might be neccessary when the "openssl ca" magic is too much and cannot be turned off in certain usecases. Thus when using "openssl x509" instead, from each CSR, a openssl.config has to be created manually by duplicating the CSR fields before signing, which makes it even more risky and error prone than using the "copy_extensions".

It would be nice to support the existing "copy_extensions = copy" feature also in for "openssl x509". (It would be even more nice, if it would allow "... = copy:subjectAltName", but that is another story ...)

**Comment by michalmedvecky** [comment]
:pray:
