### ISSUE TITLE
Cannot complete handshake with site

### ISSUE THREAD

**Issue by SergeyXP** [openssl/openssl#3652]
When calling
openssl s_client -connect skinsjar.com:443

I get the following error:
CONNECTED(00000790)
3024:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:.
.\..\openssl-1.1.0f\ssl\record\rec_layer_s3.c:1399:SSL alert number 40

**Comment by kroeckx** [comment]
I suspect this is cloudflare that is somehow sending a failure. I suggest you contact them instead.

**Comment by zhaozg** [comment]
-servername blabla

**Comment by kroeckx** [comment]
This works: openssl s_client -connect skinsjar.com:443  -servername skinsjar.com

So they just require SNI.
