### ISSUE TITLE
Command to install openssl libraries (which are compiled by own)

### ISSUE THREAD

**Issue by PravallikaKG** [openssl/openssl#3669]
I compiled the openssl code base for MIPS 32 bit Linux. Compilation is successful and the ssl, crypto libraries are generated.

Now i want to install them in my embedded device. What is the command to install?
Note: I dont want to install using apt-get command. Because i already have libraries for my platform.

Thanks In Advance.

**Comment by mattcaswell** [comment]
Use:

    make install
