### ISSUE TITLE
NULL-ptr return of BN_CTX_get is often handled differently

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#3676]
At some places all BN_CTX_get are checked for NULL,
At other places only the last BN_CTX_get is checked for NULL.

That can be confusing.

**Comment by bernd-edlinger** [comment]
By the internal logic of BN_CTX_get,
only the last return value really needs to be checked.
But the "correct" code looks surprising.

**Comment by richsalz** [comment]
Perhaps we should document that once it fails, it will always fail, so that the current behavior is documented?

**Comment by mattcaswell** [comment]
It's already documented:

    BN_CTX_get() returns a pointer to the B<BIGNUM>, or B<NULL> on error.
    Once BN_CTX_get() has failed, the subsequent calls will return B<NULL>
    as well, so it is sufficient to check the return value of the last
    BN_CTX_get() call. In case of an error, an error code is set, which
    can be obtained by L<ERR_get_error(3)>.

**Comment by richsalz** [comment]
Damn.  Wish RTFM'd before causing a hassle.  Sorry @bernd-edlinger :)

**Comment by richsalz** [comment]
BTW, that means this issue is now "only check the last one in a series of calls" :)

**Comment by bernd-edlinger** [comment]
fixed on trunk.
