### ISSUE TITLE
Are all P256 implementations constant time now?

### ISSUE THREAD

**Issue by Okinalo** [openssl/openssl#3687]
@richsalz  @dot-asm @levitte @shlomif @davidben I read about this timing attack on P-256 in OpenSSL 1.0.1u, I wondered if all P256 implementations in OpenSSL are now constant time, including the ecp_nistz256 implementations for arm, avx, ppc, sparc and x86? If so, since which version of OpenSSL? Because it is not mentioned if everything is now constant time everywhere.

**Comment by richsalz** [comment]
Look at the files you are concerned about.
Short answer is yes, I am sure they are.

**Comment by Okinalo** [comment]
@richsalz I understood that P-256 has different levels of constant-time (such as BN_MOD_INVERSE, BN_FLG_CONSTTIME, BN_mod_inverse_no_branch, ec_nistp_64_gcc_128, BN_mod_exp_mont_consttime, EC_GFp_nistz256_method) 
Could you clarify what this means and which versions of OpenSSL 0.9.6,0.9.8,0.9.7,1.0.0.,1.0.1,1.0.2,1.1.0 use completely constant time operations for P-256 and which ones do not?

**Comment by richsalz** [comment]
No, that's too much work for free support.  Consider posting on the openssl-users mailing list, https://mta.openssl.org for joining.

The only supported releases are 1.0.2 and 1.1.0
