### ISSUE TITLE
OpenSSL_1_0_2-stable will no longer compile.

### ISSUE THREAD

**Issue by sacko87** [openssl/openssl#369]
In branch `OpenSSL_1_0_2-stable`: there is no label `done` in the funtion `X509_verify_cert`. Thus it no longer compiles.

This was caused by @25efcb44ac88ab34f60047e16a96c9462fad39c1. I assume this wasn't tested before committing the change? As I am unsure whether you wanted to introduce the label or use `end`. I'll leave the change to you.

**Comment by ghedo** [comment]
This has already been fixed, but see comment at #370.

**Comment by richsalz** [comment]
see that comment, but yeah fixed.
