### ISSUE TITLE
Openssl Dtls1_2 not forcing Hello Verify Request record to v1.2

### ISSUE THREAD

**Issue by csanoop** [openssl/openssl#3696]
Hi,
I am using OpenSSL library (version 1.1.0f) to execute DTLS 1.2 server with below furnished command,

> _s_server -accept 192.168.0.2:4433 -cert server_certificate.pem -CAfile ca_certificate.pem -key server_key.pem -dtls1_2 -debug_

Even though I am forcing dtls1_2 parameter OpenSSL server is sending Hello verify request with Record Layer version as 1.0. 

One of the pre-released version "openssl-1.1.0-pre1", sends the record layer version as DTLS 1.2 for the Hello Verify request handshake message.

Why is this behavior seen only for Hello Verify request in version 1.1.0f? 

Thanks
Anoop

**Comment by mattcaswell** [comment]
The HelloVerifyRequest message is sent by a server before version negotiation happens on the connection. It is not until the ServerHello is sent that the version for the connection is decided.

Note that the server_version field inside the HelloVerifyRequest also says DTLSv1.0 as per the RFC:

    The server_version field has the same syntax as in TLS.  However, in
    order to avoid the requirement to do version negotiation in the
    initial handshake, DTLS 1.2 server implementations SHOULD use DTLS
    version 1.0 regardless of the version of TLS that is expected to be
    negotiated.  DTLS 1.2 and 1.0 clients MUST use the version solely to
    indicate packet formatting (which is the same in both DTLS 1.2 and
    1.0) and not as part of version negotiation.  In particular, DTLS 1.2
    clients MUST NOT assume that because the server uses version 1.0 in
    the HelloVerifyRequest that the server is not DTLS 1.2 or that it
    will eventually negotiate DTLS 1.0 rather than DTLS 1.2.

The record version is just consistent with the server_version field. It should have no impact on the subsequent version negotiation. (Confusingly though the spec contradicts itself about the server_version a little later on. Errata exist in this area to clear this up).

OpenSSL 1.0.2 also behaves in the same way as the current 1.1.0. If 1.1.0-pre1 behaved differently then I assume that was a bug that was subsequently fixed.

**Comment by csanoop** [comment]
As per RFC6347 and errata furnished below, update is only meant for handshake layer format.
[ https://www.rfc-editor.org/errata_search.php?rfc=6347&eid=4103]

Below reasoning for record layer server version is not seen in RFC6347 and how was this dervied?
> The record version is just consistent with the server_version field.

**Comment by mattcaswell** [comment]
Well there is no explicit guidance in RFC6347 about what the record layer version should be for the HelloVerifyRequest. However in all other messages the record layer version is either DTLS1.0 before version negotiation or the negotiated version afterwards. You can either look at it that the HelloVerifyRequest is "negotiating" DTLS1.0 (which it isn't really - but that's what appears in the server_version field) or that the version negotiation hasn't take place yet. Either way the answer is still the same: DTLS1.0.
