### ISSUE TITLE
openssl 1.0.2l (and probably since 1.0.2j) 64 bits version with mingw-w64

### ISSUE THREAD

**Issue by stephane78** [openssl/openssl#3698]
You assume in cryptlib.c and mem_dbg.c that a pointer can be casted as unsigned long which is false in 64 bits.so I try to build it with mingw-w64 64 bits version and must modify variables as unsigned long long,I am not sure that it will works well.....(I am trying to build a 64 bits debug version)

**Comment by stephane78** [comment]
problem for openssl 1.0.2j and 1.0.2l....

**Comment by stephane78** [comment]
I think I didn't have this problem for the 64 bits release version....

**Comment by mattcaswell** [comment]
Please can you provide the build steps you followed including how you run config or Configure. What problems do you see because of this? Can you be specific about what you changed in cryptolib.c and mem_dbg.c?

**Comment by stephane78** [comment]
(under msys2) ./Configure no_shared --prefix=/c/openssld debug
mingw32-make depend
then script because of a bug in make 
then ming32-make
change in cryptlib.c l 447 id->val = (unsigned long long)id->ptr; and in  crypto.h l 448 typedef struct crypto_threadid_st {
    void *ptr;
    unsigned long long val;
} CRYPTO_THREADID;
for memdbg.c not already changed  but error l 326 ret = (unsigned long)a->addr;

**Comment by stephane78** [comment]
change  l322 memdbg.c :static unsigned long long mem_hash(const MEM *a)
{
    unsigned long long ret;

    ret = (unsigned long long )a->addr;

    ret = ret * 17851 + (ret >> 14) * 7 + (ret >> 4) * 251;
    return (ret);
}
but l662 problem: BIO_snprintf(bufp, BUF_REMAIN, "number=%d, address=%08llX\n",
                 m->num, (unsigned long long)m->addr);

**Comment by stephane78** [comment]
I don't know why there is an error l662 I have put: address=%016llX\n" but there is an error on format=

**Comment by stephane78** [comment]
I don't really understand where BIO_snPrintf is defined,because I see the definition in b_print.c(_dopr) in bio but it is not compiled when I compile memdbg.c.so I don't know why I have this error l662 of memdbg.c....Need  I really to do a make depend, before the make ?

**Comment by richsalz** [comment]
For 1.0.2, you *must* do make depend before building.

**Comment by stephane78** [comment]
thank you richsalz,Ok I have already done it,I think I didn't have all these problems when I compiled the 64 bits release of 1.0.2j last year,so I think there is just problems for the 64 bits debug version

**Comment by stephane78** [comment]
I want to build a 64 bits debug version of openssl because I want to build a 64 bits debug version of Qt.does a release version of openssl work with a debug version of Qt ? Otherwise I could try to use my release version of openssl with a debug version of Qt

**Comment by mattcaswell** [comment]
> ./Configure no_shared --prefix=/c/openssld debug

This is wrong. The "debug" on the end here does not mean build OpenSSL in debug mode. It means configure for the "debug" platform. This is a developer platform (which is actually Linux). The target you need to build on mingw64 is....mingw64, i.e.

./Configure no_shared --prefix=/c/openssld mingw64

There is no debug-mingw64 target in 1.0.2.

> I want to build a 64 bits debug version of openssl because I want to build a 64 bits debug version of Qt.does a release version of openssl work with a debug version of Qt ?

It should work fine.

**Comment by stephane78** [comment]
OK thanks a lot mattcaswell,so  I have already a build ....my problem is solved
