### ISSUE TITLE
SSL_CTX_new function call makes a segment fault

### ISSUE THREAD

**Issue by eastyu** [openssl/openssl#3706]
SSL_CTX_new is invoked in every thread in my program(8 threads), sometimes it will make a segment fault. 
Here is the call stack got from core dump
> #0   0x00007fb12083becb in sha1_block_data_order_avx () from /lib64/libcrypto.so.10
> #1   0xfb3bfd659b96877f in ?? ()
> #2   0xc81ee611f0b5c695 in ?? ()
> #3   0xcd398997da12b4ec in ?? ()
> #4   0x5075877299b5ea28 in ?? ()
> #5   0x7ac6b2810b09dffa in ?? ()
> #6   0x68610feb4572c6d8 in ?? ()
> #7   0xacbba14256845c39 in ?? ()
> #8   0xddf6916b944f7b4b in ?? ()
> #9   0x00007fb120bad8ba in ?? () from /lib64/libcrypto.so.10
> #10 0x00007fb110001560 in ?? ()
> #11 0x0000000000000005 in ?? ()
> #12 0x00007fb12083833f in SHA1_Update () from /lib64/libcrypto.so.10
> #13 0x00007fb1208ac4f6 in ssleay_rand_add () from /lib64/libcrypto.so.10
> #14 0x00007fb1208ac7b5 in ssleay_rand_bytes () from /lib64/libcrypto.so.10
> #15 0x00007fb120bf4ce3 in SSL_CTX_new () from /lib64/libssl.so.10_

**Version**:
> OpenSSL 1.0.1e-fips 11 Feb 2013
> built on: Mon Feb 20 14:38:48 UTC 2017
> platform: linux-x86_64
> options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
> compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
> OPENSSLDIR: "/etc/pki/tls"
> engines:  rdrand dynamic

**OS**:
> Linux CentOS7 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by richsalz** [comment]
It is most likely that you have a pointer bug in your program.
It is also possible that SSL_CTX_new calls functions that is not not thread-safe.
You can put a block/mutex around calls to SSL_CTX_new and see if that fixes the problem?

**Comment by richsalz** [comment]
I didn't even notice that you're using 1.0.1.  That's no longer a supported release.  Try upgrading.

**Comment by eastyu** [comment]
How can I know which functions are thread-safe or not? Is there any document for this?

**Comment by eastyu** [comment]
After upgrading to version 1.1.0, the issue seems to disappear.
