### ISSUE TITLE
SSL_connect block for a long time

### ISSUE THREAD

**Issue by benghopy** [openssl/openssl#3715]
Using the openssl-1.0.2e, if you limit you network, and make a connect to a ssl server, but the SSL_connect block for a long long time!!!

**Comment by richsalz** [comment]
can you get a packet trace?
this is almost definitely NOT an openssl issue.

**Comment by benghopy** [comment]
Can you give me an example to use nonblock socket to make a ssl connect.

**Comment by InfoHunter** [comment]
There are lots of examples, like this one: https://github.com/nginx/nginx/blob/master/src/event/ngx_event_openssl.c#L1224

**Comment by mattcaswell** [comment]
Not an OpenSSL issue. Closing.
