### ISSUE TITLE
OpenSSL OCSP Responder don't start anymore

### ISSUE THREAD

**Issue by DBLouis** [openssl/openssl#3719]
I used OpenSSL OCSP server for about a week and it worked fine. Today I upgraded my system and after a reboot it failed to start.

Here is the command used to start the service:

    openssl ocsp -index <index.txt> -port 127.0.0.1:2560 -sha256 -CA <ca-chain.pem> -rkey <ocsp.key.pem> -rsigner <ocsp.cert.pem>

Now I get this error:

    Can't parse "127.0.0.1:2560" as a number

If I change to just `-port 2560` I get:

    Digest must be before -cert or -serial

openssl version:
OpenSSL 1.1.0f  25 May 2017

**Comment by InfoHunter** [comment]
`-port` requires a number, so you cannot pass a "ip:port" string to it.

**Comment by DBLouis** [comment]
It worked before the upgrade

**Comment by InfoHunter** [comment]
Hmm, it seems 1.1.0f requires either `-cert` or `-serial` should be specified if `-md` is used...

**Comment by DBLouis** [comment]
But `-cert` and `-serial` are client options, that doesn't make any sense, does it?

**Comment by InfoHunter** [comment]
According to the docs (`man ocsp`), `-[digest]` is also a client option. I think you should just simply remove that `-sha256` in your command.

**Comment by InfoHunter** [comment]
What version of OpenSSL do you use before upgrading to 1.1.0f?

**Comment by levitte** [comment]
I'm guessing the pre-upgrade version was 1.0.2*something*.  It's true that the `-port` argument then took a full *host*:*port* combo.  This has changed for 1.1.0, it seems.  Frankly; I can understand why, considering the name.  It might be a good idea to have a `-listen` parameter that could take the combo...  or restore the old `-port` behavior, even though it's not the best option name...

**Comment by InfoHunter** [comment]
It might be good if `ocsp` could be separated into two apps to avoid confusing and reduce code complicity.

**Comment by mattcaswell** [comment]
This doesn't seem to be a bug, so closing.
