### ISSUE TITLE
SIGSEGV in subcall from FIPS_drbg_generate()

### ISSUE THREAD

**Issue by lonewasp** [openssl/openssl#3721]
Openssl 1.0.2j (checking against openssl-fips-2.0.16):

openssl-fips-2.0.16/fips/rand/fips_drbg_hash.c -> drbg_hash_generate() -> hash_gen() does not check for FIPS_digestinit() exit code probably resulting in SIGSEGV on memory tight system (failed to allocate ctx->md_data).

(gdb) bt
#0  0x00007f9bdf767d50 in ?? ()
#1  0x00007f9be0d1f15e in ?? () from /crash/libcrypto.so.1.0.2
#2  0x00007f9be0d1f64c in ?? () from /crash/libcrypto.so.1.0.2
#3  0x00007f9be0d1c9f0 in FIPS_drbg_generate () from /crash/libcrypto.so.1.0.2
#4  0x00007f9be0d20e1f in ?? () from /crash/libcrypto.so.1.0.2
#5  0x00007f9be0a06652 in ssl3_get_client_key_exchange () from /crash/libssl.so.1.0.2
#6  0x00007f9be0a09217 in ssl3_accept () from /crash/libssl.so.1.0.2
...

and

(gdb) bt
#0  0x00007f8153114d50 in ?? ()
#1  0x00007f81542c115e in ?? () from /crash/libcrypto.so.1.0.2
#2  0x00007f81542c164c in ?? () from /crash/libcrypto.so.1.0.2
#3  0x00007f81542be9f0 in FIPS_drbg_generate () from /crash/libcrypto.so.1.0.2
#4  0x00007f81542c2e1f in ?? () from /crash/libcrypto.so.1.0.2
#5  0x00007f8153fcff7f in SSL_CTX_new () from /crash/libssl.so.1.0.2
...

**Comment by SteveMarquess** [comment]
Unfortunately this is not fixable due to the prohibition to changes to "cryptographically significant" code. Noted in README.wishlist in OpenSSL-fips-2_0-dev.

**Comment by richsalz** [comment]
Closing per @SteveMarquess
