### ISSUE TITLE
On 1.1.0f with SCTP support enabled the DTLS support is broken

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#3723]
When the openssl-1.1.0f is compiled with the SCTP support enabled, the DTLS does not work.
I've tested it with unpatched upstream sources on Fedora.

In Terminal 1: 
openssl s_server -cipher ALL -nocert -accept 5555 -state  -dtls
Using default temp DH parameters
ACCEPT
SSL_accept:before SSL initialization
SSL_accept:before SSL initialization
SSL_accept:SSLv3/TLS read client hello
SSL_accept:DTLS1 write hello verify request

In Terminal 2:
openssl s_client -cipher ALL -connect 127.0.0.1:5555 -dtls
CONNECTED(00000003)

And the connection is stuck.

With the SCTP disabled on build, everything works normally.

**Comment by mattcaswell** [comment]
Looks like the bug is in bio.h:

    # define BIO_CTRL_DGRAM_SET_PEEK_MODE      50

    # ifndef OPENSSL_NO_SCTP
    /* SCTP stuff */
    #  define BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE    50

These CTRL values are supposed to be unique, but here there is a clash between BIO_CTRL_DGRAM_SET_PEEK_MODE and BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE. The code issues the latter unconditionally when using DTLS with the reasoning that it will be ignored if we're not in non-SCTP DTLS. Unfortunately it isn't due to this clash. It ends up setting the BIO into peek mode so it never clears anything from the underlying socket and keeps reading the same data over and over - throwing it away as a replay.

**Comment by mattcaswell** [comment]
The simplest solution would be to change BIO_CTRL_DGRAM_SET_PEEK_MODE to a unique value. Unfortunately that then has binary compatibility problems. Any application using BIO_CTRL_DGRAM_SET_PEEK_MODE would suddenly break. An alternative is to leave the clash (which is a bit yucky) and to ensure that libssl doesn't use BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE unconditionally.

**Comment by t8m** [comment]
Is there any real use of BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE outside of the OpenSSL DTLS implementation itself? If not, it could be changed.

**Comment by mattcaswell** [comment]
I don't know. Probably not. There's also probably not any real usage of BIO_CTRL_DGRAM_SET_PEEK_MODE either because it is quite new. However we can't say for sure. I think I have a work around though that will solve the binary compatibility issue. Fix coming up.

**Comment by t8m** [comment]
Or you can add 50 as a compatibility value for the BIO_CTRL_DGRAM_SET_PEEK_MODE (keep it working for the 50 but add a new non-conflicting value)

**Comment by mattcaswell** [comment]
> Or you can add 50 as a compatibility value for the BIO_CTRL_DGRAM_SET_PEEK_MODE (keep it working for the 50 but add a new non-conflicting value)

Exactly the work around I was referring to. Fix in #3724

**Comment by mattcaswell** [comment]
@t8m please could you verify #3724 solves your issue?

**Comment by t8m** [comment]
Heh I meant it the other way but wrote it this way :( 
Change the value of BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE but keep it reacting to the old 50 value.

**Comment by t8m** [comment]
The #3724 solves the issue. I however see the anonymous ciphersuites not working for some reason but that is unrelated.
