### ISSUE TITLE
Anonymous ciphersuites do not work on 1.1.0f

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#3737]
I am unable to make anonymous ciphersuites to work with 1.1.0f although they seem to be enabled.

How to reproduce:

apps/openssl ciphers -v AECDH-AES256-SHA
AECDH-AES256-SHA        TLSv1 Kx=ECDH     Au=None Enc=AES(256)  Mac=SHA1

Terminal1:
apps/openssl s_server -cipher AECDH-AES256-SHA -nocert -accept 5555 -state
Using default temp DH parameters
ACCEPT
SSL_accept:before SSL initialization
SSL_accept:before SSL initialization
SSL3 alert write:fatal:handshake failure
SSL_accept:error in error
ERROR
140498707957312:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:1404:
shutting down SSL
CONNECTION CLOSED

Terminal2:
apps/openssl s_client -cipher AECDH-AES256-SHA -connect localhost:5555
CONNECTED(00000003)
140251809580608:error:141640B5:SSL routines:tls_construct_client_hello:no ciphers available:ssl/statem/statem_clnt.c:800:

Running with openssl client 1.0.2k to the server from Terminal1:
openssl s_client -cipher AECDH-AES256-SHA -connect fedoratest:5555
CONNECTED(00000003)
140305975601016:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:

**Comment by mattcaswell** [comment]
Try adding ":@SECLEVEL=0" to the end of your ciphersuite string and check the docs here:

https://www.openssl.org/docs/man1.1.0/apps/ciphers.html

https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_get_security_level.html

**Comment by t8m** [comment]
Ah, ok, this makes it to work. However I'd say that the documentation of this should be more prominent. And I am also unsure whether the anonymous ciphersuites actually belong to the SECLEVEL 0 if for example authentication is achieved by other means.
What's confusing is that even explicitly selecting the anonymous ciphersuite does not work.

**Comment by t8m** [comment]
Also another confusing thing is that s_server will happily start but it will not support any cipher.
