### ISSUE TITLE
Conversion to/from OpenSSL cipher names and RFC cipher names

### ISSUE THREAD

**Issue by Scottmitch** [openssl/openssl#3747]
#### Summary
OpenSSL has its own naming convention for ciphers which differs from cipher names defined in the various RFCs. Applications which must support RFC cipher names (e.g. Netty/Conscrypt) and OpenSSL cipher names currently implement a custom conversion routine. As OpenSSL's rules and format for the custom cipher names change libraries must play catchup and may be buggy [1]. Since OpenSSL introduces this custom naming convention it seems appropriate to provide a reliable conversion routine to/from RFC cipher names and OpenSSL cipher names to reduce duplication and ensure correctness.

#### Converting to RFC cipher names (from an SSL_CIPHER structure)
`SSL_CIPHER_standard_name` is currently available only when building with `enable-ssl-trace`. Is it possible to make this method always available?

#### Converting to OpenSSL cipher names (from RFC cipher names)
I am not aware of anything offered by OpenSSL which does this. If there is a means todo this could someone point it out, and if not then please consider the following approaches:
- Accepting standard cipher names in public APIs that deal with ciphers; and/or
- Provide a means to convert from standard cipher names to OpenSSL cipher names.

BoringSSL will provide make similar changes [2] ... would OpenSSL consider doing the same?

[1] https://github.com/netty/netty/pull/6875
[2] https://boringssl-review.googlesource.com/c/17324

**Comment by Scottmitch** [comment]
Also please consider:

- Accepting standard cipher names in public APIs that deal with ciphers; and/or
- Provide a means to convert from standard cipher names to OpenSSL cipher names.

**Comment by InfoHunter** [comment]
Seems this guy has fixed the ChaCha20 naming issue: #3748

**Comment by InfoHunter** [comment]
Ha, glad to meet you. I just noticed My bad, didn't read your PR carefully, just noticed it's in the 'trace' part.

**Comment by InfoHunter** [comment]
So @davidben do you have a plan to create a PR to make `SSL_CIPHER_standard_name` always available as what you have done in https://boringssl-review.googlesource.com/c/17324 (adding a ''standard name field in `ssl_cipher_st` and not maintain the static cipher string table in 'trace' code is a good idea, this is what I exactly intend to do either)

**Comment by davidben** [comment]
I don't intend to put one together myself, no.

**Comment by Scottmitch** [comment]
Note that I updated the title and issue description to provide more context.

**Comment by schwabe** [comment]
OpenVPN currently maintains its own translation table to have the same names for both mbedtls and OpenSSL. If OpenSSL would gain a feature/way to query RFC cipher names, we would appricate that.

https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/ssl.c#L113

**Comment by daurnimator** [comment]
lua-http likewise carries such a map: https://github.com/daurnimator/lua-http/blob/e79ad71c14a7b734280e40744bd9a5c2267e1444/http/tls.lua#L69-L408

**Comment by mattcaswell** [comment]
Linked PR was merged so closing.
