### ISSUE TITLE
Installation error for 1.0.2.l.tar.gz - Unsupported 16-Bit Apllication Error 

### ISSUE THREAD

**Issue by BarryCheema** [openssl/openssl#3752]
When trying to install the above version I get the error message The program or feature "filepath\install.com" cannot start or run due to incompatibility with 64-bit versions of Windows.  Please contact the software vendor to ask if a 64-bit Windows compatible version is available.

We only have 64-bit Microsoft Office.  How can I install this.  We need to create some keys and this is the only software HMRC will accept us creating them from?

**Comment by BarryCheema** [comment]
Then get a message saying version of this file is not compatible with the version of Windows you're running.  Check your computers system information to see whether you need an x86 (32-bit_ ot x64 (64-bit_ version of the program.

**Comment by mattcaswell** [comment]
How are you trying to install? The above file is a compressed archive of the source code for OpenSSL - you have to compile it yourself. We do not distribute OpenSSL in executable form, although there are third parties that do. You may want to check this link: https://www.openssl.org/community/binaries.html

**Comment by BarryCheema** [comment]
Hi Matt, 

Sorry for the delay in getting back to you.  Thanks for the comment.  I Have been able to get a binary that worked for us.  Many thanks.
