### ISSUE TITLE
openssl config failed

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [openssl/openssl#3764]
# openssl config failed

> openssl config failed: error:02001003:system library:fopen:No such process

https://github.com/xgqfrms-gildata/App001/issues/3

what's wrong with that?

![echo openssl_conf](https://user-images.githubusercontent.com/18028768/27515359-1abf3cbe-59d4-11e7-8c78-9da66430e946.png)
![openssl -not works](https://user-images.githubusercontent.com/18028768/27515360-1ac0d204-59d4-11e7-939f-82eafd9be621.png)

**Comment by xgqfrms-GitHub** [comment]
https://gist.github.com/xgqfrms-gildata/5acc4a357722e9e2636009fbd6846338#gistcomment-2132092

**Comment by richsalz** [comment]
Are you sure the file exists?

**Comment by xgqfrms-GitHub** [comment]
No, I can't find it on my `C` disk!

but, why I can get the `$ echo %OPENSSL_CONF%`!

https://stackoverflow.com/questions/7360602/openssl-and-error-in-reading-openssl-conf-file

**Comment by richsalz** [comment]
So the error message is correct -- your environment points to a file that does not exist.

As for why the variable is set in your environment, I don't know.  But this does not seem to be an OpenSSL issue.

**Comment by xgqfrms-GitHub** [comment]
I didn't delete anything,  fewer days ago it all works!

I'm very confused with this, should I reinstall OpenSSL ?

**Comment by xgqfrms-GitHub** [comment]
# OpenSSL for Windows10

> https://wiki.openssl.org/index.php/Binaries

https://sourceforge.net/projects/openssl/

https://www.conan.io/search?q=OpenSSL
https://www.conan.io/source/OpenSSL/1.0.2g/lasote/stable
https://github.com/conan-io/conan


https://www.openssl.org/community/binaries.html

http://gnuwin32.sourceforge.net/packages/openssl.htm

> Win32, i.e. MS-Windows 95 / 98 / ME / NT / 2000 / XP / 2003 / Vista / 2008 with msvcrt.dll and msvcp60.dll.

**Comment by xgqfrms-GitHub** [comment]
# `$ set OPENSSL_CONF=C:\OpenSSL\bin\openssl.cnf`

https://github.com/xgqfrms-gildata/App001/issues/3#issuecomment-310907266

https://github.com/xgqfrms-gildata/App001/issues/3#issuecomment-310907406

**Comment by xgqfrms-GitHub** [comment]
# everything now is OK!
![openssl cnf ok-new](https://user-images.githubusercontent.com/18028768/27517388-52028c24-59fe-11e7-9407-5aace0ea638c.png)

**Comment by drwasho** [comment]
For anyone else stumbling onto the same problem but the above command didn't work, it may be because you installed the Win64 version of OpenSSL... so try this instead:

`set OPENSSL_CONF=C:\OpenSSL-Win64\bin\openssl.cnf`
