### ISSUE TITLE
tsget: call undefined subroutine &WWW::Curl::Easy::global_cleanup

### ISSUE THREAD

**Issue by petterreinholdtsen** [openssl/openssl#3765]
This issue is also reported as https://bugs.debian.org/742553 .

When trying to use tsget to fetch a trusted timestamp, the script fail
with an error because it call a undefined subroutine.  I test using this
script:
```
  #!/bin/sh
  set -e
  url="http://zeitstempel.dfn.de"
  openssl ts -query -data "$1" -cert | tee $1.tsq \
    | /usr/lib/ssl/misc/tsget -h "$url" -o $1.tsr
  openssl ts -reply -in "$1.tsr" -text
```
When I run it, after installing the libwww-curl-perl package, I get the
following output. Notice the perl error:
```
  % sh -x ./timestamptrust ./timestamptrust
  + set -e
  + url=http://zeitstempel.dfn.de
  + openssl ts -query -data ./timestamptrust+  -cert
  tee ./timestamptrust.tsq
  + /usr/lib/ssl/misc/tsget -h http://zeitstempel.dfn.de -o ./timestamptrust.tsr
  Undefined subroutine &WWW::Curl::Easy::global_cleanup called at /usr/lib/ssl/misc/tsget line 196
  %
```

As far as I can tell, the call to WWW::Curl::Easy::global_cleanup can be
removed.

**Comment by levitte** [comment]
Looking at it, I can't see why we have that call.

**Comment by levitte** [comment]
The fix has now been applied in all active branches
