### ISSUE TITLE
Possible upstream bug: under version 1.1.0.f relating to cert signing

### ISSUE THREAD

**Issue by graysky2** [openssl/openssl#3767]
I am unable to connect to my openvpn server on a new box (client and server both run Arch x86_64). I believe that OpenVPN is rejecting a self-signed CA signature now whereas it did not in the past. Around November of 2016 when Arch Linux was running on openssl-1.0.2j, I did not experience this issue generating my openvpn files under that version. For example, multiple servers I created then still works to this day using the identical procedure with Easy-RSA to generate the key/certs [documented here](https://wiki.archlinux.org/index.php/Easy-RSA).

Excerpt from openvpn client trying to connect:
```
VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=ease CA
OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

It has been suggestion that potentially, this change in behavior could be due to an upstream bug with openssl-1.1.  I am not knowledgeable enough to pinpoint recognizing that multiple factors might be to blame (me, openvpn, openssl, or something else).

Links to complete logs:
[openvpn server log](https://bugs.archlinux.org/task/54589?getfile=15371)
[openvpn client log](https://bugs.archlinux.org/task/54589?getfile=15372)

**Comment by schwabe** [comment]
Upstream OpenVPN author here. Old easy-rsa generated certificates with md5 signatures.

**Comment by graysky2** [comment]
> Upstream OpenVPN author here. Old easy-rsa generated certificates with md5 signatures.

The problem was with me (typo) using the wrong crt to generate my client.conf.  See: https://community.openvpn.net/openvpn/ticket/907

Thank you for the reply.
