### ISSUE TITLE
IPv6 support for BIOS APIs

### ISSUE THREAD

**Issue by vinitjain123** [openssl/openssl#377]
This issue is related to Ipv6 support for Bios socket source/sink APIs.
 I am using opnessl v 0.9.8za and observed Bios API support only IPv4. 

OpenSSL/0.9.8za/Src/crypto/bio/bss_conn.c +202
case BIO_CONN_S_CREATE_SOCKET:
                        /* now setup address */
                        memset((char *)&c->them,0,sizeof(c->them));
                        c->them.sin_family=AF_INET;
                        c->them.sin_port=htons((unsigned short)c->port);
                        l=(unsigned long)
                                ((unsigned long)c->ip[0]<<24L)|
                                ((unsigned long)c->ip[1]<<16L)|
                                ((unsigned long)c->ip[2]<< 8L)|
                                ((unsigned long)c->ip[3]);
                        c->them.sin_addr.s_addr=htonl(l);
                        c->state=BIO_CONN_S_CREATE_SOCKET;

I am planing to add support for Ipv6.
Please confirm if this patch will be acceptable in OpenSSL.

**Comment by mattcaswell** [comment]
IPv6 support will not be added to 0.9.8. Only important security fixes are being applied to that branch, and support will end completely at the end of this year. @kroeckx has been working on equivalent patches for the master branch. You should check with him before doing work on IPv6 support.
