### ISSUE TITLE
digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:531

### ISSUE THREAD

**Issue by reset12** [openssl/openssl#3774]
There is an incompatibility between the openssl Version OpenSSL 1.1.0f and OpenSSL 1.0.2m-dev.

I have encrypted some files on my laptop with openssl on Ubuntu 16.04 and debian 8 and migrated now to Debian 9.  After the migration to debian 9 with openssl 1.1.0f i got the error in the title and was no more be able to decrypt my files.  I must install a older version of openssl to decrypt my files.
You can test ist with the following Script:
#!/bin/bash
echo "Test openssl with different Versions"
dsnin="/tmp/testfile.txt"
echo "Testfile for openssl" >$dsnin
cat $dsnin
openssl version
openssl aes-256-cbc -a -salt -k 12345678 -in $dsnin -out $dsnin.enc
echo "File after decrypt"
/home/xx/opt/bin/openssl version
/home/xx/opt/bin/openssl aes-256-cbc -d -a -k 12345678 -in $dsnin.enc -out $dsnin
cat $dsnin

The output when i running this script is:
./testopenssl.sh 
Test openssl with different Versions
Testfile for openssl
OpenSSL 1.1.0f  25 May 2017
File after decrypt
OpenSSL 1.0.2m-dev  xx XXX xxxx
bad decrypt
140633576617624:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:531:

Caution: This script is testing the opposit way as my error is, because i get the error from old to new version. There should be no difference in the Data between Versions, because the user could not decrypt all files and encrypt it again, every time a new update arrives.

**Comment by richsalz** [comment]
The default digest changed from MD5 to SHA256.  So add "-digest md5" to 1.1.0 if you need compatibility with older versions or data.

**Comment by richsalz** [comment]
sorry, I mean use the "-md" flag.
