### ISSUE TITLE
LoadLibrary / FreeLibrary behavior on Windows with static build in DLL

### ISSUE THREAD

**Issue by chrisd1100** [openssl/openssl#3777]
I have OpenSSL statically compiled into a shared object (DLL) on Windows (Windows 10 x86-64). This SO is dynamically loaded into my application via `LoadLibrary`.

I noticed that after a call to `SSL_CTX_new` I can not unload the SO via `FreeLibrary`. The process holds on to a reference to the SO not matter how many times `FreeLibrary` is called.

I am trying to understand the global state of OpenSSL and how I can work around this issue. My app needs to be able to unload the SO then reload a new SO in its place.

I've tried `OPENSSL_thread_stop` and `OPENSSL_cleanup` with no success.

Any ideas?

**Comment by kaduk** [comment]
You did not say what version of OpenSSL is in use, which is highly relevant, as the behavior in this space has changed substantially recently; commit 5836780f436e03be231ff245f04f2f9f2f0ede91 comes to mind as one example but IIRC there are others.

**Comment by mattcaswell** [comment]
I am assuming you are using OpenSSL 1.1.0. OpenSSL uses atexit() to cleanup after itself. Some OSes will handle this nicely and call the atexit() handler just before the library unloads. Some will not and will call the atexit() handler at process exit, even if the handler has already been unloaded, which leads to a crash. To prevent this issue we forced the OpenSSL libraries to remain loaded until process exit - which was the best of a bad set of options. Mostly this works fine but does cause problems in exactly the scenario you describe, i.e. statically linking an SO to OpenSSL and then trying to dynamically load/unload the SO.

The behaviour can be suppressed by compiling openssl with the no-dso option. Do so at your own risk though if you are loading and unloading libraries - it may crash if running on an OS that isn't friendly towards atexit(). I'm not sure how windows 10 behaves in this regard. The other disadvantage with no-dso is that you also won't be able to dynamically load engines at runtime if that is a requirement for your application.

Another option for you to consider would be to dynamically link to OpenSSL instead. That way OpenSSL will not prevent your own SO from being unloaded.

**Comment by chrisd1100** [comment]
Thanks for your help, with the `no-dso` option enabled at compile time I no longer have the issue.

Indeed I was using OpenSSL 1.1.0 (1.1.0c), and I encountered a second issue after enabling `no-dso`, which was addressed here: https://github.com/openssl/openssl/issues/1899. The app was hanging on the first OpenSSL API call. Upgrading to OpenSSL (1.1.0f) fixed that issue.

I also found some documentation related to this issue here: https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_init_crypto.html. There it seems to instruct the user to call `OPENSSL_cleanup` and `OPENSSL_thread_stop` manually when in my situation (OpenSSL is statically compiled inside a dynamically loaded SO).

If that is the case, would it be advisable to handle the situation in `DllMain`, like this? Or is there a double-free / race condition here somewhere:

```
#include <windows.h>

#include "openssl/ssl.h"

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
	hinstDLL, fdwReason, lpvReserved;

	switch (fdwReason) {
		case DLL_PROCESS_ATTACH:
			break;
		case DLL_THREAD_ATTACH:
			break;
		case DLL_THREAD_DETACH:
			OPENSSL_thread_stop();
			break;
		case DLL_PROCESS_DETACH:
			OPENSSL_cleanup();
			break;
	}

	return TRUE;
}
```

Thanks again for the insight.

**Comment by mattcaswell** [comment]
Well, that's not quite what the documentation says. Basically it says don't call `OPENSSL_cleanup()` unless for some reason you know that the atexit() handlers won't be called. That is not the case in your situation - they will be called (there is a risk, depending on how Windows 10 handles `atexit()`, that they will be called after the library is unloaded which will cause a crash - either way they are called!!). So, don't call `OPENSSL_cleanup()`.

You *should* call `OPENSSL_thread_stop()` because this is the situation that the docs talk about, i.e. Windows static linking. The method that you propose should be fine.

**Comment by chrisd1100** [comment]
Yep, you are correct, found the documentation from Microsoft: https://msdn.microsoft.com/en-us/library/988ye33t.aspx

It appears that on DLL cleanup, any `atexit` handlers set within the DLL are called on `PROCESS_DETACH` in an encapsulated manner.

**Comment by leozzyzheng** [comment]
Could you provide the whole complie configuration? I have added `no-dso` but the dll still could not be unloaded. Thanks!

**Comment by mattcaswell** [comment]
> Could you provide the whole complie configuration? I have added no-dso but the dll still could not be unloaded. Thanks!

`perl Configure VC-WIN64A no-dso`

**Comment by leozzyzheng** [comment]
@mattcaswell Thanks, I'm using `perl Configure --debug VC-WIN32 no-shared threads no-dso no-engine` but doesn't work, should I rebuild the libcurl also?

**Comment by mattcaswell** [comment]
> @mattcaswell Thanks, I'm using perl Configure --debug VC-WIN32 no-shared threads no-dso no-engine but doesn't work, should I rebuild the libcurl also?

Since you are using "no-shared" (i.e. static linking), you will need to rebuild any application that links to OpenSSL.

**Comment by leozzyzheng** [comment]
@mattcaswell Understand, let me try it.

**Comment by leozzyzheng** [comment]
@mattcaswell Yes you're right, the dll could be unloaded correclty now.
