### ISSUE TITLE
IPv6 support for BIOS APIs

### ISSUE THREAD

**Issue by vinitjain123** [openssl/openssl#378]
This issue is related to IPv6 support for BIOs socket Apis.
I wrote one test sample for IPv6 and observed BIOs apis does not support IPv6 on latest master stream.
Here i am listing client and server code.
===================================================
client.c
void do_client_loop(BIO *conn)
{
        int err, nwritten;
        char buf[80];
        for (;;)
        {
                if (!fgets(buf, sizeof(buf), stdin))
                        break;
                printf("the buf is %s\n",buf);
                for (nwritten = 0; nwritten < sizeof(buf); nwritten += err)
                {
                        err = BIO_write(conn, buf + nwritten, strlen(buf) - nwritten);
                        if (err <= 0)
                               return;
                }
        }
}
int main(int argc, char *argv[])
{
       BIO *conn;
       init_OpenSSL();
        conn = BIO_new_connect(SERVER ":" PORT);
        if (!conn)
                int_error("Error creating connection BIO");
        if (BIO_do_connect(conn) <= 0)
                int_error("Error connecting to remote machine");
        fprintf(stderr, "Connection opened\n");
        do_client_loop(conn);
        fprintf(stderr, "Connection closed\n");
        BIO_free(conn);
        return 0;
}
------------------------------------------------------------------------------------------------------------
server.c
#include "common.h"

void do_server_loop(BIO *conn)
{
        int err, nread;
        char buf[80];

        do
        {
                for (nread = 0; nread < sizeof(buf); nread += err)
                {
                        err = BIO_read(conn, buf + nread, sizeof(buf) - nread);
                        if (err <= 0)
                                break;
                }
                fwrite(buf, 1, nread, stdout);
        }
        while (err > 0);
}

void THREAD_CC server_thread(void *arg)
{
        BIO *client = (BIO *)arg;

#ifndef WIN32
        pthread_detach(pthread_self());
#endif
        fprintf(stderr, "Connection opened.\n");
        do_server_loop(client);
        fprintf(stderr, "Connection closed.\n");

        BIO_free(client);
        ERR_remove_state(0);
#ifdef WIN32
        _endthread();
#endif
}
int main(int argc, char *argv[])
{
        BIO *acc, *client;
        THREAD_TYPE tid;

        init_OpenSSL();

        acc = BIO_new_accept(PORT);
        if (!acc)
                int_error("Error creating server socket");

        if (BIO_do_accept(acc) <= 0)
                int_error("Error binding server socket");

        for (;;)
        {
                if (BIO_do_accept(acc) <= 0)
                        int_error("Error accepting connection");

                client = BIO_pop(acc);
                THREAD_CREATE(tid, &server_thread, client);
        }

        BIO_free(acc);
        return 0;
}
-----------------------------------------------------------------------------------------------------
common.h
#include <openssl/bio.h>
#include <openssl/err.h>
#include <openssl/rand.h>
#include <openssl/ssl.h>
#include <openssl/x509v3.h>

#ifndef WIN32
#include <pthread.h>
#define THREAD_CC
#define THREAD_TYPE pthread_t
#define THREAD_CREATE(tid, entry, arg) pthread_create(&(tid), NULL,(entry), (arg))
#else
#include <windows.h>
#define THREAD_CC _ _cdecl
#define THREAD_TYPE DWORD
#define THREAD_CREATE(tid, entry, arg) do { _beginthread((entry), 0, (arg));\
        (tid) = GetCurrentThreadId(); \
} while (0)
#endif

#define PORT "6001"
#define SERVER "[2607:f388:202:b3ff::8329]"
#define CLIENT "[2607:f388:202:b3ff::8329]"
#define int_error(msg) handle_error(__FILE__, __LINE__ , msg)
void handle_error(const char *file, int lineno, const char *msg);
void init_OpenSSL(void);
================================================================
I tried this sample with different formats if SERVER and CLIENT
EX : 
#define SERVER "[2607:f388:202:b3ff::8329]"
#define CLIENT "[2607:f388:202:b3ff::8329]"

#define SERVER "2607:f388:202:b3ff::8329"
#define CLIENT "2607:f388:202:b3ff::8329"

#define SERVER "[::1]"
#define CLIENT "[::1]"

#define SERVER "::1"
#define CLIENT "::1"

but socket did not get connected successfully.  I checked source code of 
1. Src/crypto/bio/b_sock.c
2. Src/crypto/bio/bss_connect.c
which doesn't seems to be IPv6 compatible. 

I would like to work on support IPv6 ,So could you please share information related to IPv6 support for BIOs APIs ?Latest status would be appreciated.

**Comment by richsalz** [comment]
It is being worked on; see https://github.com/openssl/openssl/pull/285  closing this as a duplicate.

**Comment by vinitjain123** [comment]
Hi richsalz , 
 
Thanks for the information. 
After applying this patch, segmentation fault is being observed. so just want to confirm if this stand alone patch is sufficient for the fix?

**Comment by richsalz** [comment]
sorry, no idea.
