### ISSUE TITLE
Openssl 1.1.0e/f install_sw without openssl.cnf

### ISSUE THREAD

**Issue by mlerczak** [openssl/openssl#3785]
Hi there, after make install_sw there is no content in /etc/ssl

`  misc  openssl.cnf  openssl.cnf.dist  private` is missing.  When I make same with `make install` all files is on place.

```bash
RUN wget -O /tmp/openssl.tgz https://www.openssl.org/source/openssl-1.1.0f.tar.gz \
    && tar -zxf /tmp/openssl.tgz -C /tmp \
    && cd /tmp/openssl-* \
    && ./config --prefix=/usr \
                --openssldir=/etc/ssl \
                --libdir=lib \
                no-shared \
                zlib-dynamic \
    && make && make install_sw \
```

**Comment by levitte** [comment]
```
make install_ssldirs
```

The reason for a separate thing is that an installation of *software* shouldn't necessarely overwrite an already present `openssl.cnf`

**Comment by mattcaswell** [comment]
Issue was answered. Closing.
