### ISSUE TITLE
Please provide xz compressed releases

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#3786]
If it is not too inconvenient please provide further releases also as a .xz archive.
The size comparison:
openssl-1.1.0f.tar.gz 5.1M 
openssl-1.1.0f.tar.xz 3.5M

I could recompress it myself but then I wouldn't have an official the PGP signature.

**Comment by robert-scheck** [comment]
I wonder if `.lz` rather `.xz` doesn't make even more sense, given the lzip format is intended for long-term archiving (some GNU projects are using it already as replacement for xz format), size is about the same with xz.

**Comment by nickthetait** [comment]
Is there any interest in this functionality from core developers? If so, I'd be interested in creating a little tool to automate this...

**Comment by mattcaswell** [comment]
We already have tools for creating releases which for some reason (not sure why) are not public (I thought they were in our tools repo, but apparently not). If we were to do this it would need to be integrated into that.

**Comment by nickthetait** [comment]
Who do we need to annoy about publishing these tools? :stuck_out_tongue_winking_eye:

**Comment by richsalz** [comment]
Look in the release_tools section of our github repositories.
I don't see any need for yet another compressed file format.  zip (for windows) might make sense, but everyone knows tar/gzip.

**Comment by levitte** [comment]
We don't have the our release tools on github, they are still internal, like @mattcaswell says.

**Comment by richsalz** [comment]
ah, right review-tools != release-tools.  let's chat offline about publishing those at some point.  But the key point is still not seeing a need to add a new compressed format.

**Comment by nickthetait** [comment]
In that case I suggest:
* close this issue
* create a "publish release tools to github" issue as a reminder

**Comment by richsalz** [comment]
closed and #5125 opened.  thanks @nickthetait !
