### ISSUE TITLE
Android x86_64 (FIPS and non-FIPS) requires some changes

### ISSUE THREAD

**Issue by alan-kozlay** [openssl/openssl#3787]
My build environment:
HOST:       CentOS 7 Linux x86_64
TARGET:  Android x86_64
TOOL:      Android NDK 15 (android-ndk-r15b-linux-x86_64.zip).
OSSL:       openssl-1.0.2l & openssl-fips-2.0.16

My environment variables are set as:
ANDROID_NDK_ROOT=/home/me/Android/Sdk/ndk-bundle
ANDROID_API=android-23
ANDROID_EABI=x86_64-4.9
ARCH=arch-x86_64
SYSROOT=/home/me/Android/Sdk/ndk-bundle/platforms/android-23/arch-x86_64
ANDROID_DEV=/home/me/Android/Sdk/ndk-bundle/platforms/android-23/arch-x86_64/usr
ANDROID_TOOLCHAIN=/home/me/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin
CROSS_COMPILE=x86_64-linux-android-
CC=gcc
HOSTCC=gcc
FIPS_SIG=/tmp/openssl/openssl-fips-2.0.16/util/incore

I can build and test both FIPS and non-FIPS builds for x86_64 Android, but only after changes.  Unfortunately, my change (B) _technically_ constitutes a violation of the FIPS Policy.

**(A) The following change is needed by both FIPS and non-FIPS build processes for x86_64 on Android:**
File: openssl-1.0.2l/Configure
Line: 474
Mod: Line must become:
`"android","gcc:-mandroid -I\$(ANDROID_DEV)/include -L\$(ANDROID_DEV)/lib64 -B\$(ANDROID_DEV)/lib64 -O3 -fomit-frame-pointer -Wall::-D_REENTRANT::-ldl:BN_LLONG RC4_CHAR RC4_CHUNK DES_INT DES_UNROLL BF_PTR:${no_asm}:dlfcn:linux-shared:-fPIC::.so.\$(SHLIB_MAJOR).\$(SHLIB_MINOR)",`

**(B) The following change is needed by FIPS build process for x86_64 on Android:**
When calling config to build the FIPS Module, a symbol must be added to the command-line:
$ ./config -DFIPS_REF_POINT_IS_CROSS_COMPILER_AWARE

It appears that change (B) is required because ./openssl-fips-2.0.16/fips/fips_canister.c (line 33) only recognizes `__i386__` and `__i386` (_not `__x86_64__`_) as valid architecture symbols when `__ANDROID__` is defined.

Is there a plan for adding Android x86_64 as a supported Operational Environment in a future FIPS Module?
This is important because, when building Android, a decision must be made whether to support both 32-bit and 64-bit shared objects or only 64-bit.  If the decision is made to support both, all system libraries must have both 32 and 64 bit versions included.  Given the limited storage space of typical Android hardware, a decision to support both (because FIPS OpenSSL is only available in 32-bit) is costly. 
Or, do you disagree that change (B) invalidates FIPS?

Thanks,
-Alan

**Comment by levitte** [comment]
Regarding your modified line in Configure, it's better to make a separate line with a different name, like this:

```
"android-x86_64","gcc:-mandroid -I\$(ANDROID_DEV)/include -L\$(ANDROID_DEV)/lib64 -B\$(ANDROID_DEV)/lib64 -O3 -fomit-frame-pointer -Wall::-D_REENTRANT::-ldl:BN_LLONG RC4_CHAR RC4_CHUNK DES_INT DES_UNROLL BF_PTR:${no_asm}:dlfcn:linux-shared:-fPIC::.so.\$(SHLIB_MAJOR).\$(SHLIB_MINOR)",
```

**Comment by alan-kozlay** [comment]
Yes.  I agree.
I'm guessing the "android" was a default if the architecture wasn't recognized.

**Comment by SteveMarquess** [comment]
As the OP noted any modification of the FIPS module tarball means the result cannot be claimed as FIPS 140 validated. Unfortunately only specific platforms ("Operational Environments") have been formally tested for the OpenSSL FIPS Module Validations. The module may or may not compile for other untested platforms, but in any case the result is unvalidated and should be considerd undefined. The config and Configure files in the FIPS module tarball have many vestigial architecture entries that do not correspond to any formally tested platforms, but any platform that can't be compiled is not validated.

**Comment by SteveMarquess** [comment]
Oh, I should mention that there is a process (the "change letter" update) by which new platforms can be formally added to the existing validations. That process is how the count of such platforms grew to the current 250+, more by far than for any other validated module. But, it costs time and money.

**Comment by richsalz** [comment]
Closing per @SteveMarquess
