### ISSUE TITLE
Getting Public Key Signed off by Approved CA

### ISSUE THREAD

**Issue by BarryCheema** [openssl/openssl#3792]
Following my last post we have now successfully created public keys, but we need them to be signed off by an approved CA on the HMRC list.  As we are working to a tight deadline and as everyone who was working here the last time we had to get sign off has now left (!!) we are struggling to get sign off of the keys by tomorrow if possible.  These are the companies provided to us
Quo Vadis 
•             Trustis
•             Verisign
•             Thawte
•             Entrust
•             GeoTrust
•             Comodo
•             GlobalSign
•             TERENA

it looks like they will charge us for this?  Is anyone part of this community able to advise ohow we could get the keys signed off.  We have no contacts at any of these companies and trying to reach out to them has been difficult.

**Comment by mattcaswell** [comment]
Most of these companies will offer online purchase of certificates. Take a look around the websites for these companies and choose one that suits. If all you are after is simple domain validation then normally this can be achieved very quickly. Anyway this is not an OpenSSL issue, so not really appropriate here. Closing.
