### ISSUE TITLE
Consider exposing SSL_CIPHER->algo_strength

### ISSUE THREAD

**Issue by FauxFaux** [openssl/openssl#3795]
In OpenSSL 1.0, applications can detect how secure an established connection is by examining the `algo_strength` on a `SSL_get_current_cipher()`, and comparing it with e.g. `SSL_MEDIUM`. In 1.1, this struct is opaque, and this value isn't exposed anywhere that I can find.

e.g. skipfish, a website analysis tool, uses it to warn users about their website negotiating poor ciphers:
https://github.com/spinkham/skipfish/blob/093800c9de4116706258982376abce01928a3f7b/src/http_client.c#L1961

This seems like a useful feature: Please add a way to access this data.

I don't believe that the strength of a cipher is supposed to be a private implementation detail, because it's exposed via. the cipher selection process. In fact, a user on IRC suggested a workaround of enumerating the cipher sets for each of MEDIUM and HIGH, and seeing if our cipher appears in that list. I admit this would probably work, but it's a lot of additional, unnecessary code.

**Comment by richsalz** [comment]
SSL_MEDIUM is an opinion from the OpenSSL developers.  The proper thing to do is for skipfish, or any other tool, to have its own list of ciphers that it considers good, bad, indifferent.  I'd really prefer that we not expose this.

**Comment by mattcaswell** [comment]
The opinion above is to not add this feature, so closing.

**Comment by FauxFaux** [comment]
I disagree, but a decisive answer is better than an open ticket. Thanks. :+1:

**Comment by Gu1nness** [comment]
I allow myself to reopen this.
Maintaining twice the same list is useless and would create some additional work in order to maintain a project such as skipfish.

This seems to me important to expose this variable since I trust OpenSSL to decide well the weak, medium, strong ciphers.

**Comment by t8m** [comment]
The question is what skipfish intends to do with the information - the information whether some cipher is HIGH or MEDIUM or anything else can differ based on the version, release branch, etc. So if skipfish is built/linked to a different openssl version it would potentially show different information for the same ciphersuite. Is this acceptable for the skipfish use-case?

If the intention is to show the user what the particular openssl version thinks is the appropriate "security level" of an algorithm, then OK.

If the intention is to show the "current state of art" security level, then it would be better if the list was managed by skipfish itself or it would have to be ensured that the skipfish is linked to openssl from the master branch as released branches unless they are newly released will tend to keep these lists stable and not up-to-date with the current state of art.

**Comment by Gu1nness** [comment]
Thanks for your answer!

The intention is more to show the current state of the art security level since skipfish is a web app security scanner.
However, since I'm planning to take skipfish back and maintain it on the long term, and if possible have it packaged in distributions, I cannot compile against master of OpenSSL.

So I guess that the only solution left is to maintain the list in skipfish, and find a way to be kept up-to-date on the security level of the algorithms.

Sorry for the noise.
