### ISSUE TITLE
Doubt on gcm128 short IV handling

### ISSUE THREAD

**Issue by vache7** [openssl/openssl#3796]
in master/crypto/modes/gcm128.c line 828 - CRYPTO_gcm128_setiv() :
in the special handling of short (12 byte long) IV : 

``` C
if (len == 12) {
        memcpy(ctx->Yi.c, iv, 12);
        ctx->Yi.c[15] = 1;
        ctr = 1;
}
```

The applied IV seems undefined for Yi.c[12, 13 and 14].
It is used in 898:

``` C
(*ctx->block) (ctx->Yi.c, ctx->EK0.c, ctx->key)
```

Then correctly set in 904: 

``` C
PUTU32(ctx->Yi.c + 12, ctr);
```

resulting in potentially wrong EK0 (used by authentication, not encryption)
This is probably not seen by many users since Yi is 0 initialized at init time.

**Comment by paulidale** [comment]
Could you give an example of a failure you're seeing?  Ideally, including sample code.

The union should be properly initialised to zero earlier in the function:
```
    ctx->Yi.u[0] = 0;
    ctx->Yi.u[1] = 0;
```

The assignment to `ctx->Yi.c[15]` sets the counter to 1 which matches what `ctr` is set to.

The other branch of the `if (len == 12)` conditional will not fully initialise the `Yi.c` array when `len` < 16.  Again, the earlier assignments to `Yi.u` should cover this.

**Comment by vache7** [comment]
You're right of course... I hate unions.
I'll close the issue, I won't bother again.

I saw that while tracking a problem that had absolutely nothing to do with it (my keys were getting corrupted!) but I couldn't make sense of this code. I should have spent more time analysing it, it would have been obvious.
