### ISSUE TITLE
Does SSL_connect/SSL_do_handshake return 1 meaning handshake is done (server hello is received)?

### ISSUE THREAD

**Issue by yctung** [openssl/openssl#3798]
Hi all,

I am working on making my client can have TLS 1.3 0RTT resumption (early data). 
My program's logic is to check the status of early data once the handshake finishes.

However, I just notice that SSL_handshake might return 1 while the handshake is not finished. Is it a bug? For example: 

int SSL_do_handshake(SSL *s)
{
    ..... < original cod > ....
    printf("[OPENSSL]: SSL_do_handshake ret = %d, state = %d, SSL_is_init_finished = %d\n", ret, SSL_get_state(s), SSL_is_init_finished(s));
    return ret;
}

When the SSL_write_early_data is called, I am getting the result of ret == 1 but SSL_is_init_finished is false. And by tracking the other part of my socket, the handshake is not finished yet.

Yu-Chih

**Comment by mattcaswell** [comment]
`SSL_do_handshake()` should never return 1 without completing the handshake *when called directly by an application*. `SSL_write_early_data()` (indirectly) invokes `SSL_do_handshake()` and performs some magic to make it behave slightly differently. Specifically for early data we want to initiate the handshake but stop it at a given point so that we can start sending the early data instead - even though the handshake is not yet complete. The fact that the handshake isn't complete is why it's called "early" data! So, this is totally normal behaviour.

**Comment by yctung** [comment]
Hey Matt,

You are right. But in this case, should I busy wait after sending the early data to until SSL_is_init_finish returning true?

For example, here is an example of my code:
void my_handshake(SSL *ssl){
    int ret = -1;
    if (need_to_send_early_data) {
         ret = ssl_write_early_data(s, early_data, early_data_len);
         // I am not sure if handshake finished or not (mostly not)
         while(!ssl_is_init_finished(s)) {
              ret = ssl_connect(s); // not sure if it is a good way to do it.....
         }
         return ret;
     else {
          return ssl_connect(s);
     }
}

**Comment by mattcaswell** [comment]
Well you *can* do it that way, with the caveat that it is not sufficient just to call ssl_is_init_finished() - you need to also check the ret value (in case of fatal errors). You might want to consider the use of blocking sockets rather that non-blocking if you don't have anything else to do in your app while waiting for the connection to complete (you still need to put it in a loop even then though). Alternatively, when checking the "ret" value (using SSL_get_error()) if you get SSL_ERROR_WANT_READ then you can do a "select" call (or equivalent) on the underlying socket waiting for it to be readable before recalling SSL_connect().

**Comment by yctung** [comment]
Oops, you are right. My system needs the non-blocking IO. So, I will also check the ret. Thanks!
