### ISSUE TITLE
'make test' failures for MSVC build with '-arch:AVX2' key on Windows

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#3803]
Hello everyone,

For builds using MSVC:
```
perl Configure -arch:AVX2 shared VC-WIN64A && nmake && nmake test
```
test recipes:
```
70-test_asyncio.t
70-test_bad_dtls.t
70-test_clienthello.t
70-test_recordlen.t
80-test_cipherbytes.t
80-test_cipherlist.t
...
```
unable to finish its tasks and had to be terminated manually.

Reproduced for:
- builds using MSVC with `<Release><Shared|Static>` configurations and `-arch:AVX2` key.

Not reproduced for:
- builds using MSVC with `<Debug><Shared|Static>` configurations and `-arch:AVX2` key,
- builds using MSVC with `<Release><Shared|Static>` configurations and `-arch:AVX` key,
- builds using migw-w64 with `-mtune=native -march=native` keys on Haswell CPU and ICC with `-QxCORE-AVX2` key.

Environment:
- Windows 10 x64,
- MSVC 2015 Update 3,
- Windows SDK 10.0.14393.33,
- Active Perl 5.24.1,
- OpenSSL-1.1.1-dev (8530039a307f7aa8acb0516fdd38191baa91d434).

Alexander

**Comment by bernd-edlinger** [comment]
oh, generally all Windows Versions are currently broken.

**Comment by bernd-edlinger** [comment]
could you please try if b5319bdb fixes your problem?

**Comment by sav-ix** [comment]
Downloaded recent master and patch b5319bdbd095ff59d084af5ce16e5f715963557d, but was unable to apply it neither using `git apply` command neither manually, since OpenSSL sources doesn't contain wanted strings.
On what OpenSSL sources should be applied this patch?

**Comment by bernd-edlinger** [comment]
master branch

**Comment by sav-ix** [comment]
Ah, I missed that b5319bdbd095ff59d084af5ce16e5f715963557d was already merged to master. It turns out I tried to apply it again.
Just tested build using MSVC with Release Shared configuration and `-arch:AVX2`, and `make test` run get stuck on `70-test_asyncio.t` test as before patch.

**Comment by bernd-edlinger** [comment]
And if you build with no-asm does it work then?

**Comment by sav-ix** [comment]
Tested build using MSVC with Release Shared configuration and `no-asm -arch:AVX2` keys, and `make test` run get stuck on `70-test_asyncio.t` test as before.
In addition found, that error not reproduced, if `/O1` key used instead of `/O2` for Release Shared build.
Since this issue could relate to my system or MSVC 2015 instead of OpenSSL, could anyone reproduce it using MSVC 2015 and MSVC 2017?

**Comment by dot-asm** [comment]
I haven't tried to reproduce it, but two things. The fact that outcome depends on optimization level is very likely an indication of a compiler bug. Compilers bugs never make sense and bite you when you least expect it, and there is nothing *we* can do about it. Secondly, out of curiosity, what is it you are trying to achieve with -arch:AVX2? Note that it doesn't affect assembly modules, in sense that you get all the fancy code paths like AVX2 or AVX512 [provided that you use nasm] compiled and *executed* [if appropriate for current processor] *irregardless* -arch flag passed to compiler [or compiler itself]...

**Comment by dot-asm** [comment]
> [or compiler itself]

More specifically compiler's ability to generate AVX2 code. I mean AVX2 assembly code paths will be compiled [provided that you use nasm] and executed even if compiler has no idea whatsoever about AVX2.

**Comment by sav-ix** [comment]
> Compilers bugs never make sense and bite you when you least expect it, and there is nothing _we_ can do about it.

But _we_ could report it on MSVC bugtracker. Thus I asked OpenSSL Community about build results using MSVC <2015|2017> on Haswell CPU.

> what is it you are trying to achieve with -arch:AVX2?

It's hard to expect, that usage of `-arch:AVX2` key for builds using MSVC would significantly increase OpenSSL performance. At least not today.
The main goal was to use the same set of compiler keys during build of different libraries. Based on the (naive) assumption, that it would decrease chance of (runtime) troubles, when all that libraries would be combined in the same project. 
And since build systems of few of that libraries are using `-arch:AVX2` key in its MSVC toolchains, it was added to build commands of all other libraries. That's how this issue was revealed.

**Comment by dot-asm** [comment]
The problem persists even with VS2017. It actually fails earlier, already in test_evp with
```
        # Subtest: run_file_tests
        1..1
        # INFO:
        # Reading recipes\30-test_evp_data\evpciph.txt
        # ERROR: (ptr) 'equals = strchr(s->buff, '=') != NULL' failed @ test\testutil\stanza.c:107
        # 0x0
        # INFO:
        # Missing = at line 8
        #
        # INFO:
        # Completed 0 tests with 1 errors and 0 skipped
        not ok 1 - recipes\30-test_evp_data\evpciph.txt
```
I.e. it apparently fails to parse file, let alone perform calculations. Even though this doesn't formally preclude possibility that stanza.c violates some letter of the standard, which allows compiler to generate failing code, knowing that lowering optimization level helps speaks rather in favour of suggestion that it's compiler bug [i.e. non-OpenSSL problem].

> -arch:AVX2 ... would decrease chance of (runtime) troubles, when all that libraries would be combined in the same project.

It won't make any difference. I mean having different parts compiled with different -arch flags. Well, given natural limitations, like -arch flag in *either* component effectively limiting where you can actually execute binary.

**Comment by sav-ix** [comment]
Thank you for test results using MSVC 2017. Since error reproducible, I [reported](https://connect.microsoft.com/VisualStudio/feedback/details/3136946) it on MSVC bugtracker.

And this issue could probably be closed, as
>non-OpenSSL problem

**Comment by bernd-edlinger** [comment]
ok, good bye.

**Comment by aargor** [comment]
Hi, I'm a developer on VC++. I'm writing to confirm that you did indeed find a compiler bug for /arch:AVX2, thanks! The SBC (silent-bad-codegen) is occurring in ssl_cipher_collect_ciphers, in ssl\ssl_ciph.c.

I just finished tracking down the function we're breaking on, so I can't say anything about an ETA for a fix, but if this is blocking: I confirmed that turning off optimizations for that function (via #pragma optimize("",off) ... #pragma optimize("",on)) lets an -arch:AVX2 build get past the hangs you've observed. I don't see the other issue dot-asm mentioned about parsing, however.

We daily test our latest compiler bits against a suite of OSS projects, including this one, to flush out compiler bugs. We haven't gone beyond the default release options for these projects, but clearly it's worth looking into more.

Also, thank you very much for reporting the bug and the very clear repro instructions in the Connect thread. I gave a quick reply there too. When we have a fix for the bug we update the Connect thread.

Thanks again,
Aaron Gorenstein
Microsoft Visual C++

**Comment by sav-ix** [comment]
Hello, Aaron,

Thank you for response. Tested workaround with `#pragma optimize("",<off|on>)` for `ssl_cipher_collect_ciphers()` and it allowed to bypass this issue.
I will follow the updates here and in the Connect thread.

**Comment by dot-asm** [comment]
> Tested workaround

Just in case, it won't be considered for inclusion into repository. As already mentioned, there is no reason to compile OpenSSL with -arch:AVX2, so just don't. At least till compiler bug is fixed. Well, even when it's fixed, it still wouldn't real point in doing so... @aargor, what would be more helpful if you could back up the assertion that there is no requirement that all (dll) components of application have to be compiled with same -arch flag. In sense that if it's shown that there is some breakage because of the mixing, it will be considered by Microsoft as bug. It will have to be, because it would mean non-compliance with calling convention. Well, admittedly except for "natural" breakages like execution on pre-AVX2 processors, execution of application with at least one component compiled with -arch:AVX2.

**Comment by dot-asm** [comment]
> I don't see the other issue dot-asm mentioned about parsing, however.

Note that we are using different VS versions. @sav-ix - 2015 and myself - 2017. For reference, my compiler version is 19.10.25019. However, I just double-checked and it turned out that parsing failure does *not* depend on -arch:AVX2 flag. In other words it appears to be independent problem...

**Comment by sav-ix** [comment]
>Just in case, it won't be considered for inclusion into repository.

Since it's just a workaround, and since issue relate to the compiler, of course there is no sense to push it to master.

**Comment by dot-asm** [comment]
> parsing failure does not depend on -arch:AVX2 flag. In other words it appears to be independent problem...

As it turns out it's the way my git checks out files. It was replacing \n with \r\n, which confuses parser. I mean when it says "can't find =" it's looking at line consisting of \r alone. So disregard comments about parsing, I apologize for unnecessary possible confusion.

[Hmmm, I recall looking into it... It might happen that I found default appropriate at the time, and it, default, has changed afterwards in grand upgrade to 2017. Windows is not my platform of choice for daily activities...]

**Comment by levitte** [comment]
The parser issue is probably because of [this](https://github.com/openssl/openssl/blob/master/test/testutil/stanza.c#L23), i.e. we open *text files* in *binary mode* for some reason.
(I cannot for the life of me understand why we do that)

**Comment by dot-asm** [comment]
Oh! It *is* because of that. I mean I can confirm that if I check out in my usual way and remove 'b', then it works! Thanks!

**Comment by richsalz** [comment]
We use stdin/stdout in whatever mode they are in.

We consistently open ‘-in’ and ‘-out’ files in binary mode because it is consistent – are we reading a DER file or a PEM file?  We can’t tell at the open time.

**Comment by levitte** [comment]
That's not stdin, that's a file named as an argument, and we *know* it's a text file. 

Re the command line and if I recall correctly, we open stdin in text mode if we expect pem, and binary mode if we expect raw der, all depending on the `-inform` argument (default `pem`)

**Comment by richsalz** [comment]
No, stdin is always left as the platform has it.  If you want explicit control, use the -in/-out flags.

**Comment by levitte** [comment]
Maybe you should grep for `B_FORMAT_TEXT` in apps/apps.h and look at the format macros you find. Perhaps also look at `dup_bio_in` with friends in apps/apps.c

**Comment by levitte** [comment]
But meh, the discussion on command line is neither here nor there in this issue. The issue is test/evp_test.c, which does open files named on the command line, and *wrongly* opens them in binary mode.

**Comment by richsalz** [comment]
Thanks for the nudge.

**Comment by richsalz** [comment]
Oh.  Well, fix that. ☺

**Comment by levitte** [comment]
See #3939

**Comment by aargor** [comment]
Hi @dot-asm , I agree that what you described about "mixing" /arch dlls should be supported. I don't see it written down anywhere, so I'll see if I can get a published statement.

Glad this isn't a blocking issue for you all,
Aaron

**Comment by sav-ix** [comment]
Since [link](https://connect.microsoft.com/VisualStudio/feedback/details/3136946) at Connect became 404, reporting here: issue not reproduced after moving to MSVC 2017 15.5.0.
Thank you for fix, Aaron.

**Comment by sav-ix** [comment]
> Just in case, it won't be considered for inclusion into repository.

Based on this, me also have a question out of curiosity. If [proposed](https://github.com/openssl/openssl/issues/3803#issuecomment-315454711):
```
#pragma optimize("",off) ... #pragma optimize("",on)
```
workaround for this issue could not be added to master, since it's a compiler bug, then why https://github.com/openssl/openssl/commit/b32166b4fabd2a3aeec382521b0173b24a5d7c02 wasn't reverted, after related ICE was fixed with MSVC 2015 Update 2, and OpenSSL CI builds became unblocked? Thanks.

CC: @mattcaswell

**Comment by richsalz** [comment]
Not adding a special pragma is not the same as reverting a no-longer-necessary change.  It could have been done, but nobody saw the need or made a PR or even suggestion to do so.  The change also didn't break anything.

The pragma approach isn't portable, since 'pragma optimize' could mean different things to different platforms.  It could have been wrapped in an ifdef, but then it start to grow bigger and uglier.
