### ISSUE TITLE
Add no-store Configure option

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#3807]
It would be nice to have a no-store configure option which would exclude the store directory.

**Comment by levitte** [comment]
I'm unsure about that idea, for the same reason I'd be unsure about `no-pem`.

**Comment by mattcaswell** [comment]
Why would you want such a thing? If you don't want it - don't use it. Why would we need a compile time option for it? In general I think there is a preference in the team to *reduce* the number of compile time options.

**Comment by matbech** [comment]
The idea came up because the store feature has a strong dependency to ui (https://github.com/openssl/openssl/issues/3806) and I prefer to exclude the ui feature at compile time. In hindsight, I believe there is no need for a no-store option once issue 3806 is resolved.
