### ISSUE TITLE
Unable to reject a early data after read it?

### ISSUE THREAD

**Issue by yctung** [openssl/openssl#3808]
Hi,

I am using OpenSSL to enable TLS 1.3 and 0RTT resumption in my service. 
I noticed that when my server has called "SSL_read_early_data" successfully, the client will think the early data has been "accepted" (i.e., SSL_get_early_data_status() == SSL_EARLY_DATA_ACCEPTED).

However, in some cases, my server might want to "reject" the early data after I parse it (e.g., only accept the HTTP GET but reject HTTP POST as sent by early data). In such cases, the client will need to know the early data is rejected and then send the request again via a normal ssl_write() call.

So, is there any way that server can reject the early data but reject it? or am I using the wrong way in client to determine if the early data is accepted?

**Comment by mattcaswell** [comment]
This is not allowed by the TLSv1.3 spec. A server informs the client that it will accept the early data that the client is about to send *before* it has read it. It is not allowed to accept it, then read it and subsequently change its mind and reject it.

**Comment by kaduk** [comment]
Applications MUST NOT use TLS 1.3 0-RTT data without an application profile specifying how to use early data with that application.  In your case, HTTP is the application, and there is no official specification defining such an application profile.  (There is a individual-submission internet-draft that may turn into such a thing, but it is a work in progress: https://tools.ietf.org/html/draft-thomson-http-replay-00, which requests IANA to allocate a new 4NN (Too Early) error code, but there is nothing usable for this purpose yet.)

**Comment by yctung** [comment]
Hi

Thank you for the explanation. But in this case, what would be the usage of early data? especially when people have concerns on its security guarantee. I mean, what should be the correct server behavior to use this early data in the perspective of applications? If server needs to "accept" and handle all early data after reading it, would that be insecure?


Yu-Chih

**Comment by richsalz** [comment]
Is it insecure?  It depends on your protocol.  For detailed discussion of the impact and affects of 0RTT early data, look at the  TLS 1.3 spec and perhaps the WG mailing list at the ietf.

**Comment by yctung** [comment]
Yeah, I read the arguments about 0RTT. I know how it works and and know it is "replayable". So, a general suggestion online is to only use it for GET without any parameter (in terms of HTTP). However, turns out I can't just "reject" it after I know the early data is a GET. In this case, my server needs to accept all the early data and control the logic to use only GET in my client.

**Comment by kaduk** [comment]
We (the IETF TLS working group) generally expect that applications will have to define some application-specific mechanism to say "I can't accept this in early data; try again later"; for HTTP this would be the 4NN (Too Early) error code that is described in the document I linked.

**Comment by yctung** [comment]
Hi Kaduk,

I read your post. But it also means my server + 4NN will not be compatible with other browsers/clients that have TLS1.3 + 0RTT but no 4NN implemented, right?

**Comment by kaduk** [comment]
I feel that it is quite hard to be confident that you are compatible with things that are deployed but do not document what their behavior is supposed to be.
It may be worth taking your question to the ietf-http-wg mailing list to coordinate experimental deployment efforts.  But yes, in general, if you are deploying something experimental/WIP like this, there will be some amount of incompatibility, quite possibly even with the final version of the protocol.  So be careful to not deploy anything that you can't roll back/change as needed :)

**Comment by yctung** [comment]
Hi kaduk,

Thank you for the reply. In this case, I might restrict to enable early data when only my client talking to my server (e.g., give session ticket allowing early data when when my server knows it is connected by my client). So I will not break anything if others talk to me.

Yu-Chih
