### ISSUE TITLE
ABI breakage due to symbols being renamed

### ISSUE THREAD

**Issue by bjourne** [openssl/openssl#3818]
I'm one of the Factor language developers (http://factorcode.org/). We have a binding for the libssl library implemented using dlopen similar to how Python's ctypes work.

In the new version of OpenSSL, you have renamed several symbols such as `SSL_library_init`, `SSL_load_error_strings` and so on which makes supporting both old and new version of the library difficult. During runtime, there is no way to check what version of libssl is installed so there is no way to know if the right function to call is named `SSL_library_init` or `OPENSSL_init_ssl`.

For C code, you have a compatibility macro but that of course is only available during compile-time and does not help other languages.

I think it would be better to retain these symbols so that you don't break the ABI unnecessarily. Sometimes breaking the ABI is unavoidable, but in this case, it is a simple function rename so keeping a function called `SSL_library_init` that just calls `OPENSSL_init_ssl` doesn't cost much.

If you don't return these function names, then you could at least be more careful not to break the ABI in the future.

Another thing that could help language bindings is adding a function called `OPENSSL_get_library_version` that returns an integer holding the version of the library. For example, if the version is less than 0x0101 then you would know that you should call `SSL_library_init` and otherwise `OPENSSL_init_ssl`.

**Comment by levitte** [comment]
There is actually a way to tell <1.1.0 and >=1.1.0 libraries apart at runtime.
<1.1.0 libcrypto has a symbol called `SSLeay`, which is the function that returns the integer you request.  In >=1.1.0, this function has been renamed to `OpenSSL_version_num`, which doesn't exist in <1.1.0 OpenSSL.  You do have the capability to look up symbols, I hope?

**Comment by richsalz** [comment]
And also, we completely broke the ABI for 1.1.0 by making almost all structures opaque.  We gave notice about this multiple times.  Sorry.

**Comment by bjourne** [comment]
Opaqueness of structs doesn't matter because you weren't intended to, and didn't have to, access fields inside of them. Our binding isn't affected by that change -- only the function renames.

Yes, looking up symbols and using either `SSLeay` or `OpenSSL_version_num` works, although it is not ideal. I didn't know about that function, thanks. Hopefully you will be more careful about gratuitous abi breaks in the future.

**Comment by kaduk** [comment]
I don't think it was a lack of caution or care that is responsible for the particular ABI break that you wrote about.  That is, our stable release policy gives us very few occasions where we are permitted to break ABI *at all*, and so at each new major release milestone we must consider not only breaks that have happened already as part of development, but also breaks that may be desired in the next several years as part of forward-looking architecture cleanup.  One of the more recent cleanup goals has been to move towards more modern and standardized symbol names (e.g., TLS_method() vs. SSLv23_method()), including cleaning up vestiges of SSLeay, the precursor to OpenSSL.  In order to effect this architectural cleanup, all the old names needed to be entirely removed, and at the new major version is the only possible time to do so.

**Comment by bjourne** [comment]
Why does old names have to be removed? No one using openssl gives a crap if  functions like `sk_num` remains in the library as aliases for `OPENSSL_sk_num`. Removing such aliases is gratuitous breakage as it as no upside.

But if you, for whatever reason, really wants to remove deprecated names, then the right way to do it is to wait until you are sure no existing code has a valid reason for depending on them. But existing code has that because many current distros, such as Ubuntu lts, ships with openssl 1.0.2 in which you need to use those old names.  

I.e you can not *in the same release* both add new function names and remove the old ones without causing  trouble for your users. You need to add function names in one release and then *in the next one* remove the old ones.

**Comment by richsalz** [comment]
Look at what curl, postfix, and others have done.
You can get many of the old names by using the "api compat" flag when you configure openssl.
