### ISSUE TITLE
Cmake

### ISSUE THREAD

**Issue by Amatsukan** [openssl/openssl#382]
Why not use CMake?

**Comment by richsalz** [comment]
We are very reluctant to add any build dependency, given the wide number of platforms.  We're looking at revamping the build system.

**Comment by SmallJoker** [comment]
I got the same question and wonder why not replace the Perl dependency with CMake?

**Comment by richsalz** [comment]
perl's more portable for us (e.g., VMS is a supported platform)

**Comment by mattcaswell** [comment]
Perl is already extensively used for numerous scripts so it wouldn't be *replacing* the Perl dependency with cmake, but *adding* cmake as a dependency. We try to avoid adding new dependencies as much as possible due to the wide number of platforms and environments that we need to build under.

**Comment by levitte** [comment]
Guys, should we make this an FAQ item?

**Comment by richsalz** [comment]
Sure, but generic like “why don’t you use cake or {other build tool}?”
