### ISSUE TITLE
Is it possible to get the x and y coordinates of an X25519 curve?

### ISSUE THREAD

**Issue by al3xkr** [openssl/openssl#3835]
Hello,
I am trying to get the x and y coordinates from an X25519 generated pkey. To my understanding I need to get the group and a point of the curve  in order to use them as parameters for `EC_POINT_get_affine_coordinates_GF2m(const EC_GROUP *ec_group, const EC_POINT *p, BIGNUM *x, BIGNUM *y, BN_CTX *ctx);`. Below is the block of my code without the NULL checking and generation of the pkey which is successful:
```
EC_KEY *ec_key;
ec_key = EC_KEY_new();
EVP_PKEY_assign_EC_KEY(pkey, ec_key);

const EC_GROUP *ec_group;
ec_group = EC_KEY_get0_group(ec_key);

const EC_POINT * ec_point;
ec_point = EC_KEY_get0_public_key(ec_key);
```
The problem is that the `EC_KEY_get0_group(ec_key);`  returns NULL. Also if I try to create a new group with `EC_GROUP_new_by_curve_name(NID_X25519);` it also returns NULL, even though it works if I substitute the NID_X25519 with another curve... Am I missing something?

**Comment by noloader** [comment]
You should probably use the [OpenSSL mailing lists](https://www.openssl.org/community/mailinglists.html) to ask questions.

**Comment by richsalz** [comment]
Yes, @noloader is correct.  I am closing this issue.  Please use the mailing list; https://mta.openssl.org for details in joining.
