### ISSUE TITLE
What is the difference between PKCS12_key_gen_uni and PKCS5_PBKDF2_HMAC?

### ISSUE THREAD

**Issue by evan0322** [openssl/openssl#385]
I am digging into the code for generate a PKCS12 file but got confused by `PKCS12_key_gen_uni` and `PKCS5_PBKDF2_HMAC`. 

for `PKCS12_key_gen_uni` 

    int PKCS12_key_gen_uni(unsigned char *pass, int passlen, unsigned char *salt,
                       int saltlen, int id, int iter, int n,
                       unsigned char *out, const EVP_MD *md_type)

for `PKCS5_PBKDF2_HMAC`

    int PKCS5_PBKDF2_HMAC(const char *pass, int passlen,
                      const unsigned char *salt, int saltlen, int iter,
                      const EVP_MD *digest, int keylen, unsigned char *out)

The purpose of the two methods are both deriving key from password using EVP_MD *digest. But the out put is totally different even if the input is all the same. Should different key derive approaches give the same result for the same input and configuration? Or PKCS12 require some more hacky configuration?

Thank you very much!!

**Comment by kaduk** [comment]
> Should different key derive approaches give the same result for the same input and configuration?

No.  Different key derivation schemes use different internal algorithms to produce the pseudorandom output, and if the different algorithms produced the same output, that would be a catastrophic failure of both algorithms, since they are no longer pseudorandom.
