### ISSUE TITLE
No file openssl.H

### ISSUE THREAD

**Issue by Elonnuir** [openssl/openssl#3857]
Good day! I compiled the dynamic library of WIN32, but there is no file openssl.H in the inclusion. Tell me please what is the reason.

**Comment by levitte** [comment]
Why should there be a openssl.h?  Can't you use the header files that we *do* deliver?

**Comment by Elonnuir** [comment]
There is a file ssl.h, in the file there are headers openssl.h, which are not.

![ssl](https://user-images.githubusercontent.com/28627920/27872311-06a9bf80-61b1-11e7-96f4-21cc236bee16.png)

**Comment by Elonnuir** [comment]
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory
	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\SteamKalix.vc.pdb -DUNICODE -DWIN32 -DWIN64 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\SteamKalix -I. -IE:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl -IC:\Qt\5.6\msvc2015_64\include -IC:\Qt\5.6\msvc2015_64\include\QtWidgets -IC:\Qt\5.6\msvc2015_64\include\QtGui -IC:\Qt\5.6\msvc2015_64\include\QtANGLE -IC:\Qt\5.6\msvc2015_64\include\QtNetwork -IC:\Qt\5.6\msvc2015_64\include\QtCore -Idebug -I. -IC:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015 -Fodebug\ @C:\Users\ASUSPC~1\AppData\Local\Temp\networkmanager.obj.4328.47.jom
networkmanager.cpp
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory
	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\SteamKalix.vc.pdb -DUNICODE -DWIN32 -DWIN64 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\SteamKalix -I. -IE:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl -IC:\Qt\5.6\msvc2015_64\include -IC:\Qt\5.6\msvc2015_64\include\QtWidgets -IC:\Qt\5.6\msvc2015_64\include\QtGui -IC:\Qt\5.6\msvc2015_64\include\QtANGLE -IC:\Qt\5.6\msvc2015_64\include\QtNetwork -IC:\Qt\5.6\msvc2015_64\include\QtCore -Idebug -I. -IC:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015 -Fodebug\ @C:\Users\ASUSPC~1\AppData\Local\Temp\listingsmanager.obj.4328.47.jom
listingsmanager.cpp
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory
	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\SteamKalix.vc.pdb -DUNICODE -DWIN32 -DWIN64 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\SteamKalix -I. -IE:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl -IC:\Qt\5.6\msvc2015_64\include -IC:\Qt\5.6\msvc2015_64\include\QtWidgets -IC:\Qt\5.6\msvc2015_64\include\QtGui -IC:\Qt\5.6\msvc2015_64\include\QtANGLE -IC:\Qt\5.6\msvc2015_64\include\QtNetwork -IC:\Qt\5.6\msvc2015_64\include\QtCore -Idebug -I. -IC:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015 -Fodebug\ @C:\Users\ASUSPC~1\AppData\Local\Temp\moc_login.obj.4328.47.jom
moc_login.cpp
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory
	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\SteamKalix.vc.pdb -DUNICODE -DWIN32 -DWIN64 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\SteamKalix -I. -IE:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl -IC:\Qt\5.6\msvc2015_64\include -IC:\Qt\5.6\msvc2015_64\include\QtWidgets -IC:\Qt\5.6\msvc2015_64\include\QtGui -IC:\Qt\5.6\msvc2015_64\include\QtANGLE -IC:\Qt\5.6\msvc2015_64\include\QtNetwork -IC:\Qt\5.6\msvc2015_64\include\QtCore -Idebug -I. -IC:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015 -Fodebug\ @C:\Users\ASUSPC~1\AppData\Local\Temp\login.obj.4328.47.jom
login.cpp
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory
	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\SteamKalix.vc.pdb -DUNICODE -DWIN32 -DWIN64 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\SteamKalix -I. -IE:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl -IC:\Qt\5.6\msvc2015_64\include -IC:\Qt\5.6\msvc2015_64\include\QtWidgets -IC:\Qt\5.6\msvc2015_64\include\QtGui -IC:\Qt\5.6\msvc2015_64\include\QtANGLE -IC:\Qt\5.6\msvc2015_64\include\QtNetwork -IC:\Qt\5.6\msvc2015_64\include\QtCore -Idebug -I. -IC:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015 -Fodebug\ @C:\Users\ASUSPC~1\AppData\Local\Temp\steamkalix.obj.4328.47.jom
steamkalix.cpp
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory
	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\SteamKalix.vc.pdb -DUNICODE -DWIN32 -DWIN64 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\SteamKalix -I. -IE:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl -IC:\Qt\5.6\msvc2015_64\include -IC:\Qt\5.6\msvc2015_64\include\QtWidgets -IC:\Qt\5.6\msvc2015_64\include\QtGui -IC:\Qt\5.6\msvc2015_64\include\QtANGLE -IC:\Qt\5.6\msvc2015_64\include\QtNetwork -IC:\Qt\5.6\msvc2015_64\include\QtCore -Idebug -I. -IC:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015 -Fodebug\ @C:\Users\ASUSPC~1\AppData\Local\Temp\moc_steamkalix.obj.4328.47.jom
moc_steamkalix.cpp
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory
E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include\openssl\ssl.h(15): fatal error C1083: Не удается открыть файл включение: openssl/e_os2.h: No such file or directory

**Comment by Elonnuir** [comment]
The compiler swears on a file ssl.H
![ssl](https://user-images.githubusercontent.com/28627920/27872846-d431d3e2-61b2-11e7-8dea-596e6d26917e.png)

**Comment by levitte** [comment]
Do you have `E:\OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release\OpenSSL-vc14-WIN32-release-shared\include` in your inclusion path?

**Comment by Elonnuir** [comment]
win32:CONFIG(release, debug|release): LIBS += -LE:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/lib/ -llibssl
else:win32:CONFIG(debug, debug|release): LIBS += -LE:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/lib/ -llibssld

INCLUDEPATH += E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include/openssl
DEPENDPATH += E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include/openssl

**Comment by levitte** [comment]
Remove `/openssl` at the end of the INCLUDEPATH value, possibly also the DEPENDPATH value.

`#include <openssl/e_os2.h>` merges your include path value with `openssl/e_os2.h`, which means that with the value you currently have, it will try to read `E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include/openssl/openssl/e_os2.h` when it really should read  `E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include/openssl/e_os2.h`

This is not an OpenSSL error, so I'm closing.

**Comment by Elonnuir** [comment]
In the OpenSSL build there is a file ssl.H, in the interior of this file are connected
#include <openssl / e_os2.h>
#include <openssl / opensslconf.h>
#include <openssl / comp.h>
#include <openssl / bio.h>
# If OPENSSL_API_COMPAT <0x10100000L
#include <openssl / x509.h>
#include <openssl / crypto.h>
#include <openssl / lhash.h>
#include <openssl / buffer.h>
#endif
#include <openssl / pem.h>
#include <openssl / hmac.h>
#include <openssl / async.h>

#include <openssl / safestack.h>
#include <openssl / symhacks.h>
#include <openssl / ct.h>
#include <openssl / sslerr.h>
But in the assembly there is no such file openssl.H
Do you understand me?

**Comment by richsalz** [comment]
I think we are confused.

The include line
```
#incldue <openssl/e_os2.h>
```

Is using ```openssl/``` as a relative pathname.

*there is no openssl.h* file.

**Comment by richsalz** [comment]
AARgh.  I mean that you are confused.

There is no openssl.h header file.

**Comment by levitte** [comment]
`#include <openssl/e_os2.h>` means to read `openssl/e_os2.h`, i.e. the file `e_os2.h` in the relative subdirectory `openssl`.  None if this signifies that there should be a `openssl.h`

**Comment by Elonnuir** [comment]
I then do not know the reason. But the compiler swears and points to ssl.h!

I changed the dependencies and moved the header files from the openssl folder to the include folder but it did not bring any results.

win32:CONFIG(release, debug|release): LIBS += -LE:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/lib/ -llibssl
else:win32:CONFIG(debug, debug|release): LIBS += -LE:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/lib/ -llibssld

INCLUDEPATH += E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include
DEPENDPATH += E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include

**Comment by richsalz** [comment]
I suggest you post to the openssl-users mailing list.  See https://mta.openssl.org for information on joining the list.  There are some native Russian speakers there who might be able to help you better.

There is no openssl.h header file.  You need to change your INCLUDEPATH to have the right value.

**Comment by Elonnuir** [comment]
Thank you! How difficult it is to communicate without knowing the language.

**Comment by levitte** [comment]
Do *not* move down the header files from `E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include/openssl` to `E:/OpenSSL-Libs-1.1.1buildsOpenssl-vc14-release/OpenSSL-vc14-WIN32-release-shared/include`.
*Only* modify INCLUDEPATH and DEPENDPATH like I said earlier.

**Comment by Elonnuir** [comment]
I first changed, but the result is the same.
Then I downloaded the installer http://slproweb.com/products/Win32OpenSSL.html
I thought that the problem with my build, but the result is the same.

**Comment by Elonnuir** [comment]
I found the reason !!! Thank you very much!
