### ISSUE TITLE
asn1.h and value of ub-organizational-unit-name-length

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#3872]
According to the comments in [`asn1.h`](https://github.com/openssl/openssl/blob/master/include/openssl/asn1.h) (around line 200):

```
/* size limits: this stuff is taken straight from RFC2459 */

# define ub_name                         32768
# define ub_common_name                  64
# define ub_locality_name                128
# define ub_state_name                   128
# define ub_organization_name            64
# define ub_organization_unit_name       64
# define ub_title                        64
# define ub_email_address                128
```

Both [RFC 2459](https://www.ietf.org/rfc/rfc2459.txt) and [RFC 5280](https://www.ietf.org/rfc/rfc5280.txt) specify `ub_organization_unit_name` as 32, not 64:

```
ub-organizational-unit-name-length INTEGER ::= 32
```

And the latest X.509 standards appear to removes the constraints. From [Amendment to CABF Baseline Requirements](https://mailarchive.ietf.org/arch/msg/pkix/nWgnNZHh2w2l-WfbHKozpm2IWcQ) on the PKIX mailing list (from [Peter Bowen's comment on April 6](https://mailarchive.ietf.org/arch/msg/pkix/igWz36OccWv2NIjuRNkE1aBaW2c)):

> It [the incompatibilities, sic] is even worse. 7th and 8th (and maybe prior releases) removed the usage of ub- from the schema. The schema itself no longer bounds DirectoryStrings and X.509 explicitly says they are unbounded. 

Based on the above information, OpenSSL could produce certificates that cannot be consumed by some clients. And clients that want to follow CA/B Forum issuing policie may not be able to do so.

**Comment by levitte** [comment]
There are two different sizes that apply to organizational unit names, one called `ub-organizational-unit-name`, which *is* 64, and the other called `ub-organizational-unit-name-length`, which is indeed 32.

Now, if you study the ASN.1 code in RFC 5280, the former applies to X.520 attributes, i.e. to subject and issuer names, which is what these constants deal with.  So libcrypto is not at fault here.

Closing this.
