### ISSUE TITLE
openssl-1.0.2l make depend fails on Solaris

### ISSUE THREAD

**Issue by pschaef** [openssl/openssl#3874]
I am trying to compile openssl 1.0.2l on solaris with algorithms disabled. This requires to invoke 'make depend' which fails: 

$./config threads no-idea no-mdc2 no-rc5
.....
Since you've disabled or enabled at least one algorithm, you need to do
the following before building:

        make depend

```
Configured for solaris-sparcv9-cc.
$ make depend
making depend in crypto...
make[1]: Entering directory `/home1/pschaef/tmp/openssl-1.0.2l/crypto'
makedepend: syntax error at line 1: `(' unexpected
mv: cannot access Makefile.new
make[1]: *** [depend] Error 2
make[1]: Leaving directory `/home1/pschaef/tmp/openssl-1.0.2l/crypto'
make: *** [depend] Error 1
```

Notes:
- The same issue also already exists in openssl-1.0.2j. I had not tried with other versions yet.
- makedepend is located in /usr/openwin/bin

**Comment by richsalz** [comment]
What happens when you just type "makedepend" at a shell prompt?
what does ``` head -1 `which makedepend` ``` show?
This appears to be a solaris/openwin issue, and not an openssl issue.
you might be able to edit util/domd to set the $MAKEDEPEND variable to the right invocation.

**Comment by pschaef** [comment]
$ makedepend
makedepend: syntax error at line 1: `(' unexpected

makedepend is an ELF executable, no shell script:
$ head -1 `which makedepend`             
ELF4it4 (44���W�W�`Oa�bb�/usr/lib/ld.so.1�R�=-e8T<I�c`LZl v�"h51pn�@dMs+0��iY_N!t�;r.Ubqf�uWE��w*kya�|~OJHP${V��:B]#&/,DCF42KQ>?A()XG'7%9^\xg3zoSmj}���x�
                                      <T Vl
$ 
$ which makedepend
/usr/openwin/bin/makedepend

I don't know which makedepend executable could be referenced instead in domd. 
/usr/openwin/bin/makedepend seems to be the correct and only choice but it has issues with the file(s) it is intended to work with

**Comment by levitte** [comment]
> ```
> $ makedepend
> makedepend: syntax error at line 1: `(' unexpected
> ```

Now, *that's* interesting!  What, exactly, is it that `makedepend` tries to read here?  Could that be determined somehow?  (I'd use something like `strace` on Linux, but cannot remember if that's available on Solaris).

**Comment by pschaef** [comment]
I think truss is the equivalent on Solaris.

This is the output of truss makedepend.
...
open64("/usr/openwin/bin/makedepend", O_RDONLY) = 3
close(19)                                       Err#9 EBADF
fcntl(3, F_DUPFD, 0x00000013)                   = 19
close(3)                                        = 0
fcntl(19, F_SETFD, 0x00000001)                  = 0
ioctl(2, TCGETA, 0xFFBEFC0C)                    = 0
ioctl(19, TCGETA, 0xFFBEFC0C)                   Err#25 ENOTTY
read(19, "7F E L F0102010202010115".., 128)     = 128
getuid()                                        = 1033 [1033]
stat64("/usr/binELF4it4", 0xFFBEF988) Err#2 ENOENT
stat64("/binELF4it4", 0xFFBEF988)      Err#2 ENOENT
stat64("/usr/sbinELF4it4", 0xFFBEF988) Err#2 ENOENT
stat64("/sbinELF4it4", 0xFFBEF988)     Err#2 ENOENT
stat64("/usr/local/binELF4it4", 0xFFBEF988) Err#2 ENOENT
stat64("/home/opt/SunStudio-12/SUNWspro/binELF4it4", 0xFFBEF988) Err#2 ENOENT
stat64("/usr/openwin/binELF4it4", 0xFFBEF988) Err#2 ENOENT
/usr/openwin/bin/makedependwrite(2, " / u s r / o p e n w i n".., 27)   = 27
: write(2, " :  ", 2)                           = 2
syntax errorwrite(2, " s y n t a x   e r r o r", 12)    = 12
 at line write(2, "   a t   l i n e  ", 9)              = 9
1write(2, " 1", 1)                              = 1
: write(2, " :  ", 2)                           = 2
`write(2, " `", 1)                              = 1
(write(2, " (", 1)                              = 1
'write(2, " '", 1)                              = 1
 unexpectedwrite(2, "   u n e x p e c t e d", 11)               = 11

write(2, "\n", 1)                               = 1
llseek(0, 0, SEEK_CUR)                          = 205512
_exit(2)

**Comment by levitte** [comment]
Those stat64 lines make me think something is very odd with your makedepend...  Of course, it might be embedded backspace characters that play tricks...

Anyhow, this clearly indicates that the issue isn't with us.

**Comment by richsalz** [comment]
It is very strange that if you type it the  command line it gets an error.  Something is strange/wrong/broken in your local environment, I think.
