### ISSUE TITLE
[TEMP. FIX] undefined reference to `pthread_atfork'

### ISSUE THREAD

**Issue by concatime** [openssl/openssl#3884]
Hi. I'm trying to build Nginx with this [script](https://gist.github.com/concatime/408a0d8dc3e3a1973ba5f38012f3753f), but I get this error.
```
objs/addon/src/ngx_http_brotli_filter_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lpthread -lcrypt -lm ../pcre-8.41/.libs/libpcre.a ../openssl/.openssl/lib/libssl.a ../openssl/.openssl/lib/libcrypto.a -ldl ../libatomic_ops-7.6.0/src/libatomic_ops.a \
-Wl,-E
../openssl/.openssl/lib/libcrypto.a(threads_pthread.o): In function `openssl_init_fork_handlers':
threads_pthread.c:(.text+0x1ba): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:309: objs/nginx] Error 1
```
I was able to build two weeks ago, so this issue must be new.

[EDIT] See the temporary [fix](https://github.com/openssl/openssl/issues/3884#issuecomment-313857555).

**Comment by richsalz** [comment]
What platform?  Pthread_atfork is a standard API in pthreads library.

**Comment by concatime** [comment]
Well, I tried on my server, which is Debian 9 from OVH, and on my desktop, OpenSUSE Tumbleweed. Both with the same result. I used gcc-7/g++-7, maybe because of this?

**Comment by concatime** [comment]
Well, this error happens also with gcc/g++ 6.

**Comment by richsalz** [comment]
It’s the pthreads library.

**Comment by t-j-h** [comment]
Note: pthread_atfork can be in libc rather than libpthreads.

**Comment by richsalz** [comment]
Yes, good point.

Either way, is it reasonable for us to assume that pthread_atfork exists if posix threads is used on Linux?  Or do we need another
Compile flag?

**Comment by levitte** [comment]
It looks to me like this is an order problem:

```
objs/addon/src/ngx_http_brotli_filter_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lpthread -lcrypt -lm ../pcre-8.41/.libs/libpcre.a ../openssl/.openssl/lib/libssl.a ../openssl/.openssl/lib/libcrypto.a -ldl ../libatomic_ops-7.6.0/src/libatomic_ops.a \
-Wl,-E
```

Shouldn't `-lpthread` appear last to make sure the symbol references in `libcrypto.a` get properly resolved?

**Comment by kroeckx** [comment]
You should use "-pthread", not "-lpthread".

-lpthread will probably also work if you move it to the end of the
libraries.

For some reason you're also using a static version of all the
libraries. I suggest you use shared versions instead if you can.
Your OS should already provide shared versions of those libraries.

**Comment by paulidale** [comment]
I'm with @levitte the -lpthread should be later in the command line.  After the .a files.
You shouldn't need it twice.  -ldl is there twice too.

That is more like:
```
objs/addon/src/ngx_http_brotli_filter_module.o \
objs/ngx_modules.o \
 ../pcre-8.41/.libs/libpcre.a ../openssl/.openssl/lib/libssl.a ../openssl/.openssl/lib/libcrypto.a ../libatomic_ops-7.6.0/src/libatomic_ops.a \
-ldl -lpthread -lpthread -lcrypt -lm -Wl,-E
```

**Comment by concatime** [comment]
So finally, It seems that the Nginx configuration file is quite odd. So the the temporary solution for now is a hack. After running the `./configure`, in `obj/Makefile`, you should remove  the first `-lpthread` and move the second the end of the line before `"`. Since the github repo of Nginx is just a mirror, I can't submit an issue about this.

**Comment by concatime** [comment]
We should leave this post open since Nginx has not yet patched this.

**Comment by richsalz** [comment]
We're glad you got it working.  You can still open an issue with nginx.  OpenSSL's GH repo is just a downstream clone and we take issues :)  This will come up for anyone who is building from master and the next release.  Their config file was wrong and they just got lucky until now.

**Comment by t0mtaylor** [comment]
this worked for me:

`-L ../openssl-dev/.openssl/lib/ -ldl -lcrypt -lm ../pcre-8.39/.libs/libpcre.a ../openssl-dev/.openssl/lib/libssl.a ../openssl-dev/.openssl/lib/libcrypto.a -ldl ../zlib-1.2.8/libz.a -lpthread \
	-Wl,-E`

**Comment by levitte** [comment]
Hmm, there was another issue where someone complained that our `libcrypto.pc` didn't have the necessary options to have the pthread library be part of the final link. Does nginx us pkgconfig files to figure out compile and link options? Then that might be the issue, and that falls back on us.

**Comment by meilihao** [comment]
Today i get the same problem when use `--with-openssl=../openssl-master --with-openssl-opt='enable-tls1_3'`:
```
../openssl-master/.openssl/lib/libcrypto.a(threads_pthread.o)：In function ‘fork_once_func’：
threads_pthread.c:(.text+0x16)：undefined reference to `pthread_atfork'
```
OS: CentOS Linux release 7.4.1708 (Core)
nginx: nginx-1.13.5
openssl : d2ef6e4

**Comment by meilihao** [comment]
And i add `-pthread` to `--with-cc-opt` to build again, but get a same error:
```sh
...
-Wl,-z,relro -Wl,-z,now -pie -ldl -lpthread -lcrypt -lpcre ../openssl-master/.openssl/lib/libssl.a ../openssl-master/.openssl/lib/libcrypto.a -ldl -lz \
-Wl,-E
../openssl-master/.openssl/lib/libcrypto.a(threads_pthread.o)：In function ‘fork_once_func’：
threads_pthread.c:(.text+0x16)：undefined reference to 'pthread_atfork'
```

**Comment by meilihao** [comment]
[I solved this by concatime's solution ](https://github.com/openssl/openssl/issues/3884#issuecomment-313857555)

**Comment by levitte** [comment]
Yeah, it's a solution, but kind of a hack. If we're at fault, I will gladly resolve it, but maybe not this week (out travelling)

**Comment by dsamarin** [comment]
For those who want a scripted temporary solution: 

```sh
gawk -i inplace \
  '/pthread/ { sub(/-lpthread /, ""); sub(/-lpthread /, ""); sub(/\\/, "-lpthread \\"); print } ! /pthread/ { print }' \
  "objs/Makefile"
```

**Comment by mattcaswell** [comment]
@levitte - do we need to do something here?

**Comment by levitte** [comment]
Yes, we do, we need to make sure that `-pthread` is part of `ex_libs` in config targets where this is present in cflags.  That way, it will end up in `Libs.private` in libcrypto.pc

**Comment by levitte** [comment]
Fixes in #5134 (master) and #5135 (1.1.0)

**Comment by khs1994** [comment]
nginx 1.13.11 fix

* https://github.com/nginx/nginx/commit/90ca1071b77b0fbb4373ae052b1242023295513f

**Comment by ReK2Fernandez** [comment]
Hello Im having this same issue under
```
Ubuntu 18.04.3 LTS
```
with:
```
  8%] Linking CXX executable test_cypher_suites
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make:113: recipe for target 'libraries/fc/test/crypto/test_cypher_suites' failed
make[2]: *** [libraries/fc/test/crypto/test_cypher_suites] Error 1
CMakeFiles/Makefile2:789: recipe for target 'libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all' failed
make[1]: *** [libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
none of the work around did work for me, because I can't downgrade to that version with apt

**Comment by levitte** [comment]
You should look into the order in which the linking command line gets the different libraries, which means you need to tell your make to be a bit more verbose

**Comment by SergeyJames** [comment]
In my case building of [openssl](https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1h)  with flag  **no-threads**, was the solution:
```code
./config  no-threads
```

**Comment by ccy234** [comment]
> And i add `-pthread` to `--with-cc-opt` to build again, but get a same error:
> 
> ```shell
> ...
> -Wl,-z,relro -Wl,-z,now -pie -ldl -lpthread -lcrypt -lpcre ../openssl-master/.openssl/lib/libssl.a ../openssl-master/.openssl/lib/libcrypto.a -ldl -lz \
> -Wl,-E
> ../openssl-master/.openssl/lib/libcrypto.a(threads_pthread.o)：In function ‘fork_once_func’：
> threads_pthread.c:(.text+0x16)：undefined reference to 'pthread_atfork'
> ```

you should use  "--with-ld-opt=-pthread"
