### ISSUE TITLE
X509_SIG_INFO_get/set not usable

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#3894]
These two new API fuctions are not usable because it is impossible to get a X509_SIG_INFO
data value unless you have an access function for X509's SIG_INFO member.

There is `X509_get_signature_info` which extracts the data from the X509's SIG_INFO member.
I suppose that is an internal API, and should move to a different header file.

**Comment by bernd-edlinger** [comment]
in doc/man3/X509_get0_signature.pod this is written:
```
X509_SIG_INFO_get() and X509_SIG_INFO_set() get and set information
about a signature in an B<X509_SIG_INFO> structure. They are only
used by implementations of algorithms which need to set custom
signature information: most applications will never need to call
them.
```

But X509_SIG_INFO is opaque, and therefore it is impossible to
use these two APIs.  Is this use case realistic?

Either make X509_SIG_INFO a non-opaque
or better make this API internal?

**Comment by kaduk** [comment]
My impression when looking at this before was that the API was in practice more of an internal API than a public one, but of course we cannot actually remove public APIs in a stable release branch.

**Comment by bernd-edlinger** [comment]
It is a new API in 1.1.1, so now is the only time when we can remove it.

**Comment by levitte** [comment]
I don't understand how these functions aren't usable.  Unless I'm mistaken, at least `X509_SIG_INFO_set` is crucial to anyone who defines the `siginf_set` function in `EVP_PKEY_ASN1_METHOD`.

Are you really saying that the API for `X509_SIG_INFO` is incomplete, i.e. it lacks a creator and a destructor?  Or that we lack an API for setting the `siginf_set` field in a `EVP_PKEY_ASN1_METHOD`?  Both are certainly true.

**Comment by bernd-edlinger** [comment]
Yes, X509_SIG_INFO has no definition in public headers.

**Comment by bernd-edlinger** [comment]
And if I need that information I use X509_get_signature_info all the time.

**Comment by levitte** [comment]
> Yes, X509_SIG_INFO has no definition in public headers.

That's certainly not true, [it is defined](https://github.com/openssl/openssl/blob/master/include/openssl/ossl_typ.h#L136), it's just opaque...  which is the way we want to go.

> And if I need that information I use X509_get_signature_info all the time.

Ah, so does that mean that the issue is really about `X509_SIG_INFO_get`?  Or so you have issues with `X509_SIG_INFO_set` as well?

**Comment by levitte** [comment]
I'll have you note that `X509_get_signature_info` does a little bit more than `X509_SIG_INFO_get`...

**Comment by bernd-edlinger** [comment]
Naming a use case for X509_SIG_INFO_get/set would be a start.

**Comment by levitte** [comment]
My first comment was about the use of `X509_SIG_INFO_set` (please stop ignoring that).
As for `X509_SIG_INFO_get`, I currently don't have one, I' guessing it was thrown in for orthogonality (which does make sense from an esthetic point of view).

**Comment by bernd-edlinger** [comment]
I am just wondering what the application is supposed to do with X509_SIG_INFO_set.
I call that the use case:

```
X509_SIG_INFO info;
X509_SIG_INFO_set(&info, a, b, c, d);
```
and the only possible next action is:
`X509_SIG_INFO_get(&info, &a, &b, &c, &d);
`
However the application can't declare info because it is opaque.

**Comment by levitte** [comment]
This is of course impossible:

``` C
X509_SIG_INFO info;
```

`EVP_PKEY_ASN1_METHOD`'s `siginf_set` receives an already allocated `X509_SIG_INFO`, that's where `X509_SIG_INFO_set` comes in handy (as a current example).

> However the application can't declare info because it is opaque.

So you want a creator and a destructor.  Feel free to make that PR!  ;-)
(I'm currently busy extending the API for `EVP_PKEY_ASN1_METHOD` to be able to actually set `siginf_set`...  that was definitely lacking!)

**Comment by levitte** [comment]
#4589 extends the API for creating `EVP_PKEY_ASN1_METHOD` to set `siginf_set` among others...  that's a crucial missing piece in this discussion.

**Comment by richsalz** [comment]
I think @bernd-edlinger was saying we don't need to expose ANY functions for this datatype.
And if we want to, since it is only in master, we can do so.

**Comment by levitte** [comment]
Sure, and I state that for any `EVP_PKEY_ASN1_METHOD` that needs custom siginfo, we need to publish these functions.

**Comment by bernd-edlinger** [comment]
In the moment it looks like this API is isolated from the rest of the APIs.
But as soon as there is a use case for this API, everything will probably be more clear.
In the moment I don't see the use case.

**Comment by bernd-edlinger** [comment]
Okay, @levitte's PR #4589 fixes this issue.
