### ISSUE TITLE
OSSL_STORE doesn't work well with file names that have a device name in the path

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#3897]
This affects Windows and VMS.  Paths like `C:\foo\bar.pem` or `dev:[foo]bar.pem` error out with "unsupported scheme".  The original intention was that `STORE_open` would detect such paths to the best of its ability and treat them using the "file" scheme (and the "file" scheme loader would of course be able to handle them correctly as well).

-----

Note: this is first of all a reminder to myself to fix this.  Participation is welcome nonetheless.

**Comment by mattcaswell** [comment]
Linked PR was merged so closing.
