### ISSUE TITLE
shared library without version suffix for android (feature request)

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#3902]
Although Android loader support shared libraries with version suffix (foo.so.1.2.3) package manager does not suffixes. 

This is request to enhance build process to allow redefinition of shared library format on certain platforms. 
What about for android builds to use SHARED_NAME from build.info to define library name formats?

**Comment by INRIX-joel-winarske** [comment]
This has a few clues on how to do it.
https://stackoverflow.com/questions/24204366/how-to-build-openssl-as-unversioned-shared-lib-for-android

**Comment by levitte** [comment]
Have a look at #3964 and tell me if that helps.  The example in the description should be what you're looking for, right?

**Comment by levitte** [comment]
Note that I can't justify better support than this.  I consider removing the SOVER info to be dangerous, generally speaking, so I cannot see myself implementing it as something configurable.

**Comment by t-j-h** [comment]
I don't consider removing SOVER at all dangerous (generally or specifically speaking) and making users that need/want that functionality jump through a pile of hoops to get there wouldn't be my first choice :-)

**Comment by levitte** [comment]
This is a fairly minimal hoop to jump through ;-)

```
$ make SHLIB_VERSION_NUMBER= SHLIB_EXT=.so
```

Re danger, I disagree.  Just think of upgrading a 1.0.2 `libcrypto.so` to a 1.1.0 one.  There would be *no* information about the major bump, and you'd see apps go *KABOOM* left and right.

**Comment by dot-asm** [comment]
> Re danger

It's not only about what users *can* do, but even examples you give. What I'm trying to say is that `make SHLIB_EXT='.$(SHLIB_VERSION_NUMBER).so'` might be better example?

**Comment by levitte** [comment]
@dot-asm, sure, that works too.  It's just, I know nothing about Android and what the package manager can deal with, so I relied entirely on the original text of this issue.  If it works to have the SOVER before `.so` instead of after (and also have it be part of SONAME in the libraries themselves) then sure!

**Comment by levitte** [comment]
I changed the commit message accordingly

**Comment by petrovr** [comment]
Richard Levitte wrote:
> @dot-asm, sure, that works too.  It's just, I know nothing about Android and what the package manager can deal with, so I relied entirely on the original text of this issue.  If it works to have the SOVER before `.so` instead of after (and also have it be part of SONAME in the libraries themselves) then sure!
>
Actually  there are tho phases
1) creation of package ( apk-file from gradle build system)
2) installation by package manager (pm) on device
Issue is with (2) pm

./$ARCH/libcrypto.so.1is peeked by build system(1) but not installed by 
pm (2) .

According to my notes:
a)  (1) and (2) should process ./$ARCH/libcrypto$XXX.so.
b) lib prefiix is required for installation. i.e. ./$ARCH/crypto-$XXX.so 
is packaged but not installed .


Currently I use name format ./$ARCH/libcrypto.so and library (peeked 
according to device architecture)  is installed into <application native 
library path>

Definitions like SHARED_SUFFIX='.$(SHLIB_VERSION_NUMBER).so' seems to me 
possible solution. It could allow use of name in "release format" : 
"-<version>.so'.

Additional comments on #3964 .

**Comment by INRIX-joel-winarske** [comment]
I tried these changes, building with 
`make SHLIB_VERSION_NUMBER= SHLIB_EXT=.so`

```
$ readelf -d libssl.so 

Dynamic section at offset 0x4277c contains 30 entries:
  Tag        Type                         Name/Value
 0x00000003 (PLTGOT)                     0x4392c
 0x00000002 (PLTRELSZ)                   3472 (bytes)
 0x00000017 (JMPREL)                     0xc4fc
 0x00000014 (PLTREL)                     REL
 0x00000011 (REL)                        0x94cc
 0x00000012 (RELSZ)                      12336 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffa (RELCOUNT)                   1512
 0x00000006 (SYMTAB)                     0x148
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000005 (STRTAB)                     0x36b8
 0x0000000a (STRSZ)                      16671 (bytes)
 0x00000004 (HASH)                       0x77d8
 0x00000001 (NEEDED)                     Shared library: [libcrypto.so.1.1]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x0000000e (SONAME)                     Library soname: [libssl.so.1.1]
 0x0000001a (FINI_ARRAY)                 0x429f8
 0x0000001c (FINI_ARRAYSZ)               8 (bytes)
 0x00000019 (INIT_ARRAY)                 0x43778
 0x0000001b (INIT_ARRAYSZ)               4 (bytes)
 0x00000010 (SYMBOLIC)                   0x0
 0x0000001e (FLAGS)                      SYMBOLIC BIND_NOW
 0x6ffffffb (FLAGS_1)                    Flags: NOW NODELETE
 0x6ffffff0 (VERSYM)                     0x8d60
 0x6ffffffc (VERDEF)                     0x9410
 0x6ffffffd (VERDEFNUM)                  3
 0x6ffffffe (VERNEED)                    0x946c
 0x6fffffff (VERNEEDNUM)                 2
 0x00000000 (NULL)                       0x0
$ readelf -d libcrypto.so

Dynamic section at offset 0x181850 contains 29 entries:
  Tag        Type                         Name/Value
 0x00000003 (PLTGOT)                     0x182e1c
 0x00000002 (PLTRELSZ)                   944 (bytes)
 0x00000017 (JMPREL)                     0x3ee70
 0x00000014 (PLTREL)                     REL
 0x00000011 (REL)                        0x2e300
 0x00000012 (RELSZ)                      68464 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffa (RELCOUNT)                   8551
 0x00000006 (SYMTAB)                     0x148
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000005 (STRTAB)                     0x10658
 0x0000000a (STRSZ)                      80289 (bytes)
 0x00000004 (HASH)                       0x23ffc
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x0000000e (SONAME)                     Library soname: [libcrypto.so.1.1]
 0x0000001a (FINI_ARRAY)                 0x17e650
 0x0000001c (FINI_ARRAYSZ)               8 (bytes)
 0x00000019 (INIT_ARRAY)                 0x18284c
 0x0000001b (INIT_ARRAYSZ)               4 (bytes)
 0x00000010 (SYMBOLIC)                   0x0
 0x0000001e (FLAGS)                      SYMBOLIC BIND_NOW
 0x6ffffffb (FLAGS_1)                    Flags: NOW NODELETE
 0x6ffffff0 (VERSYM)                     0x2c154
 0x6ffffffc (VERDEF)                     0x2e1f8
 0x6ffffffd (VERDEFNUM)                  6
 0x6ffffffe (VERNEED)                    0x2e2c0
 0x6fffffff (VERNEEDNUM)                 2
 0x00000000 (NULL)                       0x0

```

Android requires the dynamic libs to only referenced non-versioned for "NEEDED" value.
Android uses dlopen(), which uses the "NEEDED" value from the so, to load dependencies.  If a versioned library is referenced, it will fail.  The packaging tool does not allow numbered .so files.  You can rename a file, and fake it, but it will fail to load due to a missing dependency.

So for the case of libssl.so readelf- d should return "Shared library: [libcrypto.so]"

hth

**Comment by Neph0** [comment]
Hello,

What's the status on this? I'm in need of a versionless shared library (for the same reasons than above). I've tried using `make SHLIB_VERSION_NUMBER= SHLIB_EXT=.so`, but it doesn't work.

Thanks in advance.

**Comment by mattcaswell** [comment]
> I've tried using make SHLIB_VERSION_NUMBER= SHLIB_EXT=.so, but it doesn't work.

What version of OpenSSL did you use? The functionality to do this is only in 1.1.1/master

**Comment by Neph0** [comment]
Oh, I see.

I was trying using the 1.1.0g version. Thanks for the answer!

**Comment by petrovr** [comment]
Thomas Barusseau wrote:
> Oh, I see.
>
> I was trying using the 1.1.0g version. Thanks for the answer!
>

For protocol : solution for 1.1.0* is to android generic targets in 
10-main.conf to add:
shared_extension => ".so",

Perhaps not so flexible as master (upcoming 1.1.1) but acceptable.


Regards,
Roumen Petrov

**Comment by endragor** [comment]
Is this supposed to work with 1.0.2o and `./Configure android-x86`? `./Configure` doesn't allow to specify SHLIB_* parameters and `make` seems to ignore them, i.e. `make SHLIB_VERSION_NUMBER= SHLIB_EXT=.so` didn't work. Is there a way to remove .so suffix when building 1.0.2o release?

**Comment by manjunath143** [comment]
make SHLIB_VERSION_NUMBER= SHLIB_EXT=.so

Hi Friends , 
Does this work with  openssl 1.1.1b ?
Or there are different commands ?
