### ISSUE TITLE
openssl 1.1.0f

### ISSUE THREAD

**Issue by naiefe** [openssl/openssl#3908]
when downloading the openssl 1.1.0f trying to install it on linux error occur 

tried on centos 5 & centos 7 

see error:-

make: *** No rule to make target `clean'.  Stop.

i think there is missing files in it

**Comment by richsalz** [comment]
You cannot do any make at all until you run config.
Please see the INSTALL instructions.

**Comment by naiefe** [comment]
-bash: ./config: No such file or directory

**Comment by naiefe** [comment]
ok thanks got it there was no permission for thr ./config i used chmod 77 and it s work fine now
