### ISSUE TITLE
CAPI like engine for Mac and Linux?

### ISSUE THREAD

**Issue by art926** [openssl/openssl#3919]
We really need to support client certificates with non-exportable private keys in our very big project, that uses OpenSSL. Is there an alternative for CAPI engine in OpenSSL for Mac and Linux? If not, is it planned to be added any time soon?

**Comment by levitte** [comment]
There is a [pkcs#11 engine](https://github.com/OpenSC/engine_pkcs11).  Not provided by us, though, but is actively developed.
