### ISSUE TITLE
cannot decrypt file encrypted with different version?!

### ISSUE THREAD

**Issue by undermydesk** [openssl/openssl#3928]
Dear all,

just stumbled about this one... 

encrypt a file (with only some ASCII text) on FreeBSD 10.3 stable (OpenSSL 1.0.1u-freebsd  22 Sep 2016):

_openssl aes-256-cbc -a -salt -in hello-world.txt -out hello-world.txt.enc_

and tried to decrypt this (hello-world.txt.enc) on Debian Stretch (OpenSSL 1.1.0f  25 May 2017):

_openssl aes-256-cbc -d -a -in hello-world.txt.enc_

fails (returns only garbage) with:

bad decrypt
140584895280384:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:535:

(doing the same the other way around gives
   encrypt on Debian Stretch with 1.1.0f
   decrypt on FreeBSD 10.3 stable with 1.0.1u

bad decrypt
34379303800:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:/usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/evp/evp_enc.c:516:
)

Is this really expected behaviour?!

Thankyou!

**Comment by kaduk** [comment]
https://www.openssl.org/docs/faq.html#USER3

specify '-md md5' to get the older (less secure) behavior.

**Comment by richsalz** [comment]
https://www.openssl.org/docs/faq.html#USER3
