### ISSUE TITLE
enhancement request -- display Subject Alternative Name

### ISSUE THREAD

**Issue by hymie0** [openssl/openssl#3932]
Greetings.  It's possible that I have no idea what I'm talking about, so bear with me and please be kind.

`openssl` has the `x509` command to (among other things) display information about a certificate; for example

    $ openssl x509 -in mycert.pem -noout -dates
    notBefore=Jun 30 11:47:03 2017 GMT
    notAfter=Jun 30 11:47:03 2020 GMT

However, as far as I can tell, there is no option to specify the "X509v3 Extensions" or any specific extension.  You can view them by disabling everything else, such as

    $ openssl x509 -in mycert.pem -noout -text -certopt no_subject,no_header,no_version,no_serial,[...]

but that gets long and ugly.

The point being... it's my understanding that the "Subject Alternative Name" is becoming a very important value in the certificate.  Even though it is buried inside the X509v3 Extensions, it would be very nice if the `openssl x509` command had an option to easily display the SAN like it does with the subject or dates.

Thank you for your consideration.

**Comment by richsalz** [comment]
yes, that would be useful to have.
no plans to do it, although a PR would be useful.

**Comment by levitte** [comment]
I agree that it would be useful.  PR welcome ;-)

**Comment by InfoHunter** [comment]
I've made a proposal to resolve this.

`openssl x509 -ext subjectAltName ...`

**Comment by nickthetait** [comment]
Relevant PR for this issue has been merged, this issue can be closed
