### ISSUE TITLE
Using OpenSSL with LKL's non-blocking sockets

### ISSUE THREAD

**Issue by speedingdaemon** [openssl/openssl#3937]
I have a polling server code that works without any issues if I don't use LKL APIs.
But when I replaced with LKL APIs, I am getting following error (printed in my application code) with SSL_accept:
[ERROR]: FATAL SSL_retcode for OPERATION=SSL_ACCEPT Retcode=5 Error:error:00000000:lib(0):func(0):reason(0)

Here, Retcode=5 corresponds to SSL_ERROR_SYSCALL in OpenSSL.
This is the place (in openssl/ssl/statem/statem.c) that is causing state_machine() to return -1 for SSL_accept call:
while (st->state != MSG_FLOW_FINISHED) {
if (st->state == MSG_FLOW_READING) {
ssret = read_state_machine(s);
if (ssret == SUB_STATE_FINISHED) {
st->state = MSG_FLOW_WRITING;
init_write_state_machine(s);
} else {
/* NBIO or error */ 
goto end;    <<<<<<<<===== this one
}
This is the bt:
#0 state_machine (s=0x56391929fff0, server=1) at ssl/statem/statem.c:398
#1 0x00007f4a0b934734 in ossl_statem_accept (s=0x56391929fff0) at ssl/statem/statem.c:234
#2 0x00007f4a0b92bd27 in ssl_do_handshake_intern (vargs=0x56391929dbb0) at ssl/ssl_lib.c:3303
#3 0x00007f4a0b4b57b0 in async_start_func () at crypto/async/async.c:154
#4 0x00007f4a0ae81a90 in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Any clue on what am I missing?

Has anyone tried a simple LKL-based server that also uses OpenSSL?

**Comment by bernd-edlinger** [comment]
just a guess:  what did the accept return ?

**Comment by fenrig** [comment]
Could you look at the following issue, and the title and original description are due to a misdiagnosis but its explained in one of the comments. Though I believe our issues are quite common:
https://github.com/openssl/openssl/issues/3962

**Comment by mattcaswell** [comment]
No response from the original OP to @bernd-edlinger. Closing.
