### ISSUE TITLE
Docs for "without p11-kit"

### ISSUE THREAD

**Issue by bmomjian** [openssl/openssl#3960]
This URL:

    https://github.com/OpenSC/libp11

explains how to configure the OpenSSL config file to know about the libraries under the heading "Using in systems without p11-kit,", but at the bottom it explains that you have to "provide the engine configuration explicitly."  I think the second part is unnecessary if the first part is done properly.

**Comment by levitte** [comment]
Ok.  I wonder, though, why you're saying this here and not [there](https://github.com/OpenSC/libp11/issues)...  I do notice [#165](https://github.com/OpenSC/libp11/issues/165), though.

So uhmm, I'm confused, I do not understand what you want from us.

**Comment by bmomjian** [comment]
Wow, I have no idea how I accidentally got in here.  Sorry.

**Comment by levitte** [comment]
Ah, a mistake.  That's cool :-)
