### ISSUE TITLE
fflush(NULL) or printf("...\n") in  ssl/statem/statem.c fixes syserror with return code 0 (which indicates EOF)

### ISSUE THREAD

**Issue by fenrig** [openssl/openssl#3962]
Hi I've been debugging openssl 1.1.0f on rpi3 (aarch64). I'm having this issue with s_client and my own client code.
Note 1) on my host the same command with the same input files made the connection succeed so there is something with openssl on the target system
Note 2) the openssl s_client command: 
> openssl s_client -connect 192.168.10.174 -CAfile server_rootCA.pem -debug -cert 011a.cert -key 011a.privkey -cipher AES128-SHA256:AES256-SHA256

Protocol wise this is happening AFTER server_hello (after this message the socket get -1 and close on both ends).

So I traced the error to BIO_do_connect() which is an alias for BIO_do_handshake() which is an alias for BIO_ctrl(). Which you guys probably already know.

!!! the following is a misdiagnosis and is not relevant anymore to the issue !!! (put it in bold font)

**So I will be adding my printout in the openssl code (the prints move the the corresponding lines so I've added the function as the 3 parameter in my printout). I've added the prints starting from BIO_do_connect().**

[openssl_printout.txt](https://github.com/openssl/openssl/files/1157945/openssl_printout.txt)

**Though I've narrowed the issue down to BIO_ctrl which is called with BIO_CTRL_PUSH (=6) as the cmd argument and then BIO_ctrl calling b->method->ctrl() which in the error case I traced back to conn_ctrl(), which is being called with cmd BIO_CTRL_PUSH. 
And conn_ctrl() has not implemented BIO_CTRL_PUSH in the switch, so the default case is called which returns 0 and causes BIO_do_connect() to issue an error after shutting down the socket.**

**Comment by fenrig** [comment]
Additional note: I've had the exact same issue on openssl 1.1.0e, but didnt debug that version (though its probably the exact problem as it had the exact same issue/symptoms)

**Comment by levitte** [comment]
Ok, so this is confusing...  so let's start with a few easily grepable facts:

1.   `s_client` doesn't use `BIO_do_connect`...  or `BIO_do_handshake` for that matter.
2.   There's only one place where `BIO_CTRL_PUSH` is used in a `BIO_ctrl` call, and that's in `BIO_push`...  the result of that `BIO_ctrl` call *is ignored*, so can't generate an error.

So, errrr, I can't quite tell you where that error comes from.

Looking at your trace, I'm noticing this line:

```
crypto/bio/bio_lib.c: 515: BIO_ctrl: ret: -1
```

That's the probably cause of your issue...  However, it's unclear to me what `BIO_ctrl` call this was, so it might be a good idea to repeat the list of `BIO_ctrl` arguments on this line to make sure we know what it is about.

**Comment by fenrig** [comment]
Oh okay I've added it to the case but its still failing so obviously you are right :D I'll look further :)

**Comment by fenrig** [comment]
okay so the original description is wrong, but I found the the culprit (more or less).

When I add a specific print to statem.c (<openssl>/ssl/statem/statem.c) in the function state_machine the error doesnt happen.

you can find more info in this gist:
https://gist.github.com/fenrig/62b29d97e64837462ae8634193049b50#file-statem-c-L208

**Comment by fenrig** [comment]
my issue is quite common to following issue posted 5 days ago:
https://github.com/openssl/openssl/issues/3937

**Comment by mattcaswell** [comment]
What is the server in this scenario? Is that also openssl (if so what version)? Can you recompile with the enable-ssl-trace config option and then run s_client with the -trace command line option and post the output?

**Comment by fenrig** [comment]
okay so server is running on archlinux using openssl s_server [x86-64]
I'll recompile the s_client on target (RPI3 with a very minimal linux enviroment) [aarch64]

Both are version 1.1.0f

**Comment by fenrig** [comment]
with fflush
[with_fflush_s_client.txt](https://github.com/openssl/openssl/files/1162421/with_fflush_s_client.txt) [aarch64]
[with_fflush_s_server.txt](https://github.com/openssl/openssl/files/1162422/with_fflush_s_server.txt) [x86_64]

**Comment by mattcaswell** [comment]
I meant without fflush.

**Comment by fenrig** [comment]
without fflush
[without_fflush_s_client.txt](https://github.com/openssl/openssl/files/1162438/without_fflush_s_client.txt) [aarch64]
[without_fflush_s_server.txt](https://github.com/openssl/openssl/files/1162439/without_fflush_s_server.txt) [x86-64]

**Comment by fenrig** [comment]
note that without fflush s_client fails and s_server exits after server_hello

**Comment by mattcaswell** [comment]
Please could you apply the following debug patch and re-run the test (without fflush):

````
diff --git a/apps/s_client.c b/apps/s_client.c
index ce1a408dcc..255f8276c8 100644
--- a/apps/s_client.c
+++ b/apps/s_client.c
@@ -2289,6 +2289,7 @@ int s_client_main(int argc, char **argv)
                 if ((k != 0) || (cbuf_len != 0)) {
                     BIO_printf(bio_err, "write:errno=%d\n",
                                get_last_socket_error());
+                    ERR_print_errors(bio_err);
                     goto shut;
                 } else {
                     read_tty = 1;
````

**Comment by fenrig** [comment]
with the one line patch
[without_fflush_s_client_patched.txt](https://github.com/openssl/openssl/files/1162653/without_fflush_s_client_patched.txt)

**Comment by mattcaswell** [comment]
Well that didn't tell me anything at all! Here's a fuller patch. Can you try that again?
[debug.txt](https://github.com/openssl/openssl/files/1162680/debug.txt)

**Comment by fenrig** [comment]
yeah probably later, at this pace I can't get anything done :) and I'm on a really tight schedule. And the fflush "fixes" my problem. I really need to finish this :) I'll report later

**Comment by mattcaswell** [comment]
No further info on this, so closing.
