### ISSUE TITLE
Compile current openssl version with VS 2017 failed

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#3966]
I tried to compile the current openssl distribution with VS 2017 and it failed with the following error message:

```
c:\download\openssl-1.1.0f\openssl-1.1.0f>nmake

Microsoft (R) Program Maintenance Utility, Version 14.10.25019.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

        "C:\Perl64\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "crypto\include\internal\bn_conf.h.in" > crypto\include\internal\bn_conf.h
        "C:\Perl64\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "crypto\include\internal\dso_conf.h.in" > crypto\include\internal\dso_conf.h
        "C:\Perl64\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\openssl\opensslconf.h.in" > include\openssl\opensslconf.h
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe" depend && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe" _all

Microsoft (R) Program Maintenance Utility, Version 14.10.25019.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.


Microsoft (R) Program Maintenance Utility, Version 14.10.25019.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

        "C:\Perl64\bin\perl.exe" "util\mkbuildinf.pl" ""cl" """ ""VC-WIN64A"" > crypto\buildinf.h
        cl  /I "." /I "crypto\include" /I "include" /I "crypto" -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_API_COMPAT=0x10100000L "-DENGINESDIR=\"C:\\download\\openssl-1.1.0f\\bin\\lib\\engines-1_1\"" "-DOPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MDd /Od -DDEBUG -D_DEBUG /Zi /Fdossl_static -c /Focrypto\cversion.obj "crypto\cversion.c"
cversion.c
        "C:\Perl64\bin\perl.exe" "util\mkdef.pl" "crypto" 32 > libcrypto-1_1-x64.def
        "C:\Perl64\bin\perl.exe" -i.tmp -pe "s|^LIBRARY\s+crypto32|LIBRARY libcrypto-1_1-x64|;" libcrypto-1_1-x64.def
        DEL libcrypto-1_1-x64.def.tmp
        "C:\Perl64\bin\perl.exe" "util\mkrc.pl" libcrypto-1_1-x64.dll > libcrypto-1_1-x64.rc
        rc /folibcrypto-1_1-x64.res libcrypto-1_1-x64.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST libcrypto-1_1-x64.dll.manifest DEL /F /Q libcrypto-1_1-x64.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1-x64.dll /def:libcrypto-1_1-x64.def @C:\Users\twolf10\AppData\Local\Temp\nmDCA9.tmp || (DEL /Q libcrypto.* libcrypto-1_1-x64.* && EXIT 1)
crypto\aes\aes_cfb.obj : fatal error LNK1112: Modul-Computertyp "X86" steht in Konflikt mit dem Zielcomputertyp "x64".
NMAKE : fatal error U1077: "link": Rückgabe-Code "0x1"
Stop.
NMAKE : fatal error U1077: ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe"": Rückgabe-Code "0x2"
Stop.

c:\download\openssl-1.1.0f\openssl-1.1.0f>
```

**Comment by kaduk** [comment]
Does the bittedness of your visual studio developers console match the bittedness (32 vs 64) of your openssl configure target?  The "X86" makes me think that your console is targetting 32-bit mode, but the log shows openssl trying to build 64-bit code.

**Comment by wolftobias** [comment]
I did the following steps:

- installed 64-bit Perl, http://www.activestate.com/ActivePerl.
- installed 64-bit NASM, available from http://www.nasm.us,
- opened VS2017 x64 Cross (and Native 2. try) Tools Command Prompt

perl Configure VC-WIN64A --prefix=c:\download\openssl-1.1.0f\bin --debug enable-ssl-trace enable-crypto-mdebug no-deprecated

nmake

nmake install

All these steps were working with VS 2012 and I think 2015!

**Comment by kaduk** [comment]
As I understand it, that is supposed to work.  But I don't have a windows system handy at the moment; maybe someone else on the team who does could take a look.

**Comment by dot-asm** [comment]
nmake clean or start from fresh.

**Comment by wolftobias** [comment]
Issue ist still existing, just tested with a fresh the master zip file download. Same error!

**Comment by kaduk** [comment]
I note that the issue is currently in the 'closed' state.
You should provide a more detailed log of what you did, starting from the fresh zip download, in order for reopining the issue to be justified.

**Comment by wolftobias** [comment]
I think the issue comes with the parameters I`m using.

**Comment by kaduk** [comment]
>  dot-asm closed this 4 days ago

which apparently was at the same time as the "nmake clean or start from fresh" comment.
@dot-asm do you have access to VS2017?

**Comment by dot-asm** [comment]
> @dot-asm do you have access to VS2017?

It would be a mistake to assume that I would have closed the issue without having tried to reproduce it. In other words, yes, I do have access to VS2017 (community version), and yes, I did try to reproduce it, obviously unsuccessfully.

**Comment by dot-asm** [comment]
What does `where cl` return and what does cl (without arguments) print. Mine prints
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x64
```
That last "for x64" is the keyword.

**Comment by wolftobias** [comment]
C:\download\openssl\openssl-master>where cl
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x86\cl.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.exe

**Comment by dot-asm** [comment]
I mean that if your target is VC-WIN64A, then cl should print "for x64". Not more, but more importantly not less either. How you get there, or how things are or should be called in start menu, or if it's native or cross compiler, is not an OpenSSL problem. I.e. something for user to figure out. However, if you indeed invoked "x64_x86 Cross Tools", then yes, it would be wrong. It's 64-bit compiler executable that generates 32-bit code. Compiler executable's bitness doesn't matter, what counts is what it generates. If assertion is that it worked with previous VS version, I don't believe it.

**Comment by wolftobias** [comment]
Ok now it`s working, thank you very much for your suppport. I wrote down a note for VS2012 and I was sure I was using x64_x86 Cross Tools Command Prompt at that time. I don`t have VS2012 right now on my maschine to prove it.
