### ISSUE TITLE
How to verfiy TLS connection is FIPS 140-2 complaint or not

### ISSUE THREAD

**Issue by schitransh** [openssl/openssl#3967]
Hi 

i have built node.js with openSSL Fips 2.0 (openssl-fips-2.0.16).

[root@localhost bin]# ./node -p "process.versions.openssl"
1.0.2k-fips

I am able to use fips enable crypto algorithm (SHA256) and getting failure by using MD5.
so i am asuming node.js binary has successfully compiled with fips 2.0.

But i want to verfiy TLS connection has made from node.js application towards GCM cloud is fips 140-2 compliant or not?

Thanks
Chitransh

**Comment by SteveMarquess** [comment]
There really is no such thing as "FIPS 140 compliant" (even though that term is much used and abused). You're thinking of "FIPS 140 validated", which is a special state of grace (aka "magical pixie dust") that cannot be affirmatively established by any technical test (though you can sometimes demonstrate that an application cannot be using validated cryptography). You need a paper trail (see the [FIPS module user guide](https://www.openssl.org/docs/fips/UserGuide-2.0.pdf).

At runtime you can use FIPS_mode() to check for FIPS mode operation, but note that if improperly built, if not built from a snail-mailed CD, if not built for a formally tested platform, etc. etc., the result is still _NOT_ FIPS 140 validated no matter what FIPS_mode(0 returns.

**Comment by richsalz** [comment]
Closing per @SteveMarquess
