### ISSUE TITLE
t1_*

### ISSUE THREAD

**Issue by Sn0keR4xor** [openssl/openssl#3968]
Hello, I'm fine and I hope you are fine! I'm currently trying to understand the openssl code, till now all fine, but I stuck on understanding of the t1_* code, on `ssl/t1_*.c`, Please, correct me if I'm wrong, this codes are used to describe and/or define the implementation of tls for version tls versions 1.1 and 1.2?

**Comment by mattcaswell** [comment]
Not an OpenSSL bug. Please ask general questions on the openssl-users email list:

https://mta.openssl.org
