### ISSUE TITLE
While compiling openssl-tls1.3-draft-19 on Suse Linux 10 with kernel version 2.6.16.21-0.8-default, i was facing compilation issue.

### ISSUE THREAD

**Issue by chaitanyavaleti** [openssl/openssl#3977]
I tried multiple options of Configuring like
1)./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared
and
2)./config  shared 
3)Configure shared --prefix=/usr/bin/openssl --openssldir=/usr/bin/openssl linux-x86_64

but non of the options helped to get the below error resolved.

gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib64/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -fPIC -DOPENSSL_USE_NODELETE -MMD -MF crypto/mem_sec.d.tmp -MT crypto/mem_sec.o -c -o crypto/mem_sec.o crypto/mem_sec.c

In file included from /usr/include/linux/timex.h:58,
                 from /usr/include/linux/sched.h:11,
                 from /usr/include/linux/mm.h:4,
                 from /usr/include/linux/mman.h:5,
                 from crypto/mem_sec.c:36:
/usr/include/linux/time.h:12: error: redefinition of 'struct timespec'
/usr/include/linux/time.h:18: error: redefinition of 'struct timeval'
/usr/include/linux/time.h:168: error: redefinition of 'struct itimerspec'

I traced the code and could find that this section of code is added newly as part of draft-19, but not present in draft-18.

# if defined(OPENSSL_SYS_LINUX)
#  include <sys/syscall.h>
#  include <linux/mman.h>// This line is causing the issue of redefinition
#  include <errno.h>
# endif

I just removed this include file "linux/mman.h"  from meme_sec.c under crypto/ and i could successfully compile the code  and generate shared libraries

Please review the issue and do the needful.

**Comment by mattcaswell** [comment]
Also see #3900

**Comment by mattcaswell** [comment]
Is this still an issue on latest master?

**Comment by petrovr** [comment]
mattcaswell wrote:
> Is this still an issue on latest master?
>
I can not see any commit in master that resolves issue.
#3900 is about presence of linux/mman.h
#3977 is about usability of linux/mman.h

Work-around for presence is to use asm/mman.h instead. I can not see how 
work around will resolve issue but lets reported confirm.

**Comment by mattcaswell** [comment]
Should be fixed by commit f1c00b93e2. Closing.
