### ISSUE TITLE
-hash function calculates same value for different certificates

### ISSUE THREAD

**Issue by 3nigma2112** [openssl/openssl#3988]
I have two different CA root certs, both with the same distinguished name. One is an older SHA1 signing cert, and one is a SHA256 signing cert.  They have the same DN as a result of a CA key rollover to update the signing key from SHA1 to SHA256.  The problem I've encountered is that we need to use both CA certs to validate certificates signed by the older root and certificates signed by the new root.  The "openssl x509 -noout -hash -in ca-certificate-file" produces the exact same hash value for both certificates yet, aside from the distinguished name, the certificates are completely different.
Can this be fixed so that the hash function uses additional information within the certificate (i.e. serial number, validity period, etc.) to come up with a unique hash for each CA root cert?

**Comment by richsalz** [comment]
We cannot change the meaning of the -hash flag.  If you want to hash the entire cert, for example:
```
openssl x509 -outform der -in certificate-file | openssl sha1
```
(the existing hash is a hack taking only four bytes)

**Comment by snhenson** [comment]
The -hash output is used to lookup certificates by subject name so by definition identical subject names will have the same hash. Certificates with the same has value are distinguished by the extension. The first is .0 the second .1 etc. The rehash utility does this automatically.

If you want to hash the whole certificate you can either use the command @richsalz suggested or the -fingerprint option.

**Comment by 3nigma2112** [comment]
Ok, thank you. Do the .0 and .1, etc., extensions show up on the files that are created with the hash names in the directory where the root certificates are stored?

Thanks,

Peter J Tijerina, CISSP
BNSF Enterprise Security Engineering
Office: 817-593-5019
Mobile: 940-231-4598
AlphaPager: 9402314598@txt.att.net<mailto:9402314598@txt.att.net>

This message may be confidential and should be read or retained only by the intended recipient. If you have received this transmission in error, please immediately notify the sender by replying to this message and then delete it from your system.
