### ISSUE TITLE
Override and legal fallback to the original tls1_prf

### ISSUE THREAD

**Issue by deemru** [openssl/openssl#4005]
Hello, @richsalz, we had this topic on the last IETF 99 and you asked to write down this issue.

I can override `NID_tls1_prf` in `ENGINE_set_pkey_meths()`, but currently i can not do a legal fallback to the original openssl implementation `tls1_prf_pkey_meth` without using the internal `evp_pkey_method_st` interface from `evp_int.h` to call `init`, `cleanup`, `derive`, `ctrl` and `ctrl_str`.

The only legal option here is to completely duplicate the original implementation. But it looks ugly.

**Comment by snhenson** [comment]
Where do you want to do the fallback? Do you want to do it within an implementation or in the application?

There is a limitation in the current algorithm handling (which affects other things like ciphers too): you cannot specify the software implementation if the default implementation has been replaced.

**Comment by deemru** [comment]
Yes, i want the fallback inside my implementation of `NID_tls1_prf`.

I use my implementation of `NID_tls1_prf` for specific algorithms so all others goes to the fallback. I do not like to include the internal openssl interface from `evp_int.h`, because you can not rely on internal interfaces.

**Comment by deemru** [comment]
Looks fixed, `evp_pkey_method_st` is part of https://github.com/openssl/openssl/blob/e2e09d9fba1187f8d6aafaa34d4172f56f1ffb72/include/crypto/evp.h#L43-L90
