### ISSUE TITLE
SSL_reset or SSL_seek can't put the bio to the initial (unread) state?

### ISSUE THREAD

**Issue by yctung** [openssl/openssl#4010]
I am working on reusing the same session ticket over several SSL connections. I know the session ticket can be serialized to a file and read it back but I am trying to do it without saving the file (i.e., in memory).

ex: 
```
BIO *bio = BIO_new(BIO_s_mem());
PEM_write_bio_SSL_SESSION(bio, sess);
SSL_SESSION *sess1 = PEM_read_bio_SSL_SESSION(bio, NULL, 0, NULL);
//BIO_reset(bio);  // not helpful
//BIO_seek(bio, 0);  // not helpful
SSL_SESSION *sess2 = PEM_read_bio_SSL_SESSION(bio, NULL, 0, NULL); // This will return null
```

Is it the intended behavior? how can I reuse the same bio to do it?

**Comment by kaduk** [comment]
The common idiom for doing this operation is to pair up i2d_SSL_SESSION() and d2i_SSL_SESSION(), though it is admittedly a little silly that we don't have a native SSL_SESSION_dup().
