### ISSUE TITLE
Infrastructure: Install tests

### ISSUE THREAD

**Issue by GyrosGeier** [openssl/openssl#4012]
The AppVeyor tests verify that compilation works, but don't test installation, which allowed a bug to sneak through — see https://github.com/openssl/openssl/pull/3942

**Comment by t8m** [comment]
This is already fixed.

**Comment by levitte** [comment]
Although...  it would be good to have something that checks that an *installation* works properly.

VMS product packaging have something called an Installation Verification Procedure, which is norm in any software package.  Other platforms ...  or for that matter, package systems, could learn from this.  And so could we...

**Comment by t8m** [comment]
> Although... it would be good to have something that checks that an _installation_ works properly.

Added as an idea to futures.
