### ISSUE TITLE
fuzz/driver.c not MSVC compatible

### ISSUE THREAD

**Issue by gvanem** [openssl/openssl#4017]
The `fuzz/driver.c` does not compile using MSVC due to the `#include <unistd.h>`. Except for this, the fuzz-program seems to compile and run fine using MSVC-2015.

A patch like this would be nice:
```c
#ifndef _MSC_VER
#include <unistd.h>
#endif
```

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
