### ISSUE TITLE
i2d_SSL_SESSION/i2d_SSL_SESSION does not work for TLS1.3 session ticket

### ISSUE THREAD

**Issue by yctung** [openssl/openssl#4018]
Here is the minimal testing code to reproduce the bug:
```
static SSL_SESSION * test_serialize(SSL_SESSION *sess) {
    int len = i2d_SSL_SESSION(sess, NULL);
    unsigned char *bytes = (unsigned char *)malloc(sizeof(unsigned char)*len);
    unsigned char *temp = bytes;
    int ret = i2d_SSL_SESSION(sess, &temp);
    SSL_SESSION *temp1;
    SSL_SESSION *temp2 = d2i_SSL_SESSION(&temp1, (const unsigned char **)&bytes, len);
    return temp1;
}
```

I put this code in the s_client by passing the session read from a file (sess_in). I am certain that without this code, the session works correctly, but with this code, the session fails (at the line of i2d_SSL_SESSION).

**Comment by kaduk** [comment]
```
    SSL_SESSION *tmp1;
    SSL_SESSION *temp2 = d2i_SSL_SESSION(&temp1, (const unsigned char **)&bytes, len);
```

This is improper usage -- passing a non-NULL first argument is saying that that argument points to already-allocated storage, but you are passing a pointer to uninitialized memory, which is undefined behavior.  Pass NULL instead and return temp2 from your snippet.
