### ISSUE TITLE
PFS SSL_CTX_set_tmp_dh clarification? (doc bug)

### ISSUE THREAD

**Issue by dpocock** [openssl/openssl#402]
Looking at this manual page: http://linux.die.net/man/3/ssl_ctx_set_tmp_dh

It states "These functions apply to SSL/TLS servers only."

Some applications use the same SSL_CTX* for both server and client sockets, e.g. SIP servers act as both server and client.

Is there any harm in calling SSL_CTX_set_tmp_dh() on an SSL_CTX * that will be used for both server and client sockets?

Or is it better to just use SSL_set_tmp_dh(SSL *) for each server connection?

For the code I am working on, the SSL_CTX* is created here: https://github.com/resiprocate/resiprocate/blob/master/resip/stack/ssl/Security.cxx#L299

and the SSL* is created here: https://github.com/resiprocate/resiprocate/blob/master/resip/stack/ssl/TlsConnection.cxx#L97

**Comment by kroeckx** [comment]
The server will select the DH parameters to use.  The call has no effect when it's a client.

**Comment by dpocock** [comment]
Ok, thanks for that feedback.  I had seen other code trying to avoid using the method when the SSL_CTX* is for a client, e.g. http://trac.pjsip.org/repos/changeset/4871 and I wasn't sure if this is just for efficiency or if it must avoid it.

Given the lifecycle of SSL_CTX* in reSIProcate is different though, I will just call SSL_CTX_set_tmp_dh() for every SSL_CTX* though.

**Comment by richsalz** [comment]
answered by kurt, not an issue-- the documentation is correct.
