### ISSUE TITLE
Where is the repository branch for OpenSSL FIPS module v2.0.16 ?

### ISSUE THREAD

**Issue by alan-kozlay** [openssl/openssl#4027]
I'm looking to do a bare clone of the OpenSSL repository to include the updates for FIPS module v2.0.16, but I only see up to OpenSSL-fips-2_0_14 in the tags.  Just unzipping openssl-fips-2.0.16.tar.gz is not an entire repository.

**Comment by SteveMarquess** [comment]
An important point to note is that the OpenSSL FIPS Object Module is not, and never has been, the "entire repository". That module is a separate and distinct software product and is not OpenSSL proper. It kinda-sorta matches a separate branch within the OpenSSL git repo, but isn't the same thing (for the upcoming validation the module code will live in a separate repo entirely).

Only the official tarball (with HMAC-SHA1 digest as specified in the Security Policy) defines the cryptographic module; the git repo and tags are a convenience for us but not recognized by the CMVP. We set the tags only after each revision is formally approved by the CMVP (which usually takes many months after coding). Actual module development and testing is, of necessity, done with patches against the previous official tarball. We're a little behind on retrofitting the repo to match the latest official tarballs. If you're doing anything that pretends to be FIPS 140 validated you must reference the official tarballs (which incidentally must be obtained by snail-mail CDs, not downloading).

Yes, that's profoundly bass-ackwards. Welcome to FIPS 140, the tail that wags the dog.

**Comment by richsalz** [comment]
Closing this issue, per @SteveMarquess

**Comment by snhenson** [comment]
FYI: the OpenSSL-fips-2_0_15 and OpenSSL-fips-2_0_16 tags have now been added.
