### ISSUE TITLE
Configure/install problem

### ISSUE THREAD

**Issue by dyomas** [openssl/openssl#4028]
I use openssl in sources. To install openssl under _specific path_ I run:

`./config --prefix=<specific_path>`

**Problem:**

If specified path contains directory _lib64_, openssl components installed in _<specific_path>/lib64_
If specified path contains no directory _lib64_, openssl components installed in _<specific_path>/lib_

But dependent projects always try obtain openssl components from the same directory (_lib_). Problem localized in Perl script [Configure](https://github.com/openssl/openssl/blob/master/Configure). Confirmed in versions [1.1.0](https://github.com/openssl/openssl/archive/OpenSSL_1_1_0.tar.gz), [1.1.0f](https://github.com/openssl/openssl/archive/OpenSSL_1_1_0f.tar.gz) under _Ubuntu 14.04.4 LTS_

**Workaround:**

I patch final _Makefile_:
```sed -i.back "s/^\(LIBDIR\|ENGINESDIR\)=\(.*\)lib64\(.*\)/\1=\2lib\3/" Makefile```
results looks like:
```
diff Makefile.back Makefile
53,54c53,54
- LIBDIR=lib64
- ENGINESDIR=<specific_path>/lib64/engines-1.1
---
+ LIBDIR=lib
+ ENGINESDIR=<specific_path>/lib/engines-1.1
```

**Comment by levitte** [comment]
There's an easier workaround:

```
./config --prefix=<specific_path> --libdir=lib
```
