### ISSUE TITLE
s_client+s_server chain options missing documentation

### ISSUE THREAD

**Issue by mpeylo** [openssl/openssl#4038]
Regarding the GIT master branch as of 28.7.2017

At least the following options are listed in --help of s_client and s_server, but are not explained in the doc/man1/s_client.pod and man1/s_server.pod. The --help text is very rudimentary and for most options it is not fully obvious what they do. s_server.pod lists the options, but doesn't explain them.

-build_chain
-cert_chain
-chainCApath
-chainCAfile
-xchain
-xchain_build 
-xkey infile
-xcert infile
-xchain infile
-xchain_build
-xcertform
-xkeyform

only in s_server:
-dcert_chain

**Comment by beldmit** [comment]
Should be closed as #6209 is merged.

**Comment by richsalz** [comment]
Good point, thank you.
