### ISSUE TITLE
RSA key size not used when selecting shared signature algorithms

### ISSUE THREAD

**Issue by roelfdutoit** [openssl/openssl#4042]
If a TLS 1.2/1.3 client sigalgs lists sha512_rsa_pss before sha384_rsa_pss and sha256_rsa_pss then the OpenSSL server will select sha512_rsa_pss even if the RSA key in the X.509 certificate is only 1024-bit.  The server aborts the session with an "internal_error" alert (80) and dumps the following error:

```
140217200965440:error:0409806E:rsa routines:RSA_padding_add_PKCS1_PSS_mgf1:data too large for key size:crypto/rsa/rsa_pss.c:192:
140217200965440:error:141EC044:SSL routines:tls_construct_server_key_exchange:internal error:ssl/statem/statem_srvr.c:2473:
```

**Comment by bernd-edlinger** [comment]
that's probably because you should use 2048 bit keys nowadays.

**Comment by mattcaswell** [comment]
Linked PR was merged so closing.
