### ISSUE TITLE
`man cms`: inconsistency between -indef and -noindef doco

### ISSUE THREAD

**Issue by apjanke** [openssl/openssl#406]
In the current `man cms` documentation, it says this:

```
       -stream, -indef
           The -stream and -indef options are equivalent and enable
           streaming I/O for encoding operations.  This permits single
           pass processing of data without the need to hold the entire
           contents in memory, potentially supporting very large files.
           Streaming is automatically set for S/MIME signing with
           detached data if the output format is SMIME.  It is currently
           off by default for all other operations.

       -noindef
           Disable streaming I/O where it would produce an indefinite
           length constructed encoding.  This option currently has no
           effect.  In the future, streaming will be enabled by default
           on all relevant operations and this option will disable it.
```

That seems inconsistent: `-noindef` says streaming is off by default for everything; `-indef` says it's on by default for this particular S/MIME signing case case. Is one of these out of date or am I misunderstanding what it says here?

**Comment by kroeckx** [comment]
The way I read it, it's default on for smime and off for all
others, but in the future the defaults might change.  -noindef
currently has no effect, but in case the default change it will
have an effect.

**Comment by apjanke** [comment]
But doesn't that meant that `-noindef` does have an effect, when used in conjunction with `-sign`, and the `-nodetach` option is not specified? Seems like that should be documented in the `-noindef` option itself, if that's the case.

**Comment by mattcaswell** [comment]
"-noindef says streaming is off by default for everything" - it doesn't say that the way I read it.

I don't think there is anything to be done here. Closing.
