### ISSUE TITLE
Please add a way to copy cipher contexts

### ISSUE THREAD

**Issue by triska** [openssl/openssl#4078]
I am currently working on OpenSSL bindings for the declarative programming language **Prolog**:

**http://eu.swi-prolog.org/pldoc/man?section=crypto**

In this language, *destructive modifications* of existing terms must be avoided. For the bindings I have provided so far, I am always internally *copying* contexts, and then modifying the fresh&nbsp;copy, thus preserving existing contexts. This has important benefits regarding thread&nbsp;safety etc. and already works for the [hash&nbsp;API](http://eu.swi-prolog.org/pldoc/man?section=crypto-hash) via `EVP_MD_CTX_copy_ex`.

I now would like to add a way to *incrementally* **encrypt** and **decrypt** data, and I find that the OpenSSL&nbsp;API falls short in the following respect:

Currently, there is no way to *copy ciphers contexts*. Please add such an API.

For example, in analogy to `EVP_MD_CTX_copy_ex`, please add **`EVP_CIPHER_CTX_copy_ex`**. 

Thank&nbsp;you!

**Comment by mattcaswell** [comment]
Err...there is an EVP_CIPHER_CTX_copy()?

https://github.com/openssl/openssl/blob/master/include/openssl/evp.h#L471

**Comment by triska** [comment]
Yes, thank you! However, could you please make this officially available by documenting it? It seems completely undocumented as far as I can tell.

**Comment by richsalz** [comment]
Yes it's undocumented.  Too much of the API isn't documented.  But that doesn't mean it's not official.  The fact that it is in a public header file is sufficient.
