### ISSUE TITLE
Slow RAND_poll in MinGW-compiled OpenSSL 1.0.2l

### ISSUE THREAD

**Issue by Vort** [openssl/openssl#4085]
```RAND_poll``` call can take 10+ seconds to complete when OpenSSL library is compiled for Windows platform with GCC compiler.
This bug was partially fixed with 47e0a1c335295d7548ecd1860954ee4f988d9804, but only for MSVC ```#ifdef``` branch. ```#else``` branch left unfixed.
What I guess is needed to be done is adding of ```&& (!good || (GetTickCount() - starttime) < MAXDELAY)``` code also to [this](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/rand/rand_win.c#L499) position.

Test code:
```cpp
// g++ rand_poll_test.cpp -lcrypto -o rand_poll_test.exe

#include <iostream>
#include <openssl/rand.h>

#define NUM_ALLOCS 800000

int main()
{
	char** dummymem = new char*[NUM_ALLOCS];
	for (int i = 0; i < NUM_ALLOCS; i++)
		dummymem[i] = new char[2];
	int startTime = GetTickCount();
	RAND_poll();
	int endTime = GetTickCount();
	int elapsed = endTime - startTime;
	std::cout << elapsed << " ms : " << (elapsed > 2000 ? "bad" : "good") << std::endl;
	delete[] dummymem;
	return 0;
}
```
MinGW result:
```
$ ./rand_poll_test.exe
7239 ms : bad
```
MSVC 2015 result:
```
1108 ms : good
```

**Comment by Vort** [comment]
Patch:
```patch
diff --git a/crypto/rand/rand_win.c b/crypto/rand/rand_win.c
index 06670ae..31a7fee 100644
--- a/crypto/rand/rand_win.c
+++ b/crypto/rand/rand_win.c
@@ -496,6 +496,9 @@ int RAND_poll(void)
                             do
                                 RAND_add(&hentry, hentry.dwSize, 5);
                             while (heap_next(&hentry)
+                                   && (!good
+                                       || (GetTickCount() - starttime) <
+                                       MAXDELAY)
                                    && --entrycnt > 0);
                         }
                     } while (heaplist_next(handle, &hlist) 
```

**Comment by richsalz** [comment]
What version of the code are you looking at?  I see those changes in 1.0.2 already.

**Comment by Vort** [comment]
@richsalz, latest version in `OpenSSL_1_0_2-stable` branch: [rand_win.c](https://github.com/openssl/openssl/blob/a33a335e442b0bb53d28eb42833944327651c9ed/crypto/rand/rand_win.c).
You can see that code at lines 469, 483 and 502, but it should be also at line 499.

**Comment by richsalz** [comment]
@vort, please see https://github.com/openssl/openssl/pull/4106

**Comment by richsalz** [comment]
fix merged, thanks!
