### ISSUE TITLE
test/asn1_time_test.c does not compile with Configure --strict-warnings -std=gnu89

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#4121]
`gcc  -I. -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DTERMIOS -DL_ENDIAN -Wall -g -O0  -DDEBUG_UNUSED -Wswitch -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wsign-compare -Wmissing-prototypes -Wshadow -Wformat -Wtype-limits -Wundef -Werror -std=gnu89  -MMD -MF test/asn1_time_test.d.tmp -MT test/asn1_time_test.o -c -o test/asn1_time_test.o test/asn1_time_test.c
`

yields
```
test/asn1_time_test.c:82:5: error: this decimal constant is unsigned only in ISO C90 [-Werror]
     { "19011213204552Z",   V_ASN1_GENERALIZEDTIME, V_ASN1_GENERALIZEDTIME, 1, -2147483648, -1, 0, },
     ^
test/asn1_time_test.c:91:5: error: this decimal constant is unsigned only in ISO C90 [-Werror]
     { "20500101120000Z",   V_ASN1_GENERALIZEDTIME, V_ASN1_GENERALIZEDTIME, 1,  2524651200,  1, 0, },
     ^
test/asn1_time_test.c:96:5: error: this decimal constant is unsigned only in ISO C90 [-Werror]
     { "19011213204551Z",   V_ASN1_GENERALIZEDTIME, V_ASN1_GENERALIZEDTIME, 1, -2147483649, -1, 0, },
     ^
test/asn1_time_test.c:97:5: error: this decimal constant is unsigned only in ISO C90 [-Werror]
     { "19000101120000Z",   V_ASN1_GENERALIZEDTIME, V_ASN1_GENERALIZEDTIME, 1, -2208945600, -1, 0, },
     ^
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7028: test/asn1_time_test.o] Error 1
```

while everything else compiles fine with all those 'pedantic' settings.

My workaroud is to remove `-Werror` in the above gcc invocation and then re-start `make`.

**Comment by mattcaswell** [comment]
We support C90, not earlier.

**Comment by DDvO** [comment]
I thought I had taken `-std=gnu89` from (an earlier version of) the OpenSSL contribution guideline, but may have been mistaken.
I've just learned from https://gcc.gnu.org/onlinedocs/gcc/Standards.html#Standards and https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html that C89 and C90 are synonyms.

Anyway, I cannot reproduce the issue any more with the current master.
