### ISSUE TITLE
test/sslapitest.c fails due to memory leak in test_session_with_both_cache()

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#4127]
When built with enable-crypto-mdebug like in https://travis-ci.org/openssl/openssl/builds/262739932?utm_source=github_status&utm_medium=notification
test/sslapitest.c fails due to a memory leak, which I pinned down to be in test_session_with_both_cache().

BTW, chasing the memory leak I found some minor issues in `test/testutil/driver.c`, which can be cured as follows:
```

diff --git a/test/testutil/driver.c b/test/testutil/driver.c
index cf4296a23f..620b1ddf3c 100644
--- a/test/testutil/driver.c
+++ b/test/testutil/driver.c
@@ -40,7 +40,7 @@ static int seed = 0;
  */
 static int num_test_cases = 0;

-void add_test(const char *test_case_name, int (*test_fn) ())
+void add_test(const char *test_case_name, int (*test_fn) (void))
 {
     assert(num_tests != OSSL_NELEM(all_tests));
     all_tests[num_tests].test_case_name = test_case_name;
@@ -105,7 +105,7 @@ void setup_test_framework()
     if (test_seed != NULL) {
         seed = atoi(test_seed);
         if (seed <= 0)
-            seed = time(NULL);
+            seed = (int)time(NULL);
         test_printf_stdout("%*s# RAND SEED %d\n", subtest_level(), "", seed);
         test_flush_stdout();
         srand(seed);
@@ -121,6 +121,7 @@ void setup_test_framework()

 int pulldown_test_framework(int ret)
 {
+    set_test_title(NULL);
 #ifndef OPENSSL_NO_CRYPTO_MDEBUG
     if (should_report_leaks()
         && CRYPTO_mem_leaks_cb(openssl_error_cb, NULL) <= 0)
@@ -142,7 +143,8 @@ static char *test_title = NULL;

 void set_test_title(const char *title)
 {
-    free(test_title);
+    if (test_title)
+        free(test_title);
     test_title = title == NULL ? NULL : strdup(title);
 }

```

**Comment by kaduk** [comment]
The fix to the memory leak is in #4126 FWIW

**Comment by richsalz** [comment]
@paulidale using time to seed srand!  Gasp, the horror.
:)
free(0) is defined to be okay.
the testfn param declaration could be improved like you have, so keeping this open.

**Comment by DDvO** [comment]
I know that the XYZ_free() functions of OpenSSL work fine with NULL passed,
but the Dr. Memory tool complained about the free(NULL):
```
Error #2: INVALID HEAP ARGUMENT to free 0x022385b8
# 0 replace_free                 [d:\drmemory_package\common\alloc_replace.c:2706]
# 1 set_test_title               [p:\pki\openssl\master\test\testutil\driver.c:148]
# 2 run_tests                    [p:\pki\openssl\master\test\testutil\driver.c:236]
# 3 main                         [p:\pki\openssl\master\test\testutil\main.c:51]
Note: @0:00:25.805 in thread 9932
Note: refers to -1 byte(s) before next malloc
Note: next higher malloc: 0x022385b8-0x022385d5
Note: refers to -29 byte(s) beyond last valid byte in prior malloc
Note: prev lower malloc:  0x022385b8-0x022385d5
```
Maybe there are stdlib implementations that misbehave on `free(0)`.

**Comment by kaduk** [comment]
It is in the C language specification that for the free function, "if ptr is a null pointer, no action occurs".  I don't know what Dr. Memory is doing, but the spec is quite clear.

**Comment by DDvO** [comment]
Thanks for the hints regarding free(0).

I can confirm the fix of the memory leak in #4126.

**Comment by paulidale** [comment]
> using time to seed srand! Gasp, the horror.

In a non-cryptographic context where we only want something different.

**Comment by DDvO** [comment]
I've just created a little pull requests for the other things (except free(0) check).

I agree with @paulidale that in such a test context no high-quality seed is needed.

**Comment by richsalz** [comment]
I was teasing him, based on the RAND work we've been doing :)

**Comment by paulidale** [comment]
> I was teasing him, based on the RAND work we've been doing :)

I knew :)  Pity I couldn't come up with a wittier response :(

Using time as the only seed is a bit of a pet peeve of mine.  It is widely recommended but not good for crystallographic purposes.

**Comment by mattcaswell** [comment]
Linked PRs were merged so closing.
