### ISSUE TITLE
Race condition in output of 70-test_sslmessages.t and 70-test_sslsessiontick.t?

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4129]
I've filed #3562 about this issue before, but it still seem unfixed on Debian hurd with commit 523ea2721581cf9eaa20036327b53b36ba2135ba applied. You can see a log at: https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=hurd-i386&ver=1.1.0f-4&stamp=1502089091&raw=0

**Comment by kroeckx** [comment]
Now also seen on s390x: https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=s390x&ver=1.1.0f-5&stamp=1503611682&raw=0

**Comment by mattcaswell** [comment]
That looks like a different problem. The first one seems to relate to tests being out of sequence. The s390x failure says "No plan found in TAP output"

**Comment by mattcaswell** [comment]
Does this help?

````
diff --git a/util/perl/TLSProxy/Proxy.pm b/util/perl/TLSProxy/Proxy.pm
index c92652e78f..802c33a07c 100644
--- a/util/perl/TLSProxy/Proxy.pm
+++ b/util/perl/TLSProxy/Proxy.pm
@@ -23,6 +23,7 @@ use TLSProxy::Certificate;
 use TLSProxy::CertificateVerify;
 use TLSProxy::ServerKeyExchange;
 use TLSProxy::NewSessionTicket;
+use Time::HiRes qw/usleep/;
 
 my $have_IPv6 = 0;
 my $IP_factory;
@@ -340,6 +341,9 @@ sub clientstart
               .$self->serverpid."\n";
         waitpid( $self->serverpid, 0);
         die "exit code $? from server process\n" if $? != 0;
+    } else {
+        # Give s_server sufficient time to finish what it was doing
+        usleep(250000);
     }
     die "clientpid is zero\n" if $self->clientpid == 0;
     print "Waiting for client process to close: ".$self->clientpid."\n";
````

**Comment by kroeckx** [comment]
I think that fixed it, at least I didn't see this error message when I applied this patch in the last upload to Debian.
