### ISSUE TITLE
What is the correct/suggested way to push SSL state machine for reading control records (like a new session ticket?)

### ISSUE THREAD

**Issue by yctung** [openssl/openssl#4135]
Hi,

I just notice there is an interesting behavior in my system that the new session ticket might not be read. Here is the problem:

--- Followings are packet received in SSL client ---
1. ServerHello
2. UserData 1 (sent by early data)
3. New Session Ticket
3. UserData 2
---------------------------------------------------

I am using a non-blocking socket, so basically I signal my client to call SSL_connect or SSL_read if necessary (e.g., packet received in the socket and client want to read/handshake). This system works perfectly if the client wants to read UserData 2, so they will call SSL_read after the new session ticket packet and OpenSSL will smartly read the new session and update internal states and then read the UserData2 for the client.

However, in the case where is no such UserData2, my system will get a socket read event but client will be reluctant to read because there is actually no application data to read. In such a case, should I "kick" the OpenSSL to read "ghost" bytes by calling SSL_read?

Yu-Chih

**Comment by kaduk** [comment]
Yes, you can call SSL_read() with a zero-length buffer (or a larger one and handle the zero-length read).
(Assuming I understand you correctly, as you did not explicitly indicate that you're talking about TLS 1.3 draft support, which is not present in any released version of OpenSSL.)

**Comment by yctung** [comment]
Hi, Kaduk

Just wanna make sure I understand you correctly. Are you suggesting calling "SSL_read(ssl, NULL, 0)" in this situation? I wanna confirm it is an intended behavior that care has been taken by OpenSSL for doing this ghost read. (I have this concern since I know, in few systems, write/read 0 bytes might trigger the EOF of sockets.)

BTW, I am using TLS 1.3 now but this seems a general problem if TLS sending any control message after the user data. TLS 1.3 particularly triggers this problem all the time since data can be sent as early data and there is always a new session ticket sent after the handshake.

Yu-Chih
