### ISSUE TITLE
OpenSSL 1.0.2d + FIPS 2.0.9: Internal error low level API call to cipher AES forbidden

### ISSUE THREAD

**Issue by karanpopali** [openssl/openssl#414]
Platform: Android

OpenSSL aborts itself when I use cipher returned by EVP_get_cipherbyname(). Everything works fine if I use direct method to get the Cipher instance (i.e. EVP_aes_256_cbc()). Another interesting thing is, I get different object address as result from EVP_get_cipherbyname() and EVP_aes_256_cbc() (see first log for more info).

I also verified the same with OpenSSL 1.0.1p, and I get same result from direct/indirect method and everything works fine.

Logs: 
V OpenSSL: EVP_get_cipherbyname ADDRESS cbc(indirect) 0x74b562d8 cbc(direct) 0x74b4e3f8 gcm (indirect) 0x74b564ac gcm (direct) 0x74b4e5cc
E OpenSSL : OpenSSL internal error file aes_misc.c:83 Low level API call to cipher AES forbidden in FIPS mode!

Let me know if you need more info.

**Comment by karanpopali** [comment]
This is happening because of this chageset: 1dded7f7e8e9f737ef9d7e3c3ef165a78fd7fa1d
> Experimental multi-implementation support for FIPS capable OpenSSL.
>
> When in FIPS mode the approved implementations are used as normal,
> when not in FIPS mode the internal unapproved versions are used instead.
> This means that the FIPS capable OpenSSL isn't forced to use the
> (often lower perfomance) FIPS implementations outside FIPS mode.

Does this mean that FIPS object module is not compatible with OpenSSL module 1.0.2?

**Comment by richsalz** [comment]
no, it means you cannot use the low-level calls in FIPS mode.
