### ISSUE TITLE
Fuzzing broken on 17-07-25

### ISSUE THREAD

**Issue by kcc** [openssl/openssl#4140]
The fuzzing build was broken by https://github.com/openssl/openssl/commit/9f08a1c63efa2205aca4361a830ac04407325597
FuzzerSetRand is defined in fuzz/test-corpus.c but this file is not used when actually building for fuzzing.

**Comment by levitte** [comment]
Is this still an issue?

**Comment by richsalz** [comment]
No; my mistake in not closing this.
