### ISSUE TITLE
OpenSSL's PRNG does not seed internally

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#4148]
External packages use RAND_status() to check "whether OpenSSL's PRNG is internally seeded". 
Test ts quite simple - check runs simple one line program that check for "RAND_status() == 1".
Now this test(check) fail with master branch.

Look like incompatible function modification.

**Comment by richsalz** [comment]
On the contrary, the status is accurate.  What did programs do if it returned 0 before?  They should do this:
```
if (RAND_status() == 0)
    RAND_poll();
```

**Comment by petrovr** [comment]
Rich Salz wrote:
> On the contrary, the status is accurate.  What did programs do if it returned 0 before?  They should do this:

> ```
> if (RAND_status() == 0)
>      RAND_poll();
> ```

As I wrote it is check for functionality : 
https://github.com/openssh/openssh-portable/blob/master/configure.ac#L2885 
.
This check exist since decades.  So failure is considered as "OpenSSL's 
PRNG cannot internally seeded" and then is required package to be setup 
with external prng (entropy source).

This is modification of functionality.
It seems to me you consider OpenSSL releases before 1.1.1 as broken
In such case please drop existing function in favour on something new
- RAND_status2?

Roumen

**Comment by richsalz** [comment]
That test is, and always has been, wrong.  Perhaps someone else on the team can come up with a suggestion.

**Comment by petrovr** [comment]
P.S.
just tested but even after RAND_poll() RAND_status() still does not 
return 1.

**Comment by richsalz** [comment]
How did you configure openssl, did you use and --with-rand-seed?

**Comment by kroeckx** [comment]
I assume that now RAND_status() returns 0 before you call RAND_bytes() but that with the old code it already returned 1.

**Comment by richsalz** [comment]
Does this patch fix it?
```
diff --git a/crypto/rand/drbg_lib.c b/crypto/rand/drbg_lib.c
index e9502db..7ecdeae 100644
--- a/crypto/rand/drbg_lib.c
+++ b/crypto/rand/drbg_lib.c
@@ -403,6 +403,8 @@ static int drbg_status(void)
     int ret;
 
     CRYPTO_THREAD_write_lock(rand_drbg.lock);
+    if (rand_drbg.state == DRBG_UNINITIALISED
+            && RAND_DRBG_instantiate(&rand_drbg, NULL, 0) == 0)
     ret = rand_drbg.state == DRBG_READY ? 1 : 0;
     CRYPTO_THREAD_unlock(rand_drbg.lock);
     return ret;
```

**Comment by FdaSilvaYY** [comment]
'ret' could be return uninitialized  with your patch  ? it seems to me that the 'if' statement is incomplete ;)

**Comment by richsalz** [comment]
yeah, if should be
```
diff --git a/crypto/rand/drbg_lib.c b/crypto/rand/drbg_lib.c
index e9502db..7ecdeae 100644
--- a/crypto/rand/drbg_lib.c
+++ b/crypto/rand/drbg_lib.c
@@ -403,6 +403,8 @@ static int drbg_status(void)
     int ret;
 
     CRYPTO_THREAD_write_lock(rand_drbg.lock);
+    if (rand_drbg.state == DRBG_UNINITIALISED)
+            RAND_DRBG_instantiate(&rand_drbg, NULL, 0);
     ret = rand_drbg.state == DRBG_READY ? 1 : 0;
     CRYPTO_THREAD_unlock(rand_drbg.lock);
     return ret;
```

**Comment by petrovr** [comment]
Rich Salz wrote:
....
> +    if (rand_drbg.state == DRBG_UNINITIALISED)
> +            RAND_DRBG_instantiate(&rand_drbg, NULL, 0);
....

Code above resolves issue.
Roumen

**Comment by richsalz** [comment]
fixed on master, thanks for the report.
