### ISSUE TITLE
If 'no-rsa' is removed then why 'OPENSSL_NO_RSA' is not removed?

### ISSUE THREAD

**Issue by InfoHunter** [openssl/openssl#4152]
As 7ec8de16fe23e207d3e1bbb95d53843dbc9c06c8 removed `no-rsa` option (along with others), why is the `OPENSSL_NO_RSA` still kept in the codebase? 

I also find this attempt to remove those macros: #1561 [and instead, seems no further attempts on fixing the no-<cipher> options]

**Comment by mattcaswell** [comment]
It was removed as an option because it was horribly broken and too much effort to fix. At the time we thought that we may wish to invest the effort to fix it at some point in the future so we decided not to remove `OPENSSL_NO_RSA`.
