### ISSUE TITLE
EBCDIC support

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#4154]
There are some suspicions about the validity of the current EBCDIC support.  There look like problems with the code handling EBCDIC -- it is applied in some places but not others.  These should be investigated and fixed.

Moreover, two of the unit tests currently fail when `-DCHARSET_EBCDIC -DCHARSET_EBCDIC_TEST` are defined.  These are `test_stack` and `test_passwd`.  That the former is failing in a test of an _integer_ stack is a concern.  These are covered by #4130

These comments are a result of #4102 wherein @dot-asm wrote:
>As for EBCDIC vs. ASCII it was kind of decided to postpone it. The fact that there is problem is acknowledged, but it's not clear if it should be solved by adhering to ASCII codes for '0'..'9'. [I for one would rather see string converted elsewhere.] It's also acknowledged that there are other problems with EBCDIC, like lack of access to a system, at least for the time being. It would probably be more efficient to solve latter problem first, then get kind of a bird-view on the problem, and only then it would probably be appropriate to decide which approach to take...

and:
>The whole thing is big potential EBCDIC issue, on multiple levels. I'd say that it's not unreasonable to remove EBCDIC targets from Configurations/10-main.conf. Because none of them are likely to be brought alive. And the only reason for not removing all EBCDIC traces even from source code is remote possibility of having the opportunity to solve the puzzle on z/OS.

and @tmshort wrote:
> so let's document the issues we've discovered/discussed in the code/README. I'm fine with removing/commenting out EBCDIC platforms, and even adding a check to the unit tests or config, or whatever to prevent inadvertent builds.

Identified concerns (there are far more):
- `a2d_ASN1_OBJECT` in `crypto/asn1/a_object.c` has comparisons against period and space immediately before the `isdigit` check.  These might need to be made in ASCII not the native character set.
- `a2d_ASN1_OBJECT` in `crypto/asn1/a_object.c` is using a digit minus '0' to generate a number.  The character set used needs to be checked in case they are ASCII.
- `BN_hex2bn` in `crypto/bn/bn_print.c` is the input argument a localized string (i.e. either ASCII or EBCDIC) or is it always ASCII? For EBCDIC platforms, maybe it can auto-detect based on the first character? (*a > 0x7F, it's EBCDIC, otherwise, assume ASCII input).
- `CONF_parse_list` in `crypto/conf/conf_mod.c` are config files ASCII or localised?  Are they allowed extended ASCII characters?

**Comment by paulidale** [comment]
Also refer to #2488
#4102 has a lot of other commentary.

**Comment by mattcaswell** [comment]
How do we progress this?

**Comment by richsalz** [comment]
We have IBM staffers who work with openssl, hopefully they will speak up if there is a problem.  That ticket is two years old.

Ask for comments, like we're doing, and then close as WONTFIX or NOTNEEDED

**Comment by paulidale** [comment]
I created this as a placeholder so we wouldn't lose track of it.  I'm fine with a won't fix resolution.

**Comment by tmshort** [comment]
If there's an IBMer who can work on/evaluate this, then sure. Otherwise, close.

**Comment by t-j-h** [comment]
Keep it open. I will sort this out if no one else does. Just rather busy with RSA conference.

**Comment by t-j-h** [comment]
Note that there are many users of OpenSSL on such platforms and they should not be removed. I've made my view on that clear ...

**Comment by levitte** [comment]
If someone wants to toss an account on an appropriate box my way, I can certainly try to help out.

**Comment by p-steuer** [comment]
There is ongoing openssl work on both z/VSE and z/OS. Whenever we find something, we'll fix it e.g. https://github.com/openssl/openssl/pull/10417 .

Regarding z/OS platform access, you could check if this ISV program is suitable:
https://www-356.ibm.com/partnerworld/wps/pub/systems/whyibm/programs

Otherwise, im still looking for a more 'quick and easy' way to provide an appropriate system (as we do at zLinux).

**Comment by mspncp** [comment]
Please note also the recent inquiry on openssl-users

- [Problems porting Openssl 1.1.1d to zos](https://mta.openssl.org/pipermail/openssl-users/2019-November/011504.html)

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
