### ISSUE TITLE
Heap leak seen for OpenSSL 1.1.0b

### ISSUE THREAD

**Issue by ghanashyams** [openssl/openssl#4155]
@levitte 

I am using openSSL 1.1.0b with patch #3035(from Levite) and is statically linked to my application dll.
The exported functions from dll are consumed from pool of threads inside application EXE.

In following scenario:

1) thread1 loads the dll, and called an exported function that consumes some openSSL feature.
2) thread2 called freeLibrary on the above dll.

When freelibrary is called if the thread1 has not exited then I am seeing a heap leak through appverifier as below.
Introducing a call to OpenSSL_thread_stop() before returnig the exported functions in my application dll helps.I dont see any more noise through app verifier. Is this the way to proceed with or any other better work around ?

00007ffdc4a3fd99 ntdll!RtlDebugAllocateHeap+0x000000000003bf65
    00007ffdc4a2db7c ntdll!RtlpAllocateHeap+0x0000000000083fbc
    00007ffdc49a8097 ntdll!RtlpAllocateHeapInternal+0x0000000000000727
    00007ffda8bbbaa2 vrfcore!VfCoreRtlAllocateHeap+0x0000000000000022
    00007ffda6ad4ced vfbasics!AVrfpRtlAllocateHeap+0x000000000000010d
    00007ffd7508636d appdll!_heap_alloc_base+0x000000000000005d [\vctools\crt\crtw32\heap\malloc.c @ 58]
    00007ffd7503f92b appdll!_heap_alloc_dbg_impl+0x000000000000027b [\vctools\crt\crtw32\misc\dbgheap.c @ 431]
    00007ffd7503ff09 appdll!_nh_malloc_dbg_impl+0x0000000000000039 [\vctools\crt\crtw32\misc\dbgheap.c @ 239]
    00007ffd7503fe99 appdll!_nh_malloc_dbg+0x0000000000000049 [\vctools\crt\crtw32\misc\dbgheap.c @ 302]
    00007ffd7502ee7a appdll!malloc+0x000000000000002a [\vctools\crt\crtw32\misc\dbgmalloc.c @ 56]
    00007ffd74db7f16 appdll!CRYPTO_malloc+0x0000000000000076 [\openssl-1.1.0b\crypto\mem.c @ 92]
    00007ffd74db82e0 appdll!CRYPTO_zalloc+0x0000000000000030 [\openssl-1.1.0b\crypto\mem.c @ 100]
    00007ffd74dbc6ec appdll!ERR_get_state+0x000000000000007c [\openssl-1.1.0b\crypto\err\err.c @ 650]
    00007ffd74dbcc84 appdll!ERR_put_error+0x0000000000000024 [\openssl-1.1.0b\crypto\err\err.c @ 359]
    00007ffd74e007c5 appdll!BIO_new_file+0x0000000000000085 [\openssl-1.1.0b\crypto\bio\bss_file.c @ 75]
    00007ffd74ea95c6 appdll!def_load+0x0000000000000036 [\openssl-1.1.0b\crypto\conf\conf_def.c @ 140]
    00007ffd74e1e0e6 appdll!NCONF_load+0x0000000000000066 [\openssl-1.1.0b\crypto\conf\conf_lib.c @ 217]
    00007ffd74dc01f6 appdll!CONF_modules_load_file+0x0000000000000086 [\openssl-1.1.0b\crypto\conf\conf_mod.c @ 129]

Thanks
Ghanashyam

**Comment by richsalz** [comment]
Yes, stopping all threads before unloading is the right thing to do.

**Comment by ghanashyams** [comment]
Stopping all threads mean calling OpenSSL_thread_stop( ) in those threads that used openSSL feature, right?

**Comment by richsalz** [comment]
Yes.

**Comment by ghanashyams** [comment]
Can't be some better design around to reduce this overhead?

**Comment by richsalz** [comment]
It seems wrong to unload a library without having all your application threads release their resources.  Or don't unload the library.  Or ignore the leaks.  Maybe @mattcaswell or @dot-asm have another idea?
