### ISSUE TITLE
X25519 implementation complicates curve order preference for consuming applications

### ISSUE THREAD

**Issue by gsuberland** [openssl/openssl#4175]
X25519 is currently implemented separately from the main ECC / ECDH functionality. I am told this is due to the fact that X25519 does not have parameters. Unfortunately the existing implementation is causing problems with consuming applications' ability to allow user-selectable curve order preferences, such as in Apache and nginx.

I believe the current behaviour in OpenSSL is to select X25519 by default when an ECDH cipher suite is selected. This is of course preferable, as P-curves have rigidity concerns (although it is worth noting that the perceived validity of this concern is orthogonal to this issue). In practice, however, it appears that consuming applications currently have to provide their own glue-code in order to support X25519 as part of a configurable curve order preference list.

This is best demonstrated in nginx. If left in a default state, X25519 is prioritised and P-curves (P-256 and P-384, iirc) are accepted as a fallback. However, if you specify the [`ssl_ecdh_curve`](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ecdh_curve) configuration directive, such as in the case of wanting to disable P-256 entirely, X25519 cannot be selected at all as it is not part of the generic ECDH implementation. This means that users are stuck with either the default configuration provided by OpenSSL, or a custom curve order with no X25519 support.

In Apache it appears that the default behaviour is different, at least from experimentation (I haven't reviewed the source). By default Apache sets P-256 and P-384 as supported. Again, using the `SSLOpenSSLConfCmd ECDHParameters` configuration directive does not allow X25519 to be selected. This implies that Apache has no X25519 support at all at the moment. This is arguably an Apache bug rather than a flaw in OpenSSL, but I would assume that it stems from the Apache team explicitly selecting a known curve preference order rather than relying upon the OpenSSL defaults, which is arguably a reasonable security decision for them to have made, albeit with unexpected side-effects.

My concern is that the current implementation forces consuming applications to include parsing and glue code for ECDH curve order lists, if the application wishes to expose this as a user preference via the accepted string-based format without (unexpectedly) losing X25519 support. While a competent developer may implement such functionality without problems, it is generally poor practice (at least in my opinion) to defer such an edge-case to the consuming application's developer, particularly when there is likely to be an expectation that all curve selection would be possible by the generic approach.

I would suggest one of two alternative approaches:

1. Make X25519 available as part of the regular ECDH APIs internally, but return an error or warning if non-null parameters are passed, thus making the distinction largely transparent to the consuming application.
2. Integrate X25519 support within function which accepts the colon-separated curve order preference string, thus alleviating the need for such code in the consuming application, but otherwise leave the ECDH APIs alone.

Should both of these approaches be deemed inappropriate, I would be interested to hear any alternative approach which results in X25519 being transparently supported as part of curve order preferences. I also admit that I am not intimately familiar with OpenSSL internals, so my apologies for any inaccuracies here.

Tagging @richsalz as I have discussed this with him to some extent on Twitter.

**Comment by davidben** [comment]
Inspecting the source, your option 2 appears to already be the case. Are you sure you are spelling it right? NGINX's `ssl_ecdh_curve` hook is implemented using the `SSL_CTX_set1_curves_list` (available in all versions X25519 is available) which does not depend on the `EC_KEY` machinery. Note how, if `EC_curve_nist2nid` can't find a NIST curve, it just looks up the NID by name. X25519 has a NID named "X25519".
https://github.com/openssl/openssl/blob/master/ssl/t1_lib.c#L429

**Comment by mattcaswell** [comment]
I was going to say the same thing. AFAIK option 2 is already the case?

**Comment by gsuberland** [comment]
I don't have nginx to hand to re-verify, but Apache 2.4.27 with OpenSSL 1.1.0f uses P-256 by default:

```
# openssl version
OpenSSL 1.1.0f  25 May 2017

# openssl s_client -debug -connect 127.0.0.1:443
[snip]
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
[snip]
``` 

Specifying `SSLOpenSSLConfCmd ECDHParameters X25519` fails:

```
[ssl:emerg] [pid 4016:tid 396] AH02407: "SSLOpenSSLConfCmd ECDHParameters X25519" failed for servertwo.tld:443
[ssl:emerg] [pid 4016:tid 396] AH02312: Fatal error initialising mod_ssl, exiting.
```

As does `SSLOpenSSLConfCmd Curves X25519`:

```
[ssl:emerg] [pid 4316:tid 412] AH02407: "SSLOpenSSLConfCmd Curves X25519" failed for servertwo.tld:443
[ssl:emerg] [pid 4316:tid 412] AH02312: Fatal error initialising mod_ssl, exiting.
```

Whereas both cases work just fine when P-256 is given as a curve name.

It appears that I may be wrong about nginx's behaviour, although the configuration has caused some confusion to other users regardless (see #2188).

**Comment by davidben** [comment]
As folks said on that bug, #2188 has nothing to do with whether X25519 is an `EC_KEY` and instead is because TLS 1.2 uses the same curve list for ECDSA as ECDHE. This means you cannot use an ECDSA certificate without allowing the corresponding curve. Indeed that it got as far as failing the handshake like that suggests setting X25519 in NGINX *does* work.

The ECDHParameters string command indeed wraps the legacy API and does not work with X25519. That can probably be fixed but since it only supports one curve, you would run into the same issue as #2188 for an ECDSA certificate.
https://github.com/openssl/openssl/blob/master/ssl/ssl_conf.c#L222

The Curves command should call the same function as NGINX (which, per #2188 does accept X25519). Are you sure your Apache is actually running against 1.1.0f? That it has a default of P-256 makes me think you linked against a system copy of 1.0.2 or so.

**Comment by kroeckx** [comment]
At least in the master branch, using "-groups P-256" or "-groups X25519" works for me for both client and server and seems to do what is expected.

But the -groups option was added in the master branch, not in the 1.1.0 stable versions.

And we actually seem to test for X25519 in the 1.1.0 stable branch's test suite, so I assume it just works there too.

(Curves is an alias for Groups in master, Curves should work in 1.1.0, both should work in master.)

**Comment by gsuberland** [comment]
davidben said:

> Are you sure your Apache is actually running against 1.1.0f? That it has a default of P-256 makes me think you linked against a system copy of 1.0.2 or so.

D'oh! I was testing against a Windows version of Apache which had the new OpenSSL libraries (libssl, libcrypto) but *also* the old 1.0.2 libeay32/ssleay32 libraries, and for some reason it was using those old libraries despite having the latest mod_ssl version.

Wiping the directory and loading a brand new VC15 build in with only the libssl/libcrypto libraries resolved the issue. X25519 is now used by default. Apologies for all the confusion and huge thanks for giving me the nudge in the right direction!

**Comment by snhenson** [comment]
The main reason X25519 is implemented separately is differences between the algorithm and other curves. The ASN.1 format for keys has a new "top level" algorithm OID for it instead of using the ecPublicKey with a separate curve OID.
