### ISSUE TITLE
Signing OCSP responses with RSA PSS

### ISSUE THREAD

**Issue by dcooper16** [openssl/openssl#4184]
As far as I can tell the command-line tool for generating OCSP responses does not provide a way to sign the responses using RSA PSS. Other command-line tools, such as `req`, `ca`, and `x509`, provide the option to use RSA PSS by accepting the `-sigopt` option. Is there a reason the `-sigopt` option was added to `req`, `ca`, and `x509`, but not `ocsp`?

I've developed a patch for `ocsp` to accept the `-sigopt` option for signing OCSP responses (but not OCSP requests), and I can submit it as a PR if there is interest. I expect that it will need some work, though, as I am not very familiar with the OpenSSL code base. I mainly wrote the patch by copying similar code from other modules.

**Comment by richsalz** [comment]
yes, please submit the PR.  And sign our CLA.  thank you!

**Comment by mattcaswell** [comment]
Linked PR was fixed. Closing.
