### ISSUE TITLE
About Link error 

### ISSUE THREAD

**Issue by dskim4747** [openssl/openssl#4189]
This are some parts of link errors happened after i start command >  nmake -f cedll.mk   
I was compiling openssl for WIN-CE. the characters below means that they cant check the external symbol... please give me some advise to solve this problem 

-------------------------------------------------------------------------------------------------------------------
cryptlib.obj : error LNK2019: __GetUserKData 외부 기호(참조 위치: GetCurrentThreadId 함수)에서 확인하지 못했습니다.
rand_win.obj : error LNK2001: __GetUserKData 외부 기호를 확인할 수 없습니다.
cryptlib.obj : error LNK2019: __imp___itod 외부 기호(참조 위치: CRYPTO_get_new_lockid 함수)에서 확인하지 못했습니다.
b_print.obj : error LNK2001: __imp___itod 외부 기호를 확인할 수 없습니다.
md_rand.obj : error LNK2001: __imp___itod 외부 기호를 확인할 수 없습니다.
randfile.obj : error LNK2001: __imp___itod 외부 기호를 확인할 수 없습니다.
cryptlib.obj : error LNK2019: __imp___muld 외부 기호(참조 위치: CRYPTO_get_new_lockid 함수)에서 확인하지 못했습니다.
b_print.obj : error LNK2001: __imp___muld 외부 기호를 확인할 수 없습니다.
ts_rsp_verify.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
cms_ess.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
pk7_doit.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
ocsp_vfy.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
pqueue.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
v3_utl.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
v3_ncons.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
cms_sd.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
cms_dd.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
a_set.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
tasn_enc.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
asn1_lib.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
x509_cmp.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
ecs_vrf.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
obj_dat.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
obj_lib.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
bio_ok.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
rsa_saos.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
rsa_pss.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
rsa_pmeth.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
dsa_asn1.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
cryptlib.obj : error LNK2019: memcmp 외부 기호(참조 위치: CRYPTO_THREADID_cmp 함수)에서 확인하지 못했습니다.
set_key.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
wrap128.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
rsa_sign.obj : error LNK2001: memcmp 외부 기호를 확인할 수 없습니다.
cryptlib.obj : error LNK2019: MessageBoxW 외부 기호(참조 위치: OPENSSL_showfatal 함수)에서 확인하지 못했습니다.
cryptlib.obj : error LNK2019: _vsnwprintf 외부 기호(참조 위치: OPENSSL_showfatal 함수)에서 확인하지 못했습니다.
cryptlib.obj : error LNK2019: MultiByteToWideChar 외부 기호(참조 위치: OPENSSL_showfatal 함수)에서 확인하지 못했습니다.
o_dir.obj : error LNK2001: MultiByteToWideChar 외부 기호를 확인할 수 없습니다.
dso_win32.obj : error LNK2001: MultiByteToWideChar 외부 기호를 확인할 수 없습니다.
bss_file.obj : error LNK2001: MultiByteToWideChar 외부 기호를 확인할 수 없습니다.
ts_lib.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
srp_lib.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
srp_vfy.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
wcecompatex.lib(time.obj) : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
wp_dgst.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
wp_block.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
ts_rsp_sign.obj : error LNK2019: __security_cookie 외부 기호(참조 위치: TS_RESP_create_tst_info 함수)에서 확인하지 못했습니다.
ts_rsp_verify.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
ocsp_vfy.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
ui_lib.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
ui_openssl.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
ui_util.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
p12_mutl.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
p12_npas.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
ocsp_lib.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
ocsp_srv.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
pk7_smime.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
p12_crpt.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
p12_crt.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
p12_decr.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
cms_kari.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
conf_def.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
conf_mod.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.
pk7_doit.obj : error LNK2001: __security_cookie 외부 기호를 확인할 수 없습니다.

----------------------------------------------------------------------------------------------------------------

**Comment by nickthetait** [comment]
The maintainers may be able to help you more if they could see the command output in English. There should be a way to temporarily change the locale for your terminal. I'm unaware of how to do this on windows, but search around for something like "change/override locale/language windows terminal/command" for a tutorial.

**Comment by mattcaswell** [comment]
Is this still an issue? Please provide full details of the build steps you took and the version of OpenSSL.

**Comment by mattcaswell** [comment]
No response to my earlier question. Closing.
