### ISSUE TITLE
apps require me to enter the pass phrase for a key twice

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4195]
It seems that recently changed something to the handling of reading pass phrases for private keys. It now requires me to enter the correct password 2 times after each other. If I first type a wrong one, it still requires me to enter the password 2 times. This is only in the master branch.

**Comment by petrovr** [comment]
Kurt Roeckx wrote:
> It seems that recently changed something to the handling of reading pass phrases for private keys. It now requires me to enter the correct password 2 times after each other. If I first type a wrong one, it still requires me to enter the password 2 times.
>
https://github.com/openssl/openssl/issues/4147

**Comment by levitte** [comment]
Addressed in #4198
