### ISSUE TITLE
MD4 and MD5 differences.

### ISSUE THREAD

**Issue by yuhong** [openssl/openssl#4199]
I noticed https://github.com/openssl/openssl/commit/3009458e2f63b84e9631dfbf8b5c7cb38b2b283c#diff-c1d3fb8d60b1ac08be5a7c9a81bea049 . MD4 and MD5 are similar. I wonder if they could share some code. (Ideally it should be removed but I think NT password hashes use it.)

**Comment by yuhong** [comment]
Actually, I think the differences between the two files are so minor they might not be copyrightable.

**Comment by levitte** [comment]
It's true that they are very similar.  Their copyrightability is a different question entirely, though.

**Comment by richsalz** [comment]
It's not worth merging the code -- it works, there are assembler versions, and both algorithms are outdated anyway.  Closing this issue.  But thanks for looking at it.
