### ISSUE TITLE
Unreachable code in ssl test

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4200]
In test/ssl_test_ctx.c at the end of the file there are checks for server2 and resume-server2 that can never be reached because the checks for server and resume-server would already have matched. Using strncmp() or changing the order will probably fix this, but I wonder why things aren't broken.

There also seem to be some TEST_tree() calls missing.

**Comment by paulidale** [comment]
I must be missing something, the code uses `strcmp`to look for these strings which should work.  Using `strncmp` would cause a mismatch.

The `TEST_true` is definitely an issue.  I think they should be removed and informative messages added instead -- parse_client_options and parse_server_options produce error messages so there is no need to double up.

**Comment by paulidale** [comment]
The parse_client_options and parse_server_options functions print out sufficient information.
The `TEST_true` calls just need to be removed I think.

**Comment by kroeckx** [comment]
The strcmp()s where correct, the strncmp() would cause the problem.
