### ISSUE TITLE
Is there a flag to disable man pages (html) from being generated during the build?

### ISSUE THREAD

**Issue by sully7** [openssl/openssl#4215]
Just curious, and didn't know if there was a better place to post to ask... but is there a configuration you can use during the build to turn off the documentation / "man pages" from getting created/copied during a build?

I'm fairly new to OpenSSL, but after poking around for a while, I was able to find the `process_docs.pl`, as well as the `install_html_docs` in the makefile... but short of ripping it out of the makefile template, it doesn't seem like there's a good way to just switch it off.

**Comment by levitte** [comment]
You mean during installation...

If you look for `install:` in the Makefile, you'll find this:

```
install: install_sw install_ssldirs install_docs
```

So I'd suggest you try this:

```
$ make install_sw install_ssldirs
```
