### ISSUE TITLE
BN_hex2bn( )  stops reading when non-hex characters are encountered and continues with incompletely inputs. 

### ISSUE THREAD

**Issue by Souravpunoriyar** [openssl/openssl#4228]
From Man Page:
BN_hex2bn() converts the string str containing a hexadecimal number to a BIGNUM and stores it in **bn. If *bn is NULL, a new BIGNUM is created. If bn is NULL, it only computes the number's length in hexadecimal digits. If the string starts with '-', the number is negative. A "negative zero" is converted to zero. BN_dec2bn() is the same using the decimal system.

BN_hex2bn( ) doesnot give any info if input data has any non-hex characters. It takes all the valid hex values until it encounter an invalid character and goes ahead (with bn not NULL)..
Example:-
const char p_str1[] = "11111111#22222222";
const char p_str2[]= "33333333#44444444" ;
BN_hex2bn(&p, p_str1);
BN_hex2bn(&q, p_str2);
BN_add(r, p, q);
gives result: 44444444

Looking into BN_hex2bn( ) code in openssl.
for (i = 0; i <= (INT_MAX/4) && isxdigit((unsigned char)a[i]); i++)
continue; /* t doesnot gives info of invalid hex-char inputs */

"The manpage could say that it stops on wrong characters"

**Comment by richsalz** [comment]
```
; gcc a.c -lcrypto
; ./a.out
i = 3
; cat a.c

#include <openssl/bn.h>
#include <stdio.h>

int main()
{
    BIGNUM *b = BN_new();
    int i;

    i = BN_hex2bn(&b, "123#456");
    printf("i = %d\n", i);
    return 0;
}
```
The wording is there, but not clear "return the length of valid representation."
PR pending with better wording.

**Comment by richsalz** [comment]
PR #4234 merged.  thanks.
