### ISSUE TITLE
X509_NAME_print_ex in RFC 2253 format

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#4232]
I parse a X509_NAME with X509_NAME_add_entry_by_NID and when I use X509_NAME_print_ex with flag = XN_RFC_2253 the resulted string is always flipped.

e.g. 
1 run
C=DE, O=T-Systems, CN=Joe Doe
CN=Joe Doe, O=T-Systems, C=DE

2 run
CN=Joe Doe, O=T-Systems, C=DE
C=DE, O=T-Systems, CN=Joe Doe

and the same strings will never be equal. When I use instead X509_NAME_print_ex without the flag XN_RFC_2253 the strings are equal. My question is now should a rfc 2253 string not always be generated in the same way?

**Comment by richsalz** [comment]
I don't understand what you are saying.  Are you saying that your code doesn't match what the one-line call to X509_NAME_print_ex does?  Perhaps you should post what you're doing.

**Comment by snhenson** [comment]
From RFC2253: 

>    Otherwise, the output consists of the string encodings of each
>    RelativeDistinguishedName in the RDNSequence (according to 2.2),
>    starting with the last element of the sequence and moving backwards
>    toward the first.
>
