### ISSUE TITLE
Increased latency in TLS 1.3

### ISSUE THREAD

**Issue by nrobbin** [openssl/openssl#4237]
I have noticed that the latency of "simple" applications seems to be higher using TLS 1.3 as compared to TLS 1.2.  I found issue #3906 (and #3955) and believe that a larger fix or application note is required.  It is not just early data that is impacted, but all scenarios where the client is the first side to send application data after the TLS 1.3 handshake.

For the purposes of discussion, a simple application is one that does:
```
 SSL_connect();
 SSL_write(client_request);
 SSL_read(server_response);
```

In TLS 1.2, the SSL_connect() call returns after reading the server finished message.

In TLS 1.3 however, the SSL_connect() call returns just after writing the client finished message.  If TCP_NODELAY is disabled (Nagle is enabled), it is likely that the sending of the client_request will be buffered by the TCP stack.  The protocol change means that clients enabling TLS 1.3 will see increased latency unless they make other changes.

**Comment by kaduk** [comment]
Who speaks last in a full handshake is something that changed from TLS 1.2 to TLS 1.3, yes; it's a rather inherent/fundamental difference.
However, it's incredibly unclear that OpenSSL should be responsible for attempting to put in any sort of mitigation for the consequence you observe.  There is not a particularly portable way to do so in code, and we promise to do the crypto and TLS protocol bits, but not really the "transmit them on the wire" part.  From this perspective, the onus to work around the Nagle behavior lies on the applications experiencing performance concerns -- there doesn't seem to be rope given to OpenSSL to do anything.

**Comment by nrobbin** [comment]
I agree with you that this is the responsibility of the application to solve in the general case.  OpenSSL is not responsible for TCP issues.

I do think OpenSSL can provide some help to the application programmer.  A documentation note was added for TLS 1.3 early data.  This note should be expanded to explain that it covers not just TLS 1.3 early data, but all TLS 1.3 handshakes where the client "speaks" first.

Also, while I understand that s_time isn't truly designed for speed, it could call BIO_set_tcp_ndelay for TLS 1.3 and TLS 1.2 session reuse cases which would provide additional clues to developers.

**Comment by mattcaswell** [comment]
It occurs to me that this issue could happen even in TLSv1.2 in a resumption handshake.
