### ISSUE TITLE
Implement more default threadid callbacks

### ISSUE THREAD

**Issue by Manishearth** [openssl/openssl#426]
We currently provide [a default `threadid_callback()`](https://github.com/openssl/openssl/blob/master/crypto/thr_id.c#L186) for Windows only. Everywhere else, we use `CRYPTO_THREADID_set_pointer(id, (void *)&errno);`, i.e. the address of `errno` is used to identify the thread.

This caused a scary-looking [malloc crash](https://github.com/servo/servo/pull/7837#issuecomment-145351797) (free-after-free), which was due to a race in `ERR_get_state` (when the error is put in the hashmap). It turned out that [our OpenSSL bindings](https://github.com/sfackler/rust-openssl/pull/282) didn't set `threadid_callback`, causing a crash on OS X. (Related note: I'm pretty sure "address of errno" should have worked too since errno is an lvalue. I'm not sure if there's something to be investigated there. However, the changes in the linked PR stopped the crash from happening)

I feel that OpenSSL should provide defaults for more OSes. We could just copy the implementations [in the testing code](https://github.com/openssl/openssl/blob/master/crypto/threads/mttest.c#L115) for irix/solaris/posix/netware/beos.

I'm willing to make the PR for this myself, I'd just like to see if that's a change openssl is willing to accept (and if I've missed something) :smile:

**Comment by richsalz** [comment]
Our plan is to use native threads and remove the "run-time callbacks" instead of the current approach.  See #451
