### ISSUE TITLE
Issue with latest openssl-1.1.0f with android-ndk-r8e

### ISSUE THREAD

**Issue by amit1990sumit** [openssl/openssl#4262]
I am getting an error in openssl while compiling app with openssl-1.1.0f using android-ndk-r8e.
Please help me, I am not able to figure out this.

**Below are the errors getting in openssl.**
1) libcrypto.a(init.o):init.c:function ossl_init_base_ossl_: error: undefined reference to 'atexit'
2) error: invalid use of incomplete type 'SSL_CTX {aka struct ssl_ctx_st}'
/ossl_typ.h:145:16: error: forward declaration of 'SSL_CTX {aka struct ssl_ctx_st}'
3)  error: invalid use of incomplete type 'SSL {aka struct ssl_st}'
 ossl_typ.h:144:16: error: forward declaration of 'SSL {aka struct ssl_st}'

**Comment by FdaSilvaYY** [comment]
Same as #2239 and others...
This structure is now opaque and allocated/handled/freed using dedicated methods.

**Comment by richsalz** [comment]
@FdaSilvaYY is right for 2 and 3; it's probably a bug in your application.  But 1 is different.  Please post the error message.

**Comment by amit1990sumit** [comment]
@FdaSilvaYY/ @richsalz thank you so much for the reply.
**Regarding 1 issue.**
I am using 
**status = curl_easy_setopt(curlHandle, CURLOPT_SSL_CTX_FUNCTION, SslPreInitListener);**
SslPreInitListener contains three paramter(CURL * curlHandle, SSL_CTX * sslCtx, void * ctxData) which is called by curl, now how I will handle this because I am not created SSL_CTX instead getting this from curl as a callback return and if access **sslCtx->app_verify_arg = ctxData;** it gives error.
I am using curl latest version 7.55.1.

**Regarding 3 issue.**
I am getting same error as mentioned above.
libcrypto.a(init.o):init.c:function ossl_init_base_ossl_: error: undefined reference to 'atexit'
collect2: error: ld returned 1 exit status. Below is the code snipet where issue is coming.
If I comment **"atexit(OPENSSL_cleanup);"** then it works fine.

`DEFINE_RUN_ONCE_STATIC(ossl_init_base)
{
#ifdef OPENSSL_INIT_DEBUG
    fprintf(stderr, "OPENSSL_INIT: ossl_init_base: Setting up stop handlers\n");
#endif
    /*
     * We use a dummy thread local key here. We use the destructor to detect
     * when the thread is going to stop (where that feature is available)
     */
    CRYPTO_THREAD_init_local(&threadstopkey, ossl_init_thread_stop_wrap);
#ifndef OPENSSL_SYS_UEFI
    **atexit(OPENSSL_cleanup);**
#endif
    if ((init_lock = CRYPTO_THREAD_lock_new()) == NULL)
        return 0;
    OPENSSL_cpuid_setup();

    /*
     * BIG FAT WARNING!
     * Everything needed to be initialized in this function before threads
     * come along MUST happen before base_inited is set to 1, or we will
     * see race conditions.
     */
    base_inited = 1;

#if !defined(OPENSSL_NO_DSO) && !defined(OPENSSL_USE_NODELETE)
# ifdef DSO_WIN32
    {
        HMODULE handle = NULL;
        BOOL ret;

        /* We don't use the DSO route for WIN32 because there is a better way */
        ret = GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS
                                | GET_MODULE_HANDLE_EX_FLAG_PIN,
                                (void *)&base_inited, &handle);

        return (ret == TRUE) ? 1 : 0;
    }
# else
    /*
     * Deliberately leak a reference to ourselves. This will force the library
     * to remain loaded until the atexit() handler is run at process exit.
     */
    {
        DSO *dso = NULL;

        ERR_set_mark();
        dso = DSO_dsobyaddr(&base_inited, DSO_FLAG_NO_UNLOAD_ON_FREE);
        DSO_free(dso);
        ERR_pop_to_mark();
    }
# endif
#endif

    return 1;
}`

**Comment by richsalz** [comment]
Curl builds with openssl 1.1.0; if you are having problems with curl source, try asking "over there."
Atexit is part of windows.  How did you configure openssl?

**Comment by amit1990sumit** [comment]
@richsalz, Thanks for the reply.
Sure I will ask this to curl team.
Below is my openssl config command.
./Configure android -no-asm -fpic

**Comment by mattcaswell** [comment]
Android support in 1.1.1 has bee overhauled. Moving this issue to 1.1.0 milestone.

**Comment by t8m** [comment]
This is an issue in an unsupported 1.1.0 branch. Closing.
