### ISSUE TITLE
'ssl.h ... asn1.h: cannot parse' errors for mingw-w64 builds on Windows

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#4267]
Hello everyone,

For builds using mingw-w64 got errors:
```
./Configure shared mingw64 && make

<snip>

test/testutil/tests.c:214:1: note: in expansion of macro 'DEFINE_COMPARISONS'
 DEFINE_COMPARISONS(size_t, size_t, "%zu")
 ^~~~~~~~~~~~~~~~~~
ar  r test/libtestutil.a apps/win32_init.o test/testutil/basic_output.o test/testutil/cb.o test/testutil/driver.o test/testutil/format_output.o test/testutil/init.o test/testutil/main.o test/testutil/output_helpers.o test/testutil/stanza.o test/testutil/tap_bio.o test/testutil/test_cleanup.o test/testutil/tests.o
C:\ProgramData\Mingw64\bin\ar.exe: creating test/libtestutil.a
ranlib test/libtestutil.a || echo Never mind.
make -f ./Makefile.shared -e \
	ECHO=echo \
	PLATFORM=mingw64 \
	PERL="perl" SRCDIR='.' DSTDIR="." \
	INSTALLTOP='/usr/local' LIBDIR='lib' \
	LIBDEPS=' '""' -lws2_32 -lgdi32 -lcrypt32 ' \
	LIBNAME=crypto SHLIBVERSION=1.1 \
	STLIBNAME=libcrypto.a \
	SHLIBNAME=libcrypto.dll.a SHLIBNAME_FULL=libcrypto-1_1-x64.dll \
	CC='gcc' CFLAGS='-DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1_1\"" -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m64 -Wall -O3 -D_MT  -D_WINDLL' \
	LDFLAGS='' SHARED_LDFLAGS='-static-libgcc ' \
	RC='windres' SHARED_RCFLAGS='--target=pe-x86-64' \
	link_shlib.mingw-shared
make[2]: Entering directory '/c/libOPENSSL-1.1.1-dev/build'
File include/openssl/ssl.h: cannot parse: ()()))
#INFO::;
File include/openssl/ssl.h: cannot parse: ()()))
#INFO::DEPRECATEDIN_1_1_0;
File include/openssl/ssl.h: cannot parse: ()
#INFO::;
File include/openssl/ssl.h: cannot parse: ()


enum;
File include/openssl/asn1.h: cannot parse: ()
#INFO::;
File include/openssl/asn1.h: cannot parse: ()
#INFO::;
File include/openssl/asn1.h: cannot parse: ()
#INFO::;
File include/openssl/asn1.h: cannot parse: ()
#INFO::;
File include/openssl/asn1.h: cannot parse: ()
#INFO::;
File include/openssl/asn1.h: cannot parse: ()

#INFO::;
File include/openssl/asn1.h: cannot parse: ()

#INFO::;
File include/openssl/asn1.h: cannot parse: ()

#INFO::;
File include/openssl/asn1.h: cannot parse: ()

#INFO::;
```
on which OpenSSL build stop respond.

Reproduced for:
- builds using mingw-w64 with `Shared` layout,

not reproduced for:
- builds using mingw-w64 with `Static` layout,
- builds using MSVC with `Shared` layout.

Environment:
- Windows 10 x64,
- mingw-w64 <6.3.0|7.2.0> x86_64,
- msys2-x86_64-20161025 with recent updates,
- OpenSSL-1.1.1-dev (32c1356302e74dfa5e8bd2d7002c18d91a323b70).

Tested few snapshots and got results:
32c1356302e74dfa5e8bd2d7002c18d91a323b70 build stop respond
4dae7cd3f0f074e01b2fe73ffff0dfbf032fa566 build stop respond
0443b1171da43696a2cd67cfcb0624be1e3ee25b build broken
e15c95ce8596bcc2a5f5e163ff78ccf469dbf994 build broken
11a25d34549461ad6ddd61322ed3b54dd4c69686 build successfull

Alexander

**Comment by levitte** [comment]
Make sure that you use the mingw perl, not the msys one.  If I understand correctly, they have some subtle differences...

**Comment by sav-ix** [comment]
Did you mean to use MSYS2 Perl (https://msys2.github.io/) instead of ActiveState Perl (https://www.activestate.com/ActivePerl), as mentioned in OpenSSL [documentation](https://github.com/openssl/openssl/blob/master/NOTES.WIN)? If yes, I did so. If not, I'm really confused, since MSYS2 Perl is essential part of MSYS2 and it would be hard to replace its bunded Perl with 3rdparty one.

Me used MSYS2 Perl for builds using mingw-w64 starting from OpenSSL 1.0.2x to 1.1.1-dev https://github.com/openssl/openssl/commit/11a25d34549461ad6ddd61322ed3b54dd4c69686, and there were no troubles with it. Does it mean there were some changes to OpenSSL build system after mentioned PR, which broke MSYS2 compatibility?

In addition, static builds using mingw-w64 with MSYS2 Perl finishes successfully. So is the problem really in Perl?

**Comment by mattcaswell** [comment]
I think @levitte meant it the other way around. Use the msys2 one not the mingw one.

I cannot reproduce this issue. I updated my msys2 install to the latest (via "pacman -Syu"), which gives me:
````
$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 7.2.0

$ perl --version

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-msys-thread-multi
````

I checked out the commit you mentioned (32c1356) and configured/built using the exact same command as you did. Everything built fine. I subsequently got some "make test" errors, but that seems to be unrelated to your issue. The only significant environmental difference I can see is that I only have Win 8.1 not 10 - but I can't think that that would have anything to do with it.

**Comment by sav-ix** [comment]
Found source of error. Some OpenSSL source files were checked out with `CRLF` line terminators instead of `LF` ones. After setting all to `LF` build error gone.
Not sure whether it's bug or feature, but it's a weak part of OpenSSL [Perl-based] build system, which limits OpennSSL sources to be distributed in Unix format only. Perhaps this should be mentioned in OpenSSL documentation. At least I didn't found any other notable OSS project, which throw build errors depending of line terminators.

**Comment by levitte** [comment]
Hmmm...  I thought I had found all the places where the line terminator could cause trouble.  Apparently not.  I'll have another look at `util/mkdef.pl`...

**Comment by levitte** [comment]
I may have found it...  @sav-ix, would you be willing to try this patch?

``` diff
diff --git a/util/mkdef.pl b/util/mkdef.pl
index 8c0ccd0c76..f0d8952c4b 100755
--- a/util/mkdef.pl
+++ b/util/mkdef.pl
@@ -412,10 +412,10 @@ sub do_defs
 
                print STDERR "DEBUG: parsing ----------\n" if $debug;
                while(<IN>) {
+                       s|\R$||; # Better chomp
                        if($parens > 0) {
                                #Inside a DEPRECATEDIN
                                $stored_multiline .= $_;
-                               $stored_multiline =~ s|\R$||; # Better chomp
                                print STDERR "DEBUG: Continuing multiline DEPRECATEDIN: $stored_multiline\n" if $debug;
                                $parens = count_parens($stored_multiline);
                                if ($parens == 0) {
```

**Comment by levitte** [comment]
(it would be extra good if you got some of the OpenSSL header files to be terminated with CRLFs

**Comment by levitte** [comment]
Even better, try #4304

**Comment by sav-ix** [comment]
Downloaded fresh OpenSSL master with `LF` line terminators, run build using mingw-w64:
```
./Configure shared mingw64 >_Configure.log && make
```
and all build tasks finished successfully.

Then converted sources to `CRLF` line terminators using command:
```
find . -name "*" -type f -exec perl -i.mybackup -pe 's/\n/\r\n/;' {} \; && find . -name "*.mybackup" -type f -delete
```
and build using mingw-w64 finished with `#INFO::; ... File include/openssl/asn1.h: cannot parse: ()` errors.
Then applied PR https://github.com/openssl/openssl/pull/4304/commits/526e6ea4ef13318e5c53f14593ecba80d95222e4 to sources with `CRLF` line terminators and all build tasks finished successfully.
Thank you for [a quick] fix.

**Comment by sav-ix** [comment]
Also got an error:
```
../test/recipes/80-test_pkcs12.t ................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```
during `make test` run for `CRLF` line terminated sources. Not reproduced for `LF` terminated ones.

**Comment by mattcaswell** [comment]
Does the same test always reliably fail? I am seeing some intermittent failures aside from those covered by #4305, and the ones discussed in #4306. Possibly some kind of race condition.

**Comment by sav-ix** [comment]
Made two more builds  using mingw-w64 with https://github.com/openssl/openssl/commit/526e6ea4ef13318e5c53f14593ecba80d95222e4 applied and `LF` line terminators. In both cases `80-test_pkcs12.t` test run finished successfully.
Made two more builds  using mingw-w64 with https://github.com/openssl/openssl/commit/526e6ea4ef13318e5c53f14593ecba80d95222e4 applied and `CRLF` line terminators. In both cases `80-test_pkcs12.t` test run failed.
@mattcaswell, I assume this should be reproducible on your system too.

**Comment by mattcaswell** [comment]
I could reproduce this. I think this is related to your "find" based conversion method for LF->CRLF. Specifically it seems to modify test/shibboleth.pfx which is treated by git as a binary file (because it is). However your routine changes it anyway - which obviously then causes the test to fail that uses it.

**Comment by sav-ix** [comment]
I confirm, file ` test/shibboleth.pfx` is damaged after `LF → CRLF` conversion. Thank you for clarification.

**Comment by levitte** [comment]
It's unlikely that this will happen because of git, considering the following line in `.gitattributes`:

```
*.pfx binary
```
