### ISSUE TITLE
dsa_do_sign() can segfault with non-FIPS 186 compliant keys

### ISSUE THREAD

**Issue by kkanago** [openssl/openssl#4278]
In FIPS mode, dsa_do_sign() uses fips_check_dsa_prng() to detect keys with invalid parameters. If an invalid key is detected the routine jumps to the label “err” where it calls BN_clear_free() twice passing the uninitialized stack variables m and xr. If the contents of  these variables are not zeros, BN_clear_free() may call OPENSSL_cleanse() with an invalid pointer which can cause a segfault.  In addition the code after err calls DSAerr with a reason of ERR_R_BN_LIB which is incorrect/misleading. Keys that are too short are correctly handled so a good test case is a 4k key.

It looks like this could be corrected by replacing the “goto err;” after fips_check_dsa_prng() with “return NULL;” as is done with the other error checking in this routine

**Comment by richsalz** [comment]
We are not making any changes to the existing FIPS code.  The new FIPS project will take a different approach.  Closing this.
