### ISSUE TITLE
Install issue NASM not found

### ISSUE THREAD

**Issue by markgreve** [openssl/openssl#4280]
I installed nasm-2.14rc0-installer-x64.exe  set the path C:\Program Files\NASM
Using    openssl-1.1.0f.tar.gz
Pearl    ActivePerl-5.24.1.2402-MSWin32-x64-401627.exe      64bit

Ran the following pearl command from the folder that openssl was extracted to 
perl Configure VC-WIN64A

C:\VisaCheckout\OpenSSL\OpenSSLApp\openssl-1.1.0f>perl Configure VC-WIN64A
Configuring OpenSSL version 1.1.0f (0x1010006fL)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default]
    no-zlib-dynamic [default]
Configuring for VC-WIN64A
NASM not found - please read INSTALL and NOTES.WIN for further details

**Comment by mattcaswell** [comment]
What happens if you type "nasm" from the command prompt? Does it find it? If not then your PATH updates have not taken.

**Comment by markgreve** [comment]
Path update didn't take when powered down and restarted command worked.
