### ISSUE TITLE
Restore server state from TLS 1.3 HRR cookie

### ISSUE THREAD

**Issue by tatsuhiro-t** [openssl/openssl#4283]
I try to implement the stateless retry described in:

https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#rfc.section.4.2.2

> Allowing the server to offload state to the client, thus allowing it to send a HelloRetryRequest without storing any state. The server can do this by storing the hash of the ClientHello in the HelloRetryRequest cookie (protected with some suitable integrity algorithm).

Is that possible with the current OpenSSL API?   It looks like echoing back cookie is implemented (#2839).
This is required to implment QUIC stateless retry, and client address validation.

**Comment by mattcaswell** [comment]
No - there is no support for enabling an OpenSSL server to send a cookie. If a client receives one from a server then it will echo it back.

**Comment by tatsuhiro-t** [comment]
Thank you for prompt reply.  Is there any plan to implement server side functionality?

**Comment by mattcaswell** [comment]
Not at the moment. No one has asked for it until now. :-) Perhaps you could elaborate on why this is needed.

**Comment by tatsuhiro-t** [comment]
Yes, I need this feature to implement QUIC.
QUIC uses TLSv1.3 handshake to derive key materials.  The current draft mandates stateless retry which utilizes HRR cookie.  I haven't still fully understand everything, but so far it requires for server to store its state (probably, CH hash as described in TLS1.3 draft) in cookie extension in HRR, and reconstructs the previous state from the cookie the client echos back.  Using cookie this way also provides client address validation.

For relevant section of QUIC draft is as follows:
https://quicwg.github.io/base-drafts/draft-ietf-quic-tls.html#rfc.section.8.1
https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.5.4.2

**Comment by mattcaswell** [comment]
I'll look into the feasibility/desirability of this. It might take a while to get to the top of my TODO list :-)

**Comment by tatsuhiro-t** [comment]
After some interop sessions with another QUIC implementation, server needs to send data to restore server state + application specific data (for QUIC, this is client address validation token) in HRR cookie.

**Comment by richsalz** [comment]
@mattcaswell FYI this means that QUIC cannot be built using standard OpenSSL.  Please bump the priority :)

**Comment by mattcaswell** [comment]
See my initial analysis of stuff we will need to do for QUIC here:

https://mta.openssl.org/pipermail/openssl-dev/2017-September/009713.html

**Comment by tatsuhiro-t** [comment]
As for early_exporter_master_secret, QUIC does not send early data in a way TLS does.  It sends the data encrypted by a key which is derived from early_exporter_master_secret.
Therefore, QUIC client probably does not send early_data extension.  The crypto library is expected to export key material using early_exporter_master_secret without the existence of the extension in Client Hello.

I'm playing with OpenSSL source code how to achieve this.
Looks like tls13_change_cipher_state provides all data necessary to compute early_exporter_master_secret.  Currently, for early secret derivation, it is only called when early data is indicated in Client Hello.
