### ISSUE TITLE
who can tell me why when i used perl to compile the  OpenSSL the cmd telled  me directory given with --prefix MUST be absolute? 

### ISSUE THREAD

**Issue by hangyiwei** [openssl/openssl#4285]
How can i fixed it ?

**Comment by richsalz** [comment]
This is a bit confusing.  I am not sure I understand your question.
What system are you using?  What exactly was the commandline you used?
What version of openssl?
Do you mean that you did '--prefix=foo' or something?  You need to do '--prefix=/path/to/foo'

**Comment by hangyiwei** [comment]
I have solved the problem,BTW,Thanks!
