### ISSUE TITLE
Wrong decoding UTF8Srings in X509v3 extensions of certificate

### ISSUE THREAD

**Issue by Aleksandr-ru** [openssl/openssl#4288]
I'm trying to get text from certificate with command
`openssl x509 -engine gost -noout -inform pem -text -in /path/to/file.pem`
the result is correct, but not in the " X509v3 extensions:" section
```
[...]
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment, Data Encipherment, Key Agreement
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, E-mail Protection

            X509v3 Certificate Policies: 
                Policy: 1.2.643.100.113.1

            1.2.643.100.112: 
                0..."........ "............-...... 3.3"........ .... "Notary-PRO" v.2.7.7.................... ... 149/3/2/2-1269 .... 21.07.2014.6.................... ... 149/7/1/1-921 .... 10.11.2014
            1.2.643.100.111: 
                .0"......................" (.............. ......)
[...]
```
See that 1.2.643.100.111 and 1.2.643.100.112 have dots, but it should be Cyrillic chars because this extensions are UTF8Strings.
And when I use command
`openssl x509 -engine gost -noout -inform pem -text -in /path/to/file.pem -certopt ext_parse`
the result is 
```
[...]
            X509v3 Certificate Policies: 
                Policy: 1.2.643.100.113.1

            1.2.643.100.112: 
    0:d=0  hl=3 l= 181 cons: SEQUENCE          
    3:d=1  hl=2 l=  34 prim:  UTF8STRING        :СКЗИ "Крипто-КОМ 3.3"
   39:d=1  hl=2 l=  30 prim:  UTF8STRING        :ПАК УЦ "Notary-PRO" v.2.7
   71:d=1  hl=2 l=  55 prim:  UTF8STRING        :Заключение № 149/3/2/2-1269 от 21.07.2014
  128:d=1  hl=2 l=  54 prim:  UTF8STRING        :Заключение № 149/7/1/1-921 от 10.11.2014

            1.2.643.100.111: 
    0:d=0  hl=2 l=  48 prim: UTF8STRING        :"Криптотокен" (АЛАДДИН Р.Д.)
[...]
```
So there are correct values inside, but not correctly displayed by default.
As a workaround I can use regexp but this is not a solution.

**Comment by levitte** [comment]
Would you mind sharing such a certificate for testing purposes?

**Comment by Aleksandr-ru** [comment]
Here is official public certificate of CA with the same problem (see 1.2.643.100.111 and  1.2.643.100.112):
https://e-trust.gosuslugi.ru/Shared/DownloadCert?thumbprint=AD83E7E5356918B30EDA69441CC9FCB501F6355C
Certificate in DER format so the problem is reproducible with commands
`openssl x509 -engine gost -noout -inform der -text -in /path/to/file.der`
and
`openssl x509 -engine gost -noout -inform der -text -certopt ext_parse -in /path/to/file.der`

**Comment by richsalz** [comment]
I believe this is a known bug -- the only things we decode/print properly are the DN's, not the extensions.

**Comment by snhenson** [comment]
What's happening is that it is seeing an unknown extension. It attempts to show any printable characters in the raw value without any interpretation: that's what it did by default a very long time ago and that has never been updated. The "ext_parse" option attempts to asn1parse unknown extensions which is arguably a much more sensible default. Can we change that in a stable release branch?

**Comment by kroeckx** [comment]
Is there something related to that "ext_parse" we can enable in
one or more of the fuzzers?

**Comment by snhenson** [comment]
Yes: set the flag `X509V3_EXT_PARSE_UNKNOWN` in `X509_print_ex()` et al.

**Comment by tuchik** [comment]
_

#1. 

_

**Comment by mattcaswell** [comment]
I think this is less a bug and more the lack of a feature. Moving this to post 1.1.1 milestone.

**Comment by t8m** [comment]
Closing as duplicate of #3291
