### ISSUE TITLE
Support for certificate partial wildcard in middle of 

### ISSUE THREAD

**Issue by copelnug** [openssl/openssl#4293]
RFC6125 give some example of wildcard in section 6.4.3 (https://tools.ietf.org/html/rfc6125#section-6.4.3):
1. baz*.example.net should match baz1.example.net
2. *baz.example.net should match foobaz.example.net
3. b*z.example.net should match buzz.example.net

Using OpenSSL X509_check_host(), the first two are OK but the last does not work. 

By looking into the code, It seems to be explicitly disabled as per a comment in valid_start in v3_utl.c

> /* No 'foo*bar' wildcards */

Should it be corrected? Or is there a reason it is not supported?

**Comment by richsalz** [comment]
It's really dangerous -- did you see the errata for that RFC? -- and nobody does it.  We have no plans to support this.

**Comment by copelnug** [comment]
I only see one errata ([#3090](https://www.rfc-editor.org/errata_search.php?rfc=6125)) and it seems to find problem with wildcards in generals and have nothing specific about the b*z.example.net case. Also, I have problem seeing how b*z.example.net would be worse than b*.example.net.

Also, whatever the reason, I think it would be good to at least modify the comment to indicate why foo*bar are not valid.

**Comment by richsalz** [comment]
Do you have a suggestion for wording that would be more helpful?

**Comment by copelnug** [comment]
As I don't see how the errata indicating why b*z.example.net is more problematic than a simple wildcard, I do not have any idea. Is there another errata that I'm not seeing?

**Comment by richsalz** [comment]
Wildcards are risky as the errata shows.  However they are widely used, with "*.foo.bar" as the only form that is in public use, so supporting that is reasonable.  Embedded wildcards are more risky and there is no demand for them.

**Comment by copelnug** [comment]
I agree that wildcards carry some risk, but partial wildcard seems to me less risky than the others. For example, \*.foo.bar match many string more than b\*z.foo.bar

Also, I find strange that b\*.foo.bar and \*z.foo.bar are supported but not b\*z.foo.bar

Finally, there is a flag in OpenSSL to disable partial wildcard that can be used to only accept \*.foo.bar

**Comment by richsalz** [comment]
Not sure what else I can say.  We disagree.

**Comment by R030t1** [comment]
@richsalz Failing to give any explanation at all is a lot different from giving some explanation, however tenuous.

**Comment by frankpinto** [comment]
Agreed, that "explanation" was pretty useless. A careful reading of the only Errata and section 7.2 (plus linked presentations) shows that any issue with 3 above works on case 1 and 2. Sounds like just fear/paranoia + it not being that important compared to other development that's keeping it unimplemented. I agree that use-cases for it are few

**Comment by bmwiedemann** [comment]
https://www.rfc-editor.org/errata_search.php?rfc=6125 writes

> However, the client SHOULD NOT
>       attempt to match a presented identifier where the wildcard
>       character is embedded within an A-label or U-label [IDNA-DEFS] of
>       an internationalized domain name [IDNA-PROTO].

That is indeed an additional complication of matching `b*z.example.com` over `*.example.com`
