### ISSUE TITLE
Raw Ciphers List empty on session reuse

### ISSUE THREAD

**Issue by jeppojeps** [openssl/openssl#4295]
Hello, NGINX is calling the following SSL function to retrieve the client hello ciphers:
SSL_get0_raw_cipherlist()
Every time a session is reused the list is empty so basically the following pointer is empty:
s->s3->tmp.ciphers_raw

Is there another function we have to call to get the ciphers of a reused session or is there indeed an issue?

**Comment by kaduk** [comment]
What version of OpenSSL?  (It looks like ssl_cache_cipherlist() should be getting called in the current master, on a quick read.)
Starting in 1.1.1 you'll have access to the early callback that can access the raw ciphers from the ClientHello directly.

**Comment by jeppojeps** [comment]
Hello, the version is libssl.so.10 - I will try to put some prints here and
there to confirm than. What I can confirm is that there is no manipulation
whatsoever on the data that SSL_get0_raw_cipherlist() returns (in thsi case
0) when the session is reused. I know that because the session_id is set.

Let me give you more info tomorrow.

Thanks,
Antonio

2017-08-30 20:54 GMT+02:00 kaduk <notifications@github.com>:

**Comment by jeppojeps** [comment]
I found the issue, I have 1.0.1e and it does not support raw_ciphers, it uses the SSL_get_shared_ciphers, that is not working properly with session reuse :(

**Comment by kaduk** [comment]
Ah, the shared ciphers would only be computed when negotiation is performed (i.e., not resumption), yes.
Hopefully you can update to a supported version of OpenSSL and pick up the needed funcitonality.
