### ISSUE TITLE
copy-paste bug: crypto\asn1\asn1_gen.c - (!strncmp(vstart, "BITLIST", 3))

### ISSUE THREAD

**Issue by pavel-pimenov** [openssl/openssl#43]
V666 Consider inspecting third argument of the function 'strncmp'. It is possible that the value does not correspond with the length of a string which was passed with the second argument. asn1_gen.c 371

		case ASN1_GEN_FLAG_FORMAT:
		if (!strncmp(vstart, "ASCII", 5))
			arg->format = ASN1_GEN_FORMAT_ASCII;
		else if (!strncmp(vstart, "UTF8", 4))
			arg->format = ASN1_GEN_FORMAT_UTF8;
		else if (!strncmp(vstart, "HEX", 3))
			arg->format = ASN1_GEN_FORMAT_HEX;
		else if (!strncmp(vstart, "BITLIST", 3))
			arg->format = ASN1_GEN_FORMAT_BITLIST;

fix:
if (!strncmp(vstart, "BITLIST", 3)) -> if (!strncmp(vstart, "BITLIST", 7))

**Comment by ghedo** [comment]
This was fixed in 0b142f022e2c5072295e00ebc11c5b707a726d74, so it can be closed.
