### ISSUE TITLE
define sslprotocol for each vhost

### ISSUE THREAD

**Issue by moztabaahmed** [openssl/openssl#4301]
Hello,

I am seriously frustrated because of this openssl bug. There was a bug issue opened long time ago (found on the net), but it was closed without any resolution & was marked as resolved.

However, it's still not resolved. Is there any way I can achieve SSLProtocol settings activation for each vhost?

What I am trying to do is, deactivate tlsv1.0 for 2 vhosts but keep them that specific TLS version active for other vhosts. How can I get that to work?

Best regards.

**Comment by kaduk** [comment]
vhosts sounds like something in a webserver, not the core openssl crypto/ssl library (i.e., you have found the wrong issue tracker).
When you do find the right issue tracker, it's probably polite to include a link to the thing you "found on the net" along with the new bug report.

**Comment by moztabaahmed** [comment]
I am not a programmer, but it seems like a issue with openssl. not apache. I've included the openssl ticket here. Please suggest further. Thanks

Issue: https://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=3183

**Comment by moztabaahmed** [comment]
Apache bug track discussion:

https://bz.apache.org/bugzilla/show_bug.cgi?id=55707

**Comment by richsalz** [comment]
I appreciate your frustration.  But this is an Apache configuration issue, not an openssl issue.
You will be best served by asking that question to Apache.

**Comment by moztabaahmed** [comment]
Hello Rich,

Thank you for your kind reply. I did include a apache bug page. Where I saw this comment,

"Confirmed. It's due to a current limitation in OpenSSL, actually - when we use  SSL_set_SSL_CTX() in the SNI callback in ssl_engine_kernel.c, OpenSSL only switches the certificate, but not any of the other settings.

I have filed

  https://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=3183

meanwhile, and on the mod_ssl side, we are basically stuck with fixing this in a sane way until it's addressed in OpenSSL. If you're compiling against OpenSSL before 1.0.0, you could apply this patch, in theory (but note that this fiddles with OpenSSL internals, and is not the way forward to fix the issue):

--- ssl_engine_kernel.c (revision 1546692)
+++ ssl_engine_kernel.c (working copy)
@@ -2014,6 +2014,7 @@ static int ssl_find_vhost(void *servername, conn_r
             SSL_set_verify(ssl, SSL_CTX_get_verify_mode(ctx),
                            SSL_CTX_get_verify_callback(ctx));
         }
+        SSL_set_ssl_method(ssl, ctx->method);

         /*
          * Adjust the session id context. ssl_init_ssl_connection()"

I am not sure if the problem that guy mentioned is fixed in the newer version. Right now I'm using openssl 1.0.1e-60.el7_3.1. I will open a ticket to Apache. But before that, I want to make sure that the old issue mentioned is fixed.

Thank you :)

**Comment by richsalz** [comment]
1.0.0 and 1.0.1 aren't no longer supported.  I believe that using the early-callback in master you can do what you want; not sure about 1.0.2 or 1.1.0  But it seems to me a separate SSL_CTX for each vhost is really the best way to go.

**Comment by moztabaahmed** [comment]
richsalz,

I manually compiled both 1.0.2 and 1.1.0 today. But the issue still persists :(

How do I seperate SSL_CTZ for each vhost? I've tried everything, all latest version softwares. nothing works :(.

Please suggest.

Thank you

**Comment by richsalz** [comment]
It is not an OpenSSL issue.  It is the way Apache uses OpenSSL.  Sorry we cannot help you more.

**Comment by kaduk** [comment]
To expound a bit more, the relationship between vhost and SSL_CTX is something entirely internal to Apache, over which OpenSSL has essentially no control.  (All we can do is in terms of what is allowed/disallowed by the APIs we expose.)
It seems like perhaps the core issue here is that SNI processing (where SSL_CTXs are commonly switched to map to a different vhost) is performed after TLS version negotiation, so even though the SSL_CTX can be changed, the TLS version has already been decided.  Rich alluded to this by mentioning the early callback (new in OpenSSL 1.1.1, not yet released), which allows the application to switch SSL_CTXes *before* TLS version negotiation.  But if this ordering between TLS version negotiation and SSL_CTX switching is in fact the key matter, there is simply nothing to be done until OpenSSL 1.1.1 is available -- chanigng the ordering of SNI processing and TLS version negotiation is a major undertaking that presents far too much risk to attempt in a stable release branch.
