### ISSUE TITLE
Tests failing in msys2/mingw builds

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#4306]
Multiple tests are failing on the master branch in msys2/mingw (32-bit and 64-bit). #4305 addresses some issues. However many other failures seem to be due the interpretation of the perl variable $^X. On Linux I get this:

````
$ perl -e 'print $^X'
/usr/bin/perl
````

On Windows ActiveState Perl I get this:

````
c:\Users\Matt\Source\Repos\openssl>perl -e "print $^X"
C:\Perl64\bin\perl.exe
````

But in Msys2 I get:

````
$ perl -e 'print "$^X\n"'
perl
````

This causes a problem in the `perlapp` and `perltest` functions in Test.pm which both have a line like this:

````
        my @interpreter = __fixup_prg($^X);
````

and the function `__fixup_prg` does this:

````
    # We test if the program to use exists.
    if ( ! -x $prog ) {
	$prog = undef;
    }
````

This test fails on msys2 (but manually passing in "/usr/bin/perl" instead of "perl" succeeds). Commenting out the above existence check causes the tests to pass - but it is not clear that that is the best solution.

Ping @levitte.

**Comment by levitte** [comment]
Hmmm, would you mind trying this, to see if it gives better results?

```
$ perl -MConfig -e 'print $Config{perlpath}'
```

**Comment by levitte** [comment]
On the other hand, come to think of it, `__fixup_prg` doesn't really have any business checking the existence of the program.  If program doesn't exist, it will fail to execute anyway, so removing that check may be the smoothest solution.
