### ISSUE TITLE
no-ripemd switch forgets to exclude the symbols from the def

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#431]
error LNK2001: unresolved external symbol RIPEMD160
Problem is in libeay.num
>RIPEMD160_Init                          1042	EXIST::FUNCTION:
RIPEMD160_Update                        1043	EXIST::FUNCTION:
RIPEMD160_Final                         1044	EXIST::FUNCTION:
RIPEMD160                               1045	EXIST::FUNCTION:
RIPEMD160_Transform                     1046	EXIST::FUNCTION:

function should not be exported if no-ripemd is set

**Comment by ghedo** [comment]
@mattcaswell this can be closed as well now.
