### ISSUE TITLE
90-test_store.t fails on MSYS2/mingw

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#4314]
The above test is failing on msys2/mingw with lots of errors like this:

````
Couldn't open file or uri file;C:\msys64\home\Matt\openssl\test\certs
1972:error:02016002:system library:stat:No such file or directory:crypto/store/loader_file.c:812:file;C:\msys64\home\Matt\openssl\test\certs
1972:error:2C064069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:crypto/store/store_register.c:217:scheme=file;C
../../util/shlib_wrap.sh ../../apps/openssl.exe storeutl 'file:/home/Matt/openssl/test/certs' => 1
not ok 194
````

Sure enough trying that command from the msys2 command line I get much the same result. The reason is due to msys2 file mangling. The Msys2 shell converts things it thinks are UNIX style filenames into native filenames before passing them to the application. Running this command from the command line succeeds:

````
$ MSYS2_ARG_CONV_EXCL="*" ../util/shlib_wrap.sh ./openssl storeutl 'file:/c:/msys64/home/Matt/openssl/test/certs'
````

The problem here is that it requires knowledge of the msys install location, i.e. "c:/msys64/". Not sure how to get that.

Thoughts @levitte?

**Comment by levitte** [comment]
No thoughts so far, but am willing to make a test of my own...  I'm not aware of this file mangling stuff, do you have a quick pointer to reference documentation on it?

**Comment by mattcaswell** [comment]
Unfortunately not, I've not managed to find a good reference on it. Google has various references but nothing definitive that I can find.

**Comment by levitte** [comment]
Found some here:

http://www.mingw.org/wiki/Posix_path_conversion

This is frustrating...

**Comment by levitte** [comment]
I think that the cleanest we can do is to avoid the tests if file: URIs without the authority part when testing in mingw.  I'm currently checking if cygwin has the same issue

**Comment by turboj** [comment]
Current openssl (1.1.0g) tests work on MSYS2 with

`MSYS2_ARG_CONV_EXCL="file" make test`

This solves a path conversion error in the _pem tests. Note that some other tests actually need the path conversion of MSYS2, so ` MSYS2_ARG_CONV_EXCL="*" ` is too much.
