### ISSUE TITLE
celeron J1900 CPU run openssl-1.0.1e-42.el6_7.4.x86_64  trap invalid opcode

### ISSUE THREAD

**Issue by magic-bag** [openssl/openssl#4315]
run my app, dmesg is trap invalid opcode ip:XX sp:xx ERROR:0 in libcrypto.so.1.0.1e

**Comment by richsalz** [comment]
I'm sorry, but we can't help you, for a couple of reasons.  First, 1.0.1 is no longer supported by the OpenSSL project (but some vendors may be supporting it; consider contacting your supplier). Second, you gave us not enough information to reproduce the problem, not even saying what the app is, or what the backtrace is.  Sorry.
