### ISSUE TITLE
my CPU not support AES-Ni, how can I close this phy function in openssl?

### ISSUE THREAD

**Issue by magic-bag** [openssl/openssl#4329]
my CPU is Celeron J1900, not support AES-ni . when I run my app, gdb message is "received signal SIGILL" in aesni_encrypt_key () from /usr/lib64/libcrypto.so.

**Comment by richsalz** [comment]
OpenSSL checks at runtime to see if the instruction is there.  You can also set the PCAP environment variable, see the manpage.
