### ISSUE TITLE
Application is getting killed after BIO_FLUSH() function in linux based system

### ISSUE THREAD

**Issue by Apoorvahraju** [openssl/openssl#4330]
Hi all,

I am using OpenSSL version 0.9.8o 01 June 2010  in my application (written in C++ ). Platform is linux.
After BIO_FLUSH() the application is getting killed. What may be the reason for this ? How can i debug the problem. please help.

Thank you,
Apoorva

**Comment by mattcaswell** [comment]
Sorry, we no longer support 0.9.8. Please upgrade to a more recent version.

**Comment by Apoorvahraju** [comment]
Hi ,

Already this application is in use and we can't upgrade to recent SSL.
Can you please suggest me with any reference links or similar kind of issues. So that i can look into it and found out what is making application to kill.

Thank you,
Apoorva
