### ISSUE TITLE
Insecure openssl_fopen

### ISSUE THREAD

**Issue by icebreaker2** [openssl/openssl#4334]
I am using the OpenSSL API for a project I am working on. I ran flawfinder against my implementations to detect security flaws. One of them was an unprotected usage of ``fopen``. I use this function for AES key storage. For other crypto keys like ECC, RSA, etc. I use the OpenSSL ``PEM_write``-methods with BIO. 

In short: I protected and tested my ``fopen`` usage against race conditions and was curious whether the OpenSSL methods were vulnerable, too. I could not create a reliable test case for the OpenSSL methods therefore I followed the stacktrace.

Heres the method used to create a new ``FILE`` stream for ECC, RSA, etc.:

```c/c++
BIO *BIO_new_file(const char *filename, const char *mode)
{
    BIO  *ret;
    FILE *file = openssl_fopen(filename, mode);
...
```
Tracing ``openssl_fopen`` leads to an unprotected call of ``fopen``
```c/c++
FILE *openssl_fopen(const char *filename, const char *mode)
{
    FILE *file = NULL;
...
        if (MultiByteToWideChar(CP_UTF8, flags,
                                filename, len_0, wfilename, sz) &&
            MultiByteToWideChar(CP_UTF8, 0, mode, strlen(mode) + 1,
                                wmode, OSSL_NELEM(wmode)) &&
            (file = _wfopen(wfilename, wmode)) == NULL &&
            (errno == ENOENT || errno == EBADF)
            ) {
            /*
             * UTF-8 decode succeeded, but no file, filename
             * could still have been locale-ized...
             */
            file = fopen(filename, mode);
}
```

Am I missing some security measures taken? 

I cannot share my implementation, sorry for that. But I mainly used ``unlink()`` with ``open(fileName, O_WRONLY | O_CREAT | O_EXCL, FILE_MODE)``.

I pass the file stream manually into BIO using ``BIO_set_fp`` now.

**Comment by levitte** [comment]
This is obviously on Windows, right?  I just read up, and it seems that `fopen_s` is prefered there...  not that I quite understand how that's more secure, but I'm guessing that's not what you're asking for either.

I noticed the `open` line you gave there, with `O_EXCL` among others, and unless I'm mistaken, `fopen` doesn't do exclusivity, so I'm going to assume that's what you're actually asking for.

You may not know that there is a BIO source/sink that deals with file descriptors...  the thing with that one is that *you* must create the file descriptor yourself.  This is an example code how to do it (untested and unchecked):

``` C
    int fd = open ("whatever.pem", O_WRONLY | O_CREATE | O_EXCL, 0700);
    BIO *bio = fd >= 0 ? BIO_new_fd(fd, 1) ? NULL;
```

The resulting BIO, if non-NULL, can then be used with whatever OpenSSL functions you want to use it with.  BIO_free() will close the file for you.

If this is satisfactory answer, please close this issue.

**Comment by richsalz** [comment]
I would also like to know what "unprotected use of fopen" is.

**Comment by icebreaker2** [comment]
@levitte Thanks for your detailed answer. Currently I create file descriptors and use ``fdopen`` to pass a file stream into BIO (as described above) iff ``open`` returns a non-negative value which it does if one file has been created in the meantime. It seems to be one step done additionally by myself -- I will change it to your example.

@richsalz I meant an unprotected usage against race conditions. I assumed if using ``BIO *BIO_new_file`` was not secured against it the docs would mention it. But I have taken a closer look into it and (at least in my application) there is no way that it could harm execution if tested for a null return. So never mind.
