### ISSUE TITLE
HMAC_MAX_MD_CBLOCK is too small for SHA-3

### ISSUE THREAD

**Issue by fxdupont** [openssl/openssl#4335]
SHA3_224 uses a 144 octet block size when HMAC_MAX_MD_CBLOCK is defined to be 128 in include/openssl/hmac.h so:
        j = EVP_MD_block_size(md);
        if (!ossl_assert(j <= (int)sizeof(ctx->key)))
            goto err;
from HMAC_Init_ex() (crypto/hmac/hmac.c) always fails (i.e. returning 0).

The fix (for master or any branch which has crypto/evp/m_sha3.c file) is to update:
# define HMAC_MAX_MD_CBLOCK      128/* largest known is SHA512 */
changing for instance 128 by 200 (and SHA512 by Keccak).

**Comment by snhenson** [comment]
This isn't as straight forward as just changing the header file. There are binary compatibility issues involved too.

**Comment by fxdupont** [comment]
HMAC_MAX_MD_CBLOCK is used only in hmac_lcl.h (private header file to hmac.c) and hmac.c so in theory it is enough to recompile hmac.c...

**Comment by snhenson** [comment]
Only used by OpenSSL yes. However I'm considering what the effect would be on an application which uses HMAC_MAX_MD_CBLOCK with the old headers.

**Comment by fxdupont** [comment]
Discussion was moved to PR #4338.
