### ISSUE TITLE
OpenSSL BIO Library in Linux

### ISSUE THREAD

**Issue by Apoorvahraju** [openssl/openssl#4343]
Hi,

Would like to know whether  BIO functions are thread safe? or not.

I have some questions. Where I can post my queries regarding OpenSSL ?

Thanks,
Apoorva

**Comment by mattcaswell** [comment]
The openssl-users email list is a good place for questions (https://mta.openssl.org/mailman/listinfo/openssl-users).

The BIO functions themselves are thread safe as long as you do not share a single BIO object across multiple threads.

If you are using OpenSSL 1.0.2 then you also need to set up the locking callbacks (https://www.openssl.org/docs/man1.0.2/crypto/threads.html). This is not necessary in OpenSSL 1.1.0.
