### ISSUE TITLE
CMake support revisited

### ISSUE THREAD

**Issue by rcdailey** [openssl/openssl#4345]
Doing a simple search for 'cmake' in the issues tab reveals 2 closed issues from 2015, where CMake was refused as an idea due to "portability issues" (not sure what this means since CMake is already portable). However, 2 years later I think it would be nice to revisit this.

Note that as a bare minimum, I don't expect CMake to *replace* the current build system, but at the very least provide it as an alternative to make/configure, which are not portable to Windows very easily. Lots of projects have CMake support so I think it's worth it. I realize that this adds maintainability overhead since it isn't replacing the current build system.

There are plenty of CMake scripts out there that support this, such as: https://github.com/guusw/OpenSSL-CMake/blob/master/CMakeLists.txt

I am happy to help contribute this if you accept this idea. Furthermore I'd be willing to help enhance it if needed. Thoughts?

**Comment by richsalz** [comment]
If it's already out there and supported by other repo's perhaps we could add a FAQ entry.  Are you willing to write one?

**Comment by rcdailey** [comment]
I'm willing to help in any way I can, of course. Could you explain a bit more about this FAQ entry? What is the expectation you have?

**Comment by richsalz** [comment]
Look at the frequently asked question on the website, https://www.openssl.org/docs/faq.html and draft something that points to the other repo.  Or perhaps someone on the dev team with an interest in cmake will actually take it on.  But I'm doubtful :)

**Comment by levitte** [comment]
I'm not sure how that current (1.1.0 and on) build system isn't portable to Windows, considering we do use on Windows just as easily as on Unix...

Regarding the portability issues, the main one is that CMake hasn't been ported to VMS...  or anything that isn't Unix or Windows, basically.

Note that there's nothing stopping you from producing a CMake based port.  I suggest making sure that it interfaces well with the build system, at the very least the `build.info` files, or someone will have to keep track of changes and make sure the CMake files are kept in sync.  I did that for the VMS building scripts we had in versions prior to 1.1.0, and I can only tell you that was *very* annoying in the long run.

**Comment by rcdailey** [comment]
I'm not sure what VMS is, but is cross compiling an option? Also @richsalz, you haven't really answered my question (or perhaps I'm not asking it well): What exactly is the FAQ entry supposed to be about?

**Comment by levitte** [comment]
VMS is an operating system, a bit different from Unix and Windows.  Cross compiling is currently not an option (not sure it will ever be).

**Comment by richsalz** [comment]
Q: Can I use CMake to build OpenSSL
A: Not directly, but you can find it here...  note that you might have to ...

**Comment by mattcaswell** [comment]
I'm not really sure I understand what the supposed advantage of CMake is an OpenSSL context. The only benefits I could get from the issue description was that:

1) It's more portable to Windows than make/configure. But we already have a perfectly good build system on windows that enables builds using either VisualStudio or MSYS2/make. Not sure why we would want to add a third option.

2) Lots of other projects are using it. But - so what? - this doesn't seem a great reason in itself for us to use it too.

If we choose to integrate CMake as a build option then we have to maintain it, and regularly test that it is still working which is a considerable overhead. We already have a significant number of travis/appveyor jobs. Adding more will slow down the feedback loop when raising PRs for us to be able to say the CIs are "green".

**Comment by rcdailey** [comment]
@levitte 

> I'm not sure how that current (1.1.0 and on) build system isn't portable to Windows, considering we do use on Windows just as easily as on Unix...

This isn't easy on Windows like it is on linux. Windows has no package managers for native libs for starters. Also we do not have "make" (our closest is nmake provided by Visual Studio), and IIRC I think Perl was required too, not sure if it still is though). There's a lot of setup needed. Things get even more complex when we need to cross compile for Android NDK from a windows OS. This is trivial in CMake since the NDK already provides a CMake toolchain that we already use since our main projects use CMake as well.

**Comment by mattcaswell** [comment]
> Windows has no package managers for native libs for starters

I don't see how CMake helps here.

> we do not have "make" (our closest is nmake provided by Visual Studio)

And we support nmake. If you don't already have nmake your going to need to install *some* kind of toolchain whether that be CMake or something else. This doesn't seem like a reason for us to add more options than we already have.

> IIRC I think Perl was required too

Perl is still required and that's not going away whether you use CMake or not.

**Comment by rcdailey** [comment]
@mattcaswell 

Benefits as I see them:

* Consistent build methods (instructions) across platforms (windows v linux v mac is the same). Despite what you are saying, instructions are distinctly different on each platform (simple example: Windows does not have configure, and requires installing several third party dependencies to be able to build, versus just one (CMake in this case)). Note that I'm stating my experiences more than pure facts (I can't do the latter very well since you are more knowledgeable on the project than I am)
* More flexibility on choice of toolchains to build and/or work with the code (I can choose make, nmake, ninja, Visual Studio, xcode, Eclipse, etc).
* Much easier ability to cross compile (CMake is designed to simplify this). The main use case for this in my situation is Android NDK (cross compiling using a host OS of both Linux and Windows)

I am not sure the long term maintenance of CMake would be as huge as you seem to make it out to be. Sure, the initial overhead is large because you have to get CMake working initially, but once you do the most common changes are likely to be things like:

* Adding/removing source files
* Modifying compile parameters like preprocessor definitions, flags, etc

In these cases, those are 1 line code changes that take less than 30 seconds if you set up the CMake scripts right. Now the complexity of the CI build systems I can't speak to, but what you say does seem to make sense, but IMHO the value outweighs the cost of that.

**Comment by levitte** [comment]
> simple example: Windows does not have configure

Errrr, say what?

**Comment by rcdailey** [comment]
To be completely honest, if I didn't have to build this for Android NDK, I wouldn't feel so strongly about it. But it is seriously a pain in the rear to cross compile OpenSSL (or *any* library using make/configure for that matter), especially on Windows. I've had very little success with this. Boost is another one that's extremely painful.

The best experience I've ever had with cross compiling is CMake.

If all I needed to do was build on Windows, then I'd just use CMake's `ExternalProject_Add()` to do the `configure` and `nmake` steps and call it done without bothering you guys.

@levitte 

>> simple example: Windows does not have configure
>
> Errrr, say what?

The point I'm trying to make: Windows *doesn't* have it working out of the box like Ubuntu (you run apt-get to grab some basic packages and done). You have to sometimes use cygwin/mingw, or install perl to do that stuff. It's not a drop-in solution like Linux.

**Comment by levitte** [comment]
> The point I'm trying to make: Windows *doesn't* have it working out of the box like Ubuntu (you run apt-get to grab some basic packages and done). You have to sometimes use cygwin/mingw, or install perl to do that stuff. It's not a drop-in solution like Linux.

So at a minimum, you have to install perl, or you have to install CMake.  The rest are dependencies that are needed anyway.

What I mostly hear is that the Android cross build is annoyingly difficult.  I haven't done much of that, haven't tried it myself.  The other choice could be to help us make that support better.  You seem very set on CMake, though, so I'm not terribly hopeful in that regard...

**Comment by mattcaswell** [comment]
> Consistent build methods (instructions) across platforms (windows v linux v mac is the same)

1.1.0 introduced unified build for all our platforms. The build instructions are the same across all platforms. There are some platform specific notes (e.g. around perl versions and nasm etc) - but those aren't going away by using CMake (unless you're suggesting we install those automatically via CMake - which seems like a really bad idea).

> simple example: Windows does not have configure

This makes no sense. Are you referring to OpenSSL Configure (a perl script) which works perfectly well on Windows, or autotools "configure" which OpenSSL doesn't use?

> More flexibility on choice of toolchains to build and/or work with the code

You can already use VisualStudio/nmake or MSYS2/make. Adding more options is not necessarily a good thing. It just adds to the "matrix" of platforms we have to support and check that they work on a regular basis.

>  once you do the most common changes are likely to be things like:
Adding/removing source files
Modifying compile parameters like preprocessor definitions, flags, etc
In these cases, those are 1 line code changes that take less than 30 seconds if you set up the CMake scripts right.

This is what we had before in the 1.0.2 build system (i.e. a Unix build system and a separate Windows build system), and I can tell you from bitter experience that it was a major PIA. There is no way we are going back to that!

**Comment by rcdailey** [comment]
Ok so this has been helpful for me. If I understand correctly, I am complaining about the old build method which was difficult for me to use. If version 1.1 introduced something different I will learn more about that.

My fixation is less about CMake (even though, yes, I *really do* like it because it has proven usefulness), but more about making OpenSSL easy to build (especially for the cross compilation for Android NDK use case).

I won't argue for CMake anymore, we've all made our points. I'll close this for now. My main goal was just to check up on everyone's feelings about this, and I accomplished that. Thanks again to everyone's quick responses and helpful feedback. I'll check out the build instructions for v1.1 and see if things are better. If I have issues cross compiling I'll let you know!

**Comment by richsalz** [comment]
Just wanted to thank you for starting and contributing to a useful discussion.

**Comment by ForwardXu** [comment]
I really think it's necessary to support CMake for cross compile.

**Comment by qis** [comment]
@rcdailey Wouldn't it make sense to re-open this issue until CMake support is added?

It's useful for more organized build environments, where CMake toolchain files are used to set specific compiler flags that are used for everything, including building dependencies.

Right now, I have to painstakingly synchronize everything.

Another benefit is support for previously unsupported toolsets, like `clang` (*not* `clang-cl`) on Windows.

**Comment by rcdailey** [comment]
I completely agree but it's ultimately up to the developers of the project. I closed it not because I do not feel CMake should be used, but because they are strongly against it. If they will not spend time on it or maintain it, then why should we leave it open?

Having said that, I completely agree that CMake support is superior to what they are using and I personally prefer it. It's been two years so I'll let them chime in to see if opinions have changed in 2 years.

**Comment by levitte** [comment]
I personally revisit this and learn more about about cmake a little now and then. I must confess that I do like it, where it's available. Unfortunately, there are drawbacks: 1) for building cmake, C++11 is required, which isn't available everywhere, 2) I find it notoriously difficult to write new generators for systems that aren't supported by cmake today.

**Comment by qis** [comment]
Yeah, but let them decide if it should be closed or left open so that people can find it more easily.

**Comment by mspncp** [comment]
> Yeah, but let them decide if it should be closed or left open so that people can find it more easily.

I don't think you need to worry about closed issues being more difficult to find. Here is what GitHub's new 'related issues' (beta) feature shows when I enter 'cmake' in the subject line of the 'new issue' dialog:

![image](https://user-images.githubusercontent.com/11467854/67143373-1fc5f400-f26b-11e9-83aa-6eb6b17f3eeb.png)

On the issue search page, all people need to do is to remove the "is:open" filter:

- [is:issue cmake](https://github.com/openssl/openssl/issues?utf8=%E2%9C%93&q=is%3Aissue+cmake)
- [is:issue in:title cmake](https://github.com/openssl/openssl/issues?utf8=%E2%9C%93&q=is%3Aissue+in%3Atitle+cmake)

Or they can use Google search syntax:

- [cmake site:github.com/openssl/openssl](https://www.google.com/search?q=cmake+site%3Agithub.com%2Fopenssl%2Fopenssl)

**Comment by qis** [comment]
@mspncp Guess how I came here! And you are way too optimistic if you think people will do that instead of clicking on `Issues`, searching for `cmake`, then cursing and searching for a sub-par third party solution.
