### ISSUE TITLE
Calling EVP_CipherInit() with a null cipher, after a previous call setting the cipher, clears the cipher

### ISSUE THREAD

**Issue by guyharris** [openssl/openssl#4347]
The OpenSSL 0.9.6 documentation says:

> EVP_CIPHER_asn1_to_param() sets the cipher parameters based on an ASN1 AlgorithmIdentifier "parameter". The precise effect depends on the cipher. In the case of RC2, for example, it will set the IV and effective key length. This function should be called after the base cipher type is set but before the key is set. For example EVP_CipherInit() will be called with the IV and key set to NULL, EVP_CIPHER_asn1_to_param() will be called and finally EVP_CipherInit() again with all parameters except the key set to NULL. It is possible for this function to fail if the cipher does not have any ASN1 support or the parameters cannot be set (for example the RC2 effective key length is not supported.

which indicates that you can call `EVP_CipherInit()` on a context to set the cipher, but not set other parameters, and subsequently call `EVP_CipherInit()` again, with the cipher null, and with other parameters supplied.

This works in OpenSSL 1.0.x as well.

However, change c0ca39bdd6048c77901f821ba0d2eeaa9341f7af broke this in OpenSSL 1.1.x; now the second call to `EVP_CipherInit()` will clear the cipher, setting the cipher pointer to NULL, rendering the context unusable - a crash will occur on any call that attempts to dereference the context's cipher pointer.

This caused tcpdump, when using OpenSSL 1.1.x, to crash if the user tried to decrypt ESP traffic, as it was using the multiple-calls-to-`EVP_CipherInit()` idiom.

That idiom works with `EVP_CipherInit_ex()`, so we changed tcpdump to use `EVP_CipherInit_ex()` if it's available.  However, other programs and libraries still using `EVP_CipherInit()` may be subject to crashes if they use that idiom.

**Comment by mattcaswell** [comment]
This was fixed by #4613. Closing.
