### ISSUE TITLE
Makefile(238) : fatal error U1001: syntax error : illegal character '{' in macro

### ISSUE THREAD

**Issue by tejas3** [openssl/openssl#4352]
Facing issue while running nmake to build openssl

**Comment by levitte** [comment]
What openssl version, or if you're building from a git clone, what's your branch and top commit?

**Comment by tejas3** [comment]
Hello,

Yes, downloaded from: (https://github.com/openssl/openssl.git) clone.
Branch is Master
 yes it is top commit.

Kindly revert if you need further details.

Thanks & Regards,
Tejas

**Comment by levitte** [comment]
Ok good.  Next thing, can you tell me what the configuration command was?  You know, the command starting with `perl Configure`...  I'm interested in the exact command line you used.

**Comment by tejas3** [comment]
Hi,

Yes,
first command was: perl Configure
second command was: nmake

And I got error mentioned in subject.

Thanks & Regards,
Tejas

**Comment by levitte** [comment]
Surely, there were some arguments after `perl Configure`?  I need the *full* command

**Comment by tejas3** [comment]
Hi Richard,

I wanted to build it for win32 platform only.
So first time I used perl Configure {VC-WIN32 } but I got message on
command line : "target already defined - { (offending arg: VC-WIN32)"
So I simply fired "perl Configure" command. And it was successful.

Issue in "nmake" command.

Regards,
Tejas

**Comment by levitte** [comment]
I certainly doubt that running `perl Configure` was successful without any argument at all.  However, the first command was slightly wrong as well, so try this instead:

```
perl Configure VC-WIN32
```

(i.e. no braces)
... and then nmake.

**Comment by tejas3** [comment]
Hi Richard,

PFA.


Regards,
Tejas

**Comment by levitte** [comment]
I assume that means Pretty F*ng Awesome, and that we can close this case?

(PFA can also mean Please Find Attached)

**Comment by tejas3** [comment]
Hi Richard,

No, still issue is there when I do "nmake". You can see error at the bottom
of screenshot.

-Tejas

**Comment by levitte** [comment]
Ah...  in that case, you forgot to attach the screenshot.

**Comment by tejas3** [comment]
Hi Richard,

Please refer previous screen shot. See at the bottom.

Tejas

**Comment by levitte** [comment]
I misunderstand.  Please resend the screenshot

**Comment by tejas3** [comment]
Sorry Richard for misunderstanding. :-(

PFA.
see fatal error at the bottom of screen shot.

-Tejas

**Comment by levitte** [comment]
Ok...  it seems that your attachment gets lost over mail, because I'm still not getting a screenshot.
Please log in on github and use the web interface instead.

**Comment by tejas3** [comment]
<img width="426" alt="opensslcmd" src="https://user-images.githubusercontent.com/13366362/30248446-a812810e-9645-11e7-9f40-5c94032a7cd9.png">

**Comment by levitte** [comment]
Thanks!  And I think you've made a mistake, because that seems to be OpenSSL 1.0.1c, and that version builds in a distinctly different way.  I think you'll find a document called `INSTALL.W32` there, and you should do as it says...

... but most of all, version 1.0.1c is oooold and unsupported, please download something current (currently supported versions are 1.0.2, 1.1.0 and the master branch).

Since this is an unsupported version, I'm closing this issue.

**Comment by tejas3** [comment]
Thanks alot. :-)

**Comment by jalalMohammad511** [comment]
i am seeing this issue as well. i am using 1.0.2

![image](https://user-images.githubusercontent.com/54873532/64219274-b2f0c900-ce79-11e9-82f4-7049c57ee00d.png)

**Comment by uidn0158** [comment]
> i am seeing this issue as well. i am using 1.0.2
> 
> ![image](https://user-images.githubusercontent.com/54873532/64219274-b2f0c900-ce79-11e9-82f4-7049c57ee00d.png)

Hello Jalal,

Did you find the method to fix this issue? I am building GmSSL, and find the same error as yours.
Thanks.

Tim

**Comment by QuentinGouchet** [comment]
I have had the same error and it seems that it was my fault. Try:
nmake -f ms\ntdll.mak
instead of just nmake

**Comment by mdeihly** [comment]
> I have had the same error and it seems that it was my fault. Try: nmake -f ms\ntdll.mak instead of just nmake

Hi, I got this error after calling **nmake -f ms\ntdll.mak**. Did you get it as well? Thanks
![image](https://user-images.githubusercontent.com/41584417/196700964-6cc4da0d-400b-4826-87fc-c35488c8a2e1.png)
