### ISSUE TITLE
Support: direct assignment of public key to (CSR) X509_REQ required!

### ISSUE THREAD

**Issue by tejas3** [openssl/openssl#4360]
In current situation openssl needs Private key to set public key in CSR request creation, there are some scenario when we get only public key from server and needs to create CSR X509_REQ!

**Comment by richsalz** [comment]
You cannot create an X.509 certificate request with a public key.  The whole point of the data structure is to prove "proof of posession" of the private key.  If the server is sending the client a public key that it expects the client to use, then it must also send the client the matching private key.

Perhaps you are using the data structure in a way that's not intended, or perhaps you can explain it some more?  Based on what you wrote so far, this would be closed.

**Comment by tejas3** [comment]
Hello,

I got public key in EC_POINT type, so I have converted EC_POINT to EVP_KEY type and then attached to X509_REQ_set_pubkey(...).

So closing this issue.
