### ISSUE TITLE
no-dh no-ec doesn't build

### ISSUE THREAD

**Issue by benlaurie** [openssl/openssl#4365]
ssl/statem/statem_clnt.c:1618:52: error: no member named 'pkey' in 'struct ssl3_state_st::(anonymous at ssl/statem/../ssl_locl.h:1408:5)'
    if (s->ext.tls13_cookie_len == 0 && s->s3->tmp.pkey != NULL) {

**Comment by kaduk** [comment]
Addressed via #4369
