### ISSUE TITLE
x509: Bad format "engine" must be PEM or DER  CSR; (Certificate Signing Request) using openssl

### ISSUE THREAD

**Issue by swati025** [openssl/openssl#4366]
I have been trying to sign CSR using Yubikey 4+U2F+CCID  with the following command:
openssl x509 -engine pkcs11 -req -days 3650 -CAform PEM -CA My-mfg-ca.crt -CAkeyform engine -CAkey "pkcs11:pin-value=123456" -CAcreateserial -in hsm-challenge.csr -out hsm-challenge.crt

I have attached picture of errors i am getting.
<img width="235" alt="opensslforum" src="https://user-images.githubusercontent.com/23661778/30425159-e2bdd506-9965-11e7-8b0f-fe9b8bd7823a.PNG">

Below is my openssl configuration file 
<img width="525" alt="opensslcfgforengine" src="https://user-images.githubusercontent.com/23661778/30425216-1318f29e-9966-11e7-992d-df4196894e98.PNG">

With my yubikey having default values of PIN and Management keys and blocked PUK
I have imported My-mfg-ca.pfx in yubikey also provided My-mfg-ca.crt as a file.

**Comment by djm300** [comment]
Same issue noted here

**Comment by levitte** [comment]
That's because the `-CAkeyform` argument for `openssl x509` doesn't handle engine backed keys, only PEM and raw DER files.

I'll consider this a feature request

**Comment by Jajcus** [comment]
But this used to work properly — just google '"cakeyform engine"' for examples. So it is a regression, not a feature request. A serious regression, because having CA key on a PKCS#11 token is quite an important use case.

**Comment by levitte** [comment]
You know, you're quite correct!  I was stoopidly looking at -CAform :-/

**Comment by levitte** [comment]
#4643 should fix it.

**Comment by Jajcus** [comment]
Thanks!

**Comment by swati025** [comment]
[openssl.cfg.txt](https://github.com/openssl/openssl/files/1460709/openssl.cfg.txt)
I am Sorry for not discussing this issue before, actually i resolved that just after two days when i posted it.
But what is making me write here is, I just changed the sequence in which i wrote the engine configuration in openssl.cfg.
I am attaching the configuration file which worked for me for openssl version 1.0.2l.

.

**Comment by levitte** [comment]
The config file was never the issue here...  I'm glad, though, that you found a way around the issue.
