### ISSUE TITLE
ECDH benign malleability

### ISSUE THREAD

**Issue by ofek** [openssl/openssl#4370]
This is in reference to my findings in [https://github.com/ofek/coincurve/issues/9](https://github.com/ofek/coincurve/issues/9). Basically, since there are two points that correspond to every x value, a shared secret is not a 1:1 mapping of public keys given a specific secret key.

This is documented as a potential vulnerability in [SEC 1 v2.0](http://www.secg.org/sec1-v2.pdf) section B.4.1 attack no. 8.

We should add a note about this for our users. Also, perhaps we could eventually add a non-malleable version.

[https://github.com/bitcoin-core/secp256k1](https://github.com/bitcoin-core/secp256k1) does this by returning a sha256 of the compressed point, i.e. `sha256([02|03]|x)`.

**Comment by kaduk** [comment]
Add a note ... where exactly?
This report seems like it could benefit from a bit more context.

**Comment by bernd-edlinger** [comment]
I think he wants to use the y-coordinate of the secret point.
That could be computed using low level APIs of course.
But I am not sure if that adds much security.

**Comment by mattcaswell** [comment]
It's not clear that we need to do anything here. If the reporter provides a concrete PR then we will look at it.
