### ISSUE TITLE
Openssl Failed 40-test_rehash

### ISSUE THREAD

**Issue by stevenzhu25** [openssl/openssl#4387]
```
[root@las4 openssl-1.1.0f]# make test
make depend && make _tests
make[1]: Entering directory `/root/openssl-1.1.0f'
make[1]: Leaving directory `/root/openssl-1.1.0f'
make[1]: Entering directory `/root/openssl-1.1.0f'
( cd test; \
  SRCTOP=../. \
  BLDTOP=../. \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=.././engines \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl  )
../test/recipes/01-test_abort.t ............ ok   
../test/recipes/01-test_sanity.t ........... ok   
../test/recipes/01-test_symbol_presence.t .. ok   
../test/recipes/02-test_ordinals.t ......... ok   
../test/recipes/03-test_exdata.t ........... ok   
../test/recipes/03-test_ui.t ............... ok   
../test/recipes/04-test_pem.t .............. ok     
../test/recipes/05-test_bf.t ............... ok   
../test/recipes/05-test_cast.t ............. ok   
../test/recipes/05-test_des.t .............. ok   
../test/recipes/05-test_hmac.t ............. ok   
../test/recipes/05-test_idea.t ............. ok   
../test/recipes/05-test_md2.t .............. skipped: md2 is not supported by this OpenSSL build
../test/recipes/05-test_md4.t .............. ok   
../test/recipes/05-test_md5.t .............. ok   
../test/recipes/05-test_mdc2.t ............. ok   
../test/recipes/05-test_rand.t ............. ok   
../test/recipes/05-test_rc2.t .............. ok   
../test/recipes/05-test_rc4.t .............. ok   
../test/recipes/05-test_rc5.t .............. skipped: rc5 is not supported by this OpenSSL build
../test/recipes/05-test_rmd.t .............. ok   
../test/recipes/05-test_sha1.t ............. ok   
../test/recipes/05-test_sha256.t ........... ok   
../test/recipes/05-test_sha512.t ........... ok   
../test/recipes/05-test_wp.t ............... ok   
../test/recipes/10-test_bn.t ............... ok   
../test/recipes/10-test_exp.t .............. ok   
../test/recipes/15-test_dh.t ............... ok   
../test/recipes/15-test_dsa.t .............. ok   
../test/recipes/15-test_ec.t ............... ok   
../test/recipes/15-test_ecdsa.t ............ ok   
../test/recipes/15-test_genrsa.t ........... ok   
../test/recipes/15-test_rsa.t .............. ok   
../test/recipes/15-test_rsapss.t ........... ok   
../test/recipes/20-test_enc.t .............. ok       
../test/recipes/20-test_passwd.t ........... ok   
../test/recipes/25-test_crl.t .............. ok   
../test/recipes/25-test_d2i.t .............. ok     
../test/recipes/25-test_pkcs7.t ............ ok   
../test/recipes/25-test_req.t .............. ok   
../test/recipes/25-test_sid.t .............. ok   
../test/recipes/25-test_verify.t ........... ok       
../test/recipes/25-test_x509.t ............. ok   
../test/recipes/30-test_afalg.t ............ skipped: test_afalg not supported for this build
../test/recipes/30-test_engine.t ........... ok   
../test/recipes/30-test_evp.t .............. ok   
../test/recipes/30-test_evp_extra.t ........ ok   
../test/recipes/30-test_pbelu.t ............ ok   
../test/recipes/40-test_rehash.t ........... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
	(less 1 skipped subtest: 3 okay)
../test/recipes/60-test_x509_store.t ....... ok   
../test/recipes/70-test_asyncio.t .......... ok   
../test/recipes/70-test_bad_dtls.t ......... ok   
../test/recipes/70-test_clienthello.t ...... ok   
../test/recipes/70-test_packet.t ........... ok   
../test/recipes/70-test_sslcbcpadding.t .... ok   
../test/recipes/70-test_sslcertstatus.t .... ok   
../test/recipes/70-test_sslextension.t ..... ok   
../test/recipes/70-test_sslmessages.t ...... ok   
../test/recipes/70-test_sslrecords.t ....... ok    
../test/recipes/70-test_sslsessiontick.t ... ok    
../test/recipes/70-test_sslskewith0p.t ..... ok   
../test/recipes/70-test_sslvertol.t ........ ok   
../test/recipes/70-test_tlsextms.t ......... ok   
../test/recipes/70-test_verify_extra.t ..... ok   
../test/recipes/80-test_ca.t ............... ok   
../test/recipes/80-test_cipherlist.t ....... ok   
../test/recipes/80-test_cms.t .............. ok   
../test/recipes/80-test_ct.t ............... ok   
../test/recipes/80-test_dane.t ............. ok   
../test/recipes/80-test_dtls.t ............. ok   
../test/recipes/80-test_dtlsv1listen.t ..... ok   
../test/recipes/80-test_ocsp.t ............. ok     
../test/recipes/80-test_pkcs12.t ........... ok   
../test/recipes/80-test_ssl_new.t .......... ok     
../test/recipes/80-test_ssl_old.t .......... ok   
../test/recipes/80-test_ssl_test_ctx.t ..... ok   
../test/recipes/80-test_sslcorrupt.t ....... ok   
../test/recipes/80-test_tsa.t .............. ok     
../test/recipes/80-test_x509aux.t .......... ok   
../test/recipes/90-test_async.t ............ ok   
../test/recipes/90-test_bio_enc.t .......... ok   
../test/recipes/90-test_bioprint.t ......... ok   
../test/recipes/90-test_constant_time.t .... ok   
../test/recipes/90-test_fuzz.t ............. ok     
../test/recipes/90-test_gmdiff.t ........... ok   
../test/recipes/90-test_heartbeat.t ........ skipped: heartbeats is not supported by this OpenSSL build
../test/recipes/90-test_ige.t .............. ok   
../test/recipes/90-test_memleak.t .......... ok   
../test/recipes/90-test_p5_crpt2.t ......... ok   
../test/recipes/90-test_secmem.t ........... ok   
../test/recipes/90-test_shlibload.t ........ ok   
../test/recipes/90-test_srp.t .............. ok   
../test/recipes/90-test_sslapi.t ........... ok   
../test/recipes/90-test_threads.t .......... ok   
../test/recipes/90-test_v3name.t ........... ok   

Test Summary Report
-------------------
../test/recipes/40-test_rehash.t         (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=95, Tests=547, 75 wallclock secs ( 0.66 usr  0.14 sys + 52.71 cusr  9.45 csys = 62.96 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make[1]: Leaving directory `/root/openssl-1.1.0f'
make: *** [tests] Error 2
[root@las4 openssl-1.1.0f]# 

```

Centos 7
Tried to do as a non-root user. (require sudo and failed)

**Comment by stevenzhu25** [comment]
Test:
```
[root@las4 openssl-1.1.0f]# HARNESS_VERBOSE=yes make 'TESTS=test_rehash' test 
make depend && make _tests
make[1]: Entering directory `/root/openssl-1.1.0f'
make[1]: Leaving directory `/root/openssl-1.1.0f'
make[1]: Entering directory `/root/openssl-1.1.0f'
( cd test; \
  SRCTOP=../. \
  BLDTOP=../. \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=.././engines \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl test_rehash )
../test/recipes/40-test_rehash.t .. 
Usage: rehash [options] [cert-directory...]
Valid options are:
 -help    Display this summary
 -h       Display this summary
 -compat  Create both new- and old-style hash links
 -old     Use old-style hash to generate links
 -n       Do not remove existing links
 -v       Verbose output
../util/shlib_wrap.sh ../apps/openssl rehash -help => 0
1..5
../../util/shlib_wrap.sh ../../apps/openssl rehash . => 0
ok 1 - Testing normal rehash operations
../../util/shlib_wrap.sh ../../apps/openssl rehash . => 0
ok 2 - Testing rehash operations on readonly files
../../util/shlib_wrap.sh ../../apps/openssl rehash . => 0
ok 3 - Testing rehash operations on empty directory
not ok 4 - Testing that we aren't running as a privileged user, such as root

#   Failed test 'Testing that we aren't running as a privileged user, such as root'
#   at ../test/recipes/40-test_rehash.t line 49.
ok 5 # skip It's pointless to run the next test as root
# Looks like you failed 1 test of 5.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
	(less 1 skipped subtest: 3 okay)

Test Summary Report
-------------------
../test/recipes/40-test_rehash.t (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=1, Tests=5,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.09 cusr  0.03 csys =  0.16 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make[1]: Leaving directory `/root/openssl-1.1.0f'
make: *** [tests] Error 2
[root@las4 openssl-1.1.0f]# 

```

**Comment by kaduk** [comment]
> not ok 4 - Testing that we aren't running as a privileged user, such as root

You're not supposed to run the test suite as root, and the test suite detects that you're running it as root, in this case.

**Comment by stevenzhu25** [comment]
I know.. But when i switch to a new user "steven" (Just created) i use sudo command.. and still show the same output.

**Comment by stevenzhu25** [comment]
@kaduk

**Comment by stevenzhu25** [comment]
```
[steven@las4 openssl-1.1.0f]$ HARNESS_VERBOSE=yes make 'TESTS=test_rehash' test
make depend && make _tests
make[1]: Entering directory `/root/openssl-1.1.0f'
make[1]: Leaving directory `/root/openssl-1.1.0f'
make[1]: Entering directory `/root/openssl-1.1.0f'
( cd test; \
  SRCTOP=../. \
  BLDTOP=../. \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=.././engines \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl test_rehash )
/bin/sh: line 0: cd: test: Not a directory
Can't open perl script ".././test/run_tests.pl": Permission denied
make[1]: *** [_tests] Error 13
make[1]: Leaving directory `/root/openssl-1.1.0f'
make: *** [tests] Error 2

```

**Comment by stevenzhu25** [comment]
Moved the openssl install to /etc/tmp, try run.. still failed the same test.
```
[steven@las4 tmp]$ HARNESS_VERBOSE=yes make 'TESTS=test_rehash' test
make depend && make _tests
make[1]: Entering directory `/etc/tmp'
make[1]: Leaving directory `/etc/tmp'
make[1]: Entering directory `/etc/tmp'
( cd test; \
  SRCTOP=../. \
  BLDTOP=../. \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=.././engines \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl test_rehash )
../test/recipes/40-test_rehash.t .. 
Usage: rehash [options] [cert-directory...]
Valid options are:
 -help    Display this summary
 -h       Display this summary
 -compat  Create both new- and old-style hash links
 -old     Use old-style hash to generate links
 -n       Do not remove existing links
 -v       Verbose output
../util/shlib_wrap.sh ../apps/openssl rehash -help => 0
1..5
mkdir rehash.12652: Permission denied at ../test/testlib/OpenSSL/Test.pm line 874.
# Looks like your test exited with 255 before it could output anything.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 5/5 subtests 

Test Summary Report
-------------------
../test/recipes/40-test_rehash.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 5 tests but ran 0.
Files=1, Tests=0,  1 wallclock secs ( 0.03 usr  0.00 sys +  0.07 cusr  0.01 csys =  0.11 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make[1]: Leaving directory `/etc/tmp'
make: *** [tests] Error 2
[steven@las4 tmp]$ 

```

**Comment by levitte** [comment]
If you sudo, that means you still run the test as root.
Don't sudo.

**Comment by sscherfke** [comment]
How are we supposed to run the tests from build-environments like Docker where *are* root? I have not yet found a solution to "un-root" myself.

**Comment by jbatres20** [comment]
I'm having the same errors and then when I try to install OpenSSH-7.6.p1, it cannot find the OpenSSL library.

[root@web openssl-1.1.0g]# make test
make depend && make _tests
make[1]: Entering directory `/root/openssl-1.1.0g'
make[1]: Leaving directory `/root/openssl-1.1.0g'
make[1]: Entering directory `/root/openssl-1.1.0g'
( cd test; \
  mkdir -p test-runs; \
  SRCTOP=../. \
  BLDTOP=../. \
  RESULT_D=test-runs \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=`cd .././engines; pwd` \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl  )
../test/recipes/01-test_abort.t ............ ok   
../test/recipes/01-test_sanity.t ........... ok   
../test/recipes/01-test_symbol_presence.t .. ok   
../test/recipes/02-test_ordinals.t ......... ok   
../test/recipes/03-test_exdata.t ........... ok   
../test/recipes/03-test_ui.t ............... ok   
../test/recipes/04-test_pem.t .............. ok     
../test/recipes/05-test_bf.t ............... ok   
../test/recipes/05-test_cast.t ............. ok   
../test/recipes/05-test_des.t .............. ok   
../test/recipes/05-test_hmac.t ............. ok   
../test/recipes/05-test_idea.t ............. ok   
../test/recipes/05-test_md2.t .............. skipped: md2 is not supported by this OpenSSL build
../test/recipes/05-test_md4.t .............. ok   
../test/recipes/05-test_md5.t .............. ok   
../test/recipes/05-test_mdc2.t ............. ok   
../test/recipes/05-test_rand.t ............. ok   
../test/recipes/05-test_rc2.t .............. ok   
../test/recipes/05-test_rc4.t .............. ok   
../test/recipes/05-test_rc5.t .............. skipped: rc5 is not supported by this OpenSSL build
../test/recipes/05-test_rmd.t .............. ok   
../test/recipes/05-test_sha1.t ............. ok   
../test/recipes/05-test_sha256.t ........... ok   
../test/recipes/05-test_sha512.t ........... ok   
../test/recipes/05-test_wp.t ............... ok   
../test/recipes/10-test_bn.t ............... ok   
../test/recipes/10-test_exp.t .............. ok   
../test/recipes/15-test_dh.t ............... ok   
../test/recipes/15-test_dsa.t .............. ok   
../test/recipes/15-test_ec.t ............... ok   
../test/recipes/15-test_ecdsa.t ............ ok   
../test/recipes/15-test_genrsa.t ........... ok   
../test/recipes/15-test_rsa.t .............. ok   
../test/recipes/15-test_rsapss.t ........... ok   
../test/recipes/20-test_enc.t .............. ok       
../test/recipes/20-test_passwd.t ........... ok   
../test/recipes/25-test_crl.t .............. ok   
../test/recipes/25-test_d2i.t .............. ok     
../test/recipes/25-test_pkcs7.t ............ ok   
../test/recipes/25-test_req.t .............. ok   
../test/recipes/25-test_sid.t .............. ok   
../test/recipes/25-test_verify.t ........... ok       
../test/recipes/25-test_x509.t ............. ok   
../test/recipes/30-test_afalg.t ............ skipped: test_afalg not supported for this build
../test/recipes/30-test_engine.t ........... ok   
../test/recipes/30-test_evp.t .............. ok   
../test/recipes/30-test_evp_extra.t ........ ok   
../test/recipes/30-test_pbelu.t ............ ok   
../test/recipes/40-test_rehash.t ........... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
	(less 1 skipped subtest: 3 okay)
../test/recipes/60-test_x509_store.t ....... ok   
../test/recipes/70-test_asyncio.t .......... ok   
../test/recipes/70-test_bad_dtls.t ......... ok   
../test/recipes/70-test_clienthello.t ...... ok   
../test/recipes/70-test_packet.t ........... ok   
../test/recipes/70-test_sslcbcpadding.t .... ok   
../test/recipes/70-test_sslcertstatus.t .... ok   
../test/recipes/70-test_sslextension.t ..... ok   
../test/recipes/70-test_sslmessages.t ...... ok   
../test/recipes/70-test_sslrecords.t ....... ok    
../test/recipes/70-test_sslsessiontick.t ... ok    
../test/recipes/70-test_sslskewith0p.t ..... ok   
../test/recipes/70-test_sslvertol.t ........ ok   
../test/recipes/70-test_tlsextms.t ......... ok   
../test/recipes/70-test_verify_extra.t ..... ok   
../test/recipes/80-test_ca.t ............... ok   
../test/recipes/80-test_cipherlist.t ....... ok   
../test/recipes/80-test_cms.t .............. ok   
../test/recipes/80-test_ct.t ............... ok   
../test/recipes/80-test_dane.t ............. ok   
../test/recipes/80-test_dtls.t ............. ok   
../test/recipes/80-test_dtlsv1listen.t ..... ok   
../test/recipes/80-test_ocsp.t ............. ok     
../test/recipes/80-test_pkcs12.t ........... ok   
../test/recipes/80-test_ssl_new.t .......... ok     
../test/recipes/80-test_ssl_old.t .......... ok   
../test/recipes/80-test_ssl_test_ctx.t ..... ok   
../test/recipes/80-test_sslcorrupt.t ....... ok   
../test/recipes/80-test_tsa.t .............. ok     
../test/recipes/80-test_x509aux.t .......... ok   
../test/recipes/90-test_async.t ............ ok   
../test/recipes/90-test_bio_enc.t .......... ok   
../test/recipes/90-test_bioprint.t ......... ok   
../test/recipes/90-test_constant_time.t .... ok   
../test/recipes/90-test_fuzz.t ............. ok     
../test/recipes/90-test_gmdiff.t ........... ok   
../test/recipes/90-test_heartbeat.t ........ skipped: heartbeats is not supported by this OpenSSL build
../test/recipes/90-test_ige.t .............. ok   
../test/recipes/90-test_memleak.t .......... ok   
../test/recipes/90-test_p5_crpt2.t ......... ok   
../test/recipes/90-test_secmem.t ........... ok   
../test/recipes/90-test_shlibload.t ........ ok   
../test/recipes/90-test_srp.t .............. ok   
../test/recipes/90-test_sslapi.t ........... ok   
../test/recipes/90-test_threads.t .......... ok   
../test/recipes/90-test_v3name.t ........... ok   

Test Summary Report
-------------------
../test/recipes/40-test_rehash.t         (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=95, Tests=556, 29 wallclock secs ( 0.27 usr  0.06 sys + 23.32 cusr  5.74 csys = 29.39 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make[1]: Leaving directory `/root/openssl-1.1.0g'
make: *** [tests] Error 2
[root@web openssl-1.1.0g]#

**Comment by richsalz** [comment]
*DO NOT RUN THE TESTS AS ROOT*

**Comment by levitte** [comment]
I can't remember exactly where, but I think I saw someone mention that if you run in a docker, you *are* root by default, and it sounded to me like it can be hard to get away from that.  It's possible that we should redesign that test so that it doesn't fail when you run as root, and only skips the no-root specific subtests...

**Comment by sscherfke** [comment]
We currently use this script to build OpenSSL 1.1 from within a Docker container:
```bash
if [ `uname` == Darwin ]; then
    ./Configure darwin64-x86_64-cc shared --prefix=$PREFIX --openssldir=$PREFIX/ssl
else
    ./config shared --prefix=$PREFIX --openssldir=$PREFIX/ssl
fi

make

# Some tests don't like to be run as "root".  Create a "test" user for them.
USER=test
id -u $USER &>/dev/null || adduser $USER
chown -R $USER .
sudo -u $USER bash -c "make test"  # Run tests
chown -R root .

make install
```

**Comment by levitte** [comment]
In the mean time, the test recipe got fix to not break when root runs, just skip over the one test that's pointless in that setting.  So to test rehash *fully*, it's still *recommended* to test as non-root, but if you happen to be root when testing, that's not the end of the world.

**Comment by jbatres20** [comment]
Thank you for your help. I ran a test from **Levitte** that I found on another post and the test passed.
My problem now is the OpenSSL library not found while trying to install OpenSSH-7.6.0g. I will open another issue for that.
Here is the output from that test:

[root@web openssl-1.1.0g]# make test TESTS=test_sanity V=1
make depend && make _tests
make[1]: Entering directory `/root/openssl-1.1.0g'
make[1]: Leaving directory `/root/openssl-1.1.0g'
make[1]: Entering directory `/root/openssl-1.1.0g'
( cd test; \
  mkdir -p test-runs; \
  SRCTOP=../. \
  BLDTOP=../. \
  RESULT_D=test-runs \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=`cd .././engines; pwd` \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl test_sanity )
../test/recipes/01-test_sanity.t .. 
1..1
../../util/shlib_wrap.sh ../../test/sanitytest => 0
ok 1 - running sanitytest
ok
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.00 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.02 CPU)
Result: PASS
Tests are not supported with your chosen Configure options
make[1]: Leaving directory `/root/openssl-1.1.0g'
[root@web openssl-1.1.0g]# 

[root@web ~]# openssl version
OpenSSL 1.1.0g  2 Nov 2017

Thanks,

Jorge Batres

**Comment by richsalz** [comment]
You need to tell OpenSSH where your OpenSSL libraries are installed.  This is **not** an OpenSSL issue.

**Comment by hantaoya** [comment]
/usr/bin/perl .././test/run_tests.pl  )
../test/recipes/01-test_abort.t .................... ok
../test/recipes/01-test_sanity.t ................... ok
../test/recipes/01-test_symbol_presence.t .......... ok
../test/recipes/01-test_test.t ..................... ok
../test/recipes/02-test_errstr.t ................... 69/76
../test/recipes/02-test_errstr.t ................... Dubious, test returned 32 (wstat 8192, 0x2000)
Failed 32/76 subtests
../test/recipes/02-test_internal_ctype.t ........... ok
../test/recipes/02-test_lhash.t .................... ok
../test/recipes/02-test_ordinals.t ................. ok
../test/recipes/02-test_stack.t .................... ok
../test/recipes/03-test_exdata.t ................... ok
../test/recipes/03-test_internal_asn1.t ............ ok
../test/recipes/03-test_internal_chacha.t .......... ok
../test/recipes/03-test_internal_curve448.t ........

../test/recipes/03-test_internal_curve448.t ........ ok
../test/recipes/03-test_internal_ec.t .............. ok
../test/recipes/03-test_internal_mdc2.t ............ ok
../test/recipes/03-test_internal_modes.t ........... ok
../test/recipes/03-test_internal_poly1305.t ........ ok
../test/recipes/03-test_internal_siphash.t ......... ok
../test/recipes/03-test_internal_sm2.t ............. ok
../test/recipes/03-test_internal_sm4.t ............. ok
../test/recipes/03-test_internal_ssl_cert_table.t .. ok
../test/recipes/03-test_internal_x509.t ............ ok
../test/recipes/03-test_ui.t ....................... ok
../test/recipes/04-test_asn1_decode.t .............. ok
../test/recipes/04-test_asn1_encode.t .............. ok
../test/recipes/04-test_asn1_string_table.t ........ ok
../test/recipes/04-test_bio_callback.t ............. ok
../test/recipes/04-test_bioprint.t ................. ok
../test/recipes/04-test_err.t ...................... ok
../test/recipes/04-test_pem.t ...................... ok
../test/recipes/05-test_bf.t ....................... ok
../test/recipes/05-test_cast.t ..................... ok
../test/recipes/05-test_cmac.t ..................... ok
../test/recipes/05-test_des.t ...................... ok
../test/recipes/05-test_hmac.t ..................... ok
../test/recipes/05-test_idea.t ..................... ok
../test/recipes/05-test_md2.t ...................... skipped: md2 is not supported by this OpenSSL build
../test/recipes/05-test_mdc2.t ..................... ok
../test/recipes/05-test_rand.t ..................... ok
../test/recipes/05-test_rc2.t ...................... ok
../test/recipes/05-test_rc4.t ...................... ok
../test/recipes/05-test_rc5.t ...................... skipped: rc5 is not supported by this OpenSSL build
../test/recipes/06-test-rdrand.t ................... ok
../test/recipes/10-test_bn.t ....................... 6/7

../test/recipes/10-test_bn.t ....................... ok
../test/recipes/10-test_exp.t ...................... ok
../test/recipes/15-test_dh.t ....................... ok
../test/recipes/15-test_dsa.t ...................... ok
../test/recipes/15-test_ec.t ....................... ok
../test/recipes/15-test_ecdsa.t .................... ok
../test/recipes/15-test_ecparam.t .................. ok
../test/recipes/15-test_genec.t .................... ok
../test/recipes/15-test_genrsa.t ................... ok
../test/recipes/15-test_mp_rsa.t ................... ok
../test/recipes/15-test_out_option.t ............... ok
../test/recipes/15-test_rsa.t ...................... ok
../test/recipes/15-test_rsapss.t ................... ok
../test/recipes/20-test_dgst.t ..................... ok
../test/recipes/20-test_enc.t ...................... ok
../test/recipes/20-test_enc_more.t ................. ok
../test/recipes/20-test_passwd.t ................... ok
../test/recipes/25-test_crl.t ...................... ok
../test/recipes/25-test_d2i.t ...................... ok
../test/recipes/25-test_pkcs7.t .................... ok
../test/recipes/25-test_req.t ...................... ok
../test/recipes/25-test_sid.t ...................... ok
../test/recipes/25-test_verify.t ................... Dubious, test returned 7 (wstat 1792, 0x700)
Failed 7/146 subtests
../test/recipes/25-test_x509.t ..................... ok
../test/recipes/30-test_afalg.t .................... ok
../test/recipes/30-test_engine.t ................... ok
../test/recipes/30-test_evp.t ...................... ok
../test/recipes/30-test_evp_extra.t ................ ok
../test/recipes/30-test_pbelu.t .................... ok
../test/recipes/30-test_pkey_meth.t ................ ok
../test/recipes/30-test_pkey_meth_kdf.t ............ ok
../test/recipes/40-test_rehash.t ................... ok
../test/recipes/60-test_x509_check_cert_pkey.t ..... ok
../test/recipes/60-test_x509_dup_cert.t ............ ok
../test/recipes/60-test_x509_store.t ............... ok
../test/recipes/60-test_x509_time.t ................ ok
../test/recipes/70-test_asyncio.t .................. ok
../test/recipes/70-test_bad_dtls.t ................. ok
../test/recipes/70-test_clienthello.t .............. ok
../test/recipes/70-test_comp.t ..................... ok
../test/recipes/70-test_key_share.t ................ ok
../test/recipes/70-test_packet.t ................... ok
../test/recipes/70-test_recordlen.t ................ ok
../test/recipes/70-test_renegotiation.t ............ ok
../test/recipes/70-test_servername.t ............... ok
../test/recipes/70-test_sslcbcpadding.t ............ ok
../test/recipes/70-test_sslcertstatus.t ............ ok
../test/recipes/70-test_sslextension.t ............. ok
../test/recipes/70-test_sslmessages.t .............. ok
../test/recipes/70-test_sslrecords.t ............... ok
../test/recipes/70-test_sslsessiontick.t ........... ok
../test/recipes/70-test_sslsigalgs.t ............... ok
../test/recipes/70-test_sslsignature.t ............. ok
../test/recipes/70-test_sslskewith0p.t ............. ok
../test/recipes/70-test_sslversions.t .............. ok
../test/recipes/70-test_sslvertol.t ................ ok
../test/recipes/70-test_tls13alerts.t .............. ok
../test/recipes/70-test_tls13cookie.t .............. ok
../test/recipes/70-test_tls13downgrade.t ........... ok
../test/recipes/70-test_tls13hrr.t ................. ok
../test/recipes/70-test_tls13kexmodes.t ............ ok
../test/recipes/70-test_tls13messages.t ............ ok
../test/recipes/70-test_tls13psk.t ................. ok
../test/recipes/70-test_tlsextms.t ................. ok
../test/recipes/70-test_verify_extra.t ............. ok
../test/recipes/70-test_wpacket.t .................. ok
../test/recipes/80-test_ca.t ....................... ok
../test/recipes/80-test_cipherbytes.t .............. ok
../test/recipes/80-test_cipherlist.t ............... ok
../test/recipes/80-test_ciphername.t ............... ok
../test/recipes/80-test_cms.t ...................... Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/6 subtests
../test/recipes/80-test_cmsapi.t ................... ok
../test/recipes/80-test_ct.t ....................... ok
../test/recipes/80-test_dane.t ..................... ok
../test/recipes/80-test_dtls.t ..................... ok
../test/recipes/80-test_dtls_mtu.t ................. ok
../test/recipes/80-test_dtlsv1listen.t ............. ok
../test/recipes/80-test_ocsp.t ..................... ok
../test/recipes/80-test_pkcs12.t ................... ok
../test/recipes/80-test_ssl_new.t .................. Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/30 subtests
../test/recipes/80-test_ssl_old.t .................. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests
../test/recipes/80-test_ssl_test_ctx.t ............. ok
../test/recipes/80-test_sslcorrupt.t ............... ok
../test/recipes/80-test_tsa.t ...................... ok
../test/recipes/80-test_x509aux.t .................. ok
../test/recipes/90-test_asn1_time.t ................ ok
../test/recipes/90-test_async.t .................... ok
../test/recipes/90-test_bio_enc.t .................. ok
../test/recipes/90-test_bio_memleak.t .............. ok
../test/recipes/90-test_constant_time.t ............ ok
../test/recipes/90-test_fatalerr.t ................. ok
../test/recipes/90-test_gmdiff.t ................... ok
../test/recipes/90-test_gost.t ..................... skipped: No test GOST engine found
../test/recipes/90-test_ige.t ...................... ok
../test/recipes/90-test_includes.t ................. ok
../test/recipes/90-test_memleak.t .................. ok
../test/recipes/90-test_overhead.t ................. skipped: Only supported in no-shared builds
../test/recipes/90-test_secmem.t ................... ok
../test/recipes/90-test_shlibload.t ................ Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/10 subtests
../test/recipes/90-test_srp.t ...................... ok
../test/recipes/90-test_sslapi.t ................... ok
../test/recipes/90-test_sslbuffers.t ............... ok
../test/recipes/90-test_store.t .................... ok
../test/recipes/90-test_sysdefault.t ............... ok
../test/recipes/90-test_threads.t .................. ok
../test/recipes/90-test_time_offset.t .............. ok
../test/recipes/90-test_tls13ccs.t ................. ok
../test/recipes/90-test_tls13encryption.t .......... ok
../test/recipes/90-test_tls13secrets.t ............. ok
../test/recipes/90-test_v3name.t ................... ok
../test/recipes/95-test_external_boringssl.t ....... skipped: No external tests in this configuration
../test/recipes/95-test_external_krb5.t ............ skipped: No external tests in this configuration
../test/recipes/95-test_external_pyca.t ............ skipped: No external tests in this configuration
../test/recipes/99-test_ecstress.t ................. ok
../test/recipes/99-test_fuzz.t ..................... ok

Test Summary Report
-------------------
../test/recipes/02-test_errstr.t                 (Wstat: 8192 Tests: 76 Failed: 32)
  Failed tests:  3-4, 9-11, 14, 16-17, 22-23, 26-27, 29-30
                32-33, 35-36, 43, 48, 51-52, 54, 60-62
                64, 66, 69-70, 72, 74
  Non-zero exit status: 32
../test/recipes/25-test_verify.t                 (Wstat: 1792 Tests: 146 Failed: 7)
  Failed tests:  86, 109-110, 113, 118, 121, 137
  Non-zero exit status: 7
../test/recipes/80-test_cms.t                    (Wstat: 1280 Tests: 6 Failed: 5)
  Failed tests:  1-5
  Non-zero exit status: 5
../test/recipes/80-test_ssl_new.t                (Wstat: 768 Tests: 30 Failed: 3)
  Failed tests:  12, 20, 28
  Non-zero exit status: 3
../test/recipes/80-test_ssl_old.t                (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
../test/recipes/90-test_shlibload.t              (Wstat: 1024 Tests: 10 Failed: 4)
  Failed tests:  2, 4, 6, 8
  Non-zero exit status: 4
Files=158, Tests=2649, 2059 wallclock secs (13.40 usr  0.86 sys + 1866.35 cusr 213.50 csys = 2094.11 CPU)
Result: FAIL
make[1]: *** [Makefile:208: _tests] Error 1
make[1]: Leaving directory '/data/tpc_c_cplusplus/thirdparty/tassl/tassl-1.1.1-armeabi-v7a-build'
make: *** [Makefile:205: tests] Error 2

prove -v 02-test_errstr.t
-------------------------------------------------------------------------------------------------------------
# prove 80-test_ssl_new.t
80-test_ssl_new.t .. Can't locate OpenSSL/Glob.pm in @INC (you may need to install the OpenSSL::Glob module) (@INC contains: /data/perl/lib/perl5/site_perl/5.34.1/arm-linux /data/perl/lib/perl5/site_perl/5.34.1 /data/perl/lib/perl5/5.34.1/arm-linux /data/perl/lib/perl5/5.34.1) at 80-test_ssl_new.t line 15.
BEGIN failed--compilation aborted at 80-test_ssl_new.t line 15.
80-test_ssl_new.t .. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run

Test Summary Report
-------------------
80-test_ssl_new.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.13 usr  0.01 sys +  0.03 cusr  0.00 csys =  0.17 CPU)
Result: FAIL
--------------------------------------------------------------------------------------------------------------
I ran tassl and he reported this error ,The box above is a single execution error log,What is the reason
