### ISSUE TITLE
Unable to install the openssl 1.0.1j  on solaris 10 32 bit OS

### ISSUE THREAD

**Issue by knrs1** [openssl/openssl#4390]
#pkgadd -d openssl.1.0.1j.i86pc.Solaris.10.pkg
The following packages are available: 
1 openssl openssl 1.0.1j i86pc Solaris 10 
(i386) 1.0.1j 

Select package(s) you wish to process (or 'all' to process 
all packages). (default: all) [?,??,q]: 

Processing package instance <openssl> from </export/home/pif1/openssl.1.0.1j.i86pc.Solaris.10.pkg> 

openssl 1.0.1j i86pc Solaris 10(i386) 1.0.1j 
The OpenSSL Project 
## Executing checkinstall script. 
ld.so.1: pkgserv: fatal: /usr/lib/libcrypto.so.1.0.0: wrong ELF class: ELFCLASS64 
ld.so.1: pkgserv: fatal: relocation error: file /usr/lib/libpkg.so.1: symbol PKCS7_free: referenced symbol not found 
pkgadd: ERROR: cannot start pkgserv daemon: Bad file number

**Comment by knrs1** [comment]
need urgent help

**Comment by kaduk** [comment]
Sorry, you'll need to contact the provider of your Solaris packages, as only they would know the details of the particular packaged versions of openssl.
Also, OpenSSL 1.0.1j is end-of-life and not supported by the OpenSSL project.

**Comment by knrs1** [comment]
Thanks for your prompt response

i downloaded 1.0.2j version, thats also not aloowing to install. Could you please help me on that?
