### ISSUE TITLE
check len > 0 in X509_NAME_get_text_by_OBJ()

### ISSUE THREAD

**Issue by qloong** [openssl/openssl#4392]
In X509_NAME_get_text_by_OBJ(X509_NAME *name, ASN1_OBJECT *obj, char *buf, int len) 
The function may assume the caller use the input parameters properly.

When input with buf != NULL and len <= 0, the result "memcpy(buf, data->data, -1)" looks like fun. :-)

Need to check len > 0 in this function implementation.

**Comment by mattcaswell** [comment]
That would be programmer error. Generally speaking we don't check for NULL input parameters, so I'm not sure we should necessarily check for a negative length in this scenario. Closing.
