### ISSUE TITLE
"ossl_init_config" funtion pointer in the 593 lines of the crypto/init.c file

### ISSUE THREAD

**Issue by jacobishao** [openssl/openssl#4409]
could someone tell where is the definition of 'ossl_init_config' which is in  the 593 lines of the crypto/init.c file ? thank you very much.

**Comment by mattcaswell** [comment]
Line 213
https://github.com/openssl/openssl/blob/master/crypto/init.c#L213

**Comment by jacobishao** [comment]
thank you very much!
when I expand the macro,I make sense.

2017-09-24 0:38 GMT+08:00 mattcaswell <notifications@github.com>:
