### ISSUE TITLE
Suspicious return type

### ISSUE THREAD

**Issue by vedantk** [openssl/openssl#4413]
ec_GFp_nistp_points_make_affine_internal(...) accepts a function pointer which has a suspicious type (ecp_nistputil.c):

`int (*felem_is_zero) (const void *in)`

The return type is "int", but one of the assumed values of the function pointer is felem_is_zero_int(...) from ecp_nistp224.c, which returns "limb" (uint64_t).

This shouldn't result in an accidental register clobber on the standard set of x86/ARM calling conventions (RAX, EAX/EDX, and r0-r4 are generally not preserved across function calls). This may be an issue if some other calling convention is in use.

**Comment by bernd-edlinger** [comment]
I think this is a valid concern.

**Comment by dot-asm** [comment]
I wonder how come this is not caught by strict warnings... Ah! There is explicit cast to (int (*))...

It should be noted that while concern is formally grounded, suggested clobbering problem is not the reason. Note that there is explicit cast to int followed by implicit cast to limb. This formally guarantees that upper half of return limb is zeroed, i.e. not clobbered. But that's not the real problem. Real problem is that on big-endian[!] 32-bit[!] systems implicit cast to 64-bit value would place upper half of return value to register that would otherwise receive 32-bit integer return value. However! Module in question can't be compiled on 32-bit system. Nor can it be compiled on big-endian system. Well, "can" in latter sentence means rather that it won't produce correct result. In fact there are requirements formulated for this module. The target system has to be 64-bit little-endian one, and it has to be able to sustain unaligned load. In other words the problem never occurs in practice. But this doesn't mean that it would be inappropriate to resolve formally inappropriate cast :-)

**Comment by bernd-edlinger** [comment]
Yes, the cast is definitely evil.
I think it is possible that int64_t can be returned in completely different registers than int.

**Comment by dot-asm** [comment]
> In other words the problem never occurs in practice.

It came out a bit misleading in the context. Cast doesn't cause problem in practice, because it doesn't cause problem on systems that meet the requirement.

**Comment by bernd-edlinger** [comment]
Yes, fortunately, there is no actual problem with any known target.
However, I believe that it was the author's intention to provide a wrapper function
around felem_is_zero that returns int here, therefore the name with suffix _int.
nistp256 and nistp521 do that correctly, this one looks like a simple oversight.

**Comment by dot-asm** [comment]
> I think it is possible that int64_t can be returned in completely different registers than int.

I've never seen that... Well, I bet standard doesn't actually says that it can't be the case and surely declare it as implementation-specific. At least we know that floating point values are customarily returned in separate registers. And this kind of calls for following question. Wouldn't it be appropriate to get rid of (int (*)) cast in ec_GFp_nistp_points_make_affine_internal call? I mean that #4450 should not only change the return value, but even argument...

**Comment by bernd-edlinger** [comment]
I know what you mean, but there are many more type-casts around in this module.

And I share your feeling about those....

**Comment by dot-asm** [comment]
> this one looks like a simple oversight.

I don't argue against that, nor am I saying that we shouldn't fix it. What I'm saying is that maybe the fix should really aim for removal of (int (*)) cast in ec_GFp_nistp_points_make_affine_internal call. Maybe in all ecp_nistp modules ;-)

**Comment by bernd-edlinger** [comment]
I can have a look, maybe it is more easy than it looks at first sight...

**Comment by dot-asm** [comment]
Sure it's easy. Since it's effectively a wrapper function, it can as well accept void \* and [implicitly] cast it to felem.

**Comment by bernd-edlinger** [comment]
All those type casts look somehow invalid:

```
                                             (void (*)(void *))felem_one,
                                             (int (*)(const void *))
                                             felem_is_zero_int,
                                             (void (*)(void *, const void *))
                                             felem_assign,
                                             (void (*)(void *, const void *))
                                             felem_square_reduce, (void (*)
                                                                   (void *,
                                                                    const void
                                                                    *,
                                                                    const void
                                                                    *))
                                             felem_mul_reduce,
                                             (void (*)(void *, const void *))
                                             felem_inv,
                                             (void (*)(void *, const void *))
                                             felem_contract);
```

**Comment by dot-asm** [comment]
On side note. If we go back to question about why wasn't it caught by strict warnings for a moment. Wouldn't it be meaningful is compiler warned about explicit[!] cast between pointers to functions that return incompatible types? Well, this is wrong forum to pose the question, but you, Bernd, might be right person to facilitate the answer ;-)

**Comment by bernd-edlinger** [comment]
Yes!!!!

**Comment by dot-asm** [comment]
> All those type casts look somehow invalid:

Well, I was thinking exclusively about is_zero. Of course if we widen the scope, it might get out of control. I suppose suggestion is to limit #4450 to is_zero and postpone the rest for another request...

**Comment by bernd-edlinger** [comment]
Okay, agreed.

**Comment by dot-asm** [comment]
>> I think it is possible that int64_t can be returned in completely different registers than int.

> I've never seen that...

In a sense I contradict myself. The way 64-bit values are returned on 32-bit big-endian systems can be viewed as "different registers". I suppose my mind got confused by "completely". I mean when I read "*completely* different registers" I thought "no, they are [always] same [integer] registers"... Sorry about possible confusion...

**Comment by bernd-edlinger** [comment]
Andy, implementing a warning as suggested seems feasible.

**Comment by dot-asm** [comment]
> implementing a warning as suggested seems feasible.

Cool! Thanks :-) But that would have to be another story, while this one can be closed. Well, there is suggestion to sanitize even more pointer-to-function casts, but I suppose it would be more efficient if we let them surface with new warning. I mean we can let computer help...
