### ISSUE TITLE
where is the definition of 'stack_st_CONF_MODULES' 

### ISSUE THREAD

**Issue by jacobishao** [openssl/openssl#4415]
when I expand the macro of 'STACK_OF(CONF_MODULE)',I got 'stack_st_CONF_MODULES'.
but i can't find the definition of this struct.
can someone help? thank you.

**Comment by levitte** [comment]
`include/openssl/safestack.h`

**Comment by jacobishao** [comment]
define STACK_OF(type) struct stack_st_##type
STACK_OF(t1);
I can get the statement
struct stack_st_CONF_MODULE ;
but I don't how many members does the struct has

**Comment by jacobishao** [comment]
as some aspect , it's just a  clarification or a definition 
right ?

**Comment by levitte** [comment]
It's just an opaque type definition.  If you want to look at the actual structure, have a look in `crypto/stack/stack.c`.  However, if you only want to use it, you should do so through the available stack manipulation functions.  They're all documented in `doc/man3/DEFINE_STACK_OF.pod`, which you can view in a more readable manner like this:

```
$ perldoc doc/man3/DEFINE_STACK_OF.pod
```
