### ISSUE TITLE
CA command generates V1 certificates with extensions

### ISSUE THREAD

**Issue by gareththered** [openssl/openssl#4419]
OpenSSL, with a configuration file that uses `copy_extensions = copyall` (or `copy`) but no `x509_extensions` section (and without `-extensions` on the command line) will copy any extensions from the request (as it should) but sets the X509 version to `0x0` (version 1).

It should either remove the extensions, or better, automatically set the version to `0x2` (version 3) if extensions are present.

If generating non-compliant certificates is deemed acceptable, then the CA command could at least print a warning message.

A workaround is to simply define an empty `x509_extensions` section.

The above was tested on v1.0.2.g on Linux Mint.

**Comment by levitte** [comment]
Good catch.  #4421 should fix this specifically for 1.0.2, please try it out.

**Comment by gareththered** [comment]
I've just compiled with Mint's OpenSSL v1.0.2g source package and your patch applied and it has resolved the issue.  Many thanks for such a quick response.
