### ISSUE TITLE
Result changed after using pipeline

### ISSUE THREAD

**Issue by WalterInSH** [openssl/openssl#4432]
Hi I'm using openssl command on Mac OS. 

I need to
1. calculate a string's md5
2. then calculate the md5's sha1

It worked fine separately. 

```
echo -n '18610286215' |openssl md5
->7af506da0e9df5fb30df0145a52752a2

echo -n '7af506da0e9df5fb30df0145a52752a2'|openssl sha1
->86c99e2542eacc8c8cebffb00b75f6eb4bbeaffe
```

But I got a totally different result when I put them together with a pipeline.

```
echo -n '18610286215' |openssl md5 |openssl sha1
->6f19810138f481f921cf05896478373a0878d73f
```

I'm not sure what's going on even though I tried googling it. Could you help me?

Openssl version:
OpenSSL 0.9.8zh 14 Jan 2016

**Comment by richsalz** [comment]
Because your second echo is wrong.
```
; echo -n '18610286215' | openssl md5                             
(stdin)= 7af506da0e9df5fb30df0145a52752a2
; echo -n '18610286215' | openssl md5 | openssl sha1              
(stdin)= b5e3d901e44a1e96803c3e9ad65b6abfaa232c41
; echo '(stdin)= 7af506da0e9df5fb30df0145a52752a2' | openssl sha1
(stdin)= b5e3d901e44a1e96803c3e9ad65b6abfaa232c41
```

And you should upgrade to a current version; 0.9.8 is buggy and insecure and unsupported, although that's not relevant here.

**Comment by levitte** [comment]
Also, along a pipeline, you need to be careful with line endings:

```
: ; echo 7af506da0e9df5fb30df0145a52752a2 |openssl sha1
(stdin)= 6f19810138f481f921cf05896478373a0878d73f
: ; echo -n 7af506da0e9df5fb30df0145a52752a2 |openssl sha1
(stdin)= 86c99e2542eacc8c8cebffb00b75f6eb4bbeaffe
```

what ended up happening with `echo -n '18610286215' |openssl md5 |openssl sha1` is that the result from `openssl md5` had a line ending, so even if you take away the `(stdin)= `, you'll get the wrong result:

```
: ; echo -n '18610286215' | openssl md5 | cut -f2 -d' ' | openssl sha1
(stdin)= 6f19810138f481f921cf05896478373a0878d73f
```

This is true regardless of OpenSSL version.

**Comment by WalterInSH** [comment]
@levitte & @richsalz  Your replies are really helpful. 

You're right about the 'line endings'!! Here's an additional test (after upgrading my openssl).

```
echo -n '18610286215' | openssl md5
->(stdin)= 7af506da0e9df5fb30df0145a52752a2

echo -n '7af506da0e9df5fb30df0145a52752a2\n'|openssl sha1
->(stdin)= 6f19810138f481f921cf05896478373a0878d73f
```

To fix the problem, just remove the line ending character.

```
echo -n '18610286215' | openssl md5 | cut -f2 -d' ' | tr -d '\n' |openssl sha1
->(stdin)= 86c99e2542eacc8c8cebffb00b75f6eb4bbeaffe
```

About MacOS:
MaxOS has already had openssl installed. The version's "OpenSSL 0.9.8zh 14 Jan 2016". It does not print '(stdin)=', so this prefix is irrelevant in this case.

Your replies helped me a lot. Big thanks!
