### ISSUE TITLE
too short salt used in "enc" command

### ISSUE THREAD

**Issue by fedor-brunner** [openssl/openssl#4433]
OpenSSL enc 
https://www.openssl.org/docs/manmaster/man1/enc.html
command can use password together with salt to create key/IV for symmetric encyption. Because the salt is only 8 bytes long there are only 2^64 possible key/IV pairs which can be generated from a single password.

So because of birthday paradox after about 2^32 encryptions using the enc command with a single password there is high probability of key/IV reuse.

Possible solutions:
  1. Remove the password and salt options from enc command.
  2. Increase the length of salt. Optimal length would be 64 bytes.

**Comment by t8m** [comment]
I do not think this is going to happen ever. We should not be inventing our own file encryption formats. Closing.
