### ISSUE TITLE
Macro redefinition warnings

### ISSUE THREAD

**Issue by Coeur** [openssl/openssl#4441]
AES_ENCRYPT and AES_DECRYPT macros are redefined when including both https://github.com/BrianGladman/aes and https://github.com/openssl/openssl.

[Cocoapods recommandation](https://guides.cocoapods.org/using/troubleshooting.html#can-i-workaround-duplicate-symbol-errors-with-static-libraries):
> Can I workaround ‘Duplicate Symbol’ errors with static libraries?
> [...]
> in general, the vendor should really prefix any dependencies it includes, so you don’t need to deal with it. When this happens, please contact the vendor and ask them to fix it on their side.

So my request is: can you prefix AES_ENCRYPT and AES_DECRYPT macros please?

Related: https://github.com/BrianGladman/aes/issues/29

**Comment by richsalz** [comment]
OpenSSL doesn't work well with any other crypto implementations, and certainly in the same file it's just about impossible.  You only need one AES implementation :)  You can work around this by putting something like this:
```
#define AES_DECRYPT OPENSSL_AES_DECRYPT
#define AES_ENCRYPT OPENSSL_AES_ENCRYPT
#include <openssl/aes.h<
```

**Comment by Coeur** [comment]
I'm sorry to have bothered you.

We were actually including both files simultaneously accidentally because we were doing an extra:

    #include "aes.h"

Which was taking the undesired one and was redefining the macro.
So issue was on our end and was fixed with:

    #include "openssl/aes.h"

**Comment by richsalz** [comment]
glad you got it fixed :)
