### ISSUE TITLE
Add branch coverage to coveralls statistics

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#4444]
Coveralls.io recently gained support for measuring not only line coverage but also branch coverage: https://github.com/lemurheavy/coveralls-public/issues/31#issuecomment-284484062

I'd like to see it reported openssl builds

**Comment by richsalz** [comment]
And also as you commented in another PR, we should try to make "failures" ignore anything less than .5% or such.

**Comment by levitte** [comment]
Unless I'm mistaken, coveralls.io has simply started to show branch coverage, hasn't it?  The rest depends entirely on what code we actually run in our tests, i.e. do we actually run all branches everywhere?  (I doubt it, there are lots of places where we don't deliberately try to cause faults, for example)

**Comment by levitte** [comment]
Or do you have to switch something on to display branch coverage?  I've looked around a bit, but can't find such a switch.  If there is one, someone please point it out, thank you.

**Comment by tomato42** [comment]
`gcov` needs to be told to collect branch coverage - that's options `-b` and `-c`

coveralls needs to be told to display them - that's in project Settings → Badge and Token → Branch Coverage checkbox near "Include in Aggregate %"

after both of those things are done, a new run should have two new columns in the source file listing - branch hits and branch misses

**Comment by levitte** [comment]
Ok, thanks for the info.  I've just changed the settings at Coveralls, and pushed a PR to add the flags in our .travis.yml
