### ISSUE TITLE
Error: add subject alternative name 

### ISSUE THREAD

**Issue by tejas3** [openssl/openssl#4445]
<img width="406" alt="capture" src="https://user-images.githubusercontent.com/13366362/31030909-99a548fc-a574-11e7-9c41-6dd6d45a4481.PNG">

**openssl version: OpenSSL 1.0.2l  25 May 2017**

**openssl.cfg**:

**[ req ]**
distinguished_name = req_distinguished_name
req_extensions = v3_req

**[ req_distinguished_name ]**
countryName = Country Name (2 letter code)
countryName_default = US
stateOrProvinceName = State or Province Name (full name)
stateOrProvinceName_default = MN
localityName = Locality Name (eg, city)
localityName_default = Minneapolis
organizationalUnitName	= Organizational Unit Name (eg, section)
organizationalUnitName_default	= Domain Control Validated
commonName = Internet Widgits Ltd
commonName_max	= 64

**[ v3_req ]**
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = www.google.com
IP.1 = 192.168.1.1

**Comment by levitte** [comment]
Mysterious.  I tried it on Linux just now, with exactly that configuration, and it worked like a charm...

**Comment by tejas3** [comment]
Facing same issue on windows platform.
Also attached openssl.cfg.     Kindly rename [openssl.txt --> openssl.cfg]
[openssl.txt](https://github.com/openssl/openssl/files/1348207/openssl.txt)

**Comment by tejas3** [comment]
Solved!
So closing this issue
