### ISSUE TITLE
Double endian-change in AES

### ISSUE THREAD

**Issue by sivizius** [openssl/openssl#4446]
Ohai,
the AES-implementation with lookup-tables in aes_core uses GET32 and PUT32. Both changes the endianess, but because there are just several table-lookups, it would work (I tested it) without this changes of endianess with adjusted lookup-tables and masks.
Is there a (security) reason, why this is done this way?

**Comment by dot-asm** [comment]
> Is there a (security) reason, why this is done this way?

This is not OpenSSL *issue* and it's not even OpenSSL-specific question. Hence it's not right forum to pose it. Why it's done that way is effectively stated in beginning of file, starting from line 10. Keep in mind that there is difference between assuming that everybody has computer like yours and producing portable code. Also note that it's not the only implementation available in OpenSSL...
