### ISSUE TITLE
CipherSuite TLS_CENSORED_WITH_CENSORED_CENSORED = { 0x01, 0xC3 }

### ISSUE THREAD

**Issue by KOLANICH** [openssl/openssl#4451]
In some shitty jurisdictions the Internet is censored. TLS connections are also censored by IP addresses. Now it's hard to understand if a site just down or censored. So in the wake of http 451 code I propose to add a new ciphersuite, 
```CipherSuite TLS_CENSORED_WITH_CENSORED_CENSORED = { 0x01, 0xC3 }```
(```0x01c3``` = ```451```)
to allow the censors (often censors are ISPs which emploees are also not happy with the situation) to show the people and the websites what the sites are not down/there are connections from that jurisdiction, but they are censored.

**Comment by richsalz** [comment]
And see also HTTP error code 451.
