### ISSUE TITLE
SSLeay doesn't return runtime OpenSSL version, but compile time version.

### ISSUE THREAD

**Issue by smukil** [openssl/openssl#4454]
I work on a project where we use OpenSSL by dynamically linking against it. We recently noticed an issue, where the SSLeay() function does not return the version of the OpenSSL library it's linked against, but rather returns the version that it was compiled against.

We used a small test program to verify this as well:
`#include <openssl/ssl.h>

int main()
{
        unsigned long ssl_version;
        ssl_version = SSLeay();

        printf("Compiled with: %lx (%s)\n", OPENSSL_VERSION_NUMBER, OPENSSL_VERSION_TEXT);
        printf("Running with:  %lx (%s)\n", ssl_version, SSLeay_version(SSLEAY_VERSION));

        return 0;
}`

We built this on a CentOS6.4 machine which contains "OpenSSL 1.0.0-fips 29 Mar 2010".

And we ran it on a RHEL6.7 machine which contains "OpenSSL 1.0.1e-fips 11 Feb 2013". We get:

> Compiled with: 10000003 (OpenSSL 1.0.0-fips 29 Mar 2010)
> Running with:  10000003 (OpenSSL 1.0.0-fips 29 Mar 2010)

When we compile and run it on the same RHEL6.7 machine, we get:

> Compiled with: 1000105f (OpenSSL 1.0.1e-fips 11 Feb 2013)
> Running with:  1000105f (OpenSSL 1.0.1e-fips 11 Feb 2013)

When we compile it on RHEL6.7 and run it on CentOS6.4, we get:

> Compiled with: 1000105f (OpenSSL 1.0.1e-fips 11 Feb 2013)
> Running with:  10000003 (OpenSSL 1.0.0-fips 29 Mar 2010)

So it looks like compiling against a newer version and running against an older version is fine, but not the other way round.

Under GDB I noticed that there are 2 definitions of SSLeay() in the same dynamically linked libcrypto.so:

> (gdb) disas 0x000000384906bfd0
> Dump of assembler code for function SSLeay:
>    0x000000384906bfd0 <+0>:	mov    $0x1000105f,%eax
>    0x000000384906bfd5 <+5>:	retq   

> (gdb) disas
> Dump of assembler code for function SSLeay:
> => 0x000000384906bfc0 <+0>:	mov    $0x10000003,%eax
>    0x000000384906bfc5 <+5>:	retq  

Which is confusing to me, why would it have a hardcoded version of a specific older OpenSSL version in the SO? Unless, I'm grossly misunderstanding something.

So, my question is, is this a bug in OpenSSL? Or are we not supposed to be building against an older OpenSSL and running against a newer version?

**Comment by richsalz** [comment]
You will have to contact your vendor.  OpenSSL 1.0.1 is no longer supported by the OpenSSL team.

**Comment by levitte** [comment]
I'll still respond to this, because we have the *exact* same setup in current releases, i.e. this specific problem might still exist in what we do support.

However, @smukil, I believe you made a mistake somewhere, and I can imagine two possibilities:

1. you linked with the static library, not the shared one.  In that case, that's the library version you transport with the program, no matter what version is on the machine you run.
2. you haven't linked against the shared library you thought you have.

Re this:

> We built this on a CentOS6.4 machine which contains "OpenSSL 1.0.0-fips 29 Mar 2010".
> 
> And we ran it on a RHEL6.7 machine which contains "OpenSSL 1.0.1e-fips 11 Feb 2013". We get:

I imagine it's the first mistake...

Just to make absolutely sure, I made a test with the oldest supported OpenSSL version, 1.0.2.  It's the current default on my laptop, on which I also have the bleeding edge branch of 1.0.2.  My test is, very simply put, building and running your program (called foo.c here).
The installed version on my laptop is "OpenSSL 1.0.2l  25 May 2017", and the bleeding edge branch is "OpenSSL 1.0.2m-dev  xx XXX xxxx", lives in `gitwrk/openssl.net/official/1.0.2` and was configured for shared library support:

```
: ; cat foo.c
#include <openssl/ssl.h>

int main()
{
        unsigned long ssl_version;
        ssl_version = SSLeay();

        printf("Compiled with: %lx (%s)\n", OPENSSL_VERSION_NUMBER, OPENSSL_VERSION_TEXT);
        printf("Running with:  %lx (%s)\n", ssl_version, SSLeay_version(SSLEAY_VERSION));

        return 0;
}
: ; cc -o foo foo.c -lcrypto
: ; ./foo
Compiled with: 100020cf (OpenSSL 1.0.2l  25 May 2017)
Running with:  100020cf (OpenSSL 1.0.2l  25 May 2017)
: ; (cd gitwrk/openssl.net/official/1.0.2; ln -s libcrypto.so.1.0.0 libcrypto.so.1.0.2)
: ; LD_LIBRARY_PATH=gitwrk/openssl.net/official/1.0.2 ./foo
./foo: gitwrk/openssl.net/official/1.0.2/libcrypto.so.1.0.2: no version information available (required by ./foo)
Compiled with: 100020cf (OpenSSL 1.0.2l  25 May 2017)
Running with:  100020d0 (OpenSSL 1.0.2m-dev  xx XXX xxxx)
```

(The symlink libcrypto.so.1.0.0 -> libcrypto.so.1.0.2 is needed because I run Debian, and Debian has made a different shared library version choice than we did, for historical reasons)

**Comment by FdaSilvaYY** [comment]
@smukil : `ldd`  is your friend ;)
Your binary app is statically linked to a different binary lib ; and/or pointing to a different binary lib file at runtime .
Please see also : https://www.cyberciti.biz/.../linux-shared-library-management.html

**Comment by richsalz** [comment]
@levitte thanks for the details; I learned something!

**Comment by smukil** [comment]
Thanks for the response @levitte and @FdaSilvaYY.

I made sure that the binaries are dynamically linked to OpenSSL. I used the following command to build the test binary:
make ssltest CFLAGS='-Wall -g -O2' LDFLAGS='-lcrypto -lssl'

Also, I confirmed that both the test binaries, i.e. one that was compiled on CentOS6.4 with OpenSSL 1.0.0 and the other that was compiled on RHEL6.7 with OpenSSL 1.0.1e, are linked to the exact same libcrypto and libssl. Both are running on the RHEL6.7 machine:

> $ ./ssltest_compiled_on_67 
> Compiled with: 1000105f (OpenSSL 1.0.1e-fips 11 Feb 2013)
> Running with:  1000105f (OpenSSL 1.0.1e-fips 11 Feb 2013)

> $ ldd ssltest_compiled_on_67 
> 	linux-vdso.so.1 =>  (0x00007ffefc5ad000)
> 	**libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x0000003849000000)**
> 	**libssl.so.10 => /usr/lib64/libssl.so.10 (0x000000384b800000)**
> 	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000003efd600000)
> 	libm.so.6 => /lib64/libm.so.6 (0x0000003841400000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003efda00000)
> 	libc.so.6 => /lib64/libc.so.6 (0x0000003840c00000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x0000003840800000)
> 	libz.so.1 => /lib64/libz.so.1 (0x0000003841c00000)
> 	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x0000003848c00000)
> 	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x0000003847c00000)
> 	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x0000003846400000)
> 	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x0000003848400000)
> 	libresolv.so.2 => /lib64/libresolv.so.2 (0x0000003843000000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000003840400000)
> 	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x0000003848800000)
> 	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x0000003847000000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003841000000)
> 	libselinux.so.1 => /lib64/libselinux.so.1 (0x0000003842000000)

> $ ./ssltest_compiled_on_64 
> Compiled with: 10000003 (OpenSSL 1.0.0-fips 29 Mar 2010)
> Running with:  10000003 (OpenSSL 1.0.0-fips 29 Mar 2010)

> $ ldd ssltest_compiled_on_64 
> 	linux-vdso.so.1 =>  (0x00007ffd0fb77000)
> 	**libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x0000003849000000)**
> 	**libssl.so.10 => /usr/lib64/libssl.so.10 (0x000000384b800000)**
> 	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000003efd600000)
> 	libm.so.6 => /lib64/libm.so.6 (0x0000003841400000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003efda00000)
> 	libc.so.6 => /lib64/libc.so.6 (0x0000003840c00000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x0000003840800000)
> 	libz.so.1 => /lib64/libz.so.1 (0x0000003841c00000)
> 	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x0000003848c00000)
> 	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x0000003847c00000)
> 	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x0000003846400000)
> 	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x0000003848400000)
> 	libresolv.so.2 => /lib64/libresolv.so.2 (0x0000003843000000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000003840400000)
> 	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x0000003848800000)
> 	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x0000003847000000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003841000000)
> 	libselinux.so.1 => /lib64/libselinux.so.1 (0x0000003842000000)

So I've learned that this may be a problem only with a small subset of OpenSSL versions I'm working with. I went with @richsalz 's suggestion and opened a ticket with the vendor (RHEL) and this is the response I received:

> 
> This is done on purpose. Some applications perform incorrect (too sensitive) version check and the only way to avoid it is to mask the actual run-time version of OpenSSL built against an old OpenSSL release.
> 
> You need to build against the oldest OpenSSL version with which you need your software to run. So if your intention is to be able to run the software with RHEL-6.4 then you must also build it on this RHEL release. You should be able to run it with any newer RHEL-6 version as well. But of course you cannot use new features of the newer OpenSSL version except these that do not require any new API call.
https://bugzilla.redhat.com/show_bug.cgi?id=1497859

So, although this was intended to work as you explained and as I expected, they may have modified these older versions to do something else. Which seems like they're breaking expectations, but I'll continue the thread with them. Thanks for all your help!
