### ISSUE TITLE
Missing latest release tag on releases

### ISSUE THREAD

**Issue by mboelen** [openssl/openssl#4469]
When fetching the latest release via the GitHub API, I discovered that the latest release is not tagged as such. So it shows a release of 2000 now (2000-11-07T13:49:47Z).

**Comment by kaduk** [comment]
Just for clarity, can you expound on what "the GitHub API" means -- i.e., a specific URL?

**Comment by mboelen** [comment]
curl https://api.github.com/repos/openssl/openssl/releases/latest (returns no data)

Example with Lynis: curl https://api.github.com/repos/CISOfy/lynis/releases/latest (returns data)

**Comment by richsalz** [comment]
We only do tagging, we don't do releases.  If you can point to docs to tell us how to do that, we could consider it :)

**Comment by mboelen** [comment]
Yes, I saw the tags: curl https://api.github.com/repos/openssl/openssl/tags
The latest tag has a funky name ("rsaref"), which is why I discovered this when reviewing OpenSSL for our website: https://linuxsecurity.expert/tools/openssl/

Sure, here is the related document: https://help.github.com/articles/creating-releases/ - for our project we do it manually, but you can also automate that (depending on how you do tagging)

Thanks for the considering it. Would be great if both tagging and releases are used. Then each release can be discovered easily by both users and systems. If our website discovers a new release, we will also do announce it in such case. So free PR for the project :)

**Comment by levitte** [comment]
"the latest tag" isn't the latest tag.  It seems that the tags output is sorted in reverse alphanumerical order on the tag name...

**Comment by levitte** [comment]
I guess we could do that form of release...  the description could contain a URL to our downloads location.

**Comment by levitte** [comment]
That'll be for future releases, if we do decide to do this...

**Comment by mboelen** [comment]
Yes @levitte - you are right about that. For most projects, this sorting is right, as tag 1.2.3 will be after 1.2.2. In the case of the OpenSSL project, it doesn't sort properly, so that is why we can't use tags either. Automatic adding releases would solve it. Thanks for the consideration :)

**Comment by levitte** [comment]
> it doesn't sort properly, so that is why we can't use tags either

... you *could* pick out the tags that fit our release scheme and sort on your own ;-)
(the perl style regexp to match our release tags it `OpenSSL_\d_\d_\d[1-z]*`)

**Comment by Croydon** [comment]
Revisiting this.

I would love to see that OpenSSL creates GitHub releases and uploads the official release downloads to these releases. 

The downloads from the OpenSSL website have the annoying downside that they are not lasting URLs as releases get moved to the sub-directory `old/`. This makes packaging OpenSSL harder as it needs to be. (And yes, nobody should use old versions, but breaking isn't the answer)

GitHub releases could also serve as another download mirror.

I'm confused what the last comments mean, because OpenSSL already uses git tags (even when the comments were written 2017), hence I don't understand a discussion about potential sorting issues . GitHub sorts tags and releases by the time they got created (at least if I'm not missing something).

**Comment by t8m** [comment]
The issue with unstable download URLs can be solved also by changing the layout of the existing download directories.

**Comment by t8m** [comment]
For example we could rename/symlink old->all and always copy/symlink the current release to this directory as well.

**Comment by pzygielo** [comment]
> For example we could rename/symlink old->all and always copy/symlink the current release to this directory as well.

That would also fulfil promise (https://www.openssl.org/source/):
> 	All releases can be found at /source/old.

:smile:

**Comment by t8m** [comment]
Yep :smile:

**Comment by levitte** [comment]
The current idea is that the top source directory should not be cluttered with old stuff, people that simply look there with no further expectation should find the latest.  Only the latest.

However, an this is what I suppose @t8m is trying to say, is that we should only archive the actual files, even the latest, in `source/1.1.1/` [^1] for example, and then symlink them in the top directory, and it should be documented somewhere, if not said directly in our announcements, that for permalink purposes, people should use, say, `https://openssl.org/source/1.1.1/openssl-1.1.1f.tar.gz`.

-----

[^1]: In such a setting, "old" is getting aged and shouldn't be used any more....  we might want to keep a symlink around, though.

**Comment by t8m** [comment]
Yes, that would solve it.

**Comment by mattcaswell** [comment]
The stable permalinks already exist, e.g. this works:

https://www.openssl.org/source/openssl-1.1.1a.tar.gz

We probably don't advertise that fact anywhere.

**Comment by richsalz** [comment]
symlinks don't work with CDN's very well; you want a rewrite rule.

**Comment by mattcaswell** [comment]
> symlinks don't work with CDN's very well; you want a rewrite rule.

Like I said, there is nothing to be done. It already all works (and through the CDN).

**Comment by t8m** [comment]
Closing as we do not use GitHub releases feature and the stable symlinks work fine.
