### ISSUE TITLE
no-srp configure option results in build failure

### ISSUE THREAD

**Issue by cconroy** [openssl/openssl#447]
If you configure to build with the option "no-srp", then the build fails since it tries to compile bn_srp.c which includes srp.h:

```
In file included from bn_srp.c:3:
../../include/openssl/srp.h:66:4: error: #error SRP is disabled.
```

I reproduced this on Centos 6.5 linux and mac (both x86_64)

For reference, my configure options:
`/Configure --prefix=/path/to/my/prefix zlib enable-camellia enable-seed enable-tlsext enable-rfc3779 enable-cms enable-md2 no-mdc2 no-gost no-srp shared`

This is from latest master:

```
commit 15db6a40d3569789329d3f6f84e47e0e0e8f9caa
Author: Richard Levitte <levitte@openssl.org>
Date:   Mon Oct 19 20:53:14 2015 +0200

    make update
    
    Reviewed-by: Matt Caswell <matt@openssl.org>

```

**Comment by levitte** [comment]
Easy fix, coming up.

**Comment by richsalz** [comment]
@levitte is this closed or fixed or pending?

**Comment by mattcaswell** [comment]
This should be fixed now. Closing.
