### ISSUE TITLE
d2i_PublicKey documentation error

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4489]
d2i_PublicKey is documented as a general d2i_TYPE, so:

    TYPE *d2i_TYPE(TYPE **a, unsigned char **pp, long length);

But it's really:

    EVP_PKEY *d2i_PublicKey(int type, EVP_PKEY **a, const unsigned char **pp, long length);

So it takes a type as argument.

**Comment by richsalz** [comment]
Fix merged.

**Comment by Amirhosein835** [comment]
I have continue
