### ISSUE TITLE
PEM_read_bio_X509_REQ(...) Always returns NULL!

### ISSUE THREAD

**Issue by tejas3** [openssl/openssl#4505]
**Openssl Version: OpenSSL 1.0.2l  25 May 2017**

**BIO* bo = BIO_new(BIO_s_mem());
BIO_write(bo, csrString.c_str(), strlen(csrString.c_str()));
X509_REQ* req1 = PEM_read_bio_X509_REQ(bo, NULL, NULL, NULL);**

Above code always returns null even if csrString is in correct format.

Also tried with-

**BIO* in = BIO_new_file(csrFile, "r");
X509_REQ* req = PEM_read_bio_X509_REQ(in, NULL, NULL, NULL);**

**Comment by kaduk** [comment]
> Above code always returns null even if csrString is in correct format.

What do you believe to be the correct format?

For example, this works for me:

```
bkaduk@bos-:~/git/openssl$ cat /tmp/a.pem
-----BEGIN CERTIFICATE REQUEST-----
MIICijCCAXICAQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUx
ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAKAb1qWtJnhOYA/rb5ZS1Zn8rnGh0sVZK8azhtvk
FGduBZEkQHQ3KV2a8/2R9WdlNXehXKw7FxFeqMug7plh87QOlY5vxGOHjaBc+Nua
17EQSLO11TF55/vKXy6cIEqUnFuKwRNrokFpnFj27kVbZd74529WNq14tGbcIybE
fNzyvlJnb3M/szIhjLoOp8Pus/UdngIB3nqswKsCIVEnHe6y2dbsVCiH3qEqQRof
2n62kFuFuhRiSL8xVEr+tEFZXgfLWOdK5vD/qeCYABLM5o0gTuuyDH/BiOb34zRd
5UK5pYN/YTy6bBKIgCkucr5/XkRxm57B7uUwcxw/l7K4AyUCAwEAAaAAMA0GCSqG
SIb3DQEBCwUAA4IBAQBGWdqVUxDSw5rdS7hs53roIvrcO6/oaGsTSG0laSlX7la4
iJigQS88uHp92ecIbiIX3YQnAFZkGfH2ZjdJ5nd0ux80STLl9yGYtdgR4xsBjmBZ
B40aRdjnqA3u2EN5iixW9T92ZcwxxCd1AYkKRs1lW/Wv5qugoCOggqDRdNryPZ53
JtwUQfuHI6amtsIV3WyE2F4gasMUgSsprql3uUTIXPxwC0NuKBLVFJ453msIePWf
bp4j8YQTI+ySc61RnhYGK8rxdzDsczS7A58l5xaZeYDD/WMBVGoDwGoDCVLx9Ema
R4i/e+Qdh9bBODQ2YhQOdP0Fy+vlt1KIgSmQ0wd1
-----END CERTIFICATE REQUEST-----
bkaduk@bos:~/git/openssl$ cat /tmp/a.c
#include <openssl/pem.h>
#include <stdio.h>

int main(void)
{
    BIO *in = BIO_new_file("/tmp/a.pem", "r");
    X509_REQ *req = PEM_read_bio_X509_REQ(in, NULL, NULL, NULL);
    printf("got pointer %p\n", req);
    return 0;
}
bkaduk@bos:~/git/openssl$ cc  /tmp/a.c -lcrypto -o /tmp/a
bkaduk@bos:~/git/openssl$ /tmp/a
got pointer 0x1fe8520
```

**Comment by tejas3** [comment]
Does it only work with CSR(signed) string? because I have CSR string data before it get signed by private key.

**Comment by kaduk** [comment]
Yes, the X509_REQ type is different from the X509_REQ_INFO type.  For the latter, it looks like you'd need to manually do the base64 decoding and use d2i_X509_REQ_INFO().

**Comment by tejas3** [comment]
X509_REQ_INFO* reqInfo;
suppose  reqInfo is filled with without signed CSR string data(reqInfo not null now) then how to convert X509_REQ_INFO to X509_REQ ?

**Comment by kaduk** [comment]
I have never actually done this, but apps/req.c:do_X509_REQ_sign() seems to be doing this sort of thing.  Note that the standalone ```X509_REQ_INFO *``` is not used, but rather one is expected to populate the X509_REQ_INFO member of the X509_REQ structure.  At present there is no public API to do so, so one is forced to inspect the private header (x509_int.h) and massage the obtained X509_REQ_INFO into the corresponding fields of the desired X509_REQ.  (memcpy might be simplest, albeit sloppy.)

So, we are forced to conclude that the X509_REQ_INFO type is not really well-supported, and its ASN.1 functions are implemented mostly as a side effect of implementing ASN.1 functions for the more usable X509_REQ type.  I am not sure that I see a clear case for making the X509_REQ_INFO type more usable, but would welcome some reasoning from tejas3 that it should be supported, or discussion from other team members.

**Comment by tejas3** [comment]
Hi kaduk,

>I am not sure that I see a clear case for making the X509_REQ_INFO type more usable, but would >welcome some reasoning from tejas3 that it should be supported, or discussion from other team >members.

Any update on this? did you get a chance to talk with your team for the same?
Eagerly waiting for you reply.
Thanks in advance!

**Comment by kaduk** [comment]
I was not planning to take the initiative on this issue, sorry.
I was hoping that you could write up a short description of why it is useful to have better support for the X509_REQ_INFO type, as there is a sustained maintenance cost for adding new things to the public API, and we don't want to incur that cost without knowing that there is some concrete benefit gained from it.
