### ISSUE TITLE
DESTDIR is not respected during make install

### ISSUE THREAD

**Issue by FireBurn** [openssl/openssl#4506]
When I configure OpenSSL 1.0.2l as follows:

./config --prefix=/directory/to/prefix --openssldir=/etc/pki/tls/ shared threads

make -j10

Doesn't work:

make DESTDIR=/temporary/install/folder install

It complains that folder /etc/pki/tls/man cannot be created when it should be creating /temporary/install/folder/etc/pki/tls/man

Works:

make INSTALL_PREFIX=/temporary/install/folder install

**Comment by mattcaswell** [comment]
I believe you are confusing the instructions between 1.0.2 and master/1.1.0. Lots of stuff changed between those versions. The behaviour you are describing above is as documented. In 1.0.2 see:

https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/INSTALL#L228

**Comment by levitte** [comment]
You should read the `INSTALL` that comes with the distribution.  See, things have changed between pre-1.1.0 OpenSSL and OpenSSL 1.1.0.  It's correct that with 1.0.2, `INSTALL_PREFIX` should be used ([as documented in the 1.0.2 `INSTALL`](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/INSTALL#L224-L232)).  We changed the name to `DESTDIR` for OpenSSL 1.1.0.

**Comment by FireBurn** [comment]
That's the bit I was missing - thanks :D
