### ISSUE TITLE
Addition of callback_arg to psk_client_callback functions

### ISSUE THREAD

**Issue by vineyyadav** [openssl/openssl#4510]
I want to receive a custom argument in the callback set via `SSL_set_psk_client_callback`. Currently, the callback provides with the `SSL*` but I have a scenario where I have more than one SSL clients to manage in a single application context. When the callback is called, I don't have a good way of knowing for which SSL Client this callback has been called.

Similar APIs to set the callback argument are available for another callback functions e.g. `SSL_set_msg_callback_arg`.

This request is for addition of APIs like `SSL_set_psk_client_callback_arg`, `SSL_CTX_set_psk_client_callback_arg`, `SSL_set_psk_server_callback_arg`, `SSL_CTX_set_psk_server_callback_arg`. The APIs will take a void* argument and store it in the `SSL`/`SSL_CTX` and pass it back when calling the callback.

**Comment by richsalz** [comment]
You can use the EXDATA in an SSL object to add your specific needs.  The problem with changing API of the callback function is that, well, it changes the API and we can't do that in a dot release.  Sorry, it was a goof to leave it out, but there is a workaround.
