### ISSUE TITLE
When sending the list of acceptable client cert issuers do not use the case ignore match to avoid duplicates

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#4512]
When OpenSSL creates the list of acceptable client cert issuers it avoids duplicates via the X509_NAME_cmp match. Unfortunately there are CAs that created CA certificates with DNs that differ only by the case of some characters. If the server wants to accept certificates issued by both CA certificates it will send only one of these DNs to the client. If the client is OpenSSL, it is not a problem, because it will again use X509_NAME_cmp match to match it and it will use a certificate which differs only by case happily. Unfortunately the widespread web browsers such as Firefox do not use the same algorithm and will not use such case-insensitively matching certificate to the server.

Would you accept pull request that would implement change of this behavior? I suppose changing the behavior of X509_NAME_cmp is not acceptable but different matching function can be used for creating the CA DN list.

**Comment by t8m** [comment]
Ping, did you have any chance to look at this to decide whether you would accept pull request as described above?

**Comment by mattcaswell** [comment]
How would the new algorithm work, and which branches would you target?

**Comment by t8m** [comment]
There are multiple options, but the simplest one I intended to implement is to simply compare the DER encoding of the names when creating the list of names to send.

The primary target branch would be master. It would be up to you to whether we should backport it also to stable branches and which ones.

**Comment by t8m** [comment]
@mattcaswell what is your opinion about this?

**Comment by mattcaswell** [comment]
I'm open to considering it on master. I am doubtful we would backport it. My main worry is - would this change of behaviour break anything?

**Comment by t8m** [comment]
OK, I'll prepare a pull request on master. I currently do not see how it could break anything however I might be overlooking something of course.

**Comment by mattcaswell** [comment]
Linked PR was merged so closing this.
