### ISSUE TITLE
ImportError: No module named urlgrabber

### ISSUE THREAD

**Issue by ZimmerHao** [openssl/openssl#453]
when i excute yum install openssl-devel on centos7 , it shows ImportError: No module named urlgrabber,
but when i install urlgrabber, it still show the same  error.

the steps i install urlgrabber is:
wget ftp://mirror.switch.ch/pool/4/mirror/scientificlinux/7.1/x86_64/os/Packages/python-urlgrabber-3.10-6.el7.noarch.rpm
sudo rpm -ivh python-urlgrabber-3.10-6.el7.noarch.rpm 

i think something wrong with the installation of urlgrabber, but how to install urlgrabber

**Comment by richsalz** [comment]
yum uninstall ?
This is not an openssl issue; closing.
