### ISSUE TITLE
compilation fail -- 1.0.1j no-tls option

### ISSUE THREAD

**Issue by bhaspurk** [openssl/openssl#4538]
Hello,
Apologies that this may have been addressed before, but I could not find a reason why this flag should not work.
I would like to build libssl such that it only supports TLSv1.2. Since it currently supports TLSv1.0 and TLSv1.1, security tools are complaining. 
As per this - https://rt.openssl.org/Ticket/Display.html?id=2788&user=guest&pass=guest, it seems like I should not be able to compile with this flag. 
Is there any other way to disable TLSv1.0 and 1.1 while building libssl?
Thank you

**Comment by kaduk** [comment]
First off, 1.0.1j is out of support -- the currently supported branches are 1.0.2 and 1.1.0.

Second, the "no-tls" option in 1.0.2 and previous releases controlled *all* versions of TLS, and it was not possible to compile out support for just TLS 1.0 and 1.1.  This has changed as of 1.1.0, where you can configure with no-tls1 and no-tls1_1 to leave just TLS 1.2 enabled.

Thirdly, it's generally recommended to leave the various TLS versions enabled at build time and disable the undesired ones at runtime, e.g., via SSL_CTX_set_min_proto_version().

And finally, you refer to the "no-tls" option but link to an old RT ticket that describes issues with "no-tlsext", an entirely different thing.
