### ISSUE TITLE
how to use openssl in xbox and ps4

### ISSUE THREAD

**Issue by cheimint** [openssl/openssl#4539]
Hi.
I wonder if openssl supports xbox and ps4.
install file only wrote "support Linux/windows family."
ps4 is based on linux, but a different. 
xbox is based on windows, but a different. 

I wonder how to build openssl for xbox/ps4
or 
I wonder if someone is using it in that environment.

**Comment by mattcaswell** [comment]
I'm not aware of anyone building in that environment. It might work it might not. You might have to play around with the build time configuration a bit to make it work.
