### ISSUE TITLE
Freeing an SSL BIO can result in "shutdown while in init" error

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#4545]
Freeing an SSL BIO should check whether we are still in the init stage before calling SSL_shutdown(), otherwise we will get a stale error on the error queue.

**Comment by bernd-edlinger** [comment]
Yes, and as we know SSL_shutdown can trap if previously an API function returned
an SSL_ERROR_SSL

**Comment by mattcaswell** [comment]
Not a 1.1.1 specific issue so removing that milestone.
