### ISSUE TITLE
Symlinks for manual page invocation

### ISSUE THREAD

**Issue by mukrop** [openssl/openssl#4548]
During an OpenSSL usability study we found out that many participants (more than a quarter) intuitively expected to find manual pages under `man openssl subcommand` (e.q. `man openssl verify`) instead of `man subcommand` (e.g. `man verify`). The experiment ran on Ubuntu 16.04.

This could be easily solved by symlinking the manual pages.
(This is already used elsewhere -- for example `man git commit` automatically redirects to `man git-commit` on Fedora.)

Although this is mostly a thing of the ports to the individual operating systems, the upstream project can probably ease the setting (as suggested by @richsalz).

**Comment by kaduk** [comment]
That's not the traditional man(1) behavior -- ```man foo bar``` first displays the manual for 'foo', then when the pager exits, displays the manual for 'bar'.  So this seems to be either a distro-specific issue or a user education/expectation issue.

Additionally, it's not clear that having symlinks would be helpful for all packagers -- FreeBSD, for example, uses hard links for manual pages, so having upstream OpenSSL ship symlinks would just cause extra work for the FreeBSD packagers.

So, at present, I believe that this issue is best addressed by distro packagers and not in OpenSSL proper.  (But I will leave the issue open for a bit in case there is more to say.)

**Comment by mukrop** [comment]
I was describing a developer expectation behavior. We gave tasks to attendees of an international dev conference and over a quarter of the participants (~25/100 people) expected to find the man page under `man openssl verify` (the only variant used more was the correct one with things such as `man openssl-verify` and `man openssl.verify` present only marginally).

Though, this is only a suggestion. Feel free to close it, if it's not widely deployable. I opened the issue based on the recommendation from @richsalz to spark the discussion.

**Comment by mattcaswell** [comment]
To expect to see something from `man openssl-verify` seems fairly reasonable to me (more reasonable than `man verify` which is what we have now).

**Comment by kaduk** [comment]
I'm not opposed to having us ship something that ```man openssl-verify``` picks up on.

**Comment by levitte** [comment]
Actually, it isn't terribly difficult to add those symlinks, and they do make sense.  I assume this is only for the `man1` section, right?

**Comment by mattcaswell** [comment]
Right.

**Comment by richsalz** [comment]
Perhaps something like
```
openssl help verify
openssl man verify
```
which just exec's the right man command?  Like git's ```git help branch``` does ```man git-branch```

**Comment by levitte** [comment]
@richsalz that still requires symlinks like `openssl-verify.1` to be present ;-)

**Comment by richsalz** [comment]
We already do links when we install the manpages in section 3.

**Comment by levitte** [comment]
Yes?

**Comment by richsalz** [comment]
So I mean, a minor update to the NAME section of almost all man1 files should do this.
See #4553.  And @mukrop, please tell us how to credit your work in the commit message.

**Comment by levitte** [comment]
I obviously over-complicated things, your solution was too obvious... :-)

**Comment by richsalz** [comment]
I have a simple mind.  :)  I'll merge once @mukrop tells us how to credit him.

**Comment by mukrop** [comment]
@richsalz, I'm not sure what exactly is needed. Name? Institution? Email?

**Comment by richsalz** [comment]
Whatever you want to provide.  It's just an acknowledgement to go into the commit message.  For example, "Recommended by a study conducted by Martin Ukrop" or similar.

**Comment by mukrop** [comment]
"Recommended by a usability study conducted by Martin Ukrop at CRoCS, FI MU." would be nice. Thanks.

**Comment by richsalz** [comment]
Argh.  I forgot to update the commit commit; sorry @mukrop .  But I did fix it for 1.0.2 commit.

**Comment by richsalz** [comment]
Merged to master, 1.1.0 and 1.0.2; thanks for the feedback.
