### ISSUE TITLE
OpenSSL 1.0.2* doesn’t preserve digests for SNI

### ISSUE THREAD

**Issue by masaori335** [openssl/openssl#4554]
SHA1 is always used as digest of signature algorithm, when `SSL_set_SSL_CTX()` is called for SNI.
We only see this issue with OpenSSL 1.0.2*. We don’t see this issue with 1.0.1* or 1.1.0*.

This was originally fixed by https://github.com/openssl/openssl/commit/4e05aedbcab7f7f83a887e952ebdcc5d4f2291e4  for 1.0.1* and https://github.com/openssl/openssl/commit/14e14bf6964965d02ce89805d9de867f000095aa for master. The change for master was cherry-picked to 1.0.2* (https://github.com/openssl/openssl/commit/1ce95f19601bbc6bfd24092c76c8f8105124e857) but it looks not enough.
IMO, it should copy `CERT_PKEY`s like the fix for 1.0.1* or negotiate signature algorithm from copied `peer_sigalgs` again.

**Comment by davidben** [comment]
Do you all call `SSL_set_SSL_CTX` in `SSL_CTX_set_cert_cb`'s callback by any chance? I haven't tested it but, from source inspection, it looks like the issue might be that 1.0.2 calls `tls1_set_server_sigalgs` *before* the certificate decisions are actually finalized by `cert_cb`. Either the `digest` decisions should be copied over as you suggest, or those should happen in the other order.

**Comment by masaori335** [comment]
> Do you all call SSL_set_SSL_CTX in SSL_CTX_set_cert_cb's callback by any chance?

Yes, we are. This is originally reported to Apache Traffic Server. ( https://github.com/apache/trafficserver/issues/2482 ) If you need details of how we call, please refer below.

https://github.com/apache/trafficserver/blob/3eb676e03a10cd71eb3d78b36d967b2957ac39cd/iocore/net/SSLUtils.cc#L1467

https://github.com/apache/trafficserver/blob/3eb676e03a10cd71eb3d78b36d967b2957ac39cd/iocore/net/SSLUtils.cc#L352

**Comment by davidben** [comment]
Ah okay. If my theory is right, I believe you'll find the OpenSSL bug no longer reproduces if you turn `TS_USE_CERT_CB` off and use the other callback. (But then you can't load the certificate asynchronously which seems to be why you all are [using cert_cb](https://mta.openssl.org/pipermail/openssl-dev/2015-January/000476.html).) That might explain why folks didn't notice the 1.0.2 backport was incomplete.

**Comment by masaori335** [comment]
Right. I don't see this issue after I turned off `TS_USE_CERT_CB`.

**Comment by masaori335** [comment]
This is fixed in 1.0.2m. Thanks!
