### ISSUE TITLE
Is openssl 1.0 incompatible with 1.1?

### ISSUE THREAD

**Issue by bhepple** [openssl/openssl#4585]
I encrypted a file using openssl with fedora-25/openssl-1.0. Now that I upgraded to -26/openssl-1.1, it fails to decrypt. Is that expected behaviour or a bug? Is there a fix?

Encrypting: openssl enc -blowfish < plaintext > cryptotext

Decrypting: openssl enc -d -blowfish < cryptotext

**Comment by mattcaswell** [comment]
The default digest changed between 1.0 and 1.1 from md5 (considered insecure) to sha256. Try adding "-md md5" to your decryption command.

**Comment by bhepple** [comment]
awesome! Thanks so much!

**Comment by richsalz** [comment]
https://www.openssl.org/docs/faq.html#USER3
