### ISSUE TITLE
Visual Studio warnings building for Windows CE

### ISSUE THREAD

**Issue by gjcoram** [openssl/openssl#4586]
I had four warnings (which are treated as errors in my setup) trying to compile OpenSSL 1.0.2l for Windows CE using Visual C++ 6.0 (Visual Studio 98).

1.
.\crypto\bio\b_print.c(505) : warning C4146: unary minus operator applied to unsigned type, result still unsigned

This was fixed in January in this patch:
https://github.com/openssl/openssl/commit/68d4bcfd0651c7ea5d37ca52abc0d2e6e6b3bd20#diff-c227518dd22bb40dadfbc0513c5c2d7f

but was apparently not backported to 1.0.2l (It's a little odd, because the patch to crypto\asn1\x_long.c was included in 1.0.2l.)

2.
.\crypto\evp\encode.c(294) : warning C4761: integral size mismatch in argument; conversion supplied

That line is now 270 in the master branch, and says
        v = conv_ascii2bin(tmp);
where tmp is declared as an integer on line 250.

Previously, tmp was declared an unsigned char.

Since "in" is "const unsigned char *in", it seems that this line:
        tmp = *(in++);
would indicate that tmp should be unsigned char, and I can't figure out why it was changed.

----------------------

3.
.\crypto\x509_v3\v3_scts.c(159) : warning C4244: 'function' : conversion from 'unsigned __int64 ' to 'long ', possible loss of data

That line is the last argument here:

    ASN1_GENERALIZEDTIME_adj(gen, (time_t)0,
                             (int)(timestamp / 86400000),
                             (timestamp % 86400000) / 1000); 

This file isn't on the master branch, and the last commit was in 2015. I have an old copy of the code that compiled OK, and it had

                             (long)((timestamp % 86400000) / 1000)); 

but I can't find the commit where that change was made.

----------------------

4.
.\ssl\d1_lib.c(578) : warning C4761: integral size mismatch in argument; conversion supplied.

This is in the function dtls1_set_handshake_header, which got moved to a different file in the master branch. What's in the code (in the 1.0.2 branch) now is
    dtls1_set_message_header(s, p, htype, len, 0, len);
whereas the previous code had
    dtls1_set_message_header(s, p, (unsigned char)htype, len, 0, len);

**Comment by richsalz** [comment]
You added that flag, right?  We don't support it.

**Comment by levitte** [comment]
Errr, @gjcoram, did you add a flag when configuring or did this happen with a default config?

**Comment by gjcoram** [comment]
What flag is that? I don't recall adding a flag, although I suppose there is a flag that says to treat warnings as errors. I would think it would be best to clean up the warnings, whether or not they are treated as errors.
I followed some directions years ago to get a config file for making OpenSSL DLLs and/or libs for use with an e-mail client, and the flags I remember adding were things to remove certain export-restricted encryption algorithms (perl Configure no-rc5 no-idea no-ec no-asm VC-WIN32).

**Comment by richsalz** [comment]
Yes, we agree it will be good to remove warnings.  The 1.1.0 branch, and later, goes a very long way to doing that.  There are still some problem areas in Windows builds, however.

I don't know what the flag is.  Please post the command-line or script you use to configure and build openssl.

**Comment by dot-asm** [comment]
> Windows CE using Visual C++ 6.0

And my question is what does it even mean. I mean does Visual C 6.0 actually support Windows CE? Well, it might not matter in the context, but it does make things utterly confusing. 1.0.2 used to compile cleanly by VC6, but apparently not anymore. VC6 is not supported by vendor, so on this ground alone this can be dismissed. Unless one compiles with newer compiler, confirms warnings and makes team choose between a) fixing warnings with newer compiler, or b) claiming that warnings are safe to ignore and omit /WX flag from util/pl/VC-32.pl.

**Comment by gjcoram** [comment]
I build OpenSSL for Windows CE 2.0 and 2.11, to support a mail client (nPOPuk) that runs on handheld PCs (Jornada 720/728/820, and others). I got the Windows CE Toolkit which I suppose provided the SDK for WinCE. I have to admit, that was 15+ years ago, and I've been mainly dumping in the new source code.

I had originally configured OpenSSL with this:
perl Configure no-rc5 no-idea no-ec no-asm VC-WIN32
and I didn't add any flags. It looks like dot-asm is saying that the /WX flag is part of the standard configuration, not something I added.

As to whether the warnings are only "valid" if a new compiler complains, I do think at least point 2, where "tmp" was changed from unsigned char to int, but then gets its value from unsigned char *in, is a valid warning.

**Comment by dot-asm** [comment]
> I build OpenSSL for Windows CE 2.0 and 2.11, to support a mail client (nPOPuk) that runs on handheld PCs (Jornada 720/728/820, and others).

And Jornada is powered by ARM processor, so VC6 compiler can't possibly help, because it targets x86. I'm also surprised that VC-WIN32 worked, VC-CE is the one that it meant to work with CE.

> As to whether the warnings are only "valid" if a new compiler complains

That's not exactly what I meant to say. I meant it wouldn't be a productive way to spend resources if we pay attention to unsupported compilers. And that the only feasible way to move forward here is to make identical case with newer compiler. And it probably doesn't have to be CE, just 32-bit Windows would do.

**Comment by dot-asm** [comment]
> It looks like dot-asm is saying that the /WX flag is part of the standard configuration, not something I added.

Wait a sec! It looks like I've mislead readers. /WX was part of VC-WIN32 target for quite a while, but when double-checked I don't see it anymore in 1.0.2. So that team has already take position on ignoring warnings from 32-bit VC... But the option is still there for VC-CE, but it's asserted that it's VC-WIN32 that was used... So things are still confusing and even getting more so...

**Comment by gjcoram** [comment]
My apologies ... I built/configured both VC-WIN32 and VC-CE. I know I originally compiled just the DLLs, and then I made some changes to compile libs so I could statically link, but that was 15+ years ago, and I don't remember what that change was. And I know a couple times when the code was updated, something else broke (eg, I think fips didn't work when I first tried compiling whatever version it was that started supporting that). So, I've been lazy about re-running configure.
I am sure it's VC6 with the Windows CE Toolkit, which provides the ARM (and MIPS, SH3, and SH4) cross-compilation. I also have eMbedded Visual C++ 3.0, but I suspect that's also not supported.

**Comment by gjcoram** [comment]
OK, so I also have VS 2005 installed; same warning:


C:\Users\gjcoram\Documents\VisualStudio>vcvars32
Setting environment for using Microsoft Visual Studio 2005 x86 tools.

C:\Users\gjcoram\Documents\VisualStudio\npop\openssl>nmake -f ntlib.mak

Microsoft (R) Program Maintenance Utility Version 8.00.50727.762
Copyright (C) Microsoft Corporation.  All rights reserved.

Building OpenSSL
        cl /Fotmp32\b_print.obj  -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_NO_IDEA -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_EC -DOPENSSL_NO_ECDSA -DOPENSSL_NO_ECDH -DOPENSSL_NO_GOST -DOPENSSL_NO_JPAKE -DOPENSSL_NO_DYNAMIC_ENGINE /Zl /Zi /Fdtmp32/lib -c .\crypto\bio\b_print.c
b_print.c
.\crypto\bio\b_print.c(505) : warning C4146: unary minus operator applied to unsigned type, result still unsigned

**Comment by gjcoram** [comment]
Ah, sorry, the b_print.c issue was already corrected. I checked the other 3 files I got warnings from, this time using VS2005, and two of them don't give warnings in the newer compiler. I'm still curious why the change in encode.c (from unsigned char to int) was done, but I understand you don't want to spend time on obsolete compilers.

I do still get a warning from v3_scts.c:
.\crypto\x509v3\v3_scts.c(159) : warning C4244: 'function' : conversion from 'unsigned __int64' to 'long', possible loss of data




C:\Users\gjcoram\Documents\VisualStudio\npop\openssl>del tmp32\encode.obj

C:\Users\gjcoram\Documents\VisualStudio\npop\openssl>del tmp32\v3_scts.obj

C:\Users\gjcoram\Documents\VisualStudio\npop\openssl>del tmp32\d1_lib.obj

C:\Users\gjcoram\Documents\VisualStudio\npop\openssl>nmake -f ntlib.mak

Microsoft (R) Program Maintenance Utility Version 8.00.50727.762
Copyright (C) Microsoft Corporation.  All rights reserved.

Building OpenSSL
        cl /Fotmp32\encode.obj  -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_NO_IDEA -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_EC -DOPENSSL_NO_ECDSA -DOPENSSL_NO_ECDH -DOPENSSL_NO_GOST -DOPENSSL_NO_JPAKE -DOPENSSL_NO_DYNAMIC_ENGINE /Zl /Zi /Fdtmp32/lib -c .\crypto\evp\encode.c
encode.c
        cl /Fotmp32\v3_scts.obj  -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_NO_IDEA -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_EC -DOPENSSL_NO_ECDSA -DOPENSSL_NO_ECDH -DOPENSSL_NO_GOST -DOPENSSL_NO_JPAKE -DOPENSSL_NO_DYNAMIC_ENGINE /Zl /Zi /Fdtmp32/lib -c .\crypto\x509v3\v3_scts.c
v3_scts.c
.\crypto\x509v3\v3_scts.c(159) : warning C4244: 'function' : conversion from 'unsigned __int64' to 'long', possible loss of data
        lib /nologo /out:out32\libeay32.lib @C:\Users\gjcoram\AppData\Local\Temp
\nmF81D.tmp
fips_ers.obj : warning LNK4221: no public symbols found; archive member will be inaccessible
        cl /Fotmp32\d1_lib.obj  -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_NO_IDEA -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_EC -DOPENSSL_NO_ECDSA -DOPENSSL_NO_ECDH -DOPENSSL_NO_GOST -DOPENSSL_NO_JPAKE -DOPENSSL_NO_DYNAMIC_ENGINE /Zl /Zi /Fdtmp32/lib -c .\ssl\d1_lib.c
d1_lib.c
        lib /nologo /out:out32\ssleay32.lib @C:\Users\gjcoram\AppData\Local\Temp
\nmFD5B.tmp

C:\Users\gjcoram\Documents\VisualStudio\npop\openssl>

**Comment by dot-asm** [comment]
See #4718.

**Comment by gjcoram** [comment]
Thanks.
