### ISSUE TITLE
ecp_nistz256-x86_64.asm

### ISSUE THREAD

**Issue by Advanium** [openssl/openssl#459]
I've been trying to build OpenSSL from the master branch using the MSVC14 tool chain and ran into the following error:

![openssl-amd64_x86](https://cloud.githubusercontent.com/assets/515866/10832775/a4b6f6ba-7e8d-11e5-804f-2274514e0816.png)

Could you please provide instructions on how to get this to work?

**Comment by mattcaswell** [comment]
Please try again using nasm.
