### ISSUE TITLE
certificate request file (.csr) is not generated by openSSL, why?

### ISSUE THREAD

**Issue by ziath** [openssl/openssl#4598]
Hello,

I am new to openSSL. I need to create a .csr file from openSSL to order a new certificate to my win10 computer. I did following as below.

In the demo directory I dont see the "ziath.ipa.xxx-net.net.csr" file.

What did I do wrong?
Appreciate any help.

Regards

Ziath

```
cd \demo
set RANDFILE=c:\demo\.rnd
set OPENSSL_CONF=C:\OpenSSL-Win32\bin\openssl.cfg
c:\OpenSSL-Win32\bin\openssl.exe

OpenSSL> req -new -newkey rsa:2048 -keyout ziath.ipa.xxx-net.net.key -out \ziath.ipa.xxx-net.net.csr
Generating a 2048 bit RSA private key
......................................+++
.......................+++
writing new private key to 'ziath.ipa.xxx-net.net.key'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:BN
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:xxx
Organizational Unit Name (eg, section) []:IN
Common Name (e.g. server FQDN or YOUR name) []:ziath.ipa.xxx-net.net
Email Address []:ziath.fernando@xxx.com

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
```

**Comment by levitte** [comment]
I think you'll find it in `c:\`, because if the backslash in `-out \ziath.ipa.xxx-net.net.csr`

**Comment by ziath** [comment]
Hi levitte,
thanks a lot for your kind advice. However I couldn't locate the file ziath.ipa.xxx-net.net.csr in c:\. So I re ran the command so that the file is saved in demo. 

cd \demo
set RANDFILE=c:\demo\.rnd
set OPENSSL_CONF=C:\OpenSSL-Win32\bin\openssl.cfg
c:\OpenSSL-Win32\bin\openssl.exe

OpenSSL> req -new -newkey rsa:2048 -keyout ziath.ipa.xxx-net.net.key -out c:\demo\ziath.ipa.xxx-net.net.csr

Then I notice following files in c:\demo

.rnd   				31/10/2017 9:49 AM	RND file
ziath.ipa.xxx-net.net		31/10/2017 9:50 AM	CSR file
ziath.ipa.xxx-net.net		31/10/2017 9.49 AM	KEY file


As the final confirmation I need to do following to check if the .csr file is correct.
req -in c:\demo\ziath.ipa.xxx-net.net.csr -text -noout

But then I get this error.
OpenSSL> req -in c:\demo\ziath.ipa.xxx-net.net.csr -text -noout
problem creating object tsa_policy1=1.2.3.4.1
7480:error:08064066:object identifier routines:OBJ_create:oid exists:crypto\objects\obj_dat.c:689:
error in req

Then I tried below as the .csr file don't show that .csr
Then I get following error.
OpenSSL> req -in c:\demo\ziath.ipa.xxx-net.net -text -noout
req: Cannot open input file c:\demo\ziath.ipa.xxx-net.net, No such file or directory
req: Use -help for summary.

I appreciate any advice for me to figure out what did I do wrong.  

Regards

Ziath

**Comment by levitte** [comment]
Perhaps you shouldn't forget to have the whole file name in the last command...  `c:\demo\ziath.ipa.xxx-net.net` isn't the same as `c:\demo\ziath.ipa.xxx-net.net.csr`

**Comment by ziath** [comment]
Hi levitte,

Thanks for your assistance in helping me.
I re-did the all the sequence once more as follows.
I couldn't get my last step of verification of the .scr file correctly.

Could you please check what went wrong?

==========================================================
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\X1>cd \demo
C:\demo>set RANDFILE=c:\demo\.rnd
C:\demo>set OPENSSL_CONF=C:\OpenSSL-Win32\bin\openssl.cfg
C:\demo>c:\OpenSSL-Win32\bin\openssl.exe
OpenSSL> req -new -newkey rsa:2048 -keyout ziath.ipa.xxx-net.net.key -out c:\demo\ziath.ipa.xxx-net.net.csr
Generating a 2048 bit RSA private key
...........+++
...................+++
writing new private key to 'ziath.ipa.xxx-net.net.key'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:BN
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:Kg Serusop
Organization Name (eg, company) [Internet Widgits Pty Ltd]:xxx
Organizational Unit Name (eg, section) []:ION
Common Name (e.g. server FQDN or YOUR name) []:ziath.ipa.xxx-net.net
Email Address []:ziath.nazoordeen@xxx.com

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:

+++++++++++++++++++++++++++++
below is how c:\demo directory looks like.

.rnd 02/11/2017 12:16 PM	RND file
ziath.ipa.xxx-net.net	02/11/2017 12:18 PM	CSR file
ziath.ipa.xxx-net.net	02/11/2017 12:16 PM	KEY file

+++++++++++++++++++++++++++++++++++++

OpenSSL> req -in c:\demo\ziath.ipa.xxx-net.net.csr -text -noout
problem creating object tsa_policy1=1.2.3.4.1
3348:error:08064066:object identifier routines:OBJ_create:oid exists:crypto\objects\obj_dat.c:689:
error in req
OpenSSL>

**Comment by levitte** [comment]
Ooooohhhh!  *That* was an intricate bug.

What's happening is that since you're using `openssl` as a shell so to speak, the first `req` has already loaded the OIDs from `openssl.cnf`, and the second `req` tries to load the same `openssl.cnf`, create the OIDs again, and gets an error because they're already present in the runtime.

If you start fresh and *only* do the second `req`, I think you'll have better luck.

`openssl` more often run with its arguments directly on the command line, like this:

```
C:\demo>c:\OpenSSL-Win32\bin\openssl.exe req -new -newkey rsa:2048 -keyout ziath.ipa.xxx-net.net.key -out c:\demo\ziath.ipa.xxx-net.net.csr
C:\demo>c:\OpenSSL-Win32\bin\openssl.exe req -in c:\demo\ziath.ipa.xxx-net.net.csr -text -noout
```

**Comment by ziath** [comment]
Hi levitte,

It works. Thanks for your support and advice.

Regards

Ziath

**Comment by levitte** [comment]
You're welcome :-)
