### ISSUE TITLE
Building libcrypto with only SHA-1 (for use with EVP functions)

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4599]
1. How can I exclude everything from a libcrypto.a build other than SHA-1/EVP? There are a lot of "no-" configuration options. The question is, which ones do I need exactly, and do these indeed exclude everything other than SHA-1/EVP?

2. Which header files do I need for only SHA-1/EVP? I want to remove all unneeded header files.

**Comment by richsalz** [comment]
Are you building only a crypto library and you only want SHA1?   Is that only the digest, or do you want to leave out all encryption (RSA, ECC, etc) as well?  If the answer to both is yes, then you might it easier to pull files out into a new library.

**Comment by snap9** [comment]
@richsalz I want to use SHA-1 (with EVP) in OpenSSL. I need nothing else in OpenSSL.

**Comment by snap9** [comment]
I'd prefer building existing OpenSSL over pulling out files manually (sounds tedious). The question is how to build as small size libcrypto.a as possible.

**Comment by kaduk** [comment]
Small size of the finished library was not a design goal for OpenSSL, so there is a pretty limited amount of low-hanging fruit, here.  If size is a strong concern for your project, then an alternate crypto library designed for embedded use may be more appropritae.

**Comment by richsalz** [comment]
Sorry, but we don't support what you want to do.  There are too many other things intertwined, and some probably don't even have the necessary ifdef wrappers.  You could start with a configured and built library and use "nm -o libcrypto.a" (on a Unix-type system) to figure out what files are needed.

Also, note that if you statically link your application, then the size of the library does not matter much, only the needed functions will be pulled in; that might be small enough for you.

**Comment by kaduk** [comment]
> Also, note that if you statically link your application, then the size of the library does not matter much, only the needed functions will be pulled in; that might be small enough for you.

I think you need to use ```-ffunction-sections``` and ``--gc-sections``` to get exactly that benefit; the "normal" linker operation would just be at object file granularity.  But yes, that's another reasonable option if the scenario permits it.

**Comment by snap9** [comment]
Thanks, that helps a lot :)
