### ISSUE TITLE
bn.h: Warning: Parameter 'a' not found in the function declaration

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4601]
`bn.h` in openssl-1.1.0f. My compiler is warning me in this code

    /** BN_is_negative returns 1 if the BIGNUM is negative
     * \param  a  pointer to the BIGNUM object
     * \return 1 if a < 0 and 0 otherwise
     */
    int BN_is_negative(const BIGNUM *b);

that `\param a` should be changed to `\param b`.

**Comment by kaduk** [comment]
Already fixed in 28c0a61b3084ca05d1c590113332501e96b6175d (master) and 8bd108a0042a75cca34de4f803f6aa62299d0463 (OpenSSL_1_1_0-stable), and will be in the next release.
