### ISSUE TITLE
Are all these options a function of the CPU architecture - as opposed to the SDK?

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4609]
In `Configurations/10-main.conf`:

    "darwin64-x86_64-cc" => {
        inherit_from     => [ "darwin-common", asm("x86_64_asm") ],
        cflags           => add("-arch x86_64 -DL_ENDIAN -Wall"),
        bn_ops           => "SIXTY_FOUR_BIT_LONG",
        perlasm_scheme   => "macosx",
        shared_ldflag    => "-arch x86_64 -dynamiclib",
    },

Were every single one of `x86_64_asm`, `DL_ENDIAN `, `SIXTY_FOUR_BIT_LONG `, and `perlasm_scheme   => "macosx"` chosen only because of the x86_64 architecture -- as opposed to because of the macOS SDK?

Similarly here:

    "ios64-cross" => {
        inherit_from     => [ "darwin-common", asm("aarch64_asm") ],
        cflags           => add("-arch arm64 -mios-version-min=7.0.0 -isysroot \$(CROSS_TOP)/SDKs/\$(CROSS_SDK) -fno-common"),
        sys_id           => "iOS",
        bn_ops           => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
        perlasm_scheme   => "ios64",
    },

Were every single one of `aarch64_asm `, `SIXTY_FOUR_BIT_LONG `, `RC4_CHAR `, `perlasm_scheme   => "ios64"` chosen only because of the arm64 architecture -- as opposed to because the iOS SDK?

I'm trying to understand which settings are due to architecture and which due to SDK.

**Comment by kroeckx** [comment]
All the ones you mention are CPU specific, except the perlasm_scheme which is toolchain specific.

**Comment by snap9** [comment]
@kroeckx Thank you! What about `shared_ldflag    => "-arch x86_64 -dynamiclib"`? Does this affect static libraries in any way? (My guess it only affects shared libraries, but I thought I'd make sure.)

**Comment by kroeckx** [comment]
The first part seems to tell the linker which architecture it's
for, the second probably that it needs to make a shared library,
but I'm really not sure. But it at least looks toolchain specific.

**Comment by dot-asm** [comment]
CPU- vs. toolchain-specific is not exactly adequate division. The mesh is *three*-dimensional: CPU, OS, compiler. As far as assembly modules go, they are maintained CPU-specific but OS- and compiler-neutral. C code is primarily neutral, but has some CPU-specific sections (inline assembly) and some OS-specific sections (e.g. `#ifdef _WIN32` or `#ifdef __linux`). Build system is supposed to tie everything up in compiler/toolchain-specific manner.
