### ISSUE TITLE
Undefined symbols for architecture x86_64 for SHA1

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [openssl/openssl#4611]
Just installed the library on my MAC with brew.
I'm trying to make sha1 hash in my C program. I included the file `/usr/local/opt/openssl/include/openssl/sha.h`
When I'm trying to compile with the command `gcc -Wall -o socketserver socketserver.c -v` it throws the next error:

Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name socketserver.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -Wall -fdebug-compilation-dir /Users/stakantin/server/hoofgage -ferror-limit 19 -fmessage-length 133 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/ct/7vvq9gx949xczw98mzy38x4c0000gn/T/socketserver-dec712.o -x c socketserver.c
clang -cc1 version 9.0.0 (clang-900.0.38) default target x86_64-apple-darwin16.7.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.12.0 -o socketserver /var/folders/ct/7vvq9gx949xczw98mzy38x4c0000gn/T/socketserver-dec712.o -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_SHA_Final", referenced from:
      _main in socketserver-dec712.o
  "_SHA_Init", referenced from:
      _main in socketserver-dec712.o
  "_SHA_Update", referenced from:
      _main in socketserver-dec712.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What I'm doing wrong and how to fix it?

**Comment by levitte** [comment]
Consider adding -lcrypto to your command line...

**Comment by kroeckx** [comment]
You don't seem to link with libcrypto. You probably need to add -L/usr/local/opt/openssl/lib -lcrypto

I also suggest you #include <openssl/sha.h> instead, and use -I/usr/local/opt/openssl/include/

The functions are called SHA1_*, not SHA_*.

You might also want to use the EVP interface instead of directly
using the SHA interface. See the manpage of EVP_DigestInit_ex

I also suggest you switch to SHA256 unless you really need to use
SHA1.

**Comment by KonstantinKolodnitsky** [comment]
Thanks @levitte It seems fixed the issue.

Thanks @kroeckx I have sha.h included already. And I have to use SHA1 because of 3rd party app requirement(for a handshake). I'll think about interface.

**Comment by ky2ninh** [comment]
It seems that CMake by Jetbrain CLion doesn't like any flavors of -lcrypto I tried. Anyone has what's working for CMake?

Haven't coded in C++ in 20 years and it shows.  

/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_BUILD_TYPE=Debug -lcrypto -G "CodeBlocks - Unix Makefiles" /Users/kninh/CLionProjects/abc
CMake Error: Unknown argument -lcrypto




/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_BUILD_TYPE=Debug -L/usr/local/Cellar/openssl/1.0.2s/lib -lcrypto -G "CodeBlocks - Unix Makefiles" /Users/kninh/CLionProjects/abc
CMake Error: Unknown argument -lcrypto



/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_BUILD_TYPE=Debug -L/usr/local/Cellar/openssl/1.0.2s/lib/libcrypto -G "CodeBlocks - Unix Makefiles" /Users/kninh/CLionProjects/abc
CMake Error: Unknown argument -L/usr/local/Cellar/openssl/1.0.2s/lib/libcrypto
