### ISSUE TITLE
Dictionary with oids for fuzzers

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4615]
I would like to have a dictionary for the fuzzers that has the OIDs in them. I've manually created one, but I would like to have one that's auto updated when new OIDs get added.

The one I generated looks like this:
```
# OIDs
"\x2A\x86\x48\x86\xF7\x0D"
"\x2A\x86\x48\x86\xF7\x0D\x01"
"\x2A\x86\x48\x86\xF7\x0D\x02\x02"
"\x2A\x86\x48\x86\xF7\x0D\x02\x05"
"\x2A\x86\x48\x86\xF7\x0D\x03\x04"
"\x2A\x86\x48\x86\xF7\x0D\x01\x01\x01"
"\x2A\x86\x48\x86\xF7\x0D\x01\x01\x02"
"\x2A\x86\x48\x86\xF7\x0D\x01\x01\x04"
"\x2A\x86\x48\x86\xF7\x0D\x01\x05\x01"
"\x2A\x86\x48\x86\xF7\x0D\x01\x05\x03"
```

In theory you can add a name before it, like:
OBJ_rsadsi="\x2A\x86\x48\x86\xF7\x0D"

I guess it would be nice, but it also works without.

It doesn't require normal characters to be hex escaped, but it was easy.

@levitte: Is this something you can do?

**Comment by levitte** [comment]
How would you like that dictionary?  We already have it, don't we, in form of the object database?  We just need to figure a way to extract them all at once...

**Comment by kroeckx** [comment]
The fuzzers (at least afl and libfuzzer) support the format I've
pointed to, so I would like to get a file in that format ...

**Comment by levitte** [comment]
Ah.  Ok, the attached perl script should do it nicely then.  Calling like this:

```
perl $SCRIPT crypto/objects/obj_dat.h > fuzzeroid
```

``` perl
#! /usr/bin/env perl
# Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the OpenSSL license (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

my $obj_dat_h = $ARGV[0];

open IN, '<', $obj_dat_h
    || die "Couldn't open $obj_dat_h : $!\n";

while(<IN>) {
    s|\R$||;                    # Better chomp

    next unless m|^\s+((0x[0-9A-F][0-9A-F],)*)\s+/\*\s\[\s*\d+\]\s(OBJ_\w+)\s\*/$|;

    my $OID = $1;
    my $OBJname = $3;

    $OID =~ s|0x|\\x|g;
    $OID =~ s|,||g;

    print "$OBJname=\"$OID\"\n";
}
close IN;
```

**Comment by richsalz** [comment]
I assume someone will make a PR to add this to the build :)  Maybe util/make-oid-fuzz or such for the script name?

**Comment by levitte** [comment]
I can easily do that, but then I wonder, how exactly do you want the result to be generated, @kroeckx?  Manually (with instructions from `fuzz/README.md`) or automatically as part of a build?

**Comment by kroeckx** [comment]
I guess the other files are generated as part of make update? So
at that time would be fine for me.


Kurt

**Comment by levitte** [comment]
@kroeckx, please have a look at #4637.
