### ISSUE TITLE
Only expose EVP interface for crypto primitives

### ISSUE THREAD

**Issue by kaduk** [openssl/openssl#4619]
We currently have a mix of the abstract EVP interface and direct functions for many (older) ciphers, hash functions, etc.  To make life easier on the library consumer (in terms of picking which API to use) and to make the library easier to maintain, we should only expose the abstract EVP interface and remove any existing lower-level APIs.

**Comment by levitte** [comment]
This will also greatly simplify the instrumentations, for example removing the somewhat convoluted relationship between them and engines

**Comment by paulidale** [comment]
@dot-asm suggested in #4616 the removal of the evp direct functions like `EVP_sha1` and instead rely on look ups by name.  I like this suggestion.

**Comment by t-j-h** [comment]
That will break a *lot* of code.

**Comment by richsalz** [comment]
Yeah, we can't remove them.

**Comment by mattcaswell** [comment]
> @dot-asm suggested in #4616 the removal of the evp direct functions like EVP_sha1 and instead rely on look ups by name. I like this suggestion.

I think that would be very difficult to justify. You could *possibly* say we won't add any new ones.

**Comment by levitte** [comment]
You haven't forgotten this discussion is for 1.2.0, right?

**Comment by dot-asm** [comment]
Quiting myself: "one might find it appropriate to compromise and say that those EVP_algo() that can't be disabled could be exported, but those which can be disabled shouldn't really."

**Comment by levitte** [comment]
> You could *possibly* say we won't add any new ones.

Is that a question we should ask ourselves re things we've added for 1.1.1?

**Comment by mattcaswell** [comment]
> You haven't forgotten this discussion is for 1.2.0, right?

Nope

**Comment by t8m** [comment]
We have already deprecated low level crypto APIs in 3.0. Removal will happen at some point. I do not think we need to have an issue open for that task though. Closing.
