### ISSUE TITLE
MDC2 disabled but mdc2dgst.c and mdc2_one build failed on windows.

### ISSUE THREAD

**Issue by wrenashe** [openssl/openssl#462]
<1.0.2d>
mdc2dgst.c
	cl /Fotmp32dll\mdc2_one.obj  -Iinc32 -Itmp32dll -DOPENSSL_NO_RC5 -DOPENSSL_NO_IDEA -DOPENSSL_NO_MD2 -DOPENSSL_NO_MDC2 -DNO_RAND_SCREEN -D_CRT_NON_CONFORMING_SWPRINTFS  /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -DOPENSSL_NO_RC5 -DOPENSSL_NO_IDEA -DOPENSSL_NO_MD2 -DOPENSSL_NO_MDC2 -DNO_RAND_SCREEN -D_CRT_NON_CONFORMING_SWPRINTFS -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_STATIC_ENGINE /Zi /Fdtmp32dll/lib -D_WINDLL  -DOPENSSL_BUILD_SHLIBCRYPTO -c .\crypto\mdc2\mdc2_one.c
mdc2_one.c
C:\cloverrel\cloverleaf-external\openssl-1.0.2d\inc32\openssl/mdc2.h(69) : fatal error C1189: #error :  MDC2 is disabled.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
make: *** [openssl-1.0.2d/out32dll/openssl.exe] Error 2

crypto/mdc2/**mdc2dgst.c** and **mdc2_one.c** missed preprocessor directives
```
#ifndef OPENSSL_NO_MDC2
:
:
#endif
```

**Comment by mattcaswell** [comment]
Looks like someone fixed this. At least I can't reproduce it with the latest 1.0.2 from git on Windows.
