### ISSUE TITLE
dclean in test deleting source files

### ISSUE THREAD

**Issue by robertyseward** [openssl/openssl#4621]
For openssl-1.0.2l, if I do the following in SuSE 42.2 (although I don't think the OS matters):

`  make dclean`
`  ./config shared zlib`
`  make`

then I get the failure:

`ssltestlib.o: In function 'main':`
`ssltestlib.c:(.text.startup+0x0): multiple definition of 'main'`
`dtlstest.o:dtlstest.c:(.text.startup+0x0): first defined here`
`dtlstest.o: In function 'test_dtls_unprocessed':`
`dtlstest.c:(.text+0x6f): undefined reference to 'create_ssl_ctx_pair'`
`dtlstest.c:(.text+0xb5): undefined reference to 'bio_f_tls_dump_filter'`
`dtlstest.c:(.text+0xe4): undefined reference to 'create_ssl_objects'`
`dtlstest.c:(.text+0x12e): undefined reference to 'mempacket_test_inject'`
`dtlstest.c:(.text+0x13d): undefined reference to 'create_ssl_connection'`
`collect2: error: ld returned 1 exit status`
`../Makefile.shared:171: recipe for target 'link_app.gnu' failed`

This is because dclean will remove ssltestlib.c, and the configure will cause it to be linked to dummytest.c.  Both dtlstest.c and dummytest.c have a `main()`, so we get a failure.

I believe that the root problem is that dclean in test is removing all files in `$(SRC)`, whereas it should only be removing those files that are links.  So, maybe instead of 

`  rm -f $(SRC) $(SHA256TEST).c $(SHA512TEST).c evptests.txt newkey.pem testkey.pem \`
`       testreq.pem`

do something like:

`  rm -f $(shell for f in $(SRC); do [ -L $$f ] && echo $$f; done) \`
`      (SHA256TEST).c $(SHA512TEST).c evptests.txt newkey.pem testkey.pem testreq.pem`

Or maybe:

`  DISTSRC= $(ASN1TEST).c $(IGETEST).c dummytest.c ssltestlib.c methtest.c r160test.c`
`  rm -f $(filter-out $(DISTSRC),$(SRC)) \`
`      (SHA256TEST).c $(SHA512TEST).c evptests.txt newkey.pem testkey.pem testreq.pem`

**Comment by enkidushane** [comment]
This issue still exists in 1.0.2o when making from source (on Ubuntu-16.04, btw).
Running "make clean" instead of "make dclean" leaves ssltestlib.c in place, and allows everything to be compiled without issue.

**Comment by t8m** [comment]
1.0.2 is out of regular support. Closing.
