### ISSUE TITLE
Are all the headers (apart from opensslconf.h) always exactly the same?

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4622]
For a given OpenSSL version, are all the include/openssl headers (apart from opensslconf.h) always exactly the same - no matter how we configure and compile (i.e., for all CPU architectures, toolchains, platforms, compilers, etc.)?

I'm pretty sure this is the case, but I wanted to make sure.

**Comment by richsalz** [comment]
There are ifdefs in the headers but the same headers for everything.  You could have looked :)

For the future, please ask questions on the openssl-users mailing list; see https://mta.openssl.org for details on joining.
