### ISSUE TITLE
Handshake gives error "wrong verion number"

### ISSUE THREAD

**Issue by zl950402** [openssl/openssl#4626]
I'm using this https://github.com/youngwolf-project/ascs/tree/master/examples/ssl_test

and when I restart client for 3 times. 
Client gives error "stream truncated" and 
Server gives error "336130315 wrong version number" and then "336130329 decryption failed or bad record mac"

Any idea? 

win7 x64  binary win32
Thanks :)

**Comment by mattcaswell** [comment]
Sounds like this is a query you should raise with the project at the link you gave. Decryption failed or bad record mac is usually an indicator that something fairly low level has gone wrong. You might want to use wireshark to see what is happening on the wire.
