### ISSUE TITLE
Apps doesn't compile if OPENSSL_NO_SOCK or OPENSSL_NO_OCSP are defined

### ISSUE THREAD

**Issue by mxmauro** [openssl/openssl#463]
The problem is caused by the `load_cert_crl_http` function in `apps.c` file. They call to undefined OCSP functions.

`load_cert_crl_http` and the call to this function should be enclosed in a `#ifdef/#endif` block.

Regards,
Mauro.

**Comment by richsalz** [comment]
apps don't build without sockets, but the no-ocsp issue is fixed in commit 5d32228  thanks.
