### ISSUE TITLE
"make test" fails for iOS build. How to run tests for iOS?

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4638]
Running this on my macOS works just fine:

    $ declare -x CROSS_COMPILE=`xcode-select --print-path`/Toolchains/XcodeDefault.xctoolchain/usr/bin/
    $ declare -x CROSS_TOP=`xcode-select --print-path`/Platforms/iPhoneOS.platform/Developer
    $ declare -x CROSS_SDK=iPhoneOS.sdk
    $ ./Configure no-shared ios64-cross
    $ make

However the tests fail miserably:

    $ make test
    ...
    Failed tests:  1, 7, 9-16, 27-28, 41-42, 44-47, 52-59
                71, 77-78, 80, 82, 85-86, 89, 91, 93, 95
                97, 99-101, 103, 105-106, 108-111
    ...
    Files=95, Tests=369, 14 wallclock secs ( 0.33 usr  0.17 sys +  9.01 cusr  3.69 csys = 13.20 CPU)
    Result: FAIL

Actually, this feels reasonable to me because it doesn't make any sense to take tests that were compiled for iOS and run them on macOS (totally different architectures).

So the question is, **how do I run the tests on iOS? For example, does OpenSSL provide a public C function for running the tests?**

**Comment by richsalz** [comment]
No, you have to move the whole setup over to the system being tested and run the perl scripts and other stuff there as well.

**Comment by snap9** [comment]
@richsalz Thanks for the info. It's pity because iPhone isn't meant as a dev machine. So this will probably be impossible without jailbreaking the device (and who wants to do that).

I guess our only remaining option is to write our own tests for whatever OpenSSL functionality we end up using in our apps.

**Comment by snap9** [comment]
@richsalz Actually, it looks like it won't be too hard to manually copy-paste code from the test .c files. For each test, it's just a matter of copying the code inside `main()` into another function and calling that function.

But like I said, it's a bit pity that each test's `main()` isn't calling such a reusable function in the first place - that would have allowed me to use that reusable function in code that can run on iOS :)

@kroeckx @dot-asm @levitte Maybe you find the above to be a good idea for future refactoring.

**Comment by levitte** [comment]
I think I recall doing similar things when I dealt with the FIPS module on small devices...  so yeah, could be an idea.

I'm not promising immediate action, I hope you understand that.

**Comment by snap9** [comment]
@levitte Fully understand. Keep up the good work on OpenSSL.
