### ISSUE TITLE
Why BUF_MEM_grow(_clean) can't make one last try with size 0x7fffffff ?

### ISSUE THREAD

**Issue by sverx** [openssl/openssl#464]
I mean, I understand we can't grow past 2^31, but why can't we grow to **exactly** that value?
(I mean when ((len + 3) / 3 * 4) would go past it)

```
if (len > LIMIT_BEFORE_EXPANSION) {
  if (len == HARD_LIMIT) {
    BUFerr(BUF_F_BUF_MEM_GROW_CLEAN, ERR_R_MALLOC_FAILURE);
    return (0);
   } else {
    n=HARD_LIMIT;
  }
}
else {
  n = (len + 3) / 3 * 4;
}
```

**Comment by richsalz** [comment]
what would be the point?  It's still not excatly what was asked for ...
