### ISSUE TITLE
Different output of 'openssl enc' by using OpenSSL_1_0_2-stable and OpenSSL_1_1_0-stable

### ISSUE THREAD

**Issue by jijianwen** [openssl/openssl#4640]
When using OpenSSL_1_0_2-stable
     # echo 'someTextIWantToEncrypt' | ./apps/openssl enc -base64 -e -aes-256-cbc -nosalt -pass pass:mySecretPass
Got the following output:
    KPkBkGJ9bs4YHvh24xz7m9jTlYWm1LcIFcWR0DwY4PU=

But when using OpenSSL_1_1_0-stable
    # echo 'someTextIWantToEncrypt' | ./apps/openssl enc -base64 -e -aes-256-cbc -nosalt -pass pass:mySecretPass

Got the following output:
qEVrLSGgA7/aGJtlsiR6v24fMwQCIIkFl4jBJgA+gso=

Please help check.

**Comment by levitte** [comment]
What  happens if you add `-md md5` to the command?

**Comment by jijianwen** [comment]
@levitte , got the same output by adding ` -md md5`

The output is:
KPkBkGJ9bs4YHvh24xz7m9jTlYWm1LcIFcWR0DwY4PU=

**Comment by levitte** [comment]
Good.

The reason you get a difference is that the default hash algo used to process the password has changed.  In pre 1.1.0, it was md5.  In 1.1.0, it was changed to sha256.  The `-md` option is used to specify the desired hash algo explicitely.

**Comment by jijianwen** [comment]
@levitte Thanks for your explanation!

**Comment by richsalz** [comment]
https://www.openssl.org/docs/faq.html#USER3
