### ISSUE TITLE
Failed test "In context empty records test" on debian-hurd

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4650]
It seems that on hurd sometimes the "In context empty records test" failed. Most of the time it's successful, but sometimes it fails. Example logs where it failed:
https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=hurd-i386&ver=1.1.0g-1&stamp=1509641755&raw=0
https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=hurd-i386&ver=1.1.0f-2&stamp=1496599867&raw=0

I want to note that on debian-hurd we've always had different timing than the other arches, it seems to be very good at triggering race conditions, for instance #4129 and #3562, so this might be an other case of a race condition.

**Comment by kroeckx** [comment]
This log also has various others errors in it:
https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=hurd-i386&ver=1.1.0g-1&stamp=1509651995&raw=0

**Comment by kroeckx** [comment]
I have no idea. I'm not able to reproduce the original problem on
a hurd system. So I guess I will only know if I actually make an
upload to Debian.

**Comment by mattcaswell** [comment]
So keep open for now or close?

**Comment by kroeckx** [comment]
Keep it open for now, I'll look at it again aat some later time.

**Comment by levitte** [comment]
Side note: should we have a hurd VM on our machinery?

**Comment by mattcaswell** [comment]
Not a 1.1.1 specific issue so removing that milestone.

**Comment by t8m** [comment]
Closing. Please reopen if you're still seeing TLSProxy related issues on Hurd.
