### ISSUE TITLE
Is it a mistake of openssl docs ? or a mistake of wiki page ?

### ISSUE THREAD

**Issue by oknet** [openssl/openssl#4657]
According to the openssl 1.1.0 docs, it said the EVP_CTRL_AEAD_SET_TAG is only legal and must before any data is processed.

https://www.openssl.org/docs/man1.1.0/crypto/EVP_CIPHER_CTX_ctrl.html

```
EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, taglen, tag);

Sets the expected tag to taglen bytes from tag. This call is only legal when decrypting data and must be made before any data is processed (e.g. before any EVP_DecryptUpdate() call). For OCB mode the taglen must either be 16 or the value previously set via EVP_CTRL_AEAD_SET_TAG.
```

But the sample codes shows different : https://wiki.openssl.org/index.php?title=EVP_Authenticated_Encryption_and_Decryption&oldid=2612

```
	/* Provide the message to be decrypted, and obtain the plaintext output.
	 * EVP_DecryptUpdate can be called multiple times if necessary
	 */
	if(!EVP_DecryptUpdate(ctx, plaintext, &len, ciphertext, ciphertext_len))
		handleErrors();
	plaintext_len = len;

	/* Set expected tag value. Works in OpenSSL 1.0.1d and later */
	if(!EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, 16, tag))
		handleErrors();

	/* Finalise the decryption. A positive return value indicates success,
	 * anything else is a failure - the plaintext is not trustworthy.
	 */
	ret = EVP_DecryptFinal_ex(ctx, plaintext + len, &len);
```

I found the wiki page is created by @mattcaswell  and @nkarstens is the last editor.

Is it a mistake of openssl docs ? or a mistake of wiki page ?

Thanks.

**Comment by mattcaswell** [comment]
This is a bug in the docs which was fixed in commit 9807f03e4. Actually the man page link you provided doesn't include that text any more, and its not in the docs in the latest 1.1.0 version that was released yesterday.
