### ISSUE TITLE
If prefix path contains spaces, make produces an error.

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4668]
I can successfully run

    ./Configure --prefix="/Users/snap9/Desktop/asdf1 asdf2" no-shared darwin64-x86_64-cc

Note the quoted path containing a space. Normally such paths work fine as long as they are quoted. (By the way, the folder "asdf1 asdf2" does indeed exist on my Desktop.)

However, when running `make` I get this error:

    clang: error: no such file or directory: 'asdf2/ssl"'
    clang: error: no such file or directory: 'asdf2/lib/engines-1.1"'
    make[2]: *** [link_app.] Error 1
    make[1]: *** [apps/openssl] Error 2
    make: *** [all] Error 2

Is there a way to solve this other than to escape the space with a `\`? **Update:** Not even escaping the space works. Same error. Hmm.

**Comment by levitte** [comment]
Would you mind telling us the exact `make` command line, and give us more of the output?  (oh, and if you run make with the `-s` flag, please skip it, so we can see the command lines that are attempted)

I assume we're talking about 1.1.0 or master?

**Comment by snap9** [comment]
I ran only `make` (no arguments). Here are more lines preceding the error:

    cc  -I. -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/snap9/Desktop/asdf1 asdf2/ssl\"" -DENGINESDIR="\"/Users/snap9/Desktop/asdf1 asdf2/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall   -MMD -MF apps/ts.d.tmp -MT apps/ts.o -c -o apps/ts.o apps/ts.c
    cc  -I. -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/snap9/Desktop/asdf1 asdf2/ssl\"" -DENGINESDIR="\"/Users/snap9/Desktop/asdf1 asdf2/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall   -MMD -MF apps/verify.d.tmp -MT apps/verify.o -c -o apps/verify.o apps/verify.c
    cc  -I. -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/snap9/Desktop/asdf1 asdf2/ssl\"" -DENGINESDIR="\"/Users/snap9/Desktop/asdf1 asdf2/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall   -MMD -MF apps/version.d.tmp -MT apps/version.o -c -o apps/version.o apps/version.c
    cc  -I. -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/snap9/Desktop/asdf1 asdf2/ssl\"" -DENGINESDIR="\"/Users/snap9/Desktop/asdf1 asdf2/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall   -MMD -MF apps/x509.d.tmp -MT apps/x509.o -c -o apps/x509.o apps/x509.c
    rm -f apps/openssl
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f ./Makefile.shared -e \
    		PERL="perl" SRCDIR=. \
    		APPNAME=apps/openssl OBJECTS="apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o" \
    		LIBDEPS='-Wl,-search_paths_first '" -L. -lssl -L. -lcrypto"' ' \
    		CC='cc' CFLAGS='-DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/snap9/Desktop/asdf1 asdf2/ssl\"" -DENGINESDIR="\"/Users/snap9/Desktop/asdf1 asdf2/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall  ' \
    		LDFLAGS='' \
    		link_app.
    ( :; LIBDEPS="${LIBDEPS:--Wl,-search_paths_first  -L. -lssl -L. -lcrypto }"; LDCMD="${LDCMD:-cc}"; LDFLAGS="${LDFLAGS:--DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/snap9/Desktop/asdf1 asdf2/ssl\"" -DENGINESDIR="\"/Users/snap9/Desktop/asdf1 asdf2/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall   }"; LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`; LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`; echo LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=apps/openssl} apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o ${LIBDEPS}; LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=apps/openssl} apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o ${LIBDEPS} )
    LD_LIBRARY_PATH=.: cc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/Users/snap9/Desktop/asdf1 asdf2/ssl" -DENGINESDIR="/Users/snap9/Desktop/asdf1 asdf2/lib/engines-1.1" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall -o apps/openssl apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o -Wl,-search_paths_first -L. -lssl -L. -lcrypto
    clang: error: no such file or directory: 'asdf2/ssl"'
    clang: error: no such file or directory: 'asdf2/lib/engines-1.1"'
    make[2]: *** [link_app.] Error 1
    make[1]: *** [apps/openssl] Error 2
    make: *** [all] Error 2

**Comment by snap9** [comment]
By the way, I'm on macOS Sierra 10.12.6 doing the build with Xcode 9 command line tools.

**Comment by levitte** [comment]
Space is our nemesis...  you're right, we're fragile there, specifically on Unix like systems (I think we've gotten all the kinks out of this on Windows).  I suggest avoiding it for the time being.

**Comment by levitte** [comment]
There are definitely possible fixes, more or less invasive.  None of them are quick fixes, though...

**Comment by snap9** [comment]
@levitte Ok, thanks for the info :)

**Comment by mattcaswell** [comment]
@levitte - what should happen with this issue? Is the milestone correct?

**Comment by levitte** [comment]
Well, you could say that the milestone is correct, but at the same time irrelevant.  In 1.1.1, we're rid of `Makefile.shared`, which means that *if this is still an issue* (I hope not), it's in a different place altogether.  In other words, this is a 1.1.0 issues, and setting a milestone here is irrelevant.  A 1.1.0 label is a better choice.

**Comment by t8m** [comment]
Closing as this is an issue in an unsupported branch.

**Comment by littlebowlnju** [comment]
This issue is  opened in 2017, I wonder if this issue solved at all now cause I meet the same problem now in 2022.
And i am so desperate to find a solution but cannot. (renaming the path is not a solution to me😢😢😢)

Can anyone show me some light😭😭😭

**Comment by t8m** [comment]
What branch are you trying to build @littlebowlnju ?

**Comment by vanyauhalin** [comment]
I encountered the same problem while attempting to build Ruby from sources. After multiple attempts to resolve the issue of the compiler's inability to handle a path with spaces, I made a different decision. I created a symlink with a name that doesn't contain spaces, pointing to a directory that does. Surprisingly, this approach worked.

```fish
#/bin/fish

set -gx XDG_DATA_HOME "$HOME/Library/Application-Support-Alias"
set -gx XDG_DATA_HOME_BACKPORT "$HOME/Library/Application Support"

if not test -e $XDG_DATA_HOME
	command ln -s $XDG_DATA_HOME_BACKPORT $XDG_DATA_HOME
end
```

**Comment by jamuir** [comment]
I have done some work on this issue and have just opened a PR.
