### ISSUE TITLE
Single interface for reading private/public key

### ISSUE THREAD

**Issue by jeroenooms** [openssl/openssl#467]
Is there an EVP read function for `der` data that understands both public and private keys? I currently use `d2i_PrivateKey_bio` and `d2i_PUBKEY`, but this requires the user to specify if the key is public or private. It would be really nice to have a generic function to convert `der` into `EVP_PKEY` that works for both public or private keys.

Similar question for `PEM_read_bio_PUBKEY` and `PEM_read_bio_PrivateKey`, although in this case I can easily figure it out myself by inspecting the pem header.

**Comment by devendermishrajio** [comment]
DER/BER format is binary format. In PEM format, it is explicitly mentioned that key is of x type. But not in DER/BER as their ASN1.1 syntax does not have scope for mentioning type of key in their header. Hence, user must be aware of the type of the key.

There is no function for DER data. For such functions for DER data, they will need full parsing of the data and then it can be determined the type of key and then allocate the object.

Regarding PEM_read_bio_PUBKEY/PrivateKey, public key and private key are different. I do not see any reason to use public key and private key alternatively in a program. In asymmetric encryption, you should be aware that what type of key was used to encrypt this data. And in every case, you cannot send private key to tell that this was used to encrypt the data.

Please explain your use-case for the need of same interface to read private and public key.

**Comment by richsalz** [comment]
"no" :)
