### ISSUE TITLE
openssl dhparam - verify destination is writeable 

### ISSUE THREAD

**Issue by Leryan** [openssl/openssl#4671]
Hi,

I just generated some DH params, the process took a fair amount of time. I copy/pasted the command from another machine for generation on another but didn't change the destination file path.

This is clearly a [pebkac](https://en.wikipedia.org/wiki/User_error) but why not checking if destination path is writeable before generation?

**Comment by FdaSilvaYY** [comment]
WIP: see #904

**Comment by Leryan** [comment]
Nice, thank you :)
