### ISSUE TITLE
openssl in interactive mode doesn't clean up between commands

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#4679]
When running `openssl` in interactive mode, things aren't properly cleaned up between commands (see #4598 for an example).

In pre-1.1.0, every sub command did itss own initialization and cleanup explicitely.  With 1.1.0 and on, initialization is done automatically in libcrypto and libssl, and cleanup is done at program exit.  It *is* possible to do an explicit `OPENSSL_cleanup`, but reinitializing is not possible.

This makes interactive mode unusable for more than the simplest sub-commands.

**Comment by FdaSilvaYY** [comment]
While thinking at this, I remember that there is a bunch of global variables.
Most of the commands don't clear/init these global vars at its startup ( s_server is one exception I recall).
So, one could end-up with some remaining settings from one command while launching another .
Behavior inherited from 1.0.2, I suppose.

**Comment by mattcaswell** [comment]
This isn't going to be fixed in the 1.1.1 timeframe. Moving to post 1.1.1
