### ISSUE TITLE
would you add interface for Base64?

### ISSUE THREAD

**Issue by jtbuaa** [openssl/openssl#469]

**Comment by levitte** [comment]
Like this? 

http://openssl.org/docs/man1.0.2/crypto/BIO_f_base64.html

**Comment by mattcaswell** [comment]
You can also use (the unfortunately undocumented :-( ) function EVP_EncodeBlock, or (for larger amounts of data, and also undocumented :-( ) functions EVP_EncodeInit, EVP_EncodeUpdate and EVP_EncodeFinal.

**Comment by benlaurie** [comment]
Then the bug is lack of documentation. :-)

**Comment by mattcaswell** [comment]
True...

**Comment by jtbuaa** [comment]
Ah, I see. thank you
