### ISSUE TITLE
Documentation for CRYPTO_thread_glock_new() is missing

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#4707]
The function was added to the public interface in PR #4294, but documentation is missing.

**Comment by mspncp** [comment]
The original reason why I was looking for the documentation was because I was unsure about the differences between using `CRYPTO_thread_glock_new()` vs.  `CRYPTO_thread_lock_new()`.

But now I learned that @kaduk intends to remove the function again (PR #4321). What's the current state of this PR?

**Comment by richsalz** [comment]
It was never intended to be a public funtion, only for OpenSSL;s internal use.  If it stays, perhaps the name should be changed.

**Comment by mspncp** [comment]
Ok, understood. But then its prototype shouldn't be in  `<openssl/crypto.h>`:
```
include/openssl/crypto.h:70:CRYPTO_RWLOCK *CRYPTO_THREAD_glock_new(const char *name);
```

Coming back to my initial problem, which made me seek documentation in the first place: Can you explain in two or three sentences what the intention behind the global locks is and why they were introduced? I did not have the time yet to dig through the pull request, so I didn't get the point of the glocks yet.

**Comment by richsalz** [comment]
Thread-safety and forking.  Look at the fork-prepare routines.

**Comment by kaduk** [comment]
The short summary is in http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_atfork.html at the "expected usage is that the prepare handler acquires all mutex locks and the other two fork handlers release them.", but it turns out this is actually quite challenging to do in a usable way, as was pointed out on #4321

**Comment by mspncp** [comment]
@kaduk thanks for the explanation. I read up a bit on this subject and was suprised to learn that getting fork() done right in multithreaded applications is more difficult than expected.  The atfork approach to grab all important locks before forking sounds reasonable, but it will propably only work if the application programmer provides callbacks to treat his own locks in a similar way. Are there existing applications using openssl that mix threads and forks? Until now, I believed that a webserver would either fork or create new threads for incoming connections. What particular use case is OpenSSL trying to address?

Also I was wondering whether installing these atfork handlers would impose an unwanted overhead for applications that don't mix forks and threads? Or multithreaded applications that only just use fork()/execve()? At least in the special case of the `system()` library call, this problem seems to be addressed by glibc, but that's not guaranteed, see [man system(3)](http://man7.org/linux/man-pages/man3/system.3.html):

       According to POSIX.1, it is unspecified whether handlers registered
       using pthread_atfork(3) are called during the execution of system().
       In the glibc implementation, such handlers are not called.

Questions over questions. This could be a nice subject for a post on the OpenSSL blog...

**Comment by kaduk** [comment]
> Are there existing applications using openssl that mix threads and forks?

No, any such code would have no hope of working.

I believe that the only fork handler we need right now is the one to increment the depth of the reseed hierarchy counter in the child, as I attempted to discuss at #4110

**Comment by mspncp** [comment]
Since there is a broad consent that the global lock implementation should be reverted (see #5089) I'll close this issue ahead of time.
