### ISSUE TITLE
How to accommodate Signature values i.e. R and S from ECDSA Signature Algorithm into a X509 Certificate request structure to form a valid CSR

### ISSUE THREAD

**Issue by swati025** [openssl/openssl#4711]
I have to generate valid X.509 Certificates for the Subject, for which I have been given the Public key of the subject and the unique info what they want to put into their unique certificate. So I am sending this CertificateRequestInfo (X509_Req_INFO structure) to the Subject and receiving R & S values as a signature so in order to create a valid Certificate Signing Request i need to have the signature accommodated inside this struct X509_req_st {
    X509_REQ_INFO *req_info;
    X509_ALGOR *sig_alg;
    **ASN1_BIT_STRING *signature;**
    int references;
}

**Comment by richsalz** [comment]
You cannot generate a certificate request without the private key.  So if you are given only the public key, you cannot do it.

Are you saying that you send them the certreq, and they return a signature?

**Comment by swati025** [comment]
No , I am sending them the X509_REQ_INFO not the X509_REQ

**Comment by swati025** [comment]
X509_REQ has to be generated at my end.
I am quite new to this ECDSA algorithm which has this R&S values, but this is giving me an impression that there should be something to hold them(the signatures).  I found this structure in ecdsa.h
struct ECDSA_SIG_st {
    BIGNUM *r;
    BIGNUM *s;
} ECDSA_SIG;
but i am not quite sure if this can be a substitute of private key.

**Comment by richsalz** [comment]
If you have a keypair Kpub and Kpriv, then the certificate request has the Kpub in it, but it must be signed with Kpriv.  That is how the CA that processes the request knows that the requestor actually has possession of the private key.

Your best method might be to start dissecting what happens during the apps/req.c program while making a cert request.

**Comment by swati025** [comment]
ASN1_BIT_STRING_set function helped me to fill the DER format signature and created Certificate Signing Request with Public key: "BJauLfCJaX3Zk1d2m4Sl8Ma9u7UZzV/KftOI1bsmukUKviUEn9idhkFQH1sXsKsvSzseURzYveBBV7yiTeTJdrk="
Signature = "MEUCIQC/F4JPQWvJPrvI4l0UbcPfqN2rbU5rxjNr0gQyZZTcfwIgA35chfLXM9CvQGBaWwskEAmj2CyD/JXAk6oUOGMuEio="

which looks like
swati025\Openssl_Appln>openssl req -in CSRConstructed.pem -noout -text
Certificate Request:
    Data:
        Version: 1 (0x1)
        Subject: C=IN, ST=MH, L=PUNE, OU=ABC, CN=88:22:32:49, O=XXX
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:96:ae:2d:f0:89:69:7d:d9:93:57:76:9b:84:a5:
                    f0:c6:bd:bb:b5:19:cd:5f:ca:7e:d3:88:d5:bb:26:
                    ba:45:0a:be:25:04:9f:d8:9d:86:41:50:1f:5b:17:
                    b0:ab:2f:4b:3b:1e:51:1c:d8:bd:e0:41:57:bc:a2:
                    4d:e4:c9:76:b9
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        Attributes:
            a0:00
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:bf:17:82:4f:41:6b:c9:3e:bb:c8:e2:5d:14:
         6d:c3:df:a8:dd:ab:6d:4e:6b:c6:33:6b:d2:04:32:65:94:dc:
         7f:02:20:03:7e:5c:85:f2:d7:33:d0:af:40:60:5a:5b:0b:24:
         10:09:a3:d8:2c:83:fc:95:c0:93:aa:14:38:63:2e:12:2a

Now, the issue is Certificate is not getting created and says
![image](https://user-images.githubusercontent.com/23661778/32934290-97a790bc-cb91-11e7-8e3f-ac80f74bc839.png)

**Comment by SE5530000000008506126997** [comment]
Mohamed ali
