### ISSUE TITLE
PHP: AES-CMAC Various data length support

### ISSUE THREAD

**Issue by MuminCelal** [openssl/openssl#4712]

**Comment by richsalz** [comment]
Can you please provide some information about what it is you are looking for?

**Comment by MuminCelal** [comment]
I want to use openssl in PHP 7 completely, every feature. One of them is that AES-CMAC algorithm. I want to use AES-CMAC that accepts 256 bit key.

**Comment by richsalz** [comment]
So is this a PHP issue, or is OpenSSL missing something you want?

**Comment by MuminCelal** [comment]
I know. I want to know is that how to use OpenSSL AES-CMAC that accepts 256 bit key apart from PHP or another language. In my searches, I just saw AES-CMAC that accepts 128 bit key.

**Comment by richsalz** [comment]
So you want AES-CMAC 256 support in openssl and then someone else write php interface for that.
Why do you want aes-cmac-256?

**Comment by MuminCelal** [comment]
For the clarifying, As I understand the AES-CMAC mechanism, current one accepts 128 bit key and it produces 128 bit subkeys (K1, K2) according to message length and then CMAC of the data is produced. Am I wrong?

**Comment by dot-asm** [comment]
K1 and K2 are not cipher keys, but block-size-length values used in CMAC composition. In other words 128-bitness of K1 and K2 has nothing to do with AES strength (as in AES-128, AES-192, AES-256), but its block size.

**Comment by MuminCelal** [comment]
I understand the what you mean. Thank you for your answers

**Comment by bukka** [comment]
@MuminCelal I maintain [an extension](https://github.com/bukka/php-crypto) that probably does what you wanted and it's available on PECL. The docs for CMAC can be found at:

https://github.com/bukka/php-crypto/blob/master/docs/cmac.md
