### ISSUE TITLE
using password protected client side certificate with openssl

### ISSUE THREAD

**Issue by amlwwalker** [openssl/openssl#472]
Hi,
I am having a problem using openssl with a client side certificate that is password protected. When the password is removed it is possible to pass the certificate to the server successfully however when it is password protected it seems to fail. 
In the browser the certificate works fine, but from openssl on the command line i get access forbidden every time when there is a password.

I have a server live that is my testing application and a client certificate that I am willing to share if anyone can help resolve this. I would like to send it privately and encrypted if possible.

**Comment by richsalz** [comment]
certificate or key?  what fails, the command-line or some app built on openssl?

**Comment by richsalz** [comment]
no action, closing.  please discuss on openssl-users mailing list.
