### ISSUE TITLE
SSL_free() breaks sessions obtained via SSL_get1_session()

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#4720]
There is a SSL connection active. I do
   SSL_get1_session()
and use the returned session in another connection. SSL-session resumption works.
If the SSL connection does
  SSL_shutdown()
  SSL_free()
then the session can still be used in another connection, SSL-session resumption works.
Now, if I miss or skip SSL_shutdown() and perfm only SSL_free() then the retrieved session can no be reusued in a later SSL connection, SSL-session resumption won't work.
It seems that SSL_shutdown() before SSL_free() is required otherwise the session is somehow broken. 
This wasn't like that in 1.02 seems to be new in 1.1.
Is this behavior expected? I would *expect*  a session with a refcounter to remain persistent untill it there is no valid reference to it.

**Comment by kaduk** [comment]
This is the result of ssl_clear_bad_sessions() being conditionally called from SSL_free() (based on whether it has been shutdown cleanly):

```
int ssl_clear_bad_session(SSL *s)
{
    if ((s->session != NULL) &&
        !(s->shutdown & SSL_SENT_SHUTDOWN) &&
        !(SSL_in_init(s) || SSL_in_before(s))) {
        SSL_CTX_remove_session(s->session_ctx, s->session);
        return 1;
    } else
        return 0;
}
```

There is some text in the spec about sessions not being reusable if the connection is aborted by the peer that makes this behavior justifiable, but it is not entirely clear that it's actually the best behavior for us to have.

**Comment by sebastianas** [comment]
This should be at least documented.
What means aborted? Not shutdown properly like in this case, switched timeout/error on an active connection (like by switching from WIFI to mobile and the old IP is gone) or something within the SSL specification?

**Comment by mattcaswell** [comment]
> This wasn't like that in 1.02 seems to be new in 1.1.

The code in question is there in both 1.0.2 and 1.1.0+. My tests indicate that it gets triggered in the same way in both branches, i.e. it doesn't look to me like the behaviour has changed.

I updated the docs in PRs #6053, #6054.

**Comment by sebastianas** [comment]
On 2018-04-23 10:32:58 [+0000], mattcaswell wrote:
> > This wasn't like that in 1.02 seems to be new in 1.1.
> 
> The code in question is there in both 1.0.2 and 1.1.0+. My tests
> indicate that it gets triggered in the same way in both branches, i.e.
> it doesn't look to me like the behaviour has changed.

I debuged this in netkit-ftp-ssl [0]. So this triggered in Debian and
the openssl version, that I used for testing, should have been 1.0.2m.
So this version worked, while the 1.1 version at the time did not. So
based on this, something changed.

I didn't test 1.0.2o but I have no reason to believe that it changed but
I can double check today if you want me to.

> I updated the docs in PRs #6053, #6054.
Thank you.

[0] https://bugs.debian.org/859224

Sebastian

**Comment by mattcaswell** [comment]
> I debuged this in netkit-ftp-ssl [0]. So this triggered in Debian and
the openssl version, that I used for testing, should have been 1.0.2m.
So this version worked, while the 1.1 version at the time did not. So
based on this, something changed.

My best guess is that something else changed between 1.0.2 and 1.1.0 that caused this behaviour to trigger in one case but not the other. I couldn't say what.
