### ISSUE TITLE
defaulting max_early_data to SSL3_RT_MAX_PLAIN_LENGTH causes wasted traffic

### ISSUE THREAD

**Issue by kaduk** [openssl/openssl#4725]
Currently, we set a default ```max_early_data``` to ```SSL3_RT_MAX_PLAIN_LENGTH``` in SSL_CTX_new(), on the grounds that this is a sane default value for applications to use and there's supposedly no need to make them explicitly set a value when there are other things they have to do in order to get the application to actually use early data.  IIRC these "other things" are just calls to SSL_read_early_data(), which sets ```s->early_data_state``` to ```SSL_EARLY_DATA_ACCEPTING``` whicih in turn is required for final_early_data() to set ```s->ext.early_data``` to ```SSL_EARLY_DATA_ACCEPTED```, which is in turn then used to determine whether we send the early_data extension in tls_construct_stoc_early_data() to tell the client that early data was accepted.
However, this setup means that when we construct a session ticket, tls_construct_stoc_early_data() will see a non-zero ```s->max_early_data``` and put into the ticket's extensions "sure, send us early data".  Clients will see this and attempt to send early data, which is doomed to fail unless the application has opted in.  This wastes bandwidth attempting to send data that will be rejected, and will also burn up session tickets for clients that adhere to the spec's recommendation to only use a ticket once.

The ```s->early_data_state``` field is not usable when determining whether to indicate that a given
ticket under construction should indicate to the client that early data is acceptable, as that field is a property of the current connection, and is not relevant to the application's configuration.  I think that we should change the default ```max_early_data``` to zero and require the application to set a non-zero value when it adds calls to SSL_read_early_data(), to make the default behavior for non-early-data-consuming applications more reasonable.

**Comment by mattcaswell** [comment]
This is a good argument and seems fairly reasonable to me. When I set the default it wasn't clear to me what the default should be so I think I just picked something! We should make sure we update the docs if we do this. Care to make a PR?

**Comment by kaduk** [comment]
I can try to put something together, sure.  I'm at the IETF meeting this week, so it may take longer than usual.
