### ISSUE TITLE
SSL_read() returned variable erroneous data (OpenSSL 1.1.0g)

### ISSUE THREAD

**Issue by hondero2552** [openssl/openssl#4726]
Alright, so this is a question but also almost a bug report. So bare with me here. According to OpenSSL's documentation SSL_read() returns the number of bytes read from the socket (after decryption). I am testing my server locally and although I was sending 96 bytes from the client, I was only receiving 1 byte according to the returned variable of SSL_read().

Where things got weird was when I decided to do a memory dump of my receiving buffer....it had all the data my sending buffer sent but it was not relaying that information to me. Meaning that ssl_read() was still returning 1 byte read even-though it was reading the whole 96. 

There is no buffer overrun issues because the buffer is big enough (although I didn't test things with a smaller buffer), but there is still the issue of the documentation being completely wrong about this function and more importantly how are we supposed to find out how many bytes were received by ssl_read() if it always says it only receives 1 byte??

How to fix this: The only work around I found was using ssl_peek() before ssl_read() but that is just a temporary solution. The documentation must be updated to either reflect using ssl_peek() or ssl_read() must change its behavior.

**Comment by richsalz** [comment]
You are supposed to keep calling read until you get all the data that you are expecting.  TLS (and SSL) are stream-oriented protocols, they do not preserve packet boundaries.  Are you using non-blocking mode?

**Comment by hondero2552** [comment]
Yes, I am using non-blocking, and I do understand that I need to keep calling ssl_read() until I get all my data, but if I provide a buffer that is big enough (which it definitely is in my case) ssl_read() must return how many bytes it loaded, not simply return 1 byte every time....

**Comment by richsalz** [comment]
no, it does not have to do what you want it to do :)
Have you looked at SSL_pending?

**Comment by hondero2552** [comment]
yeahp....it returns same info..wrong as well.....one byte pending when I know is 96, and the reason I know is because ssl_read() ends up reading 96 bytes after it's called...I'm testing something right now.....with ssl_peek()....

**Comment by hondero2552** [comment]
What in the world.....so here is the update when I call ssl_read() inside the condition statement of my while loop
` while ((bytesRead = SSL_peek(m_ssl, mBeginningDataBufferAddress, maxBufferSize) > 0))`

it returns the wrong data, but if I call it outside of it, it doesn't....

Damn Xcode and it's cheap compiler optimization BS!

**Comment by richsalz** [comment]
So it's a compiler bug?  Wow, that's frustrating.  Close this?

**Comment by hondero2552** [comment]
Yeahp...please close it.... Was able to recreate the compiler bug in three different places... Thanks and sorry for wasting your time.

**Comment by richsalz** [comment]
It's okay.  Glad you got it working!
