### ISSUE TITLE
no-rmd160 is broken - fatal error C1189: #error:  RMD160 is disabled.

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#473]
At least on Windows, the no-rmd160 option is broken.

perl Configure no-rmd160 VC-WIN32 -DUNICODE -D_UNICODE -DWINVER=0x0601 -D_WIN32_WINNT=0x0601

The rmd_dgst.c is included in the nt.mak/ntdll.mak:
cl ...... .\crypto\ripemd\rmd_dgst.c

Which generates this error message:
C:\openssl\openssl\include\openssl/ripemd.h(70): fatal error C1189: #error:  RMD160 is disabled.

**Comment by richsalz** [comment]
seems to work now.

**Comment by matbech** [comment]
Unfortunately no:
rmd_dgst.c
include\openssl/ripemd.h(69): fatal error C1189: #error:  RMD160 is disabled.

**Comment by richsalz** [comment]
Which version?  I can't reproduce this in master.

**Comment by matbech** [comment]
I can reproduce this with master.

**Comment by richsalz** [comment]
What config line are you using?

**Comment by matbech** [comment]
I just tested it with the no-rmd160 alone:

set options=no-rmd160
perl Configure %options% VC-WIN32 -DUNICODE -D_UNICODE -DWINVER=0x0601 -D_WIN32_WINNT=0x0601

**Comment by matbech** [comment]
The problem is in mk1mf.pl
It expects no-ripemd:
		"no-ripemd" => \$no_ripemd,

What works is using Configure with:
no-ripemd no-rmd160
but it would be better to change "no-ripemd" in mk1mf.pl
