### ISSUE TITLE
Support of ECDSA_SIG (R & S values) assignment to x509_REQ->signature = ?

### ISSUE THREAD

**Issue by tejas3** [openssl/openssl#4730]
Is this support available in openssl using any openssl API ? 
x_509_req->signature  = ECDSA_SIG (appending signature to x509_req so that CSR construction done)

**Comment by SE5530000000008506126997** [comment]
Mohamed ali

**Comment by SE5530000000008506126997** [comment]
Mohamed ali

**Comment by mattcaswell** [comment]
Please ask these types of questions on the openssl-users email list:

https://mta.openssl.org
