### ISSUE TITLE
PVS-Studio + openssl-master

### ISSUE THREAD

**Issue by pavel-pimenov** [openssl/openssl#4733]
@richsalz  (https://github.com/openssl/openssl/issues/4729)
html report for master
https://yadi.sk/d/uprl_mCU3Pfune

![default](https://user-images.githubusercontent.com/920705/32761933-57727980-c907-11e7-9514-4d741e95b462.png)

**Comment by FdaSilvaYY** [comment]
Ping @pavel-pimenov : can you rerun the analyzer on current master ?

**Comment by pavel-pimenov** [comment]
@FdaSilvaYY master e72bf96
https://yadi.sk/d/Oa9ZUWHm3Supxt

**Comment by mattcaswell** [comment]
I'm thinking we should close this issue. I ran through some of these reports and large numbers of the issues are either false positives or trivial issues in test programs or other non-essential areas. Given the large number of reports its difficult to see the useful reports from the uninteresting. It is more helpful to raise specific issues or pull requests where an actual issue has been identified. We already have access to coverity which is our preferred tool for this kind of analysis - so I think we are better off investing our resources in analysing the coverity reports.
