### ISSUE TITLE
pem tests on MSYS2 spurious failure

### ISSUE THREAD

**Issue by turboj** [openssl/openssl#4740]
Current openssl (1.1.0g) tests work on MSYS2 with 

MSYS2_ARG_CONV_EXCL="file" make test

This solves a path conversion error in the _pem tests. Note that some other tests actually need the path conversion of MSYS2, so MSYS2_ARG_CONV_EXCL="*" is too much.

**Comment by kaduk** [comment]
It would be interesting to see what similar failures occur when running tests on the master branch -- perhaps the data_file() perl function is doing something unfortunate (i.e., using an absolute path without coping properly for msys2/cygwin)

**Comment by levitte** [comment]
@turboj, are you talking about some specific test, or in general?  Considering that `MSYS2_ARG_CONV_EXCL` is supposed to match the beginning of arguments that shouldn't be converted, that has me think you're talking about `test/recipes/90-test_store.t` in particular, correct?

A question, do you actually need to set `MSYS2_ARG_CONV_EXCL` at all?  #4322 should help avoid problematic arguments, and that's where we had problems before (see #4314)...

**Comment by turboj** [comment]
Without `MSYS2_ARG_CONV_EXCL` I had failues in `04-test_pem.t` because it calls openssl with a `file:` argument for the password that MSYS2 wrongly converts into `file;` (note the semicolon). Other tests where fine.

Trying to use `MSYS2_ARG_CONV_EXCL="*" make test` 
hangs in `70-test_sslmessages.t` because the openssl sever fails to start. This test requires argument conversion to work.

Documenting this behaviour in README or NOTES.WIN would be nice.

**Comment by levitte** [comment]
Hmmm...  does this patch work?

``` diff
diff --git a/test/recipes/04-test_pem.t b/test/recipes/04-test_pem.t
index c37c98738b..11e3314b55 100644
--- a/test/recipes/04-test_pem.t
+++ b/test/recipes/04-test_pem.t
@@ -88,7 +88,10 @@ SKIP: {
     skip "DSA support disabled, skipping...", (scalar keys %dsa_expected) unless !disabled("dsa");
     foreach my $input (keys %dsa_expected) {
         my @common = ($cmd, "pkey", "-inform", "PEM", "-passin", "file:" . data_file("wellknown"), "-noout", "-text", "-in");
-        my @data = run(app([@common, data_file($input)], stderr => undef), capture => 1);
+        {
+            local $ENV{MSYS2_ARG_CONV_EXCL} = "file:";
+            my @data = run(app([@common, data_file($input)], stderr => undef), capture => 1);
+        }
         my @match = grep /68:42:02:16:63:54:16:eb:06:5c:ab:06:72:3b:78:/, @data;
         is((scalar @match > 0 ? 1 : 0), $dsa_expected{$input});
     }
```

**Comment by levitte** [comment]
(I edited the patch, the first variant was faulty)

**Comment by turboj** [comment]
Almost correct. $ENV is special in perl, and "local" will not work for me:
```
-            local $ENV{MSYS2_ARG_CONV_EXCL} = "file:";
+            $ENV{MSYS2_ARG_CONV_EXCL} = "file:";
```

**Comment by levitte** [comment]
That's curious... Localizing %ENV values should work. Granted, I didn't test that patch, but will later

**Comment by turboj** [comment]
The local %ENV does not seem to work. This might be a limitation in windows, as environment is per-process there.

**Comment by levitte** [comment]
This makes no sense...

I just tried the following perl script in an Mingw32 shell as well as in cmd.exe:

``` perl
#! /usr/bin/perl

my $syscmd =
    $^O eq 'MSWin32' ? 'echo %FOO%' : 'echo $FOO';

print "1: FOO=", $ENV{FOO} ? $ENV{FOO} : "", "\n";
system($syscmd);
{
    local $ENV{FOO} = 'foo';
    print "2: FOO=", $ENV{FOO} ? $ENV{FOO} : "", "\n";
    system($syscmd);
}
```

And well, the results was totally what I expected:

Mingw32:

```
Richard@OSFWin7 MINGW32 ~
$ perl /e/foo.pl
1: FOO=

2: FOO=foo
foo

Richard@OSFWin7 MINGW32 ~
$ FOO=bar perl /e/foo.pl
1: FOO=bar
bar
2: FOO=foo
foo
```

cmd.exe:

```
C:\Users\Richard>perl e:/foo.pl
1: FOO=
%FOO%
2: FOO=foo
foo

C:\Users\Richard>set FOO=bar

C:\Users\Richard>perl e:/foo.pl
1: FOO=bar
bar
2: FOO=foo
foo
```

**Comment by turboj** [comment]
My Bad. 
I did not check the line number properly and applied the fix by hand in the wrong spot. m-(

The original proposed fix to the DSA test works properly:
```
     skip "DSA support disabled, skipping...", (scalar keys %dsa_expected) unless !disabled("dsa");
     foreach my $input (keys %dsa_expected) {
         my @common = ($cmd, "pkey", "-inform", "PEM", "-passin", "file:" . data_file("wellknown"), "-noout", "-text", "-in");
-        my @data = run(app([@common, data_file($input)], stderr => undef), capture => 1);
+        my @data;
+        {
+            local $ENV{MSYS2_ARG_CONV_EXCL} = "file:";
+            @data = run(app([@common, data_file($input)], stderr => undef), capture => 1);
+        }
```
