### ISSUE TITLE
error: storage size of ‘ctx’ isn’t known

### ISSUE THREAD

**Issue by jacky-ge** [openssl/openssl#4749]
I met the following error:

aes_ecb.c: In function ‘aesEncrypt’:
aes_ecb.c:62:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^
aes_ecb.c: In function ‘aesDecrypt’:
aes_ecb.c:81:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^

**Comment by levitte** [comment]
You're using OpenSSL 1.1.0, right?  That's because the type became opaque, and you can't allocate `ctx` on the stack any more.  The function to create a `EVP_CIPHER_CTX *ctx` is `EVP_CIPHER_CTX_new`
