### ISSUE TITLE
function MDC2_Final coredump

### ISSUE THREAD

**Issue by tan00** [openssl/openssl#4759]
OpenSSL version:	
> OpenSSL 1.0.1f 6 Jan 2014 (Library: OpenSSL 1.0.1m 19 Mar 2015)

OS Name:
> Linux LN-PC 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Problem Description (steps that will reproduce the problem, if known):
> function MDC2_Final(hashVal,(MDC2_CTX *)context)  coredump

the function MDC2_Final in  openssl-1.1.0f/crypto/mdc2/mdc2dgst.c  has a coredump error if the parameter MDC2_CTX contain error value 

this code will reproduce the coredump:

```
int main()
{
        unsigned char context[1024] = {0};
        unsigned char hashVal[1024] = {0};
        context[0] = 0x31;
        int ret = MDC2_Final(hashVal,(MDC2_CTX *)context);
        //int ret = MD5_Final(hashVal,(MDC2_CTX *)context);       
        printf("ret=[%d]\n",ret);
        return ret;
}
```

MDC2_Final source code is not robust enough
```
typedef struct mdc2_ctx_st {
    unsigned int num;
    unsigned char data[MDC2_BLOCK];
    DES_cblock h, hh;
    int pad_type;               /* either 1 or 2, default 1 */
} MDC2_CTX;

int MDC2_Final(unsigned char *md, MDC2_CTX *c)
{
    unsigned int i;
    int j;

    i = c->num;
    j = c->pad_type;
    if ((i > 0) || (j == 2)) {
        if (j == 2)
            c->data[i++] = 0x80;
        memset(&(c->data[i]), 0, MDC2_BLOCK - i);
        mdc2_body(c, c->data, MDC2_BLOCK);
    }
    memcpy(md, (char *)c->h, MDC2_BLOCK);
    memcpy(&(md[MDC2_BLOCK]), (char *)c->hh, MDC2_BLOCK);
    return 1;
}
````
if *c is 0x3100000000000000000000000000000000.......
c->num bigger than  MDC2_BLOCK  that  'memset(&(c->data[i]), 0, MDC2_BLOCK - i);' core dumped

core file is 
```
(gdb) bt
#0  __memset_avx2 () at ../sysdeps/x86_64/multiarch/memset-avx2.S:161
#1  0x00007f6a753cabc5 in MDC2_Final () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00000000004007ce in ?? ()
#3  0x00000000000020e0 in ?? ()
#4  0x00000000000020e0 in ?? ()
#5  0x0000000000000031 in ?? ()
#6  0x0000000000000000 in ?? ()

```

**Comment by t-j-h** [comment]
So your "issue" is that if you fail to call MDC2_Init then the other APIs are not "defensive" with respect to the contents of the context?

**Comment by tan00** [comment]
Yes.  This is not a problem if  we wrap the three APIs. 
In some applications  the step hash  API couldn't  be wrapped to one  because of the limit of message length. The interface will be exposed to customers. 
Other hash algorithm  will not coredump even if the input is invalid.

What should I Do if the input is incorrect?
