### ISSUE TITLE
SSL initialising fails with 1.1.1 using BIO pairs

### ISSUE THREAD

**Issue by magsys** [openssl/openssl#4762]
I'm updating our Delphi SSL code to support 1.1.1 in addition to 1.0.2
and 1.1.0, common code with a few version checks. This is using Windows
10.  

With 1.1.1, SSL connections fail to initialise, failing with the first
BIO_read after setting up the context and BIOs. There is no real error
(I can see), read just fails and BIO_should_retry says no with a zero
reason.   

We are using SSL filter I/O with a BIO pair, we handle all I/O using
non-blocking Windows APIs.  

There was no particular issue updating to 1.1.0, apart from new context
stuff, but 1.1.1 seems to have changed something to make our code fail.
I can not see anything in the TLS/1.3 notes that relates to simple SSL
initialisation.  

The main APIs called are, in order: 

SSL_new(myContext) 
BIO_new(BIO_f_ssl)
BIO_new_bio_pair
SSL_set_ex_data
SSL_set_session
SSL_set_tlsext_host_name
SSL_set_connect_state
SSL_set_bio
SSL_set_info_callback
SSL_set_msg_callback
BIO_set_ssl
BIO_read - 0 bytes

which is where it dies, after a SSL_CB_HANDSHAKE_START info message and
a 512 byte write client hello. 

The openssl.exe built with 1.1.1 seems to work OK making a client
connection, but uses different BIO I/O.

Is some new initialisation required for 1.1.1?

**Comment by mattcaswell** [comment]
> Is some new initialisation required for 1.1.1?

No, if it works for 1.1.0 it should work for 1.1.1 (with the exception of the notes made in my blog post here: https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/)

Could you construct some simplified code that exhibits the problem?

**Comment by magsys** [comment]
Yes, I read the TLS1.3 primer carefiully (it really need a quick edit to say draft 21 is supported), and I have tried setting groups (which also fails) but have context max version set to 1.2 and nothing else seems specific to current tls versions. 

The complication here is our code is an open source Delphi internet library, so everything is object pascal. We do sometimes have header conversion issues, particulary when macros become exports because we have to find those changes manually, but I've carefully compared the main header files between 1.1.0 and 1.1.1 and don't think I've missed anything.  

The 1.1.1 code is not yet in SVN, but I can put it there, and there are numerous SSL samples (servers and clients) all of which fail to iniitialse an SSL connection.  But you would need Delphi 2007 or l;ater to run it.  

Sorry, managed to avoid learning C since I starting developing stuff in PLM/80.

**Comment by mattcaswell** [comment]
Perhaps if you captured a wireshark trace of a failing connection that might give us some hint as to what is going wrong.

**Comment by magsys** [comment]
We do have a lot of logging, including protocol messages:  

Using 1.1.1
10:55:44:281 connect to 192.168.1.121/443
10:55:44:292 04326370 Socket handle created handle=920
10:55:44:302 TWSocket will connect to 192.168.1.121:443
10:55:44:326 SessionConnected
10:55:44:346 State = httpConnected
10:55:44:358 State = httpWaitingHeader
cmd> GET /testing/unicodedemo.htm HTTP/1.1
cmd> Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*
cmd> Connection: Keep-Alive
cmd> Accept-Language: en, fr
cmd> User-Agent: Mozilla/4.0 (compatible; ICS; MSIE 4.0)
cmd> Host: telecom.magenta
cmd> Proxy-Connection: Keep-Alive
10:55:44:429 7 header lines to send
GET /testing/unicodedemo.htm HTTP/1.1
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*
Connection: Keep-Alive
Accept-Language: en, fr
User-Agent: Mozilla/4.0 (compatible; ICS; MSIE 4.0)
Host: telecom.magenta
Proxy-Connection: Keep-Alive
cmd>
10:55:44:445 04326370 PutDataInSslBuffer handle=920 [1] Data:GET /testing/unicodedemo.htm HTTP/1.1$0D $0A Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*$0D $0A Connection: Keep-Alive$0D $0A Accept-Language: en, fr$0D $0A User-Agent: Mozilla/4.0 (compatible; ICS; MSIE 4.0)$0D $0A Host: telecom.magenta$0D $0A Proxy-Connection: Keep-Alive$0D $0A $0D $0A
10:55:44:455 SendRequest Done
10:55:44:462 04326370 StartSslHandshake handle=920
10:55:44:472 04326370 InitSSLConnection handle=920
10:55:56:998 04326370 Start Ssl ReadBIO
10:56:56:266 04326370 ICB> undefined: where=00000010
10:57:51:371 04326370 ICB> SSL_CB_HANDSHAKE_START
10:58:53:082 ProtoMsg: None, State: SSLv3/TLS write client hello, Send, DataLen: 5, Data= 1603010200
10:58:53:088 ProtoMsg: TLS 1.2 Handshake: Client Hello, State: SSLv3/TLS write client hello, Send, DataLen: 512, Data= 010001FC0303139B658843BD3FA9660B49B7B7803BC95CE9CF91FBC3E7CF35A8608B08D52E7A000084C02CC03000A3009FCCA9CCA8CCAAC0AFC0ADC0A3C09FC02BC02F00A2009EC0AEC0ACC0A2C09EC024C028006B006AC073C07700C400C3C023C02700670040C072C07600BE00BDC00AC0140039003800880087C009C01300330032009A009900450044009DC0A1C09D009CC0A0C09C003D00C0003C00BA00350084002F00960041000700FF0100014F00000014001200000F74656C65636F6D2E6D6167656E7461000B000403000102000A000A0008001D0017001900180016000000170000000D002800260403050306030807080408050806040105010601030302030301020103020202040205020602001500E90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
11:01:42:342 04326370 ResetSslSession handle=920
11:01:42:363 04326370 Fatal error SSL handshake handle=920 EOpenSslError
InitSSLConnection: ReadBIO, Retry Reason 0
error:00000000:lib(0):func(0):reason(0)
11:01:42:373 SessionClosed Error: 10053
!EOpenSslError:
InitSSLConnection: ReadBIO, Retry Reason 0
error:00000000:lib(0):func(0):reason(0)
11:01:42:386 State = httpAborting
11:01:42:397 04326370 *CloseCalled handle=-1

Hope this helps.  The context is set identically for 1.1.0 (I think) and works, this same code works in 1.1.0 where it says: 

Using 1.1.0 
19:16:01:738 022A6370 StartSslHandshake handle=884
19:16:01:743 022A6370 InitSSLConnection handle=884
19:16:08:112 022A6370 ICB> SSL_CB_HANDSHAKE_START
19:16:08:125 ProtoMsg: TLS 1.2, State: SSLv2/v3 write client hello B, Send, DataLen: 5, Data= 1603010164
19:16:08:134 ProtoMsg: TLS 1.2 Handshake: Client Hello, State: SSLv2/v3 write client hello B, Send, DataLen: 356, Data= 01000160030357C961432B900570FDA0D5A0AB862B57D7656D41E88FCBCCA16FDF649E0158370000CAC030C02CC028C024C014C00A00A500A300A1009F006B006A0069006800390038003700360088008700860085C01900A7006D003A0089C032C02EC02AC026C00FC005009D003D00350084C02FC02BC027C023C013C00900A400A200A0009E00670040003F003E0033003200310030009A0099009800970045004400430042C01800A6006C0034009B0046C031C02DC029C025C00EC004009C003C002F009600410007C011C007C0160018C00CC00200050004C012C008001600130010000DC017001BC00DC003000A00FF0100006D00000014001200000F74656C65636F6D2E6D6167656E7461000B000403000102000A001C001A00170019001C001B0018001A0016000E000D000B000C0009000A00230000000D0020001E060106020603050105020503040104020403030103020303020102020203000F000101
19:16:08:142 022A6370 BIO_read(sslbio, 0x19FABE, 0) = -1   [2] Data:
19:16:08:148 022A6370 BIO_read(nbio, 0x2272B38, 361) = 361   [3] Data:$16 $03 $01 $01 d$01 $00 $01 `$03 $03 W$C9 aC+$90 $05 p$FD $A0 $D5 $A0 $AB $86 +W$D7 emA$E8 $8F $CB $CC $A1 o$DF d$9E $01 X7$00 $00 $CA $C0 0$C0 ,$C0 ($C0 $$C0 $14 $C0 $0A $00 $A5 $00 $A3 $00 $A1 $00 $9F $00 k$00 j$00 i$00 h$00 9$00 8$00 7$00 6$00 $88 $00 $87 $00 $86 $00 $85 $C0 $19 $00 $A7 $00 m$00 :$00 $89 $C0 2$C0 .$C0 *$C0 &$C0 $0F $C0 $05 $00 $9D $00 =$00 5$00 $84 $C0 /$C0 +$C0 '$C0 #$C0 $13 $C0 $09 $00 $A4 $00 $A2 $00 $A0 $00 $9E $00 g$00 @$00 ?$00 >$00 3$00 2$00 1$00 0$00 $9A $00 $99 $00 $98 $00 $97 $00 E$00 D$00 C$00 B$C0 $18 $00 $A6 $00 l$00 4$00 $9B $00 F$C0 1$C0 -$C0 )$C0 %$C0 $0E $C0 $04 $00 $9C $00 <$00 /$00 $96 $00 A$00 $07 $C0 $11 $C0 $07 $C0 $16 $00 $18 $C0 $0C $C0 $02 $00 $05 $00 $04 $C0 $12 $C0 $08 $00 $16 $00 $13 $00 $10 $00 $0D $C0 $17 $00 $1B $C0 $0D $C0 $03 $00 $0A $00 $FF $01 $00 $00 m$00 $00 $00 $14 $00 $12 $00 $00 $0F telecom.magenta$00 $0B $00 $04 $03 $00 $01 $02 $00 $0A $00 $1C $00 $1A $00 $17 $00 $19 $00 $1C $00 $1B $00 $18 $00 $1A $00 $16 $00 $0E $00 $0D $00 $0B $00 $0C $00 $09 $00 $0A $00 #$00 $00 $00 $0D $00  $00 $1E $06 $01 $06 $02 $06 $03 $05 $01 $05 $02 $05 $03 $04 $01 $04 $02 $04 $03 $03 $01 $03 $02 $03 $03 $02 $01 $02 $02 $02 $03 $00 $0F $00 $01 $01
19:16:08:160 022A6370 BIO_read(nbio, 0x2272B38, 0) = 0   [4] Data:
19:16:08:167 022A6370 BIO_read(nbio, 0x2272B38, 0) = 0   [5] Data:
19:16:08:174 022A6370 BIO_write(nbio, 0x2272B38, 7) = 7   [6] Data:$16 $03 $03 $00 A$02 $00
19:16:08:182 ProtoMsg: None, State: SSLv3 read server hello A, Recv, DataLen: 5, Data= 1603030041
19:16:08:191 022A6370 BIO_read(sslbio, 0x19FC83, 0) = -1   [7] Data:
19:16:08:198 022A6370 BIO_read(nbio, 0x2272B38, 0) = 0   [8] Data:
19:16:08:208 022A6370 BIO_write(nbio, 0x2272B38, 63) = 63   [9] Data:$00 =$03 $03 k)KY#sm$CF $BE ~$B9 l$82 $F9 $C9 $FE $05 k$A1 ,3$9E $8F $0E $97 $B2 $DF 8$C6 $85 $C3 $CD $00 $C0 0$00 $00 $15 $FF $01 $00 $01 $00 $00 $00 $00 $00 $00 $0B $00 $04 $03 $00 $01 $02 $00 #$00 $00
19:16:08:215 ProtoMsg: TLS 1.2 Handshake: Server Hello, State: SSLv3 read server hello B, Recv, DataLen: 65, Data= 0200003D03036B294B5923736DCFBE7EB96C82F9C9FE056BA12C339E8F0E97B2DF38C685C3CD00C030000015FF0100010000000000000B00040300010200230000
19:16:08:224 022A6370 BIO_read(sslbio, 0x19FC83, 0) = -1   [10] Data:
19:16:08:230 022A6370 BIO_read(nbio, 0x2272B38, 0) = 0   [11] Data:
19:16:08:237 022A6370 BIO_read(nbio, 0x2272B38, 0) = 0   [12] Data:
19:16:08:244 022A6370 BIO_write(nbio, 0x2272B38, 5) = 5   [13] Data:$16 $03 $03 $04 -
19:16:08:251 ProtoMsg: None, State: SSLv3 read server certificate A, Recv, DataLen: 5, Data= 160303042D
19:16:08:259 022A6370 BIO_read(sslbio, 0x19FC83, 0) = -1   [14] Data:
19:16:08:266 022A6370 BIO_read(nbio, 0x2272B38, 0) = 0   [15] Data:
19:16:08:274 022A6370 BIO_read(nbio, 0x2272B38, 0) = 0   [16] Data:
19:16:08:281 022A6370 BIO_write(nbio, 0x2272B38, 1069) = 1069   [17] Data:$0B $00 $04 )$00 $04 &$00 $04 #0$82 $04 $1F 0$82 $03 $07 $A0 $03 $02 $01 $02 $02 $08 @$FF $A5 $CC G$FD $92 $B7 0$0D $06 $09 *$86 H$86 $F7 $0D $01 $01 $0C $05 $00 0$81 $B1 1$1F 0$1D $06 $03 U$04 $03 $0C $16 Magenta Development CA1$1C 0$1A $06 $03 U$04 $0B $0C $13 Development Testing1$0F 0$0D $06 $03 U$04 $08 $0C $06 Surrey1$1C 0$1A $06 $03 U$04 $0A $0C $13 Magenta Systems Ltd1$0B 0$09 $06 $03 U$04 $06 $13 $02 GB1$10 0$0E $06 $03 U$04 $07 $0C $07 Croydon1"0 $06 $09 *$86 H$86 $F7 $0D $01 $09 $01 $16 $13 delphi@magsys.co.uk0$1E $17 $0D 170811111212Z$17 $0D 200507111212Z0$81 $8D 1$18 0$16 $06 $03 U$04 $03 $0C $0F telecom.magenta1$1C 0$1A $06 $03 U$04 $0B $0C $13 Magenta Development1$16 0$14 $06 $03 U$04 $08 $0C $0D Great Britain1$1C 0$1A $06 $03 U$04 $0A $0C $13 Magenta Systems Ltd1$0B 0$09 $06 $03 U$04 $06 $13 $02 GB1$10 0$0E $06 $03 U$04 $07 $0C $07 Croydon0$82 $01 "0$0D $06 $09 *$86 H$86 $F7 $0D $01 $01 $01 $05 $00 $03 $82 $01 $0F $00 0$82 $01 $0A $02 $82 $01 $01 $00 $BC $A5 $AE $C3 f$E8 $FB u_CD<$8D $1E $84 $B2 $C8 ^$1B $E2 m$EC $E2 J$F1 |$C7 U$B5 [$B8 $B1 qA$C2 I$98 g$05 S$D3 l$C0 $EE $95 $FE g9$1C $FA 5$F9 $D1 T$0D $9B $A2 $A6 $B0 $DF XX0$9B $0C =$9C $B0 $DD i9_$0F $10 -$BD `$C6 <$E0 $97 $9D $04 $0B $B5 $B2 $C6 $A0 $BB $F5 $96 $E4 $E3 $F8 $A1 \$A1 4;$7F $DA $84 *$8C $D9 a$8F $9A e$E2 $EB G{$FE z lk$AB K7$AC $06 $B7 $BD S$F7 }$AD $9D $93 $DC g@$CA $00 J.$81 ES$F8 $0D $E3 $C9 n$D7 $04 vXD$14 $0D ;.$BF $19 m$D2 $EE e$BC $9B $E0 $A4 $0E e=$06 $D4 2=$FD k$B0 $08 $92 M$0B |$B3 $9D /$9E s$CB Q$1B $94 $E0 y$03 $8D V$99 $E2 $14 $ED Z$8B $EF $D8 $E4 $0A $0E $A5 $04 $00 ]1rh$FA iX$85 $97 $8D $D6 E6$1A $AB 1$DD $AF $E5 !$EC $C5 @$CF $A3 $A3 @$BF $94 $8E $87 $81 @Op)$B3 $88 $DA $D7 $BD @$C8 $04 $C0 $91 $95 $F9 $02 $03 $01 $00 $01 $A3 ]0[0$0C $06 $03 U$1D $13 $01 $01 $FF $04 $02 0$00 0$1C $06 $03 U$1D $11 $04 $15 0$13 $82 $0F telecom.magenta$82 $00 0$0E $06 $03 U$1D $0F $01 $01 $FF $04 $04 $03 $02 $03 $F8 0$1D $06 $03 U$1D %$04 $16 0$14 $06 $08 +$06 $01 $05 $05 $07 $03 $02 $06 $08 +$06 $01 $05 $05 $07 $03 $01 0$0D $06 $09 *$86 H$86 $F7 $0D $01 $01 $0C $05 $00 $03 $82 $01 $01 $00 8Q$DF $0B u$F9 $11 $90 D$02 $16 RO$EF $C8 $B5 >^$1F ]c$B3 A$91 $1A $C1 $0B J$7F G$C3 $B0 $05 $BB $0F $07 $DB $FD $0B W$E1 $EC $F0 $E0 $88 $C1 s$B2 $C2 $B6 $08 :$$E2 $DA $B1 $A6 $1B $9C :$1E  $83 K$BB $D0 $81 $EB $97 $04 $7F $DE Z$D2 $A3 !$88 l\$19 b$80 $C7 $B1 Z$CA $A9 =$DF %$81 4,$C0 {$F0 <$1F $84 $A1 1W$85 $0D J;K$AD $10 @$D6 $A5 ~a$8A $F5 $04 TR$F3 Rl$8C #$1E $CA $08 $08 $CE 3$0E ^$E4 7v$10 $00 $E6 $AE _$DF $9C V$83 ,$94 $97 $14 $0C $89 $81 $E3 H$17 '[4$94 $EF $C3 $B5 $A8 $CD $94 $15 $D3 ~8z$D6 $86 i$09 MG $BF $E3 $F3 $D6 4$84 $B4 $90 $9F ^#$C1 -$F4 $D6 $E2 $0D ~|$DF $93 WO{$E1 $D3 $97 $C2 $AD D$9F $8E $BB $11 a$E2 $F1 )3$01 $AB `0'j$C9 $8F fhB$C1 $A0 $06 $AA $DC $EF $9E $FB $E6 B$0D $0B $B6 $ED $00 ~sia:B$12 &$F3 $BB $05 NN$8F $D7
19:16:08:290 ProtoMsg: TLS 1.2 Handshake: Certificate, State: SSLv3 read server certificate B, Recv, DataLen: 1069, Data= 0B0004290004260004233082041F30820307A003020102020840FFA5CC47FD92B7300D06092A864886F70D01010C05003081B1311F301D06035504030C164D6167656E746120446576656C6F706D656E74204341311C301A060355040B0C13446576656C6F706D656E742054657374696E67310F300D06035504080C06537572726579311C301A060355040A0C134D6167656E74612053797374656D73204C7464310B30090603550406130247423110300E06035504070C0743726F79646F6E3122302006092A864886F70D010901161364656C706869406D61677379732E636F2E756B301E170D3137303831313131313231325A170D3230303530373131313231325A30818D3118301606035504030C0F74656C65636F6D2E6D6167656E7461311C301A060355040B0C134D6167656E746120446576656C6F706D656E743116301406035504080C0D4772656174204272697461696E311C301A060355040A0C134D6167656E74612053797374656D73204C7464310B30090603550406130247423110300E06035504070C0743726F79646F6E30820122300D06092A864886F70D01010105000382010F003082010A0282010100BCA5AEC366E8FB755F43443C8D1E84B2C85E1BE26DECE24AF17CC755B55BB8B17141C24998670553D36CC0EE95FE67391CFA35F9D1540D9BA2A6B0DF5858309B0C3D9CB0DD69395F0F102DBD60C63CE0979D040BB5B2C6A0BBF596E4E3F8A15CA1343B7FDA842A8CD9618F9A65E2EB477BFE7A206C6BAB4B37AC06B7BD53F77DAD9D93DC6740CA004A2E814553F80DE3C96ED704765844140D3B2EBF196DD2EE65BC9BE0A40E653D06D4323DFD6BB008924D0B7CB39D2F9E73CB511B94E079038D5699E214ED5A8BEFD8E40A0EA504005D317268FA695885978DD645361AAB31DDAFE521ECC540CFA3A340BF948E8781404F7029B388DAD7BD40C804C09195F90203010001A35D305B300C0603551D130101FF04023000301C0603551D1104153013820F74656C65636F6D2E6D6167656E74618200300E0603551D0F0101FF0404030203F8301D0603551D250416301406082B0601050507030206082B06010505070301300D06092A864886F70D01010C050003820101003851DF0B75F91190440216524FEFC8B53E5E1F5D63B341911AC10B4A7F47C3B005BB0F07DBFD0B57E1ECF0E088C173B2C2B6083A24E2DAB1A61B9C3A1E20834BBBD081EB97047FDE5AD2A321886C5C196280C7B15ACAA93DDF2581342CC07BF03C1F84A13157850D4A3B4BAD1040D6A57E618AF5045452F3526C8C231ECA0808CE330E5EE437761000E6AE5FDF9C56832C9497140C8981E34817275B3494EFC3B5A8CD9415D37E387AD68669094D4720BFE3F3D63484B4909F5E23C12DF4D6E20D7E7CDF93574F7BE1D397C2AD449F8EBB1161E2F1293301AB6030276AC98F666842C1A006AADCEF9EFBE6420D0BB6ED007E7369613A421226F3BB054E4E8FD7
19:16:08:298 VCB> VerifyPeer: Subject = /CN=Magenta Development CA/OU=Development Testing/ST=Surrey/O=Magenta Systems Ltd/C=GB/L=Croydon/emailAddress=delphi@magsys.co.uk
19:16:08:309 VCB> VerifyPeer: Serial  = $00
19:16:08:316 VCB> VerifyPeer: Error   = ok
19:16:08:325 TriggerSslVerifyPeer
19:16:08:333 VCB> VerifyPeer: Subject = /CN=telecom.magenta/OU=Magenta Development/ST=Great Britain/O=Magenta Systems Ltd/C=GB/L=Croydon
19:16:08:340 VCB> VerifyPeer: Serial  = $40ffa5cc47fd92b7
19:16:08:348 VCB> VerifyPeer: Error   = ok
19:16:08:358 TriggerSslVerifyPeer

**Comment by magsys** [comment]
This issue is now resolved and can be closed.  The cause was a change to bio_st in 1.1.1 that broke a kludge to support BIO_test_flags when it was a macro many years ago, and our Delphi header translation needs code to work around macros.  It was never updated to an exported function because it still worked.  Sorry.

**Comment by mattcaswell** [comment]
Ok - thanks for letting us know.
