### ISSUE TITLE
Incorrect handling in DTLS Handshake for SCTP connection causes infinite loop in application

### ISSUE THREAD

**Issue by mahesh116** [openssl/openssl#4763]
There are multiple messages exchanged during DTLS Handshake for SCTP connection. "Client Certificate Request" message sent from server to client requesting the client to send out the public key to authenticate the client. "Client Certificate Request" is not mandatory step in DTLS handshake.

If public key is not configured in client instance and client instance receive "Client Certificate Request" from server during the handshake, this will lead to the infinite loop in application (SSL_Connect will be called infinite number of times). 

![image 1](https://user-images.githubusercontent.com/27770135/33067401-0bb3e164-ced4-11e7-93e1-9671828d06e4.png)

Following is the sequence of events (Attached image above):

1) Client receives "Client Certificate Request" from server.
2) Client instance does not have public key configured, so client respond back with "AUTH Certificate" message with length 0.
3) Server respond with "Handshake Alert" to client.
4) Client try to send out "Client Key Exchange" to server.
5) Client try to construct and send out "Change Cipher Spec" message to server but here enters into section of code which leads the "SSL_Connect" to loop.

![image 2](https://user-images.githubusercontent.com/27770135/33067740-1d73319c-ced5-11e7-946a-ce1b19084236.png)

"Pre-Work" step for "Change Cipher Spec" expects SCTP_SENDER_DRY_EVENT at SCTP Layer but the SCTP layer already has "Handshake Alert" to be read, so SCTP does not raise the SCTP_SENDER_DRY_EVENT event. This "Pre-Work" step never be successful, and always returns SUB_STATE_ERROR causes SSL_Connect to loop in the application. (Please refer the above image for exact section of code causing the problem).

State machine is never moved from write state to read state. "Handshake Alert" is never read by the openssl due to continues failure in "Pre-Work" step for "Change Cipher Spec" message. 

This bug happens to be on SSL_Accept as well. SSL_Accept also enters infinite loop in TLS_ST_SW_SERVER_DONE state.

![image 3](https://user-images.githubusercontent.com/27770135/33259981-8caacea4-d384-11e7-883f-0eb89e836201.png)

![image 4](https://user-images.githubusercontent.com/27770135/33260019-ab2c780a-d384-11e7-9033-fea2feffcc06.png)

This scenario is tested both in openssl 01.01.00g and 01.00.02k (This openssl version which comes along with RHEL 7.4)

**Comment by mahesh116** [comment]
Hi,
Any plans to fix this issue in upcoming releases ?

**Comment by mattcaswell** [comment]
I'm currently away at Real World Crypto 2018 this week. I'll try and take a look at this next week. Ping me if I forget :-)

**Comment by mattcaswell** [comment]
Hmmmm....there is actually a test for this scenario that exercises SCTP:

https://github.com/openssl/openssl/blob/master/test/ssl-tests/04-client_auth.conf.in#L88

I wonder why it doesn't fail?

**Comment by mattcaswell** [comment]
Looks like the test doesn't fail because of a race condition. We move on to writing out the CCS immediately after the empty Certificate message has been written. Because the test is run on the localhost the Certificate message has already been delivered by the time we get to the dtls_wait_for_dry() test. In the test the client and server are taking turns sequentially. Since the message has been delivered and the server hasn't processed it yet (because it hasn't had its turn) the socket is dry so we continue. If the localhost wasn't so fast at delivering it the dtls_wait_for_dry() test would fail first time around, giving the server the opportunity to process what it has got, which would then issue the alert and hit this problem. I can't think of a simple way to change the test to reliably reproduce this which would be suitable for inclusion in the source - but I can "hack" it to do it for the purposes of attempting a fix.

**Comment by mattcaswell** [comment]
Please try the fix in #5084 (master) or #5085 (1.1.0). I've not backported to 1.0.2 at this stage (the code there looks quite different).

**Comment by mahesh116** [comment]
Hello Matt,

Sorry for the delayed response. We have tested the fix and it works fine for us. Would like to hear for you if this fix will be ported to 1.0.2 thread and what version will have this fix ?

**Comment by mattcaswell** [comment]
> Sorry for the delayed response. We have tested the fix in 1.1.0 and it works fine for us. Would like to hear from you if this fix will be ported to 1.0.2 thread and what version will have this fix ?

Thanks for the confirmation. I'm still waiting on a review for the fix. I've just rebased and refreshed it. I'm not currently planning to port to 1.0.2.

**Comment by mattcaswell** [comment]
This fix is now in and will be included in 1.1.0h to be released next week.
