### ISSUE TITLE
Add an easy to use installer for Windows

### ISSUE THREAD

**Issue by meh-uk** [openssl/openssl#477]
The installation process on Windows seems to be pretty painful at the moment as it requires cygwin/perl to be installed and the link to download the PlatformSDK is broken.

Can you just add an MSI file to sort all this out for users please? We want people to secure their sites properly and if the tools aren't easy to use the temptation is very great to simply not bother with security.

Should note as I care about security I'm going to use openssl on my Mac instead which comes with it out the box, but that is a pretty poor workaround.

**Comment by mattcaswell** [comment]
As a project it is our policy to only distribute source code. It is highly unlikely that that policy will change. There are a couple of different places where you can you download precompiled binaries:

https://wiki.openssl.org/index.php/Binaries

**Comment by meh-uk** [comment]
Seems like a reasonable approach for Linux and other *nix based OS's. Doesn't seem like a reasonable approach for Mac OS X or Windows.

A link at least to the wiki page in the Windows 'installer' would be good though.
