### ISSUE TITLE
OpenSSL 1.1.0g Makefile issues

### ISSUE THREAD

**Issue by rbasch** [openssl/openssl#4771]
One traditional approach to source tree management is to create a source tree and to create a separate build tree (which sometimes requires creating links to the source tree). OpenSSL has a few files where it attempts to modify in-place, including ./configdata.pm (new file in 1.1.0g). If you extract a single source tree and create two build trees linking to the source tree files, the default Makefile will try to write through the symlink to the source tree. This is particularly bad if your two builds are for different configurations (e.g. gcc -m32 vs gcc -m64) since configdata.pm will contain incorrect information.

All file modifications (during the config step) should be done using a backup file mechanism, not in-place modification.

**Comment by levitte** [comment]
Errrr, don't symlink, just create a build tree for your purpose and run the config scripts from there.  Like this:

```
# assume the source is in /usr/src/openssl-1.1.0g
$ mkdir /var/tmp/openssl-1.1.0g-m32
$ mkdir /var/tmp/openssl-1.1.0g-m64

# build -m32
$ /usr/src/openssl-1.1.0g/Configure linux-x86
$ make

# build -m64
$ /usr/src/openssl-1.1.0g/Configure linux-x86_64
$ make
```

If you create a lot of symlinks to the source tree from the build tree, you're screwing things up royally...  and quite unnecessarely.  Just... don't.
