### ISSUE TITLE
Incorrect docs for EVP_EncryptUpdate and EVP_DecryptUpdate

### ISSUE THREAD

**Issue by eldiener** [openssl/openssl#4775]
In the docs for EVP_EncryptUpdate and EVP_DecryptUpdate at https://wiki.openssl.org/index.php/Manual:EVP_EncryptInit(3) the 'in' parameter is 'unsigned char *' whereas in the header file the 'in' parameter is 'const unsigned char *'. The online docs need to be corrected.

**Comment by mattcaswell** [comment]
Fixed in master. I'm hoping @FdaSilvaYY will backport to 1.1.0/1.0.2

**Comment by FdaSilvaYY** [comment]
Fully fixed ?

**Comment by mattcaswell** [comment]
Fixed!
