### ISSUE TITLE
Get rid of EVP_MAX_KEY_LENGTH

### ISSUE THREAD

**Issue by p-steuer** [openssl/openssl#4777]
Cipher key lengths are currently limited to EVP_MAX_KEY_LENGTH = 512bits (sufficient for all supported ciphers including xts keys).

However, engine modules may need larger keys to store key objects. E.g. wrapped aes keys:
The engines aes implementation can generate such key objects using the EVP_CIPHER_CTX_ctrl interface together with the EVP_CTRL_RAND_KEY control or the (currently undocumented) higher level EVP_CIPHER_CTX_rand_key interface (having the  EVP_CIPH_RAND_KEY flag set).

I propose to change buffers of EVP_MAX_KEY_LENGTH size to dynamically allocated buffers of size EVP_CIPHER_key_length(cipher).

I see EVP_MAX_KEY_LENGTH is part of this versions api such that it would be applications responsibility to either not depend on it or not use engines that generate larger keys. Future releases could get rid of EVP_MAX_KEY_LENGTH.

What do you think ?

**Comment by mattcaswell** [comment]
I think there is some merit in getting rid of it. But it couldn't go completely until 1.2.0.

**Comment by p-steuer** [comment]
Just found a corresponding note in EVP_EncryptInit(3)'s BUG section:

> EVP_MAX_KEY_LENGTH and EVP_MAX_IV_LENGTH only refer to the internal
ciphers with default key lengths. If custom ciphers exceed these values the
results are unpredictable.

In case you agree to change this for 1.2.0, i would provide a patch to have internal key buffers dynamically allocated. This wouldnt break the the 1.1.x api and id like to see it on master because im working on an engine which uses keys generated/wrapped by a HSM.

Second part would be to remove EVP_MAX_IV_LENGTH and update EVP_EncryptInit(3) for 1.2.0.

**Comment by mattcaswell** [comment]
This isn't going to happen in the 1.1.1 timeframe. Pushing to post 1.1.1 milestone.

**Comment by p-steuer** [comment]
This one could become obsolete with the new provider model, because the work-around fitting a key-object into EVP_MAX_KEY_LENGTH bytes is not needed anymore, once key-objects/keygen becomes supported also for symmetric crypto, see https://github.com/openssl/openssl/issues/8719

**Comment by p-steuer** [comment]
Im closing this in favor of https://github.com/openssl/openssl/issues/10265 which is obviously the better way to do it (compared to allowing arbitrary long keys buffers to hide a key object within).
