### ISSUE TITLE
Load CA certs from a single file

### ISSUE THREAD

**Issue by algv** [openssl/openssl#4780]
I want use two CA certificates in sigle file (s_server -CAfile or SSLCACertificateFile in Apache mod_ssl). Subject names identicaly. Second cert in bundle never load for verify chain. It really correct?

[SSL_load_client_CA_file](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/ssl_cert.c#L873)
```
...
 if ((xn = X509_get_subject_name(x)) == NULL)
            goto err;
        /* check for duplicates */
        xn = X509_NAME_dup(xn);
        if (xn == NULL)
            goto err;
        if (sk_X509_NAME_find(sk, xn) >= 0)
X509_NAME_free(xn);
...
```
In  [RFC 5280](https://tools.ietf.org/html/rfc5280) I cannot find what must check only subject name. Maybe need add subject key identifier?

> To facilitate certification path construction, this extension MUST
>    appear in all conforming CA certificates, that is, all certificates
>    including the basic constraints extension (Section 4.2.1.9) where the
>    value of cA is TRUE.  In conforming CA certificates, the value of the
>    subject key identifier MUST be the value placed in the key identifier
>    field of the authority key identifier extension (Section 4.2.1.1) of
>    certificates issued by the subject of this certificate.  Applications
>    are not required to verify that key identifiers match when performing
>    certification path validation.

**Comment by mattcaswell** [comment]
Please ask this type of question on the openssl-users email list:

https://mta.openssl.org
