### ISSUE TITLE
BIO_write/mem_write behavior change in OpenSSL 1.1

### ISSUE THREAD

**Issue by zecke** [openssl/openssl#4782]
I am looking at client code that looks like:

```
       ssl->bioRead = BIO_new(BIO_s_mem());
....
        n = BIO_write(ssl->bioRead, srcBuf, srcLen);

        if(n < srcLen) {
                if(ssl->loglevel) printf("sqConnectSSL: BIO too small for input\n");
                return SQSSL_GENERIC_ERROR;
        }
```

On connection set-up this might be called with srcLen == 0. Due to the change in mem_write and the BUF_MEM_grow_clean API -1 will be returned now. Apparently the buffer was not grown (it didn't need to). As len < 0 will return 0.. I think len <= 0 should return 0 as well? This could be added to BIO_write?

```
     int ret = -1;
-    blen = bm->length;
-    if (BUF_MEM_grow_clean(bm, blen + inl) != (blen + inl))
+    blen = bbm->readp->length;
+    mem_buf_sync(b);
+    if (BUF_MEM_grow_clean(bbm->buf, blen + inl) == 0)
         goto end;
```

**Comment by zecke** [comment]
This regression was added in e5bf3c923c184b19e8c3ef7043080955479a2325. The commit doesn't discuss the behavior change. Was it accidental?

**Comment by mattcaswell** [comment]
Almost certainly accidental. I can't match up your proposed patch with the current code. Perhaps you'd like to raise this as a PR rather than just an issue?

**Comment by zecke** [comment]
"referenced" this issue. It is a commit in the client code and github saw the url and updated this comment. So you see the "negative" effect on client code... It is also not how "write(2)" syscalls behave..

**Comment by levitte** [comment]
I'm quite amazed this hasn't been discovered before now (ok, half a year ago, but on a scale of 20ish years, that's more or less "now").  Fixing it is easy.
