### ISSUE TITLE
session ticket optimize for openssl-1.0.2j

### ISSUE THREAD

**Issue by cjhust** [openssl/openssl#4784]
according to RFC5077: https://tools.ietf.org/html/rfc5077#page-13
struct {
          ProtocolVersion protocol_version;
          CipherSuite cipher_suite;
          CompressionMethod compression_method;
          opaque master_secret[48];
          ClientIdentity client_identity;
          uint32 timestamp;
      } StatePlaintext;

we delete session_id, session_id_context, timestamp(can ignore), timeout(can ignore), therefore session ticket's length reduced from 103 byte to 63 byte.

we delete timestamp and timeout because of using nginx, ticket key can change every once in a while.

this is our patch:
https://github.com/cjhust/ngx_mod/blob/master/patches/openssl-1.0.2j-session-ticket-trim.patch

**Comment by mattcaswell** [comment]
Thanks. I'm going to close this issue because we do not accept new feature patches against the 1.0.2 branch. However it will remain on github in a "closed" state for others to see your patch. If you'd like to submit a patch against the master branch then please open a pull request.
