### ISSUE TITLE
SSL conf module is added too late

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#4788]
If you configure openssl.cnf as expected i.e. to contain:

```
openssl_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ ssl_sect ]

sapps = sapps_sect

[ sapps_sect ]

Protocol = ....

```
It will not work when openssl s_client is called with '-ssl_config sapps' option.

openssl s_client -ssl_config sapps ...
Error using configuration "sapps"
139853230610176:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
139853230610176:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
139853230610176:error:0E07506E:configuration file routines:module_load_dso:error loading dso:crypto/conf/conf_mod.c:222:module=ssl_conf, path=ssl_conf
139853230610176:error:0E076071:configuration file routines:module_run:unknown module name:crypto/conf/conf_mod.c:164:module=ssl_conf
139853230610176:error:14187071:SSL routines:ssl_do_config:invalid configuration name:ssl/ssl_mcnf.c:152:name=sapps

The reason is that the SSL conf module is added too late as it is added after the default configuration file is already loaded.

This patch basically fixes the issue, however I understand that it is not portable.

```
diff --git a/crypto/conf/conf_mall.c b/crypto/conf/conf_mall.c
index 4e7a434..1c8f289 100644
--- a/crypto/conf/conf_mall.c
+++ b/crypto/conf/conf_mall.c
@@ -7,6 +7,8 @@
  * https://www.openssl.org/source/license.html
  */
 
+#define _GNU_SOURCE
+
 #include <stdio.h>
 #include <openssl/crypto.h>
 #include "internal/cryptlib.h"
@@ -15,10 +17,16 @@
 #include <openssl/asn1.h>
 #include <openssl/engine.h>
 
+#ifdef HAVE_DLFCN_H
+# include <dlfcn.h>
+#endif
+
 /* Load all OpenSSL builtin modules */
 
 void OPENSSL_load_builtin_modules(void)
 {
+    void (*SSL_module_add_fn)(void);
+
     /* Add builtin modules here */
     ASN1_add_oid_module();
     ASN1_add_stable_module();
@@ -26,4 +34,9 @@ void OPENSSL_load_builtin_modules(void)
     ENGINE_add_conf_module();
 #endif
     EVP_add_alg_module();
+#ifdef HAVE_DLFCN_H
+    SSL_module_add_fn = dlsym(RTLD_DEFAULT, "SSL_add_ssl_module");
+    if (SSL_module_add_fn != NULL)
+        SSL_module_add_fn();
+#endif
 }
```

**Comment by t8m** [comment]
Probably the load of the SSL conf module code should all be moved to libcrypto as otherwise for applications using just the libcrypto although they do not care about the SSL conf stuff they would still encounter the libssl_conf.so load errors.

**Comment by levitte** [comment]
Please try out #4792, I do believe that fixes your issue.

**Comment by t8m** [comment]
Yes, that fixes the issue with openssl apps. The remaining question is what happens if some 3rd party application calls OPENSSL_init_crypto() but uses some shared library that uses libssl for TLS communication (and calls itself OPENSSL_init_ssl()).

**Comment by t8m** [comment]
As a test I tried to call both OPENSSL_init_crypto() and OPENSSL_init_ssl() in the apps_startup() and as expected this makes it not to work correctly again. So yes, the #4792 fixes the issue for openssl app but it is not completely general solution.

**Comment by levitte** [comment]
Generally speaking, we're thinking that an application shouldn't need to use `OPENSSL_init_crypto` or `OPENSSL_init_ssl`, as these are called internally when needed.  Secondly, I'd say that an application that knowingly uses *anything* that ends up calling libssl routines should call `OPENSSL_init_ssl` before `OPENSSL_init_crypto`, if that's at all needed.

Remains, of course, cases when the load and use of libssl isn't a known fact, or when it so happens that `OPENSSL_init_crypto` gets called first, for whatever reason...  I'll dive into this.  @mattcaswell, if you have any ideas around this, it would be helpful.

**Comment by mattcaswell** [comment]
The whole point about OPENSSL_init_crypto() and OPENSSL_init_ssl() was that they (in most cases) should be implicit and called automatically. Similarly you shouldn't need to explicitly clean up the library. In previous version of OpenSSL there has been the problem where two different libraries loaded by an application both have a dependency on OpenSSL and then they have a battle about initialisation and de-initialisation. In that scenario you could easily envisage a case where one external library has a dependency on libcrypto (only) and one has a dependency on both libcrypto and libssl. Depending on the order these external libraries get called then OPENSSL_init_crypto() could get called before OPENSSL_init_ssl(). Unfortunately I don't have any great ideas for solving it... :-(

**Comment by t8m** [comment]
Well, my patch above actually solves it, but unfortunately it is a hack and not something that could be committed.

On the other hand as loading the configuration is done explicitly only when OPENSSL_init_crypto() is called with OPENSSL_INIT_LOAD_CONFIG I suppose this might not be a pronounced problem in real world.

**Comment by levitte** [comment]
Right...  and the hack could be made useful, as that's basically a poor man's implementation of weak symbols, so to speak.

Another thing I'm considering is lazy evaluation, i.e. read a process the config file as late as possible.  In other words, `CONF_modules_load_file` and friends could just register the file name, but the actual reading would only happen the first time anyone tries to use its values.

**Comment by levitte** [comment]
Cancel the lazy evaluation idea, it was a bad one...

**Comment by levitte** [comment]
@t8m, you're actually more right than you might know...  I needed to re-read the manpage to jog my memory about this all.

The relevant section (from https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_init_crypto.html):

> Numerous internal OpenSSL functions call OPENSSL_init_crypto(). Therefore, in order to perform non-default initialisation, OPENSSL_init_crypto() MUST be called by application code prior to any other OpenSSL function calls.

I find it troublesome, though, that only `OPENSSL_init_crypto` is mentioned here.  @mattcaswell, what would you say about the idea of merging the `OPENSSL_init_crypto` and `OPENSSL_init_ssl` manual pages into one for 1.1.1?

**Comment by richsalz** [comment]
My guess is that they were separate because crypto and ssl were separate subdirs until recently.

**Comment by levitte** [comment]
Yes, that's my guess as well.

**Comment by mattcaswell** [comment]
Yes that was the reason. I have no problem with merging the pages.
