### ISSUE TITLE
not allocated lock in store

### ISSUE THREAD

**Issue by mohamadpk** [openssl/openssl#4794]
hi. i use openssl in c++ for curl.i set CURLOPT_SSL_CTX_FUNCTION option to a function then curl call my ctx function. on ctx fucntion my code is `X509_STORE *store;
  X509 *cert = NULL;
  BIO *bio;
  char *mypem =
	  "-----BEGIN CERTIFICATE-----\n"
	  "MIIDxTCCAq2gAwIBAgIBADANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx\n"
	  "EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT\n"
	  "EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp\n"
	  "ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTA5MDkwMTAwMDAwMFoXDTM3MTIzMTIz\n"
	  "NTk1OVowgYMxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH\n"
	  "EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjExMC8GA1UE\n"
	  "AxMoR28gRGFkZHkgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjCCASIw\n"
	  "DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL9xYgjx+lk09xvJGKP3gElY6SKD\n"
	  "E6bFIEMBO4Tx5oVJnyfq9oQbTqC023CYxzIBsQU+B07u9PpPL1kwIuerGVZr4oAH\n"
	  "/PMWdYA5UXvl+TW2dE6pjYIT5LY/qQOD+qK+ihVqf94Lw7YZFAXK6sOoBJQ7Rnwy\n"
	  "DfMAZiLIjWltNowRGLfTshxgtDj6AozO091GB94KPutdfMh8+7ArU6SSYmlRJQVh\n"
	  "GkSBjCypQ5Yj36w6gZoOKcUcqeldHraenjAKOc7xiID7S13MMuyFYkMlNAJWJwGR\n"
	  "tDtwKj9useiciAF9n9T521NtYJ2/LOdYq7hfRvzOxBsDPAnrSTFcaUaz4EcCAwEA\n"
	  "AaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE\n"
	  "FDqahQcQZyi27/a9BUFuIMGU2g/eMA0GCSqGSIb3DQEBCwUAA4IBAQCZ21151fmX\n"
	  "WWcDYfF+OwYxdS2hII5PZYe096acvNjpL9DbWu7PdIxztDhC2gV7+AJ1uP2lsdeu\n"
	  "9tfeE8tTEH6KRtGX+rcuKxGrkLAngPnon1rpN5+r5N9ss4UXnT3ZJE95kTXWXwTr\n"
	  "gIOrmgIttRD02JDHBHNA7XIloKmf7J6raBKZV8aPEjoJpL1E/QYVN8Gb5DKj7Tjo\n"
	  "2GTzLH4U/ALqn83/B2gX2yKQOC16jdFU8WnjXzPKej17CuPKf1855eJ1usV2GDPO\n"
	  "LPAvTK33sefOT6jEm0pUBsV/fdUID+Ic/n4XuKxe9tQWskMJDE32p2u0mYRlynqI\n"
	  "4uJEvlz36hz1\n"
	  "-----END CERTIFICATE-----\n";
  bio = BIO_new_mem_buf(mypem, -1);

  PEM_read_bio_X509(bio, &cert, 0, NULL);
  if(cert == NULL)
    printf("PEM_read_bio_X509 failed...\n");
 
  store = SSL_CTX_get_cert_store((SSL_CTX *)sslctx);

  if(X509_STORE_add_cert(store, cert) == 0)
    printf("error adding certificate\n");
 

  X509_free(cert);
  BIO_free(bio);`
on call to X509_STORE_add_cert the application open crash dialog Access violation reading location 0x00000000. i open store in visual studio see 
![image](https://user-images.githubusercontent.com/4367879/33233997-76dcd88e-d234-11e7-87e6-8a6ecd022926.png)

then change all 0x00000000 to number from 1 to 11 for detect what 0 is my problem then resume program and error occurred on 
![image](https://user-images.githubusercontent.com/4367879/33234030-e2dd0888-d234-11e7-8ec2-3fd417036316.png)

11 means 
![image](https://user-images.githubusercontent.com/4367879/33234035-fae73cc8-d234-11e7-8f73-db685488b868.png)

 lock is 0x00000000 as you can see in my first image. 1.why lock is important and 2.why is not allocated? 3. why error occurred on X509_STORE_add_cert. tnx. this is a long story such as Harry Potter.

**Comment by mattcaswell** [comment]
Looks like the store has not been initialised properly. How do you create `sslctx`?

**Comment by mattcaswell** [comment]
No response from OP so closing.
