### ISSUE TITLE
the exe compiled from OpenSSL 1.1.0 with Cygwin 64bit can't decrypt chinese string normally

### ISSUE THREAD

**Issue by auxo86** [openssl/openssl#4799]
I try to compile OpenSSL 1.1.0g with Cygwin 64bit under Cygwin-x86_64 config mode.
After test, I found that it can't decrypt chinese string normally with aes-256-cbc cipher. For example, 

**under cygwin64:**
$ echo 今天天氣真晴朗，處處梅花香。 | openssl aes-256-cbc -e -a -pass pass:1234
U2FsdGVkX1+Jyyk/vJogKFqjztsqpul8gQ4MJNG1869LT+QkR/3geV4CR59ofu/7
X9Zk/96cAHMnu6+vxctrkQ==

auxo@clinicinfo-7 ~/openssl-1.1.0g
$ echo U2FsdGVkX1+Jyyk/vJogKFqjztsqpul8gQ4MJNG1869LT+QkR/3geV4CR59ofu/7 | openssl aes-256-cbc -d -a -pass pass:1234
bad decrypt
0:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:536:
今天天氣真▒

**under win10 CMD:**
c:\OpenSSL\gcc-win64a\bin>echo 今天天氣真晴朗，處處梅花香。 | openssl aes-256-cbc -e -a -pass pass:1234
U2FsdGVkX1+OhiEY8cO2wIjyq1oMoLC3QR9XaIJbHYoojEz12XJIeYyk/3uGfgq0

c:\OpenSSL\gcc-win64a\bin>echo U2FsdGVkX1+OhiEY8cO2wIjyq1oMoLC3QR9XaIJbHYoojEz12XJIeYyk/3uGfgq0 | openssl aes-256-cbc -d -a -pass pass:1234
▒▒▒ѤѮ▒▒u▒▒▒ԡA▒B▒B▒▒▒᭻▒C

Any idea will be appreciate.

Best, 
auxo

**Comment by levitte** [comment]
That's because you're only echoing back part of the armored encrypted string.  The full string (2 lines) is this:

```
U2FsdGVkX1+Jyyk/vJogKFqjztsqpul8gQ4MJNG1869LT+QkR/3geV4CR59ofu/7
X9Zk/96cAHMnu6+vxctrkQ==
```

If I feed it all back to OpenSSL, here's what I get on Linux:

```
: ; (echo U2FsdGVkX1+Jyyk/vJogKFqjztsqpul8gQ4MJNG1869LT+QkR/3geV4CR59ofu/7; echo X9Zk/96cAHMnu6+vxctrkQ==) | openssl aes-256-cbc -d -a -pass pass:1234
今天天氣真晴朗，處處梅花香。
```

It might be safer to save the encryption result on file and feed that to the decryption command...

**Comment by auxo86** [comment]
Sorry for my butter fingers to make the copy/paste error, it’s my fault.

I redo the test again.

Under Cygwin:
$ echo 今天天氣真晴朗，處處梅花香。 | openssl aes-256-cbc -e -a -pass pass:1234
U2FsdGVkX1/r5vIhZG+U3FKcF4kslsRXkl21a6GA6tEsk/3PjvqGqH+g22YuZBcO
uREu72Woc4W7Zg4BMG6gEw==

$ echo U2FsdGVkX1/r5vIhZG+U3FKcF4kslsRXkl21a6GA6tEsk/3PjvqGqH+g22YuZBcOuREu72Woc4W7Zg4BMG6gEw== | openssl aes-256-cbc -d -a -pass pass:1234
今天天氣真晴朗，處處梅花香。

The result is good.

However,  the same exe under windows shell (cmd):

c:\OpenSSL\gcc-win64a\bin>echo 今天天氣真晴朗，處處梅花香。 | openssl aes-256-cbc -e -a -pass pass:1234
U2FsdGVkX1/z/ms01DpXGgd0sCV3zzClOayO1WWq8Q0HOqAPSRdrWERvVuK72dUF

c:\OpenSSL\gcc-win64a\bin>echo U2FsdGVkX1/z/ms01DpXGgd0sCV3zzClOayO1WWq8Q0HOqAPSRdrWERvVuK72dUF | openssl aes-256-cbc -d -a -pass pass:1234
▒▒▒ѤѮ▒▒u▒▒▒ԡA▒B▒B▒▒▒᭻▒C C

Let’s do it again:
c:\OpenSSL\gcc-win64a\bin>echo 今天天氣真晴朗，處處梅花香。 | openssl aes-256-cbc -e -a -pass pass:1234
U2FsdGVkX1/0dnrcxr3I+vsNpygB91VZuul0/UDB0RCKk9f4NnaVlEZ7sDeRMjcG

c:\OpenSSL\gcc-win64a\bin>echo U2FsdGVkX1/0dnrcxr3I+vsNpygB91VZuul0/UDB0RCKk9f4NnaVlEZ7sDeRMjcG | openssl aes-256-cbc -d -a -pass pass:1234
▒▒▒ѤѮ▒▒u▒▒▒ԡA▒B▒B▒▒▒᭻▒C

It’s weird, isn’t it?

Best,

Axuo

**Comment by levitte** [comment]
(so I'm reopening this)

**Comment by dot-asm** [comment]
First question is what goes through that pipe. What do cygwin echo and Windows echo emit? Cygwin ought to emit UTF-8, and Windows - UTF-16. That explains why ciphertexts are different. Indeed, you're encrypting different inputs, and UTF-8 representation would be longer for Chinese. Secondly, as for decrypted output appearing garbled in second case. Well, question is what does cygwin run-time does when application code attempts to emit binary stream on standard output. Does it pay attention to code page/system locale? Assumes UTF-8? Performs any conversions? And how is output rendered? I mean if you consider cygwin example, it was surely executed in "cygwin terminal". Note that when openssl -d issued UTF-8 it was rendered readable. Would it be [as] readable if an application generated UTF-8 output in Windows console? Bottom line is that it's not more weird than mismatching expectations. But either way, it's not openssl problem, it's all about what it gets on input and how output is rendered. Original suggestion to stick with files is the one that eliminates ambiguity, and is the only one sensible...

**Comment by dot-asm** [comment]
> Would it be [as] readable if an application generated UTF-8 output in Windows console?

Reversed can be asked too. I.e. how would output look like if an application issued UTF-16 in "cygwin terminal". As simplest example create file with notepad with text in question, save it as Unicode (which Microsoftish for UTF-16), and try to `cat` it in UTF-8-oriented "cygwin terminal"...

**Comment by auxo86** [comment]
After doing some research on MSDN, the default windows shell code page under Chinese windows is 950.
Fortunately, we can change the code page to utf8 using command chcp, like this:

chcp 65001

Then we can use openssl compiled by Cygwin:
c:\OpenSSL\gcc-win64a\bin>echo 今天天氣真晴朗，處處梅花香 | openssl aes-256-cbc -e -a -pass pass:1234
U2FsdGVkX1+M+TF1+jxbC835kEUJ+7/G0xUQEOrlBarxJ7on6zWnxoT4cBeuLDfd
tmXS6fj3tOnKTG3nagNilg==

c:\OpenSSL\gcc-win64a\bin>echo U2FsdGVkX1+M+TF1+jxbC835kEUJ+7/G0xUQEOrlBarxJ7on6zWnxoT4cBeuLDfdtmXS6fj3tOnKTG3nagNilg== | openssl aes-256-cbc -d -a -pass pass:1234
今天天氣真晴朗，處處梅花香

It really works.
However, If you want to write a wrapper for openssl.exe in c# like me, try to compile the openssl source code with vc++. It is ready to use without such problem.

**Comment by richsalz** [comment]
So should this issue be closed, or is there something for openssl to do here?

**Comment by dot-asm** [comment]
I reckon it should be closed. As already mentioned it's not openssl problem. Nor should it be problem with VC build.
