### ISSUE TITLE
Unchecked EVP_MD_CTX_new() return value in CMS_SignerInfo_verify()

### ISSUE THREAD

**Issue by FlyerEye** [openssl/openssl#4800]
File: crypto/cms/cms_sd.c
Function: CMS_SignerInfo_verify()
Line: 718

Function EVP_MD_CTX_new() returns a NULL pointer if there is no enough memory. To avoid potential NULL dereference, its return value should be checked against NULL. However, in function CMS_SignerInfo_verify(), its return value is directly used without NULL check (see line 720). This may result in a NULL dereference bug.

For your convenience, I copy and paste related bugs as follows.

717     if (si->mctx == NULL)
718         si->mctx = EVP_MD_CTX_new();
719     mctx = si->mctx;
720     if (EVP_DigestVerifyInit(mctx, &si->pctx, md, NULL, si->pkey) <= 0)
721         goto err;

Thanks,
Pan Bian

**Comment by richsalz** [comment]
Thank you.  Fixed in master and 1.1.0
