### ISSUE TITLE
statem_dtls: return a correct value on error path

### ISSUE THREAD

**Issue by FlyerEye** [openssl/openssl#4807]
File: ssl/statem/statem_dtls.c
Function: dtls_construct_change_cipher_spec
Lines: 890~893

Function dtls_construct_change_cipher_spec() always returns 1 on both success and failure paths. Maybe, 0 should be returned when the call to WPACKET_put_bytes_u16() fails (see line 890).

For your convenience, I copy and paste related codes as follows:

 885 int dtls_construct_change_cipher_spec(SSL *s, WPACKET *pkt)
 886 {
 887     if (s->version == DTLS1_BAD_VER) {
 888         s->d1->next_handshake_write_seq++;
 889 
 890         if (!WPACKET_put_bytes_u16(pkt, s->d1->handshake_write_seq)) {
 891             SSLerr(SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC, ERR_R_INTERNAL_ERROR);
 892             ssl3_send_alert(s, SSL3_AL_FATAL, SSL_AD_INTERNAL_ERROR);
 893         }
 894     }
 895 
 896     return 1;
 897 }

As a comparison, function tls_construct_change_cipher_spec() (defined in file ssl/statem/statem_lib.c) returns 0 when the put action fails. Shown as follows:

 845 int tls_construct_change_cipher_spec(SSL *s, WPACKET *pkt)
 846 {
 847     if (!WPACKET_put_bytes_u8(pkt, SSL3_MT_CCS)) {
 848         SSLerr(SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC, ERR_R_INTERNAL_ERROR);
 849         ssl3_send_alert(s, SSL3_AL_FATAL, SSL_AD_INTERNAL_ERROR);
 850         return 0;
 851     }
 852 
 853     return 1;
 854 }

Thanks,
Pan Bian

**Comment by mattcaswell** [comment]
Yeah, it should return 0. I actually have a fix for this already in #4778.
