### ISSUE TITLE
Failed to parse/decompose certReqInfo.der file

### ISSUE THREAD

**Issue by tejas3** [openssl/openssl#4811]
Openssl version: OpenSSL 1.0.2l
Command used: openssl asn1parse -inform der -in CertReqInfo.der
CertReqInfo.der contains x509_req->req_info data
error: 15772:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:.\crypto\asn1\asn1_lib.c:147:

**Comment by richsalz** [comment]
There is not enough information -- can you base64 encode and post the DER file?

**Comment by tejas3** [comment]
[CertReqInfo.txt](https://github.com/openssl/openssl/files/1510732/CertReqInfo.txt)

Please rename above file with der instead of txt  *CertReqInfo.der*

**Comment by richsalz** [comment]
The DER encoding claims it wants 193 bytes, but the file is only 130.  Are you sure it wasn't truncated?

**Comment by levitte** [comment]
I suspect a conversion has been made somewhere along the way.  Here's what the file looks like after I've downloaded it, shown with `od -c`:

```
: ; od -c CertReqInfo.txt 
0000000   0 201 301 002 001 001   0   _   1  \v   0  \t 006 003   U 004
0000020 006 023 002   I   N   1  \v   0  \t 006 003   U 004  \b  \f 002
0000040   W   I   1 022   0 020 006 003   U 004  \a  \f  \t   M   i   l
0000060   w   a   u   k   e   e   1  \v   0  \t 006 003   U 004  \v  \f
0000100 002   B   E   1 024   0 022 006 003   U 004 003  \f  \v   8   8
0000120   :   2   2   :   3   2   :   4   9   1  \f   0  \r  \n 006 003
0000140   U 004  \r  \n  \f 003   x   y   z   0   Y   0 023 006  \a   *
0000160 206   H 316   = 002 001 006  \b   * 206   H 316   = 003 001  \a
0000200 003   B
0000202
```

Notice the `\r\n` sequences in there?  I'll bet a good amount that at least on of them were originally `\n`...

**Comment by tejas3** [comment]
yes, got it. Thanks
Closing issue
