### ISSUE TITLE
FIPS:  Periodic DRBG health check does not block crypto operations

### ISSUE THREAD

**Issue by tfs1969v2** [openssl/openssl#4814]
The crux of the issue is what is the difference between post_failure and fips_post_fail in fips_post.c.  fips_post_fail is the “real” guard from crypto operations continuing forward after a KAT / Health / selftest failure.

There are 2 interesting APIs – 

fips_post_failed (sets post_failure)

fips_set_selftest_fail(sets fips_post_fail)

The DRBG sets post_failure in the FIPS_drbg_health_check(), using fips_post_failed() – but if the health check fails (during one of the “interval” health checks while initing – FIPS_drbg_generate() or reseeding, FIPS_drbg_reseed()), the DRBG and other crypto operations will still function.  

Note that if it fails during a FIPS_selftest(), it will set the appropriate value, and block subsequent crypto operations.  

For all of the algs, the DRBG is the only one with this behavior (but the DRBG is really the only “interval” check that runs), meaning it calls fips_post_failed() (which sets post_failure, but not fips_post_fail through a call to fips_set_selftest_fail()).

I believe this is likely an oversite in the code, as this check only happens 2^24 operations, unless you dork with it in the debugger, or set the drbg health interval to a small number.  I believe that a call to fips_set_selftest_fail() is missing from the drbg health check (see fips_check_ec() and fips_check_rsa(), which set both post_failure and fips_post_fail).

It is clearly a very minor issue, if it is one at all.  I’m not certain if the DRBG is subject to the same FIPS restrictions as the actual key algs if a health check fails during a periodic call, but I think it should be.  I would love someone to tell me this is a non issue because of section XYZ of the FIPS certification document.   Let me know if you want code to repro - really can be done easily by adding small reseed and check intervals to the DRBG_CTX, and forcing a fips_drbg_kat() failure in the debugger.

FIPS_drbg_set_check_interval(dctx, 1)
FIPS_drbg_set_reseed_interval(dctx, 1);

**Comment by richsalz** [comment]
The current FIPS code is frozen -- no new changes, no revalidation. We will be working on a new release based on 1.1.x stream.

**Comment by tfs1969v2** [comment]
Thanks - would you agree that this is a legitimate FIPS certification issue and my proposed fix (adding fips_set_selftest_fail() to the FIPS_drbg_health_check()) is the right thing to do?

**Comment by richsalz** [comment]
It appears to be a legitimate issue, but if you change a line of code the validation is no longer valid.

**Comment by tfs1969v2** [comment]
We hit this during our own FIPS validation, and will likely just be doing a patch for our distribution.

**Comment by batmaninpink** [comment]
I experience this issue far more often than every 2^24 operations - it seems to be triggered by my laptop going into sleep/resume while having a VPN client in FIPS-mode running - when it comes back from sleep it fairly often goes into a state where all crypto operations fail with:

 error:2D071086:FIPS routines:FIPS_drbg_generate:selftest failed

**Comment by t8m** [comment]
The old FIPS module is not supported anymore. Closing.
