### ISSUE TITLE
DER encoding of ASN.1 BOOLEAN is 0xff instead of 0x01

### ISSUE THREAD

**Issue by johndoe31415** [openssl/openssl#4817]
Dear OpenSSL devs,

I've just encountered something that I find very curious and believe it may be a bug. With 92b1b9a8 I see the following behavior:

```
$ openssl req -new -nodes -subj "/CN=Foo" -x509 | openssl asn1parse -i 
[...]
  476:d=4  hl=2 l=  15 cons:     SEQUENCE          
  478:d=5  hl=2 l=   3 prim:      OBJECT            :X509v3 Basic Constraints
  483:d=5  hl=2 l=   1 prim:      BOOLEAN           :255
  486:d=5  hl=2 l=   5 prim:      OCTET STRING      [HEX DUMP]:30030101FF
```

I.e., the BOOLEAN ASN.1 value that indicates if the extension is critical or not is encoded as 0xff insead of 0x01. I'm not an expert in ASN.1, so I'm not 100% sure if this is correct; however I do believe that this is valid BER, but not valid DER (where BOOLEAN true would be encoded as 0x01).

I encountered this because I was dissecting X.509 certs with pyasn1 and re-encoding them as DER -- the difference showed up there.

Also note that this behaviour appears for quite a while in OpenSSL (at least since August, which was my original version before I recompiled with HEAD to check if it was fixed aleady).

Kind regards,
Johannes

**Comment by levitte** [comment]
I can confirm this behavior for 1.1.0g.

**Comment by levitte** [comment]
However, the TRUE value for BOOLEAN is indeed encoded 0xFF.  There is no difference between BER and DER in this regard.  Perhaps you're up the BOOLEAN value with the data type tag for BOOLEAN, which is indeed 0x01?

See https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf, page 6

**Comment by johndoe31415** [comment]
Oh, indeed! Thanks for the clarification.

I'm guessing this is a bug in pyasn1, then, and will report it there accordingly. Sorry for the noise.
