### ISSUE TITLE
max count of certificates in CA file

### ISSUE THREAD

**Issue by algv** [openssl/openssl#4819]
What maximum count of certificates can use in CA file? If count bigger than some value handshake will failed.

Example:

_server:_
> openssl s_server -key '/test/key.pem' -cert '/test/cert.pem' -CAfile '/test/bundle.crt'  -accept 4444 -www -Verify 2

_client:_
> openssl  s_client -connect localhost:4444

CA files for testing: [ca.zip](https://github.com/openssl/openssl/files/1514264/ca.zip)

Now, for bundle with 300 certificates all work. But for 600 failed. Out to termainal:
_s_server:_

```
139902460221080:error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error:s3_pkt.c:1487:SSL alert number 50
139902460221080:error:140780E5:SSL routines:ssl23_read:ssl handshake failure:s23_lib.c:137:
```

_s_client:_

```
CONNECTED(00000003)
depth=0 C = RU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 C = RU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = localhost
verify return:1
140457918953112:error:1408709F:SSL routines:ssl3_get_certificate_request:length mismatch:s3_clnt.c:2171:
140457918953112:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
Certificate chain
 0 s:/C=RU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=localhost
   i:/C=RU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=localhost
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDhTCCAm2gAwIBAgIJAIqASWpVLKlnMA0GCSqGSIb3DQEBCwUAMFkxCzAJBgNV
BAYTAlJVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0xNzExMjkxNDA3
MDlaFw0xNzEyMjkxNDA3MDlaMFkxCzAJBgNVBAYTAlJVMRMwEQYDVQQIDApTb21l
LVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxEjAQBgNV
BAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ+X
q9e9E4AOmoRebBmj2sqfrXxqkG9nHoa11rDn4bryZnwPcLZs4taIScfDSlNXPpF6
CYmnyGKAqmVQruMf9qx9mWEDhRDG+n4p4UtqGk6TM12lK1ggWs+958fgi/Bhv1H4
MzxLo9t9rSINOFyz8lOxAvoGn2BJBjIVO7kccR5FeTvPu5tl5HAJsw8/NBdxL8p3
JIc5WWceyvIdgQve0ojCkqZtdN0A5UBoHNn5AztEZBXj/vSlMDj6cphaLxzV0q1z
Itr2LZGAUYFxMciRw0f1AqfgxprAuhEizqjhw5iqISs3cQbVLWTp2FYexHi3h5go
89z+PPiJhlt3CmdwPo8CAwEAAaNQME4wHQYDVR0OBBYEFPL1Bw/w25nWNT1KRW9M
gmwoVov5MB8GA1UdIwQYMBaAFPL1Bw/w25nWNT1KRW9MgmwoVov5MAwGA1UdEwQF
MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHaco90X6fSOakdQ1dmHMIND8I8zbUbw
U+COgrCTLNILwpZrR1YcTTBOGd6SvBYO5hcciEsi68Iqf3MozujWOHeP6+Fu1bHq
IPBb4dHOkCuM28JmlYrJX1+9nKkGrCCYN3c/4NDl1704hbNLOk34oOkPm/uHoXeV
HHqxrXGk8Cw/ojca6XZiRQX8AZwuUKBJHMpPL+P5oeorIZRNChIfATDDdi3iKnor
3AiRBH02e595V1mFgl0m79BxWvqJg8jHFCoDnveUkES3Hzii2n9M4Ax4eDtMgWC9
cwQ1oXd1mnMp/Ostl9c7aqBH9wpSJTt6eNq0uE8jCE7nIlQGcFziVvs=
-----END CERTIFICATE-----
subject=/C=RU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=localhost
issuer=/C=RU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=localhost
---
No client certificate CA names sent
Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 76292 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1511968940
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
```

(also connection to apache from browser with big CA file not work)

**Comment by mattcaswell** [comment]
Interesting. That is an insanely large CA file to be using.

The issue is that you are requesting a certificate from the client. The server will send a certificate request message from the server to the client listing all of the permissible CA names that the server will accept. The TLS protocol defines that the maximum length of that list is 65535 bytes. In the example bundle that you provided each CA name is consuming between 123 and 125 bytes, so approximately you're going to blow the limit at around 524 certificates.

Interestingly OpenSSL 1.0.2 and 1.1.0 don't handle that very well. They end up sending a malformed CertificateRequest message if you go over the limit. 1.1.1-dev does better and correctly detects the problem (due to the new WPACKET improvements we put in place) and aborts the connection before attempting to send a malformed message.

**Comment by algv** [comment]
Thanks for answer. I testing server with accredited in our country CA (this bundle: [CROSS_DUC.zip](https://github.com/openssl/openssl/files/1514998/CROSS_DUC.zip))

Parse to openssl supporting format:

> openssl.exe pkcs7 -inform DER -outform PEM -in ./CROSS_DUC.p7b -print_certs > ./certificate_bundle.cer

And users cannot connect..

**Comment by richsalz** [comment]
Note that if the server sends *NO* names, then the client is free to send any cert that it has. You might have to change you code to work that way and do extra validation work in your server application code.

Having answered the question, can this issue be closed?

**Comment by algv** [comment]
Yes, can closed. Thanks for the clarification.

**Comment by algv** [comment]
apache: https://bz.apache.org/bugzilla/show_bug.cgi?id=61929
