### ISSUE TITLE
Memory leak in OpenSSL EVP example

### ISSUE THREAD

**Issue by thomasvanhesteren** [openssl/openssl#4820]
Hi,

I found a memory leak in the example code on [this page](https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption).

The problem is that the cleanup functions are called in the wrong order, leading to a (huge) memory leak:
```
EVP_cleanup();
ERR_free_strings();
```

To fix this memory leak the cleanup should be called as:
```
ERR_free_strings();
EVP_cleanup();
```

Could anyone please edit the wiki page in order to save other developers a lot of time 👍

**Comment by richsalz** [comment]
Updated the wiki; it uses the auto-init stuff (and mentions that in the text) from 1.1.0
No leaks :)
Thanks for reporting this!
