### ISSUE TITLE
Question about the HASH_CTX structure

### ISSUE THREAD

**Issue by sequencer** [openssl/openssl#4822]
Hello, recently I'm reading the SHA256 implementing in openssl
However, I have some question, and Googled them without any solution.
at https://github.com/openssl/openssl/blob/e670e90319b902de528db0d22d7197b5de1f4891/crypto/include/internal/md32_common.h#L31
the `Nl,Nh;` are defined, and without any initiate. at 
https://github.com/openssl/openssl/blob/e670e90319b902de528db0d22d7197b5de1f4891/crypto/include/internal/md32_common.h#L256
`c->Nl` are used.
about L256-L259, I'm confusing about this.

What `HASH_LONG       Nl,Nh;` in HASH_CTX?

**Comment by levitte** [comment]
Nh and Nl hold the total message length in number of bits.  Nh is the higher half, Nl iss the lower half.  It's made this way to allow 64 bits to be stored on L32 architectures.

This length is needed for the final padding (see `HASH_FINAL`)
