### ISSUE TITLE
ASN1 templates: application tags for sequences?

### ISSUE THREAD

**Issue by olegst90** [openssl/openssl#4823]
Sorry if it's not a right place to ask such questions, the thing is I'm trying to use new asn.1 templates feature and in my asn module I use custom application tags. How do I specify them in sequences definition  using macros from asnt1.h? 

I mean, I have such a bnf:

Foo ::= [APPLICATION 13] SEQUENCE { 
        m01 INTEGER,
	m02 OCTET STRING
}

And I need to override default sequence tag.

**Comment by levitte** [comment]
The appropriate place for this kind of question is openssl-users@openssl.org.  You do need to subscribe, please see [here](https://www.openssl.org/community/mailinglists.html) for more info.
