### ISSUE TITLE
Howto remove compiled openssl1.1.1-dev from debian ?

### ISSUE THREAD

**Issue by tvequaud** [openssl/openssl#4824]
I had to compile openssl from sources on a Debian Stretch. But now I want to go back to official package openssl from Debian. I tried to remove with apt, dpk, remove everything with locate + rm commands... Still have this f**** reference to openssl 1.1.1-dev

```
root@sd-101643:~# openssl version
OpenSSL 1.1.0f  25 May 2017 (Library: OpenSSL 1.1.1-dev  xx XXX xxxx)
```
 How to remove this ?????

**Comment by levitte** [comment]
`apt` and `dpkg` wouldn't know about 1.1.1-dev unless you have a Debian package for it.

How exactly did you install 1.1.1-dev?  If you configured with `--prefix=/usr`, you probably need to reinstall the official Debian packages for the shared libraries (`libssl1.1` and possibly `libssl.dev`).  Otherwise, go look for `libcrypto.so.1.1` in non-default locations (such as `/usr/local/lib`), rename them and see if that helps.

**Comment by mattcaswell** [comment]
Assuming the openssl binary on your PATH is the one in `/usr/bin/openssl` (use `which openssl` to confirm), what does `ldd /usr/bin/openssl` tell you?

**Comment by tvequaud** [comment]
@mattcaswell : here it is !

```
ldd /usr/bin/openssl
	linux-vdso.so.1 (0x00007fff27dcd000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f6000587000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6000383000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6000166000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5fffdc7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6000cbb000)

```

Seems second line is broken ! Do you know how to update this path, please ?

**Comment by tvequaud** [comment]
I fixed it by running `apt-get install --reinstall libssl-1.1`
Maybe there is a better option ?
Thank you very much @mattcaswell you helped me a lot !

**Comment by mattcaswell** [comment]
So, having fixed libssl-1.1, is `openssl version` now reporting the correct response?

**Comment by tvequaud** [comment]
Yep, only "OpenSSL 1.1.0f  25 May 2017" and now everything works like a charm : I can curl URL in HTTPS !

**Comment by mattcaswell** [comment]
Great. Closing this.
