### ISSUE TITLE
Issue in debug build of openssl version 0.9.8 on Red Hat Linux 5 machine

### ISSUE THREAD

**Issue by hariompatnayak** [openssl/openssl#4825]
I used ./config -d [options], but the release build was made using "-d" as well. "-d" was ignored.
Please help if it is possible to build openssl0.9.8 debug build on the same machine or any other linux machine.

**Comment by richsalz** [comment]
You will need to contact RedHat support groups or developer forums.  The OpenSSL project no longer supports 0.9.8.  You might post to one of the openssl mailing lists, however, just in case someone else has the same issue; see https://mta.openssl.org for details.
