### ISSUE TITLE
Bug in crypto/bio/bss_mem.c starting from openssl 1.1.0f

### ISSUE THREAD

**Issue by hariompatnayak** [openssl/openssl#4827]
static int mem_write(BIO *b, const char *in, int inl)     ----> openssl1.1.0f
{
  ......
  if (BUF_MEM_grow_clean(bbm->buf, blen + inl) == 0)
      goto end;
  ......
}
static int mem_write(BIO *b, const char *in, int inl)    ----> openssl 0.9.8
{
  ......
  if (BUF_MEM_grow_clean(bm,blen+inl) != (blen+inl))
      goto end;
 .......
}
This caused an issue if (blen+inl==0) when initialization vector was of zero length, the function "BUF_MEM_grow_clean" returned 0 in both cases, but "mem_write" eventually returned -1 in openssl 1.1.0f and it returned 0 in openssl 0.9.8

**Comment by richsalz** [comment]
So what are you suggesting we do?

**Comment by hariompatnayak** [comment]
I was just letting the openssl developers know  about it so that it can be fixed in the next version. If I need to report this somewhere else, please let me know.

**Comment by richsalz** [comment]
I mean, what is the fix you would like to see?

**Comment by hariompatnayak** [comment]
I think the check "if (BUF_MEM_grow_clean(bbm->buf, blen + inl) == 0)" in the above mentioned function should be changed back to "if (BUF_MEM_grow_clean(bbm->buf, blen + inl) != (blen+inl))" as it used to be earlier so that the case where  (blen+inl==0) occurs, is handled appropriately.

**Comment by levitte** [comment]
The problem is that `BUF_MEM_grow_clean()` returns 0 on error, so the old check isn't quite right either.
This is essentially the same issue as #4782, which I just submitted a fix for, which I think will apply here as well.

**Comment by levitte** [comment]
I thought github would do that automagically, wonder why it didn't this time.  Ah well...

**Comment by mspncp** [comment]
I noticed that previously: The regex of the automagical commit scanner does not seem to match fixes of multiple issues, which is the case in the commit message of 8dd55d9ee107:

> Fixes #4782 #4827

**Comment by kroeckx** [comment]
You would need to do something like fixes #4782, fixes #4827

**Comment by mspncp** [comment]
You are right, Kurt. For the curious: it is [officially documented here](https://help.github.com/articles/closing-issues-using-keywords/#closing-multiple-issues). Nevertheless, I find `fixes #4782, #4827` more natural. Maybe I'll open an issue on that at github some day.
