### ISSUE TITLE
Test fails on OS X El Capitan

### ISSUE THREAD

**Issue by ChrisCalderon** [openssl/openssl#485]
Configured with `./Configure darwin64-x86_64-cc`
After configuring, running `make` finishes without error. `make test` fails here:
```
../test/recipes/90-test_async.t ........... sh: line 1: 61186 Segmentation fault: 11  ../util/shlib_wrap.sh ./asynctest 2> ./test_async.tmp_err
../test/recipes/90-test_async.t ........... 1/1
#   Failed test 'running asynctest'
#   at ../test/testlib/OppenSSL/Test/Simple.pm line 64.
# Looks like you failed 1 test of 1.
../test/recipes/90-test_async.t ........... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by mattcaswell** [comment]
Can you confirm you have the very latest git master version including this recent commit which provides some OS/X fixes: 6e8ac5087061

**Comment by ChrisCalderon** [comment]
I don't have that commit! I'll pull then try again...

**Comment by ChrisCalderon** [comment]
Ok, with the latest commit `make test` no longer fails.
