### ISSUE TITLE
Engine locking issue

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#4851]
There is a race condition between `engine_unlocked_init` and `engine_unlocked_finish` in `crypto/engine/eng_init.c`.  The problem being that the global lock is given up to call _finish()_ and taken again immediately afterwards.  If while the lock is released, the initialisation function gets called then an inconsistent situation is created.

`engine_unlocked_finish` is only called this way from `ENGINE_finish` further down the file.

Originally found as part of #4821

**Comment by levitte** [comment]
The solution is simple, for 1.1.0 and on; simply remove the unlock and lock around the `finish` call.

For 1.0.2, the situation is more difficult, as some of our engines use the same global lock, and other external ones may as well. At this point, I think we need to leave it as a known issue...

**Comment by levitte** [comment]
Hmmm?  I assumed you were talking about these lines in `engine_unlocked_finish`:

``` C
    if ((e->funct_ref == 0) && e->finish) {
        if (unlock_for_handlers)
            CRYPTO_THREAD_unlock(global_engine_lock);
        to_return = e->finish(e);
        if (unlock_for_handlers)
            CRYPTO_THREAD_write_lock(global_engine_lock);
        if (!to_return)
            return 0;
    }
```

The answer is very simple, for 1.1.0 and on, they should be reduced to:

``` C
    if ((e->funct_ref == 0) && e->finish) {
        to_return = e->finish(e);
        if (!to_return)
            return 0;
    }
```

The input parameter `unlock_for_handlers` can also be safely removed.

Why?  Because the engines don't have access to libcrypto locks, so there's no risk of getting an interlock here.

**Comment by paulidale** [comment]
Okay, I'll remove the unlocking code as part of #4821 but keep it as a separate commit

**Comment by paulidale** [comment]
Using the per engine instead of global lock to guard these bits can be done later.
