### ISSUE TITLE
No glock_free

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#4852]
There is a call `CRYPTO_THREAD_glock_new` but no corresponding `CRYPTO_THREAD_glock_free`.  There is no way to safely clean up a lock allocated this way.

First noticed in #4402 where a global lock is freed using `CRYPTO_THREAD_lock_free` which removes the lock but doesn't adjust the global linked list.

**Comment by kaduk** [comment]
I would rather remove the concept of global locks entirely than try to "fix" it; they don't really add any value since the multi-process+multi-threaded case is basically impossible to use anyway.

**Comment by kaduk** [comment]
Commit 63ab5ea13b671cb60dd4b7cfde2bcae9d14c5a60 reverted the global lock implementation, so closing this as overtaken by events
