### ISSUE TITLE
VS2017 15.5 Blake2b.c Hang with SSA Optimizer Enabled 

### ISSUE THREAD

**Issue by MeerMusik** [openssl/openssl#4859]
When compiling 1.1.0 Stable (latest Head), the Compiler stops and hangs indefinitely after reaching Blake2b.c - right after creating the Blake2b.obj File.

It turned out, the Problem is the SSA Optimizer. After disabling the SSA Optimizer with
```
/d2SSAOptimizer-
```
everything compiles as it should again.

Environment:
* VS2017, x64, 15.5.0
* VS Compiler Tool Set 14.12
* CL Version: 19.12.25830.2
* Link Version: 14.12.25830.2
* SSA Optimizer: Enabled
* VS Native CMD Line
* Windows 10 Fall Creators Update with SDK 16299
* OpenSSL 1.1.0 latest Head
* Perl 3.6.3
* NASM 2.13.02
* Dynamic and Static build
* Adding 'no-blake2' let OpenSSL build fine (with and without the SSA Optimizer)
* No Error with Antergos (Arch) and GCC 7.2.0 (tested just to be sure)

Configure Parameter:
```
set CL=/MP4 /cgthreads4 /nologo && perl Configure no-comp no-rc5 no-idea no-mdc2 no-tls1 no-tls1-method no-tls1_1 no-tls1_1-method no-dtls no-dtls1-method no-dtls1_2 no-dtls1_2-method no-deprecated no-weak-ssl-ciphers VC-WIN64A --prefix=%SystemDrive%\openssl11x64\ --openssldir=%SystemDrive%\openssl11x64\ && nmake >blake2b_error.log
```

The below "Error Log" Files are all I can provide ATM. (Please Ignore the last Line "Compiler terminating.  Please wait..." - this is from canceling the Operation after 2 Minutes with CTRL+C)
[blake2b_error.log](https://github.com/openssl/openssl/files/1537718/blake2b_error.log)

Full Log File with SSA Optimizer Disabled. Maybe it helps. I dont know :)
[blake2b_error_SSAOptimizer_Disabled.log](https://github.com/openssl/openssl/files/1537789/blake2b_error_SSAOptimizer_Disabled.log)

Keeping Folders and Files - if you need other Files just let me know.

BTW: Disabling the SSA Optimizer did not help with the Fuzz Test:
```
...
test\recipes\90-test_fuzz.t ............. 
Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 10/10 subtests 
...
test\recipes\90-test_fuzz.t           (Wstat: 2560 Tests: 10 Failed: 10)
  Failed tests:  1-10
  Non-zero exit status: 10
Files=95, Tests=484, 134 wallclock secs ( 1.56 usr +  0.27 sys =  1.83 CPU)
Result: FAIL
```
Think I need to create another BR!?

Thanks!
Oliver

**Comment by maksqwe** [comment]
It was reported to the VS bugtracker
https://developercommunity.visualstudio.com/content/problem/160717/clexe-vs154-155-regression-compiler-is-stuck-in-in.html

> Karen Huang · 7 hours ago 0
> Thank you for your feedback! We have fixed the problem in an upcoming release. Thank you for helping us build a better Visual Studio!

**Comment by richsalz** [comment]
I am glad you tracked it down.  This is a compiler bug, with known workaround and fixed in the upcoming release.  Nothing for OpenSSL to do here, so I am closing this.
