### ISSUE TITLE
error: invalid symbol redefinition   _bsaes_enc_key_convert

### ISSUE THREAD

**Issue by garyyu** [openssl/openssl#4860]
I build from the source on Mac with git tag: OpenSSL-fips-2_0_16

```
$ ./Configure darwin64-x86_64-cc
$ make
```
then got this error:
```
bsaes-x86_64.s:580:1: error: invalid symbol redefinition
_bsaes_enc_key_convert:
```
then I have to use 'no-asm' option to config and make.

```
$ ./Configure darwin64-x86_64-cc no-asm
$ make 
```
My Mac OS version:
```
$ uname -a
Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
```

**Comment by dot-asm** [comment]
```
$ ./Configure darwin64-x86_64-cc
$ make
```

That's not how OpenSSL-fips-\* tags are supposed to be used. See FIPS User Guide. FIPS module's config is specifically tailored to do the right thing, and is even required to be used. Closing this.
