### ISSUE TITLE
Text-Template-1.46 license in OpenSSL 1_1_0g

### ISSUE THREAD

**Issue by luisapace** [openssl/openssl#4871]
Hi, 
in the https://github.com/openssl/openssl/tree/OpenSSL_1_1_0g/external/perl/Text-Template-1.46
I see two license files: 

1. https://github.com/openssl/openssl/blob/OpenSSL_1_1_0g/external/perl/Text-Template-1.46/COPYING
2. https://github.com/openssl/openssl/blob/OpenSSL_1_1_0g/external/perl/Text-Template-1.46/Artistic

The first is GPL, the second one is Artistic. 

Could you please tell me what is the license of Text-Template-1.46? GPL or Artistic?

Thanks.

**Comment by levitte** [comment]
Over [here](http://search.cpan.org/~mjd/Text-Template-1.46/lib/Text/Template.pm), you can read that either can be used:

> ```
>                                                  ... You may also can
>     redistribute it and/or modify it under the terms of the Perl
>     Artistic License.
> ```

For [version 1.47](http://search.cpan.org/~mschout/Text-Template-1.47/lib/Text/Template.pm), it simply refers to the [Perl license](https://dev.perl.org/licenses/), which basically says the same thing, that you can choose which one you want to use.

**Comment by luisapace** [comment]
@levitte Thanks a lot!
