### ISSUE TITLE
Openssl 1.1.0g - Debian 9 - Compilation with stderr

### ISSUE THREAD

**Issue by dertin** [openssl/openssl#4886]
Hi,

I'm seeing some mistakes that I do not understand. Maybe it's not important, but just in case I share it.
I'm running the test on Travis, the compilation works inside Docker with Debian 9. 64x

Source: https://www.openssl.org/source/openssl-1.1.0g.tar.gz
```
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' no-comp no-zlib no-zlib-dynamic shared

make
make test
sed -i 's# libcrypto.a##;s# libssl.a##;/INSTALL_LIBS/s#libcrypto.a##' Makefile
make MANSUFFIX=ssl install

ldconfig
ldconfig -p | grep libcrypto
```
https://github.com/dertin/lemp-stack-debian/blob/develop/install.sh#L193-L201

The installation does not cancel, but leaves the following alerts:
(stderr only, not stdout)
```
ar: creating libcrypto.a

ar: creating libssl.a

make[1]: *** [_tests] Error 1

make: *** [tests] Error 2

Cannot find "SSL_CTX_set0_ctlog_store" in podpath: cannot find suitable replacement path, cannot resolve link

Cannot find "d2i_SCT_LIST" in podpath: cannot find suitable replacement path, cannot resolve link

Cannot find "d2i_SCT_LIST" in podpath: cannot find suitable replacement path, cannot resolve link

Cannot find "i2d_SCT_LIST" in podpath: cannot find suitable replacement path, cannot resolve link
```
https://travis-ci.org/dertin/lemp-stack-debian/jobs/314049987#L420-L427

**Comment by levitte** [comment]
Those alerts can be ignored.  *However*, please do *not* do this:

```
sed -i 's# libcrypto.a##;s# libssl.a##;/INSTALL_LIBS/s#libcrypto.a##' Makefile
```

You see, the shared libraries are built with the static libraries as input, so by doing that, you're basically cutting the build chain right in the middle.

**Comment by dertin** [comment]
@levitte Thanks for the comment.
