### ISSUE TITLE
Support the name "SHA-1" as an alias of "SHA1"

### ISSUE THREAD

**Issue by Niggler** [openssl/openssl#4895]
Functions like `EVP_get_digestbyname` support hyphenated names, as evidenced in [`ssl/ssl_lib.c`](https://github.com/openssl/openssl/blob/master/ssl/ssl_lib.c#L2835):

```js
    if ((ret->md5 = EVP_get_digestbyname("ssl3-md5")) == NULL) {
        SSLerr(SSL_F_SSL_CTX_NEW, SSL_R_UNABLE_TO_LOAD_SSL3_MD5_ROUTINES);
        goto err2;
    }
    if ((ret->sha1 = EVP_get_digestbyname("ssl3-sha1")) == NULL) {
        SSLerr(SSL_F_SSL_CTX_NEW, SSL_R_UNABLE_TO_LOAD_SSL3_SHA1_ROUTINES);
        goto err2;
    }
```

The official rendering of the Secure Hash Algorithm 1 is "SHA-1" according to [FIPS 180-4](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf) and [RFC 3174](https://tools.ietf.org/html/rfc3174), with a hyphen.  There would seem to be no technical barrier to aliasing the name.  Where supported, would it make sense to alias the digest name "sha-1" to "sha1"?

**Comment by richsalz** [comment]
But those names are used in the TLS specification; it's not clear we need to use them in the user layer in general.

**Comment by bnoordhuis** [comment]
I think what @Niggler is getting at is that `EVP_get_digestbyname("sha1")` works but `EVP_get_digestbyname("sha-1")` does not, even though the latter is the preferred spelling.

**Comment by levitte** [comment]
I see no harm in adding aliases.  After all, it's just a simple edit of `crypto/objects/objects.txt` followed by a `make update`...

Anyone want to take that on?  Is this only for SHA-1, or are there others that could benefit with the same kind of aliasing?  PRs welcome (or a list of desired aliases)!

**Comment by levitte** [comment]
@Vonter gave it a good try in #4900, but it turns out it wasn't as easy as I imagined...  it's been long since I dealt with this part of the source.

**Comment by dot-asm** [comment]
> EVP_get_digestbyname("sha-1") does not [work], even though the latter is the preferred spelling.

I disagree with this assertion. That "latter is **the** preferred spelling." I don't feel that there is consensus on *the* preferred [and universal] spelling. SHA-1 is surely preferred spelling in *written* text as direct reference to algorithm in question, but hardly in application code or elsewhere, for example it's hmac-sha1, sha1WithRSAEncryption, etc. Ironically even referred RFC is entitled "US Secure Hash Algorithm 1 (SHA1)"...

**Comment by t8m** [comment]
SHA-1 is now properly fetchable name. The EVP_get_digestby... is legacy interface. Closing.
