### ISSUE TITLE
SSL_OP_NO_RENEGOTIATION not documented as new in 1.1.1

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#4897]
``SSL_OP_NO_RENEGOTIATION`` was added in PR #3432 but not documented as new feature. The man page for ``SSL_get_options`` only lists ``SSL_OP_PRIORITIZE_CHACHA`` as new option.

**Comment by richsalz** [comment]
Ping @tmshort, you want to make a PR to fix this?

**Comment by tiran** [comment]
Too late :)

**Comment by mspncp** [comment]
Only two changes in all these years? Does not look like a complete history to me. ;-)

```
HISTORY
    The attempt to always try to use secure renegotiation was added in Openssl
    0.9.8m.

    SSL_OP_PRIORITIZE_CHACHA and SSL_OP_NO_RENEGOTIATION were added in OpenSSL
    1.1.1.
```

**Comment by tmshort** [comment]
Options haven't changed much over the years, mostly due to backwards compatibility... I have a big chart of them that I could make into a history, if needed, but it would take a little more research for exact version numbers.

**Comment by richsalz** [comment]
We don't have a formal policy, but we sort of only started listing changes since 1.1.0
