### ISSUE TITLE
./util/pod2mantest missing in 1.0.2e

### ISSUE THREAD

**Issue by df-cryptostorm** [openssl/openssl#490]
during `make install`:

make[1]: Leaving directory `/usr/src/openssl-1.0.2e/tools'
/bin/sh: ./pod2mantest: No such file or directory
installing man1/asn1parse.1
sh: --section=1: command not found
make: *** [install_docs] Error 1

Copying pod2mantest over from 1.0.2d seems to work.

**Comment by quanah** [comment]
Also missing in 1.0.1q

**Comment by glensc** [comment]
file is present in branch: https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/util/pod2mantest

**Comment by glensc** [comment]
upstream tracker: https://rt.openssl.org/Ticket/Display.html?id=4164

**Comment by mattcaswell** [comment]
Closing. This should be fixed in latest tarball.

**Comment by glensc** [comment]
confirming to be fixed with  openssl-1.0.2e.tar.gz       MD5 checksum: 5262bfa25b60ed9de9f28d5d52d77fc5
