### ISSUE TITLE
Platform support for Windows ARM64 with MSVC

### ISSUE THREAD

**Issue by GyrosGeier** [openssl/openssl#4904]
Building with

    vcvarsall.bat amd64_arm64
    Configure VC-WIN64A no-asm
    nmake

Gets fairly far along, and then fails to link:

    crypto\uplink-x86_64.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'

It's obvious that not much is missing for this to work, and this might be useful for the new ARM based Windows netbooks.

**Comment by levitte** [comment]
Actually, much *is* missing...  for the most part, `no-asm` is indeed the solution, but for the uplink stuff, there's a need for a `ms\uplink-arm{something}.pl`, and err, @dot-asm?

**Comment by levitte** [comment]
... and it may be that a whole new config target is needed.

**Comment by dot-asm** [comment]
> there's a need for a ms\uplink-arm{something}.pl

One should keep in mind that uplink is engaged when you start mixing run-times. Or in other words when there is possibility that application and shared library are linked with different run-times. But they, MS, kind of promise that run-time will be same now across versions, so it should be possible to omit uplink if you know that application will be compiled by new enough compiler. And it should always be case with platforms that has no legacy ties, like Windows IoT, or whichever Windows on ARM. In other words, there is no need to bother with it in *this* case.

**Comment by dot-asm** [comment]
Resolved in #5502.
