### ISSUE TITLE
Linking error - unresolved external symbol _EVP_MD_CTX_new

### ISSUE THREAD

**Issue by paulorb** [openssl/openssl#4909]
I am compiling SNMP linking to Openssl 1.0.2k and I am getting these errors:

```
3>netsnmp.lib(keytools.obj) : error LNK2001: unresolved external symbol _EVP_MD_CTX_new
3>netsnmp.lib(scapi.obj) : error LNK2001: unresolved external symbol _EVP_MD_CTX_new
3>netsnmp.lib(keytools.obj) : error LNK2001: unresolved external symbol _EVP_MD_CTX_free
3>netsnmp.lib(scapi.obj) : error LNK2001: unresolved external symbol _EVP_MD_CTX_free
```
I also search on StackOverflow and found that

EVP_MD_CTX_new() in 1.1.0 has replaced EVP_MD_CTX_create() in 1.0.x.

EVP_MD_CTX_free() in 1.1.0 has replaced EVP_MD_CTX_destroy() in 1.0.x.

Since I am using 1.0.2k I might not have this functions anymore. So I disabled it in the net-snmp-config.h

```
/* Define to 1 if you have the `EVP_MD_CTX_create' function. */
#define HAVE_EVP_MD_CTX_CREATE 0

/* Define to 1 if you have the `EVP_MD_CTX_destroy' function. */
#define HAVE_EVP_MD_CTX_DESTROY 0
```
But even doing that I am getting the same errors.
This is the related code inside of SNMP (keytools.c)
```
    /*
     * Setup for the transform type.
     */
#ifdef NETSNMP_USE_OPENSSL
#ifdef HAVE_EVP_MD_CTX_CREATE
    ctx = EVP_MD_CTX_create();
#else
    ctx = malloc(sizeof(*ctx));
    if (!EVP_MD_CTX_init(ctx))
        return SNMPERR_GENERR;
#endif
```

I am compiling my sample project using VS2008 as Multi-threaded DLL (/MD) linking to libsnmp and OpenSSL 1.0.2k both static or dynamic (I tried both and I am getting the same error)

Are these functions (EVP_MD_CTX_new ...)  supposed to be replaced? Or they are still on the new versions of OpenSSL?

**Comment by paulorb** [comment]
For now I am using NETSNMP_USE_INTERNAL_CRYPTO that disables OpenSSL and uses snmp internal cryptography and it is working fine. Anyway I used OpenSSL in Paho without problems so maybe it is an error in SNMP and not in OpenSSL.

**Comment by mattcaswell** [comment]
Yes, this appears to be an SNMP problem not OpenSSL. Closing this for now.
