### ISSUE TITLE
libssl triggers SIGILL on sparc64

### ISSUE THREAD

**Issue by jengelh** [openssl/openssl#4922]
```
libssl1.1:sparc64       1.1.0g-2  (Debian GNU/Linux, sid)
```
During initialization, OpenSSL tries to determine the hardware capabilites and directly issues certain instructions. These cause SIGILL to be thrown (which openssl per se handles, but it still ptracers by default which does not seem too nice). Is there no other way that does not involve relying on signals, like using `getauxval(AT_HWCAP)` on Linux instead?
```
Program received signal SIGILL, Illegal instruction.
0xffff80010166a124 in _sparcv9_fmadd_probe () at ../crypto/sparccpuid.S:330
330     ../crypto/sparccpuid.S: No such file or directory.
(gdb) disas
Dump of assembler code for function _sparcv9_fmadd_probe:
   0xffff80010166a118 <+0>:     impdep1  108, %g0, %g0, %g0
   0xffff80010166a11c <+4>:     impdep1  108, %g2, %g2, %g2
   0xffff80010166a120 <+8>:     retl 
=> 0xffff80010166a124 <+12>:    impdep2  34, %g0, %g0, %g0
End of assembler dump.
(gdb) c
Continuing.

Program received signal SIGILL, Illegal instruction.
0xffff80010166a134 in _sparcv9_vis3_probe () at ../crypto/sparccpuid.S:346
346     in ../crypto/sparccpuid.S
(gdb) c
Continuing.

Program received signal SIGILL, Illegal instruction.
0xffff80010166a140 in _sparcv9_fjaesx_probe () at ../crypto/sparccpuid.S:354
354     in ../crypto/sparccpuid.S
(gdb) 
Continuing.
<runs ok afterwards>
```

**Comment by dot-asm** [comment]
See https://www.openssl.org/docs/faq.html#PROG15 for workarounds if you find it counterproductive. As for getauxval(AT_HWCAP), is it expressive enough already? I mean it was really limited last time I checked. In sense that it didn't answer all the questions. And this also means that there is a "timing" factor. I mean if you happen to run on system that provides the interface, but not all relevant values, you'll be missing capabilities. BTW, I don't find no getauxval on Debian 7.8. [Just in case, no, I have no control over machine in question and can't follow various update-this-n-that...

**Comment by dot-asm** [comment]
In the essence, what I'm trying to say is that it's not really a coincidence that getauxval(AT_HWCAP) is *not* used on SPARC. So I'm closing this, but if more concrete suggestion is presented, i.e. not in form of general why-not question, but more detailed this-is-what-one-can-do, then it will be considered.
