### ISSUE TITLE
Error while linking to libcrypto.a static library in macOS

### ISSUE THREAD

**Issue by ssrlive** [openssl/openssl#4923]
In my project [SSR-native](https://github.com/ShadowsocksR-Live/shadowsocksr-native), I try to linking to static OpenSSL in macOS. But it occur error. 
It's only on macOS with static linking.  
And it's NOT in Linux/Windows or dynamic linking. 
Please review it.

```
[ 91%] Linking C executable ssr-client
Undefined symbols for architecture x86_64:
  "_EVP_CIPHER_CTX_reset", referenced from:
      _cipher_context_init in encrypt.c.o
      _cipher_context_set_iv in encrypt.c.o
  "_OPENSSL_init_crypto", referenced from:
      _enc_key_init in encrypt.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by t-j-h** [comment]
Which version of OpenSSL are you using?
Did you build it yourself? Is it the system provided one?
Basically there is insufficient information to provide any meaningful feedback.

**Comment by ssrlive** [comment]
I using the git master branch. 
and 
```
./config
make
sudo make install
```

**Comment by gpongelli** [comment]
Have you tried with [wiki commands](https://wiki.openssl.org/index.php/Compilation_and_Installation#OS_X) ?

**Comment by mattcaswell** [comment]
Please ask this type of question on the openssl-users email list:

https://mta.openssl.org

**Comment by AbandonedCart** [comment]
@ssrlive Per the notice when installing openssl from Homebrew, you have to add it to your PATH before any other openssl references (ie. export PATH=/usr/local/opt/openssl@1.1/bin:$PATH)
