### ISSUE TITLE
TLSv1.3: SSL_export_keying_material should work after Sever Finished

### ISSUE THREAD

**Issue by tatsuhiro-t** [openssl/openssl#4925]
At the moment, it looks like SSL_export_keying_material is not available before handshake finishes.
According to https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#rfc.section.7.1 exporter_master_secret depends on ClientHello...server Finished, so it does not need to wait for handshake to complete.

**Comment by mattcaswell** [comment]
This was fixed by commit 2221ec10. Closing.
