### ISSUE TITLE
blake2s.c takes ~15 min to compile with VS2017

### ISSUE THREAD

**Issue by andyli** [openssl/openssl#4936]
We are using AppVeyor to compile openssl 1.1.0g. We notice that the crypto\blake2\blake2s.c file takes about 15 minutes to compile with Visual Studio 2017.

A build log can be found at https://ci.appveyor.com/project/HaxeFoundation/neko/build/306/job/rqbai6657l86typ7#L1811
Hover line 1811 and 1812 and you can see the times from the start of build are 04:37 and 19:18, respectively. It means line 1811 took 19:18 - 04:37 = 14 minutes 41 seconds to complete.

It is most likely a VS 2017 issue since with VS 2013, the same file took only 1 second to compile:
https://ci.appveyor.com/project/HaxeFoundation/neko/build/306/job/a0067v1cd8kvam0i

It would be great to find out the cause and workaround it and report it to Microsoft.

**Comment by dot-asm** [comment]
This is presumably effectively duplicate of #4859. In other words it's not problem with VS2017, but specific version, and it's confirmed compiler bug. At least I can *not* confirm that it's problem to compile blake2 with VS2017 15.4 (I haven't upgraded).

**Comment by dot-asm** [comment]
> it's not problem with VS2017

I meant not a problem with VS2017 *in general*, [but with specific version].

**Comment by andyli** [comment]
I see. Thanks for the quick reply!
