### ISSUE TITLE
SSL Handshaking Errors

### ISSUE THREAD

**Issue by josh-mclean** [openssl/openssl#4938]
In our production enviornment we are seeing the following errors:

56937033 SSL_do_handshake() 
failed (SSL: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption 
failed or bad record mac) while SSL handshaking, client: 

We had this issue on Ubuntu 14.04LTS and openssl 1.0.1f.
We upgraded to openssl 1.1.0f and Ubuntu 16.04LTS
We are using this with Nginx 1.13.4
Let me know what more information you need and what would be the best steps to try and resolve this error.

Josh

**Comment by dot-asm** [comment]
The key question is how to reproduce the problem and reproduce *reliably*. Most notably can you reproduce it with openssl s_client? On same system? From another one? If so, which cipher?

**Comment by josh-mclean** [comment]
We are now at the point where we can reproduce reliably after approximately 6 minutes of requests on a test machine.  We don't use openss s_client.  We run our testing software in a loop against our NGINX node.

We are able to eliminate the errors by disabling SSL Caching in Nginx.  The setting in the nginx.conf that produces errors is:
ssl_session_cache shared:SSL:50m;
To get the errors to STOP we have to set it to:
ssl_session_cache off;

According to the tcpdump .pcap file when we produce a 504 Gateway Timeout Error the cipher was:
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)

We can produce this error from different machines that get updated, or stay at their currently patched status.

We disabled the ssl_session_cache because we noted that all the packets were flagged in the network trace with:
Expert Info (Note/Sequence):  This session reuses previously negotiated keys (Session resumption)

It seems that there is some type of issue with SSL Session Resumption on nginx with OpenSSL.

Let me know what more information you would be interested in knowing.  This happens on a small percentage of requests but more of our customers have noticed this issue.

**Comment by dot-asm** [comment]
It looks very much like TLS session data gets corrupted (or pointer gets replaced). Now thing is that session handling is actually application's responsibility. This means that it's *more likely* to be nginx fault. So that you'd better off brining this up with nginx. This still doesn't preclude possibility that there is bug in OpenSSL, but it's probably not right place to *start* unraveling the problem.

**Comment by dot-asm** [comment]
Just in case for reference.The original query about cross-system test and specific cipher was effectively dictated by assumption that it might be problem with specific cipher on specific processor. Failures to resume session are not specific to any cipher or processor, so query was irrelevant to this particular problem.

**Comment by mattcaswell** [comment]
Is this now resolved?

**Comment by josh-mclean** [comment]
Yes.

**Comment by mattcaswell** [comment]
Great! Closing.

**Comment by hcconquer** [comment]
> Great! Closing.

hi, can give the fix commit, I search 'bad record' and '#4938', but found nothing.
