### ISSUE TITLE
How to enable TLS_FALLBACK_SCSV support on OpenSSL v1.0.2g ?

### ISSUE THREAD

**Issue by baijianpeng** [openssl/openssl#4945]
I am running OpenSSL v1.0.2g on my Ubuntu Server 16.04.3 . When I evaluate my SSL security with "https://www.ssllabs.com/ssltest" , I noticed this line on the final report:

> 

Downgrade attack prevention | Unknown (requires support for at least two protocols, excl. SSL2)
-- | --

It was said that I should enable TLS_FALLBACK_SCSV to sove this issue.

How can I enable TLS_FALLBACK_SCSV on my OpenSSL?

Thank you.

**Comment by mattcaswell** [comment]
Sending TLS_FALLBACK_SCSV is a *client* side option. Detecting it on the server side is done automatically - you don't need to do anything.
