### ISSUE TITLE
TLSv1.3 cipher alias

### ISSUE THREAD

**Issue by moyaldror** [openssl/openssl#4953]
TLSv1.3 ciphers are missing from `cipher_aliases`, can it be added?

**Comment by kaduk** [comment]
There is some additional discussion at at least https://github.com/openssl/openssl/issues/2276 (and maybe other places).  So, I think some additional justification of need other than "they are missing" would be required before any action would be taken.

**Comment by moyaldror** [comment]
The only good justification I see is keeping up with old aliasing - I see no reason why there should be aliases for SSLv3, TLSv1/1.2 but not for TLSv1.3

**Comment by kaduk** [comment]
"TLS 1.3 exceptionalism" already holds sway in that there are not dedicated TLS 1.3 method object/functions; this case seems "similar enough" to me that I expect TLS 1.3 exceptionalism to hold sway.

**Comment by mattcaswell** [comment]
This is a dupe of #2276. There is more discussion in that issue, so closing this one in favour of it.
