### ISSUE TITLE
Issue building 1.0.2n on Windows

### ISSUE THREAD

**Issue by Framnk** [openssl/openssl#4957]
There seems to be some kind of Makefile issue when I attempt to build 1.0.2n on Windows.  I downloaded the release .zip and extracted to a folder and using a VC++ command-prompt I ran:

"perl configure VC-WIN32"

All seems to go well running the perl command.  Then I run:

"nmake"

and immediately I get:

makefile(243) : fatal error U1001: syntax error : illegal character '{' in macro

**Comment by levitte** [comment]
Please read `INSTALL.W32`, there's a bit more to it than just running Configure before you can run nmake
