### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by cyberhawk777** [openssl/openssl#496]
I work in an environment that includes some RHEL 5.11 servers, which are currently too important to be brought down for an upgrade and are running openssl 0.9.8e.  A system we use for monitoring is running RHEL 6.5 with openssl 1.0.1e.  The difference in openssl versions is resulting in several errors which we'd like to fix, preferably without upgrading at this time.  Is there any way to get openssl 0.9.8e to communicate with 1.0.1e?

**Comment by mattcaswell** [comment]
0.9.8 and 1.0.1 should be able to talk to each other fine (dependant on run-time and compile time configuration). What errors are you seeing?

**Comment by cyberhawk777** [comment]
I'll have to go through some log files to find the exact text and then I'll post it here.

**Comment by cyberhawk777** [comment]
My boss and I are still checking for the error messages, but the primary issue seems to be the monitoring server is giving a false LDAP error saying the client is untrusted, due to the different openssl versions.  If you want, I can paste that error in, but it's not likely to be of much help, since the error itself is more related to LDAP.

**Comment by mattcaswell** [comment]
Does it actually say its due to the different openssl versions? Please post the error, to see if it gives any kind of clue. Another option for progressing this is if you are able to get and provide a wireshark packet capture of the SSL/TLS handshake.

**Comment by cyberhawk777** [comment]
check_syncrepl.py - ERROR - LDAP bind failed. {'info': "TLS error -8172:Peer's certificate issuer has been marked as not trusted by the user.", 'desc': "Can't contact LDAP server"}

and

FAILED : LDAP bind failed. {'info': "TLS error -8172:Peer's certificate issuer has been marked as not trusted by the user.", 'desc': "Can't contact LDAP server"}

are the errors we've been getting.  Other clients can contact the LDAP servers normally, leading us to believe it is an openssl issue.  I'm not sure if my boss has more reason than that, but this is at least the logic I've been using.

**Comment by mattcaswell** [comment]
This doesn't look to me like a 0.9.8<->1.0.1 interop thing at all. Rather the certificate that the server is presenting is failing to verify on the client side. The error message indicates that the certificate issuer has not been marked as trusted. There are a couple of reasons I can think of for that:

1) The server has been mis-configured and is not providing the full certificate chain - normally the server will supply all certificates in the chain including its own certificate as well as any intermediary CA certificates, but excluding the root CA certificate itself. Sometimes servers are misconfigured to only provide some of those certificates, in which case the client will fail.

2) If these servers have been running for some while without any issues then probably a more likely problem is that the client does not have (or has not been configured to use) the root CA certificate in its trust store.

This is an application configuration issue (not directly an openssl issue). I'm not familiar with LDAP configuration, but some googling turned up this answer on stack exchange which appears relevant:
https://serverfault.com/questions/437546/centos-openldap-cert-trust-issues

**Comment by cyberhawk777** [comment]
Although I may try to work through the troubleshooting steps again, like I said, the LDAP clients seem to be able to communicate with the servers fine.  Only the monitoring server has trouble.  That's what has us puzzled.

**Comment by mattcaswell** [comment]
Right - but if I understand correctly, the monitoring server is acting as a client when talking to your LDAP servers? If the monitoring server does not have its trust store set up correctly then that will give you exactly the behaviour you are experiencing, i.e. all other clients (which do have correct trust stores) work correctly - but the one that doesn't will fail.

**Comment by cyberhawk777** [comment]
Correct.  It's acting as a client.  And that is a good point about the trust store.  I may have to look into that.  It still seems to be the version difference, but I try to keep an open mind when troubleshooting and not eliminate any possibilities.

Thanks for the help.  I guess I'll just go ahead and close the thread.
