### ISSUE TITLE
Compile issue 1.0.2n crypto o_init.c Win32 VisualStudio2013

### ISSUE THREAD

**Issue by RobLockhart** [openssl/openssl#4967]
I use scripts to build OpenSSL, and up to this point, they've all worked flawlessly, up to and including 1.0.2m. However, with 1.0.2n, I am no longer able to complete the compile. It appears that a previous warning has been changed to an error.

Prerequisites:
* Windows 10 x64 with all updates
* Netwide Assembler, version 2.12.01
* ActivePerl 5.22.1 build 2201
* Microsoft Visual Studio Professional 2013
* Cygwin-64 terminal (just base install, DEC 2017)
* OpenSSL FIPS canister 2.0.16 tarball
* OpenSSL binary tarballs (1.0.2m and 1.0.2n)

The error message is below. I will include a verbose log if possible (via pastebin-like URL)

1.0.2n error:

cl /Fotmp32dll\o_init.obj  -Iinc32 -Itmp32dll /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -WX -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -D_WINSOCK_DEPRECATE
D_NO_WARNINGS -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -I\usr\local\ssl\fips-2.0/include -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DW
HIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_FIPS -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_STATIC_ENGINE /Zi /Fdtmp32dll/lib -D_
WINDLL  -DOPENSSL_BUILD_SHLIBCRYPTO -c .\crypto\o_init.c
o_init.c
.\crypto\o_init.c(77) : error C2220: warning treated as error - no 'object' file generated
.\crypto\o_init.c(77) : warning C4013: 'FIPS_crypto_set_id_callback' undefined; assuming extern returning int
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.

1.0.2m "warning":

cl /Fotmp32dll\o_init.obj  -Iinc32 -Itmp32dll /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WO
RDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -I\usr\local\ssl\fips-2.0/include -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_USE
_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_FIPS -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_STATIC_ENGINE /Zi /Fdtmp32dll/lib -D_WINDLL  -DOPENSSL_BUILD_SHLIBCRYPTO -c
 .\crypto\o_init.c
o_init.c
.\crypto\o_init.c(77) : warning C4013: 'FIPS_crypto_set_id_callback' undefined; assuming extern returning int

**CG** = Cygwin console
*VS** = Visual Studio 2013 x86 (32-bit) console
Source files are in their own directory on another drive (I:)
All compilations are done using user in Administrator group on C: root folders

WORKING 1.0.2m compilation:  https://pastebin.ca/3950604
BROKEN 1.0.2n compilation:  https://pastebin.ca/3950607

**Comment by RobLockhart** [comment]
Looks like the top-level "Configure" file changed for 1.0.2n. Reverting back to the Configure from 1.0.2m allowed the compile to succeed, as well as the test steps "passed all tests" after "nmake -f ms\ntdll.mak test".

The differences in the Configure files are (line 595, non-debug version) are highlighted below. Can someone please comment as to the impact on security and stability by using the 1.0.2m Configure file?

1.0.2m:
# 'perl Configure VC-WIN32' with '-DUNICODE -D_UNICODE'
"VC-WIN32","cl:-W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN **-D_CRT_SECURE_NO_DEPRECATE:::WIN32:**:BN_LLONG RC4_INDEX EXPORT_VAR_AS_FN ${x86_gcc_opts}:${x86_asm}:win32n:win32",

1.0.2n:# 'perl Configure VC-WIN32' with '-DUNICODE -D_UNICODE'
"VC-WIN32","cl:-W3 **-WX** -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN **-D_CRT_SECURE_NO_DEPRECATE** **-D_WINSOCK_DEPRECATED_NO_WARNINGS:::WIN32::BN_LLONG** RC4_INDEX EXPORT_VAR_AS_FN ${x86_gcc_opts}:${x86_asm}:win32n:win32",

**Comment by mspncp** [comment]
This has been fixed, details see https://github.com/openssl/openssl/pull/4884#issuecomment-350858287 and #4870.

**Comment by RobLockhart** [comment]
Thank you! I concur that this patch "Add missing prototype for FIPS callback" does fix the build issue:
https://github.com/mspncp/openssl/commit/015e9c6235f264674cf035d8eb8a18acc38284f9

**Comment by mspncp** [comment]
Commit https://github.com/mspncp/openssl/commit/015e9c6235f264674cf035d8eb8a18acc38284f9 is the original patch from my pull request. Meanwhile, the fix has been merged to the  [OpenSSL_1_0_2-stable](https://github.com/openssl/openssl/commits/OpenSSL_1_0_2-stable) branch as 18df0adda98f8f21cc494b4835c2817bcadbeb8a, where it will be part of the next official release.
