### ISSUE TITLE
 OPENSSL_init_ssl

### ISSUE THREAD

**Issue by whzh01** [openssl/openssl#4973]
When I load the openssl.so in the php.ini file, it has a problem as following,
php: symbol lookup error: /usr/local/php7/lib/php/extensions/no-debug-non-zts-20170718/openssl.so: undefined symbol: OPENSSL_init_ssl

**Comment by kaduk** [comment]
I think you would be more likely to get results by seeking help in a PHP-specific forum -- we don't really have enough information here to be of much help.

**Comment by mattcaswell** [comment]
Yes - please check with php first. Closing this.
