### ISSUE TITLE
Disable NewSessionTicket message in TLSv1.3

### ISSUE THREAD

**Issue by moyaldror** [openssl/openssl#4978]
According to the [draft](https://tools.ietf.org/html/draft-ietf-tls-tls13-22#section-4.6.1):

> 4.6.1.  New Session Ticket Message
>
>  At any time after the server has received the client Finished
>  message, it **MAY** send a NewSessionTicket message. 

In previous versions, I could use `SSL_OP_NO_TICKET` to disable session tickets but I can't find such option for TLSv1.3.

Is it supported and I just failed to find it? 
If not, will it be supported or I should add my own code?

**Comment by mattcaswell** [comment]
It isn't currently supported. There is a TODO around this in the code in ssl/statem/statem_srvr.c:
````
    case TLS_ST_SR_FINISHED:
        /*
         * Technically we have finished the handshake at this point, but we're
         * going to remain "in_init" for now and write out the session ticket
         * immediately.
         * TODO(TLS1.3): Perhaps we need to be able to control this behaviour
         * and give the application the opportunity to delay sending the
         * session ticket?
         */
        st->hand_state = TLS_ST_SW_SESSION_TICKET;
        return WRITE_TRAN_CONTINUE;
````
PRs to address this are welcome

**Comment by moyaldror** [comment]
I have seen this TODO, but it says only delay and not to totally disable so I guessed wrong that it's not relevant to me.

Should I create the PR?

**Comment by mattcaswell** [comment]
> Should I create the PR?

If you feel able, please go ahead. You will need to have a CLA on file before it could be accepted (but that doesn't stop you from creating it first).

**Comment by moyaldror** [comment]
Sure, I will happily do it.

Should I only add the ability to disable the NewSessionTicket or as the TODO implicates I should add the ability to delay? If so who should I get requirements from?
