### ISSUE TITLE
Using of deprecated api evp_dss1() in openssl 1.1.0g

### ISSUE THREAD

**Issue by sankalp135** [openssl/openssl#4985]
EVP_dss1() function was deprecated in Openssl 1.1.X release but it is present in 1.0.X release. 

We want to include deprecated "EVP_dss1()" function in OpenSSL 1.1.x. Could you please provide procedure to include deprecated functons in Openssl 1.1.X?

We found below on wiki . 
Access to deprecated functions/macros has been removed by default. To enable access you must do two things.
 1) Build OpenSSL with deprecation support (pass "enable-deprecated" as an argument to config)
 2) Applications must define "OPENSSL_USE_DEPRECATED" before including OpenSSL header files

For the 1) we have added it in Config options. However how to use OPENSSL_USE_DEPRECATED is not available in any forum. Could you please share sample code snippet to use OPENSSL_USE_DEPRECATED

**Comment by kaduk** [comment]
Just ```#define OPENSSL_USE_DEPRECATED 1``` before ```#include <openssl/evp.h>``` gets evaluated (which probably translates to before any OpenSSL headers gets included, for simplicity).
