### ISSUE TITLE
1.0.2n build issues with VS2015

### ISSUE THREAD

**Issue by chcg** [openssl/openssl#4987]
Starting with 1.0.2n the following warnings appear for the x64 build:

```

  
  	cl /Fotmp32\cryptlib.obj  -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -WX -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -D_WINSOCK_DEPRECATED_NO_WARNINGS -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE /Zl /Zi /Fdtmp32/lib -c .\crypto\cryptlib.c
  
  cryptlib.c
  
c:\program files (x86)\microsoft sdks\windows\v7.1a\include\sal_supp.h(57): error C2220: warning treated as error - no 'object' file generated [C:\projects\nppftp\_build\NppFTP3rdPartyPrerequists.vcxproj]
  
c:\program files (x86)\microsoft sdks\windows\v7.1a\include\sal_supp.h(57): warning C4005: '__useHeader': macro redefinition [C:\projects\nppftp\_build\NppFTP3rdPartyPrerequists.vcxproj]
  
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sal.h(2866): note: see previous definition of '__useHeader'
  
c:\program files (x86)\microsoft sdks\windows\v7.1a\include\specstrings_supp.h(77): warning C4005: '__on_failure': macro redefinition [C:\projects\nppftp\_build\NppFTP3rdPartyPrerequists.vcxproj]
  
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sal.h(2876): note: see previous definition of '__on_failure'
  
.\crypto\cryptlib.c(447): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long' [C:\projects\nppftp\_build\NppFTP3rdPartyPrerequists.vcxproj]
  
.\crypto\cryptlib.c(911): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\nppftp\_build\NppFTP3rdPartyPrerequists.vcxproj]
  
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\cl.EXE"' : return code '0x2' [C:\projects\nppftp\_build\NppFTP3rdPartyPrerequists.vcxproj]
  
  Stop.
  
  
```

leading to broken builds of N++ nppFTP plugin, because they are treated as errors.

See e.g. https://ci.appveyor.com/project/ashkulz/nppftp/build/0.27.3.40/job/mbrkkcis9xp38u2j

**Comment by richsalz** [comment]
1.0.2 does not compile without warnings and will not build if you set "warnings as errors."

**Comment by chcg** [comment]
@richsalz But it is the default since https://github.com/openssl/openssl/commit/b2921cf7f2468ecf9932527070cd30b3f5cbb467

>  Configure: add back /WX to VC-WIN32.
> 
> We had /WX (treat warnings as errors) in VC-WIN32 for long time. At
> some point it was somehow omitted. It's argued that it allows to
> keep better focus on new code, which motivates the comeback...
> 
> Reviewed-by: Rich Salz <rsalz@openssl.org>
> (Merged from #4718)

Could it be configured out?

**Comment by dot-asm** [comment]
> [/WX] is default since b2921cf

... in VC-WIN32[!] build, i.e. 32-bit one. While you're referring to x64, i.e. 64-bit build. It doesn't add up. Secondly, note that it's complaining about SDK, i.e. vendor-supplied, headers. This is not something we can do about, but you can work around this particular problem by adding -wd4005 flag to configure command line to suppress offending C4005 warning.

**Comment by chcg** [comment]
@dot-asm Thanks for the hint. The x64 build is currently slightly misconfigured, because it use x64 config for compiler settings (C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat)/cmake, but for openssl perl VC-WIN32 instead of VC-WIN64A.

Also the win32 build fails, see https://ci.appveyor.com/project/ashkulz/nppftp/build/0.27.3.40/job/4t9mq6ir9dpfu8at , but just with the macro redefinitions.

I'm wondering why this differs from openssl appveyor build https://ci.appveyor.com/project/openssl/openssl/build/OpenSSL_1_0_2-stable.14648/job/8s01p7u0sqkvrxaa, also the compiler call is identical.

Differences as far as I can see are the parameters:
--openssldir=C:\projects\nppftp\_build\x86\3rdparty no-shared
and maybe the used appveyor image, which is not visible in the openssl appveyor.yml.

**Comment by levitte** [comment]
I'm noticing [these lines in `build_3rdparty.py`](https://github.com/ashkulz/NppFTP/blob/master/build_3rdparty.py#L195-L196), but I can't see [`CMakeLists.txt`](https://github.com/ashkulz/NppFTP/blob/master/CMakeLists.txt#L45-L51) setting the prefix to "msvc_x64" anywhere, so the target in `build_3rdparty.py` ends up being "msvc" at all times, i.e. generate a 32-bit OpenSSL build, whether that's appropriate or not.

**Comment by dot-asm** [comment]
> Also the win32 build fails, see https://ci.appveyor.com/project/ashkulz/nppftp/build/0.27.3.40/job/4t9mq6ir9dpfu8at , but just with the macro redefinitions.

And you should be able to remedy it with additional -wd4005 flag.

> I'm wondering why this differs from openssl appveyor build

I don't know... We're using VSVER: 14 to pick "image", but it doesn't seem to be documented, so ... Shrug... In either case, it's *external* problem, so just use additional flag...
