### ISSUE TITLE
Crash happened in fuction  "ERR_clear_error" of openssl 1.1.0c

### ISSUE THREAD

**Issue by forston** [openssl/openssl#4988]
hi 

i meet a problem in current project recently.

A crash  happened in fuction  "ERR_clear_error" of openssl 1.1.0c, interrupter event is SIGSEGV.

i check code of this version.
void ERR_clear_error(void)
{
int i;
ERR_STATE *es;
es = ERR_get_state();
for (i = 0; i < ERR_NUM_ERRORS; i++) 
{ err_clear(es, i); } 
es->top = es->bottom = 0;
}

it seems that es may be a null point.

in fuction ERR_get_state, it can return null

Please help to check when ERR_get_state will return null.

best regards

**Comment by mattcaswell** [comment]
This was fixed already in 819d18f61. The fix is available in 1.1.0g.
