### ISSUE TITLE
tls_early_post_process_client_hello:version too low

### ISSUE THREAD

**Issue by cjhust** [openssl/openssl#4989]
2017/12/28 15:16:22 [crit] 136870#136870: *10109750 SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking, client: 221.204.238.54, server: 0.0.0.0:443
2017/12/28 15:16:25 [crit] 136853#136853: *10111540 SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking, client: 60.211.204.215, server: 0.0.0.0:443

env:
nginx+tls1.3-draft18 branch

**Comment by mattcaswell** [comment]
What was the client? Most likely the client was using a version of TLS that was not allowed by the server, e.g. attempting to negotiate SSLv3 which is disabled on the server. This is OpenSSL operating normally.

**Comment by cjhust** [comment]
this is our online server, so can't find the client version because handshake is not finished.

but another server running with nginx+openssl-1.0.2 in the same cluster have not such error logs.

**Comment by levitte** [comment]
SSLv3 is disabled by default in OpenSSL 1.1.0 and on, but not in 1.0.2.  That's the likely difference.

**Comment by cjhust** [comment]
yes, you are right.
#openssl s_client -connect 127.0.0.1:443  -ssl3
server will have such error logs.

**Comment by cjhust** [comment]
thanks

**Comment by jetma** [comment]
> SSLv3 is disabled by default in OpenSSL 1.1.0 and on, but not in 1.0.2. That's the likely difference.

How can I enable SSLv3 in OpenSSL 1.1.0?

**Comment by mattcaswell** [comment]
> How can I enable SSLv3 in OpenSSL 1.1.0?

You really don't want to do that. SSLv3 is insecure and no longer widely used. If there are clients out there still using it then the correct response is to fail. Those clients need to upgrade to something secure.

If you absolutely *must* have SSLv3 then you need to recompile OpenSSL with SSLv3 support added in. That is done at the "Configure" stage of the build process, e.g.:

````
$ ./config enable-ssl3
$ make
$ make test
$ make install
````
