### ISSUE TITLE
Homeblockcoin app crashed

### ISSUE THREAD

**Issue by pepinocosmico** [openssl/openssl#4991]
Hello. I used homeblockoin app to Store my coins and it is not working so i cant use my coins. When i open app a message says: assertion failed

**Comment by levitte** [comment]
You should talk with Homeblockcoin, then

**Comment by pepinocosmico** [comment]
I cant contact to them. They dont have support...

Enviado desde mi iPhone

**Comment by levitte** [comment]
... and we don't have support on their stuff.  Sorry, we cannot help you.
