### ISSUE TITLE
How to setup in Visual Studio 2013 

### ISSUE THREAD

**Issue by atsuyim** [openssl/openssl#500]
Is there any official tutorial from openssl community where i can learn how to set it up and running in windows 8, VS2013.

I found some of the tutorial (which are listed at the button of this treat) but it didn't work for me. So any help would do just great.
And lastly do i need to install Perl?
Thank you

{
        http://p-nand-q.com/programming/windows/building_openssl_with_visual_studio_2013.html
        http://developer.covenanteyes.com/building-openssl-for-visual-studio/
}

**Comment by gvanem** [comment]
You have written a question in a **Problem Report** section! This is not a discussion-forum. Redirect your questions to one of the OpenSSL developer mailing-lists; openssl-dev@openssl.org etc.

And BTW, no OpenSSL core-developer seems to take notice of this PR section anyway.

**Comment by mattcaswell** [comment]
Not true! We do take notice. The correct mailing list to raise this on is openssl-users@openssl.org. The dev list is for development of openssl itself.

(Yes you do need perl)

**Comment by gvanem** [comment]
> Not true! We do take notice.

Okay, my bad impression then. But there are so many unlabelled PRs here.

**Comment by richsalz** [comment]
Too much stuff, not enough time.
