### ISSUE TITLE
Errors in Source/Or Something.

### ISSUE THREAD

**Issue by odin-loki** [openssl/openssl#5004]
Errors affect using GCC with SYS2 on Windows 10 64 bit. Latest Windows. OpenSSL was 1.0.2.

make[2]: Entering directory '/home/Odin/openssl-1.0.2n/crypto/bn'
gcc -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include  -D_WINDLL -DOPENSSL_PIC -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -O3 -Wall -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -c -o x86_64-gcc.o asm/x86_64-gcc.c
asm/x86_64-gcc.c:61:0: warning: "BN_ULONG" redefined
 #  define BN_ULONG unsigned long

In file included from asm/../bn_lcl.h:115:0,
                 from asm/x86_64-gcc.c:1:
../../include/openssl/bn.h:212:0: note: this is the location of the previous definition
 #  define BN_ULONG        unsigned long long

asm/x86_64-gcc.c:108:10: **error**: conflicting types for 'bn_mul_add_words'
 BN_ULONG bn_mul_add_words(BN_ULONG *rp, const BN_ULONG *ap, int num,
          ^~~~~~~~~~~~~~~~
In file included from asm/../bn_lcl.h:115:0,
                 from asm/x86_64-gcc.c:1:
../../include/openssl/bn.h:850:10: note: previous declaration of 'bn_mul_add_words' was here
 BN_ULONG bn_mul_add_words(BN_ULONG *rp, const BN_ULONG *ap, int num,
          ^~~~~~~~~~~~~~~~
asm/x86_64-gcc.c:139:10: **error**: conflicting types for 'bn_mul_words'
 BN_ULONG bn_mul_words(BN_ULONG *rp, const BN_ULONG *ap, int num, BN_ULONG w)
          ^~~~~~~~~~~~
In file included from asm/../bn_lcl.h:115:0,
                 from asm/x86_64-gcc.c:1:
../../include/openssl/bn.h:852:10: note: previous declaration of 'bn_mul_words' was here
 BN_ULONG bn_mul_words(BN_ULONG *rp, const BN_ULONG *ap, int num, BN_ULONG w);
          ^~~~~~~~~~~~
asm/x86_64-gcc.c:167:6: **error**: conflicting types for 'bn_sqr_words'
 void bn_sqr_words(BN_ULONG *r, const BN_ULONG *a, int n)
      ^~~~~~~~~~~~
In file included from asm/../bn_lcl.h:115:0,
                 from asm/x86_64-gcc.c:1:
../../include/openssl/bn.h:853:6: note: previous declaration of 'bn_sqr_words' was here
 void bn_sqr_words(BN_ULONG *rp, const BN_ULONG *ap, int num);
      ^~~~~~~~~~~~
asm/x86_64-gcc.c:192:10: **error**: conflicting types for 'bn_div_words'
 BN_ULONG bn_div_words(BN_ULONG h, BN_ULONG l, BN_ULONG d)
          ^~~~~~~~~~~~
In file included from asm/../bn_lcl.h:115:0,
                 from asm/x86_64-gcc.c:1:
../../include/openssl/bn.h:854:10: note: previous declaration of 'bn_div_words' was here
 BN_ULONG bn_div_words(BN_ULONG h, BN_ULONG l, BN_ULONG d);
          ^~~~~~~~~~~~
asm/x86_64-gcc.c:203:10: **error**: conflicting types for 'bn_add_words'
 BN_ULONG bn_add_words(BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp,
          ^~~~~~~~~~~~
In file included from asm/../bn_lcl.h:115:0,
                 from asm/x86_64-gcc.c:1:
../../include/openssl/bn.h:855:10: note: previous declaration of 'bn_add_words' was here
 BN_ULONG bn_add_words(BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp,
          ^~~~~~~~~~~~
asm/x86_64-gcc.c:229:10: **error**: conflicting types for 'bn_sub_words'
 BN_ULONG bn_sub_words(BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp,
          ^~~~~~~~~~~~
In file included from asm/../bn_lcl.h:115:0,
                 from asm/x86_64-gcc.c:1:
../../include/openssl/bn.h:857:10: note: previous declaration of 'bn_sub_words' was here
 BN_ULONG bn_sub_words(BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp,
          ^~~~~~~~~~~~
asm/x86_64-gcc.c:389:6: **error**: conflicting types for 'bn_mul_comba8'
 void bn_mul_comba8(BN_ULONG *r, BN_ULONG *a, BN_ULONG *b)
      ^~~~~~~~~~~~~
In file included from asm/x86_64-gcc.c:1:0:
asm/../bn_lcl.h:509:6: note: previous declaration of 'bn_mul_comba8' was here
 void bn_mul_comba8(BN_ULONG *r, BN_ULONG *a, BN_ULONG *b);
      ^~~~~~~~~~~~~
asm/x86_64-gcc.c:492:6: **error**: conflicting types for 'bn_mul_comba4'
 void bn_mul_comba4(BN_ULONG *r, BN_ULONG *a, BN_ULONG *b)
      ^~~~~~~~~~~~~
In file included from asm/x86_64-gcc.c:1:0:
asm/../bn_lcl.h:510:6: note: previous declaration of 'bn_mul_comba4' was here
 void bn_mul_comba4(BN_ULONG *r, BN_ULONG *a, BN_ULONG *b);
      ^~~~~~~~~~~~~
asm/x86_64-gcc.c:531:6: **error**: conflicting types for 'bn_sqr_comba8'
 void bn_sqr_comba8(BN_ULONG *r, const BN_ULONG *a)
      ^~~~~~~~~~~~~
In file included from asm/x86_64-gcc.c:1:0:
asm/../bn_lcl.h:512:6: note: previous declaration of 'bn_sqr_comba8' was here
 void bn_sqr_comba8(BN_ULONG *r, const BN_ULONG *a);
      ^~~~~~~~~~~~~
asm/x86_64-gcc.c:606:6: **error**: conflicting types for 'bn_sqr_comba4'
 void bn_sqr_comba4(BN_ULONG *r, const BN_ULONG *a)
      ^~~~~~~~~~~~~
In file included from asm/x86_64-gcc.c:1:0:
asm/../bn_lcl.h:513:6: note: previous declaration of 'bn_sqr_comba4' was here
 void bn_sqr_comba4(BN_ULONG *r, const BN_ULONG *a);
      ^~~~~~~~~~~~~
make[2]: *** [Makefile:104: x86_64-gcc.o] Error 1
make[2]: Leaving directory '/home/Odin/openssl-1.0.2n/crypto/bn'
make[1]: *** [Makefile:88: subdirs] Error 1
make[1]: Leaving directory '/home/Odin/openssl-1.0.2n/crypto'
make: *** [Makefile:287: build_crypto] Error 1

Am using SYS2 on Windows 10 64-Bit. Compiling with MingGw 64 Bit.

**Comment by odin-loki** [comment]
Is this OpenSSL version.  2017-Dec-07 13:47:59  openssl-1.0.2n.tar.gz.

**Comment by kaduk** [comment]
You also need to provide the Configure/config invocation.  (Also, markdown has plenty of ways to provide quoted literal, such as enclosing in triple-backticks (`) -- it would be easier to read things if you use them.)

**Comment by odin-loki** [comment]
Needs 

#include <windows.h>

on dso_win32.c file.

**Comment by odin-loki** [comment]
And there was a whole bunch of double prototype definitions. One was undefined and needed to be put in the right place. Forget which ones.

**Comment by kaduk** [comment]
There are lots of OpenSSL developers who do not regularly have access to windows systems.  If you do not want to have to wait for help from those who do have such access, please provide more detail, such as actual console output.

**Comment by kaduk** [comment]
> Needs ```#include <windows.h>``` on dso_win32.c file.

Do you have some other version of OpenSSL installed on your build system such that the "wrong" headers might be getting pulled in?  dso_win32.c includes ```cryptlib.h``` which includes ```e_os.h``` which includes ```windows.h```.

**Comment by odin-loki** [comment]
No, never used OpenSSL before,

**Comment by odin-loki** [comment]
I am actually not sure if it is the diference between using GCC and MingW64 that is the problem.

**Comment by odin-loki** [comment]
Ok. So after fiddling around alot more. The errors I found only affect using normal GCC on SYS2 with Windows 10.
The LTS of OpenSSL compiles (a few warnings) on MinGw64 on SYS2 with Windows 10.

**Comment by t-j-h** [comment]
It looks like you are trying to use plain gcc to compile when mingw is required.

**Comment by mattcaswell** [comment]
What does typing `gcc --version` report?

**Comment by tskardal** [comment]
I ended up on this issue after getting the error after following this guide https://wiki.qt.io/Compiling_OpenSSL_with_MinGW - My problem was that I didn't use the correct gcc because the `export PATH= ...` example was wrong in my case.

Doing `export PATH="/c/msys64/mingw32/bin:$PATH"`
instead of `export PATH="/c/msys2/mingw32/bin:$PATH"`
made it for me. Just wanted to fill in!

**Comment by richsalz** [comment]
Glad you got it resolved!

**Comment by igormcoelho** [comment]
I don't know if it's related, but I built openssl1.1.0i with no problems for linux, and the cross compiling windows build is now failing tests:
```
make test
make depend && make _tests
make[1]: Entering directory '/home/imcoelho/git-reps/openssl-build/openssl-1.1.0i/build-win-64'
make[1]: Leaving directory '/home/imcoelho/git-reps/openssl-build/openssl-1.1.0i/build-win-64'
make[1]: Entering directory '/home/imcoelho/git-reps/openssl-build/openssl-1.1.0i/build-win-64'
( cd test; \
  mkdir -p test-runs; \
  SRCTOP=../.. \
  BLDTOP=../. \
  RESULT_D=test-runs \
  PERL="/usr/bin/perl" \
  EXE_EXT=.exe \
  OPENSSL_ENGINES=`cd .././engines; pwd` \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl ../../test/run_tests.pl  )
../../test/recipes/01-test_abort.t ............ ok   
../../test/recipes/01-test_sanity.t ........... ok   
../../test/recipes/01-test_symbol_presence.t .. ok   
../../test/recipes/02-test_ordinals.t ......... ok   
../../test/recipes/03-test_exdata.t ........... ok   
../../test/recipes/03-test_ui.t ............... ok   
../../test/recipes/04-test_err.t .............. ok   
../../test/recipes/04-test_pem.t .............. ok     
../../test/recipes/05-test_bf.t ............... ok   
../../test/recipes/05-test_cast.t ............. ok   
../../test/recipes/05-test_des.t .............. ok   
../../test/recipes/05-test_hmac.t ............. ok   
../../test/recipes/05-test_idea.t ............. ok   
../../test/recipes/05-test_md2.t .............. skipped: md2 is not supported by this OpenSSL build
../../test/recipes/05-test_md4.t .............. ok   
../../test/recipes/05-test_md5.t .............. ok   
../../test/recipes/05-test_mdc2.t ............. ok   
../../test/recipes/05-test_rand.t ............. ok   
../../test/recipes/05-test_rc2.t .............. ok   
../../test/recipes/05-test_rc4.t .............. ok   
../../test/recipes/05-test_rc5.t .............. skipped: rc5 is not supported by this OpenSSL build
../../test/recipes/05-test_rmd.t .............. ok   
../../test/recipes/05-test_sha1.t ............. ok   
../../test/recipes/05-test_sha256.t ........... ok   
../../test/recipes/05-test_sha512.t ........... ok   
../../test/recipes/05-test_wp.t ............... ok   
../../test/recipes/10-test_bn.t ............... ok   
../../test/recipes/10-test_exp.t .............. ok   
../../test/recipes/15-test_dh.t ............... ok   
../../test/recipes/15-test_dsa.t .............. ok   
../../test/recipes/15-test_ec.t ............... ok   
../../test/recipes/15-test_ecdsa.t ............ ok   
../../test/recipes/15-test_genrsa.t ........... ok   
../../test/recipes/15-test_rsa.t .............. ok   
../../test/recipes/15-test_rsapss.t ........... ok   
../../test/recipes/20-test_enc.t .............. ok       
../../test/recipes/20-test_passwd.t ........... ok   
../../test/recipes/25-test_crl.t .............. ok   
../../test/recipes/25-test_d2i.t .............. ok     
../../test/recipes/25-test_pkcs7.t ............ ok   
../../test/recipes/25-test_req.t .............. ok   
../../test/recipes/25-test_sid.t .............. ok   
../../test/recipes/25-test_verify.t ........... ok       T
../../test/recipes/25-test_x509.t ............. ok   
../../test/recipes/30-test_afalg.t ............ skipped: test_afalg not supported for this build
../../test/recipes/30-test_engine.t ........... ok   
../../test/recipes/30-test_evp.t .............. ok   
../../test/recipes/30-test_evp_extra.t ........ ok   
../../test/recipes/30-test_pbelu.t ............ ok   
../../test/recipes/40-test_rehash.t ........... skipped: test_rehash is not available on this platform
../../test/recipes/60-test_x509_dup_cert.t .... ok   
../../test/recipes/60-test_x509_store.t ....... skipped: test_rehash is not available on this platform
../../test/recipes/60-test_x509_time.t ........ ok   
../../test/recipes/70-test_asyncio.t .......... ok   
../../test/recipes/70-test_bad_dtls.t ......... ok   
../../test/recipes/70-test_clienthello.t ...... ok   
../../test/recipes/70-test_packet.t ........... ok   
../../test/recipes/70-test_sslcbcpadding.t .... ok   
../../test/recipes/70-test_sslcertstatus.t .... ok   
../../test/recipes/70-test_sslextension.t ..... ok   
../../test/recipes/70-test_sslmessages.t ...... ok   
../../test/recipes/70-test_sslrecords.t ....... Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/11 subtests 
../../test/recipes/70-test_sslsessiontick.t ... skipped: Unable to start up Proxy for tests
../../test/recipes/70-test_sslskewith0p.t ..... skipped: Unable to start up Proxy for tests
../../test/recipes/70-test_sslvertol.t ........ skipped: Unable to start up Proxy for tests
../../test/recipes/70-test_tlsextms.t ......... skipped: Unable to start up Proxy for tests
../../test/recipes/70-test_verify_extra.t ..... ok   
../../test/recipes/80-test_ca.t ............... ok   
../../test/recipes/80-test_cipherlist.t ....... ok   
../../test/recipes/80-test_cms.t .............. ok   
../../test/recipes/80-test_ct.t ............... ok   
../../test/recipes/80-test_dane.t ............. ok   
../../test/recipes/80-test_dtls.t ............. ok   
../../test/recipes/80-test_dtlsv1listen.t ..... ok   
../../test/recipes/80-test_ocsp.t ............. ok     
../../test/recipes/80-test_pkcs12.t ........... ok   
../../test/recipes/80-test_ssl_new.t .......... ok     
../../test/recipes/80-test_ssl_old.t .......... ok   
../../test/recipes/80-test_ssl_test_ctx.t ..... ok   
../../test/recipes/80-test_sslcorrupt.t ....... ok   
../../test/recipes/80-test_tsa.t .............. ok     
../../test/recipes/80-test_x509aux.t .......... ok   
../../test/recipes/90-test_async.t ............ ok   
../../test/recipes/90-test_bio_enc.t .......... ok   
../../test/recipes/90-test_bioprint.t ......... ok   
../../test/recipes/90-test_constant_time.t .... ok   
../../test/recipes/90-test_fatalerr.t ......... ok   
../../test/recipes/90-test_fuzz.t ............. ok     
../../test/recipes/90-test_gmdiff.t ........... ok   
../../test/recipes/90-test_heartbeat.t ........ skipped: heartbeats is not supported by this OpenSSL build
../../test/recipes/90-test_ige.t .............. ok   
../../test/recipes/90-test_memleak.t .......... ok   
../../test/recipes/90-test_p5_crpt2.t ......... ok   
../../test/recipes/90-test_secmem.t ........... ok   
../../test/recipes/90-test_shlibload.t ........ ok   
../../test/recipes/90-test_srp.t .............. ok   
../../test/recipes/90-test_sslapi.t ........... ok   
../../test/recipes/90-test_threads.t .......... ok   
../../test/recipes/90-test_v3name.t ........... ok   

Test Summary Report
-------------------
../../test/recipes/70-test_sslrecords.t     (Wstat: 1280 Tests: 11 Failed: 5)
  Failed tests:  7-11
  Non-zero exit status: 5
Files=99, Tests=532, 1187 wallclock secs ( 0.65 usr  0.10 sys + 95.36 cusr 116.44 csys = 212.55 CPU)
Result: FAIL
Makefile:157: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/imcoelho/git-reps/openssl-build/openssl-1.1.0i/build-win-64'
Makefile:155: recipe for target 'tests' failed
make: *** [tests] Error 2
```

I had this same compiling issue using `./Configure mingw64 shared --cross-compile-prefix=x86_64-w64-mingw32-`, so I removed `shared`, it compiled, but failed tests.

So I tried to build LTS version 1.0.2p, and it is also failing tests... is that normal?

```
The following command should have some OK's and some failures
There are definitly a few expired certificates
../util/shlib_wrap.sh ../apps/openssl verify -CApath ../certs/demo ../certs/demo/*.pem
../certs/demo/ca-cert.pem: C = AU, ST = Queensland, O = CryptSoft Pty Ltd, CN = Test CA (1024 bit)
error 20 at 0 depth lookup:unable to get local issuer certificate
../certs/demo/dsa-ca.pem: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = CA
error 20 at 0 depth lookup:unable to get local issuer certificate
388:error:0B06E06B:x509 certificate routines:X509_get_pubkey_parameters:unable to find parameters in chain:x509_vfy.c:2057:
../certs/demo/dsa-pca.pem: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = PCA
error 18 at 0 depth lookup:self signed certificate
C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = PCA
error 10 at 0 depth lookup:certificate has expired
OK
../certs/demo/pca-cert.pem: C = AU, ST = Queensland, O = CryptSoft Pty Ltd, CN = Test PCA (1024 bit)
error 18 at 0 depth lookup:self signed certificate
C = AU, ST = Queensland, O = CryptSoft Pty Ltd, CN = Test PCA (1024 bit)
error 10 at 0 depth lookup:certificate has expired
OK
Makefile:273: recipe for target 'test_verify' failed
make[1]: *** [test_verify] Error 2
make[1]: Leaving directory '/home/imcoelho/git-reps/openssl-build/openssl-1.0.2p/test'
Makefile:473: recipe for target 'tests' failed
make: *** [tests] Error 2
```
Used this configuration: `./Configure mingw64 shared --cross-compile-prefix=x86_64-w64-mingw32-`

**Comment by mspncp** [comment]
@igormcoelho please don't reuse existing (closed) issues to report new issues. If you think that your issue is related to this one, you can refer to it by its GitHub number.

**Comment by igormcoelho** [comment]
oh, sorry @mspncp , I will open a new one and related to this :smile:
