### ISSUE TITLE
More Errors In Source.

### ISSUE THREAD

**Issue by odin-loki** [openssl/openssl#5005]
So after I deleted all the double function definitions in the LTS Release of OpenSSL. And put one in the right place. I get this litany of Errors. Please keep the interns away from the code.

dso_win32.c: In function 'win32_load':
dso_win32.c:169:5: error: unknown type name 'HINSTANCE'
     HINSTANCE h = NULL, *p = NULL;
     ^~~~~~~~~
dso_win32.c:169:19: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     HINSTANCE h = NULL, *p = NULL;
                   ^~~~
dso_win32.c:177:9: warning: implicit declaration of function 'LoadLibraryA' [-Wimplicit-function-declaration]
     h = LoadLibraryA(filename);
         ^~~~~~~~~~~~
dso_win32.c:178:11: warning: comparison between pointer and integer
     if (h == NULL) {
           ^~
dso_win32.c:183:10: error: 'HINSTANCE' undeclared (first use in this function)
     p = (HINSTANCE *) OPENSSL_malloc(sizeof(HINSTANCE));
          ^~~~~~~~~
dso_win32.c:183:10: note: each undeclared identifier is reported only once for each function it appears in
dso_win32.c:183:21: error: expected expression before ')' token
     p = (HINSTANCE *) OPENSSL_malloc(sizeof(HINSTANCE));
                     ^
dso_win32.c:202:11: warning: comparison between pointer and integer
     if (h != NULL)
           ^~
dso_win32.c:203:9: warning: implicit declaration of function 'FreeLibrary' [-Wimplicit-function-declaration]
         FreeLibrary(h);
         ^~~~~~~~~~~
dso_win32.c: In function 'win32_unload':
dso_win32.c:209:5: error: unknown type name 'HINSTANCE'
     HINSTANCE *p;
     ^~~~~~~~~
dso_win32.c: In function 'win32_bind_var':
dso_win32.c:240:5: error: unknown type name 'HINSTANCE'
     HINSTANCE *ptr;
     ^~~~~~~~~
dso_win32.c:256:11: warning: implicit declaration of function 'GetProcAddress' [-Wimplicit-function-declaration]
     sym = GetProcAddress(*ptr, symname);
           ^~~~~~~~~~~~~~
dso_win32.c:256:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     sym = GetProcAddress(*ptr, symname);
         ^
dso_win32.c: In function 'win32_bind_func':
dso_win32.c:267:5: error: unknown type name 'HINSTANCE'
     HINSTANCE *ptr;
     ^~~~~~~~~
dso_win32.c:283:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     sym = GetProcAddress(*ptr, symname);
         ^
In file included from dso_win32.c:614:0:
/usr/include/w32api/tlhelp32.h: At top level:
/usr/include/w32api/tlhelp32.h:15:3: error: unknown type name 'HANDLE'
   HANDLE WINAPI CreateToolhelp32Snapshot(DWORD dwFlags,DWORD th32ProcessID);
   ^~~~~~
/usr/include/w32api/tlhelp32.h:15:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'CreateToolhelp32Snapshot'
   HANDLE WINAPI CreateToolhelp32Snapshot(DWORD dwFlags,DWORD th32ProcessID);
                 ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:26:5: error: unknown type name 'SIZE_T'
     SIZE_T dwSize;
     ^~~~~~
/usr/include/w32api/tlhelp32.h:27:5: error: unknown type name 'DWORD'
     DWORD th32ProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:28:5: error: unknown type name 'ULONG_PTR'
     ULONG_PTR th32HeapID;
     ^~~~~~~~~
/usr/include/w32api/tlhelp32.h:29:5: error: unknown type name 'DWORD'
     DWORD dwFlags;
     ^~~~~
/usr/include/w32api/tlhelp32.h:37:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Heap32ListFirst(HANDLE hSnapshot,LPHEAPLIST32 lphl);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:37:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Heap32ListFirst'
   WINBOOL WINAPI Heap32ListFirst(HANDLE hSnapshot,LPHEAPLIST32 lphl);
                  ^~~~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:38:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Heap32ListNext(HANDLE hSnapshot,LPHEAPLIST32 lphl);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:38:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Heap32ListNext'
   WINBOOL WINAPI Heap32ListNext(HANDLE hSnapshot,LPHEAPLIST32 lphl);
                  ^~~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:41:5: error: unknown type name 'SIZE_T'
     SIZE_T dwSize;
     ^~~~~~
/usr/include/w32api/tlhelp32.h:42:5: error: unknown type name 'HANDLE'
     HANDLE hHandle;
     ^~~~~~
/usr/include/w32api/tlhelp32.h:43:5: error: unknown type name 'ULONG_PTR'
     ULONG_PTR dwAddress;
     ^~~~~~~~~
/usr/include/w32api/tlhelp32.h:44:5: error: unknown type name 'SIZE_T'
     SIZE_T dwBlockSize;
     ^~~~~~
/usr/include/w32api/tlhelp32.h:45:5: error: unknown type name 'DWORD'
     DWORD dwFlags;
     ^~~~~
/usr/include/w32api/tlhelp32.h:46:5: error: unknown type name 'DWORD'
     DWORD dwLockCount;
     ^~~~~
/usr/include/w32api/tlhelp32.h:47:5: error: unknown type name 'DWORD'
     DWORD dwResvd;
     ^~~~~
/usr/include/w32api/tlhelp32.h:48:5: error: unknown type name 'DWORD'
     DWORD th32ProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:49:5: error: unknown type name 'ULONG_PTR'
     ULONG_PTR th32HeapID;
     ^~~~~~~~~
/usr/include/w32api/tlhelp32.h:58:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Heap32First(LPHEAPENTRY32 lphe,DWORD th32ProcessID,ULONG_PTR th32HeapID);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:58:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Heap32First'
   WINBOOL WINAPI Heap32First(LPHEAPENTRY32 lphe,DWORD th32ProcessID,ULONG_PTR th32HeapID);
                  ^~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:59:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Heap32Next(LPHEAPENTRY32 lphe);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:59:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Heap32Next'
   WINBOOL WINAPI Heap32Next(LPHEAPENTRY32 lphe);
                  ^~~~~~~~~~
/usr/include/w32api/tlhelp32.h:60:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Toolhelp32ReadProcessMemory(DWORD th32ProcessID,LPCVOID lpBaseAddress,LPVOID lpBuffer,SIZE_T cbRead,SIZE_T *lpNumberOfBytesRead);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:60:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Toolhelp32ReadProcessMemory'
   WINBOOL WINAPI Toolhelp32ReadProcessMemory(DWORD th32ProcessID,LPCVOID lpBaseAddress,LPVOID lpBuffer,SIZE_T cbRead,SIZE_T *lpNumberOfBytesRead);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from dso_win32.c:614:0:
/usr/include/w32api/tlhelp32.h:63:5: error: unknown type name 'DWORD'
     DWORD dwSize;
     ^~~~~
/usr/include/w32api/tlhelp32.h:64:5: error: unknown type name 'DWORD'
     DWORD cntUsage;
     ^~~~~
/usr/include/w32api/tlhelp32.h:65:5: error: unknown type name 'DWORD'
     DWORD th32ProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:66:5: error: unknown type name 'ULONG_PTR'
     ULONG_PTR th32DefaultHeapID;
     ^~~~~~~~~
/usr/include/w32api/tlhelp32.h:67:5: error: unknown type name 'DWORD'
     DWORD th32ModuleID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:68:5: error: unknown type name 'DWORD'
     DWORD cntThreads;
     ^~~~~
/usr/include/w32api/tlhelp32.h:69:5: error: unknown type name 'DWORD'
     DWORD th32ParentProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:70:5: error: unknown type name 'LONG'
     LONG pcPriClassBase;
     ^~~~
/usr/include/w32api/tlhelp32.h:71:5: error: unknown type name 'DWORD'
     DWORD dwFlags;
     ^~~~~
/usr/include/w32api/tlhelp32.h:72:5: error: unknown type name 'WCHAR'
     WCHAR szExeFile[MAX_PATH];
     ^~~~~
/usr/include/w32api/tlhelp32.h:72:21: error: 'MAX_PATH' undeclared here (not in a function)
     WCHAR szExeFile[MAX_PATH];
                     ^~~~~~~~
/usr/include/w32api/tlhelp32.h:77:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Process32FirstW(HANDLE hSnapshot,LPPROCESSENTRY32W lppe);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:77:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Process32FirstW'
   WINBOOL WINAPI Process32FirstW(HANDLE hSnapshot,LPPROCESSENTRY32W lppe);
                  ^~~~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:78:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Process32NextW(HANDLE hSnapshot,LPPROCESSENTRY32W lppe);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:78:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Process32NextW'
   WINBOOL WINAPI Process32NextW(HANDLE hSnapshot,LPPROCESSENTRY32W lppe);
                  ^~~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:81:5: error: unknown type name 'DWORD'
     DWORD dwSize;
     ^~~~~
/usr/include/w32api/tlhelp32.h:82:5: error: unknown type name 'DWORD'
     DWORD cntUsage;
     ^~~~~
/usr/include/w32api/tlhelp32.h:83:5: error: unknown type name 'DWORD'
     DWORD th32ProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:84:5: error: unknown type name 'ULONG_PTR'
     ULONG_PTR th32DefaultHeapID;
     ^~~~~~~~~
/usr/include/w32api/tlhelp32.h:85:5: error: unknown type name 'DWORD'
     DWORD th32ModuleID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:86:5: error: unknown type name 'DWORD'
     DWORD cntThreads;
     ^~~~~
/usr/include/w32api/tlhelp32.h:87:5: error: unknown type name 'DWORD'
     DWORD th32ParentProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:88:5: error: unknown type name 'LONG'
     LONG pcPriClassBase;
     ^~~~
/usr/include/w32api/tlhelp32.h:89:5: error: unknown type name 'DWORD'
     DWORD dwFlags;
     ^~~~~
/usr/include/w32api/tlhelp32.h:90:5: error: unknown type name 'CHAR'
     CHAR szExeFile[MAX_PATH];
     ^~~~
/usr/include/w32api/tlhelp32.h:95:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Process32First(HANDLE hSnapshot,LPPROCESSENTRY32 lppe);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:95:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Process32First'
   WINBOOL WINAPI Process32First(HANDLE hSnapshot,LPPROCESSENTRY32 lppe);
                  ^~~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:96:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Process32Next(HANDLE hSnapshot,LPPROCESSENTRY32 lppe);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:96:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Process32Next'
   WINBOOL WINAPI Process32Next(HANDLE hSnapshot,LPPROCESSENTRY32 lppe);
                  ^~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:107:5: error: unknown type name 'DWORD'
     DWORD dwSize;
     ^~~~~
/usr/include/w32api/tlhelp32.h:108:5: error: unknown type name 'DWORD'
     DWORD cntUsage;
     ^~~~~
/usr/include/w32api/tlhelp32.h:109:5: error: unknown type name 'DWORD'
     DWORD th32ThreadID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:110:5: error: unknown type name 'DWORD'
     DWORD th32OwnerProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:111:5: error: unknown type name 'LONG'
     LONG tpBasePri;
     ^~~~
/usr/include/w32api/tlhelp32.h:112:5: error: unknown type name 'LONG'
     LONG tpDeltaPri;
     ^~~~
/usr/include/w32api/tlhelp32.h:113:5: error: unknown type name 'DWORD'
     DWORD dwFlags;
     ^~~~~
/usr/include/w32api/tlhelp32.h:118:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Thread32First(HANDLE hSnapshot,LPTHREADENTRY32 lpte);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:118:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Thread32First'
   WINBOOL WINAPI Thread32First(HANDLE hSnapshot,LPTHREADENTRY32 lpte);
                  ^~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:119:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Thread32Next(HANDLE hSnapshot,LPTHREADENTRY32 lpte);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:119:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Thread32Next'
   WINBOOL WINAPI Thread32Next(HANDLE hSnapshot,LPTHREADENTRY32 lpte);
                  ^~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:122:5: error: unknown type name 'DWORD'
     DWORD dwSize;
     ^~~~~
/usr/include/w32api/tlhelp32.h:123:5: error: unknown type name 'DWORD'
     DWORD th32ModuleID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:124:5: error: unknown type name 'DWORD'
     DWORD th32ProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:125:5: error: unknown type name 'DWORD'
     DWORD GlblcntUsage;
     ^~~~~
/usr/include/w32api/tlhelp32.h:126:5: error: unknown type name 'DWORD'
     DWORD ProccntUsage;
     ^~~~~
/usr/include/w32api/tlhelp32.h:127:5: error: unknown type name 'BYTE'
     BYTE *modBaseAddr;
     ^~~~
/usr/include/w32api/tlhelp32.h:128:5: error: unknown type name 'DWORD'
     DWORD modBaseSize;
     ^~~~~
/usr/include/w32api/tlhelp32.h:129:5: error: unknown type name 'HMODULE'
     HMODULE hModule;
     ^~~~~~~
/usr/include/w32api/tlhelp32.h:130:5: error: unknown type name 'WCHAR'
     WCHAR szModule[MAX_MODULE_NAME32 + 1];
     ^~~~~
/usr/include/w32api/tlhelp32.h:131:5: error: unknown type name 'WCHAR'
     WCHAR szExePath[MAX_PATH];
     ^~~~~
/usr/include/w32api/tlhelp32.h:136:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Module32FirstW(HANDLE hSnapshot,LPMODULEENTRY32W lpme);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:136:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Module32FirstW'
   WINBOOL WINAPI Module32FirstW(HANDLE hSnapshot,LPMODULEENTRY32W lpme);
                  ^~~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:137:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Module32NextW(HANDLE hSnapshot,LPMODULEENTRY32W lpme);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:137:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Module32NextW'
   WINBOOL WINAPI Module32NextW(HANDLE hSnapshot,LPMODULEENTRY32W lpme);
                  ^~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:140:5: error: unknown type name 'DWORD'
     DWORD dwSize;
     ^~~~~
/usr/include/w32api/tlhelp32.h:141:5: error: unknown type name 'DWORD'
     DWORD th32ModuleID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:142:5: error: unknown type name 'DWORD'
     DWORD th32ProcessID;
     ^~~~~
/usr/include/w32api/tlhelp32.h:143:5: error: unknown type name 'DWORD'
     DWORD GlblcntUsage;
     ^~~~~
/usr/include/w32api/tlhelp32.h:144:5: error: unknown type name 'DWORD'
     DWORD ProccntUsage;
     ^~~~~
/usr/include/w32api/tlhelp32.h:145:5: error: unknown type name 'BYTE'
     BYTE *modBaseAddr;
     ^~~~
/usr/include/w32api/tlhelp32.h:146:5: error: unknown type name 'DWORD'
     DWORD modBaseSize;
     ^~~~~
/usr/include/w32api/tlhelp32.h:147:5: error: unknown type name 'HMODULE'
     HMODULE hModule;
     ^~~~~~~
/usr/include/w32api/tlhelp32.h:154:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Module32First(HANDLE hSnapshot,LPMODULEENTRY32 lpme);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:154:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Module32First'
   WINBOOL WINAPI Module32First(HANDLE hSnapshot,LPMODULEENTRY32 lpme);
                  ^~~~~~~~~~~~~
/usr/include/w32api/tlhelp32.h:155:3: error: unknown type name 'WINBOOL'
   WINBOOL WINAPI Module32Next(HANDLE hSnapshot,LPMODULEENTRY32 lpme);
   ^~~~~~~
/usr/include/w32api/tlhelp32.h:155:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Module32Next'
   WINBOOL WINAPI Module32Next(HANDLE hSnapshot,LPMODULEENTRY32 lpme);
                  ^~~~~~~~~~~~
dso_win32.c:624:16: error: unknown type name 'WINAPI'
 typedef HANDLE(WINAPI *CREATETOOLHELP32SNAPSHOT) (DWORD, DWORD);
                ^~~~~~
dso_win32.c:625:14: error: unknown type name 'WINAPI'
 typedef BOOL(WINAPI *CLOSETOOLHELP32SNAPSHOT) (HANDLE);
              ^~~~~~
dso_win32.c:626:14: error: unknown type name 'WINAPI'
 typedef BOOL(WINAPI *MODULE32) (HANDLE, MODULEENTRY32 *);
              ^~~~~~
dso_win32.c: In function 'win32_pathbyaddr':
dso_win32.c:630:5: error: unknown type name 'HMODULE'
     HMODULE dll;
     ^~~~~~~
dso_win32.c:631:5: error: unknown type name 'HANDLE'
     HANDLE hModuleSnap = INVALID_HANDLE_VALUE;
     ^~~~~~
dso_win32.c:631:26: error: 'INVALID_HANDLE_VALUE' undeclared (first use in this function)
     HANDLE hModuleSnap = INVALID_HANDLE_VALUE;
                          ^~~~~~~~~~~~~~~~~~~~
dso_win32.c:633:5: error: unknown type name 'CREATETOOLHELP32SNAPSHOT'
     CREATETOOLHELP32SNAPSHOT create_snap;
     ^~~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:634:5: error: unknown type name 'CLOSETOOLHELP32SNAPSHOT'
     CLOSETOOLHELP32SNAPSHOT close_snap;
     ^~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:635:5: error: unknown type name 'MODULE32'
     MODULE32 module_first, module_next;
     ^~~~~~~~
dso_win32.c:647:11: warning: implicit declaration of function 'LoadLibrary' [-Wimplicit-function-declaration]
     dll = LoadLibrary(TEXT(DLLNAME));
           ^~~~~~~~~~~
dso_win32.c:647:23: warning: implicit declaration of function 'TEXT' [-Wimplicit-function-declaration]
     dll = LoadLibrary(TEXT(DLLNAME));
                       ^~~~
dso_win32.c:648:13: warning: comparison between pointer and integer
     if (dll == NULL) {
             ^~
dso_win32.c:653:20: error: 'CREATETOOLHELP32SNAPSHOT' undeclared (first use in this function)
     create_snap = (CREATETOOLHELP32SNAPSHOT)
                    ^~~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:654:9: error: expected ';' before 'GetProcAddress'
         GetProcAddress(dll, "CreateToolhelp32Snapshot");
         ^~~~~~~~~~~~~~
dso_win32.c:655:21: warning: comparison between pointer and integer
     if (create_snap == NULL) {
                     ^~
dso_win32.c:665:19: error: 'CLOSETOOLHELP32SNAPSHOT' undeclared (first use in this function)
     close_snap = (CLOSETOOLHELP32SNAPSHOT) CloseHandle;
                   ^~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:665:44: error: expected ';' before 'CloseHandle'
     close_snap = (CLOSETOOLHELP32SNAPSHOT) CloseHandle;
                                            ^~~~~~~~~~~
dso_win32.c:667:21: error: 'MODULE32' undeclared (first use in this function)
     module_first = (MODULE32) GetProcAddress(dll, "Module32First");
                     ^~~~~~~~
dso_win32.c:667:31: error: expected ';' before 'GetProcAddress'
     module_first = (MODULE32) GetProcAddress(dll, "Module32First");
                               ^~~~~~~~~~~~~~
dso_win32.c:668:30: error: expected ';' before 'GetProcAddress'
     module_next = (MODULE32) GetProcAddress(dll, "Module32Next");
                              ^~~~~~~~~~~~~~
dso_win32.c:670:20: error: invalid type argument of unary '*' (have 'int')
     hModuleSnap = (*create_snap) (TH32CS_SNAPMODULE, 0);
                    ^~~~~~~~~~~~
dso_win32.c:679:11: error: invalid type argument of unary '*' (have 'int')
     if (!(*module_first) (hModuleSnap, &me32)) {
           ^~~~~~~~~~~~~
dso_win32.c:680:10: error: invalid type argument of unary '*' (have 'int')
         (*close_snap) (hModuleSnap);
          ^~~~~~~~~~~
dso_win32.c:687:14: error: 'BYTE' undeclared (first use in this function)
         if ((BYTE *) addr >= me32.modBaseAddr &&
              ^~~~
dso_win32.c:687:20: error: expected expression before ')' token
         if ((BYTE *) addr >= me32.modBaseAddr &&
                    ^
dso_win32.c:689:14: error: invalid type argument of unary '*' (have 'int')
             (*close_snap) (hModuleSnap);
              ^~~~~~~~~~~
dso_win32.c:721:15: error: invalid type argument of unary '*' (have 'int')
     } while ((*module_next) (hModuleSnap, &me32));
               ^~~~~~~~~~~~
dso_win32.c:723:6: error: invalid type argument of unary '*' (have 'int')
     (*close_snap) (hModuleSnap);
      ^~~~~~~~~~~
dso_win32.c: In function 'win32_globallookup':
dso_win32.c:730:5: error: unknown type name 'HMODULE'
     HMODULE dll;
     ^~~~~~~
dso_win32.c:731:5: error: unknown type name 'HANDLE'
     HANDLE hModuleSnap = INVALID_HANDLE_VALUE;
     ^~~~~~
dso_win32.c:731:26: error: 'INVALID_HANDLE_VALUE' undeclared (first use in this function)
     HANDLE hModuleSnap = INVALID_HANDLE_VALUE;
                          ^~~~~~~~~~~~~~~~~~~~
dso_win32.c:733:5: error: unknown type name 'CREATETOOLHELP32SNAPSHOT'
     CREATETOOLHELP32SNAPSHOT create_snap;
     ^~~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:734:5: error: unknown type name 'CLOSETOOLHELP32SNAPSHOT'
     CLOSETOOLHELP32SNAPSHOT close_snap;
     ^~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:735:5: error: unknown type name 'MODULE32'
     MODULE32 module_first, module_next;
     ^~~~~~~~
dso_win32.c:736:5: error: unknown type name 'FARPROC'
     FARPROC ret = NULL;
     ^~~~~~~
dso_win32.c:736:19: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     FARPROC ret = NULL;
                   ^~~~
dso_win32.c:739:13: warning: comparison between pointer and integer
     if (dll == NULL) {
             ^~
dso_win32.c:744:20: error: 'CREATETOOLHELP32SNAPSHOT' undeclared (first use in this function)
     create_snap = (CREATETOOLHELP32SNAPSHOT)
                    ^~~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:745:9: error: expected ';' before 'GetProcAddress'
         GetProcAddress(dll, "CreateToolhelp32Snapshot");
         ^~~~~~~~~~~~~~
dso_win32.c:746:21: warning: comparison between pointer and integer
     if (create_snap == NULL) {
                     ^~
dso_win32.c:756:19: error: 'CLOSETOOLHELP32SNAPSHOT' undeclared (first use in this function)
     close_snap = (CLOSETOOLHELP32SNAPSHOT) CloseHandle;
                   ^~~~~~~~~~~~~~~~~~~~~~~
dso_win32.c:756:44: error: expected ';' before 'CloseHandle'
     close_snap = (CLOSETOOLHELP32SNAPSHOT) CloseHandle;
                                            ^~~~~~~~~~~
dso_win32.c:758:21: error: 'MODULE32' undeclared (first use in this function)
     module_first = (MODULE32) GetProcAddress(dll, "Module32First");
                     ^~~~~~~~
dso_win32.c:758:31: error: expected ';' before 'GetProcAddress'
     module_first = (MODULE32) GetProcAddress(dll, "Module32First");
                               ^~~~~~~~~~~~~~
dso_win32.c:759:30: error: expected ';' before 'GetProcAddress'
     module_next = (MODULE32) GetProcAddress(dll, "Module32Next");
                              ^~~~~~~~~~~~~~
dso_win32.c:761:20: error: invalid type argument of unary '*' (have 'int')
     hModuleSnap = (*create_snap) (TH32CS_SNAPMODULE, 0);
                    ^~~~~~~~~~~~
dso_win32.c:770:11: error: invalid type argument of unary '*' (have 'int')
     if (!(*module_first) (hModuleSnap, &me32)) {
           ^~~~~~~~~~~~~
dso_win32.c:771:10: error: invalid type argument of unary '*' (have 'int')
         (*close_snap) (hModuleSnap);
          ^~~~~~~~~~~
dso_win32.c:778:14: error: invalid type argument of unary '*' (have 'int')
             (*close_snap) (hModuleSnap);
              ^~~~~~~~~~~
dso_win32.c:780:20: warning: return makes pointer from integer without a cast [-Wint-conversion]
             return ret;
                    ^~~
dso_win32.c:782:15: error: invalid type argument of unary '*' (have 'int')
     } while ((*module_next) (hModuleSnap, &me32));
               ^~~~~~~~~~~~
dso_win32.c:784:6: error: invalid type argument of unary '*' (have 'int')
     (*close_snap) (hModuleSnap);
      ^~~~~~~~~~~
make[2]: *** [<builtin>: dso_win32.o] Error 1
make[2]: Leaving directory '/home/Odin/openssl-1.0.2n/crypto/dso'
make[1]: *** [Makefile:88: subdirs] Error 1
make[1]: Leaving directory '/home/Odin/openssl-1.0.2n/crypto'
make: *** [Makefile:287: build_crypto] Error 1

Again I am using Windows 10 64 bit. Compiling using MingW 64bit and and using SYS2.

**Comment by kaduk** [comment]
> So after I deleted all the double function definitions in the LTS Release of OpenSSL. And put one in the right place. I get this litany of Errors. Please keep the interns away from the code.

Someone who "watches" the entire repo might know that you are trying to refer to #5004 , but someone coming to this later has no idea what you are trying to refer to.  The remark about interns is also not needed; this code does work for many other people.

Since this report is apparently predicated on some local patches that you have declined to publish, as well as not specifying the full Configure invocation, I will close it in preference of #5004.

**Comment by odin-loki** [comment]
Needs

#include <windows.h>

on dso_win32.c file.

**Comment by t-j-h** [comment]
e_os.h has the #include <windows.h> in it ...  and e_os.h is included.

If you are not getting that included then you do not have the right configuration in place - as this will get defined for the windows based configurations.
