### ISSUE TITLE
error: ‘BN_MASK2’ undeclared

### ISSUE THREAD

**Issue by ilovelinux** [openssl/openssl#5006]
It was defined in OpenSSL 1.0.2 in openssl/bn.h as:
Line 189: `#  define BN_MASK2        (0xffffffffffffffffL)`
or
Line 218: `#  define BN_MASK2        (0xffffffffffffffffLL)`
or
Line 247: `#  define BN_MASK2        (0xffffffffL)`
But it has been removed in OpenSSL 1.1.0. How can I replace it?

**Comment by kroeckx** [comment]
BN_MASK2 is an implementation detail. Your code should not be
using it. What are you trying to do with it?

**Comment by ilovelinux** [comment]
I solved my problem.
I'm fix incompatibility errors of a repository and it was one of them.
Who wrote that code was using BN_MASK2 improperly.
Thanks for your time :)
