### ISSUE TITLE
Typo in displaying CRL Issuing Distribution Point extension

### ISSUE THREAD

**Issue by mpg** [openssl/openssl#5014]
When using `openssl crl -noout -text` on a CRL that includes the Issuing Distribution Point extension, the name of this extension is displayed as `X509v3 Issuing Distrubution Point` (notice the `u` in `DistrUbution`).

**Comment by mattcaswell** [comment]
This is already fixed in master and 1.1.0 (b9b6a7e5). I guess whoever did the fix decided it wasn't worth backporting to 1.0.2.
