### ISSUE TITLE
How can I decrypt an encrypted private key in my java program

### ISSUE THREAD

**Issue by sd1700092** [openssl/openssl#5015]
I use "openssl enpkey -algorithm RSA -out privatekey.pem -pass pass:1234 -des-ede3-cbc" and I got a password protected private key...
How can I decrypt it, since I want to use a Java program to use the RSA function. 
(I know how to realize RSA in Java program, but I just dont know how to use it when my private key is password protected)
So how shall I write my java program?

**Comment by levitte** [comment]
It's better to post this kind of question to openssl-users@openssl.org.  See https://www.openssl.org/community/mailinglists.html for further information on the mailing lists.
