### ISSUE TITLE
kECDHe and similar ciphers are documented but ignored

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#5022]
Hi,

as mentioned in https://github.com/openssl/openssl/pull/4980#discussion_r158740589
cipher strings like `-kECDHe` used to work from 1.0.0 to 1.0.2 but do no longer work today.
these keywords are mentioned as CHANGES between 0.9.8n and 1.0.0:

```
     The temporary ciphersuite alias "ECCdraft" is no longer
     available, and ECC ciphersuites are no longer excluded from "ALL"
     and "DEFAULT".  The following aliases now exist for RFC 4492
     ciphersuites, most of these by analogy with the DH case:

         kECDHr   - ECDH cert, signed with RSA
         kECDHe   - ECDH cert, signed with ECDSA
         kECDH    - ECDH cert (signed with either RSA or ECDSA)
         kEECDH   - ephemeral ECDH
         ECDH     - ECDH cert or ephemeral ECDH

         aECDH    - ECDH cert
         aECDSA   - ECDSA cert
         ECDSA    - ECDSA cert

         AECDH    - anonymous ECDH
         EECDH    - non-anonymous ephemeral ECDH (equivalent to "kEECDH:-AECDH")

     [Bodo Moeller]
```

While `openssl ciphers kECDHe` returns a failure, which is probably Okay,
`openssl ciphers 'DEFAULT:!kECDHe'` just ignores the kECDHe keyword,
which is questionable.

**Comment by t-j-h** [comment]
It is not ignoring the kECDHe keyword in ciphers - it is ignoring anything it doesn't know about. That has I believe always been the behaviour.

e.g.

openssl ciphers DEFAULT:complete-rubbish

is an acceptable cipher string setting ... and "complete-rubbish" is ignored.

**Comment by bernd-edlinger** [comment]
Yes,

but unfortunately "kECDHe" is not like "complete-rubbish", at least it needs to be documented
that kECDHe and all the other variants mentioned above do no longer work as they used to,
and are ignored when not used as the first word in a cipher list.

However, even when these keywords are no longer recognized, it might be a better option to
make an exception from the "ignore anything it doesn't know about" policy at least?

**Comment by bernd-edlinger** [comment]
FWIW I could make a PR and update the docs mentioning that these ciphers are no longer
recognized and remove all remaining uses of these (in the test suite at `test/recipes/80-test_ssl_old.t`)
but there is also `include/openssl/ssl.h:# define SSL_TXT_kECDHe          "kECDHe"`
shouldn't these defines be removed as well?

**Comment by kaduk** [comment]
We cannot remove any symbols from the public headers until the next major release (1.2).

**Comment by bernd-edlinger** [comment]
or change it to something working?
`#define SSL_TXT_kECDHe "kECDHE"`
or make this `kECDHe` just work?

**Comment by kaduk** [comment]
Changing it to something working is consistent with the API stability policy, I think ("fixing a bug").

**Comment by davidben** [comment]
kECDHe and kECDHE are very different. kECDHE refers to the widely-deployed ECDHE ciphers where the server sends a fresh ECDHE key and signs with its signing key. kECDHe refers to ECDH_ECDSA ciphers where the server has an *ECDH* leaf certificate containing a *static* ECDH key. The issuing certificate is then ECDSA.

**Comment by bernd-edlinger** [comment]
Thanks @davidben,
is there an exact repacement of `kECDHe` ?
`ECDH_ECDSA` is not working in the cipher command....

**Comment by bernd-edlinger** [comment]
Hmm, have these ECDH_ECDSA ciphers just all be removed in 1.1.0 ?
if that is the case then ignoring anything like `kECDHe` would be the right thing to do,
and keeping the define would not cause any harm?

**Comment by davidben** [comment]
Yes, they've been removed. They're a mess in the state machine, lack forward secrecy, and are not actually used by anyone.

**Comment by bernd-edlinger** [comment]
Aaah, I see.
So what remains is just, that there are simply no more ciphers in the following classes:
```
aECDH
kECDH
kECDHe
kECDHr
```
all others like `kEECDH` still work.
So, having a comment at these defines that these ciphers have been removed
might be sufficient?

**Comment by richsalz** [comment]
There are a couple of parts to this.  First is that the ```_TXT_``` defines have to stay around for now.  Sadly.  Second is that the define's should not be used in our source IMO.  Because then we get things out of sync and end up with issues like this one.

I think the TXT defines should be moved to their own header file, which could then be include'd now and removed later.  (Just like the error codes are now in a separate file)

**Comment by bernd-edlinger** [comment]
What do you think about PR #5023 ?
I found a few more no longer avaliable ciphers,
like "EXP", "aDH", "kDH", "kDHd", and "kDHr" (@kaduk note the oxford comma :-)
Is adding a comment to the define clear enough?

**Comment by richsalz** [comment]
i like it :)  thanks for looking into this.

**Comment by bernd-edlinger** [comment]
Fixed.
