### ISSUE TITLE
openssl req: Default to only allowing one instance of an extension

### ISSUE THREAD

**Issue by sleevi** [openssl/openssl#5037]
https://github.com/openssl/openssl/pull/4986 added the ability to specify extensions via the command-line, which is a fantastic addition and a great improvement. However, it comes with a certain footgun risk, in that the following command-lines are semantically different:

`openssl req -new -extension 'subjectAltName = DNS:dom.ain, DNS:oth.er'`
vs
```
openssl req -new -extension 'subjectAltName = DNS:dom.ain' \
                                   -extension 'subjectAltName = DNS:oth.er'
```

The former produces a valid (RFC 5280-sense) certificate with a SAN with multiple dNSName certificates, while the latter produces an invalid (RFC 5280-sense) certificate with multiple SAN extensions, each with a single dNSName.

The relevant text from RFC 5280 is https://tools.ietf.org/html/rfc5280#section-4.2, namely
> A certificate MUST NOT include more than one instance of a particular extension.

I believe the root cause of this is https://github.com/openssl/openssl/blob/bfa470a4f64313651a35571883e235d3335054eb/apps/req.c#L664 , namely, the 0 for the `flags` parameter of `X509V3_set_ctx`. If `flags` was set to `X509V3_CTX_REPLACE`, then https://github.com/openssl/openssl/blob/a1df06b36347a31c17d09e6ca3e1464bdf7eb4d5/crypto/x509v3/v3_conf.c#L314 would remove the first SAN and only add the second SAN.

Given that the motivation raised on https://github.com/openssl/openssl/issues/3311 was for better browser-interoperability, I thought I'd raise it as a potential issue, since the potential misuse/confusion around the API (and the man page's slight ambiguity in https://github.com/openssl/openssl/commit/bfa470a4f64313651a35571883e235d3335054eb#diff-53273ca131c2cc2dc8bbab2e15754b16R129 that it'd be an invalid cert) will potentially result in users adding multiple SAN extensions, and then finding their certificates are rejected as invalid.

Possible solutions:
* Just set the X509V3_CTX_REPLACE, which will silently use the last extension
* Add additional logic to X509V3_EXT_add_nconf_sk to warn/error on multiple extensions being present (rather than just replace), and then use that as part of the config testing/parsing

It's unclear when there'd be a valid case for multiple extensions, even in the non-5280 compliance case, given X.509, but if it is, having it be opt-in might be a better default.

**Comment by richsalz** [comment]
I agree, it should be opt-in or not allowed.  Thanks for digging into this!

**Comment by levitte** [comment]
Thanks for the report.  I'm ready to fix, but I'm going back between soft (using X509V3_CTX_REPLACE) and hard (X509V3_CTX_NO_DUPLICATES, which is to be defined then)...  in the end, what would you (anyone) think is the better way?

**Comment by sleevi** [comment]
I understand the debate - it's the same one I've been having. I think I've settled on NO_DUPLICATES being more desirable than _REPLACE, because it provides a developer early and actionable feedback. The behaviour of _REPLACE would mean that they wouldn't surface an error (perhaps just a warning, or just silent replacing as is), but the cert wouldn't match their expectations, and so if/when they tried to deploy, it Just Wouldn't Work.

In the case of a X509_REQ being generated (rather than an X509), it may be that their generated request ends up rejected by the CA, but after they've done additional work (such as payment or validation) - that is, relying on their issuing CA to say "This is a bad request".

So fail early, fail often, fail hard :)

**Comment by levitte** [comment]
Thanks for the input, sounds reasonable.  Pr coming up soon.

**Comment by kaduk** [comment]
(I agree with sleevi -- using _REPLACE invites silent failures for consumers.)

**Comment by levitte** [comment]
Errr, btw @sleevi, did you actually try that "faulty" command?  I just tried this, from a fresh master

```
: ; ./util/shlib_wrap.sh apps/openssl req -new -addext 'subjectAltName = DNS:dom.ain' -addext 'subjectAltName = DNS:oth.er'
Generating a 2048 bit RSA private key
...+++
.......+++
writing new private key to 'privkey.pem'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
-----BEGIN CERTIFICATE REQUEST-----
MIICrjCCAZYCAQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUx
ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAMhLMXlBRUqPHAPVBZZo3eQnTvhXNlKhs5Ob6vZf
f4OqrOx0bX2ptFKXQ53FV9jxPRtZe+bMnWmIcfcliBX3zMdwNI9EZ7OI+XcFxffQ
q51OnSqwyIdRjSKiTH28C0QQRf3fCalCdezchSr260f4Hb47fcgj9WlXAPP/GjJ+
zZEY0TWBgAHESf+83CEt5GYyzyK6FIK9OHhUrDjz/XsR28xz77mTKLfgLZspzwJV
u2IgL5+yd5l3gAjTroOcSGQsV2c3/wRQfOYFaegASysjgc6OQ6y0xACalACf8u8b
3s8exdUpOyl25bu4+3lxmX/c79S6wWvOMAOhSoOyb4LWTpECAwEAAaAkMCIGCSqG
SIb3DQEJDjEVMBMwEQYDVR0RBAowCIIGb3RoLmVyMA0GCSqGSIb3DQEBCwUAA4IB
AQBQygfI5ob4eU/LTsqgBEDtIOnNvs5W/7nMzTa5YoGp8ZFYBe3nHJ3TMgWGmeJH
Pv/QjzKgO9hjbFcQh3m6vw7+/FWcku8t1m2RkTqGM1vPPbqzWj2GDcov7wfJsqV3
nFbP8fbNoPr5OKtUO8KJNqJHG6+VXAaRQPTgxIfYyN3lAbOj74c+32vtMhFZqNfg
DMilOxzT/MP+h47l2opeWALELOSVizclxvYlZOuO255O0JGa5IRPDDeWWntY6O/j
kQmdudBtnQF6yhMNy/nUo79e2RBjE8ne0usXwX0jldm1N9qw69PbE9BqqwdhyeCh
sAtWGgC98KTzbP3hWPTB2+bZ
-----END CERTIFICATE REQUEST-----
: ; openssl req -text -noout
-----BEGIN CERTIFICATE REQUEST-----
MIICrjCCAZYCAQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUx
ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAMhLMXlBRUqPHAPVBZZo3eQnTvhXNlKhs5Ob6vZf
f4OqrOx0bX2ptFKXQ53FV9jxPRtZe+bMnWmIcfcliBX3zMdwNI9EZ7OI+XcFxffQ
q51OnSqwyIdRjSKiTH28C0QQRf3fCalCdezchSr260f4Hb47fcgj9WlXAPP/GjJ+
zZEY0TWBgAHESf+83CEt5GYyzyK6FIK9OHhUrDjz/XsR28xz77mTKLfgLZspzwJV
u2IgL5+yd5l3gAjTroOcSGQsV2c3/wRQfOYFaegASysjgc6OQ6y0xACalACf8u8b
3s8exdUpOyl25bu4+3lxmX/c79S6wWvOMAOhSoOyb4LWTpECAwEAAaAkMCIGCSqG
SIb3DQEJDjEVMBMwEQYDVR0RBAowCIIGb3RoLmVyMA0GCSqGSIb3DQEBCwUAA4IB
AQBQygfI5ob4eU/LTsqgBEDtIOnNvs5W/7nMzTa5YoGp8ZFYBe3nHJ3TMgWGmeJH
Pv/QjzKgO9hjbFcQh3m6vw7+/FWcku8t1m2RkTqGM1vPPbqzWj2GDcov7wfJsqV3
nFbP8fbNoPr5OKtUO8KJNqJHG6+VXAaRQPTgxIfYyN3lAbOj74c+32vtMhFZqNfg
DMilOxzT/MP+h47l2opeWALELOSVizclxvYlZOuO255O0JGa5IRPDDeWWntY6O/j
kQmdudBtnQF6yhMNy/nUo79e2RBjE8ne0usXwX0jldm1N9qw69PbE9BqqwdhyeCh
sAtWGgC98KTzbP3hWPTB2+bZ
-----END CERTIFICATE REQUEST-----
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c8:4b:31:79:41:45:4a:8f:1c:03:d5:05:96:68:
                    dd:e4:27:4e:f8:57:36:52:a1:b3:93:9b:ea:f6:5f:
                    7f:83:aa:ac:ec:74:6d:7d:a9:b4:52:97:43:9d:c5:
                    57:d8:f1:3d:1b:59:7b:e6:cc:9d:69:88:71:f7:25:
                    88:15:f7:cc:c7:70:34:8f:44:67:b3:88:f9:77:05:
                    c5:f7:d0:ab:9d:4e:9d:2a:b0:c8:87:51:8d:22:a2:
                    4c:7d:bc:0b:44:10:45:fd:df:09:a9:42:75:ec:dc:
                    85:2a:f6:eb:47:f8:1d:be:3b:7d:c8:23:f5:69:57:
                    00:f3:ff:1a:32:7e:cd:91:18:d1:35:81:80:01:c4:
                    49:ff:bc:dc:21:2d:e4:66:32:cf:22:ba:14:82:bd:
                    38:78:54:ac:38:f3:fd:7b:11:db:cc:73:ef:b9:93:
                    28:b7:e0:2d:9b:29:cf:02:55:bb:62:20:2f:9f:b2:
                    77:99:77:80:08:d3:ae:83:9c:48:64:2c:57:67:37:
                    ff:04:50:7c:e6:05:69:e8:00:4b:2b:23:81:ce:8e:
                    43:ac:b4:c4:00:9a:94:00:9f:f2:ef:1b:de:cf:1e:
                    c5:d5:29:3b:29:76:e5:bb:b8:fb:79:71:99:7f:dc:
                    ef:d4:ba:c1:6b:ce:30:03:a1:4a:83:b2:6f:82:d6:
                    4e:91
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:oth.er
    Signature Algorithm: sha256WithRSAEncryption
         50:ca:07:c8:e6:86:f8:79:4f:cb:4e:ca:a0:04:40:ed:20:e9:
         cd:be:ce:56:ff:b9:cc:cd:36:b9:62:81:a9:f1:91:58:05:ed:
         e7:1c:9d:d3:32:05:86:99:e2:47:3e:ff:d0:8f:32:a0:3b:d8:
         63:6c:57:10:87:79:ba:bf:0e:fe:fc:55:9c:92:ef:2d:d6:6d:
         91:91:3a:86:33:5b:cf:3d:ba:b3:5a:3d:86:0d:ca:2f:ef:07:
         c9:b2:a5:77:9c:56:cf:f1:f6:cd:a0:fa:f9:38:ab:54:3b:c2:
         89:36:a2:47:1b:af:95:5c:06:91:40:f4:e0:c4:87:d8:c8:dd:
         e5:01:b3:a3:ef:87:3e:df:6b:ed:32:11:59:a8:d7:e0:0c:c8:
         a5:3b:1c:d3:fc:c3:fe:87:8e:e5:da:8a:5e:58:02:c4:2c:e4:
         95:8b:37:25:c6:f6:25:64:eb:8e:db:9e:4e:d0:91:9a:e4:84:
         4f:0c:37:96:5a:7b:58:e8:ef:e3:91:09:9d:b9:d0:6d:9d:01:
         7a:ca:13:0d:cb:f9:d4:a3:bf:5e:d9:10:63:13:c9:de:d2:eb:
         17:c1:7d:23:95:d9:b5:37:da:b0:eb:d3:db:13:d0:6a:ab:07:
         61:c9:e0:a1:b0:0b:56:1a:00:bd:f0:a4:f3:6c:fd:e1:58:f4:
         c1:db:e6:d9
```

Note how there is only *one* SAN extension, but with the last value from the command line.

Thing is that all the added extension get buffered into a mass of text, making up an in memory "file".  In this case, it would become exactly this:

```
subjectAltName = DNS:dom.ain
subjectAltName = DNS:oth.er
```

and it seems that the nconf reader already the replacing thing, at least withing the same file.  So it seems that the fix needs to be something more than just the call of `X509V3_set_ctx`, and to figure out what's needed, I need to know a bit more about your conditions...  is there a subjectAltName in the openssl.cnf that the command used, for example?

**Comment by sleevi** [comment]
You're right - the nconf de-duplication (in https://github.com/openssl/openssl/blob/26a7d938c9bf932a55cb5e4e02abb48fe395c5cd/crypto/conf/conf_api.c#L59 ) handles removing duplicate values from the same section, while the use of separate CONFs ( for https://github.com/openssl/openssl/blob/bfa470a4f64313651a35571883e235d3335054eb/apps/req.c#L668 and https://github.com/openssl/openssl/blob/bfa470a4f64313651a35571883e235d3335054eb/apps/req.c#L675 ) result in the duplicate extensions if both a config and the command-line are set, since they use separate conf->data structures.

**Comment by mattcaswell** [comment]
Its not clear to me what needs to happen with this to push it forward? Ping @levitte, @sleevi.

**Comment by richsalz** [comment]
ping @levitte

**Comment by richsalz** [comment]
I think flags specified on the command-line should override config files as that's common behavior for all sorts of other things. So all we need to do is scan the -addext flags and error out if there's a duplicate.

**Comment by richsalz** [comment]
And #6636 was merged.  So for now you can't add repeated extensions which is okay (IMO)
