### ISSUE TITLE
Provide ability to set TLS settings system-wide

### ISSUE THREAD

**Issue by nmav** [openssl/openssl#5041]
When shipping openssl on an operating system it is often desirable to provide system-wide default settings for all applications using openssl. That is run-time options such as, disable old protocols and only allow TLS1.2 (see [0]), disable MD5 as a signing algorithm, set acceptable curves, limits for DH and RSA keys, etc. OpenSSL provides a system-wide configuration file (openssl.cnf), but no settings related to the options above are applied on TLS sessions by default.

[0]. Examples of operating systems which needed to do something like that:
https://lists.debian.org/debian-devel-announce/2017/08/msg00004.html
https://fedoraproject.org/wiki/Changes/StrongCryptoSettings

Relates to #4962

**Comment by richsalz** [comment]
I think this is something we should do.

**Comment by nmav** [comment]
This is addressed by #4848
