### ISSUE TITLE
build error (undeclared identifiers)

### ISSUE THREAD

**Issue by moominka** [openssl/openssl#5051]
Hello

I'm trying to modify my build of nginx 1.13.8, built against OpenSSL 1.1.1-dev, (draft 18) on OSX 10.10.5, but I get this when adding the nginx-ct module to the configure line. 

Are you able to cast any light on the below?

All is well until

-o objs/addon/nginx-ct/ngx_ssl_ct_module.o \
		~/src/nginx-ct/ngx_ssl_ct_module.c
~/src/nginx-ct/ngx_ssl_ct_module.c:164:19: error: use of undeclared identifier 'SSL_EXT_CLIENT_HELLO'
    int context = SSL_EXT_CLIENT_HELLO
                  ^
~/src/nginx-ct/ngx_ssl_ct_module.c:165:19: error: use of undeclared identifier 'SSL_EXT_TLS1_2_SERVER_HELLO'
                | SSL_EXT_TLS1_2_SERVER_HELLO
                  ^
~/src/nginx-ct/ngx_ssl_ct_module.c:166:19: error: use of undeclared identifier 'SSL_EXT_TLS1_3_CERTIFICATE'
                | SSL_EXT_TLS1_3_CERTIFICATE;
                  ^
~/src/nginx-ct/ngx_ssl_ct_module.c:167:9: error: implicit declaration of function 'SSL_CTX_add_custom_ext' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    if (SSL_CTX_add_custom_ext(ssl_ctx, NGX_SSL_CT_EXT, context,
        ^
~/src/nginx-ct/ngx_ssl_ct_module.c:192:20: error: use of undeclared identifier 'SSL_EXT_TLS1_3_CERTIFICATE'
    if (context == SSL_EXT_TLS1_3_CERTIFICATE && chainidx != 0) {
                   ^
5 errors generated.
make[1]: *** [objs/addon/nginx-ct/ngx_ssl_ct_module.o] Error 1

**Comment by levitte** [comment]
This is a question best asked on openssl-users@openssl.org.  See https://www.openssl.org/community/mailinglists.html for mailing list info.
