### ISSUE TITLE
get rid of `demo/` directory

### ISSUE THREAD

**Issue by azet** [openssl/openssl#5053]
Hi,

As stated in the README: these demos are outdated and some won't even work with historic versions of OpenSSL. Still; developers might make the mistake and stumble upon these and use/reuse parts when searching GitHub, Google et cetera. This might be potentially dangerous and it just adds unnecessary LoC to the OpenSSL project. Maybe we should get rid of them?

Thanks,
Aaron

**Comment by levitte** [comment]
That, or we could make sure they build and run correctly...  Add a 'demo' Makefile target?  I think loosely we talked about doing such a thing quite some time ago.

**Comment by mattcaswell** [comment]
Yeah - if we have demos they should build. So we either build them every time (or at least every time in travis/appveyor) or ditch them IMO.

**Comment by paulidale** [comment]
I think they build and run.  One of the people here got that much going a few months back.
They could do with a cleanse and be checked for current best practice (code health Tuesday?).

A Makefile target sense.

**Comment by Croydon** [comment]
Maybe create a new demo repository to keep it more clean?

**Comment by mattcaswell** [comment]
Probably this kind of clean up is too late for 1.1.1. Moving to the post 1.1.1 milestone.

**Comment by t8m** [comment]
There are some updates to the demos being done. I do not think we want to completely remove them. Closing.
