### ISSUE TITLE
-lcrypto option not working for RISCV architecture

### ISSUE THREAD

**Issue by nandeesha-veeranna** [openssl/openssl#5056]
I am trying to run the OpenSSL benchmarks for my experimentation. I am trying to compile using RISV gcc compiler with the command  riscv64-unknown-elf-gcc  sha256.S -o sha.riscv -lcrypto. It throws an error -can't find -lcrypto. Initially, the error was there for both gcc and riscvgcc compilation. Later when I have installed the libssl-dev, it worked for normal gcc but in RISCVgcc the problem still persists. Please help me to resolve the issue.

**Comment by richsalz** [comment]
Look at the riscv64 compiler documentation and find where it wants libraries installed; cross-compiling is special and won't use the system locations.  Or explicitly put a path to the library as in /home/user/test/openssl/libcrypto.a or whatever.
