### ISSUE TITLE
deadlock between ssl23_accept () and  ssl23_connect ()

### ISSUE THREAD

**Issue by obisluo** [openssl/openssl#5062]
Deadlock has happened intermittently.
The stack on the client side:
 #0  0x00007fc8ebc70aab in read () from /lib64/libpthread.so.0
#1  0x00007fc8d8ba4502 in sock_read () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
#2  0x00007fc8d8ba2b71 in BIO_read () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
#3  0x00007fc8d8b6d99f in ssl23_read_bytes () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
#4  0x00007fc8d8b6d2bf in ssl23_connect () from /opt/techno/Middleware/bin/libnqutilitysslall64.so

On the server side:
*#0  0x00007f5dbf86daab in read () from /lib64/libpthread.so.0
*#1  0x00007f5dbe394502 in sock_read () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
*#2  0x00007f5dbe392b71 in BIO_read () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
*#3  0x00007f5dbe357f38 in ssl3_read_n () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
*#4  0x00007f5dbe358fed in ssl3_read_bytes () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
*#5  0x00007f5dbe35a5dd in ssl3_get_message () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
*#6  0x00007f5dbe34a52a in ssl3_check_client_hello () from /opt/techno/Middlewar
e/bin/libnqutilitysslall64.so
*#7  0x00007f5dbe34f108 in ssl3_accept () from /opt/techno/Middleware/bin/libnqutilitysslall64.so
*#8  0x00007f5dbe35c121 in ssl23_get_client_hello () from /opt/techno/Middleware
/bin/libnqutilitysslall64.so
*#9  0x00007f5dbe35c943 in ssl23_accept () from /opt/techno/Middleware/bin/libnqutilitysslall64.so

It is on 1.0.1s.

**Comment by richsalz** [comment]
1.0.1 is no longer supported.  Can you reproduce the problem with a current release?  If not, we'll have to  close this issue.

**Comment by mattcaswell** [comment]
No response from OP. Closing.
