### ISSUE TITLE
Error in BN_get_word(3) man page

### ISSUE THREAD

**Issue by schodet** [openssl/openssl#5066]
In the return value documentation:

> BN_get_word() returns the value a, and 0xffffffffL if a cannot be represented as an unsigned long.

Actually, `BN_get_word` returns `BN_MASK2` (not part of public interface) in this case, which is 0xffffffffffffffffL on 64 bit platforms.

See: https://github.com/openssl/openssl/blob/master/doc/man3/BN_zero.pod

**Comment by richsalz** [comment]
Do you think if we changed it to say "all bits set" that would be accurate?

**Comment by schodet** [comment]
I agree.

It would be nice to have access to `BN_MASK2` too, to simplify user code. I think that this function will be more popular in the following years because of the `BIGNUM` struct fields are private now.

Also I realized that return types does not match code, it's written `unsigned long`, but the code returns `BN_ULONG` which can be `unsigned long long` for example. I suppose this also affects other functions working with words.

**Comment by paulidale** [comment]
Testing for all bits set is `~result == 0`.  That doesn't seem too complex.
I almost suggested `result + 1 == 0` but that's slightly confusing :)

I agree about the return type.

**Comment by richsalz** [comment]
But the return type error should only matter on places where "long" != "long long" right?
It still seems like something we can't change for now.

**Comment by schodet** [comment]
@richsalz I do not get what you mean. The issue is about documentation, not about code.

**Comment by richsalz** [comment]
Please take a look at #5141 and see if it's better.

**Comment by schodet** [comment]
There is also: "BN_get_word() returns B<a>, if it can be represented as an unsigned
long.".

**Comment by richsalz** [comment]
Thanks, fixed that as well and updated commit pushed.  @t-j-h please reconfirm.

**Comment by schodet** [comment]
There is also a problem with `BN_set_word` which also takes a `BN_ULONG`. I looked for other functions in other man pages but the other ones are good.

**Comment by richsalz** [comment]
Fixed on 1.0.2 1.1.0 and master.  Thanks for the report!

**Comment by schodet** [comment]
Thanks for the fix!
