### ISSUE TITLE
Windows build: version resource is missing

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#5075]
The version resource is missing in both dlls (libssl-1_1.dll and libcrypto-1_1.dll).

**Comment by levitte** [comment]
What version are we talking about?

**Comment by matbech** [comment]
It's the master branch.

**Comment by levitte** [comment]
Ah, right you are!  Fix coming up, watch this space

**Comment by levitte** [comment]
Please have a look at #5077.  If you can confirm that it does indeed fix your issue, that would be great!

**Comment by matbech** [comment]
I can confirm that it does fix the issue. Thank you.
