### ISSUE TITLE
Overwrite of standard asn1 methods no longer possible

### ISSUE THREAD

**Issue by fschueller-ifd** [openssl/openssl#5086]
With commit d85722d31ac9ff0dc54c06cdc8d125acf56ca27a EVP_PKEY_asn1_add0() checks if a for already registered ameth for the nid. The used function pkey_asn1_find() checks also the standard-meths.

With this, it is no longer possible to replace openssl-default-meths with modificated ones process globally.

**Comment by mattcaswell** [comment]
@levitte - thoughts?

**Comment by levitte** [comment]
The trouble is that `EVP_PKEY_asn1_find` will prioritize application added methods over standard ones, while `EVP_PKEY_asn1_find_str` goes the other way around.  So depending on how you look them up, you will get different results.  I took that as an indication that overloading standard asn1 methods wasn't really supported, hence d85722d...

I'm open to rethinking this and changing `EVP_PKEY_asn1_find_str` to index from end to start when looking for the asn1 method matching the string.
