### ISSUE TITLE
"Unable to set local cert chain file" on Debian libssl-dev in php Docker images

### ISSUE THREAD

**Issue by bscheshirwork** [openssl/openssl#5098]
I have error with client certificate on specific build of `libssl-dev` (`FROM debian:stretch-slim`)
https://github.com/docker-library/php/blob/f4baf0edbc4e05e241938c68bcc7c9635707583d/7.2/stretch/fpm/Dockerfile#L109
https://packages.debian.org/stretch/libssl-dev
I got error
```sh
  [PHPUnit\Framework\Exception (2)]                                                                                                                                                                 
  file_get_contents(): Unable to set local cert chain file `/var/www/html/api/tests/_data/client01.crt'; Check that your cafile/capath settings include details of your certificate and its issuer  
```

in another build (FROM alpine:3.7) with use `libressl-dev` 
https://github.com/docker-library/php/blob/f4baf0edbc4e05e241938c68bcc7c9635707583d/7.2/alpine3.7/fpm/Dockerfile#L98
same code is work

or if I try to directly run `curl` command 
all is work

https://github.com/docker-library/php/issues/564

I search this
https://github.com/oerdnj/deb.sury.org/issues/661#issuecomment-323683681

**Comment by richsalz** [comment]
Does the pathname exist?  CURL is using its own certificate store, I think (does "all is work" mean "it all works"?)

I think this is a configuration error.

**Comment by bscheshirwork** [comment]
"it all works" yes. Sorry for my Engrish :cat:  

Pathname(s) exist and readable.

From alpine3.7 php build with all another 
same params/config
scripts (test script and codeception codecoverage) 
correctly work - paths and config is correct.

CURL run with this params (under debian php container, using same cert and same path. All cert is correct, fresh and active):
```sh
curl -v --cacert /var/www/html/api/tests/_data/ca.crt --key /var/www/html/api/tests/_data/client01.key --cert /var/www/html/api/tests/_data/client01.crt --url https://dev.api:8084/v1/feedback/create --request POST --data "name=tester&email=tester@gmail.com&subject=test&body=message body"
```

**Comment by richsalz** [comment]
Your English is better than my any-other-language. ;)

This looks like a PHP configuration issue, not OpenSSL.

**Comment by bscheshirwork** [comment]
So... I think this issue about `libssl-dev` who uses in 
```sh
	apt-get install -y --no-install-recommends \
		libargon2-0-dev \
		libcurl4-openssl-dev \
		libedit-dev \
		libsqlite3-dev \
		libssl-dev \
```

It wrong repo for this issue?
Sorry I am nube in linux make command - build `libssl-dev` for debian stretch package
https://packages.debian.org/stretch/libssl-dev
based on this repo source code 
or build from any other place?

**Comment by richsalz** [comment]
try asking on a PHP or debian forum.

**Comment by bscheshirwork** [comment]
Oh.. I can see in this README.md
```
OVERVIEW
 --------

 The OpenSSL toolkit includes:

 libssl (with platform specific naming):
     Provides the client and server-side implementations for SSLv3 and TLS.
```

> This looks like a PHP configuration issue, not OpenSSL.
You think `libssl` is not have a error?
Error happens with 
wrong `./configure` on `make` process?

**Comment by richsalz** [comment]
Right, I think libssl does not have an error.  I think perhaps the PHP/OpenSSL package is using a path that you do not know about.  Or something like that.  This is not an OpenSSL error.  CURL also uses openssl and you say it works correctly.

Whenever two packages are involved, it can be frustrating to make them work together properly.

**Comment by kaduk** [comment]
> build libssl-dev for debian stretch package
https://packages.debian.org/stretch/libssl-dev
based on this repo source code
or build from any other place?

Do you want ```apt-get source openssl```?

**Comment by mattcaswell** [comment]
Assumed not to be an OpenSSL error. Closing.

**Comment by bscheshirwork** [comment]
https://github.com/docker-library/php/issues/844#issuecomment-521953648
