### ISSUE TITLE
Should we publish our release tools?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#5125]
The "tools," such as they are, are mainly a couple of docs files and recipes to follow.  Is it useful to others?  I'm skepticl, but #3786 raised it.

**Comment by Croydon** [comment]
Is it a lot of work to keep them up to date when published? Is there a chance they contain critical data? 

If both answers are a clear no then I would go with an open-by-default approach and publish them.

**Comment by richsalz** [comment]
The bulk of it is two text files that are in our private doc repo.  Creating a new repo and pulling those two files out is a bit of work.  Hard to see the point of it.

**Comment by richsalz** [comment]
We put this into our tools repo, https://github.com/openssl/tools, in the release-tools sub directory.
