### ISSUE TITLE
openssl: /usr/local/ssl/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)

### ISSUE THREAD

**Issue by Dani778** [openssl/openssl#5129]
I have an issue with openssl 1.1.1-dev after install

This is error:
`openssl: /usr/local/ssl/libssl.so.1.1: version OPENSSL_1_1_1 not found (required by openssl)`
My system:
`[loginuser@lastfrag openssl]$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core
`
My openssl config:
`./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl         -Wl,-rpath,'$(LIBRPATH)'`

Additionaly i added libs to ld path ,  openssl-1.1.0g

**Comment by Dani778** [comment]
I repaired issue copying new libssl.so.1.1 to /usr/local/ssl/ but i have new error
`openssl version
Segmentation fault
`

**Comment by Dani778** [comment]
Issue closed , file was broken , i find new  and working. Topic to close

**Comment by levitte** [comment]
Cool. Thanks.
