### ISSUE TITLE
Tests fail to build if ssl-trace or unit-test are enabled

### ISSUE THREAD

**Issue by nickthetait** [openssl/openssl#5130]
I am able to successfully build/install/run many configurations of OpenSSL in a virtual machine. However these two configuration options failed for an as-yet-unknown reason. They may be unrelated issues, but I discovered them at the same time.

Platform: Ubuntu LTS 16.04

OpenSSL Version: 1.1.1-dev

Commit hash: 154d8c132fbe22a248f95e95ef21f1840451da62

# Enable SSL Trace
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' enable-ssl-trace && make test

Get the following output:
```
..... (many lines skipped)
apps/s_client.o: In function `s_client_main':
s_client.c:(.text+0x4298): undefined reference to `SSL_trace'
apps/s_server.o: In function `sv_body':
s_server.c:(.text+0x11d1): undefined reference to `SSL_trace'
apps/s_server.o: In function `www_body':
s_server.c:(.text+0x232b): undefined reference to `SSL_trace'
apps/s_server.o: In function `rev_body':
s_server.c:(.text+0x2970): undefined reference to `SSL_trace'
collect2: error: ld returned 1 exit status
Makefile:6443: recipe for target 'apps/openssl' failed
make[1]: *** [apps/openssl] Error 1
make[1]: Leaving directory '/home/crypto/SRC/openssl'
Makefile:166: recipe for target 'tests' failed
make: *** [tests] Error 2
```

# Enable Unit Test
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' enable-unit-test && make test

Get the following output:
```
..... (many lines skipped)
../test/recipes/99-test_fuzz.t ..................... ok     

Test Summary Report
-------------------
../test/recipes/01-test_symbol_presence.t        (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=140, Tests=1240, 239 wallclock secs ( 3.25 usr  0.36 sys + 60.70 cusr 15.25 csys = 79.56 CPU)
Result: FAIL
Makefile:168: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/crypto/SRC/openssl'
Makefile:166: recipe for target 'tests' failed
make: *** [tests] Error 2
```

**Comment by mattcaswell** [comment]
I have been unable to reproduce either failure. I used the same commit as you and the same command line. The only difference is I am on Ubuntu 17.10. My suspicion is that you were building with a non-clean source tree. Can you try again (ensuring to run "make clean" first)?

**Comment by bernd-edlinger** [comment]
Not sure if the` -rpath` linker option interferes with the `LD_LIBRARY_PATH` environment variable.
According `man ld` the `-rpath` directory is searched before `LD_LIBRARY_PATH`

The linker uses the following search paths to locate required
           shared libraries:

           1.  Any directories specified by -rpath-link options.

           2.  Any directories specified by -rpath options.  The difference
               between -rpath and -rpath-link is that directories specified by
               -rpath options are included in the executable and used at
               runtime, whereas the -rpath-link option is only effective at
               link time. Searching -rpath in this way is only supported by
               native linkers and cross linkers which have been configured
               with the --with-sysroot option.

           3.  On an ELF system, for native linkers, if the -rpath and
               -rpath-link options were not used, search the contents of the
               environment variable "LD_RUN_PATH".

           4.  On SunOS, if the -rpath option was not used, search any
               directories specified using -L options.

           5.  For a native linker, search the contents of the environment
               variable "LD_LIBRARY_PATH".

           6.  For a native ELF linker, the directories in "DT_RUNPATH" or
               "DT_RPATH" of a shared library are searched for shared
               libraries needed by it. The "DT_RPATH" entries are ignored if
               "DT_RUNPATH" entries exist.

           7.  The default directories, normally /lib and /usr/lib.

           8.  For a native linker on an ELF system, if the file
               /etc/ld.so.conf exists, the list of directories found in that
               file.

**Comment by levitte** [comment]
With `--enable-new-dtags`, `DT_RUNPATH` is set instead of `DT_RPATH`

**Comment by bernd-edlinger** [comment]
Hmm, I think I can reproduce this now:

```
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' && make test
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' enable-ssl-trace && make test
[....]
apps/s_client.o: In function `s_client_main':
s_client.c:(.text+0x4298): undefined reference to `SSL_trace'
apps/s_server.o: In function `sv_body':
s_server.c:(.text+0x1261): undefined reference to `SSL_trace'
apps/s_server.o: In function `www_body':
s_server.c:(.text+0x23ab): undefined reference to `SSL_trace'
apps/s_server.o: In function `rev_body':
s_server.c:(.text+0x29f0): undefined reference to `SSL_trace'
collect2: error: ld returned 1 exit status
Makefile:6446: recipe for target 'apps/openssl' failed
make[1]: *** [apps/openssl] Error 1
make[1]: Leaving directory '/home/ed/OPC/openssl'
Makefile:166: recipe for target 'tests' failed
make: *** [tests] Error 2
```

you were supposed to make distclean before next ./config, right?

**Comment by nickthetait** [comment]
Thanks @mattcaswell. Running "make clean" between builds reliably fixes this problem. Would there be value in mentioning this in the install file or just the existence of this issue is enough?
