### ISSUE TITLE
openssl crashes with SSL_DEBUG enabled

### ISSUE THREAD

**Issue by Decave** [openssl/openssl#5138]
(1) prerequisites:
-OpenSSL top of tree (fa7435820ee9075fa542baf2577b77f5fd8f801d)
-Linux 4.13.0-26-generic

(2) error: Hits segfault when trying to create an OpenSSL client because of a bad fprintf debug statement.
: https://github.com/openssl/openssl/blob/master/ssl/statem/statem_clnt.c#L2284

(3)details
When SSL_DEBUG is enabled, the following line gets executed: https://github.com/openssl/openssl/blob/master/ssl/statem/statem_clnt.c#L2284

```
        const EVP_MD *md = NULL;
        unsigned char *tbs;
        size_t tbslen;
        int rv;

        /*
         * |pkt| now points to the beginning of the signature, so the difference
         * equals the length of the parameters.
         */
        if (!PACKET_get_sub_packet(&save_param_start, &params,
                                   PACKET_remaining(&save_param_start) -
                                   PACKET_remaining(pkt))) {
            SSLfatal(s, SSL_AD_DECODE_ERROR, SSL_F_TLS_PROCESS_KEY_EXCHANGE,
                     ERR_R_INTERNAL_ERROR);
            goto err;
        }

        if (SSL_USE_SIGALGS(s)) {
            unsigned int sigalg;

            if (!PACKET_get_net_2(pkt, &sigalg)) {
                SSLfatal(s, SSL_AD_DECODE_ERROR, SSL_F_TLS_PROCESS_KEY_EXCHANGE,
                         SSL_R_LENGTH_TOO_SHORT);
                goto err;
            }
            if (tls12_check_peer_sigalg(s, sigalg, pkey) <=0) {
                /* SSLfatal() already called */
                goto err;
            }
#ifdef SSL_DEBUG
            fprintf(stderr, "USING TLSv1.2 HASH %s\n", EVP_MD_name(md)); // <==== segfault
#endif
        } else if (!tls1_set_peer_legacy_sigalg(s, pkey)) {
            SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_PROCESS_KEY_EXCHANGE,
                     ERR_R_INTERNAL_ERROR);
            goto err;
        }

        if (!tls1_lookup_md(s->s3->tmp.peer_sigalg, &md)) { // <========== md set here
            SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_PROCESS_KEY_EXCHANGE,
                     ERR_R_INTERNAL_ERROR);
            goto err;
        }
```

The `md` hash is NULL, and is set to NULL at the top of the codeblock, and is never set before we print the debug message. It looks like this regression was introduced in commit f365a3e2e552e36f5c885953f5a361267f0d06c6:
```

-            md = ssl_md(s->s3->tmp.peer_sigalg->hash_idx);
 #ifdef SSL_DEBUG
             fprintf(stderr, "USING TLSv1.2 HASH %s\n", EVP_MD_name(md));
 #endif
-        } else if (EVP_PKEY_id(pkey) == EVP_PKEY_RSA) {
-            md = EVP_md5_sha1();
-        } else {
-            md = EVP_sha1();
+        } else if (!tls1_set_peer_legacy_sigalg(s, pkey)) {
+            al = SSL_AD_INTERNAL_ERROR;
+            goto err;
         }
 
+        md = ssl_md(s->s3->tmp.peer_sigalg->hash_idx);
+ 
```

Here are concrete steps to hit the segfault:
1. ./config -DOPENSSL_LINUX_TLS -DSSL_DEBUG no-asm -g3 -O0 -fno-omit-frame-pointer -fno-inline-functions
2. run make
3. Spin up test server: `sudo env LD_LIBRARY_PATH=#LD_LIBRARY_PATH:`pwd`/.. ./openssl s_server -tls1_2 -cipher ECDHE-RSA-AES128-GCM-SHA256`
4. Spin up test client: `sudo env LD_LIBRARY_PATH=#LD_LIBRARY_PATH:`pwd`/.. ./openssl s_client -tls1_2 -debug -connect 127.0.0.1:4433`

(4) proposal:
The obvious solution is to call the `fprintf` after we set `md` in `tls1_lookup_md`.

**Comment by richsalz** [comment]
Please see if PR #5140 fixes the problem.

**Comment by richsalz** [comment]
Fixed in master, thanks for the report!
