### ISSUE TITLE
Use AES256-CBC-SHA256 for default TLS session ticket key

### ISSUE THREAD

**Issue by Castaglia** [openssl/openssl#514]
Currently, by default OpenSSL uses `AES128-CBC-SHA256` for encrypting TLS session tickets, regardless of the actual ciphersuite negotiated for the SSL session.  Some of the current/popular ciphersuites negotiate longer keys, thus those sessions are protected by a weaker key (for the session ticket) than is desirable.  This is highlighted in the Wikipedia article on [TLS session tickets](https://en.wikipedia.org/wiki/Transport_Layer_Security#Session_tickets).

Unless there are other considerations, using `AES256-CBC-SHA256` by default would provide default TLS session ticket key that is twice as long.

**Comment by mattcaswell** [comment]
PR was merged.
