### ISSUE TITLE
SHLIB_EXT_SIMPLE broke SHLIB_EXT 

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#5143]
In "master" branch SHLIB_EXT was implemented to allow at compile time to replace SONAME version and version suffix in library file name  - mostly to avoid shared library version on android where libfoo.so.1.2.3 is not acceptable.

Now it seem to me SHLIB_EXT does not work properly: .../ld: error: cannot open ./libcrypto.so: Too many levels of symbolic links
...

Makefile is produced with following snipped:
	rm -f $target
	ln -s $target_full $target
Note that  if SHLIB_EXT=.so  is specified at build(make) time $target_full is same as $target.

This is expected even documented (see comment in unix-Makefile.tmpl before sub shlib): "... On some systems, they may therefore return the exact same."

With other words current build rules broke solution for issue #3902 .

**Comment by levitte** [comment]
Please test #5144

**Comment by petrovr** [comment]
Richard Levitte wrote:
> Please test #5144
>
Patch in #5144 resolves build issue.
