### ISSUE TITLE
Building 1.0.2n from source does not include -ldl stuff?

### ISSUE THREAD

**Issue by jjimenezg93** [openssl/openssl#5147]
Hello.

I'm trying to link a ported .so project to **OpenSSL** and **cURL**. I'm compiling both of them with **zlib** support and everything links (except for some _strdup and similar stuff, but this has nothing to do with openSSL).

The point is that **1.1.0 compiles** fine with that:

`$ LIBS="-lz -ldl" ./config -fPIC -static --debug zlib --with-zlib-include=<project_path>/zlib/zlib_release_64bit_static-linux/include --with-zlib-lib=<project_path>/zlib/zlib_release_64bit_static-linux/lib no-zlib-dynamic --prefix=<project_path>/openssl/openssl_debug_64bit_static-linux enable-ssl2 enable-ssl3 enable-ssl3-method no-shared no-threads`

But **1.0.2 does not** (I need 1.0.2 because Windows' version is already using that and we don't want to fill our source with OPENSSL_API_COMPAT stuff), I get `undefined reference... to 'dlopen'` (and all of its friends, `dlclose`, `dlsym`, etc.). It looks like it's not including `-ldl` stuff since executing this (in `openssl-1.0.2n/crypto/dso`):

`$ ls *.o | xargs nm -gC | grep dl`

shows:

`crypto/dso/dso_dlfcn.o:

                 U dladdr

                 U dlclose

                 U dlerror

                 U dlopen

                 U dlsym`

However, the `configure` output shows this:

`EX_LIBS       =-ldl -L<project_path>/zlib/zlib_release_64bit_static-linux/lib -lz`

When I run `$ make V=1` I can see it's calling **`gcc`** like this:

`gcc -I. -I.. -I../include -I<project_path>/zlib/zlib_release_64bit_static-linux/include -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -fPIC -static --debug -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o cryptlib.o cryptlib.c`

Isn't an `-ldl` missing here? It is expanding and linking to `zlib` but there's no sign of `ldl`.

I'm using **cURL-7.54.0** and **zlib-1.2.11**.

Thanks in advance.

**UPDATE**
---

Indeed, I tried again to run the same configure command on both versions (tried to add `LDFLAGS="-L$LIBDIR/lib -ldl` and also adding `-static` at the end of `LIBS=...` with no success). This is part of the output of **1.0.2n**:

`EX_LIBS       =-ldl -L<project_path>/src/zlib/zlib_release_64bit_static-linux/lib -lz`

**1.1.0g** however:

`EX_LIBS       =-L<project_path>/src/zlib/zlib_release_64bit_static-linux/lib -lz -ldl -static`

It definitely looks like `-ldl` is not in the right place, isn't it? What am I doing wrong or what's the workaround? Thanks.

**Comment by levitte** [comment]
A lot of this is about assumptions how OpenSSL's config work.  For the moment, environment variables like LIBS (which is non-standard in the GNU world, btw; the correct name is LDLIBS), LDFLAGS and so on are *not* supported by OpenSSL's config scripts.  Instead, you have to add those flags as config options, like this:

```
./config -fPIC -ldl ...
```

**Comment by levitte** [comment]
(you may have been lucky getting `-ldl` in `EX_LIBS` anyway, because the configuration data for the platform you're building on might know it's needed)

**Comment by jjimenezg93** [comment]
@levitte thanks for your answer. I've just tried this:

`./config -fPIC -ldl -static --debug zlib --with-zlib-include=<project_path>/zlib/zlib_release_64bit_static-linux/include --with-zlib-lib=<project_path>/zlib/zlib_release_64bit_static-linux/lib no-zlib-dynamic --prefix=<project_path>/openssl/openssl_debug_64bit_static-linux enable-ssl2 enable-ssl3 enable-ssl3-method no-shared no-threads`

and the `EX_LIBS` looks like this:

`EX_LIBS       =-ldl -ldl -L/home/jjimenez/l-code/BlackICE/pkcs11_wrapper/cs_pkcs11_R2/src/zlib/zlib_release_64bit_static-linux/lib -lz`

which seems even more weird for me. I tried to put `-ldl` after `zlib` and it's the same.

Thanks.

**Comment by jjimenezg93** [comment]
@levitte I'd like to know why you close this, btw. What you said did not fix the problem.

**Comment by levitte** [comment]
Well, OpenSSL's config obviously already knows `-ldl` is needed, but since you gave that explicitely as well, you get a duplicate.  Now, `libz` doesn't depend on `libdl`, so it doesn't matter if `-ldl` comes before or after `-lz`.

I closed this because it seems to me that it's primarly a usage issue, not a bug in OpenSSL.  This question should really go to `openssl-users@openssl.org` (see https://www.openssl.org/community/mailinglists.html for mailing list info).

**Comment by kaduk** [comment]
> gcc -I. -I.. -I../include -I<project_path>/zlib/zlib_release_64bit_static-linux/include -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -fPIC -static --debug -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -c -o cryptlib.o cryptlib.c

> Isn't an -ldl missing here? It is expanding and linking to zlib but there's no sign of ldl.

No.  This is compiling a C file to an ELF object file (```gcc -c```), and as such does not need to link in any dependent libraries.  ```-ldl``` would be needed (potentially) for actually linking an executable, e.g., a ```ld``` command line.
