### ISSUE TITLE
Bug on "enc" wiki page

### ISSUE THREAD

**Issue by Sulow89** [openssl/openssl#5148]
As I didn't get a reply when I reported this to `wiki-support[at]openssl.org` and `marquess[at]opensslfoundation.com` about a month ago, I decided to open an issue on Github.

There's a bug on the "Enc" wiki page: https://wiki.openssl.org/index.php/Enc

```
-pass arg
This specifies the password source. Possible values for arg are
pass:password or pass:filename, where password is your password and
filename file containing the password.
```

1. It's `file:filename` not `pass:filename`
  This is quite bad. If e.g. `pass:/path/to/file` is used as explained
  in the wiki article, the password used to encrypt / decrypt is
  literally `/path/to/file`, it is not read from file `/path/to/file`
2. It should say `and filename is the file` (missing `is the`)

**Comment by Sulow89** [comment]
`1.` applies to the other sections as well:

```
-k password, -kfile filename
Both option are used to specify a password or a file containing the
password which is used for key derivation. However they are deprecated.
You should use the -pass option instead. The equivalents are
-pass pass:password and -pass: pass:filename respectively. 
```

**Comment by mattcaswell** [comment]
Hmm. I think the whole man pages section on the wiki should be removed. They are out of date. The original idea was that people could make suggested modifications to the man pages directly on the wiki - which would then periodically get merged back into the main source tree. But, for various reasons, it never worked out like that.

**Comment by richsalz** [comment]
I am in favor of that.  I'll do a PR to fix the manpage. Who can remvoe the wiki manpages?

**Comment by mattcaswell** [comment]
The man page is already fixed. It's just that the wiki doesn't have the up to date version of it.

> Who can remvoe the wiki manpages?

I probably can in theory...if I can figure out how.

**Comment by richsalz** [comment]
Perhaps this will help: https://www.mediawiki.org/wiki/Extension:DeleteBatch

**Comment by iamamoose** [comment]
(It's not just the man pages, there's whole sections of the wiki that are several years out of date and have incorrect or outdated information).   When using search engines for things (i.e. "openssl list digests"), the man pages rank highly, so we could replace each page with just a link to https://www.openssl.org/docs/manpages.html

**Comment by iamamoose** [comment]
list of pages to delete (i'll just do this via the api tomorrow or Mon):

[media.txt](https://github.com/openssl/openssl/files/1793841/media.txt)

**Comment by mattcaswell** [comment]
In theory we regularly upload fresh versions of the man pages to the wiki. But I suspect that broke a long time ago and no one noticed. Better to ditch them anyway.

**Comment by iamamoose** [comment]
Agreed. Done. There might be a little cleanup of links needed over time (but so many wiki links are broken anyway).  I'll also go through and make sure we didn't get any edits from anyone to them we lost. 

In case we ever want to restore them we can just modify this quick script I used

[delpages.py.txt](https://github.com/openssl/openssl/files/1794176/delpages.py.txt)
