### ISSUE TITLE
As server, when we verify client'certs by using local trusted certs, why root cert is needed?

### ISSUE THREAD

**Issue by mrpre** [openssl/openssl#516]
In my opinion, if  a trusted chain is like this: Root->Ca1->Ca2, and now  Ca2 is in our local cert library, then a cert singed by ca2 is received, we shold trust it.
Will it cause some security problem ?

**Comment by richsalz** [comment]
> In my opinion, if a trusted chain is like this: Root->Ca1->Ca2, and now Ca2 is in our local cert library, then a cert singed by ca2 is received, we shold trust it

That is the way thing should work.

**Comment by mrpre** [comment]
But i still can't understand the necessity root while verifying client certificate chain.
Has it been defined in RFC and will it cause security problem without root certificate ?

**Comment by richsalz** [comment]
I don’t understand the question.  The root certificate does not need to be verified; the cert is only used to hold the key.  The intermediate gets verified, and then you add it to the trust store, and there's no need to re-verify it against a root.  In essence the intermediate has now become a root.  As for what the RFC says, just read it.  Perhaps these questions are best asked on the TLS@IETF.ORG mailing list, not here.
