### ISSUE TITLE
Building issues on OSX 10.11.2

### ISSUE THREAD

**Issue by revmischa** [openssl/openssl#517]
* Does not build shared library by default
* Builds 32-bit not 64-bit by default
* Uses a prefix of /usr/local/ssl instead of /usr/local like any other UNIX package
* `--help` does not work on ./config
* ./config should be named ./configure like every other autotools package in existence
* ./Configure and ./GitConfigure returns an error: 
```
unknown option - static-engine
Imported platform darwin64-x86_64-cc
makefile.master:681: *** missing separator.  Stop.
```

**Comment by mouse07410** [comment]
My personal opinion:

> Does not build shared library by default

No big deal.

> Builds 32-bit not 64-bit by default

Strange, but again - no big deal.

> Uses a prefix of /usr/local/ssl instead of /usr/local like any other UNIX package

Well, that's what `--prefix=` and `--openssldir=` are for.

> `--help` does not work on ./config

I think this should be addressed/fixed.

> ./Configure and ./GitConfigure returns an error...

Likewise.

**Comment by richsalz** [comment]
believed all fixed now :)
