### ISSUE TITLE
CRL: Explicit tagging for onlyContainsUserCerts tolerated

### ISSUE THREAD

**Issue by flurbi** [openssl/openssl#5176]
OpenSSL 1.0.1f 6 Jan 2014

Is: Implicit and explicit tagging for onlyContainsUserCerts is parsed.
Should: Only implicit tagging should be parsed.

**Comment by flurbi** [comment]
I have corresponding test material, but I do not see how to upload it. Thus:

enduser.pem.crt
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIBADANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAt0cnVz
dGFuY2hvcjAeFw0wMTAxMDEwMDAwMDBaFw00OTAxMDEwMDAwMDBaMBIxEDAOBgNV
BAMMB2VuZHVzZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDWzWd
W1P4y0xPM0tS0CtlhzmXDfSkQrwn8xlIUDhT6QnRmi8M8QmPRIam+OB66zW/N/jl
q/ju7kQ2Ljn3XE+gIgCMXVJEgSlP5lPNv2lBh9CaisKwX2Tn8IOO7zn0xZqr9Qr3
xbDPPzLhTwGQfk3PUK80zhO7jnAu0a5MVCcT5q0XZhG5E/siRh/et97BRKjvppda
+O9bmuNaQ7AiwbTw0YamnXEUENG1F5XjvvtoChPywKnYXxMK0LRcq85dUC5X11E+
Y6QnvvlETncZXw4scWKErYKuSkYaZ9VKk1zIRMGDTEsy4rDluoKYKleiPdMV0R2c
eFLCic5e5hrhOosnAgMBAAGjgbYwgbMwDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMC
BaAwHQYDVR0OBBYEFKWqV88gyuCto1rT4DD7Oz/QJMMjMB8GA1UdIwQYMBaAFKgR
QVInERzJRma9DUgqqN7qQdQ3MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjA3BgNVHR8EMDAuMCygKqAohiZodHRwOi8vbG9jYWxob3N0OjEyMzQ1L3RydXN0
YW5jaG9yLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAo8lEUrolSN45N9tFMADLqZmO
G/foVI1F48sG+hvgBiaEih665xwrltO/wsFwv8JXowrpow98RSEzwzVE/mSG/5yr
HPSEajovuwwuzhsc4LF4wTlD+hznf7+Rt44Opqpaj4G034TF+e3xEwVkVsgVCcuj
+IhAm01u0rhgRUxF+mrpyL1WY5hj10x45/CEJwBMspMtn/PsTIzdjs9OeKsrmYZS
JPhK6PJpAcEr+kFm+bdBW71YxMF+fogaKLI04StkR98ZLebAk3zLA5as1B5JS5zN
U4gI278A3PGyHLLgW/C95+anHwpJMchwTeyW0MW6W5cp/dNXJzMDaxC3K57VKA==
-----END CERTIFICATE-----

trustanchor_explicit_only_user.pem 
-----BEGIN X509 CRL-----
MIIBsDCBmQIBATANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAt0cnVzdGFuY2hv
chcNMDIwMTAxMDAwMDAwWhcNNDgwNjAxMDAwMDAwWjAAoE0wSzAKBgNVHRQEAwIB
ADA9BgNVHRwBAf8EMzAxoCqgKIYmaHR0cDovL2xvY2FsaG9zdDoxMjM0NS90cnVz
dGFuY2hvci5jcmyhAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAJmJCmHwmKh8b3yH1
KkarlAzvleZk+R9G8RANqH7V2/Dncaa3xih0F+y+m2K17ES4uLSOCg7xw4PTkR4G
QYIvzild4A8/5LB5+PlDVL7yIZ177Ksr2mfBYYNn2RpcJq4m42Mdxhg+010J9xi3
UXm8hli3AoP10o/Bi+jgCFASqyZrALmB5Fqcc6XqRMRTZOe0MDq1yytmRqKLll1X
eMc9KDo1pLujQyd2p+6KVkkd36XAi7jTeitkm2lANhXyO0tKVmv+eb32aWcV6vBF
EHNGiJnqY0URorSR6rTu5+ajqf5Hl8UvWzObZVLGxFEkgRd46gmI1nDyxkhq6/8W
r/o12Q==
-----END X509 CRL-----
-----BEGIN CERTIFICATE-----
MIICyjCCAbKgAwIBAgIBADANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAt0cnVz
dGFuY2hvcjAgFw0wMDAxMDEwMDAwMDBaGA8yMDUwMDEwMTAwMDAwMFowFjEUMBIG
A1UEAwwLdHJ1c3RhbmNob3IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQC90A4lx8iOw2WePM0+yKu4aw2meR06LpQyG4VXRdHHtfSW9LhpHGzap47DAcwE
+cAis3l58qQAnJy3fIHJs71liC3pHwK8ilzKKJr73uqJ38iEDfxTCbq6aghemsjY
iBRa2PnSwFnKF/aXqTaT9hr1JtJ9FiOKyjYEcejnXOqIIMNyW7pIqxnDDjOUtvTR
bJNRnxHvGxouHzoL+L8X10MJQio3WeqImlHBIH2ehnm3Pty16JeFTgYgq6aErkd0
0s+a9kwW0IN4kgx1qnwM08JuvawLSdh97znSphWGA6lZ9jHWSf7LKzUQ56YORq5z
BRKLcU4Jc3I+iBzujAnpmrHXAgMBAAGjITAfMB0GA1UdDgQWBBSoEUFSJxEcyUZm
vQ1IKqje6kHUNzANBgkqhkiG9w0BAQsFAAOCAQEARIAoSVoxX+QQj1q5qyHmKI6U
uZhSVH/fJYhsiiWeul6AnAOnj71GbMln4FfC2q6A1+h/iS8BrpgtLZZ+yLjhvaXl
ubxYK1suZ0ldIUqxuKHSTDchb1OCxyAMtEzusSfHSaRICTw0tP3iFNoR0mxNB2YY
esAqEMkWP/eKWYhPYdxofpwobDPhBiB6vg7d21UFNlMDDZosHwiVAd1IdkCoI5wl
boKkhP93KxrUw8xEeeHvlsYZjM/fACYNCyZ6QgkUtu9Dvff3iGyMSMIqfa65wIyY
YAvzzIEuEOb7VCugJg1wC5n6gZsMxO5wfoCSw2Qh1bXXzqAOka9ij/KizIrB9g==
-----END CERTIFICATE-----

trustanchor_only_user.pem 
-----BEGIN X509 CRL-----
MIIBrjCBlwIBATANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAt0cnVzdGFuY2hv
chcNMDIwMTAxMDAwMDAwWhcNNDgwNjAxMDAwMDAwWjAAoEswSTAKBgNVHRQEAwIB
ADA7BgNVHRwBAf8EMTAvoCqgKIYmaHR0cDovL2xvY2FsaG9zdDoxMjM0NS90cnVz
dGFuY2hvci5jcmyBAf8wDQYJKoZIhvcNAQELBQADggEBACqNSXoRqlV2GrqfeVPj
HEc2l8IuOOqW66K7eBYEeKsiAtAYjNgXHjrGMCMjinEq0qQgCBHjcgpfbVrtbJCP
45Qygx20pfrKn5Zm0g05M6N+ZLHGVRRxTBzd3jZkIWu938DUlDdvNPNhGAtKukhD
dIYdxby6+tLoctsXJeL4ofhwtRNv8Q3Sr+LcsteGVOYvH857gFE2Z8e/fxf56OVT
zwypJdGJEmLdw+0nnMAJTbAghcLwTd8JLx/rrrc2Z5AMecT7z5vM5Osx1xdXGof3
IZapQIDXwgFiQJvKoKpG+4b26BbdalGJ/OctLzeMLxoxNJk3gajnEagbvD9IGW08
Ha4=
-----END X509 CRL-----
-----BEGIN CERTIFICATE-----
MIICyjCCAbKgAwIBAgIBADANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAt0cnVz
dGFuY2hvcjAgFw0wMDAxMDEwMDAwMDBaGA8yMDUwMDEwMTAwMDAwMFowFjEUMBIG
A1UEAwwLdHJ1c3RhbmNob3IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQC90A4lx8iOw2WePM0+yKu4aw2meR06LpQyG4VXRdHHtfSW9LhpHGzap47DAcwE
+cAis3l58qQAnJy3fIHJs71liC3pHwK8ilzKKJr73uqJ38iEDfxTCbq6aghemsjY
iBRa2PnSwFnKF/aXqTaT9hr1JtJ9FiOKyjYEcejnXOqIIMNyW7pIqxnDDjOUtvTR
bJNRnxHvGxouHzoL+L8X10MJQio3WeqImlHBIH2ehnm3Pty16JeFTgYgq6aErkd0
0s+a9kwW0IN4kgx1qnwM08JuvawLSdh97znSphWGA6lZ9jHWSf7LKzUQ56YORq5z
BRKLcU4Jc3I+iBzujAnpmrHXAgMBAAGjITAfMB0GA1UdDgQWBBSoEUFSJxEcyUZm
vQ1IKqje6kHUNzANBgkqhkiG9w0BAQsFAAOCAQEARIAoSVoxX+QQj1q5qyHmKI6U
uZhSVH/fJYhsiiWeul6AnAOnj71GbMln4FfC2q6A1+h/iS8BrpgtLZZ+yLjhvaXl
ubxYK1suZ0ldIUqxuKHSTDchb1OCxyAMtEzusSfHSaRICTw0tP3iFNoR0mxNB2YY
esAqEMkWP/eKWYhPYdxofpwobDPhBiB6vg7d21UFNlMDDZosHwiVAd1IdkCoI5wl
boKkhP93KxrUw8xEeeHvlsYZjM/fACYNCyZ6QgkUtu9Dvff3iGyMSMIqfa65wIyY
YAvzzIEuEOb7VCugJg1wC5n6gZsMxO5wfoCSw2Qh1bXXzqAOka9ij/KizIrB9g==
-----END CERTIFICATE-----

How to reproduce:

    # The parsing should fail, but it does not. 
    openssl verify \
       -verbose \
       -CAfile trustanchor_explicit_only_user.pem \
       -x509_strict \
       -crl_check \
       enduser.pem.crt

    # Correct onlyContainsUserCerts.
    openssl verify \
       -verbose \
       -CAfile trustanchor_only_user.pem \
       -x509_strict \
       -crl_check \
       enduser.pem.crt

**Comment by mattcaswell** [comment]
Why is this a problem?

**Comment by flurbi** [comment]
No problem so far. I just reported a violation of the strict standard compliance, which may be a hint to an inaccuracy, and thus may help the openssl developers to improve the quality. I do not know if this non-standard feature has been introduced on purpose; if yes, the motivation could be documented (compatibility with some software? which?); if no, the code in question should be reviewed and/or sanitized. In both cases, 'wontfix' is a possible resolution, with a proper justification.

**Comment by mattcaswell** [comment]
My guess is that this is done on purpose to work around broken encoders. I haven't tested it but I don't think this is restricted to this one field (I expect that this will happen anywhere there is implicit tagging). In any case changing that behaviour is probably inadvisable unless we can identify a real issue that causes a problem as a result. It is quite possible that there are "real" encodings out there produced by (broken) encoders that do this. If we "fix" it then suddenly we will not be able to read those encodings - which represents an interop break. If there is no harm being caused then we are better off not fixing it from an interop perspective. Of course we won't know if this really is an issue until we pushed such a change - but by then its a bit late.

My thinking at the moment is that this should be "won't fix".

**Comment by flurbi** [comment]
As long as the code supports both implicit and explicit on purpose (i.e. as long as the parser is still under strict control), I agree that 'wontfix' is acceptable, or even recommendable for compatibility. Also, I would not be surprised if some encoders use implicit/explicit improperly (here and/or at other places), because the ASN.1 rules governing implicit/explicit are unfortunately intricate.

**Comment by mattcaswell** [comment]
Ok - closing this as "won't fix".
