### ISSUE TITLE
openssl ciphers -V -s   (reports non-supported ciphers)

### ISSUE THREAD

**Issue by hubbardmeister** [openssl/openssl#518]
I have a goal as a Security company/officer/cloud provider to NOT TRUST my various applications on the ciphers they want to use. I am thus after having specific list of CIPHERS that the server will offer. This will be relatively static. I was there for compiling the openssl 1.1 code(zip from this week, lots of great updates by the way) and adding various no-rc2,no-rc4...  no-ssl3 . I got really confused on what was in and what was not based on the ciphers  -s  (supported ciphers)output i was seeing. There appears to be a minor bug i hacked in t1_lib.c where;

here is the simple change - gives me desired results;
int ssl_cipher_disabled(SSL *s, const SSL_CIPHER *c, int op)
{
#ifdef OPENSSL_NO_SSL3
/* we didn't want SSL3 - outa here)
 */
        s->s3->tmp.mask_ssl |= SSL_SSLV3;
#endif

 
My bigger ask - when the user has options for including/excluding ciphers in a help list output. Can this be the system wide defaults at that point, or is it  supposed to be already?

eg   I run this command - it sets my desired list
openssl ciphers  -V '!tlsv1_0:!tlsv1_1:HIGH:+TLSv1.2:-NULL:-SHA:-SHA128:-AES128:-DHE:-MD5'

i run openssl ciphers -s 

and i then get the list based on the set list from the prior request. I am now confident the Servers Ciphers are as i need and some application wont go selecting something less that optimal.

Thanks

**Comment by richsalz** [comment]
If you put "DEFAULT:" at the start of your cipher string, doesn't that give you what you want?

**Comment by hubbardmeister** [comment]
This does not help, still have ciphers listed that should not be. Like SSLV3.

**Comment by richsalz** [comment]
SSLV3 is not a cipher, it is a shorthand for "ciphers defined in SLSV3"  What you should really do is make a list of those you DO wnat to allow, and specify only that as a simple list.

**Comment by hubbardmeister** [comment]
Agreed , its a group of ciphers that we use a label for(Cipher Suites). I can quickly code this out, was looking for default behaviour to ensure that 'openssl  ciphers -s' really reflects  ONLY my desired ciphers.  It does not look like current behaviour allows this.

**Comment by richsalz** [comment]
Right.  So is this still an open issue?

**Comment by hubbardmeister** [comment]
The 'openssl ciphers -V -s'  appears to incorrectly report the Group of associated Ciphers related to the SSLV3 when it is specifically  compiled out with no-ssl3. This is what the #define i added earlier resolves. This should reflect the correct supported ciphers at that point. I believe this is still a problem and would help folks.

**Comment by richsalz** [comment]
Isn't that just reporting the version where the cipher first became available?
Can you perhaps cut/paste an output line and highlight the part you think wrong?
Sorry for being so dense here.

**Comment by hubbardmeister** [comment]
Hi,
Hope you can read these (from linux. added a .txt suffix to upload).
Nossl3butshows SSL3 - compiled with no-ssl3 and listing of command 'openssl  ciphers -s -V'
[nossl3butshows_sslv3.txt](https://github.com/openssl/openssl/files/75038/nossl3butshows_sslv3.txt)
Same output , but compiled with the #define , 
[withdefineinplace.txt](https://github.com/openssl/openssl/files/75040/withdefineinplace.txt)
My Makefile.
[Makefile.txt](https://github.com/openssl/openssl/files/75041/Makefile.txt)

Thanks

**Comment by richsalz** [comment]
Are you complaining about lines like this?
```
0xC0,0x14 - ECDHE-RSA-AES256-SHA    SSLv3 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
```
In particular, the "SSLv3" part of that line?  That is *when the cipher suite was first enabled*

**Comment by kroeckx** [comment]
Maybe it would be useful to list with protocols all support a
given cipher?

**Comment by hubbardmeister** [comment]
Hi Rich,
Yes. That is either in correct or confusing, not sure on the correct /
desired behavior....

Thanks

On Wed, Dec 30, 2015 at 2:37 PM, Rich Salz <notifications@github.com> wrote:

> Are you complaining about lines like this?
> ```
> 0xC0,0x14 - ECDHE-RSA-AES256-SHA SSLv3 Kx=ECDH Au=RSA Enc=AES(256)
> Mac=SHA1
> ```
> In particular, the "SSLv3" part of that line? That is *when the cipher
> suite was first enabled*
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openssl/openssl/issues/518#issuecomment-168087944>.
>



-- 
Phone 408-206-2208
Regards
Rob Hubbard

**Comment by richsalz** [comment]
The documentation was updated in commit baf245ec5fe969f115e0e556bf0da6bf7e960847
