### ISSUE TITLE
compile apps for Android

### ISSUE THREAD

**Issue by Rhtyme** [openssl/openssl#5183]
I am trying compile the sources in apps folder for Android in NDK r16 in order to send openssl commands directly from Android app (crypto and ssl modules are compiled fine). I have configured sources for Android environment. There are some functions that are not defined and throwing an error in `apps/openssl.c`:
```
lh_FUNCTION_insert ()
lh_FUNCTION_free ()
lh_FUNCTION_retrieve ()
lh_FUNCTION_new ()
```
When I compile for linux no errors are occured, but when I compile in ANDROID_NDK, compiler says :
```
./obj/local/arm64-v8a/objs-debug/gapps/apps/openssl.o: In function `prog_init':
/openssl/apps/openssl.c:703: undefined reference to `lh_FUNCTION_new'
/mnt/325E8FF25E8FACE3/02.01.2018/app/src/main/openssl/apps/openssl.c:708: undefined reference to `lh_FUNCTION_insert'
./obj/local/arm64-v8a/objs-debug/gapps/apps/openssl.o: In function `main':
/openssl/apps/openssl.c:173: undefined reference to `lh_FUNCTION_retrieve'
/openssl/apps/openssl.c:259: undefined reference to `lh_FUNCTION_free'
./obj/local/arm64-v8a/objs-debug/gapps/apps/openssl.o: In function `do_cmd':
/openssl/apps/openssl.c:466: undefined reference to `lh_FUNCTION_retrieve'
/openssl/apps/openssl.c:489: undefined reference to `lh_FUNCTION_retrieve'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/arm64-v8a/libgapps.so] Error 1

```
In older versions like 1.0.1u, above functions are defined in `openssl/safestack.h` file so I successfully compiled apps module for Android in that version.
Please tell me what to do in this situation, is there any script that generates `openssl/safestack.h` and other depended files suitable for Android environment?
I am using openssl-1.1.0g version compiling in Android NDK 16.1 version in Ubuntu.

**Comment by richsalz** [comment]
What was the config command line you used?  Are you sure you unpacjked and built the whole release?

**Comment by Rhtyme** [comment]
I downloaded openssl-1.1.0g from openssl.org site, and just configured it like this `./config` and did some changes.I don't remember exact changes I made, something like I copied opensslconf.h, progs.h  and other files into appropriate openssl folder. The source code is here [https://github.com/Rhtyme/openssl-android-terminal/tree/master/app/src/main/openssl_110g_succ](url).

**Comment by richsalz** [comment]
Sorry, but unless you can give us the exact steps to reproduce this we're going to have to close this issue.  You should not be copying header files around until after the build is done.
