### ISSUE TITLE
OpenSSL failed due to the fatal error U1073: don't know how to make 'clean'

### ISSUE THREAD

**Issue by shanshan0309** [openssl/openssl#5187]
Hi,

I tried to build openssl with VS2017 update 2 on Windows. It failed due to the fatal error U1073: don't know how to make 'clean'. This issue is can be reproduced from master revision [8c3bc594](https://github.com/openssl/openssl/commit/8c3bc594e0c74926bfefb84b8bae8a2fac82e465). Could you please help take a look at this issue? Thank you very much!

**Repro steps:**
1. git clone https://github.com/openssl/openssl D:\openssl\src
2. cd D:\openssl\src
3. perl Configure VC-WIN32
4. nmake clean

**Error information:**
[executing command] nmake clean 
Microsoft (R) Program Maintenance Utility Version 14.13.26111.0
Copyright (C) Microsoft Corporation.  All rights reserved.
**NMAKE : fatal error U1073: don't know how to make 'clean'**

**Comment by mattcaswell** [comment]
Did the "perl Configure" line run successfully? Did it create a makefile?

**Comment by shanshan0309** [comment]
@mattcaswell, thank you. Yes, the "perl Configure" line run successfully. The log file are as follows:
[executing command] perl Configure VC-WIN32 
Using implicit seed configuration
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
for VC-WIN32

It looks like you don't have either nmake.exe or dmake.exe on your PATH,
so you will not be able to execute the commands from a Makefile.  You can
install dmake.exe with the Perl Package Manager by running:

    ppm install dmake

Creating configdata.pm
Creating makefile
Undefined subroutine &Text::Template::GEN0::quotiry_l called at template line 178.
 in Configurations\windows-makefile.tmpl, fragment starting at line 176
NOTE: Starting with OpenSSL 1.1.1, 'Configure' doesn't display all the disabled
options or the "make variables" with their values.  Instead, you must use
'configdata.pm' as a script to get a display of the configuration data.  For
help, please do this:

        perl configdata.pm --help
[command took 7 seconds]

**Comment by levitte** [comment]
The `quotiry_l` issue is real, and it's being resolved with #5196.  Needs reconfirmation, then it'll be merged.

**Comment by levitte** [comment]
You should be able to get a fresher master now and get a working build.
