### ISSUE TITLE
Include DSTU4145 OIDs

### ISSUE THREAD

**Issue by gmile** [openssl/openssl#5194]
Would OpenSSL team consider including DSTU4145 OIDs into OpenSSL core?

DSTU4145 is important Ukrainian government crypto standard, which is required to be followed by every legal digital interaction in the country. If including the patches would be something OpenSSL core team is interested in, I'm more than willing to assist in submitting necessary patches via a pull request.

Right now there's an OpenSSL fork where an engine with DSTU4145 is being maintained – https://github.com/dstucrypt/openssl-dstu/tree/dstu-1_0_1h. I would very much like to see OIDs separated from the engine, and have OIDs merged into upstream OpenSSL. The patch with OIDs already exists, though it would have to be rebased & cleaned up before submitting in a form of PR: https://github.com/dstucrypt/openssl-dstu/commit/5ffb6d0018eb230acb38656a8ad1cee5da63b28f.

Having OIDs upstreamed would allow DSTU4145 engine maintainers to focus on the engine development and significantly simplify its support. A big issue right now is keeping up with CVE patches, for instance, where it is required that the DSTU4145 patches are constantly rebased.
Another pain is that due to the lack of native support of DSTU4145 in OpenSSL, developers (like myself) have to use local proprietary C libraries, code of which cannot be properly audited.

In essence the engine/OID separation step would somewhat follow scenario with GOST engine: OIDs remained in the OpenSSL tree, while the engine code is now being developed in a dedicated repository – https://github.com/gost-engine/engine.

In 2016 original author of DSTU4145 patches tried submitting them, but ultimately didn't follow up to provide OIDs as a separate PR – https://rt.openssl.org/Ticket/Display.html?id=3163&user=guest&pass=guest. I wonder if it can be done this time.

**Comment by richsalz** [comment]
Yes, please do so.

**Comment by gmile** [comment]
Closing since #5216 is now merged.
