### ISSUE TITLE
cryptlib.o (where to find?)

### ISSUE THREAD

**Issue by cokeflash** [openssl/openssl#5195]
Hi!
Where I can find the file cryptlib.o?

I have trouble with compile openssl cryptdev support.

Can someone help please?

make depend; make; make install
making depend in crypto...
make[1]: Entering directory '/home/nwo/Downloads/openssl-1.0.2n/crypto'
gcc: error: unrecognized command line option '--with-cryptodev'
Makefile:136: recipe for target 'local_depend' failed
make[1]: *** [local_depend] Error 1
make[1]: Leaving directory '/home/nwo/Downloads/openssl-1.0.2n/crypto'
Makefile:483: recipe for target 'depend' failed
make: *** [depend] Error 1
making all in crypto...
make[1]: Entering directory '/home/nwo/Downloads/openssl-1.0.2n/crypto'
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H --with-cryptodev -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o cryptlib.o cryptlib.c
gcc: error: unrecognized command line option '--with-cryptodev'
<builtin>: recipe for target 'cryptlib.o' failed
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory '/home/nwo/Downloads/openssl-1.0.2n/crypto'
Makefile:287: recipe for target 'build_crypto' failed
make: *** [build_crypto] Error 1
making all in crypto...
make[1]: Entering directory '/home/nwo/Downloads/openssl-1.0.2n/crypto'
gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H --with-cryptodev -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o cryptlib.o cryptlib.c
gcc: error: unrecognized command line option '--with-cryptodev'
<builtin>: recipe for target 'cryptlib.o' failed
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory '/home/nwo/Downloads/openssl-1.0.2n/crypto'
Makefile:287: recipe for target 'build_crypto' failed
make: *** [build_crypto] Error 1

**Comment by cokeflash** [comment]
cd openssl-1.0.2n

patch -p1 < ../ocf-linux-20171122/patches/openssl-1.0.2l.patch

rm /home/nwo/Downloads/openssl-1.0.2n/Makefile

sudo su

./config shared threads --with-cryptodev --openssldir=/etc/ssl --libdir=/lib --prefix=/usr

make depend; make; make install

**Comment by cokeflash** [comment]
what i have made wrong? how to fix?

**Comment by richsalz** [comment]
The flag '--with-cryptodev' is wrong.  Configure doesn't recognize it and it passing it to the compiler which barfs and fails to compile things.  You want to use ```enable-decryptoeng```

**Comment by levitte** [comment]
Actually, on 1.0.2, the cryptodev engine leads a somewhat secret life...  It's build by default on OpenBSD, FreeBSD, and if you want to *force* it to be built on other systems, you need to have `-DHAVE_CRYPTODEV` on the configuration command line.

**Comment by mattcaswell** [comment]
> patch -p1 < ../ocf-linux-20171122/patches/openssl-1.0.2l.patch

Where did you get this patch from? I can find the OCF linux version for OpenSSL 0.9.8 but not one for 1.0.2. Anyway the 0.9.8 version seems to add the "--with-cryptodev" option, so I assume the 1.0.2 version does the same. This seems to be a problem with your use of the patch, and not with OpenSSL. I suggest you contact the OCF Linux guys for support.

**Comment by cokeflash** [comment]
I use Ubuntu Mate... ok, I will contact the OCF Linux guys...

**Comment by cokeflash** [comment]
-- openssl engine:
(cryptodev) BSD cryptodev engine
(dynamic) Dynamic engine loading support
I'm happy :-)
