### ISSUE TITLE
OpenSSL and FIPS compatibility

### ISSUE THREAD

**Issue by Smeyla** [openssl/openssl#5201]
Hi,

I compiled a FIPS capable OpenSSL using fips-openssl-2.0.16 and fips-openssl-1.0.2l (designed as Long Time Support release on https://www.openssl.org/policies/releasestrat.html).

After compilation, i have 2 sets of headers:
 - 75 openssl's headers (v1.0.2l)
 - 26 FIPS' headers (v1.1.0)

I don't know which ones to use to compile my application using FIPS capable OpenSSL.
If I use FIPS' headers, i have compilation errors. For example, ASN1_OBJECT type is defined in asn1.h in v1.1.0 whereas it is defined in ossl_typ.h in v1.0.2l. asn1.h doesn't exist in my FIPS' headers but ossl_typ.h does so ASN1_OBJECT type is never found.
If I use only openssl's headers, I don't know if it is still FIPS compliant.

What is the solution in this case?

**Comment by t-j-h** [comment]
See section 5 in [https://www.openssl.org/docs/fips/UserGuide-2.0.pdf](url)

**Comment by Smeyla** [comment]
I read it several times and I did not find any explanation about header files to include. Or I misunderstood something...

**Comment by t-j-h** [comment]
Follow the instructions in the user guide - it tells you what to build and how to build it to create the FIPS canister and then how to build a FIPS-capable OpenSSL release (which is what you need for your application). And section 5 tells you how to write your application so you can enter FIPS mode and how to check that FIPS mode is operational.

**Comment by Smeyla** [comment]
I have the FIPS-capable OpenSSL release and the FIPS canister. But in my build directory, I have 2 sub-directories: fips and openssl.

If, in my application, I include headers from the openssl's directory it works fine: i am able to call FIPS_mode_set(). If I include headers from the fips' directory it doesn't compile.

Since the headers from the openssl's directory are older than those from the fips' directory, I am not sure that it is still FIPS compliant.

**Comment by mattcaswell** [comment]
Use the openssl headers. As long as FIPS_mode_set() is called and you've followed the rest of the user guide correctly then you are compliant.

**Comment by Smeyla** [comment]
Ok! Thank you for your time.
