### ISSUE TITLE
Unable to configure for Windows

### ISSUE THREAD

**Issue by xyuan240** [openssl/openssl#5204]
Hi, I have been following the steps to install openssl at a Windows7 system, and get stuck at the configuration steps. When I run the command : perl.exe Configure VC-WIN32, I got the following output and please refer to the error at the bottom of the log. 

The issue seems to be related with Text::Template, and I have installed it but the issue still persists. 

Any help/suggestions will be very appreciated! Thanks

%%% CMD OUTPUT%%%
> perl.exe Configure VC-WIN32
Using implicit seed configuration
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
for VC-WIN32
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-devcryptoeng [default]  OPENSSL_NO_DEVCRYPTOENG
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-external-tests [default]  OPENSSL_NO_EXTERNAL_TESTS
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-tls13downgrade [default]  OPENSSL_NO_TLS13DOWNGRADE
    no-tls1_3       [default]  OPENSSL_NO_TLS1_3
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default]
    no-zlib-dynamic [default]

PERL          =C:\Perl64\bin\perl.exe
PERLVERSION   =5.24.3 for MSWin32-x64-multi-thread
HASHBANGPERL  =/usr/bin/env perl
DEFINES       =DSO_WIN32 OPENSSL_SYS_WIN32 WIN32_LEAN_AND_MEAN L_ENDIAN _CRT_SECURE_NO_DEPRECATE _WINSOCK_DEPRECATED_NO_WARNINGS UNICODE _UNICODE OPENSSL_USE_APPLINK NDEBUG OPENSSL_NO_STATIC_ENGINE OP
ENSSL_PIC OPENSSL_BN_ASM_PART_WORDS OPENSSL_IA32_SSE2 OPENSSL_BN_ASM_MONT OPENSSL_BN_ASM_GF2m SHA1_ASM SHA256_ASM SHA512_ASM RC4_ASM MD5_ASM RMD160_ASM AES_ASM VPAES_ASM WHIRLPOOL_ASM GHASH_ASM ECP_NI
STZ256_ASM PADLOCK_ASM POLY1305_ASM
CC            =cl
CFLAGS        =-W3 -wd4090 -Gs0 -GF -Gy -nologo /MD /O2 -WX
LD            =link
LDFLAGS       =/nologo /debug
EX_LIBS       =ws2_32.lib gdi32.lib advapi32.lib crypt32.lib user32.lib
Undefined subroutine &Text::Template::GEN0::quotiry_l called at template line 178.
 in Configurations\windows-makefile.tmpl, fragment starting at line 176
%%% END OF OUTPUT%%%

Regards

**Comment by mspncp** [comment]
See https://github.com/openssl/openssl/pull/5196

**Comment by levitte** [comment]
Please pull a fresher master.  #5196 got merged in earlier today.

**Comment by xyuan240** [comment]
Thanks all, it fixed the problem
