### ISSUE TITLE
No object file generated when compiling for win32 

### ISSUE THREAD

**Issue by xyuan240** [openssl/openssl#5209]
I got the following error when compiling for VC-WIN32 configuration:
Could you please help? Thanks.

%%%
aes_wrap.c
crypto\aes\aes_wrap.c(18) : error C2220: warning treated as error - no 'object' file generated
crypto\aes\aes_wrap.c(18) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data
crypto\aes\aes_wrap.c(26) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\amd64\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
%%%

PS. Let me know if you need a longer log.

**Comment by mattcaswell** [comment]
Did you run this from the 32-bit developer command prompt or the 64-bit one? Which version of OpenSSL is this?

**Comment by mspncp** [comment]
From your log output  it looks like you specified a 32bit target (CV-WIN32), but are using a 64bit build environment (cl.exe,nmake.exe).

**Comment by mspncp** [comment]
Try to use the VC-WIN64A target.

**Comment by xyuan240** [comment]
VC-WIN64A compiles in my case, thanks
