### ISSUE TITLE
Internal Error during CertificateRequest parsing

### ISSUE THREAD

**Issue by ic0ns** [openssl/openssl#5213]
During our research with TLS-Attacker we discovered that the openssl client responds with an Internal Error Alert if the length fields in a CertificateRequest message are not correct. We assume that this behavior is harmless but not RFC compliant:
>An internal error unrelated to the peer or the correctness of the
>protocol (such as a memory allocation failure) makes it impossible
>to continue.  This message is always fatal.

An example CertificateRequest which shows this behavior:
 `0d0000080001000202010000`

`140500787355392:error:1416909F:SSL routines:tls_process_certificate_request:length mismatch:ssl/statem/statem_clnt.c:2457:`

**Comment by richsalz** [comment]
We tend to reply 'internal error' when the incoming packet format is badly formatted.  You don't have to open separate issues for each instance of this :)  But listing the places where we send the wrong alert would be useful.

**Comment by jurajsomorovsky** [comment]
According to the TLS spec, an internal error is
> unrelated to the peer or the correctness of the protocol (such as a memory allocation failure) makes it impossible to continue.  This message is always fatal.

In such cases either a decode_error
> A message could not be decoded because some field was out of the specified range or the length of the message was incorrect.  This message is always fatal and should never be observed in communication between proper implementations (except when messages were corrupted in the network).

or an illegal_parameter alert
> A field in the handshake was out of range or inconsistent with other fields.  This message is always fatal.

would be more appropriate.

We know that this is not security relevant and is only a minor issue :)
We talked to @mattcaswell at RWC and he was interested in creating issues for these problems.

But you are right, it would be better to collect all of them and submit them in one issue instead of spamming your repo :)

**Comment by richsalz** [comment]
I completely agree with all of that. :)  Looking forward to eventually getting a full-passing grade from your tool!

**Comment by mattcaswell** [comment]
> We tend to reply 'internal error' when the incoming packet format is badly formatted.

I hope we don't. Mostly we reply decode_error or illegal_parameter as appropriate. At least I hope we do in master where I've tried to clean some of this stuff up.

> We talked to @mattcaswell at RWC and he was interested in creating issues for these problems.

Please do. I'd like to hear about them.

I assume you tested on master?

**Comment by ic0ns** [comment]
Yes we tested on the current master branch.
