### ISSUE TITLE
pkeyutl cannot access keys (private or public) on pkcs11 tokens

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#522]
Symptoms:
```
$ openssl version
OpenSSL 1.0.2e 3 Dec 2015
$ openssl pkeyutl -engine pkcs11 -keyform engine -sign -inkey "pkcs11:object=SIGN%20key;object-type=private" -pkeyopt digest:sha384 -out t384.dat.sig -in t384.dat
engine "pkcs11" set.
PKCS#11 token PIN: 
Error initializing context
140735278175056:error:260C0065:engine routines:ENGINE_get_pkey_meth:unimplemented public key method:tb_pkmeth.c:128:
140735278175056:error:0609D09C:digital envelope routines:INT_CTX_NEW:unsupported algorithm:pmeth_lib.c:164:
Usage: pkeyutl [options]
-in file        input file
.........
```

When signature is created by a fixed version of openssl, pkeyutl still fails to access public key:
```
$ openssl pkeyutl -engine pkcs11 -keyform engine -verify -pubin -inkey "pkcs11:object=SIGN%20pubkey;object-type=public" -sigfile t384.dat.sig -pkeyopt digest:sha384 -in t384.dat
engine "pkcs11" set.
Error initializing context
140735278175056:error:260C0065:engine routines:ENGINE_get_pkey_meth:unimplemented public key method:tb_pkmeth.c:128:
140735278175056:error:0609D09C:digital envelope routines:INT_CTX_NEW:unsupported algorithm:pmeth_lib.c:164:
Usage: pkeyutl [options]
-in file        input file
.........
```

This issue has been discussed on the openssl-dev mailing list, and Steve Henson suggested a solution [https://www.mail-archive.com/openssl-dev@openssl.org/msg41176.html].
PR to fix this problem (addressing Steve Henson's concern that this fix should not interfere with other engines https://www.mail-archive.com/openssl-dev@openssl.org/msg41180.html) submitted: https://github.com/openssl/openssl/pull/520

After applying the above fix, the application behaves correctly:
```
openssl pkeyutl -engine pkcs11 -keyform engine -sign -inkey "pkcs11:object=SIGN%20key;object-type=private" -pkeyopt digest:sha384 -out t384.dat.sig -in t384.dat
engine "pkcs11" set.
PKCS#11 token PIN: 
$ dumpasn1 t384.dat.sig
  0 102: SEQUENCE {
  2  49:   INTEGER
       :     00 8B FB 6D 0B E0 1A 29 4F 40 D9 95 74 A2 86 A4
       :     9C FB 77 17 35 FC 65 80 E7 1B E8 04 DB 91 DD CE
       :     1B FE 30 6D 3B 48 59 3D 10 9C 03 CC 70 B6 D8 22
       :     B9
 53  49:   INTEGER
       :     00 8F EB CE 89 1A 0C 12 EF 42 E4 C3 A4 12 D2 01
       :     E4 5F B5 98 EE 41 E1 BA 19 D8 73 69 BB 52 56 87
       :     72 C4 2B 83 5E 4B A9 BE 49 AE 17 EA B0 F9 28 34
       :     30
       :   }

0 warnings, 0 errors.
$ openssl pkeyutl -engine pkcs11 -keyform engine -verify -pubin -inkey "pkcs11:object=SIGN%20pubkey;object-type=public" -sigfile t384.dat.sig -pkeyopt digest:sha384 -in t384.dat
engine "pkcs11" set.
Signature Verified Successfully
$
```

P.S. The proposed PR also addresses an issue of NULL-pointer access during engine destroy operation.

**Comment by levitte** [comment]
My concern with the change that #520 offers is the risk of it becoming permanent.  Steve calls the fix a temporary measure in the message you point at.  That's the reason I'm reluctant.

However, in discussing this privately with Steve, he reminded me of the solution in `openssl dgst` in master, where the engine is only used for loading keys unless you add the option `-engine_impl`.  I think that would be a cleaner solution that leaves the decision in the hands of the user.

So in essence, I would welcome a solution where the engine parameter to `EVP_PKEY_CTX_new` is `NULL` by default.

**Comment by mouse07410** [comment]
As I understand it, Steve was concerned of making this fix permanent because he thought that sometimes people may want/need the "old" behavior (passing `e` rather than `NULL`).

As I'm observing, there is no way the code can work with pkcs11 engine, unless the engine parameter is `NULL`, so I think it is safe to always pass `NULL` if `keyform = engine` (or `peerform = engine`), *and* engine is `pkcs11`. I admit that I don't know what other engines there are, and whether they'd benefit from the same fix or break on it.

I also don't know (not enough expertise with the internals of openssl) when you do want/need to pass the engine parameter.

This is why I restricted the proposed fix to the case when both are true: (a) the key is on the token (so the engine should access it), *and* (b) the engine is `pkcs11` (as I know that it needs this fix for sure).

> I would welcome a solution where the engine parameter to EVP_PKEY_CTX_new is NULL by default.

I can certainly change my proposed fix to do that. But could you clarify: do you want to preserve the option of passing `e`, and what would be the condition for passing a non-`NULL` engine parameter? An extra explicit command-line argument `-engine_impl`? Or when neither `keyform` nor `peerform` parameter is provided? I admit being a bit confused here.

**Comment by levitte** [comment]
My thought is that without `-engine_impl`, `EVP_PKEY_CTX_new` would get `NULL`, with that option, it would get `e`.

(have a look at `dgst.c`, see how it does it)

**Comment by mouse07410** [comment]
OK, now I understand what what you're asking for. Let me work on that. I hope somebody else would update the documentation (once this PR is submitted and merged).

**Comment by mouse07410** [comment]
Submitted https://github.com/openssl/openssl/pull/523.

**Comment by mouse07410** [comment]
@levitte any update on the merge? Is anything blocking it now?

**Comment by mouse07410** [comment]
@levitte could I ask to merge this one rather sooner than later? Thanks!

**Comment by mouse07410** [comment]
Thanks!

**Comment by jclsn** [comment]
I am getting the same error. Would be nice if an example for ``-engine_impl`` could be added to the documentation or manpages

**Comment by mouse07410** [comment]
Now that OpenSSL v3+ deprecates the engine API altogether. So, you're better off switching to _provider_ API.
