### ISSUE TITLE
Support for multivalue rdn is broken

### ISSUE THREAD

**Issue by asambeka** [openssl/openssl#5233]
OpenSSL client supports multivalue rdn only in the last RDN component of the DN.
e.g.
`/DC=org/DC=OpenSSL/DC=DEV/UID=123456+CN=John Doe` works while
`/DC=org/DC=OpenSSL/DC=DEV+O=users/CN=John Doe` does not.

`$openssl req -new -multivalue-rdn -subj "/DC=org/DC=OpenSSL/DC=DEV/UID=123456+CN=John Doe" -sha256 -key rdntest.key -out test.csr`
`$openssl req -noout -text -in test.csr
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: DC=org, DC=OpenSSL, DC=DEV, CN=John Doe/UID=123456
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
`

And 
`$openssl req -new -multivalue-rdn -subj "/DC=org/DC=OpenSSL/DC=DEV+O=users/CN=John Doe" -sha256 -key rdntest.key -out test.csr`
`$openssl req -noout -text -in test.csr
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: DC=org, DC=OpenSSL, O=users, DC=DEV, CN=John Doe
        Subject Public Key Info:
`

Later is simply treated as another RDN and not as multivalued RDN.

This should be fixed as this break LDAP integration with Certificates.

**Comment by richsalz** [comment]
What version are you using?  When I try against the latest master, I get a "no distinguished name" error.  What seems to agree with your issue: the request DN isn't parsed properly.

At any rate, multi-value RDN's are not a high priority for the team.  If you need this fixed, you might have to do it yourself and create a pull request.

**Comment by asambeka** [comment]
My version: LibreSSL 2.2.7

I'll try to fork and submit pull. Will it be okay to add dependency on Mozilla C LDAP SDK? It has an RFC 2253 compliant DN parser.

**Comment by levitte** [comment]
Hmmm, I Just tried the same thing with the Debian installed OpenSSL 1.1.0g, and it seems to register the multivalue RDN:

```
: ; openssl req -new -multivalue-rdn -subj "/DC=org/DC=OpenSSL/DC=DEV/UID=123456+CN=John Doe" -sha256 -key rdntest.key -out test.csr
: ; openssl req -noout -subject -in test.csr
subject=DC = org, DC = OpenSSL, DC = DEV, CN = John Doe + UID = 123456
: ; openssl req -noout -subject -in test.csr -nameopt multiline
subject=
    domainComponent           = org
    domainComponent           = OpenSSL
    domainComponent           = DEV
    commonName                = John Doe + userId                    = 123456
```

```
: ; openssl req -new -multivalue-rdn -subj "/DC=org/DC=OpenSSL/DC=DEV+O=users/CN=John Doe" -sha256 -key rdntest.key -out test.csr
: ; openssl req -noout -subject -in test.csr
subject=DC = org, DC = OpenSSL, O = users + DC = DEV, CN = John Doe
: ; openssl req -noout -subject -in test.csr -nameopt multiline
subject=
    domainComponent           = org
    domainComponent           = OpenSSL
    organizationName          = users + domainComponent           = DEV
    commonName                = John Doe
```

Tried the same with a freshly built checkout of master as well, got the exact same results.

It's possible that OpenSSL 1.0.2 has this fault.  Considering that's the point where LibreSSL forked, we might have it there too.  I'll check.

As for library dependencies, we try our best to keep them at a minimum.

**Comment by levitte** [comment]
Nope, 1.0.2 seems to work right as well...

```
: levitte@lapdog:~/gitwrk/openssl.net/official/1.0.2
: ; ./util/shlib_wrap.sh apps/openssl genrsa -out rdntest.key
Generating RSA private key, 2048 bit long modulus
............................................+++
.......................................+++
e is 65537 (0x10001)
: ; ./util/shlib_wrap.sh apps/openssl req -new -multivalue-rdn -subj "/DC=org/DC=OpenSSL/DC=DEV/UID=123456+CN=John Doe" -sha256 -key rdntest.key -out test.csr
: ; ./util/shlib_wrap.sh apps/openssl req -noout -subject -in test.csr -nameopt oneline
subject=DC = org, DC = OpenSSL, DC = DEV, CN = John Doe + UID = 123456
: ; ./util/shlib_wrap.sh apps/openssl req -new -multivalue-rdn -subj "/DC=org/DC=OpenSSL/DC=DEV+O=users/CN=John Doe" -sha256 -key rdntest.key -out test.csr
: ; ./util/shlib_wrap.sh apps/openssl req -noout -subject -in test.csr -nameopt oneline
subject=DC = org, DC = OpenSSL, O = users + DC = DEV, CN = John Doe
```

So I think you need to take this back to the LibreSSL folks...

**Comment by asambeka** [comment]
I see issues even with 1.0.2.g:
```
$:~/certs/nodeagent$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
$:~/certs/nodeagent$ openssl req -new -sha256 -key serverB.key -out serverB.csr -multivalue-rdn -subj "/DC=org/DC=OpenSSL/DC=DEV+O=users/CN=John Doe"
$:~/certs/nodeagent$ openssl req -in serverB.csr -noout -text
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: DC=org, DC=OpenSSL, O=users, DC=DEV, CN=John Doe
        Subject Public Key Info:
```
