### ISSUE TITLE
pkeyutl fails "-derive" when one of the keys is on a hardware token

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#524]
```
echo "Deriving shared key from ephemeral private and token public keys..."
$ apps/openssl pkeyutl -engine pkcs11 -peerform engine -derive -inkey /tmp/derive.99204.priv.pem -peerkey "pkcs11:object=KEY%20MAN%20pubkey;object-type=public" -out /tmp/derive.99204.shared1
engine "pkcs11" set.
no engine specified
unable to load Peer Key
Error reading peer key pkcs11:object=KEY%20MAN%20pubkey;object-type=public
Usage: pkeyutl [options]
-in file        input file
......
```

Similar when the private key is on the token:
```
apps/openssl pkeyutl -engine pkcs11 -keyform engine -derive -inkey id_03 -peerform DER -peerkey /tmp/derive.99204.pub.der -hexdump
engine "pkcs11" set.
PKCS#11 token PIN:
140735231131728:error:10071065:elliptic curve routines:EC_POINT_cmp:incompatible objects:ec_lib.c:1002:
140735231131728:error:0609B099:digital envelope routines:EVP_PKEY_derive_set_peer:different parameters:pmeth_fn.c:314:
Public Key operation error
140735231131728:error:100D908C:elliptic curve routines:PKEY_EC_DERIVE:keys not set:ec_pmeth.c:216:
$ dumpasn1 /tmp/derive.99204.pub.der
  0 118: SEQUENCE {
  2  16:   SEQUENCE {
  4   7:     OBJECT IDENTIFIER ecPublicKey (1 2 840 10045 2 1)
 13   5:     OBJECT IDENTIFIER secp384r1 (1 3 132 0 34)
       :     }
 20  98:   BIT STRING
       :     04 7B FA 9B D5 F3 E2 6A 9B 07 9A 09 5E B9 F5 52
       :     02 BF 86 5C D9 B9 B3 1C F9 F1 32 75 B7 9C A2 C0
       :     CD FC 77 FE 7E 3E 80 91 93 9B 4B DF C2 C5 32 B6
       :     6B 46 58 2C 9C 76 7A 4A 22 F9 EC DC A6 37 09 20
       :     97 B7 A1 35 85 7E 3C E0 6A 8D ED B6 A1 2A 6F 87
       :     B1 40 1B 08 7A 6E DC 09 03 21 A0 36 26 53 DC 72
       :     3A
       :   }

0 warnings, 0 errors.
$ pkcs15-tool --list-keys
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
Private EC Key [PIV AUTH key]
        Object Flags   : [0x1], private
        Usage          : [0x4], sign
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        FieldLength    : 384
        Key ref        : 154 (0x9A)
        Native         : yes
        Auth ID        : 01
        ID             : 01
        MD:guid        : 0x'30316234616361663934653637386235363830333063623237386433646461340000000000000000'

Private EC Key [SIGN key]
        Object Flags   : [0x1], private
        Usage          : [0x204], sign, nonRepudiation
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        FieldLength    : 384
        Key ref        : 156 (0x9C)
        Native         : yes
        Auth ID        : 01
        ID             : 02
        MD:guid        : 0x'30326234616361663934653637386235363830333063623237386433646461340000000000000000'

Private EC Key [KEY MAN key]
        Object Flags   : [0x1], private
        Usage          : [0x100], derive
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        FieldLength    : 384
        Key ref        : 157 (0x9D)
        Native         : yes
        Auth ID        : 01
        ID             : 03
        MD:guid        : 0x'30336234616361663934653637386235363830333063623237386433646461340000000000000000'

Private EC Key [CARD AUTH key]
        Object Flags   : [0x0]
        Usage          : [0x4], sign
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        FieldLength    : 384
        Key ref        : 158 (0x9E)
        Native         : yes
        ID             : 04
        MD:guid        : 0x'30346234616361663934653637386235363830333063623237386433646461340000000000000000'
```

It is possible to use private or public key directly from the token in `-sign` and `-verify` commands. 

Ideal solution: ability to derive a symmetric key when (a) private key is on the token and peer's (ephemeral) public key is in a file, and (b) (ephemeral) private key is is a file and peer public key is on the token.

**Comment by mouse07410** [comment]
With the current levels of OpenSSL-1.0.2f+ and 1.1, all of the above except one have been addressed.

The only remaining issue is to be able to perform `-derive` when the **public** key is on the token. As was pointed out, this use case is somewhat contorted because in real life you aren't likely to have access to your peer's hardware token.

**Comment by mouse07410** [comment]
**Update**  

Tested OpenSSL-1.1 (pre-whatever :) with an ECC token, `ECDH1-DERIVE` with the private key on the token works fine. Thanks, @dengert 

P.S. I still would like to get the weird case of *public* key being on the token to work, but that's for later. ;)

**Comment by dengert** [comment]
On 2/22/2016 9:49 AM, Mouse wrote:
> *Update*
>
> Tested OpenSSL-1.1 (pre-whatever :) with an ECC token, |ECDH1-DERIVE| with the private key on the token works fine. Thanks, @dengert <https://github.com/dengert>
>
> P.S. I still would like to get the weird case of /public/ key being on the token to work, but that's for later. ;)

Not with a PIV card. It does not define how to do that.

>
> —
> Reply to this email directly or view it on GitHub <https://github.com/openssl/openssl/issues/524#issuecomment-187239368>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
> Not with a PIV card. It does not define how to do that.

True, **but**... Before the patch it (`openssl pkeyutl -derive ...`) had no problem accessing **public** key on the token - so regardless of whether it was defined or not, there was a way. After the `ECDH-DERIVE` has been fixed (and it's a good thing!) to work with the private key on the token, it unfortunately lost the ability to deal with the less-needed public key on the token. 

I agree with you that this second use case is contorted, and far far less important or necessary that the main one (private key on the token). It would still be nice if both could be made to work. One way to do that appears to simply not initialize the key structure with the `derive()` method if `-peerform engine`. A concern is that such a measure would screw up functioning of programmatic access that loads/initializes the engine once, and then performs several operations...

**Comment by mouse07410** [comment]
Thanks to @mtrojnar this is working completely - for private *or* public key on the token, tested with  OpenSSL-1.0.2g+ and OpenSSL-1.1-pre4. Just use the latest [`libp11`](https://github.com/OpenSC/libp11) master branch from Github.
