### ISSUE TITLE
Configure usability

### ISSUE THREAD

**Issue by dot-asm** [openssl/openssl#5248]
Recent changes to Configure stripped all visual feedback about configurations parameters. As alternative it's suggested to examine configdata.pm (by running it with flags) and Makefile. I'd like to argue that this poses a two-fold problem.

1. One of ideas behind original output was that user would intuitively provide the output as part of problem report. Leaving no visual information about configuration parameters and leaving no explicit instructions on what problem report receiver would appreciate to see in the report is essentially counter-productive. Even though one can argue that user can and should figure latter out by fine-reading README, INSTALL and NOTES. [Well, one can actually challenge if it's there. As closest it says about failures during make is "try this-n-that and if it's still problem mail openssl-users or report a bug". It does mention configdata --help elsewhere, but apparently nowhere does it say what's considered useful to problem report receiver.]

2. Depriving all visual feedback makes it unnecessary tricky to experiment with additional config command line options. When user passes an additional flag it's reasonable to assume that [s]he would appreciate to see how it's interpreted and affects for example compiler command line parameters. And I'd say that imposing multi-step procedure with multi-page output poses a usability problem.

**Comment by levitte** [comment]
1. I agree that Configure should say *something*. It's been argued that what it currently says (in master) is insufficient and possibly ambiguous. I'm looking for for input on what to replace it with (and yes, there are some suggestions). For problem reports, it would make sense to suggest `perl configdata.pm --dump`, of course...

2. I dunno what to say here. There's a trade-off between not wanting to spew an unsolicited dump in the face of our users, still wanting to give them the possibility to get information they desire or need without having to wade through a ton of stuff or knowing exactly what to grep for, and wanting to give the full picture (note that you can still select what of several groups of data that you might be interested in)

**Comment by levitte** [comment]
There's one thing about the multi-step approach that I keep forgetting to mention: timing.

There's been many a time when a dump of configuration data *at the time of configuration* is utterly uninteresting. However, when make has failed a gazillion lines later is usually a time when I start to want to see what actually got configured. With the dump that Configure did (and does in 1.1.0), that means I either have to scroll back (if possible... my scroll buffer of 2000 lines is usually *not* enough) or reconfigure just to get those lines again. In my mind, it's more convenient to have a runnable configdata.pm that I can ask any time...

**Comment by dot-asm** [comment]
> There's a trade-off between not wanting to spew an unsolicited dump in the face of our users, ...

Well, one can argue whether or not some truncated feedback is actually unsolicited. [And it was truncated in master in comparison to 1.1.0.] As taking this argument to the outermost would render *any* output unsolicited. For example I for one might find it irrelevant when configdata.pm is generated(*). Anyway, would it be possible to say this? If user passed *any* additional command line option, then [s]he solicited feedback.

> ... and wanting to give full picture.

??? Full picture is, has been and will always be there, so how come it becomes part of trade-off? As it is now it sounds more like "there is full picture and it's more usable to everybody that anything else. period." This doesn't sound like trade-off...

(*) Currently suggested output reads:
```
Configuring OpenSSL version 1.1.1-dev (0x10101000L) for linux-x86_64
Using implicit random seed configuration
Creating configdata.pm
Creating Makefile
```

**Comment by dot-asm** [comment]
> a dump of configuration data at the time of configuration is utterly uninteresting [because make fails later].

That's why I [suggested](https://github.com/openssl/openssl/pull/5247#issuecomment-362601163) that note about how to troubleshoot such case is in "star-box". Idea is to stimulate user to put something in short-term memory.

Just in case, note that 2nd usability problem is not about that. One can even say following. 1st usability problem is about unsuspecting user. And so is timing issue you brought up. 2nd usability problem on the other hand is rather about aware user, one who needs [or appreciate opportunity] to perform sanity check at config time. I mean pass an extra argument, see what it entails. And assertion is that even extra step poses usability problem.

**Comment by mspncp** [comment]
> For problem reports, it would make sense to suggest `perl configdata.pm --dump`, of course...

I would rather go with Andy's suggestion of having a special config (or make) target which forwards to the `perl configdata --dump` command. How about supporting the following two commands?
```
./configure dump
perl Configure dump
``` 
 The user is already confronted with `./configure`, `perl Configure <config_target>`, and `make <build_target>`, so one should not introduce yet another script, in particular since it's an implementation detail that `configdata.pm` is the perl module handling the configuration.

**Comment by mspncp** [comment]
Currently, there are far too many steps to be followed for issuing a bug report.

```
If you wish to report a bug then please include the following information
 and create an issue on GitHub:

    - OpenSSL version: output of 'openssl version -a'
    - Configuration data: output of 'perl configdata.pm --dump'
    - OS Name, Version, Hardware platform
    - Compiler Details (name, version)
    - Application Details (name, version)
    - Problem Description (steps that will reproduce the problem, if known)
    - Stack Traceback (if the application dumps core)
```

A lot of this information could be gathered automatically by `./configure dump`. Let me take the version information as an example: As Andy (or someone else?) mentioned previously, `openssl version -a` is not the best choice, because it shows the version information of the _installed_ binaries, not of the ones which are built.

The `./configure dump` command could grep the `OPENSSL_VERSION_TEXT` from `opensslv.h` and display it. Even more, if the date is `xx XXX xxxx`, it could silently issue the `git describe` command, which yields something like  `OpenSSL_1_1_0-pre6-3849-g71bb86f0dc` if it's a git working copy.

**Comment by t-j-h** [comment]
What you are describing is something separate - a tool for automating the information required for a bug report - that to me is a different (but also useful) problem.

**Comment by mspncp** [comment]
But isn't Andy's central motivation for raising this issue precisely the goal to provide an easy-to-use way for the unexperienced user to gather information for bug reports ? At least that's what I read in the description above: 

> One of ideas behind original output was that user would intuitively provide the output as part of problem report.

**Comment by nickthetait** [comment]
Automated collection of relevant debugging information would greatly reduce time between initial report to triage. I think this is a great direction to take. I see this effort as tightly coupled with the design of the output that `configure` provides

**Comment by noloader** [comment]
One other thing... configure no longer seems to actually configure. `--openssl-dir` should be rejected when it is used, and not at some random time later.

```
$ ./config --openssl-dir=/opt/local/test/a/bin --prefix=/opt/local/test  --libdir=/opt/local/test/b/lib
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1-pre2-dev (0x10101002L) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

NOTE: Starting with OpenSSL 1.1.1, 'Configure' doesn't display all the disabled
options or the "make variables" with their values.  Instead, you must use
'configdata.pm' as a script to get a display of the configuration data.  For
help, please do this:

        perl configdata.pm --help
skylake:openssl$ make
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _all
make[1]: Entering directory '/home/jwalton/openssl'
make[1]: Leaving directory '/home/jwalton/openssl'
make[1]: Entering directory '/home/jwalton/openssl'
gcc  -I. -Iinclude -Wall -O3 -pthread -m64 --openssl-dir=/opt/local/test/a/bin -Wa,--noexecstack -fPIC -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSLDIR="\"/opt/local/test/ssl\"" -DENGINESDIR="\"/opt/local/test/opt/local/test/b/lib/engines-1.1\"" -c -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
gcc: error: unrecognized command line option '--openssl-dir=/opt/local/test/a/bin'
make[1]: *** [Makefile:677: apps/app_rand.o] Error 1
make[1]: Leaving directory '/home/jwalton/openssl'
make: *** [Makefile:144: all] Error 2
```

**Comment by noloader** [comment]
This is starting to smell of bad engineering.

Add a `--quiet` switch to suppress the output if you don't want to see it. Otherwise, leave it alone.

**Comment by levitte** [comment]
> One other thing... configure no longer seems to actually configure.

Because it's behaving more like GNU's `configure` (except it doesn't do all the searching and checking)?

> `--openssl-dir` should be rejected when it is used, and not at some random time later.

You obviously know you spellt it wrong, and it *is* documented that all unrecognised flags become C flags.  We cannot take that away in the middle of a major release series, because it would disrupt things too much for those who do use this feature (I'm sure you call it "misfeature"), so if you want *that* behavior gone, you can propose it for 1.2.

**Comment by levitte** [comment]
@noloader, regarding the output from Configure / config, have a look at #5247, where it refers directly to the `--dump` parameter instead of having you read the help.

**Comment by mattcaswell** [comment]
Can this be closed now?

**Comment by levitte** [comment]
I think so.  Haven't heard anything more on the matter for a bit, and I do believe I adapted Configure according to desire (although my desire for feedback hasn't been met, mais c'est la vie).

Tell you what, if someone still has issues, they can open a new issue.

Closing.
