### ISSUE TITLE
Bug in ECDSA_verify / i2d_ECDSA_SIG when sig component is negative

### ISSUE THREAD

**Issue by bse-sja** [openssl/openssl#5249]
ECDSA_verify fails if one of the signature components is negative
because i2d_ECDSA_SIG returns the incorrect size;

problem is in ecs_vrf.c:

    derlen = i2d_ECDSA_SIG(s, &der);
    if (derlen != sig_len || memcmp(sigbuf, der, derlen))
        goto err;

If signature component is negative derlen is computed as 71 instead of 70.
So I get "Public Key operation error" ... but if I comment out the length
check I get "Signature Verified Successfully"

Here is the parse of the signature file (second component is negative):

openssl asn1parse -i -inform DER -in file -in pub.sig
    0:d=0  hl=2 l=  68 cons: SEQUENCE
    2:d=1  hl=2 l=  32 prim:  INTEGER           :
4C5A2B4F5DF1540481A1B07A7A6007284AD69C654AA12863A4B9728B1179D0CB
   36:d=1  hl=2 l=  32 prim:  INTEGER           :
-37D6425BDFF8E68263205D4DD798AE816B127B439AE29161662B23D15D773C7D

od -t x1 pub.sig
0000000 30 44 02 20 4c 5a 2b 4f 5d f1 54 04 81 a1 b0 7a
0000020 7a 60 07 28 4a d6 9c 65 4a a1 28 63 a4 b9 72 8b
0000040 11 79 d0 cb 02 20 c8 29 bd a4 20 07 19 7d 9c df
0000060 a2 b2 28 67 51 7e 94 ed 84 bc 65 1d 6e 9e 99 d4
0000100 dc 2e a2 88 c3 83
0000106

**Comment by richsalz** [comment]
What software generated that signature?  Shouldn't numbers with the high-bit-one have a leading zero so that they are not, as shown here, interpreted as negative?

**Comment by bse-sja** [comment]
signature was generated by Atmel ATECC508 hardware crypto chip and dropped
into a fixed DER format.

So prepending a zero to numbers with the high bit set seems to fix the
problem. Although I get a similar error
if I prepend a 0 to a postive number (which seems like it should be valid)
.. so will have to do some signature content
based parsing to generate DER signatures that openssl is happy with.

(could not find a command line tool to to create DER format signatures /
keys from raw binary data ...)

Thanks !
    Stuart

**Comment by davidben** [comment]
Unfortunately a pair of DER INTEGERs are a terrible format for (EC)DSA signatures, but that mistake was made long ago and we're stuck with what we've got. OpenSSL is correct to reject that signature. Your software will need to encode your INTEGERs correctly. In particular:

1. You need to encode your values in minimal-length. If r happens to be 5, it needs to be encoded with one byte, not 32.
2. After removing leading zeros, if and only if the high bit is set, add a single leading zero to make it positive.

Yes, this is an obnoxiously variable-length signature format. :-(

**Comment by richsalz** [comment]
I am closing this.

**Comment by mspncp** [comment]
> I am closing this.

Did you press the wrong button? :wink:
