### ISSUE TITLE
Include in manpage of X509_check_host incomplete

### ISSUE THREAD

**Issue by dveeden** [openssl/openssl#5255]
Manpage: https://www.openssl.org/docs/manmaster/man3/X509_check_host.html

This has
```
#include <openssl/x509.h>
```

But `X509_CHECK_FLAG_NO_WILDCARDS` is not defined in that header.
```
$ git grep 'define X509_CHECK_FLAG_NO_WILDCARDS'
include/openssl/x509v3.h:# define X509_CHECK_FLAG_NO_WILDCARDS    0x2
```

So to me it looks like this is not correct/complete.

**Comment by richsalz** [comment]
Fixed on master; thanks!
