### ISSUE TITLE
Direct access to ED25519 sign/verify functions

### ISSUE THREAD

**Issue by rwfranks** [openssl/openssl#5261]
May I make a special pleading for the three ED25519 routines in curve25519.c to be promoted from ec_lcl.h into ec.h and exposing these to the wider world.

Pressure is mounting, from DNSSEC tool builders and others, for the Net::DNS::SEC perl distribution to incorporate ED25519 sign/verify functions.

Net::DNS::SEC already depends upon OpenSSL libcrypto.so for its cryptography.  Extending this to include ED25519 would be much the best route to a good quality and maintainable solution.

Your cooperation would be greatly appreciated by the Net::DNS::SEC user base.

**Comment by mattcaswell** [comment]
The dev version (1.1.1) already supports Ed25519 (although it does this via the EVP interface, and not in the manner you proposed).

**Comment by rwfranks** [comment]
I do not doubt that for a second.

But burrowing through a nest of MD_CTX, PKEY_CTX, PKEY objects to call the ONE line that matters is less than appealing, when the full generality of EVP is not warranted.

Please reconsider my request.

**Comment by richsalz** [comment]
We understand.  But a single common interface is something we consider important and EVP is it.
