### ISSUE TITLE
Compile PHP 7.2.2 with openssl on macOS

### ISSUE THREAD

**Issue by xxalfa** [openssl/openssl#5262]
macOS 10.13.2
LibreSSL 2.2.7

When I try to compile PHP 7.2.2 with openssl, I get these errors.

```
configure: error: Cannot find OpenSSL's <evp.h>
```
The following command solves the first problem.
```
$ cd /usr/local/include 
$ ln -s ../opt/openssl/include/openssl
```
Now I get this error, can someone help me?
```
Undefined symbols for architecture x86_64:
  "_X509_get_signature_nid", referenced from:
      _zif_openssl_x509_parse in openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
```

**Comment by levitte** [comment]
OpenSSL != LibreSSL, even though the latter is a fork of the former.
I think you should get in touch with the LibreSSL folks.

**Comment by xxalfa** [comment]
```
$ openssl version
LibreSSL 2.2.7
```
Then I do not understand why LibreSSL is installed. I would like to use openssl and did it with brew install openssl.

My wish is simply to use the latest version of PHP with openssl, so I'm in the right place.
