### ISSUE TITLE
[Q] chacha20 IV length

### ISSUE THREAD

**Issue by wongsyrone** [openssl/openssl#5264]
Based on OpenSSL 1.1.0g documentation, chacha20 is a cipher with 96bit IV.

```
=item EVP_chacha20()

The ChaCha20 stream cipher. The key length is 256 bits, the IV is 96 bits long.
```

While `EVP_CIPHER_iv_length(cipher)` gives me the following result.

```
name=ChaCha20
block_sz=1
key_length=32
iv_length=16
```

Can anyone elaborate how to use the IETF variant?

**Comment by p-steuer** [comment]
iv_length=16 i.e., 128 bit refers to 32 bit counter followed by 96 bit nonce. ChaCha20_ctr32 works on 32 bit counter, so libcrypto's ChaCha20 implementation conforms to RFC7539.

**Comment by wongsyrone** [comment]
@p-steuer Hi, thanks for the reply, but it doesn't work, the test vector in libsodium looks different. https://github.com/jedisct1/libsodium/blob/master/test/default/chacha20.c#L81

**Comment by p-steuer** [comment]
I cannot see how the test vectors look different ? Its a counter value (ic) and a 96bit nonce (nonce_hex). Encode the counter value to 32 bit little endian and concatenate it with the nonce. Use the resulting iv with EVP_*Init.
