### ISSUE TITLE
MSVC build recursion discards nmake flags

### ISSUE THREAD

**Issue by qris** [openssl/openssl#5277]
NMake is incredibly verbose, spewing out the entire make command line for each file which adds about a thousand long lines of noise to a CI build log like [this one](https://ci.appveyor.com/project/qris/boxbackup/build/job/299umaism669damj) (see lines 2018 to 4308).

I would like to run `nmake` with the `/s` option, and in fact my build script already does that, but the generated `makefile` recursively invokes `$(MAKE)` without `/$(MAKEFLAGS)` and so discards the option:

```
# The main targets ###################################################

all: build_generated
        $(MAKE) depend && $(MAKE) _all
_all: build_libs_nodep build_engines_nodep build_programs_nodep
```

From the [NMake manual](https://msdn.microsoft.com/en-us/library/7cafx990.aspx), list of macros:

> MAKE: Command used originally to invoke NMAKE.The $(MAKE) macro gives the full path to nmake.exe.
> MAKEFLAGS: Options currently in effect. Use as /$(MAKEFLAGS). Note, /F is not included.

So I think that if the generated `makefile` replaced `$(MAKE)` with `$(MAKE) /$(MAKEFLAGS)` then the `/s` (slient) option would be passed down recursively.

Does that sound reasonable?

**Comment by levitte** [comment]
So, errr, if there are no options currently in effect, that would essentially mean that `$(MAKE) depend` expands to `/path/to/nmake.exe / depend`?  That makes no sense to me.  No fault of yours, the manual says so...  just makes me wonder.

But sure, this can be done.

**Comment by levitte** [comment]
Please try #5278
