### ISSUE TITLE
Question about structure BIO_BUF_MEM

### ISSUE THREAD

**Issue by davidhuziji** [openssl/openssl#5280]
Hi,

I'm a newbie of OpenSSL. I'd like to ask about the design of struct `BIO_BUF_MEM`.

I wonder why there are two `struct buf_mem_st *` pointers inside `BIO_BUF_MEM`. Besides, the read/write of BIO memory buffer seem to be a little complex. It copies `*buf` to `*readp` and sometimes even move data between `*readp` and `*buf`.

Could you please tell me why not just use a simple `void *readp` to address the current reading point in `*buf`?

**Comment by richsalz** [comment]
(Well unsigned char* not void* but the question is still valid.)  Perhaps look at commit 9fe9d0461ea4bcc42cd75a30f013fa61b5407b93 and its comments?
For more discussion, please use the openssl-users mailing list; see https://mta.openssl.org for details.
