### ISSUE TITLE
Improve TLS 1.3 error reporting

### ISSUE THREAD

**Issue by richmoore** [openssl/openssl#5289]
Matt's recent TLS 1.3 blog post states:

> If a client has TLSv1.3 enabled but no TLSv1.3 ciphersuites configured then it will immediately fail (even if the server does not support TLSv1.3) with an error message like this:
> 140399519134144:error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available:ssl/statem/statem_clnt.c:3715:No ciphers enabled for max supported SSL/TLS version

And specifies similar behaviour for servers. If we know what the problem is then surely we can produce an error that's a bit more readable - If not then expect to answer lots of questions from confused users.

**Comment by mattcaswell** [comment]
This is the standard OpenSSL error format and can't easily be changed. We *can* change the text at the end, if you have a better suggestion.

**Comment by levitte** [comment]
Well, we *can* change the error text in `crypto/err/openssl.txt`...  as long as we don't reindex the errors, those texts will remain unaltered by mkerr.pl.

(actually, I'm pondering of those texts should even change when reindexing...)

**Comment by mattcaswell** [comment]
> And specifies similar behaviour for servers. If we know what the problem is then surely we can produce an error that's a bit more readable - If not then expect to answer lots of questions from confused users.

We changed the way TLSv1.3 ciphers are configured so that they are always on by default, so this issue shouldn't happen any more.
