### ISSUE TITLE
Building for Windows with no-des, no-descbcm flags has no effect when trying to connect from client

### ISSUE THREAD

**Issue by suhasus** [openssl/openssl#5298]
Built openssl for Windows with no-des and no-descbcm. Version 1.0.2k
The list of supported ciphers shows correct (i.e. no DES or 3DES ciphers are listed). 
However when a client tries to connect with 3DES (even tried DES-CBC3-SHA) it is able to connect.

The same works correctly for Ubuntu and Centos

**Comment by richsalz** [comment]
Please show the command lines necessary to reproduce this.  Was this s_client talking to s_server?  If not, are you sure that the server program was using the right library?  Also, I don't think you can actually disable DES in 1.0.2; it's required by some of the protocol work.  So maybe the error is that the build system let you do this?

**Comment by suhasus** [comment]
Built openssl 1.0.2k for VC-WIN32 environment.
I configured openssl with -
> perl Configure VC-WIN32 no-asm no-des no-descbcm --prefix=c:/somedir/openssl
The followed instructions in https://github.com/openssl/openssl/blob/OpenSSL_1_0_2k/INSTALL.W32 to build and install openssl.
When I run '_**openssl ciphers -v**_' I do not see DES and 3DES ciphers in the list which is as expected.
My application is built in Python tornado and use python ssl. 
When I run a openssl client and try to connect to my server it does connect on DES and 3DES.
I'm running - openssl s_client -connect ECDHE-RSA-DES-CBC3-SHA 10.68.141.185 and it get connected.

Here is the list with YES and NO for DES -
Testing ECDHE-RSA-DES-CBC3-SHA...YES
Testing ECDHE-ECDSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing EDH-RSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing EDH-DSS-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing AECDH-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing ADH-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing DES-CBC3-SHA...YES
Testing EDH-RSA-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing EDH-DSS-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing ADH-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing DES-CBC-SHA...NO (sslv3 alert handshake failure)

**Comment by mattcaswell** [comment]
> I'm running - openssl s_client -connect ECDHE-RSA-DES-CBC3-SHA 10.68.141.185 and it get 

I assume you meant `openssl s_client -cipher ECDHE-RSA-DES-CBC3-SHA -connect 10.68.141.185`. I tried this (with 1.0.2k on Windows, VC-WIN32 as per your enviroment) and I get:

````
>openssl s_client -cipher ECDHE-RSA-DES-CBC3-SHA
Error with command: "-cipher ECDHE-RSA-DES-CBC3-SHA"
3468:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:.\ssl\ssl_lib.c:1383:
````

So this does appear to be working properly. My best guess is that you are picking up some old version of OpenSSL rather than the one you think you are. What does `openssl version -a` report?

**Comment by mattcaswell** [comment]
Is this still an issue or can this be closed?

**Comment by suhasus** [comment]
This can be closed. This is not an issue
