### ISSUE TITLE
Inconsistent generation logic for asm modules

### ISSUE THREAD

**Issue by vdukhovni** [openssl/openssl#5310]
In commits 10eab320a5e4b585f640b5f11d21eebaebb1814a, 184bc45f683c76531d7e065b6553ca9086564576 and eb77e8886df84526f42f566632be71d4ed373308  and perhaps other commits most of the assembly modules were modified to take an output file name.  But apparently not all.  NetBSD does cross-builds and needs to generate the Perl asm files directly bypassing Configure.  It would be good to have the logic be consistent across all architectures.

Still writing to STDOUT:
```
crypto/des/asm/desboth.pl
crypto/rc4/asm/rc4-c64xplus.pl
crypto/sha/asm/keccak1600-armv4.pl
crypto/sha/asm/keccak1600-avx2.pl
crypto/sha/asm/keccak1600-avx512.pl
crypto/sha/asm/keccak1600-avx512vl.pl
crypto/sha/asm/keccak1600-c64x.pl
```

**Comment by krytarowski** [comment]
Just in case, NetBSD's userland just has been ported to OpenSSL 1.1. We use build.sh and skip Configure.

**Comment by levitte** [comment]
Either way, consistency is good for us too, so...
I'll look into it.

**Comment by levitte** [comment]
Hmmm, I did a bit of grepping, and found this:

`crypto/des/asm/desboth.pl` is required by `crypto/des/asm/des-586.pl`, so no worry there.
`crypto/sha/asm/keccak1600-*.pl` aren't used at all for the moment, but it's true that they should conform to the same format as the rest of our asm modules.
`crypto/rc4/asm/rc4-c64xplus.pl` is the only one of those cited that is actually used today...  obviously not our most prominent platform though, or we would have caught the issue quite a while ago.

**Comment by richsalz** [comment]
I would just remove c64xplus.  a really old platform, a really bad cipher.

**Comment by dot-asm** [comment]
> I would just remove c64xplus. a really old platform

When you say "really old platform" what do you think of? Somebody told me that he thought it's Commodore 64. Is it what you think too? Thing is that it's *not* Commodore 64, but a high-performance DSP from Texas Instruments. Multi-core, GHz frequencies... Just in case fore reference, why do I program it? For clarity of mind, it work as kind of a tool for identifying and illuminating algorithm dependency chain, which helps to estimate performance on other processors [and identify anomalies].

**Comment by dot-asm** [comment]
But back to original request. I'd like to argue that it's not actually justified. In sense that if there is no reference in *our* build system to some piece of code, be it C or assembly, then no assumptions should be made about said piece of code. And if you set aside our build system, then you become ultimately responsible for tracking the working code. As for list in question. One has to recognize that Keccak1600 modules are currently work in progress. For example, if you try to compile them all and link (on most popular platform), you should get linking errors about multiple defined symbols (or link with something you didn't actually meant to link, which might still happen to work on current computer though). desboth.pl was already answered, so rc4-c64xplus.pl is arguably the only one that would exhibit inconsistent behaviour.

But I have question in the context. What is the reason for putting aside our build system? Just wondering... As for cross-compiling capabilities, I for one use it all the time. Well, not really on daily basis, rather weekly, but it does work. And I find it hard to imagine that it wouldn't on BSD...

**Comment by dot-asm** [comment]
> See, too many overlapping model numbers.

Does it mean that you too thought it was Commodore 64? I'm bad at reading subliminal messages...

>  Is it something openssl should support?

Not everything is about "should be done". I mean there are things that should be done, and there are things that can be done. And thing about latter is that you don't know how it turns out. To give another example "should openssl support risc-v"?

**Comment by dot-asm** [comment]
> I'd like to argue that it's not actually justified.

I naturally meant that not everything in list is justified. But since absolute majority can be viewed unjustified, it's probably not inappropriate to project it at whole request :-)

**Comment by richsalz** [comment]
Yes, I thought it was Commodore.  I don't understand what your "putting aside the build system" means.  Perhaps join the discussion on openssl-project?

**Comment by vdukhovni** [comment]
Replying to Andy asking about why NetBSD bypasses Configure:

NetBSD can cross-build a reproducible build of the full base system for
any supported architecture from any supported architecture (and even from
Windows) by first building the tool-chain, and then using that tool-chain
to build the entire system for the target architecture.  The entire system
has a highly stylized set of "make" files that achieve the required consistency.

So our Configure simply does not fit into that process.  The OpenSSL in the base
NetBSD system is built directly from the source files, and Christos is just asking
for a bit more consistency in the call interface of the Perl modules.  I think it
is something we ourselves can benefit from (per Richard Levitte) so I think this
should be done.

**Comment by vdukhovni** [comment]
> @richsalz crypto/des/asm/desboth.pl is required by crypto/des/asm/des-586.pl, so no worry there.

It would also help if modules that were only `required` by other modules and  do not directly produce asm code were called `something.pm` rather than `something.pl`.  I know it is not something we need, but I think that it is good to make it easier for downstream distributions to bundle OpenSSL (rather than consider alternatives). So I am not calling out *bugs*, rather asking for I think are reasonable accommodations, that perhaps are also likely to make our own code somewhat easier to work with.

**Comment by dot-asm** [comment]
> So our Configure simply does not fit into that process.

But you ought to have package-specific Makefiles, and on per-target-processor basis. Right? So where does OpenSSL's one come from? You generate it, right? And question is what is it that disqualifies Configure for the job? Especially now, when it generates single "flat" Makefile [potentially in separate build directory]...

>  I think this [harmonization of perlasm command line options] should be done.

I didn't say that it won't be done. Only implied that you have to leave some room for things like work in progress. And that you can't rely simply on list of files, as it kind of sounds that you do... Specifically as far as Keccak1600 modules go, I'm acutely aware what needs to be done(*) and will do it [soon enough]. BTW, another example when it would be inappropriate to rely on list of files are poly1305_base2_44.c and poy1305_ieee754.c, which are just reference implementations, not to be used in production build. Well, one can argue that there is no place for them in release tar-ball, but on the other hand build system "knows" what to do and not do...

(*) Just in case, what needs to be done is not limited to command line option handling. ISA-extension-specific subroutines will be renamed, they will be adjusted to work on non-ELF systems, Windows SEH handlers will be added, ...

**Comment by zoulasc** [comment]
Just to be clear: NetBSD generates the per-architecture files from perl once; when we import a new openssl or as needed. We automate this using make:
https://nxr.netbsd.org/xref/src/crypto/external/bsd/openssl/lib/libcrypto/arch/x86_64/Makefile

It helps when the perl generators have a consistent command line api and naming...

**Comment by dot-asm** [comment]
> Just to be clear: NetBSD generates the per-architecture files from perl once;

And question still is why not each time :-) Well, per-version-import should work, as it does have references to what's used and what is not.

> https://nxr.netbsd.org/xref/src/crypto/external/bsd/openssl/lib/libcrypto/arch/x86_64/Makefile

This kind of asks for more questions than provides answers. This request is about making scripts threat last command line argument as file name, while referred rule relies on code being emitted on standard output. So which one is it? Related question how does it work for sha256-x86_64.s. Presumably it's generated by original rule in Makefile generated by Configure and rules in question simply leaves it as it is. In other words original rule generated by Configure apparently worked just fine. And it looks like most of them would. The *only* one that might need a fix-up is x86_64cpuid. Or does it actually have to? Is it actually so that there is no .hidden on NetBSD? Because if there is, you won't need to PLT the call. [In such case you won't need to #include <asm.h>. And as for rdseed thing, it's handled in x86_64-xlate.pl by encoding with .byte, so it shouldn't be even visible to assembler. [Which asks for question if x86_64-xlate.pl is out of sync/date?] ...

**Comment by vdukhovni** [comment]
In answer to "which is it", the answer is: consistency.  The Makefile for 1.0.2 assumed stdout, the Makefile for 1.1.0 is changing to take filenames, because that's what the 1.1.0 code is (mostly) doing.

As for whether NetBSD could use "Configure"? There may be issues with the reproducible build in terms of timestamps, or other issues relating to cross-compilation, but for that I have to leave the detailed answer to Christos.  Suffice it to say that the NetBSD build is avoiding Configure for various reasons, probably legitimate, and where it makes sense to help them (especially if it makes our own practices more predicable), we probably should make the effort.

**Comment by krytarowski** [comment]
I've not audited this, but we had commits such as: https://github.com/NetBSD/src/commit/75b561e1636a8d5c995a5b56c48592a5b19a3816

"Restore pic and sse2 enabled code to make libcrypto works as before."

This might be an inspiration for upstream.

**Comment by richsalz** [comment]
I'd like to understand why NetBSD cannot (or just does not) use Configure, and would rather address those root issues first as they are more likely to be widely useful.  Their reasons may be legitimate, or not, but it's also not clear we should spend any effort on avoiding Configure, just like we don't spend any effort on CMake, etc.  Hopefully Christos can respond here, or in email that you can forward.

**Comment by krytarowski** [comment]
Basically we use uniform reimplementation of build rules through BSD-style Makefiles. Usually configure scripts don't work well as we are heading for aggressive crossbuildability from any POSIX-like environment to any target NetBSD architecture with minimal dependencies (C89, sh(1), cc(1), ...).

There might be some exceptions but best to wait for feedback from Christos who did the upgrade.

**Comment by levitte** [comment]
Well, if you run your own build system, you can of course expect our support to be accordingly lacking. After all, we can't stop you, and if you find that easier to deal with (even if we can't quite understand it), good for you! 

That being said, this case was rather simple and a good catch, so fixing the issue was possible, and justifiable. I see no reason not to simply say "thank you".

**Comment by levitte** [comment]
Also, considering what @dot-asm says about the keccak stuff, I would simply not try to build it if I was you.

**Comment by vdukhovni** [comment]
The reasons why Configure is not used are justifiably interesting, but I don't think they stand in the way of addressing this issue.  Making the Perl asm file CLI more uniform is also in our own interest. So we should still do it even if NetBSD could use Configure, but is too lazy to figure out how.  Of course I rather suspect that bypassing Configure (in building the base system, Configure is OK IIRC for pkgsrc) is necessary for various rather technical reasons, that might give us insight into OS platform release engineering, but probably won't shed much light on OpenSSL.  OpenSSL is likely not the the only upstream source whose build system is bypassed, the same likely goes for Heimdal, ...

**Comment by vdukhovni** [comment]
It may turn out that indeed this issue ends up just documenting our ASM perl module CLI for the record. If all currently active modules already do the right thing. That's great. In that case I'd simply ask that we explicitly distinguish between the ".pl" and ".pm" files, so that it is more clear which is which when reviewing interface consistency.

**Comment by levitte** [comment]
> It would also help if modules that were only required by other modules and do not directly produce asm code were called something.pm rather than something.pl

Agreed, and desboth.pl is a perfect candidate for such a rename.  We have, after all, moved on from the age of Perl 3 and Perl 4 ;-)

**Comment by krytarowski** [comment]
We can still build OpenSSL from pkgsrc, but this one is using the regular upstream Configure.

Upstream should rather look for patches added to our downstream sources, we used to have some enhancements like (if I recall correctly) optimized m68k assembly snippets for some functions. I'm personally not involved in OpenSSL to establish the cooperation, but best to keep local patches to minimum.

**Comment by zoulasc** [comment]
The reason we cannot use Configure or build the assembly files every time is because we don't distribute perl in the base software.

**Comment by richsalz** [comment]
Interesting.   Thanks for the explanation.

**Comment by dot-asm** [comment]
> we cannot use Configure or build the assembly files every time is because we don't distribute perl in the base software.

But you do have to have perl when you prepare the base source package, right? Ought to. And you should be able to use Configure then, right? Do you? Do you use generated Makefile? What if there was a target that generated all the .S/.s files? I mean what if at the time you prepare the base source package you would execute Configure followed by 'make assembly'(*). And if you wanted to fix them up, [which I still see no real reason for,] you would look for generated files instead of .pl. As already implied, trouble is that looking for .pl files is error-prone, you can't rely on it. [And once again, it doesn't mean that command line option handling won't be harmonized, it only means that you shouldn't rely on list of all .pl files even if they all are harmonized.]

(*) Also note that Configure can generate Makefile in directory other than source directory. So that you can create per-target-platform directories with separate Makefiles and pre-generated assembly modules.

**Comment by levitte** [comment]
@dot-asm mentions `make assembly`, which doesn't exist, *BUT* `make build_all_generated` does...

**Comment by levitte** [comment]
I just reminded myself that `make build_all_generated` is  only in 1.1.1 (not yet released), not in 1.1.0.  But we *are* talking 1.1.1 here, aren't we?  Considering you mentioned keccak stuff, which doesn't exist in 1.1.0, that is...

**Comment by dot-asm** [comment]
> `make assembly`, which doesn't exist

It was rather an example to illuminate the possibility/suggestion.

**Comment by dot-asm** [comment]
> But we are talking 1.1.1 here, aren't we?

Well, I for one would actually argue that it wouldn't be inappropriate to backport build_all_generated to 1.1.0. Because cooperation with dist vendors is meaningful thing to do. And if they choose to stick with 1.1.0 for a bit longer, we shouldn't be opposed to helping.

**Comment by levitte** [comment]
I agree

**Comment by zoulasc** [comment]
Yes, having an option to build all generated files would be helpful, but we would also need at list a way to display a list of all the generated files so that we know what was generated.

**Comment by levitte** [comment]
`grep ^GENERATED Makefile`

**Comment by dot-asm** [comment]
Just to illuminate the possibility. @zoulasc, consider following sequence (which you can exercise *now*, though only with master):
```
mkdir archx
cd archx
../openssl-1.1.x/Configure archx [--cross-compile-prefix=some-odd-stuff-]
make build_all_generated
```
What is it that would be missing in archx for your purposes?  If nothing is missing, then just pack it. If something is missing, then let's figure it out...

**Comment by levitte** [comment]
(reopened, 'cause I'm not sure we've fixed everything that was brought up here)

**Comment by dot-asm** [comment]
It was noted that build_all_generated can produce erroneous result when "archx" is not x86[_64]. This was corrected. build_all_generated was backported to 1.1.0 (though just mentioned fix for the moment of this writing is pending in #5581). If no feedback is provided, then I suppose it could be closed...

**Comment by mattcaswell** [comment]
> (reopened, 'cause I'm not sure we've fixed everything that was brought up here)

@levitte - I'm not sure what is still outstanding for this issue. Can you clarify?

**Comment by levitte** [comment]
Well, there was @dot-asm's overhaul the day after I reopened, and then there was #6079 that got merged last week.  I do think that *now* we have resolved everything that was a concern, directly or indirectly.  Thanks for the reminder, closing now.
