### ISSUE TITLE
Add support for bcrypt KDF

### ISSUE THREAD

**Issue by hifi** [openssl/openssl#5323]
Currently no crypto library supports the OpenSSH specific bcrypt KDF which is used with new passphrase protected keys. Only ED25519 private keys default to it at this point but the file format supports all existing key types (DSA, RSA and ECDSA).

There are more than one project that could benefit from that support. Any library/program that works with SSH keys needs to be able to decrypt and encrypt such keys (like libssh) and currently the solution has been to embed the needed code from OpenBSD or OpenSSH portable (bcrypt_pbkdf.c and blowfish.c).

Would it be possible to get this into OpenSSL?

https://github.com/openssh/openssh-portable/blob/master/openbsd-compat/bcrypt_pbkdf.c

**Comment by kroeckx** [comment]
We would like to move to only implementing things that have been standardized. bcrypt doesn't seem to fit that. rfc8018 only mentions PBKDF1 and PBKDF2, recommending PBKDF2. They seem to have modified PBKDF2.

**Comment by hifi** [comment]
That is correct, their implementation is a modified one. If it's a dead end, please close this as WONTFIX for future generations to find this. Thanks.

**Comment by richsalz** [comment]
Okay, closing.  Thanks for checking into it!
