### ISSUE TITLE
Translation into Spanish language

### ISSUE THREAD

**Issue by michaelizer** [openssl/openssl#5325]
Greetings, I would like to contribute to the project by translating it into Spanish. Spanish is my native language so don't panic, but a lot of Spanish speakers are still limited by the language so this is primarily to help them.

Thanks in advance and for your time. Keep up the great work.

**Comment by richsalz** [comment]
That sounds really great, thanks!

**Comment by michaelizer** [comment]
Should I open a new branch for the Spanish translations?

**Comment by richsalz** [comment]
What are you translating, the POD pages?
At any rate, you should create your own branch in your own repo (keep it pushed on github) with translations.

**Comment by michaelizer** [comment]
Understood, thank you very much

**Comment by michaelizer** [comment]
>What are you translating, the POD pages?

Yes, I wanted to start with the main pod files like [README](https://github.com/openssl/openssl/blob/master/README) or [CONTRIBUTING](https://github.com/openssl/openssl/blob/master/CONTRIBUTING) and then go deeper into other branches, what do you think?

Also (Optional) I could change them to .md for esthetic purposes, but that's your call.

**Comment by richsalz** [comment]
When I said pod files, I meant the manpages in the doc subdirectory.  I am sure the files you are working on are very useful to translate as well.  I don't know about markdown, perhaps ask on the openssl-project mailing list (https://mta.openssl.org to join)

**Comment by michaelizer** [comment]
>When I said pod files, I meant the manpages in the doc subdirectory.

Got it

And I'm sorry, let's not complicate with markdown, I won't change the type of the files.

**Comment by nickthetait** [comment]
I'd like to offer any help on the specifics of translation. My Spanish is pretty ok, native English speaker, and already have familiarity with the project. Don't be afraid to spam me with notifications in this thread 😄
