### ISSUE TITLE
TLS 1.3 CCS sending does not follow D.4 Middlebox Compatibility Mode

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#5331]
Section D.4 of [draft-ietf-tls-tls13-23.txt](https://tools.ietf.org/html/draft-ietf-tls-tls13-23) states:
```
   -  The server sends a dummy change_cipher_spec record immediately
      after its first handshake message.  This may either be after a
      ServerHello or a HelloRetryRequest.
```

1d0c08b49 sends CCS right before Finished (5th message _after_ ServerHello), causing the connection to not be compatible with middleboxes

**Comment by mattcaswell** [comment]
How are you testing that? I don't see that behaviour. I just ran an s_server/s_client connection through wireshark for a simple 1-RTT handshake and I see this:

````
ClientHello
                           ServerHello
                           CCS
                           ApplicationData
                           ApplicationData
                           ApplicationData
                           ApplicationData
CCS
ApplicationData
````

**Comment by tomato42** [comment]
🤦‍ mixed up client and server side packets, sorry
