### ISSUE TITLE
Biased returns from OPENSSL_ia32_RDRAND/RDSEED

### ISSUE THREAD

**Issue by bdonlan** [openssl/openssl#5340]
Currently, OPENSSL_ia32_RDRAND/RDSEED use a zero return to report an unsuccessful call to RDRAND/RDSEED. However, zero is an acceptable (but somewhat rare) return value from RDRAND and RDSEED. If RDRAND/RDSEED return zero but success, then the [assembly code for OPENSSL_ia32_RDRAND/RDSEED](https://github.com/openssl/openssl/blob/79337628702dc5ff5570f02d6b92eeb02a310e18/crypto/x86_64cpuid.pl#L440) replaces this with the remaining retry count (for some reason), which is then used as the random number. This biases the RNG slightly towards values 1-8, since the default retry count is 8 times. In practice, since RDRAND almost never fails, this roughly doubles the frequency that a value of 8 is returned. 
 
This issue is more significant in 32-bit builds, as the probability of a zero return is 2^-32 instead of 2^-64.

**Comment by noloader** [comment]
I believe this issue was reported in the old RT. I seem to recall is was a *"won't fix"* because the bias is negligible.

**Comment by dot-asm** [comment]
Resolved in #5342.
