### ISSUE TITLE
Last byte repeated in OPENSSL_ia32_RDRAND/RDSEED_bytes

### ISSUE THREAD

**Issue by bdonlan** [openssl/openssl#5341]
When the rdcpu entropy source is enabled, openssl calls the OPENSSL_ia32_RDRAND_bytes (and _RDSEED_bytes) functions to obtain entropy. These functions are implemented in perlasm, in https://github.com/openssl/openssl/blob/79337628702dc5ff5570f02d6b92eeb02a310e18/crypto/x86_64cpuid.pl#L455
 
When these functions are invoked with a buffer length that is not divisible by 8, they obtain a 64-bit sample from RDRAND or RDSEED, then enter a loop where they write one byte at a time to the memory buffer. However, this loop shifts the wrong register - it copies a value from the low byte of %r10, then shifts %r8 (otherwise unused in this function) right by 8 bits (see line 485). As a result, if a buffer of 8n + m bytes is passed, where m is between 2 and 7 bytes inclusive, the last m bytes will all be the same value. 
 
Note that, in practice, this function seems to be invoked with a buffer size of 16 bytes, avoiding this issue. Additionally, this function appears to be unused on version 1.1.0g; the entropy source code calling _bytes is added in the master branch, so I assume it's planned to be used in 1.1.1.

A standalone application demonstrating this bug can be found here: https://gist.github.com/bdonlan/a6b8fce7f6175bd695254b7aef438199

**Comment by dot-asm** [comment]
Resolved in #5342.
