### ISSUE TITLE
Mingw64 compile failure

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#5347]
On latest master with `./config -d --strict-warnings` on mingw64:

````
gcc  -I. -Icrypto/include -Iinclude -DDSO_WIN32 -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1_1\"" -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m64 -Wall -g -O0 -D_MT  -DDEBUG_UNUSED -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wswitch -Wsign-compare -Wmissing-prototypes -Wshadow -Wformat -Wtype-limits -Wundef -Werror -Wmisleading-indentation -D_WINDLL -MMD -MF crypto/asn1/x_long.d.tmp -MT crypto/asn1/x_long.o -c -o crypto/asn1/x_long.o crypto/asn1/x_long.c
crypto/asn1/x_int64.c: In function 'uint64_print':
crypto/asn1/x_int64.c:105:34: error: unknown conversion type character 'j' in format [-Werror=format=]
         return BIO_printf(out, "%jd\n", **(int64_t **)pval);
                                  ^
crypto/asn1/x_int64.c:105:32: error: too many arguments for format [-Werror=format-extra-args]
         return BIO_printf(out, "%jd\n", **(int64_t **)pval);
                                ^~~~~~~
crypto/asn1/x_int64.c:106:30: error: unknown conversion type character 'j' in format [-Werror=format=]
     return BIO_printf(out, "%ju\n", **(uint64_t **)pval);
                              ^
crypto/asn1/x_int64.c:106:28: error: too many arguments for format [-Werror=format-extra-args]
     return BIO_printf(out, "%ju\n", **(uint64_t **)pval);
                            ^~~~~~~
cc1.exe: all warnings being treated as errors
make[1]: *** [Makefile:1275: crypto/asn1/x_int64.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from crypto/asn1/ameth_lib.c:10:0:
./e_os.h:310:8: error: "_MSC_VER" is not defined, evaluates to 0 [-Werror=undef]
 #  if (_MSC_VER >= 1310)
        ^~~~~~~~
cc1.exe: all warnings being treated as errors
make[1]: *** [Makefile:963: crypto/asn1/ameth_lib.o] Error 1
make[1]: Leaving directory '/home/Matt/openssl'
make: *** [Makefile:139: all] Error 2
````

**Comment by levitte** [comment]
Does this make a difference?

``` C
# if defined(_MSC_VER) && (_MSC_VER >= 1310)
```

I'm seeing the same kind of construct elsewhere in e_os.h

**Comment by dot-asm** [comment]
There is reason for why .travis.yml uses -Wno-pedantic-ms-format with mingw targets. Basically there are more reasons for why --strict-warnings wouldn't work with mingw64, so just don't use it. Or trim it down with -Wno-this -Wno-that...

**Comment by dot-asm** [comment]
Well, it's not unreasonable to address _MSC_VER thing, but other than that.... just don't use it.

**Comment by dot-asm** [comment]
Just to clarify. Elimination of warnings [other than format] in 64-bit Windows conflicts with goal of maintaining binary compatibility in minor releases. That's essentially why it's not exercised in same extent as on the other platform.

**Comment by dlegaultbbry** [comment]
For the printf undefined format specifiers, -D__USE_MINGW_ANSI_STDIO=1 can be used make them compliant on mingw. size_t printing with %zu also generates an error without this.

**Comment by richsalz** [comment]
Thanks, but it's not `printf` that is generating complaints, it is *our* `BIO_printf` routine.

**Comment by bernd-edlinger** [comment]
You could try to change the attribute on BIO_printf to something like
`((__format__(__gnu_printf__, 2, 3)))`

**Comment by dot-asm** [comment]
There already is similar precedent, for MacOS, which spells !defined(__APPLE__) in __bio_h__attr__ condition. However! Once again, it's not exclusively about BIO_printf. You'll get past this warning just find find others... In the essence it would be same story as in #4832. Warning-free compilation is of course nice, but just mechanically masking warnings would arguably make more damage than good.

**Comment by mattcaswell** [comment]
This seems to be fixed.
