### ISSUE TITLE
Test 90-test_fuzz.t fails on Windows

### ISSUE THREAD

**Issue by w3stling** [openssl/openssl#5349]
Test 90-test_fuzz.t fails for OpenSSL 1.1.0g. That test also fails in latest from branch OpenSSL_1_1_0-stable.
OpenSSL 1.1.0f have no failing tests.

Building on Windows 7 with Visual Studio 2013 compiler.

**Build commands:**

```
D:\> "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\vcvars64.bat"
D:\> perl Configure VC-WIN64A --prefix=D:\openssl-OpenSSL_1_1_0g-64bit-release-DLL-VS2013
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g>nmake
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g>nmake test

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\nmake.exe" depend && "C:\Program Files (x86)\M
icrosoft Visual Studio 12.0\VC\BIN\amd64\nmake.exe" _tests

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

mkdir .\test\test-runs
set SRCTOP=.
set BLDTOP=.
set RESULT_D=.\test\test-runs
set PERL=C:\Perl64\bin\perl.exe
set OPENSSL_DEBUG_MEMORY=on
"C:\Perl64\bin\perl.exe" ".\test\run_tests.pl"
test\recipes\01-test_abort.t ............ ok
test\recipes\01-test_sanity.t ........... ok
test\recipes\01-test_symbol_presence.t .. ok
test\recipes\02-test_ordinals.t ......... ok
test\recipes\03-test_exdata.t ........... ok
test\recipes\03-test_ui.t ............... ok
test\recipes\04-test_pem.t .............. ok
test\recipes\05-test_bf.t ............... ok
test\recipes\05-test_cast.t ............. ok
test\recipes\05-test_des.t .............. ok
test\recipes\05-test_hmac.t ............. ok
test\recipes\05-test_idea.t ............. ok
test\recipes\05-test_md2.t .............. skipped: md2 is not supported by this OpenSSL build
test\recipes\05-test_md4.t .............. ok
test\recipes\05-test_md5.t .............. ok
test\recipes\05-test_mdc2.t ............. ok
test\recipes\05-test_rand.t ............. ok
test\recipes\05-test_rc2.t .............. ok
test\recipes\05-test_rc4.t .............. ok
test\recipes\05-test_rc5.t .............. skipped: rc5 is not supported by this OpenSSL build
test\recipes\05-test_rmd.t .............. ok
test\recipes\05-test_sha1.t ............. ok
test\recipes\05-test_sha256.t ........... ok
test\recipes\05-test_sha512.t ........... ok
test\recipes\05-test_wp.t ............... ok
test\recipes\10-test_bn.t ............... ok
test\recipes\10-test_exp.t .............. ok
test\recipes\15-test_dh.t ............... ok
test\recipes\15-test_dsa.t .............. ok
test\recipes\15-test_ec.t ............... ok
test\recipes\15-test_ecdsa.t ............ ok
test\recipes\15-test_genrsa.t ........... ok
test\recipes\15-test_rsa.t .............. ok
test\recipes\15-test_rsapss.t ........... ok
test\recipes\20-test_enc.t .............. ok
test\recipes\20-test_passwd.t ........... ok
test\recipes\25-test_crl.t .............. ok
test\recipes\25-test_d2i.t .............. ok
test\recipes\25-test_pkcs7.t ............ ok
test\recipes\25-test_req.t .............. ok
test\recipes\25-test_sid.t .............. ok
test\recipes\25-test_verify.t ........... ok
test\recipes\25-test_x509.t ............. ok
test\recipes\30-test_afalg.t ............ skipped: test_afalg not supported for this build
test\recipes\30-test_engine.t ........... ok
test\recipes\30-test_evp.t .............. ok
test\recipes\30-test_evp_extra.t ........ ok
test\recipes\30-test_pbelu.t ............ ok
test\recipes\40-test_rehash.t ........... skipped: test_rehash is not available on this platform
test\recipes\60-test_x509_store.t ....... skipped: test_rehash is not available on this platform
test\recipes\70-test_asyncio.t .......... ok
test\recipes\70-test_bad_dtls.t ......... ok
test\recipes\70-test_clienthello.t ...... ok
test\recipes\70-test_packet.t ........... ok
test\recipes\70-test_sslcbcpadding.t .... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_sslcertstatus.t .... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_sslextension.t ..... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_sslmessages.t ...... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_sslrecords.t ....... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_sslsessiontick.t ... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_sslskewith0p.t ..... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_sslvertol.t ........ skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_tlsextms.t ......... skipped: TLSProxy isn't usable on MSWin32
test\recipes\70-test_verify_extra.t ..... ok
test\recipes\80-test_ca.t ............... ok
test\recipes\80-test_cipherlist.t ....... ok
test\recipes\80-test_cms.t .............. ok
test\recipes\80-test_ct.t ............... ok
test\recipes\80-test_dane.t ............. ok
test\recipes\80-test_dtls.t ............. ok
test\recipes\80-test_dtlsv1listen.t ..... ok
test\recipes\80-test_ocsp.t ............. ok
test\recipes\80-test_pkcs12.t ........... skipped: Non-Greek system locale
test\recipes\80-test_ssl_new.t .......... ok
test\recipes\80-test_ssl_old.t .......... ok
test\recipes\80-test_ssl_test_ctx.t ..... ok
test\recipes\80-test_sslcorrupt.t ....... ok
test\recipes\80-test_tsa.t .............. ok
test\recipes\80-test_x509aux.t .......... ok
test\recipes\90-test_async.t ............ ok
test\recipes\90-test_bio_enc.t .......... ok
test\recipes\90-test_bioprint.t ......... ok
test\recipes\90-test_constant_time.t .... ok
test\recipes\90-test_fuzz.t ............. Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 10/10 subtests
test\recipes\90-test_gmdiff.t ........... ok
test\recipes\90-test_heartbeat.t ........ skipped: heartbeats is not supported by this OpenSSL build
test\recipes\90-test_ige.t .............. ok
test\recipes\90-test_memleak.t .......... ok
test\recipes\90-test_p5_crpt2.t ......... ok
test\recipes\90-test_secmem.t ........... ok
test\recipes\90-test_shlibload.t ........ ok
test\recipes\90-test_srp.t .............. ok
test\recipes\90-test_sslapi.t ........... ok
test\recipes\90-test_threads.t .......... ok
test\recipes\90-test_v3name.t ........... ok

Test Summary Report
-------------------
test\recipes\90-test_fuzz.t           (Wstat: 2560 Tests: 10 Failed: 10)
  Failed tests:  1-10
  Non-zero exit status: 10
Files=95, Tests=498, 6964 wallclock secs ( 1.78 usr +  0.77 sys =  2.54 CPU)
Result: FAIL
NMAKE : fatal error U1077: 'C:\Perl64\bin\perl.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\nmake.exe"' : return code
'0x2'
Stop.


**Compiler version:**
D:\>cl -v
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.


**Perl version:**
D:\>perl -v

This is perl 5, version 24, subversion 2 (v5.24.2) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2017, Larry Wall

Binary build 2403 [403863] provided by ActiveState http://www.ActiveState.com
Built Aug 25 2017 05:28:15

```

**Comment by richsalz** [comment]
Please do the equivalent to this command, in order to get verbose debugging output.
```
make TESTS=test_fuzz V=1 tests
```
(I don't know how to translate that into nmake syntax)

perl is just complaining that the test program is exiting with a failure code.  nothing's wrong with perl or the scripts.

**Comment by dot-asm** [comment]
It's `make test`, not `make tests`, i.e. no s, and with nmake it's exactly same, just nmake instead of make.

**Comment by dot-asm** [comment]
One has to keep in mind that V=1 output from test_fuzz is very long. If all of them fail, then it's something fundamentally wrong, most likely with user environment. Otherwise search for "not ok". The fact that other tests worked *might* be an indication of a compiler bug...

**Comment by w3stling** [comment]
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g>nmake TESTS=test_fuzz V=1 test

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\nmake.exe" depend && "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\nmake.exe" _tests

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

mkdir .\test\test-runs
A subdirectory or file .\test\test-runs already exists.
        set SRCTOP=.
        set BLDTOP=.
        set RESULT_D=.\test\test-runs
        set PERL=C:\Perl64\bin\perl.exe
        set OPENSSL_DEBUG_MEMORY=on
        "C:\Perl64\bin\perl.exe" ".\test\run_tests.pl" test_fuzz
test\recipes\90-test_fuzz.t ..
1..10
# Subtest: Fuzzing asn1
    1..1135
Can't spawn "..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0059b3b544460f79c53cfedfccdf03990cece488": No error at test\testlib/OpenSSL/Test.pm line 391.
..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0059b3b544460f79c53cfedfccdf03990cece488 => 255
    not ok 1
    #   Failed test at test\recipes\90-test_fuzz.t line 37.
Can't spawn "..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0084f61ecf0b891ba136d5cd17b74e59da3bc736": No error at test\testlib/OpenSSL/Test.pm line 391.
..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0084f61ecf0b891ba136d5cd17b74e59da3bc736 => 255
    not ok 2
    #   Failed test at test\recipes\90-test_fuzz.t line 37.
Can't spawn "..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0096661704ea09219fd9d4300a505c03184b4011": No error at test\testlib/OpenSSL/Test.pm line 391.
..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0096661704ea09219fd9d4300a505c03184b4011 => 255
    not ok 3
    #   Failed test at test\recipes\90-test_fuzz.t line 37.
Can't spawn "..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\00bd8b434ddb8a36d8a48214ab119dc5f048d498": No error at test\testlib/OpenSSL/Test.pm line 391.
..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\00bd8b434ddb8a36d8a48214ab119dc5f048d498 => 255
    not ok 4
    #   Failed test at test\recipes\90-test_fuzz.t line 37.
Can't spawn "..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0136e7416e1c2e6b49e6bc8677dc03317b071a83": No error at test\testlib/OpenSSL/Test.pm line 391.
..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0136e7416e1c2e6b49e6bc8677dc03317b071a83 => 255
    not ok 5
    #   Failed test at test\recipes\90-test_fuzz.t line 37.
Can't spawn "..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\013a6665b1fa416058d87dba3b6849710d81db19": No error at test\testlib/OpenSSL/Test.pm line 391.
..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\013a6665b1fa416058d87dba3b6849710d81db19 => 255
    not ok 6
    #   Failed test at test\recipes\90-test_fuzz.t line 37.
...
...

**Comment by w3stling** [comment]
I can run the asn1-test.exe command manually from command line. And I am running it from an command prompt with admin rights.

D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\test\test-runs>..\..\fuzz\asn1-test.exe ..\..\fuzz\corpora\asn1\0059b3b544460f79c53cfedfccdf03990cece488

**Comment by dot-asm** [comment]
In other words script fails to start programs in fuzz subdirectory. This reminds me the case when dlls were not copied to fuzz directory, and fuzz executables were picking up other incompatible dlls, and failed to start like described, but that was resolved... Can you double-check that you have OpenSSL dlls in fuzz subdirectory? Though fact that you can start it manually suggests that it should work... Anyway, if dlls are there, then it ought to be something with your environment. How executable searches for dll is subject to tweaking, and it might happen that failure to start from script is how it's supposed to work on *your* system. Some "execution policy" module in the way perhaps?

**Comment by levitte** [comment]
Side note for @dot-asm: both `test` and `tests` are valid testing targets.   They do the same thing, it's just a conveniance that both exist.

**Comment by dot-asm** [comment]
> both test and tests are valid testing targets

Live and learn :-) Thanks!

**Comment by w3stling** [comment]
> Can you double-check that you have OpenSSL dlls in fuzz subdirectory?

No DLLs in directory D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\fuzz

`D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g>dir /s /b *.dll`
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\libcrypto-1_1-x64.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\libssl-1_1-x64.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\apps\libcrypto-1_1-x64.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\apps\libssl-1_1-x64.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\engines\capi.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\engines\dasync.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\engines\ossltest.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\engines\padlock.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\test\libcrypto-1_1-x64.dll
D:\Downloads\1_1_0g\openssl-OpenSSL_1_1_0g\test\libssl-1_1-x64.dll

After copying libcrypto-1_1-x64.dll and libssl-1_1-x64.dll to fuzz directory test passes!

..\..\fuzz\ct-test.exe ..\..\fuzz\corpora\ct\fdd9076226c20fed2175e5db9439c8d7a34e39af => 0
    ok 119
..\..\fuzz\ct-test.exe ..\..\fuzz\corpora\ct\fe9f6093c7583ad2f0d0336dd20a95b6a203328c => 0
    ok 120
ok 10 - Fuzzing ct
ok
All tests successful.
Files=1, Tests=10, 813 wallclock secs ( 1.15 usr +  0.08 sys =  1.23 CPU)
Result: PASS

Thanks!

**Comment by levitte** [comment]
I cannot say what went wrong.  Going back to the `makefile` template, I can see that the DLLs are normally copied to the fuzz directory directly after they are created.

**Comment by dot-asm** [comment]
> Going back to the makefile template, I can see that the DLLs are normally copied to the fuzz directory directly after they are created.

But apparently not in 1.1.0. It looks like it wasn't backported...

**Comment by levitte** [comment]
Good point.  I've re-opened #4171 for that reason

**Comment by dot-asm** [comment]
Fix was backported, closing.
