### ISSUE TITLE
Build break: Windows: no-engine

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#536]
Configure no-engine VC-WIN32 breaks the build because the following functions are still exported in libeay32.def:
TS_CONF_set_crypto_device
TS_CONF_set_default_engine

linker error:
LIBEAY32.def : error LNK2001: unresolved external symbol TS_CONF_set_crypto_device
LIBEAY32.def : error LNK2001: unresolved external symbol TS_CONF_set_default_engine

**Comment by matbech** [comment]
fixed with https://github.com/openssl/openssl/commit/8e237299b0357091dae8e7175cbfa11f4fbc98c7

**Comment by levitte** [comment]
A fix has been pushed just now, so this ticket can be closed.

**Comment by levitte** [comment]
And this page didn't update before I sent my comment...  ah well ;)
