### ISSUE TITLE
Trouble verifying root certificates in 1.1.1-pre1

### ISSUE THREAD

**Issue by sfackler** [openssl/openssl#5362]
The following program fails to verify the root certificate when built against the 1.1.1-pre1 dist, but succeeds against 1.1.0 (and 1.0.2 with adjustments to initialize the library and use SSLv23_method):

```c
#include <assert.h>
#include <openssl/bio.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <stdio.h>

int main() {
    SSL_CTX *ctx = SSL_CTX_new(TLS_method());
    assert(ctx);
    int r = SSL_CTX_load_verify_locations(ctx, "/etc/ssl/cert.pem", NULL);
    assert(r);
    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);

    SSL *ssl = SSL_new(ctx);
    assert(ssl);

    BIO *bio = BIO_new_connect("google.com:443");
    assert(bio);

    SSL_set_bio(ssl, bio, bio);

    r = SSL_connect(ssl);
    assert(r == -1);

    int error = SSL_get_error(ssl, r);
    assert(error == SSL_ERROR_SSL);

    ERR_print_errors_fp(stderr);

    long verify = SSL_get_verify_result(ssl);
    printf("%s\n", X509_verify_cert_error_string(verify));
}
```

```
$ gcc -L $HOME/openssl-1.1.1/lib -I $HOME/openssl-1.1.1/include test.c -lssl -lcrypto -lpthread -ldl
139943886673728:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1903:
self signed certificate
```

```
$ gcc -L $HOME/openssl-1.1.0/lib -I $HOME/openssl-1.1.0/include test.c -lssl -lcrypto -lpthread -ldl
$ ./a.out
a.out: test.c:23: main: Assertion `r == -1' failed.
```

Both libraries were built from source with:

```
$ ./config --prefix=$HOME/openssl-1.1.1 --debug no-shared
$ make -j4
$ make install_sw
```

**Comment by sfackler** [comment]
If I disable TLSv1.3 it appears to successfully verify, interestingly.

**Comment by mattcaswell** [comment]
This seems to be related to the handling of SNI. In the above code snippet you are not setting any and Google is responding with a dummy certificate:

````
        Subject: OU = "No SNI provided; please fix your client.", CN = invalid2.invalid
````

What is interesting is that, even though TLSv1.2 is being negotiated, Google seems to be behaving differently in the presence of a TLSv1.3 ClientHello, i.e. if we send a TLSv1.2 ClientHello without SNI then Google negotiates TLSv1.2 and responds with a "real" certificate, but if we send a TLSv1.3 ClientHello then Google negotiates TLSv1.2 and responds with the invalid certificate.

Presumably this is a deliberate Google policy to encourage proper sending of SNI data. Perhaps @davidben can comment.

*Possibly* we could change OpenSSL to refuse to even attempt a connection if TLSv1.3 is active but no SNI has been set (in much the same way as we refuse to create a connection if no TLSv1.3 ciphersuites are available). That is likely to hurt a lot of people though, and is harder to fix than the ciphersuite issue (which can often be done through a simple configuration change) :-(

**Comment by richsalz** [comment]
SNI is required in TLS 1.3 so failing to connect (on our side) might be reasonable.

**Comment by mattcaswell** [comment]
> SNI is required in TLS 1.3 so failing to connect (on our side) might be reasonable.

Do you have a reference for that? I don't see it.

In section 9.2 it is listed as "mandatory to implement", but it does not appear in the "mandatory to send" list in that section.

There is also this para:

````
   Additionally, all implementations MUST support use of the
   "server_name" extension with applications capable of using it.
   Servers MAY require clients to send a valid "server_name" extension.
   Servers requiring this extension SHOULD respond to a ClientHello
   lacking a "server_name" extension by terminating the connection with
   a "missing_extension" alert.
````

Strictly speaking this means Google are not obeying the spec in returning an invalid spec  - they should instead respond with "missing_extension".

**Comment by richsalz** [comment]
Ah, you're right, I mis-remembered SNI as a MUST.

**Comment by sfackler** [comment]
Ah thanks!

**Comment by mattcaswell** [comment]
Closing this.
