### ISSUE TITLE
GCM MAC computation for AES-GCM

### ISSUE THREAD

**Issue by Smeyla** [openssl/openssl#5379]
Hi,

I would like to use OpenSSH in FIPS mode with FIPS capable OpenSSL. I saw #3216 and #4157 and i have some questions.

In #4157, @srahul123 explains that aes256-gcm is affected by this issue but he tried to solve it modifying `gcm128.c` file. Are aes128-gcm and aes256-gcm both affected?

If I configure OpenSSH adding `aes256-gcm@openssh.com` in the "Ciphers" option, do you know i am concerned by this issue? Are GCM MAC computed anyway?

**Comment by richsalz** [comment]
It is likely that AES128-GCM is also affected.  We are not supporting the current FIPS code, it is "frozen"  We are working on a new FIPS version for the next release.  If you modify the current code in any way, you cannot claim to be FIPS compliant, sorry.
