### ISSUE TITLE
Cipher list of TLSv1.2

### ISSUE THREAD

**Issue by rrip** [openssl/openssl#5385]
In 1.1.1 pre1, when using SSL_CTX_new(TLS_server_method()), then SSL_CTX_set_cipher_list to set the cipher list to "TLSv1.2", client SSL sessions report No Cipher Overlap. Qualys SSLLABS also reports no ciphers. Setting it to "HIGH" works. Did something change in this release with cipher list "TLSv1.2" ?

**Comment by richsalz** [comment]
See #5359  You can't have non-default ciphers and default ssl_ctx.  This is being discussed over there.

**Comment by kaduk** [comment]
The cipher list "TLSv1.2" is generally a bad idea anyway, since it means "ciphers added in TLS 1.2", not "ciphers that can be used with TLS 1.2".  If you want to limit the protocol version, use ```SSL_{CTX_,}set_{min,max}_proto_version()```.
