### ISSUE TITLE
openssl-1.0.2-stable "N" & "O"dev failed on windows 10 with msvc2015 X86

### ISSUE THREAD

**Issue by daveaton** [openssl/openssl#5389]
I can't seem to compile a x86 version of openssl using version openssl 1.0.2n or the current master 1.0.2o_dev

I am running windows 10 X64 bit home.

Here is what I have tried..

openssl 1.0.2n on MSVC 2015.
http://www.eatoncode.com/resources/shareit/Screencast_21-53_15-02-2018.mp4

openssl 1.0.2o on MSVC 2015.
http://www.eatoncode.com/resources/shareit/Screencast_22-25_15-02-2018.mp4

I have searched the closed problems and found this.

https://github.com/openssl/openssl/issues/169

I have tried to use the solutions it gave but it did not work on my machine.

oddly enough the x64 version compiled without a problem.

Here are the commands I am trying to run..

1. Open up x86 Native Tools Command Prompt for VS 2015. Make sure it's opened with Admin.

"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

mkdir c:\openssl\debug\x86

mkdir c:\openssl\release\x86

cd C:\openssl-1.0.2n

```
perl Configure debug-VC-WIN32 --prefix=c:\openssl\debug\x86

ms\do_ms

ms\do_nasm

nmake -f ms\ntdll.mak

nmake -f ms\ntdll.mak install

nmake -f ms\ntdll.mak clean

```

```
perl Configure VC-WIN32 --prefix=c:\openssl\release\x86

ms\do_ms

ms\do_nasm

nmake -f ms\ntdll.mak

nmake -f ms\ntdll.mak install

nmake -f ms\ntdll.mak clean
```

I have NASM is 2.13.03 installed.  http://www.nasm.us/

I have the most recent Active Perl installed.  https://www.activestate.com/activeperl

Is this a known issue ?

**Comment by daveaton** [comment]
It seems further google searches and I found the proper answer.

https://github.com/openssl/openssl/issues/475

I forgot the "no-asm" argument.  It's compiling now.

**Comment by mattcaswell** [comment]
Compiling without "asm" has serious performance implications. Maybe that's ok for your use case. The problem seems to be that, although you say you have installed NASM, it is not found on your %PATH%. You need to update the %PATH% environment variable to add the directory where NASM is installed.
