### ISSUE TITLE
Where is md4test?

### ISSUE THREAD

**Issue by TimJSwan89** [openssl/openssl#5393]
To replicate a build issue that someone reported for another project, I need to run `test/md4test` and `test/md5test`, but it seems like only `md2test` exists in the `test` folder.

Were the other ones removed or am I missing something obvious, here?

Here's a reference to an `md4test` at a different source:
http://docs.huihoo.com/doxygen/openssl/1.0.1c/crypto_2md4_2md4test_8c_source.html

**Comment by mattcaswell** [comment]
It was removed by this PR on the basis that all of the tests are redundant because they are covered by evptest:

https://github.com/openssl/openssl/pull/2784
