### ISSUE TITLE
OpenSSL 1.1. does not honor --libdir

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#5398]
I asked for the libraries to be placed in `/opt/local/test/b/lib`:

```
$ ./config --openssldir=/opt/local/test/a/bin --prefix=/opt/local/test  --libdir=/opt/local/test/b/lib
```

Here is where they showed up:

```
$ find /opt/local/test -name 'libssl*'
/opt/local/test/opt/local/test/b/lib/libssl.so.1.1
/opt/local/test/opt/local/test/b/lib/libssl.a
/opt/local/test/opt/local/test/b/lib/libssl.so
/opt/local/test/opt/local/test/b/lib/pkgconfig/libssl.pc
```

No environmental variables are set that could interfere with OpenSSL scripts, like `INSTALL_PREFIX`.

**Comment by mattcaswell** [comment]
This looks like correct behaviour to me. From INSTALL `--prefix` says this:

````
  --prefix=DIR
                   The top of the installation directory tree...
````

Whereas `--libdir` says this:

````
  --libdir=DIR
                   The name of the directory under the top of the installation
                   directory tree (see the --prefix option) where libraries will
                   be installed.  By default this is "lib".
````

So you have asked for libraries to be installed in the `/opt/local/test/b/lib` directory under the top of the installation directory tree (which is `/opt/local/test`). In other words you have said to put libraries in `/opt/local/test/opt/local/test/b/lib`, which is exactly where they have been put!

**Comment by noloader** [comment]
@mattcaswell ,

I did not ask for the libraries to be placed under the `prefix` directory. I gave the absolute path for where I wanted them.

As far as I know there is no way to use a directory that is *not* under `--prefix`. How does one install to the following locations:

* `openssl` in `/opt/a`
* `libssl.so` in `/opt/b`
* `libcrupto.so` in `/opt/b`
* `openssl.cfg` in `/opt/c`

As far as I know, OpenSSL is the ***only*** configure program with this behavior.

For completeness, here is the behavior the most of the remainder of the world uses: [GNU coding standards](https://www.gnu.org/prep/standards/standards.html) and to a lesser extent [Variables for Installation Directories](https://www.gnu.org/software/make/manual/html_node/Directory-Variables.html).

**Comment by mattcaswell** [comment]
> I did not ask for the libraries to be placed under the prefix directory. I gave the absolute path for where I wanted them.

The documentation is clear that *all* paths that you give in this option are relative to the prefix directory. 

AFAIK we do not claim compliance with the GNU coding standards in this regard. There are a whole stack of these options in the GNU standards that we don't support at all. So, realistically, no one using OpenSSL Configure could expect to get GNU behaviour. We certainly wouldn't be looking to change Configure to conform to those standards across the board in the 1.1.1 timeframe (its too late for that). It might be a reasonable thing to consider for the future (I don't know I haven't thought about it).

With specific reference to libdir it *might* be a reasonable thing to consider adding support for absolute paths in 1.1.1, but I would defer to @levitte on that.

**Comment by levitte** [comment]
> With specific reference to libdir it _might_ be a reasonable thing to consider adding support for absolute paths in 1.1.1, but I would defer to @levitte on that.

I think that's a good idea, and shouldn't be too hard to implement either.  `--openssldir` already works that way.

**Comment by levitte** [comment]
I take that back actually, it's a little more complex than the `--openssldir` case, as the latter will supposedly generate an absolute path as value for the `OPENSSLDIR` variable in the Makefile.

Not so for `LIBDIR`, so that means we need to check in runtime (well, build time) if it's absolute or not, and adapt every usage of it accordingly.  It's still not terribly hard to do on Unix.  On native Windows, however...

... and I'm out of cycles for the day...

**Comment by levitte** [comment]
Ah, I think I found the solution.  According to the GNU coding standard, the directory variables are lower case, so the trick is to use that to our advantage.  I'm currently working on code that will give us the following:

For `--libdir=/absolute/path`:

```
LIBDIR=
libdir=/absolute/path
```

For `--libdir=relativepath`:

```
LIBDIR=relativepath
libdir=$(INSTALLTOP)/$(LIBDIR)
```

When no `--libdir` is given, the result will be this, which is basically what we have today:

```
LIBDIR=lib
libdir=$(INSTALLTOP)/$(LIBDIR)
```

**Comment by levitte** [comment]
See #5446
