### ISSUE TITLE
TLS v1.2 Cipher Suites support in OpenSSL v1.0.2n and v1.1.0f

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#5403]
Am building a Medical domain application using dcmtk.
For TLS/SSL support we build dcmtk with OpenSSL library.
I need to support the following four TLSv1.2 cipher suites:
 ·TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
 ·TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
 ·TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 ·TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

For Open SSL v 1.0.2n version, none of the four seems to work.
But, on listing the supported cipher suites[$openssl ciphers -v -tlsv1] these four are listed:
ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH Au=RSA Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH Au=RSA Enc=AESGCM(256) Mac=AEAD
ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH Au=RSA Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH Au=RSA Enc=AESGCM(128) Mac=AEAD

The situation is such that a data is sent from client to server using one of these cipher suites.
Server side logs "unspecified TLS" error whereas the client side logs "no ciphers available".

Seems something to do with ssl_cipher_list_to_bytes() of ssl_lib.c
It is to be noted that for the same set up with OpenSSL version 1.1.0f, the below two ciphers work:
 ·TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 ·TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

Any input on the same is highly appreciated.
At-least thoughts on what could possibly be wrong would be of good help.
Thanking you in advance.

OS: Windows 7 64 bit

Regards,
Amal

**Comment by mattcaswell** [comment]
Did you call `SSL_CTX_set_tmp_dh()` or `SSL_CTX_set_ecdh_auto()` on the server? These are needed in 1.0.2 to set the appropriate parameters to use for DHE/ECDHE ciphersuites.

https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_tmp_dh.html
https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_ecdh_auto.html

Note that in 1.1.0 ecdh_auto is on by default (and in fact cannot be switched off), which might explain why the ECHDE ciphersuites were working for you in 1.1.0.

**Comment by amaljesudas** [comment]
Hi Matt,

Thank you so much for pointing out the same.
As you mentioned, I checked the occurrence of SSL_CTX_set_tmp_dh() and  SSL_CTX_set_ecdh_auto() in my server code.
SSL_CTX_set_ecdh_auto() was not used and when I added that, could see that ECDHE cipher suites were working.
On the other hand SSL_CTX_set_tmp_dh() is already called but still my client-server communication is not working for DHE cipher suites.
I need to dig in a little more before I conclude on DHE cipher suite issue.
But, you have guided me in the right direction.
Will get back soon with my finding or fix.

Thanks & Regards,
Amal

**Comment by mattcaswell** [comment]
> On the other hand SSL_CTX_set_tmp_dh() is already called but still my client-server communication is not working for DHE cipher suites.

You might want to check that the parameters for DHE (set via SSL_CTX_set_tmp_dh) are using a sufficiently large prime. Small primes may not be used.

**Comment by amaljesudas** [comment]
Hi Matt,

I was just going through the s3_lib.c source code while checking DHE cipher suites.
Came across the following block of code:

         _/* Skip TLS v1.2 only ciphersuites if not supported */
        if ((c->algorithm_ssl & SSL_TLSV1_2) && !SSL_USE_TLS1_2_CIPHERS(s))
            continue;_

From the comment, it appears to be a provision to skip unsupported TLSv1.2 cipher suites.
Does this mean that there is some provision to configure support for a set of cipher suites?
If the cipher suite is listed on checking with the command **$openssl ciphers -v -tlsv1**,  can it still show up as unsupported in the above code block?

Kindly excuse my shallow knowledge here.

Thanks & Regards,
Amal

**Comment by mattcaswell** [comment]
> Does this mean that there is some way to configure support for a set of cipher suites?

Well, you can configure support for a set of ciphersuites but that code is nothing to do with that capability.  See:

https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_cipher_list.html

> If the cipher suite is listed on checking with the command $openssl ciphers -v -tlsv1, can it still show up as unsupported in the above code block?

Yes. The above code block determines whether the protocol version that has been negotiated is compatible with the ciphersuite. Certain ciphersuites are *only* compatible with TLSv1.2 (or DTLSv1.2) - including the four that you are interested in. If you negotiate TLSv1.1 or below then you won't be able to use those ciphersuites.

**Comment by amaljesudas** [comment]
Hi Matt,

Thanks for clarifying the same.
Just to add, I am setting DHE-RSA-AES128-GCM-SHA256 cipher suite for my server and trying to sent data from a client using DHE-RSA-AES128-GCM-SHA256 cipher suite itself. 
Also, a similar mode was followed for ECDHE cipher suites and that combination worked. 
Therefore, in case of DHE cipher suites also wont TLSv1.2 be negotiated?
Please correct me if my thinking is wrong.

Thanks & Regards,
Amal

**Comment by amaljesudas** [comment]
Hi Matt,

The issue seems to be with the DH parameter file provided.
I generated a new one and now DHE cipher suites are also working.
I will close this issue now, although it was more of a knowledge share than an issue.
Thanks a lot for your support.

Thanks & Regards,
Amal

**Comment by hlsantos** [comment]
Hey Matt,  Thanks million!   Wow!  I was beating my brain over this for a week trying to get my openssl-based web server (Wildcat!) working with the ECDHE ciphers/curves.  Calling the SSL_CTX_set_ecdh_auto() function did the trick.    Now do I even need to bother calling SSL_CTX_set_tmp_dh()  at this point?  The default is DH 512 and much of the brain-bashing research was exploring increasing the DB bits, 1024, 2048, etc, which helped but couldn't get Chrome to work.   Enabling ecdh in code did the trick.  I just wanted to give you credit!  Thanks!     :+1:

**Comment by mattcaswell** [comment]
> Now do I even need to bother calling SSL_CTX_set_tmp_dh() at this point? The default is DH 512 and much of the brain-bashing research was exploring increasing the DB bits, 1024, 2048, etc, 

It's possible that some clients may not support ECDH. If you have any clients like that then you may wish to call that function anyway. If supporting such clients isn't important to you then you don't need to call it.

Whatever you decide though either 1) don't call it at all, or 2) call it with at least 2048 bit parameters.

**Comment by hlsantos** [comment]
Thanks Matt. I am back in getting the final release production code completed. making final changes.  So is it safe to call both? 

```
      //if (dh) SSL_CTX_set_tmp_dh(ctx, dh);  // disabled: future, see if safe to call both.
      SSL_CTX_set_ecdh_auto(ctx, 1);   // new: enable ecdh curves
```
dh/bits can still be prepared via operator config.  I will make it 2048 bits the default now.  But if I enabled, do you think it is  safe to call both?   I suppose I can add the switches to make the combos completely optional either way.

Thanks

**Comment by mattcaswell** [comment]
Yes, its safe to call both.
