### ISSUE TITLE
Huawei PGPverify tool which has OpenSSL license issues.

### ISSUE THREAD

**Issue by Tianjiao** [openssl/openssl#5404]
Hello

I download the [Huawei](http://www.huawei.com/en/contact-us) PGPverify tool from [here](http://support.huawei.com/enterprise/en/tool/software-digital-signature-validation-tool-(pgp-verify)-TL1000000054/TV1000000016), but find 3 OpenSSL license issues.
According to the documentation in the OpenPGP Signature Verification Guide.pdf, this tool is based on the OpenSSL.

1.  **Lack of the OpenSSL license file**, nor the block of the license content.

Could not find it in the documentation, nor in the binary package.
According to the OpenSSL license, Point 2

> Point 2. Redistributions in binary form must _reproduce the above copyright
> notice_, this list of conditions and the following disclaimer in
> the documentation and/or other materials provided with the
> distribution.

Which means that the license file should be remained in the binary form, which is not the case.

2. The copyright announcement in the Windows command line mode **does not include the phrase** 

> "This product includes software developed by the OpenSSL Project
> for use in the OpenSSL Toolkit. (http://www.openssl.org/)".

Execute the following command, the output is:
```
"C:\Users\Dell\Downloads\VerificationTools\windows\x86\PGPVerify TOOL\PGPVerify.exe" -h

PGPVerify version V100R001C00SPC320
Copyright (c) Huawei Technologies Co., Ltd. 2017. All rights reserved.

```
According to the OpenSSL license, Point 3
> Point 3. _All advertising materials_ mentioning features or use of this
> software must display the following acknowledgment:
> "This product includes software developed by the OpenSSL Project
> for use in the OpenSSL Toolkit. (http://www.openssl.org/)"

Which means that **every** copyright claim, must provide the license phrase, as well.

3. **The GUI "hide" the About info**, must right click your mouse to select to see it, not in the menu.

Which means that the copyright notice is hidden from the ordinary view.

So are they license issues?

**Comment by richsalz** [comment]
Why do you think the OpenPGP product uses openssl?

**Comment by Tianjiao** [comment]
Because Huawei claims it by itself. I get the OpenSSL information from two sources.

1. From the [OpenPGP Signature Verification Guide.pdf](http://support.huawei.com/enterprise/en/tool/software-digital-signature-validation-tool-(pgp-verify)-TL1000000054/TV1000000016), at the Page 39, it contains the OpenSSL license information.

2. From the linux x64 binary from the [VerificationTools.rar](http://support.huawei.com/enterprise/en/tool/software-digital-signature-validation-tool-(pgp-verify)-TL1000000054/TV1000000016), when I run it in the virtual machine, it prints out the OpenSSL license information, namely

> "This product includes software developed by the OpenSSL Project
> for use in the OpenSSL Toolkit. (http://www.openssl.org/)"

However, Huawei does **not** fully comply with the license terms, which is the main reason that I opened an issue here.

**Comment by richsalz** [comment]
Thank you for reporting it; we will take it up with them.
