### ISSUE TITLE
OpenSSL 1.1.0: NOTES.PERL should mention Win32::API requirement

### ISSUE THREAD

**Issue by makr** [openssl/openssl#5413]
Hi OpenSSL-Team,

this is just a suggestion to slightly extend the documentation or - at your discretion - you might also opt for making the test code a little more robust ;-) ...
I experienced a failing test_pkcs12 on one of my Windows build machines. Running it with TESTS=test_pkcs12 V=1 as seen in other issues, it turned out that this test tried to execute 'locale -a'. This fails for obvious reasons on Windows.
It turned out, that Win32::API wasn't installed with the ActivePerl 5.10.1 on this machine. I wasn't able to 'cpan -i' it either, so I updated to the current ActivePerl version which comes with Win32::API and everything is fine now on Windows.

So I suggest to mention the Win32::API requirement in the 'Notes on Perl On Windows' section in NOTES.PERL, which would have brought me at least to find out that this module is missing on this machine before I even tried to build OpenSSL on this machine.

Thanks! -- Matthias Kraft

**Comment by levitte** [comment]
But...  does the test actually *fail*, or does it just whine about 'locale -a' not being possible to execute, but the test itself still says `ok`, not `not ok`?

**Comment by dot-asm** [comment]
It should fail. Because then it doesn't convert string from utf-8. However! I've rather suggest to add additional `elsif ($^O eq "MSWin32") { plan skip_all => "No Win32::API"; }` after attempt to detect Win32::API. [I can do it...]

**Comment by makr** [comment]
It fails.

**Comment by dot-asm** [comment]
See #5416.
