### ISSUE TITLE
Strange behavior of `DEFAULT` in cipher list

### ISSUE THREAD

**Issue by AloisMahdal** [openssl/openssl#5420]
For example, following commands will return the same set:

    openssl ciphers DEFAULT
    openssl ciphers DEFAULTz

despite `DEFAULTz` not being a valid cipher string.

I have already [reported this to Fedora][1].  According to @t8m, the `DEFAULTz` is equivalent to `DEFAULT:z`, in which case it would be valid behavior (because `z`, not being a valid cipher string can be ignored).  [ciphers(1)][2] does not seem to allow such interpretation, though (or at very least this is very counterintuitive).

  [1]: https://bugzilla.redhat.com/show_bug.cgi?id=1547067
  [2]: https://www.openssl.org/docs/man1.1.0/apps/ciphers.html

I'm observing this with `openssl-1.1.0g-1.fc26` on Fedora 26.

**Comment by mattcaswell** [comment]
The behaviour has been like this for a *very* long time. Since at least commit 018e57c74d9d (18 years ago). It seems harmless though, and changing it could break stuff (if people have inadvertently forgotten to include a ":" in their configs) - so I don't think this should be fixed. Perhaps a note in the documentation would be in order. Feel free to raise a PR to do that.

**Comment by t8m** [comment]
I'll create PR for that doc improvement.

**Comment by AloisMahdal** [comment]
(I can't help myself but post this witty comment.) Harmless, bit confusing indeed: Current number of PRs attempting to explain `DEFAULT` in man page: 3

**Comment by richsalz** [comment]
yeah, the current behavior is a horrible hack.

**Comment by AloisMahdal** [comment]
Note that the behavior is actually a bit less harmless:  reading man page, one could come to conclusion that eg. `DEFAULT+ECDH` will select intersection of default set with ECDH. However, turns out that

 *  this gets *actually* interpreted as `DEFAULT:+ECDH`, enabling more ciphers than intended,
 *  and `DEFAULT+ECDH` (in "AND" meaning defined by doc) is not really possible.
