### ISSUE TITLE
Need to document PEM_X509_INFO_read_bio()

### ISSUE THREAD

**Issue by vdukhovni** [openssl/openssl#5424]
Would be great if someone would contribute a "pod" manpage, with an EXAMPLES section that includes some sample code.

**Comment by rainerjung** [comment]
It is especially noteworthy, that PEM_X509_INFO_read_bio() only supports PEM_STRING_RSA private keys, eg. not the PEM_STRING_PKCS8INF OpenSSL supports in many other places it reads private keys from PEM.

**Comment by nhorman** [comment]
API call seems documented now, closing
