### ISSUE TITLE
Can X25519/Ed25519 functions be possibly exposed for direct use?

### ISSUE THREAD

**Issue by Nekotekina** [openssl/openssl#5453]
Hello, I'd like to ask about the following functions from curve25519.c:

```C
int ED25519_sign(uint8_t *out_sig, const uint8_t *message, size_t message_len,
		const uint8_t public_key[32], const uint8_t private_key[32]);
int ED25519_verify(const uint8_t *message, size_t message_len,
		const uint8_t signature[64], const uint8_t public_key[32]);
void ED25519_public_from_private(uint8_t out_public_key[32],
		const uint8_t private_key[32]);

int X25519(uint8_t out_shared_key[32], const uint8_t private_key[32],
		const uint8_t peer_public_value[32]);
void X25519_public_from_private(uint8_t out_public_value[32],
		const uint8_t private_key[32]);
```

Trying to get equivalent functionality over the binary data using only available OpenSSL API seems pretty hard or even impossible. I'm not very familiar with OpenSSL so I failed to figure it out. On the other hand, these functions are simple and obvious.

**Comment by richsalz** [comment]
We understand, but our policy is that the EVP interface is the only one we are going to expose.  Of course, you have the source and  can do what you want.

**Comment by mattcaswell** [comment]
I'm going to reopen this, because I think there may some issues with the EVP interface to this, but I need time to investigate.

**Comment by mattcaswell** [comment]
#5520 eventually got merged which makes using X25519/Ed25519 via EVP considerably easier. Closing this.

**Comment by aep** [comment]
doesn't look like there's an EVP equivalent to ED25519_public_from_private yet?

**Comment by t8m** [comment]
> doesn't look like there's an EVP equivalent to ED25519_public_from_private yet?

If you create a new EVP_PKEY via EVP_PKEY_fromdata with just setting the private key, the resulting key will have the public key calculated during the import. So you can then get the public key value via EVP_PKEY_get_BN_param().

**Comment by mattcaswell** [comment]
> If you create a new EVP_PKEY via EVP_PKEY_fromdata with just setting the private key, the resulting key will have the public key calculated during the import. So you can then get the public key value via EVP_PKEY_get_BN_param().

Easier is to create the EVP_PKEY using `EVP_PKEY_new_raw_private_key_ex()`. The public key is actually an octet string so you actually have to use `EVP_PKEY_get_octet_string_param()`. E.g. something like this:

````
    EVP_PKEY *our_pkey = EVP_PKEY_new_raw_private_key_ex(NULL, "X25519", NULL,
                                                         priv_key, 32);
    size_t outlen = 0;
    unsigned char pub_key[32];

    if (!EVP_PKEY_get_octet_string_param(pkey, OSSL_PKEY_PARAM_PUBLIC_KEY, pub_key, sizeof(pub_key), &outlen))
        goto err;
````

**Comment by mattcaswell** [comment]
Oh...sorry...you said Ed25519 and my example was X25519. Same concept applies though.
