### ISSUE TITLE
Typo in documentation for ASN1_STRING_set

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#5454]
https://www.openssl.org/docs/man1.1.0/crypto/ASN1_STRING_set.html

> In general it cannot be assumed that the data returned by ASN1_STRING_data() is null terminated or does not contain embedded nulls. The actual format of the data will depend on the actual string type itself: **_for example for and IA5String*_* the data will be ASCII, for a BMPString two bytes per character in big endian format, UTF8String will be in UTF8 format.

I've highlighted the section with the typo above.

**Comment by mlindner** [comment]
Considering this is fixed, can't we close this?

**Comment by mspncp** [comment]
Sure. Thanks for reporting it!
