### ISSUE TITLE
1.1.1-pre2 does not allow TLS1.2 connections if TLS1.3 cipher are missing

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#5474]
As reported in Debian BTS [0] if a TLS1.3 cipher is missing then a TLS1.2 only connection is not established even if the remote supports only TLS1.2. I know that this was mentioned / covered in [1].
Would it be possible to strip TLS1.3 from the possible protocols that can be negotiated if the TLS1.3 cipher(s) is(are) missing?
I think libio-socket-ssl-perl is not the only one that has hardcoded ciphers. Nevertheless I asked for inclusion of the TLS1.3 cipher so that it is possible to use the protocol in future.

[0] https://bugs.debian.org/891665
[1] https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/

Sebastian

**Comment by mattcaswell** [comment]
This is a well known issue and is being tracked in issue #5359. We have a possible solution in #5392.

Since this is being tracked elsewhere, I'm closing this issue.
