### ISSUE TITLE
Some application distributes your library, without your license copy?

### ISSUE THREAD

**Issue by Tianjiao** [openssl/openssl#5484]
Hello

When I download some application from [here](http://dlglobal.qq.com/weixin/Windows/WeChat_C1018.exe) in [here](http://www.wechat.com/en/) and install it, your library is found in its installation directory, but your license copy is missing.
[The Shared Library.zip](https://github.com/openssl/openssl/files/1769464/The.Shared.Library.zip)

How do I know that is your library?
I hover the mouse pointer over the library file on the Windows system, and it shows in the field of the "Company":

> The OpenSSL Project, http://wwww.openssl.org/

It contains the website link to your homepage, which is the trace back link and the unique identification that the library belongs to you.

According to your [license terms](https://github.com/openssl/openssl/blob/master/LICENSE):

>  2. Redistributions in binary form must reproduce the above copyright
>  notice, this list of conditions and the following disclaimer in
> the documentation and/or other materials provided with the
>  distribution.

I can't find your license copy neither in their binary nor their EULA, so I report it to you.

The following applications share the same issue:

Download [here](https://alimarket.taobao.com/markets/qnww/aliww-download?spm=a21e4.8043303.0.0.56f535196zo447&wh_from=win) from [here](http://wangwang.taobao.com/)
Download [here](http://j.br.baidu.com/v1/t/full/p/browser/tn/11000002/ch_dl_url) from [here](https://liulanqi.baidu.com/)
Download [here](http://lotus.sp.iqiyi.com/ota?id=&pubplatform=1&pubarea=pcltdown_15030501&qipuid=&u=&pu=) from [here](https://www.iqiyi.com/)
Download [here](http://download.cntv.cn/cbox/v4/ysyy_v4.4.2.0_Setup_1001.exe) from [here](http://app.cctv.com/appkhdxz/pc/index.shtml)

**Comment by richsalz** [comment]
Thanks, we will followup with them.

**Comment by Tianjiao** [comment]
Thanks for accepting my report.

Sorry but I forgot a point, I can't find **the license phrase** in their software, as well.
That is, I can not find the following acknowledgment from their ads, and About info.
And they include the Windows specific code, so _SSLeay License, Point 4_ also applies.

According to your license, Point 3

> 3. All advertising materials mentioning features or use of this
> software must display the following acknowledgment:
> "This product includes software developed by the OpenSSL Project
> for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
> 

And SSLeay License, Point 3 and 4

> 3. All advertising materials mentioning features or use of this software
> must display the following acknowledgement:
> "This product includes cryptographic software written by
>  Eric Young (eay@cryptsoft.com)"
>  The word 'cryptographic' can be left out if the rouines from the library
>  being used are not cryptographic related :-).
> 4. If you include any Windows specific code (or a derivative thereof) from 
> the apps directory (application code) you must include an acknowledgement:
> "This product includes software written by Tim Hudson (tjh@cryptsoft.com)"
