### ISSUE TITLE
1.1.0g: test_shlibload fails on AIX

### ISSUE THREAD

**Issue by makr** [openssl/openssl#5485]
Hello OpenSSL-team!

I am checking test_shlibload failures on AIX. All test cases dump a core with SIGILL. I already played around with the sources for quite some time and am confident now, that it has to do with OPENSSL_cleanup() is not removed as atexit() handler.
I added a number of OPENSSL_INIT_DEBUG outputs. Now when I remove the dlclose()-call the test cases succeed and the output shows that OPENSSL_cleanup() is called after shlibtest's main() returns:

```
bash-4.2$ ../util/shlib_wrap.sh ./shlibloadtest -just_crypto libcrypto.so libssl.so                          
OPENSSL_INIT: ossl_init_base: Setting up stop handlers
OPENSSL_INIT: ossl_init_base: Registering cleanup exit handler
OPENSSL_INIT: ossl_init_thread_start: marking thread for err_state
OPENSSL_INIT: ossl_init_load_crypto_strings: err_load_crypto_strings_int()
OPENSSL_INIT: ossl_init_thread_start: marking thread for err_state
Success
OPENSSL_INIT: OPENSSL_cleanup: function entered
OPENSSL_INIT: ossl_init_thread_stop: err_delete_thread_state()
OPENSSL_INIT: OPENSSL_cleanup: err_free_strings_int()
OPENSSL_INIT: OPENSSL_cleanup: rand_cleanup_int()
OPENSSL_INIT: OPENSSL_cleanup: conf_modules_free_int()
OPENSSL_INIT: OPENSSL_cleanup: engine_cleanup_int()
OPENSSL_INIT: OPENSSL_cleanup: crypto_cleanup_all_ex_data_int()
OPENSSL_INIT: OPENSSL_cleanup: bio_sock_cleanup_int()
OPENSSL_INIT: OPENSSL_cleanup: bio_cleanup()
OPENSSL_INIT: OPENSSL_cleanup: evp_cleanup_int()
OPENSSL_INIT: OPENSSL_cleanup: obj_cleanup_int()
OPENSSL_INIT: OPENSSL_cleanup: err_cleanup()
```
This behavior is problematic on AIX, at least. On AIX the dlclose() behavior is documented as follows:

> Modules being unloaded with the dlclose subroutine will not be removed from the process's address space if they are still required by other modules. Nevertheless, subsequent uses of Data are invalid,
>        and further uses of symbols that were exported by the module being unloaded result in undefined behavior.

The stack trace in the core dump shows that exit() is trying to invoke a function at 0x0.

My opinion here is that a library that is supposed to be dynamically loaded (and unloaded) should not register atexit() handlers, but declare init/fini or constructor/destructor functions instead.

I'll play around with it tomorrow, but maybe someone has another opinion meanwhile.

kind regards
-- Matthias

**Comment by makr** [comment]
The problematic piece of code is in init.c,  starting at line 109 (in 1.1.0g) with the comment "Deliberately leak a reference to ourselves. [...]". This is just not doing what it should do, as there is no dladdr() in AIX. Hence HAVE_DLINFO in dso_dlfcn.c is undefined. Hence dlfcn_pathbyaddr() always returns -1, which becomes the return value of DSO_pathbyaddr() in dso_lib.c. Hence DSO_dsobyaddr() returns NULL and we do not, even deliberately, have a reference to ourself.

When I injected an ... dlopen( "libcrypto.so", RTLD_LAZY ); ... into this block, the "-just_crypto" test case stopped failing and the other two failed in OPENSSL_cleanup() at the OPENSSL_atexit()-handlers (init.c line 412: currhandler->handler();). I had to inject another ... dlopen( "libssl.so", RTLD_LAZY ); ... to stop it failing altogether. BTW a  ... dlopen( NULL, RTLD_NOW|RTLD_GLOBAL ); ... didn't help at all.

I haven't found a way to retrieve the libraries name or path on AIX. I still think the atexit()-stuff is not the right solution here. I do recognize that using init/fini handling is highly compiler dependent, but I still think it is the right thing to do.

Maybe there is another solution. But I also have to admit, that although I starred at the DSO-code quite a couple of hours, I haven't quite groked it.

It stops failing, once I add a configure option -Wl,-binitfini:OPENSSL_init:OPENSSL_cleanup:0 and then edit the Makefile to have $(EX_LIBS) removed from the test/shllibloadtest target and not calling atexit() in init.c when _AIX is defined. When compiled in this way and with OPENSSL_INIT_DEBUG defined, the output shows, that OPENSSL_cleanup now gets called within dlclose().

I'll create a patch and cross-check no other platform will be affected. Is this something you would accept as solution for this particular problem? I mean it is changing semantics on AIX...

-- Matthias

**Comment by mattcaswell** [comment]
> I mean it is changing semantics on AIX...

In what way is it changing semantics?

I came across this, which seems to suggest how the missing dladdr could be done on AIX:

https://root.cern.ch/blog/aix-and-dladdr

**Comment by makr** [comment]
On AIX it would not register OPENSSL_cleanup() as exit()-hook anymore. It would be a fini-function instead and be executed right away when dlclose() is called.

I am not quite sure how this example could escape me, especially as it now seem to pop up in multiple variations with every Google search. Anyway, if it is OK to have OPENSSL_cleanup() be registered as fini-function (or destructor on GCC), then this deliberate obtaining of a reference would not be needed anymore.

**Comment by mattcaswell** [comment]
Right, but I'm thinking it might be better to keep the behaviour on AIX the same as everywhere else. As you say above the fini function concept is highly compiler dependent which is why we didn't do it that way in the first place (because we need to be able to run on lots of different platforms with lots of different compilers). We already have two different ways to do this (nodelete vs leak a reference). I'm not sure introducing a third is the way to go.

**Comment by makr** [comment]
I see, perfect, thanks! I will work on a patch doing it this way then. Unfortunately I am at home currently, so it will take another couple of days.

**Comment by makr** [comment]
Just a ping. I am still on it. I have a working implementation, but it cannot lookup &base_inited (yet) and for looking up function symbols it needs to resolve the ptrgl virtual addresses. Next is to extend the shlibloadtest to ensure it will work for everyone.
I do not have access to an AIX machine with GCC, so I don't know what happens with these targets.

**Comment by covener** [comment]
I tested the branch in the related PR with an Apache httpd release candidate and no longer needed my partial workarounds to avoid atexit() SIGILL.  Thanks @makr !  aix 7.1/xlc/ppc64 FWIW.

**Comment by mattcaswell** [comment]
This should be fixed in master now (right?), so changing milestone to 1.1.0.

**Comment by t8m** [comment]
Closing
