### ISSUE TITLE
not able to get the executable file for openssl  on windows 2008 r2

### ISSUE THREAD

**Issue by imrannawaz** [openssl/openssl#5487]
I have downloaded the openssl from the downloads and unzipped the folder and am not getting option to install the openssl application .Is there any way we can directly install the openssl application in simple steps. With openssl i want to create pub and priv keys for my certificate.
My OS : win 2008 r2 64 bit

Please help or guide the simple steps.

**Comment by mspncp** [comment]
From openssl.org you can only download the source code. If you are looking for prebuilt binaries, please have a look at https://wiki.openssl.org/index.php/Binaries.

**Comment by mspncp** [comment]
See also https://www.openssl.org/community/binaries.html, which links to the wiki.
