### ISSUE TITLE
OpenSSL FIPS ms\do_nasm Perl do_rlink_rule Build Failure.

### ISSUE THREAD

**Issue by AlanRashid** [openssl/openssl#5496]
I've tried building a FIPS OpenSSL, version 2.0.16, and every variant I've tried to build produces the same error when running ms\do_nasm:  Undefined subroutine &main::do_rlink_rule called at util\mk1mf.pl line 983.  Attached is a copy of one of the sessions I ran with the command line entries I made and the ms\do_nasm error highlighted.
[OPENSSL_FIPS_Build_Session.txt](https://github.com/openssl/openssl/files/1776946/OPENSSL_FIPS_Build_Session.txt)

**Comment by richsalz** [comment]
Did you follow the steps in Appendix A, exactly?  It doesn't look like it.

**Comment by t8m** [comment]
Old FIPS module is not supported anymore. Closing.
