### ISSUE TITLE
Compile error with MSVC and x64 target

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#5497]
f_generic.c
crypto\ec\curve448\f_generic.c(125): error C2220: warning treated as error - no 'object' file generated
crypto\ec\curve448\f_generic.c(125): warning C4244: 'function': conversion from 'dsword_t' to 'uint32_t', possible loss of data
crypto\ec\curve448\f_generic.c(138): warning C4244: 'function': conversion from 'dword_t' to 'uint32_t', possible loss of data
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\cl.EXE"' : return code '0x2'

**Comment by dot-asm** [comment]
This is already recognized and being addressed in #5494. But thanks for report :-)

On side note there is contradiction in your report. Subject says x64, while this failure can be observed only in 32-bit [debug] build.
