### ISSUE TITLE
Minimal memory footprint per SSL connection

### ISSUE THREAD

**Issue by yoggikim** [openssl/openssl#55]
I'm using a Node.js client to connect to thirdparty SSL servers. Currently, memory footprint is about ~130kb per connection. Node.js uses OpenSSL for this.
How can I reduce this footprint to the minimal possible size?
I've read that Google has done some work on the subject a while back:
https://www.imperialviolet.org/2010/06/25/overclocking-ssl.html

Is this still relevant? Any pointers? 
Many thanks!

**Comment by richsalz** [comment]
ask on openssl-users mailing list, this is not an issue with the openssl software.
