### ISSUE TITLE
build_all_generated conundrum

### ISSUE THREAD

**Issue by dot-asm** [openssl/openssl#5505]
Trouble with build_all_generated is that when output ~for~ from perlasm script is .S file, it calls current compiler [to pre-process .S], but it's not given that current compiler is aware of the target compiler's options or pre-defines relevant values. In other words assumption that target compiler can be completely different from current one at build_all_generated stage is meaningful and useful. It's kind of pre-cross-compile scenario. I mean compilation itself might be non-cross-compile, but build_all_generated ~itself is~ could be. For this we would have to split .pl -> .s rule to two, .pl -> .S and .S -> .s. Just in case why not .S -> .o. It doesn't work *universally*. I mean it does work on most contemporary platforms, but there are some corner cases...

**Comment by dot-asm** [comment]
> Just in case why not .S -> .o. It doesn't work universally.

Well, straightforward .S -> .o doesn't work universally, but it should be possible to merge .S -> .s -> .o, effectively same way .pl -> .S -> .s is merged.

**Comment by levitte** [comment]
Soooo, is it something like this that you're asking for?

``` diff
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index fd1f10948a..10f70ee9c6 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -877,13 +877,16 @@ EOF
           } -> {$args{intent}};
           if (defined($generator)) {
               # If the target is named foo.S in build.info, we want to
-              # end up generating foo.s in two steps.
+              # end up generating foo.s in two steps.  Just to make sure
+              # we don't mess up on case independent file system, the
+              # intermediary file is named foo.s.S .
               if ($args{src} =~ /\.S$/) {
                    (my $target = $args{src}) =~ s|\.S$|.s|;
                    return <<"EOF";
-$target: $args{generator}->[0] $deps
+$target.S: $args{generator}->[0] $deps
+       $generator \$@
+$target: $target.S
        ( trap "rm -f \$@.*" INT 0; \\
-         $generator \$@.S; \\
          \$(CPP) $incs $cppflags \$@.S | \\
          \$(PERL) -ne '/^#(line)?\\s*[0-9]+/ or print' > \$@.i && \\
          mv -f \$@.i \$@ )
```

**Comment by dot-asm** [comment]
This is just splitting the rule, but problem runs a little bit deeper. make build_all_generated should not aim for generating .s, but .S. So that it would be compiler on the target system that would preprocess them. I've figured it out how to do that... As well as how to split the rule... I feel that it would be appropriate to merge the .S->.s with .s->.o in way similar to current .pl->.S->.s...

**Comment by levitte** [comment]
So basically, you want to duplicate the `$(CPP) | $(PERL)` combination to `sub src2obj`, and shorten .pl->.S->.s to be just .pl->.S, did I get that right?

**Comment by dot-asm** [comment]
> did I get that right?

Yes. [I can do that, we if you want to, then go ahead. Just in case, even 1.1.0 should be the target. This is because build_all_generated was taken there.]

**Comment by levitte** [comment]
(Be my guest, I'll be sure to review ;-) )
