### ISSUE TITLE
1.1.1 -> RAND_load_file() does not accept special files

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#5511]
Since commit 9ee344f5cd5e ("Cleanup RAND_load_file,RAND_write_file") it is no longer possible to do
    RAND_load_file("/dev/urandom", 512);

The commit argues that the source contains a comment that only regular files should be used. This has never been documented in the man-page, still works in 1.1.0.
Looking at the code I can't see why this would not work for a char or dev file. This is seems to break a testsuite so far but I still investigate…
However changing code on 1.1.0->1.1.1 which should be a drop-in replacement does not look right.

**Comment by richsalz** [comment]
It's a bug that it used to work.  The docs for 1.1.0 say "file" and do not mention "device" at all.

**Comment by sebastianas** [comment]
On 2018-03-04 21:01:20 [+0000], Rich Salz wrote:
> It's a bug that it used to work.  The docs for 1.1.0 say "file" and do not mention "device" at all.

Yes. It does not say "plain/regular file" it says "file". Same a
character file, device file. The `read()' man page also says 
	pread, read — read from a file

and works with _all_ files.
What I don't don't understand is what you gain by excluding char and
device files. Imho it would just work perfectly if you limit the
`stat()' check to regular files only for `max_bytes' < 0.
Do you mind a patch doing that?

> 
Sebastian

**Comment by richsalz** [comment]
Fine.

**Comment by bernd-edlinger** [comment]
The main difference between disk files and device files is
that EINTR makes the function RAND_load_file fail.
Reading devices with fread is not especially safe.
See #2045 for more details.

**Comment by bernd-edlinger** [comment]
That is no issue with disk files (neither with nfs mounts
either, when the kernel is not very old)

**Comment by sebastianas** [comment]
Well, it is true that linux tries to avoid returning EAGAIN/ERESTARTSYS on regular files and it might happen for dev/urandom if a signal is raised. The POSIX spec [fread](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html) points to [fgetc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fgetc.html) for errors and that one says that EINTR is a valid error that might be returned and it should be considered.

**Comment by bernd-edlinger** [comment]
Sure it can probably be solved but it will look ugly. Standard I/O is just not the right API for devices.
For instance if you want to open a tty device the open can block and wait for the carrier detect
signal, unless you use O_NONBLOCK.
And you should use O_NOCTTY or the device might become the controlling tty device.
I think a device should use low level APIs like open, read, select, close.
Especially when you are not sure what device you actually want to open.

**Comment by mspncp** [comment]
> I think a device should use low level APIs like open, read, select, close.

Good point. Given that statement, isn't it a logical consequence that `RAND_load_file()` should actually be using `open/read/close` instead of `fopen/fread/fclose` in the first place? After all, it's only reading chunks of binary data.

**Comment by bernd-edlinger** [comment]
not soure how that plays with VMS

**Comment by richsalz** [comment]
Using standard i/o should handle all the messy eintr/buffering/refill stuff.  I ripped out read(2) for fread(3) because it's much cleaner and it should work fine.

**Comment by mspncp** [comment]
Well, then it's probably not worth changing anything. Calling `RAND_load_file("/dev/urandom", ...)` is obsolete for the new OpenSSL CSPRNG anyway.

**Comment by sebastianas** [comment]
On 2018-03-07 13:13:31 [+0000], Rich Salz wrote:
> Using standard i/o should handle all the messy eintr/buffering/refill stuff.  I ripped out read(2) for fread(3) because it's much cleaner and it should work fine.

If you ask for 512 bytes and receive 64 then the fread() will read up
the remaining bytes but it will likely read 4KiB into its internal
buffer.
If you receive EAGAIN/EINTR due to a signal (which happens on Linux if
the signal was sent before the kernel started to fill user's buffer)
then it (fread()) will do nothing but return 0 and will have ferror()
set and errno will be set properly so you have to retry yourself. I have
no idea what happens for !LINUX || !GLIBC. 

I could come up with a nice read() loop here.
I could add a fix for the missing EINTR consideration.

If it stays as it and remains only valid for regular files (which
forbids /dev/urandom for instance) then it won't be a simple replacement
for 1.1.0 and should be documented properly. And it could be fixed one
way or another.

Sebastian

**Comment by mspncp** [comment]
In 1.1.1 it is not necessary anymore to call RAND_load_file() to read from the random device manually. One can just call [RAND_poll()](
https://github.com/openssl/openssl/blob/master/crypto/rand/rand_lib.c#L405]), then the RNG will reseed automatically using os specific random sources. The default implementation for linux will first attempt to use [getrandom()](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_unix.c#L173) and only after that try the list of random devices configured in [DEVRANDOM](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_unix.c#L187). The reading is done [using streams](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_unix.c#L196). So if you want to fix it in RAND_load_file(), please fix it in rand_unix.c, too.

**Comment by ciz** [comment]
This OpenSSL 1.1.1 change in behavior breaks OpenSSH on at least Red Hat and SUSE, as they are both using RAND_load_file("/dev/urandom").
https://src.fedoraproject.org/rpms/openssh/blob/master/f/openssh-6.6p1-entropy.patch#_80

**Comment by richsalz** [comment]
Sigh.  So what should we do?  Just try to read 256 bytes and add in whatever we get back?

**Comment by bernd-edlinger** [comment]
Note: the code in question did never work reliably with device files.

**Comment by sebastianas** [comment]
On 22 March 2018 14:01:55 CET, Rich Salz <notifications@github.com> wrote:
>Sigh.  So what should we do?  Just try to read 256 bytes and add in
>whatever we get back?

I will add a open/read loop and handle error codes. 

Sebastian

**Comment by richsalz** [comment]
See #5728.  Also recall the discussion in https://github.com/openssl/openssl/pull/2045

**Comment by sebastianas** [comment]
Argh. So I read the discussion in #2045 but missed your pulled in #5278.
