### ISSUE TITLE
1.1.1 -> ./Configure script uses enviroment variables

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#5512]
Commit 89bea0830de9 ("Make it possible to add env var assignments as Configure options") adds support for something like 
   ./Configure CC=clang linux-x86_64
but what it also supports is
  export CFLAGS=Option
  ./Configure linux-x86_64
I'm not sure if this is intentional or not but this works. The problem I have with the latter is that the Debian build system sets CFLAGS (and others) before calling the script. In the Debian specific config we set CFLAGS and inherit from linux-x86_64 for x86-64. With Configure taking CFLAGS from the environment we lose all that.

Is this "options via environment" intentional or not? The example looks like commandline is planned.
Should I add an option which does not consider the environment options or should I instead make sure that the environment is clean?

**Comment by kroeckx** [comment]
I think the intention is to support what GNU supports, which I think supports both. We might have to adjust the Debian packaging for it. But @levitte will probably know.

**Comment by levitte** [comment]
Yes, that's exactly the intention

**Comment by dot-asm** [comment]
> Yes, that's exactly the intention

And at some point I argued that it's not exactly right. Our compiler flags defined through config targets should not be override-able by environment variables, environment variable flags should be instead added/merged. [Or related note this is exactly the kind of problem when immediate visual feedback, i.e. 2nd idem #5248, would be indispensable to trouble-shoot :-)]

**Comment by petrovr** [comment]
I did not understand issue. If many build system comands
$ CFLAGS="..." config-script
and
$ config-script  CFLAGS="..."
produce one and the same result.


I agree with Andy that flags from environment should be merged with project flags.
Usually autotool based scripts append project flags to user specified  (CFLAGS, LDFLAGS) and prepend paths (-I, -L ) that point to build or source tree.
Merge of flags is separate issue.

**Comment by levitte** [comment]
Thanks for the reminder, I meant to do something about the "overridable" flags vs the project ones, and I do have an idea to how to do that as well. Coming in a PR later today or tomorrow.

**Comment by levitte** [comment]
The autotools actually have a concept of user flags (usually the optimize and debug flags), which are overridable by things like CFLAGS, and flags that are "discovered" by autoconf....

**Comment by sebastianas** [comment]
On 2018-03-05 11:13:01 [+0000], Richard Levitte wrote:
> The autotools actually have a concept of user flags (usually the optimize and debug flags), which are overridable by things like CFLAGS, and flags that are "discovered" by autoconf.... 

Exactly. The remaining cflags which were supposed to be set within the
autotools project are still set. I think is also true for CPPFLAGS and a
few other.
Only the command options (CC, LD, AR and so on) are overwritten as far
as I remember.

**Comment by levitte** [comment]
Well, it's probably true for command variables as well, *if* someone thinks it's a good idea to extend them with a flag (which I believe is fairly unlikely, but not entirely unheard of)

**Comment by bernd-edlinger** [comment]
I think the GNU build system uses CFLAGS to override completely
and usually something like AM_CFLAGS to add additional options,
The option can be given at ./config or as make arguments

**Comment by bernd-edlinger** [comment]
From the autoconf documentation I read:
CFLAGS, LDFLAGS, CPPFLAGS are primarily user flags.
However CFLAGS has a default of "-g -O2" when not given by the user.
Flags that the package needs for proper operation go
to AM_CFLAGS, AM_LDFLAGS, AM_CPPFLAGS or similar, is that correct?

**Comment by levitte** [comment]
Yes, that's exactly right.

**Comment by levitte** [comment]
We have something similar in our build files, theoretically separated by type of thing being built, prefixed `LIB_`, `DSO_` and `BIN_` instead of `AM_`.  All we need to do is make better use of those...

**Comment by levitte** [comment]
(like I said, coming up)

**Comment by petrovr** [comment]
Bernd Edlinger wrote:
>  From the autoconf documentation I read:
> CFLAGS, LDFLAGS, CPPFLAGS are primarily user flags.
> However CFLAGS has a default of "-g -O2" when not given by the user.
> Flags that the package needs for proper operation go
> to AM_CFLAGS, AM_LDFLAGS, AM_CPPFLAGS or similar, is that correct?

No as many projects does not use automake .

**Comment by levitte** [comment]
> No as many projects does not use automake .

Well, that *was* a comparison with the GNU autotools, specifically

**Comment by levitte** [comment]
If anyone's interested, #5534

**Comment by dot-asm** [comment]
This one is ready to be closed?

**Comment by sebastianas** [comment]
yes, I tested on the master branch and works great. Thanks.
