### ISSUE TITLE
BN_clear_free vs BN_free inconsistency 

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#5517]
It is expected behaviour of functions to be same except as is documented "BN_clear_free() additionally overwrites the data before the memory is returned to the system", quoted from https://www.openssl.org/docs/man1.1.0/crypto/BN_clear_free.html .

Unfortunately in 1.1.0 branch clear is performed even data is non fried. It seems to me issue is fixed in master.

I would like to request manual page to be updated to inform that BN_clear_free has bug in 1.1.0.

For instance following snipped could demonstrate defect.
  d2 = BN_new();
  BN_with_flags(d2, d1, 0);
  BN_clear_free(d2);   <- error d1 is cleared as well

**Comment by richsalz** [comment]
That's a bug and we should fix the *code* not the docs.  Thanks for reporting it.

**Comment by petrovr** [comment]
Rich Salz wrote:
> That's a bug and we should fix the *code* not the docs.  Thanks for reporting it.

Actually it is long standing bug.

BN_with_flags is added after 0.9.7g and BN_clear_free() is from SSLEay 
code 0.9.1c.

So idea is to write that 1.1.1 is first version that allows 
BN_clear_free() for number initialized by BN_with_flags().

Code correction by 5f2d9c4d26c923ece6ee04616a2d32a1afc124c8

Regards,
Roumen

**Comment by mattcaswell** [comment]
Well using BN_with_flags() brings with it a set of restrictions which are clearly documented in the man page:

````
BN_with_flags creates a B<temporary> shallow copy of B<b> in B<dest>. It places
significant restrictions on the copied data. Applications that do no adhere to
these restrictions may encounter unexpected side effects or crashes. For that
reason use of this function is discouraged. Any flags provided in B<flags> will
be set in B<dest> in addition to any flags already set in B<b>. For example this
might commonly be used to create a temporary copy of a BIGNUM with the
B<BN_FLG_CONSTTIME> flag set for constant time operations. The temporary copy in
B<dest> will share some internal state with B<b>. For this reason the following
restrictions apply to the use of B<dest>:

=over 2

=item *

B<dest> should be a newly allocated BIGNUM obtained via a call to BN_new(). It
should not have been used for other purposes or initialised in any way.

=item *

B<dest> must only be used in "read-only" operations, i.e. typically those
functions where the relevant parameter is declared "const".
````

It seems clear to me that BN_clear_free() could not be classed as a "read-only" operation. So, I don't think this is really a bug - it's just another manifestation of the underlying restrictions of BN_with_flags(). The fact that you can do it in master is co-incidental - you shouldn't really be doing it there either. It just happens to work.

**Comment by mattcaswell** [comment]
Closing as not-a-bug.
