### ISSUE TITLE
DNS Nameconstrains rejecting all certificates with a CN name

### ISSUE THREAD

**Issue by luizluca** [openssl/openssl#5521]
Our internal CA restricts dnsnames to .mydomain.com. So, only xxx.mydomain.com dns names are valid.
It also restricts subject subtree (DC = com, DC = mydomain), but I guess it is not related.

Since 5bd5dcd49605ca2aa7931599894302a3ac4b0b04, openssl started to check CN values against name constraints. The commit message even tells that this check is not present in RFC. A Subject like:

DC = com, DC = mydomain, OU = Computers, CN = xxx
(very common in Active Directory)

If pass the check asn1_valid_host(), I'll check my dnsnames restrictions against CN value. Obviously, xxx will not match .mydomain.com. Is this really expected? Wouldn't it be safer to check CN only when it contains a domain, like /[a-z]+\.[a-z]+/ ?

Am I getting something wrong? Updating OpenSSL will make hundreds of certificates invalid.

**Comment by luizluca** [comment]
I did a simple patch in order to disable CN name constraints. It did solve my problem but left unused code:

https://github.com/openssl/openssl/compare/OpenSSL_1_1_0-stable...luizluca:disable_NAME_CONSTRAINTS_check_CN?expand=1

**Comment by mattcaswell** [comment]
I'm not sure why the commit message in 5bd5dcd suggests the RFC doesn't require this check. My reading of the RFC suggests that the check is required:

````
   The name constraints extension, which MUST be used only in a CA
   certificate, indicates a name space within which all subject names in
   subsequent certificates in a certification path MUST be located.
   Restrictions apply to the subject distinguished name and apply to
   subject alternative names.
````
And a bit later on:
````
   If a name constraints extension that is marked as critical
   imposes constraints on a particular name form, and an instance of
   that name form appears in the subject field or subjectAltName
   extension of a subsequent certificate, then the application MUST
   either process the constraint or reject the certificate.
````

So it seems to me we are doing the right thing.

**Comment by richsalz** [comment]
But not if the CN isn't a hostname.  For example, see https://www.ietf.org/mail-archive/web/pkix/current/msg27675.html

**Comment by richsalz** [comment]
I mean, not if the cert is for TLS server-auth.

**Comment by mattcaswell** [comment]
> But not if the CN isn't a hostname

Right - so presumably that's why the above commit introduces the `asn1_valid_host()` check. If it conforms to the rules of a hostname, then we treat it as a hostname.

**Comment by luizluca** [comment]
@richmoore ,

AFAIK, CN is only used by clients when there is no subjectAltName or if it does not understand subjectAltName extension (is there any serious SSL that does not use it yet?). It is probably not a requirement but If nameconstraints is implemented in client SSL library, it might also understand subjectAltName. If client does not understand nameconstraints and if is marked as critical, cert is rejected. If it does understand it, only subjectAltName will be used by client to check service DNS and CN will not be used. CN will only be used when there is no subjectAltName. IMHO, if there is any subjectAltName, DNS nameconstraints must not be checked against CN, no matter what format it contains. If we are debating about it, perhaps RFC is simply not clear enough. 

Considering that I'm wrong and it must check CN against DNS nameconstraints even when subjectAltName is present, asn1_valid_host is still too flexible. It accepts any CN that does not have an invalid char. Wouldn't it be safer if if requires a dot between [:alnum:]? Checking a non FQDN against DNS nameconstraints does not make sense.

RFC cites that "subject distinguished name" and "subject field" must be checked against nameconstraints. Remeber that nameconstraints is not only about DNS. There is DirName, which must be checked against "subject distinguished name". Maybe RFC was mentioning DirName in that case.

Keep in mind that this change invalidated all certificates that were issued by (but not only) M$ CA when there is any DNS name constraint. Is this really what we want?

At least M$ SSL and gnutls does check nameconstraints this way.

**Comment by mattcaswell** [comment]
I would be interested in hearing @vdukhovni's opinion on this.

**Comment by vdukhovni** [comment]
What was the actual CN in this case.  Was it an FQDN?  Or just a bare hostname?
It looks like asn1_valid_host() considers too many strings to valid hostnames.  I'd like to remove that function entirely,, and check the name after conversion to UTF8 at:

  https://github.com/openssl/openssl/commit/5bd5dcd49605ca2aa7931599894302a3ac4b0b04#diff-caf502a9d3e53f3b21e77e5e324b62b4R257

As for generally checking the CN, since name checks might (stilll) be done by the application and not OpenSSL, and the application might accept the CN even if DNS-ID SANs are present, or not look at the SANs at all, we should still check the CN against any DNS name constraints, when the CN is a plausible DNS-ID name.  We could perhaps make a special case for applications that enable the internal name checks, which we know to handle DNS-ID SANs correctly.

**Comment by vdukhovni** [comment]
Please test PR #6265

**Comment by luizluca** [comment]
@vdukhovni , it works for me. Before PR #6265:

Verify return code: 47 (permitted subtree violation)

After PR #6265:

Verify return code: 0 (ok)

**Comment by richsalz** [comment]
The fix was merged, closing this issue.
