### ISSUE TITLE
AEAD: the CAESAR finalists

### ISSUE THREAD

**Issue by paragonie-scott** [openssl/openssl#5524]
The [CAESAR](https://competitions.cr.yp.to/caesar.html) competition just announced its finalists: https://twitter.com/TomerAshur/status/970743450764283905

| Algorithm | Use Case |
|-----------|-----------|
| ACORN   | Lightweight AEAD |
| AEGIS     | Normal AEAD |
| Ascon     | Lightweight AEAD |
| COLM    | Nonce-misuse resistant AEAD |
| Deoxys-II | Nonce-misuse resistant AEAD |
| MORUS | Normal AEAD |
| OCB | Normal AEAD|

Although there is still time for last-minute cryptanalysis before the final CAESAR portfolio is published, you can anticipate a push for at least some of these ciphers to be included in TLS in the near future.

**Comment by tarcieri** [comment]
Perhaps someone could pick up this draft to support OCB mode: https://tools.ietf.org/html/draft-zauner-tls-aes-ocb-04

**Comment by mattcaswell** [comment]
That draft has expired and hasn't seen any activity in nearly 2 years, so it doesn't look very alive. You could ping Aaron Zauner to see if he is interested in picking it back up again.

**Comment by randombit** [comment]
@mattcaswell FWIW Botan implements the TLS-OCB ciphersuites from draft-04. If you're interested I could set up a test server.

**Comment by mattcaswell** [comment]
> @mattcaswell FWIW Botan implements the TLS-OCB ciphersuites from draft-04. If you're interested I could set up a test server.

Thanks - I'll keep that in mind for if this draft wakes up again. Without it coming out of draft though it won't get implemented in OpenSSL (because we have a policy of not implementing non-standardised crypto) so there is probably no point in setting up a test server at this point.

**Comment by funny-falcon** [comment]
Isn't it interesting to inplement AEGIS - fastest cipher (on platform with AES support)? 0.66 cycle per byte on Snady Bridge for 4096 byte message - it is quite impressive compared with 2-3cpb for AES128-GCM

**Comment by romen** [comment]
> Isn't it interesting to inplement AEGIS - fastest cipher (on platform with AES support)? 0.66 cycle per byte on Snady Bridge for 4096 byte message - it is quite impressive compared with 2-3cpb for AES128-GCM

It is interesting, but our policy requires any of the finalists in the portfolio to be part of a published standard for being included and maintained as part of the codebase.

That being said, with the new provider architecture it should be quite easy to plug in this functionality as an external provider to provide this capability to applications that want to use `libcrypto`.

**Comment by paulidale** [comment]
Nothing is preventing the work being done to incorporate the new ciphers, it is just unlikely to be accepted until it is standardised.  As @romen mentioned, the new provider architecture is ideal for this -- implement it in your own provider and when the standard is done, it will come across smoothly.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by ghen2** [comment]
> Isn't it interesting to inplement AEGIS - fastest cipher (on platform with AES support)? 0.66 cycle per byte on Snady Bridge for 4096 byte message - it is quite impressive compared with 2-3cpb for AES128-GCM

FWIW: there's an implementation for OpenSSL 3.4 and 3.5 here: https://github.com/aegis-aead/openssl/

Re. standardisation, there's an active [draft-irtf-cfrg-aegis-aead](https://datatracker.ietf.org/doc/draft-irtf-cfrg-aegis-aead/), and IANA has assigned TLS cipher suite code points:
`0x13,0x06	TLS_AEGIS_256_SHA512 `
`0x13,0x07	TLS_AEGIS_128L_SHA256`
