### ISSUE TITLE
Typo in documentation for i2d_TYPE for 1.1.0 and above

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#5527]
https://www.openssl.org/docs/man1.1.0/crypto/i2d_X509.html

The article makes multiple references to "out" but "out" is not a variable for the function, "pp" is. This seems to be a carryover from the 1.0.2 documentation where it was "out" for i2d_X509.

**Comment by mspncp** [comment]
This has been fixed for master by #5365. I'll have a look whether the fix can be cherry-picked.

**Comment by mspncp** [comment]
PR #5365 has been merged now to OpenSSL_1_1_0-stable (9d927ddf1c74). Thanks for reporting!
