### ISSUE TITLE
Typo in documentation for BN_bn2bin

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#5536]
https://www.openssl.org/docs/man1.1.0/crypto/BN_bn2dec.html

> BN_bn2hex() and BN_bn2dec() return printable strings containing the hexadecimal and decimal encoding of a respectively. For negative numbers, the string is prefaced with a leading '-'. The string must be freed later using OPENSSL_free().

"respectively" is not a noun. This issue also exists in 1.0.2 documentation.

**Comment by richsalz** [comment]
This is a bug, I guess, in pod2html.  The "a" is a parameter, and marked with B<>.
