### ISSUE TITLE
SSL_CTX_set_cert_store() does not call X509_STORE_up_ref()

### ISSUE THREAD

**Issue by sgobiraj** [openssl/openssl#5538]
I have a global X509_STORE that is shared by multiple SSL_CTX objects. SSL_CTX_set_cert_store() function does not call X509_STORE_up_ref() but it calls X509_STORE_free() when being replaced or when the SSL_CTX_free() is called. This leads to the X509_STORE being destroyed while other SSL_CTX objects maybe referencing it. I don't get why on an SSL_CTX_free() it is doing an X509_STORE_free() but never does an X509_STORE_up_ref() when doing the SSL_CTX_set_cert_store() in the first place. The way I'm getting around this is by doing the X509_STORE_up_ref() myself when I do the SSL_CTX_set_cert_store(). However I'm not sure if this is a bug or by design. I don't see the rationale behind it if it is by design.

**Comment by kaduk** [comment]
It is by (flawed) design.  Consulting, e.g., https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_cert_store.html, we find that:

> SSL_CTX_set_cert_store() does not increment the store's reference count, so it should not be used to assign an X509_STORE that is owned by another SSL_CTX.

> To share X509_STOREs between two SSL_CTXs, use SSL_CTX_get_cert_store() to get the X509_STORE from the first SSL_CTX, and then use SSL_CTX_set1_cert_store() to assign to the second SSL_CTX and increment the reference count of the X509_STORE.

That is, the SSL_CTX_set1_cert_store() is more like what you expect the API to be, but the behavior of SSL_CTX_set_cert_store() is what it is and cannot be changed without breaking existing programs.
