### ISSUE TITLE
Missing man page for deprecated public CMAC_* functions

### ISSUE THREAD

**Issue by Hal-Murray** [openssl/openssl#5539]
After a fresh clone:
```
[murray@hgm openssl]$ grep CMAC doc/ -r
doc/man3/EVP_PKEY_CTX_ctrl.pod:and B<p2> is MAC key. This is used by Poly1305, SipHash, HMAC and CMAC.
[murray@hgm openssl]$ 
```

**Comment by kroeckx** [comment]
So there are at least 2 relevant stackoverflow questions related to this:
https://stackoverflow.com/questions/28354844/how-to-calculate-aes-cmac-using-openssls-cmac-xxx-functions
https://stackoverflow.com/questions/34990080/cmac-key-generation-with-openssl-evp-digestsign-fails

We also have an EVP_PKEY_new_CMAC_key(), which we should probably encourage to be used instead of the CMAC interface.

**Comment by slontis** [comment]
The new interface EVP_MAC can now be used.
See also EVP_MAC_CMAC.
There is documentation (.pod files) for these.

**Comment by mattcaswell** [comment]
> The new interface EVP_MAC can now be used.

Current this is master only - so not in any stable release.

**Comment by slontis** [comment]
Can this be closed now? There is a stable 3.0 release that contains the EVP_MAC_CMAC interface

**Comment by t8m** [comment]
Well... the CMAC_ public functions are deprecated but still there so the bug is still relevant although definitely not a priority to fix.

**Comment by Hal-Murray** [comment]
> Can this be closed now? There is a stable 3.0 release that contains the
> EVP_MAC_CMAC interface 

I think so.

It would be nice if there was a web page discussing this area.  I assume the 
lack of web pages was because it wasn't a good/clean API appropriate for 
public use.  But I'm not the only one who found it and figured out how to use 
it.  Explaining that whold area may take more than a simple web page or more 
time to make it small/clean than is available.

Many many years ago, the group I worked with had 3 types of APIs.  In addition 
to public and private, there was also friends.  Friends covered the case of a 
legitimate use case that wasn't covered by the public APIs.  There were few 
users and they were expected to modify their code if/when things changed.  It 
was the sort of cooperative work that is much easier in small groups.


-- 
These are my opinions.  I hate spam.

**Comment by erbsland-dev** [comment]
@t8m I can create a PR that includes man pages for the deprecated functions, pointing to the new ones, if this is still desired.

In my experience, having these man pages significantly aids in the migration efforts of older code. To keep the effort low, I wouldn’t explain the functions in detail on these man pages, as the new functions are already sufficiently documented.

**Comment by t8m** [comment]
Yes, surely a PR adding the documentation even for deprecated functions would be welcome.
