### ISSUE TITLE
bad decrypt:../crypto/evp/evp_enc.c:540

### ISSUE THREAD

**Issue by Guiraud** [openssl/openssl#5541]
Hi, while decrypting a file I get this error.
Only on my debian 9 Stretch thougth.
the openssl version is 1.1.0f

On Jessie it's 1.0.1t
the command is  : 
openssl enc -d -aes-128-cbc -md md5-K xxxxxxxxxxxxxxx -iv yyyyyyyyyyyyyyyyy -in input.zip -out decrypt.zip
Since the key and pass works on an other  OS I wouldn't target he key issue. the complete error is  : 
bad decrypt
140404913980672:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:540:

**Comment by mattcaswell** [comment]
So you used "-md md5" on both platforms? Normally this error occurs due to this:

https://www.openssl.org/docs/faq.html#USER3

But that only applies if you haven't specified "-md".

**Comment by Guiraud** [comment]
It happens with or without -md md5. I tryed with -md SHA256 too. On Jessie we don't put the md sequence.

**Comment by Guiraud** [comment]
If it helps. I tryed to change the version of openssl with or without "-md" : 
$ openssl version
OpenSSL 1.0.1t  3 May 2016 (Library: OpenSSL 1.0.2l  25 May 2017)
$ openssl enc -d -aes-128-cbc -K xxxxxxxxxxxxxx -iv yyyyyyyyyyy -in input.zip -out decrypt.zip
bad decrypt
140047127731736:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:536:

**Comment by mattcaswell** [comment]
> $ openssl version
OpenSSL 1.0.1t 3 May 2016 (Library: OpenSSL 1.0.2l 25 May 2017)

That indicates a problem with the OpenSSL install in your test. The command line version and the library version should match. Here you have a 1.0.1 command line with a 1.0.2 library.

Using your 1.1.0f version please report the output from 

````
$ openssl version -a
````

**Comment by Guiraud** [comment]
This version seems to work on other computers with Jessie. While I'm quite sure this is not the issue, I kept this one.
$ openssl version -a
OpenSSL 1.0.1t  3 May 2016 (Library: OpenSSL 1.0.2l  25 May 2017)
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/lib/ssl"

**Comment by Guiraud** [comment]
Ok I found the issue. I feel really sorry for myself. I wasn't writing the path after the "-in" and the "-out".

**Comment by mattcaswell** [comment]
Great - I'm glad you found the issue. Closing this.

**Comment by mnr31** [comment]
40409129530688:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:610:
 i am getting same error
