### ISSUE TITLE
Build process may fail if source directory != build directory

### ISSUE THREAD

**Issue by stu003** [openssl/openssl#5543]
https://github.com/openssl/openssl/blob/72983c0eab750dfc1b6298c516df7afb1a73ba54/Configure#L2098

Here `$srcdir` should be replaced with `$blddir` since `$d` enumerates keys from `%{$unified_info{depends}->{$dest}}` hash, which was previously populated with paths relative to the build directory.

For example, if the source is placed in:
```
/Users/denis/Backup/source/openssl-1.1.1-pre2
```
and the current build directory is:
```
/Users/denis/Backup/Garbage/_build/nav2020/ios_OPENSSL
```
then the current version fails with the following message:
> Configuring OpenSSL version 1.1.1-pre2 (0x10101002L) for ios-cross
> Using os-specific seed configuration
> mkdir /Users/denis/Backup/source/openssl-1.1.1-pre2/../../../../source: Permission denied at /Users/denis/Backup/source/openssl-1.1.1-pre2/Configure line 1528.

This is because the path:
```
/Users/denis/Backup/source/openssl-1.1.1-pre2/../../../../source
```
actually points to `/Users/source`, whereas if `/../../../../source` were appended to the build directory (see above), it would've resulted in:
```
/Users/denis/Backup/source
```
which is the valid directory location.

**Comment by stu003** [comment]
Sorry, I can check this not earlier than the next Monday. As I remember, the value of `$d` that caused the problem was `../../../../source/configdata.pm` or maybe some other file in the source directory.

**Comment by stu003** [comment]
No, I haven't built in the source directory previously. I tried a clean build in another directory as I described above.

**Comment by levitte** [comment]
Odd, because the fault in question happens if there's a `configdata.pm` in the source directory, and that only happens if someone configured while standing in the source directory.

**Comment by stu003** [comment]
Could this path still somehow occur in the depends hash? As I understand, physical presense of `configdata.pm` in the source directory isn't enough for that. And also, could other files that are actually present in the source tree, for example, `.h` files, result in the same behavior?

**Comment by levitte** [comment]
No, the error only happens for files that are supposed to be generated in the build tree but is found in the source tree.  And only if that file is one of the values of a `DEPEND` command in a `build.info` file...  and only if it's not the goal of a `GENERATE` line...  I think there's only `configdata.pm` left that can exhibit this anomaly.

But in any case, regardless of exactly which files, you were entirely correct that the `cleandir` call that you pointed at was unnecessary.

#5546 hopefully fixed all that, I hope.  Please try it out.

**Comment by stu003** [comment]
Thanks! Sorry, will be able to test this only on Monday.

**Comment by stu003** [comment]
Yes,  906032d fixes the problem. Btw, I've found `configdata.pm` in the source directory. Now the build doesn't fail even if this file is present there.

**Comment by levitte** [comment]
Cool. Thanks!
