### ISSUE TITLE
SSL_stateless failure is ambiguous

### ISSUE THREAD

**Issue by Ralith** [openssl/openssl#5549]
`SSL_stateless` does not appear to directly communicate whether "failure" indicates a HelloRetryRequest was sent or an unrecoverable error occurred. A QUIC implementation needs to distinguish between these cases so that it can determine whether to reply with a CONNECTION_CLOSE message.

Is it intended that the caller inspect the error stack, and interpret an empty error stack as indicating that a HelloRetryRequest was generated? If so, I'll make a documentation PR to clarify this. If not, perhaps an additional return value should be defined?

cc @mattcaswell

**Comment by mattcaswell** [comment]
Fix for this in #5562.
