### ISSUE TITLE
OPENSSL_SYS_WIN32 vs OPENSSL_SYS_WINDOWS vs WIN32 vs _WIN32

### ISSUE THREAD

**Issue by mcr** [openssl/openssl#5557]
It seems that OPENSSL_SYS_WINDOWS is not set for mingw cross compilation.
Conversely, WIN32 is not set for (64-bit?) Windows (appveyor) builds.
We have code that tests for _WIN32 as well.

Shouldn't mingw builds and native builds see essentially the same set of defines?

**Comment by levitte** [comment]
Hmmm, mingw compilers do defined `_WIN32` or `_WIN64`, don't they?  In that case, `include/openssl/e_os2.h` *should* defined `OPENSSL_SYS_WIN32` or `OPENSSL_SYS_WIN64`, and also `OPENSSL_SYS_WINDOWS` by consequence...

`WIN32` is defined in `e_os.h`....  aaaaand I'm not too sure about that one.

`_WIN32` is pre-defined by the macro, and it's true that we have a lot of code that check this directly rather than `OPENSSL_SYS_` macros...  there are different schools of thought among developers on the subject of what to use.  I cannot say what is the better way.

**Comment by mcr** [comment]
Yes, MINGW defines _WIN32. I didn't check inf they defined _WIN64 or not.
64-bit builds seem to define _WIN32.

e_os2.h would be a great place to fix this and then change all the references to _WIN32 to
OPENSSL_SYS_WINDOWS (unless it really cares about 32/64-bit builds, which should be rare).

**Comment by levitte** [comment]
Oh boy...  I think that the current school of thought is to trust the compiler, i.e. prefer `_WIN32` over the `OPENSSL_SYS_` stuff...

**Comment by levitte** [comment]
Move to post-1.1.1

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by rsbeckerca** [comment]
Last I tried (4 months), MINGW did not define _WIN64 but did _WIN32. I think this is an active interest given that _WIN32 is still an active interest.

**Comment by nhorman** [comment]
I'm not sure I agree there is active interest here, given that the last comment was over 6 years ago.

But sure, we can look at it still.  @mcr can you provide a proposal about what specifically  should be done to reconcile this inconsistency?

**Comment by nhorman** [comment]
no response from @mcr , @rsbeckerca do you have interest in creating a PR for this?

**Comment by rsbeckerca** [comment]
> no response from @mcr , @rsbeckerca do you have interest in creating a PR for this?

@nhorman What did you have in mind in terms of the PR contents?

**Comment by nhorman** [comment]
honestly unsure, I only ask you @rsbeckerca because you noted some experience cross-compiling with mingw above.

If there is no active interest here though, I'll just mark this as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by rsbeckerca** [comment]
> honestly unsure, I only ask you @rsbeckerca because you noted some experience cross-compiling with mingw above.
> 
> If there is no active interest here though, I'll just mark this as inactive, to be closed at the end of 3.4 dev barring further input

Interesting thought. My experience with Mingw is really not productive. I've tried to use dlopen and automatic dll loads, which crash 100% of the time in my tool chain. I would like to do this, but am not confident of being able to make it work.

**Comment by mcr** [comment]
Hi, I don't do Windows. I only experienced this, noticed this, because of CI runs.
I can't offer advice: the project will have to decide what (cross-)compilers are important, and what symbols the project intends to depend upon.

**Comment by rsbeckerca** [comment]
@nhorman Thinking about it, if have `OPENSSL_SYS_WINDOWS`, what does it mean? 32-bit? 64-bit? We need some differentiation between the two, so `OPENSSL_SYS_WINDOWS32` and `OPENSSL_SYS_WINDOWS64` set in `./Configurations` to avoid any confusion. This might result is a massive PR, and then does `OPENSSL_SYS_WINDOWS` mean either?

**Comment by nhorman** [comment]
from e_os2.h:

* OPENSSL_SYS_WINDOWS indicates the target platform is windows (64/32 bit agnostic)
* OPENSSL_SYS_WIN64 indicates the target platform sets _WIN64
* OPENSSL_SYS_WIN32 indicates the target platform set _WIN32

**Comment by rsbeckerca** [comment]
> from e_os2.h:
> 
>     * OPENSSL_SYS_WINDOWS indicates the target platform is windows (64/32 bit agnostic)
> 
>     * OPENSSL_SYS_WIN64 indicates the target platform sets _WIN64
> 
>     * OPENSSL_SYS_WIN32 indicates the target platform set _WIN32

So would the PR simply be replacing _WIN64 with OPENSSL_SYS_WIN64 and _WIN32 with OPENSSL_SYS_WIN32?

**Comment by nhorman** [comment]
possibly.  Though from this conversation, I'm getting the impression that none of us (myself definitely included) don't really understand the problem here.

I just setup mingw64 in msys2 here (our primary support platform), and it seems to build just fine (including defining OPENSSL_SYS_WINDOWS).  Granted thats not a cross-compliation target, but from looking at the platform list, all we support is mingw64 for a 64 bit target.

Given that the appveyor builds are all gone now (we don't even do mingw64 builds, which is likely its own issue), I'm not sure that we're going to get anywhere with this.

**Comment by FdaSilvaYY** [comment]
> > from e_os2.h:
> 
> > 
> 
> >     * OPENSSL_SYS_WINDOWS indicates the target platform is windows (64/32 bit agnostic)
> 
> > 
> 
> >     * OPENSSL_SYS_WIN64 indicates the target platform sets _WIN64
> 
> > 
> 
> >     * OPENSSL_SYS_WIN32 indicates the target platform set _WIN32
> 
> 
> 
> So would the PR simply be replacing _WIN64 with OPENSSL_SYS_WIN64 and _WIN32 with OPENSSL_SYS_WIN32 outside of e_os2.h?

_WIN32 is also defined for 64-bits toolchain, see MSDN

**Comment by rsbeckerca** [comment]
> > > from e_os2.h:
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * OPENSSL_SYS_WINDOWS indicates the target platform is windows (64/32 bit agnostic)
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * OPENSSL_SYS_WIN64 indicates the target platform sets _WIN64
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * OPENSSL_SYS_WIN32 indicates the target platform set _WIN32
> > > ```
> > 
> > 
> > So would the PR simply be replacing _WIN64 with OPENSSL_SYS_WIN64 and _WIN32 with OPENSSL_SYS_WIN32 outside of e_os2.h?
> 
> _WIN32 is also defined for 64-bits toolchain, see MSDN

Sounds like someone else should do this.

**Comment by rsbeckerca** [comment]
Let's drop it then. One question... I need to make some edits on the Community support list. May I ask where?

**Comment by nhorman** [comment]
@rsbeckerca are you referring to the list of community support platform owners?

You can open a pr in the general-policies repo, editing the file:
https://github.com/openssl/general-policies/blob/master/policy-supplemental/platforms.md

**Comment by rsbeckerca** [comment]
> @rsbeckerca are you referring to the list of community support platform owners?
> 
> You can open a pr in the general-policies repo, editing the file: https://github.com/openssl/general-policies/blob/master/policy-supplemental/platforms.md

Thanks. Done.
