### ISSUE TITLE
The output of 'openssl version -f', is it worth keeping as is?

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#5571]
With #5560, the output of `openssl version -f` changed, quite drastically.  On my laptop, it went from something like this:

```
: ; ./util/shlib_wrap.sh apps/openssl version -f
compiler: gcc -fPIC -pthread -m64  -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG
```

to this:

```
: ; ./util/shlib_wrap.sh apps/openssl version -f
compiler: gcc -pthread -m64  -Wa,--noexecstack -Wall -O3 -DNDEBUG
```

The question is, do we want that, or do we want the former display.  I'm ambivalent and seek input.

**Comment by richsalz** [comment]
I would like to see the full set of build flags.

**Comment by richsalz** [comment]
I might retract my comment.  What is the purpose of that output?  Is it to say how the *openssl* is built, or to say what flag a *program* needs to use openssl?  It's no longer sufficient for the former, and it never really worked for the latter.  So perhaps we remove it. And if we can't remove it now, then make it either the lib flags or the app flags, I guess, but make an explicit decision and update the manpage.

**Comment by levitte** [comment]
And therein lies the question, what's the purpose of display the flags?  If you're developing OpenSSL, you're much better off with the output of `perl configdata.pm --dump` or a direct study of the build file anyway...  and quite frankly, I'm not even sure it gives much of anything to someone who just want to link their program with libcrypto or libssl...  (actually, the output lacks the most crucial flags for anyone wanting to link with static libcrypto or libssl, the additional libraries that one needs to link with)

**Comment by levitte** [comment]
On the other hand, we also display very internal things, such as BN and cipher options...  so it seems like the display of "stuff" with `openssl version` is intended to show the internals, and in that case, the display of the library macros that are set on the command line makes sense.

**Comment by dot-asm** [comment]
> What is the purpose of that output? ... better off with the output of perl configdata.pm --dump

I'd say it's **post-installation** trouble-shooting thing, i.e. after you've deleted configdata.pm. It also tells something about how it's handled by distro vendors. I mean you can see certain things without having to pull their source code package and struggle with that. In other words it's of more value to us than to user. If anything, it should rather be expanded or modified, but not just removed. For example one idea for extending is linker flags, it can be relevant to access when trouble-shooting, maybe more specifically -rpath...

**Comment by levitte** [comment]
Okie, I'm convinced they should be kept (and currently are).
