### ISSUE TITLE
warning: attempt to free a non-heap object 'recp' (1.1.0-pre2 with MinGW 5.3.0 LTO)

### ISSUE THREAD

**Issue by vszakats** [openssl/openssl#558]
When building latest curl `master/HEAD` against OpenSSL 1.1.0-pre2 (in LTO mode, using MinGW 5.3.0), this warning is shown at the link phase of `curl.exe`:

32-bit:
```
In function 'CRYPTO_free',
    inlined from 'BN_RECP_CTX_free' at bn_recp.c:90:9,
    inlined from 'BN_mod_exp_recp' at bn_exp.c:396:5,
    inlined from 'BN_mod_exp' at bn_exp.c:256:13:
mem.c:245:5: warning: attempt to free a non-heap object 'recp' [-Wfree-nonheap-object]
```

Live log:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.348#L3477

64-bit
```
In function 'CRYPTO_free',
    inlined from 'BN_RECP_CTX_free' at bn_recp.c:90:9,
    inlined from 'BN_mod_exp_recp' at bn_exp.c:396:5:
mem.c:245:5: warning: attempt to free a non-heap object 'recp' [-Wfree-nonheap-object]
```

Live log:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.348#L7589

**Comment by ghedo** [comment]
I think this is a false positive. If you look at the `BN_RECP_CTX_free()` function, `OPENSSL_free()` is called on `recp` only when the `BN_FLG_MALLOCED` flag is set, but the compiler has no way of knowing that at compile time so it probably just outputs a warning.

**Comment by vszakats** [comment]
A false positive is a possibility. In LTO mode the linker may be able to see uses of the above call that the compiler can't &mdash; and find additional problems.

Just in case, here is a build log that _doesn't_ emit such warning, and the only difference between the above one is that it used OpenSSL 1.1.0-pre**1** and a few weeks older `curl` revision:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.304#L3461

(to sort out `curl` from the equation, I can revert to that exact older revision, though it will miss a required `-pre2` fix)

**Comment by vszakats** [comment]
Closing this due to no interest.
