### ISSUE TITLE
No way to set correct --sysroot values in build using Android NDK r16 (OpenSSL 1.1.0)

### ISSUE THREAD

**Issue by AlexanderplUs** [openssl/openssl#5588]
Starting Android NDK r16 it is required to use Unified headers in build process for Android. Otherwise compiler can't find standard headers, for example <assert.h>.
According to documentation https://android.googlesource.com/platform/ndk/+/master/docs/UnifiedHeaders.md when compiling we must use `-isystem $NDK/sysroot/usr/include/$TRIPLE -sysroot=$NDK/sysroot` and at link time '--sysroot=$NDK/platforms/android-$API/arch-$ARCH/'.  Obviously `--sysroot` parameter must be different at compile and link times. Standard environment variable `CROSS_SYSROOT` allow only one value. And there is no way to set extra CFLAGS and LDFLAGS using Configure script as it allows only one set of additional parameters at the end of its command line. Which goes to the CFLAGS and applies to the both compiling and linking.

**Comment by petrovr** [comment]
AlexanderplUs wrote:
> Starting Android NDK r16 it is required to use Unified headers in build process for Android. Otherwise compiler can't find standard headers, for example <assert.h>.
> According to documentation https://android.googlesource.com/platform/ndk/+/master/docs/UnifiedHeaders.md when compiling we must use `-isystem $NDK/sysroot/usr/include/$TRIPLE -sysroot=$NDK/sysroot` and at link time '--sysroot=$NDK/platforms/android-$API/arch-$ARCH/'.  Obviously `--sysroot` parameter must be different at compile and link times. Standard environment variable `CROSS_SYSROOT` allow only one value. And there is no way to set extra CFLAGS and LDFLAGS using Configure script as it allows only one set of additional parameters at the end of its command line. Which goes to the CFLAGS and applies to the both compiling and linking.
>
Android ndk r16+ does not mix headers with libraries. It is save to use 
both arguments.
For ndk r14*  and ndk r15* I don't follow android documentation  - old 
sysroot must fine.

For unified build you could set variable CC to compiler plus isystem 
flags and to build without to set cross-compile-prefix.

Not OpenSSL defect nor limitation.

Regards,
Roumen

**Comment by richsalz** [comment]
Sounds like there is nothing for OpenSSL to do here, closing this.

**Comment by dot-asm** [comment]
Please don't, I have a comment on this...

**Comment by dot-asm** [comment]
> we must use -isystem $NDK/sysroot/usr/include/$TRIPLE -sysroot=$NDK/sysroot and at link time '--sysroot=$NDK/platforms/android-$API/arch-$ARCH/'.

You can specify multiple `-isystem and so -isystem $NDK/sysroot/usr/include/$TRIPLE -isystem $NDK/sysroot/usr/include --sysroot=$NDK/platforms/android-$API/arch-$ARCH/` should do the trick. At least it works for me in #5589, and I wonder if you could give it a try and tell what you think.

**Comment by dot-asm** [comment]
@petrovr, I wonder how does your $PATH look like. Next thing I'm going to try is to add support for clang and there is not cross-compile prefix and then question is where do I get other tool-chain components from.

**Comment by dot-asm** [comment]
One of purposes with my comment was to "advertise" #5589 [which does address the reported problem, though not in 1.1.0], and since it's as appropriate to comment there, I'm closing this.

**Comment by AlexanderplUs** [comment]
@dot-asm, adding additional -isystem really helps, thanks.
Here my command line for configuring OpenSSL 1.1.0 with NDK r16

SYSTEM=android ARCH=$(ARCH) CROSS_COMPILE=$(TOOLCHAIN_BIN_PREFIX) CROSS_SYSROOT=$(NDK_ROOT)/platforms/android-$(API_LEVEL)/arch-$(ARCH) ./Configure --prefix=$(prefix) --openssldir=$(prefix) --sysroot=$(NDK_ROOT)/platforms/android-$(API_LEVEL)/arch-$(ARCH) -D__ANDROID_API__=$(API_LEVEL) -isystem $(NDK_ROOT)/sysroot/usr/include/$(TOOLCHAIN) -isystem $(NDK_ROOT)/sysroot/usr/include $(TARGET)

But as I can see it isn't documented in Android doc and may be broken in the next NDK r17.
