### ISSUE TITLE
1.0.2 dynamic library version incorrect

### ISSUE THREAD

**Issue by cityzz** [openssl/openssl#5594]
Built the 1.0.2n dynamic library from source code.
The dynamic library for the libcrypto.so is libcrypto.so.1.0.0 while I think is should be libcrypto.1.0.2 , so does the libssl.so

I've also saw the same problem in 1.0.2h as well.
Is it a bug? Or is it something we do for a purpose?

The config command I used it as below:
./Configure -fPIC --prefix=/path/to/build_objs --openssldir=/path/to/build_objs linux-x86_64 shared

And then just
make depend && make
make install

The build environment is Ubuntu 16.04 with gcc
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by levitte** [comment]
This is a common misunderstanding...  the shared library version is not the same thing as the project version number.  Very simply put, if two shared libraries have the exact same SONAME (which is reflected in the file name), they are considered compatible (at least upwardly).  This is the mechanism that allows a shared library upgrade to actually work.

**Comment by Tianjiao** [comment]
@cityzz , Hi, your config command has some small error for CFLAGS, it should be

`./Configure CFLAGS="-fPIC" --prefix=/path/to/build_objs --openssldir=/path/to/build_objs linux-x86_64 shared`

**Comment by levitte** [comment]
Actually, @Tianjiao, @cityzz's configuration command is correct.
