### ISSUE TITLE
INSTALL.WIN configure option `enable-static-engine` appears to be ignored

### ISSUE THREAD

**Issue by vszakats** [openssl/openssl#560]
When configuring with:
```
./Configure mingw shared enable-static-engine no-unit-test no-ssl3 no-rc5 no-idea no-dso --prefix=/usr/local
```

The option `enable-static-engine` seems to have no effect on the build (also when using the `mingw64` target). Is there something I should do differently to make this option work as described in `INSTALL.WIN`?

option enabled:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.349

option disabled (default):
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.348

**Comment by vszakats** [comment]
Problem appears valid, but doesn't seem to be picked up by devs, so closing.

**Comment by vszakats** [comment]
Thank you @richsalz!

**Comment by mattcaswell** [comment]
I think this will only work for VisualStudio builds. Although I just tried it and the build fell over, so "work" is perhaps stretching the truth a bit :-)

**Comment by mattcaswell** [comment]
Do we need this feature? Perhaps we should remove it.

**Comment by vszakats** [comment]
If engines don't imply any extra `.dll` dependencies (and have no other downsides whatsoever), maybe they could be built into the core `.dll` by default. That would make the runtime layout more lean IMO - and sort out certain runtime issues as well.

**Comment by mattcaswell** [comment]
Ping @levitte, this issue is probably relevant to your build system work.

**Comment by levitte** [comment]
It's at least good for me to be aware of. :-)

**Comment by levitte** [comment]
Looking at git history, this is a very old option, and I can't really see how it's supported by the build system today.  There doesn't seem to be any support for it in `engines/Makefile.in`, at the very least...  there seems to be support for it in `util/mk1mf.pl`, though.  Interesting.

My brain is not wrapping around this for the moment, I'll give it another go tomorrow.

**Comment by vszakats** [comment]
I'd think it may be a solution to just delete this option from the documentation. Probably not something too many people need if being broken unnoticed for a longer period.
