### ISSUE TITLE
-nameopt compat does not output the OpenSSL 1.0 format

### ISSUE THREAD

**Issue by brianhlin** [openssl/openssl#5605]
New format, even when specifying `-nameopt compat`. There's also no difference between `-nameopt compat` and `-nameopt -compat`

```
$ openssl version
OpenSSL 1.1.0g-fips  2 Nov 2017
$ openssl x509 -in /etc/grid-security/hostcert.pem -noout -nameopt compat -subject
subject=DC=org, DC=opensciencegrid, C=US, O=OSG Software, OU=Services, CN=blin-latitude.localdomain
$ openssl x509 -in /etc/grid-security/hostcert.pem -noout -nameopt -compat -subject
subject=DC=org, DC=opensciencegrid, C=US, O=OSG Software, OU=Services, CN=blin-latitude.localdomain
```

Actual old format:

```
# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
# openssl x509 -in /etc/grid-security/hostcert.pem -noout -subject
subject= /DC=org/DC=opensciencegrid/O=Open Science Grid/OU=Services/CN=fermicloud321.fnal.gov
```

**Comment by petrovr** [comment]
$ openssl version
OpenSSL 1.0.2n  7 Dec 2017
$ openssl x509 -in testocsp_rsa-dsa.crt -noout -subject -nameopt compat
subject= C=XX, ST=World, O=SSH Test Team cyrillic-\U0410\U0411\U0412-\U042F\U0430\U0431\U0432-\U044F greek-\U0391\U0392\U0393-\U03A9\U03B1\U03B2\U03B3-\U03C9, OU=SSH Testers cyrillic-\U0410\U0411\U0412-\U042F\U0430\U0431\U0432-\U044F greek-\U0391\U0392\U0393-\U03A9\U03B1\U03B2\U03B3-\U03C9-2, OU=SSH Testers cyrillic-\U0410\U0411\U0412-\U042F\U0430\U0431\U0432-\U044F greek-\U0391\U0392\U0393-\U03A9\U03B1\U03B2\U03B3-\U03C9-1, OU=SSH Testers cyrillic-\U0410\U0411\U0412-\U042F\U0430\U0431\U0432-\U044F greek-\U0391\U0392\U0393-\U03A9\U03B1\U03B2\U03B3-\U03C9-3, CN=validator RSA(dsa)
$ openssl x509 -in testocsp_rsa-dsa.crt -noout -subject
subject= /C=XX/ST=World/O=SSH Test Team cyrillic-\xD0\x90\xD0\x91\xD0\x92-\xD0\xAF\xD0\xB0\xD0\xB1\xD0\xB2-\xD1\x8F greek-\xCE\x91\xCE\x92\xCE\x93-\xCE\xA9\xCE\xB1\xCE\xB2\xCE\xB3-\xCF\x89/OU=SSH Testers cyrillic-\xD0\x90\xD0\x91\xD0\x92-\xD0\xAF\xD0\xB0\xD0\xB1\xD0\xB2-\xD1\x8F greek-\xCE\x91\xCE\x92\xCE\x93-\xCE\xA9\xCE\xB1\xCE\xB2\xCE\xB3-\xCF\x89-2/OU=SSH Testers cyrillic-\xD0\x90\xD0\x91\xD0\x92-\xD0\xAF\xD0\xB0\xD0\xB1\xD0\xB2-\xD1\x8F greek-\xCE\x91\xCE\x92\xCE\x93-\xCE\xA9\xCE\xB1\xCE\xB2\xCE\xB3-\xCF\x89-1/OU=SSH Testers cyrillic-\xD0\x90\xD0\x91\xD0\x92-\xD0\xAF\xD0\xB0\xD0\xB1\xD0\xB2-\xD1\x8F greek-\xCE\x91\xCE\x92\xCE\x93-\xCE\xA9\xCE\xB1\xCE\xB2\xCE\xB3-\xCF\x89-3/CN=validator RSA(dsa)

Confirmed.  Quote from manual page "compat     use the old format. This is equivalent to specifying no name options at all."

I cannot see reason in 2018  OpenSSL to support "old format" - old format does not allow to "reconstruct" distinguished name.

As this is document functionality option argument "compat" should work as is described.

P.S. same result with with OpenSSL 1.1.1-pre3-dev  xx XXX xxxx

**Comment by mattcaswell** [comment]
I've looked into this and I think this is a documentation issue. The "compat" nameopt was introduced by commit a657546f9 in July 2000. It causes the flag `XN_FLAG_COMPAT` to be set which was introduced at the same time. That commit has this comment against that flag:

````
#define XN_FLAG_COMPAT         0               /* Traditional SSLeay: use old X509_NAME_print */
````

The compat option is described as meaning "use the old format". Which should be read as "use the *really* old SSLeay format".

**Comment by mattcaswell** [comment]
Although...going back to old versions of OpenSSL it seems the "compat" format has changed!!

In 1.0.2 I get this:
````
$ openssl x509 -in server.pem -noout -subject
subject= /C=UK/O=OpenSSL Group/OU=FOR TESTING PURPOSES ONLY/CN=Test Server Cert

$ openssl x509 -in server.pem -noout -subject -nameopt compat
subject= C=UK, O=OpenSSL Group, OU=FOR TESTING PURPOSES ONLY, CN=Test Server Cert
````

If I go back to 0.9.7 (about the oldest I can still compile). I get this:
````
$ openssl x509 -in server.pem -noout -subject
subject= /C=AU/ST=Queensland/O=CryptSoft Pty Ltd/CN=Server test cert (512 bit)

$ openssl x509 -in server.pem -noout -subject -nameopt compat
subject= /C=AU/ST=Queensland/O=CryptSoft Pty Ltd/CN=Server test cert (512 bit)
````

**Comment by mattcaswell** [comment]
So, in summary it seems that:

1) The default output format has changed between 1.0.2 and 1.1.0
2) The nameopt "compat" output is consistent between 1.0.2 and 1.1.0
3) AFAICT there is no way to get 1.1.0 to print out in the old default 1.0.2 format

Given that 1.1.0 was billed as an incompatible release I think this is ok. It might have been better had we provided a proper compatibility option. But its probably a bit late now, and not worth fixing. Therefore I think this issue should be closed.

**Comment by richsalz** [comment]
Nice diagnosis and testing work!

**Comment by dmngb** [comment]
> But its probably a bit late now, and not worth fixing.

It seems Apache/mod_ssl still requires old default 1.0.2 format in .htpasswd files when using FakeBasicAuth (subject-based authorization with client certificates authentication).

So having a compatibility option to get default 1.0.2 format using 1.1 command line would be very valuable: we keep a statically linked copy of openssl 1.0.2 command line only to be able to get certificate subjects in the default 1.0.2 syntax!

**Comment by InfoHunter** [comment]
TBH, I don't think it's worth doing that in the next OpenSSL release (3.0.0). Instead I think Apache/mod_ssl should be updated to adapt the changes...
