### ISSUE TITLE
Failed to run openssl test after revision 249b4e2(Refactor the 'depend' target) on Windows

### ISSUE THREAD

**Issue by shanshan0309** [openssl/openssl#5611]
I tried to build openssl using VS2017 update 5 on Windows. I noticed that openssl test failed to run after revision [249b4e2](https://github.com/openssl/openssl/commit/249b4e28a6c91074f2fe276a2b2b40eb6f9639a9) (Refactor the 'depend' target). Could you please help take a look at this? Thanks in advance!

**Repro steps:**
1. git clone https://github.com/openssl/openssl D:\openssl\src
2. cd D:\openssl\src
3. perl Configure VC-WIN32
4. nmake clean
5. where cl.exe
6. nmake
7. nmake test

**Expected result:**
All tests passed

**Actual result:**
NMAKE : fatal error U1073: don't know how to make 'C:\Program'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

**Comment by levitte** [comment]
Thanks.  There's an ongoing effort to fix the issues with dependency generation, see #5591.  Would you mind trying that out?

**Comment by shanshan0309** [comment]
@levitte. Thanks for looking into this issue. I applied your change( #5591) but it still hit this issue.

**Comment by levitte** [comment]
Did you try to go from the start, i.e. Configure 'n all?

**Comment by shanshan0309** [comment]
Yes, I start from the "perl Configure VC-WIN32". It failed to execute command "nmake" because of following error:
NMAKE : fatal error U1077: 'cl' : return code '0xff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

**Comment by levitte** [comment]
Yup, I got the same.  Normally, I'd recommend `nmake clean` first, but that's obviously going to fail, but doing `del /S *.d` helps, then reconfigure again.  Now you'll have a clean makefile again.

**Comment by shanshan0309** [comment]
Thanks, @levitte. When I execute del /S *.d. It still fail to "nmake" because of NMAKE : fatal error U1077.

**Comment by levitte** [comment]
Did you reconfigure again?

**Comment by shanshan0309** [comment]
@levitte, I tried it again and it works well. Thanks for your help. 
Thank you very much.

**Comment by levitte** [comment]
You're welcome...  now, all that's needed is for that PR to get merged to master...

**Comment by dot-asm** [comment]
As temporary workaround one can simply configure with additional no-makedepend option.

**Comment by shanshan0309** [comment]
Okay, Thanks @levitte and @dot-asm.
