### ISSUE TITLE
error: dereferencing 'void *' pointer while compiling

### ISSUE THREAD

**Issue by shameempk** [openssl/openssl#5614]
Branch: OpenSSL_1_0_2-stable
OS: NetBSD

Building OpenSSL causing `error: dereferencing 'void *' pointer`.
File: crypto/engine/eng_cryptodev.c
Line no: 1060

How to bypass the error:
```
-        pd[i] = crp->crp_p[bytes - i - 1];
+       pd[i] = ((char*)crp->crp_p)[bytes - i - 1];
```

`struct crparam` definition from cryptodev.h:
```
struct crparam {
        void *          crp_p;
        u_int           crp_nbits;
};
```

**Comment by levitte** [comment]
Fixed!  Thanks for the patch

**Comment by shameempk** [comment]
Thanks for the quick response. That was real quick. I really don't know what happened. I think, this type casting part was there in 1.0.1c. How come it is not there in 1.0.2x? Am I missing something?

**Comment by levitte** [comment]
> I really don't know what happened. I think, this type casting part was there in 1.0.1c. How come it is not there in 1.0.2x? Am I missing something?

[Nope](https://github.com/openssl/openssl/blob/OpenSSL_1_0_1-stable/crypto/engine/eng_cryptodev.c#L992)

I would rather believe that your `cc` has gotten pickier ;-)

**Comment by shameempk** [comment]
I was using NetBSD version of openssl (1.0.1c) it had this fix already.
ftp://ftp.netbsd.org/pub/NetBSD/NetBSD-6.0/source/sets/src.tgz

Thanks.
