### ISSUE TITLE
TLSv1.3 session problems

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#5628]
In TLSv1.2 a session always has an id and may be associated with a ticket. At the end of the handshake we always update the server's internal session cache (unless it has been explicitly turned off) to store the session details. This cache is only used in the event that a client attempts to resume via a session id. If we receive a session id (with no ticket) then we look it up in the cache. If it's there then we can resume from it. If we get a ticket then there is no need to use the cache because we can extract the session info directly from the ticket.

Sessions get flushed from the cache if they exceed a timeout period. They also get removed if a connection fails for some reason (fatal alert gets sent).

We also have an optional facility for an external session cache. If you enable this then you get callbacks every time a new session is created, or a session is removed (due to timeout or some other error), or when we want to look up a session in the cache.

In TLSv1.3 there is a key difference in the way sessions work. There is no explicit session id - so clients will never resume by session id alone. At the moment we don't really account for this. We still store the session in the internal cache. We still time them out after a period of time, and remove them in the event of an error etc. All of this in spite of the fact that this cache will *never be used* to resume sessions, because a client will never resume by session id alone. This seems to be a big waste of resources.

An obvious answer to this is to not update the internal cache for TLSv1.3. However things are complicated by the existence of the external cache. We actually recommend that apps implement the new_session_cb to hear about new sessions being created (if they need to know about this), whether or not they are planning to implement an external cache, rather than to use SSL_get_session() - because sessions are created post-handshake in TLSv1.3.

One thing the internal cache is used for is to determine when a session has exceeded its timeout. If an application does have an external cache then it may want to know about timeout events to clear its own cache. If we remove the internal cache then they won't get those callbacks anymore (potentially leading to the external cache growing in size indefinitely).

So all of this tends to suggest that perhaps we should keep the internal cache after all (at least by default, for backwards compat reasons). If we do that though it makes me wonder why we bother with storing the full session state in the ticket at all. We have all the information we need to resume in our cache. We could just put the session id *in the ticket* and resume from that. This would save bloat in the ticket extension + remove the need for ticket keys and encryption/decryption/integrity checking of the ticket.

Another possible argument in favour of keeping the internal cache is that we could (optionally) use it to enforce single-use tickets. Once a ticket is used we simply remove it from the cache so that it can't be used again.

So I'm thinking we should:
1) Retain the internal cache for compatibility reasons in the default case (with a possibility to enable a single-use ticket feature)
2) Provide an option to run with no cache (fully stateless tickets) - in which case you don't get the session removed callbacks and your application has to be able to cope with that
3) In the default case support simple "stateful" tickets, that just store the session id

As things stand we've got a mixture of both 1 + 2 without fully realising the benefits of either.

**Comment by kaduk** [comment]
Right, the expository focus in TLS 1.3 on session tickets as opposed to session IDs is just exposition -- the network facing part behaves identically, and the server can make an implementation decision whether to use a stateful cache or stateless tickets (or, apparently, both).  The document is probably easier to read with only one mechanism discussed, but there are hints that the stateful method still works fine, e.g., in the 0-RTT anti-replay section.

Shrinking down the ticket contents to just have the session ID (or even just *be* the session ID, if there's sufficient entropy in the IDs) by default would be fine.  Which I guess is a long way of saying "I agree with your analysis and this seems like a fine path forward".

**Comment by mattcaswell** [comment]
All of the issues raised here have been addressed with the exception of the proposal to use session id based tickets. I've captured that more fully in #6391, so I think this can be closed now.
