### ISSUE TITLE
AIX PPC build issue

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#5659]
I've got a failure building for AIX:

> gcc  -I. -Iinclude -I.. -I../include -maix64 -pthread -O -DOPENSSLDIR="\"/scratch/nsegen/jenkins/workspace/openssl-aix_ppc64/install/ssl\"" -DENGINESDIR="\"/scratch/nsegen/jenkins/workspace/openssl-aix_ppc64/install/lib/engines-1.1\"" -DB_ENDIAN -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_NO_ASYNC -c -MMD -MF apps/s_socket.d.tmp -MT apps/s_socket.o -c -o apps/s_socket.o ../apps/s_socket.c
	ar r apps/libapps.a apps/app_rand.o apps/apps.o apps/bf_prefix.o apps/opt.o apps/s_cb.o apps/s_socket.o
ar: creating an archive file apps/libapps.a
ar: 0707-126 apps/app_rand.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 apps/apps.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 apps/bf_prefix.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 apps/opt.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 apps/s_cb.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 apps/s_socket.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
make: The error code from the last command is 6.

The configure line being used is:

> ./Configure aix64-gcc

The output from _configdata.pm_ is attached: [dump.txt](https://github.com/openssl/openssl/files/1823524/dump.txt)

The issue is that the _Makefile_ is getting the line `ARFLAGS= r` from somewhere.
The correct args appears in _10-main.conf_: `arflags          => "-X64 r",`

The same is happening for 32 bit builds.

**Comment by dot-asm** [comment]
Richard, could you look at this and choose what's more appropriate? 6475b64978083750018db90c60f4df142aa2e28f says "make sure", but later on ARFLAGS, i.e. in capitals, was prioritized, and as result arflags, i.e. lower-case, is effectively disregarded. So does one capitalize remaining ones? Or does one add arflags => 'ARFLAGS' to target_attr_translate in Configure?

And what about Configurations/README that talks about lower-case arflags?

**Comment by dot-asm** [comment]
And question of course what else we might have missed. I mean besides arflags. On AIX, fixing arflags appears sufficient, but can there be something else lurking?

**Comment by dot-asm** [comment]
ARFLAGS seem to be the only affected, so it's only original question. In the context one can wonder if the -X flag should be part of AR rather than ARFLAGS...

Just in case. There also is option to specify -X32_64 and tell "don't care, just put stuff", but that would mean that in case user mixes things up, it would be harder to troubleshoot. For this reason explicit -X64 or -X32 are preferable, they will tell what's wrong upfront.

**Comment by covener** [comment]
re: lurking: when building httpd and its dependencies, which use slightly different builds,  I always have this in my env:

export OBJECT_MODE=64
export lt_cv_path_NM="/usr/bin/nm -B -X64"
export AR="ar -X64"

(I am not sure if the hint in the middle would be used by openssls build or if it's n/a there)

**Comment by dot-asm** [comment]
> In the context one can wonder if the -X flag should be part of AR rather than ARFLAGS

Rationale would be "if user wants to say `make ARFLAGS=rv`, it would still work". In clfags we kind of have non-overridable and overridable parts, and it's not inappropriate here. However, fixing it in same way as cflags would be an overkill...

**Comment by dot-asm** [comment]
I'm aware of OBJECT_MODE, but we can't rely on user to set it or set it right. For this reason it's noted only during ./config, then then idea is to "freeze" flags so that output for generated Makefile would be independent of current value of OBJECT_MODE or its presence.

**Comment by dot-asm** [comment]
See #5713. I tested it only with aix[64]-gcc, as I don't have easy way to test aix[64]-cc. But there is no reason to believe that it would be different, it's same ar and ranlib that are called in both cases...

**Comment by paulidale** [comment]
aix64-cc compiles with this change.  I'm getting some test errors but it seems unlikely they are related.

**Comment by dot-asm** [comment]
I had an opportunity to test xlc not so long ago. Try to drop optimization when compiling crypto/stack/stack.c...

**Comment by paulidale** [comment]
The stack test was the first to fail.  Recompiling stack.c without optimisation fixed things.

**Comment by dot-asm** [comment]
#5713 is merged. As for stack.c, it's something for IBM to sort out. I mean it's clearly a compiler bug. What's "fascinating" about it is that it's like pretty trivial code and it's virtually impossible to imagine what could be the trigger. But compiler bugs never make sense...

**Comment by trudeaun** [comment]
I'm interested to look into this issue with stack.c further. Which version of IBM XL C/C++ for AIX are you using? You can get that info by using the -v compiler option. Which version of the AIX OS are you using? What compile command can reproduce the issue?

**Comment by paulidale** [comment]
> $ cc -qversion=verbose
> IBM XL C/C++ Enterprise Edition for AIX, V9.0
> Version: 09.00.0000.0007
> Driver Version: 09.00(C/C++) Level: 080814
> C Front End Version: 09.00(C/C++) Level: 090529
> C++ Front End Version: 09.00(C/C++) Level: 090527
> High-Level Optimizer Version: 09.00(C/C++) and 11.01(Fortran) Level: 090501
> Low-Level Optimizer Version: 09.00(C/C++) and 11.01(Fortran) Level: 090509

**Comment by dot-asm** [comment]
> V9.0

That old? I had this problem with 12.1. I suppose relevant question is if latest version is affected. As for reproducing the problem. After downloading/cloning latest development branch, `./Configure aix-cc`, then `make`, and finally `make test TESTS=test_stack`. Try even `./Configure aix64-cc`.

**Comment by trudeaun** [comment]
Thanks for providing this issue. I can check if this issue still exists on the latest version 13.1.3. I think your current steps to reproduce involve compiling the entire project. Are you able to provide steps to compile just one (or a small number of) files?
