### ISSUE TITLE
Add no-async configure option separate from no-threads?

### ISSUE THREAD

**Issue by justinddunlap** [openssl/openssl#567]
The async sublibrary seems to break the usage of openssl on Android. While newer versions of the Android NDK contain ucontext.h, the actual makecontext/setcontext/etc functions are not implemented. This does not break compile (other than warnings about implicit function definition), but causes linker errors when trying to link to the library.

It seems like it would be a good idea to allow disabling of async for POSIX-type platforms that support threads, but do not support the ucontext routines?

**Comment by richsalz** [comment]
fixed
