### ISSUE TITLE
Make public SM2 functions libcrypto private

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#5670]
#4793 added a few public SM2 function that really shouldn't be,  They're only used by the EC code and the SM2 functionality should only be reachable through the EVP API.

As a consequence, the two test programs `test/sm2crypttest.c` and `test/sm2sigtest.c` should be viewed as internal and allowed to access those SM2 functions.  SM2 through the EVP API is already tested with added data in `test/recipes/30-test_evp_data/evppkey.txt`

**Comment by randombit** [comment]
I can address this but probably will not have time to create a PR until Friday or Saturday.

**Comment by ronaldtse** [comment]
Thanks @randombit , @levitte !

**Comment by mattcaswell** [comment]
Hi @randombit - any update on this?

**Comment by randombit** [comment]
@mattcaswell Sorry for the holdup, should be able to look at this tomorrow

**Comment by randombit** [comment]
@mattcaswell @levitte Fixed in PR #5895

**Comment by richsalz** [comment]
Since #5895 was closed, closing this.
Thanks!

**Comment by ronaldtse** [comment]
Thank you @levitte @randombit @mattcaswell @richsalz ! 👍
