### ISSUE TITLE
Issues with system-default SSL_CTX_new

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#5671]
We need a clean way to opt-out (at least for postfix).
Should probably only read the config file at startup time.
Need a CHANGES entry.

**Comment by mattcaswell** [comment]
> Need a CHANGES entry.

There is one now. @richsalz - any thoughts on my proposed opt-out? If the opt-out is ok then this can probably be closed.

**Comment by richsalz** [comment]
The ```NO_LOAD_CONFIG``` ?  Yes, I'm in favor of that.  It will be easy for postfix to use via ifdef.

**Comment by mattcaswell** [comment]
> The NO_LOAD_CONFIG ? Yes, I'm in favor of that. It will be easy for postfix to use via ifdef.

So, this capability is already present. Closing.
