### ISSUE TITLE
crypto/ctype and conf/keymap

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#5672]
These are very similar and should be merged.
See https://github.com/openssl/openssl/pull/5669#issuecomment-374231801

**Comment by richsalz** [comment]
See also perhaps #5840

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by richsalz** [comment]
`git grep keymap crypto` returns nothing.  Overtaken by events, closing.
