### ISSUE TITLE
pkcs7_verify get actual error

### ISSUE THREAD

**Issue by minaevmike** [openssl/openssl#568]
Hi,
when i trying to verify pkcs7 signauture in case of error i want get the actual problem, such as self-signed certificate, the cert if outdated and so on. But https://github.com/openssl/openssl/blob/master/crypto/pkcs7/pk7_smime.c#L323 hides the actual error with PKCS7_R_CERTIFICATE_VERIFY_ERROR, is it possible to do smth with it?

**Comment by richsalz** [comment]
you can get the error data via ```ERR_error_string_n```
