### ISSUE TITLE
Building openssl-1.1.1-pre3 reports errors in 70-test_sslmessages, 70-test_tls13messages

### ISSUE THREAD

**Issue by plaintextcity** [openssl/openssl#5693]
Built Openssl 1.1.1-pre3 on Windows, Visual Studio 2017/strawberry/nacm.   Build appears successful other than failed message test cases.

> ```
> Test Summary Report
> -------------------
> test\recipes\70-test_sslmessages.t            (Wstat: 2304 Tests: 4 Failed: 0)
>   Non-zero exit status: 9
>   Parse errors: Bad plan.  You planned 21 tests but ran 4.
> test\recipes\70-test_tls13messages.t          (Wstat: 2304 Tests: 4 Failed: 0)
>   Non-zero exit status: 9
>   Parse errors: Bad plan.  You planned 16 tests but ran 4.
> Files=146, Tests=1274, 643 wallclock secs ( 1.26 usr +  1.77 sys =  3.03 CPU)
> Result: FAIL
> NMAKE : fatal error U1077: 'C:\Strawberry\perl\bin\perl.exe' : return code '0x1'
> Stop.
> NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\nmake.exe"' : return code '0x2'
> Stop.
> OpenSSL 1.1.1-pre3 (beta) 20 Mar 2018
> ```

**Comment by mattcaswell** [comment]
Please report the output from running `nmake V=1 TESTS="test_sslmessages test_tls13messages"`

**Comment by plaintextcity** [comment]
Please see output attached from command:

`nmake test V=1 TESTS="test_sslmessages test_tls13messages" > test_output.txt 2>&1
`

[test_output.txt](https://github.com/openssl/openssl/files/1830299/test_output.txt)

**Comment by mattcaswell** [comment]
Could you try the patch in #5412 and see if that makes a difference please?

**Comment by plaintextcity** [comment]
It will be a few hours before I can get back to this.

**Comment by plaintextcity** [comment]
Test Summary Report
-------------------
test\recipes\70-test_key_share.t              (Wstat: 1536 Tests: 22 Failed: 6)
  Failed tests:  1, 4, 6-7, 13-14
  Non-zero exit status: 6
test\recipes\70-test_sslextension.t           (Wstat: 2304 Tests: 6 Failed: 0)
  Non-zero exit status: 9
  Parse errors: Bad plan.  You planned 7 tests but ran 6.
test\recipes\70-test_sslmessages.t            (Wstat: 65280 Tests: 4 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 21 tests but ran 4.
test\recipes\70-test_sslrecords.t             (Wstat: 512 Tests: 18 Failed: 2)
  Failed tests:  15, 18
  Non-zero exit status: 2
test\recipes\70-test_sslsigalgs.t             (Wstat: 1024 Tests: 21 Failed: 4)
  Failed tests:  1, 6, 19-20
  Non-zero exit status: 4
test\recipes\70-test_sslsignature.t           (Wstat: 512 Tests: 4 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
test\recipes\70-test_sslversions.t            (Wstat: 512 Tests: 7 Failed: 2)
  Failed tests:  5, 7
  Non-zero exit status: 2
test\recipes\70-test_tls13cookie.t            (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
test\recipes\70-test_tls13kexmodes.t          (Wstat: 2048 Tests: 11 Failed: 8)
  Failed tests:  2, 4-10
  Non-zero exit status: 8
test\recipes\70-test_tls13messages.t          (Wstat: 65280 Tests: 12 Failed: 12)
  Failed tests:  1-12
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 16 tests but ran 12.
test\recipes\70-test_tls13psk.t               (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
test\recipes\70-test_tlsextms.t               (Wstat: 256 Tests: 10 Failed: 1)
  Failed test:  10
  Non-zero exit status: 1
Files=146, Tests=1281, 637 wallclock secs ( 1.24 usr +  1.00 sys =  2.24 CPU)
Result: FAIL
NMAKE : fatal error U1077: 'C:\Strawberry\perl\bin\perl.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
OpenSSL 1.1.1-pre3 (beta) 20 Mar 2018

**Comment by plaintextcity** [comment]
I tested this with variable results, using the new Proxy.pm and Record.pm resulted in more errors on my machine.  Digging through 5412 my understanding is that the test harness is sensitive to fragmentation, and think having used the VPN on my laptop would have lowered the MTU(and/or enabled PMTU).   I'd defer to the openssl team on whether this (testing on potentially reduced MTU machines) needs to be fixed, it's possible it could apply to vm/container continuous integration machines.  Either way this can be closed in favor of 5412 and I'll look if I can help there.

**Comment by mattcaswell** [comment]
Ok, closing as per the above.

**Comment by plaintextcity** [comment]
Just commenting to confirm that building the current (cloned from openssl-master) now that #5412 was merged resulted in "All tests successful".  Thanks.
