### ISSUE TITLE
build conflict under Ubuntu 17.10 openssl1.0.2n with hexchat2.14.1

### ISSUE THREAD

**Issue by russherman** [openssl/openssl#5696]
You two like to fight this one out? :)
[](https://github.com/hexchat/hexchat/issues/2149)

**Comment by russherman** [comment]
Not sure if link made it into msg,
https://github.com/hexchat/hexchat/issues/2149

**Comment by levitte** [comment]
I just answered there.  As far as I can tell, that isn't an error on our end, so I'm closing this.
