### ISSUE TITLE
Documentation fixes for openssl-1.0.1g (Ubuntu 14.04)

### ISSUE THREAD

**Issue by cookiengineer** [openssl/openssl#57]
I already tried to write on the mailing list, but it didn't work.

The current suggested stable 1.0.1g download won't compile on up2date systems as there are many errors in the documentation pod files.

Here's the patch file I created: https://gist.github.com/martensms/10107481

**Comment by manur** [comment]
`make install_sw` worked for me on CentOS as well. Thank you.
