### ISSUE TITLE
test/aborttest from 1.1.1-pre3 `make test` tickles Problem Reporting GUI

### ISSUE THREAD

**Issue by wrowe** [openssl/openssl#5700]
UI Problem Reporting tools are triggered by the test/aborttest, leading to GUI noise in what is otherwise a detached, stdio-redirected make test invocation.

Not sure if there is a workaround that can be automated. Observed on Fedora 27.

**Comment by mattcaswell** [comment]
Not planning to fix this for 1.1.1. Not sure if there is a fix! Move to post 1.1.1 milestone for now.

**Comment by t8m** [comment]
I do not think there is a way to fix this. We would have to drop the test and I do not think we want to. Closing.
