### ISSUE TITLE
custom version number 

### ISSUE THREAD

**Issue by igorvoltaic** [openssl/openssl#5705]
if i change version number in
https://github.com/openssl/openssl/blob/master/include/openssl/opensslv.h

i get this error while compiling
/usr/bin/perl util/mkdef.pl crypto linux > libcrypto.map
Invalid version number: 1_1_0 for current version 1_0_0

where else i need to change version number?

**Comment by levitte** [comment]
So, uhmmm, I assume you're trying to "downgrade" the version number to 1.0.0...  Thing is that the ordinals files we have contain symbols that are for 1.1.0 and up only, and that can't work with a lower version number...

Why are you doing this?  You do know that doing this comes with a big risk of screwing things up quite badly, right?

**Comment by igorvoltaic** [comment]
I'm not intended to use it globally, there is an app which is hardcoded to libssl.so.1.0.0 and libcrypto.so.1.0.0 even in newest releases. and developer isn't intended to change anything for right now. And i do not want to use 1.0.0 but change 1.1.0 to spoof version num and put those to libs to app's lib/ directory.
then just do LD_LIBRARY_PATH for this app only.

**Comment by levitte** [comment]
Ok, that is a *very* *bad* *idea*.

OpenSSL 1.1.0 changed the API and ABI, so there isn't a clean upgrade path that allows what you're trying to do.

**Comment by levitte** [comment]
I'm sorry to say that you will have to insist with your developer, or adapt that app for OpenSSL 1.1.0 yourself.

I don't think I can help you further, so closing this issue.

**Comment by igorvoltaic** [comment]
Thanks for clearing this out
