### ISSUE TITLE
Not able to compile openssl for aarch64-linux platform

### ISSUE THREAD

**Issue by shkart** [openssl/openssl#5707]
Hi,
   I am trying to compile openssl for linux-aarch64 platform, i am using aarch64-poky-linux-gcc cross compiler on ubuntu 16.04. I am getting "/lib/ld-linux-aarch64.so.1: No such file or directory" error. ld-linux-aarch64.so.1 is installed under "/opt/poky/2.1.2/sysroots/aarch64-poky-linux/lib" and has symbolic link to "ld-2.23.so", i tried exporting the __CNF_LDFLAGS environment variable to look in "/opt/poky/2.1.2/sysroots/aarch64-poky-linux/lib" directory, that did not resolve the issue. Any suggestions please, thanks in advance.

**Comment by shkart** [comment]
[dump_output.txt](https://github.com/openssl/openssl/files/1832676/dump_output.txt)

I have attached output of "perl configdata.pm --dump" command,

**Comment by mattcaswell** [comment]
What version of OpenSSL are you doing this with? I get different output from `perl configdata.pm --dump` compared to you when I try your command line (using the latest git OpenSSL sources).

**Comment by mattcaswell** [comment]
Ah...no...I take that back...it turns out I wasn't sat on the latest master when I tried it.

**Comment by dot-asm** [comment]
This doesn't sound like OpenSSL problem. Can you compile `main(){}`? With compiler in question of course? If not, it's not something we can help with. As we stand for source code, and you stand for *working* toolchain. If you get this message when trying to execute binary on target system, then toolchain doesn't match the target system. Again, not OpenSSL problem...
