### ISSUE TITLE
documentation error in ecparam -conv_form default value

### ISSUE THREAD

**Issue by john-chuah** [openssl/openssl#5711]
The web page at https://www.openssl.org/docs/man1.0.2/apps/ecparam.html states that "compressed" is the default value for -conv_form, but it should actually be "uncompressed" according to the code in apps/ecparam.c.

**Comment by mattcaswell** [comment]
Seems to be the case for master/1.1.0 too.

**Comment by mattcaswell** [comment]
Fix in #5712
