### ISSUE TITLE
Remote Cipher test failed

### ISSUE THREAD

**Issue by TTributh** [openssl/openssl#5714]
Hi,
I used the actual git version:
OpenSSL 1.1.1-pre4-dev  xx XXX xxxx

With this little script:
for a in TLS_CHACHA20_POLY1305_SHA256 \
	 TLS_AES_256_GCM_SHA384 \
	 TLS_AES_128_GCM_SHA256
do 
  echo QUIT|openssl s_client -cipher $a -connect example.net:443 2>/dev/null|grep ^New
done
  

I got always only these results:
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384

I tested against several applications like nginx, dovecot & exim.
In former versions there was a possibility the check for the existence of several TLS1.3 ciphers.
This is actually gone and only the first DEFAULT Cipher is shown with the openssl client.

Cheers Torsten

**Comment by richsalz** [comment]
For TLS 1.3, use the -ciphersuites flag.  Closing this.
