### ISSUE TITLE
Pointer double free in OpenSSL 1.0.2n err.c

### ISSUE THREAD

**Issue by Sleepless-Knight** [openssl/openssl#5716]
Apologies if this is dealt with somewhere, but a search of issues found no mention of a crash by double free of a pointer as described below.

OS/X 10.3.1
XCode 9.2
cURL 7.57.0 using OpenSSL 1.0.2n

Synchronisation functions are set by:

      CRYPTO_set_locking_callback(&lockCallback);
      CRYPTO_set_id_callback(&threadIdCallback);

We maintain a static array (number of elements set by call to CRYPTO_num_locks()) mutexes for OpenSSL's use.

We experience a crash in openssl-1.0.2n/crypto/mem.c CRYPTO_free(void* str) running our own stress tests for our own software. To that end we have turned on the CRYPT debugging malloc/free functions and built with LEVITTE_DEBUG_MEM defined.

This illustrates what we have found:

**LEVITTE_DEBUG_MEM:         > 0x0x7f9e0a4303a0 (600) err.c:1036 in thread 0x700027859000**
INFO    Looks like file err.c:453 in thread 0x700036886000 already owns mux 1. Thread 0x700027859000 blocking.
LEVITTE_DEBUG_MEM:         > 0x0x7f9e0a67e810 (600) err.c:1036 in thread 0x70003c898000
INFO    Looks like file err.c:453 in thread 0x700036886000 already owns mux 1. Thread 0x70003c898000 blocking.
LEVITTE_DEBUG_MEM:         > 0x0x7f9e0a5068b0 (176) lhash.c:138 in thread 0x700036886000
LEVITTE_DEBUG_MEM:         > 0x0x7f9e0a5069d0 (128) lhash.c:140 in thread 0x700036886000
INFO    err.c:453 in thread 0x700027859000 acquired mux 1 from thread 0x700036886000.
INFO    err.c:453 in thread 0x70003c898000 acquired mux 1 from thread 0x700036886000.
LEVITTE_DEBUG_MEM:         > 0x0x7f9e0a679f90 (24) lhash.c:210 in thread 0x700036886000
LEVITTE_DEBUG_MEM:         < 0x0x7f9e0a506290 err.c:655 in thread 0x700036886000`
**LEVITTE_DEBUG_MEM:         < 0x0x7f9e0a4303a0 err.c:655 in thread 0x700027859000**
LEVITTE_DEBUG_MEM:         > 0x0x7f9e0a664600 (72) dso_lib.c:106 in thread 0x700036886000
INFO    Looks like file eng_table.c:259 in thread 0x700036886000 already owns mux 30. Thread 0x700027859000 blocking.
**_LEVITTE_DEBUG_MEM:         < 0x0x7f9e0a4303a0 err.c:655 in thread 0x70003c898000_**
unit_tests(10949,0x70003c898000) malloc: *** error for object 0x7f9e0a4303a0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Assuming (as appears to be the case) LEVITTE_DEBUG_MEM indicates memory allocation by '>' and memory freed by '<' we have the following (with our additional debugging added):

Memory address 0x7f9e0a4303a0 is allocated in thread 0x700027859000. Then it is 
 is first freed in thread 0x700027859000. Then again in thread 0x70003c898000 where upon we segfault (as we should with a double free).

We are going to move up to OpenSSL 1.1 and depending upon the results will not be investigating the crash above further - except to provide additional information as you request.

If we find the issue in OpenSSL 1.1 we will resume our analysis there.

Feel free to direct us to the fix if it has already been made!

**Comment by mattcaswell** [comment]
Hmmm...not aware of any fixes made in this area, or any other reports of this. The 1.1.0 threading approach is quite different so it is quite likely that you will not experience this issue there (assuming the problem is in OpenSSL code).

**Comment by richsalz** [comment]
Is this a dynamically loaded ENGINE?

**Comment by Sleepless-Knight** [comment]
Forgive my belated response. The emails finished up in junk and tis a long time since I checked.

Our CURL source appears to define this:

/* Define to 1 if you have the `ENGINE_load_builtin_engines' function. */
#define HAVE_ENGINE_LOAD_BUILTIN_ENGINES 1

Presumably then a dynamically loaded engine is only there if it is bundled with OpenSSL?

**Comment by t8m** [comment]
1.0.2 branch is out of regular support. Closing.
