### ISSUE TITLE
Can not access member of X509_st in Axis2c project.

### ISSUE THREAD

**Issue by nixiejun** [openssl/openssl#5717]
Hi All,

In Axis2c, src\core\transport\http\sender\ssl\ssl_utils.c contains a piece of code:

       ` 
        X509 *peer_cert = NULL
        X509_STORE *cert_store = NULL;
        X509_NAME *peer_name = NULL;
        X509_OBJECT *client_object = NULL;
        X509 *client_cert = NULL;
        peer_cert = SSL_get_peer_certificate(ssl);
        if (peer_cert && peer_cert->cert_info)
        {
            peer_name = (peer_cert->cert_info)->subject;
        }
        cert_store = SSL_CTX_get_cert_store(ctx);
        if (peer_name && cert_store)
        {
            client_object = X509_OBJECT_retrieve_by_subject(cert_store->objs,
                X509_LU_X509,
                peer_name);
        }
        if (client_object)
        {
            client_cert = (client_object->data).x509;
            if (client_cert &&
                (M_ASN1_BIT_STRING_cmp(client_cert->signature,
                        peer_cert->signature) == 0))
            {
                if (peer_cert)
                {
                    X509_free(peer_cert);
                }
                AXIS2_LOG_DEBUG(env->log, AXIS2_LOG_SI,
                    "[ssl client] SSL certificate verified against peer");
                return ssl;
            }
        }`

When compiling, errors occurs:
`>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(30): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\string.h(335): note: see declaration of 'strncpy'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(166): error C2037: left of 'cert_info' specifies undefined struct/union 'x509_st'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(168): error C2037: left of 'cert_info' specifies undefined struct/union 'x509_st'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(174): error C2037: left of 'objs' specifies undefined struct/union 'x509_store_st'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(175): warning C4047: 'function': 'stack_st_X509_OBJECT *' differs in levels of indirection from 'int'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(175): warning C4024: 'X509_OBJECT_retrieve_by_subject': different types for formal and actual parameter 1
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(176): error C2440: 'function': cannot convert from 'X509_NAME *' to 'X509_LOOKUP_TYPE'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(176): warning C4024: 'X509_OBJECT_retrieve_by_subject': different types for formal and actual parameter 2
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(176): error C2198: 'X509_OBJECT_retrieve_by_subject': too few arguments for call
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(180): error C2037: left of 'data' specifies undefined struct/union 'x509_object_st'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(182): warning C4013: 'M_ASN1_BIT_STRING_cmp' undefined; assuming extern returning int
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(182): error C2037: left of 'signature' specifies undefined struct/union 'x509_st'
1>Z:\3rdParty_Source\xquery_builder\mstr_axis2c\src\core\transport\http\sender\ssl\ssl_utils.c(183): error C2037: left of 'signature' specifies undefined struct/union 'x509_st'`

Seems that in 1.1.0, x509 structure is made opaque. But I am not sure which accessor function should I call to obtain the member. Is there an document that can guide me? Thanks in advance.

**Comment by mattcaswell** [comment]
A good place to start is to review the list of various accessor functions and other APIs listed here:

https://www.openssl.org/docs/man1.1.0/crypto/

For the subject name ((peer_cert->cert_info)->subject) use `X509_get_subject_name()`:

https://www.openssl.org/docs/man1.1.0/crypto/X509_get_subject_name.html

For the cert_store object cache (cert_store->objs) use X509_STORE_get0_objects():

https://www.openssl.org/docs/man1.1.0/crypto/X509_STORE_get0_objects.html

To get the X509 out of an X509_OBJECT ((client_object->data).x509) use X509_OBJECT_get0_X509() (darn! not documented)

To get the signature out of an X509 (client_cert->signature) use X509_get0_signature():

https://www.openssl.org/docs/man1.1.0/crypto/X509_get0_signature.html
