### ISSUE TITLE
openssl s_client a –verify_host in -h (help) should be  –verify_hostname

### ISSUE THREAD

**Issue by gmadkat** [openssl/openssl#572]
I found a bug in the usage of openssl s_client:

Openssl s_client –h says the usage for hostname verification is –verify_host. This does not work. I dug thru the code and discovered it is actually –verify_hostname. Minor typo, but hard to find unless you look at the code… 

This wont work:

openssl s_client -connect <host>:<port> -tls1_2  -verify_host  getdnsapi.net

This works:

openssl s_client -connect  <host>:<port> -tls1_2  -verify_hostname getdnsapi.net

**Comment by richsalz** [comment]
Which version?  I don't see this.

**Comment by gmadkat** [comment]
I see this on the OpenSSL 1.0.2e

**Comment by richsalz** [comment]
thanks fixed with 78a140e which will be in the next 1.0.2 release.
