### ISSUE TITLE
How to better understand openssl?

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [openssl/openssl#5724]
I have insisted on reading the openssl source code for 2 months，however，I have 2 doubts:
	a.how can I better grasp the openssl architecture
	b.how to better use the openssl application scenario

**Comment by richsalz** [comment]
You might be better served by looking at an application that uses it (mod_ssl in apache?) and then starting to read the API's that are called.  Or look at the apps code, and trace through them.
Good luck.

**Comment by aixiaoxiaoyu** [comment]
Thank you ! @richsalz
