### ISSUE TITLE
Modify Antminer A3 Algo Blake2b to Mine Blake2s

### ISSUE THREAD

**Issue by scottymcquaker** [openssl/openssl#5734]
Can someone help me work out how to do this?  

Thanks

**Comment by dot-asm** [comment]
No. This is not OpenSSL *issue*.

**Comment by scottymcquaker** [comment]
what thread is best?

**Comment by richsalz** [comment]
Wherever you got the software you are asking about?  I have no idea what "antminer" is or where to get it.
