### ISSUE TITLE
multicerts for multi algorithm server handshake fail.

### ISSUE THREAD

**Issue by ken1no** [openssl/openssl#5735]
Multicerts for multi algorithm (RSA+SHA256:ECDSA+SHA256) server handshake fails for RSA+SHA256.
at OpenSSL 1.1.1-pre3 / -tls1_3
our server setting is 

/usr/local/bin/openssl s_server -tls1_3 -cert ~/.acme.sh/www.example.com/fullchain.cer -key ~/.acme.sh/www.example.com/www.example.com.key  -cert2 ~/.acme.sh/www.example.com_ecc/fullchain.cer -key2 ~/.acme.sh/www.example.com_ecc/www.example.com.key -servername www.example.com

and the client with sigalgs = ECDSA+SHA256  is success. 

# /usr/local/bin/openssl s_client -host www.example.com -port 4433 -tls1_3  -servername www.example.com  -sigalgs ECDSA+SHA256

but the client with sigalgs = RSA+SHA256 is fail. 

# /usr/local/bin/openssl s_client -host www.example.com -port 4433 -tls1_3 -servername www.example.com -sigalgs RSA+SHA256
CONNECTED(00000003)
34387091456:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1570:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 214 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1521809346
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

---------------------------------
server message:
---------------------------------
ACCEPT
Hostname in TLS extension: "www.example.com"
Switching server context.
ERROR
34387091456:error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:2472:
shutting down SSL
CONNECTION CLOSED
ACCEPT

**Comment by kaduk** [comment]
What happens if the client passes ```rsa_pss_pss_sha256``` instead of ```RSA+SHA256```?  The latter implies RSA with PKCS#1 padding, which is not permitted for TLS 1.3 signatures.

**Comment by mattcaswell** [comment]
When both `-cert`/`-key` and `-cert2`/`-key2` are used this enables you to set up different certs/keys for the default server and the server for the supplied SNI server name. It does *not* enable you to set up multiple certs/keys for the *same* SNI server name (or default server). OpenSSL (the library) does allow you to do this, but it is not exposed via `s_server`.

> Can I use certificates of different signature algorithms (set of -key and -cert is RSA-PSS+SHA256, set of -key2 and -cert2 is ECDSA+SHA256) with the same domain name?

Yes in your own application code, but not via `s_server`.

Closing this.
