### ISSUE TITLE
Included TLS 1.3 ciphers in "openssl ciphers -V <crappy_pattern>"

### ISSUE THREAD

**Issue by drwetter** [openssl/openssl#5736]
```
OpenSSL 1.1.1-pre3 (beta) 20 Mar 2018
built on: Fri Mar 23 12:35:22 2018 UTC
platform: linux-x86_64
options:  bn(64,64) md2(char) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64  -Wa,--noexecstack -fsanitize=address -fno-omit-frame-pointer -g -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DOPENSSL_USE_BUILD_DATE
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr//lib64/engines-1.1"
Seeding source: os-specific
```

```
apps/openssl ciphers  -V RC2                                                                                               master
          0x13,0x02 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
          0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0x13,0x01 - TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
```

```
apps/openssl ciphers  -V aNULL                                                                                             master
          0x13,0x02 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
          0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0x13,0x01 - TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
          0x00,0xA7 - ADH-AES256-GCM-SHA384   TLSv1.2 Kx=DH       Au=None Enc=AESGCM(256) Mac=AEAD
          0x00,0xA6 - ADH-AES128-GCM-SHA256   TLSv1.2 Kx=DH       Au=None Enc=AESGCM(128) Mac=AEAD
          0x00,0x6D - ADH-AES256-SHA256       TLSv1.2 Kx=DH       Au=None Enc=AES(256)  Mac=SHA256
          0x00,0xC5 - ADH-CAMELLIA256-SHA256  TLSv1.2 Kx=DH       Au=None Enc=Camellia(256) Mac=SHA256
          0x00,0x6C - ADH-AES128-SHA256       TLSv1.2 Kx=DH       Au=None Enc=AES(128)  Mac=SHA256
          0x00,0xBF - ADH-CAMELLIA128-SHA256  TLSv1.2 Kx=DH       Au=None Enc=Camellia(128) Mac=SHA256
          0xC0,0x19 - AECDH-AES256-SHA        TLSv1 Kx=ECDH     Au=None Enc=AES(256)  Mac=SHA1
          0x00,0x3A - ADH-AES256-SHA          SSLv3 Kx=DH       Au=None Enc=AES(256)  Mac=SHA1
          0x00,0x89 - ADH-CAMELLIA256-SHA     SSLv3 Kx=DH       Au=None Enc=Camellia(256) Mac=SHA1
          0xC0,0x18 - AECDH-AES128-SHA        TLSv1 Kx=ECDH     Au=None Enc=AES(128)  Mac=SHA1
          0x00,0x34 - ADH-AES128-SHA          SSLv3 Kx=DH       Au=None Enc=AES(128)  Mac=SHA1
          0x00,0x9B - ADH-SEED-SHA            SSLv3 Kx=DH       Au=None Enc=SEED(128) Mac=SHA1
          0x00,0x46 - ADH-CAMELLIA128-SHA     SSLv3 Kx=DH       Au=None Enc=Camellia(128) Mac=SHA1
          0xC0,0x16 - AECDH-RC4-SHA           TLSv1 Kx=ECDH     Au=None Enc=RC4(128)  Mac=SHA1
          0x00,0x18 - ADH-RC4-MD5             SSLv3 Kx=DH       Au=None Enc=RC4(128)  Mac=MD5 
          0xC0,0x17 - AECDH-DES-CBC3-SHA      TLSv1 Kx=ECDH     Au=None Enc=3DES(168) Mac=SHA1
          0x00,0x1B - ADH-DES-CBC3-SHA        SSLv3 Kx=DH       Au=None Enc=3DES(168) Mac=SHA1
          0xC0,0x15 - AECDH-NULL-SHA          TLSv1 Kx=ECDH     Au=None Enc=None      Mac=SHA1
```

**Comment by mattcaswell** [comment]
This is correct behaviour. See:

https://github.com/openssl/openssl/blob/master/CHANGES#L16

Also see the description of the cipherlist argument to the `ciphers` command line app, here:

https://www.openssl.org/docs/man1.1.1/man1/ciphers.html

**Comment by drwetter** [comment]
it breaks programs using the cmdline interface. It's a breaking change I do not see a reason for.
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by kroeckx** [comment]
The problem is that not doing it the current way breaks more. If
you can come up with a good proposal on how to deal with this, we
always want to know.

**Comment by drwetter** [comment]
Am 23. März 2018 19:13:15 MEZ schrieb Kurt Roeckx <notifications@github.com>:
>The problem is that not doing it the current way breaks more. If
>you can come up with a good proposal on how to deal with this, we
>always want to know.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openssl/openssl/issues/5736#issuecomment-375755284

okay. In order to answer this and come up with a proposal I need to understand the reason why you're doing this and why it can't be hidden from the user. 

As said from the user perspective it breaks programs. Besides the response of the ciphers command looks utterly awkward.

Cheers, Dirk

-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by kroeckx** [comment]
Have you read this?
https://www.openssl.org/blog/blog/2018/02/08/tlsv1.3/

There are lots of people that set up their cipher list specifying
ciphers, and none of the TLS 1.3 ciphers matches.

The only alternative is not to use TLS 1.3, which we think is even
worse.

I'm also not sure how it broke things for you.


Kurt

**Comment by mattcaswell** [comment]
See #5359 and #5392 for a discussion on some of the issues. TLSv1.3 ciphersuites do not work like TLSv1.2 and below ciphersuites. All options we have considered for introducing them break something - short of disabling TLSv1.3 by default which we do not want to do. This is the least breaking change we can come up with.

**Comment by drwetter** [comment]
I swallowed this a while back but every time when I try just to list ciphers and try to figure out what a specific openssl version supports -- this is my complaint and nothing else -- I am still scratch my head.

Reading #5359 and #5392 didn't give me a hint why the **list function** ``openssl ciphers`` produces as a default non-compatible results. 

Today I even tried to inhibit the usage of TLS 1.3 ciphers using a openssl 1.0.2 compatible command line where I don't need to do a workaround for just listing ciphers. A workaround in my case (testssl.sh) means: 

a) find out the openssl version, 
b) build the command line for
c) list ciphers.

Instead of just listing ciphers.

Even this doesn't work which feels quite strange:

```
root@7349dd6d615b:~# openssl ciphers -V '!TLS_AES_128_GCM_SHA256:!TLS_AES_256_GCM_SHA384:!TLS_CHACHA20_POLY1305_SHA256:!TLSv1.3'
          0x13,0x02 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
          0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0x13,0x01 - TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
root@7349dd6d615b:~# openssl version
OpenSSL 1.1.1a  20 Nov 2018
root@7349dd6d615b:~#
```

I do understand that for library calls, openssl s_client, s_server and friends we always want TLS 1.3 ciphers. But why can't one just use standard means like the one above?  


PS: WRT the blog entry from @mattcaswell  which @kroeckx  cited.: E.g. ``openssl ciphers -s -v "ECDHE:!COMPLEMENTOFDEFAULT"`` works for me only in ksh. Others like tcsh/csh, bash, zsh complain because of the not quoted ``!`. Single quotes should work for all shells.
