### ISSUE TITLE
The version of a CSR is not checked using `openssl req`.

### ISSUE THREAD

**Issue by LuckyResistor** [openssl/openssl#5738]
The `req` command does not check the version byte after reading a certificate signing request. If the command line tool is reading a file with an unsupported version number (anything greater than zero), it will proceed and ignore this error. The `-verify` option will give an `OK` result, even a such CSR is, as fast as I can see, not valid.

As I understand, the latest specification implemented in the openssl library is PKCS#10 version 1.7, which requires a version number `0x00` for this field.

**Comment by richsalz** [comment]
It does not seem worth blocking 1.1.1 for this.  And also, flexibility in creating objects is a useful debugging tool.

**Comment by nhorman** [comment]
I don't see this fixed yet, but I don't see this fitting into our schedule either, @LuckyResistor are you interested in creating a PR for this issue?

**Comment by LuckyResistor** [comment]
@nhorman I’ll check if this is still an issue. If it is, I’ll ensure a PR is created to resolve it.

**Comment by nhorman** [comment]
@LuckyResistor Thank you!  Assigning this to you as a community issue

**Comment by LuckyResistor** [comment]
@nhorman Please, assign this issue to @erbsland-dev

**Comment by nhorman** [comment]
can do, thank you

**Comment by erbsland-dev** [comment]
@nhorman No problem at all. I just realized that my PR can be simplified by using the X509_* functions instead of checking at the ASN1 layer. I’ll add a second commit to the PR to make this adjustment.

**Comment by nhorman** [comment]
and with that, I've assigned this to you, many thanks!  I see your PR has been attached as well, which is great.  Just need you to sign a cla if you are able please (link provided over in the PR), so that we can consider the patch.

**Comment by erbsland-dev** [comment]
@nhorman Just signed and sent the ICLA.
