### ISSUE TITLE
Facing Openssl linker issue while trying to reproduce curl related issue

### ISSUE THREAD

**Issue by chandran-uday** [openssl/openssl#5758]
Trying to write a tester to reproduce the curl related issue by linking it with openssl libraries.But i'm facing linker issues related to openssl...
 
Could someone suggest me the feasible solution to get resolved from this issue?
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "curl/curl.h"

int main()
{

    CURLM *pCurl;

    pCurl  =  curl_multi_init();

    if (!(pCurl))
    {

        printf("MultiHandle init failed");
        return -1;
    }

    return 1;
}

**Makefile :**

CC      = gcc
CFLAGS  = -c -Wall -Iinclude
RM      = rm -f

all: curl_test.o
        gcc -o curltest  -lcurl -lcrypto -lssl -lz -lssh2

curl_test.o:curl_test.c
        $(CC) $(CFLAGS) curl_test.c

clean:
        $(RM) curltest
		
		
		
**Issue which i'm getting while linking**

root@localhost curl_test]# make
gcc -o curltest  lib/libcurl.so -lcrypto -lssl -lz libssh2.so
/usr/bin/ld: warning: libssl.so.1.0.0, needed by lib/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by lib/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
lib/libcurl.so: undefined reference to `SSL_CTX_set_srp_username'
lib/libcurl.so: undefined reference to `SSL_CTX_set_srp_password'
collect2: ld returned 1 exit status
make: *** [all] Error 1

**Comment by t8m** [comment]
This was left unanswered for more than 3 years. I am sorry for that but given this was just some local environment issue (wrong/missing installation of proper openssl and/or libcurl packages) I am closing this now.
