### ISSUE TITLE
Please adjust the security levels to be more practical

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#5760]
_This issue is meant to start a discussion how to improve the usefulness of `@SECLEVEL` setting. The proposal below can be adjusted according to it._

The current meaning of security levels is not that practical for real world use. Given the current use of the parameters affected by the `@SECLEVEL` it is not particularly useful to use anything higher than level 2 which on the other hand does not disable things that are not that widely used any more and whose security is already problematic.

The setting could be more practical if following or similar adjustment was done:

**Level 1**: Disable also SSL3.

**Level 2**: Disable also 3DES and TLS 1.0

**Level 3**: Disable also TLS 1.1 and DTLS 1.0

**Comment by mattcaswell** [comment]
Probably this is not going to happen for 1.1.1. Moving to a post 1.1.1 milestone.

**Comment by t8m** [comment]
Sure, I have no problem with that.

**Comment by t8m** [comment]
This is obsolete now.
