### ISSUE TITLE
OpenSSL_1_0_2o doesn't build with no-threads config and parallel build

### ISSUE THREAD

**Issue by bnason-nf** [openssl/openssl#5762]
Hi,

I just tried to build OpenSSL_1_0_2o with "./config no-threads && make -j", it fails with a missing ENGINE_load_gost symbol, the tail of the output is this:

>../libcrypto.a(eng_all.o): In function `ENGINE_load_builtin_engines':
>eng_all.cmake[2]: Leaving directory 'openssl/test'
>:(.text+0x41): undefined reference to `ENGINE_load_gost'
>collect2: error: ld returned 1 exit status
>../Makefile.shared:164: recipe for target 'link_app.' failed
>make[2]: *** [link_app.] Error 1
>make[2]: Leaving directory 'openssl/test'
>Makefile:528: recipe for target 'evp_test' failed
>make[1]: *** [evp_test] Error 2
>make[1]: Leaving directory 'openssl/test'
>Makefile:295: recipe for target 'build_tests' failed
>make: *** [build_tests] Error 1
>make: *** Waiting for unfinished jobs....
>../libcrypto.a(eng_all.o): In function `ENGINE_load_builtin_engines':
>eng_all.c:(.text+0x41): undefined reference to `ENGINE_load_gost'
>collect2: error: ld returned 1 exit status
>../Makefile.shared:164: recipe for target 'link_app.' failed
>make[2]: *** [link_app.] Error 1
>make[2]: Leaving directory 'openssl/apps'
>Makefile:156: recipe for target 'openssl' failed
>make[1]: *** [openssl] Error 2
>make[1]: Leaving directory 'openssl/apps'
>Makefile:293: recipe for target 'build_apps' failed
>make: *** [build_apps] Error 1

It builds fine if I just do a "./config && make -j", or a "./config no-threads && make". Is this a known limitation of the openssl build? If I'm understanding issue #298 correctly, parallel builds should be working.

Thanks,
Benbuck

**Comment by levitte** [comment]
Parallell builds are not possible with OpenSSL < 1.1.0.  That is known.  Please try without `-j`

**Comment by bnason-nf** [comment]
Hi Richard,

Thanks for the response. As noted above, it does work without -j, I just wasn't sure whether that was expected or not, but it sounds like it is.

Thanks,
Benbuck
