### ISSUE TITLE
version 1.0.2n with -DNO_RC4 flag does not take out RC4 ciphers

### ISSUE THREAD

**Issue by MikeY2018** [openssl/openssl#5763]
Hello,

With OpenSSL 1.0.2n, Qualys still reporting

Vulnerabilities reported:
SSL/TLS use of weak RC4 cipher
Birthday attacks against TLS ciphers with 64bit block size vulnerability (Sweet32)
HTTP Security Header Not Detected
 
What flags do I need to set to rebuild 1.0.2n so that these can be taken care of?

According to the Makefile, the following flags when defined with "config" will disable the algorithms

```
# NO_IDEA - Define to build without the IDEA algorithm
# NO_RC4  - Define to build without the RC4 algorithm
# NO_RC2  - Define to build without the RC2 algorithm
```

The executable "openssl" generated responds to RC4-SHA cipher using this command:
```
openssl s_client -cipher 'RC4-SHA' -connect <target:443> -tls1_2
```

Running "openssl version -a" on the server yielded the following:
```
OpenSSL 1.0.2n  7 Dec 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DNO_IDEA -DNO_RC4 -DNO_RC2 -DSSL_FORBID_ENULL -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/ssl"
```

Thanks.
Michael

**Comment by levitte** [comment]
Errr...  those comments in Makefile our outdated.  Did you read INSTALL?  There you have the correct instruction, which includes:

> ```
>   no-<cipher>   Build without the specified cipher (bf, cast, des, dh, dsa,
>                 hmac, md2, md5, mdc2, rc2, rc4, rc5, rsa, sha).
>                 The crypto/<cipher> directory can be removed after running
>                 "make depend".
> ```

**Comment by MikeY2018** [comment]
Thanks. That works.
