### ISSUE TITLE
 crl -out /dev/null gives permission denied 

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#5764]
It seems to me I have to report regression in master branch in a separate issue instead "https://github.com/openssl/openssl/issues/5590#issuecomment-373502637 "

Following command ${OPENSSL} crl -out /dev/null -in "${FILE}" -hash works fine in my regression test for about 15 years. For protocol you could see command in diffs for http://roumenpetrov.info/openssh/download-20040819.html#get_f (2003-01-30 12:14:15+0200)

Reverting commits related "Check directory is able to create files for various -out option" restores previous functionality.

**Comment by mspncp** [comment]
I am sorry, it seems like I closed #5590 prematurely. I forgot about your comments in #3709.

**Comment by mattcaswell** [comment]
My understanding is that with #6033 this should be fixed. I just tried it and it seems to be ok now. Closing.
