### ISSUE TITLE
1.1.0h - compile warnings with MinGW & gcc 7.3.0

### ISSUE THREAD

**Issue by MSP-Greg** [openssl/openssl#5766]
1.1.0h built & passed all tests, which is typical.

I build & test Ruby trunk (head/master), and when MinGW changed to gcc 7.x, there were quite a few compiler warnings.

If the info is helpful, I can attached all of them...

Thanks, Greg

**Comment by richsalz** [comment]
If they are about size and/or unsigned things, I don't think they're of interest now.  But if there are other warnings, it would be nice to see them.

**Comment by MSP-Greg** [comment]
I forgot to mention that I'm not really a c type.  I can read it and get a general idea...

Forgot to mention that Ruby `digest` and `openssl` built also without failures using the 1.1.0h dll's.

Attached is my attempt at cleaning the log of everything not related to the warnings....

[mingw-w64-openssl-1.1.0.h-1-x86_64-build_warnings.log](https://github.com/openssl/openssl/files/1853975/mingw-w64-openssl-1.1.0.h-1-x86_64-build_warnings.log)

Thanks for your work.

**Comment by richsalz** [comment]
Thank you!  Perhaps @mspncp wants to take a look, but my initial reaction is that most of these are fixed in master, and the others are mostly-harmless noise warnings.

**Comment by MSP-Greg** [comment]
Thank you.  Maybe this weekend I'll try and build 1.1.1.  Standard MSYS2/MinGW is currently using 1.0.2.

**Comment by mspncp** [comment]
@richsalz, I'm not sure why you picked me as candidate for looking at [mingw-w64-openssl-1.1.0.h-1-x86_64-build_warnings.log](https://github.com/openssl/openssl/files/1853975/mingw-w64-openssl-1.1.0.h-1-x86_64-build_warnings.log)? We don't use mingw to build OpenSSL on Windows.

Regarding the `BIO_PRI64` format string warnings, @dot-asm might be the right consultant, see 70b9063cd24904fd3d0b83173c51fdcf34085967.

As for the `setsockopt()` warning: I know that the warnings occur because Microsoft declares `optval` non-posix-ly as `const char *` instead of `const void *`, see [setsockopt() on MSDN](https://msdn.microsoft.com/de-de/library/windows/desktop/ms740476%28v=vs.85%29.aspx). Also, I stumbled over an interesting ten year old thread about [setsockopt on mingw](https://lists.gnu.org/archive/html/bug-gnulib/2008-04/msg00283.html) on bug-gnulib started by Simon Josefsson (@jas4711?). Maybe he can tell us what happened to his patches that attempted to fix this issue?


```
../openssl-1.1.0h/crypto/bio/b_sock2.c:90:56: warning: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
         if (setsockopt(sock, SOL_SOCKET, SO_KEEPALIVE, &on, sizeof(on)) != 0) {
                                                        ^

In file included from ../openssl-1.1.0h/e_os.h:199:0,
                 from ../openssl-1.1.0h/crypto/bio/bio_lcl.h:11,
                 from ../openssl-1.1.0h/crypto/bio/b_sock2.c:14:
E:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:999:34: note: expected 'const char *' but argument is of type 'int *'
   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
                                  ^~~~~~~~~~
```

**Comment by bernd-edlinger** [comment]
I think the warnings about "ll" formatting are because BIO_printf
is actually using gnu format strings, IOW %lld does not work with msvcrt
only %I64d does but the format attribute indicates system default runtime.
You could try to change the attribute on BIO_printf to something like this:

```
diff --git a/include/openssl/bio.h b/include/openssl/bio.h
index f435bd8..337ecc0 100644
--- a/include/openssl/bio.h
+++ b/include/openssl/bio.h
@@ -718,13 +718,13 @@ void BIO_copy_next_retry(BIO *b);
 #  define __bio_h__attr__(x)
 # endif
 int BIO_printf(BIO *bio, const char *format, ...)
-__bio_h__attr__((__format__(__printf__, 2, 3)));
+__bio_h__attr__((__format__(__gnu_printf__, 2, 3)));
 int BIO_vprintf(BIO *bio, const char *format, va_list args)
-__bio_h__attr__((__format__(__printf__, 2, 0)));
+__bio_h__attr__((__format__(__gnu_printf__, 2, 0)));
 int BIO_snprintf(char *buf, size_t n, const char *format, ...)
-__bio_h__attr__((__format__(__printf__, 3, 4)));
+__bio_h__attr__((__format__(__gnu_printf__, 3, 4)));
 int BIO_vsnprintf(char *buf, size_t n, const char *format, va_list args)
-__bio_h__attr__((__format__(__printf__, 3, 0)));
+__bio_h__attr__((__format__(__gnu_printf__, 3, 0)));
 # undef __bio_h__attr__

```

**Comment by richsalz** [comment]
Because, sadly, as a dumb American I picked the wrong German.  Sorry to both Bernd and Matthias.

**Comment by bernd-edlinger** [comment]
I don't have access to a mingw system but I can come up with a PR if someone
is willing to try out if the above patch improves the situation...

**Comment by MSP-Greg** [comment]
@bernd-edlinger @richsalz

Thank you for the work.  Below are the differences in the build logs:
```
Build Log Search Results 1.1.0h
before & after patch

before  after  search regex
  14      0    BIO_[a-z]*printf
  35     18    : warning:
```

Below is the list of remaining warnings:
```
warning: overflow in implicit constant conversion [-Woverflow]
crypto/bio/b_sock.c:211:13
crypto/bio/b_sock.c:216:16
crypto/bio/b_sock.c:219:16
crypto/bio/b_sock.c:226:13
crypto/bio/b_sock.c:233:13
crypto/bio/b_sock2.c:45:16
crypto/bio/b_sock2.c:51:16

warning: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
crypto/bio/b_sock2.c:90:56
crypto/bio/b_sock2.c:98:56
crypto/bio/b_sock2.c:164:47
crypto/bio/b_sock2.c:189:56
crypto/bio/b_sock2.c:197:56
crypto/bio/b_sock2.c:211:57

warning: overflow in implicit constant conversion [-Woverflow]
crypto/bio/b_sock2.c:256:16
crypto/bio/b_sock2.c:261:16

warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
crypto/engine/eng_list.c:346:22

warning: passing argument 1 of '_InterlockedExchangeAdd' from incompatible pointer type [-Wincompatible-pointer-types]
crypto/threads_win.c:132:35

warning: overflow in implicit constant conversion [-Woverflow]
apps/s_socket.c:92:21
```


Please feel free to ping me re MinGW builds.

Thanks again, Greg

**Comment by MSP-Greg** [comment]
Not being a c type, not sure what the last list of warnings indicate, but there are patches re 'gnu_printf' in Ruby MinGW builds.

So, I'm okay to close.  Thanks again, Greg

**Comment by t8m** [comment]
Closing as this was reported against 1.1.0 which is out of support for a long time. If it applies to master, please open a new issue.
