### ISSUE TITLE
Why is ssl3_ciphers not const while ssl2_ciphers was (before it was removed)?

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#5768]
https://github.com/openssl/openssl/blob/e6e9170d6e28038768895e1af18e3aad8093bf4b/ssl/s3_lib.c#L127

This can/should be const.

**Comment by mattcaswell** [comment]
Because of this:

https://github.com/openssl/openssl/blob/e6e9170d6e28038768895e1af18e3aad8093bf4b/ssl/s3_lib.c#L3215
