### ISSUE TITLE
Why recompiled 1.0.2n responds to Qualys Cipher suites?

### ISSUE THREAD

**Issue by MikeY2018** [openssl/openssl#5775]
Hi,

I was able to use "no-<cipher>" to removed unwanted and weak ciphers and yet Qualys reported cipher suites.

The recompiled version showed the following suites for each protocol.
tls1_1:	ECDHE-RSA-AES256-SHA
tls1_1:	DHE-RSA-AES256-SHA
tls1_1:	DHE-RSA-CAMELLIA256-SHA
tls1_1:	AES256-SHA
tls1_1:	CAMELLIA256-SHA
tls1_1:	ECDHE-RSA-AES128-SHA
tls1_1:	DHE-RSA-AES128-SHA
tls1_1:	DHE-RSA-CAMELLIA128-SHA
tls1_1:	AES128-SHA
tls1_1:	CAMELLIA128-SHA
tls1_2:	ECDHE-RSA-AES256-GCM-SHA384
tls1_2:	ECDHE-RSA-AES256-SHA384
tls1_2:	ECDHE-RSA-AES256-SHA
tls1_2:	DHE-RSA-AES256-GCM-SHA384
tls1_2:	DHE-RSA-AES256-SHA256
tls1_2:	DHE-RSA-AES256-SHA
tls1_2:	DHE-RSA-CAMELLIA256-SHA
tls1_2:	AES256-GCM-SHA384
tls1_2:	AES256-SHA256
tls1_2:	AES256-SHA
tls1_2:	CAMELLIA256-SHA
tls1_2:	ECDHE-RSA-AES128-GCM-SHA256
tls1_2:	ECDHE-RSA-AES128-SHA256
tls1_2:	ECDHE-RSA-AES128-SHA
tls1_2:	DHE-RSA-AES128-GCM-SHA256
tls1_2:	DHE-RSA-AES128-SHA256
tls1_2:	DHE-RSA-AES128-SHA
tls1_2:	DHE-RSA-CAMELLIA128-SHA
tls1_2:	AES128-GCM-SHA256
tls1_2:	AES128-SHA256
tls1_2:	AES128-SHA
tls1_2:	CAMELLIA128-SHA

Qualys reported the following:

# TLS 1.2                                                 (suites in server-preferred order)
--
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)                                                                                                                              DH 2048 bits   FS | 256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x6b)                                                                                                                              DH 2048 bits   FS | 256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)                                                                                                                              DH 2048 bits   FS | 256
TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA (0x88)                                                                                                                              DH 2048 bits   FS | 256
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)                                                                                       WEAK | 256
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d)                                                                                       WEAK | 256
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)                                                                                       WEAK | 256
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (0x84)                                                                                       WEAK | 256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 128
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 128
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 128
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)                                                                                                                              DH 2048 bits   FS | 128
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x67)                                                                                                                              DH 2048 bits   FS | 128
TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x33)                                                                                                                              DH 2048 bits   FS | 128
TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA (0x45)                                                                                                                              DH 2048 bits   FS | 128
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)                                                                                       WEAK | 128
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c)                                                                                       WEAK | 128
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)                                                                                       WEAK | 128
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (0x41)                                                                                       WEAK | 128
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (0xc012)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       WEAK | 112
TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (0x16)                                                                                                         DH 2048 bits   FS                                                                   WEAK | 112
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)                                                                                       WEAK | 112
TLS_DHE_RSA_WITH_SEED_CBC_SHA (0x9a)                                                                                                                              DH 2048 bits   FS | 128
TLS_RSA_WITH_SEED_CBC_SHA (0x96)                                                                                       WEAK | 128
TLS_RSA_WITH_IDEA_CBC_SHA (0x7)                                                                                       WEAK | 128
TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       INSECURE | 128
TLS_RSA_WITH_RC4_128_SHA (0x5)                                                                                       INSECURE | 128
TLS_RSA_WITH_RC4_128_MD5 (0x4)                                                                                       INSECURE | 128
# TLS 1.1                                                 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)                                                                                                                              DH 2048 bits   FS | 256
TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA (0x88)                                                                                                                              DH 2048 bits   FS | 256
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)                                                                                       WEAK | 256
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (0x84)                                                                                       WEAK | 256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 128
TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x33)                                                                                                                              DH 2048 bits   FS | 128
TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA (0x45)                                                                                                                              DH 2048 bits   FS | 128
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)                                                                                       WEAK | 128
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (0x41)                                                                                       WEAK | 128
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (0xc012)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       WEAK | 112
TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (0x16)                                                                                                         DH 2048 bits   FS                                                                   WEAK | 112
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)                                                                                       WEAK | 112
TLS_DHE_RSA_WITH_SEED_CBC_SHA (0x9a)                                                                                                                              DH 2048 bits   FS | 128
TLS_RSA_WITH_SEED_CBC_SHA (0x96)                                                                                       WEAK | 128
TLS_RSA_WITH_IDEA_CBC_SHA (0x7)                                                                                       WEAK | 128
TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       INSECURE | 128
TLS_RSA_WITH_RC4_128_SHA (0x5)                                                                                       INSECURE | 128
TLS_RSA_WITH_RC4_128_MD5 (0x4)                                                                                       INSECURE | 128

Thanks,
Michael

**Comment by mattcaswell** [comment]
> I was able to to use "no-" to removed unwanted and weak ciphers and yet Qualys reported cipher suites.

Please describe the build steps that you took along with all config options

> The recompiled version showed the following suites for each protocol.

How did you generate this list?

> Qualys reported the following:

How did you test? Are you sure that you are using your newly built OpenSSL version and not an old one?

**Comment by MikeY2018** [comment]
Thanks Matt.

1. make clean
2. ./config no-comp no-idea no-dtls1 no-psk no-srp no-bf no-des no-md2 no-rc2 no-rc4 no-rc5 no-seed -DSSL_FORBID_ENULL
3. make test
4. make install

On the server side, I ran this script using loopback on port 443

#!/usr/bin/env bash
#
SERVER=$1

for v in ssl2 ssl3 tls1 tls1_1 tls1_2; do
  for c in $(openssl ciphers 'ALL:eNULL' | tr ':' ' '); do
    openssl s_client -connect $SERVER \
      -cipher $c -$v < /dev/null > /dev/null 2>&1 && echo -e "$v:\t$c"
  done
done

**Comment by MikeY2018** [comment]
I tested using this on the target
https://www.ssllabs.com/ssltest/analyze.html

Here is the version of openssl I built it with
OpenSSL 1.0.2n  7 Dec 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) 
compiler: gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DSSL_FORBID_ENULL -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/ssl"

**Comment by mattcaswell** [comment]
What is the output of `openssl ciphers -v ALL:eNULL`? Can you confirm that qualys is definitely hitting your server (i.e. can you see the test in your server logs)?

**Comment by MikeY2018** [comment]
I can confirm that Qualys is hitting on my server from the rolling output of my log file. Here is the result from 'openssl ciphers -v ALL:eNULL'

ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-RSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA384
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA384
ECDHE-RSA-AES256-SHA    SSLv3 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
ECDHE-ECDSA-AES256-SHA  SSLv3 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA1
DH-DSS-AES256-GCM-SHA384 TLSv1.2 Kx=DH/DSS   Au=DH   Enc=AESGCM(256) Mac=AEAD
DHE-DSS-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=DSS  Enc=AESGCM(256) Mac=AEAD
DH-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA256
DHE-DSS-AES256-SHA256   TLSv1.2 Kx=DH       Au=DSS  Enc=AES(256)  Mac=SHA256
DH-RSA-AES256-SHA256    TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AES(256)  Mac=SHA256
DH-DSS-AES256-SHA256    TLSv1.2 Kx=DH/DSS   Au=DH   Enc=AES(256)  Mac=SHA256
DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
DHE-DSS-AES256-SHA      SSLv3 Kx=DH       Au=DSS  Enc=AES(256)  Mac=SHA1
DH-RSA-AES256-SHA       SSLv3 Kx=DH/RSA   Au=DH   Enc=AES(256)  Mac=SHA1
DH-DSS-AES256-SHA       SSLv3 Kx=DH/DSS   Au=DH   Enc=AES(256)  Mac=SHA1
DHE-RSA-CAMELLIA256-SHA SSLv3 Kx=DH       Au=RSA  Enc=Camellia(256) Mac=SHA1
DHE-DSS-CAMELLIA256-SHA SSLv3 Kx=DH       Au=DSS  Enc=Camellia(256) Mac=SHA1
DH-RSA-CAMELLIA256-SHA  SSLv3 Kx=DH/RSA   Au=DH   Enc=Camellia(256) Mac=SHA1
DH-DSS-CAMELLIA256-SHA  SSLv3 Kx=DH/DSS   Au=DH   Enc=Camellia(256) Mac=SHA1
GOST2001-GOST89-GOST89  SSLv3 Kx=GOST     Au=GOST01 Enc=GOST89(256) Mac=GOST89
GOST94-GOST89-GOST89    SSLv3 Kx=GOST     Au=GOST94 Enc=GOST89(256) Mac=GOST89
AECDH-AES256-SHA        SSLv3 Kx=ECDH     Au=None Enc=AES(256)  Mac=SHA1
ADH-AES256-GCM-SHA384   TLSv1.2 Kx=DH       Au=None Enc=AESGCM(256) Mac=AEAD
ADH-AES256-SHA256       TLSv1.2 Kx=DH       Au=None Enc=AES(256)  Mac=SHA256
ADH-AES256-SHA          SSLv3 Kx=DH       Au=None Enc=AES(256)  Mac=SHA1
ADH-CAMELLIA256-SHA     SSLv3 Kx=DH       Au=None Enc=Camellia(256) Mac=SHA1
ECDH-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH/RSA Au=ECDH Enc=AESGCM(256) Mac=AEAD
ECDH-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AESGCM(256) Mac=AEAD
ECDH-RSA-AES256-SHA384  TLSv1.2 Kx=ECDH/RSA Au=ECDH Enc=AES(256)  Mac=SHA384
ECDH-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AES(256)  Mac=SHA384
ECDH-RSA-AES256-SHA     SSLv3 Kx=ECDH/RSA Au=ECDH Enc=AES(256)  Mac=SHA1
ECDH-ECDSA-AES256-SHA   SSLv3 Kx=ECDH/ECDSA Au=ECDH Enc=AES(256)  Mac=SHA1
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
CAMELLIA256-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(256) Mac=SHA1
ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
ECDHE-RSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA256
ECDHE-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA256
ECDHE-RSA-AES128-SHA    SSLv3 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA1
ECDHE-ECDSA-AES128-SHA  SSLv3 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA1
DH-DSS-AES128-GCM-SHA256 TLSv1.2 Kx=DH/DSS   Au=DH   Enc=AESGCM(128) Mac=AEAD
DHE-DSS-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=DSS  Enc=AESGCM(128) Mac=AEAD
DH-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA256
DHE-DSS-AES128-SHA256   TLSv1.2 Kx=DH       Au=DSS  Enc=AES(128)  Mac=SHA256
DH-RSA-AES128-SHA256    TLSv1.2 Kx=DH/RSA   Au=DH   Enc=AES(128)  Mac=SHA256
DH-DSS-AES128-SHA256    TLSv1.2 Kx=DH/DSS   Au=DH   Enc=AES(128)  Mac=SHA256
DHE-RSA-AES128-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA1
DHE-DSS-AES128-SHA      SSLv3 Kx=DH       Au=DSS  Enc=AES(128)  Mac=SHA1
DH-RSA-AES128-SHA       SSLv3 Kx=DH/RSA   Au=DH   Enc=AES(128)  Mac=SHA1
DH-DSS-AES128-SHA       SSLv3 Kx=DH/DSS   Au=DH   Enc=AES(128)  Mac=SHA1
DHE-RSA-CAMELLIA128-SHA SSLv3 Kx=DH       Au=RSA  Enc=Camellia(128) Mac=SHA1
DHE-DSS-CAMELLIA128-SHA SSLv3 Kx=DH       Au=DSS  Enc=Camellia(128) Mac=SHA1
DH-RSA-CAMELLIA128-SHA  SSLv3 Kx=DH/RSA   Au=DH   Enc=Camellia(128) Mac=SHA1
DH-DSS-CAMELLIA128-SHA  SSLv3 Kx=DH/DSS   Au=DH   Enc=Camellia(128) Mac=SHA1
AECDH-AES128-SHA        SSLv3 Kx=ECDH     Au=None Enc=AES(128)  Mac=SHA1
ADH-AES128-GCM-SHA256   TLSv1.2 Kx=DH       Au=None Enc=AESGCM(128) Mac=AEAD
ADH-AES128-SHA256       TLSv1.2 Kx=DH       Au=None Enc=AES(128)  Mac=SHA256
ADH-AES128-SHA          SSLv3 Kx=DH       Au=None Enc=AES(128)  Mac=SHA1
ADH-CAMELLIA128-SHA     SSLv3 Kx=DH       Au=None Enc=Camellia(128) Mac=SHA1
ECDH-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH/RSA Au=ECDH Enc=AESGCM(128) Mac=AEAD
ECDH-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AESGCM(128) Mac=AEAD
ECDH-RSA-AES128-SHA256  TLSv1.2 Kx=ECDH/RSA Au=ECDH Enc=AES(128)  Mac=SHA256
ECDH-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AES(128)  Mac=SHA256
ECDH-RSA-AES128-SHA     SSLv3 Kx=ECDH/RSA Au=ECDH Enc=AES(128)  Mac=SHA1
ECDH-ECDSA-AES128-SHA   SSLv3 Kx=ECDH/ECDSA Au=ECDH Enc=AES(128)  Mac=SHA1
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
CAMELLIA128-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(128) Mac=SHA1

**Comment by MikeY2018** [comment]
I have a theory and need SSL Lab to confirm. My theory is that Qualys could be using "nmap" to determine the cipher suites on the target server. It appears that the results on the target server with "nmap --script ssl-cert,ssl-enum-ciphers -p 443,465,993,995 127.0.0.1" yielded very similar results Qualys reported against the target server. 

Here are the partial results on "nmap --script ssl-cert,ssl-enum-ciphers -p 443,465,993,995 127.0.0.1"
...
| ssl-enum-ciphers: 
|   TLSv1.1
|     Ciphers (19)
|       TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA
|       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA
|       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA
|       TLS_DHE_RSA_WITH_SEED_CBC_SHA
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA
|       TLS_RSA_WITH_AES_128_CBC_SHA
|       TLS_RSA_WITH_AES_256_CBC_SHA
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA
|       TLS_RSA_WITH_IDEA_CBC_SHA
|       TLS_RSA_WITH_RC4_128_MD5
|       TLS_RSA_WITH_RC4_128_SHA
|       TLS_RSA_WITH_SEED_CBC_SHA
|     Compressors (1)
|       uncompressed
|   TLSv1.2
|     Ciphers (31)
|       TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
|       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA
|       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA
|       TLS_DHE_RSA_WITH_SEED_CBC_SHA
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA
|       TLS_RSA_WITH_AES_128_CBC_SHA
|       TLS_RSA_WITH_AES_128_CBC_SHA256
|       TLS_RSA_WITH_AES_128_GCM_SHA256
|       TLS_RSA_WITH_AES_256_CBC_SHA
|       TLS_RSA_WITH_AES_256_CBC_SHA256
|       TLS_RSA_WITH_AES_256_GCM_SHA384
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA
|       TLS_RSA_WITH_IDEA_CBC_SHA
|       TLS_RSA_WITH_RC4_128_MD5
|       TLS_RSA_WITH_RC4_128_SHA
|       TLS_RSA_WITH_SEED_CBC_SHA
|     Compressors (1)
|_      uncompressed
...

**Comment by mattcaswell** [comment]
It's clear from the above output that there are no RC4 ciphersuites in that list (for example) whereas the qualys output has them. There is no way that an openssl instance with that output from `openssl ciphers` can offer an RC4 ciphersuite. This implies one of the following is happening:

1) Qualys is at fault. This seems quite unlikely.

2) There is some intermediate proxy that is terminating the TLS connection with Qualys that has different settings to your server.

3) Your server is using a different OpenSSL instance to the one that you have compiled and are using on the command line.

My guess is 3. This would also explain why your script doesn't identify the weak ciphersuites. Your script uses the local OpenSSL instance which has all those weak ciphersuites disabled - so it never attempts to connect to your local server using those ciphersuites.

You might try running your script again, but hitting your server from a different machine with vanilla OpenSSL (i.e. with all the normal ciphersuites compiled in). If that shows up ciphersuites that your local test didn't find then that proves your server is using a different instance of OpenSSL to the one that you have compiled.

**Comment by MikeY2018** [comment]
Thanks. The issue is now resolved. Qualys depends on the Apache/Httpd or similar layer to conduct tests. For those who share similar issues here, check your Apache/Httpd virtual host configurations as not to override your base configuration. Inherit from the base and when and is necessary tweak that in each of your virtual  host configuration. For ciphers, just inherit from base.
