### ISSUE TITLE
Confusing documentation surrounding cipherstring and TLS 1.3 in blog post

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#5777]
After merge of #5392 the official [blog post](https://www.openssl.org/blog/blog/2018/02/08/tlsv1.3/) about TLS v1.3 contains deprecated information, in particular it says that use of cipherstring like `ECDHE:!COMPLEMENTOFDEFAULT` will make it incompatible with TLS 1.3.

This is not the case as now (e6e9170) as both for `s_client` and other callers, use of `-cipher` or [`SSL_set_cipher_list`](https://www.openssl.org/docs/manmaster/man3/SSL_set_cipher_list.html) will not affect TLS 1.3 configuration

**Comment by mattcaswell** [comment]
Question to @openssl. How should we handle this? Create a new blog post describing the new way to configure cipherstrings? We could then update the old post with a reference to the new one? Or should we edit the old post to remove the out-of-date info - but last time I tried that people complained :-).

**Comment by tomato42** [comment]
well, the quoted blog post is already an update to a previous one published last year, so adding link from the old to the new one, with up-to-date information would be expected and consistent :)

**Comment by mattcaswell** [comment]
Should it be a "here's whats changed since the last post" blog, or should it be a repost of the original blog, but updated?

**Comment by richsalz** [comment]
do both: update the original and put a Note at the beginning.

**Comment by kroeckx** [comment]
We've moved this to the wiki. Can this be closed?

**Comment by tomato42** [comment]
Sorry, forgot about this bug. Yes, the [wiki](https://wiki.openssl.org/index.php/TLS1.3) is good. Thanks!
