### ISSUE TITLE
Double definitions SIXTY_FOUR_BIT/THIRTY_TWO_BIT

### ISSUE THREAD

**Issue by DarovskikhAndrei** [openssl/openssl#5784]
openssl_1_1_0-stable
opensslconf.h and bn_conf.h are generated, when I configure and make openssl. Both files have defines like this:
#define SIXTY_FOUR_BIT_LONG
#undef SIXTY_FOUR_BIT
#undef THIRTY_TWO_BIT
And this defines are include if not defined OPENSSL_SYS_UEFI (crypto/bn/look bn_lcl.h and opensslconf.h).
It is required duplicate or bug? Why is it require?

**Comment by levitte** [comment]
We *wish* to move them away from `opensslconf.h`...  However, if you look at `include/openssl/bn.h`, they are used there to determine how `BN_ULONG` should be defined, and `BN_ULONG` is used in the public API.

That means that unfortunately, we cannot remove those definitions from `opensslconf.h`, at least yet.  OpenSSL 1.2 is our next chance to refactor the BN API, if that's enough of a priority.
