### ISSUE TITLE
SSL_do_handshake() failed (SSL: error:14160100:SSL routines:read_state_machine:missing fatal) while SSL handshaking

### ISSUE THREAD

**Issue by cjhust** [openssl/openssl#5786]
openssl-1.1.1-pre2

online error logs:
SSL_do_handshake() failed (SSL: error:14160100:SSL routines:read_state_machine:missing fatal) while SSL handshaking

**Comment by mattcaswell** [comment]
This indicates that a fatal error occurred while reading a handshake message but for some reason we have failed to log the fatal error properly. We've detected it further up the stack, so this error message tells us that we have hit a fatal condition but details about what that fatal error was are missing! So, first we need to figure out what the real fatal error is and why it failed to log the error properly.

Are you able to tell us anymore about the circumstances behind this? Can you reproduce the problem? You say this was in online error logs. Was this an isolated incident, or do you see many of these?

**Comment by cjhust** [comment]
there are serveral services on our system, and this error log appears only occasionally, so I can't see many of there.

**Comment by mattcaswell** [comment]
Hmm, without further information it's going to be very difficult to track down. I'm going to leave this issue open for now to see if more information comes to light, or if other people encounter the same issue.

**Comment by kroeckx** [comment]
I'm wondering if it's related to the other issue you reported: #5787

**Comment by cjhust** [comment]
today we catch the pcap of the client.
the client's version is SSL v2.0.

**Comment by cjhust** [comment]
![image](https://user-images.githubusercontent.com/7733629/38654418-cf43b5fa-3e41-11e8-866b-6193e076371c.png)

**Comment by cjhust** [comment]
#openssl s_client -connect 123.132.254.136:443 -ssl3 -cipher RC4-MD5

can reproduce

**Comment by mattcaswell** [comment]
That is an SSLv2 backwards compat ClientHello. It is actually declaring support for SSLv3, but is wrapping it up in an SSLv2 ClientHello. I'm still not able to reproduce this locally. Hitting your server using the above s_client command does indeed come back with an internal error alert - but I really need to figure out what is happening on the server side. When I try sending a backwards compat ClientHello like the one you captured to a default 1.1.1 s_server instance it does fail. But if fails for the "right" reasons and gives a sensible error message (version too low). That's because a default instance will not talk SSLv3.

Are you still using 1.1.1-pre2 or have you upgraded?

Can you tell me how you configured OpenSSL when you built it? Or even better post the output from running the following in the location where you built OpenSSL:
````
 $ perl configdata.pm --dump
````

Also, how have you configured the running OpenSSL instance, e.g. any protocol versions enable/disabled, ciphersuites configured, etc

**Comment by mattcaswell** [comment]
@cjhust any response to my questions above?

**Comment by mattcaswell** [comment]
Ping @cjhust.

**Comment by mattcaswell** [comment]
No response from OP so closing.

**Comment by zhuxiaochu** [comment]
I encounter the same issue.After i analyze the access.log,I find that happened when someone(maybe a bot) send strings like 'V\x00\xEA\x00V\x00(\x00\xEB\x00!\x00Y\x00{\x00\xCC\x00\xA5\x00Y\x00\xEA\x00\xEB\x00\x06\x00\xCC\x00!\x00Y\x00z\x00\xEA\x00\xA5\x00|\x00\xEA\x00\xB0\x00\x06\x00\xA5\x00\xEB\x00!\x00V\x00\xE9\x005\x00\x06\x005\x00z\x005\x005\x00\xE9\x00\xCC\x00W\x00W\x00(\x00\x06\x00(\x00\x06\x00Y\x00\xEA\x00|\x00z\x00(\x00\xE9\x00!\x00\xCC\x00Y\x00{\x00\x06\x00\xA5\x00{\x00W\x00z\x00\xEB\x00Y\x00(\x00W\x00\xB0\x00\xCC\x00\xEA\x00\xEB\x005\x00\xEA\x00\xB0\x00W\x00!\x00\xCC\x00W\x00!\x00{\x00W\x005.....400',then the server will get the above error.this is all what i know now.

**Comment by esalesplatform** [comment]
> I encountered the same issue.After i analyze the access.log,I find that happened when someone(maybe a bot) send strings like 'V\x00\xEA\x00V\x00(\x00\xEB\x00!\x00Y\x00{\x00\xCC\x00\xA5\x00Y\x00\xEA\x00\xEB\x00\x06\x00\xCC\x00!\x00Y\x00z\x00\xEA\x00\xA5\x00|\x00\xEA\x00\xB0\x00\x06\x00\xA5\x00\xEB\x00!\x00V\x00\xE9\x005\x00\x06\x005\x00z\x005\x005\x00\xE9\x00\xCC\x00W\x00W\x00(\x00\x06\x00(\x00\x06\x00Y\x00\xEA\x00|\x00z\x00(\x00\xE9\x00!\x00\xCC\x00Y\x00{\x00\x06\x00\xA5\x00{\x00W\x00z\x00\xEB\x00Y\x00(\x00W\x00\xB0\x00\xCC\x00\xEA\x00\xEB\x005\x00\xEA\x00\xB0\x00W\x00!\x00\xCC\x00W\x00!\x00{\x00W\x005.....400',then the server will get the above error.And i think he may omit some information,just like[https://serverfault.com/questions/905011/nginx-ssl-do-handshake-failed-ssl-error1417d18cssl](url)



> I encountered the same issue.After i analyze the access.log,I find that happened when someone(maybe a bot) send strings like 'V\x00\xEA\x00V\x00(\x00\xEB\x00!\x00Y\x00{\x00\xCC\x00\xA5\x00Y\x00\xEA\x00\xEB\x00\x06\x00\xCC\x00!\x00Y\x00z\x00\xEA\x00\xA5\x00|\x00\xEA\x00\xB0\x00\x06\x00\xA5\x00\xEB\x00!\x00V\x00\xE9\x005\x00\x06\x005\x00z\x005\x005\x00\xE9\x00\xCC\x00W\x00W\x00(\x00\x06\x00(\x00\x06\x00Y\x00\xEA\x00|\x00z\x00(\x00\xE9\x00!\x00\xCC\x00Y\x00{\x00\x06\x00\xA5\x00{\x00W\x00z\x00\xEB\x00Y\x00(\x00W\x00\xB0\x00\xCC\x00\xEA\x00\xEB\x005\x00\xEA\x00\xB0\x00W\x00!\x00\xCC\x00W\x00!\x00{\x00W\x005.....400',then the server will get the above error.And i think he may omit some information,just like[https://serverfault.com/questions/905011/nginx-ssl-do-handshake-failed-ssl-error1417d18cssl](url)

Sorry, how do you solve that issue?
