### ISSUE TITLE
Please provide stable permanent tarball locations

### ISSUE THREAD

**Issue by tp-m** [openssl/openssl#5796]
It would be great if you could provide stable permanent tarball locations on openssl.org.

Currently what happens is that a new release will appear in e.g.

`https://ftp.openssl.org/source/openssl-1.1.0g.tar.gz`

and then once the next one comes out this tarballs moves to e.g.

`https://ftp.openssl.org/source/old/1.1.0/openssl-1.1.0g.tar.gz`

which leads to a 404 at the original location.

This is a problem for meta-build systems that refer to tarballs at their original locations and that need to achieve reproducible builds over time.

There may be a desire to make users upgrade to the latest version as soon as possible, and to signal when a version is no longer the latest, but I don't think tarballs disappearing is the right signaling mechanism here (assuming it's done this way on purpose in the first place, which might not be the case).

It would be great if there was a stable location for tarballs from the moment they are released, or explicit 301 redirects be set up when the tarball is moved so that http clients can automatically follow the link.

Otherwise there's a slightly perverse incentive to always track the latest-but-one release because the URL is only stable once it's moved into the old/ subfolder :)

This could also be solved on the consumer side by mirroring the tarballs elsewhere of course, which is the current solution, but it seems better to refer to the original location and have users retrieve tarballs from there, especially for such an important and security-sensitive module such as openssl.

Thanks for reading, hope this is something that can be sorted in some way.

**Comment by levitte** [comment]
Agreed.  I'm currently looking at an easy .htaccess rule that does 301 redirects for tarballs that aren't present directly in source.  Just a moment...

**Comment by levitte** [comment]
Ok, URL rewrite done.  Please have a look, try it out.

I understand that it doesn't exactly match everything you desire, but I certainly hope it helps...

**Comment by tp-m** [comment]
Perfect, thanks a lot!
```
$ wget https://ftp.openssl.org/source/openssl-1.1.0g.tar.gz
--2018-03-29 13:37:40--  https://ftp.openssl.org/source/openssl-1.1.0g.tar.gz
Resolving ftp.openssl.org (ftp.openssl.org)... 194.97.150.234, 2001:608:c00:180::1:ea
Connecting to ftp.openssl.org (ftp.openssl.org)|194.97.150.234|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ftp.openssl.org/source/old/1.1.0/openssl-1.1.0g.tar.gz [following]
--2018-03-29 13:37:40--  https://ftp.openssl.org/source/old/1.1.0/openssl-1.1.0g.tar.gz
Reusing existing connection to ftp.openssl.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 5404748 (5.2M) [application/x-gzip]
Saving to: ‘openssl-1.1.0g.tar.gz’
```
