### ISSUE TITLE
""error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing"

### ISSUE THREAD

**Issue by vasim-farooqui** [openssl/openssl#5806]
Hi I am facing error while using git fetch

"error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/organisationname/reponame/info/refs?service=git-upload-pack
fatal: HTTP request failed.

After this error updated openssl version from 0.9 to 1.0.1e
Still getting same error.

**Comment by mspncp** [comment]
Hi, the versions 0.9 and 1.0.1 are outdated and not supported anymore. Please upgrade to version 1.0.2, see https://www.openssl.org/source.

**Comment by vasim-farooqui** [comment]
Hi

I have upgrade the openssl version to  OpenSSL 1.0.2a 19 Mar 2015
Still facing the same error.

Regards,
Vasim

**Comment by mattcaswell** [comment]
What platform are you on? How did you do the upgrade? i.e. did you download and build from source, or did you get OpenSSL from your OS vendor repository?

**Comment by vasim-farooqui** [comment]
CentOS release 5.7 (Final)    x86_64   Yes Downloaded the package from below url and build from source.
https://www.openssl.org/source/openssl-1.0.2a.tar.gz

**Comment by mattcaswell** [comment]
Ok. I don't know why you chose 1.0.2a since that is not the most recent 1.0.2 release and has security issues. You should really use 1.0.2o (the most up to date version).

The most likely explanation is that you still have the system version of OpenSSL installed and your git is using that one. If your git command is linked against OpenSSL 0.9.x then you probably need a newer version of that too.

**Comment by vasim-farooqui** [comment]
How do i make git to use to new version of openssl installed.
Is there any way to config that for git

**Comment by kroeckx** [comment]
You really need to recompile it and make sure it uses the correct headers and links to the correct library

**Comment by vasim-farooqui** [comment]
Recompile git or openssl, is there any way where i can re-install git with higher version and keep the existing setting as it is.

**Comment by levitte** [comment]
This is really a question you should ask the git folks...  their [README](https://github.com/git/git/blob/master/README.md) might be helpful.  As for rebuilding git, I suggest you have a look at their [INSTALL](https://github.com/git/git/blob/master/INSTALL), where you will find *nothing* about OpenSSL, but everything about libcurl, which is a HTTP transport library that uses, among others, OpenSSL:

> ```
> - Git is reasonably self-sufficient, but does depend on a few external
>   programs and libraries. ...
> ...
> 	- "libcurl" library is used by git-http-fetch, git-fetch, and, if
> 	  the curl version >= 7.34.0, for git-imap-send.  You might also
> 	  want the "curl" executable for debugging purposes. If you do not
> 	  use http:// or https:// repositories, and do not want to put
> 	  patches into an IMAP mailbox, you do not have to have them
> 	  (use NO_CURL).
> ```

So all in all, you will need to build newer versions of OpenSSL, libcurl and git, at the very least...  and to build git, you will need to make sure that you have installed the development packages for everything else that you want git to use.

For further information specifically about git, I suggest that you talk with the git folks, as they are much better informed than any of us.  The README I pointed at has the contact details.

**Comment by richsalz** [comment]
And now I think this issue can be closed.

**Comment by vasim-farooqui** [comment]
@kroeckx   Yes definitely i need to upgrade git .
Do you happened to know the way to do it in which it does not break the system.

**Comment by kjr247** [comment]
@vasim-farooqui 
https://gitforwindows.org/
download here.

**Comment by JulienDesurmont** [comment]
Hello.
I've faced the same issue : 

Use this command to pull / fetch :  **git remote add origin git@github.com:*********.git**

instead of git remote add origin https://github.com/*********.git
