### ISSUE TITLE
issue with named curve X25519 in openssl 1.0.2

### ISSUE THREAD

**Issue by rkumarsahu** [openssl/openssl#5807]
I am using ECDHE and trying to generate a EC_KEY using the named curve x25519 (29). All the API succeeds. But finally when I am using EC_POINT_point2oct() api to convert the key, it returns a 35 bytes key. I am expecting a 32 bytes key for the named curve 29. Is there a known issue with openssl 1.0.2 for the named curve 29.

**Comment by richsalz** [comment]
I don't know what the code is doing, but 1.0.2 does not support 25519.  Are you sure you are using that version?

**Comment by mattcaswell** [comment]
I'm not sure what you've done but you are mixing up various different things:

1) OpenSSL 1.0.2 does not support X25519 at all. You need to use OpenSSL1.1.0 for that.

2) The curve is 25519. The algorithm is X25519 (which works much like standard ECDH). In its implementation it is quite different to all of the other OpenSSL curves. You cannot create an EC_KEY for it even in OpenSSL1.1.0. You must use the EVP routines to work with it. The primitive functions are not exposed via the API.

3) X25519 has the number 29 in the *TLS* Supported Groups registry (https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8). This is TLS specific and libcrypto EC* functions know nothing about it.

**Comment by rkumarsahu** [comment]
Thanks a lot @richsalz  and @mattcaswell for responding to my query. I am using openssl 1.0.2.
@mattcaswell  Yes, I mixed different things. I am generating a key pair which can support named curve 29. So I used the following APIs.

EC_KEY *eckey = EC_KEY_new_by_curve_name(nid);
EC_KEY_generate_key(ec_key);
EVP_PKEY *evpkey = EVP_PKEY_new();
EVP_PKEY_assign_EC_KEY(evpkey, eckey);

To serialize the key, I am using the EC_POINT_point2oct() API. This generally works for other named curves but specifically has problem with curve 29 (25519). Like you said, this is probably because the openssl 1.0.2 doesn't have support for curve 25519. 

I want to upgrade the openssl but there is no new openssl version which is declared as LTS yet post 1.0.2. 
So I am little hesitant to upgrade as of now.

**Comment by richsalz** [comment]
Okay, you know that 1.0.2 does not support Curve 25519, and you can't upgrade.  Closing this issue.

**Comment by mattcaswell** [comment]
> To serialize the key, I am using the EC_POINT_point2oct() API. This generally works for other named curves but specifically has problem with curve 29 (25519). Like you said, this is probably because the openssl 1.0.2 doesn't have support for curve 25519.

Even if you had an OpenSSL version with 25519 support you couldn't do it this way anyway. Curve 25519 works entirely differently internally to all the other EC stuff. You can't use any of the EC_* functions on it. You can only use EVP_* functions.

**Comment by rkumarsahu** [comment]
@mattcaswell  Thanks a lot. That really helps.
