### ISSUE TITLE
Cannot use the GOST engine in s_client/s_server

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#5809]
When OPENSSL_init_ssl() is called it does some initialisation of the ciphersuites. It scans the list of ciphersuites and removes any from the list that are disabled. In the apps this happens *before* any engine is loaded so when it scans the list is sees that it doesn't have any GOST support and disables the ciphersuites. Later the engine gets loaded but by then it is too late - the ciphersuites are already disabled.

I seem to recall some years ago this happened and we fixed it so that if you had an engine configured in your config file it would be loaded first. However this doesn't seem to work any more. It seems to be broken in 1.1.0 too.

**Comment by mattcaswell** [comment]
Ping @beldmit for any further thoughts.

**Comment by mattcaswell** [comment]
This issue seems to have been recently (re)introduced by commit 0a90a6831e.

Ping @levitte for your thoughts.

**Comment by levitte** [comment]
My thoughts? Well, I suspected that the commit you refer to could come bite us back, just couldn't see how. So it seems that we have a bit of a catch 22 to deal with... I don't have any bright ideas for the moment, but will get back when I do (unless someone already has).

**Comment by mattcaswell** [comment]
So from the commit message to that commit we see:

>IF OPENSSL_init_ssl() is called with the option flag
OPENSSL_INIT_LOAD_CONFIG, any SSL config will be handled wrongly
(i.e. there will be an attempt to load libssl_conf.so or whatever
corresponds to that on non-Unix platforms).  Therefore, at least
SSL_add_ssl_module() MUST be called before OPENSSL_init_crypto() is
called.  The base ssl init does that, plus adds all kinds of ciphers
and digests, which is harmless.

I immediately wonder what happens if you have a system wide config file with SSL stuff in it - but you app is only doing crypto stuff so OPENSSL_init_ssl() never gets called? Or am I misunderstanding the problem?

Or another scenario what about if your app does both crypto and ssl stuff, but does the crypto stuff first? OPENSSL_init_crypto() will happen first no matter what.

**Comment by beldmit** [comment]
I can confirm that when I was providing the GOST TLS support in OpenSSL 1.1.0, there were some issues related to order of loading engines and availability of options such as algorithm names in cmdline applications etc. But AFAIR there were no problems in s_client/s_server at that moment.

**Comment by vpodobaev** [comment]
@mattcaswell Thank you very much!
