### ISSUE TITLE
no-dgram is broken

### ISSUE THREAD

**Issue by benlaurie** [openssl/openssl#581]
```
$ ./config no-dgram --strict-warnings
```

Results in...

```
$ make test
...
../test/recipes/80-test_ssl.t ............. 11/44     # Child (DTLS Version min/max tests) exited without calling finalize()
    
    #   Failed test 'DTLS Version min/max tests'
    #   at /usr/local/lib/perl5/site_perl/Test/More.pm line 1314.
    # Looks like you planned 1 test but ran 2.
    # Looks like you failed 1 test of 2 run.
```

**Comment by nicepat** [comment]
no longer reproduce the issue with commit #1ffa8a9685e22a5a0ff1b1322df4d1720b05ce4c 

user@ubuntu:~/Downloads/openssl$ uname -a
Linux ubuntu 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

please see result from my system.
../test/recipes/80-test_dane.t ............ ok
../test/recipes/80-test_dtlsv1listen.t .... ok
../test/recipes/80-test_ocsp.t ............ ok
../test/recipes/80-test_ssl.t ............. ok
../test/recipes/80-test_tsa.t ............. ok
../test/recipes/90-test_async.t ........... ok
../test/recipes/90-test_constant_time.t ... ok
../test/recipes/90-test_gmdiff.t .......... ok

**Comment by richsalz** [comment]
thanks!
