### ISSUE TITLE
Config is not loaded by default

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#5820]
As part of #4848, I was expecting the default config to be loaded all the time. But it seems this is not the case. The apps call OPENSSL_init_ssl() with OPENSSL_INIT_LOAD_CONFIG (which isn't documented), it's documented for OPENSSL_init_crypto(). There it's documented that it's not the default. Why is this not the default? Just for backwards compatibility?

**Comment by mattcaswell** [comment]
It is documented for OPENSSL_init_ssl():

````
The B<opts> parameter specifies which aspects of libssl and libcrypto should be
initialised. Valid options for libcrypto are described on the
L<OPENSSL_init_crypto(3)> page. In addition to any libcrypto
specific option the following libssl options can also be used:
````

So all OPENSSL_init_crypto() options also apply to OPENSSL_init_ssl().

I believe it isn't the default for backwards compatibility. Co-incidentally I made it the default for libssl as part of #5818 (although I hadn't thought about the backwards compatibility concern). But #4848 does imply that we should be doing it by default anyway.

**Comment by bernd-edlinger** [comment]
Note, unless I am mistaken, the environment variable OPENSSL_CONF can be used to change the
system configuration to pretty much anything, including code-execution in every application that does
not opt-out.

**Comment by mattcaswell** [comment]
> Note, unless I am mistaken, the environment variable OPENSSL_CONF can be used to change the
system configuration to pretty much anything, including code-execution in every application that does
not opt-out.

Only if an application actually loads config.

**Comment by bernd-edlinger** [comment]
> Only if an application actually loads config.

Yes, but that is what will happen automatically in future.
I wonder if that environment lookup should be configurable.

**Comment by mattcaswell** [comment]
> Yes, but that is what will happen automatically in future.
I wonder if that environment lookup should be configurable.

It doesn't automatically happen at the moment. If #5818 gets merged then it will.

**Comment by mattcaswell** [comment]
(at least it will for libssl applications).

**Comment by mattcaswell** [comment]
This should be fixed now.
