### ISSUE TITLE
WIN64: 'Command-line error: invalid macro definition: "LIBZ=\"ZLIB1\""' error for shared builds using ICC

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#5827]
Hello, everyone,

For OpenSSL builds using ICC got error:
```
set CC=icl

perl Configure zlib-dynamic --with-zlib-include="%CD%\..\..\libZLIB-1.2.11\ICC64RH\include" shared VC-WIN64A && nmake

<snip>

        icl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "." /I "include" "-D\"LIBZ=\\\"ZLIB1\\\"\"" "-DL_ENDIAN" "-DOPENSSL_PIC" "-DOPENSSL_CPUID_OBJ" "-DOPENSSL_IA32_SSE2" "-DOPENSSL_BN_ASM_MONT" "-DOPENSSL_BN_ASM_MONT5" "-DOPENSSL_BN_ASM_GF2m" "-DSHA1_ASM" "-DSHA256_ASM" "-DSHA512_ASM" "-DRC4_ASM" "-DMD5_ASM" "-DAES_ASM" "-DVPAES_ASM" "-DBSAES_ASM" "-DGHASH_ASM" "-DECP_NISTZ256_ASM" "-DX25519_ASM" "-DPADLOCK_ASM" "-DPOLY1305_ASM" "-DOPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" "-DENGINESDIR=\"C:\\Program Files\\OpenSSL\\lib\\engines-1_1\"" "-DZLIB" "-DZLIB_SHARED" "-DOPENSSL_SYS_WIN32" "-DWIN32_LEAN_AND_MEAN" "-DUNICODE" "-D_UNICODE" "-D_CRT_SECURE_NO_DEPRECATE" "-D_WINSOCK_DEPRECATED_NO_WARNINGS" "-DOPENSSL_USE_APPLINK" "-DNDEBUG" "-Ic:\\libOPENSSL-1.1.1-dev\\build\\..\\..\\libZLIB-1.2.11\\ICC64RH\\include"  /Zs /showIncludes "apps\app_rand.c" 2>&1 > apps\app_rand.d
NMAKE : fatal error U1077: 'icl' : return code '0x4'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

<snip>

nmake

<snip>

        icl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "." /I "include" "-D\"LIBZ=\\\"ZLIB1\\\"\"" "-DL_ENDIAN" "-DOPENSSL_PIC" "-DOPENSSL_CPUID_OBJ" "-DOPENSSL_IA32_SSE2" "-DOPENSSL_BN_ASM_MONT" "-DOPENSSL_BN_ASM_MONT5" "-DOPENSSL_BN_ASM_GF2m" "-DSHA1_ASM" "-DSHA256_ASM" "-DSHA512_ASM" "-DRC4_ASM" "-DMD5_ASM" "-DAES_ASM" "-DVPAES_ASM" "-DBSAES_ASM" "-DGHASH_ASM" "-DECP_NISTZ256_ASM" "-DX25519_ASM" "-DPADLOCK_ASM" "-DPOLY1305_ASM" "-DOPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" "-DENGINESDIR=\"C:\\Program Files\\OpenSSL\\lib\\engines-1_1\"" "-DZLIB" "-DZLIB_SHARED" "-DOPENSSL_SYS_WIN32" "-DWIN32_LEAN_AND_MEAN" "-DUNICODE" "-D_UNICODE" "-D_CRT_SECURE_NO_DEPRECATE" "-D_WINSOCK_DEPRECATED_NO_WARNINGS" "-DOPENSSL_USE_APPLINK" "-DNDEBUG" "-Ic:\\libOPENSSL-1.1.1-dev\\build\\..\\..\\libZLIB-1.2.11\\ICC64RH\\include"  -c /Foapps\app_rand.obj "apps\app_rand.c"
app_rand.c
Command-line error: invalid macro definition: "LIBZ=\"ZLIB1\""

compilation aborted for apps\app_rand.c (code 4)
NMAKE : fatal error U1077: '"C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\bin\intel64\icl.EXE"' : return code '0x4'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```
which reproduced after commit abe256e7951e6d57f8f6b4364ea696eb4ead3852.

Reproduced for:
* builds using ICC with Shared layout and `zlib-dynamic` flag,

not reproduced for:
* builds using ICC with Static layout,
* builds using mingw-w64 and MSVC with Shared layout.

Environment:
* Windows 10 x64,
* mingw-w64 x86_64 7.3.0,
* ICC 2018 Update 2,
* MSVC 2017 15.5.0,
* Windows SDK 10.0.16299.15,
* MSYS2 20170918,
* OpenSSL-1.1.1-dev (803cc8c7d4fce5ba8a4b843e0d778983d5b75c9e).

CC: @levitte

Best,

Alexander

**Comment by richsalz** [comment]
I don't believe ICC is a supported compiler.

**Comment by sav-ix** [comment]
Yes and no. The last discussion on this stopped [here](https://github.com/openssl/openssl/issues/1150#issuecomment-372040613).

**Comment by levitte** [comment]
Doesn't matter, @richsalz, that macro definition is malformed either way.

**Comment by bernd-edlinger** [comment]
Can someone explain to me why does everybody configure with zlib-dynamic when there
is a CRIME attack?

**Comment by sav-ix** [comment]
Presumably because it's a *legal* OpenSSL build flag.

So the question rather is, why `zlib-dynamic` flag allowed, when it leads to security flaws?

**Comment by richsalz** [comment]
Many things lead to security flaws that are still allowed.  And I don't see what's wrong with the macro. And the discussion did tail off, which means the default is still *not supported.*

**Comment by levitte** [comment]
@richsalz, `"-D\"LIBZ=\\\"ZLIB1\\\"\""` tries to tell the compiler to define the macro `"LIBZ=\"ZLIB1\""` (all quotes included), not the macro `LIBZ` with the value `"ZLIB1"`.  That *is* wrong, whether we're talking CL or ICC.  The troublesome thing is that CL lets this pass silently (I just tested), while ICC complains (rightfully).

In other words, even though ICC detected the issue, *this is not an ICC issue*, it's an issue in our makefile template for Windows.

**Comment by levitte** [comment]
@sav-ix, please try #5833

**Comment by sav-ix** [comment]
Applied Change 21eab2dcba0e55dd109364266bd0fea9c2cb21a6 to OpenSSL-1.1.1-dev (803cc8c7d4fce5ba8a4b843e0d778983d5b75c9e) sources, and for builds using Windows ICC with `<Debug|Release> Shared` configurations error not reproduced. Also made sure, that it doesn't break shared MSVC builds.
Thank you for [a quick] fix!

**Comment by richsalz** [comment]
Thanks for the explanation.
