### ISSUE TITLE
How to actually use EVP to do ED25519

### ISSUE THREAD

**Issue by PH0lder** [openssl/openssl#5835]
I am attempting to use ED25519.  I found this page
https://www.openssl.org/docs/manmaster/man7/Ed25519.html
which mentions EVP_PKEY_ED25519 which does not appear in my copy of the openssl source that I downloaded earlier this evening.

I did ./config followed by make and it built without any errors.  I am looking at the evp.h file in the include/openssl directory.  Searching for 25519 gets no hits. The openssl app reports:  OpenSSL 1.1.0h-fips  27 Mar 2018

In particular, I want to write code to generate a random private key and then derive the corresponding public key, if someone can point me at a working example I'd be very appreciative.

**Comment by bernd-edlinger** [comment]
Only X25519 is supported in 1.1.0
For Ed25519 you need the 1.1.1 version

**Comment by richsalz** [comment]
No, X25519 is not supported in 1.1.0 EVP.
Closing this issue.

**Comment by PH0lder** [comment]
I wanted to suggest that it would be wise to add a section to the docs (such as the one I linked above) that says "since {version}" so that when encountering something you think you could use, you'd know what version of the library is required.

**Comment by bernd-edlinger** [comment]
Rich, at least this command does work with 1.1.0 (and it uses EVP intenally):
`openssl genpkey -algorithm X25519 -text`

**Comment by mattcaswell** [comment]
> No, X25519 is not supported in 1.1.0 EVP.

X25519 is supported in 1.1.0 EVP but has some significant limitations. The support is better in 1.1.1. Ed25519 is only supported in 1.1.1.

> If X25519 is supposed to be supported in 1.1.0 in EVP then that still wouldn't explain why there are NO references to 22519 in any constant in the evp.h file... I mean I would expect it to occur in some way in a constant related to X25519?

Actually the only constant you need is `NID_X25519` which is defined in `openssl/obj_mac.h`.

**Comment by richsalz** [comment]
@bernd-edlinger yeah, I confused EVP and EC ... Thanks.
I still think there's no reason to re-open this, but feel free to do so if I'm wrong on that (too).
