### ISSUE TITLE
openssl ocsp responder

### ISSUE THREAD

**Issue by cyberlink1** [openssl/openssl#584]
Was trying to set up an ocsp responder with openssl

It seems that it requires the signing cert to have a password (Which I prefer) but there is no way to daemonize it. I need to make it a daemon that starts at boot for the CA.

Guess my question is, did I miss something or is it something that feature that has not been implemented?

**Comment by richsalz** [comment]
Please ask this question on opensls-users.

**Comment by cyberlink1** [comment]
It was asked on  Nov 10 20:58:08 UTC 2015 and there was no answer.

There is no docs on it, I can run it command line as an ocsp responder but it does not take the pass:password option, the -passin does not work, and there appears to be no way to pipe or direct it a password for the signing key.

**Comment by richsalz** [comment]
So either remove the password or we need to add code to add those flags.

**Comment by cyberlink1** [comment]
If you remove the password it still prompts you for a password and hitting enter gets the following error

Enter pass phrase for /etc/pki/tls/certs/ocsp.key:
140302893254472:error:28069065:lib(40):UI_set_result:result too small:ui_lib.c:869:You must type in 4 to 8191 characters

**Comment by richsalz** [comment]
Plus go to the mailing list.

**Comment by jennymorton** [comment]
@cyberlink1 Hey Todd, did you resolve the issue? :)
