### ISSUE TITLE
`OPENSSL_1_1_1' not found (required by openssl)

### ISSUE THREAD

**Issue by SimonFearby** [openssl/openssl#5845]
Error: 
```
> openssl version
> openssl: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
> openssl: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
```

# I ran the follwoing on Ubuntu 16.04, nginx version: nginx/1.13.9
```
# git clone git://git.openssl.org/openssl.git
# cd openssl/
# ./config --prefix=/usr/
# make
# sudo make install
# openssl version
```

**Comment by mattcaswell** [comment]
Try setting your `LD_LIBRARY_PATH` to point to the location of your newly compiled OpenSSL libs. The above indicates that you are picking up the old system OpenSSL libraries.

**Comment by levitte** [comment]
Do you expect us to start reading your blog to help you out?  Quite the shameless plug there, dude ;-)

**Comment by SimonFearby** [comment]
Sorry, just happy to help others with the same error and solution. I'll delete

**Comment by mattcaswell** [comment]
It should be:
````
$ export LD_LIBRARY_PATH=/usr/local/lib"
````
(assuming you installed OpenSSL to the default location)

**Comment by mattcaswell** [comment]
You might also want to read the NOTES.UNIX file which gives a different way to do this.

**Comment by SimonFearby** [comment]
Thanks, I set  "export LD_LIBRARY_PATH=/usr/local/lib" and it worked a treat
openssl version
OpenSSL 1.1.1-pre3 (beta) 20 Mar 2018

Thanks mattcaswell and levitte

**Comment by SimonFearby** [comment]
All working in production :)

**Comment by Fudoshiki** [comment]
@SimonFearby hello, can u  provide full steps fro install, i have same issue

```
git clone git://git.openssl.org/openssl.git
cd openssl/
./config
make install
openssl version

# openssl: /lib64/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
# openssl: /lib64/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)

export LD_LIBRARY_PATH=/usr/local/lib
openssl version

# openssl: /lib64/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
# openssl: /lib64/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
```

**Comment by mariojar** [comment]
perhaps you can help me, i get the same error when i try  connect to oc cli on ubuntu

oc login
oc: /usr/lib/libcrypto.so.10: version `OPENSSL_1.0.1_EC' not found (required by oc)
oc: /usr/lib/libcrypto.so.10: version `libcrypto.so.10' not found (required by oc)

with: 
openssl version
OpenSSL 1.1.1  11 Sep 2018

which openssl
/usr/bin/openssl

**Comment by kroeckx** [comment]
libcrypto.so.10 and OPENSSL_1.0.1_EC are clearly not things that we made. I have no idea where those files come from, but you should talk to them.

**Comment by levitte** [comment]
I have seen that kind of libcrypto SONAME before... CentOS, right? I assume there is a libcrypto.so.11 somewhere (`ldd $(type -p openssl)` should show that), so you have to upgrade `oc` to a version that uses the newer openssl package.

**Comment by Adtx** [comment]
> perhaps you can help me, i get the same error when i try connect to oc cli on ubuntu
> 
> ```
> oc login
> oc: /usr/lib/libcrypto.so.10: version `OPENSSL_1.0.1_EC' not found (required by oc)
> oc: /usr/lib/libcrypto.so.10: version `libcrypto.so.10' not found (required by oc)
> ```
> with:
> openssl version
> OpenSSL 1.1.1 11 Sep 2018
> 
> which openssl
> /usr/bin/openssl

I have the exact same problem.

**Comment by donizyo** [comment]
This exception occurred to me when I compile OpenSSL 1.1.1b in my Docker image.
As is followed is my solution:
```docker
FROM        base AS openssl
LABEL       image=openssl:1.1.1b

ARG         URL_ZLIB_TARBALL=http://www.zlib.net/zlib-1.2.11.tar.gz
ARG         URL_OPENSSL_TARBALL=https://www.openssl.org/source/openssl-1.1.1b.tar.gz
ENV         ZLIB_PREFIX=/usr/local
ENV         OPENSSL_PREFIX=/usr/local
ARG         OPENSSL_DIR=$OPENSSL_PREFIX/ssl
ARG         LD_LIBRARY_PATH=$OPENSSL_PREFIX/lib

# zlib
RUN         cd "$PATH_APP" && \
            curl -sL "$URL_ZLIB_TARBALL" -o zlib.tar.gz && \
            tar -xf zlib.tar.gz --one-top-level=zlib --strip-components 1
RUN         cd "$PATH_APP/zlib" && \
            ./configure --prefix="$ZLIB_PREFIX" && \
            make && \
            make install
RUN         cd "$PATH_APP/zlib" && \
            make clean && \
            rm -f "$PATH_APP/zlib.tar.gz"
# openssl
RUN         cd "$PATH_APP" && \
            curl -sL "$URL_OPENSSL_TARBALL" -o openssl.tar.gz && \
            tar -xf openssl.tar.gz --one-top-level=openssl --strip-components 1
RUN         cd "$PATH_APP/openssl" && \
            ./config \
                --prefix="$OPENSSL_PREFIX" \
                --openssldir="$OPENSSL_DIR" \
                --api=1.1.0 \
                --strict-warnings \
                zlib-dynamic && \
            make && \
            make test && \
            make install && \
            echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> /etc/environment
RUN         cd "$PATH_APP/openssl" && \
            make clean && \
            rm -f "$PATH_APP/openssl.tar.gz"
# openssl test
RUN         openssl version
```

**Comment by gyzdmgqy** [comment]
I have the same issue. In my case (Ubuntu 18.04), even after successful install of openssl (tried various version), it still does not work. I studied this thread as well as many others online and resolve the issue as follows:
1) `sudo apt-get install locate` (to install the locate to find where exactly libssl.so.1.1 is.)
2)` locate libssl.so.1.1 `
3) figure out in the listed location /usr/lib/x86_64-linux-gnu/libssl.so.1.1 is the right one. (it varies cross different platforms)
4) `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu`
Then when execute openssl version, it should work now.
5) if it works in step 4), you can add `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu` to `~/.bashrc` to enable a permanent solution, otherwise you need to execute step 4) every time restarts.

**Comment by kroeckx** [comment]
That should already be in your default library search directory.
If that fixes it for you, it seems that you actually try to load
an other by default. ldd `which openssl` should tell you which
it's tring to load.

**Comment by jaum20** [comment]
> 2\. execute `locate libssl.so.1.1` and it gives the following:

`locate` didn't worked for me. I had to use `whereis` to find the location

**Comment by vladyslav2** [comment]
Fixed for Kali, I had to update `/etc/apt/sources.d/zerotier.list` from buster to bookworm and it helped
```
deb http://download.zerotier.com/debian/bookworm bookworm main
```
