### ISSUE TITLE
rand_pool_add(): double meaning of returned 0

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#5846]
rand_pool_add() returns 0 in the following cases:

1.  If there's an error, i.e. too much data is added for the given pool.
2.  If there isn't enough entropy.

In case 1, one should stop feeding more data (as it answers the question "was it ok to feed you with this butt-load?"), but in case 2, one should try to add more (as it answers the question "should I feed you another spoon-full?").  But from the returned zero, it's obviously quite hard to know what to do.

The solution for the caller is to call rand_pool_entropy_available() before calling rand_pool_add().

rand_pool_add() shouldn't try to answer two different things with the same value.

**Comment by mspncp** [comment]
Sounds reasonable. Was there a specific cause that led you to raise this issue?

**Comment by mspncp** [comment]
> rand_pool_add() shouldn't try to answer two different things with the same value.

 It could also make the errors distinguishable by pushing different error values...

**Comment by levitte** [comment]
Yup.  rand_vms.c needed fixing, and I'm feeding the pool smaller bits of data at a time with rand_pool_add(), and it gives me zero back.  That's a perfectly useless answer, but rand_pool_entropy_available() will at least tell me if I should feed it yet another spoonful.

**Comment by levitte** [comment]
I would say that the simplest fix would be to have rand_pool_add return a boolean, i.e. only try to answer case 1, and force the caller to use rand_pool_entropy_available() to check the state of the pool.

**Comment by mspncp** [comment]
I will have a look at it when I‘m back home.

**Comment by mspncp** [comment]
Have you also seen rand_pool_entropy_required()?

**Comment by levitte** [comment]
Uhmmmm, according to my `git grep`, it doesn't exist...

**Comment by mspncp** [comment]
The name is from memory, I‘m sitting here with my mobile only. I‘ll have to look it up later...

**Comment by mspncp** [comment]
/*
 * Returns the (remaining) amount of entropy needed to fill
 * the random pool.
 */

size_t rand_pool_entropy_needed(RAND_POOL *pool)

**Comment by mspncp** [comment]
Sorry, I meant 

/*
 * Returns the number of bytes needed to fill the pool, assuming
 * the input has 'entropy_per_byte' entropy bits per byte.
 * In case of an error, 0 is returned.
 */

size_t rand_pool_bytes_needed(RAND_POOL *pool, unsigned int entropy_per_byte)
{
