### ISSUE TITLE
Please add the ability to export raw private/public keys via the EVP interface

### ISSUE THREAD

**Issue by kareldonk** [openssl/openssl#5848]
Pull request #5520 added the ability to import raw key data into OpenSSL via the EVP interface. It would be nice to also have a set of functions to export raw key data out of OpenSSL via the EVP interface.
And if possible a generalized set of functions that can be used on any supported key by EVP_PKEY (so not just X25519/X448/Ed25519/X25519).

The last few days I've been struggling to find an easy way to get binary raw key data out of OpenSSL instead of exporting PEMs. The raw bytes make it easier to transfer over the wire with less overhead (no Base64 encoding and PEM headers etc.).

**Comment by pieterlexis** [comment]
Yes please! We'd like to have an alternative implementation next to libsodium and libdecaf for ed25519 and ed448 in [PowerDNS](https://github.com/PowerDNS/pdns)

**Comment by mattcaswell** [comment]
I definitely want to do this, but it won't be in the upcoming 1.1.1 release unfortunately because we already passed feature freeze.

> And if possible a generalized set of functions that can be used on any supported key by EVP_PKEY (so not just X25519/X448/Ed25519/X25519).

This is a bit more difficult. For those algorithms and some others the "key" is just a blob of binary data. For others the key is structured so it is unclear what a "raw" key means in that case.

**Comment by kareldonk** [comment]
@mattcaswell The next release would also be nice. Even if we could just get a blob of binary data out, that would already be helpful. As long as we can pass in that blob of binary data again to read back in the key. I haven't looked at the internals behind this in OpenSSL so I don't know if this is possible. I'm just suggesting this based on a few use case scenarios where it would be nice to have. 
Perhaps if what you're making could be some kind of generalized interface, it could be implemented as well for future algorithms if not for the older ones.

**Comment by pieterlexis** [comment]
> @mattcaswell The next release would also be nice. Even if we could just get a blob of binary data out, that would already be helpful. As long as we can pass in that blob of binary data again to read back in the key. I haven't looked at the internals behind this in OpenSSL so I don't know if this is possible. I'm just suggesting this based on a few use case scenarios where it would be nice to have.

From a quick look, I think exposing it as a `BIGNUM` is the way to do this

**Comment by mattcaswell** [comment]
This got implemented and will be in the 1.1.1 release after all. See #6394.

**Comment by kareldonk** [comment]
THANKS!!!
