### ISSUE TITLE
VMS rand_pool_acquire_entropy doesn't deliver enough entropy for DRBG with nonce

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#5849]
Up until commit 2a70d65b99e1f2376be705d18bca88703b7e774a, the required number of bits of entropy was 256.  Now, when a nonce is used, the requirement is 384 bits.

Unfortunately, `crypto/rand/rand_vms.c` delivers 64 bytes, with assumed strength of 4 bits of entropy per byte.  That's 256 bits of entropy, which isn't enough for the new requirements.

I hope the VMS community can help out here.  We obviously need to add more "random" data...

**Comment by richsalz** [comment]
Was it intentional that we added 50% more seed to our requirements list?  I’m not sure that was a good thing to do.

**Comment by mspncp** [comment]
There would also have been a way to obtain a nonce which would have required less entropy. See https://github.com/openssl/openssl/pull/5503#comment-371960392.

**Comment by mspncp** [comment]
This would have been my favorite choice.

**Comment by mspncp** [comment]
> ... would have required less entropy. 

To be more precise: it would have required _no_ extra entropy.

**Comment by levitte** [comment]
Also related but not quite the same level of failure; if you configure with DEVRANDOM = "/dev/random", and then exhaust /dev/random (a simple `od -c /dev/random` until you see it slow down), and finally run something like `./util/shlib_wrap.sh test/drbgtest`, you will see it grind to a halt for a bit, most probably after it has output this line:

```
ok 2 - test_error_checks
```

See, `test_rand_reseed` is the next test, and that'll exercise entropy acquisition.

**Comment by levitte** [comment]
(test that on Linux a moment ago)

**Comment by mspncp** [comment]
Well, so it blocks while reading from /dev/random, because you drained it. What is so unusual about that?

**Comment by levitte** [comment]
I was thinking that when you do get a block, it will only output 8 bytes at a time.  That hits the same issue, although not as seriously.

Granted, it was a fairly weak remark.  Feel free to ignore.

**Comment by mspncp** [comment]
It takes a while to refill 384 bits of entropy and the test reseeds more than once.
