### ISSUE TITLE
Add support to pass custom flags to `windres` tool

### ISSUE THREAD

**Issue by vszakats** [openssl/openssl#585]
Without it, the build will fail with any mingw distro that supports multiple targets 
and the targeted platform differs from the host platform. F.e. when using 
`mingw6-w64` i686-hosted toolchain [1] to create 64-bit OpenSSL binaries, 
or using x86_64-hosted toolchain [2] to build 32-bit OpenSSL binaries.

As a solution I'm at the moment using this patch:
   https://github.com/vszakats/harbour-deps/blob/master/openssl.diff#L29-L30
With these settings:
   https://github.com/vszakats/harbour-deps/blob/master/openssl.sh#L24-L25

The long form of these options is: `--target=pe-i386` and `--target=pe-x86-64`

But it'd be nice to have this out of the box.

An even better solution would be to automate this by _always_ passing 
these flags when targeting `mingw` or `mingw64` respectively. This is safe 
to do, as these `windres` options are also supported by single-target `mingw`
distros since a very long time (or possibly since the beginning, though I 
haven't made tests with very old `mingw` releases.)

/cc @levitte 

[1] <https://downloads.sourceforge.net/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.3.0/threads-posix/sjlj/i686-5.3.0-release-posix-sjlj-rt_v4-rev0.7z>
[2] <https://downloads.sourceforge.net/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.3.0/threads-posix/sjlj/x86_64-5.3.0-release-posix-sjlj-rt_v4-rev0.7z>

**Comment by levitte** [comment]
I've a few question about the diffs:

1. is the `-march` argument really necessary?  Won't the toolchain do the right thing?  I've received hints from elsewhere that they are more trouble than useful.
2. The `crypto/bio/bio.h` has been fixed (but perhaps not released yet, though)
3. I don't understand the `crypto/dh` changes, especially the one in `crypto/dh/dh.h`

I suppose, however, that the important thing is the changes to `Configure`...  

...  truly, would you mind making a mingw pull request with these patches?  It will be far easier to work with.

**Comment by levitte** [comment]
Another question is if `-mno-cygwin` is needed.

**Comment by vszakats** [comment]
1. As for `-march` I think the best is to not specify it at all in the default build configuration, which seems to be in agreement with the hints you got. If someone has specific needs (= different from C compiler defaults), the best way is to address it is by passing them as custom options.
2., 3. These were bugfixes commited to the 1.0.2 (and/or master) branches, that came out the days after 1.0.2f was released, which I retrofitted to my 1.0.2f build. We can disregard those here, they are unrelated.

**Comment by levitte** [comment]
For display, this is a patch I've received recently.  It's for master.

https://gist.github.com/levitte/4ec9a909bbf3a31c77a6

**Comment by levitte** [comment]
Thanks for your answers

**Comment by vszakats** [comment]
`-mno-cygwin` was required about 10 years ago when mingw was not a separate project but an operating mode implemented as part of the `cygwin` toolchain. I can't tell exactly which version made it unnecessary, but by now it can be safely dropped. (I deleted it from another project in 2008 and there was never any repercussions)

**Comment by levitte** [comment]
Cool

**Comment by vszakats** [comment]
The gist look good.

In addition, I'd recommend adding `-m32` and `-m64` to the `mingw`, `mingw64` targets respectively. They are supported by all known mingw distros and they are in fact _required_ when working with a dual-target mingw distro.

**Comment by levitte** [comment]
Regarding `-mno-cygwin` and a bit more, here's another opinion (and I quote):

> Well, whatever they say it doesn't feel right. -fomit-frame-pointer for mingw64? More harm than improvement (if any). Remove applink from 32-bit? It means that they prevent users from mixing dlls and applications. Well, they are likely to argue that nobody does it, but doesn't it really only mean that they wouldn't ever do it? For reference, what's -mno-cygwin flag is about? It's about compiling for mingw with cygwin compiler. Mingw compiler did support -mno-cygwin as do-nothing for compatibility, but stopped as far as I understand. But once again, this option is not about mingw compiler, it's about cygwin compiler...

**Comment by vszakats** [comment]
- I haven't suggested adding it, but `-fomit-frame-pointer` has indeed no meaning in `mingw64`, so it can be safely dropped.
- Removing applink was a personal choice on my part. Can't really tell if it's globally a good choice to drop it. To me it looked a hellishly ugly hack (sorry), which is fragile and not working as intended in multiple scenarios. A reliable solution would be much welcome here. Here's the commit where I disabled it, after some users reported crashes when calling OpenSSL APIs that required certain (_non_-`FILE *` related) C RTL calls: https://github.com/vszakats/harbour-deps/commit/a13423f82edeb30e8ee6c6220d1c94af4fbca8aa
It's also well possible that I'm using it wrong, but it's not easy to gather information about details, besides scanning the source code and making inherently limited tests.
- `-mno-cygwin` - maybe I'm misunderstanding something, but the opinion suggests that if someone these days would like to use the cygwin toolchain to create mingw binaries (?), it's required. It's debatable how common this scenario is, but of course it can be left there, if that makes some users happy, but it's also a solution that those users enable this option manually, as this option has nothing to do with `mingw` itself, it's a cygwin specific option, only useful there. I personally find the latter cleaner, but it's not a big problem the other way either, only a little bit of clutter.

**Comment by vszakats** [comment]
Answering here: https://github.com/openssl/openssl/issues/625#issuecomment-180733433

**Comment by vszakats** [comment]
Closing this in favour of the other [thread](https://github.com/openssl/openssl/issues/625) where this is being addressed, thanks to @levitte.
