### ISSUE TITLE
EVP_DigestSignInit fails with BLAKE2 algorithms

### ISSUE THREAD

**Issue by kareldonk** [openssl/openssl#5854]
The `EVP_DigestSignInit` function fails when using the `EVP_blake2s256` and `EVP_blake2b512` algortihms. I'm not sure if this is by design or if those algorithms are not supported. I assumed any of the `EVP_MD` types could be used and I couldn't find anything in the docs about supported types. I'm using the 1.1.0f version of the libcrypto library.

**Comment by levitte** [comment]
Nope.  `EVP_DigestSignInit` works only for EVP_MDs with associated pkey algos.  There's a draft in the works to define such a set of algos: https://github.com/willinois/draft-wconner-blake2sigs

**Comment by mattcaswell** [comment]
I updated the docs to make the restrictions explicit in #5992.
