### ISSUE TITLE
Windows build failure: can not open “windows.h”: No such file or directory

### ISSUE THREAD

**Issue by infeng** [openssl/openssl#586]
My system version is windows10 x64 and my vs version is ve2015 community.
When i execute "nmake -f ms\ntdll.mak" , fail.
The error message is:
ms\uplink.c(11): fatal error C1083: can not open head file: “windows.h”: No such file or directory
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.EXE"”: return code“0x2”
Stop.

**Comment by Ventusfahrer** [comment]
hi
windows.h is part of the Windows Software Developmnet Kit (Windows xx SDK) which needs to be installed in addition to Visual Studio.

So this is not an open-ssl issue, but an incomplete setup of your development environment.

See https://dev.windows.com/en-us/downloads/windows-10-sdk for the download location and documentation. 

After you have installed the SDK you need to specify it's include and lib directories in the environment variables INCLUDE and LIBPATH. 

Alternatively you can specify the directories in the projects properties (compiler and linker).

**Comment by junfx** [comment]
Install windows 10 sdk and rename **W**indows.h to **w**indows.h?
