### ISSUE TITLE
[Security] Pasting password into powershell prompt generates unencrypted .pfx

### ISSUE THREAD

**Issue by rocifier** [openssl/openssl#5864]
Using the following command in Windows 10 powershell prompts me to enter and re-enter my password. I tested this using an intermediate CA from Let's Encrypt and the following command to combine public, private, and ca files into a .pfx certificate:

`openssl pkcs12 -export -out "certificate_combined.pfx" -inkey "private.key" -i
n "certificate.crt" -certfile ca_bundle.crt`

Manually typing the password applies the "invisible" password to the generated pfx certificate, but pasting any characters at all does not input those characters (unseen), when the user may presume that they were entered.

If the entire password was pasted twice, eg. from https://strongpasswordgenerator.com then the user may assume the .pfx is encrypted (since there is no warning shown regarding entering a blank password), and try to distribute it via email, or direct upload to a server. Such an action would unknowingly expose the user's private key to privileged attackers.

If this is a powershell issue we can't fix, I recommend a notice to show at the prompt informing users they must enter the password using the keyboard, and pasting part or all of a password will not work. This probably also affect other prompts in the system - I have not tested them.

I have not tested bash for this issue.

**Comment by rocifier** [comment]
How are the "Enter password:" prompts handled? Are they built into powershell or is there code to request masked user input at those times?

**Comment by mspncp** [comment]
Have a look at [read_string_inner() in ui_openssl.c](https://github.com/openssl/openssl/blob/master/crypto/ui/ui_openssl.c#L274):

```
(gdb) bt
#0  read_string_inner (ui=0x5555558a2550, uis=0x55555589db00, echo=0, strip_nl=1) at crypto/ui/ui_openssl.c:275
#1  0x00007ffff78358aa in read_string (ui=0x5555558a2550, uis=0x55555589db00) at crypto/ui/ui_openssl.c:233
#2  0x00007ffff7834ba6 in UI_process (ui=0x5555558a2550) at crypto/ui/ui_lib.c:515
#3  0x00007ffff7796b75 in EVP_read_pw_string_min (buf=0x7fffffffcd70 "\260\315\377\377\002", min=4, len=1024,
    prompt=0x7ffff78a24e8 "Enter PEM pass phrase:", verify=1) at crypto/evp/evp_key.c:67
#4  0x00007ffff77c54ba in PEM_def_callback (buf=0x7fffffffcd70 "\260\315\377\377\002", num=1024, w=1, key=0x0) at crypto/pem/pem_lib.c:54
#5  0x00007ffff77c7f3e in do_pk8pkey (bp=0x55555589d250, x=0x55555589ddd0, isder=0, nid=-1, enc=0x7ffff7b1c8a0 <des_cbc>, kstr=0x0, klen=0, cb=0x0, u=0x0)
    at crypto/pem/pem_pk8.c:79
#6  0x00007ffff77c7d8d in PEM_write_bio_PKCS8PrivateKey (bp=0x55555589d250, x=0x55555589ddd0, enc=0x7ffff7b1c8a0 <des_cbc>, kstr=0x0, klen=0, cb=0x0, u=0x0)
    at crypto/pem/pem_pk8.c:46
#7  0x00007ffff77c8cb1 in PEM_write_bio_PrivateKey (bp=0x55555589d250, x=0x55555589ddd0, enc=0x7ffff7b1c8a0 <des_cbc>, kstr=0x0, klen=0, cb=0x0, u=0x0)
    at crypto/pem/pem_pkey.c:100
#8  0x00005555555a8f4b in pkey_main (argc=0, argv=0x7fffffffd910) at apps/pkey.c:197
#9  0x00005555555a170a in do_cmd (prog=0x555555897a60, argc=4, argv=0x7fffffffd910) at apps/openssl.c:564
#10 0x00005555555a0aac in main (argc=4, argv=0x7fffffffd910) at apps/openssl.c:183
```

**Comment by mattcaswell** [comment]
This appears to be a powershell issue, not OpenSSL. Closing.
