### ISSUE TITLE
latest link openssl-1.0.2-latest.tar.gz has problem

### ISSUE THREAD

**Issue by sawanoboly** [openssl/openssl#5865]
pointer of latest link `https://www.openssl.org/source/openssl-1.0.2-latest.tar.gz` It will return another response for each request.

It returns 301 or 302

```
# case 301 (location will be 404)
$ curl -sfLI https://www.openssl.org/source/openssl-1.0.2-latest.tar.gz 
HTTP/1.1 301 Moved Permanently
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Location: https://www.openssl.org/source/old/1.0.2/openssl-1.0.2-latest.tar.gz

# case 302
$ curl -sfLI https://www.openssl.org/source/openssl-1.0.2-latest.tar.gz 
HTTP/1.1 302 Moved Temporarily
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Location: https://www.openssl.org/source/openssl-1.0.2o.tar.gz
```

**Comment by richsalz** [comment]
ping @levitte

**Comment by levitte** [comment]
We had a mixup yesterday with our .htaccess, you may have caught us in the middle of correcting it, or some caching after effect...  Either way, when I'm checking now, it consistently gives me 302s, so I think the problem went away.

Thanks for reporting!

**Comment by sawanoboly** [comment]
hmm... still failed my tests. @levitte 
https://travis-ci.org/matsumotory/ngx_mruby/jobs/361961947

Would you please check again? Or, please purge cache if using CDN.
