### ISSUE TITLE
1.1.0h build issue on SPARC/Solaris and maybe HPUX

### ISSUE THREAD

**Issue by thogard** [openssl/openssl#5867]
The Makefile for 1.1.0h now requires CPP to be set but config doesn't set it.

Typical errors are a number of unknown symbols:
 _sparcv9_rdtick                     ./libcrypto.so
bn_mul_mont_int                   ./libcrypto.so

The easy solution is to run:
CPP=cpp make

This was tested on Solaris 9 and 11.  It appears that "make clean" also fails to remove some of the SPARC assembly object files so it won't rebuild after a "make clean;CPP=cpp make"   removing the .o files fixes that problem.

**Comment by levitte** [comment]
That was quite a thing you found. Unfortunately, it slipped us by, obviously.

Fix coming up

**Comment by levitte** [comment]
Btw, this affects config targets that use s390x, IA64 or Sparc assembler modules.  So it does affect HPUX on IA64, indeed.

**Comment by dot-asm** [comment]
> CPP=cpp make

What's config target? Thing is that cpp might be insufficient, because we pass even compiler-specific flags. If it's pure pre-processor, then it might either fail complaining on invalid flags, or silentrly ignore them. And latter can have more bad consequences for some targets.

**Comment by dot-asm** [comment]
As curious fact. I don't even have any cpp in my vanilla Solaris x86 +devstudio installation...
