### ISSUE TITLE
Only oneshot supported error when creating ed25519 signatures

### ISSUE THREAD

**Issue by KevinLapagna** [openssl/openssl#5873]
I get an "only oneshot supported" error, whenever I try to sign or verify something with ed25519. I'm using OpenSSL 1.1.1-pre3 (beta) for this.

Is this just still work in progress for a complete ed25519 support or is there another way to create and verify ed25519 signatures with the openssl CLI?

```
$ openssl genpkey -algorithm ed25519 -out ed25519-priv-key.pem
$ echo "sign me" | openssl dgst -sign ed25519-priv-key.pem
Read Error in stdin
140570478014912:error:060AD0B1:digital envelope routines:update:only oneshot supported:crypto/evp/m_sigver.c:20:
```

**Comment by mattcaswell** [comment]
Hmmm. Interesting. We implement PureEdDSA which does not have a separate digest step. This is unlike the other signing algorithms that we have. The dgst app only knows about those. We either need to get it to bail out with an error if you attempt to sign using Ed25519/Ed448, or teach dgst that it doesn't actually need to do a digest at all for those algorithms (which seems a bit strange given the name of the app).

While checking something on this I looked at the dgst man page and found this gem:
````
The digest of choice for all new applications is SHA1. Other digests
       are however still widely used.
````
That probably needs updating too!!!

**Comment by KevinLapagna** [comment]
Signing with _pkeyutl_ seems also not possible yet. But at least the error message says so more directly.

```
$ echo "sign me" | openssl pkeyutl -sign -inkey ed25519-priv-key.pem
pkeyutl: Error initializing context
139637327172032:error:0608D096:digital envelope routines:EVP_PKEY_sign_init:operation not supported for this keytype:crypto/evp/pmeth_fn.c:40:
```

**Comment by mattcaswell** [comment]
> Is there a openssl command line util to sign and verify a message (albeit unhashed) using a Ed25519 private/public key?

No, this is not supported. There are no plans to support it in the upcoming 1.1.1 release.

**Comment by parasssh** [comment]
> No, this is not supported. There are no plans to support it in the upcoming 1.1.1 release.

Could we reopen this issue and mark it with a label after-1.1.1 and/or master ?

**Comment by mattcaswell** [comment]
I'd suggest opening a new issue. The immediate problem about misleading error messages was addressed.
