### ISSUE TITLE
srp does not support options of sha-xxx

### ISSUE THREAD

**Issue by slowingwind** [openssl/openssl#5878]
I see that srp implementation is based on EVP_sha1.
does it have options to support other hashing algorithms like EVP_sha256, EVP_sha512?

**Comment by mattcaswell** [comment]
Unfortunately not at this time.

**Comment by richsalz** [comment]
(That's not us, that's the standards definition BTW)

**Comment by tdwmap** [comment]
@richsalz Hi, do you mean the standard SRP only allows EVP_sha1 but not EVP_sha256? We tried to use OpenSSL to build a c++ client to work with authentication backend from AWS Cognito service. AWS Cognito supports SRP but seems to use EVP_sha256. Does that mean they are not compliant to SRP standard? Thanks for you input!

**Comment by richsalz** [comment]
Please see https://tools.ietf.org/html/rfc2945

**Comment by tdwmap** [comment]
@richsalz Thanks for the pointer. The RFC doc used SHA-1 as the reference hash function, but it also says other hash functions can be used:

Any hash function used with SRP should produce an output of at least 16 bytes and have the property that small changes in the input cause significant nonlinear changes in the output.

So I'll take it that current OpenSSL release only supports SHA-1 implementation and other hash functions are not supported?
