### ISSUE TITLE
Import wycheproof tests

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#5885]
Google's project wycheproof has a large collection of test vectors, in json.  We should look at building a tool to import and convert them.

https://github.com/google/wycheproof

**Comment by levitte** [comment]
So all we need is a conf Parser that groks json, the rest seems to be a job for evptest.

**Comment by levitte** [comment]
... I meant stanza reader.

**Comment by richsalz** [comment]
Closing since #7714 has more discussion.
