### ISSUE TITLE
GlobalSign Certificates failing

### ISSUE THREAD

**Issue by jjbeber** [openssl/openssl#5890]
I'm facing this issue with GlobalSign certificates, they work well with Chrome and Firefox, but with tools that use OpenSSL (curl, python requests, urllib3) they fail.

I'm not the maintainer of the sites, I'm just facing some problems with some APIs of the first domain. I don't know what to do, Can someone give me some help to understand what is going on?

# The first domain

## Curl
```
❯ curl -vvI https://mqlinuxext.serasa.com.br/         
*   Trying 200.245.207.210...
* TCP_NODELAY set
* Connected to mqlinuxext.serasa.com.br (200.245.207.210) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```
## OpenSSL
`❯ openssl s_client -connect mqlinuxext.serasa.com.br:443 -state -debug`: [gist link](https://gist.github.com/jjbeber/8a503cd5f6b5baf60c8997dd272b91ea)

## Firefox
![serasa_firefox](https://user-images.githubusercontent.com/29125605/38396590-37f12674-390f-11e8-890f-239d85c0ed21.png)
![serasa_firefox_1](https://user-images.githubusercontent.com/29125605/38396596-41c31892-390f-11e8-883e-ca20e7bc6168.png)

## Chrome
![serasa_chrome](https://user-images.githubusercontent.com/29125605/38396593-3c3d7390-390f-11e8-8b84-730e4eb3a795.png)

# Second domain

## Curl
```
*   Trying 200.193.75.39...
* TCP_NODELAY set
* Connected to portal1.tupy.com.br (200.193.75.39) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

## OpenSSL
`openssl s_client -connect portal1.tupy.com.br:443 -state -debug`:  [gist link](https://gist.github.com/jjbeber/05b8b5216761608b3ee6bc9ad8ce17ad)

## Firefox
![tupy_firefox](https://user-images.githubusercontent.com/29125605/38396703-e0035670-390f-11e8-90dc-9cbccd33d589.png)
![tupy_firefox_2](https://user-images.githubusercontent.com/29125605/38396704-e1f057f8-390f-11e8-8fc4-1d08abf2176d.png)

## Chrome
![tupy_chrome](https://user-images.githubusercontent.com/29125605/38396706-e40c204e-390f-11e8-9577-bcb7be08b4ff.png)

**Comment by richsalz** [comment]
```
SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

Did you read the error message?  Did you look at the curl link?

Curl does not know the CA you are using.

**Comment by levitte** [comment]
[This part](https://gist.github.com/jjbeber/8a503cd5f6b5baf60c8997dd272b91ea#file-openssl_mqlinuxext_serasa-L239-L243) of your `openssl s_client` output shows what's missing (quoted here):

```
---
Certificate chain
 0 s:/C=BR/ST=SP/L=Sao Paulo/O=Serasa S.A./CN=*.serasaexperian.com.br
   i:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2
---
```

It seems that the issuer cert is missing in the collection in `/etc/ssl/certs`.  You should file a report about this with the Linux dist you use, so they might add that issuer certificate to the collection.

**Comment by richsalz** [comment]
I was just asking questions to help figure out what you had already done, that's all.

**Comment by borisgorbunov** [comment]
Good day, did you manage to fix this problem with "unable to get local issuer certificate"
