### ISSUE TITLE
openssl enc

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#5893]
Hi,

Was checking encryption and decryption options in openssl.
The below link mentions some parameters that could be used with enc:
https://www.openssl.org/docs/manmaster/man1/enc.html

But on trying out, the parameters **-pbkdf2** and **-iter** was shown as unknown options.
I tried with the following versions of openssl: 1.0.2o  and 1.0.2n.

Could any one suggest what could be wrong.

Thanks & Regards,
Amal

**Comment by mattcaswell** [comment]
That's the link for the master (i.e. dev) version. Here is the equivalent link for 1.0.2:

https://www.openssl.org/docs/man1.0.2/apps/enc.html

As you will notice those options do not exist in that version.

**Comment by amaljesudas** [comment]
Hi Matt,

Thanks for the info.
Also, although command line arguments are not supported in 1.0.2, is there a possibility iteration count and pbkdf2 are supported internally by 1.0.2 ?
In between if I need to get the dev version which includes support for iter and pbkdf2, how or which version should I take.

Regards,
Amal

**Comment by levitte** [comment]
PBKDF2_HMAC is available through [`EVP_BytesToKey`](https://www.openssl.org/docs/man1.0.2/crypto/EVP_BytesToKey.html)...  is that what you're asking for, @amaljesudas?

**Comment by amaljesudas** [comment]
Hi @levitte,

Thank you for suggesting the same.
I was asking if pbkdf2 and iter support exists in 1.0.2 version, although not supported through command line.
Since you mentioned EVP_BytesToKey, I will give that a try. 
Can you also tell me if openssl dev(master) version source package is available or if openssl packages are available only for release versions? (Asking because @mattcaswell mentioned that the link I referred was for the master (i.e. dev) version. )
I am new to openssl and is just learning from bits and pieces.  

Thanks & Regards,
Amal

**Comment by mattcaswell** [comment]
Actually I recommend against `EVP_BytesToKey`. It is *not* an implementation of PBKDF2. From the docs:

````
Newer applications should use a more modern algorithm such as PBKDF2 as
defined in PKCS#5v2.1 and provided by PKCS5_PBKDF2_HMAC.
````

Instead see the PKCS5_PBKDF2_HMAC() function:

https://www.openssl.org/docs/man1.1.0/crypto/PKCS5_PBKDF2_HMAC.html

**Comment by mattcaswell** [comment]
Note the link above is for the 1.1.0 docs. The function does exist in 1.0.2 but is undocumented there. It works the same way as in 1.1.0.

**Comment by amaljesudas** [comment]
Thanks @mattcaswell and @levitte .
Your suggestions helped.
Also, I checked the implementation of CMS utility.

Regards,
Amal
