### ISSUE TITLE
cms -resign produces bad output

### ISSUE THREAD

**Issue by ddurham2** [openssl/openssl#591]
When using cms -resign to add a signature to a file, the Content Type..\r\n\r\n was duplicated in the resulting file.  This obviously caused verification to fail.

Testing master @ f006217bb628d05a2d5b866ff252bd94e3477e1f

**Comment by mattcaswell** [comment]
Please can you let me know the command line options you used to do this? Steve has had a look at this and can only reproduce it by including the -text option with -resign. Since -text should only be used when the input isn't in MIME format that is an error.

**Comment by mattcaswell** [comment]
Ping @ddurham2...please see previous question.

**Comment by mattcaswell** [comment]
No response from @ddurham2. Assuming this is user error as per the message above (i.e. using -text with -resign.). Closing.
