### ISSUE TITLE
Memory leak in rsa

### ISSUE THREAD

**Issue by 860000023** [openssl/openssl#5912]
The following code generates a leak

```
int MyRsaPrivateDec(byte *InBuffer,int StrLen, byte *OutBuffer)
{
	int iRetLen;
	BIGNUM *bnn, *bnd,*bne;

    RSA* pRsa ;
	EnterCriticalSection(&g_csConns);
	iRetLen = 0;
	pRsa= RSA_new();
	bnn = BN_new();
	bne = BN_new();
	bnd = BN_new();

	BN_hex2bn(&bnn, MODULUS);
	BN_set_word(bnd, PUBLIC_EXPONENT); // 
	BN_hex2bn(&bne, PRIVATE_EXPONENT);

	pRsa->n = bnn;
	pRsa->d = bnd;
	pRsa->e = bne;
    iRetLen = RSA_private_decrypt( 128 , InBuffer , OutBuffer , pRsa ,  RSA_PKCS1_PADDING );       

	RSA_free( pRsa );
	CRYPTO_cleanup_all_ex_data();
	LeaveCriticalSection(&g_csConns);
    return iRetLen;
	
}
```

i need help ,thx

**Comment by richsalz** [comment]
You need to provide more information, like where the leak is

**Comment by gomesconsultingservices** [comment]
Does RSA_free free the n, d, and e?  If not the bnn, bnd, and bne need to be freed in the listed function.

**Comment by mspncp** [comment]
Yes, it does: see [crypto/rsa/rsa_lib.c, L105](https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_lib.c#L105).

**Comment by mspncp** [comment]
Since your RSA struct is not opaque, you are probably using OpenSSL version 1.0.2. In this case you find [the code here](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/rsa/rsa_lib.c#L209).

**Comment by levitte** [comment]
Did that code run error free?  Otherwise, you have the internal error state to deal with, which is cleaned up with `ERR_remove_thread_state(NULL)`.

**Comment by mattcaswell** [comment]
In 1.0.2 you have to explicitly de-initialise the library. See the cleanup section here:

https://wiki.openssl.org/index.php/Library_Initialization

How do you know you have a leak? Do you have some debug output that indicates the source?

**Comment by richsalz** [comment]
Closing this issue.  Please reply with more data and re-open if it's still an issue.
