### ISSUE TITLE
SSL cipher not using tls

### ISSUE THREAD

**Issue by freaknils** [openssl/openssl#5914]
Hi, i have to use weak SSLv3 on a CentOS 7 Server to connect to an old mail server.

But my connection is not started by default. I think this is a bug in openssl.

```
~ openssl version -a
OpenSSL 1.0.2k-fips  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(8x,char) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic
```
This does not work:
```
~ openssl s_client -connect X.X.X.X:993  -prexit
CONNECTED(00000003)
140224255924128:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 289 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1523269578
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 289 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1523269578
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```
But this works fine:
```
~ openssl s_client -connect X.X.X.X:993  -prexit -tls1
CONNECTED(00000003)
....
---
Certificate chain
....
---
Server certificate
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----
....
---
No client certificate CA names sent
---
SSL handshake has read 1254 bytes and written 491 bytes
---
New, TLSv1/SSLv3, Cipher is RC4-MD5
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : RC4-MD5
    Session-ID: ...
    Session-ID-ctx:
    Master-Key: ....
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1523269620
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
```

Sadly i am not able to upgrade on a newer release.
Thanks!

**Comment by richsalz** [comment]
https://www.openssl.org/docs/faq.html#PROG6

**Comment by richsalz** [comment]
I missed that, sorry.

**Comment by richsalz** [comment]
What ciphers does the server support?  It could be that the server only supports weak ciphers, which are not supported in TLS 1.2, so you will have to explicitly connect with the older protocol??

**Comment by freaknils** [comment]
When I connect with -tls1 the connection uses:
```
SSL-Session:
    Protocol  : TLSv1
    Cipher    : RC4-MD5
```

**Comment by richsalz** [comment]
So I am confused.  Does this work?  Are you saying that the "use any protocol version" does not negotiate properly?  Does the server *only* support SSLv3?  My guess is no, since you say "it works" and I assume you are connecting to the desired server.  Does the server claim to support 1.2 ?

Version negotiation is done by the server accepting something the client offers.  It is possible that the openssl s_client in openssl 1.0.2 does not set the version range properly, but having more data might help debug this.  Or perhaps someone else can take a look.

**Comment by freaknils** [comment]
Yes 
```
openssl s_client -connect X.X.X.X:993  -prexit -tls1
```
works very well. My problem is, that I use a PHP function which depends on ssl. I went through the PHP source code and now I think that there is a problem in openssl.

**Comment by freaknils** [comment]
The server only supports TLS1

**Comment by richsalz** [comment]
The command-line works.  So now we have to figure out if it is an openssl bug or a php integration bug.  Since part of openssl works, the first place to look is at the php code.  I would suggest asking there, first.

**Comment by freaknils** [comment]
Is there a way to force to a special TLS version?

**Comment by richsalz** [comment]
Yes, via both command line (using the flags -tls1, etc) and the API (SSL_OP_NO_xxx for pre-1.1.1, or the API's setmin/max TLS version for pre-1.1.1. and later)

**Comment by freaknils** [comment]
Thanks for your reply. Is there a c function which I can use to enforce TLS1 in my c Code?

**Comment by freaknils** [comment]
Sorry I did n

**Comment by SimonFearby** [comment]
Personally I'd choose an option other than SSL 3, can you update the mailserver?

**Comment by freaknils** [comment]
Hi, no I am not able to update the server.

**Comment by shyamkhakhar9** [comment]
@freaknils I am also getting same error with tls1.2 were you able to solve it ?
