### ISSUE TITLE
Reallocating a X509 signature

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#5915]
Is there any method for modifying a X509 structure's signature and replacing it with my own? As far as I can tell the only way to do this is to use ASN1_STRING_data(cert->signature) and then modify that.

**Comment by mattcaswell** [comment]
That function is deprecated in version 1.1.0 and the X509 structure is opaque, so that approach might work in 1.0.2 but not in 1.1.0. AFAIK there is no way to do this in 1.1.0.
