### ISSUE TITLE
OpenSSL 1.1.1-pre5 + Nginx 1.13.11 can't support ChaCha20 .

### ISSUE THREAD

**Issue by haiwx** [openssl/openssl#5917]
It's a bug of Nginx ? The cipher is always `TLS_AES_256_GCM_SHA384`(TLS 1.3)

**Comment by richsalz** [comment]
What client are you using?  What protocol version (not TLS 1.3)?  How did you configure ciphers on the server?

**Comment by haiwx** [comment]
@richsalz Thanks for the reply, I tested it with Firefox Nightly and testssl.sh. And not only me testes it ,see:(https://www.v2ex.com/t/445216 (Chinese)),TLS_AES_256_GCM_SHA384` is always first choose.

```
ssl_ciphers TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256 ……
```

**Comment by mattcaswell** [comment]
Is this using the latest OpenSSL version from git? Has nginx been updated to use the new way of configuring TLSv1.3 ciphersuites? The default TLSv1.3 ciphersuites are now:

"TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256"

If you want to change them you need to configure them differently than for the TLSv1.2 and below ciphersuites.

**Comment by haiwx** [comment]
@mattcaswell Yes , it's lastest OpenSSL, what's the new way of configuring TLSv1.3 ciphersuites, can you show me a simple example ? Very Thanks!

![suit](https://user-images.githubusercontent.com/13563349/38547792-9f9045fe-3ce2-11e8-890a-b44db58ba2a5.png)

**Comment by leonklingele** [comment]
@haiwx to list available cipher suites, use the following command:
`$ openssl ciphers -V | awk '{print $3}'`

Each line represents a cipher suite which you can use for the `ssl_ciphers` directive of nginx verbatim, each separated by a colon.

**Comment by haiwx** [comment]
@leonklingele I did not mean that. mattcaswell said :" the new way of configuring TLSv1.3 ciphersuites" already. But i don't know about it.

**Comment by richsalz** [comment]
For example, Apache added a new configuration directive to specify the TLS 1.3 ciphersuites.

This looks to be an nginx configuration issue.  I think we should close this.
