### ISSUE TITLE
OpenSSL 1.1.0 cannot load public key from certificate with rsassaPss in SubjectPublicKeyInfo

### ISSUE THREAD

**Issue by a20god** [openssl/openssl#5919]
A major CA, D-Trust, uses a root certificate that uses rsassaPss as algorithm in SubjectPublicKeyInfo:
[D-TRUST_Root_CA_3_2016.txt](https://github.com/openssl/openssl/files/1893824/D-TRUST_Root_CA_3_2016.txt)
OpenSSL 1.1.0h cannot load the public key from that certificate (as evidenced by the .txt file). Support for rsassaPss in SubjectPublicKeyInfo should be backported from OpenSSL 1.1.1.

**Comment by mattcaswell** [comment]
Unfortunately that is highly unlikely to happen. It is too significant a change for a stable release.

**Comment by richsalz** [comment]
And supporting a new signature type is a new feature, so it won't happen.
