### ISSUE TITLE
Refactor SM2 implementation to use its own PMETH

### ISSUE THREAD

**Issue by ronaldtse** [openssl/openssl#5924]
From these discussions:
* https://github.com/openssl/openssl/pull/5895#discussion_r180432430
* https://github.com/openssl/openssl/pull/4793#issuecomment-380055949

@dot-asm:
>  It should either be implemented as own pmeth, or have own kmeth that would override default, or something else.

@levitte:
> I think I saw @dot-asm suggest that ec_curve.c could be changed to include specific EC_KEY_METHODs with select curves, and thereby hook the SM2 curves with the SM2 algos by default. I know I was thinking something like that as well early on when looking at #4793, but couldn't quite get it together without making things hugely incompatible with 1.1.0... but maybe there's a possibility to do this?

@randombit:
> The initial implementation was using its own pmeth but it was removed along the way because wiring into existing ec_pmeth.c seemed simpler and without harm. 
> OK. I will create a PR moving SM2 to its own PMETH in next week or so.

cc: @richsalz @mattcaswell @InfoHunter

**Comment by randombit** [comment]
I started on implementing this but it is slow going both because I'm 90% on other projects right now (unrelated to Ribose) and also since it's not really clear (to me) if I also need AMETH/KMETH to do a PMETH or generally how any of these structures are supposed to work.

**Comment by randombit** [comment]
Fixed by #6443
