### ISSUE TITLE
Is WINARM support coming?

### ISSUE THREAD

**Issue by kunalspathak** [openssl/openssl#593]
Are there any plans of adding WINDOWS/ARM configuration?

I checked [Configure](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/Configure#L580) file and [mk1mf.pl](https://github.com/openssl/openssl/blob/e8cdcd52b33605b44390888e6aaa0548ca877b46/util/mk1mf.pl#L99) but don't find an entry for WINARM.

**Comment by richsalz** [comment]
we have no plans to do so at this time.  Does config for windows with no-asm not work?

**Comment by kunalspathak** [comment]
Actually, it does work. Thanks!
