### ISSUE TITLE
openssl holding on to load of memory when calling PEM_read_X509_CRL

### ISSUE THREAD

**Issue by ericcurtin** [openssl/openssl#5931]
When reading a 15mb crl file in pem format, openssl holds onto 100mb of RAM:

```
#include <openssl/x509.h>
#include <openssl/pem.h>

#include <string.h>
#include <string>

// Examples of strings to pass here are VmSize, VmRSS, VmHWM, HugetlbPages
std::string get_from_proc(std::string what) {
    if (FILE* f = fopen("/proc/self/status", "r")) {
        what += ':';
        char line[128];
        while (fgets(line, sizeof(line), f)) {
            if (!strncmp(line, what.c_str(), what.size())) {
                fclose(f);
                return line;
            }
        }
        fclose(f);
    }
    return "";
}

int main() {
  FILE* fp = fopen("some_15_mb_crl_file", "r");
  printf("%s\n", get_from_proc("VmRSS").c_str());
  X509_CRL* crl = PEM_read_X509_CRL(fp, NULL, NULL, NULL);
  printf("%s\n", get_from_proc("VmRSS").c_str());
  fclose(fp);
  printf("%s\n", get_from_proc("VmRSS").c_str());
  X509_CRL_free(crl);
  printf("%s\n", get_from_proc("VmRSS").c_str());
  return 0;
}
```

g++ file.cpp -lssl; ./a.out

and output:

```
VmRSS:	    2120 kB

VmRSS:	  119044 kB

VmRSS:	  119040 kB

VmRSS:	  105872 kB
```

Using version OpenSSL 1.0.1e-fips on Red Hat 6 x86_64. Is reproducabile on any openssl 1.0.1 version on red hat/centos 6 x86_64.

valgrind reports no memory leaks

**Comment by ericcurtin** [comment]
Valgrind reports this 

==3804734== Memcheck, a memory error detector
==3804734== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==3804734== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==3804734== Command: ./a.out
==3804734== 
==3804734== 
==3804734== HEAP SUMMARY:
==3804734==     in use at exit: 416 bytes in 6 blocks
==3804734==   total heap usage: 3,311,936 allocs, 3,311,930 frees, 168,705,946 bytes allocated
==3804734== 
==3804734== LEAK SUMMARY:
==3804734==    definitely lost: 0 bytes in 0 blocks
==3804734==    indirectly lost: 0 bytes in 0 blocks
==3804734==      possibly lost: 0 bytes in 0 blocks
==3804734==    still reachable: 416 bytes in 6 blocks
==3804734==         suppressed: 0 bytes in 0 blocks
==3804734== Reachable blocks (those to which a pointer was found) are not shown.
==3804734== To see them, rerun with: --leak-check=full --show-reachable=yes
==3804734== 
==3804734== For counts of detected and suppressed errors, rerun with: -v
==3804734== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6) 

So it looks like everything is deallocated fine

**Comment by richsalz** [comment]
You might consider using a malloc-debug package (including openssl's own) to see if it's openssl runtime or malloc allocating memory.

**Comment by ericcurtin** [comment]
We actually figured it out, if you call malloc_trim(0) after X509_CRL_free(crl), the OS claims most of the memory back:

```
X509_CRL_free(crl);
malloc_trim(0);
```
