### ISSUE TITLE
EVP_PKEY_get0_DH needs a check on whether it returns NULL

### ISSUE THREAD

**Issue by ruciser** [openssl/openssl#5934]
Hi, I found that _EVP_PKEY_get0_DH(EVP_PKEY *pkey)_ may return a NULL value.
While in ssl/statem_srvr.c in both 1.1.1 and 1.1.0 version of OpenSSL, function _tls_construct_server_key_exchange_ and _tls_process_cke_dhe_ seem to call _EVP_PKEY_get0_DH_ without checking the returned value, and then pass the returned value directly into other function calls.

Take _tls_construct_server_key_exchange_ for example: 
int tls_construct_server_key_exchange(SSL *s, WPACKET *pkt)
{ ......
       s->s3->tmp.pkey = ssl_generate_pkey(pkdhp);
        if (s->s3->tmp.pkey == NULL) {
            /* SSLfatal() already called */
            goto err;
        }
        dh = EVP_PKEY_get0_DH(s->s3->tmp.pkey);  **//here dh may need a check on the NULL situation**
        ......
        DH_get0_pqg(dh, &r[0], NULL, &r[1]);
......
}

**Comment by mattcaswell** [comment]
Fix in #5983.
