### ISSUE TITLE
forward declaration of 'X509 in ossl_typ.h

### ISSUE THREAD

**Issue by ramahmoo** [openssl/openssl#594]
We are planning to migrate our openssl application from version 1.0.2e to 1.1.0-pre1. Tried to compile our application with 1.1.0-pre1 and immediately found error in ossl_typ.h "forward declaration of 'X509". Cross checked and found that x509_st is defined in crypto/include/internal/x509_int.h. Is it no more public structure?

**Comment by mattcaswell** [comment]
Correct. That is one of the major differences between 1.1.0 and 1.0.2. You will find that many structures have been made opaque. You need to use accessor functions where you might have previously delved directly into the structure internals. Incidentally 1.1.0-pre2 is now out, so you maybe better using that instead.

**Comment by ramahmoo** [comment]
ossl_typ.h is part of openssl include, and there i see an error on line
typedef struct x509_st X509;

should i remove this header file from my includes and try to use new accessor functions?

**Comment by ramahmoo** [comment]
i have used instances of X509 in many places in my application code.

**Comment by mattcaswell** [comment]
You should not get a compilation error on that line itself. Although the compiler may (indirectly) complain about it if you attempt to allocate the object directly (e.g. on the stack). So this won't work because the compiler doesn't know the storage size for the X509 object:
````
void myfunc(void) {
    X509 myx509;

    ....
}
````
Instead you have to do:
````
void myfunc(void) {
    X509 *myx509;

    myx509 = X509_new();
    ....
}
````

**Comment by richsalz** [comment]
In other words, what @mattcaswell was saying, is that this is how you do "opaque types" in C.  You declare the struct, but only allow pointers to it.  If you decide to fix/update your code, please open an issue if you find that there are any utility functions that you need.
