### ISSUE TITLE
EVP_get_cipherbyname() fails

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#5940]
I am implementing CMS with password based encryption using openssl.
Using the openssl CMS utility, I could successfully encrypt and decrypt a file.
But on trying to achieve the same in a sample application, it fails.
On debugging, I could understand that CMS_final() is returning false.
Investigating further, the issue was seen to be from function OBJ_NAME_get()  \crypto\objects\o_names.c.
Here names_lh is seen to be NULL.
Surprisingly, on debugging CMS utility with same parameters,  names_lh is not NULL.
Can someone please help me sort this out.

Thanks & Regards,
Amal

**Comment by mattcaswell** [comment]
What version of OpenSSL are you using? If it's 1.0.2 (or earlier) then did you initialise the library? OpenSSL 1.0.2 needs explicit initialisation. That is no longer the case in version 1.1.0.

If this is your problem then you might want to check:

https://wiki.openssl.org/index.php/Library_Initialization

**Comment by amaljesudas** [comment]
Thank you @mattcaswell, your suggestion fixed my issue.
I was using 1.0.2n and did not initialize.

Regards,
Amal
