### ISSUE TITLE
Memory leak in OpenSSL 1.1.0 async API

### ISSUE THREAD

**Issue by xybu** [openssl/openssl#5950]
So `OPENSSL_cleanup()` is scheduled to run at exit to free memory.
Inside its code, it sets `stopped` to 1 before calling the actual functions that free up memory:
https://github.com/openssl/openssl/blob/6b49b30811f4afa0340342af9400b8d0357b5291/crypto/init.c#L432

Then calls `ossl_init_thread_stop()` to free the thread-local async stuff:
https://github.com/openssl/openssl/blob/6b49b30811f4afa0340342af9400b8d0357b5291/crypto/init.c#L438

Inside this function, it calls `ASYNC_cleanup_thread()` to free up thread-local memory
https://github.com/openssl/openssl/blob/6b49b30811f4afa0340342af9400b8d0357b5291/crypto/init.c#L354

`ASYNC_cleanup_thread()` is at
https://github.com/openssl/openssl/blob/cbe2964821bb063f61ed2544cfce196ec1c0d62b/crypto/async/async.c#L391

It calls `async_free_pool_internal()` internally:
https://github.com/openssl/openssl/blob/cbe2964821bb063f61ed2544cfce196ec1c0d62b/crypto/async/async.c#L376

which then calls `async_ctx_free()` internally:
https://github.com/openssl/openssl/blob/cbe2964821bb063f61ed2544cfce196ec1c0d62b/crypto/async/async.c#L386

This `function uses async_get_ctx()` to obtain thread-local async ctx to free:
https://github.com/openssl/openssl/blob/cbe2964821bb063f61ed2544cfce196ec1c0d62b/crypto/async/async.c#L70

`async_get_ctx()` calls `OPENSSL_init_crypto()` internally:
https://github.com/openssl/openssl/blob/cbe2964821bb063f61ed2544cfce196ec1c0d62b/crypto/async/async.c#L60

But `OPENSSL_init_crypto()` won't succeed if `stopped == 1`:
https://github.com/openssl/openssl/blob/6b49b30811f4afa0340342af9400b8d0357b5291/crypto/init.c#L543

So `async_get_ctx()` returns a NULL ptr, resulting in that `async_ctx_free()` fails to free the ctx.

**Comment by xybu** [comment]
Is it fine to move

https://github.com/openssl/openssl/blob/6b49b30811f4afa0340342af9400b8d0357b5291/crypto/init.c#L438

to the line above `stopped = 1`?

https://github.com/openssl/openssl/blob/6b49b30811f4afa0340342af9400b8d0357b5291/crypto/init.c#L432

**Comment by bernd-edlinger** [comment]
No, this will enable the error module to allocate a new state, if anything triggers an error.
I would prefer to expand async_get_ctx without the call to OPENSS_crypto_init.

**Comment by stevelinsell** [comment]
Yes I agree with @bernd-edlinger instead of calling async_get_ctx() from async_ctx_free()  it would be better just calling CRYPTO_THREAD_get_local(&ctxkey) directly sidestepping the OPENSSL_crypto_init for that case.
@mattcaswell as you wrote that bit of code do you happen to know if there is there any reason why it would cause an issue if the call to OPENSSL_crypto_init is bypassed in the case of calling an async_ctx_free()?
I can raise a pull request with the fix if you like.

**Comment by bernd-edlinger** [comment]
There is probably also an issue if the application calls ASYNC_cleanup_thread
without first ASYNC_init_thread as this function would be using an uninitialized
thread key handle.

**Comment by bernd-edlinger** [comment]
I just wondered how the reporter ran into the issue.
Our test case explicitly calls ASYNC_cleanup_thread when appropriate, but
when that call is missing I see a memory leak.  If ASYNC_cleanup_thread
is called for ossl_init_thread_stop it is the thread key exists.

But what would happen if the API function ASYNC_cleanup_thread is called
at the wrong time.  Then it uses an uninitialized thread key, I don't know
if that is always safe.

I am thinking of adding the OPENSSL_init_crypto to ASYNC_cleanup_thread,
the API function, and at the same time having an internal function async_cleanupt_thread
for instance, that is only called from OPENSSL_init_crypto and that does not
need to call back to OPENSSL_init_crypto.

Hmm, at least that's what came into my mind ....

**Comment by xybu** [comment]
@bernd-edlinger Well we found this because our code did not call ASYNC_cleanup_thread() explicitly but relied on `OPENSSL_cleanup()`.

**Comment by bernd-edlinger** [comment]
Boah!

```
ASYNC_start_job ->
        if ((ctx->currjob = async_get_pool_job()) == NULL) {
            return ASYNC_NO_JOBS;
        }

async_get_pool_job ->
        if (ASYNC_init_thread(0, 0) == 0)
            return NULL;

ASYNC_init_thread -> err:  async_free_pool_internal(pool);

async_free_pool_internal ->  async_ctx_free()
```

so ctx->currjob = async_get_pool_job() in ASYNC_start_job can delete ctx before assigning!
