### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by lgh8820** [openssl/openssl#5953]
checking OpenSSL header version... 1010008f (OpenSSL 1.1.0h  27 Mar 2018)
checking OpenSSL library version... configure: error: OpenSSL >= 1.1.0 is not yet supported (have "1010008f (OpenSSL 1.1.0h  27 Mar 2018)")

openssh-7.7p1
zlib-1.2.11
OpenSSL 1.1.0h
Centos 6.9

The installation is wrong, how to solve it, thank you

**Comment by levitte** [comment]
I assume you were trying to compile openssh, is that it?  Apparently, whatever you're trying to build hasn't been adapted for OpenSSL 1.1.0 yet.  Unfortunately, *we* can't do anything about it.  You need to talk with those who made whatever you're trying to build.

There's usually a README that will explain to you where you can report issues.  Read it.

**Comment by ArsenShnurkov** [comment]
I got this message when emerging "net-misc/openssh-7.7_p1-r4". The README is here - https://github.com/openssh/openssh-portable

**Comment by mspncp** [comment]
Since you are using emerge/portage, it might also be a problem specific to your Gentoo Linux distribution.

**Comment by levitte** [comment]
I've the impression that @ArsenShnurkov only tried to helpfully indicate where to find the appropriate README...

**Comment by petrovr** [comment]
Gentoo emerge has a flag X509. Try it ;).

**Comment by levitte** [comment]
@petrovr, how exactly does that help openssh compile with a openssl that's too modern for it?

**Comment by petrovr** [comment]
:) if X509 flag is selected ebuild script will download and apply diff (patch) ( see  http://roumenpetrov.info.localhost/secsh/download.html )

As result OpenSSH turns into PKIX-SSH what is more then support "X.509 based authorization".
Of course PKIX-SSH works fine with OpenSSL 1.1.* even more - with upcoming 1.1.1 where user could use OpenSSL store API to access user identifies (keys) and other functionality that does not exist in OpenBSD version.

For protocol ebuild script X509_VER variable could be changed to 11.3.2 - this version restores tun/tap functionality broken by OpenBSD team in OpenSSH 7.7p1 and restores "hostbased authentication" broken in PKIX-SSH 11.0.
