### ISSUE TITLE
OpenSSL 1.1.1pre4 m_blake2b compilation error [-Werror=missing-field-initializers].

### ISSUE THREAD

**Issue by Graymanflo** [openssl/openssl#5955]
Good evening.

I am trying to compile OpenSSL 1.1.1pre4 for Nginx 1.13.12 but I am running into this compilation error on Debian 9:

```
gcc  -I. -Icrypto/include -Iinclude -fPIC -m64  -Wa,--noexecstack -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fdebug-prefix-map=/usr/src/nginx-pagespeed/nginx-1.13.12=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC  -D_GLIBCXX_USE_CXX11_ABI=0 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/src/nginx-pagespeed/openssl-1.1.1-pre4/.openssl/ssl\"" -DENGINESDIR="\"/usr/src/nginx-pagespeed/openssl-1.1.1-pre4/.openssl/lib/engines-1.1\"" -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -MMD -MF crypto/blake2/m_blake2s.d.tmp -MT crypto/blake2/m_blake2s.o -c -o crypto/blake2/m_blake2s.o crypto/blake2/m_blake2s.c
crypto/blake2/m_blake2b.c:53:1: error: missing initializer for field 'md_ctrl' of 'EVP_MD {aka const struct evp_md_st}' [-Werror=missing-field-initializers]
 };
 ^
In file included from crypto/blake2/m_blake2b.c:24:0:
crypto/include/internal/evp_int.h:118:11: note: 'md_ctrl' declared here
     int (*md_ctrl) (EVP_MD_CTX *ctx, int cmd, int p1, void *p2);
           ^~~~~~~
cc1: all warnings being treated as errors
Makefile:1610: recipe for target 'crypto/blake2/m_blake2b.o' failed
make[4]: *** [crypto/blake2/m_blake2b.o] Error 1
make[4]: *** Waiting for unfinished jobs....
crypto/blake2/m_blake2s.c:53:1: error: missing initializer for field 'md_ctrl' of 'EVP_MD {aka const struct evp_md_st}' [-Werror=missing-field-initializers]
 };
 ^
In file included from crypto/blake2/m_blake2s.c:24:0:
crypto/include/internal/evp_int.h:118:11: note: 'md_ctrl' declared here
     int (*md_ctrl) (EVP_MD_CTX *ctx, int cmd, int p1, void *p2);
           ^~~~~~~
cc1: all warnings being treated as errors
Makefile:1618: recipe for target 'crypto/blake2/m_blake2s.o' failed
make[4]: *** [crypto/blake2/m_blake2s.o] Error 1
make[4]: Leaving directory '/usr/src/nginx-pagespeed/openssl-1.1.1-pre4'
Makefile:170: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/usr/src/nginx-pagespeed/openssl-1.1.1-pre4'
objs/Makefile:1969: recipe for target '/usr/src/nginx-pagespeed/openssl-1.1.1-pre4/.openssl/include/openssl/ssl.h' failed
make[2]: *** [/usr/src/nginx-pagespeed/openssl-1.1.1-pre4/.openssl/include/openssl/ssl.h] Error 2
make[2]: Leaving directory '/usr/src/nginx-pagespeed/nginx-1.13.12/debian/build-nginx'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/usr/src/nginx-pagespeed/nginx-1.13.12/debian/build-nginx'
debian/rules:50: recipe for target 'build-arch.nginx' failed
make: *** [build-arch.nginx] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

[https://pastebin.com/raw/wP4Js04X](https://pastebin.com/raw/wP4Js04X) - Is there anything I can do to get around it?

**Comment by richsalz** [comment]
How did you configure?  I don't think our flags have the missing-initializer warning.  So maybe just turn that off.

**Comment by levitte** [comment]
It comes from `-Wall`.  With OpenSSL's configuration script, we have `--strict-warnings`, which adds `-Wall`, but also `-Wno-missing-field-initializers`, for obvious reasons...

**Comment by levitte** [comment]
Since this seems to be a nginx build, I'm gonna think that you should talk with the NGINX project first.

**Comment by Graymanflo** [comment]
I just confirmed that this does not happen with openssl-1.0.2n on Nginx 1.13.12, seems like there is a missing initializer in m_blake2s.

**Comment by levitte** [comment]
Considering we ourselves avoid that very warning, *we are perfectly aware of it*, and dismiss it, because we count on the compiler filling up the rest for us.  So if possible, I would say that your best option is to add `-Wno-missing-field-initializers`, at least to the OpenSSL part of the build.

**Comment by Graymanflo** [comment]
I filled a ticket to Nginx as suggested I can get around the error with -Werror removed from auto/cc/gcc in Nginx's source. Although I believe this causes the build to fail ( [https://pastebin.com/ir2DkBTm](https://pastebin.com/ir2DkBTm) ).

**Comment by richsalz** [comment]
This is not an openssl issue.  We *don't want* missing initializer warnings; we turn it off.  So, closing this.

**Comment by Graymanflo** [comment]
Yeah, I figured it would have to be added on your end @richsalz since Nginx's -Werror is making sure there aren't any missing initializers in the compiled dependencies.

**Comment by Graymanflo** [comment]
For anyone with the same issue feel free to take a look at my Nginx bug report with the resolution here: [trac.nginx.org](https://trac.nginx.org/nginx/ticket/1528#comment:3).

For the lazy just do not compile with DPKG_EXPORT_BUILDFLAGS enabled on Debian 9.x and PCRE 2-10.31 as it is conflicting with OpenSSL 1.1.1pre4 compilation. Thanks for the help guys!

**Comment by richsalz** [comment]
No, we don't want the missing initializers warning. We take advantage of the C guarantee about zero-init.

**Comment by FdaSilvaYY** [comment]
I remember an old PR that explicitly NULL-init all the fields of globally-allocated structures, who was not approved because of too much changes and very few added-value.
