### ISSUE TITLE
Openssl decryption

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#5965]
Hi,

I have an encrypted file and the following inputs:
- Encryption algorithm: AES_128_CBC
- Private key
- Certificate file

Using openssl utility, how to I decrypt the above file?
OR
Are these inputs insufficient to decrypt an encrypted file?

Thanks in advance.

Regards,
Amal

**Comment by richsalz** [comment]
Impossible to say.  What is the format of the encrypted file?  Is it s/mime cms or something else?

**Comment by amaljesudas** [comment]
Hi @richsalz,

Thanks for checking my post.
Your question is what troubles me as well.
I just have a encrypted file, the private key file and certificate file and also the encryption algorithm.
Was checking if these inputs are sufficient for us to decide on how to decrypt the file.

In between, I was able to decrypt the same using the smime command as below:
>**openssl smime -decrypt -in D:\1\00000000 -inform DER -out D:\1\Dec -inkey D:\KEY.PEM**

Where 00000000 is the input encrypted file, KEY.PEM is the private key and Dec is he output decrypted file.

Looking at the above decryption, do you think that encrypted file is of s/mime format, since we could decrypt using smime command?
If so, in general does smime command line function work only for files encrypted in s/mime format.

Sorry for putting so many queries, but I am just taking baby steps in openssl and file security.
Hope you understand.

Thanks in advance.

Regards,
Amal

**Comment by richsalz** [comment]
Well, yeah, if the smime command worked than it was an mime file.  Thats the only format it supports. Congrats.  I think we can close this issue now.

**Comment by amaljesudas** [comment]
Thanks @richsalz .
Will work with smime then.

Will close this issue as my queries are now answered.

Regards,
Amal
