### ISSUE TITLE
EVP_DigestSign not algorithm agnostic

### ISSUE THREAD

**Issue by rwfranks** [openssl/openssl#5972]
EVP_DigestSign generates RSA, ED25519, and ED448 signatures in the form
required in the DNS RRSIG record.

However, when attempting to do the same for DSA and ECDSA, the result is
an ASN1 encoded sequence of two bit strings:
        302c
        0214 4343557aabfc96a3c37c0f0695b47ac4fcca40bb
        0214 756832b1c4ba2c9c10440b5798c92954b0a354a4

RFC2536 describes a DSA signature as a simple concatenation of three
fields:
        Field   Size
        -----   ----
         T      1 octet         (length($g)-64)/8
         R      20 octets
         S      20 octets

The T field is utterly useless, but is an RFC2536 required item.

ECDSA signatures contain the R and S fields only:
        Field   Size
        -----   ----
         R      32 or 48 octets
         S      32 or 48 octets

**Comment by levitte** [comment]
You get two *integers* (not the same as bit strings), which conforms to [RFC 3279](https://tools.ietf.org/html/rfc3279), see sections 2.2.2 and 2.2.3.  As for T, you will have to get that from elsewhere.

**Comment by richsalz** [comment]
Closing this.
