### ISSUE TITLE
state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by grizzer** [openssl/openssl#5973]
I'm trying to use the Trust_Cert capability of the Connection object in the Nexpose ruby gem. When I feed the certificate to the object and try to login, I get the following:

"Retrying the request due to SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate). If you see this message please open an Issue on Github with the error."

WIndows 10 Enterprise
irb 0.9.6
openssl 2.1.0
nexpose 7.2.0

Ruby Installer with devkit 2.4.4

**Comment by richsalz** [comment]
You need to open an issue with the Nexpose project, not OpenSSL.
