### ISSUE TITLE
TLSProxy -naccept synchronisation broken

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#5982]
PR #5843 changed the way we synchronise between connects when using "-naccept". This doesn't seem to be working on BSD (tried FreeBSD and OpenBSD). I get failures along the lines of:

````
../test/recipes/70-test_tls13messages.t (Wstat: 0 Tests: 15 Failed: 0)
  Parse errors: Tests out of sequence.  Found (2) but expected (1)
                Tests out of sequence.  Found (3) but expected (2)
                Tests out of sequence.  Found (4) but expected (3)
                Tests out of sequence.  Found (5) but expected (4)
                Tests out of sequence.  Found (6) but expected (5)
````

Looking at the build output I get s_server output intermingled with TLSProxy output:

````
Client cipher list: Processing flight 3
TLS_AES_256_GCM_SHA384 Record 1: (server -> client)
TLS_CHACHA20_POLY1305_SHA256  Content type: APPLICATION DATA
:  Version: TLS1.2
TLS_AES_128_GCM_SHA256  Length: 243
:  Inner content type: HANDSHAKE
ECDHE-ECDSA-AES256-GCM-SHA384  Message type: NewSessionTicket
:  Message Length: 222
ECDHE-RSA-AES256-GCM-SHA384
:Forwarded packet length = 248

DHE-RSA-AES256-GCM-SHA384:Received client packet
ECDHE-ECDSA-CHACHA20-POLY1305Packet length = 26
:Processing flight 4
ECDHE-RSA-CHACHA20-POLY1305 Record 1: (client -> server)
DHE-RSA-CHACHA20-POLY1305  Content type: APPLICATION DATA
:  Version: TLS1.2
ECDHE-ECDSA-AES128-GCM-SHA256  Length: 21
:  Inner content type: APPLICATION DATA
ECDHE-RSA-AES128-GCM-SHA256  [ENCRYPTED APPLICATION DATA]
:  [test]
DHE-RSA-AES128-GCM-SHA256
:Forwarded packet length = 26

ECDHE-ECDSA-AES256-SHA384:Connection closed
ECDHE-RSA-AES256-SHA384:read:errno=0
DHE-RSA-AES256-SHA256:Waiting for client process to close: 32928...
read R BLOCK
ECDHE-ECDSA-AES128-SHA2561..16
:    # Subtest: Default handshake test
ECDHE-RSA-AES128-SHA256    1..34
:    ok 1 - Message type check. Got 1, expected 1
DHE-RSA-AES128-SHA256    ok 2 - Extension presence check (Message: 1 Extension: 4, 0)
````
This is causing the test runner to get confused.

**Comment by dot-asm** [comment]
I wouldn't say that this is problem with -naccept, but rather with interweaving output from multiple programs that confuses TAP parser. It was discussed as potential problem in #5843, but since it worked (and keeps working) on ci and a range on non-linux systems I tried by the time I worked on it, I figured that it's not really a problem. But apparently it is... I'll have a look...

As for attributing it specifically to #5843. I haven't actually looked at TLSProxy till recently, but I reckon that in quite a number of cases it worked circumstantially, just because timings between different components happened to be "right". Recent changes did change timings and more importantly synchronization mechanisms (to more accurate), but it apparently needs some more work specifically in TAP area...

**Comment by mattcaswell** [comment]
> As for attributing it specifically to #5843. I haven't actually looked at TLSProxy till recently, but I reckon that in quite a number of cases it worked circumstantially, just because timings between different components happened to be "right".

Probably you are right with respect to timings in general. In this specific case the code prior to #5843 just did a sleep to give s_server time to finish what it was doing. There's always the chance that we didn't sleep long enough, but it seemed ok. I can see it consistently failing in my BSD environment at the moment. I also tried with a commit just before 5843 went in and it was consistently passing.

**Comment by mattcaswell** [comment]
I have VMs for FreeBSD 10.3 and OpenBSD 5.9

**Comment by dot-asm** [comment]
Keyword turned to be single-processor VM. I managed to reproduce the problem even on FreeBSD 11 if I drop amount of virtual processors to 1. Since #5975 was not approved yet, I've added fix there, so double-check...

**Comment by dot-asm** [comment]
In the context one can wonder if it would be appropriate to provide option to cancel excessive output from s_server/s_client, or do opposite, i.e. provide option to emit excessive output from s_server/s_client. Or detect if standard input is a tty and not produce excessive output...

**Comment by levitte** [comment]
Right now, the amount of output is controlled with `$HARNESS_ACTIVE` and `$HARNESS_VERBOSE`, see for example https://github.com/openssl/openssl/blob/master/test/recipes/70-test_key_share.t#L63-L68

So it seems that to provide some more variety in the output, one might want to have the last argument to `TLSProxy::Proxy->new()` to be more of a flags kind of thing, so one can not only specify that it should be verbose or not, but also to what level.

**Comment by levitte** [comment]
Note that `$HARNESS_ACTIVE` and `$HARNESS_VERBOSE` are created by the TAP modules, so we cannot touch them.  However, I've already started with environment variables having names starting with `HARNESS_OPENSSL_`, which might be an appropriate to get better output control.

**Comment by dot-asm** [comment]
I rather meant canceling specifically from s_client/s_server. Rationale is that in proxy context output from proxy should be sufficient, with V=1 that is. There are -quiet flags, but they have side effects. For example in s_server it suppresses *all* output including ACCEPT (probably should be overridden for dynamic port), and in s_client it implies -ign_eof.

**Comment by dot-asm** [comment]
> in s_server it, [-quiet] suppresses all output including ACCEPT

Well, it actually doesn't suppress output that caused grief in *this* case. Because it goes to stderr, while what's suppressed is stdout...

**Comment by dot-asm** [comment]
Since I could reproduce it and confirm that last addition to #5975 addresses it, I reckon this can be closed.
