### ISSUE TITLE
SMIME encryption/decryption

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#5984]
Hi,

I was just trying out encryption and decryption of a file using openssl smime command.
Just happened to notice that smime command does not support the following ciphers:
**aes_128_gcm** and 
**aes_256_gcm**

I have mentioned the above two as they are of importance to the encryption/decryption I wish to implement finally.
Can anyone let me know if this(not supporting the above ciphers) was done with any specific reason?
If not, can I support the same in my application that will be modeled around smime command?
Please respond even if the reason is an obvious one, as I am just learning the basics of file security and openssl.

Thanks in advance.

Regards,
Amal

**Comment by richsalz** [comment]
AESGCM is not defined for S/MIME.

**Comment by amaljesudas** [comment]
Hi @richsalz ,

Thanks for responding.
One last query:
If I add support for these in the file smime.c [i.e. include add cipher = EVP_aes_128_gcm() and cipher = EVP_aes_256_gcm() to the if-else ladder]; will AES GCM support be enabled?
Or is it wrong to add this support for S/MIME?

Regards,
Amal

**Comment by richsalz** [comment]
I don't know the interaction of S/MIME code with AEAD crypto.  It might work, it might not. It won't be standard.

**Comment by richsalz** [comment]
S/MIME is defined by the IETF. The working group in charge of edits to s/mime is called "lamps"  If you search for "ietf lamps wg" you can find more information.  Consider joining, and working to get it added to the standards.  It's free, just email participation.
