### ISSUE TITLE
Tighten the probality for being a prime

### ISSUE THREAD

**Issue by AnnieYousar** [openssl/openssl#6012]
`include/openssl/bn.h`  sets an error rate of less than 2^-80 for random `b`-bit input, b >= 100.
It seems to be the time to recompute the table 4.4 in the Handbook of Applied Cryptography [Menezes, van Oorschot, Vanstone; CRC Press 1996] for an error rate of 2^-120.
Note that there will be no changes for the number of prime checks for bit size greater than 2535, for lower bit sizes (but greater than 1000) at most three additional Rabin-Miller checks are sufficient. 
Such an adjustment costs almost nothing (as it done only at the end of the pseudo prime check) but gives a better assurance.

**Comment by AnnieYousar** [comment]
My results:
```
/* checks for 2^-120 */   /* checks for 2^-80 */
  (b) >= 2536  ?  2 :      (b) >= 1300  ?  2 :
  (b) >= 1686  ?  3 :      (b) >=  850  ?  3 :
  (b) >= 1268  ?  4 :      (b) >=  650  ?  4 :
  (b) >= 1020  ?  5 :      (b) >=  550  ?  5 :
  (b) >=  856  ?  6 :      (b) >=  450  ?  6 :
  (b) >=  739  ?  7 :      (b) >=  400  ?  7 :
  (b) >=  500  ? 11 :      (b) >=  350  ?  8 :
  (b) >=  450  ? 13 :      (b) >=  300  ?  9 :
  (b) >=  350  ? 17 :      (b) >=  250  ? 12 :
  (b) >=  300  ? 20 :      (b) >=  200  ? 15 :
  (b) >=  250  ? 26 :      (b) >=  150  ? 18 :
  (b) >=  200  ? 28 :     /* b >=  100 */ 27
  (b) >=  150  ? 35 :
  (b) >=  100  ? 47 :
 /* b >=   50 */ 57
```

**Comment by mspncp** [comment]
Hi Annie,

interesting suggestion. Are you able to share the script or code with which you calculated this table? I have a related question: even the technical guidelines [BSI-TR-02102-1](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf?__blob=publicationFile&v=7) of the German Federal Office for Information Security (BSI) still refer (on page 67) to algorithm 4.24 from [71]. So why do you think they are not secure enough? Do you have any information whether the BSI is currently planning to tighten the conditions?


[71] A. Menezes, P. van Oorschot und O. Vanstone. Handbook of Applied Cryptography. CRC Press, 1996.

**Comment by AnnieYousar** [comment]
Hi Matthias,
I made a Magma script based on the functions from Fact 4.48 (p. 147 of HAC) and re-calculate the Tables 4.3 and 4.4. The script can be run at http://magma.maths.usyd.edu.au/calc.

```
f1:= function(k,t)
 if (k ge 2) and (t eq 1) then return RealField(4)!-Log(2,k^2*4^(2-Sqrt(k)));
 else return "";
 end if;
end function;

f2:= function(k,t)
 if ((t eq 2) and (k ge 88)) or ((t ge 3) and (9*t le k) and (k ge 21)) then
  return RealField(4)!-Log(2,k^1.5*2^t*4^(2-Sqrt(t*k))/Sqrt(t));
 else return "";
 end if;
end function;

f3:= function(k,t)
 if ((k le 9*t) and (4*t le k) and (k ge 21)) then
  return RealField(4)!-Log(2,7/20*k/2^(5*t) + 1/7*k^(15/4)/2^(k/2+2*t) +12*k/2^(k/4+3*t));
 else return "";
 end if;
end function;

f4:= function(k,t)
 if (4*t ge k) and (k ge 21) then
  return RealField(4)!-Log(2,1/7*k^(15/4)/2^(k/2+2*t));
 else return "";
 end if;
end function;

for i:=512 to 8192 by 256 do
 s:="";
 for t:=1 to 7 do
  rs:=Sprintf("%o ",f1(i,t)); s*:=rs;
  rs:=Sprintf("%o ",f2(i,t)); s*:=rs;
  rs:=Sprintf("%o ",f3(i,t)); s*:=rs;
  rs:=Sprintf("%o",f4(i,t)); s*:=rs;
  s*:=": ";
 end for;
 printf "%4o : %o\n",i,s;
end for;

```
Concerning your second question, the Miller-Rabin test is fine. It is the number of MR tests that OpenSSL makes to ensure with a small error probability that a pseudo prime is a prime.  Have a look at p. 67 of BSI-TR-02102-1: It says that 4 iterations of MR give prob of 2^-109 for a 1000 bit candidate. But OpenSSL does only 3, as required by prob of 2^-80. For  2^-120 (required by the BSI, cf. p. 8, beyond 2022) five MR test are sufficient.

**Comment by AnnieYousar** [comment]
I oversaw the third question: " Do you have any information whether the BSI is currently planning to tighten the conditions?"
No.

**Comment by kroeckx** [comment]
So I think what you're saying is that if we want to generate something at the X bit security level, the probability of it not being prime should be 2^-X?

On page it says
```
(ii) (Worst case) In order to restrict the probability that a fixed number p is identified as a
prime number by means of the Miller-Rabin algorithm, although it is a composite number, to
1/2^100, the algorithm must be called up 50 times with bases a1,...,a,50 ∈{2,3,...,p−2} that
were chosen independently of each other with respect to the uniform distribution.  See Section
B.4 for recommended methods for the calculation of uniformly distributed random numbers in
{2,3,...,p−2}
```

It's not clear to me when we need to use that, and it also says:

Page 67 also says: 
```
In accordance with [42], Appendix F.2, it is also recommended in this
Technical Guideline to perform a verification of the prime number property with 50 rounds of the
Miller-Rabin primality test when generating prime numbers which are to be used in particularly
security-critical functions in a cryptosystem or the generation of which is not very time-critical.
This applies, for example, to prime numbers which are generated once as permanent parameters
of a cryptographic mechanism and are not changed over a longer period of time or possibly used
by many users.
```

Does that mean that for instance for RSA and DH generation, we should use 50 rounds instead to reach 2^-100 or 60 to reach 2^-120?

The current code for RSA key generation just does:
```
            if (!BN_generate_prime_ex(prime, bitsr[i] + adj, 0, NULL, NULL, cb))
```

We could add an additional BN_is_prime_fasttest_ex() call if needed.

**Comment by kroeckx** [comment]
Reading FIPS 186-4, it's seems to be the case where the distribution is not uniform, or where you want to check something generated by someone else, and it's mostly for DSA. For RSA it should be fine.

**Comment by AnnieYousar** [comment]
I read the chap. 4 of HAC: http://cacr.uwaterloo.ca/hac/about/chap4.pdf, which is referred by OpenSSL in `include/openssl/bn.h`. My target was only to re-calculate the table in line 106 - 130 for `BN_prime_checks`, based on a stronger probability assumption 2^-80 => 2^-120 with the means of HAC.  I've no ideas for changes in the prime search procedure `BN_generate_prime_ex`.

**Comment by kroeckx** [comment]
4.49 there say:
```
In practice, one is usually willing to tolerate an error probability of
(1/2)^80 when using Algorithm 4.44 to generate probable primes
```

If possible I would like to have a motivation for changing that from 80 to 120.

**Comment by AnnieYousar** [comment]
The text in 4.49 of HAC is from 1996, where MD5 and RSA-768 were not broken yet. In Note 51 on p. 33 of http://sogis.org/documents/cc/crypto/SOGIS-Agreed-Cryptographic-Mechanisms-1.0.pdf even 125 is required.

**Comment by AnnieYousar** [comment]
Good point. Looks like to fix the number of MR test at, e.g. 5 for all key lengths. I'll re-calculate the errors probs based on this assumption.

**Comment by mspncp** [comment]
Annie, since you proposed it, would you like to create your own pull request for it? If not, I'll yield precedence to Kurt, but would be willing to do it if Kurt is too busy with other things.

**Comment by mspncp** [comment]
Sidenote: we should not forget to do detailed performance tests for this change in order not to repeat previous mistakes.

**Comment by AnnieYousar** [comment]
4,5,6 MR-tests give the following security levels
```
            MR tests:    4    5    6
plen:   512, seclevel:  73   83   92 bits
plen:   768, seclevel:  93  105  116 bits
plen:  1024, seclevel: 109  124  137 bits
plen:  1536, seclevel: 137  155  171 bits
plen:  2048, seclevel: 161  182  200 bits
plen:  3072, seclevel: 201  227  249 bits
plen:  4096, seclevel: 235  264  291 bits
plen:  6144, seclevel: 292  328  361 bits
plen:  8192, seclevel: 340  382  420 bits
plen: 11264, seclevel: 402  451  496 bits
```

**Comment by kroeckx** [comment]
So it seems that 4 is even already more than enough and 3 might be enough for all of them. Do you also have a formula that turns the bit length into the security length? I think I've at least seen it once.

**Comment by AnnieYousar** [comment]
Kurt, please take into account that during a prime search every time a sieved out candidate is checked (genrsa prints a dot "."), only one MR test applies. All composite candidates will fail the MR test with the first witness. The subsequent MR test will be needed only at the end, to be sure that the candidate is a prime with higher probability. Therefore it doesn't hurt to make an extra test to acchieve a higher assurance.
The table above says that for a 2^-128 error level for an RSA-2048 key you must pass six tests. With five test you get only 2^-124 for each prime and with four test only 2^-109. So three are not enough.

**Comment by kroeckx** [comment]
Oh, you're saying for a 2048 bit RSA key, for which we should reach the 112 bit level, we want to reach the 112 bit level for each of the 1024 bit primes?

I'm getting the 112 bit from what BN_security_bits() currently uses, which is based on the NIST recommendation (see https://www.keylength.com/en/4/), which gives:
1024 80
2048 112
3072 128
7680 192
15360 256

Anyway, like you explained, the + is at the end and doesn't take much time. I have no problem doing 6 for those larger key lengths, even when we could do with less.

**Comment by AnnieYousar** [comment]
Have a look at http://www.bouncycastle.org/jira/browse/BJA-694. BouncyCastle made MR tests before also according to the key size, which is wrong. You have to consider the prime length.

**Comment by kroeckx** [comment]
Do you have to code that was used to generate that?

**Comment by kroeckx** [comment]
I'm trying to understand the algorithm from fips 186-4 in F.1. Should you stop when Pk,t is < Ptarget for all values of M, or any?

**Comment by AnnieYousar** [comment]
> I'm trying to understand the algorithm from fips 186-4 in F.1. Should you stop when Pk,t is < Ptarget for all values of M, or any? I think it at least says any.
Yes. If you find an M, such that p_{k,t} < p_{target} you leave the M cycle and the t cycle. this is the Magma code that can be run at http://magma.maths.usyd.edu.au/calc/
```
securitybits:=128;
//for k:=16 to 6000 by 1 do
for k in [48,99,149,198,247,291,341,447,479,691,782,906,1080,1345,1794,2719,5908] do
  for t:=1 to 65 do
    for M:=3 to Floor(2*Sqrt(k-1)-1) do
      S:=0;             // Summe über m
      for m:=3 to M do
        s:=0;           // Summe über j
        for j:=2 to m do
          s+:=(RealField(32)!2)^-(j+(k-1)/j);
        end for;
        S+:=2^(m-(m-1)*t)*s;
      end for;
      A:=2^(k-2-M*t);
      B:=8*(Pi(RealField(32))^2-6)/3*2^(k-2)*S;
      pkt:=2.00743*Log(2)*k*2^-k*(A+B);
      seclevel:=Floor(-Log(2,pkt));
      if seclevel ge securitybits then
        printf "k: %5o, security: %o bits  (t: %o, M: %o)\n",k,seclevel,t,M;
        break;
      end if;
    end for;
    if seclevel ge securitybits then break; end if;
    end for;
end for;

```

**Comment by AnnieYousar** [comment]
Kurt, Matthias, Rich, thanks for commenting. The issue is solved with Kurt's commit #6075.

**Comment by richsalz** [comment]
More importantly, thanks for raising the issue and helping improve OpenSSL!

**Comment by AnnieYousar** [comment]
I'll be back soon.
