### ISSUE TITLE
OpenSSL 1.0.2f seems to break OpenSMTPD 5.7.3p1 (Portable) in x86 (32-bit) 

### ISSUE THREAD

**Issue by mrkiko** [openssl/openssl#602]
systems

While for some reasons I can't obtain a coredump related to the problem, I 
observed that upgrading to OpenSSL 1.0.2f causes OpenSMTD Portable to 
break on my 32-bit X86 system.
Rebuilding the software did not fix the problem.
Going back to OpenSSL 1.0.2e fixes the problem, advancing to OpenSSL 
1.0.2f reliably allows me to reproduce the issue.

For those interested in off-topic OpenSMTPD logs, they can now be found 
here:
http://cxg.de/_c7d605.htm

It's very possible I am wrong: I posted this issue due to the fact that it 
seems to me that the segfault happens when initializzing tls 
(tls+auth:///hostname...)
Thanks guys for your work, patience and passion.

**Comment by mattcaswell** [comment]
That's not a lot to go on ;-) I think we're going to need that coredump to make any headway with this issue.

**Comment by mrkiko** [comment]
@mattcaswell thank you for the reply and kindness.
Unfortunately I don't have that system at hand. But I remember I had 
somedifficulties: because the coredump wasn't generated. I know it would be 
very much needed.
Sorry.

**Comment by mattcaswell** [comment]
Ok. I'm going to close this for now - there's really nothing we can do without more information. If this crops up again, and we can get some more useful debugging info then we can open a new issue.

**Comment by mrkiko** [comment]
That's fine. thank you.
