### ISSUE TITLE
Renamed public symbols

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#6030]
Inspired by #6023, I scanned the global headers for removed or renamed public symbols. That is, I ran

```
colordiff -ru openssl-1.1.0/include/openssl/ openssl/include/openssl | less
```

and did a manual review of the output, focusing on all removed lines which contained a define or a typedef.  This is all I found

### Renamed STORE defines

```
--- openssl-1.1.0/include/openssl/err.h 2018-03-05 01:38:58.784118561 +0100
+++ openssl/include/openssl/err.h       2018-04-17 07:15:57.462111009 +0200

-# define ERR_LIB_STORE           44
+# define ERR_LIB_OSSL_STORE      44

-# define STOREerr(f,r) ERR_PUT_error(ERR_LIB_STORE,(f),(r),OPENSSL_FILE,OPENSSL_LINE)
+# define OSSL_STOREerr(f,r) ERR_PUT_error(ERR_LIB_OSSL_STORE,(f),(r),OPENSSL_FILE,OPENSSL_LINE)
 
+# define SM2err(f,r) ERR_PUT_error(ERR_LIB_SM2,(f),(r),OPENSSL_FILE,OPENSSL_LINE)
+# define OSSL_STOREerr(f,r) ERR_PUT_error(ERR_LIB_OSSL_STORE,(f),(r),OPENSSL_FILE,OPENSSL_LINE)
```

@levitte, these renames should be uncritical, because the STORE api was not implemented yet in 1.1.0, right? The only notable thing is that OSSL_STOREerr() is defined twice. (This happened in 71a5516dcc8). Fixed in #6029.

### Renamed SSL_CTRL's

```
--- openssl-1.1.0/include/openssl/ssl.h 2018-03-28 00:32:43.730861753 +0200
+++ openssl/include/openssl/ssl.h       2018-04-19 21:58:43.591475783 +0200

-# define SSL_CTRL_GET_CURVES                     90
-# define SSL_CTRL_SET_CURVES                     91
-# define SSL_CTRL_SET_CURVES_LIST                92
-# define SSL_CTRL_GET_SHARED_CURVE               93
+# define SSL_CTRL_GET_GROUPS                     90
+# define SSL_CTRL_SET_GROUPS                     91
+# define SSL_CTRL_SET_GROUPS_LIST                92
+# define SSL_CTRL_GET_SHARED_GROUP               93
```

Fixed in #6203
  

### Removed PEM typedefs
 
 
```
--- openssl-1.1.0/include/openssl/pem.h 2018-03-05 01:38:58.797118691 +0100
+++ openssl/include/openssl/pem.h       2018-03-28 00:32:00.002420874 +0200
 
-typedef struct pem_recip_st {
-    ...
-} PEM_USER;

-typedef struct pem_ctx_st {
-    ...
-} PEM_USER;
```

OK (unused in 1.1.0)

**Comment by levitte** [comment]
I was wondering what the STOREerr macro in 1.1.0 was about, 'cause like you say, there is no such module in 1.1.0... But, there [was actually an experimental one in 1.0.2](https://github.com/openssl/openssl/tree/OpenSSL_1_0_2-stable/crypto/store)! (no, don't try it)
It seems that our clean out of that one wasn't quite complete. 

So yeah, all good, that difference can be ignored (apart from the duplicate)

**Comment by levitte** [comment]
I wonder what `PEM_USER` was about... That probably lost in history, though.

**Comment by mspncp** [comment]
It is. At least it is already present in d02b48c63a58ea4367a0e905979f140b7d090f86. So probably only @t-j-h  can tell us...

```
~/src/openssl$ git log -SPEM_USER | grep commit
```

commit f77524524548be9740b143bccfde7565493ae78e
commit 849c80bc5ddb122e06effb39a7a0be2bf2cf4cbe
commit 8d7ed6ff90581cf34a00d59d301d8cc7da2efc54
commit d02b48c63a58ea4367a0e905979f140b7d090f86
```

**Comment by mspncp** [comment]
A final question @levitte: I did not deal with the error code defines generated by `mkerr.pl`, since they were moved around too much. It would have been just too tedious. The only feasable solution which I currently see would be to filter and sort the symbols into two separate files, one for the removed lines and on for the added ones, and then do a side-by-side diff. Do you think it's wort the effort?

**Comment by mspncp** [comment]
Another possibility would be to hack the `mkerr.pl` script (for master and 1.1.0) such that it dumps a copy of each generated symbol into a separate file. These could be sorted and compared easily. Thoughts?

**Comment by levitte** [comment]
Error codes are collected in `crypto/err/openssl.txt`, as long as the names and numbers are consistent in that file, we're good.  We do allow renaming of the error macros.

**Comment by levitte** [comment]
`crypto/err/openssl.txt` is new in master, yes.  In 1.1.0, the database was the err number macro definitions themselves, which was somewhat flawed (i.e. more difficult to parse).

> But what if applications check for explicit error codes?

The error codes are more for printout and human consumption.  Also, the *numbers* should stay the same even if the *name* changes, so this should be safe from an ABI point of view, unless there are new errors.  But yeah, checking the exact error codes is fragile and isn't encouraged.
(from a personal point of view, I don't quite agree with this, but it's been the attitude of the project for a long time, and isn't enough of a bother to make a stink)

**Comment by mspncp** [comment]
Closing, since #6023 and #6029 have been merged.
