### ISSUE TITLE
Ciphers supported by CMS

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#6034]
Hi,

Was checking CMS utility source code.
Saw that there are around 12 ciphers(and 4 wrap ciphers) that are currently supported by CMS.
I could not find any list of CMS supported algorithms from IETF RFC  links.
Also, cipher definition of CMS utility asks us to check enc for list of supported ciphers.
If we check enc command, it lists a larger number of ciphers.
Could anyone shed light on why only 12(or 16) ciphers are supported by CMS utility?

Thanks in advance.

Regards,
Amal

**Comment by richsalz** [comment]
Because those are the only ones defined by IETF RFC's *at the time.*  There are new ciphers being added in the IETF LAMPS working group.  As for which RFC's define ciphers, you'll have to use a search engine.

**Comment by amaljesudas** [comment]
Hi @richsalz ,

Thanks for the reply.
I did a search for RFC's that define ciphers, but was not able to find any that list ciphers for CMS.
The nearest I could get is the below one:
[https://tools.ietf.org/html/draft-irtf-cfrg-cipher-catalog-01](url)

Also, I tried to join the LAMPS group, but the mail login option did not work.

So, as you mentioned, CMS utility supports ciphers that were mentioned in RFC at the time of utility development.
I will stick to that info.
In between, if possible, please let me know if there is some place where I could find more info.
 
Regards,
Amal

**Comment by kaduk** [comment]
@amaljesudas did you want RFCs 3370 and 5754?
Also, what about https://www.ietf.org/mailman/listinfo/spasm (the list name differs from the WG name for historical reasons; follow the link from https://datatracker.ietf.org/wg/lamps/about/)

**Comment by amaljesudas** [comment]
Hi @kaduk ,

Thank you for the link.
I was able to subscribe to SPASM mail list.
Will try posting my query to the group.

Regards,
Amal
