### ISSUE TITLE
bug report: OpenSSL 1.0.2m: Segment fault on AIX at freelist_extract

### ISSUE THREAD

**Issue by sandeepumeshbe** [openssl/openssl#6039]
Hello

We have a 64-bit mutithreaded application running on AIX with openSSL 1.0.2m and this consistently coredumps with the below stack:

Segmentation fault in freelist_extract at 0x900000005154134 ($t19)
0x900000005154134 (freelist_extract+0x84) 41820078 beq 0x9000000051541ac (freelist_extract+0xfc)
(dbx) where
freelist_extract() at 0x900000005154134
ssl3_setup_read_buffer() at 0x9000000051543c0
ssl3_setup_buffers() at 0x900000005154448
ssl23_get_client_hello() at 0x90000000517ffa0
ssl23_get_server_method() at 0x900000005180608
SSL_accept() at 0x90000000513e680
do_ssl_hs(int)(conn_nbr = 19), line 4467 in "TcpSvr.cpp"
threaded_work__ssl_hs(void*)(parms = 0x0fffffffffffe4bc), line 4351 in "TcpSvr.cpp"
(dbx)

Typically dumps is seen when ~26 threads are running. Is there any hardlimit set by openssl on the number of threads that can run ?
Also please provide us with any other pointers in resolving this.

Configuration option used:
./Configure enable-ssl2 -DSSL_ALLOW_ADH --prefix=/usr --openssldir=/var/ssl no-idea no-rc5 no-symlinks shared threads aix64-xlc_r

And in Configure file we have :
"aix64-xlc_r", "cc:-q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst::-qthreaded -D_THREAD_SAFE:AIX::SIXTY_FOUR_BIT_LONG RC4_CHAR:${ppc64_asm}:aix64:dlfcn:aix-shared::-q64 -qmkshrobj:.so.\$(SHLIB_MAJOR).\$(SH
LIB_MINOR)::-X 64",

Thanks

Regards
Sandeep

**Comment by richsalz** [comment]
Did you set the locking callbacks properly?
It is possible, but unlikely, that there is a bug in OpenSSL.  It is more likely a bug in your program not locking and releasing things at the right time.  Can you run it under valgrind or asan or something?

**Comment by FdaSilvaYY** [comment]
See #5659, and AIX PPC build issue #5659
There is something between AiX, xlc and stack.c code

**Comment by dot-asm** [comment]
I find it hard to imagine that it has anything to do with stack.c thing. It looks as genuine synchronization problem, and in 1.0.2 context it's actually application's responsibility. To provide callbacks that OpenSSL would use to synchronize access to shared structures. So question still remains "Did you set the locking callbacks properly?"

**Comment by yapingcat** [comment]
> Hello
> 
> We have a 64-bit mutithreaded application running on AIX with openSSL 1.0.2m and this consistently coredumps with the below stack:
> 
> Segmentation fault in freelist_extract at 0x900000005154134 ($t19)
> 0x900000005154134 (freelist_extract+0x84) 41820078 beq 0x9000000051541ac (freelist_extract+0xfc)
> (dbx) where
> freelist_extract() at 0x900000005154134
> ssl3_setup_read_buffer() at 0x9000000051543c0
> ssl3_setup_buffers() at 0x900000005154448
> ssl23_get_client_hello() at 0x90000000517ffa0
> ssl23_get_server_method() at 0x900000005180608
> SSL_accept() at 0x90000000513e680
> do_ssl_hs(int)(conn_nbr = 19), line 4467 in "TcpSvr.cpp"
> threaded_work__ssl_hs(void*)(parms = 0x0fffffffffffe4bc), line 4351 in "TcpSvr.cpp"
> (dbx)
> 
> Typically dumps is seen when ~26 threads are running. Is there any hardlimit set by openssl on the number of threads that can run ?
> Also please provide us with any other pointers in resolving this.
> 
> Configuration option used:
> ./Configure enable-ssl2 -DSSL_ALLOW_ADH --prefix=/usr --openssldir=/var/ssl no-idea no-rc5 no-symlinks shared threads aix64-xlc_r
> 
> And in Configure file we have :
> "aix64-xlc_r", "cc:-q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst::-qthreaded -D_THREAD_SAFE:AIX::SIXTY_FOUR_BIT_LONG RC4_CHAR:${ppc64_asm}:aix64:dlfcn:aix-shared::-q64 -qmkshrobj:.so.$(SHLIB_MAJOR).$(SH
> LIB_MINOR)::-X 64",
> 
> Thanks
> 
> Regards
> Sandeep
@sandeepumeshbe 
 hi ,do you slove this problem ? now, i see the same problem. i have already set the locking callbacks properly, but openssl still crashed,
Crashing frame :
#0  0x00007f8cfb47ac19 in freelist_extract.isra.0 () from /lib64/libssl.so.10
#1  0x00007f8cfb47b745 in ssl3_setup_read_buffer () from /lib64/libssl.so.10
#2  0x00007f8cfb47b8b9 in ssl3_setup_buffers () from /lib64/libssl.so.10
#3  0x00007f8cfb47cf25 in ssl23_get_client_hello () from /lib64/libssl.so.10
#4  0x00007f8cfb47d5a8 in ssl23_accept () from /lib64/libssl.so.10
#5  0x00007f8ce45c6aeb in completeHandshake (ctx=0x7f8c640018e0) at ../source/port/aio-socket-epoll.c:551
#6  0x00007f8ce45c6eed in epoll_accept (ctx=0x7f8ce8021bb0, flags=1, error=0) at ../source/port/aio-socket-epoll.c:610
#7  0x00007f8ce45c674d in aio_socket_process (timeout=64) at ../source/port/aio-socket-epoll.c:434
#8  0x00007f8ce45c5c66 in aio_worker (param=0x0) at src/aio-worker.c:19
#9  0x00007f8cfd21de25 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f8cfc72b34d in clone () from /lib64/libc.so.6

my Openssl version : OpenSSL 1.0.2k-fips
i use CRYPTO_set_locking_callback CRYPTO_set_id_callback  CRYPTO_set_dynlock_create_callback
CRYPTO_set_dynlock_lock_callback CRYPTO_set_dynlock_destroy_callback to set  locking_function and threadid_func.

So if you slove this problem ,could you help me, i am helpless.  Thank you

**Comment by sandeepumeshbe** [comment]
You need to ensure that application links with same shared object.
Based on the openssl version, it is possible that openssl provider can provide .so.1.0.2, .so.1.0.1 and henceforth. Please ensure that application links the same shared object.

In my case, application was linking with multiple versions of openssl shared object : /usr/lib/libcrypto.a(libcrypto.so.1.0.0) and/usr/lib/libcrypto.a(libcrypto.so.1.0.2)

**Comment by kaduk** [comment]
At this point 1.0.2 is EOL, so it's unlikely this will get much attention from the dev team.

**Comment by yapingcat** [comment]
> You need to ensure that application links with same shared object.
> Based on the openssl version, it is possible that openssl provider can provide .so.1.0.2, .so.1.0.1 and henceforth. Please ensure that application links the same shared object.
> 
> In my case, application was linking with multiple versions of openssl shared object : /usr/lib/libcrypto.a(libcrypto.so.1.0.0) and/usr/lib/libcrypto.a(libcrypto.so.1.0.2)

Thank you for your reply. i will check it.    Thanks a lot

**Comment by t8m** [comment]
1.0.2 branch is out of regular support. Closing.
