### ISSUE TITLE
Is there a way of checking if my public key created outside openssl is correct?

### ISSUE THREAD

**Issue by aSedmakHC** [openssl/openssl#6056]
Hi everyone,

this may be a stupid question but I haven't found an answer to this. I have my 22-byte public key created using sect163k1 elliptic curve and want to check if it is authentic. I've found the ECDSA_verifty and ECDSA_do_verify functions which should do what I want but I have a problem with EC_KEY object.

How can I transform my public key (uint8_t *) to EC_KEY object and then check if it is valid using correct elliptic curve? I've been searching for a few days now and can't figure it out.

Thanks in advance!
Adam

**Comment by richsalz** [comment]
How did you create your public key?  (It doesn't seem like it was with OpenSSL).  And you can't create just a public key, you create a keypair. To import keys, look at  ```EC_KEY_oct2key``` The "verify" functions don't do what you think -- they are verifying a *signature.*

**Comment by aSedmakHC** [comment]
I need to check if zigbee OTA upgrade image is valid. Zigbee message has ECDSA signature and certificate on it. So public / private keypair is created somewhere else and I need to check if my public key is correct so I can accept or discard an image.

**Comment by richsalz** [comment]
So it's not your public key, it's the public key you got from the cert in the update, I see.  The verify functions should be able to take the cert and the content and verify the signature.  Closing this issue.
