### ISSUE TITLE
Only the first trust certificate in CAfile is considered, when multiple certificates have the same subject and SAN extension

### ISSUE THREAD

**Issue by MarcBeckerSAP** [openssl/openssl#6058]
I am experiencing issues when using certificates in my trust store that have the same subject and SAN extension. It seems like the order of the trust certificates in the CAfile seem to matter in this case. Only the first certificate is used for validation during the SSL handshake. The issue is easily reproducible by following the steps given below. In my example I am starting a Node.js server. However the issue is not on server side but on client side, so the issue should be reproducible with any SSL server providing the same certificates.

**1. Create two different certificates with the same subject and SAN extensions to reproduce the issue:**
Put the following into a bash script and run it to generate the certificates:
```bash
#!/bin/bash
openssl req -x509 -sha256 -newkey rsa:4096 -nodes \
  -keyout key.pem \
  -subj "/CN=localhost/C=DE/ST=BW/O=SAP" -days 365 \
  -extensions SAN \
  -config <(cat /etc/ssl/openssl.cnf \
    <(printf "\n[SAN]\nsubjectAltName=DNS:localhost")) \
  -out cert.pem

openssl req -x509 -sha256 -newkey rsa:4096 -nodes \
  -keyout key2.pem \
  -subj "/CN=localhost/C=DE/ST=BW/O=SAP" -days 365 \
  -extensions SAN \
  -config <(cat /etc/ssl/openssl.cnf \
    <(printf "\n[SAN]\nsubjectAltName=DNS:localhost")) \
  -out cert2.pem

cat cert.pem cert2.pem > correct-order.pem
cat cert2.pem cert.pem > incorrect-order.pem
```

**2. Start the server**
Put the following into a file called server.js:
```javascript
const fs = require("fs"),
      https = require("https");

var privateKey = fs.readFileSync('key.pem').toString();
var certificate = fs.readFileSync('cert.pem').toString();

var server = https.createServer({key: privateKey, cert: certificate}, function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
});
server.listen(8000);
```

Start the server with the following command:
`node server.js &`

**3. Perform an SSL handshake with the server using the two CAfiles:**
The following command uses a CAfile, which contains the certificate that is being used by the server first and another certificate with the same subject and SAN extension second. The SSL handshake succeeds.
`openssl s_client -connect localhost:8000 -CAfile correct-order.pem`

The following provides a CAfile with the same two certificates as used in the command before, but in different order. The certificate, that is not being used by the server comes first, while the correct trust certificate comes second. **The SSL handshake fails unexpectedly**:
`openssl s_client -connect localhost:8000 -CAfile incorrect-order.pem`

I was able to reproduce the issue using **openssl version 1.0.2o**
Please note that when omitting the SAN extension from the certificates during creation, the issue is **NOT** reproducible and the order does not seem to matter anymore.

**Comment by MarcBeckerSAP** [comment]
Ok, but why is only the first certificate that matches the SAN considered? Wouldn't it make sense to search for other possible matches, in case the certificate can't be used to validate the certificate during the SSL handshake?
I think it is a little inconsistent in comparison to the behaviour if no SANs are present. Although the CN (I guess?) is used to find an appropriate certificate, not only the first, but all potential matches, are used to try to validate certificate during the SSL handshake in this case.

**Comment by richsalz** [comment]
Multiple certs with the same host is not common. One can make the argument that the "older" cert should be revoked or expired, even.  We don't support that use-case.
