### ISSUE TITLE
IPv6 support for openssl s_client

### ISSUE THREAD

**Issue by peterthomassen** [openssl/openssl#6061]
Thank you for building this great library!

OpenSSL does not seem to support IPv6 for `openssl s_client`. I'd like to suggest adding it.

**Comment by richsalz** [comment]
It's in master right now, and will be in the next release.
Thanks for the kind words.

**Comment by kroeckx** [comment]
It's also already in 1.1.0?

**Comment by richsalz** [comment]
oops yeah i was looking at the wrong branch.
