### ISSUE TITLE
Openssl v1.0.2e: t1_lib.c: Check for incorrect return value leading to SSL negotiation failure

### ISSUE THREAD

**Issue by NehaChatrath** [openssl/openssl#607]
Hello,
I upgraded from OpenSSL version v1.0.2 to v1.0.2e and started observing issues in SSL negotiations randomly.
I observed that as part of v1.0.2e, while processing CLIENT_HELLO message in t1_lib.c, extra checks for checking return value of HMAC_Update() have been added while decrypting the  ticket IE.   
Following is the code flow:
ssl3_get_client_hello()
    |-ssl_get_prev_session
      |-tls1_process_ticket
        |-tls_decrypt_ticket
          |-HMAC_Update   --------> _Check for this function to return a value has been added as part of OpenSSL v1.0.2e._
            |-EVP_DigestUpdate   
              |-ctx->update(ctx, data, count)
              
The update function in EVP_MD_CTX has a return type void.

Thus, HMAC_Update function ends up checking for random values. When the value is greater than 0, SSL negotiations are successful but for other values, the failure is percolated to the calling functions which typically leads to ssl3_accept() failures in my case.

As part of the fix, I suggest removing the check for checking the return type of HMAC_Update function in tls_decrypt_ticket().

Attached is the patch for the same. 
[diff.txt](https://github.com/openssl/openssl/files/113237/diff.txt)

Thanks and regards
Neha Chatrath

**Comment by mattcaswell** [comment]
> The update function in EVP_MD_CTX has a return type void.

But it doesn't??? See:

````
struct env_md_ctx_st {
    const EVP_MD *digest;
    ENGINE *engine;             /* functional reference if 'digest' is
                                 * ENGINE-provided */
    unsigned long flags;
    void *md_data;
    /* Public key context for sign/verify */
    EVP_PKEY_CTX *pctx;
    /* Update function: usually copied from EVP_MD */
    int (*update) (EVP_MD_CTX *ctx, const void *data, size_t count);
} /* EVP_MD_CTX */ ;
````
There must be some other reason you are seeing random values coming back??

**Comment by mattcaswell** [comment]
See also:
https://rt.openssl.org/Ticket/Display.html?id=4290&user=guest&pass=guest

**Comment by NehaChatrath** [comment]
So here is the further explanation. 
In tls_decrypt_ticket(), 
HMAC_Init_ex() is invoked with "pointer to md" as one of the input parameterS of type "EVM_MD". The value of "md" is the value returned by tlsext_tick_md().
As per OpenSSL code:
 #   ifdef OPENSSL_NO_SHA256
** define tlsext_tick_md  EVP_sha1
else
define tlsext_tick_md  EVP_sha256**
#   endif

Thus, "md" variable would either point to EVP_sha1 or EVP_sha256 which further points to sha1_md or sha256_md structures.  If you look further into these structures, you will come across that both SHA1_Update() and SHA256_Update()  have a return type as "void".

In EVP_DigestInit_ex() (which is invoked from HMAC_Init_ex()) , line 219:
 ctx->update = type->update;   --------> _update function points to either SHA1_Update() or SHA256_Update()._

Thus, return value of SHA1_Update() or SHA256_Update() functions are checked in  tls_decrypt_ticket() as part of line:
================================================
/* Check HMAC of encrypted ticket */
    if (**HMAC_Update(&hctx, etick, eticklen) <= 0**
             || HMAC_Final(&hctx, tick_hmac, NULL) <= 0) {

**Comment by kaduk** [comment]
Sorry, why do you think SHA1_Update() and SHA256_Update() have return type void?

They are implemented via the HASH_UPDATE function in md32_common.h, with HASH_UPDATE being defined as a macro to the appropriate value before md32_common.h is included, e.g., in crypto/sha/sha_locl.h.  HASH_UPDATE has return type int.

**Comment by kroeckx** [comment]
struct evp_md_st (EVP_MD) has for the update function:
    int (*update) (EVP_MD_CTX *ctx, const void *data, size_t count);

The sha256_md variable fills that in as "update256", which is:
static int update256(EVP_MD_CTX *ctx, const void *data, size_t count)
{
    return SHA256_Update(EVP_MD_CTX_md_data(ctx), data, count);
}

And SHA256_Update itself is the HASH_UPDATE as already pointed
out, which also returns in int.

If anything of those would return void instead of int, the
compiler would complain about that.

Also, HASH_UPDATE() always returns 1.

**Comment by richsalz** [comment]
@NehaChatrath is this still an issue?  What platform are you running on?

**Comment by mattcaswell** [comment]
No further input. Closing this ticket.
