### ISSUE TITLE
Cannot create directory C:/Program Files (x86)/Common Files/SSL: No such file or directory

### ISSUE THREAD

**Issue by kohldampfer** [openssl/openssl#6072]
I am building OpenSSL on a Windows machine. When I run the configure script, I am doing it like this:

`path\to\perl.exe Configure VC-WIN32 enable-static-engine no-zlib --prefix="D:\target\dir"`

After invoking `nmake install VERBOSE=1`, OpenSSL compiles and links and afterwards, I get at some point this error message and the build stops:

> Cannot create directory C:/Program Files (x86)/Common Files/SSL: No such file or directory

It's OK that the build stops at this point. In my opinion, when I use the `--prefix` option, then the `install` part should not install / copy some files into another directory than I set through the `--prefix` option. So, for me, this is a bug.

**What do you think about this?**

Edit:
I compile OpenSSL version `1.1.0h`.

**Comment by kohldampfer** [comment]
Possible workaround is to add the parameter `--openssldir="D:\target\dir\SSL"` when calling the `perl.exe` command.

**Comment by levitte** [comment]
Yes.  Since 1.1.0, `--openssldir` no longer depends on `--prefix`.

**Comment by al1970** [comment]
There's another solution:
start the 'mingw64.exe' or the 'cmd.exe' (depending on the build toolchain) with administration privileges.
The problem in directory creation is due to lack of administration right.

**Comment by Sami-Veni** [comment]
I got the similar error doing the same using VS2019. I ran Developer cmd for VS2019 with administrative privilege and it worked fine.

**Comment by AntonDueck** [comment]
only admin can write to C:/Program Files (x86)/Common Files/SSL. so you habe to define the --openssldir or have the acces rights
