### ISSUE TITLE
Decrypt fail with TLSv1.2, ECDHE-RSA-AES128-SHA256

### ISSUE THREAD

**Issue by cozmavladimir** [openssl/openssl#6076]
Openssl version 1.1.0h
Steps to reproduce:
openssl s_client -connect www.raiffeisenonline.ro:443

GET /eBankingWeb/dtagent_ICA23bjprx_7000000061013.js HTTP/1.1
Host: www.raiffeisenonline.ro
User-Agent: curl/7.51.0
Accept: */*

Javascript file gets corrupted with AES_CBC, but works fine with AES_GCM.

[wrong-output.txt](https://github.com/openssl/openssl/files/1946055/wrong-output.txt)

**Comment by mattcaswell** [comment]
This appears to be a server side issue. I was able to recreate the above. The decryption seems to be working just fine, its just that the javascript sent consists of the characters ".ajaxS" repeated over and over again. Running this through wireshark reveals that the server is sending vast quantities of (apparently correctly encrypted) application data packets. I'd suggest you contact the server operator - this does not appear to be an OpenSSL issue.

**Comment by rafyyy** [comment]
Hi, 

@mattcaswell i did the same request with LibreSSL 2.5.5, same protocol and cipher and it worked correctly.
[libressl_request.txt](https://github.com/openssl/openssl/files/1946367/libressl_request.txt)

**Comment by mattcaswell** [comment]
That does not implicate OpenSSL. It just means that something in the handshake is confusing the server - it is clearly sensitive to some kind of combination of ciphersuite/extension/other options. But this still very much looks like a server issue.

**Comment by EnachescuAlin** [comment]
using openssl 1.0.2o with same cipher everything is ok. what changes were made between openssl 1.0.2o and 1.1.0h ?

**Comment by mattcaswell** [comment]
Lots changed! See:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/CHANGES#L359

A lot of that wouldn't be visible in the handshake, but stuff like support for encrypt-them-mac or extended-master-secret would be.
