### ISSUE TITLE
openssl.org domain does not have SPF records

### ISSUE THREAD

**Issue by iamamoose** [openssl/openssl#6077]
We receive numerous security reports stating that we have no Sender Policy Framework (SPF) record on openssl.org.

**Comment by iamamoose** [comment]
We don't send transactional email and do not consider envelope sender forgery to be a security issue for openssl.org.  We have no immediate plans to publish SPF records.

**Comment by bernd-edlinger** [comment]
oops...

**Comment by bernd-edlinger** [comment]
+1
for fixing this issue

**Comment by bernd-edlinger** [comment]
which is the correct outgoing smtp server address?

**Comment by bernd-edlinger** [comment]
Does that mean that I can send mail from my dial-up ip address ?

**Comment by Jasonbuchanan1983** [comment]
<img width="375" alt="Screenshot 2021-05-02 at 5 09 44 AM" src="https://user-images.githubusercontent.com/82856229/116810329-d2d20780-ab08-11eb-8723-3207f95e66db.png">
#15095 [+1 (612) 261-7139]() [My iPhone Bluetooth devices and data account number ](jasonbuchanan1983@icloud.com) 

Duplicate of #
