### ISSUE TITLE
when is it the best to call OPENSSL_thread_stop()?

### ISSUE THREAD

**Issue by seekforwings** [openssl/openssl#6081]
In my project which is worked with some developers, I found the api OPENSSL_thread_stop and I try to use it with the latest release version of openssl. Then I crashed!!!
After some debug and test(for more detail infos, you could see [here](https://blog.csdn.net/newmandirl/article/details/80081210), I want two answers kind of important.
1.Is it that after OPENSSL_thread_stop is called in a thread, the thread SHOULD be to stop, AND the thread SHOULDN'T do any network tasks any longer?
2.Could you please tell me what ways will be good to call OPENSSL_thread_stop? So far, I figured out two ways, see the link above please.

I would be glad to hear anything from you :)

**Comment by seekforwings** [comment]
If there is no network task later, I can call many times of OPENSSL_thread_stop as I want, without crashing. In fact, this is of cause: the api OPENSSL_thread_stop will call the api ossl_init_thread_stop once and then remove this api object from the pthread_key_t. And when any OPENSSL_thread_stop is called later in this thread, the api ossl_init_thread_stop will not be called again.
But there is a possibility that there is some network task going to do in this thread even if OPENSSL_thread_stop has been called. For example, we may use a thread, and run many runnables, until this thread stops. Any time when a runnable ends, we call OPENSSL_thread_stop. Later then a new runnable is going to run in this thread, it may do some network tasks with openssl. I've tested that, with openssl_version_1.1.0.g, it didn't crash. With openssl_version_1.1.1-pref5, it CRASHED.

**Comment by bernd-edlinger** [comment]
You should try the latest git version.
It may help to have a call stack.

**Comment by seekforwings** [comment]
Well, I know that OPENSSL_thread_stop should be called before the thread actually exists, but I am not very sure whether it is not allowed to do any network tasks with openssl after OPENSSL_thread_stop is called.
I have to call OPENSSL_thread_stop because, we are using openssl in a static link mode in a dynamic library. See: [here](https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_thread_stop.html#NOTES)

**Comment by seekforwings** [comment]
Do you mean the master branch? Yes, I also tried.

**Comment by bernd-edlinger** [comment]
what call stack do you see?

**Comment by seekforwings** [comment]
Well, could you please tell how to figure out how to see the call stack as you said?

**Comment by seekforwings** [comment]
OK, wait a minute

**Comment by bernd-edlinger** [comment]
Oh, now I see the problem.
Thanks!

**Comment by seekforwings** [comment]
Well, additionally, could you please tell me whether or not it is allowed to do any network tasks with openssl after OPENSSL_thread_stop is called?

**Comment by bernd-edlinger** [comment]
Yes.

**Comment by seekforwings** [comment]
I don't really think there is any problem with the second way above. Normally, we can avoid using OPENSSL_thread_stop in project at all, because the ossl_init_thread_stop_wrap will be called when pthread_exit.
And normally we can call curl_easy_reset to reset anything in the same thread. This api should make sure that the state, values etc, be the real initial status. They shouldn't be affected by calling or not OPENSSL_thread_stop.

**Comment by richsalz** [comment]
I really don't think it's safe to call thread-stop while a thread is active.  Yes it may work most of the time.  But this is not the same as thread cancel-points.  We have not gone through and found every possible cancellation point and made sure we do the right thing.

**Comment by seekforwings** [comment]
Well, to avoid any risks from calling thread-stop in the active thread, it is advised to call it only once before the thread actually stops as I talked above?
