### ISSUE TITLE
DHE-RSA-SEED-SHA,SEED-SHA 128 bit cipher suites are enabled if cipherSuite is appended with ALL

### ISSUE THREAD

**Issue by raveendrapadala** [openssl/openssl#6086]
Team,

**Environment**:

- I am using [appweb](https://github.com/embedthis/appweb) webserver and configured openssl for TLS handshake. 

- I am using [testssl.sh](https://github.com/drwetter/testssl.sh) tool to see the list the ciphers supported by my product. 

- I am using openssl s_client TLS client tool to check whether the above cipher suite my product is negotiating or not?

- In both configurations TLS protocol 1.1 was set. All other webserver configurations are unchanged except ciphersuite string.

**Problem Description**: Week
CipherSuite Macro was set to ` !ADH:HIGH:MEDIUM:!RC4:!IDEA:!CBC:!3DES:!eNULL:@STRENGTH:` in the webserver configuration file
Test ssl tool reports:
Weak 128 Bit ciphers (SEED, IDEA, RC[2,4])   not offered (OK)
Detailed Report Attached:
[cipherList_withoutALL.txt](https://github.com/openssl/openssl/files/1949137/cipherList_withoutALL.txt)

CipherSuite Macro was set to `!ADH:HIGH:MEDIUM:!RC4:!IDEA:!CBC:!3DES:!eNULL:@STRENGTH:ALL` in the webserver configuration file
Testssl tool reports:
Weak 128 Bit ciphers (SEED, IDEA, RC[2,4])    offered (NOT ok)
Detailed report attached:
[cipherList_withALL.txt](https://github.com/openssl/openssl/files/1949138/cipherList_withALL.txt)

only CipherSuite was changed in webserver configuration in the product. **Can someone comment on this observation?**

**Comment by richsalz** [comment]
You added ALL.  It added those other ciphers.  What did you think ALL meant? :)  Closing this issue.

**Comment by raveendrapadala** [comment]
@richsalz :
user was given option to enter input which was appended at the end.
My understanding is once  ! is given it was for permanent deletion. Now the question is why only these two ciphers are enabled? which are week ciphers infact strength was not changed earlier? strength was 168bit or heigher.

**Comment by richsalz** [comment]
You did not disable SEED.

**Comment by richsalz** [comment]
If you are allowing users to append 'anything' to the cipher string, then I am not positive that it is possible to prevent them from adding weak ciphers.  For example, they could add "@SECLEVEL=0" and explicitly name some ciphers that, like SEED, you forgot to disable.
