### ISSUE TITLE
openssl-1.1.0-pre2 build failed on mingw cross compiler

### ISSUE THREAD

**Issue by ramahmoo** [openssl/openssl#609]
We have successfully build openssl-1.1.0-pre1 for cross platforms recently and were in migration phase. Now we want to build openssl-1.1.0-pre2 but build failed. See below a snippet from our build that causes the build fail:

`x86_64-w64-mingw32-ar  r ../../libcrypto.a async.o async_err.o arch/async_posix.                                              o arch/async_win.o arch/async_null.o
x86_64-w64-mingw32-ranlib ../../libcrypto.a || echo Never mind.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/async'
if [ -n "libcrypto.dll.a libssl.dll.a" ]; then \
                (cd ..; make libcrypto.dll.a); \
        fi
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[3]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[4]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
Bareword found where operator expected at util/mkdef.pl line 1573, near "s/\./_/                                              gr"
Unquoted string "r" may clash with future reserved word at util/mkdef.pl line 15                                              73.
syntax error at util/mkdef.pl line 1573, near "s/\./_/gr"
Execution of util/mkdef.pl aborted due to compilation errors.
/usr/lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld: cry                                              pto.def:1: syntax error
crypto.def: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[4]: *** [link_a.cygwin] Error 1
make[4]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[3]: *** [do_cygwin-shared] Error 2
make[3]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[2]: *** [libcrypto.dll.a] Error 2
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[1]: *** [shared] Error 2
make[1]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto'
make: *** [build_crypto] Error 1
making all in crypto...
make[1]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto'
making all in crypto/objects...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/object                                              s'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/objects                                              '
making all in crypto/md4...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/md4'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/md4'
making all in crypto/md5...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/md5'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/md5'
making all in crypto/sha...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/sha'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/sha'
making all in crypto/mdc2...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/mdc2'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/mdc2'
making all in crypto/hmac...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/hmac'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/hmac'
making all in crypto/ripemd...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ripemd                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ripemd'
making all in crypto/whrlpool...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/whrlpo                                              ol'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/whrlpoo                                              l'
making all in crypto/poly1305...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/poly13                                              05'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/poly130                                              5'
making all in crypto/des...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/des'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/des'
making all in crypto/aes...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/aes'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/aes'
making all in crypto/rc2...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rc2'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rc2'
making all in crypto/rc4...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rc4'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rc4'
making all in crypto/idea...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/idea'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/idea'
making all in crypto/bf...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/bf'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/bf'
making all in crypto/cast...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/cast'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/cast'
making all in crypto/camellia...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/camell                                              ia'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/camelli                                              a'
making all in crypto/seed...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/seed'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/seed'
making all in crypto/chacha...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/chacha                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/chacha'
making all in crypto/modes...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/modes'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/modes'
making all in crypto/bn...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/bn'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/bn'
making all in crypto/ec...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ec'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ec'
making all in crypto/rsa...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rsa'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rsa'
making all in crypto/dsa...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/dsa'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/dsa'
making all in crypto/dh...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/dh'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/dh'
making all in crypto/dso...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/dso'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/dso'
making all in crypto/engine...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/engine                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/engine'
making all in crypto/buffer...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/buffer                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/buffer'
making all in crypto/bio...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/bio'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/bio'
making all in crypto/stack...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/stack'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/stack'
making all in crypto/lhash...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/lhash'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/lhash'
making all in crypto/rand...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rand'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/rand'
making all in crypto/err...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/err'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/err'
making all in crypto/evp...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/evp'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/evp'
making all in crypto/asn1...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/asn1'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/asn1'
making all in crypto/pem...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pem'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pem'
making all in crypto/x509...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/x509'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/x509'
making all in crypto/x509v3...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/x509v3                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/x509v3'
making all in crypto/conf...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/conf'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/conf'
making all in crypto/txt_db...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/txt_db                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/txt_db'
making all in crypto/pkcs7...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pkcs7'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pkcs7'
making all in crypto/pkcs12...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pkcs12                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pkcs12'
making all in crypto/comp...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/comp'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/comp'
making all in crypto/ocsp...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ocsp'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ocsp'
making all in crypto/ui...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ui'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ui'
making all in crypto/cms...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/cms'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/cms'
making all in crypto/pqueue...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pqueue                                              '
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/pqueue'
making all in crypto/ts...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ts'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ts'
making all in crypto/srp...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/srp'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/srp'
making all in crypto/cmac...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/cmac'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/cmac'
making all in crypto/ct...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ct'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/ct'
making all in crypto/async...
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/async'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto/async'
if [ -n "libcrypto.dll.a libssl.dll.a" ]; then \
                (cd ..; make libcrypto.dll.a); \
        fi
make[2]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[3]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[4]: Entering directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
Bareword found where operator expected at util/mkdef.pl line 1573, near "s/\./_/                                              gr"
Unquoted string "r" may clash with future reserved word at util/mkdef.pl line 15                                              73.
syntax error at util/mkdef.pl line 1573, near "s/\./_/gr"
Execution of util/mkdef.pl aborted due to compilation errors.
/usr/lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld: cry                                              pto.def:1: syntax error
crypto.def: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[4]: *** [link_a.cygwin] Error 1
make[4]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[3]: *** [do_cygwin-shared] Error 2
make[3]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[2]: *** [libcrypto.dll.a] Error 2
make[2]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2'
make[1]: *** [shared] Error 2
make[1]: Leaving directory `/usr/local/openssl-lib/openssl-1.1.0-pre2/crypto'
make: *** [build_crypto] Error 1
remove temp source dir
`

**Comment by ramahmoo** [comment]
seems this has been already discussed in 
[https://github.com/openssl/openssl/issues/551](url)

Trying right now the proposed fixed.

**Comment by ramahmoo** [comment]
#551 proposed fix works.

**Comment by levitte** [comment]
This has already been fixed, see 56afc18714664e8fb395a2e143e48be3ab146d43

**Comment by richsalz** [comment]
This is a known issue with older versions of perl.  I think there's a work-around coming.
