### ISSUE TITLE
Openssl: General

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#6091]
Hi,

Is there a way to check if a file that I have is encrypted or not?
I am looking for an openssl API or something.

Thanks in advance.

Regards,
Amal

**Comment by mattcaswell** [comment]
That kind of depends.

In general the answer is "no". Encrypted data looks like a random sequence of bytes, so you don't know whether it's encrypted, or whether it's just random data!

If your encrypted data is wrapped up in some standard envelope then it might be possible. E.g. if the data has been encrypted using the openssl command line "enc" application then (except in some cases where options suppress it) the encrypted data will be prefixed with the magic string ""Salted__". Presence of that string indicates the data has been encrypted with the command line app.

**Comment by amaljesudas** [comment]
Thanks @mattcaswell .
For the present, I will take the "no". :smile: 


Regards,
Amal

**Comment by amaljesudas** [comment]
Hi @mattcaswell ,

If I were to consider only CMS encryption cases, will it be correct if I parse the first 12 bytes of the encrypted message and check for presence of "MIME-Version"?
I expect that all CMS encrypted files will have this in header, which will indirectly imply it is encrypted.
Please correct me if I am wrong.

Thanks in advance.

Regards,
Amal
