### ISSUE TITLE
Stupid question how do I replace 1.1.1-pre3 with 1.1.1-pre6 on Ubuntu 16.04

### ISSUE THREAD

**Issue by SimonFearby** [openssl/openssl#6107]
Stupid question how do I replace 1.1.1-pre3 with 1.1.1-pre6 on Ubuntu 16.04

I did..

mkdir temp 
cd temp
sudo git clone https://github.com/openssl/openssl.git
cd openssl
make
sudo make install

After....
openssl
OpenSSL> version
OpenSSL 1.1.1-pre3 (beta) 20 Mar 2018 remains installed?

Location..
which openssl
/usr/local/bin/openssl

Thanks

**Comment by bernd-edlinger** [comment]
add ./config

**Comment by t-j-h** [comment]
Check which shared libraries you are using
ldd openssl

etc

**Comment by SimonFearby** [comment]
I tried again with
./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -Wl,-rpath,/usr/local/ssl/lib

**Comment by SimonFearby** [comment]
ldd openssl
ldd: ./openssl: No such file or directory

sudo apt-get install ldd
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ldd

**Comment by levitte** [comment]
If your previous installation ended up with `/usr/local/bin/openssl`, then `--prefix=/usr/local` would be better.  I suspect that you made the previous installation with defaults, i.e. something like this:

```
./config -Wl,-rpath,'$(LIBRPATH)'
```

**Comment by SimonFearby** [comment]
Solved, thanks levitte etc

# ./config --prefix=/usr/local --openssldir=/usr/local -Wl,-rpath,/usr/local
# sudo make
# sudo make install

Verified

# openssl
# OpenSSL> version
# OpenSSL 1.1.1-pre6-dev  xx XXX xxxx


Shows as a TLS 1.3 connection in Chrome 67 dev console and https://dev.ssllabs.com/ssltest/analyze.html?d=fearby.com&s=104.27.154.69&latest

Thanks

**Comment by levitte** [comment]
... except that `-Wl,-rpath,/usr/local` isn't quite right.  The better choice *is* to use `$(LIBRPATH)` like I showed you, 'cause then you don't need to care about the exact rpath, the build will generate it for you.

**Comment by SimonFearby** [comment]
Thanks, will use $(LIBRPATH) in future.
