### ISSUE TITLE
unknown option -serverpref in openssl s_client -ssl2

### ISSUE THREAD

**Issue by iambrosie** [openssl/openssl#611]
When running ./openssl s_client -ssl2 -serverpref -connect host:port

I get the following error:

unknown option -serverpref

I believe this should not happen since the list of options which is printed after the above mentioned error includes the following:

-serverpref   - Use server's cipher preferences (only SSLv2)

Here's the openssl details:
iambrosie@xxx:~/Tools/OpenSSL/openssl-1.0.2f/apps$ ./openssl version -a
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
OpenSSL 1.0.2f  28 Jan 2016
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/ssl"

**Comment by richsalz** [comment]
The bug is that the message should not appear in the help text (only valid for server-side).
Thanks.

**Comment by richsalz** [comment]
fixed in next 1.0.2 release, a2bab12a331b6764804913d08e2e472c9e5d13ae
