### ISSUE TITLE
h2s_ipsec brazil

### ISSUE THREAD

**Issue by ericcurtin** [openssl/openssl#6112]
Cannot maintain connection for over 20 minutes

**Comment by ericcurtin** [comment]
Apr 26 19:33:45 s54t0108g rda-midway[4065256]: INF [http-connection.cpp:284] POST /dialer from tcp:127.0.0.1:64654 
Apr 26 19:33:45 s54t0108g rda-midway[4065256]: INF [connection-ticket.cpp:171] Verify Ticket: h2s_ipsec - tcp:10.129.64.134:22 ; ricardo.durao@hpe.com
Apr 26 19:33:46 s54t0108g rda-midway[4065256]: INF [ipsec_connection.cpp:69] IPsec connection established: 72e042d8-150a-452e-a16e-5eac413f1804
Apr 26 19:33:48 s54t0108g rda-midway[4065256]: INF [repeater.cpp:517] SSH session started to tcp:10.129.64.134:22 by ricardo.durao@hpe.com using public key authentication
Apr 26 19:33:48 s54t0108g rda-midway[4065256]: INF [midway.cpp:1820] Created 'device.connect' message for station id: 72e042d8-150a-452e-a16e-5eac413f1804 using tunnel mode: h2s_ipsec
Apr 26 19:33:48 s54t0108g rda-midway[4065256]: INF [connection-ticket.cpp:171] Verify Ticket: h2s_ipsec - tcp:10.129.64.134:22 ; ricardo.durao@hpe.com
Apr 26 19:34:22 s54t0108g rda-midway[4065256]: INF [repeater.cpp:1261] SS1/TS02/XSl02 (cas) start pipe (2,2) on {ricardo.durao@hpe.com@work:1,72e042d8-150a-452e-a16e-5eac413f1804:1} from HPE for ssh to target tcp:127.0.0.1:22 serial  sku ssh cas at 2018-04-26 19:34:22Z [1524771262]
Apr 26 19:39:57 s54t0108g rda-midway[4065256]: INF [connection-ticket.cpp:171] Verify Ticket: h2s_ipsec - tcp:10.129.64.134:22 ; marcelo.hansen@hpe.com
Apr 26 19:42:55 s54t0108g rda-midway[4065256]: INF [repeater.cpp:1261] SS1/TS02/XSl02 (cas) start pipe (3,3) on {ricardo.durao@hpe.com@work:1,72e042d8-150a-452e-a16e-5eac413f1804:1} from HPE for browser to target tcp:rjmck01hpsa1:8000 serial  sku ssh cas at 2018-04-26 19:42:55Z [1524771775]
Apr 26 19:43:21 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS4/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:43:24 s54t0108g rda-midway[4065256]: INF [repeater.cpp:1483] CS1/PS3-3/SS1/TS02/XSl02 Channel EOF
Apr 26 19:43:28 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS3/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:43:43 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS5/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:43:43 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS6/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:43:45 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS8/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:43:46 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS9/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:43:55 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS10/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:43:56 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS7/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:44:45 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS11/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:44:45 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS12/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:44:46 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS13/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:44:46 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS14/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:44:46 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS16/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:44:46 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS2/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:45:35 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS17/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:45:35 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS18/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:45:35 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS19/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:45:35 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS20/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:45:35 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS21/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:45:35 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS22/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:45:35 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS15/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:46:22 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS24/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:46:24 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS23/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:46:24 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS25/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:46:25 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS26/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:46:25 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS27/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:46:25 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS28/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:46:26 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS29/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:47:14 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS30/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:47:15 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS33/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:47:15 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS32/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:47:15 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS34/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:47:15 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS36/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:47:15 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS31/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:03 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS35/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:04 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS37/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:04 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS38/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:04 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS39/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:04 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS40/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:04 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS41/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:05 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS43/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:52 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS42/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:53 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS44/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:54 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS45/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:54 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS46/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:54 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS47/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:48:55 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS48/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:49:44 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS50/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:49:44 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS52/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:49:44 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS51/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:49:44 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS53/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:49:44 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS54/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:49:44 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS56/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:49:44 s54t0108g rda-midway[4065256]: INF [repeater.cpp:432] CS49/PS3-3/SS1/TS02/XSl02 Channel ssh EOF
Apr 26 19:50:14 s54t0108g rda-midway[4065256]: ERR [repeater.cpp:1381] Cannot open forward channel: Socket error: Connection timed out
Apr 26 19:50:14 s54t0108g rda-midway[4065256]: FTL [repeater.cpp:439] Error on ssh channel: Socket error: Connection timed out
Apr 26 19:50:14 s54t0108g rda-midway[4065256]: INF [repeater.cpp:379] SSH session stopped with tcp:10.129.64.134:22 , dur=986(s)
Apr 26 19:50:14 s54t0108g rda-midway[4065256]: ERR [ipsec_connection.cpp:84] Failed to drop IPsec connection: 72e042d8-150a-452e-a16e-5eac413f1804 - IPsec error
Apr 26 19:50:14 s54t0108g rda-midway[4065256]: FTL [bandicoot-reporter.cpp:13] bandicoot caught a signal: 11

**Comment by levitte** [comment]
This is Open*SSL*, not OpenSSH.

**Comment by ericcurtin** [comment]
Apologies, wrong github page, too many tabs open
