### ISSUE TITLE
Building aircrack-ng for Raspberry Pi says HMAC_CTX_* functions are not defined

### ISSUE THREAD

**Issue by pcolladosoto** [openssl/openssl#6122]
As I was compiling the source code for aircrack-ng, gcc threw an error saying that HMAC_CTX struct type, as well as HMAC_CTX_* were not defined. I have included <openssl/hmac.c> in the code, but it keeps throwing the error...

**Comment by patrickschneider23** [comment]
- `ich `

**Comment by pcolladosoto** [comment]
I will try to do so. Are the HMAC_CTX functions still public? Thanks for the fast reply!

**Comment by kroeckx** [comment]
It's just the struct itself that's no longer public, there should
be public functions for everything you want to do with it.

**Comment by pcolladosoto** [comment]
Thanks a lot, that was a huge help!
