### ISSUE TITLE
Some documentation links are broken

### ISSUE THREAD

**Issue by vdukhovni** [openssl/openssl#6126]
For example, https://www.openssl.org/docs/man1.1.0/ssl/SSL_set1_host.html contains a broken link to `X509_check_host` (`https://www.openssl.org/docs/man1.1.0/ssl/X509_check_host.html`) the link should be to the crypto not the SSL library (`https://www.openssl.org/docs/man1.1.0/crypto/X509_check_host.html`). The same probably applies to other machine-generated links from SSL manpages that reference libcrypto.

**Comment by kroeckx** [comment]
Sounds a lot like #1819

**Comment by vdukhovni** [comment]
Yes, looks the same to me, shall I close this one, and perhaps we'll do something about #1819?

**Comment by t8m** [comment]
This should have been closed a long time ago as duplicate.
