### ISSUE TITLE
Add include guards to the header files

### ISSUE THREAD

**Issue by davxy** [openssl/openssl#6128]
Some header files does not have the "classic" include guard:

    #ifndef HEADER_FOO
    #define HEADER_FOO
    ...
    #endif /* HEADER_FOO */

Even though in some cases that is not **technically** mandatory, as a **design/stylistic** suggestion I propose to add the include guards to every header file as a *de-facto* coding rule.

**Comment by richsalz** [comment]
For what it's worth, it's my opinion that this is not worth spending time (yours, nor the team's) at this point in the release cycle.  We have a big backlog of PR's and coverity things to worry about.

**Comment by davxy** [comment]
Understood. Actually I'm studying the internals especially of the libcrypto and if I spot something that smells bed I'll try at least to improve it... I hope this is the spirit of the project

**Comment by richsalz** [comment]
Absolutely and completely that's the spirit!  It might be more useful to open issues for these kinds of things, and we can get back to them after the 1.1.1 release.  Or keep doing what you're doing.  Every contribution to improve the code helps!

**Comment by t8m** [comment]
All the public headers have the guards. Some of the internal ones do not have them. I do not think this is a "feature" worth working on. If somebody creates a PR adding the guards, it will be considered. Closing.
