### ISSUE TITLE
EC_GROUP_free segfaults while accessing generator point_finish

### ISSUE THREAD

**Issue by Silur** [openssl/openssl#6147]
**x86_64 4.16.5-1-ARCH
OpenSSL 1.1.0h  27 Mar 2018**

Code example below results in a segfault at `ec_lib.c:589` while `EC_GROUP_free` tries to clean up the point generator (`ec_lib.c:104`) because `point->meth->point_finish` is a non-accessible memory address by this time.
```c
#include <openssl/bn.h>
#include <openssl/ec.h>

int main()
{
	EC_GROUP *curve = EC_GROUP_new(EC_GFp_simple_method());
	BN_CTX *bnctx = BN_CTX_new();
    BIGNUM *a = BN_new();
    BIGNUM *b = BN_new();
    BIGNUM *p = BN_new();
    /* manual secp256k1 */
    BN_zero(a);
    BN_set_word(b, 7);
    BN_hex2bn(&p, "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F");
    char *generator = "0479BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D9\
        59F2815B 16F81798 483ADA77 26A3C465 5DA4FBFC 0E1108A8 FD17B448\
        A6855419 9C47D08F FB10D4B8";
    char *order = "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8C\
        D0364141";
    char *cofactor = "01";
	EC_GROUP_set_curve_GFp(curve, p, a, b, bnctx);

    BIGNUM *q = BN_new();
    EC_POINT *g = EC_POINT_new(curve);
    BN_hex2bn(&q, cofactor);
    EC_POINT_hex2point(curve, generator, g, bnctx);
    BIGNUM *o = BN_new();
    BN_hex2bn(&o, order);
    EC_GROUP_set_generator(curve, g, o, q);
    EC_GROUP_free(curve);
	return 0;
}
```

**Comment by mattcaswell** [comment]
I cannot reproduce this. I tried against the same OpenSSL build (1.1.0h). I can't see any reason why `point->meth->point_finish` would be non-accessible at that point - and (for me) it seems to work just fine.

Hmmm....

**Comment by levkk** [comment]
I also tried this with `master` at `4db296d9` and it ran without a segfault.

**Comment by levkk** [comment]
Same result, no segfault.

**Comment by mattcaswell** [comment]
But you get a segfault if you checkout the OpenSSL_1_1_0h tag and try against that right? If so that suggests that the problem has been fixed already! If not...well then that's really weird.

**Comment by mattcaswell** [comment]
So how did you get your original 1.1.0h that you originally tested against and saw the seg fault? It's starting to sound like some environmental issue on your side.

**Comment by levkk** [comment]
I'm not the one who reported the issue, I just noticed it and trying to help out :) @Silur is the original reporter.

**Comment by mattcaswell** [comment]
Right..duh! Thanks. @Silur?

**Comment by Silur** [comment]
no advance on my side but since this can't be reproduced elsewhere then closing for probable env issue
