### ISSUE TITLE
Win32 compilation fails when --with-zlib-include is set to a full path

### ISSUE THREAD

**Issue by noahdav** [openssl/openssl#6153]
On branch OpenSSL_1_0_2-stable I am trying to build OpenSSL with zlib support.  I run the the configure script --with-zlib-include set to a full windows paths (i.e. c:\src\zlib) during compilation It fails with the following errors.  Other paths seem to be working as I would expect.

I used the following command to configure:
perl Configure debug-VC-WIN32 --prefix=c:\src\bin\openssl\x86\debug --with-zlib-include=c:\src\zlib --with-zlib-lib=c:\src\bin\zlib\x86\debug enable-zlib enable-zlib-dynamic

However if I do not use the \ in the --with-zlib-include it seems to be OK.

This command line works
perl Configure debug-VC-WIN32 --prefix=c:\src\bin\openssl\x86\debug --with-zlib-include=../zlib --with-zlib-lib=c:\src\bin\zlib\x86\debug enable-zlib enable-zlib-dynamic

This seems to be similar to https://github.com/openssl/openssl/issues/5208.  However I am not seeing the the required fixes missing on my side.

**Comment by noahdav** [comment]
I forgot the error I was seeing.

        cl /Fotmp32dll.dbg\cversion.obj  -Iinc32 -Itmp32dll.dbg /MDd /Od -DDEBUG -D_DEBUG -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -WX -Gs0 -GF -Gy -Zi -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -D_WINSOCK_DEPRECATED_NO_WARNINGS -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DZLIB -DZLIB_SHARED -DOPENSSL_NO_STATIC_ENGINE  -Ic:\src\zlib /Zi /Fdtmp32dll.dbg/lib -D_WINDLL  -DOPENSSL_BUILD_SHLIBCRYPTO -DMK1MF_BUILD -DMK1MF_PLATFORM_VC_WIN32 -c .\crypto\cversion.c
cversion.c
.\crypto\cversion.c(82): error C2220: warning treated as error - no 'object' file generated
.\crypto\cversion.c(82): warning C4129: 's': unrecognized character escape sequence
.\crypto\cversion.c(82): warning C4129: 'z': unrecognized character escape sequence
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.

Also this works fine for the VC-WIN64A configuration.

**Comment by pps83** [comment]
So far the only solution is to use relative paths for zlib, otherwise it will fail

**Comment by t8m** [comment]
1.0.2 is out of regular support. Closing.
