### ISSUE TITLE
Suspicious, likely dead code in ec_wNAF_mul()

### ISSUE THREAD

**Issue by Dmitry-Me** [openssl/openssl#616]
Cppcheck found this in `ec_wNAF_mul()`

            if (tmp_len <= max_len) {
                /*
                 * One of the other wNAFs is at least as long as the wNAF
                 * belonging to the generator, so wNAF splitting will not buy
                 * us anything.
                 */

                numblocks = 1;
                totalnum = num + 1; /* don't use wNAF splitting */
                wNAF[num] = tmp_wNAF;
                wNAF[num + 1] = NULL;
                wNAF_len[num] = tmp_len;
                if (tmp_len > max_len)
                    max_len = tmp_len;

Note ` if (tmp_len > max_len)` neither `max_len` nor `tmp_len` have changed since outer ` if (tmp_len <= max_len) {` so the inner `if` condition will always be false and the dependent code will never run.

**Comment by richsalz** [comment]
+1

**Comment by kroeckx** [comment]
I'm not sure what the +1 / reviewed means here, there doesn't seem to be a patch.

**Comment by richsalz** [comment]
good point, it describes a patch to be made, isn't a pull request.

**Comment by Dmitry-Me** [comment]
Actually I have no idea of how this should be fixed. That code was added for some purpose. What was the purpose?

**Comment by nick599** [comment]
@Dmitry-Me I could not find tmp_len in the ec2_mult.c
- Hence can this issue be closed?

**Comment by richsalz** [comment]
no, it's in ec_mult.c around line 323.

**Comment by nick599** [comment]
Is there a way one can find out who wrote that section, so we can ask them?

**Comment by richsalz** [comment]
Post to openssl-dev might elicit and answer.  Or, since this is clearly dead code no matter the intent, a PR to remove it would work.

**Comment by nick599** [comment]
@richsalz what is the email address for openssl-dev?

**Comment by richsalz** [comment]
You have to be a member to post; see https://mta.openssl.org

**Comment by bbbrumley** [comment]
@nick599 FWIW I'm somewhat familiar with that code. I'm guessing it's just a leftover condition check from a copy/paste -- changed some variable names then tweaked the outer condition, then failing to remove the resulting inner dead code. Here's the commit that did it if you want to dig more:

https://github.com/openssl/openssl/commit/37c660ff9b22d6f0eb19a9881d3b663ca4f63449#diff-40a9b7f560ef4410b988fafff6e79928

**Comment by nick599** [comment]
Ok, it seems we need a pull request with the dead code removed. 
It's been a while since I cloned a repo, edited applicable file, then make a pull request. I'm willing to do this or hand this over to someone who has more experience.
