### ISSUE TITLE
Internal Errors

### ISSUE THREAD

**Issue by Apromixately** [openssl/openssl#6176]
As requested by @richsalz in https://github.com/openssl/openssl/issues/5213 here are some more cases where you return internal error but probably shouldn't because we were able to trigger them using malformed messages.

ssl/statem/statem_clnt.c:2468
ssl/statem/statem_clnt.c:2507
ssl/s3_lib.c:4744
crypto/asn1/asn1_lib.c:101
ssl/statem/extensions_clnt.c:1292
ssl/statem/statem_srvr.c:2912

I hope I got all of these right. Feel free to ask for more information if you need any.

**Comment by mgierlings** [comment]
I just wanted to report that I found more locations where an `INTERNAL_ERROR` alert is erroneously sent: https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/ssl/statem/statem_clnt.c#L432

^ This one should probably be `UNEXPECTED_MESSAGE` instead.

https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/ssl/statem/statem_clnt.c#L2510, https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/ssl/statem/statem_clnt.c#L2531, https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/ssl/statem/statem_clnt.c#L2537

**Comment by mattcaswell** [comment]
https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/ssl/statem/statem_clnt.c#L432

This one really is an internal error, and is only sent after an `ossl_assert` test has failed (so in a debug build this will crash). If you managed to get this through malformed messages I'd be very interested to know how you did that.

**Comment by mattcaswell** [comment]
https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/ssl/statem/statem_clnt.c#L2537

Again, with this one I can only see that it can occur with a malloc failure...how did you get it?

**Comment by mgierlings** [comment]
> 
> 
> [openssl/ssl/statem/statem_clnt.c](https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/ssl/statem/statem_clnt.c#L2537)
> 
> Line 2537 in [7835e97](/openssl/openssl/commit/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2)
>  SSLfatal(s, SSL_AD_INTERNAL_ERROR, 
> 
> Again, with this one I can only see that it can occur with a malloc failure...how did you get it?
# Steps to reproduce 
## Get TLS-Attacker
```
git clone https://github.com/RUB-NDS/TLS-Attacker.git
```

## Build TLS-Attacker (Maven required)
```
cd TLS-Attacker
mvn clean install
```

Download and extract  the archive containing workflow trace b3ac3359670cfb_0.382295.wt.xml and the configuration file b3ac3359670cfb94_0.382295.cfg.xml to the TLS-Attacker directory.

[b3ac3359670cfb94_0.382295.zip](https://github.com/openssl/openssl/files/2766345/b3ac3359670cfb94_0.382295.zip)

## Build OpenSSL
```
git clean -fdx
git fetch --tags
git checkout tags/OpenSSL_1_1_1
AFL_USE_ASAN=1 AFL_HARDEN=1 CC=afl-gcc CXX=afl-g++ ./config no-shared -DPEDANTIC enable-tls1_3 enable-weak-ssl-ciphers enable-rc5 enable-md2 enable-ssl3 enable-ssl3-method enable-nextprotoneg enable-ec_nistp_64_gcc_128 enable-ubsan enable-asan --debug
nice -n 19 make -j$(nproc)
```

## Start TLS-Attacker
`export tid=b3ac3359670cfb94_0.382295 && apps/TLS-Server.jar -port 44585 -workflow_input $tid.wt.xml -config $tid.cfg.xml`

## Run OpenSSL against TLS-Attacker
```
./apps/openssl s_client -port 44585
```

## Observe OpenSSL output 
```
CONNECTED(00000005)                                             
depth=0 C = DE, ST = NRW, L = Bochum, O = "<script>alert('TLS-Attacker')</script>", CN = tls-attacker.de
verify error:num=18:self signed certificate                 
verify return:1          
depth=0 C = DE, ST = NRW, L = Bochum, O = "<script>alert('TLS-Attacker')</script>", CN = tls-attacker.de
verify return:1
140402253124480:error:14169168:SSL routines:tls_process_certificate_request:signature algorithms error:ssl/statem/statem_clnt.c:2538:
---
Certificate chain
 0 s:C = DE, ST = NRW, L = Bochum, O = "<script>alert('TLS-Attacker')</script>", CN = tls-attacker.de
-----------------------------------------------------------------------------------------------------------------
...
```

## Observe TLS-Attacker output 
```
23:01:23 [main] INFO : DefaultWorkflowExecutor - Waiting for incoming connection on localhost:44585
23:01:24 [main] INFO : ReceiveAction - Received Messages (server): CLIENT_HELLO, 
23:01:24 [main] INFO : SendAction - Sending messages (server): SERVER_HELLO, CERTIFICATE, CERTIFICATE_REQUEST, 
23:01:25 [main] WARN : Serializer - Int "5505024" is too long to write in field of size 2. Only using last 2 bytes.
23:01:25 [main] WARN : Serializer - Int "5505024" is too long to write in field of size 2. Only using last 2 bytes.
23:01:26 [main] INFO : ReceiveAction - Received Messages (server): Alert(FATAL,INTERNAL_ERROR)
```

I don't have a workflow to hit 2510, but based on this hit by the above repro I found that location suspicious. 432 got my attention because of the adjacent comment. 

```
        /*
         * We should only get here if we received a CertificateRequest after
         * we already sent close_notify
         */
```

If this `INTERNAL_ERROR` is triggered by an incoming `CertificateRequest` after a `close_notify` has been sent, this would be a protocol violation and should probably be replaced with an `UNEXPECTED_MESSAGE` alert.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
