### ISSUE TITLE
How to configure oscp protocol

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [openssl/openssl#6189]
Dear Developers：
     I don't understand how to configure the oscp process, what methods help me understand this part of the knowledge.

**Comment by InfoHunter** [comment]
https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol

and

https://github.com/openssl/openssl/blob/master/doc/man1/ocsp.pod

**Comment by mattcaswell** [comment]
Question was answered. No follow up questions so closing.
