### ISSUE TITLE
Did csr (AKA: Certificate signing request) contain certificate public key? if have,,how do i exoport public key from csr file ? thanks

### ISSUE THREAD

**Issue by andylau004** [openssl/openssl#6193]
up

**Comment by richsalz** [comment]
X509_REQ_get_pubkey.

**Comment by andylau004** [comment]
@richsalz does have andy cmd support ?
like this
openssl ec -in id_pc_sdk_7789.key -pubout -out ec.pubkey

**Comment by richsalz** [comment]
For X509_REQ the "req" command has a "-pubkey" flag.
