### ISSUE TITLE
General SSL_library_init():

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#6202]
Hi,

Is there a way to check if openssl initialization is already done?
i.e. check if **SSL_library_init()** or **OPENSSL_init_ssl()** is already invoked?

Thanks in advance.

Regards,
Amal

**Comment by richsalz** [comment]
For which version?

**Comment by amaljesudas** [comment]
Hi @richsalz ,

Openssl v1.0.2n.

Regards,
Amal

**Comment by richsalz** [comment]
There is no official API for this.  You could do an EVP lookup with a cipher that you "know" should be there.

**Comment by amaljesudas** [comment]
Thanks @richsalz 

Regards,
Amal
