### ISSUE TITLE
Unable to build libssl.dll libcrypto.dll

### ISSUE THREAD

**Issue by kdgoud** [openssl/openssl#6213]
This is what im tring to do:
Build openssl1.1.0g without dependency on msvcr and use libssl , libcrypto dlls for other projects
Environment: Windows server 2016 , MS2005 
i have built openssl using 

> perl Configure --config=sonic.conf no-idea no-rc5 no-mdc2 enable-weak-ssl-ciphers  %CONFIG% 

But this only generates openssl.exe but not libssl*.dll or libcrypto*.dll

If i try with "no-shared" flag, it generates dlls, openssl.exe but with msvcr dependency.

Previously for openssl0.9.8, we used to create them using the following scripts/files, and these arent available with the openssl1.1.0g 

> echo modify makefiles to build psc_crypto%shlibver%.dll and psc_ssl%shlibver%.dll
> type ms\ntdll.mak | perl -pi -e "s/ssleay32/psc_ssl%shlibver%/g" > ms\ntdll.tmp
> type ms\ntdll.tmp | perl -pi -e "s/libeay32/psc_crypto%shlibver%/g" > ms\ntdll.mak
> type ms\libeay32.def | perl -pi -e "s/LIBEAY32/psc_crypto%shlibver%/g" > ms\libeay32.tmp
> move /Y ms\libeay32.tmp ms\libeay32.def
> type ms\ssleay32.def | perl -pi -e "s/SSLEAY32/psc_ssl%shlibver%/g" > ms\ssleay32.tmp
> move /Y ms\ssleay32.tmp ms\ssleay32.def
> echo nmake dll ^> make-openssl-%version%-dll.log
> call nmake -f ms\ntdll.mak all > make-openssl-%version%-dll.log 2>&1

Now i cannot create dlls without msvcr dependency.

**Comment by kaduk** [comment]
> i have built openssl using

> >   perl Configure --config=sonic.conf no-idea no-rc5 no-mdc2 enable-weak-ssl-ciphers %CONFIG%

> But this only generates openssl.exe but not libssl*.dll or libcrypto*.dll

That shows just the "generate makefiles" step; it seems that the actual build command used was not shown.

But see also #3377 (and presumably others).

**Comment by kdgoud** [comment]
Thanks, i think i found a way to achive this, but i had to run the build twice.

> perl Configure --config=sonic.conf no-shared no-idea no-rc5 no-mdc2 enable-weak-ssl-ciphers %CONFIG%
> nmake 

This will generate static openssl.exe 

> perl Configure --config=sonic.conf no-idea no-rc5 no-mdc2 enable-weak-ssl-ciphers %CONFIG%
>// Using perl replace /MD with /MT in makefile
>perl -pi.back -e "s/\/MD/\/MT/g" makefile
>nmake 

This would generate static DLLS. LIBS

**Comment by dot-asm** [comment]
We naturally can't prevent anybody doing whatever they like, but as already said in #3377, this is *not* something that can be [meaningfully] supported. Even if something works... Statically linked openssl.exe? Great! DLLs linked with /MT? Not that great idea...

**Comment by richsalz** [comment]
Closing this issue.  We don't support this.
