### ISSUE TITLE
What do BN_mod_mul_montgomery ?

### ISSUE THREAD

**Issue by maxben14** [openssl/openssl#6242]
int BN_mod_mul_montgomery(BIGNUM *r, const BIGNUM *a, const BIGNUM *b,
                          BN_MONT_CTX *mont, BN_CTX *ctx)
This function do rezult = a * b ?
I want do this function on qt with NTL library.
Help me please about math in this function.

**Comment by richsalz** [comment]
There's a manpage (surprisingly:).  Closing this.

**Comment by maxben14** [comment]
@richsalz , do you can me say what do this function BN_mod_mul_montgomery in termins math ?

**Comment by maxben14** [comment]
BN_mod_mul_montgomery() computes Mont(a,b):=a*b*R^-1 and places the result in r. 
What is number R ?

**Comment by richsalz** [comment]
I suggest you ask on the openssl-users mailing list; see https://mta.openssl.org for details on how to join.
