### ISSUE TITLE
Heartbeats without Heartbeat Extension

### ISSUE THREAD

**Issue by ic0ns** [openssl/openssl#6246]
During our research on TLS-Attacker we discovered that Openssl 1.0.2o allows HeartbeatRequests to be sent by both parties even if the heartbeat extension was **not** negotiated in the handshake. This bug is present in Openssl atleast since 1.0.1f (Heartbleed, i did not check older versions).  I am not sure if heartbeat can be activated in the newest version,. If Openssl is not compiled with heartbeat support we could not reproduce this issue.

This bug can be reproduced with TLS-Attacker:
```
git clone https://github.com/RUB-NDS/TLS-Attacker.git
cd TLS-Attacker
mvn clean install
openssl s_server
java -jar apps/TLS-Client.jar -connect localhost:4433 -workflow_input <trace> -cipher TLS_RSA_WITH_AES_128_CBC_SHA
```
with the following WorkflowTrace:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workflowTrace>
    <Send>
        <messages>
            <ClientHello>
                <extensions>
                    <ECPointFormat/>
                    <EllipticCurves/>
                    <RenegotiationInfoExtension/>
                </extensions>
            </ClientHello>
        </messages>
    </Send>
    <Receive>
        <expectedMessages>
            <ServerHello>
                <extensions>
                    <ECPointFormat/>
                    <RenegotiationInfoExtension/>
                </extensions>
            </ServerHello>
            <Certificate/>
            <ServerHelloDone/>
        </expectedMessages>
    </Receive>
    <Send>
        <messages>
            <RSAClientKeyExchange/>
            <ChangeCipherSpec/>
            <Finished/>
        </messages>
    </Send>
    <Receive>
        <expectedMessages>
            <ChangeCipherSpec/>
            <Finished/>
        </expectedMessages>
    </Receive>
    <Send>
        <messages>
	    <Heartbeat>
	    </Heartbeat>
	</messages>
    </Send>
    <Receive>
        <expectedMessages>
	    <Heartbeat>
	    </Heartbeat>
        </expectedMessages>
    </Receive>
</workflowTrace>
```

We think this issue has little security implications. 

Best regards
Robert Merget (@ic0ns), Simon Friedberger (@Apromixately) and Juraj Somorovsky (@jurajsomorovsky)

**Comment by mattcaswell** [comment]
What does a receiving OpenSSL peer do if it gets an unsolicited heartbeat request? Respond to it, drop it, drop the connection, or something else?

**Comment by ic0ns** [comment]
Currently it responds to it. I would expect that it should answer with an unexpected_message Alert or drop the message instead.

**Comment by kaduk** [comment]
unexpected_message seems like it should be the correct behavior.
I mostly expect that 1.1.0's rewritten state machine should already do that (unexpected_message) but did not test.

**Comment by t8m** [comment]
1.0.2 is out of regular support. Closing.
