### ISSUE TITLE
Resolve conflicting requirements on long strings in the Coding Style guideline

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#6254]
The official coding guideline at https://www.openssl.org/policies/codingstyle.html says:

> Indentation is four space characters.

> The limit on the length of lines is 80 columns.

> Never break user-visible strings, however, because that breaks the ability to grep for them.

As I mentioned in https://github.com/openssl/openssl/pull/6218#discussion_r187581896,
I tried strictly following these rules but this is not possible with long user-visible strings.
So I ask for clarification of the coding guidelines in this respect.

As @mattcaswell put it in https://github.com/openssl/openssl/pull/6218#discussion_r187584238:
> It seems that either we have to break the coding style's indentation rules, or the coding styles rules on not breaking user visible strings, or the coding styles rules on line length. One way or another the rules have to be broken in this case! I think the least offensive option (to me at least) is to indent it properly and break the 80 char limit.

I tend to agree that when using long strings sacrificing the line length limit hurts least.

**Comment by mspncp** [comment]
> Never break user-visible strings, however, because that breaks the ability to grep for them.

According to my understanding of the english language, the "however" in this sentence (which is the last sentence of Chapter 2) means that this rule overrules the previous ones. So I don't see any need to change the rules.

**Comment by DDvO** [comment]
This implies that the last of the three requirements is the strongest,
but does not make clear (at least to some people including me)
whether then to sacrifice indentation or the line length limit.

**Comment by mspncp** [comment]
Well, I would say the 80 column rule looses; there is a precedent a few lines above:

> ..., unless exceeding 80 columns significantly increases readability...

**Comment by mspncp** [comment]
Also, the "however" only applies to Chapter 2 (80 column rule), not to Chapter 1 (indentation).

**Comment by mspncp** [comment]
Reading @mattcaswell's comment,

>  I think the least offensive option (to me at least) is to indent it properly and break the 80 char limit.

 I think I don't speak for myself alone. However, if you think the wording should be made more precise, you are welcome to make suggestions.

**Comment by richsalz** [comment]
When I was a kid, my parent's got my sisters and I this book:  "Tiffany's Table Manner for Children"  It's renamed to "for Teenagers" apparently: https://www.amazon.com/Tiffanys-Manners-Teenagers-Walter-Hoving/dp/0394828771

It taught how to eat asparagus, which utensils to use and so on.  The last rule was "break these rules when appropriate."

That admonition holds here.  This is written by programmers for programmers to help make the code more clear.  Just do the right thing.

**Comment by DDvO** [comment]
@mspncp, your points have convinced me that this must be the intended meaning, 
and happily this corresponds to what I see as the most sensible option :)
I do value the idea of not breaking user-visible strings.

For extra clarity, one might re-phrase the sentence in question to:
> However, let long user-visible strings go beyond 80 columns, because breaking them up would limit the ability to grep for them.

**Comment by DDvO** [comment]
@richsalz, I'm glad that you speak for some relaxation here.

So when having a statement involving a long user-visible string such as
```
    if (condition)
        foo(arg1, "long long long long long long long long long long long long long long long msg");
```
what I'll do is to re-format it to
```
    if (condition)
        foo(arg1, 
            "long long long long long long long long long long long long long long long msg");
```
where the string literal goes beyond 80 columns and is even followed by two further chars, namely `);`
