### ISSUE TITLE
It's not possible to export the raw public key for X25519/Ed255919/X448/Ed448

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#6259]
Other algorithms provide low level APIs for getting hold of low level details such as raw key formats. However X5519/Ed25519/X448/Ed448 do not provide this capability (although you can *import* the raw key formats). Arguably this is a bug that should have been done at the same time as the import code.

This causes real problems in practice, e.g. see:

https://stackoverflow.com/questions/50351287/how-to-openssl-1-1-1-ecdh-with-25519/

**Comment by wyllys66** [comment]
Agree, the EVP_PKEY API is lacking functions for accessing parts of X25519 (et al) related keys, for example, it would be good to have:

EC_KEY *EVP_PKEY_get0_X25519_KEY(const EVP_PKEY *key);

and also add support for NID_X25519 so "new_by_curve_name" function works:

EC_KEY *key = EC_KEY_new_by_curve_name(NID_X25519);

**Comment by mattcaswell** [comment]
> it would be good to have:
>
> EC_KEY *EVP_PKEY_get0_X25519_KEY(const EVP_PKEY *key);
> 
> and also add support for NID_X25519 so "new_by_curve_name" function works:
> 
> EC_KEY *key = EC_KEY_new_by_curve_name(NID_X25519);

It won't be implemented quite like this. X25519 is implemented as a standalone algorithm and is not built on top of the EC library, i.e. there is no `EC_KEY` for X25519 hidden away somewhere in the EVP_PKEY. Similarly you will never be able to create an EC_KEY from the X25519 nid because it just doesn't make sense: the EC library doesn't know how to handle curve 25519, so it can't create an EC_KEY for it.

**Comment by wyllys66** [comment]
Thanks for the explanation.  I probably need to read the code more closely or try to find some good examples for using the 25519 APIs.

**Comment by HansN** [comment]
I'd would like to see a way to also export the raw _private_ key.
The case is that when you interface the lib from another language than C (Erlang in this case). Then can't return the EVP_PKEY back the calling language.
If you could get the raw private key also, you would be able to re-construct the first EVP_PKEY easily when it is time for  EVP_PKEY_derive().

**Comment by mattcaswell** [comment]
#6394 adds support for getting raw private and public keys.

**Comment by mattcaswell** [comment]
Ability to export raw private and public keys now added in via #6394.
