### ISSUE TITLE
Regarding TLS-1.3 ClientFinished during post-handshake authentication

### ISSUE THREAD

**Issue by ukartha** [openssl/openssl#6263]
In TLS-1.3 draft section 4.4 [page 65],
base key mentioned for MAC key to be used while generating FinishedMessage
during post handshake authentication is  _client_application_traffic_secret_N_ . But  _client_finished_secret_
is being used regardless of whether it is post-handshake authentication or not.

```

    if (!ssl_handshake_hash(s, hash, sizeof(hash), &hashlen)) {
        /* SSLfatal() already called */
        goto err;
    }

    if (str == s->method->ssl3_enc->server_finished_label)
        key = EVP_PKEY_new_raw_private_key(EVP_PKEY_HMAC, NULL,
                                           s->server_finished_secret, hashlen);
    else
        key = EVP_PKEY_new_raw_private_key(EVP_PKEY_HMAC, NULL,
                                           s->client_finished_secret, hashlen);

    if (key == NULL
            || ctx == NULL
            || EVP_DigestSignInit(ctx, NULL, md, NULL, key) <= 0
            || EVP_DigestSignUpdate(ctx, hash, hashlen) <= 0
            || EVP_DigestSignFinal(ctx, out, &hashlen) <= 0) {
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_TLS13_FINAL_FINISH_MAC,
                 ERR_R_INTERNAL_ERROR);
        goto err;
    }

    ret = hashlen;
 err:
    EVP_PKEY_free(key);
    EVP_MD_CTX_free(ctx);
    return ret;
}

``` 

If `s->post_handshake_auth` is set as `SSL_PHA_REQUESTED` , should we not use `s->client_app_traffic_secret`?

Sorry if I have misread something here.

**Comment by kaduk** [comment]
I believe your analysis is correct; thank you for reporting it!.  @mattcaswell what are your thoughts?

**Comment by mattcaswell** [comment]
Looks correct to me. Fix in #6297.

I'm intrigued to know how you found that! Is there another implementation somewhere that does post handshake authentication? I think this remains untested from an inter op perspective (because no one else had it).

**Comment by ukartha** [comment]
I work for Cavium and we use OpenSSL stack to offload some of the SSL operations during handshake to our crypto accelerator. I noticed the difference from TLS draft while trying to offload post handshake authentication.

**Comment by mattcaswell** [comment]
Ah! Makes sense! Thanks.
