### ISSUE TITLE
util/lib*.num: Tool for checking symbol consistency between minor revisions

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#6274]
According to our policies, symbols which exist in different stable branches that just differ by a minor revision (`master`/`OpenSSL_1_1_1-stable` vs. `OpenSSL_1_1_0-stable`) need to have the same symbol value assigned in libcrypto.num resp. libssl.num. Otherwise, ABI compatibility is violated.

It would be convenient to have a tool that automatically detects inconsistencies like #6272, when new public functions are backported to stable branches.

**Comment by thesamesam** [comment]
FTR, this was done in https://github.com/openssl/openssl/issues/22571.

**Comment by mspncp** [comment]
...and #22589

Thanks for the hint, what a funny coincidence: I actually closed this issue as 'not planned' some days ago due to inactivity.
