### ISSUE TITLE
OpenSSL support for ed25519ph

### ISSUE THREAD

**Issue by ionelm2** [openssl/openssl#6277]
Hello,
as far as I see there is no support for the ed25519ph digital signature algorithm. Is there any plan to add this? 
In terms of effort I think it is not really a big deal since ed25519 is already supported on the 1.1.0 branch and the pre-hashed version only includes additional hashing of the "dom" string.
if no one is already preparing something in this direction, does it make sense that I propose a solution for this (a "pull request" as I learn from the wiki).

Greetings,
Ionel!

**Comment by richsalz** [comment]
It could be useful (it's more work getting all the little bits done then you might first think), but it *is* too late for the upcoming 1.1.1 release.  So maybe, yes, but no rush. :)

**Comment by ionelm2** [comment]
ok, then I would like to start working on this: let's see where I get stuck :D

**Comment by mattcaswell** [comment]
There is already support for ed448ph in the low level primitives. It's just not exposed through EVP at the moment. You might want to take a look at that.

**Comment by JulesRenz** [comment]
Hi, I know this issue has collected quite some dust in the meantime but I am encountering the need to verify x509 certificates, that use ed25519ph as the signature algorithm and have a hard time finding tools that can achieve that.

Any chance, that there has been some progress on this in openSSL?
Many Thanks in advance
Cheers
Julian

**Comment by mattcaswell** [comment]
No progress. The dev team have other significant priorities at the moment so this is unlikely to receive attention anytime soon unless someone else contributes a PR.

**Comment by JulesRenz** [comment]
Hi @mattcaswell , thanks for your feedback, good to know!

**Comment by ViSemih** [comment]
Hello,
I want to ask, is there any new information about supporting the algorithm ED25519ph with OpenSSL?

I really search for a tool, which can create a ED25519ph signature!

BR
Semih

**Comment by mattcaswell** [comment]
Nothing further to add. The dev team continues to be focused on the development of OpenSSL 3.0 (due for release at the end of this year) so this is not a priority. If someone wants to contribute a PR then it would be looked at.

**Comment by JulesRenz** [comment]
Hi @mattcaswell , I suppose there are still no news regarding this algorithm, right? By chance I was revisiting this issue today and found that it has a 1 year aniversary since your last comment - I thought I'd give it a shot ;)

Cheers
Julian

**Comment by mattcaswell** [comment]
Nope - nothing has changed in the last year.

**Comment by paulidale** [comment]
If somebody were to create a pull request, it would be view favourably.  The development team won't get this this until after 3.0.

**Comment by saper** [comment]
When assigning OIDs to Ed22519 and ED448, [IETF decided not to assign OID values to the hashed variants yet](https://datatracker.ietf.org/doc/draft-ietf-curdle-pkix/shepherdwriteup/).

**Comment by jamuir** [comment]
@paulidale :  I have done some work on this, but will need some guidance before I can complete it.

https://github.com/jamuir/openssl/commit/aedb0063

I have created two new internal functions for Ed25519ph sign and verify.

I guess I will need to update `crypto/ec/ecx_meth.c` to expose them to callers.  Is that correct?

**Comment by paulidale** [comment]
The should be exposed via the provider interfaces (which are accessed via EVP).  I.e. in `providers/implementations/signature`
