### ISSUE TITLE
OPENSSL_thread_stop not called when OpenSSL is compiled with no-shared

### ISSUE THREAD

**Issue by Zenju** [openssl/openssl#6283]
When OpenSSL 1.1.0h is compiled with **no-shared** on Windows 10, OPENSSL_thread_stop() is never called, thous memory is leaked for each thread using OpenSSL.

The reason seems to be that on Windows, the only place where OPENSSL_thread_stop() would be called is in \crypto\dllmain.c.
Naturally, dllmain.c doesn't apply for a "no-shared" build.

I'm using the following workaround until further, which gets rid of the memory leaks:

```
struct OpenSslThreadCleanUp
{
    ~OpenSslThreadCleanUp()
    {
        OPENSSL_thread_stop();
    }
};
thread_local OpenSslThreadCleanUp tearDownOpenSslThreadData;
```

**Comment by mattcaswell** [comment]
Yes, this is a known limitation on Windows. See the NOTES section here:

https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_init_crypto.html
