### ISSUE TITLE
Inconsistency with openssl-fips

### ISSUE THREAD

**Issue by nakkore** [openssl/openssl#6287]
openssl 1.0.2n
openssl-fips-2.0.16

During a bug investigation I found an inconsistency which seems to originate in a line missing 
in the openssl-fips file fips_enc.c function FIPS_cipherinit. 

At line 210 
case EVP_CIPH_CTR_MODE:
/* following line  is missing */
 ctx->num = 0;

which in certain circumstances lead to an inconsistency when calling EVP_EncryptUpdate. 
The following code can help reproducing the issue. Intentionally error checking on function returns has been left out for simplicity. 

It's worth noting that the inconsistency is highlighted in the second call to EVP_EncryptInit_ex/EVP_EncryptUpdate/EVP_EncryptFinal_ex in each output generation.

Calling twice EVP_EncryptInit_ex/EVP_EncryptUpdate/EVP_EncryptFinal to calculate out1 and out2 is made intentionally to reproduce the problem. 

void EVPInitBug() {

        static const int IN_MSG_SIZE = 12;

        const unsigned char key[] = "DEAFBEAFCAC0DEAD";
        const unsigned char iv[] = "1111111111111111";

        unsigned char in1[IN_MSG_SIZE];
        unsigned char in2[IN_MSG_SIZE];
        unsigned char out1[IN_MSG_SIZE];
        unsigned char out2[IN_MSG_SIZE];

        int outLen1 = 0;
        int outLen2 = 0;
        int tmplen = 0;

        EVP_CIPHER_CTX ctx1;
        EVP_CIPHER_CTX ctx2;

        memset(in1, 0, IN_MSG_SIZE);
        memset(in2, 0, IN_MSG_SIZE);

        /* FIPS is enabled by default */

        EVP_CIPHER_CTX_init(&ctx1);
        EVP_EncryptInit(&ctx1, EVP_aes_128_ctr(), key, 0);

        /* calculates out1 */        
        EVP_EncryptInit_ex(&ctx1, 0, 0, 0, iv);
        EVP_EncryptUpdate(&ctx1, out1, &outLen1, in1, IN_MSG_SIZE);
        EVP_EncryptFinal_ex(&ctx1, out1 + outLen1, &tmplen);

        /* re-calculates out1 */        
        EVP_EncryptInit_ex(&ctx1, 0, 0, 0, iv);
        EVP_EncryptUpdate(&ctx1, out1, &outLen1, in1, IN_MSG_SIZE);
        EVP_EncryptFinal_ex(&ctx1, out1 + outLen1, &tmplen);

        /* disable FIPS */
        FIPS_mode_set(0);

        EVP_CIPHER_CTX_init(&ctx2);
        EVP_EncryptInit(&ctx2, EVP_aes_128_ctr(), key, 0);

         /* calculates out2 */        
        EVP_EncryptInit_ex(&ctx2, 0, 0, 0, iv);
        EVP_EncryptUpdate(&ctx2, out2, &outLen2, in2, IN_MSG_SIZE);
        EVP_EncryptFinal_ex(&ctx2, out2 + outLen2, &tmplen);

        /* re-calculates out2 */        
        EVP_EncryptInit_ex(&ctx2, 0, 0, 0, iv);
        EVP_EncryptUpdate(&ctx2, out2, &outLen2, in2, IN_MSG_SIZE);
        EVP_EncryptFinal_ex(&ctx2, out2 + outLen2, &tmplen);  

        if (memcmp(out1, out2, IN_MSG_SIZE) == 0) {
            printf("outputs match\n");
        } else {
            printf("outputs don't match\n");
        }       
    }

   

   If IN_MSG_SIZE = 16 the outputs always match: I haven't investigated why.  

   If instead of using  EVP_EncryptInit_ex(&ctx1, 0, 0, 0, iv); the context is initialised with the alternative
   EVP_EncryptInit_ex(&c->ctx, evp,  0, key, iv) then the outputs always match again.
  
   Hope this can help.
   Thank you

**Comment by richsalz** [comment]
Thanks for the report.  We are not touching the FIPS 2.0 code.  I am glad you have a work-around.

**Comment by nakkore** [comment]
I can understand that.
I hope it can be fixed in FIPS 3.x if there will be a 3.x...
Thank you.

**Comment by paulidale** [comment]
Closing this because it's unsupported and impossible to fix without requiring a new FIPS validation.
