### ISSUE TITLE
openssl's interactive mode can't work for multiple commands

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#6292]
It's already been noticed in more than one issue, such as #2795, that trying the `openssl` command in interactive mode may cause errors when certain commands are combined, for example all those using `-config` to load an extra configuration file.

How to solve this remains to be decided.  Cleanup of internal data between commands?  Remove the interactive mode?

**Comment by FdaSilvaYY** [comment]
See also  #4679

**Comment by richsalz** [comment]
This defect is also in 1.1.0 (and probably back to 1.0.2).  Removing the 1.1.1 milestone.

**Comment by dwhitla** [comment]
2 years

**Comment by dwhitla** [comment]
OpenSSL is completely unusable from the command line and has been now for over 2 years. Seriously WTF. Can't create CSRs using -config. Can't sign. Can't validate. How is this such a low priority?
