### ISSUE TITLE
OpenSSL 1.1.1-pre6-dev - Missing alert when receiving an invalid client certificate

### ISSUE THREAD

**Issue by SmallLars** [openssl/openssl#6294]
In our application we are using a RSA-PSK cipher to run a pairing. The server requests a certificate the client needs to provide. When the connection is established, we store the certificate on the server.

After the pairing we can connect with a (EC)DHE-RSA cipher, recognizing the client with the requested certificate we provided by registering it as a CA certificate on the server side.

This works fine, but we are not able to find out if a handshake with (EC)DHE-RSA failed if we deleted the client certificate from the server. After the client sends Certificate, Client Key Exchange, Certificate Verify, Change Cipher Spec and Finished, there is no response (alert) from the server.
There should be an alert with certificate_unknown(46).

I tried to solve this issue in statem_srvr.c::tls_process_client_certificate. After the
```
i = ssl_verify_cert_chain(s, sk);
```
I try to do
```
if (i == 1) {
    if ((s->verify_mode & SSL_VERIFY_PEER) && s->verify_result == X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT) {
        SSLfatal(s, SSL_AD_HANDSHAKE_FAILURE,
                 SSL_F_TLS_PROCESS_CLIENT_CERTIFICATE,
                 SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN);
    }
}
```
But there are two problems:
1. The handshake fails during the RSA-PSK pairing.
2. The alert is still not send.

I think it is the wrong position to fix this issue, but I can not find an other line where s->session->verify_result or s->verify_result is used. Can anyone help me?

**Comment by SmallLars** [comment]
I can force to send the alert by adding a "goto err;". But with this change, the other server messages are send to.

I was able to find out that, even if the certificate check fail, the other messages are generated but not send without my change.

**Comment by mattcaswell** [comment]
Are you using TLSv1.2 (or below) or TLSv1.3? I'm assuming TLSv1.2.

> After the client sends Certificate, Client Key Exchange, Certificate Verify, Change Cipher Spec and Finished, there is no response (alert) from the server.

I'm trying to figure out what you mean by "no response". Does the connection abort, or does the handshake complete without sending an alert, or does the server hang?

````
i = ssl_verify_cert_chain(s, sk);
````
The `i` return value indicates whether the verification was successful or not. If `i` is 1 then it means the verification was successful and the connection can continue. Your suggested change seems to imply that `ssl_verify_cert_chain()` is returning 1. Is that correct? If so, then we need to figure out why that is.

Do you have a custom verification callback in place?

**Comment by SmallLars** [comment]
I am using TLSv1.2, right. "no response" means, that the connection aborts. I am not sure yet, if OpenSSL closes the connection, or the [Qt-Framework](https://www.qt.io/) I use. When I use Wireshark I can see ChangeCipherSpec and Finished in a successfull handshake. Without the provided CA on the server this messages are missing and I also can not see the Alert I excpect.

ssl_verify_cert_chain is returning 1 all the time, right. When I do the pairing with RSA-PSK, s->verify_result is 18 (X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT) and the handshake succeeds. When I use (EC)DHE-RSA without the CA on the Server, s->verify_result is 18 also, but the connection aborts.

The custom verification callback is a great hint, thank you. Need to check the Qt-Framework and my own code.

**Comment by mattcaswell** [comment]
> ssl_verify_cert_chain is returning 1 all the time, right. When I do the pairing with RSA-PSK, s->verify_result is 18 (X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT) and the handshake succeeds. When I use (EC)DHE-RSA without the CA on the Server, s->verify_result is 18 also, but the connection aborts.

So, if I understand you correctly, `ssl_verify_cert_chain` returns 1 even in the case where you are using ECDHE-RSA? And then at some later point (we don't know when) the connection aborts?

In the normal course of events if the verification result indicates a failure (such as X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT) then `ssl_verify_cert()` will return with a value less than 0. It is at that point that OpenSSL will generate the appropriate alert. By using a custom verification callback you can override that behaviour to force the verification to succeed anyway. Presumably somewhere in your code that is happening in order for the PSK connection to go through without complaining. If I've understood all of the above correctly then it looks to me like the custom callback is succeeding even in the ECDHE-RSA case - which is why you don't see the alert being sent. I can't explain why the connection then goes on to abort though.

**Comment by SmallLars** [comment]
> So, if I understand you correctly, ssl_verify_cert_chain returns 1 even in the case where you are using ECDHE-RSA? And then at some later point (we don't know when) the connection aborts?

Right, return value is 1 all the time. With (EC)DHE-RSA and registered CA certificate s->verify_result is 0. Without registered CA certificate s->verify_result is 18. We use a callback that ignores the 18 during RSA-PSK, but not during (EC)DHE-RSA.

The callback happens, after the generation of TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CHANGE and TLS_ST_SW_FINISHED.
The messages are generated even if s->verify_result is 18.

When I use the code from my first post:
```
if (i == 1) {
    if ((s->verify_mode & SSL_VERIFY_PEER) && s->verify_result == X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT) {
        SSLfatal(s, SSL_AD_HANDSHAKE_FAILURE,
                 SSL_F_TLS_PROCESS_CLIENT_CERTIFICATE,
                 SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN);
    }
}
goto err;
```
the Alert is send together with the 4 generated messages, but that can not be right. I try to find a line of code where s->verify_result or s->session->verify_result is evaluated after the callback to clear the generated messages and generate an Alert. But I did not succeed. Can you help me to find the location where that should happen?

**Comment by mattcaswell** [comment]
> Right, return value is 1 all the time.

The return code from this function determines whether to send an alert or not. If the verification fails (i <= 0) then the alert gets sent. If it's 1 then this indicates success, no alert gets sent, and processing continues.

Adding the code you are suggesting is wrong. You should not be conditionally trying to send an alert if i == 1. Instead we need to figure out why i is 1 in the first place. If you are expecting an alert to be sent and the connection to abort then i needs to be <= 0.

> The callback happens, after the generation of TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CHANGE and TLS_ST_SW_FINISHED.

This doesn't sound right. The callback should happen before the generation of those messages, on receipt of the certificate from the client.

The function `ssl_verify_cert_chain()` invokes the X509 certificate validation. The last step is to invoke the callback with the result. If some result other than `X509_V_OK` is obtained then we expect the callback to return some value <=0. It is this value that gets passed back through the stack and is the return value from `ssl_verify_cert_chain()`.

My suggestion would be to place a breakpoint on this line:

https://github.com/openssl/openssl/blob/master/crypto/x509/x509_vfy.c#L162

We expect to get here after the internal verification has occurred but immediately before the callback is invoked. You will probably find the breakpoint is hit during the construction of the server certificate chain (which isn't interesting to us). Just let the execution continue until we hit the breakpoint and the backtrace indicates that we have been invoked (via a number of other functions) by `tls_process_client_certificate`.

At this point we expect the `err` variable to be `X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT`. Step into the callback and see how the return value gets to be set to 1, and check how that propagates back through the stack until you're back in the `tls_process_client_certificate` function. Hopefully that should give us the hint as to what is going on.

**Comment by SmallLars** [comment]
Thanks alot. Finally I found the right callback in Qt and the root cause of my problem:
https://code.woboq.org/qt5/qtbase/src/network/ssl/qsslsocket_openssl.cpp.html#215

**Comment by mattcaswell** [comment]
Great. Glad you figured out what was happening. Closing this issue.
