### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by dioubernardo** [openssl/openssl#6300]
After the update the error Verify return code: 20 (unable to get local issuer certificate) is shown

This occurs when executing the command
openssl s_client -connect g1.globo.com:443

It does not occur on all sites, but several sites are experiencing this. When I open the same in chrome or firefox the error is not shown, apparently the certificates are valid.

I tested it on
Ubuntu 14.04 - OpenSSL 1.0.1f 6 Jan 2014
Ubuntu 16.04 - OpenSSL 1.0.2g 1 Mar 2016

**Comment by richsalz** [comment]
What is going on is that the browsers have a list of CA's that they trust.  OpenSSL provides no such list.  Some distro's include a "trust list" with their repackaging of OpenSSL.

You can use s_client to capture the cert chain, and put the CA's into a directory (one cert/file) that you trust via an s_client command-line flag.

Closing this.
