### ISSUE TITLE
OpenSSL 1.0.2o Compilation warning/error rsa_oaep.c: error: 'dblen' may be used uninitialized in this function 

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#6301]
Compiler: gcc 4.8.5

With some of the recent changes added to rsa_oaep.c adding OPENSSL_cleanse() functions, it looks like a compiler warning is being generated. When used with -Werror this causes a compilation failure.

**Comment by richsalz** [comment]
We don't support -Werror on the 1.0.2 releases.  Yes there are some code-cleanup things in that release.  I am going to close this.

**Comment by mlindner** [comment]
-Werror works however on the 1.0.2 release before this though? It also continues to work if this one issue is fixed...

**Comment by mlindner** [comment]
Thank you very much.

**Comment by mattcaswell** [comment]
Linked PR was merged so closing.
