### ISSUE TITLE
1.1.1-pre6 includes unwanted ciphers in Client Hello

### ISSUE THREAD

**Issue by securityguy** [openssl/openssl#6309]
When SSL_CTX_set_cipher_list() is used to set ciphers, version 1.1.1-pre6 includes additional unwanted ciphersuites in the Client Hello message.

This is verified not to occur with 1.1.0h

This behaviour can be observed using:

openssl s_client -connect google.com:443 -cipher NULL-MD5:@SECLEVEL=0

and looking at the client hello message with wireshark.

**Comment by richsalz** [comment]
Is it the TLS 1.3 ciphers?  Those are set separately.

**Comment by securityguy** [comment]
Yes, they are. Thank you!
