### ISSUE TITLE
Server rejects 0-RTT with SSL_SESS_CACHE_NO_INTERNAL_LOOKUP

### ISSUE THREAD

**Issue by tatsuhiro-t** [openssl/openssl#6313]
My server has external session cache which can be shared with multiple servers.  Internal cache cannot be used because it is useless if a client hits different server on resumption.
In order to check that external cache works, I set SSL_SESS_CACHE_NO_INTERNAL_LOOKUP in my server.  Unfortunately, this makes server reject 0-RTT request.  I observed that callback function set by SSL_CTX_sess_set_remove_cb is called, but it does not affect anything because its return value is void. Is this expected behaviour?

If anti replay only works with internal cache, it would be nice to have an option to disable it, and just do https://tools.ietf.org/html/draft-ietf-tls-tls13-28#section-8.3
This is because a callback set by SSL_CTX_sess_set_remove_cb does not return a value, so one cannot know that session is really removed or not.

**Comment by mattcaswell** [comment]
> If anti replay only works with internal cache, it would be nice to have an option to disable it,

Yes, anti-replay only works with the internal cache. I can look into an option to disable it.

**Comment by mattcaswell** [comment]
An option to disable anti-replay has now been implemented. Closing this issue.
