### ISSUE TITLE
Curve wap-wsg-idm-ecid-wtls7 is incorrect according to WTLS specification

### ISSUE THREAD

**Issue by cygnusv** [openssl/openssl#6317]
I've been fuzzing `EC_POINT_is_on_curve()` lately (see #6302) and noticed something strange with one of the WTLS curves. The [WTLS specification](http://www.openmobilealliance.org/tech/affiliates/wap/wap-261-wtls-20010406-a.pdf) defines several curves; in particular, in page 86, it defines curve `wap-wsg-idm-ecid-wtls7` to be a mere alias of `secp160r1`. However, for some reason, in OpenSSL this curve is defined to be `secp160r2`  ([link](https://github.com/openssl/openssl/blob/master/crypto/ec/ec_curve.c#L2950)):

```
    {NID_wap_wsg_idm_ecid_wtls7, &_EC_SECG_PRIME_160R2.h, 0,
     "SECG/WTLS curve over a 160 bit prime field"},
```

I would make a pull request with the required changes since they seem trivial, but I'm concerned with the implications about interoperability (this seems to happen for at least the last 16 years). In case the problem is confirmed, what would be the best way to proceed?

**Comment by richsalz** [comment]
16 years?  Wow.  At any rate, this is also in 1.0.2 and 1.1.0, so it is not strictly a 1.1.1 issue; removing that milestone.

**Comment by cygnusv** [comment]
If this problem has gone unnoticed for 16 years, then it perhaps means that (almost) nobody is using this curve (and perhaps other WTLS curves). Any idea of who may be using it as for 2018?

**Comment by t8m** [comment]
There is probably no point in fixing this after all these years. The curve should not be used anymore as it is too weak.
