### ISSUE TITLE
openssl verify problem

### ISSUE THREAD

**Issue by cucushift** [openssl/openssl#6320]
hi folks，when i use `openssl verify` to verify crt，giving the result as follows
```
[root]# openssl verify -CAfile ca.crt server.crt
server.crt: OK
```

```
[root]# openssl verify -CAfile  server.crt ca.crt
ca.crt: OK
```
> ca.crt sighed  server.crt 

**is that right result？**

**Comment by richsalz** [comment]
The cafile is a set of certs that could be used.  If ca.crt is self-signed, then the CA's listed in the file are not consulted.  So yes, this is working as designed.

**Comment by cucushift** [comment]
@richsalz 
> If ca.crt is self-signed, then the CA's listed in the file are not consulted. 

can you give me more information, I don't really understand it. thanks.

**Comment by richsalz** [comment]
I don't have time to write a tutorial, sorry.
