### ISSUE TITLE
issues about decode data after shakehands and after received some data.

### ISSUE THREAD

**Issue by junbrave1** [openssl/openssl#6325]
hi, 
i am suffered an error for days. 
we have a smtp server uses openssl 1.0.2j and boost 1.51.0. 
most of the time it works pretty well.

some times, the boost function "async_read_some" throws an error "nested asn1 error" or "too long". and after some time, if the client reconnect and send the data again, it will possibly succeed. 

i have searched the code, the error message is raised by openssl. the definition is that:

err.c
static ERR_STRING_DATA ERR_str_reasons[] {
	...
	{ERR_R_NESTED_ASN1_ERROR, "nested asn1 error"},
	...
}

asn1_err.c
static ERR_STRING_DATA ASN1_str_reasons[] = {
	...
	{ERR_REASON(ASN1_R_TOO_LONG), "too long"},
	...
}

below is our function witch binded to boos async_read_some.

if(m_bStarttls)
{
	m_sslSocket->async_read_some(boost::asio::buffer(pBase, nSize),
								 boost::bind(&Connection::handleReadMailData,
								 shared_from_this(),
								 msgBlkPtr,
								 boost::asio::placeholders::error,
								 boost::asio::placeholders::bytes_transferred));
	return;
}

void Connection::handleReadMailData(MessageBlockPtr msgBlkPtr, const boost::system::error_code& err, size_t nTransferedBytes)
{
	if(err)
	{
		SVC_LOG(err.value(), err.message().c_str()));
		stop();
		return;
	}	
	...
}

anybody ever encounter this problem?

can some one please figure out what the possible reason?

**Comment by junbrave1** [comment]
there is more infomation.
some time it failed in the function: asn1_d2i_ex_primitive
 ret = asn1_check_tlen(NULL, &utype, &oclass, NULL, NULL,
                              &p, inlen, -1, 0, 0, ctx);
        if (!ret) {
            ASN1err(ASN1_F_ASN1_D2I_EX_PRIMITIVE, ERR_R_NESTED_ASN1_ERROR);
            return 0;
        }
		
the error code is:		
218546234
the error message is:
nested asn1 error

-------------------------------------------------------------------------------------------
some time it failed in the function: ASN1_get_object
if (*plength > (omax - (p - *pp))) {
        ASN1err(ASN1_F_ASN1_GET_OBJECT, ASN1_R_TOO_LONG);
        /*
         * Set this so that even if things are not long enough the values are
         * set correctly
         */
        ret |= 0x80;
    }
		
the error code is:		
218570907
the error message is:
too long

**Comment by junbrave1** [comment]
more infomation:

to avoid the possible crash risk of openssl renegotiation, we set the callback function:
SSL_CTX_set_info_callback(ctx, ssl_callback_Info);
if the renegotiation occurs, we close the connection.
the code is like bellow:
`void ssl_callback_Info(const SSL *ssl, int where, int rc)
{
	Connection *conn = (Connection *)SSL_get_app_data(ssl);
	if (conn == NULL){
		return ;
	}
	if ((where & SSL_CB_ACCEPT_LOOP) && conn->m_shake_status == 1) {
		int state = SSL_get_state((SSL *)ssl);
		if (state == SSL3_ST_SR_CLNT_HELLO_A
				|| state == SSL23_ST_SR_CLNT_HELLO_A) {
			conn->m_shake_status = 2;
			conn->socket().close();
		}
	}
}`
did i do something wrong?  i the decoding failure likely to be related to this behavior?

**Comment by mattcaswell** [comment]
It would help if you are able to capture the network traces (e.g. via wireshark) of a failing connection.

**Comment by richsalz** [comment]
It is not right to close the socket in the callback.
If you want to prevent renegotiation, there is an ```SSL_OP``` flag for that.

**Comment by junbrave1** [comment]
@mattcaswell thanks, but unfortunately i can not do that. it happens not too many times, and it is running in the production environment.  there are huge numbers of connections.

**Comment by junbrave1** [comment]
@richsalz thank you for your advice.  
i do not understand. because i did not know so much about openssl.  
if I disable heavy negotiation, does it mean that clients will cause problems if they initiate negotiations?

i want to retain the ability to renegotiate but want to avoid a vulnerability to renegotiation.
some more advice about this? 
is it sufficient to upgrade to the latest version?

thank you again, waiting for your reply.

**Comment by richsalz** [comment]
*   i want to retain the ability to renegotiate but want to avoid a vulnerability to renegotiation.
some more advice about this?
is it sufficient to upgrade to the latest version?



Which vulnerability?



But yes, upgrade

**Comment by junbrave1** [comment]
thanks!


security scans from government found that our smtp server had ssl reconnection security vulnerabilities so we disable it.

i don't know so much about the detail.

maybe something like below:
https://www.digicert.com/news/2011-06-03-ssl-renego/
and:
https://scottlinux.com/2011/11/03/how-to-check-for-ssl-renegotiation/

**Comment by richsalz** [comment]
I am sorry, but there's really no information for us to work with here.  Such as what version you are using, what flags are used to create connections, what the vulnerability report is, and so on.

I am going to have to close this issue.  Upgrade to the latest openssl release branch, maybe that will help.  Good luck.
