### ISSUE TITLE
#error "Need GCC 4.0 or later to define type uint128_t"

### ISSUE THREAD

**Issue by andreasschulze** [openssl/openssl#6327]
is GCC 4.0 a strict requirement?

I compile openssl-1.1.0* with "CONFARGS += enable-ec_nistp_64_gcc_128"

Now, for 1.1.1-pre6 I get that error:
crypto/ec/ecp_nistp224.c:48:4: error: #error "Need GCC 4.0 or later to define type uint128_t"

on SLES11 I've to use gcc-4.3.

will try to disable enable-ec_nistp_64_gcc_128 ...

**Comment by andreasschulze** [comment]
ups, so I *do* use gcc > 4.0 and should not get a this error?

**Comment by andreasschulze** [comment]
btw. disabling enable-ec_nistp_64_gcc_128 helps also...
But should I *want* to disable the optimized code?

**Comment by levitte** [comment]
You should not get that error.  However, you might want to check that your compiler actually defines the macro we check:

```
cc -dM -E -x c /dev/null | grep INT128
```

If it does provide support for `uint128_t`, that command should output something like this:

```
#define __SIZEOF_INT128__ 16
```

**Comment by andreasschulze** [comment]
it doesn't

to give you a view: # cc -dM -E -x c /dev/null | grep SIZEOF
#define __SIZEOF_INT__ 4
#define __SIZEOF_POINTER__ 8
#define __SIZEOF_LONG__ 8
#define __SIZEOF_LONG_DOUBLE__ 16
#define __SIZEOF_SIZE_T__ 8
#define __SIZEOF_WINT_T__ 4
#define __SIZEOF_PTRDIFF_T__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_WCHAR_T__ 4
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_LONG_LONG__ 8

cc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux)

**Comment by mattcaswell** [comment]
Probably the error message "Need GCC 4.0 or later to define type uint128_t" is misleading given @dot-asm's comment above.

**Comment by levitte** [comment]
I agree with @mattcaswell, the message needs to change.  Also, from looking around a bit, it seems that checking `__SIZEOF_INT128__` is more correct than going for specific GCC versions in any case, so it's possible we should change that condition in the release branches as well.

**Comment by levitte** [comment]
Also, since master has better control of predefined macros when configuring, it might be a good thing to diagnose and affect the `ec_nistp_64_gcc_128` option already then...

**Comment by levitte** [comment]
@andreasschulze, #6328 might at least give you better diagnostics.  Are you willing to give it a shot?

**Comment by andreasschulze** [comment]
without actual trying that:
- the error text is more descriptive
- the error condition in configure looks "$ trivial and no so wrong :-)"
I cannot say if I find time to rebuild with this modification because it's much easier to me to build from a published tar.gz
