### ISSUE TITLE
crypt(3) over OpenSSL API

### ISSUE THREAD

**Issue by minibuild** [openssl/openssl#6334]
Guys,  
I've done a tiny work where I used some code directly from [apps/passwd.c](https://github.com/openssl/openssl/blob/master/apps/passwd.c)
My intention was to have platform agnostic implementation of [crypt(3)](http://man7.org/linux/man-pages/man3/crypt.3.html) without explicit dependence to `link with -lcrypt`, so the only dependence there is OpenSSL API.

__I hope that I don't violate OpenSSL License__.  If you are concerned about, please check it,  
it is here on github - https://github.com/minibuild/openssl_posix_crypt
Otherwise just close this issue.

**Comment by mattcaswell** [comment]
IANAL but since you released your derived work under the same licence terms as OpenSSL it looks fine to me.
