### ISSUE TITLE
Testing new pkey methods in ENGINE

### ISSUE THREAD

**Issue by APOB83** [openssl/openssl#6339]
Hey, I've created a new ENGINE for openSSL that supports new public key methods not currently supported in openSSL. I'm trying to figure out how I can make openSSL calls from the command line to run the pkey methods for keygen, encrypt, decrypt. Is there a way to do this? I can generate a new NID (with OBJ_create) and register the pkey methods using the various EVP_PKEY_meth_set_x() calls, but I'm just stuck on how to actually call these methods from the command line. Any pointers appreciated.

**Comment by mattcaswell** [comment]
Many of the OpenSSL command line applications enable you to specify an engine with the "-engine" flag, e.g. genpkey, pkey, enc all have this option.
