### ISSUE TITLE
opensslconf.h or opensslconf.h.in

### ISSUE THREAD

**Issue by SouthHalfCents** [openssl/openssl#6345]
why there's no openssl/opensslconf.h any more?

**Comment by SouthHalfCents** [comment]
there is no "opensslconf.h" file in newest version, only "opensslconf.h.in"..... libcurl need to include "openssl/opensslconf.h"

**Comment by mattcaswell** [comment]
opensslconf.h is a file that is generated when you build OpenSSL. Have you built and installed OpenSSL?

**Comment by levitte** [comment]
If you downloaded the source distribution, you need to configure, build and install it before you can use it. This is normal operation.

**Comment by SouthHalfCents** [comment]
thank you, it's ok now  (￣▽￣)／
