### ISSUE TITLE
Enabling OPENSSL_NO_EC2M on OpenSSL 1.0.2 keeps invalid ciphers in "openssl speed" causing errors

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#6351]
$ openssl speed ecdsa
Doing 160 bit sign ecdsa's for 10s: 144893 160 bit ECDSA signs in 9.89s 
Doing 160 bit verify ecdsa's for 10s: 44082 160 bit ECDSA verify in 9.93s
Doing 192 bit sign ecdsa's for 10s: 131793 192 bit ECDSA signs in 9.94s 
Doing 192 bit verify ecdsa's for 10s: 38013 192 bit ECDSA verify in 9.95s
Doing 224 bit sign ecdsa's for 10s: 97271 224 bit ECDSA signs in 9.93s 
Doing 224 bit verify ecdsa's for 10s: 28255 224 bit ECDSA verify in 9.93s
Doing 256 bit sign ecdsa's for 10s: 218582 256 bit ECDSA signs in 9.93s 
Doing 256 bit verify ecdsa's for 10s: 99796 256 bit ECDSA verify in 9.93s
Doing 384 bit sign ecdsa's for 10s: 49205 384 bit ECDSA signs in 9.90s 
Doing 384 bit verify ecdsa's for 10s: 10970 384 bit ECDSA verify in 9.83s
Doing 521 bit sign ecdsa's for 10s: 23063 521 bit ECDSA signs in 9.91s 
Doing 521 bit verify ecdsa's for 10s: 5617 521 bit ECDSA verify in 9.78s
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
ECDSA failure.
140736204276680:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:ec_curve.c:3179:
OpenSSL 1.0.2o  27 Mar 2018
built on: reproducible build, date unspecified
options:bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx) 
compiler: cc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_EC2M -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
                              sign    verify    sign/s verify/s
 160 bit ecdsa (secp160r1)   0.0001s   0.0002s  14650.5   4439.3
 192 bit ecdsa (nistp192)   0.0001s   0.0003s  13258.9   3820.4
 224 bit ecdsa (nistp224)   0.0001s   0.0004s   9795.7   2845.4
 256 bit ecdsa (nistp256)   0.0000s   0.0001s  22012.3  10049.9
 384 bit ecdsa (nistp384)   0.0002s   0.0009s   4970.2   1116.0
 521 bit ecdsa (nistp521)   0.0004s   0.0017s   2327.2    574.3
 163 bit ecdsa (nistk163)   0.0000s   0.0000s      inf      inf
 233 bit ecdsa (nistk233)   0.0000s   0.0000s      inf      inf
 283 bit ecdsa (nistk283)   0.0000s   0.0000s      inf      inf
 409 bit ecdsa (nistk409)   0.0000s   0.0000s      inf      inf
 571 bit ecdsa (nistk571)   0.0000s   0.0000s      inf      inf
 163 bit ecdsa (nistb163)   0.0000s   0.0000s      inf      inf
 233 bit ecdsa (nistb233)   0.0000s   0.0000s      inf      inf
 283 bit ecdsa (nistb283)   0.0000s   0.0000s      inf      inf
 409 bit ecdsa (nistb409)   0.0000s   0.0000s      inf      inf
 571 bit ecdsa (nistb571)   0.0000s   0.0000s      inf      inf

**Comment by t8m** [comment]
This is fixed in 1.1.1 and master. Closing.
