### ISSUE TITLE
Why Ed25519 private key length is 34 bytes?

### ISSUE THREAD

**Issue by zensh** [openssl/openssl#6357]
I parsed https://github.com/openssl/openssl/blob/master/test/certs/server-ed25519-cert.pem

it's public key is `0a410c8fe4912e3652b61dd222b1b4d7773261537d7ebad59df6cd33622a693e`, 32 bytes, it is right.

I parsed https://github.com/openssl/openssl/blob/master/test/certs/server-ed25519-key.pem as PKCS#8

it's private key is `0420d6b9fc4d48cee48b835af0a07c65d5557b05d72798c7ae97da6fb2fccaa2b8e6`, 34 bytes, but not 64 bytes, why?

**Comment by mattcaswell** [comment]
Private and public keys in Ed25519 are 32 bytes (not sure why you expect 64 for the private key). RFC8032 defines Ed25519 and says:

> An EdDSA private key is a b-bit string k

It then defines the value b as being 256 for Ed25519, i.e. a private key is 256 bits (== 32 bytes).

PKCS#8 is a standard for storing private keys for all sorts of different algorithms. The format is basically an integer version number, an object identifier to identify the algorithm, and an OCTET STRING for the private key data. The format of the private key data could be anything depending on the algorithm. It might be ASN.1 data inside the OCTET STRING or something else.

This document defines what that is for Ed25519 private keys:
https://tools.ietf.org/html/draft-ietf-curdle-pkix-10

What it says is that *inside* the OCTET STRING is another OCTET STRING for the private key data. The ASN.1 tag for OCTET STRING is 0x04, and the length of that string is 32 bytes (0x20 in hex). 

> it's private key is 0420d6b9fc4d48cee48b835af0a07c65d5557b05d72798c7ae97da6fb2fccaa2b8e6, 34 bytes, but not 64 bytes, why?

So in the above string the leading `0420` is the OCTET STRING tag and length. The remaining 32 bytes are the key itself.

**Comment by zensh** [comment]
@mattcaswell Got it. Thank you very much.
My old "private key" is signing key, must include public key, so `PrivateKeySize` is `64`. This is used widely，such as:

In Golang: https://github.com/golang/crypto/blob/a3beeb748656e13e54256fd2cde19e058f41f60f/ed25519/ed25519.go#L31
In tweetnacl-js: https://github.com/dchest/tweetnacl-js#naclsignsecretkeylength--64

Almost all ed25519 implementations' keypair() function will return 64 bytes SigningKey
https://blog.mozilla.org/warner/2011/11/29/ed25519-keys/

**Comment by davidben** [comment]
Yeah, as the chart in that blog post suggests, there's lots of different formulations of Ed25519 private keys. :-) The in-memory representation will likely keep the public key around with the private key to save work for each signature. My impression is that combined representation was also common for the serialized private key.

The IETF formulation diverges from this and treats only the "seed" as the private key. That means you need to do some format-munging depending on which direction you're trying to convert things. On the OpenSSL side, that means APIs to get at the raw representation of the key would be handy, similar to how RSA `EVP_PKEY`s expose the underlying `RSA` object via `EVP_PKEY_get0_RSA`. On the side of existing implementations, an API like BoringSSL's `ED25519_keypair_from_seed` may be handy. I've been meaning to upstream such an API for the Go stack.

**Comment by mattcaswell** [comment]
> On the OpenSSL side, that means APIs to get at lower-level serializations of the key would be handy

There's already an API for importing raw keys, but nothing for exporting them from OpenSSL, hence #6259.

**Comment by davidben** [comment]
> I've been meaning to upstream such an API for the Go stack.

Here we are: https://go-review.googlesource.com/#/c/115297/
