### ISSUE TITLE
openssl-1.1.1-pre6  "what pkeyopt should be when sign, verify using sm2 key  in command line"

### ISSUE THREAD

**Issue by horshine** [openssl/openssl#6359]
I Generate SM2 key:
#openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2  -out signkey.pem

but how to sign and verify, I don't know what the pkeyopt should be
#openssl pkeyutl -sign -pkeyopt ec_paramgen_curve:sm2 -inkey  signkey.pem -in abc.txt -out abc.txt.sig

I'm new on openssl, thanks for help.

**Comment by mattcaswell** [comment]
Unfortunately it is not currently possible to do this via the command line in 1.1.1.

I created #6719 to track the feature request to add that capability. Closing this.
