### ISSUE TITLE
libsourcey compilation fails

### ISSUE THREAD

**Issue by RanjKuru** [openssl/openssl#6361]
I try to compile libsourcey with openssl. But this is the result
`In file included from /srv/Workspaces/Sandbox/libsourcey/src/crypto/src/hash.cpp:12:0:
/srv/Workspaces/Sandbox/libsourcey/src/crypto/include/scy/crypto/hash.h:56:16: error: field ‘_ctx’ has incomplete type ‘EVP_MD_CTX {aka evp_md_ctx_st}’
     EVP_MD_CTX _ctx;
                ^~~~
In file included from /usr/local/include/openssl/evp.h:14:0,
                 from /srv/Workspaces/Sandbox/libsourcey/src/crypto/include/scy/crypto/hash.h:20,
                 from /srv/Workspaces/Sandbox/libsourcey/src/crypto/src/hash.cpp:12:
/usr/local/include/openssl/ossl_typ.h:92:16: note: forward declaration of ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
 typedef struct evp_md_ctx_st EVP_MD_CTX;
                ^~~~~~~~~~~~~
crypto/CMakeFiles/crypto.dir/build.make:110: recipe for target 'crypto/CMakeFiles/crypto.dir/src/hash.cpp.o' failed
make[2]: *** [crypto/CMakeFiles/crypto.dir/src/hash.cpp.o] Error 1
CMakeFiles/Makefile2:828: recipe for target 'crypto/CMakeFiles/crypto.dir/all' failed
make[1]: *** [crypto/CMakeFiles/crypto.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
`
The problem, is that EVP_MD_CTX is defined inside evp_loclh.h. But that is not even inside the openssl. I tried cmake, make and sudo make install, it never worked.

**Comment by richsalz** [comment]
It looks like libsourcey does not support 1.1.0, which made most structures opaque.  You have to use an earlier release.

**Comment by kroeckx** [comment]
Or you need to modify the source to allocate that structure
instead.

**Comment by talma** [comment]
hash.h line 56: 
    EVP_MD_CTX* _ctx;

x509certificate.cpp lines 62-63:
//        _certificate->references++;
         X509_up_ref(_certificate); // OpenSSL >= 1.1.0

hash.cpp (compared against 5/10/17 8:58PM revision)
line 44: 
    EVP_MD_CTX_free(_ctx);

lines 52-53
//    internal::api(EVP_MD_CTX_cleanup(&_ctx));
    internal::api(EVP_DigestInit(_ctx, _md));

line 60:
    internal::api(EVP_DigestUpdate(_ctx, data, length));

line 82:
        internal::api(EVP_DigestFinal(_ctx, &_digest[0], &len));
