### ISSUE TITLE
Syntax error initializing x64 commands to install 

### ISSUE THREAD

**Issue by richardlittlej6** [openssl/openssl#6365]
Well, this program definitely works best with Perl for x64bit Windows, however I am getting numerous errors for the file (path: openssl\Configurations) windows-makefile template that need debugged. Also installs fine with cynwin same error with file.
![err2](https://user-images.githubusercontent.com/21162712/40619177-9aa00ad6-6283-11e8-954b-95e722380b82.PNG)

**Comment by dot-asm** [comment]
Well, you might as well pass .c file to perl and complain about that. As already said in another request, this is not place for general Q&A. Actually, there is no place for *such* Q&A, ones that are described in accompanying documentation. I mean even when you turn to users mail list, it's implied that you read something. So I'd suggest to do that, read all accompanying documentation. Especially note that INSTALL refers to OS-specific NOTES...
