### ISSUE TITLE
Doesn't build on OS/X

### ISSUE THREAD

**Issue by nigelhorne** [openssl/openssl#6375]
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _all
make[1]: *** No rule to make target `crypto/include/internal/cryptlib.h', needed by `crypto/aes/aes_ige.o'.  Stop.
make: *** [all] Error 2
hornenj@home:~/src/openssl$ find . -name cryptlib.h
./include/internal/cryptlib.h
hornenj@home:~/src/openssl$ ls crypto/include/internal/
__DECC_INCLUDE_EPILOGUE.H	engine.h
__DECC_INCLUDE_PROLOGUE.H	err_int.h
aria.h				evp_int.h
asn1_int.h			md32_common.h
async.h				objects.h
bn_conf.h			poly1305.h
bn_conf.h.in			rand_int.h
bn_dh.h				sha.h
bn_int.h			siphash.h
bn_srp.h			sm3.h
chacha.h			sm4.h
cryptlib_int.h			store.h
ctype.h				store_int.h
dso_conf.h			x509_int.h
dso_conf.h.in

**Comment by nigelhorne** [comment]
I ran this command, then 'make' and 'make test' both worked.

`ln include/internal/cryptlib.h crypto/include/internal/`

**Comment by richsalz** [comment]
Yes,you have to follow the instructions.  Closing this issue.

**Comment by nigelhorne** [comment]
> Also you're not even calling the correct make. Don't access it from within the Xcode.app. 

I typed 'make' at the command line, I did not "access from within the Xcode.app" as you suggest.

**Comment by nigelhorne** [comment]
> Please read the readme before filing issues.
> 
> https://wiki.openssl.org/index.php/Compilation_and_Installation

Sorry my ESP chip didn't work.  There is no mention of this important stage on the README at https://github.com/openssl/openssl.

**Comment by levitte** [comment]
Oh!  Could it be that you placed new source in a spot where you had files from an older build remaining?  See, `cryptlib.h` moved in august last year (commit 67dc995eaf538ea309c6292a1a5073465201f55b), so if you still have dependency files from that time lying around, the error you get makes sense, although unfortunate.

Please try `make clean` before `make`, and if that doesn't help, try this:

```
find /src/openssl -name '*.d' | xargs rm
```
