### ISSUE TITLE
Recent change in OpenSSL 1.0.2n (or m?) caused NULL pointer dereference

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#6381]
Pull request: #4836

This change can cause a null pointer dereference to occur at https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/engine/tb_asnmth.c#L218

When pkey_asn1_meths returns, if it doesn't support the nid, then it returns NULL and doesn't set ameth. This causes "ameth->pem_str" to segfault. This can happen after the engine calls ENGINE_set_pkey_asn1_meths to give its supported methods. look_str_cb seems to ignore those supported methods and always tries to access the ameth even if it doesn't exist.

To be specific this segfault happens during SSL_library_init/OPENSSL_init_ssl.

**Comment by levitte** [comment]
Can you check if #6383 fixes the issue for you?

**Comment by mlindner** [comment]
I can tell just from looking that it will fix the segfault, but I'm not sure what additional repercussions may occur. I was wondering if there was a more correct way to write the pkey_asn1_meths function. Is there documentation on this somewhere? I couldn't find any on the API of pkey_asn1_meths.

**Comment by levitte** [comment]
It's documented in 1.1.0.  And no, there's not a "more correct" way to do this, as new ASN1 methods are only needed once for each object type, so unless an engine implements a whole new type of key (GOST is the one example we currently have), there's not need to implement any ASN1 method.

**Comment by levitte** [comment]
Thank you

**Comment by mlindner** [comment]
Hi levitte can you point me to that documentation on the API? I couldn't locate it.

**Comment by mlindner** [comment]
Looking at this more, I'm wondering if there's not a better fix. I'm wondering how this null pointer dereference even occurred in the first place. Like why does look_str_cb even get called on this when it knows that there's no supported nid as specified in engine_table_register? There may be a bug in the registry function itself in ENGINE_pkey_asn1_find_str/engine_table_doall. It should be able to confirm that the nid isn't in the nid list because it was already given in engine_table_register.
