### ISSUE TITLE
Rename OpenSSL to OpenTLS To Comply with RFC7568

### ISSUE THREAD

**Issue by jandrusk** [openssl/openssl#6384]
It's 2018 and 'SSL' is now a deprecated term given RFC7568 along with the POODLE and BEAST vulnerabilities that explicitly require the disabling of the SSL protocols. I move to have OpenSSL re-branded to OpenTLS to comply with RFC7568 and to eliminate confusion.

**Comment by richsalz** [comment]
The OpenSSL "brand" is very recognized.  We're not going to do this.

**Comment by richsalz** [comment]
Another team member pointed out that I might be too harsh.  Perhaps better is "we have no plans to do this at this time."

**Comment by jandrusk** [comment]
The name doesn't reflect reality.

**Comment by richsalz** [comment]
But it does have mindshare and reflect history. :)

**Comment by mspncp** [comment]
> I move to have OpenSSL re-branded to OpenTLS to comply with RFC7568 and to eliminate confusion.

FWIW: Today I stumbled over a very interesting historical fact about the rebranding of OpenSSL: Initially, when it emerged from SSLeay, it was called OpenTLS and only later on renamed to OpenSSL:

```
commit f1c236f849d9799a5de0ad1f6c64b33291f60c84
Author: Ralf S. Engelschall <rse@openssl.org>
Date:   Wed Dec 23 07:38:54 1998 +0000

    Switch to OpenSSL name
```
(see f1c236f849d9) 

```
commit c537fb08cd93c3c564478e6a238e502a7d17e216
Author: Ralf S. Engelschall <rse@openssl.org>
Date:   Tue Dec 22 16:01:06 1998 +0000

    OpenTLS ready
```
(see c537fb08cd93)

```
commit 651d0aff98d28e2db146afa1790e9e22f3ef22db
Author: Ralf S. Engelschall <rse@openssl.org>
Date:   Tue Dec 22 15:04:48 1998 +0000

    Various cleanups and fixed by Marc and Ralf to start the OpenTLS project
```
(see 651d0aff98d2)

**Comment by mspncp** [comment]
Ok, looking a bit closer at the dates: it was called OpenTLS for less than a day ;-)

**Comment by iamamoose** [comment]
Yes, the original planned name was going to be OpenTLS and it was changed to OpenSSL at the very last minute.  It was fortunate we'd registered both domain names!  I'll be writing a blog about this :)

**Comment by InfoHunter** [comment]
> I'll be writing a blog about this :)

As a part of the 20th anniversary? ;-)

**Comment by levitte** [comment]
I just read through [RFC 7568](https://tools.ietf.org/html/rfc7568), and must say I find a certain appeal in it.  It's about more than just rebranding; it's about avoid all uses of SSLv3 if possible, so for example not having it as a fallback from TLS (I haven't looked if we do that kind of fallback today or not).

Renaming is just polish on the surface...  (or virtue signalling, if you wish).  If you ask me, modifying the code to comply with this RFC needs to happen first.

**Comment by iamamoose** [comment]
https://www.openssl.org/blog/blog/2018/12/20/20years/

**Comment by StephenWall** [comment]
OpenTLS is taken.  [https://github.com/lpoulain/OpenTLS](https://github.com/lpoulain/OpenTLS)

**Comment by zakcodez** [comment]
It's also taken here: [https://github.com/prisma/opentls](https://github.com/prisma/opentls)
