### ISSUE TITLE
EAP-FAST broken by 1.1.1-pre7 (unexpected NewSessionTicket after ServerHello)

### ISSUE THREAD

**Issue by jmalinen** [openssl/openssl#6395]
It looks like my EAP-FAST test cases are failing when testing with 1.1.1-pre7 while the same test cases passed with 1.1.1-pre6. Please note that I'm explicitly disabling TLS v1.3 support for EAP-FAST testing.

The new error shows up on the client side by OpenSSL reporting unexpected message when processing ServerHello (see log below). Interestingly, the different behavior seems to be on the server side, though, since the test cases pass when server is built with 1.1.1-pre6 while client side uses 1.1.1-pre7. The difference in the message from the server side is in 1.1.1-pre7 ended up adding an unexpected NewSessionTicket between ServerHello and ChangeCipherSpec. What's that all about? Surely NewSessionTicket should not be inserted at that point in time for a new session.. These EAP-FAST test cases work by first running through a provisioned step that generates the EAP-FAST specific session ticket (i.e., not using this TLS NewSessionTicket contents) and the failing step is the following attempt when the client tries to use the EAP-FAST session ticket in SessionTicket extension of the ClientHello. With 1.1.1-pre7, this gets that interesting response from the server with ServerHello following by NewSessionTicket.

SSL: (where=0x10 ret=0x1)
SSL: (where=0x1001 ret=0x1)
SSL: SSL_connect:before SSL initialization
OpenSSL: TX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 16 03 01 00 f9
OpenSSL: TX ver=0x303 content_type=22 (handshake/client hello)
OpenSSL: Message - hexdump(len=249): 01 00 00 f5 03 03 91 56 85 a3 e2 9d 6f e5 33 c0 d8 b8 ec 19 e8 8e b0 68 ce 89 e2 9c f1 29 0e 97 3b 60 b3 4e 67 9b 00 00 38 c0 2c c0 30 00 9f cc a9 cc a8 cc aa c0 2b c0 2f 00 9e c0 24 c0 28 00 6b c0 23 c0 27 00 67 c0 0a c0 14 00 39 c0 09 c0 13 00 33 00 9d 00 9c 00 3d 00 3c 00 35 00 2f 00 ff 01 00 00 94 00 0b 00 04 03 00 01 02 00 0a 00 0c 00 0a 00 1d 00 17 00 1e 00 19 00 18 00 23 00 3c 00 02 00 38 7b 80 43 e0 d6 75 88 04 e4 10 87 17 26 80 b5 7e 11 a8 ba ae 0a 1c ba 24 3a 5d 30 3e e4 2f 4f de 4c 25 7d 93 82 72 88 3a a1 4f a1 86 39 c3 8e 87 01 a2 76 09 76 0d 56 a1 00 16 00 00 00 17 00 00 00 0d 00 30 00 2e 04 03 05 03 06 03 08 07 08 08 08 09 08 0a 08 0b 08 04 08 05 08 06 04 01 05 01 06 01 03 03 02 03 03 01 02 01 03 02 02 02 04 02 05 02 06 02
SSL: (where=0x1001 ret=0x1)
SSL: SSL_connect:SSLv3/TLS write client hello
SSL: (where=0x1002 ret=0xffffffff)
SSL: SSL_connect:error in SSLv3/TLS write client hello
SSL: SSL_connect - want more data
SSL: 254 bytes pending from ssl_out
SSL: Using TLS version TLSv1.2
SSL: 254 bytes left to be sent out (of total 254 bytes)
...
EAP: Received EAP-Request id=40 method=43 vendor=0 vendorMethod=0
EAP: EAP entering state METHOD
SSL: Received packet(len=326) - Flags 0x01
OpenSSL: RX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 16 03 03 00 3d
SSL: (where=0x1001 ret=0x1)
SSL: SSL_connect:SSLv3/TLS write client hello
OpenSSL: RX ver=0x303 content_type=22 (handshake/server hello)
OpenSSL: Message - hexdump(len=61): 02 00 00 39 03 03 6b e0 46 db 32 82 95 21 59 91 c9 bc 07 d1 86 58 26 c7 81 d0 3a 0a 8d 1a c4 81 7a b7 93 47 5f 0c 00 00 39 00 00 11 ff 01 00 01 00 00 23 00 00 00 16 00 00 00 17 00 00
OpenSSL: Server selected cipher suite 0x39
EAP-FAST: SessionTicket callback
EAP-FAST: SessionTicket - hexdump(len=0): [NULL]
EAP-FAST: client_random - hexdump(len=32): 91 56 85 a3 e2 9d 6f e5 33 c0 d8 b8 ec 19 e8 8e b0 68 ce 89 e2 9c f1 29 0e 97 3b 60 b3 4e 67 9b
EAP-FAST: server_random - hexdump(len=32): 6b e0 46 db 32 82 95 21 59 91 c9 bc 07 d1 86 58 26 c7 81 d0 3a 0a 8d 1a c4 81 7a b7 93 47 5f 0c
EAP-FAST: master_secret - hexdump(len=48): 11 07 cb 07 42 da 2b 89 29 26 99 35 b8 6a 4e 9e 81 f8 91 d9 37 f5 be b3 9b 00 60 44 96 36 02 3d b4 a6 7b a2 dd 67 86 41 78 4a 07 5b 9e 84 3b d8
OpenSSL: tls_session_ticket_ext_cb: length=0
OpenSSL: ClientHello SessionTicket extension - hexdump(len=0):
OpenSSL: RX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 16 03 03 00 aa
SSL: (where=0x1001 ret=0x1)
SSL: SSL_connect:SSLv3/TLS read server hello
OpenSSL: TX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 15 03 03 00 02
OpenSSL: TX ver=0x303 content_type=21 (alert/)
OpenSSL: Message - hexdump(len=2): 02 0a
SSL: (where=0x4008 ret=0x20a)
SSL: SSL3 alert: write (local SSL3 detected an error):fatal:unexpected_message
SSL: (where=0x1002 ret=0xffffffff)
SSL: SSL_connect:error in error
OpenSSL: openssl_handshake - SSL_connect error:141A10F4:SSL routines:ossl_statem_client_read_transition:unexpected message

And this is what shows up at the server side:

SSL: Received packet(len=260) - Flags 0x01
SSL: Received packet: Flags 0x1 Message Length 0
SSL: (where=0x10 ret=0x1)
SSL: (where=0x2001 ret=0x1)
SSL: SSL_accept:before SSL initialization
OpenSSL: RX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 16 03 01 00 f9
SSL: (where=0x2001 ret=0x1)
SSL: SSL_accept:before SSL initialization
OpenSSL: RX ver=0x304 content_type=22 (handshake/client hello)
OpenSSL: Message - hexdump(len=249): 01 00 00 f5 03 03 91 56 85 a3 e2 9d 6f e5 33 c0 d8 b8 ec 19 e8 8e b0 68 ce 89 e2 9c f1 29 0e 97 3b 60 b3 4e 67 9b 00 00 38 c0 2c c0 30 00 9f cc a9 cc a8 cc aa c0 2b c0 2f 00 9e c0 24 c0 28 00 6b c0 23 c0 27 00 67 c0 0a c0 14 00 39 c0 09 c0 13 00 33 00 9d 00 9c 00 3d 00 3c 00 35 00 2f 00 ff 01 00 00 94 00 0b 00 04 03 00 01 02 00 0a 00 0c 00 0a 00 1d 00 17 00 1e 00 19 00 18 00 23 00 3c 00 02 00 38 7b 80 43 e0 d6 75 88 04 e4 10 87 17 26 80 b5 7e 11 a8 ba ae 0a 1c ba 24 3a 5d 30 3e e4 2f 4f de 4c 25 7d 93 82 72 88 3a a1 4f a1 86 39 c3 8e 87 01 a2 76 09 76 0d 56 a1 00 16 00 00 00 17 00 00 00 0d 00 30 00 2e 04 03 05 03 06 03 08 07 08 08 08 09 08 0a 08 0b 08 04 08 05 08 06 04 01 05 01 06 01 03 03 02 03 03 01 02 01 03 02 02 02 04 02 05 02 06 02
OpenSSL: tls_session_ticket_ext_cb: length=60
OpenSSL: ClientHello SessionTicket extension - hexdump(len=60): 00 02 00 38 7b 80 43 e0 d6 75 88 04 e4 10 87 17 26 80 b5 7e 11 a8 ba ae 0a 1c ba 24 3a 5d 30 3e e4 2f 4f de 4c 25 7d 93 82 72 88 3a a1 4f a1 86 39 c3 8e 87 01 a2 76 09 76 0d 56 a1
EAP-FAST: SessionTicket callback
EAP-FAST: SessionTicket (PAC-Opaque) - hexdump(len=60): 00 02 00 38 7b 80 43 e0 d6 75 88 04 e4 10 87 17 26 80 b5 7e 11 a8 ba ae 0a 1c ba 24 3a 5d 30 3e e4 2f 4f de 4c 25 7d 93 82 72 88 3a a1 4f a1 86 39 c3 8e 87 01 a2 76 09 76 0d 56 a1
EAP-FAST: Received PAC-Opaque - hexdump(len=56): 7b 80 43 e0 d6 75 88 04 e4 10 87 17 26 80 b5 7e 11 a8 ba ae 0a 1c ba 24 3a 5d 30 3e e4 2f 4f de 4c 25 7d 93 82 72 88 3a a1 4f a1 86 39 c3 8e 87 01 a2 76 09 76 0d 56 a1
EAP-FAST: Decrypted PAC-Opaque - hexdump(len=48): 01 20 e0 a5 9f 2b d8 34 72 20 0a 21 bc a5 f9 e5 8f 7b 62 4a c4 88 cd 7d c1 37 c0 4c d5 0d 5e 81 50 ac 02 04 5b 1a 9e 93 03 04 75 73 65 72 00 00
EAP-FAST: PAC-Key from decrypted PAC-Opaque - hexdump(len=32): e0 a5 9f 2b d8 34 72 20 0a 21 bc a5 f9 e5 8f 7b 62 4a c4 88 cd 7d c1 37 c0 4c d5 0d 5e 81 50 ac
EAP-FAST: Identity from PAC-Opaque - hexdump_ascii(len=4):
                                    user            
EAP-FAST: client_random - hexdump(len=32): 91 56 85 a3 e2 9d 6f e5 33 c0 d8 b8 ec 19 e8 8e b0 68 ce 89 e2 9c f1 29 0e 97 3b 60 b3 4e 67 9b
EAP-FAST: server_random - hexdump(len=32): 6b e0 46 db 32 82 95 21 59 91 c9 bc 07 d1 86 58 26 c7 81 d0 3a 0a 8d 1a c4 81 7a b7 93 47 5f 0c
EAP-FAST: master_secret - hexdump(len=48): 11 07 cb 07 42 da 2b 89 29 26 99 35 b8 6a 4e 9e 81 f8 91 d9 37 f5 be b3 9b 00 60 44 96 36 02 3d b4 a6 7b a2 dd 67 86 41 78 4a 07 5b 9e 84 3b d8
SSL: (where=0x2001 ret=0x1)
SSL: SSL_accept:SSLv3/TLS read client hello
OpenSSL: TX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 16 03 03 00 3d
OpenSSL: TX ver=0x303 content_type=22 (handshake/server hello)
OpenSSL: Message - hexdump(len=61): 02 00 00 39 03 03 6b e0 46 db 32 82 95 21 59 91 c9 bc 07 d1 86 58 26 c7 81 d0 3a 0a 8d 1a c4 81 7a b7 93 47 5f 0c 00 00 39 00 00 11 ff 01 00 01 00 00 23 00 00 00 16 00 00 00 17 00 00
OpenSSL: Server selected cipher suite 0x39
SSL: (where=0x2001 ret=0x1)
SSL: SSL_accept:SSLv3/TLS write server hello
OpenSSL: TX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 16 03 03 00 aa
OpenSSL: TX ver=0x303 content_type=22 (handshake/new session ticket)
OpenSSL: Message - hexdump(len=170): 04 00 00 a6 00 00 00 00 00 a0 dd e8 a3 b9 23 09 00 fa 81 72 3e 72 06 34 d1 cd 1e 3c dd 3c ee ea df 1f 51 ed ae 50 e0 e1 47 24 01 c5 5f 66 77 2d 06 cb 2d 7e f0 73 98 5e d7 54 16 17 79 08 18 a9 5b be 09 3f 98 9f 0e 3b 37 8a c2 af e6 01 78 bd 11 f8 aa 86 15 f7 dd 18 ce e5 55 15 e6 71 13 4a 99 35 e4 b3 82 c6 9c 62 da ca 1a e5 cb c4 52 c5 70 0c 0e 9f d0 a9 4b b0 31 13 56 94 f7 3d 34 5d 94 ec 80 92 71 8a 9d e6 86 69 ea 2c 90 5c cf 34 e0 6c c1 ee c4 bd 09 44 81 a2 06 61 01 20 08 2a 79 c7 48 fa 3c 22 72 c4 0e 6a
SSL: (where=0x2001 ret=0x1)
SSL: SSL_accept:SSLv3/TLS write session ticket
OpenSSL: TX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 14 03 03 00 01
OpenSSL: TX ver=0x303 content_type=20 (change cipher spec/)
OpenSSL: Message - hexdump(len=1): 01
SSL: (where=0x2001 ret=0x1)
SSL: SSL_accept:SSLv3/TLS write change cipher spec
OpenSSL: TX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 16 03 03 00 44
OpenSSL: TX ver=0x303 content_type=22 (handshake/finished)
OpenSSL: Message - hexdump(len=16): 14 00 00 0c 3a 1a 93 00 89 c1 30 f3 f6 76 61 e9
SSL: (where=0x2001 ret=0x1)
SSL: SSL_accept:SSLv3/TLS write finished
SSL: (where=0x2002 ret=0xffffffff)
SSL: SSL_accept:error in SSLv3/TLS write finished
SSL: SSL_connect - want more data
SSL: 320 bytes pending from ssl_out
SSL: Using TLS version TLSv1.2
...
SSL: Received packet(len=13) - Flags 0x01
SSL: Received packet: Flags 0x1 Message Length 0
OpenSSL: RX ver=0x0 content_type=256 (TLS header info/)
OpenSSL: Message - hexdump(len=5): 15 03 03 00 02
OpenSSL: RX ver=0x303 content_type=21 (alert/)
OpenSSL: Message - hexdump(len=2): 02 0a
SSL: (where=0x4004 ret=0x20a)
SSL: SSL3 alert: read (remote end reported an error):fatal:unexpected_message
SSL: (where=0x2002 ret=0xffffffff)
SSL: SSL_accept:error in error
OpenSSL: openssl_handshake - SSL_connect error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message

**Comment by mattcaswell** [comment]
> The difference in the message from the server side is in 1.1.1-pre7 ended up adding an unexpected NewSessionTicket between ServerHello and ChangeCipherSpec. What's that all about? Surely NewSessionTicket should not be inserted at that point in time for a new session.

This is a valid place in the handshake for a NewSessionTicket to appear. In a successful resumption using a ticket a server may decide to issue a new ticket immediately. If it wants to do so then it adds an empty session ticket extension in the ServerHello, and then the next message is a NewSesssionTicket. However, as far as I can tell from your traces, there is no such extension in the ServerHello, but the server has apparently decided to send one anyway. Obviously this is unexpected from the client side, so the client aborts.

There was some work on ticket callbacks done between pre6 and pre7 so it looks like we might have broken something for applications using such a callback. I'll dig a bit deeper (but it might be Monday before I can get to it).

**Comment by jmalinen** [comment]
Interesting.. The ServerHello does actually include an empty SessionTicket extension in the pre7 case when NewSessionTicket gets added after ServerHello. At least with EAP-FAST, I would not want that to happen, though, since the session ticket is delivered in EAP-FAST specific manner.

**Comment by jmalinen** [comment]
And to be more exact, if I restore the if (s->ext.session_secret_cb) return SSL_TICKET_NO_DECRYPT part in tls_get_ticket_from_client(), the old behavior is restored. I'm not sure what exactly this moving of that condition into tls_decrypt_ticket() in the commit is supposed to do, but that seems to be part that changed the behavior. The additional !SSL_IS_TLS13(s) condition should not have any impact for my test since I'm disable TLS v1.3 for EAP-FAST.

**Comment by jmalinen** [comment]
Thanks, that commit on top of the current master branch snapshot does indeed resolve this.
