### ISSUE TITLE
No OSX Sierra build/install instructions?  Or am I just blind? Also, default Openssl wont update to include needed files.

### ISSUE THREAD

**Issue by number435398** [openssl/openssl#6397]
I just looked over this git several times, I don't see any instructions to build or install on Mac OS.

I'm using OSX Sierra but the openssl it came with doesn't contain the necessary files for building a cryptocurrency wallet, such as crypto.h.  Even telling it to update didn't resolve that issue.

**Comment by richsalz** [comment]
Mac bundles a very old (and insecure) version of OpenSSL.

The INSTALL file says the pre-reqs that are required, and what to do.  You can find more information here as well: https://wiki.openssl.org/index.php/Compilation_and_Installation
