### ISSUE TITLE
SSL_get_async_wait_fd() truncates a handle on 64-bit Windows

### ISSUE THREAD

**Issue by Dmitry-Me** [openssl/openssl#640]
This was found via C4047 Visual C++ warning - `HANDLE` is implicitly converted into `int`. On 64-bit Windows `HANDLE` is a 64-bit `void*` and `int` is 32-bit, so truncation technically happens when `SSL_get_async_wait_fd()` return `HANDLE` as `int`. This code and all code that makes use of `SSL_get_async_wait_fd()` result should be carefully reviewed and fixed.

**Comment by mattcaswell** [comment]
Yes, this is an error in the definition of SSL_get_async_wait_fd(). It should return an OSSL_ASYNC_FD (which is an int on UNIX, but a HANDLE on Windows). I know about this, but this area of code is shortly to be refactored anyway, so I've held off fixing this for the moment.

**Comment by mattcaswell** [comment]
This issue was fixed some while ago.
