### ISSUE TITLE
System call to get randomness on Solaris

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#6403]
Solaris has getrandom() and getentropy() support since version 11.3. But it seems there is no way to detect this at compile time. I guess we need some way to detect that in Configure in that case.

Reading https://blogs.oracle.com/solaris/solaris-random-number-generation-v2 and https://docs.oracle.com/cd/E86824_01/html/E54765/getrandom-2.html, I'm not sure if getrandom() (without GRND_RANDOM) provides the same semantics as Linux. It says it use the urandom pool and that urandom works even when not enough entropy is available. At least on Linux it's explicit that it needs to be initialized, that it did have enough entropy at some point, nowhere in the documentation for Solaris does it say that it needs to be initialized. I guess we should use getentropy() on Solaris, they seem to be recommending that for userspace random number generators.

**Comment by dot-asm** [comment]
You are forgetting one more time, run time. Hint is DSO_global_lookup.

**Comment by kroeckx** [comment]
You're right, I didn't think about trying to detect this at runtime. The code seems to have suggestions to DSO_global_lookup() can be used for that, but I don't actually see any use of it?

**Comment by dot-asm** [comment]
It was used in 1.0.2, but those parts were rewritten.
