### ISSUE TITLE
NOTES.unix only describes ELF

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#6407]
See the comments in #6404

**Comment by dot-asm** [comment]
On additional note I'd say that it would be appropriate to clarify that OpenSSL no longer sets run-time path for the openssl binary by default. [I'm still not convinced that it's adequate choice, not do that *by default*, but whatever.] It also might be right spot to discuss how other applications are supposed to be linked. I mean the notes effectively discuss how to get running [shared] /pre/fix/bin/openssl, but it's only part of the story...

**Comment by levitte** [comment]
I agree, @dot-asm, that seems perfectly appropriate.

**Comment by richsalz** [comment]
Is andy's comment about no longer setting the run-time path still relevant?  i'd like to close this if not.

**Comment by t8m** [comment]
I do not think we should set the rpath.  If nothing else that would have to be a separate RFE and Post 3.0 one.

**Comment by richsalz** [comment]
apparently openssl used to set rpath?  shrug.  closing this issue.

**Comment by levitte** [comment]
There are notes in the file re linking other applications.  If that is sufficient, I don't know.  Please have a read through, and if you think there are notes that need to be added, speak up!

**Comment by richsalz** [comment]
yes there are other notes and if there are problems new issues should be opened.

**Comment by levitte** [comment]
> apparently openssl used to set rpath? shrug. closing this issue.

When linking `apps/openssl`, yes.  There were issues with that, because it set DT_RPATH, which renders any setting of LD_LIBRARY_PATH useless.
