### ISSUE TITLE
OPENSSL_zalloc()/OPENSSL_malloc() return value should not be cast

### ISSUE THREAD

**Issue by Dmitry-Me** [openssl/openssl#641]
There're some spots where result of `OPENSSL_zalloc()` is being cast to a specific pointer type. This is redundant and dangerous as explained here http://stackoverflow.com/questions/1565496 Those casts should be removed.

**Comment by richsalz** [comment]
dangerous seems an exaggeration, but i have a patch to fix being reviewed shortly :)

**Comment by Dmitry-Me** [comment]
@richsalz Not really an exaggeration - you can easily have a pointer truncated into an `int` and then expanded back.

**Comment by richsalz** [comment]
fixed with commit 43ecb9c.  thanks!
