### ISSUE TITLE
How to generate SM2 signatures use private key string without userid?

### ISSUE THREAD

**Issue by wumingyuan** [openssl/openssl#6422]
I have SM2 private key string, like "C9F699DC1EB82AC8A0F508F045D70D70887AF5D532C7C08A8F6AB3A6243978B3".
How to generate 64 length SM2 signatures use private key string without userid?
Thanks very much.

**Comment by mattcaswell** [comment]
That looks like a raw EC private key value (presumably for the SM2 curve). Can you get it in PKCS8 format? That would make life a *lot* easier for you. That way you can use the `d2i_PKCS8PrivateKey()` family of functions to get your key loaded into an `EVP_PKEY` structure (or alternatively the `PEM_read_PrivateKey()` functions if your PKCS8 file is PEM encoded).

If all you've got is the raw key, then it can be done, but its quite a bit more difficult, .e.g something like this (completely untested, and without the normal error checking etc):

    EC_KEY *eckey = EC_KEY_new_by_curve_name(NID_sm2);
    BIGNUM *rawkey = BN_bin2bn(rawbinkey, rawbinkeylen, NULL);
    EC_KEY_set_private_key(eckey, rawkey);
    EC_GROUP *group = EC_KEY_get0_group(eckey);
    EC_POINT *pubkey = EC_POINT_new(group);
    EC_POINT_mul(group, pubkey, rawkey, NULL, NULL, NULL);
    EC_KEY_set_public_key(eckey, pubkey);
    EVP_PKEY *pkey = EVP_PKEY_new();
    EVP_PKEY_set1_EC_KEY(pkey, eckey);

This will give you the key in an EVP_PKEY structure (in the `pkey` variable). From there you can create signatures using the EVP signing routines, e.g. `EVP_DigestSignInit()` etc:

https://www.openssl.org/docs/man1.1.1/man3/EVP_DigestSign.html

**Comment by mattcaswell** [comment]
One other point to note is that the SM2 API is not very stable at the moment. The low level SM2 primitives were recently made private (so you can only access them via the EVP routines now). Also there may be further changes coming (e.g. see the discussion in #6402).

**Comment by wumingyuan** [comment]
Thanks very much. You've solved my problem perfectly. @mattcaswell
