### ISSUE TITLE
openssl-1.1.0h.tar.gzopenssl-1.1.0h.tar.gz has no definition of  struct dh_st

### ISSUE THREAD

**Issue by bolds07** [openssl/openssl#6423]
The file dh.h has the following lines:

```
/* Already defined in ossl_typ.h */
/* typedef struct dh_st DH; */
/* typedef struct dh_method DH_METHOD; */
```

and oss_typ.h has:

`typedef struct dh_st DH;`

but nowhere is made the concrete defition of dh_st, so when someone tries to use the compiler says:
`error: incomplete definition of type 'struct dh_st'`

**Comment by richsalz** [comment]
That is correct.  In OpenSSL 1.1 we made most of the structures opaque. You can't create objects directly on the stack, but only have pointers to them.
