### ISSUE TITLE
openssl 1.1 does not recognize its library openssl library (ssllib1.1)

### ISSUE THREAD

**Issue by AddaxSoft** [openssl/openssl#6431]
i'm trying to compile a program that has ssllib1.1 as a depenedency.

I installed openssl1.1.0h by : (configure && make && make install) 

but the output of `openssl version -a` does not show library version:

    OpenSSL 1.1.0h  27 Mar 2018
    built on: reproducible build, date unspecified
    platform: linux-x86_64
    options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
    compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\""  -Wa,--noexecstack
    OPENSSLDIR: "/usr/local/ssl"
    ENGINESDIR: "/usr/local/lib/engines-1.1"

unlike other boxes I have where the same command results in:

    OpenSSL 1.1.0g  2 Nov 2017 **(Library: OpenSSL 1.1.0h  27 Mar 2018)**
    built on: reproducible build, date unspecified
    platform: debian-amd64
    compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\""
    OPENSSLDIR: "/usr/lib/ssl"
    ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"

This results in "error: OpenSSL library not found." for compiling the program I want to run

**Comment by levitte** [comment]
`openssl version - a` only shows the library version separately *if it differs from the openssl command version*

**Comment by AddaxSoft** [comment]
ok but the compiling process still complains there is no open ssl library installed. How do I findout where is the open ssl lib path and which version I have?

**Comment by mattcaswell** [comment]
The libraries should be in /usr/local/lib (assuming default config parameters).

**Comment by levitte** [comment]
It may be that you need to tell your build configuration (whatever it is) to look in `/usr/local/lib`

**Comment by AddaxSoft** [comment]
I did that and I did run `ldconfig`
then `ldconfig -v | head` and I can confirm ssllib1.1 is in the path
```
/usr/local/lib:
        libssl.so.1.1 -> libssl.so.1.1
        libcrypto.so.1.1 -> libcrypto.so.1.1

```

**Comment by levitte** [comment]
I think you need to add `--with-ssl-dir=/usr/local` to your configuration command.

Also, this is an OpenSSH problem, not an OpenSSL one.  You should [take this problem to them](https://www.openssh.com/portable.html)

**Comment by AddaxSoft** [comment]
wait what, what happened? that flagged solved my issue
now I want to understand why?

**Comment by levitte** [comment]
I went ahead and read `configure.ac`.  The section that checks for OpenSSL shows that other than the standard libraries, they only look in `/usr/local/ssl/lib`, which is the standard installation directory for OpenSSL before 1.1.0.  So it appears you can report a configuration bug to them.

**Comment by admzzz** [comment]
@levitte 
can you help once again, pls?
```

~/build/openssh-7.8p1$ ./configure PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ --with-ssl-engine --with-openssl=/usr/local/lib
.................................................

checking whether AI_NUMERICSERV is declared... yes
checking for getpgrp... yes
checking if getpgrp accepts zero args... yes
checking OpenSSL header version... 1010100f (OpenSSL 1.1.1  11 Sep 2018)
checking OpenSSL library version... not found
configure: error: OpenSSL library not found.

$ openssl version -a
OpenSSL 1.1.1  11 Sep 2018
built on: Wed Sep 12 00:38:27 2018 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
Seeding source: os-specific
```
