### ISSUE TITLE
Won't instal on Ubuntu 18.04

### ISSUE THREAD

**Issue by SimonFearby** [openssl/openssl#6434]
I tried (this used to work on Ubuntu 16.04)

----------------------------
openssl version
OpenSSL 1.1.0g  2 Nov 2017 (Library: OpenSSL 1.1.0h  27 Mar 2018)

mkdir /openssltemp
cd /openssltemp

sudo git clone git://git.openssl.org/openssl.git

cd openssl/

./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -Wl,-rpath,/usr/local/ssl/lib
make
sudo make install

openssl version
OpenSSL 1.1.0g  2 Nov 2017 (Library: OpenSSL 1.1.0h  27 Mar 2018)
----------------------------

I tried this and reboted (it helped with pre6) - no luck
export LD_LIBRARY_PATH=/usr/local/lib
echo "export LD_LIBRARY_PATH=/usr/local/bin/openssl" >> ~/.bashrc

Ideas?

**Comment by levitte** [comment]
You might want to make sure you run `/usr/local/ssl/bin/openssl`, i.e. set your PATH right.
