### ISSUE TITLE
EVP_PKEY_asn1_find_str() crash

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#6441]
For a fairly recent version of the code (commit 73cc84a132a0) I suffer from a crash on openssl startup at
`EVP_PKEY_asn1_find_str()` line 132:
```
        if (ameth->pem_str && (int)strlen(ameth->pem_str) == len
```
due to `ameth->pem_str` being NULL. The string being looked for is `"gost-mac"`, yet this happens also for other values like `"gost2001""`. The values of the index `i` for which this occurs are 6 and downwards.
This may also indicate that something is wrong with some the first 7 entries in `standard_methods[]`:
```
0x6dd52060 <rsa_asn1_meths>,
0x6dd520e8 <rsa_asn1_meths+136>,
0x6dd1b660 <dh_asn1_meth>,
0x6dd1c220 <dsa_asn1_meths>,
0x6dd1c2a8 <dsa_asn1_meths+136>,
0x6dd1c330 <dsa_asn1_meths+272>,
0x6dd1c3b8 <dsa_asn1_meths+408>,
0x6dd1c440 <dsa_asn1_meths+544>,
0x6dd2ada0 <eckey_asn1_meth>,
0x6dd39480 <hmac_asn1_meth>,
0x6dd10660 <cmac_asn1_meth>,
0x6dd521a0 <rsa_pss_asn1_meth>,
0x6dd1b720 <dhx_asn1_meth>,
0x6dd327c0 <ecx25519_asn1_meth>,
0x6dd32880 <ecx448_asn1_meth>,
0x6dd51360 <poly1305_asn1_meth>,
0x6dd54b20 <siphash_asn1_meth>,
0x6dd32940 <ed25519_asn1_meth>,
0x6dd32a00 <ed448_asn1_meth>
```

The stack srace is:
```	
	EVP_PKEY_asn1_find_str() at ameth_lib.c:130 0x6db536d4	
	get_optional_pkey_id() at ssl_ciph.c:337 0x690dabb0	
	ssl_load_ciphers() at ssl_ciph.c:420 0x690dade8	
	ossl_init_ssl_base() at ssl_init.c:102 0x690df8ee	
	ossl_init_ssl_base_ossl_() at ssl_init.c:24 0x690df6ef	
	pthread::once() at thread.cc:2.062 0x6110f2f4

        OPENSSL_init_ssl() at ssl_init.c:206 0x690dfa33	
	apps_startup() at openssl.c:84 0x421d59	
	main() at openssl.c:159 0x421f95		
```

My tmp fix is to add `ameth->pem_str &&` before the `strlen` call.

**Comment by DDvO** [comment]
It turns out that the method list mentioned above was not overwritten, but its statically determined fields values, as represented in `crypto/dsa/dsa_ameth.o` somehow were outdated and pretty wrong!

Today I had updated to that OpenSSL pre-release mentioned above. I was force to re-do configuration but (maybe due to using `ccache`?) `crypto/dsa/dsa_ameth.o` was not re-compiled (and some 9 days old). On the other hand, `crypto/dsa/dsa_ameth..c` has not changed since Oct 27 of last year.

After re-compiling this source file the problem was gone. I do not understand why this inconsistency came up. I cannot imagine that one is supposed to do a manual `make clean` on (re-)configuration.

**Comment by mattcaswell** [comment]
Environmental issue so closing this.
