### ISSUE TITLE
Problem decoding aes-256-cbc on 1.1.0h

### ISSUE THREAD

**Issue by debohman** [openssl/openssl#6444]
I have 1.0.2o installed in /usr/local, and I built a version of 1.1.0h on my system. I am finding that if I encode a short text file with:

openssl enc -a -e -aes256 -in /etc/passwd

I cannot decode it using 1.1.0h:

openssl enc -a -d -aes256 -in passwd.aes256

1.0.2o and the os distributed 0.9.8zh successfully decrypt the file.

I am running macOS 10.12.6.

These is the configuration from the generated Makefile:

PLATFORM=darwin64-x86_64-cc
OPTIONS=--prefix=/tmp/dst.ssl/usr/local --openssldir=/tmp/dst.ssl/usr/local/share enable-shared enable-zlib-dynamic no-asan no-crypto-mdebug no-crypto-mdebug-backtrace no-ec_nistp_64_gcc_128 no-egd no-fuzz-afl no-fuzz-libfuzzer no-heartbeats no-md2 no-msan no-rc5 no-sctp no-ssl-trace no-ssl3 no-ssl3-method no-ubsan no-unit-test no-weak-ssl-ciphers
CONFIGURE_ARGS=(--prefix=/tmp/dst.ssl/usr/local, --openssldir=/tmp/dst.ssl/usr/local/share, darwin64-x86_64-cc, shared, zlib-dynamic)

**Comment by mattcaswell** [comment]
See this FAQ:
https://www.openssl.org/docs/faq.html#USER3

**Comment by debohman** [comment]
Okay, thank you.
