### ISSUE TITLE
i2d_DSAPublicKey() exports wrong representation

### ISSUE THREAD

**Issue by pprindeville** [openssl/openssl#6445]
Looking at RFC-5912, Section 6. “ASN.1 Module for RFC 3279” it says:

```
  -- DSA PK Algorithm, Parameters, and Keys

  pk-dsa PUBLIC-KEY ::= {
   IDENTIFIER id-dsa
   KEY DSAPublicKey
   PARAMS TYPE DSA-Params ARE inheritable
   -- Private key format not in this module --
   CERT-KEY-USAGE { digitalSignature, nonRepudiation, keyCertSign,
                       cRLSign }
  }

  id-dsa OBJECT IDENTIFIER ::= {
   iso(1) member-body(2) us(840) x9-57(10040) x9algorithm(4) 1 }

  DSA-Params ::= SEQUENCE {
   p  INTEGER,
   q  INTEGER,
   g  INTEGER
  }

  DSAPublicKey ::= INTEGER --  public key, y
```

but that’s not what the marshaling code shows after this change:

```
ASN1_SEQUENCE(DSAPublicKey) = {
       ASN1_SIMPLE(DSA, pub_key, BIGNUM),
       ASN1_SIMPLE(DSA, p, BIGNUM),
       ASN1_SIMPLE(DSA, q, BIGNUM),
       ASN1_SIMPLE(DSA, g, BIGNUM)
} ASN1_SEQUENCE_END_name(DSA, DSAPublicKey)
```

Clearly `DSAPublicKey` is a scalar of a single `INTEGER`, not a `SEQUENCE`.

Why are we violating the RFC?

And why are we duplicating DSA-Params?  That’s marshaled as:

```
ASN1_SEQUENCE_cb(DSAparams, dsa_cb) = {
       ASN1_SIMPLE(DSA, p, BIGNUM),
       ASN1_SIMPLE(DSA, q, BIGNUM),
       ASN1_SIMPLE(DSA, g, BIGNUM),
} static_ASN1_SEQUENCE_END_cb(DSA, DSAparams)
```

so we seem to have some redundancy here.

There are bits of CMS that I need to implement which require a canonical DSA public key representation.

**Comment by mattcaswell** [comment]
The man page for d2i_DSAPublicKey has this note about it:
https://www.openssl.org/docs/man1.1.0/crypto/d2i_DSAPublicKey.html


```
DSAPublicKey, DSAPrivateKey
 Use a non-standard OpenSSL format and should be avoided; use DSA_PUBKEY, PEM_write_PrivateKey(3), or similar instead.
```
The "non-standard OpenSSL format" has been there since the beginning of time and pre-dates the various RFCs in question. It persists for backwards compat reasons.

If you want to represent a DSA public key in "canonical" format then you should use SubjectPublicKeyInfo form so, as the note above suggests, use `i2d_DSA_PUBKEY()`.

**Comment by pprindeville** [comment]
> If you want to represent a DSA public key in "canonical" format then you should use SubjectPublicKeyInfo form so, as the note above suggests, use `i2d_DSA_PUBKEY()`.

It might be _a_ canonical format, but it's not _the_ canonical format as apparently there are several.

Where is the structure of the `DSA_PUBKEY` described?  It's not in `crypto/dsa/dsa_asn1.c`...

The format that I'm needing for the cryptographic message signing I'm doing needs the digest (usually SHA-1) of the public key solo, i.e. just the ASN.1 `INTEGER` itself with no embellishment.

As for:

> The "non-standard OpenSSL format" has been there since the beginning of time and pre-dates the various RFCs in question. It persists for backwards compat reasons.

I don't see any places where it's actually used outside of `crypto/x509/x_all.c`.  Just how much stuff would break if this were to change?

Or are you talking about in external source code?

**Comment by mattcaswell** [comment]
> Where is the structure of the DSA_PUBKEY described? It's not in crypto/dsa/dsa_asn1.c... (for that matter, where's the format of SubjectPublicKeyInfo?). If it's the same as in RFC-5912, then that's not what I need either.

`i2d_DSA_PUBKEY` is just a thin wrapper around an `X509_PUBKEY` which is defined here:

https://github.com/openssl/openssl/blob/master/crypto/x509/x_pubkey.c#L52-L55

The above is the definition of a SubjectPublicKeyInfo structure.

>The format that I'm needing for the cryptographic message signing I'm doing needs the digest (usually SHA-1) of the public key solo, i.e. just the ASN.1 INTEGER itself with no embellishment.

If all you need is the encoding of an ASN.1 INTEGER then you can use `i2d_ASN1_INTEGER()`. You'll need to convert the public key into an ASN1_INTEGER object first using `BN_to_ASN1_INTEGER()`.

> I don't see any places where it's actually used outside of crypto/x509/x_all.c. Just how much stuff would break if this were to change?

> Or are you talking about in external source code?

It's exposed via various external APIs (both directly and indirectly) - so yes I'm talking about external source code. It's unclear how much if anything is actually using it - but changing its meaning is probably unwise.

**Comment by pprindeville** [comment]
> If all you need is the encoding of an ASN.1 INTEGER then you can use `i2d_ASN1_INTEGER()`. You'll need to convert the public key into an `ASN1_INTEGER` object first using `BN_to_ASN1_INTEGER()`.

And indeed, that's what I ended up doing here:

https://github.com/openssl/openssl/pull/6448/files#diff-f10d53adf70373d46ba25a78a5deb048R161

**Comment by mattcaswell** [comment]
No changes required, so closing.
