### ISSUE TITLE
DSA_sign_setup() is broken in OpenSSL 1.1.0

### ISSUE THREAD

**Issue by HPaulS** [openssl/openssl#6447]
As of OpenSSL 1.1.0, `DSA_sign_setup()` is no longer useful.  This is because `DSA` is now an opaque struct so there is no way to pass the values returned by `DSA_sign_setup()` to `DSA_do_sign()`.  This all used to work fine in OpenSSL 1.0.2 and earlier so I would regard this as a regression.

`DSA_sign_setup()` is important.  If you have a lot of messages to sign with the same key it can speed things up 100-fold, perhaps more, so it would be good if it could be fixed.

Proposal:

1.  `DSA_sign_setup( )` should lose its `kinvp` and `rp` parameters.  Instead, it should stash its results in `dsa` and set a flag in `dsa` so that it knows that `DSA_sign_setup()` has been called.

2.  `DSA_do_sign()` should consult that flag and do the right thing.  If it needs to return `DSA_R_NEED_NEW_SETUP_VALUES` then it should do so and the caller must start over.  To see why this is sometimes necessary, see the implementation of `dsa_do_sign()` [here](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/dsa/dsa_ossl.c).  You'll need to reinstate some of that old code.

3.  `DSA_free()` should free any pointers stashed in `dsa` by `DSA_sign_setup()`.

I hope that is doable.  I don't know the code well enough to be certain that it is.

Regards - Paul Sanders.

**Comment by kroeckx** [comment]
So in 1.0.2 the DSA structure had a kinv and r field to store
those precomputed values, but were removed by this commit:

commit e1d9f1ab39eeab0c3c2b9415e0aaaa8c05858f77
Author: Dr. Stephen Henson <steve@openssl.org>
Date:   Mon Mar 7 17:31:00 2016 +0000

    Remove kinv/r fields from DSA structure.

    The kinv/r fields in the DSA structure are not used by OpenSSL internally
    and should not be used in general.

And there now just doesn't seem to be any way to use them.

**Comment by HPaulS** [comment]
Well just roll that change back, essentially, then you can implement the rest of my proposal.  Maybe I'm missing something but I don't see the problem.  The changes made to `dsa_do_sign()` at that time were naive because the person who made them evidently didn't appreciate that `DSA_sign_setup()` serves an important purpose and should be maintained in a usable state.

Do I need to say any more or can you run with that?

Also, please keep the documentation up to date!  We wasted quite a bit of time on this over at [StackOverflow](https://stackoverflow.com/questions/50750417/what-is-the-proper-way-to-efficiently-use-digital-signatures).

**Comment by romen** [comment]
I gave a [longer answer](https://stackoverflow.com/a/50791866) on your StackOverflow question.

The short version is that DSA nonce generated in `DSA_sign_setup()`should not be reused!

Also if 1024-bit DSA signature generation takes tens of second on your machine, I suspect you are being slowed down by the PRNG (maybe low entropy on /dev/random?).

**Comment by HPaulS** [comment]
Hi romen,

That answer is very helpful, thank you.  I see I have a lot to learn about cryptography. 

My tests were with a debug build, so 3000 calls to `DSA_do_sign()` would probably take around 3 seconds (as opposed to 10 seconds) on my 3GHz core i3 in a release build.  That's generally the kind of speedup I see.  This  all on Windows, so no /dev/random.  Maybe it uses `CryptGenRandom()`, I haven't looked (and probably won't).

And please guys, update the documentation!!! (just ditch `DSA_sign-setup()` entirely if it is now dead code).

**Comment by richsalz** [comment]
To make it explicit: re-using the random value exposes the private key.

We have ABI guarantees we try to keep.

We cannot fix bugs if we're not aware of them.  A huge stackoverflow thread doesn't help fix openssl if it's not reported here.

Thanks.

**Comment by HPaulS** [comment]
Yes, thank you, I understand all that now, I will update my post on SO.  And in my own defense, I _did_ report it here, straightaway, but not being well-versed in cryptography in general I was throroughly misled by the documentation and so was the OP on StackOverflow.  Sp please please fix that.

And please forget I said 'naive', I didn't understand why the code was changed as it was, but then again the original response to my bug report didn't give me even the slightest clue.

**Comment by davidben** [comment]
Actually, I don't think your stack-overflow code is doing anything. Removing those `kinv` and `r` fields was definitely correct, but they did get `NULL`ed on first use anyway. Rather, your loop checking for `DSA_R_NEED_NEW_SETUP_VALUES` isn't running because `DSA_R_NEED_NEW_SETUP_VALUES` is an error code returned off the side, not a return value of `DSA_sign`. So your speedup is because it is indeed faster to do nothing and return an error than compute a DSA signature. :-)

To be clear, however, **do not play games with DSA k values**. I notice your StackOverflow edit describes this as merely risky and leaves open the possibility that the risk is acceptable to someone. This is incorrect. If you reuse k even *once*, you have completely lost your private key. Anyone can just compute the private key directly from the two signatures. If you use a known or predictable value of k, you have completely lost your private key. **Do not do this.**

If DSA is too slow for your use, use a different algorithm if DSA. There are much better algorithms available now.

**Comment by HPaulS** [comment]
@davidben OK, that's clear enough, I have updated my SO post.  But _please_ (and this is the fourth time I have mentioned this and nobody has acknowledged it) remove `DSA_sign_setup()` from the documentation and the API, and say in the documentation why you have done so.  We were all thoroughly misled by this over at SO.  We thought the function was there to be used.  People who use OpenSLL are not cryptogrophy experts. They just want to get the job done.

Or would you prefer me to open a new issue for this?  I don't mind doing that if it will help you guys.  This one has got  bit messy.

Other stuff:

> I don't think your stack-overflow code is doing anything.

Actually, I think it is, not that it really matters now, see the 1.0.2 implementation of `dsa_do_sign()` [here](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/dsa/dsa_ossl.c).

> If DSA is too slow for your use, use a different algorithm. There are much better algorithms available now.

A specific recommendation would be welcome, especially to the OP who has a genuine performance problem (I was just chipping in).  The code [posted by romen at SO](https://stackoverflow.com/a/50791866/5743288) was actually slower, when I informally benchmarked it on my Windows machine.

**Comment by HPaulS** [comment]
Oh yes, is there even the minutest chance that [this](https://eprint.iacr.org/2018/069.pdf) might be of interest?  I could be barking completely up the wrong tree but they do talk about speeding up the calculation of `r` for an algorithm that may or may not be one that OpenSSL supports.

I'm probably talking total rubbish (I'm well out of my depth here) but I chanced across it so I thought I'd pass it on.

**Comment by romen** [comment]
I am in the process of writing a PR updating the documentation about `DSA_sign_setup()` for 1.1.1 and 1.1.0.
It's a WIP as I need feedback about potential ENGINE DSA_meth implementations.

**Comment by HPaulS** [comment]
@romen That's great, thank you.  Sorry we took the long and winding road on this one - that's partly down to me.  I logged a comment on the other thread.

**Comment by richsalz** [comment]
Please open a new issue.

**Comment by HPaulS** [comment]
@richsalz Romen did already.

**Comment by HPaulS** [comment]
Issue closed, see issue [#6460](https://github.com/openssl/openssl/pull/6460).

**Comment by romen** [comment]
#6465 aims at fixing the 1.0.2 documentation so that users are clearly warned against using `DSA_sign_setup()` the wrong way.
