### ISSUE TITLE
mkdef.pl sets GSMATCH ID to 0,0 in VMS shareables

### ISSUE THREAD

**Issue by vman55** [openssl/openssl#6449]
mkdef.pl apparently (my perl is very weak) attempts to rummage through opensslv.h to get the current OPENSSL_VERSION_TEXT definition and convert it to a pair of integers as the image's major and minor ID numbers.  I may have worked for version 1_1_0, but 1_1_0h  fails, the regular expression used to extract the numbers doesn't accomodate the letter.

**Comment by levitte** [comment]
Damn. OK, will fix.

**Comment by levitte** [comment]
Fix is in #6450.  Would you be willing to confirm, @vman55?

**Comment by levitte** [comment]
(dunno how acquainted you are with github, btw...  should you need it, the branch for #6450 is [here](https://github.com/levitte/openssl/tree/fix-6449), and you can download a zip from there)

**Comment by vman55** [comment]
The fix gets the GSMATCH to "101,0" on my system as expected.  A further refinement would incorporate the letter into the minor version (1_1_0h -->  101,8)

[mkdef.txt](https://github.com/openssl/openssl/files/2089931/mkdef.txt)

**Comment by levitte** [comment]
The letter releases correspond to ECOs in the VMS world.  Do those come with GSMATCH changes?  If not, I don't see reason to incorporate the letter in the minor version.

**Comment by levitte** [comment]
(Reopen this issue if it turns out that we should indeed incorporate the letters)
