### ISSUE TITLE
TLS-PSK : SSL3 alert read:fatal:decode error

### ISSUE THREAD

**Issue by fadeos** [openssl/openssl#6456]
Hello,
I have a problem with the TLS-PSK openssl server when I connect it with my client in PSK I have a error "decode error".

TLS-PSK openssl server:
**openssl s_server -state -debug -msg -trace -psk myhexakey -accept 50000 -cipher PSK-AES128-CBC-SHA -nocert**

log:
**Using default temp DH parameters
PSK key given, setting server callback
ACCEPT
SSL_accept:before SSL initialization
read from 0x1ac6ca0 [0x1ad1f43] (5 bytes => 5 (0x5))
0000 - 16 03 03 00 3c                                    ....<
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 60
read from 0x1ac6ca0 [0x1ad1f48] (60 bytes => 60 (0x3C))
0000 - 01 00 00 38 03 03 cb 63-f4 71 a5 85 01 9b 46 e0   ...8...c.q....F.
0010 - bd 54 d4 8a 49 dd 8e a4-50 8e f0 71 3a 32 a7 c9   .T..I...P..q:2..
0020 - c9 61 4b c9 92 74 00 00-0a 00 ae 00 b0 00 8c 00   .aK..t..........
0030 - 8b 00 2c 01 00 00 05 00-01 00 01 01               ..,.........
SSL_accept:before SSL initialization
    ClientHello, Length=56
      client_version=0x303 (TLS 1.2)
      Random:
        gmt_unix_time=0xCB63F471
        random_bytes (len=28): A585019B46E0BD54D48A49DD8EA4508EF0713A32A7C9C9614BC99274
      session_id (len=0): 
      cipher_suites (len=10)
        {0x00, 0xAE} TLS_PSK_WITH_AES_128_CBC_SHA256
        {0x00, 0xB0} TLS_PSK_WITH_NULL_SHA256
        {0x00, 0x8C} TLS_PSK_WITH_AES_128_CBC_SHA
        {0x00, 0x8B} TLS_PSK_WITH_3DES_EDE_CBC_SHA
        {0x00, 0x2C} TLS_PSK_WITH_NULL_SHA
      compression_methods (len=1)
        No Compression (0x00)
      extensions, length = 5
        extension_type=max_fragment_length(1), length=1
          0000 - 01                                             .

SSL_accept:SSLv3/TLS read client hello
Sent Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 74
    ServerHello, Length=70
      server_version=0x303 (TLS 1.2)
      Random:
        gmt_unix_time=0x2A8DF7B9
        random_bytes (len=28): 9589F2F3D4EE1441083D8868B82AAD6FDB46113060A792D041E4BA9B
      session_id (len=32): C20425CF6F95298E5EF51B408AB68B0FF5840F56BACA719BDFB2D37931AAAE66
      cipher_suite {0x00, 0x8C} TLS_PSK_WITH_AES_128_CBC_SHA
      compression_method: No Compression (0x00)
      No Extensions

SSL_accept:SSLv3/TLS write server hello
Sent Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 4
    ServerHelloDone, Length=0

write to 0x1ac6ca0 [0x1adb1e0] (88 bytes => 88 (0x58))
0000 - 16 03 03 00 4a 02 00 00-46 03 03 2a 8d f7 b9 95   ....J...F..*....
0010 - 89 f2 f3 d4 ee 14 41 08-3d 88 68 b8 2a ad 6f db   ......A.=.h.*.o.
0020 - 46 11 30 60 a7 92 d0 41-e4 ba 9b 20 c2 04 25 cf   F.0`...A... ..%.
0030 - 6f 95 29 8e 5e f5 1b 40-8a b6 8b 0f f5 84 0f 56   o.).^..@.......V
0040 - ba ca 71 9b df b2 d3 79-31 aa ae 66 00 8c 00 16   ..q....y1..f....
0050 - 03 03 00 04 0e                                    .....
0058 - <SPACES/NULS>
SSL_accept:SSLv3/TLS write server done
read from 0x1ac6ca0 [0x1ad1f43] (5 bytes => 5 (0x5))
0000 - 15 03 03 00 02                                    .....
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Alert (21)
  Length = 2
read from 0x1ac6ca0 [0x1ad1f48] (2 bytes => 2 (0x2))
0000 - 02 32                                             .2
    Level=fatal(2), description=decode error(50)

SSL3 alert read:fatal:decode error
SSL_accept:error in SSLv3/TLS write server done
ERROR
140608622139200:error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error:ssl/record/rec_layer_s3.c:1399:SSL alert number 50
shutting down SSL
CONNECTION CLOSED**

Thanks.

**Comment by N-faycal** [comment]
+1 on this. We have the same issue. Client is an embedded system

**Comment by mattcaswell** [comment]
Which version of OpenSSL is this? Is client OpenSSL as well or just the server?

**Comment by fadeos** [comment]
- Version:  OpenSSL 1.1.0g  2 Nov 2017
- Its just an Openssl server

**Comment by ygm521** [comment]
is solved?

**Comment by t8m** [comment]
1.1.0 branch is not supported anymore. Closing.
