### ISSUE TITLE
user defined include paths in Configure script

### ISSUE THREAD

**Issue by ashiwnksk** [openssl/openssl#6462]
i have my own set of standard libraries and header files like stdio.h. How to give this in Configure script to pick it from my own path, rather than standard path [/usr/include]

**Comment by levitte** [comment]
You can simply give the include paths as arguments to Configure, the same way as you would to the compiler, `-I/what/ever`

**Comment by levitte** [comment]
Our configure script does consider any header paths, it only passes those switches along to the compiler. So if you want to relay *to the compiler* not to use the standard header paths, you can give that option to the configure script as well.

**Comment by levitte** [comment]
So if your compiler is gcc or anything compatible, you could pass `-nostdinc -I/what/ever` to the configure script.

**Comment by ashiwnksk** [comment]
@levitte  Thanks for the suggestion. The option you mentioned helped me. But i am seeing the below error during make depend. I am not sure that it is picking up from the right path

In file included from cryptlib.c(117):
cryptlib.h(62): catastrophic error: cannot open source file "stdlib.h"
  # include <stdlib.h>
                      ^

mem.c(59): catastrophic error: cannot open source file "stdio.h"
  #include <stdio.h>
                    ^

mem_clr.c(60): catastrophic error: cannot open source file "string.h"
  #include <string.h>
                     ^

mem_dbg.c(112): catastrophic error: cannot open source file "stdio.h"
  #include <stdio.h>
                    ^

In file included from cversion.c(59):
cryptlib.h(62): catastrophic error: cannot open source file "stdlib.h"
  # include <stdlib.h>
                      ^

In file included from ex_data.c(141):
cryptlib.h(62): catastrophic error: cannot open source file "stdlib.h"
  # include <stdlib.h>
                      ^

cpt_err.c(62): catastrophic error: cannot open source file "stdio.h"
  #include <stdio.h>
                    ^

In file included from uid.c(56):
../include/openssl/crypto.h(120): catastrophic error: cannot open source file "stdlib.h"
  # include <stdlib.h>
                      ^

o_time.c(65): catastrophic error: cannot open source file "string.h"
  #include <string.h>
                     ^

o_str.c(60): catastrophic error: cannot open source file "ctype.h"
  #include <ctype.h>
                    ^

o_dir.c(60): catastrophic error: cannot open source file "errno.h"
  #include <errno.h>
                    ^

In file included from o_fips.c(59):
cryptlib.h(62): catastrophic error: cannot open source file "stdlib.h"
  # include <stdlib.h>
                      ^

In file included from o_init.c(56):
../e_os.h(468): catastrophic error: cannot open source file "unistd.h"
  #    include OPENSSL_UNISTD
                             ^

make[2]: *** [local_depend] Error 1

**Comment by ashiwnksk** [comment]
Please excuse for the format while pasting.

**Comment by levitte** [comment]
What path did you give, and where is your variant of `stdio.h`?

**Comment by levitte** [comment]
Ah, the configure script isn't perfect. Remove the space between `-I` and `/home/libs/stdlib/inc` (making them one argument) and you should be fine.

**Comment by ashiwnksk** [comment]
Sorry it's typo, actually there is no space, i removed space too.  Still i am facing same issue.

**Comment by ashiwnksk** [comment]
@levitte thanks for the support. It worked. Mistake was i am using relative path after -I, I replaced this with the absolute path, it started working

**Comment by ashiwnksk** [comment]
Hi Levitte can't i use relative path instead of absolute path.?

**Comment by ashiwnksk** [comment]
@levitte  Thanks for valued response. It helped lot.
