### ISSUE TITLE
Apache 2.4.33+OpenSSL 1.0.2o failed to start on solaris 

### ISSUE THREAD

**Issue by shitapatilptc** [openssl/openssl#6463]
Apache failed to start on SOLARIS 11 if SSL is configured. If SSL is not configured, it works well.

Stack trace of core dump indicates failure in libcrypto module. Any help is really appreciated.

````
_0xffffffff73f2f9a0(ffffffff7fffe820, ffffffffffffffff, 1e, ffffffff7c7a9818, 74, ffffffff7c8e4640)
**libcrypto.so.1.0.0`ERR_get_state**+0x30(ffffffff7fffe830, 1, 1290, 1000, 12b0, 1000)
**libcrypto.so.1.0.0`ERR_clear_error**+4(100248220, 8000, 0, 1000, 1000, 1040)
**libcrypto.so.1.0.0`ENGINE_load_builtin_engines**+0x14(1, ffffffff7cc67e68, 10018abc0, 10018a040, 38, 101010101010101)
0xffffffff7391143c(4, 1001cfae8, 1001cdad8, a00000000, ffffffff78f11d80, ffffffff78f11e70)
ap_run_pre_config+0x60(1001a1918, 1001cfae8, 1001cdad8, 1e0, 1, 210)
main+0xa70(1001a1918, 1001903d8, 100079400, 100190000, 100193c00, 100193000)
_start+0x7c(5, ffffffff7fffefb8, ffffffff7fffefe8, 0, 103d9c, ffffffff7fffefb8)_
````

[truss output.txt](https://github.com/openssl/openssl/files/2093765/truss.output.txt)

**Comment by richsalz** [comment]
Are you sure that you built and configured apache and the openssl version compatibly?
Why is there no symbol for the ...43c function?
There is really not enough information here.

**Comment by shitapatilptc** [comment]
Thanks for response. Yes we build apache+openssl on solaris platform only. Also the same installation copy is working find on local solaris systems.
Problem arise only at the customer's system.

Any specific information I should look for?

**Comment by shitapatilptc** [comment]
We found a workaround 
Apache 2.4.33+OpenSSL 1.0.2o = Fails to start so we downgrade openssl version to 1.0.2k(available in solaris library) and it worked
**Apache 2.4.33+OpenSSL 1.0.2K = Works well !**

Has anyone observed such issue?

**Comment by t8m** [comment]
Closing as 1.0.2 is not supported anymore.
