### ISSUE TITLE
Revise DSA_sign_setup() API

### ISSUE THREAD

**Issue by romen** [openssl/openssl#6464]
As a follow up to #6460 , we should revise the `DSA_sign_setup()` API for the **next major release**.

My proposal is to change the function signature so that it does not take pointers to return `kinv` and `r`:

```
int DSA_sign_setup(DSA *dsa, BN_CTX *ctx);
```

upon calling it, implementations should take care of internally store the precomputation results, consume them when the actual signature is generated and efficiently and securely discard used precomputation values to avoid reuse.

The user would than have the choice of calling `DSA_sign()` directly (or through higher level APIs) without explicit precomputation or to explicitly call `DSA_sign_setup()` some time before `DSA_sign()` to separate (**for each signature**) the *setup* phase from the actual *signature* phase.
`DSA_sign()` should obviously take care of implicitly calling `dsa_sign_setup()` if no fresh precomputed data is already stored and also to make sure that precomputed data is safely cleansed and discarded after each signature, to avoid reuse of nonces.

What I have in mind should also accommodate for example alternative implementations allowing support for batch signatures, and also allow the default OpenSSL implementation to provide optional support for safe `DSA_sign_setup()` precomputation (since 1.1.0 basically calling this function when using dsa_ossl.c just wastes time and memory).

**Comment by romen** [comment]
Pinging @mattcaswell and @richsalz to comment on this idea and also to flag this issue with the right flags/milestone for *next major release*.

**Comment by mattcaswell** [comment]
> I swear we used to have a 1.2.0 label...but I can't find it...

Ah...darn, we did (e.g. see #5451). We used to have a 1.2.0 milestone, but that got merged into a generic "Post 1.1.1" milestone. I think we actually lost information when we did that because some issues can't be resolved until 1.2.0, while others could be resolved in 1.1.2 (if such a version gets created).

Ping @richsalz for your thoughts.

**Comment by richsalz** [comment]
I don't like to predict the future, and saying "after 1.1.1" seems like the only thing we can guarantee.

**Comment by mattcaswell** [comment]
> I don't like to predict the future, and saying "after 1.1.1" seems like the only thing we can guarantee.

Right - but there are certain things that we *know* would not be allowed in 1.1.2 (according to our rules as they are today). It seems useful to know which ones they are. Of course anything can change, but still...

**Comment by richsalz** [comment]
The problem is that 1.1.2 is kind of implying we WILL do it then, whereas "after 1.1.1" is accurate. And then once 1.1.1 is released, we do a review of all "after" tagged items and (tentatively, initially) assign to the next release target.

**Comment by mattcaswell** [comment]
I don't really see it that way. A milestone is an expectation of what we plan to happen not a commitment set in stone.

**Comment by mattcaswell** [comment]
> Right, but you’re saying “earliest we could do it” which isn’t an expectation.

Sure it is. The milestones are a tool for us to track stuff, not any kind of unchangeable commitment to it. We change them *regularly*. We could get in the habit of saying "...assuming that the OMC doesn't change the rules and we don't change our minds about whether they apply in this case...<insert other caveats here>" after every time we assign something to a milestone - but that doesn't seem to be necessary.

**Comment by romen** [comment]
@richsalz @mattcaswell on a side note, as per @levitte suggestion, I opened #6467 to use the DEPRECATEDIN_1_2_0 macro to mark the function declaration as deprecated.

Your ongoing discussion on the nature of the flags/milestones and their naming might be relevant for that PR as to me it appears that adding that macro in the code is actually more "set in stone" than setting a label/milestone on GitHub.

So, if you think it's relevant, I would like to hijack your discussion and move it over there (at #6467 )

**Comment by romen** [comment]
This is obsolete now, as for 3.0.0 these low-level APIs are now being deprecated.
