### ISSUE TITLE
Building libcrypto.a with only SHA, GCM, and CBC

### ISSUE THREAD

**Issue by jerrylui803** [openssl/openssl#6471]
How do I build libcrypto.a with only ``aes-128/256-gcm`` and ``aes-128/256-cbc`` and ``sha-256, sha-512, sha-224, and sha-1``, so that file size of libcrypto.a is as small as possible
I am not sure which options (the "no-xxx" options for disabling stuff) should I use when running ./config because some options seem to conflict (or dependent) with other options

This is what I have now, and I hope to reduce the size more:
``./config no-idea no-camellia no-seed no-bf no-cast no-des no-rc2 no-rc4 no-rc5 no-md2 no-md4 no-ripemd no-mdc2 no-dsa no-dh no-ec no-ecdsa no-ecdh no-sock no-ssl2 no-ssl3 no-err  no-engine no-hw``

**Comment by richsalz** [comment]
Do you want the optimized/faster assembly language versions?  If so you'll need the EVP API. You'll have to edit openssl_add_all_ciphers_int() for that to work.
After you do the config command, just build "lbcrypto.a" not libssl and the apps, for example. You can then take the library and try to remove things and keep building your app until it works.

We don't support "just these ciphers and only those ciphers."

I am going to close this.

**Comment by levitte** [comment]
FYI, the EVP API has nothing to do with optimized/faster assembly language...  However, the EVP API is increasingly the only API through which crypto algos should be selected and used.

**Comment by richsalz** [comment]
*   EVP API has nothing to do with optimized/faster assembly language...

Are you sure?  I recall that, for example, the hardware AESNI instructions are not available through AES_encrypt. But maybe I am wrong, ping @dot-asm to correct at least one of us. ☺
