### ISSUE TITLE
Extensions in certificates are not transferred to certificate requests and vice versa.

### ISSUE THREAD

**Issue by jimbobmcgee** [openssl/openssl#6481]
From man 1 x509:

> BUGS
> Extensions in certificates are not transferred to certificate requests and vice versa.

This bug needs to die in a fire.  It renders `x509 -x509toreq` absolutely useless.

https://rt.openssl.org/Ticket/Display.html?id=3762 suggests that it has been resolved, but I can't see any release information that suggests when.

Making a custom conf file is not a suitable workaround, unless there is an obvious single-line config that I'm missing, but `copy_extensions = copy` is only documented for CA.  I'm not a CA.  

I just don't want to have to type however many subject alternate names, basic usages, extended usages, etc. into a new config, when they already exist in the certificate.  Surely that's the whole point of `-x509toreq`?

**Comment by richsalz** [comment]
It was marked as resolved when it was migrated over to be a GitHub issue.

**Comment by jimbobmcgee** [comment]
@richsalz - Well, that makes sense.  I did search for issues pertaining to `-x509toreq` in Github, but didn't see anything.  Maybe I missed it.

Is the underlying issue actually resoved, though, or is it still a problem?

**Comment by richsalz** [comment]
I don't know, but I guess it's still a problem.

**Comment by jimbobmcgee** [comment]
@richsalz - Only if my *understanding* is correct.  Perhaps what I'm trying to do is invalid?  

The CSRs that I have seen include details about extensions such as `subjectAltName` and `basicConstraints`, and `openssl req` allows you to create such (with an `-extensions` section), but they are *lost* when trying to generate a CSR from an existing certificate (e.g. if renewing the cert with a third-party CA).

`openssl x509 -in oldcert.crt -signkey newkey.key -out newcert.crt` appears to make a self-signed cert with a new key, with all the subject and extension details of the old cert.
`openssl x509 -x509toreq -in newcert.crt -signkey newkey.key -out newreq.csr` appears to make a signing request for the new cert with the new key, but the new CSR does not have the `Requested Extensions` section with the extensions from the new cert.

If a certificate request *without* extensions is valid for a certificate *with* extensions, then maybe there isn't a problem.  But it seems to me that, if the certificate request doesn't have them, then the CA isn't going to know to *add* them.

Coming from a Windows GUI world, where the MMC has both 'Renew certificate with same key' and 'Renew certificate with new key' baked in (but no reasonable means to automate), I turned to `-x509toreq` as a potential alternative, but the lack of extension support is a showstopper.

**Comment by richsalz** [comment]
Your understanding is correct, and the manpage says it's a bug.  Guess it's still a bug. :(

**Comment by jimbobmcgee** [comment]
I'm not a C programmer but, at the risk of introducing far more headaches than I could hope to solve, it *looks* as though the necessary building blocks to provide some support already mostly-exists within x509_req.c, just that there is no means to access the function via the openssl executable.

To that end, I've had a stab at patching in what *might* be a solution -- namely adding support for the `-ext` parameter (which currently allows selection of extensions for *displaying* in `x509 -text`) to *also* allow for choosing extensions which can be copied in `x509 -x509toreq`.

I'm nervous about presenting as a full-on pull request, though, as I have no build environment to speak of (*not a C programmer*), and I'm not at all familiar with the codebase so might have gotten completely the wrong end of the stick while reading through.

Instead, I've attached a couple of diffs of the files that I would change.  Hopefully they make sense and, if they are at all useful to you, please feel free to use them!

[x509.c-diff.txt](https://github.com/openssl/openssl/files/2099953/x509.c-diff.txt)
[x509_req.c-diff.txt](https://github.com/openssl/openssl/files/2099954/x509_req.c-diff.txt)

**Comment by DDvO** [comment]
Thanks @jimbobmcgee for providing a concrete suggestion to solve this.
Similarly to the PR #9449, it extends `X509_to_X509_REQ()`.

Meanwhile I've provided in #13711 a solution that works even without extending that function,
namely by calling it with a NULL key pointer such that it does not (yet) sign the request structure,
then calling `X509_REQ_add_extensions()`, and finally signing the structure using `X509_REQ_sign()`.

**Comment by jimbobmcgee** [comment]
@DDvO : I've not got the skills to review https://github.com/openssl/openssl/pull/13711, but does your `-copy_extensions` option allow specifying which extensions to copy, or does it copy all of them arbitrarily?

It was suggested in some of the comments of similar issue https://github.com/openssl/openssl/issues/10458, that copying all arbitrarily might be unwise.  If that is the case, then possibly allowing the `-ext` argument to work with `-x509toreq` to explicitly allow certain extensions might be valid.  

Looking back, I believe that might have been my intent when editing openssl/apps/x509.c, but it's been a couple of years, so I may be misremembering.

**Comment by DDvO** [comment]
> @DDvO : I've not got the skills to review #13711, but does your `-copy_extensions` option allow specifying which extensions to copy, or does it copy all of them arbitrarily?

By default it copies all existing extensions.
Yet I've added today a commit with several improvements:
AKIDs and SKIDs are not copied to CSRs since they make no sense there.
The `ext` option can be used to select which extensions to copy, also when converting a cert to another cert.
Copied extensions may be overridden and augmented by further ones specified using `-extfile` and `-extensions`.

> It was suggested in some of the comments of similar issue #10458, that copying all arbitrarily might be unwise. If that is the case, then possibly allowing the `-ext` argument to work with `-x509toreq` to explicitly allow certain extensions might be valid.

Those comments did not take into account that the `x509` app (as well as `req`) are low-level cert and CSR manipulation tools
and must not be seen or abused as substitute for a proper CA.
Even the OpenSSL `ca` command is just a demo application and is not meant to be used for productive, security-critical purposes.

> Looking back, I believe that might have been my intent when editing openssl/apps/x509.c, 
but it's been a couple of years, so I may be misremembering.

I hope you don't expect anyone else to guess what your intent has been back then :wink:
but I've had a closer look at the patch you provided, and it does (re-)use the `-ext` option for selecting which extensions to copy.

**Comment by jimbobmcgee** [comment]
@DDvO.

> Those comments did not take into account that the x509 app (as well as req) are low-level cert and CSR manipulation tools and must not be seen or abused as substitute for a proper CA.

Creation of a CSR based on the data within an existing certificate (inference x509 to req) is not necessarily a CA operation.  At least, it certainly wasn't when *this* user was attempting it -- I had inherited an existing cert with approx. 40 SANs added to it, it was due for renewal, and I didn't want to have to type those buggers in again!   *(Narrator: "He did...")*

I figured that, at least in my case, being able to say *fold the SAN extensions into the new request, but leave out the CT and AIA stuff* might be useful.

> I hope you don't expect anyone else to guess what your intent has been back then

Not at all, but after two years, it wasn't fresh in my own mind so, after re-reading my diff from back then, I left a note, both for posterity and so someone might have a starting point should they agree that filtering in a similar way was desirable.

PS. I fear your PR may not gain traction if you have attempted to change too much in one go.  You may have better luck if your split it out into per-feature PRs.

**Comment by DDvO** [comment]
> > Those comments did not take into account that the x509 app (as well as req) are low-level cert and CSR manipulation tools and must not be seen or abused as substitute for a proper CA.
> 
> Creation of a CSR based on the data within an existing certificate (inference x509 to req) is not necessarily a CA operation. 

Sure, but the direction CSR -> cert (which is the same as in a proper CA) was as I recall those comments were about.
And after doing such a conversion the natural next step will be to convert that CSR (by whatever means) into a cert, where the same caveat regarding unintended/harmful extensions would apply again.

> At least, it certainly wasn't when _this_ user was attempting it -- I had inherited an existing cert with approx. 40 SANs added to it, it was due for renewal, and I didn't want to have to type those buggers in again! _(Narrator: "He did...")_

Sorry to hear!
 
> I figured that, at least in my case, being able to say _fold the SAN extensions into the new request, but leave out the CT and AIA stuff_ might be useful.

So for your next cert with, say, 50 SANs, you'll have a more convenient way of doing that :smile:

> > I hope you don't expect anyone else to guess what your intent has been back then
> 
> Not at all, but after two years, it wasn't fresh in my own mind so, after re-reading my diff from back then, I left a note, both for posterity and so someone might have a starting point should they agree that filtering in a similar way was desirable.

Thanks for clarifying.

> PS. I fear your PR may not gain traction if you have attempted to change too much in one go. You may have better luck if your split it out into per-feature PRs.

You are generally right, and normally I'd do it that way, but since I was already touching a lot in `x505` and its doc it would have been cumbersome to do the addition of this feature separately and later merge the resulting 2+ PR with conflicts.
