### ISSUE TITLE
s_client reports incomplete session data

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#6482]
When a TLSv1.3 connection is established s_client dumps various information about the connection including the session data. However at this point no NewSessionTickets have been received yet and so the session data is incomplete. For example the master key is reported like this:

````
    Master-Key: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
````

This value doesn't get set until a ticket arrives. Actually it's not really the master key for TLSv1.3 at all its the resumption PSK, so the label is also mis-leadingly named.

**Comment by kroeckx** [comment]
I guess this might be related:
https://github.com/openssl/openssl/pull/6215#discussion_r187629392
