### ISSUE TITLE
Openssl 1.0.2o disabling executables

### ISSUE THREAD

**Issue by pranavabhat** [openssl/openssl#6485]
Hi All,

I'm using openssl version 1.0.2o.
Is there an option in Configure script to disable the generation of executable?
Since I only need libraries(libssl.a and libcrypto.a) to be generated as part of make, please help in knowing of options to do so, if any.

Thanks,
Pranava

**Comment by ashiwnksk** [comment]
Please go through the link https://github.com/openssl/openssl/blob/master/INSTALL it may help you

**Comment by ashiwnksk** [comment]
Check no-stdio option for the Configure

**Comment by richsalz** [comment]
no-stdio probably does more than you want.

edit the makefile by hand.
