### ISSUE TITLE
x509_load_serial() can generate an incorrect serialfile path.

### ISSUE THREAD

**Issue by DShambroom** [openssl/openssl#6489]
The following code at line 1062, in function x509_load_serial(), file apps\x509.c, generates an incorrect serialfile path if the CAfile path contains the "." character in any directory component.

if (serialfile == NULL) {
        BUF_strlcpy(buf, CAfile, len);
        for (p = buf; *p; p++)
            if (*p == '.') {
                *p = '\0';
                break;
            }
        BUF_strlcat(buf, POSTFIX, len);
    } else
        BUF_strlcpy(buf, serialfile, len);

E.g., if (serialfile == NULL && CAfile == "/home/wds/test.new/CA.cer")
then (serialfile == "/home/wds/test.srl")

**Comment by richsalz** [comment]
yes that is a bug.

**Comment by Ana06** [comment]
The code in master looks a little bit different: https://github.com/openssl/openssl/blob/master/apps/x509.c#L918

but I think that the bug is still there :thinking: can I send a PR to try to fix it? :smile:

**Comment by t-j-h** [comment]
The fix should be relatively trivial in master - strchr to strrchr ... and a PR is always welcome.

**Comment by Ana06** [comment]
@t-j-h 

> The fix should be relatively trivial in master - strchr to strrchr ... and a PR is always welcome.

that is actually what I have already done :wink:
