### ISSUE TITLE
OPENSSL_NO_DSO doesn't exist

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#6495]
If you configure with "no-dso", then the macro "OPENSSL_NO_DSO" doesn't get defined. However it is used nonetheless:

https://github.com/openssl/openssl/blob/master/crypto/init.c#L114
https://github.com/openssl/openssl/blob/master/crypto/init.c#L679
https://github.com/openssl/openssl/blob/master/include/internal/dsoerr.h#L16

This issue affects 1.1.0 as well.

**Comment by mattcaswell** [comment]
Note that the effect of "no-dso" is to use the NULL DSO method, so you still get all the DSO symbols - they just don't do anything.

**Comment by levitte** [comment]
That was an intentional change of methodology. At the time, some of us felt that the "don't even provide stubs" was an unnecessary burden on the users, that it was better to simply return an error when the functionality isn't available.

**Comment by levitte** [comment]
The RSA library was created in a different time and with a different mindset...

**Comment by richsalz** [comment]
I know.  I think the change was a mistake and I'd like us to reconsider.

**Comment by t8m** [comment]
OPENSSL_NO_DSO is defined but it is not used anywhere anyway in the current master. Closing.
