### ISSUE TITLE
DRBG update

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#6533]
There are two DRBGs in the old FIPS module that are not in the current code base (hash and HMAC).  They ought to be bought forward so the code isn't lost in the murkiness of history.

Adding an option to specify which DRBG is used by default and a way of changing would also be useful.

**Comment by paulidale** [comment]
@kroeckx @mspncp

**Comment by slontis** [comment]
See: https://github.com/openssl/openssl/pull/6779

**Comment by slontis** [comment]
Pauli should this be closed?

**Comment by paulidale** [comment]
Yes.
