### ISSUE TITLE
1.1.1-pre8 SSL state becoming defunct

### ISSUE THREAD

**Issue by helamonster** [openssl/openssl#6541]
I'm testing with openssl 1.1.1 all the way to 1.1.1-pre8 and the git version, along with stunnel 5.46 or 5.47 and am having a problem with the SSL state becoming invalid somehow. I'm using stunnel to wrap port 80 of an apache server. Upon first glance, it appears to be working. I then run the SSL Labs test (https://dev.ssllabs.com/ssltest) on my site. The test completes normally once, but after the first run, no client can connect to the service.

The ssl labs site error is:

> Assessment failed: Unexpected failure

Google Chrome's error is:

> This site can’t provide a secure connection
example.com sent an invalid response.
Try running Connectivity Diagnostics.
ERR_SSL_PROTOCOL_ERROR

Here's my stunnel config:
`chroot = /var/lib/stunnel4/`
`setuid = stunnel4`
`setgid = stunnel4`
`pid = /stunnel4.pid`
`debug = 7`
`cert = /etc/stunnel/example.com.crt`
`key = /etc/stunnel/example.com.key`
`verify = 2`
` CAfile = /etc/stunnel/example.com.ca`
`sslVersion = all`
`options = NO_SSLv3`
`options = NO_TLSv1`
`options = NO_TLSv1.1`
`[https]`
`accept  = 10.0.0.3:443`
`connect = 10.0.0.20:80`
`cert = /etc/stunnel/example.com.crt`
`key = /etc/stunnel/example.com.key`
`ciphers = TLS13-AES-256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384`
`options = CIPHER_SERVER_PREFERENCE`
`options = DONT_INSERT_EMPTY_FRAGMENTS`
`TIMEOUTclose = 0`

The author of stunnel (Michel) Indicates he is also seeing this issue:

> Yes, I am aware of the errors (most likely race conditions) in the
current beta versions of OpenSSL 1.1.1. The errors I'm getting on stunnel (the real errors and not just TLS
alerts sent to clients) are:

`crypto/evp/evp_enc.c:157: OpenSSL internal error: assertion failed:`
`ctx->cipher->block_size == 1 || ctx->cipher->block_size == 8 ||`
`ctx->cipher->block_size == 16`

My stunnel log contains (when trying a new connection after it being defunct):
2018.06.20 14:29:32 LOG7[main]: Found 1 ready file descriptor(s)
2018.06.20 14:29:32 LOG7[main]: FD=4 events=0x2001 revents=0x0
2018.06.20 14:29:32 LOG7[main]: FD=7 events=0x2001 revents=0x1
2018.06.20 14:29:32 LOG7[main]: Service [https] accepted (FD=3) from 1.1.1.1:33734
2018.06.20 14:29:32 LOG7[200]: Service [https] started
2018.06.20 14:29:32 LOG7[200]: Setting local socket options (FD=3)
2018.06.20 14:29:32 LOG7[200]: Option TCP_NODELAY set on local socket
2018.06.20 14:29:32 LOG5[200]: Service [https] accepted connection from 1.1.1.1:33734
2018.06.20 14:29:32 LOG6[200]: Peer certificate required
2018.06.20 14:29:32 LOG7[200]: TLS state (accept): before SSL initialization
2018.06.20 14:29:32 LOG7[200]: TLS state (accept): before SSL initialization
2018.06.20 14:29:32 LOG7[200]: TLS alert (write): fatal: internal error
2018.06.20 14:29:32 LOG7[200]: Deallocating application specific data for session connect address
2018.06.20 14:29:32 LOG3[200]: error queue: 1422312D: error:1422312D:SSL routines:ssl_generate_session_id:ssl session id callback failed
2018.06.20 14:29:32 LOG3[200]: error queue: 2406B072: error:2406B072:random number generator:RAND_DRBG_generate:in error state
2018.06.20 14:29:32 LOG3[200]: error queue: 2406C06E: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
2018.06.20 14:29:32 LOG3[200]: error queue: 2406B072: error:2406B072:random number generator:RAND_DRBG_generate:in error state
2018.06.20 14:29:32 LOG3[200]: error queue: 2406C06E: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
2018.06.20 14:29:32 LOG3[200]: error queue: 2406C06E: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
2018.06.20 14:29:32 LOG3[200]: error queue: 2406B072: error:2406B072:random number generator:RAND_DRBG_generate:in error state
2018.06.20 14:29:32 LOG3[200]: SSL_accept: 2406C06E: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
2018.06.20 14:29:32 LOG5[200]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.06.20 14:29:32 LOG7[200]: Local descriptor (FD=3) closed
2018.06.20 14:29:32 LOG7[200]: Service [https] finished (0 left)

I'm pretty new to investigating these types of issues. Could this be a problem of the system running out of entropy from the system's RNG related to #6432?

**Comment by kroeckx** [comment]
On Wed, Jun 20, 2018 at 07:25:30PM +0000, Jeremy Bryan Smith wrote:
> 2018.06.20 14:29:32 LOG3[200]: error queue: 2406C06E: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy

Are you running in a chroot?
Do you have a recent linux kernel?
Did you try this with older openssl versions?

**Comment by helamonster** [comment]
Yes, I am running in a chroot, and to test out my theory of it being related to #6432, I bind mounted /dev into the chroot with:

`mount -o bind /dev /var/lib/stunnel4/dev/`

...to allow access to /dev/random and /dev/urandom within the chroot.

This appears to work around them problem, so hopefully the fixes in #6432 will resolve this properly. In the meantime I can continue my tests with this workaround. 

I haven't tested with older versions because I need TLS 1.3 functionality for my tests.

**Comment by kroeckx** [comment]
> This appears to work around them problem, so hopefully the fixes in #6432 will resolve this properly. In the meantime I can continue my tests with this workaround. 

Can you test that the patch in #6432 works for you?

**Comment by helamonster** [comment]
Yes, the patch in #6432 worked for me.

**Comment by dot-asm** [comment]
> crypto/evp/evp_enc.c:157: OpenSSL internal error: assertion failed:
> ctx->cipher->block_size == 1 || ctx->cipher->block_size == 8 ||
> ctx->cipher->block_size == 16

I find it hard to imagine that this is related. And it ought to be much more serious than initially reported problem. As the only imaginable reason for this assertion to fail is severe programming error or memory corruption (as result of severe programming error elsewhere).

**Comment by ymshenyu** [comment]
openssl 1.1.1 pre8 support tls 1.3 draft 26 27 28  and  ssllabs just support draft 23.

**Comment by mattcaswell** [comment]
Since #6432 got merged I'm closing this.
