### ISSUE TITLE
1.1.1-pre8 - spelling-error-in-manpage

### ISSUE THREAD

**Issue by andreasschulze** [openssl/openssl#6543]
spelling errors pointed out by Debian lintian:

doc/man3/SSL_CTX_sess_set_get_cb.pod:
-SSL_CTX_sess_get_get_cb() allow to retrieve the function pointers of the
+SSL_CTX_sess_get_get_cb() allow one to retrieve the function pointers of the

doc/man3/SSL_CTX_set_cert_verify_callback.pod
-allow to continue the connection in case of failure (by always returning 1)
+allow one to continue the connection in case of failure (by always returning 1)

doc/man7/RAND_DRBG.pod
-however, it will be necessary to explicitely specify a seed source during
+however, it will be necessary to explicitly specify a seed source during

doc/man3/X509_VERIFY_PARAM_set_flags.pod
-flag takes precendence over the B<X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT> flag.
+flag takes precedence over the B<X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT> flag.

**Comment by andreasschulze** [comment]
and these warnings from lintian are somehow related to some too long lines:
usr/share/man/man1/ciphers.1.gz 230: warning [p 2, 2.2i]: can't break line
usr/share/man/man3/SSL_CTX_set_cipher_list.3.gz 179: warning [p 1, 6.8i]: can't break line

**Comment by kroeckx** [comment]
Those warnings about long lines are already in #6473.

**Comment by paulidale** [comment]
I've submitted a PR for the first batch of errors.  I avoided the _allow one to_ alternatives since the wording seemed incongruous with the usual style.
