### ISSUE TITLE
Question regarding RFC5280 standard

### ISSUE THREAD

**Issue by spkesan** [openssl/openssl#6559]
From which openssl version onwards do we support RFC5280 key usage extensions or does it depend upon something else too.

**Comment by richsalz** [comment]
What do you mean support?  Do you mean being able to create certs/cert-requests?  OR do you mean verifying that the certs in a TLS-presented chain have the right usages?

**Comment by t8m** [comment]
In general meaning of the word support we have some support for key usage extensions with all the current versions. There was no response from the reporter that would clarify his question. Closing.
