### ISSUE TITLE
X509_NAME_oneline() contains repeated comparison

### ISSUE THREAD

**Issue by Dmitry-Me** [openssl/openssl#656]
`X509_NAME_oneline()` contains this:

        if (type == V_ASN1_GENERALSTRING ||
            type == V_ASN1_VISIBLESTRING ||
            type == V_ASN1_PRINTABLESTRING ||
            type == V_ASN1_TELETEXSTRING ||
            type == V_ASN1_VISIBLESTRING || type == V_ASN1_IA5STRING) {

where `type == V_ASN1_VISIBLESTRING` is checked twice. This was found with Cppcheck. I dunno whether the second comparison should just be removed or something else should be checked instead.

**Comment by mattcaswell** [comment]
Fixed by commit 2647e2617e3.
