### ISSUE TITLE
TLS1.3: post handshake auth uses the wrong keys

### ISSUE THREAD

**Issue by nmav** [openssl/openssl#6564]
I'm working on an interoperability testing with gnutls and openssl and I noticed that under TLS1.3 openssl seem to be using the wrong keys to calculate the finished message (as client or server).

During the post-handshake process openssl client calls `tls13_final_finish_mac` for the finished calculation and uses `s->client_finished_secret` which is identical to the secret used during the handshake finished calculation. My understanding from [the TLS draft table in 4.4](https://tools.ietf.org/html/draft-ietf-tls-tls13-28#section-4.4) is that the post-handshake finished keys should be derived from the current application traffic key.

**Comment by mattcaswell** [comment]
What OpenSSL commit are you using for this? This problem sounds a lot like #6263 which was fixed in de9f5b355.

**Comment by nmav** [comment]
Ouch, the submodule we use was few commits behind. I can verify that the latest version interoperates fine. Sorry for the false alarm.
