### ISSUE TITLE
Bug? OpenSSL 1.1.1-pre8:  "no-deprecated" build breaks use of OPENSSL_init_ssl() and OpenSSL_add_ssl_algorithms()

### ISSUE THREAD

**Issue by Simon-Edwards01** [openssl/openssl#6565]
It appears that OPENSSL_init_ssl() was deprecated in 1.1.1. Is that intentional?

The result of building with "no-deprecated" is that code which uses OpenSSL_add_ssl_algorithms() or SSL_library_init() fails due to the the following code...

In openssl/ssl.h @ 1924

``` C
# if OPENSSL_API_COMPAT < 0x10100000L
#  define SSL_library_init() OPENSSL_init_ssl(0, NULL)
# endif
```

but @ 1082

``` C
**# define OpenSSL_add_ssl_algorithms()    SSL_library_init()**
# if OPENSSL_API_COMPAT < 0x10100000L
#  define SSLeay_add_ssl_algorithms()    SSL_library_init()
# endif
```

OPENSSL_init_ssl() is (almost) documented here for 1.1.0, although the cross link is broken:
https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_init_crypto.html

Was the intention to drop it completely for 1.1.1? Or is this a problem with accidentally deprecating it in ssl.h?  

BTW: I haven't followed the path any further to see if the implementation itself is also deprecated.

**Comment by Simon-Edwards01** [comment]
Sorry, was confused in the docs.

**Comment by Simon-Edwards01** [comment]
Apologies for the awful formatting above.

There appears to be a bug in the accidental definition of OpenSSL_add_ssl_algorithms() in ssl.h during **no-deprecated** builds.

This shows up as **SSL_library_init()** being undefined when building 1.1.1-pre8 and having old code that used **OpenSSL_add_ssl_algorithms()** .

At line 1578
``` C
    # if OPENSSL_API_COMPAT < 0x10100000L
    #  define SSL_load_error_strings() \
        OPENSSL_init_ssl(OPENSSL_INIT_LOAD_SSL_STRINGS \
                         | OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL)
    # endif
```

At line  1082
``` C
    # define OpenSSL_add_ssl_algorithms()    SSL_library_init()
    # if OPENSSL_API_COMPAT < 0x10100000L
    #  define SSLeay_add_ssl_algorithms()    SSL_library_init()
    # endif
````

IMHO the definition of OpenSSL_add_ssl_algorithms should be inside that OPENSSL_API_COMPAT definition section not outside it.

**Comment by levitte** [comment]
You are quite right, and that deprecation is even documented!  PR coming up.
