### ISSUE TITLE
Missing error check of RAND_bytes() calls in apps/speed.c

### ISSUE THREAD

**Issue by tomgu1991** [openssl/openssl#6567]
Shall we check the return value of RAND_bytes() in apps/speed.c? Such as,
```c
speed.c : 881-890
static int RAND_bytes_loop(void *args)
{
    loopargs_t *tempargs = *(loopargs_t **) args;
    unsigned char *buf = tempargs->buf;
    int count;

    for (count = 0; COND(c[D_RAND][testnum]); count++)
        RAND_bytes(buf, lengths[testnum]);
    return count;
}
```

We find the return value of this call been checked in other files in apps folder.

Such as,
```c
apps/s_cb.c
708:         if (RAND_bytes(cookie_secret, COOKIE_SECRET_LENGTH) <= 0) {
709              BIO_printf(bio_err, "error setting random cookie secret\n");

apps/rand.c
107:         r = RAND_bytes(buf, chunk);
108          if (r <= 0)
109              goto end;
```

In the manual doc, RAND_bytes() puts **num** cryptographically strong pseudo-random bytes into **buf** and the return value 0 on failure. This is the [doc link](https://www.openssl.org/docs/manmaster/man3/RAND_bytes.html)

This problem exists in many versions:
OpenSSL_1_1_0-stable/apps/speed.c,
OpenSSL_1_1_1-pre8/apps/speed.c,
OpenSSL_1_1_1-pre4/apps/speed.c, et al.

Zuxing Gu, Jiecheng Wu
Tsinghua University, Tsmart-IMChecker Group
guzx14@mails.tsinghua.edu.cn, wjc17@mails.tsinghua.edu.cn

**Comment by kroeckx** [comment]
Can you open pull requests for all those issues you've filed?
