### ISSUE TITLE
Check the result of BIO_new_file in fuzz/asn1parse.c

### ISSUE THREAD

**Issue by tomgu1991** [openssl/openssl#6571]
Shall we check the return value of BIO_new_file in fuzz/asn1parse.c? Even though, it seems that it is a test folder to use AFL LibFuzzing tool.

```c
int FuzzerInitialize(int *argc, char ***argv)
{
    bio_out = BIO_new_file("/dev/null", "w");
    OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL);
    ERR_get_state();
    CRYPTO_free_ex_index(0, -1);
    return 1;
}
```

Zuxing Gu, Jiecheng Wu

**Comment by kroeckx** [comment]
I guess this is the one I don't care about. The fuzzer doesn't even look at the return value of this function. If this fails, the fuzzer really isn't going to do anything useful.

For all the  others, feel free to fix them. Please don't submit an issue for all of them, just fix them.

**Comment by tomgu1991** [comment]
I agree. We will try our best to deeply understand the source code and create the patches.
Thanks for your responses!
