### ISSUE TITLE
Shall we check the return value of BN_set_word() call in ssl/t1_lib.c

### ISSUE THREAD

**Issue by tomgu1991** [openssl/openssl#6572]
[BN_set_word(BIGNUM *a, BN_ULONG w)](https://www.openssl.org/docs/manmaster/man3/BN_set_word.html) set **a** to the values **w**. The return value is 0 for failure.

In method ssl_get_auto_dh() of ssl/t1_lib.c, the error check of return value is missed. 

```c
ssl/t1_lib.c, ssl_get_auto_dh:2308-2313
	    BIGNUM *p, *g;
        if (dhp == NULL)
            return NULL;
        g = BN_new();
        if (g != NULL)
            BN_set_word(g, 2);

```

Besides, we find the return value of this call been checked in other files.

Such as,
```c
engines/e_capi.c
 688:         if (!BN_set_word(e, rp->pubexp))
 689              goto memerr;
```

This problem exists in many versions:
OpenSSL_1_1_0-stable
OpenSSL_1_1_1-pre4-8

Zuxing Gu, Jiecheng Wu

**Comment by mattcaswell** [comment]
Closing since the fix was merged.
