### ISSUE TITLE
Potential bugs in apps/speed.c, which caused by missing error code checkings

### ISSUE THREAD

**Issue by tomgu1991** [openssl/openssl#6573]
[HMAC_Init_ex, HMAC_Update, HMAC_Final](https://www.openssl.org/docs/manmaster/man3/HMAC_Init_ex.html) are hash functions used for message authentication, which is based on a hash function. The return value of them contains the error code, where 0 is for failure. It seems that the return value should be checked carefully.

In method HMAC_loop() of apps/speed.c, the error checks of return values are missed. 

```c
apps/speed.c
static int HMAC_loop(void *args)
{
    loopargs_t *tempargs = *(loopargs_t **) args;
    unsigned char *buf = tempargs->buf;
    HMAC_CTX *hctx = tempargs->hctx;
    unsigned char hmac[MD5_DIGEST_LENGTH];
    int count;

    for (count = 0; COND(c[D_HMAC][testnum]); count++) {
        HMAC_Init_ex(hctx, NULL, 0, NULL, NULL);
        HMAC_Update(hctx, buf, lengths[testnum]);
        HMAC_Final(hctx, hmac, NULL);
    }
    return count;
}

```

Besides, we find all the other call sites of these methods have been check.

This problem exists in many versions:
OpenSSL_1_1_0-stable
OpenSSL_1_1_1-pre6-8

Zuxing Gu, Jiecheng Wu

**Comment by t8m** [comment]
The speed.c is reworked to use EVP_MAC for HMAC and there is error checking in master.
