### ISSUE TITLE
Potential null pointer dereference bug in ssl/statem/statem_srvr.c, which caused by missing error code checkings of EVP_PKEY_get0_DH()

### ISSUE THREAD

**Issue by tomgu1991** [openssl/openssl#6574]
[EVP_PKEY_get0_DH()](https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_get0_DH.html) return the referenced key in **pkey** or **NULL** if the key is not of the correct type. So, the return value of it may be a null pointer, which should be checked, such as this [commit](https://github.com/openssl/openssl/commit/a68236572850a1f50d5c40990b5a15a18ebea3bc)

```
on Apr 17 1 parent 7d4488b commit a68236572850a1f50d5c40990b5a15a18ebea3bc       
       dh = EVP_PKEY_get0_DH(s->s3->tmp.pkey);
+        if (dh == NULL) {
+            SSLfatal(s, SSL_AD_INTERNAL_ERROR,
+                     SSL_F_TLS_CONSTRUCT_SERVER_KEY_EXCHANGE,
+                     ERR_R_INTERNAL_ERROR);
+            goto err;
+        }
```

In method tls_process_cke_dhe() of ssl/statem/statem_srvr.c, the error check of return value is missed. And the return value `cdh` is used in DH_set0_key, where may cause a null pointer dereference bug.

```c
apps/speed.c
   cdh = EVP_PKEY_get0_DH(ckey); // cdh is not checked
    pub_key = BN_bin2bn(data, i, NULL);

    if (pub_key == NULL || !DH_set0_key(cdh, pub_key, NULL)) {// used here
        SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_PROCESS_CKE_DHE,
                 ERR_R_INTERNAL_ERROR);
        if (pub_key != NULL)
            BN_free(pub_key);
        goto err;
    }

// however, the dh do not be checked before use, which may result in a null pointer dereference.
int DH_set0_key(DH *dh, BIGNUM *pub_key, BIGNUM *priv_key)
{
    if (pub_key != NULL) {
        BN_free(dh->pub_key);
        dh->pub_key = pub_key;
    }
    if (priv_key != NULL) {
        BN_free(dh->priv_key);
        dh->priv_key = priv_key;
    }

    return 1;
}
```

This problem exists in many versions:
OpenSSL_1_1_0-stable
OpenSSL_1_1_1-pre7-8

Zuxing Gu, Jiecheng Wu

**Comment by FdaSilvaYY** [comment]
FYI, most of OpenSSL API don't check for NULL pointer as input, as it is a lot of burden ... 
and mainly consequence of programming error .

Speed.c is a test tool, not a reference for API use.
IMHO, as it use a restricted set of crypto algorithms, it has very few chance to fail in this case.
On the opposite, the commit you mention is handling some algorithm sent/choosed by the other communication side.

**Comment by tomgu1991** [comment]
I agree with the speed.c.

OpenSSL API has a well-formatted API Reference. And the source code does a lot of error code checks, including NULL pointer checks.
