### ISSUE TITLE
Missing error checks in EC_KEY generating of apps/speed.c

### ISSUE THREAD

**Issue by tomgu1991** [openssl/openssl#6575]
[EC_KEY_generate_key(EC_KEY *key)](https://www.openssl.org/docs/manmaster/man3/EC_KEY_generate_key.html) generates a new public and private key for the supplied **eckey** object. The return value 0 is for failure. 

In apps/speed.c, the error check of the return value of EC_KEY_generate_key is missed. 

```c
 apps/speed.c: 2744-2753
			for (i = 0; i < loopargs_len; i++) {
                EC_KEY_precompute_mult(loopargs[i].ecdsa[testnum], NULL);
                /* Perform ECDSA signature test */
                EC_KEY_generate_key(loopargs[i].ecdsa[testnum]);
                st = ECDSA_sign(0, loopargs[i].buf, 20, loopargs[i].buf2,
                                &loopargs[i].siglen,
                                loopargs[i].ecdsa[testnum]);
                if (st == 0)
                    break;
            }
// definition of EC_KEY_generate_key
int EC_KEY_generate_key(EC_KEY *eckey)
{
    if (eckey == NULL || eckey->group == NULL) {
        ECerr(EC_F_EC_KEY_GENERATE_KEY, ERR_R_PASSED_NULL_PARAMETER);
        return 0;
    }
    if (eckey->meth->keygen != NULL)
        return eckey->meth->keygen(eckey); // use a function pointer, may return a null
    ECerr(EC_F_EC_KEY_GENERATE_KEY, EC_R_OPERATION_NOT_SUPPORTED);
    return 0;
}
```

This problem exists in many versions:
OpenSSL_1_1_0-stable
OpenSSL_1_1_1-pre4-8

Zuxing Gu, Jiecheng Wu

**Comment by FdaSilvaYY** [comment]
IMHO, speed.c is a specific tool, where a lot of error checking are missing...
But his code is already large enough, and it works on a restricted set of algorithm.

**Comment by mspncp** [comment]
I'm undecided whether it is worth adding rigorous error checking to the `openssl speed` tool. It might not be necessary, but one argument for doing it nevertheless would be to provide a positive example for others. What do the other @openssl/committers think about it?

**Comment by richsalz** [comment]
I think it can be useful, but to me it's definitely low priority.  I would merge all apps/speed" issues into one, and wait for a PR to come through.

**Comment by t8m** [comment]
The speed.c is reworked to use EVP_PKEY for ECDSA and there is error checking in master.
