### ISSUE TITLE
smime encrypt maxes out at 2004623747 bytes

### ISSUE THREAD

**Issue by imreACTmd** [openssl/openssl#6577]
Using OpenSSL 1.0.1f 6 Jan 2014 on Ubuntu 3.13.0-147-generic x86_64, The following smime encrypt command stops at 2004623747 bytes.
 
    dd if=/dev/random of=3GB bs=1048576 count=3000
    openssl smime -encrypt -binary -aes256 -outform DER -in 3GB -out 3GB.smime pubkey

3145728000 3GB
2004623747 3GB.smime

Same thing seems to happen on OSX as well.

**Comment by richsalz** [comment]
This is a known limit.  In later versions you can use the -stream option for streaming encrytp.
