### ISSUE TITLE
Error in cipher list

### ISSUE THREAD

**Issue by MrOutput** [openssl/openssl#658]
```
$ openssl ciphers -tls1_2
Error in cipher list
140716126807704:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1369:
```
Page 74 has a list of ciphers for tls1.2

https://www.ietf.org/rfc/rfc5246.txt

## update

I was able to get the list by using `ciphers TLSv1.2`

**Comment by goelakash** [comment]
Seems to be a typo there (-tls1_2 not -tsl1_2).

**Comment by MrOutput** [comment]
@goelakash good catch! However, the latter is also broken!

**Comment by goelakash** [comment]
I could reproduce your error in 1.0.2 stable, but not the dev version. Which version are on?

**Comment by MrOutput** [comment]
OpenSSL 1.0.2f  28 Jan 2016

**Comment by richsalz** [comment]
The flag is "-tls1" in openssl 1.0.2/1.1 and in 1.1 -tls1_1 and -tls1_2 are additional flags.
