### ISSUE TITLE
1.1.1-pre8: runtime detection of getentropy() does not work

### ISSUE THREAD

**Issue by a20god** [openssl/openssl#6591]
I get this error when trying to load an executable statically linked against OpenSSL 1.1.1-pre8 on Ubuntu 16.04 x86_64 (which uses glibc 2.23):

>/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

Apparently, making the reference to getentropy a weak reference does not remove the requirement for glibc to provide GLIBC_2.25.

(The static OpenSSL library was built on a system with eglibc 2.13, the executable was linked on a system with glibc 2.27. The problem might go away by linking on a system without getentropy.)

**Comment by t8m** [comment]
You cannot link an executable on system with glibc 2.27 and expect it to work on 2.23. I do not think this is a problem with getentropy().

**Comment by a20god** [comment]
Well, it did work for me before switching to OpenSSL 1.1.1.

**Comment by t8m** [comment]
It could be a different thing than the getentropy() call. Anyway I do not think this is really supported. If you want to produce a binary that is supposed to run on multiple different systems, you need to build it on the system with the oldest components that are within the supported systems.

**Comment by richsalz** [comment]
It used to work but that was luck.  For example other internals of libc could have changed in a non-portable way.  (That's doubtful but possible.)  As @t8m said, if you want to run on multiple systems you need to build+link against the oldest version.  I am going to close this.
