### ISSUE TITLE
"Bad records mac“ error with openssl1.1.1-pre8

### ISSUE THREAD

**Issue by armman475** [openssl/openssl#6598]
Hi.
I want to study tls1.3 protocol, but when I acces some tls1.3‘s websites using the openssl tool under Linux, there is a "bad record mac" error.
My command  is as follows：
  ./openssl s_client -connect blog.cloudflare.com:443 
CONNECTED(00000003)
140154923763456:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record 
.......
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1530096349
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no

**Comment by mattcaswell** [comment]
Strange. That exact same command works perfectly for me.

What platform are you on?

Some things to try:

- Recompile OpenSSL with the "no-asm" option to turn off assembler optimisations and try again. If it works after that, then it might indicate an assembler bug.
- Recompile OpenSSL with the "enable-ssl-trace" option and then pass "-trace" to your s_client command line. This might give us more clue as to what the issue might be.

**Comment by armman475** [comment]
Thank you for your response.
My Linux OS is Centos6.4 x86_64.
There is one more point to note, I added a define（TLS1_3_VERSION_DRAFT_23）. Because my another PC is using windows10+chorme(TLS1.3 Draft23) .
If I use Openssl1.1.1-pre8 original version, access blog.cloudflare.com is ok, but access imququ.com is error.
If I use Openssl1.1.1-pre8 modified version, access blog.cloudflare.com  and imququ.com are error.
I tried your method and the result is still the same. Attachments are detailed information
[err_info.txt](https://github.com/openssl/openssl/files/2143664/err_info.txt)

**Comment by kroeckx** [comment]
You can't just modify the version that's announced. The draft 23 protocol is different than the draft 28 protocol, it's normal that you get an error in that case.

**Comment by armman475** [comment]
Sorry,I'm still confused.
In the Windows platform chrome browser(TLS1.3 Draft23) access a website(blog.cloudflare.com) and b website( imququ.com) are correct.
Why on Centos platform, using original Openssl1.1.1-pre8, access A website is normal, but access B website is error.(140366833325824:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1557:SSL alert number 70)

**Comment by richsalz** [comment]
The wire protocol for the drafts is different.  OpenSSL only supports one draft at a time.  You need to get the "Draft 23" version of openssl and use that.

**Comment by kroeckx** [comment]
imququ.com only seems to support draft 23. The -pre8 version only
supports draft 26, 27 and 28. So if you tell s_client to only use
TLS 1.3, it's normal that you get an error that there are no
matching protocol versions.

I see no problem here, this all looks expected.

**Comment by armman475** [comment]
The problem is solved.Thank you for your patience to explain.
