### ISSUE TITLE
OpenSSL barfs on critical crlDistributionPoint extensions that are critical

### ISSUE THREAD

**Issue by rylarson** [openssl/openssl#660]
This occurs with 1.0.1e. 

Given a CA and an identity certificate with `crlDistributionPoint` extensions, openssl correctly fetches the CRL and detects revocation when the `crlDistributionPoint` extension is marked non critical, but barfs when the `crlDistributionPoint` extension is marked critical.

I thought this might have something to do with it being marked critical implying scope segmentation, but I made sure that my CRL has the matching `Issuing Distribution Point` extension.

**Comment by richsalz** [comment]
does this also happen in current versions?

**Comment by mattcaswell** [comment]
No response from original submitter. 1.0.1 only receives security fixes, so if this only impacts 1.0.1 it will not be fixed. Closing.

**Comment by zviratko** [comment]
This is still an issue on 1.0.2k
The actual error with openssl verify is:

`error 34 at 0 depth lookup:unhandled critical extension`

-ignore_critical makes it go away, but that's obviously wrong.

**Comment by richsalz** [comment]
OpenSSL does not handle crlDistributionPoint.  Therefore it is doing the right thing.
