### ISSUE TITLE
Plans for GCM?

### ISSUE THREAD

**Issue by MrOutput** [openssl/openssl#661]
Are there any plans to support GCM? HTTP2 requires it. I want to make a cert to use with my server so I can support HTTP2 but openssl does not support it. Any guidance would be greatly appreciated!

In the mean time, I am going to try GNUTLS's certtool.

**Comment by richsalz** [comment]
I think you're confused.  GCM, as in AES-GCM?  That's a symmetric cipher, not a key used to sign a cert.  Post to openssl-users.

**Comment by MrOutput** [comment]
I cannot use that cipher to encrypt anything. Every time I try to make my private key using the AES-GCM cipher, OpenSSL says, "does not support AEAD".

**Comment by mattcaswell** [comment]
The "enc" command line utility does not support AEAD ciphers (which includes GCM based ciphers). Both libcrypto and libssl do support AEAD though.

**Comment by MrOutput** [comment]
From my understanding...I need to use AES-GCM cipher to generate an RSA private key to sign my certificate for it to comply with the HTTP2 Standard. @mattcaswell I will try the `crypto`?

**Comment by mattcaswell** [comment]
I think you are confused. HTTP2 requires that clients/servers support the TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 ciphersuite (which openssl does). The only bit of that ciphersuite name which is relevant to generating a certificate is the RSA bit. Just create a regular RSA certificate and it will be suitable for use with that ciphersuite.

**Comment by MrOutput** [comment]
@mattcaswell I may be a bit confused. I am new to this network security deal. I will generate a regular rsa key and make sure that my server supports that cipher suite. Thank you!
