### ISSUE TITLE
RC4() segfaults

### ISSUE THREAD

**Issue by tfsdev** [openssl/openssl#6618]
One of our application occasionally crashes on calling RC4(). I managed to extract the offending data from one of the crash dumps and make the code below:

$ cat /etc/issue.net
Debian GNU/Linux 9
$ uname -a
Linux test 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.12-1~bpo9+1 (2018-06-03) x86_64 GNU/Linux
$ dpkg -l | grep openssl
ii  openssl                          1.1.0f-3+deb9u2                amd64        Secure Sockets Layer toolkit - cryptographic utility
$ md5sum /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
f3ea5ef53dd7e20054ebe2dbcbce4238  /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
$ g++ test.c -o test -lcrypto
$ ./test
Segmentation fault (core dumped)
$ cat test.c
```
#include <openssl/rc4.h>
#include <stdio.h>

int main()
{
	RC4_KEY key;
	key.x = 8480;
	key.y = 1548419072;
	RC4_INT d[256] = {2139815936,984285184,11894,772472832,11331,3433758720,10453,2292908032,11381,818610176,10742,3452633088,6945,3786080256,11637,1261109248,11485,4117430272,10816,1433075712,10426,4140498944,5834,3681222656,10987,3939172352,10961,1642790912,11726,1600847872,10841,2401959936,10557,10516,12057,3127574528,11805,998965248,9860,168493056,7962,2391474176,7992,2720727040,11033,4125818880,7868,1894449152,10786,3440050176,11367,1152057344,9184,3171614720,8828,1808465920,9753,1414201344,10809,1108017152,9036,527106048,10060,3697999872,5091,2408251392,11471,2475360256,6637,1997209600,9048,2387279872,3216,3618308096,11222,2496331776,11767,1680539648,10960,2861236224,8529,1445658624,6004,4276813824,11054,2854944768,10740,1554710528,11430,2311782400,10998,34275328,11380,3630891008,6800,1640693760,9338,1430978560,11163,2213216256,11262,2307588096,9347,1101725696,11247,3110797312,11451,4251648000,4273,4257939456,11437,1393229824,8804,1072365568,2815,625672192,9796,2127233024,10229,4092264448,10285,2244673536,9582,1626013696,11372,4054515712,11051,2880110592,8146,3693805568,3440,1007353856,10037,3169517568,9565,478871552,11386,2548760576,12092,1462435840,6358,2053832704,4774,399179776,11267,4155179008,6925,2580217856,10412,3603628032,10131,3867869184,11019,2206924800,10348,3414884352,10836,3924492288,6745,418054144,10884,2192244736,9257,2561343488,10795,3335192576,10717,3037396992,9121,2026569728,11230,1485504512,10751,1126891520,11778,2422931456,9437,32178176,5867,562757632,10031,1160445952,6236,3014328320,10978,3521839104,10749,480968704,4399,2383085568,7815,2276130816,4777,3184197632,10656,3523936256,6887,1355481088,9570,2007695360,8488,2276130816,11027,2813001728,6730,806027264,8914,569049088,10945,3494576128,7830,2917859328,10505,3393912832,5706,3018522624,9504,850067456,5937,944439296,10272,1124794368,6265,1439367168,5090,145424384,9819,1261109248,5235,340459520,6903,3616210944,2584,294322176,10617,636157952,9236,4025155584,11994,631963648,10710,1615527936,8807,3247112192,7296,4197122048,10935,3150643200,9948,3557490688,10720,522911744,11534,2733309952,6611,1248526336};

	for(int i=0; i<256; i++)
		key.data[i] = d[i];
	
	unsigned char input[] = {0x4d,0x8a,0x83,0x24,0xdd,0x20,0x31,0x72,0xc9,0x02};
	unsigned char output[1024];

	RC4(&key, 10, input, output);
}
```

**Comment by dot-asm** [comment]
Well, you should expect anything to happen if you feed random data as key schedule. More specifically .data is 256 elements large, and .x, .y and .data[] elements are used as indices. So what would using a large number as index in small table entail? Segmentation fault? Not unlikely at all(*). So question is not why RC4 crashes, but where does the random data come from. And that would be question rather about application than OpenSSL. I mean how come corrupted data is fed to RC4. Unfortunately we can't offer much help with it.

(*) This is not complete story, because depending on processor code executes it switches between RC4_CHAR and RC4_INT, but .x and .y being that large indicate data corruption.
