### ISSUE TITLE
How to generate X25519 keys in openssl 1.1.0h?

### ISSUE THREAD

**Issue by vikram919** [openssl/openssl#6619]
`EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new_id(NID_X25519, NULL);` for initializing the context but this return -2.

I tried implementing below code:
``` java
        EVP_PKEY *pkey = NULL;
	EVP_PKEY_CTX *pctx;
	if (NULL == (pctx = EVP_PKEY_CTX_new_id(NID_X25519, NULL))) {
		fprintf(stderr, "error while initializing public key context\n");
	}
	if (EVP_PKEY_keygen_init(pctx) <= 0) {
		printf("error while initialization %d\n");
	}
	if (EVP_PKEY_keygen(pctx, &pkey) <= 0) {
		printf("error while key generation\n");
	}
	EVP_PKEY_CTX_free(pctx);
```
this did not work all the conditons failed.

I even tried:
```java
       EC_GROUP *ec_group;
	ec_group = EC_GROUP_new_by_curve_name(NID_X25519);
	if (ec_group == NULL) {
		printf("\nEC_GROUP is INVALID.\n");
	} else {
		printf("\nEC_GROUP is ok.\n");
	}
```
which prints invalid group.

**Comment by vikram919** [comment]
> you cannot use the low level EC functions with it)

can you tell me, what is the right way to do?

> Are you sure you are picking up the correct version of the library and not an older version?

am using: openssl 1.1.0h, I checked by using `openssl version`

**Comment by mattcaswell** [comment]
> can you tell me, what is the right way to do?

You should use the EVP functions, as you have been doing.

> am using: openssl 1.1.0h, I checked by using openssl version

That tells you the version of the openssl binary - not necessarily what your code is using.

Is your code dynamically or statically linked against openssl? Assuming you are using dynamic linking what does `ldd` report for your application? E.g. if your app is compiled into a binary called `myapp`, then run `ldd myapp`.

**Comment by zhengfish** [comment]
Hello,
Maybe you can have a look:
https://github.com/alexkrontiris/OpenSSL-x25519-key_exchange

**Comment by t8m** [comment]
There was no further response from the reporter. Closing.
