### ISSUE TITLE
CONF_get_number

### ISSUE THREAD

**Issue by dot-asm** [openssl/openssl#6620]
Quoting CONF_get_number:
```
    if (conf == NULL) {
        status = NCONF_get_number_e(NULL, group, name, &result);
```
First argument to NCONF_get_number_e is also called conf. Now quoting NCONF_get_number_e:
```
    for (*result = 0; conf->meth->is_number(conf, *str);) {
```
No checks for conf being non-NULL are performed prior that point.

**Comment by paulidale** [comment]
It looks like there is a check and the right thing is done.

`NCONF_get_number_e` calls `NCONF_get_string` which in turn calls `_CONF_get_string` which does a `getenv(3)` call if _conf_ is NULL.  If `getenv(3)` returns NULL and _conf_ is NULL, an error is raised and the NULL cascades back up to `NCONF_get_number_e` where _str_ is checked and it returns before the _for_ loop.

Closing no the assumption this analysis is correct...

**Comment by paulidale** [comment]
That's reasonable.  I'm reopening this and committing to fixing it.

**Comment by paulidale** [comment]
A fix is in place + unit tests.
