### ISSUE TITLE
Webpage https://www.openssl.org/docs/fips.html shows incorrect URL

### ISSUE THREAD

**Issue by kdekker** [openssl/openssl#6625]
Unfortunately, the links to NIST in https://www.openssl.org/docs/fips.html all land on a generic search form of NIST. 

I found that the FIPS reports are accessible by using a different URL, e.g.
https://csrc.nist.gov/projects/cryptographic-module-validation-program/Certificate/1747
https://csrc.nist.gov/projects/cryptographic-module-validation-program/Certificate/2398
https://csrc.nist.gov/projects/cryptographic-module-validation-program/Certificate/2473

I was not able to find a search URL that immediately fills in the search form.

You may like to update https://www.openssl.org/docs/fips.html accordingly.

**Comment by richsalz** [comment]
2473 is owned by someone else, but 2398 and 1747 should be listed; we'll update the page, thank you.

**Comment by richsalz** [comment]
See   https://github.com/openssl/web/pull/63

**Comment by richsalz** [comment]
The website update was pushed.  Thanks!
