### ISSUE TITLE
incorrect alert sent for too large Finished messages

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#6631]
When OpenSSL server receives a Finished message that is 80 bytes or longer, it sends an incorrect alert (`illegal_parameter`) instead of the TLS 1.3 mandated `decode_error`.

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/ecdsa ecdsa
PYTHONPATH=. python scripts/test-tls13-finished.py
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
(snip)
single bit error - cipher TLS_AES_128_GCM_SHA256, bit 207 ...
OK

padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 48 ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f4e59e6f6d0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f4e59e6f590>) with last message being: <tlslite.messages.Message object at 0x7f4e58a8b090>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-finished.py", line 421, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 212, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1080, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "decode_error" does not match received "illegal_parameter"

sanity ...
OK

Fuzzing TLS 1.3 Finished messages
version: 1

Test end
successful: 698
failed: 12
  'padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 48'
  'padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 16348'
  'padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 16777183'
  'padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 48, pad_right 0'
  'padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 16348, pad_right 0'
  'padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 32'
  'padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 48'
  'padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 16332'
  'padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 16777167'
  'padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 32, pad_right 0'
  'padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 48, pad_right 0'
  'padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 16332, pad_right 0'
```

   </p></details>

**Comment by mattcaswell** [comment]
TLS1.3 has this to say about `decode_error` vs `illegal_parameter`:

    Note: TLS defines two generic alerts (see Section 6) to use upon
    failure to parse a message.  Peers which receive a message which
    cannot be parsed according to the syntax (e.g., have a length
    extending beyond the message boundary or contain an out-of-range
    length) MUST terminate the connection with a "decode_error" alert.
    Peers which receive a message which is syntactically correct but
    semantically invalid (e.g., a DHE share of p - 1, or an invalid enum)
    MUST terminate the connection with an "illegal_parameter" alert.

If we receive a Finished message where the length of the verify_data is not equal to the length of the Hash is that a syntax error or a semantic error? That sounds more like a semantic error to me (the Finished message is correctly formed, it's just that the data in it doesn't match what we would expect for the context).

Therefore, arguably, OpenSSL gets it wrong and we should be sending illegal_parameter and not decode_error in *all* cases where the Finished message size isn't as expected (including those less than 80 bytes).

In this particular case what is happening is that illegal_parameter is being sent when processing the message header, i.e. *before* we even get as far as processing the body of the Finished message. When we receive a correctly formatted message header we sanity check it before we attempt to go any further. We check that the length of the message looks reasonable for the message type. In the case of Finished there is a hard limit of 64 bytes (actually I think we could lower that to 48 - the output size of SHA384). Anything longer than that and we fail the sanity test and reject the message.

So, the message header is correctly formatted, but the message length is longer than anything we would ever expect for a Finished message. That sounds like a semantic error and illegal_parameter seems like the correct response to me?

**Comment by mattcaswell** [comment]
Good point.

However, of course, a handshake message itself *does* have an explicit length:

````
      struct {
          HandshakeType msg_type;    /* handshake type */
          uint24 length;             /* bytes in message */
          select (Handshake.msg_type) {
              case client_hello:          ClientHello;
              case server_hello:          ServerHello;
              case end_of_early_data:     EndOfEarlyData;
              case encrypted_extensions:  EncryptedExtensions;
              case certificate_request:   CertificateRequest;
              case certificate:           Certificate;
              case certificate_verify:    CertificateVerify;
              case finished:              Finished;
              case new_session_ticket:    NewSessionTicket;
              case key_update:            KeyUpdate;
          };
      } Handshake;
````
So, at this level you could consider the Finished message to be semantically incorrect if you know that the length of the message is infeasible for any valid message. That is what is happening in this scenario.

**Comment by tomato42** [comment]
> So, at this level you could consider the Finished message to be semantically incorrect if you know that the length of the message is infeasible for any valid message.

yes, and that situation ("contain an out-of-range length") is specified as decode_error

**Comment by mattcaswell** [comment]
> yes, and that situation ("contain an out-of-range length") is specified as decode_error

The length is not out-of-range according to the syntax of handshake messages. Any uint24 length is syntactically valid.

**Comment by kaduk** [comment]
Can we perhaps take a step back and ask why Hubert cares which alert is used here?

**Comment by tomato42** [comment]
@mattcaswell the specification says that if you negotiated a specific PRF, there is one and only one correct encoding of the Finished message: a single field of the length of the PRF hash, any other size is unparseable as a valid Finished message; just like a ClientHello without extensions but with a single 0x00 byte following it is unparsable as a ClientHello message or like ClientHello with 31 byte random field is unparsable.

unparsable messages should result in decode_error

> Can we perhaps take a step back and ask why Hubert cares which alert is used here?

because it is not uncommon for it to be an indicator of some deeper, more serious, issue (especially if the returned alerts are inconsistent, like in this case)

having the same behaviour makes it easier to share the test suite between different implementations (and when test suite is strict, means the bugs don't hide in plain sight) and it ensures interoperability between implementations in the process

consistency in error reporting aids in debugging issues, both for developers and networking engineers

finally, (though not as important), is that differences in alerts sent for different corner cases can be used to fingerprint implementations

**Comment by kaduk** [comment]
having the same behavior with respect to generated alerts to large part also requires having the same internal implementation state machine (i.e., the same order for all parsing and sanity checks).  I don't think that's a reasonable requirement to attempt to impose on all TLS implementations at this time.

**Comment by davidben** [comment]
In this case (and really most cases of decode_error vs. illegal_parameter), it's more an indication of the TLS adding needless complexity to error-handling. Indeed it is generally more robust to handle parameter validation and decoding as one logical unit. The separation just forces extra branches. I rather regret my part in clarifying the distinction between all those alerts in TLS 1.3. We should have folded all the "peer sent something invalid" alerts together.

To @kaduk's point regarding having the same state machine, one concrete example is if the peer sends an unexpected but badly encoded message. I've seen implementations which parse the message first and then decide if it's a valid type, and I've also seen implementations which check the type first. The former would send decode_error and the latter unexpected_message.

**Comment by mattcaswell** [comment]
> @mattcaswell the specification says that if you negotiated a specific PRF, there is one and only one correct encoding of the Finished message: a single field of the length of the PRF hash, any other size is unparseable as a valid Finished message; just like a ClientHello without extensions but with a single 0x00 byte following it is unparsable as a ClientHello message or like ClientHello with 31 byte random field is unparsable.

> unparsable messages should result in decode_error

But we have failed before we have attempted to parse the Finished  message. We are failing at the message header which has a semantically invalid length. Therefore, IMO, illegal_parameter is the correct response. In other words we have a syntactically invalid Finished contained within a syntactically correct, but semantically invalid Handshake message. Since we spot the semantic error first illegal_parameter is the result.

**Comment by tomato42** [comment]
> But we have failed before we have attempted to parse the Finished message

_openssl_ failed before, but that's not what the protocol specifies

as you've said yourself, "if you know that the length of the message is infeasible for any valid message", and the handshake protocol layer does not know that, it's just implemented in openssl in a way it does

> having the same behavior with respect to generated alerts to large part also requires having the same internal implementation state machine

this is a problem only if there are multiple errors at the same time, with a single protocol violation, you should send a specific alert; here we are talking about a single protocol violation

> Indeed it is generally more robust to handle parameter validation and decoding as one logical unit.

it also means that the code needs to have bigger context, to decide what messages are valid and which are not, which leads to not reusable code, which in turn is considered a bad programming practice. From testing perspective it also leads to more complex methods, and harder to test code (as the "units" (from unit testing) are much bigger).

> one concrete example is if the peer sends an unexpected but badly encoded message. I've seen implementations which parse the message first and then decide if it's a valid type

parsing unexpected message shouldn't happen because parsing may actually result in state being updated (even with alert being sent) or it may lead to undefined behaviour being invoked (like uninitialised memory being accessed to check if some values are within valid ranges or not)

**Comment by davidben** [comment]
You're making some rather general statements there about implementation strategies. There are different valid ways to structure a TLS implementation. I've seen quite a few at this point.

**Comment by kaduk** [comment]
A single protocol violation can be detected in different ways by different aspects of a TLS implementation.  The protocol specification does not specify precisely which order all possible checks should be performed in, ergo, there is room for implementation flexibility.  It is valid for different implementations to notice different aspects of the protocol violation first, and your compliance suite needs to take that into account.

**Comment by tomato42** [comment]
> The protocol specification does not specify precisely which order all possible checks should be performed in, ergo, there is room for implementation flexibility.

I do agree, but not in this specific example.

in this specific example, the specification says:
```
   decode_error  A message could not be decoded because some field was
      out of the specified range or the length of the message was
      incorrect.  This alert is used for errors where the message does
      not conform to the formal protocol syntax.
```
here, the length of the message is incorrect *and* it doesn't conform to formal protocol syntax, ergo, decode_error is expected.

**Comment by mattcaswell** [comment]
As you say, the specification says "A message could not be decoded ..." for decode_error. But that's not what has happened (yet). At the point that we notice a problem the message has decoded just fine. Syntactically everything was good.

The spec defines illegal_parameter as follows:

    illegal_parameter  A field in the handshake was incorrect or
      inconsistent with other fields.  This alert is used for errors
      which conform to the formal protocol syntax but are otherwise
      incorrect.

This describes exactly the situation we have and therefore IMO this is an appropriate alert to send back. Had we instead continued to process the message we would eventually have sent back a decode_error. An implementation is perfectly at liberty to fail early or late and, depending on your point of view and the point at which you spot the problem, either alert would be a reasonable choice. There is nothing in the spec that prioritises decode_error over illegal_parameter or vice versa. An implementation can choose whichever one most closely matches the situation. Your insistence that we *must* send back decode_error doesn't seem to be backed by the spec.

I think we will just have to agree to disagree on this one :-)

**Comment by mattcaswell** [comment]
> again, implementation detail,

So? Implementations are allowed to vary within the constraints of the spec.

> If that was the case, there would be no point in having decode_error, or overflow_error, or decrypt_error, or even bad_record_mac alerts as separate ones, because all of them are about "parameters" to some method or function that given other parameters or constants are "illegal". But the specification provides us with more specific errors, so they should be used when more specific errors are identified.

I don't consider "illegal_parameter" as less specific than "decode_error". In fact the spec describes them both as generic alerts to be used in different circumstances. The former being for messages which are "semantically invalid" and the latter being for messages which "cannot be parsed according to the syntax".

I don't think we are making any progress with this discussion. Unless others weigh in on this and think we should change things, I'm going to close this issue soon.

**Comment by tomato42** [comment]
please, tell me, why do you consider a Finished message of, say, 80 bytes to be a different situation than a Client Hello that has data following the extensions list?

**Comment by mattcaswell** [comment]
Because we have parsed a message which we expect to be in the "Handshake" format (as posted above). As far as we have got with the processing, it *is* in that format and we have successfully parsed it. There is no syntax error as far as we can tell so far. Due to the context external to the syntax we happen to know that a very long Finished message isn't reasonable for our implementation. This is a semantic error. Data following the ClientHello is disallowed by the syntax. It is unparseable - a syntax error.

It could be that in the future new digests are defined with very long outputs. At that point (i.e. when they are implemented in OpenSSL), longer Finished messages will suddenly become acceptable. In that case the syntax won't have changed. The semantics will have. It would be surprising if the syntax of TLSv1.3 had to change to support a longer digest.

**Comment by tomato42** [comment]
but if the Handshake header of the Client Hello indicates that it is 512KiB long, it is the same error, as there is no way to create a Client Hello longer than just over 128KiB while following the ClientHello message syntax, the only way to do it is to add data past extensions field, isn't it?

**Comment by mattcaswell** [comment]
Ah right, I see your point. But that is the same situation as for the Finished message and all the same arguments apply. At the point the implementation spots the error it could see it as a semantic error. It has parsed the header successfully without a syntax problem and seen a large length which it doesn't think is sensible. An illegal_parameter would be a reasonable choice of error at this point. Logically the implementor can take the argument further and deduce that a later syntax error is inevitable (even though we haven't seen it yet) and therefore a decode_error would also be a reasonable choice. It is up to the implementor to make that decision. The spec does not constrain the choice one way or the other.

I think we're going around in circles with this discussion now, so I'm closing this issue.

**Comment by tomato42** [comment]
>  It is up to the implementor to make that decision. The spec does not constrain the choice one way or the other.

it does for Client Hello
