### ISSUE TITLE
undefined reference to SSLv23_method

### ISSUE THREAD

**Issue by howryu** [openssl/openssl#6639]
I am compiling openssl 1.1.0g from source code using default configuration. However, it seems that linking to boost library failed because undefined reference to SSLv23_method. I know this method is deprecated, however, it is deprecated but not removed right? So in theory, it should be still supported right? Or is there any option I need to enable during the compilation? 

BTW, I did a `nm -gC libssl.a | grep SSLv23_method` and yes, I did not find this symbol.

**Comment by levitte** [comment]
You may have to rebuild the boost library if it's currently built for openssl <1.1.0. Most of all, it should include `openssl/ssl.h` to get the correct definition of `SSLv23_method`, since it is a macro from 1.1.0...
