### ISSUE TITLE
complie failed on CentOS 7

### ISSUE THREAD

**Issue by kn007** [openssl/openssl#6641]
make install failed on CentOS 7 x64(kernel 4.9.86-30) with gcc 7.3.1 20180303
```
install libcrypto.a -> /data/src/openssl/.openssl/lib/libcrypto.a
install libssl.a -> /data/src/openssl/.openssl/lib/libssl.a
install libcrypto.so.1.1 -> /data/src/openssl/.openssl/lib/libcrypto.so.1.1
link /data/src/openssl/.openssl/lib/libcrypto.so -> /data/src/openssl/.openssl/lib/libcrypto.so.1.1
install libcrypto.so -> /data/src/openssl/.openssl/lib/libcrypto.so
install libcrypto.so.1.1 -> /data/src/openssl/.openssl/lib/libcrypto.so
ar: /data/src/openssl/.openssl/lib/libcrypto.so: File format not recognized
ar: /data/src/openssl/.openssl/lib/libcrypto.so.new: File format not recognized
make: *** [Makefile:328: install_dev] Error 1
```

**Comment by levitte** [comment]
That's curious... Would you mind showing us your configuration command? The output of this should do:

```
perl configdata.pm -c
```

**Comment by kn007** [comment]
```
 perl configdata.pm -c                                                                                      master [dfee862] modified untracked

Command line (with current working directory = .):

    /usr/bin/perl ./Configure linux-x86_64 --prefix=/data/src/openssl/.openssl --openssldir=/etc/pki/tls shared zlib-dynamic enable-tls1_3 enable-weak-ssl-ciphers enable-ec_nistp_64_gcc_128

Perl information:

    /usr/bin/perl
    5.16.3 for x86_64-linux-thread-multi
```

**Comment by richsalz** [comment]
@kn007 He meant the *output* of running perl configdata.  (And . is always the name of the current working directory :)

**Comment by kn007** [comment]
@richsalz Yes, it is the result of the `perl configdata.pm -c`

**Comment by richsalz** [comment]
So it generated no output? Strange.

**Comment by kn007** [comment]
The output is here: https://github.com/openssl/openssl/issues/6641#issuecomment-402306962

**Comment by richsalz** [comment]
okay, thanks (I mis-read it).  @levitte will have to look at this.

**Comment by kn007** [comment]
Thank you.

Which gcc version is recommand?

**Comment by levitte** [comment]
The trouble with this is that the Makefile seems to be generated for AIX.  AIX is a strange beast in many regards, and the Makefile for it contains code that stuffs libcrypto.so into libcrypto.a (long story).  This shouldn't appear anywhere else, but it seems like it did in your case, hence the `ar` error messages that you see.

@dot-asm, you did the AIX work, do you have any idea what happened here?

**Comment by levitte** [comment]
It might be that my guess is wrong as well.  Looking further...

**Comment by levitte** [comment]
Well, in that case, I'm out of ideas.  @kn007, would you mind sharing the produced `Makefile`?

**Comment by levitte** [comment]
... and looking at that, I found exactly the AIX stuff that I suspected!

**Comment by levitte** [comment]
(look for `strip-X32_64`, the suspected code surrounds that line)

**Comment by levitte** [comment]
Ah, I looked through the changelog for Text::Template, and the [changes](https://metacpan.org/changes/distribution/Text-Template#L68) indicate that `Text::Template->append_text_to_output` came in version 1.46.  That means that any version older than that will fail in exactly this way (i.e. `output_off` and `output_on` have no effect).

**Comment by levitte** [comment]
So I suppose that @kn007 has an older `Text::Template`, which can be confirmed like this:

```
perl -e 'use Text::Template; print $Text::Template::VERSION,"\n";'
```

**Comment by kn007** [comment]
Thank you, it is 1.45.
Let me try to upgrade and complie again.

**Comment by kn007** [comment]
After `Text::Template` upgrade to 1.53, openssl compile fine, thanks a lot.

**Comment by nathancfox** [comment]
@kn007 Hi, I just ran into the same issue in a different setting and my Text::Template is also 1.45. How did you upgrade yours to fix the issue?

**Comment by kn007** [comment]
using cpan to upgrade it.
other way you could compile it by yourself.

**Comment by AbleSteven** [comment]
Thank you, you save my life ! @levitte
