### ISSUE TITLE
SM2 code assumes a prime field curve

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#6646]
The SM2 code seems to assume that a prime field curve is in use rather than a binary field:
https://github.com/openssl/openssl/blob/master/crypto/sm2/sm2_crypt.c#L51-L52

Is that a restriction of SM2, or is this incorrect?

Spotted by @dot-asm in this [comment](https://github.com/openssl/openssl/pull/6592#discussion_r199538789).

Ping @randombit, @ronaldtse.

**Comment by dot-asm** [comment]
As far as I understand originally SM2 resisted use of any curve other than SM2, which is GFp, but the restriction was lifted in dedicated pmeth. In other words it's probably not like it was wrong all along...

**Comment by dot-asm** [comment]
BTW, it's not the only reference to GFp. EC_POINT_[get|set]_affine_coordinates_GFp is another...

**Comment by randombit** [comment]
I have seen no reference in the standard docs to using SM2 over binary curves.

**Comment by randombit** [comment]
Ah ok there is a testcase for SM2 over a 257-bit binary curve in http://dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM2_2.pdf

**Comment by bernd-edlinger** [comment]
I always wondered why there are _GFp and _GF2m methods,
when they are look completely identical both in the interface and in the implementation?

**Comment by ronaldtse** [comment]
@randombit is correct, SM2 works over GFp and binary, but as @dot-asm pointed out, the SM2 curve is GFp and is the only "authorized" curve. The binary curve usage was only present in an "example". 

So while technically we should support both, in practice it's (probably) rarely used this way. Since we've already gone down the PMeth route, we should just support both...

**Comment by mattcaswell** [comment]
@randombit, @ronaldtse will one of you be creating a PR for this issue?

**Comment by randombit** [comment]
@mattcaswell I can do a PR for this but my queue is quite long right now.

**Comment by mattcaswell** [comment]
> @mattcaswell I can do a PR for this but my queue is quite long right now.

I see there are a couple of uses of `EC_GROUP_get_curve_GFp`, one use of `EC_POINT_set_affine_coordinates_GFp`, and multiple uses of `EC_POINT_get_affine_coordinates_GFp`. Is it correct to say that in all cases it is a simple matter of calling the equivalent GF2m function with exactly the same parameters when we are using a binary curve? Or is it more complex than that?

**Comment by romen** [comment]
@mattcaswell I am a little bit swamped at the moment to check it again, but last time I was working with this code for the SM2 manuscript, those `*_GFp` wrappers worked just fine (calling the pointers inside the EC_METHOD structure) even when the code path was forcefully fed a binary curve.

I left myself a note about digging further on why there are different wrappers for GFp and GF2m given that it seems like the EC_METHOD struct should take care of the differences between binary and prime curves, but haven't yet had the time.

You might want to look into this now!

**Comment by mattcaswell** [comment]
> I am a little bit swamped at the moment to check it again, but last time I was working with this code for the SM2 manuscript, those *_GFp wrappers worked just fine (calling the pointers inside the EC_METHOD structure) even when the code path was forcefully fed a binary curve.

Yes - they should do. Although it is a little odd to call a GFp wrapper if you have a binary curve. Probably not a practice we should encourage...unless we take the step of deprecating those wrappers altogether and provide generic ones instead.

> I left myself a note about digging further on why there are different wrappers for GFp and GF2m given that it seems like the EC_METHOD struct should take care of the differences between binary and prime curves, but haven't yet had the time.

I have often wondered this myself. I have no idea - I can't think of a good reason - but perhaps there is one.
