### ISSUE TITLE
Cannot get information about current certificate (cannot access to x509_st and x509_cinf_st structures)

### ISSUE THREAD

**Issue by kyrychen** [openssl/openssl#6649]
I try to get information about current certificate with curl_easy_getinfo (..., CURLINFO_TLS_SSL_PTR, ...) and SSL_get_peer_certificate(...) methods.
I can get x509_st pointer (as SSL_get_peer_certificate return value) but I cannot get x509_cinf_st pointer (as cert_info field).
I have found more information about "opaque" structures in 1.1.0 version but I have not found information wich accessors can I use for getting x509_cinf_st object and its fields

**Comment by richsalz** [comment]
Search for "X509_get" in doc/man3 of 1.1.0 or later release.
