### ISSUE TITLE
how to caculate the version number of  openssl

### ISSUE THREAD

**Issue by kgbook** [openssl/openssl#6657]
I failed to cross compile libcurl , log:
```
 "curl_ntlm_core.c:167:27: error: unknown type name ‘DES_key_schedule’
                         DES_key_schedule DESKEYARG(ks))"
```
I grep the symbol `DES_key_schedule`, and found it 
```
#  if (OPENSSL_VERSION_NUMBER < 0x00907001L)
#    define DES_key_schedule des_key_schedule
#    define DES_cblock des_cblock
#    define DES_set_odd_parity des_set_odd_parity 
#    define DES_set_key des_set_key                                 
#    define DES_ecb_encrypt des_ecb_encrypt                                                                                        
#    define DESKEY(x) x                                                              
#    define DESKEYARG(x) x                                                              
#  else                                                                               
#    define DESKEYARG(x) *x                                                         
#    define DESKEY(x) &x                                                               
#  endif 
```
It obvious that the openssl version number should less than 0x00907001L.

And openssl info is that:

```
/home/libopenss # ./openssl version -a
OpenSSL 1.1.1-pre9-dev  xx XXX xxxx
built on: Fri Jul  6 05:49:37 2018 UTC
platform: linux-armv4
options:  bn(64,32) rc4(char) blowfish(ptr) 
compiler: arm-hisiv300-linux-gcc -fPIC  -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DNDEBUG
OPENSSLDIR: "/home/kgbook/tools/libopenssl/ssl"
ENGINESDIR: "/home/kgbook/tools/libopenssl/lib/engines-1.1"
Seeding source: os-specific
```

The version number is not string but a long integer number, how to figure out my openssl version number?

**Comment by levitte** [comment]
The problem seems to be that you don't include the proper header files to get `DES_key_schedule` correctly defined. This line must be present in your source module:

```
#include <openssl/des.h>
```

**Comment by levitte** [comment]
... and looking at [the source module in question](https://github.com/curl/curl/blob/master/lib/curl_ntlm_core.c), it looks like it's done right, so I have no idea what to say... However, it looks to me like you should take the issue to the [curl project](https://github.com/curl/curl)

Closing

**Comment by kgbook** [comment]
@levitte 

Not that.

the lib path I pass to the configure is not right, see https://github.com/curl/curl/issues/2714

Thanks the same.

**Comment by levitte** [comment]
OK then! I'm glad this got resolved.
