### ISSUE TITLE
crypto/engine/eng_devcrypto.c: Typo in conditional hash support

### ISSUE THREAD

**Issue by cemeyer** [openssl/openssl#6672]
In `digest_data`, the conditions `# if !defined(CHECK_BSD_STYLE_MACROS) && defined(CRYPTO_RIPEMD160)`, etc, should probably have `&&` replaced with `||`, which seems to match the intent (as well as the earlier use like `#if !defined(CHECK_BSD_STYLE_MACROS) || defined(CRYPTO_AES_CTR)`).

As-is, even if a BSD-style cryptodev.h were to define a plain RIPEMD160 or SHA2, OpenSSL cryptodev will not support those hashes on that platform.

**Comment by richsalz** [comment]
Fix was merged, closing this.
