### ISSUE TITLE
CryptoAPI ENGINE (capi): Forced usage of cryptographic service provider PROV_RSA_AES if available does not work with Smart Cards

### ISSUE THREAD

**Issue by dhoelzl** [openssl/openssl#6677]
Currently there is tested if the cryptographic service provider `PROV_RSA_AES` is available:

https://github.com/openssl/openssl/blob/master/engines/e_capi.c#L480

If it is available and the type of the certificate is `PROV_RSA_FULL` it will be used regardless of the cryptographic service provider established by `CertGetCertificateContextProperty` (https://github.com/openssl/openssl/blob/master/engines/e_capi.c#L1261):

https://github.com/openssl/openssl/blob/master/engines/e_capi.c#L1476

The used cryptograpic service provider is `rsa_aes_cspname` ("Microsoft Enhanced RSA and AES Cryptographic Provider", `MS_ENH_RSA_AES_PROV`).

This works fine with our software client certificates but if a smart card is used, `CryptAcquireContext` later fails.
If the cryptographic service provider established by `CertGetCertificateContextProperty` is used, smart card certificates will work.

The CSP name (`pinfo->pwszProvName`) of the smart card client certificate is "Microsoft Base Smart Card Crypto Provider" (`MS_SCARD_PROV`).

This behavior was introduced in this commit:

https://github.com/openssl/openssl/commit/7b548d3f11adccc67123e1f6f5c118aef857a8d2

Regards,
Dominik

**Comment by richsalz** [comment]
This appears to be purely 1.1.1 issue; adding the tag.

**Comment by mattcaswell** [comment]
> This appears to be purely 1.1.1 issue; adding the tag.

The commit in question also appears in 1.1.0, so removing the 1.1.1 milestone.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing.

**Comment by dhoelzl** [comment]
> The version 1.1.1 is not supported anymore. Closing.

What about recent versions?

**Comment by t8m** [comment]
If this applies to current versions then we can reopen that. However given engines are deprecated I do not see fixing this issue would be a priority for the team. We would consider PRs if submitted.
