### ISSUE TITLE
why just encrypted message can be decrypt that only 256 byte?

### ISSUE THREAD

**Issue by ardashir66** [openssl/openssl#6678]
hi.
please help me , i using c++ and openssl, 
i encrypted message with private key and when i want to decryption it with public key
just the message decrypted truly that are 256 byte. if 257 or 258 byte  it failed and not decrypted .

`//---------------------------------- private encrypt
    encrypt = (char*)malloc(RSA_size(private_key));
    int encrypt_length = private_encrypt(strlen(message), (unsigned char*)message, (unsigned char*)encrypt, private_key, RSA_PKCS1_PADDING);
//-------------- func
int private_encrypt(int flen, unsigned char* from, unsigned char* to, RSA* key, int padding) {
    int result = RSA_private_encrypt(flen, from, to, key, padding);
    return result;
}
//---------------- decode pub key
        unsigned char* b64out=(unsigned char*)malloc(length) ;
       int rsa_outlen  = public_decrypt(
            contents1.length(), ( unsigned char*)contents1.c_str(), b64out,
            rsa, RSA_PKCS1_PADDING);
//--------------- func
int public_decrypt(int flen, unsigned char* from, unsigned char* to, RSA* key, int padding) {

    int result = RSA_public_decrypt(flen, from, to, key, padding);
    return result;
}

 `

**Comment by bernd-edlinger** [comment]
With PKCS1 Padding the plain text has to be 11 bytes shorter than the RSA block size.
If your RSA key is 2048 bits, that will be 256-11=245 bytes max plain text.
Which will result in 256 bytes cipher text.

It can't encrypt larger data.

Please note that PKCS1 Padding is not considered secure any more, therefore
you should use PSS padding or OAEP padding in new applications.

**Comment by ardashir66** [comment]
thanks in advance for answered fast.
my plain text is under 100 byte and key 2048 bits.
i dont know why another Padding type not work! so i have chosen  RSA_PKCS1_PADDING.
my problem is another thing. when encrypted text equal to 256 byte, its worked correctly .
but some of plain text 257 or 257 byte and not decrypted.

**Comment by bernd-edlinger** [comment]
RSA is not CBC, so you only encrypt one block at a time.

**Comment by ardashir66** [comment]
dear friend, i know that, but my problem is another thing.

**Comment by richsalz** [comment]
I think you should learn some more cryptography basics.
I am going to close this; OpenSSL GitHub issues aren't really the place to engage in a tutorial.
You cannot RSA-encrypt something bigger than they keysize.

**Comment by ardashir66** [comment]
oh my god, some misunderstanding happen. my block is correctly encrypted on small block. just not decrypted correctly.

**Comment by richsalz** [comment]
> just the message decrypted truly that are 256 byte. if 257 or 258 byte it failed

I don't know what you are doing.  256 bytes is 2048 bits.  That's the size of your key.  You cannot encrypt or decrypt things bigger than your key.

**Comment by bernd-edlinger** [comment]
But your code is probably wrong, because c_str() is for zero-terminated strings,
and RSA cipher blocks are not zero-terminated.

**Comment by ardashir66** [comment]
i found the problem is only not support another Padding in my program. for example when i use RSA_PKCS1_OAEP_PADDING for encryption this error happen:
error:04066076:rsa routines:rsa_ossl_private_encrypt:unknown padding type
pleasee me whats wrong that not worked another padding type ?

**Comment by bernd-edlinger** [comment]
rsa_ossl_private_encrypt is a signing routine, but OAEP is an encryption padding.
You really should learn some more cryptography basics.

**Comment by ardashir66** [comment]
Mr @bernd-edlinger  i just want to encrypt message(A) with private-key using RSA_PKCS1_OAEP_PADDING. but error coming :( error:04066076:rsa routines:rsa_ossl_private_encrypt:unknown padding type)
i did not used rsa_ossl_private_encrypt. :(

**Comment by bernd-edlinger** [comment]
Sorry I can't help you, please read the manual doc/man3/RSA_private_encrypt.pod:

`RSA_private_encrypt, RSA_public_decrypt - low level signature operations`

So a) these are low level funcitons, and b) they are for signature, not encryption.

**Comment by ardashir66** [comment]
thank you dear friends.
i got it finally. i wanted this cryptography for generate/validate license for my software. so maybe i have to use this method for my target: RSA_sign and RSA_verify.
