### ISSUE TITLE
windows.h could not be found

### ISSUE THREAD

**Issue by nasmdh** [openssl/openssl#6679]
Hello,
@ashalatan-0504
I am encountering the following error. Can someone help?

![image](https://user-images.githubusercontent.com/15107340/42452848-76f8275c-838b-11e8-8a7f-6cb05422980c.png)

I already included the file path in the file, but it is complaining with other files. I am building the program on windows 10 x64 Intel Visual C++ 2015 x64 Native...

thank you

**Comment by dot-asm** [comment]
This is not OpenSSL problem. If wouldn't be even if you were trying to compile OpenSSL, and not z3[?]. It is your responsibility to provide working development environment, as we can't possibly help with that.

**Comment by nasmdh** [comment]
it is a mistake. Please delete it if you can.
