### ISSUE TITLE
Why delete the interface SSL_CTX_set_tmp_ecdh_callback, which interface replaces it?

### ISSUE THREAD

**Issue by Trree** [openssl/openssl#6693]
Why delete the interface SSL_CTX_set_tmp_ecdh_callback, which interface replaces it?

**Comment by richsalz** [comment]
It is still there, as a macro.  To update your code, look at the CHANGES file.

**Comment by mspncp** [comment]
> It is still there, as a macro.

To be precise, `SSL_{CTX}_set_tmp_ecdh()` is (and was) a macro wrapping a `SSL_CTX_ctrl(...)` call (but the implementation changed in 6977e8ee4a718a76351ba5275a9f0be4e530eab5). The functions `SSL_{CTX}_set_tmp_ecdh_callback()` were removed in 6f78b9e824c053d062188578635c575017b587c5, see [CHANGES, 1278-1274](https://github.com/openssl/openssl/blob/master/CHANGES#L1268-#L1274).

**Comment by davidben** [comment]
To answer the original question, per that CHANGES entry, you should use `SSL_{CTX_}set1_curves` and configure your curve preferences with OpenSSL. `SSL_CTX_set_tmp_ecdh_callback` doesn't interact with TLS negotiation correctly and can result in connection failures.
