### ISSUE TITLE
Missing check?

### ISSUE THREAD

**Issue by Bugcheckers** [openssl/openssl#6695]
Hi,

I am doing some static analysis on openssl source code. I have noticed the following check in 14 files in apps directory ( e.g. dhparam.c (dhparam_main function), dsaparam.c (dsaparam_main function), ecparam.c (ecparam_main function), enc.c (enc_main function), ....]:

if (!opt_rand(o))
                goto end;

But doesn't appear in apps/ocsp.c ( ocsp_main function).

Would you let me know if the check is missed or not?

**Comment by richsalz** [comment]
ocsp doesn't have the -rand flag so the call is not there.
Basic questions like this should be posted to the mailing list; see https://mta.openssl.org for details.
