### ISSUE TITLE
OID errors

### ISSUE THREAD

**Issue by Restemayer** [openssl/openssl#6696]
I've been creating certificates for smartcard login for months, and now it doesn't work.

```
crl@crl:~/CA$ openssl req -new -newkey rsa:2048 -keyout private/rose-key.pem -out rose-req.pem -config openssluser.cnf

problem creating object scardLogin=1.3.6.1.4.1.311.20.2.2

140235418927552:error:08064066:object identifier routines:OBJ_create:oid exists../crypto/objects/obj_dat.c:701:
```

If I comment out the oid lines in the configuration file, I can make the certificate request, but issuing the certificate then fails.

```
crl@crl:~/CA$ openssl ca -config openssluser.cnf -in rose-req.pem -out rose-cert.pem

Using configuration from openssluser.cnf

Enter pass phrase for ./private/cakey.pem:

Error Loading extension section usr_cert_scarduser

140535368032704:error:0E06D06C:configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:275:group=CA_default name=email_in_dn

140535368032704:error:0D06407A:asn1 encoding routines:a2d_ASN1_OBJECT:first num too large:../crypto/asn1/a_object.c:61:

140535368032704:error:2206706E:X509 V3 routines:v2i_EXTENDED_KEY_USAGE:invalid object identifier:../crypto/x509v3/v3_extku.c:93:section:,name:scardLogin,value:

140535368032704:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=extendedKeyUsage, value=clientAuth,scardLogin
```

**Comment by Restemayer** [comment]
Ok.  Next time I'm in the office I'll rename the object in my config file and try it that way.  Any reason this seemed to work fine three or four months ago the last time I added an employee, and now it fails all over the place?  I haven't changed anything in the config file between then and now, though I have been running regular updates.  Broken by an update?

**Comment by t8m** [comment]
The RFE that was coming from this was implemented. I do not think we will be able to find out why that regression issue happened for the reporter after almost 3 years. Closing.
