### ISSUE TITLE
Openssl issue while upgrading from version 1.0.2g with fips mode enabled.

### ISSUE THREAD

**Issue by ajaynalawade** [openssl/openssl#6700]
Hi,

I am running go lang based server with fips mode enabled. I am using spacemonkeygo for openssl bindings. When I run server with version post Openssl 1.0.2g (1.0.2h onwards), I get following error while reading request from connection.
"SSL errors: SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac"

Here are some of my observations,
1. Creating 2 connections in parallel gives this issue.
2. While a client is sending data, another client connecting does not error. The error seems to be only when two clients try to handshake together. If we serialise ssl wrap even thousands of clients do not give this issue.
3. There comes a time(after 40 iterations in case of 3 parallel handshaking clients) after which the server kind of gives up and keeps on giving the same error no matter how much we slow down the clients(I stopped my client script for 5 minutes before trying again).

Here is server code, with which I am able to reproduce this issue.

`
package main

import (
    "log"
    "net"
    "net/http"
    "fmt"
    "os"
    "bufio"
    "io"
    "strconv"
    "github.com/spacemonkeygo/openssl"
)

func init_fips() {
        err := openssl.FIPSModeSet(true)
        if err != nil {
                panic(fmt.Errorf("%v Error:%v\n", "openssl failed to set fips mode.", err))
        }
        log.Print("OpenSSL FIPS mode is set to: True\n")
}

func main() {
    init_fips()
    
    laddr := "0.0.0.0:443"
    var ln net.Listener
    var err error

    // Init SSL shared context used across connections
    ctx, err := openssl.NewCtxFromFiles("/etc/certs/sslcert.crt", "/etc/certs/sslcert.key")
    if err != nil {
        log.Fatalf("Failed to read ssl certificate. Error: %v", err)
    }

    // Set options and do not allow SSLv2 and SSLv3 communication
    _ = ctx.SetOptions(openssl.CipherServerPreference |
        openssl.NoSSLv2 | openssl.NoSSLv3)

    // Read certificate
    // Listen on bind address
    ln, err = openssl.Listen("tcp", laddr, ctx)

    if err != nil {
        log.Fatalf("Failed to start server. Error: %v",
            err)
        os.Exit(1)
    } else {
            log.Println("Started secure server")
    }
    if err != nil {
        log.Fatalf("server: listen: %s", err)
    }
    log.Print("server: listening")
    for {
        accepted, err := ln.Accept()

        if err != nil {
            log.Println("Got errored while accepting connection. %v", err)
            return
        }

        go handleClient(accepted)
    }
}

func handleClient(conn net.Conn) {
    defer conn.Close()
    reader := bufio.NewReader(conn)
    for {
        //log.Print("server: conn: waiting")
        var err error
        httpreq, err := http.ReadRequest(reader)
        if err != nil {
                log.Print("Errored while reading request. Error: ", err)
                break
        }
        buf := make([]byte, httpreq.ContentLength)
        toread := int(httpreq.ContentLength)
        rbytes := 0
        n := 0
        for toread > 0 {
                n, err = httpreq.Body.Read(buf[rbytes:])
                if err != nil && err != io.EOF {
                        log.Print("Errored while reading request body. Error: ", err)
                        break
                }
                rbytes += n
                toread = toread - n
        }

        resp := append([]byte("HTTP/1.1 200 OK\r\n"+"Content-Length: "+
                strconv.Itoa(len(buf))+"\r\n\r\n"), buf...)
        _, err = conn.Write(resp)
        if err != nil {
                log.Print("Errored while writing response. Error: ", err)
                break
        }

        log.Printf("server: conn: wrote %d bytes", n)

    }
    log.Println("server: conn: closed")
}
`

Issue is reproducible with openssl-1.0.2h build with fips module openssl-fips-2.0.16.  I am running server on Ubuntu 14.04.5 .

**Comment by richsalz** [comment]
Did you set up the locking callbacks in your openssl server?

**Comment by ajaynalawade** [comment]
@richsalz, Thanks for reply. I am using spacemonkeygo binding for openssl in go lang. I am expecting spacemonkeygo during init must be setting locking callbacks. But still I will check code to confirm.

Also can setting fips mode make any difference. As I can see issue only if, FIPS_mode_set(1) is called.

**Comment by richsalz** [comment]
I have no experience with spacemonkeygo -- no knowledge of it, actually.  The symptoms you describe are consistent with locking not set, but we'll have to wait and see.

**Comment by ajaynalawade** [comment]
@richsalz , thanks for information. I can see spacemonkeygo openssl not setting CRYPTO_set_id_callback. After setting this callback server is running fine.

Any reason, why I was hitting issue only when FIPS mode is set. As CRYPTO_set_id_callback callback was not set even when running without FIPS mode, but server was running fine without any issue.

**Comment by mattcaswell** [comment]
Did you try this with OpenSSL 1.0.2m or later? Possibly it is bug #4180 which was fixed by #4192. The first release with that fix in it was 1.0.2m.

**Comment by richsalz** [comment]
I am going to close this issue.  You have working code, @mattcaswell pointed to some bugs and a later release, so there is nothing for openssl to do here.

**Comment by ajaynalawade** [comment]
I was using Openssl 1.0.2o version. Sure I have working code, but was curious 'why issue was seen with fips mode set'.

**Comment by richsalz** [comment]
It's a timing isssue.  So perhaps FIPS changes the timing of things.  We don't maintain the current FIPS code any more.  Sorry.

**Comment by ajaynalawade** [comment]
@richsalz Thanks for the help.
