### ISSUE TITLE
error: ‘i2d_ASN1_bytes’ was not declared in this scope

### ISSUE THREAD

**Issue by wdx7266** [openssl/openssl#6701]
I write the following code:

```
#include <openssl/asn1.h>
#include <vector>

int main(){
      ASN1_STRING *asn1str = ASN1_STRING_new();
     ASN1_STRING_set(asn1str, v.data(), v.size());
     char *pp[10];
     int data_len = i2d_ASN1_bytes(asn1str, pp, V_ASN1_PRIMATIVE_TAG,
                                V_ASN1_SEQUENCE);
}
```
When I try to run the above code, I got an error:

```
error: ‘i2d_ASN1_bytes’ was not declared in this scope
```

**Comment by richsalz** [comment]
It appears that function was removed when we cleaned up the ASN1 "M" macro stuff.  What are you trying to do?

**Comment by wdx7266** [comment]
I was trying to conver ASN.1 DER encoding to the original ECEDA signature data, which should have a size of 64 Bytes instead of 70 or 71 Bytes in the DER encoding mode. Now, I find the function `ECDSA_SIG *d2i_ECDSA_SIG(ECDSA_SIG **sig, const unsigned char **pp, long len)` in `ec.h`, it just satisfy the needs of decode a DER encoded ECDSA signature.

**Comment by wdx7266** [comment]
It is okay to close this, thank you very much.

**Comment by NanFeng009** [comment]
Hi, richsalz
For this series function i2d_ASN1_bytes, any replacement solution for it in openssl?  or need user implement it by themselves?

**Comment by richsalz** [comment]
I have no suggestion sorry.

**Comment by mcraiha** [comment]
Sorry to respond this late (this page has quite high Google rank with certain keywords), but the way seems to be `ASN1_put_object` +  `ASN1_object_size`. You can find some examples from Apple's example page, those examples show how to calculate length of data array and how to write the data
https://opensource.apple.com/source/OpenSSL/OpenSSL-22/openssl/crypto/pkcs7/example.c.auto.html
