### ISSUE TITLE
Build without some features

### ISSUE THREAD

**Issue by Mathiasb17** [openssl/openssl#6703]
Hello,

I need the reduce the size of the binary in my project. I would like to know if it is easy to build openssl without every feature excepted TLS and elliptic curves which are the only ones i use.

As i'm not using symmetric ciphering nor hashing function, would it be straightforward to modify the makefiles to do so ? if yes, how so ?

Thanks a lot,

**Comment by richsalz** [comment]
Short answer is no, it is not easy.  You will have to slash away at the code.  Note that TLS needs hashing functions. :)  Closing this.

**Comment by levitte** [comment]
As far as I know, TLS needs a few symmetric ciphers as well...

You *can* exclude chosen algorithms when Configuring, so if you exclude everything except a minimal set needed for your TLS requirements, you might gain some...
