### ISSUE TITLE
End Customer Impacted - OpenSSL Crash. (Official Intel Corp. submitted bug)

### ISSUE THREAD

**Issue by george-tai** [openssl/openssl#6704]
Hi, would someone be able to tell me the change log for  OPENSSL 1.0.2h - such that C2000 Rangeley can pass, C3000 Failed, but then was fixed with the Latest OpenSSL.  Unfortunately - END CUSTOMER cannot change openssl version and must keep openssl 1.0.2h, so I need to identify why it fails on C3000 but passes on C2000.  Any hints would be appreciated. 

<img width="635" alt="issue_openssl 1 0 2h" src="https://user-images.githubusercontent.com/41134788/42639085-c7bed9c2-8621-11e8-9a77-03c388c2eb7e.png">

![image](https://user-images.githubusercontent.com/41134788/42638974-94d07264-8621-11e8-87c7-c3696fc47c4d.png)

**Comment by richsalz** [comment]
Sure, look in the git commit log for all the details.  Download the release you care about and look at the NEWS and CHANGES file.  All releases can be found at https://www.openssl.org/source/old/
