### ISSUE TITLE
Cipher 0x001E mapping

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#6710]
Currently it points to `TLS_FORTEZZA_KEA_WITH_RC4_128_SHA` which is standardised in RFC6101. However according to https://www.ietf.org/mail-archive/web/tls/current/msg00036.html it is actually `TLS_KRB5_WITH_DES_CBC_SHA`.
Searching around openssl, this was previously brought up in #1743

This conflict is notable for me because `TLS_KRB5_WITH_DES_CBC_SHA` is on the http2 banned ciphers list (see [RFC7540 appendix A](https://tools.ietf.org/html/rfc7540#appendix-A))

**Comment by davidben** [comment]
The constant dates to 93ab9e421e4517b81d11ca741d55e6bb6f696c40. Even then, the only other reference was in the documentation:

> SSL_FORTEZZA_KEA_WITH_RC4_128_SHA       Not implemented.

Interestingly, OpenSSL believes 0x1D and 0x1E are the Fortezza ciphers, while the IANA registry says:

> 0x00,0x1C-1D | Reserved to avoid conflicts with SSLv3

This comes from RFC 5246:

>   Note: The cipher suite values { 0x00, 0x1C } and { 0x00, 0x1D } are
>   reserved to avoid collision with Fortezza-based cipher suites in
>   SSL 3.

However, in RFC 6101, it says the Fortezza ciphers are:

>     CipherSuite SSL_FORTEZZA_KEA_WITH_NULL_SHA         = { 0X00,0X1C };
>     CipherSuite SSL_FORTEZZA_KEA_WITH_FORTEZZA_CBC_SHA = { 0x00,0x1D };
>     CipherSuite SSL_FORTEZZA_KEA_WITH_RC4_128_SHA      = { 0x00,0x1E };

It seems SSL 3.0 originally had three Fortezza ciphers, 0x1C through 0x1E, but this was mistranscribed into TLS as only 0x1C and 0x1D, and then TLS_KRB5_WITH_DES_CBC_SHA collided with SSL_FORTEZZA_KEA_WITH_RC4_128_SHA.

I also found this thread here, which says:
https://bugzilla.mozilla.org/show_bug.cgi?id=61932
> I'd spotted the conflict. There was some discussion of this on ietf-tls 
> recently, where there was a suggestion that the single DES based 0x1e
> cipher suite should just not be implemented. This is the route I'm currently 
> taking.

At this point, both ciphers are legacy, so which is the "actual" name is kind of academic. :-)

**Comment by kaduk** [comment]
See also the recent discussion at https://www.ietf.org/mail-archive/web/tls/current/msg26454.html

**Comment by daurnimator** [comment]
Can it be confirmed that OpenSSL has never, and never will, implement either of FORTEZZA_KEA_WITH_RC4_128_SHA  or KRB5_WITH_DES_CBC_SHA?

**Comment by richsalz** [comment]
We never had Fortezza code. We did have some Kerberos code but I don’t recall what it did. We are highly unlikely to implement those old, weak, security algorithms but there are very few promises about the future that we can actually make.

**Comment by davidben** [comment]
Given the Kerberos cipher uses single-DES which costs about $30 to break, it seems like a fairly safe bet though. :-)

**Comment by tomato42** [comment]
> We did have some Kerberos code but I don’t recall what it did.

there are patches to make if fully functional, but yes, given that it uses single DES, it should not be used at all

**Comment by daurnimator** [comment]
> there are patches to make if fully functional

If there were patches for Kerberos but not for Fortezza, then we should give the id to the Kerberos cipher.

**Comment by daurnimator** [comment]
https://github.com/wahern/luaossl/pull/142/commits/e75a942f1b9783230d06235589b5f1413f05f359 is pending merge if the above sounds reasonable.

**Comment by richsalz** [comment]
This doesn't seem worth doing.  Those code-points have a mangled history, and aren't currently implemented.

**Comment by daurnimator** [comment]
okay.... considering that history I think I'm going to merge my commit to the luaossl project anyway: there's always the chance that someone out there is using an openssl < 1.1.1 with the kerberos code around.

**Comment by t8m** [comment]
This is completely obsolete now. Closing.
