### ISSUE TITLE
EC Precomputation Table fails for non-standard Generator Points

### ISSUE THREAD

**Issue by navaneethrameshan** [openssl/openssl#6714]
(Found in OpenSSL 1.0.2)
 
OpenSSL provides means to build a pre-computation table for the generator of a curve via the `EC_GROUP_precompute_mult` function. OpenSSL's default, and fastest implementation for operations on standard NIST curves is provided by `ecp_nistz256.c`.  However, when one tries to build a pre-computation table for a custom generator point, but otherwise using the same curve parameters (a, b, and p) for standard NIST curves, scalar multiplication on this curve begins failing.
 
We have traced the cause for this failure to some checks in function `ecp_nistz256_set_from_affine` of ecp_nistz256.c, which check if the first entry in the precomputed table exists on the curve.  In this case, the point is on the curve, but it is already in a Montgomery form within the pre-computation table.  Later this point gets re-encoded to Montgomery a second time, which then causes the "is on curve" check to fail.
 
Work Around:
 
We have found a work-around that succeeds, but is not pretty. It works by decoding the coordinates from Montgomery form prior to the check. See https://github.com/navaneethrameshan/openssl/commit/3c0a55deca1a5c21f2258f2742e06f5d0188aa2c 

This enables the checks to succeed, but it is a little hacky, and probably not the best long-term solution.  It looks like the reason this is not encountered in the default case is that there is check for whether or not the generator is the default generator, and if it is it falls back to using the hard-coded pre-computation table (bypassing this check entirely).  It was suggested to us that Andy Polyakov may have particular expertise in this area of the code and could provide some useful recommendations on how to best correct this issue.

**Comment by dot-asm** [comment]
Could you provide the custom generator?

**Comment by navaneethrameshan** [comment]
In this code, point multiplication with the custom generator fails when pre-computation is enabled. Here is a sample code with the custom generator: https://github.com/navaneethrameshan/openssl/commit/a80d6f722534f2970bb87eff3d7faef565f3551a

openssl was compiled with the following flags:
`./Configure linux-x86_64 -DOPENSSL_FAST_EC2M -DFAST_PCLMUL -DECP_NISTZ256_ASM -DO3 no-shared`

 If you think the work around is a good solution, I can issue a PR.

**Comment by dot-asm** [comment]
See #6738. The problem ran a bit deeper. Beside problem with representation, reference to pre_comp->precomp[0] in ecp_nistz256_set_from_affine call was x86_64-specific, i.e. wouldn't have worked on other platforms. Fixing that revealed problem with non-x86_64 scatter_w7, which had to be addressed too.

**Comment by dot-asm** [comment]
#6738 was merged and now even 1.0.2-specific #6761 is merged. Closing...
