### ISSUE TITLE
SSL_read() does not return in the server application

### ISSUE THREAD

**Issue by alicanhaman** [openssl/openssl#6715]
After our server application successfully accepts and completes the initial handshake with client peer, receiver thread in the application freezes or blocks or hangs on etc. during the read of real message. We added some additional lines in our server application and we saw that the receiver thread blocks on SSL_read() method call i.e. SSL_read() method does not return anything. Afterwards server application cannot respond to any requests from clients and the only workaround can be applied is the restart of server application. Let me state some specific status for this incident:

- This incident occurs occasionally, we did not observe any regular pattern or any specific client that always causes this issue. 

- In this application TCP sockets respectively underlying BIO is set as BLOCKING during SSL_read() call (I could not remember exact reason but we use NON-BLOCKING sockets for only SSL_accept(). After that we set back to BLOCKING mode). 

- In the Wireshark traces, we observe some RETRANSMISSION occurrences between server and client messaging but I do not know a retransmission might lead to such a blockage. 

- OpenSSL version is 1.0.2j.

Any help/proposal/recommendation would be appreciated. Thanks in advance.

**Comment by richsalz** [comment]
If your application blocked in the system call?  Or is it looping in SSL_read calling BIO_read?

**Comment by alicanhaman** [comment]
If understand your question correctlyi I would say the latter one i.e. the message can be successfully retrieved by system and then we call SSL_read as:
int result = SSL_read (MySSL, MyBuffer, MyBufferSize);
But this method does not return and therefore corresponding thread is blocked in the application.

**Comment by alicanhaman** [comment]
Thank you for your comment, the wireshark traces are overwritten unfortunately but I can say that client and server are in different countries, the connection is not really stable. Maybe some data is lost during transmission? Nevertheless, I still wonder if there a way to make the application more rebust i.e. even the specified message cannot be retrieved/processed completely, let the SSL_read() returns some error and proceeds with the next messages?

**Comment by kroeckx** [comment]
You should then really switch to non-blocking mode. SSL_read() is
documented to only return once it has data to return when in
blocking mode.

If you really want to use blocking mode, I suggest you instead
create a thread per connection.
