### ISSUE TITLE
AESNI support for CTR cipher

### ISSUE THREAD

**Issue by leonidgurevich** [openssl/openssl#6721]
Hi,
Hope this is the place to ask:
I did some work with EVP api and found out that even if AESNI is available and in use for various set of ciphers, the CTR cipher still doesn't do it.
Any particular reason, why? And are there any plans to add AESNI support for CTR?

Thanks!

**Comment by leonidgurevich** [comment]
I an using EVP API.
There are the following defines in the e_aes.c:
https://github.com/openssl/openssl/blob/master/crypto/evp/e_aes.c#L325 (and below) 

#define aesni_ctr_cipher aes_ctr_cipher  etc.

**Comment by dot-asm** [comment]
> There are following defines in the e_aes.c:

And? I mean do the referred lines actually mean that AES-NI is not used in CTR? No. They only mean that subroutine referred from corresponding EVP_CIPHER structure is not specific to AES-NI. It simply doesn't have to be. Yet it doesn't mean that AES-NI is not used in CTR. If AES-NI wasn't used then you wouldn't observe as much performance with apps/openssl speed -evp aes-128-ctr. AES-NI CTR-specific subroutine gets "wired" in aesni_init_key. [Just in case for reference. It's even possible to get rid of aesni_init_key, i.e. have common aes_init_key "wire" even AES-NI subroutines. Generally speaking e_aes.c deserves an overhaul and it's possible to improve its readability...]
