### ISSUE TITLE
Document application level retry when 0-RTT connection failed to negotiate TLS 1.3

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#6735]
if in the connection client advertised version of protocol that is not supported by server (at 1a50eedf2a1fbb1e that means 0x0304 (TLS1.3 final) or 0x7f1d (127, 29; draft-29)) but includes 0-RTT, the connection will negotiate TLS 1.2 and server will fail to handle the early data correctly (i.e. it won't continue the connection)

see also #6734 for a related, but different issue

Note: the test case uses 0x0305 as the test version (to not require changes after TLS 1.3 goes final), behaviour can be changed by editing [line 605](
https://github.com/tomato42/tlsfuzzer/blob/7e58104dd1e4c36d45ced5e038bea60de10efff4/scripts/test-tls13-0rtt-garbage.py#L605)

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tomato42/tlsfuzzer/pull/423 is merged
git checkout 0rtt-garbage-resumption
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/ecdsa ecdsa
PYTHONPATH=. python scripts/test-tls13-0rtt-garbage.py
popd
kill $openssl_pid

```

  </p></details>

   <details><summary>tlsfuzzer output</summary><p>

note the "handshake with invalid 0-RTT and unknown version (downgrade to TLS 1.2)" test case
failure in "handshake with 0-RTT, HRR and early data after 2nd Client Hello" is caused by #6734 
```
sanity ...
OK

handshake with invalid 0-RTT and CCS ...
OK

handshake with invalid 0-RTT and HRR ...
OK

handshake with invalid 0-RTT with fragmented early data ...
OK

handshake with invalid 0-RTT and unknown version (downgrade to TLS 1.2) ...
Error encountered while processing node <tlsfuzzer.expect.ExpectChangeCipherSpec object at 0x7f20988a18d0> (child: <tlsfuzzer.expect.ExpectFinished object at 0x7f20988a1910>) with last message being: <tlslite.messages.Message object at 0x7f20988a6c10>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-0rtt-garbage.py", line 727, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 210, in run
    RecordHeader2)))
AssertionError: Unexpected message from peer: Alert(fatal, unexpected_message)

undecryptable record later in handshake together with early_data ...
OK

handshake with invalid 0-RTT and CCS between early data records ...
OK

handshake with invalid PSK ...
OK

handshake with 0-RTT, HRR and early data after 2nd Client Hello ...
Error encountered while processing node <tlsfuzzer.expect.ExpectNewSessionTicket object at 0x7f209888a750> (child: <tlsfuzzer.expect.ExpectNewSessionTicket object at 0x7f209888a750>) with last message being: None
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-0rtt-garbage.py", line 727, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 196, in run
    raise AssertionError("Unexpected closure from peer")
AssertionError: Unexpected closure from peer

handshake with invalid 0-RTT ...
OK

sanity ...
OK

Basic check if TLS 1.3 server can handle 0-RTT handshake
Verify that the server can handle a 0-RTT handshake from client
even if (or rather, especially if) it doesn't support 0-RTT.

version: 1

Test end
successful: 9
failed: 2
  'handshake with 0-RTT, HRR and early data after 2nd Client Hello'
  'handshake with invalid 0-RTT and unknown version (downgrade to TLS 1.2)'
```

   </p></details>

  <details><summary>openssl output</summary><p>

```
Using default temp DH parameters
ACCEPT
140464152045376:error:140940F5:SSL routines:ssl3_read_bytes:unexpected record:ssl/record/rec_layer_s3.c:1724:
140464152045376:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:674:
```

  </p></details>

**Comment by kroeckx** [comment]
If it negotiates TLS 1.2, I'm not sure what you think is wrong.

**Comment by tomato42** [comment]
the problem is not the negotiation of TLS 1.2, the problem is that if negotiation of TLS 1.2 is a result of mismatch between supported versions (supported draft) of TLS 1.3, the server will abort the connection because it doesn't recognise the early data for what it is

[section D.3](https://tools.ietf.org/html/draft-ietf-tls-tls13-28#appendix-D.3) is a bit confusing though, speaking about only the client, not server

and together with the downgrade protection from [section 4.1.3](https://tools.ietf.org/html/draft-ietf-tls-tls13-28#page-37) a client can know if it connected to a TLS 1.3 server or not, even if the connection ended up with TLS 1.2

**Comment by kroeckx** [comment]
I'm still not sure what you're trying to say. If there is early
data on a TLS 1.2 connection, because that is what it ends up
negiotating, shouldn't it complain because it has no idea what
this early data is, and abort?

**Comment by davidben** [comment]
Right, there's not much point since existing TLS 1.2 servers will not do this. So, when we think about operation concerns with a large server deployment, the incompatibility is already an issue. Note the client text has a MUST-level requirement to reject 1.2 ServerHellos that makes this pointless anyway. (The requirement is needed to make the robust version of the client retry possible.)

> section D.3 is a bit confusing though, speaking about only the client, not server

No, D.3 talks about both clients and servers. Here is the server text.

>   To avoid this error condition, multi-server deployments SHOULD ensure
>   a uniform and stable deployment of TLS 1.3 without 0-RTT prior to
>   enabling 0-RTT.

But I agree the text isn't ideal. My original version in https://github.com/tlswg/tls13-spec/pull/439 more explicitly said to do a retry. Some of that got lost in https://github.com/tlswg/tls13-spec/pull/502, which I +1'd but, looking again, I think it got too weak. 

As far as I'm concerned, the application-level client retry on unexpected TLS 1.2 ServerHello is a requirement for playing the 0-RTT game. That was a pretty common sentiment from server operators, that this fallback is needed. While everyone SHOULD get the deployment order right, it's a bit of an operational concern.

Alas, It's an application-level retry, so it's difficult to mandate this at TLS, but so it goes. With a good 0-RTT API from the TLS layer and the right application-level organization, it turns out you basically get the client retry for free in your 0-RTT reject code.

**Comment by mattcaswell** [comment]
I agree with the above. This seems like correct behaviour to me?

**Comment by tomato42** [comment]
> I agree with the above. This seems like correct behaviour to me?

yes, it would be the correct behaviour, though introducing the retry mechanism I'm really not a fan of and in a place that it's not really necessary

> Alas, It's an application-level retry, so it's difficult to mandate this at TLS, but so it goes. With a good 0-RTT API from the TLS layer and the right application-level organization, it turns out you basically get the client retry for free in your 0-RTT reject code.

so should we verify that the s_client is performing that 0-RTT retry in case the TLS 1.3 was rejected?

(I haven't looked at the openssl test suite, so it may already be there, if it is, then this bug can be closed)

**Comment by mattcaswell** [comment]
> so should we verify that the s_client is performing that 0-RTT retry in case the TLS 1.3 was rejected?

It doesn't. But I'm not really sure it's appropriate for s_client to do so. It might make sense for browsers and other applications - but perhaps not for s_client as a testing tool.

**Comment by tomato42** [comment]
I see s_client both as a testing tool and example code

if that code wouldn't be in s_client, where should it be?

**Comment by mattcaswell** [comment]
> I see s_client both as a testing tool and example code

Yikes...don't use s_client as an example :-)

Perhaps there should be something in the man page, or on the wiki?

**Comment by tomato42** [comment]
> Yikes...don't use s_client as an example :-)

not for copy-pasting, more like "how do I use this API method"
