### ISSUE TITLE
Does openssl 1.1.1 need callback?

### ISSUE THREAD

**Issue by g10guang** [openssl/openssl#6736]
I want to invoke a https request with libcurl + openssl.

I have read some documents, such as [https://curl.haxx.se/libcurl/c/threadsafe.html](https://curl.haxx.se/libcurl/c/threadsafe.html).

In openssl <= 1.0.2, we need 2 callbacks:

```c
CRYPTO_set_id_callback((unsigned long (*)())thread_id);                                         
CRYPTO_set_locking_callback((void (*)(int, int, const char *, int))lock_callback);
```

In openssl >= 1.1.0, we need another callback:

```c
CRYPTO_THREADID_set_callback((unsigned long (*)())thread_id);
```

But I look the macro definition:

![_153188397079](https://user-images.githubusercontent.com/18458140/42857872-6032569c-8a7e-11e8-8550-2b6563c5bad8.png)

It seems they do nothing. So I want to ask **whether openssl 1.1.1 still need callbacks function to set or not in multithread environment**.

Some document is welcome. Thank you.🙂

**Comment by g10guang** [comment]
And I check the macro is set to non:

![_15318870814475](https://user-images.githubusercontent.com/18458140/42863095-86dcd91e-8a94-11e8-867c-6533f078abbc.png)

**Comment by mspncp** [comment]
The locking callbacks have been removed in 2e52e7df518d80188c865ea3f7bb3526d14b0c08, see also the note in [CHANGES, L934](https://github.com/openssl/openssl/blob/master/CHANGES#L934):

```
  *) OpenSSL now uses a new threading API. It is no longer necessary to
     set locking callbacks to use OpenSSL in a multi-threaded environment. There
     are two supported threading models: pthreads and windows threads. It is
     also possible to configure OpenSSL at compile time for "no-threads". The
     old threading API should no longer be used. The functions have been
     replaced with "no-op" compatibility macros.
     [Alessandro Ghedini, Matt Caswell]
```

**Comment by mattcaswell** [comment]
> In openssl >= 1.1.0, we need another callback:

This is not correct. No threading callbacks are required in 1.1.0

**Comment by g10guang** [comment]
@mspncp Thank you.

The **pthreads** threading mudel is `#include<pthread.h>` in Linux?

**Comment by g10guang** [comment]
@mattcaswell Sorry, maybe I am wrong. I get this information from several blogs.
