### ISSUE TITLE
tsan failure in lhash stats updates: EVP_DigestByName -> OBJ_NAME_get -> lh_retrieve

### ISSUE THREAD

**Issue by mingtaoy** [openssl/openssl#6751]
Hello! I noticed some tsan failures while testing OpenSSL 1.1.1.

PR #4429 removed the atomics in lhash and replaced them with normal, non-atomic variables.

However, lh_retrieve is being used in several other public functions (such as `EVP_get_digestbyname` that are supposedly thread safe. Because lh_retrieve modifies stats like `num_retrieves` on the get path, this causes tsan failures.

[Here](https://gist.github.com/mingtaoy/d43a5d56f56ea9520ed5e3fef2b20850#file-tsan-log) is an example of a failure.  In this example, I am sharing an `X509_STORE` object in multiple threads, with each thread creating its own `X509_STORE_CTX` and performing an `X509_verify_cert()` operation. `X509_verify_cert` eventually calls `EVP_DigestByName`, which uses an `OBJ_NAME` lhash.

One suggestion would be to not enable lhash stats by default (it seems to be mainly for debugging purposes), which would somewhat sidestep this issue. I believe this was done in PR #4427, but it looks like that PR was abandoned.

**Comment by richsalz** [comment]
Maybe add an internal hash-create API that takes flags, such as not doing stats?

**Comment by richsalz** [comment]
See #6754   Can you see if that fixes the problem?

**Comment by mingtaoy** [comment]
Almost,

`lh->error` needs to be similarly guarded, otherwise two threads calling `EVP_get_digestbyname` will [both attempt a write to `lh->error`](https://github.com/richsalz/openssl/blob/ef54be47a303e23368f23b27ee9699b102e86938/crypto/lhash/lhash.c#L169). ([tsan output](https://gist.github.com/mingtaoy/25c7a9168fbf8adf01901e3ae6275bc9))

**Comment by richsalz** [comment]
Perhaps that one variable should use the atomic variable stuff. :(

**Comment by mingtaoy** [comment]
That fixes the tsan errors for lh_retrieve. Thanks @richsalz!

**Comment by mattcaswell** [comment]
Does this impact 1.1.0 too? I'm assuming it does hence the "Assessed" milestone.

**Comment by richsalz** [comment]
*   Does this impact 1.1.0 also?

The threading issues were not documented in 1.1.0.

**Comment by kroeckx** [comment]
I looks like the error problem is a bug that should also get fixed in older versions.

**Comment by richsalz** [comment]
I cannot get fixed in 1.0.2 because there were no atomics back then. I feel it should not get fixed in 1.1.0 because the documentation is silent on thread-safety.

**Comment by dot-asm** [comment]
This is addressed in #6786, along with nit in v3_purp.c. And then there is #6891 to address same nit in 1.1.0 and 1.0.2. As for statistics in 1.1.0 and 1.0.2, we just leave them as they are, inaccurate in multi-threaded context. Well, it's not really a big problem to back-port tsan_assist.h, so if there is burning need to chase races specifically in 1.1.0 or 1.0.2, it could be arranged...
