### ISSUE TITLE
Windows build issue: expanded command too long

### ISSUE THREAD

**Issue by fkorsa** [openssl/openssl#6765]
See attached file for the exact log.

I followed these steps:

- Download sources from latest openssl-1.1.0h from website
- Install Perl using the recommended "ActiveState Perl"
- Run perl Configure VC-WIN64A
- Run nmake

I couldn't go further because of this error.

I don't know if that made any sense, but I tried to run these commands inside powershell. It was no better.

[nmake.log](https://github.com/openssl/openssl/files/2220012/nmake.log)

**Comment by levitte** [comment]
Uhmmmmmmm.......  that's the command line from the Unix Makefile, not the MSVC makefile that's usually produced.  In all likelyhood, the configuration failed for some reason.  Would you mind sharing the log for that?

**Comment by fkorsa** [comment]
Sure, here it is.
[configure.log](https://github.com/openssl/openssl/files/2222503/configure.log)

It says that NASM is not found, but if I understood NOTES.WIN correctly, it's optional, right?

**Comment by levitte** [comment]
Ah, that explains it...  well, it's optional yes, but then you have to configure with `no-asm`.

**Comment by fkorsa** [comment]
My bad. I passed no-asm to the configure script and indeed, it worked correctly. Sorry for taking your time.

**Comment by fkorsa** [comment]
If at all possible, maybe make the failure of the configure script more explicit? Either by having an error message saying that no Makefile was generated, or by not having a default Unix Makefile in the repo (which would imply that nmake will fail with a "no makefile" error).

Another fix for this particular issue would be to say explicitly in NOTES.WIN, in the paragraph concerning NASM, that no-asm must be passed if we want to build without assembler modules. However that would not the general troubleshooting of the configure script.

**Comment by levitte** [comment]
Wish granted!  See #6771

**Comment by dot-asm** [comment]
> by not having a default Unix Makefile in the repo

There is no Unix Makefile in the repo. If you had one, then it's yours.

**Comment by levitte** [comment]
There is a Unix Makefile in the tarballs we distribute, @dot-asm.  Note how @fkorsa said they downloaded the source from the web site?

**Comment by dot-asm** [comment]
Ouch! One can only wonder why... And one can probably argue that it really shouldn't be there. Or if it has to be there, then it should be "unconfigured, run config" as default target. BTW, what else shouldn't be in the tar-ball is configdata.pm. Having one worsens your chances of building off-tree. I haven't trouble-shooted it, but I'm runnign into very strange problems with configdata.pm in source tree.

**Comment by levitte** [comment]
I have asked if we should stop having a dumbed down Makefile (it's produced with the 'dist' config target)... I think it was argued that it works on the majority of platforms (Unix), so should therefore be kept around. I don't agree with that, but shrugged since that's what we have done since the dawn of time.

**Comment by t-j-h** [comment]
I think one of the original arguments against removing it was that originally we didn't depend on perl existing so we have a very plain makefile and people with non-complicated environments could actually use it as-is. I'm less convinced it is useful these days ...

**Comment by levitte** [comment]
"originally" as in pre-1.1.0, right? 'cause yeah, we've become very dependent on perl since 1.1.0, for example to produce opensslconf.h. There's no getting away from it...

**Comment by levitte** [comment]
Note that we *can* make a distribution fully populated so no perl is required.  All it takes is to have `make dist` run `$(MAKE) build_all_generated`.  Because the `dist` config target doesn't include any assembler modules, it's effectively a `no-asm` configuration.

BUT...  it's still Unix only, and I think that's the major issue...

**Comment by richsalz** [comment]
I am in favor of not distributing the Makefile.  For a future release, we should not generate anything that is built via perl.
