### ISSUE TITLE
ARM and Intel builds create incompatible encrypted files

### ISSUE THREAD

**Issue by vanmierlo** [openssl/openssl#6766]
Hi,

I'm trying to encrypt a file using openssl 1.0.2l on a 64 bit x86 intel linux platform and decrypt it on a 32 bit arm cortex-A9 linux platform using openssl 1.0.2g. But this fails with a 'bad decrypt' message. Also the other way around fails. The x86 encrypted file can correctly be decrypted on windows with either 1.0.2g or 1.0.2o, so it seems it is not a version problem. Both systems can also decrypt their own generated files. I'm using AES256.

Should I assume the ARM build to be broken?

Maarten

**Comment by vanmierlo** [comment]
I did not (consciously) build any version. The x86 linux version came with Ubuntu16, the Windows versions I downloaded from https://indy.fulgan.com/SSL/ and the ARM version came from Yocto Rocko which I think came precompiled as well.

From your comment I take it this not a known problem. I'll download the sources and try to cross-compile them myself. But I'm not sure yet how I should run 'make test' cross-platform.

**Comment by vanmierlo** [comment]
I have pulled the 1.0.2p sources from git and cross-compiled them. I had to jump through some hoops to get the so's as well. The resulting openssl + libs create aes256 encrypted files on arm that the x86 can read and vice versa.

So I guess I'm barking up the wrong tree and should turn to Yocto instead.

**Comment by vanmierlo** [comment]
On the openembedded mailing list I got an answer that tells me this problem *was* an issue (#4659) in openssl, caused by either openssl sources or by bin-utils (2.29) which should now be fixed.

**Comment by kaduk** [comment]
Recording for posterity, cross-compiling and 'make test' do not currently play well together.

**Comment by vanmierlo** [comment]
Btw. binutils have also reverted the behavior of ADR under normal conditions in 2.31.

**Comment by dot-asm** [comment]
Thanks for report!

As for 'make test' and cross-compiling not getting along. While this is not untrue in most general case, it's not that impossible on Linux for Linux targets, thanks to qemu-user. Quite contrary, very simple once you figure it out. One even has two options. One is `env EXE_SHELL=qemu-<arch> make test`, another is to setup binfmt to call qemu-<arch>, so that alien binaries can be executed from shell prompt as if they were native.
