### ISSUE TITLE
Cannot get peer certificate within callback

### ISSUE THREAD

**Issue by noahdav** [openssl/openssl#6777]
Hi,

In OpenSSL 1.0.3 I am trying to implement a peer verification callback by using SSL_CTX_set_cert_verify_callback.  In my callback I am trying to get the X509 cert from the X509_STORE_CTX.

int verify_callback(X509_STORE_CTX* ctx, void* arg) {
 ...
X509* cert = ctx->cert;
...
}

This works fine in all of the architectures we are building except of MIPS.
error: dereferencing pointer to incomplete type 'X509_STORE_CTX {aka struct x509_store_ctx_st}'
             cert = ctx->cert;

I do not have access to a MIPS build to test this as it is only being built as part of the pull request.  Is this not a safe way to get the certificate?  From what I can see I do not understand why this is not supported.  Can someone point me to how to get the peer certificate within the callback on all architectures?

**Comment by richsalz** [comment]
There's a bit of confusion here.  There is no such thing as 1.0.3 from the openssl project.
If code works on one build, and doesn't on another, then the first one is 1.0.2 or earlier, and the latter is 1.1.0.

We made structures opaque in 1.1.0 (the "incomplete type").  The function to use is ```X509_STORE_CTX_get_current_cert```

Closing this.

**Comment by noahdav** [comment]
Sorry the confusion.  I am using 1.0.2 from the OpenSSL_1_0_2-stable branch.  When I use X509_STORE_CTX_get_current_cert it returns NULL in normal cases.  According to docs X509_STORE_CTX_get_current_cert() returns the certificate in ctx which caused the error or NULL if no certificate is relevant.

In my case I need to verify the peer certificate so is there another way to retrieve this.

**Comment by richsalz** [comment]
Is it possible that the other side did not send a cert?  This should only happen if you are the server.

**Comment by noahdav** [comment]
@richsalz can you please reactivate this post.

I am on the client trying to perform mutual auth.  I am using the callback to verify that the server cert is what we expect.  In our case we have a custom security provider which will validate the cert which we pass to it.  If I use ctx->cert I am able to get what appears to be the server cert.  However when I use _STORE_CTX_get_current_cert it returns NULL which according to the documentation appears to be the correct behavior.

Since ctx->cert is working in all platforms which are built except for MIPS is there something that I need to do in order to get this on the MIPS platform?  On MIPS this fails at compile time with the error above. 
 If this is not the correct way to get the peer certificate within the callback registered in there another supported way?

Here is how I am registering the callback as well.   
        SSL_CTX_set_verify(ctx,
            SSL_VERIFY_PEER | SSL_VERIFY_CLIENT_ONCE | SSL_VERIFY_FAIL_IF_NO_PEER_CERT,
            NULL);

        SSL_CTX_set_cert_verify_callback(
            ctx,
            verify_callback,
            NULL);

**Comment by richsalz** [comment]
Something is wrong with the source code on MIPS.  I don't know what you'll have to do to diagnose or fix that.

**Comment by noahdav** [comment]
does anyone have any pointers on how to get this working for MIPS in 1.0.2.  I am stuck on what I need to do in order to get this resolved.

**Comment by t8m** [comment]
The 1.0.2 releases are no longer supported. Closing.
