### ISSUE TITLE
When setting RAND_DRBG_FLAG_CTR_NO_DF we're not compliant with FIPS

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#6780]
We need to get full entropy from the parent DRBG when not using a DF. A DRBG only generates full entropy for the first strength / 2 output. That means that if you want to update the child DRBG and the parent and child have the same strength, you need to reseed the parent twice and each time get half of the entropy you need.

See SP800-90C 10.1.2.

Cc: @slontis

**Comment by paulidale** [comment]
Can we ban the `no_df` DRBG case for FIPS?
This can either be done in the code or via the security policy.  We don't have a policy for the latter yet.

I'd be tempted to ban the `no_df` case outside of FIPS too, it doesn't make a lot of sense.

**Comment by paulidale** [comment]
Adding a reference to #6778

**Comment by kroeckx** [comment]
I have no problem banning NO_DF in FIPS mode. I was just surprised that @slontis was using it, while he seems to be working on FIPS support.

**Comment by slontis** [comment]
Only used by accident while testing set_defaults(). :) The changes I have been doing are not necessarily fips. What I was testing was swapping between different DRBG types.

**Comment by paulidale** [comment]
This was resolved by #6778 
Closing.

The no_df case hasn't been banned outside of FIPS.  That would be a new issue.
