### ISSUE TITLE
"./config no-bio" compilation failure

### ISSUE THREAD

**Issue by pranavabhat** [openssl/openssl#6784]
Hi All,

Just need to understand if there is any more changes needed to compile with "**no-bio**" configuration option.
The following is the error seen:

**In file included from cpt_err.c:63:0:
../include/openssl/err.h:149:5: error: unknown type name 'CRYPTO_THREADID'
     CRYPTO_THREADID tid;
     ^
../include/openssl/err.h:356:36: error: unknown type name 'CRYPTO_THREADID'
 void ERR_remove_thread_state(const CRYPTO_THREADID *tid);
                                    ^
make[1]: *** [cpt_err.o] Error 1
make[1]: Leaving directory `/home/pranava/OpenSSL/crypto'
make: *** [build_crypto] Error 1**

Thanks,
Pranava

**Comment by richsalz** [comment]
This is not really supported.  For example, libssl will not work.  I think this issue should be closed.
