### ISSUE TITLE
Missing return value check of ASN1_INTEGER_set() in crypto/pkcs12/p12_init.c

### ISSUE THREAD

**Issue by Jason2031** [openssl/openssl#6789]
Function `ASN1_INTEGER_set()` sets the value of its parameter. It may return 0 for failure. Function `v2i_TLS_FEATURE` defined in `crypto/x509v3/v3_tlsf.c` calls `ASN1_INTEGER_set()` and forgets the return value check. See the following code: 
```c
static TLS_FEATURE *v2i_TLS_FEATURE(const X509V3_EXT_METHOD *method,
                                    X509V3_CTX *ctx, STACK_OF(CONF_VALUE) *nval)
{
    ... // omitted
        ASN1_INTEGER_set(ai, tlsextid);
        sk_ASN1_INTEGER_push(tlsf, ai);
    }
    return tlsf;

 err:
    sk_ASN1_INTEGER_pop_free(tlsf, ASN1_INTEGER_free);
    return NULL;
}
```
Jiecheng Wu, Zuxing Gu

**Comment by richsalz** [comment]
We fixed this in master and 1.1.0; thanks for the report!
