### ISSUE TITLE
undetectable SSL_CTX leak in SSL_new()

### ISSUE THREAD

**Issue by yumeyao** [openssl/openssl#6793]
CLA: trivial

when i'm analysing the source code, I find there is a potential SSL_CTX leak in SSL_new()

`SSL *SSL_new(SSL_CTX *ctx);`

When it succeeds, ctx will be assigned to ssl->ctx, therefore upon SSL_free(), ssl->ctx will be freed. In other words, ctx's **ownership** has been transferred to ssl.

But when it fails, it would become impossible to know whether the ctx is freed inside the function.
- An early fail would cause ctx left unfreed.
- A late fail would cause ctx being freed.

To fix this issue, we only need to change 
```
 err:
    if (s != NULL)
        SSL_free(s);
```
to
```
 err:
    if (s != NULL) {
        s->ctx = NULL;
        SSL_free(s);
    }
```

so that we will have a unified behavior:
- If the function succeeds, ssl_ctx will be owned by ssl. freeing ssl frees ssl_ctx. no need to handle ssl_ctx separately afterwards.
- If the function fails, ssl_ctx is not freed and requires the user to free it manually.

moving the statement of assigning ctx to some place right before success return won't work because s->ctx may be used in `s->method->ssl_new(s)` and we need to check its return value.

**Comment by t-j-h** [comment]
SSL_CTX is reference counted - the reference is incremented in the line before s->ctx=ctx and in the SSL_CTX_free the reference is decremented. There is no actual free in the call in the error handling path - it works entirely as a reference count decrement.

**Comment by yumeyao** [comment]
I see.
So the user should always free SSL_CTX and can free it at any time right?

ctx->references = 1 in SSL_CTX_new()
+2 in SSL_new() if success (1 for ssl->ctx, another for ssl->session_ctx)
+0 if fails
and -2 in SSL_free() for a valid SSL
-1 for SSL_CTX_free()

**Comment by t8m** [comment]
> So the user should always free SSL_CTX and can free it at any time right?

Yes. Closing.
