### ISSUE TITLE
s_client: Option unknown option -ssl3 though -ssl3 present in man

### ISSUE THREAD

**Issue by BohdanHamulets** [openssl/openssl#6801]
When using a `openssl s_client -connect <server>:<port> -ssl3` I get:

```
s_client: Option unknown option -ssl3
s_client: Use -help for summary.
```

When using `openssl s_client -help`, this option is indeed not listed, while on `man s_client` it's there:

```
-**ssl3**, -tls1, -tls1_1, -tls1_2, -no_ssl3, -no_tls1, -no_tls1_1, -no_tls1_2
           These options require or disable the use of the specified SSL or TLS protocols.  By default s_client will negotiate the highest mutually supported protocol version.  When a specific TLS
           version is required, only that version will be offered to and accepted from the server.
```

Bug in documentation or in the s_client itself? 

openssl is already the newest version (1.1.0f-3+deb9u2)

**Comment by kroeckx** [comment]
SSLv3 support is disabled by default, so that option does not work.
You need to recompile if you really need SSLv3 support, but I
suggest you don't.

**Comment by BohdanHamulets** [comment]
Okay, so this should be then reflected in the man page, or removed, right?

**Comment by richsalz** [comment]
See #6816

**Comment by tmshort** [comment]
Should this be closed, given that #6816 is closed?

**Comment by richsalz** [comment]
yes, thanks for the reminder. closing this issue.

**Comment by BohdanHamulets** [comment]
Yes, thanks a lot!

9 серп. 2018 р. 16:41 "Todd Short" <notifications@github.com> пише:
