### ISSUE TITLE
Webpage/manpages don't show B<> perldoc tags bold

### ISSUE THREAD

**Issue by bbolli** [openssl/openssl#6803]
The very first CSS rule in `/inc/screen.css` has the style `font: inherit`. This suppresses the effect of all `B<>` perldoc tags that we insert painstakingly into the man pages' source.

**Comment by levitte** [comment]
This issue is misplaced, should really be in [the web repo](/openssl/web)

**Comment by levitte** [comment]
(copied to openssl/web#74)
