### ISSUE TITLE
"Certificate required" alert should not be mapped to "handshake failure"

### ISSUE THREAD

**Issue by p-mongo** [openssl/openssl#6804]
https://github.com/openssl/openssl/commit/42c28b637c5ac9a288a0a6bde8f32622ba60e0a1 added this line:

<pre>
   case SSL_AD_CERTIFICATE_REQUIRED:
        return SSL_AD_HANDSHAKE_FAILURE;
</pre>

And same for TLS.

My understanding is this causes servers to report "handshake failure" to clients when a client did not provide a certificate to the server and the server required a certificate to be provided. These are distinct conditions as far as I can tell, according to the description of "handshake failure" in https://github.com/tlswg/tls13-spec/blob/master/draft-ietf-tls-tls13.md. A handshake failure error is very generic and usually difficult/impossible to debug.

https://github.com/tlswg/tls13-spec/blob/master/draft-ietf-tls-tls13.md also specifies a "certificate_required" alert; it seems to me that this should be sent to clients when a certificate is required and not supplied.

**Comment by mattcaswell** [comment]
Fix in #6809

**Comment by p-mongo** [comment]
Thank you for the quick fix. TLS 1.2 (https://www.ietf.org/rfc/rfc5246.txt) seems to not have anything like a "certificate required" alert, thus using TLS 1.3+ is desired for better error reporting. Good to know.
