### ISSUE TITLE
About the performance of multi-prime RSA

### ISSUE THREAD

**Issue by armman475** [openssl/openssl#6808]
I tested the performance of multi-prime RSA with Openssl1.1.1-pre3, and the results were not as expected.

```
# ./openssl speed -primes 3 rsa2048
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000934s 0.000036s   1070.3  27899.1

# ./openssl speed -primes 2 rsa2048
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000812s 0.000036s   1231.1  28078.2
```

3 prime should be better than 2 prime.Is my understanding wrong?

**Comment by kroeckx** [comment]
I get for 3:
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000883s 0.000035s   1132.7  28492.3
rsa 4096 bits 0.005973s 0.000128s    167.4   7803.8
for 2:
rsa 2048 bits 0.001162s 0.000035s    860.6  28540.3
rsa 4096 bits 0.008280s 0.000130s    120.8   7702.1

The sign operations are faster.


Kurt

**Comment by armman475** [comment]
The same environment.
./openssl speed -primes 3 rsa4096
                  sign    verify    sign/s verify/s
rsa 4096 bits 0.006424s 0.000133s    155.7   7505.4

# ./openssl speed -primes 2 rsa4096
                  sign    verify    sign/s verify/s
rsa 4096 bits 0.008672s 0.000133s    115.3   7499.3

Is my rsa2048 result normal?

**Comment by t-j-h** [comment]
What is your platform?
What details come from ./openssl version -a

I certainly see improved performance for 3-print 2048 and 4096.

2-prime 
> rsa 2048 bits 0.000866s 0.000026s   1154.8  39133.7
> rsa 4096 bits 0.006220s 0.000096s     160.8  10456.9

3-prime
>rsa 2048 bits 0.000666s 0.000025s   1501.2  39446.0
>rsa 4096 bits 0.004504s 0.000096s     222.0  10459.5


This is on a standard Ubuntu 16.04 build of master with default option in a VM on 
> model name      : Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz

**Comment by t-j-h** [comment]
I'm running *master* - i.e. current latest code. 

I suggest you check master or move forward onto a later 1.1.1 beta release - pre8 was 20-Jun-2018 ... pre3 is pretty old relatively speaking.

**Comment by armman475** [comment]
I compiled the latest version and the resultis still the same.
./config
make

**Comment by davidben** [comment]
There is dedicated RSAZ code for RSA private key operations with 1024-bit primes (so 2048-bit two-prime RSA). It only kicks in on some CPUs (I believe it's if you have AVX2 but not ADX), so that may explain the discrepancy.

**Comment by randombit** [comment]
With latest master (28c5b7d482) on Skylake i7-6700k (has AVX2+ADX), GCC 8.1

2 primes
```
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000491s 0.000014s   2034.7  70347.0
rsa 3072 bits 0.001471s 0.000029s    679.7  33996.3
rsa 4096 bits 0.003441s 0.000050s    290.6  19887.6
```

3 primes
```
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000627s 0.000014s   1594.6  70220.7
rsa 3072 bits 0.000757s 0.000030s   1321.0  33890.0
rsa 4096 bits 0.003708s 0.000050s    269.7  19847.7
```

4 primes

```
                  sign    verify    sign/s verify/s
rsa 4096 bits 0.001085s 0.000051s    922.1  19653.7
```

3 prime 3072 and 4 prime 4096 are much faster, probably because it hits the dedicated path for 1024 bit modexp. But 3 prime 2048+4096 are slower.

**Comment by mattcaswell** [comment]
What should we do with this issue? This has the 1.1.1 milestone against it.

**Comment by paulidale** [comment]
I can't see what can be done apart from closing it.  Disabling the fast path code seems counterproductive and it is too late to create fast path code for other sizes.  The best I can think of is a line in the documentation explaining that some sized numbers are just faster.

**Comment by mattcaswell** [comment]
Ok - closing as per above.
