### ISSUE TITLE
DEPRECATEDIN_1_2_0() is too eager

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#6814]
We have some functions that are due to be deprecated in 1.2.0. We have marked those future deprecations with the `DEPRECATEDIN_1_2_0` macro. However it is too eager and it is actually marking these functions as deprecated *now*. If you compile code using the marked functions the compiler will warn about their use.

**Comment by mattcaswell** [comment]
I think there are probably 3 scenarios we *may* want to support. At a minimum we need to support (1):

1) The default: You can use these functions in 1.1.1 and there will be no warnings. This must be the default in order to preserve our compatibility guarantee (a user should be able to drop in the 1.1.1 headers without suddenly getting new warnings)

2) Switch on warnings for stuff that will be deprecated in the future but still build in support for it. This would probably have to be a new option. Using it would be an explicit acceptance that the compatibility guarantee wouldn't apply, and builds could be broken at any time with any future update.

3) Same as (2) but additionally don't build in support for the deprecated functions.

**Comment by levitte** [comment]
Hmmm? I thought I had fixed it to do (1), not at all long ago...

**Comment by levitte** [comment]
Oh...  I might have found it, and we can look at any deprecation macro, such as:

```
#if OPENSSL_API_COMPAT < 0x10000000L
# define DEPRECATEDIN_1_0_0(f)   DECLARE_DEPRECATED(f)
#else
# define DEPRECATEDIN_1_0_0(f)
#endif
```

So what this is telling me is that when we have an API compatibility for something older than 1.0.0, we apply the 1.0.0 deprecation.  If we have an API compatibility for 1.0.0 *or newer*, we don't apply the 1.0.0 deprecation.  Am I reading that correctly?

**Comment by mattcaswell** [comment]
As currently defined the `DEPRECATEDIN` macros do one of two things:

- If OPENSSL_API_COMPAT is less than the specified level then they build-in support for the function *but mark it as deprecated*. This is the same as scenario (2) above

- If OPENSSL_API_COMPAT is equal to or greater than the specified level the declaration for the function disappears completely so it cannot be used. This is scenario (3).

What we don't have is anyway to do scenario (1), i.e. build-in support and don't mark it as deprecated in the case where the deprecation is for a future version.

**Comment by levitte** [comment]
Ah!
