### ISSUE TITLE
1.1.0h - brainpoolP512t1 no shared cipher

### ISSUE THREAD

**Issue by n8v8R** [openssl/openssl#6818]
Having generated a private key with `openssl ecparam -name brainpoolP512t1 -genkey` and then tested the CA signed certificate produces:

`openssl s_server -cert /etc/pki/certs/ec.cert.pem -key /etc/pki/private/ec.key.pem -port 5555`

> Using default temp DH parameters
> ACCEPT
> ERROR
> 140556848214464:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:1404:
> shutting down SSL

---

`openssl s_client -connect localhost:5555`

> CONNECTED(00000003)
> 140592558260672:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1407:SSL alert number 40
> 
> no peer certificate available
> 
> No client certificate CA names sent
> 
> SSL handshake has read 7 bytes and written 176 bytes
> Verification: OK
> 
> New, (NONE), Cipher is (NONE)
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : 0000
>     Session-ID:
>     Session-ID-ctx:
>     Master-Key:
>     PSK identity: None
>     PSK identity hint: None
>     SRP username: None
>     Start Time: 1532975393
>     Timeout   : 7200 (sec)
>     Verify return code: 0 (ok)
>     Extended master secret: no

---

Since I first thought this being a bug in dovecot the issue was discussed on their mailing list but the dovecot developers had the some results with this curve.

**Comment by richsalz** [comment]
The only curves that are supported in TLS are P256r1, P384r1, and p512r1. You can generate those other curves, but can't use them in TLS.  See IETF RFC 7027.  Closing.

**Comment by n8v8R** [comment]
Unless minsunderstanding brainpoolP512**r**1 should work though but not brainpoolP512**t**1

> 2.  Brainpool NamedCurve Types
> 
>    According to [RFC4492], the name space NamedCurve is used for the
>    negotiation of elliptic curve groups for key exchange during a
>    handshake starting a new TLS session.  This document adds new
>    NamedCurve types to three elliptic curves defined in [RFC5639] as
>    follows:
> 
>            enum {
>                 brainpoolP256r1(26),
>                 brainpoolP384r1(27),
>                 brainpoolP512r1(28)
>            } NamedCurve;
> 
>    These curves are suitable for use with Datagram TLS [RFC6347].

**Comment by richsalz** [comment]
Right.  And you generated, and tried to use, p512t1

**Comment by n8v8R** [comment]
Ok, so I did now `openssl ecparam -name brainpoolP512r1 -genkey` and then ran the same test as above but it yields the same result however.

This is the genrated certificate
```
-----BEGIN CERTIFICATE-----
MIICkDCCAfWgAwIBAgIJALoslKv/bCcbMAoGCCqGSM49BAMEMFkxCzAJBgNVBAYT
AjAwMQswCQYDVQQIDAIwMDELMAkGA1UEBwwCMDAxDTALBgNVBAoMBHRlc3QxDzAN
BgNVBAsMBlNlcnZlcjEQMA4GA1UEAwwHRUMgdGVzdDAeFw0xODA3MzAxOTUxMDla
Fw00ODA5MTAxOTUxMDlaMFkxCzAJBgNVBAYTAjAwMQswCQYDVQQIDAIwMDELMAkG
A1UEBwwCMDAxDTALBgNVBAoMBHRlc3QxDzANBgNVBAsMBlNlcnZlcjEQMA4GA1UE
AwwHRUMgdGVzdDCBmzAUBgcqhkjOPQIBBgkrJAMDAggBAQ0DgYIABAFHVrvDePBc
lwDWOEphC1Be3q6bA0CxqAE8NOWoTz5Z95F58l5fkvKiFQSLxSjqvHFmMKLpnU2j
wHbEsf4NYHaTxQI1jGs4A5dHz0SSzUfrczlBWYTLwoYFJ7FuqtNvoE9bSrrqVFh0
LY+MAbfLIwZ8IaJawWzHzyyqiKaeXMbho2MwYTAdBgNVHQ4EFgQUmNmHYuBZDloU
G/WqqiBQOc2QCVgwHwYDVR0jBBgwFoAUmNmHYuBZDloUG/WqqiBQOc2QCVgwDwYD
VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwQDgYgAMIGE
AkBX0ckLxGR1xioJYIt1fGJy1CJAkCIkkZfqdWmrW0NiM32F2sc8/Z71pU6/EXMJ
MtuAOva7HQ3eaUSfy8hyIn/ZAkBnhAyhWI+ON0Uc9dVqywEkd0UNeiwAplQcQ08m
xElLbtNTmEgVD8UX24XSUNDMzKyRq9ev1DhU6bpTsx5TF/dn
-----END CERTIFICATE-----
```

**Comment by richsalz** [comment]
Try to capture packets and do a dump (such as via wireshark).

**Comment by n8v8R** [comment]
Suppose that is what it boils down to? Meaning that there is no support for` brainpoolP512r1` in 1.1.0h?

```
Extension: supported_groups (len=10)
    Type: supported_groups (10)
    Length: 10
    Supported Groups List Length: 8
    Supported Groups (4 groups)
        Supported Group: x25519 (0x001d)
        Supported Group: secp256r1 (0x0017)
        Supported Group: secp521r1 (0x0019)
        Supported Group: secp384r1 (0x0018)
```

**Comment by richsalz** [comment]
You have to call the ```SSL_CTX_set1_groups_list``` API in your code, or use the ```-groups``` flag (I think) to s_client and s_server.

**Comment by t-j-h** [comment]
The -groups option is relatively new - it was added in commit 863fe19b5fb4a2af9f47ed664cb9dcb7d52331d1

**Comment by richsalz** [comment]
Use -curves instead of -groups for non-master.

**Comment by n8v8R** [comment]
Ha, and there is works indeed.

And how does that translate in the app API `SSL_CTX_set1`?

**Comment by richsalz** [comment]
If you write your own code, you'll need the API call.  IF you use the command-line only, you're all set.

**Comment by n8v8R** [comment]
I am not writing code but depending on apps to make the API call, like dovecot - which currently does not work with the brainpool curves.

Apparently `-curve`  on the cli needs to be set both ends (s_server | s_client) but how is that supposed to work from the app. Appologies if that question is beyond the scope of the ticket, just want to make it work...

**Comment by kroeckx** [comment]
In your version the functions are probably still called
SSL_CTX_set1_curves() and SSL_CTX_set1_curves_list(). See the
manpage.
