### ISSUE TITLE
Missing return value check of ASN1_INTEGER_to_BN() in crypto/ts/ts_lib.c

### ISSUE THREAD

**Issue by Jason2031** [openssl/openssl#6820]
Function `ASN1_INTEGER_to_BN()` converts ASN1_INTEGER ai into a BIGNUM. It may return NULL if the passed type is incorrect (due to programming error) or due to a memory allocation failure. Function `TS_ASN1_INTEGER_print_bio()` defined in crypto/ts/ts_lib.c calls `ASN1_INTEGER_to_BN()` but forgets the return value check. See the following code:
```c
int TS_ASN1_INTEGER_print_bio(BIO *bio, const ASN1_INTEGER *num)
{
    BIGNUM *num_bn;
    int result = 0;
    char *hex;

    num_bn = BN_new();
    if (num_bn == NULL)
        return -1;
    ASN1_INTEGER_to_BN(num, num_bn);  // missing return value check
    if ((hex = BN_bn2hex(num_bn))) {
        result = BIO_write(bio, "0x", 2) > 0;
        result = result && BIO_write(bio, hex, strlen(hex)) > 0;
        OPENSSL_free(hex);
    }
    BN_free(num_bn);

    return result;
}
```
Jiecheng Wu, Zuxing Gu

**Comment by paulidale** [comment]
Should be fixed in master now.

**Comment by mattcaswell** [comment]
Fix was merged so closing.
