### ISSUE TITLE
Make RAND_METHOD opaque

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#6829]
See some discussion in #3797

**Comment by colmmacc** [comment]
Its it worth considering making a no-op that does nothing?

**Comment by richsalz** [comment]
Or maybe always return an error.  Not sure.

**Comment by levitte** [comment]
Side note: shouldn't this be labeled 1.2.0? That would clearly mark it for the next major release.
(I thought I had created that label, why did it disappear?)

**Comment by richsalz** [comment]
closing this as #10017 has more discussion.
