### ISSUE TITLE
EVP_CTRL_GCM_SET_IVLEN didn't work

### ISSUE THREAD

**Issue by wdx7266** [openssl/openssl#6831]
I try the example in [openssl wiki]( https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption#Authenticated_Encryption_using_GCM_mode), and want to set IV length.

```
        EVP_CIPHER_CTX *ctx;

        int len;

        int ciphertext_len;

        /* Create and initialise the context */
        if (!(ctx = EVP_CIPHER_CTX_new()))
        {
            throw std::runtime_error("Error");
        }

        /* Initialise the encryption operation. */
        if (1 != EVP_EncryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, NULL, NULL))
        {
            throw std::runtime_error("Error");
        }

        /* Set IV length if default 12 bytes (96 bits) is not appropriate */
        if (1 !=
            EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, 16, NULL))
        {
            throw std::runtime_error("Error");
        }
        std::cout << EVP_CIPHER_CTX_iv_length(ctx) << std::endl;

```

However, it didn't run as my expectation, the output is still the 12.

The OpenSSL version I use is the OpenSSL 1.1.1-pre8 (beta), just as the following:

```
$ openssl version
OpenSSL 1.1.1-pre8 (beta) 20 Jun 2018
```

So, what's the right way to use the `EVP_CTRL_GCM_SET_IVLEN` to control the length of IV?

**Comment by mattcaswell** [comment]
You're doing it right. The function `EVP_CIPHER_CTX_iv_length(ctx)` returns the *default* IV length, not the length overridden by `EVP_CTRL_GCM_SET_IVLEN`.

Note that you should use `EVP_CTRL_AEAD_SET_IVLEN` in preference to `EVP_CTRL_GCM_SET_IVLEN`. They are synonyms and behave identically but the former is the preferred name moving forward.

**Comment by jatinarora2409** [comment]
Is there a way we can check that, this working or not?
