### ISSUE TITLE
Qualified Certificate Statements extension is not in the critical extensions list

### ISSUE THREAD

**Issue by carioli** [openssl/openssl#6834]
Qualified Certificate Statements extension may be critical or non-critical according to the 3.2.6 paragraph of the RFC 3739 Internet X.509 Public Key Infrastructure: Qualified Certificates Profile.
But it is not in the critical extensions list: 

    static const int supported_nids[] = {
        NID_netscape_cert_type, /* 71 */
        NID_key_usage,          /* 83 */
        NID_subject_alt_name,   /* 85 */
        NID_basic_constraints,  /* 87 */
        NID_certificate_policies, /* 89 */
        NID_crl_distribution_points, /* 103 */
        NID_ext_key_usage,      /* 126 */
    #ifndef OPENSSL_NO_RFC3779
        NID_sbgp_ipAddrBlock,   /* 290 */
        NID_sbgp_autonomousSysNum, /* 291 */
    #endif
        NID_policy_constraints, /* 401 */
        NID_proxyCertInfo,      /* 663 */
        NID_name_constraints,   /* 666 */
        NID_policy_mappings,    /* 747 */
        NID_inhibit_any_policy  /* 748 */
    };

**Comment by richsalz** [comment]
It is not in the critical list because there is no code to implement and check the semantics of those values.

**Comment by carioli** [comment]
Is exist any way to extend this list for the software which checks the semantics of those values ?

**Comment by richsalz** [comment]
Sure, write the code and submit it as a pull request. :)  It will not happen in this uppcoming 1.1.1 release.

**Comment by carioli** [comment]
Thanks

**Comment by kroeckx** [comment]
This looks very related to #6739

**Comment by FdaSilvaYY** [comment]
@carioli : a good start point for adding extensions : https://github.com/openssl/openssl/pull/2759
