### ISSUE TITLE
OpenSSL 1.1.0-stable Branch Broken?

### ISSUE THREAD

**Issue by alexw91** [openssl/openssl#6839]
The OpenSSL 1.1.0 Stable branch builds are failing:
https://travis-ci.org/openssl/openssl/builds/410827758
https://travis-ci.org/awslabs/s2n/jobs/411023270#L2993

Looks like [this commit](https://github.com/openssl/openssl/commit/24233a0f3c491919ee3a38e2567271ccc041ee1d) is missing `#include "internal/refcount.h"` that was present in the [cherry-picked commit](https://github.com/openssl/openssl/commit/680b9d45b005c2d0a48fd574db903bf4486b49ae#diff-ee7db9eed4b01eb03a13e412c3a0d095R13)?

**Comment by dot-asm** [comment]
Addressed in #6843. Thanks for heads up!
