### ISSUE TITLE
build break: no-deprecated breaks for Windows build

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#684]
The reason is that OPENSSL_config is still in the generated libeay32.def

but in conf.h the function is no longer compiled in:
#if OPENSSL_API_COMPAT < 0x10100000L
void OPENSSL_config(const char *config_name);
...

**Comment by levitte** [comment]
Is that the only one?

**Comment by matbech** [comment]
If you mean the only function, yes. I have temporary removed it from libeay.num and build succeeds.

**Comment by levitte** [comment]
Cool.  I've a fix in, it's pending review.

**Comment by matbech** [comment]
Thanks.

**Comment by levitte** [comment]
c35f5c3d3a557288b6c7dcaa17dbbc5916e3e263
