### ISSUE TITLE
server_certificate_type is optional since TLS 1.3 draft 22

### ISSUE THREAD

**Issue by shawnl** [openssl/openssl#6840]
shawn@scaleway:/root$ openssl s_client -connect 10.66.3.8:5555
`281473378612896:error:1416F09F:SSL routines:tls_process_server_certificate:length mismatch:../ssl/statem/statem_clnt.c:1842:`

when I don't sent a certificate

```CONNECTED(00000003)
281473378612896:error:1416F09F:SSL routines:tls_process_server_certificate:length mismatch:../ssl/statem/statem_clnt.c:1842:
---
no peer certificate available
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 311 bytes and written 656 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_CHACHA20_POLY1305_SHA256
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_CHACHA20_POLY1305_SHA256
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1533166435
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

I'm using picotls on the other side.

see https://tools.ietf.org/html/draft-ietf-tls-tls13-28

I want to use ssh-like-authentication (for distcc), so I don't need certificates.

**Comment by kaduk** [comment]
It might be useful for future readers to note why you closed this.

**Comment by shawnl** [comment]
Because server_certificate_type (to send raw public keys) is a tls extension, rfc 7250, and picotls (and no other library) implements it.

I would like an implementation of raw public keys. Unfortunately because of Debians rules I cannot use openssl with my project to (distcc).

**Comment by richsalz** [comment]
Are you sure about the Debian rules?  @kroeckx is both a debian and openssl committer, so pinging him.

**Comment by shawnl** [comment]
https://lintian.debian.org/tags/possible-gpl-code-linked-with-openssl.html

**Comment by kroeckx** [comment]
Do you mean that even if OpenSSL supported it, you wouldn't be
able to use it because of license issues?

This might change in the future in case it's GPLv3(+), since we
intend to change to the Apache 2 license.

**Comment by shawnl** [comment]
> Do you mean that even if OpenSSL supported it, you wouldn't be able to use it because of license issues? 

Correct.
