### ISSUE TITLE
Feature Request: Support PKCS#11 URI in configuration file

### ISSUE THREAD

**Issue by MatthiasLohr** [openssl/openssl#6842]
Hello,

I'm using a hardware token (YubiKey) for issuing/signing new certificates. Up to now, I have to do it manually by typing ```-engine pkcs11 -keyfile "pkcs11:manufacturer=piv_II;id=%02" -keyform e``` for every command I want to issue with my YubiKey.

It would be great if it is possible to configure that in the openssl.conf file, e.g. using PKCS#11 URIs for CA file/keyfiles etc.

See also: OpenSC/libp11#232

Best regards
Matthias

**Comment by t8m** [comment]
With 3.0.0 and an eventual PKCS11 provider properly configured in the config file it should be simply matter of using proper URI for the keyfile. I am not sure if there is anything else to work on here apart from making a PKCS11 provider.

We will not add any new feature related to engines.
Closing.
