### ISSUE TITLE
openSSL1.1.0h ssl library initialization

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#6845]
Hello!

I'm using openssl1.1.0h with dynamic gost engine. All cryptographic operations are working. However, when I try to use it with libssl library, it disables gost cipher suites, because the config is loaded after cipher suites are registered.

diff -u -N -r openssl-1.1.0h_orig/ssl/ssl_init.c openssl-1.1.0h_debug/ssl/ssl_init.c
--- openssl-1.1.0h_orig/ssl/ssl_init.c	2018-03-27 16:50:40.000000000 +0300
+++ openssl-1.1.0h_debug/ssl/ssl_init.c	2018-08-01 13:36:43.136986459 +0300
@@ -191,13 +191,13 @@
         return 0;
     }
 
-    if (!RUN_ONCE(&ssl_base, ossl_init_ssl_base))
-        return 0;
-
     if (!OPENSSL_init_crypto(opts | OPENSSL_INIT_ADD_ALL_CIPHERS
                              | OPENSSL_INIT_ADD_ALL_DIGESTS, settings))
         return 0;
 
+    if (!RUN_ONCE(&ssl_base, ossl_init_ssl_base))
+        return 0;
+
     if ((opts & OPENSSL_INIT_NO_LOAD_SSL_STRINGS)
         && !RUN_ONCE(&ssl_strings, ossl_init_no_load_ssl_strings))
         return 0;
Best regards,
Yuliya.

**Comment by mattcaswell** [comment]
This is a known issue. See #5809. It was fixed in git by PR #5879. Also see commit 23dec58b9c. It will be fixed in 1.1.0i (no release date as yet).
