### ISSUE TITLE
How do I generate a certificate by function

### ISSUE THREAD

**Issue by liangruxing** [openssl/openssl#6846]
not use command,How do I generate a certificate by function?

**Comment by mattcaswell** [comment]
1) Create an X509 object:
https://www.openssl.org/docs/man1.1.0/crypto/X509_new.html

2) Fill in the various values for your certificate. See the numerous X509* man pages here:
https://www.openssl.org/docs/man1.1.0/crypto/

3) Sign your X509 object with your CA's private key using `X509_sign_ctx()`:
https://www.openssl.org/docs/man1.1.0/crypto/X509_sign_ctx.html

**Comment by liangruxing** [comment]
think you so much

**Comment by liangruxing** [comment]
thank you so much
