### ISSUE TITLE
Ciphertext length is less than 128, RSA public decrypt failure, how do I solve it?

### ISSUE THREAD

**Issue by tigerNongdahu** [openssl/openssl#6847]
my code : 
```
RSA_public_decrypt(inlen,(unsigned char *)instr,(unsigned char*)*outstr,rsa_ctx,RSA_PKCS1_PADDING);
```

Who can help me to solve this problem？
Very urgent ！！！

**Comment by mattcaswell** [comment]
Please can you provide some more information:

1) Provide the exact error message that you have received
2) Please can you explain how the ciphertext was generated

**Comment by tigerNongdahu** [comment]
1. the ciphertext was generated by java, the code:
public static String privateEncrypt(String data, RSAPrivateKey privateKey) {
		try {
			Cipher cipher = Cipher.getInstance("RSA");
			cipher.init(Cipher.ENCRYPT_MODE, privateKey);
			
			return Base64.encodeBase64String(rsaSplitCodec(cipher, Cipher.ENCRYPT_MODE, data.getBytes(CHARSET),
					privateKey.getModulus().bitLength()));
		} catch (Exception e) {
			throw new RuntimeException("[" + data + "]", e);
		}
	}

private static byte[] rsaSplitCodec(Cipher cipher, int opmode, byte[] datas, int keySize) {
		int maxBlock = 0;
		if (opmode == Cipher.DECRYPT_MODE) {
			maxBlock = keySize / 8;
		} else {
			maxBlock = keySize / 8 - 11;
		}
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		int offSet = 0;
		byte[] buff;
		int i = 0;
		try {
			while (datas.length > offSet) {
				if (datas.length - offSet > maxBlock) {
					buff = cipher.doFinal(datas, offSet, maxBlock);
				} else {
					buff = cipher.doFinal(datas, offSet, datas.length - offSet);
				}
				out.write(buff, 0, buff.length);
				i++;
				offSet = i * maxBlock;
			}
		} catch (Exception e) {
			throw new RuntimeException("[" + maxBlock + "]", e);
		}
		byte[] resultDatas = out.toByteArray();
		IOUtils.closeQuietly(out);
		return resultDatas;
	}


2.  First, I use Base64 to translate the ciphertext . Then, use RSA to decrypt，the code:
int rsa_pub_decrypt(char *intstr,char *path_key,int inlen,char** outstr){
    RSA *p_rsa;
    FILE *file;
    int rsa_len,num;
    
    if((file=fopen(path_key,"r"))==NULL){
        perror("open key file error");
        return -1;
    }
    if((p_rsa=PEM_read_RSA_PUBKEY(file,NULL,NULL,NULL))==NULL){
        ERR_print_errors_fp(stdout);
        return -1;
    }
    num = do_operation(p_rsa,intstr,path_key,inlen,outstr,2);
    RSA_free(p_rsa);
    fclose(file);
    return num;
}

static int do_operation(RSA* rsa_ctx,char *instr,char* path_key,int inlen,char** outstr,int type)
{
    if(rsa_ctx == NULL || instr == NULL || path_key == NULL)
    {
        perror("input elems error,please check them!");
        return -1;
    }
    int rsa_len,num = 0;
    rsa_len = RSA_size(rsa_ctx);

    *outstr=(unsigned char *)malloc(rsa_len+1);
    memset(*outstr,0,rsa_len+1);
    switch(type){
        case 1: //pub enc
            if(inlen == 0){
                perror("input str len is zero!");
                goto err;
            }
            num = RSA_public_encrypt(inlen,(unsigned char *)instr,(unsigned char*)*outstr,rsa_ctx,RSA_PKCS1_PADDING);
            printf("\n\nRSA_public_encrypt:%d\n\n",num);
            break;
        case 2: //prv dec
            printf("\n\ninlen lenth:%d\n\n",inlen);
            num = RSA_public_decrypt(inlen,(unsigned char *)instr,(unsigned char*)*outstr,rsa_ctx,RSA_PKCS1_PADDING);
             printf("\n\n RSA_public_decrypt:%d \n\n",num);
            break;
        default:
            break;
    }
    
    if(num == -1)
    {
        printf("Got error on enc/dec!\n");
        perror("enc or dec:");
    err:
        free(*outstr);
        *outstr = NULL;
        num = -1;
    }
    return num;
}

3.  I user perror to print ,i received the error message：
enc or dec: Undefined error:0

how do I solve it?

**Comment by levitte** [comment]
> First, I use Base64 to translate the ciphertext . Then, use RSA to decrypt

Why do you do the base64 translation?

**Comment by tigerNongdahu** [comment]
1. Because Java used base64 to encrypt, so I use Base64  to decrypt.
2.I use ERR_print_errors_fp(stderr), received the error message:
6125989960:error:0407006A:lib(4):func(112):reason(106):rsa_pk1.c:103:
6125989960:error:04067072:lib(4):func(103):reason(114):rsa_eay.c:705:

**Comment by kroeckx** [comment]
Error 106 is: RSA_R_BLOCK_TYPE_IS_NOT_01
Error 114 is: RSA_R_PADDING_CHECK_FAILED

Try calling it with RSA_NO_PADDING?

**Comment by tigerNongdahu** [comment]
I've tried RSA_NO_PADDING, but it doesn't work.

**Comment by kroeckx** [comment]
With RSA_NO_PADDING the decryption should always work, it just
doesn't remove the padding for you. Are you saying you still don't
see what you expect in what is returned?

Are you sure you're using the correct RSA key?

**Comment by tigerNongdahu** [comment]
It can decrypt, but the result is not right. 
use the same public_key.pem, is OK when the ciphertext length is  128 ,but the other lenght is not.

**Comment by levitte** [comment]
What other lengths?

**Comment by kroeckx** [comment]
As the manpage says, for the RSA_NO_PADDING case, the length must
match the RSA size. I guess you should put '\0' bytes in front of
it case the length is not correct.

But you really should look into padding it, it's not secure if
it's not padded.

**Comment by kroeckx** [comment]
I might have misunderstood something. In any case, if it works for
128 bytes, it should work for 127 bytes too. I guess you have
about a 1/256 chance that it's a 127 byte value.
