### ISSUE TITLE
Cryptography differential fuzzer on oss-fuzz

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#6848]
I'll be submitting a cryptography differential fuzzer to oss-fuzz soonish. That means it will compare the output of cryptographic algorithms across different libraries including OpenSSL. Currently it does hashes, hmacs and symmetric encryption and decryption.

I take it you are interested in being included in the CC list to receive crash reports automatically? Shall I use the same CC list as the bignum fuzzer?

Thanks

**Comment by mattcaswell** [comment]
Yes please!!

**Comment by guidovranken** [comment]
Great, thanks :+1:
