### ISSUE TITLE
Status of relicensing?

### ISSUE THREAD

**Issue by qwertychouskie** [openssl/openssl#6850]
What is the current status of re-licensing to Apache 2.0?

**Comment by mattcaswell** [comment]
The work is ongoing. It's going to be some while yet before we can do it. It won't be done in time for our 1.1.1 release.

**Comment by qwertychouskie** [comment]
Could you guys consider releasing a stripped-down version with the Apache 2.0 license?  We (https://github.com/supertuxkart/stk-code/issues/3344) are having some compliance issues that need to be fixed.

**Comment by mattcaswell** [comment]
Unfortunately that would be significant work and almost certainly not viable for us.

**Comment by TechnikEmpire** [comment]
Not sure why this isn't an open issue being tracked.

openSSL has a very problematic license. The status page on the website shows that no one is left to sign off on it. Can this at least be kept open and tracked?
