### ISSUE TITLE
OpenSSL 1.1.0 g compilation issue for ARM in VS2017

### ISSUE THREAD

**Issue by ghanashyams** [openssl/openssl#6856]
I am trying to compile OpenSSL 1.1.0g in windows using VS2017. Provided following to perl commands
perl Configure VC-WIN64A --prefix=C:\tools\openssl no-shared no-dso no-engine no-asm

The above command errors out saying following:
 #error:  Compiling Desktop applications for the ARM platform is not supported.

After googling about this topic I provided following command  to perl
perl Configure VC-WIN32 --prefix=C:\tools\openssl no-shared no-dso no-engine no-asm  -D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE

It compiles successfully, but while linking the lib with target application I get following error:
module machine type 'x64' conflicts with target machine type 'ARM64'

What is the correct perl command to compile Openssl in windows for ARM using VS2017

An early response is appreciated.

Thanks

Ghanashyam

**Comment by dot-asm** [comment]
> What is the correct perl command to compile Openssl in windows for ARM using VS2017

There is none. Windows on ARM is not supported by 1.1.0. Support is being added to 1.1.1, so just use master branch or download pre-release tar-ball.

**Comment by dot-asm** [comment]
Oh! I failed to mention that Configurations/50-win-onecore.conf has some ARM-specific notes.

**Comment by ghanashyams** [comment]
Still same issue I am facing. I used following command:
perl Configure VC-WIN64-ARM --prefix=C:\fold\tools\openssl no-shared no-dso no-engine no-asm -D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE

OpenSSL compiled successfully. But while linking the lib with target application I get following error:
module machine type 'x64' conflicts with target machine type 'ARM64'

**Comment by dot-asm** [comment]
Well, what can I say? VC-WIN64-ARM works for me in sense that nmake succeeds and there 175 ARM64 .exe-s according to `dumpbin /headers`. The rest is really up to you to figure out.

**Comment by ghanashyams** [comment]
Running dumpbin /headers on the generated openssl exe/lib I see following: 
 FILE HEADER VALUES
             1C4 machine (ARM)

However if I compile any source in VS 2017 IDE targeting ARM64 I see following if I run through dumpbin /headers

FILE HEADER VALUES
            AA64 machine (ARM64)

Any idea why the openssl binary/libs coming as  1C4 machine (ARM) ?

**Comment by ghanashyams** [comment]
It seems to be a bug in Openssl for ARM compilation. Though target is defined as below in  Configurations/50-win-onecore.conf for VC-WIN64-ARM , it compiles to target: 1C4 machine (ARM)

"VC-WIN64-ARM" => {
        inherit_from    => [ "VC-noCE-common" ],
        defines         => add("_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE",
                               "OPENSSL_SYS_WIN_CORE"),
        bn_ops          => "SIXTY_FOUR_BIT RC4_CHAR EXPORT_VAR_AS_FN",
        lflags          => add("/NODEFAULTLIB:kernel32.lib"),
        ex_libs         => "onecore.lib",
        multilib        => "-arm64",
    },

**Comment by ghanashyams** [comment]
It seems ARM64 through cmdline is not getting effected in VS2017.  It errors out as below if amd64_arm64 is provided as command param to vcvarsall.bat.

amd64_arm is getting effected where target binary is ARM. So how did u generate ARM64 binary for OpenSSL in windows?


C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>**vcvarsall.bat amd64_arm64**
Error in script usage. The correct usage is:
    vcvarsall.bat [option]
  or
    vcvarsall.bat [option] store
  or
    vcvarsall.bat [option] [version number]
  or
    vcvarsall.bat [option] store [version number]
where [option] is: x86 | amd64 | arm | x86_amd64 | x86_arm | amd64_x86 | amd64_arm
where [version number] is either the full Windows 10 SDK version number or "8.1" to use the windows 8.1 SDK
:
The store parameter sets environment variables to support
  store (rather than desktop) development.
:
For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_arm store
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm store 10.0.10240.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1
:
Please make sure either Visual Studio or C++ Build SKU is installed.

**Comment by dot-asm** [comment]
I have vcvarsamd64_arm64.bat and I just execute it [without ever looking what's inside]. After which cl represents itself as `Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for ARM64`.

**Comment by ghanashyams** [comment]
Yeah it seems vcvarsamd64_arm64.bat is located under C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build, which i need to use to make ARM64 build.

**Comment by ghanashyams** [comment]
Yes I could generate ARM64 build for OpenSSL 1.1.1 using C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat. And my application also compiles and links fine using the generated ARM64 lib of OpenSSL.

Thanks

**Comment by besti4ok** [comment]
всем привет.
делаюю файл сборки 
perl Configure VC-WIN64A no-shared no-asm
создает пустой файл makefile.new
запускаю команду nmake получаю ошибку
NMAKE : fatal error U1064: MAKEFILE не найден и конечный файл не задан
Stop.
