### ISSUE TITLE
tests: evp_test succeeds after "SM2 tests" report a fake error

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#6857]
Noticed while testing 2c826cbe2c35237fafb78af8d5ef0e7b1542c334, which is part of #6854.

To reproduce the problem, checkout and build 2c826cbe2c35237fafb78af8d5ef0e7b1542c334, then run

```
 ./util/shlib_wrap.sh test/evp_test test/recipes/30-test_evp_data/evppkey.txt
```
 
The tail of the test output is:

```
    ...
    # Starting "SM2 tests" tests at line 18402
    # ERROR: (memory) 'expected->output == got' failed @ test/evp_test.c:1111
    # --- expected->output
    # +++ got
    # 0000:-3045022100f11bf3 6e75bb304f094fb4 2a4ca22377d0cc76 8637c5011cd59fb9
    # 0000:+3045022061fa912d d72fff1aebf4857a 77189bdf25c2ae63 fe6d530e7878d89d
    #             ^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
    # 0020:-ed4b130c98022035 545ffe2c2efb3abe e4fee661468946d8 86004fae8ea53115
    # 0020:+570505b602210099 be0398f934a02cc6 d47cf774e44294ad b35c6741ad81693c
    #       ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
    # 0040:-93e48f7fe21b91
    # 0040:+a14caef35d5af2
    #       ^^^^^^^^^^^^^^
    #
    # INFO:  @ test/testutil/stanza.c:121
    # Starting "Chosen Wycheproof vectors" tests at line 18440
    # INFO:  @ test/testutil/stanza.c:33
    # Completed 1442 tests with 0 errors and 0 skipped
    ok 1 - test/recipes/30-test_evp_data/evppkey.txt
ok 1 - run_file_tests
```

**Comment by romen** [comment]
The console output is misleading: that test expects a mismatch so it is passing.

**Comment by mspncp** [comment]
Thanks @romen for the information. If this is the case, is there a way to make the output more clear for innocent bystanders?

Also, there is a contradiction with @kroeckx: After cherry-picking his commit https://github.com/kroeckx/openssl/commit/124b577b97847b61f7bae9e8afbd663ba5994629 the test fails again:

```
msp@msppc:~/src/openssl$ ./util/shlib_wrap.sh test/evp_test test/recipes/30-test_evp_data/evppkey.txt
1..1
    # Subtest: run_file_tests
    1..1
    # INFO:  @ test/testutil/stanza.c:21
    # Reading test/recipes/30-test_evp_data/evppkey.txt
    # INFO:  @ test/testutil/stanza.c:121
    # Starting "RSA tests" tests at line 131
    # INFO:  @ test/evp_test.c:2341
    # test/recipes/30-test_evp_data/evppkey.txt:149 Verify error
    # INFO:  @ test/testutil/stanza.c:33
    # Completed 8 tests with 1 errors and 0 skipped
    not ok 1 - test/recipes/30-test_evp_data/evppkey.txt
not ok 1 - run_file_tests
```

**Comment by mspncp** [comment]
Kann ich machen. Du fährst wohl direkt hin?

**Comment by mspncp** [comment]
UPS sorry, this was intended for WhatsApp 😂

**Comment by kroeckx** [comment]
My commit didn't make sense, it returned errors when a test was supposed to fail.

**Comment by kroeckx** [comment]
A different test that might also confuse you is:
```
        # ERROR: (ptr) 'got = OPENSSL_malloc(got_len) != NULL' failed @ test/evp_test.c:1682
```

I'm not sure there is anything to fix. Those test, when they fail, give you useful debug output. When they're expected to fail show you things you don't care about and might confuse you. I guess we could complicate the code by not using the TEST_mem_eq function in case we expect it to fail.

**Comment by mspncp** [comment]
> I guess we could complicate the code by not using the TEST_mem_eq function in case we expect it to fail.

Why do you think this makes it more complicate? On the contrary, a test should always test for the condition it expects to see. In this case, using `TEST_mem_ne()` instead of `TEST_mem_eq()` would have the desired effect: The test is silent when there is a discrepancy and complains if there is none.

**Comment by mspncp** [comment]
I reformulated the title to change the current focus of this issue: IMHO it is confusing that an ERROR is reported for the discrepancy although it is expected. Without having looked into details, my wild guess is that replacing `TEST_mem_eq()` by  `!TEST_mem_ne()` would silence this fake error message.

**Comment by mspncp** [comment]
So what do you two prefer? That I close this issue or leave it open as incentive for the future? ;-)

**Comment by richsalz** [comment]
Look at ```expected_err``` in evp_test Put a "Result=..." in the testcase.

**Comment by paulidale** [comment]
Would adding a `TEST_note` indicating that the error was expected help?

**Comment by paulidale** [comment]
It might be a bit dodgy but it would be possible to add a global _failure is expected_ flag to the test framework which suppresses the error reporting.

I'm not at all sure I like the idea though.

**Comment by mattcaswell** [comment]
Is anything more needed for this, or can it be closed?

**Comment by mspncp** [comment]
This issue was resolved by #6899, which has been merged to 4cceb185b137a0b0c57c226a76542ab2c5e4e251.

**Comment by mspncp** [comment]
Funny, I was already writing this when your question came.

**Comment by mspncp** [comment]
Too many coincidences 😉 ...
