### ISSUE TITLE
Parsing of EDIPARTYNAME is incorrect

### ISSUE THREAD

**Issue by filipnavara** [openssl/openssl#6859]
As part of https://github.com/dotnet/corefx/pull/31579 I discovered that OpenSSL has wrong ASN definition for EdiPartyName (https://tools.ietf.org/html/rfc5280#section-4.2.1.6):

```
ASN1_SEQUENCE(EDIPARTYNAME) = {
        ASN1_IMP_OPT(EDIPARTYNAME, nameAssigner, DIRECTORYSTRING, 0),
        ASN1_IMP_OPT(EDIPARTYNAME, partyName, DIRECTORYSTRING, 1)
} ASN1_SEQUENCE_END(EDIPARTYNAME)
```

First, the `partyName` is not optional:

>   EDIPartyName ::= SEQUENCE {
>        nameAssigner            [0]     DirectoryString OPTIONAL,
>        partyName               [1]     DirectoryString }

Second, DIRECTORYSTRING is a choice, so it should be `_EXP`, not `_IMP` because of X.680-2015 31.2.7 (c):

> 31.2.7 The tagging construction specifies explicit tagging if any of the following holds:
> a) the "Tag EXPLICIT Type" alternative is used;
> b) the "Tag Type" alternative is used and the value of "TagDefault" for the module is either EXPLICIT TAGS or is empty;
> c) the "Tag Type" alternative is used and the value of "TagDefault" for the module is IMPLICIT TAGS or AUTOMATIC TAGS, but the type defined by "Type" is an untagged choice type, an untagged open type, or an untagged "DummyReference" (see Rec. ITU-T X.683 | ISO/IEC 8824-4, 8.3).

Test data are available in the linked pull request.

/cc @davidben, BoringSSL is affected as well.

**Comment by richsalz** [comment]
Can you explain why https://www.openssl.org/docs/faq.html#PROG6 does not apply?

**Comment by filipnavara** [comment]
I am not questioning the definition of GeneralName itself:

```
ASN1_CHOICE(GENERAL_NAME) = {
        ASN1_IMP(GENERAL_NAME, d.otherName, OTHERNAME, GEN_OTHERNAME),
        ASN1_IMP(GENERAL_NAME, d.rfc822Name, ASN1_IA5STRING, GEN_EMAIL),
        ASN1_IMP(GENERAL_NAME, d.dNSName, ASN1_IA5STRING, GEN_DNS),
        /* Don't decode this */
        ASN1_IMP(GENERAL_NAME, d.x400Address, ASN1_SEQUENCE, GEN_X400),
        /* X509_NAME is a CHOICE type so use EXPLICIT */
        ASN1_EXP(GENERAL_NAME, d.directoryName, X509_NAME, GEN_DIRNAME),
        ASN1_IMP(GENERAL_NAME, d.ediPartyName, EDIPARTYNAME, GEN_EDIPARTY),
        ASN1_IMP(GENERAL_NAME, d.uniformResourceIdentifier, ASN1_IA5STRING, GEN_URI),
        ASN1_IMP(GENERAL_NAME, d.iPAddress, ASN1_OCTET_STRING, GEN_IPADD),
        ASN1_IMP(GENERAL_NAME, d.registeredID, ASN1_OBJECT, GEN_RID)
} ASN1_CHOICE_END(GENERAL_NAME)
```

The same rule that makes X509_NAME explicit applies to the members of EdiPartyName too.

**Comment by filipnavara** [comment]
Note that NSS (Mozilla) had the same bug 15 years ago - https://bugzilla.mozilla.org/show_bug.cgi?id=233586

**Comment by filipnavara** [comment]
Test data: `300EA50CA10A13086564695061727479` (content of Subject Alternative Name extension)
Visual representation: https://lapo.it/asn1js/#300EA50CA10A13086564695061727479

**Comment by bbernier** [comment]
Hello,

I have run into the same issue. This is causing openssl invalid parsing on valid asn1 defined in https://tools.ietf.org/html/rfc5280#section-4.2.1.6 for EDIPartyName

EDIPartyName ::= SEQUENCE {
        nameAssigner            [0]     DirectoryString OPTIONAL,
        partyName               [1]     DirectoryString }

Has there been any update on this?
