### ISSUE TITLE
FIPS 2.0.11 build with Visual Studio 2010 fails self-tests 

### ISSUE THREAD

**Issue by Aaron-1688** [openssl/openssl#6863]
Hello, 

I hit the exactly the same FIPS link issue as the one reported here - http://openssl.6102.n7.nabble.com/FIPS-Module-1-2-build-with-Visual-Studio-2010-fails-self-tests-tt36372.html#a36391

A solution was posted here - http://openssl.6102.n7.nabble.com/FIPS-Module-1-2-build-with-Visual-Studio-2010-fails-self-tests-td36372.html
>On Mon, Apr 16, 2012, Vimol Kshetrimayum wrote: 
>> It is still not working for me. I had tried all possible place to add 
>> /dynamicbase:NO and/or /fixed flag. 
>> 
>> I am wondering how it was working for Grant Averett. 
>> Where did you exactly add the /FIXED flag? 
>> 
>That's weird. I can reproduce that issue with my setup and this fixes it: 
>http://cvs.openssl.org/chngview?cn=22392
>
>Steve. 
>-- 
>Dr Stephen N. Henson. OpenSSL project core developer. 
>Commercial tech support now available see: http://www.openssl.org

However, the link is not accessible - http://cvs.openssl.org/chngview?cn=22392

Anyone knows how to retrieve it?

Thanks in advance, 
Aaron

**Comment by t-j-h** [comment]
I would guess that is e4588dc486b947cf243b64ceab31acb637d40233

**Comment by Aaron-1688** [comment]
Thanks so much, Tim.

Adding linker option /fixed works for me.

Aaron

**Comment by t-j-h** [comment]
You're welcome. Marking issue closed.
