### ISSUE TITLE
ssl3_write_pending:bad write retry

### ISSUE THREAD

**Issue by tokers** [openssl/openssl#6865]
Hello!

We found this some logs in our error.log:

```
2018/08/06 12:00:19 [crit] 3933468#3933468: *1495878 SSL_shutdown() failed (SSL: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry) while closing request, client: 116.24.83.186, server: 0.0.0.0:443
2018/08/06 12:00:19 [crit] 3933475#3933475: *1497036 SSL_shutdown() failed (SSL: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry) while closing request, client: 124.227.106.252, server: 0.0.0.0:443
2018/08/06 12:00:20 [crit] 3933468#3933468: *1497300 SSL_shutdown() failed (SSL: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry) while closing request, client: 116.24.83.186, server: 0.0.0.0:443
```

It seems strange, I want to know which circumstance may results in this problem and is this problem hurts the connection?

By the way, we are using the Intel QAT service and enable the `SSL_MODE_ASYNC`, our OpenSSL version is `1.1.1-pre2`.

Best Regards
Alex Zhang

**Comment by kroeckx** [comment]
I'm wondering what we do in case SSL_shutdown() returns -1, do we
properly call it with the same pointer ourself?

**Comment by kroeckx** [comment]
On Mon, Aug 06, 2018 at 02:52:49AM -0700, Kurt Roeckx wrote:
> I'm wondering what we do in case SSL_shutdown() returns -1, do we
> properly call it with the same pointer ourself?

So we have a special buffer for that in the SSL struct, so that
seems fine.

**Comment by mattcaswell** [comment]
> It's too weird, I found the last action also is the SSL_shutdown rather than SSL_write, and it returns SSL_ERROR_WANT_WRITE, so the SSL_shutdown is called again after a while (notified by the epoll), then this log is print.

Interesting. That sounds like a potential OpenSSL bug. I'd need to investigate further (although there are other priorities at the moment so it may take me a while).

**Comment by tokers** [comment]
@mattcaswell 
Thanks a lot!

I'm looking forward to the result for your survey :), before that, I will hack our service to just give up sending the `close_notify` alert in this situation.

**Comment by kroeckx** [comment]
Are you sure the last SSL_write also didn't return SSL_ERROR_WANT_WRITE?

**Comment by tokers** [comment]
@kroeckx 

> Are you sure the last SSL_write also didn't return SSL_ERROR_WANT_WRITE?

What I can ensure is that the last action is SSL_shutdown, I'm not sure whether SSL_shutdown before the last SSL_shutdown() call returns SSL_ERROR_WANT_WRITE.

**Comment by tokers** [comment]
@mattcaswell @kroeckx 
I will try to reproduce this problem in a testable environment (this problem occurs only in our product environment), and also check our own codes. :)

**Comment by nzt4567** [comment]
I can confirm we are seeing this as well, using unpatched https://github.com/intel/asynch_mode_nginx and OpenSSL 1.1.0h or 1.1.0i. Unfortunately, nginx dies with `SSL_CTX_new() failed (SSL:)` during config parsing if linked to OpenSSL 1.1.1 so I can't really test that version.

**Comment by p01arbear** [comment]
Most likely it's https://trac.nginx.org/nginx/ticket/1194 which was fixed by https://github.com/intel/asynch_mode_nginx/commit/a28ac19083e58ec98849279b55c7917d6d08c381

**Comment by t8m** [comment]
@tokers Is this problem still relevant for you? If not, please close.

**Comment by tokers** [comment]
@t8m OK.
