### ISSUE TITLE
Compilation of openssl failing showing error “no rule to make target 'jnix/jniglue.c'”

### ISSUE THREAD

**Issue by Sammy-iiitb** [openssl/openssl#6869]
I am trying to compile openssl using ndk-build on an linux machine and earlier compilation failed saying that "aes.h" file was missing for resolving that I installed libssl-dev package and that worked and installation moved for some more steps and failed on this.

> make: *** No rule to make target 'jnix/jniglue.c', needed by 'obj/local/armeabi-v7a/objs/opvpnutil/jniglue.o'. Stop.

In this there is so such path exists and I doubt I have to install some package again to fix this issue.

**Comment by levitte** [comment]
That's not part of OpenSSL...
