### ISSUE TITLE
About 1.0.2p version release !!

### ISSUE THREAD

**Issue by hareesh1git** [openssl/openssl#6871]
Hi,

Can you please tell when is the official release of 1.0.2p version.

Thanks !!

**Comment by mspncp** [comment]
As far as I know, the there is no official release plan for service releases. Most often, a new release is triggered when some important security bug was reported, which needs to be fixed. These service releases are then announced a few days in advance on the openssl-announce and openssl-users mailing list. 

Why do you need the 1.0.2p release in the first place? Does it contain a bugfix which you need and which is not present in 1.0.2o yet? Do you intend to compile OpenSSL yourself or are you using the OpenSSL version of your linux distribution?

If you are using the preinstalled openssl from your distribution, then please note that it may take a while after a new OpenSSL release until that release becomes available in your distribution.

If you intend to compile the source yourself, then you can just clone the git repository and switch to the OpenSSL_1_0_2-stable branch, or alternatively download a [daily snapshot](https://www.openssl.org/source/snapshot).

Hope that helps.
