### ISSUE TITLE
TLS_CT_NUMBER is incorrect

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#6873]
TLS_CT_NUMBER which is defined in tls1.h is equal to 9, but there are 10 different signatures defined above.

**Comment by richsalz** [comment]
Thanks.  Please see #6874

**Comment by richsalz** [comment]
Thanks.  Please see #6874

**Comment by richsalz** [comment]
Fixed in master and 1.1.0.  Thanks for the report!
