### ISSUE TITLE
not able to Compile && make openssl with ndk17b --> Oscam (binary for Android) 

### ISSUE THREAD

**Issue by Screamfox** [openssl/openssl#6879]
Hi, @Devs 

I have some issue when i try to compile the openssl with the android tools-chain,

before i have received this issue reported here [#3826](https://github.com/openssl/openssl/issues/3826) 

complaining with 

```
...
/libcrypto.so: error: undefined reference to 'stderr'
./libcrypto.so: error: undefined reference to 'stdin'
./libcrypto.so: error: undefined reference to 'signal'
./libcrypto.so: error: undefined reference to 'tcsetattr'
./libcrypto.so: error: undefined reference to 'tcgetattr'
...
```

So i tried this 

>@nurupo Well, as a workaround, you could replace the gcc binary with a bash script file named gcc which calls clang instead.
>
>e.g. save
>
>#!/bin/sh
>$ANDROID_TOOLCHAIN_DIR/arm-linux-androideabi-clang "$@"
>as $ANDROID_TOOLCHAIN_DIR/arm-linux-androideabi-gcc, overwriting the original gcc.
>
>If using clang doesn't work because openssl detects that it's clang and tries to use the unsupported ->mandroid, then try copying gcc to gcc-original and saving
>
>#!/bin/sh
>$ANDROID_TOOLCHAIN_DIR/arm-linux-androideabi-gcc-original -D__ANDROID_API__=$API "$@"
>as gcc. Don't forget to set $API.
>

### and i get this

```
/android-toolchain/bin/arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/android-toolchain/sysroot/usr/ssl\"" -DENGINESDIR="\"/android-toolchain/sysroot/usr/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot= -Wa,--noexecstack  --deprecated-headers -fPIC -DOPENSSL_USE_NODELETE -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c
/bin/sh: 1: /android-toolchain/bin/arm-linux-androideabi-gcc: Text file busy
Makefile:644: recipe for target 'crypto/aes/aes_cbc.o' failed
make[1]: *** [crypto/aes/aes_cbc.o] Error 2
make[1]: Leaving directory '/openssl-1.1.0h'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

So i tried many other things and i don't have more ideas some help ?

rgds

EDIT

Just in case if this help you to know what tutorial i'm following the tutorial i'm following is this tutorial [http://www.streamboard.tv/oscam/wiki/crosscompiling#android](http://www.streamboard.tv/oscam/wiki/crosscompiling#android)

in the tutorial above the openssl is really old version 1.0.1o so i would like to install the latest 1.1.1-pre9dev with the android toolchain

**Comment by nurupo** [comment]
Try to build openssl using the clang android toolchain, not the gcc, that's what worked for me.

**Comment by Screamfox** [comment]
@nurupo 

Thank you to reply me :)

i have a problem since something is missing here, but the right question is what ? :)

when i build the toolchain i build in standalone like this

for gcc version <-- well so this is the wrong method apparently 

`./make_standalone_toolchain.py --arc arm --api 21 --install-dir /android-toolchain/`

for clang version <--- new method to build toolchain to build and to be ok for openssl :) 

`./make-standalone-toolchain.sh --arch=arm --platform=android-21 --install-dir=/android-toolchain --toolchain=arm-linux-android-clang3.6´

i think here there are something missing below...

commands typed
```
export ANDROID_NDK=/android-ndk-r16b/
export PATH=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin:$PATH<-- i think something is wrong somewhere here but... i don't know
export CXX=/android-toolchain/bin/arm-linux-androideabi-clang++
export CC=/android-toolchain/bin/arm-linux-androideabi-clang 
export RANLIB=/android-toolchain/bin/arm-linux-androideabi-ranlib
export ANDROID_NDK=/android-ndk-r16b/
./Configure --prefix=/android-toolchain/sysroot/usr android -D__ANDROID_API__=21
``` 

 and i get something like this
```
Configuring OpenSSL version 1.1.1-pre9-dev (0x10101009L) for android
Using os-specific seed configuration
no sysroot=/android-ndk-r16b//platforms/android-21/arch- at (eval 7) line 62.
```

so do you now how i say the arch is ?? i know something is missing but the right question is what ? :s 

Just a other once question if i use gcc after to cross compile my C++ source code to build the binary for Android it's work same as Clang ?

**Comment by dot-asm** [comment]
'android' is a template, which means that it's not supposed to be used as argument to Configure(*). You should use one of targets listed in NOTES.ANDROID. As for setting CC and RANLIB variables. Nobody can prevent you from trying things that come to mind, but recommended/supported way to use clang is depicted in NOTES.ANDROID. Which says "One can engage clang by adjusting PATH to cover NDK's clang. ..."

(*) This asks for question if Configure should reject attempt to use template as target. I thought that it would, but apparently not...

**Comment by levitte** [comment]
> This asks for question if Configure should reject attempt to use template as target. I thought that it would, but apparently not...

It does, but *after* trying to resolve all the inheritances, which means that any function reference embedded in the configs will be executed before the template marker is checked...  Fix coming up.

**Comment by levitte** [comment]
See #6885

**Comment by AZBoxEmperador** [comment]
This is the lines of codes I use and I also ge some erros, 

`sudo apt-get update
sudo apt-get install subversion
wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
unzip android-ndk-r13b-linux-x86_64.zip
cd android-ndk-r13b/build/tools
export TOOLCHAIN=/android-toolchain
./make_standalone_toolchain.py --arch arm --api 24 --install-dir /android-toolchain
wget http://www.openssl.org/source/openssl-1.0.1g.tar.gz
tar -xf openssl-1.0.1g.tar.gz
cd openssl-1.0.1g
export CC=$TOOLCHAIN/bin/arm-linux-androideabi-gcc
export RANLIB=$TOOLCHAIN/bin/arm-linux-androideabi-ranlib
./Configure --prefix=$TOOLCHAIN/sysroot/usr android
make
make install_sw
svn checkout http://www.streamboard.tv/svn/oscam/trunk oscam-svn
wget https://github.com/oscam-emu/oscam-emu/raw/master/oscam-emu.patch
cd oscam-svn
patch -p0 < ../oscam-emu.patch
./config.sh --enable WEBIF WITH_SSL IPV6SUPPORT
make static EXTRA_FLAGS="-pie" LIB_RT= LIB_PTHREAD= CROSS=/android-toolchain/bin/arm-linux-androideabi-`

these are the errors I get:

`HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 439528 template bytes into 178106 bytes. 261422 saved bytes (59.48%).
/bin/sh: 1: /android-toolchain/bin/arm-linux-androideabi-gcc: not found
make[2]: /android-toolchain/bin/arm-linux-androideabi-gcc: Command not found
Makefile:443: recipe for target 'build/-ssl-static/cscrypt/des.o' failed
make[2]: *** [build/-ssl-static/cscrypt/des.o] Error 127
Makefile:395: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile.extra:263: recipe for target 'static' failed
make: *** [static] Error 2
root@edwin-VirtualBox:~# 

`

**Comment by Screamfox** [comment]
@AZBoxEmperador 

This is something wrong probably with the path where you have "installed" the toolchain check the path 

Rgds
