### ISSUE TITLE
Build failed when upgrade openssl from 1.0.x to 1.1.0g

### ISSUE THREAD

**Issue by NanFeng009** [openssl/openssl#6884]
on ubuntu 18.04, i build my project with openssl, and got this error.
`error: invalid use of incomplete type ‘OCSP_BASICRESP {aka struct ocsp_basic_response_st}’
   retVal = OCSP_BASICRESP_sign(basic_resp, pkey, dgst, 0);`
`/usr/include/openssl/ocsp.h:110:16: note: forward declaration of ‘OCSP_BASICRESP {aka struct ocsp_basic_response_st}’
 typedef struct ocsp_basic_response_st OCSP_BASICRESP;`
 I found that ocsp_basic_response_st is defined in the crypto/oscp/oscp_lcl.h header file which is part of the openssl package, but is not public.
Is that is an issue?

**Comment by richsalz** [comment]
In the 1.1.0 release, we made many datatypes opaque.  You no longer have direct access, you must use pointers.  Closing this issue.

**Comment by NanFeng009** [comment]
@richsalz 
actually, i used the pointer, and i used the macro `OCSP_REQUEST_sign` whichi defined in ocsp.h. in there it try to direct access.

**Comment by NanFeng009** [comment]
in the master branch, i found the `OCSP_BASICRESP_sign` was in ocsp_lcl.h file instead of ocsp.h file. but after searched the whole openssl code, there was no code reference `OCSP_BASICRESP_sign`. it seems useless, am i right? why not remove it? or it is an issue?
