### ISSUE TITLE
README Reference to Notification Requirements for the Export Controls TSU 

### ISSUE THREAD

**Issue by collina** [openssl/openssl#69]
The information within the README on notification requirements for export controls on encryption is likely out of date and potentially unnecessarily burdensome. For one, the link provided for BIS on the TSU no longer works, but the notification requirements have probably changed since this was written. OpenSSL could probably resolve this matter through emailing the BIS and NSA addresses a link to this repository. Otherwise, the maintainers are responsible for notifying BIS of every update to OpenSSL. It may be useful to consult the regulations again:

> (3) Notification requirement. You must notify BIS and the ENC Encryption Request  Coordinator via e-mail of the Internet location (e.g., URL or Internet address) of the publicly available encryption source code or provide each of them a copy of the publicly available encryption source code. If you update or modify the source code, you must also provide additional copies to each of them each time the cryptographic functionality of the source code is updated or modified. In addition, if you posted the source code on the Internet, you must notify BIS and the ENC Encryption Request Coordinator each time the Internet location is changed, but you are not required to notify them of updates or modifications made to the encryption source code at the previously notified location. In all instances, submit the notification or copy to crypt@bis.doc.gov and to enc@nsa.gov.

http://www.ecfr.gov/cgi-bin/text-idx?c=ecfr&sid=68098bc2e5baf66160cb14b37313c68f&rgn=div8&view=text&node=15:2.1.3.4.25.0.1.13&idno=15

**Comment by richsalz** [comment]
We addressed this issue, although we said "figure it out"
