### ISSUE TITLE
EOL regression on cygwin

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#6903]
When I have access to cygwin environment I did tests on PKIX-SSH functionality. Last time I did test against openssl master branch (about 2 weeks old clone). One of tests fail as X5.09 client certificate was not accepted verification fail. 
Failure is that hash command (see "https://gitlab.com/secsh/pkixssh/blob/master/tests/CA/test-dn_auth_path.sh.inc#L32") does not return correct(expected) result. Output of command ends with both CR LF as result CR character is encoded into file name and "hash directory" stop to work.

Further test shows that other commands are also impacted. For instance x509 command output certificate with \<CR\>\<LF\> as EOL.
Review of code in apps.c shows a lot of lines like this "https://github.com/openssl/openssl/blob/master/apps/apps.c#L2452" .
This is not correct form functional point of view. The fact that format is TEXT does not mean that system has to use "TEXT" file mode. Function modestr() is also impacted.

On cygwin is used UNIX EOL convention. System openssh version output correctly only \<LF\> as EOL .

Another point is that name of function istext() is ambiguous. PEM is "text" format but use like this "textmode = istext(format);" is not correct as "file text mode" != "text format".

**Comment by mattcaswell** [comment]
The code you point to in apps hasn't changed for several years. Are you sure this is a regression? What OpenSSL version has this previously worked with?

**Comment by petrovr** [comment]
mattcaswell wrote:
> The code you point to in apps hasn't changed for several years. Are you sure this is a regression? What OpenSSL version has this previously worked with?
> 

Works fine with 1.0.2 (system package).
"several years" for what? Logic text file => text file mode does not 
exist in 1.0.2. I found it in 1.1.0_stable as well . So regression is 
for 1.1.0*.

Regards,
Roumen Petrov

**Comment by mattcaswell** [comment]
The apps code was changed by commit a60994df34f in 2015. Looks like that commit is not in 1.0.2.

Ping @levitte.

**Comment by levitte** [comment]
I think this needs some deeper analysis.  To say that we should use text mode when outputing text is plain wrong in my mind.  However, if we somehow do not follow the Cygwin EOL convention, then we're doing something wrong with textmode settings on that system.

The two places that are affected by `BIO_FP_TEXT` specifically on Cygwin are [here](https://github.com/openssl/openssl/blob/master/crypto/bio/bss_file.c#L254-L260) and [here](https://github.com/openssl/openssl/blob/master/crypto/bio/bss_file.c#L282-L288).  So the question is, do we make the wrong `setmode` call, or does it interact in weird ways with Cygwin?  Same question about the `b` and `t` mode letters to `fopen`...

**Comment by petrovr** [comment]
Richard Levitte wrote:
> I think this needs some deeper analysis.  To say that we should use text mode when outputing text is plain wrong in my mind.  However, if we somehow do not follow the Cygwin EOL convention, then we're doing something wrong with textmode settings on that system.
> 
> The two places that are affected by `BIO_FP_TEXT` specifically on Cygwin are [here](https://github.com/openssl/openssl/blob/master/crypto/bio/bss_file.c#L254-L260) and [here](https://github.com/openssl/openssl/blob/master/crypto/bio/bss_file.c#L282-L288).  So the question is, do we make the wrong `setmode` call, or does it interact in weird ways with Cygwin?  Same question about the `b` and `t` mode letters to `fopen`...
> 

I think that BIO module process BIO_FP_TEXT flag properly - it sets mode 
to ..O_TEXT/..O_BINARY accordingly. Same for "b" vs "t" flag for file 
streams.

Issue is at "application" level - when to use(set) BIO_FP_TEXT.

Regards,
Roumen Petrov

**Comment by levitte** [comment]
I think we disagree. I think that when the output to a file (or stdout) is expected to be text, that file should be set to text mode. Anything else simply doesn't make sense. If we end up outputting incorrect EOL for the platform, then that's where the issue is.

**Comment by petrovr** [comment]
pkix-ssh has work-around on this.
Definitely we will not agree on the way how to use text(print) streams vs end-of-line convention.
