### ISSUE TITLE
How can a client write and shutdown TLS 1.3 so that server reads the sent data?

### ISSUE THREAD

**Issue by ppisar** [openssl/openssl#6904]
While debugging https://rt.cpan.org/Public/Bug/Display.html?id=125218 and https://github.com/openssl/openssl/issues/5637 I came to a point were either I cannot use OpenSSL properly or there is something fishy in the OpenSSL-1.1.1-pre8.

A client does:

SSL_connect()
SSL_write()
SSL_shutdown()
shutdown(SHUT_RDWR)

A server does:

SSL_accept()
SSL_read()

The code works with OpenSSL-1.1.0h, the server receives all deciphered data without reporting any error:

~~~
$ openssl version
OpenSSL 1.1.0h-fips  27 Mar 2018
$ ./a.out 
Client
Server
TCP connected.
TCP accepted.
SSL accepted.
SSL connected.
Client SSL_write returned 6
Client write finished.
Client shut down TLS session.
Client shut down TCP.
Server SSL_read returned 6
text
Server SSL_read returned 0
Server thinks a client closed a TLS session
Server read finished.
Server process terminated normally with 0 exit code
~~~

If I run the code with OpenSSL-1.1.1-pre8 that uses TLS 1.3, SSL_accept() fails on SIGPIPE:

~~~
$ openssl version
OpenSSL 1.1.1-pre8 (beta) FIPS 20 Jun 2018
$ ./a.out 
Client
TCP connected.
Server
TCP accepted.
SSL connected.
Client SSL_write returned 6
Client write finished.
Client shut down TLS session.
Client shut down TCP.
Server reveived 13 signal
SSL_accept failed: 
Server process terminated normally with 1 exit code
~~~

Here is the code, certificate in ./cert.pem file  and private key in ./cert.key are not included:

~~~
#define _POSIX_C_SOURCE 1
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <signal.h>
#include <errno.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <signal.h>

void handler(int signal) {
    fprintf(stderr, "Server reveived %d signal\n", signal);
}

int main(int argc, char **argv) {
    pid_t server_pid;
    int wstatus;
    int server_socket, client_socket;
    int true = 1;
    struct sockaddr_in6 addr = {
        .sin6_family = AF_INET6,
        .sin6_port = 2000,
        .sin6_flowinfo = 0,
        .sin6_addr = IN6ADDR_LOOPBACK_INIT
    };
    const char message[] = "text\n";
    int processed;
    SSL_CTX *ssl_ctx;
    SSL *ssl;
    int retval;

    server_socket= socket(AF_INET6, SOCK_STREAM, 0);
    if (server_socket < 0) {
        perror("socket failed");
        exit(EXIT_FAILURE);
    }
    if (setsockopt(server_socket, SOL_SOCKET, SO_REUSEADDR, &true, sizeof(true))) {
        perror("setcockopt failed\n");
        exit(EXIT_FAILURE);
    }
    if (bind(server_socket, (const struct sockaddr *)&addr, sizeof(addr))) {
        perror("bind failed");
        exit(EXIT_FAILURE);
    }
    if (listen(server_socket, 1)) {
        perror("liste failed");
        exit(EXIT_FAILURE);
    }

    server_pid = fork();
    if (server_pid < 0) {
        perror("fork failed");
        exit(EXIT_FAILURE);
    } else if (server_pid == 0) {
        /* Server */
        int fd;
        char buffer[1024];
        struct sigaction action;
        sigset_t sigset;

        printf("Server\n");

        sigemptyset(&sigset);
        action.sa_handler = handler;
        action.sa_flags = 0;
        action.sa_mask = sigset;
        sigaction(SIGPIPE, &action, NULL);

        fd = accept(server_socket, NULL, 0);
        if (fd < 0) {
            perror("accept failed");
            exit(EXIT_FAILURE);
        }
        printf("TCP accepted.\n");

        /*if (!OPENSSL_init_ssl(0, NULL)) {
            fprintf(stderr, "OPENSSL_init_ssl failed\n");
            exit(EXIT_FAILURE);
        }*/
        /*OpenSSL_add_ssl_algorithms();*/
        ssl_ctx = SSL_CTX_new(TLS_server_method());
        if (!ssl_ctx) {
            fprintf(stderr, "SSL_CTX_new failed\n");
            exit(EXIT_FAILURE);
        }
        if (1 != SSL_CTX_use_PrivateKey_file(ssl_ctx, "key.pem", SSL_FILETYPE_PEM)) {
            fprintf(stderr, "SSL_CTX_use_PrivatKey_file failed: ");
            ERR_print_errors_fp(stderr);
            exit(EXIT_FAILURE);
        }
        if (1 != SSL_CTX_use_certificate_file(ssl_ctx, "cert.pem", SSL_FILETYPE_PEM)) {
            fprintf(stderr, "SSL_CTX_use_certificate_file failed: ");
            ERR_print_errors_fp(stderr);
            exit(EXIT_FAILURE);
        }
        ssl = SSL_new(ssl_ctx);
        if (!ssl) {
            fprintf(stderr, "SSL_new failed\n");
            exit(EXIT_FAILURE);
        }
        if (!SSL_set_fd(ssl, fd)) {
            fprintf(stderr, "SSL_set_fd failed\n");
            exit(EXIT_FAILURE);
        }
        if (SSL_accept(ssl) <= 0) {
            fprintf(stderr, "SSL_accept failed: ");
            ERR_print_errors_fp(stderr);
            fprintf(stderr, "\n");
            exit(EXIT_FAILURE);
        }
        printf("SSL accepted.\n");

        while (1) {
            processed = SSL_read(ssl, buffer, sizeof(buffer));
            printf("Server SSL_read returned %d\n", processed);
            if (processed > 0) {
                printf("%.*s", (int)processed, buffer);
            } else {
                int ssl_error = SSL_get_error(ssl, processed);
                if (ssl_error == SSL_ERROR_ZERO_RETURN) {
                    printf("Server thinks a client closed a TLS session\n");
                    break;
                }
                if (ssl_error != SSL_ERROR_WANT_READ &&
                        ssl_error != SSL_ERROR_WANT_WRITE) {
                    fprintf(stderr, "server read failed: ssl_error=%d:", ssl_error);
                    ERR_print_errors_fp(stderr);
                    fprintf(stderr, "\n");
                    exit(EXIT_FAILURE);
                }
            }
        };
        printf("Server read finished.\n");

        SSL_free(ssl);
        SSL_CTX_free(ssl_ctx);
        close(fd);
        exit(EXIT_SUCCESS);
    }

    /* Client */
    printf("Client\n");
    client_socket = socket(AF_INET6, SOCK_STREAM, 0);
    if (client_socket < 0) {
        perror("socket failed");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (connect(client_socket, (const struct sockaddr *)&addr, sizeof(addr))) {
        perror("connect failed");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("TCP connected.\n");

    /*if (!OPENSSL_init_ssl(0, NULL)) {
        fprintf(stderr, "OPENSSL_init_ssl failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }*/
    /*OpenSSL_add_ssl_algorithms();*/
    ssl_ctx = SSL_CTX_new(TLS_client_method());
    if (!ssl_ctx) {
        fprintf(stderr, "SSL_CTX_new failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (1 != SSL_CTX_use_PrivateKey_file(ssl_ctx, "key.pem", SSL_FILETYPE_PEM)) {
        fprintf(stderr, "SSL_CTX_use_PrivatKey_file failed: ");
        ERR_print_errors_fp(stderr);
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (1 != SSL_CTX_use_certificate_file(ssl_ctx, "cert.pem", SSL_FILETYPE_PEM)) {
        fprintf(stderr, "SSL_CTX_use_certificate_file failed: ");
        ERR_print_errors_fp(stderr);
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    ssl = SSL_new(ssl_ctx);
    if (!ssl) {
        fprintf(stderr, "SSL_new failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (!SSL_set_fd(ssl, client_socket)) {
        fprintf(stderr, "SSL_set_fd failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (SSL_connect(ssl) <= 0) {
        fprintf(stderr, "SSL_connect failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("SSL connected.\n");


    for (const char *start = message; start - message < sizeof(message);
            start += processed) {
        processed = SSL_write(ssl, start, sizeof(message) - (start - message));
        printf("Client SSL_write returned %d\n", processed);
        if (processed <= 0) {
            int ssl_err = SSL_get_error(ssl, processed);
            if (ssl_err != SSL_ERROR_WANT_READ && ssl_err != SSL_ERROR_WANT_WRITE) {
                fprintf(stderr, "client write failed: ssl_error=%d: ", ssl_err);
                ERR_print_errors_fp(stderr);
                fprintf(stderr, "\n");
                kill(server_pid, SIGTERM);
                exit(EXIT_FAILURE);
            }
            processed = 0;
        }
    };
    printf("Client write finished.\n");

    retval = SSL_shutdown(ssl);
    if (retval < 0) {
        int ssl_err = SSL_get_error(ssl, retval);
        fprintf(stderr, "Client SSL_shutdown failed: ssl_err=%d\n", ssl_err);
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("Client shut down TLS session.\n");

    if (shutdown(client_socket, SHUT_RDWR)) {
        perror("client shutdown failed");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("Client shut down TCP.\n");

    SSL_free(ssl);
    SSL_CTX_free(ssl_ctx);
    if (server_pid == waitpid(server_pid, &wstatus, 0)) {
        if (WIFEXITED(wstatus)){
            printf("Server process terminated normally with %d exit code\n",
                    WEXITSTATUS(wstatus));
        } else if (WIFSIGNALED(wstatus)) {
            printf("Server process terminated with %d signal\n",
                    WTERMSIG(wstatus));
        }
    }
    exit(EXIT_SUCCESS);
}
~~~

I suspect shutdown(SHUT_RDWR) is the problem. Client should probably use close only sending TCP direction. But many OpenSSL manuals and articles declare that it's fine for a party to perform a one-side SSL_shutdown and then close the TCP connection completely if the party is not interested in data from the other side.

And actually many codes, e.g Perl Net-SSLeay do not perform SSL_shutdown at all and the server reads the sent data and reports 0 by SSL_read() after client closes the TCP connection. I worry that the new OpenSSL is not compatible enough to support existing code. Is there a way of writing an OpenSSL application that will work with both old and new OpenSSL/TLS version?

**Comment by mattcaswell** [comment]
This is an interesting problem - perhaps we should add something to the OpenSSL TLSv1.3 wiki page about this:
https://wiki.openssl.org/index.php/TLS1.3

In the TLSv1.3 protocol the server may send some protocol messages *after* the main handshake is complete. This could in theory also happen in TLSv1.2 (e.g. with a renegotiation) but it happens a lot less frequently. Specifically in TLSv1.3 sessions are not established during the main handshake. Instead, after the main handshake is complete, a server may send some NewSessionTicket messages to the client. The client can then use those tickets to later resume.

In your code the client never attempts to read any application data from the server, and the server never attempts to write any. Nonetheless, after the handshake, the server will automatically attempt to send 2 NewSessionTicket messages. I think what is happening is that the client has already detected the end of the handshake, sent its data, and then closed down the connection. The server meanwhile hasn't finished writing out its tickets and hits the broken pipe.

There are some things that spring to mind that you could do to work around this problem:

1) Disable automatic sending of tickets from the server. See SSL_CTX_set_num_tickets()/SSL_set_num_tickets():
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_num_tickets.html

This obviously means that you won't ever receive session information, and hence session resumption will not work. But maybe that is ok for you.

2) Change your application so that the server must write something and the client must read something. OpenSSL will always write its tickets out immediately after the main handshake. By forcing the client to read application data it will then also process any session tickets that were sent.

3) Do a full two way shutdown. This will ensure any pending protocol messages are dealt with.

4) Handle the broken pipe signal. In this case the server will be left in a state where it still wants to write out its tickets but it can't. You'd have to swap the write BIO for the server to go to some "/dev/null" style BIO instead and then you should be able to continue.

**Comment by mattcaswell** [comment]
One further thought on the above is that actually all of options 1, 3 and 4 will mean that session resumption will not work for you (because they all end up discarding or not sending the session tickets in some way). The only option out of the above which enables session resumption is option 2.

**Comment by mattcaswell** [comment]
Option 5 (if session resumption is important to you): Clients that want to do resumption must be prepared to process post-handshake session tickets at any time - its a fundamental property of TLSv1.3. This could be done by simply calling SSL_read(s, 0) if the read fd becomes readable, and not shutting down until it has got the tickets it wants (or perhaps some timeout has been reached). You can use SSL_CTX_sess_set_new_cb() to detect when a new session has been created.

The more I think about this, the more I think that option 4 is the right answer in the generic case in combination with option 5 if resumption is important.

**Comment by davidben** [comment]
In general, any remotely nontrivial application should be configuring things to ignore `SIGPIPE`. It's a goofy workaround for simple UNIX utilities that failed to check the return value of `write`. The assumption is the utility has no purpose in life but to read and write data from a single pipe and, if the writes are blackholed due to missing error-handling, the process may as well be killed.

Today, programs are much more complex and `SIGPIPE` remains as a wart that everyone targeting a UNIX-like platform must live with. :-/

**Comment by kroeckx** [comment]
It's not clear to me why option 3 wouldn't be able to resume

**Comment by mattcaswell** [comment]
> It's not clear to me why option 3 wouldn't be able to resume

Once we've sent a close_notify we ditch any unexpected handshake messages, so any NewSessionTickets that we may receive are not acted on:

https://github.com/openssl/openssl/blob/345bee916ac5ad28dd269afc24c27fe234c4045b/ssl/record/rec_layer_s3.c#L1558-L1593

**Comment by mattcaswell** [comment]
I'm wondering if we could do something in the library to make option 4 easier, i.e. basically if we're writing out a NewSessionTicket and get an EPIPE error back then ignore that error and carry as if the operation succeeded. Then all the application has to do is ignore SIGPIPE (which as @davidben suggests it probably should do anyway). Do we think the whole server that only reads/client that only writes scenario is common enough to warrant that?

**Comment by ppisar** [comment]
Thank you for the explanation. Comments to the options:

(1) I tried disabling sending tickets with SSL_set_num_tickets() and it works for me. Great.

(4) I was thinking how to implement ignoring SIGPIPE. Do I understand correctly that after failing SSL_accept() with SSL_ERROR_SYSCALL and EPIPE errno, I should change BIO and retry the SSL_accept() and expect a success? How could I distinguish handshake failure and ticket sending failure because of the EPIPE? Probably by the second EPIPE failure. This work around sounds clumsy.

(2) Changing an application protocol is probably a no-go. I don't have any real use case except the Net-SSLeay tests now. Maybe a syslog over TLS could be an example.

(5) Waiting for tickets in the client before shutting down sounds good. With the shutdown did you mean SSL_shutdown()? Yet I did not tried to implement it.

(3) I tried to implement a full two-way shutdown and while it works wit the old OpenSSL, the prerelease does not work as expected when a client performs a dummy SSL_read() between first and second SSL_shutdown() as recommend by SSL_shutdown(3) manual. The dummy SSL_read() returns 0, but SSL_get_error() reports SSL_ERROR_SYSCALL (with 0 errno) instead of SSL_ERROR_ZERO_RETURN. Is this a know OpenSSL bug? If it does not bother you, here is the program output:

~~~
$ ./a.out 
Client
Server
TCP connected.
TCP accepted.
SSL connected.
Client SSL_write returned 6
Client write finished.
Client shut down TLS session.
Client SSL_read returned 0
Client read failed: ssl_error=5 errno=Success: 
SSL accepted.
Server SSL_read returned 6
text
Server SSL_read returned 0
Server thinks a client closed a TLS session
Server read finished.
Server shut down a TLS session.
Server thinks a client shut down the TLS session.
~~~

And the corresponding code:

~~~
#define _POSIX_C_SOURCE 1
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <signal.h>
#include <errno.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <signal.h>
#include <string.h>

void handler(int signal) {
    fprintf(stderr, "Server reveived %d signal\n", signal);
}

int main(int argc, char **argv) {
    pid_t server_pid;
    int wstatus;
    int server_socket, client_socket;
    int true = 1;
    struct sockaddr_in6 addr = {
        .sin6_family = AF_INET6,
        .sin6_port = 2000,
        .sin6_flowinfo = 0,
        .sin6_addr = IN6ADDR_LOOPBACK_INIT
    };
    const char message[] = "text\n";
    char buffer[1024];
    int processed;
    SSL_CTX *ssl_ctx;
    SSL *ssl;
    int retval;

    server_socket= socket(AF_INET6, SOCK_STREAM, 0);
    if (server_socket < 0) {
        perror("socket failed");
        exit(EXIT_FAILURE);
    }
    if (setsockopt(server_socket, SOL_SOCKET, SO_REUSEADDR, &true, sizeof(true))) {
        perror("setcockopt failed\n");
        exit(EXIT_FAILURE);
    }
    if (bind(server_socket, (const struct sockaddr *)&addr, sizeof(addr))) {
        perror("bind failed");
        exit(EXIT_FAILURE);
    }
    if (listen(server_socket, 1)) {
        perror("liste failed");
        exit(EXIT_FAILURE);
    }

    server_pid = fork();
    if (server_pid < 0) {
        perror("fork failed");
        exit(EXIT_FAILURE);
    } else if (server_pid == 0) {
        /* Server */
        int fd;
        struct sigaction action;
        sigset_t sigset;

        printf("Server\n");

        sigemptyset(&sigset);
        action.sa_handler = handler;
        action.sa_flags = 0;
        action.sa_mask = sigset;
        sigaction(SIGPIPE, &action, NULL);

        fd = accept(server_socket, NULL, 0);
        if (fd < 0) {
            perror("accept failed");
            exit(EXIT_FAILURE);
        }
        printf("TCP accepted.\n");

        /*if (!OPENSSL_init_ssl(0, NULL)) {
            fprintf(stderr, "OPENSSL_init_ssl failed\n");
            exit(EXIT_FAILURE);
        }*/
        /*OpenSSL_add_ssl_algorithms();*/
        ssl_ctx = SSL_CTX_new(TLS_server_method());
        if (!ssl_ctx) {
            fprintf(stderr, "SSL_CTX_new failed\n");
            exit(EXIT_FAILURE);
        }
        if (1 != SSL_CTX_use_PrivateKey_file(ssl_ctx, "key.pem", SSL_FILETYPE_PEM)) {
            fprintf(stderr, "SSL_CTX_use_PrivatKey_file failed: ");
            ERR_print_errors_fp(stderr);
            exit(EXIT_FAILURE);
        }
        if (1 != SSL_CTX_use_certificate_file(ssl_ctx, "cert.pem", SSL_FILETYPE_PEM)) {
            fprintf(stderr, "SSL_CTX_use_certificate_file failed: ");
            ERR_print_errors_fp(stderr);
            exit(EXIT_FAILURE);
        }
        ssl = SSL_new(ssl_ctx);
        if (!ssl) {
            fprintf(stderr, "SSL_new failed\n");
            exit(EXIT_FAILURE);
        }
        if (!SSL_set_fd(ssl, fd)) {
            fprintf(stderr, "SSL_set_fd failed\n");
            exit(EXIT_FAILURE);
        }
#if OPENSSL_VERSION_NUMBER >= 0x1010100fL
        /* TLS 1.3 server sends session tickets after a handhake as part of
         * the SSL_accept(). If a client finishes all its job before server
         * sends the tickets, SSL_accept() fails with EPIPE errno. Since we
         * are not interested in a session resumption, we can not to send the
         * tickets. */
        /*if (1 != SSL_set_num_tickets(ssl, 0)) {
            fprintf(stderr, "SSL_set_num_tickets failed\n");
            exit(EXIT_FAILURE);
        }
        Or we can perform two-way shutdown. Client must call SSL_read() before
        the final SSL_shutdown(). */
#endif
        retval = SSL_accept(ssl);
        if (retval  <= 0) {
            fprintf(stderr, "SSL_accept failed ssl_err=%d errno=%s: ",
                    SSL_get_error(ssl, retval), strerror(errno));
            ERR_print_errors_fp(stderr);
            fprintf(stderr, "\n");
            exit(EXIT_FAILURE);
        }
        printf("SSL accepted.\n");

        while (1) {
            processed = SSL_read(ssl, buffer, sizeof(buffer));
            printf("Server SSL_read returned %d\n", processed);
            if (processed > 0) {
                printf("%.*s", (int)processed, buffer);
            } else {
                int ssl_error = SSL_get_error(ssl, processed);
                if (ssl_error == SSL_ERROR_ZERO_RETURN) {
                    printf("Server thinks a client closed a TLS session\n");
                    break;
                }
                if (ssl_error != SSL_ERROR_WANT_READ &&
                        ssl_error != SSL_ERROR_WANT_WRITE) {
                    fprintf(stderr, "server read failed: ssl_error=%d:", ssl_error);
                    ERR_print_errors_fp(stderr);
                    fprintf(stderr, "\n");
                    exit(EXIT_FAILURE);
                }
            }
        };
        printf("Server read finished.\n");

        retval = SSL_shutdown(ssl);
        if (retval < 0) {
            int ssl_err = SSL_get_error(ssl, retval);
            fprintf(stderr, "Server SSL_shutdown failed: ssl_err=%d\n", ssl_err);
            kill(server_pid, SIGTERM);
            exit(EXIT_FAILURE);
        }
        printf("Server shut down a TLS session.\n");

        if (retval != 1) {
            retval = SSL_shutdown(ssl);
            if (retval != 1) {
                int ssl_err = SSL_get_error(ssl, retval);
                fprintf(stderr,
                        "Waiting for client shutdown using SSL_shutdown failed: "
                        "ssl_err=%d\n", ssl_err);
                kill(server_pid, SIGTERM);
                exit(EXIT_FAILURE);
            }
        }
        printf("Server thinks a client shut down the TLS session.\n");

        SSL_free(ssl);
        SSL_CTX_free(ssl_ctx);
        close(fd);
        exit(EXIT_SUCCESS);
    }

    /* Client */
    printf("Client\n");
    client_socket = socket(AF_INET6, SOCK_STREAM, 0);
    if (client_socket < 0) {
        perror("socket failed");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (connect(client_socket, (const struct sockaddr *)&addr, sizeof(addr))) {
        perror("connect failed");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("TCP connected.\n");

    /*if (!OPENSSL_init_ssl(0, NULL)) {
        fprintf(stderr, "OPENSSL_init_ssl failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }*/
    /*OpenSSL_add_ssl_algorithms();*/
    ssl_ctx = SSL_CTX_new(TLS_client_method());
    if (!ssl_ctx) {
        fprintf(stderr, "SSL_CTX_new failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (1 != SSL_CTX_use_PrivateKey_file(ssl_ctx, "key.pem", SSL_FILETYPE_PEM)) {
        fprintf(stderr, "SSL_CTX_use_PrivatKey_file failed: ");
        ERR_print_errors_fp(stderr);
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (1 != SSL_CTX_use_certificate_file(ssl_ctx, "cert.pem", SSL_FILETYPE_PEM)) {
        fprintf(stderr, "SSL_CTX_use_certificate_file failed: ");
        ERR_print_errors_fp(stderr);
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    ssl = SSL_new(ssl_ctx);
    if (!ssl) {
        fprintf(stderr, "SSL_new failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (!SSL_set_fd(ssl, client_socket)) {
        fprintf(stderr, "SSL_set_fd failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    if (SSL_connect(ssl) <= 0) {
        fprintf(stderr, "SSL_connect failed\n");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("SSL connected.\n");


    for (const char *start = message; start - message < sizeof(message);
            start += processed) {
        processed = SSL_write(ssl, start, sizeof(message) - (start - message));
        printf("Client SSL_write returned %d\n", processed);
        if (processed <= 0) {
            int ssl_err = SSL_get_error(ssl, processed);
            if (ssl_err != SSL_ERROR_WANT_READ && ssl_err != SSL_ERROR_WANT_WRITE) {
                fprintf(stderr, "client write failed: ssl_error=%d: ", ssl_err);
                ERR_print_errors_fp(stderr);
                fprintf(stderr, "\n");
                kill(server_pid, SIGTERM);
                exit(EXIT_FAILURE);
            }
            processed = 0;
        }
    };
    printf("Client write finished.\n");

    retval = SSL_shutdown(ssl);
    if (retval < 0) {
        int ssl_err = SSL_get_error(ssl, retval);
        fprintf(stderr, "Client SSL_shutdown failed: ssl_err=%d\n", ssl_err);
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("Client shut down TLS session.\n");

    if (retval != 1) {
        /* Consume all server's data to access the server's shutdown */
        while (1) {
            processed = SSL_read(ssl, buffer, sizeof(buffer));
            printf("Client SSL_read returned %d\n", processed);
            if (processed <= 0) {
                int ssl_error = SSL_get_error(ssl, processed);
                if (ssl_error == SSL_ERROR_ZERO_RETURN) {
                    printf("Client thinks a server finished sending data\n");
                    break;
                }
                if (ssl_error != SSL_ERROR_WANT_READ &&
                        ssl_error != SSL_ERROR_WANT_WRITE) {
                    fprintf(stderr, "Client read failed: ssl_error=%d errno=%s: ",
                            ssl_error, strerror(errno));
                    ERR_print_errors_fp(stderr);
                    fprintf(stderr, "\n");
                    exit(EXIT_FAILURE);
                }
            }
        };

        retval = SSL_shutdown(ssl);
        if (retval != 1) {
            int ssl_err = SSL_get_error(ssl, retval);
            fprintf(stderr,
                    "Waiting for server shutdown using SSL_shutdown failed: "
                    "ssl_err=%d\n", ssl_err);
            kill(server_pid, SIGTERM);
            exit(EXIT_FAILURE);
        }
    }
    printf("Client thinks a server shut down the TLS session.\n");

    if (shutdown(client_socket, SHUT_RDWR)) {
        perror("client shutdown failed");
        kill(server_pid, SIGTERM);
        exit(EXIT_FAILURE);
    }
    printf("Client shut down TCP.\n");

    SSL_free(ssl);
    SSL_CTX_free(ssl_ctx);
    if (server_pid == waitpid(server_pid, &wstatus, 0)) {
        if (WIFEXITED(wstatus)){
            printf("Server process terminated normally with %d exit code\n",
                    WEXITSTATUS(wstatus));
        } else if (WIFSIGNALED(wstatus)) {
            printf("Server process terminated with %d signal\n",
                    WTERMSIG(wstatus));
        }
    }
    exit(EXIT_SUCCESS);
}
~~~

**Comment by kroeckx** [comment]
Have you tried this with the latest version from master? I can reproduce the problem using -pre8, but not using master.

**Comment by ppisar** [comment]
I conducted my test with pre8 only. Now I checked the master and I confirm the two-way shutdown works as expected with it. It was fixed with 93f528f36 commit as issue #6262.

**Comment by kroeckx** [comment]
I have to wonder how correct the SSL_shutdown() manpage is when it says
```
According to the TLS standard, it is acceptable for an application to only send its
shutdown alert and then close the underlying connection without waiting for the peer's
response
```
Should that at least add something about only in the case you're sure it's not going to send you data back? Or should we just remove that?

(I guess I should at least look up where in the RFC it says such a thing.)

**Comment by davidben** [comment]
RFC 5246:
>   If the application protocol using TLS provides that any data may be
>   carried over the underlying transport after the TLS connection is
>   closed, the TLS implementation must receive the responding
>   close_notify alert before indicating to the application layer that
>   the TLS connection has ended.  If the application protocol will not
>   transfer any additional data, but will only close the underlying
>   transport connection, then the implementation MAY choose to close the
>   transport without waiting for the responding close_notify.  No part
>   of this standard should be taken to dictate the manner in which a
>   usage profile for TLS manages its data transport, including when
>   connections are opened or closed.

RFC 8446 has a shorter version of that text that seems to omit the "MAY" clause, I suppose because it's implicit from the condition on the MUST clause.

close_notify is just an EOF. How your application protocol wants to deal with EOF depends on your application protocol. (Personally I think the second mode of `SSL_shutdown` shouldn't exist at all and the caller should just read to EOF if it wants to get the other EOF. But it's a bit late for that one.)

**Comment by kroeckx** [comment]
I'll think about how to improve the SSL_shutdown manpage even
more to at least make it more clear when it's safe to close the
connection without doing a two way shutdown.

It's already rewritten to suggest to use SSL_read() for the 2nd
part, I guess I can also make it more explict that this second
mode is not needed if SSL_read() was used.

**Comment by ppisar** [comment]
On Mon, Aug 13, 2018 at 07:24:02PM +0000, mattcaswell wrote:
> @ppisar perhaps you could try out the patch in #6944?
> 
The commit fixes one-way SSL_shutdown() followed by full TCP shutdown
scenario. Then the server can read all the data the client sent before.

If OpenSSL default BIO used send(..., MSG_NOSIGNAL) instead of write(),
applications would not have to deal with SIGPIPE signal. The only drawback is
that send() needs a descriptor of socket type. It would not work on other
types of descriptors. Although I cannot image why somebody used OpenSSL on top
of non-sockets.

**Comment by kroeckx** [comment]
The wiki currently also says:
`
An OpenSSL client will only process received sessions when they attempt to read application data. During the read if a session ticket message is encountered then it will be automatically processed. A consequence of this is that if a client application never attempts to read data from the server then it will never receive a session and hence resumption will not be possible. For that reason, if session resumption is required, then it is recommended that clients always perform at least one read between establishing and shutting down a connection. 
`

I doubt this is currently documented in the documentation. And I actually prefer that shutdown handles this instead.

**Comment by ppisar** [comment]
Thank you for the fix. I confirm it fixes SSL_accepting() a half-closed TCP connection.

**Comment by rdp** [comment]
Sorry I'm a bit of a newbie here.  I think this patch mentioned maybe doesn't help fix things for those of us that use a BIO, is that right?

In my head the difficulty is this: sometimes we don't control the client, only the server, so we can't "always enforce" a two way shutdown.  It's mentioned as optional anyway.

So if you're building a more "generic" transportation library, things get a bit funky.  When a user upgrades to openssl v1.1 suddenly (if their transport protocol doesn't include the client reading anything from the server, which is common in unit tests) things can start crashing.  But it's only "sometimes" because depending on how the timing ends up, maybe the socket has already been closed, maybe it hasn't, when the server sends its post handshake session ticket.  So you get flakey "broken pipe" messages.  In essence every library that uses OpenSSL suddenly now might have flakey unit tests.   The workarounds mentioned above do work (note to self, had to set the ticket num on the context before creating the SSL object).  It's confusing.  How can we know when SSL_Accept fails, if it's due to a "graceful" client closed the connection without reading, vs. non-graceful?  How to know that we can turn around and still call SSL_Read, sometimes, after an SSL_Accept just failed?

Kind of a fault of the spec...

**Comment by kroeckx** [comment]
After SSL_accept() failed, you can never call SSL_read().

So are you saying that there are still EPIPEs that we don't ignore?
Or that the EPIPE is seen a custom BIO, that the BIO returns some
error, and that we don't ignore that?

**Comment by rdp** [comment]
Yeah it's in a "scripting-ish" language (crystal) so the EPIPE from within the BIO causes it to raise an exception all the way out through SSL_Accept.

I did have a thought similar to #7948 maybe it could write tickets "with the first write" or configurably do so, or something like that?  Just an idea.  Thanks!
