### ISSUE TITLE
Need SSL_shutdown() support for libevent

### ISSUE THREAD

**Issue by pprindeville** [openssl/openssl#6911]
Opening this to get input from the OpenSSL community.  It's not clear to us in libevent-land how to handle clean shutdowns:

http://archives.seul.org/libevent/users/Aug-2018/msg00003.html

**Comment by pprindeville** [comment]
@azat Heads up.

**Comment by pprindeville** [comment]
And this thread seems to be related:

https://mta.openssl.org/pipermail/openssl-users/2018-August/008419.html

**Comment by azat** [comment]
@pprindeville it is not about "it is unclear" it is about "add SSL_shutdown() and be ready to the fact that close/free bufferevent can do some io over network"

So this not an openssl issue, can be closed.
