### ISSUE TITLE
i2d_ASN1_OBJECT issue

### ISSUE THREAD

**Issue by spike-spb** [openssl/openssl#6914]
Hello!

I have a question about i2d_ASN_OBJECT function. The [documentation](https://www.openssl.org/docs/man1.1.0/crypto/i2d_X509.html) says that:
> If *ppout is NULL memory will be allocated for a buffer and the encoded data written to it. In this case *ppout is not incremented and it points to the start of the data just written.
The function is declared as:
```c
int i2d_ASN1_OBJECT(const ASN1_OBJECT *a, unsigned char **pp)
```
So there is no need for manual memory allocation for the "pp"?
But I am getting segfault in this code:
```c
unsigned char *ctder = NULL;
int ctderlen, r;
ASN1_OBJECT* obj = OBJ_txt2obj("1.2.3.4", 1);
ctderlen = i2d_ASN1_OBJECT(obj, &ctder);
```
What is wrong with it?

**Comment by mspncp** [comment]
I checked it for master and I can confirm that  `i2d_ASN1_OBJECT()` indeed does not behave as documented in `d2i_x509.pod`.  So this is either a documention issue or an implementation bug. 

While the documented auto-allocation feature is implemented for `i2d_X509()` and in general for all functions which are implemented via `IMPLEMENT_ASN1_FUNCTION()` (because this feature is implemented in [asn1_item_flags_i2d()](https://github.com/openssl/openssl/blob/master/crypto/asn1/tasn_enc.c#L47)), it does not seem to be implemented for `i2d_ASN1_OBJECT()` (and maybe also other functions?)

The crash can be reproduced by applying the following patch to master


```
diff --git a/apps/openssl.c b/apps/openssl.c
index a872e2c5ee..41278c7bd5 100644
--- a/apps/openssl.c
+++ b/apps/openssl.c
@@ -164,6 +164,12 @@ int main(int argc, char *argv[])
         goto end;
     }

+    {
+        unsigned char *ctder = NULL;
+        ASN1_OBJECT* obj = OBJ_txt2obj("1.2.3.4", 1);
+        i2d_ASN1_OBJECT(obj, &ctder);
+    }
+
     prog = prog_init();
     pname = opt_progname(argv[0]);

```

and (after building) running the following command

```
~/src/openssl$ util/shlib_wrap.sh apps/openssl
Segmentation fault
```

**Comment by richsalz** [comment]
I bet it was a documentation error that I introduced when all the i2d manpages were unified. (There probably wasn’t separate docs for i2d_ASN1_OBJECT)

**Comment by mspncp** [comment]
There was only rudimentary documentation in [d2i_ASN1_OBJECT.pod](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/doc/crypto/d2i_ASN1_OBJECT.pod) and it was a good thing that you created this common man page for all i2d_TYPEs. The question now is whether i2d_ASN1_OBJECT is the only exception from the rule and how we should deal with this exception: just documented it or fix it?

**Comment by levitte** [comment]
In 1.0.2, `i2d_ASN1_OBJECT` is documented to work in similar ways as `i2d_X509`.  `i2d_X509` has the following as part of its documentation:

```
For OpenSSL 0.9.7 and later if B<*out> is B<NULL> memory will be
allocated for a buffer and the encoded data written to it. In this
case B<*out> is not incremented and it points to the start of the
data just written.
```

To me, that implies that `i2d_ASN1_OBJECT` should allocate new space if `*out` is NULL, and that the current behaviour is a bug, and should be corrected (actually, as far back as 1.0.2).

**Comment by levitte** [comment]
PR submitted

**Comment by spike-spb** [comment]
What about i2d_ASN1_BOOLEAN? See https://stackoverflow.com/questions/51784080/i2d-asn1-object-issue

**Comment by richsalz** [comment]
@levitte , looks like more to do: "Another example of a function that does not do allocation for you is i2d_ASN1_BOOLEAN() and indeed it crashes as well if you try to use it with a NULL out pointer."

**Comment by levitte** [comment]
Done, see #6943.  That one is 1.0.2 only...
