### ISSUE TITLE
Is EXPORT_VAR_AS_FUNCTION still needed?

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#6920]
The `EXPORT_VAR_AS_FUNCTION` functionality is a bit obscure, and comes with OpenSSL 0.9.7, at a time that should be long past by now, or so I hope (2002).  The entries about that functionality in CHANGES are these:

```
  *) Windows apparently can't transparently handle global
     variables defined in DLLs. Initialisations such as:

        const ASN1_ITEM *it = &ASN1_INTEGER_it;

     won't compile. This is used by the any applications that need to
     declare their own ASN1 modules. This was fixed by adding the option
     EXPORT_VAR_AS_FN to all Win32 platforms, although this isn't strictly
     needed for static libraries under Win32.
     [Steve Henson]
```
...
```
  *) Introduce the possibility to access global variables through
     functions on platform were that's the best way to handle exporting
     global variables in shared libraries.  To enable this functionality,
     one must configure with "EXPORT_VAR_AS_FN" or defined the C macro
     "OPENSSL_EXPORT_VAR_AS_FUNCTION" in crypto/opensslconf.h (the latter
     is normally done by Configure or something similar).

     To implement a global variable, use the macro OPENSSL_IMPLEMENT_GLOBAL
     in the source file (foo.c) like this:

        OPENSSL_IMPLEMENT_GLOBAL(int,foo)=1;
        OPENSSL_IMPLEMENT_GLOBAL(double,bar);

     To declare a global variable, use the macros OPENSSL_DECLARE_GLOBAL
     and OPENSSL_GLOBAL_REF in the header file (foo.h) like this:

        OPENSSL_DECLARE_GLOBAL(int,foo);
        #define foo OPENSSL_GLOBAL_REF(foo)
        OPENSSL_DECLARE_GLOBAL(double,bar);
        #define bar OPENSSL_GLOBAL_REF(bar)

     The #defines are very important, and therefore so is including the
     header file everywhere where the defined globals are used.

     The macro OPENSSL_EXPORT_VAR_AS_FUNCTION also affects the definition
     of ASN.1 items, but that structure is a bit different.

     The largest change is in util/mkdef.pl which has been enhanced with
     better and easier to understand logic to choose which symbols should
     go into the Windows .def files as well as a number of fixes and code
     cleanup (among others, algorithm keywords are now sorted
     lexicographically to avoid constant rewrites).
     [Richard Levitte]
```

(it isn't mentioned that this was also needed for VMS on VAX -- shared library support was kind of half baked...  since we don't support VAX any more since 1.1.0, that requirement is now long gone)

So the question is if the reasons for EXPORT_VAR_AS_FUNCTION still exist on Windows versions we claim to support (how far back?).  If not, it's become a no-op and should probably be cleaned away at some point...

**Comment by richsalz** [comment]
I was about to open the same issue, when I got prompted for this one :) I just created #9284 and was spurred to think about the var-as-function stuff.

I would actually go the other way, and *only* export functions.  Want a PR for that?

**Comment by levitte** [comment]
I actually agree that we never should export data, only functions. I can't look now, but I suspect that our data exports are very few, and that it would certainly be easy to re-implement them in a manner similar to how `errno` is often implemented (have you looked? It's pretty darn smart)

**Comment by richsalz** [comment]
Yes I've looked at errno. :)  The only data exports we support are in the ASN1 headers.  I'll work up a PR.

**Comment by levitte** [comment]
With #9285 merged, this can be closed.  Finally :smile:
