### ISSUE TITLE
EdDSA (ed25519, ed448) missing in speed output

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#6922]
When running `openssl speed` (f460e8396f8cb1), the performance of the ed25519 and ed448 is not tested or listed, I don't see any relevant identifiers in the source file either to run just them (like it is possible with `ecdhx25519` for X25519).

**Comment by paulidale** [comment]
I can't see why this should be a blocker -- speed didn't support this previously and still doesn't now.

**Comment by tomato42** [comment]
I don't think it *must* be in 1.1.1 either, but that's assuming it can get in one of the letter releases - EdDSA is kind of a hot topic, so not having ability to benchmark it is kind of a bummer...

**Comment by mattcaswell** [comment]
Do we think it can go in a letter release. Technically it would be a feature which wouldn't normally be allowed?

**Comment by tomato42** [comment]
fixed by d3a9fb10eefe
