### ISSUE TITLE
Message digest calculation in parallel

### ISSUE THREAD

**Issue by tomer-hadri-s1** [openssl/openssl#6923]
Hi,
I have a class which encapsulates below message digest functionality:
EVP_MD_CTX_new()
EVP_DigestInit_ex()
EVP_DigestUpdate()
EVP_DigestFinal_ex()
EVP_MD_CTX_free()

I want to allocate this class in multiple threads, meaning each thread will have its own instance, specifically its own MD context. Thus, i will have the option of performing multiple hashing in parallel. Due to performance considerations, i don`t want to use locks. 
Is this behavior is supported without implementing the OpenSSL locking functionality?

Thanks,
Tomer.

**Comment by richsalz** [comment]
You don't say what version of OpenSSL you are using, but since you ask about implementing locks, I assume you mean 1.0.2.  Yes, as long as the context is not shared you will be okay. Closing this.
