### ISSUE TITLE
openssl 1.1.0h gives error with update-ca-certificates

### ISSUE THREAD

**Issue by tallandtree** [openssl/openssl#6936]
When I install openssl 1.1.0h on Ubuntu 16.04 and run "update-ca-certificates", I get the following error:
```
Updating certificates in /etc/ssl/certs...
syntax error at /usr/bin/c_rehash line 15, near "= ;"
Unknown regexp modifier "/W" at /usr/bin/c_rehash line 28, at end of line
Unknown regexp modifier "/3" at /usr/bin/c_rehash line 28, at end of line
Unknown regexp modifier "/2" at /usr/bin/c_rehash line 28, at end of line
No such class installdir at /usr/bin/c_rehash line 63, near "Prefix our installdir"
  (Might be a runaway multi-line // string starting on line 28)
syntax error at /usr/bin/c_rehash line 63, near "Prefix our installdir"
Execution of /usr/bin/c_rehash aborted due to compilation errors.
```
This seems to be caused by missing quotes in 
```
my $dir = ;
my $prefix = /usr;
```
I install openssl via downloading the package and running:
```
config --prefix=/usr
make clean
make
make install
```
I've tried different config options, but none works:
```
config --prefix=/usr --openssldir=/usr
```
The quotes are not there in /usr/bin/c_rehash which gives the following error upon installing extra certificates (note you have to have new certificates in the /usr/local/share/ca-certificates folder):
```
# update-ca-certificates
Updating certificates in /etc/ssl/certs...
Unknown regexp modifier "/r" at /usr/bin/c_rehash line 15, at end of line
Execution of /usr/bin/c_rehash aborted due to compilation errors.
```
If I add quotes, the quotes are escaped.
It seems caused by this change: https://github.com/openssl/openssl/commit/77ba00bc3b7a1348f310ea7ce44890eb2c11899f#diff-4a4711c36bc44fe6f6cfa046eb6144fb. If the string does not contain quotes, it does not add the required quotes.

**Comment by levitte** [comment]
This has been fixed after the release of 1.1.0h, in 7ee2a43069913fb7c444c656048996ea92cc465e
Incidently, we're releasing 1.1.0i tomorrow, so you'll have that code changed back when upgrading.
