### ISSUE TITLE
NST not sent when ClientHello uses PSK

### ISSUE THREAD

**Issue by karlmhenderson** [openssl/openssl#6941]
According to RFC8446, Section C.4 “Servers SHOULD issue new tickets with every connection”.
 
Yet, version 1.1.1-pre8, in file ssl/statem/extensions_srvr.c, method tls_parse_ctos_psk, s->ext.ticket_expected = 0, preventing the NST from being sent.
 
This appears to be a bug – or am I missing something?

**Comment by karlmhenderson** [comment]
This is on version 1.1.1-pre8

**Comment by karlmhenderson** [comment]
I wasn't receiving a NST and traced it back to that line of code - not getting reset latter. Below is a trace from s_client connecting to s_server without the NST.

CONNECTED(00000003)
Sent Record
Header:
  Version = TLS 1.0 (0x301)
  Content Type = Handshake (22)
  Length = 288
    ClientHello, Length=284
      client_version=0x303 (TLS 1.2)
      Random:
        gmt_unix_time=0x278022F6
        random_bytes (len=28): 3BBFDB62A08FA81FFC5A26E05C3787EF990E3FEFCC9598A842E4989A
      session_id (len=32): A4771695BC9FA307BD10E1B590D7DB52272F10897E589E392F8C9A349C3CDC11
      cipher_suites (len=8)
        {0x13, 0x02} TLS_AES_256_GCM_SHA384
        {0x13, 0x03} TLS_CHACHA20_POLY1305_SHA256
        {0x13, 0x01} TLS_AES_128_GCM_SHA256
        {0x00, 0xFF} TLS_EMPTY_RENEGOTIATION_INFO_SCSV
      compression_methods (len=1)
        No Compression (0x00)
      extensions, length = 203
        extension_type=server_name(0), length=14
          0000 - 00 0c 00 00 09 6c 6f 63-61 6c 68 6f 73 74      .....localhost
        extension_type=ec_point_formats(11), length=4
          uncompressed (0)
          ansiX962_compressed_prime (1)
          ansiX962_compressed_char2 (2)
        extension_type=supported_groups(10), length=12
          ecdh_x25519 (29)
          secp256r1 (P-256) (23)
          ecdh_x448 (30)
          secp521r1 (P-521) (25)
          secp384r1 (P-384) (24)
        extension_type=session_ticket(35), length=0
        extension_type=encrypt_then_mac(22), length=0
        extension_type=extended_master_secret(23), length=0
        extension_type=signature_algorithms(13), length=30
          ecdsa_secp256r1_sha256 (0x0403)
          ecdsa_secp384r1_sha384 (0x0503)
          ecdsa_secp521r1_sha512 (0x0603)
          ed25519 (0x0807)
          ed448 (0x0808)
          rsa_pss_pss_sha256 (0x0809)
          rsa_pss_pss_sha384 (0x080a)
          rsa_pss_pss_sha512 (0x080b)
          rsa_pss_rsae_sha256 (0x0804)
          rsa_pss_rsae_sha384 (0x0805)
          rsa_pss_rsae_sha512 (0x0806)
          rsa_pkcs1_sha256 (0x0401)
          rsa_pkcs1_sha384 (0x0501)
          rsa_pkcs1_sha512 (0x0601)
        extension_type=supported_versions(43), length=7
          TLS 1.3 (draft 28) (32540)
          TLS 1.3 (draft 27) (32539)
          TLS 1.3 (draft 26) (32538)
        extension_type=psk_key_exchange_modes(45), length=2
          psk_dhe_ke (1)
        extension_type=key_share(51), length=38
            NamedGroup: ecdh_x25519 (29)
            key_exchange:  (len=32): A0EC13E2A33CC87075A311D77AE15B3BEBE50573849A1C368E6F94A1C3FFF133
        extension_type=psk(41), length=52
          0000 - 00 0f 00 09 43 6c 69 65-6e 74 5f 49 64 00 00   ....Client_Id..
          000f - 00 00 00 21 20 85 cb bf-70 a2 ac 23 c9 db b9   ...! ...p..#...
          001e - b2 c4 1c 00 c5 57 8e 16-1e b3 b9 ec c2 25 6f   .....W.......%o
          002d - 1c e8 a2 ca 12 82 a2                           .......

Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 122
    ServerHello, Length=118
      server_version=0x303 (TLS 1.2)
      Random:
        gmt_unix_time=0x75DBBB0E
        random_bytes (len=28): 0EB56C3AA4685DD6F90889F0B709433BBC5171DF0441A1D6FCCEBEEF
      session_id (len=32): A4771695BC9FA307BD10E1B590D7DB52272F10897E589E392F8C9A349C3CDC11
      cipher_suite {0x13, 0x02} TLS_AES_256_GCM_SHA384
      compression_method: No Compression (0x00)
      extensions, length = 46
        extension_type=supported_versions(43), length=2
            TLS 1.3 (draft 28) (32540)
        extension_type=key_share(51), length=36
            NamedGroup: ecdh_x25519 (29)
            key_exchange:  (len=32): 6E1E5BA50CEB4984375993E1062A22E5A958CE6FE527E7F65732828927FBCA5C

Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ChangeCipherSpec (20)
  Length = 1
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ApplicationData (23)
  Length = 23
  Inner Content Type = Handshake (22)
    EncryptedExtensions, Length=2
      extensions, length = 0

Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ApplicationData (23)
  Length = 1033
  Inner Content Type = Handshake (22)
    Certificate, Length=1012
      context (len=0): 
      certificate_list, length=1008
        ASN.1Cert, length=1003
------details-----
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            b9:ee:d4:d9:55:a5:9e:b3
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = OpenSSL Test Intermediate CA
        Validity
            Not Before: Dec  8 14:01:48 2011 GMT
            Not After : Oct 16 14:01:48 2021 GMT
        Subject: C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:f3:84:f3:92:36:dc:b2:46:ca:66:7a:e5:29:c5:
                    f3:49:28:22:d3:b9:fe:e0:de:e4:38:ce:ee:22:1c:
                    e9:91:3b:94:d0:72:2f:87:85:59:4b:66:b1:c5:f5:
                    7a:85:5d:c2:0f:d3:2e:29:58:36:cc:48:6b:a2:a2:
                    b5:26:ce:67:e2:47:b6:df:49:d2:3f:fa:a2:10:b7:
                    c2:97:44:7e:87:34:6d:6d:f2:8b:b4:55:2b:d6:21:
                    de:53:4b:90:ea:fd:ea:f9:38:35:2b:f4:e6:9a:0e:
                    f6:bb:12:ab:87:21:c3:2f:bc:f4:06:b8:8f:8e:10:
                    07:27:95:e5:42:cb:d1:d5:10:8c:92:ac:ee:0f:dc:
                    23:48:89:c9:c6:93:0c:22:02:e7:74:e7:25:00:ab:
                    f8:0f:5c:10:b5:85:3b:66:94:f0:fb:4d:57:06:55:
                    21:22:25:db:f3:aa:a9:60:bf:4d:aa:79:d1:ab:92:
                    48:ba:19:8e:12:ec:68:d9:c6:ba:df:ec:5a:1c:d8:
                    43:fe:e7:52:c9:cf:02:d0:c7:7f:c9:7e:b0:94:e3:
                    53:44:58:0b:2e:fd:29:74:b5:06:9b:5c:44:8d:fb:
                    32:75:a4:3a:a8:67:7b:87:32:0a:50:8d:e1:a2:13:
                    4a:25:af:e6:1c:b1:25:bf:b4:99:a2:53:d3:a2:02:
                    bf:11
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Non Repudiation, Key Encipherment
            Netscape Comment: 
                OpenSSL Generated Certificate
            X509v3 Subject Key Identifier: 
                82:BC:CF:00:00:13:D1:F7:39:25:9A:27:E7:AF:D2:EF:20:1B:6E:AC
            X509v3 Authority Key Identifier: 
                keyid:36:C3:6C:88:E7:95:FE:B0:BD:EC:CE:3E:3D:86:AB:21:81:87:DA:DA

    Signature Algorithm: sha1WithRSAEncryption
         a9:bd:4d:57:40:74:fe:96:e9:2b:d6:78:fd:b3:63:cc:f4:0b:
         4d:12:ca:5a:74:8d:9b:f2:61:e6:fd:06:11:43:84:fc:17:a0:
         ec:63:63:36:b9:9e:36:6a:b1:02:5a:6a:5b:3f:6a:a1:ea:05:
         65:ac:7e:40:1a:48:65:88:d1:39:4d:d3:4b:77:e9:c8:bb:2b:
         9e:5a:f4:08:34:39:47:b9:02:08:31:9a:f1:d9:17:c5:e9:a6:
         a5:96:4b:6d:40:a9:5b:65:28:cb:cb:00:03:82:63:37:d3:ad:
         b1:96:3b:76:f5:17:16:02:7b:bd:53:53:46:72:34:d6:08:64:
         9d:bb:43:fb:64:b1:49:07:77:09:61:7a:42:17:11:30:0c:d9:
         27:5c:f5:71:b6:f0:18:30:f3:7e:f1:85:3f:32:7e:4a:af:b3:
         10:f7:6c:c6:85:4b:2d:27:ad:0a:20:5c:fb:8d:19:70:34:b9:
         75:5f:7c:87:d5:c3:ec:93:13:41:fc:73:03:b9:8d:1a:fe:f7:
         26:86:49:03:a9:c5:82:3f:80:0d:29:49:b1:8f:ed:24:1b:fe:
         cf:58:90:46:e7:a8:87:d4:1e:79:ef:99:6d:18:9f:3e:8b:82:
         07:c1:43:c7:e0:25:b6:f1:d3:00:d7:40:ab:4b:7f:2b:7a:3e:
         a6:99:4c:54
-----BEGIN CERTIFICATE-----
MIID5zCCAs+gAwIBAgIJALnu1NlVpZ6zMA0GCSqGSIb3DQEBBQUAMHAxCzAJBgNV
BAYTAlVLMRYwFAYDVQQKDA1PcGVuU1NMIEdyb3VwMSIwIAYDVQQLDBlGT1IgVEVT
VElORyBQVVJQT1NFUyBPTkxZMSUwIwYDVQQDDBxPcGVuU1NMIFRlc3QgSW50ZXJt
ZWRpYXRlIENBMB4XDTExMTIwODE0MDE0OFoXDTIxMTAxNjE0MDE0OFowZDELMAkG
A1UEBhMCVUsxFjAUBgNVBAoMDU9wZW5TU0wgR3JvdXAxIjAgBgNVBAsMGUZPUiBU
RVNUSU5HIFBVUlBPU0VTIE9OTFkxGTAXBgNVBAMMEFRlc3QgU2VydmVyIENlcnQw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDzhPOSNtyyRspmeuUpxfNJ
KCLTuf7g3uQ4zu4iHOmRO5TQci+HhVlLZrHF9XqFXcIP0y4pWDbMSGuiorUmzmfi
R7bfSdI/+qIQt8KXRH6HNG1t8ou0VSvWId5TS5Dq/er5ODUr9OaaDva7EquHIcMv
vPQGuI+OEAcnleVCy9HVEIySrO4P3CNIicnGkwwiAud05yUAq/gPXBC1hTtmlPD7
TVcGVSEiJdvzqqlgv02qedGrkki6GY4S7GjZxrrf7Foc2EP+51LJzwLQx3/JfrCU
41NEWAsu/Sl0tQabXESN+zJ1pDqoZ3uHMgpQjeGiE0olr+YcsSW/tJmiU9OiAr8R
AgMBAAGjgY8wgYwwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBeAwLAYJYIZI
AYb4QgENBB8WHU9wZW5TU0wgR2VuZXJhdGVkIENlcnRpZmljYXRlMB0GA1UdDgQW
BBSCvM8AABPR9zklmifnr9LvIBturDAfBgNVHSMEGDAWgBQ2w2yI55X+sL3szj49
hqshgYfa2jANBgkqhkiG9w0BAQUFAAOCAQEAqb1NV0B0/pbpK9Z4/bNjzPQLTRLK
WnSNm/Jh5v0GEUOE/Beg7GNjNrmeNmqxAlpqWz9qoeoFZax+QBpIZYjROU3TS3fp
yLsrnlr0CDQ5R7kCCDGa8dkXxemmpZZLbUCpW2Uoy8sAA4JjN9OtsZY7dvUXFgJ7
vVNTRnI01ghknbtD+2SxSQd3CWF6QhcRMAzZJ1z1cbbwGDDzfvGFPzJ+Sq+zEPds
xoVLLSetCiBc+40ZcDS5dV98h9XD7JMTQfxzA7mNGv73JoZJA6nFgj+ADSlJsY/t
JBv+z1iQRueoh9Qeee+ZbRifPouCB8FDx+AltvHTANdAq0t/K3o+pplMVA==
-----END CERTIFICATE-----
------------------
        extensions, length = 0

depth=0 C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
verify error:num=21:unable to verify the first certificate
verify return:1
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ApplicationData (23)
  Length = 281
  Inner Content Type = Handshake (22)
    CertificateVerify, Length=260
      Signature Algorithm: rsa_pss_rsae_sha256 (0x0804)
      Signature (len=256): 6B97A4C0439CDE56BCABD769D387CDD126586DBA35458404F17CF3E3B9FF79C9115BF29EB04A9D4EC64D3A13E4187CF4F4DCFC6EB3A1F379801EB5A3D1221A18F8487A3C3D2214743178AB272BF09CB185BDB6FB2FEFE1496F773EF0741870D3124E21CB45C69E2CC1A6C8A5F82D72D67795AE323A7D2B1A69C5E9B1947BA3FD6C96EB5A29497E0C654DCC2152EC6C2B8E6084E34D3F8363D2F9E1154F6EED269E6CBF168D578D50D490485329372A6B98B9C83CCC84BA06D397AA1B1D15CC3C78D61B4A716D67C5935FB5E966DE15ABE91AEFC53EEBF5E1E616C17EC0A04E45978E558F8249F24051F2F6D3FEDB15C719552E1946B1E8786A0F4A3736F4CFCF

Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ApplicationData (23)
  Length = 69
  Inner Content Type = Handshake (22)
    Finished, Length=48
      verify_data (len=48): FB8D5F871623F019D30EE25B7A7C5323C670735B05E6A6DDB2EE7FBC482C87E9B85DFE950DC72D2D7320139914AD2E60

Sent Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ChangeCipherSpec (20)
  Length = 1
    change_cipher_spec (1)

Sent Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ApplicationData (23)
  Length = 69
  Inner Content Type = Handshake (22)
    Finished, Length=48
      verify_data (len=48): 18301F896D53A0CA3982114946519166BA4F81A126FDDDEEC5272F6234277376A091FDB6090D70A8B6955EAB3503AC81

---
Certificate chain
 0 s:C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
   i:C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = OpenSSL Test Intermediate CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIID5zCCAs+gAwIBAgIJALnu1NlVpZ6zMA0GCSqGSIb3DQEBBQUAMHAxCzAJBgNV
BAYTAlVLMRYwFAYDVQQKDA1PcGVuU1NMIEdyb3VwMSIwIAYDVQQLDBlGT1IgVEVT
VElORyBQVVJQT1NFUyBPTkxZMSUwIwYDVQQDDBxPcGVuU1NMIFRlc3QgSW50ZXJt
ZWRpYXRlIENBMB4XDTExMTIwODE0MDE0OFoXDTIxMTAxNjE0MDE0OFowZDELMAkG
A1UEBhMCVUsxFjAUBgNVBAoMDU9wZW5TU0wgR3JvdXAxIjAgBgNVBAsMGUZPUiBU
RVNUSU5HIFBVUlBPU0VTIE9OTFkxGTAXBgNVBAMMEFRlc3QgU2VydmVyIENlcnQw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDzhPOSNtyyRspmeuUpxfNJ
KCLTuf7g3uQ4zu4iHOmRO5TQci+HhVlLZrHF9XqFXcIP0y4pWDbMSGuiorUmzmfi
R7bfSdI/+qIQt8KXRH6HNG1t8ou0VSvWId5TS5Dq/er5ODUr9OaaDva7EquHIcMv
vPQGuI+OEAcnleVCy9HVEIySrO4P3CNIicnGkwwiAud05yUAq/gPXBC1hTtmlPD7
TVcGVSEiJdvzqqlgv02qedGrkki6GY4S7GjZxrrf7Foc2EP+51LJzwLQx3/JfrCU
41NEWAsu/Sl0tQabXESN+zJ1pDqoZ3uHMgpQjeGiE0olr+YcsSW/tJmiU9OiAr8R
AgMBAAGjgY8wgYwwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBeAwLAYJYIZI
AYb4QgENBB8WHU9wZW5TU0wgR2VuZXJhdGVkIENlcnRpZmljYXRlMB0GA1UdDgQW
BBSCvM8AABPR9zklmifnr9LvIBturDAfBgNVHSMEGDAWgBQ2w2yI55X+sL3szj49
hqshgYfa2jANBgkqhkiG9w0BAQUFAAOCAQEAqb1NV0B0/pbpK9Z4/bNjzPQLTRLK
WnSNm/Jh5v0GEUOE/Beg7GNjNrmeNmqxAlpqWz9qoeoFZax+QBpIZYjROU3TS3fp
yLsrnlr0CDQ5R7kCCDGa8dkXxemmpZZLbUCpW2Uoy8sAA4JjN9OtsZY7dvUXFgJ7
vVNTRnI01ghknbtD+2SxSQd3CWF6QhcRMAzZJ1z1cbbwGDDzfvGFPzJ+Sq+zEPds
xoVLLSetCiBc+40ZcDS5dV98h9XD7JMTQfxzA7mNGv73JoZJA6nFgj+ADSlJsY/t
JBv+z1iQRueoh9Qeee+ZbRifPouCB8FDx+AltvHTANdAq0t/K3o+pplMVA==
-----END CERTIFICATE-----
subject=C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert

issuer=C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = OpenSSL Test Intermediate CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1559 bytes and written 373 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1534185356
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no

**Comment by mattcaswell** [comment]
Please provide details of your s_client and s_server command lines, and what version OpenSSL you were testing.

**Comment by karlmhenderson** [comment]
Version 1.1.1-pre8
> openssl s_client -tls1_3 -psk_identity Client_Id -psk 1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A -connect localhost:443 -trace
> openssl s_server -tls1_3 -psk_identity Client_Id -psk 1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A -port 443 -trace

**Comment by mattcaswell** [comment]
Ah, right. We suppress NewSessionTicket when we accept an external PSK on the basis that you already have a workable multi-use PSK so you don't need another one.

@vdukhovni is that behaviour in line with your expectations following our previous discussions on tickets/PSKs?

Maybe there is a documentation issue here.

**Comment by karlmhenderson** [comment]
I discussed this with Sean Turner as wolfssl does not exhibit this behavior.

This is Sean's take:

"Okay so I’m following you - the OpenSSL server won’t send an NST message after completing the an initial PSK-based handshake?  That seems wrong.  If you look at C.4 it says "Servers SHOULD issue new tickets with every connection”

**Comment by vdukhovni** [comment]
IIRC, we did not discuss how the ticket issuance policy interacts with **external** PSKs, so that's a judgement call.  We should probably consider external PSKs as equivalent to a full handshake (not a ticket-based resumption), and issue tickets accordingly.  That might reduce "linkability" of future resumptions. What do you think?

**Comment by mattcaswell** [comment]
Hmmm, I was fairly sure we implemented this as a result of our discussions...

I'm unsure about the linkability issue. Ultimately external PSKs are multi-use after all, so as soon as you use it again you are linked. I suppose it does reduce linkability of intermediate resumption PSKs.

**Comment by vdukhovni** [comment]
Yes, linkable for each full PSK exchange, but given a sufficiently long resumption lifetime, not in between. Sorry, I don't recall any particular view I would have taken on external PSKs and tickets.  I was focused mainly on session tickets and interaction with full handshakes, ...
So no strong views here from me, this is probably fine either way, but I am leaning somewhat in the direction of issuing tickets as with other initial handshakes.

**Comment by mattcaswell** [comment]
Ok, I'll take a look at it.

**Comment by mattcaswell** [comment]
I created a fix in #7097 for this. In all other respects we treat a PSK connection like a resumption, so I made the tickets works like this too (i.e. we issue one new ticket after a PSK, just like we would if resuming from an earlier ticket).
