### ISSUE TITLE
openssl in new version does not read ECDSA keys from previous version

### ISSUE THREAD

**Issue by Rejikcz** [openssl/openssl#6947]
Please can you help ? 
redhat was able to reproduce bug, details are here:

https://bugzilla.redhat.com/show_bug.cgi?id=1610222

Thanks

**Comment by richsalz** [comment]
Can you reproduce this just with openssl, and without using openssh?  Which versions of openssl do you think are incompatible?

**Comment by Rejikcz** [comment]
Hi,

old release was something about openssl-1.0.1e (for testing I use CENTOSv6.9)
current "stable" release in F28 is openssl-1.1.0h

when I was googling I found many comments regarding change from 1.0 to 1.1

and your question about reproducing just with openssl - please can you advice which command should I use ? I'm really no expert, I need help in this case. I will give you all results you neeed. 

Thank you
Rej

**Comment by levitte** [comment]
Did you get anywhere?

**Comment by Rejikcz** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1610222
https://bugzilla.mindrot.org/show_bug.cgi?id=2895

issue is clear, but nobody knows, what to do ...

**Comment by petrovr** [comment]
Issue is not clear.
I test read of posted key with all OpenSSL versions that I have (from 0.9.8f to current master) - key is read by openssl.
In one on comment key was tested with named_curve but argument is explicit.

New secsh may print different error when cannot read key - wrong passphrase, invalid format, libcrypto error.
Old secsh versions print only wrong passphrase when PEM key cannot be loaded and invalid format when check for EC key fail.

Dunno why secsh command fail in Rejikcz tests.
With pkixssh builds against 0.9.8*, 1.0.{0|1|2}*, 1.1* master key is read just fine (ssh-keygen -f ... -y).

**Comment by t8m** [comment]
I've verified that with current 1.1.1 release and master as well the command `openssl ec -in ~/Downloads/ecdsa  -text -param_enc named_curve` converts the key from the https://bugzilla.mindrot.org/show_bug.cgi?id=2895 link into the named curve parameter form just fine.

Closing. If you can still reproduce the issue with the current master, please reopen.
