### ISSUE TITLE
openssl tls

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#6952]
I'm using openssl with external engine and I need the same write/read sequence number on each peer side. When the connection is started the client begins to write with seq = 1, and the server starts reading with 0 value. Why does this happen?

**Comment by YuDudysheva** [comment]
Actually each side of connection starts sending from the first record and starts receiving from the zero one.

**Comment by richsalz** [comment]
That is the way TLS works.  Clsoing this issue.
