### ISSUE TITLE
Consider using clang's scan-build static analyzer

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#6969]
I got it to work like this:
```
; CC=gcc ./config ...options...
; scan-build make
; scan-view /tmp/...filename...
```

4 API errors (passing in NULL) 2 logic errors (undefined assignment or operation result), 113 dead assignment/ininitialization/increment (pointless op)

**Comment by dot-asm** [comment]
I only made some semi-random picks from crypto and ssl. The only API error from ssl/statem/statem_dtls.c is false. Uninitialized reads in curve448 are false. It's angry with reading junk in masking it with zero in bn_mod_add_fixed_top, which produces predictable result and solves constant-time-ness problem. And here is interesting question in context of bn_mod_add_fixed_top. Would we memset uninitialized vector to appease analyzer which simply can't see that outcome it not undefined?

As for dead assignments/initialization/increments. Yeah, some would be appropriate to remove, line zeroings in old des, cast, idea, ..., contemporary compilers don't honour them anyway. But a lot of dead assignments/initialization/increments can be attributed to readability. Which brings us to another interesting question. Computers for humans or vice versa? I mean would it be appropriate to make code less readable for humans to meet computer's standard or "readability"?

**Comment by paulidale** [comment]
The scan-build program doesn't seem to be strongly recommended anymore: https://clang-analyzer.llvm.org/command-line.html

As with all static analysers, it needs to be backed by a database to avoid getting the same (false) reports each run.  scan-build isn't.

**Comment by t8m** [comment]
Should we close it?

**Comment by richsalz** [comment]
In light of Pauli's comments, I'm closing this.  Perhaps 6968 should be expanded in scope to cover all static analyzers the project knows of, and then open specific issues if/when one seems worth doing?
