### ISSUE TITLE
Unchecked EVP_MD_CTX_new() return value in OCSP_basic_sign()

### ISSUE THREAD

**Issue by Jason2031** [openssl/openssl#6973]
Function `EVP_MD_CTX_new()` returns a NULL pointer if there is no enough memory. To avoid potential NULL dereference, its return value should be checked against NULL. However, in function `OCSP_basic_sign()`, its return value is directly used without NULL check. This may result in a NULL dereference bug. Codes related to this bug are as follow:
```c
int OCSP_basic_sign(OCSP_BASICRESP *brsp,
                    X509 *signer, EVP_PKEY *key, const EVP_MD *dgst,
                    STACK_OF(X509) *certs, unsigned long flags)
{
    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    EVP_PKEY_CTX *pkctx = NULL;
    int i;

    if (!EVP_DigestSignInit(ctx, &pkctx, dgst, NULL, key)) {
        EVP_MD_CTX_free(ctx);
        return 0;
    }
    i = OCSP_basic_sign_ctx(brsp, signer, ctx, certs, flags);
    EVP_MD_CTX_free(ctx);
    return i;
}
```
Function `EVP_DigestSignInit()` use `ctx` without checking if it is non-NULL.

**Comment by paulidale** [comment]
Fixed by #7087
