### ISSUE TITLE
STDIN doesn't work when use s_client on 1.0.2 (on Windows command)

### ISSUE THREAD

**Issue by x270** [openssl/openssl#6979]
Use ```s_client -connect``` and need network auto disconnection,
run the following command on Linux.
```openssl s_client -connect example.com:443 < /dev/null```

run the following command on Windows. 
```openssl s_client -connect example.com:443 < nul```

This Windows command is OK on 1.1.0, but it doesn't work on 1.0.2 on Windows.
STDIN, It seems to be ignored on 1.0.2.
```read: errno=0``` will be displayed after 60 seconds and will be disconnected. It seem timeout.

Is this in the specification ?

I tried the following Versions.
- OS : Windows 10 Pro 1803, Windows 7 Pro SP1
- OpenSSL : 1.0.2f, 1.0.2h, 1.0.2m, 1.0.2o, 1.0.2p, 1.1.0h, 1.1.0i

**Comment by t8m** [comment]
The 1.0.2 releases are no longer supported. Closing.
