### ISSUE TITLE
Unchecked OBJ_nid2obj() return value in crypto/asn1/asn_moid.c: do_create

### ISSUE THREAD

**Issue by Jason2031** [openssl/openssl#6982]
Function `OBJ_nid2obj()` may return a NULL pointer on failure. To avoid potential NULL dereference, its return value should be checked against NULL. However, in function `do_create()` in file `crypto/asn1/asn_moid.c`, its return value is directly used without NULL check. This may result in a NULL dereference bug. Codes related to this bug are as follow:

```c
   99          memcpy(lntmp, ln, p - ln);
  100          lntmp[p - ln] = 0;
  101:         oid = OBJ_nid2obj(nid);
  102          oid->ln = lntmp;
  103      }
```
Jiecheng Wu, Zuxing Gu

**Comment by dot-asm** [comment]
OBJ_nid2obj is bound to succeed here, but arguably it's would be more appropriate to allocate string first *then* call OBJ_create. See #6998. Closing this. Thank you very much for report!
