### ISSUE TITLE
Consider a proper application-level library

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#6986]
This is from email from @DDvO in Sept 2017.

Back on 13 May 2016 I had proposed by email to a couple of people including Rich Salz
a third library level (on top of crypto and ssl) with more high-level, application-oriented code.
His response was:
That is a really interesting idea.  Please bring this up on openssl-dev mailing list.

Then I posted that by mistake unfortunately not in the right forum but at:
https://groups.google.com/forum/#!topic/mailing.openssl.dev/FOL2afc3cb8
I quote my post here for convenience:
So far, the OpenSSL code has essentially a three-level structure with a hierarchy of two libraries and a command-line application at the top: 

apps/openssl 
libssl 
libcrypto 

In the apps/ directory there is various generally useful code like handling crypto-related files and messages, general TLS client/server and CA functionality, implementing parts of protocols like S/MIME, CRL, and OCSP, and certainly more to come. 

While this code serves as a model for using the libraries and it can be used in a limited way by invoking the openssl application binary, it cannot be re-used directly. Other applications that need similar functionality need to copy/re-implement and then maintain portions of that code. 

On the other hand, the libraries contain some code that is actually too high-level for them, for instance the minimal HTTP client as part of the crypto library (crypto/ocsp/ocsp_ht.c). 

It would be very helpful to introduce a further level in the hierarchy consisting of a more application-oriented library: 

apps/openssl 
libtlsapps <-- new (with tentative name here) 
libssl 
libcrypto 

Then all more high-level and application support functionality will go there. This would make much of the generally useful code that so far resides in the apps/ folder directly accessible to other 
applications at the programming level, i.e., in the form of a library/API, with all the re-usability advantages that this brings. It would also relieve libcrypto from more application-/high-level topics like HTTP. 

This library would also form an ideal condensation point for further high-level uses of TLS that may in the future get integrated with OpenSSL, like CMP and EST implementations.

I recently learned that LibreSSL already/meanwhile has something in this direction:
libtls: a new TLS library, designed to make it easier to write foolproof applications
I believe this would be of great benefit also for OpenSSL itself.

<< ATT00001.txt (0.4KB) (0.4KB) >>

**Comment by DDvO** [comment]
Quoting from https://github.com/openssl/openssl/pull/11755#issuecomment-629228771

> > @DDvO: 
> > And of course various other rather high-level features that do not really belong to libcrypto,
> > such as S/MIME, TS, HTTP, OCSP, and CMP.
> 
> @levitte:
> I agree completely! There's a lot that's been shoved into libcrypto that's more like protocol libraries (interestingly, we have a separate libssl, go figure!) or application utility libraries.

We could go for this not too far in the future, after finishing 3.0.

**Comment by levitte** [comment]
We could, but that'll have to be after a lot of consideration, since that's going to be quite a huge breaking change.

Do note that I think that libapps.a should remain a utility library specifically for our application.  If someone wants to make a more public library from it, the API should really be redone from the ground up, 'cause the current pile of random routines is a horrible design for public use.

**Comment by DDvO** [comment]
I'd be interested in adopting this major topic - if I get sufficient support/funding by Siemens,
and of course in close agreement with all others here.

**Comment by levitte** [comment]
In my personal pink nirvana, we would build a new app from the bottom up, with a more modern command line UI (probably inspired from command trees such as git and a few others).  Even better, I'd make that a separate project.

Like I said, pink nirvana.

**Comment by richsalz** [comment]
I'm (slightly) curious what's missing from your nirvana, pink or otherwise.  To me, the only thing missing is aliases and user initrc files

**Comment by mattcaswell** [comment]
> pink nirvana

Ha - ha. I'm not sure that term means much to any but a few select people. For the unenlightened its the name we gave to this diagram from the 3.0 design doc:

https://www.openssl.org/docs/images/ToBeComponent.png

**Comment by levitte** [comment]
@richsalz, the consistency between commands is bulky; there's no support whatsoever for "global" options; some of the commands are bulky (most of all the pkey commands) and could do well with some positional arguments that don't need a -flag in front of them (for example the algorithm name).
It's also notoriously *difficult* to write new commands, and the whole structure still has pretty heavy traces from the time when each command was a mini-program in its own right. 

A complete redesign from the ground up would be better in the long run than the constant patching that's been done so far.

**Comment by richsalz** [comment]
See #13440, closing.
