### ISSUE TITLE
Support Ed25519 sign/verify operations from OpenSSL CLI

### ISSUE THREAD

**Issue by parasssh** [openssl/openssl#6988]
The issue #5873 only fixed the error reporting for Ed25519 sign operation with "dgst" utility. 

But as it stands, as of today, there is no way to sign/verify a message/file using Ed25519 keys and signature algorithm using the OpenSSL CLI. 

I suggest adding a option -one-shot to the pkeyutl

**Comment by CodeGuro** [comment]
After coming across this issue, I did some research and found the threads #5873, #5880, #6284, and followed them up to this one. I came to say that the same issue affects Ed448 sign operation as well.

**Comment by la-urre** [comment]
Hey ! Any update on this ?

**Comment by mattcaswell** [comment]
> I suggest adding a option -one-shot to the pkeyutl

This sounds reasonable but this is very low priority at the moment. Everyone is concentrating on the changes required for 3.0. Adding the "help wanted" label. PRs welcome.

**Comment by romen** [comment]
`master`, and the upcoming 3.0 alpha1 release, ships with limited (there are size limits due to buffering) support for signing files from the command line with `pkeyutl`.

A related discussion is happening on the `openssl-users` mailing list in this thread: https://mta.openssl.org/pipermail/openssl-users/2020-April/012248.html


An extract from it that is relevant to this PR:

```sh
λ /tmp/test25519/ ### Ensure OpenSSL dev build is in use for this shell
λ /tmp/test25519/ which openssl ; openssl version
/opt/openssl-master/bin/openssl
OpenSSL 3.0.0-dev xx XXX xxxx (Library: OpenSSL 3.0.0-dev xx XXX xxxx)
λ /tmp/test25519/ ### Generate Ed25519 private key
λ /tmp/test25519/ openssl genpkey -algorithm Ed25519 -out priv.pem
λ /tmp/test25519/ ### Extract pub key from private key
λ /tmp/test25519/ openssl pkey -in priv.pem -pubout -out pub.pem
λ /tmp/test25519/ ###
λ /tmp/test25519/ ### Up to this point all the commands were compatible
λ /tmp/test25519/ ### with OpenSSL 1.1.1 releases, the next one is the
λ /tmp/test25519/ ### one that requires OpenSSL 3.0.0-dev as `pkeyutl`
λ /tmp/test25519/ ### now has support for `-rawin` which is required
λ /tmp/test25519/ ### for signing/veryfing files with Ed25519 keys. 
λ /tmp/test25519/ ###
λ /tmp/test25519/ ### Generate a signature `sig.dat` for the file
λ /tmp/test25519/ ### `/bin/ls` using `priv.key` private Ed25519 key;
λ /tmp/test25519/ openssl pkeyutl -sign -inkey priv.pem -out sig.dat \
    -rawin -in /bin/ls
λ /tmp/test25519/ ### Verify the file `/bin/ls` against a signature
λ /tmp/test25519/ ### `sig.dat` under the public Ed25519 key `pub.pem`.
λ /tmp/test25519/ ### Success is expected.
λ /tmp/test25519/ openssl pkeyutl -verify -pubin -inkey pub.pem \
    -rawin -in /bin/ls -sigfile sig.dat
Signature Verified Successfully
λ /tmp/test25519/ ### Verify the file `/bin/echo` against a signature
λ /tmp/test25519/ ### `sig.dat` under the public Ed25519 key `pub.pem`.
λ /tmp/test25519/ ### Failure is expected.
λ /tmp/test25519/ openssl pkeyutl -verify -pubin -inkey pub.pem \
    -rawin -in /bin/echo -sigfile sig.dat
Signature Verification Failure
```
The updated documentation is in [this template file](https://github.com/openssl/openssl/blob/555ed96812f7f6cfb6066327aee40244517e2e05/doc/man1/openssl-pkeyutl.pod.in) and should soon be available also at https://www.openssl.org/docs/manmaster/man1/openssl-pkeyutl.html

I believe current support (even with its limits) could already be enough to close this issue.
@parasssh do you agree?

**Comment by romen** [comment]
Sidenote:
> Publication of the updated documentation is depending on fixing https://github.com/openssl/tools/issues/66 for which the PR awaiting OMC approval is at https://github.com/openssl/web/pull/175

**Comment by romen** [comment]
I will give it at least 3 more days (to reach a full week) to give time to @parasssh to comment on the resolution of the issue, unless otherwise indicated I will assume we can agree on considering this issue solved and close it.

**Comment by parasssh** [comment]
> `master`, and the upcoming 3.0 alpha1 release, ships with limited (there are size limits due to buffering) support for signing files from the command line with `pkeyutl`.
> 
> A related discussion is happening on the `openssl-users` mailing list in this thread: https://mta.openssl.org/pipermail/openssl-users/2020-April/012248.html
> 
> An extract from it that is relevant to this PR:
> 
> ```shell
> λ /tmp/test25519/ ### Ensure OpenSSL dev build is in use for this shell
> λ /tmp/test25519/ which openssl ; openssl version
> /opt/openssl-master/bin/openssl
> OpenSSL 3.0.0-dev xx XXX xxxx (Library: OpenSSL 3.0.0-dev xx XXX xxxx)
> λ /tmp/test25519/ ### Generate Ed25519 private key
> λ /tmp/test25519/ openssl genpkey -algorithm Ed25519 -out priv.pem
> λ /tmp/test25519/ ### Extract pub key from private key
> λ /tmp/test25519/ openssl pkey -in priv.pem -pubout -out pub.pem
> λ /tmp/test25519/ ###
> λ /tmp/test25519/ ### Up to this point all the commands were compatible
> λ /tmp/test25519/ ### with OpenSSL 1.1.1 releases, the next one is the
> λ /tmp/test25519/ ### one that requires OpenSSL 3.0.0-dev as `pkeyutl`
> λ /tmp/test25519/ ### now has support for `-rawin` which is required
> λ /tmp/test25519/ ### for signing/veryfing files with Ed25519 keys. 
> λ /tmp/test25519/ ###
> λ /tmp/test25519/ ### Generate a signature `sig.dat` for the file
> λ /tmp/test25519/ ### `/bin/ls` using `priv.key` private Ed25519 key;
> λ /tmp/test25519/ openssl pkeyutl -sign -inkey priv.pem -out sig.dat \
>     -rawin -in /bin/ls
> λ /tmp/test25519/ ### Verify the file `/bin/ls` against a signature
> λ /tmp/test25519/ ### `sig.dat` under the public Ed25519 key `pub.pem`.
> λ /tmp/test25519/ ### Success is expected.
> λ /tmp/test25519/ openssl pkeyutl -verify -pubin -inkey pub.pem \
>     -rawin -in /bin/ls -sigfile sig.dat
> Signature Verified Successfully
> λ /tmp/test25519/ ### Verify the file `/bin/echo` against a signature
> λ /tmp/test25519/ ### `sig.dat` under the public Ed25519 key `pub.pem`.
> λ /tmp/test25519/ ### Failure is expected.
> λ /tmp/test25519/ openssl pkeyutl -verify -pubin -inkey pub.pem \
>     -rawin -in /bin/echo -sigfile sig.dat
> Signature Verification Failure
> ```
> 
> The updated documentation is in [this template file](https://github.com/openssl/openssl/blob/555ed96812f7f6cfb6066327aee40244517e2e05/doc/man1/openssl-pkeyutl.pod.in) and should soon be available also at https://www.openssl.org/docs/manmaster/man1/openssl-pkeyutl.html
> 
> I believe current support (even with its limits) could already be enough to close this issue.
> @parasssh do you agree?

Looks good to me. I presume it is doing the one-shot mode.

**Comment by romen** [comment]
> Looks good to me. I presume it is doing the one-shot mode.

Yes, as of this writing, using `pkeyutl` like described above is first allocating a buffer in which to copy the file contents, and then running the one-shot PureEdDSA version of Ed25519/448.

The current limitation is on the maximum file size that can be signed, and the fact that it would be nice, on platforms where it is possible to use `mmap` to prefer that to the current buffering solution.
This was discussed in #8431 and is still desirable. We should probably open an issue to track it as a separate feature request with the `help wanted` label.

**Comment by romen** [comment]
Closing this, marking it as fixed by #8431.

**Comment by romen** [comment]
Note that this is fixed in `master` (and already available in the 3.0 alpha 1 release).

We could open a separate issue (PR welcome) to discuss if this feature should be backported to 1.1.1 as well: technically we don't allow new features in patch releases, but there is room for an argument that adding this feature can be considered a bug fix.

- The feature was indeed initially available during the development cycle of 1.1.1
- It was expected to land in the release, as proven by this doc issue (#11633)
- Was removed from `pkeyutl` (#6284) after discussing an issue that is more relevant to the programming API and not really against having that functionality available in the CLI utility (#5880).

**Comment by romen** [comment]
> The current limitation is on the maximum file size that can be signed, and the fact that it would be nice, on platforms where it is possible to use `mmap` to prefer that to the current buffering solution.
> This was discussed in #8431 and is still desirable. We should probably open an issue to track it as a separate feature request with the `help wanted` label.

See #11677

**Comment by ckcr4lyf** [comment]
I would appreciate it being added to 1.1.1 

I am on:

```
$ openssl version
OpenSSL 1.1.1q  5 Jul 2022
```

And if I want to use Curve25519 for signing with Ed25519, it fails:
```
$ openssl genpkey -algorithm ed25519 -out aliceEdX.pem
$ echo hi > message.txt
$ openssl dgst -sha256 -sign aliceEdX.pem -out /tmp/sign.sha256 message.txt
Key type not supported for this operation
```

Since Ed25519 is quite popular, I think adding it to OpenSSL CLI (even 1.1.1) would be nice

**Comment by t8m** [comment]
No features are added to stable releases. That is a policy.

**Comment by hilbix** [comment]
With such a strict policy, some short example C code to create a 3.0 compatible signature with older OpenSSL would be nice.  Because this is far from obvious how to archive that (if you have no access to 3.x).
