### ISSUE TITLE
Maybe zero memory before CRYPTO_secure_malloc returns

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#6989]
This was reported by my colleague John Shriver.

```CRYPTO_secure_free()``` calls ```CLEAR()``` so that data doesn't lie around, and ```mmap()``` returns zero'd pages.

However, ```CRYPTO_secure_malloc()``` returns memory with the old linked-list data (the ```SH_LIST``` structure) still at the front of the block, which are pointers into the free list or some other recently-allocated block of memory.  This is moderately bad on read (missing detection of bug), and toxic on write (corrupted freelist or worse).

It could be done in ```sh_remove_from_list()```, setting ```temp->p_next``` to NULL unconditionally, and setting ```temp->next``` to NULL if not NULL (since it is already tested). This would add overhead to coalescing, however, which also calls ```sh_remove_from_list()```. So maybe do it in ```sh_malloc()```; this would either require casting or always do the ```memset(0)``` making it equivalent to ```CRYPTO_secure_zalloc()``` which adds overhead.

**Comment by paulidale** [comment]
Fix merged to master.
