### ISSUE TITLE
supplemental data missing check

### ISSUE THREAD

**Issue by eti1** [openssl/openssl#70]
In s3_clnt.c and s3_srvr.c, two (identical) functions are present to retreive supplemental data after certificate: tls1_get_server_supplemental_data and tls1_get_client_supplemental_data.
The length of supp data is readen with a n2l3(p, supp_data_len). 
supp_data_len is not checked against the message's length, and a data pointer located outside the buffer could be passed an argument to a srv_supp_data_records handler.
I suggest checking if supp_data_len+3 < n before the parsing loop.

edit: actually if (n<supp_data_len)

**Comment by nick599** [comment]
I could not find the referenced files: s3_clnt.c nor s3_srvr.c via searching in the OpenSSL GitHub repository. Found a few references to them though:

**s3_clnt.c** and **s3_srvr.c** appear in:
1) Netware/globals.txt 
2) ssl/ssl_sess.c 
3) ssl/statem/statem_clnt.c

Do the s3_clnt.c and s3_srvr.c files exist anymore?

**Comment by eti1** [comment]
Hello,
short answer: I have no clue.
I just remember was already totally unused two years ago, so it makes sense
that it has been removed.

**Comment by richsalz** [comment]
closing this; those functions don't exist any more and the state machine code has been rewritten.  thanks @nick599 and @eti1
