### ISSUE TITLE
Unable to compile 1.0.2p using Server 2003 PSDK x64 due to gmtime_s

### ISSUE THREAD

**Issue by winkelsdorf** [openssl/openssl#7006]
I am unable to compile for x64 using `Windows Server 2003 SP1 Platform SDK for x64, NASM and Strawberry Perl`.

**Build commands**
```
perl configure VC-WIN64A
ms\do_win64a
nmake -f ms\ntdll.mak
nmake -f ms\ntdll.mak test
```

**Output** 
pointing to the recent change of using gmtime_s function:
```
	link /nologo /subsystem:console /opt:ref /debug /dll /out:out32dll\libeay32.dll /def:ms/LIBEAY32.def @C:\Users\LOCALA~1\AppData\Local\Temp\nm71C9.tmp
   Creating library out32dll\libeay32.lib and object out32dll\libeay32.exp
o_time.obj : error LNK2019: unresolved external symbol gmtime_s referenced in function OPENSSL_gmtime
Microsoft (R) Program Maintenance Utility   Version 7.00.8882
Copyright (C) Microsoft Corp 1988-2000. All rights reserved.

NMAKE : fatal error U1077: 'link' : return code '0x460'
Stop.

out32dll\libeay32.dll : fatal error LNK1120: 1 unresolved externals
Running Test
	cl /Fotmp32dll\constant_time_test.obj -Iinc32 -Itmp32dll /MD /Ox -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_STATIC_ENGINE /Zi /Fdtmp32dll/app -c .\crypto\constant_time_test.c
constant_time_test.c
	link /nologo /subsystem:console /opt:ref /debug /dll /out:out32dll\libeay32.dll /def:ms/LIBEAY32.def @C:\Users\LOCALA~1\AppData\Local\Temp\nm8783.tmp
   Creating library out32dll\libeay32.lib and object out32dll\libeay32.exp
o_time.obj : error LNK2019: unresolved external symbol gmtime_s referenced in function OPENSSL_gmtime
out32dll\libeay32.dll : fatal error LNK1120: 1 unresolved externals
Rebase DLLs
Microsoft (R) COFF/PE Editor Version 8.00.40310.39
Copyright (C) Microsoft Corporation.  All rights reserved.

EDITBIN : fatal error LNK1104: cannot open file 'libeay32.dll'
Microsoft (R) COFF/PE Editor Version 8.00.40310.39
Copyright (C) Microsoft Corporation.  All rights reserved.

EDITBIN : fatal error LNK1104: cannot open file 'ssleay32.dll'

C:\OpenSSL\Temp\openssl-1.0.2p-x64\out32dll>
Microsoft (R) Program Maintenance Utility   Version 7.00.8882
Copyright (C) Microsoft Corp 1988-2000. All rights reserved.

NMAKE : fatal error U1077: 'link' : return code '0x460'
Stop.
```

Likely related to #5719.

**Comment by dot-asm** [comment]
Oh! I seem to recall that unlike regular MSVC installations, PSDK is linking with system32\msvcrt.dll. I mean regular MSVC customarily come with version-specific run-time dll, while PSDK uses one shipped with Windows itself. Is this correct recollection? Unfortunately there is no [reliable] way to tell if we are looking at custom dll or default one at compile time. Relevant question is how wide-spread PSDK compiler is. I mean are users more likely to use regular MSVC or PSDK? I'd guess former.., What you can do is to bump expected version to 1500 to get pass it, but it probably won't make to the repository...

**Comment by dot-asm** [comment]
It should also be possible to work around the problem by passing -D_MSC_VER=1300 as additional argument at config time. Either way, it's "won't fix" thing, so closing...

**Comment by winkelsdorf** [comment]
@dot-asm Hi Andy! Late feedback, holiday season. Thank you for your quick help, yes you're absolutely correct about PSDK. It is linking to `system32\msvcrt.dll`, thus removing dependencies to the usual runtime collection of MSVC.

I've double checked with the corresponding versions and from what I can tell I agree that there is no other reliable way to determine if the PSDK is used to compile. The compiler itself is MSVC, but some adjustments are made to point it to the platform library.

This said, of course does the -D_MSC_VER override work, thanks for pointing towards it! 💯 I agree to closing it was "won't fix" after your clarification.

As previous versions compiled without adjustment I would probably add a single line note to the WIN compile docs pointing to the configuration switch as some might oversee it like I did.

**Comment by noskill24** [comment]
I have the same problem and found this topic.
So, how can I pass `-D_MSC_VER=1300` argument to a Perl script?

    perl configure VC-WIN64A
    ms\do_win64a
    nmake -f ms\ntdll.mak
    nmake -f ms\ntdll.mak test

**Comment by t8m** [comment]
`perl configure VC-WIN64A -D_MSC_VER=1300`

**Comment by noskill24** [comment]
Another question:
Most of libraries in the Platform SDK have been built with /GS switch. So if we use compiler that doesn't automatically injects buffer overrun code, then we need explicitly specify `/GS` flag and "bufferoverflowU.lib" as additional library to link.
So how to specify `/GS` switch for the compiler, and "bufferoverflowU.lib" as additional library to link?

**Comment by noskill24** [comment]
Another question:
Most of libraries in the Platform SDK have been built with /GS switch. So if we use compiler that doesn't automatically injects buffer overrun detection, then we need explicitly specify /GS flag and bufferoverflowU.lib as additional library to link.
So how to specify /GS switch for the compiler, and bufferoverflowU.lib as additional library to link?

**Comment by noskill24** [comment]
Another question:
Most of libraries in the Platform SDK have been built with `/GS` switch. So if we use compiler that doesn't automatically injects buffer overrun detection, then we need explicitly specify `/GS` flag and `bufferoverflowU.lib` as additional library to link.
So how to specify `/GS` switch for the compiler, and `bufferoverflowU.lib` as additional library to link?

**Comment by noskill24** [comment]
Another question:
Most of libraries in the Platform SDK have been built with `/GS` switch. So if we use compiler that doesn't automatically injects buffer overrun detection, then we need explicitly specify `/GS` flag and `bufferoverflowU.lib` as additional library to link.

So how to specify `/GS` switch for the compiler?

And how to add extra libraries to link?

I tried to do this as the documentation says:
`perl configure -LbufferoverflowU.lib`

but this will result an invalid output:
EX_LIBS=-LbufferoverflowU.lib ws2_32.lib gdi32.lib advapi32.lib crypt32.lib user32.lib
