### ISSUE TITLE
File descriptor leak of random devices in 1.1.1-pre9

### ISSUE THREAD

**Issue by bwelling** [openssl/openssl#7022]
This is new in -pre9, and is related to the persistent random device changes.

On shutdown, OPENSSL_cleanup() calls rand_cleanup_int(), which calls rand_pool_cleanup() followed by RAND_set_rand_method(NULL).

If nothing has ever used random numbers before, the 
rand_pool_cleanup() call does nothing, as there's nothing to clean up, but the RAND_set_rand_method(NULL) call will then execute the RUN_ONCE(&rand_init, do_rand_init), as it's never been called before, which will open the random devices.  Nothing will ever close them, as rand_pool_cleanup() has already been called.

**Comment by mspncp** [comment]
@bwelling thanks for reporting this issue. Please try #7023 and check whether it fixes the problem.

**Comment by mspncp** [comment]
And thanks for providing a complete analysis of the problem. Almost nothing left to do :-)

**Comment by bwelling** [comment]
Yes, that fixes the problem.  Thanks!

**Comment by mspncp** [comment]
@bwelling #7023 is being revised by #7588. Would you mind checking again with #7588?
