### ISSUE TITLE
Check OpenSSL version in runtime

### ISSUE THREAD

**Issue by davidskiff** [openssl/openssl#7024]
Hi,
Our product need to integrate with both OpenSSL v1.0.2 and v1.1.0.
SSLeay_version() available for v1.0.2, but was replace with OpenSSL_version() in v1.1.0.

In order to have same product sources (without #ifdef macro per OpenSSL version), I would like to know how it`s possible to check OpenSSL version in **runtime** in a uniform way for both?

Thanks,
David.

**Comment by mattcaswell** [comment]
1.0.2 and 1.1.0 are not source or binary compatible with each other. Therefore your product will need to be built to target one or the other at *compile* time. At a source level `SSLeay_version()` still exists in 1.1.0, but as a macro for `OpenSSL_version()` so you don't (necessarily) have to make source level changes to support this - but you still need to know at compile time which of the two versions you are targetting.

**Comment by shivbindas** [comment]
Hi Matt, 
I am also facing one issue while compiling my discache on RHEL8 which comes with openssl 1.1.1b
while compiling it i am seeing below error :

./configure --prefix=/home/sgarg/rpmbuild/SOURCES/distcache
checking for SSL/TLS toolkit base... none
checking openssl/opensslv.h usability... yes
checking openssl/opensslv.h presence... yes
checking for openssl/opensslv.h... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for OpenSSL version... OK
checking for OpenSSL ENGINE support... yes
checking for SSLeay_version in -lcrypto... no
checking for SSL_CTX_new in -lssl... yes
configure: error: ... Error, SSL/TLS libraries were missing or unusable
configure: error: /bin/sh './configure' failed for ssl


Can you please help me here ?

 openssl version -a
OpenSSL 1.1.1 FIPS  11 Sep 2018
built on: Fri Dec 14 14:00:55 2018 UTC
platform: linux-x86_64
options:  bn(64,64) md2(char) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific
engines:  rdrand dynamic

**Comment by t8m** [comment]
The configure check needs to include crypto.h. Does it?

**Comment by shivbindas** [comment]
where i can check that crypto.h is included or not ?

**Comment by shivbindas** [comment]
My compilation is working absolutely fine with openssl1.0.2k while its failing for 1.1.1b version only. i hope something is missing from openssl 1.1.1b version side

**Comment by mattcaswell** [comment]
Please don't add different issues onto the end of a closed issue. I see you have opened #9790 which is the correct place to ask for help on this issue.
