### ISSUE TITLE
asynctest fails on Linux under ia64

### ISSUE THREAD

**Issue by jduerstock** [openssl/openssl#7030]
On Linux/ia64, the 1.1.1-pre9 test suite fails on asynctest:

```
../../test/recipes/90-test_async.t .................... 
1..1
test_ASYNC_init_thread() failed
../../util/shlib_wrap.sh ../../test/asynctest => 1
not ok 1 - running asynctest

#   Failed test 'running asynctest'
#   at /<<PKGBUILDDIR>>/build_static/test/../../util/perl/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
```

(The full build log is here: https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=ia64&ver=1.1.1~~pre9-1&stamp=1534883907&raw=0 )

**Comment by kroeckx** [comment]
I'm not convinced this is an openssl issue. This is most likely an
IA64 specific issue in the toolchain.

This test started breaking between 1.1.0g-2
(https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=ia64&ver=1.1.0g-2&stamp=1515524924&raw=0)
and 1.1.0g-2+b1
(https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=ia64&ver=1.1.0g-2%2Bb1&stamp=1516763329&raw=0)
So the source did not change, but it broke.

**Comment by mattcaswell** [comment]
Appears to not be an OpenSSL issue so closing this.
