### ISSUE TITLE
speed rejects most digest/cipher algorithms as unknown

### ISSUE THREAD

**Issue by mpeylo** [openssl/openssl#7032]
Contrary to what the _speed_ manpage suggests, the _openssl speed_ app does not take all the digests/ciphers as outputted by _list -digest-commands_ and _list -cipher-commands_. Those algorithms which do not work if given explicitly seem also to be omitted when no algorithm option is given, and the "pre-compiled grand selection is tested".

Digests supported by _speed_ are e.g. md4, md5, sha1, sha256

Verified with recent master (OpenSSL 1.1.1-pre10-dev) and 1.1.0f

Issue #6922 appears to be somewhat related, while the EdDSA signatures (even the working ecdhx25519) mentioned there might not be neither referenced explicitly by the speed man page nor do they seem to be retrievable by any of the mentioned _list_ options.

To reproduce, in Bash, do:
$ for alg in \`openssl list -digest-commands\`; do openssl speed $alg 2>&1 | grep Unknown; done
speed: Unknown algorithm blake2b512
speed: Unknown algorithm blake2s256
speed: Unknown algorithm gost
speed: Unknown algorithm sha224
speed: Unknown algorithm sha3-224
speed: Unknown algorithm sha3-256
speed: Unknown algorithm sha3-384
speed: Unknown algorithm sha3-512
speed: Unknown algorithm sha384
speed: Unknown algorithm sha512-224
speed: Unknown algorithm sha512-256
speed: Unknown algorithm shake128
speed: Unknown algorithm shake256
speed: Unknown algorithm sm3

$ for alg in \`openssl list -cipher-commands\`; do openssl speed $alg 2>&1 | grep Unknown; done
speed: Unknown algorithm aes-128-ecb
speed: Unknown algorithm aes-192-ecb
speed: Unknown algorithm aes-256-ecb
speed: Unknown algorithm aria-128-cbc
speed: Unknown algorithm aria-128-cfb
speed: Unknown algorithm aria-128-cfb1
speed: Unknown algorithm aria-128-cfb8
speed: Unknown algorithm aria-128-ctr
speed: Unknown algorithm aria-128-ecb
speed: Unknown algorithm aria-128-ofb
speed: Unknown algorithm aria-192-cbc
speed: Unknown algorithm aria-192-cfb
speed: Unknown algorithm aria-192-cfb1
speed: Unknown algorithm aria-192-cfb8
speed: Unknown algorithm aria-192-ctr
speed: Unknown algorithm aria-192-ecb
speed: Unknown algorithm aria-192-ofb
speed: Unknown algorithm aria-256-cbc
speed: Unknown algorithm aria-256-cfb
speed: Unknown algorithm aria-256-cfb1
speed: Unknown algorithm aria-256-cfb8
speed: Unknown algorithm aria-256-ctr
speed: Unknown algorithm aria-256-ecb
speed: Unknown algorithm aria-256-ofb
speed: Unknown algorithm base64
speed: Unknown algorithm bf-cfb
speed: Unknown algorithm bf-ecb
speed: Unknown algorithm bf-ofb
speed: Unknown algorithm camellia-128-cbc
speed: Unknown algorithm camellia-128-ecb
speed: Unknown algorithm camellia-192-cbc
speed: Unknown algorithm camellia-192-ecb
speed: Unknown algorithm camellia-256-cbc
speed: Unknown algorithm camellia-256-ecb
speed: Unknown algorithm cast5-cbc
speed: Unknown algorithm cast5-cfb
speed: Unknown algorithm cast5-ecb
speed: Unknown algorithm cast5-ofb
speed: Unknown algorithm des-cfb
speed: Unknown algorithm des-ecb
speed: Unknown algorithm des-ede
speed: Unknown algorithm des-ede-cbc
speed: Unknown algorithm des-ede-cfb
speed: Unknown algorithm des-ede-ofb
speed: Unknown algorithm des-ede3-cbc
speed: Unknown algorithm des-ede3-cfb
speed: Unknown algorithm des-ede3-ofb
speed: Unknown algorithm des-ofb
speed: Unknown algorithm des3
speed: Unknown algorithm desx
speed: Unknown algorithm idea-cfb
speed: Unknown algorithm idea-ecb
speed: Unknown algorithm idea-ofb
speed: Unknown algorithm rc2-40-cbc
speed: Unknown algorithm rc2-64-cbc
speed: Unknown algorithm rc2-cfb
speed: Unknown algorithm rc2-ecb
speed: Unknown algorithm rc2-ofb
speed: Unknown algorithm rc4-40
speed: Unknown algorithm seed-cfb
speed: Unknown algorithm seed-ecb
speed: Unknown algorithm seed-ofb
speed: Unknown algorithm sm4-cbc
speed: Unknown algorithm sm4-cfb
speed: Unknown algorithm sm4-ctr
speed: Unknown algorithm sm4-ecb
speed: Unknown algorithm sm4-ofb

**Comment by paulidale** [comment]
I suspect the solution here is to change the documentation so that the `-evp` is mentioned as being required for such algorithms.

**Comment by mpeylo** [comment]
Sounds like a reasonable way forward. I confirmed that nearly everything given by `list` works with `-evp` in a recent build based on master, besides:
- " base64 is an unknown cipher or digest"
- "gost is an unknown cipher or digest"

**Comment by mpeylo** [comment]
Note: I created pull request #7051 to add non-evp sha224 and sha384 to speed. Their absence was the trigger for me realizing this. Changes do not include this larger, high-level documentation fix so I didn't reference this issue.

**Comment by darakian** [comment]
I'm also hitting this on openssl 1.1 installed via homebrew
```
jon~❯❯❯ openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by levitte** [comment]
We should really have `openssl speed` assume `-evp` and be done with it.  An increasing number of algorithms will only be accessible that way anyway.

**Comment by darakian** [comment]
Out of curiosity, what does the `-evp` flag do?

**Comment by richsalz** [comment]
It uses the EVP API like ```EVP_EncryptUpdate``` to call crypto functions, as opposed to hardwired functions like ```AES_cbc_encrypt``` which are deprecated and less efficient (less assembly stuff, for example).

The next release will only support FIPS through the EVP API.

**Comment by darakian** [comment]
Gotcha. Thanks!

**Comment by levitte** [comment]
Er, less assembly stuff? Where did you get that from?

**Comment by richsalz** [comment]
my recollection is that the legacy API's don't always engage the optimized assembler (e.g., AESNI).  is that wrong?
