### ISSUE TITLE
Unable to connect to server with TLSv1.3 running OpenSSL 1.1.1-pre9 on Nginx 1.15.2

### ISSUE THREAD

**Issue by PikachuEXE** [openssl/openssl#7036]
Browsers used in tested:
- Firefox 61.0.2 (64-bit)
- Chrome Version 68.0.3440.106 (Official Build) (64-bit) (1.3 enabled with draft 28)
OS: macOS 10.13.6

I was able to connect with TLSv1.3 with all of above browsers to a server 
running OpenSSL 1.1.1-pre8 (not 9) on Nginx 1.15.2

**Comment by mattcaswell** [comment]
pre-9 support RFC TLSv1.3 only (not draft 28). That is most likely the issue.

**Comment by PikachuEXE** [comment]
Any other way to test the server with RFC TLSv1.3?

**Comment by mattcaswell** [comment]
You could use the `openssl s_client` command to do that.

**Comment by nollijimayu** [comment]
me, too
RFC TLSv1.3 work Chrome canary use!! (Ver 70.0.3530.0)
I have not found any other browsers yet.

**Comment by mattcaswell** [comment]
Closing this as there is nothing for OpenSSL to do.
