### ISSUE TITLE
Some __FILE__/__LINE__ macros remain when building with new `no-filenames` option

### ISSUE THREAD

**Issue by vszakats** [openssl/openssl#704]
After 3ba84717a0ac76785935efcca50ab80e1e2f5564, the new `no-filenames` option leaves a few source filenames and line numbers embedded in the binaries, via these files:
* include/openssl/crypto.h
* engines/e_dasync_err.h

Is this intended or something to be fixed?

/cc @dwmw2

**Comment by richsalz** [comment]
if you have a PR, we don't need an issue.  too many things to track :)

**Comment by vszakats** [comment]
Wanted to get a yay/nay first on whether this is intentional or an oversight. Sided on 'oversight' later to move along, but still being unsure how it is regarded by committer.

It seems assessment was correct, let's migrate to the PR!

**Comment by dwmw2** [comment]
Apologies for delay; I'm not always receiving github mail notification. Yes, it was an oversight. This patch has been rebased for quite some time, and new instances of `__FILE__`/`__LINE__` were missed in the process. Sorry about that.

**Comment by vszakats** [comment]
No worries, thank you for your confirmation @dwmw2.
