### ISSUE TITLE
Use only high level APIs in the `speed` app

### ISSUE THREAD

**Issue by romen** [openssl/openssl#7053]
*From the discussion in #7051 ~~~, and recurring replies on misperceived performance regressions/comparisons issues~~~.*

For applications developers and users, using `speed` in its current state can actually be misleading: applications should always go through the `EVP` API (or other future high level APIs), so making performance evaluations based on the benchmarks of the raw algorithm underneath, without accounting for the rest of operations performed at the `EVP` level -- which in most cases even application developers willing to use the raw crypto implementations should also implement on their own -- can actually lead to wrong assumptions.

From this perspective I would rather prefer, **for a future release**, to have the public `speed` app always going through the high level APIs and strip out the raw crypto benchmarks to a private test utility.

**Comment by dot-asm** [comment]
> recurring replies on misperceived performance regressions/comparisons issues.

Recurring? All recent ones had nothing to do with that... I recall internal[!] question from quite a while ago about some of the algorithms that turned to be EVP vs. non-EVP issue, but that's about it... Or maybe you are talking about aes vs. -evp aes, when only -evp goes for AES-NI (or equivalent on other platforms). Is this it? Note that it's just *one* issue, and it's not about regression :-)

Anyway, as already said, it's not like it makes no sense to remove raw interface calls, yet it's not given that providing at least some raw options would be unreasonable. On certain level speed results are always a bit misleading. As any dedicated benchmark. One can say that they tell rather about processor than real-life application. One can also say that speed is rather about developer comparing application performance with speed results and identifying hot spots in application. Well, this is not exactly argument in favour of raw calls. No. But point is rather that one doesn't have to be rigid about speed.c, there is some room for inconsistencies. It might become more apparent if one puts it like this. Suggestion is limit speed to -evp and move raw to separate internal, non-installable utility. But why not make *whole* speed separate and non-installtable? ;-)

**Comment by levitte** [comment]
> But why not make *whole* speed separate and non-installtable? ;-)

I actually like that idea

**Comment by romen** [comment]
> Recurring? All recent ones had nothing to do with that... I recall internal[!] question from quite a while ago about some of the algorithms that turned to be EVP vs. non-EVP issue, but that's about it... Or maybe you are talking about aes vs. -evp aes, when only -evp goes for AES-NI (or equivalent on other platforms). Is this it? Note that it's just one issue, and it's not about regression :-)

@dot-asm You got me! :)
"Recurring" might be too strong a word. When I wrote that I had these 2 in mind:
- https://github.com/openssl/openssl/issues/6396#issuecomment-394511377
- https://github.com/openssl/openssl/issues/6512#issuecomment-398224744

**Comment by FdaSilvaYY** [comment]
Kind of SRS for `speed` : https://github.com/openssl/openssl/issues/7278#issuecomment-423746970

**Comment by t8m** [comment]
This is now resolved on master.
