### ISSUE TITLE
Self signed certificates generated by "req -x509" always have [ v3_ca ] extensions added to them

### ISSUE THREAD

**Issue by rogerjames99** [openssl/openssl#7055]
When using the current default config openssl.cnf any self signed certificates generated using "openssl req -x509" have the x509v3 extensions defined in the [ v3_ca ] section of the default config file added to them.

With the current default config file this results in the following extensions being added.

subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer
basicConstraints = critical,CA:true

These are added irrespective of whether the self signed certificate is for a ca.

This is wrong and causes problems with the mobile version of the firefox browser. It may cause problems with other browsers. I have not tested any others.

This bug can be verified merely by looking at the current default openssl.cnf file.

**Comment by InfoHunter** [comment]
I don't quite understand why this is a problem. If the default configuration file is not fit for the scenario, then why not customize one to fit it?

**Comment by rogerjames99** [comment]
On 30 August 2018 04:02:41 Paul Yang <notifications@github.com> wrote:
> I don't quite understand why this is a problem. If the default 
> configuration file is not fit for the scenario, then why not customize one 
> to fit it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
Hi Paul,

The problem is that it is the default!

It makes the assumption that all self signed certificates are to be marked 
as top level internet CA certificates for use as trust anchors in the 
global pki. In reality this is a very rare use case. The most common use 
case for self signed certificates is as basic x509 certificates in a 
private trust environment. For example as a server host certificate for a 
web based configuration gui in an embedded device such as a home router.

Putting TLS 1.3 x509v3 extensions in a certificate causes problems in some 
browsers that can prevent them from adding private self signed certificates 
as exceptions.

**Comment by levitte** [comment]
Actually, using self signed certificates as EE certificates is a conceptual misuse.
However, if that's what you want to do, the `openssl x509` command has the capacity to create self signed v1 certs...

**Comment by rogerjames99** [comment]
On 30 August 2018 10:18:37 Richard Levitte <notifications@github.com> wrote:
> Actually, using self signed certificates as EE certificates is a conceptual 
> misuse.
> However, if that's what you want to do, the openssl x509 command has the 
> capacity to create self signed v1 certs...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Hi Richard,

Can you expand on your conceptual misuse statement. I am interested to know 
why you think an end entity x509 certificate cannot be self signed. Are you 
talking in pki terms or x509 terms.

Cheers,

Roger

**Comment by rogerjames99** [comment]
On 30 August 2018 10:18:37 Richard Levitte <notifications@github.com> wrote:
> Actually, using self signed certificates as EE certificates is a conceptual 
> misuse.
> However, if that's what you want to do, the openssl x509 command has the 
> capacity to create self signed v1 certs...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Mea culpa. Please ignore my previous message. I realise now that using 
"openssl req -x509" is really saying that you want a CA root cert 
generated, and that we should be using "openssl x509 -req" to generate a 
self signed cert. I will close this bug. Once again my apologies. My only 
suggestion is that the assumption that is going to be a root cert could be 
made clearer in the docs.

Roget
