### ISSUE TITLE
Memory Leak bug in ssl/s3_lib.c 4554  (4606)

### ISSUE THREAD

**Issue by fangang190** [openssl/openssl#7060]
Hi, we find a memory leak bug in ssl/s3_lib.c 4554 (4606 in current version). 
This bug happens when the program taking true branch at line 4569 and goto the err label. 

There is no free operation in the err section. 

![image](https://user-images.githubusercontent.com/1679432/44646413-6aecca00-aa0d-11e8-9114-2cccf48066e7.png)

GF
Sourcebrella

**Comment by mattcaswell** [comment]
Yes, looks like we need to free `pskpms` in the event that the `generate_master_secret` call fails
