### ISSUE TITLE
Memory leak bug in apps/s_server.c: 3330

### ISSUE THREAD

**Issue by fangang190** [openssl/openssl#7061]
Hi, 

We find a memory leak bug in apps/s_server.c 3294 (3330 in the most recent version). The variable **con** is not released when taking the "err" goto statement at line 3305. 

![image](https://user-images.githubusercontent.com/1679432/44646561-03834a00-aa0e-11e8-95f3-084b77dbe667.png)

GF
Sourcebrella

**Comment by mattcaswell** [comment]
Yes, looks like we need to free `con` in both `www_body` and `rev_body`
