### ISSUE TITLE
Error #2F067065 - "ess signing certificate error" when validating timestamp reply 

### ISSUE THREAD

**Issue by Gigaju** [openssl/openssl#7062]
Hi,

I get an error when I try to validate a RFC3161-compliant timestamp reply.
The reply can be validated with an application using BouncyCastle.
This bug was also present in OpenSSL 1.0.1 as mentioned in #2473 .

Here is my environment:
```
# Distrib info
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

# OpenSSL info
OpenSSL 1.1.0g  2 Nov 2017
built on: reproducible build, date unspecified
platform: debian-amd64
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\"" 
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
```

Steps to reproduce:
```
# Query generation
$ openssl ts -query -data /etc/passwd -sha256 -out query.tsr

# Here is the query
$ openssl ts -query -text -in query.tsq 
Using configuration from /usr/lib/ssl/openssl.cnf
Version: 1
Hash Algorithm: sha256
Message data:
    0000 - 85 26 8f fc df fc 8f 54-ea d0 04 88 02 35 53 c1   .&.....T.....5S.
    0010 - 06 4b d9 7f 04 ed e4 11-a1 dc 99 12 4c e9 ac 54   .K..........L..T
Policy OID: unspecified
Nonce: 0x985B3170CE7DEED8
Certificate required: no
Extensions:

# Send it to the server - PrimeKey SignServer 4.0.0
$ cat query.tsq | curl -H 'Content-Type: application/timestamp-query' --cacert ca-tls.pem https://signserver.my.domain:8442/signserver/tsa?workerName=TimeStampSigner --data-binary @- -o reply.tsr

# Here is the reply
$ openssl ts -reply -in reply.tsr -text
Using configuration from /usr/lib/ssl/openssl.cnf
Status info:
Status: Granted.
Status description: Operation Okay
Failure info: unspecified

TST info:
Version: 1
Policy OID: [confidential - scrapped]
Hash Algorithm: sha256
Message data:
    0000 - 85 26 8f fc df fc 8f 54-ea d0 04 88 02 35 53 c1   .&.....T.....5S.
    0010 - 06 4b d9 7f 04 ed e4 11-a1 dc 99 12 4c e9 ac 54   .K..........L..T
Serial number: 0x2D26E0730ABDDD1B
Time stamp: Aug 23 14:19:52 2018 GMT
Accuracy: 0x01 seconds, unspecified millis, unspecified micros
Ordering: no
Nonce: 0x985B3170CE7DEED8
TSA: [confidential - scrapped: same info as my TSA cert for sure]
Extensions:

# This is when it gets weird
$ openssl ts -verify -in query.tsr -CAfile tsa-ca.pem -untrusted tsa.pem -queryfile query.tsq 
Using configuration from /usr/lib/ssl/openssl.cnf
Verification: FAILED
140401657303488:error:2F067065:time stamp routines:ts_check_signing_certs:ess signing certificate error:../crypto/ts/ts_rsp_verify.c:230:
```

I can't attach reply ASN.1 for confidentiality issues but if it is really needed I can reproduce these steps in a test environment with no private info and then send the reply.

Thanks !

**Comment by pepito4** [comment]
Hi Gigaju,

I ran into the same issue while working with dfn.de TSA. This happens when your TSA is working with the SHA256withRSAEncryption algorithm.
Support has been added in the pull request #771 , but it is not included in openssl 1.1.0. It is included in openssl 1.1.1 pre-release though. 
I downloaded this version, compiled it and timestamp verification worked fine for me.
Hope this helps you.

**Comment by H3llK33p3r** [comment]
I have a similar issue when the timestamp response contains an EssCertIdv2 as described in the RFC and to be compliant with ETSI. Does someone have already verify a timestamp response with and EssCertIdv2 ?

**Comment by FdaSilvaYY** [comment]
@H3llK33p3r : take a look at #14503 and related, it has fix some issues related to EssCertIdv2.

**Comment by H3llK33p3r** [comment]
Thank for the response @FdaSilvaYY , after more investigation it seems that my issue is related to the EssCertIdv2 issuerSerial. 

I have no issue with my server returning the v1 (no general names included in issuer serial). 

With EssCertIdv2, the verify fails when issuer serial is set (this part is optionnal according to rfc5035). So either the serial number has an issue or the general names. I will perform additionnal tests.

**Comment by t8m** [comment]
The ess cert id handling should be fixed on current master. Closing. Please open new issues if you still see problems with ess handling in the current 3.0 prereleases.

**Comment by H3llK33p3r** [comment]
Ok thanks, the issue was related to the RFC (on my side only) and the order of the general names element. 

```
issuer
      contains the issuer name of the certificate.  For non-attribute certificates, the issuer MUST contain only the issuer name from
      the certificate encoded in the directoryName choice of GeneralNames.  For attribute certificates, the issuer MUST contain
      the issuer name field from the attribute certificate.
```

Sorry for the inconvenience.

**Comment by t8m** [comment]
> Sorry for the inconvenience.

No problem.
