### ISSUE TITLE
I want the so names as libssl32.so.1.1 and libcrypto32.so.1.1 for 32-bit

### ISSUE THREAD

**Issue by pams189** [openssl/openssl#7064]
We need to use both 64-bit and 32-bit ssl and crypto so files in the same location in Red Hat Linux and it's creating problem because both 64-bit and 32-bit builds have same names. So while building the 32-bit so files if i get the names as libssl32.so.1.1 and libcrypto32.so.1.1 will resolve the problem for me. Please guide me to build the same in Linux.

Thanks,
DASARI PAMULETI
pams189@gmail.com

**Comment by levitte** [comment]
The easiest way to do this is to create a configuration target collection of your own (in a location that you point out with the environment variable `OPENSSL_LOCAL_CONFIG_DIR`, or in the source tree `Configurations`) named something ending with `.conf`, where you inherit from existing configs and modify the attributes `multilib` and `shlib_variant`, like this:

```
%targets = (
    "linux-x86-32" => {
        inherit_from => [ 'linux-elf' ],
        multilib => '',
        shlib_variant => '32',
    },
    "linux-x86_64-64" => {
        inherit_from => [ 'linux-x86_64' ],
        multilib => '',
        shlib_variant => '64',
    },
);
```

You won't get those targets automatically selected by `./config`, but if you use them directly with `./Configure`, I think you'll get what you want, or something close to that.

**NOTE:** *this is top of my head, I haven't tested this, please try that out and tell us if you got what you wanted or not*

... also, you have to make sure to use a pretty up to date 1.1.0 version if you're not building from the master branch.

**Comment by bbbrumley** [comment]
+1 for custom configs. Did not test above out, but @dot-asm educated me in #6206.

**Comment by pams189** [comment]
Hi,

Thanks for your quick reply on this. I tested the scenario mentioned, i
created the .conf file with the targets given but still it is giving names
as  libssl.so.1.1 and libcrypto.so.1.1.

After creating the pams.conf file and i ran as follows.
./Configure linux-x86-32 -shared -m32 --config=pams.conf
make

Please let me know did i ran anything wrong above?

Thanks,
DASARI

**Comment by romen** [comment]
I think it should be ` ./Configure <nameOfYourCustomTarget> -shared -m32 --config=pams.conf`.

Where `<nameOfYourCustomTarget>` is whatever name you setup in your `pams.conf`

**Comment by pams189** [comment]
I have created the pams.conf as follows
%targets = (
    "pams-32" => {
        inherit_from => [ 'linux-elf' ],
        multilib => '',
        shlib_variant => '32',
    }
);

And i ran the configure as follows
 ./Configure pams-32 -shared -m32 --config=pams.conf

Still so names same libssl.so.1.1 and libcrypto.so.1.1 i need the so names as libssl32.so.1.1 and libcrypto32.so.1.1.

**Comment by romen** [comment]
I'm definitely not an expert on this: have you tried using exactly the lines @levitte suggested?

**Comment by bbbrumley** [comment]
@pams189 works for me ...

```
bbrumley@arizona:~/svnrepos/openssl_github$ cat Configurations/90-bbbrumley.conf 
my %targets = (
    "linux-x86-32" => {
        inherit_from => [ 'linux-elf' ],
        multilib => '',
        shlib_variant => '32',
    },
    "linux-x86_64-64" => {
        inherit_from => [ 'linux-x86_64' ],
        multilib => '',
        shlib_variant => '64',
    }
);
bbrumley@arizona:~/svnrepos/openssl_github$ ./Configure linux-x86-32 -shared -m32
Configuring OpenSSL version 1.1.1-pre10-dev (0x1010100aL) for linux-x86-32
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   If you want to report a building issue, please include the   ***
***   output from this command:                                    ***
***                                                                ***
***     perl configdata.pm --dump                                  ***
***                                                                ***
**********************************************************************
bbrumley@arizona:~/svnrepos/openssl_github$ make -j8

...

make[1]: Leaving directory '/home/bbrumley/svnrepos/openssl_github'
bbrumley@arizona:~/svnrepos/openssl_github$ ls -1 lib*
libcrypto32.so.1.1
libcrypto.a
libcrypto.map
libcrypto.pc
libcrypto.so
libssl32.so.1.1
libssl.a
libssl.map
libssl.pc
libssl.so
bbrumley@arizona:~/svnrepos/openssl_github$ 
```

**Comment by romen** [comment]
Here is the [relevant documentation](https://github.com/openssl/openssl/blob/master/Configurations/README).

After reading it, it looks like your configuration should be working as well. 

What version of OpenSSL are you trying to build exactly? Is it an unmodified release tarball/git clone or are you (or your distribution vendor) applying some patches? 
Have you made sure you are running `./Configure` in a clean state? Or there might be previous build attempts/ccache or similar things altering the build?

**Comment by pams189** [comment]
Hi,

i am using the openssl 1.1.0f version is that causing the issue do i need to use the latest one to make it work for me?

**Comment by pams189** [comment]
I verified the same in 1.1.1-pre9 it is working i am able to get libssl32.so.1.1 and libcrypto32.so.1.1. So the suggestion will work only in 1.1.1 releases but my product works on 1.1.0f is there any way i get the same in 1.1.0f version?

**Comment by levitte** [comment]
Ah, 110f is fairly old in this regard. It was released in May last year, and `shlib_variant` support was added this year. So to be able to do what you want, you need to do it from a fresher 1.1.0 release.

**Comment by pams189** [comment]
Verified the same in 1.1.0h and able to get libssl32.so.1.1 and libcrypto32.so.1.1. Thanks Everyone for your quick response and resolving it for me.

**Comment by levitte** [comment]
Great!
