### ISSUE TITLE
File Operations in OpenSSL

### ISSUE THREAD

**Issue by pranavabhat** [openssl/openssl#7076]
Hi All,

Could you please let us know an way to load CA Lists to SSL CTX in the form of ASN1 encoder buffer[DER] (i.e. without using SSL_CTX_load_verify_locations)?

By default, SSL_CTX_load_verify_locations is using the path and file handling.
As we don't want to use file system for SSL operations, Need to load the ASN1 encoder buffer[DER] as a CA List to SSL CTX.

Thanks in Advance

**Comment by JohnAZoidberg** [comment]
There is SSL_CTX_set_cert_store() with which you can set a custom X509_STORE.

```c
X509 *root_cert = d2i_X509(NULL, &buffer, buffer_len);

X509_STORE *store = X509_STORE_new();
X509_STORE_add_cert(store, root_cert);
SSL_CTX_set_cert_store(ctx, store);
```
I haven't tested this exact code and it doesn't contain error checks or cleanup but should give you a pretty good idea of how to achieve what you want. Now that you know which functions to use their manpages can help you further.

**Comment by levitte** [comment]
> This shouldn't really be an issue but a question on the openssl-users mailing list.

Agreed.  Closing this.
