### ISSUE TITLE
RSA signature regression issue in openssl 1.0.2p

### ISSUE THREAD

**Issue by tudu123** [openssl/openssl#7077]
Client application uses openssl 1.0.2p to connect to server and got the ssl error during TLS handshake, the issue doesn't repro in 1.0.2o.

Root cause is below:

// openssl\src\crypto\rsa_sign.c
int RSA_sign(int type, const unsigned char *m, unsigned int m_len,
             unsigned char *sigret, unsigned int *siglen, RSA *rsa)
{
   ...
   /*
    * Before OpenSSL 1.0.2P, below if statement is checking the RSA_FLAG_SIGN_VER
    * with rsa->flags. If the flag is set by application, then the callback API
    * rsa_sign will be called to allow application/hardware has opportuiny to do
    * the RSA signature. But with the latest 1.0.2P, it is checking the flag from
    * rsa->meth. This is a regression issue and may cause rsa_sign callback is not
    * called any more. I see there is a way to change the upper application/hardware
    * to re-set the flag again in rsa->meth, but please keep OpenSSL has a better
    * backward compatibility to not rely on the changes in application/hardward layer.
    */
    if ((rsa->meth->flags & RSA_FLAG_SIGN_VER) && rsa->meth->rsa_sign) {
        return rsa->meth->rsa_sign(type, m, m_len, sigret, siglen, rsa);
    }

**Comment by tudu123** [comment]
Any update?  It should be related to code change https://github.com/openssl/openssl/pull/5971

**Comment by t8m** [comment]
1.0.2 releases are not supported anymore. Closing.
