### ISSUE TITLE
Poly1305 error with asm on linux-armv4

### ISSUE THREAD

**Issue by shigeki** [openssl/openssl#708]
Poly1305 with asm on linux-armv4 (Raspbian GNU/Linux 8 on raspberry pi2) seems to have an issue that it cannot calculate a correct MAC in a certain condition. `make test` shows the error as
```txt
Test Summary Report
-------------------
../test/recipes/30-test_evp.t           (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=68, Tests=361, 276 wallclock secs ( 3.94 usr  0.52 sys + 233.18 cusr 12.35 csys = 249.99 CPU)
Result: FAIL
Failed 1/68 test programs. 1/361 subtests failed.
````
and they are two tests for chacha20-poly1305.
```txt
ohtsu@raspberrypi:~/github/openssl$ ./test/evp_test test/evptests.txt
Test line 2958: unexpected error TAG_VALUE_MISMATCH
Expected: 1AE10B594F09E26A7E902ECBD0600691
Got:      0AE1D6731075D9EB2A9375783ED553FF
Test line 2966: unexpected error TAG_VALUE_MISMATCH
Expected: EEAD9D67890CBB22392336FEA1851F38
Got:      26478F50C054F563DBC0A21E261572AA
451 tests completed with 2 errors, 0 skipped
````
The errors come from Poly1305 as I made self tests with `POLY1305_ASM`. Some tests of self generated and one test from RFC7539 of  "5*H+L reduction intermediate" are failed.
```txt
ohtsu@raspberrypi:~/github/openssl/crypto/poly1305$ gcc -o poly1305 -I../include -DSELFTEST -DPOLY1305_ASM poly1305.c ../../libcrypto.a
ohtsu@raspberrypi:~/github/openssl/crypto/poly1305$ ./poly1305
Poly1305 test #5 failed.
got:      80f8c262a71202d1e29179cbcb5d5a57
expected: 812059a5da198637cac7c4a631bee466
````
Testing with the current Chrome Canary based on draft-04 show the error of bad record mac.
```txt
1996231888:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:record/ssl3_record.c:470:
````

Building with no-asm has no errors on tests and the connection with Chrome Canary works fine so that the issue is caused by `poly1305-armv4.S`.

**Comment by dot-asm** [comment]
I can't reproduce this. Do you get same "got" values all the time? If so, can you post the binary? The one you've compiled with -DSELFTEST...

**Comment by shigeki** [comment]
Yes, I got the same value in the error all the time.

I put a build tar ball of my openssl git repo into https://html5.ohtsu.org/openssl-build-raspi2.tar.gz . Please download it and take a look at it. 
The selftest binary is `crypto/poly1305/poly1305` on the master branch.

My environment is as below. Please let me know if you need more information.
```sh
ohtsu@raspberrypi:~/github/openssl$ uname -a
Linux raspberrypi 4.1.17-v7+ #838 SMP Tue Feb 9 13:15:09 GMT 2016 armv7l GNU/Linux
ohtsu@raspberrypi:~/github/openssl$ gcc --version
gcc (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ohtsu@raspberrypi:~/github/openssl$ as --version
GNU assembler (GNU Binutils for Raspbian) 2.25
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `arm-linux-gnueabihf'.
````

**Comment by dot-asm** [comment]
Hmm... If I `gcc -I../include -DSELFTEST -DPOLY1305_ASM poly1305.c ../../libcrypto.a` I too get the error, but if I  `gcc -I../include -DSELFTEST -DPOLY1305_ASM poly1305.c poly1305-armv4.o` it passes. I'm inclined to conclude that poly1305-armv4 module is not the problem by itself. That is poly1305-armv4 can still be a trigger, but it's not really a problem with instruction sequence. Something presumably happens during linking. Either of options work fine elsewhere...

**Comment by dot-asm** [comment]
No, as it turns out one NEON instruction was misassembled. Those other options working elsewhere depend rather on the fact that it was previous assembler version assembler involved. And linking with poly1305-armv4.o vs. ../../libcrypto.a worked, because in former case armcap.o wasn't linked, which means that OPENSSL_armcap_P went uninitialized, which means that NEON code path was not exercised. Fix is upcoming...

**Comment by shigeki** [comment]
I've just found that 14577312211e25024ffd90bbded44b021877fc59 resolves the issue and all tests are passed. Testing with connection Chrome Canary is also fine. Thanks.
