### ISSUE TITLE
"openssl" s_client cannot connect to https://www.accuweather.com, while "curl" can!

### ISSUE THREAD

**Issue by gogo9th** [openssl/openssl#7084]
Hi, I have one mysterious problem. The following HTTPS command successfully returns the requested page:

**$ curl -vi https://www.accuweather.com**
* Rebuilt URL to: https://www.accuweather.com/
*   Trying 104.74.153.67...
* TCP_NODELAY set
* Connected to www.accuweather.com (104.74.153.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
...
</BODY>
</HTML>
* Connection #0 to host www.accuweather.com left intact

However, if I do the same with openssl as below, it doesn't return any response:

**$ openssl s_client -connect www.accuweather.com:443**

...
---
**GET / HTTP/2**
**Host: www.accuweather.com**
**User-Agent: curl/7.58.0**
Accept: */*

(hangs forever)

The bold texts are what I type in the terminal. Do you have idea why this problem occurs?

**Comment by richsalz** [comment]
Could it be that HTTP/2 is a binary protocol, not text?

**Comment by gogo9th** [comment]
It's the same even if I do the following:

GET / HTTP/1.1
Host: www.accuweather.com
User-Agnet: curl/7.58.0
Accept: */*

**Comment by gogo9th** [comment]
The result is the same even if I use HTTP 1.1 instead of HTTP 2 as the following:

GET / HTTP/1.1
Host: www.accuweather.com
User-Agent: curl/7.58.0
Accept: \*/\*

**Comment by yan12125** [comment]
Seems www.accuweather.com does not work with HTTP/1.1
```
$ curl --http1.1 -v https://www.accuweather.com
* Rebuilt URL to: https://www.accuweather.com/
*   Trying 23.42.97.135...
* TCP_NODELAY set
* Connected to www.accuweather.com (23.42.97.135) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=Pennsylvania; L=State College; O=Accuweather, Inc.; CN=*.accuweather.com
*  start date: May 31 00:00:00 2017 GMT
*  expire date: Aug 25 12:00:00 2019 GMT
*  subjectAltName: host "www.accuweather.com" matched cert's "*.accuweather.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: www.accuweather.com
> User-Agent: curl/7.61.0
> Accept: */*
>
(stuck here)
```

**Comment by gogo9th** [comment]
Hmm... I agree. Thanks!
