### ISSUE TITLE
-rsa_keygen_bits:4096 displays "Generating a 2048 bit RSA-PSS private key"

### ISSUE THREAD

**Issue by BillGoldstein** [openssl/openssl#7086]
tested with 1.1.1-pre8 (win32):
-newkey rsa-pss -rsa_keygen_bits:4096 gives message "Generating a 2048 bit RSA-PSS private key", though it actually generates 4096 key.

**Comment by mattcaswell** [comment]
The issue appears to affect "rsa" too (not just rsa-pss), and also seems to affect 1.1.0 (although rsa-pss is only in 1.1.1).

**Comment by t-j-h** [comment]
That looks like it has been broken in terms of reporting what it is going to do since the pkey_ctrl_string calls were added - i.e. -pkeyopt was added.

For reference: the command line being used is I assume something like this:

`./util/shlib_wrap.sh apps/openssl req -newkey rsa-pss -pkeyopt rsa_keygen_bits:4096`

**Comment by levitte** [comment]
There's currently no way to get the information of number of bits *out* of a `EVP_PKEY_CTX`, as far as I can see...  so it seems we have two choices: 1) add an API to retrieve such information, or 2) don't try to report the number of bits.

At this stage, it seems more prudent to take the second choice...

**Comment by mattcaswell** [comment]
> At this stage, it seems more prudent to take the second choice...

I agree.

**Comment by BillGoldstein** [comment]
Just as an aside, to gen an rsa-pss key, had to use
"openssl req -newkey rsa-pss -pkeyopt rsa_keygen_bits:4096"
vs for an rsa key
"openssl req -newkey rsa:4096" (which does report correct number of bits in message),
so perhaps
"openssl req -newkey rsa-pss:4096"
ought to work, too?
