### ISSUE TITLE
Heartbeat overcomplicated?

### ISSUE THREAD

**Issue by brightbits** [openssl/openssl#71]
I'm sure many questions have been asked since the whole heartbleed thing come about but I couldn't find an answer anywhere..

The whole point of the heartbeat is to ensure the other end is still there.. why not just send a PING and wait for a PONG or something simple, why does it need to send a buffer and expect that in response? It seems like its more complicated than it needs to be...

**Comment by mattcaswell** [comment]
As noted above this an issue for discussion on openssl-users mailing list. Closing this as an issue here.
