### ISSUE TITLE
SSL_shutdown:shutdown while in init (1.0.2f)

### ISSUE THREAD

**Issue by itpp16** [openssl/openssl#710]
about https://github.com/openssl/openssl/commit/64193c8218540499984cd63cda41f3cd491f3f59
This may solve the initial issue (ssl_undefined_function:called a function you should not call) but creates a new one:
SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking

**Comment by mattcaswell** [comment]
This is intentional. SSL_shutdown() previously reported this condition as "success" when in fact it had failed. It now correctly reports it as a failure.

**Comment by iroller** [comment]
Hi @mattcaswell. We're having such `shutdown while in init` errors from time to time when using openssl `1.0.2g-1ubuntu4.5` and uploading files to AWS S3. Do you have any suggestions on what can be causing those or how to debug? Thanks!

**Comment by mattcaswell** [comment]
This is really a question for the openssl-users email list. See:
mta.openssl.org

The error message means that your application has called SSL_shutdown() before a connection has been fully established. If you want to avoid those errors then don't call SSL_shutdown() if the macro SSL_in_init() returns true.
