### ISSUE TITLE
Possible inefficiency in HMAC_Init_ex

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#7104]
The `HMAC_Init_ex` function in `crypto/hmac/hmac.c` forces a reset if the user passes an md to the function.  This occurs even if it is the same pointer as was there present.

This could mean there is an unnecessary reset happening.
It might, instead, be required.

Noticed by @levitte in #7092

**Comment by nhorman** [comment]
@paulidale I (think) this is fixed by the fact that a new MD in HMAC_Init_ex is not accompanied by a new key, it gets rejected.  Is that sufficient or is there more to be done here?

**Comment by paulidale** [comment]
Closeing, not worth following up after all this time.
