### ISSUE TITLE
Disabling SHA-1 in TLS handshake in Linux

### ISSUE THREAD

**Issue by SiddalingaSwamy12** [openssl/openssl#7108]
As SHA1 is not recommended, I want to disable the SHA1 hash algorithm. I used OpenSSL API to set signature algorithm to SSL_CTX,

static INT32 signAlgoList[24] = { NID_sha512, 
EVP_PKEY_RSA, NID_sha512, EVP_PKEY_DSA, NID_sha512, EVP_PKEY_EC,NID_sha384, 
EVP_PKEY_RSA, NID_sha512, EVP_PKEY_DSA, NID_sha384, EVP_PKEY_EC, NID_sha256, 
EVP_PKEY_RSA, NID_sha256, EVP_PKEY_DSA, NID_sha256, EVP_PKEY_EC, NID_sha224, 
EVP_PKEY_RSA, NID_sha224, EVP_PKEY_DSA, NID_sha224, EVP_PKEY_EC };

  /* signature algorithm list */

  (void)SSL_CTX_set1_client_sigalgs(sCtxMutualAuth, (int *)signAlgoList, 24);

   (void)SSL_CTX_set1_sigalgs(sCtxMutualAuth, (int *)signAlgoList, 24);

After including these APIs in my program SHA-1 is diabled in Windows(Am not seeing Sha-1 in wireshark logs) but, still SHA1 is not disabled in Linux. It is showing SHA-1 in Wireshark logs. Can anyone suggest me, is there any other way to disable the SHA1 in Linux

**Comment by mattcaswell** [comment]
Some things to check:

- Does `SSL_CTX_set1_sigalgs()` or `SSL_CTX_set1_client_sigalgs()` return an error (0 return)? You're just ignoring the return value so you won't see if it has failed
- Is `sizeof(INT32) == sizeof(int)` on your platform? If it's not then that could cause the above to go wrong.

**Comment by SiddalingaSwamy12** [comment]
- Am not catching return value of SSL_CTX_set1_sigalgs(), but how its running fine in windows? SHA-1 is disbled in windows.

**Comment by SiddalingaSwamy12** [comment]
Just now i upgraded openssl to 1.0.2p in Linux. Now am not seeing SHA-1 in Clinet hello.
But SHA-1 is still there in certificate request.

Note : My server is running in Linux and Client in Windows

**Comment by t8m** [comment]
1.0.2 releases are no longer supported. The current master downgrades SHA-1 strength so it is not used with the default security level. Closing.
