### ISSUE TITLE
Redundant/missing check for RSA

### ISSUE THREAD

**Issue by Bugcheckers** [openssl/openssl#7117]
We have seen an inconsistency in

https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_pk1.c#L164

```
if (tlen < 0 || flen < 0)
        return -1;
```

https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_oaep.c#L138

```
if (tlen <= 0 || flen <= 0)
        return -1;
```

Same operation is performed on flen variable afterwards:

```
if (flen != num) {
    memcpy(em + num - flen, from, flen);
```

We believe either `flen==0` is redundant  in the second case or is missing in the first case.

**Comment by mattcaswell** [comment]
It makes no sense to me to call those functions with `flen == 0`. Probably it should be checked in the first instance. Presumably if `flen == 0`, then `from` may be `NULL` which would hit undefined behaviour when we hit the later `memcpy`. Erroring out early if `flen == 0` would avoid that.

OTOH, should it be considered a programmer error to call those functions with `flen == 0`? In which case adding the check might be nice but not strictly necessary.

Either way this seems like a relatively minor issue. PRs welcome.
