### ISSUE TITLE
 DRBG: Using a weaker strength DRBG as a source is not currently supported.

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#7118]
Currently there is only one DRBG implementation (DRBG_ctr). It is only possible to set one strength for the master and slave DRBG's. 
If alternate DRBG's are added (Hash or HMAC) (See PR #6779) then it is possible to add weaker strength DRBG's as the master DRBG.

If additional DRBG's are supported then a decision will need to be made to either 
  (1) Support this feature OR
  (2) Document that it is not supported.

----------------------------------------------------------------------------------------
NOTES:

rand_lib.c contains the following code:

``` C
rand_drbg_get_entropy(....)
{
  .....
    if (drbg->parent && drbg->strength > drbg->parent->strength) {
        /*
         * We currently don't support the algorithm from NIST SP 800-90C
         * 10.1.2 to use a weaker DRBG as source
         */
        RANDerr(RAND_F_RAND_DRBG_GET_ENTROPY, RAND_R_PARENT_STRENGTH_TOO_WEAK);
        return 0;
    }
}
```

**Comment by paulidale** [comment]
This was dealt with in ~#8660~ but until such time as it is actually required, it has been decided to not support such a mode.  Closing.
