### ISSUE TITLE
DRBG: Prediction Resistance is not currently supported.

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#7119]
Assuming that there will be an proper entropy source (dev_rand  or dev_urand),
or that there will be some way of externally supplying a validated entropy source - 
The following code will need to be changed in file rand_lib.c

---------------

``` C
rand_drbg_get_entropy(...)
{
    .....
    if (drbg->parent) {
       ....
    } else  {
        if (prediction_resistance) {
            /*
             * We don't have any entropy sources that comply with the NIST
             * standard to provide prediction resistance (see NIST SP 800-90C,
             * Section 5.4).
             */
            RANDerr(RAND_F_RAND_DRBG_GET_ENTROPY,
                    RAND_R_PREDICTION_RESISTANCE_NOT_SUPPORTED);
```

------------------
 NOTE that CAVs tests would currently pass because the DRBG's created for testing are not part of the master/slave logic (so this path is never executed).

**Comment by slontis** [comment]
Found while adding PR https://github.com/openssl/openssl/pull/6779

**Comment by paulidale** [comment]
This has been dealt with in ~#8647~
Closing.
