### ISSUE TITLE
Two "RSA-PSS KEY GENERATION OPTIONS" sections in genpkey docs.  2nd is correct one?

### ISSUE THREAD

**Issue by BillGoldstein** [openssl/openssl#7124]
https://www.openssl.org/docs/man1.1.1/man1/openssl-genpkey.html has 2 sections titled "RSA-PSS KEY GENERATION OPTIONS", the 2nd of which is probably the right one?

**Comment by mattcaswell** [comment]
Strange. This looks like a website issue. The master man pages are correct:

https://www.openssl.org/docs/manmaster/man1/openssl-genpkey.html

But master and 1.1.1 are the same branch, so these two should be identical.

@levitte any thoughts?

**Comment by BillGoldstein** [comment]
Looks okay today...guess it got fixed in release process somehow.
