### ISSUE TITLE
Redundant Casting and Switch Case (Harmonization)

### ISSUE THREAD

**Issue by Bugcheckers** [openssl/openssl#7125]
**Redundant switch case and initialization**

The following functions are doing the same thing, however the last four initialize `ret = 1` and use a switch case, which seem to be redundant

1. https://github.com/openssl/openssl/blob/master/crypto/asn1/bio_asn1.c#L311
----
2. https://github.com/openssl/openssl/blob/master/crypto/evp/bio_b64.c#L535
3. https://github.com/openssl/openssl/blob/master/crypto/evp/bio_enc.c#L389
4. https://github.com/openssl/openssl/blob/master/crypto/evp/bio_md.c#L201
5. https://github.com/openssl/openssl/blob/master/crypto/evp/bio_ok.c#L407
----
----
**Redundant Casting**

https://github.com/openssl/openssl/blob/master/crypto/x509v3/v3_utl.c#L929
`chklen = strlen((char *)chk);`

https://github.com/openssl/openssl/blob/master/crypto/x509v3/v3_utl.c#L910
`chklen = strlen(chk);`

**Comment by t8m** [comment]
The report is just for code cleanness issue and it is against an old code revisions so most of the links are not relevant anymore. Closing.
