### ISSUE TITLE
X509_sign SIGSEGVs with NULL private key

### ISSUE THREAD

**Issue by DirtYiCE** [openssl/openssl#7133]
With openssl 1.1.0i, you could call X509_sign with NULL `pkey` and `md` as a way to invalidate the encoded certificate. With openssl 1.1.1-pre9, it SIGSEGVs in `int_ctx_new`. The corresponding NULL check was removed at https://github.com/openssl/openssl/commit/2f2e6b6278bc4cbf670e42ae9f4ff818529df37c#diff-50c3cc4d0cdfdf4ab6900bf17c3224d5.

**Comment by paulidale** [comment]
Fixed in #7146
