### ISSUE TITLE
Crash when try to set siphash's hash size to 8 through the EVP interface 

### ISSUE THREAD

**Issue by orignal** [openssl/openssl#7143]
in 1.1.1-pre9

I call following code:
```
EVP_PKEY * pkey = EVP_PKEY_new_raw_private_key (EVP_PKEY_SIPHASH, NULL, key, 16);
EVP_MD_CTX * mdctx = EVP_MD_CTX_create ();	
EVP_PKEY_CTX * ctx = NULL;
EVP_DigestSignInit (mdctx, &ctx, NULL, NULL, pkey);
EVP_PKEY_CTX_ctrl (ctx, -1, EVP_PKEY_OP_SIGNCTX, EVP_PKEY_CTRL_SET_DIGEST_SIZE, 8, NULL));
```	

It passes null pointer here
https://github.com/openssl/openssl/blob/master/crypto/siphash/siphash_pmeth.c#L139
and crashes here
https://github.com/openssl/openssl/blob/master/crypto/siphash/siphash.c#L86
because of the  null pointer for k.

**Comment by orignal** [comment]
Both of them are valid.
And EVP_DigestSign produces correct hash after it if I don't call EVP_PKEY_CTX_ctrl.
But it assumes hash size as 16, but I need 8.

**Comment by levitte** [comment]
I just looked at the code, and that particular control is badly written, it requires that a key has already been created, but that's done with the control `EVP_PKEY_CTRL_DIGESTINIT`, which uses the current SIPHASH hash_size (which defaults to the maximum possible), so in the end, this requires that a "default" SIPHASH key gets created, then you can change the hash size, which will re-create the SIPHASH key (to something different).

What's lacking is a hash size setter in siphash.c.  Coming up.
