### ISSUE TITLE
Call of ENGINE_finish() with NULL is not permitted.

### ISSUE THREAD

**Issue by FdaSilvaYY** [openssl/openssl#715]
Hi,
While digging in the code, I notice that this method can't be be called with NULL, because it triggers an error.
I don't see the value added of this error,  as a NULL engine pointer means that no engine is active.

Allowing this, could remove many lines of code around the calls to ENGINE_finish.
Want a PR ?

**Comment by levitte** [comment]
Many lines of code?  You mean something like `if (engine != NULL)`?

**Comment by FdaSilvaYY** [comment]
Yes, or any other form of testing the arguments before calling it.
There is  around 20 test / branching that could be removed.

**Comment by richsalz** [comment]
Yes please.

**Comment by richsalz** [comment]
I am in favor of this, since it simplifies calling code.
See #743.  @levitte? :)

**Comment by richsalz** [comment]
done.
