### ISSUE TITLE
OpenSSL Documentation

### ISSUE THREAD

**Issue by wolfebrian2120** [openssl/openssl#7150]
Is there any documentation on the use of config files for generating certificates? I have seen examples, around the interwebs, but I am looking for a more comprehensive list of options that are available.

**Comment by InfoHunter** [comment]
Are you seeking these files? https://github.com/openssl/openssl/blob/master/doc/man5

**Comment by wolfebrian2120** [comment]
Hi yes that is what i have been looking for. Thx
