### ISSUE TITLE
wss server crash by openssl 1.1.0f

### ISSUE THREAD

**Issue by ycf8788** [openssl/openssl#7162]
My server have appeared a crash maybe about openssl 1.1.0f.My server use boost asio(v1.6.7) and openssl(v1.1.0f) to support wws protocol. It's occasionally happened crash when I started a pressure test.
 The crash generate a dump file. the stack info like this:

`libssl-1_1.dll!do_ssl3_write(ssl_st * s, int type, const unsigned char * buf, unsigned int * pipelens, unsigned int numpipes, int create_empty_fragment) 行 772	C`
`libssl-1_1.dll!ssl3_dispatch_alert(ssl_st * s) 行 98	C`
`libssl-1_1.dll!ssl3_send_alert(ssl_st * s, int level, int desc) 行 81	C`
`libssl-1_1.dll!ssl3_get_record(ssl_st * s) 行 521	C`
`libssl-1_1.dll!ssl3_read_bytes(ssl_st * s, int type, int * recvd_type, unsigned char * buf, int len, int peek) 行 1055	C`
`libssl-1_1.dll!ssl3_read_internal(ssl_st * s, void * buf, int len, int peek) 行 3835	C`
`libssl-1_1.dll!ssl3_read(ssl_st * s, void * buf, int len) 行 3857	C`
`libssl-1_1.dll!SSL_read(ssl_st * s, void * buf, int num) 行 1552	C`

Do you have any suggestions or ideas, how to get around this?

Thanks!

**Comment by t8m** [comment]
1.1.0 is out of support. Please open a new issue if you still see the same problem with 1.1.1 or 3.0.
