### ISSUE TITLE
Fix mkdef.pl step on case-sensitive win32 filesystem

### ISSUE THREAD

**Issue by wrowe** [openssl/openssl#7172]
The following mkdef error shows up on Windows 64 builds run from an x64 native command tools
console window on Windows 10, using the -pre9 and later master git checkout, with the newest April
update to Windows 10, and a checkout created or tarball unpacked from ubuntu on linux (resulting in case sensitive directories);

        "C:\Perl64\bin\perl.exe" "..\..\src\openssl-1.1.1-pre9\util\mkdef.pl" crypto 32 > libcrypto.def
Can't open ..\..\src\openssl-1.1.1-pre9\include\openssl\__decc_include_epilogue.h, No such file or directory, at ..\..\src\openssl-1.1.1-pre9\util\mkdef.pl line 343.

This appears to be a filename case sensitivity issue.

__DECC_INCLUDE_EPILOGUE.H
__DECC_INCLUDE_PROLOGUE.H

each exist at;

include/openssl/
include/internal/
crypto/include/internal/

This was introduced in April 2018 on Windows 10 for users who mix checkouts from ubuntu-on-windows 
(services for unix) with building under Windows.

It appears that mkdef.pl is forcing filenames lowercase with lc(), which is ill advised on a case sensitive 
filesystem. However, adding these two file names (in lower-case) to the $skipthese list appears to resolve 
the entire issue for the time being. E.g. at ln 241 add:

$skipthese{'include/openssl/__decc_include_epilogue.h'} = 1;
$skipthese{'include/openssl/__decc_include_prologue.h'} = 1;

These are already excluded in their lc()'ed lowercase form in test/build.info. Why the glob is matching
*.h to *.H is another issue, arising from perl's win32 assumptions.

Note that the files named crypto/LPdir_win.c, crypto/LPdir_win32.c also cause issues due to forced 
lower case semantics when using Configure.pl to generate makefiles.

**Comment by levitte** [comment]
That's new...  How does one enable case sensitivity?  I need to experiment a bit...

**Comment by wrowe** [comment]
Indeed, new to me too, it was pretty straightforward to make a case sensitive NTFS volume for years, but per-dir is brand new.

Review https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10 and similar for guidance. Or simply install Services For Unix in add remove windows features, the default mkdir under Ubuntu creates case sensitive dirs.

**Comment by levitte** [comment]
It looks to me like it should be fine removing the `lc` call and use the `basename($f)` result directly.  Can you verify this?

**Comment by wrowe** [comment]
I've confirmed that dropping the lc's from both add-depends.pl and mkdef.pl causes the entire build
to succeed on case-sensitive win32 checkout and vpath build trees. It does make more sense, as you
suggested.

[openssl-7172.patch.log](https://github.com/openssl/openssl/files/2372093/openssl-7172.patch.log)

**Comment by levitte** [comment]
Thanks for the hint.  I've prepared #7195 as a fix, I hope it corresponds to what you did.

**Comment by wrowe** [comment]
Confirmed this is correct and ready to merge to master and 1_1_1-stable
