### ISSUE TITLE
Did the new version of openssl 1.0.2/1.1.0 is compatible with Apache 2.2.27 

### ISSUE THREAD

**Issue by phanimngr** [openssl/openssl#7173]
Did the new version of openssl 1.0.2/1.1.0 is compatible with Apache 2.2.27 on oracle solaris 10 server , can you please suggest on it

**Comment by rainerjung** [comment]
This question should be posted to the Apache httpd users list, see http://httpd.apache.org/lists.html#http-users.

**Comment by mattcaswell** [comment]
Please ask Apache this question. Closing.
