### ISSUE TITLE
mod_ssl vs PHA - unable to consume non-appdata records

### ISSUE THREAD

**Issue by notroj** [openssl/openssl#7178]
With older OpenSSL/TLS versions, mod_ssl was able to do:

> 
            SSL_renegotiate(ssl);
            SSL_do_handshake(ssl);
            SSL_peek(ssl, buf, 0);

to trigger and complete a renegotiation to request a client cert.

There doesn't seem to be any way to do this with 1.1.1pre9 and PHA.  mod_ssl can now do:

>
            SSL_verify_client_post_handshake(ssl);
            SSL_do_handshake(ssl);

And the CertificateRequest gets sent to the client.  If the server does not call SSL_peek(), OpenSSL does not wait for a Certificate message.  If it does call SSL_peek(), it appears to wait to actually consume some app_data, when none is (necessarily) expected at this point in the HTTP connection.

As discussed in this thread https://marc.info/?l=openssl-dev&m=145546707418497&w=2 what mod_ssl really needs is an API to ask OpenSSL to read/consume/process non-appdata records which are available from the bio but then return control to the application.  Is something like this possible?

**Comment by t8m** [comment]
And I actually think that the SSL_peek() with zero length (possibly also ignoring the buffer argument) should semantically do exactly that. And if it does not with 1.1.1 I would consider this to be a bug.

**Comment by mattcaswell** [comment]
Does calling `SSL_clear_mode(ssl, SSL_MODE_AUTO_RETRY)` before the peek help at all?

**Comment by mattcaswell** [comment]
BTW, note that a client is not obligated to immediately respond with a response. It could come back with application data first, before the requested certificate.

**Comment by notroj** [comment]
Adding `SSL_clear_mode(ssl, SSL_MODE_AUTO_RETRY)` before the peek seems to work.  Testing further but this looks promising, thanks!

With HTTP/1.1 the problem of app data at this point in the protocol has always been there and never been possible to solve completely server-side without some protocol change, I don't know if was addressed in HTTP/2.

**Comment by mattcaswell** [comment]
See:

https://github.com/openssl/openssl/blob/a4a90a8a3bdcb9336b5c9c15da419e99a87bc6ed/CHANGES#L121-L130

I'm wondering if this might give you an issue in your TLSv1.2 code.

**Comment by notroj** [comment]
It looks like mod_ssl can/should turn off AUTO_RETRY by default, it is designed to cope with SSL_read() returning SSL_ERROR_WANT_READ.  Can you expand on why this might matter for TLSv1.2?

Also, apologies for overloading this ticket with random questions, but the specific semantics of SSL_VERIFY_MODE_HANDSHAKE are not really clear from the man page.  If it is optional, what difference should it make and why/when should it be set?

**Comment by mattcaswell** [comment]
> It looks like mod_ssl can/should turn off AUTO_RETRY by default, it is designed to cope with SSL_read() returning SSL_ERROR_WANT_READ. Can you expand on why this might matter for TLSv1.2?

With AUTO_RETRY on, if you attempt to read application data but actually get handshake data then it will process the handshake data and then immediately try again to get application data. You saw this as a hang in the `SSL_peek()` call in TLSv1.3. But you also have an `SSL_peek()` call in TLSv1.2 so the same should occur there AFAICT.

> Also, apologies for overloading this ticket with random questions, but the specific semantics of SSL_VERIFY_POST_HANDSHAKE [edit: fixed typo] are not really clear from the man page. If it is optional, what difference should it make and why/when should it be set?

Before the handshake starts if you set `SSL_VERIFY_PEER` then it will attempt to obtain a cert from the client during the handshake *unless* you also set `SSL_VERIFY_POST_HANDSHAKE`. By setting both you can set everything up before the handshake starts and forget about it. Alternatively you can set neither before the handshake starts, and just set `SSL_VERIFY_PEER` later on.

**Comment by notroj** [comment]
Thanks for your help @mattcaswell - I think we have ironed out all the 1.1.1 issues in mod_ssl other than the fact that PHA is broken by default as covered in the other ticket.  I'll close this.
