### ISSUE TITLE
SSL_set1_curves can set a limited list of curves

### ISSUE THREAD

**Issue by aenachescu** [openssl/openssl#7184]
Hi,
I have the following problem, when I run `openssl ecparam -list_curves`  there are 80 curves listed, but only a part of them can be added in a SSL struct using SSL_set1_curves function because tls1_ec_nid2curve_id() returns 0. For example, let be secp112r1 curve, I can create the EC key with this curve and also I can create a certificate using that key but I can't configure the server and the client to use secp112r1 curve. My question is why this limitation exists and if it's possible to extend SSL_set1_curves function so that we can set any built-in curve.

**Comment by richsalz** [comment]
Not all curves supported by the crypto library have official values in the TLS protocol.

**Comment by kroeckx** [comment]
I think they can also be removed because they don't provide 80 bit
of security, and you might need to change the security level if
you really want to use them.

**Comment by EnachescuAlin** [comment]
> Not all curves supported by the crypto library have official values in the TLS protocol.

So, tls1_ec_nid2curve_id() actually converts the EC nid to the curve id defined in the TLS protocol?

> I think they can also be removed because they don't provide 80 bit of security, and you might need to change the security level if you really want to use them.

I think they should kept because I need them for the compatibility with old servers.

**Comment by kroeckx** [comment]
On Tue, Sep 11, 2018 at 10:42:31AM -0700, Alin Enachescu wrote:
> > I think they can also be removed because they don't provide 80 bit of security, and you might need to change the security level if you really want to use them.
> 
> I think they should kept because I need them for the compatibility with old servers.

Like I said, change the security level. It defaults to 1. The
easiest way to change it is probably adding @SECLEVEL=0 in your
cipher string. Note that this might also enable other ciphers you
might not want.

**Comment by EnachescuAlin** [comment]
Changing security level does not help me because security level does not affect the behavior of tls1_ec_nid2curve_id function.

**Comment by t8m** [comment]
This was already answered in the first reply. Not all curves can be used in TLS protocol.
