### ISSUE TITLE
SSL_CTX_set_cipher_list always adds TLS 1.3 ciphers

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#7196]
In OpenSSL 1.1.0 and below if you passed a pattern to `SSL_CTX_set_cipher_list` that didn't match any ciphers the function would return 0 and not set any cipher suites. As of 1.1.1 the TLS 1.3 ciphers are added unconditionally https://github.com/openssl/openssl/blob/88ea3685e4bf30fc529fe46e19effc6317726de8/ssl/ssl_ciph.c#L1597-L1604 so this function can't return an empty cipher suite list. You can see this behavior with this example which will fail the assert under 1.1.1 but pass in 1.1.0.

```c
#include <openssl/ssl.h>
#include <assert.h>


int main(void) {
    int res;
    SSL_CTX *ctx = SSL_CTX_new(TLS_method());
    res = SSL_CTX_set_cipher_list(ctx, "nonsense");
    STACK_OF(SSL_CIPHER) *sk_ciphers = SSL_CTX_get_ciphers(ctx);
    assert(sk_SSL_CIPHER_num(sk_ciphers) == 0);
    return 0;
}
```
Additionally, even passing  the deprecated `TLSv1_2_method` to constrain the connection to 1.2 will add the ciphers.

The TLS 1.3 suites being added while ignoring the filter was presumably done to prevent situations where custom cipher suite specification would prevent the use of TLS 1.3, but the intermingling of TLS 1.3 and previous cipher suites here where the documented filter is not always applied is more than a little confusing.

**Comment by reaperhulk** [comment]
I've been informed that `SSL_CTX_set_ciphersuites` is the API of record for manipulating TLS 1.3 suites, but should TLS 1.3 suites be showing up in this list when the CTX is configured for TLS 1.2?

**Comment by mattcaswell** [comment]
Yes that is the intended design. We tried out quite a number of ways of doing this in the various beta releases and all of them had some problem or another and the behaviour was unexpected for something. Doing it this way seemed to break the least things.

**Comment by reaperhulk** [comment]
Okay, thanks for confirming. I’ll change some expectations on my end!

**Comment by normanmaurer** [comment]
@reaperhulk thanks for reporting... I just hit the same "issue" in https://github.com/netty/netty-tcnative and was about to create an issue when I found this one :)

@mattcaswell I wonder if it may make sense to mention the behaviour change somewhere tho.

**Comment by mattcaswell** [comment]
> I wonder if it may make sense to mention the behaviour change somewhere tho.

Actually it is. The TLSv1.3 CHANGES entry, plus multiple of my blog posts point towards this page where the change is discussed (see the ciphersuites section):

https://wiki.openssl.org/index.php/TLS1.3

On reviewing the wording though perhaps it could be made a bit more explicit with regards to the behaviour of `SSL_CTX_get_ciphers()`

**Comment by normanmaurer** [comment]
@mattcaswell I somehow totally missed it... Thanks!

**Comment by mattcaswell** [comment]
I added an extra couple of sentences on the wiki page to be more explicit about the behaviour of `SSL_CTX_get_ciphers()`.

**Comment by davidben** [comment]
It is a little odd that the `SSL_R_NO_CIPHER_MATCH` path is now unreachable. I would have expected the ordering to be:

1. Process rule string for 1.2 ciphers
2. Usual error-handling
3. Prepend the 1.3 ciphers

If the model is that 1.3 ciphers are different animals and thus configured separately, that's a bit more self-consistent.
