### ISSUE TITLE
70-test_comp.t waits for input from stdin

### ISSUE THREAD

**Issue by a20god** [openssl/openssl#7203]
Windows 7, x64, Microsoft C/C++ Compiler 19.11, perl 5.14.0 for MinGW, OpenSSL 1.1.1 configured and built with
> perl Configure VC-WIN64A no-asm
> nmake
> nmake test

The tests stop here:
> test\recipes\70-test_comp.t .....................

Apparently, perl is waiting for input from stdin (no CPU time consumed, keyboard input is echoed).

**Comment by mattcaswell** [comment]
You are mixing perl for mingw with VS. See the documentation in NOTES.PERL on this issue:

https://github.com/openssl/openssl/blob/6839a7a7f4973a3fc2f87b12664c26d524bef1f4/NOTES.PERL#L30-L40

Trying building again with a more suitable perl version

**Comment by a20god** [comment]
The tests pass with ActivePerl (which seems to be just another MinGW version of perl, albeit a better one than the one at https://sourceforge.net/projects/perl-mingw/). Thanks!

**Comment by Ramsesse** [comment]
Hello, I have the same problem here, 
with perl -version:

> This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread
> (with 1 registered patch, see perl -V for more detail)
> 
> Copyright 1987-2018, Larry Wall
> 
> Binary build 0000 [92425271] provided by ActiveState http://www.ActiveState.com
> Built Oct 23 2019 15:41:44

Also stops on 

> test\recipes\70-test_comp.t ..................…

Win10, fresh new openssl from GitHub, perl installed, VS 2019 build tools.

Any ideas?

**Comment by 8ahnenerbe8** [comment]
the same problem

**Comment by 8ahnenerbe8** [comment]
> Hello, I have the same problem here,
> with perl -version:
> 
> > This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread
> > (with 1 registered patch, see perl -V for more detail)
> > Copyright 1987-2018, Larry Wall
> > Binary build 0000 [92425271] provided by ActiveState http://www.ActiveState.com
> > Built Oct 23 2019 15:41:44
> 
> Also stops on
> 
> > test\recipes\70-test_comp.t ..................…
> 
> Win10, fresh new openssl from GitHub, perl installed, VS 2019 build tools.
> 
> Any ideas?
the same problem

**Comment by 8ahnenerbe8** [comment]
> Hello, I have the same problem here,
> with perl -version:
> 
> > This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread
> > (with 1 registered patch, see perl -V for more detail)
> > Copyright 1987-2018, Larry Wall
> > Binary build 0000 [92425271] provided by ActiveState http://www.ActiveState.com
> > Built Oct 23 2019 15:41:44
> 
> Also stops on
> 
> > test\recipes\70-test_comp.t ..................…
> 
> Win10, fresh new openssl from GitHub, perl installed, VS 2019 build tools.
> 
> Any ideas?


the same problem

**Comment by ruiyan-yu** [comment]
[ActivePerl 5.24.2 Build 2403](https://downloads.activestate.com/ActivePerl/) works.

**Comment by ttxs69** [comment]
Hello,I have the same problem here.
With perl -version:
`This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2018, Larry Wall

Binary build 0000 [1adeb458] provided by ActiveState http://www.ActiveState.com
Built Feb 25 2020 19:28:11`
Win10 1909 and VS 2019 Community

**Comment by gocove** [comment]
I have the same problem, stuck on 70-test_comp.t.
Windows 7, VS2017 Community.

This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2018, Larry Wall

Binary build 0000 [15feb953] provided by ActiveState http://www.ActiveState.com
Built Mar 25 2020 15:30:17

**Comment by gocove** [comment]
Added Win32-Process to my ActiveState Perl distribution. The test passes now.

**Comment by panicjoker** [comment]
I have the same problem.

perl -version

This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2018, Larry Wall

Binary build 0000 [58a1981e] provided by ActiveState http://www.ActiveState.com
Built Apr 10 2020 17:28:14

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

Win10, fresh new openssl from GitHub, VS 2019 build tools.

Any ideas?

**Comment by jddurand** [comment]
> Added Win32-Process to my ActiveState Perl distribution. The test passes now.

This is just a bypass that makes the creation of a process faster than traditional fork/exec (where perl translates fork to a thread, and exec to a process). The real problem is a timing issue in TLSProxy/Proxy.pm where the STDIN, shared between the parent and the child, can be restored to its original state before the new process is instanciated by perl. Then it has nothing to read and will hang. This can happen on every OS with the current code.

I think that in TLSProxy/Proxy.pm there is no need of Win32::Process nor of exec(): a separate instance of the perl interpretor instanciated by fork() (i.e. a real process on non-MSWin32, a thread on MSWin32/ithreads (which the default)) is enough, provided it is working on a safe STDIN.

I have a patch that has been tested on
* MSWin32 cl compiler from Visual Studio 2022 perl 5.37.5
* Debian x64 gcc12 compiler perl

**Comment by jan-lalinsky** [comment]
I've got the same problem, compiling openssl 1.1.1q on Rocky Linux 9, Perl v5.32.1.  "make test" prints several tests ok, then

70-test_comp.t ........

and hangs indefinitely, while CPU is doing nothing. @jddurand I've tried your Proxy.pm patch, but unfortunately it did not help; make test still hangs on ../test/recipes/70-test_comp.t ....

I've checked running processes, there are two processes  "/usr/bin/perl -w ../test/recipes/70-test_comp.t", the older waits on syscall

connect(4, {sa_family=AF_INET6, sin6_port=htons(39865), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, 28

the newer one (higher PID, child of the older one) waits on

read(5,

**Comment by jddurand** [comment]
@jan-lalinsky since the parent looks like stalled in `connect` system call I'd guess this is something else, local to your OS (e.g. network rules ?).

**Comment by jan-lalinsky** [comment]
You're right, allowing traffic on ::1 and 127.0.0.0/8 in firewall did help, now all tests either get automatically skipped or finish with "ok". Thanks!

**Comment by vrkosk** [comment]
Also fails with OpenSSL 3.2.0 and 3.1.4 on this system.

When you interrupt with Ctrl-C, the output is amusing:

```
70-test_comp.t ..................... Terminating on signal SIGINT(2)
NNMMAAKKEE  ::  ffaattaall  eerrrroorr  UU11005588::  tteerrmmiinnaatteedd  bbyy  uusseerr

SSttoopp..
```

_However_, a different Windows Server 2022 system in the same network, also compiling with VS2019, does not have this problem. All the build steps are identical (for both Perl and OpenSSL). Comparing the environment variables, the only difference I can find is:

- On the system where the test works, environment variable is UCRTVersion=10.0.20348.0
- On the system where the test fails, environment variable is UCRTVersion=10.0.19041.0

(I don't know if this is a red herring.)

**Comment by george-kp** [comment]
I had the same problem with hanging 70-test_comp.t with  32 bit build of OpenSSL 3.4.0 and 3.2.2on windows 11 64 bit. But it appears that my firewall was the reason. Disabling firewall for perl application solves the problem.
