### ISSUE TITLE
OpenSSL 1.1.0g and 1.0.1e-fips compatibility

### ISSUE THREAD

**Issue by kibrazh48** [openssl/openssl#7213]
Hello!

I have Ubuntu 18.04 with OpenSSL 1.1.0g and CentOS 7.3.1611 with OpenSSL 1.0.1e-fips.
I build my project on Ubuntu 18.04 with '-lcrypto -lssl' libraries and try to run the binary in CentOS and it leads to the following error:

$ ./prog
./prog: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

I know about that table https://abi-laboratory.pro/?view=timeline&l=openssl

Could you please hint me how to fix that issue or the only one way is to install "OpenSSL 1.1.0g" on CentOS?

**Comment by levitte** [comment]
The OpenSSL 1.1.x series and 1.0.x series aren't compatible, and this is expressed in a difference in library SONAME.

You either need to rebuild your application on CentOS or install OpenSSL 1.1.0g on CentOS.
