### ISSUE TITLE
1.1.1: certificate-request genaration fails if 'STate' or 'OrganizationUnit' is empty

### ISSUE THREAD

**Issue by lzsiga** [openssl/openssl#7215]
When trying to generate a certificate request, If either 'STate' or 'OrganizationUnit' is empty, I get this error-message:
`1:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:crypto/asn1/a_mbstr.c:100:minsize=1`
The same command works perfectly in 1.0.2

**Comment by mattcaswell** [comment]
What was the command that you used?

**Comment by kroeckx** [comment]
Instead of /ST=/, you should just drop it. They both have a
minimum requirement of a length of 1. But there is no reason to
add them if you don't need them.

**Comment by lzsiga** [comment]
Thank you, kroeckx, that helped.
