### ISSUE TITLE
Is draft article 28 the same as the final version?

### ISSUE THREAD

**Issue by KomorebiL** [openssl/openssl#7220]
Sorry, my English is a bit bad.

I installed the latest version of OpenSSL on my server.
This is its link:
>  https://www.openssl.org/source/openssl-1.1.1.tar.gz

Here are some of the configurations from nginx on my server.
```
ssl_protocols                TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers    on;
ssl_ciphers                  TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:EECDH+CHACHA20:EECDH+AESGCM;
```

A puzzling problem arises: when I use 
```
openssl s_client ip:port
```
 on linux, Protocol shows TLSv1.3, which is very normal.

But when I use a browser to access the domain name, the potocol is TLSv1.2.

I saw a sentence in the document:
> Although the latest 1.1.1 versions support the final standard version, other applications that support TLSv1.3 may still be using older draft versions. This is a common source of interoperability problems. If two peers supporting different TLSv1.3 draft versions attempt to communicate then they will fall back to TLSv1.2.

So what I want to ask is: Is draft article 28 the same as the final version?

**Comment by romen** [comment]
Most probably the browser you are using does not yet support the final published revision of the standard (RFC8446) but only draft 28.

Although they are very similar, the draft version and the final version are not interoperable, as you quoted from the [wiki](https://wiki.openssl.org/index.php/TLS1.3).
