### ISSUE TITLE
Performance issue in BIO_get_host_ip

### ISSUE THREAD

**Issue by smanikantan** [openssl/openssl#7228]
The function BIO_get_host_ip performs poorly in the following environment

GNU C Library (GNU libc) stable release version 2.17
CentOS Linux release 7.3.1611 
openssl version : 1.0.2

This function grabs a lock and then invokes gethostbyname. With multi-threaded application, the lock is a bottleneck and results in bad performance.
We can  use thread safe version gethostbyname_r instead of gethostbyname and eliminate the need for big lock in BIO_get_host_ip

**Comment by paulidale** [comment]
It seems unlikely that this will get addressed.  This function is deprecated in 1.1.x and later and 1.0.2 is only getting bug fixes at this stage.

**Comment by mlindner** [comment]
Would pull requests for it be accepted?

**Comment by t-j-h** [comment]
Pull requests are always welcome and will be evaluated on their merit.

**Comment by levitte** [comment]
Note that we need to retain the use of gethostbyname for those who don't have gethostbyname_r

**Comment by smanikantan** [comment]
Thanks for the inputs all.

Is there a compile time flag, which i could use to in order to call
gethostbyname_r ?
I think, it is safe to use gethostbyname_r for linux ?

Thanks
Mani

**Comment by paulidale** [comment]
You'll need to use the feature check macros.  `man gethostbyname_r` lists them.  On my machine:

```
   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       gethostbyname2(), gethostent_r(), gethostbyaddr_r(), gethostbyname_r(),
       gethostbyname2_r():
           Since glibc 2.19:
               _DEFAULT_SOURCE
           Glibc versions up to and including 2.19:
               _BSD_SOURCE || _SVID_SOURCE
```

So you'll need something like:
```
#if defined(__GLIBC__)
# if defined(__GLIBC_PREREQ)
#  if __GLIBC_PREREQ(2, 19)
#   if defined(_DEFAULT_SOURCE)
#     define HAVE_GETHOSTBYNAME_R
#   endif
#  else
#   if defined(_BSD_SOURCE) || defined(_SVID_SOURCE)
#     define HAVE_GETHOSTBYNAME_R
#   endif
#  else
#   if defined(_BSD_SOURCE) || defined(_SVID_SOURCE)
#     define HAVE_GETHOSTBYNAME_R
#   endif
# endif
#endif
```

But I've probably made a mistake in there...

**Comment by smanikantan** [comment]
Hi All : 

I have submitted a pull request for this change #7250.

Thanks
Mani
