### ISSUE TITLE
Update man page examples for "deprecated key derivation used" warning

### ISSUE THREAD

**Issue by blueyed** [openssl/openssl#7231]
I am using `-aes-256-cbc` to encrypt passwords/data used in my dotfiles.
The full command is `openssl enc -md sha256 -aes-256-cbc -a -A -salt -pass file:$PASSWDFILE"`.

Now I am seeing the following warning with that:

```
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
```

1. I've noticed that the EXAMPLES in `enc(1)` have the same problem, where `des3` or `bf` is used.
2. should I re-encrypt my passwords using `-pbkdf2`?

**Comment by kroeckx** [comment]
> 2. should I re-encrypt my passwords using `-pbkdf2`?

Yes

**Comment by mattcaswell** [comment]
> Then likely the examples in the man page should get fixed also, right?

Yes - they probably should.

**Comment by sfetome** [comment]
> 2. should I re-encrypt my passwords using `-pbkdf2`?
> Yes

But

* Q1 how can i get workaround this?
i know it is security vulnerability.
but not all of my clients shipped with the openssl version 1.0.2+

since it is not just a warning, it stops the decryption process.
how can i get workaround this make it supported by old openssl version?

* Q2: i am previously using the des3. it has such warning.
i then tried the aes256-cfb, it has such warning also.
any suggested on encryption method that could be supported down to 0.9.8?

**Comment by MichaIng** [comment]
@sfetome 
Which OpenSSL version do you use where it is not just a warning?
Until at least `1.1.1a` it is just a warning and decryption works still well, at least with `-aes-256-cbc`,  `-aes-256-cfb` and `-des3`.

**Comment by kaduk** [comment]
The 0.9.8 releases are not supported anymore, so my knowledge of them is hazy, but I don't believe there are any algorithms available there that are consistent with modern best practices.

**Comment by sfetome** [comment]
I was using git-windows Git-2.21.0-64-bit.exe

**Comment by sfetome** [comment]
@kaduk 
> The 0.9.8 releases are not supported anymore, so my knowledge of them is hazy, but I don't believe there are any algorithms available there that are consistent with modern best practices.

yes you are right. but it broke my data, i can't mirage to another encryption method.

**Comment by sfetome** [comment]
[plain.txt](https://github.com/openssl/openssl/files/2949232/plain.txt)
encrypt with below command with password 7231
```
sfetome@maclan bin $ openssl enc -e -aes-256-cbc -in plain.txt -out plain.aes256 -pass pass:7231
```
[plain.aes256.is.not.txt](https://github.com/openssl/openssl/files/2949231/plain.aes256.is.not.txt)

### window  cmd error
```cmd
E:\plain>openssl enc -d -aes-256-cbc -in plain.aes256 -pass pass:7231

ù|çˆÓSÛ½yÁ–¯³V5u*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
2932:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../openssl-1.1.1a/crypto/evp/evp_enc.c:537:

E:\plain>openssl version
OpenSSL 1.1.1a  20 Nov 2018
```

### can be decrypted on the mac natively
```
sfetome@maclan bin $ openssl enc -e -aes-256-cbc -in plain.txt -out plain.aes256 -pass pass:7231

sfetome@maclan bin $ openssl enc -d $opt -aes-256-cbc -in plain.aes256 -pass pass:7231
this is plain for issue 7231


sfetome@maclan bin $ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
```

**Comment by MichaIng** [comment]
@blueyed 
> $opt

What does this variable contain on your mac?

As you encrypt on your mac and decrypt on Windows, I guess the issue as due to different default options of the openssl command. I tend to set most options actively, e.g:
```
openssl enc -e -a -aes-256-cbc -salt -in plain.txt -out plain.aes256 -pass pass:7231
openssl enc -d -a -aes-256-cbc -salt -in plain.aes256 -pass pass:7231
```
- So the use of salt and base64 is forced.

**Comment by mattcaswell** [comment]
@sfetome This could be another issue unrelated to the "deprecated key derivation" warning. In particular see:

https://www.openssl.org/docs/faq.html#USER3

In other words add "-md md5" to your command line when using OpenSSL 1.1.x to decrypt data encrypted with 0.9.8

**Comment by sfetome** [comment]
@MichaIng 
> > $opt
> What does this variable contain on your mac?
it is empty. i have tried to pass --pbkdf2 as efault option with it on windows. but i was not lucky

> * So the use of salt and base64 is forced.
use the same without salt option before.

**Comment by sfetome** [comment]
@mattcaswell 
> https://www.openssl.org/docs/faq.html#USER3
>>
>>Why do I get errors when trying to decrypt 1.0.2 data with 1.1.0?
>>>A message digest is used to create the encrypt/decrypt key from a human-entered passphrase. In OpenSSL 1.1.0 we changed from MD5 to SHA-256. We did this as part of an overall change to move away from the now-insecure and broken MD5 algorithm. If you have old files, use the "-md md5" flag to decrypt them.


> 
> In other words add "-md md5" to your command line when using OpenSSL 1.1.x to decrypt data encrypted with 0.9.8

put ```-md md5``` option on command line encrypted data **decrypted successfully**.


Q: but why did you set sha256 as the default value.
it breaks the command line.
some users might drop the idea of upgrading to the more secure new version just because of changing of command line or don't want to figure it out.

**Comment by mattcaswell** [comment]
> but why did you set sha256 as the default value.

Because the old default (md5) is broken and no longer considered secure.

**Comment by MichaIng** [comment]
Okay so the decryption issue was indeed not related to the `pbkdf2` warning but a changed default: `-md md5` => `-md sha256`
So it makes sense when moving encrypted data between different platforms to define all parameters explicitly.
____________________
I hope this closes now the digression to come back to the man page example updates 😄.

**Comment by maxwell-k** [comment]
I think that the [examples](https://github.com/openssl/openssl/blob/master/doc/man1/enc.pod#examples) were updated in https://github.com/openssl/openssl/commit/eadde90bff01a6755399a4e1f6a3e4a9ed0fd61d and that this issue can be closed. https://github.com/openssl/openssl/pull/7248 says that it fixes this issue.

**Comment by mattcaswell** [comment]
Closing as per comment above.
