### ISSUE TITLE
EDDSA produces incorrect signature if signature is inside buffer to sign

### ISSUE THREAD

**Issue by orignal** [openssl/openssl#7232]
openssl 1.1.1 release

```
EVP_PKEY *pkey = EVP_PKEY_new_raw_private_key (EVP_PKEY_ED25519, NULL, key, 32);
EVP_MD_CTX * mdctx = EVP_MD_CTX_create();
uint8_t buf[100], buf1[100],* sig;
sig = buf + 36; // 100 - 64
memcpy (buf1, buf, 100);
EVP_DigestSignInit (mdctx, NULL, NULL, NULL, pkey);
size_t len = 64;
EVP_DigestSign (mdctx, sig, &len, buf, 100); 
```
Signature verification fails against buf1 (original content).

My expectation that original content must be taken, then SHA512 calculated and then resulting signature stored.
I'm not sure if it's bug or it works as designed in case of EDDSA. 
If it's expected behavior, would be nice to mention in the docs.

**Comment by t8m** [comment]
I do not think we are going to fix this "inefficiency". Closing.
