### ISSUE TITLE
Default Fips DRBG cannot call Rand_poll() during the reseed process

### ISSUE THREAD

**Issue by laogaolao** [openssl/openssl#7240]
I call the FIPS_mode_set(1), then call RAND_pseudo_bytes for more than 1 << 24 times to trigger the reseed process, but Rand_poll() still cannot be called during the reseed process.

**Comment by laogaolao** [comment]
Yes, I am using OpenSSL 1.0.2o with Fips 2.0.16.
But I am very confused about this. If we don't set Fips mode, system will call ssleay_rand_cleanup to clean the global variable **initialized**, and it will call the Rand_poll to get fresh entropy in reseed process. But the cleanup method for Fips doesn't do this, I don't know why.

**Comment by mspncp** [comment]
> ...system will call ssleay_rand_cleanup...

Who is "the system" and when does it call the cleanup function?

I don't see `RAND_cleanup()/ssleay_rand_cleanup()` called anywhere inside the library itself, only from application code:

```make
util/libeay.num:457:RAND_cleanup                            465	EXIST::FUNCTION:
crypto/rand/rand_lib.c:133:void RAND_cleanup(void)
crypto/rand/rand.h:100:void RAND_cleanup(void);
crypto/rand/md_rand.c:160:static void ssleay_rand_cleanup(void);
crypto/rand/md_rand.c:170:    ssleay_rand_cleanup,
crypto/rand/md_rand.c:181:static void ssleay_rand_cleanup(void)
apps/speed.c:2168:        RAND_cleanup();
apps/speed.c:2263:        RAND_cleanup();
apps/speed.c:2356:        RAND_cleanup();
apps/apps.h:192:                        RAND_cleanup(); \
apps/apps.h:203:                        RAND_cleanup(); \
doc/crypto/RAND_add.pod:69:L<RAND_load_file(3)|RAND_load_file(3)>, L<RAND_cleanup(3)|RAND_cleanup(3)>
doc/crypto/RAND_load_file.pod:46:L<rand(3)|rand(3)>, L<RAND_add(3)|RAND_add(3)>, L<RAND_cleanup(3)|RAND_cleanup(3)>
doc/crypto/RAND_set_rand_method.pod:49:RAND_bytes(), RAND_cleanup(), RAND_add(), RAND_pseudo_rand()
doc/crypto/RAND_egd.pod:76:L<RAND_cleanup(3)|RAND_cleanup(3)>
doc/crypto/RAND_cleanup.pod:5:RAND_cleanup - erase the PRNG state
doc/crypto/RAND_cleanup.pod:11: void RAND_cleanup(void);
doc/crypto/RAND_cleanup.pod:15:RAND_cleanup() erases the memory used by the PRNG.
doc/crypto/RAND_cleanup.pod:19:RAND_cleanup() returns no value.
doc/crypto/RAND_cleanup.pod:27:RAND_cleanup() is available in all versions of SSLeay and OpenSSL.
doc/crypto/rand.pod:30: void RAND_cleanup(void);
doc/crypto/rand.pod:173:L<RAND_cleanup(3)|RAND_cleanup(3)> 
doc/ssleay.txt:4973:void RAND_cleanup();
```

**Comment by laogaolao** [comment]
yes, you are right, cleanup will be called by application

**Comment by mspncp** [comment]
I was too pessimistic. Now I believe that in contrary to the DRBG on the master branch, an automatic reseeding will do no harm, because the SSLEAY PRNG does not maintain an error state.

See pull request #7247 for full details.

**Comment by laogaolao** [comment]
For the modification in the rand_lib.c, the comments:
     * Note: it is threadsafe to increment the counter, since RAND_bytes()
     * takes the CRYPTO_LOCK_RAND somewhere up the stack.
     */
I don't see any lock in the source code, could you give more hint for this? Thanks.

**Comment by mspncp** [comment]
@laogaolao thank you for asking this question. It showed me, that this note is actually not helpful and rather distracting. I will give you a more detailed answer to your question later, when I have more time. For the moment, I decided to remove the Note entirely.

**Comment by mspncp** [comment]
> I don't see any lock in the source code, could you give more hint for this? Thanks.

As I already mentioned in my last reply, my note was far too technical and in this particular case practically irrelevant. Because the point is that the access to the entire random generator (not only to the counter) needs to be synchronized in a multithreaded application.  The RAND API normally takes care of this automatically (provided the application has set the [locking callbacks](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/doc/crypto/threads.pod#description) during initialization). So if the application calls `RAND_bytes()`, the `CRYPTO_LOCK_RAND` lock will be taken internally before generating the  random bytes.  Since reseeding happens during generation of random bytes, it follows that the `CRYPTO_LOCK_RAND` lock is held in `rand_drbg_reseed()`. (`CRYPTO_LOCK_RAND` is actually just an index in an array of locks provided by the application).

That's all the comment was about. I hope this information adds to your stock of useless knowledge ;-).


```make
msp@msppc:~/src/openssl-1.0.2$ grep -rnH CRYPTO_LOCK_RAND crypto
crypto/rand/md_rand.c:148:                                           * holds CRYPTO_LOCK_RAND (to
crypto/rand/md_rand.c:150:/* access to lockin_thread is synchronized by CRYPTO_LOCK_RAND2 */
crypto/rand/md_rand.c:223:        CRYPTO_r_lock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:225:        CRYPTO_r_unlock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:230:        CRYPTO_w_lock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:262:        CRYPTO_w_unlock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:315:        CRYPTO_w_lock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:328:        CRYPTO_w_unlock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:393:        CRYPTO_w_lock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:396:    CRYPTO_w_lock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:398:    CRYPTO_w_unlock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:473:        CRYPTO_w_unlock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:531:        CRYPTO_w_lock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:535:            CRYPTO_w_unlock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:539:        CRYPTO_w_unlock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:583:        CRYPTO_r_lock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:585:        CRYPTO_r_unlock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:590:        CRYPTO_w_lock(CRYPTO_LOCK_RAND);
crypto/rand/md_rand.c:595:        CRYPTO_w_lock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:597:        CRYPTO_w_unlock(CRYPTO_LOCK_RAND2);
crypto/rand/md_rand.c:612:        CRYPTO_w_unlock(CRYPTO_LOCK_RAND);
crypto/crypto.h:205:# define CRYPTO_LOCK_RAND                18
crypto/crypto.h:206:# define CRYPTO_LOCK_RAND2               19
```

**Comment by laogaolao** [comment]
@mspncp Thanks for your explaination, that's helpful.

**Comment by mspncp** [comment]
@laogaolao would you mind trying #7259 for me and let me know whether it works as you expect? Thanks!

**Comment by laogaolao** [comment]
@mspncp Sure, I have make the change in our system, but still need to wait the bsp guy to finish the random device work, because we should get the seeds from this new random device instead of the /dev/urandom

**Comment by mspncp** [comment]
Well, /dev/urandom will be good enough for me...   ;-)

**Comment by mspncp** [comment]
The fix has now been merged.  Thanks @laogaolao for reporting the issue!
