### ISSUE TITLE
Change in 'openssl verify' behavior from 1.0.2 to 1.1.0

### ISSUE THREAD

**Issue by tmshort** [openssl/openssl#7245]
It looks as though commit d9e309a6 caused a behavior change in the `openssl verify` command, specifically with self-signed certificates.

In 1.0.2, it would report that a self-signed certificate was self-signed, but then succeed. There were special checks in the `cb()` to see if certain errors occured (e.g. `X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT`), and indicate that it was OK.

In 1.1.0, the same checks are in `cb()`, but then the `check()` functions looks to see if `X509_verify_cert()` succeeds, and if it does, looks at the `X509_STORE_CTX_get_error()`, which returns the errors that were exempted out of `cb()` if they occur.

1.0.2 code:
```
    i = X509_verify_cert(csc);
    X509_STORE_CTX_free(csc);

    ret = 0;
 end:
    if (i > 0) {
        fprintf(stdout, "OK\n");
        ret = 1;
    } else
        ERR_print_errors(bio_err);
```

1.1.0 code:
```
    i = X509_verify_cert(csc);
    if (i > 0 && X509_STORE_CTX_get_error(csc) == X509_V_OK) {
        printf("%s: OK\n", (file == NULL) ? "stdin" : file);
        ret = 1;
        if (show_chain) {
            int j;

            chain = X509_STORE_CTX_get1_chain(csc);
            num_untrusted = X509_STORE_CTX_get_num_untrusted(csc);
            printf("Chain:\n");
            for (j = 0; j < sk_X509_num(chain); j++) {
                X509 *cert = sk_X509_value(chain, j);
                printf("depth=%d: ", j);
                X509_NAME_print_ex_fp(stdout,
                                      X509_get_subject_name(cert),
                                      0, XN_FLAG_ONELINE);
                if (j < num_untrusted)
                    printf(" (untrusted)");
                printf("\n");
            }
            sk_X509_pop_free(chain, X509_free);
        }
    } else {
        printf("error %s: verification failed\n", (file == NULL) ? "stdin" : file);
    }
```

**Comment by tmshort** [comment]
1.0.2 prints "OK" and returns a 0 (success) error code, 1.1.0 does not print "OK" and returns a 2 (error) error code.

Errors ARE printed on stdout, however, in both cases.

This is not limited to self-signed certs, but could also impacts expired certs, etc.

If people thought that 1.0.2 was simply broken, I'm ok with that.

**Comment by t8m** [comment]
This was intentional behavior change which is not going to be reverted. Closing.
