### ISSUE TITLE
set_ciphersuites function should be static or renamed ssl_internal_set_ciphersuites 

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#7252]
See ssl_ciph.c:1304

`int set_ciphersuites(STACK_OF(SSL_CIPHER) **currciphers, const char *str)`

This should be static and renamed ssl_internal_set_ciphersuites ...

**Comment by mspncp** [comment]
I can make that change for you. However, there are other static int functions which don't carry the `internal` in their name. So I would leave the name unchanged if that's ok for you.

**Comment by mspncp** [comment]
E.g. `static int update_cipher_list_by_id(...)` and `static int update_cipher_list(...)`.

**Comment by mspncp** [comment]
See #7253.
