### ISSUE TITLE
error:14212044:SSL routines:tls_construct_ctos_early_data:internal error:ssl/statem/extensions_clnt.c:801:

### ISSUE THREAD

**Issue by MWoscek** [openssl/openssl#7261]
140494829385536:error:14212044:SSL routines:tls_construct_ctos_early_data:internal error:ssl/statem/extensions_clnt.c:801:

The issue is TLS13_MAX_RESUMPTION_PSK_LENGTH is set to 64. However,  TLSv1.3 PSK length should be 256 bytes.  

ssl_locl.h :
# define TLS13_MAX_RESUMPTION_PSK_LENGTH      64
unsigned char master_key[TLS13_MAX_RESUMPTION_PSK_LENGTH];

 Just verified on my system using the latest openssl that modifying the TLS13_MAX_RESUMPTION_PSK_LENGTH    to 256 fixes the above error.

**Comment by mattcaswell** [comment]
Fix in #7267.
