### ISSUE TITLE
Random seeding for FIPS

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#7262]
As part of the FIPS 140-2 project, there need to be some additional changes to the random number generation infrastructure.  FIPS 140-2 has a requirement for continuous random number generation tests (CRNG) to be run.  These are outlined on page number 36 of the [FIPS 140-2](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf) document:
> _Continuous random number generator test_. If a cryptographic module employs Approved or non-Approved RNGs in an Approved mode of operation, the module shall perform the following continuous random number generator test on each RNG that tests for failure to a constant value.
> 1. If each call to a RNG produces blocks of _n_ bits (where _n_ > 15), the first _n_-bit block generated after power-up, initialization, or reset shall not be used, but shall be saved for comparison with the next _n_-bit block to be generated. Each subsequent generation of an _n_-bit block shall be compared with the previously generated block. The test shall fail if any two compared _n_-bit blocks are equal.
> 2. If each call to a RNG produces fewer than 16 bits, the first _n_ bits generated after power-up, initialization, or reset (for some _n_ > 15) shall not be used, but shall be saved for comparison with the next _n_ generated bits. Each subsequent generation of _n_ bits shall be compared with the previously generated _n_ bits. The test fails if any two compared _n_-bit sequences are equal.

The same testing is repeated on page number 95 of the [FIPS 140-2 Derived Test Requirements](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Module-Validation-Program/documents/fips140-2/FIPS1402DTR.pdf) document.  The testing requirements are expounded upon somewhat confusingly in section _9.8 Continuous Random Number Generator Tests_ by the [FIPS 140-2 implementation guidance](https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/fips140-2/fips1402ig.pdf) document.  However, this doesn't appear to be relevant at this point because [SP 800-90A](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf) hasn't been finalised yet.

The upshot of all of this is that we need to include a CRNG test when operating in a FIPS 140-2 environment.  Because this involves discarding some data, it should not be made mandatory outside of FIPS 140-2.  The CRNG testing needs to check the blocks being fed **into** our master (`master_drbg`) from our various entropy sources.  It does **not** need to be performed for any of the DRBG that chain from the master.

In essence, the master DRBG will need to save the previous block of seed material it used.  When reseeding, it must confirm that the new seed material is different to the saved block.  It then consumes the new seed block and saves it for comparison during the _next_ reseed operation.  The natural size for the block would be the seed length for the DRBG, although smaller might be permissible.

There is one nuance at startup: the first block of entropy gathered is **not** used as seed material.  Instead, it must be saved and a second block obtained for seeding purposes.  The second block is compared to the first before discarding the first and actually seeding the master DRBG.

If we have several different seed sources available, there is no need for the CRNG testing to be done _separately_ for each.  We can agglomerate their output into a single pool which is used to seed the master DRBG.

**Comment by paulidale** [comment]
@kroeckx @mspncp

**Comment by paulidale** [comment]
An update: it is okay to choose a block size that is smaller than the DRBG seed length.

I posit a 64 bit block size.  This is a balance between reaping and discarding too much entropy from the operating system and the probability of accidentally getting a duplicated block.

**Comment by t-j-h** [comment]
16 bytes (i.e. 128-bit) is a normal block size in this sort of context but smaller would also be workable.

**Comment by paulidale** [comment]
I believe we seed using 384 bits, a 128 bit block would mean reading 512 bits.  A 64 bit block reads 448 bits.  The choice is where to place the trade off? 

I vaguely remember a guidance suggesting the probability of failure for this test be in the range 2<sup>32</sup> to 2<sup>-40</sup>.  I can't find the reference and am likely wrong about the context.

**Comment by paulidale** [comment]
This was addressed by #8599 
Closing.
