### ISSUE TITLE
X509_REQ_sign() error with EVP_SM3

### ISSUE THREAD

**Issue by MasterMeng** [openssl/openssl#7266]
When using X509_REQ_sign() with EVP_SM3, reported error: "elloptic curve routines:pkey_ec_ctrl:invalid digest type"

**Comment by mattcaswell** [comment]
The SM* support is largely limited to access via the EVP layer at the moment. Integration into X509 is not there yet, e.g. see #6837, #6579.

**Comment by MasterMeng** [comment]
Thanks a lot
