### ISSUE TITLE
`openssl smime -crl_check` works only when I provide `-CAfile`

### ISSUE THREAD

**Issue by colotiline** [openssl/openssl#7268]
Hi.

## Setup
1. CentOS 7.
2. OpenSSL 1.0.2k-fips  26 Jan 2017.

## Purpose
I want to verify CMS with `-crl_check`.

## Steps to reproduce
1. Add GOST support to openssl.
2. Generate certificate here https://www.cryptopro.ru/certsrv/.
3. Copy root and CRL from https://www.cryptopro.ru/certsrv/certcarc.asp.
4. Convert root by `openssl x509 -inform DER -in /home/certnew.cer -out crypto-cert.pem`.
5. Convet CRL by `openssl crl -in certcrl.crl -inform der -out certcrl.pem`.
6. Combine root and CRL by `cat crypto-cert.pem certcrl.pem > crypto-cert-combine.pem`.
7. Copy `crypto-cert-combine.pem` to `/etc/pki/ca-trust/source/anchors/`.
8. Execute `update-ca-trust`.

## Expected behaviour
Run `openssl smime -verify -crl_check -inform DER -in /home/cms.bin -content /home/message.txt` and get response:
```
Hi.
Verification successful
```

## Actual behaviour
Get response:
```
Verification failure
140580621272976:error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:pk7_smime.c:336:Verify error:unable to get certificate CRL
```

## Workaround
Run `openssl smime -verify -crl_check -inform DER -in /home/cms.bin -content /home/message.txt -CAfile /etc/pki/ca-trust/source/anchors/crypto-cert-combine.pem`. 

Response:
```
Hi.
Verification successful
```

## Why workaround is not applicable
I've got around 400-500 combined roots and CRLs and I'm not sure that it's a good idea to go through them all until I have a success or all of them failed.

## Questions
* Is this the expected behaviour?
* Is there any option to don't use the workaround (`-CApath` changes nothing)?

## Attachments
[cms-and-message.zip](https://github.com/openssl/openssl/files/2396327/cms-and-message.zip)

**Comment by algv** [comment]
This is expected behaviour. If you set -crl_check, openssl [add flag](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/apps/apps.c#L2361) for checks end entity certificate validity by attempting to look up a valid CRL. If a valid CRL cannot be found an error occurs.

Certificates verifing in [check_cert(X509_STORE_CTX *ctx)](https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/crypto/x509/x509_vfy.c#L867). There you can see, what if cannot finde CRL [return error](https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/crypto/x509/x509_vfy.c#L894)

**Comment by colotiline** [comment]
@algv could you say where openssl looks for valid CRL by default in CentOS? And what does "valid" mean?

**Comment by algv** [comment]
First openssl serach CRL [by "score"](https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/crypto/x509/x509_vfy.c#L1150) (it some criterias by issuer name, and, most newer...). Then [check CRL validaty](https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/crypto/x509/x509_vfy.c#L1485). Valid CRL is actual by time and have correct signature.

In CentOS and any other systems need give path to CRL. May be help:  https://github.com/openssl/openssl/issues/1701

**Comment by t8m** [comment]
CentOS uses /etc/pki/tls/cert.pem as the default CA bundle path.
