### ISSUE TITLE
openssl-1.1 lost the ability to find engine(s)

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#727]
```
$ ~/src/openssl-1.1/bin/openssl engine pkcs11 -t
140735268914000:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:172:filename(/Users/ur20980/src/openssl-1.1/lib/engines/pkcs11.dylib): dlopen(/Users/ur20980/src/openssl-1.1/lib/engines/pkcs11.dylib, 2): image not found
140735268914000:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:220:
140735268914000:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:456:
140735268914000:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:372:id=pkcs11
$
```

As you can see, after the last couple of commits it stopped looking for **`libpkcs11.dylib`** and started looking for **`pkcs11.dylib`**. Below is the proof:
```
$ ln -s /Users/ur20980/src/openssl-1.1/lib/engines/libpkcs11.dylib /Users/ur20980/src/openssl-1.1/lib/engines/pkcs11.dylib
$ ~/src/openssl-1.1/bin/openssl engine pkcs11 -t
(pkcs11) pkcs11 engine
     [ available ]
$
```

While the workaround isn't terribly complicated, I think the original behavior needs to be restored.

**Comment by levitte** [comment]
Here's the commit where that name change happened:

```
commit 9ee0ed3de66678a15db126d10b3e4226e835b8f5
Author: Richard Levitte <levitte@openssl.org>
Date:   Mon Feb 15 18:29:09 2016 +0100

    Big rename fest of engine DSO names, from libFOO.so to FOO.so
    
    The engine DSOs were named as if they were shared libraries, and could
    end up having all sorts of fancy names:
    
      Cygwin: cygFOO.dll
      Mingw:  FOOeay32.dll
      Unix:   libFOO.so / libFOO.sl / libFOO.dylib / ...
    
    This may be confusing, since they look like libraries one should link
    with at link time, when they're just DSOs.
    
    It's therefore time to rename them, and do it consistently on all
    platforms:
    
      Cygwin & Mingw: FOO.dll
      Unix:           FOO.{so,sl,dylib,...}
    
    Interestingly enough, the MSVC and VMS builds always did it this way.
    
    Reviewed-by: Andy Polyakov <appro@openssl.org>

```

It was an informed decision, and a calculated one from my perspective.  Of course this would mean old habit hit a wall.

I suggest that engine_pkcs11 build a DSO called `pkcs11.dylib` / `pkcs11.so` / `pkcs11.dll` / etc for OpenSSL 1.1 and on.

**Comment by mouse07410** [comment]
> It was an informed decision, and a calculated one from my perspective.
> Of course this would mean old habit hit a wall.

OK, got it.

> I suggest that engine_pkcs11 build a DSO called pkcs11.dylib / pkcs11.so / pkcs11.dll / etc
> for OpenSSL 1.1 and on.

Got it. Will bring it up to the libp11 maintainers.

Thanks!

**Comment by levitte** [comment]
You're welcome.  Sorry if I came out harsh

**Comment by mouse07410** [comment]
Apology accepted but unnecessary - I find your response perfectly polite and to the point.

**Comment by deekshith565** [comment]
Hi,

I get the following error can anyone help please?

OpenSSL> engine dynamic -pre "SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre "MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll"
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
13280:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\pkcs11.dll)
13280:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
13280:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
[Failure]: MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll
13280:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
13280:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:

**Comment by deekshith565** [comment]
I think so, I have built PKCS11 engine from https://github.com/OpenSC/libp11/blob/master/INSTALL.md using MSYS2 installation process, by cloning git  https://github.com/OpenSC/libp11.git

there the version is OpenSSL 1.0.2m  2 Nov 2017
