### ISSUE TITLE
Inconsistent cipher lists across documentation

### ISSUE THREAD

**Issue by evqna** [openssl/openssl#7273]
Currently, information about what ciphers are available for encryption is spread across different parts of the documentation: the manual pages for the openssl command line tool and the _**enc**_ subprogram, as well as the `openssl enc -ciphers` command output.

Assuming **_enc -ciphers_** is the canonical source of truth, the following inconsistencies appear:

Missing in _**openssl(1)**_:
- aes aliases:
  - aes[128|192|256]
  - aes-[128|192|256]-[cbc|cfb|cfb1|cfb8|ctr|ecb|ofb]
- camellia aliases:
  - camellia[128|192|256]
  - camellia-[128|192|256]-[cbc|cfb|cfb1|cfb8|ctr|ecb|ofb]
- 40 and 64 bit RC2/RC4:
  - rc2-40-cbc, rc2-64-cbc, rc4-40

Missing in _**openssl(1)**_ and **_enc(1)_**:
- (id-)?aes[128|192|256]-wrap
- id-aes[128|192|256]-wrap-pad
- aria aliases:
  - aria[128|192|256]
  - aria-[128|192|256]-[cbc|cfb|cfb1|cfb8|ctr|ecb|ofb]
- blowfish (alias to _bf-cbc_)
- chacha20
- des-ede-ecb (alias to _des-ede_)
- des-ede3-[cfb1|cfb8|ecb]
- des3-wrap (alias to _id-smime-alg-CMS3DESwrap_)
- desx-cbc
- id-smime-alg-CMS3DESwrap
- rc2 aliases:
  - rc2-[40|64|128]
- seed aliases:
  - seed
  - seed-[cbc|cfb|ecb|ofb]
- sm4 aliases:
  - sm4
  - sm4-[cbc|cfb|ctr|ecb|ofb]

And of course a few outliers:

Present in **_enc(1)_** but not supported:
- rc4-64

Present in _**openssl(1)**_ and **_enc(1)_** but not supported (due to compile options maybe?):
- rc5
- rc5-[cbc|cfb|ecb|ofb]

I did not try exhaustively but through random sampling it looks like most of the 'missing' aliases are recognized both as `openssl <cipher>` and `openssl enc -<cipher>` and as such should probably be mentioned in the manual.

Version info
-

`openssl version -a` output:

```OpenSSL 1.1.1  11 Sep 2018
built on: Tue Sep 11 14:26:06 2018 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
OPENSSLDIR: "/usr/local/etc/openssl@1.1"
ENGINESDIR: "/usr/local/Cellar/openssl@1.1/1.1.1/lib/engines-1.1"
Seeding source: os-specific
```

**Comment by InfoHunter** [comment]
> Present in openssl(1) and enc(1) but not supported (due to compile options maybe?):

Yes, RC5 is not enabled by default

**Comment by InfoHunter** [comment]
I am going to add some missing stuffs in the documentation to mitigate some misunderstandings from users.

**Comment by InfoHunter** [comment]
I update some stuffs in `enc` document, hope this helps

**Comment by InfoHunter** [comment]
And from my point of view, I think it's not necessary to document the 'not-encouraged' ciphers like RC2...

**Comment by richsalz** [comment]
I think a note at the end is sufficient, perhaps something like:
```
Depending on how OpenSSL was configured and built, not all ciphers listed here may be present.
```

**Comment by InfoHunter** [comment]
It seems some improvements have been made addressing this issue, could we close this issue now or is there further improvements need to be done for this? @evqna

**Comment by evqna** [comment]
It looks like the most important ones have been taken care of (AES, Camellia, Seed, ...). The rest seems very niche, so I'm fine with closing.
