### ISSUE TITLE
ASN1_put_object outputs wrong encoded bytes

### ISSUE THREAD

**Issue by fefe17** [openssl/openssl#7276]
```
163     if (tag < 31)
164         *(p++) = i | (tag & V_ASN1_PRIMITIVE_TAG);
165     else {
166         *(p++) = i | V_ASN1_PRIMITIVE_TAG;
```

This looks wrong to me. In the tag >= 31 case, you encode as if tag was 31 and then send the long-form length. This ode encodes as if tag was 0, or am I missing something?

166 should be:

`*(p++) = i | 31 | V_ASN1_PRIMITIVE_TAG;`

**Comment by levitte** [comment]
Uhmmm, how about I quote one single line from `include/openssl/asn1.h`:

``` C
# define V_ASN1_PRIMITIVE_TAG            0x1f
```

Is that good enough an explanation?
(reminder: 0x1f == 31)

**Comment by fefe17** [comment]
You are right, my mistake.
