### ISSUE TITLE
devcrypto RC4 table init issue

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#7280]
In the devcrypto code you have the following cipher definition table where the RC4 is missing a 'mode' value and when requesting the algorithm from /dev/crypto uses an ID of 0 which is an invalid algorithm.

```
    { NID_aes_128_cbc, 16, 128 / 8, 16, EVP_CIPH_CBC_MODE, CRYPTO_AES_CBC },
    { NID_aes_192_cbc, 16, 192 / 8, 16, EVP_CIPH_CBC_MODE, CRYPTO_AES_CBC },
    { NID_aes_256_cbc, 16, 256 / 8, 16, EVP_CIPH_CBC_MODE, CRYPTO_AES_CBC },
#ifndef OPENSSL_NO_RC4
    { NID_rc4, 1, 16, 0, CRYPTO_ARC4 },
#endif
```

**Comment by levitte** [comment]
Hi, would you mind checking if #7281 solves your problem?

**Comment by dlegaultbbry** [comment]
yes it does, thanks
