### ISSUE TITLE
MINGW-W64 and SOCKET type (should not be int)

### ISSUE THREAD

**Issue by JPeterMugaas** [openssl/openssl#7282]
I was compiling OpenSSL 1.1.1 release with GCC 8.2.0 and I got some warnings that I think need to be fixed.

===
[1;30mgcc  -I. -Icrypto/include -Iinclude -I../openssl-1.1.1 -I../openssl-1.1.1/crypto/include -I../openssl-1.1.1/include -m64 -Wall -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mingw64\"" -DENGINESDIR="\"/mingw64/lib/engines-1_1\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DZLIB -DZLIB_SHARED -DNDEBUG  -MMD -MF crypto/threads_win.d.tmp -MT crypto/threads_win.o -c -o crypto/threads_win.o ../openssl-1.1.1/crypto/threads_win.c[0m
../openssl-1.1.1/crypto/threads_win.c: In function 'CRYPTO_atomic_add':
[1;33m[1;33m../openssl-1.1.1/crypto/threads_win.c:154:35: warning:[0m[0m passing argument 1 of '_InterlockedExchangeAdd' from incompatible pointer type [-Wincompatible-pointer-types]
     *ret = InterlockedExchangeAdd(val, amount) + amount;
                                   ^~~
In file included from D:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:27

===
[1;30mgcc  -I. -Icrypto/include -Iinclude -I../openssl-1.1.1 -I../openssl-1.1.1/crypto/include -I../openssl-1.1.1/include -m64 -Wall -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mingw64\"" -DENGINESDIR="\"/mingw64/lib/engines-1_1\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DZLIB -DZLIB_SHARED -DNDEBUG  -MMD -MF crypto/bio/b_sock.d.tmp -MT crypto/bio/b_sock.o -c -o crypto/bio/b_sock.o ../openssl-1.1.1/crypto/bio/b_sock.c[0m
../openssl-1.1.1/crypto/bio/b_sock.c: In function 'BIO_get_accept_socket':
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock.c:202:13: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
     int s = INVALID_SOCKET;
             ^~~~~~~~~~~~~~
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock.c:207:16: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         return INVALID_SOCKET;
                ^~~~~~~~~~~~~~
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock.c:210:16: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         return INVALID_SOCKET;
                ^~~~~~~~~~~~~~
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock.c:217:13: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         s = INVALID_SOCKET;
             ^~~~~~~~~~~~~~
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock.c:224:13: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         s = INVALID_SOCKET;
             ^~~~~~~~~~~~~~
[1;30mgcc  -I. -Icrypto/include -Iinclude -I../openssl-1.1.1 -I../openssl-1.1.1/crypto/include -I../openssl-1.1.1/include -m64 -Wall -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mingw64\"" -DENGINESDIR="\"/mingw64/lib/engines-1_1\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DZLIB -DZLIB_SHARED -DNDEBUG  -MMD -MF crypto/bio/b_sock2.d.tmp -MT crypto/bio/b_sock2.o -c -o crypto/bio/b_sock2.o ../openssl-1.1.1/crypto/bio/b_sock2.c[0m
../openssl-1.1.1/crypto/bio/b_sock2.c: In function 'BIO_socket':
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock2.c:45:16: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         return INVALID_SOCKET;
                ^~~~~~~~~~~~~~
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock2.c:51:16: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         return INVALID_SOCKET;
                ^~~~~~~~~~~~~~
../openssl-1.1.1/crypto/bio/b_sock2.c: In function 'BIO_bind':
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock2.c:136:9: warning:[0m[0m unused variable 'on' [-Wunused-variable]
     int on = 1;
         ^~
../openssl-1.1.1/crypto/bio/b_sock2.c: In function 'BIO_accept_ex':
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock2.c:294:16: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         return INVALID_SOCKET;
                ^~~~~~~~~~~~~~
[1;33m[1;33m../openssl-1.1.1/crypto/bio/b_sock2.c:299:16: warning:[0m[0m overflow in conversion from 'long long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Woverflow]
         return INVALID_SOCKET;
                ^~~~~~~~~~~~~~
[1;30mgcc  -I. -Icrypto/include -Iinclude -I../openssl-1.1.1 -I../openssl-1.1.1/crypto/include -I../openssl-1.1.1/include -m64 -Wall -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mingw64\"" -DENGINESDIR="\"/mingw64/lib/engines-1_1\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DZLIB -DZLIB_SHARED -DNDEBUG  -MMD -MF crypto/bio/bf_buff.d.tmp -MT crypto/bio/bf_buff.o -c -o crypto/bio/bf_buff.o ../openssl-1.1.1/crypto/bio/bf_buff.c[0m
===

The problem seems to be a long standing issue. OpenSSL has defined things as an "int" type which is ALWAYS 32-bits (4 bytes wide) which is not like a typical Unix-like system where "int" may 8-bytes wide. SOCKET was defined as "UINT_PTR" in one version of the winsock2.h header and as u_int for 32-bit versions of Windows.  You can't always depend upon some values always being 32-bits wide.  Please feel free to examine and use patch I included in the .TXT file attached   I realize that this could possibly break some things but I think it might be worth doing given the discussion.  GCC has tightened up quite a bit on these warnings for good reason.

[win64-fixes.patch.txt](https://github.com/openssl/openssl/files/2401930/win64-fixes.patch.txt)

**Comment by dot-asm** [comment]
This is *long-known* [non-]problem, and suggested way is not right way to solve it.

As for "[non-]problem". The warning is formally warranted, but the implicit casts are safe to ignore. Quoting post from 2008 "Windows SOCKET is a handler to *kernel* object and as such constitutes an *offset* in per-process handle table. As this table can accommodate not more than 2^24 entries, it's always *safe* to cast/truncate SOCKET to 32-bit value and back. Even on 64-bit Windows." The reason for why the warning is not addressed is because it's argued that it's better to *not mask* the warning in wait for moment when it's appropriate to address it, between major releases. Which brings us to "way to solve it." OpenSSL aims to provide platform-neutral interface, which means that platform-specific headers such as winsock.h should not appear in public headers. Nor can we demand/expect that application developer includes platform-specific header prior openssl ones. This means that BIO socket interface should declare a neutral type for socket, one that would meet arbitrary demand, and only *then* choose appropriate casts to be used internally.

On related note. There are more spots where interface is platform-specific, that would be appropriate to resolve. timeval should be "appropriated" and a neutral replacement structure should be used, in interface dtsl1_ctrl. Time in general should be a neutral type, obviously 64-bit one, obviously with sub-second granularity. Well, with such type at hand it would probably be appropriate to omit timeval altogether. Then crypto.h shouldn't include pthread.h and naturally not use corresponding types, platform-neutral ones should be introduced and be internally casted to platform-specific...

**Comment by t8m** [comment]
Closing as we are not going to fix this per the reasoning above.
