### ISSUE TITLE
openssl-1.1.1, error when executing "make" 

### ISSUE THREAD

**Issue by DC-Buildman** [openssl/openssl#7288]
Following are the steps.
 
"./config --prefix=/u/build/build2/openssl/openssl.SYMC-1.1.1.shared/root/app/symc/packages/openssl.SYMC-1.1.1.shared shared zlib -L$baseLinkDir/lib -lz enable-ec_nistp_64_gcc_128"
"make depend"
"make"
 
I see this error
 
crypto/ec/ecp_nistp224.c:48:4: error: #error "Your compiler doesn't appear to support 128-bit integer types"
crypto/ec/ecp_nistp224.c:75: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'widelimb'
crypto/ec/ecp_nistp224.c:78: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'widefelem'
crypto/ec/ecp_nistp224.c:426: error: expected ')' before 'out'
crypto/ec/ecp_nistp224.c:454: error: expected ')' before 'out'
crypto/ec/ecp_nistp224.c:491: error: expected ')' before 'out'
crypto/ec/ecp_nistp224.c:503: error: expected ')' before 'out'
crypto/ec/ecp_nistp224.c:519: error: expected ')' before 'out'
crypto/ec/ecp_nistp224.c:537: warning: type defaults to 'int' in declaration of 'widefelem'
crypto/ec/ecp_nistp224.c:537: error: expected ';', ',' or ')' before 'in'
crypto/ec/ecp_nistp224.c: In function 'felem_square_reduce':
crypto/ec/ecp_nistp224.c:603: error: 'widefelem' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:603: error: (Each undeclared identifier is reported only once
crypto/ec/ecp_nistp224.c:603: error: for each function it appears in.)
crypto/ec/ecp_nistp224.c:603: error: expected ';' before 'tmp'
crypto/ec/ecp_nistp224.c:604: warning: implicit declaration of function 'felem_square'
crypto/ec/ecp_nistp224.c:604: error: 'tmp' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:605: warning: implicit declaration of function 'felem_reduce'
crypto/ec/ecp_nistp224.c: In function 'felem_mul_reduce':
crypto/ec/ecp_nistp224.c:610: error: 'widefelem' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:610: error: expected ';' before 'tmp'
crypto/ec/ecp_nistp224.c:611: warning: implicit declaration of function 'felem_mul'
crypto/ec/ecp_nistp224.c:611: error: 'tmp' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c: In function 'felem_neg':
crypto/ec/ecp_nistp224.c:678: error: 'widefelem' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:678: error: expected ';' before 'tmp'
crypto/ec/ecp_nistp224.c:679: warning: implicit declaration of function 'felem_diff_128_64'
crypto/ec/ecp_nistp224.c:679: error: 'tmp' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c: In function 'felem_inv':
crypto/ec/ecp_nistp224.c:713: error: 'widefelem' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:713: error: expected ';' before 'tmp'
crypto/ec/ecp_nistp224.c:716: error: 'tmp' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c: In function 'point_double':
crypto/ec/ecp_nistp224.c:830: error: 'widefelem' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:830: error: expected ';' before 'tmp'
crypto/ec/ecp_nistp224.c:837: error: 'tmp' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:888: error: 'tmp2' undeclared (first use in this function)
crypto/ec/ecp_nistp224.c:890: warning: implicit declaration of function 'widefelem_scalar'
 
earlier for openssl-1.1.0i, I used the same steps.
 
 
I have attached the dump . Please suggest the resolution for this issue.
 
Thanks,
Vinay
[perl-configdata-dump.txt](https://github.com/openssl/openssl/files/2404964/perl-configdata-dump.txt)

**Comment by dot-asm** [comment]
> #error "Your compiler doesn't appear to support 128-bit integer types"

Just don't use enable-ec_nistp_64_gcc_128. It's humanly impossible to test all compiler versions and one can't expect that extension code, such as one in question, keeps working with arbitrarily old compiler in newer release. In this particular case the compiler feature detection was replaced with more reliable and unified. Requirements are listed in INSTALL. Well, one can cheat by passing `-D__SIZEOF_INT128__=16` to config, but formally you'd be better off not using the enable option.
