### ISSUE TITLE
SSL_ERROR_SSL / EAGAIN on large datachunks in non-blocking multithreaded mode error

### ISSUE THREAD

**Issue by hello983834** [openssl/openssl#7291]
OpenSSL 1.1.1
SSL_ctx_set_mode set to SSL_MODE_ENABLE_PARTIAL_WRITE | SSL_MODE_ASYNC | SSL_MODE__ACCEPT_MOVING_WRITE_BUFFER
The problem didn't happen with OpenSSL 1.0.2.

SSL_write on a buffer of 150k - 750k sometimes returns -1 and SSL_get_error returns SSL_ERROR_SSL after a tls handshake has been done and data has already been received.
An strace shows that the underlying write()-call writes multiple 16406 byte packets with the last only being able to write 14147 bytes of the 16406 bytes. Then the final write of 2259 gets an EAGAIN error. Errno is also set to EAGAIN and SSL_want_write() also return true.

1.
I would assume SSL_get_error should return SSL_ERROR_WANT_WRITE, not SSL_ERROR_SSL

2.
Calling ERR_get_error() however says "shutdown while in init". This isn't possible as the connection is already setup. I might do this wrong since I have a special thread setup and aren't clearing previous errors. The connection is established randomly in 1of 4 non-blocking/async threads. When the connection have exchanged acceptable amount of data, the connection is transferred to a worker thread for further processing.

**Comment by mattcaswell** [comment]
> Calling ERR_get_error() however says "shutdown while in init". This isn't possible as the connection is already setup.

What protocol version does this happen with? It is possible to re-enter "init" after the connection set up, e.g. during a reneg for TLSv1.2. In TLSv1.3 this can happen while processing post-handshake messages.

In order for you to get that error message you must have already called SSL_shutdown() (its the only place in the code where the error gets raised). But if so, it doesn't make sense to be calling SSL_write() after such a call. So something seems a little odd.

**Comment by hello983834** [comment]
It happends with both tls 1.2 and 1.3.
I am positive I didn't call ssl_shutdown for that connection (and the same code worked with 1.0.2), but it is possible another connection in the same thread called it previously.
x

**Comment by mattcaswell** [comment]
Make sure you call `ERR_clear_error()` after any errors. If you have stale errors on the error queue `SSL_get_error()` is going to get confused.

**Comment by hello983834** [comment]
That seem to have solved the SSL_get_error()-problem :)
However this is probably not a very optimal solution.  The worker threads call many functions, including third party library calls. To guarantee that I handle all scenarios I should call ERR_clear_error() before every ssl_write.

while (all_is_good)
{
   process_stuff_and_get_more_data();
  ERR_clear_error() ;
  ssl_write();
}
