### ISSUE TITLE
How to uses openssl achieve my own function

### ISSUE THREAD

**Issue by terrantsh** [openssl/openssl#7292]
i want to use openssl ahcieve my .pem to encrypt

**Comment by mspncp** [comment]
Hello @terrantsh, this GitHub site is for developing OpenSSL, for reporting issues or for submitting pull requests. If you have general questions about using OpenSSL, it is better if you post your questions to the openssl-users mailinglist, see https://mta.openssl.org/mailman/listinfo/openssl-users.

Hope that helps
