### ISSUE TITLE
shlib_variant not compatible with SHLIB_VERSION_NUMBER= SHLIB_EXT=.so 

### ISSUE THREAD

**Issue by misery** [openssl/openssl#7295]
I tried new shlib_variant feature with v1.1.1 here.

I added shlib_variant '-gov' to Configuration/15-android.conf. It works flawlessly with default values of SHLIB_VERSION_NUMBER and SHLIB_EXT.

But if I call "make SHLIB_VERSION_NUMBER= SHLIB_EXT=.so" the "make install_sw" target will fail here.

```
[...]
created directory `/tmp/dummy/lib'
install libcrypto.a -> /tmp/dummy/lib/libcrypto.a
install libssl.a -> /tmp/dummy/lib/libssl.a
install libcrypto-gov.so.1.1 -> /tmp/dummy/lib/libcrypto-gov.so.1.1
cp: cannot stat 'libcrypto-gov.so.1.1': No such file or directory
```

It still tries to install .1.1 suffix.

**Comment by misery** [comment]
By the way... is it possible to pass shlib_variant as cmdline config or do I need to patch the sources? And the other way around: Is it possible to pass SHLIB_VERSION_NUMBER and SHLIB_EXT in the same manner I can do for shlib_variant?

**Comment by misery** [comment]
Sorry, I missed that I need to pass SHLIB_VERSION_NUMBER= SHLIB_EXT=.so to "make install_sw", too.

So it is another reason to make it easier to use. :-)

**Comment by levitte** [comment]
There's nothing stopping you from making your own android config target that simply adds `shlib_variant`, in your own file.  The contents would be as simple as this:

``` perl
(
    'my_android' => {
        inherit_from  => [ 'INSERT_ANDROID_CONFIG_NAME_HERE' ],
        shlib_variant => '-gov',
    }
);
```

(you must change `INSERT_ANDROID_CONFIG_NAME_HERE` to the name of the config target you want to inherit from)

**Comment by misery** [comment]
Thanks, is it possible to pass SHLIB_VERSION_NUMBER= SHLIB_EXT=.so to the config file?

**Comment by levitte** [comment]
Yes.

``` perl
        shared_extension => '.so'
```

**Comment by misery** [comment]
Thanks!
