### ISSUE TITLE
Build instructions for portable openssl 

### ISSUE THREAD

**Issue by srossross** [openssl/openssl#7296]
I'm trying to build a portable binary of openssl to run in google functions. I can configure and make openssl with

```
./config no-shared
make
```

but when I try to run openssl on a different machine I get this error:

```
     Error: /root/repo/functions/bin/openssl-Linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /root/repo/functions/bin/openssl-Linux)
```

Is there a way to build a portable openssl without shared libs like libc?

Thanks

**Comment by dot-asm** [comment]
You obviously need to find system with oldest glibc version you want to support and compile on *that* one. Well, configuration procedure also recognizes -static flag, and produces statically-linked binaries, but it's not actually supported for general use, rather for specific testing purposes. Most notably such apps/openssl can't resolve non-number host names, e.g. github.com, it just crashes. At least as long as you use [contemporary] glibc. Last remark means that you can have better luck statically linking with rum-time other than glibc. For example musl appear to work better, i.e. statically linked apps/openssl can resolve host names without crashing. Either way, the first suggestion is the only one supported, so there is probably nothing else to add, closing.
