### ISSUE TITLE
Compile OpenSSL 1.1.1 with VS 2017 Statically or Dinamically include removed macros.

### ISSUE THREAD

**Issue by jvelilla** [openssl/openssl#7309]
Hi, I've compiled OpenSSL 1.1.1 on windows with VS2017 (shared and no-shared) and in both cases, the macros **OPENSSL_NO_STATIC_ENGINE** and **OPENSSL_NO_DYNAMIC_ENGINE** that were taken away from openssl/opensslconf.h are again generated.

The [OpenSSL changelog](https://www.openssl.org/news/changelog.txt ) does not mention they are back.

``` Changes between 1.1.0h and 1.1.0i [14 Aug 2018]
     The macros OPENSSL_NO_STATIC_ENGINE and OPENSSL_NO_DYNAMIC_ENGINE
     are also taken away from openssl/opensslconf.h, as they are irrelevant.   [Richard Levitte]
```

**Build method:**

1: perl Configure VC-WIN64A [no-shared|shared] --prefix=C:\Build-OpenSSL-VC-64-STATIC
2: nmake
3: nmake test
4: nmake install

So, Is it ok to remove them from the generated openssl/opensslconf.h?

**Comment by levitte** [comment]
They came back, and it seems I forgot to update CHANGES accordingly.  Sorry.

**Comment by jvelilla** [comment]
> They came back, and it seems I forgot to update CHANGES accordingly. Sorry.

Ok, question, so What's the recommended way to have a common `openssl/opensslconf.h` for STATIC and DYNAMIC ENGINE?
