### ISSUE TITLE
OpenSSL 1.1.1 all password bytes are ignored after first newline  

### ISSUE THREAD

**Issue by kujbol** [openssl/openssl#7310]
Hey, I was looking around openssl code, I was trying to port decrypting of openssl encrypted files. I've run into problem when password used for encoding these files had new lines in it. 

https://github.com/openssl/openssl/blob/7c69495712e3dc9aa8db38271f0c3faeb2037165/apps/apps.c#L439
Thanks to that openssl is ignoring all following password bytes after first `\n` occurrence. 

I'm not quite sure if it is a bug or a feature, but It would be good to at least mention about it there  https://www.openssl.org/docs/man1.1.0/apps/openssl.html#Pass-Phrase-Options

**Comment by levitte** [comment]
It is documented for `file:pathname`, but that should probably be moved to a paragraph of its own that refers back to the pass phrase options where this applies (all the different file ones).

**Comment by michael-o** [comment]
The docs should also mention that OpenSSL will not strip `\r` for the line and will feed it to the password reader, thus password files need to have Unix LS on any POSIX-like system.

**Comment by erbsland-dev** [comment]
@t8m Here my suggestion #24878 for an improved documentation that should resolve this issue.
