### ISSUE TITLE
Incorrect PSK binder generation with second ClientHello

### ISSUE THREAD

**Issue by vanc** [openssl/openssl#7312]
According to TLS 1.3 RFC 8446 [section 4.2.11.2.  PSK Binder](https://tools.ietf.org/html/rfc8446#section-4.2.11.2), with the second ClientHello after server responded with a HelloRetryRequest, the transcript hash would be computed the same way as [section 4.4.1](https://tools.ietf.org/html/rfc8446#section-4.4.1).

>  Note that in the first flight,
>  Truncate(ClientHello1) is hashed directly, but in the second flight,
>  ClientHello1 is hashed and then reinjected as a "message_hash"
>  message, as described in Section 4.4.1.

However, in tls_psk_do_binder() from ssl/statem/extensions.c, when the s->hello_retry_request is SSL_HRR_PENDING, the code simply grab all the cached handshake messages, including the current ClientHello, truncate the current ClientHello up to the binder, and do a simple EVP_DigestUpdate. It's not consistent with the RFC.

Did I miss something?

**Comment by kaduk** [comment]
The magic is hidden in ```ssl/statem/statem_lib.c:create_synthetic_message_hash()``` (and its callers)

**Comment by vanc** [comment]
> The magic is hidden in `ssl/statem/statem_lib.c:create_synthetic_message_hash()` (and its callers)

Well, this function does do the magic, but just not for PSK binders. It's only used for the client/server Finished messages.

**Comment by kaduk** [comment]
Note that ```ssl3_finish_mac()``` will either write a message to the handshake memory buffer or append to the digest if the digest is initialized.  ```create_synthentic_message_hash()``` calls ```ssl3_init_finished_mac()``` to get rid of the handshake digest, so the ```ssl3_finish_mac()`` call really is caching the "message_hash" handshake message into the memory buffer.  ```tls_psk_do_binder()``` is then going to retrieve the contents of the memory buffer, which ought to include the dummy "message_hash" handshake message, as I am reading things.

**Comment by vanc** [comment]
Right. Thanks for the pointers. Debugged into the code and yes, indeed, the cached message contains the synthetic ClientHello1 already.
