### ISSUE TITLE
Old 1.1.1 pre-release versions fail talking to RFC TLSv1.3

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#7315]
OpenSSL 1.1.1-pre6 and below fail during a handshake with an RFC TLSv1.3 implementation. These versions get confused and think they have seen the draft version that is acceptable to them (draft-26 in the case of 1.1.1-pre6).

This issue was fixed in 1.1.1-pre7.

All users of pre-release versions of 1.1.1 are advised to upgrade to the final released version.

**Comment by Lekensteyn** [comment]
I guess that the negotiation issue was fixed in commit 73cc84a132a08a02253ae168600fc4d16cd400d8, ssl/statem/statem_lib.c?

**Comment by mattcaswell** [comment]
Correct. See comment "Don't actually accept real TLSv1.3".
