### ISSUE TITLE
asn1parse inform pem is not RFC7468 compliant

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#7317]
running openssl-1.1.0h-3.fc27

```
openssl req -x509 -newkey rsa -pkeyopt rsa_keygen_bits:2048 -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl x509 -in /tmp/localhost.crt -out /tmp/localhost.pem -text
openssl asn1parse -in /tmp/localhost.pem -inform pem
```
outputs:
```
Error: offset too large
```

This is despite [RFC 7468](https://tools.ietf.org/html/rfc7468#section-2) requirement:
```
   Data before the encapsulation boundaries are
   permitted, and parsers MUST NOT malfunction when processing such
   data.
```

**Comment by mspncp** [comment]
@mattcaswell what was the reason why `-strictpem` was not made the default behaviour? Was it for compatibility reasons? Should we consider making it the default for the next major version?

**Comment by tomato42** [comment]
+1 on that question, while I understand the usability of decoding pem-header-less base64 encoded data, shouldn't the default be the standard PEM?

**Comment by mspncp** [comment]
Give me a day or two and I can prepare a pull request which makes `-strictpem` the default  (but keeping the option for compatibility reasons) and adds a new `-nopem` option to return to the old behaviour.

**Comment by mspncp** [comment]
Please have a look at #7320.

**Comment by mattcaswell** [comment]
> @mattcaswell what was the reason why -strictpem was not made the default behaviour? Was it for compatibility reasons?

I have absolutely no recollection of making that commit :-)
I have no problem with making this the default.

**Comment by mattcaswell** [comment]
Although....is making it the default a breaking change in any way?

**Comment by mspncp** [comment]
Well, I wouldn't backport it to 1.1.1., at least not with the new default. Only keep it on master which (almost surely) will be scheduled as a major release.

**Comment by mattcaswell** [comment]
>  Only keep it on master which (almost surely) will be scheduled as a major release.

Right - but we are likely to specify a policy around breaking changes. It won't be "open season".

**Comment by mspncp** [comment]
> we'll do major releases more frequently

Don't forget, we only have thirteen of them left ;-)
