### ISSUE TITLE
Apple Rejects Apps that link to 1.1.1

### ISSUE THREAD

**Issue by ecnepsnai** [openssl/openssl#7318]
Hello,

I'm attempting to update my iOS App with OpenSSL 1.1.1, however Apple is rejecting the binary because:

> **Non-public API usage:**
> The app references non-public symbols in Frameworks/CertificateKit.framework/CertificateKit: _getcontext, _makecontext, _setcontext

I don't have any symbols like that in my code base (that wraps around OpenSSL), however I can see references to all three of them in the libssl binary, oddly enough I can't see any references to them in the source, for example:

<img width="1105" alt="screen shot 2018-09-25 at 14 32 57" src="https://user-images.githubusercontent.com/1607109/46044546-ed7dad80-c0cf-11e8-8b7e-255edf0cb2c7.png">

Unfortunately this means that no iOS apps can be submitted to the app store if they use OpenSSL 1.1.1. OpenSSL 1.1.0i is not affected.

I'd be interested in helping resolve this issue quickly, please let me know if there's any more information I can provide.

**Comment by kaduk** [comment]
The short-term workaround would be to configure with ```no-async```

**Comment by ecnepsnai** [comment]
@kaduk Can confirm that disabling the async feature is a valid work-around at this time. This unblocks my app, but this issue should still be addressed, if possible.

**Comment by dot-asm** [comment]
Well, it doesn't have to be short-term. In sense that async support is highly unlikely to be used on iOS, so it might as well be permanently disabled. As far as I understand it's used by an external engine, and engines are not even available on iOS. This actually asks for question if it would be appropriate to add "async" to "engine" in disable_cascades. Like in #7401.

**Comment by levitte** [comment]
We have the ability to disable or enable features by default per config target, so would it be suitable to add this in the iOS config targets?

```
        disable  => [ 'async'],
```

**Comment by mattcaswell** [comment]
Looks good to me.

**Comment by levitte** [comment]
PR coming up

**Comment by ecnepsnai** [comment]
Oh, you beat me to it. I'll close my PR then.

**Comment by ensean** [comment]
Has any one try to communicate with Apple about this false alert ...?

**Comment by kroeckx** [comment]
Are you still seeing it with 1.1.1a?

**Comment by ensean** [comment]
@kroeckx I have tried compile the 1.1.1a source code on mac os without explicitly disable the **async** function as follows:
```
unzip the source code && cd to the source dir
./config
./make
```
Then, when performs ·nm· here goes the result
```
liyxMBP:openssl-1.1.1a liyx$ nm libcrypto.a | grep 'setcontext\|getcontext|\makecontext'
                 U _setcontext
liyxMBP:openssl-1.1.1a liyx$
```

_setcontext maybe also rejected again by Apple ...

**Comment by ecnepsnai** [comment]
@kroeckx I compiled 1.1.1a for ios-xcrun, ios64-xcrun, iossimulator-xcrun, iossimulator-xcrun and did not explicitly specify "--no-async" and submitted it to apple. It did not fail validation (where with 1.1.1 it did).

**Comment by ensean** [comment]
@ecnepsnai   I checked my build process again and update my comment, there is a mistake in my  previous *grep pattern*.  I am not quite familiar with c language compiling would you kindly show your build commands ?  Thanks a lot in advance.
> @kroeckx I compiled 1.1.1a for ios-xcrun, ios64-xcrun, iossimulator-xcrun, iossimulator-xcrun and did not explicitly specify "--no-async" and submitted it to apple. It did not fail validation (where with 1.1.1 it did).

**Comment by levitte** [comment]
The difference should be in configuration, no? This isn't my field, really, but I have so far assumed that ios config targets must be given explicitly, that running `. /config` is insufficient...

**Comment by ecnepsnai** [comment]
> @ecnepsnai I checked my build process again and update my comment, there is a mistake in my previous _grep pattern_. I am not quite familiar with c language compiling would you kindly show your build commands ? Thanks a lot in advance.
> 
> > @kroeckx I compiled 1.1.1a for ios-xcrun, ios64-xcrun, iossimulator-xcrun, iossimulator-xcrun and did not explicitly specify "--no-async" and submitted it to apple. It did not fail validation (where with 1.1.1 it did).

I used https://github.com/certificate-helper/openssl-ios

But I took out `--no-async` to test on https://github.com/certificate-helper/openssl-ios/blob/master/build-openssl.sh#L46

**Comment by ecnepsnai** [comment]
@levitte The issue is resolved as on 1.1.1a (for me at least). @kroeckx were you able to get it to work using my script?

**Comment by ensean** [comment]
@ecnepsnai I have tried your script, the `-no-async` option in your `build-openssl.sh` works as expected for both v1.1.1 and v1.1.1a, that is the *_*context* functions can not be found by `nm`
I will try to revise mine build commands.

**Comment by ecnepsnai** [comment]
I think we're good then - closing.
