### ISSUE TITLE
Engine's .rsa_sign and .rsa_verify methods are never invoked when using PSS padding mode

### ISSUE THREAD

**Issue by reiniert** [openssl/openssl#7341]
The following happens while implementing an engine with RSA support. Although `RSA_METHOD`'s `.flags` has `RSA_FLAG_SIGN_VER` set and both `.rsa_sign` and `.rsa_verify` have been assigned, the latter two never get invoked when using `RSA_PKCS1_PSS_PADDING` padding mode. Instead, `.rsa_priv_enc` and `.rsa_pub_dec` are invoked. See [this code snippet](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2n/crypto/rsa/rsa_pmeth.c#L267) for the signing side (and note that `RSA_sign` does get invoked when the padding mode is `RSA_PKCS1_PADDING`, as expected):

```
        } else if (rctx->pad_mode == RSA_PKCS1_PADDING) {
            unsigned int sltmp;
            ret = RSA_sign(EVP_MD_type(md), tbs, tbslen, sig, &sltmp, rsa);
            if (ret <= 0)
                return ret;
            ret = sltmp;
        } else if (rctx->pad_mode == RSA_PKCS1_PSS_PADDING) {
            if (!setup_tbuf(rctx, ctx))
                return -1;
            if (!RSA_padding_add_PKCS1_PSS_mgf1(rsa, rctx->tbuf, tbs,
                                                md, mgf1md, rctx->saltlen))
                return -1;
            ret = RSA_private_encrypt(RSA_size(rsa), rctx->tbuf,
                                      sig, rsa, RSA_NO_PADDING);
```

This is with `1.0.2n` but seems to be the same for other versions.

**Comment by selvanair** [comment]
This appears to be due to the fact that there is no way to pass the padding identifier to rsa_sign -- rsa_sign() implementation is supposed to assume the  padding is PKCS1. This also makes it seemingly impossible to implement signing using Windows Cryptography NG API.

An option would be to still call rsa_sign() nevertheless, and expect the implementation to check the padding required using EVP_PKEY_CTX_get_rsa_padding(), for example.

**Comment by petrovr** [comment]
mattcaswell wrote:
> RSA_sign() by definition uses PKCS1 padding. In the above code snippet the creation of the PSS padding is implemented within libcrypto and then the raw RSA private encrypt operation is used to create the final signature. So for an engine to support PSS it is sufficient to support the raw private encrypt operation.
Quote:
/* CryptoAPI RSA operations */

int capi_rsa_priv_enc(int flen, const unsigned char *from,
                       unsigned char *to, RSA *rsa, int padding)
{
     CAPIerr(CAPI_F_CAPI_RSA_PRIV_ENC, CAPI_R_FUNCTION_NOT_SUPPORTED);
     return -1;
}

So limitation is not only to CAPI but affects other engines.


> It is not possible (in the code as it stands today) to delegate the PSS padding operation itself to the engine.
>

**Comment by mattcaswell** [comment]
> So limitation is not only to CAPI but affects other engines.

I'm not really sure what your point is here.  CAPI does not implement this function. It isn't a limitation of the ENGINE API that prevents this. It's just a non-implemented feature. Why is this relevant to other engines?

**Comment by petrovr** [comment]
mattcaswell wrote:
>> So limitation is not only to CAPI but affects other engines.
> 
> I'm not really sure what your point is here.  CAPI does not implement this function. It isn't a limitation of the ENGINE API that prevents this. It's just a non-implemented feature. Why is this relevant to other engines?
> 

You statement is rejection of request.

In this engine is not implemented because external API does not provide 
respective functionality.
For instance one API is Microsoft Crypto, another sample is Mozilla NSS. 
With both  APIs could be implemented only sign/verify functionality.

Conclusion in some cases is not possible to implement private encryption.

So why OpenSSL RSA method has sing/verify functions? It is rhetorical 
question.


You suggestion makes no sense.


Regards,
Roumen Petrov

**Comment by selvanair** [comment]
CAPI is an old interface and cant anyway do PSS padding so this is irrelevant to CAPI.

However, ability to support external signing using Windows Cryptography Next Generation (CNG) API would be nice. I think the way to do that would be to hook on to evp_pkey_sign_init() and evp_pkey_sign() callbacks in EVP_PKEY_METHOD. I am not entirely sure the best way to use these but will raise that question in the users list.

**Comment by reiniert** [comment]
@mattcaswell wrote:

> RSA_sign() by definition uses PKCS1 padding. In the above code snippet the creation of the PSS padding is implemented within libcrypto and then the raw RSA private encrypt operation is used to create the final signature. So for an engine to support PSS it is sufficient to support the raw private encrypt operation. It is not possible (in the code as it stands today) to delegate the PSS padding operation itself to the engine.

In stead of "it is sufficient", the wording "it is required" seems more appropriate here.

I do not have much to add to the discussion except for my opinion. libcrypto is not the right place to implement padding, it belongs in or under RSA_sign() and that function needs a padding parameter, just like private_encrypt() has. Any other approach that will allow the engine to take care of the padding seems like a workaround and would have to be documented as such. The current implementation can not be defended and it stops people from doing what they  need to do to support PSS in their engines.

**Comment by mattcaswell** [comment]
Right - it is required. Note that we can't modify `RSA_sign()` itself for backwards compat reasons. It would have to be some other function with an additional padding parameter. PRs are always welcome :-)

**Comment by reiniert** [comment]
For information: this issue can be worked around via a customized `EVP_PKEY_METHOD` that forwards all functions to the original methods, except for the `sign` and `verify` functions. The latter need to have custom implementations that directly invoke signing or verifying functions if PSS padding is required, and otherwise forward to the `RSA_sign` and `RSA_verify` methods to be treated as usual.

See [this unit](https://github.com/rticommunity/openssl-cng-engine/blob/974393f87058f16baeb380e7be9091440c34a194/src/e_bcrypt_pkey.c#L411-L448) as an example, as well as [this PR]( https://github.com/OpenSC/pkcs11-helper/pull/31)
