### ISSUE TITLE
Cannot establish connection using external EC EVP_PKEY that can't sign SHA512

### ISSUE THREAD

**Issue by dwmw2** [openssl/openssl#7348]
https://github.com/tpm2-software/tpm2-tss-engine/issues/15

The TPM cannot do SHA512. OpenSSL asks it to. Am I missing a way to indicate that this EVP_PKEY isn't able to perform SHA512 signature?

**Comment by mattcaswell** [comment]
I posted a comment in that issue. You can control the signature algorithms supported using the "-sigalgs" option to s_server.

**Comment by dwmw2** [comment]
Straw man PR posted. Actually hooking up EVP_PKEY_supports_digest_nid() n the ENGINE in question is left as an exercise for the user...

**Comment by romen** [comment]
Let's keep it open until the 1.0.2 and 1.1.1 PRs are both merged!

**Comment by romen** [comment]
With #7609 and #7610 both merged, this has been now fixed also in 1.0.2 and 1.1.1.

**Comment by romen** [comment]
Thanks again @dwmw2 for reporting and fixing this!
