### ISSUE TITLE
Engine is loading twice

### ISSUE THREAD

**Issue by shadz3rg** [openssl/openssl#7358]
Ubuntu 18.04 fresh install
OpenSSL 1.1.0g (1.1.1 tested with the same results)
I had installed and configured GOST engine, openssl s_client and cURL 7.58 working completely fine.

Wget 1.19.4 outputs message "GOST engine already loaded" before every call.
```
root@home_server:/home/atari# wget https://curl.haxx.se/download/curl-7.61.1.tar.gz
--2018-10-06 12:30:56--  https://curl.haxx.se/download/curl-7.61.1.tar.gz
GOST engine already loaded
Resolving curl.haxx.se (curl.haxx.se)... 151.101.38.49, 2a04:4e42:9::561
Connecting to curl.haxx.se (curl.haxx.se)|151.101.38.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3986062 (3.8M) [application/x-gzip]
Saving to: ‘curl-7.61.1.tar.gz.2’

curl-7.61.1.tar.gz.2                     100%[================================================================================>]   3.80M  2.19MB/s    in 1.7s

2018-10-06 12:30:58 (2.19 MB/s) - ‘curl-7.61.1.tar.gz.2’ saved [3986062/3986062]
```

PHP 7.2.10 + OpenSSL = OK, as expected, GOST is available
```
root@home_server:/home/atari# php -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```

PHP 7.2.10 + OpenSSL + Libcurl = Not OK, got the same message, GOST is also available both in curl and openssl modules
```
root@home_server:/home/atari# php -v
GOST engine already loaded
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```

Is it expected behavior?
I was sure that problem was in Libcurl and PHP+Openssl, but it's strange why Wget load it more than once.

**Comment by petrovr** [comment]
Oleg Aleksandrovich wrote:
> Ubuntu 18.04 fresh install
> OpenSSL 1.1.0g (1.1.1 tested with the same results)
> I had installed and configured GOST engine, openssl s_client and cURL 7.58 working completely fine.
>
> Wget 1.19.4 outputs message "GOST engine already loaded" before every call.
> ```
[SNIP]
Wget performs (in brief for more recent openssl version) initialization:
(1)  OPENSSL_load_builtin_modules();
(2)  ENGINE_load_builtin_engines();
(3)  CONF_modules_load_file(NULL, NULL, 
CONF_MFLAGS_DEFAULT_SECTION|CONF_MFLAGS_IGNORE_MISSING_FILE);
(4)  OPENSSL_init_ssl(0, NULL);

I'm not convinced that initialization order is correct. OpenSSL before 
1.1 recommends (3) to be called last. In 1.1 (auto initialization) there 
is no such requirement.

Perhaps in 1.1 (3) CONF_modules_load_file does not sets  some flags and 
as result (4) load configuration again.

**Comment by xoyteam** [comment]
Use an openss call specifying an engine:
openssl -engine gost ciphers
and remove the information about manual loading of the gost engine library from the config.
