### ISSUE TITLE
How small can OpenSSL get?

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#7369]
A recurring question is how small can an OpenSSL build be?

Having measurements of library sizing for various compile options would allow for a rapid answer to this question.  This should include a standard build and a build with as many space saving options (-Os, as many no-XXX options as are reasonable, OPENSSL_SMALL_FOOTPRINT and anything that can be found).  Ideally both libcrypto and libssl would be sized.

As for architectures, x86-64 is an obvious first choice however ARM 32 might be better.  The configuration options should be listed so the results can be replicated for other platforms.

**Comment by richsalz** [comment]
I would rather we get rid of small-footprint, or test it.

**Comment by paulidale** [comment]
I tried to add it to the Travis loops in #3268 and the final result was for the option to be added to build bot instead.  The name is a misnomer, the resulting libcrypto isn't exactly small.

**Comment by richsalz** [comment]
Ah right.  But we don't do the fuzz and other tests, right?  Just like a dozen KAT's for whirlpool and similar KAT's for other algorithms.

**Comment by paulidale** [comment]
I don't know the extent and don't know how to get to build bot yet.

**Comment by nhorman** [comment]
@paulidale is this still something you're interested in pursuing?

**Comment by paulidale** [comment]
No.
