### ISSUE TITLE
TLS1_2: fatal decrypt_error

### ISSUE THREAD

**Issue by littlepenguin4321** [openssl/openssl#7370]
We have a mips32 based embedded device with openssl 1.0.2o .
The remote openssl tls1_2 connect to the webserver installed on this device is failing with "fatal decrypt_error" . 
Connection works with tls1_1. The local (on same device) connect also works in both cases i.e. tls1_2 and tls1_1.

Openssl Version - 1.0.2o and 1.0.2p
Target - mips32 (compiler gcc)

Tried openssl config with various config options (Compiler/OS - linux-generic32, linux-mips32,  Flags- no-asm, disabling optimization). But facing same error in all these cases.

`#openssl s_client -connect  <ipaddr>:443 -tls1_2 -msg`

```
----------------
>>> TLS 1.2 Alert [length 0002], fatal decrypt_error
    02 33
140463749879456:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:rsa_sign.c:291:
140463749879456:error:1408D07B:SSL routines:SSL3_GET
----------------
---
No client certificate CA names sent
SSL handshake has read 1305 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1539041589
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)

```

**Comment by dot-asm** [comment]
Things don't add up. You say it's 1.0.2o/p, but there is no error at rsa_sign.c:291 in either. But there is such error in 1.0.1. Or in other words it looks rather as it we are looking at 1.0.1. And it's not supported. So that unless more tangible evidence is presented that it's in fact 1.0.2, this will be considered as non-problem. For the record, I can't reproduce the problem with 1.0.2.

**Comment by littlepenguin4321** [comment]
> Things don't add up. You say it's 1.0.2o/p, but there is no error at rsa_sign.c:291 in either. But there is such error in 1.0.1. Or in other words it looks rather as it we are looking at 1.0.1. And it's not supported. So that unless more tangible evidence is presented that it's in fact 1.0.2, this will be considered as non-problem. For the record, I can't reproduce the problem with 1.0.2.

I have added some debug flags in openssl configure. Updated the client side openssl to 1.0.2p. 
Now client (x86_64, also on arm) and server (mips) are using same version of openssl.
Error location is "bad signature:rsa_sign.c:278".

**Openssl Configure**

`/Configure --shared --openssldir="/" --prefix="$(MIPS_TARGET_DIR)/build" linux-generic32 --cross-compile-prefix=mipsel-unknown-linux-gnu-  -O0 -DTLS_DEBUG -DKSSL_DEBUG -DCIPHER_DEBUG -DOPENSSL_SSL_DEBUG_BROKEN_PROTOCOL -DKSSL_DEBUG -DSSL_DEBUG  -DOPENSSL_RI_DEBUG -DPKT_DEBUG`


**Openssl Connect Command**
`openssl s_client -connect <ipaddr>:443 -tls1_2`

**Client Side Log (1.0.2p)**
```
CONNECTED(00000003)
verify return:1
3069359840:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:rsa_sign.c:278:
3069359840:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:s3_clnt.c:2038:
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1305 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1539897825
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
---

```

**Server Side Log (1.0.2p)**

```
tls1_enc(0)
dec 301
00 SCSV received by server
Server has 77 from 0x10029d18:
0x2ac18b20:ECDHE-RSA-AES256-GCM-SHA384
0x2ac18a60:ECDHE-ECDSA-AES256-GCM-SHA384
0x2ac189a0:ECDHE-RSA-AES256-SHA384
0x2ac188e0:ECDHE-ECDSA-AES256-SHA384
0x2ac185e0:ECDHE-RSA-AES256-SHA
0x2ac18400:ECDHE-ECDSA-AES256-SHA
0x2ac18880:SRP-DSS-AES-256-CBC-SHA
0x2ac18850:SRP-RSA-AES-256-CBC-SHA
0x2ac18820:SRP-AES-256-CBC-SHA
0x2ac18190:DH-DSS-AES256-GCM-SHA384
0x2ac18130:DHE-DSS-AES256-GCM-SHA384
0x2ac180d0:DH-RSA-AES256-GCM-SHA384
0x2ac18070:DHE-RSA-AES256-GCM-SHA384
0x2ac17b90:DHE-RSA-AES256-SHA256
0x2ac17b60:DHE-DSS-AES256-SHA256
0x2ac17b30:DH-RSA-AES256-SHA256
0x2ac17b00:DH-DSS-AES256-SHA256
0x2ac17830:DHE-RSA-AES256-SHA
0x2ac17800:DHE-DSS-AES256-SHA
0x2ac177d0:DH-RSA-AES256-SHA
0x2ac177a0:DH-DSS-AES256-SHA
0x2ac17da0:DHE-RSA-CAMELLIA256-SHA
0x2ac17d70:DHE-DSS-CAMELLIA256-SHA
0x2ac17d40:DH-RSA-CAMELLIA256-SHA
0x2ac17d10:DH-DSS-CAMELLIA256-SHA
0x2ac18b80:ECDH-RSA-AES256-GCM-SHA384
0x2ac18ac0:ECDH-ECDSA-AES256-GCM-SHA384
0x2ac18a00:ECDH-RSA-AES256-SHA384
0x2ac18940:ECDH-ECDSA-AES256-SHA384
0x2ac184f0:ECDH-RSA-AES256-SHA
0x2ac18310:ECDH-ECDSA-AES256-SHA
0x2ac18010:AES256-GCM-SHA384
0x2ac178f0:AES256-SHA256
0x2ac17770:AES256-SHA
0x2ac17ce0:CAMELLIA256-SHA
0x2ac17e90:PSK-AES256-CBC-SHA
0x2ac18af0:ECDHE-RSA-AES128-GCM-SHA256
0x2ac18a30:ECDHE-ECDSA-AES128-GCM-SHA256
0x2ac18970:ECDHE-RSA-AES128-SHA256
0x2ac188b0:ECDHE-ECDSA-AES128-SHA256
0x2ac185b0:ECDHE-RSA-AES128-SHA
0x2ac183d0:ECDHE-ECDSA-AES128-SHA
0x2ac187f0:SRP-DSS-AES-128-CBC-SHA
0x2ac187c0:SRP-RSA-AES-128-CBC-SHA
0x2ac18790:SRP-AES-128-CBC-SHA
0x2ac18160:DH-DSS-AES128-GCM-SHA256
0x2ac18100:DHE-DSS-AES128-GCM-SHA256
0x2ac180a0:DH-RSA-AES128-GCM-SHA256
0x2ac18040:DHE-RSA-AES128-GCM-SHA256
0x2ac17ad0:DHE-RSA-AES128-SHA256
0x2ac17980:DHE-DSS-AES128-SHA256
0x2ac17950:DH-RSA-AES128-SHA256
0x2ac17920:DH-DSS-AES128-SHA256
0x2ac17710:DHE-RSA-AES128-SHA
0x2ac176e0:DHE-DSS-AES128-SHA
0x2ac176b0:DH-RSA-AES128-SHA
0x2ac17680:DH-DSS-AES128-SHA
0x2ac17a70:DHE-RSA-CAMELLIA128-SHA
0x2ac17a40:DHE-DSS-CAMELLIA128-SHA
0x2ac17a10:DH-RSA-CAMELLIA128-SHA
0x2ac179e0:DH-DSS-CAMELLIA128-SHA
0x2ac18b50:ECDH-RSA-AES128-GCM-SHA256
0x2ac18a90:ECDH-ECDSA-AES128-GCM-SHA256
0x2ac189d0:ECDH-RSA-AES128-SHA256
0x2ac18910:ECDH-ECDSA-AES128-SHA256
0x2ac184c0:ECDH-RSA-AES128-SHA
0x2ac182e0:ECDH-ECDSA-AES128-SHA
0x2ac17fe0:AES128-GCM-SHA256
0x2ac178c0:AES128-SHA256
0x2ac17650:AES128-SHA
0x2ac179b0:CAMELLIA128-SHA
0x2ac17e60:PSK-AES128-CBC-SHA
0x2ac17f80:DHE-RSA-SEED-SHA
0x2ac17f50:DHE-DSS-SEED-SHA
0x2ac17f20:DH-RSA-SEED-SHA
0x2ac17ef0:DH-DSS-SEED-SHA
0x2ac17ec0:SEED-SHA
Client sent 84 from 0x1002b068:
0x2ac18b20:ECDHE-RSA-AES256-GCM-SHA384
0x2ac18a60:ECDHE-ECDSA-AES256-GCM-SHA384
0x2ac189a0:ECDHE-RSA-AES256-SHA384
0x2ac188e0:ECDHE-ECDSA-AES256-SHA384
0x2ac185e0:ECDHE-RSA-AES256-SHA
0x2ac18400:ECDHE-ECDSA-AES256-SHA
0x2ac18190:DH-DSS-AES256-GCM-SHA384
0x2ac18130:DHE-DSS-AES256-GCM-SHA384
0x2ac180d0:DH-RSA-AES256-GCM-SHA384
0x2ac18070:DHE-RSA-AES256-GCM-SHA384
0x2ac17b90:DHE-RSA-AES256-SHA256
0x2ac17b60:DHE-DSS-AES256-SHA256
0x2ac17b30:DH-RSA-AES256-SHA256
0x2ac17b00:DH-DSS-AES256-SHA256
0x2ac17830:DHE-RSA-AES256-SHA
0x2ac17800:DHE-DSS-AES256-SHA
0x2ac177d0:DH-RSA-AES256-SHA
0x2ac177a0:DH-DSS-AES256-SHA
0x2ac17da0:DHE-RSA-CAMELLIA256-SHA
0x2ac17d70:DHE-DSS-CAMELLIA256-SHA
0x2ac17d40:DH-RSA-CAMELLIA256-SHA
0x2ac17d10:DH-DSS-CAMELLIA256-SHA
0x2ac18b80:ECDH-RSA-AES256-GCM-SHA384
0x2ac18ac0:ECDH-ECDSA-AES256-GCM-SHA384
0x2ac18a00:ECDH-RSA-AES256-SHA384
0x2ac18940:ECDH-ECDSA-AES256-SHA384
0x2ac184f0:ECDH-RSA-AES256-SHA
0x2ac18310:ECDH-ECDSA-AES256-SHA
0x2ac18010:AES256-GCM-SHA384
0x2ac178f0:AES256-SHA256
0x2ac17770:AES256-SHA
0x2ac17ce0:CAMELLIA256-SHA
0x2ac18af0:ECDHE-RSA-AES128-GCM-SHA256
0x2ac18a30:ECDHE-ECDSA-AES128-GCM-SHA256
0x2ac18970:ECDHE-RSA-AES128-SHA256
0x2ac188b0:ECDHE-ECDSA-AES128-SHA256
0x2ac185b0:ECDHE-RSA-AES128-SHA
0x2ac183d0:ECDHE-ECDSA-AES128-SHA
0x2ac18160:DH-DSS-AES128-GCM-SHA256
0x2ac18100:DHE-DSS-AES128-GCM-SHA256
0x2ac180a0:DH-RSA-AES128-GCM-SHA256
0x2ac18040:DHE-RSA-AES128-GCM-SHA256
0x2ac17ad0:DHE-RSA-AES128-SHA256
0x2ac17980:DHE-DSS-AES128-SHA256
0x2ac17950:DH-RSA-AES128-SHA256
0x2ac17920:DH-DSS-AES128-SHA256
0x2ac17710:DHE-RSA-AES128-SHA
0x2ac176e0:DHE-DSS-AES128-SHA
0x2ac176b0:DH-RSA-AES128-SHA
0x2ac17680:DH-DSS-AES128-SHA
0x2ac17f80:DHE-RSA-SEED-SHA
0x2ac17f50:DHE-DSS-SEED-SHA
0x2ac17f20:DH-RSA-SEED-SHA
0x2ac17ef0:DH-DSS-SEED-SHA
0x2ac17a70:DHE-RSA-CAMELLIA128-SHA
0x2ac17a40:DHE-DSS-CAMELLIA128-SHA
0x2ac17a10:DH-RSA-CAMELLIA128-SHA
0x2ac179e0:DH-DSS-CAMELLIA128-SHA
0x2ac18b50:ECDH-RSA-AES128-GCM-SHA256
0x2ac18a90:ECDH-ECDSA-AES128-GCM-SHA256
0x2ac189d0:ECDH-RSA-AES128-SHA256
0x2ac18910:ECDH-ECDSA-AES128-SHA256
0x2ac184c0:ECDH-RSA-AES128-SHA
0x2ac182e0:ECDH-ECDSA-AES128-SHA
0x2ac17fe0:AES128-GCM-SHA256
0x2ac178c0:AES128-SHA256
0x2ac17650:AES128-SHA
0x2ac17ec0:SEED-SHA
0x2ac179b0:CAMELLIA128-SHA
0x2ac18550:ECDHE-RSA-RC4-SHA
0x2ac18370:ECDHE-ECDSA-RC4-SHA
0x2ac18460:ECDH-RSA-RC4-SHA
0x2ac18280:ECDH-ECDSA-RC4-SHA
0x2ac174a0:RC4-SHA
0x2ac17470:RC4-MD5
0x2ac18580:ECDHE-RSA-DES-CBC3-SHA
0x2ac183a0:ECDHE-ECDSA-DES-CBC3-SHA
0x2ac175c0:EDH-RSA-DES-CBC3-SHA
0x2ac17590:EDH-DSS-DES-CBC3-SHA
0x2ac17560:DH-RSA-DES-CBC3-SHA
0x2ac17530:DH-DSS-DES-CBC3-SHA
0x2ac18490:ECDH-RSA-DES-CBC3-SHA
0x2ac182b0:ECDH-ECDSA-DES-CBC3-SHA
0x2ac17500:DES-CBC3-SHA
rt=0 rte=0 dht=1 ecdht=1 re=1 ree=0 rs=0 ds=0 dhr=0 dhd=0
1:[00000080:00000001:00000189:00000085]0x2ac18b20:ECDHE-RSA-AES256-GCM-SHA384
Empty RI extension sent by server
tls1_enc(1)
rt=0 rte=0 dht=1 ecdht=1 re=1 ree=0 rs=0 ds=0 dhr=0 dhd=0
tls1_enc(1)
Using hash SHA512
tls1_enc(1)
tls1_enc(1)
tls1_enc(0)
726161696:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:s3_pkt.c:1498:SSL alert number 51
0A 00 1C 00 1A 00 17 00 19 00 1C 00 1B 00 18
00 1A 00 16 00 0E 00 0D 00 0B 00 0C 00 09 00 0A
00 23 00 00 00 0D 00 20 00 1E 06 01 06 02 06 03
05 01 05 02 05 03 04 01 04 02 04 03 03 01 03 02
03 03 02 01 02 02 02 03 00 0F 00 01 01 
dec 2
02 33 
```

**Comment by littlepenguin4321** [comment]
The crypto/sha/sha512.c does not have any preprocessor defines for mips/mips32. 

It has 3 versions of sha512_block_data_order

1. `defined (__i386) || defined(__i386__) || defined(_M_IX86) `
2. `defined(OPENSSL_SMALL_FOOTPRINT)`
3. for all other cases

The configuration selected by my build-system is generic-32 so it was selecting the 3rd sha512_block_data_order. 

I have tried enabling the version 1 by supplying additional flag. 
Now `openssl s_client -connect <ipaddr>:443 -tls1_2` test is not failing in my target.

I have also added SHA512_BLOCK_CAN_MANAGE_UNALIGNED_DATA, L_ENDIAN in configuration but sha512 is working even without this.

test/sha512t is also OK.
```
Testing SHA-512 ... passed.
Testing SHA-384 ... passed.
```

**Comment by dot-asm** [comment]
> It has 3 versions of sha512_block_data_order ... generic-32 so it was selecting the 3rd sha512_block_data_order.

And so would most of the platforms. 3rd variant is not "rare"/"obscure", rather contrary, others are. For the record adding -DOPENSSL_SMALL_FOOTPRINT to Configure command line enables second variant. However, it makes lesser sense to use it without -Os.

> ... version 1 ... is not failing in my target.

It's likely to be a compiler problem. i.e. bug in compiler. It's strange that -O0 didn't make difference, as optimizer is customarily one that causing problems. Again, I can't reproduce the problem. Both linux-generic32 and linux-mips32 pass SHA512 tests and s_server is interoperable.

**Comment by littlepenguin4321** [comment]
> It's likely to be a compiler problem. i.e. bug in compiler. It's strange that -O0 didn't make difference, as >optimizer is customarily one that causing problems. Again, I can't reproduce the problem. Both linux-generic32 and linux-mips32 pass SHA512 tests and s_server is interoperable.

Please suggest a test case to make sure that it is a compiler specific issue?
Is there anything in latest openssl (1.1.X) that can help me to investigate further?

**Comment by dot-asm** [comment]
> Please suggest a test case to make sure that it is a compiler specific issue?

*This* report is the test case. As already said, I can't reproduce the problem with my MIPS compiler. Nor is there evidence that non-MIPS platform would fail. If there was a problem with sha512.c, it would have been reported already, it's >10 years old code. In other words there is plenty of evidence that there is no problem with sha512.c implementation, and it's all against this one case. And compiler is apparently the only thing that is special about it. Of course problem might be that this is not evidence you've collected yourself, and you don't trust it...

> investigate further?

Simplest would be to compile sha512.c with another MIPS compiler. Unfortunately it might not work, because newer compiler might generate function calls that are specific to it. For example contemporary GNU compilers generate calls to __stack_chk_guard and __stack_chk_fail as part of stack protection sequence. It's possible to suppress them by using -fno-stack-protector, but there might be other things... But let's say it works and you effectively confirm that your compiler miscompiles sha512.c. But this calls for following question. If it miscompiles sha512.c, is there anything else it could have miscompiled? You might find that it miscompiles 3rd (most common) variant in sha512.c, but not 1st or 2nd. But would it actually give you peace of mind? Another path to pursue could be to find another 32-bit platform that would fail test/sha512t. But there is a catch. There are assembly implementations, and since goal of the exercise is to show that sha512.c is broken (as opposite to compiler), then one should be looking for platform that would fail no-asm build...
