### ISSUE TITLE
Could not load PKCS11 shared library files in windows 10

### ISSUE THREAD

**Issue by elliotmtx** [openssl/openssl#7373]
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

PKCS#11 engine I have built using https://github.com/OpenSC/libp11/blob/master/INSTALL.md using MSYS2 installation process by cloning git: https://github.com/OpenSC/libp11.git

I get the following error:

```
OpenSSL> engine dynamic -pre "SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre "MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll"

(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
21564:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\pkcs11.dll)
21564:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
21564:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
[Failure]: MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll
21564:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
21564:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:
```

Those paths exists and I still don't know what might be the issue.

And I don't know other way to build PKCS engines.

Can anyone please help.

**Comment by stevelinsell** [comment]
Hi @deekshith565 

If your msys2 setup has:
OpenSSL 1.0.2m 2 Nov 2017 (as mentioned in #727)
and your target has:
OpenSSL 1.1.0h 27 Mar 2018

then it could be that the engine is not loading rather than not being found as OpenSSL 1.0.2 is not binary compatible with OpenSSL 1.1.0 and your engine is getting built against OpenSSL 1.0.2.
I'm not familiar with msys2 and building for Windows targets so can't tell you exactly, but I would imagine you need to update the OpenSSL package in the msys2 environment to the matching OpenSSL 1.1.0 version and see if that helps.

I'm only guessing though, it could be something else entirely.....

**Comment by deekshith565** [comment]
I have executed using openssl.exe from MSYS2 setup where the version is 1.0.2m but still I face same error.

**Comment by deekshith565** [comment]
Can anyone please help?

**Comment by levitte** [comment]
This line:

```
21564:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\pkcs11.dll)
```

Is a direct result of this call returning NULL:

```
    h = LoadLibraryA(filename);
```

So this issue isn't so much about compatibility between libcrypto and pkcs11.dll as it is about the module `C:\msys64\usr\lib\engines\pkcs11.dll` not being loadable, period!  For what reason?  I do not know...  unfortunately, we're not displaying the Windows error message in that message (something we probably should change).

A simple program to try this out would be:

``` C
#include <stdio.h>
#include <windows.h>

int main()
{
    const char *filename = "C:\\msys64\\usr\\lib\\engines\\pkcs11.dll";
    HINSTANCE h = LoadLibraryA(filename);

    if (h == NULL) {
        unsigned int err = GetLastError();
        fprintf(stderr, "Failed loading %s: 0x%08x\n", filename, err);
    } else {
        fprintf(stderr, "Successfully loaded %s\n");
    }
}
```

You could also simply check with a Windows Explorer that this module actually exists in that location.

**Comment by levitte** [comment]
And oh, if you do compile and run that little program and get a failure code, here's the list of all of them (divided in chunks of 500 codes each): https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

**Comment by hajikhorasani** [comment]
@deekshith565 maybe the dll loaded but some other errors came up. Please use CryptokiMPX to generate some logs, and send them to me:
https://github.com/hajikhorasani/cryptokimpx

**Comment by levitte** [comment]
I looked again, and noticed this:

```
[Failure]: MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll
21564:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
21564:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:`
```

So it seems `MODULE_PATH` isn't understood by what has been loaded at that time.  Please try the following command:

```
OpenSSL> engine dynamic -pre "SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -post "MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll"
```

(note how the `MODULE_PATH` argument is a `-post` instead of a `-pre`)

**Comment by ixe013** [comment]
> And oh, if you do compile and run that little program and get a failure code, here's the list of all of them (divided in chunks of 500 codes each): https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

You can also get a localized description of the error code with `net helpmsg`. Try this (using your own error number, decimal):

```
net helpmsg 17
```

**Comment by t8m** [comment]
1.0.2 and 1.1.0 are unsupported versions. Please open a new issue if you see the same problem with 1.1.1 or 3.0 versions.
