### ISSUE TITLE
NULL Dereference - Missing check on s->s3->tmp.pkey

### ISSUE THREAD

**Issue by Bugcheckers** [openssl/openssl#7374]
s->s3->tmp.pkey is checked here:

https://github.com/openssl/openssl/blob/master/ssl/statem/statem_srvr.c#L3147

skey = s->s3->tmp.pkey;
    if (skey == NULL) { ...

But it is not checked here:

https://github.com/openssl/openssl/blob/master/ssl/statem/statem_srvr.c#L3202

EVP_PKEY *skey = s->s3->tmp.pkey;

No check on skey and if skey is NULL, skey is dereferenced (from->type) in EVP_PKEY_copy_parameters 

https://github.com/openssl/openssl/blob/master/crypto/evp/p_lib.c#L75

Thank you!

**Comment by Bugcheckers** [comment]
Hi @mattcaswell,

Would you please check this issue?

Thank you!

**Comment by mattcaswell** [comment]
Yes this looks inconsistent. There probably should be a check in both. Although this is a "should not happen scenario" so you could equally argue that we could get rid of the first check. Taking an attitude of an abundance of caution I'd go with adding a check in the second case. Feel free to submit a PR for this.

**Comment by Bugcheckers** [comment]
> Yes this looks inconsistent. There probably should be a check in both. Although this is a "should not happen scenario" so you could equally argue that we could get rid of the first check. Taking an attitude of an abundance of caution I'd go with adding a check in the second case. Feel free to submit a PR for this.

Thanks @mattcaswell !
Is there a concrete specification among OpenSSL community that no one should call any API with NULL parameters? Because based on the 3 reports we submitted so far, it seems it is a common inconsistency in OpenSSL that checking NULL take place inside some of the functions, while in other locations, checking NULL parameters appears before calling the API. I think this lack of consensus could be the reason for some of the bugs in software development. What do you think?

Thank you!

**Comment by mattcaswell** [comment]
> Is there a concrete specification among OpenSSL community that no one should call any API with NULL parameters? Because based on the 3 reports we submitted so far, it seems it is a common inconsistency in OpenSSL that checking NULL take place inside some of the functions, while in other locations, checking NULL parameters appears before calling the API. I think this lack of consensus could be the reason for some of the bugs in software development. What do you think?

I think that is a different issue to the one we are looking at here. This is about a purely internal value held in the SSL structure. We expect it to have been set by earlier logic if we get this far in the processing. However the logic is sufficiently complex that we are entertaining the possibility that there could have been a programming error, and therefore we explicitly check it to avoid a crash. Possibly this should really be an "ossl_assert" check.

This is a different issue to whether we check parameters for NULL when they are passed to some API function. That is a matter of debate within the community. Some people feel that we should always explicitly check, and some people feel that we should never explicitly check. There is as yet no agreed consensus on that. We should try to get to one - but like I said that doesn't really have a bearing on this specific issue.

**Comment by Bugcheckers** [comment]
Thank you @mattcaswell for clarification!
