### ISSUE TITLE
do_handhake on the client returns 0 before sending the Finished message?

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#7395]
I'm debugging m2crypto's test suite that now has a problem with OpenSSL 1.1.1 and TLS 1.3.

What I'm seeing is that it calls BIO_do_handshake() (I think) in the client, wait for that to return 1, and then just closes the connection. It did not send a Finished message back before closing the connection, so the server never sees the Finished message, and never says the handshake is complete.

It then keeps hanging in the server, because it doesn't check the return value of recv() indicating that the connection is closed, and just keeps on trying to read from it.

Is there some flush missing or something?

**Comment by mattcaswell** [comment]
Hmmm. Just from code inspection the flush seems to be there:

https://github.com/openssl/openssl/blob/628ee796389b555ddb5fc28355e16e9417ab1724/ssl/statem/statem_clnt.c#L841-L854

**Comment by kroeckx** [comment]
Never mind, I found what the problem was. It's using a memory bio, and on success it doesn't read from that memory bio to write it to the socket.
