### ISSUE TITLE
Missing include/openssl/applink.c [again] in 1.1.1

### ISSUE THREAD

**Issue by wrowe** [openssl/openssl#7396]
This bug seems to have resurfaced with no issue-based discussion on github that it was intentional.

Pull request #1314 seems to be newly rebroken with the 1.1.1 makefile/installer schema.

Legacy windows builds expect this to be in the `make install` resulting includes tree.

If this was deliberately deprecated, pointers are welcomed, but so long as openssl is built to anticipate the availability of OPENSSL_USE_APPLINK, it is irresponsible not to deliver it in said binary install target.

**Comment by mattcaswell** [comment]
I don't think this was intentional.

@levitte - any ideas?

**Comment by levitte** [comment]
Ah, we stopped looking at `@{$target{defines}}` and are looking at `${$config{defined}}` instead, which is wrong for default builds but completely right if the macro is passed on the configuration command line.  The solution is to look at both.  PR coming up!
