### ISSUE TITLE
lib*-lib-*.o + lib*-shlib-*.o make lesser sense

### ISSUE THREAD

**Issue by dot-asm** [openssl/openssl#7407]
I understand the formal sentiment behind idea to compile object files that go to shared and static libraries differently, but on practical level it's probably an overkill. For following reason. Contemporary systems are likely to employ [variation of] ASLR. Secondly, OpenSSL can get embedded into another shared object, most notably JNI. In both cases it's desired that object modules in static library are compiled with position-independent flag, i.e. as if they were compiled for usage in shared library. In other words it hardly makes sense to compile anything else but position-independent code. But in such case flags would be same for lib\*-lib-\*.o and lib\*-shlib-\*.o, and compiling pair would be just waste of resources and time. Of course majority hardly notices the waste, because majority is using fancy processors and difference in build time is tolerable for human observer. (I mean humans are slow.) But it's a waste nevertheless. And it gets really "painful" on less fancy systems, such as those in IoT segment. Either way, bottom line is that original single-object approach arguably was balanced enough. I mean by default build single position-independent object and put it into both static and dynamic libraries. And those who actually require non-position-independent code in static library can achieve the goal with dedicated config.

**Comment by dot-asm** [comment]
Just in case. I recall a remark elsewhere about -static link being problematic, i.e. linking application code with -static flag. If this was contributing factor to the lib-shlib split, then one should recognize that problem with -static link runs deeper than just compiler flags. glibc threads don't work at all, binary crashes at startup. Name resolution doesn't work, binary crashes in attempt to resolve name to address. It should be noted though that these are apparently glibc-specific problems, because for example application statically linked with musl doesn't exhibit such problems...

**Comment by dot-asm** [comment]
If there is something that is sensible to do differently when putting together static library it's ... engines. It makes sense to compile engines and engine support as if whole thing was configured with no-shared and put these object files into static library. So that application [consciously] linked with static library (or shared library that wraps OpenSSL) would be self-sufficient. Another option is to compile static engine support as if whole thing was configured with no-engine.

On related note. e_padlock is "bit rotten" in shared build. Since -DPADLOCK_ASM is not passed bind_engine does nothing.

**Comment by levitte** [comment]
@dot-asm, if you have a look at #7159, you'll see that the main driver behind this change isn't quite that, but rather about shared source between different products, and where the different products come with different build settings (inclusion directories, for example).  This may not be terribly important now, but we have a FIPS-related future where this may/will make more sense.

**Comment by levitte** [comment]
However, we may use the same mechanisms to resolve some things about simultaneous shared and static builds that we have ignored.  I haven't dived into that very much yet, thanks for the reminder.

**Comment by dot-asm** [comment]
The focus is rather on lib-shlib, i.e. *second* prefix, than on the *first* prefix, such as libcrypto. I appreciate the possibility of same input file being compiled for different contexts, it's just that *as it stands now* lib-shlib split makes lesser sense. And I'm inclined to assert that just-double-everything-with-lib-shlib won't ever make much sense. It should rather be more nuanced, with just a small subset of object files (at least engines and engines initialization) being compiled differently for static and shared libraries.

On potentially related note. After AIX arrangement, the lib{crypto|sll}_a.a thing, I wonder if it would be appropriate to extend this approach to all platforms (including Windows). I.e. to produce lib{crypto|sll}_a.a and tell users to -lcrypto_a (modulo something else for Windows), if they want to link statically. How is it potentially related? Because *first* prefix would be different, e.g. libcrypto vs. libcrypto_a;-)

**Comment by levitte** [comment]
It's true that we could complicate the configuration code to check if the lib and shlib configuration settings differ at all, and only apply the prefix if they do, per object file.  It's gonna require some brain twisting, but should be doable.

As for a rename of the static library, I've been thinking for quite a while that we should do that, because it will give better consistency across all supported platforms.  I would avoid `_a` and rather go with something like `-static` or `_static` (I actually think there's even a precedent for such a naming scheme...  could that even be on Linux?  My memory is a little vague on that subject)

**Comment by dot-asm** [comment]
Here is another related "bit rot". Original idea behind subdir targets was to facilitate "rapid prototyping". I mean you edit a file, but don't want to re-link whole thing just yet, so you run for example `make crypto/bn`. Now `make crypto/bn` will rebuild libcrypto-lib-\*, but not libcrypto-shlib-\*. Well, it doesn't really matter [now], because as already established shlib is just redux of lib. But things turn unexpected/weird on Windows. Provided that you configured shared build, nmake compiles only libcrypto-shlib-\*, no libcrypto-lib-\*. But if you run `nmake crypto\bn` it builds libcrypto-lib-\*...

**Comment by levitte** [comment]
That's interesting. I will have a look shortly

**Comment by dot-asm** [comment]
> That's interesting. I will have a look shortly ... #7452 

Now if I run `make crypto/bn` on Linux in no-shared config I get `make: *** No rule to make target 'crypto/bn/libcrypto-shlib-bn_add.o', needed by 'crypto/bn'.  Stop.` Well, there is certain ambiguity in the assertion, as I haven't actually tested shared config, or looked how things are on Windows now. But either way, I'm still inclined to assert that just-double-everything-with-lib-shlib won't ever make much sense. As already said, "it should rather be more nuanced, with just a small subset of object files (at least engines and engines initialization) being compiled differently for static and shared libraries."

**Comment by levitte** [comment]
I just discovered that you get a related issue if you `nmake crypto` with 1.1.0 and 1.1.1, because `crypto\dllmain.obj` is missing among the dependencies for `crypto\` when configured shared.  That's not *bad* in the same way as missing rules, but still...
