### ISSUE TITLE
Inconsistent check on EVP_PKEY_new

### ISSUE THREAD

**Issue by Bugcheckers** [openssl/openssl#7416]
@mattcaswell 

Referring to https://github.com/openssl/openssl/issues/7374#issuecomment-429918919, here is another example that somewhere check is done in function while in another locations an additional check is done at the parent level as well:

https://github.com/openssl/openssl/blob/master/apps/dsa.c#L224
pk = EVP_PKEY_new();
        if (pk == NULL)
           goto end;
EVP_PKEY_set1_DSA(pk, dsa);

https://github.com/openssl/openssl/blob/master/apps/rsa.c#L272
pk = EVP_PKEY_new();
EVP_PKEY_set1_RSA(pk, rsa);

pk is checked inside EVP_PKEY_assign which is called inside both EVP_PKEY_set1_DSA and EVP_PKEY_set1_RSA

Thank you!

**Comment by mattcaswell** [comment]
Neither of these are "wrong" exactly - just inconsistent. The explicit check in the "dsa" app looks more obvious to me (i.e. it is not obvious that there is a redundant check in EVP_PKEY_set1_DSA()), so I prefer that approach.

**Comment by romen** [comment]
I second Matt's opinion on preferring the approach used for DSA.

@Bugcheckers would you be so kind to open a PR to "fix" the code in `apps/rsa.c` to conform to the style used in `apps/dsa.c`?

**Comment by Bugcheckers** [comment]
Thank you guys @mattcaswell @romen for your comments!
I provided a pull request.

Thanks!
