### ISSUE TITLE
Malloc failure error with openssl

### ISSUE THREAD

**Issue by chirag7888** [openssl/openssl#7418]
I am using openssl to encrypt file and I am getting malloc error as shown below.

```
openssl version
OpenSSL 1.0.2j-fips  26 Sep 2016

openssl command
openssl cms -sign -in infile -signer file.crt.pem -inkey file.key.pem -CAfile CAfile -out outfile -keyopt rsa_padding_mode:pss -certfile by_hash/81908841

Errors
1435735688:error:2E0A40AF:CMS routines:CMS_add0_cert:certificate already present:cms_lib.c:462:
1435735688:error:2E094041:CMS routines:CMS_sign:malloc failure:cms_smime.c:461:
```

Please note that I am 100% sure that the parameters which I have provided is 100% correct, (i.e. infile, outfile, certfile, keyfile, cafile and hash_file)

Thanks in advance

**Comment by mspncp** [comment]
Hi @chirag7888,

IMO you are looking at the wrong error message: The true error is:  "certificate already present". (It is always better to look at the _first_ error message first ;-) )

https://github.com/openssl/openssl/blob/e216bf9d7ca761718f34e8b3094fcb32c7a143e4/crypto/cms/cms_lib.c#L462

The followup message is wrong and misleading, this needs to be fixed (pr coming soon...)

https://github.com/openssl/openssl/blob/e216bf9d7ca761718f34e8b3094fcb32c7a143e4/crypto/cms/cms_smime.c#L461



Note: your OpenSSL version is quite outdated, you should update to version 1.0.2p (2018-Aug-14). You can download it from https://www.openssl.org/source

**Comment by chirag7888** [comment]
Thanks for the quick response really appreciated,
Even i felt the same, but the question is when i change encryption algorithm to smime from cms then it works properly, So i didn't look at that angle.
If you are sure about this malloc error is due to the first error, Can you please tell me how to overcome that issue?

**Comment by mspncp** [comment]
> If you are sure about this malloc error is due to the first error, ...

I didn't debug it, but I would guess it's this misleading `goto` here: After failing to add the cert, it simply jumps to `merr`, where the malloc error message is printed.

https://github.com/openssl/openssl/blob/e216bf9d7ca761718f34e8b3094fcb32c7a143e4/crypto/cms/cms_smime.c#L447-L448

>  Can you please tell me how to overcome that issue?

Well, you need to find out, why the "certificate [is] already present"  ;-). Without having your environment, I can only guess...

**Comment by chirag7888** [comment]
Ok, I will check that,  Thanks for your valuable time

**Comment by mspncp** [comment]
@chirag7888 I just opened pull requests to fix the misleading malloc failure message (see #7445 (master) and #7446 (1.0.2)).

**Comment by mspncp** [comment]
I reopened this issue for reference. It will be closed automatically when the pull requests get merged.

**Comment by chirag7888** [comment]
@mspncp 
After debugging more in this issue, I have found that the problem is with "certfile" (last option of command -certfile)
That particular certfile has multiple entries of cert with same fingerprint, And that is causing this issue.

Reproducible steps:
1. Get all correct/proper files mentioned in the subject/body
2. Run the command mentioned in body (Which should be passed/should be signed properly)
3. Edit certfile (last option file), duplicate the certificate and put it in same file.
4. Run step #2, which should throw errors mentioned in body, (Note: With S/Mime this is working, but with CMS its throwing error)

**Comment by chirag7888** [comment]
@mspncp 
After debugging more in this issue, I have found that the problem is with "certfile" (last option of command -certfile)
That particular certfile has multiple entries of cert with same fingerprint, And that is causing this issue.

Reproducible steps:
1. Get all correct/proper files mentioned in the subject/body
2. Run the command mentioned in body (Which should be passed/should be signed properly)
3. Edit certfile (last option file), duplicate the certificate and put it in same file.
4. Run step #2, which should throw errors mentioned in body, (Note: With S/Mime this is working, but with CMS its throwing error)

**Comment by chirag7888** [comment]
> Ok, I will check that, Thanks for your valuable time

@mspncp 
After debugging more in this issue, I have found that the problem is with "certfile" (last option of command -certfile)
That particular certfile has multiple entries of cert with same fingerprint, And that is causing this issue.

Reproducible steps:
1. Get all correct/proper files mentioned in the subject/body
2. Run the command mentioned in body (Which should be passed/should be signed properly)
3. Edit certfile (last option file), duplicate the certificate and put it in same file.
4. Run step #2, which should throw errors mentioned in body, (Note: With S/Mime this is working, but with CMS its throwing error)

**Comment by mspncp** [comment]
_(Just deleted two duplicates of the same message)_

**Comment by mspncp** [comment]
> @chirag7888 I just opened pull requests to fix the misleading malloc failure message (see #7445 (master) and #7446 (1.0.2)).

#7445 and #7446 have been discontinued long time ago and are now closed. So I'm closing this issue again.
