### ISSUE TITLE
RAND_keep_random_devices_open not working

### ISSUE THREAD

**Issue by shawnw** [openssl/openssl#7419]
Using OpenSSL 1.1.1 in Arch linux, when checking lsof on a long-running application I noticed that `/dev/random/` and `/dev/urandom` were being opened by something. Some digging around found that a relatively recent OpenSSL change was to blame and that using `RAND_keep_random_devices_open(0);` would stop that behavior (This program execs itself to refresh its binary without dropping established connections, so leaving them open was causing a descriptor leak). The man page says it takes effect immediately and should be called during initialization, but I found that it working is very dependent on when in the program the function is called -- use it before any other OpenSSL routines that use random numbers, and the descriptors will be left open.

Consider this demonstration program:

```
#include <openssl/rand.h>
#include <openssl/bn.h>
#include <unistd.h>
#include <stdlib.h>
int main(void) {
  BIGNUM *bn;
  BN_CTX *ctx;
  RAND_keep_random_devices_open(0);
  ctx = BN_CTX_new();
  bn = BN_new();
  BN_set_word(bn, 1567);
  BN_is_prime_ex(bn, BN_prime_checks, ctx, NULL);
  sleep(10);
  return 0;
}

```

and the relevant strace output:

```
openat(AT_FDCWD, "/dev/urandom", O_RDONLY) = 3
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
openat(AT_FDCWD, "/dev/random", O_RDONLY) = 4
fstat(4, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 8), ...}) = 0
openat(AT_FDCWD, "/dev/srandom", O_RDONLY) = -1 ENOENT (No such file or directory)
futex(0x7f7ebc7db948, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f7ebc7db7f8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f7ebc7db7ec, FUTEX_WAKE_PRIVATE, 2147483647) = 0
getrandom("\x5b\xcd\xab\xc5\xa8\x3c\x89\x84\x8f\xcd\x97\x85\x90\x1a\x00\x22\xb3\x42\x4d\x53\x6b\xa6\xef\xa6\xad\x5e\xb2\x83\x2d\x99\x67\x8d", 32, 0) = 32
getpid()                                = 21486
clock_gettime(CLOCK_REALTIME, {tv_sec=1539757629, tv_nsec=856678890}) = 0
futex(0x7f7ebc7db918, FUTEX_WAKE_PRIVATE, 2147483647) = 0
nanosleep({tv_sec=10, tv_nsec=0}, 0x7ffea2d3c070) = 0
futex(0x7f7ebc7db6a4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
close(3)                                = 0
fstat(4, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 8), ...}) = 0
close(4)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

```

It only closes the descriptors (3 and 4) when the program exits normally. If it instead execs another program, they're left open and unused in it. If I move the `RAND_keep_random_devices_open()` call to just below the `sleep()`, they get closed right then, though. Instead of having to figure out by trial and error where to call the function, it'd be nice if it behaved as advertised. (I'm also not sure why it's opening the random device files at all when it uses the `getrandom()` syscall instead to seed things, or why it's opening both more than one...)

**Comment by paulidale** [comment]
I'll try to have a look at this one tomorrow.  Nothing immediately springs to mind as to why.

The reason it is opening the random devices is that OpenSSL was configured to include both these and `getrandom(2)` as sources.  The RAND subsystem isn't clever enough to know that the latter isn't going to fail once seeded.

From the trace, it doesn't look like it is opening any of these more than once.  /dev/urandom, /dev/random and /dev/srandom are tried but only the first two succeed.

**Comment by shawnw** [comment]
@paulidale  The real problem is that the files are being kept open despite that behavior being turned off.

**Comment by paulidale** [comment]
I've got a fix.  Having working code made it much easier thanks :)

**Comment by mspncp** [comment]
@mattcaswell I'm going the set the 1.1.a milestone on this issue and both pull requests. Just as a reminder that it at least needs to be triaged.

**Comment by paulidale** [comment]
Apologies for not following up on these.  I've been distracted.

**Comment by mattcaswell** [comment]
Ping @paulidale - what needs to happen with this?

**Comment by t8m** [comment]
If #7437 can fail only in case getrandom() works at the beginning but not later then I would say this is very improbable scenario which can be ignored. Do you have any concrete example how this could happen apart from artificial stuff like having the call blocked by seccomp.

**Comment by paulidale** [comment]
According to the man page I've got here, EINTR is a possible failure return from `getrandom`.  We also use `getentropy` if it's available, that can fail with EIO.  These can happen anytime.

So, yes it is possible.

**Comment by mspncp** [comment]
Note: we loop on EINTR since 630ce41e836.

**Comment by kroeckx** [comment]
And EIO is when you call it with a too great length, which we don't.

But we could also call it with an invalid pointer, or turn some unknown flag on.

**Comment by mspncp** [comment]
Correct. When you configure `--with-rand-seed=getrandom` then the preprocessor constant `OPENSSL_RAND_SEED_GETRANDOM` is defined and no other constants `OPENSSL_RAND_SEED_XXX`, so the following code is not compiled at all:

https://github.com/openssl/openssl/blob/ac765685d4b08a48cefffc71c434760045154dad/crypto/rand/rand_unix.c#L317-L326

Note: the default `--with-rand-seed=os` maps to whatever is best for the platform, on Linux it's equivalent to `--with-rand-seed=getrandom,devrandom`, see

https://github.com/openssl/openssl/blob/ac765685d4b08a48cefffc71c434760045154dad/crypto/rand/rand_unix.c#L189-L195
