### ISSUE TITLE
engine loading twice

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#7422]
Hello!
I'm using OpenSSL version 1.1.0i with external gost implementation. When I call "openssl ca" from command line with "-config" option  engine module is called twice and function ENGINE_add tries to add gost engine to engine list which causes conflicting engine error. If config option is not present everithing works fine.

**Comment by t8m** [comment]
We are sorry for neglecting your issue. Unfortunately 1.1.0 is out of support. If you're able to reproduce the problem with 1.1.1 or 3.0 versions, please open a new issue.
