### ISSUE TITLE
Add "Deprecated in"/"Removed in" flags in OpenSSL 1.0.2 to help with migration

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#7436]
It's difficult to migrate code right now because we don't know what functions will be gone when moving to 1.1.1 without first trying to compile against it. Can flags be added to 1.0.2 to mark all removed functions so we know what we need to rework before switching versions? Have an IFDEF that can be set that will disable all functions that will be removed in a future version.

**Comment by t8m** [comment]
This is obsolete request for 1.0.2/1.1.1 migration. We now properly signalize functions that will be removed in future via deprecations in 3.0.
