### ISSUE TITLE
Unable to compile libcrypt with shared flags

### ISSUE THREAD

**Issue by goelakash** [openssl/openssl#744]
I am trying to build Julia from source, and can't get openssl to compile libcrypt with shared flags.
I tried:

1. `./Config shared`

2. `CFLAGS=-fPIC ./Config` 

3. `CFLAGS=-fPIC ./Config shared`

and `make checkinstall` each time, but couldn't get past this error: 

>/usr/bin/ld: /usr/local/lib/libcrypto.a(poly1305-x86_64.o): relocation R_X86_64_PC32 against symbol `poly1305_blocks' can not be used when making a shared object; recompile with -fPIC
>/usr/bin/ld: final link failed: Bad value

**Comment by levitte** [comment]
Try this (fresh checkout of master please):

    ./config shared pic

**Comment by levitte** [comment]
(removed my previous comment, spoke too fast.  Hold on)

**Comment by levitte** [comment]
Can you tell from the build log that `./config shared` doesn't build with `-fPIC`?  It should happen without any more help....  what platform is this on?

**Comment by goelakash** [comment]
Ubuntu 14.04 (3.13.0-79)
I'll post the build logs.

**Comment by goelakash** [comment]
As you can see, the -fPIC flag is setup in CFLAGS. So libcrypt should also be compiling correctly.
```
Operating system: x86_64-whatever-linux2
Configuring for linux-x86_64
Configuring for linux-x86_64
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-krb5         [krb5-flavor not specified] OPENSSL_NO_KRB5
    no-libunbound   [experimental] OPENSSL_NO_LIBUNBOUND (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-rfc3779      [default]  OPENSSL_NO_RFC3779 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-zlib         [default] 
    no-zlib-dynamic [default] 
IsMK1MF=0
CC            =gcc
CFLAG         =-fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
EX_LIBS       =-ldl
CPUID_OBJ     =x86_64cpuid.o
BN_ASM        =x86_64-gcc.o x86_64-mont.o x86_64-mont5.o x86_64-gf2m.o rsaz_exp.o rsaz-x86_64.o rsaz-avx2.o
EC_ASM        =ecp_nistz256.o ecp_nistz256-x86_64.o
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes-x86_64.o vpaes-x86_64.o bsaes-x86_64.o aesni-x86_64.o aesni-sha1-x86_64.o aesni-sha256-x86_64.o aesni-mb-x86_64.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4-x86_64.o rc4-md5-x86_64.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =md5-x86_64.o
SHA1_OBJ_ASM  =sha1-x86_64.o sha256-x86_64.o sha512-x86_64.o sha1-mb-x86_64.o sha256-mb-x86_64.o
RMD160_OBJ_ASM=
CMLL_ENC      =cmll-x86_64.o cmll_misc.o
MODES_OBJ     =ghash-x86_64.o aesni-gcm-x86_64.o
ENGINES_OBJ   =
PROCESSOR     =
RANLIB        =/usr/bin/ranlib
ARFLAGS       =
PERL          =/usr/bin/perl
SIXTY_FOUR_BIT_LONG mode
DES_UNROLL used
DES_INT used
RC4_CHUNK is unsigned long
```

**Comment by levitte** [comment]
I'm testing with the same setup (3.13.0-76-generic) and get no error.  So for the moment, this is a *cannot-reproduce* issue.

Would you mind doing a `make clean all > make.log 2>&1` and post `make.log`?

**Comment by dot-asm** [comment]
Somewhere in the beginning of crypto/poly1305/asm/poly1305-x86_64.pl you can find
```
.globl  poly1305_init
.globl  poly1305_blocks
.globl  poly1305_emit
```
Adding following lines should help
```
.hidden poly1305_blocks
.hidden poly1305_emit
```
Test and report back.

**Comment by goelakash** [comment]
@levitte https://github.com/goelakash/openssl-make-log/blob/master/openssl-log/someoutput.log

**Comment by goelakash** [comment]
@dot-asm I'll keep you posted. Julia takes a lot of time to build (I did a `make clean all` just to sure this time).

**Comment by goelakash** [comment]
@dot-asm Thanks a lot! That did it.

**Comment by tmshort** [comment]
@dot-asm is this going to be fixed in master branch, or was there some other solution?

**Comment by dot-asm** [comment]
I don't know how OpenSSL is integrated to Julia, but it doesn't seem to it's linked with normally build libcrypto/ssl.so. But how come normal OpenSSL build doesn't suffer from this? There are two mechanisms: -Bsymbolic and crypto.map. Keyword is to wire references within shared library in manner with makes it impossible to override the symbols in question by loading another shared library. And in the process it resolves relocations correctly. I would recommend to adhere to this in all situations. But sure one can throw in .hidden into master...
