### ISSUE TITLE
OpenSSL support for z/OS

### ISSUE THREAD

**Issue by smuehlst** [openssl/openssl#7441]
We are using OpenSSL 1.1.0 with some modifications on z/OS. While using OpenSSL 1.1.0 as a static library works fine, it is currently not possible to use OpenSSL 1.1.0 in the context of a shared library. If the calling process decides to unload the shared library, there is a crash when the calling process exits, because the cleanup routines registered via atexit() are no longer available after the unloading of the shared library.

The reason is that for z/OS no platform-specific code exists that protects the shared library from unloading by deliberately leaking a reference to the shared library. See the relevant code in crypto/init.c:

https://github.com/openssl/openssl/blob/f2828a14fbe2ce56b5090f45b2a9a6e749d33b22/crypto/init.c#L143

This issue is related to the discussion in issue #7388, and @mattcaswell asked me create a separate issue for the z/OS problem.

**Comment by t-j-h** [comment]
Patches for z/OS would also be welcome. It has been on my list to complete that work.

**Comment by dlegaultbbry** [comment]
You could also link with -Wl,-znodelete and compile with -DOPENSSL_USE_NODELETE which is what we have done for this issue while we add support for atexit handlers for unloading libraries.

**Comment by smuehlst** [comment]
> Patches for z/OS would also be welcome. It has been on my list to complete that work.

@t-j-h: In what form would you want the patches, and against what baseline?

Our OpenSSL codebase has additional changes beyond z/OS+EBCDIC support, and we are using OpenSSL 1.1.0 currently. So it would require some additional effort to prepare a patch that only includes our EBCDIC-specific code. It is also possible and even likely that EBCDIC support is incomplete, as we are only using a small fraction of OpenSSL's functionality, and we are testing OpenSSL only in the context of our application.

Nevertheless we would be very interested if we can help to get official z/OS support into OpenSSL.

**Comment by t-j-h** [comment]
PRs against master is what are the most useful - and not all lumped into a single patch.

Separately if you want some views on the approach you have taken feel free to contact me directly and I can take a look at what you have done. I've been through multiple sets of approaches - but we haven't ever had a set of patches that get us to the point of the test suite fully working. Getting the library working isn't that hard - but ensuring all the test applications compile and operate is the challenge.

That is the "bar" to get decent support in place and what has slowed me down is being busy on other things and also that my z/OS environment is z/PDT so it is an emulation - and it is very slow to work with.

**Comment by levitte** [comment]
I'll disagree with Tim on one point: if it's hard for you to transport your changes to the master branch, I think it's better that we get clean patches against whatever OpenSSL base line you use (1.1.0), and we can use git to transport the changes to whatever branch we see fit.
Of course, we *do* appreciate it if you turn of with PRs against master, should that be easy enough for you.

**Comment by smuehlst** [comment]
As a first step I will try to run the test suite. In the past that was a hopeless effort, but maybe it is easier with OpenSSL 1.1.0.

**Comment by smuehlst** [comment]
@dlegaultbbry: Thank you for the suggestion, but I'm afraid that `-Wl,-znodelete` is not a valid option for the z/OS compiler/linker.

**Comment by smuehlst** [comment]
@t-j-h: With a small change in the top-level Makefile I was able to run the test suite, and it reported about 40 failed tests of 504 tests executed. I did not find any log files to examine what actually went wrong. How can I find out why a test actually failed?
I will contact you by email how to proceed with the patches.

**Comment by levitte** [comment]
Top level Makefile? With 1.1.0, there is only one Makefile (top-level indeed)

Anyway, the method to get verbosity out of the tests is this: `make test V=1`
You can also select exactly what tests to run like this: `make test V=1 TESTS='test_evp test_enc'` (I hope it's obvious what those names correspond to)

**Comment by smuehlst** [comment]
> Top level Makefile? With 1.1.0, there is only one Makefile (top-level indeed)

You're right. I was so used to the old build system that I hadn't realized up to now that this is the only Makefile left except for
```
./demos/bio/Makefile
./demos/evp/Makefile
```

**Comment by levitte** [comment]
> I was so used to the old build system ...

Yup, gotcha.  I was wondering, for a moment, if there was a more serious mixup there.  Glad it was just a slip.

**Comment by t8m** [comment]
I've transformed the issue into a generic OpenSSL support for z/OS one. Of course it would need a community to support this - providing patches and so on.

**Comment by mattcaswell** [comment]
Doesn't the work that @p-steuer did cover this? Or are there still things that don't work on z/OS?

**Comment by t8m** [comment]
@smuehlst Are there still any further issues to solve?

**Comment by smuehlst** [comment]
The original problem for which I opened this issue has been resolved (crashes with dynamic linking and atexit() handlers on z/OS).

We are currently using a version from the OpenSSL_1_1_1-stable branch which has some patches of us on top for fixing EBCDIC issues. We plan to switch to OpenSSL 3.0 in the future, but we haven't tried a 3.0 release candidate yet. 

This will go along with the switch to a new compiler on z/OS. There is now an clang-based compiler for z/OS available from IBM which we will use for all future development. This will maybe make some things easier, but maybe there also will be new issues. 

In the past I also gave up after a while when I tried to run the test suite, but this may have improved as well in the meantime.

@t8m: Are you interested in z/OS- and EBCDIC-related issues in the OpenSSL_1_1_1-stable branch, or is the focus on OpenSSL 3.0 now?

@mattcaswell: Regarding the work of @p-steuer I looked at his commits, and I have the impression that he worked on the port for Linux on z/Series machines, which does not involve any EBCDIC-specific code.

**Comment by t8m** [comment]
> @t8m: Are you interested in z/OS- and EBCDIC-related issues in the OpenSSL_1_1_1-stable branch, or is the focus on OpenSSL 3.0 now?

Given the z/OS and EBCDIC is not really working without significant patches on 1.1.1 I do not think we want such changes there. And 3.0 release is imminent so any eventual changes probably won't be merged there. But that does not mean they cannot be merged after the release. So please test OpenSSL 3.0.

**Comment by smuehlst** [comment]
> Given the z/OS and EBCDIC is not really working without significant patches on 1.1.1 I do not think we want such changes there. And 3.0 release is imminent so any eventual changes probably won't be merged there. But that does not mean they cannot be merged after the release. So please test OpenSSL 3.0.

Ok, we will test OpenSSL 3.0 then, but I can't yet estimate how soon that will happen.

I think this issue can be closed then, and I will open a new issue for OpenSSL 3.0 in the future.
