### ISSUE TITLE
Seeing ChangeCipherSpec in TLS 1.3 wireshark trace

### ISSUE THREAD

**Issue by kapiliitr** [openssl/openssl#7447]
I have attached wireshark traces for TLS 1.2 and 1.3. 

10.0.1.4 is the client and 157.55.193.21 is the server in these traces.

I didn’t expect the second round trip in TLS 1.3. Do you know what could be the reason for that ? Maybe I have misconfigured something or is that expected ?

![tls12](https://user-images.githubusercontent.com/1621360/47233226-e5d7be80-d386-11e8-8386-4a7c2d003977.png)
![tls13](https://user-images.githubusercontent.com/1621360/47233227-e5d7be80-d386-11e8-82d5-e59592237078.png)

**Comment by kaduk** [comment]
Did you read https://tools.ietf.org/html/rfc8446#appendix-D.4 ?

**Comment by kapiliitr** [comment]
I did, but I didn't understand how this is applicable in my scenario. I am using two VMs in Azure as a client and server.

I even tried with both client and server on localhost and that too had the same handshake trace. Maybe I have misunderstood something. Could you please explain what I am doing wrong and what I should do to get a true TLS 1.3 handshake.

Thanks

**Comment by kaduk** [comment]
```SSL_OP_ENABLE_MIDDLEBOX_COMPAT``` is set by default in 1.1.1, so per SSL_CTX_set_options(3) you should expect to see the compatibility messages sent unless disabled.
You are not doing anything wrong, and you are getting a TLS 1.3 handshake -- the Encrypted Extensions message is enough to prove that.  You could dive into the ServerHello further and see the contents of the "supported_versions" extension if you really wanted to, too.
If you do not want to see the ChangeCipherSpec, use SSL_CTX_clear_options() (or SSL_clear_options()) to unset the compat flag.
