### ISSUE TITLE
Add support to build libeay32.dll and ssleay32.dll for Windows ARM32 (1_0_2_stable branch)

### ISSUE THREAD

**Issue by jiria** [openssl/openssl#7448]
Currently, when building dlls for Windows, `-DOPENSSL_USE_APPLINK` is added to `$cflags`. This in turn enables the `ms/uplink.h` include through `cryptlib.h` (gleaned from `VC-32.pl`). It also builds and adds for linking `ms\applink.c` and `ms\uplink.c`. The problem with applink is that it requires architecture specific assembly code. `uplink-x86.pl` generates the assembly code for x86 using `x86asm.pl`. `uplink-x86)x64.pl` does this for x64 using `x86_6x-xlate.pl`. The corresponding ARM32 architecture specific assembly code is missing.

We have noticed that not all projects require the applink functionality to work properly. We propose to disable uplink for Windows ARM32 until the applink functionality is implemented for ARM32. The change is very small: https://github.com/jiria/openssl/commit/2d6d50595780b5765042511bc76072356d9c9369

What is your opinion about it?

**Comment by FdaSilvaYY** [comment]
1.0.2 is under maintenance, so no evolution,  just bugfix and security fix can be added .
See https://www.openssl.org/policies/releasestrat.html
Feel fee to submit a PR against master branch.

**Comment by t8m** [comment]
1.0.2 is unsupported. Closing.
