### ISSUE TITLE
Overquoted cc/gcc/cl arguments

### ISSUE THREAD

**Issue by FdaSilvaYY** [openssl/openssl#746]
When you look at Travis ou AppVeyor logs, You found this 
> i686-w64-mingw32-gcc -I../include -DDSO_WIN32 -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines\""  -D_MT -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -m32 -Wall -O3 -fomit-frame-pointer -DWHIRLPOOL_ASM -Wno-pedantic-ms-format    -c -o e_capi.o e_capi.c

Precisely, some path arguments are overquoted , for nothing :
-DOPENSSLDIR="\"/usr/local/ssl\"" 
-DENGINESDIR="\"/usr/local/lib/engines\""

This begins recently, probably after a makefile/perl buils system change.

**Comment by levitte** [comment]
In what way are they over-quoted?  They need to be strings in the C source, i.e. appear with quotes within the source.  Without them, building `crypto/cversion.c` will go *BAMF*

**Comment by levitte** [comment]
These two lines, more precisely:

https://github.com/openssl/openssl/blob/master/crypto/cversion.c#L100
https://github.com/openssl/openssl/blob/master/crypto/cversion.c#L107

**Comment by levitte** [comment]
(there are other places as well, I can point out all places if you want ;-))

**Comment by FdaSilvaYY** [comment]
I wasn't remember it, you're rigth, it's an engines specific.
