### ISSUE TITLE
OpenSSL sends Supported Groups x448 and x25519 although configured with no-tls1_3.

### ISSUE THREAD

**Issue by jtrillma** [openssl/openssl#7460]
We build OpenSSL 1.1.1 with the configure switch no-tls1_3. Looking at a Handshake, we see that it sends the Supported Groups x448 and x25519. Since they are not known to TLS 1.2 implementations we think that this is a bug.

**Comment by mattcaswell** [comment]
This is not correct. X448 and X25519 are well defined in TLSv1.2. See RFC 8422:

https://tools.ietf.org/html/rfc8422
