### ISSUE TITLE
openssl 1.1.1 install failed occasionally when parallel build

### ISSUE THREAD

**Issue by sandy-lcq** [openssl/openssl#7466]
1. Version openssl 1.1.1
2. run "make -j 48 install" on ubuntu 16.04 
3. error:
```
 link openssl/1.1.1-r0/image/usr/lib/libcrypto.so -> openssl/1.1.1-r0/image/usr/lib/libcrypto.so.1.1
+mv: cannot stat 'openssl/1.1.1-r0/image/usr/lib/libcrypto.so.1.1.new': No such file or directory
+make: *** [Makefile:441: install_runtime] Error 1

openssl/1.1.1-r0/image/usr/share/doc/openssl/html/man3/RAND_cleanup.html
mv: cannot stat 'openssl/1.1.1-r0/image/usr/lib/libcrypto.so.1.1.new': No such file or directory
+Makefile:318: recipe for target 'install_dev' failed
+make: *** [install_dev] Error 1
```

4. This maybe related to parallel build.  From the Makefile, both target "install_runtime" and "install_dev"
try to install libcrypto.so.  and have a part code very similar list below.  
    I think the problem should caused by install_dev and install_runtime  operate the libcrypro.so under libdir at the sametime,  can have the condition,  when try to mv  -f liblibcrypto.so.1.1.new to libcrypto.so.1.1, but liblibcrypto.so.1.1.new don't exist.

```
install_dev:
        @set -e; for l in $(INSTALL_LIBS); do \
                fn=`basename $$l`; \
                $(ECHO) "install $$l -> $(DESTDIR)$(libdir)/$$fn"; \
                cp $$l $(DESTDIR)$(libdir)/$$fn.new; \
                $(RANLIB) $(DESTDIR)$(libdir)/$$fn.new; \
                chmod 644 $(DESTDIR)$(libdir)/$$fn.new; \
                mv -f $(DESTDIR)$(libdir)/$$fn.new \
                      $(DESTDIR)$(libdir)/$$fn; \
        done

install_runtime:
        @set -e; for s in dummy $(INSTALL_SHLIBS); do \
                if [ "$$s" = "dummy" ]; then continue; fi; \
                fn=`basename $$s`; \
                : ; \
                $(ECHO) "install $$s -> $(DESTDIR)$(libdir)/$$fn"; \
                cp $$s $(DESTDIR)$(libdir)/$$fn.new; \
                chmod 755 $(DESTDIR)$(libdir)/$$fn.new; \
                mv -f $(DESTDIR)$(libdir)/$$fn.new \
                      $(DESTDIR)$(libdir)/$$fn; \
                : ; \
        done
```

**Comment by mspncp** [comment]
> run "make -j 48 install" on ubuntu 16.04

48?! Is this a typo or are you doing a stress test?

**Comment by sandy-lcq** [comment]
Hi,  Not a typo,   I  just use "-j 48" to build

**Comment by kaduk** [comment]
The build targets aren't so great, either, if you pass more than one top-level target, since we have lots of rules that do ```make depend && make _target``` and that will spin up competing make dependency engines.  Some older discussion at https://github.com/openssl/openssl/pull/6236#issuecomment-389152233

**Comment by levitte** [comment]
Yup.  That's the cost of providing for all sorts of `make` implementations, including those that have *no* inclusion capability at all, or don't have error-agnostic inclusion, or...

**Comment by kaduk** [comment]
I wonder if there's a good place to document the limitation.
Though, it occurs to me, we might be able to customize the makefile template to allow for use of more advanced make features where available.  It's less clear if that would be worth the effort involved, though.

**Comment by levitte** [comment]
Yeeeaaaaahhhhh, we were discussing that quiet a while back, and it died out when we realised that on a system with several `make` implementations, we have *no* idea which one the user will end up using, and since they compete on `Makefile`...

**Comment by levitte** [comment]
As for documentation, either somewhere in `NOTES.UNIX`, or create a brand new `NOTES.make` (I haven't tested [jom](https://wiki.qt.io/Jom) too much yet, but I assume we're getting into similar problems with that)

**Comment by sandy-lcq** [comment]
But parallel  build for installation target mostly working for us(except this occasionally install fail issue). 
Is there any possible that parallel build for installation target  have any potential problems I can't foresee?  You are expert of this, can you give any comments about parallel build for installation target in case we don't have this occasionally install fail issue?   Thanks.

**Comment by rpurdie** [comment]
The Yocto Project has been running parallel make install for openssl for a while, we use it by default for many different software projects. Only recently have we had a reported failure so it seems this has been working for many people in many thousands of builds at his point so it would seem it can't have been that badly broken. It seems sad to me to give up and go back to serial install, equally we have little choice if that is the official project view,

**Comment by mspncp** [comment]
My personal experience, not an official statement: `make -j 8 && sudo make -j 8 install` has worked well for me without ever failing.

**Comment by levitte** [comment]
Yup, but @sandy-lcq is entirely correct that there's a race condition, as both `install_dev` and `install_runtime` try to install the exact same shared libraries, so you may *occasionally* run into issues.

I had another look, and realised this was simpler to solve than I had realised.  PR coming up!

**Comment by kraj** [comment]
> My personal experience, not an official statement: `make -j 8 && sudo make -j 8 install` has worked well for me without ever failing.

I do make -j44 and that could make this race condition occur more often on big rigs

**Comment by levitte** [comment]
It took me longer than I first imagined to fix this in a good way...  it wasn't such a breeze after all...  I'm still at it, though

**Comment by levitte** [comment]
Please have a look at #7583 and see if that helps.  I haven't experimented enormously with it myself, so a few more eyes would be a good thing.

**Comment by levitte** [comment]
So...  anyone interested in looking at #7583?

**Comment by sandy-lcq** [comment]
I  just looked at the unix-makefile,  looks good except one place I  don't understand, 

install_engines : check_INSTALLTOP install_runtime_libs build_engines
previously,  install_engines don't need to install_runtime_lib, I don't know why we need add this depend.
does we just want depend on build_libs?

**Comment by levitte** [comment]
@sandy-lcq, most of our engines are linked with libcrypto, so it does make sense to install the shared libraries, if there are any, when installing engines, wouldn't you say?

**Comment by sandy-lcq** [comment]
Then,  I don't have other comments.
