### ISSUE TITLE
libcurl with ssl in linux (curle_not_built_in error)

### ISSUE THREAD

**Issue by SiddalingaSwamy12** [openssl/openssl#7468]
curl_easy_setopt(Config->hHandle->curl, CURLOPT_SSL_CTX_FUNCTION, NULL))

is returning CURLE_NOT_BUILT_IN error in linux, where in Windows(Visual Studio) its working fine.

I built libcurl in linux with following commands: sudo apt-get install libssl-dev sudo apt-get install openssl libssl-dev sudo apt-get install libcurl4-gnutls-dev

but still getting same error even after building curl and libcurl with ssl

**Comment by mattcaswell** [comment]
This question should be directed to a curl forum.

**Comment by agnosticdev** [comment]
Yes, as stated above, the curl project should be able to help you with this issue: https://github.com/curl/curl
If you search around in curl for `curl_easy_setopt` and `CURLE_NOT_BUILT_IN` this may also lead you to the root of your issue.
