### ISSUE TITLE
OpenSSL 1.1.1 does not allow sending of no SupportedGroups

### ISSUE THREAD

**Issue by RoffelKartoffel** [openssl/openssl#7471]
Trying to disable the SupportedGroups for TLS 1.2 by SSL_CTX_ctrl(ctx, SSL_CTRL_SET_CURVES, 0, 0)  fails with „error:14275041:SSL routines:tls1_set_groups:malloc failure“.

We build it with the no-tls1_3 configure switch.

We are only using RSA_PSK suites which do not require finite fields or elliptic curves. OpenSSL 1.0.2o did not send any.

**Comment by misery** [comment]
This line seems to be the root of all evil. ;-)
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/ssl/statem/extensions_clnt.c#L135

Used ciphers:
```
"RSA-PSK-AES256-GCM-SHA384"
"RSA-PSK-AES256-CBC-SHA384"
"RSA-PSK-AES128-GCM-SHA256"
"RSA-PSK-AES128-CBC-SHA256"
"RSA-PSK-AES256-CBC-SHA"
```

c->min_tls is always TLS1_3_VERSION true because it checks SSL_CIPHER ```"TLS_AES_256_GCM_SHA384"```. But why?

**Comment by jtrillma** [comment]
By overriding the default 1.3 ciphersuites with an empty list in SSL_CTX_set_ciphersuites we found a workaround, the EC extensions (no_supported_groups, ec_point_formats) are not included anymore in the Client Hello. 

It seems that somewhere an ifdef is missing, but I could not pinpoint the location. When using no-tls1_3 the TLS 1.3 ciphers should not have an influence on min_tls.

**Comment by tomato42** [comment]
@RoffelKartoffel a bit of a side question, but why you don't want to send that extension? In general, including it should be harmless...

**Comment by RoffelKartoffel** [comment]
Here is some background to your side question so that you can understand how we stumbled upon this issue:

We are developing software which is required to follow strict security specifications. Each release is evaluated for conformity to these specifications by evaluators assigned by our customer. Since the extension is not required, evaluators think that it must not be send.

Furthermore we fear that existing third-party server software might not expect this new behavior.

**Comment by mattcaswell** [comment]
Fix in #7479.

**Comment by jtrillma** [comment]
Thank you for your time on this issue, the pull request fixes it.

**Comment by kaduk** [comment]
> Furthermore we fear that existing third-party server software might not expect this new behavior.

Just to be absolutely clear: any TLS server software that cannot handle receiving a new (unknown to it) extension is broken and need to be fixed.  I can understand that you might need a way to workaround such issues, and a conservative stance is to limit what your clients send, but that does not change the fact that the server is broken.

**Comment by tomato42** [comment]
not to mention that a server that _still_ has problem with unrecognised extensions (and includes `supported_groups` in that list) will be completely incompatible with clients that advertise TLS 1.3 support

so while I understand the conservative behaviour, I'd say that breaking such stuff is the only way forward (so that bug gets noticed)
