### ISSUE TITLE
Adopt https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#7472]
I encourage the OpenSSL project to adopt the widespread https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

**Comment by richsalz** [comment]
also for your consideration: http://lists.gnu.org/archive/html/info-gnu/2018-10/msg00001.html

**Comment by levitte** [comment]
Oh, I *do* like RMS' take on it!

**Comment by t8m** [comment]
+1 to the way RMS did it for GNU project.

**Comment by richsalz** [comment]
Closing this. If the project wants to change it will have to do so because of internal feelings, not opinions from outsdiers.
