### ISSUE TITLE
rand_pool_acquire_entropy may fail if the buffer pointer address being passed to read syscall is a large virtual address.

### ISSUE THREAD

**Issue by mohitsahni** [openssl/openssl#7477]
The rand_init may fail if the pool->buffer pointer has an address which generates EFAULT during syscall. 
In my case I am allocating buffer from a shared memory space which has a large virtual address and the read system call for reading /dev/urandom etc files fails with EFAULT error.  

> 504             while (bytes_needed != 0 && attempts-- > 0) {
> 505                 buffer = rand_pool_add_begin(pool, bytes_needed); 
> 506                 bytes = read(fd, buffer, bytes_needed);

**Comment by t8m** [comment]
I do not think this is a bug. I'd say - do not do that then.
