### ISSUE TITLE
SSL_connect returns -1, SSL_get_error() gives SSL_ERROR_SSL while ERR_error_string() gives error:00000000:lib(0):func(0):reason(0)

### ISSUE THREAD

**Issue by VijayalakshmiSundaravaradhan** [openssl/openssl#7488]
I have a client application that accesses a wcf service using gSOAP with OpenSSL. The application runs on my PC that has openssl version 1.0.2g.

```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```
But when I run the same application on my arm system which has openssl version 1.0.2 h, SSL_connect throws this error which I could not even decipher. Please let me know the possible causes of this error. Is it because of the openssl version or something else?

**Comment by mattcaswell** [comment]
Please give us a bit more information:
What is the return value from SSL_connect()?
What is the return value from SSL_get_error()?
How did you obtain the error code to pass to ERR_error_string()?

**Comment by VijayalakshmiSundaravaradhan** [comment]
SSL_connect() returned -1 and SSL_get_error returned 1, i.e SSL_ERROR_SSL

Here is how I used ERR_error_string()

`char msg[1024];
ERR_error_string_n(ERR_get_error(), msg, sizeof(msg));
printf("%s %s %s %s\n", msg, ERR_lib_error_string(0), ERR_func_error_string(0), ERR_reason_error_string(0));
`

The error was resolved(not exactly) by calling  _soap_ssl_client_context(m_proxy.soap, SOAP_SSL_NO_AUTHENTICATION, NULL, NULL, NULL, NULL, NULL);_

But it is a temporary solution and I don't understand why this works. And how I am able to run the application successfully on my PC without the temporary fix? What I am missing?

**Comment by mattcaswell** [comment]
Hmmm...something doesn't quite add up. There is only one place in the implementation of SSL_get_error() that returns SSL_ERROR_SSL. It's here:

https://github.com/openssl/openssl/blob/896e8c5713b50ff2ef1478d5c6709874ce57cf05/ssl/ssl_lib.c#L2707-L2725

So, as you can see, the only way that function can return 1 (SSL_ERROR_SSL) is if ERR_peek_error() returns a value != 0. However the error string you are getting back is what happens when you pass 0 as the error value to `ERR_error_string_n()`. So `ERR_peek_error()` is returning non-zero, but `ERR_get_error()` returns zero?? This doesn't sound likely so something else must be happening. Perhaps the error queue is getting emptied somehow between the point that `SSL_get_error()` returns SSL_ERROR_SSL, and the point where you call `ERR_get_error()`? Do you make any other libssl/libcrypto calls between those two points?

**Comment by VijayalakshmiSundaravaradhan** [comment]
Here is the following code in my application to retrieve the error info.
```
int r = SSL_connect(soap->ssl);
if ((r) <= 0)
{
int err = SSL_get_error(soap->ssl, r);
if(err == SSL_ERROR_SSL){              
              ERR_load_crypto_strings();
              SSL_load_error_strings(); // just once
              char msg[1024];
              ERR_error_string_n(ERR_get_error(), msg, sizeof(msg));
              printf("%s %s %s %s\n", msg, ERR_lib_error_string(0), ERR_func_error_string(0), ERR_reason_error_string(0));
}
}
```

**Comment by mattcaswell** [comment]
You're supposed to call this bit once up front (i.e. before calling other OpenSSL functions):
````
              ERR_load_crypto_strings();
              SSL_load_error_strings(); // just once
````
i.e. call it when you first initialise the library, and before SSL_connect(). I can't see why that would cause the error queue to be emptied but lets at least eliminate that issue.

One other slightly odd thing is your call of `ERR_lib_error_string(0)`, `ERR_func_error_string(0)` and `ERR_reason_error_string(0)`. That doesn't really make any sense. You would normally call `ERR_get_error()` once, and then use the return value to pass to all of those functions.

**Comment by VijayalakshmiSundaravaradhan** [comment]
Thanks for the help. Now I could get a proper error code. 

error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

**Comment by VijayalakshmiSundaravaradhan** [comment]
I also found something else. The flags set to SSL_CTX_set_options() call differs in PC and my arm system and it is because of the long data type. My PC is 64-bit and my arm system is 32-bit and hence the long is 8 bytes in PC while 4 bytes in the arm system.

**Comment by mattcaswell** [comment]
WRT to the certificate verify failed you might want to look at the return value from `SSL_get_verify_result()` to see what went wrong:
https://www.openssl.org/docs/man1.0.2/ssl/SSL_get_verify_result.html

The meaning of the return values from that function are further described here:
https://www.openssl.org/docs/man1.0.2/apps/verify.html

**Comment by VijayalakshmiSundaravaradhan** [comment]
Okay!
I got the error code 30 X509_V_ERR_AKID_SKID_MISMATCH

**Comment by mattcaswell** [comment]
Hmm. That is...surprising. AFAIK you shouldn't normally get that error return value. Perhaps @vdukhovni might be able to offer some insight here.

**Comment by vdukhovni** [comment]
A quick look suggests that this error can only happen via a call to X509_check_akid() from X509_check_issued(), which is only called from check_issued() in crypto/x509/x509_vfy.c.
That last function can in turn only set the error in question if the verification parameter flags
include the non-default "X509_V_FLAG_CB_ISSUER_CHECK".

```
static int check_issued(X509_STORE_CTX *ctx, X509 *x, X509 *issuer)
{
    int ret;
    ret = X509_check_issued(issuer, x);
    if (ret == X509_V_OK)
        return 1;
    /* If we haven't asked for issuer errors don't set ctx */
    if (!(ctx->param->flags & X509_V_FLAG_CB_ISSUER_CHECK))
        return 0;

    ctx->error = ret;
    ctx->current_cert = x;
    ctx->current_issuer = issuer;
    return ctx->verify_cb(0, ctx);
}
```

The documentation says:
```
The B<X509_V_FLAG_CB_ISSUER_CHECK> flag enables debugging of certificate
issuer checks. It is B<not> needed unless you are logging certificate
verification. If this flag is set then additional status codes will be sent
to the verification callback and it B<must> be prepared to handle such cases
without assuming they are hard errors.
```

With that flag set (does the application in question do anything to set this flag?),
it may be possible for that error to percolate up into the verification context.
With the flag set, false positive errors are quite likely.  Without it, I don't presently
see how the reported issue can arise.  DO NOT set this flag.
