### ISSUE TITLE
How to use the sm2_do_sign function.

### ISSUE THREAD

**Issue by zxuewu** [openssl/openssl#7489]
I added the sm2_do_sign function in my test code,when I compiled the code with gcc, I got something as followd:
# gcc -g -o sm2_sign_test sm2_sign_test.c -L/usr/local/lib64 -lssl -lcrypto
/tmp/ccUWXXJc.o: In function `main':
/usr/local/src/test_doc/sm2_test.c:108: undefined reference to `sm2_do_sign'
collect2: error: ld returned 1 exit status

**Comment by InfoHunter** [comment]
That is an internal function and you should not use that directly for standalone applications.

Use the EVP interface for SM2 instead. Here is a reference: https://github.com/openssl/openssl/blob/f81b043ad856d8b9af5239a4978f8bd4b965dab9/doc/man7/SM2.pod

**Comment by zxuewu** [comment]
I have done with this, thanks a lot!
