### ISSUE TITLE
/dev/fd/63.srl: No such file or directory

### ISSUE THREAD

**Issue by chenlein** [openssl/openssl#7490]
When I execute the following command:
```
[root@master-0 dashboard]# openssl x509 -req -sha256 -days 3650 -in pki/cert/dashboard.csr -out pki/cert/dashboard.crt -CA <(cat pki/CA/rootCA.crt) -CAkey <(cat pki/CA/rootCA.key) -CAcreateserial -extfile <(cat pki/dashboard-openssl-exts.conf)
```
and I got the following stdout:
```
Signature ok
subject=/C=CN/ST=HB/L=WH/O=DM/OU=YPT/CN=192.168.10.10
Getting CA Private Key
/dev/fd/63.srl: No such file or directory
140195256260496:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:p_lib.c:137:
140195256260496:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/dev/fd/63.srl','r')
140195256260496:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
140195256260496:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/dev/fd/63.srl','w')
140195256260496:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
```
and then I execute the following command:
```
[root@master-0 dashboard]# openssl x509 -req -sha256 -days 3650 -in pki/cert/dashboard.csr -out pki/cert/dashboard.crt -CA pki/CA/rootCA.crt -CAkey <(cat pki/CA/rootCA.key) -CAcreateserial -extfile <(cat pki/dashboard-openssl-exts.conf)
Signature ok
subject=/C=CN/ST=HB/L=WH/O=DM/OU=YPT/CN=192.168.10.10
Getting CA Private Key
```
it work good

I try to echo the command:
```
[root@master-0 dashboard]# echo openssl x509 -req -sha256 -days 3650 -in pki/cert/dashboard.csr -out pki/cert/dashboard.crt -CA <(cat pki/CA/rootCA.crt) -CAkey <(cat pki/CA/rootCA.key) -CAcreateserial -extfile <(cat pki/dashboard-openssl-exts.conf)
openssl x509 -req -sha256 -days 3650 -in pki/cert/dashboard.csr -out pki/cert/dashboard.crt -CA /dev/fd/63 -CAkey /dev/fd/62 -CAcreateserial -extfile /dev/fd/61
```
The output is `/dev/fd/63`, not `/dev/fd/63.srl`

openssl version: OpenSSL 1.0.2k-fips  26 Jan 2017
linux-release: CentOS Linux release 7.5.1804 (Core)

**Comment by richsalz** [comment]
Output is only supported for regular files, not devices.  The app often makes a temp file first, and then renames it to the true target.

**Comment by chenlein** [comment]
@richsalz Thanks for your answer. 
I know that `-out` parameter is only supported for regular files, not devices. However the `-CAcreateserial` and the `-CAkey` supported _Process Substitution_ , why is `-CA` not supported?

**Comment by chenlein** [comment]
@richsalz OK, I got it. Thank you for your help.

**Comment by Bharathkumarraju** [comment]
I have used  -CAcreateserial while creating crt ...it also created a ca.srl in current directory.. i hope it works as well.. any help much appreciated.
```bharathdasaraju@MacBook-Pro TLSCERTS $ openssl x509 -req -in admin.csr -CAcreateserial -CA ca.crt -CAkey ca.key -out admin.crt
Signature ok
subject=/CN=kube-admin
Getting CA Private Key
bharathdasaraju@MacBook-Pro TLSCERTS $```

**Comment by deluca-mike** [comment]
@Bharathkumarraju Consider: http://certificate.fyicenter.com/1972_OpenSSL_x509-req_-Error_my_ca.srl%3A_No_error_.html

Consider the `-CAcreateserial` flag/option.


> When using "x509" command to sign CSR, you have to use the following options to help OpenSSL to manage how serial number should be provided to the new certificates.

> Use "-set_serial nnnn" command option to provide the serial number manually.
> Use "-CAcreateserial" command option to let OpenSSL to create the serial number for you.
> Use "-CAserial filename" command option to ask OpenSSL to read the serial number from the given file. OpenSSL will also increment the serial number in the file for you.
> Create a default serial number file with the same file name as the CA certificate with ".srl" file extension. OpenSSL will read and increment the serial number from the this default file.
