### ISSUE TITLE
How do you use SM2 asymmetric encryption in SSL

### ISSUE THREAD

**Issue by Mingzhe-Zhu** [openssl/openssl#7491]
First, I consulted a China website, https://blog.csdn.net/dong_beijing/article/details/81417214.
Generate the key:
./openssl ecparam -genkey -name SM2 -out priv.key
Generate a certificate:
./openssl req -new -x509 -sha256 -key priv.key -out cer.crt -days 10000 -subj '/C=CN/ST=Beijing/L=Haidian/O=Datang/OU=SDT/CN=Shixun/emailAddress=dongzy08@163.com'
Second, I use ssl to establish client-server connection.
Thrid, I got a error: error 14094410 ssl_routines:ssl3_read_bytrs: sslv3 alert handshake SSL alert number 40.
In a word, I want to know in openssl 1.1.1, can we use M2 asymmetric encryption in SSL? 
Besides, in 
./openssl req -new -x509 -sha256 -key priv.key -out cer.crt -days 10000 -subj '/C=CN/ST=Beijing/L=Haidian/O=Datang/OU=SDT/CN=Shixun/emailAddress=dongzy08@163.com'
if I change -sha256 to -SM3, then I got a error:
error 100C508A: elliptic curve routines: invalid digest type.

**Comment by InfoHunter** [comment]
The answer is *no*. We have not supported SM2 with SSL/TLS protocol at current stage. The main reason for this is there lacks of standards about how to use SM2 in TLS protocol. So before relevant standards coming out, there will be no SM2 in TLS protocol...

**Comment by Mingzhe-Zhu** [comment]
> The answer is _no_. We have not supported SM2 with SSL/TLS protocol at current stage. The main reason for this is there lacks of standards about how to use SM2 in TLS protocol. So before relevant standards coming out, there will be no SM2 in TLS protocol...

Thanks a lot...  
We want to use SM2 with SSL/TLS protocol in commercial products. As you know, GmSSL has already finished SM2 in SSL protocol. But we are not sure about the stability of this open source project. Do you have some opinions?

**Comment by richsalz** [comment]
I wonder what TLS values GmSSL uses for SM2?  The IETF has not assigned any.

**Comment by InfoHunter** [comment]
>  As you know, GmSSL has already finished SM2 in SSL protocol.

> I wonder what TLS values GmSSL uses for SM2? 

The TLS protocol in GmSSL is not the widely adopted *standard* protocol which is published by IETF RFCs. That protocol is a Chinese-modified version of TLSv1.1 published by GM/T 0024-2014  as a Chinese national standard.

OpenSSL (along with other popular open source crypto libraries and browsers) follows the international standard, for instance TLSv1.3 as the latest one in this series. So I think it's possible for OpenSSL to support SM algorithms with standard TLS protocol (but which is not defined yet as Rich and I mentioned above). And I don't know if OpenSSL is going to support GM/T 0024-2014, but from my perspective, the possibility is very low...

For GmSSL, TBH I haven't tried that before so I don't know the stability of it...

**Comment by InfoHunter** [comment]
I assume this issue is resolved, so closing...
