### ISSUE TITLE
Fix internal tests for shared Windows builds

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#7492]
The testsuite has many so called _internal_ tests, which link statically against libcrypto and/or libssl. All these internal tests are disabled for shared Windows builds, because the names of the static libraries collide with the names of the import libraries for the DLLs.

https://github.com/openssl/openssl/blob/f81b043ad856d8b9af5239a4978f8bd4b965dab9/test/build.info#L434-L445

There has been some discussion about whether the static libraries should be renamed, but that is only an option for the next major release. I would like to suggest a temporary workaround which would be backportable to 1.1.1 and would enable us to activate all internal tests for shared Windows builds.

Instead of renaming the _installed_ libraries, one could build additional static libraries (on windows only) to make the static tests depending on these. One does not even have to rename the static libraries, just place them in a separate directory (e.g. `static\libcrypto.lib`, `static\libssl.lib`), to distinguish them from the import libraries. These static libraries would only be used for the internal tests and not installed later on.

If building two library versions is undesired on this notoriously slow platform, then one could add a --static-tests option for windows, which is disabled by default.

**References**

This request originated from a discussion with @levitte in #7462, see in particular

* https://github.com/openssl/openssl/pull/7462#issuecomment-432021865
* https://github.com/openssl/openssl/pull/7462#issuecomment-432106224
* https://github.com/openssl/openssl/pull/7462#issuecomment-432118520

**Comment by levitte** [comment]
#7496 is an attempt to do this.  It's really a quick hack, but a fairly easy one to understand.

**Comment by mspncp** [comment]
Cool,  thank you very much! That was a really fast reaction.

I'll rebase #7462 on top of this pr and and check whether it works (later this evening).

**Comment by mspncp** [comment]
If it works, I'll try to enable all the other tests, too. (If you already started doing it, go ahead of course.)

**Comment by mspncp** [comment]
Oh, vorget my last remark. The changes for test/build.info are already in your pr.
