### ISSUE TITLE
Cross compile of FIPS canister build produces wrong HMAC for text section on ARM/thumb instructions.

### ISSUE THREAD

**Issue by dghq67** [openssl/openssl#7498]
When the incore script produces the HMAC signature across text and read only data section of the FIPS canister, it uses the addresses directly out of the ELF header to address the offset in the SO file. As the ARM ABI specifies all text symbol addresses that reference thumb instructions have bit zero set to indicate that it is addressing a thumb instruction, the incore script does the HMAC across the required address plus 1. The runtime HMAC check uses the current instruction position plus offset to address the memory being HMACed and uses the correct address, this produces an mismatching HMAC and fails the canister:

```bash

root@ace1000:~/20181015# ./fips-test2 
.rodata start: 0x401af360
.rodata end: 0x401b5e3c
.text start: 0x400e4a00
.text end: 0x40111e5c
Embedded: 15cde835df5fb529f860ca141ae79a2cc7efd720
Calculated: ab80f1c0af402467b08efab9c65e1e162809bb9a
Re-Calculated at .text + 1 : 15cde835df5fb529f860ca141ae79a2cc7efd720
FIPS mode: 0
Attempting to enable FIPS mode
1075847824:error:2D06B06F:FIPS routines:FIPS_check_incore_fingerprint:fingerprint does not match:fips.c:232:

```

This is being cross compiled as:

CURRENT_OPENSSL_VERSION=openssl-1.0.2p
CURRENT_FIPS_VERSION=openssl-fips-ecp-2.0.16
export SYSTEM="Linux"
export HOSTCC="gcc"
export MACHINE="armv71"
export ARCH="arm"
export CROSS_COMPILE="arm-linux-gnueabihf-"
export FIPSDIR="$modbasedir/deliver"
export FIPS_SIG="$privdir/${CURRENT_FIPS_VERSION}/util/incore"

The build server is:

uname -a
Linux srv606 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

But I get the same results from a cross compile docker as well.

**Comment by paulidale** [comment]
This issue is not going to be fixed.  Doing so would require modifying the FIPS object module which would, in turn, require a completely new FIPS validation.  In its current form, it could not pass.

The choice comes down to:
1. accept this problem or
1. fix it and cease being FIPS.

Neither is ideal.

**Comment by vikas-yadav77** [comment]
Hi, 

@dghq67, I am also facing similar kind of issue,  Do we have any solution for this issue?
