### ISSUE TITLE
Sending/receiving custom TLS frames

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#7514]
I'd like it to be possible to schedule sending custom TLS frames. In addition to making custom behaviour possible, the implementation of e.g. `SSL_key_update` would become simpler, with the possibility that future TLS extensions could be implemented as shared libraries, without newer openssl releases.

Likewise you'd need a way to register a handler for custom TLS frames.

**Comment by kaduk** [comment]
I'm not sure I understand how this would be useful for as-yet-unknown future TLS record or handshake type.  For example, a hypothetical key update analogue would require a way to update the key hierarchy in use, which seems like it would need to touch the library internals.  Absent a use case where a completely external implementation that does not access the library internals could work, it's unclear that there's a reason to adopt such functionality.  (Do you have a use case in mind that I'm not thinking of?)

**Comment by t8m** [comment]
I do not think we are going to implement such feature in foreseeable future.
