### ISSUE TITLE
openssl/rand_drbg.h should include openssl/obj_mac.h

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#7521]
When using this header in 3rd party code, it references NID values but doesn't include mac_obj.h leading to compile failures unless you include that header manually beforehand. Additionally you also need to reference NID values in RAND_DRBG_secure_new or RAND_DRBG_new to instantiate an instance. so it's not wasted.

**Comment by richsalz** [comment]
The tests try to compile everything with just a single include, to make sure all files are usable by themselves. That test would have caught this. The rand_drbg file, if it's really public, needs to be added to that test.

**Comment by dlegaultbbry** [comment]
Well I don't know if it's covered in your compile test but it is a public header.

dist/CHANGES:  *) Added new public header file <openssl/rand_drbg.h> and documentation

**Comment by mspncp** [comment]
@dlegaultbbry of course the missing include needs to be fixed. Rich only meant to say that also the test which would have caught this issue, is missing. I'll have a look at it.

**Comment by mspncp** [comment]
See #7524

**Comment by mspncp** [comment]
Third attempt. It's too late in the evening for writing pleasing and typo free commit messages... ;-)
