### ISSUE TITLE
openssl needs auto link function like boost

### ISSUE THREAD

**Issue by runforu** [openssl/openssl#7525]
1. Modify the build system to support the different file name of output library based on the compiling instruction. The name looks like libssl-mt-gd-x32.lib
2. Add indicator in the header file to make a auto link to the library which the header file contribute to.
it looks like
#define OPENSSL_LIB_PREFIX "lib"
#define OPENSSL_LIB_NAME "ssl"
#define OPENSSL_LIB_THREAD_OPT "mt"
#define OPENSSL_LIB_THREAD_DEBUG "gd"
#define OPENSSL_LIB_CPU "x32"
#pragma comment(lib, OPENSSL_LIB_PREFIX BOOST_STRINGIZE(OPENSSL_LIB_NAME ) OPENSSL_LIB_THREAD_OPT OPENSSL_LIB_THREAD_DEBUG  OPENSSL_LIB_CPU ".lib")

**Comment by levitte** [comment]
Why do we need to do this?

**Comment by mattcaswell** [comment]
No response from OP, so closing this.
