### ISSUE TITLE
This comment seems to be outstanding

### ISSUE THREAD

**Issue by borisPis** [openssl/openssl#7527]
_Originally posted by @mattcaswell in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MTY5NDA0NzM5/pull_request_reviews/more_threads_

What do you mean? - AFAIU it is resolved.

**Comment by levitte** [comment]
That link does seem to be valid

**Comment by mattcaswell** [comment]
This is part of PR #5253. Not sure why it got raised as a separate issue. I suspect this was done in error. Closing.
