### ISSUE TITLE
1.1.1 Final:  04-test_err.t test failure on several RedHat build platforms

### ISSUE THREAD

**Issue by Simon-Edwards01** [openssl/openssl#7528]
Synopsis: errno is not preserved across calls to pthread_once.  So a test for errno preservation fails.

This has not been checked on earlier versions of OpenSSL, just the 1.1.1 final GA version.

Details:

Whilst doing builds of OpenSSL on quite a few Linux/Unix platforms we see a failure crop up on several RedHat build platforms. Specifically IBM 390 and x86/x64 chipsets. It doesn't appear on RedHat Power PC build systems.  Nor does it appear in Suse builds on the same failing chipsets.

A typical setup for x86 looks like this...

Configure linux-x86 no-threads  enable-ssl3 no-ec2m no-idea no-rc5 no-weak-ssl-ciphers enable-capieng  no-deprecated no-shared -DOPENSSL_NO_AUTOLOAD_CONFIG --prefix=`pwd`/buildoutput --openssldir=`pwd`/buildoutput -D_FILE_OFFSET_BITS=64

Due to this issue we have a consistent test failure in the post-build test runs.

```
../test/recipes/04-test_err.t ...................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

All the other tests pass.

Debugging shows the following sequence.

.. in the test cycle on 32bit single threaded post-build test runs the auto-initialisation code gets triggered.

The whole test looks like this...

``` C
static int preserves_system_error(void)
{
#if defined(OPENSSL_SYS_WINDOWS)
    SetLastError(ERROR_INVALID_FUNCTION);
    ERR_get_error();
    return TEST_int_eq(GetLastError(), ERROR_INVALID_FUNCTION);
#else
    errno = EINVAL;
    ERR_get_error();
    return TEST_int_eq(errno, EINVAL);
#endif
}
```

... But the actual implementation walks through quite a lot of auto-init stuff that works fine. I have skipped over most of the debugged code-path in the sequence below. Until the following sequence happens beneath OPENSSL_init_crypto()...

```
(gdb) r
Starting program: /home1/hub/axle/axle18/ri/openssl/single/32/openssl/test/errtest
[Thread debugging using libthread_db enabled]

Breakpoint 1, main (argc=1, argv=0xffffd4f4) at test/testutil/main.c:36
36          int ret = EXIT_FAILURE;
(gdb) c
Continuing.

Breakpoint 2, main (argc=1, argv=0xffffd4f4) at test/testutil/main.c:51
51              ret = run_tests(argv[0]);
(gdb) c
Continuing.
1..1

Breakpoint 3, ERR_get_error () at crypto/err/err.c:429
429         return get_error_values(1, 0, NULL, NULL, NULL, NULL);
(gdb) c
Continuing.

Breakpoint 4, get_error_values (inc=1, top=0, file=0x0, line=0x0, data=0x0, flags=0x0) at crypto/err/err.c:483
483         es = ERR_get_state();
(gdb) c
Continuing.

Breakpoint 5, ERR_get_state () at crypto/err/err.c:702
702             OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL);
(gdb) c
Continuing.

Breakpoint 6, OPENSSL_init_crypto (opts=2, settings=0x0) at crypto/init.c:603
603                 && !RUN_ONCE(&load_crypto_strings, ossl_init_load_crypto_strings))
(gdb) s
CRYPTO_THREAD_run_once (once=0x82545ec, init=0x806c16b <ossl_init_load_crypto_strings_ossl_>) at crypto/threads_pthread.c:112
112     {
(gdb) l
107
108         return;
109     }
110
111     int CRYPTO_THREAD_run_once(CRYPTO_ONCE *once, void (*init)(void))
112     {
113         if (pthread_once(once, init) != 0)
114             return 0;
115
116         return 1;
(gdb) s
113         if (pthread_once(once, init) != 0)
(gdb) p errno
$27 = **22**
(gdb) s
116         return 1;
(gdb) p errno
$28 = **34**
(gdb)
```

Notice that its attempting to return 1.  So the call succeeded. However a by-product of success is to update errno holding EINVAL (22) with ERANGE (34) and so the test fails.  

The code makes no attempt to check errno as it is not supposed to be updated.

It appears that pthread_once is defined to return an errno value, not set errno. But it's not defined as not setting errno, either. It appears that setting errno is up to the vendor's implementation.

In POSIX.1 2008, pthread_once was only allowed to return EINVAL.

As of the 2017 update...
http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_once.html
...it's allowed to set anything except EINTR. Still no comment on errno though.

So it appears this is a legitimate portability bug in either OPENSSL_init_crypto or CRYPTO_THREAD_run_once, depending on at what level the "preserves errno" guarantee is supposed to be enforced. 

The simplest fix would be to save and restore errno in CRYPTO_THREAD_run_once, but it may be appropriate to move that higher in the logic, depending on where errno is used internally and how many places call CRYPTO_THREAD_run_once.

**Comment by bernd-edlinger** [comment]
Confirmed, I can reproduce if I set errno in ossl_init_load_crypto_strings:
```
diff --git a/crypto/init.c b/crypto/init.c
index fc6aade..c0fe42f 100644
--- a/crypto/init.c
+++ b/crypto/init.c
@@ -198,6 +198,7 @@ DEFINE_RUN_ONCE_STATIC(ossl_init_load_crypto_strings)
     ret = err_load_crypto_strings_int();
     load_crypto_strings_inited = 1;
 #endif
+errno = 99;
     return ret;
 }
```

**Comment by bernd-edlinger** [comment]
The whole test seems fragile, I would not have expected ERR_get_error to preserve errno.
@davidben 
from the commit message of 2de108dfa343c3e06eb98beb122cd06306bb12fd
it seems to me that a lot of code runs between the O/S error and the SSL_get_error,
which can have an effect on the errno.  Which means, I think preserving errno
around TlsGetValue is a good thing, but assuming the errno is preserved when
all the way from the socket thru the bio to the SSL_get_error seems questionable.

**Comment by bernd-edlinger** [comment]
With above error injection the test case starts to fail from the first day on.

Well, I think the underlying problem is as follows:
We have an O/S call in a socket BIO function, the call sets errno.
The result bubbles up a BIO stack to the SSL which returns to
user code, which calls SSL_get_error, which always erases errno,
or whatever Windows has for the same puropse in the TlsGetValue.
Then if the SSL_get_error does not have any idea what it was, it returns
SSL_ERROR_SYSCALL, and then the user code probably expects
errno to have still something useful.

No doubt the stack has probably grown deeper, and the initialization
code has become more complex.

However we have a way to preserve the error number, by using
`SYSerr(SYS_F_FCNTL, get_last_sys_error());` or similar.
I wonder why we are not simply using it.

And OTOH doesn't this whole incident mean that errno passes
from crypto-code to user-code, without being cleared?

**Comment by Simon-Edwards01** [comment]
Yes that last comment is exactly the crux of the problem. 

The "information" being passed in errno is the cause of failure of what is by then an unknown O/S call that happened somewhere much deeper. So unless it is overridden by OpenSSL code with a sensible value it is at best dubious in quality and cannot be relied upon to diagnose behaviour of the OpenSSL API call.

The main problem with this is that the caller cannot trust the OpenSSL API to tell it what has gone wrong.

Armed with your information I now suggest that :

1. The test case is (slightly surprisingly) therefore valid as it is written.  
2. That errno needs to be protected across the whole API call being tested unless a failure is being reported. In which case it should be set explicitly to match the error.
3. That the new 1.1.1 auto-initialisation code insertions be modified to preserve errno as described in (2). 
4.  In no circumstances should errno be modified if no error is being reported by OpenSSL in any API calls.

(4) seems like a nice principle, but is probably not achievable in a hurry.

**Comment by makr** [comment]
This test case also fails on Solaris and AIX builds. It, however, only fails in the automatic build. When manually attempting to reproduce on the console to get a verbose output, it succeeds.

**Comment by mattcaswell** [comment]
#7680 should fix this issue.
