### ISSUE TITLE
Memory should be cleansed after calling the keylog callback

### ISSUE THREAD

**Issue by mkauf** [openssl/openssl#7534]
[Keylog callbacks](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_keylog_callback.html) are called with a parameter ``line`` that contains the key material. After calling the callback, the memory allocated for ``line`` should be cleansed with [OPENSSL_cleanse()](https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_cleanse.html).

Currently this memory is not cleansed. See the function ``nss_keylog_int()`` in the file ``ssl_lib.c``.

**Comment by paulidale** [comment]
This should be fixed now.
