### ISSUE TITLE
Cannot compile openssl1.1.1's Windows 32-bit static library

### ISSUE THREAD

**Issue by Mingzhe-Zhu** [openssl/openssl#7535]
First of all, currently, is there an official openssl 1.1.1 Windows 32-bit static library? Where can I download it?
Besides, I referred to the Chinese link: https://blog.csdn.net/qq_22000459/article/details/82968171. But as many of the posts on the web say, the nmake tool compiled incorrectly and could not be fixed. Using the dmake.exe under perl to compile also comes with an Error: Error: -- Expecting macro or rule defn, found neither. I tried many times and cann't fix it. So far, it is easy for me to complie static library of openssl 1.1.1 under linux system, but in windows systems, I can not solve the problem.
Is anyone that can help me? Thanks a lot.

**Comment by levitte** [comment]
How about you show us exactly what you did, and what errors you get.  Start with your configuration command, and then a log of what goes wrong.

**Comment by Mingzhe-Zhu** [comment]
> How about you show us exactly what you did, and what errors you get. Start with your configuration command, and then a log of what goes wrong.

![image](https://user-images.githubusercontent.com/33438500/47779490-2bf03300-dd34-11e8-98c7-0e462f4968f1.png)

**Comment by mattcaswell** [comment]
You're not supposed to use dmake. You are supposed to use nmake. What happens when you attempt to use that?

**Comment by Mingzhe-Zhu** [comment]
> You're not supposed to use dmake. You are supposed to use nmake. What happens when you attempt to use that?

![image](https://user-images.githubusercontent.com/33438500/47779774-e41ddb80-dd34-11e8-9357-474688da1967.png)
I refer to the posts on many websites in China, all of which say that nmake compilation will have problems, so I use dmake.I tried it. There's also a problem.A post on the website seems to say that the makefile supports nmake by default, and that it is easily buggy to compile with dmake.But nmake compilation also has problems, so it's hard to fix.

**Comment by mattcaswell** [comment]
Are you running this from a *developer* command prompt? Running nmake from the command line requires your environment to be properly set up. Using the developer command prompt should do that for you. Make sure you use the 32-bit developer command prompt with the VC-WIN32 OpenSSL Configuration target. If you really want 64-bit then use a 64-bit developer command prompt and VC-WIN64A OpenSSL Configuration target.

**Comment by levitte** [comment]
The the output, it looks like the environment is set up correctly.  @Mingzhe-Zhu, would you mind translating that error message?  Most of us don't read Chinese.

**Comment by levitte** [comment]
It's the translation of the `cl` error message that I'm interested in.  Among others, it should say on what line the error occurred.

**Comment by InfoHunter** [comment]
Although I know zero about Windows but I can provide the translation Richard was interested in. That `cl` error message said `'cl' is not either an external or internal command or an executable program`...

I guess you can then figure out the 'native' wording of Windows...

**Comment by InfoHunter** [comment]
the `0x1` and `0x2` are return values of `cl` and `nmake.exe` in the 2 `fatal error U1017` lines, respectively.

**Comment by levitte** [comment]
Ah, in that case I was wrong earlier, the environment isn't set up right. See @mattcasswell's comment...

**Comment by levitte** [comment]
Thanks for the translation, @InfoHunter

**Comment by Mingzhe-Zhu** [comment]
Since the vs2015 x86 local tool command prompt was not installed by default, I need to rerun the installation program of vs2015 to supplement the installation again.
Use vs2015 x86 local tool command prompt to run nmake.
Thanks a lot. Problem sloved. @levitte @mattcaswell @InfoHunter
