### ISSUE TITLE
pkeyutl -sign produces "Public Key operation error"

### ISSUE THREAD

**Issue by cronos2** [openssl/openssl#7537]
When attempting to sign data using `pkeyutl` the execution exits with the aforementioned error. Steps to reproduce:

`openssl pkeyutl -sign -inkey <private_DSA_key> -in <data_to_be_signed>`

For reference, I am using "OpenSSL 1.1.0f 25 May 2017" under Debian Stretch 9, Linux 4.9.0-7-amd64. Some colleagues have been able to reproduce this behaviour in different GNU/Linux environments, but not MacOS, for example, so it seems to be a portability issue.

Let me know if I can provide any additional details that might be helpful. Thank you for your time.

**Comment by levitte** [comment]
Could you give us a full log?  There should be more error messages.

**Comment by levitte** [comment]
Also, on affected systems, please check if DSA has been disabled...

```
openssl list -disabled
```

**Comment by mattcaswell** [comment]
I'd also ask you how long the data is that is being signed.

See the man page for this utility:
https://www.openssl.org/docs/man1.1.0/apps/pkeyutl.html

As noted on that page DSA will assume SHA1 is in use and:
"... if the value of digest is sha1 the input should be 20 bytes long binary encoding of SHA-1 hash function output."

**Comment by levitte** [comment]
(apologies for the put down, @mattcaswell...  I just want to make sure to avoid red herrings if we can)

**Comment by mattcaswell** [comment]
Sure, no problem. Just a thought. Note that the "The input data looks too long to be a hash" error messages doesn't exist in 1.1.0 though. However, I think it still just ignores data that exceeds q.

**Comment by cronos2** [comment]
> Could you give us a full log? There should be more error messages.

Sure, could you tell me how to do that? I haven't found anything in the manual, nothing seemingly related in `/var/log`.




> Also, on affected systems, please check if DSA has been disabled...
> 
> ```
> openssl list -disabled
> ```

This is the output

```
Disabled algorithms:
HEARTBEATS
IDEA
MD2
MDC2
RC5
SCTP
SSL3
ZLIB
```

So I guess the answer is no.

> I'd also ask you how long the data is that is being signed.
> 
> See the man page for this utility:
> https://www.openssl.org/docs/man1.1.0/apps/pkeyutl.html
> 
> As noted on that page DSA will assume SHA1 is in use and:
> "... if the value of digest is sha1 the input should be 20 bytes long binary encoding of SHA-1 hash function output."

Yes, I read that part of the manual after several attempts, although it's somewhat hidden in my opinon. I've tried different sizes. A few bytes directly from stdin, a medium size file (~100B) and a *large* file (12KB). All of them get the same treatment. Feeding it a raw input or a digest doesn't matter either. So, again, I guess the answer is no (this is probably not the cause).

**Comment by levitte** [comment]
> > Could you give us a full log? There should be more error messages.
> 
> Sure, could you tell me how to do that? I haven't found anything in the manual, nothing seemingly related in `/var/log`.

You misunderstood.  I mean the full output.  When `openssl pkeyutl` says "Public Key operation error", there should be at least one more line of output.

**Comment by cronos2** [comment]
> > > Could you give us a full log? There should be more error messages.
> > 
> > 
> > Sure, could you tell me how to do that? I haven't found anything in the manual, nothing seemingly related in `/var/log`.
> 
> You misunderstood. I mean the full output. When `openssl pkeyutl` says "Public Key operation error", there should be at least one more line of output.

Oh, I'm sorry. No, that's the only output I get.

**Comment by levitte** [comment]
...

That's *really* weird

**Comment by levitte** [comment]
Ooooooh!  I happen to have a machine that runs Debian 9! ...  and I just reproduced the error.  So ok, now I've something to work with.

**Comment by cronos2** [comment]
Nice! Glad I could help then. Let me know if there's anything else I can do.

**Comment by levitte** [comment]
This all seems to depend on OpenSSL version.  Up to 1.1.0h, the behaviour is as you describe, but after that, conditions are more relaxed when no digest algorithm was specified explicitly (to be exact, that happened with commit 34515e8f88e57c13cdf2b1d4ec094ffd4e9f8d94).

The exact same problem can be generated with a more modern OpenSSL, all you have to do is give an explicit digest:

```
: ; echo -n 012345678901234567890 | openssl pkeyutl -sign -inkey test/testdsa.pem -hexdump -pkeyopt digest:sha1
Public Key operation error
: ; echo -n 01234567890123456789 | openssl pkeyutl -sign -inkey test/testdsa.pem -hexdump -pkeyopt digest:sha1
0000 - 30 2d 02 15 00 87 88 89-10 8d d7 01 8d 74 b1 9e   0-...........t..
0010 - 22 6f da c7 da 0c de 83-d5 02 14 59 43 22 5d 9e   "o.........YC"].
0020 - be 4b ea b3 55 90 ef 5e-73 40 d8 bf 3a 61 65      .K..U..^s@..:ae
: ; echo -n 012345678901234567890 | openssl pkeyutl -sign -inkey test/testdsa.pem -hexdump
0000 - 30 2d 02 15 00 c8 68 4c-dc 85 7b 08 a8 58 9d 74   0-....hL..{..X.t
0010 - 63 46 82 ca 8b 87 d7 b5-45 02 14 15 26 c3 4d 48   cF......E...&.MH
0020 - e2 c9 2d bf 66 8d d1 94-19 3e 62 a0 de 7a a0      ..-.f....>b..z.
: ; openssl version
OpenSSL 1.1.1  11 Sep 2018
```

So the answer for you is that it depends on your OpenSSL version (you never mentioned what version you run on MacOS)...  as for Debian 9, you might want to encourage them to upgrate their openssl package.  I'm not sure if that conforms to their update policy, though.

That closes this case.
