### ISSUE TITLE
Where did c2i_ functions go?

### ISSUE THREAD

**Issue by jayz5** [openssl/openssl#7538]
I have some sample code which uses c2i_ functions like `c2i_ASN1_INTEGER()`, but in openssl 1.1.1 I cannot compile it since all c2i_* functions are missing from the header file asn1.h where I used to see them: https://github.com/openssl/openssl/blob/master/include/openssl/asn1.h

Can someone let me know where these c2i functions go, or what are their replacement?

**Comment by mattcaswell** [comment]
The c2i functions are considered internal only and were removed from the public API in OpenSSL 1.1.0. You should use the d2i equivalents instead.

**Comment by jayz5** [comment]
thanks @mattcaswell

**Comment by thejeff77** [comment]
@mattcaswell do you have any recommendations on replacements for c2i_ASN1_INTEGER? 

The d2i_ASN1_UINTEGER is the only similar one, and it does not do the same thing.

Thanks for any advice! I'd love to get by this blocker I have here.

**Comment by mattcaswell** [comment]
The c2i_* functions parse  the content bytes of a DER INTEGER, i.e. the bit after the tag/length. You need to rewrite your code to pass the whole DER INTEGER encoding including the tag/length and use the d2i_* functions instead.

**Comment by thejeff77** [comment]
Fixed it up, not too bad. You can close this if you like.

**Comment by udiakasnuke** [comment]
I am recently migrating from 1.0.2 to 1.1.1. I am having hard time figuring out how to convert c2i_ASN1_INTEGER to one of its equivalent. Can someone please provide me with the source please. Thanks!! 
@mattcaswell @thejeff77

**Comment by thejeff77** [comment]
@udiakasnuke - this was my solution in Swift code using the equivalent d2i function:

```
    func DecodeASN1Integer(startOfInt intPointer: inout UnsafePointer<UInt8>?, length: Int) -> Int? {
        let integer = d2i_ASN1_UINTEGER(nil, &intPointer, length)
        let result = ASN1_INTEGER_get(integer)
        ASN1_INTEGER_free(integer)
        return result
    }
```

**Comment by udiakasnuke** [comment]
Thanks @thejeff77, pardon me but i don't see any visible difference b/w the usage of c2i_ASN1_INTEGER and it's near equivalent d2i_ASN1_UINTEGER apart from this extra line **let result = ASN1_INTEGER_get(integer)** but that might further be because of swift code. I am still a bit unclear. Please clear me!!

**Comment by mattcaswell** [comment]
A DER encoded integer consists of a single byte "tag", followed by 1 or more bytes indicating the length of the integer, followed by the contents of the integer itself. `c2i_ASN1_INTEGER` assumes that you have already decoded the tag and length bytes somehow and are just decoding the "content" bytes. `d2i_ASN1_INTEGER` on the other hand decodes the whole thing, tag, length bytes and the content bytes.

These two functions are not a straight one-for-one swap. You need to analyse your application that is currently calling `c2i_ASN1_INTEGER` and figure out how it is decoding the tag and length bytes, and replace all of that code with `d2i_ASN1_INTEGER`.
