### ISSUE TITLE
client with openssl 1.0.1e can't connect to server with openssl 1.1.1-1 via tlsv1.2

### ISSUE THREAD

**Issue by ITwrx** [openssl/openssl#7539]
i don't know if this is a bug or if this is intentional, but i thought i'd report just in case. 

i have an android 4.4.4 client running openssl 1.0.1e (i think. i ran "strings /system/lib/libssl.so | grep -i openssl" to determine that.). i have an xmpp server with openssl 1.1.1-1. when trying to connect to the server(prosody) with the conversations app on the phone i get an "inappropriate fallback" error. downgrading openssl on the server to openssl-1.1.0.h-1 allows the tls connection to be established.
thanks

**Comment by kroeckx** [comment]
1.0.1e at least reminds me of issue #7126, but this looks like a different error.

Can you check with something like wireshark or tcpdump that there are 2 connection attempts, where the first uses TLS 1.2 but fails, and then tries again with TLS 1.1?

Is that server running Debian? If yes, can you try editing the /etc/ssl/openssl.cnf file, and change the SECLEVEL from 2 to 1 and see if that helps?

**Comment by ITwrx** [comment]
i performed a capture earlier and it looks to just be one attempt that is rejected, but i'm not experienced with tcpdump so here's a little screenshot. 

![screen_of_wireshark](https://user-images.githubusercontent.com/1002762/47823324-bab17f80-dd35-11e8-8711-fc84c94e2af4.png)

the server is running archlinux and i didn't realize that downgrading openssl would break pacman so i can't upgrade openssl back to 1.1.1-1 to test seclevel right now. i'll try to get back to you on that once i debork my xmpp server...
thanks

**Comment by kroeckx** [comment]
If it's running archlinux, forget about the seclevel thing.

**Comment by kroeckx** [comment]
Is it possible that you send a pcap file to us so that we can take a look it? Or open that file with wireshark and show more of the details in the packet like the list of ciphers it's sending.

**Comment by kroeckx** [comment]
He mentioned that the client is the "conversations app" on android 4.4.4

**Comment by davidben** [comment]
Probably this then: https://github.com/siacs/Conversations/commit/fd7a5c605aa14852398c514288ab5d1971573a47#diff-26f9d14899125d9a8d7f6b219ff95815

**Comment by ITwrx** [comment]
client is Conversations 1.16.0. here's another screen. if that doesn't give you what you need, maybe you can point me to an email address you want me to use for the pcap.

![wireshark_screen2](https://user-images.githubusercontent.com/1002762/47824460-00bd1200-dd3b-11e8-8cae-338d279f6d5e.png)

@davidben  so, maybe conversations is doing something wrong but it was allowed to slide by openssl until v1.1.1?

**Comment by ITwrx** [comment]
maybe i need to update conversations, fix my borked pacman, update openssl and get back to y'all?

**Comment by davidben** [comment]
Yes, the way FALLBACK_SCSV works, if you set it wrong, you can easily make version-intolerant clients on accident, which is unfortunate. It appears to be fixed though, so try updating your client.

(Looks Conversations uses `getSupportedCipherSuites` rather than `getDefaultCipherSuites`, and Android's TLS library included "TLS_FALLBACK_SCSV" in the former. That seems a bad idea. I'll file a bug with them.)

**Comment by ITwrx** [comment]
cool, thanks to both for the help and for reporting that.

**Comment by kroeckx** [comment]
So I think there is nothing we can do about this on our end, and we have bugs filed on the relevant other side, so I'm closing this.
