### ISSUE TITLE
Use of uninitialized value in pattern match

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#7543]
I'm see the following error (repeated a number of times) when running make against master:

````
Use of uninitialized value in pattern match (m//) at ./util/add-depends.pl line 39.
````

**Comment by mattcaswell** [comment]
I suppose I should say warning rather than error since the build continues successfully.

**Comment by levitte** [comment]
Ah, the joys of perl :-)

If `$foo{bar}` was undefined, refering to its content will suddenly make it defined.  There is a spot where we do something corresponding to `@{$foo{bar}}`, which will automatically create that hash table element with an empty array reference.  This is avoided with `${$foo{bar} // []}`.

PR coming up!

**Comment by levitte** [comment]
I should have cherry-picked the correction.  Done now.
