### ISSUE TITLE
can't parse ocsp response data in openssl ocsp module

### ISSUE THREAD

**Issue by mr-tan4** [openssl/openssl#7550]
system:mac os 
openssl version :

> OpenSSL 1.1.2-dev  xx XXX xxxx
built on: Tue Oct  9 05:17:36 2018 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: cc -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/opt/openssl/lib/engines-1.1"
Seeding source: os-specific

command:

 >openssl ocsp -issuer chain.crt -cert client2.crt -text -url http://localhost:8000

result:
![image](https://user-images.githubusercontent.com/15813848/47889859-18a1ac80-de87-11e8-9ca5-6d105d12a52d.png)

**Comment by mattcaswell** [comment]
So - what seems to be the problem? I don't see an error here?

**Comment by t8m** [comment]
No response from the reporter. Closing.
