### ISSUE TITLE
OpenSSL 1.1.1 final: Excessive amount of warnings (5430) in x448 code compilation on 32bit platforms.

### ISSUE THREAD

**Issue by Simon-Edwards01** [openssl/openssl#7556]
The 1.1.1 code set includes X448 code source sets that are not 32bit friendly.  

The warnings all make use of a macro SC_LIMB in **/crypto/ec/curve448/word.h**

A RedHat build example is in the attached file.

[32bitUnixLinux_x448_warnings.txt](https://github.com/openssl/openssl/files/2543421/32bitUnixLinux_x448_warnings.txt)

Here is one example.
``` C
crypto/ec/curve448/curve448.c:30: warning: integer constant is too large for 'long' type
```
There are 5436 lines in the attached RedHat build warnings file.  Of which roughly **5430 lines are warnings caused by this one issue.**

This occurs on AIX 32bit builds using the standard OpenSSL Configure build flags, but can be mitigated by the use of **-qlanglvl=stdc99**

This occurs on RedHat and Suse 32bit builds, and again on the Solaris Intel 32bit gcc builds where I have been unable to mitigate it so far.

The code is attempting to split 64bit unsigned longs (which should ideally be appended with "ULL" or "ull" but aren't) and insert them into a construction as two separate elements on a 32bit platform, and the same data as a single element on a 64bit platform. 

Its doing the conversion as s simple cast, well half of it is. The same cast is missing from construction of the second element. Surely there is a better way making this transition from 64 to 32-bits?

This is the actual line at fault.
``` C
#  define SC_LIMB(x) ((uint32_t)(x)),((x) >> 32)
```
Looking at the binary output afterwards under the debugger it appears to succeed in its aim. However the sheer quantity of warnings means that there is a risk of ignoring other real issues.  Plus of course requiring that we investigate the warning in a debugger to prove that it is actually working.

The rest of the relevant troublesome source from word.h is here:
``` C
# if (ARCH_WORD_BITS == 64)
typedef uint64_t word_t, mask_t;
typedef __uint128_t dword_t;
typedef int32_t hsword_t;
typedef int64_t sword_t;
typedef __int128_t dsword_t;
# elif (ARCH_WORD_BITS == 32)
typedef uint32_t word_t, mask_t;
typedef uint64_t dword_t;
typedef int16_t hsword_t;
typedef int32_t sword_t;
typedef int64_t dsword_t;
# else
#  error "For now, we only support 32- and 64-bit architectures."
# endif

/*
 * Scalar limbs are keyed off of the API word size instead of the arch word
 * size.
 */
# if C448_WORD_BITS == 64
#  define SC_LIMB(x) (x)
# elif C448_WORD_BITS == 32
#  define SC_LIMB(x) ((uint32_t)(x)),((x) >> 32)
# else
#  error "For now we only support 32- and 64-bit architectures."
# endif
```

A typical RedHat Configure looks like this...

Configure linux-x86 no-threads enable-ssl3 no-ec2m no-idea no-rc5 no-weak-ssl-ciphers enable-capieng no-deprecated no-shared -DOPENSSL_NO_AUTOLOAD_CONFIG --prefix=pwd/buildoutput --openssldir=pwd/buildoutput -D_FILE_OFFSET_BITS=64

**Comment by levitte** [comment]
So, it sounds like you're saying that this would be a better definition for `SC_LIMB`:

``` C
# if C448_WORD_BITS == 64
#  define SC_LIMB(hi,lo) (((hi) << 32) | (ll))
# elif C448_WORD_BITS == 32
#  define SC_LIMB(hi,lo) (lo),(hi)
```

**Comment by Simon-Edwards01** [comment]
No, you've got that a bit backwards.  

The issue is caused by taking a single value, such as "0xNNNN...NNN". Then splitting the value into two elements. 

In thousands of cases these large values are part of a table of comma separated elements in the x448 code.  After splitting it down into 32-bit values, both new elements remain comma separated after the macros have finished. 

Solving warnings from just two macros reduces the huge error count down to around 60 errors. Which I am still looking at.

It looks like most of those remaining errors will require appending "**ULL**" to the value directly in source to solve, as the the ones that I have seen so far don't get processed by macros at the point of the compiler warnings being generated.

The two main macros are:

- **SC_LIMB** in **word.h** 
- **LIMB** in **arch_32/f_impl.h**

Note: **FIELD_LITERAL** is the macro found in the source set. Each **FIELD_LITERAL** use generates eight warnings caused by the sub-macro **LIMB** that is inserted by **FIELD_LITERAL**. I have included both for transparency in the source snippet below.

The principal of the problem is in two parts.

1. That you should not assume that the compiler knows the length of a numeric definition unless you tell it. It will usually try to fit a value into an unsigned int, which doesn't work for large values in 32bit builds. The easiest solution to this is to append "ULL" to the large values concerned.  Whilst avoiding other variants such as "ull" and "llu" to allow its use on older compilers.  This issue is not limited to the x448 code, but this area is by far the most affected.
2. That having now got the length fixed at 64bit in (1). When using the compiler to perform the length conversion you should tell the compiler that the change is intended by casting it down to the lower length. Otherwise it warns you about the bits being lost in case it was unintentional. To remove the warning you need to tell it that the action is intentional.

None of this is an issue in 64bit builds, or builds where you can tell the compiler to use 64bits for fixed values (e.g. AIX).

Here's the first now-cleanly-compiling **SC_LIMB** macro, in word.h:   
``` C
# if C448_WORD_BITS == 64
#  define SC_LIMB(x) (x)
# elif C448_WORD_BITS == 32
#  define SC_LIMB(x) ((uint32_t)((x##ULL) << 32)),((uint32_t)(((x##ULL) >> 32)))
# else
#  error "For now we only support 32- and 64-bit architectures."
# endif
```

Here's the fixed-up main warning generator **LIMB** in arch_32/f_impl.h:

``` C
#ifndef HEADER_ARCH_32_F_IMPL_H
# define HEADER_ARCH_32_F_IMPL_H

# define GF_HEADROOM 2

# define LIMB(x) ((x##ULL) & ((1 << 28) - 1)), ((x##ULL) >> 28)
# define FIELD_LITERAL(a, b, c, d, e, f, g, h) \
    {{LIMB(a), LIMB(b), LIMB(c), LIMB(d), LIMB(e), LIMB(f), LIMB(g), LIMB(h)}}
```

**Comment by levitte** [comment]
Seems like you have things under control. Can we expect a PR?

**Comment by Simon-Edwards01** [comment]
Yes, in the next week or so.  
As of now I think there will be three PR from me for 1.1.1.  Only one may be slightly contentious. I will raise that one as a pair of related issues next week. Two issues because there's one obvious area I can't fix, docs.

**Comment by mspncp** [comment]
>As of now I think there will be three PR from me for 1.1.1.

Please open your pull request against the `master` branch nevertheless. It will be decided which parts can be cherry-picked resp. backported to 1.1.1, when the pull request gets accepted. (Bugfixes will almost certainly be backported to 1.1.1.)

**Comment by levitte** [comment]
I have a little bit more time now than before, and while I understand the reasoning for the `ULL` idea, we also need to remember that our code needs to be C89 for the pure language. `ULL` is a C99 feature.

This is why I went the other way and wanted to split the literal numbers in two halves, which would only be shift-ored together on 64 bit systems.

**Comment by levitte** [comment]
I'll create a PR promptly

**Comment by levitte** [comment]
I suppose, btw, that the `U` suffix is still required...  that one existed in already C89.

**Comment by levitte** [comment]
> but will mean editing some hundreds of 64bit fields to complete the change.

Are you sure about this?  I just did a grep for `SC_LIMB`, and got this:

```
: ; git grep SC_LIMB
crypto/ec/curve448/curve448.c:            SC_LIMB(0xc873d6d54a7bb0cf), SC_LIMB(0xe933d8d723a70aad),
crypto/ec/curve448/curve448.c:            SC_LIMB(0xbb124b65129c96fd), SC_LIMB(0x00000008335dc163)
crypto/ec/curve448/scalar.c:            SC_LIMB(0x2378c292ab5844f3), SC_LIMB(0x216cc2728dc58f55),
crypto/ec/curve448/scalar.c:            SC_LIMB(0xc44edb49aed63690), SC_LIMB(0xffffffff7cca23e9),
crypto/ec/curve448/scalar.c:            SC_LIMB(0xffffffffffffffff), SC_LIMB(0xffffffffffffffff),
crypto/ec/curve448/scalar.c:            SC_LIMB(0x3fffffffffffffff)
crypto/ec/curve448/scalar.c:            SC_LIMB(0xe3539257049b9b60), SC_LIMB(0x7af32c4bc1b195d9),
crypto/ec/curve448/scalar.c:            SC_LIMB(0x0d66de2388ea1859), SC_LIMB(0xae17cf725ee4d838),
crypto/ec/curve448/scalar.c:            SC_LIMB(0x1a9cc14ba3c47c44), SC_LIMB(0x2052bcb7e4d070af),
crypto/ec/curve448/scalar.c:            SC_LIMB(0x3402a939f823b729)
crypto/ec/curve448/word.h:#  define SC_LIMB(x) (x)
crypto/ec/curve448/word.h:#  define SC_LIMB(x) ((uint32_t)(x)),((x) >> 32)
```

**Comment by Simon-Edwards01** [comment]
Now take a look for the second macro... FIELD_LITERAL 

BTW I think the ULL horse may have already left the stable.  Whilst looking into an uninitialised variable issue on HP-UX builds I found the code in crypto/bn/bn_nist.c, there are rather a lot of them.  I don't know if they get switched on only for C99 builds?

**Comment by Simon-Edwards01** [comment]
It is kind of ironic that the ULL in crypto/bn/bn_nist.c are only used in 64bit builds, when they are not really needed.

The 32bit variants use your split 32bit variation as an #ifdef#else#endif  duplicated collection.  I'd rather not have to do that to the x448 table collection.

**Comment by levitte** [comment]
> FIELD_LITERAL

... ok, now my head hurts.  28-bit shift?????

**Comment by Simon-Edwards01** [comment]
indeed

**Comment by levitte** [comment]
It also strikes me as a bit odd that we basically only have the 32-bit curve448 implementation (just found the original in `https://sourceforge.net/p/ed448goldilocks/code/ci/master/tree/`)...  but ah well, I'm not gonna judge.

**Comment by mattcaswell** [comment]
> It also strikes me as a bit odd that we basically only have the 32-bit curve448 implementation

That was done because it was the lowest common denominator and the easiest thing to integrate that would work everywhere. The Curve448 PR was fairly huge as it was. My intention was always to go back and add some of the other optimised implementations - but other things took over and that never happened.

**Comment by levitte** [comment]
Ah, ok

**Comment by levitte** [comment]
Hmm, speaking of which, does anyone know the proper gcc / clang option to generate warnings on this kind of stuff?  I just tried, and even with a linux-x86 config (with `-march=i686 -m32`), these numbers are treated with complete silence.  I guess that says a bit about the capacity of these compilers, and yet, it would be nice to be able to catch this kind of issue.

**Comment by levitte** [comment]
Never mind that last question, that would be `-Wlong-long`...  which we reaaaaally want to avoid using in a general sense.

**Comment by levitte** [comment]
I just found `MONTGOMERY_FACTOR`...  I think I need to walk away from this for a bit.

**Comment by Simon-Edwards01** [comment]
Yes, I felt that way too. 

The good news is that after fixing up just those two macros the entire collection of warnings on the RedHat build is limited to 59 counts of this one type of issue in just seven files.

I have attached the remaining warnings for you to see
[OpenSSL1.1.1_64bit_warnings.txt](https://github.com/openssl/openssl/files/2566150/OpenSSL1.1.1_64bit_warnings.txt)

The compilation lines are included which show the flags in use at the time.

There are a lot of ULL used in the BN code, but all that I have looked at so far have a second 32bit implementation. However the use of ULL at all means that the 64bit version isn't c89 compliant today.  Is c89 only intended as a 32bit standard? I haven't looked.

The affected BN file collection is: 

        bn_nist.c    bn_gf2m.c    bn_lcl.h    bn_srp.c    bn_dh.c

ULL also makes an appearance in poly1305_ieee754.c, which doesn't appear to be only 64bit code and will need some attention for c89 compliance on 32bit.

I was initially only targeting a fix for the two macros as low hanging fruit. Two lines of change really does stop thousands of warnings.  But there is more to this one than those two.

**Comment by Simon-Edwards01** [comment]
in case it helps reproduce it here are my config args.

CONFIGURE_ARGS=("linux-x86", "no-threads", "enable-ssl3", "no-ec2m", "no-idea", "no-rc5", "no-weak-ssl-cipher
s", "no-deprecated", "no-shared", "-DOPENSSL_NO_AUTOLOAD_CONFIG", "--prefix=/home1/build/openssl/single/32/openssl/buildoutput", "--openssldir=home1/build/openssl/single/32/
openssl/buildoutput", "-D_FILE_OFFSET_BITS=64")

The gcc in use is 

gcc version 4.4.5 20110214 (Red Hat 4.4.5-6) (GCC)

**Comment by levitte** [comment]
You know...  another option would be for you to add `-Wno-long-long` to your configuration.  I believe this has been argued before (just not by me).  And yeah, one might argue that `-Wno-long-long` should be part of our standard config, but there's always the question of how far back that particular option is supported (and we do try to allow fairly aged gcc versions to build our source smoothly enough).

When I think of it, we have yet to get reports of where these number actually **fail**, not just *warn*, so this is more a story about compilers that like to complain loudly rather than builds that actually fail.

I think we also need to strike a balance on the other impact, i.e. maintainability of imported code.  If we want to import further improvements of the original code, what's the backlash if we deviate too much from it?  At what point does that cost us more than having to ignore a specific warning (possibly explicitly with `-Wno-long-long`)?  @mattcaswell, your opinion matters here, since you did the original import.

(and perhaps we simply *should* add `-Wno-long-long` as a standard gcc option, for everyone's peace of mind)

**Comment by Simon-Edwards01** [comment]
I took a similar view on AIX and added "-qlanglvl=stdc99" which has a similar effect.

However I then started to wonder at the sheer quantity of them, and tried to fix it at source.  BTW turning on C99 support on gcc didn't work well, although I can't remember the errors right now. They were no longer just warnings. Probably because you have some gcc extensions reliance in Linux build targets which would be switched off with strict C99 applied.

Whilst we think the current collection are safe to ignore. The downside is that if you add -Wno-long-long you will mask any real rounding errors that may be introduced later. Squelching errors is rarely a good long term solution.

**Comment by levitte** [comment]
> The downside is that if you add -Wno-long-long you will mask any real rounding errors that may be introduced later. Squelching errors is rarely a good long term solution.

I'm unsure that what this is true.  `-Wlong-long` only warns any time the `long long` type is used, be it implicitly or explicitly.  A quick test shows that there are other warnings when values are *actually* dropped, at least with gcc:

``` foo.c
#include <stdio.h>

int main() {
    long foo = 0x123456789;

    printf("%ld\n", foo);
}
```

```
: ; gcc -march=i686 -m32 -o foo foo.c
foo.c: In function ‘main’:
foo.c:4:16: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘4886718345’ to ‘591751049’ [-Woverflow]
     long foo = 0x123456789;
                ^~~~~~~~~~~
```

(I verified this as far back as gcc 4.8)

**Comment by Simon-Edwards01** [comment]
I'll have a play with the option and see what shows up.

**Comment by Simon-Edwards01** [comment]
Looking back I didn't answer one of your questions. The warning flag you need is -Wall. Like this, using your demo source above...

gcc -m32 -Wall  trial.c
trial.c: In function 'main':
trial.c:4: warning: integer constant is too large for 'long' type
trial.c:4: warning: overflow in implicit constant conversion

-qno-long-long doesn't appear to exist back in gcc 4.4.5 land. That it is simply ignored rather than causes an error is odd. I may be missing something here...

BTW looking at the MONTGOMERY_FACTOR substitutions I cannot see how it is not simply discarding 32-bits of expected data. I am gong to have to pre-process that one out to take a look after the macro's have worked through.

Is there a x448 test in the suite yet?

**Comment by levitte** [comment]
As you can see from my output, I didn't even need `-Wall`...

**Comment by regtable** [comment]
hi guys hope you dont mind me reopening this thread some what. 
i am building 1.0.2q (probably going to update to latest 1.0.2[q+]) see if it changes but this "warning" is worrysome.
```bss_bio.c: In function 'bio_nread':
bss_bio.c:320:15: warning: overflow in conversion from 'long long int' to 'long int' changes value from '9223372036854775807' to '-1' [-Woverflow]
         num = SSIZE_MAX;
```
i am unsure as to why this happens building using:
```
 mysys2
 mingw64 (make -v ){
GNU Make 4.2.1
Built for x86_64-pc-msys
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
}
gcc -v
{
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-8-20181214/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=ada,c,lto,c++,objc,obj-c++,fortran --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 8.2.1 20181214 (Rev1, Built by MSYS2 project)
}
i noticed this "warning during compile of my source code and never realised its importing the warning because of openssl i chased it around my code for a while looking for a fix but its a dependant problem.
you think its going to cause some major bugs if used as is? or could it be down to not having a defined value so its overflowing...
thanks in advance

**Comment by levitte** [comment]
How did you configure OpenSSL?

**Comment by regtable** [comment]
i used 
./Configure no-zlib no-shared no-dso no-krb5 no-camellia no-capieng no-cast no-cms no-dtls1 no-gost no-gmp no-heartbeats no-idea no-jpake no-md2 no-mdc2 no-rc5 no-rdrand no-rfc3779 no-rsax no-sctp no-seed no-sha0 no-static_engine no-whirlpool no-rc2 no-rc4 no-ssl2 no-ssl3 mingw64
make depend 
make

**Comment by levitte** [comment]
Hmm...  odd, I imagine that 64-bit mingw should have a 64-bit ssize_t (which ossl_ssize_t is an alias for).

I'll try to have a look in the next few days

**Comment by regtable** [comment]
no rush. i am happy that you responded within a few minutes :-). it all builds regardless so i will build the 64 bit application i am trying to make and just mess about see if i see anything actually breaking. 
im coming to think its a problem with the compiler though as every other dependancy i build has some form of "this is broken" error or warning 
im not 100% clued up on openssl and what the apps actually using from it may get lucky eh lol
thanks again 
if i find a work around i shall give a edit / post here

**Comment by regtable** [comment]
Ok so somehow I managed to build it from fresh tarball and not get this error cropping up just a few warnings for unused variables and also a few too many things defined for the function. Not sure why that is would think ssl being what it is code would compile clean as a whistle. Anywho turns out I was either compiling a polluted version x86 and x86_64 mixed up together or compile system was a gonner.  But compiled and working as far as I can tell. Thanks for the help hope your not racking your brain looking for something not easially reproducible.

**Comment by t8m** [comment]
Is this still an issue on both 1.1.1 and master branches?

**Comment by orgads** [comment]
With 1.1.1s, the only errors I'm getting are:

```
crypto/dh/dh_rfc7919.c: In function 'dh_param_init':
crypto/dh/dh_rfc7919.c:23: warning: type-punning to incomplete type might break strict-aliasing rules
crypto/x509/x509_vpm.c: In function 'X509_VERIFY_PARAM_set1_ip':
crypto/x509/x509_vpm.c:436: warning: dereferencing type-punned pointer will break strict-aliasing rules
```

The first one is on https://github.com/openssl/openssl/blob/f868abcc5d/crypto/dh/dh_rfc7919.c#L23 and the second one on https://github.com/openssl/openssl/blob/f868abcc5d/crypto/x509/x509_vpm.c#L436

They're not specific to 32 bit, so I guess this issue can be closed.
