### ISSUE TITLE
Question: Unit testing SSL_set_tlsext_host_name in the user code, client side.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [openssl/openssl#7560]
I have a piece of user code that invokes ` SSL_set_tlsext_host_name` on `SSL*`, client side. Is there a way for me to write a unit test that gets the value of the hostname set previously, on the client side? `SSL_get_servername` is for the server side only, isn't it?

**Comment by kaduk** [comment]
As of #10018 `SSL_get_servername()` is documented to fulfil this purpose.
Sorry for the very slow reply on this one.
