### ISSUE TITLE
Build attributes

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#7568]
Build attributes associated with files is something I'd like to generalize.

What are those, you might wonder?  Well....  we actually already have that already in some cases (`_NO_INST` keyword suffix), or lack them in others (keeping track of exactly what programs / scripts are installed where).  One is handled by Configure, the rest is hard coded in the build file templates.

Seeing that it's not terribly important for Configure to know the exact details, and having stuff hard coded in the build file templates is directly bad, we might want to see attributes as a message being passed from the build.info files to the build file templates.

So, I'd like to device some kind of build.info attribute syntax, which is always optional, but can help indicate to the build file templates what the intention is with a produced file.  For example:

```
# indicate that these programs should not be installed
PROGRAMS{noinst}=test/foo
# indicate that these scripts are if the "misc" category
SCRIPT{misc}=tools/c_rehash
```

My intent  is for these attributes to be used primarily for end products, i.e. programs, scripts, libraries, ...  They would simply be bits of information in string form that get passed on to the build file templates, and most of all, Configure doesn't need to know anything about them other than the syntax and where to store them.

**Comment by paulidale** [comment]
_should be installed_ and `PROGRAMS{noinst}=` ?  One negative too many or few.

**Comment by levitte** [comment]
Thank you, corrected

**Comment by robotiko380** [comment]
Would you have some time to answer some of question sometime?
Samuel J.

**Comment by levitte** [comment]
Depends, Samuel J.  Is it related to this issue, then fire away.  If it's something other related to OpenSSL, please create another issue.
