### ISSUE TITLE
How to generate SM2/SM4 algorithms in code form instead of on the command line

### ISSUE THREAD

**Issue by Mingzhe-Zhu** [openssl/openssl#7570]
I'm sorry to bring this problem up.
    Use the API in evp. h? Openssl 1.1.1 just came out, there's not a lot of information on the web. Take a look at the openssl 1.1.1 document, which contains only SM2 signature in code form, but no encrypted/decrypted code form.
    Want to tell me which apis to call? Is there a relevant sample program?

**Comment by mattcaswell** [comment]
How to use SM2 for encryption came up on the openssl-users email list recently. My answer to that question is here:

https://mta.openssl.org/pipermail/openssl-users/2018-October/009105.html

**Comment by Mingzhe-Zhu** [comment]
> How to use SM2 for encryption came up on the openssl-users email list recently. My answer to that question is here:
> 
> https://mta.openssl.org/pipermail/openssl-users/2018-October/009105.html

Thank you very much. You guys are so professional.
