### ISSUE TITLE
compile error in Android NDK

### ISSUE THREAD

**Issue by cucbin** [openssl/openssl#7578]
I want to compile OpenSSL as static Library, but there was some error in compile processing.

the error is below:
..../toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-ld: error: cannot find -lgcc
..../toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-ld: error: cannot find -lgcc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libcrypto.so] Error 1
make: *** [all] Error 2

And I can found it has been created the static library in dir.

the NDK Version I used is r18b. 
the OpenSSL Version is 1.1.1 release.
the issue exists in the arm-linux-androideabi platform.

can you give me some idea for this issue? Thanks!

**Comment by cucbin** [comment]
@mattcaswell ok, the steps that I was referenced to `https://wiki.openssl.org/index.php/Android`

1. Download `setenv-android.sh` file from OpenSSL site
2. Change `ANDROID_NDK_ROOT` in `setenv-android.sh`, I used r18b version.
3. The Configure parameters
./Configure android-armeabi shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=\`pwd\`/output
./Configure android-x86 shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=\`pwd\`/output

Command line:
```
$. ./setenv-android.sh
$./Configure android-armeabi shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=`pwd`/output 
or
$./Configure android-x86 shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=`pwd`/output

$make depend
$make all
```

**Comment by mattcaswell** [comment]
Those steps are out of date and are for older versions of OpenSSL (I just made an edit to that wiki page to make that clearer). For OpenSSL 1.1.1 you should read the INSTALL guide and the NOTES.ANDROID file:

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/INSTALL
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/NOTES.ANDROID

**Comment by cucbin** [comment]
@mattcaswell thanks,
I use the steps that reference from NOTES.ANDROID file, but the issue still exists. I use the command line below:
```
$export ANDROID_NDK= my NDK path
$PATH=${ANDROID_NDK}/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:$PATH
$./Configure android-arm -D__ANDROID_API__=21
$make

```

and it would stop the compile process and print the error info after a while. 
so could you please help me to take a look at it? thanks!

**Comment by mattcaswell** [comment]
I just tried out the r18b NDK release on my linux machine and was able to get openssl to successfully build. However, according to the notes on the NDK download page, gcc support has been removed so I had to adjust my PATH to use clang instead:

````
$ export ANDROID_NDK=/path/to/my/install/of/android-ndk-r18b
$ export PATH=/path/to/my/install/of/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
$ ./Configure android-arm -d__ANDROID_API__=21
$ make
````

**Comment by cucbin** [comment]
@mattcaswell ok, thanks. I get it, I think it's probably that I used MacOS. 
I use the command like your:
```
$ export ANDROID_NDK=/path/to/my/install/of/android-ndk-r18b
$ export PATH=/path/to/my/install/of/android-ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin:$PATH
$ ./Configure android-arm -D__ANDROID_API__=21 no-shared no-hw no-engine --prefix=`pwd`/output --openssldir=`pwd`/output
$ make
```
**and it caught other error and some undefined reference error.** 
.../ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: apps/libapps.a: no archive symbol table (run ranlib)
.../ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ssl: no archive symbol table (run ranlib)
.../ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: crypto: no archive symbol table (run ranlib)


anyway, it can create the static library in the directory.

**Comment by petrovr** [comment]
cucbin wrote:

Dear reporter, I would like to suggest you to test current master or 
1.1.1 branch  - see below.

 > @mattcaswell ok, thanks. I get it, I think it's probably that I used 
MacOS.
 > I use the command like your:
 > ```
 > $ export ANDROID_NDK=/..../android-ndk-r18b
 > $ export PATH=...
 >

gcc is removed from NDK >= r18 .

You could set extra variables ( 
https://github.com/openssl/openssl/pull/7179#issuecomment-431477861 ) to 
ensure "pure" clang build.
Let me know if those variables resolve you issue.

Remark: current build system sets those variables and this will be in 
next release.

Regards,
Roumen Petrov

**Comment by cucbin** [comment]
@petrovr Thanks for your comment, I've pulled the latest commit, and it seems no problem in the build process.

@mattcaswell Thanks for your help in this issue, I think your team will release the code in the next release. so I think we can close this issue. You are really a very good team.

Final, thanks all.
