### ISSUE TITLE
pkcs7_verify fails when we verified Apple certificate signature

### ISSUE THREAD

**Issue by SeolhwaHan** [openssl/openssl#7579]
When we switched to macOS 10.14, xcode 10(from macOS 10.13, xcode 9), 
pkcs7_verify function returns false.

Our test environment is as follows.
Openssl version : 1.0.2p(also 1.1.0i version fails) 
OS : macOS(10.13.3, 10.14) 
Certificate: iPhone Distribution Certificate(I'm sorry I could not upload the certificate file.) 
Commands:
$ openssl asn1parse -inform der -in temp.der(left is old version, right is new version) 
<img width="1278" alt="2018-11-07 2 35 12" src="https://user-images.githubusercontent.com/23625035/48113156-e0420a00-e29c-11e8-83a4-8d5fe5c1c97e.png">

$ openssl smime -verify -inform D -in temp.der -content temp -CAfile root.pem -purpose any -ignore_critical 
<img width="1279" alt="2018-11-07 2 55 18" src="https://user-images.githubusercontent.com/23625035/48113210-2c8d4a00-e29d-11e8-90e0-9fec17eb9f54.png">

Reference : https://openradar.appspot.com/43560180

**Comment by ValZapod** [comment]
Is this still and issue??

**Comment by t8m** [comment]
1.0.2 and 1.1.0 are unsupported versions. Please open a new issue if this is still a problem with 1.1.1 or 3.0 versions.
