### ISSUE TITLE
"FIPS mode not supported" on OpenSSL 1.1.1

### ISSUE THREAD

**Issue by junaruga** [openssl/openssl#7582]
I got an message "FIPS mode not supported", when doing configuration on OpenSSL 1.1.1 with openssl-fips. Building with fips mode has not been supported from OpenSSL 1.1.1?

Related commit hash: https://github.com/openssl/openssl/commit/b53338cbf8822dd774f9e4057307f347d2b63ff0

```
$ ./config fips shared \
>   --prefix=/usr/local/openssl-1.1.1-fips \
>   --with-fipsdir=/usr/local/openssl-fips-2.0.16
Operating system: x86_64-whatever-linux2


Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

FIPS mode not supported
```

```
$ ./Configure \
>   fips \
>   --prefix=/usr/local/openssl-1.1.1-fips \
>   --with-fipsdir=/usr/local/openssl-fips-2.0.16

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

FIPS mode not supported
```

**Comment by richsalz** [comment]
Correct, the current FIPS module only works with 1.0.2

The project is starting work on a new FIPS module which will be included in the next release.

**Comment by junaruga** [comment]
@richsalz  Sure, thanks for the info.
I wish this ticket will be kept without closing until "a new FIPS module which will be included in the next release".

**Comment by StephenWall** [comment]
Where is this work taking place?  It would be nice to see the progress in a branch on github.

**Comment by mattcaswell** [comment]
There's no code yet - a lot of design work has been going on. We expect to publish that very soon.

**Comment by quanah** [comment]
I have a customer who claims to have a FIPS 140-2 module (from some private company?) that works with the OpenSSL 1.1.1 series.  This requires patching OpenSSL 1.1.1 to re-enable FIPS mode.  Is this not a valid reason for OpenSSL 1.1.1 to allow FIPS mode?

**Comment by levitte** [comment]
We have no knowledge of that FIPS module and how it works, so that's kinda hard...

**Comment by mspncp** [comment]
Some linux distributions do their own FIPS validations which encompass OpenSSL among others. RHEL has one, and Ubuntu did one recently. AFAIK, they are based on 1.1.1, but I'm not sure.

**Comment by mspncp** [comment]
(A quick search yields that Ubuntu's validation might to be based on 1.0.2)

**Comment by levitte** [comment]
If that is the case, then they've made an incompatible mod. And sure, they're free to do so...

**Comment by t-j-h** [comment]
@quanah you should ask which certificate number matches the validation being used as that will provide details at least of what is being claimed.

**Comment by quanah** [comment]
> 
> 
> @quanah you should ask which certificate number matches the validation being used as that will provide details at least of what is being claimed.

All I need on my end of things is to be able to enable FIPS mode, so they can drop their module in. It's not on me to ensure that their module even works, that's between them and their supplier.  But since you can't enable FIPS mode in 1.1.1, that's somewhat problematic.

**Comment by t-j-h** [comment]
It's not that simple. The code to support redirection for FIPS usage was removed. It isn't just a mode change - it is hundreds of hooks to redirect and rename symbols. I doubt that anyone has actually ported those back into the code base for 1.1 at all.

**Comment by quanah** [comment]
Thanks @t-j-h ! I've been rather skeptical of this entire bit they want to do from the get-go.

**Comment by user100003** [comment]
@richsalz and others: Any updates on the FIPS roadmap? Several factors prompting that

1. AES GCM in FIPS mode has a bug ([issue](https://github.com/openssl/openssl/issues/5379)). We noticed it also fails [GCM spec](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.694.695&rep=rep1&type=pdf) test 5, 11 and 17. 
2. The OpenSSL [FIPS page](https://www.openssl.org/docs/fips.html ) doesn't educate readers on whats ahead
3. FIPS 140-3 kicking in in 2019 alongside 140-2

FIPS validation is a huge pain point and pointlessly expensive for modern software development, so what the OpenSSL foundation does is fantastic - much appreciated!

PS: It's probably worth creating a master ticket on the next FIPS release tracking all things 'next-release FIPS'?

**Comment by richsalz** [comment]
I don't speak for the project.  If you have specific questions about the state of things, consider asking on the openssl-users mailing list (see https://mta.openssl.org to join). 

I believe your no. 1 will not be a factor as the code will be the standard AES code from the mainline. I believe your no. 3 is not relevant since 140-2 is still available and applicable.

Might I humbly suggest that if you've gotten value from the FIPS work, your company make a donation to the project.

**Comment by mattcaswell** [comment]
The last blog post was from earlier this year describing some of the current activity and how the new OpenSSL 3.0 will work with FIPS:

https://www.openssl.org/blog/blog/2019/02/13/FIPS-update/

The current timeline aims for us to be code complete by the end of the year with a possible release in early Q2 2020 (although we may not be validated at the point of release).

**Comment by onajafi** [comment]
I found this in the [blog post](https://www.openssl.org/blog/blog/2019/02/13/FIPS-update/) about OpenSSL 3.0 :

> The new design incorporates the FIPS module into main line OpenSSL. It will no longer be a separate download and support periods will also be aligned. It will of course be possible to build OpenSSL with or without the FIPS module depending on your own individual circumstances and requirements.

Does this mean that there will be no separate FIPS module to use with OpenSSL 1.1.1 ?

**Comment by mattcaswell** [comment]
> Does this mean that there will be no separate FIPS module to use with OpenSSL 1.1.1 ?

Correct. The new FIPS module will be for OpenSSL 3.0.

**Comment by t8m** [comment]
I am going to close it. Although it might trigger opening further similar issues as people often do not search closed issues when reporting a new issue.

**Comment by mspncp** [comment]
> people often do not search closed issues when reporting a new issue.

FWIW: as a countermeasure, GitHub has a new beta feature which displays matching issues automatically when you enter your new issue.

**Comment by tbswork1** [comment]
> You can close your own issues, too :)
> 
> The next release of OpenSSL is 3.0 and will include the FIPS module. All of this work is being done in the open on GitHub in the "master" branch. There will _not_ be a FIPS module for the 1.1.1 release.

What is this link for:

https://beta.openssl.org/docs/fips/UserGuide-1.1.1.pdf

**Comment by paulidale** [comment]
That's one of the guides for the 1.0.2 FIPS validations.  Version numbering of the FOM got into the two point something -- the reason we jumped to 3.0 for the last major release.
