### ISSUE TITLE
Openssl version 1.0.2p can not create ecdsa group

### ISSUE THREAD

**Issue by wwjd228** [openssl/openssl#7592]
Hi, 
I encounter an issue that "Failed to create new EC Group" with curve id NID_brainpoolP512t1.
I used function
"EC_GROUP_new_by_curve_name(NID_brainpoolP512t1)"
And it always return NULL value.

**Comment by mattcaswell** [comment]
Hmm. I just tried this out and it works fine for me. Where did you get your version of OpenSSL from? If you built it yourself from source what config options did you use?

**Comment by wwjd228** [comment]
I download the source from
https://www.openssl.org/source/
./config --prefix="PATH"
then
make && make install

**Comment by mattcaswell** [comment]
That's odd. Here is the minimal test that I used. Does this work for you?

````
#include <openssl/ec.h>
#include <openssl/objects.h>

int main(void)
{
    EC_GROUP *group;

    group = EC_GROUP_new_by_curve_name(NID_brainpoolP512t1);

    if (group == NULL)
        printf("Group was NULL\n");
    else
        printf("Group was not NULL\n");

    EC_GROUP_free(group);

    return 0;
}
````

**Comment by wwjd228** [comment]
@mattcaswell I compile with 
"gcc ec_group.c -lssl -lcrypto"
it also got "Group was NULL"

My environment:
Ubuntu 14.04 LTS

**Comment by mattcaswell** [comment]
What does `ldd` give you for the above minimal test executable file? e.g. if your executable is called `ec_group`, please give the output of `ldd ec_group`

**Comment by wwjd228** [comment]
@mattcaswell the following is my output:
$ ldd ec_group
        linux-vdso.so.1 =>  (0x00007fff7b5cf000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f9095b81000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f90957b8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f90955b4000)
        /lib64/ld-linux-x86-64.so.2 (0x00005604e3a7e000)

**Comment by mattcaswell** [comment]
This looks like you are picking up the system version of libcrypto rather than your version. Where did you install libcrypto to? You might need to set the `LD_LIBRARY_PATH` environment variable prior to executing your code to point to the correct location.

**Comment by wwjd228** [comment]
@mattcaswell Yes, your right! the issue is solved! thanks.

**Comment by mattcaswell** [comment]
Great! Closing this issue.
