### ISSUE TITLE
Travis: changing dist trusty to xenial

### ISSUE THREAD

**Issue by junaruga** [openssl/openssl#7612]
Ubuntu Xenial 16.04 is available on Travis CI now.

```
dist: xenial
```

https://blog.travis-ci.com/2018-11-08-xenial-release

https://docs.travis-ci.com/user/reference/xenial/
> Compilers and Build toolchain
>    clang and llvm 7
>    cmake 3.12.4
>    gcc 5.4.0
>    ccache 3.2.4
>    shellcheck 0.5.0
>    shfmt 2.4.0

Shall we use it?

**Comment by junaruga** [comment]
Info: `xenial` is much more heavy than `trusty` right now, because maybe many people are trying it :-)

**Comment by Croydon** [comment]
This happened here: https://github.com/openssl/openssl/commit/16161a30f2d432dc851a67d0ba24c0fa738e0767

**Comment by junaruga** [comment]
Sure. I would close this ticket. Thanks for reporting.
