### ISSUE TITLE
Advanced BLAKE2 parameters support advice

### ISSUE THREAD

**Issue by evqna** [openssl/openssl#7636]
In #980 it was requested that the blake2 interface was made more flexible to allow users to provide custom parameters such as digest length, hash key, salt and personalization. At the time it looked like a large effort was required to work around the limitations of the EVP_MD API but with the recent work by @levitte on the EVP_MAC API in #7393 this seems worth revisiting.

There is some backend implementation work required to support the key and digest length parameters but most of the issues seem to revolve around exposing these parameters through the EVP interface 
 and passing them around.

I would be happy to work on this, but since I don't have much experience designing APIs or working on EVP I need some guidance:

The value of blake2 parameters is stored in a BLAKE2_PARAM struct that is part of the actual algorithm (the block is hashed with the IV to initialize the hashing state). Currently the structure is internal to the blake2 init method so there is no way to write setter functions.
All blake2 methods already receive a BLAKE2_CTX parameter, is it acceptable to store custom parameters there or should modifying this structure be avoided? Are there existing EVP apis to access it? (it is stored as _md_data_ in EVP_MD_CTX).

Since using blake2 as a keyed hash makes it essentially equivalent to a MAC, would it make more sense to expose this parameter as part of the EVP_MAC api? Is this what users expect or does it make the api more unintuitive? How then would we allow users to modify the key and other digest parameters at the same time?
#7597 uses EVP_MAC_ctrl() to control all instance specific parameters for KMACs, is this a preferred method?

Other non-tree parameters seem easier to handle:
- Supporting the *salt* and *personalization* parameters only requires setting a fixed size byte field in the param block.
- The *digest_length* parameter must be set in the param block and somehow passed to the blake2_final method. The EVP_MD returned by EVP_blake2() already hardcodes the digest length, would that be an issue?

**Comment by paulidale** [comment]
I can answer some of the questions.  The _ctrl() functions are the preferred method for algorithm specific parameters.  Storing parameters in the BLAKE2_CTX seems like the way to go.  I'd cache the various settings in the _CTX and let the _init_ call set everything up -- i.e. between the _new_ and the _init_, the parameters get set.

I'm not sure if this should move to the EVP_MAC, blake2 is generally considered to be a digest even though it can act as a MAC.

**Comment by paulidale** [comment]
I'm fine with _both_ MD and MAC implementations for this.

**Comment by t8m** [comment]
Is there still anything missing or can this be closed?

**Comment by nhorman** [comment]
referenced PR's complete, closing
