### ISSUE TITLE
openssl-1.1.1, error when executing "make"

### ISSUE THREAD

**Issue by pointevent** [openssl/openssl#7649]
Hi,
I download openssl-1.1.1.tar.gz and use cygwin make it,but the command line show this error.

crypto/comp/c_zlib.c:35:11: fatal error: zlib.h: No such file or directory        # include
--

crypto/comp/c_zlib.c:35:11: fatal error: zlib.h: No such file or directory        # include                                                                          ^~~~~~~~                                                              compilation terminated.                                                          make[1]: *** [Makefile:2221: crypto/comp/c_zlib.o] Error 1
--

**Comment by levitte** [comment]
Configure *without* `zlib` or `zlib-dynamic`

OR

Install the cygwin package `libzip-devel`
