### ISSUE TITLE
Removal of references to s3_clnt.c and s3_srvr.c

### ISSUE THREAD

**Issue by nick599** [openssl/openssl#765]
Following https://github.com/openssl/openssl/issues/70, the files: s3_clnt.c and s3_srvr.c appear in:
1) Netware/globals.txt 
2) ssl/ssl_sess.c 
3) ssl/statem/statem_clnt.c

s3_clnt.c and s3_srvr.c no longer exist.
Requesting pull request that removes those references in the three stated files.

**Comment by nick599** [comment]
Requesting pull request that removes those references in stated files.

**Comment by nick599** [comment]
s3_clnt.c and s3_srvr.c no longer exist.

**Comment by mattcaswell** [comment]
Fixed by commit d4d78943798.
