### ISSUE TITLE
Zero out actx->tls_aad

### ISSUE THREAD

**Issue by ManSoSec** [openssl/openssl#7652]
During key initialization, we found out doing a zero out (`memset(actx->tls_aad, 0, POLY1305_BLOCK_SIZE);`) might be missed here:
https://github.com/openssl/openssl/blob/master/crypto/evp/e_chacha20_poly1305.c#L172

``` C
    actx->len.aad = 0;
    actx->len.text = 0;
    actx->aad = 0;
    actx->mac_inited = 0;
    actx->tls_payload_length = NO_TLS_PAYLOAD_LENGTH;
```
As it has done here:
https://github.com/openssl/openssl/blob/master/crypto/evp/e_chacha20_poly1305.c#L512

``` C
        actx->len.aad = 0;
        actx->len.text = 0;
        actx->aad = 0;
        actx->mac_inited = 0;
        actx->tag_len = 0;
        actx->nonce_len = 12;
        actx->tls_payload_length = NO_TLS_PAYLOAD_LENGTH;
        memset(actx->tls_aad, 0, POLY1305_BLOCK_SIZE);
```

I can provide a pull request if this is an issue.

**Comment by t8m** [comment]
This is not a real problem. Besides, in current master this is a legacy implementation, the provider one is different.
