### ISSUE TITLE
unrecognized command line option '-m64'

### ISSUE THREAD

**Issue by tushargajjar** [openssl/openssl#7655]
I compiled the openssl in the UBUNTU16.04，and i am getting following error:

tushar@LT0050:~/sdk-new/third-party/openssl$ make
make depend && make _all
make[1]: Entering directory '/home/tushar/sdk-new/third-party/openssl'
make[1]: Leaving directory '/home/tushar/sdk-new/third-party/openssl'
make[1]: Entering directory '/home/tushar/sdk-new/third-party/openssl'
aarch64-linux-gnu-gcc-5  -Icrypto -I. -Icrypto/include -Iinclude  -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/tushar/sdk-new/third-party/openssl-master/build/ssl\"" -DENGINESDIR="\"/home/tushar/sdk-new/third-party/openssl-master/build//lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/libcrypto-lib-cversion.d.tmp -MT crypto/libcrypto-lib-cversion.o -c -o crypto/libcrypto-lib-cversion.o crypto/cversion.c
aarch64-linux-gnu-gcc-5: error: unrecognized command line option '-m64'
Makefile:9268: recipe for target 'crypto/libcrypto-lib-cversion.o' failed
make[1]: *** [crypto/libcrypto-lib-cversion.o] Error 1
make[1]: Leaving directory '/home/tushar/sdk-new/third-party/openssl'
Makefile:171: recipe for target 'all' failed
make: *** [all] Error 2

More message:
build machine： UBUNTU16.04 x86_64;
target：APQ8053L arm board

command: ./Configure --prefix=/home/tushar/sdk-new/third-party/openssl-master/build/--openssldir=/home/tushar/sdk-new/third-party/openssl-master/build/ssl CC=aarch64-linux-gnu-gcc-5

can anyone assist how i can go around this error?

**Comment by jamuir** [comment]
I think you need to pass an appropriate "os/compiler" argument to `./Configure`.

Try `./Configure linux-aarch64`

There is good info here:

https://wiki.openssl.org/index.php/Compilation_and_Installation

**Comment by jamuir** [comment]
@mattcaswell:  looks like this can be closed.  Could you please click the button?

**Comment by mattcaswell** [comment]
Thanks @jamuir. Closing.

**Comment by zhanglm666** [comment]
./Configure linux-aarch64 no-asm no-async --prefix=$PWD/../install_openssl
