### ISSUE TITLE
Missing OPENSSL_clear_free(ec->key, ec->keylen)

### ISSUE THREAD

**Issue by ManSoSec** [openssl/openssl#7657]
Calling `OPENSSL_clear_free(ec->key, ec->keylen)` seems to be a common pattern before assigning value to CMS_EncryptedContentInfo ->key field:

https://github.com/openssl/openssl/blob/master/crypto/cms/cms_enc.c#L120
https://github.com/openssl/openssl/blob/master/crypto/cms/cms_env.c#L411
https://github.com/openssl/openssl/blob/master/crypto/cms/cms_kari.c#L246
``` C
OPENSSL_clear_free(ec->key, ec->keylen);
ec->key = cek;
ec->keylen = ceklen;
```

But it is missed here:
https://github.com/openssl/openssl/blob/master/crypto/cms/cms_pwri.c#L376
``` C
ec->key = key;
ec->keylen = keylen;
```

I can provide a pull request if this is an issue.

**Comment by kaduk** [comment]
I would go ahead and make the pull request.
I did not do a thorough review, but it seems more likely than not to be a bug.
