### ISSUE TITLE
The key is too small but return 1 when set tmp dh 

### ISSUE THREAD

**Issue by zf2534** [openssl/openssl#7677]

**Comment by zf2534** [comment]
if (!ssl_ctx_security(ctx, SSL_SECOP_TMP_DH,
                                  EVP_PKEY_security_bits(pkdh), 0, pkdh)) {
                SSLerr(SSL_F_SSL3_CTX_CTRL, SSL_R_DH_KEY_TOO_SMALL);
                EVP_PKEY_free(pkdh);
                return 1;
            }

**Comment by InfoHunter** [comment]
What version of OpenSSL are you using? The latest code returns 0 instead of 1

**Comment by InfoHunter** [comment]
Ahh, I found 1.0.2 and 1.1.0 return the wrong value

**Comment by InfoHunter** [comment]
Errr, sorry, this piece of logic has not been added in 1.0.2, so only 1.1.0 is affected

**Comment by zf2534** [comment]
I used the openssl 1.1.1 version

**Comment by zf2534** [comment]
> What version of OpenSSL are you using? The latest code returns 0 instead of 1

I am using the openssl 1.1.1

**Comment by mattcaswell** [comment]
Looks like this was fixed in master via commit d9720a59, but the fix has not been backported to 1.1.1

**Comment by InfoHunter** [comment]
This issue is fixed to 1.1.1 branch via #7678 (3ccccb9), thank you @zf2534 for reporting!
