### ISSUE TITLE
openssl-1.1.0j: parallel install broken

### ISSUE THREAD

**Issue by Polynomial-C** [openssl/openssl#7679]
commit 2801f671288d592b29a38c6098f53e6f3221d27a broke parallel install target:

```
mv: cannot stat 'Makefile.new': No such file or directory
make[1]: *** [Makefile:214: depend] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/openssl-1.1.0j/work/openssl-1.1.0j-abi_x86_64.amd64'
make: *** [Makefile:138: build_programs] Error 2
make: *** Waiting for unfinished jobs....
```
and later on
```
mv: cannot stat 'Makefile.new': No such file or directory
make[1]: *** [Makefile:214: depend] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/openssl-1.1.0j/work/openssl-1.1.0j-abi_x86_64.amd64'
make: *** [Makefile:132: build_libs] Error 2
```
This is caused by calls to `build_programs` and `build_libs` targets which both call `dependmagic` which then calls `make depend` and that fails.

See downstream bug report: https://bugs.gentoo.org/671602

**Comment by levitte** [comment]
"broke parallel install" is a bit strong, I might remark, as the install target wasn't previously designed for parallelism.  It was pure luck it worked, errr, most of the time.

I'll look into it, but it may be that we're reaching the limits of what magic we can get out of make (remember that we need to avoid implementation specific features)

**Comment by Polynomial-C** [comment]
Well, from my POV as distro package maintainer this is a regression as parallel install used to work for quite a while already (at least we didn't get any bug reports before openssl-1.1.0j and my test machines also didn't catch any prallel install issues before).

**Comment by sebastianas** [comment]
I remember I had 70a56b914772e6b21cda2a5742817ae4bb7290f1 to get it work once then it broke again and got fixed by someone from the dev team. Odd but I can find the PR.

**Comment by JL2210** [comment]
I have the exact same issue. Thank you for filing this.

**Comment by levitte** [comment]
Note that  2801f67 was done to fix occasional install problems, see #7466.

However, I may have found a way to ensure that the depend target isn't done in a sub-make, is that enough not to trip things for you?

```
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index 11fecc259b..50362d3812 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -77,8 +77,14 @@
      # to. You're welcome.
      sub dependmagic {
          my $target = shift;
-
-         return "$target: build_generated\n\t\$(MAKE) depend && \$(MAKE) _$target\n_$target";
+         my $magic = <<"_____";
+$target: build_generated depend
+       \$(MAKE) _$target
+_$target
+_____
+         # Remove line ending
+         $magic =~ s|\R$||;
+         return $magic;
      }
      '';
 -}
```

**Comment by Polynomial-C** [comment]
With that patch the build fails much earlier:

```
make depend 
Makefile:129: *** missing separator.  Stop.
```

**Comment by JL2210** [comment]
@Polynomial-C That's because the tabs didn't paste properly in Github. Remove all the instances of 8 spaces with tabs in the patch that he sent.

**Comment by JL2210** [comment]
Yay! This issue has been fixed on Gentoo!

**Comment by luke-jr** [comment]
1.0.2t actually installs a *corrupt* libcrypto.so.1.0.0 that breaks most of my system. :(

**Comment by Polynomial-C** [comment]
Gentoo still carries this patch with openssl-1.1.1 series. Any chance the fix from @levitte can finally be pushed into the repo?

**Comment by kaduk** [comment]
It is more likely to be looked at if it is made into a pull request.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing.
