### ISSUE TITLE
SSL_accept fails with SSL_ERROR_SYSCALL and Unknown Protocol

### ISSUE THREAD

**Issue by RohanKurane** [openssl/openssl#7682]
I am running into an issue with SSL_accept() in my server code.  I am using openssl 1.0.2g

Here is my server code - 
                open socket , bind to socket, listen on socket
                initialize SSL context and libraries. Load certificate and Private key files
                {
                    SSL_load_error_strings();
                    ERR_load_BIO_strings();
                    SSL_library_init();
                    OpenSSL_add_all_algorithms();
                    const SSL_METHOD *method;
                    method = SSLv23_server_method();
                    ctx = SSL_CTX_new(method);
                    if (SSL_CTX_use_certificate_file(ctx, ccrt, SSL_FILETYPE_PEM) <= 0) {
                       ERR_print_errors_fp(stdout);
                     }
                     if (SSL_CTX_use_PrivateKey_file(ctx, ckey, SSL_FILETYPE_PEM) <= 0 ) {
                        ERR_print_errors_fp(stdout);
                     }
                }
                pselect() waits on any incoming connections or any reads on existing connections
                if new connection - accept()  the connection and add to the pselect FD_SET and return
               if existing connection, there is something to read so do the following  {
                SSL *ssl;
                if ( !ctx )
                {
                      return 0;                
               }
                ssl = SSL_new(ctx);
                SSL_set_fd(ssl, soc);
                int ret = SSL_accept(ssl);   --> **FAILS**
                if (ret <= 0) {
                    ERR_print_errors_fp(stdout);
                     return 0}
             }

When the error queue is printed it shows - 
error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:640:
@davidben  - I saw you reply to a few other issues. Dont mind me tagging you here

**Comment by RohanKurane** [comment]
I changed

method = SSLv23_server_method(); to 
method = TLSv1_2_server_method();

Now SSL_accept() gives me back a wrong version number error.

error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:386:

When I listed the SSL and TLS versions in use on my system -

openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1.2

What am I missing here ?

**Comment by mattcaswell** [comment]
You don't say what version of OpenSSL you are using. I'm assuming 1.0.2 based on some of the things you've said.

> method = SSLv23_server_method(); to
> method = TLSv1_2_server_method();

Don't do that. `SSLv23_server_method()` is the correct one to use. This gives you a version flexible method which will choose the most appropriate protocol version. `TLSv1_2_server_method()` will *only* ever negotiate TLSv1.2 - which is a problem if the client doesn't support it.

> error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:640:

This error can occur if you have disabled SSLv3 and TLSv1 using the `SSL_OP_NO_SSLv3` and `SSL_OP_NO_TLSv1` options, and then the client attempts to connect using SSLv3 or TLSv1. Have you done that in your code somewhere? I couldn't see it in the sample code you pasted.

If not then a wireshark trace of the communication between the client and the server might be helpful.

**Comment by RohanKurane** [comment]
Thenks @mattcaswell 
I will take a look.  And yes, my OpenSSL is 1.0.2g
I do not disable them SSLv3 and TLSv1 explicityly using SSL_OP_NO_SSLv3 in the code that I know of. But I will take a look. 

After some code modifications and resetting to SSLv23_server_method() and SSLv23_client_method(), my code does the following - 

```open socket , bind to socket, listen on socket for incoming new connections or reads on existing fd's
initialize SSL context and libraries. Load certificate and Private key files
{
SSL_load_error_strings();
ERR_load_BIO_strings();
SSL_library_init();
OpenSSL_add_all_algorithms();
const SSL_METHOD *method;
method = SSLv23_server_method();
ctx = SSL_CTX_new(method);
if (SSL_CTX_use_certificate_file(ctx, ccrt, SSL_FILETYPE_PEM) <= 0) {
ERR_print_errors_fp(stdout);
}
if (SSL_CTX_use_PrivateKey_file(ctx, ckey, SSL_FILETYPE_PEM) <= 0 ) {
ERR_print_errors_fp(stdout);
}
}

pselect() waits on any incoming connections or any reads on existing connections
if new connection - accept() the connection and add to the pselect FD_SET and do the following {
  Open an outgoing to connection to the host
  socket and connect to the fd
            fp = stdout;
            SSL_load_error_strings();   /* Bring in and register error messages */
            SSL_library_init();
            OpenSSL_add_all_algorithms();  /* Load cryptos, et.al. */
            ERR_clear_error();
            method = SSLv23_client_method();
            cctx = SSL_CTX_new(method);   /* Create new context */
            if ( cctx == NULL )
            {
                ERR_print_errors_fp(stdout);
            }
            ERR_clear_error();
            cssl = SSL_new(cctx);      /* create new SSL connection state */
            SSL_set_fd(cssl, fd);    /* attach the socket descriptor */

            ERR_clear_error();
            int rconnect = SSL_connect(cssl);   /* perform the connection */
            if ( rconnect != 1 )                /* perform the connection */
            {
                ERR_print_errors_fp(stdout);
            }
            r = SSL_write(cssl, buffer, len); 
}

On the other hand if existing connection, there is something to read so do the following {
SSL *ssl;
if ( !ctx )
{
return 0;
}
ssl = SSL_new(ctx);
SSL_set_fd(ssl, soc);
int ret = SSL_accept(ssl);
if (ret <= 0) {
ERR_print_errors_fp(stdout);
return 0
 }
 }
```

I am now getting these errors on the SSL_connect() and SSL_accept() calls. 

```140421481408040:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
140421481408040:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:640:
140421481408040:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
140421481408040:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:640:
140421481543208:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
140421481408040:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
140421481408040:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:640:
140421481408040:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:s3_pkt.c:1487:SSL alert number 70
```
Subsequently the SSL_write() and SSL_read() calls fail as well. 
```SSL_write() returned error:00000002:lib(0):func(0):system lib
SSL_read returned error:00000001:lib(0):func(0):reason(1)```

Could these failures be because of what you said ?

**Comment by RohanKurane** [comment]
@mattcaswell 
In /usr/include/openssl/ssl.h I do see these defines
```
# define SSL_OP_NO_SSLv2                                 0x01000000L
# define SSL_OP_NO_SSLv3                                 0x02000000L
# define SSL_OP_NO_TLSv1                                 0x04000000L
# define SSL_OP_NO_TLSv1_2                               0x08000000L
# define SSL_OP_NO_TLSv1_1                               0x10000000L
```

Do you suggest commenting out the following line ?
```# define SSL_OP_NO_SSLv3                                 0x02000000L```

**Comment by RohanKurane** [comment]
I did make sure the md5sum for both the cert and key used are the same. 
I do see this when I try to verify the cert
```
openssl verify cert.pem 
cert.pem: C = US, ST = Califrnia, L = Oak, O = DE, OU = Backend, CN = Root CA
error 18 at 0 depth lookup:self signed certificate
OK
```

Is that OKAY ?

Here is how I generate the cert and key files - 
openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem

**Comment by RohanKurane** [comment]
I also want to point out that my client and server are on the same machine at this point where I get the errors. 
But after I pass this, they could be on different hosts.

**Comment by mattcaswell** [comment]
Please email me a wireshark trace of the communication (matt@openssl.org)

**Comment by RohanKurane** [comment]
@mattcaswell  - Just emailed you the tcpdump trace.  Let me know what you find or if you need anything else. I appreciate your help very much.

**Comment by RohanKurane** [comment]
Here is a qs I have if you can help answer - 
When the client calls ```connect()``` and successfully connects to the server host, should I issue the ```SSL_connect()``` right after it to Initiate the handshake ? The client will then tries to write some bytes to the socket using ```SSL_write```.

On the other hand, the server uses ```pselect()``` to monitor if any read fds are ready for read and issues the ```accept()``` call successfully for the incoming connection. Should I issue the ```SSL_accept()``` call right after the ```accept()``` returns to complete the handshake ?

I have noticed that the ```SSL_connect()``` returns ```SSL_ERROR_WANT_READ``` (this is when the SSL_connect() is issued after a select() call to monitor the write fd set and returns and as per the Openssl documentation).

What is the right procedure here on issuing the calls and in what order ?

**Comment by RohanKurane** [comment]
Hi @mattcaswell  - Sorry for the delay on this. I am working on some code changes. 
In the meantime I do have a question - 
The issue I have is the client and server can go thru the same code to do reads and writes. So I need to know if its the client or server doing the SSL_read() and SSL_write() because it needs the right SSL structure to be passed in. 
Is there a way to test and get a SSL structure from a file descriptor ? So after we do SSL_set_fd(ssl, fd), is there a way to retrieve ssl from a known fd ? That ssl was used in SSL_accept() and SSL_connect() so it has to be the same for SSL_write() and SSL_read().  
I noticed there is a SSL_get_fd() function that would return the fd for a ssl context. Is there a reverse of that function i.e return ssl structure for a passed in fd ?

**Comment by mattcaswell** [comment]
No, that is not possible.
