### ISSUE TITLE
msys2 openssl 1.1 issue on X509: problems on macro DEFINE_STACK_OF?

### ISSUE THREAD

**Issue by saverio-mori** [openssl/openssl#7686]

**Comment by saverio-mori** [comment]
Unfortunately no, i have only headers and libs. I suppose 1.1.x from some filenames, while headers contains 2018 as copyright

**Comment by levitte** [comment]
The header file `openssl.h` has the version number

**Comment by mattcaswell** [comment]
> The header file openssl.h has the version number

I think you meant `opensslv.h`

**Comment by levitte** [comment]
Yes, correct. Sorry for the confusion

**Comment by saverio-mori** [comment]
I have not openssl.h. The header folder for openssl include other 105 files

**Comment by saverio-mori** [comment]
Ok, i see. I have missed that. Version is "OpenSSL 1.1.1a  20 Nov 2018"

**Comment by mattcaswell** [comment]
Looking at net-snmp it seems to use the mingw compiler rather than the msys2 compiler, i.e. it is targeting native windows not msys2. I suspect you're going to have problems if you are using the openssl version that comes with msys2 because that is specifically built for the msys2 environment - not for native windows. I suggest you contact the net-snmp project for support on how to properly build it using OpenSSL on windows.

**Comment by saverio-mori** [comment]
Thanks. Actually i have used the mingw64 environment of msys to build net-snmp, and for a while building run. The net-snmp team maintain a readme for windows (http://www.net-snmp.org/docs/README.win32.html) but it is obsolete. In this readme they suggest to download openssl from http://www.slproweb.com/products/Win32OpenSSL.html, install and then copy to the mingw tree the include folder and the libeay32.* files, where * is a or def. But these files no longer exist in latest openssl; moreover slproweb team no longer support mingw. On the other hand msys mingw already include openssl, so i find strange to modify these files....

**Comment by mattcaswell** [comment]
> On the other hand msys mingw already include openssl, so i find strange to modify these files....

I'm not really an msys guy, but I think the msys openssl files are for building and supporting msys executables - not normal native windows executables. If my understanding is correct the net-snmp build you are attempting will create native windows binaries. Therefore you cannot mix these two. If the net-snmp README is obsolete then you need to ask the net-snmp team for updated instructions.

**Comment by mattcaswell** [comment]
> If you are trying to build in a bare msys2 environment, you're out of luck. We don't even have a config target for it, and the config script will tell you that it's not supported.

Nonetheless there *is* a version of OpenSSL availble for the msys2 environment available via pacman. I have a copy of it in my msys2 environment (1.1.1a).

**Comment by levitte** [comment]
Yes, absolutely.  It's easy to figure out what the libraries are called, too:

```
Richard@DESKTOP-651QCCU MSYS ~/work/_openssl-64-msys
$ ldd /usr/bin/openssl.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffd2b050000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffd29920000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffd27440000)
        msys-crypto-1.0.0.dll => /usr/bin/msys-crypto-1.0.0.dll (0x561730000)
        msys-ssl-1.0.0.dll => /usr/bin/msys-ssl-1.0.0.dll (0x4ba5c0000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
        msys-z.dll => /usr/bin/msys-z.dll (0x522fe0000)
        ??? => ??? (0xeb0000)

Richard@DESKTOP-651QCCU MSYS ~/work/_openssl-64-msys
$ uname -a
MSYS_NT-10.0 DESKTOP-651QCCU 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys
```

This is the result of their hacking, though...  you can have a look for yourself and see what they did to be able to build by [looking in their source repo](https://github.com/Alexpux/MSYS2-packages/tree/master/openssl)...  this includes adding configurations for msys.

(maybe we should add our own msys configs based on what can be figured from there, but that's a separate issue, isn't it?  Not to say pretty specialised...)

**Comment by saverio-mori** [comment]
I have worked with the mingw64 setup, i have executed the specific launcher of MSYS (the environment includes 3 launcher, msys, mingw32 and mingw64) and the command prompt was labelled as mingw64; moreover the building was quite fine until openssl. Also mingw64 package has its own openssl library: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-openssl, updated two days ago to openssl 1.1.1.a. I have adviced Alexpux of this issue.

**Comment by levitte** [comment]
Could you please tell us how you configured OpenSSL?

**Comment by saverio-mori** [comment]
Default installation settings, while for build net-snmp  i have used something as 
`./configure --prefix="$BASEDIR" \
  --with-mibdirs="$BASEDIR/share/snmp/mibs" \
  --with-mib-modules="agentx disman/event-mib winExtDLL "\
  --disable-embedded-perl --without-perl-modules --enable-ipv6 `

**Comment by levitte** [comment]
Right now, this looks like a net-snmp issue to me, or possibly a msys2 / mingw environment mixup.  Just to check that we haven't done something really dumb, I tried compiling this on my msys2 instance, with `openssl-devel` 1.0.2.p-2 installed, as well as my mingw64 instance, with `mingw64-w64-x86_64-openssl`1.1.1.a-1 installed.  It compiled without any issue.

``` C
#include <openssl/dh.h>
int main() {
}
```

I have no idea what's going on in your environment.  Like @mattcaswell implied, it looks like there's a mixup somewhere...  but most of all, this is clearly a `net-snmp` build issue, and you should probably talk with the people of that project first.

**Comment by saverio-mori** [comment]
Yes, i agree. It suppose it is a problem of mingw, these errors seems to me "internal"; i will do a try. Anyway i will contact net-snmp team too. Thank to you all for yours advices!

**Comment by totszwai** [comment]
Hello, is there a patch I could use for this? I am also stuck on this, trying to use MSYS2 MINGW64 to build openssl 1.1.1o.
