### ISSUE TITLE
Move from  DTLS 1.0 to DTLS 1.2

### ISSUE THREAD

**Issue by getsoubl** [openssl/openssl#7695]
Hello,
We are using  openssl is 1.0.2 and try to port the old DTLS 1.0 to DTLS 1.2

Is the DTLSv1_handle_timeout supported in DTLS 1.2?
If not, how we check that the timer expire in allgin with **4.2.4.  Timeout and Retransmission section** of the RFC 6347 (https://tools.ietf.org/html/rfc6347#section-4.2.4)

Best regards
George

**Comment by mattcaswell** [comment]
Yes, it still works. The name is unfortunate but it still applies to DTLSv1.2.
