### ISSUE TITLE
Missing include/openssl/comp.h

### ISSUE THREAD

**Issue by dilyanpalauzov** [openssl/openssl#7702]
I call `./Configure threads no-comp shared -DPURIFY --prefix=/usr/local --openssldir=/etc/openssl linux-x86_64 && make` which fails with
```
make[2]: Entering directory '/src/openssl-1.0.2q/crypto/err'
make[2]: *** No rule to make target '../../include/openssl/comp.h', needed by 'err_all.o'.  Stop.
make[2]: Leaving directory '/src/openssl-1.0.2q/crypto/err'
make[1]: *** [Makefile:90: subdirs] Error 1
make[1]: Leaving directory '/src/openssl-1.0.2q/crypto'
```
I have crypto/comp/comp.h, but no include/openssl/comp.h .  Shouldn’t crypto/err/err_all.c use include crypto/comp/comp.h instead of include openssl/comp.h or a link crypto/comp/comp.h ü→ include/openssl/comp.h be created?

**Comment by mspncp** [comment]
I believe you just forgot to do `make depend` after configuring. See the end of the configure output:

```
...
Configured for linux-x86_64.

*** Because of configuration changes, you MUST do the following before
*** building:

        make depend
```

**Comment by mspncp** [comment]
Note: the symbolic link from `include/openssl/comp.h`  to `crypto/comp/comp.h` is not contained in the tarfile, it is created during configuring. However, you specified `no-comp`, so it didn't get created.

**Comment by levitte** [comment]
Yup, `make depend` is the answer.
