### ISSUE TITLE
Add and prefer OSSL_HASH instead of lh_ prefix?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#7704]
Should OpenSSL stop using lh_ to stop namespace collision?  There's about 120 used internally, and we could keep the lh_ names for compatibility.

**Comment by richsalz** [comment]
BTW sk_ is over 2500 uses, so that's a bigger issue if you want to address it.

**Comment by levitte** [comment]
A question, are you talking about actual observed collision, or is that hypothetical? That will affect how this gets prioritized.

**Comment by levitte** [comment]
I suspected that, obviously.

The understanding so far is to use `OSSL_` as a prefix for new modules... I'm frankly apprehensive of converting already existing APIs unless there are actual clashes (also, we can argue that "we were there first" 😉).

But not to be entirely dismissive, it's still something to consider *some* time...

**Comment by richsalz** [comment]
I would do it by adding the new names and then later on removing the old ones.
If you're willing, i can make a PR to do part 1.

**Comment by nhorman** [comment]
seems like this won't get planned

marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by richsalz** [comment]
No interest and I don't care since apparently it's not affecting any downstream users. Closing this.
