### ISSUE TITLE
Regression: Tor's use of SSL_export_keying_material() broken with TLS 1.3 in Openssl 1.1.1a

### ISSUE THREAD

**Issue by nmathewson** [openssl/openssl#7712]
Hello!  Commit ec0c5f5693e39c5a013f81e6dd9dfd09ec65162d, "Reduce stack usage in tls13_hkdf_expand", breaks TLS1.3 when used with Tor.

The idea behind this commit, if I understand correctly, was to save stack space in `tls13_hkdf_expand` by lowering TLS13_MAX_LABEL_LEN, on the theory that TLS itself never uses any labels longer than 12 characters.

But the problem here is that the `tls13_hkdf_expand` function is also reachable from SSL_export_keying_material(), which is a public API.  As part of its handshake, Tor invokes this function with a 44-byte label.  This is no longer supported by OpenSSL 1.1.1a.

If we were to change Tor to use a shorter label, we'd break backward compatibility.

The simplest solution here would be to revert ec0c5f5693e39c5a013f81e6dd9dfd09ec65162d.

References:

#7297 is the original PR that introduced this problem for us.

https://trac.torproject.org/projects/tor/ticket/28616 is the Tor bug.

**Comment by mattcaswell** [comment]
Darn. Yes that does seem to be a sensible solution. Ping @bernd-edlinger.

**Comment by bernd-edlinger** [comment]
Agreed, maybe leave the "static" labelprefix in place.
Bit I wonder how the caller should know of the 248 byte limit then....
@mattcaswell could you please take care of this, thanks!
