### ISSUE TITLE
BN_mod_add_quick returns different result since 1.0.2p

### ISSUE THREAD

**Issue by eladavron** [openssl/openssl#7713]
Greetings!
We're using OpenSSL with WAPI, and ever since upgrading to 1.0.2p we can't connect to our Certificate based WAPI AP.
We did some deep digging and narrowed the issue down to changes made in 83325a68ad5fdfc359ab9d82a0e0da8e5fe7ede1 (all commits before that one work with our system, and all commits after it don't). Specifically the method `BN_mod_add_quick`.
More specifically - if we take the final 1.0.2p code and replace its implementation of `BN_mod_add_quick` with that of 1.0.2o, everything works as expected. 
Furthermore, the difference is only in value - the method itself returns "true" (success) in both cases.
Any insights or ideas into this would be greatly appreciated.
Thanks!

**Comment by mattcaswell** [comment]
Can you give details of specific params that cause the difference in behaviour?

**Comment by eladavron** [comment]
Yes, here's a reproducible example:
```cpp
BIGNUM* r2 = BN_new();
BIGNUM* a2 = BN_new();
BIGNUM* b2 = BN_new();
BIGNUM* m2 = BN_new();

BN_hex2bn(&r2, "B6FEE0E66D44782A1744F2CD28969C8C1EDEB1CE8AFBF6D5");
BN_hex2bn(&a2, "8CBE73EFDF8441F980C40F0A0107797A8CFB932FF6CD171C");
BN_hex2bn(&b2, "C384D85E8A0426CAD6F8AEDAEE64659D264CA6FAE361CAFE317598D9B79B5B42");
BN_hex2bn(&m2, "BDB6F4FE3E8B1D9E0DA8C0D40FC962195DFAE76F56564677");

TRACE_LOG(OUTPUT_LEVEL_DBG, "R: %s", BN_bn2hex(r2));
TRACE_LOG(OUTPUT_LEVEL_DBG, "A: %s", BN_bn2hex(a2));
TRACE_LOG(OUTPUT_LEVEL_DBG, "B: %s", BN_bn2hex(b2));
TRACE_LOG(OUTPUT_LEVEL_DBG, "M: %s", BN_bn2hex(m2));

BN_mod_add_quick(r2, a2, b2, m2);

TRACE_LOG(OUTPUT_LEVEL_DBG, "RUNNING QUICK MOD ADD!");

TRACE_LOG(OUTPUT_LEVEL_DBG, "R2: %s", BN_bn2hex(r2));
TRACE_LOG(OUTPUT_LEVEL_DBG, "A2: %s", BN_bn2hex(a2));
TRACE_LOG(OUTPUT_LEVEL_DBG, "B2: %s", BN_bn2hex(b2));
TRACE_LOG(OUTPUT_LEVEL_DBG, "M2: %s", BN_bn2hex(m2));
```

The results in 102o are:
```             
R: B6FEE0E66D44782A1744F2CD28969C8C1EDEB1CE8AFBF6D5    
A: 8CBE73EFDF8441F980C40F0A0107797A8CFB932FF6CD171C    
B: C384D85E8A0426CAD6F8AEDAEE64659D264CA6FAE361CAFE317598D9B79B5B42  
M: BDB6F4FE3E8B1D9E0DA8C0D40FC962195DFAE76F56564677    

RUNNING QUICK MOD ADD!     

R2: C384D85E8A0426CAA6002DCC8F5D89F89967F530D49FE25F6076449A58122BE7 
A2: 8CBE73EFDF8441F980C40F0A0107797A8CFB932FF6CD171C   
B2: C384D85E8A0426CAD6F8AEDAEE64659D264CA6FAE361CAFE317598D9B79B5B42 
M2: BDB6F4FE3E8B1D9E0DA8C0D40FC962195DFAE76F56564677   
```

And with 102p:

```
R: B6FEE0E66D44782A1744F2CD28969C8C1EDEB1CE8AFBF6D5    
A: 8CBE73EFDF8441F980C40F0A0107797A8CFB932FF6CD171C    
B: C384D85E8A0426CAD6F8AEDAEE64659D264CA6FAE361CAFE317598D9B79B5B42  
M: BDB6F4FE3E8B1D9E0DA8C0D40FC962195DFAE76F56564677    

RUNNING QUICK MOD ADD!     

R2: A6002DCC8F5D89F89967F530D49FE25F6076449A58122BE7   
A2: 8CBE73EFDF8441F980C40F0A0107797A8CFB932FF6CD171C   
B2: C384D85E8A0426CAD6F8AEDAEE64659D264CA6FAE361CAFE317598D9B79B5B42 
M2: BDB6F4FE3E8B1D9E0DA8C0D40FC962195DFAE76F56564677

```
I did notice that in o’s result, the string is much longer, and that the upper (extra) 16 characters seem to be the upper 16 characters of B.

**Comment by mattcaswell** [comment]
````
BN_hex2bn(&b2, "C384D85E8A0426CAD6F8AEDAEE64659D264CA6FAE361CAFE317598D9B79B5B42");
BN_hex2bn(&m2, "BDB6F4FE3E8B1D9E0DA8C0D40FC962195DFAE76F56564677");
````

This looks like an invalid use of the `BN_mod_add_quick()` function. The preconditions for this function are that both `a` and `b` are non-negative and less than `m`. This is clearly not the case in the above since `b` is clearly larger than `m`. If you don't meet the preconditions then you have to use `BN_mod_add()` instead.

**Comment by mattcaswell** [comment]
AFAIK only invalid inputs get different results.

> Furthermore, wouldn't it be prudent to have the method fail on incorrect or invalid input?

I would be worried about the potential performance impacts of doing so.
