### ISSUE TITLE
Can OpenSSL be used over custom transports other than sockets?

### ISSUE THREAD

**Issue by raveendrapadala** [openssl/openssl#7715]
All,
As per the client-server programs i see OpenSSL context is used over Network sockets. 

Let us suppose if I would like to use OpenSSL over custom transport mechanism(E.g:I2C) for handshake with peer device is it possible?

If yes, do we have any sample references please share the details.

**Comment by levitte** [comment]
yes, it is possible.  All that you should need to do is to write a BIO source/sink for it.  One example is the bio pair, found in `crypto/bio/bss_bio.c`.  It is primarly a test tool, but it is an example of a BIO source/sink that doesn't use sockets.

**Comment by kroeckx** [comment]
It should be possible to do TLS / DTLS over any bidirectional
communication channel. TCP and UDP are just very common, but there
is no need to use them. Note that TLS expects the properties of
TCP to be able to work, that is that packets all arrive and in
order.
