### ISSUE TITLE
 openssl ciphers "" lists a few ciphers and does not throw error anymore in 1.1.1

### ISSUE THREAD

**Issue by rbalint** [openssl/openssl#7725]
In 1.1.1 the behaviour of the openssl ciphers command changed. Now for empty cipher list string it lists a few ciphersuites, while the man page ciphers(1) says: "The cipher list consists of one or more cipher strings separated by colons. "

 ```
root@cosmic-daily:~# openssl ciphers ""
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
 ```

Previously it raised an error:
```
user@bionic$ openssl ciphers ""
Error in cipher list
139669014430144:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2129:
user@bionic$  openssl version
OpenSSL 1.1.0g  2 Nov 2017
```

**Comment by mattcaswell** [comment]
This is expected behaviour. This is due to the different handling of TLSv1.3 ciphersuites. These are configured separately and are present by default. Refer to the ciphers man page:

https://www.openssl.org/docs/man1.1.1/man1/ciphers.html

See the description for the "-ciphersuites" option.
