### ISSUE TITLE
s_server -no_ticket does not work with TLS 1.3

### ISSUE THREAD

**Issue by FiloSottile** [openssl/openssl#7727]
`s_server` will send session tickets after negotiating TLS 1.3 even if `-no_ticket` is used. It would be nice to have the ability to turn them off: they pollute test cases and as they are delivered after the handshake they are complicated to ignore.

**Comment by FiloSottile** [comment]
Just found https://github.com/openssl/openssl/blob/f1d49ed94707f5f0799541aa8e528dce67712948/apps/s_server.c#L964 in the source, although it's not in https://www.openssl.org/docs/manmaster/man1/s_server.html.

Is that online man page updated automatically?

**Comment by mspncp** [comment]
Thanks Filo for your report. It seems like the `-num_tickets` flag was introduced for `openssl s_server` app in commit 394159da60 but has not been documented yet. So I'll reopen this ticket and ping @mattcaswell to have a look.

**~/src/openssl$ git --no-pager  log --oneline -S num_tickets**
41145c35bf Document changes to SSL_OP_NO_TICKET for TLSv1.3
56548e86ac Add documentation for the ability to control the number of tickets
36ff232cf2 Change the default number of NewSessionTickets we send to 2
394159da60 Allow configuation of the number of TLSv1.3 session tickets via SSL_CONF
9d0a8bb71e Enable the ability to set the number of TLSv1.3 session tickets sent

**Comment by mspncp** [comment]
@FiloSottile FYI: a pull request has been created by @mattcaswell which adds the missing documentation for the `-num_tickets` option.
