### ISSUE TITLE
Setting TLS PRF secret unsets TLS PRF seed

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#7728]
Testing https://github.com/openssl/openssl/pull/6674/files#diff-5cdc677aaa86805a06a5772b83976f38R82 I ran into an issue where KDF would fail if the seed was set before the secret.
This appears to be present in previous releases: 
https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/crypto/kdf/tls1_prf.c#L70

Use case: https://github.com/wahern/luaossl/pull/154/commits/228c1b6077d063434174d43217764cee4888010c#diff-ce817d33bbc15430a154eb6954bd86faR11735

**Comment by t8m** [comment]
This does not seem to be an issue anymore after the implementation was moved to the provider(s).
