### ISSUE TITLE
ECDSA_SIG_set0 does not follow documentation

### ISSUE THREAD

**Issue by HenriChataing** [openssl/openssl#7731]
The documentation attached to the prototype declaration of `ECDSA_SIG_set0` seem to imply that `NULL` can be passed for `r` or `s` and the old value will be retained. The actual implementation returns an error if either is `NULL`.
Either the documentation or the implementation should be updated, with a preference for the latter (if updating only one part of the signature, you would need to create a duplicate for the other one).

**Comment by kroeckx** [comment]
I think it should behave like the others. For instance RSA_set0_key() is documented as:
```
The values n and e must be non-NULL the first time this function is called on a given RSA object.
```

**Comment by HenriChataing** [comment]
I hadn't though about this case :) Following the example you proposed, the implementation should be something like this then:

```c
int ECDSA_SIG_set0(ECDSA_SIG *sig, BIGNUM *r, BIGNUM *s)
{
    if ((sig->r == NULL && r == NULL) ||
        (sig->s == NULL && s == NULL))
        return 0;

    if (r != NULL) {
        BN_clear_free(sig->r);
        sig->r = r;
    }
    if (s != NULL) {
        BN_clear_free(sig->s);
        sig->s = s;
    }

    return 1;
}
```
