### ISSUE TITLE
d2i_X509 undefinend reference

### ISSUE THREAD

**Issue by matthiasballreich** [openssl/openssl#7741]
I tried to link the 1.1.2-dev to my C++ Project in QT. Paths are correct and working with structures like X509, but everytime i got the error: d2i_X509 undefinend reference when i want to use that method.

What's the problem? I don't found the declaration of this method inside the X509.h. Was this method removed ore something changed?

**Comment by levitte** [comment]
This declaration macro, which is present in `include/openssl/x509.h`, does generate `d2i_X509` among others:

``` C
DECLARE_ASN1_FUNCTIONS(X509)
```

Can you make us a small example to try with?

**Comment by matthiasballreich** [comment]
Thanks - good to know that this is the declaration.

I added my small QT C*+ example Project.
[test.zip](https://github.com/openssl/openssl/files/2637215/test.zip)

**Comment by levitte** [comment]
Lesson to learn: don't just give the error message, also show the command that got the error:

```
g++ -Wl,-O1 -o test main.o mainwindow.o moc_mainwindow.o   -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: main.o: in function `main':
main.cpp:(.text.startup+0x47): undefined reference to `d2i_X509'
```

When looking at that line, it's completely obvious why you get the error; you're not linking with `libcrypto`.

Now, looking at `test.pro`, I notice a few lines starting with `win32:` (why???) that should add the appropriate linking options (although `-llibcrypto` wasn't quite right).  With the following change, the build goes through error free:

``` diff
: ; diff -u test.pro.orig test.pro
--- test.pro.orig	2018-12-02 19:07:30.000000000 +0100
+++ test.pro	2018-12-02 19:59:05.208805849 +0100
@@ -39,7 +39,7 @@
 else: unix:!android: target.path = /opt/$${TARGET}/bin
 !isEmpty(target.path): INSTALLS += target
 
-win32: LIBS += -L$$PWD/../openssl/openssl/ -llibcrypto
-win32: LIBS += -L$$PWD/../openssl/openssl/ -llibssl
+LIBS += -L$$PWD/../openssl/openssl/ -lssl
+LIBS += -L$$PWD/../openssl/openssl/ -lcrypto
 INCLUDEPATH += $$PWD/../openssl/openssl/include
 DEPENDPATH += $$PWD/../openssl/openssl/include
```
