### ISSUE TITLE
Issue in TLS 1.3 custom ciphersuites order sent in client hello

### ISSUE THREAD

**Issue by ealashwali** [openssl/openssl#7749]
I am using OpenSSL 1.1.1a in another SW that performs TLS handshake. The software allows sending a custom ciphersuites list and performs a TLS handshake. I am using the tool with `OpenSSL 1.1.1a`. There is an issue that seems from the underlying library. The ciphersuites list order is unreliable. I did not face any problem with this SW in previous version using OpenSSL 1.1.0g.
Please, see the issue and how to reproduce it here:
https://github.com/prbinu/tls-scan/issues/21

**Comment by richsalz** [comment]
I am a bit confused about your issue.  You are using OpenSSL in software on a server, S, and some other software is running on the client, C, is that right?  And what is happening?

Note that the main difference between 1.1.0 and 1.1.1 is adding TLS 1.3, and OpenSSL uses the highest TLS version possible.  Perhaps you want to remove 1.3 from your server versions?  You can do this at run-time.

**Comment by mattcaswell** [comment]
This is due to a problem in tls-scan. It isn't setting TLSv1.3 ciphersuites properly. I commented directly in the referred issue.

**Comment by ealashwali** [comment]
@richsalz Thanks for your response. @mattcaswell replied in the referred issue. Just to clarify. tls-scan acts as a client. But it allows me to customise the list of ciphersuites. It is used for scanning a list of servers. I do not know or set anything about the servers. However, the client uses OpenSSL1.1.1a to offer TLS 1.3. But the list of ciphersuites order that tls-scan is not correct when the tls-scan uses OpenSSL1.1.1, but this issue does not appear with older OpenSSL like OpenSSL1.1.0g.

**Comment by richsalz** [comment]
It looks like tls-scan is doing the wrong thing, as @mattcaswell pointed out.  I think this issue can be closed.
