### ISSUE TITLE
OpenSSL BER-encoding

### ISSUE THREAD

**Issue by MasterMeng** [openssl/openssl#7751]
When I import a certificate to a ukey,it request the certificate encoding by ber,but I couldn`t find anything about ber-encoding in openssl lib.Is it supported?

**Comment by richsalz** [comment]
Yes it is supported.  It is a binary format.  Many commands have an "-outform DER" for example. You can consider DER to be a subset of BER.

**Comment by mspncp** [comment]
If you are interested in more details, search for ASN.1 ([Abstract Syntax Notation One](https://en.wikipedia.org/wiki/Abstract_Syntax_Notation_One)). This is the grammar which describes how the binary data is organized and BER resp. DER are the _basic_ resp. _distinguished encoding rules_ which mandate how the data is to be encoded, when it is saved to a file or transmitted. As @richsalz already replied, DER is more specific than BER, so DER-encoded data conforms to the BER-encoding rules (but not vice versa).
