### ISSUE TITLE
TLS 1.2 finished message

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#7753]
In 1.2 version of TLS, verify_data length depends on the cipher suite. Hovewer in openssl 1.1.1a TLS1_FINISH_MAC_LENGTH is always equal to 12. May it would be a good idea to make this value changeable?

**Comment by mattcaswell** [comment]
There are no currently supported ciphersuites that have a value for this other than 12 (do any exist?). If at some point in the future we were to add support for a ciphersuite that had a different value for this then we would integrate support for it at that time. It seems fairly pointless to do so until then.
