### ISSUE TITLE
Can't load ./.rnd into RNG

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#7754]
When you call openssl 1.1.1а command line utility ./.rnd file is created with root privileges. After that when you try to generate a certificate, the message appears:
140396229990144:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto/rand/randfile.c:98:Filename=./.rnd

**Comment by mspncp** [comment]
As far as I know (and I verified it using strace), `openssl rand` _does not_ read or write a rand file unless you provide the `-rand` resp. `-writerand` option. Now if you explicitely tell openssl to create this rand file as root, it is your duty to change the file permissions or ownership in order to be able to load it back in again.

```
Usage: rand [flags] num
Valid options are:
 -help               Display this summary
 -out outfile        Output file
 -rand val           Load the file(s) into the random number generator
 -writerand outfile  Write random data to the specified file
 -base64             Base64 encode output
 -hex                Hex encode output
 -engine val         Use engine, possibly a hardware device
```

**Comment by mspncp** [comment]
It could also be configured in `openssl.cnf`.

**Comment by mspncp** [comment]
> When you call openssl 1.1.1а command line utility ./.rnd file is created with root privileges. 

@bernd-edlinger is it possible that this is a side effect of your change 1fd6afb571e85fbc37ffb522646e7ec2c6e4a11e?

@YuDudysheva If you have `RANDFILE=...` configuration lines in your `openssl.cnf` than you can safely remove them, as it was done in 1fd6afb571e85fbc37ffb522646e7ec2c6e4a11e, because saving and restoring the rng state is not necessary anymore in the openssl 1.1.1 random generator.

**Comment by YuDudysheva** [comment]
@mspncp removing line with RANDFILE from config works fine.  Thank you

**Comment by dazinator** [comment]
I am still having this problem:

I'm on Windows 10 using:

> OpenSSL> version
OpenSSL 1.1.1  11 Sep 2018

When I run the following command in an Administrative command prompt, and having taken the suggestioin above of removing both RANDFILE= lines from `openssl.conf.` I see the following:

> openssl req -new -x509 -key privatekey.pem -out publickey.cer -days 1825
Can't load ./.rnd into RNG
10136:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto\rand\randfile.c:88:Filename=./.rnd
You are about to be asked to enter information that will be incorporated

**Comment by bernd-edlinger** [comment]
You should probably update to 1.1.1b now

**Comment by Lidiaaa** [comment]
Tell me how to fix the error, version 1.1.1b
OpenSSL> genrsa -out hasanova.pem -des3 -rand .rnd 4096
Can't load .rnd into RNG
14656:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto\rand\randfile.c:98:Filename=.rnd
error in genrsa

**Comment by mspncp** [comment]
@Lidiaaa did you try suggestion https://github.com/openssl/openssl/issues/7754#issuecomment-444063355?

**Comment by Lidiaaa** [comment]
@mspncp Yes, it still does not help

**Comment by mspncp** [comment]
Oh! I overlooked that you supplied it as an command argument:

```
OpenSSL> genrsa -out hasanova.pem -des3 -rand .rnd 4096
```

Please try the following command instead:

```
OpenSSL> genrsa -out hasanova.pem -des3  4096
```

**Comment by Lidiaaa** [comment]
@mspncp error
OpenSSL> genrsa -out hasanova.pem -des3  4096
genrsa: Can't open "hasanova.pem" for writing, Permission denied
error in genrsa

**Comment by mspncp** [comment]
Please only reply on #8717.

**Comment by MasterJames** [comment]
For me the issue was the --rand flag now only works as a config file parameter.

Before it only work as a ---rand flag and not from the config file, so now you take out the CLI -- rand flag but make sure it's set in the config file.

Too bad they didn't make it work in both ways with the CLI flag overriding (maybe next time both ways will work properly together) Well I guess that's one way to show people it's working properly and get ride of the hack to fix that's no longer needed. If intentional I would love an error message saying BTW use the config file instead of CLI for rnd file for now.

**Comment by mspncp** [comment]
> For me the issue was the --rand flag now only works as a config file parameter.

I'm not sure I understand what you are talking about. Only the RANDFILE config file parameters were removed in https://github.com/openssl/openssl/commit/0f58220973a02248ca5c69db59e615378467b9c8#diff-8ce6aaad88b10ed2b3b4592fd5c8e03aL13 and https://github.com/openssl/openssl/commit/0f58220973a02248ca5c69db59e615378467b9c8#diff-8ce6aaad88b10ed2b3b4592fd5c8e03aL60.

The `-rand` command line option was not changed. Note however, that we don't use gnu-style long options, so there's only one dash, not two (`--rand`).

**Comment by mspncp** [comment]
> The `-rand` command line option was not changed. Note however, that we don't use gnu-style long options, so there's only one dash, not two (`--rand`).

Correction: TIL that nowadays one or two dashes are accepted equally (starting from version 1.1.0).

**Comment by MasterJames** [comment]
Right thanks for the - double -- clarity. I did mean single dash. I looked into it further it seems it use to work with -rand file:Private/.rnd and now the "file:" part causes the error.
I think I would have preferred to use the config file before as I had that initially from before and so when it did not work I found only the command line -rand flag would work but stopped working when I moved to Ununtu 19.
To clarify if you put the "file:" reference on the command line flag value it will fail with that "Can't load file into RNG".

**Comment by bathindahelper** [comment]
Can somebody give me the full command pls?
i was using this command (by finding the exact command from some 2 year old video): sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt

And I'm getting this error: "Can't load /root/.rnd into RNG
140121868997056:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd" 

I'm using latest openssh (just downloaded) on Ubuntu 18.04.x (upgraded)

**Comment by richsalz** [comment]
Please open a new issue, don't post a different problem to a closed issue.

**Comment by mspncp** [comment]
@bathindahelper did you read this issue and try the suggestions I made?

**Comment by matusnovak** [comment]
@bathindahelper I had the same issue as you on Ubuntu 18.04.x. Removing (or commenting out) `RANDFILE  = $ENV::HOME/.rnd` from `/etc/ssl/openssl.cnf` worked for me.

**Comment by bathindahelper** [comment]
> Please open a new issue, don't post a different problem to a closed issue.

@richsalz Sorry, but I (may be wrongly) thought that my issue was very much related. Sorry again.


@bathindahelper did you read this issue and try the suggestions I made?
@mspncp  Yes I did read all posts, but couldn't find the solution.


@bathindahelper I had the same issue as you on Ubuntu 18.04.x. Removing (or commenting out) `RANDFILE = $ENV::HOME/.rnd` from `/etc/ssl/openssl.cnf` worked for me.

@matusnovak Thank you. I'll try and let know.

**Comment by bathindahelper** [comment]
@matusnovak  Yes it DID SOLVE the problem. 
Thank you very much. (Though I am surprised how did it came to your mind though!!!)

**Comment by fred-maria** [comment]
Hello, for information I had the same issue on Windows with mingw64 (coming from a Git installation).
Openssl version is 1.1.1d
The problem was solved by running from git bash:  `chmod 600 ~/.rnd`
Need also to mention that I used neither `-rand` nor `-writerand` option on openssl command.

**Comment by mikebridge** [comment]
Is there any risk to working around this just with `touch ~/.rnd`?

**Comment by ptrovatelli** [comment]
> Is there any risk to working around this just with `touch ~/.rnd`?

good question because modifying the openssl.cnf may not be easy (I have this problem during a gitlab-ci run). 

To be very safe see this comment

https://security.stackexchange.com/questions/177509/purpose-of-randfile-in-openssl/177512#177512
`dd if=/dev/urandom of=~/.rnd bs=256 count=1`

**Comment by aneesh121** [comment]
If you are in ubuntu environment, just comment out these two lines from /etc/ssl/openssl.cnf
```
#RANDFILE       = $ENV::HOME/.rnd
#RANDFILE       = $dir/private/.rand    # private random number file
```
Thant would do the trick !

**Comment by diegodurante** [comment]
```
Can't load /root/.rnd into RNG
140195094647232:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
```
I was experiencing this issue while generating a self signed certificate into a docker container with a ubuntu 18.04 image, before it was working fine with ubuntu 14.

I was able to fix the issue thanks to @mikebridge suggestion:

> Is there any risk to working around this just with touch ~/.rnd?

I am doing this locally, in development environment so I don't need to care about security concerns.

Old code:
`RUN openssl req -x509 -sha256 -nodes -newkey rsa:4096 -days 365 -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj '/CN=localhost'
`

New working code: 🎉
```
RUN touch ~/.rnd
RUN openssl req -x509 -sha256 -nodes -newkey rsa:4096 -days 365 -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj '/CN=localhost'
```

Hope it helps!

**Comment by shirakaba** [comment]
> I had the same issue as you on Ubuntu 18.04.x. Removing (or commenting out) `RANDFILE = $ENV::HOME/.rnd` from `/etc/ssl/openssl.cnf` worked for me.

I can confirm that this also works for me on Ubuntu 18.04.x. If you prefer not to edit the `/etc/ssl/openssl.cnf` directly, you can pass in an altered copy of the same file, that has the above-mentioned `RANDFILE` line commented out, by passing in a `-config` param like so:

`-config <(cat /etc/ssl/openssl.cnf | sed "s/RANDFILE\s*=\s*\$ENV::HOME\/\.rnd/#/")`

## Before (fails)

```sh
openssl \
  req \
  -subj "${SUBJECT}" \
  -new \
  -x509 \
  -passout "pass:${CERT_AUTH_PASS}" \
  -keyout "${FILE_NAME}.key" \
  -out "${FILE_NAME}.crt" \
  -days 36500
```

## After (succeeds)

```sh
openssl \
  req \
  -subj "${SUBJECT}" \
  -new \
  -x509 \
  -passout "pass:${CERT_AUTH_PASS}" \
  -keyout "${FILE_NAME}.key" \
  -out "${FILE_NAME}.crt" \
  -days 36500 \
  -config <(cat /etc/ssl/openssl.cnf | sed "s/RANDFILE\s*=\s*\$ENV::HOME\/\.rnd/#/")
```

---

In my case, it means one less thing to provision to keep my SSL scripts working on each new Ubuntu server. Hope this helps someone!

**Comment by Lovor01** [comment]
> Windows

You should set Randfile to location of .rnd file, i.e. `set RANDFILE=.rnd`

**Comment by btufail** [comment]
> ```
> Can't load /root/.rnd into RNG
> 140195094647232:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
> ```
> 
> I was experiencing this issue while generating a self signed certificate into a docker container with a ubuntu 18.04 image, before it was working fine with ubuntu 14.
> 
> I was able to fix the issue thanks to @mikebridge suggestion:
> 
> > Is there any risk to working around this just with touch ~/.rnd?
> 
> I am doing this locally, in development environment so I don't need to care about security concerns.
> 
> Old code:
> `RUN openssl req -x509 -sha256 -nodes -newkey rsa:4096 -days 365 -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj '/CN=localhost' `
> 
> New working code: 🎉
> 
> ```
> RUN touch ~/.rnd
> RUN openssl req -x509 -sha256 -nodes -newkey rsa:4096 -days 365 -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj '/CN=localhost'
> ```
> 
> Hope it helps!

In my case: "RUN touch ~/.rnd" did the magic. Thanks @diegodurante diegodurante

**Comment by 2anoyu** [comment]
FIX this problem 
> into RNG 140407482536384:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88

This is caused by the default random file is missing.  The message above is a warning and can be ignored in most cases, but if you want to prevent the warning - read on.  Creating a blank file called .rnd with touch may work, but it is not a random file.

Create a /home/username/.rnd file with the command below ( this is in Linux, I assume it is similar in Windows c:\users\username\.rnd )

       openssl rand -out ~/.rnd -writerand ~/.rnd      
    ( In windows it should be - openssl rand -out c:\users\username\.rnd -writerand c:\users\username\.rnd )

The file will be read/write by the username 
next time something is looking for the .rnd file it will find the file in the default location for that user and not give the error.

Since I am on Linux I cannot be sure about the Windows format, but the idea is to create a .rnd file in your home directory.
