### ISSUE TITLE
OpenSSL 1.0.2p broke common usage of EVP_PKEY_asn1_new

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#7758]
This commit broke our usage of EVP_PKEY_asn1_new. https://github.com/openssl/openssl/commit/f72a7ce8bc0a5c0866c6a848a7f54854d67aeba2

I thought that minor releases should never break the API of existing funcitonality? This is how we call the function:
`EVP_PKEY_asn1_new(NID_undef, 0, NULL, NULL);`

We do this to create a dummy ASN1 method.

**Comment by mattcaswell** [comment]
> I thought that minor releases should never break the API of existing funcitonality?

Hmm - that's true. On the face of it we do seem to have done that with this commit. Ping @levitte?

**Comment by levitte** [comment]
The origin is #6880, and this was to ensure that the internal tables would never be populated with an invalid `EVP_PKEY_ASN1_METHOD`.

@mlindner, may I ask what you do with the dummy ASN1 method?  Would it help if we moved the check to `EVP_PKEY_asn1_add0`, i.e. refused to register an invalid ASN1 method rather than refusing to create it?

**Comment by mlindner** [comment]
I think that would work. The code that calls `EVP_PKEY_asn1_new(NID_undef, 0, NULL, NULL);` is somewhat of a hack in our code so the created asn1 method isn't used. We've worked around the issue locally by setting ASN1_PKEY_ALIAS despite it not being an alias.

Still, isn't that still an API change?

**Comment by levitte** [comment]
> Still, isn't that still an API change?

It's a bug fix, i.e. you should never have been able to register such a `EVP_PKEY_ASN1_METHOD` in the first place.  I know that views differs on this, but between bothering applications and allowing our internal tables to get corrupted, I choose the former.  However, I do see value in doing the former as gently as possible.

**Comment by mlindner** [comment]
Ok sounds good to me, I'll leave it to the OpenSSL people to decide the best fix for this that has the most narrow effect on existing users.

**Comment by levitte** [comment]
Fixup in #7847.  Care trying the patch out?

**Comment by mlindner** [comment]
Sorry missed your comment. Yes that looks fine to me.

**Comment by levitte** [comment]
Cool. Thanks 🙂
