### ISSUE TITLE
ocsp utility doesn't tolerate critical id-pkix-ocsp-no-check extension

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#7761]
If the delegated OCSP responder has id-pkix-ocsp-nocheck extension specified and marked as critical, the ocsp response verification check fails.

How reproducible:
always

Steps to Reproduce:
1. Create a PKI structure with separate OCSP server and leaf certificates
2. Start ocsp responder with the certificate
3. Try to verify any certificate using openssl ocsp

Actual results:
Response Verify Failure
140627725788992:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unhandled critical extension
certs/ca_cert.pem: good
        This Update: Jul 23 15:12:40 2013 GMT

Expected:
Response verify OK
certs/ca_cert.pem: good

**Comment by mattcaswell** [comment]
Isn't that correct behaviour? If we receive a critical extension that we don't recognise then surely the correct thing to do is to fail? Or is this issue actually a feature request asking us to support this?

**Comment by t8m** [comment]
Yes, it is RFE for adding support for this extension. There are OCSP responders that send this extension marked as critical although it is recommended to mark it as non-critical.

**Comment by t8m** [comment]
The implementation can be as rudimentary as just ignoring this particular extension even if it is marked as critical, because of the thing the presence of this extension means.

**Comment by t8m** [comment]
@DDvO what do you think about this issue?

**Comment by DDvO** [comment]
Simply ignoring a critical extension is exactly what must not happen. See RFC 5280 section 4.2:

>    A certificate-using system MUST reject the certificate if it encounters
>    a critical extension it does not recognize or a critical extension
>    that contains information that it cannot process.

So the current OpenSSL implementation is correct.
In the given case it's the risk/fault of the cert issuer marking that extension critical.

**Comment by DDvO** [comment]
What we could do is to implement some policy option(s) how the verification procedure is supposed to handle the cases listed in https://tools.ietf.org/html/rfc6960#section-4.2.2.2.1, including the reaction on that extension. Then it won't be an unknown extension any more, and only then are we entitled not to reject it.

**Comment by kroeckx** [comment]
> Response Verify Failure
> 140627725788992:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unhandled critical extension
> certs/ca_cert.pem: good
>         This Update: Jul 23 15:12:40 2013 GMT

If the OCSP check fails, do we want to return "good"?

**Comment by t8m** [comment]
@DDvO - and I am saying the policy (if we want the support to be as rudimentary as possible) could be: ignore the extension and do the check anyway. Then we can declare the extension as known and we do not need to reject it any more even if marked as critical.

**Comment by t8m** [comment]
I am in no way asking for ignoring any unknown critical extension.

**Comment by DDvO** [comment]
> I am in no way asking for ignoring any unknown critical extension.

Just 'knowing' a critical extension is not sufficient  - see again what I quoted:

> A certificate-using system MUST reject the certificate if it encounters if it encounters
(a critical extension it does not recognize or) 
a critical extension that contains information that it cannot process.

The trivial 'handling' you suggested, namely ignoring (rather than doing) what a critical extension expresses,
in my view boils down to a violation of the second case mentioned there that must not happen.

On the other hand, the semantics of this specific extension is that something does not need to be done -
namely, not certificate status checking is needed to an OCSP responder with such a cert.
Since OpenSSL usually does not do cert status checking anyway this semantics is fulfilled by default :)

**Comment by DDvO** [comment]
Why not seriously implement the intended reaction on this extension:
If `X509_V_FLAG_CRL_CHECK` or the like is set in the verification parameters and the `id-pkix-ocsp-nocheck` extension is present in an OCSP responder cert then temporarily disable all revocation status checks while verifying that cert.
It should take only a few lines of code to do that.

**Comment by DDvO** [comment]
Here is the essence of solving this:
```
diff --git a/crypto/ocsp/ocsp_vfy.c b/crypto/ocsp/ocsp_vfy.c
index 92512829c9..d180a1bd06 100644
--- a/crypto/ocsp/ocsp_vfy.c
+++ b/crypto/ocsp/ocsp_vfy.c
@@ -41,9 +41,12 @@ static int ocsp_verify_signer(X509 *signer, X509_STORE *st, unsigned long flags,
         OCSPerr(0, ERR_R_X509_LIB);
         goto end;
     }
-    if ((flags & OCSP_PARTIAL_CHAIN) != 0
-            && (vp = X509_STORE_CTX_get0_param(ctx)) != NULL)
-        X509_VERIFY_PARAM_set_flags(vp, X509_V_FLAG_PARTIAL_CHAIN);
+    if ((vp = X509_STORE_CTX_get0_param(ctx)) != NULL) {
+        if ((flags & OCSP_PARTIAL_CHAIN) != 0)
+            X509_VERIFY_PARAM_set_flags(vp, X509_V_FLAG_PARTIAL_CHAIN);
+        if (X509_get_ext_by_NID(signer, NID_id_pkix_OCSP_noCheck, -1) >= 0)
+            X509_VERIFY_PARAM_clear_flags(vp, X509_V_FLAG_CRL_CHECK_ALL);
+    }
     X509_STORE_CTX_set_purpose(ctx, X509_PURPOSE_OCSP_HELPER);
     X509_STORE_CTX_set_trust(ctx, X509_TRUST_OCSP_REQUEST);
     /* TODO: why is X509_TRUST_OCSP_REQUEST set? Seems to get ignored. */
diff --git a/crypto/x509/v3_purp.c b/crypto/x509/v3_purp.c
index 8b0dfd9759..4c2341ed10 100644
--- a/crypto/x509/v3_purp.c
+++ b/crypto/x509/v3_purp.c
@@ -282,6 +282,9 @@ int X509_supported_extension(X509_EXTENSION *ex)
 #ifndef OPENSSL_NO_RFC3779
         NID_sbgp_ipAddrBlock,   /* 290 */
         NID_sbgp_autonomousSysNum, /* 291 */
+#endif
+#ifndef OPENSSL_NO_OCSP
+        NID_id_pkix_OCSP_noCheck, /* 369 */
 #endif
         NID_policy_constraints, /* 401 */
         NID_proxyCertInfo,      /* 663 */
```

**Comment by t8m** [comment]
@DDvO would you like to submit a PR when you've already solved this?

**Comment by DDvO** [comment]
> @DDvO would you like to submit a PR when you've already solved this?

There are still some open points with this solution, but ok I've submitted a respective PR: #12947.
Can you provide a suitable set of test certs?

**Comment by DDvO** [comment]
A test with such a cert has been added to #12947.

**Comment by ghulands** [comment]
What version will this feature start appearing in?

**Comment by DDvO** [comment]
It is part of the master, so will appear in the next release: version 3.0.0.
