### ISSUE TITLE
link_app makefile target broken on gcc-4.8 ARM

### ISSUE THREAD

**Issue by madduci** [openssl/openssl#778]
I'm using gcc-4.8.2 toolchain for crosscompiling for an ARMv8 CPU.

The process of compiling everything works smoothly until the target _link_app_, on the linking process, where multiple undefined functions are not available

**Comment by richsalz** [comment]
need more details.  like what?  something failed to compile ...

**Comment by madduci** [comment]
I'll put on pastebin the complete log

**Comment by madduci** [comment]
Here you can find the complete error details:

http://pastebin.com/Ft4NxTE8

The problem comes from s_server.c, it contains undefined references to SRP_user_pwd_free and SRP_VBASE_get1_by_user in sv_body, init_ssl_connection, www_body and rev_body

My building environment is:
Debian 8 x64, Cross Toolchain: gcc-arm-gnueabi 4.8.2

Building OpenSSL versions prior to 1.0.2g works without problems

**Comment by mretallack** [comment]
I have hit the same problem, it looks like the symbols needed adding to the openssl.ld file. I have a patch that seems to fix the issue.

[SRP_missingLDEntry.txt]
(https://github.com/openssl/openssl/files/163067/SRP_missingLDEntry.txt)

**Comment by mattcaswell** [comment]
There is no such file in openssl. I believe this may be a Debian specific file used for adding symbol versioning.

**Comment by mretallack** [comment]
Yes, you are correct. OpenEmbedded uses the debian patches. This adds in the openssl.ld file which did not include the new entries.

**Comment by mattcaswell** [comment]
So, this is not an OpenSSL issue. Please raise a bug with the debian OpenSSL package maintainers (ping @kroeckx). Closing this issue.

**Comment by madduci** [comment]
It's not Debian specific. I was compiling the tar.gz package downloaded from openssl.org and just configured the project and ran 'make clean && make'. Why was it working with previous 1.0.2f version then?

**Comment by mattcaswell** [comment]
Sounds like you may have a different problem to @mretallack (although the symptoms sound the same)

**Comment by madduci** [comment]
I've performed other tests with multiple configuration flags (static/shared, no-engine, threads,...) and forced the _make depend_ command (arm-gnueabi-gcc -M) but the build fails always when building s_server.c. It builds without errors when using gcc 4.9 in my host machine.

Could it be a failure of gcc 4.8 or of ar?

**Comment by levitte** [comment]
Lines like these:

```
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

indicate you're trying to run a parallelle make (-j*nn*).  Don't...  or, well, that depends actually.  By all means do in a super fresh pull of the master branch, but otherwise, just don't, the classic build scheme isn't built for that.

**Comment by madduci** [comment]
I get some other errors as well:

http://pastebin.com/75xLbL2U

**Comment by levitte** [comment]
Thanks, I know what to do with that one. Fix coming up.

**Comment by madduci** [comment]
any update on this?

**Comment by levitte** [comment]
Uhmmmm....  this is embarassing, but I lost track of this.  So sorry.

Unforatuntely, your last pastebin isn't available any more, would you care to repeat it?

**Comment by madduci** [comment]
Here you have the full log:

http://pastebin.com/LQsG3NRw

**Comment by mattcaswell** [comment]
Ping @levitte....it seems you forgot the promised fix ;-)

**Comment by kaduk** [comment]
@levitte do you have any state on this one?

**Comment by levitte** [comment]
Unfortunately no.  There's that lost pastebin where "some other error" came up, and I cannot remember at this time if I did fix that particular error or not.  The latest pasted log doesn't tell me anything other than there is indeed two symbols missing, errr, *somewhere*, but I cannot for the life of me figure out how that would be in *our* source, 'cause those symbols do exist, including in `util/libeay.num`, and all we have as evidence is a patch for a file that is not ours (but was presumably created from `util/libeay.num`).  How exactly that comes into play with our builds is beyond me, and I suspect there is some local patching that we aren't privvy to.

So at this point, I can only say "cannot duplicate" and hope that if the error persists, someone (else?) will create a new issue and we get another chance at looking at this more closely.

With apologies for dropping this ball for so long...
