### ISSUE TITLE
Support for linux-arc in openssl-1.1.1

### ISSUE THREAD

**Issue by siabc123si** [openssl/openssl#7840]
Hi all,

Recently upgraded openssl-1.0.2<> to openssl-1.1.1

For "linux-arc" combination, following gcc & ldl flags are used in openssl-1.0.2<> in Configure file
  "linux-arc","gcc:-DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall::-D_REENTRANT::-ldl:BN_LLONG:${no_asm}:dlfcn:linux-shared:-fPIC:-shared:.so.\$(SHLIB_MAJOR).\$(SHLIB_MINOR)",

Need to add these flags to openssl-1.1.1. Since the Configure file format as been changed, i find it almost impossible to add flags and compile for "linux-arc".

I followed "https://wiki.openssl.org/index.php/Compilation_and_Installation#Platfom_specific" and added flags in Configure file (of openssl-1.1.1) as below:
"
"linux-arc-rpath", "gcc:-DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall -Wl,-rpath=/usr/local/ssl/lib::-D_REENTRANT::-Wl,-rpath=/usr/local/ssl/lib -ldl:BN_LLONG:${no_asm}:dlfcn:linux-shared:-fPIC:-shared:.so.\$(SHLIB_MAJOR).\$(SHLIB_MINOR)";
"

On compiling, i am getting below error:
"
buildroot/build_arc/openssl-1.1.1$ ./Configure linux-arc noasm
Global symbol "$no_asm" requires explicit package name at ./Configure line 24.
BEGIN not safe after errors--compilation aborted at ./Configure line 1601.
"
when i run "perl configdata.pm --dump" no useful info is displayed,

I downloaded openssl-1.1.1 and used it as part of linux OS.

I tried to edit/add new configurations/<> but nothing helped.
Please help me in assigning these gcc flags for linux-arc combination on openssl-1.1.1

Thank you.

**Comment by levitte** [comment]
The platform config files look entirely different since 1.1.0.  So here's a quick tip based on the config entry you present; save that in `Configurations/linux-arc.conf`:

``` perl
(
    "linux-arc" => {
        inherit_from     => [ "linux-generic32" ],
        CFLAGS           => add(picker(release => "-fomit-frame-pointer")),
        lib_cppflags     => add("-DL_ENDIAN"),
        bn_ops           => "BN_LLONG",
    },
    "linux-arc-rpath" => {
        inherit_from     => [ "linux-arc" ],
        LDFLAGS          => add("-Wl,--enable-new-dtags,-rpath,$(LIBRPATH)"),
    },
);
```

**Comment by siabc123si** [comment]
Thanks for the quick response. Even before getting response i added "linux-arc" configuration in 10-main.conf
-------------------
    #### linux-arc setups
    "linux-arc" => {
        # 32-bit build.
        inherit_from     => [ "linux-generic32", asm("arc_asm") ],
        CC               => "gcc",
        CFLAGS           => add(picker(default => "-Wall",
                                       release => "-O3 -fomit-frame-pointer")),
        cppflags         => threads("-D_REENTRANT"),
        lib_cppflags     => add("-DL_ENDIAN -DTERMIOS"),
        bn_ops           => "BN_LLONG",
        ex_libs          => add("-ldl"),
        dso_scheme       => "dlfcn",
        shared_target    => "linux-shared",
        shared_cflag     => "-fPIC",
        shared_extension => "-shared:.so.\$(SHLIB_MAJOR).\$(SHLIB_MINOR)",
    },
--------
and executed , 
buildroot/build_arc/openssl-1.1.1$ ./Configure  linux-arc
Configuring OpenSSL version 1.1.1 (0x1010100fL) for linux-arc
Using os-specific seed configuration
Warning! target arc_asm doesn't exist!
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   If you want to report a building issue, please include the   ***
***   output from this command:                                    ***
***                                                                ***
***     perl configdata.pm --dump                                  ***
***                                                                ***
**********************************************************************

perl configdata.pm --dump is attached.
[1.log](https://github.com/openssl/openssl/files/2655039/1.log)

**Comment by siabc123si** [comment]
Tried adding "linux-arc.conf" in Configurations/ folder. Still encountered error:

"
buildroot/build_arc/openssl-1.1.1$ ./Configure --config=Configurations/linux-arc.conf

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

The following config targets from Configurations/linux-arc.conf
shadow pre-existing config targets with the same name:
  linux-arc
  linux-arc-rpath
'

I am pretty new perl language, so please bear with if my questions are too dumb.
Thanks to all of you who are helping me on this.

**Comment by levitte** [comment]
Configure will read *all* `Configurations/*.conf` automatically, so if you have the same targets defined in more than one of them, it will detect that.

Now, if you make the inherit line this, you should have less problems:

```
    inherit_from     => [ "linux-generic32" ]
```

Did you try the exact file I gave you in my first comment?

**Comment by siabc123si** [comment]
When i run configure with linux-arc.conf, i commented out "linux-arc" related changes in 10-main.conf.

"Did you try the exact file I gave you in my first comment?"
  ---- Yes. Exact copy. no changes from what you mentioned in first comment.

**Comment by levitte** [comment]
Ah, remove the --config option from your configuration command line. Like this

```
./Configure linux-arc
```

**Comment by siabc123si** [comment]
May be i am trying multiple ways to solve the issue. (a) adding line in Configure file b) editing existing .conf to add "linux-arc" settings. c) adding new .conf file for "linux-arc"). To simplify let me follow one procedure as suggested by you and provide outcome of the same.

**Comment by levitte** [comment]
BTW, I am off to sleep now. I'll be back tomorrow.

**Comment by siabc123si** [comment]
Have a good sleep. Thanks alot for your precious time and effort.

**Comment by siabc123si** [comment]
As said tried:

./Configure linux-arc (with Configurations/linux-arc.conf and no changes in 10-main.conf and configure)
"
buildroot/build_arc/openssl-1.1.1$ ./Configure linux-arc
Configuring OpenSSL version 1.1.1 (0x1010100fL) for linux-arc
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   If you want to report a building issue, please include the   ***
***   output from this command:                                    ***
***                                                                ***
***     perl configdata.pm --dump                                  ***
***                                                                ***
**********************************************************************
"

configuration dump is here:
[linux-arc.log](https://github.com/openssl/openssl/files/2655243/linux-arc.log)

**Comment by kroeckx** [comment]
It says the Makefile is made, so what is the problem? What happens when you run make?

**Comment by siabc123si** [comment]
Okay great....i was thinking it as error.
Run "make" and it generated libssl.so file

I think i could run it now.......Thanks alot.

**Comment by mspncp** [comment]
> Okay great....i was thinking it as error.

Never mind, you are not the first one , see #7499  :-)

**Comment by siabc123si** [comment]
can i add those lines into Configure file ?... instead of new .conf file

**Comment by levitte** [comment]
> can i add those lines into Configure file ?... instead of new .conf file

No.

**Comment by siabc123si** [comment]
thanks levitte and others.
Now i want to add below flags to .conf file:
" 
 "linux-arc" => {
        # 32-bit build.
        inherit_from     => [ "linux-generic32", asm("arc_asm") ],
        CC               => "gcc",
        CFLAGS           => add(picker(default => "-Wall",
                                       release => "-O3 -fomit-frame-pointer")),
        cppflags         => threads("-D_REENTRANT"),
        lib_cppflags     => add("-DL_ENDIAN -DTERMIOS"),
        bn_ops           => "BN_LLONG",
        ex_libs          => add("-ldl"),
        dso_scheme       => "dlfcn",
        shared_target    => "linux-shared",
        shared_cflag     => "-fPIC",
        shared_extension => "-shared:.so.\$(SHLIB_MAJOR).\$(SHLIB_MINOR)",
    },
"
I edited "linux-arc" section of the linux-arc.conf as required. I could generate Make file. On running Make  following error is observed.

"
buildroot/build_arc/openssl-1.1.1$ make
Makefile:185: *** target pattern contains no `%'.  Stop.
"
is there any issue in required Linux-arc settings ?

**Comment by siabc123si** [comment]
Thanks to all of you for your valuable inputs in resolving this issue

**Comment by levitte** [comment]
You don't really need to add all those extra attributes.  The `inherit_from` attribute is for listing other config targets that yours inherits from, so if you go find `linux-generic32` in `Configurations/10-main.conf`, you can see what attributes are already there.  Basically, you've duplicated quite a lot where you need not.

The `asm("no_asm")` in your `inherit_from` is both wrong and unnecessary, just drop it.

As for `-shared`, you don't need to have it in there at all.  `shared_target => "linux-shared"` is enough to produce the magic.

Finally, the shared extension should be `shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)"`, but you do inherit that from `linux-generic32` anyway...

> I have a follow up question. Can i pass linux-arc.conf from a different folder/location as argument to ./Configure command ?

Yes.  Remember the `--config` option that you used earlier?  That's actually exactly the way to do it.  The only reason it didn't work earlier is that since the file was inside `Configurations/`, it ended up being loaded twice, something we simply haven't thought of (i.e. you uncovered a small bug).

**Comment by siabc123si** [comment]
Thanks levitte for detailed explanation.

I removed most of the duplicate settings after going through "linux-generic32" settings.

"....of (i.e. you uncovered a small bug)." --- i feel good by contributing in some way.

If i use  "--config=<>/linux-arc.conf" command. Do i need to copy 10-main.conf to same location ? or it will pick at run time from Configurations?

**Comment by siabc123si** [comment]
I am almost there. I could compile at system level (in linux OS) and generate final executable. But subsequent compilation fails with wierd reason (not related to openssl)

When i check, one thing is out of order. Files(eg: libcrypto.map) that have been generated by openssl-1.1.1 are copied to build folder (in my case buildroot/ directory) instead of being in buildroot/build_arc/openssl-1.1.1/ folder.

I suspect this is causing subsequent build failures. Anyway i need to remove openssl output from build directory (buildroot/).

**Comment by siabc123si** [comment]
HI all,

I am encountering follow up issue, compiling openssl-1.1.1 at system level. (openssl-1.1.1 standalone compilation is successful)

Error is as below:
"
rm -f test/x509aux
${LDCMD:-/usr/local/ARC/arcp1/uclibc/bin/arc-linux-uclibc-gcc} -Wa,--noexecstack -Wall -O3 -fomit-frame-pointer -L.  -L/home/<>/buildroot/build_arc/staging_dir/lib \
                -o test/x509aux test/x509aux.o \
                 test/libtestutil.a -lcrypto -ldl -ldl
make[5]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[4]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
# Work around openssl build bug to link libssl.so with libcrypto.so.
rm /home/<>/buildroot/build_arc/openssl-1.1.1/libssl.so.*.*.*
rm: cannot remove `/home/<>/buildroot/build_arc/openssl-1.1.1/libssl.so.*.*.*': No such file or directory
make[3]: [/home/<>/buildroot/build_arc/openssl-1.1.1/apps/openssl] Error 1 (ignored)
make MAKE="make -j1" CC=/usr/local/ARC/arcp1/uclibc/bin/arc-linux-uclibc-gcc -C /home/<>/buildroot/build_arc/openssl-1.1.1
make[4]: Entering directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make -j1 depend && make -j1 _all
make[5]: Entering directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[5]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[5]: Entering directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[5]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[4]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make -j5 CC=/usr/local/ARC/arcp1/uclibc/bin/arc-linux-uclibc-gcc INSTALL_PREFIX=/home/<>/buildroot/build_arc/staging_dir -C /home/<>/buildroot/build_arc/openssl-1.1.1 install
make[4]: Entering directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make depend && make _all
*** Installing development files
Cannot create directory /usr/lib/ssl/bin: No such file or directory
Cannot create directory /usr/lib/ssl/include: No such file or directory
Cannot create directory /usr/lib/ssl/lib: No such file or directory
make[4]: *** [install_runtime] Error 2
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [install_dev] Error 2
make[4]: *** [install_engines] Error 2
install ./apps/CA.pl -> /usr/lib/ssl/misc/CA.pl
make[5]: Entering directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
cp: cannot create regular file `/usr/lib/ssl/misc/CA.pl.new': Permission denied
make[4]: *** [install_ssldirs] Error 1
make[5]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[5]: Entering directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[5]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[4]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
make[3]: *** [/home/<>/buildroot/build_arc/staging_dir/lib/libcrypto.a] Error 2
make[3]: Leaving directory `/home/<>/buildroot'
make[2]: *** [do_buildroot] Error 2
make[2]: Leaving directory `/home/<>'
make[1]: *** [.first_run] Error 2
make[1]: Leaving directory `/home/<>'
make: *** [image] Error 2
"

Corresponding system level openssl.mk(buildroot/package/openssl/openssl.mk) file is as below:

"
$(OPENSSL_DIR)/.unpacked: $(DL_DIR)/$(OPENSSL_SOURCE)
        $(OPENSSL_CAT) $(DL_DIR)/$(OPENSSL_SOURCE) | tar -C $(BUILD_DIR) $(TAR_OPTIONS) -
        cp -fa package/openssl/linux-arc.conf $(OPENSSL_DIR)/Configurations
#       $(OPENSSL_DIR)/Configure linux-arc
        touch $(OPENSSL_DIR)/.unpacked

$(OPENSSL_DIR)/Makefile: $(OPENSSL_DIR)/.unpacked
        (cd $(OPENSSL_DIR); \
        CFLAGS="-DOPENSSL_NO_KRB5 -DOPENSSL_NO_IDEA -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_BF \
               -DOPENSSL_NO_CAST -DOPENSSL_NO_MD2 -DOPENSSL_NO_RIPEMD -DOPENSSL_NO_CAMELLIA -DOPENSSL_NO_ENGINE \
               -DOPENSSL_NO_CAMELLIA -DOPENSSL_NO_SSL2 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_TLSEXT -DSSL_OP_NO_TICKET -DOPENSSL_NO_DES \
               -DOPENSSL_NO_SSL1 -DOPENSSL_NO_SHA512 \
               $(TARGET_CFLAGS)" \
        PATH=$(TARGET_PATH) ./Configure linux-$(OPENSSL_TARGET_ARCH) --prefix=/usr/lib/ssl \
                --openssldir=/usr/lib/ssl -L$(STAGING_DIR)/lib -ldl \
                -I$(STAGING_DIR)/include $(OPENSSL_OPTS) no-threads \
                shared no-idea no-mdc2 no-rc5 no-bf no-cast no-md2 no-rc2\
        no-camellia no-hw no-sse2)

$(OPENSSL_DIR)/apps/openssl: $(OPENSSL_DIR)/Makefile
        $(MAKE1) CC=$(TARGET_CC) -C $(OPENSSL_DIR) depend all
        # Work around openssl build bug to link libssl.so with libcrypto.so.
        -rm $(OPENSSL_DIR)/libssl.so.*.*.*
        $(MAKE1) CC=$(TARGET_CC) -C $(OPENSSL_DIR)

$(STAGING_DIR)/lib/libcrypto.a: $(OPENSSL_DIR)/apps/openssl
        $(MAKE) CC=$(TARGET_CC) INSTALL_PREFIX=$(STAGING_DIR) -C $(OPENSSL_DIR) install
        cp -fa $(OPENSSL_DIR)/libcrypto.so* $(STAGING_DIR)/lib/
        chmod a-x $(STAGING_DIR)/lib/libcrypto.so.$(LIB_VER)
        (cd $(STAGING_DIR)/lib; ln -fs libcrypto.so.$(LIB_VER) libcrypto.so)

"
Required output is generated in "buildroot/build_arc/openssl-1.1.1", but system level compilation fails.
Please provide your valuable inputs.

Please let me know if i need to created another issue (ticket) for this failure

**Comment by levitte** [comment]
> ```
> rm /home/<>/buildroot/build_arc/openssl-1.1.1/libssl.so.*.*.*
> ```

Please make that:

```
rm /home/<>/buildroot/build_arc/openssl-1.1.1/libssl.so.*
```

We don't have 3-digit SONAMEs any more.

> ```
> Cannot create directory /usr/lib/ssl/bin: No such file or directory
> Cannot create directory /usr/lib/ssl/include: No such file or directory
> Cannot create directory /usr/lib/ssl/lib: No such file or directory
> ```

Hmmm, do you have permission to create those directories?

> ```
> cp: cannot create regular file `/usr/lib/ssl/misc/CA.pl.new': Permission denied
> ```

Oh yeah, that does it, you need to check your permissions.

**Comment by siabc123si** [comment]
Thanks levitte.

"....do you have permission to create those directories?" ....yes i guess.Earlier i used to compile openssl-1.0.2k and never had issues.

**Comment by siabc123si** [comment]
error after changing"libssl.so.*.*.* to libssl.so.*"

"
rm -f test/uitest
${LDCMD:-/usr/local/ARC/arcp1/uclibc/bin/arc-linux-uclibc-gcc} -Wa,--noexecstack -Wall -O3 -fomit-frame-pointer -L.  -L/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/staging_dir/lib \
                -o test/uitest test/uitest.o \
                 apps/libapps.a -lssl test/libtestutil.a -lcrypto -ldl -ldl
make[5]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
make[4]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
make -j5 CC=/usr/local/ARC/arcp1/uclibc/bin/arc-linux-uclibc-gcc INSTALL_PREFIX=/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/staging_dir -C /home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1 install
make[4]: Entering directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
make depend && make _all
*** Installing development files
Cannot create directory /usr/lib/ssl/include: No such file or directory
Cannot create directory /usr/lib/ssl/lib: No such file or directory
make[4]: *** [install_engines] Error 2
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [install_dev] Error 2
Cannot create directory /usr/lib/ssl/bin: No such file or directory
make[4]: *** [install_runtime] Error 2
make[5]: Entering directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
install ./apps/CA.pl -> /usr/lib/ssl/misc/CA.pl
cp: cannot create regular file `/usr/lib/ssl/misc/CA.pl.new': Permission denied
make[4]: *** [install_ssldirs] Error 1
make[5]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
make[5]: Entering directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
make[5]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
make[4]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/openssl-1.1.1'
make[3]: *** [/home/psirisilla/p4/bbic4_main2_g/buildroot/build_arc/staging_dir/lib/libcrypto.a] Error 2
make[3]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g/buildroot'
make[2]: *** [do_buildroot] Error 2
make[2]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g'
make[1]: *** [.first_run] Error 2
make[1]: Leaving directory `/home/psirisilla/p4/bbic4_main2_g'
make: *** [image] Error 2
"

**Comment by siabc123si** [comment]
Error after moving "libssl.so.*.*.* to libssl.so.*"

"
libtool: install: warning: remember to run `libtool --finish /lib'
Warning! target no_asm doesn't exist!
Cannot create directory /usr/lib/ssl/lib: No such file or directory
Cannot create directory /usr/lib/ssl/include: No such file or directory
make[4]: *** [install_engines] Error 2
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [install_dev] Error 2
Cannot create directory /usr/lib/ssl/bin: No such file or directory
make[4]: *** [install_runtime] Error 2
cp: cannot create regular file `/usr/lib/ssl/misc/CA.pl.new': Permission denied
make[4]: *** [install_ssldirs] Error 1
make[3]: *** [/home/<>/buildroot/build_arc/staging_dir/lib/libcrypto.a] Error 2
make[2]: *** [do_buildroot] Error 2
make[1]: *** [.first_run] Error 2
make: *** [image] Error 2
"
Not sure how to get "permissions" to create a folder.

**Comment by levitte** [comment]
I have *no* idea why it talks about the `no_asm` target.

**Comment by siabc123si** [comment]
i have "no_asm" in my linux_arc.conf file. let me remove it and compile

**Comment by siabc123si** [comment]
Found one issue in our make file:
INSTALL_PREFIX is replaced with DESTDIR in openssl-1.1.1. Replacing it helped in creating destination folder at proper location.

**Comment by siabc123si** [comment]
Now next error is as below

"
make[4]: Leaving directory `/home/<>/buildroot/build_arc/openssl-1.1.1'
cp -fa /home/<>/buildroot/build_arc/openssl-1.1.1/libcrypto.so* /home/<>/buildroot/build_arc/staging_dir/lib/
chmod a-x /home/<>/buildroot/build_arc/staging_dir/lib/libcrypto.so.1.1
(cd /home/<>/buildroot/build_arc/staging_dir/lib; ln -fs libcrypto.so.1.1 libcrypto.so)
(cd /home/<>/buildroot/build_arc/staging_dir/lib; ln -fs libcrypto.so.1.1 libcrypto.so.0)
cp -fa /home/<>/buildroot/build_arc/openssl-1.1.1/libssl.so* /home/<>/buildroot/build_arc/staging_dir/lib/
chmod a-x /home/<>/buildroot/build_arc/staging_dir/lib/libssl.so.1.1
(cd /home/<>/buildroot/build_arc/staging_dir/lib; ln -fs libssl.so.1.1 libssl.so)
(cd /home/<>/buildroot/build_arc/staging_dir/lib; ln -fs libssl.so.1.1 libssl.so.0)
mkdir -p /home/<>/buildroot/build_arc/root/usr/lib/ssl
cp -fa /home/<>/buildroot/build_arc/staging_dir/lib/libcrypto.so* /home/<>/buildroot/build_arc/root/usr/lib/
cp -fa /home/<>/buildroot/build_arc/staging_dir/lib/libssl.so* /home/<>/buildroot/build_arc/root/usr/lib/
cp -fa /home/<>/buildroot/build_arc/staging_dir/bin/openssl  /home/<>/buildroot/build_arc/root/bin/
cp: cannot stat `/home/<>/buildroot/build_arc/staging_dir/bin/openssl': No such file or directory
make[3]: *** [/home/<>/buildroot/build_arc/root/usr/lib/libcrypto.so.1.1] Error 1

"
Had "buildroot/build_arc/staging_dir/bin/openssl" this location is changed in openssl-1.1.1 ? or it related to our make file only ?

**Comment by siabc123si** [comment]
i fixed above one. Follow up issue is in curl:
"
qh_curl_ws.c:14:25: error: openssl/sha.h: No such file or directory
/usr/local/ARC/arcp1/uclibc/bin/arc-linux-uclibc-gcc -Os -pipe  -I/home/<>/buildroot/build_arc/staging_dir/include -I/usr/local/ARC/arcp1/uclibc/arc-linux-uclibc/include -I/home/<>/buildroot/package/qharvest/qharvestd -DJSONC_COMPAT -DCONF_FILE_DEFAULT=/mnt/jffs2/qharvestd.conf -DHAVE_FW_UPGRADE=1 -DHAVE_SONIQ=1 -I/home/<>/buildroot/../buildroot/package/qcsapi/qcsapi-1.0.1/ -I/home/<>/buildroot/.. -I/home/<>/buildroot/../include -I/home/<>/buildroot/../drivers/include/shared -I/home/<>/buildroot/../buildroot/package/pktlogger_d/pktlogger_d -DHAVE_PKTLOGGER=1 -DHAVE_PTY=1 -DHAVE_ZLIB=1 -DHAL_QCSAPI -Werror -Wall -DVERSION=1.33.1 -DCOMMIT_HASH=35c0a22 -std=gnu99 -ffunction-sections -fdata-sections -pipe -Wall -fPIC -c HAVE_SCAN_BW.c 2>/dev/null && echo "#define HAVE_SCAN_BW 1" >> qcsapi_caps.h || echo "#define HAVE_SCAN_BW 0" >> qcsapi_caps.h
cc1: warnings being treated as errors
qh_curl_ws.c: In function âws_connect_cbâ:
qh_curl_ws.c:556: warning: implicit declaration of function âSHA1â
make[4]: *** [qh_curl_ws.o] Error 1
make[4]: *** Waiting for unfinished jobs....
"
do i need to upgrade curl tool ?

**Comment by siabc123si** [comment]
In openssl-1.1.1 lot of generic files(sha.h, md5.herr.h,etc) are misplaced in "buildroot/build_arc/staging_dir/lib/ssl/include/openssl/" folder whereas in 1.0.2k these are located in " buildroot/build_arc/staging_dir/include/openssl/".

One change i did to our openss;.mk is as below:
cp -fa $(STAGING_DIR)/lib/ssl/bin/openssl  $(TARGET_DIR)/bin/ ---- openssl-1.1.1
cp -fa $(STAGING_DIR)/bin/openssl  $(TARGET_DIR)/bin/ ------------- openssl-1.0.2k

but not sure how above line can impact /include/ directory contents

**Comment by siabc123si** [comment]
At last all my issues are fixed. Thanks levitte for ur prompt response.

**Comment by levitte** [comment]
I don't know where you imagine that OpenSSL installs stuff, so let me clarify that bit.

Your `--prefix` configuration value ends up in `$(INSTALL_TOP)` in your Makefile, so taken in 1.1.0 terms, here's where things are installed:

`$(DESTDIR)$(INSTALL_TOP)/bin` for applications
`$(DESTDIR)$(INSTALL_TOP)/lib` for libraries
`$(DESTDIR)$(INSTALL_TOP)/include/openssl` for header files

It's actually the exact same for 1.0.2, just that we use `$(INSTALL_PREFIX)` instead of `$(DESTDIR)` there, as you discovered.

So with your `--prefix=/usr/lib/ssl`, and your `DESTDIR=$(STAGING_DIR)` (`INSTALL_PREFIX=$(STAGING_DIR)` for 1.0.2), here's where things *should* end up:

`$(STAGING_DIR)/usr/lib/ssl/bin/openssl`
`$(STAGING_DIR)/usr/lib/ssl/lib/libcrypto.so.*`
`$(STAGING_DIR)/usr/lib/ssl/lib/libcrypto.so`
`$(STAGING_DIR)/usr/lib/ssl/lib/libssl.so.*`
`$(STAGING_DIR)/usr/lib/ssl/lib/libssl.so`
`$(STAGING_DIR)/usr/lib/ssl/include/openssl/*.h`

**Comment by siabc123si** [comment]
--prefix=/usr/lib/ssl is also wrong ( earlier it was set to --prefix=/ but i modified it wrongly). on correcting to "--prefix=/" everything went smooth.

Thanks again levitte for your detailed explanation.
i donit know how to close this bug.

**Comment by levitte** [comment]
Closing it
