### ISSUE TITLE
tsget files announce (un)"released" yet version / master 2018-12-10

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#7861]
After update one of my build environments to current master (2018-12-10) I note that some differences. Let see one of them:

``` diff
diff -urN master-20181118/ssl/misc/tsget.pl master/ssl/misc/tsget.pl
--- master-20181118/ssl/misc/tsget.pl	2018-11-18 21:46:36.387422695 +0200
+++ master/ssl/misc/tsget.pl	2018-12-10 20:16:39.560247257 +0200
....
@@ -47,7 +47,7 @@
     $curl->setopt(CURLOPT_VERBOSE, 1) if $options{d};
     $curl->setopt(CURLOPT_FAILONERROR, 1);
     $curl->setopt(CURLOPT_USERAGENT,
-        "OpenTSA tsget.pl/openssl-1.1.2-dev");
+        "OpenTSA tsget.pl/openssl-3.0.0");
 
     # Options for POST method.
     $curl->setopt(CURLOPT_UPLOAD, 1);
```

I'm not sure that new "version" scheme should allows such situation - user agent from version not released yet.
It is more logical versions before "release" to be marked as alpha or prealpha and etc. if "dev" suffix is not acceptable.

**Comment by levitte** [comment]
(please learn MarkDown, I'm tiring of post-editing your texts :wink:)

**Comment by levitte** [comment]
Please see #7866
