### ISSUE TITLE
remove definition of OPENSSL_VERSION_NUMBER

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#7863]
OPENSSL_VERSION_NUMBER is deprecated in 4+ but function in 3+.
quote from see opensslv.h
```
....
# if !OPENSSL_API_4
/* Synthesize OPENSSL_VERSION_NUMBER with the layout 0xMNN00PPSL */
...
#  define OPENSSL_VERSION_NUMBER        \
....
```

quote from cversion.c:
```
....
#if !OPENSSL_API_3
unsigned long OpenSSL_version_num(void)
{
    return OPENSSL_VERSION_NUMBER;
}
#endif
....
```

I cannot see reason for such difference.
Please synchronize versions - 3 is fine with me.

**Comment by richsalz** [comment]
Put your literal code blocks inside three backtick literals.  Like this:
```
 ```
   do this
 ```
```

**Comment by richsalz** [comment]
Put your literal text inside three backticks one a line by themselves.

**Comment by levitte** [comment]
I agree that the difference is unnerving.  This has already been noticed during the debate in #7853 (feel free to share an opinion there)

**Comment by petrovr** [comment]
Now I would like to change request  - from "deprecation of definition OPENSSL_VERSION_NUMBER and function OpenSSL_version_num() / master 2018-12-10" to remove definition of OPENSSL_VERSION_NUMBER .

**Comment by petrovr** [comment]
So the reason is that format of macro definition is changed.
As result of this third party scrips(!) are not able to find  openssl version number.

Remark: Only executable could check properly version number, i.e. tools  has to perform compilation and environment to allows execution.

**Comment by petrovr** [comment]
The similar impact of changes could be seen in script util/mktar.sh - due to change of format script does not work.

**Comment by levitte** [comment]
You're quite right about util/mktar.sh, thanks for the notification.  I've submitted #9745 to fix it, feel free to check it out.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> You're quite right about util/mktar.sh, thanks for the notification.  I've submitted #9745 to fix it, feel free to check it out.
> 

util/mktar.sh is not real issue at is part of mainstream code (when is 
need it will adjusted to current code base).

Иmagine that this is third party software that uses definition of FOO - 
change of value format requires changes in external software 
nevertheless if is marked as deprecated or not.

Real case is this one:
Documentation:
   https://cmake.org/cmake/help/latest/module/FindOpenSSL.html
Code:

https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindOpenSSL.cmake#L350

Regards
Roumen Petrov

**Comment by levitte** [comment]
Well, I did think of external parties as well, so if you look at #9745, you will notice a new script that extracts version information in a uniform way regardless of (currently released) version.  Hopefully, programs such as cmake's `FindOpenSSL` will find that useful.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> Well, I did think of external parties as well, so if you look at #9745, you will notice a new script that extracts version information in a uniform way regardless of (currently released) version.  Hopefully, programs such as cmake's `FindOpenSSL` will find that useful.
> 

Script is not usable - for third party software it adds extra 
dependencies to the script language(at build time).
In such case we could binary (executable) as openssl version outputs 
required information. Unfortunately is not usable in cross-platform build.


Regards,
Roumen Petrov

**Comment by kroeckx** [comment]
On Sun, Sep 01, 2019 at 04:32:36AM -0700, Румен Петров wrote:
> 
> Script is not usable - for third party software it adds extra 
> dependencies to the script language(at build time).
> In such case we could binary (executable) as openssl version outputs 
> required information. Unfortunately is not usable in cross-platform build.

To build software that wants to link to openssl, the
/usr/bin/openssl binary is not needed, and at least in Debian it's
normally not present.

**Comment by levitte** [comment]
Aha, gotcha.  It would be better with a generated script with just the values, created alongside `openssl.pc` etc.  Sure, that can be done as well

**Comment by petrovr** [comment]
Generation of another (new) file with information will note resolve issue with third party software.
For instance CMAKE still will fail to detect OpenSSL.
Let assume that CMAKE enhance check for version to detect new format.  This is not security issue and more or less will not be back-ported. So users of "old" cmake will still impacted.


But I start to think what if is changed "direction" in hypothetical script - do not export but to import (generate).


What is a script using input from command line or file to generate include/openssl/opensslv.h and to propagate to other files if necessary. For instance "version" is used in generated pkg-config files.
Also script could update change log  (CHANGES) with version and date.

**Comment by levitte** [comment]
It's true that we could go that way...  A lot of other types of projects have the version number somewhere in configuration data, and generate whatever they need for presentation etc (a notable example is autoconf, where the version of the project is defined by `AC_INIT`), and cmake has a similar mechanism (although not as mandatory), as part of the [project command](https://cmake.org/cmake/help/v3.15/command/project.html).

We could simply add a VERSION statement in `build.info`...  or add a version number directly to `$config{version}`.  I'm not sure which I prefer...

Either way, we will have to tweak our release scripts...

**Comment by petrovr** [comment]
Richard Levitte wrote:
> ....(a notable example is autoconf, where the version of the project is defined by `AC_INIT`)...

Yes, automake recommend file "version.m4" with M4-macros suitable for 
AC_INIT and etc. Also it takes care for dependency and distribution of 
that file.
If project uses autoheader this will produce a number of PACKAGE_* 
definitions in configuration header (config.h by default).


But not everything is generated from configuration and build systems. 
For instance in rpm-spec files also has version information.
At time of release configure.ac (indirectly from version.m4 if used) and 
other files (for instance rpm-spec) has to be updated.

Next step is automation of release process: "prepare version 1.2.3.4 
....", where prepare is script.


Regards,
Roumen

**Comment by petrovr** [comment]
Obsoleted by #10203
