### ISSUE TITLE
copyright years after switch of license

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#7864]
After update one of my build environments to current master (2018-12-10) I note that in some files copyright years remain as before, i.e. YYYY-2016, or 2016, and etc.

Please could you (OpenSSL team) check what should be in copyright statement after license change.

**Comment by richsalz** [comment]
File not edited do not get the copyright updated.  Please post specifics if you see errors, otherwise I think this can be closed.

**Comment by petrovr** [comment]
Rich Salz wrote:
> File not edited do not get the copyright updated.  Please post specifics if you see errors, otherwise I think this can be closed.
> 
> 

Actually file is changed like this:
diff -urN master-20181118/include/openssl/aes.h master/include/openssl/aes.h
--- master-20181118/include/openssl/aes.h	2018-11-18 21:46:35.034431938 
+0200
+++ master/include/openssl/aes.h	2018-12-10 20:16:38.197254735 +0200
@@ -1,7 +1,7 @@
  /*
   * Copyright 2002-2016 The OpenSSL Project Authors. All Rights Reserved.
   *
- * Licensed under the OpenSSL license (the "License").  You may not use
+ * Licensed under the Apache License 2.0 (the "License").  You may not use
   * this file except in compliance with the License.  You can obtain a copy
   * in the file LICENSE in the source distribution or at
   * https://www.openssl.org/source/license.html

**Comment by mspncp** [comment]
I think this is a special case, because practically every file got modified by the license change. But that does not mean that we want to update all copyright years now.

**Comment by mattcaswell** [comment]
My guess is that the `do-copyright-year` script in the tools repo will update all of these next time we run it.

**Comment by mspncp** [comment]
> My guess is that the do-copyright-year script in the tools repo will update all of these next time we run it.

This should not have an influence on the OMC's decision, because the effort to modify the script to skip the license change commit(s) can be neglected. More important are the questions whether updating the copyright years of all files is desired by the OMC (which was not the case back in https://github.com/openssl/openssl/pull/5027#issuecomment-355809064) and/or whether it might be required for legal reasons (because of the relicensing), as indicated by @richsalz.
