### ISSUE TITLE
EVP_PKEY_size should be declared to take a const parameter

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#7872]
````
int EVP_PKEY_size(EVP_PKEY *pkey)
{
    if (pkey && pkey->ameth && pkey->ameth->pkey_size)
        return pkey->ameth->pkey_size(pkey);
    return 0;
}
````
Note that `pkey->ameth->pkey_size()` is already declared to take a const param.

**Comment by levitte** [comment]
Any reasonable constification gets a +1 from me...  and there are oh so many more spots where we should constify, I'm surprised you targeted one function only!

**Comment by mattcaswell** [comment]
> I'm surprised you targeted one function only!

Only 'cos I noticed this one specifically while reviewing a PR

**Comment by shreyabhandare** [comment]
i clones the master and trying to make changes but the files are set with RO option?

**Comment by mattcaswell** [comment]
Hmmm...that's odd. How did you clone?

**Comment by shreyabhandare** [comment]
used https

**Comment by shreyabhandare** [comment]
nevermind, when i opened it directly rather than cscope it worked, sorry for the bother

**Comment by shreyabhandare** [comment]
If i want to start reading the code base, where should i begin?

**Comment by richsalz** [comment]
It is better to ask the question on the mailing list, https://mta.openssl.org for details on joining openssl-users

**Comment by levitte** [comment]
Oy...  where to start reading.  I remember asking myself the same question about the predecessor (SSLeay) more than 20 years ago.  I feel you, @shreyabhandare, that's *not* an easy question.

However, you could start with what this very issue is concerned with, a function called `EVP_PKEY_size`, which you can find using git commands:

```
git grep EVP_PKEY_size
```

But to get back to your question, I often start with the public stuff when I get myself into a new project.  Manuals and APIs.  For manuals, `doc/man7/crypto.pod` and `doc/man7/ssl.pod` could be a starting point.  They can be viewed directly or with `perldoc`.

**Comment by levitte** [comment]
Also, getting acquainted with our build system, start with INSTALL

**Comment by mattcaswell** [comment]
My advice would be to find an area to work on (look at the issues and choose one you think you might be able to take on). Then try and learn what you can about that one area. Read the man pages; read the source around that area. It might take you a long time to get your head around it, but once you understand one area you can start expanding your knowledge and learn more parts of the code.

That's how I started. I'm still doing it now. There are still parts of the code that are a complete mystery to me ;-)

**Comment by shreyabhandare** [comment]
thanks Richard, Matt, time to get my hands dirty! :)

**Comment by DDvO** [comment]
At least for EVP_PKEY_size() the constification has meanwhile been done:
```
47ec2367ebf include/openssl/evp.h (Shreya Bhandare     2018-12-13 22:59:10 +0530 1052) int EVP_PKEY_size(const EVP_PKEY *pkey);
```

**Comment by mattcaswell** [comment]
Great. Closing.
