### ISSUE TITLE
ARM thumb: error: out of range immediate fixup value on Clang >= 5

### ISSUE THREAD

**Issue by kleest** [openssl/openssl#7878]
Commit: 6de98b4fb6265f8a4b2e5b599d6714ff937dca6b
Android NDK Version: r18b

[config_android.log](https://github.com/openssl/openssl/files/2669412/config_android.log)
[config_rpi.log](https://github.com/openssl/openssl/files/2669413/config_rpi.log)

Environment:
```
ANDROID_NDK=/android/ndk
ANDROID_PLATFORM=android-27
PATH=/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:/android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

$ which clang
/android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin//clang

$ configdata.pm --dump
<see attached file>
```

Error:
```
clang  -Icrypto -I. -Icrypto/include -Iinclude  -fPIC -pthread  -target thumbv7-linux-androideabi -gcc-toolchain /android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/android/ndk/platforms/android-28/arch-arm -Wa,--noexecstack -Qunused-arguments -Wall -O3 -mthumb -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -D__ANDROID_API__=28 -isystem /android/ndk/sysroot/usr/include/arm-linux-androideabi -isystem /android/ndk/sysroot/usr/include -DNDEBUG -D__ARM_MAX_ARCH__=7 -c -o crypto/poly1305/libcrypto-lib-poly1305-armv4.o crypto/poly1305/poly1305-armv4.S
crypto/poly1305/poly1305-armv4.S:168:2: error: out of range immediate fixup value
 addeq r12,r11,#(poly1305_emit-.Lpoly1305_init)
 ^
crypto/poly1305/poly1305-armv4.S:169:2: error: out of range immediate fixup value
 addne r12,r11,#(poly1305_emit_neon-.Lpoly1305_init)
 ^
crypto/poly1305/poly1305-armv4.S:171:2: error: out of range immediate fixup value
 addne r11,r11,#(poly1305_blocks_neon-.Lpoly1305_init)
 ^
Makefile:9912: recipe for target 'crypto/poly1305/libcrypto-lib-poly1305-armv4.o' failed
make[1]: *** [crypto/poly1305/libcrypto-lib-poly1305-armv4.o] Error 1
```

It seems, that compiling with the `-mthumb` option leads to the calculated immediate [being out-of-range](https://reviews.llvm.org/D15442). Without that option, compilation is working fine. Also, with Android NDK r16b that file compiles fine but the build fails at the linking stage (unrelated to this issue).  
When natively compiling on a Raspberry PI (`./config -mthumb`) with LLVM 6.0.0, the same error appears ([config_rpi.log](https://github.com/openssl/openssl/files/2669413/config_rpi.log)), so this is not limited to cross-compilation or Android.

At this point, I do not know if this is actually an issue of OpenSSL, an invalid configuration (is arm-v7a together with `-mthumb` actually supported?) or a bug in LLVM.

**Comment by kervala** [comment]
I have the same issue :(

[ 92%] Building C object crypto/CMakeFiles/crypto.dir/__/asm/poly1305-armv4.S.o
/home/buildslave/quick-build-android-openssl/build_armeabi-v7a_default/asm/poly1305-armv4.S:168:2: error: out of range immediate fixup value
 addeq r12,r11,#(poly1305_emit-.Lpoly1305_init)
 ^
/home/buildslave/quick-build-android-openssl/build_armeabi-v7a_default/asm/poly1305-armv4.S:169:2: error: out of range immediate fixup value
 addne r12,r11,#(poly1305_emit_neon-.Lpoly1305_init)
 ^
/home/buildslave/quick-build-android-openssl/build_armeabi-v7a_default/asm/poly1305-armv4.S:171:2: error: out of range immediate fixup value
 addne r11,r11,#(poly1305_blocks_neon-.Lpoly1305_init)

**Comment by mciarcia-nav** [comment]
I have similar issue with ndk r19:
openssl/crypto/aes/asm/aes-armv4.S:358:2: error: out of range immediate fixup value
 sub r10,r3,#AES_encrypt-AES_Te @ Te
 ^
openssl/crypto/aes/asm/aes-armv4.S:994:2: error: out of range immediate fixup value
 sub r10,r3,#AES_decrypt-AES_Td @ Td

only for arm-v7a ABI

**Comment by levitte** [comment]
Do the changes in #8160 make a difference? That PR has been closed (I believe it's prematurely), but no matter, please have a look.

**Comment by mciarcia-nav** [comment]
That PR doesn't make difference. I turned off the assembly part which looks old asm code for arm v4 architecture (https://github.com/openssl/openssl/blob/master/crypto/aes/asm/aes-armv4.pl#L17). Wondering if it could really provide any benefit to the build using arm v4 assembly with arm v7 CPU.

**Comment by kleest** [comment]
Same problem when applying the PR on top of 6de98b4fb6265f8a4b2e5b599d6714ff937dca6b with identical environment and configuration.

**Comment by gjasny** [comment]
Adding `-no-integrated-as` to the compile command for that file works for me.

**Comment by amrox** [comment]
Same issue with OpenSSL 1.1.1d Android NDK Version: r20

I was able to get it to work by turning off thumb support  via `-DANDROID_ARM_MODE=arm` https://developer.android.com/ndk/guides/cmake#android_arm_mode

**Comment by xajik** [comment]
Having same problem, compiling with **Rust**:
`
openssl = {version = "0.10", features = ["vendored"]}
openssl-sys = "0.9"
`

Works fine with:
`
cargo build --target aarch64-linux-android --release
cargo build --target i686-linux-android --release
`

And for the: 
`cargo build --target armv7-linux-androideabi --release`
Crash: 
`
--- stderr
clang90: error: no input files
crypto/poly1305/poly1305-armv4.S:168:2: error: out of range immediate fixup value
 addeq r12,r11,#(poly1305_emit-.Lpoly1305_init)
 ^
crypto/poly1305/poly1305-armv4.S:169:2: error: out of range immediate fixup value
 addne r12,r11,#(poly1305_emit_neon-.Lpoly1305_init)
 ^
crypto/poly1305/poly1305-armv4.S:171:2: error: out of range immediate fixup value
 addne r11,r11,#(poly1305_blocks_neon-.Lpoly1305_init)
 ^
make[1]: *** [Makefile:4253: crypto/poly1305/poly1305-armv4.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:174: build_libs] Error 2
`

**Comment by Havoc24k** [comment]
@xajik Please see answer here https://github.com/briansmith/ring/issues/798#issuecomment-499744299

I changed the .cargo/config target linker to another version like `armv7a-linux-androideabi28-clang`

```
[target.armv7-linux-androideabi]
ar = "/home/havoc24k/projects/security-module/rust/client-android/NDK/arm/bin/arm-linux-androideabi-ar -marm"
linker = "/home/havoc24k/projects/security-module/rust/client-android/NDK/arm/bin/armv7a-linux-androideabi28-clang"
```

and also run the cargo build command like this

`CC=armv7a-linux-androideabi28-clang cargo build --target armv7-linux-androideabi --release`

And I was able to generate the `.so` file for ARMv7 as well.

**Comment by oleavr** [comment]
I've submitted a minimal fix for this issue in #13757.

**Comment by tormentous** [comment]
Sorry for the bump. How do you set this in the Android.mk file?

[armeabi-v7a] Compile thumb : crypto_static <= aes-armv4.S
/Users/admin/strongswan-android/strongswan/src/frontends/android/app/src/main/jni/openssl/crypto/aes/asm/aes-armv4.S:358:2: error: out of range immediate fixup value
sub r10,r3,#AES_encrypt-AES_Te @ Te
^
/Users/admin/android/strongswan/src/frontends/android/app/src/main/jni/openssl/crypto/aes/asm/aes-armv4.S:994:2: error: out of range immediate fixup value
sub r10,r3,#AES_decrypt-AES_Td @ Td
^
make: *** [/Users/admin/adt-bundle-mac-x86_64-20140702/sdk/ndk/22.1.7171670/build/core/build-binary.mk:477: /Users/admin/strongswan-android/strongswan/src/frontends/android/app/src/main/obj/local/armeabi-v7a/objs/crypto_static/crypto/aes/asm/aes-armv4.o] Error 1

> @xajik Please see answer here [briansmith/ring#798 (comment)](https://github.com/briansmith/ring/issues/798#issuecomment-499744299)
> 
> I changed the .cargo/config target linker to another version like `armv7a-linux-androideabi28-clang`
> 
> ```
> [target.armv7-linux-androideabi]
> ar = "/home/havoc24k/projects/security-module/rust/client-android/NDK/arm/bin/arm-linux-androideabi-ar -marm"
> linker = "/home/havoc24k/projects/security-module/rust/client-android/NDK/arm/bin/armv7a-linux-androideabi28-clang"
> ```
> 
> and also run the cargo build command like this
> 
> `CC=armv7a-linux-androideabi28-clang cargo build --target armv7-linux-androideabi --release`
> 
> And I was able to generate the `.so` file for ARMv7 as well.

**Comment by t8m** [comment]
Fixed already.
