### ISSUE TITLE
curve25519.c:67:1: error: initializer element is not constant  static const int64_t kTop39Bits = ~kBottom25Bits;  ^

### ISSUE THREAD

**Issue by lastchoice** [openssl/openssl#788]
SDIR="\"/usr/local/lib/engines\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack -fPIC   -c -o curve25519.o curve25519.c
curve25519.c:67:1: error: initializer element is not constant
 static const int64_t kTop39Bits = ~kBottom25Bits;
 ^
curve25519.c:68:1: error: initializer element is not constant
 static const int64_t kTop38Bits = ~kBottom26Bits;
 ^
make[2]: *** [curve25519.o] Error 1
make[2]: Leaving directory `/home/walsh/honey/openssl-master/crypto/ec'
make[1]: *** [subdirs] Error 1
make[1]: Leaving directory `/home/walsh/honey/openssl-master/crypto'
make: *** [build_crypto] Error 1

**Comment by ekasper** [comment]
https://github.com/openssl/openssl/pull/789

**Comment by ekasper** [comment]
And fixed.

**Comment by RJPercival** [comment]
Thanks for fixing that so quickly.
