### ISSUE TITLE
Typo in man files for X509_NAME_ENTRY_get_object

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#7883]
https://github.com/openssl/openssl/blob/4746f25ac62e5bbdc07eedcec9c9a27547577141/doc/man3/X509_NAME_ENTRY_get_object.pod#L54-L56

"X509_NAME_ENTRY_create_by_txt(), X509_NAME_ENTRY_create_by_NID(), and X509_NAME_ENTRY_create_by_OBJ() create and return an"

Line stops abruptly.

**Comment by mspncp** [comment]
This seems to be a copy&paste leftover from the DESCRIPTION section

https://github.com/openssl/openssl/blob/4746f25ac62e5bbdc07eedcec9c9a27547577141/doc/man3/X509_NAME_ENTRY_get_object.pod#L44-L46

It probably just needs to be removed. The RETURN VALUE section already contains the necessary documentation.

https://github.com/openssl/openssl/blob/4746f25ac62e5bbdc07eedcec9c9a27547577141/doc/man3/X509_NAME_ENTRY_get_object.pod#L81-L83
 
Would you like to create a pull request for it or shall I do it?

**Comment by mspncp** [comment]
Fix is in #7884
