### ISSUE TITLE
Streaming XOF output, please?

### ISSUE THREAD

**Issue by nmathewson** [openssl/openssl#7894]
Right now, when you call EVP_DigestFinalXOF, you invalidate the EVP_MD_CTX object.  This means that it's impossible to use an XOF in a streaming mode, as you sometimes want for very long XOF outputs.  (We use them when we want to replace our PRNG with something deterministic for testing, and they're also useful for other applications.)

I suggest a new EVP_DigestSqueezeXOF function, with arguments and return values as for EVP_DigestFinalXOF, except that it may be called more than once, and that the calls yield successive bytes from the XOF stream.

If this proposal is acceptable, then I'd be able to write a patch, though I would appreciate guidance about how to structure it and fit it into the EVP abstraction.

**Comment by kroeckx** [comment]
Do you know why EVP_DigestFinalXOF() can't be called again? Is
there a reason we can't just change that?

**Comment by nmathewson** [comment]
I may be wrong here, since I don't know the internals so well:

My understanding was that EVP_DigestFinalXOF calls the ctx->digest->cleanup() function, and calls  OPENSSL_cleanse on the ctx->md_data field of the EVP_MD_CTX, to free whatever it allocated and wipe it clean.  But if it didn't do that, then there would currently (IIUC) be no function that the user needed to invoke that would actually make sure that cleanup and OPENSSL_cleanse() got called, I thought.

Or would EVP_MD_CTX_reset() [called from EVP_MD_CTX_free()] be sufficient to ensure that cleanup and cleanse are invoked?

**Comment by kroeckx** [comment]
I expect the free call to properly clean up, and consider it a bug if it doesn't.

**Comment by nmathewson** [comment]
So if I understand correctly, you're saying that you'd prefer a patch that would make EVP_DigestFinalXOF() safe to call repeatedly, and no new API?  If so I can try to do that.

**Comment by kroeckx** [comment]
Yes, I prefer that.

**Comment by nmathewson** [comment]
I've added a draft PR as #7921 , with open questions.  It passes my own tests, at least.
