### ISSUE TITLE
Openssl 1.1.1a fails 04-test_err.t test with WIN64 debug build

### ISSUE THREAD

**Issue by mshaw1990** [openssl/openssl#7897]
```
nmake V=1 TESTS=test_err test

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.
exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Stud
io 14.0\VC\BIN\amd64\nmake.exe" /                   _tests

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        mkdir .\test\test-runs
A subdirectory or file .\test\test-runs already exists.
        set SRCTOP=.
        set BLDTOP=.
        set RESULT_D=.\test\test-runs
        set PERL=C:\Perl64\bin\perl.exe
        set OPENSSL_ENGINES=C:\repo\git_co\vega_fw44\02_src\crypto\model\openssl-1.1.1a\engines
        set OPENSSL_DEBUG_MEMORY=on
        "C:\Perl64\bin\perl.exe" ".\test\run_tests.pl" test_err
test\recipes\04-test_err.t ..
1..1
    # Subtest: ..\errtest.exe
    1..1
    # ERROR: (int) 'GetLastError() == ERROR_INVALID_FUNCTION' failed @ test\errtest.c:27
    # [0] compared to [1]
    not ok 1 - preserves_system_error
..\errtest.exe => 1
not ok 1 - running errtest
#   Failed test 'running errtest'
#   at C:\repo\git_co\vega_fw44\02_src\crypto\model\openssl-1.1.1a\util\perl/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
test\recipes\04-test_err.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  1 wallclock secs ( 0.02 usr +  0.01 sys =  0.03 CPU)
Result: FAIL
NMAKE : fatal error U1077: 'C:\Perl64\bin\perl.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by mattcaswell** [comment]
Please try testing with the head of the OpenSSL_1_1_1-stable branch. There was a recent fix that (may) solve this issue (see commit 99992ad2201).

**Comment by levitte** [comment]
Thanks for the analysis.  That means that the issue sits in the order of these lines:

https://github.com/openssl/openssl/blob/9a3b5b766421b7ed9df859956d44fcbe52c2dd82/crypto/err/err.c#L257-L258

I.e. the `err_load_strings` call may still change the system error because of possible `malloc()` calls.

@mattcaswell, can you recall why those two lines aren't in the other order, i.e. system error resetting last?

**Comment by mattcaswell** [comment]
> @mattcaswell, can you recall why those two lines aren't in the other order, i.e. system error resetting last?

I can think of no reason why they couldn't be the other way around - but I'm not sure what led you to the conclusion that those lines are the problem. Probably there are multiple paths to get to CRYPTO_malloc() which don't include those lines.

I'm thinking that instead of fixing all of these places where errno might get overwritten individually, we just handle it once in get_error_values (crypto/err.c).

**Comment by levitte** [comment]
> I'm thinking that instead of fixing all of these places where errno might get overwritten individually, we just handle it once in get_error_values (crypto/err.c).

Sounds like a good idea.  I suppose you want to restore just before the `return ret;` line...

**Comment by mattcaswell** [comment]
> Sounds like a good idea. I suppose you want to restore just before the return ret; line...

Probably I won't get around to this until I'm back from holiday...so if anyone else wants to pick this up, feel free.

**Comment by levitte** [comment]
If @mshaw1990 can help testing, I can pick this up.

I do need that help, 'cause I haven't been able to reproduce the issue...

**Comment by mshaw1990** [comment]
I would be more than happy to offer any help I can!

**Comment by levitte** [comment]
Calling your attention to #7902

**Comment by mshaw1990** [comment]
I have checked out commit ee80f4bfaf8e5aff0b4c484f0c91df48c3f10cb7 and I have verified that the proposed fix works, thank you for your prompt replies and fix!

nmake test

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" /                 depend && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" /                   _tests

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        mkdir .\test\test-runs
        set SRCTOP=.
        set BLDTOP=.
        set RESULT_D=.\test\test-runs
        set PERL=C:\Perl64\bin\perl.exe
        set OPENSSL_ENGINES=E:\temp\openssl\openssl-ee80f4bfaf8e5aff0b4c484f0c91df48c3f10cb7\engines
        set OPENSSL_DEBUG_MEMORY=on
        "C:\Perl64\bin\perl.exe" ".\test\run_tests.pl"
test\recipes\01-test_abort.t .................... ok
test\recipes\01-test_sanity.t ................... ok
test\recipes\01-test_symbol_presence.t .......... ok
test\recipes\01-test_test.t ..................... ok
test\recipes\02-test_errstr.t ................... ok
test\recipes\02-test_internal_ctype.t ........... ok
test\recipes\02-test_lhash.t .................... ok
test\recipes\02-test_ordinals.t ................. ok
test\recipes\02-test_stack.t .................... ok
test\recipes\03-test_exdata.t ................... ok
test\recipes\03-test_internal_asn1.t ............ ok
test\recipes\03-test_internal_chacha.t .......... ok
test\recipes\03-test_internal_curve448.t ........ ok
test\recipes\03-test_internal_mdc2.t ............ ok
test\recipes\03-test_internal_modes.t ........... ok
test\recipes\03-test_internal_poly1305.t ........ ok
test\recipes\03-test_internal_siphash.t ......... ok
test\recipes\03-test_internal_sm2.t ............. ok
test\recipes\03-test_internal_sm4.t ............. ok
test\recipes\03-test_internal_ssl_cert_table.t .. ok
test\recipes\03-test_internal_x509.t ............ ok
test\recipes\03-test_ui.t ....................... ok
test\recipes\04-test_asn1_decode.t .............. ok
test\recipes\04-test_asn1_encode.t .............. ok
test\recipes\04-test_asn1_string_table.t ........ ok
test\recipes\04-test_bio_callback.t ............. ok
test\recipes\04-test_bioprint.t ................. ok
test\recipes\04-test_err.t ...................... ok
test\recipes\04-test_pem.t ...................... ok
test\recipes\05-test_bf.t ....................... ok
test\recipes\05-test_cast.t ..................... ok
test\recipes\05-test_des.t ...................... ok
test\recipes\05-test_hmac.t ..................... ok
test\recipes\05-test_idea.t ..................... ok
test\recipes\05-test_md2.t ...................... skipped: md2 is not supported
by this OpenSSL build
test\recipes\05-test_mdc2.t ..................... ok
test\recipes\05-test_rand.t ..................... ok
test\recipes\05-test_rc2.t ...................... ok
test\recipes\05-test_rc4.t ...................... ok
test\recipes\05-test_rc5.t ...................... skipped: rc5 is not supported
by this OpenSSL build
test\recipes\06-test-rdrand.t ................... ok
test\recipes\10-test_bn.t ....................... ok
test\recipes\10-test_exp.t ...................... ok
test\recipes\15-test_dh.t ....................... ok
test\recipes\15-test_dsa.t ...................... ok
test\recipes\15-test_ec.t ....................... ok
test\recipes\15-test_ecdsa.t .................... ok
test\recipes\15-test_ecparam.t .................. ok
test\recipes\15-test_genrsa.t ................... ok
test\recipes\15-test_mp_rsa.t ................... ok
test\recipes\15-test_out_option.t ............... ok
test\recipes\15-test_rsa.t ...................... ok
test\recipes\15-test_rsapss.t ................... ok
test\recipes\20-test_enc.t ...................... ok
test\recipes\20-test_enc_more.t ................. ok
test\recipes\20-test_passwd.t ................... ok
test\recipes\25-test_crl.t ...................... ok
test\recipes\25-test_d2i.t ...................... ok
test\recipes\25-test_pkcs7.t .................... ok
test\recipes\25-test_req.t ...................... ok
test\recipes\25-test_sid.t ...................... ok
test\recipes\25-test_verify.t ................... ok
test\recipes\25-test_x509.t ..................... ok
test\recipes\30-test_afalg.t .................... skipped: test_afalg not suppor
ted for this build
test\recipes\30-test_engine.t ................... ok
test\recipes\30-test_evp.t ...................... ok
test\recipes\30-test_evp_extra.t ................ ok
test\recipes\30-test_pbelu.t .................... ok
test\recipes\30-test_pkey_meth.t ................ ok
test\recipes\30-test_pkey_meth_kdf.t ............ ok
test\recipes\40-test_rehash.t ................... skipped: test_rehash is not av
ailable on this platform
test\recipes\60-test_x509_check_cert_pkey.t ..... ok
test\recipes\60-test_x509_dup_cert.t ............ ok
test\recipes\60-test_x509_store.t ............... skipped: test_rehash is not av
ailable on this platform
test\recipes\60-test_x509_time.t ................ ok
test\recipes\70-test_asyncio.t .................. ok
test\recipes\70-test_bad_dtls.t ................. ok
test\recipes\70-test_clienthello.t .............. ok
test\recipes\70-test_comp.t ..................... ok
test\recipes\70-test_key_share.t ................ ok
test\recipes\70-test_packet.t ................... ok
test\recipes\70-test_recordlen.t ................ ok
test\recipes\70-test_renegotiation.t ............ ok
test\recipes\70-test_servername.t ............... ok
test\recipes\70-test_sslcbcpadding.t ............ ok
test\recipes\70-test_sslcertstatus.t ............ ok
test\recipes\70-test_sslextension.t ............. ok
test\recipes\70-test_sslmessages.t .............. ok
test\recipes\70-test_sslrecords.t ............... ok
test\recipes\70-test_sslsessiontick.t ........... ok
test\recipes\70-test_sslsigalgs.t ............... ok
test\recipes\70-test_sslsignature.t ............. ok
test\recipes\70-test_sslskewith0p.t ............. ok
test\recipes\70-test_sslversions.t .............. ok
test\recipes\70-test_sslvertol.t ................ ok
test\recipes\70-test_tls13alerts.t .............. ok
test\recipes\70-test_tls13cookie.t .............. ok
test\recipes\70-test_tls13downgrade.t ........... ok
test\recipes\70-test_tls13hrr.t ................. ok
test\recipes\70-test_tls13kexmodes.t ............ ok
test\recipes\70-test_tls13messages.t ............ ok
test\recipes\70-test_tls13psk.t ................. ok
test\recipes\70-test_tlsextms.t ................. ok
test\recipes\70-test_verify_extra.t ............. ok
test\recipes\70-test_wpacket.t .................. skipped: Test disabled in this
 configuration
test\recipes\80-test_ca.t ....................... ok
test\recipes\80-test_cipherbytes.t .............. ok
test\recipes\80-test_cipherlist.t ............... ok
test\recipes\80-test_ciphername.t ............... ok
test\recipes\80-test_cms.t ...................... ok
test\recipes\80-test_cmsapi.t ................... ok
test\recipes\80-test_ct.t ....................... ok
test\recipes\80-test_dane.t ..................... ok
test\recipes\80-test_dtls.t ..................... ok
test\recipes\80-test_dtls_mtu.t ................. ok
test\recipes\80-test_dtlsv1listen.t ............. ok
test\recipes\80-test_ocsp.t ..................... ok
test\recipes\80-test_pkcs12.t ................... skipped: Non-Greek system loca
le
test\recipes\80-test_ssl_new.t .................. ok
test\recipes\80-test_ssl_old.t .................. ok
test\recipes\80-test_ssl_test_ctx.t ............. ok
test\recipes\80-test_sslcorrupt.t ............... ok
test\recipes\80-test_tsa.t ...................... ok
test\recipes\80-test_x509aux.t .................. ok
test\recipes\90-test_asn1_time.t ................ ok
test\recipes\90-test_async.t .................... ok
test\recipes\90-test_bio_enc.t .................. ok
test\recipes\90-test_constant_time.t ............ ok
test\recipes\90-test_fatalerr.t ................. ok
test\recipes\90-test_gmdiff.t ................... ok
test\recipes\90-test_gost.t ..................... skipped: No test GOST engine f
ound
test\recipes\90-test_ige.t ...................... ok
test\recipes\90-test_includes.t ................. ok
test\recipes\90-test_memleak.t .................. ok
test\recipes\90-test_overhead.t ................. skipped: Only supported in no-
shared builds
test\recipes\90-test_secmem.t ................... ok
test\recipes\90-test_shlibload.t ................ ok
test\recipes\90-test_srp.t ...................... ok
test\recipes\90-test_sslapi.t ................... ok
test\recipes\90-test_sslbuffers.t ............... ok
test\recipes\90-test_store.t .................... ok
test\recipes\90-test_sysdefault.t ............... ok
test\recipes\90-test_threads.t .................. ok
test\recipes\90-test_time_offset.t .............. ok
test\recipes\90-test_tls13ccs.t ................. ok
test\recipes\90-test_tls13encryption.t .......... ok
test\recipes\90-test_tls13secrets.t ............. ok
test\recipes\90-test_v3name.t ................... ok
test\recipes\95-test_external_boringssl.t ....... skipped: No external tests in
this configuration
test\recipes\95-test_external_krb5.t ............ skipped: No external tests in
this configuration
test\recipes\95-test_external_pyca.t ............ skipped: No external tests in
this configuration
test\recipes\99-test_ecstress.t ................. ok
test\recipes\99-test_fuzz.t ..................... ok
All tests successful.
Files=153, Tests=1421, 865 wallclock secs ( 3.00 usr +  0.64 sys =  3.64 CPU)
