### ISSUE TITLE
Wrong version value for PKCS#8 output for ed25519 keys?

### ISSUE THREAD

**Issue by hahseba** [openssl/openssl#7898]
Hi, using OpenSSL 1.1.1a 20 Nov 2018 on Windows and running the following commands:

    ```
    $ openssl genpkey -algorithm Ed25519 -out ed25519key.pem
    $ openssl pkcs8 -topk8 -outform DER -in ed25519key.pem -out ed25519key.pfx -nocrypt
    ```
I receive an output that I cannot insert into some other crypto libraries (see https://github.com/briansmith/ring/issues/740). The advice is that the version number in the asn.1 output is of an incorrect value. In my understanding, it should be zero. Is this a bug in OpenSSL or is something else amiss here?

**Comment by mattcaswell** [comment]
Assuming this is a test key you can share, what do you get from:

````
openssl asn1parse -in ed25519key.pfx -inform DER
````

and

````
hexdump -C ed25519key.pfx
````

For one I just generated I get:

````
openssl asn1parse -in ed25519key.pfx -inform DER
    0:d=0  hl=2 l=  46 cons: SEQUENCE          
    2:d=1  hl=2 l=   1 prim: INTEGER           :00
    5:d=1  hl=2 l=   5 cons: SEQUENCE          
    7:d=2  hl=2 l=   3 prim: OBJECT            :ED25519
   12:d=1  hl=2 l=  34 prim: OCTET STRING      [HEX DUMP]:04204E00D60E854B037CC52BD6BFAF6CFD1DD8CB45A955905D19BDD85CFECED8C68F
````

and

````
hexdump -C ed25519key.pfx
00000000  30 2e 02 01 00 30 05 06  03 2b 65 70 04 22 04 20  |0....0...+ep.". |
00000010  4e 00 d6 0e 85 4b 03 7c  c5 2b d6 bf af 6c fd 1d  |N....K.|.+...l..|
00000020  d8 cb 45 a9 55 90 5d 19  bd d8 5c fe ce d8 c6 8f  |..E.U.]...\.....|
00000030
````

Which clearly shows the version as "0" - which seems correct.

**Comment by hahseba** [comment]
Thank you for these commands. Looks like my editor completely messes up binary to hex conversion, very sorry for the noise.
