### ISSUE TITLE
issuer certificate may found unexpected and result verify failed

### ISSUE THREAD

**Issue by MagicC1** [openssl/openssl#7899]
CA have signed certificate with two different public key algorithm, both CA have loaded in verify store, If the different was load before same  public key algorithm,the wrong CA will found to build the certificate chain,and verification will failed.

Version: 1.1.1
build: self build
Configure certificate (issuer and subject is same and no akid): 
Root CA(RSA) > CA(RSA) > EE(RSA)
Root CA(DSA) > CA(DSA) > EE(DSA)
Verify mode: Client verify Server
Client:  
Step 1: Init setup
Step 2: Load Root CA(DSA) and CA(DSA)
Step 3: Load Root CA(RSA) and CA(RSA)

Server:
Step 1: Init setup
Step2: Load EE(RSA) and key
Step 3:Load CA(RSA)

Build certificate chain:   Root CA(DSA) - CA(DSA) - EE(RSA) 

The verification with such certificate chain will  failed.

**Comment by levitte** [comment]
This sounds like EE(RSA) is lacking the [Authority Key Identifier extension](https://tools.ietf.org/html/rfc5280#section-4.2.1.1).  Either that, or you've found a genuine bug.  Would you mind running this command for us and verify if or if not you find a line saying "X509v3 Authority Key Identifier:"?  And oh, please check that the value (the line after) *differs* for EE(RSA) and EE(DSA).

```
openssl x509 -text -noout -in FILE
```

where you use the file name of EE(RSA) and EE(DSA) instead of `FILE` (assuming the files are in PEM format)

**Comment by MagicC1** [comment]
the verify will pass in case of only load RSA certificate, The AKID extension will ignore in case not present.
AKID extension was non-critical as per RFC5280:
> Conforming CAs MUST mark this extension as non-critical.
If verification in "NID of public key algorithm" added when check issued,such case will supported.what is your opinion?

**Comment by MagicC1** [comment]
the verify will pass in case of only load RSA certificate, The AKID extension will ignore in case not present.
AKID extension was non-critical as per RFC5280:

> Conforming CAs MUST mark this extension as non-critical.

If verification in "NID of public key algorithm" added when check issued,such case will supported.what is your opinion?

**Comment by levitte** [comment]
Side note: I think you misunderstand what 'non-critical' means.  It means that an extension that is *present* can still be ignored by software that do not know the extension.

Otherwise, my opinion is that it would certainly be a useful feature.  I can look into it.

**Comment by levitte** [comment]
Nevertheless, if CA(RSA) and CA(DSA) claim to be conformant, they MUST include the AKID among the extensions of certs they issue. Had they done so, you would not have had this issue.

That being said, I've started coding an extra check for the algorithms used. PR coming up later this evening (my time)

**Comment by MagicC1** [comment]
Yes,there is no such issue when AKID present. If implement support certificate  without AKID ,add an extra check for the algorithms used will help to avoid build certificate chain with the mismatch algorithms. Thanks.

**Comment by richsalz** [comment]
There is no requirement that a CA using RSA can only sign certs with RSA keys.

**Comment by MagicC1** [comment]
Is it necessity to check the sign when build certificate chain which was done in the verify step currently.

**Comment by levitte** [comment]
@richsalz, you have to agree, thought, that for verification to occur, the algorithm of the signing key should match the algorithm of the *signature* in the signed certificate.

**Comment by richsalz** [comment]
Yes I agree the signature type must map the type of key the signer's cert.  I was just pointing out that to not go too far :)

**Comment by levitte** [comment]
Me, going too far??????  Well, have a look in #7919 and see for yourself :wink:

**Comment by MagicC1** [comment]
@levitte #7919 was exactly match with what I tried explain. Actually,I was misunderstand the comments that CA using RSA can only sign certs with RSA keys from @richsalz . these two was different part in certificate, this MR will help in Certification Path Building.

**Comment by levitte** [comment]
And it's in!  Thanks for the idea, @MagicC1

**Comment by MagicC1** [comment]
Welcome, and thanks for the discussion. :-)
