### ISSUE TITLE
Use ' pkcs7_decrypt ' decrypt the .P7M file ,just a part  plain text some others is unknow code

### ISSUE THREAD

**Issue by hatjs880328s** [openssl/openssl#7909]
Use ' pkcs7_decrypt ' decrypt the .P7M file ,just a part is  **plain text** some others is unknow code like undecrypt.

why?

**Comment by hatjs880328s** [comment]
What steps have been omitted?

**Comment by levitte** [comment]
This kind of question is better suited for the mailing list openssl-users@openssl.org.  You must subscribe to post, please look here for more info: https://www.openssl.org/community/mailinglists.html
