### ISSUE TITLE
x509_lcl.h is required for X509_LOOKUP_METHOD definition

### ISSUE THREAD

**Issue by johny7** [openssl/openssl#7923]
With OpenSSL 1.1.1a, x509_lcl.h header, which is included in the list of headers for export, contains this line:
```
#include "internal/refcount.h"
```

Which breaks the build.

**Comment by levitte** [comment]
> x509_lcl.h header, **which is included in the list of headers for export**

Wait what?  Where is it listed for export?  I can't see that in our source.

**Comment by johny7** [comment]
Sorry, you are right, it is not included into the list of headers for export, it was manually included by our engineers. I changed topic to reflect that.

Ok, the issue is, the header is required for X509_LOOKUP_METHOD to work. This struct is used if you want to create wrapper to external certificate store, for example, to Windows Certificate Store.

This header should be somehow exposed. Thank you.

**Comment by richsalz** [comment]
You don't need the header file; the struture is opaque on purpose. You have to use the "new" function, and then set the various lookup functions.  Maybe they need to be more documented?

**Comment by johny7** [comment]
Yes, you are right, methods like X509_LOOKUP_meth_set_get_by_subject, X509_LOOKUP_meth_set_get_by_issuer_serial, X509_LOOKUP_meth_set_get_by_fingerprint can be used to set struct values.
