### ISSUE TITLE
openssl decrypt the file with errors:

### ISSUE THREAD

**Issue by 12cheny** [openssl/openssl#7926]

**Comment by 12cheny** [comment]
openssl aes-256-cbc -d -a -in AAA_encrypted.tar.gz -out AAA.tar.gz
 run with errors below:

bad decrypt
9112:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:.\crypto\evp\evp_enc.c:531:

**Comment by levitte** [comment]
Don't use `-a` on a tarball.  Do read the manual.
