### ISSUE TITLE
Minor typo in docs

### ISSUE THREAD

**Issue by behrangsa** [openssl/openssl#7927]
# Current:

> Additionally emailAddress is include

# Expected:

> Additionally emailAddress is included

# Location: 
https://www.openssl.org/docs/manmaster/man1/req.html

**Comment by InfoHunter** [comment]
You wanna launch a pull request to fix this?

**Comment by InfoHunter** [comment]
> Raised a PR.

Thanks!

**Comment by jwilk** [comment]
I guess this can be closed now?

**Comment by levitte** [comment]
Yip
