### ISSUE TITLE
Insecure Scrypt parameters

### ISSUE THREAD

**Issue by taoeffect** [openssl/openssl#793]
[These](https://github.com/openssl/openssl/blame/033585175485077bf7f5bbb352fd4f162d0c235f/apps/pkcs8.c#L205) are apparently ["idiotic"](https://twitter.com/cperciva/status/705851273170423808) according to Colin, who seems quite upset.

**Comment by FdaSilvaYY** [comment]
fixed here 5fc3ee4b77 , no ?

**Comment by kroeckx** [comment]
I think so, so I'm closing this.
