### ISSUE TITLE
PCLINT Info:773 in ssl.h

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#7930]
Info:773 reported from PCLINT in ssl.h
desc: Expression-like macro 'SSL_MAX_CERT_LIST_DEFAULT' not parenthesized
ssl.h:640
`# define SSL_MAX_CERT_LIST_DEFAULT 1024*100`

**Comment by MagicC1** [comment]
Suggest add Parentheses and will be:
`# define SSL_MAX_CERT_LIST_DEFAULT (1024*100)`
