### ISSUE TITLE
uid.c:(.text+0x23): undefined reference to 'getauxval' on linux with glibc 2.11

### ISSUE THREAD

**Issue by HeYoushang** [openssl/openssl#7932]
when link openssl1.1.1 library, we got the following error on linux with glibc 2.11 version,
`uid.c:(.text+0x23): undefined reference to 'getauxval'`,
from [http://man7.org/linux/man-pages/man3/getauxval.3.html](url), we found getauxval is supported from glibc 2.16 version, 
and the code in uid.c of openssl is as following, it looks like we already consider the glibc version, but why the usage of getauxval is outside of `#  if __GLIBC_PREREQ(2, 16)` statement:

``` C
# if defined(__GLIBC__) && defined(__GLIBC_PREREQ)
#  if __GLIBC_PREREQ(2, 16)
#   include <sys/auxv.h>
#  endif
# endif

int OPENSSL_issetugid(void)
{
# ifdef AT_SECURE
    return getauxval(AT_SECURE) != 0;
# else
    return getuid() != geteuid() || getgid() != getegid();
# endif
}
```

**Comment by levitte** [comment]
Supposedly, `AT_SECURE` is defined by the inclusion of `sys/auxv.h`, so using that macro as a guard was assumed to be sufficient.

So it seems that *something else* defined `AT_SECURE`, do you have any idea what that could be?

**Comment by HeYoushang** [comment]
@levitte 
thank you for reply.
we search the AT_SECURE in `/usr/include` on ubuntu 4.4.0 with glibc 2.23, found two definitions, 
`root@ubuntu:/usr/include# grep -nr AT_SECURE`
`linux/auxvec.h:27:#define AT_SECURE 23   /* secure mode boolean */`
`x86_64-linux-gnu/bits/auxv.h:55:#define AT_SECURE       23              /* Boolean, was exec setuid-like?  */`
but there is no definition in sys/auxv.h, while sys/auxv.h actually exists on my machine.
`root@ubuntu:/usr/include# find -name auxv.h`
`./sys/auxv.h`
`./x86_64-linux-gnu/bits/auxv.h`
`./x86_64-linux-gnu/sys/auxv.h`
on another machine, suse 11, with glibc 2.23, also found two difinitions in `/usr/include`, 
`linux/auxvec.h:27:#define AT_SECURE 23   /* secure mode boolean */`
`elf.h:1038:#define      AT_SECURE       23              /* Boolean, was exec setuid-like?  */`
on the previous machine, suse 11, with glibc 2.11, also found the above two definitions.
so do you have any idea ?

**Comment by levitte** [comment]
Don't worry too much about the multitude of files, it's an inclusion jungle.

The definition in `elf.h` was interesting...  that might be included recursively somewhere.  So ok, `AT_SECURE` wasn't a good guard, we'd better make our own.  PR coming up!

**Comment by levitte** [comment]
Have a look at #7933 and see if that fixes your problem

**Comment by HeYoushang** [comment]
#7933 will fix my current problem, but there are some other usages of `getauxval` in openssl, in `crypto/ppccap.c` and `crypto/armcap.c`, as follows, 
`#if defined(__GNUC__) && __GNUC__>=2 && defined(__ELF__)`
`extern unsigned long getauxval(unsigned long type) __attribute__ ((weak));`
`#else`
`static unsigned long (*getauxval) (unsigned long) = NULL;`
`#endif`
i am not sure if there is problem here

**Comment by levitte** [comment]
`ppccap.c` and `armcap.c` are built for the PowerPC and ARM architectures, respectively.  *If* they are problematic, they need to be treated separately.

**Comment by HeYoushang** [comment]
yes, here we have arm machines, but haven't compiled. i will continue commenting if there was any news.
thank you very much.

**Comment by HeYoushang** [comment]
no problem. thanks again
