### ISSUE TITLE
Cannot create directory C:/Program Files/OpenSSL: No such file or directory

### ISSUE THREAD

**Issue by yuchaoo** [openssl/openssl#7934]
openssl-OpenSSL_1_1_1a
1 perl Configure VC-WIN64A enable-static-engine no-zlib --openssldir="E:\OpenSSL"
2 nmake
3 nmake test
4 nmake install
That's where the above problem comes in

**Comment by JonasVautherin** [comment]
Same issue, but using `--prefix`. Did you find the root cause?

**Comment by t8m** [comment]
Are you able to reproduce this with 3.0 beta release?
