### ISSUE TITLE
PC-Lint Error:123 from U64 in modes_lcl.h and sha.h

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#7935]
U64 was defined in exposed head files and used internally, this will result confliction with the same define in adapter which have different prototype.

modes_lcl.h:
`#if (defined(_WIN32) || defined(_WIN64)) && !defined(__MINGW32__)`
`typedef __int64 i64;`
`typedef unsigned __int64 u64;`
`# define U64(C) C##UI64`
`#elif defined(__arch64__)`
`typedef long i64;`
`typedef unsigned long u64;`
`# define U64(C) C##UL`
`#else`
`typedef long long i64;`
`typedef unsigned long long u64;`
`# define U64(C) C##ULL`
`#endif`
`typedef unsigned int u32;`
`typedef unsigned char u8;`

sha.h:
`# if (defined(_WIN32) || defined(_WIN64)) && !defined(__MINGW32__)`
`#  define SHA_LONG64 unsigned __int64`
`#  define U64(C)     C##UI64`
`# elif defined(__arch64__)`
`#  define SHA_LONG64 unsigned long`
`#  define U64(C)     C##UL`
`# else`
`#  define SHA_LONG64 unsigned long long`
`#  define U64(C)     C##ULL`
`# endif`

Could these define move to c file or internal headfile?

**Comment by richsalz** [comment]
modes_lcl.h is an internal header file and should not be installed into the public directory. did you do an "install" by hand?

**Comment by MagicC1** [comment]
What about sha.h？

**Comment by richsalz** [comment]
sha.h is a public header file.  U64 is a poor choice for a macro name and perhaps should be changed to be OSSL_U64 or something like that.

**Comment by MagicC1** [comment]
As the adapter have no chance to use U64 from sha.h , How about move this to internal headfile?

**Comment by MagicC1** [comment]
Okay,It will come soon,Thanks.

**Comment by HeYoushang** [comment]
@richsalz 
do you have any suggestion where to move the U64, to sha_locl.h or just to sha512.c, sha_locl.h is for internal usage, but seems only used in sha1dgst.c currently, not so widely

**Comment by richsalz** [comment]
I have no suggestion.

**Comment by KanPlus** [comment]
U64 was defined in modes.h which only used interner
