### ISSUE TITLE
API for configuration of TLSv1.3 ciphersuites

### ISSUE THREAD

**Issue by rbaranauskas** [openssl/openssl#7938]
Hello,

It seems that nginx guys think your approach of specifying ciphersuites for TLSv1.3 is a bug and are actively waiting for a fix. Reference: https://trac.nginx.org/nginx/ticket/1533. 

Are you even considering it as a bug and are going to work on fixing it?

**Comment by mattcaswell** [comment]
The approach is not a bug and there are no plans to "fix it".
