### ISSUE TITLE
EVP_DecryptUpdate fails if in == out if there is some partial data already buffered

### ISSUE THREAD

**Issue by madscientist** [openssl/openssl#7941]
I'm using OpenSSL 1.1.1a on my GNU/Linux x86_64 system, built myself with GCC.  I'm working with the EVP interface on AES in different modes.  In all cases in my system I'm encrypting/decrypting into the same buffer as the source, not into a separate buffer.

I ran into a failure decrypting because of this code in `crypto/evp/evp_enc.c:EVP_DecryptUpdate()` line 487:

```
    if (ctx->final_used) {
        /* see comment about PTRDIFF_T comparison above */
==>     if (((PTRDIFF_T)out == (PTRDIFF_T)in)
            || is_partially_overlapping(out, in, b)) {
            EVPerr(EVP_F_EVP_DECRYPTUPDATE, EVP_R_PARTIALLY_OVERLAPPING);
            return 0;
        }
```

This is the only place in the entire EVP interface, as far as I can tell, where it checks for and fails if the `in` and `out` pointers being equal.  I read the discussion about `PTRDIFF_T` but I didn't see anything there to justify the equality comparison.

Is there something about this particular situation which makes this check necessary?  Is it not the case that I can decrypt into the same buffer in all situations?

I would have imagined that this code should simply be:

```
    if (ctx->final_used) {
        if (is_partially_overlapping(out, in, b)) {
            EVPerr(EVP_F_EVP_DECRYPTUPDATE, EVP_R_PARTIALLY_OVERLAPPING);
            return 0;
        }
```

but I certainly am no expert at OpenSSL.

Thanks!

**Comment by ctsr227** [comment]
I'm hitting this problem, and, like the OP, I can't see any reason why this logic is written the way it is.  Has anybody figured out what's going on here?

**Comment by ctsr227** [comment]
@dot-asm, do you have any insight into why the "in == out" check was added with the "partially overlapping buffer" patch you made?  

P.S. Thanks for your contributions to open source.

**Comment by ctsr227** [comment]
I get it now.  This explains it more or less:

https://github.com/openssl/openssl/pull/5427#issuecomment-369205788

**Comment by beldmit** [comment]
Isn't it worth summarizing it as a comment to the corresponding function (with a link to the issue)?

**Comment by erbsland-dev** [comment]
@t8m That PR should resolve this issue.
