### ISSUE TITLE
RAND_DRBG: Implement randomness generation for UEFI

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#7944]
This issue has been braught up in the recent [OSTIF Security Audit of the OpenSSL 1.1.1 Random Number Generation](https://ostif.org/our-review-of-the-openssl-1-1-1-random-number-generation-update) and still needs to be addressed. 

The following text is a minimally redacted excerpt from [opensslrng-audit-report.pdf](https://ostif.org/wp-content/uploads/2018/09/opensslrng-audit-report.pdf):

### E. UEFI randomness generation

In `rand_unix.c` the following defines are made:

https://github.com/openssl/openssl/blob/23d221b771348e3e3ee316cd1190a4a344d145fc/crypto/rand/rand_unix.c#L91-L94

The UEFI specification from 2.4 upwards supports generating random numbers using the protocol
`EFI_RNG_PROTOCOL`. The implementation details are in a driver called [rngdxe](https://github.com/tianocore/edk2/tree/master/SecurityPkg/RandomNumberGenerator/RngDxe) and can be
summarized as “uses RDRAND plus various DRBGs as specified in SP800-90.
We have not audited this code ourselves. We mention this as one of two possible alternatives to “none” on
UEFI platforms:

1. Use it.
2. Since it is based on RDRAND anyway, use that to collect randomness for the seed value

Related to: #7945 #7946

**Comment by mspncp** [comment]
cc @veorq

**Comment by paulidale** [comment]
For x86 and x86/64, I don't see a need to support this.  We have hooks for RDRAND and RDSEED already.  Having a second way to access RDRAND seems pointless.  It might even be detrimental -- we choose RDSEED over RDRAND but do UEFI platforms or are they limited to RDRAND?

For ARM, ARM/64 and Itanium, I can see some benefit.  Remember that these platforms do not have RDRAND, so some investigation will be required to see if what they do is meritorious.

**Comment by mspncp** [comment]
@paulidale as far as I understand it, this issue is not about UEFI in general, but rather about the case when `OPENSSL_SYS_UEFI` is defined and in which `OPENSSL_RAND_SEED_NONE` is enforced. I did not dig into the sources yet to find out when this case precisely applies.

**Comment by mspncp** [comment]
Cleaning up old neglected issues...
