### ISSUE TITLE
Force inclusion of OPENSSL_INIT_LOAD_CONFIG into OPENSSL_init_ssl

### ISSUE THREAD

**Issue by johny7** [openssl/openssl#7949]
The idea of force enabling of the config option imho is a bad idea for almost all library users, except of the internal usage. Separate config file is usually not provided (insecure) and I am not sure why was it enabled in 1.1.1.

Initialization fails because of this. Attempt to bypass the init with adding OPENSSL_INIT_NO_LOAD_CONFIG brings to https://github.com/openssl/openssl/issues/7350 bug.

I had to dig into sources and now have to add OPENSSL_NO_AUTOLOAD_CONFIG macro to bypass this, but this means that library is not silently-recompile-and-replace-able anymore.

**Comment by tmshort** [comment]
I was running into this problem.

**Comment by mattcaswell** [comment]
> Separate config file is usually not provided (insecure) and I am not sure why was it enabled in 1.1.1.
>
> Initialization fails because of this.

A lack of a config file should not cause intialisation to fail? It should just carry on regardless.

> Attempt to bypass the init with adding OPENSSL_INIT_NO_LOAD_CONFIG brings to #7350 bug.

That issue is fixed in git by commit f725fe5 and will be in 1.1.1b.
