### ISSUE TITLE
The macro define will cause Pclint warnnings

### ISSUE THREAD

**Issue by lilongyan-huawei** [openssl/openssl#7954]
in include/openssl/ssl.h: line 644
![image](https://user-images.githubusercontent.com/46128592/50428300-6ff55380-08f1-11e9-8bea-255ff7a4901e.png)

it should be "# define SSL_MAX_CERT_LIST_DEFAULT (1024*100)"

**Comment by t8m** [comment]
Already fixed in master. Closing.
