### ISSUE TITLE
Errors while using arm-linux-gnueabihf-gcc to compile and install openssl-1.0.2q

### ISSUE THREAD

**Issue by WendyHuangLa** [openssl/openssl#7955]
I want to compile OpenSSL for ARM, but there's something wrong when I do the command "make install".
Current machine:
![image](https://user-images.githubusercontent.com/33440566/50439362-bfa54080-092c-11e9-9e5c-569ac12b9608.png)
Target machine:
![image](https://user-images.githubusercontent.com/33440566/50439389-e06d9600-092c-11e9-8fc3-c6d49f04e65f.png)
The cross-compile tools on current machine is arm-linux-gnueabihf-gcc, as in "gcc-linaro-7.3-2018.05.tar.xz" download from https://releases.linaro.org/components/toolchain/gcc-linaro/latest-7/
The whole process is as follows:
1.Download openssl-1.0.2q.tar.gz from https://www.openssl.org/source/ ;
2.Do the following commands: 
```
tar zxvf openssl-1.0.2q.tar.gz
cd openssl-1.0.2q
CC=arm-linux-gnueabihf-gcc
./config no-asm shared --prefix=~/openssl/armlib --openssldir=ssl --cross-compile-prefix=arm-linux-gnueabihf-
```
then the Makefile as below:
![image](https://user-images.githubusercontent.com/33440566/50439824-735b0000-092e-11e9-99f8-f23b83ec8145.png)
......
![image](https://user-images.githubusercontent.com/33440566/50439868-a2717180-092e-11e9-9b0d-b202fa8f7028.png)
3.Then execute "make" command, seems everything is OK. But when I execute "make install" command, the outputs are like this:
![image](https://user-images.githubusercontent.com/33440566/50440060-6b4f9000-092f-11e9-9956-ec66d4e4615c.png)

The error is "arm-linux-gnueabihf-fcc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found".
Then I search "liblto_plugin.so" and find these:
![image](https://user-images.githubusercontent.com/33440566/50440208-195b3a00-0930-11e9-84f9-98bdad443954.png)

So......I'm confused.
Then when I execute "make install_sw" command, no errors was reported, but there's nothing in the "ssl" dir, so I was wondering if something is still wrong, too.
4.But !!! When I do these commands below:
```
make clean
CC=gcc
./config no-asm shared --prefix=~/openssl/armlib --openssldir=ssl
make
sudo make install
```
Then everything is OK ! And there are normal outputs in "ssl" directory.

Does anyone knows how to solve this problem ? Is it something wrong with the cross compiler ?

**Comment by InfoHunter** [comment]
I think it's only because your previous build output nothing due to the build failure in step 3. So you may need to fix the `fatal error` reported by the cross compiler first.

**Comment by WendyHuangLa** [comment]
> I think it's only because your previous build output nothing due to the build failure in step 3. So you may need to fix the `fatal error` reported by the cross compiler first.

The problem is that I've tried so many ways but still cannot solve the `fatal error` in step 3

**Comment by bernd-edlinger** [comment]
It is possible that you cross-compiler is broken.

But your configuration will not work for cross-compilation.
First you should first install a fresh copy of you openssl directory, `make clean` is not enough.

Then you should not use the ./config method for cross compile.
Conceptually you need to configure the --prefix how it is used on the target:
`./Configure linux-elf no-asm shared --prefix=/usr --openssldir=ssl --cross-compile-prefix=arm-linux-gnueabihf-`

Then install on the host using an INSTALL_PREFIX 
`make install INSTALL_PREFIX=~/openssl/armlib`

that will install libs into ~/openssl/armlib/usr/lib
headers into ~/openssl/armlib/usr/include/openssl
and arm-binary executable into ~/openssl/armlib/usr/bin
etc.

**Comment by t8m** [comment]
1.0.2 is out of support. Closing.
