### ISSUE TITLE
appveyor doesn't build plain/non-shared version anymore

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#7958]
The code to build seems to be inside an:
```
If ($env:Configuration -Match "shared" -or $env:EXTENDED_TESTS) 
```

Which doesn't make sense.

**Comment by paulidale** [comment]
Add a no-shared build to the CI.
Or hijack one of the existing builds to include this.

**Comment by kroeckx** [comment]
Maybe the issue isn't clear. There is a no-shared target. It
runs configure, but doesn't actually do anything else like build
it or run the test suite.

**Comment by levitte** [comment]
> ... but doesn't actually do anything else like build it or run the test suite.

Not quite true.  See the code:

https://github.com/openssl/openssl/blob/8dc34b1f579f71f24aa385d33112da4a91db7079/appveyor.yml#L56-L60

If your commit contains `[extended tests]`, then the no-shared configuration will be built.

However, the code that checks for `[extended tests]` comes quite late in `before_build:`...  it could be moved to happen before configuration, so I can understand that the build output looks confusing.

**Comment by kroeckx** [comment]
So we don't build it during pull requests, but it does get build when it's building master itself. I had to search the last build of master that it didn't cancel, which is currently: https://ci.appveyor.com/project/openssl/openssl/builds/36510326, where it does at least seem to build all targets.

**Comment by levitte** [comment]
I've looked over the appveyor docs, and think I found a method that makes things more clear.  PR coming up!

**Comment by levitte** [comment]
See #13537

**Comment by levitte** [comment]
Github should have autoclosed this when #13537 was merged...
