### ISSUE TITLE
ssl_method_st referenced before definition in ssl.h

### ISSUE THREAD

**Issue by eldavido** [openssl/openssl#796]
Hi everyone

I'm trying to support an old crufty legacy app and in the process, bring some of the "Indy" symbols forward to `master` (exact details unimportant).

I've tried to add a header file and some supplementary code to the build process to create a private fork. My files reference `SSL_SESSION`. I see from `ssl.h`, brought in via an include of `<openssl/ssl.h>`, that on line 328 this symbol is typedef'd to a `struct ssl_session_st`:

```
328: typedef struct ssl_session_st SSL_SESSION;
```

So far as I can tell, `struct ssl_session_st` isn't defined anywhere in `ssl.h`, which I consider an error.

I'm happy to correct this problem but I need some advice from the maintainers on how best to do so. Should I move the definition of this struct into this file? Happy to lend a hand but I don't know the larger context of what's going on here.

**Comment by kroeckx** [comment]
That struct ssl_session_st is not in any public header is
intentional. You should not be accessing any of it's members
directly but instead use the functions for it.

**Comment by eldavido** [comment]
Got it, thanks.

Maybe it should be taken out of the public header, then? I was confused because the typedef is in `ssl.h` but you're saying the structure if public...is there some legacy reason this typedef is necessary?

**Comment by kroeckx** [comment]
The type "SSL" is used in the API, but it's only used as a
pointer.  So you need to make the type known to the compiler,
but the compiler doesn't need to know what the members are.  So
the typedef itself is needed in the public header.
