### ISSUE TITLE
How to use TLS 1.3 properly on a server application?

### ISSUE THREAD

**Issue by trippleflux** [openssl/openssl#7963]
Hello,

 On OpenSSL 1.0.2x, i am doing the following to enable incoming TLS 1.2 related connections : 
Method = TLSv1_2_method();
But for somehow on 1.1.1a could not found the same function/method in which should named it as TLSv1_3_method(); .

I have googling around and i found out that i should use https://www.openssl.org/docs/manmaster/man3/SSL_CTX_add_custom_ext.html instead for TLS 1.3, can anyone please give the examples code in C language?

**Comment by trippleflux** [comment]
we need an easy TLS 1.3 like on TLS 1.2 with default options in which named like TLSv1_3_method(); .

**Comment by kroeckx** [comment]
You should use TLS_server_method() or SSLv23_server_method().

If you want to limit the protocol versions that are supported you
can use SSL_CTX_set_min_proto_version().

**Comment by trippleflux** [comment]
@kroeckx 
Thanks a lot for the pointers, but i am getting "14644:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl\record\ssl3_record.c:332:" when trying to connect with : 
```
openssl s_client -connect 127.0.0.1:5420 -cipher TLS13-CHACHA20-POLY1305-SHA256
```

My codes looks like this : 
````
		else if (!_tcsicmp(tszEncryptionProtocol, _TEXT("TLS1.3")))
		{
			Method = TLS_server_method();
			Putlog(LOG_ERROR, _T("TLS 1.3 Enabled"));
			lpService->bSslSupported = FALSE;
		}

	pCtx = SSL_CTX_new(Method);
	SSL_CTX_set_min_proto_version(pCtx, TLS1_3_VERSION);
	SSL_CTX_set_max_proto_version(pCtx, TLS1_3_VERSION);
````

Basically it's a open source FTPD, i know that there is no good FTP Client in which supporting TLS 1.3, i just wanted to prepare for it.

**Comment by trippleflux** [comment]
Ok my mistake, because openssl s_client doesn't understand implicit FTP command, need to disable EXPLICIT_ENCRYPTION in order to connect by start the host-client TLS negotiation.

Another turn around is, now i am getting this : 
````
12-28-2018 19:14:17 OpenSSL error: error:141F7065:SSL routines:final_key_share:no suitable key share
````

How to proceed?

**Comment by kroeckx** [comment]
I really recommend that you don't set the maximum protocol
version, that way when a new version of TLS is available, it will
automatically switch to the new version if both sides support it.
For that reason I also recommend that you don't set the minimum to
TLS 1.3, but to 1.2.

Your "-cipher" argument to s_client isn't doing what you want. If
you really want to limit the TLS 1.3 ciphers to use that one, you
need to use -ciphersuites.

I assume you're not resuming. I have no idea why your client does
not have a key_share.

**Comment by kroeckx** [comment]
s_client also supports -starttls ftp

**Comment by trippleflux** [comment]
Thanks a lot for the answer, really help me to resurrecting an old FTPD code :-)
