### ISSUE TITLE
why use sm2 can not decrypt?

### ISSUE THREAD

**Issue by liangruxing** [openssl/openssl#7964]
I use sm4_internal_test.c and set EC_GROUP params:
EC_GROUP *test_group =
        create_EC_group
        ("FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFF",//SM2_P
         "FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC",//SM2_A
         "28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E93",//SM2_B
         "32C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7",//SM2_G_X
         "BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0",//SM2_G_Y
         "FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFF7203DF6B21C6052B53BBF40939D54123",//SM2_N
         "1"
         );

it can encrypt ,but I use other program to decrypt and failed . Did i set the wrong params ?

**Comment by t8m** [comment]
SM2 cannot be used with EC keys anymore. Closing.
