### ISSUE TITLE
Target configuration

### ISSUE THREAD

**Issue by tanerjn** [openssl/openssl#7965]
I want to make use of openssl in Android NDK. Is it the right way to use openssl.conf and use macros for target architecture or it only enough to use Configurations/15-android.conf ?

I'm working both on Ubuntu16 and High Sierra, should I have more considerations? Thanks,

**Comment by mspncp** [comment]
Hi @tan3x, the [openssl-users](https://mta.openssl.org/mailman/listinfo/openssl-users) mailing list is a much better place to ask general questions about building and using OpenSSL. The GitHub issues are intended to report bugs and problems.
