### ISSUE TITLE
Compiler Optimization question when building openssl 1.1.0i-fips for Windows Embedded 6.0

### ISSUE THREAD

**Issue by jopi2016** [openssl/openssl#7978]
Hi everybody,

I've got a question about building OpenSSL 1.1.0i for Windows Embedded 6.0 based on ARM.
When I build OpenSSL using the default release optimization setting /O1i in target "VC-CE" of file Configurations/10-main.conf then RSA_size() in crypto\rsa\rsa_crpt.c gives me back a wrong value (125 instead of 128).
If I change the optimization to /Od then everything works fine. Although this has the downside that my binary increases in size.

What I'm wondering now is that if I look into MSDN (https://docs.microsoft.com/en-us/cpp/build/reference/o1-o2-minimize-size-maximize-speed?view=vs-2017) I don't find the option /O1i. Is this a mix of /O1 and /Oi ?

The strange thing is that if I build the same source on a x86-device with Windows Embedded 7.0 with optimization /O1i then RSA_size() works correctly.

Before I've been using 1.0.2k-fips and there RSA_size() worked correctly with option /O1i

Please find attached my makefile with /O1i and /Od of version 1.1.0i, my 10-main.conf of version 1.1.0i

Thanks in advance
[files2.zip](https://github.com/openssl/openssl/files/2726612/files2.zip)

**Comment by jopi2016** [comment]
Hi,
thanks for your hint. I'll give it a try.

Another option might be removing step by step parts of the optimization and check if RSA-size() then returns the correct value ( according to above link /O1 is equivalent to /Og /Os /Oy /Ob2 /GF /Gy )

**Comment by fredy-gu** [comment]
in crypto/bn/bn_lib.c, BN_num_bits_word, slight change:
-- BN_ULONG x, mask;
++volatile BN_ULONG x, mask;
seems be working.
