### ISSUE TITLE
openssl 1.1.1a Compile failed in Suse 11.

### ISSUE THREAD

**Issue by 372979131** [openssl/openssl#7987]
System OS:
Suse 11
GCC version:
CTU1000012808 [rdAgent]:~/Agent/build # gcc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux)

Compile config:
 config no-shared no-threads no-asm no-static-engine enable-ssl2 --prefix=$OPENSSL_INSTALL_PATH --openssldir=${OPENSSL_INSTALL_PATH}/ssl -Wl,--default-symver

Error:
rm -f apps/openssl
${LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -Wall -O3 -fPIC -L.   \
                -o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
                 apps/libapps.a -lssl -lcrypto -ldl -pthread
./libcrypto.so: undefined reference to `engine_load_padlock_int'
collect2: ld returned 1 exit status
make[1]: *** [apps/openssl] Error 1
make[1]: Leaving directory `/home/rdAgent/Agent/open_src/openssl'
make: *** [all] Error 2

someone can help me check why?
thank very much~~~

**Comment by levitte** [comment]
I tried to reproduce, but get no build failure.  Would you be willing to share a full build log, not just the last command?

**Comment by icedcoke** [comment]
first install dependence
yum install libtool perl-core zlib-devel -y
then 
make clean
able to solve the problem
我安装的是openssl 1.1.1a。顺利通过编译。

**Comment by paulidale** [comment]
Assuming that this was fixed, closing.

**Comment by shell1980** [comment]
> first install dependence yum install libtool perl-core zlib-devel -y then make clean able to solve the above problem 我安装的是openssl 1.1.1a。顺利通过编译。

it`s useful , thankyou ! and my verson is  openssl  3.0.5

**Comment by melonnpu** [comment]
> first install dependence yum install libtool perl-core zlib-devel -y then make clean able to solve the above problem 我安装的是openssl 1.1.1a。顺利通过编译。

it's useful,thank you! and my version is openssl 1.1.1s

**Comment by nidejuli** [comment]
execute make install 
error:
/usr/local/openssl_install: file not recognized: Is a directory
collect2: error: ld returned 1 exit status
make[1]: *** [libcrypto.so] Error 1
make[1]: Leaving directory `/usr/local/openssl1.1.1/openssl-1.1.1w'
make: *** [all] 错误 2
