### ISSUE TITLE
openssl 1.1.1a on Solaris 10 SPARC including in shared library build fails with text relocation errors

### ISSUE THREAD

**Issue by sortel64** [openssl/openssl#7989]
While including openssl 1.1.1a in my shared library, the build fails with the following:
```
g++ -L/usr/local/lib -z text -z defs -shared -o myplugin_d.so.1 ../Plugin.o MyPlugin.o HttpClient.o HttpHeader.o Url.o jsoncpp.o sr_funcs.o -locl_ssld -locld /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a -lxnet -lsocket -lnsl -lpthread -lrt -lc
Text relocation remains                         referenced
    against symbol                  offset      in file
ecp_nistz256_point_add_vis3         0x25f4c     /usr/local/lib/libcrypto.a(ecp_nistz256-sparcv9.o)
```
This is using gcc v4.9.2.  It seems to be referencing the openssl assembly code bits.  I did see that -fPIC was applied to each file during the openssl build.  This worked using prior versions of openssl.

[configdata.txt](https://github.com/openssl/openssl/files/2729607/configdata.txt)
Thank you!

**Comment by rainerjung** [comment]
Could you try whether adding the linker flag -Bsymbolic when you link your software helps (or as -Wl,-Bsymbolic if the linker is called via gcc)?

There were other similar errors, for example:

https://mta.openssl.org/pipermail/openssl-dev/2016-March/005714.html

Regards,

Rainer

**Comment by sortel64** [comment]
Rainer,
Thank you for the quick response.  That worked!
Regards,
Scott
