### ISSUE TITLE
Sparc build doesnt compile (master) due to version header changes.

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#7996]
Sparc builds are failing with the following error..

````
gcc  -I. -Icrypto/include -Iinclude -I.. -I../crypto/include -I../include  -fPIC -pthread -m32 -mcpu=ultrasparc -Wa,-Av8plus -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DB_ENDIAN -DBN_DIV2W -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/scratch/nsegen/jenkins/workspace/openssl-linux_sparc/install/ssl\"" -DENGINESDIR="\"/scratch/nsegen/jenkins/workspace/openssl-linux_sparc/install/lib/engines-3\"" -DNDEBUG  -c -o crypto/des/libcrypto-lib-des_enc-sparc.o crypto/des/des_enc-sparc.S
../include/openssl/opensslv.h: Assembler messages:
../include/openssl/opensslv.h:92: Error: Unknown opcode: `unsigned'
../include/openssl/opensslv.h:93: Error: Unknown opcode: `unsigned'
../include/openssl/opensslv.h:94: Error: Unknown opcode: `unsigned'
../include/openssl/opensslv.h:95: Error: Unknown opcode: `const'
../include/openssl/opensslv.h:96: Error: Unknown opcode: `const'
make[1]: *** [crypto/des/libcrypto-lib-des_enc-sparc.o] Error 1
````
opensslv.h was recently changed to have arrays in it. I think it had just #defines in it beforehand.
opensslconf.h is included in des_enc.m4 which (then includes opensslv.h). The assembler doesnt know what to do with unsigned char *.

-----------------------------------
Configuration tested was (other sparc variants also had this problem)

/usr/local/perl_remote/5.10.1/bin/perl ../Configure --prefix=/scratch/install shared linux-sparcv9

Perl information:

    /usr/local/packages/perl_remote/5.10.1/bin/perl
    5.10.1 for sparc64-linux

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    ktls                    [default]        OPENSSL_NO_KTLS
    afalgeng                [too-old-kernel] 
    asan                    [default]        OPENSSL_NO_ASAN
    crypto-mdebug           [default]        OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]        OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]        OPENSSL_NO_EGD
    external-tests          [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]        OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]        OPENSSL_NO_HEARTBEATS
    md2                     [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]        OPENSSL_NO_MSAN
    rc5                     [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]        OPENSSL_NO_SCTP
    ssl-trace               [default]        OPENSSL_NO_SSL_TRACE
    ubsan                   [default]        OPENSSL_NO_UBSAN
    unit-test               [default]        OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]        
    zlib-dynamic            [default]        
    ssl3                    [default]        OPENSSL_NO_SSL3
    ssl3-method             [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    CXX => "g++",
    CXXFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c aes-sparcv9.S aest4-sparcv9.S aesfx-sparcv9.S",
    aes_obj => "aes_core.o aes_cbc.o aes-sparcv9.o aest4-sparcv9.o aesfx-sparcv9.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "asm/sparcv8plus.S sparcv9-mont.S sparcv9a-mont.S vis3-mont.S sparct4-mont.S sparcv9-gf2m.S",
    bn_obj => "asm/sparcv8plus.o sparcv9-mont.o sparcv9a-mont.o vis3-mont.o sparct4-mont.o sparcv9-gf2m.o",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-pthread -m32 -mcpu=ultrasparc -Wa,-Av8plus",
    chacha_asm_src => "chacha_enc.c",
    chacha_obj => "chacha_enc.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c cmllt4-sparcv9.S",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o cmllt4-sparcv9.o",
    cppflags => "",
    cpuid_asm_src => "sparcv9cap.c sparccpuid.S",
    cpuid_obj => "sparcv9cap.o sparccpuid.o",
    cxxflags => "-std=c++11 -pthread -m32 -mcpu=ultrasparc -Wa,-Av8plus",
    def_extension => ".ld",
    defines => [  ],
    des_asm_src => "des_enc-sparc.S fcrypt_b.c dest4-sparcv9.S",
    des_obj => "des_enc-sparc.o fcrypt_b.o dest4-sparcv9.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-sparcv9.S",
    ec_obj => "ecp_nistz256.o ecp_nistz256-sparcv9.o",
    enable => [ "afalgeng" ],
    ex_libs => "-ldl -pthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DOPENSSL_USE_NODELETE -DB_ENDIAN -DBN_DIV2W",
    lib_defines => [  ],
    md5_asm_src => "md5-sparcv9.S",
    md5_obj => "md5-sparcv9.o",
    modes_asm_src => "ghash-sparcv9.S",
    modes_obj => "ghash-sparcv9.o",
    module_cflags => "-fPIC",
    module_cxxflags => "",
    module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    padlock_asm_src => "",
    padlock_obj => "",
    perlasm_scheme => "void",
    poly1305_asm_src => "poly1305-sparcv9.S",
    poly1305_obj => "poly1305-sparcv9.o",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    sha1_asm_src => "sha1-sparcv9.S sha256-sparcv9.S sha512-sparcv9.S",
    sha1_obj => "sha1-sparcv9.o sha256-sparcv9.o sha512-sparcv9.o",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,--version-script=",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-soname=",
    shared_target => "linux-shared",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar
    ARFLAGS         = r
    CC              = gcc
    CFLAGS          = -Wall -O3
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXX             = g++
    CXXFLAGS        = -Wall -O3
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = /usr/local/packages/perl_remote/5.10.1/bin/perl
    RANLIB          = ranlib
    RC              = windres

**Comment by mattcaswell** [comment]
See fix in #7997.
