### ISSUE TITLE
rpm built from source can't be installed on centos 7.4

### ISSUE THREAD

**Issue by BedivereZero** [openssl/openssl#8002]
I build rpm from source

```shell
rpmbuild -ta openssl-1.0.2q.tar.gz
```

get three rpms:

- openssl-1.0.2q-1.x86_64.rpm
- openssl-devel-1.0.2q-1.x86_64.rpm
- openssl-doc-1.0.2q-1.x86_64.rpm

then, I install two:

```shell
yum install openssl-1.0.2q-1.x86_64.rpm openssl-devel-1.0.2q-1.x86_64.rpm
```

failed:

```shell
Transaction check error:
  file /usr/lib64/pkgconfig/openssl.pc conflicts between attempted installs of openssl-devel-1:1.0.2q-1.x86_64 and openssl-1:1.0.2q-1.x86_64
```

I think the possible reason is this:

```spec
%files 
%defattr(0644,root,root,0755)
%doc CHANGES CHANGES.SSLeay LICENSE NEWS README

%attr(0755,root,root) %{_bindir}/*
%attr(0755,root,root) %{_libdir}/*.so*
%attr(0755,root,root) %{_libdir}/engines/*.so*
%attr(0755,root,root) %{_libdir}/pkgconfig/*
%attr(0755,root,root) %{openssldir}/misc/*
%attr(0644,root,root) %{_mandir}/man[157]/*

%config %attr(0644,root,root) %{openssldir}/openssl.cnf 
%dir %attr(0755,root,root) %{openssldir}/certs
%dir %attr(0755,root,root) %{openssldir}/misc
%dir %attr(0750,root,root) %{openssldir}/private

%files devel
%defattr(0644,root,root,0755)
%doc CHANGES CHANGES.SSLeay LICENSE NEWS README

%attr(0644,root,root) %{_libdir}/*.a
%attr(0644,root,root) %{_libdir}/pkgconfig/openssl.pc
%attr(0644,root,root) %{_includedir}/openssl/*
%attr(0644,root,root) %{_mandir}/man[3]/*
```

both openssl-1.0.2q-1-x86_64.rpm and openssl-devel-1.0.2q-x86_64.rpm contain the file

 `%{_libdir}/pkgconfig/openssl.pc`

**Comment by mattcaswell** [comment]
The OpenSSL project does not provide those rpms. This sounds like an issue for the centos maintainers.

**Comment by robert-scheck** [comment]
This is not an issue for the CentOS maintainers, because `rpmbuild -ta openssl-1.0.2q.tar.gz` isn't the way that CentOS ever uses to build RPM packages. This is more an OpenSSL upstream issue, because `rpmbuild -ta` uses actually `openssl-1.0.2q/openssl.spec` of upstream `openssl-1.0.2q.tar.gz`. But let me add that this spec file doesn't have a good style as per Fedora/RHEL/CentOS packaging policies.

**Comment by levitte** [comment]
@mattcaswell, sorry for being contrary, but the 1.0.2 branch [still has a spec file](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/openssl.spec).
It's largely unmaintained and should really be thrown away if you ask me.

(this issue shows exactly the reason that it was the right move to abandon all attempts at packaging specs with 1.1.0. It's simply not our job)

**Comment by t-j-h** [comment]
I would +1 a PR removing it.

**Comment by levitte** [comment]
Is that acceptable in a release branch?  If it is, a PR will be coming up.

**Comment by mattcaswell** [comment]
Since this is 1.0.2 only, and 1.0.2 is in security-fix only mode this won't be fixed.
