### ISSUE TITLE
About SSL_read Some Feature..

### ISSUE THREAD

**Issue by CandyMi** [openssl/openssl#8003]
I would like to ask where the openssl documentation mentions that SSL_read will read the number of bytes other than the specified byte and store it yourself?
    For example: suppose 100 bytes in the buffer (required for encryption)
    When I first registered the read event with epoll, I read 50 bytes from the buffer.
    When I registered the read event with epoll for the second time, I still couldn't get the read event callback?
What's this sh*t feature?

**Comment by CandyMi** [comment]
Yes. I know the rest of the buffers inside the SSL object. But good?

**Comment by mattcaswell** [comment]
I'm not sure I understand what you are trying to say. Data is sent in TLS in "records". The size of the record is defined by the sender of the data. SSL_read will read data from the file descriptor one record at a time. This is because an entire record must be processed in one go in order to decrypt and verify it. If the user application requested less bytes in the SSL_read call than were decrypted then the remaining bytes are buffered internally for a subsequent call.

**Comment by CandyMi** [comment]
>I'm not sure I understand what you are trying to say. Data is sent in TLS in "records". The size of the record is defined by the sender of the data. SSL_read will read data from the file descriptor one record at a time. This is because an entire record must be processed in one go in order to decrypt and verify it. If the user application requested less bytes in the SSL_read call than were decrypted then the remaining bytes are buffered internally for a subsequent call.

Yes. this's my question.  but my event-driven framework is registery events before SSL_read. 
But sometimes reading with SSL_read will read buf empty! This will cause my next registration event to have no readable data until timeout. I have solved this problem and thank you for your answer.
Sorry to reply too later.  :)  @mattcaswell

**Comment by LikeUSummer** [comment]
> I would like to ask where the openssl documentation mentions that SSL_read will read the number of bytes other than the specified byte and store it yourself?     For example: suppose 100 bytes in the buffer (required for encryption)     When I first registered the read event with epoll, I read 50 bytes from the buffer.     When I registered the read event with epoll for the second time, I still couldn't get the read event callback? What's this sh*t feature?

Hi~ Could you share me how you solved the problem mentioned above?  I want to know what mechanism should I token to obtain the rest 50 bytes (buffered in SSL object), I don't want to repeatly call SSL_read many times on one epoll notify, I need something notify me again about the rest 50 bytes. 
Thank you!

**Comment by CandyMi** [comment]
Hi. @LikeUSummer 

  When you need to use `ssl` to read a `buffer` with a specified byte size, you can try to use the `ssl_peek` method to check the internal received byte size.

  But according to my experience: "Anytime I need to register for read/write events, I will use `ssl_read*` to confirm that the buffer is empty or the existing data is incomplete". And this will minimize my `system calls `Number of times.

  Hope these can help you.    :)

**Comment by LikeUSummer** [comment]
> Hi. @LikeUSummer
> 
> When you need to use `ssl` to read a `buffer` with a specified byte size, you can try to use the `ssl_peek` method to check the internal received byte size.
> 
> But according to my experience: "Anytime I need to register for read/write events, I will use `ssl_read*` to confirm that the buffer is empty or the existing data is incomplete". And this will minimize the number of `syscall`.
> 
> Hope these can help you. :)

Wow~ Thank you sincerely, for what you said really helped me to puzzle out about SSL.
