### ISSUE TITLE
exit status 0/Success even when reporting Hostname mismatch

### ISSUE THREAD

**Issue by diepes** [openssl/openssl#8006]
$ openssl version
OpenSSL 1.1.0g  2 Nov 2017

I am trying to use  openssl in a script to check that a webserver/ssl supports a hostname.
The exit code is always 0/Success even when it reports Hostname mismatch
 
e.g.
```
$ echo "Q" | openssl s_client -verify_hostname dud.google -verify 3 -connect www.google.com:443 && echo ">> OK"
...
   Start Time: 1547077574
    Timeout   : 7200 (sec)
    Verify return code: 62 (Hostname mismatch)
    Extended master secret: yes
---
DONE
>> OK
```

**Comment by mattcaswell** [comment]
Try adding `-verify_return_error` to your command line
