### ISSUE TITLE
build fails for aarch64BE

### ISSUE THREAD

**Issue by leimaohui** [openssl/openssl#8007]
- configure

perl openssl/1.1.1-r0/openssl-1.1.1/Configure  --prefix=$useprefix --openssldir=/usr/lib64/ssl-1.1 --libdir=/usr/lib64 linux-aarch64

- error message

| crypto/sha/keccak1600-armv8.S: Assembler messages:
| crypto/sha/keccak1600-armv8.S:836: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:849: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:862: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:875: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:888: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:901: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:914: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:927: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:940: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:953: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:966: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:979: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
| crypto/sha/keccak1600-armv8.S:985: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'

**Comment by mattcaswell** [comment]
Ping @levitte. Any thoughts?

**Comment by NaveenShivanna86** [comment]
hi..
i am also facing this compile issue when open the assembler instruction (removed "no-asm" option) for targets “linux-aarch64“ and ”linux-arm64ilp32”

can anyone suggests how to solve this ?

**Comment by NaveenShivanna86** [comment]
@levitte

**Comment by NaveenShivanna86** [comment]
@levitte i used openssl1.1.1a and encountered below error, please suggest if there is any alternative 

crypto/sha/keccak1600-armv8.S: Assembler messages:
crypto/sha/keccak1600-armv8.S:836: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:849: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:862: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:875: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:888: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:901: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:914: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:927: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:940: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:953: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:966: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:979: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
crypto/sha/keccak1600-armv8.S:985: Error: operand 1 must be an integer register -- `rev v31.16b,v31.16b'
Makefile:4964: recipe for target 'crypto/sha/keccak1600-armv8.o' failed
make: *** [crypto/sha/keccak1600-armv8.o] Error 1

**Comment by leimaohui** [comment]
Please reference to [#9151](https://github.com/openssl/openssl/pull/9151)
