### ISSUE TITLE
update demo source code to align with best practice

### ISSUE THREAD

**Issue by HolgerJeromin** [openssl/openssl#801]
There is demo code for various tasks in the demo folder.
But for example the [x509/mkcert.c](https://github.com/openssl/openssl/blob/master/demos/x509/mkcert.c) demo uses [deprecated](https://www.openssl.org/docs/manmaster/crypto/RSA_generate_key.html) `RSA_generate_key` instead of `RSA_generate_key_ex`. 

Please update the demo folder with best practice code. If there is another place with better learning code delete the wrong leading demos from the repository.

**Comment by nick599** [comment]
Can you give examples of best practice code replacing what's there?

**Comment by HolgerJeromin** [comment]
I have no experience with openssl, that's why I had problems with the documentation. Sorry I am not aware of better code examples

**Comment by mattcaswell** [comment]
This demo has been removed from 1.1.0. Closing this.
