### ISSUE TITLE
OpenSSL searches for libeay32.dll and ssleay32.dll when it has libcrypto and libssl installed.

### ISSUE THREAD

**Issue by liubomirwm** [openssl/openssl#8011]
For some reason OpenSSL continues to search for these two dlls and breaks with an error for missing them, although it has the libcrypto and libssl dlls. I even tried renaming these two dlls to libeay32.dll and ssleay32.dll but it seems that they are not compatible because OpenSSL crashes when they are renamed with a different error.

So why does OpenSSL version 1.1.0i continues to search for the old dlls?

**Comment by mspncp** [comment]
Are you sure you don't have some older binaries lying around? I don't see many occurrances of 'libeay' or 'ssleay' in the source code:

```
$ git grep libeay OpenSSL_1_1_0i
OpenSSL_1_1_0i:.gitignore:/ms/libeay32.def
OpenSSL_1_1_0i:CHANGES:     become part of libeay.num as well.
OpenSSL_1_1_0i:CHANGES:     from Windows DLLs. Fixed up libeay.num for new functions.
OpenSSL_1_1_0i:CHANGES:     to ms/libeay{16,32}.def.
OpenSSL_1_1_0i:CHANGES:     the util/ssleay.num and util/libeay.num files with any new functions.
OpenSSL_1_1_0i:Configurations/README:                  files util/libeay.num or util/ssleay.num in the


$ git grep ssleay OpenSSL_1_1_0i
OpenSSL_1_1_0i:.gitignore:/ms/ssleay32.def
OpenSSL_1_1_0i:CHANGES:  *) All instances of the string "ssleay" in the public API were replaced
OpenSSL_1_1_0i:CHANGES:  *) Change ssleay_rand_bytes (crypto/rand/md_rand.c)
OpenSSL_1_1_0i:CHANGES:     Otherwise while one thread is in ssleay_rand_bytes (which sets the
OpenSSL_1_1_0i:CHANGES:     flag), *other* threads can enter ssleay_add_bytes without obeying
OpenSSL_1_1_0i:CHANGES:     of 'md', i.e. 80 bits.  ssleay_rand_add, on the other hand, chains
OpenSSL_1_1_0i:CHANGES:  *) Use lock CRYPTO_LOCK_RAND correctly in ssleay_rand_status
OpenSSL_1_1_0i:CHANGES:     the util/ssleay.num and util/libeay.num files with any new functions.
OpenSSL_1_1_0i:CHANGES:     1. merge various obsolete readme texts into doc/ssleay.txt
OpenSSL_1_1_0i:CHANGES:  *) First cut of a cleanup for apps/. First the `ssleay' program is now named
OpenSSL_1_1_0i:CHANGES:     into a single doc/ssleay.txt bundle. This way the information is still
OpenSSL_1_1_0i:CHANGES:     when "ssleay" is still not found.
OpenSSL_1_1_0i:CHANGES:  *) Added "oid_file" to ssleay.cnf for "ca" and "req" programs.
OpenSSL_1_1_0i:CHANGES:  *) Added -a (all) option to "ssleay version" command.
OpenSSL_1_1_0i:Configurations/README:                  files util/libeay.num or util/ssleay.num in the
OpenSSL_1_1_0i:util/mkcerts.sh:# SSLEAY=`pwd`/apps/ssleay; export SSLEAY
```

**Comment by liubomirwm** [comment]
It complains that it doesn't find these old dlls, not that it uses them.

A little background - i have a local development wordpress installation, and a plugin throws this exception:
![image](https://user-images.githubusercontent.com/16529989/51085340-25246a00-1740-11e9-816d-ca493a910d6a.png)
I use XAMPP with PHP 7.2.9 and OpenSSL 1.1.0i. When i go to directory C:\xampp\apache\bin and run the command below all is ok:
![image](https://user-images.githubusercontent.com/16529989/51085391-d5926e00-1740-11e9-8ed2-cbdea6faaf76.png)
This is the certificate that is server by the server. However, if i go into C:\xampp\php\extras\openssl i get this error:
![image](https://user-images.githubusercontent.com/16529989/51085414-328e2400-1741-11e9-8467-adcb88ae20ac.png)
What makes me worry is the date of modification of the openssl.exe binary - 16th of April 2012. Maybe Apache has version 1.1.0i, but PHP has an older version? I do not know, XAMPP says that this version is released with OpenSSL 1.1.0i and if i open XAMPP's phpinfo page it says that the loaded module is OpenSSL 1.1.0i. However, they do update XAMPP regularly with new versions of openssl.

It should not be using an old binary, what do you thing? Do i have to also open an issue there or it might be from OpenSSL?

**Comment by mspncp** [comment]
Ok, your command shell locates two different openssl.exe binaries, depending on which directory you are in. But this does not mean that it is a problem of Apache or PHP, or OpenSSL. My guess is that you have some old openssl.exe binary somewhere on your computer which is included in your PATH variable. You can check that using

```
cd C:\xampp\apache\bin
where openssl

cd C:\xampp\php\extras\openssl
where openssl
```

If the date of your openssl binary is accurate, then it is from version 1.0.1 or older, which is very outdated and not supported anymore.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
