### ISSUE TITLE
Invalid instruction exception in OPENSSL_rdtsc @ppc e500v2

### ISSUE THREAD

**Issue by MagicC1** [openssl/openssl#8012]
Version: OpenSSL1.1.1
CPU type: ppc e500v2

Callstack:
OPENSSL_rdtsc
rand_drbg_get_additional_data
RAND_DRBG_bytes
RAND_bytes
SSL_CTX_new

Analysis:
instruction mftbu was not supported in ppc e500v2, this result Invalid instruction exception
The implement of OPENSSL_rdtsc in ppc:
'OPENSSL_rdtsc:'
'.globl	.OPENSSL_rdtsc'
'.align	4'
'.OPENSSL_rdtsc:'
'___'
'$code.=<<___	if ($flavour =~ /64/);'
'	mftb	r3'
'___'
'$code.=<<___	if ($flavour !~ /64/);'
'Loop_rdtsc:'
'	mftbu	r5'
'	mftb	r3'
'	mftbu	r4'
'	cmplw	r4,r5'
'	bne	Loop_rdtsc'
'___'
'$code.=<<___;'
'	blr'
'	.long	0'
'	.byte	0,12,0x14,0,0,0,0,0'
'.size	.OPENSSL_rdtsc,.-.OPENSSL_rdtsc'

The reference manual of PPC:
http://cache.freescale.com/files/32bit/doc/ref_manual/E500CORERM.pdf

**Comment by MagicC1** [comment]
maybe no-asm option could be setted to disable the assemble code.

**Comment by bernd-edlinger** [comment]
I wonder if we should simply use mfspr 268/269 instead of mftb/mftbu
```
diff --git a/crypto/ppccpuid.pl b/crypto/ppccpuid.pl
index b1241a7..c1c59f8 100755
--- a/crypto/ppccpuid.pl
+++ b/crypto/ppccpuid.pl
@@ -129,13 +129,13 @@ Ladd:     lwarx   r5,0,r3
 .OPENSSL_rdtsc:
 ___
 $code.=<<___   if ($flavour =~ /64/);
-       mftb    r3
+       mfspr   r3,268
 ___
 $code.=<<___   if ($flavour !~ /64/);
 Loop_rdtsc:
-       mftbu   r5
-       mftb    r3
-       mftbu   r4
+       mfspr   r5,269
+       mfspr   r3,268
+       mfspr   r4,269
        cmplw   r4,r5
        bne     Loop_rdtsc
 ___
```

**Comment by mspncp** [comment]
> maybe no-asm option could be setted to disable the assemble code

Are you saying that `no-asm` is not respected for your ppc configuration? Have you tried to `make clean`, reconfigure and rebuild? If the problem still remains, please raise a separate github issue for this and provide the output of `perl configdata.pm --dump` and relevant parts of the make output.

**Comment by bernd-edlinger** [comment]
Hmm, linux did replace all mftb/mftbu with mfspr 268/269 years ago, because of the same issue,
but had to revert that later (MPC8xx did trap on the mfspr insns):
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ae2163be10ac6090e7aeed72591e2d7fabb1cdda

So we need either a runtime check, or a configure option for MPC8xx.
I assume that MPC8xx devices are still in use today?

**Comment by bernd-edlinger** [comment]
Would you mind trying out the patch in #8043 ?

**Comment by MagicC1** [comment]
@mspncp no-asm could work and could used to avoid the invalid instruction issue.
