### ISSUE TITLE
Type incompatibility of new macro OPENSSL_VERSION_NUMBER

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#8021]
For the 3.0.0 pre-release the macro OPENSSL_VERSION_NUMBER has been re-implemented, now using a constant calculation rather than a literal. Commit 5d609f22d2 removed the type cast to `long`, such that now it reads:
```
#  define OPENSSL_VERSION_NUMBER        \
          ( (OPENSSL_VERSION_MAJOR<<28)  \
            |(OPENSSL_VERSION_MINOR<<20) \
            |(OPENSSL_VERSION_PATCH<<4)  \
            |_OPENSSL_VERSION_PRE_RELEASE )
```
This provides backward compatibility regarding the value, but not regarding the type of the expression.
Note that formerly the type was (unsigned) `long`, for instance as in:
```
# define OPENSSL_VERSION_NUMBER  0x10102000L
````
while now the inferred type is just `int`.

This creates type warnings/errors in contexts like
```
printf("OpenSSL compile-time version is 0x%lx\n", OPENSSL_VERSION_NUMBER);
```

I was about to suggest (re-)adding a type cast to `unsigned long` to the macro quoted above, but apparently this would cause other problem as mentioned in #7851.

**Comment by kroeckx** [comment]
Maybe we can just put the "L" back after things like
OPENSSL_VERSION_MAJOR?

**Comment by DDvO** [comment]
Good idea! I can confirm that adding the 'L' solves the problem.

I just suggest not to put the 'L' after `OPENSSL_VERSION_MAJOR` nor `OPENSSL_VERSION_MINOR` nor `OPENSSL_VERSION_PATCH`, such that these definitions stay as clear and simple as they are now, but after the literals defining `_OPENSSL_VERSION_PRE_RELEASE`:
```
#  ifdef OPENSSL_VERSION_PRE_RELEASE
#   define _OPENSSL_VERSION_PRE_RELEASE 0x0L
#  else
#   define _OPENSSL_VERSION_PRE_RELEASE 0xfL
#  endif
```
