### ISSUE TITLE
atexit always return -1 on VxWorks system

### ISSUE THREAD

**Issue by HeYoushang** [openssl/openssl#8022]
https://github.com/openssl/openssl/blob/e26f653defd08334ebfa517b6715a338f543fbf1/crypto/init.c#L140
Function `atexit` always return -1 on VxWorks system, see debugging information below in the image, 
![image](https://user-images.githubusercontent.com/46014603/51178699-66627880-18fe-11e9-8a7f-a328e78f03d6.png)
and we found an implimentation as follows:
```
int atexit
(
void (*__func)(void)    /* pointer to a function */
) 
{
    return (ERROR); 
}
```
maybe we should exclude the calling of `atexit` by macro `OPENSSL_SYS_VXWORKS`.

**Comment by bernd-edlinger** [comment]
kernel or RTP ?

**Comment by HeYoushang** [comment]
er... not sure about this , but we compiled openssl in a common way , i think it was linked to standard library and this is a kernel issue , how to confirm whether it is kernel or RTP anyway ?

**Comment by mattcaswell** [comment]
It should be possible to work around this by an application calling `OPENSSL_init_crypto` using the flag `OPENSSL_INIT_NO_ATEXIT`. See:

https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_init_crypto.html

**Comment by mattcaswell** [comment]
The proper fix for this would be to have a "no-atexit" Configure option which is "on" by default for VxWorks platforms where this is an issue. If "atexit" doesn't work on a particular platform then that does impley applications will have to explicitly call `OPENSSL_cleanup`.

PRs for the above welcome!

**Comment by t8m** [comment]
> If "atexit" doesn't work on a particular platform then that does impley applications will have to explicitly call `OPENSSL_cleanup`.

Only if they care about memory leaks on process exit which is not that useful except for clean valgrind outputs or so. Or is there any other reason to call OPENSSL_cleanup?

**Comment by mattcaswell** [comment]
> Only if they care about memory leaks on process exit which is not that useful except for clean valgrind outputs or so. Or is there any other reason to call OPENSSL_cleanup?

No, that's true.

**Comment by richsalz** [comment]
I am not sure that adding another configuration option is the right way to go.  There is also a cost with doing that -- for example, the docs probably need an update to add "if configured on your platform".

If VxWorks provides atexit but it always fails, I'm not sure that OpenSSL needs to handle that cleanly.

**Comment by HeYoushang** [comment]
If the latest openssl version supports the configuration option OPENSSL_INIT_NO_ATEXIT to avoid calling of atexit, I think this issue could be closed. Application may configure this option to avoid initailization failing.

**Comment by mattcaswell** [comment]
> If the latest openssl version supports the configuration option OPENSSL_INIT_NO_ATEXIT to avoid calling of atexit, I think this issue could be closed. Application may configure this option to avoid initailization failing.

Ok. In that case - closing.
