### ISSUE TITLE
Externalize id-signingTime from CMS_ContentInfo

### ISSUE THREAD

**Issue by elear** [openssl/openssl#8026]
OpenSSL provides a way to validate a CMS signature with using a specified time (-attime).  Programmatically, I would like to know when the signature was made in order to validate with that time.  More precisely, what is needed is access to id-signingTime from the CMS structure, akin to X509_VERIFY_PARAM_get_time(), but presumably using CMS_ContentInfo.

I am told that this is a bug because CMS_ContentInfo is opaque, and a method should be available for access to the field.

**Comment by mattcaswell** [comment]
Seems like a reasonable accessor to want to have. As a missing accessor we can treat that as a bug and backport to 1.1.1.

**Comment by jamuir** [comment]
I can take a look at this.

**Comment by jamuir** [comment]
Signing Time is described in the CMS RFC:

  https://datatracker.ietf.org/doc/html/rfc5652#section-11.3

It is an Attribute and has been assigned an OID (and a NID, which is internal to OpenSSL).

I am looking at `master` and see that OpenSSL now provides the following APIs:

```C
  /* include/openssl/cms.h */

  int CMS_signed_get_attr_count(const CMS_SignerInfo *si);
  int CMS_signed_get_attr_by_NID(const CMS_SignerInfo *si, int nid, int lastpos);
  int CMS_signed_get_attr_by_OBJ(const CMS_SignerInfo *si, const ASN1_OBJECT *obj, int lastpos);
```

I'm not sure when they were added.

Unfortunately, there does not seem to be any documentation for them.

Inside `crypto/cms/cms_sd.c`, you can see an example of how to check for a Signing Time attribute using its NID:

https://github.com/openssl/openssl/blob/8d13d9e7305643c28c69c57df798b553b78c2876/crypto/cms/cms_sd.c#L823-L840

Perhaps the only work that is needed now is documentation and possibly a test.

@elear : will these APIs give you what you need?

@mattcaswell : what do you think?

**Comment by jamuir** [comment]
The issue description mentions using `-attime` during a cms verify operation, like this:

```
openssl cms -verify -in smout.txt -CAfile cacert.pem -attime 4684708800
```
Note that `-attime` only influences certificate validation.  The value of Signing Time attributes are not compared against the date set using `-attime`.

**Comment by jamuir** [comment]
The PR I opened provides an example of how to access the signingTime data from the CMS_ContentInfo structure.

**Comment by jamuir** [comment]
Shane L has a PR (#22656) that adds documentation for several APIs used for extracting data from CMS objects (including the APIs I used).  Once that PR is merged, I think this issue can be closed.

Tomas M suggested that we could provide a new API for more convenient access to Signing Time data.  If there is interest from our users, then I think it makes sense to do that (and note that this issue is several years old).
