### ISSUE TITLE
1.1.1a fails on musl with "Invalid version number 1_1_1 is greater than 1_1_1a or is invalid"

### ISSUE THREAD

**Issue by marv** [openssl/openssl#8032]
Building openssl 1.1.1a on a musl based Exherbo system fails with the following error:

``` 
x86_64-pc-linux-musl-ar: creating test/libtestutil.a
x86_64-pc-linux-musl-ar r test/libtestutil.a test/testutil/basic_output.o test/testutil/cb.o test/testutil/driver.o test/testutil/format_output.o test/testutil/init.o test/testutil/main.o test/testutil/output_helpers.o test/testutil/stanza.o test/testutil/tap_bio.o test/testutil/test_cleanup.o test/testutil/tests.o
x86_64-pc-linux-musl-ranlib test/libtestutil.a || echo Never mind.
/usr/x86_64-pc-linux-musl/bin/perl5.28 util/mkdef.pl crypto linux > libcrypto.map
make[1]: Leaving directory '/var/tmp/paludis/build/dev-libs-openssl-1.1.1a/work/openssl-1.1.1a'
Invalid version number 1_1_1 is greater than 1_1_1a or is invalid
make[1]: *** [Makefile:790: libcrypto.map] Error 255
make: *** [Makefile:171: all] Error 2
```
see the end of https://gitlab.exherbo.org/exherbo-misc/infra-scripts/-/jobs/9681/raw for a full build log.

I tried to build yesterdays OpenSSL_1_1_1-stable branch, but it resulted in the same error (just with 1_1_1b)

master builds fine and I think that commit https://github.com/openssl/openssl/commit/8effd8fa67689e1d4318cfda21604eef428a37cf#diff-bafeca6edbb214872f5843fa8065ad24 fixed the problem (it removes the parts from the script that yielded the error), but it doesn't backport straightforward (and i'm too unfamiliar with the codebase really)

Could/should the fix be backported? Would be great if we can make 1.1.1b compile on musl

**Comment by kroeckx** [comment]
The code that generates that error is still there, it just moved
to a different file.

Master is not affected by this because it only has 1 version: 3_0_0.

I don't understand why you get that error, it's just the perl
script that generates the .map file. We should get that error on
all platforms, I don't see how musl would be different.

**Comment by marv** [comment]
Thanks for the input. I investigated a bit further and found out that it's actually perl's `index` function that misbehaves on musl and causes the `die ... if index(...)` to be triggered. I'm closing this issue because it needs to be fixed in perl or musl.
Sorry for the noise
