### ISSUE TITLE
ERR_get_error for cms provides vague programmatic guidance

### ISSUE THREAD

**Issue by elear** [openssl/openssl#8035]
CMS is relying on X509_verify_cert() in the below code from cms_smime.c.  j below provides the correct code from X509, and the correct resultant string.  However, the error code from CMS is simply "Verification error".  That's not a lot to go on, programmatically.

```
    i = X509_verify_cert(ctx);
    if (i <= 0) {
        j = X509_STORE_CTX_get_error(ctx);
        CMSerr(CMS_F_CMS_SIGNERINFO_VERIFY_CERT,
               CMS_R_CERTIFICATE_VERIFY_ERROR);
        ERR_add_error_data(2, "Verify error:",
                           X509_verify_cert_error_string(j));
        goto err;
    }

```

If CMS is going to rely heavily on X509, then its error codes should align as well.  There are two ways to handle this: 

- Push multiple errors onto the stack, but that seems wrong, because there really is but one error.
- Align CMS error codes so that they match those of X509 (j above).  That's only risky for those
  client apps where they are not using the defined mnemonics.

**Comment by mattcaswell** [comment]
I'm not sure I understand the issue. In the above code isn't the original error (j) added as "error data" to the CMS error?

**Comment by elear** [comment]
Thanks, @mattcaswell  for your interest.  The issue is that (j) isn't directly returned or exposed to the calling application.  Instead, you end up with a string associated with a vague verify error.  I don't want the string.  I want j, so that I can give specific advice without having to parse strings.

**Comment by mattcaswell** [comment]
Perhaps a simple solution would be to add the error number as part of the error data. You'd still have to parse a string - but it would be straight forward.

**Comment by elear** [comment]
That wouldn't be my first choice, for the obvious reasons.

**Comment by mattcaswell** [comment]
How about using a verify callback? This would enable you to get hold of the error code directly.

````
int verify_callback(int ok, X509_STORE_CTX *ctx) {
    int j;

     j = X509_STORE_CTX_get_error(ctx);
    /* Do something with j */

    return ok;
}
````

Then just call `X509_STORE_set_verify_cb()` on your `X509_STORE` before passing it to the CMS code.

**Comment by elear** [comment]
I'll give that a shot.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
