### ISSUE TITLE
NCONF_load fails when config file has a "\" at the wrong place

### ISSUE THREAD

**Issue by ChrisBFX** [openssl/openssl#8038]
We encountered a strange error when we tried to sign a certificate using the openssl cli with a very long custom extension (basically a json string encoded as an UTF8 string).
We included the extension inside the configuration file like documented here https://www.openssl.org/docs/man1.1.0/apps/x509v3_config.html.

example:
```
[req_extensions]
1.3.6.1.4.1.99999.3.100.10.10=ASN1:UTF8String:"[{\"licenseType\":\"rent\",\"dateStart\":\"2017-05-28T00:00:00+00:00\",\"dateEnd\":\"2020-02-29T00:00:00+00:00\",\"isOem\":true,\"isBrandable\":true,\"comment\":\"some fillup to reach more than 510 characters in one line to fool openssls unescape reader.some fillup to reach more than 510 characters in one line to fool openssls unescape reader.some fillup to reach more than 510 characters in one line to fool openssls unescape reader.123456789\",\"multiTenancy\":true}]"
```

When loading this configuration file openssl strips the last backslash which then results in some corrupt json.

During debugging we found the responsible code for this behavior in https://github.com/openssl/openssl/blob/master/crypto/conf/conf_def.c#L295
Which looks quite strange for me. Why would you need to strip some escaping characters when reading a file in parts?

Hope this was clear enough, if not feel free to ask for more information.

**Comment by levitte** [comment]
To explain this further, it seems this is about the limit of the internal line buffer, and we simply truncate lines that are longer, or something like that.
