### ISSUE TITLE
x509_check_purpose returns error

### ISSUE THREAD

**Issue by kalyani-k** [openssl/openssl#8044]
Hi,
I am using openssl 1.0.2n version and have an issue using the function x509_check_purpose function.
I am using this function to verify the signed certificate with the private key got created during CSR generation. But the x509_check_purpose is returning error. the manual page for this functions is not available in openssl org site. below is the code snippet. when I tried to match the certificate with the private key through a online tool, both are matching. and also this piece of code is working for a different set of certificates. 
Please help me to identify what's going wrong in my case.

```C
cert = load_cert(bio_err, certfile, FORMAT_PEM);
	if(cert == NULL) 
	{ 
		return(1); 
	}
rc = X509_check_purpose( cert, 2, 0 );
	if ( rc == 0 )
	{
		rc = X509_check_purpose( cert, 3, 0 );
		if ( rc == 0 )
		{
		***********error debug printed here saying it is not a server certificate() *************
		return(2);
		}
	}
````
what does 2, 3 which are defined as 'id' as per this function definition specify. after this, there's a below code to check private key. what do the x509_check_purpose does and do we really need to check this? 
````
	rc = X509_check_private_key(cert, pkey);
	if(rc == 0) 
	{
		return(1);
	} else 
	{
		return(0);
	}
```

**Comment by mattcaswell** [comment]
See PR #10301 which adds documentation for this function and should help you understand its usage.
