### ISSUE TITLE
OPENSSL_strnlen SIGSEGV in o_str.c line 76

### ISSUE THREAD

**Issue by blastwave** [openssl/openssl#8048]
After 1.1.1a finally builds on Solaris 10 with Oracle Studio 12.6 and C99 strict CFLAGS 
the tests begin to fail instantly thus : 

../test/recipes/01-test_abort.t .................... ok
../test/recipes/01-test_sanity.t ................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

This happens because of a core dump in sanitytest thus : 

t@1 (l@1) program terminated by signal SEGV (no mapping at the fault address)
Current function is OPENSSL_strnlen
   76       for (p = str; maxlen-- != 0 && *p != '\0'; ++p) ;
(dbx) where
current thread: t@1
=>[1] OPENSSL_strnlen(str = 0x14f180 "<bad address 0x000000000014f180>", maxlen = 2147483646U), line 76 in "o_str.c"
  [2] fmtstr(sbuffer = 0xffffffff7fffda60, buffer = 0xffffffff7fffda50, currlen = 0xffffffff7fffd908, maxlen = 0xffffffff7fffda58, value = 0x14f180 "<bad address 0x000000000014f180>", flags = 0, min = 0, max = 2147483647), line 376 in "b_print.c"
  [3] _dopr(sbuffer = 0xffffffff7fffda60, buffer = 0xffffffff7fffda50, maxlen = 0xffffffff7fffda58, retlen = 0xffffffff7fffe268, truncated = 0xffffffff7fffda4c, format = 0x100042c9f "", args = 0xffffffff7fffe4f0), line 309 in "b_print.c"
  [4] BIO_vprintf(bio = 0x10014c7e0, format = 0x100042c98 "%d - %s", args = 0xffffffff7fffe4e0), line 880 in "b_print.c"
  [5] test_vprintf_stdout(fmt = 0x100042c98 "%d - %s", ap = 0xffffffff7fffe4e0), line 42 in "basic_output.c"
  [6] test_verdict(pass = 1, extra = 0x100042c98 "%d - %s", ... = (nil), ...), line 165 in "driver.c"
  [7] run_tests(test_prog_name = 0xffffffff7ffff9d8 "../../test/sanitytest"), line 212 in "driver.c"
  [8] main(argc = 1, argv = 0xffffffff7ffff798), line 51 in "main.c"
(dbx) list
   76       for (p = str; maxlen-- != 0 && *p != '\0'; ++p) ;
   77   
   78       return p - str;
   79   }
   80   
   81   size_t OPENSSL_strlcpy(char *dst, const char *src, size_t size)
   82   {
   83       size_t l = 0;
   84       for (; size > 1 && *src; size--) {
   85           *dst++ = *src++;
(dbx) 

Of course that address is insane. 

(dbx) print p
dbx: warning: cannot recreate macro information for o_str.c -- unrecognized compiler : /opt/developerstudio12.6/bin/c99
p = 0x14f180 "<bad address 0x000000000014f180>"
(dbx) 

Dennis

**Comment by mattcaswell** [comment]
Looks like some strangeness related to va_arg processing.

**Comment by blastwave** [comment]
The work around is to simply not try strict C99 and then no such problem happens.

**Comment by richsalz** [comment]
OpenSSL doesn't claim compatibility with C99, just C90.  So using the proper compiler isn't a work-around, it's a requirement. :)  Turn off the flag.

**Comment by blastwave** [comment]
It was fun to try :-)  flag gone !

**Comment by richsalz** [comment]
So this can be closed?

**Comment by blastwave** [comment]
Sorry .. never should have existed in the first place. Really the user mail list is better for this sort of thing but that seems to be pretty quiet these days.

**Comment by blastwave** [comment]
I realize this is a bit old however it seems odd that strict C90 fails : 
.
.
.

make[1]: Entering directory '/opt/bw/build/openssl-1.1.1d_debian_sid_i686_5.3.7-genunix.001'
make[1]: Leaving directory '/opt/bw/build/openssl-1.1.1d_debian_sid_i686_5.3.7-genunix.001'
make[1]: Entering directory '/opt/bw/build/openssl-1.1.1d_debian_sid_i686_5.3.7-genunix.001'
/usr/bin/gcc-9  -I. -Iinclude -fPIC -std=c90 -pedantic -pedantic-errors -Wpedantic -fno-builtin -march=i686 -mtune=i686 -Wl,-rpath=/opt/bw/lib,--enable-new-dtags -mpc80 -pthread -Wa,--noexecstack -std=c90 -pedantic -pedantic-errors -Wpedantic -fno-builtin -march=i686 -mtune=i686 -Wl,-rpath=/opt/bw/lib,--enable-new-dtags -mpc80 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/bw/ssl\"" -DENGINESDIR="\"/opt/bw/lib/engines-1.1\"" -DNDEBUG -I/opt/bw/include -D_POSIX_PTHREAD_SEMANTICS -D_TS_ERRNO -D_LARGEFILE64_SOURCE -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
In file included from include/openssl/x509.h:30,
                 from apps/apps.h:26,
                 from apps/app_rand.c:10:
include/openssl/sha.h:91:36: error: ISO C90 does not support 'long long' [-Wlong-long]
   91 | #  define SHA_LONG64 unsigned long long
      |                                    ^~~~
include/openssl/sha.h:96:5: note: in expansion of macro 'SHA_LONG64'
   96 |     SHA_LONG64 h[8];
      |     ^~~~~~~~~~
include/openssl/sha.h:91:36: error: ISO C90 does not support 'long long' [-Wlong-long]
   91 | #  define SHA_LONG64 unsigned long long
      |                                    ^~~~
include/openssl/sha.h:97:5: note: in expansion of macro 'SHA_LONG64'
   97 |     SHA_LONG64 Nl, Nh;
      |     ^~~~~~~~~~
include/openssl/sha.h:91:36: error: ISO C90 does not support 'long long' [-Wlong-long]
   91 | #  define SHA_LONG64 unsigned long long
      |                                    ^~~~
include/openssl/sha.h:99:9: note: in expansion of macro 'SHA_LONG64'
   99 |         SHA_LONG64 d[SHA_LBLOCK];
      |         ^~~~~~~~~~
make[1]: *** [Makefile:708: apps/app_rand.o] Error 1
make[1]: Leaving directory '/opt/bw/build/openssl-1.1.1d_debian_sid_i686_5.3.7-genunix.001'
make: *** [Makefile:174: all] Error 2
Command exited with non-zero status 2


I can try C89 however I am not sure what difference that would make. 

Dennis
