### ISSUE TITLE
how the macro : OPENSSL_SMALL_FOOTPRINT worked in ARM architecture.

### ISSUE THREAD

**Issue by hucailai** [openssl/openssl#8052]
Hi Rich Salz:

we are reducing the libsize of libssl and libcrypto in ARM architecture.

we got a macro OPENSSL_SMALL_FOOTPRINT.but it look like effective only in X86 architecture.

```
#if defined(__i386) || defined(__i386__) || defined(_M_IX86)
# define SMALL_REGISTER_BANK
# if defined(WHIRLPOOL_ASM)
#   define OPENSSL_SMALL_FOOTPRINT
#  endif
```
if we  force define the macro OPENSSL_SMALL_FOOTPRINT，it will any problem ？

**Comment by bernd-edlinger** [comment]
I suppose you will configure with no-whirlpool anyway, and just add -DOPENSSL_SMALL_FOOTPRINT
to your config arguments.

**Comment by richsalz** [comment]
Should be fine to do so.
