### ISSUE TITLE
BUG - extracted data include additional "\r" symbols

### ISSUE THREAD

**Issue by WarlordXXX** [openssl/openssl#8056]
When decrypt and extracted signed data - data include additional "\r" symbols, this is BUG.
For details see https://github.com/gost-engine/engine/issues/104#issue-399317697

OS: Windows 7 64-bit
OpenSSL 1.1.1a 32-bit

**Comment by mattcaswell** [comment]
What happens if you use the "-binary" option to the cms command line app?

**Comment by WarlordXXX** [comment]
> What happens if you use the "-binary" option to the cms command line app?

Thanks, it worked :D
