### ISSUE TITLE
Configure option no-* do not work as expected

### ISSUE THREAD

**Issue by bjxiangy** [openssl/openssl#8057]
When building openssl 1.1.1a, use following option for configuration. After build and installation (make DESTDIR=$INSTALLDIR install), disabled algorithms header file are still copied to installation directory. 

$PERL ./Configure \
  zlib-dynamic \
  no-idea \
  no-mdc2 \
  no-rc5 \
  no-hw \
  no-egd \
  no-engine \
  enable-tls1_3 \
.....
The header files still exist.
./include/openssl/rc5.h
./include/openssl/idea.h
./include/openssl/engineerr.h
./include/openssl/mdc2.h

**Comment by levitte** [comment]
Yes.  This is a change that came about with OpenSSL 1.1.0, for user convenience, i.e. we no longer force everyone to do this (and get it wrong):

``` C
#include <openssl/opensslconf.h>
#ifndef OPENSSL_NO_RC5
# include <openssl/rc5.h>
#endif 
#ifndef OPENSSL_NO_IDEA
# include <openssl/idea.h>
#endif 
/* ... you get the idea */
```

instead, you can include everything present.  If you look inside those header files, you will however see that their contents are guarded with similar `#ifndef OPENSSL_NO_whatever`, so your access to the actual APIs is still restricted by the `no-` options.

**Comment by mspncp** [comment]
> ```c
> ...
> #ifndef OPENSSL_NO_IDEA
> # include <openssl/idea.h>
> #endif 
> /* ... you get the idea */
> ```

Pun intended @levitte? ;-)

**Comment by levitte** [comment]
> Pun intended @levitte? ;-)

Hahaha, I so wish it was!
