### ISSUE TITLE
1.0.1s makes porting to HP-UX much harder than before

### ISSUE THREAD

**Issue by Tux** [openssl/openssl#806]
Let me take HP-UX 11.11/PA2 as an example.
Up to and including 1.0.1r, I just unpacked from the distributes .tar.gz and ran
```
$ ./Configure zlib zlib-dynamic no-asm hpux64-parisc2-cc
$ perl -pi -e's/\+O3/+O2 +Z -AC99/' Makefile
$ make
$ make test
$ make install
```
And all went well.
As of 1.0.1s, a new tool is required that is not available in HP-UX land: makedepend
```
$ ./Configure zlib zlib-dynamic no-asm hpux64-parisc2-cc
⋮
make[1]: Leaving directory `/pro/3gl/openssl-1.0.1s/test'

Configured for hpux64-parisc2-cc.

*** Because of configuration changes, you MUST do the following before
*** building:

        make depend
$ make depend
making depend in crypto...
make[1]: Entering directory `/pro/3gl/openssl-1.0.1s/crypto'
../util/domd[30]: makedepend:  not found.
mv: Makefile.new: cannot access: No such file or directory
make[1]: *** [local_depend] Error 127
make[1]: Leaving directory `/pro/3gl/openssl-1.0.1s/crypto'
make: *** [depend] Error 1
```
The makedepend tool is *very* hard to build from scratch on HP-UX, as it depends on a plethora of (recent) GNU tools that are obviously also not available on HP-UX. I build a lot of OpenSource projects on HP-UX, and this is the first that needs makedepend.
Building makedepend requires pkg-config, which also fails to build.

For 11.11, makedepend is available in HP's imake package (imake-6.00 from 2002), if I install that, I do have makedepend, but it might not do what is expected: I have no way to tell.

```
$ perl -pi -e's/\+O3/+O2 +Z -AC99/' Makefile
$ make depend
⋮
$ make
⋮
$ make test
⋮
rc4-40
rc4-40 base64
seed
seed base64
seed-cbc
seed-cbc base64
seed-cfb
seed-cfb base64
seed-ecb
seed-ecb base64
seed-ofb
seed-ofb base64
zlib
9223376434892769432:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.so): Unable to find library 'libz.so'.
9223376434892769432:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:232:
9223376434892769432:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:463:
9223376434892769432:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.so): Unable to find library 'libz.so'.
9223376434892769432:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:232:
9223376434892769432:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:463:
cmp: EOF on ./p.zlib.clear
make[1]: *** [test_enc] Error 1
make[1]: Leaving directory `/pro/3gl/openssl-1.0.1s/test'
make: *** [tests] Error 2
```
That used to pass. The problem in above fail is that something is told to look for libz.so, where on HP-UX/PA the naming convention for shared libraries is libz.sl
I did not spot an obvious location in the build procedure to fix that

So

1. Where does the sudden need for makedepend come from and can it please be removed? (as there are no packages available anywhere that make makedepend available for HP-UX 11.00 and older, they are ruled out forgood by this change)

2. Where should I look for having PA-RISC search for .sl instead of .so

(Note that AIX only has .a, and it is shared by default)

**Comment by gabsoftware** [comment]
You can install https://h20392.www2.hp.com/portal/swdepot/displayProductInfo.do?productNumber=HPDesktopDev

Then add makedepend on your PATH (or make a symbolink link of it to a directory in your path).

Its location is /opt/imake/bin/makedepend

**Comment by Tux** [comment]
That package is for 11.31 (HP-UX Developer's Toolkit for HP-UX 11i v3).

My issue was raised against 11.00 and older.

FWIW 11.31 (11iv3) is only available for Itanium, not for PA-RISC. (Well, there has been a release that should have worked on PA-RISC, but you can safely rule them out as non-existent)

**Comment by gabsoftware** [comment]
How about https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=B3394BA ?

> The HP-UX Developer's Toolkit consists of libraries used for developing user interfaces. It includes X11R6 archive libraries, Motif 2.1 archive libraries, HP CDE 2.1 archive libraries, sample programs, man pages, header files for X11R6, Motif2.1, HP CDE 2.1, Audio and Image products **and Imake utilities**. The Toolkit provides a complete set of tools for developing applications that incorporate such features as a graphical user interface, imaging, audio, and an on-line Help system. The HP-UX Developer's Toolkit is available for **11.00**, 11i and 11i Itanium® releases. **PA releases consist of the complete set of all the above mentioned toolkits**

**Comment by gabsoftware** [comment]
I needed OpenSSL to build Nginx. Now working perfectly, I have HTTP/2 enabled Nginx running on my 11.31i.

**Comment by richsalz** [comment]
So, the makedepend that was mentioned above should be fine.
I don't know about the shared library extension; we made no changes, so maybe this is a new config you are trying?
1.0.1 only gets security fixes now.
closing this.
