### ISSUE TITLE
compilation error clang80: error: argument unused during compilation: '-stdlib=libc++'

### ISSUE THREAD

**Issue by jjvargas** [openssl/openssl#8062]
Anyone getting this error when compiling for android?
clang80: error: argument unused during compilation: '-stdlib=libc++'

Cheers

**Comment by r0l1** [comment]
Have a look at: https://github.com/golang/go/issues/29706
This might help you.

**Comment by artob** [comment]
More specifically, the NDK toolchain bug is discussed at: https://github.com/android-ndk/ndk/issues/849

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
