### ISSUE TITLE
$ANDROID_NDK not defined for cross-compiling

### ISSUE THREAD

**Issue by xerta555** [openssl/openssl#8066]
Hello

I'm trying to cross-compile openssl for Android archs with NDK to get curl binary files for Android by following this thread:
https://gist.github.com/jhandley/a5e9ab2fe09e7addde6f

I have ajust it with the new links versions for each depedencies, but when i try to configure the cross-compile for openssl with theses settings:

./Configure android-armv7 no-asm no-shared --static --with-zlib-include=${ZLIB_DIR}/include --with-zlib-lib=${ZLIB_DIR}/lib

I get this error:
`Configuring OpenSSL version 1.1.1a (0x1010101fL) for android-arm
Using os-specific seed configuration
$ANDROID_NDK is not defined at (eval 6) line 26.`

I tried to browse the Configure file with nano, but i don't know where i need to set the ANDROID_NDK path.

Maybe that i don't make a step propeply ?

**Comment by levitte** [comment]
[`INSTALL`](https://github.com/openssl/openssl/blob/master/INSTALL) says this early on:

```
 For additional platform specific requirements, solutions to specific
 issues and other details, please read one of these:

  * NOTES.UNIX (any supported Unix like system)
  * NOTES.VMS (OpenVMS)
  * NOTES.WIN (any supported Windows)
  * NOTES.DJGPP (DOS platform with DJGPP)
  * NOTES.ANDROID (obviously Android [NDK])
```

You might want to take a look at the appropriate NOTES file.
