### ISSUE TITLE
Unable to set "uncompressed" only ec_point_formats

### ISSUE THREAD

**Issue by alimtolman** [openssl/openssl#8067]
There's an issue in t1_lib.c in procedure tls1_get_formatlist.
It should be like this
````
void tls1_get_formatlist(SSL *s, const unsigned char **pformats, size_t *num_formats)
{
    /*
     * If we have a custom point format list use it otherwise use default
     */
    if (sizeof(s->ext.ecpointformats) > 0) { /* Modified line */
        *pformats = s->ext.ecpointformats;
        *num_formats = s->ext.ecpointformats_len;
    } else {
        *pformats = ecformats_default;
        /* For Suite B we don't support char2 fields */
        if (tls1_suiteb(s))
            *num_formats = sizeof(ecformats_default) - 1;
        else
            *num_formats = sizeof(ecformats_default);
    }
}
````

or like this
````
void tls1_get_formatlist(SSL *s, const unsigned char **pformats, size_t *num_formats)
{
    /*
     * If we have a custom point format list use it otherwise use default
     */
    if (s->ext.ecpointformats_len > 0) { /* Modified line */
        *pformats = s->ext.ecpointformats;
        *num_formats = s->ext.ecpointformats_len;
    } else {
        *pformats = ecformats_default;
        /* For Suite B we don't support char2 fields */
        if (tls1_suiteb(s))
            *num_formats = sizeof(ecformats_default) - 1;
        else
            *num_formats = sizeof(ecformats_default);
    }
}
````

Explanation:
When you set s->ext.ecpointformats to TLSEXT_ECPOINTFORMAT_uncompressed, the value is 0 and old condition 
````
if (s->ext.ecpointformats)
````
is always false.

**Comment by mattcaswell** [comment]
Well `s->ext.ecpointformats` is a `char *` type. It points to a *buffer* containing the custom point formats. So if `s->ext.ecpointformats` points to a buffer containing `TLSEXT_ECPOINTFORMAT_uncompressed`, then it will be non-NULL and so the condition will evaluate to true.

However, you are right that the condition always evaluates to false - but for a different reason. AFAICT there is no way of setting a custom `ecpointformats` buffer in the first place!! Therefore the buffer is always NULL.

**Comment by alimtolman** [comment]
But there's in some cases I needed to set custom ec_point_formats. By the way I think that it should be changed.

**Comment by mattcaswell** [comment]
Well, from looking at the code., it was clearly the original intention that you should be able to set a custom ec_point_formats list - it was just never fully implemented. So either I think we need to remove that code entirely, or complete the implementation to enable it to be set.

I'm curious to know why you would want to set a custom list.

**Comment by alimtolman** [comment]
In some cases it can be use as security condition to block unauthorized requests. Cuz' no one looking at http extension's when making requests.

**Comment by mattcaswell** [comment]
Are you suggesting that some servers reject requests based on the contents of the ec_point_formats??? I have never encountered such a server? Configuring a server in such a way would seem.....strange. I see 0 security benefit in doing so.

**Comment by alimtolman** [comment]
It’s not about real security. It’s just one of condition that can be used. As I said no one looking at http extensions when making requests. Any way in the OpenSSL the ec_point_formats can be custom, right? I’m just suggesting to make it work correctly.

**Comment by mattcaswell** [comment]
> Any way in the OpenSSL the ec_point_formats can be custom, right?

Well there is some code in there which seems to be for that purpose. But AFAICT there is no public API for it. So one way we can "fix it" is to just remove the code.

**Comment by alimtolman** [comment]
I just made changes that I’ve wrote in first message and it worked. It’s possible to set it. The ,ec_point_formats, variable is public and contains in ext structure in ,ssl_st, and in ,ssl_ctx_st, so I can set it and it will work. I’ve already tested it.

**Comment by mattcaswell** [comment]
> The ec_point_formats variable is public and contains in ext structure in ssl_st and in ssl_ctx_st so I can set it and it will work. 

This is not correct. The `ecpointformats` variable is defined in ssl_st and ssl_ctx_st - but both of those structures are opaque. They are only defined in ssl_locl.h which is a private internal OpenSSL header file not for use by end user applications. If you are accessing these things from your application then you're not doing it right!

In order to make it public we would have to implement additional "getter" and "setter" functions.

**Comment by alimtolman** [comment]
Well. Then I’m doing it in wrong way. So may be you need to make custom editable? Because tls1_get_formatlist void checking is custom or not. It’ll be really helpful and will make extensions fully editable.
