### ISSUE TITLE
Only 32 KeyUpdates allowed per-connection

### ISSUE THREAD

**Issue by agl** [openssl/openssl#8068]
The use of [`key_update_count`](https://github.com/openssl/openssl/blob/master/ssl/statem/statem_lib.c#L617) strictly limits the number of TLS 1.3 KeyUpdate messages to 32 on a connection, irrespective of how long-lived the connection is or how much data is passing over it. While limiting a flood of KeyUpdate messages without any application data flow makes sense, a limit this strict seems like it'll trip up applications that try to rotate keys every <i>x</i> MBs of data, or <i>y</i> hours of time, etc.

(Note, in BoringSSL we have the same variable but it limits the number of _consecutive_ KeyUpdate messages. So application data resets the count. The limit there is just designed to avoid being an unbounded sink of network data without the upper levels of the stack ever seeing an event.)

**Comment by tomato42** [comment]
also, given that it requires just three HKDF-Expand-Label calculations per KeyUpdate received, it's not very efficient DoS mechanism – it's comparable to just decrypting the message in the first place.

sending appdata consisting only of padding will have very similar effect on server

**Comment by mattcaswell** [comment]
Fix in #8095
