### ISSUE TITLE
Documentation unclear for EVP_PKEY_get_raw_public_key and EVP_PKEY_get_raw_private_key for 25519 keys

### ISSUE THREAD

**Issue by zpostfacto** [openssl/openssl#8070]
The documentation for these functions says:

> The number of bytes written is populated in *len. If the buffer priv is NULL then *len is populated with the number of bytes required to hold the key. The calling application is responsible for ensuring that the buffer is large enough to receive the private key data.

Actually we found that you need to set the len argument to the size of your buffer before you call it.  (This is for X25519 and ED25519 keys, at least.)

I noticed that some functions in OpenSSL that have signatures like this have in/out arguments, so you have to set the size to the size of your buffer calling the function.  For others, it's strictly an output argument, and your buffer just needs to be big enough.  (e.g. EVP_EncryptUpdate).

EVP_DigestSignFinal is an example of a function that does requires you to set the length to the size of your buffer before calling. it.  The documentation for that function reads:

> If sig is not NULL then before the call the siglen parameter should contain the length of the sig buffer. 

So: For EVP_PKEY_get_raw_public_key, is the documentation wrong, or the code?  I could make a PR if I know which is correct.

**Comment by mattcaswell** [comment]
Well, I checked how this was implemented for other algorithms (not just X25519/ED25519). HMAC, Poly1305, Siphash, X448 and Ed448 all check `*len` to ensure that the buffer is large enough before using it. So I think it is the documentation that is wrong (well, no so much wrong, but more "missing an important piece of information").

**Comment by slontis** [comment]
This was fixed by https://github.com/openssl/openssl/pull/11254
