### ISSUE TITLE
ftps/ftpes serve support in openssl library through API

### ISSUE THREAD

**Issue by Rohit2387** [openssl/openssl#8072]

**Comment by mspncp** [comment]
@Rohit2387 if you are looking for a C-API based on OpenSSL which implements ftps, you might want to have a look at [libcurl](https://curl.haxx.se).

**Comment by Rohit2387** [comment]
Hi,

I dont want to use any other library.I want to use openssl API and want to host ftps server.Libcurl supprot ftp,sftp but i want ftps support.

**Comment by mspncp** [comment]
Are you sure that curl does not support ftps? A 30 second google search brought me to this page:

https://curl.haxx.se/libcurl/c/ftpsget.html

Anyway, OpenSSL is a TLS implementation which happens to provide also a public Crypto API. But FTPS is out of the scope of this project. So I'm closing this issue.

**Comment by Rohit2387** [comment]
The link which you have mentioned,contains client code to get file from server.I want server hosting Support.

**Comment by mspncp** [comment]
Then I would suggest that you search further whether someone has already implemented one using libcurl and/or post a question to the curl mailing list. Here you are definitely wrong.

**Comment by Rohit2387** [comment]
OK Thanks
