### ISSUE TITLE
How to reduce the footprint of openssl-1.1.1.

### ISSUE THREAD

**Issue by siabc123si** [openssl/openssl#8078]
HI,

I upgraded openssl version from 1.0.2k to 1.1.1 version.

Upon compiling final linux image,  noticed any increase of overall footprint of image by ~500KB.

Details about compilation can be found on bug https://github.com/openssl/openssl/issues/7840.

This is for arc CPU.

Is there a way to reduce the size of openssl-1.1.1 foot print ? ( tried -DOPENSSL_SMALL_FOOTPRINT but not much difference)

Thanks,

**Comment by FdaSilvaYY** [comment]
You may read  https://github.com/openssl/openssl/blob/master/INSTALL, 
and them try the various `no- ` option depending on your use case.
1st suggestion : no-srp, no-ct, no-sm2, no-dtls ...

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
