### ISSUE TITLE
s_client -verify_return_error does not seem to work

### ISSUE THREAD

**Issue by hannob** [openssl/openssl#8079]
According to the docs:
```
-verify_return_error
Return verification errors instead of continuing. This will typically abort the handshake with a fatal error.
```

However it does not seem to work:
```
openssl s_client -verify_return_error -connect expired.badssl.com:443 -servername expired.badssl.com
```
Shows an error (certificate has expired), but continues the connection.

Same for
```
openssl s_client -connect google.com:443 -verify_hostname foo -verify_return_error
```
Shows "Hostname mismatch", but continues the connection.

**Comment by mattcaswell** [comment]
I believe you have to use it in combination with the "-verify" option if you want the handshake to abort. I'm not sure if that is a documentation error or a bug in the code.

**Comment by mattcaswell** [comment]
Yes, I agree. Something needs to change. I'm just undecided at the moment as to the best approach to fixing it. Probably we should just make it match the documentation.
