### ISSUE TITLE
Two functions misnamed in compat API when moving from 1.0.2 to 1.1.x

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8084]
Change: https://github.com/openssl/openssl/commit/6ddbb4cd92ad8c9ebf874e5d9920c122696b7477

In this change the functions `X509_STORE_get1_certs` and `X509_STORE_get1_crls` were renamed to  `X509_STORE_CTX_get1_certs` and `X509_STORE_CTX_get1_crls` respectively. Additionally, #define statements were added to attempt to maintain compatability, however they were named incorrectly. They were named `X509_STORE_get1_cert` and `X509_STORE_get1_crl` instead. Please fix this so the API remains compatible.

**Comment by mspncp** [comment]
See #8086
