### ISSUE TITLE
ossl_init_load_crypto_nodelete leaks when built staticly

### ISSUE THREAD

**Issue by reanimus** [openssl/openssl#8085]
I found this occurred when running statically-linked. When built without OPENSSL_USE_NODELETE, the DSO loading code will fail. dlfcn_load will add some error data, but ERR_add_error_vdata doesn't check that the error state isn't null before allocating a buffer and copying data into it. When it calls ERR_set_error_data, the check occurs there and the function returns immediately, leaking the buffer passed into it.

Ideally, ERR_add_error_vdata ought to check error state before copying out data.

**Comment by mattcaswell** [comment]
Fix in #8105.
