### ISSUE TITLE
Windows7 nmake test failure test\recipes\02-test_errstr.t Dubious, test returned 19

### ISSUE THREAD

**Issue by FlemishGiant** [openssl/openssl#8091]
Hello,
This is my first time working with OpenSSL so please forgive me if I have missed something obvious.

using  OpenSSL 3.0.0-dev according to README
(Should I maybe just take a step back and go to 1.1.1?)

I configured OpenSSL using:
>perl configure VC-WIN32

then successfully built using:
>nmake

from the Developer Cmd Prompt VS2015

Failure occurs when I run:
>nmake test

The following results, only one of the tests fails, command line returns:
![image](https://user-images.githubusercontent.com/47034716/51755251-351b4280-208c-11e9-983b-00a2083b49f8.png)

"test\recipes\02-test_errstr.t .................... Dubious, test returned 19 <wstat 4864, 0x1300>
Failed 19/73 subtests "

All other tests come back as "ok" or "skipped" due to not available or not supported.

Test Summary Report is as follows:
![image](https://user-images.githubusercontent.com/47034716/51755315-5a0fb580-208c-11e9-9014-c24961441b51.png)

Please let me know if you require any additional information.
Thank you for your time!

**Comment by mattcaswell** [comment]
Strange. This works for me with VS2015 on Windows 8.1. I don't have a Win7 machine to test on.

Please can you give the output from running this command:

````
nmake TESTS=test_errstr V=1 test
````

**Comment by mattcaswell** [comment]
Incidentally this is a new test not included in the latest release of 1.1.1 (i.e. 1.1.1a). It *is* in the latest 1.1.1 dev branch so will be in the forthcoming 1.1.1b whenever that comes out - so it would be good to get this fixed. If you just need to get going then you could download and use 1.1.1a and it should work by virtue of not having the test to run :-)

**Comment by FlemishGiant** [comment]
Thank you very much Matt,
see attached for the output of:
>nmake TESTS=test_errstr V=1 test

[nmake_test.txt](https://github.com/openssl/openssl/files/2797298/nmake_test.txt)


I see an Arg list too long and a permission denied at the top of the output. Could this be a permissions issue?

**Comment by FlemishGiant** [comment]
Just to comment for someone else that may encounter this issue in the near future, using 1.1.1 works just fine as mattcaswell stated above, but I personally needed to run my developer command prompt as admin in order to install at the default location "Program Files (x86)"(which makes sense). But I only needed admin when installing, all other steps work fine without admin.  

Thank you very much for your help here mattcaswell!

**Comment by levitte** [comment]
Ah, this seems to be all the network related POSIX errors, which depends on WinSock being initialized or not.  So from the results reported so far here, it appears this initialization happens automatically or earlier in newer Windows versions, but not in Windows 7.

The easiest solution is to blacklist those error numbers in that test recipe.

**Comment by levitte** [comment]
Would you mind trying #8094?

**Comment by FlemishGiant** [comment]
Test appears to yield the same results. Please advise if I may have missed something.

I went to issue #8094 and copied the file as you had edited in the last commit and put it in place. Tests still appear to return the same errors though (appears to be identical, I'll place the verbose if you wish)

One other note, I didn't realize until I had installed the previous version that the libraries libeay and ssleay are no longer created in these later versions, but the end result of my efforts will require these libraries. So I had to revert to 1.0.2 anyhow to get these libraries, which by the way, worked just fine with 0 problems.

**Comment by levitte** [comment]
FYI, 1.0.2 (and therefore libeay and libssl) is reaching end of life at the end of this year, i.e. we will stop supporting it.

**Comment by mattcaswell** [comment]
> Tests still appear to return the same errors though

This test is about checking OpenSSL's internal cache of system error strings match what we expect for the platform. As such it is normal output to see error strings in the verbose output.

> I'll place the verbose if you wish

Please can we see the verbose output?

**Comment by FlemishGiant** [comment]
See attached:

[openssl-verbose_test-test_errstr.txt](https://github.com/openssl/openssl/files/2803754/openssl-verbose_test-test_errstr.txt)

Like I said, output looks the same as before I changed the file.
