### ISSUE TITLE
memcpy used to copy overlapped memory

### ISSUE THREAD

**Issue by HeYoushang** [openssl/openssl#8099]
the following code pass `crl` and `crl->sha1_hash` into `X509_CRL_digest` , 
https://github.com/openssl/openssl/blob/e85d19c68e7fb3302410bd72d434793e5c0c23a0/crypto/x509/x_crl.c#L175
and in `X509_CRL_digest` , `memcpy` is used to copy `data->sha1_hash` to `md`, then the source and destination addresses are the same, as follows, 
https://github.com/openssl/openssl/blob/e85d19c68e7fb3302410bd72d434793e5c0c23a0/crypto/x509/x_all.c#L383
the behavior of copying overlapped memory used by `memcpy` is undefined.

**Comment by mattcaswell** [comment]
Yes, I agree. Fix in #8104.
