### ISSUE TITLE
support standard ANDROID_NDK_HOME env var

### ISSUE THREAD

**Issue by eighthave** [openssl/openssl#8101]
Though not well documented, the standard environment variable for the Android NDK is `ANDROID_NDK_HOME` not `ANDROID_NDK`.  It would be nice if OpenSSL also supported that.  Here are some references:

* https://github.com/googlesamples/android-ndk/wiki
* https://docs.bazel.build/versions/master/tutorial/android-app.html
* https://blog.gauravagarwalr.com/posts/2018-04-11-setting-up-flutter/
* https://android.googlesource.com/platform/external/conscrypt/+/master/.travis.yml#28
* https://android.googlesource.com/platform/tools/cmake-utils/+/cmake-master-dev/android.toolchain.cmake#130

**Comment by levitte** [comment]
Have a look at #8103
