### ISSUE TITLE
`openssl pkcs12 -twopass` does not work

### ISSUE THREAD

**Issue by jack-fortanix** [openssl/openssl#8107]
If you use `-twopass` option with `pkcs12`, it does ask for a second password, but it does not use it for the MAC, instead it still uses the encryption password. Here I enter "mac" when prompted for the MAC key and use "xyzzy" as the encryption key.

```
$ openssl pkcs12 -export -inkey rsa.key -in rsa.crt  -name Bongo -out twopass.pfx -passin pass:xyzzy -passout pass:xyzzy -twopass 
Enter MAC Password: <enter mac>
Verifying - Enter MAC Password: <enter mac>
$ openssl pkcs12 -in twopass.pfx -passin pass:xyzzy
Bag Attributes
    friendlyName: Bongo
...
$ openssl pkcs12 -in twopass.pfx -twopass
Enter MAC Password: <enter mac>
Enter Import Password: <enter xyzzy>
Mac verify error: invalid password?
$ openssl pkcs12 -in twopass.pfx -twopass
Enter MAC Password: <enter xyzzy>
Enter Import Password: <enter xyzzy>
Bag Attributes
    friendlyName: Bongo
...
```

I see this with both OpenSSL 1.1.0g and latest master.

**Comment by mattcaswell** [comment]
The issue here is that, when exporting, the `-twopass` option cannot be used in conjunction with the `-passout` option. You could be forgiven for not knowing this since the pkcs12 app silently ignores the option rather than complaining about it, and the restriction is not documented! Fix for those issues in #8114.

**Comment by jack-fortanix** [comment]
> pkcs12 app silently ignores the option rather than complaining about it

If it ignores it, then why did it ask me for a MAC password?

**Comment by mattcaswell** [comment]
It goes ahead and asks for the password - but then silently ignores it. Hence #8114 which prevents that.
