### ISSUE TITLE
openssl Root CA issue

### ISSUE THREAD

**Issue by ChongqingDuan** [openssl/openssl#8119]
Recently I was learning OpenSSL, Find an interesting thing.
Certificate
RootCAfile
ClientCAfile(sign by IntermediateCAfile)
SeverCAfile(sign by IntermediateCAfile)

client code
SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);
SSL_CTX_load_verify_locations(CTX, RootCAfile,null)
SSL_CTX_use_certificate_file(ctx, ClientCAfile, SSL_FILETYPE_PEM)

This configuration handshake is successful. but when I use wireshark tool to Analysis. find sever send all Certificate to client. Why send the root certificate? "SSL_CTX_load_verify_locations" is load verify certificate for verify the peer certificate. 

issue:
Why send the Root certificate? like this, It is not safe for the session. or I understand is not correct?
so I hope someone can answer my confusion.
thanks

**Comment by richsalz** [comment]
The TLS protocol definitions allow someone to send upto, but not including, the root; both behaviors are legal.

One reason to send the root is if there are two CA’s that signed the certificate, and you want to explicitly give the recipient a path through the PKI chain.

**Comment by ChongqingDuan** [comment]
>           The TLS protocol definitions allow someone to send upto, but not including, the root; both behaviors are legal.
> 
> One reason to send the root is if there are two CA’s that signed the certificate, and you want to explicitly give the recipient a path through the PKI chain.

thanks Richsalz Answer .
"someone to send upto, but not including the root"
-> This mean not send  Root CA, right？
such, How can I successfully verify the sever certificate, at same time not send out Root CA certificate.
maybe copy the Root CA in the Client Side first?  But during verification, Client Sile how find the Root CA certificate？ and than for verify the sever certificate？

**Comment by richsalz** [comment]
The server can send the root, or not send the root.  The client must have a list of roots that it is willing to trust. In browsers, they typically call this the trust store; in OpenSSL it’s the X509_STORE object. It is the obligation of your program to populate it.

**Comment by kaduk** [comment]
In particular, it is the obligation of your program to populate it, because to do otherwise involves trusting any random blob that claims to be a root CA and is sent to you over the (assumed hostile) network.  Doing so removes all the security provided by TLS, so it is not something that TLS practitioners would consider.

**Comment by ChongqingDuan** [comment]
>  it is the obligation of your program to populate it
But after verify sever, Client silde still Automatically send out all certificate (include ClientCA, IntermediateCA, RootCA) to sever.No filter Root certificate. 

 I hope only send out ClientCA,  How should I modify it?

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
