### ISSUE TITLE
s_client returned protocol version is confusing

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8123]
When using OpenSSL 1.1.1 s_client, when connecting to server using TLS 1.2 it will print information like this (omitting certificate for brevity):
```
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: DH, 2048 bits
---
SSL handshake has read 3369 bytes and written 474 bytes
Verification: OK
---
New, TLSv1.2, Cipher is DHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES128-GCM-SHA256
    Session-ID: 1A492810EBC7EED481E317C24F7603B8815412B878968E1834A68A9066A8E1E6
    Session-ID-ctx: 
    Master-Key: A4FF98985C1F686CE3D0C70D7A34A99D0096243A12BD43296FBB3D26A79372C51981059BCC015E33957C60F10C9601B3
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1548865483
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
The version is returned in two places:
```
New, TLSv1.2, Cipher is DHE-RSA-AES128-GCM-SHA256
```
and
```
    Protocol  : TLSv1.2
```

when negotiating some other cipher and protocol, the information may look like this:
```
---
Acceptable client certificate CA names
O = Example CA
Client Certificate Types: RSA sign, ECDSA sign, DSA sign
Peer signing digest: MD5-SHA1
Peer signature type: RSA
Server Temp Key: DH, 2048 bits
---
SSL handshake has read 3426 bytes and written 1551 bytes
Verification: OK
---
New, SSLv3, Cipher is DHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.1
    Cipher    : DHE-RSA-AES128-SHA
    Session-ID: 692C1185B5CB799A4E2689F3852B0DADF8C250B2123E8EBC7892D08D2EBE94DF
    Session-ID-ctx: 
    Master-Key: C67509476284C9D75CEFC9D0FF68DDBAAA74C61A239255A3599FF4CB15FE29F5F356E19000B9487C7E1E7F12259FE5D1
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1548865404
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
Giving two *different* protocol versions:
```
New, SSLv3, Cipher is DHE-RSA-AES128-SHA
```
and
```
    Protocol  : TLSv1.1
```

why is that? the version returned in the `New` line is not the version of the _connection_. it's the protocol version of the _cipher_!

The bigger problem is that when negotiating TLS 1.3 the *complete* output from s_client may look like this (when the server doesn't send NewSessionTicket):
```
CONNECTED(00000003)
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
---
Certificate chain
 0 s:CN = localhost
   i:CN = localhost
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC+zCCAeOgAwIBAgIJALEP97+mvF6wMA0GCSqGSIb3DQEBBQUAMBQxEjAQBgNV
BAMMCWxvY2FsaG9zdDAeFw0xNTAzMDMxNTUzNDhaFw0yNTAyMjgxNTUzNDhaMBQx
EjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAOYz+2ar/b83RjKoFvYG7Zff7N0BT7qWdSzP6k03r2czbRo0+L1Afh6TLGz/
H66PftmXDaEPADmmJ8DjiQW05eTDV7HiVLXHG1YK4a7VhdMODFLUjV1w1rip1i/C
WAEbLHZPQZ0gN4bexY1Y7HY5cF5brCbRFHGpSHIj1Jdo3zJBawJpqM9nHDz04nVd
pJKFat8PbGrrGZBhXpg/opwg5GVAbbVroG8Nt7ATeIzY4YCaUS/9rs7J0qV6tatz
egUEGg6aCdsu4FrGQFA2/RRCtEF8H5A6gPdwTex4COR+RVXbaWUnlwyfTRjAVF2x
FiWA0WShLeTblixMxv42qUZidHUCAwEAAaNQME4wHQYDVR0OBBYEFFpCTwDYmMcu
zo+fxFRZJTIChcHqMB8GA1UdIwQYMBaAFFpCTwDYmMcuzo+fxFRZJTIChcHqMAwG
A1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBABF66SE6d9Px5nTjuwvq3112
Vw3l1ejJFwauYY36ctPnuNgG0V0A7Hs5ksAvsSe+SGedzASr9vRDy/aZ007Voo4a
tmP3vVtyjT2EHSXWFxLRNVr+vPnFCEBjPVpbmRNeB5odGjFh9oG6UmcdvlS/4rAI
pVOeGw0kx/yXpGRkVB6kc+XcsEi45ERIEYBBdE1RU04y/Q0YfPi6jXF6hTV7bIoH
LEKV/td6Edje2ihjlz33amR8qOv6wH1vUiRj3VRp+aegnigTq3S+FO9mmh7tP/Wg
DOOM6qxItHCcnphOYzY2gaQM5YnsLVmr3HUn/IEUT4uf2VjDNz/a7JWebscQsZI=
-----END CERTIFICATE-----
subject=CN = localhost

issuer=CN = localhost

---
No client certificate CA names sent
Peer signing digest: SHA512
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1257 bytes and written 391 bytes
Verification error: self signed certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 18 (self signed certificate)
---
```

Meaning that there is no information about negotiated protocol version, only the information derived from the cipher negotiated.

So I think that the information returned by `s_client` is confusing and unreliable. Either the `New` line should provide the protocol version of the connection, or the output should include a new line that provides the negotiated protocol version, even if the server didn't send a NST.

**Comment by t8m** [comment]
Yeah, I agree that not printing the summary SSL session information in this case is wrong.

**Comment by mattcaswell** [comment]
Agreed this is confusing. The s_client/s_server output could be made clearer.

**Comment by erbsland-dev** [comment]
@t8m @mattcaswell @tomato42

The code responsible for these confusing outputs is located here:

The cipher version is displayed after either `New,` or `Reused,` in the following lines:
https://github.com/openssl/openssl/blob/2c3f1a6cad300e3812aee34dab98f23a329296f4/apps/s_client.c#L3482-L3485

The current session's protocol version is output here:
https://github.com/openssl/openssl/blob/2c3f1a6cad300e3812aee34dab98f23a329296f4/apps/lib/s_cb.c#L686-L688

I think I can write a PR to improve this situation, but I don't use these tools regularly and am unsure about the expected output. Could you please advise on what the output should be at these points? What should be added or modified to make the outputs clearer?

**Comment by tomato42** [comment]
this: ` SSL_CIPHER_get_version(c), ` is wrong, it should report the negotiated version of the SSL object instead

**Comment by t8m** [comment]
> this: `SSL_CIPHER_get_version(c),` is wrong, it should report the negotiated version of the SSL object instead

No, I do not think this would be right. The version of the cipher must be kept as is.

Perhaps the s_client output could look like:
New, Cipher is DHE-RSA-AES128-SHA (SSLv3)

That could make it more clear that the version is associated with the cipher suite not the version negotiated.

Perhaps we could add additional output of the protocol version negotiated?

**Comment by tomato42** [comment]
that still leaves the issue of the output not actually including the negotiated protocol version in case the server didn't send a NewSessionTicket...
Also, frankly, I find the information of "which protocol version was the cipher introduce in" completely useless...
if you think providing it, then having it as `(SSLv3)` would be fine
but then I think we need additional field that reports the real protocol version.

**Comment by t8m** [comment]
> that still leaves the issue of the output not actually including the negotiated protocol version in case the server didn't send a NewSessionTicket... Also, frankly, I find the information of "which protocol version was the cipher introduce in" completely useless... if you think providing it, then having it as `(SSLv3)` would be fine but then I think we need additional field that reports the real protocol version.

I agree that the version of the cipher is not much useful but we can introduce larger changes only in 4.0.

And yeah, I've suggested outputting the negotiated protocol version in addition to that.

**Comment by erbsland-dev** [comment]
@tomato42 @t8m With this PR, the output looks like this:

```console
/usr/local/bin/openssl s_client tufa.ost.educateit.ch:443
Connecting to ***
CONNECTED(00000005)
(...)
---
New, Cipher is TLS_AES_256_GCM_SHA384 (TLSv1.3)
Protocol: TLSv1.3
Server public key is 384 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 10 (certificate has expired)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: AFEADFCD3040C90A127F1745AB543DB74623B0E37552D326B580AC14F9C2B878
(...)
```

I have omitted large parts of the output to focus on the relevant lines. I have a few questions to better understand and improve the output:

1. **Cipher Version**: I’m not entirely sure what exactly the cipher version represents. It seems to use the same naming convention as the protocol version, which adds to the confusion. Could you provide some clarity on this?

2. **Protocol Version from Context vs. Session**: I do not fully understand the difference between the protocol version indicated in the SSL context and the SSL session. Could you explain how these versions differ and why both are significant?

I appreciate your guidance on these points to ensure the output is as clear and useful as possible.

**Comment by erbsland-dev** [comment]
It seems some tests rely on this output and are now failing. I will take a closer look at this tomorrow.
