### ISSUE TITLE
Build FIPS capable OpenSSL for iOS 11

### ISSUE THREAD

**Issue by amrithathorath** [openssl/openssl#8128]
Is there a set of instructions that can be followed to build FIPS capable OpenSSL for iOS 11?

**Comment by paulidale** [comment]
If the instructions from the user guide cannot be **exactly** followed, it isn't possible.

For Unix like platforms this is:

```
./config
make
make install
```

No changes are permitted, no extra arguments, no intervening commands.

**Comment by lisarabe** [comment]
I know there are scripts to build OSSL on older versions of iOS (such as this:  https://github.com/virtru/iOS-openSSL-FIPS/tree/develop ) but I haven't seen any for newer versions.

**Comment by lisarabe** [comment]
There are scripts to build on older versions of iOS (such as this: https://github.com/virtru/iOS-openSSL-FIPS/tree/develop ) but I don't know of any that work for newer versions.

**Comment by lisarabe** [comment]
There are scripts to build on older versions of iOS (such as this: https://github.com/virtru/iOS-openSSL-FIPS/tree/develop ) but I don't know of any that work for newer versions.

**Comment by paulidale** [comment]
Those scripts don't follow the mandated build process -- the result will not be FIPS compliant.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
