### ISSUE TITLE
openssl/INSTALL makes numerous references to version 1.1.0 despite being 1.1.1

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8129]
Some help files seem to still be out of date for 1.1.1 and and reference 1.1.0. A quick code grep should be done for "1.1.0"/"1.1.x" to see if any other locations need to be changed.

**Comment by mlindner** [comment]
https://github.com/openssl/openssl/blob/c4734493d7da404b1747195a805c8d536dbe6910/INSTALL#L976
https://github.com/openssl/openssl/blob/c4734493d7da404b1747195a805c8d536dbe6910/INSTALL#L1082

Those are two I noticed, but didn't look at other files.

**Comment by levitte** [comment]
#8130 is my proposed adjustment, please give it a look

**Comment by levitte** [comment]
@mlindner, thanks for your patience
