### ISSUE TITLE
Can't set renegotiation_info extension

### ISSUE THREAD

**Issue by alimtolman** [openssl/openssl#8143]
When I do ```SSL_renegotiate``` the ```renegotiation_info ``` extension is not added.
```SSL_renegotiate``` is calling after ```SSL_connect```
Is it wrong?
I've tried to look through code and everything seems good but extension isn't adding.

using OpenSSL 1.1.1a

**Comment by mattcaswell** [comment]
How do you know that the extension hasn't been added? i.e. how are you checking this? My tests with s_server/s_client do show this being added correctly.

What TLS protocol version has been negotiated? Note that SSL_renegotiate() will not work at all if TLSv1.3 is negotiated.

**Comment by alimtolman** [comment]
I’ve used Charles to check extensions in the request. And I’m using TLSv1.2

**Comment by mattcaswell** [comment]
What happens if you attempt to use s_client to connect to your server (via Charles)? Once s_client connects enter "R" (followed by the enter key) to initiate a renegotiation. Do you see the extension then?

**Comment by alimtolman** [comment]
It shows that “Renegotiation IS supported” but after sending “R” I’m getting error “num=20:unable to get local issuer certificate”

**Comment by alimtolman** [comment]
I've tried to use ```SSL_CTX_add_custom_ext``` but it's also doesn't work. There's no way to add ```renegotiation_info``` to extensions?

**Comment by mattcaswell** [comment]
> It shows that “Renegotiation IS supported” but after sending “R” I’m getting error “num=20:unable to get local issuer certificate”

This should just be a warning, and shouldn't prevent the handshake from completing. Can you check whether it did and whether the ClientHello has the extension?

> I've tried to use SSL_CTX_add_custom_ext but it's also doesn't work. There's no way to add renegotiation_info to extensions?

`renegotiation_info` is a builtin extension and should get added automatically. You cannot explicitly add such extensions (`SSL_CTX_add_custom_ext` will only work for extensions not known by OpenSSL).

**Comment by alimtolman** [comment]
> This should just be a warning, and shouldn't prevent the handshake from completing. Can you check whether it did and whether the ClientHello has the extension?

The extensions is sending before I’ll send “R”. So the ClientHello doesn’t contain this extension. It’s just impossible.

> `renegotiation_info` is a builtin extension and should get added automatically. You cannot explicitly add such extensions (`SSL_CTX_add_custom_ext` will only work for extensions not known by OpenSSL).

So how should I add it? Idk what to try.

**Comment by alimtolman** [comment]
I think I should use Wireshark to check the second ClientHello. I’ll try asap.

What about initial ClientHello? Is it possible to add ‘’’renegotiation_info’’’ to the extensions (not in s_client)?

**Comment by kaduk** [comment]
Please see RFC 5746 Section 3.4 for a description of the expected client behavior in the initial handshake, in particular the semantic equiavlence between the SCSV and the extension.

**Comment by mattcaswell** [comment]
> I think I should use Wireshark to check the second ClientHello. I’ll try asap.

You'll need to set Wireshark up to decrypt the traffic if you're going to do that. The second ClientHello is encrypted. Doesn't Charles enable you to see this?

> What about initial ClientHello? Is it possible to add ‘’renegotiation_info’’ to the extensions (not in s_client)?

No, this isn't possible and is not necessary. OpenSSL uses a different mechanism to indicate renegotiation_info support in the initial ClientHello. Specifically it sends a special ciphersuite (TLS_EMPTY_RENEGOTIATION_INFO_SCSV) in the initial ClientHello instead.
