### ISSUE TITLE
S390 build is broken by latest changes to rc4/build.info

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#8155]
This is a build issue for S390 on master:
The build is looking for rc4-s390x.s and not finding it because it has been changed in rc4/buildinfo to be an uppercase .S extension.

------------->
gcc  -I. -Icrypto/include -Iinclude -I.. -I../crypto/include -I../include  -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DB_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DAES_ASM -DAES_CTR_ASM -DAES_XTS_ASM -DGHASH_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/scratch/nsegen/jenkins/workspace/openssl-linux_s390x/install/ssl\"" -DENGINESDIR="\"/scratch/nsegen/jenkins/workspace/openssl-linux_s390x/install/lib/engines-\"" -DNDEBUG  -MMD -MF crypto/rc2/libcrypto-lib-rc2ofb64.d.tmp -MT crypto/rc2/libcrypto-lib-rc2ofb64.o -c -o crypto/rc2/libcrypto-lib-rc2ofb64.o ../crypto/rc2/rc2ofb64.c
make[1]: *** No rule to make target `crypto/rc4/rc4-s390x.s', needed by `crypto/rc4/libcrypto-lib-rc4-s390x.o'.  Stop.
make[1]: Leaving directory `/scratch/nsegen/jenkins/workspace/openssl-linux_s390x/build-linux_s390x'

--------------->
I assume 00-base-templates.conf needs to be changed to use 	rc4_asm_src     => "rc4-s390x.S",

**Comment by levitte** [comment]
The assumption is incorrect, what needs to be changed is `crypto/rc4/build.info`

There is an automatic .S to .s conversion in the build file templates, which goes through the C Preprocessor....

Patience 'til tomorrow, please?

**Comment by slontis** [comment]
No hurry...

**Comment by levitte** [comment]
It was easier than I though...

**Comment by levitte** [comment]
Mind trying #8157?

**Comment by slontis** [comment]
It will take quite a bit longer than it took you to fix it as its in a CI loop :). I will try to manually test it if I can..

**Comment by slontis** [comment]
It appears to work with that change. I reverted the change and it still worked (until I manually deleted the .s file (doh))
