### ISSUE TITLE
AIX6_PPC64 build is broken when building app library and trying to link libcrypto (instead of libcryto64)

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#8156]
This is broken on master:

This was broken after the 21st of January (when the changes related to specifying shared_extension = "64.so.\$(SHLIB_VERSION_NUMBER) in 10-main.conf were added.

The error is:
${LDCMD:-cc} -q64 -qmaxmem=16384 -qro -qroconst -qthreaded -O -L. -Wl,-bsvr4   -o apps/openssl apps/openssl-bin-asn1pars.o apps/openssl-bin-ca.o apps/openssl-bin-ciphers.o apps/openssl-bin-cms.o apps/openssl-bin-crl.o apps/openssl-bin-crl2p7.o apps/openssl-bin-dgst.o apps/openssl-bin-dhparam.o apps/openssl-bin-dsa.o apps/openssl-bin-dsaparam.o apps/openssl-bin-ec.o apps/openssl-bin-ecparam.o apps/openssl-bin-enc.o apps/openssl-bin-engine.o apps/openssl-bin-errstr.o apps/openssl-bin-gendsa.o apps/openssl-bin-genpkey.o apps/openssl-bin-genrsa.o apps/openssl-bin-nseq.o apps/openssl-bin-ocsp.o apps/openssl-bin-openssl.o apps/openssl-bin-passwd.o apps/openssl-bin-pkcs12.o apps/openssl-bin-pkcs7.o apps/openssl-bin-pkcs8.o apps/openssl-bin-pkey.o apps/openssl-bin-pkeyparam.o apps/openssl-bin-pkeyutl.o apps/openssl-bin-prime.o apps/openssl-bin-rand.o apps/openssl-bin-rehash.o apps/openssl-bin-req.o apps/openssl-bin-rsa.o apps/openssl-bin-rsautl.o apps/openssl-bin-s_client.o apps/openssl-bin-s_server.o apps/openssl-bin-s_time.o apps/openssl-bin-sess_id.o apps/openssl-bin-smime.o apps/openssl-bin-speed.o apps/openssl-bin-spkac.o apps/openssl-bin-srp.o apps/openssl-bin-storeutl.o apps/openssl-bin-ts.o apps/openssl-bin-verify.o apps/openssl-bin-version.o apps/openssl-bin-x509.o  apps/libapps_a.a -lssl -lcrypto -lpthreads 
ld: 0711-317 ERROR: Undefined symbol: .OPENSSL_LH_strhash
ld: 0711-317 ERROR: Undefined symbol: .OPENSSL_die
ld: 0711-317 ERROR: Undefined symbol: .OPENSSL_sk_new_null
ld: 0711-317 ERROR: Undefined symbol: .OPENSSL_sk_pop_free
ld: 0711-317 ERROR: Undefined symbol: .OPENSSL_sk_push
ld: 0711-317 ERROR: Undefined symbol: .OPENSSL_sk_free
.....

It appears that it creates a libcrypto64.so so using -lcrypto probably wont work.. The 32 bit version works since it doesnt have the 64 tacked onto it.
.....
.....
shlib-v3_pcons.o crypto/x509v3/libcrypto-shlib-v3_pku.o crypto/x509v3/libcrypto-shlib-v3_pmaps.o crypto/x509v3/libcrypto-shlib-v3_prn.o crypto/x509v3/libcrypto-shlib-v3_purp.o crypto/x509v3/libcrypto-shlib-v3_skey.o crypto/x509v3/libcrypto-shlib-v3_sxnet.o crypto/x509v3/libcrypto-shlib-v3_tlsf.o crypto/x509v3/libcrypto-shlib-v3_utl.o crypto/x509v3/libcrypto-shlib-v3err.o  -lpthreads 
	rm -f libcrypto64.so &&  ar -X64 r libcrypto64.so libcrypto64.so.3
ar: creating an archive file libcrypto64.so

------------------------>
The configuration is:
    perl ../Configure --prefix=openssl-aix6_ppc64/install shared no-asm -DOPENSSL_NO_ASYNC aix64-cc

Perl information:

    perl
    5.24.0 for aix-64all

Enabled features:

    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    ktls                    [default]   OPENSSL_NO_KTLS
    afalgeng                [not-linux] 
    asan                    [default]   OPENSSL_NO_ASAN
    asm                     [option]    OPENSSL_NO_ASM
    crypto-mdebug           [default]   OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]   OPENSSL_NO_EGD
    external-tests          [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]   OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]   OPENSSL_NO_HEARTBEATS
    md2                     [default]   OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]   OPENSSL_NO_MSAN
    rc5                     [default]   OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]   OPENSSL_NO_SCTP
    ssl-trace               [default]   OPENSSL_NO_SSL_TRACE
    ubsan                   [default]   OPENSSL_NO_UBSAN
    unit-test               [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]   
    zlib-dynamic            [default]   
    ssl3                    [default]   OPENSSL_NO_SSL3
    ssl3-method             [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar -X64",
    ARFLAGS => "r",
    CC => "cc",
    CFLAGS => "-O",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib -X64",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c",
    aes_obj => "aes_core.o aes_cbc.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "bn_asm.c",
    bn_obj => "bn_asm.o",
    bn_ops => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-q64 -qmaxmem=16384 -qro -qroconst -qthreaded",
    chacha_asm_src => "chacha_enc.c",
    chacha_obj => "chacha_enc.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o",
    cppflags => "-D_THREAD_SAFE",
    cpuid_asm_src => "mem_clr.c",
    cpuid_obj => "mem_clr.o",
    defines => [  ],
    des_asm_src => "des_enc.c fcrypt_b.c",
    des_obj => "des_enc.o fcrypt_b.o",
    disable => [  ],
    dso_scheme => "dlfcn",
    ec_asm_src => "",
    ec_obj => "",
    enable => [  ],
    ex_libs => "-lpthreads",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "-Wl,-bsvr4",
    lib_cflags => "",
    lib_cppflags => "-DB_ENDIAN",
    lib_defines => [  ],
    lib_extension => "_a.a",
    md5_asm_src => "",
    md5_obj => "",
    modes_asm_src => "",
    modes_obj => "",
    module_cflags => "-qpic",
    module_cxxflags => "",
    module_ldflags => "-Wl,-G,-bsymbolic,-bexpall",
    padlock_asm_src => "",
    padlock_obj => "",
    perl_platform => "Unix",
    perlasm_scheme => "aix64",
    poly1305_asm_src => "",
    poly1305_obj => "",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    shared_cflag => "-qpic",
    shared_defflag => "-Wl,-bE:",
    shared_defines => [  ],
    shared_extension => "64.so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".a",
    shared_ldflag => "-Wl,-G,-bsymbolic",
    shared_rcflag => "",
    shared_target => "aix",
    sys_id => "AIX",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR = 
    BUILDFILE = 
    CC = 
    CROSS_COMPILE = 
    CXX = 
    HASHBANGPERL = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar -X64
    ARFLAGS         = r
    CC              = cc
    CFLAGS          = -O
    CPPDEFINES      = OPENSSL_NO_ASYNC
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = perl
    RANLIB          = ranlib -X64
    RC              = windres

**Comment by levitte** [comment]
The AIX shared library stuff is surrounded by AIX specific magic.  I suggest you read the commit history surrounding this, and I think @makr was involved (pardon me if I'm wrong)

**Comment by makr** [comment]
Something is really wrong above at the place where it does ```rm -f libcrypto64.so && ar -X64 r libcrypto64.so libcrypto64.so.3```. This just doesn't make sense. It is not referring to the correct variables. Or these variables don't have the necessary content for AIX.
Would need to review the changes of commit 9dd4ed2, as I think the changes done around the ```$simple: $full``` rule in the UNIX Makefile template might be the cause here. But I would need to run this on an AIX-box. This needs to wait until later this week ...

**Comment by levitte** [comment]
Ah, that gave me a bit of a clue.  The extension stuff has been reworked entirely in master, and it's quite possible that the AIX support was lost in the process.  Fortunately, I can compare with the 1.1.1 branch and see what's amiss.

**Comment by levitte** [comment]
#8162 should fix this issue, please try it out

**Comment by slontis** [comment]
Seems to build now.. Thanks.
