### ISSUE TITLE
DTLS code sends server items twice

### ISSUE THREAD

**Issue by mcr** [openssl/openssl#8166]
This is a tshark capture of some devices behind a Thread Gateway.
One is using mbedtls and the other is a custom stack (or mbedtls).
I am specifically writing about packet 42 and 43-47.  Note the approx. 1s delay.
Yes, it will get fragmented (sometimes called fragletted) by the 6lowpan 802.15.4 layer, but for me, it's all ethernet.  The 836 byte combined packet is big true, and may take some time to get to the end point.   It seems that packet 43 is a retransmit, and that something is deciding that it should send
smaller packets, so it is sending everything again.

Is there a way to set the initial packet size smaller so that it just sends packets 43-47?
I think that I started to report this last November, but I don't think that I finished the bug report.

(the actual IPv6 prefixes have been replaced with CAFE:BEEF:)

<pre>
   40 2737.571484297 CAFE:BEEF:f:68::2 → CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 DTLSv1.2 122 Hello Verify Request
   41 2737.612972542 CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 → CAFE:BEEF:f:68::2 DTLSv1.2 191 Client Hello
   42 2737.614732707 CAFE:BEEF:f:68::2 → CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 DTLSv1.2 936 Server Hello, Certificate, Server Key Exchange, Certificate Request, Server Hello Done
   43 2738.633423638 CAFE:BEEF:f:68::2 → CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 DTLSv1.2 172 Server Hello
   44 2738.633470711 CAFE:BEEF:f:68::2 → CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 DTLSv1.2 562 Certificate
   45 2738.633495270 CAFE:BEEF:f:68::2 → CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 DTLSv1.2 230 Server Key Exchange
   46 2738.633538213 CAFE:BEEF:f:68::2 → CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 DTLSv1.2 133 Certificate Request
   47 2738.633562419 CAFE:BEEF:f:68::2 → CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 DTLSv1.2 87 Server Hello Done
   48 2738.697945967 CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 → CAFE:BEEF:f:68::2 DTLSv1.2 77 Alert (Level: Fatal, Description: Handshake Failure)
   49 2738.709774560 CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 → CAFE:BEEF:f:68::2 DTLSv1.2 77 Alert (Level: Fatal, Description: Handshake Failure)
   50 2738.722205311 CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 → CAFE:BEEF:f:68::2 DTLSv1.2 77 Alert (Level: Fatal, Description: Handshake Failure)
   51 2738.730392184 CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 → CAFE:BEEF:f:68::2 DTLSv1.2 77 Alert (Level: Fatal, Description: Handshake Failure)
   52 2738.779531473 CAFE:BEEF:f:68:d45d:c2fb:9ffd:1339 → CAFE:BEEF:f:68::2 DTLSv1.2 77 Alert (Level: Fatal, Description: Handshake Failure)
</pre>

I am using openssl 1.1.1 (not A), although with a few patches in the CMS code.
As this is an interop issue with a pre-release stack from other manufacturers, I can not provide a way to reproduce this.  I can provide packet traces though.  Our test certificates are also not important and I could provide those, but we do not get to the point of doing DH anyway.

**Comment by mattcaswell** [comment]
There are a few functions that may or may not help. By default OpenSSL should query the underlying transport to try and figure out the MTU automatically. You can switch that off using the option `SSL_OP_NO_QUERY_MTU`.

You can set an explicit MTU size using `SSL_set_mtu` or `DTLS_set_link_mtu` (the former sets the MTU for the DTLS part of the packet, the latter sets the MTU for the whole packet (including any UDP/IP overheads)

**Comment by mcr** [comment]
The resend seems to be a typical exponential backup, as we 
If the correspondent sends me an ICMPv6 too big, that would come up through the UDP socket layer, and maybe would cause this behaviour.  (Well, we just looked for ICMPs, and didn't see any).
So I will take a look at the MTU logic; maybe it only gets kicked *after* the first packet is sent, and concludes with a rather smaller than expected size.  I guess we just want it consistent.
I will be increasing the initial timeout once I figure out how: for these small devices and the speed of the 802.15.4 networks, we definitely need to give them more initial time.
