### ISSUE TITLE
BIO_accept() fails to detect memory allocation

### ISSUE THREAD

**Issue by Dmitry-Me** [openssl/openssl#817]
`BIO_accept()` has this code:

    *ip_port = OPENSSL_zalloc(strlen(host) + strlen(port) + 2);
     strcpy(*ip_port, host);
     strcat(*ip_port, ":");
     strcat(*ip_port, port);

which fails to check that `OPENSSL_zalloc()` returned a non-null pointer. I could craft a patch but I have no idea of how to handle the error.

**Comment by richsalz** [comment]
I think the only reasonable thing to do is put the strcpy/strcat inside ```if (*ip_port != NULL)``` block.
And while you're there, put a blank line after the host/port local vars :)

**Comment by levitte** [comment]
I think @Dmitry-Me wonders what `BIO_accept()` should return when that error occurs...

**Comment by richsalz** [comment]
I know.  Filling in the pointer with NULL and succeeding seems okay.  This ain't gonna happen very often, unless there's other bugs in the program romping around on malloc structures

**Comment by levitte** [comment]
The alternative is to close the received socket, free `host` and `port` and set `ret = -1`, thereby forcing an error.  But yeah, when memory allocation fails, you're basically in an undefined state.

**Comment by richsalz** [comment]
Yes, I know you can close the socket and return ENOMEM.  Seems overkill to me, but I defer to you.

**Comment by levitte** [comment]
I leave it to @Dmitry-Me to decide.

**Comment by Dmitry-Me** [comment]
Great! Now I have a chance to craft another Heartbleed.

**Comment by mattcaswell** [comment]
Fixed in ad9a056
