### ISSUE TITLE
Option to Disable Documentation in Configure Script

### ISSUE THREAD

**Issue by iguessthislldo** [openssl/openssl#8170]
I'm currently doing a build of OpenSSL as part of a build in Travis and I would like to reduce the overall time of the build. I see there is a `no-tests` option but I noticed that OpenSSL `make` and `make install` spends more time dealing with the documentation than the actual libraries. I think that's probably a good thing overall, but I don't need the documentation in this case and I don't see a `no-docs` or similar option.

**Comment by mspncp** [comment]
The `install` target is actually split into three subtargets:

https://github.com/openssl/openssl/blob/8269e44f9e40831a497fe9f31ba1d65aeb49a5c1/Configurations/unix-Makefile.tmpl#L362

So try `make install_sw`, this should save your day ;-)

**Comment by iguessthislldo** [comment]
@mspncp That should take most of the time off the ssl build, thanks!

**Comment by mspncp** [comment]
You're welcome.  So can  this issue be closed?

_Side note: If you are building OpenSSL only as third party library and not expecting errors from building it, you might want to consider speeding it up further by doing a parallel build and install (e.g. `make -j8` and `make -j8 install`). Parallel builds used to be not entirely safe, but this was fixed only recently in #7583._

**Comment by iguessthislldo** [comment]
Yes, I'm closing it. Thanks for the tip, but I'm already using `-j N`. As for the safety warning, I'm using 1.1.1a so I'm assuming I have that fix.

**Comment by mspncp** [comment]
> I'm using 1.1.1a so I'm assuming I have that fix.

Yes, #7583 was merged to 1.1.1 in commit 201a33f4abb639527da28e83e6ae782907a1c114 before 1.1.1a was released.

**Comment by levitte** [comment]
> *Parallel builds used to be not entirely safe,*

Parallel *installs*

**Comment by mspncp** [comment]
Yeah, that’s what I _meant_ to say. :-)
