### ISSUE TITLE
Failed tests on windows build of OpenSSL 1.1.1a with no-shared and enable-crypto-mdebug

### ISSUE THREAD

**Issue by cmconti** [openssl/openssl#8171]
Running nmake test fails for OpenSSL 1.1.1a on windows.

test\recipes\05-test_rand.t ..................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests

As documented at https://www.openssl.org/docs/manmaster/man3/OPENSSL_init_crypto.html in a static windows build each thread should call OPENSSL_thread_stop before exiting.

In this case, the code in the test file test\drbgtest.c fails to do this.
updating the windows version of the thread_run function to make the call fixes the issue.
```
static DWORD WINAPI thread_run(LPVOID arg)
{
    run_multi_thread_test();
#ifdef OPENSSL_NO_DYNAMIC_ENGINE
    OPENSSL_thread_stop();
#endif
    return 0;
}
```
I'm not sure OPENSSL_NO_DYNAMIC_ENGINE is the correct macro to use, though it is definitely set when no-shared is used.

**Comment by levitte** [comment]
`OPENSSL_NO_DYNAMIC_ENGINE` is not the right macro, but is also not needed, because drbgtest is *always* linked with the static libcrypto library.

**Comment by levitte** [comment]
See if the patch from #8173 works well enough for you.

**Comment by cmconti** [comment]
Yes, it works for me.  Thanks.

**Comment by kroeckx** [comment]
Is there a reason this was reopened?

**Comment by levitte** [comment]
Er....  I have *no* idea.  I must have pressed the wrong button.  Closing.
