### ISSUE TITLE
OpenSSL PKCS#11 Engine

### ISSUE THREAD

**Issue by opensignature** [openssl/openssl#8182]
My first contribution to the native engine PKCS#11 is ready.
I took only a few lines of code from libp11 but it's almost all my work.
It 's just the beginning and has only one function, **to sign** but it is still already usable in the real world with some precaution.
ID, PIN and module-path are passed only through PKCS11-URI.
-inkey "pkcs11:id=%43%4e%53;pin-value=12345678;module-path=/usr/lib/cryptoki.so"
source is here: https://github.com/opensignature/openssl/pull/1/commits/9f40c468630c272aada6da096fed73fd4647b1d5

Antonio

**Comment by mattcaswell** [comment]
> I took only a few lines of code from libp11 but it's almost all my work.

Do you mean the few lines of code you took is your work? What does almost mean?

**Comment by opensignature** [comment]
Sorry, I was not clear.
parse_attribute and other functions come from libp11.
The rest is written by me.

**Comment by t-j-h** [comment]
You cannot copy non-trivial functions from other locations. You need to write your own.
That isn't a complicated function.

**Comment by t-j-h** [comment]
Note I added the license clash issue until the functions are rewritten. I don't see that as a major issue for you to resolve - I just don't want us as a group to forget about that item.
Hopefully the quick review feedback can be addressed.

**Comment by opensignature** [comment]
I have entirely rewritten the functions and I corrected the error handling.

**Comment by t-j-h** [comment]
Can you put that into a standard pull request please ...

**Comment by opensignature** [comment]
> Can you put that into a standard pull request please ...

https://github.com/openssl/openssl/pull/8200
