### ISSUE TITLE
blake3b assembler value out of range (Motorola 68000)

### ISSUE THREAD

**Issue by rc-matthew-l-weber** [openssl/openssl#8190]
openssl 1.1.1a in a Buildroot build using uclibc, GCC6, and Binutils 2.31.1
(Attached is the build config dump)
[buildconfig.txt](https://github.com/openssl/openssl/files/2845982/buildconfig.txt)

I first switched into the base build folder and built the asm (-S) for the crypto/blake2/blake2bc file.  Then the following to reproduce the specific error and get the asm causing it.

/accts/user/buildroot/output/host/bin/m68k-buildroot-uclinux-uclibc-gcc  -I. -Icrypto/include -Iinclude -fPIC -pthread -Wa,--noexecstack -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2   -fno-dwarf2-cfi-asm  -Wl,-elf2flt -static -mxgot -DHAVE_FORK=0 -DOPENSSL_NO_MADVISE -DOPENSSL_NO_ASYNC   -fno-dwarf2-cfi-asm  -Wl,-elf2flt -static -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR=""/etc/ssl"" -DENGINESDIR=""/usr/lib/engines-1.1"" -DZLIB -DNDEBUG -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -MMD blake2b.s 
blake2b.s: Assembler messages:
blake2b.s:11167: Error: value -32790 out of range

In the blake2b.s
  11142 .L13:
  11143         addq.l #8,%a4
  11144         addq.l #8,%a0
  11145         move.l -8(%a0),%a2
  11146         move.l -4(%a0),%a3
  11147         move.l 56(%a0),%d0
  11148         move.l 60(%a0),%d1
  11149         move.l -8(%a4),%d6
  11150         move.l %a2,%d2
  11151         eor.l %d0,%d2
  11152         move.l %a3,%d0
  11153         move.l -4(%a4),%d7
  11154         eor.l %d1,%d0
  11155         eor.l %d6,%d2
  11156         eor.l %d7,%d0
  11157         move.l %d2,-8(%a0)
  11158         move.l %d0,-4(%a0)
  11159         move.l %d2,-8(%a4)
  11160         move.l %d0,-4(%a4)
  11161         cmp.l %a1,%a4
  11162         jne .L13
  11163 .L5:
  11164         move.l -3500(%fp),%d0
  11165         add.l %d0,12(%fp)
  11166         sub.l %d0,16(%fp)
  11167         jne .L7
  11168         movem.l (%sp),#15612
  11169         unlk %fp
  11170         rts
  11171         .size   blake2b_compress, .-blake2b_compress
  11172         .align  2
  11173         .globl  BLAKE2b_Init
  11174         .type   BLAKE2b_Init, @function

**Comment by rc-matthew-l-weber** [comment]
I believe I should just set -DOPENSSL_NO_BLAKE2  as that archtecture doesn't look like a blake algo is applicable.

**Comment by rc-matthew-l-weber** [comment]
Then I failed on sha512 with a similar error

**Comment by kroeckx** [comment]
I have no idea why you get such an error. We do not have assembler for blake2, there is no blake2b.s in the source.

**Comment by rc-matthew-l-weber** [comment]
I created the file after initially getting the error.  I believe there is a binutils issue with this arch's toolchain as I then ran into a similar out of bounds on sha512

**Comment by kroeckx** [comment]
So this issue can be closed?

**Comment by rc-matthew-l-weber** [comment]
Yep. I'll reopen if I find more details.

**Comment by rc-matthew-l-weber** [comment]
Just a note for this archtecture there is a compiler/assembler issue.  It can be worked around by disabling blake2 and selecting OPENSSL_SMALL_FOOTPRINT to take a different sha512 algo path.
