### ISSUE TITLE
Set number of iterations for `openssl pkcs12` command

### ISSUE THREAD

**Issue by imgx64** [openssl/openssl#8194]
The `openssl pkcs12` command doesn't have options to set the number of key iterations and MAC iterations. It uses 2048 by default and they can be set to 1 by using `-noiter` and `-nomaciter`.

I'm proposing to add two new parameters to allow the user to set an arbitrary number of iterations. Unfortunately, `-maciter` is already taken by a legacy option, so I suggest calling these new options `-iters n` and `-maciters n`.

**Comment by mattcaswell** [comment]
The "enc" and "pkcs8" comands use `-iter` to specify the number of iterations so for consistency I would prefer `-iter` to `-iters`. It's unfortunate that `-maciter` is already taken. Especially as it effectively "does nothing" (it sets the mac iteration count to the default value, which seems fairly pointless). Maybe `-maciternum`???

**Comment by kaduk** [comment]
I'll note that having both ```-maciter``` and ```-maciters``` is a recipe for great user confusion.
(We have similar excitement in krb5 with the ```pkinit_identity``` and ```pkinit_identities``` configuration options, one of which is relevant for clients and the other for KDCs.)

**Comment by iamihalcea** [comment]
Would option names like `-setiter` and `-setmaciter` work? I can only see a few other examples that look like that for req and x509

**Comment by imgx64** [comment]
How about using `-maciter [n]` and checking if the next arg is a number? It would require modifying `opt.c` and possibly adding a new `valtype` to `OPTIONS`, but it's doable.

Or would that be a bad idea?

**Comment by mattcaswell** [comment]
> How about using -maciter [n] and checking if the next arg is a number? It would require modifying opt.c and possibly adding a new valtype to OPTIONS, but it's doable.

Hmmm...that could possibly work.

**Comment by richsalz** [comment]
Flags that take an optional parameter are very bad for usability.
