### ISSUE TITLE
Sparse array node size

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#8201]
The sparse array implementation from #8197 is geared towards indexing by NID.  For large memory devices, a NID will be located after exactly one pointer dereference.  For small memory devices, it is three.  Both of these settings are a _best guess_ as to the likely usages.

1. It would be straightforward to allow different power of two sizes for the node allocations.
2. It would be relatively easy to allow arbitrary sized node allocations.

The penalty for allowing either of these would be a performance reduction.
1. A variable power of two change would be a small penalty (more fields in the structure and non-constant shifts and masks).
2. An arbitrary would require the storage costs plus division and modulo operations which would likely be more expensive.

Some experience and a discussion would be useful before the current settings are modified.

**Comment by levitte** [comment]
Gut feeling: power of two should be sufficient.

[side note: I know some people who are fans of odd numbers (don't ask me why), so if power of two plus one is an option without too much of a penalty, that could be an option too....]

**Comment by romen** [comment]
I second the power of two gut feeling!.

**Comment by levitte** [comment]
(I removed the FIPS label, because this isn't specifically about the forthcoming FIPS module.  I'd argue that this label should be removed from PR #8197 as well)

**Comment by paulidale** [comment]
#8197 doesn't have the FIPS label and I can't see that it ever did.  I agree that this isn't FIPS related.

I don't think that 2ⁿ±1 would be any better than allowing anything.  2ⁿ is special in that division by it is a shift and modulo by it an AND.

There are reasons for avoiding powers of two (cache lines being that size e.g.), but I doubt they would be relevant here.

**Comment by levitte** [comment]
> #8197 doesn't have the FIPS label and I can't see that it ever did.

You're right!!!  I could have sworn ...  ah well, I must have confused it with another PR

**Comment by levitte** [comment]
I was only thinking 2ⁿ+1, not 2ⁿ±1, and was imagining that handling that lowest bit wouldn't be much of a challenge, but I haven't really looked into it, so I may be hugely wrong.  I defer to you :-)

**Comment by paulidale** [comment]
The Mersenne numbers, 2ⁿ-1, appear to be [possible](http://homepage.cs.uiowa.edu/~jones/bcd/mod.shtml).  They involve a loop to sum the base 2ⁿ-1 digits.

As the link also notes, some 2ⁿ+1 are possible.  The example given is 2²+1 = 5 and it only works because 3×5 = 15 = 2⁴-1 which reduces it to the 2ⁿ-1 case: j mod 5 ≡ (j mod 15) mod 5.

I don't think it is worth the extra effort and we should just accept the division and modulus cost if we want other than powers of two.  These operations aren't _that_ expensive on most machines.

**Comment by levitte** [comment]
Sure.  Was worth a thought, though, even if only to dismiss

**Comment by paulidale** [comment]
The size has been made compile time configurable with defaults of 12 or 4 bits depending on large or small memory model.  It must be a power of 2 still.

**Comment by romen** [comment]
I agree that with the width being completely configurable at build time and with reasonable default values this issue could be closed.

I guess the only reason to have it configurable at this point would be to have different sizes for different arrays.

**Comment by paulidale** [comment]
Two discussion points:

1. Are the current defaults reasonable?  My only concern at present is the 4096 pointer large memory node size being too large, but others might have different worries.

1. We have things already that are sparse and occupy a very different range of values to NIDs.  TLS cipher suites come to mind immediately.  Likewise, the PBE definitions in `builtin_pbe` in `crypto/evp/evp_pbe.c` that are indexed on two integer values (type and NID) which would easily map to a single integer.  Do these (and the inevitable others) justify allowing different sizes for different arrays?
