### ISSUE TITLE
ENG-Cryptodev func "bn2crparam" change the endianess of the converted binary number to BiG-endian.

### ISSUE THREAD

**Issue by pangupta** [openssl/openssl#8202]
On OpenSSL 1.1.0 code branch, I have a query on the below code snippet from the commit (https://github.com/openssl/openssl/commit/912d7c75d41a36bac2371f4e3a440eca86b6489b):

```
@@ -1022,24 +1020,16 @@ static int bn2crparam(const BIGNUM *a, struct crparam *crp)
     crp->crp_nbits = 0;

     bits = BN_num_bits(a);
-    bytes = (bits + 7) / 8;
+    bytes = BN_num_bytes(a);

-    b = malloc(bytes);
+    b = calloc(bytes,1);
     if (b == NULL)
         return (1);
-    memset(b, 0, bytes);

     crp->crp_p = (caddr_t) b;
    crp->crp_nbits = bits;

-    for (i = 0, j = 0; i < a->top; i++) {
-        for (k = 0; k < BN_BITS2 / 8; k++) {
-            if ((j + k) >= bytes)
-                return (0);
-            b[j + k] = a->d[i] >> (k * 8);
-        }
-        j += BN_BITS2 / 8;
-    }
+    BN_bn2bin(a, b);
     return (0);
}
```
The binary string output of the function BN_bn2bin(a, b)” is in big-endian form.
As per earlier implementation, the Big Num to binary conversion results in little-endian form.

Hence as a result of this commit, the converted binary string is reversed as compared to the earlier one.
Whereas the interpretation of the binary string at the cryptodev-linux is continued to be same.

=========================================================
To keep the converted binary string to little-endian, the correct implementation would be to use "BN_bn2lebinpad" instead of "BN_bn2bin".

**Comment by levitte** [comment]
I might add that `crparam2bn` has the same issue, just the other way around.

**Comment by levitte** [comment]
Would you mind trying out #8204 and see if that solved the problem correctly (and didn't introduce anything new)?

**Comment by pangupta** [comment]
I have verified it and found to be working correctly.

**Comment by levitte** [comment]
Cool, thank you!

**Comment by pangupta** [comment]
Thanks for the quick Code changes.

I have a generous request if you can update the commit information with the following:

Reported-by: Pankaj Gupta [pankaj.gupta@nxp.com](mailto:pankaj.gupta@nxp.com)
Tested-by: Pankaj Gupta [pankaj.gupta@nxp.com](mailto:pankaj.gupta@nxp.com)

If you think, I contributed a little by suggesting the change "BN_bn2lebinpad(a, b, bytes)" in bn2crparam(), then add:
Signed-off-by: Pankaj Gupta [pankaj.gupta@nxp.com](mailto:pankaj.gupta@nxp.com)

Thanks.

Regards
Pankaj

**Comment by levitte** [comment]
Oh dude, I'm sorry.  I would have done that in an instant if it wasn't for our policy to not rewrite history once it's been merged into the main branches.
