### ISSUE TITLE
VMS-specific bug in OpenSSL build configuration

### ISSUE THREAD

**Issue by mgdaniel** [openssl/openssl#8207]
Reported by Mark Berryman (<mark@theberrymans.com>)  on comp.os.vms; reproduced here.  This was derived from advice to OpenSSL builders on VMS platforms but should be considered as a refinement to the OpenSSL baseline.

Historically, OpenSSL has done symbol substitution in its configuration file as follows:
```
dir             = ssl1$root:[demoCA     # Where everything is kept
certs           = ${dir}.certs]         # Where the issued certs are kept
crl_dir         = ${dir}.crl]           # Where the issued crl are kept
database        = ${dir}]index.txt      # database index file.
new_certs_dir   = ${dir}.certs]         # default place for new certs.
certificate     = ${dir}]cacert.pem     # The CA certificate
serial          = ${dir}]serial.txt     # The current serial number
#crlnumber      = ${dir}]crlnumber      # the current crl number  - do we need .TXT or .?
crl             = ${dir}]crl.pem        # The current CRL
private_key     = ${dir}.private]cakey.pem      # The private key
```
Specify a dollar sign, a brace (or a parenthesis), the symbol name, and a closing brace.  At some point (somewhere in the 1.0.2 train it looks like) the OpenSSL team decided to make the enclosing braces optional. This means that if you have any dollar signs in your VMS file names (e.g. ssl1$root) then OpenSSL will try to treat the alphanumerics after the the $ as a symbol name and throw an error when it can't find it.

There are two ways to address this:
1. eliminate all dollar signs in your OpenSSL configuration file that are not used to indicate symbol substitution (such as replacing ssl1$root with a new logical name ssl1_root).
2. correct the code to make the enclosing braces once again mandatory.

The steps to do this are:
1. edit `[.crypto.conf]conf_def.c`
2. search for '$' (there should only be one instance)
3. change that line from
```
    else if (*from == '$') {
```
   to
```
#ifdef OPENSSL_SYS_VMS
     else if ((*from == '$') && ((from[1] == '{') || (from[1] == '('))) {
#endif
```
and rebuild OpenSSL.

A working configuration file is required for many OpenSSL operations. As you can see, I use the VMS-specific one distributed with SSL1.  I have used the above fix in OpenSSL 1.0.2o and later as well as in OpenSSL 1.1.1a.

**Comment by levitte** [comment]
> There are two ways to address this:
> 1. eliminate all dollar signs in your OpenSSL configuration file that are not used to indicate symbol substitution (such as replacing ssl1$root with a new logical name ssl1_root).
> 2. correct the code to make the enclosing braces once again mandatory.

There's actually a third way, and it's to escape the offending $, i.e.:

```
dir             = ssl1\$root:[demoCA     # Where everything is kept
```

There's also some confusion as to what OpenSSL team we're talking about...  As far as I recall, this has *always* been the situation in our source...  however, when DECompHP (it's hard to remember which one of them it was) packaged OpenSSL in their own SSL product, they decided to include the patch that you refer to.  *I want to clarify that they did share such patches with us*, I can't quite remember why we decided to incorporate some and not others at the time.

Quite frankly, I'm ambivalent regarding that particular change, because I can see confusion when transporting a config file, or even just having the knowledge from one system and having to struggle because it works subtly differently on a different platform.  I can mention that Windows users have their own struggle, as they must double evey \ they have in their paths.

So it's really a finger in the air kind of question, if we should have local variations in the syntax or not.

**Comment by mgdaniel** [comment]
The argument may be made that the OS vendor historically (HP/HPE) has made this change in its [Open]SSL releases and has stated (now VSI) intends to make this change in its future releases of the code and so having it in the OpenSSL baseline code would enhance code and behaviour compatibility between vendor-supplied and individual build-on-site installations.

**Comment by levitte** [comment]
Does the rest of @openssl have an opinion on this?

**Comment by t-j-h** [comment]
Follow your recommendation whatever it is :-)

**Comment by levitte** [comment]
Well, my take so far has been that the syntax should be platform agnostic, i.e. not having varying syntax conventions.  However, I understand the VMS folks, since `$` is a common symbol character on that platform, so there's this clash where VMS folks always have to remember to escape it, *which is unnatural from a VMS perspective*.

Note that if we do allow platform family variance for the syntax, we should also consider Windows, where `\` is the natural path delimiter...

So I'm ambivalent on the subject and need help deciding.

**Comment by kaduk** [comment]
I have a slight inclination to not vary the syntax with platform, but it is very slight and could probably be swayed in either direction.

**Comment by levitte** [comment]
I've thought about this issue off and on, and here's an idea that came to me today: what if we introduced a pragma?  After all, we have already introduced a directive, `.include`, so we *could* introduce others as well.  Example:

```
.pragma dollarid=true                   # Make dollar signs without following brace
                                        # part of the normal identity character set

dir             = ssl1$root:[demoCA     # Where everything is kept
certs           = ${dir}.certs]         # Where the issued certs are kept
crl_dir         = ${dir}.crl]           # Where the issued crl are kept
database        = ${dir}]index.txt      # database index file.
new_certs_dir   = ${dir}.certs]         # default place for new certs.
certificate     = ${dir}]cacert.pem     # The CA certificate
serial          = ${dir}]serial.txt     # The current serial number
#crlnumber      = ${dir}]crlnumber      # the current crl number  - do we need .TXT or .?
crl             = ${dir}]crl.pem        # The current CRL
private_key     = ${dir}.private]cakey.pem      # The private key

**Comment by levitte** [comment]
Hey, would you mind trying out the patch from #8882?  I'm not asking you to try master for the moment, there are currently other issues on VMS with that branch.  However, the #8882 patch should be applicable on 1.1.1.

**Comment by mgdaniel** [comment]
The original op commented (I invited him to participate directly in the discussion but so far) ...

I do have one problem with it.

For various reasons, I have multiple versions of OpenSSL in use on my system -
mainly due to the requirements of the package using OpenSSL.  I use the same
SSL configuration file for all of these versions (it is pointed to by the
logical name OPENSSL_CONF).  Since this change is not backwards compatible,
aren’t any versions of OpenSSL prior to when this gets implemented going to
choke on the presence of the .pragma statement in the configuration file?

Specifically, an error like this:
$ openssl req -new -x509 -nodes -days 3600 -batch -key t.t
req: Error on line 12 of config file "SSL1$ROOT:[000000]OPENSSL-VMS.CNF"
unable to find 'distinguished_name' in config
problems making Certificate Request
2070548160:error:0E06D06A:configuration file routines:NCONF_get_string:no conf
or environment variable:FREEWARE:[freeware.openssl-1^
.1^.1b.crypto.conf]conf_lib.c;1:269:

Mark B.

**Comment by levitte** [comment]
We did figure out an alternative Syntax with the `.include` directive, simply allow an equal sign between the directive and its value, i.e:

```
.pragma = dollarid:true
```

To older OpenSSL versions, that will simply look like an unused variable.

If you look at #8882, you will see that I implemented exactly that possibility.

**Comment by mgdaniel** [comment]
The original op commented: "Since he’s made the proposed change backwards compatible, it works for me.".  Thanks for your efforts Richard.
