### ISSUE TITLE
Abort in ssl3_pkt.c

### ISSUE THREAD

**Issue by hlsantos** [openssl/openssl#8228]
I have version 1.0.2.17 of ssleay32.dll and libeay32.dll and got a report of an abort at this location of ssl_pkt3.dll, the ssl3-write_byte() function, line 837:

       i = do_ssl3_write(s, type, &(buf[tot]), nw, 0);
        if (i <= 0) {
            /* XXX should we ssl3_release_write_buffer if i<0? */
            s->s3->wnum = tot;   <<---- ABORTS HERE
            return i;
        }

The s3 pointer probably went bad here.  It occurred during an FTP/TLS session connection drop.  It is intermittent.  I am tracing this down in our multi-threaded calling functions,  but I wanted to note the inline comment,:

    /* XXX should we ssl3_release_write_buffer if i<0? */

where possibly the coder's question of releasing the write buffer when i<0 is necessary in order to have a graceful exit with a negative return value allowing for the calling function to capture the possible socket drop.

Thanks

Hector Santos, Santronics Software
hsantos@isdg,net

**Comment by kroeckx** [comment]
Do you use the same SSL * from multiple threads?

**Comment by hlsantos** [comment]
I have an 15+ years old multiple internet protocols client/server design.  Much to recall about the design but we did follow the long history of OpenSSL multiple thread model.  This includes using WIndows Locks/Mutexes and TLS (Thread Local Storage) design to help separate dynamic objects.  Very complex model, it has all been debugged and solidified over the many years.   For the FTP Server, there is an implicit (port 990) vs explicit AUTH TLS/SSL design.  When starting the FTP server, a certificate is loaded and a SSL context created for the process.  For each connection or explicit call to AUTH TLS/SL, ssl_accept(ftpserver->GetContext(), ssl_options) is called.

I'm currently going thru a load/stress test, forcing drops during file transfers, and nothing so far, but of course, that doesn't mean anything.   

I was just wondering if there anything to consider with the coder's inline comment. if i < 0, i is there a socket error, i.e. like a drop?    I see what you mean if there was shared context between threads, you wouldn't be sure to release pointers at that point.

**Comment by mattcaswell** [comment]
> I was just wondering if there anything to consider with the coder's inline comment. if i < 0, i is there a socket error, i.e. like a drop?

That comment should just be removed. It is not necessary to call `ssl3_release_write_buffer()` at that point. All that function does is free up some memory that will get freed later anyway when `SSL_free()` is called.

**Comment by mattcaswell** [comment]
if `s->s3` is invalid or NULL at that point then something has gone badly wrong (probably somewhere else). It suggests some form of memory corruption (which could be due to threading issues as @kroeckx was probably thinking)

**Comment by hlsantos** [comment]
Within a single thread, I've been able to recreate socket drop file transfer aborts within ssl3_pkts.c and t1_enc.c.  100% repeatable.  Captured socket drop aborts are releasing session pointers, including ssl so this is all being re-investigated.  Could be a timing or initialing issue, while the data channel thread is doing I/O, pulling the rug from under its feet.  Async 101 stuff.  arggggggggggg.   Thanks for your input.

**Comment by mattcaswell** [comment]
Ok - so can this issue be closed for now?

**Comment by hlsantos** [comment]
I'll close it,  I can always open it up again if I find something,.  My stress loads connection drops abort within the sslwrite() code consistently in the same various spots.  I want to double check w/ prior openssl versions since its the only big change in our last release was for the TLS v1.3/EDHE Cipher server-side enabling.  I also want to find out why an exception catch around the sslwrite call is not trapping the aborts .   Thanks
