### ISSUE TITLE
OpenSSL deserves proper build system that works out of the box for iOS/Mac

### ISSUE THREAD

**Issue by pps83rbx** [openssl/openssl#8231]
Currently it does not work at all. There are tons of ios/mac specific targets and they simply do not work for me. People are hoardying all these github gist scripts for building openssl. Why openssl simply doesn't handle it properly? By far the most annoying build experience for ios/mac/simulator.

**Comment by levitte** [comment]
PRs welcome! I'm willing to help (I don't have access to Apple stuff, but could consider running a iOS emulator to help testing)

**Comment by kaduk** [comment]
On my macOS 10.13 machine, once XCode is installed, I can just

```
git clone https://github.com/openssl/openssl
./config
make
```
and everything works fine -- it even picks a 64-bit build, which has only been the case since fairly recently.  I really need something more concrete to figure out what is causing the OP to be confused.
Is it iOS builds specifically (or maybe just cross-builds for iOS)?  Can we please see specific examples of what doesn't work and how?

**Comment by paulidale** [comment]
I do the same here.  I seem to remember needing to change Perl away from the system default but that was for the tools repo not OpenSSL itself.

**Comment by pps83rbx** [comment]
I didn't even know about `./config` shouldn't be `./configure` in the first place (as that's what commonly is used?).
I thought I had to do `perl ./Configure ...` to build openssl on mac. I was mainly referring to ios and ios simulation targets. Mac version didn't have issues I think (I don't even remember it, I just built it and forgot about it). But ios and iossimulator just didn't work for me.

**Comment by richsalz** [comment]
OpenSSL doesn't use autotools, and has been using "config" and "Configure" for a very long time.

The answer to your issues is use "./config [your-flag-if-any]", as Ben said.

I think this issue can be closed.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
