### ISSUE TITLE
v1.1.1 does not obey explicitly deleted cipher strings

### ISSUE THREAD

**Issue by yawnbox** [openssl/openssl#8233]
Example: https://www.ssllabs.com/ssltest/analyze.html?d=0x1302.cyber.cafe

Purpose: to test explicit and singular cipher suite configurations for web proxy decryption. Cheers

```
$ openssl version
OpenSSL 1.1.1  11 Sep 2018

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

$ nginx -v
nginx version: nginx/1.15.5 (Ubuntu)

$ cat /etc/nginx/crypto/tls-0x1302.conf
ssl_dhparam /etc/nginx/crypto/dhparam.pem;
ssl_ecdh_curve secp384r1;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
ssl_protocols TLSv1.3;
ssl_ciphers "TLS_AES_256_GCM_SHA384:!TLS_CHACHA20_POLY1305_SHA256:!TLS_AES_128_GCM_SHA256";
```

**Comment by mattcaswell** [comment]
This is an nginx configuration question. The above ciphersuites are for TLSv1.3 and are configured differently to TLSv1.2 and below ciphersuites in OpenSSL 1.1.1. You need to figure out how nginx handles that configuration difference. I suggest you ask on an nginx support forum.
