### ISSUE TITLE
apps/speed in 1.1.0 segfaults since 1.1.0i

### ISSUE THREAD

**Issue by jeffmahoney** [openssl/openssl#8243]
While running 'openssl speed BLAKE2s256' I encountered a segfault:
(gdb) where
#0  0x00007ffff7196cee in __strcmp_sse2_unaligned () from /lib64/libc.so.6
#1  0x00005555555be0cf in opt_found (nbelem=<optimized out>,
    pairs=0x5555557e3250 <ecdh_choices+272>, result=<optimized out>,
    name=<optimized out>) at apps/speed.c:298
#2  speed_main (argc=1, argv=0x7fffffffe1e8) at apps/speed.c:1519
#3  0x0000555555585018 in do_cmd (prog=0x555555817d50, argc=2,
    argv=0x7fffffffe1e0) at apps/openssl.c:476
#4  0x00005555555854be in do_cmd (argv=0x7fffffffe1e0, argc=<optimized out>,
    prog=<optimized out>) at apps/openssl.c:460
#5  main (argc=<optimized out>, argv=0x7fffffffe1e0) at apps/openssl.c:181

It turns out that ecdh_choices is NULL terminated but is iterated using
an array member count.  It hits the NULL entry, tries to dereference it, and
fireworks ensue.

I have the fix written up.

**Comment by FdaSilvaYY** [comment]
Fixed in #8244, commit 3318493b85a8189f6385d5489f97f0e101471f92.
Can be closed
