### ISSUE TITLE
[1.1.1a] secondary library linked against libssl cannot dlopen()ed on AIX

### ISSUE THREAD

**Issue by makr** [openssl/openssl#8266]
Hi *,

a devteam using my provided OpenSSL 1.1.1a build for AIX runs into another issue I haven't seen so far coming my way.
They attempt to dlopen() a shared library that itself is linked against libssl and libcrypto and receive the following error:
```
 Library libfoo.so could not be loaded.

      Library Path: /path/to/foo/lib/libfoo.so
      ERROR: "rtld: 0712-001 Symbol main was referenced
      from module /path/to/openssl/lib/libssl.a(libssl64.so.1.1),
                but a runtime definition of the symbol was not found.
                rtld: 0712-001 Symbol main was referenced
      from module /path/to/openssl/lib/libcrypto.a(libcrypto64.so.1.1),
                but a runtime definition of the symbol was not found." 
```
I am not quite sure why there is no symbol main in the runtime context, but that's not the point. The point is that both libraries are indeed importing main:
```
$ dump -X64 -Tv libssl.a
libssl.a[libssl64.so.1.1]:

                        ***Loader Section***

                        ***Loader Symbol Table Information***
[Index]      Value      Scn     IMEX Sclass   Type           IMPid Name

[0]     0x00000000    undef      IMP     RW EXTref libc.a(shr_64.o) errno
[...]
[955]   0x00000000    undef      IMP     DS EXTref              .. main
```
and
```
$ dump -X64 -Tv libcrypto.a

libcrypto.a[libcrypto64.so.1.1]:

                        ***Loader Section***

                        ***Loader Symbol Table Information***
[Index]      Value      Scn     IMEX Sclass   Type           IMPid Name

[0]     0x00000000    undef      IMP     RW EXTref libc.a(shr_64.o) errno
[...]
[4497]  0x00000000    undef      IMP     DS EXTref              .. main
```
Both are the very last entry in their table. Both are referencing ```..``` as module to import main from. There is no problem if a program with a main()-function is calling dlopen() on libfoo.so.

Why is it referencing main and what is it used for?

**Comment by levitte** [comment]
I tried to grep through the source in `crypto/` if I could find it, but to no avail.  I have no clue!  The only place I know that we deal with main at all is in libtestutil, with the test apps, but that shouldn't affect the main libraries...  however, this being AIX, I'm ready for surprises!

**Comment by makr** [comment]
OK, I see. I'll try to find some clue on a live system...

**Comment by levitte** [comment]
Please do

**Comment by makr** [comment]
Looks as if the ```$shared_ldflag``` in ```Configurations/10-main.conf:aix-common``` needs to be extended by ```,-bnoentry```. This remove quite a number of symbol references and still works with my brief tests. But as I couldn't provoke the original error anyway, I'll check with the complaining devteam first.

**Comment by levitte** [comment]
Okie.  Will you submit a PR if a change is actually needed?

**Comment by makr** [comment]
Sure.

**Comment by makr** [comment]
The PR #8282 should also go into 1.1.1. Let me know if you need a separate PR for this.
