### ISSUE TITLE
Build break: no-engine

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#827]
Configure no-engine tries to build several engines:
From ntdll.mak
E_SHLIB=$(ENG_D)\padlock.dll \
	$(ENG_D)\capi.dll $(ENG_D)\dasync.dll 

The build will then fail with this error:
e_padlock.c
openssl\include\openssl/engine.h(70): fatal error C1189: #error:  ENGINE is disabled.

On a related note, no-capieng does not seem to have any effect.

**Comment by levitte** [comment]
Hopefully, we'll get unified builds for native windows real soon (in review for the moment).  I've already lined up the required fixes to support those config options with the unified build scheme.  Doing the same in `util/mk1mf.pl` is...  painful.

**Comment by matbech** [comment]
No longer relevant.
