### ISSUE TITLE
PHP Startup: Unable to load dynamic library php_curl.dll ' - Das angegebene Modul wurde nicht gefunden.  in Unknown on line 0.

### ISSUE THREAD

**Issue by petesky** [openssl/openssl#828]
When updating to SSL 1.0.2g i get PHP Startup: Unable to load dynamic library php_curl.dll - Das angegebene Modul wurde nicht gefunden. in Unknown on line 0.

I use PHP 5.2.17 VC6 TS x86

**Comment by richsalz** [comment]
Looks like a CURL issue, not an openssl issue.  But I could be wrong.

**Comment by petesky** [comment]
Sure - i can recompile PHP 5.2.17 but i'm not able to do. So please keep openSSL compatible to older PHP versions as 1.0.2f works fine so far !

**Comment by richsalz** [comment]
We try to keep things binary-compatible across letter update releases.
Please explain what broke and we'll try to fix it.

**Comment by petesky** [comment]
I'm only a simple user but using the new 1.0.2g libraries (libeay32.dll and ssleay.dll) cause my php to avoid loading the php_curl.dll which uses ssl functions. For me it looks like there is something wrong in environment / config of openssl ? Some users on apachelounge report mixing CRT version or additional configuration options which are needed to keep the symbols. I still use PHP 5.2.17 and cannot upgrade due to VC6 which is needed for my old webserver i use.

**Comment by petesky** [comment]
With dependencywalker i get the following error:
Error: At least one module (SSLEAY32.DLL) has an unresolved import due to a missing export function in an implicitly dependent module.

**Comment by petesky** [comment]
Referring to http://abi-laboratory.pro/tracker/compat_report/openssl/1.0.2f/1.0.2g/2ccb1/abi_compat_report.html#Removed

...you should return NULL instead of removing the SSLv2_client_method functions completely to stay binary comapatible imho ?

**Comment by mattcaswell** [comment]
That's been fixed in git. If you recompile OpenSSL using "enable-ssl2" during config then you should get the missing symbols back. We made other changes in the latest 1.0.2 to ensure SSL2 isn't used by default even when you have explicitly enabled it at compile time so this should still be safe (unless applications explicitly ask for SSL2).
