### ISSUE TITLE
no-static-engine ignored on macos 10.13.6

### ISSUE THREAD

**Issue by hdatma** [openssl/openssl#8284]
opendkim-2.11.0 is stubbornly refusing openssl-1.1.1a:

`checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing ERR_peek_error... none required
checking for library containing SSL_library_init... no
Configure: error: Cannot build shared opendkim
                                              against static openssl libraries.
                                              Configure with --disable-shared
                                              to get this working or obtain a
                                              shared libssl library for
                                              opendkim to use.'

Out of curiosity, I compiled openssl with shared (default) non-static-engine. The attached  log shows that openssl ignores the option.

**Comment by richsalz** [comment]
SSL_library_init is now a macro; the OpenDKIM configure script doesn't work and needs to be upgraded.  My guess is that they really don't support OpenSSL 1.1.0 at all, yet.

**Comment by hdatma** [comment]
It works on RHEL 7.

**Comment by hdatma** [comment]
https://sourceforge.net/p/opendkim/patches/37/

**Comment by hdatma** [comment]
Puf! Gone! Oh well...

'...
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing ERR_peek_error... none required
checking whether SHA256_DIGEST_LENGTH is declared... yes
checking for milter library and includes... /services/share/libmilter
checking for library containing smfi_register... -lmilter
checking for smfi_insheader... yes
...'
