### ISSUE TITLE
 Is there a mechanism to prevent DOS attacks?

### ISSUE THREAD

**Issue by hucailai** [openssl/openssl#8289]
for an example，when in handshake state，after send client hello，but the remote repeats sending hello request。have any mechanism  to close this connection。

**Comment by mattcaswell** [comment]
Some record types will detect this kind of thing. For example repeatedly sending the same warning alerts, or repeatedly sending key updates will fail after some maximum limit is hit. I don't think that is the case though for renegotiations.

There is nothing though to stop an attacker from repeatedly creating new connections and then closing them down again.
