### ISSUE TITLE
openssl multithread SSL_read set ssl* point to NULL

### ISSUE THREAD

**Issue by yulongWanghb** [openssl/openssl#8296]
ssl library :boringssl 
openssl version: 1.0.2  
 
**Bug description**:
 > I try to use multi thread when sending https request at the same time ,each thread create it's own SSL/SSL_CTX data structure pointer , when the programe running ,i get a crash at SSL_read function
 eg:SSL_read(ssl, buf, tmpbuf),
   i check the crash and find  ssl pointer is set to NULL , when searching the internet, someone tell me SSL_read will share  data In multi threads,   so i set  these two call_back function  ,but it doesn't work 
           >>CRYPTO_set_id_callback(id_function);
           >> CRYPTO_set_locking_callback(locking_function);

   can someone give me ideal to deal with it ? thanks a lot !

**crash print output**: 
    before ssl_read retry times1  ssl_ address 0xbe83f580
    after    ssl_read retry times1  ssl_ address 0

**Comment by yulongWanghb** [comment]
can somebody help me? ,i was confused with this problem for a few days,thanks a lot

**Comment by mattcaswell** [comment]
> ssl library :boringssl

You are using boringssl not OpenSSL. You need to ask those guys for help.

**Comment by yulongWanghb** [comment]
> > ssl library :boringssl
> 
> You are using boringssl not OpenSSL. You need to ask those guys for help.
> i can't  refer a issue on boringssl project , and also know boringssl is a fork of OpenSSL ,so i wonder there may be good solutions or ideas,  i guess multi-thread lead this problem ,openssl use  call_back function to set mutex ,i did so ,it doesn't work ,there are other methods to makesure multi-thread safe ?

**Comment by davidben** [comment]
BoringSSL's bugtracker is https://crbug.com/boringssl. Or you can always email me and AGL. We've diverged enough at this point that filing bugs across projects isn't particularly useful unless you've already identified the cause and verified some issue is present in both.

However, see BoringSSL's README. You likely want to be using OpenSSL anyway.
