### ISSUE TITLE
OpenSSL 1.1.0+ no longer accepts CSRs accepted by OpenSSL 1.0.2

### ISSUE THREAD

**Issue by tidoublemy** [openssl/openssl#8298]
I've come across a compatibility issue very similar to https://github.com/openssl/openssl/issues/7134 but not resolved by that fix.  There exist CSRs in which the integer 0 is incorrectly encoded with the octets "02 00" rather than "02 01 00".  See, as an example, https://github.com/r509/r509/blob/v0.10.0/spec/fixtures/csr4.pem

OpenSSL before version 1.1.0 was able to parse these, but newer versions output:
```
4618220992:error:0D0E20DE:asn1 encoding routines:c2i_ibuf:illegal zero content:crypto/asn1/a_int.c:154:
4618220992:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:658:Field=version, Type=X509_REQ_INFO
4618220992:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:658:Field=req_info, Type=X509_REQ
4618220992:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:crypto/pem/pem_oth.c:33:
```
Modeled on the approach taken in the fix for #7134, the following trivial patch seems to resolve the incompatibility:

```
diff -Naur openssl-1.1.1a/crypto/asn1/tasn_dec.c openssl-1.1.1a.new/crypto/asn1/tasn_dec.c
--- openssl-1.1.1a/crypto/asn1/tasn_dec.c	2018-11-20 08:35:37.000000000 -0500
+++ openssl-1.1.1a.new/crypto/asn1/tasn_dec.c	2019-02-21 09:10:23.000000000 -0500
@@ -832,7 +832,7 @@
     case V_ASN1_INTEGER:
     case V_ASN1_ENUMERATED:
         tint = (ASN1_INTEGER **)pval;
-        if (!c2i_ASN1_INTEGER(tint, &cont, len))
+        if (len != 0 && !c2i_ASN1_INTEGER(tint, &cont, len))
             goto err;
         /* Fixup type to match the expected form */
         (*tint)->type = utype | ((*tint)->type & V_ASN1_NEG);
```

**Comment by levitte** [comment]
There's a huge difference between this and #7134.  #7134 dealt with the fact that we have changed internal OpenSSL ASN.1 types for native integers, and the old types were indeed encoded incorrectly (zeroes were represented as zero length).  So the issue there was for OpenSSL to be able to read RSA keys *created with older OpenSSL versions*.

I just had a look at `i2c_ASN1_INTEGER` in the 1.0.2 branch, and can't see that it encodes zeroes incorrectly.  I might be wrong about that, and if I am, it needs to be fixed in newer versions.
So I guess my question is, what software created those CSRs?  If it was OpenSSL, I can see a stronger incentive to include a bug compatibility fix, but otherwise, I'm frankly less keen.

**Comment by tidoublemy** [comment]
I don't know at this point if there was an older version of OpenSSL that used to encode these incorrectly, though I'm still trying to figure that out.  The history on another bug I found in searching on the error string suggests that there was, as that issue reportedly went away when they updated OpenSSL.  But my own testing has not found a version of OpenSSL that was incorrectly encoding these.  (Reference: https://github.com/DavidWittman/csrgenerator.com/issues/22)

I also don't know any specific products that generate with this issue, but I do work for a public CA and can see that we are receiving CSRs that are handled by our current OpenSSL 1.0.2 that would not be handled if we were to upgrade due to this issue.  I'll continue to investigate and let you know if I can isolate any particular sources for this mis-encoding.

**Comment by tidoublemy** [comment]
I tested a variety of versions of OpenSSL and didn't see any exhibit this encoding behavior, so in spite of what seemed to be suggested in the csrgenerator.com issue, I'm inclined to believe OpenSSL has never encoded these incorrectly.  I also investigated a variety of CSRs we've recently received with this encoding error (we see it in about 1 out of every 500 CSRs we receive) and found no obvious clues as to what software might be generating them.  I saw Apache, Nginx, and Microsoft all reported as the servers hosting the certificates that had originated with CSRs that were encoded in this way.  So I'd say it's unfortunately unlikely that I'm going to be able to answer your question.

**Comment by levitte** [comment]
Well, you did confirm that OpenSSL doesn't seem to be at fault. Not sure about the position of the rest of the team, my personal view is that we can't be bug compatible with every other software out there. I don't entirely agree with Postel on this topic...
