### ISSUE TITLE
Better C++ API?

### ISSUE THREAD

**Issue by fekir** [openssl/openssl#8313]
Hello,

is the openssl project interested in providing a more "easy-to-use" API for the C++ programming language?

In the wiki (or generally speaking online) I can see sometimes C++ samples (for example here: https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption#C.2B.2B_Programs).

I'm not for a completely different interface for the C++ programming language, this would only add confusion and a much deeper learning curve, because now there are two different ways to do the same thing.

I'm thinking more about adding separate header (like pkcs7.hpp), with some utilities that work seamlessly together with the existing API.
For example the definition of an `unique_PKCS7`, that uses internally `PKCS7_free`, or another factory function, similarly to `PKCS7_new`, but that returns a `unique_PKCS7` instead of a naked pointer.
Thus if someone is using C++, the recommended way would be to use `unique_PKCS7` instead of managing memory manually.

Of course the first improvement would be adding types for avoiding resource leaks through destructors (in most cases it is as mentioned simply providing a definition with `std::unique_ptr`), maybe there are also other areas (overloads? more strict type-checking? compile-time computations?), where the api could get simplified/improved.

Of course every project could add those definitions by itself, but staying in sync with the original project is cumbersome.

Another possible benefit of providing such an interface is ensuring that the openssl header files can also be included in c++ code.
This might sometimes be an issue when using some words that are reserved in the c++ standard, but are not in c, like `class`.
AFAIK there are no checks of this type at the moment.

If there is interest, I could try to put some time into it.
I always define such structures in most project I use, so that's not a big deal.
Where it might get more difficult is how to integrate it with the project :-)

**Comment by levitte** [comment]
> This might sometimes be an issue when using some words that are reserved in the c++ standard, but are not in c, like `class`.

Ah, that's a good point.  I think I see where that might be an issue.

Something to be noted is that we have autogenerated test apps that do only one thing, they include each public header file (save a limited list) individually just to see that they don't cause any compilation error.  We *could* have those exact same apps compiled with C++ as well, if the configuration specifies a C++ compiler.  That should be sufficient to find this kind of issue.

-----

About the other topic, I'm unsure how wise it is to add C++ stuff in OpenSSL itself.  Sure, it would be cool 'n all that, but then there's the question of maintenance.  Is the collective @openssl developer C++ skill set up to the challenge?

Mind you, it's not like I want to discourage your idea, but it might be better to look upon that as a separate project with strong ties to OpenSSL rather than a part of OpenSSL.

These are just my cautious thoughts, I'd welcome other opinions.

**Comment by paulidale** [comment]
Is supporting C++ in OpenSSL opening the floodgates for supporting other programming languages?  They are quite different languages.

I consider not using C++ reserved words in public headers as a slightly different matter.

**Comment by fekir** [comment]
@paulidale 

Yes, C++ is a different language from C, but with a lot of common history, techniques and similar syntax.
Despite that, they should be treated differently.
That's the whole reason why I'm asking if it makes sense to provide a "better" API than the raw C interface, because programming paradigms are different, and because the C++ language has more to offer for avoiding some errors.

> Is supporting C++ in OpenSSL opening the floodgates for supporting other programming languages?

Theoretically yes, even if I do not think so, since C and C++ have a lot in common, contrary to other languages. But that's why I'm asking.

@ levitte 
Good idea for the tests.

As I already stated such an interface could be provided as separate project.
IMHO it would be too much work. Many functions in openssl are generated (if I remember correctly), by macros or the build system, given a specific type.
Those macros/part of the build system could also generate most of the C++ functions.
As a separate project, such possibility partly vanishes, and most things that could get automated must be updated manually.
It also adds edge cases and possible issues if openssl moves, renames or adds some types, and if we want to have a library for every version from now on.

I do not believe that it would be a great effort providing such an interface, IMHO a first version of it would be just providing the typedefs for std::unique_ptr, and maybe some factory functions.
As a separate project also the adoption rate would be much lower, since "it is another dependency", while creating those typedefs (or just copy-pasting) is very easy.

**Comment by mattcaswell** [comment]
IMO C++ language bindings do not belong in OpenSSL. I would welcome good language bindings in a separate project.

**Comment by levitte** [comment]
#8325 adds build tests with C++

**Comment by fekir** [comment]
@mattcaswell 
For me a language binding would be something that would completely hide the openssl API, a complete facade and provide another interface.
Most languages would do something like that instead of calling the C functions directly, and there are already some wrappers around openssl for providing a more nice or easy-to-use API.

I'm proposing to add something much much smaller, something like the least amount of code needed to completely avoid some common type of errors.
The most low hanging fruit is IMHO memory leaks, and many could be literally fixed by a one-liner definition (per type).

A separate library is IMHO an overkill, (also due to the lack of a standard package manager) unless it would be possible to (optionally) ship it with openssl.
Would that be a better option?

**Comment by kaduk** [comment]
Having recently spoken against openssl adopting Net::SSLeay, I am somewhat constrained to also oppose adopting C++ bindings as a project.  Though, the C++ case is a much closer question to me, with some reasonable arguments in support of adopting C++ bindings.  My main argument against adoption is that I don't think we have a big enough core pool of C++ expertise in the current openssl team members, so it would not be a sustainable effort.

**Comment by richsalz** [comment]
I think not using C++ keywords is the only thing that this project should do.

**Comment by t-j-h** [comment]
I agree with @richsalz in that adding a separate C++ API is not something that we should be tackling within the project itself. It should be possible to compile OpenSSL with a C++ compiler - but beyond that I don't think we should be adding additional APIs for C++ specific usage into the main project.

**Comment by levitte** [comment]
> It should be possible to compile OpenSSL with a C++ compiler

I doubt it.  We haven't wrapped the internal headers with `extern "C" { ... }`, so we're quite likely to hit a snag or two.

**Comment by levitte** [comment]
The OpenSSL team members seem to all be of the same opinion...  Since #8325 (inclusion of public headers with C++) is now merged, I believe it's time to close this issue.

I do look forward to seeing the project that raises a C++ API (even just partial), though.
