### ISSUE TITLE
Time to retired crypto-mdebug

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#8322]
With the default library context, we may end up having some objects cleaned out as part of an automatic `OPENSSL_cleanup()` (registered with `atexit()`).  However, `test/testutil/driver.c` calls `CRYPTO_mem_leaks_cb()` explicitly when OpenSSL is configured with `enable-crypto-mdebug`, and this happens before the automatic `OPENSSL_cleanup()`, meaning that anything not yet cleaned out from the default library context gets reported as a memory leak.

This has been a problem that's been waiting to happen for years (I'm actually surprised it's taken all this time).  `debug-mdebug` was developed in a time before cool and fancy tools like valgrind were commonly available.  Times are different now, and external tools usually do a better job.

Time to retire `debug-mdebug` (make it a no-op for the sake of compatibility)

**Comment by mattcaswell** [comment]
Hmmm. I much prefer crypto-mdebug to using valgrind. I use it all the time. It would be a big loss to see this go.

**Comment by levitte** [comment]
I found that `crypto-mdebug` can't be removed entirely, as it covers more than leak detection.

**Comment by levitte** [comment]
The trouble with the crypto-mdebug leak detection gets hooked in wrong.  Some memory may be freed *after* the leak report is printed, with gives false alarms.  We have dealt with that by having an exception control, but with the addition of the default library context and its late cleanup means that basically *every* addition of stuff into the default library context will have to include such exception...  and that kind of defeats the purpose.

We have to remember that the leak detection stuff was designed at a time where library cleanup was done explicitly rather than automatically.  With that, the application could control in what order stuff was done, and especially that leak detection after all appropriate library cleanup is done.

Additionally, I find that valgrind creates much better reports than crypto-mdebug ever does, even with backtracing enabled.

**Comment by levitte** [comment]
...

the alternative is to specify that an application that calls `CRYPTO_mem_leaks_cb()` *must* run an explicit `OPENSSL_cleanup()` first...

**Comment by richsalz** [comment]
If you remove mem-debug, you need to think if that's part of the public API.  And more importantly, you need to run memleak-checking as part of a CI build.

**Comment by levitte** [comment]
Re memleak-checking, I give you #8323

**Comment by levitte** [comment]
It's kinda sorta part of the public API...  *only* if you explicitly configure with `crypto-mdebug`, which I don't expect in production code.  However, I was planning on leaving a shim behind.

**Comment by richsalz** [comment]
See #10572
