### ISSUE TITLE
EC interface changes

### ISSUE THREAD

**Issue by bbbrumley** [openssl/openssl#8332]
Opening a discussion about reducing the EC interface in future versions where API changes are allowed. Tagging @romen if there's something I've missed.

* ~~Entire concept of `EC_METHOD` should not be public facing.~~ done in #11928
* ~~Deprecate `EC_GROUP_precompute_mult` `EC_GROUP_have_precompute_mult` `EC_KEY_precompute_mult`. The `speed` app is the only software I've ever found using them. (Besides, with recent EC changes most use cases don't have access to this type of precomp anyway. Only the hard coded constants from the custom `EC_METHOD`s.)~~ done in #11851
* ~~Deprecate `EC_POINTs_mul`. The `aG + bP` interface of `EC_POINT_mul` is enough for crypto.~~ done in #11807
* ~~Deprecate `EC_POINT_set_Jprojective_coordinates_GFp` `EC_POINT_get_Jprojective_coordinates_GFp`. Whether a point has 3, 4, 5, ... coordinates, and what coordinate system the `EC_METHOD` uses, should not be public facing.~~ done in #11527
* ~~Deprecate `EC_POINT_make_affine` and `EC_POINTs_make_affine` since the `EC_POINT` structure has been opaque for some time now.~~ done in #11874
* Investigate deprecating `EC_GROUP_set_curve` since it seems uncommon to reuse an `EC_GROUP` that way instead of other direct constructors for `EC_GROUP`. Suggested in #11928

**Comment by davidben** [comment]
+1 to each of these. As a data point, we've dropped all of these from BoringSSL without trouble. In practice, people don't seem to really use them.

The one footnote is here is `EC_GROUP_method_of` + `EC_METHOD_get_field_type` is currently the only way to check whether a group is GFp or GF2m. See also issue #6275. (As a compatibility hack, BoringSSL currently returns a dummy pointer out of `EC_GROUP_method_of` and makes `EC_METHOD_get_field_type` always return `NID_X9_62_prime_field` because we don't do GF2m at all.)

**Comment by bbbrumley** [comment]
> See also issue #6275

Great! They are good arguments.

> `EC_GROUP_method_of` + `EC_METHOD_get_field_type` is currently the only way to check whether a group is GFp or GF2m

Hrm good point. Personally I've only written / seen code that uses `EC_METHOD_get_field_type` to differentiate calling `EC_POINT_*_affine_coordinates_GFp` or `EC_POINT_*_affine_coordinates_GF2m`. But those are now deprecated with `EC_POINT_*_affine_coordinates`.

Help me understand -- what are the important use cases for getting access to `group->meth->field_type` for linking applications? I'm struggling.

**Comment by davidben** [comment]
I think it was just that. `EC_POINT_*_affine_coordinates` hadn't existed at the time the code in question was written. I could also imagine someone wanting to print some metadata about the curve for some reason, in which case this would be useful.

But my own project has ditched GF2m curves altogether, so I'm not a good judge these sorts of use cases. If I had my way, even user-specified curves would be gone altogether and there would only be the four or so common named curves. :-)

**Comment by bbbrumley** [comment]
Re: fetching `field_type`:

* So with my _avoid-public-API-creep-like-the-plague_ hat on, I'd say dig for it in the `EC_GROUP_get_ecparameters` output.
* With my _application-developer-friendly_ hat on, it does seem a bit silly to allocate and walk an ASN1 structure to fetch this.

I'm leaning to the former, since I'm still having a hard time convincing myself of use cases where this is necessary. You already have an `EC_GROUP` or `EC_POINT`; it didn't materialize out of the ether. If you need to e.g. exclude binary curves or filter, to me it seems at that level is where it should be done. Not deeper in the code where you're already operating on the allocated curve.

Maybe it's a good exercise for me to go through, try to strip it out of the library internally and see how many hoops I have to jump through.

**Comment by mattcaswell** [comment]
These seems like good suggestions to me.

**Comment by t8m** [comment]
All the items should be done now. Closing.
