### ISSUE TITLE
ca tool help and man page don't list sigopt

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8335]
in c8147d37cca

both `openssl ca -help` and ca man page don't list `-sigopt` as a valid argument, it's documented only in the dgst man page

**Comment by mattcaswell** [comment]
It seems this is now documented in `-help` and on the man page - although the documentation doesn't list what the algorithm specific sigpopts are. It would be helpful if we added those.

**Comment by ruscot** [comment]
Hi, I read this issue and I want to know if you want to add the algorithm used in the man page or in openssl ca -help ?
And my second question is more about what we want to add in documentation :
I find on internet documentation of openssl an example for the SM2 certificate https://www.openssl.org/docs/manmaster/man1/openssl-ca.html  
I read on internet that SM2 use the SM3 cryptographic hash algorithm to calculate the 32byte digest. And the SM3 needs the digest signature party ID which correspond to the sigopt, am I wrong ?
So it's that type of thing you want to add in the documentation ?

**Comment by jamuir** [comment]
I think this can be closed.

The original issue (i.e. "sigopt" missing from `man openssl-ca` and `openssl ca -help`) was resolved at some point.

Here is what I see my ubuntu machine:

```
$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
$ openssl ca -help 2> foo.tmp && grep sigopt foo.tmp
 -sigopt val             Signature parameter in n:v form
$ man openssl-ca | grep sigopt
       arg] [-utf8] [-sigopt nm:v] [-vfyopt nm:v] [-create_serial] [-rand_serial] [-multivalue-rdn] [-rand files]
       -sigopt nm:v
                -sigopt "distid:1234567812345678" \
```
