### ISSUE TITLE
pkcs12 man page does not document NONE 

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8336]
in c8147d37ccaaf28c

the man page for pkcs12 tool does not list `NONE` as a valid (and special) argument for `-certpbe`

**Comment by erbsland-dev** [comment]
@tomato42 @mattcaswell I’ve reviewed the existing code and documentation related to this issue. The keyword `NONE` is currently supported as a valid argument in the latest version of `openssl`.

You can find the relevant code handling the NONE keyword here:
https://github.com/openssl/openssl/blob/6dacee485fad2c4d334e08af48891636205ddb6b/apps/pkcs12.c#L1327-L1341

Additionally, the NONE keyword is documented in the OpenSSL manual, as shown here:
https://github.com/openssl/openssl/blob/6dacee485fad2c4d334e08af48891636205ddb6b/doc/man1/openssl-pkcs12.pod.in#L328-L338

I’m not entirely sure how the referenced commit relates to this issue, but based on the issue title and description, it seems that if the `NONE` keyword is documented correctly, this issue could be considered resolved and potentially closed.

**Comment by t8m** [comment]
I am closing this as this is resolved in the current versions.

**Comment by t8m** [comment]
Thanks @erbsland-dev for the verification.
