### ISSUE TITLE
some doubt about register ssl obj to X509_STORE_CTX in SSL handshake step.

### ISSUE THREAD

**Issue by chensqecc** [openssl/openssl#8337]
hi  
i have a question about register ssl obj to X509_STORE_CTX in SSL handshake step.

from openssl 1.1.1 code,  ssl server(or client) will have two different process to send certificate and get certificate.

the process is like that:
(a)send certificate:
#0  check_issued_adaptor (ctx=0x947cf0, x=0x9455a0, issuer=0x9455a0) at server.c:361
#1  0x000000000054068b in internal_verify (ctx=0x947cf0) at crypto/x509/x509_vfy.c:1718
#2  0x000000000053d6c6 in verify_chain (ctx=0x947cf0) at crypto/x509/x509_vfy.c:232
#3  0x000000000053d921 in X509_verify_cert (ctx=0x947cf0) at crypto/x509/x509_vfy.c:295
#4  0x000000000044e881 in ssl_add_cert_chain (s=0x949350, pkt=0x7fffffffe2a0, cpk=0x9415e0) at ssl/statem/statem_lib.c:943
#5  0x000000000044eab8 in ssl3_output_cert_chain (s=0x949350, pkt=0x7fffffffe2a0, cpk=0x9415e0) at ssl/statem/statem_lib.c:999
#6  0x000000000045963d in tls_construct_server_certificate (s=0x949350, pkt=0x7fffffffe2a0) at ssl/statem/statem_srvr.c:3767
#7  0x000000000044010a in write_state_machine (s=0x949350) at ssl/statem/statem.c:840
#8  0x000000000043f53c in state_machine (s=0x949350, server=1) at ssl/statem/statem.c:440
#9  0x000000000043f08f in ossl_statem_accept (s=0x949350) at ssl/statem/statem.c:254
#10 0x000000000042636f in SSL_do_handshake (s=0x949350) at ssl/ssl_lib.c:3583
#11 0x000000000042258d in SSL_accept (s=0x949350) at ssl/ssl_lib.c:1651
#12 0x0000000000403d1a in basic_server () at server.c:428
#13 0x0000000000404bc8 in main () at server.c:975

(b) get and parse certificate:
#0  check_issued_adaptor (ctx=0x963690, x=0x95bf90, issuer=0x946e90) at server.c:361
#1  0x000000000053b21c in X509_STORE_CTX_get1_issuer (issuer=0x7fffffffe098, ctx=0x963690, x=0x95bf90) at crypto/x509/x509_lu.c:675
#2  0x0000000000542845 in get_issuer (issuer=0x7fffffffe098, ctx=0x963690, cert=0x95bf90) at crypto/x509/x509_vfy.c:2853
#3  0x0000000000542c1c in build_chain (ctx=0x963690) at crypto/x509/x509_vfy.c:2992
#4  0x000000000053d5b7 in verify_chain (ctx=0x963690) at crypto/x509/x509_vfy.c:218
#5  0x000000000053d921 in X509_verify_cert (ctx=0x963690) at crypto/x509/x509_vfy.c:295
#6  0x00000000004196d3 in ssl_verify_cert_chain (s=0x949350, sk=0x9419f0) at ssl/ssl_cert.c:515
#7  0x00000000004591fa in tls_process_client_certificate (s=0x949350, pkt=0x7fffffffe2b0) at ssl/statem/statem_srvr.c:3664
#8  0x00000000004535b8 in ossl_statem_server_process_message (s=0x949350, pkt=0x7fffffffe2b0) at ssl/statem/statem_srvr.c:1172
#9  0x000000000043fa85 in read_state_machine (s=0x949350) at ssl/statem/statem.c:633
#10 0x000000000043f4fd in state_machine (s=0x949350, server=1) at ssl/statem/statem.c:431
#11 0x000000000043f08f in ossl_statem_accept (s=0x949350) at ssl/statem/statem.c:254
#12 0x000000000042636f in SSL_do_handshake (s=0x949350) at ssl/ssl_lib.c:3583
#13 0x000000000042258d in SSL_accept (s=0x949350) at ssl/ssl_lib.c:1651
#14 0x0000000000403d1a in basic_server () at server.c:428
#15 0x0000000000404bc8 in main () at server.c:975

in openssl 1.1.1 code,we can see in the  ssl_verify_cert_chain function(get and parse certificate process), we will call X509_STORE_CTX_set_ex_data to set ssl obj to ctx.
    if (!X509_STORE_CTX_set_ex_data
        (ctx, SSL_get_ex_data_X509_STORE_CTX_idx(), s)) {
        goto end;
    }
so in the cert verify callback function, we can get ssl obj from ctx and do some check for ssl obj.

while in another process (send certificate), in ssl_add_cert_chain function, after get xs_ctx,we don't set ssl obj to xs_ctx. so now the problem is : if i want do some verify callback, and this callback will use ssl obj. i cann't get it. i just can get it in another process(get and parse certificate).

please help confirm what is background here? does it a defect for openssl? And is there any other method to get a ssl obj  in check callback process when send a  certificate?

**Comment by kaduk** [comment]
I'm not 100% I'm understanding the question correctly, but in general when you get/parse the certificate from a peer, that's untrusted input and you have to be careful about validating and verifying the certification chain in order to determine the authentication state of the peer.  That could include using different trust anchors depending on who you were trying to connect to, etc.
When preparing a certificate to send to the peer, that input is generally going to be trusted input -- you know exactly where it's coming from, and any verification of the authentication chain is just as a consideration to the peer, and to get a more useful local error message than "received abort from the peer".  But if you already know what you are sending, then there is less need for flexibility in how to perform the validation, since it's generally assumed to be valid already.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
