### ISSUE TITLE
Certificate with long integer marked as bad integer

### ISSUE THREAD

**Issue by JoSSte** [openssl/openssl#8339]
OpenSSL is marking a certificate serial number as "bad". As far as I can see, the serial number is conforming to the 20 octet, long integer value, only thing is that it is in hexadecimal format... I would not expect this to fail...

**OpenSSL 1.0.2o**
openssl asn1parse -in cust.crt
    0:d=0  hl=4 l= 891 cons: SEQUENCE
    4:d=1  hl=4 l= 611 cons: SEQUENCE
    8:d=2  hl=2 l=   3 cons: cont [ 0 ]
   10:d=3  hl=2 l=   1 prim: INTEGER           :02
   13:d=2  hl=2 l=   8 prim: INTEGER           :20ABB6B7F62361

**OpenSSL 1.1.1a**
openssl asn1parse -in cust.crt
    0:d=0  hl=4 l= 891 cons: SEQUENCE
    4:d=1  hl=4 l= 611 cons: SEQUENCE
    8:d=2  hl=2 l=   3 cons: cont [ 0 ]
   10:d=3  hl=2 l=   1 prim: INTEGER           :02
   13:d=2  hl=2 l=   8 prim: INTEGER           :BAD INTEGER:[0020ABB6B7F62361]

**Comment by davidben** [comment]
`0020ABB6B7F62361` is not a correct INTEGER encoding. INTEGERs must be encoded with the minimum number of bytes. `20` does not have the high bit set, so it is incorrect to prepend a zero byte there. (You pretend leading zero bytes if you want a positive number and the high bit would otherwise be set, making the value negative.)

**Comment by JoSSte** [comment]
Ok. So if it was `20ABB6B7F62361` it would be valid?

**Comment by davidben** [comment]
I believe so. If you work on the software that produced this certificate, please familiarize yourself with ASN.1 encoding rules.

**Comment by JoSSte** [comment]
It's generated by an IBM module i believe...

**Comment by levitte** [comment]
Note that this is only something that's done with the `asn1parse` output, it doesn't affect the how that integer is processed.  See it as a gentle nudge to whoever output that certificate that they didn't get it quite right.

**Comment by davidben** [comment]
Note this is not universally true of all implementations. Stricter parsers will reject such inputs, and failing to encode certificates correctly is often considered misissuance. You should file a report with the vendor.

**Comment by levitte** [comment]
> Note this is not universally true of all implementations.

Well, err, no, of course not.  I spoke from an OpenSSL perspective.
