### ISSUE TITLE
chacha20-poly1305: fails to detect tampering, where IV > 12 and IV <= 16 (CHACHA_CTR_SIZE)

### ISSUE THREAD

**Issue by jorangreef** [openssl/openssl#8345]
I have been fuzzing OpenSSL's implementation of several AEAD ciphers in OpenSSL 1.1.1a.

For `chacha20-poly1305`, OpenSSL supports an IV, where IV >= 1 byte and IV <= 16 bytes (`CHACHA_CTR_SIZE`), with the default IV being 12 bytes or 96-bits.

However, fuzzing revealed test vectors where 4 bytes of the IV range can be modified by an attacker, without `EVP_CipherFinal_ex()` detecting the corruption.

This means that where authenticated messages use `chacha20-poly1305` as AEAD cipher, and where a 128-bit nonce is included in the authenticated message (instead of the default 96-bit nonce), an attacker can modify 4 bytes of the authenticated message without detection.

Here are test vectors showing IVs for which these collisions are possible:

```
algorithm=chacha20-poly1305
enc=0 (decrypting...)
key=5afd42de4b3da741009ce0f6e8fdf9d3e05142d4dd4998b19c192379523a7c62 (32 bytes)
iv=bab79b546a22cb759a2a7dbcf033 (14 bytes) [corrupt at offset 0, original=b9b79b546a22cb759a2a7dbcf033]
ciphertext=1bc91bf03ef31fa4df81341172b24241697d1313 (20 bytes)
aad=130afce35153a185dd55a5315fa03fdb67ce4a053f58 (22 bytes)
tag=5e202b695689a6d0bbe57aed922bac61 (16 bytes)
TAMPERING NOT DETECTED

algorithm=chacha20-poly1305
enc=0 (decrypting...)
key=c4a70a7cd67c6e0499a323fe85288b946d6d1b5103c6f9b50f5b0dfb92f9edb9 (32 bytes)
iv=765935269f6e019f8ae5aae8353df7 (15 bytes) [corrupt at offset 1, original=765835269f6e019f8ae5aae8353df7]
ciphertext=a59d24 (3 bytes)
aad=a89b005817a4103bc034b004c3afc5c534e85d3650513640df36 (26 bytes)
tag=ced3b91249e3a0ecb3f39b83f6fcd9 (15 bytes)
TAMPERING NOT DETECTED

algorithm=chacha20-poly1305
enc=0 (decrypting...)
key=4e090c4887311123b914fabebd4ed066ce5ee6bc4695d20e34f19b4b99ae1bf7 (32 bytes)
iv=fe97b3cd475439553a585d5982fb0aed (16 bytes) [corrupt at offset 2, original=fe97b2cd475439553a585d5982fb0aed]
ciphertext=95a448b9f3499e1d9f1cee55cede31ecf09d1e07a67b98d9ba92afea1e (29 bytes)
aad=3cdc133a0e16d2df9e0469 (11 bytes)
tag=c2650e0f8db4cd484defa126d108d4 (15 bytes)
TAMPERING NOT DETECTED

algorithm=chacha20-poly1305
enc=0 (decrypting...)
key=e3c30b4556809968baf0277bfdd716a2059cc8d1652310130e49f845318ccf58 (32 bytes)
iv=2309bdf81e51fd18661466a4ccaf29ee (16 bytes) [corrupt at offset 3, original=2309bdf71e51fd18661466a4ccaf29ee]
ciphertext=81bf678661c6d8635aef310f41fed675e27efd54a60cf070710d9f8c43 (29 bytes)
aad=(0 bytes)
tag=52d7f5c6a131b7f5d236805afa8d (14 bytes)
TAMPERING NOT DETECTED
```

I understand that 96-bit nonces are the default, but accepting 128-bits is dangerous if it allows the possibility of tampering with the cipher's context.

**Comment by jorangreef** [comment]
In fact, you can tamper with any of the first 4 bytes (offsets 0,1,2,3) of the IV provided.

For example, OpenSSL will finalize the same plaintext without detecting corruption for any of these IVs:

```
b9b79b546a22cb759a2a7dbcf033 (original)
dead9b546a22cb759a2a7dbcf033 (corrupt)
beef9b546a22cb759a2a7dbcf033 (corrupt)
```

This does not appear to be the case for GCM and OCB with IV > 12 bytes, which appear to authenticate every part of the IV.

OpenSSL's accepting of 16-byte IVs for chacha20-poly1305, without authenticating all of the message,  breaks the perceived authentication contract and introduces a weird machine.

This might prove significant for network and storage protocols which assume full message authentication, and then proceed to do a further calculation on the message (including the tampered IV), e.g. ReedSolomon for erasure coding. This could wreak havoc.

Granted, most users of chacha20-poly1305 will use 12-byte IVs, but some custom protocols would have reserved space for 16-byte IVs.

Either OpenSSL accepts 16-byte IVs and authenticates all of the IV, or OpenSSL accepts only 12-byte IVs.

If OpenSSL promises AEAD guarantees for the full message (including the IV) then it must keep it, or  else encrypt-then-mac advocates are going to start saying "I told you so".

**Comment by mattcaswell** [comment]
I am investigating this issue.

**Comment by kaduk** [comment]
e_chacha20_poly1305.c has:
```
    case EVP_CTRL_AEAD_SET_IV_FIXED:
        if (arg != 12)
            return 0;
        actx->nonce[0] = actx->key.counter[1]
                       = CHACHA_U8TOU32((unsigned char *)ptr);
        actx->nonce[1] = actx->key.counter[2]
                       = CHACHA_U8TOU32((unsigned char *)ptr+4);
        actx->nonce[2] = actx->key.counter[3]
                       = CHACHA_U8TOU32((unsigned char *)ptr+8);
        return 1;
```
Is the test code checking for errors from the IV setting operation?

**Comment by jorangreef** [comment]
@kaduk are you asking me about my test code or are you asking @mattcaswell about OpenSSL's test code?

Our fuzz tests check all returns for errors, but you should be able independently to verify the test vectors I provided, to be sure.

**Comment by jorangreef** [comment]
We are using `EVP_CTRL_AEAD_SET_IVLEN` to set the IV length:

```
if (!EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_IVLEN, iv_size, NULL)) {
  EVP_CIPHER_CTX_free(ctx);
  return "ivSize invalid";
}
```

**Comment by kaduk** [comment]
(I was asking about your test code, which you posted the right snippet of; thanks)
