### ISSUE TITLE
openssl 1.1.1a cipher doe nost list all supported ciphers

### ISSUE THREAD

**Issue by manuelgavidia** [openssl/openssl#8350]
Building openssl from tag OpenSSL_1_1_1a and running _ciphers_ command I get a cipher list not including ECDHE-ECDSA-AES128-CCM8, but I am able to ran a server explicitly setting this cipher. Should not this cipher be listed in _ciphers_ command?

> export RANDFILE=.rnd
> ./openssl ecparam -name secp521r1 -out my-ca-key.pem -genkey
> ./openssl req -new -x509 -days 365 -key my-ca-key.pem -out my-ca-cert.pem -config openssl.cnf
> ./openssl ecparam -name secp521r1 -out my-server-key.pem -genkey
> ./openssl req -new -key my-server-key.pem -out my-server-csr.pem -config openssl.cnf
> ./openssl x509 -req -days 365 -in my-server-csr.pem -CA my-ca-cert.pem -CAkey my-ca-key.pem -set_serial 01 -out my-server-cert.pem
> ./openssl s_server -debug  -key my-server-key.pem -cert my-server-cert.pem -CAfile my-ca-cert.pem -cipher ECDHE-ECDSA-AES128-CCM8
> Using default temp DH parameters
>ACCEPT

Output from ciphers command:
```
$openssl ciphers
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA
```

**Comment by mattcaswell** [comment]
Running `openssl ciphers` without specifying a specific cipher list is the same thing as running `openssl ciphers DEFAULT`, i.e. it gives you the list of default ciphersuites. There are some ciphersuites which are not in the default group such as the one you identify. To see a fuller list you can run `openssl ciphers ALL`

**Comment by manuelgavidia** [comment]
Thank you !!!
