### ISSUE TITLE
1.0.2r NonStop Port Regression - starting big number library test

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#8352]
This is a new condition in 1.0.2r that did not exist in 1.0.2q. When we hit the `starting big number library test`, the test suite fails during setup. We are not sure what is going on. The test fails immediately, and does not take a while as hinted.

```
    $ make test
    <snip>
    starting big number library test, could take a while...
    /bin/sh: tmp.bntest: cannot create
```
I would appreciate some guidance in resolving this so that 1.0.2r can pass without errors for the NonStop community.

**Comment by levitte** [comment]
Creating `tmp.bntest` is done entirely in `test/Makefile`, and that part hasn't changed between 1.0.2q and 1.0.2r.  This is the exact lines that create it (in 1.0.2r):

https://github.com/openssl/openssl/blob/b34cf4eb616446a1ee7bd0db0a625edf25047342/test/Makefile#L253

Considering it's `/bin/sh` reporting the failure to create, I have to ask if there are external factors that have been overlooked (read-only file in the way, that sort of silliness that might slip from even the best of minds at times...)

**Comment by rsbeckerca** [comment]
Operator error. The previous run was done under SUDO. 1.0.2r passes on NonStop now. We are still willing to share the ported code.
