### ISSUE TITLE
App is Rejected by Apple because the mothod dlopen() and dlsym() in dso_dlfcn.c

### ISSUE THREAD

**Issue by iamhyw** [openssl/openssl#8353]
Apple reply:
This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as **dlopen()**, **dlsym()**, respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

How can I fix it?

**Comment by levitte** [comment]
You can build a OpenSSL without DSO, by adding `disable-dso` to the configuration command.

**Comment by levitte** [comment]
(`no-dso` works as well)

**Comment by iamhyw** [comment]
@levitte OK! Thanks! I will try it.
