### ISSUE TITLE
TLS 1.3 with private key in an HSM

### ISSUE THREAD

**Issue by pgianna** [openssl/openssl#8356]
We are using Apache/mod_ssl built with OpenSSL 1.1.1a. The server key is in an HSM, accessed though an OpenSSL engine provided by the HSM vendor. In this environment TLS 1.3 does not work, neither TLS 1.2 with the PSS signature scheme. TLS 1.2 with older PKCS v1.5 signature schemes works.
Stepping into the source I traced the error in function pkey_rsa_sign in file crypto/rsa/rsa_pmeth.c. In particular the call to RSA_private_encrypt() with RSA_NO_PADDING fails, I assume because the HSM refuses to do a raw RSA signature.
As it is I don't see any way for eanbling PSS if the hardware will not accept a raw RSA signature operation, which is very likely for hardened HSMs that meet strict compliance guidelines.

**Comment by kaduk** [comment]
Is the hardware capable of natively doing PSS signatures? (If so, how?)
You plain can't do TLS 1.3 using an RSA certificate without PSS signatures.

**Comment by pgianna** [comment]
The hardware is supposed to support RSA_PKCS_PSS mechanisms for signing on its PKCS11 interface. But it seems that openssl uses the encrypt function for PSS signing, and the HSM will not allow it with the 
RSA_NO_PADDING parameter.

**Comment by kaduk** [comment]
This seems to be related to #7968

**Comment by mattcaswell** [comment]
In OpenSSL 3.0 this will be possible using the new "provider" mechanism (which can be seen as a replacement for engines). There are no plans to fix this for engines.

**Comment by t8m** [comment]
Closing, this requires the HSM to have a provider or having a PKCS11 provider and pkcs11 module for the HSM.
