### ISSUE TITLE
Compilation failure on FreeBSD when including <openssl/crypto.h> after #define'ing _ANSI_SOURCE

### ISSUE THREAD

**Issue by dfoxfranke** [openssl/openssl#8358]
Defining _ANSI_SOURCE before including `<time.h>` on FreeBSD will suppress definition of the `clockid_t` type. Since `<time.h>` is part of ANSI C but `clockid_t` is POSIX-specific, this is correct behavior.

FreeBSD's `<pthread.h>` header transitively includes `<time.h>` in order to get the definition of `clockid_t` which is used in the prototype for `pthread_getcpuclockid()`. As a result,

```
#define _ANSI_SOURCE
#include <pthread.h>
```
will result in compilation error on FreeBSD. This can't be considered a FreeBSD bug since it doesn't make any sense to do this; if you're depending on POSIX headers, you should be defining some value of _POSIX_SOURCE instead.

On the other hand, I do expect

```
#define _ANSI_SOURCE
#include <openssl/crypto.h>
```

to work since OpenSSL is meant to be portable beyond POSIX.

And on the 1.0.2 branch, it works. In 1.1.0, however, `<openssl/crypto.h>` contains

```
#   include <pthread.h>
typedef pthread_once_t CRYPTO_ONCE;
typedef pthread_key_t CRYPTO_THREAD_LOCAL;
typedef pthread_t CRYPTO_THREAD_ID;
```

thus causing a compilation error.

These types shouldn't be defined this way in public headers; they should be opaque structs with their actual implementation in terms of `pthread_t` etc. being hidden in .c files or private headers.

I haven't thought all the way through whether or not this is fixable in 1.1.0/1.1.1 without breaking the ABI, but it should be straightforward to correct in 3.0.0.

cc @Hal-Murray who spotted this issue while testing libaes_siv on FreeBSD.

**Comment by levitte** [comment]
I disagree with making our entirely own opaque structures for `CRYPTO_ONCE` et al, it seems to add cruft for little actual gain.

The `_ANSI_SOURCE` problem is a different one, and not something we support in itself, so the most straight forward answer is "don't do that", although we *could* check it and disable all thread support if it's defined.  That is, however, not a high priority thing.

**Comment by paulidale** [comment]
Closing since this isn't going to be addressed.
