### ISSUE TITLE
Solaris x86 assembly failure with 1.1.1b

### ISSUE THREAD

**Issue by nrgiii** [openssl/openssl#8361]

**Comment by levitte** [comment]
Would you care to describe it a bit more?  Failure logs?  `./configdata.pm --dump` output?  That sort of thing?

**Comment by nrgiii** [comment]
assembler step on solaris x86_64 build fails in 1.1.1b with this error:
Assembler:
        "ghash-x86_64.s", line 1311 : Syntax error
        Near line: ".cfi_startproc      "
        "ghash-x86_64.s", line 1375 : Syntax error
cc: fbe failed for ghash-x86_64.s


1.1.1a did not show this problem.  From reading the code, it appears .cfi_startproc directives were added to 1.1.1b and that there are 2 missing  .cfi_endproc directives.  I have coded a fix and will submit a PR.

```
normg@echo>/opt/studio12.5/bin/cc -KPIC -m64 -xstrconst -Xa -KPIC -mt -g -DFILIO_H -DL_ENDIAN \
> -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT \
> -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM \
> -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM \
> -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM \
> -DOPENSSLDIR="\"/export/foof3/users/buildgss/35/build45663/slow13/openssl_1.1/install13/ssl\"                                    " \
> -DENGINESDIR="\"/export/foof3/users/buildgss/35/build45663/slow13/openssl_1.1/install13/lib/e                                    ngines-1.1\"" \
> -D_REENTRANT  -c -o ghash-x86_64.o ghash-x86_64.s
Assembler:
        "ghash-x86_64.s", line 1311 : Syntax error
        Near line: ".cfi_startproc      "
        "ghash-x86_64.s", line 1375 : Syntax error
cc: fbe failed for ghash-x86_64.s

```

**Comment by levitte** [comment]
Oh, I've seen that being fixed already...  yeah, in #8281, but that went to master only.  It should have gone to the 1.1.1 branch as well.

**Comment by levitte** [comment]
Cherry-picking done, see https://github.com/openssl/openssl/pull/8281#issuecomment-468043170

**Comment by nrgiii** [comment]
Wow, that was fast! Closing issue.

**Comment by levitte** [comment]
Glad you approve.
