### ISSUE TITLE
openssl supports obsoleted curves in TLS 1.3

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8369]
using c8147d37ccaaf28c4

When openssl client is configured to support only one of the curves that is forbidden in TLS 1.3, it does send that curve in `supported_groups` extensions and it does also put appropriate key share into the `key_share` extension.

When openssl server is configured to support curves from the obsolete range, it will accept them and negotiate the connection.

This is in direct violation of RFC 8446 Section B.3.1.4:
```
   Values within "obsolete_RESERVED" ranges are used in previous
   versions of TLS and MUST NOT be offered or negotiated by TLS 1.3
   implementations.
```

Reproducer:
```
openssl s_server -www -key /tmp/localhost.key -cert /tmp/localhost.crt -curves secp256k1 &
openssl s_client -connect localhost:4433 -curves secp256k1
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
---
Certificate chain
 0 s:CN = localhost
   i:CN = localhost
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC/jCCAeagAwIBAgIJAJY7vRSnaOIeMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
BAMMCWxvY2FsaG9zdDAeFw0xOTAyMjgxMTMzMDBaFw0yMDAyMjgxMTMzMDBaMBQx
EjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAOZF7CHMipJNGSXF9zkic4KHhfbeguwpzQ5BURj5FTsYaCDNVvbZoCXg9wQu
Ba3Zh00IJOSiw+/QO/fAUo1K4OfmcLsayPeYo/ETazDEOVeR3ip5UbPkmUUsJHNM
v+CndK47dvdMWMg8Z7tdhiKSRR52/P0LpRGb581VsbwDsE0qEOPCZWw9CyR24XXs
AP1gtGgSG4S270TSgtObhElgnHhByzE7CU4yoVtOf/wTxLD3nTZ0Re6IH5TzJBYS
r32MNerQJ1+og875smvharui9mvqkf7C9t/3iUZk0q1txjRvkPCULIghswBJOouW
MWy4QVV0ngvjb08yX185TbK3lC0CAwEAAaNTMFEwHQYDVR0OBBYEFOxcwiSeNPM5
eUd3bqn626NmHndTMB8GA1UdIwQYMBaAFOxcwiSeNPM5eUd3bqn626NmHndTMA8G
A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAKnLxDuhhABncrwN+Nmn
CZEqX5nsm8bf5WMe6Tsiny1pJ7oM3xkmddYrgB0JsonNQsFiNTlRcTvLLXqtUR9q
rZG0NCC2dPGg7zt20tP3Va2mnxs6KnA2HDLGamHX3KQIkxh6gSWDD+fR5KO0zCTm
Wj4fyDWZREZRVS5GkUvUD2uojlUPXnSIBhqXcaOKH8lAs0eNswDkL4WMsuDGYFhM
nOEd6NxyHciSBIff74xZY7mrOpzSqRja6Ccy2NWp4tqTTwCxy0NROAYwqk+/wC24
v8IzvEbrXfZOUx2dhM9jU3hI+ngZoLcmaHISCIpdIahUvAkrjuBBsG9fix5XhmhE
x3E=
-----END CERTIFICATE-----
subject=CN = localhost

issuer=CN = localhost

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, secp256k1, 256 bits
---
SSL handshake has read 1359 bytes and written 398 bytes
Verification error: self signed certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 18 (self signed certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 6B5371AD62219E323837AEA7DBBD245A5A801F53F5AF79241DDBAFA830B69021
    Session-ID-ctx: 
    Resumption PSK: 120016B3EF3566237CEEED5E4FF3A742886E64FA5EB5902401B45CB0D88524F7D36114112C0F4EED423408FE8E09373E
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - de cb 39 b8 8a 18 6c 8a-c3 a7 75 10 b7 fa b5 ae   ..9...l...u.....
    0010 - de df b0 c8 9b 89 29 84-84 47 7f 3d 98 6c 8c cc   ......)..G.=.l..
    0020 - b7 14 88 b0 d0 6e 15 85-a3 40 1b 14 f1 a3 c7 e9   .....n...@......
    0030 - 7d 8a 0c ee cd 89 51 57-95 e3 33 4e ab df 49 09   }.....QW..3N..I.
    0040 - 9b f9 d5 0b e6 88 7f 71-e5 78 06 0a 93 d6 e4 4e   .......q.x.....N
    0050 - 1e ef 48 bf 5e 27 10 b6-19 91 b6 55 17 52 b2 61   ..H.^'.....U.R.a
    0060 - 82 9b 87 13 22 c9 3d 2b-23 a6 66 d1 89 36 13 9e   ....".=+#.f..6..
    0070 - 4a 5b fb cd 1d 12 fe ec-48 bf 62 18 ad bf 3d 38   J[......H.b...=8
    0080 - 32 f0 46 93 d3 24 2b ef-81 0b f3 3e c7 dc 2d 42   2.F..$+....>..-B
    0090 - aa a5 14 fd 62 bf 02 fe-99 7d aa c3 55 a6 93 fa   ....b....}..U...
    00a0 - 9c cf 29 80 4f 6b 2c c7-30 00 60 be bb a0 e6 30   ..).Ok,.0.`....0
    00b0 - 64 ee a0 b6 05 b6 37 9e-8c 21 38 cd a1 6d 6c 57   d.....7..!8..mlW
    00c0 - a7 68 81 42 dc dd 73 4c-31 4f 16 4f 70 e1 7d 47   .h.B..sL1O.Op.}G

    Start Time: 1551357312
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 173306786EEF2BDB23A79C1214DB7B261E807F703AFBE5FD74027B4461C6AAD5
    Session-ID-ctx: 
    Resumption PSK: 088A16FF0B7BC72F7CC3788F0540C900F9C632F15E2D9FFF35070509FB918416DB450F5157E46AD92BCFAC7B0A5622D1
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - de cb 39 b8 8a 18 6c 8a-c3 a7 75 10 b7 fa b5 ae   ..9...l...u.....
    0010 - 2c 3d 27 fd 87 d3 33 14-1d a4 fc 6d d0 92 b4 99   ,='...3....m....
    0020 - 81 d1 e7 36 6a 04 18 29-55 0e 14 99 c2 b8 65 3e   ...6j..)U.....e>
    0030 - a7 8b 8f 9d 1f 87 39 00-c3 20 d7 4a d5 f7 9e 96   ......9.. .J....
    0040 - c3 da 89 e4 30 40 c5 ae-8d ac eb 52 b9 44 7e 49   ....0@.....R.D~I
    0050 - d5 0d e3 9d bb 51 87 8a-74 c2 15 4e fa 6f 91 2e   .....Q..t..N.o..
    0060 - e8 07 6b d2 3e 72 41 81-8d 9c c8 3a d4 b5 dd 6a   ..k.>rA....:...j
    0070 - fe 74 3a 7a a5 9c 66 fd-be 6f 08 5d b4 c0 de cc   .t:z..f..o.]....
    0080 - 33 ad 40 ef f5 62 d5 24-46 c3 c1 ba f4 d7 30 4f   3.@..b.$F.....0O
    0090 - 54 79 d5 6c 78 5e 87 00-49 be fb f2 25 28 fa da   Ty.lx^..I...%(..
    00a0 - 28 8c 93 64 c5 78 36 e8-2b c2 82 d0 31 b7 09 5a   (..d.x6.+...1..Z
    00b0 - 42 28 4c 87 4b 59 d9 47-ea bd 72 fd c2 fc 66 d7   B(L.KY.G..r...f.
    00c0 - f5 f7 30 b5 43 ce 0b c4-77 5e ad b0 f7 57 8f 65   ..0.C...w^...W.e

    Start Time: 1551357312
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
DONE
```

**Comment by bernd-edlinger** [comment]
Note: #7485 fixes this issue, except that it also enables brainpool codepoints.

**Comment by tomato42** [comment]
@bernd-edlinger the problem is combination of that requirement (which does suggest that servers need to reject ClientHellos with any of the obsolete curves if they advertise TLS 1.3 too) and backwards compatibility for clients that actually want to negotiate brainpool...

as the old (TLS 1.2-only) implementations won't recognise new IDs, while new implementations should abort upon seeing old IDs

**Comment by bernd-edlinger** [comment]
Sounds more like a specification erratum.
We have already enough stuff that don't IOP with TLS1.3, don't we?

**Comment by tomato42** [comment]
"IOP"?

**Comment by bernd-edlinger** [comment]
Inter-OPerability

**Comment by tomato42** [comment]
I don't see how - that fragment disallows only the TLS 1.3 clients from sending those groups, TLS 1.2 clients still can do that and the servers should still accept them, irrespective of groups included

**Comment by bernd-edlinger** [comment]
How I understood that, is that it is pointless to send curves that are TLS1.2 only, when
you want to negotiate TLS1.3 only, and vice-versa.  In the client hello.
But if you want to negotiate TLS1.3+TLS1.2 the server should ignore what does not work
for the selected protocol.

**Comment by tomato42** [comment]
but that's not what the specification says, it says "MUST NOT be offered [...] by TLS 1.3 implementations.", ergo if you do advertise TLS 1.3, you MUST NOT include those groups

yes, the server MAY ignore those groups, but because such ClientHello is technically malformed, it isn't required to accept it

**Comment by bernd-edlinger** [comment]
I'm not a lawyer, but as I said, if we implemented it this way it will cause damage.

**Comment by tomato42** [comment]
and I'm saying that sending them in a TLSv1.3 ClientHello will cause damage too

thus the "problem" I mentioned in the [previous comment](https://github.com/openssl/openssl/issues/8369#issuecomment-468343466) and something I should be addressed in the draft

**Comment by kaduk** [comment]
So, I raised this topic back before 1.1.1 finalized, and the conclusion was that we weren't willing to remove the ability to use the obsolete curves in a backwards-compatible release.
Since 3.0.0 is not guaranteed to be backwards compatible, I'm inclined to support some work in this space, though the exact bounds of what I would support are not entirely clear.

**Comment by tomato42** [comment]
I'm not saying that the support for those curves should be removed completely, but at the very least openssl server should not negotiate them in TLS 1.3

**Comment by t8m** [comment]
So to summarize - the client-side issue seems to be bug in the RFC (at least for the case where client accepts negotiating TLS-1.2 with the obsolete curves). And the server-side issue is RFC violation however it should be fairly harmless one at least until the obsolete curves are found to be really insecure (ignoring the short ones for now).

**Comment by kaduk** [comment]
> the client-side issue seems to be bug in the RFC

While that's a defensible position to take, it does not, however, qualify for an erratum, since it was a decision consciously made at time of publication.

**Comment by bernd-edlinger** [comment]
like the brexit ?

**Comment by tomato42** [comment]
no

4 years after the brainpool curves were defined for TLS they weren't supported by more than 10% of Alexa top 1M, so it's not like they were popular among users. Their selection criteria weren't exactly snow-white (https://bada55.cr.yp.to/brainpool.html, https://www.ietf.org/mail-archive/web/tls/current/msg10271.html) so they weren't popular among cryptographers either.

**Comment by larsrh** [comment]
I don't know what the correct solution to this should be, but I figured I could post my findings from a debug session here (involving OpenSSL 1.1.1c). I Wireshark'ed an OpenSSL client session with the following invocation:

```
openssl s_client -connect localhost:4343 -curves "X25519:P-256:P-521:P-384:secp256k1" -showcerts -tls1_3
```

The server was configured to present an EC certificate with the secp256k1 curve.

Here's the Wireshark output:

![Screenshot_20190731_143730](https://user-images.githubusercontent.com/923079/62212353-d4552580-b3a0-11e9-9509-c2244475fe1a.png)

As you can see secp256k1 (0x0016) is listed even though it is unsupported in the `supported_groups` extension.

As far as I could tell, neither the Java TLS implementation (throws an exception because there is no suitable hash algorithm for the curve) nor OpenSSL's own `s_server` can finish the handshake with these parameters.

**Comment by tomato42** [comment]
> OpenSSL's own `s_server` can finish the handshake with these parameters.

you need to change the set of supported curves both in client and server; start `s_server` with `-curves secp256k1`

**Comment by larsrh** [comment]
I did that, but that only works if both client and server use TLS 1.2. It fails with 1.3.

**Comment by tomato42** [comment]
just retested with 74b9ce2d84a5fe (current OpenSSL_1_1_1-stable branch); exact same result as in original comment

**Comment by larsrh** [comment]
I cannot reproduce this:

```
$ openssl s_server -accept 8080 -cert demo/cert.pem -key demo/key.pem -curves secp256k1 -tls1_3
Using default temp DH parameters
ACCEPT
ERROR
139853611709632:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:ssl/statem/statem_srvr.c:1667:
shutting down SSL
CONNECTION CLOSED
```

```
$ openssl s_client -connect localhost:8080 -curves secp256k1 -showcerts -tls1_3
CONNECTED(00000003)
140636565664960:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1536:SSL alert number 70
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 240 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

It works when using `-tls1_2`.

**Comment by tomato42** [comment]
> `:SSL routines:tls_early_post_process_client_hello:unsupported protocol`

that's clearly unrelated to curve selection

**Comment by sahanaprasad07** [comment]
would it be interesting to add this issue to  3.0.0 beta1?

**Comment by romen** [comment]
@mattcaswell should be able to confirm, but I believe one option now could be to have a provider dedicated to add brainpool support (with whatever code points are acceptable for that) via capabilities.

The default provider would provide the brainpool crypto functionality, the optional provider would just "publish" the capability for TLS 1.3. Do you think that is possible Matt?
I have no opinion regarding the matter if such a provider should be provided by the openssl project or if we could just provide support for the author of such a provider and instruct users to try it out.

**Comment by mattcaswell** [comment]
> whatever code points are acceptable for that

RFC8734 specifies the relevant codepoints.

> The default provider would provide the brainpool crypto functionality, the optional provider would just "publish" the capability for TLS 1.3. Do you think that is possible Matt?

Yes, this sounds viable.

> I have no opinion regarding the matter if such a provider should be provided by the openssl project or if we could just provide support for the author of such a provider and instruct users to try it out.

I see no reason why we wouldn't have this in our default provider. The only question is *when* we do that. I don't see that as something we would hold beta 1 for, nor do I think the core dev team should spend time on it. OTOH hand if someone contributed a PR adding the relevant codepoints before beta 1 is released I don't see why we wouldn't add it.

Ultimately though if such a PR doesn't materialise in time it could be added by a third party provider in the manner you suggest.

**Comment by kaduk** [comment]
While having an avenue to support the new TLS 1.3 brainpool codepoints is fine, I thought the initial report here was that we should not be offering (or accepting) the old codepoints in a TLS 1.3 implementation.  The recent proposals for a provider dedicated to brainpool support do not seem to address that topic.

**Comment by tomato42** [comment]
(sorry, mis-clicked)

**Comment by TheBestOrNothing** [comment]
@mattcaswell I meet the same issue as @larsrh. secp256k1 only works if both client and server use TLS 1.2 but fails with 1.3. Do you have draft timeline to fix this issue? It is very helpful and useful to build up peer to peer safe communication with BTC or ETH key.

**Comment by mattcaswell** [comment]
> @mattcaswell I meet the same issue as @larsrh. secp256k1 only works if both client and server use TLS 1.2 but fails with 1.3. Do you have draft timeline to fix this issue? It is very helpful and useful to build up peer to peer safe communication with BTC or ETH key.

Please raise this as a separate issue as it is different to the initial issue raised here.
