### ISSUE TITLE
Possible ABI break when updating openssl from 1.1.1a to 1.1.1b

### ISSUE THREAD

**Issue by Erick555** [openssl/openssl#8386]
Hi!
In [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) we're trying to keep ABI compatibility when updating elements like openssl to new releases. In order to achieve this we use [libabigail](https://sourceware.org/libabigail/) tool to automate ABI compat checks. During openssl update from 1.1.1a to 1.1.1b our tool produced following complaint:
```
┌───────────────────────────────────────┐
│ ABI Break: libcrypto.so.1.1:libcrypto │
└───────────────────────────────────────┘

Functions changes summary: 0 Removed, 1 Changed (4 filtered out), 0 Added (2 filtered out) functions
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

1 function with some indirect sub-type change:

  [C]'function void OPENSSL_INIT_free(OPENSSL_INIT_SETTINGS*)' at conf_lib.c:409:1 has some indirect sub-type changes:
    parameter 1 of type 'OPENSSL_INIT_SETTINGS*' has sub-type changes:
      in pointed to type 'typedef OPENSSL_INIT_SETTINGS' at ossl_typ.h:141:1:
        underlying type 'struct ossl_init_settings_st' at conf.h:15:1 changed:
          type size changed from 64 to 192 (in bits)
          2 data member insertions:
            'char* ossl_init_settings_st::filename', at offset 0 (in bits) at conf.h:21:1
            'unsigned long int ossl_init_settings_st::flags', at offset 128 (in bits) at conf.h:23:1
          1 data member change:
           'char* ossl_init_settings_st::appname' offset changed from 0 to 64 (in bits) (by +64 bits)
```
As part of our [discussion](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1056) about what to do with that we would like to ask about your opinion on the matter. Especially I wanted to ask if reported change was intentional and if it's safe for backward compatibility thus if above report is a false positive.

I would be grateful if you can find time to respond. Thank you.

**Comment by davidben** [comment]
`struct ossl_init_settings_st` is defined an internal header (include/internal/conf.h). It's an opaque type so that new versions can change the size without breaking ABI. Is it possible your tool is scanning the entire include directory, rather than just include/openssl?

**Comment by kroeckx** [comment]
As far as I can see OPENSSL_INIT_SETTINGS is a non-pubilc type.
You need to allocate it using OPENSSL_INIT_new(), and then you
only pass that pointer to OpenSSL functions to do something with
it. You can not access the member fields in the applications. The
library will always allocate the correct length, and the library
is the only thing that can look at the members and modify it. So
this does not look like an ABI problem. You should not look at
internal header files for ABI problems.

**Comment by Erick555** [comment]
Thank you very much for a quick and helpful comments. I appreciate it.
