### ISSUE TITLE
const mismatch between 

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#8394]
The PKCS8_pkey_get0_attrs function returns const STACK_OF(X509_ATTRIBUTE) and there is no non-const variant of this function.
The X509at_get0_data_by_OBJ accepts STACK_OF(X509_ATTRIBUTE)

**Comment by beldmit** [comment]
The PKCS8_pkey_get0_attrs function returns const STACK_OF(X509_ATTRIBUTE) and there is no non-const variant of this function.
The X509at_get0_data_by_OBJ accepts STACK_OF(X509_ATTRIBUTE)

**Comment by levitte** [comment]
Without looking, I would think of constifying the argument to `X509at_get0_data_by_OBJ` before anything else, if that's possible.

**Comment by akshit-akhoury** [comment]
Hey, if the ask is to set the arguments of `X509at_get0_data_by_OBJ ` to accept const STACK_OF(X509_ATTRIBUTE), I think I can make this change.

**Comment by mattcaswell** [comment]
> Hey, if the ask is to set the arguments of X509at_get0_data_by_OBJ to accept const STACK_OF(X509_ATTRIBUTE), I think I can make this change.

Yes please!

**Comment by akshit-akhoury** [comment]
Hey, I've created a PR, wasn't sure if this change required either update of docs or tests.

**Comment by beldmit** [comment]
Fixed by #13062
