### ISSUE TITLE
Documentation bug: SHA is no longer supported in 1.1.1

### ISSUE THREAD

**Issue by PatrickMiddleton** [openssl/openssl#8407]
Have just built OpenSSL 1.1.1b, and unit tests in other software failed to build because SHA support is no longer present.

https://www.openssl.org/docs/man1.1.1/man3/SHA1_Init.html states "The predecessor of SHA-1, SHA, is also implemented, but it should be used only when backward compatibility is required."

**Comment by tnarg999** [comment]
I tried building OpenSSL 1.1.1b and I did not encounter any issues with SHA support. From what I understand, OpenSSL removed support of SHA-0 in version 1.1.0 and I could not find any implementation of SHA-0 in the code. Looking at the git history, it looks like that line "The predecessor of SHA-1 ..." was added 21 years ago; therefore, I think this line should be removed from the documentation.

**Comment by WolfWings** [comment]
Stumbled through this issue looking for 'good first issue' issues, looks like this was entirely resolved, live documentation for 1.1.1 shows the wording corrected, etc, I think this issue is safe to close?

**Comment by t8m** [comment]
Yes, closing. Thank you for the heads up.
