### ISSUE TITLE
Manpages index page on website is broken

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8413]
https://www.openssl.org/docs/manpages.html index pages are now missing. Clicking on master correctly shows the index of pages but the links for 1.1.1, 1.1.0 and 1.0.2 now link to basic html index pages of html files.

**Comment by levitte** [comment]
That...  shouldn't happen.  I've regenerated everything, will investigate further tomorrow (it's been a long day)

**Comment by mlindner** [comment]
@levitte Just following up, if the problem was found.

**Comment by mattcaswell** [comment]
This doesn't seem to be a problem any more. Closing.
