### ISSUE TITLE
aix6_ppc is hanging during tests due to a recent change to rand

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#8416]
The changes made in #8251 are causing issues on AIX. Running the tests using
>make tests
Results in tests hanging before the tests actually start running. The test that hangs is different on different runs (e.g- test_rand, test_sm2)
It was running for 15 hours stuck on one of the tests.
Reverting the changes makes the tests run without hanging.

The build config was:
    perl ../Configure --prefix=/scratch/nsegen/jenkins/workspace/openssl-aix6_ppc64/install shared no-asm -DOPENSSL_NO_ASYNC aix64-cc

Perl information:

    perl
    5.24.0 for aix-64all

Enabled features:

    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    ktls                    [default]   OPENSSL_NO_KTLS
    afalgeng                [not-linux] 
    asan                    [default]   OPENSSL_NO_ASAN
    asm                     [option]    OPENSSL_NO_ASM
    crypto-mdebug           [default]   OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]   OPENSSL_NO_EGD
    external-tests          [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]   OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]   OPENSSL_NO_HEARTBEATS
    md2                     [default]   OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]   OPENSSL_NO_MSAN
    rc5                     [default]   OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]   OPENSSL_NO_SCTP
    ssl-trace               [default]   OPENSSL_NO_SSL_TRACE
    ubsan                   [default]   OPENSSL_NO_UBSAN
    unit-test               [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]   
    zlib-dynamic            [default]   
    ssl3                    [default]   OPENSSL_NO_SSL3
    ssl3-method             [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar -X64",
    ARFLAGS => "r",
    CC => "cc",
    CFLAGS => "-O",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib -X64",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c",
    aes_obj => "aes_core.o aes_cbc.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "bn_asm.c",
    bn_obj => "bn_asm.o",
    bn_ops => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-q64 -qmaxmem=16384 -qro -qroconst -qthreaded",
    chacha_asm_src => "chacha_enc.c",
    chacha_obj => "chacha_enc.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o",
    cppflags => "-D_THREAD_SAFE",
    cpuid_asm_src => "mem_clr.c",
    cpuid_obj => "mem_clr.o",
    defines => [  ],
    des_asm_src => "des_enc.c fcrypt_b.c",
    des_obj => "des_enc.o fcrypt_b.o",
    disable => [  ],
    dso_scheme => "dlfcn",
    ec_asm_src => "",
    ec_obj => "",
    enable => [  ],
    ex_libs => "-lpthreads",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "-Wl,-bsvr4",
    lib_cflags => "",
    lib_cppflags => "-DB_ENDIAN",
    lib_defines => [  ],
    md5_asm_src => "",
    md5_obj => "",
    modes_asm_src => "",
    modes_obj => "",
    module_cflags => "-qpic",
    module_cxxflags => "",
    module_ldflags => "-Wl,-G,-bsymbolic,-bexpall",
    padlock_asm_src => "",
    padlock_obj => "",
    perl_platform => "AIX",
    perlasm_scheme => "aix64",
    poly1305_asm_src => "",
    poly1305_obj => "",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    shared_cflag => "-qpic",
    shared_defflag => "-Wl,-bE:",
    shared_defines => [  ],
    shared_extension => "64.so.\$(SHLIB_VERSION_NUMBER)",
    shared_ldflag => "-Wl,-G,-bsymbolic,-bnoentry",
    shared_rcflag => "",
    shared_target => "aix",
    sys_id => "AIX",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPPFLAGS = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LDFLAGS = 
    LDLIBS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar -X64
    ARFLAGS         = r
    CC              = cc
    CFLAGS          = -O
    CPPDEFINES      = OPENSSL_NO_ASYNC
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = perl
    RANLIB          = ranlib -X64
    RC              = windres

**Comment by bernd-edlinger** [comment]
is this linux, which version ?

**Comment by levitte** [comment]
@bernd-edlinger, the Configure command @slontis shows has this: aix64-cc

**Comment by bernd-edlinger** [comment]
So something completely different.
It is a bit surprising why the select on /dev/random does only
sometimes hang.  Does the select on AIX provide any
information on the entropy pool used by /dev/urandom?

**Comment by bernd-edlinger** [comment]
I mean could it be that /dev/urandom is not properly initialized
when this select starts to wait?

**Comment by bernd-edlinger** [comment]
Can you try out what happens on your system when you do this:
`dd if=/dev/random bs=1 count=1 | hexdump -C`
does that block or is there data available?

**Comment by slontis** [comment]
dd if=/dev/random bs=1 count=100 is generating data, but it can be a bit slow (5-30 secs) on multiple runs.
dd if=/dev/urandom bs=1 count=100 is fast.
Running an individual test that it was getting stuck on multiple times seemed to run well.

**Comment by slontis** [comment]
After logging data in DEVRANDOM_WAIT it is hanging on the select(). Ocassionally it doesnt block and a test will run, but most of the time it blocks on the first call. Any tests that use libcrypto cause 32 bytes to be grabbed (its not the actual test grabbing rand data). It should only be doing this for linux configurations maybe? Does waiting for dev/random really ensure that /dev/urandom is initialized?

**Comment by paulidale** [comment]
The `getrandom(2)` system call was introduced into Linux mid-late 2014.  If it is available, it should be used unconditionally.  I'd only not use it if the `getentropy(2)` call were available.

As for `/dev/urandom`, I've doubts that it is _guaranteed to be seeded_ if `/dev/random` is readable.  I've not checked current kernels (where `getrandom(2)` is available and preferable), but I believe early kernels didn't automatically seed `/dev/urandom` when enough entropy had been gathered.  Rather, it was seeded on `read(2)`.  Likewise, checking the value in `/proc/sys/kernel/random/entropy_avail` was not sufficient -- between seeing that there was enough entropy available and reading from `/dev/urandom`, another process could have stolen all of the entropy via `/dev/random`.

Effectively: we cannot fix the unfixable.

Ideally, I'd like to (eventually) include Stephan Müller's [CPU Jitter](http://www.chronox.de/jent/doc/CPU-Jitter-NPTRNG.html) as a souce.

**Comment by bernd-edlinger** [comment]
Okay, thanks.
That looks like select is blocking for hours when a read would only block for seconds.
So I guess limiting that to linux would be fine.

As for linux v2.6 .. v4.8 that should be guaranteed.
See for instance `add_interrupt_randomness` in `drivers/char/random.c`,
where the first 128 bits of randomness went directly to the `nonblocking_pool`,
and only when that is initialized new entropy go to the `input_pool`.

From there on we have
```
source(s) -> input_pool  -> blocking_pool
                         -> nonblocking_pool
```

so when the `input_pool` is eventually receiving data (that is the earliest time
when a select would wake up), the `nonblocking_pool` is also seeded.

**Comment by bernd-edlinger** [comment]
> Effectively: we cannot fix the unfixable.

Yes, but I doubt we can trust completely in the implementation of the underlying random source.
Somehow I would think one need to have more than one, and use measures in case
one of them fails.

That includes the using the .rnd file for instance, which we had in the past,
and which mitigates any weakness in the initial seeding of the RNG, as long
as it is kept secret.
