### ISSUE TITLE
Create a gh-pages site

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#8424]
GitHub can automatically create a website for a user, project, or organization.  It's called "github pages"  For openssl it would be "openssl.github.io"  That should be a simple repo with one file, index.html, that redirects to the official OpenSSL website.

Please take a look at https://github.com/richsalz/openssl.github.io and consider using it.

**Comment by levitte** [comment]
... why do we need this?

**Comment by richsalz** [comment]
In my experience folks who look at github.org/FOO are getting more trained to look at FOO.github.io

And the cost, once you create the repo, is zero.

**Comment by levitte** [comment]
And here I thought that people read the README, and possibly clicked on URLs found there.

It's not like I really mind, but I do get worried about yet another thing to keep in mind, even if it looks like a one time easy peazy thing *now*

So I'm agnostic to the idea, other @openssl folks will have to speak their mind

**Comment by noloader** [comment]
>  That should be a simple repo with one file, index.html, that redirects to the official OpenSSL website.

Good idea. It takes the name away from potential squatters of the OpenSSL name.

**Comment by mattcaswell** [comment]
There seems no enthusiasm for this idea at the moment. Closing.
