### ISSUE TITLE
SSL_CTX_new failed,but cant't get details of the error.

### ISSUE THREAD

**Issue by hucailai** [openssl/openssl#8427]
https://github.com/openssl/openssl/blob/7120f1e7c74c8220f43fd28ac7303c0cab29dabe/crypto/rand/rand_unix.c#L381

in function “get_random_device”，if the syscall "open" failed，we can‘t get the system error code。

whether is needed to push some error code to error stack？

**Comment by hucailai** [comment]
???

**Comment by kaduk** [comment]
Given the way the code is architected to retry, to try different devices, and to try again on the next attempt to get random bytes, it's unclear that pushing an error code for any single failed open is appropriate.
(IIUC, the "common" case when this open fails would be showing up as

drbg_lib.c:395
```C
        RANDerr(RAND_F_RAND_DRBG_INSTANTIATE, RAND_R_ERROR_RETRIEVING_ENTROPY);
```
).

But tagging @mspncp in case he has further thoughts or wants to drag in other opinions.

**Comment by mspncp** [comment]
@hucailai are you sure that it is really the reading of the random _device_ (`/dev/urandom`, etc.) which is failing? On newer kernels(*), OpenSSL would first attempt to use the `getrandom()` system call, which is the preferred choice. Only afterwards, the devices would be opened and read.

What is your distribution and kernel version?

As for reporting the errno: in principle that's a good suggestion, but as @kaduk wrote, the entropy collector tries multiple entropy sources and only if the last one finally fails it makes sense to report an error. So reporting the error(s) is not trivial, but I'll give it a thought.


(*) _getrandom() is available starting with kernel version >= 3.17 according to @kroeckx, see https://github.com/openssl/openssl/issues/5330#issuecomment-391455244)_.

**Comment by mspncp** [comment]
Did you try running your program with `strace`?

**Comment by hucailai** [comment]
because the  rights of of this  “/dev/urandom 、 /dev/random  ”，is changed， and  this “/dev/srandom” not exist in system。 so we just get the  errno =2  “ #define ENOENT   2 /* No such file or directory */”

but we cat‘t get the  erron = 13   #define EACCES 13 /* Permission denied */
because it replace by  the last syscall。


so i suggest to push  error to stack while open failed。

**Comment by kaduk** [comment]
I am pretty confused about what sort of system would need to restrict access to *both* /dev/random and /dev/urandom.  (The former is somewhat understandable due to the Linux broken historical behavior predating getentropy().)

**Comment by paulidale** [comment]
I don't think we should be pushing errors whenever this `open(2)` call fails.  We _expect_ it to fail for at least one of the device entries on most systems, the RNG seeding code tries to cope with this.  We also make no attempt to preserve `errno(3)` anywhere else in the source code.  In my view this is a bug in the operating environment not libcrypto.

My suggestion would be to either make one of the random device nodes readable or to configure OpenSSL to not try to use them as a source.

**Comment by hucailai** [comment]
i got it ,thanks
