### ISSUE TITLE
EVP_bf_cfb() missing in x86 and x64 builds of OpenSSL 1.1.1b

### ISSUE THREAD

**Issue by MikeZarlenga** [openssl/openssl#8436]
I'm trying to move some legacy crypto code off OpenSSL 0.9.6c to the latest version.

I downloaded and built version 1.1.1b from source, using Visual Studio 2019 on Windows 7 x64.
I successfully built both the 32-bit (VC-WIN32) and 64-bit (VC-WIN64A) configurations.

My problem is, my legacy code uses EVP_bf_cfb() and it's missing from both the 32- and 64-bit libcrypto DLLs (but I do see EVP_bf_cfb64() in the DLLs)

- Has EVP_bf_cfb() been deprecated? (it's still listed on the 1.1.1 man page)
- Has it been replaced with  EVP_bf_cfb64()? Are they compatible?
- Did I build 1,1.1b wrong?

Best regards.

**Comment by mattcaswell** [comment]
Its defined as a macro in openssl/evp.h:
````
#  define EVP_bf_cfb EVP_bf_cfb64
````

**Comment by MikeZarlenga** [comment]
Yes, I see that.

Is EVP_bf_cfb64 a backward-compatible replacement for EVP_bf_cfb?

When I encrypt with the legacy code using cipher EVP_bf_cfb, I'm unable to decrypt using the same key and iv in the new code, using cipher EVP_bf_cfb64.

If someone can tell me that they are, indeed, compatible, then I know my problem is elsewhere, probably in the new code and not the underlying OpenSSL library.

Best regards.

**Comment by richsalz** [comment]
Perhaps you need "-md md5" ?  See https://www.openssl.org/docs/faq.html#USER

**Comment by mattcaswell** [comment]
They are intended to be compatible....but a lot could have happened in the 17 years since 0.9.6c came out...

**Comment by MikeZarlenga** [comment]
> Perhaps you need "-md md5" ? See https://www.openssl.org/docs/faq.html#USER

Thank you, that's a good lead, I'll investigate.

**Comment by MikeZarlenga** [comment]
Wow. The problem was very well hidden!

The original programmer set the IV using a char [] that's shorter than 8 bytes and OpenSSL grabs 8 bytes  for the IV regardless, so the actual IV was IV in the code, plus 0xCCs padded out to 8 bytes, total. It's funny, for years, no one knew why this code had to be built in debug mode to work, now I know and I can fix that.

**Comment by mattcaswell** [comment]
Great - glad you fixed it.

**Comment by levitte** [comment]
Note to @openssl : maybe we do need to be more careful with size assumptions going forward
