### ISSUE TITLE
Build openssl 1.1.0 with "/INTEGRITYCHECK" option

### ISSUE THREAD

**Issue by phongpro1996** [openssl/openssl#8448]
hello
I want to add "IntegrityCheck" option to openssl1.1.0 when I build it. I need some help. How can i do this?
Thank for helping

**Comment by mspncp** [comment]
I haven't tried it, but it should be possible to add it as `LDFLAGS=...` at the end of the configure commmand.

```
perl Configure VC-WIN64A ... LDFLAGS="/nologo /debug /integritycheck"
```

(_Note that you need to sign libcrypto.dll and libssl.dll yourself if you add the [/INTEGRITYCHECK](https://docs.microsoft.com/en-us/cpp/build/reference/integritycheck-require-signature-check?view=vs-2017) linker option._)

**Comment by phongpro1996** [comment]
i type perl Configure VC-WIN64A LDFLAGS="/nologo /debug /integritycheck"
Then "nmake" and get a error
`NMAKE : fatal error U1064: MAKEFILE not found and no target specified`

**Comment by levitte** [comment]
Did the configuration command produce any output?  If it didn't produce a makefile, then something stopped the configuration process before that

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
