### ISSUE TITLE
Compiling with FIPS support breaks CRYPTO_set_mem_functions()

### ISSUE THREAD

**Issue by dfoxfranke** [openssl/openssl#8450]
I'm not sure precisely which versions this affects. I discovered the issue in the 1.1.0h-fips build distributed in OpenSuSE Tumbleweed, but also looked at the code in branch OpenSSL-fips-2_0-stable and the behavior appears the same.

When OpenSSL is built with GCC, `OpenSSL_init()` is declared with `__attribute__((constructor))`, causing it to automatically run when libcrypto is loaded, ahead of calling `main()`.

When `OPENSSL_FIPS` is #defined, `OpenSSL_init()` will call `RAND_init_fips()`, which entails doing some memory allocations.

`CRYPTO_set_mem_functions()` has to be called before any memory allocations have occurred, or it will fail.

This function is therefore unusable when OpenSSL is compiled with FIPS support, regardless of whether FIPS mode is ever actually enabled.

**Comment by mattcaswell** [comment]
Unfortunately we are no longer making changes to the OpenSSL-fips-2_0 code, so this is not something that will be fixed.

**Comment by dfoxfranke** [comment]
That's the answer I expected, but I thought I'd file this anyway so you could make a note not to reintroduce the same bug when FIPS support returns.

**Comment by mattcaswell** [comment]
Since this is in the old FOM it won't be fixed so closing this issue.
