### ISSUE TITLE
Explicit external definition of string names

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#8454]
In 3.0 there will be well defined string names used for various purposes. The design document has this to say about it:

> Names are required for algorithms, parameters, and properties. In order to ensure consistency and to enable external Provider implementers to define new names in a consistent way there will be a registry of recommended or used names. It will be maintained separately from the sources.

So far not much thought has been given to what that registry will look like. IMO there should be:

* A well defined format that can be made human readable and machine readable (see below)
* For each name a clear definition of what it is to be used for (e.g. algorithm name, property name, parameter name)
* For parameters we should be defining
    * The algorithm the parameter is associated with and what it is to be used for (e.g. is it associated with the private key? the public key? other agreed parameters?) etc
    * The expected type and (where appropriate) the width of the parameter (e.g. if it is an integer is it 32-bit/64-bit/multi-precision?)
* For properties we should be defining
    * Valid values
* Parameter names probably need to be unique within the scope of an algorithm but not beyond that, e.g. DSA has a "p" parameter, and so does DH; but they should be considered as different to each other.

The format should either be directly human readable or be able to be transformed into some human readable format so that it acts as documentation for Provider developers.

The format should also be machine readable so that we automate checking that OSSL_PARAM instances meet the requirements (possibly we could choose to just do such checking only in debug builds for performance reasons). We'd also have to be able to cope with scenarios where there is no well defined format (e.g. where an external provider is developed using parameters unknown to libcrypto).

**Comment by levitte** [comment]
> The format should either be directly human readable or be able to be transformed into some human readable format so that it acts as documentation for Provider developers.

I'm leaning toward XML, for two reasons:

1. it's a well understood markup, with a well defined schema syntax
2. with xsltproc, it's superbly easy to convert to anything we want (including C), given a suitable style sheet.

**Comment by paulidale** [comment]
> The format should also be machine readable so that we automate checking that OSSL_PARAM instances meet the requirements

Might it be better to generate the rather than just checking?  I don’t know if this would be practical or not.

**Comment by levitte** [comment]
> Might it be better to generate the rather than just checking? I don’t know if this would be practical or not.

That would be incredibly cumbersome. How would the code generator know what variable to associate the param name with in a specific `OSSL_PARAM` construction?

**Comment by paulidale** [comment]
In the XML perhaps? <variable>

**Comment by levitte** [comment]
So an external document will determine how I name my local variables?  No, sorry, I cannot see supporting that idea.

**Comment by levitte** [comment]
I'm currently going with the idea of generating a structure that holds the information for each parameter, and collect instances of those structures in appropriately named arrays.  Those names shall include the algorithm name.  Then we can have a simple function called something like `OSSL_PARAM_check` that takes three arguments: 1) the `OSSL_PARAM` array to be checked, 2) the size of that `OSSL_PARAM` array, and 3) a pointer to one of the generated type definition arrays.

This can be used in an assertion, at the discretion of the programmer.

**Comment by richsalz** [comment]
I think the XML(?) file should be able to specify in/out and optional.

**Comment by levitte** [comment]
No.  For an RSA object (just to pick a favourite example), there are the parameters "n", "d", "e", etc.  They aren't either in our out, that state *depends on the usage*, and it would be ridiculous to have two sets of parameters for each object, not to mention confusing.

**Comment by richsalz** [comment]
okay.

**Comment by mattcaswell** [comment]
It seems we're not taking this forward.
