### ISSUE TITLE
Create/init OSSL_PARAM on the stack

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#8471]
There don't seem to be any tests for creating -- *and initializaing* -- an OSSL_PARAM array on the stack.  I would think this would be the most common use-case within OpenSSL: EVP functions turning RSA BIGNUM etc into OSSL_PARAM lists and calling into a provider.  Am I wrong to think so?

**Comment by levitte** [comment]
Depending on C standard, they will either use the `OSSL_PARAM_` constructor macros or the `OSSL_PARAM_construct_` constructor functions, both of which are demonstrated in `test/params_test.c`.

**Comment by levitte** [comment]
> I would think this would be the most common use-case within OpenSSL: EVP functions turning RSA BIGNUM etc into OSSL_PARAM lists and calling into a provider. Am I wrong to think so?

Nope, that's the intention

**Comment by richsalz** [comment]
It would be good to have a testcase that creates and initializes, such as at https://github.com/openssl/openssl/pull/8377/files#diff-9ada85359453f0e7c673ab148047472dR57

**Comment by levitte** [comment]
https://github.com/openssl/openssl/blob/81d61a62faa809e6c51f5fc2b86fb0d31146fd5e/test/params_api_test.c#L453-L501

**Comment by richsalz** [comment]
That declares and builds at runtime.  This is about initializing on-stack. Is that possible?

**Comment by levitte** [comment]
You have hit the answer to that yourself:

``` C
#include <stdio.h>
#include <openssl/params.h>

void bar(const OSSL_PARAM *params)
{
  int bar;
  const OSSL_PARAM *p = OSSL_PARAM_locate(params, "foo");

  OSSL_PARAM_get_int(p, &bar);
  printf("%d\n", bar);
}

int main()
{
  int foo = 42;
  OSSL_PARAM params[] =
    { OSSL_PARAM_int("foo", &foo),
      OSSL_PARAM_END };

  bar(params);
  return 0;
}
```

```
: ; cc -std=c89 -pedantic -I ~/gitwrk/openssl.net/official/_build/include/ -I ~/gitwrk/openssl.net/official/master/include/ -o foo.o -c foo.c
In file included from foo.c:2:
foo.c: In function ‘main’:
/home/levitte/gitwrk/openssl.net/official/master/include/openssl/params.h:25:22  warning: initializer element is not computable at load time [-Wpedantic]
     { (key), (type), (addr), (sz), (rsz) }
                      ^
/home/levitte/gitwrk/openssl.net/official/master/include/openssl/params.h:29:5: note: in expansion of macro ‘OSSL_PARAM_DEFN’
     OSSL_PARAM_DEFN((key), OSSL_PARAM_INTEGER, (addr), sizeof(int), NULL)
     ^~~~~~~~~~~~~~~
foo.c:17:7: note: in expansion of macro ‘OSSL_PARAM_int’
     { OSSL_PARAM_int("foo", &foo),
       ^~~~~~~~~~~~~~
/home/levitte/gitwrk/openssl.net/official/master/include/openssl/params.h:25:5: warning: initializer element is not computable at load time [-Wpedantic]
     { (key), (type), (addr), (sz), (rsz) }
     ^
/home/levitte/gitwrk/openssl.net/official/master/include/openssl/params.h:29:5: note: in expansion of macro ‘OSSL_PARAM_DEFN’
     OSSL_PARAM_DEFN((key), OSSL_PARAM_INTEGER, (addr), sizeof(int), NULL)
     ^~~~~~~~~~~~~~~
foo.c:17:7: note: in expansion of macro ‘OSSL_PARAM_int’
     { OSSL_PARAM_int("foo", &foo),
       ^~~~~~~~~~~~~~
```

So yes, it *is* possible, provided a modern C standard is used, like I implied in my first comment above.

**Comment by levitte** [comment]
Note when I remove `-std=c89`:

```
: ; cc -pedantic -I ~/gitwrk/openssl.net/official/_build/include/ -I ~/gitwrk/openssl.net/official/master/include/ -o foo.o -c foo.c
```

**Comment by levitte** [comment]
> It would be good to have a testcase that creates and initializes, such as at https://github.com/openssl/openssl/pull/8377/files#diff-9ada85359453f0e7c673ab148047472dR57

That test case partly constructs the OSSL_PARAM array in runtime, mind you...

**Comment by richsalz** [comment]
When I use ```clang -pedantic``` I get errors:
```
; clang -pedantic -Wall -ansi -Iinclude -c a.c
a.c:16:7: warning: initializer for aggregate is not a compile-time constant
      [-Wc99-extensions]
    { OSSL_PARAM_int("foo", &foo),
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
include/openssl/params.h:29:5: note: expanded from macro 'OSSL_PARAM_int'
    OSSL_PARAM_DEFN((key), OSSL_PARAM_INTEGER, (addr), sizeof(int), NULL)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/openssl/params.h:25:22: note: expanded from macro 'OSSL_PARAM_DEFN'
    { (key), (type), (addr), (sz), (rsz) }
                     ^~~~~~
1 warning generated.
; 
```

Is this not a supported configuration?  So for portability only run-time local OSSL_PARAM arrays it seems.  :(

**Comment by richsalz** [comment]
Add your sample code https://github.com/openssl/openssl/issues/8471#issuecomment-472581451 into test_params PR and see if the CI's pass.

**Comment by levitte** [comment]
> Add your sample code https://github.com/openssl/openssl/issues/8471#issuecomment-472581451 into test_params PR and see if the CI's pass.

'cause we don't already know that?

https://github.com/openssl/openssl/pull/8377#issuecomment-469407545

**Comment by richsalz** [comment]
So I guess we have come around to confirming my point.  You cannot initialize an array of OSSL_PARAMS as a local variable.  Right?

**Comment by paulidale** [comment]
There is (was) an on stack params array in the api tests. It initialised using the function calls.

It isn’t possible to do an auto array that is directly initialised, only static arrays can have this and then we lose all reentrancy but can gain const.

An array can be partially initialised and the variable addresses added _post hoc_ which means no const. I did this in the tests albeit for struts not arrays of struts.

**Comment by paulidale** [comment]
> You cannot initialize an array of OSSL_PARAMS as a local variable. Right?

Yes. At least not using C’s array initialiser syntax.

**Comment by levitte** [comment]
> You cannot initialize an array of OSSL_PARAMS as a local variable. Right?

Actually, I believe you can, as long as all values are computable by the compiler.

``` C
  static int foo = 42;
  OSSL_PARAM params[] =
    { OSSL_PARAM_int("foo", &foo),
      OSSL_PARAM_END };
```

In this case, `&foo` is computable. But not terribly useful for reentrancy.

**Comment by richsalz** [comment]
Sheesh.  Perhaps I'm being needlessly pedantic.  Or perhaps you guys are being argumentative.  *But for the most common use-case* you can't declare and define a local OSSL_PARAM array at the time of declaration, i.e., using ```OSSL_PARAM x[] = ```

I guess you can close this as "yup, you're right, working as designed."

**Comment by paulidale** [comment]
Apologies, I’m keeping my answers terse since I’m one handed on a tablet for the moment.

_Working as designed_ and being _nice to use_ aren’t always the same. I’d like auto arrays to be easier than they are now. I just don’t see how yet.

**Comment by richsalz** [comment]
FWIW, in my old PR #8377 I did it by separating the name and type from binding it to the variable.

**Comment by levitte** [comment]
My last comment was more of a curiousity kinda thing than trying to be argumentative.

So yeah, works as designed.
