### ISSUE TITLE
OPENSSL_TRACE should be disabled by default

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#8472]
Subject line says it all.

Well, except that this should be mentioned somewhere in NEWS or README or something.

But, again, DISABLED BY DEFAULT.

**Comment by levitte** [comment]
Well, I guess the question to be asked is if tracing useful for application developers that link with OpenSSL.  If it is, then what does everyone think of the implication that every such developer will have to build their own OpenSSL libraries?

**Comment by richsalz** [comment]
Compared to the risk of security data being exposed, I'd say a security library should do the safe thing.  For example, I am worried about a code getting put into OpenSSL that puts key material into a TRACE statement.

By making trace ON by default, every trace statement must be evaluated for security issues and the appropriate caveats and steps taken. Not just now, but *from now on.*

**Comment by levitte** [comment]
That *is* a good point.

**Comment by mspncp** [comment]
As stated previously in https://github.com/openssl/openssl/pull/8198#issuecomment-469603448, I share Rich's point of view. IMO the tracing is a feature for developers, not normal users. And for developers it should not be a too great obstacle to compile their own instance of openssl.

**Comment by levitte** [comment]
> And for developers it should not be a too great obstacle to compile their own instance of openssl.

Well, it is a point that the previous very internal stuff was only available in custom built OpenSSL libraries, so it's not a great loss if it's disabled by default.  Yeah ok.

So, who wants to make the PR?

**Comment by kroeckx** [comment]
I just want to say that I agree that it should not be enabled by default.

**Comment by mspncp** [comment]
See  #8474
