### ISSUE TITLE
Windows: linker error with X509_get0_sm2_id

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#8484]
Linker error:
libcrypto.def : error LNK2001: unresolved external symbol X509_get0_sm2_id
libcrypto.def : error LNK2001: unresolved external symbol X509_set_sm2_id

With the following Configure options:
set options=no-cmac no-ocsp no-ui-console no-sock no-dgram no-camellia no-idea no-rc2 no-md2 no-md4 no-sm3 no-sm4 no-mdc2 no-srp no-whirlpool no-seed no-rc4 no-rc5 no-hw no-cms no-scrypt no-cast no-err no-deprecated no-engine no-dso no-crypto-mdebug no-filenames no-async no-rmd160 no-blake2 no-comp no-ts no-gost no-ct no-chacha no-dsa
set options=%options% VC-WIN32-ONECORE -DUNICODE -D_UNICODE -DWINVER=0x0601 -D_WIN32_WINNT=0x0601

Using master with the windows-makefile.tmpl fix.

**Comment by mattcaswell** [comment]
Most likely #8481 will fix it.

**Comment by matbech** [comment]
It did. Thank you.
