### ISSUE TITLE
Build issue under Windows CE 7

### ISSUE THREAD

**Issue by TechToExplore** [openssl/openssl#8486]
Environment details:
- OpenSSL version : openssl-1.0.2
- OS :  Customized Windows CE 7  ( by embedded PLC supplier - Beckhoff)
- Target board/processor type : arm
- Visual Studio 2008

**Goal** : To cross-compile the Openssl library for the arm based target type running customized Windows CE 7 on a development machine.

I could see a similar issue reported  'About Link error #4189' but closed due to insufficient information

**Description of the issue:**
Using a development machine followed the below steps to cross-compile the openssl library (using Visual studio 2008 CLI) as first step.
1. Install required tools like cygwin, perl etc.
2. Downloaded wcecompat and compiled it  https://github.com/mauricek/wcecompat
     Environment set as  below
_set LIB=C:\Program Files (x86)\Windows CE Tools\SDKs\Beckhoff_HMI_700\Lib\ARMV7;C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\lib\ARMV4I;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib
set INCLUDE=C:\Program Files (x86)\Windows CE Tools\SDKs\Beckhoff_HMI_700\Include\ARMV7
set OSVERSION=WCE700
set PLATFORM=VC-CE
set TARGETCPU=ARMV4I
set Path=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\bin\x86_arm;%Path%
set LIBPATH="C:\Program Files (x86)\Windows CE Tools\SDKs\Beckhoff_HMI_700\Lib\ARMV7";C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib;_
3. Downloaded OpenSSL, configured (debug mode set) and compiled using 
    nmake -f ms\cedll.mak

Below is the snap of build log showing error and attachment contains detailed log
_Building OpenSSL
	link /nologo /opt:ref /subsystem:windowsce,7.00 /machine:THUMB /debug /dll /out:out32dll_ARMV4I\libeay32d.dll /def:ms/LIBEAY32.def @C:\Users\grundfos\AppData\Local\Temp\nm13E.tmp
   Creating library out32dll_ARMV4I\libeay32d.lib and object out32dll_ARMV4I\libeay32d.exp
cryptlib.obj : error LNK2019: unresolved external symbol __imp___itod referenced in function CRYPTO_get_new_lockid
b_print.obj : error LNK2001: unresolved external symbol __imp___itod
md_rand.obj : error LNK2001: unresolved external symbol __imp___itod
randfile.obj : error LNK2001: unresolved external symbol __imp___itod
cryptlib.obj : error LNK2019: unresolved external symbol __imp___muld referenced in function CRYPTO_get_new_lockid
b_print.obj : error LNK2001: unresolved external symbol __imp___muld
ts_rsp_verify.obj : error LNK2001: unresolved external symbol memset
ts_verify_ctx.obj : error LNK2001: unresolved external symbol memset
srp_lib.obj : error LNK2001: unresolved external symbol memset
ui_lib.obj : error LNK2001: unresolved external symbol memset
pqueue.obj : error LNK2001: unresolved external symbol memset
wp_dgst.obj : error LNK2001: unresolved external symbol memset
ts_rsp_sign.obj : error LNK2019: unresolved external symbol memset referenced in function TS_RESP_create_response
p12_key.obj : error LNK2001: unresolved external symbol memset
comp_lib.obj : error LNK2001: unresolved external symbol memset
eng_lib.obj : error LNK2001: unresolved external symbol memset
.............................
.............................._

Ref.zip contains modified config.pl (for wcecompact.pl), cedll.mak (Openssl) and log.txt (build log showing errors)
[Ref.zip](https://github.com/openssl/openssl/files/2967582/Ref.zip)

Build steps are based on the below reference link but instead of openssl 1.0.0 version, openssl 1.0.2 version was used and hence the patch update referred in link was skipped
http://documentation.unified-automation.com/uasdkcpp/1.5.2/html/CompileOpenSSLCE.html

Guess I am missing some library dependencies. Anything related to ws2_32.lib or coredll.lib?
Also let me know if there are references to build using Visual studio 2008 IDE (defining dependencies) as well.

Any help would be appreciated.

**Comment by TechToExplore** [comment]
Further info on the environment and configuration of openssl as below

_Setting environment for using Microsoft Visual Studio 2008 x86 tools.

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC>set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE;C:\Program Files\Microsoft SDKs\Windows\v6.0A\include;

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC>set LIB=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\LIB;C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib;

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC>set LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\LIB;

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC>set Path=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\VCPackages;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin;C:\cygwin64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC>cd C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl Configure no-idea no-mdc2 no-rc5 no-asm no-ssl2 no-ssl3 VC-CE
Configuring for VC-CE
    no-asm          [option]   OPENSSL_NO_ASM
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-idea         [option]   OPENSSL_NO_IDEA (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-krb5         [krb5-flavor not specified] OPENSSL_NO_KRB5
    no-libunbound   [experimental] OPENSSL_NO_LIBUNBOUND (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-mdc2         [option]   OPENSSL_NO_MDC2 (skip dir)
    no-rc5          [option]   OPENSSL_NO_RC5 (skip dir)
    no-rfc3779      [default]  OPENSSL_NO_RFC3779 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-shared       [default]
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-ssl2         [option]   OPENSSL_NO_SSL2 (skip dir)
    no-ssl3         [option]   OPENSSL_NO_SSL3 (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS (skip dir)
    no-zlib         [default]
    no-zlib-dynamic [default]
IsMK1MF=1
CC            =cl
CFLAG         =-DOPENSSL_THREADS  -DDSO_WIN32
EX_LIBS       =
CPUID_OBJ     =mem_clr.o
BN_ASM        =bn_asm.o
EC_ASM        =
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes_core.o aes_cbc.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4_enc.o rc4_skey.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =
SHA1_OBJ_ASM  =
RMD160_OBJ_ASM=
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
MODES_OBJ     =
ENGINES_OBJ   =
PROCESSOR     =
RANLIB        =true
ARFLAGS       =
PERL          =/usr/bin/perl
THIRTY_TWO_BIT mode
BN_LLONG mode
RC4_INDEX mode
RC4_CHUNK is undefined

Configured for VC-CE.

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>
C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set OSVERSION=WCE700

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set PLATFORM=VC-CE

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set TARGETCPU=ARMV4I

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set WCECOMPAT="C:\target\Work\wcecompat-master"

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set LIB=C:\Program Files (x86)\Windows CE Tools\SDKs\Beckhoff_HMI_700\Lib\ARMV7;C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib;C:\P

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set INCLUDE=C:\Program Files (x86)\Windows CE Tools\SDKs\Beckhoff_HMI_700\Include\ARMV7;C:\Program Files (x86)\Microsoft Visual Studio

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set Path=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\ce\bin\x

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>set LIBPATH="C:\Program Files (x86)\Windows CE Tools\SDKs\Beckhoff_HMI_700\Lib\ARMV7";C:\Program Files (x86)\Microsoft Visual Studio 9

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>ms\do_ms.bat

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mkfiles.pl  1>MINFO

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mk1mf.pl no-asm VC-WIN32  1>ms\nt.mak

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mk1mf.pl dll no-asm VC-WIN32  1>ms\ntdll.mak

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>if x == x goto skipce

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mkdef.pl 32 libeay  1>ms\libeay32.def

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mkdef.pl 32 ssleay  1>ms\ssleay32.def

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>
C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>ms\do_ms.bat

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mkfiles.pl  1>MINFO

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mk1mf.pl no-asm VC-WIN32  1>ms\nt.mak

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mk1mf.pl dll no-asm VC-WIN32  1>ms\ntdll.mak

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>if xWCE700 == x goto skipce

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mk1mf.pl no-asm VC-CE  1>ms\ce.mak

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mk1mf.pl dll no-asm VC-CE  1>ms\cedll.mak

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mkdef.pl 32 libeay  1>ms\libeay32.def

C:\target\Work\openssl-1.0.2r.tar\openssl-1.0.2r>perl util\mkdef.pl 32 ssleay  1>ms\ssleay32.def_

**Comment by TechToExplore** [comment]
@mattcaswell : Any clues on the above issue since you looked into a similar issue thought you might help ( 'About Link error #4189')?

**Comment by Fighter19** [comment]
Hey there.
I had similar issues. (Plus some during compilation, but none which couldn't be easily fixed)
Are you sure you have defined WCECOMPAT in your environment?
Either way for me, the DLLs build, but they're creating error messages, even though it works fine on Windows (Desktop).

**Comment by mdeihly** [comment]
I have compiled OpenSSL successfully.
Environment details:

- OpenSSL version : OpenSSL 1.1.1
- OS : Windows CE 7 
- Target board/processor type : x86
- Visual Studio 2008

I followed this page:
https://qiita.com/souju/items/94117c024862f57459c3

**Comment by t8m** [comment]
Closing as the original issue was about 1.0.2 which is long time out of support.
