### ISSUE TITLE
Incorrectly formatted sha256-sum for sha256sum program

### ISSUE THREAD

**Issue by Millnert** [openssl/openssl#849]
The sha256 sums published on https://www.openssl.org/source/ are incorrectly formatted
e.g. https://www.openssl.org/source/openssl-1.0.2g.tar.gz.sha256.
The basic program sha256sum expects a filename at the end of the file.

It appears some release-script is messing that up.

**Comment by mattcaswell** [comment]
We don't use sha256sum, nor have we ever claimed support for it AFAIK.
We use openssl itself to create the sums. Possibly we could create the files in
a format that sha256sum expects, but I wonder whether that would break
stuff for other people who expect it in this format.
