### ISSUE TITLE
`openssl dgst -r` breaks dangerously on filenames with newlines (does not emulate coreutils behavior)

### ISSUE THREAD

**Issue by dkg** [openssl/openssl#8493]
When `openssl dgst -r` encounters a filename that has a newline in it, it can be convinced to emit an uninterpretable digest summary:

```
0 dkg@alice:/tmp/cdtemp.6F5CpY$ for x in a b 'a b' "$(printf 'a\nb')"; do echo "$x" > "$x"; done
0 dkg@alice:/tmp/cdtemp.6F5CpY$ sha256sum *
87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7  a
\911169ddaaf146aff539f58c26c489af3b892dff0fe283c1c264c65ae5aa59a2  a\nb
01186fcf04b4b447f393e552964c08c7b419c1ad7a25c342a0b631b1967d3a27  a b
0263829989b6fd954f72baaf2fc64bc2e2f01d692d4de72986ea808f6e99813f  b
0 dkg@alice:/tmp/cdtemp.6F5CpY$ openssl dgst -r *
87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7 *a
911169ddaaf146aff539f58c26c489af3b892dff0fe283c1c264c65ae5aa59a2 *a
b
01186fcf04b4b447f393e552964c08c7b419c1ad7a25c342a0b631b1967d3a27 *a b
0263829989b6fd954f72baaf2fc64bc2e2f01d692d4de72986ea808f6e99813f *b
0 dkg@alice:/tmp/cdtemp.6F5CpY$ 
```

If this is used in an automated way to create digests of files whose names are manipulable by a malicious party, that party could inject spurious digests in the output.

[coreutils describes the escaping rules in the md5sum documentation](https://www.gnu.org/software/coreutils/manual/html_node/md5sum-invocation.html#md5sum-invocation).  `openssl dgst -r` should follow suit:

>  if [the file name] contains a backslash or newline, the line is started with a backslash, and each problematic character in the file name is escaped with a backslash, making the output unambiguous even in the presence of arbitrary file names.

**Comment by agnosticdev** [comment]
Interesting.  I am also able to reproduce this too.
So, following output from `sha256sum *` would be similar for `openssl dgst -r *`:
``` 
\911169ddaaf146aff539f58c26c489af3b892dff0fe283c1c264c65ae5aa59a2  a\nb

# instead of:

911169ddaaf146aff539f58c26c489af3b892dff0fe283c1c264c65ae5aa59a2 *a
b
```

**Comment by agnosticdev** [comment]
@dkg A fix for this issue has now gone into master as of last night.
https://github.com/openssl/openssl/pull/8578

**Comment by levitte** [comment]
Ah, right, so let's close this
