### ISSUE TITLE
Missing line '.text' in 'crypto/bn/asm/ppc.pl'

### ISSUE THREAD

**Issue by lzsiga** [openssl/openssl#8495]
Hi, I think I detected a very minor bug in `crypto/bn/asm/ppc.pl`: it misses a `.text` line that results Assembler-warnings if using GNU-Assembler on AIX/Power platform (in some old AIX-versions, the default Assembler doesn't know the Altivec-instructions, so you have to use gas).
```
bn-ppc.s.before: Assembler messages:
bn-ppc.s.before: Warning: warning: symbol .bn_sqr_comba4 has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_sqr_comba8 has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_mul_comba4 has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_mul_comba8 has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_sub_words has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_add_words has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_div_words has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_sqr_words has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_mul_words has no csect
bn-ppc.s.before: Warning: warning: symbol .bn_mul_add_words has no csect
```
The suggested change:
```
--- ppc.pl.before       2019-03-15 17:36:35.000000000 +0100
+++ ppc.pl.after        2019-03-16 07:10:30.000000000 +0100
@@ -258,6 +258,7 @@
  # .text section
  
        .machine        "any"
+       .text
  
  #
  #     NOTE:   The following label name should be changed to
```
The resulting change in the generated Assembly source:
```
--- bn-ppc.s.before     2019-03-16 07:27:56.000000000 +0100
+++ bn-ppc.s.after      2019-03-16 07:50:10.000000000 +0100
@@ -94,6 +94,7 @@
  
  
  .machine      "any"
+ .csect        .text[PR],7
  
  
  
```

**Comment by levitte** [comment]
See #8496.

This issue doesn't seem to be build threatening, though.  It *is* just a warning.  But yeah, should still be fixed.

**Comment by lzsiga** [comment]
Hi, levitte, thank you for help. I see some 'failed test' messages at #8496 -- do they mean some actual problem? (I kind of doubt that: those messages seem to refer different platforms like x86 and amd64, not Power)

Note: If compiled with `gas`, linker `ld` gives error messages like this:
```
ld: 0711-593 SEVERE ERROR: Symbol .bn_sqr_comba4 (entry 2) in object crypto/bn/libcrypto-shlib-bn-ppc.o:
        The symbol refers to a csect with symbol number 0, which was not
        found. The new symbol cannot be associated with a csect and
        is being ignored.
```

**Comment by mspncp** [comment]
>  I see some 'failed test' messages at #8496 

I guess you are talking about the AppVeyor build failures: One is completely unrelated and the other one is currently being fixed in #8497. Nothing you need to worry about. 😃

**Comment by levitte** [comment]
> Note: If compiled with `gas`, linker `ld` gives error messages like this:
> ```
> ld: 0711-593 SEVERE ERROR: Symbol .bn_sqr_comba4 (entry 2) in object crypto/bn/libcrypto-shlib-bn-ppc.o:
>         The symbol refers to a csect with symbol number 0, which was not
>         found. The new symbol cannot be associated with a csect and
>         is being ignored.
> ```

Was that with or without #8496?  If with, it would seem like the fix made things worse...

**Comment by lzsiga** [comment]
No, sorry, that's the original state.
Thank you very much for your help.
