### ISSUE TITLE
SSL_connect() returns success for revoked cert in 1.1.1

### ISSUE THREAD

**Issue by macdice** [openssl/openssl#8500]
Hello,

In 1.1.1, SSL_connect() returns success (1) when the server has rejected the client's certificate as revoked.  Later attempts to read consume and report the error.  In 1.0.2, SSL_connect() would fail (0).  This change in behaviour causes intermittent breakage for PostgreSQL.  Is it intentional?

Here are the steps to reproduce.  You could probably skip steps 1-3 and use pre-built packages for this and step through with a debugger or whatever, but I found it easier to demonstrate the problem by inserting some printf-messages into PostgreSQL, YMMV.

1. Get dependencies (Debian packages shown):

```
$ sudo apt-get install make gcc git bison flex libreadline-dev libssl-dev libz-dev patch
$ git clone https://github.com/postgres/postgres.git
$ cd postgres
```

2.  Patch the PostgreSQL client library to print some debugging message:

```
$ patch -p1 --ignore-whitespace <<EOF
--- a/src/interfaces/libpq/fe-secure-openssl.c
+++ b/src/interfaces/libpq/fe-secure-openssl.c
@@ -1196,12 +1196,14 @@ open_client_SSL(PGconn *conn)
 
        ERR_clear_error();
        r = SSL_connect(conn->ssl);
+       fprintf(stderr, "SSL_connect returned %d\n", r);
        if (r <= 0)
        {
                int                     err = SSL_get_error(conn->ssl, r);
                unsigned long ecode;
 
+               fprintf(stderr, "SSL_get_error returned %d\n", err);
                ecode = ERR_get_error();
                switch (err)
                {
                        case SSL_ERROR_WANT_READ:

EOF
```

3.  Build:

```
$ ./configure --prefix=`pwd`/install --enable-debug --enable-cassert --with-openssl
$ make && make install && make check
```

4.  Set up a PostgreSQL server with SSL support:

```
$ ./install/bin/initdb -D pgdata
$ cp src/test/ssl/ssl/* pgdata/
$ chmod 600 pgdata/*.key
$ cat <<EOF > pgdata/postgresql.conf
ssl=on
ssl_ca_file='root+client_ca.crt'
ssl_cert_file='server-cn-only.crt'
ssl_key_file='server-cn-only.key'
ssl_crl_file='root+client.crl'
EOF
$ ./install/bin/postgres -D pgdata
```

... that'll run until you stop it with ^C.

5.  In another shell, cd to that postgres dir and try to connect with a revoked client certificate:

```
$ ./install/bin/psql "host=localhost dbname=postgres user=postgres sslcert=pgdata/client-revoked.crt sslkey=pgdata/client-revoked.key sslmode=require"
```
It'll fail, but the way it fails varies.  If you built against 1.0.2 (I tested on a CentOS 7.6 system with openssl-libs-1.0.2k-16.el7.x86_64) you see:

```
SSL_connect returned -1
SSL_get_error returned 2
SSL_connect returned -1
SSL_get_error returned 2
SSL_connect returned 0
SSL_get_error returned 1
psql: SSL error: sslv3 alert certificate revoked
```

If you built against 1.1.1 (I tested on a Debian Buster system with libssl 1.1.1b-1, and on a FreeBSD 13-CURRENT system with 1.1.1b-freebsd) you see:

```
SSL_connect returned -1
SSL_get_error returned 2
SSL_connect returned -1
SSL_get_error returned 2
SSL_connect returned 1
psql: SSL error: sslv3 alert certificate revoked
```

Although psql produced the same error message to the user, it did that in a different code path, after SSL_connect() returned 1 and then it sent some data and tried to read the response and got an error.

But *sometimes* on a Linux system with unlucky enough scheduling, you see:

```
SSL_connect returned 1
psql: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
could not send startup packet: Connection reset by peer
```

That's because the server managed to close before psql got around to sending some data (which it thought it could do because SSL_connect() apparently succeeded), so it got ECONNRESET and died horribly.  It looks like we could fix that by attempting to read to see if that produces errors after such a failure, but I wanted to reach out and see if that was actually a bug, intentional change or misunderstanding on our part first.  From where I'm sitting it seems pretty fishy that SSL_connect() would return 1 in this case.

Thanks!

pgsql-hackers mailing list where this has been discussed:

https://www.postgresql.org/message-id/flat/CAEepm%3D2n6Nv%2B5tFfe8YnkUm1fXgvxR0Mm1FoD%2BQKG-vLNGLyKg%40mail.gmail.com

**Comment by kroeckx** [comment]
Note that in TLS 1.3, client authentication happens after
the handshake.

**Comment by macdice** [comment]
Huh, I see, thanks for the clue.  Seems like we might need to review our connection logic then.  https://wiki.openssl.org/index.php/TLS1.3 describes some of this.  Perhaps we need to figure out how to wait for a session, or, since the first thing we do is write application data, handle ECONNRESET by trying to read.  I wonder if the former is problematic because "it could be sometime later (or not at all)" and the latter is problematic because at least one operating systems we care about doesn't allow you to read data from a socket after a write has failed.

**Comment by mattcaswell** [comment]
> Note that in TLS 1.3, client authentication happens after the handshake.

That's kind of true but isn't the full story. It is true that TLS1.3 introduces post-handshake client authentication. However it also still supports in-handshake client authentication - but the server doesn't verify the certificate until after the handshake has finished from the client's perspective. This is what a TLS1.2 hanshake looks like (from RFC5246):

````
Client                                               Server

      ClientHello                  -------->
                                                      ServerHello
                                                     Certificate*
                                               ServerKeyExchange*
                                              CertificateRequest*
                                   <--------      ServerHelloDone
      Certificate*
      ClientKeyExchange
      CertificateVerify*
      [ChangeCipherSpec]
      Finished                     -------->
                                               [ChangeCipherSpec]
                                   <--------             Finished
      Application Data             <------->     Application Data
````

And this is the equivalent in TLS1.3 (from RFC 8446):

````
       Client                                           Server

Key  ^ ClientHello
Exch | + key_share*
     | + signature_algorithms*
     | + psk_key_exchange_modes*
     v + pre_shared_key*       -------->
                                                  ServerHello  ^ Key
                                                 + key_share*  | Exch
                                            + pre_shared_key*  v
                                        {EncryptedExtensions}  ^  Server
                                        {CertificateRequest*}  v  Params
                                               {Certificate*}  ^
                                         {CertificateVerify*}  | Auth
                                                   {Finished}  v
                               <--------  [Application Data*]
     ^ {Certificate*}
Auth | {CertificateVerify*}
     v {Finished}              -------->
       [Application Data]      <------->  [Application Data]
````

Notice that in TLSv1.2 the client is not free to start sending application data until after it has received the "Finished" message from the server. This occurs after the server has verified the client cert and therefore if there is a problem with that cert then the handshake will abort (and so SSL_connect will not return successfully).

In TLSv1.3 things are different. The server sends its "Finished" message earlier. The client sends its certificate, certificate verify and finished message as the last thing in the handshake and then is immediately free to start sending application data. This is the point at which SSL_connect returns success. However at this point, even though from the client perspective the handshake has finished, from the server perspective it hasn't. That doesn't happen until it receives the client's last flight of messages - and it isn't until that occurs that the client certificate is verified. If it spots a problem then the server will abort at that point - which from the client's perspective occurs *after* the handshake has already finished.

**Comment by macdice** [comment]
Thanks for the detailed explanation.

So, it looks like there is no way for the client to wait for the server to have verified the client's cert, right?  In the case of application-level protocols like ours where the client sends application data first, it simply has to go ahead and do that, and then if it gets an OS-level error like EPIPE or ECONNRESET because the server has already closed the socket*, it then has to try to read so that it can find out the error code we want to report to users ("sslv3 alert certificate revoked"), right?

*I suspect that ECONNRESET/EPIPE on initial sendto() of client data send can only happen with client and server on the same machine and only on some OSes, due to details of TCP implementation, since a remote machine would reply with a TCP RST which causes some *later* sendto() to fail.  Maybe not many people care about this localhost case since TLS to localhost is not terribly useful, but this problem showed up as random weird behaviour on our build/test farm machine, so I need to fix it somehow.  Presumably someone with a multi-sendto() initial application message could also see the problem with a remote server.  BTW I suspect that approach to handling the socket-closed error might not work on Windows, because Windows doesn't allow you to read data from a socket which has already failed to write; if we need to do it this way, on Windows we may not ever be able to retrieve that error message (but that seems to be a flaw in that TCP stack that we might just have to live with unless someone can figure out how to change its behaviour; it bites us in other ways too).

**Comment by kroeckx** [comment]
The RFC requires us the close the connection on send or receive of
an error alert. So if the server rejects the client certificate,
if should sent the alert and close the connection.

If the client sends data to the server, the TCP stack will reply
with a reset.

I assume this is a test to see that you get the proper error
message? I'm afraid that TLS 1.3 has made it difficult to properly
show that error message, because it would require an extra round
trip before you can send application data.

You can argue that the client should not attempt to use an expired
certificate.

**Comment by macdice** [comment]
> I assume this is a test to see that you get the proper error message? I'm afraid that TLS 1.3 has made it difficult to properly show that error message, because it would require an extra round trip before you can send application data. You can argue that the client should not attempt to use an expired certificate.

Correct.  We want cert verification failure to be reported distinctly from our general "server closed the connection unexpectedly" message that tells you your network is busted or that-isn't-actually-a-PostgreSQL server or whatever.

**Comment by macdice** [comment]
Thanks both for your help.  I think we know what we need to do now: handle reset connection by trying to retrieve the server's final message (for the benefit of users on OSes where that actually works).  OpenSSL is obviously working as designed, so I'll close this now.
