### ISSUE TITLE
Can we build openssl for architectures like x86 and ARM using Cmake or autotools

### ISSUE THREAD

**Issue by deekshith-elear** [openssl/openssl#8511]
HI,
I am using cmake as my build system. Is it possible to build openssl for android for architectures x86 and ARM using Cmake? If possible what are the list of flags we have to use.

**Comment by levitte** [comment]
No it's not possible, sorry.  We've had to craft our own because of lack of support for either on those systems on some platforms.

I suggest reading INSTALL, it has an exhaustive list of configuration command line arguments for you to use.
