### ISSUE TITLE
i2d_X509_REQ() -> d2i_X509_REQ() = asn1 encoding routines:c2i_ASN1_OBJECT:invalid object encoding:a_object.c:287

### ISSUE THREAD

**Issue by minfrin** [openssl/openssl#8514]
When an attempt is made to take a partially built X509_REQ structure, serialise to to der form with i2d_X509_REQ() as follows:

https://source.redwax.eu/projects/RS/repos/mod_spkac/browse/mod_spkac.c#886

Then you try to deserialise the der back to the structure using d2i_X509_REQ() as follows:

https://source.redwax.eu/projects/RS/repos/mod_ca/browse/mod_ca_ldap.c#358

The deserialisation attempt fails as follows:

139903756527504:error:0D0C40D8:asn1 encoding routines:c2i_ASN1_OBJECT:invalid object encoding:a_object.c:287:
139903756527504:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:720:Field=algorithm, Type=X509_ALGOR
139903756527504:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:720:Field=sig_alg, Type=X509_REQ

This worked in RHEL6 (openssl-1.0.1e-42), but has regressed in RHEL7 (openssl-1.0.2k-16), and also does not work in openssl v1.1.1a.

In our case the CSR is not yet signed, as it is currently being built, and it appears at some point openssl introduced a parsing error when encountering unsigned CSRs.

How can we get this fixed?

**Comment by vdukhovni** [comment]
There is no bug.  The structure is missing a mandatory component.  OpenSSL is working as expected. If earlier versions tolerated malformed CSRs, that was an implementation artefact, not expected behaviour.
I will let this issue stay open a day or two, but then close it barring new information.

**Comment by vdukhovni** [comment]
For the record the CSR structure now embeds the CRI and signature algorithm, so these simply cannot be omitted:
```
struct X509_req_st {
    X509_REQ_INFO req_info;     /* signed certificate request data */
    X509_ALGOR sig_alg;         /* signature algorithm */
    ASN1_BIT_STRING *signature; /* signature */
    CRYPTO_REF_COUNT references;
    CRYPTO_RWLOCK *lock;
};
```

**Comment by minfrin** [comment]
Looking deeper at this, it appears the regression is in i2d_X509_REQ() at the encoding step.

This is a partially built CSR from before the regression:

`[root@monica ~]# openssl asn1parse -inform DER < old.bin 
    0:d=0  hl=4 l= 509 cons: SEQUENCE          
    4:d=1  hl=4 l= 497 cons: SEQUENCE          
    8:d=2  hl=2 l=   0 prim: INTEGER           :00
   10:d=2  hl=2 l=  67 cons: SEQUENCE          
   12:d=3  hl=2 l=  14 cons: SET               
   14:d=4  hl=2 l=  12 cons: SEQUENCE          
   16:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   21:d=5  hl=2 l=   5 prim: PRINTABLESTRING   :Test1
   28:d=3  hl=2 l=  49 cons: SET               
   30:d=4  hl=2 l=  47 cons: SEQUENCE          
   32:d=5  hl=2 l=   3 prim: OBJECT            :serialNumber
   37:d=5  hl=2 l=  40 prim: PRINTABLESTRING   :2c0fc7471e7f522887f3f9a7bf6835815772de33
   79:d=2  hl=4 l= 290 cons: SEQUENCE          
   83:d=3  hl=2 l=  13 cons: SEQUENCE          
   85:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
   96:d=4  hl=2 l=   0 prim: NULL              
   98:d=3  hl=4 l= 271 prim: BIT STRING        
  373:d=2  hl=3 l= 129 cons: cont [ 0 ]        
  376:d=3  hl=2 l=  42 cons: SEQUENCE          
  378:d=4  hl=2 l=   9 prim: OBJECT            :challengePassword
  389:d=4  hl=2 l=  29 cons: SET               
  391:d=5  hl=2 l=  27 prim: IA5STRING         :uqg4w5n5yeehukieohuvl009i0
  420:d=3  hl=2 l=  83 cons: SEQUENCE          
  422:d=4  hl=2 l=   9 prim: OBJECT            :Extension Request
  433:d=4  hl=2 l=  70 cons: SET               
  435:d=5  hl=2 l=  68 cons: SEQUENCE          
  437:d=6  hl=2 l=  66 cons: SEQUENCE          
  439:d=7  hl=2 l=   3 prim: OBJECT            :X509v3 Subject Alternative Name
  444:d=7  hl=2 l=  59 prim: OCTET STRING      [HEX DUMP]:303981373263306663373437316537663532323838376633663961376266363833353831353737326465333340756B2E736173686B65792E6F7267
  505:d=1  hl=2 l=   3 cons: SEQUENCE          
  507:d=2  hl=2 l=   1 prim: OBJECT            :itu-t
  510:d=1  hl=2 l=   1 prim: BIT STRING        
`

This is the partially build CSR after the regression:

`[root@emma ~]# openssl asn1parse -inform DER < req.bin 
    0:d=0  hl=4 l= 509 cons: SEQUENCE          
    4:d=1  hl=4 l= 498 cons: SEQUENCE          
    8:d=2  hl=2 l=   1 prim: INTEGER           :00
   11:d=2  hl=2 l=  67 cons: SEQUENCE          
   13:d=3  hl=2 l=  14 cons: SET               
   15:d=4  hl=2 l=  12 cons: SEQUENCE          
   17:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   22:d=5  hl=2 l=   5 prim: UTF8STRING        :Test1
   29:d=3  hl=2 l=  49 cons: SET               
   31:d=4  hl=2 l=  47 cons: SEQUENCE          
   33:d=5  hl=2 l=   3 prim: OBJECT            :serialNumber
   38:d=5  hl=2 l=  40 prim: PRINTABLESTRING   :354616bb0358f9474f1e84af5550567f8b6c4d5b
   80:d=2  hl=4 l= 290 cons: SEQUENCE          
   84:d=3  hl=2 l=  13 cons: SEQUENCE          
   86:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
   97:d=4  hl=2 l=   0 prim: NULL              
   99:d=3  hl=4 l= 271 prim: BIT STRING        
  374:d=2  hl=3 l= 129 cons: cont [ 0 ]        
  377:d=3  hl=2 l=  42 cons: SEQUENCE          
  379:d=4  hl=2 l=   9 prim: OBJECT            :challengePassword
  390:d=4  hl=2 l=  29 cons: SET               
  392:d=5  hl=2 l=  27 prim: IA5STRING         :dfwrrdq4uhec96yj23io8soav0
  421:d=3  hl=2 l=  83 cons: SEQUENCE          
  423:d=4  hl=2 l=   9 prim: OBJECT            :Extension Request
  434:d=4  hl=2 l=  70 cons: SET               
  436:d=5  hl=2 l=  68 cons: SEQUENCE          
  438:d=6  hl=2 l=  66 cons: SEQUENCE          
  440:d=7  hl=2 l=   3 prim: OBJECT            :X509v3 Subject Alternative Name
  445:d=7  hl=2 l=  59 prim: OCTET STRING      [HEX DUMP]:303981373335343631366262303335386639343734663165383461663535353035363766386236633464356240756B2E736173686B65792E6F7267
  506:d=1  hl=2 l=   2 cons: SEQUENCE          
  508:d=2  hl=2 l=   0 prim: OBJECT            :BAD OBJECT
  510:d=1  hl=2 l=   1 prim: BIT STRING        
`

The difference is that this in the first object:

`
  507:d=2  hl=2 l=   1 prim: OBJECT            :itu-t
`

has become this in the second object:

`
  508:d=2  hl=2 l=   0 prim: OBJECT            :BAD OBJECT
`

Is there an API call or some way that I can set the signature above to an encodable empty value as opposed to a corrupt value?

**Comment by vdukhovni** [comment]
Relevant commits:

https://github.com/openssl/openssl/commit/38a503fb8adaad331b8a67aaa9eb2fa915113ed0 (1.0.1i)
https://github.com/openssl/openssl/commit/ff4cfc4c588c41d5e8d2d530231bc36cbc525add (1.0.2-beta2)

With these ASN.1 encoding of NID_undef generates no output (dubious) as opposed to previous "0.0" (also dubious). There is no object id for NID_undef, and i2d_ASN1_OBJECT should perhaps simply fail when encountering objects that have no encoding.

**Comment by vdukhovni** [comment]
@minfrin The only functions I known of that set the signature fields of an X509_REQ are the functions that sign the request.  I am not aware of any direct write accessors for the signature algorithm, parameters and value.

**Comment by vdukhovni** [comment]
Closing in favour of #8553
