### ISSUE TITLE
Commands 'req', 'x509' and 'ca': missing documentation for option '-sigopt'

### ISSUE THREAD

**Issue by lzsiga** [openssl/openssl#8516]
Commands `req`, `x509` and `ca`: missing documentation for option '-sigopt'

Hi, I think I found a minor deficiency in manuals of `req(1)`, `x509(1)` and `ca(1)`:
they don't contain the description of option `-sigopt`;
I think it could be simply copied from `dgst(1)` manual:

```
=item B<-sigopt nm:v>

Pass options to the signature algorithm during sign or verify operations.
Names and values of these options are algorithm-specific.
```

**Comment by lzsiga** [comment]
I see it has been fixed. Thank you.

**Comment by paulidale** [comment]
Thanks for reporting it.
