### ISSUE TITLE
customizing android toolchain options in Configure

### ISSUE THREAD

**Issue by deekshith-elear** [openssl/openssl#8522]
Hi,
I have installed NDK tool chain in specific location like```/opt/android/toolchain_armeabi_v7a_19/...``` how can I use this tool chains insted of ```NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/``` in Configure

**Comment by levitte** [comment]
You can find the information you need in [`NOTES.ANDROID`] (https://github.com/openssl/openssl/blob/master/NOTES.ANDROID)
