### ISSUE TITLE
OpenSSL 1.1.1b breaks OPENSSL_config(NULL)

### ISSUE THREAD

**Issue by pkl97** [openssl/openssl#8528]
The test program below works fine with OpenSSL 1.1.1a but prints this error when 1.1.1b is used:
    ```
error:02001015:system library:fopen:Is a directory
    ```

The culprit is the call OPENSSL_config(NULL). If it is commented out, then the program also works against 1.1.1b.

The platform is Windows 7, VS 2017 15.9.9 x64.

```
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/conf.h>
#include <iostream>

int main()
{
    OPENSSL_config(NULL); // works in OpenSSL 1.1.1a, fails in 1.1.1b
    SSL_CTX* ctx=SSL_CTX_new(TLS_client_method());
    if (ctx == nullptr)
        std::cout << ERR_error_string(ERR_get_error(), 0) << std::endl; // prints error:02001015:system library:fopen:Is a directory
    return 0;
}
```

Regards, Peter.

**Comment by levitte** [comment]
So what's happened in df1f538f28c10f2954757164b17781040d2355ef is that the flag `CONF_MFLAGS_IGNORE_MISSING_FILE` was dropped.  That's probably the actual cause for what you're seeing, and I assume it's the same if you, for example, `OPENSSL_config("foo")`, i.e. the argument doesn't really matter, what matters is that it can't find `openssl.cnf` where it expects to do so.  That means that the error is actually appropriate (and a lack thereof was a bug in 1.1.1a).

**Comment by pkl97** [comment]
Sorry, but I have to disagree. `OPENSSL_config()` is part of the OpenSSL interface since 0.9.7. Its [manpage](https://www.openssl.org/docs/man1.0.2/man3/OPENSSL_config.html) states _"Errors are silently ignored"_. This always included a non existent configuration file. Lots of software out there relies on this behavior. So "fixing" this bug actually breaks existing software. In my case it is a third party library that calls `OPENSSL_config()` internally without me being able to influence this call in any way.

**Comment by levitte** [comment]
I was wrong, the `CONF_MFLAGS_IGNORE_MISSING_FILE` is still there...

**Comment by levitte** [comment]
...  or oh!

@pkl97, you're right, this does look like an omission.  Previously, there was an internal override of the settings flags that `OPENSSL_config()` creates, which wasn't the best...  so that was change to only set default CONF MFLAGS if no settings was passed down...  but since `OPENSSL_config()` does create one, even though with no flags, no flags are set.

The implication is that the following diff should be applied.  Would you be willing to test it?

``` diff
diff --git a/crypto/conf/conf_sap.c b/crypto/conf/conf_sap.c
index 38621db3c8..3994a86395 100644
--- a/crypto/conf/conf_sap.c
+++ b/crypto/conf/conf_sap.c
@@ -35,6 +35,7 @@ void OPENSSL_config(const char *appname)
     memset(&settings, 0, sizeof(settings));
     if (appname != NULL)
         settings.appname = strdup(appname);
+    settings.flags = DEFAULT_CONF_MFLAGS;
     OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, &settings);
 }
 #endif
```

**Comment by pkl97** [comment]
@levitte: Great, your patch fixes the problem (tested under Windows x86/x64)!

Regards, Peter.

**Comment by levitte** [comment]
#8533

**Comment by cotequeiroz** [comment]
@levitte 
I think this needs to be reworked, as a call to `CONF_modules_load_file` with `CONF_MFLAGS_IGNORE_MISSING_FILE` should not fail either.  Note that the flag is still defined, so it was not [entirely] dropped as stated above.  `wget` makes such a call here http://git.savannah.gnu.org/cgit/wget.git/tree/src/openssl.c#n202, so it fails to initialize SSL if `openssl.cnf` is not found:
```
$ wget https://google.com
--2019-04-22 10:10:16--  https://google.com/
Disabling SSL due to encountered errors.
```
If you want me to tackle this, let me know and I'll do it as soon as I am able.

**Comment by cotequeiroz** [comment]
Never mind.  It does work as is.  Sorry about the noise.
