### ISSUE TITLE
HKDF doesn't allow zero length key

### ISSUE THREAD

**Issue by orignal** [openssl/openssl#8531]
version 1.1.1
I try to run following code

EVP_PKEY_CTX * pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_HKDF, NULL);
EVP_PKEY_derive_init (pctx);
EVP_PKEY_CTX_set_hkdf_md (pctx, EVP_sha256());   
EVP_PKEY_CTX_set1_hkdf_salt (pctx, salt, 32);
EVP_PKEY_CTX_set1_hkdf_key (pctx, NULL, 0);  // returns error
EVP_PKEY_derive (pctx, out, &outLen);

If I don't call EVP_PKEY_CTX_set1_hkdf_key, than EVP_PKEY_derive fails.
Some crypto algorithms (for example, Noise) require HKDF with zero length key by design.
As workaround I use 

EVP_PKEY_CTX_hkdf_mode (pctx, EVP_PKEY_HKDEF_MODE_EXPAND_ONLY);
uint8_t tempKey[32]; unsigned int len;
HMAC(EVP_sha256(), salt, 32, NULL, 0, tempKey, &len);
EVP_PKEY_CTX_set1_hkdf_key (pctx, tempKey, len);
 
I believe openssl should do it inside the library.

**Comment by paulidale** [comment]
@davidmakepeace will this be an issue in 3.0.0 and the new API?

**Comment by levitte** [comment]
*Is* this an issue in 3.0.0?

**Comment by paulidale** [comment]
A quick look over the code and it seems like it wouldn't be. I've not run the test to be certain.

**Comment by orignal** [comment]
> A quick look over the code and it seems like it wouldn't be. I've not run the test to be certain.

Do you mean zero length key should work already or it's not supposed to by design? In last case how is it supposed to be used in algorithms requiring it?

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing.
