### ISSUE TITLE
When I use the clang compiler to compile the openssl (version: 1.1.1a) with “linux-aarch64”, openssl will report the compilation failure. 

### ISSUE THREAD

**Issue by xiongyyy** [openssl/openssl#8545]
Hi here,
When I use the clang compiler to compile the openssl (version: 1.1.1a) with “linux-aarch64”, openssl will report the compilation failure. The reason is: 
Openssl reported an error in the crypto/arm_arch.h file
error "unsupported ARM architecture"

am I missing any configuration? Or openssl does not support assembly of the arm platform?

My configuration：
export CC=clang
export CROSS_COMPILE=XXX
export AR=llvm-ar
./Configure linux-aarch64
make

I am very grateful for your reply.

**Comment by mattcaswell** [comment]
Likely this is an environmental issue in your cross-compile setup. I am able to successfully cross-compile for that target using:
````
perl Configure --cross-compile-prefix=aarch64-linux-gnu- linux-aarch64
````

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
