### ISSUE TITLE
Solaris config targets failing with GNU ld

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#8547]
Ref: https://mta.openssl.org/pipermail/openssl-users/2019-March/010147.html

It seems that we're unprepared for GNU ld being used on Solaris.  All our solaris config targets derive most of their ld flags from the `solaris-common` template:

``` perl
        shared_ldflag    => "-Wl,-Bsymbolic",
        shared_defflag   => "-Wl,-M,",
        shared_sonameflag=> "-Wl,-h,",
```

With [Solaris ld](https://docs.oracle.com/cd/E26502_01/html/E29030/ld-1.html), `-M` does what we think it does:

> -M *mapfile*
> 
>    Reads *mapfile* as a text file of directives to ld. 

With [GNU ld](https://sourceware.org/binutils/docs/ld/Options.html#Options), it has a different meaning:

> -M
> --print-map
>
>    Print a link map to the standard output. A link map provides information about the link, including the following: 
>    ...

The `shared` attributes in our solaris config targets should be moved to `Configurations/shared_info.pl` and be made to use the mechanism that detects if the linker that's used is GNU ld or not.

**Comment by richsalz** [comment]
Is this mix and matching toolchain?  Like Solaris CC with GNU ld?  I don't think the project should support that.  If you want to support Solaris or GCC toolchains, that seems more reasonable.

**Comment by levitte** [comment]
It's about allowing builds with GNU cc to use GNU ld. Our current config targets assume Sun ld at all times, which is absolutely fine with a GNU cc that's been built to use that. However, if GNU binutils is installed when GNU cc is being built, it will use GNU ld, if I understand correctly. So we fail on Solaris when it's done with a full GNU toolchain. That's what this PR tries to fix.
