### ISSUE TITLE
32/64 Build Notes.Win Question

### ISSUE THREAD

**Issue by hlsantos** [openssl/openssl#8551]
We are porting our Win32 platform to Win64 (x64) and we are going to take the opportunity to also move towards the LTS OpenSSL v1.1.x version.  

I can see the Notes.WIN information is still evolving.  So maybe the notes can be updated to assists folks with similar compilation scenarios.

We are going to need to build both 32 bit and 64 bit *.DLL/LIB files for the 64 bit RPC Server side and the 32 bit RPC client side of our platform.  Given you have a setup perl to do:

Perl Config VC-WIN64A 
Perl Config VC-WIN32

It would appear we will need to do this in two separate folders?  Correct?

**Comment by levitte** [comment]
Yes.  However, you can have the two builds share the same source, by building outside of the source tree:

```
rem Assume the openss source is in subdirectory "openssl"

mkdir openssl-32
cd openssl-32
perl ..\openssl\Configure VC-WIN32
nmake
cd ..


mkdir openssl-64
cd openssl-64
perl ..\openssl\Configure VC-WIN64A
nmake
cd ..
```

**Comment by hlsantos** [comment]
Thanks you!  I will try this! :)   Good note to add for 32/64 bit build environments.

**Comment by hlsantos** [comment]
Levitte, 

I did the 32/64 compile and began to recompile/edit some internal ssl tools,  

I found the output for SSLeay_version(SSLEAY_PLATFORM) for a 32 bit compile was VC-WIN64A

At first I thought it was related source include folder.  I added two folders to my INCLUDE statement

     openssl-1_1_1-stable\include
     openssl-1_1_1-stable\x32\include

yet, it still output VC_WIN64A

But I found it was related to the library.   Here is my test program used the non-static libs.

``// File: C:\Files\openssl\openssl-1_1_1-stable\wctest\ListSSLversion.cpp

#include <stdio.h>
#include <windows.h>

#include <openssl/ssl.h>
#include <openssl/crypto.h>

#pragma comment(lib,"libssl.lib")
#pragma comment(lib,"libcrypto.lib")
//#pragma comment(lib,"libssl_static.lib")
//#pragma comment(lib,"libcrypto_static.lib")

void main(char argc, char *argv[])
{
#ifdef _WIN64
   printf("** 64 bit **\n");
#else
   printf("** 32 bit **\n");
#endif

   if (SSLeay() != SSLEAY_VERSION_NUMBER) {
      printf("! SSL DLL Version Mismatch\n");
      printf("! Expected: %08X\n",SSLEAY_VERSION_NUMBER);
      printf("! Loaded  : %08X\n",SSLeay());
   }

   printf("- SSLEAY_VERSION_NUMBER : %s\n",SSLeay_version(SSLEAY_VERSION_NUMBER));
   printf("- SSLEAY_VERSION  : %s\n",SSLeay_version(SSLEAY_VERSION));
   printf("- SSLEAY_BUILT_ON : %s\n",SSLeay_version(SSLEAY_BUILT_ON));
   printf("- SSLEAY_PLATFORM : %s\n",SSLeay_version(SSLEAY_PLATFORM));
}
`
You will get VC-WIN64A when using the non-static library.   Switch the the static lib by changing the pragmas and it works to output VC-WIN32

Keep in mind and this was a clean 32 bit only build. I still got the VC-WIN64A,

**Comment by levitte** [comment]
Closing this in favor of #8556, which goes into the remaining details
