### ISSUE TITLE
Test 03-test_params_api failing on multiple platforms.

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#8570]
The param API tests are failing with the following errors (cut down list shown here)

../../test/recipes/03-test_params_api.t ............... 
1..1
    # Subtest: ../../test/params_api_test
    1..12
        # Subtest: test_param_int
        1..6
        # ERROR: (memory) 'buf == cmp' failed @ ../test/params_api_test.c:92
        # --- buf
        # +++ cmp
        # 0000:-00000000
        # 0000:+3bbf2738
        #       ^^^^^^^^
        # 
        not ok 1 - iteration 1
        # ERROR: (memory) 'buf == cmp' failed @ ../test/params_api_test.c:92
        # --- buf
        # +++ cmp
        # 0000:-00000000
        # 0000:+2248269f
        #       ^^^^^^^^
        # 
        not ok 2 - iteration 2

--------------------------------------------------------------
In the configuration data shown below this looks suspicious.
    lib_cflags => "",
    lib_cppflags => "-DB_ENDIAN",

Here are some configurations that are affected by this...
../Configure shared no-asm aix-cc
../Configure no-asm -DOPENSSL_NO_ASYNC aix64-cc
../Configure shared no-engine no-asm hpux-ia64-cc
../Configure shared linux32-s390x
./Configure shared linux64-s390x
./Configure shared -m32 -lrt solaris-sparcv9-cc

--------------------------------------------------------------
The configuration below is for:
>perl ../Configure shared no-asm aix-cc

Perl information:

    perl
    5.24.0 for aix-64all

Enabled features:

    aria
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    crmf
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    padlockeng
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    ktls                    [default]   OPENSSL_NO_KTLS
    afalgeng                [not-linux] 
    asan                    [default]   OPENSSL_NO_ASAN
    asm                     [option]    OPENSSL_NO_ASM
    buildtest-c++           [default]   
    crypto-mdebug           [default]   OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]   OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]   OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]   OPENSSL_NO_EGD
    external-tests          [default]   OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]   OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]   OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]   OPENSSL_NO_HEARTBEATS
    md2                     [default]   OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]   OPENSSL_NO_MSAN
    rc5                     [default]   OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]   OPENSSL_NO_SCTP
    ssl-trace               [default]   OPENSSL_NO_SSL_TRACE
    trace                   [default]   OPENSSL_NO_TRACE
    ubsan                   [default]   OPENSSL_NO_UBSAN
    unit-test               [default]   OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]   OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]   
    zlib-dynamic            [default]   
    ssl3                    [default]   OPENSSL_NO_SSL3
    ssl3-method             [default]   OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar -X32",
    ARFLAGS => "r",
    CC => "cc",
    CFLAGS => "-O",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib -X32",
    RC => "windres",
    aes_asm_src => "aes_core.c aes_cbc.c",
    aes_obj => "aes_core.o aes_cbc.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "bn_asm.c",
    bn_obj => "bn_asm.o",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-q32 -qmaxmem=16384 -qro -qroconst -qthreaded",
    chacha_asm_src => "chacha_enc.c",
    chacha_obj => "chacha_enc.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o",
    cppflags => "-D_THREAD_SAFE",
    cpuid_asm_src => "mem_clr.c",
    cpuid_obj => "mem_clr.o",
    defines => [  ],
    des_asm_src => "des_enc.c fcrypt_b.c",
    des_obj => "des_enc.o fcrypt_b.o",
    disable => [  ],
    dso_scheme => "dlfcn",
    ec_asm_src => "",
    ec_obj => "",
    enable => [  ],
    ex_libs => "-lpthreads",
    includes => [  ],
    keccak1600_asm_src => "keccak1600.c",
    keccak1600_obj => "keccak1600.o",
    lflags => "-Wl,-bsvr4",
    lib_cflags => "",
    lib_cppflags => "-DB_ENDIAN",
    lib_defines => [  ],
    md5_asm_src => "",
    md5_obj => "",
    modes_asm_src => "",
    modes_obj => "",
    module_cflags => "-qpic",
    module_cxxflags => "",
    module_ldflags => "-Wl,-G,-bsymbolic,-bexpall",
    padlock_asm_src => "",
    padlock_obj => "",
    perl_platform => "AIX",
    perlasm_scheme => "aix32",
    poly1305_asm_src => "",
    poly1305_obj => "",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    shared_cflag => "-qpic",
    shared_defflag => "-Wl,-bE:",
    shared_defines => [  ],
    shared_ldflag => "-Wl,-G,-bsymbolic,-bnoentry",
    shared_rcflag => "",
    shared_target => "aix",
    sys_id => "AIX",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPPFLAGS = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LDFLAGS = 
    LDLIBS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar -X32
    ARFLAGS         = r
    CC              = cc
    CFLAGS          = -O
    CPPDEFINES      = OPENSSL_NO_ASYNC
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = perl
    RANLIB          = ranlib -X32
    RC              = windres

**Comment by paulidale** [comment]
It looks like a missing `-D_BENDIAN` in the configurations.

**Comment by slontis** [comment]
This still seems to be broken in the CI loop.

**Comment by slontis** [comment]
This is being addressed in
https://github.com/openssl/openssl/pull/8629

**Comment by slontis** [comment]
Another platform specific problem was addressed by https://github.com/openssl/openssl/pull/8696
So this should be good now.
