### ISSUE TITLE
Error while using libcrypto.so

### ISSUE THREAD

**Issue by deekshith-elear** [openssl/openssl#8573]
Hi,
Getting error while using libcrypto.so in my project and showing error was ```libcrypto.so: cannot find CRYPTO_num_locks, CRYPTO_set_locking_callback, CRYPTO_set_id_callback, ERR_free_strings,...``` and compiled openssl using command ```./Configure linux-x86_64```
Can any one help me to solve this error.

**Comment by mlindner** [comment]
More information is needed. For example: full errors, how you're linking libcrypto to your project, where you installed OpenSSL to, etc.

**Comment by levitte** [comment]
I suspect the project was built for OpenSSL 1.0.2, and an attempt was made to link it with OpenSSL 1.1.0 or newer, un modified. Correct, @deekshith-elear?

**Comment by deekshith-elear** [comment]
No, project was built for 1.1.0 and I'm thinking that above mentioned symbols for 1.1.0 openssl and it is not built for 1.1.0 and How can I build openssl for 1.1.0 version

**Comment by levitte** [comment]
`CRYPTO_num_locks`, `CRYPTO_set_locking_callback`, `CRYPTO_set_id_callback`, `ERR_free_strings` do not exist in 1.1.0 and newer. They do exist in 1.0.2. If you want to build with OpenSSL 1.1.0 or newer, you must not call those functions

**Comment by deekshith-elear** [comment]
can I configure openssl for 1.0.2?  if  yes, then where i have to mention `-DOPENSSL_API_COMPAT=0x10100000L` during `./Configure` or `make`

**Comment by mattcaswell** [comment]
If you want 1.0.2 then you need to download the 1.0.2 source distribution instead. There is no way to get 1.1.1a to generate those missing symbols.
