### ISSUE TITLE
Missing d2i_RSA_NET.  Replacement for load_netscape_key

### ISSUE THREAD

**Issue by hlsantos** [openssl/openssl#8577]
What replaces this function that was used in (apps\apps.c): load_netscape_key()) that was removed? 

My ssl configuration code had used the 1.02q apps\apps.c code to check private keys.  What would the function in 1.02q apps\apps.c be replaced with?

**Comment by mlindner** [comment]
Those functions aren't valid for any private keys, how could you be using them? They're from an outdated standard from 2 decades ago.

**Comment by hlsantos** [comment]
20 years?  Openssl is about that old.    

It was used to import IIS Cert/Keys when customers (of all scales; hobbyist, small biz to enterprise) switch from IIS to our Wildcat! platform   

This should not be a concern.  We are talking about an OpenSSL API product line where coders provide a vast array of features and the client/server implementors to  pick and choose what they need to offer out of the box, or optionally to their customers.  You can't make decisions like this for folks like this by pulling stuff out especially after 20 years without a workaround or perhaps by moving the code  to a legacy set of API that is still part of the package.  Something,  you just don't pull code list this..   That's not cool.  Its create kludges and more support headaches.  Let the implementer decide what is required or not for their OpenSSL package.

Thanks

PS:  We still provide integrated RS232/Modem Hosting Servers to a vast array of high end enterprise market for nearly 30 years moving data around..  Many migrated to the TCP/IP hosting by simply flipping a switch.  Many stayed with RS232 because of business or security mandates believe it or not.

**Comment by kroeckx** [comment]
As it has been pointed out, this is an obsolete and insecure file format. I suggest you actually remove support for it. I would even suggest that they don't convert the old format to an other format but just generate new keys instead.

**Comment by mlindner** [comment]
> 20 years? Openssl is about that old.

If you look at the changes, they were announced in a release that came out in the year 2001, 0.9.6a. So yes, it's about 20 years old.

**Comment by mlindner** [comment]
It's dangerous to use such features because it _looks_ like you're being secure when in a fact the keys are almost trivially breakable, especially if they're export ciphers those can be cracked relatively easily by modern computers. With modern hardware you can break the weakest 40 bit ciphers in seconds.
