### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by sdmhdn** [openssl/openssl#8583]
Hi,

I'm using OpenSSL 1.0.2 to extract some useful informations about ssl certificate messages in ssl traffic. At the begining, i use this code in my constractor :

    ```
    OpenSSL_add_all_algorithms();

    ```
and ath the end, in my distractor, i use this code : 

    ```
    CONF_modules_unload(1);
    EVP_cleanup();
    CRYPTO_cleanup_all_ex_data();
    ERR_remove_state();
    ERR_free_strings();

    ```

but, when i test my code with valgrind, final report indicate some memory leak in openssl which is about OpenSSL_add_all_ciphers and OpenSSL_add_all_algorithms_noconf and EVP_add_cipher.

**Comment by mattcaswell** [comment]
Can you provide a sample of the valgrind report? Is your application multi-threaded or single threaded?

**Comment by mattcaswell** [comment]
No response to question so closing.
