### ISSUE TITLE
[1.1.1] OCSP_id_cmp function parameters are not const

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8589]
OCSP_id_cmp in crypto/ocsp/ocsp_lib.c takes two OCSP_CERTID* that are non-const. This makes it incompatible with functions like OCSP_SINGLERESP_get0_id that return const parameters. Please fix this in 1.1.1.

https://github.com/openssl/openssl/blob/3d753b0cefaa7e3d4b5d12d7805b20fabff1f385/crypto/ocsp/ocsp_cl.c#L393-L396

https://github.com/openssl/openssl/blob/3d753b0cefaa7e3d4b5d12d7805b20fabff1f385/crypto/ocsp/ocsp_lib.c#L103-L110

**Comment by mattcaswell** [comment]
Fix in #8597.

**Comment by mlindner** [comment]
@mattcaswell This should have gotten merged to 1.1.1 as well. A non-const to const parameter change is API and ABI compatible.
