### ISSUE TITLE
X509_chain_up_ref does not check the return value of X509_up_ref possibly resulting in malformed stack

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8592]
https://github.com/openssl/openssl/blob/3e4b43b9e5aba6261b1ceb832c597ce8225782ef/crypto/x509/x509_cmp.c#L448-L458

There is no check of the return value of X509_up_ref, possibly resulting in a malformed chain if a lock acquire fails to occur. Found through code inspection.

**Comment by mattcaswell** [comment]
Fix in #8598.

**Comment by mlindner** [comment]
@mattcaswell This can be closed now right?
