### ISSUE TITLE
static const BIO_METHOD * declaration can cause unresolved link issue.

### ISSUE THREAD

**Issue by hlsantos** [openssl/openssl#8595]
In addressing issue #8562,  I was able to confirm a link issue (using VS2015 C/C++)  when using the declaration:

``` C
static const BIO_METHOD *BIO_s_wcfile(void)
{
 ...
}
```

and the BIO_s_wcfile() is referenced in other source files, the linker shows:

error LNK2019: unresolved external symbol BIO_s_wcfile referenced in function other_source_file
fatal error LNK1120: 1 unresolved externals

The other_source_file.cpp has has the proper extern statement:

extern const BIO_METHOD *BIO_s_wcfile(void);

The solution was to remove the static in the main declaration.   Minor but probably a good idea to change this in the following files:

apps\s_server.c
test\asynciotest.c
test\sslcorrupttest.c
test\tls13ccstest.c

**Comment by mspncp** [comment]
The `wc` prefix in `BIO_s_wcfile()` seems to indicate that you are building a private, modified version of OpenSSL. There is no such function like `BIO_s_wcfile()` in the source code, neither in 1.1.1

```
~/src/openssl-1.1.1$ grep -rnH 'BIO_METHOD.*BIO_s_.*file' *
crypto/bio/bss_file.c:108:const BIO_METHOD *BIO_s_file(void)
crypto/bio/bss_file.c:415:const BIO_METHOD *BIO_s_file(void)
doc/man3/BIO_s_file.pod:13: const BIO_METHOD *BIO_s_file(void);
include/openssl/bio.h:547:const BIO_METHOD *BIO_s_file(void);
```
nor in 1.0.2

```
~/src/openssl-1.0.2$ grep -rnH 'BIO_METHOD.*BIO_s_.*file' *
crypto/bio/bss_file.c:211:BIO_METHOD *BIO_s_file(void)
crypto/bio/bio.h:654:BIO_METHOD *BIO_s_file(void);
doc/crypto/BIO_s_file.pod:13: BIO_METHOD *      BIO_s_file(void);
doc/ssleay.txt:1303:BIO_METHOD *BIO_s_file(void);
```

The only grep hits show `BIO_s_file()` and none of those declarations is static.

So what makes you think your build problem is an OpenSSL issue?

**Comment by t-j-h** [comment]
@hlsantos is just pointing out the the examples are all self-contained in a single file and hence are all static and the normal pattern of real usage will have these as global functions so they can be passed into BIO_new and the suggestion is to change those.

Personally I would leave the examples as show alone but perhaps note that elsewhere - to me that is an obvious thing - if you want a function to be shared outside of a single C file it needs to not be static - and I don't see that as an OpenSSL issue. 

But I do understand what @hlsantos is explaining as the issue when copying code to write a new BIO method.

**Comment by mspncp** [comment]
Ah I see. It did not come to my mind that he was referring to the examples.

**Comment by mattcaswell** [comment]
> The solution was to remove the static in the main declaration. Minor but probably a good idea to change this in the following files:
>
> apps\s_server.c
> test\asynciotest.c
> test\sslcorrupttest.c
> test\tls13ccstest.c

While people do use the apps and tests as examples that is not their primary purpose. Since the BIO_METHOD declarations are not used outside the files they are declared in, it seems to me that "static" is entirely appropriate for those files. It also seems obvious to me that if you want to use them in other files then you shouldn't declare them as static. That is just C programming and not specific to OpenSSL usage.

So, IMO, no change should be made for this.

**Comment by hlsantos** [comment]
Yes, I agree, a minor.  No problem closing this issue. 

Overall @mattcaswell,  C/C++ coders would|should be aware but it helps to get a good handle on the the OpenSSL technical requirements, like establishing the "contract" and scope for variables and functions in the quest for a new OpenSSL (opaque) API interface.  In this case, there is no technical OpenSSL reason why a private BIO_METHOD "initializer" function, used as input for BIO_NEW(), must remain static.  IOW, it would be "OpenSSL Safe" to not make them static.  However, the only technical requirement is for the pointer to the BIO_METHOD variable instance remain static and in this case, the static instance of the variable has a global scope.   

There are some notes about this, specifically with the MS C/C++ compiler:

https://docs.microsoft.com/en-us/cpp/c-language/storage-class?view=vs-2017

```
Microsoft Specific

When the Microsoft extensions are enabled, a function originally declared without a storage class (or with extern storage class) is given static storage class if the function definition is in the same source file and if the definition explicitly specifies static storage class.

When compiling with the /Ze compiler option, functions declared within a block using the extern keyword have global visibility. This is not true when compiling with /Za. This feature should not be relied upon if portability of source code is a consideration.

END Microsoft Specific
```

**Comment by levitte** [comment]
The reason they've been made static in apps and test programs is the `--strict-warnings` configuration flag, which gives gcc builds `-Wmissing-prototypes`. From [the gcc manual](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html):

> `-Wmissing-prototypes` (C and Objective-C only)
> Warn if a global function is defined without a previous prototype declaration. This warning is issued even if the definition itself provides a prototype. Use this option to detect global functions that do not have a matching prototype declaration in a header file. 

This is primarily used to avoid very internal symbols to become visible in the libraries, and it might be arguable if this is really needed in an application, but here we are, we do apply that same warning flag everywhere, which has the compiler complain loudly if we have non-static functions without a proper declaration.

So if we do want to change this in any way, we have to start with deciding if we have to be as strict with programs as we must with libraries. 

I'm reopening, 'cause this became an interesting question.

**Comment by hlsantos** [comment]
I believe this should be a compiler independent issue and OpenSSL should continue its course to be single sourced, portable and keep with consistency - tons of compiler pragmas.  Overall, imv,  the apps should follow what the API requires.  

The API for BIO_METHOD BIO_s_file() follows a non-static for exposing the initializer function  Other 3rd party private methods SHOULD|should follow the API methodology.  Coders should be aware if its public or private app requirement. This is as close to be being an constructor in OOPs and when OpenSSL gets there,  there will be much new public, private, protected and friend(ly) class member attribute design considerations.     I can't wait to see that.  Maybe it will be modeled after some existing OOPS OpenSSL framework.   I would also agree that OpenSSL has been around a long time so there is a much support considerations.  I envy the OpenSSL Authors.  Its not a easy  thing to do.

**Comment by levitte** [comment]
I don't think there's much more to say on the subject, or anything to fix for this issue, so clossing.
