### ISSUE TITLE
aes-256-ctr block size incorrect

### ISSUE THREAD

**Issue by tomuta** [openssl/openssl#8605]
It appears that OpenSSL 1.1.0g (Ubuntu 18.04) returns a block size of 1 for AES-256 in CTR mode, which seems incorrect. The following test program reproduces the issue:

```
#include <stdio.h>
#include <openssl/ssl.h>
#include <openssl/evp.h>

int main(int argc, char *argv[])
{
	const EVP_CIPHER* c;
	SSL_library_init();
	c = EVP_get_cipherbyname("aes-256-ctr");
	if (c)
		printf("cipher %s block size: %d\n", EVP_CIPHER_name(c), EVP_CIPHER_block_size(c));
	else
		fprintf(stderr, "cipher not found\n");
	return 0;
}
```

```
gcc -o aes-ctr-blocksize-test aes-ctr-blocksize-test.c -lcrypto -lssl && ./aes-ctr-blocksize-test 
cipher AES-256-CTR block size: 1
```

**Comment by bernd-edlinger** [comment]
in CTR mode the cipher text does not need to end at a block boundary.

**Comment by mattcaswell** [comment]
This is intentional for the reason that @bernd-edlinger gives.

**Comment by tomuta** [comment]
> in CTR mode the cipher text does not need to end at a block boundary.

True, but it does need to start at a block boundary. E.g. if you start reading/downloading a file from an arbitrary offset, you need to know the block size so you can round down properly (and calculate the IV). I worked around this to make things work, but the code sure looks like one ugly hack.
