### ISSUE TITLE
copy parameter `file` of CRYPTO_mem_debug_* functions ?

### ISSUE THREAD

**Issue by avodonosov** [openssl/openssl#861]
It makes sense to copy the `file` string passed to `CRYPTO_mem_debug_*` functions, to facilitate usage from languages other than C. 

Currently `file` is expected to remain valid even after function returns (static storage class, as guaranteed by `__FILE__` C macro). But when we call for example `CRYPTO_free` from non-C language, the value we pass is usually allocated dynamically. Creating global values is not very convenient.

Here is an example in Common Lisp - as a workaround I just allocate global value "unknown file" and pass to `CRYPTO_free`: https://github.com/cl-plus-ssl/cl-plus-ssl/pull/30#issuecomment-196114925

**Comment by richsalz** [comment]
You're doing the right thing -- it's the responsibility of the wrappers to maintain the C-like string lifetimes.
