### ISSUE TITLE
What should EVP_MD_CTX_md return in 3.0?

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#8613]
The function `EVP_MD_CTX_md` returns the EVP_MD object associated with the EVP_MD_CTX. However, if the application used implicit fetch (as will the vast majority of programs initially) then this might return something unexpected, i.e. it currently returns the "fetched" digest, rather the "const" built-in version. This is problematic for 2 reasons:

1) If applications attempt to compare the returned EVP_MD * with the const versions then they won't get a match
2) If the EVP_MD_CTX subsequently gets freed, and the ref count on the fetched EVP_MD drops to zero, then the object could disappear even though the application might still be holding on to the return value from EVP_MD_CTX_md().

I think this means we somehow have to have EVP_MD_CTX_md returning the const EVP_MD originally asked for, where implicit fetch is in use.

**Comment by levitte** [comment]
> I think this means we somehow have to have EVP_MD_CTX_md returning the const EVP_MD originally asked for, where implicit fetch is in use.

Took me a minute to think this through, but that does make sense to me.

**Comment by slontis** [comment]
Hmm - if they are just using it to do a comparison then that is fine. If it still has method ptrs inside that then get accessed then that might not be so good
