### ISSUE TITLE
Leak/double free from using new X509_set_sm2_id function

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8617]
@InfoHunter I brought this in the reviews for https://github.com/openssl/openssl/pull/8465/ but I was ignored. 

```
// We have a X509* certificate x and an ASN1_OCTET_STRING* sm2_id, both allocated with assocaited _new() functions
X509_set_sm2_id(x, sm2_id);
ASN1_OCTET_STRING_free(sm2_id); // <--- free of internal x->sm2_id->data buffer
new_sm2_id = X509_get0_sm2_id(x);
//Access new_sm2_id->data results in illegal memory access of freed memory

```

Please fix this and do not ignore the issue.

**Comment by mlindner** [comment]
Alternatively:

```
// We have a X509* certificate x and an ASN1_OCTET_STRING* sm2_id, both allocated with assocaited _new() functions
X509_set_sm2_id(x, sm2_id);
X509_free(x); // <--- memory leak of sm2_id->data.
```

**Comment by InfoHunter** [comment]
The user should not do a `get` operation or SM2 related operations after he frees the `sm2_id` object which is set to an X509 object. The `X509_set_sm2_id` is something the same to other `set0` setters, say, consider the scenario that you are using `RSA_set0_factors` and are setting two `BIGNUM` objects to an `RSA` object. If you free the two `BIGNUM` objects before you are going to use the `RSA` object (to encrypt a piece of data for instance), you will access illegal memory as well.

The correct usage of this should be:

```
/* allocate sm2_id memory by whatever method */
X509_set_sm2_id(x, sm2_id);
new_sm2_id = X509_get0_sm2_id(x); /* if needed, usually not needed */
/* free sm2_id */
```

The different part is that, in X509 context, we don't free the sm2_id assigned to X509 structure, so the user needs to free the sm2_id himself.

Maybe the API name should be changed to `X509_set0_sm2_id` and drop a message in the doc to indicate this behaviour?

**Comment by InfoHunter** [comment]
> Alternatively:
> 
> ```
> // We have a X509* certificate x and an ASN1_OCTET_STRING* sm2_id, both allocated with assocaited _new() functions
> X509_set_sm2_id(x, sm2_id);
> X509_free(x); // <--- memory leak of sm2_id->data.
> ```

This is not a *leak*, the sm2_id should be freed by user explicitly.

**Comment by InfoHunter** [comment]
Another option is to make `X509_free` also frees the sm2_id field in the structure, but I am not sure if we should do that or just keep it as-is.

**Comment by mlindner** [comment]
> The user should not do a get operation or SM2 related operations after he frees the sm2_id object which is set to an X509 object.

So the sm2_id object is NEVER owned by the X509 object? That doesn't line up with any other OpenSSL structure. 

> The X509_set_sm2_id is something the same to other set0 setters

If it's the same as the other set0 setters then ownership passes to the X509* structure and you can set the original sm2_id to NULL and it will never leak. set0 implies you never need to free it and you never _should_ free it. That's not true with your implementation because as you stated it's not part of the ASN1 structure so X509_free() won't free it.
The two possibilites are:
* set0: ownership passes to the structure it's being set into, that structure is responsible for freeing it when its' free function is called
* set1: the structure is copied or reference count incremented into the structure and the caller is responsible for freeing their copy of the data
You have a situation that is neither set0 nor set1 and more so is impossible to do programmatically because you're forced to keep both sm2_id and the x509 certificate around in order to correct free memory and free them both at the same time. No one writes C code like this.

> consider the scenario that you are using RSA_set0_factors and are setting two BIGNUM objects to an RSA object. If you free the two BIGNUM objects before you are going to use the RSA object (to encrypt a piece of data for instance), you will access illegal memory as well.

Yes, but when you call RSA_free() on the RSA object it frees the objects set by RSA_set0_factors. From my understanding you never anything that frees sm2_id.

**Comment by mlindner** [comment]
> Another option is to make `X509_free` also frees the sm2_id field in the structure, but I am not sure if we should do that or just keep it as-is.

Yes that is what must be done, however the X509_free function is generated.

**Comment by InfoHunter** [comment]
There is an ASN1 callback which is triggered in X509_free (actually the ASN1_item_free) and in that callback any extra operation can be done, for instance, to free the sm2_id or other structure filed of X509 structure.

**Comment by InfoHunter** [comment]
So this is an issue about consistency but not memory leaks from my understandings

**Comment by mlindner** [comment]
It's not an issue about consistency, the API as used leaks memory in the current OpenSSL.

**Comment by InfoHunter** [comment]
> It's not an issue about consistency, the API as used leaks memory in the current OpenSSL.

It doesn't leak memory in apps/verify (the only place where this API is used in current OpenSSL), but anyway I make it consistent with other `set0` type setters in PR #8626

**Comment by mlindner** [comment]
> > It's not an issue about consistency, the API as used leaks memory in the current OpenSSL.
> 
> It doesn't leak memory in apps/verify (the only place where this API is used in current OpenSSL), but anyway I make it consistent with other `set0` type setters in PR #8626

Technically yes, but only by luck and because it's an application instead of some library code or anything else. I'm glad you created a PR for this.

**Comment by InfoHunter** [comment]
Not a problem ;-)

**Comment by InfoHunter** [comment]
Hi @mlindner , PR #8626 has been merged, so could this issue be closed?
