### ISSUE TITLE
android-arm64 build fails

### ISSUE THREAD

**Issue by AndreyPavlenko** [openssl/openssl#8619]
The attached script successfully builds targets android-arm, android-x86 and android-x86_64 but it fails for android-arm64 with the following error:

${LDCMD:-clang} -pie -pthread  -target aarch64-linux-android -gcc-toolchain /home/andrey/android/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/home/andrey/android/android-ndk/platforms/android-21/arch-arm64 -Wa,--noexecstack -Qunused-arguments -Wall -O3 -flto -L.   \
        -o test/buildtest_aes test/buildtest_aes.o \
         -lssl -lcrypto -lz -ldl -pthread 
/home/andrey/android/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: skipping incompatible ./libssl.a when searching for -lssl
/home/andrey/android/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: cannot find -lssl
/home/andrey/android/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: skipping incompatible ./libcrypto.a when searching for -lcrypto
/home/andrey/android/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: cannot find -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test/buildtest_aes] Error 1
make[1]: Leaving directory `/home/andrey/android/dev/build/arm64-api21/openssl/src'
make: *** [all] Error 2

[build.sh.zip](https://github.com/openssl/openssl/files/3026114/build.sh.zip)

**Comment by levitte** [comment]
Was this from a pristine source tree?

**Comment by AndreyPavlenko** [comment]
Yes, initially I encountered this failure when building from these sources - https://www.openssl.org/source/openssl-1.1.1b.tar.gz. Then I've downloaded openssl-master.zip from github and see the same issue.

**Comment by AndreyPavlenko** [comment]
This [build.sh.zip](https://github.com/openssl/openssl/files/3026469/build.sh.zip) script  downloads the sources from github and the same error:

${LDCMD:-clang} -pie -pthread  -target aarch64-linux-android -gcc-toolchain /home/andrey/android/android-ndk-r19c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/home/andrey/android/android-ndk-r19c/platforms/android-21/arch-arm64 -Wa,--noexecstack -Qunused-arguments -Wall -O3 -flto -L.   \
	-o test/buildtest_c_aes test/buildtest_c_aes-bin-buildtest_aes.o \
	 -lssl -lcrypto -lz -ldl -pthread 
/home/andrey/android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: skipping incompatible ./libssl.a when searching for -lssl
/home/andrey/android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: cannot find -lssl
/home/andrey/android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: skipping incompatible ./libcrypto.a when searching for -lcrypto
/home/andrey/android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld: cannot find -lcrypto

**Comment by AndreyPavlenko** [comment]
Seems the root cause is -flto flag. If I remove  -flto from OPENSSL_CONFIGURE_OPTS, the build does not fail.

**Comment by levitte** [comment]
In that case, you should make the `-flto` flag conditional depending on what platform you build for in your build.sh.  That's where it comes from.

And that means this issue gets closed.

**Comment by AndreyPavlenko** [comment]
The -flto flag should also be supported for arm64. I use it to build all my apps and it works just fine for arm64.
