### ISSUE TITLE
Backward compatibility: SSLeay function is gone

### ISSUE THREAD

**Issue by avodonosov** [openssl/openssl#862]
Function `SSLeay` is part of public API: https://www.openssl.org/docs/man1.0.1/crypto/OPENSSL_VERSION_NUMBER.html

In the current master this function is removed and instead `OpenSSL_version_num` is introduced. This breaks backward compatibility - existing clients who already use SSLeay.

Suggestion: keep `SSLeay` for backwards compatibility (even if deprecated; you introduce `OpenSSL_version_num`, but old function exists too)

**Comment by avodonosov** [comment]
BTW, it would be very helpful if documentation mentioned in which version a function is introduced. Similar to @since annotation in javadocs.

This page for example - https://www.openssl.org/docs/manmaster/crypto/OPENSSL_VERSION_NUMBER.html - doesn't mention that `OpenSSL_version_num` is absent in old version. It's important to know for a programmer.

**Comment by richsalz** [comment]
The SSL_eay versions are enabled if an -api config flag is set.  Source compatibility is maintained with that.  We explicit say there is no binary (ABI) compatibility.  We decided not to add "since" documentation.  If you want to discuss that on the mailing list, please do so.

**Comment by ekasper** [comment]
Also, I realise that "since" would be simpler but... looking at the manpages of an earlier branch can be helpful when programming against an earlier branch (manmaster is for master).

**Comment by avodonosov** [comment]
You mean manpages in branches at github? Ok, good to know (because the website only has working docs for  1.0.2 and 1.0.1). But that's a minor question.

The most confounding discovery is lack of backwards compatibility.

@richsalz I see, you have `SSLeay` declared as a `define` macro expanding to `OpenSSL_version_num`.

It's difficult to understand for me why you don't want to keep old function, as real exported symbol e.g. 
`unsigned long (*SSLeay)(void) = OpenSSL_version_num`

I will follow up on the mailing list with that question.

**Comment by richsalz** [comment]
Sure, but please see https://openssl.org/policies/releasestrat.html which describes our compatibility aims.

**Comment by avodonosov** [comment]
@richsalz I've read this two times already. Will read again before posting to mailing list.

**Comment by keaston** [comment]
Just for posterity I'll point out that declaring SSLeay as a macro means that autoconf `AC_CHECK_LIB()` invocations looking for SSLeay don't find it anymore.
