### ISSUE TITLE
ia64cpuid.S is removed by make clean on MacOS

### ISSUE THREAD

**Issue by shigeki** [openssl/openssl#863]
`make clean` on MacOS removes `crypto/ia64cpuid.S` because MacOS HFS+ filesystem is case insensitive so that `rm crypto/ia64cpuid.s` also remove it.

```sh
ohtsu@ohtsu-mac:openssl$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    crypto/ia64cpuid.S

no changes added to commit (use "git add" and/or "git commit -a")
````

See https://github.com/openssl/openssl/pull/853#issuecomment-196194142.

Cc: @levitte

**Comment by levitte** [comment]
Hey, I wonder, how did you configure?  As far as I know, we don't have a MacOS target config for IA64.

**Comment by levitte** [comment]
I never got an answer for this, so closing.
