### ISSUE TITLE
"bcrypt.dll was not found" after compiling for Windows XP.

### ISSUE THREAD

**Issue by HerMajestyDrMona** [openssl/openssl#8635]
I'm compiling static openssl-1.1.1b using Visual Studio 2017 on Windows 10.
The compilation process is flawless. Unfortunately, after including "libssl.lib" and "libcrypto.lib" to curl and testing it on Windows XP, I get the following error on launch: "The application has failed to start because bcrypt.dll was not found". It doesn't happen when I compile the old version: openssl-1.1.0e.
Commands I'm using are the following:
```
set LINK=/subsystem:console,5.01
perl Configure VC-WIN32 no-asm no-shared no-async --prefix="D:\Visual Studio\openssl" -D_USING_V141_SDK71_
nmake
nmake test
```

**Comment by mspncp** [comment]
It's a windows system library, which is added by the following linker pragma. 
https://github.com/openssl/openssl/blob/50eaac9f3337667259de725451f201e784599687/crypto/rand/rand_win.c#L26-L28

This was introduced in fa64e63373fbc845a39907407ad990a6bbb84174 and according to the comment, it is used only if compiling for Windows 7 and higher. Since you intend to use it on Windows XP, is it possible that you have set the wrong `_WIN32_WINNT` for that?

**Comment by mspncp** [comment]
BCryptGenRandom is available [starting with Windows Vista/Windows Server 2008](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptgenrandom#requirements).

**Comment by mattcaswell** [comment]
As per @mspncp's comment try adding "-D_WIN32_WINNT=0x0501" to your Configure line.

It's unclear whether we should be doing that automatically - we appear to be inconsistent. In "e_os.h" we do this:

````
#  ifdef WINDOWS
#   if !defined(_WIN32_WCE) && !defined(_WIN32_WINNT)
       /*
        * Defining _WIN32_WINNT here in e_os.h implies certain "discipline."
        * Most notably we ought to check for availability of each specific
        * routine that was introduced after denoted _WIN32_WINNT with
        * GetProcAddress(). Normally newer functions are masked with higher
        * _WIN32_WINNT in SDK headers. So that if you wish to use them in
        * some module, you'd need to override _WIN32_WINNT definition in
        * the target module in order to "reach for" prototypes, but replace
        * calls to new functions with indirect calls. Alternatively it
        * might be possible to achieve the goal by /DELAYLOAD-ing .DLLs
        * and check for current OS version instead.
        */
#    define _WIN32_WINNT 0x0501
#   endif
````
But that header never gets included from the rand_win.c code AFAICT.

**Comment by levitte** [comment]
> But that header never gets included from the rand_win.c code AFAICT.

I just looked through the includes that I can see, and agree.

@HerMajestyDrMona, can you apply this patch and confirm that it fixes the issue?

``` diff
diff --git a/crypto/rand/rand_win.c b/crypto/rand/rand_win.c
index 278aee08b4..02d96a8a2a 100644
--- a/crypto/rand/rand_win.c
+++ b/crypto/rand/rand_win.c
@@ -11,6 +11,7 @@
 #include <openssl/rand.h>
 #include "rand_lcl.h"
 #include "internal/rand_int.h"
+#include "e_os.h"                /* For a default _WIN32_WINNT */
 #if defined(OPENSSL_SYS_WINDOWS) || defined(OPENSSL_SYS_WIN32)
 
 # ifndef OPENSSL_RAND_SEED_OS
```

**Comment by HerMajestyDrMona** [comment]
Thanks a lot. I confirm that including "e_os.h" fixes the problem.

I was actually already using "-D_WIN32_WINNT=0x501" in the Configuration line, but removed it when noticed that it has no effect, and I wasn't sure if this syntax was correct.

**Comment by levitte** [comment]
Thanks for confirming.  Fix in #8638

**Comment by levitte** [comment]
I'm going to revert #8638, as it causes BCrypt *never* to be used unless the configuration says otherwise.  That wasn't quite the intent.  There's a discussion going on in #8640 regarding this...

**Comment by levitte** [comment]
I've reopened this because #8640 was a too quick solution, and [ahem] I hadn't registered the whole story here.

@HerMajestyDrMona, you said something about `-D_WIN32_WINNT=0x0501` not giving you the desired result, but without detail.  That *should* have worked.  Can you show a complete configuration line?

**Comment by HerMajestyDrMona** [comment]
Sorry for confusions.
I think I might had a mistake in this command. When I was googling for the solution, I found this thread: https://github.com/openssl/openssl/issues/1766#issue-184519867
And copied: "-D_WIN32_WINNT=0x501"

**Comment by mspncp** [comment]
I don't think this will make a difference. For the compiler, 0x501 and 0x0501 are the same number.

**Comment by HerMajestyDrMona** [comment]
Worked on a clean "1.1.1b" without applying any fixes:
`set LINK=/subsystem:console,5.01
perl Configure VC-WIN32 no-asm no-shared no-async -DOPENSSL_NO_ASYNC -D_WIN32_WINNT=0x0501 --prefix="D:\Visual Studio\openssl" -D_USING_V141_SDK71_`

I gonna recheck again with "-D_WIN32_WINNT=0x501".

**Comment by matbech** [comment]
See my comment in https://github.com/openssl/openssl/commit/2621e6405d7f4765bc57c86ec441129e7d367f14
why BCryptGenRandom was only used starting with Windows 7.

**Comment by HerMajestyDrMona** [comment]
I did few more tests, using commands I used earlier (saved in a .txt file). Every time when "-D_WIN32_WINNT=0x0501" (or 0x501) is used it doesn't give the "bcrypt.dll" error. I don't know what was wrong before. The only difference is that now, before every test I delete the openssl folder and unpack the openssl-1.1.1b.tar.gz archive again. Perhaps "nmake clean" didn't clean everything, or Visual Studio cached it somewhere, or simply user error...

I was confused, because back then, in 2017 when I compiled 1.1.0e it didn't throw .dll errors, even when "D_WIN32_WINNT" was not set in the Configuration line. Looking at the repository, many things changed, so possibly something there too.

Once again I apologize for the inconvenience.

**Comment by levitte** [comment]
OK, does that mean that this issue can be closed?

**Comment by HerMajestyDrMona** [comment]
Yes, thank you.

**Comment by hidiego** [comment]
Has anyone here found the way to compile using toolset 120_xp?
