### ISSUE TITLE
Error in libcrypto.so.1.1 while building openssl1.1.1b 

### ISSUE THREAD

**Issue by anjani-telkar** [openssl/openssl#8643]
Currently in our project we are using openssl-1.0.2k version,planning to upgrade the same to openssl-1.1.1b version.

Downloaded openssl-1.1.1b.tar.gz 
tar -xzvf openssl-1.1.1b.tar.gz
Before applying patch we copied the Makefile,Makefile.bak,makefile.org and makefile.shared from openssl-1.0.2k to openssl-1.1.1b/ and changed the version in makefile from 1.0.2k to 1.1.1b
tar -zcvf openssl-1.1.1b.tar.gz openssl-1.1.1b
we applied 1.0.2k patch on 1.1.1b and created patch,

Once I started build getting below error,not sure whether need to copy those makefiles or not,please guide me or suggest me where I am wrong

*** Installing runtime libraries
install libcrypto.so.1.1 -> /usr/lib/libcrypto.so.1.1
cp: cannot create regular file `/usr/lib/libcrypto.so.1.1.new': Permission denied
make: *** [install_runtime_libs] Error 1
        echo "No Post Install Command" ;if [[ $? -ne 0 ]]; then exit 1;fi
No Post Install Command

bash-4.1$ uname -a
 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

bash-4.1$ which openssl
/usr/bin/openssl

please let me know if you need more info.

**Comment by levitte** [comment]
With OpenSSL 1.1.0, the configuration and build system changed substantially.  Build files such as Makefile from pre-1.1.0 will simply not work at all.

What you need to do is configure the new OpenSSL anew.  If you want to remember what configuration options you used with 1.0.2k, do this:

```
grep ^CONFIGURE_ARGS= Makefile
```

and then run `./config` with the args that seem suitable (at the very least, skip the first).  In a 1.0.2 build I have, here's what it looks like:

```
: ; grep ^CONFIGURE_ARGS= Makefile
CONFIGURE_ARGS=linux-x86_64 --debug --strict-warnings -Wa,--noexecstack
```

I could then do this to reproduce the same options in 1.1.1b:

```
./config --debug --strict-warnings -Wa,--noexecstack
```

What that's done, run `make` as usual.
