### ISSUE TITLE
rand_win.c: BCryptGenRandom() used incorrectly on Windows Vista

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#8644]
In #8639 the version requirements for BCryptGenRandom were loosened from Windows 7 to Windows Vista. Subequently, [it was reported](https://github.com/openssl/openssl/commit/2621e6405d7f4765bc57c86ec441129e7d367f14#commitcomment-33002401) by @matbech, the original author (see #1142), that Windows Vista does not support calling BCryptGetRandom with the BCRYPT_USE_SYSTEM_PREFERRED_RNG flag. Instead, BCryptGenRandom() needs to be called with the handle of an algorithm provider, obtained using BCryptOpenAlgorithmProvider().

Instead of reverting #8639 as requested, my plan is to make BCryptGenRandom() behave correctly for Windows Vista. The idea is to attempt calling BCryptGenRandom(..., BCRYPT_USE_SYSTEM_PREFERRED_RNG) first, and failing that to fall back to using the Microsoft CNG provider.

_(I'll need to set up a Vista VM first to to be able to test it properly, so please hang on...)_

**See also**

- #1142 - Use BCryptGenRandom on Windows 7 or higher
- #2168 - rand_win.c may use BCryptGenRandom with BCRYPT_USE_SYSTEM_PREFERRED_RNG
- #8639 - rand_win.c: loosen version requirements for BCryptGenRandom

- [Microsoft Docs - BCryptGenRandom](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptgenrandom)
- [Microsoft Docs - BCryptOpenAlgorithmProvider](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptopenalgorithmprovider)

**Comment by HerMajestyDrMona** [comment]
A bit off-topic, but:
Wouldn't it be safer to first check if bcrypt.dll exists, then use GetProcAddress to get BCryptGenRandom, and if unsuccessful (Windows XP) use the old method? I'm asking, because I personally had to use "-D_WIN32_WINNT=0x0501" just for this function in libcurl ( https://github.com/openssl/openssl/issues/8635 ). Some developers might compile for XP to make it possible to start, even when 99% of users use Windows 7 or newer. In my opinion it could be good to allow BCryptGenRandom whenever possible. Not sure if that wouldn't complicate it too much or affect consistency of the code... just sharing my thoughts.

**Comment by mspncp** [comment]
I instrumented openssl with some printf's (see mspncp/openssl#7) and tested it on Windows Vista SP2. It seems that the [MSDN Documentation](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptgenrandom) is outdated, at least for SP 2.  The BCryptGenRandomCall() succeeded.

If nobody objects, I will consider this issue resolved and close it tomorrow.

_(@HerMajestyDrMona concerning Windows XP: I would consider it a waste of energy to make any efforts to 'fix' openssl for Windows XP, because Windows XP is EOL since 2014 and nowadays hopelessly insecure.)_

**Comment by mspncp** [comment]
Ok, I consider this issue resolved for the moment.

If anyone suspects that BCryptGenRandom() does not work on his Windows Vista machine, he might compile his own instrumented openssl application from mspncp#7 and run the

```
openssl rand -hex 10
```
command. If it does not show `STATUS_SUCCESS` as below, please post the output here, together with the Windows version.

```
Microsoft Windows [Version 6.0.6002]
Copyright (c) 2006 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\msp>openssl rand -hex 10
_WIN32_WINNT = 0x00000603
BCryptGenRandom() returned STATUS_SUCCESS
37a655fb82d04c43e694
```

**Comment by pps83rbx** [comment]
> A bit off-topic, but:
> Wouldn't it be safer to first check if bcrypt.dll exists, then use GetProcAddress to get BCryptGenRandom, and if unsuccessful (Windows XP) use the old method? I'm asking, because I personally had to use "-D_WIN32_WINNT=0x0501" just for this function in libcurl ( #8635 ). Some developers might compile for XP to make it possible to start, even when 99% of users use Windows 7 or newer. In my opinion it could be good to allow BCryptGenRandom whenever possible. Not sure if that wouldn't complicate it too much or affect consistency of the code... just sharing my thoughts.

I'd would even prefer to GetModuleHandleA("bcrypt") before using bcrypt. This way at least it would be less intrusive and would allow to [delay load bcrypt.dll](https://docs.microsoft.com/en-us/cpp/build/reference/delayload-delay-load-import)

**Comment by paulidale** [comment]
Do you realise that both calls are identical underneath the API layer?  `BCryptGenRandom` isn't a security improvement, it is a usability improvement.

We've got to support the legacy call BTW.

**Comment by pps83** [comment]
> Do you realise that both calls are identical underneath the API layer? `BCryptGenRandom` isn't a security improvement, it is a usability improvement.
> 
> We've got to support the legacy call BTW.

Can you please clarify what are you referring and replying to?

**Comment by paulidale** [comment]
The older `CryptGenRandom` will exist and is the same as `BCryptGenRandom`.
There is no need to call the first if the second fails.

Yeah, my comments are too late to change this PR.

**Comment by sebres** [comment]
I think 2621e6405d7f4765bc57c86ec441129e7d367f14 is not quite complete - there are certain win-SDK's (regardless which windows version used) where `BCRYPT_USE_SYSTEM_PREFERRED_RNG` is not defined at all in bcrypt.h.

So either it should be:
```diff
 # ifdef USE_BCRYPTGENRANDOM
 #  include <bcrypt.h>
+#  ifndef BCRYPT_USE_SYSTEM_PREFERRED_RNG
+#    undef USE_BCRYPTGENRANDOM
+#  endif
 # endif
```
or something like that:
```diff
 # ifdef USE_BCRYPTGENRANDOM
 #  include <bcrypt.h>
+#  ifndef BCRYPT_USE_SYSTEM_PREFERRED_RNG
+#    define BCRYPT_USE_SYSTEM_PREFERRED_RNG 2
+#  endif
 # endif
```

Otherwise the build can fail with `undeclared identifier 'BCRYPT_USE_SYSTEM_PREFERRED_RNG'`.

**Comment by john-8998** [comment]
> SP2

MSDN states: Windows Vista:  This flag ( BCRYPT_USE_SYSTEM_PREFERRED_RNG) **is not supported without SP2**.

@mspncp i would take @HerMajestyDrMona idea (GetProcAddress) advice.
