### ISSUE TITLE
TLS_DHE_RSA_WITH_AES_256_CBC_SHA shows as SSLv3 when it is a TLSv1.0 cipher

### ISSUE THREAD

**Issue by Egdod** [openssl/openssl#8655]
openssl-1.0.2k-8.0.1

RFC3268 shows the cipher ,TLS_DHE_RSA_WITH_AES_256_CBC_SHA, as a TLS1.0 cipher as does the openssl page https://www.openssl.org/docs/man1.0.2/man1/ciphers.html. shows the cipher as belonging to TLS1.0. However, openssl itself lists it as a SSLv3 cipher and blocks it when ```'!SSLV3'``` is used

```
$ openssl ciphers -v 'HIGH:' | grep "DHE-RSA-AES256-SHA" | grep -vP "(ECDHE|SHA256)"
DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1

$ openssl ciphers -v 'HIGH:!SSLv3' | grep "DHE-RSA-AES256-SHA" | grep -vP "(ECDHE|SHA256)"
$
```

**Comment by mattcaswell** [comment]
The version number shown by the ciphers command is the minimum TLS version required to support the ciphersuite (which is often, but not always, the version it was introduced in). That ciphersuite, although defined in TLS1.0, is perfectly backwards compatible with SSLv3.

**Comment by mattcaswell** [comment]
I noticed some of the docs are not entirely correct about this. Fix for that in #8658.

**Comment by Egdod** [comment]
The main issue is the cipher is removed when you use !SSLV3

**Comment by davidben** [comment]
You never actually want to use !SSLV3. It does not do what it looks like it does. If you want to disable SSL 3.0, you should disable it by configuring versions, not cipher suites.
