### ISSUE TITLE
HMAC SHA512-224, SHA512-256 output inconsistent with other implementation

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#8670]
For a cleartext of size 0 and a key of size 0

libsodium returns:

{0xb9, 0x36, 0xce, 0xe8, 0x6c, 0x9f, 0x87, 0xaa, 0x5d, 0x3c, 0x6f, 0x2e, 0x84, 0xcb, 0x5a, 0x42, 
 0x39, 0xa5, 0xfe, 0x50, 0x48, 0x0a, 0x6e, 0xc6, 0x6b, 0x70, 0xab, 0x5b, 0x1f, 0x4a, 0xc6, 0x73} (32 bytes)

OpenSSL returns:

{0xb7, 0x9c, 0x99, 0x51, 0xdf, 0x59, 0x52, 0x74, 0x58, 0x2d, 0xc0, 0x94, 0xa1, 0xba, 0x46, 0xc3, 
 0x3e, 0x4a, 0x36, 0x87, 0x8b, 0x2d, 0x83, 0xcb, 0x85, 0x53, 0xf0, 0xfe, 0x46, 0x7d, 0xcd, 0xcf} (32 bytes)

The difference is consistent across different key and cleartext sizes.
It seems that libsodium computes HMAC SHA512 and then chops off the second half, and OpenSSL does something else.

Is this intentional?

**Comment by levitte** [comment]
Hmmmm, I cannot say.  However, from reading the libsodium code, it seems we disagree on the applicable key size, i.e. the cut-off for when it should get an extra hashing before applying the ipad (since when is the block size for sha512 128 bytes?).  Not sure if that impacts here.

However, I've just found some NIST provided test vectors for HMAC-sha512/224 and HMAC-sha512/256.  I'll add them to our test data and we'll see how that goes

**Comment by levitte** [comment]
FYI, 'cause I assume this might be of interest to libsodium as well:

http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512_224.pdf
http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512_256.pdf

**Comment by levitte** [comment]
... so suffice to say that vectors for HMAC-SHA512/224 and HMAC-SHA512/256 seem to be hard to come by.  I did find [a stream on sci.crypt](https://groups.google.com/forum/#!topic/sci.crypt/OolWgsgQD-8) and tried those test vectors with our test machinery.  They pass.

**Comment by levitte** [comment]
If someone else wants to look and try: https://gist.github.com/levitte/a5ffb014eb3cc0b9b3d8eb8b6f3eb365

**Comment by levitte** [comment]
Ohhhhhh...  I just read the libsodium documentation, more precisely this (from https://download.libsodium.org/doc/advanced/hmac-sha2):

> ## HMAC-SHA-512-256
> 
> HMAC-SHA-512-256 is implemented as HMAC-SHA-512 with the output truncated to 256 bits. This is slightly faster than HMAC-SHA-256. Note that this construction is not the same as HMAC-SHA-512/256, which is HMAC using the SHA-512/256 function.

We don't implement that form of HMAC-SHA512-256, we implement HMAC using SHA512/256 as the underlying algorithm.  I think that's the reason you see a difference.

I think that makes this issue closable.

**Comment by guidovranken** [comment]
Confusing. Easy to mix those two up. :). Thanks!

**Comment by paulidale** [comment]
> suffice to say that vectors for HMAC-SHA512/224 and HMAC-SHA512/256 seem to be hard to come by

I couldn't find any when I added these.  The underlying digest does have vectors, so we know they word.  Likewise for the HMAC code.  I assumed both together would too.
