### ISSUE TITLE
openssl 1.0.2o with linux-generic32 option getting failed

### ISSUE THREAD

**Issue by anthekool** [openssl/openssl#8689]
I am using 32 bit toolchain(for x86 platform) to compile openssl with linux-generic32 option but i am getting error in sha256,sha1 test.
does linux-generic option supports sha1,sha256,sha512

**Comment by agnosticdev** [comment]
Just to get some more information, how are you compiling and what errors are you seeing in the tests?

**Comment by mattcaswell** [comment]
No response to above question so closing.
