### ISSUE TITLE
Server not responding to heartbeats with small payloads

### ISSUE THREAD

**Issue by rjwalls** [openssl/openssl#87]
My server is not responding to properly-constructed heartbeat messages with a payload size of less than 4073. I've also observed this behavior on other sites, e.g., duckduckgo.com.

Version details:
 - Ubuntu 12.04
 - Apache/2.2.22
 - OpenSSL 1.01 (Built on: Mon Apr 7)

You can run this [script](https://gist.github.com/rjwalls/ece8ec0b011d66827af3) with the following command to reproduce the behavior:

```bash
# Send a heartbeat with a payload of 4096 bytes 
./ssltest.py duckduckgo.com -l 4096

# Send a payload of 1024, should not receive response
./ssltest.py duckduckgo.com -l 1024
```

By default, the script will use a padding of 16 bytes. The code used for creating the message is:

```python
def build_heartbeat(payload_len=4096, padding_len=16):
    record_header = h2bin('18 03 02') + struct.pack("!H", payload_len + padding_len + 3)
    heartbeat_header = '\x01' + struct.pack("!H", payload_len)
    message = record_header + heartbeat_header + 'R' * payload_len + 'J' * padding_len

    return message
```

**Comment by Xe** [comment]
I doubt this is going to be fixed as the TLS Heartbeat extension was removed.

**Comment by richsalz** [comment]
The extension is not removed, but it is disabled by default.  Most sites WILL NOT enable it.  Closing this.

**Comment by grymer** [comment]
Just ran into this bug myself while preparing a heartbleed demo.
Looks like n2s (defined in ssl/ssl_locl.h), as used to unpack payload length in tls1_process_heartbeat function, assumes sizeof(int) is 2bytes. If you swap it out for n2l you may find a quick fix when building for linux-x86_64.
