### ISSUE TITLE
pkeyutl doesn't accept public keys

### ISSUE THREAD

**Issue by dotanrs** [openssl/openssl#8701]
version: 1.0.2 (according to brew)
`openssl version`: LibreSSL 2.6.4
installed via brew
Mac 10.14.1

---

According to the manual, the `pkeyutl -encrypt` command expect a public key.
However, running

`openssl pkeyutl -encrypt -in text -inkey rsakeys/public.pem`

returns

>unable to load __Private__ Key
4622231148:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/crypto/pem/pem_lib.c:683:Expecting: ANY PRIVATE KEY

This also happens if I add the flag '-pubin', and/or use `verify` instead of `encrypt`.

I couldn't find a way to properly run verify with a public key.

**Comment by bbbrumley** [comment]
> So uhmmmm, can't reproduce from your description

> LibreSSL 2.6.4

Could have something to do with it.

**Comment by levitte** [comment]
Thanks for the eye opener, @bbbrumley!

@dotanrs, we are not LibreSSL.  You will have to get in touch with them: https://www.libressl.org/
