### ISSUE TITLE
Memory leak in X509_STORE_CTX_get_by_subject

### ISSUE THREAD

**Issue by mityada** [openssl/openssl#8707]
`X509_STORE_CTX_get_by_subject` increments ref count for `X509_OBJECT`:
https://github.com/openssl/openssl/blob/bb315ca716656b7aff89f86d35988062952ccb21/crypto/x509/x509_lu.c#L320
When using custom `get_by_subject` implementation with 1.1 API this leads to a memory leak, as both `X509_OBJECT_set1_X509` and `X509_OBJECT_set1_X509_CRL` also increment ref count:
https://github.com/openssl/openssl/blob/68ca1737ce58173001f2146b913388f872842f69/crypto/x509/x509_lu.c#L439-L459

I believe `X509_STORE_CTX_get_by_subject` should not call `X509_OBJECT_up_ref_count`. 
[get_cert_by_subject](https://github.com/openssl/openssl/blob/master/crypto/x509/by_dir.c#L211) implementation (seems to be the only internal one) should be changed to increment ref count (or just call `X509_OBJECT_set1_*` functions).

**Comment by mattcaswell** [comment]
Fix and a test for this in #8708.

**Comment by levitte** [comment]
Alternatively, the documentation is simply incorrect.

I had a look at by_dir and by_file's history, and it does look like they stored everything they could find in the X509 store, and then returned on of the items in that store.  This behaviour makes complete sense if you consider the fact that the `get_by_subject` function may find more than one match, but can only return one object.

This doesn't at all support lookup methods that won't store the stuff they find anywhere, but on the other hand, we have code that *assumes* a lookup method will do exactly this.  For example, our verification code calls `X509_STORE_CTX_get1_certs` and `X509_STORE_CTX_get1_crls` to get matching certs and crls.  Here's the illuminating tid-bit:

https://github.com/openssl/openssl/blob/f2dbb71cb6bf6cd570f96e7663a22dd87854f08b/crypto/x509/x509_lu.c#L553-L557

Yup, you're seeing it right, it throws away the returned object.  And then, a few lines further down, it builds a stack of certs ('cause we're looking at `X509_STORE_CTX_get1_certs`) from the objects in the store:

https://github.com/openssl/openssl/blob/f2dbb71cb6bf6cd570f96e7663a22dd87854f08b/crypto/x509/x509_lu.c#L566-L577

With this in mind, I think we need to backtrack a little, and most certainly fix the documentation to match how things actually work.
