### ISSUE TITLE
64 Bit libraries and FIPS Compliance

### ISSUE THREAD

**Issue by akothari-github** [openssl/openssl#8711]
Hi,
We have built FIPS using openssl-fips-2.0.16.tar.gz and openssl-1.0.2r.tar.gz
for Android using the guide at https://wiki.openssl.org/index.php/FIPS_Library_and_Android

But this only works for 32 bit architectures. We are unable to build for 64 bit arch of arm64/x86.

64 bit arch libs can be build with v1.1.x but that isn't FIPS compliant.

We use SQLCipher for database encryption which internally uses OpenSSL.
Now, Google has mandated all Android apps to have 64 bit compliant libraries by end of August 2019 to be listed on the Play Store.
And as such, we have a dependency on an OpenSSL version that is FIPS compliant even on 64-bit platforms.

Is there a different guide we can use to build 64 bit arch from the existing FIPS compliant v1.0.x series?
Or is there a timeline by when an openSSL branch which has both 64 Bit support and FIPS complaince will be available?

**Comment by mspncp** [comment]
Please have a look at #8713 and let me know whether it fixes your problem.

**Comment by mspncp** [comment]
> Please have a look at #8713 and let me know whether it fixes your problem.

@akothari-github, pull request #8713 has been approved and is ready to merge, but I'd prefer to wait until I get some positive feedback from you.

**Comment by akothari-github** [comment]
Hey @mspncp , Thanks for the help. 
I'll test building this as soon as I can and let you know.

**Comment by mspncp** [comment]
> I'll test building this as soon as I can and let you know.

It would be great if you could also take the time to do some testing on the device, as described in [Testing the OpenSSL Libraries](https://wiki.openssl.org/index.php/FIPS_Library_and_Android#Testing_the_OpenSSL_Libraries).

_(Question to @openssl/committers, since I'm not familiar with OpenSSL on Android: I guess that running the `fips_hmac` binary as described in the Wiki is more or less a minimal test, it effectly just amounts to verifying that the FIPS POST succeeds, but not much more. Is there also a possibility to run a more complete testsuite on the device?)_

**Comment by mspncp** [comment]
@akothari-github do you think you will find time to test #8713 until Tuesday? Because after that I'll be on vacation an I'd like to merge the pull request before that.

**Comment by akothari-github** [comment]
Hey @mspncp, Sorry, not sure if I'll be able to test it by Tuesday as there are some other work commitments that I have to wrap up. 
Since you were able to build it, I guess we can get it merged. What do you say?

**Comment by nsjncp** [comment]
Have it tested for arm64... based on the guidelines given https://wiki.openssl.org/index.php/FIPS_Library_and_Android
![fips](https://user-images.githubusercontent.com/49711318/56270448-6d17ac00-60f6-11e9-9da0-d1f03e1b0e98.PNG)

**Comment by mspncp** [comment]
Thank you Neenu! :-)

**Comment by mspncp** [comment]
Thanks for the information. And please remind me to update  the wiki page accordingly after my vacation.

**Comment by paulidale** [comment]
@mspncp did the wiki get updated?

**Comment by mspncp** [comment]
No, not yet (even though @nsjncp reminded me as requested ;-). I had a busy week and next week I'm out of office. But I'll come back to it. This issue however is resolved, so I'm closing it.

**Comment by Santhosh-K-M** [comment]
@mspncp did the wiki get updated?

**Comment by mspncp** [comment]
Unfortunately this did not happen (yet). But I talked to my colleague @nsjncp and she is willing to send you her personal notes, if you contact us by email. 

_(You don't need to post your email address here on the website, just lookup my email address in the git commits and email me.)_
