### ISSUE TITLE
Can't load ./.rnd into RNG openssl

### ISSUE THREAD

**Issue by Lidiaaa** [openssl/openssl#8717]
Tell me how to fix the error, version 1.1.1b
OpenSSL> genrsa -out hasanova.pem -des3 -rand .rnd 4096
Can't load .rnd into RNG
14656:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto\rand\randfile.c:98:Filename=.rnd
error in genrsa

**Comment by mspncp** [comment]
@Lidiaaa did you try suggestion https://github.com/openssl/openssl/issues/7754#issuecomment-444063355?

**Comment by Lidiaaa** [comment]
@mspncp error
OpenSSL> genrsa -out hasanova.pem -des3 4096
genrsa: Can't open "hasanova.pem" for writing, Permission denied
error in genrsa

**Comment by mspncp** [comment]
The error message is very clear: You don't have permissions to write the file into your current working directory. From where did you start OpenSSL?  You either need to specify a full path to a location were you are allowed to write, or terminate and restart OpenSSL in a different working directory.

**Comment by kroeckx** [comment]
I'm not sure why you've used the -rand option. I assume the file
just doesn't exist. Did you copy this from some example somewhere?

I suggest you use something like this instead:
openssl genpkey -algorithm RSA -out key.pem -pkeyopt rsa_keygen_bits:4096 -aes-128-cbc

**Comment by Lidiaaa** [comment]
@mspncp thank you, it works
