### ISSUE TITLE
Access to curve 25519 functions

### ISSUE THREAD

**Issue by orignal** [openssl/openssl#8718]
Right now the only way to use it is EdDSA sign/verify through the EVP interface.
It works fine for EdDSA, but you might need an access to the  curve itself to implement different signature schemas over the curve or key blinding.
Ideally, it would be nice to have a functions similar to **EC_POINT_mul** and **EC_POINT_add**, but for 25519.

**Comment by mattcaswell** [comment]
> Right now the only way to use it is EdDSA sign/verify through the EVP interface.

It is also to possible to perform key derivation using X25519 via EVP.

> Ideally, it would be nice to have a functions similar to EC_POINT_mul and EC_POINT_add, but for 25519.

There are no plans for introducing such an interface. We wish to encourage people to use the higher level EVP interfaces. We are a general purpose crypto library, primarily focused on the users of crypto. Implementors of new schemes aren't really our target audience IMO. I'm reluctant to add new APIs for non-experts to shoot themselves in the foot with. We've got too much of that already.

**Comment by t8m** [comment]
So what would be the right way to get SPAKE on X25519 implemented in OpenSSL?

**Comment by mattcaswell** [comment]
I don't know anything about SPAKE so that's a difficult question to answer. If its actually using X25519 as you imply in your question (as opposed to directly using the 25519 group) then you can just use `EVP_PKEY_derive` to access it. If it needs to use 25519 group operations directly then that currently isn't supported by the public API. If its backed by an RFC (or similar standard) then we would certainly consider integrating it into the OpenSSL source.

**Comment by t8m** [comment]
It is a draft in the latest stage before publication by IETF:
https://datatracker.ietf.org/doc/draft-ietf-kitten-krb-spake-preauth/?include_text=1
Simple description is here:
http://k5wiki.kerberos.org/wiki/Projects/SPAKE_Preauthentication

So yes, it requires the group operations. The question is whether the EVP_PKEY API can accommodate it somehow or whether we would need a completely new API for that.

**Comment by orignal** [comment]
Same question for me. Group operations through the EVP API will be sufficient for me.

**Comment by richsalz** [comment]
The published policy requires mechanisms to be part of a standard.  The IETF RFC helps, but adoption helps more.  I doubt that SPAKE is a priority for anyone on the team, so a contribution that implemented this -- perhaps modelling it like key exchange? -- is probably going to be the best way forward.

**Comment by mattcaswell** [comment]
> The question is whether the EVP_PKEY API can accommodate it somehow or whether we would need a completely new API for that.

It sounds like an `EVP_PKEY_derive` operation to me.

**Comment by mattcaswell** [comment]
Closing this since there are no plans to do this.
