### ISSUE TITLE
HSM (engine) support for symmetric crypto

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [openssl/openssl#8719]
```
openssl enc -pass -K
```
currently only support providing an actual key or a password to derive a key from.
In our TPM engine, we'd like to add support for using symmetric keys that are shielded by the TPM.

Could `openssl enc` be extended to support these kinds of inputs ? Or could we "highjack" an existing parameter, as we do with the `-key -keyform` parameters for asymmetric keys ?

The corresponding PR is https://github.com/tpm2-software/tpm2-tss-engine/pull/77

Thanks a lot for any help !

**Comment by levitte** [comment]
Well, you could use `-K` to pass an identity in hex encoding (i.e. if your key identity is "FOO", you would give "-K 464F4F00"), and have the TPM2 engine pick it up in the encrypt / decrypt init routines.

I haven't really verified how workable that is, but that's at least an idea to try.

**Comment by AndreasFuchsSIT** [comment]
Thanks for the quick answer. I guess that's what we're doing already.
In addition however we also need a filename to be passed in.
The question is, how can we make this in one way or another "conformant" to the idea of openssl ?

**Comment by p-steuer** [comment]
I looked into supporting different HSMs via engines and the main problem was that libcrypto does not support key-objects for symmetric primitives ie symmetric keys are just bit-strings, not objects output by the corresponding keygen algorithm.

I didn't look into the new provider stuff .. does it support key-objects/keygen for symmetric crypto ? If so, that would be very helpful for HSM support.

**Comment by levitte** [comment]
The new provider doesn't *currently* have key object functionality, but both @mattcaswell and I have that in mind.

**Comment by mattcaswell** [comment]
Yes, @levitte says I fully intend to implement that - but it may be a while before I get to it. There's lots of other "plumbing" to be done for the new architecture first.

**Comment by p-steuer** [comment]
Sounds good. I definitely have to read the architecture and design docs.

**Comment by p-steuer** [comment]
Enabling HSM support for symmetric crypto is actually a part of the following effort: https://github.com/openssl/openssl/issues/10265

**Comment by t8m** [comment]
Symmetric crypto provided by an external implementation is supported via the providers API now.
