### ISSUE TITLE
How do I add a new custom API to openssl？

### ISSUE THREAD

**Issue by ChampOnBon** [openssl/openssl#8723]
I wrote a new API in ssl_lib.c, SSL_set_fd_rcv_msg, and added a declaration in include/openssl/ssl.h.Then execute "make update "and "make" to generate the libssl.so file. But then I tried "nm-D libssl.so | grep SSL_set_fd_rcv_msg" and couldn't find the API. What should I do？

**Comment by ChampOnBon** [comment]
I manually added “SSL_set_fd_rcv_msg 5000 1_1_0 NOEXIST::FUNCTION:” to the libssl.num file. The new API is still not found after compilation. The version is 1.1.1b.

**Comment by levitte** [comment]
You shouldn't have to add anything manually to util/libssl.num, `make update` should do that for you. "NOEXIST" will make it not exported as well, it should be "EXIST"

**Comment by mattcaswell** [comment]
If `make update` isn't automatically updating libssl.num then you've done something wrong somewhere...it should just pick it up automatically from the ssl.h file.

**Comment by ChampOnBon** [comment]
I added //#define SSL_SET_FD_RCV_MSG to the top of the API, which caused the make update to fail because it was needed in openssl1.0.2l. Now my problem is solved.Thank you.
