### ISSUE TITLE
AIX: BIGNUM check issue

### ISSUE THREAD

**Issue by flynn1973** [openssl/openssl#8724]
AIX 7,1 on Power9 Processors

I check the RSA public exponent to ensure it's odd.  it insists that RSA->e is even but apparrently its not.

test code: 
````
#include <stdio.h>
#include <openssl/pem.h>

#include <openssl/err.h>                                        /* ERR_* */
#include <openssl/rand.h>                                       /* RAND_* */
#include <openssl/bn.h>                                         /* BN_* */


int get_key(const unsigned char *buf, int len) {
    RSA *rsa = d2i_RSA_PUBKEY(NULL, &buf, len);
    if (rsa != NULL) {
        if (rsa->e != NULL) {
            printf("BN : <%s> (hex) -- <%s> (dec)\n", BN_bn2hex(rsa->e), BN_bn2dec(rsa->e));
            if (BN_is_odd(rsa->e) == 0) {
                printf("Error : RSA public exponent is even\n");
            } else {
                printf("RSA public exponent is OK.\n");
                return 0;
            }
        }
        RSA_free(rsa);
    } else {
        printf("Error : RSA is NULL\n");
    }
    return 1;
}

int main() {
    const unsigned char data[] = { 0x30, 0x81, 0x9f, 0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01, 0x05, 0x00, 0x03, 0x81, 0x8d, 0x00, 0x30, 0x81, 0x89, 0x02, 0x81, 0x81, 0x00, 0xd6, 0x70, 0x5d, 0x67, 0xf2, 0xe1, 0x34, 0x82, 0xd5, 0x2d, 0x79, 0xdd, 0x42, 0x55, 0x41, 0xaf, 0x0c, 0xc2, 0xb4, 0xb0, 0x94, 0xc6, 0xa0, 0x40, 0x54, 0x2e, 0x0f, 0xa5, 0x12, 0x3d, 0x43, 0x96, 0x13, 0x2d, 0x17, 0x50, 0xe5, 0x9a, 0x5a, 0x6e, 0x99, 0xc7, 0xd2, 0x63, 0x4c, 0xcd, 0x57, 0xcb, 0x57, 0x7e, 0x1e, 0x5f, 0x97, 0xaa, 0xbd, 0xe5, 0xc0, 0x98, 0xd9, 0x07, 0x52, 0xdc, 0x27, 0xa4, 0x19, 0xb2, 0x81, 0x5d, 0xd5, 0x03, 0x5c, 0xd2, 0xb3, 0xb8, 0x28, 0xaa, 0xd7, 0xaf, 0x02, 0x08, 0x1c, 0x6c, 0xc2, 0xa4, 0x6c, 0x41, 0xd3, 0xa6, 0xae, 0x51, 0x69, 0xb7, 0xd5, 0x79, 0xb8, 0x62, 0x68, 0x9e, 0xa9, 0x44, 0x8e, 0xbe, 0xb1, 0x2e, 0x1a, 0x3c, 0x4b, 0x21, 0x7b, 0x7d, 0x36, 0xf0, 0x97, 0x98, 0x81, 0x63, 0xa6, 0xfa, 0xf8, 0x28, 0x22, 0x72, 0xfe, 0x16, 0xa8, 0x16, 0x89, 0xbb, 0x02, 0x03, 0x01, 0x00, 0x01 }; /* A DER buffer, valid with openssl rsa -pubin -in <file> -inform DER */
    return get_key(data, sizeof data);
}
````
aix compile string: gcc -maix64 -lcrypto -o openssl_odd_even openssl_odd_even.c
linux compile string: gcc  -lcrypto -o openssl_odd_even openssl_odd_even.c

aix results (64bit, BIG Endian):

````
packagebuilder@aixbuildhostng: /home/packagebuilder/test # ./openssl_odd_even
BN : <010001> (hex) -- <65537> (dec)
Error : RSA public exponent is even
````
linux ppc64le results 64bit, LITTLE Endian:

````
root@lpgaixmgmtlx01:/root>./openssl_odd_even
BN : <010001> (hex) -- <65537> (dec)
RSA public exponent is OK.
````

to make this even more annoying, this problem only comes up in 64bit, 32bit compiles works flawless in aix.
````
packagebuilder@aixbuildhostng: /home/packagebuilder/test # gcc -maix32 -lcrypto -o openssl_odd_even openssl_odd_even.c
packagebuilder@aixbuildhostng: /home/packagebuilder/test # ./openssl_odd_even
BN : <010001> (hex) -- <65537> (dec)
RSA public exponent is OK.
packagebuilder@aixbuildhostng: /home/packagebuilder/test # file openssl_odd_even
openssl_odd_even: executable (RISC System/6000 V3.1) or obj module not stripped
````

this was tested with openssl OpenSSL 1.0.2p but i checked older and newer versions with same error.

see related discussion on the cfengine group...

https://groups.google.com/forum/#!topic/help-cfengine/-hmnIz0fA4Q

**Comment by bernd-edlinger** [comment]
how did you configure openssl?
did you try to use no-asm and/or disable optimizations?

**Comment by bernd-edlinger** [comment]
I wonder how you can access "rsa->e" in your sample code, since the RSA structure
is opaque, you must be using wrong header files, the RSA object is different
than in 1.0.2 so you simply do not access "e" but something completely different.

**Comment by flynn1973** [comment]
there is only one openssl distribution installed, and there is only one set of headers. this openssl package is built and delivered by ibm with the aix operating system. so ne wrong headers or self built openssl.

**Comment by bernd-edlinger** [comment]
Okay, but BN_is_odd is a 1-line function, it is hard to imagine any other possibility than a compiler bug.
We can only help if you compile openssl out of the source tar ball.

**Comment by flynn1973** [comment]
i already filed a bug report with ibm, quite curious what they have to say about this. fact is BN_is_odd works inversed in aix, not matter if i compile with gcc or ibm's xlc compiler, and this error only shows up in 64bit mode. i doubt this is just a compiler bug honestly.
will report back after i hear something from ibm.

**Comment by flynn1973** [comment]
i just wanted let you guys know that ibm found the culprit and fixed their openssl package. 

````
A. OpenSSL 1.0.2.1800 version contains the following fixes as part of this release :
- TS002131610: RSA keys not properly generated in 64-bit library
````

**Comment by sayrer** [comment]
hey, what does this actually mean? Is OpenSSL from Githubi insecure on 64-bit IBM machines?

**Comment by sayrer** [comment]
hey, what does this actually mean? Is OpenSSL from Github insecure on 64-bit IBM machines?

I don't see an open source patch referenced.

**Comment by flynn1973** [comment]
this whole story is about the ibm deliverd aix openssl package, but it stands to reason that this bug exits in uptream too.
