### ISSUE TITLE
Why is BoringSSL a submodule of OpenSSL?

### ISSUE THREAD

**Issue by JonasVautherin** [openssl/openssl#8725]
That's mainly out of curiosity, I could not figure out by looking at the project myself.

**Comment by mattcaswell** [comment]
We have an option to run the boringssl test suite against OpenSSL. See:

https://github.com/openssl/openssl/blob/master/test/README.external

**Comment by Ecordonnier** [comment]
The file was moved to https://github.com/openssl/openssl/blob/master/test/README-external.md
