### ISSUE TITLE
"TLSv1_server_method" was declared "deprecated" when using openssl1.1.1b build for Linux-x86 build

### ISSUE THREAD

**Issue by kyadav78** [openssl/openssl#8726]
Hi,
  I have compiled the openssl1.1.1b target for linux-x86 and then building my c++ project on linux system  i am getting below errors. 
````
: function "TLSv1_server_method" (declared at line 1878 of "../../../../ExternalLibs/openssl-1.1.1b/include/openssl/ssl.h") was declared "deprecated"
      m_pSecureSocket.reset(new CSecureSocket(TLSv1_server_method(),pSocket, pSocketSec->GetCtx()));
error: no instance of constructor "CSecureSocket::CSecureSocket" matches the argument list
            argument types are: (const SSL_METHOD *, ISocketWrapper *, SSL_CTX *)
      m_pSecureSocket.reset(new CSecureSocket(TLSv1_server_method(),pSocket, pSocketSec->GetCtx()));
 undefined reference to `CRYPTO_num_locks'
: undefined reference to `OpenSSL_add_all_digests'
: undefined reference to `ERR_load_crypto_strings'
: undefined reference to `CRYPTO_set_id_callback'
: undefined reference to `CRYPTO_set_locking_callback
undefined reference to `curl_global_init'
undefined reference to `curl_easy_setopt'
 undefined reference to `curl_easy_perform'
 undefined reference to `curl_easy_cleanup'
 undefined reference to `curl_global_cleanup'
undefined reference to `SSL_library_init'
undefined reference to `SSL_load_error_strings'
 undefined reference to `getauxval@GLIBC_2.16'
 undefined reference to `clock_gettime@GLIBC_2.17'
 undefined reference to `secure_getenv@GLIBC_2.17'
 undefined reference to `__fread_chk@GLIBC_2.7'
 undefined reference to `__isoc99_sscanf@GLIBC_2.7'
 undefined reference to `__stack_chk_fail@GLIBC_2.4'
 undefined reference to `__syslog_chk@GLIBC_2.4'
````

Could you please in solving these errors?

Regards
Kunal

**Comment by mattcaswell** [comment]
````
: function "TLSv1_server_method" (declared at line 1878 of "../../../../ExternalLibs/openssl-1.1.1b/include/openssl/ssl.h") was declared "deprecated"
````
Using that function was deprecated from OpenSSL 1.1.0 onwards. It shouldn't actually cause builds to fail since its still available. This is just a warning (unless of course the compile flags for your project are set to fail on warnings). However it is still good practice to fix this. `TLSv1_server_method` will only *ever* negotiate TLSv1.0 which is almost certainly not want you want. The preferred alternative is to use `TLS_server_method` which is the version flexible alternative, i.e. any supported version of TLS will be negotiated.

These errors:
````
undefined reference to `CRYPTO_num_locks'
: undefined reference to `OpenSSL_add_all_digests'
: undefined reference to `ERR_load_crypto_strings'
: undefined reference to `CRYPTO_set_id_callback'
: undefined reference to `CRYPTO_set_locking_callback
undefined reference to `SSL_library_init'
undefined reference to `SSL_load_error_strings'
````
appear to be linker errors. The above symbols were real symbols in OpenSSL 1.0.2, but in 1.1.0+ they are macros so they no longer exist in the library. It looks to me like something you are linking with was compiled against 1.0.2 and is expecting symbols that are no longer present in the new version. Whatever that is needs to be recompiled and updated to use OpenSSL 1.1.1.

The other errors don't appear to be OpenSSL specific problems.

**Comment by kyadav78** [comment]
Hi,
  Thank you for your response , it really helped in fixing some errors still i am getting below errors:
openssl1.1.1b/libcrypto.so: undefined reference to `getauxval@GLIBC_2.16'
openssl1.1.1b/libcrypto.so: undefined reference to `clock_gettime@GLIBC_2.17'
openssl1.1.1b/libcrypto.so: undefined reference to `secure_getenv@GLIBC_2.17'
openssl1.1.1b/libcrypto.so: undefined reference to `__fread_chk@GLIBC_2.7'
openssl1.1.1b/libcrypto.so: undefined reference to `__isoc99_sscanf@GLIBC_2.7'
openssl1.1.1b/libssl.so: undefined reference to `__stack_chk_fail@GLIBC_2.4'
openssl1.1.1b/libcrypto.so: undefined reference to `__syslog_chk@GLIBC_2.4'

Please suggest, Below are the steps while building openssl1.11b target for linux-x86:
linux machine(it is 64-bit) used:
% uname -a
Linux balusr09 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

step 1.Copied the openssl1.1.b tar file in the linux server .
step2. extracted the tar file.
step3. executed "./Configure linux-x86  shared enable-crypto-mdebug 
step4. make

Regards
Kunal

**Comment by mattcaswell** [comment]
````
openssl1.1.1b/libcrypto.so: undefined reference to getauxval@GLIBC_2.16' openssl1.1.1b/libcrypto.so: undefined reference to clock_gettime@GLIBC_2.17'
openssl1.1.1b/libcrypto.so: undefined reference to secure_getenv@GLIBC_2.17' openssl1.1.1b/libcrypto.so: undefined reference to __fread_chk@GLIBC_2.7'
openssl1.1.1b/libcrypto.so: undefined reference to __isoc99_sscanf@GLIBC_2.7' openssl1.1.1b/libssl.so: undefined reference to __stack_chk_fail@GLIBC_2.4'
openssl1.1.1b/libcrypto.so: undefined reference to `__syslog_chk@GLIBC_2.4'
````
Well these are clearly GLIBC symbols, which looks to be something environmental on your system (unrelated to OpenSSL itself). Perhaps a mismatch between the glibc headers and libraries?

**Comment by mattcaswell** [comment]
This doesn't seem to be an OpenSSL issue any more so closing.

**Comment by jacky-xi** [comment]
Hi,
when my client uses 'TLS_server_method' to connect server,everything is ok; but when my client uses 'TLSv1_method ( )‘ to connect server,there is error "40A7BDBC2A7F0000:error:0A000438:SSL routines:(unknown function):tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1586:SSL alert number 80"; I know that 'TLSv1_method ( )‘ has been deprecated and I am using OpenSSL 3.0.3 ,but is there any way to connect server using deprecated function?

**Comment by mattcaswell** [comment]
@jacky-xi - please raise a new issue for this, rather than commenting in a long closed old issue.
