### ISSUE TITLE
`ssl.so` not depend on`crypto.so` and contain  `crypto.so`

### ISSUE THREAD

**Issue by oncealong** [openssl/openssl#8732]
build issues, OpenSSL 1.1.1.
My Android app contain curl and ffmpeg, both them need openssl. To avoid duplicate code,  I link them with libcrypto.so and libssl.so.   
When test in an Android 4.2 machine, I found the app load libcrypto.so from `/system/lib`, not from my prebuild libcrypto.so(Android 4.2 buildin libcrypto version is too low and don't have need function).
In short, the app use the Android system buildin libcrypto.so/libssl.so,  not from my custom build.
![image](https://user-images.githubusercontent.com/5340073/56011322-ad9fb000-5d19-11e9-868d-c2dbd26ee822.png)

To avoid this, I dedice to rename libcrypto.so  to libcrypto.arm.so, so the App will load the exact libcrypto.arm.so. I custom the conf file like below: 
```
    "mycustom-android-arm" => {
        inherit_from     => [ "android-arm"],
        shared_extension => ".arm.so",
    },
```
But I found that libssl.arm.so not depend on libcrypto.arm.so, and libssl.arm.so contains all code from libcrypto.arm.so.
![image](https://user-images.githubusercontent.com/5340073/56011681-54388080-5d1b-11e9-9273-537e9edf0d18.png)

I want to know is it normal ? or how to edit `conf` that let ssl depend on crypto.

Tks.

[configdata.log](https://github.com/openssl/openssl/files/3071495/configdata.log)
[build-log.log](https://github.com/openssl/openssl/files/3071496/build-log.log)
[15-custom-so-suffix-android.log](https://github.com/openssl/openssl/files/3071497/15-custom-so-suffix-android.log)

**Comment by levitte** [comment]
The build log you have attached is before the change, right?  I can't see it building libssl.so with libcrypto inside (which you "after" picture seems to indicate)

**Comment by oncealong** [comment]
> The build log you have attached is before the change, right? I can't see it building libssl.so with libcrypto inside (which you "after" picture seems to indicate)

----
Sorry, my mistake.
[configdata-arm.so.log](https://github.com/openssl/openssl/files/3075722/configdata-arm.so.log)
[build-log-arm.so.log](https://github.com/openssl/openssl/files/3075723/build-log-arm.so.log)

And I finally build with conf like below, this build libssl.1.1.so and libcrypto.1.1.so that looks ok.
```
"mycustom-android-arm" => {
        inherit_from     => [ "android-arm"],
        shared_extension => ".\$(SHLIB_VERSION_NUMBER).so",
    },
```
![image](https://user-images.githubusercontent.com/5340073/56074588-eb6b0a00-5de7-11e9-997c-224549ee649d.png)

--------Something about libssl.arm.so and curl---------------------

Additional, when I link curl with  libssl.arm.so, curl report function `HMAC_Update` not found, but I use objdump, `HMAC_Update` is found.
```
➜  openssl-armeabi-v7a git:(v4.1) ✗ $ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/arm-linux-androideabi/bin/objdump -tT libssl.arm.so | grep HMAC_Update
00093054 l     F .text	00000018              HMAC_Update
```
then I use curl testsample and found compiler error.
compile command like:
```
toolchain/bin/arm-linux-androideabi-clang -o conftest -Qunused-arguments -g -pedantic -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wfloat-equal -Wno-multichar -Wsign-compare -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wcast-align -Wno-system-headers -Wshorten-64-to-32 -Wunused -Wvla -Wshift-sign-overflow -Wmissing-variable-declarations -Wdouble-promotion -Wcomma -O3 -Wall -pipe -std=c99 -ffast-math -fstrict-aliasing -Werror=strict-aliasing -Wa,--noexecstack -DANDROID -DNDEBUG -isystem openssl/include -march=armv7-a -mcpu=cortex-a8 -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb    -L/openssl/bin/Android/openssl-armeabi-v7a  -Wl,--fix-cortex-a8   conftest.c -lcrypto  -lz
```
testsample:
```
/* confdefs.h */
#define PACKAGE_NAME "curl"
#define PACKAGE_TARNAME "curl"
#define PACKAGE_VERSION "-"
#define PACKAGE_STRING "curl -"
#define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.haxx.se/mail/"
#define PACKAGE_URL ""
#define DEBUGBUILD 1
#define CURLDEBUG 1
#define PACKAGE "curl"
#define VERSION "-"
#define OS "arm-unknown-linux-androideabi"
#define _FILE_OFFSET_BITS 64
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_BUILTIN_AVAILABLE 1
#define CURL_DISABLE_FTP 1
#define CURL_DISABLE_FILE 1
#define CURL_DISABLE_LDAP 1
#define CURL_DISABLE_LDAPS 1
#define CURL_DISABLE_RTSP 1
#define CURL_DISABLE_DICT 1
#define CURL_DISABLE_TELNET 1
#define CURL_DISABLE_TFTP 1
#define CURL_DISABLE_POP3 1
#define CURL_DISABLE_IMAP 1
#define CURL_DISABLE_SMB 1
#define CURL_DISABLE_SMTP 1
#define CURL_DISABLE_GOPHER 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME_H 1
#define HAVE_CLOCK_GETTIME_MONOTONIC 1
#define HAVE_ZLIB_H 1
#define HAVE_LIBZ 1
#define HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID 1
/* end confdefs.h.  */

#ifdef __cplusplus
extern "C" 
#endif
char    HMAC_Update();  
int main(void)
{
    return HMAC_Update();
    return 0;
}
```

Finally is my arm.so,  if you are interesting , you could download it and rename to `libcrypto.arm.so` and `libssl.arm.so`.
[libcrypto.arm.log](https://github.com/openssl/openssl/files/3075736/libcrypto.arm.log)
[libssl.arm.log](https://github.com/openssl/openssl/files/3075737/libssl.arm.log)

**Comment by levitte** [comment]
Ah, of course, that's why libssl.arm.so includes libcrypto instead of linking with libcrypto.arm.so:

```
arm-linux-androideabi-clang {flags flags flags} -o libssl.arm.so -Wl,--version-script=libssl.map {bunch of object files} -lcrypto -ldl -pthread
```

`-lcrypto` will naturally look for `libcrypto.so`, and when not found, `libcrypto.a`.

However, what I suddenly remember is that we have better support for "variant" library names, with the config attribute `shlib_variant`.  So try this:

``` perl
    "mycustom-android-arm" => {
        inherit_from     => [ "android-arm"],
        shlib_variant => ".arm",
    },
```

The variant string gets inserted just before the ".so" extension.
