### ISSUE TITLE
FIPS module in build with -z defs

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#8735]
It seems that when you configure with no-shared, it's still creating a fips.so file.

**Comment by kroeckx** [comment]
There is also a p_test.so and legacy.so

**Comment by mattcaswell** [comment]
Well, its a design decision that the fips module will only ever be in a .so form. And I'm also not sure it follows that just because you want the static libraries for libcrypto/libssl that you don't want to use fips. You can of course independently turn off building of the fips module with "no-fips". The legacy library is another issue - I suppose you may want the option for that to be static and just part of libcrypto - although that's not possible right at the moment.

**Comment by kroeckx** [comment]
So the issue is not that we generate the shared library itself. It seems that when making the shared library, but that we pass `-z defs`, and that that works with gcc but not with clang. We don't pass it for the other shared libraries.

**Comment by kroeckx** [comment]
So it seems that gcc properly links in the asan library, clang doesn't.

**Comment by kroeckx** [comment]
It seems we can fix this with adding -lasan

**Comment by paulidale** [comment]
I think it would be sensible to allow any provider (except FIPS) to be statically linked into libcrypto.

**Comment by levitte** [comment]
Alternative fix in #8749

**Comment by kroeckx** [comment]
This issue is not fixed. OSS-Fuzz doesn't use the enable-asan option and things like that, it just adds it to the CFLAGS.

**Comment by levitte** [comment]
Can OSS-Fuzz be changed to use the `enable-asan` option?

**Comment by kroeckx** [comment]
No. But they use the enable-fuzz-libfuzzer option.

**Comment by levitte** [comment]
So let me see if I get this right, they configure in a way that makes it harder for us to detect that they enable asan, when there's an option for them to use that makes everyone happy (I assume), and now you're hinting that we should kinda piggy-back enable-asan *on a different, unrelated option*?

This is screwed up...

**Comment by levitte** [comment]
I went looking, and yeah, I get how that's hard to fix.  Meh...

**Comment by levitte** [comment]
#8778 is my attempt to fix this

**Comment by kroeckx** [comment]
Please note that this is a general framework to do fuzzing. They
set the correct cflags so that the compiler instruments the code
for fuzzing. They also have different builds, with asan, with
ubsan, and so just set additional cflags. We're not being told
that it's msan they want to do, just that they want to fuzz and
some cflags.

It currently already has code that does:
if [[ $CFLAGS = *sanitize=memory* ]]
then
  CONFIGURE_FLAGS="no-asm"
fi

You can turn that into enable-msan if you really want to, but I
don't see the point. If you want we can add some additional config
arument that disables the -z defs.

Note that there are also other projects fuzz projects that want to
link against openssl, they have the same problem that they can't
link openssl, and they do not use something like
enable-fuzz-libfuzzer. The only way to detect it there is that it
has some -fsanitize=foo as part of the config call.

So I think there are only 2 solutions:
- Detect the sanitizer based on the cflags, and use that to
  disable -z defs
- Add a new config option to disable -z defs

**Comment by levitte** [comment]
> You can turn that into enable-msan if you really want to, but I don't see the point. If you want we can add some additional config arument that disables the -z defs.

That's exactly the purpose with my translating `-fsanitize=memory` to `enable-msan`.  Note this:

https://github.com/openssl/openssl/blob/ad7e17dd6c8a3931da0fa9a06e80cf498278ef27/Configurations/shared-info.pl#L35-L38

In other words, the *addition* of `-z defs` is only made if `msan` hasn't been enabled.

**Comment by kroeckx** [comment]
This issue is still not solved.

**Comment by levitte** [comment]
Please show me an actual configuration so I have a chance to try and reproduce.

**Comment by kroeckx** [comment]
Here is a link to the latest log: https://oss-fuzz-build-logs.storage.googleapis.com/log-989a654e-97eb-4596-8232-8be66963441f.txt

You can find the recent logs on https://oss-fuzz-build-logs.storage.googleapis.com/index.html

**Comment by levitte** [comment]
Ah, yeah I see what happens, the processing order in Configure isn't quite right, the shared-info.pl data is processed too early, before the state of asan, msan and ubsan has been determined.

I'll fix when I'm more awake

**Comment by levitte** [comment]
I hope that #8846 fixed things well enough...  I forgot to place a "Fixes #8735" in that one, unfortunately.

**Comment by kroeckx** [comment]
Just in case it wasn't clear, this is still a problem.

**Comment by levitte** [comment]
I hope #8892 finally fixes this mess

**Comment by kroeckx** [comment]
It doesn't.

**Comment by kroeckx** [comment]
Never mind, that's still a log that didn't have that commit.
