### ISSUE TITLE
Gradually rewrite this library in Rust

### ISSUE THREAD

**Issue by sayrer** [openssl/openssl#8738]
The C programming language provides inadequate security guarantees, and no advantages over Rust, with the possible exception of support for platforms that will never upgrade to the next OpenSSL release.

**Comment by sayrer** [comment]
Maybe the best way to evaluate this issue would be to look at past OpenSSL vulnerabilities and see which ones Rust would mitigate.

Writing cryptography software is difficult, and C would have been a reasonable choice to provide this service in the past. It's fair to revisit that decision now. though.

**Comment by kroeckx** [comment]
I don't think this is something we want to do at this time. The
platforms supported by rust is a much smaller list than what we
support currently. And that is going to be a problem for any other
language than C, because nothing comes close to the portability of C.

**Comment by richsalz** [comment]
OpenSSL isn't stopping anyone from writing a rust crypto library.  See *ring* for example.  I think this should be closed.

**Comment by Darkspirit** [comment]
See https://github.com/mesalock-linux/mesalink

**Comment by sayrer** [comment]
> because nothing comes close to the portability of C.

I agree that it compiles on a lot of platforms.

https://github.com/openssl/openssl/issues/8724
