### ISSUE TITLE
Configure openssl bin path

### ISSUE THREAD

**Issue by insoluzioni** [openssl/openssl#8746]
Maybe you could write it in the documentation, where is the system path and where you should change if the path is not that.

I'm running on Windows, and openssl defaults the installation to C:\Program Files\OpenSLL-blahblah. So it couldn't be found and was returning ENOENT.

Perhaps if you append a variable to package.json such as "opensslPath" for example, so first time users can configure it. Workaround was editing 'index.js'

**Comment by mattcaswell** [comment]
This does seem to be documented already in NOTES.WIN:

https://github.com/openssl/openssl/blob/f2dbb71cb6bf6cd570f96e7663a22dd87854f08b/NOTES.WIN#L57-L84

As to package.json that appears to be Node.js (?) thing which is nothing to do with OpenSSL itself and not part of the OpenSSL distribution.

**Comment by levitte** [comment]
The VMS build file actually outputs some text at the end of the full installation, something like this:

```

######################################################################

Installation complete

Run @SYS$COMMON:[OPENSSL.SYSTARTUP]openssl_startup3 to set up logical names
then run @SYS$COMMON:[OPENSSL.SYSTARTUP]openssl_utils3 to define commands

```

(there's a different variant for when DESTDIR is defined)

Perhaps Windows should have something similar?

**Comment by mattcaswell** [comment]
Does not seem to be an OpenSSL issue so closing.

**Comment by insoluzioni** [comment]
Sorry guys, the problem is with npm package: node-openssl-cert
