### ISSUE TITLE
Generate sm2‘key command

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [openssl/openssl#8748]
I hope to provide sm2 command functions, such as 'genrsa'.

**Comment by levitte** [comment]
There is a `genpkey` command

**Comment by aixiaoxiaoyu** [comment]
> There is a `genpkey` command

Just EC, not SM2

**Comment by mattcaswell** [comment]
SM2 keys are encoded as normal EC keys. You can generate an SM2 key like this:

````
$ openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2 -out sm2key.pem
````
And it can be viewed like this:
````
$ openssl ec -in sm2key.pem -noout -text
read EC key
Private-Key: (256 bit)
priv:
    76:4a:a3:1f:3c:0c:e9:7a:43:bc:99:bc:32:af:a1:
    a7:00:d1:16:0e:d6:53:15:08:58:42:63:66:fc:73:
    b1:3d
pub:
    04:a4:49:c8:a7:d2:45:d8:87:2c:34:5a:19:b5:e8:
    6a:1f:15:34:8a:73:d0:6c:7f:f3:49:9b:6a:93:4b:
    0e:0c:13:6e:fb:25:c0:80:5e:3b:70:e6:12:55:ce:
    4f:75:a7:95:86:13:9e:10:dc:73:c4:27:5c:85:aa:
    e1:2c:b3:b5:9c
ASN1 OID: SM2
````
There are some edge cases which, in theory, can cause problems with this (see #8435). But in practice you're unlikely to run into that as an issue.

**Comment by aixiaoxiaoyu** [comment]
> SM2 keys are encoded as normal EC keys. You can generate an SM2 key like this:
> 
> ```
> $ openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2 -out sm2key.pem
> ```
> And it can be viewed like this:
> 
> ```
> $ openssl ec -in sm2key.pem -noout -text
> read EC key
> Private-Key: (256 bit)
> priv:
>     76:4a:a3:1f:3c:0c:e9:7a:43:bc:99:bc:32:af:a1:
>     a7:00:d1:16:0e:d6:53:15:08:58:42:63:66:fc:73:
>     b1:3d
> pub:
>     04:a4:49:c8:a7:d2:45:d8:87:2c:34:5a:19:b5:e8:
>     6a:1f:15:34:8a:73:d0:6c:7f:f3:49:9b:6a:93:4b:
>     0e:0c:13:6e:fb:25:c0:80:5e:3b:70:e6:12:55:ce:
>     4f:75:a7:95:86:13:9e:10:dc:73:c4:27:5c:85:aa:
>     e1:2c:b3:b5:9c
> ASN1 OID: SM2
> ```
> There are some edge cases which, in theory, can cause problems with this (see #8435). But in practice you're unlikely to run into that as an issue.

Thank you !But I think using SM2 is more appropriate than using EC.

**Comment by aixiaoxiaoyu** [comment]
> SM2 keys are encoded as normal EC keys. You can generate an SM2 key like this:
> 
> ```
> $ openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2 -out sm2key.pem
> ```
> And it can be viewed like this:
> 
> ```
> $ openssl ec -in sm2key.pem -noout -text
> read EC key
> Private-Key: (256 bit)
> priv:
>     76:4a:a3:1f:3c:0c:e9:7a:43:bc:99:bc:32:af:a1:
>     a7:00:d1:16:0e:d6:53:15:08:58:42:63:66:fc:73:
>     b1:3d
> pub:
>     04:a4:49:c8:a7:d2:45:d8:87:2c:34:5a:19:b5:e8:
>     6a:1f:15:34:8a:73:d0:6c:7f:f3:49:9b:6a:93:4b:
>     0e:0c:13:6e:fb:25:c0:80:5e:3b:70:e6:12:55:ce:
>     4f:75:a7:95:86:13:9e:10:dc:73:c4:27:5c:85:aa:
>     e1:2c:b3:b5:9c
> ASN1 OID: SM2
> ```
> There are some edge cases which, in theory, can cause problems with this (see #8435). But in practice you're unlikely to run into that as an issue.

Thank you ! But I think using SM2 is more appropriate than using EC.

**Comment by mattcaswell** [comment]
SM2 keys are defined at a *specification* level to be encoded as EC keys - so this makes a lot of sense. Currently there is no separate set of functions internally for generating SM2 keys versus normal EC keys. However the solution to #8435 is likely to be a dedicated set of functions for generating SM2 keys independently of EC - so it seems likely that in the long run genpkey will also have a separate SM2 algorithm name. Until that happens though you should use EC.

**Comment by mattcaswell** [comment]
Closing this, since I think #8435 is the better place to track this issue.
