### ISSUE TITLE
openssl s_server -cert server.crt -key server.key -CAfile rootCA.pem -accept 2502 -www Enter pass phrase for server.key: Error setting EC curve   

### ISSUE THREAD

**Issue by gopinatharjuan** [openssl/openssl#8751]

**Comment by gopinatharjuan** [comment]
We are receiving above error to bye pass we used -no_ecdh then came to accept mode So kindly advice how to handle in c program to skip/off the ECDH

**Comment by mattcaswell** [comment]
As noted in #3303 this is a bug in 1.0.2 that is fixed in recent versions. Since 1.0.2 is in security-fix only mode this won't be fixed.
