### ISSUE TITLE
strictpem option causes double free

### ISSUE THREAD

**Issue by AnnieYousar** [openssl/openssl#8752]
Given a ec key (pubkey.pem):
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4UjRHO7Qb2fwTB3od0CTtPdd1sQy
CSJ8oB0PVNojUgi1IsJjr4voczYPHFaUkeVNm0tNXTDr23ks757jLGB0dw==
-----END PUBLIC KEY-----
```
then strictpem option causes a core dump. 
Check `openssl asn1parse -in pubkey.pem -strparse 2` which is fine:
```
    0:d=0  hl=2 l=  19 cons: SEQUENCE
    2:d=1  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   11:d=1  hl=2 l=   8 prim: OBJECT            :prime256v1
```
whereas `openssl asn1parse -in pubkey.pem -strparse 2 -strictpem` is broken:
```
openssl asn1parse -in pubkey.pem -strparse 2 -strictpem
    0:d=0  hl=2 l=  19 cons: SEQUENCE
    2:d=1  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   11:d=1  hl=2 l=   8 prim: OBJECT            :prime256v1
Aborted (core dumped)
```
Applies to OpenSSL 1.1.0 as well as to OpenSSL 1.1.1

**Comment by mspncp** [comment]
> Applies to OpenSSL 1.1.0 as well as to OpenSSL 1.1.1

I doubt that this issue will be fixed for OpenSSL 1.1.0, because it is EOL in 2019-09-11 and in security fix only mode.

**Comment by levitte** [comment]
I did look, and the cause is a reuse of `str` when using `-strparse`...  So that's the actual culprit rather than `strictpem`

**Comment by levitte** [comment]
Or no, it's rather that `str` points at data that's already held by `buf`, which is freed first...

**Comment by mspncp** [comment]
> Or no, it's rather that `str` points at data that's already held by `buf`, which is freed first...

Well then, [go get em tiger!](https://www.youtube.com/watch?v=xc5UgsiqcOo)

**Comment by AnnieYousar** [comment]
> 
> 
> Or no, it's rather that `str` points at data that's already held by `buf`, which is freed first...
`openssl asn1parse -in pubkey.pem -strictpem` or even 
`openssl asn1parse -in pubkey.pem -strictpem -offset 2 -length 21`
works fine.

**Comment by levitte** [comment]
It's actually the combo `-strparse` and `-strictpem`

**Comment by levitte** [comment]
You're in a particularly good mood today, @mspncp :wink:

**Comment by levitte** [comment]
#8753, please try it out

**Comment by AnnieYousar** [comment]
Done. Thanks. Issue fixed.
```
openssl asn1parse -in pubkey.pem -strictpem -strparse 2
    0:d=0  hl=2 l=  19 cons: SEQUENCE
    2:d=1  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   11:d=1  hl=2 l=   8 prim: OBJECT            :prime256v1
```

**Comment by mspncp** [comment]
> You're in a particularly good mood today, @mspncp

More than usual? ;-)

> #8753, please try it out

At the moment, I'm too occupied with other business, so I won't be able to look at it before this evening or tomorrow.
