### ISSUE TITLE
sm2_encrypt no maual pages

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [openssl/openssl#8754]
![image](https://user-images.githubusercontent.com/14014477/56135491-72c0a500-5fc3-11e9-841f-6a9c05bf874b.png)

**Comment by bbbrumley** [comment]
`sm2_encrypt` is an internal function. It doen't require a `man` entry.

**Comment by InfoHunter** [comment]
Right, use `EVP_PKEY_encrypt` instead.
