### ISSUE TITLE
How to bypass installation of manual pages?

### ISSUE THREAD

**Issue by kuvaldini** [openssl/openssl#8757]
I need to `make install` without manual pages which are useless on target device.

**Comment by mattcaswell** [comment]
See the INSTALL file for documentation on this:

https://github.com/openssl/openssl/blob/72eb100f8a38c5b3822d7751eddaa2f3f4576fa1/INSTALL#L1116-L1130

Although I just noticed that it could do with an update since there is also `install_ssldirs` (for installing things like the config file etc).

**Comment by kuvaldini** [comment]
@mattcaswell  Thank you a lot!

**Comment by kuvaldini** [comment]
```
make: *** No rule to make target 'install_ssldirs'.  Stop.
```

**Comment by mattcaswell** [comment]
It's a 1.1.0+ thing, so not applicable if you're using 1.0.2 or below.
