### ISSUE TITLE
Compile failed!(make test)

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [openssl/openssl#8758]
Linux: 2.6.32-431.el6.i686 
![image](https://user-images.githubusercontent.com/14014477/56180459-ff0eae80-603b-11e9-9b07-9da5251ad6b4.png)

**Comment by chengyafei1007** [comment]
这个问题解决了吗

**Comment by mattcaswell** [comment]
Please post comments in English.

We will need to see the output from `make TESTS=test_internal_sm2 V=1 test`

**Comment by aixiaoxiaoyu** [comment]
> Please post comments in English.
> 
> We will need to see the output from `make TESTS=test_internal_sm2 V=1 test`

The same situation.

![image](https://user-images.githubusercontent.com/14014477/56333283-2b563680-61c6-11e9-89b2-eec6fcbd2177.png)

**Comment by InfoHunter** [comment]
What is your `config` parameter?

**Comment by mattcaswell** [comment]
The hint is in the line in the above screenshot about Test::More. Your perl module for Test::More is too old.

See this text in the NOTES.PERL file:

https://github.com/openssl/openssl/blob/86a7ac5e76fd3df9a5c3422153ae5a3e4f99b3a8/NOTES.PERL#L51-L63
