### ISSUE TITLE
[SOLVED] Intermittent SSL3 alert read:fatal:decrypt error in 1.0.2+ ; RSA_padding_check_PKCS1_type_1:invalid padding

### ISSUE THREAD

**Issue by petesky** [openssl/openssl#8761]
After updating to 1.0.1r (32bit) i get the obove error (sometimes immediatly and sometimes after minutes or hours). I'm not a programmer so i don't know exactly whats going on here but maybe someone has same problems and can explain better.

**Comment by mattcaswell** [comment]
Can you post the exact error message that you get? That precise error message doesn't seem to exist although we have a number of similar ones:

SSL_R_PROTOCOL_IS_SHUTDOWN
SSL_R_UNKNOWN_PROTOCOL
SSL_R_UNSUPPORTED_PROTOCOL
SSL_R_NO_PROTOCOLS_AVAILABLE
SSL_R_TLSV1_ALERT_PROTOCOL_VERSION
SSL_AD_PROTOCOL_VERSION

**Comment by petesky** [comment]
Sorry i get this message in Firefox Browser (ERR_SSL_PROTOCOL_ERROR) whenever my webserver with the 1.0.2r lib cannot handle the request anymore. Other browsers seems to have similar errormessage. I have no log with this error from ssl therefore i can't tell you more specific about this issue. But in fact moving downwards to 1.0.2q resolves the problem.

**Comment by mattcaswell** [comment]
So there are no error or logging messages on the server side when this happens? If not then capturing a wireshark trace of the failed connection attempt seems to be the only way forward.

**Comment by petesky** [comment]
I'm very sorry but i have no logs for this error. The only thing i know is that this happens whenever i try so simultaneously connect with same browser via TLS 1.2. An existing connection will work further but for any new connection it seems that the lib cannot negotiate correctly. I can try to setup a vm for testing but this error happens on a production machine with no further logging.

**Comment by mattcaswell** [comment]
Unfortunately without logs or a wireshark trace there's probably not a lot we can do to help with this issue.

**Comment by petesky** [comment]
Small correction - same problem today also with 1.0.2q . The only difference is the time between the errors. Please let me know what exactly to trace with wireshark.

**Comment by mattcaswell** [comment]
We need to see a TLS handshake that fails in the wireshark output.

**Comment by petesky** [comment]
```
[2019-04-23 11:51:02] Handshake-S before/accept initialization
[2019-04-23 11:51:02] SSL_accept:before/accept initialization
[2019-04-23 11:51:02] SSL_accept:SSLv3 read client hello A
[2019-04-23 11:51:02] SSL_accept:SSLv3 write server hello A
[2019-04-23 11:51:02] SSL_accept:SSLv3 write certificate A
[2019-04-23 11:51:02] SSL_accept:SSLv3 write key exchange A
[2019-04-23 11:51:02] SSL_accept:SSLv3 write server done A
[2019-04-23 11:51:02] SSL_accept:SSLv3 flush data
[2019-04-23 11:51:02] SSL_accept:SSLv3 read client certificate A
[2019-04-23 11:51:02] SSL3 alert read:fatal:decrypt error
[2019-04-23 11:51:02] SSL_accept:failed in SSLv3 read client key exchange A
[2019-04-23 11:51:02] CLOSE [443] -> .....:63234

```

**Comment by mattcaswell** [comment]
Hmm. That doesn't tell us too much. I'd still like to see wireshark output if possible - that has additional detail that might give us some kind of clue.

**Comment by petesky** [comment]
Hello. Can you please give me some advise to set the correct filter in Wireshark. I found also a lot of other people having this issue since a while assuming a problem with OCSP stapling ? I have a non standard webserver using just the 1.0.x 32 bit libs and i cannot set much options - i have SSL verify client = false (which seems to standard no OCSP). Is there a chance to avoid the error if i set this value to true or is there a increase of time accessing the page ?

**Comment by mattcaswell** [comment]
Decrypt error is a very generic error that could be caused by all sorts of things. It seems unlikely to be OCSP is the cause here - but until we know a bit more we can't say for sure.

I'm no wireshark expert but you don't need a filter in wireshark to start capturing packets. Filters are "display filters" so they don't impact whats in the pcap file. You can use the "ssl" filter to only show SSL/TLS traffic (assuming your web server is listening on port 443).

**Comment by petesky** [comment]
Hello. I found out that temporary disabling **ECDHE** ciphers will solve this issue. Is there something broken with these ciphers ? The error in wireshark is as follow:

```
TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Decrypt Error)
Content Type: Alert (21)
Version: TLS 1.2 (0x0303)
Length: 2
Alert Message
Level: Fatal (2)
Description: Decrypt Error (51)


```

**Comment by petesky** [comment]
Dear mattcaswell !

I can confirm that 1.0.2p works perfectly (also with ECDHE enabled ciphers) whilst 1.0.2q and upwards produces the above decrypt error on my webserver (x86 32 bit , using dll from indy or any other precompiled binary). The error can be reproduced on my system by connecting several times in a row with IE EDGE browser (but i dont know if this is an imagination). I will investigate further but maybe you can check again . Thank you.

**Comment by mattcaswell** [comment]
What happens if you configure with "no-asm" to disable assembler when building openssl? That option isn't really suitable for production use but might give a clue as to what the issue is.

**Comment by petesky** [comment]
I currently use the precompiled from https://indy.fulgan.com/SSL/ but also the shinig light have same issue. I will try to compile by myself and give feedback shortly.

**Comment by petesky** [comment]
Dear mattcaswell !

I now compiled 1.0.2r with no-asm / VC9 / X86 and it works so far. I will try without the option next few days.

**Comment by petesky** [comment]
Hello mattcasewell !

Small correction - for some reason it runs with 1.0.2r  much longer without error but somehow today i had same error after only a few hours.

**Comment by petesky** [comment]
I can say that seems to happen only in case of parallel access (eg when opening firefox with pinned tabs accessing same site). Along with this error https://github.com/miranda-ng/miranda-ng/pull/1817/commits/6adc6b7f3e39f0409312df32dcf2d73ffe4ae1e7 it may has todo with multithreading ?
? 

Read : https://www.openssl.org/docs/man1.0.2/man3/CRYPTO_set_locking_callback.html

**Comment by petesky** [comment]
After about hours of running fine i now get the error also in 1.0.2p . I assume there is a bug already in a previous version - cannot say which one runs fully stable.

**Comment by mattcaswell** [comment]
> it may has todo with multithreading ?

That's entirely plausible. Is this your own application or are you using some third-party application?

**Comment by petesky** [comment]
Its a 3r party app. I'm currently on 1.0.2o and it seems to be more stable. I found this to be the only change https://github.com/openssl/openssl/commit/3984ef0b72831da8b3ece4745cac4f8575b19098 

I will test a week more but it looks good so far with 1.0.2o

**Comment by petesky** [comment]
Dear mattcasewell !

1.0.2o runs very stable. No issues over the weekend. I compared the versions: https://github.com/openssl/openssl/compare/3ce7bc40a3c48da1c96c2d04c10045bd797c6aa3...e71ebf275da66dfd601c92e0e80a35114c32f6f8
... and i found interesting things like eg. this one: https://github.com/openssl/openssl/commit/279bf3e0a07d6c84043a316ca8494cbc3b51f731 or also others which sounds good for me.

So far so good i will try to inspect the upcoming weekend with debugger to see whats going on and i hope you will check the issue so far. I cannot believe that i'm the only one having this strange behaviour.

**Comment by mattcaswell** [comment]
Reviewing the list of commits between 1.0.2o and 1.0.2p doesn't reveal an obvious candidate for introducing this problem.

**Comment by petesky** [comment]
Good morning, Along with the error there is a second message (in FF 66+) which is right before SEC_ERROR_BAD_SIGNATURE and after pressing refresh (F5) named ERR_SSL_PROTOCOL_ERROR. As i wrote before i will try to debug with the help of a friend the upcoming weekend. It seems that error happens always when opening FF with pinned tabs along with a start page on same site.

**Comment by petesky** [comment]
Dear mattcasewell . I think you are right as this happens now with 1.0.2o also (just one error in 4 days). I will downgrade to next lower version and give feedback whenever it runs 100% stable.  I am very sorry about the long thread.

**Comment by petesky** [comment]
With 1.0.2n i get PR_END_OF_FILE_ERROR instead of SEC_ERROR_BAD_SIGNATURE in case that website opens in parallel pinned tab + startpage on same time with FF.

```
Protokollversion:: TLSv1.2
Cipher-Suite:: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Key Exchange Group:: P256
Signatur-Schema:: RSA-PKCS1-SHA512
HTTP Strict Transport Security:: Aktiviert
Public-Key-Pinning:: Deaktiviert
```

**Comment by petesky** [comment]
Here is the callstack when the SSL error occurs:

```
SSL_accept(s)
ssl3_accept(s)
ssl3_get_client_key_exchange(s)
ssl3_get_message(s, SSL3_ST_SR_KEY_EXCH_A,SSL3_ST_SR_KEY_EXCH_B, SSL3_MT_CLIENT_KEY_EXCHANGE, 2048, &ok);
ssl3_read_bytes(s, SSL3_RT_HANDSHAKE, pBuf, SSL3_HM_HEADER_LENGTH, 0) (means init_num = 0)
SSLerr(SSL_F_SSL3_READ_BYTES, SSL_AD_REASON_OFFSET + alert_descr);

```
as metioned, it's code 51 (decrypt_error).

Interestingly, the problem with the webserver being inaccessible for some time after the error is due to a change in SSL_shutdown code:
https://github.com/openssl/openssl/commit/64193c8218540499984cd63cda41f3cd491f3f59#diff-ff196ec6869f7b41a0b414a42d68a444
It seems that my webserver doesn't like it when the function is setting an error there (and returning -1). From what I was able to see in the webserver assembly code, the -1 shouldn't be a problem, but after patching the code to NOT set an error and return 1, as it used to be in previous versions, at least the server is able to recover from the SSL-error immediately and is able to serve new requests.
So a hint for the problem may be that the server still seems to be in the state SSL_in_init.
However this change doesn't fix the cause for the original error and I still have no idea how to find out what is going on here.

**Comment by mattcaswell** [comment]
What version of OpenSSL are you using on the client?

**Comment by petesky** [comment]
Tried from Ubuntu 18 (OpenSSL 1.1.1b  26 Feb 2019)

**Comment by petesky** [comment]
Dear mattcaswell !

I friend has finally solved the issue by patching the server. The server uses ISAPI (PHP,etc) so he patched the server to use libreSSL libs whilst ISAPI uses the latest Openssl binaries. It seems that - somehow - something is maybe corrupting memory (cert, etc) so the padding is wrong. It seems that error only happens in parallel access so maybe a multithreading issue. Its not really clear what exactly causes the curruption but i am finally happy. Thank you for watching the thread - please mark solved. Thank you.

**Comment by mattcaswell** [comment]
Great - glad you got it sorted.

**Comment by ErwinSteffens** [comment]
@petesky Did you ever see this problem again while using libreSSL?

We have the same issue: 
```
139874435121216:error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:../crypto/rsa/rsa_pk1.c:67:
139874435121216:error:04067072:rsa routines:rsa_ossl_public_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:572:
139874435121216:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:../crypto/asn1/a_verify.c:171:
```

When running an openssl verify on all our certificates we see this showing up randomly.

```
openssl version
OpenSSL 1.1.0j  20 Nov 2018 (Library: OpenSSL 1.1.0k  28 May 2019)
```

```
php -v
PHP 7.3.7 (cli) (built: Jul  9 2019 22:58:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies
```
