### ISSUE TITLE
make test报错

### ISSUE THREAD

**Issue by chengyafei1007** [openssl/openssl#8769]
![image](https://user-images.githubusercontent.com/46770210/56258133-1794cc80-6101-11e9-97b6-ac06d7a0b3ca.png)

**Comment by levitte** [comment]
What perl version and on what operating system?

**Comment by chengyafei1007** [comment]
> 什么perl版本和什么操作系统？

![image](https://user-images.githubusercontent.com/46770210/56258908-c6d2a300-6103-11e9-9ad9-62cd392e3dcc.png)

**Comment by levitte** [comment]
OK. According to [NOTES.PERL](https://github.com/openssl/openssl/blob/master/NOTES.PERL), you must install the `perl-core` package.

**Comment by chengyafei1007** [comment]
> perl-core

装了还是不可以

**Comment by chengyafei1007** [comment]
> > Perl的核心
> 
> 装了还是不可以

已经解决，谢谢

**Comment by levitte** [comment]
Does that mean that the tests run now?

**Comment by chengyafei1007** [comment]
是的，非常感谢您的告知

**Comment by chengyafei1007** [comment]
> 这是否意味着测试现在运行？

是的，非常感谢您的告知

**Comment by LSbrick** [comment]
Do you know the specific reason?
