### ISSUE TITLE
"make test" fails when cross compiling openssl 1.0.2r

### ISSUE THREAD

**Issue by nautilus7** [openssl/openssl#8775]
Hi, I am cross-compiling openssl 1.0.2.r for aarch64. Everything seem to work fine except for the `make test` command, where I get this error:

```
testing...
make[1]: Entering directory '/home/nautilus7/openssl-source/openssl-102r-aarch64/test'
make[2]: Entering directory '/home/nautilus7/openssl-source/openssl-102r-aarch64'
making all in apps...
make[3]: Entering directory '/home/nautilus7/openssl-source/openssl-102r-aarch64/apps'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/nautilus7/openssl-source/openssl-102r-aarch64/apps'
make[2]: Leaving directory '/home/nautilus7/openssl-source/openssl-102r-aarch64'
../util/shlib_wrap.sh ./destest
../util/shlib_wrap.sh: 103: exec: ./destest: Exec format error
Makefile:172: recipe for target 'test_des' failed
make[1]: *** [test_des] Error 2
make[1]: Leaving directory '/home/nautilus7/openssl-source/openssl-102r-aarch64/test'
Makefile:472: recipe for target 'tests' failed
make: *** [tests] Error 2
```

I made openssl like this:

```
export CC=/home/nautilus7/toolchains/aarch64/bin/aarch64-buildroot-linux-gnu-gcc
export RANLIB=/home/nautilus7/toolchains/aarch64/bin/aarch64-buildroot-linux-gnu-ranlib
./Configure linux-aarch64 shared --prefix=/home/nautilus7/toolchains/aarch64/aarch64-buildroot-linux-gnu/sysroot/usr/ --openssldir=/home/nautilus7/toolchains/aarch64/aarch64-buildroot-linux-gnu/sysroot/usr/
make
```

If I skip testing and  install openssl in my toolchain, I can use openssl without problem, so I guess building is successful. It seems only testing is not working.

Is it because I am trying to test/run aarch64 binaries in my host OS which is an x86-64 ubuntu? If this is the problem, how am I supposed to test if building went fine?

Thanks.

**Comment by mattcaswell** [comment]
> Is it because I am trying to test/run aarch64 binaries in my host OS which is an x86-64 ubuntu? If this is the problem, how am I supposed to test if building went fine?

Exactly that. That is one of the pit falls of cross-compiling. It may be possible to do something clever with qemu to run the tests - but that's outside of the scope of what we support.

**Comment by levitte** [comment]
For transparent qemu emulation, you're looking for binfmt_misc. Here's a random blog that talks a bit about it. 

https://ownyourbits.com/2018/06/13/transparently-running-binaries-from-any-architecture-in-linux-with-qemu-and-binfmt_misc/

**Comment by nautilus7** [comment]
Thanks, I'll have a look.

**Comment by paulidale** [comment]
Closing this on the assumption that the suggestion worked.
Please reopen it, if this isn't the case.
