### ISSUE TITLE
asn1parse - option to output raw to stdout

### ISSUE THREAD

**Issue by nyetwurk** [openssl/openssl#8777]
It would be really nice to be able to output raw data from `asn1parse` to `stdout` as part of a longer pipeline, e.g:
```
openssl x509 -noout -pubkey -in cert.pem | openssl asn1parse -strparse 17 -nooout | openssl dgst
```

**Comment by levitte** [comment]
`-noout` for `asn1parse` seems a bit meaningless and gives no indication what is really desired.
Quite frankly, it sounds like you simply want to extract a chunk of the (binary) input, i.e. something like this:

```
openssl x509 -noout -pubkey -in-cert.pem | \
openssl rsa -pubin -outform d | \
dd ibs=1 skip=20 | \
openssl dgst
```

**Comment by nyetwurk** [comment]
Yes, absolutely. I included `-noout` to indicate I do not want to specify an `-out`, analogous to the `openssl x509 -noout` vs `openssl x509 -out outfile`

I will try avoiding `asn1parse` entirely as you suggest; maybe it isn't necessary.

To be specific, I am trying to extract an SKI from an `ec` pubkey.

**Comment by nyetwurk** [comment]
Looks like this works, and `asn1parse` is not needed
```
openssl x509 -noout -pubkey -in cert.pem | openssl ec -pubin -outform d | dd ibs=26 skip=1 | openssl dgst -sha256
```

**Comment by bjmgeek** [comment]
I've seen some documentation online (e.g. [this stack exchange answer](https://security.stackexchange.com/a/128956/32947) showing -out - as a valid pipeline.  However, when I tried it, it made a file called `-` in the current directory.
