### ISSUE TITLE
I found a bug about openssl speed test

### ISSUE THREAD

**Issue by niiiloc** [openssl/openssl#8779]
I downloaded the newest project from github this week And use it to test aes and hmac performance.
Then I found an interesting fact as below:
openssl speed -evp aes-256-cbc
![image](https://user-images.githubusercontent.com/42606795/56343623-daf2cf00-61ed-11e9-9ed4-1f63704f9357.png)
openssl speed -evp sha256
![image](https://user-images.githubusercontent.com/42606795/56343666-f2ca5300-61ed-11e9-959f-5824c66251cd.png)
openssl speed -evp aes-256-cbc-hmac-sha256
![image](https://user-images.githubusercontent.com/42606795/56343696-0bd30400-61ee-11e9-82dd-025bfd80168c.png)

As you see, aes-256-cbc-hmac-sha256's performance is much higher than the sum of aes-256-cbc and  sha256.
Then I read the source code of openssl speed and do more tests, I've found the issue that in aes-256-cbc-hmac-sha256, openssl doesn't actually calculate the hmac value of input, only do the encryption.

Hope for your reply, thx.

**Comment by niiiloc** [comment]
Here is my test code, according to the implementation of openssl speed code.
`int openssl_aes_256_cbc_hmac_sha256_encrypt(crypto_para_t *crypto_para)
{
    EVP_CIPHER_CTX *ctx;
    int ret;
    
    UINT32 alg_id = crypto_para->alg_id;
    UCHAR *input = crypto_para->input;
    UINT32 input_len = crypto_para->input_len;
    UCHAR *iv = crypto_para->iv;
    UINT32 iv_len = crypto_para->iv_len;
    UCHAR *output = crypto_para->output;
    UINT32 *output_len = crypto_para->output_len;
    UCHAR *key = crypto_para->key;
    UINT32 key_len = crypto_para->key_len;

    ctx = EVP_CIPHER_CTX_new();

    ret = EVP_CipherInit_ex(ctx, EVP_aes_256_cbc_hmac_sha256(), NULL, NULL, iv, 1);
    if (ret != 1)
    {
        log_error("EVP_CipherInit_ex 1st failed, ret=%d\r\n", ret);
        return ret;
    }

    ret = EVP_CIPHER_CTX_set_padding(ctx, 0);
    if (ret != 1)
    {
        log_error("EVP_CIPHER_CTX_set_padding failed, ret=%d\r\n", ret);
        return ret;
    }

    ret = EVP_CipherInit_ex(ctx, NULL, NULL, key, NULL, -1);
    if (ret != 1)
    {
        log_error("EVP_CipherInit_ex 2nd failed, ret=%d\r\n", ret);
        return ret;
    }

    ret = EVP_EncryptUpdate(ctx, output, output_len, input, input_len);
    if (ret != 1)
    {
        log_error("EVP_EncryptUpdate failed, ret=%d\r\n", ret);
        return ret;
    }

    return 0;
}
`

**Comment by bernd-edlinger** [comment]
Hmm, aes-256-cbc-hmac-sha256 is a cipher, the mac should be added probably in AEAD style?
I tried to add -aead, but it does not work either:
```
openssl speed -evp aes-256-cbc-hmac-sha256 -aead
Doing aes-256-cbc-hmac-sha256 for 3s on 2 size blocks: 29959039 aes-256-cbc-hmac-sha256's in 3.00s
Doing aes-256-cbc-hmac-sha256 for 3s on 31 size blocks: 25100970 aes-256-cbc-hmac-sha256's in 2.99s
Doing aes-256-cbc-hmac-sha256 for 3s on 136 size blocks: 25078729 aes-256-cbc-hmac-sha256's in 3.00s
Doing aes-256-cbc-hmac-sha256 for 3s on 1024 size blocks: 25073346 aes-256-cbc-hmac-sha256's in 2.99s
Doing aes-256-cbc-hmac-sha256 for 3s on 8192 size blocks: 25066103 aes-256-cbc-hmac-sha256's in 3.00s
Doing aes-256-cbc-hmac-sha256 for 3s on 16384 size blocks: 25085735 aes-256-cbc-hmac-sha256's in 3.00s
version: 3.0.0-dev
built on: built on: Thu Apr 18 08:32:07 2019 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type              2 bytes     31 bytes    136 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-cbc-hmac-sha256    19972.69k   260244.17k  1136902.38k  8586992.07k 68447171.93k 137001560.75k
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
140204322457344:error:060DB0A2:digital envelope routines:evp_EncryptDecryptUpdate:partially overlapping buffers:crypto/evp/evp_enc.c:329:
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
140204322457344:error:060DB0A2:digital envelope routines:evp_EncryptDecryptUpdate:partially overlapping buffers:crypto/evp/evp_enc.c:329:
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
140204322457344:error:060DB0A2:digital envelope routines:evp_EncryptDecryptUpdate:partially overlapping buffers:crypto/evp/evp_enc.c:329:
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
140204322457344:error:060DB0A2:digital envelope routines:evp_EncryptDecryptUpdate:partially overlapping buffers:crypto/evp/evp_enc.c:329:
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
140204322457344:error:060DB0A2:digital envelope routines:evp_EncryptDecryptUpdate:partially overlapping buffers:crypto/evp/evp_enc.c:329:
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
140204322457344:error:060DB0A2:digital envelope routines:evp_EncryptDecryptUpdate:partially overlapping buffers:crypto/evp/evp_enc.c:329:
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
140204322457344:error:060DB0A2:digital envelope routines:evp_EncryptDecryptUpdate:partially overlapping buffers:crypto/evp/evp_enc.c:329:
140204322457344:error:0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length:crypto/evp/evp_enc.c:426:
```

**Comment by bernd-edlinger** [comment]
but -mb seems to work:
```
openssl speed -evp aes-256-cbc-hmac-sha256 -mb
Doing aes-256-cbc-hmac-sha256 for 3s on 8192 size blocks: 158383 evp's in 3.00s
Doing aes-256-cbc-hmac-sha256 for 3s on 16384 size blocks: 92846 evp's in 2.99s
Doing aes-256-cbc-hmac-sha256 for 3s on 32768 size blocks: 51095 evp's in 3.00s
Doing aes-256-cbc-hmac-sha256 for 3s on 65536 size blocks: 26940 evp's in 2.99s
Doing aes-256-cbc-hmac-sha256 for 3s on 131072 size blocks: 13844 evp's in 3.00s
The 'numbers' are in 1000s of bytes per second processed.
type                       8192 bytes  16384 bytes  32768 bytes  65536 bytes 131072 bytes
aes-256-cbc-hmac-sha256    432491.18k   508758.82k   558093.65k   590481.55k   604853.59k
```

**Comment by niiiloc** [comment]
mb means multiple blocks. And it should work properly without mb option.
And according to my test, openssl don't do hmac but only encrypt while doing openssl speed -evp aes-256-cbc-hmac-sha256.
![image](https://user-images.githubusercontent.com/42606795/56351071-d7b40f00-61fe-11e9-850b-70bb9fd5b13e.png)

> but -mb seems to work:
> 
> ```
> openssl speed -evp aes-256-cbc-hmac-sha256 -mb
> Doing aes-256-cbc-hmac-sha256 for 3s on 8192 size blocks: 158383 evp's in 3.00s
> Doing aes-256-cbc-hmac-sha256 for 3s on 16384 size blocks: 92846 evp's in 2.99s
> Doing aes-256-cbc-hmac-sha256 for 3s on 32768 size blocks: 51095 evp's in 3.00s
> Doing aes-256-cbc-hmac-sha256 for 3s on 65536 size blocks: 26940 evp's in 2.99s
> Doing aes-256-cbc-hmac-sha256 for 3s on 131072 size blocks: 13844 evp's in 3.00s
> The 'numbers' are in 1000s of bytes per second processed.
> type                       8192 bytes  16384 bytes  32768 bytes  65536 bytes 131072 bytes
> aes-256-cbc-hmac-sha256    432491.18k   508758.82k   558093.65k   590481.55k   604853.59k
> ```

**Comment by bernd-edlinger** [comment]
> The output only contains the cipher text of input, no hmac code.

you must also add a mac key:
EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_MAC_KEY, sizeof(key), key);
and you need to specify the 13-byte AAD using

EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_TLS1_AAD, sizeof(aad), aad);
the that needs to contain the payload length  in bytes 11&12, plus TLS version in bytes 9&10.
On output the hmac + padding should be in the encrypted data, at the position that the
payload length points to.

**Comment by niiiloc** [comment]
Thanks for your reply. I'll try it.
But I'm still confused about it, why don't mac key added in the source code of 'openssl speed -evp aes-256-cbc-hmac-sha256'.
It seems like openssl don't support it in normal mode, only support it in mb mode?
> > The output only contains the cipher text of input, no hmac code.
> 
> you must also add a mac key:
> EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_MAC_KEY, sizeof(key), key);
> and you need to specify the 13-byte AAD using
> 
> EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_TLS1_AAD, sizeof(aad), aad);
> the aad data needs to contain the payload length in bytes 11&12, plus TLS version in bytes 9&10.
> On output the hmac + padding should be in the encrypted data, at the position that the
> payload length points to.

**Comment by bernd-edlinger** [comment]
If you care about it, feel free to open a PR for such a feature,

**Comment by niiiloc** [comment]
okay, I'm appreciate for your help. In any case, yhis issue should be closed.

**Comment by bernd-edlinger** [comment]
Okay, good bye!
