### ISSUE TITLE
SSL_do_handshake returns without calling s->handshake_func

### ISSUE THREAD

**Issue by vgmahajanshetty** [openssl/openssl#8782]
Hi,

I am using OpenSSL1.1.1a. I have SSL server which should perform client auth based on particular URL requested from client.

The initial handshake goes fine and will be successful. When the server application finds a particular URL is being accessed by client, it tries to do client auth.

So now, I call SSL_do_handshake(); in this call, it sends "Hello Request" to client and returns with value 1. Then I call SSL_do_handshake() again (by this time clients "Client Hello" will be received), but the function just returns without doing anything. When I checked it, it returns at:

3571     if (SSL_in_init(s) || SSL_in_before(s)) {  ==> this will fail and returns at line 3582
3572         if ((s->mode & SSL_MODE_ASYNC) && ASYNC_get_current_job() == NULL) {
3573             struct ssl_async_args args;
3574 
3575             args.s = s;
3576 
3577             ret = ssl_start_async_job(s, &args, ssl_do_handshake_intern);
3578         } else {
3579             ret = s->handshake_func(s);
3580         }
3581     }
3582     return ret;

So it returns at line 3582 because if() at line 3571 fails. When I checked values, they are as below:
(gdb) p s->statem.hand_state
$2 = TLS_ST_OK
(gdb) p s->statem.state
$3 = MSG_FLOW_FINISHED

Please let me know whether should we call any new API when initiating client auth? I am using TLS1.2.
Same thing works fine when I use OpenSSL1.0.2.

Thank You.

**Comment by mattcaswell** [comment]
> Then I call SSL_do_handshake() again (by this time clients "Client Hello" will be received), but the function just returns without doing anything.

You need to attempt to read data from the client. The client is not required to respond with a ClientHello straight away (or at all). We will only start doing a handshake if we actually have seen handshake data arrive. This will be processed automatically as part of a call to SSL_read().

> Same thing works fine when I use OpenSSL1.0.2.

Strange. I would expect the same behaviour even in 1.0.2 The same test exists even there:

https://github.com/openssl/openssl/blob/f937540ec40a5e838460b8f19d2eb722529126b8/ssl/ssl_lib.c#L2802-L2804

**Comment by vgmahajanshetty** [comment]
Hi,

Thanks for your response.

I checked the behavior of server when using OpenSSL1.0.2.

When client sends HTTP requests after initial handshake we call SSL_read(), this reads only the HTTP request, then we decide to do client auth.
When we want to do client auth, we will call SSL_do_handshake(), this internally ssl3_accept() and sends HelloRequest then client sends ClientHello. SSL_do_handshake() returns <= 0; then we will set the event on FD to call SSL_do_handshake() again (async). This process repeats until handshake is finished successfully. 

Point here is, nowhere we called SSL_read() (It didn't hit this break point until entire handshake is finished, it got called only once when we initially read clients HTTP request); everything is done from SSL_do_handshake()->ssl3_accept() calls.

But this behavior is not seen with OpenSSL1.1.1a. As per your earlier comment, when I call SSL_read() (again in async manner) in case of OpenSSL1.1.1a, handshake (i.e, client auth) is getting finished properly.

Please let me know if there is something missing or wrong in my observation WRT client auth process in 1.0.2; also I feel there is difference in 1.0.2 and 1.1.1a how client auth is done.

Thank You.

**Comment by mattcaswell** [comment]
> When client sends HTTP requests after initial handshake we call SSL_read(), this reads only the HTTP request, then we decide to do client auth.
When we want to do client auth, we will call SSL_do_handshake(), this internally ssl3_accept() and sends HelloRequest then client sends ClientHello. SSL_do_handshake() returns <= 0;

Wait - something sounds odd here. After the server calls SSL_do_handshake() the first time and the HelloRequest is sent successfully, at this point we expect SSL_do_handshake() to return 1. This should happen before it has yet processed the ClientHello from the client. This is the behaviour I see when I tested this on my local 1.0.2 instance.

At this point we are no longer "in init" (i.e. SSL_in_init() returns 0). Do you not see this happening?

Matt

**Comment by vgmahajanshetty** [comment]
Hi,

Yes I missed that, sorry for providing half information.
First time SSL_do_handshake() sends HelloRequest and returns 1. Then we call SSL_renegotiate() and SSL_do_handshake() again. This time it returns -1, so we assign event on fd to call SSL_do_handshake() again. This process continues it completes client auth.
During this process we will not call SSL_read(), only before initiating client auth we call once to read the request and decide to do client auth. This is WRT OpenSSL1.0.2.

But, in OpenSSL1.1.1a the second call to SSL_do_handshake() will also return 1 as I explained in my first comment. When I changed to code the way you mentioned, i.e., to call SSL_read() then it processes the handshake messages and it succeeds.

My observation is, in case of OpenSSL1.0.2, we will not call SSL_read() during client auth handshake and SSL_do_handshake() performs all operations internally. Where as in OpenSSL1.1.1a we need to call SSL_read() explicitly during this process. Please let me know if this behavior is expected one or something needs to be changed (like calling some APIs).

Thank You.

**Comment by vgmahajanshetty** [comment]
Hi,

Please let me know if something is wrong from client auth point of view wrt 1.0.2 and 1.1.1a.

Thank You.

**Comment by mattcaswell** [comment]
> First time SSL_do_handshake() sends HelloRequest and returns 1. Then we call SSL_renegotiate() and SSL_do_handshake() again. This time it returns -1, so we assign event on fd to call SSL_do_handshake() again. This process continues it completes client auth.

This doesn't match my expectations of what the behaviour should be. If you call SSL_renegotiate() a second time followed by SSL_do_handshake() again then I expect it to do exactly what happened the first time again, i.e. a HelloRequest is sent followed by SSL_do_handshake() returning 1 (and no longer being "in init"). I've just tested this and that's exactly what happened for me, so I don't understand why you are seeing different behaviour.

> My observation is, in case of OpenSSL1.0.2, we will not call SSL_read() during client auth handshake and SSL_do_handshake() performs all operations internally. Where as in OpenSSL1.1.1a we need to call SSL_read() explicitly during this process. Please let me know if this behavior is expected one or something needs to be changed (like calling some APIs).

What you are *supposed* to do is call SSL_renegotiate() followed by SSL_do_handshake() to send the HelloRetryRequest. You are then supposed to continue trying to read data from the client via SSL_read(). From a general point of view the client is not obliged to respond to a HelloRetryRequest. It can ignore it completely and continue sending normal application data. Or it might be that there is data already in flight that the client has already sent but the server hasn't processed yet. If you force the server into trying to do a handshake when application data is there, then the connection will fail. For these reasons you should keep calling SSL_read(). If what is received is actually a ClientHello instead of application data then the renegotiation will happen automatically.

This is the case in both 1.0.2 and 1.1.1. What I do not understand is why you are seeing a behaviour difference between the two. That is unexpected. The behaviour you see in 1.1.1 is what I would expect in 1.0.2 too.

**Comment by vgmahajanshetty** [comment]
Thank you for your help. I figured out the reason for this change in behavior.
In our server code for some reason they have set SSL state to "s->state =  SSL_ST_ACCEPT" before calling SSL_do_handshake(s) in case of 1.0.2 code. This is the reason for it not returning 1 in second call. When I remove that then it does client auth through SSL_read(), which is right behavior.

Thank you again.

**Comment by mattcaswell** [comment]
Ah - that would explain it! Thanks for the update - closing this.
