### ISSUE TITLE
kdf(1) and pkeyutl(1) should cross-link

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8784]
note: depends on #8762 being merged

The kdf(1) man page and pkeyutl(1) man page should cross-reference each-other as the pkeyutl is the old CLI for accessing the KDFs while `kdf` is the new app not all users will be automatically familiar with.

**Comment by RameshwarapuSanthosh** [comment]
Fix for the man pages issue is submitted at: https://github.com/openssl/openssl/pull/9227

Please review to merge.

**Comment by RameshwarapuSanthosh** [comment]
Closed the previous pull request by mistake. Please review : https://github.com/openssl/openssl/pull/9228
