### ISSUE TITLE
Unable to use -subj with Windows Git Bash

### ISSUE THREAD

**Issue by djechelon** [openssl/openssl#8795]
I am using Git for Windows with OpenSSL 1.1.1a

When I run `openssl` from the Git Bash, which emulates a POSIX environment, I am unable to pass `-subj` argument to openssl

Example output using `"/C=GB/ST=London/L=London/O=Example Org/OU=Delivery/CN=example.org root CA"`

```
$ openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 -out ca.pem \ 
-subj "/C=GB/ST=London/L=London/O=Example Org/OU=Delivery/CN=example.org root CA" 

name is expected to be in the format /type0=value0/type1=value1/type2=... where characters may be escaped by \. This name  is not in that format: 'C:/Program Files/Git/C=GB/ST=London/L=London/O=Example Org/OU=Delivery/CN=example.org root CA'
problems making Certificate Request
```

This might or might not be a problem with Git Bash. As you can see, it is trying to resolve the subject as it was a file inside C:\Program Files\Git

**Comment by levitte** [comment]
This is because the underlying libraries (coming from mingw) are trying to be smart and convert arguments that look like paths to actual paths.

As you can see, they are a little too smart some times.

**Comment by mattcaswell** [comment]
You might try setting the `MSYS_NO_PATHCONV` environment variable to 1 before you start:

https://github.com/git-for-windows/git/issues/577#issuecomment-166118846

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.

**Comment by coffeefan** [comment]
Another solution might be to use double slahes "//"

**Comment by TannerPlauche** [comment]
// Slash worked for me as well. Mentioned in in Matt Casswell's reference and CoffeeFan. Thank you!

**Comment by brt-han-mai** [comment]
Double slash will cause `req: Skipping unknown attribute "/C"`, workaround would be `//C=GB/C=GB...`

**Comment by BobJackson** [comment]
Add / before /, the result like //

**Comment by MensSana** [comment]
I encountered the same problem under Cygwin, and the solution was to use single quotes instead of double for the -subj.

**Comment by lamoboos223** [comment]
i use mac and it worked with me like this

`openssl req -x509 -nodes -subj "/CN=localhost" -newkey rsa:4096 -sha256 -keyout server.key -out server.crt -days 3650`

**Comment by snydergd** [comment]
In case helpful, I wanted to mention another solution which worked in my case, which was to simply drop to a `cmd` shell inside of git bash and run the same command there.  Since it's a subprocess of git bash you still have openssl on the PATH and it seems to work.  Once done, I was able to just `exit` out of the cmd shell and return to git bash.

**Comment by paulakande-couchbase** [comment]
> i had this Error "name is expected to be in the format /type0=value0/type1=value1/type2=... where characters may be escaped by . This name is not in that format: 'C:/Program Files/Git/C=US/0=tutorialapi/CN=ca' problems making Certificate Request " but after added the double Slash, i have this Error: req: Skipping unknown attribute "/C" req: Skipping unknown attribute "/O" req: Skipping unknown attribute "/CN"
> 
> additional to this path "MSYS_NO_PATHCONV ", i have no idea what's and for what!

Did you attempt to run the same command in a different shell? Switching from Git to CMD worked for me.

**Comment by snowdream** [comment]
> You might try setting the `MSYS_NO_PATHCONV` environment variable to 1 before you start:
> 
> [git-for-windows/git#577 (comment)](https://github.com/git-for-windows/git/issues/577#issuecomment-166118846)

It Works

**Comment by TestObsd** [comment]
I found that a double forward slash did not work for me. Example:

-subj //CN=myCNValue/OU=myOuValue

However the following did:

-subj /"/CN=myCNValue/OU=myOuValue"

I am using Windows Git Bash.

**Comment by kibuh** [comment]
Thanks @paulakande-couchbase
 Worked for me like charm

**Comment by Endeathia** [comment]
> Another solution might be to use double slahes "//"

Thanks worked for me!

**Comment by sToiBe** [comment]
Hi! This is my solution
`"/c/Program Files/Git/usr/bin/openssl" req -new -key keytest -subj "/C=US/O=x/CN=x/serialNumber=IA x" -out csr-test2
`
