### ISSUE TITLE
No newly-written undocumented functions

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#8798]
@mattcaswell raised an interesting issue in https://github.com/openssl/openssl/issues#discussion_r276951486

```find-doc-nits -d``` lists all undocumented functions.  It would be good if there were a variant that didn't list the "we already known" functions, so that new code that adds to the API  could run doc-nits to make sure everything is documented.

It is fairly easy to do this, add a new flag and maintain a file such as util/doc-missing.txt or whatever, that contains the known functions. Then filter anything found against that list.

I think the harder part will be for the project to come up with the workflow to properly maintain the doc-missing file; as with many things, the code is easy. :)

**Comment by paulidale** [comment]
+1

**Comment by kroeckx** [comment]
I guess you want the CI to fail in case a new public function got added without documentation? That's a good first step.

But as far as I know, we have a policy that every new function, not just the public functions, should get documented. And if you're looking at a function that's not documented, it's a perfect time to document it.

**Comment by levitte** [comment]
Maintaining such a file should be a matter of `make update`, no? That could be as simple as an added target that looks like this:

``` make
undocumented:
        ( cd $(SRCDIR) ; ./util/find-doc-nits -d > ./util/undocumented.txt )
```

**Comment by richsalz** [comment]
As I said, this is more about policy and workflow; the code would be simple.  The OMC will have to figure the hard part out.

**Comment by agnosticdev** [comment]
This also sounds like an opportunity for someone interested in contributing to document the functions found in this file.

**Comment by mattcaswell** [comment]
> I think the harder part will be for the project to come up with the workflow to properly maintain the doc-missing file

Why does it need maintenance? Once created it can remain static can't it? It doesn't matter if entries in that file end up getting documented over time and not removed from the "missing" file, because its only being used as a filter.

**Comment by mattcaswell** [comment]
> But as far as I know, we have a policy that every new function, not just the public functions, should get documented.

Do we? That's news to me.

**Comment by mattcaswell** [comment]
> Why does it need maintenance? Once created it can remain static can't it? It doesn't matter if entries in that file end up getting documented over time and not removed from the "missing" file, because its only being used as a filter.

Or an alternative approach if we really care about it being up to date is to have make doc-nits complain if there is an entry in the missing file that isn't missing.

**Comment by paulidale** [comment]
+1 for _public functions_ being automatically nagged.

**Comment by kroeckx** [comment]
On Tue, Apr 23, 2019 at 08:29:51AM +0000, mattcaswell wrote:
> > But as far as I know, we have a policy that every new function, not just the public functions, should get documented.
> 
> Do we? That's news to me.

I have been enforcing it on all things I have reviewed. I'm
clearly under the impression that we agreed to that, even if it's
not written down.

**Comment by richsalz** [comment]
@mattcaswell time to close this?

**Comment by mattcaswell** [comment]
Yes. As of b5283535d, travis should complain about new undocumented functions.
