### ISSUE TITLE
Compiling Build Options for *.DLL and OpenSLL.EXE file only

### ISSUE THREAD

**Issue by hlsantos** [openssl/openssl#8801]
Fir the minimum distribution of Openssl Component in our package, maybe this is documented somewhere, but I would like to build for the following:

1) To build only the *.dll, *.lib files and the OpenSSL.EXE program only, and 

2) Ideally, just have the *.dll without the "-1_1" version numbers.

Is this possible with the current makefile generated?

I have been using "nmake build_libs"  to get the *.dll and *.lib.   I think you can do "nmake build_programs" to get openssl.exe but it makes the fuzz and test programs.  Probably not a big deal. to make them all, but I only need openssl.exe.  

 It would be better for me to just have *.dll with the versions since these images can be updated more often than we will need to update our own images.  If the numbers change, are we expected to have an code interface change as well?  I can only another major change like v2, but 1.x update should not require an API change in my opinion.

Thanks

**Comment by hlsantos** [comment]
I would like to suggest a 3rd item:

2)  XP/2003 support.   I understanding its EOL with Microsoft, but don't tell major companies who may not need to update XP/2003 for legacy mission critical machines, the SSL security updates are needed.  No technical reason to deny them an openssl update unless Openssl itself is not using advanced Win32/64 API files beyond XP/2003 (which I don't think it is, yet).     Anyway, with OpenSSL v1.0, all I had do was edit the vc-32.pl to set /subsystem:console,"5.01" for the linker command.

For v1.1, I don't know which *.pl, to do this in, but I see the generated makefile has the BIN_LDFLAGS which can be set.  

32 bit:
BIN_LDFLAGS=/subsystem:console,"5.01" /opt:ref $(CNF_LDFLAGS) $(LDFLAGS)
64 bit:
BIN_LDFLAGS=/subsystem:console,"5.02" /opt:ref $(CNF_LDFLAGS) $(LDFLAGS)

Maybe an LINK_VER option can be passed (default none) to do this so developers don't need modified the auto-generated make?

Thanks

**Comment by levitte** [comment]
Re building just the libraries, `build_libs` is exactly right.
For building just openssl.exe, you can `nmake apps\openssl.exe` (but you must at least do `nmake build_generated` first).
Regarding dll versions, it's correct that when the number changes, the ABI has changed. The next where this is expected is with OpenSSL 3.0.0, where you will see libcrypto-3.dll and libssl-3.dll.

Regarding changing or adding to the diverse flags, it's in the .conf files in Configurations. You can create your own .conf files and have them inherit other items, so to make your own for XP/2003, you could have one that has something like this (untested, but I'm willing to help figure it out) : 

``` perl
(
    "WIN32-XP-VC" => {
        inherit_from => [ "VC-WIN32" ], 
        lflags       => add('/subsystem:console,"5.01"', '/opt:ref'),
    }, 
);
```

**Comment by hlsantos** [comment]
Perfect.   Good info to have for overall OpenSSL "KB"    I'll go ahead and test the ,conf change with using the new *-XP-VC labels now.  Thanks

**Comment by hlsantos** [comment]
Ok, I got it. :)

I created a "xp-support.conf" file and placed in the same location as configure. I could of placed in the configurations folder and the perl --config switch would not be required.

# 04/21/19 08:03 am, SSI/HLS
# Adds XP/2003 support
# usage from within build folder:
# perl ..\configure VC-WIN32-XP --config=..\xp-support.conf

my %targets = (
    "VC-WIN32-XP" => {
        inherit_from => [ "VC-WIN32" ],
        lflags       => '/subsystem:console,"5.01" /opt:ref',
        bin_lflags   => '/subsystem:console,"5.01" /opt:ref',

    },
    "VC-WIN64A-XP" => {
        inherit_from => [ "VC-WIN64A" ],
        lflags       => '/subsystem:console,"5.02" /opt:ref',
        bin_lflags   => '/subsystem:console,"5.02" /opt:ref',
    },
);

The issues?  Not much, 

1) I had to override the above two fields: lflags and bin_lflags.  Apparently, lflags is used to establish the LDFLAGS macro in makefile to link the *.dll files only.  The bin_lflags is used to establish the BIN_LDFLAGS macro in the makefile and it is only used to create the EXE files (programs).   

2) There is some duplicity in the link macros as they are used for the link commands used for both *.DLL and *.EXE actions.  This can use "some clean up" but it was harmless. The linker did not complain of the duplicate switches.  

Tip:  Since OpenSSL v11 is not dependent on any advanced WIN32 API beyond XP/2003,  you can avoid the recompile of all the source code.  All we need here is a relink to stamp the PE header.  So I copied the already built "x32"  folder to a new "x32xp",  deleted all the *.dll and *.lib, created the new makefile from within the x32xp folder:

perl ..\configure VC-WIN32-XP --config=..\xp-support.conf

and then ran 

nmake build_libs 
nmake apps\openssl.exe

To create the images with the proper PE stamps:

C:\Files\openssl\openssl-1_1_1-stable\x32xp>fileosver *.dll apps\*.exe

32bit 05.01 XP 1.1.1.3    WINDOWS_CUI 2019-04-21 10:01:20 .\libcrypto-1_1.dll
32bit 05.01 XP 1.1.1.3    WINDOWS_CUI 2019-04-21 10:01:26 .\libssl-1_1.dll
32bit 05.01 XP 1.1.1.3    WINDOWS_CUI 2019-04-21 10:07:07 apps\openssl.exe

Thanks

**Comment by hlsantos** [comment]
Maybe one of the OpenSSL cogs can decide to take the minor cleanup of the makefile link macros and promote it to a minor bug issue, It is harmless but we never know if MS will get picky with their tools in the future. 

Other than that, I will close this issue.  Thanks @levitte

**Comment by levitte** [comment]
Since you set `lflags`, i.e. appied those flags to *everything*, another option is to configure like this:

```
perl Configure VC-WIN32 LDFLAGS="/subsystem:console,\"5.01\" /opt:ref"
```

and

```
perl Configure VC-WIN64A LDFLAGS="/subsystem:console,\"5.02\" /opt:ref"
```
