### ISSUE TITLE
openssl1.0.2j as client openssl1.1.0.c as server connect failed

### ISSUE THREAD

**Issue by zjbbuaa** [openssl/openssl#8824]
I use openssl1.0.2j as client and openssl1.1.0.c  as server.After they successfully handshake,they broken the connection after one frame successfully application data transfer.
And I receive an alert in server side that says SSL_read error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol ,and in client side openssl indicates error:1408F10B:SSL routines:ssl3_get_record:wrong version number.I don't know why.Because if I use the same version of openssl ,it always succeed.
![Uploading image.png…]()

**Comment by zjbbuaa** [comment]
![image](https://user-images.githubusercontent.com/20664050/56731948-5e806300-678e-11e9-8d73-22b2852c909b.png)

**Comment by zjbbuaa** [comment]
you see in upper image,server and cliend finish the entire handshake,and server receive one frame of application data,and then receive an encrypt alert.

**Comment by mattcaswell** [comment]
Can you attach the pcap file for the above?

**Comment by zjbbuaa** [comment]
you can see that the whole process 5.16.5.2 is a client  5.21.0.1 is a server.Hope that you can help me thankyou
[p2.zip](https://github.com/openssl/openssl/files/3119359/p2.zip)

**Comment by mattcaswell** [comment]
Looking at the capture there doesn't seem to be any obvious misbehaviour on the wire. The error you are receiving on the client side indicates that the client has received a record where the version number in the record header doesn't match the protocol version that has been negotiated. However looking in the capture file we can see that TLSv1.2 is negotiated, and then the server sends application data inside a record with TLSv1.2 in the header. So the record (AFAICT) looks well formed. Its a bit of a mystery as to why the client doesn't like it.

Are the client/server here a custom application that you have written? I wonder what might happen if you were to swap out your client with a 1.0.2j version of s_client. Does it fail in the same way?

**Comment by zjbbuaa** [comment]
Sorry,I make a mistake ,My server is 1.0.2j, my client is 1.1.0c, I try to use a 1.0.2j version of s_client ,it is successfully negotiated. If this case ,you suggestion is user 1.1.c s_client to connect my server? right?

**Comment by mattcaswell** [comment]
Yes, try to connect to the server from a 1.1.0c s_client and see if it fails in the same way.

**Comment by zjbbuaa** [comment]
I find it is my foolish problem. I send an unencrypt message to client ,sorry.
