### ISSUE TITLE
Bug in man page server example for BIO_f_ssl

### ISSUE THREAD

**Issue by ghost** [openssl/openssl#8825]
The master man page for BIO_f_ssl contains a server example which has a bug. 

After setting up the server to listen with BIO_do_accept() it immediately moves on to attempt a handshake instead of calling BIO_do_accept() again to await a connection.

[manmaster/man3/BIO_f_ssl.html](https://www.openssl.org/docs/manmaster/man3/BIO_f_ssl.html)

**Comment by levitte** [comment]
That's [this file](https://github.com/openssl/openssl/blob/master/doc/man3/BIO_f_ssl.pod), should anyone wonder
