### ISSUE TITLE
0.9.8 - 1.0.0 DER format breaking change

### ISSUE THREAD

**Issue by chrmod** [openssl/openssl#883]
The way the certificates get stored in DER file got changed in 1.0.0. CA chain used to follow singing certificated, now it is stored in the beginning of the file. 

In our usecase this break NSS compatibility. More specifically we sign Firefox addons using `openssl smime -sign` and verify them with NSS (default Firefox certificate verification). This work for addons signed with open ssl 0.9.8 and doesn't work with those signed with openssl 1.0.0. 

I will try to provide instructions how to reproduce the problem but please note that my knowledge about openssl, nss and cryptography in general is not good enough to fully understand what exactly is happening. Thus I do kindly ask for help in solving this issue.

How to test:
* given a certificate \<path_to_cert\> with a key \<path_to_key\> and it ca-chain \<path_to_ca-chain\> of intermediate and root, we want to sign some file \<path_to_file\>
* having a script called **run.sh**
```sh
$OPENSSL smime \
  -sign \
  -binary \
  -signer <path_to_cert> \
  -inkey <path_to_key> \
  -certfile <path_to_ca-chain> \
  -outform DER \
  -in <path_to_file> \
  -out $1.der \
  -nodetach \
  -passin file:<path_to_file>
openssl smime -pk7out -binary -in $1.der -inform DER -out $1.pk7
cat $1.pk7 | openssl pkcs7 -text -noout -print_certs > $1.txt
```
* `OPENSSL=<path_to_openssl_0.9.8> run.sh old`
* `OPENSSL=<path_to_openssl_0.9.8> run.sh new`
* `diff old.txt new.txt`

You should notice the the order of certificates is different between versions.
0.9.8 generates: leaf, intermediate, root
1.0.0 generates: root, intermediate, leaf

**Comment by richsalz** [comment]
The order of entries should not be important, it's up to the application to build the right chain.
Both of these releases are no longer supported, sorry.  Closing this issue.

**Comment by jrchamp** [comment]
I'm using 1.0.2 and OCSP verification appears to require a certain order to be successful. Should I open a new issue for that?

**Comment by richsalz** [comment]
Or ask on the mailing list first, but yes.

**Comment by chrmod** [comment]
when mentioning 1.0.0 I was pointing to a moment on which the change happened. This situtation occurs in happens in 1.0.2 as well.

Also the order should not matter, but in some situations it does, in this case NSS interoperability.  

As potential solution may be just a configuration I will post it on mailing list. 

Any how, @richsalz this behaviour change is not documented or pointed in changelog, so people/software may be confused.

Note that Mac OS X is still distributed with 0.9.8zg
