### ISSUE TITLE
error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by abcdef123ghi** [openssl/openssl#8831]
I tried to decrypt a chipertext which generated from Java with "DES/CBC/PKCS5Padding" encrypted and  base64 encoded and the string was     
 
"8kcQavvcw32znZUY5tPhiwgv8RBvZUZ4gY+V+ezjQV7f+o4YkEz17nyIhDfRMST2lo67CjDNBAGy
5twc2HqCNDM0hn3floYcoLhvpZCUS57i74CFW+orXmY6K/A2iq+CWs2EeMqe3YjtUmFr3qTS/WJn
8iWodjX9gw8mNTDPf3u4CRGkA+ixnw=="

the plain text was
{"resultCode":"1000","returnObj":{"batchNo":"2019042608242878","serialNo":"0e8fdfcb-9acd-440e-a845-d5ddeaeeba02","stateFlag":"0"}}

 I tried to decrypt it with the follwoing code,it doesn't work,the error was  
      "error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length" 
     when it executed in the line of  EVP_DecryptFinal_ex,I have no idea what wrong I have done yet,please take a look at my code,I checked the code was exactly like the example which was within OpenSSL wiki

    int decryptdate(string encryptdatas, string & decryptdatas)
    {
	const unsigned char iv[8] = { 'Q', 'w', 'e', 'r', '1', '2', '3', '4' };

	const unsigned char key[8] = { 'A', 'a', '1', '2', '3', '!', '@', '#' };

	const char* pCipherTextBase64 = encryptdatas.c_str();
	unsigned int ulRc = 0;
	int iTextLen = strlen(pCipherTextBase64); 
	unsigned int uLen = 0;
	unsigned char* pUnBase64 = new unsigned char[iTextLen];  
	unsigned char* pPlainText = NULL;  

	int i = 0;

	memset(pUnBase64, 0, iTextLen);
	ulRc = ns_ls::base64_decode((BYTE*)pCipherTextBase64, iTextLen, pUnBase64, uLen);//base64 decoded
	printf("decrypt uLenBuf = %d\n", uLen);

	pPlainText = new unsigned char[uLen + 1];
	memset(pPlainText, 0xff, uLen + 1);

	int outl;  
	int outl2;  
	int rv;
	EVP_CIPHER_CTX * ctx;
	ctx = EVP_CIPHER_CTX_new();
	 
	rv = EVP_DecryptInit_ex(ctx, EVP_des_cbc(), NULL, key, iv);

	if (rv != 1) {
		EVP_CIPHER_CTX_cleanup(ctx);
		return -1;
	}

	 
	rv = EVP_DecryptUpdate(ctx, pPlainText, &outl, pUnBase64, uLen); 

	if (rv != 1) {
		EVP_CIPHER_CTX_cleanup(ctx);
		return -1;
	}

	 
	rv = EVP_DecryptFinal_ex(ctx, pPlainText + outl, &outl2);

	if (rv != 1) {
		string errstr = ERR_error_string(ERR_get_error(), NULL);

		fprintf(stderr, "ERROR: EVP_CIPHER_CTX_new failed. OpenSSL error: %s\n",
			ERR_error_string(ERR_get_error(), NULL));
		EVP_CIPHER_CTX_cleanup(ctx);
		return -1;
	}

	iTextLen = (outl + outl2);
	EVP_CIPHER_CTX_cleanup(ctx); 
	return 0;
    }

lsbase64.h

    #if !defined(AFX_LSBASE64_H__28E02995_79BF_48B8_9809_9A575CB7E700__INCLUDED_)
    #define AFX_LSBASE64_H__28E02995_79BF_48B8_9809_9A575CB7E700__INCLUDED_

    #if _MSC_VER > 1000
    #pragma once
    #endif // _MSC_VER > 1000

    namespace ns_ls
    {
	   unsigned int base64_encode(const unsigned char* bytes_to_encode, unsigned int in_len, unsigned char* encoded_buffer, unsigned int& out_len);
	   unsigned int base64_decode(const unsigned char* encoded_string, unsigned int in_len, unsigned char* decoded_buffer, unsigned int& out_len);
    }

     #endif 

lsbase64.cpp

     #include <stdlib.h>
     #include <stdio.h>
     #include <iostream>
     #include <string.h>
     #include "lsbase64.h"

 

     using namespace std;
     namespace ns_ls
     {
	     static const std::string base64_chars =
		"ABCDEFGHIJKLMNOPQRSTUVWXYZ"
		"abcdefghijklmnopqrstuvwxyz"
		"0123456789+/";

	static inline bool is_base64(unsigned char c)
	{
		return (isalnum(c) || (c == '+') || (c == '/'));
	}

	unsigned int base64_encode(const unsigned char* bytes_to_encode, unsigned int in_len, unsigned char* encoded_buffer, unsigned int& out_len)
	{
		int i = 0;
		int j = 0;
		unsigned char char_array_3[3] = { 0, 0, 0 };
		unsigned char char_array_4[4] = { 0, 0, 0, 0 };
		out_len = 0;

		while (in_len--) {
			char_array_3[i++] = *(bytes_to_encode++);

			if (i == 3) {
				char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
				char_array_4[1] = ((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4);
				char_array_4[2] = ((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6);
				char_array_4[3] = char_array_3[2] & 0x3f;

				for (i = 0; i < 4; i++) {
					encoded_buffer[out_len++] = base64_chars[char_array_4[i]];
				}

				i = 0;
			}
		}

		if (i) {
			for (j = i; j < 3; j++) {
				char_array_3[j] = '\0';
			}

			char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
			char_array_4[1] = ((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4);
			char_array_4[2] = ((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6);
			char_array_4[3] = char_array_3[2] & 0x3f;

			for (j = 0; j < (i + 1); j++) {
				encoded_buffer[out_len++] = base64_chars[char_array_4[j]];
			}

			while (i++ < 3) {
				encoded_buffer[out_len++] = '=';
			}
		}

		return out_len;
	}

	unsigned int base64_decode(const unsigned char* encoded_string, unsigned int in_len, unsigned char* decoded_buffer, unsigned int& out_len)
	{
		size_t i = 0;
		size_t j = 0;
		int in_ = 0;
		unsigned char char_array_3[3] = { 0, 0, 0 };
		unsigned char char_array_4[4] = { 0, 0, 0, 0 };
		out_len = 0;

		while (in_len-- && (encoded_string[in_] != '=') && is_base64(encoded_string[in_])) {
			char_array_4[i++] = encoded_string[in_];
			in_++;

			if (i == 4) {
				for (i = 0; i < 4; i++) {
					char_array_4[i] = static_cast<unsigned char>(base64_chars.find(char_array_4[i]));
				}

				char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
				char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
				char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

				for (i = 0; i < 3; i++) {
					decoded_buffer[out_len++] = char_array_3[i];
				}

				i = 0;
			}
		}

		if (i) {
			for (j = i; j < 4; j++) {
				char_array_4[j] = 0;
			}

			for (j = 0; j < 4; j++) {
				char_array_4[j] = static_cast<unsigned char>(base64_chars.find(char_array_4[j]));
			}

			char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
			char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
			char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

			for (j = 0; (j < i - 1); j++) {
				decoded_buffer[out_len++] = char_array_3[j];
			  }
		  }

		  return out_len;
	  }
     }

**Comment by mattcaswell** [comment]
```
ulRc = ns_ls::base64_decode((BYTE*)pCipherTextBase64, iTextLen, pUnBase64, uLen);//base64 decoded
printf("decrypt uLenBuf = %d\n", uLen);
```

What is the value of `uLen` at this point?

**Comment by mattcaswell** [comment]
I was able to decrypt your test data using OpenSSL command line.

Decode the base64 data:

````
$ openssl enc -base64 -d -in test.txt -out test.bin
````
And then decrypt it (the key and iv values are hex equivalents of those given in your code):
````
$ openssl enc -d -iv 5177657231323334 -K 4161313233214023 -in test.bin -des-cbc
````
This successfully decrypted the data just fine. I can't see an obvious problem in the decryption code so my suspicion is something in the base64 decode (You could always use the OpenSSL EVP_Decode* functions for this)

**Comment by mattcaswell** [comment]
Note that the "wrong final block length" error means that when you called EVP_DecryptFinal the total amount of data being decrypted wasn't >0 and a multiple of the blocksize (8 in the case of DES). From the command line decode of the base64 encrypted data I could see that the data was 136 bytes long (which is a multiple of 8), so it seems the ciphertext is good, but is somehow the incorrect length by the time you pass it to the EVP routines.

**Comment by abcdef123ghi** [comment]
> printf("decrypt uLenBuf = %d\n", uLen);

thanks for replying,it was 57

**Comment by mattcaswell** [comment]
> thanks for replying,it was 57

So, clearly the problem is in the base64 decode, since (as I noted above) we expect it to be 136.

**Comment by abcdef123ghi** [comment]
> 
> 
> > thanks for replying,it was 57
> 
> So, clearly the problem is in the base64 decode, since (as I noted above) we expect it to be 136.

thank you very much,I really appreciated it dude
