### ISSUE TITLE
output format of issuer and subject  changed while executing openssl cmd

### ISSUE THREAD

**Issue by mwlind** [openssl/openssl#8832]
Below is my quick test for  output format with different openssl version, the first is openssl-1.1.1 while second is v1.0.2 , 

```
$ openssl\@1.1/1.1.1b/bin/openssl x509 -noout -issuer -in ~/Downloads/zac.crt
issuer=C = US, O = CCC, OU = CCCA, CN = *.test01

$ openssl/1.0.2q/bin/openssl x509 -noout -issuer -in ~/Downloads/zac.crt
issuer= /C=US/O=CCC/OU=CCCA/CN=*.test01

P.S: the _-subject_ flag will get the same result
```

I am not sure whether this is a bug or design behavior, but the return format has changed after 1.1.0g(this is my earliest version in environment),   so need your double-confirm, thank you.

**Comment by InfoHunter** [comment]
The default name option of `x509` is changed from `compat` to `oneline`, via this commit: f1cece554ddf282f1512b4da04664467746ffd24.

If you want to get the "old" format back, you can just specify the name option explicitly as:

`openssl x509 -in some.crt -noout -issuer -nameopt compat`

**Comment by mwlind** [comment]
Thanks for your kindly explanation, i did get the old format using  the cmd you gave , i will close this issue.
