### ISSUE TITLE
HTTP Connect request failes when using -proxy, missing parameter

### ISSUE THREAD

**Issue by beusink** [openssl/openssl#886]
./opensslwrap.sh s_client -proxy my.local.proxy.nl:8080 -connect www.google.com:443 -showcerts -debug
CONNECTED(00000003)
write to 0x1a64a40 [0x1a65c00] (30 bytes => 30 (0x1E))
0000 - 43 4f 4e 4e 45 43 54 20-77 77 77 2e 67 6f 6f 67   CONNECT www.goog
0010 - 6c 65 2e 63 6f 6d 3a 34-34 33 0d 0a 0d 0a         le.com:443....
read from 0x1a64a40 [0x1a64bf0] (4096 bytes => 1448 (0x5A8))
0000 - 20 34 30 30 20 62 61 64-72 65 71 75 65 73 74 0d    400 badrequest.
0010 - 0a 56 69 61 3a 20 31 2e-30 20 31 34 35 2e 31 32   .Via: 1.0 111.11
0020 - 2e 31 2e 32 31 36 20 28-4d 63 41 66 65 65 20 57   .1.11 (McAfee W

Cause, missing HTTP/1.1 after CONNECT <url>, or at least it works when adding HTTP/1.1
apps/s_client.c

```
  case PROTO_CONNECT:
        {
            int foundit = 0;
            BIO *fbio = BIO_new(BIO_f_buffer());

            BIO_push(fbio, sbio);
            BIO_printf(fbio, "CONNECT %s\r\n\r\n", connectstr);
            (void)BIO_flush(fbio);
            /* wait for multi-line response to end CONNECT response */
            do {
```
Should be (something like)
 ```
 case PROTO_CONNECT:
        {
            int foundit = 0;
            BIO *fbio = BIO_new(BIO_f_buffer());

            BIO_push(fbio, sbio);
            BIO_printf(fbio, "CONNECT %s HTTP/1.1\r\n\r\n", connectstr);
            (void)BIO_flush(fbio);
            /* wait for multi-line response to end CONNECT response */
            do {
```

**Comment by Xpose87** [comment]
Its really good

**Comment by richsalz** [comment]
commit 8230f6c.  closing, thanks!
