### ISSUE TITLE
139634603738240:error:0E06D06C:configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:273:group=ca name=default_ca

### ISSUE THREAD

**Issue by LHY2355** [openssl/openssl#8865]
139634603738240:error:0E06D06C:configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:273:group=ca name=default_ca
 How can I do?

**Comment by LHY2355** [comment]
139837451364240:error:0E06D06C:configuration file routines:NCONF_get_string:no value:conf_lib.c:324:group=ca name=default_ca

**Comment by levitte** [comment]
You can start with showing us the command you tried

**Comment by SamedHamma** [comment]
same problem , 
command : " openssl ca -extensions v3_ca -out server.CA-signed.crt -keyfile server.CA.key -verbose -selfsign -md sha256 -enddate 330630235959Z -infiles server.CA.csr "

**Comment by kuan51** [comment]
I ran into a similar error message when deploying an internal CA. Here is the conf I am using: [openssl.cnf.txt](https://github.com/openssl/openssl/files/3506193/openssl.cnf.txt). Private key file exists and all commands are run as root. Private key has 0400 permissions. 

Cmd: 
```
openssl ca -config openssl.cnf -extensions v3_intermediate_ca -days 3650 -notext -md sha256 -in ica/csr/ica.csr.pem -out ica/crt/ica.crt.pem
```

Output: 
```
Using configuration from openssl.cnf
variable lookup failed for RealCrypto CA::private_key
139758319423936:error:0E06D06C:configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:273:group=RealCrypto CA name=private_key
```

Dir and File Structure:
```
ca
├── crl
├── crt
│   └── ca.crt.pem
├── ica
│   ├── crl
│   ├── crlnumber
│   ├── crt
│   ├── csr
│   │   └── ica.csr.pem
│   ├── index.txt
│   ├── newcrt
│   ├── openssl.cnf
│   ├── openssl_ica.cnf.bak
│   ├── private
│   │   └── ica.key.pem
│   └── serial
├── index.txt
├── newcrt
├── openssl.cnf
├── openssl_root.cnf.bak
├── private
│   └── ca.key.pem
└── serial
```

**Comment by levitte** [comment]
This is the problematic line:

```
default_ca = RealCrypto CA
```

The `default_ca` is supposed to be the name of a section (called "group" in the error message), i.e something starting with a line like this:

```
[RealCrypto CA]
```

Since there isn't one, it can't process what you want further.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
