### ISSUE TITLE
EVP_aes_[128|256]_cbc_hmac_sha256() returns NULL

### ISSUE THREAD

**Issue by mirkop** [openssl/openssl#8873]
OpenSSL Versions:
* 1.1.0g
* 1.1.1b

I downloaded the source and made my own builds.

The function to get the ciphers `EVP_CIPHER *EVP_aes_[128|256]_cbc_hmac_sha256()` always returned `NULL`. If I use the equivalant function for `sha1`, it returns a valid pointer.

After looking at the code, I noticed that the `sha256` version of the function makes a call to a function `aesni_cbc_sha256_enc` as a part of the ternary statement. The equivalent code for the `sha1` version does not do that check.
https://github.com/openssl/openssl/blob/25b25b0f80f2b3f0c5449a6d5a8e7639187f9bf3/crypto/evp/e_aes_cbc_hmac_sha256.c#L927-L939

This is the function declaration for `aesni_cbc_sha256_enc`. It shows that it returns an `int`.
https://github.com/openssl/openssl/blob/25b25b0f80f2b3f0c5449a6d5a8e7639187f9bf3/crypto/evp/e_aes_cbc_hmac_sha256.c#L54-L56

However, if you look here at the comment for the implementation of `aesni_cbc_sha256_enc`, it indicates that the function returns `void`. I could not tell if the code actually returns a value.
https://github.com/openssl/openssl/blob/25b25b0f80f2b3f0c5449a6d5a8e7639187f9bf3/crypto/aes/asm/aesni-sha256-x86_64.pl#L95-L102

After I removed the call to `aesni_cbc_sha256_enc` from the `if` statement, the functions `EVP_CIPHER *EVP_aes_[128|256]_cbc_hmac_sha256()` returned valid cipher pointers. It also worked properly for encryption and decryption.

I'm not sure if the call to `aesni_cbc_sha256_enc` should be removed or not, but it worked for me. I will let the OpenSSL experts make that decision.

**Comment by mirkop** [comment]
I guess that the permalink only works in comments.

`EVP_CIPHER *EVP_aes_[128|256]_cbc_hmac_sha256()`
https://github.com/SurePassId/openssl/blob/66790d762562aec139daa5ed321e380c687608e4/crypto/evp/e_aes_cbc_hmac_sha256.c#L927-L939

This is the function declaration for `aesni_cbc_sha256_enc`.
https://github.com/SurePassId/openssl/blob/66790d762562aec139daa5ed321e380c687608e4/crypto/evp/e_aes_cbc_hmac_sha256.c#L54-L56

comment for the implementation of `aesni_cbc_sha256_enc`
https://github.com/SurePassId/openssl/blob/66790d762562aec139daa5ed321e380c687608e4/crypto/aes/asm/aesni-sha256-x86_64.pl#L95-L102

**Comment by mattcaswell** [comment]
Stitched ciphers are not available on all platforms. If your hardware cannot support them then these functions will return NULL. These ciphers are in fact specialist ciphers intended for use by libssl only.

So this is expected behaviour.
