### ISSUE TITLE
what's the diff 1.1.1b vs 1.0.2f

### ISSUE THREAD

**Issue by cosmos33** [openssl/openssl#8884]

**Comment by cosmos33** [comment]
ndk : android-ndk-r14b 
i use 1.1.1b build dynamic lib, work fine.  1.0.2f or 1.0.2o build dynamic lib, program will crash

**Comment by mattcaswell** [comment]
OpenSSL 1.0.2 and 1.1.1 are not binary compatible - and there are very significant differences between the two library versions. You will need to use code specifically compiled for the version in question.
