### ISSUE TITLE
OCSP utility requires issuer bundle to be in leaf-first order

### ISSUE THREAD

**Issue by jrchamp** [openssl/openssl#889]
If you use the certificate chain bundle as the issuer input, the file must be in leaf-first order.

```
$ ocsp -noverify -no_nonce -issuer myissuer -cert mycert -url `openssl x509 -noout -ocsp_uri -in mycert` -text
mycert: good
        This Update: Mar 16 02:23:10 2016 GMT
        Next Update: Mar 20 02:23:10 2016 GMT
```

Reversing the order of the certificates in the chain bundle results in failure:

```
$ ocsp -noverify -no_nonce -issuer myissuer_rev -cert mycert -url `openssl x509 -noout -ocsp_uri -in mycert` -text
Responder Error: unauthorized (6)
```

By using the OCSP request parser `$ openssl ocsp -reqin myocsp.req -text`, it appears that the Issuer Key Hash is being incorrectly selected from those available in the input file.

Tested using:

```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by jrchamp** [comment]
Example of a real world effect: I had the same issue when I was enabling OCSP Stapling on an F5. I needed to reverse the order of the certificate bundle in order for the OCSP response to succeed. Now that I know, I can work around it, but it was a frustrating time sink and symptomatic of incorrect behavior.

**Comment by levitte** [comment]
Appologies for the really slow response...

Actually, only the first certificate is read from the `-issuer` file, so yes, it's assumed to contain the issuer cert only, not the whole chain.

**Comment by wordpress219** [comment]
> Appologies for the really slow response...
> 
> Actually, only the first certificate is read from the `-issuer` file, so yes, it's assumed to contain the issuer cert only, not the whole chain.

It's useless.
