### ISSUE TITLE
ciphers issue with master 2019-05-07

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#8895]
With current master PKIX-SSH test try-ciphers pass all tests with
"test try ciphers: cipher 3des-cbc mac *mac-*"
, but hang on 
"test try ciphers: cipher aes128-cbc mac hmac-sha1"

Hint: see issue #8565 for details how to configure and run test. Test is the same but error is new one.

10x for fixing previous one.

**Comment by levitte** [comment]
So uhmmm, which script is it that generates this output?

**Comment by petrovr** [comment]
Richard Levitte wrote:
> So uhmmm, which script is it that generates this output?
> 

Test is the same as mentioned in #8565 . Script is regress/try-ciphers.sh .
It could be run with command:
  make -e LTESTS=try-ciphers REGRESS_TARGETS=t-exec tests

Definitely commit 
https://github.com/openssl/openssl/commit/7556b9df597ce43c1c31b294512d5146560f37c6 
( issue #8604 ) resolves previous report.
So something after 3 Apr introduce new breakage.

Regards,
Roumen

**Comment by petrovr** [comment]
Ping?

- test past  with commit f2dbb71cb6bf6cd570f96e7663a22dd87854f08b / Richard Levitte<levitte@openssl.org> /  "providers/common/digests/sha2.c: forward declare all dispatched functions"
- then there is series of 8 commits with author Matt Caswell<matt@openssl.org> related to AES and default provider that end with commit 819a7ae9fc7721f675757c0925821f91b20dfc8f
=> no surprise "move to providers adds regression"

**Comment by petrovr** [comment]
Is provider functionality stateless?

**Comment by petrovr** [comment]
Two months, no fix?
Dunno what to think about quality of some "enhancements". I guess that is clear that I'm disappointed from constant degradation of project quality. It seems to me team members spend time for non significant (cosmetic) or valueless updates.

Commit like this one 718b133a5328108099ecac0bf40d8fd4886e7b64 (Implement AES CBC ciphers in the default provider) changes management of initialization vector.

There is one secure shell functionality  - privilege separation (please search internet for details). One unprivileged process start encrypted communication and when authentication process finish deserialize its "state". In mean time is started another "session" process that serialize "state" and continue with management of user session.

Actually above mentioned commit breaks "deserialization" of cipher.

**Comment by petrovr** [comment]
Rest case - sample from https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption plus 
```diff
--- Evp-symmetric-encrypt.c     2019-07-03 14:59:09.000000000 +0300
+++ Evp-symmetric-encrypt2.c    2019-07-08 20:24:31.686803256 +0300
@@ -107,6 +107,12 @@
         handleErrors();
     ciphertext_len += len;
 
+{   /* broken by https://github.com/openssl/openssl/commit/718b133a5328108099ecac0bf40d8fd4886e7b64 */ 
+    int iv_len = EVP_CIPHER_CTX_iv_length(ctx);
+    fprintf(stderr, "iv[%d]:\n", iv_len);
+    BIO_dump_fp (stderr, EVP_CIPHER_CTX_iv(ctx), iv_len);
+}
+
     /* Clean up */
     EVP_CIPHER_CTX_free(ctx);
 
```
Expected output: 
==============================
$ ./Evp-symmetric-encrypt2
iv[16]:
0000 - 2c 8e 65 a9 92 36 ec 92-07 04 91 5c f1 a9 8a 44   ,.e..6.....\...D
Ciphertext is:
0000 - e0 6f 63 a7 11 e8 b7 aa-9f 94 40 10 7d 46 80 a1   .oc.......@.}F..
0010 - 17 99 43 80 ea 31 d2 a2-99 b9 53 02 d4 39 b9 70   ..C..1....S..9.p
0020 - 2c 8e 65 a9 92 36 ec 92-07 04 91 5c f1 a9 8a 44   ,.e..6.....\...D
Decrypted text is:
The quick brown fox jumps over the lazy dog
==============================

**Comment by petrovr** [comment]
P.S. current for iv is :
0000 - 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ................

**Comment by levitte** [comment]
There's a lot of new development happening in master right now, so it's not a big surprise that it isn't always as stable as one might want, and that we miss corner cases.  Thanks for catching them!

I'm a little concerned, though, that we don't already catch this with the current EVP tests.  Are there interesting test cases we should add?  That could be subject for a PR.

> Commit like this one 718b133 (Implement AES CBC ciphers in the default provider) changes management of initialization vector.

I'll see if I can figure that out.  The wiki example breaks, you say?

**Comment by levitte** [comment]
> Is provider functionality stateless?

Yes and no.  It's actually up to the provider...  it *can* give back a provider context on init, and hold state in that context.  Every set of dispatch function also has some kind of context creator, where it can hold state for a run of the algorithm...  this is the case for ciphers, digests, etc (obviously, or the init/update/final sequence would simply be impossible).

**Comment by levitte** [comment]
Ah, yeah, I see what's going on there...  the changes aren't quite complete.

**Comment by levitte** [comment]
(digests in providers are similarly broken for the moment, I might add...  I've some work going on to clear that up, but have a few other items on my plate as well...)

**Comment by petrovr** [comment]
Richard Levitte wrote:
> [SNIP]
> I'm a little concerned, though, that we don't already catch this with the current EVP tests.  Are there interesting test cases we should add?  That could be subject for a PR.
based on previous
There is test that uses test/recipes/30-test_evp_data/evpciph.txt


> 
>> Commit like this one 718b133 (Implement AES CBC ciphers in the default provider) changes management of initialization vector.
> 
> I'll see if I can figure that out.  The wiki example breaks, you say?

Wiki sample work fine. It was most simple way to show issue.

> 

Existing test could be changed to check for IV after initialization 
and/or encryption.
After "move to provides" EVP_CIPHER_CTX_iv(...) always return zeroes.


Roumen

**Comment by levitte** [comment]
#9324 adds a very simple test for this.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> #9324 adds a very simple test for this.
> 
Yep, initialization test is enough for now.

I wonder why move to providers is activated. In the past there was 
"EXPERIMENTAL" functionality. I'm concerned by TODO(3.0) comment. So it 
seems to me this development fails into this category but is not marked 
as experimental :(.

Roumen

**Comment by petrovr** [comment]
Issue is now superseded from other, so closing.
