### ISSUE TITLE
CRYPTO_AES_CTR define/enum compatibility with FreeBSD, OpenBSD and cryptodev-linux

### ISSUE THREAD

**Issue by Retropotenza** [openssl/openssl#8911]
Hello,

I've noticed that in https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/engine/eng_cryptodev.c the CRYPTO_AES_CTR is used for a preprocessor check.

In OpenBSD https://github.com/openbsd/src/blob/master/sys/crypto/cryptodev.h is indeed declared with a #define.

In cryptdev-linux in instead declared in an enum, which makes it not defined for the preprocessor.

Looking in more recent version of OpenSSL:

https://github.com/openssl/openssl/blob/master/engines/e_devcrypto.c

if a CRYPTO_ALGORITHM_MIN define is declared CRYPTO_AES_CTR is then handled as a define.

CRYPTO_ALGORITHM_MIN is defined on FreeBSD:

https://github.com/freebsd/freebsd/blob/master/sys/opencrypto/cryptodev.h#L167

But it isn't on OpenBSD:

https://github.com/openbsd/src/blob/master/sys/crypto/cryptodev.h

What do you think about changing:
```
#ifdef CRYPTO_ALGORITHM_MIN
# define CHECK_BSD_STYLE_MACROS
#endif
```
in
```
#if CRYPTO_ALGORITHM_MIN < CRYPTO_ALGORITHM_MAX
# define CHECK_BSD_STYLE_MACROS
#endif
```

This will work on FreeBSD where both values are known to the preprocessor, on OpenBSD where CRYPTO_ALGORITHM_MIN will be automatically set to 0, lower than the defined CRYPTO_ALGORITHM_MAX, and with cryptodev-linux where CRYPTO_ALGORITHM_MAX for the preprocessor will fall back to (0 - 1).

What about adding the above, and the check below also to the 1.0.2 OpenSSL branches?

```
#if !defined(CHECK_BSD_STYLE_MACROS) || defined(CRYPTO_AES_CTR)
```

Thanks,
Vincenzo

**Comment by levitte** [comment]
I like your ideas for the guard around the definition of `CHECK_BSD_STYLE_MACROS`, another idea would be to just:

``` C
#ifdef CRYPTO_ALGORITHM_MAX
# define CHECK_BSD_STYLE_MACROS
#endif
```

Regarding 1.0.2, it's on its last year of support, which means we only make directly security related fixes on that branch...  and this is rather a building problem as far as I can see.

**Comment by Retropotenza** [comment]
I thought about that, but `CRYPTO_ALGORITHM_MAX` is defined in cryptodev-linux (and not part of the enums):

https://github.com/cryptodev-linux/cryptodev-linux/blob/f971e0cd4a0ebe59fb2e8e17240399bf6901b09b/crypto/cryptodev.h#L57

**Comment by levitte** [comment]
Argh, right...
