### ISSUE TITLE
trying to compile openssl on debian libssl.so.1.1 & libcrypto.so.1.1

### ISSUE THREAD

**Issue by blub4747** [openssl/openssl#8913]
Hello,

I am trying to build the latest version of openssl on a Raspberry Pi 3b+ in Raspbian
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

and when ran the usually three complication commands eg 
./config, make, make install
When I than ran a openssl version
I got the following error message.

```
openssl: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
openssl: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
```

I therefore checked /usr/lib/arm-linux-gnueabihf/ and /home/blub/openssl-1.1.1b 
and both files are present in both locations.

/usr/lib/arm-linux-gnueabihf/
```
ls -la libcr*
-rw-r--r-- 1 root root   41292 Feb  6 22:17 libcrypt.a
-rw-r--r-- 1 root root 1501512 Feb 27 21:58 libcrypto.so.1.0.2
-rw-r--r-- 1 root root 1848612 Nov 28 23:43 libcrypto.so.1.1
lrwxrwxrwx 1 root root      38 Feb  6 22:17 libcrypt.so -> /lib/arm-linux-gnueabihf/libcrypt.so.1

ls -la libssl*
-rw-r--r-- 1 root root 320932 Feb 27 21:58 libssl.so.1.0.2
-rw-r--r-- 1 root root 332080 Nov 28 23:43 libssl.so.1.1
```

/home/blub/openssl-1.1.1b 

```
ls -la libssl*
-rw-r--r-- 1 root root 676876 May 10 12:23 libssl.a
-rw-r--r-- 1 root root  16073 May 10 12:25 libssl.map
-rw-r--r-- 1 root root    270 May 10 12:25 libssl.pc
lrwxrwxrwx 1 root root     13 May 10 12:25 libssl.so -> libssl.so.1.1
-rwxr-xr-x 1 root root 541116 May 10 12:25 libssl.so.1.1

ls -la libcrypto.*
-rw-r--r-- 1 root root 3820188 May 10 12:20 libcrypto.a
-rw-r--r-- 1 root root  126906 May 10 12:24 libcrypto.map
-rw-r--r-- 1 root root     291 May 10 12:25 libcrypto.pc
lrwxrwxrwx 1 root root      16 May 10 12:24 libcrypto.so -> libcrypto.so.1.1
-rwxr-xr-x 1 root root 2657208 May 10 12:24 libcrypto.so.1.1
```

Can someone please tell me how to resolve this issue ?

Thank you, blub4747

**Comment by levitte** [comment]
It's unclear to me what openssl command you used.  Was it `openssl version` (i.e. effectively `/usr/bin/openssl version`) or `/home/blub/openssl-1.1.1b/apps/openssl version`.  Have you checked with `ldd` that those two binaries are getting the expected shared libraries?

**Comment by vdukhovni** [comment]
On platforms that have an existing OpenSSL library on the default ld.so search path, custom OpenSSL libraries are sometimes best built as "shlib_variant" libraries, in which the SONAME and all the symbol versions differ from the installed default.  Such libraries don't conflict with the deployed platform libraries and can even coëxist with the platform's library int the same process.  Applications linked against the variant library will load the correct shared executables as a result of the non-default SONAMEs.

See https://github.com/openssl/openssl/blob/master/Configurations/README#L130-L150

Coincidentally, @levitte and I were just discussing making this interface more accessible/better documented, even before I saw this issue.  If my reading of your problem is correct, and you're having trouble with "DLL-hell" on platforms that already have an OpenSSL 1.1.x, then "shlib_variant" may solve your problem.

**Comment by blub4747** [comment]
Hello,
It not does matter from which location in the filesystem I run the command 
openssl version
I always do get the same result.
Here is comes result from the ldd I just ran.
``root@compile-mit-prefix:/usr/bin # ldd -v openssl | grep libssl*
        libssl.so.1.1 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.1 (0x76ee9000)
                libssl.so.1.1 (OPENSSL_1_1_0) => /usr/lib/arm-linux-gnueabihf/libssl.so.1.1
        /usr/lib/arm-linux-gnueabihf/libssl.so.1.1:
root@compile-mit-prefix:/usr/bin # ldd -v openssl | grep libcr*
        libcrypto.so.1.1 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1 (0x76c84000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76b09000)
                libc.so.6 (GLIBC_2.15) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_2.7) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
                libcrypto.so.1.1 (OPENSSL_1_1_0) => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
                libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
                libcrypto.so.1.1 (OPENSSL_1_1_0d) => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
                libcrypto.so.1.1 (OPENSSL_1_1_0i) => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
                libcrypto.so.1.1 (OPENSSL_1_1_0f) => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
                libcrypto.so.1.1 (OPENSSL_1_1_0) => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
        /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1:
                libc.so.6 (GLIBC_2.7) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_2.17) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
        /lib/arm-linux-gnueabihf/libc.so.6:
root@compile-mit-prefix:/usr/bin #

Hope it help's

**Comment by levitte** [comment]
Ah, I didn't  otice that you installed too. This means that the command you run when you type `openssl version` is /usr/local/bin/openssl. If the command was `/usr/bin/openssl version`, I assume it would not error.

There are two viable options to handle this. One is to configure `ld.so` to consider /usr/local/lib, see `man ld.so.conf`. The other is to configure with a run path and rebuild, see [NOTES. UNIX](https://github.com/openssl/openssl/blob/master/NOTES.UNIX)

**Comment by sleshJdev** [comment]
I am experiencing the same [problem](https://unix.stackexchange.com/questions/535072/dhclient-openssl-1-1-1/535116?noredirect=1#comment992246_535116). A guy suggested me to remove component one by one, but I fear that this can break my system as even relocating one file resulted that my internet connection stop working. Currently I have two openssl binaries:
```
$ ldd /usr/bin/openssl 
/usr/bin/openssl: /usr/local/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/bin/openssl)
/usr/bin/openssl: /usr/local/lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/bin/openssl)
    linux-vdso.so.1 (0x00007fff51c8d000)
    libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007fae707f5000)
    libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007fae7036a000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fae70342000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fae70321000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fae70160000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fae70b1c000)

$ ldd /usr/local/bin/openssl 
    linux-vdso.so.1 (0x00007ffe851f3000)
    libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007fc91d4ba000)
    libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007fc91d02f000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc91d007000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc91cfe6000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc91ce25000)
   /lib64/ld-linux-x86-64.so.2 (0x00007fc91d72a000)
```

I suspect that I have to remove `/usr/local/lib` somehow. Could someone aware openssl team member guide me on how to do it safely to not break my system? I'd be very appreciated.

Here is some information about system:
```
$ uname -a
Linux debian 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by richsalz** [comment]
Do *NOT* replace system components.  Configure, build, install into some other place (like /usr/local) and have your other things look in that other place.

**Comment by sleshJdev** [comment]
Ok, I'll take into account your advice. But could you please help me handle the current situation I found myself?

**Comment by richsalz** [comment]
I cannot help you; I don't know enough details about Debian, sorry.

**Comment by sleshJdev** [comment]
It's a pity... Maybe you could conduct me to someone who can help?

**Comment by richsalz** [comment]
Try some debian forums?  I have no idea.  Maybe someone else in this community can help.  I don't know.

**Comment by vdukhovni** [comment]
> Ok, I'll take into account your advice. But could you please help me handle the current situation I found myself?

Force-reinstall the base Debian OpenSSL packages.  If you're on Debian "stretch", <https://packages.debian.org/source/stretch/openssl>, they are:

```
        openssl
        libssl1.1
        libssl-dev
        libssl-doc

    # apt-get install --reinstall openssl libssl1.1 libssl-dev libssl-doc
```
Then install any non-default OpenSSL libraries in "/opt/openssl" or similar location that will not conflict with the base system. See my upthread comment about "shlib_variant" builds.

**Comment by sleshJdev** [comment]
@vdukhovni actually I already did it. I follow this [guid](https://askubuntu.com/a/1127228). May I ask to take a look at it? Is it looks correct for you? If so, I'll try one more time.

**Comment by vdukhovni** [comment]
What is it that you "already did"?  Your first task is to re-install original copies of the system OpenSSL packages in `/usr/{bin,lib,include,...}`.  Only then install a variant OpenSSL in /opt, but if you intend to link applications with that version, it may be prudent to make that a "shlib_variant" built, in order to avoid potential shared library conflicts when applications load system libraries that in turn load OpenSSL.

**Comment by sleshJdev** [comment]
I meant that I already tried to install the latest OpenSSL version in `/opt/openssl` according to [guide](https://askubuntu.com/a/1127228) I mentioned previously and it didn't help me get rid of _OPENSSL_1_1_1 version issue_. Likely I did something wrong, but not sure what exactly. I also tried to re-install the existing OpenSSL version with aptitude
```
 sudo aptitude reinstall openssl 
The following packages will be REINSTALLED:
  openssl 
0 packages upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 3 not upgraded.
Need to get 0 B/842 kB of archives. After unpacking 0 B will be used.
(Reading database ... 245193 files and directories currently installed.)
Preparing to unpack .../openssl_1.1.1c-1_amd64.deb ...
Unpacking openssl (1.1.1c-1) over (1.1.1c-1) ...
Setting up openssl (1.1.1c-1) ...
Processing triggers for man-db (2.8.5-2) ...
``` 
It also didn't help. What do I do wrong? Could you please advice some steps on how correctly resolve my issue?

**Comment by levitte** [comment]
The following two commands might answer a lot:

```
$ echo $LD_LIBRARY_PATH
$ echo $PATH
```

The trouble here is that `/usr/bin/openssl` seems to find `/usr/local/lib/libcrypto.so.1.1` (or presumably `/opt/openssl/lib/libcrypto.so.1.1` if you reinstalled your build there), and they

**Comment by sleshJdev** [comment]
Hi, @levitte 
```
$ echo $LD_LIBRARY_PATH
/opt/openssl/lib:
$ echo $PATH
/home/slesh/.rvm/gems/ruby-2.5.1/bin:/home/slesh/.rvm/gems/ruby-2.5.1@global/bin:/home/slesh/.rvm/rubies/ruby-2.5.1/bin:/home/slesh/bin:/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/java/jdk11/bin:/home/slesh/soft/gradle/bin:/home/slesh/soft/kotlinc/bin:/opt/scala-2.11.7/bin:/home/slesh/soft/activator-dist-1.3.10/bin:/home/slesh/.npm-global/bin:/home/slesh/soft/android/sdk/platform-tools:/home/slesh/soft/android/sdk/tools:/home/slesh/soft/apache-maven/bin:/opt/go:/opt/swarm/:/opt/geth/:/home/slesh/.rvm/bin:/home/slesh/.rvm/bin
```

The $LD_LIBRARY_PATH left after installation OpenSSL from sources. I've already removed OpenSSL from _/opt/openssl_.

**Comment by sleshJdev** [comment]
I tried this [gueid](https://www.howtoforge.com/tutorial/how-to-install-openssl-from-source-on-linux/) but seems unsuccessful. I still have the OpenSSL complains about OPENSSL_1_1_1 version mismatch:
```
$ openssl version
openssl: /usr/local/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
openssl: /usr/local/lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
$ /usr/local/bin/openssl.BACKUP version
OpenSSL 1.1.0  25 Aug 2016
$ /usr/bin/openssl.BACKUP version
/usr/bin/openssl.BACKUP: /usr/local/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/bin/openssl.BACKUP)
/usr/bin/openssl.BACKUP: /usr/local/lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/bin/openssl.BACKUP)
```  

Here is environment information:
```
$ echo $LD_LIBRARY_PATH 
/usr/loca/ssl/lib:
$ echo $PATH 
/home/slesh/.rvm/gems/ruby-2.5.1/bin:/home/slesh/.rvm/gems/ruby-2.5.1@global/bin:/home/slesh/.rvm/rubies/ruby-2.5.1/bin:/home/slesh/bin::/usr/local/ssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/java/jdk11/bin:/home/slesh/soft/gradle/bin:/home/slesh/soft/kotlinc/bin:/opt/scala-2.11.7/bin:/home/slesh/soft/activator-dist-1.3.10/bin:/home/slesh/.npm-global/bin:/home/slesh/soft/android/sdk/platform-tools:/home/slesh/soft/android/sdk/tools:/home/slesh/soft/apache-maven/bin:/opt/go:/opt/swarm/:/opt/geth/:/home/slesh/.rvm/bin:/home/slesh/.rvm/bin
```

Could you please advice?

**Comment by vdukhovni** [comment]
> I still have the OpenSSL complains about OPENSSL_1_1_1 version mismatch:
> 
> ```
> $ openssl version
> openssl: /usr/local/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
> openssl: /usr/local/lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)

Well, you say you removed/rebuilt `/opt/openssl`, but the complaint is about `/usr/local/lib/libssl`, which is neither from the Debian package, nor the version built with a `prefix` of `/opt/openssl`. And IIRC `/usr/local/lib` is on the default library search path in Debian.

Therefore, an incompatible OpenSSL runtime in /usr/local will cause problems. You'll have to uninstall the packages that are responsible for or dependent on `/usr/local/lib/libssl.so.1.1.`.

Frankly, the mess your system is in is not really OpenSSL-specific, the same set of issues can happen with any library once you start introducing incompatible versions, especially in locations on the default library search path.

Perhaps instead of doing your own builds you should look into "Nix" or a similar package manager that supports coexistence of multiple variants of the same software. That said, it is not for inexperienced users, do not use live systems you care about as the first place to experiment with Nix and the like...

I'd like to close this issue, you need Debian and basic sysadmin help, not OpenSSL help...

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
