### ISSUE TITLE
rand_win.c: check if BCryptGenRandom is present before using it

### ISSUE THREAD

**Issue by pps83rbx** [openssl/openssl#8915]
As [mentioned by HerMajestyDrMona](https://github.com/openssl/openssl/issues/8644#issuecomment-479388223) it might be useful for some if openssl wouldn't prevent your app from working on XP. At least the code could be guarded with a check to allow delay-loading of bcrypt.

**Comment by pps83** [comment]
https://github.com/openssl/openssl/pull/8916

**Comment by pps83** [comment]
PR #8916

**Comment by bernd-edlinger** [comment]
which one is your app?
I am on your side, but I need more data.

**Comment by nhorman** [comment]
Pr Author non responsive, closing
