### ISSUE TITLE
Unnecesary 'const'  openssl_ec_key_method

### ISSUE THREAD

**Issue by enigedev** [openssl/openssl#8918]
Hi,
I'm developing an EC and RSA engine. The problem occures as I try to use any of the 'EC_KEY_METHOD_set ' functions to substitute the default implementation with my own, hardware accelerated one. All of them result in segmentation fault. I analysed the source code and found, why the RSA part does work fine and EC does not. 

Comparing 'rsa_ossl.c' and 'ec_kmeth.c' I have found the following:

``` 
static RSA_METHOD rsa_pkcs1_ossl_meth = {
    "OpenSSL PKCS#1 RSA",
    rsa_ossl_public_encrypt,
    rsa_ossl_public_decrypt,     /* signature verification */
    rsa_ossl_private_encrypt,    /* signing */
    rsa_ossl_private_decrypt,
    rsa_ossl_mod_exp,
    BN_mod_exp_mont,            /* XXX probably we should not use Montgomery
                                 * if e == 3 */
    rsa_ossl_init,
    rsa_ossl_finish,
    RSA_FLAG_FIPS_METHOD,       /* flags */
    NULL,
    0,                          /* rsa_sign */
    0,                          /* rsa_verify */
    NULL,                       /* rsa_keygen */
    NULL                        /* rsa_multi_prime_keygen */
};
 ```

and 

```
static const EC_KEY_METHOD openssl_ec_key_method = {
    "OpenSSL EC_KEY method",
    0,
    0,0,0,0,0,0,
    ossl_ec_key_gen,
    ossl_ecdh_compute_key,
    ossl_ecdsa_sign,
    ossl_ecdsa_sign_setup,
    ossl_ecdsa_sign_sig,
    ossl_ecdsa_verify,
    ossl_ecdsa_verify_sig
};
``` 

The main difference is, that the EC_KEY_METHOD has the const modifier, which results in segfault as I attempt to modifiy it. So I tried to omit the 'const' modifier, compiled OpenSSL again and as far as I tested it, the api does work fine.

I think it's worth to change it in further releses.

**Comment by petrovr** [comment]
enigedev wrote:
> Hi,
> I'm developing an EC and RSA engine. The problem occures as I try to use any of the 'EC_KEY_METHOD_set ' functions to substitute the default implementation with my own, hardware accelerated one. All of them result in segmentation fault. I analysed the source code and found, why the RSA part does work fine and EC does not.
[SNIP}
> The main difference is, that the EC_KEY_METHOD has the const modifier, which results in segfault as I attempt to modifiy it. So I tried to omit the 'const' modifier, compiled OpenSSL again and as far as I tested it, the api does work fine.
[SNIP]

May be you code that creates key method is not correct .
Please, to create "modifiable" data structure use something like this : 
meth = EC_KEY_METHOD_new(EC_KEY_OpenSSL());

**Comment by asicminer001** [comment]
cheers

**Comment by paulidale** [comment]
All of the internal method tables are const.  If you need to modify one of these, the `EC_KEY_METHOD_ new` suggestion should work.  Remember to free it at the end.

**Comment by asicminer001** [comment]
MIDMi+n9klbmptJlIP2z1JOWRUsoqtQ5bMKyzeRBd1SNsua/kEOiMQd7/sea+ziPns11lPwjtjx88GYy60KBwpG5Q/k1W8A2G+znVvBd239fbbk8UcyBo3AOlxbrxYjkySgUDyMvlVN6NfjjRsTTUtsR8AHQobwhKnjTMYkMaEXuSxCamXNvpTRHHhcef0gMmKJJ6eJVEirl0UmvIkjliVtA+3ekDmimhK94Lbo+K8dQEq9gRLQu02hHswtj8Z1aPdqo3lpvzXM7UueIxyvIzztcI1MFz65dlOahKhPP21HQZupS6ahbcH68hpvFsNyyyrx0JjkUjvE5DL25HZrwrA

**Comment by asicminer001** [comment]
-----BEGIN PGP MESSAGE-----
Version: APG v1.1.1

hQIMA2bbs/rSIAQNARAAk+CskWa42fuqPHIKe5kk8Q8tIW4hp/WnHNCxD+0lcF0D
3zZh+DlRJEUqt4D9FQPYzuKyi+/pChODWDXzKpS5LLi7iSqoXUn8J6Fntiruhc3z
uUs12lm0kUvl7Gd9d+BWwrpx1KFsaaA+0Ff4uk7GjUuqDYLskCxuvONFVQfBJgvv
HcKY52GUin9W0x++25+WnGwHALggF2xmGsR1ftiuKdJpDyMZ0O1nDcsbH/jzgcLm
jRuDJkuUastEXzkyw6bjKVkZwtyCUxP1Ot+tHGPICyoH4B8TISiHu0uerycF16GS
9g4B6rh9m3k0i1cGxdWf05IKl3VOMWoqgMT3GnNwKxRYod/dHguy2395LzDinJ1D
8PfMAHAm8VUPwpBwoLw1dheRwPNs1APGWMLVQWryUr67b2lrPUCWJQD88q3zV3my
4k8PYGAVsuTRoMoIngW8ZGO9tRaZ92g4Ue6DIXhM5+Z/6608wl5ejBpTkTpEu3B3
m6UXZyXcNw6nP5fXEW3C8O9WHrbc0vcv0qSM9gORdWJS7U7oABSAK7oi8j9WTheP
8BQNveBfS1LOSPv5GI/XsTyQc3nEVWyOB597RKiAXVTRGV4XUo4Lt72xxlRsFSnL
gYeJkvgUm2QQntmb2EFOKGm8ATp9kFxfLe8IPoeZEDuG+rqAA/MpT1yu29lgdiaF
AYwDuUPisyaQzX4BC/9GYfM6N32APS6uOd7we4JIyxtq3uF6BTYE0fExKROLxnbC
Xw93H5w6bc5Tn++SFbB/6lMJLTdt6oAU5kLdybnSzy2U7JPR/CG95CoOkw+/IRDm
pjEnPLGbJvsZ3tM8jwSBN1keVFxIPsb8QcDdzOjZ6usuB3aLFEuJWrwJepYjSOjT
LNSMMeKVeJC/s7FAyNFzelTvaT68CupL6/Tk+bHlve/pC4N6w9Xk+XJ2DOLqpfzr
IrniT6PMQq6urviB2N7WCTx2ltRN1ThwtG/fgZez6QfKMi5KCJr+XlNyS6h0yKvt
l7jFo99g89WKGcTZPxhrC5MZ5kOVZ2bWUNChZRH3ZY4kjm1O63WMrr3Zwyamuxmy
7pL9uSRABKHlBovbMv/Z48GJ6UEHlAlYJDvcZ/1hvyVfvYR2rSn4Abz7RHs0Ht6U
zYTaxK4pLlo7Furu25BoQ5X+V2bvYHU+85szRtb0yg2UTZF/KhyXTLfwDb6/Lvcr
vrmRxXNrvVbe+tuUpirSwe0BjbZ2pR3CJDyGSjh6yB0FI2MSgEPSaf1dzg0matOY
cmn+39NdZkhPnKteaUUsCs7Hauol6T6p5NxqX8Dz1ve4NQR6PNcUeXIT6g9kzshw
Ur7DXMRsTzconbI0RkRblMNxaM1ofSHGeMjs9ldiDRjKB9jKF13EwQT4Dp573vfy
FP9/8e19aJIbMVMOfa2X5QG3Js6F6NOIaiXpm4/NMYyJuCx+PTdmB9N34OwScc0/
jnHr4v5oT48/o8px7y5N6E6W/6WO16HHGNCjINt8AykyKi6XMlHUk9qsROf9yyhH
aQ8d+X+0qCADjCDTfZREf9CbdkjPBHR+FoJ/aqKsGr+aL2GLW2tx1i3D2HCOYbcQ
nf8f027cFqT9Pd43cmR504FVKJfNXjN1cK/EYCDGKJ5A7Ywd51Jw20RxSvraixti
kgeTFwnW0Ie7333Z22jGsk05vuHCaWofuEDXiHtitaSDjBwHualbAbBSvzVh3HAn
Soarc6YaCHuB07CcdWk8ylbvl4Bhl+ljywFchRajjz7SmFQs8e6Bcjs1hayhnbXG
YRpYLBu6l+wFFKpr75yeaKsArMODGlxEzSSoNmARNjbhGbq7cJh+Yv620ePGa1Ds
rjEnU3PwLfUF0myAVLGHlnItW47BxhCktCSguSDD1yJSPbFpC7uqMPfMAwCL2v0p
wZly2P3fyfCLe4/QuHVfFnTaYKuq8Iz1acOLxkFnYOgc95G01UPdsXhAHQMYjgl+
Trjfh0oKdxqTV5Ey31OXJeNpigPIugLQYX14gVN8qXDeUNvn+NJqBeQb3Npnvobh
gqFcyMeeX7UmTySEUnjDPAVppU42rA6DurJ0bQbKYaCIP6ihs1M7oUY3zwKUz85U
DUviwGpDzdHnI5fQWrhtXxzLKeCfguNLrpNNHt1J
=O/di
-----END PGP MESSAGE-----

**Comment by asicminer001** [comment]
USER_COMMENT=
ANDROID_VERSION=9
APP_VERSION_NAME=1.5.5.1
BRAND=HUAWEI
PHONE_MODEL=INE-LX2
CUSTOM_DATA=
STACK_TRACE=android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.manichord.mgit/files/diff/ab05907dce11e4dd89467d98aaf6fd096d51af0d.diff exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1996)
	at android.net.Uri.checkFileUriExposed(Uri.java:2378)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:963)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10425)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10410)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1744)
	at android.app.Activity.startActivityForResult(Activity.java:4786)
	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
	at android.app.Activity.startActivityForResult(Activity.java:4726)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
	at android.app.Activity.startActivity(Activity.java:5147)
	at android.app.Activity.startActivity(Activity.java:5115)
	at me.sheimi.android.activities.SheimiFragmentActivity.startActivity(SheimiFragmentActivity.java:262)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at android.support.v7.widget.ShareActionProvider$ShareMenuItemOnMenuItemClickListener.onMenuItemClick(ShareActionProvider.java:371)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:321)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1228)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3228)
	at android.widget.AbsListView$3.run(AbsListView.java:4204)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

Sent from my Huawei phone

**Comment by asicminer001** [comment]
Sent from my Huawei phone

**Comment by asicminer001** [comment]
Please open the Bisq desktop app on your computer and go to Account -> Notifications. Then copy this Pairing token into the field "Pairing token":

android|HUAWEI INE-LX2|RzW0RHAzQMeyUqYg4vkfyWGbHeM+8kU5|e9zb6mtUAM8:APA91bH1t2xD9NdmVAAWAWKbgr6yz6fzjAPSmFqoCym9_pyxMVhDyaBwvdvR3-ZP4n72SXTOKga4g_MkScUX2lu4RIjCIksyKC3BxTV82L9cN6KuzwhmrzDlPVIk9g8oGZzzzFVpOhSY

The pairing token contains your excryption key (AES/CBC/NOPadding with initialization vector) which is used by Bisq to encrypt the notifications for you and a token from Google that identifies this app.Sent from my Huawei phone
