### ISSUE TITLE
x509 and x509v3 directories are intermixed and should perhaps be combined

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#8919]

**Comment by richsalz** [comment]
yes, flip a coin to see which directory survives. :)

**Comment by paulidale** [comment]
`x509ii` :)

**Comment by vdukhovni** [comment]
Make symlinks? :-)  I am very sympathetic to the observation, the split is arbitrary, and non-v3 is ancient history. However, I am concerned that we'd make it more difficult for folks to main cross branch patches, for a somewhat cosmetic reason.  So both making the change and not making it have similar appeal to me...

**Comment by levitte** [comment]
I don't quite understand in what way symlinks will help.

**Comment by vdukhovni** [comment]
Symlinks can give the appearance of having all the files in the same directory. This is not a suggestion for the master copy, just a convenience a user can create for himself while working with the files.  Not a serious suggestion, but perhaps someone might actually find it better than nothing...

**Comment by levitte** [comment]
#8925 is my attempt.

**Comment by richsalz** [comment]
And perhaps do something with #8211 which is similar.
