### ISSUE TITLE
Performance regression b/w 1.0.2o and 1.0.2q for signing ec384 type certs

### ISSUE THREAD

**Issue by eraymond00** [openssl/openssl#8924]
I've replicated this regression on a standard Centos7.3 VM on an ESXi 6.7 host, and I'm seeing the following results. I've downloaded the official tarball from ftp.openssl.org for each version, built with the default config of each version, and ran the same speed tested, isolated to a single core. The results are below:

bash-4.2# taskset 0x10 openssl speed -multi 8 ecdsap384

OpenSSL 1.0.2o 27 Mar 2018
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx)
compiler: gcc I. -I.. -I../include -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,-noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
sign verify sign/s verify/s
rsa 2048 bits 0.000725s 0.000021s 1378.8 47765.0
sign verify sign/s verify/s
384 bit ecdsa (nistp384) **0.0002s** 0.0008s **5045.4** 1204.9

bash-4.2# taskset 0x10 openssl speed -multi 8 ecdsap384

OpenSSL 1.0.2q 20 Nov 2018
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx)
compiler: gcc I. -I.. -I../include -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,-noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
sign verify sign/s verify/s
rsa 2048 bits 0.000722s 0.000021s 1384.9 47797.3
sign verify sign/s verify/s
384 bit ecdsa (nistp384) **0.0013s** 0.0008s **744.7** 1191.7

**Comment by romen** [comment]
Thanks for reporting this @eraymond00.

This performance degradation is expected and was documented in this issue:

https://github.com/openssl/openssl/issues/7622

In summary we traded performance for a more secure implementation. 
Bad news is that in the 1.0.2 branch, the complexity of redesigning the internals did not allow to apply changes that could somehow mitigate the performance loss.
The good news is that if you upgrade to 1.1.1 things don't look that bad! 

Does this answer address your concerns?

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
