### ISSUE TITLE
VC_WIN32 Build fail on Win XP x86, VC2010, OpenSSL v1.1.0-pre5-dev

### ISSUE THREAD

**Issue by bernarddt** [openssl/openssl#893]
I'm building OpenSSL v1.1.0-pre5-dev on Windows XP x86.

perl Configure VC-WIN32
nmake (inside VS Cmd 2010)

The compile failed on **crypto\ui\ui_openssl.c** (line 204): error C2014: preprocessor command must start as first nonwhite space.

I have noticed there is an extra line wrap symbol "\" after the end of the elif on line 203.

Regards,
Bernard

**Comment by richsalz** [comment]
fixed a few hours ago.  refresh from master.

**Comment by bernarddt** [comment]
Thanks!
