### ISSUE TITLE
Cannot create context with SSL_CTX_new() on VxWorks

### ISSUE THREAD

**Issue by jk-gh** [openssl/openssl#8931]
We are using OpenSSL 1.1.1b on VxWorks 5.4.2. When `SSL_CTX_new(SSLv23_method())` is called, it always returns NULL. When using OpenSSL 1.0.2n on the same system, the `SSL_CTX_new()` allocates the object, so I believe it is not an error in use.

We are using own OpenSSL build, the configuration parameters are `vxworks-ppc405 --api=0.9.8 no-asm no-threads no-async no-pic no-dso no-engine no-pinshared no-ui-console no-tests no-rfc3779 no-aria no-bf no-blake2 no-camellia no-cast no-ct no-gost no-idea no-md4 no-mdc2 no-rc2 no-rc4 no-rmd160 no-seed no-siphash no-sm2 no-sm3 no-sm4 no-whirlpool`

I tried narrowing down the cause and it seems, that it is caused by failing `atexit(OPENSSL_cleanup)` (https://github.com/openssl/openssl/blob/master/crypto/init.c#L140).
Full call chain is `SSL_CTX_new()`->`OPENSSL_init_ssl()`->`OPENSSL_init_crypto()`->`RUN_ONCE(&register_atexit, ossl_init_register_atexit)`.

Since the opts are set internally in `SSL_CTX_new()`, adding `OPENSSL_INIT_NO_ATEXIT` to opts and calling `OPENSSL_cleanup()` manually is does not seem to be an option.

**Comment by chensqecc** [comment]
in vxworks system ,atexit behavior is different with linux. so it will always failed in Vxworks.

**Comment by bernd-edlinger** [comment]
try OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL).

**Comment by jk-gh** [comment]
Thank you for response.
I am not calling the `OPENSSL_init_crypto()` directly, it is called internally in `SSL_CTX_new()`. In the code I don't see any check, that would prevent setting the atexit, if the library was already initialized. But I will try calling `OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL)` before attempting to create context anyway, just in case I overlooked something.

**Comment by jk-gh** [comment]
Update: I tried calling `OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL)` before attempting to create a context, but it had no effect.

**Comment by mattcaswell** [comment]
> Update: I tried calling OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL) before attempting to create a context, but it had no effect.

Make sure this is called before *any* OpenSSL function has been called.

**Comment by jk-gh** [comment]
I added the call of `OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL)` as first thing to `main`, but still no change. I added some printf to the `OPENSSL_init_crypto`, so I am quite sure no-one called it before my call from `main`. Later it is called many times from various places with various arguments.

We use several libraries, that use OpenSSL internally, maybe some of them calls some OpenSSL function during its static initialization. I guess the issue would be in that library then.

I can try to find out, if some other OpenSSL function is called before the `main`.

**Comment by juergenc** [comment]
Same issue here. If I put the `OPENSSL_no_config();` in comment, it works:

```C++
        //OPENSSL_no_config();
        SSL_load_error_strings();
        SSL_library_init();
        OpenSSL_add_all_algorithms();
       [...]
        SslCtxPtr ctx(SSL_CTX_new(SSLv23_method()));
```
Installed SSL lib versions on a Oracle 8 Linux (binary compatible with RHEL8):
```
openssl-libs-1.1.1-8.0.1.el8.x86_64
openssl-devel-1.1.1-8.0.1.el8.x86_64
```

The method `SSLv23_method()` is depricated and should be replaced by `TLS_method()` right? Is it 100% compatible?

**Comment by jk-gh** [comment]
I haven't succeeded in finding out, if some library calls some OpenSSL function before `main()` and I no longer have access to VxWorks system.
I believe your recommendation would work if I were able to bring it to life, but have no way to verify it.
How should we proceed with this issue?

**Comment by juergenc** [comment]
You might verify it with on RHEL-8 OS or the license free derivates CentOS-8 or Oracle-8 (like in my case).

**Comment by mattcaswell** [comment]
> I believe your recommendation would work if I were able to bring it to life, but have no way to verify it.
How should we proceed with this issue?

If you think that in all probability my suggested work around would work then I suggest that this issue should just be closed, since it seems we will not be able to make any further progress. Do you agree?

**Comment by jk-gh** [comment]
I agree.
Closing the ticket, thank you for support.
