### ISSUE TITLE
configuredata.pm

### ISSUE THREAD

**Issue by YanAnzouyijun** [openssl/openssl#8932]
hello,could you tell me  the theory of how did the "make" detect the changes of configdata.pm while make the openssl? maybe,is the time of the file ? i am confused with that.
in the Makefile:
```
configdata.pm: $(SRCDIR)/Configure $(SRCDIR)/config Configurations/common0.tmpl Configurations/unix-Makefile.tmpl Configurations/common.tmpl ./build.info crypto/build.info ssl/build.info apps/build.info test/build.info util/build.info tools/build.info fuzz/build.info engines/build.info crypto/objects/build.info crypto/buffer/build.info crypto/bio/build.info crypto/stack/build.info crypto/lhash/build.info crypto/rand/build.info crypto/evp/build.info crypto/asn1/build.info crypto/pem/build.info crypto/x509/build.info crypto/x509v3/build.info crypto/conf/build.info crypto/txt_db/build.info crypto/pkcs7/build.info crypto/pkcs12/build.info crypto/ui/build.info crypto/kdf/build.info crypto/store/build.info crypto/md4/build.info crypto/md5/build.info crypto/sha/build.info crypto/mdc2/build.info crypto/gmac/build.info crypto/hmac/build.info crypto/ripemd/build.info crypto/whrlpool/build.info crypto/poly1305/build.info crypto/blake2/build.info crypto/siphash/build.info crypto/sm3/build.info crypto/des/build.info crypto/aes/build.info crypto/rc2/build.info crypto/rc4/build.info crypto/idea/build.info crypto/aria/build.info crypto/bf/build.info crypto/cast/build.info crypto/camellia/build.info crypto/seed/build.info crypto/sm4/build.info crypto/chacha/build.info crypto/modes/build.info crypto/bn/build.info crypto/ec/build.info crypto/rsa/build.info crypto/dsa/build.info crypto/dh/build.info crypto/sm2/build.info crypto/dso/build.info crypto/engine/build.info crypto/err/build.info crypto/comp/build.info crypto/ocsp/build.info crypto/cms/build.info crypto/ts/build.info crypto/srp/build.info crypto/cmac/build.info crypto/ct/build.info crypto/async/build.info crypto/kmac/build.info test/ossl_shim/build.info Configurations/00-base-templates.conf Configurations/10-main.conf Configurations/shared-info.pl
```
for example, if i modify the ssl/build.info, bio_ssl.c had been deleted in the ssl/build.info. like this:
```
 LIBS=../libssl
SOURCE[../libssl]=\
        pqueue.c packet.c \
        statem/statem_srvr.c statem/statem_clnt.c  s3_lib.c  s3_enc.c record/rec_layer_s3.c \
        statem/statem_lib.c statem/extensions.c statem/extensions_srvr.c \
        statem/extensions_clnt.c statem/extensions_cust.c s3_cbc.c s3_msg.c \
        methods.c   t1_lib.c  t1_enc.c tls13_enc.c \
        d1_lib.c  record/rec_layer_d1.c d1_msg.c \
        statem/statem_dtls.c d1_srtp.c \
        ssl_lib.c ssl_cert.c ssl_sess.c \
        ssl_ciph.c ssl_stat.c ssl_rsa.c \
        ssl_asn1.c ssl_txt.c ssl_init.c ssl_conf.c  ssl_mcnf.c \
        ssl_err.c tls_srp.c t1_trce.c ssl_utst.c \
        record/ssl3_buffer.c record/ssl3_record.c record/dtls1_bitmap.c \
        statem/statem.c record/ssl3_record_tls13.c
```
then while i execute "make ", the result is that :
```
Detected changed: ssl/build.info
/usr/bin/perl configdata.pm -r
***** Deprecated options: no-ssl2
Configuring OpenSSL version 3.0.0-dev for target linux-x86
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
**************************************************
***                                            ***
***   Please run the same make command again   ***
***                                            ***
**************************************************
Makefile:791: recipe for target 'configdata.pm' failed
make: *** [configdata.pm] Error 1
```
so the configdata.pm  is depended on the  time of the file ( $(SRCDIR)/Configure $(SRCDIR)/config Configurations/common0.tmpl Configurations/unix-Makefile.tmpl Configurations/common.tmpl ./build.info crypto/build.info ssl/build.info apps/build.info test/build.info util/build.info tools/build.info fuzz/build.info engines/build.info crypto/objects/build.info crypto/buffer/build.info crypto/bio/build.info crypto/stack/build.info crypto/lhash/build.info crypto/rand/build.info crypto/evp/build.info crypto/asn1/build.info crypto/pem/build.info crypto/x509/build.info crypto/x509v3/build.info crypto/conf/build.info crypto/txt_db/build.info crypto/pkcs7/build.info crypto/pkcs12/build.info crypto/ui/build.info crypto/kdf/build.info crypto/store/build.info crypto/md4/build.info crypto/md5/build.info crypto/sha/build.info crypto/mdc2/build.info crypto/gmac/build.info crypto/hmac/build.info crypto/ripemd/build.info crypto/whrlpool/build.info crypto/poly1305/build.info crypto/blake2/build.info crypto/siphash/build.info crypto/sm3/build.info crypto/des/build.info crypto/aes/build.info crypto/rc2/build.info crypto/rc4/build.info crypto/idea/build.info crypto/aria/build.info crypto/bf/build.info crypto/cast/build.info crypto/camellia/build.info crypto/seed/build.info crypto/sm4/build.info crypto/chacha/build.info crypto/modes/build.info crypto/bn/build.info crypto/ec/build.info crypto/rsa/build.info crypto/dsa/build.info crypto/dh/build.info crypto/sm2/build.info crypto/dso/build.info crypto/engine/build.info crypto/err/build.info crypto/comp/build.info crypto/ocsp/build.info crypto/cms/build.info crypto/ts/build.info crypto/srp/build.info crypto/cmac/build.info crypto/ct/build.info crypto/async/build.info crypto/kmac/build.info test/ossl_shim/build.info Configurations/00-base-templates.conf Configurations/10-main.conf Configurations/shared-info.pl)?

**Comment by levitte** [comment]
Yup. That's exactly what the Makefile line you quoted means.

You may want to read up on how `make` works...

**Comment by slontis** [comment]
you need to rerun config
e.g- ./config -Werror --strict-warnings -debug
This will regenerate the Makefile which 'make' uses.
You need to do this if you change any build.info.

Can you close this please if it answers your question.

**Comment by anointedboss1717** [comment]
> hello,could you tell me  the theory of how did the "make" detect the changes of configdata.pm while make the openssl? maybe,is the time of the file ? i am confused with that.
> in the Makefile:
> ```
> configdata.pm: $(SRCDIR)/Configure $(SRCDIR)/config Configurations/common0.tmpl Configurations/unix-Makefile.tmpl Configurations/common.tmpl ./build.info crypto/build.info ssl/build.info apps/build.info test/build.info util/build.info tools/build.info fuzz/build.info engines/build.info crypto/objects/build.info crypto/buffer/build.info crypto/bio/build.info crypto/stack/build.info crypto/lhash/build.info crypto/rand/build.info crypto/evp/build.info crypto/asn1/build.info crypto/pem/build.info crypto/x509/build.info crypto/x509v3/build.info crypto/conf/build.info crypto/txt_db/build.info crypto/pkcs7/build.info crypto/pkcs12/build.info crypto/ui/build.info crypto/kdf/build.info crypto/store/build.info crypto/md4/build.info crypto/md5/build.info crypto/sha/build.info crypto/mdc2/build.info crypto/gmac/build.info crypto/hmac/build.info crypto/ripemd/build.info crypto/whrlpool/build.info crypto/poly1305/build.info crypto/blake2/build.info crypto/siphash/build.info crypto/sm3/build.info crypto/des/build.info crypto/aes/build.info crypto/rc2/build.info crypto/rc4/build.info crypto/idea/build.info crypto/aria/build.info crypto/bf/build.info crypto/cast/build.info crypto/camellia/build.info crypto/seed/build.info crypto/sm4/build.info crypto/chacha/build.info crypto/modes/build.info crypto/bn/build.info crypto/ec/build.info crypto/rsa/build.info crypto/dsa/build.info crypto/dh/build.info crypto/sm2/build.info crypto/dso/build.info crypto/engine/build.info crypto/err/build.info crypto/comp/build.info crypto/ocsp/build.info crypto/cms/build.info crypto/ts/build.info crypto/srp/build.info crypto/cmac/build.info crypto/ct/build.info crypto/async/build.info crypto/kmac/build.info test/ossl_shim/build.info Configurations/00-base-templates.conf Configurations/10-main.conf Configurations/shared-info.pl
> ```
> for example, if i modify the ssl/build.info, bio_ssl.c had been deleted in the ssl/build.info. like this:
> ```
>  LIBS=../libssl
> SOURCE[../libssl]=\
>         pqueue.c packet.c \
>         statem/statem_srvr.c statem/statem_clnt.c  s3_lib.c  s3_enc.c record/rec_layer_s3.c \
>         statem/statem_lib.c statem/extensions.c statem/extensions_srvr.c \
>         statem/extensions_clnt.c statem/extensions_cust.c s3_cbc.c s3_msg.c \
>         methods.c   t1_lib.c  t1_enc.c tls13_enc.c \
>         d1_lib.c  record/rec_layer_d1.c d1_msg.c \
>         statem/statem_dtls.c d1_srtp.c \
>         ssl_lib.c ssl_cert.c ssl_sess.c \
>         ssl_ciph.c ssl_stat.c ssl_rsa.c \
>         ssl_asn1.c ssl_txt.c ssl_init.c ssl_conf.c  ssl_mcnf.c \
>         ssl_err.c tls_srp.c t1_trce.c ssl_utst.c \
>         record/ssl3_buffer.c record/ssl3_record.c record/dtls1_bitmap.c \
>         statem/statem.c record/ssl3_record_tls13.c
> ```
> then while i execute "make ", the result is that :
> ```
> Detected changed: ssl/build.info
> /usr/bin/perl configdata.pm -r
> ***** Deprecated options: no-ssl2
> Configuring OpenSSL version 3.0.0-dev for target linux-x86
> Using os-specific seed configuration
> Creating configdata.pm
> Creating Makefile
> 
> **********************************************************************
> ***                                                                ***
> ***   OpenSSL has been successfully configured                     ***
> ***                                                                ***
> ***   If you encounter a problem while building, please open an    ***
> ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
> ***   and include the output from the following command:           ***
> ***                                                                ***
> ***       perl configdata.pm --dump                                ***
> ***                                                                ***
> ***   (If you are new to OpenSSL, you might want to consult the    ***
> ***   'Troubleshooting' section in the INSTALL file first)         ***
> ***                                                                ***
> **********************************************************************
> **************************************************
> ***                                            ***
> ***   Please run the same make command again   ***
> ***                                            ***
> **************************************************
> Makefile:791: recipe for target 'configdata.pm' failed
> make: *** [configdata.pm] Error 1
> ```
> so the configdata.pm  is depended on the  time of the file ( $(SRCDIR)/Configure $(SRCDIR)/config Configurations/common0.tmpl Configurations/unix-Makefile.tmpl Configurations/common.tmpl ./build.info crypto/build.info ssl/build.info apps/build.info test/build.info util/build.info tools/build.info fuzz/build.info engines/build.info crypto/objects/build.info crypto/buffer/build.info crypto/bio/build.info crypto/stack/build.info crypto/lhash/build.info crypto/rand/build.info crypto/evp/build.info crypto/asn1/build.info crypto/pem/build.info crypto/x509/build.info crypto/x509v3/build.info crypto/conf/build.info crypto/txt_db/build.info crypto/pkcs7/build.info crypto/pkcs12/build.info crypto/ui/build.info crypto/kdf/build.info crypto/store/build.info crypto/md4/build.info crypto/md5/build.info crypto/sha/build.info crypto/mdc2/build.info crypto/gmac/build.info crypto/hmac/build.info crypto/ripemd/build.info crypto/whrlpool/build.info crypto/poly1305/build.info crypto/blake2/build.info crypto/siphash/build.info crypto/sm3/build.info crypto/des/build.info crypto/aes/build.info crypto/rc2/build.info crypto/rc4/build.info crypto/idea/build.info crypto/aria/build.info crypto/bf/build.info crypto/cast/build.info crypto/camellia/build.info crypto/seed/build.info crypto/sm4/build.info crypto/chacha/build.info crypto/modes/build.info crypto/bn/build.info crypto/ec/build.info crypto/rsa/build.info crypto/dsa/build.info crypto/dh/build.info crypto/sm2/build.info crypto/dso/build.info crypto/engine/build.info crypto/err/build.info crypto/comp/build.info crypto/ocsp/build.info crypto/cms/build.info crypto/ts/build.info crypto/srp/build.info crypto/cmac/build.info crypto/ct/build.info crypto/async/build.info crypto/kmac/build.info test/ossl_shim/build.info Configurations/00-base-templates.conf Configurations/10-main.conf Configurations/shared-info.pl)?

**Comment by anointedboss1717** [comment]
Support
