### ISSUE TITLE
mark SSL_session_reused const

### ISSUE THREAD

**Issue by schwabe** [openssl/openssl#8934]
From the man page of `SSL_session_reused` and from the code of similar functions it seems that `SSL_session_reused (SSL *ssl)` should be `int SSL_session_reused(const SSL *s)`.

Is there a reason that the API marks this as non const?

**Comment by levitte** [comment]
Good question. Intuitively, it should be const, but needs to be confirmed with code scrutiny.
Historically, we have been sloppy re constification of parameters, so there are a number of functions that would need to change, but we do need to verify that the parameter data is indeed not modified. Anyone is welcome to do so.

**Comment by kroeckx** [comment]
The current function is this:
int SSL_session_reused(SSL *s)
{
    return s->hit;
}

The only reason I could think of that it might not be possible to
make this const is that it might need to take a lock, which it
doesn't.

**Comment by levitte** [comment]
OK. PR welcome!
