### ISSUE TITLE
does here any system function list that openssl1.1.1.a used?

### ISSUE THREAD

**Issue by chensqecc** [openssl/openssl#8937]
hi 
i want to get all the system functions that openssl1.1.1.a used.  I have do some self-search and check, and don't get any useful help now.

please help  confirm whether we have any system function list that openssl1.1.1.a (or other openssl version) used? or does here any method can get all the system function from code?

**Comment by paulidale** [comment]
On a Unix like operating system `nm -u libcrypto.so` and `nm -u libssl.so` will be a beginning.  You'll need to get the paths to the libraries correct and possibly their version extensions.

**Comment by chensqecc** [comment]
ok thank you 
@paulidale
