### ISSUE TITLE
OpenSSL 1.0.2r Win32/64 static debug build doesn't contain PDB

### ISSUE THREAD

**Issue by ScooloV** [openssl/openssl#8939]
Tried to build latest stable OpenSSL 1.0.2 lib for Windows project using next steps:
1) Installed perl/nasm
2) Launched "Developer Command Prompt for VS 2017"
3) Entered this commands:
```
cd c:\lib\openssl-1.0.2r
perl Configure debug-VC-WIN32 --prefix=c:\lib\openssl-32-dbg
ms\do_nasm
nmake -f ms\nt.mak
nmake -f ms\nt.mak test
nmake -f ms\nt.mak install
```
4) Build process was successfull and then I changed my older OpenSSL files (libeay32.lib and ssleay32.lib) with this one (previous version was 1.0.2m) after I got a lot of warnings from Visual Studio (they all look similar) like this:
```
1>libeay32.lib(cryptlib.obj) : warning LNK4099: PDB 'lib.pdb' was not found with 'libeay32.lib(cryptlib.obj)' or at 'C:\PROJECTDIR\lib.pdb'; linking object as if no debug info
```
5) Also noticed that size of 1.0.2r static-debug version is smaller than previous version, that probably means, that PDB files, which VS2017 requires for debug, are not there.

Is it bug, or build process was changed?

**Comment by petesky** [comment]
I build with cygwin (my compile_flags = "-no-asm -shared") and found the pdb in eg. openssl-1.0.2r_vs90_32\out32dll\

**Comment by levitte** [comment]
We added support for PDB files, including getting them properly installed, in 1.1.0.  1.0.2 has an older build system where that support simply isn't there, nor is very easy to add.  Considering that 1.0.2 is reaching EOL in less than 2 months, it's not worth the effort.  Please consider upgrading to 1.1.1.
