### ISSUE TITLE
openssl 1.1.0 beta 1 make rehash not working

### ISSUE THREAD

**Issue by sbagmeijer** [openssl/openssl#894]
hi I try to update my rpms to the latest version but it gives a error on "make rehash" is this removed in the new version, it worked fine in "pre2" (latest i tested).

error I get:
[root@rhel7 openssl-OpenSSL_1_1_0-pre4]# make rehash
make: *** No rule to make target `rehash'.  Stop.

I do the following in my spec file:
./config --openssldir=/usr/local/ulyaoth/ssl/openssl1.1.0 shared
make depend
make all
make rehash
make %{?_smp_mflags}

spec file: https://github.com/ulyaoth/repository/blob/master/ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec

**Comment by levitte** [comment]
Yes, it's gone.  Not needed any more, at least for building and testing.

**Comment by sbagmeijer** [comment]
Thank you for the quick response!
