### ISSUE TITLE
Memory leak in OCSP_url_svcloc_new

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#8949]
Update: the original issue described was not a leak but rather confusion about whether an `ACCESS_DESCRIPTION *` contains an empty `GENERAL_NAME *` already. However, OpenSSL itself leaks a `GENERAL_NAME *`, as you can see in the second comment

**Comment by reaperhulk** [comment]
Okay, `ACCESS_DESCRIPTION_new` allocates a `GENERAL_NAME *` for `location` so the bug in the test cases was that it replaced that GN, thus leaking it.

However, this means the following code is incorrect as it will leak:

https://github.com/openssl/openssl/blob/0c496700631d89a895617af005a338eb280095db/crypto/ocsp/ocsp_ext.c#L452

**Comment by FdaSilvaYY** [comment]
you may have miss one things: OpenSSL structures are now (since 1.1, if i not wrong) opaque,  !
So  you should not be assigning fields directly.
There are methods to get/set most of the fields in the many internals structures.

**Comment by alex** [comment]
https://github.com/openssl/openssl/blob/master/include/openssl/x509v3.h#L155-L158

**Comment by FdaSilvaYY** [comment]
AFA I see, there is no accessor to this structure internal fields .
Most of its usage rely on ASN1 mechanism.

**Comment by reaperhulk** [comment]
The `ACCESS_DESCRIPTION` structure itself is not opaque and there is a memory leak due to incorrect assignment here: https://github.com/openssl/openssl/blob/0c496700631d89a895617af005a338eb280095db/crypto/ocsp/ocsp_ext.c#L452

This is arguably related to https://github.com/openssl/openssl/issues/5158 in that OpenSSL's constructor functions give no information about what fields may be initialized with an empty value and which ones are left NULL (and the confusing memory ownership semantics following from those inconsistencies) but rather than trying to redesign the entirety of the allocation system we can just correct this memory leak and move on for now.

**Comment by FdaSilvaYY** [comment]
@alex: x509v3 extensions declarations are still public, that's bad.
@ reaperhulk : i think this code is right.
ASN1_new functions don't allocate/create the GeneralName (stack) by itself, much more if this field is optional.
In this case, a NULL field value marks it absence.
See 
https://github.com/openssl/openssl/blob/0c496700631d89a895617af005a338eb280095db/crypto/ocsp/ocsp_asn.c#L130-134

**Comment by FdaSilvaYY** [comment]
@reaperhulk : asn1 code seem to allocate simple fields as GENERAL_NAMe ( who are strings) .
So this method has a leak.

**Comment by FdaSilvaYY** [comment]
I'm preparing a PR to quickly fix this very old leak .
