### ISSUE TITLE
Wrong constraint in assembler code

### ISSUE THREAD

**Issue by ssbssa** [openssl/openssl#895]
When trying to link with LTO I had this error:
```
{standard input}: Assembler messages:
{standard input}:4742: Error: operand type mismatch for `div'
lto-wrapper.exe: fatal error: C:\msys64\mingw64\bin\g++.exe returned 1 exit status
```
I traced it back to this compiled assembler code:
```
/APP
 # 196 "asm/x86_64-gcc.c" 1
        divq      $-8446744073709551616
 # 0 "" 2
/NO_APP
```
Which is coming from crypto/bn/asm/x86_64-gcc.c:
```
BN_ULONG bn_div_words(BN_ULONG h, BN_ULONG l, BN_ULONG d)
{
    BN_ULONG ret, waste;

 asm("divq      %4":"=a"(ret), "=d"(waste)
 :     "a"(l), "d"(h), "g"(d)
 :     "cc");

    return ret;
}
```
[Apparently](https://gcc.gnu.org/ml/gcc-help/2016-03/msg00100.html), this code should use constraint "rm" instead of "g":
```
 asm("divq      %4":"=a"(ret), "=d"(waste)
 :     "a"(l), "d"(h), "rm"(d)
 :     "cc");
```

**Comment by mattcaswell** [comment]
Which version of OpenSSL does this issue refer to?

**Comment by ssbssa** [comment]
1.0.1* and 1.0.2*

**Comment by mattcaswell** [comment]
Ping @dot-asm

**Comment by dot-asm** [comment]
Here is dilemma. We don't recommend LTO (no security project should), but in such case are we supposed to fix problems with it? And if we choose to anyway, this is not the only place where "g" is used [with divq], do we fix others? In either case if we choose to do something, I'd be reluctant to use "rm", because I'm not sure if it works with older compilers. But "r" alone would be adequate...

**Comment by richsalz** [comment]
I think we fix this in the documentation.  *If you use LTO [specific flags here] then use no-asm"

**Comment by BenBE** [comment]
Actually I'd prefer to fix it in both places:
- Make things compile properly (quick search showed only 2 places in 1.0.2, didn't check 1.1.x)
- Update the documentation to include strong wording why you shouldn't use LTO (including references where to find details).

**Comment by dot-asm** [comment]
This was fixed a while ago. So this is going to be closed.

As for why one shouldn't use LTO, or more accurately overly aggressive inter-procedural analysis. Problem is that it's one of those cases when you have to use judgement. Thing is that security counter-measures tend to be implemented by making code slower, and it's optimizer's very business to consider it unnecessary slow. And IPA is the means for optimizer to succeed. Now real trouble is that actually showing it is prohibitively expensive exercise, and it can't be performed just once, as one has to do every compiler and version :-(

**Comment by hghwng** [comment]
@dot-asm What about marking security-critical functions as non-optimizable in their attributes? An optimizing compiler is free to do anything, as long as it obeys the language standard.
