### ISSUE TITLE
"so" is forced for engines instead of "dylib" on osx

### ISSUE THREAD

**Issue by chipitsine** [openssl/openssl#8950]
Hello,

I'm using current openssl master branch.
when I build https://github.com/gost-engine/engine on osx
there's an error

https://travis-ci.com/chipitsine/engine/builds/112328221#L535-L557

as you can see, there's gost.dylib, but it tries to load gost.so

this bug looks like https://github.com/openssl/openssl/issues/727

@beldmit can tell about gost engine if needed.

**Comment by levitte** [comment]
`build.log` from the openssl directory would be useful to look at...

**Comment by levitte** [comment]
Or oh, no, it won't. 'cause that travis script *rewrites it* at every step!  I'm interesting in the output from openssl's `./config`

**Comment by levitte** [comment]
... but never mind, I think I found the bug.  It looks like it's master only.

**Comment by levitte** [comment]
#8951 should fix this issue

**Comment by chipitsine** [comment]
yes, it [does](https://travis-ci.com/chipitsine/engine/builds/112343504)

**Comment by levitte** [comment]
Maybe gost.dylib isn't quite right:

https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-osx/2339910#2339910

However, earlier OpenSSL versions do support that, so...
