### ISSUE TITLE
IDEA_CFB difference between OpenSSL and libgcrypt

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#8954]
https://oss-fuzz.com/testcase-detail/5653590468722688

OSS-Fuzz does not see this as a distinct bug because Cryptofuzz always abort()s at the same place if a difference is detected, hence nobody got an e-mail.

ping @jkivilin

```

Difference detected
--
  |  
  | Operation:
  | operation name: SymmetricDecrypt
  | ciphertext: {0xf1, 0x94, 0x47, 0x44, 0xa4, 0x7c, 0x05, 0x38, 0x00, 0x0e, 0x3d, 0x61, 0x32, 0x10, 0x11, 0x88} (16 bytes)
  | tag: nullopt
  | aad: nullopt
  | cipher iv: {0x00, 0x00, 0x00, 0x6a, 0xae, 0x01, 0x2b, 0x01} (8 bytes)
  | cipher key: {0x00, 0xb2, 0xae, 0xb0, 0x00, 0x00, 0x8f, 0x9c, 0x0f, 0xf9, 0xb5, 0x72, 0xe7, 0xe9, 0x00, 0x3f} (16 bytes)
  | cipher: IDEA_CFB
  | cleartextSize: 6157541
  |  
  | Module OpenSSL result:
  |  
  | {0x87, 0xca, 0x49, 0xe6, 0xed, 0x82, 0x79, 0xc3, 0x2c, 0x60, 0x26, 0x26, 0xe3, 0x30, 0x6e, 0xe6} (16 bytes)
  |  
  | Module libgcrypt result:
  |  
  | {0x87, 0xca, 0x49, 0xe6, 0xed, 0x82, 0x79, 0xc3, 0x51, 0xa1, 0x6d, 0xb3, 0xbd, 0x5f, 0x82, 0xeb} (16 bytes)

```

**Comment by mattcaswell** [comment]
Since this is a decrypt operation do you have the original corresponding plaintext? Do the implementations differ in the encrypt operation?

**Comment by levitte** [comment]
Side note: links that require Google login aren't very helpful.

> https://oss-fuzz.com/testcase-detail/5653590468722688

**Comment by guidovranken** [comment]
Sorry for the false positive, it was a bug in my code. It's hard to get all stuff exactly right! :)
