### ISSUE TITLE
GENERAL_NAME type is not opaque

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8974]
I had thought that all types had become opaque in OpenSSL 1.1.1 but there appear to be some remaining. GENERAL_NAME is one type that is not opaque.

**Comment by levitte** [comment]
Yeah, we didn't get to all of them.
(it was in 1.1.0, BTW)

**Comment by mattcaswell** [comment]
None of the ASN.1 structures were made opaque (that was thought to be too much of a can of worms).

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
