### ISSUE TITLE
Regression on openssl 1.1.1

### ISSUE THREAD

**Issue by nacho** [openssl/openssl#8977]
I've been looking for a regression that happened in glib-networking's openssl backend. To be more specific it happens on this test: https://gitlab.gnome.org/GNOME/glib-networking/blob/master/tls/tests/connection.c#L1711

This test creates a server and gets the client connected to it. Then the client using 2 different threads one for reading and another for writing will write and read on those threads. glib-networking uses a custom bio using the glib underlying objects in order to write to the sockets. For what I can see is that in one of the calls to SSL_write, the write will successfully say that it wrote 12 bytes but these 12 bytes will never reach to the underlying bio, then the server will block forever.

I was bisecting the openssl source code and unfortunately I reached to the following commit:
```
f518cef40c431188b4910ca9bd8ef3778f599bb5 is the first bad commit
commit f518cef40c431188b4910ca9bd8ef3778f599bb5
Author: Matt Caswell <matt@openssl.org>
Date:   Tue Feb 6 17:27:25 2018 +0000

    Enable TLSv1.3 by default
    
    [extended tests]
    
    Reviewed-by: Richard Levitte <levitte@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/5266)

```

Now, this is a very big change introducing tls v1.3 so it is hard for me to follow what can be going wrong here :( I guess I will need some help from your side to actually find the place where this is regressing.

Thanks

**Comment by mattcaswell** [comment]
>  Then the client using 2 different threads one for reading and another for writing will write and read on those threads. 

Are you using some kind of synchronisation with these 2 threads? It is not supported to perform operations on the same SSL object simultaneously from 2 different threads.

**Comment by nacho** [comment]
@mattcaswell I wonder how this ever worked. I guess that explains why this does not work.
Thanks for the info! I guess for openssl I will just skip that test.

**Comment by nacho** [comment]
@mattcaswell I am reopening this to get your opinion on this other issue we are seeing. The following test https://gitlab.gnome.org/GNOME/glib-networking/blob/master/tls/tests/connection.c#L1936 closes the output stream of the client which means on the client side SSL_shutdown is called. Now, from reading the documentation and from testing this with openssl 1.1.0 I am supposed to still make reads with SSL_read on the client side. Instead what I see is that with 1.1.1 I get a SYSCALL error after SSL_shutdown was called on the ssl object.

Do you know if this use case is still supported?

**Comment by mattcaswell** [comment]
You should be able to still read even if you are closed for writes - so yes that scenario should be ok.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
