### ISSUE TITLE
Documentation needed for EC key loading

### ISSUE THREAD

**Issue by msharov** [openssl/openssl#8983]
I was unable to find any documentation or examples anywhere on how to load an EC key. I have an EC public key as a point in uncompressed form, 0x04|x|y (in an openpgp public key packet). Lacking information on how to put this data into an EC_KEY, I've come up with the following, using likely-looking functions from ec.h and trying to read openssl sources for them:
```c
EC_KEY* peck = EC_KEY_new_by_curve_name (NID_X9_62_prime256v1);
size_t ptcsz = (keysz-1)/2;
BIGNUM* x = BN_bin2bn (keyptr+1, ptcsz, NULL);
BIGNUM* y = BN_bin2bn (keyptr+ptcsz+1, ptcsz, NULL);
EC_GROUP* ecgrp = EC_KEY_get0_group (peck);
EC_POINT* ecpt = EC_POINT_new (ecgrp);
EC_POINT_set_affine_coordinates (ecgrp, ecpt, x, y, NULL);
EC_KEY_set_public_key (peck, ecpt);
EVP_PKEY_set1_EC_KEY (pkey, peck);
```
The code appears to work, but signature verification (using EVP_PKEY_verify) fails. Without documentation I have no way of knowing if the above code loaded the key correctly or if I merely succeeded in craftily bypassing enough sanity checks to cram the data in. Not being an expert on implementing ECC, I find the source code for the EC module rather difficult to understand, so I would appreciate having some simpler instructions on what needs to be done. On the man page of EC_KEY_new, perhaps?

**Comment by msharov** [comment]
Never mind. I don't know what else I was expecting. You already have EC_KEY_check_key. That succeeds, so I guess signature verification is what's broken, but that's a different issue.

**Comment by mattcaswell** [comment]
You might also like to look at the function EC_POINT_oct2point() documented here:

https://www.openssl.org/docs/man1.1.1/man3/EC_POINT_oct2point.html

That function coverts a raw "binary" format point (i.e. one in "octet" format) into an EC_POINT. This handles all the compressed vs uncompressed handling for you. So your code might look something like this (untested):

````
EC_KEY* peck = EC_KEY_new_by_curve_name (NID_X9_62_prime256v1);
EC_GROUP* ecgrp = EC_KEY_get0_group (peck);
EC_POINT* ecpt = EC_POINT_new (ecgrp);
EC_POINT_oct2point (ecgrp, ecpt, keyptr, keysz, NULL);
EC_KEY_set_public_key (peck, ecpt);
EVP_PKEY_set1_EC_KEY (pkey, peck);
````
