### ISSUE TITLE
How does Openssl set both tls1.3 and tls1.3 versions of the algorithm set?

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#8988]
I use the SSL_set_cipher_list API to set the algorithm set of tls1.3, but it is not found in wireshark capture.

    ctx = SSL_CTX_new(TLS_server_method());
    SSL_set_ciphersuites(ssl, TLS1_3_RFC_AES_128_GCM_SHA256":"\
                                  TLS1_3_RFC_AES_256_GCM_SHA384":"\
                                  TLS1_3_RFC_AES_128_CCM_SHA256":"\
                                  TLS1_3_RFC_AES_128_CCM_8_SHA256":"\
                                  TLS1_3_RFC_CHACHA20_POLY1305_SHA256)

**Comment by richsalz** [comment]
TLS 1.3 deliberately looks like TLS 1.2 (although there are some differences in the extensions and cipher suites, and a TLS 1.3-capable wireshark will detect that). The IETF did this to work around broken middleboxes.

**Comment by mattcaswell** [comment]
You said `SSL_set_cipher_list` in your text, but in the code you say `SSL_set_ciphersuites`. Which is it?

**Comment by Mengliuxx** [comment]
> 你`SSL_set_cipher_list`在文中说过，但是在你说的代码中`SSL_set_ciphersuites`。这是什么？

That's what I wrote wrong. I thought SSL_set_cipher_list was set to tls1.2, SSL_set_ciphersuites was set to tls1.3, but after testing, it didn't seem to be

**Comment by mattcaswell** [comment]
> That's what I wrote wrong. I thought SSL_set_cipher_list was set to tls1.2, SSL_set_ciphersuites was set to tls1.3, but after testing, it didn't seem to be

This is the case. SSL_set_cipher_list() sets TLSv1.2 and below ciphersuites. SSL_set_ciphersuite() sets TLSv1.3 ciphersuites.

**Comment by Mengliuxx** [comment]
> > 这就是我写错了。我以为SSL_set_cipher_list设置为tls1.2，SSL_set_ciphersuites设置为tls1.3，但经过测试，它似乎不是
> 
> 情况就是这样。SSL_set_cipher_list（）设置TLSv1.2及以下密码套件。SSL_set_ciphersuite（）设置TLSv1.3密码套件。

Ok, thank you, I will continue to try
