### ISSUE TITLE
doc: manual page should explicitly declare all single protocol TLS methods deprecated

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#8989]
The [SSL_CTX_new(3)](https://github.com/openssl/openssl/blob/5d238a1032fee0e4759c2ed7fbd09cb9d7125a72/doc/man3/SSL_CTX_new.pod) manual page states that the generic methods `TLS_*method()` should preferably be used instead of the single protocol methods, like e.g. `TLSv1_2_*method()`. However, it does not deprecate all single protocol methods entirely, only the `SSLv23_*method()`s are deprecated.

```
NOTES
       The SSL_CTX object uses method as connection method.  The methods exist in a generic type (for client and server use), a server only type, and
       a client only type.  method can be of the following types:

       TLS_method(), TLS_server_method(), TLS_client_method()
           These are the general-purpose version-flexible SSL/TLS methods.  The actual protocol version used will be negotiated to the highest
           version mutually supported by the client and the server.  The supported protocols are SSLv3, TLSv1, TLSv1.1, TLSv1.2 and TLSv1.3.
           Applications should use these methods, and avoid the version-specific methods described below.

       SSLv23_method(), SSLv23_server_method(), SSLv23_client_method()
           Use of these functions is deprecated. They have been replaced with the above TLS_method(), TLS_server_method() and TLS_client_method()
           respectively. New code should use those functions instead.

```

However, it turns out that all single protocoll methods are marked deprecated, in particular also `TLSv1_2_*method()`:

https://github.com/openssl/openssl/blob/5d238a1032fee0e4759c2ed7fbd09cb9d7125a72/include/openssl/ssl.h#L1902-L1904

Is this intentional? If yes, this needs to be documented more clearly in the manual page.

_(Side note: personally, I find it a bit confusing for the user that the TLS 1.2 methods are deprecated...)_

Related to issue #8726  (see the issue title and the first error message in the description)

**Comment by mattcaswell** [comment]
> Is this intentional? 

Yes. All single protocol methods should be deprecated.

**Comment by mspncp** [comment]
Ok, I found it (2b8fa1d56cd3a41d666994a1b2ed9df0f5e5d1ec):

```
commit 2b8fa1d56cd3a41d666994a1b2ed9df0f5e5d1ec
Author: Kurt Roeckx <kurt@roeckx.be>
Date:   Wed Mar 2 22:39:40 2016 +0100

    Deprecate the use of version-specific methods
    
    Reviewed-by: Viktor Dukhovni <viktor@openssl.org>
    
    MR: #1824
```
But then the documentation should be more explicit about that.

**Comment by mspncp** [comment]
I'll change the issue title accordingly.

**Comment by mspncp** [comment]
cc @kroeckx

**Comment by mspncp** [comment]
Actually, I can prepare a pr, unless you prefer to update the manpage yourself, Kurt.

**Comment by kroeckx** [comment]
Feel free to open a PR

**Comment by mspncp** [comment]
See #9001.
