### ISSUE TITLE
Build break: no-ui

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#899]
no-ui fails with the Windows build:
ibcrypto-1_1.def : error LNK2001: unresolved external symbol UI_new
libcrypto-1_1.def : error LNK2001: unresolved external symbol UI_new_method

**Comment by levitte** [comment]
I see no reason why UI should be possible to disable.  It's small and fairly innocuous.

**Comment by matbech** [comment]
Maybe the no-ui option should be removed then?

**Comment by richsalz** [comment]
No.  No-ui is important for embedded environments and those without stdio (eg UEFI)

**Comment by mattcaswell** [comment]
Should be fixed now.
