### ISSUE TITLE
SSL_set_tmp_ECDH API should be marked as deprecated

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#9014]
The `SSL_set_tmp_ECDH()` API call will override the values set by `SSL_set1_groups()`, at the same time it is more limited than the latter.

As such, it should be documented as deprecated in all releases that include both of those APIs.

See also: https://mta.openssl.org/pipermail/openssl-users/2019-May/010554.html

**Comment by mattcaswell** [comment]
> As such, it should be documented as deprecated in all releases that include both of those APIs.

As a matter of policy we can't go back in time and deprecate it for current stable releases. We definitely can (and should) deprecate it in master.

**Comment by tomato42** [comment]
"deprecate" for me means "warning, this is an old function/method, it will be removed in _future_ release"

Given ABI stability guarantees of OpenSSL, that of course means that they will continue to work in 1.0.2 or 1.1.1 as long as they are supported.

so, just to be clear: I do not expect any changes to code in stable branches

At the same time, I think updating the documentation is useful, as that will tell users of those versions that they should use different API to reduce the future maintenance burden of applications they write now.

**Comment by mattcaswell** [comment]
If you mark functions as deprecated using our deprecation macros then they automatically get compiled out if you compile with "no-deprecated" or using the "--api" flag with Configure. If those markings are backported to stable releases then suddenly applications using those options may stop working.

I have no objections to updating the documentation only in stable releases to suggest that it will be deprecated in a future version.

**Comment by frederikwh** [comment]
We all agree that it is changed on master? So this issue is solved by adding an update to the pod files in the current active branches (1.0.2, 1.1.0, 1.1.1)? I can help with that.

**Comment by levitte** [comment]
Side note: `no-deprecated` shouldn't be used in production.

**Comment by mattcaswell** [comment]
> Side note: no-deprecated shouldn't be used in production.

Why not?

**Comment by levitte** [comment]
> > Side note: no-deprecated shouldn't be used in production.
> 
> Why not?

Because it breaks expectations that deprecated functions are functions that are *marked for future removal*.  Since `no-deprecated` *removes* functions marked as deprecated, it defeats the normal purpose of deprecation as a warning.

In other words `no-deprecated` is a tool for application authors that really want to modify their applications for the bleeding edge nownownow.

I should have said "generally", of course.  For example, I would be terribly upset if Debian started building their openssl packages with `no-deprecated`.

**Comment by mattcaswell** [comment]
I disagree that this should not be used in production. There is nothing about `no-deprecated` that means it is unsuitable for production use.

It *does* have an impact on our backwards compatibility guarantees. So if you build with no-deprecated then you lose that guarantee. That is a decision for packagers to make though. In some circumstances it may be perfectly fine to lose that guarantee. For example, in many cases, the packager and the application author are the same person (such as where static linking is being used).

In this sense `no-deprecated` is no different to any other "no" option. If you build with `no-ec` then you're not going to be able to use any ec functions, and you're going to break any applications that do. But that might be ok, depending on your situation.

**Comment by t8m** [comment]
Yeah, no-deprecated should not be used when openssl is built as system-wide crypto library. It does not mean it should not be used when openssl is built as bundled library for a particular application for example.

**Comment by tomato42** [comment]
> We all agree that it is changed on master? So this issue is solved by adding an update to the pod files in the current active branches (1.0.2, 1.1.0, 1.1.1)? I can help with that.

@frederikwh 
yes, it does look like there is consensus about doing that.

small tip: if the patches needed to update the docs would be the same on different branches, it's not necessary to propose multiple PRs

**Comment by frederikwh** [comment]
> > We all agree that it is changed on master? So this issue is solved by adding an update to the pod files in the current active branches (1.0.2, 1.1.0, 1.1.1)? I can help with that.
> 
> @frederikwh
> yes, it does look like there is consensus about doing that.
> 
> small tip: if the patches needed to update the docs would be the same on different branches, it's not necessary to propose multiple PRs

I have searched the branches but I cannot find any reference to the functions SSL_set_tmp_ecdh() and SSL_CTX_set_tmp_ecdh(). 
Does it make sense to create documentation on something that will be deprecated on later releases?

**Comment by levitte** [comment]
> Does it make sense to create documentation on something that will be deprecated on later releases?

I think so. I think it makes sense to have them documented even if they *are* deprecated (and of course mention in the documentation that they are deprecated... Or possibly only have the deprecation notice as doc)

**Comment by kroeckx** [comment]
This was already done in #7522
