### ISSUE TITLE
Windows: Use same shared lib target name for both platforms

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#903]
I would prefer that the Windows build generates the same target name for the shared library (.dll), regardless of the target platform (x64, x86). Currently when building VC-WIN64 the -x64 suffix is added to the target output:
libcrypto-1_1-x64.dll
compared to: VC-WIN32
libcrypto-1_1.dll

The rational is that platform dependent file names make it more difficult for each task (building, testing, deployment, dynamic loading) because separate rules/code paths are required.

On Windows, dlls compiled against a different platform are usually deployed to different folders so file name conflicts are not an issue if the dlls for both platforms are deployed.

**Comment by levitte** [comment]
We've had loooong deliberations about this, taking input not only from native Windows builders, but from MingW folks as well.

In the end, "are *usually* deployed to different folders" was the key word.  *usually* doesn't meant *always*, so the `-x64` suffix was chosen to avoid the worst stoopid mistakes that will come back and bite us in the nether regions.

We did still avoid adding a `-x86` suffix for 32-bit builds... ;-)

**Comment by mattcaswell** [comment]
Question was answered. Closing this.
