### ISSUE TITLE
TLS1.3. SSL_key_update() Whether it takes effect

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#9046]
How can I know if tls1.3's key update api SSL_key_update is in effect, is there an api to view?

I called the API SSL_key_update(ssl,SSL_KEY_UPDATE_REQUESTED), but I didn't find the api to see if it works.

**Comment by mattcaswell** [comment]
The write key will be updated automatically the next time you attempt to write application data. The read key will be updated when the remote peer gets around to updating its key and you attempt to read data from that peer. There isn't a specific API available for checking this although you could probably see the key_update messages being sent and received via a msg_callback (see SSL_CTX_set_msg_callback).
