### ISSUE TITLE
bad decrypt with a symmetric key

### ISSUE THREAD

**Issue by sanikolov** [openssl/openssl#9049]
With openssl version _1.0.2g 1 Mar 2016_ I encrypt thus
$ echo 'secret message' | openssl enc -e -aes-256-cbc -k Password123 | base64
U2FsdGVkX1+QbM/fPgTdJlN9OjIpqfLNdxsSPa4Le1w=

With openssl version _1.1.0f  25 May 2017_ I decrypt the above result thus
$ echo 'U2FsdGVkX1+QbM/fPgTdJlN9OjIpqfLNdxsSPa4Le1w=' | base64 -di | openssl enc -d -aes-256-cbc -k Password123

**bad decrypt
139683559908608:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:535:**

Is there a regression test that catches these kinds of incompatibilities?

**Comment by richsalz** [comment]
https://www.openssl.org/docs/faq.html#USER3
