### ISSUE TITLE
openssl silently fails to create privateKey when PEM pass phrase not provided

### ISSUE THREAD

**Issue by davidedelvento** [openssl/openssl#905]
Consider the following:

```
davide@somewhere /tmp/openssl $ openssl pkcs12 -in xxx.p12 -nocerts -out privateKey.pem
Enter Import Password: <right password typed here>
MAC verified OK
Enter PEM pass phrase: <just type ENTER as sometimes done with ssh-keygen>
davide@somewhere /tmp/openssl $ ls -l
total 8
-rw-r--r-- 1 ddvento ddvento  156 Mar 21 11:08 privateKey.pem
-rw-r--r-- 1 ddvento ddvento 3272 Mar 21 10:49 xxx.p12
ddvento@cisl-ddventosa /tmp/openssl $ cat privateKey.pem 
Bag Attributes
    localKeyID: [an hex ID]
    friendlyName: [a friendly name]
Key Attributes: <No Attributes>
```
As you can see, privateKey.pem is "broken", most notably, there is no section starting with `-----BEGIN ENCRYPTED PRIVATE KEY-----` or `-----BEGIN PRIVATE KEY-----` which would be created if one enters a non-empty PEM pass phrase.

I understand the behavior might be the "right" one, but the UI feels very confusing. At least a warning message stating the problem is due, IMHO, something like 

``` Warning: not providing PEM pass phrase will result in no private key in  <filename> file ```

**Comment by levitte** [comment]
Thank you.  What's happening is that the `openssl pkcs12` doesn't detect or display the errors happening when writing PEM data, and that includes failure to give a pass phrase (zero length pass phrases are not valid for exporting keys).  Fix coming up.

**Comment by levitte** [comment]
Would you mind checking that the change in PR #1025 makes a difference?

**Comment by davidedelvento** [comment]
Unfortunately I don't have the build infrastructure in place and I'm too busy at the moment to set it up. But I tried this with various .p12 files and I'm confident you could reproduce a before/after behavior pretty easily (once you have the before/after binaries).

Thanks for the fix and asking me to review it, though!

**Comment by mattcaswell** [comment]
Fix was provided. Closing this.
