### ISSUE TITLE
Build break: no-dgram

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#906]
no-dgram fails with the Windows build:
libcrypto-1_1.def : error LNK2001: unresolved external symbol BIO_dgram_non_fatal_error
libcrypto-1_1.def : error LNK2001: unresolved external symbol BIO_new_dgram

**Comment by mattcaswell** [comment]
This should be fixed in latest master.

**Comment by skorniakov** [comment]
With openssl-1.1.1a I got 3 unresolved externals if using no-dgram:

libcrypto.def : error LNK2001: unresolved external symbol BIO_dgram_non_fatal_error
libcrypto.def : error LNK2001: unresolved external symbol BIO_new_dgram
libcrypto.def : error LNK2001: unresolved external symbol BIO_s_datagram
libcrypto.lib : fatal error LNK1120: 3 unresolved externals

And 10 for no-comp:
libcrypto.def : error LNK2001: unresolved external symbol COMP_CTX_free
libcrypto.def : error LNK2001: unresolved external symbol COMP_CTX_get_method
libcrypto.def : error LNK2001: unresolved external symbol COMP_CTX_get_type
libcrypto.def : error LNK2001: unresolved external symbol COMP_CTX_new
libcrypto.def : error LNK2001: unresolved external symbol COMP_compress_block
libcrypto.def : error LNK2001: unresolved external symbol COMP_expand_block
libcrypto.def : error LNK2001: unresolved external symbol COMP_get_name
libcrypto.def : error LNK2001: unresolved external symbol COMP_get_type
libcrypto.def : error LNK2001: unresolved external symbol COMP_zlib
libcrypto.def : error LNK2001: unresolved external symbol ERR_load_COMP_strings
libcrypto.lib : fatal error LNK1120: 10 unresolved externals

**Comment by mspncp** [comment]
I just tried `no-dgram` with the current master, and I had no problems. Was your source tree clean when you reconfigured? Please try `nmake clean`, then reconfigure and build again.

**Comment by skorniakov** [comment]
> 
> 
> I just tried `no-dgram` with the current master, and I had no problems. Was your source tree clean when you reconfigured? Please try `nmake clean`, then reconfigure and build again.

Thanks, nmake clean solved the problem.
