### ISSUE TITLE
Lost optimization O3 in 1.1.1c

### ISSUE THREAD

**Issue by lzsiga** [openssl/openssl#9061]
Hi, it seems to me that in version `1.1.1c` compiler-option `-O3` has been removed from `CFLAGS` resulting unoptimized programs. (It is still present in `CXXFLAGS` which is not used during C-compilation).

Specifying option `--release` during `./Configure` doesn't help; pre-setting CFLAGS to -O3 helps.

**Comment by levitte** [comment]
What platform?  How did you configure?  Showing us the output of `perl configdata.pm --dump` would be very helpful in answering these kinds of questions.

**Comment by lzsiga** [comment]
Thank you for your reply; It's AIX and Linux; I'll try and provide details soon.

**Comment by lzsiga** [comment]
Well, I think it is related with #8325 , but by now I've fixed my compile-scripts, and now they work all right. Let's say it was a single-user problem.
