### ISSUE TITLE
Build break: no-sock

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#907]
no-sock fails with the Windows build:
libcrypto-1_1.def : error LNK2001: unresolved external symbol BIO_ADDRINFO_address
libcrypto-1_1.def : error LNK2001: unresolved external symbol BIO_ADDRINFO_family
...
libcrypto-1_1.def : error LNK2001: unresolved external symbol BIO_socket
libcrypto-1_1.def : error LNK2001: unresolved external symbol BIO_socket_ioctl
libcrypto-1_1.def : error LNK2001: unresolved external symbol BIO_socket_nbio
libcrypto.lib : fatal error LNK1120: 41 unresolved externals

**Comment by levitte** [comment]
Does f9e550341281b0d344f7a5e7ac2ace79f88a3184 fix it for you?

**Comment by matbech** [comment]
Unfortunately, no.

**Comment by mattcaswell** [comment]
Looks like the functions aren't being flagged with "SOCK" in libcrypto.num

**Comment by mattcaswell** [comment]
This should be fixed now in latest master.
