### ISSUE TITLE
Performance issues with OpenSSL 1.1.1c caused by DEVRANDOM_WAIT

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#9078]
In pull request #8251, a `select()` call on `/dev/random` was added before reading from `/dev/urandom`. Let's call it the `DEVRANDOM_WAIT` feature, named after the preprocessor macro involved.

https://github.com/openssl/openssl/blob/f308fa2573b0320236cd2c2d73db37c49e3eb779/crypto/rand/rand_unix.c#L492-L514

The intention of this change was to mitigate a weakness of the `/dev/urandom` device, namely that it does not block until being initially seeded, contrary to the `getrandom()` system call, see issue #8215. Note that this change does not affect the seeding using the `getrandom()` source, which is the preferred method on newer operating systems.

There was a some discussion on the issue thread before PR #8251 was raised. While people unanimously agreed that using `getentropy()` is fine, because it [blocks at boot time](https://github.com/openssl/openssl/issues/8215#issuecomment-463178127) (see also @kroeckx's [comment](https://github.com/openssl/openssl/issues/8215#issuecomment-463306506)) until the kernel CSPRNG is properly seeded, there was some  dissent about whether the `/dev/urandom` weakness should be addressed by OpenSSL.

@t8m and I agreed that it is actually the business of the OS (resp. its init system) to take care of this and not OpenSSL's business. (see https://github.com/openssl/openssl/issues/8215#issuecomment-463537207 and https://github.com/openssl/openssl/issues/8215#issuecomment-463182881). Pull request #8251 emerged as a compromise; the idea was to wait for `/dev/random` to become readable (without reading any bytes) before reading from `/dev/urandom`. Nobody protested anymore, except for @t8m ([here](https://github.com/openssl/openssl/issues/8215#issuecomment-465136037) and [here](https://github.com/openssl/openssl/pull/8251#issuecomment-470046047)), who was no committer yet at that time, and his protests went unnoticed.

However, there is a recent [issue report on openssl-users](https://mta.openssl.org/pipermail/openssl-users/2019-May/010571.html) that this change introduced a regression and has unwanted performance impacts.

>> I built OpenSSL 1.1.1c from the recent release, but have noticed what 
>> seems like a significant performance drop compared with 1.1.1b.  I 
>> notice this when starting lighttpd.  With 1.1.1b, lighttpd starts in a 
>> few seconds, but with 1.1.1c, it takes several minutes.
>
>I think I have tracked down the change in 1.1.1c that is causing this.  
>It is the addition of the DEVRANDOM_WAIT functionality for linux in 
>e_os.h and crypto/rand/rand_unix.c.  lighttpd (libcrypto) is waiting in 
>a select() call on /dev/random.  After this eventually wakes up, it then 
>reads from /dev/urandom.  OpenSSL 1.1.1b did not do this, but instead 
>just read from /dev/urandom.  Is there more information about this 
>change (i.e., a rationale)?  I did not see anything in the CHANGES file 
>about it.
>
>Jay

I think we need to reconsider pull request #8251 and decide whether it was really good idea to fix a problem of the kernel resp. the init system in the OpenSSL library, or whether the negative side-effects outweigh the benefits. Currently, I'm leaning towards reverting the `DEVRANDOM_WAIT` commits on master and 1.1.1.

What's your opinion @openssl/committers?

**Comment by mspncp** [comment]
Side Note:  @t8m noticed that this feature can be disabled by the following 'hack': just add an explicit `-DDEVRANDOM=...` compiler argument, then the following conditional code will not be compiled and `DEVRANDOM_WAIT` will be undefined.

https://github.com/openssl/openssl/blob/f308fa2573b0320236cd2c2d73db37c49e3eb779/e_os.h#L25-L34

**Comment by mspncp** [comment]
I pinged the original reporter on [openssl-users](https://mta.openssl.org/pipermail/openssl-users/2019-June/010630.html) and hope he will join our discussion here.

**Comment by t8m** [comment]
So my opinion is of course still the same, i.e. we should not attempt to outsmart the kernel and/or init system.

**Comment by richsalz** [comment]
I understand not trying to outsmart the local platform, but most OpenSSL users are naive about cryptography, and especially about CSPRNG seeding. We should avoid simple cases where they can make mistakes that result in guessable key material, as in https://crypto.stanford.edu/RealWorldCrypto/slides/nadia.pdf et al.

**Comment by kroeckx** [comment]
Switching to getentropy() also had the effect that people got long
delays during boot or starting services the first time. So we're
now in the situation that using getentropy() or /dev/urandom
will both make us wait until the kernel tells it's ready.

So there are at least a few cases that run into this:
- You really have no entropy, you don't even store it
  between boots.
- You have entropy from the previous boot, but don't
  count it, you're waiting for fresh entropy to avoid
  an attack on the stored file.

In the first case, something really needs to wait until we have
entropy. You can argue about who it should be, OpenSSL or
something else. People get it wrong, so you can argue that OpenSSL
should protect them.

The 2nd case is really what most people that will complain about
it being slow run into. It's a local policy issue that you trust
that file or not. Most Linux distributions will take the safe way
and not trust that file, but still use it. I don't know if they
have a setting to say to trust it or not if you're not worried
about such an attack.

Recent Linux kernels will make use of things like RDRAND/RDSEED or
other hardware RNGs that are available in most modern hardware,
and will have enough new entropy very early in the boot process.
So switching to a newer kernel might fix your issues. It will also
switch you to using getentropy().

People running in a VM should make sure that the guest OS gets
entropy from the host OS.

**Comment by mspncp** [comment]
> Switching to getentropy() also had the effect that people got long
> delays during boot or starting services the first time. So we're
> now in the situation that using getentropy() or /dev/urandom
> will both make us wait until the kernel tells it's ready.

There is one important difference between `getentropy()` and the `DEVRANDOM_WAIT` method IMO: with the former, you only wait once in the early boot phase, until the initial seeding has completed, while the `select()` call can block at any time afterwards if the `entropy_avail` count goes down to zero. So you might not be starving other processes, because you don't actually read from `/dev/random`, but you might be starved by other processes hogging the entropy count of the random pool.

**Comment by t-j-h** [comment]
I would revert the commit. @tm8 is correct in that this isn't where we should be trying to fix things.

**Comment by richsalz** [comment]
If this isn’t where to fix things, then where do you think it should be address?  In every single application that generates keys?

**Comment by kroeckx** [comment]
I think the options are, in order of preference:
- In every Linux based OS
- In every software that reads from /dev/urandom on Linux
- In every application that uses crypto

The problem should fix itself as OSs adopt more recent Linux
kernels. That really is the only fix we can actually expect from
the OSs. Some are stuck on a very old kernel, you can buy new
devices that still ship with a 2.6 kernel.

**Comment by richsalz** [comment]
Okay, so tell me what Apache's mod_ssl should do that's portable for all the OpenSSL versions that it supports.  And also what should OpenSSL do when running on an old kernel, for unaware developers porting packages?

Right now, OpenSSL is safe but maybe slow to startup, and a careful consumer can rebuild openssl to not be slow.  That seems to me to be *exactly* the right trade-off.

Remind me again why you wanted RSA 2K keys as the minimum, Kurt? :)

**Comment by paulidale** [comment]
I think OpenSSL should be attempting to ensure good entropy.

Ideally the kernel/OS would but not all do, so having a fallback of libcrypto trying seems prudent.


> There is one important difference between `getentropy()` and the `DEVRANDOM_WAIT` method IMO: with the former, you only wait once in the early boot phase, until the initial seeding has completed, while the `select()` call can block at any time afterwards if the `entropy_avail` count goes down to zero. So you might not be starving other processes, because you don't actually read from `/dev/random`, but you might be starved by other processes hogging the entropy count of the random pool.

Adding a flag to only wait once would avoid this difference.  Once seeded `/dev/urandom` should be good essentially forever.  Instead of a flag it could be in a run once RNG code path.

**Comment by vdukhovni** [comment]
We can try to make things as simple as possible for the user, BUT no simpler.
This change crossed the boundary and needs to be reverted. Ensuring early boot entropy is an O/S platform task, OpenSSL cannot solve this problem, and must not try.

**Comment by mspncp** [comment]
> Adding a flag to only wait once would avoid this difference. Once seeded /dev/urandom should be good essentially forever. Instead of a flag it could be in a run once RNG code path.

There is already such a flag, it is called `wait_done`.

https://github.com/openssl/openssl/blob/98475995e1835f20ac4f4b83ec90a3e36fdb0861/crypto/rand/rand_unix.c#L500-L502

Maybe my https://github.com/openssl/openssl/issues/9078#issuecomment-498834978 gave the wrong impression that forking processes would be waiting several  times. Actually, we don't have that much information about the exact circumstances, apart form the facts cited from the original report.

> I built OpenSSL 1.1.1c from the recent release, but have noticed what
> seems like a significant performance drop compared with 1.1.1b. I
> notice this when starting lighttpd. With 1.1.1b, lighttpd starts in a
> few seconds, but with 1.1.1c, it takes several minutes.

In particular, we don't know whether the massive delay occurs only at early boot time or always. And no information about OS/kernel version. I hope the original reporter shows up and provides more detail.

**Comment by paulidale** [comment]
@mspncp I should have looked at the code :(

**Comment by paulidale** [comment]
-1 (vote forcing).  This one might come down to an OMC vote since it seems two in favour and two agin at present.

**Comment by paulidale** [comment]
I also wonder what happens in FIPS mode where `/dev/urandom` is an acceptable entropy source only if  _**the vendor must first demonstrate that the initial call (...) to /dev/urandom returns the claimed amount of entropy**_.

I'm not sure how this can be done generally.  Refer to [IG 7.15](https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/fips140-2/fips1402ig.pdf).

**Comment by vdukhovni** [comment]
Best I can determine, select on the Linux /dev/random will block any time there is insufficient "fresh entropy" in the kernel entropy pool, not just initially at boot.  While OpenSSL will block at most once per process, the delay is unbounded, unpredictable and unacceptable.  If /dev/random were to return "ready" for select even though a read(2) would block for lack of entropy, that would be a kernel bug.

The original PR must be reverted. If someone wants to block on /dev/random, they'll have to do that explicitly at the application layer. Perhaps `ssh-keygen` and/or `openssl genpkey` could elect to do that, but this must not be inflicted on unsuspecting applications by default.

**Comment by paulidale** [comment]
I agree that select(2) on `/dev/random` isn't ideal.
What other metric can we use to determine that `/dev/urandom` is adequately seeded?

**Comment by mspncp** [comment]
> -1 (vote forcing). This one might come down to an OMC vote since it seems two in favour and two agin at present.

I agree. Given the current progress of the discussion, an OMC vote seems inevitable. If there is no hurry, I would prefer however that we collect more information about the case first. I just sent [another invitation](https://mta.openssl.org/pipermail/openssl-users/2019-June/010632.html) to the reporter on the mailing list.

**Comment by mspncp** [comment]
> The original PR must be reverted. 

Commit cff8ff87ad76b93874922dd8c99f5f0fbd09e757 actually contains two parts and only the first part needs to be reverted IMO:

```
1) Use select to wait for /dev/random in readable state,
   but do not actually read anything from /dev/random,
   use /dev/urandom first.

2) Use linux define __NR_getrandom instead of the
   glibc define SYS_getrandom, in case the kernel headers
   are more current than the glibc headers.
```
(For the second part, see also https://github.com/openssl/openssl/issues/8215#issuecomment-463586870 and https://github.com/openssl/openssl/issues/8215#issuecomment-463642246).

**Comment by paulidale** [comment]
I'm not aware that calling a vote requires a strict timeline (I could easily be wrong).

I'd also prefer to see a better method to ensure that `/dev/urandom` has been seeded.  I'm not aware of one at this point.

**Comment by mspncp** [comment]
> Best I can determine, select on the Linux /dev/random will block any time there is insufficient "fresh entropy" in the kernel entropy pool, not just initially at boot. 

FWIW: The draining effect is a fact which actually can be verified by simple experiments:

In one terminal, run 

```
watch -n 1 cat /proc/sys/kernel/random/entropy_avail
```

and in the other terminal, run either

```
dd if=/dev/urandom of=/dev/null bs=64 count=1
```

or

```
dd if=/dev/random of=/dev/null bs=64 count=1
```

several times. Reading from `/dev/urandom` does not affect the entropy count of the random pool, while reading from `/dev/random` drains it, such that the read finally blocks. The DEVRANDOM_WAIT case could equally be simulated using a small C program that selects on `/dev/random` before reading from `/dev/urandom`. But I havn't done it yet.

**Comment by mspncp** [comment]
> I'm not aware that calling a vote requires a strict timeline (I could easily be wrong).

Adding a '-1' of course doesn't.  But an official announcement of the vote on the mailing list would include a timeline. I just attempted to preempt the latter.

**Comment by vdukhovni** [comment]
>   1) Use select to wait for /dev/random in readable state,
>    but do not actually read anything from /dev/random,
>    use /dev/urandom first.
> 
> 2) Use linux define __NR_getrandom instead of the
>    glibc define SYS_getrandom, in case the kernel headers
>    are more current than the glibc headers.

Yes, of course, we don't need to revert part 2, that's a feature, not a bug. Many Linux systems have kernels that are substantially newer than the userland.

**Comment by slontis** [comment]
It may be required for FIPS_MODE,
unless another entropy source is going to magically appear from somewhere.

**Comment by mspncp** [comment]
> It may be required for FIPS_MODE,

If I understood Pauli correctly, the FIPS lab is perfectly happy with `getrandom()`, which blocks until the kernel CSPRNG is initially seeded, but not afterwards anymore. So we could simply make it a minimum requirement for FIPS mode, that the kernel is new enough to support it, instead of worrying about the quirks of `/dev/urandom`.

**Comment by vdukhovni** [comment]
Perhaps FIPS-mode applications deserve all the punishment they signed up for. :-) If no other options are available the FIPS RNG can wait for /dev/random if required. FIPS aside, let's revert "part 1".

**Comment by mspncp** [comment]
> It may be required for FIPS_MODE,

If at some time in the (hopefully near) future we finally have the ability to configure our seed sources, the `DEVRANDOM_WAIT` feature could be reintroduced as an optional feature which is disabled by default:

```
rand_seed=getrandom,devurandom_wait,devrandom
```

**Comment by mspncp** [comment]
> FIPS aside, let's revert "part 1".

I can prepare a pull request as basis for an OMC vote, unless @bernd-edlinger prefers to do it himself.

**Comment by bernd-edlinger** [comment]
I'm not in a hurry, but go ahead if you like,
from the user report it looks like this is more or less what would have happened without waiting:
```
random: sshd: uninitialized urandom read (32 bytes read)
random: lighttpd: uninitialized urandom read (4096 bytes read)
```
The system would also block if getentropy was used, no doubt getentropy would be preferrable.

**Comment by vdukhovni** [comment]
The difference with `getentropy()` is that blocking does happen only once and not repeatedly thereafter as the entropy pool is "depleted". Provided some effort is made by the O/S platform to make that initial delay acceptably short, it will be tolerable. This is rather different from the situation with the /dev/random select.

**Comment by kroeckx** [comment]
The only reason I can see that /dev/random goes from readable to
blocking again is that someone is abusing /dev/random. For normal
use, where everybody uses /dev/urandom, /dev/random should stay
readable.

**Comment by mspncp** [comment]
See pull request #9084.

**Comment by ylavic** [comment]
> In one terminal, run
> 
> ```
> watch -n 1 cat /proc/sys/kernel/random/entropy_avail
> ```

In case where getrandom() is not available, and since `/dev/random` select()ion looks buggy, isn't select()ing the above file the way to wait for first the entropy bytes then?

**Comment by paulidale** [comment]
Selecting on /proc/sys/kernel/random/entropy_avail won't work, it's always readable.
Reading its contents also doesn't work for more complicated reasons.

**Comment by t8m** [comment]
Blocking on /dev/random being readable is DoS attack avenue. Currently the Linux distributions in general allow read from /dev/random to regular users. There are only some SELinux domains that have read from /dev/random blocked (btw this is another reason why opening /dev/random is not that good idea although the current code handles this fine).

**Comment by paulidale** [comment]
> If at some time in the (hopefully near) future we finally have the ability to configure our seed sources, the `DEVRANDOM_WAIT` feature could be reintroduced as an optional feature which is disabled by default:

I like this suggestion, but I'd prefer secure by default.  That is, enabled by default.

Log term key generation on first boot with little or no entropy is a problem which has been recorded numerous times in the past.  One I'd rather not repeat.

**Comment by mspncp** [comment]
> I like this suggestion, but I'd prefer secure by default. That is, enabled by default

Our solution will be secure by default: it will choose `getrandom()` if it's available. The `/dev/urandom` device is [broken by kernel design](https://github.com/openssl/openssl/issues/8215#issuecomment-463814145) and we are not in the position to fix it. So our advise to the user should be: get yourself a newer kernel or accept that it is unsafe for you to use this operating system. (There will probably be a lot more CVEs than just an unreliable random generator.)

**Comment by richsalz** [comment]
I hope there is a FAQ, a CHANGES/NEWS note, etc., to make it very clear that applications that WERE secure by default now must do something new. And I hope that OpenSSL makes that "something new" be very simple, such as calling a new API. And I hope that OpenSSL makes it clear that this was a convenience security trade-off that the OMC decided to make.

**Comment by mspncp** [comment]
> I hope there is a FAQ, a CHANGES/NEWS note, etc., to make it very clear that applications that WERE secure by default now must do something new.

Of course there will also be a CHANGES note, thank you for reminding me.

But your sentence contains an important error: It is _not_ correct that this pull request removes a feature that used to be in libcrypto all the time.

Ever since the release of 1.1.1, reading from the non-blocking `/dev/urandom` device was the second choice on Unix platforms if the `getrandom()` system call was not available. And there was _no_ waiting involved. The `DEVRANDOM_WAIT` feature was introduced only recently and added on-the-fly to the 1.1.1c bug-fix release, [without announcing that change in the CHANGES file](https://mta.openssl.org/pipermail/openssl-users/2019-May/010576.html).

So this pull request actually needs to add two CHANGES entries, one for adding the feature and one for removing it.

**Comment by richsalz** [comment]
I didn't say "used to be in libcrypto all the time." :)

**Comment by mspncp** [comment]
You said 

> ...applications that WERE secure by default...

which was suggestively formulated and is not correct. To be precise, applications WERE NEVER secure by default if you consider it insecure to read from `/dev/urandom` without checking whether it has been properly seeded.

**git log --oneline -S 'define DEVRANDOM'**
fb9163ba4d e_os.h: add prandom and hwrng to the list of random devices on s390x.
f642ebc1e2 Undo a90081576c94f9f54de1755188a00ccc1760549a
a90081576c Remove DJGPP (and therefore WATT32) #ifdef's.
4bd46774bb Move the definition of DEVRANDOM for DJGPP from Configure to e_os.h. That should solve the issues with propagating it through the Makefiles.
599c03530a Add automatic query of EGD sockets to RAND_poll(). 
58964a4922 Import of old SSLeay release: SSLeay 0.9.0b



https://github.com/openssl/openssl/blob/58964a492275ca9a59a0cd9c8155cb2491b4b909/e_os.h#L72-L76

**Comment by richsalz** [comment]
Did 1.1.1 wait until the device was ready?  If so, then applications were secure.

**Comment by mspncp** [comment]
No it didn't. Below is the code from 1708e3e85b4a86bae26860aa5d2913fc8eff6086, the 1.1.1 release. It would just try to open and read from the devices in the `random_device_paths` list in order and stop as soon as it succeeded. Since the first entry is `/dev/urandom`, this would in general be the only random device which was opened.


https://github.com/openssl/openssl/blob/1708e3e85b4a86bae26860aa5d2913fc8eff6086/e_os.h#L30-L35

https://github.com/openssl/openssl/blob/1708e3e85b4a86bae26860aa5d2913fc8eff6086/crypto/rand/rand_unix.c#L307

https://github.com/openssl/openssl/blob/1708e3e85b4a86bae26860aa5d2913fc8eff6086/crypto/rand/rand_unix.c#L339-L351

**Comment by richsalz** [comment]
Sorry for causing all this work and fuss.  I was wrong.  I thought the select/wait was in a release.

**Comment by mspncp** [comment]
No problem. It's always a pleasure to fight a battle of words with you ;-)

And once again I'm amazed how much emotions such a dry subject like a random generator can raise... :-P

**Comment by hyc** [comment]
If you revert this wait, you will flunk most commercial security audits.
https://paragonie.com/blog/2016/05/how-generate-secure-random-numbers-in-various-programming-languages

I'm not saying they're correct. Just saying, some time back, "everyone" agreed this was the right thing to do. Fwiw I never agreed with it back then either. Just be aware that you will meet political resistance to a change like this.

**Comment by vdukhovni** [comment]
> Just be aware that you will meet political resistance to a change like this.

That's OK, asbestos underwear is on. Reverting to 1.1.1 as released originally and 1.1.1[ab] is quite defensible.

**Comment by richsalz** [comment]
So @mspnc, in 1.1.1c things got more secure and this removes that putting the onus on the end-user or application.  So, I guess I was right?

**Comment by mspncp** [comment]
Sigh... I'm exhausted. You are wasting your energy on me, in the end it will be the OMC which makes the decisions.

Apropos energy: your energy would probably be better spent convincing Theodore Ts'o to rethink his decision not to block `/dev/urandom` during early boot in order not to break userland programs (see his commit message [c6e9d6f38894](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=c6e9d6f38894798696f23c8084ca7edbf16ee895)). This is the right place were you could advertise your ideas to make `/dev/urandom` more secure.  ;-)

**Comment by mspncp** [comment]
But we are turning in circles. The kernel already has been improved and people just need to move on to using getrandom() instead of /dev/urandom. Which is what OpenSSL did.

**Comment by mspncp** [comment]
Y

**Comment by mspncp** [comment]
Ups!

**Comment by richsalz** [comment]
I'll stop; I certainly don't want to (heh) exhaust a vital resource like yourself.

"Just upgrade kernels" isn't always feasible, and I think backing out of a security improvement is premature.  Shrug.  YMMV.

**Comment by t8m** [comment]
> Apropos energy: your energy would probably be better spent convincing Theodore Ts'o to rethink his decision not to block `/dev/urandom` during early boot in order not to break userland programs (see his commit message [c6e9d6f38894](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=c6e9d6f38894798696f23c8084ca7edbf16ee895)). This is the right place were you could advertise your ideas to make `/dev/urandom` more secure. ;-)

Nope, this is not a good use of anyone's energy either :), find another thing to spend the energy on. The non-blockability of /dev/urandom on Linux is set in stone and it will not change. And moreover even if the iface was not set in stone it does not make any sense to change it as everyone should be moving to getrandom() anyway which has the desired property and also more advantages such as not needing a file descriptor and a device on system.

**Comment by mspncp** [comment]
> Nope, this is not a good use of anyone's energy either :)

This occurred to me too after writing it. That's why I posted https://github.com/openssl/openssl/issues/9078#issuecomment-499181857.

**Comment by aalexand** [comment]
As a data point, I've spent good amount of time chasing sudden hangs of `npm` when running in a virtual machine on Google Cloud. It turned out to be related to upgrade of Node version to 10.16.1 which upgrades to OpenSSL 1.1.1c and this issue apparently is the cause - virtual machines have less entropy available in them I think.

**Comment by bernd-edlinger** [comment]
which linux version is that?

**Comment by kroeckx** [comment]
If you run in a virtual machine, you should make sure you actually
get rng data from the host by using something like virtio rng.


Kurt

**Comment by bernd-edlinger** [comment]
I think the described behaviour can most likely occur when a recent linux version is used
but the cross compiler does not have a define for __NR_getrandom under low entropy.
Then the all entropy from the input pool is periodically transferred to the CRNG.
But in such systems the /dev/random is not supposed to be used.
Can someone confirm if I am right with that theory ?
I would need the linux version and if __NR_getrandom is available when compiling OpenSSL.

**Comment by jasonster17** [comment]
When was this issue manifesting, for TCP connections? Was the delay only happening on the handshake process? Or did it occur repeatedly on data transfer?

**Comment by paulidale** [comment]
Library startup.

**Comment by jasonster17** [comment]
> Library startup.

Thanks for the info!

**Comment by guozhaohui** [comment]
I can still confirm those DEVRANDOM_WAIT related implementation in ver.1.1.1d and face the performance issue.

By read this long discussion, I found that this performance issues was solved by the following commit.
commit ad416c80581c181f3c96f47c670626bf3ff58410
Author: Dr. Matthias St. Pierre <Matthias.St.Pierre@ncp-e.com>
Date:   Wed Jun 5 11:09:46 2019 +0200

    Revert the DEVRANDOM_WAIT feature

But after checked the log, I found that the revert was restored by the following commit.
commit 3ff98f558157ada23a3527d82793a524eb8263ec
Author: Pauli <paul.dale@oracle.com>
Date:   Tue Aug 20 16:19:20 2019 +1000

    Start up DEVRANDOM entropy improvement for older Linux devices.

**Comment by paulidale** [comment]
This isn't so much a performance issue, it is a security issue.

High quality random numbers are critical to maintain security.  What the waiting is doing is getting such high quality randomness.  Not waiting means you won't have as much (or often any) level of security.

**Comment by t8m** [comment]
It was always a little bit controversial topic. In my opinion having the wait does not belong to openssl library itself but should be handled by external ways. In case the shared memory marker does not work for some reason openssl will always unnecessarily wait although the system RNG was already fully seeded with entropy. But yes, having the kernel RNG sufficiently seeded with quality entropy on the system boot is absolutely critical to security.

**Comment by paulidale** [comment]
In most situations, OpenSSL won't wait even if the shared memory marker doesn't work.

Depending on the kernel and operating system: select(/dev/random) will succeed immediately and read(/dev/random, 1) will consume one byte.  Once everything is properly seeded of course.

**Comment by t8m** [comment]
The `read(/dev/random, 1)` will consume all the available random bytes quickly if openssl is started many times at once. Unless you have rngd/jitterentropy or some HW entropy source.
