### ISSUE TITLE
undefined symbol: SSL_SESSION_hash 

### ISSUE THREAD

**Issue by winer632** [openssl/openssl#908]
undefined symbol: SSL_SESSION_hash

**Comment by mattcaswell** [comment]
You need to give us more information than the above. Under what circumstances do you see this, i.e. which version of OpenSSL, which platform, what options to Configure did you supply, etc.

**Comment by winer632** [comment]
[root@iZ23djkgcm2Z wangxx]# tar -xzvf openssl-OpenSSL_1_0_1s.tar.gz
[root@iZ23djkgcm2Z wangxx]# cd /home/wangxx/openssl-OpenSSL_1_0_1s
[root@iZ23djkgcm2Z wangxx]# ./config shared --prefix=/usr/local --openssldir=/usr/local/openssl && make && make install

[root@iZ23djkgcm2Z wangxx]#cd /opt/OpenIMSCore/ser_ims/modules/tls
[root@iZ23djkgcm2Z tls]#make clean
[root@iZ23djkgcm2Z tls]#make

[root@iZ23djkgcm2Z tls]#cd /opt/OpenIMSCore
[root@iZ23djkgcm2Z OpenIMSCore]# bash pcscf.sh
 0(6877) ERROR: load_module: could not open module </opt/OpenIMSCore/ser_ims/modules/tls/tls.so>: /opt/OpenIMSCore/ser_ims/modules/tls/tls.so: undefined symbol: SSL_SESSION_hash
 0(6877) parse error (167,13-14): failed to load module
 0(6877) set_mod_param_regex: No module matching <tls> found
 0(6877) parse error (169,20-21): Can't set module parameter
 0(6877) set_mod_param_regex: No module matching <tls> found
 0(6877) parse error (173,19-20): Can't set module parameter
 0(6877) set_mod_param_regex: No module matching <tls> found
 0(6877) parse error (174,19-20): Can't set module parameter
 0(6877) set_mod_param_regex: No module matching <tls> found
 0(6877) parse error (175,19-20): Can't set module parameter
 0(6877) set_mod_param_regex: No module matching <tls> found
 0(6877) parse error (176,20-21): Can't set module parameter
 0(6877) set_mod_param_regex: No module matching <tls> found
 0(6877) parse error (177,20-21): Can't set module parameter
 0(6877) set_mod_param_regex: No module matching <tls> found
 0(6877) parse error (178,20-21): Can't set module parameter
ERROR: bad config file (8 errors)
 0(6877) INFO:P-CSCF:mod_destroy: child exit
pcscf.sh: line 7:  6877 Segmentation fault      LD_LIBRARY_PATH="/usr/local/lib/ser" /opt/OpenIMSCore/ser_ims/ser -f /opt/OpenIMSCore/pcscf.cfg -D -D
[root@iZ23djkgcm2Z OpenIMSCore]# 



in D:\work\openimscore-code-1194-modify\ser_ims\trunk\modules\tls\tls_select.c, I can see the code ses_hash = SSL_SESSION_hash(ssl_ses); It should be here where trigger the error "undefined symbol: SSL_SESSION_hash"

/**
 * get TLS Session Hash  
 * @param msg - sip msg received over a TLS secure connection
 * @returns session_hash or 0 in case of error
 */
unsigned long  get_tls_session_hash(struct sip_msg* msg, char *str1, char *str2)
{
	struct tcp_connection* c;
	struct tls_extra_data* extra;
	SSL_SESSION *ssl_ses;
	unsigned long ses_hash;
	
	if (msg->rcv.proto != PROTO_TLS) {
		ERR("get_tls_session_hash: No TLS connection !\n");
		return 0;
	}
	c = tcpconn_get(msg->rcv.proto_reserved1, 0, 0, tls_con_lifetime);
	if (c && c->type != PROTO_TLS) {
		ERR("get_tls_session_hash: Connection found but is not TLS !\n");
		tcpconn_put(c);
		return 0;
	}

	if (!c || !c->extra_data) {
		ERR("get_tls_session_hash: Unable to extract SSL data from TLS connection!\n");
		return 0;
	}
	extra = (struct tls_extra_data*)c->extra_data;
	
	ssl_ses = SSL_get_session(extra->ssl) ;
	if (!ssl_ses)
	{
		ERR("get_tls_session_hash: No ssl session found !\n");
		tcpconn_put(c);
		return 0;
	}
	ses_hash = SSL_SESSION_hash(ssl_ses);
	
	tcpconn_put(c);
	return ses_hash;
}

**Comment by winer632** [comment]
There is no symbol SSL_SESSION_hash in openssl-1.0.* however SSL_SESSION_hash exists in openssl-0.9.8*. See below.
 
[root@iZ23djkgcm2Z tls]# nm /home/wangxx/openssl-OpenSSL_1_0_1s/libssl.so.1.0.0 | grep SSL_SESSION_hash
[root@iZ23djkgcm2Z tls]# 

[root@iZ23djkgcm2Z tls]# nm /home/wangxx/openssl-OpenSSL_0_9_8e/libssl.so.0.9.8 | grep SSL_SESSION_hash
000000000002e450 T SSL_SESSION_hash
000000000002e480 t SSL_SESSION_hash_LHASH_HASH
[root@iZ23djkgcm2Z tls]# 

My tls.so served in openimscore project.

[root@iZ23djkgcm2Z tls]# ldd tls.so 
        linux-vdso.so.1 =>  (0x00007fffcd9fe000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2743be5000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f27439ca000)
        libssl.so.1.0.0 => /usr/local/lib64/libssl.so.1.0.0 (0x00007f2743764000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f274354e000)
        libcrypto.so.1.0.0 => /usr/local/lib64/libcrypto.so.1.0.0 (0x00007f274316a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2742da9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f274401c000)
[root@iZ23djkgcm2Z tls]# pwd
/opt/OpenIMSCore/ser_ims/modules/tls
[root@iZ23djkgcm2Z tls]# 
[root@iZ23djkgcm2Z tls]# 
[root@iZ23djkgcm2Z tls]# locate libssl.so.1.0.0
/home/WebSS/lib/libssl.so.1.0.0
/home/authCode.gw/0315/libssl.so.1.0.0
/home/install_packet/openssl-1.0.1c/libssl.so.1.0.0
/home/wangxx/openssl-OpenSSL_1_0_1s/libssl.so.1.0.0
/usr/lib64/libssl.so.1.0.0
/usr/local/lib64/libssl.so.1.0.0
/usr/webss/lib/libssl.so.1.0.0
[root@iZ23djkgcm2Z tls]# ll /usr/local/lib64/libssl.so.1.0.0
-r-xr-xr-x 1 root root 465043 Mar 24 09:33 /usr/local/lib64/libssl.so.1.0.0
[root@iZ23djkgcm2Z tls]# ll /home/wangxx/openssl-OpenSSL_1_0_1s/libssl.so.1.0.0
-rwxr-xr-x 1 root root 465043 Mar 24 09:32 /home/wangxx/openssl-OpenSSL_1_0_1s/libssl.so.1.0.0
[root@iZ23djkgcm2Z tls]#

**Comment by winer632** [comment]
[root@iZ23djkgcm2Z wangxx]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@iZ23djkgcm2Z wangxx]# 

[root@iZ23djkgcm2Z wangxx]# tar -xzvf openssl-OpenSSL_1_0_1s.tar.gz
[root@iZ23djkgcm2Z wangxx]# cd /home/wangxx/openssl-OpenSSL_1_0_1s
[root@iZ23djkgcm2Z wangxx]# ./config shared --prefix=/usr/local --openssldir=/usr/local/openssl && make && make install

There is no symbol SSL_SESSION_hash in openssl-1.0.* however SSL_SESSION_hash exists in openssl-0.9.8*. See below.

[root@iZ23djkgcm2Z tls]# nm /home/wangxx/openssl-OpenSSL_1_0_1s/libssl.so.1.0.0 | grep SSL_SESSION_hash
[root@iZ23djkgcm2Z tls]#

[root@iZ23djkgcm2Z tls]# nm /home/wangxx/openssl-OpenSSL_0_9_8e/libssl.so.0.9.8 | grep SSL_SESSION_hash
000000000002e450 T SSL_SESSION_hash
000000000002e480 t SSL_SESSION_hash_LHASH_HASH
[root@iZ23djkgcm2Z tls]#

Is the method SSL_SESSION_hash_LHASH_HASH depricated? If so what method should I use to replace it?

The code is like this:

/**

get TLS Session Hash
@param msg - sip msg received over a TLS secure connection
@returns session_hash or 0 in case of error
/
unsigned long get_tls_session_hash(struct sip_msg msg, char str1, char *str2)
{
struct tcp_connection c;
struct tls_extra_data* extra;
SSL_SESSION *ssl_ses;
unsigned long ses_hash;

if (msg->rcv.proto != PROTO_TLS) {
ERR("get_tls_session_hash: No TLS connection !\n");
return 0;
}
c = tcpconn_get(msg->rcv.proto_reserved1, 0, 0, tls_con_lifetime);
if (c && c->type != PROTO_TLS) {
ERR("get_tls_session_hash: Connection found but is not TLS !\n");
tcpconn_put(c);
return 0;
}

if (!c || !c->extra_data) {
ERR("get_tls_session_hash: Unable to extract SSL data from TLS connection!\n");
return 0;
}
extra = (struct tls_extra_data*)c->extra_data;

ssl_ses = SSL_get_session(extra->ssl) ;
if (!ssl_ses)
{
ERR("get_tls_session_hash: No ssl session found !\n");
tcpconn_put(c);
return 0;
}
ses_hash = SSL_SESSION_hash(ssl_ses);

tcpconn_put(c);
return ses_hash;
}

**Comment by winer632** [comment]
[root@iZ23djkgcm2Z wangxx]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@iZ23djkgcm2Z wangxx]#

[root@iZ23djkgcm2Z wangxx]# tar -xzvf openssl-OpenSSL_1_0_1s.tar.gz
[root@iZ23djkgcm2Z wangxx]# cd /home/wangxx/openssl-OpenSSL_1_0_1s
[root@iZ23djkgcm2Z wangxx]# ./config shared --prefix=/usr/local --openssldir=/usr/local/openssl && make && make install

There is no symbol SSL_SESSION_hash in openssl-1.0.* however SSL_SESSION_hash exists in openssl-0.9.8*. See below.

[root@iZ23djkgcm2Z tls]# nm /home/wangxx/openssl-OpenSSL_1_0_1s/libssl.so.1.0.0 | grep SSL_SESSION_hash
[root@iZ23djkgcm2Z tls]#

[root@iZ23djkgcm2Z tls]# nm /home/wangxx/openssl-OpenSSL_0_9_8e/libssl.so.0.9.8 | grep SSL_SESSION_hash
000000000002e450 T SSL_SESSION_hash
000000000002e480 t SSL_SESSION_hash_LHASH_HASH
[root@iZ23djkgcm2Z tls]#

Is the method SSL_SESSION_hash depricated? If so what method should I use to replace it?

The code is like this:

/**

get TLS Session Hash
@param msg - sip msg received over a TLS secure connection
@returns session_hash or 0 in case of error
/
unsigned long get_tls_session_hash(struct sip_msg msg, char str1, char str2)
{
struct tcp_connection c;
struct tls_extra_data extra;
SSL_SESSION *ssl_ses;
unsigned long ses_hash;

if (msg->rcv.proto != PROTO_TLS) {
ERR("get_tls_session_hash: No TLS connection !\n");
return 0;
}
c = tcpconn_get(msg->rcv.proto_reserved1, 0, 0, tls_con_lifetime);
if (c && c->type != PROTO_TLS) {
ERR("get_tls_session_hash: Connection found but is not TLS !\n");
tcpconn_put(c);
return 0;
}

if (!c || !c->extra_data) {
ERR("get_tls_session_hash: Unable to extract SSL data from TLS connection!\n");
return 0;
}
extra = (struct tls_extra_data*)c->extra_data;

ssl_ses = SSL_get_session(extra->ssl) ;
if (!ssl_ses)
{
ERR("get_tls_session_hash: No ssl session found !\n");
tcpconn_put(c);
return 0;
}
ses_hash = SSL_SESSION_hash(ssl_ses);

tcpconn_put(c);
return ses_hash;
}

**Comment by richsalz** [comment]
You will reach more members of the community if you post to the openssl-users mailing list.  See https://mta.openssl.org

**Comment by winer632** [comment]
Thank you! I will ask in the openssl-users mailing list.

**Comment by winer632** [comment]
Finally I solved this problem by copy the declaration&implementation to \openssl-OpenSSL_1_0_1s\ssl\ssl.h & \openssl-OpenSSL_1_0_1s\ssl\ssl_lib.c and rebuild the lib.

//added by wangxx 20160325
unsigned long SSL_SESSION_hash(const SSL_SESSION *a)
{
    unsigned long l;

    l=(unsigned long)
        ((unsigned int) a->session_id[0]     )|
        ((unsigned int) a->session_id[1]<< 8L)|
        ((unsigned long)a->session_id[2]<<16L)|
        ((unsigned long)a->session_id[3]<<24L);
    return(l);
}

unsigned long SSL_SESSION_hash(const SSL_SESSION *a);//added by wangxx 20160325

**Comment by leechul** [comment]
Hi thanks for the good information

could you please let me know which line did you add in which file?
