### ISSUE TITLE
X509_cmp() is not documented

### ISSUE THREAD

**Issue by sambitdash** [openssl/openssl#9088]
`X509_cmp()` does not have any documentation nor is mapped to any generic documentation.

It's a very useful method at least for self sign cert cases.

**Comment by InfoHunter** [comment]
Hi @sambitdash , I just opened a PR adding the missing `X509_cmp` and related X509 comparison functions.

**Comment by sambitdash** [comment]
@InfoHunter thanks a lot for your quick action. While I am in agreement on most of the documentation, I have questions on the general behavior of the APIs and sought for clarification in the PR.
