### ISSUE TITLE
invoking SSL_set1_client_sigalgs() gives 'clistlen' : undeclared identifier

### ISSUE THREAD

**Issue by hareesh1git** [openssl/openssl#9092]
"# define SSL_set1_client_sigalgs(ctx, slist, slistlen) \
        SSL_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS,clistlen,(int *)(slist))"

'clistlen' used instead of 'slistlen' which is giving compilation error when invoked.

**Comment by mspncp** [comment]
Thanks for reporting this issue @hareesh1git. It seems like you are the first one to use this function: The typo has been in the macro since it was added in 3dbc46dfcd9.

https://github.com/openssl/openssl/blob/3dbc46dfcd918f7869496e34b0896dbac01d25a0/ssl/ssl.h#L1752-L1759

**Comment by mspncp** [comment]
Please take a look at #9093.
