### ISSUE TITLE
Newly added undocumented symbols

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#9095]
PR #9094 revealed that since 1.1.1 was released we have introduced 91 new public symbols that are undocumented. The complete list is:

````
# Found 4826 in util/libcrypto.num
crypto:CRYPTO_siv128_aad
crypto:CRYPTO_siv128_cleanup
crypto:CRYPTO_siv128_copy_ctx
crypto:CRYPTO_siv128_decrypt
crypto:CRYPTO_siv128_encrypt
crypto:CRYPTO_siv128_finish
crypto:CRYPTO_siv128_get_tag
crypto:CRYPTO_siv128_init
crypto:CRYPTO_siv128_new
crypto:CRYPTO_siv128_set_tag
crypto:CRYPTO_siv128_speed
crypto:ERR_load_CMP_strings
crypto:ERR_load_CRMF_strings
crypto:ERR_load_ESS_strings
crypto:ESS_SIGNING_CERT_V2_new_init
crypto:ESS_SIGNING_CERT_new_init
crypto:EVP_CIPHER_fetch
crypto:EVP_CIPHER_upref
crypto:EVP_MAC_do_all
crypto:EVP_MAC_do_all_sorted
crypto:EVP_aes_128_siv
crypto:EVP_aes_192_siv
crypto:EVP_aes_256_siv
crypto:EVP_hex2ctrl
crypto:EVP_str2ctrl
crypto:OPENSSL_LH_flush
crypto:OSSL_PARAM_construct_double
crypto:OSSL_PARAM_construct_int
crypto:OSSL_PARAM_construct_int32
crypto:OSSL_PARAM_construct_int64
crypto:OSSL_PARAM_construct_long
crypto:OSSL_PARAM_construct_size_t
crypto:OSSL_PARAM_construct_uint
crypto:OSSL_PARAM_construct_uint32
crypto:OSSL_PARAM_construct_uint64
crypto:OSSL_PARAM_construct_ulong
crypto:OSSL_PARAM_get_double
crypto:OSSL_PARAM_get_int
crypto:OSSL_PARAM_get_int32
crypto:OSSL_PARAM_get_int64
crypto:OSSL_PARAM_get_long
crypto:OSSL_PARAM_get_size_t
crypto:OSSL_PARAM_get_uint
crypto:OSSL_PARAM_get_uint32
crypto:OSSL_PARAM_get_uint64
crypto:OSSL_PARAM_get_ulong
crypto:OSSL_PARAM_set_double
crypto:OSSL_PARAM_set_int
crypto:OSSL_PARAM_set_int32
crypto:OSSL_PARAM_set_int64
crypto:OSSL_PARAM_set_long
crypto:OSSL_PARAM_set_size_t
crypto:OSSL_PARAM_set_uint
crypto:OSSL_PARAM_set_uint32
crypto:OSSL_PARAM_set_uint64
crypto:OSSL_PARAM_set_ulong
# Found 56 missing from util/libcrypto.num

# Found 506 in util/libssl.num
# Found 0 missing from util/libssl.num

# Checking macros (approximate)
include/openssl/core_numbers.h:OSSL_CORE_MAKE_FUNC
include/openssl/opensslv.h:OPENSSL_VERSION_PREREQ
include/openssl/opensslv.h:OPENSSL_MSTR_HELPER
include/openssl/opensslv.h:OPENSSL_MSTR
include/openssl/params.h:OSSL_PARAM_DEFN
include/openssl/params.h:OSSL_PARAM_int
include/openssl/params.h:OSSL_PARAM_uint
include/openssl/params.h:OSSL_PARAM_long
include/openssl/params.h:OSSL_PARAM_ulong
include/openssl/params.h:OSSL_PARAM_int32
include/openssl/params.h:OSSL_PARAM_uint32
include/openssl/params.h:OSSL_PARAM_int64
include/openssl/params.h:OSSL_PARAM_uint64
include/openssl/params.h:OSSL_PARAM_size_t
include/openssl/params.h:OSSL_PARAM_double
include/openssl/params.h:OSSL_PARAM_SIZED_int
include/openssl/params.h:OSSL_PARAM_SIZED_uint
include/openssl/params.h:OSSL_PARAM_SIZED_long
include/openssl/params.h:OSSL_PARAM_SIZED_ulong
include/openssl/params.h:OSSL_PARAM_SIZED_int32
include/openssl/params.h:OSSL_PARAM_SIZED_uint32
include/openssl/params.h:OSSL_PARAM_SIZED_int64
include/openssl/params.h:OSSL_PARAM_SIZED_uint64
include/openssl/params.h:OSSL_PARAM_SIZED_size_t
include/openssl/params.h:OSSL_PARAM_SIZED_double
include/openssl/trace.h:OSSL_TRACE_CANCEL
include/openssl/trace.h:OSSL_TRACE_ENABLED
include/openssl/trace.h:OSSL_TRACEV
include/openssl/trace.h:OSSL_TRACE
include/openssl/trace.h:OSSL_TRACE3
include/openssl/trace.h:OSSL_TRACE4
include/openssl/trace.h:OSSL_TRACE5
include/openssl/trace.h:OSSL_TRACE6
include/openssl/trace.h:OSSL_TRACE7
include/openssl/trace.h:OSSL_TRACE8
# Found 35 macros missing
````

**Comment by paulidale** [comment]
The OSSL_PARAM macros and functions are documented.
They are done generically across types, I'm not sure how this can be indicated to the checking script.

**Comment by sambitdash** [comment]
`X509_print_ex` is not documented. I was about to create a separate issue for it but guess this a generic list for all such cases.

**Comment by mspncp** [comment]
> The OSSL_PARAM macros and functions are documented.
> They are done generically across types, I'm not sure how this can be indicated to the checking script.

@paulidale That's is true, but it's not optimal yet: Currently, you need to ask for the "class name" in order to find the manual page

```
~/src/openssl$ man OSSL_PARAM
```
while a query for a method does not yield anything.

```
~/src/openssl$ man OSSL_PARAM_double
No manual entry for OSSL_PARAM_double
```
I think the method names should be added to the NAME section, too.

**Comment by paulidale** [comment]
Adding them to the NAMES section results in more "missing from SYNOPSIS" errors instead :(

**Comment by mspncp** [comment]
> Adding them to the NAMES section results in more "missing from SYNOPSIS" errors instead :(

There must be an alternative. Take a look at [D2I_X509(3)](https://www.openssl.org/docs/manmaster/man3/d2i_X509.html), its NAME section is full of explicit function names, but the SYNOPSIS section only contains templates.

cc @levitte

**Comment by mspncp** [comment]
And why not add a synopsis for all of them? Is the number of functions so large?

**Comment by richsalz** [comment]
Yes look at the manpage @mspncp suggested; and you'll need a "for comment generic" comment IIRC.  Or, add them to the synopsis.  It's one line per function.  Do not try to skimp on documenting things. :)

**Comment by richsalz** [comment]
When someone sees an OpenSSL function, they should be able to type "man that-function-name" and get the manpage.  That should be the main requirement of the documentation. There are not so many functions (compared to the d2i or exdata stuff, which are more about "classes" than number of funtions), that you cannot explicitly list and synopsize every single one of them.

**Comment by levitte** [comment]
Re d2i_X509.pod, the key line is this:

```
=for comment generic
```

**Comment by mspncp** [comment]
> Re d2i_X509.pod, the key line is this:
> 
> ```
> =for comment generic
> ```

Cool, thanks! (That's precisely why I cc'd you, because I hoped you could provide some insight.)

**Comment by mspncp** [comment]
For the curious minded, that's how it works:

https://github.com/openssl/openssl/blob/37ca204b96b036f949b8bc8389c1f8e806e1cbec/util/find-doc-nits#L182-L184

**Comment by richsalz** [comment]
Looking at the size of the PARAM API, using the 'generic' is the wrong approach.  Please see https://github.com/openssl/openssl/issues/9095#issuecomment-499874976

**Comment by mspncp** [comment]
I agree with Rich. There are not so many function that one couldn't provide a complete synopsis. (But I'd like to remark that for making `man that-function-name` find the correct manpage, an entry in the NAME section is sufficient.)

**Comment by paulidale** [comment]
I've noted all of the OSSL_PARAM_*_TYPE functions and macros specifically in the NAME and SYNOPSIS sections in PR #9114 which should clear up a lot of these.  The _TYPE versions are gone now.

**Comment by levitte** [comment]
Me, I find it overwhelming of every variant of essentially the same function is mentioned exactly in the SYNOPSIS.  NAME is sufficient (and is all that's needed for `man OSSL_PARAM_size_t` to work right)

**Comment by paulidale** [comment]
Only mentioning them in the NAME section caused even more doc-nits errors.

I'm happy to switch to the `=for comment generic` approach but the ability to "man function" will be impaired.

**Comment by mspncp** [comment]
I don't understand @paulidale. I thought the purpose of the `=for comment generic` was precisely to make it possible to name all functions in the NAME section, without having to repeate them in the SYNOPSIS section. And all functions which are listed in the NAME section should be found by `man <functionname>`.

**Comment by FdaSilvaYY** [comment]
> ```
> # Found 4826 in util/libcrypto.num
...
> crypto:ESS_SIGNING_CERT_V2_new_init
> crypto:ESS_SIGNING_CERT_new_init

...
> ```

This two methods could be made private, as they are not used in app code.

**Comment by mattcaswell** [comment]
Since #9114 went in we have an improved situation, but still 41 newly added undocumented public symbols:

````
# Found 4833 in util/libcrypto.num
crypto:CRYPTO_siv128_aad
crypto:CRYPTO_siv128_cleanup
crypto:CRYPTO_siv128_copy_ctx
crypto:CRYPTO_siv128_decrypt
crypto:CRYPTO_siv128_encrypt
crypto:CRYPTO_siv128_finish
crypto:CRYPTO_siv128_get_tag
crypto:CRYPTO_siv128_init
crypto:CRYPTO_siv128_new
crypto:CRYPTO_siv128_set_tag
crypto:CRYPTO_siv128_speed
crypto:ERR_load_CMP_strings
crypto:ERR_load_CRMF_strings
crypto:ERR_load_ESS_strings
crypto:ESS_SIGNING_CERT_V2_new_init
crypto:ESS_SIGNING_CERT_new_init
crypto:EVP_CIPHER_fetch
crypto:EVP_CIPHER_upref
crypto:EVP_MAC_do_all
crypto:EVP_MAC_do_all_sorted
crypto:EVP_aes_128_siv
crypto:EVP_aes_192_siv
crypto:EVP_aes_256_siv
crypto:EVP_hex2ctrl
crypto:EVP_str2ctrl
crypto:OPENSSL_LH_flush
# Found 26 missing from util/libcrypto.num

# Found 508 in util/libssl.num
# Found 0 missing from util/libssl.num

# Checking macros (approximate)
include/openssl/core_numbers.h:OSSL_CORE_MAKE_FUNC
include/openssl/opensslv.h:OPENSSL_VERSION_PREREQ
include/openssl/opensslv.h:OPENSSL_MSTR_HELPER
include/openssl/opensslv.h:OPENSSL_MSTR
include/openssl/params.h:OSSL_PARAM_DEFN
include/openssl/trace.h:OSSL_TRACE_CANCEL
include/openssl/trace.h:OSSL_TRACE_ENABLED
include/openssl/trace.h:OSSL_TRACEV
include/openssl/trace.h:OSSL_TRACE
include/openssl/trace.h:OSSL_TRACE3
include/openssl/trace.h:OSSL_TRACE4
include/openssl/trace.h:OSSL_TRACE5
include/openssl/trace.h:OSSL_TRACE6
include/openssl/trace.h:OSSL_TRACE7
include/openssl/trace.h:OSSL_TRACE8
# Found 15 macros missing
````

**Comment by mspncp** [comment]
I can take care of the OSSL_TRACE functions after my vacation (next week).

**Comment by richsalz** [comment]
I don't think the ```ERR_load_xxx_strings``` should be public.

Perhaps @tmshort can comment on all the SIV functions.

**Comment by levitte** [comment]
> crypto:EVP_MAC_do_all
> crypto:EVP_MAC_do_all_sorted

These are documented in #8877, I just need the time to figure out an intricate bug that's...  bugging me.

> crypto:EVP_hex2ctrl
> crypto:EVP_str2ctrl

These may actually go away when we move new APIs to be provider based.

**Comment by levitte** [comment]
@paulidale :
> The OSSL_PARAM macros and functions are documented.
> They are done generically across types, I'm not sure how this can be indicated to the checking script.

By mentioning everything from the NAME section in `util/private.num` rather than the generic name.

**Comment by levitte** [comment]
> I don't think the `ERR_load_xxx_strings` should be public.

That's a deliberate choice, so applications can load the strings they like and leave everything else alone.
Not sure if too many are loading error strings on such a fine grained level any more, though...

**Comment by tmshort** [comment]
Depends on whether or not other mode(s) functions are documented (they generally seem to not be documented):
```
crypto:CRYPTO_siv128_aad
crypto:CRYPTO_siv128_cleanup
crypto:CRYPTO_siv128_copy_ctx
crypto:CRYPTO_siv128_decrypt
crypto:CRYPTO_siv128_encrypt
crypto:CRYPTO_siv128_finish
crypto:CRYPTO_siv128_get_tag
crypto:CRYPTO_siv128_init
crypto:CRYPTO_siv128_new
crypto:CRYPTO_siv128_set_tag
crypto:CRYPTO_siv128_speed
```
These should be public, as they are the primary interface:
```
crypto:EVP_aes_128_siv
crypto:EVP_aes_192_siv
crypto:EVP_aes_256_siv
```

**Comment by mattcaswell** [comment]
> Depends on whether or not other mode(s) functions are documented (they generally seem to not be documented)

If we don't intend for end-user applications to use the functions then they should be declared internally only. If they are for end-user use then they should be documented. There shouldn't be public symbols that are documented. Historically we've been bad at documenting them - but we shouldn't be making the situation worse. So, just because other mode functions are not documented, is not a reason to not document newly added ones.

**Comment by tmshort** [comment]
> So, just because other mode functions are not documented, is not a reason to not document newly added ones.

I'm looking at it as a consistency thing. Should they even be available for public consumption, or should the older modes functions be documented as well?

**Comment by mattcaswell** [comment]
> Should they even be available for public consumption, or should the older modes functions be documented as well?

My instinct tells me that we wouldn't expect end user applications to use those functions directly, i.e. perhaps they should be internal.

**Comment by mattcaswell** [comment]
Ideally we'd make the older mode functions internal as well...but that would be a breaking change.

**Comment by tmshort** [comment]
Note that PR #9155 includes documentation for the COMP APIs and other compression code.

**Comment by richsalz** [comment]
So to fix the warnings about the SIV functions, someone needs to make a PR that puts those functions into private.num

As for the err-load-strings functions, @levitte, my point was that none of the others are documented.

**Comment by mattcaswell** [comment]
> So to fix the warnings about the SIV functions, someone needs to make a PR that puts those functions into private.num

They should be taken out of the public header files, and moved into private header files.

**Comment by mspncp** [comment]
> They should be taken out of the public header files, and moved into private header files.

Which also implies that the function names should be changed to lowercase.

**Comment by mspncp** [comment]
> I can take care of the OSSL_TRACE functions after my vacation (next week).

See pull request #9224.

**Comment by mattcaswell** [comment]
Updated list of new undocumented symbols:

````
# Found 4834 in util/libcrypto.num
crypto:CRYPTO_siv128_aad
crypto:CRYPTO_siv128_cleanup
crypto:CRYPTO_siv128_copy_ctx
crypto:CRYPTO_siv128_decrypt
crypto:CRYPTO_siv128_encrypt
crypto:CRYPTO_siv128_finish
crypto:CRYPTO_siv128_get_tag
crypto:CRYPTO_siv128_init
crypto:CRYPTO_siv128_new
crypto:CRYPTO_siv128_set_tag
crypto:CRYPTO_siv128_speed
crypto:ERR_load_CMP_strings
crypto:ERR_load_CRMF_strings
crypto:ERR_load_ESS_strings
crypto:ESS_SIGNING_CERT_V2_new_init
crypto:ESS_SIGNING_CERT_new_init
crypto:EVP_CIPHER_fetch
crypto:EVP_CIPHER_upref
crypto:EVP_MAC_do_all
crypto:EVP_MAC_do_all_sorted
crypto:EVP_aes_128_siv
crypto:EVP_aes_192_siv
crypto:EVP_aes_256_siv
crypto:EVP_hex2ctrl
crypto:EVP_str2ctrl
crypto:OPENSSL_LH_flush
# Found 26 missing from util/libcrypto.num

# Found 508 in util/libssl.num
# Found 0 missing from util/libssl.num

# Checking macros (approximate)
include/openssl/core_numbers.h:OSSL_CORE_MAKE_FUNC
include/openssl/opensslv.h:OPENSSL_VERSION_PREREQ
include/openssl/opensslv.h:OPENSSL_MSTR_HELPER
include/openssl/opensslv.h:OPENSSL_MSTR
include/openssl/params.h:OSSL_PARAM_DEFN
# Found 5 macros missing
````

**Comment by mspncp** [comment]
Looks much better now :-).

**Comment by mattcaswell** [comment]
#9232 addresses the missing `CRYPTO_siv*` functions by making them internal.

**Comment by mattcaswell** [comment]
#9233 documents `EVP_CIPHER_fetch` and `EVP_CIPHER_up_ref`.

**Comment by mattcaswell** [comment]
Remaining undocumented list is now:

````
# Found 4823 in util/libcrypto.num
crypto:ERR_load_CMP_strings
crypto:ERR_load_CRMF_strings
crypto:ERR_load_ESS_strings
crypto:ESS_SIGNING_CERT_V2_new_init
crypto:ESS_SIGNING_CERT_new_init
crypto:EVP_CIPHER_fetch
crypto:EVP_CIPHER_upref
crypto:EVP_MAC_do_all
crypto:EVP_MAC_do_all_sorted
crypto:EVP_aes_128_siv
crypto:EVP_aes_192_siv
crypto:EVP_aes_256_siv
crypto:EVP_hex2ctrl
crypto:EVP_str2ctrl
crypto:OPENSSL_LH_flush
# Found 15 missing from util/libcrypto.num

# Found 508 in util/libssl.num
# Found 0 missing from util/libssl.num

# Checking macros (approximate)
include/openssl/core_numbers.h:OSSL_CORE_MAKE_FUNC
include/openssl/opensslv.h:OPENSSL_VERSION_PREREQ
include/openssl/opensslv.h:OPENSSL_MSTR_HELPER
include/openssl/opensslv.h:OPENSSL_MSTR
include/openssl/params.h:OSSL_PARAM_DEFN
# Found 5 macros missing
````

**Comment by richsalz** [comment]
We do not document any of the ```ERR_load_XXX_strings```  -- there are 34 functions in missingcrypto.txt  So perhaps a quick PR to add those is the thing to do.

**Comment by mattcaswell** [comment]
Should new `ERR_load_XXX_strings` functions be public?

**Comment by t8m** [comment]
And if not, should the old functions be declared as deprecated in 3.0 so they are removed in 4.0?

**Comment by FdaSilvaYY** [comment]
Remaining undocumented list is now :
```
$ perl util/find-doc-nits -e -o
# Found 4688 in util/libcrypto.num
crypto:ERR_load_CMP_strings
crypto:ERR_load_CRMF_strings
crypto:ERR_load_ESS_strings
crypto:EVP_MAC_do_all
crypto:EVP_MAC_do_all_sorted
crypto:EVP_aes_128_siv
crypto:EVP_aes_192_siv
crypto:EVP_aes_256_siv
crypto:EVP_hex2ctrl
crypto:EVP_str2ctrl
crypto:OPENSSL_LH_flush
# Found 11 missing from util/libcrypto.num

# Found 508 in util/libssl.num
# Found 0 missing from util/libssl.num

# Checking macros (approximate)
include/openssl/core_numbers.h:OSSL_CORE_MAKE_FUNC
include/openssl/opensslv.h:OPENSSL_VERSION_PREREQ
include/openssl/opensslv.h:OPENSSL_MSTR_HELPER
include/openssl/opensslv.h:OPENSSL_MSTR
include/openssl/params.h:OSSL_PARAM_DEFN
# Found 5 macros missing
```

**Comment by mattcaswell** [comment]
Closing this in favour of #13192
