### ISSUE TITLE
SSL_check_chain() broken during cert_cb by PR 7257

### ISSUE THREAD

**Issue by tmshort** [openssl/openssl#9099]
PR #7257
This appears to break `SSL_check_chain()` usage as described in the documentation:

>SSL_check_chain() must be called in servers after a client hello message
>or in clients after a certificate request message. It will typically be
>called in the certificate callback.

...

>The validity of a chain is determined by checking if it matches a
>supported signature algorithm, supported curves and in the case of client
>authentication certificate types and issuer names.
>
>Since the supported signature algorithms extension is only used in TLS
>1.2, TLS 1.3 and DTLS 1.2 the results for earlier versions of TLS and DTLS
>may not be very useful. Applications may wish to specify a different
>"legacy" chain for earlier versions of TLS or DTLS.

Since the sigalgs are no longer available during the `cert_cb`, this prevents SSL_check_chain() from working properly.

**Comment by tmshort** [comment]
Note that `s_cb.c` uses `SSL_check_chain()` in the `set_cert_cb()`. This is used with the OPT_X_CASES (e.g. -xcert)
```
    while (exc != NULL) {
        i++;
        rv = SSL_check_chain(ssl, exc->cert, exc->key, exc->chain);
        BIO_printf(bio_err, "Checking cert chain %d:\nSubject: ", i);
        X509_NAME_print_ex(bio_err, X509_get_subject_name(exc->cert), 0,
                           get_nameopt());
        BIO_puts(bio_err, "\n");
        print_chain_flags(ssl, rv);
        if (rv & CERT_PKEY_VALID) {
```

**Comment by tmshort** [comment]
Closing this for the time being, as it may be a red herring in our case.

**Comment by tmshort** [comment]
`SSL_check_chain()` calls `tls1_check_chain()` calls `tls1_check_sig_alg()` which looks at `s->cert->shared_sigalgs` which is set by tls1_set_server_sigalgs() which has moved to after the cert_cb. So, when you are in the cert_cb, `tls1_check_chain()` won't ever set the `CERT_PKEY_EE_SIGNATURE` bit (for TLSv1.2+) since `tls1_set_server_sigalgs()` always returns 0. Which means that CERT_PKEY_VALID won't be set.

**Comment by tmshort** [comment]
In 1.1.1, the following worked with `openssl s_client` (connection was established):
`apps/openssl s_server -xcert apps/server.pem -xkey apps/server.pem -nocert`
In 1.1.1a, it fails:
```
Using default temp DH parameters
ACCEPT
Checking cert chain 1:
Subject: C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
	Overall Validity: NOT OK
	Sign with EE key: NOT OK
	EE signature: NOT OK
	CA signature: OK
	EE key parameters: OK
	CA key parameters: OK
	Explicitly sign with EE key: NOT OK
	Issuer Name: OK
	Certificate Type: OK
	Suite B: not tested
ERROR
140562452743936:error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:2634:
shutting down SSL
CONNECTION CLOSED
```

**Comment by kaduk** [comment]
It seems that the heart of this is that we had to store the shared_sigalgs in the CERT object rather than in the SSL directly, since at the time the ssl_st was not opaque.  This led to a need to shoehorn it into the CERT and do exception handling whenever ```s->cert``` is copied or replaced, such as in ```SSL_set_SSL_CTX()``` (which uses ```ssl_cert_dup()```, which in turn always sets the shared sigalgs to NULL).
Since ssl_st is now opaque, perhaps it's most appropriate to move the shared_sigalgs fields into struct ssl_st and put the tls1_set_server_sigalgs() call back at the end of tls_early_post_process_client_hello()  so that they'll be available in the cert_cb.
