### ISSUE TITLE
TLSv12 Client is sending RSA certificate even when it doesn't have digitalSignature bit in keyUsage extension. But RFC5246 section-7.4.6 says it's MUST condition for client to send RSA certificate with digitalSignature bit set in keyUsage extension.

### ISSUE THREAD

**Issue by hareesh-d** [openssl/openssl#9113]
https://tools.ietf.org/html/rfc5246#section-7.4.6

 Client Cert. Type   Certificate Key Type

      rsa_sign            RSA public key; the certificate **MUST** allow the
                          key to be used for signing with the signature
                          scheme and hash algorithm that will be
                          employed in the certificate verify message.

1) Though server is rejecting such certificates, may i know why client sends such certificates even when there is MUST condition for this point. Should client send empty certificate message instead of sending wrong one ? Client has the provision of sending empty certificate list when it don't have a certificate according to certificate_request. 

2) and also client is not checking the certificate_types requested in certificate_message and also server not validating if the response is according to the type requested.  Consider Server requesting only DSA certificate. Client selecting and sending RSA certificate. Server accepting it.

**Comment by hareesh1git** [comment]
Can someone please give few details to understand this behavior. Thanks.

**Comment by karlo1941** [comment]
many don't care about the standard. sometimes certificates can be found without any key usage. and they work.

**Comment by hareesh-d** [comment]
> many don't care about the standard. sometimes certificates can be found without any key usage. and they work.

In many cases, extension is present with wrong data and extension itself is not present are treated as 2 different cases. When extension itself is not present, usually standards says like treat it as success case. But extension is present and contains wrong data should be treated like failure case.

I'm yet to find out if extension is not present is also a success case in this particular behavior also.

**Comment by mattcaswell** [comment]
There is no reason for the client to enforce this itself. OpenSSL will send any certificate that has been configured and does not attempt to verify it before sending it. It is the server's responsibility to determine whether it considers the certificate as suitable for use or not, using whatever criteria it sees fit.

I don't see an issue for OpenSSL to fix here.
