### ISSUE TITLE
macOS | library that static links openssl still loaded in process memory after calling dlclose

### ISSUE THREAD

**Issue by gabrieltarpian25** [openssl/openssl#9122]
Hello,

**I have the following use case:**

- two dynamic libraries named libwaapi.dylib and libwautils.dylib

- libwaapi.dylib has implicit-dynamic linking to libwautils.dylib

- libwautils.dylib has static linking to openssl (libcrypto.a and libssl.a)

**Below is the complete workflow of the issue:**

1. void* v4_handle = (void*)dlopen( "libwaapi.dylib", RTLD_NOW )
    At this time, the OS loads libwautils.dylib and libwaapi.dylib in the process memory.
2. function exposed by libwaapi.dylib is called, which uses openssl functions from libwautils.dylib
3. dlclose(v4_handle) is called. 
    After this call, the OS unloads only libwaapi.dylib from the process memory.
    libwautils.dylib is still loaded in the process memory.

**We found a temporary workaround for this due to high priority of the issue ** but this is not sustainable in the long-term. 

void * handle = (void*)dlopen( "libwautils.dylib", RTLD_NOLOAD );
if( handle != nullptr )
{
        dlclose( handle );
        dlclose( handle );
}

We are getting the handle to libwautils.dylib which is still loaded in the process memory.
Then we are calling dlclose twice, the first one for the dlopen operation we used with RTLD_NOLOAD flag, and the second one for the handle that existed in the process memory after Step 3 from the workflow. 

**Additional info about the issue:**

- The issue is reproducible with openssl 1_1_0x and 1_1_1x.

- With openssl 1_0_2x, after Step 3 is performed, both libwaapi and libwautils libraries are successfully unloaded from the process memory.

- We noticed this issue when we upgraded from 1.0.2x to 1.1.1x. 

- We tested on macOS Sierra 10.12 and 10.12.6. The issue is reproducible on both.

- We performed a lot of additional tests and all the findings are taking us to openssl

Please let me know if you need additional information.

Thank you in advance for your help!

**Comment by mattcaswell** [comment]
Compile OpenSSL with the "no-pinshared" option (available from OpenSSL 1.1.1b and above).

See the documentation here:
https://github.com/openssl/openssl/blob/5ded1ca6dade13e093086573f4cebe400bff9f4d/INSTALL#L446-L462

**Comment by gabrieltarpian25** [comment]
Thank you @mattcaswell , it is working!
