### ISSUE TITLE
openssl 1.1.1a  brainpool Curve

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#9124]
Whether openssl 1.1.1a supports
brainpoolP256r1
brainpoolP320r1
brainpoolP384r1
brainpoolP512r1
Curve25519
Curve448
How should I test if I support it? My local test has been unsuccessful in building the chain.

**Comment by bbbrumley** [comment]
> Whether openssl 1.1.1a supports

The answer is yes. But ofc it depends on your build options.

What have you tried?

**Comment by Mengliuxx** [comment]
1.openssl s_server -accept 8445 -cert server_cert.pem -key server_key.pem  -named_curve brainpoolP320r1  -cipher  ECDHE-ECDSA-AES128-SHA  this is fail ,but when  -named_curve is brainpoolP256r1 or brainpoolP384r1  or  brainpoolP512r1 is ok ,  The test certificate and curve are corresponding ,I want to know if brainpoolP320r1 special?   

2. Curve25519 Curve448 is not in list of openssl ecparam -list_curves ? how to test it

**Comment by bbbrumley** [comment]
brainpoolP320r1 does not have a TLS codepoint at the standardization level. So that is why `s_server` is throwing an error.

Curve 22519 and Curve448 are not "curves" in the OpenSSL sense. So that is why they are not in `openssl ecparam -list_curves`. I'm not sure how to test it for TLS -- hopefully someone else can chime in.

**Comment by Mengliuxx** [comment]
so If i want to support brainpoolP320r1, i need to modify the openssl code. Is that right ?

**Comment by bbbrumley** [comment]
> so If i want to support brainpoolP320r1, i need to modify the openssl code. Is that right ?

It depends. Where do you want support for brainpoolP320r1? In what application?

**Comment by Mengliuxx** [comment]
brainpoolP320r1 does not have a TLS codepoint at the standardization level . Can I understand Openssl does not support brainpoolP320r1 ? or How should I understand?

**Comment by bbbrumley** [comment]
OpenSSL definitely supports brainpoolP320r1. You can use brainpoolP320r1 in OpenSSL like any other curve. Sign stuff. Generate certificates. Use it generically at the `EVP` level.

But TLS, as a standard, does not support brainpoolP320r1. So it doesn't matter what OpenSSL or any other TLS library does -- there is no magic number in some TLS message field reserved for brainpoolP320r1. So you cannot use it for TLS, in OpenSSL or any other library.

**Comment by kroeckx** [comment]
Also note that we do not support any of the brainpool curves with TLS 1.3, because the TLS 1.3 RFC says they're not allowed.

**Comment by bernd-edlinger** [comment]
FYI @Mengliuxx I re-activated an old PR from mine, which allows brainpool curves to
be used with TLS 1.3
it is 1.1.1-only but might be interesting for you: #11782 

If you want the client key share extension to use brainpool, that is possible,
but only if the server allows that, and the client is unable to know in advance.

so I am not sure if the code is completely error-free, but it seems still to be working,
after almost 2 years of hibernation :-)
