### ISSUE TITLE
For which versions of OpenSSL are missing NULL checks on free considered to be bugs?

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#9128]
I know for 1.1.1 and I assume 1.1.0 it's a bug, but is it also a bug for 1.0.2? If so, how far back was OpenSSL always checking for NULL before free assumed to be the case?

Sorry this isn't quite a bug report, but this question will enable bug reporting.

**Comment by mattcaswell** [comment]
IIRC we introduced NULL checks as part of 1.1.0, and so they should exist throughout 1.1.0 and 1.1.1. I also think we backported them to 1.0.2 at the same time to ease backporting other patches. Both 1.1.0 and 1.0.2 are in security-fix only mode so I wouldn't consider missing NULL checks in either of those branches as something we would fix.

**Comment by richsalz** [comment]
Yes, I backported the NULL-free code to 1.0.2 in commit f34b095fab1569d093b639bfcc9a77d6020148ff  The brevity of that comment implies to me that other functions already checked.

**Comment by mlindner** [comment]
Thanks! Closing this.
