### ISSUE TITLE
KDF api cleanup

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#9139]
The KDF API is a bit messy to use, a few changes that would make it more ergonomic:

  - All kdfs with a variable output size should permit the `EVP_KDF_CTRL_SET_MAC_SIZE` control
  - Proliferation of "info" controls: HKDF should support `SET_INFO`. kdfs should either *all* support `RESET_INFO` and `ADD_INFO`, or none of them should
  - The SSH KDF's `XCGHASH` and `SESSION_ID` sound a lot like salt/info. Could they reuse the same options?

**Comment by slontis** [comment]
Thanks for looking at the interface..
- Which ones are missing the EVP_KDF_CTRL_SET_MAC_SIZE control?
- Adding SET_INFO to hkdf wouldnt be a issue, but removing the reset/add_info is more problematic since there is still a pkey interface that uses that accesses that functionality. Backwards compatibility always makes things nastier than they should be :)
- For the SSH KDF's I dont agree with changing these names.. They are using the names referred to in the relevant RFC. I dont think it is an issue as they are documented.

**Comment by slontis** [comment]
@davidmakepeace

**Comment by daurnimator** [comment]
> For the SSH KDF's I dont agree with changing these names.. They are using the names referred to in the relevant RFC. I dont think it is an issue as they are documented.

I would be okay if there were aliases for SET_INFO/SET_SALT; but I think its silly that I need to e.g. recompile my application to support new KDFs, rather than just allowing a user to provide the KDF name and parameters as key/value pairs.

**Comment by slontis** [comment]
Any opinions @simo5?

**Comment by slontis** [comment]
> but I think its silly that I need to e.g. recompile my application to support new KDFs, rather than just allowing a user to provide the KDF name and parameters as key/value pairs.

I dont quite understand what you mean. Not all KDF's are inter-changeable.
Are you talking about the string names as opposed to the control id's?

**Comment by daurnimator** [comment]
>  Are you talking about the string names as opposed to the control id's?

I was talking about the control IDs. See https://github.com/wahern/luaossl/blob/61b14ef7d033da46c0e5cbb64f1c060e8588c3a4/src/openssl.c#L12054-L12173 for how I've ended up using the API.

**Comment by paulidale** [comment]
This sounds like the `EVP_KDF_ctrl_str` API might be relevant?
Although the arguments need to be strings.

There will be a new API base on OSSL_PARAM which should be closer to what is desired (arguments using string names and values using native types).

**Comment by daurnimator** [comment]
> This sounds like the `EVP_KDF_ctrl_str` API might be relevant?

Not really, as I still need to know the types of the values; and the list of valid string keys.
One thing that might help is a function that returns a list of the supported keys (and value types) for a given KDF.

**Comment by slontis** [comment]
Would it be possible to just convert all values to strings? Your name is already a string. then the ctrl_str() could be used??

**Comment by levitte** [comment]
May I suggest looking at #8877 to see how to solve the ctrl vs param problem? In particular, the stuff in that PR's `crypto/evp/evp_util.c` might prove useful.

**Comment by slontis** [comment]
If this MAC PR gets approved then the KDF API will also be changed to be similiar.

**Comment by paulidale** [comment]
I expect that the KDF API will switch in the same manner since it's never been public either.

I don't think we've defined anything that requests a list of legitimate parameters from an algorithm implementation.  I think we should.  A query and a free function will be necessary, perhaps a set as well.  I'm thinking a call to query the parameters an algorithm takes and the parameter array it returns can be passed back to it after filling in (rather than allocating a new array).

I'm part way through some more helper code that might assist in this...

**Comment by levitte** [comment]
> I don't think we've defined anything that requests a list of legitimate parameters from an algorithm implementation.

We have talked about it, loosely. There exists code that returns an OSSL_ITEM array, #8877 uses a constant OSSL_PARAM array instead.

> I'm thinking a call to query the parameters an algorithm takes and the parameter array it returns can be passed back to it after filling in (rather than allocating a new array).

So a reverse get_params type function? I'm not too keen on that, because the code filling in values will not necessarily fill them all in, and I don't see why a function that is essentially there to help discovery should have to re-generate the array every time.

**Comment by simo5** [comment]
@slontis I do not see it useful to rename or alias parameters for the SSHKDF, I think it would only be confusing as someone reading the relevant RFC would have to figure out what becomes what, and nobody else would be helped by using SALT/INFO as you still need to add the other parameters (ie TYPE) to be able to use SSHKDF, so it won't work with just a SALT/INFO combination anyway.

@paulidale not that this should stop any change as required, however we have backported the KDF API to 1.1.1 in RHEL and it would be nice if changes were backwards compatible, this is just a data point to consider, not a request to keep officially unreleased APIs from changing.

**Comment by paulidale** [comment]
More a reverse `set_params` function (unless I've confused myself yet again).

"Give me the list of params I can set?" doesn't sound like an unreasonable question to ask of a provider.  Returning them as a OSSL_PARAM array that can be filled in and passed to set_params also seems reasonable -- the list of names and their types needs to be communicated.

Draft of first helper code in #9246

**Comment by richsalz** [comment]
> "Give me the list of params I can set?" doesn't sound like an unreasonable question to ask of a provider.

It actually sounds like a very SILLY question to ask.  Either the caller will know what is needed and pass that in, or it will pass in whatever it has and trust the provider to retrieve what it needs.  Since semantic information is not provided (not possible really) this seems kinda pointless.

I worry that you're slowly backing into making everything possible via PARAM stuff, which wasn't the original intent.

**Comment by paulidale** [comment]
Not having this makes agility really difficult.  With it, a file with name/value pairs could be loaded into a param array without knowing anything about what the parameters actually do...

**Comment by paulidale** [comment]
I've no intention of making everything use params.  Mostly, I see them as a replacement for the ctl calls and for some communication with providers.

**Comment by levitte** [comment]
> > "Give me the list of params I can set?" doesn't sound like an unreasonable question to ask of a provider.
> 
> It actually sounds like a very SILLY question to ask.  Either the caller will know what is needed and pass that in, or it will pass in whatever it has and trust the provider to retrieve what it needs.  Since semantic information is not provided (not possible really) this seems kinda pointless.
> 
> I worry that you're slowly backing into making everything possible via PARAM stuff, which wasn't the original intent.

If you look at `openssl genpkey` and `openssl pkeyutl`, you'll see that they handle all sorts of algorithm dependent options. Those are currently transmitted with ctrl functions, but could as well be transmitted with params. Given param keywords, types and possible maximum sizes, it's not at all difficult to have code that translate text options into params. Again, see `crypto/evp_util.c` in #8877.

**Comment by paulidale** [comment]
@levitte, exactly.

@daurnimator's `luaossl` code needs to know what names are allowed and, preferably, what types are associated with each name.  Size and range limits would be a bonus but difficult to include in the OSSL_PARAM structure.

**Comment by levitte** [comment]
Maximum size is easy

**Comment by levitte** [comment]
Side note: I've some thoughts on creating a `openssl provider` command that can be used for discovery, just like `openssl engine`.

**Comment by richsalz** [comment]
Yes, a human typing things on the commandline provides out-of-band semantics about what is needed.  I don't see how #9246 is required. I can see how it makes it easier to detect errors earlier, in the app perhaps, but it would still be up to the provider to do semantic checking (e.g., imagine mutually-exclusive parameters). So you get *some* gain for complexity, and I think OpenSSL is already too complex.

**Comment by daurnimator** [comment]
> Yes, a human typing things on the commandline provides out-of-band semantics about what is needed. I don't see how #9246 is required.

The key thing is that it allows a user to use new KDFs after a openssl release without requiring a luaossl release to add support for the new parameters.

**Comment by levitte** [comment]
@richsalz does raise a good point, though. #9246 doesn't help dealing when the amount or types of parameters aren't known in compile time.

**Comment by paulidale** [comment]
> doesn't help when the amount or types of parameters aren't known in compile time.

One side must know about them at compile time.  E.g. load a provider which includes a brand new KDF which takes some custom argument.  The KDF app doesn't know about it, libcrypto doesn't know either but they can query the provider about it and make a (reasonable) attempt passing values.  How does the provider return this information? #9246 provides a way for param arrays to escape the scope where they are declared while remaining thread safe.

**Comment by richsalz** [comment]
If libcrypto doesn't know about it, how can it make a reasonable attempt at passing values?  I could understand why the KDF app might do it, because there is a human involved and they can type
```
-arg z:float:6.99
```
or similar to get a runtime dynamic arg passed into the KDF function.  But what hope does libcrypto have?

And for the KDF app case, #9246 does not seem useful.

**Comment by paulidale** [comment]
You're right, I don't think libcrypto has a use.

It's not just the KDF (where the `-kdfopt` argument could change to include type).  Pkeyutl and genpkey both take the `-pkeyopt` argument which takes `name:value` with no type information.  How to push that into a provider without knowing the type information?

Stick with the ctrl_str and not use params???

**Comment by richsalz** [comment]
> Stick with the ctrl_str and not use params?

That's what we have now.  Seems to me that not increasing complexity and API surface, but rather use the existing mechanism now is the least-risky thing to do.  In a future release we could do more.

**Comment by levitte** [comment]
> It's not just the KDF (where the -kdfopt argument could change to include type). Pkeyutl and genpkey both take the -pkeyopt argument which takes name:value with no type information. How to push that into a provider without knowing the type information?
> 
> Stick with the ctrl_str and not use params???

It's perfectly possible to have the provider return information about parameters it accepts. With that, it's up to the caller to pass down an OSSL_PARAM array that contains appropriately formed data computed from `-pkeyopt` et al.

*There is a proposal for how to handle exactly this in #8877*

**Comment by paulidale** [comment]
It makes more sense (to me) to have the _get_param_types function return an array of OSSL_PARAM that can immediately be populated by the caller and passed back.  The OSSL_ITEM structure is effectively adding a layer of indirection.

OSSL_ITEM is only used for this purpose, so it might even be possible to remove this public structure.

Still, I think we disagree.  What do other people prefer?

**Comment by levitte** [comment]
#8877 proposes to use a constant OSSL_PARAM array as descriptor rather than OSSL_ITEM.

Having an array that the caller fills in has several problems, one being how the receiving end (the provider) will know what params were actually filled in, another one being thread safety.

**Comment by paulidale** [comment]
I agree that returning a const OSSL_PARAM array solves the exposing the OSSL_ITEM problem.  The caller still has to copy the items of interest to a new OSSL_PARAM array.

Dynamically allocating the returned array solves the thread safety, which is part of the reason for #9246

As for knowing which params were filled in, I think that that can be dealt with by either adding a flags field or stealing some bits from the type.  This will be required for #9254 (to indicate allocated) where my intention is that some of the OSSL_PARAM array elements can be constructed and some allocated.  Modifying the OSSL_PARAM_set_ calls to flag that the value has changed should automate most of this.

Another alternative (which I'd not thought of before your comment) would be to let the caller clone specific elements of the const OSSL_PARAM array descriptor.  I.e. have a call which takes an OSSL_PARAM array and an array of names, it returns an allocated array of those elements from the former which are named in the latter.  This feels like it should be workable as a middle ground compromise.

**Comment by levitte** [comment]
> I agree that returning a const OSSL_PARAM array solves the exposing the OSSL_ITEM problem.

(that's the smallest problem, and OSSL_ITEM may still be useful elsewhere) 

> The caller still has to copy the items of interest to a new OSSL_PARAM array.

Do they? *Have* to, I mean? I an see copying the pointer to a name and the data type, and sometimes the size...

**Comment by paulidale** [comment]
> I an see copying the pointer to a name and the data type, and sometimes the size...

These amount to over half the structure....

Pauli

**Comment by levitte** [comment]
Uhmm... So? It's two register. It's doesn't force the provider to allocate a lot of memory, potentially partially (or entirely, if say `openssl provider` gets a very verbose mode that displays all parameters a provider, *which is a feature I'm planning on) without need.

**Comment by levitte** [comment]
Since all KDFs have now moved to the providers, and the public API has been modified accordingly, it's unclear to me if this issue is still current.  If not, it should be closed.

**Comment by paulidale** [comment]
It seems like all the concerns have been addressed.  The names of all the parameters are available as are their expected types.  A new KDF should no longer require the upstream to rebuild.

I'll close this, but if I am mistaken please reopen @daurnimator.
