### ISSUE TITLE
Linking Error while linking SSL with application

### ISSUE THREAD

**Issue by glorandrew** [openssl/openssl#9142]
I am trying to link OpenSSL libraries libcrypto.lib and libssl.lib with my application.
I am using opensslv 1.1.1c
And I am getting below linking errors:

qlib.lib(qcksum.obj) : error LNK2019: unresolved external symbol _EVP_MD_CTX_new@0 referenced in function __qcksum_init_ctx@16
qlib.lib(qcksum.obj) : error LNK2019: unresolved external symbol _EVP_MD_CTX_reset@4 referenced in function __qcksum_init_ctx@16
qlib.lib(qcksum.obj) : error LNK2019: unresolved external symbol _EVP_MD_CTX_free@4 referenced in function __qcksum_compute_file@36
qlib.lib(qcksum.obj) : error LNK2019: unresolved external symbol _EVP_DigestInit_ex@12 referenced in function __qcksum_init_ctx@16
qlib.lib(qcksum.obj) : error LNK2019: unresolved external symbol _EVP_DigestUpdate@12 referenced in function __qcksum_compute_file@36
qlib.lib(qcksum.obj) : error LNK2019: unresolved external symbol _EVP_DigestFinal@12 referenced in function __qcksum_finish_ctx@28
qlib.lib(qcksum.obj) : error LNK2019: unresolved external symbol _EVP_md5@0 referenced in function __qcksum_init_ctx@16
sgn.lib(sgn.obj) : error LNK2019: unresolved external symbol _CRYPTO_set_mem_functions@12 referenced in function _sgn_lib_init_1@0
sgn.lib(sgn.obj) : error LNK2019: unresolved external symbol _CRYPTO_malloc@12 referenced in function _sgn_lib_init_1@0
sgn.lib(sgn.obj) : error LNK2019: unresolved external symbol _CRYPTO_free@12 referenced in function _sgn_lib_fini@0
sgn.lib(sgn_x509.obj) : error LNK2001: unresolved external symbol _CRYPTO_free@12
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _OPENSSL_sk_num@4 referenced in function _sgn_verify_signer_info@40
sgn.lib(sgn_x509.obj) : error LNK2001: unresolved external symbol _OPENSSL_sk_num@4
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _OPENSSL_sk_value@8 referenced in function _sgn_verify_signer_info@40
sgn.lib(sgn_x509.obj) : error LNK2001: unresolved external symbol _OPENSSL_sk_value@8
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _OBJ_obj2nid@4 referenced in function _sgn_verify@28
sgn.lib(sgn_x509.obj) : error LNK2001: unresolved external symbol _OBJ_obj2nid@4
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _EVP_PKEY_get1_RSA@4 referenced in function _sgn_verify_signed_buffer@24
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _EVP_PKEY_free@4 referenced in function _sgn_verify_signed_buffer@24
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _RSA_verify@24 referenced in function _sgn_verify_signed_buffer@24
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _PKCS7_free@4 referenced in function _sgn_verify@28
sgn.lib(sgn_x509.obj) : error LNK2001: unresolved external symbol _PKCS7_free@4
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _X509_free@4 referenced in function _sgn_match_cert_against_store@16
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _X509_get_pubkey@4 referenced in function _sgn_verify_signed_buffer@24
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _X509_cmp@8 referenced in function _sgn_match_cert_against_store@16
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _X509_find_by_issuer_and_serial@12 referenced in function _sgn_verify_signer_info@40
sgn.lib(sgn_x509.obj) : error LNK2001: unresolved external symbol _X509_find_by_issuer_and_serial@12
sgn.lib(sgn_vfy.obj) : error LNK2019: unresolved external symbol _ERR_remove_state@4 referenced in function _sgn_verify@28
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _BIO_new@4 referenced in function _sgn_get_x509_buffer@8
sgn.lib(sgn_pkcs7.obj) : error LNK2001: unresolved external symbol _BIO_new@4
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _BIO_free@4 referenced in function _sgn_get_x509_buffer@8
sgn.lib(sgn_pkcs7.obj) : error LNK2001: unresolved external symbol _BIO_free@4
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _BIO_ctrl@16 referenced in function _sgn_get_x509_buffer@8
sgn.lib(sgn_pkcs7.obj) : error LNK2001: unresolved external symbol _BIO_ctrl@16
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _BIO_s_mem@0 referenced in function _sgn_get_x509_buffer@8
sgn.lib(sgn_pkcs7.obj) : error LNK2001: unresolved external symbol _BIO_s_mem@0
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _X509_NAME_oneline@12 referenced in function _sgn_X509_get_issuer_name@4
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _X509_get_serialNumber@4 referenced in function _sgn_X509_get_qsha_issuer_serial@16
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _X509_get_issuer_name@4 referenced in function _sgn_X509_get_issuer_name@4
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _X509_get_subject_name@4 referenced in function _sgn_X509_get_subject_name@4
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _PEM_read_bio_X509@16 referenced in function _sgn_load_cert@4
sgn.lib(sgn_x509.obj) : error LNK2019: unresolved external symbol _PEM_write_bio_X509@8 referenced in function _sgn_get_x509_buffer@8
sgn.lib(sgn_pkcs7.obj) : error LNK2019: unresolved external symbol _d2i_PKCS7_bio@8 referenced in function _sgn_decrypt_certificate@12
OBJ_WIN8_X86_REL/swin.sys : fatal error LNK1120: 33 unresolved externals

I have included libssl.lib and libcrypto.lib oth in my makefiles.

Could you let me know If I am missing anything here?

**Comment by levitte** [comment]
I this still an issue?
