### ISSUE TITLE
build.info for FIPS provider is confusing

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9150]
As mentioned in https://github.com/openssl/openssl/pull/8886...

Why does the FIPS provider have its build stuff in ```crypto/build.info``` and not in ```providers/fips/build.info```?  Especially since the latter already exists, and seems to have only a single (mysterious to me :) line in it.

If we want the FIPS provider to be a model of how others can build their own crypto providers, seems like we should fix this.

**Comment by levitte** [comment]
You forget `providers/build.info`

As for the mentions in the diverse `build.info` under `crypto`, that's only for mentioning the sources that go in, which we do where said source is, just as we do for the libraries.

Of course, we could move source away from the `crypto` tree, and we actually do, but source that is shared with the main libraries stay in place.

Does it make more sense now?

**Comment by richsalz** [comment]
Saying "the sources are these..." in one file and "how to compile them" in another file is still a bad idea, IMO.

I appreciate the explanation, but I still think this is a bug.

I knew about providers/build.info, but that seems okay since it specifies what providers to build.  Not the same thing as FIPS provider defined in two separate build.info files.

**Comment by levitte** [comment]
Would it help if this line was repeated in `providers/fips/build.info`?

```
MODULES=../fips
```

We do that as a habit for the libraries (which *is* redundant, BTW, but does clarify), so it would make sense to do that with the fips module too (and the lagacy module as well, for that matter).

**Comment by richsalz** [comment]
I think it's fundamentally broken the way it is handled now and trimming up the edges doesn't fix the bug. But if the OMC disagrees, so be it.

**Comment by levitte** [comment]
So why don't you tell us how you would specify it?

**Comment by levitte** [comment]
> If we want the FIPS provider to be a model of how others can build their own crypto providers, seems like we should fix this.

I would most certainly *not* have the FIPS provider be a model for others to follow.  Because it shares source with libcrypto and the default provider, it's much more complex in source than I'd expect any average provider module to be.

Please remember that shared source between the default and the FIPS provider is a stated goal.  There's no stated goal that the FIPS module should be an example for others to follow (although I will agree that some things could be more elegant, and I'm sure we'll have one or two refactoring fests before 3.0 is released).

**Comment by levitte** [comment]
As for models for others to follow, I could see a rewrite of some of the modules in `engines`...  or perhaps a replacement of `e_capi.c` that uses the CNG API.  Things like that...

**Comment by mattcaswell** [comment]
> If we want the FIPS provider to be a model of how others can build their own crypto providers, seems like we should fix this.

build.info seems to have zero relevance to external crypto providers since its very much tied to the OpenSSL build system. Any external provider author is unlikely to be integrating into that.

**Comment by richsalz** [comment]
I think all information about the FIPS module build process should be in providers/fips/build.info

**Comment by richsalz** [comment]
Stand-alone external providers will not use the openssl build process, but there are many (oracle, redhat, and no doubt others) who will fork the code and add their own modules.

**Comment by mattcaswell** [comment]
> I think all information about the FIPS module build process should be in providers/fips/build.info

I actually strongly disagree. I much prefer the model of keeping all build information for a set of sources in the same directory as those sources.

**Comment by levitte** [comment]
@richsalz, are you thinking the same way re the default provider and the legacy provider? If not, why not?

**Comment by richsalz** [comment]
If the default and legacy provider are pulled into separate subdirectories, then yes the build.info in that subdirectory should have everything needed to build the provider. Am I being clear?

**Comment by levitte** [comment]
> ... are pulled into separate subdirectories

Not sure what you mean by that.  Their sources are still spread around both under `providers/` and under `crypto/`, so what exactly is pulled?  BTW, both the fips and the legacy modules end up in `providers`, not in `providers/fips/` and `providers/legacy/`.

**Comment by richsalz** [comment]
I am not clear on the details of how the legacy and default providers are built.  The key point I am trying to make is one build.info file per provider. If the default bundles that into crypto/build.info, that's okay I suppose.

Maybe part of the real solution is to split crypto into new additional directories, and that the "common services" (as described in the architecture docs, also called the "core" in some of the code) is one thing, and each provider is a separate thing. Shared code goes into providers/common or some such.

But again the key point is: one build.info file for each provider. I know @mattcaswell disagrees and he likes the multiple FIPS build.info scheme. But you guys get to decide, not me.

**Comment by levitte** [comment]
I disagree too, FYI.  One tangible reason is that with the current scheme, it's fairly easy to see exactly what sources are common to several product files (libraries and modules), and even more so with #9144.  With the same information moved to each provider's build.info, it's less visible.

Please *do* keep in mind that quite a lot of code is shared between libcrypto and the FIPS provider.  It's not self evident with what you just said if such code belongs in `crypto/` or in `providers/common/`.  Do note that we are moving code that's strictly provider only to `providers/common/` or `providers/default/`.  That's exclusive code that doesn't have a public API (such as newer algorithms that only presented a EVP backend).

**Comment by richsalz** [comment]
I think #10088 cleaned this up as much as can be expected given the current views.
