### ISSUE TITLE
Unable to compile OpenSSL with PGI compilers

### ISSUE THREAD

**Issue by adamjstewart** [openssl/openssl#916]
I'm trying to compile the latest OpenSSL 1.0.2g with the latest PGI 16.3 compilers. I am on CentOS 6 x86_64. Unfortunately I can't get it to work. Here is what I've tried so far:
```bash
CC=pgcc ./config zlib no-krb5 shared > config.log 2>&1
make depend                          > config.log 2>&1
make                                 > config.log 2>&1
```
This produces the error message:
```
pgcc-Error-Unknown switch: -Wall
```
See the full [config.log](https://github.com/openssl/openssl/files/188708/config.txt) file for details.

I next tried manually editing the Makefile to remove `-Wall`. This produces the error message:
```
PGC-S-0043-Redefinition of symbol, l (../md32_common.h: 304)
```
See the full [config.log](https://github.com/openssl/openssl/files/188709/config-Wall.txt) file for details.

Am I doing something wrong here, or are the PGI compilers simply not supported? Any idea how much work it would be to add PGI support?

**Comment by dot-asm** [comment]
> are the PGI compilers simply not supported?

Correct, they are not supported.

> Any idea how much work it would be to add PGI support?

What prevents you from compiling OpenSSL with gcc and linking it with your code compiled with PGI? You are likely to be better off inter-linking...

As for error itself. It makes no sense. And given that it does work with dozen other compilers, it makes you wonder why on whole earth PGI can't take it...

**Comment by adamjstewart** [comment]
> What prevents you from compiling OpenSSL with gcc and linking it with your code compiled with PGI? You are likely to be better off inter-linking...

Yes, that's the solution I ended up using.

I'm not familiar with this community, but has there been any talk about converting the project to build with CMake or Autotools? That would probably solve the problem of the PGI compiler not working.

**Comment by richsalz** [comment]
https://www.openssl.org/docs/faq.html#MISC5

**Comment by levitte** [comment]
A note: nothing stops you from creating your own config entry (I'd recommend you have it in a separate config file) for the PGI compiler.  Have a look in `Configurations/` for READMEs and what there is now.

**Comment by mattcaswell** [comment]
Issue was resolved. Closing this.
