### ISSUE TITLE
Release of v1.0.2q is actually 1.0.2j?

### ISSUE THREAD

**Issue by RikeKroeger** [openssl/openssl#9161]
I downloaded and installed the zip archive for Release 1.0.2q and tried to use OpenSSL in my build. It outputs that it can only find OpenSSL v1.0.2j in the folder..?

**Comment by mspncp** [comment]
> I downloaded and installed the zip archive for Release 1.0.2q and tried to use OpenSSL in my build.

Which zip archive do you mean? We only provide tarballs `*.tar.gz`  for [download](https://www.openssl.org/source)

> It outputs that it can only find OpenSSL v1.0.2j in the folder..?

Who is ['It'](https://www.amazon.com/Five-Children-Puffin-Classics-Nesbit/dp/014132161X/ref=sr_1_1?crid=5NS98DQS8QX3&keywords=five+children+and+it&qid=1560511670&s=gateway&sprefix=five+child%2Caps%2C365&sr=8-1)?

**Comment by RikeKroeger** [comment]
I downloaded the file from: https://github.com/openssl/openssl/releases/tag/OpenSSL_1_0_2q
"It" is cmake, I guess. I was trying to build libcurl.

**Comment by mspncp** [comment]
> I downloaded the zip file from: https://github.com/openssl/openssl/releases/tag/OpenSSL_1_0_2q
> "It" is cmake, I guess. I was trying to build libcurl.
> 
> Oh, and thanks for the quick reply.

Oh, I see. You downloaded a snapshot of the release tag from GitHub.  I tried it, too, and I couldn't reproduce your issue: the zip file contained a folder named `openssl-OpenSSL_1_0_2q`.

Actually, our official download site is on 


Please also note that the most current release of OpenSSL 1.0.2 is 1.0.2.s, which you can [download here](https://www.openssl.org/source/).

**Comment by mspncp** [comment]
Ups, I hit the `Comment` button prematurely. So I had to edit my post...

**Comment by mattcaswell** [comment]
Where did you install OpenSSL to? Usually it won't replace the system version (and in fact I would advice not to do that). So quite likely curl is picking up that system version. You need to tell curl where to find the new version. That's probably a question for the curl guys.

**Comment by RikeKroeger** [comment]
Thanks everyone for the quick help. I will have a closer look at the build settings for curl.
