### ISSUE TITLE
CRYPO_128_wrap with 8-byte key

### ISSUE THREAD

**Issue by mred1234** [openssl/openssl#9167]
The CRYPTO_128_wrap and CRYPTO_128_unwrap functions are not reversible with an 8 byte key. 

CRYPTO_128_wrap will correctly wrap this, however, the unwrap function will not accept the 16-byte wrapped key, as the length is decremented to 8 before testing the length of (inlen < 16).

I also wonder whether the test for (inlen > CRYPTO128_WRAP_MAX) in CRYPTO_128_wrap might better be CRYPTO128_WRAP_MAX-8, so the wrapped length remains less that (1UL << 31), but the logic is still reversible between the wrap and unwrap functions.

**Comment by bernd-edlinger** [comment]
I don't quite see your point.  CRYPTO_128_wrap produces inlen+8 result,
the shortest input is 16 bytes, and produces 24 bytes out.
therefore the CRYPTO_128_unwrap reverses the 24 bytes output to produce the 16 byte original
input.

**Comment by mred1234** [comment]
The shortest may correctly be 16 bytes, however CRYPTO_128_WRAP allows for 8 bytes

    if ((inlen & 0x7) || (inlen < 8) || (inlen > CRYPTO128_WRAP_MAX))
        return 0;

Should this not be "< 16" in that case

**Comment by bernd-edlinger** [comment]
at master the check at CRYPTO_128_wrap looks differently:
https://github.com/openssl/openssl/blob/7f02a0932c8c182bc2f6320748d81e86d650c1a6/crypto/modes/wrap128.c#L55-L56
not sure if that needs to be fixed in 1.0.2

**Comment by mred1234** [comment]
I am using FIPS module, so cannot currently upgrade, so it would be good to have this changed. 
Thank you
