### ISSUE TITLE
result of `openssl verify -trusted X -partial_chain X` has changed between 1.0.2 and 1.1.1

### ISSUE THREAD

**Issue by YushengYangRTI** [openssl/openssl#9171]
Attached reproducer non-self-signed certificate:
[peer1ECdsa.txt](https://github.com/openssl/openssl/files/3298283/peer1ECdsa.txt)

1.0.2o result:

```
$ openssl verify -trusted peer1ECdsa.txt -partial_chain peer1ECdsa.txt    
peer1ECdsa.txt: C = US, ST = CA, O = Real Time Innovations, CN = dtlsexampleECdsa, emailAddress = meECdsa@rti.com    
error 20 at 0 depth lookup:unable to get local issuer certificate
```

1.1.1b result:

```
$ openssl verify -trusted peer1ECdsa.txt -partial_chain peer1ECdsa.txt    
peer1ECdsa.txt: OK
```

Why the difference in behavior? According to https://www.openssl.org/docs/man1.1.0/man1/verify.html:

> Firstly a certificate chain is built up starting from the supplied certificate and ending in the root CA. It is an error if the whole chain cannot be built up. The chain is built up by looking up the issuers certificate of the current certificate.

On the one hand, since the chain is trivial and consists of just one certificate (trusted file = certificate file), we have successfully built up the chain. On the other hand, the way we built up the chain has failed (issuer of certificate file hasn't been found). So I'm not sure which behavior is correct.

**Comment by bernd-edlinger** [comment]
X509_STORE_CTX_trusted_stack is not working with X509_V_FLAG_PARTIAL_CHAIN

**Comment by bernd-edlinger** [comment]
So 1.0.2 is buggy, while 1.1.1 does it right.

**Comment by YushengYangRTI** [comment]
Thank you!
