### ISSUE TITLE
why windows openssl obj file has contain file path ?

### ISSUE THREAD

**Issue by YanAnzouyijun** [openssl/openssl#9180]
hello, i have compiled the windows openssl static lib(libcrypto.lib) with visual studio vs2017.
but i have encountered that the the obj files such as X509_vfy.obj(you can think the obj1.obj as X509_vfy.obj in the picture). 
![](https://img-blog.csdn.net/20160910012806752?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)
could you tell me why this happen ? does any compile option has caused this ？

**Comment by levitte** [comment]
That's the debug section, so it's debugging information.

**Comment by YanAnzouyijun** [comment]
@levitte  do you know how to remove the file path ?
the configure command is 
``` shell
perl Configure VC-WIN32 no-shared
```
and the compile  is 
``` shell
cl /Fdossl_static.pdb ／MT ／Zl /Gs0 /GF /Gy /W3 /wd4090 /nologo /O2 /WX /I "." /I "include" .... /Zs /showincludes "ssl\statem\statem.c" 2>&1 >ssl\statem\statem.d
```

**Comment by YanAnzouyijun** [comment]
@levitte  hello ,i do not use 
``` shell
perl Configure debug-VC-WIN32 no-shared
```
and i have remove the /Zi and /debug compile option in the makefile. why the obj file also have the file path ?
do you know why ? i am not familiar with the visual studio ...

**Comment by vszakats** [comment]
Debug symbols aside, the binaries will still contain source code paths by default. To disable this, use `no-filenames` option with `Configure`.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
