### ISSUE TITLE
Sending errors in multiple calls

### ISSUE THREAD

**Issue by not-thanos** [openssl/openssl#9183]
OpenSSL 1.1.1c-dev

I have an SSL object with a BIO pair in a server and a client application with deliberately different cipher suites set to make the handshake between them fail.
During the handshake a `no shared cipher` error occurs at the server as expected, which then must be sent to the client in a non-application alert record if I understand it correctly.

However, if the alert cannot be sent in a single call (in this case because of a ridiculously small write buffer set for the BIO pair), then no further calls (to `SSL_do_handshake` or others) are possible to send the remainder of the error.

I would be expecting an `SSL_ERROR_WANT_WRITE` until the entire record is out, and _then_ set the error, or perhaps I'm missing something?

**Comment by mattcaswell** [comment]
> I would be expecting an SSL_ERROR_WANT_WRITE until the entire record is out, and then set the error, or perhaps I'm missing something?

We don't support that. Nor do I feel it is really needed. Alerts are so small that if we really fail to send them in one go then giving up seems like a reasonable thing to do.
