### ISSUE TITLE
multi-threading documentation for 1.0.2 is gone

### ISSUE THREAD

**Issue by bagder** [openssl/openssl#9189]
The URL that previously existed at `https://www.openssl.org/docs/man1.0.2/crypto/threads.html#DESCRIPTION` is now a 404 and the information is nowhere to be found.

This seems rather premature as there's a whole world still using this OpenSSL version and they/we might still need to learn how to use it. This includes users of libcurl when they use older openssl versions and we in the curl project refer to the above mentioned URL for people to learn the details.

Is this information now available on another URL?

**Comment by levitte** [comment]
It is available through any of the function names it describes, such as https://www.openssl.org/docs/man1.0.2/crypto/CRYPTO_lock.html...  one would think that `threads.html` should still work, though.  I'll have a look at that later today.

**Comment by levitte** [comment]
I have a fixup prepared in https://github.com/openssl/web/pull/132
