### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [openssl/openssl#919]
I would like to point out that identifiers like "[`_E_AFALG_H_`](https://github.com/openssl/openssl/blob/a193388811db7e842ed7d1966bbe2552095b26cc/engines/afalg/e_afalg.h#L55)" and "[`__PPC_ARCH_H__`](https://github.com/openssl/openssl/blob/81eae077ce679c1d7d29e19991bf055e4888a2fc/crypto/ppc_arch.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by richsalz** [comment]
Can you provide some specifics?  Our public files are fine, and a quick find/xargs/grep didn't see anything amiss.

**Comment by elfring** [comment]
How do you think about to make [the mentioned include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") also [standard complaint](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by richsalz** [comment]
shrug.  not a big deal since oyou can't compile openssl with C++ now anyway, but sure.  make a PR.

**Comment by richsalz** [comment]
@mattcaswell might as well:  see gitlab :)

**Comment by levitte** [comment]
The same rules apply in C as well.  The C++ standard is based on the C standard in this regard.  The guideline is simple, anything starting with an underscore is reserved for the compiler suite implementation, as well as anything that includes a double underscore somewhere.

The risk we take everytime we define anything starting with an underscore is that it might clash with something the compiler defines, now or in the future.

That being said, I would be strongly surprised if any compiler would define `_E_AFALG_H_` or `__PPC_ARCH_H__` unless it was out of pure spite ;-)  ...  and then, it's in non-public header files.  That makes this issue *very* low priority, to be revisited at a later time if someone reminds us.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by richsalz** [comment]
fixed in 04473165815e93c8453f6c0b55a5dd0b93f668fa  thank you!

**Comment by elfring** [comment]
Thanks for [the renaming of two include guards](https://github.com/openssl/openssl/commit/04473165815e93c8453f6c0b55a5dd0b93f668fa "Safer include guards").

Are there [a few update candidates left over](https://github.com/openssl/openssl/blob/b1322259d93cf6b6286f9febcd468b6a9f577d91/crypto/sparc_arch.h#L10 "More update candidates?")?

**Comment by richsalz** [comment]
Can we skip the guessing games? ☺
