### ISSUE TITLE
openssl engine command example does not parse

### ISSUE THREAD

**Issue by eaaltonen** [openssl/openssl#9198]
Found in  OpenSSL 1.1.1a

The example provided `README.ENGINE` for probing the list of command by "foo" engine does not match the parsing code.

Provided example is
```
openssl engine -vvvv dynamic
...
```

While a command that actually works has the order changed
```
openssl engine dynamic -vvvv
...
```

Reproducing the problem requires an engine, for example [tpm2tss](https://github.com/tpm2-software/tpm2-tss-engine).

### Fix Notes

Fix should either
* Change the example command and the usage of `openssl engine -help` consistent with the parsing code.
* Change parsing code to be consistent with example command and usage.

Can't say which option is correct.

**Comment by levitte** [comment]
I checked that with 1.1.1d just now, and it accepts both variants.
