### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [openssl/openssl#920]
Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html "Change a signal action.") ⇒ [OPENSSL_cpuid_setup](https://github.com/openssl/openssl/blob/984d6c6052169bcae8010de33f7796e455536d61/crypto/armcap.c#L89)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [OPENSSL_INIT_set_config_filename](https://github.com/openssl/openssl/blob/691064c47fd6a7d11189df00a0d1b94d8051cbe0/crypto/conf/conf_lib.c#L390)

**Comment by mattcaswell** [comment]
The second of these issues has been fixed in commit dae00d63.

**Comment by richsalz** [comment]
applications are not supposed to call that routine, and it's written in assembler and cant fail.
closing this.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?

**Comment by richsalz** [comment]
Thanks for the feedback.  This is not a general case of ignoring return values, it's a specific CPU-specific thing.   And we do static analysis and fuzzing.

**Comment by elfring** [comment]
Do you categorise [a missed check for the return value from a call of a function like "sigaction"](https://github.com/openssl/openssl/blob/d2e9e320186f0917cc940f46bdf1a7e4120da9b0/crypto/armcap.c#L98 "Update candidate: OPENSSL_cpuid_setup()") as uninteresting?

**Comment by richsalz** [comment]
As a general rule, we are concerned about checking the return values of functions.  In this *particular* case, which is for a few *specific environments* it is okay.

**Comment by elfring** [comment]
I would prefer that the error detection and corresponding exception handling will become more complete also for the mentioned specific environments. Can this software still be improved there?

**Comment by richsalz** [comment]
Bring it up on openssl-dev mailing list (see https://mta.openssl.org/mailman/listinfo/openssl-dev to join) and maybe you can convince me :)

**Comment by elfring** [comment]
How are the chances to adjust your view about the reported implementation detail better by a mailing list interface better than this issue tracker?

**Comment by richsalz** [comment]
Not everyone on the mailing list reads all the issue tracker.   Maybe you can find other people there who agree with you.

**Comment by elfring** [comment]
* Do the mentioned source code analysis tools indicate function calls like the discussed one for further considerations?
* How do you think about to annotate any more functions with [an attribute like "`warn_unused_result`"](https://gcc.gnu.org/onlinedocs/gcc-6.1.0/gcc/Common-Function-Attributes.html#index-g_t_0040code_007bwarn_005funused_005fresult_007d-function-attribute-3260 "Warn about unused function result?")?

**Comment by richsalz** [comment]
Please use the mailing list.  I'm done responding here.

**Comment by mattcaswell** [comment]
We use Coverity, and yes it does indicate unused results. We do already have some limited use of `__warn_unused_result__`. From e_os2.h:
````
# ifdef DEBUG_UNUSED
#  define __owur __attribute__((__warn_unused_result__))
# else
#  define __owur
# endif
````
libssl, evp and ct are pretty well covered. Not much else.
