### ISSUE TITLE
some value in  BN_generate_dsa_nonce should be cleaned

### ISSUE THREAD

**Issue by xxggsh** [openssl/openssl#9205]
In the BN_generate_dsa_nonce function, SHA512 is called for hash calculation. The function does not call Openssl_cleanse to clean SHA512_CTX and digest, which may contain sensitive data. such as called by  dsa_sign_setup. In which the relating output value was subsequently cleared by  BN_clear_free(k). I think in some situations,this may cause information leak.
  SHA512_Init(&sha);
  SHA512_Update(&sha, &done, sizeof(done));
  SHA512_Update(&sha, private_bytes, sizeof(private_bytes));
  SHA512_Update(&sha, message, message_len);
  SHA512_Update(&sha, random_bytes, sizeof(random_bytes));
  SHA512_Final(**digest**, &**sha**);

**Comment by richsalz** [comment]
The intermediate state of SHA is only the digest value.  What private information do you think is there?  I think you're wrong.

**Comment by xxggsh** [comment]
In the function of    dsa_sign_setup, it call the BN_generate_dsa_nonce by
 if (!BN_generate_dsa_nonce(k, dsa->q, dsa->priv_key, dgst,
                                       dlen, ctx))
and finally  call   BN_clear_free(k);  to clear the memory of k.  In the BN_generate_dsa_nonce ,the memory relates to k is  including the intermediate state of SHA ,is still  not cleared.

**Comment by richsalz** [comment]
You cannot create K from the internal state of SHA processing.

**Comment by xxggsh** [comment]
the digest value of  in BN_generate_dsa_nonce  was also not cleared .
SHA state was  left open just after the last SHA512_Final  call,can't it be infered from it?

**Comment by richsalz** [comment]
no, you cannot take SHA value and generate the input source from that.

**Comment by xxggsh** [comment]
I know I cannot generate the input source. I mean the value of the specified digest is also sensitive .which was used by dsa_sign_setup

**Comment by richsalz** [comment]
Maybe I don't understand your point, I am sorry about the language difficulties we are having.

I suppose ```private_bytes``` should be cleansed.  Are you saying that since the nonce is private to the signature the digest (which creates the nonce) should be cleansed?

**Comment by xxggsh** [comment]
Yes ,I think nonce (k value of dsa_sign_setup) is import to the security of dsa algorithm and it should be cleansed.

**Comment by richsalz** [comment]
Okay, now I understand; thanks for your patience.  Yes keeping ```k``` secret is important.  Not sure there's any way to cleanse an existing SHA state so a PR might be a bit of work.

**Comment by slontis** [comment]
The internal state is cleared when the EVP_MD_CTX is freed via a call to CRYPTO_clear_free (e.g on the SHA512_CTX).
BN_generate_dsa_nonce() does use a few buffers that should be cleared so I will add a PR related to this..
