### ISSUE TITLE
extremely slow with client certificates

### ISSUE THREAD

**Issue by noktilux** [openssl/openssl#9221]
After a recent update on an Ubuntu 18.04 Server (running Apache/2.4.29), processing of EVERY https transaction takes about 30 seconds when using a client-side certificate.

The issue appears to be with OpenSSL 1.1.1  11 Sep 2018.

No issues on a different server, running same Apache but OpenSSL 1.1.0g  2 Nov 2017.

**Comment by kroeckx** [comment]
As far as I know, you need at least apache 2.4.37 to work properly
with OpenSSL 1.1.1.

**Comment by noktilux** [comment]
> As far as I know, you need at least apache 2.4.37 to work properly with OpenSSL 1.1.1.

I just tried on another serevr where I was able to replicate the issue and upgrading Apache to 2.4.39 ultimately fixed the problem, BUT created another which had to be resolved by adding/editing...

SSLProtocol -ALL +TLSv1.2

to:  /etc/apache2/mods-enabled/ssl.conf

reference:
https://stackoverflow.com/questions/53062504/apache-2-4-37-with-openssl-1-1-1-cannot-perform-post-handshake-authentication

**Comment by fredbcode** [comment]
Hi @noktilux , I found no bug reports on Ubuntu, this is a known issue ? How did you use OpenSSL 1.1.0 with apache /2.4.29 (recompilation ?)

**Comment by fredbcode** [comment]
FYI: Ubuntu https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1833039
