### ISSUE TITLE
About AEAD in command line.

### ISSUE THREAD

**Issue by jyxjjj** [openssl/openssl#9222]
Why does openssl 1.0.2 has AEAD in enc command but openssl 1.1.0 doesn't.

**Comment by mattcaswell** [comment]
1.0.2 does not support AEAD in enc. This is the code in 1.0.2 that checks this:

https://github.com/openssl/openssl/blob/7a7afc559ebc0ad88390cc62bfc34c221d595831/apps/enc.c#L341-L344

**Comment by jyxjjj** [comment]
@mattcaswell But i found in the command line (sorry for no screenshot)
And I just know 1.1.0 doesn't.
I truely found the "openssl will not support aead in command line and even future" words.
But I truely found the "aes-256-gcm" in 1.0.2 command line outputs too.
(I can't found when i use correct command, lt's in the error output.)
 (sorry for no screenshot)

**Comment by richsalz** [comment]
The command runs, but it is silently wrong.  Later releases warned that it doesn't work.

**Comment by paulidale** [comment]
Closing this since AEAD ciphers don't work from the command line and never have.
