### ISSUE TITLE
Add possibility to exclude specific symbols from doc-nits check

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#9226]
In pull request #9224, it turned out that it would be convenient to explicitly disable the doc-nits check for specific symbols in certain sections. For example, one might want to add symbols to the NAMES section without providing a corresponding SYNOPSIS (see https://github.com/openssl/openssl/pull/9224#pullrequestreview-253143415). Currently, the only way to avoid doc-nit errors is to add a `=for comment generic` line. This however has the disadvantage that it disables the synopsis check completely, which is inconvenient when additional symbols are added later on to the pod file. It would be nicer if one could add just add a specific exclusion list (like `OSSL_TRACEV`, `OSSL_TRACE3`, `OSSL_TRACE4`, ... `OSSL_TRACE8`). 

See also the discussions in #9095.

**Comment by richsalz** [comment]
Would putting ```=for comment undocumented xxxx``` in the synopsis section fool doc-nits to not complain about xxxx?

**Comment by mspncp** [comment]
> Would putting `=for comment undocumented xxxx` in the synopsis section fool doc-nits to not complain about xxxx?

Oh, I missed that question somehow. I‘ll check that on the next occasion.
