### ISSUE TITLE
Consider removing SRP support

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9235]
SRP was never a standards-track RFC.  The IETF is working on new password-based schemes (see CFRG PAKE discussions).

See also #3055

**Comment by mattcaswell** [comment]
SRP itself *is* standards track (RFC2945). Its implementation in TLS is an informational RFC (RFC5054).

**Comment by richsalz** [comment]
That's a good clarification, thank you.  Would you be interested in a PR that removes it from TLS?

**Comment by mattcaswell** [comment]
I think it is too significant a change. My guess is that people are using this. But I could be wrong.

**Comment by kaduk** [comment]
> see CFRG PAKE discussions

Like https://mailarchive.ietf.org/arch/msg/cfrg/0NkxnEUC2wjK_2htsl9okitbNmE , which maybe implies that TLS+SRP is being used already and a replacement sought?

**Comment by beldmit** [comment]
In an ideal world TLS+SRP (and TLS+GOST too :) ) should go to a separate provider.

**Comment by richsalz** [comment]
It wasn't clear to me from the CFRG email if it was being used now or they wanted to use the PAKE equivalent, so I asked folks at Amazon.  "Not a part of our mainline services, but we do have a few places where it is being used."

Close this if you want.

**Comment by mattcaswell** [comment]
I think this should be closed.

**Comment by SkyperTHC** [comment]
I've noticed that srp.h has been removed from OpenSSL. Our project (gsocket.io) depends on it. Will it be back? Is there a replacement?

**Comment by t8m** [comment]
srp.h was not removed. Just the functionality in there was deprecated. You need to build openssl without no-deprecated configure option.
