### ISSUE TITLE
Incorrect status for setting SSL version

### ISSUE THREAD

**Issue by legendtang** [openssl/openssl#9238]
It seems that https://github.com/openssl/openssl/blob/3c83c5ba4f6502c708b7a5f55c98a10e312668da/test/ssltest_old.c#L862 may get invalid status `INT_MAX`, from `SSL_ctrl()` calls `BIO_ctrl()` (https://github.com/openssl/openssl/blob/master/ssl/bio_ssl.c) calls `BIO_nread0()` (can return `INT_MAX`).

My point is, can I still use `SSL_ctrl()`'s return code to determine if an error occurred or this is not your intention?

**Comment by RameshwarapuSanthosh** [comment]
Here set_protocol_version is setting both the SSL_CTRL_SET_MIN_PROTO_VERSION & SSL_CTRL_SET_MAX_PROTO_VERSION using SSL_ctrl, where [ssl_check_allowed_versions && ssl_set_version_bound] are bound to return 0/1 depending on the operation status. The internal implementation of ssl_check_allowed_versions & ssl_set_version_bound also return 0/1.

The same has been followed in case of SSL_CTX_set_min_proto_version/SSL_CTX_set_max_proto_version -> SSL_CTX_ctrl, where the CTX_min/max version is set. And no operation is found to be performed on the return codes, while returning to the calling function.

Please correct me, if I'm wrong.

**Comment by saik-intel** [comment]
Hi @legendtang legendtang, We have reviewed the code set_protocol_version and it will call to SSL_ctrl for SSL_CTRL_SET_MIN_PROTO_VERSION & SSL_CTRL_SET_MAX_PROTO_VERSION. For both cases SSL_ctrl is taking care to return as 0/1. Hence it wont get wrong return status. Please check and close this bug as applicable.
