### ISSUE TITLE
padlock engine cannot be disabled in OpenSSL 1.1.1

### ISSUE THREAD

**Issue by vladak** [openssl/openssl#9244]
The `no-hw-padlock` Configure option does not work on 1.1.1 - the engine is always built (discovered via relocation errors in `e_padlock-x86.o` but that's not important here as I don't want to build the engine anyway). Tried the `no-hw` option, same thing. So, this is basically a request to get cset 469ce8ff (PR #8380) backported to the `OpenSSL_1_1_1-stable` branch.

**Comment by levitte** [comment]
It turns out that this is an omission in engines/build.info.  Fix coming up!

**Comment by levitte** [comment]
#9572

**Comment by levitte** [comment]
#9572 is now in.

**Comment by vladak** [comment]
Thanks !
