### ISSUE TITLE
Replace nettle crypto library with openssl crypto library

### ISSUE THREAD

**Issue by RohanKurane** [openssl/openssl#9245]
HI, 
I want to replace the usage of nettle cryptographic library and its functions with OpenSSL for its FIPS compliance. What is the best way of going about this ? Is there any example code I can look up ? 
@mattcaswell 

I use the following headers for nettle today - 
#include <nettle/aes.h>
#include <nettle/pbkdf2.h>
#include <nettle/cbc.h>
#include <nettle/hmac.h>
#include <nettle/sha3.h>

Is there a 1 to 1 replacement for them in OpenSSL ?

Thanks
Rohan

**Comment by mattcaswell** [comment]
Unfortunately I really don't know anything about nettle so I'm not in a position to advise about migration from one to the other.

Note that standard out-of-the-box OpenSSL is not FIPS compliant. You can build a FIPS capable version of OpenSSL 1.0.2 and use it with the OpenSSL FIPS Object Module 2.0, which is FIPS compliant. But note that OpenSSL 1.0.2 is EOL at the end of this year. We are currently developing OpenSSL 3.0 which will have a built-in FIPS module - but validation of that is some way off yet.

**Comment by RohanKurane** [comment]
@mattcaswell I am planning to use 1.0.2g so I think that should be good. 
I am looking at how to replace the nettle functions with the corresponding openssl functions in 1.0.2g. Unfortunately the openssl documentation is not the best out there. :(

**Comment by levitte** [comment]
Nettle an OpenSSL are two different libraries, and you cannot treat them as drop in replacement for each other. Switching from one to the other requires a certain amount of code rewrite (even though the overall logic probably stays the same).
I can understand that our documentation is a bit intimidating, considering that ours comes in form of man pages while nettle uses the texinfo format.
We do have a set of primitives, just like nettle, such as RSA functions, AES functions, etc, but there are some algorithms in nettle that we don't implement and vice versa. We would like to *encourage* you to have a look at our EVP API, though, as that's where our future development goes. The EVP API is a sort of umbrella API with the primitives as backends.

Other than that, I do not know what else to say at this stage. I assume you will want to ask more detailed questions later, kind of "how do I...". You can do that on openssl-users@openssl.org (see https://www.openssl.org/community/mailinglists.html for mailing list details) or here.

**Comment by RohanKurane** [comment]
@mattcaswell 
I think I have the code changes done that satisfy what I need to replace the existing nettle cryptographic functions with openssl. They are certainly not 1 to 1 and need some adjustment. I think I've been able to do that. I am still testing my application since this is a sensitive change. I'll keep you updated. Thanks!

**Comment by levitte** [comment]
Glad to hear it!

**Comment by RohanKurane** [comment]
@levitte @mattcaswell  - testing some more. I will keep you both updated

**Comment by RohanKurane** [comment]
Hey @levitte @mattcaswell This thing actually seems to work. 
How can I contribute here if any way ?

**Comment by mattcaswell** [comment]
> How can I contribute here if any way ?

Take a look at the CONTRIBUTING file for information:
https://github.com/openssl/openssl/blob/master/CONTRIBUTING

**Comment by levitte** [comment]
Also depends on what you want to contribute.  If you want to add advice on how to switch from Nettle to OpenSSL, our [wiki](https://wiki.openssl.org/) may be a more suitable place.

**Comment by RohanKurane** [comment]
@mattcaswell  I think what @levitte suggested sounds good. I will take a look at the wiki
